Terraria: System.Diagnostics.Tracing.EventSource.WriteEventWithRelatedActivityIdCore
WriteEventWithRelatedActivityIdCore()
unsafe void System.Diagnostics.Tracing.EventSource.WriteEventWithRelatedActivityIdCore (int eventId, Guid * relatedActivityId, int eventDataCount, EventData * data) inline protected inherited
Definition at line 970 of file EventSource.cs.
    {
        if (!IsEnabled())
        {
            return;
        }
        try
        {
            ref EventMetadata reference = ref m_eventData[eventId];
            EventOpcode opcode = (EventOpcode)reference.Descriptor.Opcode;
            Guid* ptr = null;
            Guid activityId = Guid.Empty;
            Guid relatedActivityId2 = Guid.Empty;
            if (opcode != 0 && relatedActivityId == null && (reference.ActivityOptions & EventActivityOptions.Disable) == 0)
            {
                switch (opcode)
                {
                case EventOpcode.Start:
                    m_activityTracker.OnStart(m_name, reference.Name, reference.Descriptor.Task, ref activityId, ref relatedActivityId2, reference.ActivityOptions);
                    break;
                case EventOpcode.Stop:
                    m_activityTracker.OnStop(m_name, reference.Name, reference.Descriptor.Task, ref activityId);
                    break;
                }
                if (activityId != Guid.Empty)
                {
                    ptr = &activityId;
                }
                if (relatedActivityId2 != Guid.Empty)
                {
                    relatedActivityId = &relatedActivityId2;
                }
            }
            if (!SelfDescribingEvents)
            {
                if (reference.EnabledForETW && !m_etwProvider.WriteEvent(ref reference.Descriptor, reference.EventHandle, ptr, relatedActivityId, eventDataCount, (IntPtr)data))
                {
                    ThrowEventSourceException(reference.Name);
                }
                if (reference.EnabledForEventPipe && !m_eventPipeProvider.WriteEvent(ref reference.Descriptor, reference.EventHandle, ptr, relatedActivityId, eventDataCount, (IntPtr)data))
                {
                    ThrowEventSourceException(reference.Name);
                }
            }
            else if (reference.EnabledForETW || reference.EnabledForEventPipe)
            {
                EventSourceOptions eventSourceOptions = default(EventSourceOptions);
                eventSourceOptions.Keywords = (EventKeywords)reference.Descriptor.Keywords;
                eventSourceOptions.Level = (EventLevel)reference.Descriptor.Level;
                eventSourceOptions.Opcode = (EventOpcode)reference.Descriptor.Opcode;
                EventSourceOptions options = eventSourceOptions;
                WriteMultiMerge(reference.Name, ref options, reference.TraceLoggingEventTypes, ptr, relatedActivityId, data);
            }
            if (m_Dispatchers != null && reference.EnabledForAnyListener)
            {
                EventWrittenEventArgs eventCallbackArgs = new EventWrittenEventArgs(this, eventId, ptr, relatedActivityId);
                WriteToAllListeners(eventCallbackArgs, eventDataCount, data);
            }
        }
        catch (Exception ex)
        {
            if (ex is EventSourceException)
            {
                throw;
            }
            ThrowEventSourceException(m_eventData[eventId].Name, ex);
        }
    }
References System.Guid.Empty, System.Diagnostics.Tracing.EventSource.IsEnabled(), System.Diagnostics.Tracing.EventSource.m_activityTracker, System.Diagnostics.Tracing.EventSource.m_Dispatchers, System.Diagnostics.Tracing.EventSource.m_etwProvider, System.Diagnostics.Tracing.EventSource.m_eventData, System.Diagnostics.Tracing.EventSource.m_eventPipeProvider, System.Diagnostics.Tracing.EventSource.m_name, System.Diagnostics.Tracing.EventSource.Name, System.Diagnostics.Tracing.ActivityTracker.OnStart(), System.Diagnostics.Tracing.ActivityTracker.OnStop(), System.options, System.Diagnostics.Tracing.EventSource.SelfDescribingEvents, System.Diagnostics.Tracing.EventSource.ThrowEventSourceException(), System.Diagnostics.Tracing.EventSource.WriteMultiMerge(), and System.Diagnostics.Tracing.EventSource.WriteToAllListeners().
Referenced by System.Threading.Tasks.TplEventSource.AwaitTaskContinuationScheduled(), System.Threading.Tasks.TplEventSource.TaskScheduled(), System.Threading.Tasks.TplEventSource.TaskWaitBegin(), and System.Diagnostics.Tracing.EventSource.WriteEventCore().