Terraria: System.Diagnostics.Tracing.EventSource.GetGuid
GetGuid()
static Guid System.Diagnostics.Tracing.EventSource.GetGuid (Type eventSourceType) inline static inherited
Definition at line 330 of file EventSource.cs.
    {
        if (eventSourceType == null)
        {
            throw new ArgumentNullException("eventSourceType");
        }
        EventSourceAttribute eventSourceAttribute = (EventSourceAttribute)GetCustomAttributeHelper(eventSourceType, typeof(EventSourceAttribute));
        string name = eventSourceType.Name;
        if (eventSourceAttribute != null)
        {
            if (eventSourceAttribute.Guid != null && Guid.TryParse(eventSourceAttribute.Guid, out var result))
            {
                return result;
            }
            if (eventSourceAttribute.Name != null)
            {
                name = eventSourceAttribute.Name;
            }
        }
        if (name == null)
        {
            throw new ArgumentException(SR.Argument_InvalidTypeName, "eventSourceType");
        }
        return GenerateGuidFromName(name.ToUpperInvariant());
    }
References System.SR.Argument_InvalidTypeName, System.Diagnostics.Tracing.EventSource.GenerateGuidFromName(), System.Diagnostics.Tracing.EventSource.GetCustomAttributeHelper(), and System.Guid.TryParse().
Referenced by System.Diagnostics.Tracing.EventSource.EventSource(), and System.Diagnostics.Tracing.EventSource.CreateManifestAndDescriptors().