Terraria: System.Diagnostics.Tracing.EventSource.AddEventDescriptor
AddEventDescriptor()
static void System.Diagnostics.Tracing.EventSource.AddEventDescriptor ([NotNull] ref EventMetadata[] eventData, string eventName, EventAttribute eventAttribute, ParameterInfo[] eventParameters, bool hasRelatedActivityID) inline static private inherited
Definition at line 2464 of file EventSource.cs.
    {
        if (eventData.Length <= eventAttribute.EventId)
        {
            EventMetadata[] array = new EventMetadata[Math.Max(eventData.Length + 16, eventAttribute.EventId + 1)];
            Array.Copy(eventData, array, eventData.Length);
            eventData = array;
        }
        ref EventMetadata reference = ref eventData[eventAttribute.EventId];
        reference.Descriptor = new EventDescriptor(eventAttribute.EventId, eventAttribute.Version, (byte)eventAttribute.Channel, (byte)eventAttribute.Level, (byte)eventAttribute.Opcode, (int)eventAttribute.Task, (long)eventAttribute.Keywords | (long)SessionMask.All.ToEventKeywords());
        reference.Tags = eventAttribute.Tags;
        reference.Name = eventName;
        reference.Parameters = eventParameters;
        reference.Message = eventAttribute.Message;
        reference.ActivityOptions = eventAttribute.ActivityOptions;
        reference.HasRelatedActivityID = hasRelatedActivityID;
        reference.EventHandle = IntPtr.Zero;
        int num = eventParameters.Length;
        bool allParametersAreInt = true;
        bool allParametersAreString = true;
        foreach (ParameterInfo parameterInfo in eventParameters)
        {
            Type parameterType = parameterInfo.ParameterType;
            if (parameterType == typeof(string))
            {
                allParametersAreInt = false;
                continue;
            }
            if (parameterType == typeof(int) || (parameterType.IsEnum && Type.GetTypeCode(parameterType.GetEnumUnderlyingType()) <= TypeCode.UInt32))
            {
                allParametersAreString = false;
                continue;
            }
            if (parameterType == typeof(byte[]))
            {
                num++;
            }
            allParametersAreInt = false;
            allParametersAreString = false;
        }
        reference.AllParametersAreInt32 = allParametersAreInt;
        reference.AllParametersAreString = allParametersAreString;
        reference.EventListenerParameterCount = num;
    }
References System.Diagnostics.Tracing.SessionMask.All, System.array, System.Array.Copy(), System.Type.GetTypeCode(), System.Math.Max(), and System.IntPtr.Zero.
Referenced by System.Diagnostics.Tracing.EventSource.CreateManifestAndDescriptors().