Terraria: System.Diagnostics.Tracing.EventSource.WriteEventCore
WriteEventCore()
unsafe void System.Diagnostics.Tracing.EventSource.WriteEventCore (int eventId, int eventDataCount, EventData * data) inline protected inherited
Definition at line 962 of file EventSource.cs.
    {
        WriteEventWithRelatedActivityIdCore(eventId, null, eventDataCount, data);
    }
References System.Diagnostics.Tracing.EventSource.WriteEventWithRelatedActivityIdCore().
Referenced by System.Threading.Tasks.TplEventSource.AwaitTaskContinuationScheduled(), System.Threading.CdsSyncEtwBCLProvider.Barrier_PhaseFinished(), System.Buffers.ArrayPoolEventSource.BufferAllocated(), System.Buffers.ArrayPoolEventSource.BufferDropped(), System.Buffers.ArrayPoolEventSource.BufferRented(), System.Threading.Tasks.ParallelEtwProvider.ParallelInvokeBegin(), System.Threading.Tasks.ParallelEtwProvider.ParallelLoopBegin(), System.Threading.Tasks.ParallelEtwProvider.ParallelLoopEnd(), System.Threading.Tasks.TplEventSource.TaskCompleted(), System.Threading.Tasks.TplEventSource.TaskScheduled(), System.Threading.Tasks.TplEventSource.TaskWaitBegin(), System.Threading.Tasks.TplEventSource.TraceOperationBegin(), System.Threading.Tasks.TplEventSource.TraceSynchronousWorkEnd(), System.Diagnostics.Tracing.EventSource.WriteEvent(), System.Net.Security.NetSecurityTelemetry.WriteEvent(), System.Net.Security.NetSecurityTelemetry.WriteEvent(), System.Net.Http.HttpTelemetry.WriteEvent(), System.Diagnostics.Tracing.EventSource.WriteEvent(), System.Net.Http.HttpTelemetry.WriteEvent(), System.Diagnostics.Tracing.EventSource.WriteEvent(), System.Diagnostics.Tracing.EventSource.WriteEvent(), System.Diagnostics.Tracing.EventSource.WriteEvent(), System.Net.NetEventSource.WriteEvent(), System.Diagnostics.Tracing.EventSource.WriteEvent(), System.Diagnostics.Tracing.EventSource.WriteEvent(), System.Diagnostics.Tracing.EventSource.WriteEvent(), System.Diagnostics.Tracing.FrameworkEventSource.WriteEvent(), System.Diagnostics.Tracing.FrameworkEventSource.WriteEvent(), System.Diagnostics.Tracing.EventSource.WriteEvent(), System.Diagnostics.Tracing.EventSource.WriteEvent(), System.Diagnostics.Tracing.EventSource.WriteEvent(), System.Net.Security.NetSecurityTelemetry.WriteEvent(), System.Net.NetEventSource.WriteEvent(), System.Net.NetEventSource.WriteEvent(), System.Net.NetEventSource.WriteEvent(), System.Net.NetEventSource.WriteEvent(), System.Net.NetEventSource.WriteEvent(), System.Net.NetEventSource.WriteEvent(), System.Net.Http.HttpTelemetry.WriteEvent(), System.Net.NetEventSource.WriteEvent(), System.Net.NetEventSource.WriteEvent(), System.Diagnostics.Tracing.EventSource.WriteEvent(), System.Diagnostics.Tracing.EventSource.WriteEvent(), System.Diagnostics.Tracing.EventSource.WriteEvent(), System.Diagnostics.Tracing.EventSource.WriteEvent(), System.Diagnostics.Tracing.EventSource.WriteEvent(), and System.Diagnostics.Tracing.EventSource.WriteEvent().