Terraria: System.Diagnostics.Tracing.EventSource.AttributeTypeNamesMatch
AttributeTypeNamesMatch()
static bool System.Diagnostics.Tracing.EventSource.AttributeTypeNamesMatch (Type attributeType, Type reflectedAttributeType) inline static private inherited
Definition at line 2138 of file EventSource.cs.
    {
        if (!(attributeType == reflectedAttributeType) && !string.Equals(attributeType.FullName, reflectedAttributeType.FullName, StringComparison.Ordinal))
        {
            if (string.Equals(attributeType.Name, reflectedAttributeType.Name, StringComparison.Ordinal) && attributeType.Namespace.EndsWith("Diagnostics.Tracing", StringComparison.Ordinal))
            {
                return reflectedAttributeType.Namespace.EndsWith("Diagnostics.Tracing", StringComparison.Ordinal);
            }
            return false;
        }
        return true;
    }
References System.Type.FullName, System.Reflection.MemberInfo.Name, and System.Type.Namespace.
Referenced by System.Diagnostics.Tracing.EventSource.AddProviderEnumKind(), System.Diagnostics.Tracing.EventSource.GetCustomAttributeHelper(), and System.Diagnostics.Tracing.EventSource.IsCustomAttributeDefinedHelper().