Terraria: System.Diagnostics.Tracing.EventSource.IsEnabled
IsEnabled() [1/3]
bool System.Diagnostics.Tracing.EventSource.IsEnabled () inline inherited
Definition at line 307 of file EventSource.cs.
    {
        return m_eventSourceEnabled;
    }
References System.Diagnostics.Tracing.EventSource.m_eventSourceEnabled.
Referenced by System.Transactions.CommittableTransaction.CommittableTransaction(), System.Diagnostics.DiagnosticSourceEventSource.FilterAndTransform.FilterAndTransform(), System.Transactions.TransactionScope.TransactionScope(), System.Transactions.TransactionScope.TransactionScope(), System.Transactions.TransactionScope.TransactionScope(), System.Transactions.TransactionScope.TransactionScope(), System.Transactions.TransactionScope.TransactionScope(), System.Transactions.TransactionScope.TransactionScope(), System.Transactions.TransactionScope.TransactionScope(), System.Transactions.SinglePhaseEnlistment.Aborted(), System.Transactions.SinglePhaseEnlistment.Aborted(), System.Net.Sockets.SocketsTelemetry.AcceptFailed(), System.Net.NetEventSource.AcceptSecurityContext(), System.Net.NetEventSource.AcceptSecurityContext(), System.Net.Sockets.SocketsTelemetry.AcceptStart(), System.Net.Sockets.SocketsTelemetry.AcceptStart(), System.Net.Sockets.SocketsTelemetry.AcceptStop(), System.Net.NetEventSource.AcquireCredentialsHandle(), System.Net.NetEventSource.AcquireCredentialsHandle(), System.Net.NetEventSource.AcquireDefaultCredential(), System.Net.NameResolutionTelemetry.AfterResolution(), System.Net.NetEventSource.AttemptingRestartUsingCert(), System.Threading.Tasks.TplEventSource.AwaitTaskContinuationScheduled(), System.Threading.CdsSyncEtwBCLProvider.Barrier_PhaseFinished(), System.Net.NameResolutionTelemetry.BeforeResolution(), System.Transactions.CommittableTransaction.BeginCommit(), System.Net.NetEventSource.CertificateFromDelegate(), System.Net.NetEventSource.CertIsType2(), System.Net.NetEventSource.CertsAfterFiltering(), System.Transactions.TransactionState.ChangeStateAbortedDuringPromotion(), System.Transactions.TransactionState.ChangeStatePromotedAborted(), System.Transactions.TransactionState.ChangeStatePromotedCommitted(), System.Transactions.TransactionState.ChangeStateTransactionAborted(), System.Transactions.TransactionState.ChangeStateTransactionCommitted(), System.Transactions.CommittableTransaction.Commit(), System.Transactions.SinglePhaseEnlistment.Committed(), System.Transactions.DependentTransaction.Complete(), System.Transactions.TransactionScope.Complete(), System.Collections.Concurrent.CDSCollectionETWBCLProvider.ConcurrentBag_TryPeekSteals(), System.Collections.Concurrent.CDSCollectionETWBCLProvider.ConcurrentBag_TryTakeSteals(), System.Collections.Concurrent.CDSCollectionETWBCLProvider.ConcurrentDictionary_AcquiringAllLocks(), System.Collections.Concurrent.CDSCollectionETWBCLProvider.ConcurrentStack_FastPopFailed(), System.Collections.Concurrent.CDSCollectionETWBCLProvider.ConcurrentStack_FastPushFailed(), System.Transactions.TransactionsEtwProvider.ConfiguredDefaultTimeoutAdjusted(), System.Net.Sockets.SocketsTelemetry.ConnectFailed(), System.Net.Sockets.SocketsTelemetry.ConnectStart(), System.Net.Sockets.SocketsTelemetry.ConnectStop(), System.Threading.Tasks.Dataflow.Internal.DataflowEtwProvider.DataflowBlockCompleted(), System.Threading.Tasks.Dataflow.Internal.DataflowEtwProvider.DataflowBlockCreated(), System.Threading.Tasks.Dataflow.Internal.DataflowEtwProvider.DataflowBlockLinking< T >(), System.Threading.Tasks.Dataflow.Internal.DataflowEtwProvider.DataflowBlockUnlinking< T >(), System.Runtime.Serialization.Formatters.Binary.BinaryFormatterEventSource.DeserializationStart(), System.Runtime.Serialization.Formatters.Binary.BinaryFormatterEventSource.DeserializationStop(), System.Runtime.Serialization.Formatters.Binary.BinaryFormatterEventSource.DeserializingObject(), System.Transactions.TransactionScope.Dispose(), System.Transactions.Enlistment.Done(), System.Transactions.CommittableTransaction.EndCommit(), System.Transactions.EnlistableStates.EnlistDurable(), System.Transactions.TransactionsEtwProvider.EnlistmentAborted(), System.Transactions.TransactionsEtwProvider.EnlistmentCommitted(), System.Transactions.TransactionsEtwProvider.EnlistmentDone(), System.Transactions.TransactionsEtwProvider.EnlistmentForceRollback(), System.Transactions.TransactionsEtwProvider.EnlistmentInDoubt(), System.Transactions.TransactionsEtwProvider.EnlistmentPrepared(), System.Transactions.TransactionsEtwProvider.EnlistmentStatus(), System.Transactions.TransactionStateActive.EnlistPromotableSinglePhase(), System.Transactions.TransactionStatePhase0.EnlistPromotableSinglePhase(), System.Transactions.TransactionStateActive.EnlistVolatile(), System.Transactions.TransactionStatePhase0.EnlistVolatile(), System.Transactions.TransactionStatePromotedNonMSDTCBase.EnlistVolatile(), System.Transactions.TransactionStateActive.EnlistVolatile(), System.Transactions.TransactionStatePhase0.EnlistVolatile(), System.Transactions.TransactionStatePromotedNonMSDTCBase.EnlistVolatile(), System.Transactions.DurableEnlistmentAborting.EnterState(), System.Transactions.DurableEnlistmentCommitting.EnterState(), System.Transactions.VolatileEnlistmentAborting.EnterState(), System.Transactions.VolatileEnlistmentCommitting.EnterState(), System.Transactions.VolatileEnlistmentInDoubt.EnterState(), System.Transactions.VolatileEnlistmentPreparing.EnterState(), System.Transactions.VolatileEnlistmentSPC.EnterState(), System.Transactions.TransactionStateAborted.EnterState(), System.Transactions.TransactionStateCommitted.EnterState(), System.Transactions.TransactionStateDelegatedAborting.EnterState(), System.Transactions.TransactionStateDelegatedBase.EnterState(), System.Transactions.TransactionStateDelegatedCommitting.EnterState(), System.Transactions.TransactionStateDelegatedNonMSDTC.EnterState(), System.Transactions.TransactionStateInDoubt.EnterState(), System.Transactions.TransactionStatePromoted.EnterState(), System.Transactions.TransactionStatePromotedAborted.EnterState(), System.Transactions.TransactionStatePromotedCommitted.EnterState(), System.Transactions.TransactionStatePromotedIndoubt.EnterState(), System.Transactions.TransactionStatePromotedNonMSDTCAborted.EnterState(), System.Transactions.TransactionStatePromotedNonMSDTCCommitted.EnterState(), System.Transactions.TransactionStatePromotedNonMSDTCIndoubt.EnterState(), System.Transactions.TransactionStatePromotedNonMSDTCSinglePhaseCommit.EnterState(), System.Net.NetEventSource.EnumerateSecurityPackages(), System.Transactions.TransactionsEtwProvider.ExceptionConsumed(), System.Transactions.TransactionsEtwProvider.ExceptionConsumed(), System.Threading.Tasks.AwaitTaskContinuation.Execute(), System.Net.NetEventSource.FindingMatchingCerts(), System.Transactions.PreparingEnlistment.ForceRollback(), System.Transactions.PreparingEnlistment.ForceRollback(), System.Net.NetEventSource.FoundCertInStore(), System.Transactions.TransactionInterop.GetDtcTransaction(), System.Transactions.TransactionInterop.GetExportCookie(), System.Transactions.TransactionInterop.GetTransactionFromDtcTransaction(), System.Transactions.TransactionInterop.GetTransactionFromExportCookie(), System.Transactions.TransactionInterop.GetTransactionFromTransmitterPropagationToken(), System.Transactions.TransactionInterop.GetTransmitterPropagationToken(), System.Transactions.TransactionInterop.GetWhereabouts(), System.Net.Security.NetSecurityTelemetry.HandshakeFailed(), System.Net.Security.NetSecurityTelemetry.HandshakeStart(), System.Net.Security.NetSecurityTelemetry.HandshakeStop(), System.Threading.Tasks.TplEventSource.IncompleteAsyncMethod(), System.Transactions.SinglePhaseEnlistment.InDoubt(), System.Transactions.SinglePhaseEnlistment.InDoubt(), System.Transactions.TransactionState.InDoubtFromEnlistment(), System.Transactions.TransactionScope.Initialize(), System.Net.NetEventSource.InitializeSecurityContext(), System.Net.NetEventSource.InitializeSecurityContext(), System.Transactions.CommittableTransaction.InternalDispose(), System.Transactions.TransactionScope.InternalDispose(), System.Transactions.TransactionsEtwProvider.InvalidOperation(), System.Diagnostics.Tracing.EventSource.IsEnabled(), System.Diagnostics.Tracing.EventSource.IsEnabled(), System.Net.NetEventSource.LocatingPrivateKey(), System.Net.NetEventSource.LookForMatchingCerts(), System.Transactions.TransactionsEtwProvider.MethodEnter(), System.Transactions.TransactionsEtwProvider.MethodEnter(), System.Transactions.TransactionsEtwProvider.MethodExit(), System.Transactions.TransactionsEtwProvider.MethodExit(), System.Net.NetEventSource.NoDelegateButClientCert(), System.Net.NetEventSource.NoDelegateNoClientCert(), System.Net.NetEventSource.NoIssuersTryAllCerts(), System.Net.NetEventSource.NotFoundCertInStore(), System.Threading.Tasks.TplEventSource.OnEventCommand(), System.Diagnostics.Tracing.CounterGroup.OnTimer(), System.Net.NetEventSource.OperationReturnedSomething(), System.Threading.Tasks.ParallelEtwProvider.ParallelFork(), System.Threading.Tasks.ParallelEtwProvider.ParallelInvokeBegin(), System.Threading.Tasks.ParallelEtwProvider.ParallelInvokeEnd(), System.Threading.Tasks.ParallelEtwProvider.ParallelJoin(), System.Threading.Tasks.ParallelEtwProvider.ParallelLoopBegin(), System.Threading.Tasks.ParallelEtwProvider.ParallelLoopEnd(), System.Linq.Parallel.PlinqEtwProvider.ParallelQueryBegin(), System.Linq.Parallel.PlinqEtwProvider.ParallelQueryEnd(), System.Linq.Parallel.PlinqEtwProvider.ParallelQueryFork(), System.Linq.Parallel.PlinqEtwProvider.ParallelQueryJoin(), System.Transactions.TransactionStatePromotedP0Wave.Phase0VolatilePrepareDone(), System.Threading.Tasks.SynchronizationContextAwaitTaskContinuation.PostAction(), System.Transactions.PreparingEnlistment.Prepared(), System.Transactions.TransactionStatePromoted.PromoteEnlistmentsAndOutcome(), System.Net.NetEventSource.ReceivedFrame(), System.Transactions.TransactionManager.RecoveryComplete(), System.Transactions.PreparingEnlistment.RecoveryInformation(), System.Transactions.TransactionManager.Reenlist(), System.Net.NetEventSource.RemoteCertDeclaredValid(), System.Net.NetEventSource.RemoteCertHasNoErrors(), System.Net.NetEventSource.RemoteCertificate(), System.Net.NetEventSource.RemoteCertificateError(), System.Net.NetEventSource.RemoteCertUserDeclaredInvalid(), System.Buffers.ConfigurableArrayPool< T >.Bucket.Rent(), System.Buffers.ConfigurableArrayPool< T >.Rent(), System.Transactions.TransactionState.RestartCommitIfNeeded(), System.Buffers.ConfigurableArrayPool< T >.Bucket.Return(), System.Buffers.ConfigurableArrayPool< T >.Return(), System.Threading.Tasks.AwaitTaskContinuation.Run(), System.Threading.Tasks.SynchronizationContextAwaitTaskContinuation.Run(), System.Net.NetEventSource.SecureChannelCtor(), System.Net.NetEventSource.SecurityContextInputBuffers(), System.Net.NetEventSource.SelectedCert(), System.Net.NetEventSource.SentFrame(), System.Runtime.Serialization.Formatters.Binary.BinaryFormatterEventSource.SerializationStart(), System.Runtime.Serialization.Formatters.Binary.BinaryFormatterEventSource.SerializationStop(), System.Runtime.Serialization.Formatters.Binary.BinaryFormatterEventSource.SerializingObject(), System.Net.NetEventSource.SslStreamCtor(), System.Net.NetEventSource.SspiPackageNotFound(), System.Net.NetEventSource.SspiSelectedCipherSuite(), System.Threading.Tasks.TplEventSource.TaskCompleted(), System.Threading.Tasks.Dataflow.Internal.DataflowEtwProvider.TaskLaunchedForMessageHandling(), System.Threading.Tasks.TplEventSource.TaskScheduled(), System.Threading.Tasks.TplEventSource.TaskStarted(), System.Threading.Tasks.TplEventSource.TaskWaitBegin(), System.Threading.Tasks.TplEventSource.TaskWaitContinuationComplete(), System.Threading.Tasks.TplEventSource.TaskWaitContinuationStarted(), System.Threading.Tasks.TplEventSource.TaskWaitEnd(), System.Diagnostics.Tracing.NativeRuntimeEventSource.ThreadPoolIODequeue(), System.Diagnostics.Tracing.NativeRuntimeEventSource.ThreadPoolIOEnqueue(), System.Diagnostics.Tracing.NativeRuntimeEventSource.ThreadPoolWorkerThreadAdjustmentAdjustment(), System.Diagnostics.Tracing.NativeRuntimeEventSource.ThreadPoolWorkerThreadAdjustmentSample(), System.Diagnostics.Tracing.NativeRuntimeEventSource.ThreadPoolWorkerThreadAdjustmentStats(), System.Diagnostics.Tracing.NativeRuntimeEventSource.ThreadPoolWorkerThreadStart(), System.Diagnostics.Tracing.NativeRuntimeEventSource.ThreadPoolWorkerThreadStop(), System.Diagnostics.Tracing.NativeRuntimeEventSource.ThreadPoolWorkerThreadWait(), System.Diagnostics.Tracing.NativeRuntimeEventSource.ThreadPoolWorkingThreadCount(), System.Transactions.TransactionScope.Timeout(), System.Transactions.EnlistableStates.Timeout(), System.Transactions.TransactionStatePromotedBase.Timeout(), System.Transactions.TransactionStatePromotedNonMSDTCBase.Timeout(), System.Transactions.TransactionStateVolatilePhase1.Timeout(), System.Transactions.TransactionScope.TimerCallback(), System.Threading.Tasks.TplEventSource.TraceOperationBegin(), System.Threading.Tasks.TplEventSource.TraceOperationEnd(), System.Threading.Tasks.TplEventSource.TraceOperationRelation(), System.Threading.Tasks.TplEventSource.TraceSynchronousWorkBegin(), System.Threading.Tasks.TplEventSource.TraceSynchronousWorkEnd(), System.Transactions.TransactionsEtwProvider.TransactionAborted(), System.Transactions.TransactionsEtwProvider.TransactionCloneCreate(), System.Transactions.TransactionsEtwProvider.TransactionCommit(), System.Transactions.TransactionsEtwProvider.TransactionCommitted(), System.Transactions.TransactionsEtwProvider.TransactionCreated(), System.Transactions.TransactionsEtwProvider.TransactionDependentCloneComplete(), System.Transactions.TransactionsEtwProvider.TransactionExceptionTrace(), System.Transactions.TransactionsEtwProvider.TransactionExceptionTrace(), System.Transactions.TransactionsEtwProvider.TransactionInDoubt(), System.Transactions.TransactionsEtwProvider.TransactionManagerRecoveryComplete(), System.Transactions.TransactionsEtwProvider.TransactionManagerReenlist(), System.Transactions.TransactionsEtwProvider.TransactionPromoted(), System.Transactions.TransactionsEtwProvider.TransactionRollback(), System.Transactions.TransactionsEtwProvider.TransactionScopeCreated(), System.Transactions.TransactionsEtwProvider.TransactionScopeCurrentChanged(), System.Transactions.TransactionsEtwProvider.TransactionScopeDisposed(), System.Transactions.TransactionsEtwProvider.TransactionScopeIncomplete(), System.Transactions.TransactionsEtwProvider.TransactionScopeInternalError(), System.Transactions.TransactionsEtwProvider.TransactionScopeNestedIncorrectly(), System.Transactions.TransactionsEtwProvider.TransactionScopeTimeout(), System.Transactions.TransactionsEtwProvider.TransactionstateEnlist(), System.Transactions.TransactionsEtwProvider.TransactionTimeout(), System.Diagnostics.Tracing.EventSource.UpdateDescriptor(), System.Net.NetEventSource.UsingCachedCredential(), System.Diagnostics.Tracing.EventSource.Write(), System.Diagnostics.Tracing.EventSource.Write(), System.Diagnostics.Tracing.EventSource.Write<[DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicProperties)] T >(), System.Diagnostics.Tracing.EventSource.Write<[DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicProperties)] T >(), System.Diagnostics.Tracing.EventSource.Write<[DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicProperties)] T >(), System.Diagnostics.Tracing.EventSource.Write<[DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicProperties)] T >(), System.Net.Security.NetSecurityTelemetry.WriteEvent(), System.Net.Security.NetSecurityTelemetry.WriteEvent(), System.Net.Http.HttpTelemetry.WriteEvent(), System.Diagnostics.Tracing.EventSource.WriteEvent(), System.Net.Http.HttpTelemetry.WriteEvent(), System.Diagnostics.Tracing.EventSource.WriteEvent(), System.Diagnostics.Tracing.EventSource.WriteEvent(), System.Diagnostics.Tracing.EventSource.WriteEvent(), System.Net.NetEventSource.WriteEvent(), System.Diagnostics.Tracing.EventSource.WriteEvent(), System.Diagnostics.Tracing.EventSource.WriteEvent(), System.Diagnostics.Tracing.EventSource.WriteEvent(), System.Diagnostics.Tracing.FrameworkEventSource.WriteEvent(), System.Diagnostics.Tracing.FrameworkEventSource.WriteEvent(), System.Diagnostics.Tracing.EventSource.WriteEvent(), System.Diagnostics.Tracing.EventSource.WriteEvent(), System.Diagnostics.Tracing.EventSource.WriteEvent(), System.Net.Security.NetSecurityTelemetry.WriteEvent(), System.Net.Http.HttpTelemetry.WriteEvent(), System.Diagnostics.Tracing.EventSource.WriteEvent(), System.Diagnostics.Tracing.EventSource.WriteEvent(), System.Diagnostics.Tracing.EventSource.WriteEvent(), System.Diagnostics.Tracing.EventSource.WriteEvent(), System.Diagnostics.Tracing.EventSource.WriteEvent(), System.Diagnostics.Tracing.EventSource.WriteEvent(), System.Diagnostics.Tracing.EventSource.WriteEventVarargs(), System.Diagnostics.Tracing.EventSource.WriteEventWithRelatedActivityIdCore(), System.Diagnostics.Tracing.EventSource.WriteMultiMerge(), and System.Diagnostics.Tracing.EventSource.WriteMultiMerge().