Terraria: System.Diagnostics.Tracing.EventSource.WriteImpl
WriteImpl()
unsafe void System.Diagnostics.Tracing.EventSource.WriteImpl (string eventName, ref EventSourceOptions options, object data, Guid * pActivityId, Guid * pRelatedActivityId, TraceLoggingEventTypes eventTypes) inline private inherited
Definition at line 2947 of file EventSource.cs.
    {
        try
        {
            fixed (EventSourceOptions* ptr3 = &options)
            {
                options.Opcode = (options.IsOpcodeSet ? options.Opcode : GetOpcodeWithDefault(options.Opcode, eventName));
                EventDescriptor descriptor;
                NameInfo nameInfo = UpdateDescriptor(eventName, eventTypes, ref options, out descriptor);
                if (nameInfo == null)
                {
                    return;
                }
                IntPtr orCreateEventHandle = nameInfo.GetOrCreateEventHandle(m_eventPipeProvider, m_eventHandleTable, descriptor, eventTypes);
                int pinCount = eventTypes.pinCount;
                byte* scratch = stackalloc byte[(int)(uint)eventTypes.scratchSize];
                EventData* ptr = stackalloc EventData[eventTypes.dataCount + 3];
                for (int i = 0; i < eventTypes.dataCount + 3; i++)
                {
                    ptr[i] = default(EventData);
                }
                GCHandle* ptr2 = stackalloc GCHandle[pinCount];
                for (int j = 0; j < pinCount; j++)
                {
                    ptr2[j] = default(GCHandle);
                }
                ReadOnlySpan<byte> providerMetadata = ProviderMetadata;
                fixed (byte* pointer = providerMetadata)
                {
                    fixed (byte* pointer2 = nameInfo.nameMetadata)
                    {
                        fixed (byte* pointer3 = eventTypes.typeMetadata)
{
                            ptr->SetMetadata(pointer, providerMetadata.Length, 2);
                            ptr[1].SetMetadata(pointer2, nameInfo.nameMetadata.Length, 1);
                            ptr[2].SetMetadata(pointer3, eventTypes.typeMetadata.Length, 1);
                            EventOpcode opcode = (EventOpcode)descriptor.Opcode;
                            Guid activityId = Guid.Empty;
                            Guid relatedActivityId = Guid.Empty;
                            if (pActivityId == null && pRelatedActivityId == null && (options.ActivityOptions & EventActivityOptions.Disable) == 0)
{
                                switch (opcode)
{
                                case EventOpcode.Start:
                                    m_activityTracker.OnStart(m_name, eventName, 0, ref activityId, ref relatedActivityId, options.ActivityOptions);
                                    break;
                                case EventOpcode.Stop:
                                    m_activityTracker.OnStop(m_name, eventName, 0, ref activityId);
                                    break;
                                }
                                if (activityId != Guid.Empty)
{
                                    pActivityId = &activityId;
                                }
                                if (relatedActivityId != Guid.Empty)
{
                                    pRelatedActivityId = &relatedActivityId;
                                }
                            }
                            try
{
                                DataCollector.ThreadInstance.Enable(scratch, eventTypes.scratchSize, ptr + 3, eventTypes.dataCount, ptr2, pinCount);
                                TraceLoggingTypeInfo traceLoggingTypeInfo = eventTypes.typeInfos[0];
                                traceLoggingTypeInfo.WriteData(traceLoggingTypeInfo.PropertyValueFactory(data));
                                WriteEventRaw(eventName, ref descriptor, orCreateEventHandle, pActivityId, pRelatedActivityId, (int)(DataCollector.ThreadInstance.Finish() - ptr), (IntPtr)ptr);
                                if (m_Dispatchers != null)
{
                                    EventPayload payload = (EventPayload)eventTypes.typeInfos[0].GetData(data);
                                    WriteToAllListeners(eventName, ref descriptor, nameInfo.tags, pActivityId, pRelatedActivityId, payload);
                                }
                            }
                            catch (Exception ex)
{
                                if (ex is EventSourceException)
{
                                    throw;
                                }
                                ThrowEventSourceException(eventName, ex);
                            }
                            finally
{
                                WriteCleanup(ptr2, pinCount);
                            }
                        }
                    }
                }
            }
        }
        catch (Exception ex2)
        {
            if (ex2 is EventSourceException)
            {
                throw;
            }
            ThrowEventSourceException(eventName, ex2);
        }
    }
References System.Guid.Empty, System.Diagnostics.Tracing.EventSource.GetOpcodeWithDefault(), System.Diagnostics.Tracing.EventSource.m_activityTracker, System.Diagnostics.Tracing.EventSource.m_Dispatchers, System.Diagnostics.Tracing.EventSource.m_eventHandleTable, System.Diagnostics.Tracing.EventSource.m_eventPipeProvider, System.Diagnostics.Tracing.EventSource.m_name, System.Diagnostics.Tracing.ActivityTracker.OnStart(), System.Diagnostics.Tracing.ActivityTracker.OnStop(), System.Diagnostics.Tracing.EventDescriptor.Opcode, System.options, System.pointer, System.Diagnostics.Tracing.EventSource.ProviderMetadata, System.Diagnostics.Tracing.DataCollector.ThreadInstance, System.Diagnostics.Tracing.EventSource.ThrowEventSourceException(), System.Diagnostics.Tracing.EventSource.UpdateDescriptor(), System.Diagnostics.Tracing.EventSource.WriteCleanup(), System.Diagnostics.Tracing.EventSource.WriteEventRaw(), and System.Diagnostics.Tracing.EventSource.WriteToAllListeners().
Referenced by System.Diagnostics.Tracing.EventSource.Write(), System.Diagnostics.Tracing.EventSource.Write(), System.Diagnostics.Tracing.EventSource.Write<[DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicProperties)] T >(), System.Diagnostics.Tracing.EventSource.Write<[DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicProperties)] T >(), System.Diagnostics.Tracing.EventSource.Write<[DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicProperties)] T >(), and System.Diagnostics.Tracing.EventSource.Write<[DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicProperties)] T >().