Terraria: System.Diagnostics.Tracing.EventSource.LogEventArgsMismatches
LogEventArgsMismatches()
void System.Diagnostics.Tracing.EventSource.LogEventArgsMismatches (int eventId, object[] args) inline private inherited
Definition at line 1479 of file EventSource.cs.
    {
        ParameterInfo[] parameters = m_eventData[eventId].Parameters;
        if (args.Length != parameters.Length)
        {
            ReportOutOfBandMessage(SR.Format(SR.EventSource_EventParametersMismatch, eventId, args.Length, parameters.Length));
            return;
        }
        for (int i = 0; i < args.Length; i++)
        {
            Type parameterType = parameters[i].ParameterType;
            object obj = args[i];
            if ((obj != null && !parameterType.IsAssignableFrom(obj.GetType())) || (obj == null && parameterType.IsValueType && (!parameterType.IsGenericType || !(parameterType.GetGenericTypeDefinition() == typeof(Nullable<>)))))
            {
                ReportOutOfBandMessage(SR.Format(SR.EventSource_VarArgsParameterMismatch, eventId, parameters[i].Name));
                break;
            }
        }
    }
References System.SR.EventSource_EventParametersMismatch, System.SR.EventSource_VarArgsParameterMismatch, System.SR.Format(), System.Diagnostics.Tracing.EventSource.m_eventData, System.Reflection.ParameterInfo.Name, System.obj, System.Reflection.ParameterInfo.ParameterType, and System.Diagnostics.Tracing.EventSource.ReportOutOfBandMessage().
Referenced by System.Diagnostics.Tracing.EventSource.WriteEventVarargs().