Terraria: System.Diagnostics.Tracing.EventSource.WriteEventVarargs
WriteEventVarargs()
unsafe void System.Diagnostics.Tracing.EventSource.WriteEventVarargs (int eventId, Guid * childActivityID, object[] args) inline private inherited
Definition at line 1380 of file EventSource.cs.
    {
        if (!IsEnabled())
        {
            return;
        }
        try
        {
            ref EventMetadata reference = ref m_eventData[eventId];
            if (childActivityID != null && !reference.HasRelatedActivityID)
            {
                throw new ArgumentException(SR.EventSource_NoRelatedActivityId);
            }
            LogEventArgsMismatches(eventId, args);
            Guid* ptr = null;
            Guid activityId = Guid.Empty;
            Guid relatedActivityId = Guid.Empty;
            EventOpcode opcode = (EventOpcode)reference.Descriptor.Opcode;
            EventActivityOptions activityOptions = reference.ActivityOptions;
            if (childActivityID == null && (activityOptions & EventActivityOptions.Disable) == 0)
            {
                switch (opcode)
                {
                case EventOpcode.Start:
                    m_activityTracker.OnStart(m_name, reference.Name, reference.Descriptor.Task, ref activityId, ref relatedActivityId, reference.ActivityOptions);
                    break;
                case EventOpcode.Stop:
                    m_activityTracker.OnStop(m_name, reference.Name, reference.Descriptor.Task, ref activityId);
                    break;
                }
                if (activityId != Guid.Empty)
                {
                    ptr = &activityId;
                }
                if (relatedActivityId != Guid.Empty)
                {
                    childActivityID = &relatedActivityId;
                }
            }
            if (reference.EnabledForETW || reference.EnabledForEventPipe)
            {
                if (!SelfDescribingEvents)
                {
                    if (!m_etwProvider.WriteEvent(ref reference.Descriptor, reference.EventHandle, ptr, childActivityID, args))
                    {
                        ThrowEventSourceException(reference.Name);
                    }
                    if (!m_eventPipeProvider.WriteEvent(ref reference.Descriptor, reference.EventHandle, ptr, childActivityID, args))
                    {
                        ThrowEventSourceException(reference.Name);
                    }
                }
                else
                {
                    EventSourceOptions eventSourceOptions = default(EventSourceOptions);
                    eventSourceOptions.Keywords = (EventKeywords)reference.Descriptor.Keywords;
                    eventSourceOptions.Level = (EventLevel)reference.Descriptor.Level;
                    eventSourceOptions.Opcode = (EventOpcode)reference.Descriptor.Opcode;
                    EventSourceOptions options = eventSourceOptions;
                    WriteMultiMerge(reference.Name, ref options, reference.TraceLoggingEventTypes, ptr, childActivityID, args);
                }
            }
            if (m_Dispatchers != null && reference.EnabledForAnyListener)
            {
                if (!LocalAppContextSwitches.PreserveEventListnerObjectIdentity)
                {
                    args = SerializeEventArgs(eventId, args);
                }
                EventWrittenEventArgs eventCallbackArgs = new EventWrittenEventArgs(this, eventId, ptr, childActivityID)
                {
                    Payload = new ReadOnlyCollection<object>(args)
                };
                DispatchToAllListeners(eventCallbackArgs);
            }
        }
        catch (Exception ex)
        {
            if (ex is EventSourceException)
            {
                throw;
            }
            ThrowEventSourceException(m_eventData[eventId].Name, ex);
        }
    }
References System.Diagnostics.Tracing.EventSource.DispatchToAllListeners(), System.Guid.Empty, System.SR.EventSource_NoRelatedActivityId, System.Diagnostics.Tracing.EventSource.IsEnabled(), System.Diagnostics.Tracing.EventSource.LogEventArgsMismatches(), System.Diagnostics.Tracing.EventSource.m_activityTracker, System.Diagnostics.Tracing.EventSource.m_Dispatchers, System.Diagnostics.Tracing.EventSource.m_etwProvider, System.Diagnostics.Tracing.EventSource.m_eventData, System.Diagnostics.Tracing.EventSource.m_eventPipeProvider, System.Diagnostics.Tracing.EventSource.m_name, System.Diagnostics.Tracing.EventSource.Name, System.Diagnostics.Tracing.ActivityTracker.OnStart(), System.Diagnostics.Tracing.ActivityTracker.OnStop(), System.options, System.LocalAppContextSwitches.PreserveEventListnerObjectIdentity, System.Diagnostics.Tracing.EventSource.SelfDescribingEvents, System.Diagnostics.Tracing.EventSource.SerializeEventArgs(), System.Diagnostics.Tracing.EventSource.ThrowEventSourceException(), and System.Diagnostics.Tracing.EventSource.WriteMultiMerge().
Referenced by System.Diagnostics.Tracing.EventSource.WriteEvent(), and System.Diagnostics.Tracing.EventSource.WriteEventWithRelatedActivityId().