Terraria: System.Diagnostics.Tracing.EventSource.AddProviderEnumKind
AddProviderEnumKind()
static void System.Diagnostics.Tracing.EventSource.AddProviderEnumKind (ManifestBuilder manifest, FieldInfo staticField, string providerEnumKind) inline static private inherited
Definition at line 2426 of file EventSource.cs.
    {
        bool reflectionOnly = staticField.Module.Assembly.ReflectionOnly;
        Type fieldType = staticField.FieldType;
        if ((!reflectionOnly && fieldType == typeof(EventOpcode)) || AttributeTypeNamesMatch(fieldType, typeof(EventOpcode)))
        {
            if (!(providerEnumKind != "Opcodes"))
            {
                int value = (int)staticField.GetRawConstantValue();
                manifest.AddOpcode(staticField.Name, value);
                return;
            }
        }
        else if ((!reflectionOnly && fieldType == typeof(EventTask)) || AttributeTypeNamesMatch(fieldType, typeof(EventTask)))
        {
            if (!(providerEnumKind != "Tasks"))
            {
                int value2 = (int)staticField.GetRawConstantValue();
                manifest.AddTask(staticField.Name, value2);
                return;
            }
        }
        else
        {
            if ((reflectionOnly || !(fieldType == typeof(EventKeywords))) && !AttributeTypeNamesMatch(fieldType, typeof(EventKeywords)))
            {
                return;
            }
            if (!(providerEnumKind != "Keywords"))
            {
                ulong value3 = (ulong)(long)staticField.GetRawConstantValue();
                manifest.AddKeyword(staticField.Name, value3);
                return;
            }
        }
        manifest.ManifestError(SR.Format(SR.EventSource_EnumKindMismatch, staticField.Name, staticField.FieldType.Name, providerEnumKind));
    }
References System.Diagnostics.Tracing.EventSource.AttributeTypeNamesMatch(), System.SR.EventSource_EnumKindMismatch, System.SR.Format(), and System.value.
Referenced by System.Diagnostics.Tracing.EventSource.CreateManifestAndDescriptors().