Terraria: System.Diagnostics.Tracing.EventSource.SetCurrentThreadActivityId
SetCurrentThreadActivityId() [1/2]
static void System.Diagnostics.Tracing.EventSource.SetCurrentThreadActivityId (Guid activityId) inline static inherited
Definition at line 446 of file EventSource.cs.
    {
        if (IsSupported)
        {
            if (TplEventSource.Log != null)
            {
                TplEventSource.Log.SetActivityId(activityId);
            }
            EventPipeEventProvider.EventActivityIdControl(Interop.Advapi32.ActivityControl.EVENT_ACTIVITY_CTRL_SET_ID, ref activityId);
            Interop.Advapi32.EventActivityIdControl(Interop.Advapi32.ActivityControl.EVENT_ACTIVITY_CTRL_SET_ID, ref activityId);
        }
    }
References Interop.Advapi32.EventActivityIdControl(), System.Diagnostics.Tracing.EventPipeEventProvider.EventActivityIdControl(), System.Diagnostics.Tracing.EventSource.IsSupported, and System.Threading.Tasks.TplEventSource.Log.
Referenced by System.Diagnostics.Tracing.ActivityTracker.ActivityChanging(), System.Threading.Tasks.AwaitTaskContinuation.Execute(), System.Threading.Tasks.Task< TResult >.ExecuteWithThreadLocal(), System.Threading.Tasks.SynchronizationContextAwaitTaskContinuation.GetActionLogDelegate(), System.Runtime.CompilerServices.TaskAwaiter< TResult >.OutputWaitEtwEvents(), and System.Transactions.TransactionsEtwProvider.SetActivityId().