Terraria: System.Diagnostics.Tracing.EventSource.IsSupported
IsSupported
bool System.Diagnostics.Tracing.EventSource.IsSupported = InitializeIsSupported() static get package inherited
Definition at line 246 of file EventSource.cs.
{ get; } = InitializeIsSupported();
Referenced by System.Diagnostics.Tracing.EventSource.EventSource(), System.Diagnostics.Tracing.EventSource.EventSource(), System.Diagnostics.Tracing.EventSource.Dispose(), System.Diagnostics.Tracing.EventSource.DoCommand(), System.Diagnostics.Tracing.EventSource.EnableEventForDispatcher(), System.Diagnostics.Tracing.EventSource.GenerateManifest(), System.Diagnostics.Tracing.EventSource.GetSources(), System.AppContext.OnProcessExit(), System.Diagnostics.Tracing.NativeRuntimeEventSource.ProcessEvent(), System.StartupHookProvider.ProcessStartupHooks(), System.Diagnostics.Tracing.EventSource.SendCommand(), System.Diagnostics.Tracing.EventSource.SendCommand(), System.Diagnostics.Tracing.EventSource.SetCurrentThreadActivityId(), System.Diagnostics.Tracing.EventSource.SetCurrentThreadActivityId(), and System.Diagnostics.Tracing.EventSource.ToString().