Terraria: System.Diagnostics.Tracing.EventSource.IsCustomAttributeDefinedHelper
IsCustomAttributeDefinedHelper()
static bool System.Diagnostics.Tracing.EventSource.IsCustomAttributeDefinedHelper (MemberInfo member, Type attributeType, EventManifestOptions flags = EventManifestOptions::None) inline static package inherited
Definition at line 2080 of file EventSource.cs.
    {
        if (!member.Module.Assembly.ReflectionOnly && (flags & EventManifestOptions.AllowEventSourceOverride) == 0)
        {
            return member.IsDefined(attributeType, inherit: false);
        }
        foreach (CustomAttributeData customAttribute in CustomAttributeData.GetCustomAttributes(member))
        {
            if (AttributeTypeNamesMatch(attributeType, customAttribute.Constructor.ReflectedType))
            {
                return true;
            }
        }
        return false;
    }
References System.Diagnostics.Tracing.EventSource.AttributeTypeNamesMatch(), System.Reflection.CustomAttributeData.GetCustomAttributes(), System.Reflection.MemberInfo.IsDefined(), and System.Reflection.MemberInfo.Module.
Referenced by System.Diagnostics.Tracing.EventSource.CreateManifestAndDescriptors(), and System.Diagnostics.Tracing.ManifestBuilder.CreateManifestString().