Terraria: System.Diagnostics.Tracing.EventSource.EventSource
EventSource() [4/9]
System.Diagnostics.Tracing.EventSource.EventSource (EventSourceSettings settings, params string?[] traits) inline protected
Definition at line 490 of file EventSource.cs.
    {
        if (IsSupported)
        {
            m_eventHandleTable = new TraceLoggingEventHandleTable();
            m_config = ValidateSettings(settings);
            Type type = GetType();
            Guid guid = GetGuid(type);
            string name = GetName(type);
            Initialize(guid, name, traits);
        }
    }
References System.Diagnostics.Tracing.EventSource.GetGuid(), System.Diagnostics.Tracing.EventSource.GetName(), System.Diagnostics.Tracing.EventSource.Initialize(), System.Diagnostics.Tracing.EventSource.IsSupported, System.Diagnostics.Tracing.EventSource.m_config, System.Diagnostics.Tracing.EventSource.m_eventHandleTable, System.type, and System.Diagnostics.Tracing.EventSource.ValidateSettings().