Terraria: System.Diagnostics.Tracing.EventSource.SendCommand
SendCommand() [2/2]
static void System.Diagnostics.Tracing.EventSource.SendCommand (EventSource eventSource, EventCommand command, IDictionary< string, string?>? commandArguments) inline static inherited
Definition at line 406 of file EventSource.cs.
    {
        if (IsSupported)
        {
            if (eventSource == null)
            {
                throw new ArgumentNullException("eventSource");
            }
            if (command <= EventCommand.Update && command != EventCommand.SendManifest)
            {
                throw new ArgumentException(SR.EventSource_InvalidCommand, "command");
            }
            eventSource.SendCommand(null, EventProviderType.ETW, 0, 0, command, enable: true, EventLevel.LogAlways, EventKeywords.None, commandArguments);
        }
    }
References System.SR.EventSource_InvalidCommand, System.Diagnostics.Tracing.EventSource.IsSupported, and System.Diagnostics.Tracing.EventSource.SendCommand().
Referenced by System.Diagnostics.Tracing.EventListener.DisableEvents(), System.Diagnostics.Tracing.EventListener.EnableEvents(), System.Diagnostics.Tracing.EventSource.OverrideEventProvider.OnControllerCommand(), and System.Diagnostics.Tracing.EventSource.SendCommand().