Terraria: System.Diagnostics.Tracing.EventSource.ThrowEventSourceException
ThrowEventSourceException()
void System.Diagnostics.Tracing.EventSource.ThrowEventSourceException (string eventName, Exception innerEx = null) inline private inherited
Definition at line 1726 of file EventSource.cs.
    {
        if (m_EventSourceExceptionRecurenceCount > 0)
        {
            return;
        }
        try
        {
            m_EventSourceExceptionRecurenceCount++;
            string text = "EventSourceException";
            if (eventName != null)
            {
                text = text + " while processing event \"" + eventName + "\"";
            }
            switch (EventProvider.GetLastWriteEventError())
            {
            case EventProvider.WriteEventErrorCode.EventTooBig:
                ReportOutOfBandMessage(text + ": " + SR.EventSource_EventTooBig);
                if (ThrowOnEventWriteErrors)
                {
                    throw new EventSourceException(SR.EventSource_EventTooBig, innerEx);
                }
                return;
            case EventProvider.WriteEventErrorCode.NoFreeBuffers:
                ReportOutOfBandMessage(text + ": " + SR.EventSource_NoFreeBuffers);
                if (ThrowOnEventWriteErrors)
                {
                    throw new EventSourceException(SR.EventSource_NoFreeBuffers, innerEx);
                }
                return;
            case EventProvider.WriteEventErrorCode.NullInput:
                ReportOutOfBandMessage(text + ": " + SR.EventSource_NullInput);
                if (ThrowOnEventWriteErrors)
                {
                    throw new EventSourceException(SR.EventSource_NullInput, innerEx);
                }
                return;
            case EventProvider.WriteEventErrorCode.TooManyArgs:
                ReportOutOfBandMessage(text + ": " + SR.EventSource_TooManyArgs);
                if (ThrowOnEventWriteErrors)
                {
                    throw new EventSourceException(SR.EventSource_TooManyArgs, innerEx);
                }
                return;
            }
            if (innerEx != null)
            {
                innerEx = innerEx.GetBaseException();
                ReportOutOfBandMessage(text + ": " + innerEx.GetType()?.ToString() + ":" + innerEx.Message);
            }
            else
            {
                ReportOutOfBandMessage(text);
            }
            if (ThrowOnEventWriteErrors)
            {
                throw new EventSourceException(innerEx);
            }
        }
        finally
        {
            m_EventSourceExceptionRecurenceCount--;
        }
    }
References System.SR.EventSource_EventTooBig, System.SR.EventSource_NoFreeBuffers, System.SR.EventSource_NullInput, System.SR.EventSource_TooManyArgs, System.Diagnostics.Tracing.EventProvider.GetLastWriteEventError(), System.Diagnostics.Tracing.EventSource.m_EventSourceExceptionRecurenceCount, System.Diagnostics.Tracing.EventSource.ReportOutOfBandMessage(), System.text, and System.Diagnostics.Tracing.EventSource.ThrowOnEventWriteErrors.
Referenced by System.Diagnostics.Tracing.EventSource.SendManifest(), System.Diagnostics.Tracing.EventSource.WriteEventRaw(), System.Diagnostics.Tracing.EventSource.WriteEventVarargs(), System.Diagnostics.Tracing.EventSource.WriteEventWithRelatedActivityIdCore(), and System.Diagnostics.Tracing.EventSource.WriteImpl().