Terraria: System.Diagnostics.Tracing.EventSource.WriteEventRaw
WriteEventRaw()
unsafe void System.Diagnostics.Tracing.EventSource.WriteEventRaw (string eventName, ref EventDescriptor eventDescriptor, IntPtr eventHandle, Guid * activityID, Guid * relatedActivityID, int dataCount, IntPtr data) inline private inherited
Definition at line 1098 of file EventSource.cs.
    {
        bool flag = true;
        flag &= m_etwProvider == null;
        if (m_etwProvider != null && !m_etwProvider.WriteEventRaw(ref eventDescriptor, eventHandle, activityID, relatedActivityID, dataCount, data))
        {
            ThrowEventSourceException(eventName);
        }
        flag &= m_eventPipeProvider == null;
        if (m_eventPipeProvider != null && !m_eventPipeProvider.WriteEventRaw(ref eventDescriptor, eventHandle, activityID, relatedActivityID, dataCount, data))
        {
            ThrowEventSourceException(eventName);
        }
        if (flag)
        {
            ThrowEventSourceException(eventName);
        }
    }
References System.Diagnostics.Tracing.EventSource.m_etwProvider, System.Diagnostics.Tracing.EventSource.m_eventPipeProvider, and System.Diagnostics.Tracing.EventSource.ThrowEventSourceException().
Referenced by System.Diagnostics.Tracing.EventSource.WriteImpl(), System.Diagnostics.Tracing.EventSource.WriteMultiMerge(), and System.Diagnostics.Tracing.EventSource.WriteMultiMergeInner().