Terraria: System.Net.Http.HttpConnectionResponseContent.ConsumeStream
ConsumeStream()
Stream System.Net.Http.HttpConnectionResponseContent.ConsumeStream () inline private
Definition at line 20 of file HttpConnectionResponseContent.cs.
    {
        if (_consumedStream || _stream == null)
        {
            throw new InvalidOperationException(System.SR.net_http_content_stream_already_read);
        }
        _consumedStream = true;
        return _stream;
    }
References System.Net.Http.HttpConnectionResponseContent._consumedStream, System.Net.Http.HttpConnectionResponseContent._stream, and System.SR.net_http_content_stream_already_read.
Referenced by System.Net.Http.HttpConnectionResponseContent.CreateContentReadStream(), System.Net.Http.HttpConnectionResponseContent.CreateContentReadStreamAsync(), System.Net.Http.HttpConnectionResponseContent.SerializeToStream(), System.Net.Http.HttpConnectionResponseContent.SerializeToStreamAsync(), and System.Net.Http.HttpConnectionResponseContent.TryCreateContentReadStream().