Terraria: ChromaHotkeyPainter.Step_QuickHeal
Step_QuickHeal()
void ChromaHotkeyPainter.Step_QuickHeal () inline private
     {
         PaintKey healKey = _healKey;
         if (_player.QuickHeal_GetItemToUse() == null || _player.DeadOrGhost)
         {
             healKey.SetClear();
             _quickHealAlert = 0;
         }
         else if (_player.potionDelay > 0)
         {
             float lerpValue = Utils.GetLerpValue(_player.potionDelayTime, 0f, _player.potionDelay, clamped: true);
             Color solid = Color.Lerp(PainterColors.DangerKeyBlocked, PainterColors.QuickHealCooldown, lerpValue) * lerpValue * lerpValue * lerpValue;
             healKey.SetSolid(solid);
             _quickHealAlert = 0;
         }
         else if (_player.statLife == _player.statLifeMax2)
         {
             healKey.SetClear();
             _quickHealAlert = 0;
         }
         else if ((float)_player.statLife <= (float)_player.statLifeMax2 / 4f)
         {
             if (_quickHealAlert != 1)
             {
                 _quickHealAlert = 1;
                 healKey.SetAlert(Color.Black, PainterColors.QuickHealReadyUrgent, -1f, 2f);
             }
         }
         else if ((float)_player.statLife <= (float)_player.statLifeMax2 / 2f)
         {
             if (_quickHealAlert != 2)
             {
                 _quickHealAlert = 2;
                 healKey.SetAlert(Color.Black, PainterColors.QuickHealReadyUrgent, -1f, 2f);
             }
         }
         else
         {
             healKey.SetSolid(PainterColors.QuickHealReady);
             _quickHealAlert = 0;
         }
     }
References _healKey, _player, _quickHealAlert, Color, ChromaHotkeyPainter.PainterColors.DangerKeyBlocked, Player.DeadOrGhost, Utils.GetLerpValue(), Player.potionDelay, Player.potionDelayTime, Player.QuickHeal_GetItemToUse(), ChromaHotkeyPainter.PainterColors.QuickHealCooldown, ChromaHotkeyPainter.PainterColors.QuickHealReady, ChromaHotkeyPainter.PainterColors.QuickHealReadyUrgent, ChromaHotkeyPainter.PaintKey.SetAlert(), ChromaHotkeyPainter.PaintKey.SetClear(), ChromaHotkeyPainter.PaintKey.SetSolid(), Player.statLife, and Player.statLifeMax2.
Referenced by Update().