Terraria: ChromaHotkeyPainter.Step_QuickMana
Step_QuickMana()
void ChromaHotkeyPainter.Step_QuickMana () inline private
     {
         PaintKey manaKey = _manaKey;
         if (_player.QuickMana_GetItemToUse() == null || _player.DeadOrGhost || _player.statMana == _player.statManaMax2)
         {
             manaKey.SetClear();
         }
         else
         {
             manaKey.SetSolid(PainterColors.QuickMana);
         }
     }
References _manaKey, _player, Player.DeadOrGhost, ChromaHotkeyPainter.PainterColors.QuickMana, Player.QuickMana_GetItemToUse(), ChromaHotkeyPainter.PaintKey.SetClear(), ChromaHotkeyPainter.PaintKey.SetSolid(), Player.statMana, and Player.statManaMax2.