Terraria: System.Threading.PortableThreadPool.PerformBlockingAdjustment
PerformBlockingAdjustment() [2/2]
uint System.Threading.PortableThreadPool.PerformBlockingAdjustment (bool previousDelayElapsed, out bool addWorker) inline private
Definition at line 1682 of file PortableThreadPool.cs.
    {
        _pendingBlockingAdjustment = PendingBlockingAdjustment.None;
        addWorker = false;
        short targetThreadsGoalForBlockingAdjustment = TargetThreadsGoalForBlockingAdjustment;
        ThreadCounts counts = _separated.counts;
        short num = counts.NumThreadsGoal;
        if (num == targetThreadsGoalForBlockingAdjustment)
        {
            return 0u;
        }
        if (num > targetThreadsGoalForBlockingAdjustment)
        {
            if (_numThreadsAddedDueToBlocking <= 0)
            {
                return 0u;
            }
            short num2 = Math.Min((short)(num - targetThreadsGoalForBlockingAdjustment), _numThreadsAddedDueToBlocking);
            _numThreadsAddedDueToBlocking -= num2;
            num -= num2;
            _separated.counts.InterlockedSetNumThreadsGoal(num);
            HillClimbing.ThreadPoolHillClimber.ForceChange(num, HillClimbing.StateOrTransition.CooperativeBlocking);
            return 0u;
        }
        short num3 = (short)Math.Min((ushort)(_minThreads + BlockingConfig.ThreadsToAddWithoutDelay), (ushort)_maxThreads);
        short val = Math.Max(num3, Math.Min(counts.NumExistingThreads, _maxThreads));
        short num4 = Math.Min(targetThreadsGoalForBlockingAdjustment, val);
        short num5;
        if (num < num4)
        {
            num5 = num4;
        }
        else
        {
            if (!previousDelayElapsed)
            {
                goto IL_019f;
            }
            num5 = (short)(num + 1);
        }
        if (num5 > counts.NumExistingThreads)
        {
            long memoryLimitBytes = _memoryLimitBytes;
            if (memoryLimitBytes > 0)
            {
                long num6 = _memoryUsageBytes + (long)counts.NumExistingThreads * 65536L;
                long num7 = memoryLimitBytes * 8 / 10;
                if (num6 >= num7)
                {
                    return 0u;
                }
                long val2 = counts.NumExistingThreads + (num7 - num6) / 65536;
                num5 = (short)Math.Min(num5, val2);
                if (num5 <= num)
                {
                    return 0u;
                }
            }
        }
        _numThreadsAddedDueToBlocking += (short)(num5 - num);
        counts = _separated.counts.InterlockedSetNumThreadsGoal(num5);
        HillClimbing.ThreadPoolHillClimber.ForceChange(num5, HillClimbing.StateOrTransition.CooperativeBlocking);
        if (counts.NumProcessingWork >= num && _separated.numRequestedWorkers > 0)
        {
            addWorker = true;
        }
        num = num5;
        if (num >= targetThreadsGoalForBlockingAdjustment)
        {
            return 0u;
        }
        goto IL_019f;
        IL_019f:
        _pendingBlockingAdjustment = PendingBlockingAdjustment.WithDelayIfNecessary;
        int num8 = 1 + (num - num3) / BlockingConfig.ThreadsPerDelayStep;
        return Math.Min((uint)num8 * BlockingConfig.DelayStepMs, BlockingConfig.MaxDelayMs);
    }
References System.Threading.PortableThreadPool._maxThreads, System.Threading.PortableThreadPool._memoryLimitBytes, System.Threading.PortableThreadPool._memoryUsageBytes, System.Threading.PortableThreadPool._minThreads, System.Threading.PortableThreadPool._numThreadsAddedDueToBlocking, System.Threading.PortableThreadPool._pendingBlockingAdjustment, System.Threading.PortableThreadPool._separated, System.Threading.PortableThreadPool.CacheLineSeparated.counts, System.Threading.PortableThreadPool.BlockingConfig.DelayStepMs, System.Threading.PortableThreadPool.ThreadCounts.InterlockedSetNumThreadsGoal(), System.L, System.Math.Max(), System.Threading.PortableThreadPool.BlockingConfig.MaxDelayMs, System.Math.Min(), System.Threading.PortableThreadPool.ThreadCounts.NumExistingThreads, System.Threading.PortableThreadPool.ThreadCounts.NumProcessingWork, System.Threading.PortableThreadPool.CacheLineSeparated.numRequestedWorkers, System.Threading.PortableThreadPool.ThreadCounts.NumThreadsGoal, System.Threading.PortableThreadPool.TargetThreadsGoalForBlockingAdjustment, System.Threading.PortableThreadPool.HillClimbing.ThreadPoolHillClimber, System.Threading.PortableThreadPool.BlockingConfig.ThreadsPerDelayStep, and System.Threading.PortableThreadPool.BlockingConfig.ThreadsToAddWithoutDelay.