Terraria: System.Threading.PortableThreadPool.TryRemoveWaitThread
TryRemoveWaitThread()
bool System.Threading.PortableThreadPool.TryRemoveWaitThread (WaitThread thread) inline private
Definition at line 1808 of file PortableThreadPool.cs.
    {
        _waitThreadLock.Acquire();
        try
        {
            if (thread.AnyUserWaits)
            {
                return false;
            }
            RemoveWaitThread(thread);
        }
        finally
        {
            _waitThreadLock.Release();
        }
        return true;
    }
References System.Threading.PortableThreadPool._waitThreadLock, System.Threading.LowLevelLock.Acquire(), System.Threading.PortableThreadPool.WaitThread.AnyUserWaits, System.Threading.LowLevelLock.Release(), and System.Threading.PortableThreadPool.RemoveWaitThread().