Terraria: System.Threading.PortableThreadPool.ThreadPoolInstance
ThreadPoolInstance
readonly PortableThreadPool System.Threading.PortableThreadPool.ThreadPoolInstance = new PortableThreadPool() static
Definition at line 1313 of file PortableThreadPool.cs.
Referenced by System.Threading.PortableThreadPool.EnsureGateThreadRunning(), System.Threading.PortableThreadPool.GateThread.GateThreadStart(), System.Threading.ThreadPool.GetAvailableThreads(), System.Threading.ThreadPool.GetMaxThreads(), System.Threading.ThreadPool.GetMinThreads(), System.Threading.ThreadPool.GetOrCreateThreadLocalCompletionCountObject(), System.Threading.ThreadPool.NotifyThreadBlocked(), System.Threading.ThreadPool.NotifyThreadUnblocked(), System.Threading.ThreadPool.NotifyWorkItemComplete(), System.Threading.ThreadPool.NotifyWorkItemProgress(), System.Threading.PortableThreadPool.WaitThread.ProcessRemovals(), System.Threading.ThreadPool.RegisterWaitForSingleObject(), System.Threading.ThreadPool.ReportThreadStatus(), System.Threading.ThreadPool.RequestWorkerThread(), System.Threading.ThreadPool.SetMaxThreads(), System.Threading.ThreadPool.SetMinThreads(), System.Threading.PortableThreadPool.WaitThread.UnregisterWait(), System.Threading.PortableThreadPool.WaitThread.WaitThreadStart(), and System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart().