Terraria: System.Threading.PortableThreadPool.ReportThreadStatus
ReportThreadStatus()
void System.Threading.PortableThreadPool.ReportThreadStatus (bool isProcessingUserCallback) inline
Definition at line 1847 of file PortableThreadPool.cs.
    {
        CountsOfThreadsProcessingUserCallbacks countsOfThreadsProcessingUserCallbacks = _countsOfThreadsProcessingUserCallbacks;
        while (true)
        {
            CountsOfThreadsProcessingUserCallbacks newCounts = countsOfThreadsProcessingUserCallbacks;
            if (isProcessingUserCallback)
            {
                newCounts.IncrementCurrent();
            }
            else
            {
                newCounts.DecrementCurrent();
            }
            CountsOfThreadsProcessingUserCallbacks countsOfThreadsProcessingUserCallbacks2 = _countsOfThreadsProcessingUserCallbacks.InterlockedCompareExchange(newCounts, countsOfThreadsProcessingUserCallbacks);
            if (!(countsOfThreadsProcessingUserCallbacks2 == countsOfThreadsProcessingUserCallbacks))
            {
                countsOfThreadsProcessingUserCallbacks = countsOfThreadsProcessingUserCallbacks2;
                continue;
            }
            break;
        }
    }
References System.Threading.PortableThreadPool._countsOfThreadsProcessingUserCallbacks, System.Threading.PortableThreadPool.CountsOfThreadsProcessingUserCallbacks.DecrementCurrent(), System.Threading.PortableThreadPool.CountsOfThreadsProcessingUserCallbacks.IncrementCurrent(), and System.Threading.PortableThreadPool.CountsOfThreadsProcessingUserCallbacks.InterlockedCompareExchange().