Terraria: System.Threading.PortableThreadPool.GetAndResetHighWatermarkCountOfThreadsProcessingUserCallbacks
GetAndResetHighWatermarkCountOfThreadsProcessingUserCallbacks()
short System.Threading.PortableThreadPool.GetAndResetHighWatermarkCountOfThreadsProcessingUserCallbacks () inline private
Definition at line 1871 of file PortableThreadPool.cs.
    {
        CountsOfThreadsProcessingUserCallbacks countsOfThreadsProcessingUserCallbacks = _countsOfThreadsProcessingUserCallbacks;
        CountsOfThreadsProcessingUserCallbacks countsOfThreadsProcessingUserCallbacks2;
        while (true)
        {
            CountsOfThreadsProcessingUserCallbacks newCounts = countsOfThreadsProcessingUserCallbacks;
            newCounts.ResetHighWatermark();
            countsOfThreadsProcessingUserCallbacks2 = _countsOfThreadsProcessingUserCallbacks.InterlockedCompareExchange(newCounts, countsOfThreadsProcessingUserCallbacks);
            if (countsOfThreadsProcessingUserCallbacks2 == countsOfThreadsProcessingUserCallbacks || countsOfThreadsProcessingUserCallbacks2.HighWatermark == countsOfThreadsProcessingUserCallbacks2.Current)
            {
                break;
            }
            countsOfThreadsProcessingUserCallbacks = countsOfThreadsProcessingUserCallbacks2;
        }
        return countsOfThreadsProcessingUserCallbacks2.HighWatermark;
    }
References System.Threading.PortableThreadPool._countsOfThreadsProcessingUserCallbacks, System.Threading.PortableThreadPool.CountsOfThreadsProcessingUserCallbacks.Current, System.Threading.PortableThreadPool.CountsOfThreadsProcessingUserCallbacks.HighWatermark, System.Threading.PortableThreadPool.CountsOfThreadsProcessingUserCallbacks.InterlockedCompareExchange(), and System.Threading.PortableThreadPool.CountsOfThreadsProcessingUserCallbacks.ResetHighWatermark().
Referenced by System.Threading.PortableThreadPool.GateThread.GateThreadStart().