Terraria: System.Threading.PortableThreadPool.SetMaxThreads
SetMaxThreads()
bool System.Threading.PortableThreadPool.SetMaxThreads (int workerThreads, int ioCompletionThreads) inline
Definition at line 1442 of file PortableThreadPool.cs.
    {
        if (workerThreads <= 0 || ioCompletionThreads <= 0)
        {
            return false;
        }
        _threadAdjustmentLock.Acquire();
        try
        {
            if (workerThreads < _minThreads || !ThreadPool.CanSetMaxIOCompletionThreads(ioCompletionThreads))
            {
                return false;
            }
            ThreadPool.SetMaxIOCompletionThreads(ioCompletionThreads);
            if (ForcedMaxWorkerThreads != 0)
            {
                return true;
            }
            short num = (_maxThreads = (short)Math.Min(workerThreads, 32767));
            if (_separated.counts.NumThreadsGoal > num)
            {
                _separated.counts.InterlockedSetNumThreadsGoal(num);
            }
            return true;
        }
        finally
        {
            _threadAdjustmentLock.Release();
        }
    }
References System.Threading.PortableThreadPool._maxThreads, System.Threading.PortableThreadPool._minThreads, System.Threading.PortableThreadPool._separated, System.Threading.PortableThreadPool._threadAdjustmentLock, System.Threading.LowLevelLock.Acquire(), System.Threading.ThreadPool.CanSetMaxIOCompletionThreads(), System.Threading.PortableThreadPool.CacheLineSeparated.counts, System.Threading.PortableThreadPool.ForcedMaxWorkerThreads, System.Threading.PortableThreadPool.ThreadCounts.InterlockedSetNumThreadsGoal(), System.Math.Min(), System.Threading.PortableThreadPool.ThreadCounts.NumThreadsGoal, System.Threading.LowLevelLock.Release(), and System.Threading.ThreadPool.SetMaxIOCompletionThreads().