Terraria: System.Threading.PortableThreadPool.RegisterWaitHandle
RegisterWaitHandle()
void System.Threading.PortableThreadPool.RegisterWaitHandle (RegisteredWaitHandle handle) inline package
Definition at line 1765 of file PortableThreadPool.cs.
    {
        if (NativeRuntimeEventSource.Log.IsEnabled())
        {
            NativeRuntimeEventSource.Log.ThreadPoolIOEnqueue(handle);
        }
        _waitThreadLock.Acquire();
        try
        {
            WaitThreadNode waitThreadNode = _waitThreadsHead;
            if (waitThreadNode == null)
            {
                waitThreadNode = (_waitThreadsHead = new WaitThreadNode(new WaitThread()));
            }
            WaitThreadNode waitThreadNode2;
            do
            {
                if (waitThreadNode.Thread.RegisterWaitHandle(handle))
                {
                    return;
                }
                waitThreadNode2 = waitThreadNode;
                waitThreadNode = waitThreadNode.Next;
            }
            while (waitThreadNode != null);
            waitThreadNode2.Next = new WaitThreadNode(new WaitThread());
            waitThreadNode2.Next.Thread.RegisterWaitHandle(handle);
        }
        finally
        {
            _waitThreadLock.Release();
        }
    }
References System.Threading.PortableThreadPool._waitThreadLock, System.Threading.PortableThreadPool._waitThreadsHead, System.Threading.LowLevelLock.Acquire(), System.handle, System.Diagnostics.Tracing.NativeRuntimeEventSource.Log, System.Threading.PortableThreadPool.WaitThreadNode.Next, System.Threading.PortableThreadPool.WaitThread.RegisterWaitHandle(), System.Threading.LowLevelLock.Release(), and System.Threading.PortableThreadPool.WaitThreadNode.Thread.