Terraria: System.Threading.PortableThreadPool.AdjustMaxWorkersActive
AdjustMaxWorkersActive()
void System.Threading.PortableThreadPool.AdjustMaxWorkersActive () inline private
Definition at line 1521 of file PortableThreadPool.cs.
    {
        LowLevelLock threadAdjustmentLock = _threadAdjustmentLock;
        if (!threadAdjustmentLock.TryAcquire())
        {
            return;
        }
        bool flag = false;
        try
        {
            ThreadCounts counts = _separated.counts;
            if (counts.NumProcessingWork > counts.NumThreadsGoal || _pendingBlockingAdjustment != 0)
            {
                return;
            }
            long currentSampleStartTime = _currentSampleStartTime;
            long timestamp = Stopwatch.GetTimestamp();
            long frequency = Stopwatch.Frequency;
            double num = (double)(timestamp - currentSampleStartTime) / (double)frequency;
            if (num * 1000.0 >= (double)(_threadAdjustmentIntervalMs / 2))
            {
                int tickCount = Environment.TickCount;
                int num2 = (int)_completionCounter.Count;
                int numCompletions = num2 - _separated.priorCompletionCount;
                short numThreadsGoal = counts.NumThreadsGoal;
                int num3;
                (num3, _threadAdjustmentIntervalMs) = HillClimbing.ThreadPoolHillClimber.Update(numThreadsGoal, num, numCompletions);
                if (numThreadsGoal != (short)num3)
                {
                    _separated.counts.InterlockedSetNumThreadsGoal((short)num3);
                    if (num3 > numThreadsGoal)
                    {
                        flag = true;
                    }
                }
                _separated.priorCompletionCount = num2;
                _separated.nextCompletedWorkRequestsTime = tickCount + _threadAdjustmentIntervalMs;
                Volatile.Write(ref _separated.priorCompletedWorkRequestsTime, tickCount);
                _currentSampleStartTime = timestamp;
            }
        }
        finally
        {
            threadAdjustmentLock.Release();
        }
        if (flag)
        {
            WorkerThread.MaybeAddWorkingWorker(this);
        }
    }
References System.Threading.PortableThreadPool._completionCounter, System.Threading.PortableThreadPool._currentSampleStartTime, System.Threading.PortableThreadPool._pendingBlockingAdjustment, System.Threading.PortableThreadPool._separated, System.Threading.PortableThreadPool._threadAdjustmentIntervalMs, System.Threading.PortableThreadPool._threadAdjustmentLock, System.Threading.ThreadInt64PersistentCounter.Count, System.Threading.PortableThreadPool.CacheLineSeparated.counts, System.Diagnostics.Stopwatch.Frequency, System.Diagnostics.Stopwatch.GetTimestamp(), System.Threading.PortableThreadPool.ThreadCounts.InterlockedSetNumThreadsGoal(), System.Threading.PortableThreadPool.WorkerThread.MaybeAddWorkingWorker(), System.Threading.PortableThreadPool.ThreadCounts.NumProcessingWork, System.Threading.PortableThreadPool.ThreadCounts.NumThreadsGoal, System.Threading.PortableThreadPool.CacheLineSeparated.priorCompletedWorkRequestsTime, System.Threading.PortableThreadPool.CacheLineSeparated.priorCompletionCount, System.Threading.LowLevelLock.Release(), System.Threading.PortableThreadPool.HillClimbing.ThreadPoolHillClimber, System.Environment.TickCount, System.Threading.LowLevelLock.TryAcquire(), and System.Threading.Volatile.Write().
Referenced by System.Threading.PortableThreadPool.NotifyWorkItemProgress().