Terraria: System.Threading.PortableThreadPool.NotifyThreadBlocked
NotifyThreadBlocked()
bool System.Threading.PortableThreadPool.NotifyThreadBlocked () inline
Definition at line 1608 of file PortableThreadPool.cs.
    {
        if (!BlockingConfig.IsCooperativeBlockingEnabled || !Thread.CurrentThread.IsThreadPoolThread)
        {
            return false;
        }
        bool flag = false;
        _threadAdjustmentLock.Acquire();
        try
        {
            _numBlockedThreads++;
            if (_pendingBlockingAdjustment != PendingBlockingAdjustment.WithDelayIfNecessary && _separated.counts.NumThreadsGoal < TargetThreadsGoalForBlockingAdjustment)
            {
                if (_pendingBlockingAdjustment == PendingBlockingAdjustment.None)
                {
                    flag = true;
                }
                _pendingBlockingAdjustment = PendingBlockingAdjustment.WithDelayIfNecessary;
            }
        }
        finally
        {
            _threadAdjustmentLock.Release();
        }
        if (flag)
        {
            GateThread.Wake(this);
        }
        return true;
    }
References System.Threading.PortableThreadPool._numBlockedThreads, System.Threading.PortableThreadPool._pendingBlockingAdjustment, System.Threading.PortableThreadPool._separated, System.Threading.PortableThreadPool._threadAdjustmentLock, System.Threading.LowLevelLock.Acquire(), System.Threading.PortableThreadPool.CacheLineSeparated.counts, System.Threading.Thread.CurrentThread, System.Threading.PortableThreadPool.BlockingConfig.IsCooperativeBlockingEnabled, System.Threading.PortableThreadPool.ThreadCounts.NumThreadsGoal, System.Threading.LowLevelLock.Release(), System.Threading.PortableThreadPool.TargetThreadsGoalForBlockingAdjustment, and System.Threading.PortableThreadPool.GateThread.Wake().