Terraria: System.Security.Cryptography.AeadCommon.Encrypt
Encrypt()
static unsafe void System.Security.Cryptography.AeadCommon.Encrypt (SafeKeyHandle keyHandle, ReadOnlySpan< byte > nonce, ReadOnlySpan< byte > associatedData, ReadOnlySpan< byte > plaintext, Span< byte > ciphertext, Span< byte > tag) inline static
Definition at line 29 of file AeadCommon.cs.
    {
        fixed (byte* pbInput = &GetNonNullPinnableReference(plaintext))
        {
            fixed (byte* pbNonce = &GetNonNullPinnableReference(nonce))
            {
                fixed (byte* pbOutput = &GetNonNullPinnableReference(ciphertext))
                {
                    fixed (byte* pbTag = &GetNonNullPinnableReference(tag))
                    {
                        fixed (byte* pbAuthData = &GetNonNullPinnableReference(associatedData))
{
                            global::Interop.BCrypt.BCRYPT_AUTHENTICATED_CIPHER_MODE_INFO bCRYPT_AUTHENTICATED_CIPHER_MODE_INFO = global::Interop.BCrypt.BCRYPT_AUTHENTICATED_CIPHER_MODE_INFO.Create();
                            bCRYPT_AUTHENTICATED_CIPHER_MODE_INFO.pbNonce = pbNonce;
                            bCRYPT_AUTHENTICATED_CIPHER_MODE_INFO.cbNonce = nonce.Length;
                            bCRYPT_AUTHENTICATED_CIPHER_MODE_INFO.pbTag = pbTag;
                            bCRYPT_AUTHENTICATED_CIPHER_MODE_INFO.cbTag = tag.Length;
                            bCRYPT_AUTHENTICATED_CIPHER_MODE_INFO.pbAuthData = pbAuthData;
                            bCRYPT_AUTHENTICATED_CIPHER_MODE_INFO.cbAuthData = associatedData.Length;
                            int cbResult;
                            global::Interop.BCrypt.NTSTATUS nTSTATUS = global::Interop.BCrypt.BCryptEncrypt(keyHandle, pbInput, plaintext.Length, new IntPtr(&bCRYPT_AUTHENTICATED_CIPHER_MODE_INFO), null, 0, pbOutput, ciphertext.Length, out cbResult, 0);
                            if (nTSTATUS != 0)
{
                                throw global::Interop.BCrypt.CreateCryptographicException(nTSTATUS);
                            }
                        }
                    }
                }
            }
        }
    }
References System.Security.Cryptography.AeadCommon.GetNonNullPinnableReference(), System.ReadOnlySpan< T >.Length, and System.Span< T >.Length.
Referenced by System.Security.Cryptography.AesCcm.EncryptCore(), System.Security.Cryptography.AesGcm.EncryptCore(), and System.Security.Cryptography.ChaCha20Poly1305.EncryptCore().