Terraria: System.Security.Cryptography.AeadCommon.CheckArgumentsForNull
CheckArgumentsForNull()
static void System.Security.Cryptography.AeadCommon.CheckArgumentsForNull (byte[] nonce, byte[] plaintext, byte[] ciphertext, byte[] tag) inline static
Definition at line 9 of file AeadCommon.cs.
    {
        if (nonce == null)
        {
            throw new ArgumentNullException("nonce");
        }
        if (plaintext == null)
        {
            throw new ArgumentNullException("plaintext");
        }
        if (ciphertext == null)
        {
            throw new ArgumentNullException("ciphertext");
        }
        if (tag == null)
        {
            throw new ArgumentNullException("tag");
        }
    }
Referenced by System.Security.Cryptography.AesCcm.Decrypt(), System.Security.Cryptography.AesGcm.Decrypt(), System.Security.Cryptography.ChaCha20Poly1305.Decrypt(), System.Security.Cryptography.AesCcm.Encrypt(), System.Security.Cryptography.AesGcm.Encrypt(), and System.Security.Cryptography.ChaCha20Poly1305.Encrypt().