Terraria: System.Linq.Expressions.Interpreter.InstructionList.EmitLoad
EmitLoad() [2/3]
void System.Linq.Expressions.Interpreter.InstructionList.EmitLoad (object value) inline
Definition at line 197 of file InstructionList.cs.
    {
        EmitLoad(value, null);
    }
References System.Linq.Expressions.Interpreter.InstructionList.EmitLoad(), and System.value.
Referenced by System.Linq.Expressions.Interpreter.LightCompiler.CompileBinaryExpression(), System.Linq.Expressions.Interpreter.LightCompiler.CompileConstantExpression(), System.Linq.Expressions.Interpreter.LightCompiler.CompileConvertUnaryExpression(), System.Linq.Expressions.Interpreter.LightCompiler.CompileDefaultExpression(), System.Linq.Expressions.Interpreter.LightCompiler.CompileLiftedLogicalBinaryExpression(), System.Linq.Expressions.Interpreter.LightCompiler.CompileMember(), System.Linq.Expressions.Interpreter.LightCompiler.CompileNewExpression(), System.Linq.Expressions.Interpreter.LightCompiler.CompileTypeEqualExpression(), System.Linq.Expressions.Interpreter.LightCompiler.CompileTypeIsExpression(), System.Linq.Expressions.Interpreter.LightCompiler.CompileUnliftedLogicalBinaryExpression(), System.Linq.Expressions.Interpreter.InstructionList.EmitLoad(), System.Linq.Expressions.Interpreter.InstructionList.EmitLoad(), and System.Linq.Expressions.Interpreter.LightCompiler.EmitUnaryBoolCheck().