Terraria: System.Linq.Expressions.Interpreter.InstructionList.MakeLabel
MakeLabel()
BranchLabel System.Linq.Expressions.Interpreter.InstructionList.MakeLabel () inline
Definition at line 752 of file InstructionList.cs.
    {
        if (_labels == null)
        {
            _labels = new List<BranchLabel>();
        }
        BranchLabel branchLabel = new BranchLabel();
        _labels.Add(branchLabel);
        return branchLabel;
    }
References System.Linq.Expressions.Interpreter.InstructionList._labels, and System.Collections.Generic.Dictionary< TKey, TValue >.Add().
Referenced by System.Linq.Expressions.Interpreter.LightCompiler.CompileBinaryExpression(), System.Linq.Expressions.Interpreter.LightCompiler.CompileCoalesceBinaryExpression(), System.Linq.Expressions.Interpreter.LightCompiler.CompileConditionalExpression(), System.Linq.Expressions.Interpreter.LightCompiler.CompileConvertUnaryExpression(), System.Linq.Expressions.Interpreter.LightCompiler.CompileLiftedLogicalBinaryExpression(), System.Linq.Expressions.Interpreter.LightCompiler.CompileMethodLogicalBinaryExpression(), System.Linq.Expressions.Interpreter.LightCompiler.CompileTryExpression(), System.Linq.Expressions.Interpreter.LightCompiler.CompileTryFaultExpression(), System.Linq.Expressions.Interpreter.LightCompiler.CompileUnliftedLogicalBinaryExpression(), System.Linq.Expressions.Interpreter.LightCompiler.EmitUnaryBoolCheck(), System.Linq.Expressions.Interpreter.LightCompiler.EmitUnaryMethodCall(), and System.Linq.Expressions.Interpreter.InstructionList.MarkRuntimeLabel().