Terraria: System.Linq.Expressions.Interpreter.InstructionList.EmitLoadLocal
EmitLoadLocal()
void System.Linq.Expressions.Interpreter.InstructionList.EmitLoadLocal (int index) inline
Definition at line 281 of file InstructionList.cs.
    {
        if (s_loadLocal == null)
        {
            s_loadLocal = new Instruction[64];
        }
        if (index < s_loadLocal.Length)
        {
            Emit(s_loadLocal[index] ?? (s_loadLocal[index] = new LoadLocalInstruction(index)));
        }
        else
        {
            Emit(new LoadLocalInstruction(index));
        }
    }
References System.Linq.index, and System.Linq.Expressions.Interpreter.InstructionList.s_loadLocal.
Referenced by System.Linq.Expressions.Interpreter.LightCompiler.CompileArrayIndexAddress(), System.Linq.Expressions.Interpreter.LightCompiler.CompileBinaryExpression(), System.Linq.Expressions.Interpreter.LightCompiler.CompileConvertUnaryExpression(), System.Linq.Expressions.Interpreter.LightCompiler.CompileGetBoxedVariable(), System.Linq.Expressions.Interpreter.LightCompiler.CompileIndexAssignment(), System.Linq.Expressions.Interpreter.LightCompiler.CompileLiftedLogicalBinaryExpression(), System.Linq.Expressions.Interpreter.LightCompiler.CompileMemberAssignment(), and System.Linq.Expressions.Interpreter.LightCompiler.LoadLocalNoValueTypeCopy().