Terraria: System.Linq.Expressions.Interpreter.InstructionList.EmitInitializeLocal
EmitInitializeLocal()
void System.Linq.Expressions.Interpreter.InstructionList.EmitInitializeLocal (int index, Type type) inline
Definition at line 437 of file InstructionList.cs.
    {
        object primitiveDefaultValue = ScriptingRuntimeHelpers.GetPrimitiveDefaultValue(type);
        if (primitiveDefaultValue != null)
        {
            Emit(new InitializeLocalInstruction.ImmutableValue(index, primitiveDefaultValue));
        }
        else if (type.IsValueType)
        {
            Emit(new InitializeLocalInstruction.MutableValue(index, type));
        }
        else
        {
            Emit(InitReference(index));
        }
    }
References System.Linq.Expressions.Interpreter.ScriptingRuntimeHelpers.GetPrimitiveDefaultValue(), System.Linq.index, System.Linq.Expressions.Interpreter.InstructionList.InitReference(), and System.type.
Referenced by System.Linq.Expressions.Interpreter.LightCompiler.CompileBlockStart().