Terraria: System.Linq.Expressions.Interpreter.InstructionList.ToArray
ToArray()
InstructionArray System.Linq.Expressions.Interpreter.InstructionList.ToArray () inline
Definition at line 192 of file InstructionList.cs.
    {
        return new InstructionArray(_maxStackDepth, _maxContinuationDepth, _instructions.ToArray(), _objects?.ToArray(), BuildRuntimeLabels(), null);
    }
References System.Linq.Expressions.Interpreter.InstructionList._instructions, System.Linq.Expressions.Interpreter.InstructionList._maxContinuationDepth, System.Linq.Expressions.Interpreter.InstructionList._maxStackDepth, System.Linq.Expressions.Interpreter.InstructionList._objects, System.Linq.Expressions.Interpreter.InstructionList.BuildRuntimeLabels(), and System.Collections.Generic.List< T >.ToArray().
Referenced by System.Linq.Expressions.Interpreter.LightCompiler.MakeInterpreter().