Terraria: System.Linq.Expressions.Interpreter.InstructionList.MarkLabel
MarkLabel()
void System.Linq.Expressions.Interpreter.InstructionList.MarkLabel (BranchLabel label) inline
Definition at line 786 of file InstructionList.cs.
    {
        label.Mark(this);
    }
Referenced by System.Linq.Expressions.Interpreter.LightCompiler.CompileBinaryExpression(), System.Linq.Expressions.Interpreter.LightCompiler.CompileCoalesceBinaryExpression(), System.Linq.Expressions.Interpreter.LightCompiler.CompileConditionalExpression(), System.Linq.Expressions.Interpreter.LightCompiler.CompileConvertUnaryExpression(), System.Linq.Expressions.Interpreter.LightCompiler.CompileIntSwitchExpression< T >(), System.Linq.Expressions.Interpreter.LightCompiler.CompileLabelExpression(), System.Linq.Expressions.Interpreter.LightCompiler.CompileLiftedLogicalBinaryExpression(), System.Linq.Expressions.Interpreter.LightCompiler.CompileLoopExpression(), System.Linq.Expressions.Interpreter.LightCompiler.CompileMethodLogicalBinaryExpression(), System.Linq.Expressions.Interpreter.LightCompiler.CompileStringSwitchExpression(), System.Linq.Expressions.Interpreter.LightCompiler.CompileTryExpression(), System.Linq.Expressions.Interpreter.LightCompiler.CompileTryFaultExpression(), System.Linq.Expressions.Interpreter.LightCompiler.CompileUnliftedLogicalBinaryExpression(), System.Linq.Expressions.Interpreter.LightCompiler.EmitUnaryBoolCheck(), System.Linq.Expressions.Interpreter.LightCompiler.EmitUnaryMethodCall(), and System.Linq.Expressions.Interpreter.InstructionList.MarkRuntimeLabel().