Terraria: System.Linq.Expressions.Interpreter.InstructionList.EmitLeaveExceptionHandler
EmitLeaveExceptionHandler()
void System.Linq.Expressions.Interpreter.InstructionList.EmitLeaveExceptionHandler (bool hasValue, BranchLabel tryExpressionEndLabel) inline
Definition at line 904 of file InstructionList.cs.
    {
        Emit(LeaveExceptionHandlerInstruction.Create(EnsureLabelIndex(tryExpressionEndLabel), hasValue));
    }
References System.Linq.Expressions.Interpreter.LeaveExceptionHandlerInstruction.Create(), and System.Linq.Expressions.Interpreter.InstructionList.EnsureLabelIndex().
Referenced by System.Linq.Expressions.Interpreter.LightCompiler.CompileTryExpression().