Terraria: WorldFileData.FromInvalidWorld
FromInvalidWorld()
static WorldFileData WorldFileData.FromInvalidWorld (string path, bool cloudSave) inline static
     {
         WorldFileData worldFileData = new WorldFileData(path, cloudSave);
         worldFileData.GameMode = 0;
         worldFileData.SetSeedToEmpty();
         worldFileData.WorldGeneratorVersion = 0uL;
         worldFileData.Metadata = FileMetadata.FromCurrentSettings(FileType.World);
         worldFileData.SetWorldSize(1, 1);
         worldFileData.HasCorruption = true;
         worldFileData.IsHardMode = false;
         worldFileData.IsValid = false;
         worldFileData.Name = FileUtilities.GetFileName(path, includeExtension: false);
         worldFileData.UniqueId = Guid.Empty;
         if (!cloudSave)
         {
             worldFileData.CreationTime = File.GetCreationTime(path);
         }
         else
         {
             worldFileData.CreationTime = DateTime.Now;
         }
         return worldFileData;
     }
References WorldFileData(), CreationTime, FileMetadata.FromCurrentSettings(), GameMode, FileUtilities.GetFileName(), HasCorruption, IsHardMode, IsValid, FileData.Metadata, FileData.Name, SetSeedToEmpty(), SetWorldSize(), UniqueId, and WorldGeneratorVersion.
Referenced by WorldFile.GetAllMetadata(), Main.LoadWorlds(), and UIWorkshopWorldImport.UpdateWorkshopWorldList().