Terraria: WorldFileData.MoveToLocal
MoveToLocal()
override void WorldFileData.MoveToLocal () inline virtual
Implements FileData.
     {
         if (base.IsCloudSave)
         {
             string worldPathFromName = Main.GetWorldPathFromName(Name, cloudSave: false);
             if (FileUtilities.MoveToLocal(base.Path, worldPathFromName))
             {
                 Main.CloudFavoritesData.ClearEntry(this);
                 _isCloudSave = false;
                 _path = worldPathFromName;
                 Main.LocalFavoriteData.SaveFavorite(this);
             }
         }
     }
References FileData._isCloudSave, FileData._path, FavoritesFile.ClearEntry(), Main.CloudFavoritesData, Main.GetWorldPathFromName(), Main.LocalFavoriteData, FileUtilities.MoveToLocal(), FileData.Name, and FavoritesFile.SaveFavorite().
Referenced by UIWorldListItem.CloudButtonClick().