Terraria: WorldFileData.CopyToLocal
CopyToLocal()
void WorldFileData.CopyToLocal (string newFileName = null, string newDisplayName = null) inline
     {
         if (!base.IsCloudSave)
         {
             if (newFileName == null)
             {
                 newFileName = Guid.NewGuid().ToString();
             }
             string worldPathFromName = Main.GetWorldPathFromName(newFileName, cloudSave: false);
             FileUtilities.Copy(base.Path, worldPathFromName, cloud: false);
             _path = worldPathFromName;
             if (newDisplayName != null)
             {
                 WorldGen.RenameWorld(this, newDisplayName, OnWorldRenameSuccess);
             }
         }
     }
References FileData._path, FileUtilities.Copy(), Main.GetWorldPathFromName(), OnWorldRenameSuccess(), and WorldGen.RenameWorld().
Referenced by WorkshopSocialModule.ImportDownloadedWorldToLocalSaves().