Terraria: System.Reflection.Emit.ConstructorBuilder.GetParameters
GetParameters()
override ParameterInfo[] System.Reflection.Emit.ConstructorBuilder.GetParameters () inline
Definition at line 89 of file ConstructorBuilder.cs.
    {
        ConstructorInfo constructor = GetTypeBuilder().GetConstructor(m_methodBuilder.m_parameterTypes);
        return constructor.GetParameters();
    }
References System.Reflection.Emit.TypeBuilder.GetConstructor(), System.Reflection.MethodBase.GetParameters(), System.Reflection.Emit.ConstructorBuilder.GetTypeBuilder(), System.Reflection.Emit.ConstructorBuilder.m_methodBuilder, and System.Reflection.Emit.MethodBuilder.m_parameterTypes.