Terraria: WorldFileData.SetSeed
SetSeed()
void WorldFileData.SetSeed (string seedText) inline
     {
         _seedText = seedText;
         WorldGen.currentWorldSeed = seedText;
         if (!int.TryParse(seedText, out _seed))
         {
             _seed = Crc32.Calculate(seedText);
         }
         _seed = ((_seed == int.MinValue) ? int.MaxValue : Math.Abs(_seed));
     }
References _seed, _seedText, Crc32.Calculate(), and WorldGen.currentWorldSeed.
Referenced by WorldFile.CreateMetadata(), Main.DedServ(), UIWorldCreation.FinishCreatingWorld(), WorldFile.GetAllMetadata(), WorldFile.LoadHeader(), WorldFile.LoadWorld(), Main.OnSeedSelected(), SetSeedToEmpty(), and SetSeedToRandom().