using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Diagnostics;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.Versioning;
using System.Security;
using System.Security.Permissions;

[assembly: CLSCompliant(true)]
[assembly: AssemblyDefaultAlias("System.ComponentModel.DataAnnotations")]
[assembly: AssemblyMetadata(".NETFrameworkAssembly", "")]
[assembly: AssemblyMetadata("Serviceable", "True")]
[assembly: AssemblyMetadata("PreferInbox", "True")]
[assembly: AssemblyMetadata("IsTrimmable", "True")]
[assembly: AssemblyCompany("Microsoft Corporation")]
[assembly: AssemblyCopyright("© Microsoft Corporation. All rights reserved.")]
[assembly: AssemblyDescription("System.ComponentModel.DataAnnotations")]
[assembly: AssemblyFileVersion("6.0.21.52210")]
[assembly: AssemblyInformationalVersion("6.0.0+4822e3c3aa77eb82b2fb33c9321f923cf11ddde6")]
[assembly: AssemblyProduct("Microsoft® .NET")]
[assembly: AssemblyTitle("System.ComponentModel.DataAnnotations")]
[assembly: AssemblyMetadata("RepositoryUrl", "https://github.com/dotnet/runtime")]
[assembly: AssemblyVersion("4.0.0.0")]
[assembly: TypeForwardedTo(typeof(AssociatedMetadataTypeTypeDescriptionProvider))]
[assembly: TypeForwardedTo(typeof(AssociationAttribute))]
[assembly: TypeForwardedTo(typeof(CompareAttribute))]
[assembly: TypeForwardedTo(typeof(ConcurrencyCheckAttribute))]
[assembly: TypeForwardedTo(typeof(CreditCardAttribute))]
[assembly: TypeForwardedTo(typeof(CustomValidationAttribute))]
[assembly: TypeForwardedTo(typeof(DataType))]
[assembly: TypeForwardedTo(typeof(DataTypeAttribute))]
[assembly: TypeForwardedTo(typeof(DisplayAttribute))]
[assembly: TypeForwardedTo(typeof(DisplayColumnAttribute))]
[assembly: TypeForwardedTo(typeof(DisplayFormatAttribute))]
[assembly: TypeForwardedTo(typeof(EditableAttribute))]
[assembly: TypeForwardedTo(typeof(EmailAddressAttribute))]
[assembly: TypeForwardedTo(typeof(EnumDataTypeAttribute))]
[assembly: TypeForwardedTo(typeof(FileExtensionsAttribute))]
[assembly: TypeForwardedTo(typeof(FilterUIHintAttribute))]
[assembly: TypeForwardedTo(typeof(IValidatableObject))]
[assembly: TypeForwardedTo(typeof(KeyAttribute))]
[assembly: TypeForwardedTo(typeof(MaxLengthAttribute))]
[assembly: TypeForwardedTo(typeof(MetadataTypeAttribute))]
[assembly: TypeForwardedTo(typeof(MinLengthAttribute))]
[assembly: TypeForwardedTo(typeof(PhoneAttribute))]
[assembly: TypeForwardedTo(typeof(RangeAttribute))]
[assembly: TypeForwardedTo(typeof(RegularExpressionAttribute))]
[assembly: TypeForwardedTo(typeof(RequiredAttribute))]
[assembly: TypeForwardedTo(typeof(ScaffoldColumnAttribute))]
[assembly: TypeForwardedTo(typeof(ColumnAttribute))]
[assembly: TypeForwardedTo(typeof(ComplexTypeAttribute))]
[assembly: TypeForwardedTo(typeof(DatabaseGeneratedAttribute))]
[assembly: TypeForwardedTo(typeof(DatabaseGeneratedOption))]
[assembly: TypeForwardedTo(typeof(ForeignKeyAttribute))]
[assembly: TypeForwardedTo(typeof(InversePropertyAttribute))]
[assembly: TypeForwardedTo(typeof(NotMappedAttribute))]
[assembly: TypeForwardedTo(typeof(TableAttribute))]
[assembly: TypeForwardedTo(typeof(StringLengthAttribute))]
[assembly: TypeForwardedTo(typeof(TimestampAttribute))]
[assembly: TypeForwardedTo(typeof(UIHintAttribute))]
[assembly: TypeForwardedTo(typeof(UrlAttribute))]
[assembly: TypeForwardedTo(typeof(ValidationAttribute))]
[assembly: TypeForwardedTo(typeof(ValidationContext))]
[assembly: TypeForwardedTo(typeof(ValidationException))]
[assembly: TypeForwardedTo(typeof(ValidationResult))]
[assembly: TypeForwardedTo(typeof(Validator))]
[module: SkipLocalsInit]
