Terraria: System.Threading.Tasks.Parallel.ForEachAsyncState.Complete
Complete()
void System.Threading.Tasks.Parallel.ForEachAsyncState< TSource >.Complete () inline inherited
Definition at line 80 of file Parallel.cs.
        {
            if (_externalCancellationToken.IsCancellationRequested)
            {
                bool flag = TrySetCanceled(_externalCancellationToken);
            }
            else if (_exceptions == null)
            {
                bool flag = TrySetResult();
            }
            else
            {
                bool flag = TrySetException(_exceptions);
            }
        }
References System.Threading.Tasks.Parallel.ForEachAsyncState< TSource >._exceptions, System.Threading.Tasks.Parallel.ForEachAsyncState< TSource >._externalCancellationToken, System.Threading.CancellationToken.IsCancellationRequested, System.Threading.Tasks.TaskCompletionSource< TResult >.TrySetCanceled(), System.Threading.Tasks.TaskCompletionSource< TResult >.TrySetException(), and System.Threading.Tasks.TaskCompletionSource< TResult >.TrySetResult().