Terraria: Microsoft.Xna.Framework.Graphics.RasterizerState.SetDefaults
SetDefaults()
void Microsoft.Xna.Framework.Graphics.RasterizerState.SetDefaults () inline private
Definition at line 116 of file RasterizerState.cs.
    {
        ThrowIfBound();
        cachedCullMode = CullMode.CullCounterClockwiseFace;
        ThrowIfBound();
        cachedFillMode = FillMode.Solid;
        ThrowIfBound();
        cachedScissorTestEnable = false;
        ThrowIfBound();
        cachedMultiSampleAntiAlias = true;
        ThrowIfBound();
        cachedDepthBias = 0f;
        ThrowIfBound();
        cachedSlopeScaleDepthBias = 0f;
    }
References Microsoft.Xna.Framework.Graphics.RasterizerState.cachedCullMode, Microsoft.Xna.Framework.Graphics.RasterizerState.cachedDepthBias, Microsoft.Xna.Framework.Graphics.RasterizerState.cachedFillMode, Microsoft.Xna.Framework.Graphics.RasterizerState.cachedMultiSampleAntiAlias, Microsoft.Xna.Framework.Graphics.RasterizerState.cachedScissorTestEnable, Microsoft.Xna.Framework.Graphics.RasterizerState.cachedSlopeScaleDepthBias, and Microsoft.Xna.Framework.Graphics.RasterizerState.ThrowIfBound().
Referenced by Microsoft.Xna.Framework.Graphics.RasterizerState.RasterizerState(), and Microsoft.Xna.Framework.Graphics.RasterizerState.RasterizerState().