Terraria: Microsoft.Xna.Framework.Graphics.RasterizerState.CullCounterClockwise
CullCounterClockwise
readonly RasterizerState Microsoft.Xna.Framework.Graphics.RasterizerState.CullCounterClockwise = new RasterizerState(CullMode.CullCounterClockwiseFace, "RasterizerState.CullCounterClockwise") static
Definition at line 26 of file RasterizerState.cs.
Referenced by Terraria.Main.DoDraw(), Terraria.Graphics.Capture.CaptureInterface.ModeEdgeSelection.Draw(), Terraria.Graphics.Capture.CaptureInterface.ModeDragBounds.Draw(), Terraria.Graphics.Capture.CaptureInterface.ModeChangeSettings.Draw(), Terraria.Graphics.Capture.CaptureInterface.Draw(), Terraria.Main.DrawCapture(), Terraria.Main.DrawInterface_12_IngameFancyUI(), Terraria.Main.DrawInterface_36_Cursor(), Terraria.Main.DrawMap(), Terraria.Main.DrawMenu(), Terraria.Main.GUIBarsDrawInner(), Terraria.GameContent.AnOutlinedDrawRenderTargetContent.HandleUseReqest(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.InitializeDeviceState(), and Microsoft.Xna.Framework.Graphics.SpriteBatch.SetRenderState().