Terraria: FinalFractalHelper.Draw
Draw()
void FinalFractalHelper.Draw (Projectile proj) inline
     {
         FinalFractalProfile finalFractalProfile = GetFinalFractalProfile((int)proj.ai[1]);
         MiscShaderData miscShaderData = GameShaders.Misc["FinalFractal"];
         int num = 4;
         int num2 = 0;
         int num3 = 0;
         int num4 = 4;
         miscShaderData.UseShaderSpecificData(new Vector4(num, num2, num3, num4));
         miscShaderData.UseImage0("Images/Extra_" + (short)201);
         miscShaderData.UseImage1("Images/Extra_" + (short)193);
         miscShaderData.Apply();
         _vertexStrip.PrepareStrip(proj.oldPos, proj.oldRot, finalFractalProfile.colorMethod, finalFractalProfile.widthMethod, -Main.screenPosition + proj.Size / 2f, proj.oldPos.Length, includeBacksides: true);
         _vertexStrip.DrawTrail();
         Main.pixelShader.CurrentTechnique.Passes[0].Apply();
     }
References _vertexStrip, Projectile.ai, MiscShaderData.Apply(), FinalFractalHelper.FinalFractalProfile.colorMethod, VertexStrip.DrawTrail(), GetFinalFractalProfile(), GameShaders.Misc, Projectile.oldPos, Projectile.oldRot, Main.pixelShader, VertexStrip.PrepareStrip(), Main.screenPosition, Entity.Size, MiscShaderData.UseImage0(), MiscShaderData.UseImage1(), MiscShaderData.UseShaderSpecificData(), and FinalFractalHelper.FinalFractalProfile.widthMethod.