Terraria: System.Text.Encoding.EncodingCharBuffer.GetNextByte
GetNextByte()
unsafe byte System.Text.Encoding.EncodingCharBuffer.GetNextByte () inline package
Definition at line 171 of file Encoding.cs.
        {
            if (_bytes >= _byteEnd)
            {
                return 0;
            }
            return *(_bytes++);
        }
References System.Text.Encoding.EncodingCharBuffer._byteEnd, and System.Text.Encoding.EncodingCharBuffer._bytes.
Referenced by System.Text.UTF7Encoding.GetChars(), System.Text.GB18030Encoding.GetChars(), System.Text.ISO2022Encoding.GetCharsCP50225KR(), System.Text.ISO2022Encoding.GetCharsCP5022xJP(), and System.Text.ISO2022Encoding.GetCharsCP52936().