Terraria: System.Text.Encoding.EncodingCharBuffer.AddChar
AddChar() [2/2]
unsafe bool System.Text.Encoding.EncodingCharBuffer.AddChar (char ch, int numBytes) inline package
Definition at line 145 of file Encoding.cs.
        {
            if (_chars != null)
            {
                if (_chars >= _charEnd)
                {
                    _bytes -= numBytes;
                    _enc.ThrowCharsOverflow(_decoder, _bytes <= _byteStart);
                    return false;
                }
                *(_chars++) = ch;
            }
            _charCountResult++;
            return true;
        }
References System.Text.Encoding.EncodingCharBuffer._bytes, System.Text.Encoding.EncodingCharBuffer._byteStart, System.Text.Encoding.EncodingCharBuffer._charCountResult, System.Text.Encoding.EncodingCharBuffer._charEnd, System.Text.Encoding.EncodingCharBuffer._chars, System.Text.Encoding.EncodingCharBuffer._decoder, System.Text.Encoding.EncodingCharBuffer._enc, System.ch, System.Runtime.Serialization.Dictionary, and System.Text.Encoding.ThrowCharsOverflow().
Referenced by System.Text.Encoding.EncodingCharBuffer.AddChar(), System.Text.UTF7Encoding.GetChars(), System.Text.GB18030Encoding.GetChars(), System.Text.ISO2022Encoding.GetCharsCP50225KR(), System.Text.ISO2022Encoding.GetCharsCP5022xJP(), and System.Text.ISO2022Encoding.GetCharsCP52936().