Terraria: System.Text.Encoding.EncodingCharBuffer.Fallback
Fallback() [2/2]
unsafe bool System.Text.Encoding.EncodingCharBuffer.Fallback (byte[] byteBuffer) inline package
Definition at line 186 of file Encoding.cs.
        {
            if (_chars != null)
            {
                char* chars = _chars;
                if (!_fallbackBuffer.InternalFallback(byteBuffer, _bytes, ref _chars))
                {
                    _bytes -= byteBuffer.Length;
                    _fallbackBuffer.InternalReset();
                    _enc.ThrowCharsOverflow(_decoder, _chars == _charStart);
                    return false;
                }
                _charCountResult += (int)(_chars - chars);
            }
            else
            {
                _charCountResult += _fallbackBuffer.InternalFallback(byteBuffer, _bytes);
            }
            return true;
        }
References System.Text.Encoding.EncodingCharBuffer._bytes, System.Text.Encoding.EncodingCharBuffer._charCountResult, System.Text.Encoding.EncodingCharBuffer._chars, System.Text.Encoding.EncodingCharBuffer._charStart, System.Text.Encoding.EncodingCharBuffer._decoder, System.Text.Encoding.EncodingCharBuffer._enc, System.Text.Encoding.EncodingCharBuffer._fallbackBuffer, System.chars, System.Text.DecoderFallbackBuffer.InternalFallback(), System.Text.DecoderFallbackBuffer.InternalReset(), and System.Text.Encoding.ThrowCharsOverflow().