Terraria: System.Xml.Serialization.SchemaImporter.SchemaImporter
SchemaImporter()
System.Xml.Serialization.SchemaImporter.SchemaImporter (XmlSchemas schemas, CodeGenerationOptions options, ImportContext context) inline package
Definition at line 93 of file SchemaImporter.cs.
    {
        if (!schemas.Contains("http://www.w3.org/2001/XMLSchema"))
        {
            schemas.AddReference(XmlSchemas.XsdSchema);
            schemas.SchemaSet.Add(XmlSchemas.XsdSchema);
        }
        if (!schemas.Contains("http://www.w3.org/XML/1998/namespace"))
        {
            schemas.AddReference(XmlSchemas.XmlSchema);
            schemas.SchemaSet.Add(XmlSchemas.XmlSchema);
        }
        _schemas = schemas;
        _options = options;
        _context = context;
        Schemas.SetCache(Context.Cache, Context.ShareTypes);
    }
References System.Xml.Serialization.SchemaImporter._context, System.Xml.Serialization.SchemaImporter._options, System.Xml.Serialization.SchemaImporter._schemas, System.Xml.Serialization.XmlSchemas.AddReference(), System.Xml.Serialization.ImportContext.Cache, System.Xml.Serialization.XmlSchemas.Contains(), System.Xml.Serialization.SchemaImporter.Context, System.options, System.Xml.Serialization.SchemaImporter.Schemas, System.Xml.Serialization.XmlSchemas.SchemaSet, System.Xml.Serialization.XmlSchemas.SetCache(), System.Xml.Serialization.ImportContext.ShareTypes, System.Xml.Serialization.XmlSchemas.XmlSchema, and System.Xml.Serialization.XmlSchemas.XsdSchema.