Terraria: System.Xml.Serialization.SchemaImporter.RemoveReference
RemoveReference()
void System.Xml.Serialization.SchemaImporter.RemoveReference (XmlQualifiedName name, NameTable references) inline package inherited
Definition at line 194 of file SchemaImporter.cs.
    {
        references[name] = null;
    }
References System.Xml.Dictionary.
Referenced by System.Xml.Serialization.XmlSchemaImporter.GatherGroupChoices(), System.Xml.Serialization.XmlSchemaImporter.GetDataTypeSource(), System.Xml.Serialization.XmlSchemaImporter.ImportDataType(), System.Xml.Serialization.XmlSchemaImporter.ImportGroupMembers(), and System.Xml.Serialization.XmlSchemaImporter.ImportType().