Terraria: System.Xml.Serialization.SchemaImporter.AddReservedIdentifiersForDataBinding
AddReservedIdentifiersForDataBinding()
void System.Xml.Serialization.SchemaImporter.AddReservedIdentifiersForDataBinding (CodeIdentifiers scope) inline package inherited
Definition at line 199 of file SchemaImporter.cs.
    {
        if ((_options & CodeGenerationOptions.EnableDataBinding) != 0)
        {
            scope.AddReserved("PropertyChanged");
            scope.AddReserved("RaisePropertyChanged");
        }
    }
References System.Xml.Serialization.SchemaImporter._options, and System.Xml.Serialization.CodeIdentifiers.AddReserved().
Referenced by System.Xml.Serialization.XmlSchemaImporter.ImportStructDataType(), and System.Xml.Serialization.XmlSchemaImporter.ImportStructType().