Terraria: System.Globalization.GregorianCalendarHelper.GetYearOffset
GetYearOffset()
int System.Globalization.GregorianCalendarHelper.GetYearOffset (int year, int era, bool throwOnError) inline private
Definition at line 53 of file GregorianCalendarHelper.cs.
    {
        if (year < 0)
        {
            if (throwOnError)
            {
                throw new ArgumentOutOfRangeException("year", SR.ArgumentOutOfRange_NeedNonNegNum);
            }
            return -1;
        }
        if (era == 0)
        {
            era = m_Cal.CurrentEraValue;
        }
        for (int i = 0; i < m_EraInfo.Length; i++)
        {
            if (era != m_EraInfo[i].era)
            {
                continue;
            }
            if (year >= m_EraInfo[i].minEraYear)
            {
                if (year <= m_EraInfo[i].maxEraYear)
                {
                    return m_EraInfo[i].yearOffset;
                }
                if (!LocalAppContextSwitches.EnforceJapaneseEraYearRanges)
                {
                    int num = year - m_EraInfo[i].maxEraYear;
                    for (int num2 = i - 1; num2 >= 0; num2--)
                    {
                        if (num <= m_EraInfo[num2].maxEraYear)
{
                            return m_EraInfo[i].yearOffset;
                        }
                        num -= m_EraInfo[num2].maxEraYear;
                    }
                }
            }
            if (!throwOnError)
            {
                break;
            }
            throw new ArgumentOutOfRangeException("year", SR.Format(SR.ArgumentOutOfRange_Range, m_EraInfo[i].minEraYear, m_EraInfo[i].maxEraYear));
        }
        if (throwOnError)
        {
            throw new ArgumentOutOfRangeException("era", SR.ArgumentOutOfRange_InvalidEraValue);
        }
        return -1;
    }
References System.SR.ArgumentOutOfRange_InvalidEraValue, System.SR.ArgumentOutOfRange_NeedNonNegNum, System.SR.ArgumentOutOfRange_Range, System.Globalization.Calendar.CurrentEraValue, System.LocalAppContextSwitches.EnforceJapaneseEraYearRanges, System.SR.Format(), System.Globalization.GregorianCalendarHelper.m_Cal, System.Globalization.GregorianCalendarHelper.m_EraInfo, System.Globalization.EraInfo.maxEraYear, System.Globalization.EraInfo.minEraYear, System.year, and System.Globalization.EraInfo.yearOffset.
Referenced by System.Globalization.GregorianCalendarHelper.GetGregorianYear(), System.Globalization.GregorianCalendarHelper.IsValidYear(), and System.Globalization.GregorianCalendarHelper.ValidateYearInEra().