Terraria: System.Xml.Serialization.SchemaImporter.GetRootMapping
GetRootMapping()
StructMapping System.Xml.Serialization.SchemaImporter.GetRootMapping () inline package inherited
Definition at line 159 of file SchemaImporter.cs.
    {
        if (_root == null)
        {
            _root = CreateRootMapping();
        }
        return _root;
    }
References System.Xml.Serialization.SchemaImporter._root, and System.Xml.Serialization.SchemaImporter.CreateRootMapping().
Referenced by System.Xml.Serialization.SchemaImporter.ImportRootMapping(), and System.Xml.Serialization.XmlSchemaImporter.ImportStructType().