Terraria: System.Globalization.GregorianCalendarHelper.GetDayOfWeek
GetDayOfWeek()
DayOfWeek System.Globalization.GregorianCalendarHelper.GetDayOfWeek (DateTime time) inline
Definition at line 238 of file GregorianCalendarHelper.cs.
    {
        CheckTicksRange(time.Ticks);
        return (DayOfWeek)((time.Ticks / 864000000000L + 1) % 7);
    }
References System.Globalization.GregorianCalendarHelper.CheckTicksRange(), System.L, and System.DateTime.Ticks.
Referenced by System.Globalization.JapaneseCalendar.GetDayOfWeek(), System.Globalization.KoreanCalendar.GetDayOfWeek(), System.Globalization.TaiwanCalendar.GetDayOfWeek(), and System.Globalization.ThaiBuddhistCalendar.GetDayOfWeek().