Terraria: System.Xml.Serialization.SchemaImporter.MakeDerived
MakeDerived()
void System.Xml.Serialization.SchemaImporter.MakeDerived (StructMapping structMapping, Type baseType, bool baseTypeCanBeIndirect) inline package inherited
Definition at line 112 of file SchemaImporter.cs.
    {
        structMapping.ReferencedByTopLevelElement = true;
        if (!(baseType != null))
        {
            return;
        }
        TypeDesc typeDesc = Scope.GetTypeDesc(baseType);
        if (typeDesc == null)
        {
            return;
        }
        TypeDesc typeDesc2 = structMapping.TypeDesc;
        if (baseTypeCanBeIndirect)
        {
            while (typeDesc2.BaseTypeDesc != null && typeDesc2.BaseTypeDesc != typeDesc)
            {
                typeDesc2 = typeDesc2.BaseTypeDesc;
            }
        }
        if (typeDesc2.BaseTypeDesc != null && typeDesc2.BaseTypeDesc != typeDesc)
        {
            throw new InvalidOperationException(System.SR.Format(System.SR.XmlInvalidBaseType, structMapping.TypeDesc.FullName, baseType.FullName, typeDesc2.BaseTypeDesc.FullName));
        }
        typeDesc2.BaseTypeDesc = typeDesc;
    }
References System.Xml.Serialization.TypeDesc.TypeDesc(), System.Xml.Dictionary, System.SR.Format(), System.Xml.Serialization.TypeScope.GetTypeDesc(), System.Xml.Serialization.SchemaImporter.Scope, and System.SR.XmlInvalidBaseType.
Referenced by System.Xml.Serialization.XmlSchemaImporter.ImportDerivedTypeMapping(), System.Xml.Serialization.XmlSchemaImporter.ImportMembersMapping(), and System.Xml.Serialization.XmlSchemaImporter.ImportSchemaType().