Terraria: System.Xml.Serialization.SchemaImporter.ImportRootMapping
ImportRootMapping()
StructMapping System.Xml.Serialization.SchemaImporter.ImportRootMapping () inline package inherited
Definition at line 169 of file SchemaImporter.cs.
    {
        if (!_rootImported)
        {
            _rootImported = true;
            ImportDerivedTypes(XmlQualifiedName.Empty);
        }
        return GetRootMapping();
    }
References System.Xml.Serialization.SchemaImporter._rootImported, System.Xml.XmlQualifiedName.Empty, System.Xml.Serialization.SchemaImporter.GetRootMapping(), and System.Xml.Serialization.SchemaImporter.ImportDerivedTypes().
Referenced by System.Xml.Serialization.XmlSchemaImporter.ImportElementType(), and System.Xml.Serialization.XmlSchemaImporter.ImportType().