Terraria: System.Globalization.GregorianCalendarHelper.ToFourDigitYear
ToFourDigitYear()
int System.Globalization.GregorianCalendarHelper.ToFourDigitYear (int year, int twoDigitYearMax) inline
Definition at line 387 of file GregorianCalendarHelper.cs.
    {
        if (year < 0)
        {
            throw new ArgumentOutOfRangeException("year", SR.ArgumentOutOfRange_NeedPosNum);
        }
        if (year < 100)
        {
            int num = year % 100;
            return (twoDigitYearMax / 100 - ((num > twoDigitYearMax % 100) ? 1 : 0)) * 100 + num;
        }
        if (year < m_minYear || year > m_maxYear)
        {
            throw new ArgumentOutOfRangeException("year", SR.Format(SR.ArgumentOutOfRange_Range, m_minYear, m_maxYear));
        }
        return year;
    }
References System.SR.ArgumentOutOfRange_NeedPosNum, System.SR.ArgumentOutOfRange_Range, System.SR.Format(), System.Globalization.GregorianCalendarHelper.m_maxYear, System.Globalization.GregorianCalendarHelper.m_minYear, and System.year.
Referenced by System.Globalization.KoreanCalendar.ToFourDigitYear(), and System.Globalization.ThaiBuddhistCalendar.ToFourDigitYear().