Terraria: System.Globalization.GregorianCalendarHelper.GetEra
GetEra()
int System.Globalization.GregorianCalendarHelper.GetEra (DateTime time) inline
Definition at line 270 of file GregorianCalendarHelper.cs.
    {
        long ticks = time.Ticks;
        for (int i = 0; i < m_EraInfo.Length; i++)
        {
            if (ticks >= m_EraInfo[i].ticks)
            {
                return m_EraInfo[i].era;
            }
        }
        throw new ArgumentOutOfRangeException("time", SR.ArgumentOutOfRange_Era);
    }
References System.SR.ArgumentOutOfRange_Era, System.Globalization.EraInfo.era, System.Globalization.GregorianCalendarHelper.m_EraInfo, and System.DateTime.Ticks.
Referenced by System.Globalization.JapaneseCalendar.GetEra(), System.Globalization.JapaneseLunisolarCalendar.GetEra(), System.Globalization.KoreanCalendar.GetEra(), System.Globalization.TaiwanCalendar.GetEra(), System.Globalization.TaiwanLunisolarCalendar.GetEra(), and System.Globalization.ThaiBuddhistCalendar.GetEra().