Terraria: System.Globalization.GregorianCalendarHelper.GetDaysInYear
GetDaysInYear()
int System.Globalization.GregorianCalendarHelper.GetDaysInYear (int year, int era) inline
Definition at line 260 of file GregorianCalendarHelper.cs.
    {
        year = GetGregorianYear(year, era);
        if (year % 4 != 0 || (year % 100 == 0 && year % 400 != 0))
        {
            return 365;
        }
        return 366;
    }
References System.Globalization.GregorianCalendarHelper.GetGregorianYear(), and System.year.
Referenced by System.Globalization.JapaneseCalendar.GetDaysInYear(), System.Globalization.KoreanCalendar.GetDaysInYear(), System.Globalization.TaiwanCalendar.GetDaysInYear(), and System.Globalization.ThaiBuddhistCalendar.GetDaysInYear().