Terraria: System.Globalization.GregorianCalendarHelper.IsLeapDay
IsLeapDay()
bool System.Globalization.GregorianCalendarHelper.IsLeapDay (int year, int month, int day, int era) inline
Definition at line 321 of file GregorianCalendarHelper.cs.
    {
        if (day < 1 || day > GetDaysInMonth(year, month, era))
        {
            throw new ArgumentOutOfRangeException("day", SR.Format(SR.ArgumentOutOfRange_Range, 1, GetDaysInMonth(year, month, era)));
        }
        if (!IsLeapYear(year, era))
        {
            return false;
        }
        if (month == 2 && day == 29)
        {
            return true;
        }
        return false;
    }
References System.SR.ArgumentOutOfRange_Range, System.SR.Format(), System.Globalization.GregorianCalendarHelper.GetDaysInMonth(), System.Globalization.GregorianCalendarHelper.IsLeapYear(), and System.year.
Referenced by System.Globalization.JapaneseCalendar.IsLeapDay(), System.Globalization.KoreanCalendar.IsLeapDay(), System.Globalization.TaiwanCalendar.IsLeapDay(), and System.Globalization.ThaiBuddhistCalendar.IsLeapDay().