Terraria: System.Globalization.GregorianCalendarHelper.GetDatePart
GetDatePart()
int System.Globalization.GregorianCalendarHelper.GetDatePart (long ticks, int part) inline package
Definition at line 115 of file GregorianCalendarHelper.cs.
    {
        CheckTicksRange(ticks);
        int num = (int)(ticks / 864000000000L);
        int num2 = num / 146097;
        num -= num2 * 146097;
        int num3 = num / 36524;
        if (num3 == 4)
        {
            num3 = 3;
        }
        num -= num3 * 36524;
        int num4 = num / 1461;
        num -= num4 * 1461;
        int num5 = num / 365;
        if (num5 == 4)
        {
            num5 = 3;
        }
        if (part == 0)
        {
            return num2 * 400 + num3 * 100 + num4 * 4 + num5 + 1;
        }
        num -= num5 * 365;
        if (part == 1)
        {
            return num + 1;
        }
        int[] array = ((num5 == 3 && (num4 != 24 || num3 == 3)) ? DaysToMonth366 : DaysToMonth365);
        int i;
        for (i = (num >> 5) + 1; num >= array[i]; i++)
        {
        }
        if (part == 2)
        {
            return i;
        }
        return num - array[i - 1] + 1;
    }
References System.array, System.Globalization.GregorianCalendarHelper.CheckTicksRange(), System.Globalization.GregorianCalendarHelper.DaysToMonth365, System.Globalization.GregorianCalendarHelper.DaysToMonth366, and System.L.
Referenced by System.Globalization.GregorianCalendarHelper.AddMonths(), System.Globalization.GregorianCalendarHelper.GetDayOfMonth(), System.Globalization.GregorianCalendarHelper.GetDayOfYear(), System.Globalization.GregorianCalendarHelper.GetMonth(), and System.Globalization.GregorianCalendarHelper.GetYear().