Terraria: System.Globalization.GregorianCalendarHelper.CheckTicksRange
CheckTicksRange()
void System.Globalization.GregorianCalendarHelper.CheckTicksRange (long ticks) inline package
Definition at line 188 of file GregorianCalendarHelper.cs.
    {
        if (ticks < m_Cal.MinSupportedDateTime.Ticks || ticks > m_Cal.MaxSupportedDateTime.Ticks)
        {
            throw new ArgumentOutOfRangeException("time", SR.Format(CultureInfo.InvariantCulture, SR.ArgumentOutOfRange_CalendarRange, m_Cal.MinSupportedDateTime, m_Cal.MaxSupportedDateTime));
        }
    }
References System.SR.ArgumentOutOfRange_CalendarRange, System.SR.Format(), System.Globalization.CultureInfo.InvariantCulture, System.Globalization.GregorianCalendarHelper.m_Cal, System.Globalization.Calendar.MaxSupportedDateTime, System.Globalization.Calendar.MinSupportedDateTime, and System.DateTime.Ticks.
Referenced by System.Globalization.GregorianCalendarHelper.AddMonths(), System.Globalization.GregorianCalendarHelper.GetDatePart(), System.Globalization.GregorianCalendarHelper.GetDayOfWeek(), System.Globalization.GregorianCalendarHelper.GetWeekOfYear(), and System.Globalization.GregorianCalendarHelper.ToDateTime().