Terraria: System.DefaultBinder.ExactBinding
ExactBinding()
static MethodBase System.DefaultBinder.ExactBinding (MethodBase[] match, Type[] types, ParameterModifier[] modifiers) inline static inherited
Definition at line 655 of file DefaultBinder.cs.
    {
        if (match == null)
        {
            throw new ArgumentNullException("match");
        }
        MethodBase[] array = new MethodBase[match.Length];
        int num = 0;
        for (int i = 0; i < match.Length; i++)
        {
            ParameterInfo[] parametersNoCopy = match[i].GetParametersNoCopy();
            if (parametersNoCopy.Length == 0)
            {
                continue;
            }
            int j;
            for (j = 0; j < types.Length; j++)
            {
                Type parameterType = parametersNoCopy[j].ParameterType;
                if (!parameterType.Equals(types[j]))
                {
                    break;
                }
            }
            if (j >= types.Length)
            {
                array[num] = match[i];
                num++;
            }
        }
        return num switch
        {
            0 => null,
            1 => array[0],
            _ => FindMostDerivedNewSlotMeth(array, num),
        };
    }
References System.array, System.Type.Equals(), System.DefaultBinder.FindMostDerivedNewSlotMeth(), System.match, and System.Reflection.ParameterInfo.ParameterType.
Referenced by System.RuntimeType.GetConstructorImpl().