Terraria: System.DefaultBinder.CanChangePrimitive
CanChangePrimitive()
static bool System.DefaultBinder.CanChangePrimitive (Type source, Type target) inline static package inherited
Definition at line 1028 of file DefaultBinder.cs.
    {
        if ((source == typeof(IntPtr) && target == typeof(IntPtr)) || (source == typeof(UIntPtr) && target == typeof(UIntPtr)))
        {
            return true;
        }
        Primitives primitives = s_primitiveConversions[(int)Type.GetTypeCode(source)];
        Primitives primitives2 = (Primitives)(1 << (int)Type.GetTypeCode(target));
        return (primitives & primitives2) != 0;
    }
References System.Type.GetTypeCode(), System.DefaultBinder.s_primitiveConversions, and System.source.
Referenced by System.DefaultBinder.BindToField(), System.DefaultBinder.BindToMethod(), System.DefaultBinder.FindMostSpecificType(), System.DefaultBinder.SelectMethod(), and System.DefaultBinder.SelectProperty().