Terraria: System.DefaultBinder.CompareMethodSig
CompareMethodSig()
static bool System.DefaultBinder.CompareMethodSig (MethodBase m1, MethodBase m2) inline static inherited
Definition at line 919 of file DefaultBinder.cs.
    {
        ParameterInfo[] parametersNoCopy = m1.GetParametersNoCopy();
        ParameterInfo[] parametersNoCopy2 = m2.GetParametersNoCopy();
        if (parametersNoCopy.Length != parametersNoCopy2.Length)
        {
            return false;
        }
        int num = parametersNoCopy.Length;
        for (int i = 0; i < num; i++)
        {
            if (parametersNoCopy[i].ParameterType != parametersNoCopy2[i].ParameterType)
            {
                return false;
            }
        }
        return true;
    }
References System.Reflection.MethodBase.GetParametersNoCopy().
Referenced by System.DefaultBinder.FindMostSpecificMethod(), and System.RuntimeType.GetMethodImplCommon().