Terraria: System.DefaultBinder.FindMostSpecificType
FindMostSpecificType()
static int System.DefaultBinder.FindMostSpecificType (Type c1, Type c2, Type t) inline static private inherited
Definition at line 782 of file DefaultBinder.cs.
    {
        if (c1 == c2)
        {
            return 0;
        }
        if (t is SignatureType pattern)
        {
            if (pattern.MatchesExactly(c1))
            {
                return 1;
            }
            if (pattern.MatchesExactly(c2))
            {
                return 2;
            }
        }
        else
        {
            if (c1 == t)
            {
                return 1;
            }
            if (c2 == t)
            {
                return 2;
            }
        }
        if (c1.IsByRef || c2.IsByRef)
        {
            if (c1.IsByRef && c2.IsByRef)
            {
                c1 = c1.GetElementType();
                c2 = c2.GetElementType();
            }
            else if (c1.IsByRef)
            {
                if (c1.GetElementType() == c2)
                {
                    return 2;
                }
                c1 = c1.GetElementType();
            }
            else
            {
                if (c2.GetElementType() == c1)
                {
                    return 1;
                }
                c2 = c2.GetElementType();
            }
        }
        bool flag;
        bool flag2;
        if (c1.IsPrimitive && c2.IsPrimitive)
        {
            flag = CanChangePrimitive(c2, c1);
            flag2 = CanChangePrimitive(c1, c2);
        }
        else
        {
            flag = c1.IsAssignableFrom(c2);
            flag2 = c2.IsAssignableFrom(c1);
        }
        if (flag == flag2)
        {
            return 0;
        }
        if (flag)
        {
            return 2;
        }
        return 1;
    }
References System.DefaultBinder.CanChangePrimitive(), System.Type.GetElementType(), System.Type.IsAssignableFrom(), System.Type.IsByRef, and System.Type.IsPrimitive.
Referenced by System.DefaultBinder.FindMostSpecific(), and System.DefaultBinder.SelectProperty().