Terraria: Internal.Cryptography.HMACCommon.Dispose
Dispose()
void Internal.Cryptography.HMACCommon.Dispose (bool disposing) inline
Definition at line 98 of file HMACCommon.cs.
    {
        if (disposing)
        {
            _hMacProvider?.Dispose(disposing: true);
            _hMacProvider = null;
            _lazyHashProvider?.Dispose(disposing: true);
            _lazyHashProvider = null;
        }
    }
References Internal.Cryptography.HMACCommon._hMacProvider, Internal.Cryptography.HMACCommon._lazyHashProvider, and Internal.Cryptography.HashProvider.Dispose().
Referenced by System.Security.Cryptography.IncrementalHash.Dispose(), System.Security.Cryptography.HMACMD5.Dispose(), System.Security.Cryptography.HMACSHA1.Dispose(), System.Security.Cryptography.HMACSHA256.Dispose(), System.Security.Cryptography.HMACSHA384.Dispose(), and System.Security.Cryptography.HMACSHA512.Dispose().