Terraria: System.Xml.Xsl.XsltOld.XsltCompileContext.FuncKey.Invoke
Invoke()
override object System.Xml.Xsl.XsltOld.XsltCompileContext.FuncKey.Invoke (XsltContext xsltContext, object[] args, XPathNavigator docContext) inline
Implements System.Xml.Xsl.IXsltContextFunction.
Definition at line 276 of file XsltCompileContext.cs.
        {
            XsltCompileContext xsltCompileContext = (XsltCompileContext)xsltContext;
            PrefixQName.ParseQualifiedName(XsltFunctionImpl.ToString(args[0]), out var prefix, out var local);
            string ns = xsltContext.LookupNamespace(prefix);
            XmlQualifiedName xmlQualifiedName = new XmlQualifiedName(local, ns);
            XPathNavigator xPathNavigator = docContext.Clone();
            xPathNavigator.MoveToRoot();
            ArrayList arrayList = null;
            Key[] keyList = xsltCompileContext._processor.KeyList;
            foreach (Key key in keyList)
            {
                if (!(key.Name == xmlQualifiedName))
                {
                    continue;
                }
                Hashtable hashtable = key.GetKeys(xPathNavigator);
                if (hashtable == null)
                {
                    hashtable = xsltCompileContext.BuildKeyTable(key, xPathNavigator);
                    key.AddKey(xPathNavigator, hashtable);
                }
                if (args[1] is XPathNodeIterator xPathNodeIterator)
                {
                    XPathNodeIterator xPathNodeIterator2 = xPathNodeIterator.Clone();
                    while (xPathNodeIterator2.MoveNext())
                    {
                        arrayList = AddToList(arrayList, (ArrayList)hashtable[xPathNodeIterator2.Current.Value]);
                    }
                }
                else
                {
                    arrayList = AddToList(arrayList, (ArrayList)hashtable[XsltFunctionImpl.ToString(args[1])]);
                }
            }
            if (arrayList == null)
            {
                return XPathEmptyIterator.Instance;
            }
            if (arrayList[0] is XPathNavigator)
            {
                return new XPathArrayIterator(arrayList);
            }
            return new XPathMultyIterator(arrayList);
        }
References System.Xml.Xsl.XsltOld.XsltCompileContext.XsltCompileContext(), System.Xml.Xsl.XsltOld.XsltCompileContext.FuncKey.AddToList(), System.Xml.XPath.XPathNavigator.Clone(), System.Xml.XPath.XPathNodeIterator.Clone(), System.Xml.Dictionary, MS.Internal.Xml.XPath.XPathEmptyIterator.Instance, System.key, System.Xml.XmlNamespaceManager.LookupNamespace(), System.Xml.Xsl.XsltOld.PrefixQName.ParseQualifiedName(), System.prefix, and System.Xml.Xsl.XsltOld.XsltCompileContext.XsltFunctionImpl.ToString().