Terraria: Internal.Cryptography.HMACCommon.TryFinalizeHashAndReset
TryFinalizeHashAndReset()
bool Internal.Cryptography.HMACCommon.TryFinalizeHashAndReset (Span< byte > destination, out int bytesWritten) inline
Definition at line 83 of file HMACCommon.cs.
    {
        return _hMacProvider.TryFinalizeHashAndReset(destination, out bytesWritten);
    }
References Internal.Cryptography.HMACCommon._hMacProvider, System.destination, and Internal.Cryptography.HashProvider.TryFinalizeHashAndReset().
Referenced by System.Security.Cryptography.HMACMD5.TryHashFinal(), System.Security.Cryptography.HMACSHA1.TryHashFinal(), System.Security.Cryptography.HMACSHA256.TryHashFinal(), System.Security.Cryptography.HMACSHA384.TryHashFinal(), and System.Security.Cryptography.HMACSHA512.TryHashFinal().