Terraria: System.Net.Http.Json.HttpContentJsonExtensions.ReadFromJsonAsyncCore
ReadFromJsonAsyncCore() [2/2]
static async Task< object > System.Net.Http.Json.HttpContentJsonExtensions.ReadFromJsonAsyncCore (HttpContent content, Type type, Encoding sourceEncoding, JsonSerializerOptions options, CancellationToken cancellationToken) inline static private
Definition at line 37 of file HttpContentJsonExtensions.cs.
    {
        using (Stream contentStream2 = await GetContentStream(content, sourceEncoding, cancellationToken).ConfigureAwait(continueOnCapturedContext: false))
        {
            return await DeserializeAsyncHelper(contentStream2, type, options ?? JsonHelpers.s_defaultSerializerOptions, cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
        }
        [UnconditionalSuppressMessage("ReflectionAnalysis", "IL2026:RequiresUnreferencedCode", Justification = "Workaround for https://github.com/mono/linker/issues/1416. The outer method is marked as RequiresUnreferencedCode.")]
        [UnconditionalSuppressMessage("ReflectionAnalysis", "IL2067:UnrecognizedReflectionPattern", Justification = "Workaround for https://github.com/mono/linker/issues/1416. The outer method is marked as RequiresUnreferencedCode.")]
        static ValueTask<object> DeserializeAsyncHelper(Stream contentStream, Type returnType, JsonSerializerOptions options, CancellationToken cancellationToken)
        {
            return JsonSerializer.DeserializeAsync(contentStream, returnType, options, cancellationToken);
        }
    }
References System.cancellationToken, System.Text.Json.JsonSerializer.DeserializeAsync(), System.Text.Json.Dictionary, System.Net.Http.Json.HttpContentJsonExtensions.GetContentStream(), System.options, System.Net.Http.Json.JsonHelpers.s_defaultSerializerOptions, and System.type.
Referenced by System.Net.Http.Json.HttpContentJsonExtensions.ReadFromJsonAsync(), System.Net.Http.Json.HttpContentJsonExtensions.ReadFromJsonAsync(), and System.Net.Http.Json.HttpContentJsonExtensions.ReadFromJsonAsync< T >().