Terraria: System.Xml.Schema.XmlSchemaParticle.Empty
Empty
readonly XmlSchemaParticle System.Xml.Schema.XmlSchemaParticle.Empty = new EmptyParticle() static package inherited
Definition at line 26 of file XmlSchemaParticle.cs.
Referenced by System.Xml.Schema.Compiler.CannonicalizeAll(), System.Xml.Schema.SchemaCollectionCompiler.CannonicalizeAll(), System.Xml.Schema.Compiler.CannonicalizeChoice(), System.Xml.Schema.SchemaCollectionCompiler.CannonicalizeChoice(), System.Xml.Schema.Compiler.CannonicalizeGroupRef(), System.Xml.Schema.SchemaCollectionCompiler.CannonicalizeGroupRef(), System.Xml.Schema.Compiler.CannonicalizeParticle(), System.Xml.Schema.SchemaCollectionCompiler.CannonicalizeParticle(), System.Xml.Schema.Compiler.CannonicalizePointlessRoot(), System.Xml.Schema.Compiler.CannonicalizeSequence(), System.Xml.Schema.SchemaCollectionCompiler.CannonicalizeSequence(), System.Xml.Schema.Compiler.CleanupComplexType(), System.Xml.Schema.SchemaCollectionCompiler.CleanupComplexType(), System.Xml.Schema.XmlSchemaComplexType.ClearCompiledState(), System.Xml.Schema.XmlSchemaGroup.Clone(), System.Xml.Schema.SchemaCollectionCompiler.CompileCompexTypeElements(), System.Xml.Schema.Compiler.CompileComplexContent(), System.Xml.Schema.SchemaCollectionCompiler.CompileComplexContent(), System.Xml.Schema.Compiler.CompileComplexContentExtension(), System.Xml.Schema.SchemaCollectionCompiler.CompileComplexContentExtension(), System.Xml.Schema.Compiler.CompileComplexTypeElements(), System.Xml.Schema.Compiler.CompileContentTypeParticle(), System.Xml.Schema.SchemaCollectionCompiler.CompileContentTypeParticle(), System.Xml.Schema.Compiler.CompileGroup(), System.Xml.Schema.SchemaCollectionCompiler.CompileGroup(), System.Xml.Schema.Compiler.IsValidRestriction(), and System.Xml.Schema.SchemaCollectionCompiler.IsValidRestriction().