Terraria: System.Runtime.CompilerServices.AsyncTaskMethodBuilder.SetExistingTaskResult
SetExistingTaskResult()
static void System.Runtime.CompilerServices.AsyncTaskMethodBuilder< TResult >.SetExistingTaskResult (Task< TResult > task, TResult result) inline static package
Definition at line 337 of file AsyncTaskMethodBuilder.cs.
    {
        if (TplEventSource.Log.IsEnabled())
        {
            TplEventSource.Log.TraceOperationEnd(task.Id, AsyncCausalityStatus.Completed);
        }
        if (!task.TrySetResult(result))
        {
            ThrowHelper.ThrowInvalidOperationException(ExceptionResource.TaskT_TransitionToFinal_AlreadyCompleted);
        }
    }
References System.Threading.Tasks.TplEventSource.Log, System.task, and System.ThrowHelper.ThrowInvalidOperationException().
Referenced by System.Runtime.CompilerServices.AsyncIteratorMethodBuilder.Complete(), System.Runtime.CompilerServices.AsyncTaskMethodBuilder< TResult >.SetResult(), System.Runtime.CompilerServices.AsyncValueTaskMethodBuilder< TResult >.SetResult(), System.Runtime.CompilerServices.AsyncTaskMethodBuilder< TResult >.SetResult(), and System.Runtime.CompilerServices.AsyncValueTaskMethodBuilder< TResult >.SetResult().