Terraria: System.Runtime.CompilerServices.AsyncTaskMethodBuilder.GetStateMachineBox< TStateMachine >
GetStateMachineBox< TStateMachine >()
static IAsyncStateMachineBox System.Runtime.CompilerServices.AsyncTaskMethodBuilder< TResult >.GetStateMachineBox< TStateMachine > (ref TStateMachine stateMachine, [NotNull] ref Task< TResult > taskField) inline static private
Type Constraints
TStateMachine : IAsyncStateMachine
Definition at line 268 of file AsyncTaskMethodBuilder.cs.
                                                                                                                                                                      : IAsyncStateMachine
    {
        ExecutionContext executionContext = ExecutionContext.Capture();
        if (taskField is AsyncStateMachineBox<TStateMachine> asyncStateMachineBox)
        {
            if (asyncStateMachineBox.Context != executionContext)
            {
                asyncStateMachineBox.Context = executionContext;
            }
            return asyncStateMachineBox;
        }
        if (taskField is AsyncStateMachineBox<IAsyncStateMachine> asyncStateMachineBox2)
        {
            if (asyncStateMachineBox2.StateMachine == null)
            {
                Debugger.NotifyOfCrossThreadDependency();
                asyncStateMachineBox2.StateMachine = stateMachine;
            }
            asyncStateMachineBox2.Context = executionContext;
            return asyncStateMachineBox2;
        }
        Debugger.NotifyOfCrossThreadDependency();
        AsyncStateMachineBox<TStateMachine> asyncStateMachineBox3 = (AsyncStateMachineBox<TStateMachine>)(taskField = (AsyncMethodBuilderCore.TrackAsyncMethodCompletion ? CreateDebugFinalizableAsyncStateMachineBox<TStateMachine>() : new AsyncStateMachineBox<TStateMachine>()));
        asyncStateMachineBox3.StateMachine = stateMachine;
        asyncStateMachineBox3.Context = executionContext;
        if (TplEventSource.Log.IsEnabled())
        {
            TplEventSource.Log.TraceOperationBegin(asyncStateMachineBox3.Id, "Async: " + stateMachine.GetType().Name, 0L);
        }
        if (System.Threading.Tasks.Task.s_asyncDebuggingEnabled)
        {
            System.Threading.Tasks.Task.AddToActiveTasks(asyncStateMachineBox3);
        }
        return asyncStateMachineBox3;
    }
References System.Threading.Tasks.Task< TResult >.AddToActiveTasks(), System.Threading.ExecutionContext.Capture(), System.Runtime.CompilerServices.AsyncTaskMethodBuilder< TResult >.CreateDebugFinalizableAsyncStateMachineBox< TStateMachine >(), System.Threading.Tasks.Task< TResult >.Id, System.L, System.Threading.Tasks.TplEventSource.Log, System.Diagnostics.Debugger.NotifyOfCrossThreadDependency(), System.Threading.Tasks.Task< TResult >.s_asyncDebuggingEnabled, System.stateMachine, and System.Runtime.CompilerServices.AsyncMethodBuilderCore.TrackAsyncMethodCompletion.