Terraria: System.Net.Quic.Implementations.Mock.MockStream.WriteAsync
WriteAsync() [1/6]
override async ValueTask System.Net.Quic.Implementations.Mock.MockStream.WriteAsync (ReadOnlyMemory< byte > buffer, bool endStream, CancellationToken cancellationToken = default(CancellationToken)) inline package
Definition at line 211 of file MockStream.cs.
    {
        CheckDisposed();
        if (Volatile.Read(ref _writesCanceled))
        {
            cancellationToken.ThrowIfCancellationRequested();
            throw new OperationCanceledException();
        }
        StreamBuffer streamBuffer = WriteStreamBuffer;
        if (streamBuffer == null)
        {
            throw new NotSupportedException();
        }
        long? connectionError = _connection.ConnectionError;
        if (connectionError.HasValue)
        {
            long valueOrDefault = connectionError.GetValueOrDefault();
            throw new QuicConnectionAbortedException(valueOrDefault);
        }
        long num = (_isInitiator ? _streamState._inboundWriteErrorCode : _streamState._outboundWriteErrorCode);
        if (num != 0L)
        {
            throw new QuicStreamAbortedException(num);
        }
        using (cancellationToken.UnsafeRegister(delegate(object s)
        {
            MockStream mockStream = (MockStream)s;
            Volatile.Write(ref mockStream._writesCanceled, value: true);
        }, this))
        {
            await streamBuffer.WriteAsync(buffer, cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
            if (endStream)
            {
                streamBuffer.EndWrite();
                WritesCompletedTcs.TrySetResult();
            }
        }
    }
References System.Net.Quic.Implementations.Mock.MockStream.MockStream(), System.Net.Quic.Implementations.Mock.MockStream._connection, System.Net.Quic.Implementations.Mock.MockStream._isInitiator, System.Net.Quic.Implementations.Mock.MockStream.StreamState._outboundWriteErrorCode, System.Net.Quic.Implementations.Mock.MockStream._streamState, System.Net.Quic.Implementations.Mock.MockStream._writesCanceled, System.buffer, System.cancellationToken, System.Net.Quic.Implementations.Mock.MockStream.CheckDisposed(), System.Threading.Tasks.ValueTask< TResult >.ConfigureAwait(), System.Net.Quic.Implementations.Mock.MockConnection.ConnectionError, System.IO.StreamBuffer.EndWrite(), System.L, System.Threading.Volatile.Read(), System.s, System.Threading.Tasks.TaskCompletionSource< TResult >.TrySetResult(), System.value, System.Threading.Volatile.Write(), System.IO.StreamBuffer.WriteAsync(), System.Net.Quic.Implementations.Mock.MockStream.WritesCompletedTcs, and System.Net.Quic.Implementations.Mock.MockStream.WriteStreamBuffer.