Terraria: System.Net.Quic.Implementations.Mock.MockStream.ReadAsync
ReadAsync()
override async ValueTask< int > System.Net.Quic.Implementations.Mock.MockStream.ReadAsync (Memory< byte > buffer, CancellationToken cancellationToken = default(CancellationToken)) inline package
Definition at line 165 of file MockStream.cs.
    {
        CheckDisposed();
        StreamBuffer readStreamBuffer = ReadStreamBuffer;
        if (readStreamBuffer == null)
        {
            throw new NotSupportedException();
        }
        int num = await readStreamBuffer.ReadAsync(buffer, cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
        if (num == 0)
        {
            long? connectionError = _connection.ConnectionError;
            if (connectionError.HasValue)
            {
                long valueOrDefault = connectionError.GetValueOrDefault();
                throw new QuicConnectionAbortedException(valueOrDefault);
            }
            long num2 = (_isInitiator ? _streamState._inboundReadErrorCode : _streamState._outboundReadErrorCode);
            if (num2 != 0L)
            {
                throw (num2 == -1) ? ((QuicException)new QuicOperationAbortedException()) : ((QuicException)new QuicStreamAbortedException(num2));
            }
        }
        return num;
    }
References System.Net.Quic.Implementations.Mock.MockStream._connection, System.Net.Quic.Implementations.Mock.MockStream._isInitiator, System.Net.Quic.Implementations.Mock.MockStream.StreamState._outboundReadErrorCode, System.Net.Quic.Implementations.Mock.MockStream._streamState, System.buffer, System.cancellationToken, System.Net.Quic.Implementations.Mock.MockStream.CheckDisposed(), System.Threading.Tasks.ValueTask< TResult >.ConfigureAwait(), System.Net.Quic.Implementations.Mock.MockConnection.ConnectionError, System.L, System.IO.StreamBuffer.ReadAsync(), and System.Net.Quic.Implementations.Mock.MockStream.ReadStreamBuffer.