Terraria: System.Net.Quic.Implementations.Mock.MockStream.Write
Write()
override void System.Net.Quic.Implementations.Mock.MockStream.Write (ReadOnlySpan< byte > buffer) inline package
Definition at line 191 of file MockStream.cs.
    {
        CheckDisposed();
        if (Volatile.Read(ref _writesCanceled))
        {
            throw new OperationCanceledException();
        }
        StreamBuffer writeStreamBuffer = WriteStreamBuffer;
        if (writeStreamBuffer == null)
        {
            throw new NotSupportedException();
        }
        writeStreamBuffer.Write(buffer);
    }
References System.Net.Quic.Implementations.Mock.MockStream._writesCanceled, System.buffer, System.Net.Quic.Implementations.Mock.MockStream.CheckDisposed(), System.Threading.Volatile.Read(), System.IO.StreamBuffer.Write(), and System.Net.Quic.Implementations.Mock.MockStream.WriteStreamBuffer.