Terraria: System.Net.Quic.Implementations.Mock.MockStream.Shutdown
Shutdown()
override void System.Net.Quic.Implementations.Mock.MockStream.Shutdown () inline package
Definition at line 320 of file MockStream.cs.
    {
        CheckDisposed();
        WriteStreamBuffer?.EndWrite();
        if (_streamState._inboundStreamBuffer == null)
        {
            _connection.LocalStreamLimit.Unidirectional.Decrement();
        }
        else
        {
            _connection.LocalStreamLimit.Bidirectional.Decrement();
        }
        WritesCompletedTcs.TrySetResult();
    }
References System.Net.Quic.Implementations.Mock.MockStream._connection, System.Net.Quic.Implementations.Mock.MockStream.StreamState._inboundStreamBuffer, System.Net.Quic.Implementations.Mock.MockStream._streamState, System.Net.Quic.Implementations.Mock.MockConnection.PeerStreamLimit.Bidirectional, System.Net.Quic.Implementations.Mock.MockStream.CheckDisposed(), System.Net.Quic.Implementations.Mock.MockConnection.StreamLimit.Decrement(), System.IO.StreamBuffer.EndWrite(), System.Net.Quic.Implementations.Mock.MockConnection.LocalStreamLimit, System.Threading.Tasks.TaskCompletionSource< TResult >.TrySetResult(), System.Net.Quic.Implementations.Mock.MockConnection.PeerStreamLimit.Unidirectional, System.Net.Quic.Implementations.Mock.MockStream.WritesCompletedTcs, and System.Net.Quic.Implementations.Mock.MockStream.WriteStreamBuffer.
Referenced by System.Net.Quic.Implementations.Mock.MockStream.Dispose(), and System.Net.Quic.Implementations.Mock.MockStream.DisposeAsync().