Terraria: UIGamepadHelper.MoveToVisuallyClosestPoint
MoveToVisuallyClosestPoint() [2/2]
void UIGamepadHelper.MoveToVisuallyClosestPoint (List< UILinkPoint > lostrefpoints) inline
     {
         _ = UILinkPointNavigator.Points;
         Vector2 mouseScreen = Main.MouseScreen;
         UILinkPoint uILinkPoint = null;
         foreach (UILinkPoint lostrefpoint in lostrefpoints)
         {
             if (uILinkPoint == null || Vector2.Distance(mouseScreen, uILinkPoint.Position) > Vector2.Distance(mouseScreen, lostrefpoint.Position))
             {
                 uILinkPoint = lostrefpoint;
             }
         }
         if (uILinkPoint != null)
         {
             UILinkPointNavigator.ChangePoint(uILinkPoint.ID);
         }
     }
References UILinkPointNavigator.ChangePoint(), Main.MouseScreen, UILinkPointNavigator.Points, and UILinkPoint.Position.
Referenced by AWorkshopPublishInfoState< TPublishedObjectType >.SetupGamepadPoints(), UIReportsPage.SetupGamepadPoints(), UIResourcePackInfoMenu.SetupGamepadPoints(), UIResourcePackSelectionMenu.SetupGamepadPoints(), UIWorkshopHub.SetupGamepadPoints(), and TryMovingBackIntoCreativeGridIfOutOfIt().