Terraria: ReLogic.Content.Asset.Empty
Empty
readonly Asset<T> ReLogic.Content.Asset< T >.Empty = new Asset<T>("") static
Referenced by ReLogic.Content.AssetRepository.AssetRepository(), ReLogic.Content.AssetPathHelper.CleanPath(), Terraria.Utils.Frame(), Terraria.Mount.Initialize(), Terraria.Initializers.PlayerDataInitializer.LoadStarterMale(), Terraria.Main.MouseOversClear(), Terraria.Mount.SetAsHorse(), Terraria.Mount.SetAsMinecart(), and Terraria.Main.SetBackColor().