Terraria: System.Resources.ResourceManager.GetResourceSet
GetResourceSet()
virtual ? ResourceSet System.Resources.ResourceManager.GetResourceSet (CultureInfo culture, bool createIfNotExists, bool tryParents) inline virtual
Definition at line 313 of file ResourceManager.cs.
    {
        if (culture == null)
        {
            throw new ArgumentNullException("culture");
        }
        Dictionary<string, ResourceSet> resourceSets = _resourceSets;
        if (resourceSets != null)
        {
            lock (resourceSets)
            {
                if (resourceSets.TryGetValue(culture.Name, out var value))
                {
                    return value;
                }
            }
        }
        if (_useManifest && culture.HasInvariantCultureName)
        {
            string resourceFileName = GetResourceFileName(culture);
            Stream manifestResourceStream = MainAssembly.GetManifestResourceStream(_locationInfo, resourceFileName);
            if (createIfNotExists && manifestResourceStream != null)
            {
                ResourceSet value = ((ManifestBasedResourceGroveler)_resourceGroveler).CreateResourceSet(manifestResourceStream, MainAssembly);
                AddResourceSet(resourceSets, culture.Name, ref value);
                return value;
            }
        }
        return InternalGetResourceSet(culture, createIfNotExists, tryParents);
    }
References System.Resources.ResourceManager._locationInfo, System.Resources.ResourceManager._resourceGroveler, System.Resources.ResourceManager._resourceSets, System.Resources.ResourceManager._useManifest, System.Resources.ResourceManager.AddResourceSet(), System.culture, System.Reflection.Assembly.GetManifestResourceStream(), System.Resources.ResourceManager.GetResourceFileName(), System.Resources.ResourceManager.InternalGetResourceSet(), System.Resources.ResourceManager.MainAssembly, System.Collections.Generic.Dictionary< TKey, TValue >.TryGetValue(), and System.value.
Referenced by System.ComponentModel.ComponentResourceManager.FillResources().