Terraria: System.Resources.ResourceManager.IsDefaultType
IsDefaultType()
static bool System.Resources.ResourceManager.IsDefaultType (string asmTypeName, string typeName) inline static package
Definition at line 437 of file ResourceManager.cs.
    {
        int num = asmTypeName.IndexOf(',');
        if (((num == -1) ? asmTypeName.Length : num) != typeName.Length)
        {
            return false;
        }
        if (string.Compare(asmTypeName, 0, typeName, 0, typeName.Length, StringComparison.Ordinal) != 0)
        {
            return false;
        }
        if (num == -1)
        {
            return true;
        }
        while (char.IsWhiteSpace(asmTypeName[++num]))
        {
        }
        AssemblyName assemblyName = new AssemblyName(asmTypeName.Substring(num));
        return string.Equals(assemblyName.Name, "mscorlib", StringComparison.OrdinalIgnoreCase);
    }
Referenced by System.Resources.ManifestBasedResourceGroveler.CanUseDefaultResourceClasses(), System.Resources.ManifestBasedResourceGroveler.InternalGetResourceSetFromSerializedData(), and System.Resources.ResourceReader.ValidateReaderType().