Terraria: System.Resources.ResourceManager.InternalGetResourceSet
InternalGetResourceSet()
virtual ? ResourceSet System.Resources.ResourceManager.InternalGetResourceSet (CultureInfo culture, bool createIfNotExists, bool tryParents) inline protected virtual
Definition at line 344 of file ResourceManager.cs.
    {
        Dictionary<string, ResourceSet> resourceSets = _resourceSets;
        ResourceSet value = null;
        CultureInfo cultureInfo = null;
        lock (resourceSets)
        {
            if (resourceSets.TryGetValue(culture.Name, out value))
            {
                return value;
            }
        }
        ResourceFallbackManager resourceFallbackManager = new ResourceFallbackManager(culture, _neutralResourcesCulture, tryParents);
        foreach (CultureInfo item in resourceFallbackManager)
        {
            lock (resourceSets)
            {
                if (resourceSets.TryGetValue(item.Name, out value))
                {
                    if (culture != item)
                    {
                        cultureInfo = item;
                    }
                    break;
                }
            }
            value = _resourceGroveler.GrovelForResourceSet(item, resourceSets, tryParents, createIfNotExists);
            if (value != null)
            {
                cultureInfo = item;
                break;
            }
        }
        if (value != null && cultureInfo != null)
        {
            foreach (CultureInfo item2 in resourceFallbackManager)
            {
                AddResourceSet(resourceSets, item2.Name, ref value);
                if (item2 == cultureInfo)
                {
                    break;
                }
            }
        }
        return value;
    }
References System.Resources.ResourceManager._neutralResourcesCulture, System.Resources.ResourceManager._resourceGroveler, System.Resources.ResourceManager._resourceSets, System.Resources.ResourceManager.AddResourceSet(), System.culture, System.Resources.IResourceGroveler.GrovelForResourceSet(), System.item, System.Collections.Generic.Dictionary< TKey, TValue >.TryGetValue(), and System.value.
Referenced by System.Resources.ResourceManager.GetObject(), System.Resources.ResourceManager.GetResourceSet(), and System.Resources.ResourceManager.GetString().