Terraria: System.Reflection.Metadata.Ecma335.TypeDefTableReader.FindTypeContainingField
FindTypeContainingField()
TypeDefinitionHandle System.Reflection.Metadata.Ecma335.TypeDefTableReader.FindTypeContainingField (int fieldDefOrPtrRowId, int numberOfFields) inline package
Definition at line 126 of file TypeDefTableReader.cs.
    {
        int numberOfRows = NumberOfRows;
        int num = Block.BinarySearchForSlot(numberOfRows, RowSize, _FieldListOffset, (uint)fieldDefOrPtrRowId, _IsFieldRefSizeSmall);
        int num2 = num + 1;
        if (num2 == 0)
        {
            return default(TypeDefinitionHandle);
        }
        if (num2 > numberOfRows)
        {
            if (fieldDefOrPtrRowId <= numberOfFields)
            {
                return TypeDefinitionHandle.FromRowId(numberOfRows);
            }
            return default(TypeDefinitionHandle);
        }
        int fieldStart = GetFieldStart(num2);
        if (fieldStart == fieldDefOrPtrRowId)
        {
            while (num2 < numberOfRows)
            {
                int num3 = num2 + 1;
                fieldStart = GetFieldStart(num3);
                if (fieldStart != fieldDefOrPtrRowId)
                {
                    break;
                }
                num2 = num3;
            }
        }
        return TypeDefinitionHandle.FromRowId(num2);
    }
References System.Reflection.Metadata.Ecma335.TypeDefTableReader._FieldListOffset, System.Reflection.Metadata.Ecma335.TypeDefTableReader._IsFieldRefSizeSmall, System.Reflection.Internal.MemoryBlock.BinarySearchForSlot(), System.Reflection.Metadata.Ecma335.TypeDefTableReader.Block, System.Reflection.Metadata.TypeDefinitionHandle.FromRowId(), System.Reflection.Metadata.Ecma335.TypeDefTableReader.GetFieldStart(), System.Reflection.Metadata.Ecma335.TypeDefTableReader.NumberOfRows, and System.Reflection.Metadata.Ecma335.TypeDefTableReader.RowSize.
Referenced by System.Reflection.Metadata.MetadataReader.GetDeclaringType().