Terraria: System.Reflection.Metadata.Ecma335.TypeDefTableReader.GetFieldStart
GetFieldStart()
int System.Reflection.Metadata.Ecma335.TypeDefTableReader.GetFieldStart (int rowId) inline package
Definition at line 80 of file TypeDefTableReader.cs.
    {
        int num = (rowId - 1) * RowSize;
        return Block.PeekReference(num + _FieldListOffset, _IsFieldRefSizeSmall);
    }
References System.Reflection.Metadata.Ecma335.TypeDefTableReader._FieldListOffset, System.Reflection.Metadata.Ecma335.TypeDefTableReader._IsFieldRefSizeSmall, System.Reflection.Metadata.Ecma335.TypeDefTableReader.Block, System.Reflection.Internal.MemoryBlock.PeekReference(), and System.Reflection.Metadata.Ecma335.TypeDefTableReader.RowSize.
Referenced by System.Reflection.Metadata.Ecma335.TypeDefTableReader.FindTypeContainingField(), and System.Reflection.Metadata.MetadataReader.GetFieldRange().