Terraria: System.Reflection.Metadata.Ecma335.TypeDefTableReader.GetFlags
GetFlags()
TypeAttributes System.Reflection.Metadata.Ecma335.TypeDefTableReader.GetFlags (TypeDefinitionHandle handle) inline package
Definition at line 50 of file TypeDefTableReader.cs.
    {
        int num = (handle.RowId - 1) * RowSize;
        return (TypeAttributes)Block.PeekUInt32(num + _FlagsOffset);
    }
References System.Reflection.Metadata.Ecma335.TypeDefTableReader._FlagsOffset, System.Reflection.Metadata.Ecma335.TypeDefTableReader.Block, System.Reflection.Internal.MemoryBlock.PeekUInt32(), and System.Reflection.Metadata.Ecma335.TypeDefTableReader.RowSize.
Referenced by System.Reflection.Metadata.MetadataReader.CalculateMethodDefTreatmentAndRowId(), System.Reflection.Metadata.MetadataReader.CalculateTypeDefTreatmentAndRowId(), System.Reflection.Metadata.MetadataReader.GetAttributeTypeNameRaw(), System.Reflection.Metadata.TypeDefinition.GetProjectedFlags(), and System.Reflection.Metadata.MetadataReader.IsClrImplementationType().