Terraria: System.Reflection.Metadata.Ecma335.TypeDefTableReader.GetNamespace
GetNamespace()
StringHandle System.Reflection.Metadata.Ecma335.TypeDefTableReader.GetNamespace (TypeDefinitionHandle handle) inline package
Definition at line 62 of file TypeDefTableReader.cs.
    {
        int num = (handle.RowId - 1) * RowSize;
        return StringHandle.FromOffset(Block.PeekHeapReference(num + _NamespaceOffset, _IsStringHeapRefSizeSmall));
    }
References System.Reflection.Metadata.Ecma335.TypeDefTableReader._IsStringHeapRefSizeSmall, System.Reflection.Metadata.Ecma335.TypeDefTableReader._NamespaceOffset, System.Reflection.Metadata.Ecma335.TypeDefTableReader.Block, System.Reflection.Metadata.StringHandle.FromOffset(), System.Reflection.Internal.MemoryBlock.PeekHeapReference(), and System.Reflection.Metadata.Ecma335.TypeDefTableReader.RowSize.
Referenced by System.Reflection.Metadata.MetadataReader.CalculateCustomAttributeValueTreatment(), System.Reflection.Metadata.MetadataReader.GetAttributeTypeNameRaw(), and System.Reflection.Metadata.TypeDefinition.GetProjectedNamespaceString().