Terraria: System.Dynamic.ExpandoObject.MetaExpando.BindSetMember
BindSetMember()
override DynamicMetaObject System.Dynamic.ExpandoObject.MetaExpando.BindSetMember (SetMemberBinder binder, DynamicMetaObject value) inline virtual
Reimplemented from System.Dynamic.DynamicMetaObject.
Definition at line 309 of file ExpandoObject.cs.
        {
            ContractUtils.RequiresNotNull(binder, "binder");
            ContractUtils.RequiresNotNull(value, "value");
            ExpandoClass klass;
            int index;
            ExpandoClass classEnsureIndex = GetClassEnsureIndex(binder.Name, binder.IgnoreCase, Value, out klass, out index);
            return AddDynamicTestAndDefer(binder, klass, classEnsureIndex, new DynamicMetaObject(System.Linq.Expressions.Expression.Call(s_expandoTrySetValue, GetLimitedSelf(), System.Linq.Expressions.Expression.Constant(klass, typeof(object)), System.Linq.Expressions.Utils.Constant(index), System.Linq.Expressions.Expression.Convert(value.Expression, typeof(object)), System.Linq.Expressions.Expression.Constant(binder.Name), System.Linq.Expressions.Utils.Constant(binder.IgnoreCase)), BindingRestrictions.Empty));
        }
References System.Dynamic.DynamicMetaObject.DynamicMetaObject(), System.Dynamic.ExpandoObject.MetaExpando.AddDynamicTestAndDefer(), System.Linq.Expressions.Expression< TDelegate >.Call(), System.Linq.Expressions.Utils.Constant(), System.Linq.Expressions.Expression< TDelegate >.Constant(), System.Linq.Expressions.Expression< TDelegate >.Convert(), System.Dynamic.BindingRestrictions.Empty, System.Dynamic.ExpandoObject.MetaExpando.GetClassEnsureIndex(), System.Dynamic.ExpandoObject.MetaExpando.GetLimitedSelf(), System.index, System.Dynamic.Utils.ContractUtils.RequiresNotNull(), System.Dynamic.ExpandoObject.s_expandoTrySetValue, System.Dynamic.ExpandoObject.MetaExpando.Value, and System.value.