Terraria: System.Dynamic.ExpandoObject.MetaExpando.BindGetOrInvokeMember
BindGetOrInvokeMember()
DynamicMetaObject System.Dynamic.ExpandoObject.MetaExpando.BindGetOrInvokeMember (DynamicMetaObjectBinder binder, string name, bool ignoreCase, DynamicMetaObject fallback, Func< DynamicMetaObject, DynamicMetaObject > fallbackInvoke) inline private
Definition at line 282 of file ExpandoObject.cs.
        {
            ExpandoClass @class = Value.Class;
            int valueIndex = @class.GetValueIndex(name, ignoreCase, Value);
            ParameterExpression parameterExpression = System.Linq.Expressions.Expression.Parameter(typeof(object), "value");
            Expression test = System.Linq.Expressions.Expression.Call(s_expandoTryGetValue, GetLimitedSelf(), System.Linq.Expressions.Expression.Constant(@class, typeof(object)), System.Linq.Expressions.Utils.Constant(valueIndex), System.Linq.Expressions.Expression.Constant(name), System.Linq.Expressions.Utils.Constant(ignoreCase), parameterExpression);
            DynamicMetaObject dynamicMetaObject = new DynamicMetaObject(parameterExpression, BindingRestrictions.Empty);
            if (fallbackInvoke != null)
            {
                dynamicMetaObject = fallbackInvoke(dynamicMetaObject);
            }
            dynamicMetaObject = new DynamicMetaObject(System.Linq.Expressions.Expression.Block(new TrueReadOnlyCollection<ParameterExpression>(parameterExpression), new TrueReadOnlyCollection<Expression>(System.Linq.Expressions.Expression.Condition(test, dynamicMetaObject.Expression, fallback.Expression, typeof(object)))), dynamicMetaObject.Restrictions.Merge(fallback.Restrictions));
            return AddDynamicTestAndDefer(binder, Value.Class, null, dynamicMetaObject);
        }
References System.Dynamic.DynamicMetaObject.DynamicMetaObject(), System.Dynamic.ExpandoObject.MetaExpando.AddDynamicTestAndDefer(), System.Linq.Expressions.Expression< TDelegate >.Block(), System.Linq.Expressions.Expression< TDelegate >.Call(), System.Linq.Expressions.Expression< TDelegate >.Condition(), System.Linq.Expressions.Utils.Constant(), System.Linq.Expressions.Expression< TDelegate >.Constant(), System.Dynamic.BindingRestrictions.Empty, System.Dynamic.ExpandoObject.MetaExpando.GetLimitedSelf(), System.Linq.Expressions.Expression< TDelegate >.Parameter(), System.Dynamic.ExpandoObject.s_expandoTryGetValue, and System.Dynamic.ExpandoObject.MetaExpando.Value.
Referenced by System.Dynamic.ExpandoObject.MetaExpando.BindGetMember(), and System.Dynamic.ExpandoObject.MetaExpando.BindInvokeMember().