Terraria: System.Dynamic.ExpandoObject.MetaExpando.GetLimitedSelf
GetLimitedSelf()
Expression System.Dynamic.ExpandoObject.MetaExpando.GetLimitedSelf () inline private
Definition at line 371 of file ExpandoObject.cs.
        {
            if (TypeUtils.AreEquivalent(base.Expression.Type, base.LimitType))
            {
                return base.Expression;
            }
            return System.Linq.Expressions.Expression.Convert(base.Expression, base.LimitType);
        }
References System.Dynamic.Utils.TypeUtils.AreEquivalent(), and System.Linq.Expressions.Expression< TDelegate >.Convert().
Referenced by System.Dynamic.ExpandoObject.MetaExpando.AddDynamicTestAndDefer(), System.Dynamic.ExpandoObject.MetaExpando.BindDeleteMember(), System.Dynamic.ExpandoObject.MetaExpando.BindGetOrInvokeMember(), and System.Dynamic.ExpandoObject.MetaExpando.BindSetMember().