Terraria: System.Dynamic.ExpandoObject.MetaExpando.AddDynamicTestAndDefer
AddDynamicTestAndDefer()
DynamicMetaObject System.Dynamic.ExpandoObject.MetaExpando.AddDynamicTestAndDefer (DynamicMetaObjectBinder binder, ExpandoClass klass, ExpandoClass originalClass, DynamicMetaObject succeeds) inline private
Definition at line 343 of file ExpandoObject.cs.
        {
            Expression expression = succeeds.Expression;
            if (originalClass != null)
            {
                expression = System.Linq.Expressions.Expression.Block(System.Linq.Expressions.Expression.Call(null, s_expandoPromoteClass, GetLimitedSelf(), System.Linq.Expressions.Expression.Constant(originalClass, typeof(object)), System.Linq.Expressions.Expression.Constant(klass, typeof(object))), succeeds.Expression);
            }
            return new DynamicMetaObject(System.Linq.Expressions.Expression.Condition(System.Linq.Expressions.Expression.Call(null, s_expandoCheckVersion, GetLimitedSelf(), System.Linq.Expressions.Expression.Constant(originalClass ?? klass, typeof(object))), expression, binder.GetUpdateExpression(expression.Type)), GetRestrictions().Merge(succeeds.Restrictions));
        }
References System.Dynamic.DynamicMetaObject.DynamicMetaObject(), System.Linq.Expressions.Expression< TDelegate >.Block(), System.Linq.Expressions.Expression< TDelegate >.Call(), System.Linq.Expressions.Expression< TDelegate >.Condition(), System.Linq.Expressions.Expression< TDelegate >.Constant(), System.Dynamic.ExpandoObject.MetaExpando.GetLimitedSelf(), System.Dynamic.ExpandoObject.MetaExpando.GetRestrictions(), System.Dynamic.ExpandoObject.s_expandoCheckVersion, and System.Dynamic.ExpandoObject.s_expandoPromoteClass.
Referenced by System.Dynamic.ExpandoObject.MetaExpando.BindDeleteMember(), System.Dynamic.ExpandoObject.MetaExpando.BindGetOrInvokeMember(), and System.Dynamic.ExpandoObject.MetaExpando.BindSetMember().