Terraria: Terraria.Net.NetManager.SendToClient
SendToClient()
void Terraria.Net.NetManager.SendToClient (NetPacket packet, int playerId) inline
    {
        SendData(Netplay.Clients[playerId].Socket, packet);
    }
References Terraria.Netplay.Clients, Terraria.Net.NetManager.SendData(), and Terraria.RemoteClient.Socket.
Referenced by Terraria.Chat.ChatHelper.DisplayMessageOnClient(), Terraria.GameContent.Bestiary.NPCKillsTracker.OnPlayerJoining(), Terraria.GameContent.Bestiary.NPCWasChatWithTracker.OnPlayerJoining(), Terraria.GameContent.Bestiary.NPCWasNearPlayerTracker.OnPlayerJoining(), Terraria.GameContent.TeleportPylonsSystem.OnPlayerJoining(), Terraria.GameContent.NetModules.NetLiquidModule.PrepareAndSendToEachPlayerSeparately(), Terraria.Chat.ChatHelper.SendChatMessageToClientAs(), and Terraria.GameContent.Creative.CreativePowerManager.SyncThingsToJoiningPlayer().