Terraria: Terraria.Net.NetManager.SendToSelf
SendToSelf()
void Terraria.Net.NetManager.SendToSelf (NetPacket packet) inline
Definition at line 79 of file NetManager.cs.
    {
        packet.Reader.BaseStream.Position = 3L;
        Read(packet.Reader, Main.myPlayer, packet.Length);
        SendCallback(packet);
        Main.ActiveNetDiagnosticsUI.CountSentModuleMessage(packet.Id, packet.Length);
    }
References Terraria.Main.ActiveNetDiagnosticsUI, Terraria.Net.NetPacket.Id, Terraria.Net.NetPacket.Length, Terraria.Main.myPlayer, Terraria.Net.NetManager.Read(), Terraria.Net.NetPacket.Reader, and Terraria.Net.NetManager.SendCallback().
Referenced by Terraria.Net.NetManager.BroadcastOrLoopback(), Terraria.Net.NetManager.SendToServerAndSelf(), and Terraria.Net.NetManager.SendToServerOrLoopback().