Terraria: Terraria.Net.NetManager.SendData
SendData()
void Terraria.Net.NetManager.SendData (ISocket socket, NetPacket packet) inline private
    {
        if (Main.netMode != 0)
        {
            packet.ShrinkToFit();
            try
            {
                socket.AsyncSend(packet.Buffer.Data, 0, packet.Length, SendCallback, packet);
            }
            catch
            {
            }
            Main.ActiveNetDiagnosticsUI.CountSentModuleMessage(packet.Id, packet.Length);
        }
    }
References Terraria.Main.ActiveNetDiagnosticsUI, Terraria.Net.Sockets.ISocket.AsyncSend(), Terraria.Net.NetPacket.Buffer, Terraria.Net.NetPacket.Id, Terraria.Net.NetPacket.Length, Terraria.Main.netMode, Terraria.Net.NetManager.SendCallback(), and Terraria.Net.NetPacket.ShrinkToFit().
Referenced by Terraria.Net.NetManager.Broadcast(), Terraria.Net.NetManager.Broadcast(), Terraria.Net.NetManager.SendToClient(), and Terraria.Net.NetManager.SendToServer().