Terraria: System.Xml.Schema.SchemaInfo.Add
Add()
void System.Xml.Schema.SchemaInfo.Add (SchemaInfo sinfo, ValidationEventHandler eventhandler) inline package
Definition at line 287 of file SchemaInfo.cs.
    {
        if (_schemaType == SchemaType.None)
        {
            _schemaType = sinfo.SchemaType;
        }
        else if (_schemaType != sinfo.SchemaType)
        {
            eventhandler?.Invoke(this, new ValidationEventArgs(new XmlSchemaException(System.SR.Sch_MixSchemaTypes, string.Empty)));
            return;
        }
        foreach (string key in sinfo.TargetNamespaces.Keys)
        {
            if (!_targetNamespaces.ContainsKey(key))
            {
                _targetNamespaces.Add(key, value: true);
            }
        }
        foreach (KeyValuePair<XmlQualifiedName, SchemaElementDecl> elementDecl in sinfo._elementDecls)
        {
            if (!_elementDecls.ContainsKey(elementDecl.Key))
            {
                _elementDecls.Add(elementDecl.Key, elementDecl.Value);
            }
        }
        foreach (KeyValuePair<XmlQualifiedName, SchemaElementDecl> item in sinfo._elementDeclsByType)
        {
            if (!_elementDeclsByType.ContainsKey(item.Key))
            {
                _elementDeclsByType.Add(item.Key, item.Value);
            }
        }
        foreach (SchemaAttDef value in sinfo.AttributeDecls.Values)
        {
            if (!_attributeDecls.ContainsKey(value.Name))
            {
                _attributeDecls.Add(value.Name, value);
            }
        }
        foreach (SchemaNotation value2 in sinfo.Notations.Values)
        {
            if (!Notations.ContainsKey(value2.Name.Name))
            {
                Notations.Add(value2.Name.Name, value2);
            }
        }
    }
References System.Xml.Schema.SchemaInfo._attributeDecls, System.Xml.Schema.SchemaInfo._elementDecls, System.Xml.Schema.SchemaInfo._elementDeclsByType, System.Xml.Schema.SchemaInfo._schemaType, System.Xml.Schema.SchemaInfo._targetNamespaces, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Collections.Generic.Dictionary< TKey, TValue >.ContainsKey(), System.item, System.key, System.Collections.Generic.Dictionary< TKey, TValue >.Keys, System.Xml.Schema.SchemaInfo.Notations, System.SR.Sch_MixSchemaTypes, System.value, and System.Collections.Generic.Dictionary< TKey, TValue >.Values.
Referenced by System.Xml.Schema.XmlSchemaSet.Compile(), System.Xml.Schema.XdrBuilder.LoadSchema(), and System.Xml.Schema.XdrValidator.ProcessInlineSchema().