Terraria: System.Xml.Schema.SchemaInfo.GetAttributeXsd
GetAttributeXsd() [2/2]
SchemaAttDef System.Xml.Schema.SchemaInfo.GetAttributeXsd (SchemaElementDecl ed, XmlQualifiedName qname, XmlSchemaObject partialValidationType, out AttributeMatchState attributeMatchState) inline package
Definition at line 192 of file SchemaInfo.cs.
    {
        SchemaAttDef value = null;
        attributeMatchState = AttributeMatchState.UndeclaredAttribute;
        if (ed != null)
        {
            value = ed.GetAttDef(qname);
            if (value != null)
            {
                attributeMatchState = AttributeMatchState.AttributeFound;
                return value;
            }
            XmlSchemaAnyAttribute anyAttribute = ed.AnyAttribute;
            if (anyAttribute != null)
            {
                if (!anyAttribute.NamespaceList.Allows(qname))
                {
                    attributeMatchState = AttributeMatchState.ProhibitedAnyAttribute;
                }
                else if (anyAttribute.ProcessContentsCorrect != XmlSchemaContentProcessing.Skip)
                {
                    if (_attributeDecls.TryGetValue(qname, out value))
                    {
                        if (value.Datatype.TypeCode == XmlTypeCode.Id)
{
                            attributeMatchState = AttributeMatchState.AnyIdAttributeFound;
                        }
                        else
{
                            attributeMatchState = AttributeMatchState.AttributeFound;
                        }
                    }
                    else if (anyAttribute.ProcessContentsCorrect == XmlSchemaContentProcessing.Lax)
                    {
                        attributeMatchState = AttributeMatchState.AnyAttributeLax;
                    }
                }
                else
                {
                    attributeMatchState = AttributeMatchState.AnyAttributeSkip;
                }
            }
            else if (ed.ProhibitedAttributes.ContainsKey(qname))
            {
                attributeMatchState = AttributeMatchState.ProhibitedAttribute;
            }
        }
        else if (partialValidationType != null)
        {
            if (partialValidationType is XmlSchemaAttribute xmlSchemaAttribute)
            {
                if (qname.Equals(xmlSchemaAttribute.QualifiedName))
                {
                    value = xmlSchemaAttribute.AttDef;
                    attributeMatchState = AttributeMatchState.AttributeFound;
                }
                else
                {
                    attributeMatchState = AttributeMatchState.AttributeNameMismatch;
                }
            }
            else
            {
                attributeMatchState = AttributeMatchState.ValidateAttributeInvalidCall;
            }
        }
        else if (_attributeDecls.TryGetValue(qname, out value))
        {
            attributeMatchState = AttributeMatchState.AttributeFound;
        }
        else
        {
            attributeMatchState = AttributeMatchState.UndeclaredElementAndAttribute;
        }
        return value;
    }
References System.Xml.Schema.SchemaInfo._attributeDecls, System.Collections.Generic.Dictionary< TKey, TValue >.ContainsKey(), System.Xml.XmlQualifiedName.Equals(), System.Collections.Generic.Dictionary< TKey, TValue >.TryGetValue(), and System.value.
Referenced by System.Xml.Schema.SchemaInfo.GetAttributeXsd(), System.Xml.Schema.XmlSchemaValidator.ValidateAttribute(), and System.Xml.Schema.XsdValidator.ValidateStartElement().