Terraria: PlayerDrawLayers.DrawPlayer_14_Shoes
DrawPlayer_14_Shoes()
static void PlayerDrawLayers.DrawPlayer_14_Shoes (ref PlayerDrawSet drawinfo) inline static
     {
         if (drawinfo.drawPlayer.shoe <= 0 || drawinfo.drawPlayer.shoe >= ArmorIDs.Shoe.Count || ShouldOverrideLegs_CheckPants(ref drawinfo))
         {
             return;
         }
         int num = drawinfo.cShoe;
         if (drawinfo.drawPlayer.shoe == 22 || drawinfo.drawPlayer.shoe == 23)
         {
             num = drawinfo.cFlameWaker;
         }
         if (drawinfo.isSitting)
         {
             DrawSittingLegs(ref drawinfo, TextureAssets.AccShoes[drawinfo.drawPlayer.shoe].Value, drawinfo.colorArmorLegs, num);
             return;
         }
         DrawData item = new DrawData(TextureAssets.AccShoes[drawinfo.drawPlayer.shoe].Value, new Vector2((int)(drawinfo.Position.X - Main.screenPosition.X - (float)(drawinfo.drawPlayer.legFrame.Width / 2) + (float)(drawinfo.drawPlayer.width / 2)), (int)(drawinfo.Position.Y - Main.screenPosition.Y + (float)drawinfo.drawPlayer.height - (float)drawinfo.drawPlayer.legFrame.Height + 4f)) + drawinfo.drawPlayer.legPosition + drawinfo.legVect, drawinfo.drawPlayer.legFrame, drawinfo.colorArmorLegs, drawinfo.drawPlayer.legRotation, drawinfo.legVect, 1f, drawinfo.playerEffect);
         item.shader = num;
         drawinfo.DrawDataCache.Add(item);
         if (drawinfo.drawPlayer.shoe == 25 || drawinfo.drawPlayer.shoe == 26)
         {
             DrawPlayer_14_2_GlassSlipperSparkles(ref drawinfo);
         }
     }
References TextureAssets.AccShoes, ArmorIDs.Shoe.Count, DrawPlayer_14_2_GlassSlipperSparkles(), DrawSittingLegs(), Main.screenPosition, DrawData.shader, ShouldOverrideLegs_CheckPants(), and Asset< T >.Value.
Referenced by LegacyPlayerRenderer.DrawPlayer_UseNormalLayers().