Terraria: PlayerDrawLayers.DrawPlayer_13_Leggings
DrawPlayer_13_Leggings()
static void PlayerDrawLayers.DrawPlayer_13_Leggings (ref PlayerDrawSet drawinfo) inline static
     {
         Vector2 legsOffset = drawinfo.legsOffset;
         if (drawinfo.drawPlayer.legs == 169)
         {
             return;
         }
         if (drawinfo.isSitting && drawinfo.drawPlayer.legs != 140 && drawinfo.drawPlayer.legs != 217)
         {
             if (drawinfo.drawPlayer.legs > 0 && drawinfo.drawPlayer.legs < ArmorIDs.Legs.Count && (!ShouldOverrideLegs_CheckShoes(ref drawinfo) || drawinfo.drawPlayer.wearsRobe))
             {
                 if (!drawinfo.drawPlayer.invis)
                 {
                     DrawSittingLegs(ref drawinfo, TextureAssets.ArmorLeg[drawinfo.drawPlayer.legs].Value, drawinfo.colorArmorLegs, drawinfo.cLegs);
                     if (drawinfo.legsGlowMask != -1)
                     {
                         DrawSittingLegs(ref drawinfo, TextureAssets.GlowMask[drawinfo.legsGlowMask].Value, drawinfo.legsGlowColor, drawinfo.cLegs);
                     }
                 }
             }
             else if (!drawinfo.drawPlayer.invis && !ShouldOverrideLegs_CheckShoes(ref drawinfo))
             {
                 DrawSittingLegs(ref drawinfo, TextureAssets.Players[drawinfo.skinVar, 11].Value, drawinfo.colorPants);
                 DrawSittingLegs(ref drawinfo, TextureAssets.Players[drawinfo.skinVar, 12].Value, drawinfo.colorShoes);
             }
         }
         else if (drawinfo.drawPlayer.legs == 140)
         {
             if (!drawinfo.drawPlayer.invis && !drawinfo.drawPlayer.mount.Active)
             {
                 Texture2D value = TextureAssets.Extra[73].Value;
                 bool flag = drawinfo.drawPlayer.legFrame.Y != drawinfo.drawPlayer.legFrame.Height || Main.gameMenu;
                 int num = drawinfo.drawPlayer.miscCounter / 3 % 8;
                 if (flag)
                 {
                     num = drawinfo.drawPlayer.miscCounter / 4 % 8;
                 }
                 Rectangle rectangle = new Rectangle(18 * flag.ToInt(), num * 26, 16, 24);
                 float num2 = 12f;
                 if (drawinfo.drawPlayer.bodyFrame.Height != 0)
                 {
                     num2 = 12f - Main.OffsetsPlayerHeadgear[drawinfo.drawPlayer.bodyFrame.Y / drawinfo.drawPlayer.bodyFrame.Height].Y;
                 }
                 if (drawinfo.drawPlayer.Directions.Y == -1f)
                 {
                     num2 -= 6f;
                 }
                 Vector2 scale = new Vector2(1f, 1f);
                 Vector2 vector = drawinfo.Position + drawinfo.drawPlayer.Size * new Vector2(0.5f, 0.5f + 0.5f * drawinfo.drawPlayer.gravDir);
                 _ = drawinfo.drawPlayer.direction;
                 Vector2 vec = vector + new Vector2(0f, (0f - num2) * drawinfo.drawPlayer.gravDir) - Main.screenPosition + drawinfo.drawPlayer.legPosition;
                 if (drawinfo.isSitting)
                 {
                     vec.Y += drawinfo.seatYOffset;
                 }
                 vec += legsOffset;
                 vec = vec.Floor();
                 DrawData item = new DrawData(value, vec, rectangle, drawinfo.colorArmorLegs, drawinfo.drawPlayer.legRotation, rectangle.Size() * new Vector2(0.5f, 0.5f - drawinfo.drawPlayer.gravDir * 0.5f), scale, drawinfo.playerEffect);
                 item.shader = drawinfo.cLegs;
                 drawinfo.DrawDataCache.Add(item);
             }
         }
         else if (drawinfo.drawPlayer.legs > 0 && drawinfo.drawPlayer.legs < ArmorIDs.Legs.Count && (!ShouldOverrideLegs_CheckShoes(ref drawinfo) || drawinfo.drawPlayer.wearsRobe))
         {
             if (drawinfo.drawPlayer.invis)
             {
                 return;
             }
             DrawData item = new DrawData(TextureAssets.ArmorLeg[drawinfo.drawPlayer.legs].Value, legsOffset + new Vector2((int)(drawinfo.Position.X - Main.screenPosition.X - (float)(drawinfo.drawPlayer.legFrame.Width / 2) + (float)(drawinfo.drawPlayer.width / 2)), (int)(drawinfo.Position.Y - Main.screenPosition.Y + (float)drawinfo.drawPlayer.height - (float)drawinfo.drawPlayer.legFrame.Height + 4f)) + drawinfo.drawPlayer.legPosition + drawinfo.legVect, drawinfo.drawPlayer.legFrame, drawinfo.colorArmorLegs, drawinfo.drawPlayer.legRotation, drawinfo.legVect, 1f, drawinfo.playerEffect);
             item.shader = drawinfo.cLegs;
             drawinfo.DrawDataCache.Add(item);
             if (drawinfo.legsGlowMask == -1)
             {
                 return;
             }
             if (drawinfo.legsGlowMask == 274)
             {
                 for (int i = 0; i < 2; i++)
                 {
                     item = new DrawData(position: legsOffset + new Vector2((float)Main.rand.Next(-10, 10) * 0.125f, (float)Main.rand.Next(-10, 10) * 0.125f) + new Vector2((int)(drawinfo.Position.X - Main.screenPosition.X - (float)(drawinfo.drawPlayer.legFrame.Width / 2) + (float)(drawinfo.drawPlayer.width / 2)), (int)(drawinfo.Position.Y - Main.screenPosition.Y + (float)drawinfo.drawPlayer.height - (float)drawinfo.drawPlayer.legFrame.Height + 4f)) + drawinfo.drawPlayer.legPosition + drawinfo.legVect, texture: TextureAssets.GlowMask[drawinfo.legsGlowMask].Value, sourceRect: drawinfo.drawPlayer.legFrame, color: drawinfo.legsGlowColor, rotation: drawinfo.drawPlayer.legRotation, origin: drawinfo.legVect, scale: 1f, effect: drawinfo.playerEffect);
                     item.shader = drawinfo.cLegs;
                     drawinfo.DrawDataCache.Add(item);
                 }
             }
             else
             {
                 item = new DrawData(TextureAssets.GlowMask[drawinfo.legsGlowMask].Value, legsOffset + new Vector2((int)(drawinfo.Position.X - Main.screenPosition.X - (float)(drawinfo.drawPlayer.legFrame.Width / 2) + (float)(drawinfo.drawPlayer.width / 2)), (int)(drawinfo.Position.Y - Main.screenPosition.Y + (float)drawinfo.drawPlayer.height - (float)drawinfo.drawPlayer.legFrame.Height + 4f)) + drawinfo.drawPlayer.legPosition + drawinfo.legVect, drawinfo.drawPlayer.legFrame, drawinfo.legsGlowColor, drawinfo.drawPlayer.legRotation, drawinfo.legVect, 1f, drawinfo.playerEffect);
                 item.shader = drawinfo.cLegs;
                 drawinfo.DrawDataCache.Add(item);
             }
         }
         else if (!drawinfo.drawPlayer.invis && !ShouldOverrideLegs_CheckShoes(ref drawinfo))
         {
             DrawData item = new DrawData(TextureAssets.Players[drawinfo.skinVar, 11].Value, new Vector2((int)(drawinfo.Position.X - Main.screenPosition.X - (float)(drawinfo.drawPlayer.legFrame.Width / 2) + (float)(drawinfo.drawPlayer.width / 2)), (int)(drawinfo.Position.Y - Main.screenPosition.Y + (float)drawinfo.drawPlayer.height - (float)drawinfo.drawPlayer.legFrame.Height + 4f)) + drawinfo.drawPlayer.legPosition + drawinfo.legVect, drawinfo.drawPlayer.legFrame, drawinfo.colorPants, drawinfo.drawPlayer.legRotation, drawinfo.legVect, 1f, drawinfo.playerEffect);
             drawinfo.DrawDataCache.Add(item);
             item = new DrawData(TextureAssets.Players[drawinfo.skinVar, 12].Value, new Vector2((int)(drawinfo.Position.X - Main.screenPosition.X - (float)(drawinfo.drawPlayer.legFrame.Width / 2) + (float)(drawinfo.drawPlayer.width / 2)), (int)(drawinfo.Position.Y - Main.screenPosition.Y + (float)drawinfo.drawPlayer.height - (float)drawinfo.drawPlayer.legFrame.Height + 4f)) + drawinfo.drawPlayer.legPosition + drawinfo.legVect, drawinfo.drawPlayer.legFrame, drawinfo.colorShoes, drawinfo.drawPlayer.legRotation, drawinfo.legVect, 1f, drawinfo.playerEffect);
             drawinfo.DrawDataCache.Add(item);
         }
     }
References TextureAssets.ArmorLeg, ArmorIDs.Legs.Count, DrawSittingLegs(), TextureAssets.Extra, Main.gameMenu, TextureAssets.GlowMask, UnifiedRandom.Next(), Main.OffsetsPlayerHeadgear, TextureAssets.Players, Main.rand, Main.screenPosition, DrawData.shader, ShouldOverrideLegs_CheckShoes(), and Asset< T >.Value.
Referenced by LegacyPlayerRenderer.DrawPlayer_UseNormalLayers().