Terraria: PlayerDrawLayers.DrawPlayer_RenderAllLayers
DrawPlayer_RenderAllLayers()
static void PlayerDrawLayers.DrawPlayer_RenderAllLayers (ref PlayerDrawSet drawinfo) inline static
     {
         List<DrawData> drawDataCache = drawinfo.DrawDataCache;
         if (spriteBuffer == null)
         {
             spriteBuffer = new SpriteDrawBuffer(Main.graphics.GraphicsDevice, 200);
         }
         else
         {
             spriteBuffer.CheckGraphicsDevice(Main.graphics.GraphicsDevice);
         }
         foreach (DrawData item in drawDataCache)
         {
             if (item.texture != null)
             {
                 item.Draw(spriteBuffer);
             }
         }
         spriteBuffer.UploadAndBind();
         DrawData cdd = default(DrawData);
         int num = 0;
         for (int i = 0; i <= drawDataCache.Count; i++)
         {
             if (drawinfo.projectileDrawPosition == i)
             {
                 if (cdd.shader != 0)
                 {
                     Main.pixelShader.CurrentTechnique.Passes[0].Apply();
                 }
                 spriteBuffer.Unbind();
                 DrawHeldProj(drawinfo, Main.projectile[drawinfo.drawPlayer.heldProj]);
                 spriteBuffer.Bind();
             }
             if (i != drawDataCache.Count)
             {
                 cdd = drawDataCache[i];
                 if (!cdd.sourceRect.HasValue)
                 {
                     cdd.sourceRect = cdd.texture.Frame();
                 }
                 PlayerDrawHelper.SetShaderForData(drawinfo.drawPlayer, drawinfo.cHead, ref cdd);
                 if (cdd.texture != null)
                 {
                     spriteBuffer.DrawSingle(num++);
                 }
             }
         }
         spriteBuffer.Unbind();
         Main.pixelShader.CurrentTechnique.Passes[0].Apply();
     }
References SpriteDrawBuffer.Bind(), SpriteDrawBuffer.CheckGraphicsDevice(), DrawData.Draw(), DrawHeldProj(), SpriteDrawBuffer.DrawSingle(), Main.graphics, Main.pixelShader, Main.projectile, PlayerDrawHelper.SetShaderForData(), DrawData.shader, DrawData.sourceRect, spriteBuffer, DrawData.texture, SpriteDrawBuffer.Unbind(), and SpriteDrawBuffer.UploadAndBind().
Referenced by LegacyPlayerRenderer.DrawPlayer().