Terraria: PlayerDrawLayers.DrawPlayer_14_2_GlassSlipperSparkles
DrawPlayer_14_2_GlassSlipperSparkles()
static void PlayerDrawLayers.DrawPlayer_14_2_GlassSlipperSparkles (ref PlayerDrawSet drawinfo) inline static
     {
         if (drawinfo.shadow == 0f)
         {
             if (Main.rand.Next(60) == 0)
             {
                 Rectangle r = Utils.CenteredRectangle(drawinfo.Position + drawinfo.drawPlayer.Size / 2f + new Vector2(0f, drawinfo.drawPlayer.gravDir * 16f), new Vector2(20f, 8f));
                 int num = Dust.NewDust(r.TopLeft(), r.Width, r.Height, 204, 0f, 0f, 150, default(Color), 0.3f);
                 Main.dust[num].fadeIn = 1f;
                 Main.dust[num].velocity *= 0.1f;
                 Main.dust[num].noLight = true;
                 Main.dust[num].shader = GameShaders.Armor.GetSecondaryShader(drawinfo.drawPlayer.cShoe, drawinfo.drawPlayer);
                 drawinfo.DustCache.Add(num);
             }
             if (drawinfo.drawPlayer.velocity.X != 0f && Main.rand.Next(10) == 0)
             {
                 Rectangle r2 = Utils.CenteredRectangle(drawinfo.Position + drawinfo.drawPlayer.Size / 2f + new Vector2(drawinfo.drawPlayer.direction * -2, drawinfo.drawPlayer.gravDir * 16f), new Vector2(6f, 8f));
                 int num2 = Dust.NewDust(r2.TopLeft(), r2.Width, r2.Height, 204, 0f, 0f, 150, default(Color), 0.3f);
                 Main.dust[num2].fadeIn = 1f;
                 Main.dust[num2].velocity *= 0.1f;
                 Main.dust[num2].noLight = true;
                 Main.dust[num2].shader = GameShaders.Armor.GetSecondaryShader(drawinfo.drawPlayer.cShoe, drawinfo.drawPlayer);
                 drawinfo.DustCache.Add(num2);
             }
         }
     }
References GameShaders.Armor, Utils.CenteredRectangle(), Color, Main.dust, Dust.fadeIn, ArmorShaderDataSet.GetSecondaryShader(), Dust.NewDust(), UnifiedRandom.Next(), Dust.noLight, Main.rand, Dust.shader, and Dust.velocity.
Referenced by DrawPlayer_14_Shoes().