Terraria: PlayerDrawLayers.DrawPlayer_17_TorsoComposite
DrawPlayer_17_TorsoComposite()
static void PlayerDrawLayers.DrawPlayer_17_TorsoComposite (ref PlayerDrawSet drawinfo) inline static
     {
         Vector2 vector = new Vector2((int)(drawinfo.Position.X - Main.screenPosition.X - (float)(drawinfo.drawPlayer.bodyFrame.Width / 2) + (float)(drawinfo.drawPlayer.width / 2)), (int)(drawinfo.Position.Y - Main.screenPosition.Y + (float)drawinfo.drawPlayer.height - (float)drawinfo.drawPlayer.bodyFrame.Height + 4f)) + drawinfo.drawPlayer.bodyPosition + new Vector2(drawinfo.drawPlayer.bodyFrame.Width / 2, drawinfo.drawPlayer.bodyFrame.Height / 2);
         Vector2 vector2 = Main.OffsetsPlayerHeadgear[drawinfo.drawPlayer.bodyFrame.Y / drawinfo.drawPlayer.bodyFrame.Height];
         vector2.Y -= 2f;
         vector += vector2 * -drawinfo.playerEffect.HasFlag(SpriteEffects.FlipVertically).ToDirectionInt();
         float bodyRotation = drawinfo.drawPlayer.bodyRotation;
         Vector2 vector3 = vector;
         Vector2 bodyVect = drawinfo.bodyVect;
         Vector2 compositeOffset_BackArm = GetCompositeOffset_BackArm(ref drawinfo);
         _ = vector3 + compositeOffset_BackArm;
         bodyVect += compositeOffset_BackArm;
         if (drawinfo.drawPlayer.body > 0 && drawinfo.drawPlayer.body < ArmorIDs.Body.Count)
         {
             if (!drawinfo.drawPlayer.invis || IsArmorDrawnWhenInvisible(drawinfo.drawPlayer.body))
             {
                 Texture2D value = TextureAssets.ArmorBodyComposite[drawinfo.drawPlayer.body].Value;
                 DrawCompositeArmorPiece(ref drawinfo, CompositePlayerDrawContext.Torso, new DrawData(value, vector, drawinfo.compTorsoFrame, drawinfo.colorArmorBody, bodyRotation, drawinfo.bodyVect, 1f, drawinfo.playerEffect)
                 {
                     shader = drawinfo.cBody
                 });
             }
         }
         else if (!drawinfo.drawPlayer.invis)
         {
             drawinfo.DrawDataCache.Add(new DrawData(TextureAssets.Players[drawinfo.skinVar, 4].Value, vector, drawinfo.compBackShoulderFrame, drawinfo.colorUnderShirt, bodyRotation, drawinfo.bodyVect, 1f, drawinfo.playerEffect));
             drawinfo.DrawDataCache.Add(new DrawData(TextureAssets.Players[drawinfo.skinVar, 6].Value, vector, drawinfo.compBackShoulderFrame, drawinfo.colorShirt, bodyRotation, drawinfo.bodyVect, 1f, drawinfo.playerEffect));
             drawinfo.DrawDataCache.Add(new DrawData(TextureAssets.Players[drawinfo.skinVar, 4].Value, vector, drawinfo.compTorsoFrame, drawinfo.colorUnderShirt, bodyRotation, drawinfo.bodyVect, 1f, drawinfo.playerEffect));
             drawinfo.DrawDataCache.Add(new DrawData(TextureAssets.Players[drawinfo.skinVar, 6].Value, vector, drawinfo.compTorsoFrame, drawinfo.colorShirt, bodyRotation, drawinfo.bodyVect, 1f, drawinfo.playerEffect));
         }
         if (drawinfo.drawFloatingTube)
         {
             drawinfo.DrawDataCache.Add(new DrawData(TextureAssets.Extra[105].Value, vector, new Rectangle(0, 56, 40, 56), drawinfo.floatingTubeColor, bodyRotation, drawinfo.bodyVect, 1f, drawinfo.playerEffect)
             {
                 shader = drawinfo.cFloatingTube
             });
         }
     }
References TextureAssets.ArmorBodyComposite, ArmorIDs.Body.Count, DrawCompositeArmorPiece(), TextureAssets.Extra, GetCompositeOffset_BackArm(), IsArmorDrawnWhenInvisible(), Main.OffsetsPlayerHeadgear, TextureAssets.Players, Main.screenPosition, and Asset< T >.Value.
Referenced by DrawPlayer_17_Torso().