Terraria: PlayerDrawLayers.DrawPlayer_16_ArmorLongCoat
DrawPlayer_16_ArmorLongCoat()
static void PlayerDrawLayers.DrawPlayer_16_ArmorLongCoat (ref PlayerDrawSet drawinfo) inline static
     {
         int num = -1;
         switch (drawinfo.drawPlayer.body)
         {
         case 200:
             num = 149;
             break;
         case 202:
             num = 151;
             break;
         case 201:
             num = 150;
             break;
         case 209:
             num = 160;
             break;
         case 207:
             num = 161;
             break;
         case 198:
             num = 162;
             break;
         case 182:
             num = 163;
             break;
         case 168:
             num = 164;
             break;
         case 73:
             num = 170;
             break;
         case 52:
             num = ((!drawinfo.drawPlayer.Male) ? 172 : 171);
             break;
         case 187:
             num = 173;
             break;
         case 205:
             num = 174;
             break;
         case 53:
             num = ((!drawinfo.drawPlayer.Male) ? 176 : 175);
             break;
         case 210:
             num = ((!drawinfo.drawPlayer.Male) ? 177 : 178);
             break;
         case 211:
             num = ((!drawinfo.drawPlayer.Male) ? 181 : 182);
             break;
         case 218:
             num = 195;
             break;
         case 222:
             num = ((!drawinfo.drawPlayer.Male) ? 200 : 201);
             break;
         case 225:
             num = 206;
             break;
         case 236:
             num = 221;
             break;
         case 237:
             num = 223;
             break;
         case 89:
             num = 186;
             break;
         case 81:
             num = 169;
             break;
         }
         if (num != -1)
         {
             Main.instance.LoadArmorLegs(num);
             if (drawinfo.isSitting && num != 195)
             {
                 DrawSittingLongCoats(ref drawinfo, num, TextureAssets.ArmorLeg[num].Value, drawinfo.colorArmorBody, drawinfo.cBody);
                 return;
             }
             DrawData item = new DrawData(TextureAssets.ArmorLeg[num].Value, new Vector2((int)(drawinfo.Position.X - Main.screenPosition.X - (float)(drawinfo.drawPlayer.legFrame.Width / 2) + (float)(drawinfo.drawPlayer.width / 2)), (int)(drawinfo.Position.Y - Main.screenPosition.Y + (float)drawinfo.drawPlayer.height - (float)drawinfo.drawPlayer.legFrame.Height + 4f)) + drawinfo.drawPlayer.legPosition + drawinfo.legVect, drawinfo.drawPlayer.legFrame, drawinfo.colorArmorBody, drawinfo.drawPlayer.legRotation, drawinfo.legVect, 1f, drawinfo.playerEffect);
             item.shader = drawinfo.cBody;
             drawinfo.DrawDataCache.Add(item);
         }
     }
References TextureAssets.ArmorLeg, DrawSittingLongCoats(), Main.instance, Main.LoadArmorLegs(), Main.screenPosition, DrawData.shader, and Asset< T >.Value.
Referenced by LegacyPlayerRenderer.DrawPlayer_UseNormalLayers().