Terraria: PlayerDrawLayers.DrawPlayer_28_ArmOverItemComposite
DrawPlayer_28_ArmOverItemComposite()
static void PlayerDrawLayers.DrawPlayer_28_ArmOverItemComposite (ref PlayerDrawSet drawinfo) inline static
     {
         Vector2 vector = new Vector2((int)(drawinfo.Position.X - Main.screenPosition.X - (float)(drawinfo.drawPlayer.bodyFrame.Width / 2) + (float)(drawinfo.drawPlayer.width / 2)), (int)(drawinfo.Position.Y - Main.screenPosition.Y + (float)drawinfo.drawPlayer.height - (float)drawinfo.drawPlayer.bodyFrame.Height + 4f)) + drawinfo.drawPlayer.bodyPosition + new Vector2(drawinfo.drawPlayer.bodyFrame.Width / 2, drawinfo.drawPlayer.bodyFrame.Height / 2);
         Vector2 vector2 = Main.OffsetsPlayerHeadgear[drawinfo.drawPlayer.bodyFrame.Y / drawinfo.drawPlayer.bodyFrame.Height];
         vector2.Y -= 2f;
         vector += vector2 * -drawinfo.playerEffect.HasFlag(SpriteEffects.FlipVertically).ToDirectionInt();
         float bodyRotation = drawinfo.drawPlayer.bodyRotation;
         float rotation = drawinfo.drawPlayer.bodyRotation + drawinfo.compositeFrontArmRotation;
         Vector2 bodyVect = drawinfo.bodyVect;
         Vector2 compositeOffset_FrontArm = GetCompositeOffset_FrontArm(ref drawinfo);
         bodyVect += compositeOffset_FrontArm;
         vector += compositeOffset_FrontArm;
         Vector2 position = vector + drawinfo.frontShoulderOffset;
         if (drawinfo.compFrontArmFrame.X / drawinfo.compFrontArmFrame.Width >= 7)
         {
             vector += new Vector2((!drawinfo.playerEffect.HasFlag(SpriteEffects.FlipHorizontally)) ? 1 : (-1), (!drawinfo.playerEffect.HasFlag(SpriteEffects.FlipVertically)) ? 1 : (-1));
         }
         _ = drawinfo.drawPlayer.invis;
         bool num = drawinfo.drawPlayer.body > 0 && drawinfo.drawPlayer.body < ArmorIDs.Body.Count;
         int num2 = (drawinfo.compShoulderOverFrontArm ? 1 : 0);
         int num3 = ((!drawinfo.compShoulderOverFrontArm) ? 1 : 0);
         int num4 = ((!drawinfo.compShoulderOverFrontArm) ? 1 : 0);
         bool flag = !drawinfo.hidesTopSkin;
         if (num)
         {
             if (!drawinfo.drawPlayer.invis || IsArmorDrawnWhenInvisible(drawinfo.drawPlayer.body))
             {
                 Texture2D value = TextureAssets.ArmorBodyComposite[drawinfo.drawPlayer.body].Value;
                 for (int i = 0; i < 2; i++)
                 {
                     if (!drawinfo.drawPlayer.invis && i == num4 && flag)
                     {
                         if (drawinfo.missingArm)
{
                             drawinfo.DrawDataCache.Add(new DrawData(TextureAssets.Players[drawinfo.skinVar, 7].Value, vector, drawinfo.compFrontArmFrame, drawinfo.colorBodySkin, rotation, bodyVect, 1f, drawinfo.playerEffect)
{
                                 shader = drawinfo.skinDyePacked
                             });
                         }
                         if (drawinfo.missingHand)
{
                             drawinfo.DrawDataCache.Add(new DrawData(TextureAssets.Players[drawinfo.skinVar, 9].Value, vector, drawinfo.compFrontArmFrame, drawinfo.colorBodySkin, rotation, bodyVect, 1f, drawinfo.playerEffect)
{
                                 shader = drawinfo.skinDyePacked
                             });
                         }
                     }
                     if (i == num2 && !drawinfo.hideCompositeShoulders)
                     {
                         DrawCompositeArmorPiece(ref drawinfo, CompositePlayerDrawContext.FrontShoulder, new DrawData(value, position, drawinfo.compFrontShoulderFrame, drawinfo.colorArmorBody, bodyRotation, bodyVect, 1f, drawinfo.playerEffect)
{
                             shader = drawinfo.cBody
                         });
                     }
                     if (i == num3)
                     {
                         DrawCompositeArmorPiece(ref drawinfo, CompositePlayerDrawContext.FrontArm, new DrawData(value, vector, drawinfo.compFrontArmFrame, drawinfo.colorArmorBody, rotation, bodyVect, 1f, drawinfo.playerEffect)
{
                             shader = drawinfo.cBody
                         });
                     }
                 }
             }
         }
         else if (!drawinfo.drawPlayer.invis)
         {
             for (int j = 0; j < 2; j++)
             {
                 if (j == num2)
                 {
                     if (flag)
                     {
                         drawinfo.DrawDataCache.Add(new DrawData(TextureAssets.Players[drawinfo.skinVar, 7].Value, position, drawinfo.compFrontShoulderFrame, drawinfo.colorBodySkin, bodyRotation, bodyVect, 1f, drawinfo.playerEffect)
{
                             shader = drawinfo.skinDyePacked
                         });
                     }
                     drawinfo.DrawDataCache.Add(new DrawData(TextureAssets.Players[drawinfo.skinVar, 8].Value, position, drawinfo.compFrontShoulderFrame, drawinfo.colorUnderShirt, bodyRotation, bodyVect, 1f, drawinfo.playerEffect));
                     drawinfo.DrawDataCache.Add(new DrawData(TextureAssets.Players[drawinfo.skinVar, 13].Value, position, drawinfo.compFrontShoulderFrame, drawinfo.colorShirt, bodyRotation, bodyVect, 1f, drawinfo.playerEffect));
                     drawinfo.DrawDataCache.Add(new DrawData(TextureAssets.Players[drawinfo.skinVar, 6].Value, position, drawinfo.compFrontShoulderFrame, drawinfo.colorShirt, bodyRotation, bodyVect, 1f, drawinfo.playerEffect));
                     if (drawinfo.drawPlayer.head == 269)
                     {
                         Vector2 position2 = drawinfo.helmetOffset + new Vector2((int)(drawinfo.Position.X - Main.screenPosition.X - (float)(drawinfo.drawPlayer.bodyFrame.Width / 2) + (float)(drawinfo.drawPlayer.width / 2)), (int)(drawinfo.Position.Y - Main.screenPosition.Y + (float)drawinfo.drawPlayer.height - (float)drawinfo.drawPlayer.bodyFrame.Height + 4f)) + drawinfo.drawPlayer.headPosition + drawinfo.headVect;
                         DrawData item = new DrawData(TextureAssets.Extra[214].Value, position2, drawinfo.drawPlayer.bodyFrame, drawinfo.colorArmorHead, drawinfo.drawPlayer.headRotation, drawinfo.headVect, 1f, drawinfo.playerEffect);
                         item.shader = drawinfo.cHead;
                         drawinfo.DrawDataCache.Add(item);
                         item = new DrawData(TextureAssets.GlowMask[308].Value, position2, drawinfo.drawPlayer.bodyFrame, drawinfo.headGlowColor, drawinfo.drawPlayer.headRotation, drawinfo.headVect, 1f, drawinfo.playerEffect);
                         item.shader = drawinfo.cHead;
                         drawinfo.DrawDataCache.Add(item);
                     }
                 }
                 if (j == num3)
                 {
                     if (flag)
                     {
                         drawinfo.DrawDataCache.Add(new DrawData(TextureAssets.Players[drawinfo.skinVar, 7].Value, vector, drawinfo.compFrontArmFrame, drawinfo.colorBodySkin, rotation, bodyVect, 1f, drawinfo.playerEffect)
{
                             shader = drawinfo.skinDyePacked
                         });
                     }
                     drawinfo.DrawDataCache.Add(new DrawData(TextureAssets.Players[drawinfo.skinVar, 8].Value, vector, drawinfo.compFrontArmFrame, drawinfo.colorUnderShirt, rotation, bodyVect, 1f, drawinfo.playerEffect));
                     drawinfo.DrawDataCache.Add(new DrawData(TextureAssets.Players[drawinfo.skinVar, 13].Value, vector, drawinfo.compFrontArmFrame, drawinfo.colorShirt, rotation, bodyVect, 1f, drawinfo.playerEffect));
                     drawinfo.DrawDataCache.Add(new DrawData(TextureAssets.Players[drawinfo.skinVar, 6].Value, vector, drawinfo.compFrontArmFrame, drawinfo.colorShirt, rotation, bodyVect, 1f, drawinfo.playerEffect));
                 }
             }
         }
         if (drawinfo.drawPlayer.handon > 0 && drawinfo.drawPlayer.handon < ArmorIDs.HandOn.Count)
         {
             Texture2D value2 = TextureAssets.AccHandsOnComposite[drawinfo.drawPlayer.handon].Value;
             DrawCompositeArmorPiece(ref drawinfo, CompositePlayerDrawContext.FrontArmAccessory, new DrawData(value2, vector, drawinfo.compFrontArmFrame, drawinfo.colorArmorBody, rotation, bodyVect, 1f, drawinfo.playerEffect)
             {
                 shader = drawinfo.cHandOn
             });
         }
     }
References TextureAssets.AccHandsOnComposite, TextureAssets.ArmorBodyComposite, ArmorIDs.Body.Count, ArmorIDs.HandOn.Count, DrawCompositeArmorPiece(), TextureAssets.Extra, GetCompositeOffset_FrontArm(), TextureAssets.GlowMask, IsArmorDrawnWhenInvisible(), Main.OffsetsPlayerHeadgear, TextureAssets.Players, Main.screenPosition, DrawData.shader, and Asset< T >.Value.
Referenced by DrawPlayer_28_ArmOverItem().