Terraria: PlayerDrawLayers.DrawPlayer_28_ArmOverItem
DrawPlayer_28_ArmOverItem()
static void PlayerDrawLayers.DrawPlayer_28_ArmOverItem (ref PlayerDrawSet drawinfo) inline static
     {
         if (drawinfo.usesCompositeTorso)
         {
             DrawPlayer_28_ArmOverItemComposite(ref drawinfo);
         }
         else if (drawinfo.drawPlayer.body > 0 && drawinfo.drawPlayer.body < ArmorIDs.Body.Count)
         {
             Rectangle bodyFrame = drawinfo.drawPlayer.bodyFrame;
             int num = drawinfo.armorAdjust;
             bodyFrame.X += num;
             bodyFrame.Width -= num;
             if (drawinfo.drawPlayer.direction == -1)
             {
                 num = 0;
             }
             if (drawinfo.drawPlayer.invis && (drawinfo.drawPlayer.body == 21 || drawinfo.drawPlayer.body == 22))
             {
                 return;
             }
             DrawData item;
             if (drawinfo.missingHand && !drawinfo.drawPlayer.invis)
             {
                 _ = drawinfo.drawPlayer.body;
                 DrawData drawData;
                 if (drawinfo.missingArm)
                 {
                     drawData = new DrawData(TextureAssets.Players[drawinfo.skinVar, 7].Value, new Vector2((int)(drawinfo.Position.X - Main.screenPosition.X - (float)(drawinfo.drawPlayer.bodyFrame.Width / 2) + (float)(drawinfo.drawPlayer.width / 2)), (int)(drawinfo.Position.Y - Main.screenPosition.Y + (float)drawinfo.drawPlayer.height - (float)drawinfo.drawPlayer.bodyFrame.Height + 4f)) + drawinfo.drawPlayer.bodyPosition + new Vector2(drawinfo.drawPlayer.bodyFrame.Width / 2, drawinfo.drawPlayer.bodyFrame.Height / 2), drawinfo.drawPlayer.bodyFrame, drawinfo.colorBodySkin, drawinfo.drawPlayer.bodyRotation, drawinfo.bodyVect, 1f, drawinfo.playerEffect);
                     drawData.shader = drawinfo.skinDyePacked;
                     item = drawData;
                     drawinfo.DrawDataCache.Add(item);
                 }
                 drawData = new DrawData(TextureAssets.Players[drawinfo.skinVar, 9].Value, new Vector2((int)(drawinfo.Position.X - Main.screenPosition.X - (float)(drawinfo.drawPlayer.bodyFrame.Width / 2) + (float)(drawinfo.drawPlayer.width / 2)), (int)(drawinfo.Position.Y - Main.screenPosition.Y + (float)drawinfo.drawPlayer.height - (float)drawinfo.drawPlayer.bodyFrame.Height + 4f)) + drawinfo.drawPlayer.bodyPosition + new Vector2(drawinfo.drawPlayer.bodyFrame.Width / 2, drawinfo.drawPlayer.bodyFrame.Height / 2), drawinfo.drawPlayer.bodyFrame, drawinfo.colorBodySkin, drawinfo.drawPlayer.bodyRotation, drawinfo.bodyVect, 1f, drawinfo.playerEffect);
                 drawData.shader = drawinfo.skinDyePacked;
                 item = drawData;
                 drawinfo.DrawDataCache.Add(item);
             }
             item = new DrawData(TextureAssets.ArmorArm[drawinfo.drawPlayer.body].Value, new Vector2((int)(drawinfo.Position.X - Main.screenPosition.X - (float)(drawinfo.drawPlayer.bodyFrame.Width / 2) + (float)(drawinfo.drawPlayer.width / 2)) + num, (int)(drawinfo.Position.Y - Main.screenPosition.Y + (float)drawinfo.drawPlayer.height - (float)drawinfo.drawPlayer.bodyFrame.Height + 4f)) + drawinfo.drawPlayer.bodyPosition + new Vector2(drawinfo.drawPlayer.bodyFrame.Width / 2, drawinfo.drawPlayer.bodyFrame.Height / 2), bodyFrame, drawinfo.colorArmorBody, drawinfo.drawPlayer.bodyRotation, drawinfo.bodyVect, 1f, drawinfo.playerEffect);
             item.shader = drawinfo.cBody;
             drawinfo.DrawDataCache.Add(item);
             if (drawinfo.armGlowMask != -1)
             {
                 item = new DrawData(TextureAssets.GlowMask[drawinfo.armGlowMask].Value, new Vector2((int)(drawinfo.Position.X - Main.screenPosition.X - (float)(drawinfo.drawPlayer.bodyFrame.Width / 2) + (float)(drawinfo.drawPlayer.width / 2)) + num, (int)(drawinfo.Position.Y - Main.screenPosition.Y + (float)drawinfo.drawPlayer.height - (float)drawinfo.drawPlayer.bodyFrame.Height + 4f)) + drawinfo.drawPlayer.bodyPosition + new Vector2(drawinfo.drawPlayer.bodyFrame.Width / 2, drawinfo.drawPlayer.bodyFrame.Height / 2), bodyFrame, drawinfo.armGlowColor, drawinfo.drawPlayer.bodyRotation, drawinfo.bodyVect, 1f, drawinfo.playerEffect);
                 item.shader = drawinfo.cBody;
                 drawinfo.DrawDataCache.Add(item);
             }
             if (drawinfo.drawPlayer.body == 205)
             {
                 Color color = new Color(100, 100, 100, 0);
                 ulong seed = (ulong)(drawinfo.drawPlayer.miscCounter / 4);
                 int num2 = 4;
                 for (int i = 0; i < num2; i++)
                 {
                     float num3 = (float)Utils.RandomInt(ref seed, -10, 11) * 0.2f;
                     float num4 = (float)Utils.RandomInt(ref seed, -10, 1) * 0.15f;
                     item = new DrawData(TextureAssets.GlowMask[240].Value, new Vector2((int)(drawinfo.Position.X - Main.screenPosition.X - (float)(drawinfo.drawPlayer.bodyFrame.Width / 2) + (float)(drawinfo.drawPlayer.width / 2)) + num, (int)(drawinfo.Position.Y - Main.screenPosition.Y + (float)drawinfo.drawPlayer.height - (float)drawinfo.drawPlayer.bodyFrame.Height + 4f)) + drawinfo.drawPlayer.bodyPosition + new Vector2((float)(drawinfo.drawPlayer.bodyFrame.Width / 2) + num3, (float)(drawinfo.drawPlayer.bodyFrame.Height / 2) + num4), bodyFrame, color, drawinfo.drawPlayer.bodyRotation, drawinfo.bodyVect, 1f, drawinfo.playerEffect);
                     item.shader = drawinfo.cBody;
                     drawinfo.DrawDataCache.Add(item);
                 }
             }
         }
         else if (!drawinfo.drawPlayer.invis)
         {
             DrawData drawData = new DrawData(TextureAssets.Players[drawinfo.skinVar, 7].Value, new Vector2((int)(drawinfo.Position.X - Main.screenPosition.X - (float)(drawinfo.drawPlayer.bodyFrame.Width / 2) + (float)(drawinfo.drawPlayer.width / 2)), (int)(drawinfo.Position.Y - Main.screenPosition.Y + (float)drawinfo.drawPlayer.height - (float)drawinfo.drawPlayer.bodyFrame.Height + 4f)) + drawinfo.drawPlayer.bodyPosition + new Vector2(drawinfo.drawPlayer.bodyFrame.Width / 2, drawinfo.drawPlayer.bodyFrame.Height / 2), drawinfo.drawPlayer.bodyFrame, drawinfo.colorBodySkin, drawinfo.drawPlayer.bodyRotation, drawinfo.bodyVect, 1f, drawinfo.playerEffect);
             drawData.shader = drawinfo.skinDyePacked;
             DrawData item = drawData;
             drawinfo.DrawDataCache.Add(item);
             item = new DrawData(TextureAssets.Players[drawinfo.skinVar, 8].Value, new Vector2((int)(drawinfo.Position.X - Main.screenPosition.X - (float)(drawinfo.drawPlayer.bodyFrame.Width / 2) + (float)(drawinfo.drawPlayer.width / 2)), (int)(drawinfo.Position.Y - Main.screenPosition.Y + (float)drawinfo.drawPlayer.height - (float)drawinfo.drawPlayer.bodyFrame.Height + 4f)) + drawinfo.drawPlayer.bodyPosition + new Vector2(drawinfo.drawPlayer.bodyFrame.Width / 2, drawinfo.drawPlayer.bodyFrame.Height / 2), drawinfo.drawPlayer.bodyFrame, drawinfo.colorUnderShirt, drawinfo.drawPlayer.bodyRotation, drawinfo.bodyVect, 1f, drawinfo.playerEffect);
             drawinfo.DrawDataCache.Add(item);
             item = new DrawData(TextureAssets.Players[drawinfo.skinVar, 13].Value, new Vector2((int)(drawinfo.Position.X - Main.screenPosition.X - (float)(drawinfo.drawPlayer.bodyFrame.Width / 2) + (float)(drawinfo.drawPlayer.width / 2)), (int)(drawinfo.Position.Y - Main.screenPosition.Y + (float)drawinfo.drawPlayer.height - (float)drawinfo.drawPlayer.bodyFrame.Height + 4f)) + drawinfo.drawPlayer.bodyPosition + new Vector2(drawinfo.drawPlayer.bodyFrame.Width / 2, drawinfo.drawPlayer.bodyFrame.Height / 2), drawinfo.drawPlayer.bodyFrame, drawinfo.colorShirt, drawinfo.drawPlayer.bodyRotation, drawinfo.bodyVect, 1f, drawinfo.playerEffect);
             drawinfo.DrawDataCache.Add(item);
         }
     }
References TextureAssets.ArmorArm, Color, ArmorIDs.Body.Count, DrawPlayer_28_ArmOverItemComposite(), TextureAssets.GlowMask, TextureAssets.Players, Utils.RandomInt(), Main.screenPosition, DrawData.shader, and Asset< T >.Value.
Referenced by LegacyPlayerRenderer.DrawPlayer_UseNormalLayers().