Terraria: PlayerDrawLayers.DrawStarboardRainbowTrail
DrawStarboardRainbowTrail()
static void PlayerDrawLayers.DrawStarboardRainbowTrail (ref PlayerDrawSet drawinfo, Vector2 commonWingPosPreFloor, Vector2 dirsVec) inline static
     {
         if (drawinfo.shadow != 0f)
         {
             return;
         }
         int num = Math.Min(drawinfo.drawPlayer.availableAdvancedShadowsCount - 1, 30);
         float num2 = 0f;
         for (int num3 = num; num3 > 0; num3--)
         {
             EntityShadowInfo advancedShadow = drawinfo.drawPlayer.GetAdvancedShadow(num3);
             EntityShadowInfo advancedShadow2 = drawinfo.drawPlayer.GetAdvancedShadow(num3 - 1);
             num2 += Vector2.Distance(advancedShadow.Position, advancedShadow2.Position);
         }
         float num4 = MathHelper.Clamp(num2 / 160f, 0f, 1f);
         Main.instance.LoadProjectile(250);
         Texture2D value = TextureAssets.Projectile[250].Value;
         float x = 1.7f;
         Vector2 origin = new Vector2(value.Width / 2, value.Height / 2);
         Vector2 vector = new Vector2(drawinfo.drawPlayer.width, drawinfo.drawPlayer.height) / 2f;
         Color white = Color.White;
         white.A = 64;
         Vector2 vector2 = vector;
         vector2 = drawinfo.drawPlayer.DefaultSize * new Vector2(0.5f, 1f) + new Vector2(0f, -4f);
         if (dirsVec.Y < 0f)
         {
             vector2 = drawinfo.drawPlayer.DefaultSize * new Vector2(0.5f, 0f) + new Vector2(0f, 4f);
         }
         for (int num5 = num; num5 > 0; num5--)
         {
             EntityShadowInfo advancedShadow3 = drawinfo.drawPlayer.GetAdvancedShadow(num5);
             EntityShadowInfo advancedShadow4 = drawinfo.drawPlayer.GetAdvancedShadow(num5 - 1);
             Vector2 pos = advancedShadow3.Position + vector2 + advancedShadow3.HeadgearOffset;
             Vector2 pos2 = advancedShadow4.Position + vector2 + advancedShadow4.HeadgearOffset;
             pos = drawinfo.drawPlayer.RotatedRelativePoint(pos, reverseRotation: true, addGfxOffY: false);
             pos2 = drawinfo.drawPlayer.RotatedRelativePoint(pos2, reverseRotation: true, addGfxOffY: false);
             float num6 = (pos2 - pos).ToRotation() - (float)Math.PI / 2f;
             num6 = (float)Math.PI / 2f * (float)drawinfo.drawPlayer.direction;
             float num7 = Math.Abs(pos2.X - pos.X);
             Vector2 scale = new Vector2(x, num7 / (float)value.Height);
             float num8 = 1f - (float)num5 / (float)num;
             num8 *= num8;
             num8 *= Utils.GetLerpValue(0f, 4f, num7, clamped: true);
             num8 *= 0.5f;
             num8 *= num8;
             Color color = white * num8 * num4;
             if (!(color == Color.Transparent))
             {
                 DrawData item = new DrawData(value, pos - Main.screenPosition, null, color, num6, origin, scale, drawinfo.playerEffect);
                 item.shader = drawinfo.cWings;
                 drawinfo.DrawDataCache.Add(item);
                 for (float num9 = 0.25f; num9 < 1f; num9 += 0.25f)
                 {
                     item = new DrawData(value, Vector2.Lerp(pos, pos2, num9) - Main.screenPosition, null, color, num6, origin, scale, drawinfo.playerEffect);
                     item.shader = drawinfo.cWings;
                     drawinfo.DrawDataCache.Add(item);
                 }
             }
         }
     }
References Color, Utils.GetLerpValue(), EntityShadowInfo.HeadgearOffset, Main.instance, Main.LoadProjectile(), EntityShadowInfo.Position, TextureAssets.Projectile, Main.screenPosition, DrawData.shader, and Asset< T >.Value.
Referenced by DrawPlayer_09_Wings().