Terraria: PlayerDrawLayers.DrawPlayer_30_BladedGlove
DrawPlayer_30_BladedGlove()
static void PlayerDrawLayers.DrawPlayer_30_BladedGlove (ref PlayerDrawSet drawinfo) inline static
     {
         Item heldItem = drawinfo.heldItem;
         if (heldItem.type <= -1 || !Item.claw[heldItem.type] || drawinfo.shadow != 0f)
         {
             return;
         }
         Main.instance.LoadItem(heldItem.type);
         Asset<Texture2D> val = TextureAssets.Item[heldItem.type];
         if (!drawinfo.drawPlayer.frozen && (drawinfo.drawPlayer.itemAnimation > 0 || (heldItem.holdStyle != 0 && !drawinfo.drawPlayer.pulley)) && heldItem.type > 0 && !drawinfo.drawPlayer.dead && !heldItem.noUseGraphic && (!drawinfo.drawPlayer.wet || !heldItem.noWet))
         {
             if (drawinfo.drawPlayer.gravDir == -1f)
             {
                 DrawData item = new DrawData(val.Value, new Vector2((int)(drawinfo.ItemLocation.X - Main.screenPosition.X), (int)(drawinfo.ItemLocation.Y - Main.screenPosition.Y)), new Rectangle(0, 0, val.Width(), val.Height()), heldItem.GetAlpha(drawinfo.itemColor), drawinfo.drawPlayer.itemRotation, new Vector2((float)val.Width() * 0.5f - (float)val.Width() * 0.5f * (float)drawinfo.drawPlayer.direction, 0f), drawinfo.drawPlayer.GetAdjustedItemScale(heldItem), drawinfo.itemEffect);
                 drawinfo.DrawDataCache.Add(item);
             }
             else
             {
                 DrawData item = new DrawData(val.Value, new Vector2((int)(drawinfo.ItemLocation.X - Main.screenPosition.X), (int)(drawinfo.ItemLocation.Y - Main.screenPosition.Y)), new Rectangle(0, 0, val.Width(), val.Height()), heldItem.GetAlpha(drawinfo.itemColor), drawinfo.drawPlayer.itemRotation, new Vector2((float)val.Width() * 0.5f - (float)val.Width() * 0.5f * (float)drawinfo.drawPlayer.direction, val.Height()), drawinfo.drawPlayer.GetAdjustedItemScale(heldItem), drawinfo.itemEffect);
                 drawinfo.DrawDataCache.Add(item);
             }
         }
     }
References Item.claw, Item.GetAlpha(), Item.holdStyle, Main.instance, TextureAssets.Item, Main.LoadItem(), Item.noUseGraphic, Item.noWet, Main.screenPosition, Item.type, and Asset< T >.Value.
Referenced by LegacyPlayerRenderer.DrawPlayer_UseNormalLayers().