Terraria: PlayerDrawLayers.DrawPlayer_07_LeinforsHairShampoo
DrawPlayer_07_LeinforsHairShampoo()
static void PlayerDrawLayers.DrawPlayer_07_LeinforsHairShampoo (ref PlayerDrawSet drawinfo) inline static
     {
         if (drawinfo.drawPlayer.leinforsHair && (drawinfo.fullHair || drawinfo.hatHair || drawinfo.drawsBackHairWithoutHeadgear || drawinfo.drawPlayer.head == -1 || drawinfo.drawPlayer.head == 0) && drawinfo.drawPlayer.hair != 12 && drawinfo.shadow == 0f && Main.rgbToHsl(drawinfo.colorHead).Z > 0.2f)
         {
             if (Main.rand.Next(20) == 0 && !drawinfo.hatHair)
             {
                 Rectangle r = Utils.CenteredRectangle(drawinfo.Position + drawinfo.drawPlayer.Size / 2f + new Vector2(0f, drawinfo.drawPlayer.gravDir * -20f), new Vector2(20f, 14f));
                 int num = Dust.NewDust(r.TopLeft(), r.Width, r.Height, 204, 0f, 0f, 150, default(Color), 0.3f);
                 Main.dust[num].fadeIn = 1f;
                 Main.dust[num].velocity *= 0.1f;
                 Main.dust[num].noLight = true;
                 Main.dust[num].shader = GameShaders.Armor.GetSecondaryShader(drawinfo.drawPlayer.cLeinShampoo, drawinfo.drawPlayer);
                 drawinfo.DustCache.Add(num);
             }
             if (Main.rand.Next(40) == 0 && drawinfo.hatHair)
             {
                 Rectangle r2 = Utils.CenteredRectangle(drawinfo.Position + drawinfo.drawPlayer.Size / 2f + new Vector2(drawinfo.drawPlayer.direction * -10, drawinfo.drawPlayer.gravDir * -10f), new Vector2(5f, 5f));
                 int num2 = Dust.NewDust(r2.TopLeft(), r2.Width, r2.Height, 204, 0f, 0f, 150, default(Color), 0.3f);
                 Main.dust[num2].fadeIn = 1f;
                 Main.dust[num2].velocity *= 0.1f;
                 Main.dust[num2].noLight = true;
                 Main.dust[num2].shader = GameShaders.Armor.GetSecondaryShader(drawinfo.drawPlayer.cLeinShampoo, drawinfo.drawPlayer);
                 drawinfo.DustCache.Add(num2);
             }
             if (drawinfo.drawPlayer.velocity.X != 0f && drawinfo.backHairDraw && Main.rand.Next(15) == 0)
             {
                 Rectangle r3 = Utils.CenteredRectangle(drawinfo.Position + drawinfo.drawPlayer.Size / 2f + new Vector2(drawinfo.drawPlayer.direction * -14, 0f), new Vector2(4f, 30f));
                 int num3 = Dust.NewDust(r3.TopLeft(), r3.Width, r3.Height, 204, 0f, 0f, 150, default(Color), 0.3f);
                 Main.dust[num3].fadeIn = 1f;
                 Main.dust[num3].velocity *= 0.1f;
                 Main.dust[num3].noLight = true;
                 Main.dust[num3].shader = GameShaders.Armor.GetSecondaryShader(drawinfo.drawPlayer.cLeinShampoo, drawinfo.drawPlayer);
                 drawinfo.DustCache.Add(num3);
             }
         }
     }
References GameShaders.Armor, Utils.CenteredRectangle(), Color, Main.dust, Dust.fadeIn, ArmorShaderDataSet.GetSecondaryShader(), Dust.NewDust(), UnifiedRandom.Next(), Dust.noLight, Main.rand, Main.rgbToHsl(), Dust.shader, and Dust.velocity.
Referenced by LegacyPlayerRenderer.DrawPlayer_UseNormalLayers().