Terraria: PlayerDrawLayers.DrawPlayer_RenderAllLayersSlow
DrawPlayer_RenderAllLayersSlow()
static void PlayerDrawLayers.DrawPlayer_RenderAllLayersSlow (ref PlayerDrawSet drawinfo) inline static
     {
         int num = -1;
         List<DrawData> drawDataCache = drawinfo.DrawDataCache;
         Effect pixelShader = Main.pixelShader;
         Projectile[] projectile = Main.projectile;
         SpriteBatch spriteBatch = Main.spriteBatch;
         for (int i = 0; i <= drawDataCache.Count; i++)
         {
             if (drawinfo.projectileDrawPosition == i)
             {
                 if (!ProjectileID.Sets.HeldProjDoesNotUsePlayerGfxOffY[projectile[drawinfo.drawPlayer.heldProj].type])
                 {
                     projectile[drawinfo.drawPlayer.heldProj].gfxOffY = drawinfo.drawPlayer.gfxOffY;
                 }
                 if (num != 0)
                 {
                     pixelShader.CurrentTechnique.Passes[0].Apply();
                     num = 0;
                 }
                 try
                 {
                     Main.instance.DrawProj(drawinfo.drawPlayer.heldProj);
                 }
                 catch
                 {
                     projectile[drawinfo.drawPlayer.heldProj].active = false;
                 }
             }
             if (i != drawDataCache.Count)
             {
                 DrawData cdd = drawDataCache[i];
                 if (!cdd.sourceRect.HasValue)
                 {
                     cdd.sourceRect = cdd.texture.Frame();
                 }
                 PlayerDrawHelper.SetShaderForData(drawinfo.drawPlayer, drawinfo.cHead, ref cdd);
                 num = cdd.shader;
                 if (cdd.texture != null)
                 {
                     cdd.Draw(spriteBatch);
                 }
             }
         }
         pixelShader.CurrentTechnique.Passes[0].Apply();
     }
References Entity.active, DrawData.Draw(), Main.DrawProj(), Projectile.gfxOffY, ProjectileID.Sets.HeldProjDoesNotUsePlayerGfxOffY, Main.instance, Main.pixelShader, Main.projectile, PlayerDrawHelper.SetShaderForData(), DrawData.shader, DrawData.sourceRect, Main.spriteBatch, DrawData.texture, and Projectile.type.