Terraria: PlayerDrawLayers.DrawSittingLegs
DrawSittingLegs()
static void PlayerDrawLayers.DrawSittingLegs (ref PlayerDrawSet drawinfo, Texture2D textureToDraw, Color matchingColor, int shaderIndex = 0, bool glowmask = false) inline static private
     {
         Vector2 legsOffset = drawinfo.legsOffset;
         Vector2 vector = new Vector2((int)(drawinfo.Position.X - Main.screenPosition.X - (float)(drawinfo.drawPlayer.legFrame.Width / 2) + (float)(drawinfo.drawPlayer.width / 2)), (int)(drawinfo.Position.Y - Main.screenPosition.Y + (float)drawinfo.drawPlayer.height - (float)drawinfo.drawPlayer.legFrame.Height + 4f)) + drawinfo.drawPlayer.legPosition + drawinfo.legVect;
         Rectangle legFrame = drawinfo.drawPlayer.legFrame;
         vector.Y -= 2f;
         vector.Y += drawinfo.seatYOffset;
         vector += legsOffset;
         int num = 2;
         int num2 = 42;
         int num3 = 2;
         int num4 = 2;
         int num5 = 0;
         int num6 = 0;
         int num7 = 0;
         bool flag = drawinfo.drawPlayer.legs == 101 || drawinfo.drawPlayer.legs == 102 || drawinfo.drawPlayer.legs == 118 || drawinfo.drawPlayer.legs == 99;
         if (drawinfo.drawPlayer.wearsRobe && !flag)
         {
             num = 0;
             num4 = 0;
             num2 = 6;
             vector.Y += 4f;
             legFrame.Y = legFrame.Height * 5;
         }
         switch (drawinfo.drawPlayer.legs)
         {
         case 214:
         case 215:
         case 216:
             num = -6;
             num4 = 2;
             num5 = 2;
             num3 = 4;
             num2 = 6;
             legFrame = drawinfo.drawPlayer.legFrame;
             vector.Y += 2f;
             break;
         case 106:
         case 143:
         case 226:
             num = 0;
             num4 = 0;
             num2 = 6;
             vector.Y += 4f;
             legFrame.Y = legFrame.Height * 5;
             break;
         case 132:
             num = -2;
             num7 = 2;
             break;
         case 193:
         case 194:
             if (drawinfo.drawPlayer.body == 218)
             {
                 num = -2;
                 num7 = 2;
                 vector.Y += 2f;
             }
             break;
         case 210:
             if (glowmask)
             {
                 Vector2 vector2 = new Vector2((float)Main.rand.Next(-10, 10) * 0.125f, (float)Main.rand.Next(-10, 10) * 0.125f);
                 vector += vector2;
             }
             break;
         }
         for (int num8 = num3; num8 >= 0; num8--)
         {
             Vector2 position = vector + new Vector2(num, 2f) * new Vector2(drawinfo.drawPlayer.direction, 1f);
             Rectangle value = legFrame;
             value.Y += num8 * 2;
             value.Y += num2;
             value.Height -= num2;
             value.Height -= num8 * 2;
             if (num8 != num3)
             {
                 value.Height = 2;
             }
             position.X += drawinfo.drawPlayer.direction * num4 * num8 + num6 * drawinfo.drawPlayer.direction;
             if (num8 != 0)
             {
                 position.X += num7 * drawinfo.drawPlayer.direction;
             }
             position.Y += num2;
             position.Y += num5;
             DrawData item = new DrawData(textureToDraw, position, value, matchingColor, drawinfo.drawPlayer.legRotation, drawinfo.legVect, 1f, drawinfo.playerEffect);
             item.shader = shaderIndex;
             drawinfo.DrawDataCache.Add(item);
         }
     }
References UnifiedRandom.Next(), Main.rand, Main.screenPosition, and DrawData.shader.
Referenced by DrawPlayer_12_Skin(), DrawPlayer_12_Skin_Composite(), DrawPlayer_13_Leggings(), DrawPlayer_14_Shoes(), and DrawPlayer_15_SkinLongCoat().