Terraria: DoorOpeningHelper.Update
Update()
void DoorOpeningHelper.Update (Player player) inline
     {
         LookForDoorsToClose(player);
         if (ShouldTryOpeningDoors())
         {
             LookForDoorsToOpen(player);
         }
         if (_timeWeCanOpenDoorsUsingVelocityAlone > 0)
         {
             _timeWeCanOpenDoorsUsingVelocityAlone--;
         }
     }
References _timeWeCanOpenDoorsUsingVelocityAlone, LookForDoorsToClose(), LookForDoorsToOpen(), and ShouldTryOpeningDoors().