Terraria: DoorOpeningHelper.LookForDoorsToClose
LookForDoorsToClose()
void DoorOpeningHelper.LookForDoorsToClose (Player player) inline
     {
         PlayerInfoForClosingDoors playerInfoForClosingDoor = GetPlayerInfoForClosingDoor(player);
         for (int num = _ongoingOpenDoors.Count - 1; num >= 0; num--)
         {
             DoorOpenCloseTogglingInfo info = _ongoingOpenDoors[num];
             if (info.handler.TryCloseDoor(info, playerInfoForClosingDoor) != 0)
             {
                 _ongoingOpenDoors.RemoveAt(num);
             }
         }
     }
References _ongoingOpenDoors, GetPlayerInfoForClosingDoor(), DoorOpeningHelper.DoorOpenCloseTogglingInfo.handler, and DoorOpeningHelper.DoorAutoHandler.TryCloseDoor().
Referenced by Update().