Terraria: System.Runtime.InteropServices.ComEventsInfo.Find
Find()
static ComEventsInfo System.Runtime.InteropServices.ComEventsInfo.Find (object rcw) inline static
Definition at line 22 of file ComEventsInfo.cs.
    {
        return (ComEventsInfo)Marshal.GetComObjectData(rcw, typeof(ComEventsInfo));
    }
References System.Runtime.InteropServices.Marshal.GetComObjectData().
Referenced by System.Runtime.InteropServices.ComEventsInfo.FromObject(), and System.Runtime.InteropServices.ComEventsHelper.Remove().