Terraria: TileObjectData.TileObjectData
TileObjectData()
TileObjectData.TileObjectData (TileObjectData copyFrom = null) inline
     {
         _parent = null;
         _linkedAlternates = false;
         if (copyFrom == null)
         {
             _usesCustomCanPlace = false;
             _alternates = null;
             _anchor = null;
             _anchorTiles = null;
             _tileObjectBase = null;
             _liquidDeath = null;
             _liquidPlacement = null;
             _placementHooks = null;
             _tileObjectDraw = null;
             _tileObjectStyle = null;
             _tileObjectCoords = null;
         }
         else
         {
             CopyFrom(copyFrom);
         }
     }
References _alternates, _anchor, _anchorTiles, _linkedAlternates, _liquidDeath, _liquidPlacement, _parent, _placementHooks, _tileObjectBase, _tileObjectCoords, _tileObjectDraw, _tileObjectStyle, _usesCustomCanPlace, and CopyFrom().
Referenced by addAlternate(), addBaseTile(), addSubTile(), addTile(), and Initialize().