Terraria: TileObjectData.Initialize
Initialize()
static void TileObjectData.Initialize () inline static
     {
         _baseObject = new TileObjectData();
         _baseObject.SetupBaseObject();
         _data = new List<TileObjectData>(TileID.Count);
         for (int i = 0; i < TileID.Count; i++)
         {
             _data.Add(null);
         }
         newTile = new TileObjectData(_baseObject);
         newSubTile = new TileObjectData(_baseObject);
         newAlternate = new TileObjectData(_baseObject);
         newTile.CoordinateHeights = new int[1] { 16 };
         newTile.CoordinateWidth = 16;
         newTile.CoordinatePadding = 2;
         newTile.StyleHorizontal = true;
         newTile.StyleMultiplier = 27;
         newTile.StyleWrapLimit = 27;
         newTile.UsesCustomCanPlace = false;
         newTile.LavaDeath = true;
         newSubTile.CopyFrom(newTile);
         newSubTile.LavaDeath = false;
         newSubTile.LavaPlacement = LiquidPlacement.Allowed;
         addSubTile(13, 47);
         addSubTile(43);
         addTile(19);
         newTile.CoordinateHeights = new int[1] { 16 };
         newTile.CoordinateWidth = 16;
         newTile.CoordinatePadding = 2;
         newTile.StyleHorizontal = true;
         newTile.StyleMultiplier = 27;
         newTile.StyleWrapLimit = 27;
         newTile.UsesCustomCanPlace = false;
         newTile.LavaDeath = true;
         addTile(427);
         for (int j = 435; j <= 439; j++)
         {
             newTile.CoordinateHeights = new int[1] { 16 };
             newTile.CoordinateWidth = 16;
             newTile.CoordinatePadding = 2;
             newTile.StyleHorizontal = true;
             newTile.StyleMultiplier = 27;
             newTile.StyleWrapLimit = 27;
             newTile.UsesCustomCanPlace = false;
             newTile.LavaDeath = true;
             addTile(j);
         }
         newTile.Width = 4;
         newTile.Height = 8;
         newTile.Origin = new Point16(1, 7);
         newTile.AnchorBottom = new AnchorData(AnchorType.SolidTile | AnchorType.SolidWithTop, newTile.Width, 0);
         newTile.UsesCustomCanPlace = true;
         newTile.HookPlaceOverride = new PlacementHook(WorldGen.PlaceXmasTree_Direct, -1, 0, processedCoordinates: true);
         newTile.CoordinateHeights = new int[8] { 16, 16, 16, 16, 16, 16, 16, 16 };
         newTile.CoordinateWidth = 16;
         newTile.CoordinatePadding = 0;
         addTile(171);
         newTile.Width = 1;
         newTile.Height = 1;
         newTile.Origin = new Point16(0, 0);
         newTile.AnchorTop = new AnchorData(AnchorType.EmptyTile, newTile.Width, 0);
         newTile.AnchorBottom = new AnchorData(AnchorType.SolidTile, newTile.Width, 0);
         newTile.UsesCustomCanPlace = true;
         newTile.WaterPlacement = LiquidPlacement.NotAllowed;
         newTile.LavaDeath = true;
         newTile.CoordinateHeights = new int[1] { 38 };
         newTile.CoordinateWidth = 32;
         newTile.CoordinatePadding = 2;
         newTile.DrawYOffset = -20;
         newTile.StyleHorizontal = true;
         newTile.DrawFlipHorizontal = true;
         addBaseTile(out StyleDye);
         newTile.CopyFrom(StyleDye);
         newSubTile.CopyFrom(StyleDye);
         newSubTile.AnchorValidWalls = new int[1];
         addSubTile(3);
         newSubTile.CopyFrom(StyleDye);
         newSubTile.AnchorValidWalls = new int[1];
         addSubTile(4);
         newSubTile.CopyFrom(StyleDye);
         newSubTile.WaterPlacement = LiquidPlacement.OnlyInFullLiquid;
         addSubTile(5);
         newSubTile.CopyFrom(StyleDye);
         newSubTile.AnchorValidTiles = new int[1] { 80 };
         newSubTile.AnchorLeft = new AnchorData(AnchorType.EmptyTile, 1, 1);
         newSubTile.AnchorRight = new AnchorData(AnchorType.EmptyTile, 1, 1);
         addSubTile(6);
         newSubTile.CopyFrom(StyleDye);
         newSubTile.DrawYOffset = -6;
         newSubTile.WaterPlacement = LiquidPlacement.Allowed;
         newSubTile.AnchorTop = new AnchorData(AnchorType.SolidTile, newSubTile.Width, 0);
         newSubTile.AnchorBottom = new AnchorData(AnchorType.EmptyTile, newSubTile.Width, 0);
         addSubTile(7);
         addTile(227);
         newTile.CopyFrom(StyleDye);
         newTile.CoordinateHeights = new int[1] { 20 };
         newTile.CoordinateWidth = 20;
         newTile.CoordinatePadding = 2;
         newTile.DrawYOffset = -2;
         newTile.AnchorTop = AnchorData.Empty;
         newTile.AnchorBottom = new AnchorData(AnchorType.SolidTile | AnchorType.Table, newTile.Width, 0);
         newTile.Direction = TileObjectDirection.PlaceLeft;
         newTile.StyleHorizontal = true;
         newTile.DrawFlipHorizontal = false;
         newAlternate.CopyFrom(newTile);
         newAlternate.Direction = TileObjectDirection.PlaceRight;
         addAlternate(1);
         addTile(579);
         newTile.Width = 1;
         newTile.Height = 3;
         newTile.Origin = new Point16(0, 0);
         newTile.AnchorTop = new AnchorData(AnchorType.SolidTile, newTile.Width, 0);
         newTile.AnchorBottom = new AnchorData(AnchorType.SolidTile, newTile.Width, 0);
         newTile.UsesCustomCanPlace = true;
         newTile.LavaDeath = true;
         newTile.CoordinateHeights = new int[3] { 16, 16, 16 };
         newTile.CoordinateWidth = 16;
         newTile.CoordinatePadding = 2;
         newTile.StyleHorizontal = false;
         newTile.StyleWrapLimit = 36;
         newTile.StyleLineSkip = 3;
         newAlternate.CopyFrom(newTile);
         newAlternate.Origin = new Point16(0, 1);
         addAlternate(0);
         newAlternate.CopyFrom(newTile);
         newAlternate.Origin = new Point16(0, 2);
         addAlternate(0);
         newSubTile.CopyFrom(newTile);
         newSubTile.LinkedAlternates = true;
         newSubTile.LavaDeath = false;
         newSubTile.LavaPlacement = LiquidPlacement.Allowed;
         addSubTile(19, 48);
         addTile(10);
         newTile.Width = 2;
         newTile.Height = 3;
         newTile.Origin = new Point16(0, 0);
         newTile.AnchorTop = new AnchorData(AnchorType.SolidTile, 1, 0);
         newTile.AnchorBottom = new AnchorData(AnchorType.SolidTile, 1, 0);
         newTile.UsesCustomCanPlace = true;
         newTile.LavaDeath = true;
         newTile.CoordinateHeights = new int[3] { 16, 16, 16 };
         newTile.CoordinateWidth = 16;
         newTile.CoordinatePadding = 2;
         newTile.StyleHorizontal = false;
         newTile.StyleWrapLimit = 36;
         newTile.StyleLineSkip = 2;
         newTile.Direction = TileObjectDirection.PlaceRight;
         newAlternate.CopyFrom(newTile);
         newAlternate.Origin = new Point16(0, 1);
         addAlternate(0);
         newAlternate.CopyFrom(newTile);
         newAlternate.Origin = new Point16(0, 2);
         addAlternate(0);
         newAlternate.CopyFrom(newTile);
         newAlternate.Origin = new Point16(1, 0);
         newAlternate.AnchorTop = new AnchorData(AnchorType.SolidTile, 1, 1);
         newAlternate.AnchorBottom = new AnchorData(AnchorType.SolidTile, 1, 1);
         newAlternate.Direction = TileObjectDirection.PlaceLeft;
         addAlternate(1);
         newAlternate.CopyFrom(newTile);
         newAlternate.Origin = new Point16(1, 1);
         newAlternate.AnchorTop = new AnchorData(AnchorType.SolidTile, 1, 1);
         newAlternate.AnchorBottom = new AnchorData(AnchorType.SolidTile, 1, 1);
         newAlternate.Direction = TileObjectDirection.PlaceLeft;
         addAlternate(1);
         newAlternate.CopyFrom(newTile);
         newAlternate.Origin = new Point16(1, 2);
         newAlternate.AnchorTop = new AnchorData(AnchorType.SolidTile, 1, 1);
         newAlternate.AnchorBottom = new AnchorData(AnchorType.SolidTile, 1, 1);
         newAlternate.Direction = TileObjectDirection.PlaceLeft;
         addAlternate(1);
         newSubTile.CopyFrom(newTile);
         newSubTile.LinkedAlternates = true;
         newSubTile.LavaDeath = false;
         newSubTile.LavaPlacement = LiquidPlacement.Allowed;
         addSubTile(19, 48);
         addTile(11);
         newTile.Width = 1;
         newTile.Height = 5;
         newTile.Origin = new Point16(0, 0);
         newTile.AnchorTop = new AnchorData(AnchorType.SolidTile, newTile.Width, 0);
         newTile.AnchorBottom = new AnchorData(AnchorType.SolidTile, newTile.Width, 0);
         newTile.UsesCustomCanPlace = true;
         newTile.LavaDeath = true;
         newTile.DrawYOffset = -2;
         newTile.CoordinateHeights = new int[5] { 18, 16, 16, 16, 18 };
         newTile.CoordinateWidth = 16;
         newTile.CoordinatePadding = 2;
         newTile.Direction = TileObjectDirection.PlaceLeft;
         newTile.StyleMultiplier = 2;
         newTile.StyleWrapLimit = 2;
         for (int k = 1; k < 5; k++)
         {
             newAlternate.CopyFrom(newTile);
             newAlternate.Origin = new Point16(0, k);
             addAlternate(0);
         }
         newAlternate.CopyFrom(newTile);
         newAlternate.Direction = TileObjectDirection.PlaceRight;
         addAlternate(1);
         for (int l = 1; l < 5; l++)
         {
             newAlternate.CopyFrom(newTile);
             newAlternate.Origin = new Point16(0, l);
             newAlternate.Direction = TileObjectDirection.PlaceRight;
             addAlternate(1);
         }
         addTile(388);
         newTile.FullCopyFrom(388);
         addTile(389);
         newTile.Width = 1;
         newTile.Height = 1;
         newTile.Origin = new Point16(0, 0);
         newTile.AnchorBottom = new AnchorData(AnchorType.Table, newTile.Width, 0);
         newTile.UsesCustomCanPlace = true;
         newTile.LavaDeath = true;
         newTile.CoordinateHeights = new int[1] { 16 };
         newTile.CoordinateWidth = 16;
         newTile.CoordinatePadding = 2;
         addBaseTile(out StyleOnTable1x1);
         newTile.CopyFrom(StyleOnTable1x1);
         newTile.CoordinatePadding = 2;
         newTile.StyleHorizontal = true;
         addTile(13);
         newTile.CopyFrom(StyleOnTable1x1);
         newTile.CoordinateHeights = new int[1] { 20 };
         newTile.DrawYOffset = -4;
         newSubTile.CopyFrom(newTile);
         newSubTile.LavaDeath = false;
         newSubTile.LavaPlacement = LiquidPlacement.Allowed;
         addSubTile(25, 41);
         newSubTile.CopyFrom(newTile);
         newSubTile.WaterDeath = false;
         newSubTile.WaterPlacement = LiquidPlacement.Allowed;
         addSubTile(39);
         addTile(33);
         newTile.CopyFrom(StyleOnTable1x1);
         newTile.CoordinateHeights = new int[1] { 20 };
         newTile.DrawYOffset = -4;
         addTile(49);
         newTile.CopyFrom(StyleOnTable1x1);
         newTile.CoordinateHeights = new int[1] { 16 };
         newTile.AnchorBottom = new AnchorData(AnchorType.SolidTile | AnchorType.SolidWithTop | AnchorType.Table, newTile.Width, 0);
         newTile.DrawYOffset = 2;
         newTile.HookPostPlaceMyPlayer = new PlacementHook(TEFoodPlatter.Hook_AfterPlacement, -1, 0, processedCoordinates: true);
         newTile.StyleHorizontal = true;
         newTile.Direction = TileObjectDirection.PlaceLeft;
         newAlternate.CopyFrom(newTile);
         newAlternate.Direction = TileObjectDirection.PlaceRight;
         addAlternate(1);
         addTile(520);
         newTile.CopyFrom(StyleOnTable1x1);
         newTile.CoordinateHeights = new int[1] { 20 };
         newTile.DrawYOffset = -4;
         addTile(372);
         newTile.CopyFrom(StyleOnTable1x1);
         newTile.CoordinateHeights = new int[1] { 20 };
         newTile.DrawYOffset = -4;
         addTile(646);
         newTile.CopyFrom(StyleOnTable1x1);
         newTile.StyleHorizontal = true;
         newTile.RandomStyleRange = 5;
         addTile(50);
         newTile.CopyFrom(StyleOnTable1x1);
         newTile.AnchorBottom = new AnchorData(AnchorType.SolidTile | AnchorType.SolidWithTop | AnchorType.Table, newTile.Width, 0);
         newTile.DrawYOffset = 2;
         addTile(494);
         newTile.CopyFrom(StyleOnTable1x1);
         newTile.AnchorBottom = new AnchorData(AnchorType.SolidTile | AnchorType.SolidWithTop | AnchorType.Table | AnchorType.SolidSide, newTile.Width, 0);
         newTile.DrawYOffset = 2;
         newTile.LavaDeath = false;
         addTile(78);
         newTile.CopyFrom(StyleOnTable1x1);
         newTile.CoordinateHeights = new int[1] { 20 };
         newTile.DrawYOffset = -4;
         addTile(174);
         newTile.Width = 1;
         newTile.Height = 3;
         newTile.Origin = new Point16(0, 2);
         newTile.AnchorBottom = new AnchorData(AnchorType.SolidTile | AnchorType.SolidWithTop | AnchorType.SolidSide, newTile.Width, 0);
         newTile.UsesCustomCanPlace = true;
         newTile.LavaDeath = true;
         newTile.CoordinateHeights = new int[3] { 16, 16, 16 };
         newTile.CoordinateWidth = 16;
         newTile.CoordinatePadding = 2;
         addBaseTile(out Style1xX);
         newTile.CopyFrom(Style1xX);
         newTile.StyleWrapLimitVisualOverride = 37;
         newTile.StyleLineSkip = 2;
         newTile.DrawYOffset = 2;
         newTile.WaterDeath = true;
         newTile.WaterPlacement = LiquidPlacement.NotAllowed;
         newTile.LavaPlacement = LiquidPlacement.NotAllowed;
         newSubTile.CopyFrom(newTile);
         newSubTile.LavaDeath = false;
         newSubTile.LavaPlacement = LiquidPlacement.Allowed;
         addSubTile(23, 42);
         newSubTile.CopyFrom(newTile);
         newSubTile.WaterDeath = false;
         newSubTile.WaterPlacement = LiquidPlacement.Allowed;
         addSubTile(40);
         addTile(93);
         newTile.CopyFrom(Style1xX);
         newTile.Height = 6;
         newTile.Origin = new Point16(0, 5);
         newTile.CoordinateHeights = new int[6] { 16, 16, 16, 16, 16, 16 };
         addTile(92);
         newTile.CopyFrom(Style1xX);
         newTile.LavaPlacement = LiquidPlacement.NotAllowed;
         newTile.StyleHorizontal = true;
         newTile.Direction = TileObjectDirection.PlaceLeft;
         newAlternate.CopyFrom(newTile);
         newAlternate.Direction = TileObjectDirection.PlaceRight;
         addAlternate(1);
         addTile(453);
         newTile.Width = 1;
         newTile.Height = 2;
         newTile.Origin = new Point16(0, 0);
         newTile.AnchorTop = new AnchorData(AnchorType.SolidTile | AnchorType.SolidSide | AnchorType.PlanterBox, newTile.Width, 0);
         newTile.UsesCustomCanPlace = true;
         newTile.CoordinateHeights = new int[2] { 16, 16 };
         newTile.CoordinateWidth = 16;
         newTile.CoordinatePadding = 2;
         newTile.LavaDeath = true;
         addBaseTile(out Style1x2Top);
         newTile.CopyFrom(Style1x2Top);
         newTile.DrawYOffset = -2;
         newAlternate.CopyFrom(newTile);
         newAlternate.AnchorTop = new AnchorData(AnchorType.Platform, newTile.Width, 0);
         newAlternate.DrawYOffset = -10;
         addAlternate(0);
         addTile(270);
         newTile.CopyFrom(Style1x2Top);
         newTile.DrawYOffset = -2;
         newAlternate.CopyFrom(newTile);
         newAlternate.AnchorTop = new AnchorData(AnchorType.Platform, newTile.Width, 0);
         newAlternate.DrawYOffset = -10;
         addAlternate(0);
         addTile(271);
         newTile.CopyFrom(Style1x2Top);
         newTile.DrawYOffset = -2;
         newAlternate.CopyFrom(newTile);
         newAlternate.AnchorTop = new AnchorData(AnchorType.Platform, newTile.Width, 0);
         newAlternate.DrawYOffset = -10;
         addAlternate(0);
         addTile(581);
         newTile.CopyFrom(Style1x2Top);
         newTile.DrawYOffset = -2;
         newAlternate.CopyFrom(newTile);
         newAlternate.AnchorTop = new AnchorData(AnchorType.Platform, newTile.Width, 0);
         newAlternate.DrawYOffset = -10;
         addAlternate(0);
         addTile(660);
         newTile.CopyFrom(Style1x2Top);
         newTile.DrawYOffset = -2;
         newTile.StyleWrapLimit = 6;
         newAlternate.CopyFrom(newTile);
         newAlternate.AnchorTop = new AnchorData(AnchorType.Platform, newTile.Width, 0);
         newAlternate.DrawYOffset = -10;
         addAlternate(0);
         addTile(572);
         newTile.CopyFrom(Style1x2Top);
         newTile.DrawYOffset = -2;
         newAlternate.CopyFrom(newTile);
         newAlternate.AnchorTop = new AnchorData(AnchorType.Platform, newTile.Width, 0);
         newAlternate.DrawYOffset = -10;
         addAlternate(0);
         newSubTile.CopyFrom(newTile);
         newSubTile.LavaDeath = false;
         newSubTile.LavaPlacement = LiquidPlacement.Allowed;
         addSubTile(32, 48);
         newSubTile.CopyFrom(newTile);
         newSubTile.WaterDeath = false;
         newSubTile.WaterPlacement = LiquidPlacement.Allowed;
         addSubTile(46);
         addTile(42);
         newTile.CopyFrom(Style1x2Top);
         newTile.Height = 3;
         newTile.CoordinateHeights = new int[3] { 16, 16, 16 };
         newTile.StyleHorizontal = true;
         newTile.AnchorTop = new AnchorData(AnchorType.SolidTile | AnchorType.SolidSide | AnchorType.SolidBottom | AnchorType.PlanterBox, newTile.Width, 0);
         newTile.StyleWrapLimit = 111;
         newTile.DrawYOffset = -2;
         newAlternate.CopyFrom(newTile);
         newAlternate.AnchorTop = new AnchorData(AnchorType.Platform, newTile.Width, 0);
         newAlternate.DrawYOffset = -10;
         addAlternate(0);
         addTile(91);
         newTile.Width = 4;
         newTile.Height = 2;
         newTile.Origin = new Point16(1, 1);
         newTile.AnchorBottom = new AnchorData(AnchorType.SolidTile | AnchorType.SolidWithTop | AnchorType.SolidSide, newTile.Width, 0);
         newTile.UsesCustomCanPlace = true;
         newTile.CoordinateHeights = new int[2] { 16, 18 };
         newTile.CoordinateWidth = 16;
         newTile.CoordinatePadding = 2;
         newTile.StyleHorizontal = true;
         newTile.LavaDeath = false;
         addTile(487);
         newTile.Width = 4;
         newTile.Height = 2;
         newTile.Origin = new Point16(1, 1);
         newTile.AnchorBottom = new AnchorData(AnchorType.SolidTile | AnchorType.SolidWithTop | AnchorType.SolidSide, newTile.Width, 0);
         newTile.UsesCustomCanPlace = true;
         newTile.CoordinateHeights = new int[2] { 16, 16 };
         newTile.CoordinateWidth = 16;
         newTile.CoordinatePadding = 2;
         newTile.Direction = TileObjectDirection.PlaceLeft;
         newTile.StyleMultiplier = 2;
         newTile.StyleWrapLimit = 2;
         newTile.StyleHorizontal = true;
         newTile.LavaDeath = true;
         newAlternate.CopyFrom(newTile);
         newAlternate.Direction = TileObjectDirection.PlaceRight;
         addAlternate(1);
         addBaseTile(out Style4x2);
         newTile.CopyFrom(Style4x2);
         newSubTile.CopyFrom(newTile);
         newSubTile.LinkedAlternates = true;
         newSubTile.LavaDeath = false;
         newSubTile.LavaPlacement = LiquidPlacement.Allowed;
         addSubTile(25, 42);
         addTile(90);
         newTile.CopyFrom(Style4x2);
         newTile.CoordinateHeights = new int[2] { 16, 18 };
         newTile.CoordinatePaddingFix = new Point16(0, -2);
         newSubTile.CopyFrom(newTile);
         newSubTile.LinkedAlternates = true;
         newSubTile.LavaDeath = false;
         newSubTile.LavaPlacement = LiquidPlacement.Allowed;
         addSubTile(8, 42);
         addTile(79);
         newTile.Width = 4;
         newTile.Height = 3;
         newTile.Origin = new Point16(1, 2);
         newTile.AnchorBottom = new AnchorData(AnchorType.SolidTile | AnchorType.SolidWithTop, 2, 1);
         newTile.UsesCustomCanPlace = true;
         newTile.LavaDeath = true;
         newTile.CoordinateHeights = new int[3] { 16, 16, 16 };
         newTile.CoordinateWidth = 16;
         newTile.StyleHorizontal = true;
         newTile.CoordinatePadding = 2;
         addTile(209);
         newTile.Width = 3;
         newTile.Height = 2;
         newTile.Origin = new Point16(1, 1);
         newTile.AnchorBottom = new AnchorData(AnchorType.SolidTile | AnchorType.Table | AnchorType.SolidSide, newTile.Width, 0);
         newTile.UsesCustomCanPlace = true;
         newTile.CoordinateHeights = new int[2] { 16, 16 };
         newTile.CoordinateWidth = 16;
         newTile.CoordinatePadding = 2;
         newTile.LavaDeath = true;
         newTile.DrawYOffset = 0;
         addBaseTile(out StyleSmallCage);
         newTile.CopyFrom(StyleSmallCage);
         addTile(285);
         newTile.CopyFrom(StyleSmallCage);
         addTile(286);
         newTile.CopyFrom(StyleSmallCage);
         addTile(582);
         newTile.CopyFrom(StyleSmallCage);
         addTile(619);
         newTile.CopyFrom(StyleSmallCage);
         addTile(298);
         newTile.CopyFrom(StyleSmallCage);
         addTile(299);
         newTile.CopyFrom(StyleSmallCage);
         addTile(310);
         newTile.CopyFrom(StyleSmallCage);
         addTile(532);
         newTile.CopyFrom(StyleSmallCage);
         addTile(533);
         newTile.CopyFrom(StyleSmallCage);
         addTile(339);
         newTile.CopyFrom(StyleSmallCage);
         addTile(538);
         newTile.CopyFrom(StyleSmallCage);
         addTile(555);
         newTile.CopyFrom(StyleSmallCage);
         addTile(556);
         newTile.CopyFrom(StyleSmallCage);
         addTile(629);
         newTile.Width = 6;
         newTile.Height = 3;
         newTile.Origin = new Point16(3, 2);
         newTile.AnchorBottom = new AnchorData(AnchorType.SolidTile | AnchorType.Table | AnchorType.SolidSide, newTile.Width, 0);
         newTile.UsesCustomCanPlace = true;
         newTile.CoordinateHeights = new int[3] { 16, 16, 16 };
         newTile.CoordinateWidth = 16;
         newTile.CoordinatePadding = 2;
         newTile.DrawYOffset = 0;
         newTile.LavaDeath = true;
         addBaseTile(out Style6x3);
         newTile.CopyFrom(Style6x3);
         addTile(275);
         newTile.CopyFrom(Style6x3);
         addTile(276);
         newTile.CopyFrom(Style6x3);
         addTile(413);
         newTile.CopyFrom(Style6x3);
         addTile(414);
         newTile.CopyFrom(Style6x3);
         addTile(277);
         newTile.CopyFrom(Style6x3);
         addTile(278);
         newTile.CopyFrom(Style6x3);
         addTile(279);
         newTile.CopyFrom(Style6x3);
         addTile(280);
         newTile.CopyFrom(Style6x3);
         addTile(281);
         newTile.CopyFrom(Style6x3);
         addTile(632);
         newTile.CopyFrom(Style6x3);
         addTile(640);
         newTile.CopyFrom(Style6x3);
         addTile(643);
         newTile.CopyFrom(Style6x3);
         addTile(644);
         newTile.CopyFrom(Style6x3);
         addTile(645);
         newTile.CopyFrom(Style6x3);
         addTile(296);
         newTile.CopyFrom(Style6x3);
         addTile(297);
         newTile.CopyFrom(Style6x3);
         addTile(309);
         newTile.CopyFrom(Style6x3);
         addTile(550);
         newTile.CopyFrom(Style6x3);
         addTile(551);
         newTile.CopyFrom(Style6x3);
         addTile(553);
         newTile.CopyFrom(Style6x3);
         addTile(554);
         newTile.CopyFrom(Style6x3);
         addTile(558);
         newTile.CopyFrom(Style6x3);
         addTile(559);
         newTile.CopyFrom(Style6x3);
         addTile(599);
         newTile.CopyFrom(Style6x3);
         addTile(600);
         newTile.CopyFrom(Style6x3);
         addTile(601);
         newTile.CopyFrom(Style6x3);
         addTile(602);
         newTile.CopyFrom(Style6x3);
         addTile(603);
         newTile.CopyFrom(Style6x3);
         addTile(604);
         newTile.CopyFrom(Style6x3);
         addTile(605);
         newTile.CopyFrom(Style6x3);
         addTile(606);
         newTile.CopyFrom(Style6x3);
         addTile(607);
         newTile.CopyFrom(Style6x3);
         addTile(608);
         newTile.CopyFrom(Style6x3);
         addTile(609);
         newTile.CopyFrom(Style6x3);
         addTile(610);
         newTile.CopyFrom(Style6x3);
         addTile(611);
         newTile.CopyFrom(Style6x3);
         addTile(612);
         newTile.Width = 5;
         newTile.Height = 4;
         newTile.Origin = new Point16(2, 3);
         newTile.AnchorBottom = new AnchorData(AnchorType.SolidTile | AnchorType.SolidWithTop | AnchorType.SolidSide, newTile.Width, 0);
         newTile.UsesCustomCanPlace = true;
         newTile.CoordinateHeights = new int[4] { 16, 16, 16, 16 };
         newTile.CoordinateWidth = 16;
         newTile.CoordinatePadding = 2;
         newTile.DrawYOffset = 2;
         newTile.LavaDeath = true;
         addBaseTile(out Style5x4);
         newTile.CopyFrom(Style5x4);
         addTile(464);
         newTile.CopyFrom(Style5x4);
         addTile(466);
         newTile.Width = 2;
         newTile.Height = 1;
         newTile.Origin = new Point16(0, 0);
         newTile.AnchorBottom = new AnchorData(AnchorType.SolidTile | AnchorType.SolidWithTop | AnchorType.SolidSide, newTile.Width, 0);
         newTile.UsesCustomCanPlace = true;
         newTile.CoordinateHeights = new int[1] { 16 };
         newTile.CoordinateWidth = 16;
         newTile.CoordinatePadding = 2;
         newTile.StyleHorizontal = true;
         newTile.LavaDeath = true;
         addBaseTile(out Style2x1);
         newTile.CopyFrom(Style2x1);
         newTile.AnchorBottom = new AnchorData(AnchorType.Table, newTile.Width, 0);
         addTile(29);
         newTile.CopyFrom(Style2x1);
         newTile.AnchorBottom = new AnchorData(AnchorType.Table, newTile.Width, 0);
         addTile(103);
         newTile.CopyFrom(Style2x1);
         newTile.AnchorBottom = new AnchorData(AnchorType.Table, newTile.Width, 0);
         addTile(462);
         newTile.CopyFrom(Style2x1);
         newTile.CoordinateHeights = new int[1] { 18 };
         newSubTile.CopyFrom(newTile);
         newSubTile.LavaDeath = false;
         newSubTile.LavaPlacement = LiquidPlacement.Allowed;
         addSubTile(14, 43);
         addTile(18);
         newTile.CopyFrom(Style2x1);
         newTile.CoordinateHeights = new int[1] { 18 };
         addTile(16);
         newTile.CopyFrom(Style2x1);
         newTile.DrawYOffset = 2;
         newTile.LavaDeath = false;
         addTile(134);
         newTile.CopyFrom(Style2x1);
         newTile.AnchorBottom = AnchorData.Empty;
         newTile.AnchorLeft = new AnchorData(AnchorType.SolidTile, newTile.Height, 0);
         newTile.AnchorRight = new AnchorData(AnchorType.SolidTile, newTile.Height, 0);
         addTile(387);
         newTile.CopyFrom(Style2x1);
         newTile.DrawYOffset = 2;
         newTile.StyleWrapLimit = 53;
         addTile(649);
         newTile.CopyFrom(Style2x1);
         newTile.DrawYOffset = 2;
         newTile.LavaDeath = false;
         newAlternate.CopyFrom(newTile);
         newAlternate.Direction = TileObjectDirection.PlaceRight;
         addAlternate(1);
         newAlternate.CopyFrom(newTile);
         newAlternate.AnchorBottom = AnchorData.Empty;
         newAlternate.AnchorTop = new AnchorData(AnchorType.SolidBottom, newTile.Width, 0);
         newAlternate.DrawYOffset = -2;
         addAlternate(2);
         newAlternate.CopyFrom(newTile);
         newAlternate.Direction = TileObjectDirection.PlaceRight;
         newAlternate.AnchorBottom = AnchorData.Empty;
         newAlternate.AnchorTop = new AnchorData(AnchorType.SolidBottom, newTile.Width, 0);
         newAlternate.DrawYOffset = -2;
         addAlternate(3);
         addTile(443);
         newTile.Width = 2;
         newTile.Height = 3;
         newTile.Origin = new Point16(1, 2);
         newTile.AnchorBottom = new AnchorData(AnchorType.SolidTile | AnchorType.SolidWithTop | AnchorType.SolidSide, newTile.Width, 0);
         newTile.UsesCustomCanPlace = true;
         newTile.CoordinateHeights = new int[3] { 16, 16, 16 };
         newTile.CoordinateWidth = 16;
         newTile.CoordinatePadding = 2;
         newTile.StyleHorizontal = true;
         addBaseTile(out Style2xX);
         newTile.CopyFrom(Style2xX);
         newTile.Height = 5;
         newTile.Origin = new Point16(1, 4);
         newTile.CoordinateHeights = new int[5] { 16, 16, 16, 16, 16 };
         newTile.DrawYOffset = 2;
         newTile.LavaDeath = true;
         addTile(547);
         newTile.CopyFrom(Style2xX);
         newTile.Height = 5;
         newTile.Origin = new Point16(1, 4);
         newTile.CoordinateHeights = new int[5] { 16, 16, 16, 16, 16 };
         newTile.DrawYOffset = 2;
         newTile.LavaDeath = true;
         addTile(623);
         newTile.CopyFrom(Style2xX);
         newTile.Height = 4;
         newTile.Origin = new Point16(1, 3);
         newTile.CoordinateHeights = new int[4] { 16, 16, 16, 16 };
         newTile.DrawYOffset = 2;
         addTile(207);
         newTile.CopyFrom(Style2xX);
         newTile.Height = 3;
         newTile.Origin = new Point16(1, 2);
         newTile.CoordinateHeights = new int[3] { 16, 16, 18 };
         addTile(410);
         newTile.CopyFrom(Style2xX);
         newTile.Height = 3;
         newTile.Origin = new Point16(1, 2);
         newTile.CoordinateHeights = new int[3] { 16, 16, 16 };
         newTile.DrawYOffset = 2;
         addTile(480);
         newTile.CopyFrom(Style2xX);
         newTile.Height = 3;
         newTile.Origin = new Point16(1, 2);
         newTile.CoordinateHeights = new int[3] { 16, 16, 16 };
         newTile.DrawYOffset = 2;
         addTile(509);
         newTile.CopyFrom(Style2xX);
         newTile.Height = 3;
         newTile.Origin = new Point16(1, 2);
         newTile.CoordinateHeights = new int[3] { 16, 16, 16 };
         newTile.DrawYOffset = 2;
         addTile(657);
         newTile.CopyFrom(Style2xX);
         newTile.Height = 3;
         newTile.Origin = new Point16(1, 2);
         newTile.CoordinateHeights = new int[3] { 16, 16, 16 };
         newTile.DrawYOffset = 2;
         addTile(658);
         newTile.CopyFrom(Style2xX);
         newTile.Height = 3;
         newTile.Origin = new Point16(1, 2);
         newTile.CoordinateHeights = new int[3] { 16, 16, 16 };
         addTile(489);
         newTile.CopyFrom(Style2xX);
         newTile.DrawYOffset = 2;
         newTile.StyleWrapLimit = 7;
         newTile.Direction = TileObjectDirection.PlaceLeft;
         newAlternate.CopyFrom(newTile);
         newAlternate.Direction = TileObjectDirection.PlaceRight;
         addAlternate(7);
         addTile(349);
         newTile.CopyFrom(Style2xX);
         addTile(337);
         newTile.CopyFrom(Style2xX);
         newTile.AnchorBottom = new AnchorData(AnchorType.SolidTile | AnchorType.SolidWithTop | AnchorType.Table | AnchorType.SolidSide, newTile.Width, 0);
         newTile.DrawYOffset = 2;
         addTile(560);
         newTile.CopyFrom(Style2xX);
         newTile.Height = 3;
         newTile.Origin = new Point16(0, 0);
         newTile.AnchorBottom = default(AnchorData);
         newTile.AnchorTop = new AnchorData(AnchorType.SolidTile | AnchorType.SolidSide | AnchorType.SolidBottom | AnchorType.PlanterBox, newTile.Width, 0);
         newTile.LavaDeath = true;
         newTile.DrawYOffset = -2;
         newAlternate.CopyFrom(newTile);
         newAlternate.AnchorTop = new AnchorData(AnchorType.PlatformNonHammered, newTile.Width, 0);
         newAlternate.DrawYOffset = -10;
         addAlternate(0);
         addTile(465);
         newTile.CopyFrom(Style2xX);
         newTile.Height = 3;
         newTile.Origin = new Point16(0, 0);
         newTile.AnchorBottom = default(AnchorData);
         newTile.AnchorTop = new AnchorData(AnchorType.SolidTile | AnchorType.SolidSide | AnchorType.SolidBottom, newTile.Width, 0);
         newTile.LavaDeath = true;
         addTile(531);
         newTile.CopyFrom(Style2xX);
         addTile(320);
         newTile.CopyFrom(Style2xX);
         addTile(456);
         newTile.CopyFrom(Style2xX);
         newTile.HookPostPlaceMyPlayer = new PlacementHook(TETrainingDummy.Hook_AfterPlacement, -1, 0, processedCoordinates: false);
         newTile.Direction = TileObjectDirection.PlaceLeft;
         newTile.StyleMultiplier = 2;
         newTile.StyleWrapLimit = 2;
         newTile.DrawYOffset = 2;
         newAlternate.CopyFrom(newTile);
         newAlternate.Direction = TileObjectDirection.PlaceRight;
         addAlternate(1);
         addTile(378);
         newTile.CopyFrom(Style2xX);
         newTile.DrawYOffset = 2;
         newTile.StyleWrapLimit = 55;
         newTile.Direction = TileObjectDirection.PlaceLeft;
         newAlternate.CopyFrom(newTile);
         newAlternate.Direction = TileObjectDirection.PlaceRight;
         addAlternate(165);
         addTile(105);
         newTile.CopyFrom(Style2xX);
         newTile.Origin = new Point16(0, 2);
         newTile.RandomStyleRange = 2;
         newTile.Direction = TileObjectDirection.PlaceLeft;
         newTile.StyleWrapLimit = 2;
         newTile.StyleMultiplier = 2;
         newAlternate.CopyFrom(newTile);
         newAlternate.Direction = TileObjectDirection.PlaceRight;
         addAlternate(2);
         addTile(545);
         newTile.CopyFrom(Style2xX);
         newTile.DrawYOffset = 2;
         newTile.Height = 5;
         newTile.Origin = new Point16(0, 4);
         newTile.CoordinateHeights = new int[5] { 16, 16, 16, 16, 16 };
         newTile.LavaDeath = true;
         newSubTile.CopyFrom(newTile);
         newSubTile.LavaDeath = false;
         newSubTile.LavaPlacement = LiquidPlacement.Allowed;
         addSubTile(17, 43);
         addTile(104);
         newTile.CopyFrom(Style2xX);
         newTile.Origin = new Point16(0, 2);
         newTile.Direction = TileObjectDirection.PlaceLeft;
         newAlternate.CopyFrom(newTile);
         newAlternate.Direction = TileObjectDirection.PlaceRight;
         addAlternate(1);
         newTile.LavaDeath = true;
         addTile(128);
         newTile.CopyFrom(Style2xX);
         newTile.Origin = new Point16(0, 2);
         newTile.Direction = TileObjectDirection.PlaceLeft;
         newTile.LavaDeath = true;
         newTile.DrawYOffset = 2;
         newAlternate.CopyFrom(newTile);
         newAlternate.Direction = TileObjectDirection.PlaceRight;
         addAlternate(1);
         addTile(506);
         newTile.CopyFrom(Style2xX);
         newTile.Origin = new Point16(0, 2);
         newTile.Direction = TileObjectDirection.PlaceLeft;
         newAlternate.CopyFrom(newTile);
         newAlternate.Direction = TileObjectDirection.PlaceRight;
         addAlternate(1);
         newTile.LavaDeath = true;
         addTile(269);
         newTile.CopyFrom(Style2xX);
         newTile.LavaDeath = false;
         newTile.DrawYOffset = 2;
         newTile.Origin = new Point16(0, 2);
         newTile.Direction = TileObjectDirection.PlaceLeft;
         newTile.DrawStyleOffset = 4;
         newTile.HookPostPlaceMyPlayer = new PlacementHook(TEDisplayDoll.Hook_AfterPlacement, -1, 0, processedCoordinates: false);
         newTile.AnchorInvalidTiles = new int[5] { 127, 138, 664, 665, 484 };
         newAlternate.CopyFrom(newTile);
         newAlternate.Direction = TileObjectDirection.PlaceRight;
         addAlternate(1);
         addTile(470);
         newTile.CopyFrom(Style2xX);
         newTile.Height = 3;
         newTile.Origin = new Point16(0, 0);
         newTile.AnchorBottom = default(AnchorData);
         newTile.AnchorTop = new AnchorData(AnchorType.SolidTile | AnchorType.SolidSide | AnchorType.SolidBottom | AnchorType.PlanterBox, newTile.Width, 0);
         newTile.LavaDeath = true;
         newTile.DrawYOffset = -2;
         newAlternate.CopyFrom(newTile);
         newAlternate.AnchorTop = new AnchorData(AnchorType.PlatformNonHammered, newTile.Width, 0);
         newAlternate.DrawYOffset = -10;
         addAlternate(0);
         addTile(591);
         newTile.CopyFrom(Style2xX);
         newTile.Height = 3;
         newTile.Origin = new Point16(0, 0);
         newTile.AnchorBottom = default(AnchorData);
         newTile.AnchorTop = new AnchorData(AnchorType.SolidTile | AnchorType.SolidSide | AnchorType.SolidBottom | AnchorType.PlanterBox, newTile.Width, 0);
         newTile.LavaDeath = true;
         newTile.DrawYOffset = -2;
         newAlternate.CopyFrom(newTile);
         newAlternate.AnchorTop = new AnchorData(AnchorType.PlatformNonHammered, newTile.Width, 0);
         newAlternate.DrawYOffset = -10;
         addAlternate(0);
         addTile(592);
         newTile.Width = 3;
         newTile.Height = 3;
         newTile.Origin = new Point16(1, 2);
         newTile.AnchorBottom = new AnchorData(AnchorType.SolidTile | AnchorType.SolidWithTop | AnchorType.Table | AnchorType.SolidSide, newTile.Width, 0);
         newTile.UsesCustomCanPlace = true;
         newTile.CoordinateHeights = new int[3] { 16, 16, 16 };
         newTile.CoordinateWidth = 16;
         newTile.CoordinatePadding = 2;
         addBaseTile(out Style3x3);
         newTile.CopyFrom(Style3x3);
         newTile.Height = 6;
         newTile.Origin = new Point16(1, 5);
         newTile.AnchorBottom = new AnchorData(AnchorType.SolidTile | AnchorType.SolidWithTop | AnchorType.SolidSide, newTile.Width, 0);
         newTile.CoordinateHeights = new int[6] { 16, 16, 16, 16, 16, 16 };
         newTile.DrawYOffset = 2;
         newTile.LavaDeath = true;
         newTile.StyleHorizontal = true;
         newSubTile.CopyFrom(newTile);
         newSubTile.LavaDeath = false;
         newSubTile.LavaPlacement = LiquidPlacement.Allowed;
         addSubTile(7);
         newSubTile.CopyFrom(newTile);
         newSubTile.LavaDeath = false;
         newSubTile.LavaPlacement = LiquidPlacement.Allowed;
         addSubTile(8);
         addTile(548);
         newTile.CopyFrom(Style3x3);
         newTile.Height = 5;
         newTile.Origin = new Point16(1, 4);
         newTile.AnchorBottom = new AnchorData(AnchorType.SolidTile | AnchorType.SolidWithTop | AnchorType.SolidSide, newTile.Width, 0);
         newTile.CoordinateHeights = new int[5] { 16, 16, 16, 16, 16 };
         newTile.DrawYOffset = 2;
         newTile.LavaDeath = false;
         newTile.LavaPlacement = LiquidPlacement.Allowed;
         newTile.StyleHorizontal = true;
         addTile(613);
         newTile.CopyFrom(Style3x3);
         newTile.Height = 6;
         newTile.Origin = new Point16(1, 5);
         newTile.AnchorBottom = new AnchorData(AnchorType.SolidTile | AnchorType.SolidWithTop | AnchorType.SolidSide, newTile.Width, 0);
         newTile.CoordinateHeights = new int[6] { 16, 16, 16, 16, 16, 16 };
         newTile.DrawYOffset = 2;
         newTile.LavaDeath = false;
         newTile.LavaPlacement = LiquidPlacement.Allowed;
         newTile.StyleHorizontal = true;
         addTile(614);
         newTile.CopyFrom(Style3x3);
         newTile.Origin = new Point16(1, 0);
         newTile.AnchorTop = new AnchorData(AnchorType.SolidTile | AnchorType.SolidSide, 1, 1);
         newTile.AnchorBottom = AnchorData.Empty;
         newTile.LavaDeath = true;
         newTile.StyleWrapLimit = 37;
         newTile.StyleHorizontal = false;
         newTile.StyleLineSkip = 2;
         newTile.DrawYOffset = -2;
         newSubTile.CopyFrom(newTile);
         newSubTile.LavaDeath = false;
         newSubTile.LavaPlacement = LiquidPlacement.Allowed;
         addSubTile(32, 48);
         newSubTile.CopyFrom(newTile);
         newSubTile.WaterDeath = false;
         newSubTile.WaterPlacement = LiquidPlacement.Allowed;
         addSubTile(46);
         addTile(34);
         newTile.CopyFrom(Style3x3);
         newTile.Width = 4;
         newTile.Origin = new Point16(2, 0);
         newTile.AnchorTop = new AnchorData(AnchorType.SolidTile | AnchorType.SolidSide, 1, 1);
         newTile.AnchorBottom = AnchorData.Empty;
         newTile.LavaDeath = true;
         newTile.DrawYOffset = -2;
         addTile(454);
         newTile.Width = 3;
         newTile.Height = 2;
         newTile.Origin = new Point16(1, 1);
         newTile.AnchorBottom = new AnchorData(AnchorType.SolidTile | AnchorType.SolidWithTop | AnchorType.SolidSide, newTile.Width, 0);
         newTile.UsesCustomCanPlace = true;
         newTile.CoordinateHeights = new int[2] { 16, 16 };
         newTile.CoordinateWidth = 16;
         newTile.CoordinatePadding = 2;
         newTile.StyleHorizontal = true;
         newTile.LavaDeath = true;
         addBaseTile(out Style3x2);
         newTile.CopyFrom(Style3x2);
         newTile.CoordinateHeights = new int[2] { 16, 18 };
         newSubTile.CopyFrom(Style3x2);
         newSubTile.LavaDeath = false;
         newSubTile.LavaPlacement = LiquidPlacement.Allowed;
         addSubTile(13);
         newSubTile.CopyFrom(Style3x2);
         newSubTile.Height = 1;
         newSubTile.Origin = new Point16(1, 0);
         newSubTile.CoordinateHeights = new int[1] { 16 };
         addSubTile(25);
         addTile(14);
         newTile.CopyFrom(Style3x2);
         newTile.CoordinateHeights = new int[2] { 16, 18 };
         newSubTile.CopyFrom(Style3x2);
         newSubTile.LavaDeath = false;
         newSubTile.LavaPlacement = LiquidPlacement.Allowed;
         addSubTile(11);
         addTile(469);
         newTile.CopyFrom(Style3x2);
         newTile.StyleWrapLimitVisualOverride = 37;
         newTile.HookCheckIfCanPlace = new PlacementHook(Chest.FindEmptyChest, -1, 0, processedCoordinates: true);
         newTile.HookPostPlaceMyPlayer = new PlacementHook(Chest.AfterPlacement_Hook, -1, 0, processedCoordinates: false);
         newTile.AnchorInvalidTiles = new int[5] { 127, 138, 664, 665, 484 };
         newTile.LavaDeath = false;
         newSubTile.CopyFrom(newTile);
         newSubTile.LavaDeath = false;
         newSubTile.LavaPlacement = LiquidPlacement.Allowed;
         addSubTile(9, 42);
         addTile(88);
         newTile.CopyFrom(Style3x2);
         newTile.LavaDeath = false;
         newTile.LavaPlacement = LiquidPlacement.Allowed;
         addTile(237);
         newTile.CopyFrom(Style3x2);
         newTile.DrawYOffset = 2;
         addTile(244);
         newTile.CopyFrom(Style3x2);
         newTile.DrawYOffset = 2;
         addTile(647);
         newTile.CopyFrom(Style3x2);
         newTile.DrawYOffset = 2;
         newTile.StyleWrapLimit = 35;
         addTile(648);
         newTile.CopyFrom(Style3x2);
         newTile.DrawYOffset = 2;
         addTile(651);
         newTile.CopyFrom(Style3x2);
         newTile.LavaDeath = false;
         newTile.CoordinateHeights = new int[2] { 16, 18 };
         addTile(26);
         newTile.CopyFrom(Style3x2);
         addTile(86);
         newTile.CopyFrom(Style3x2);
         newTile.DrawYOffset = 2;
         addTile(377);
         newTile.CopyFrom(Style3x2);
         newTile.StyleWrapLimitVisualOverride = 37;
         newSubTile.CopyFrom(newTile);
         newSubTile.LavaDeath = false;
         newSubTile.LavaPlacement = LiquidPlacement.Allowed;
         addSubTile(15, 42);
         addTile(87);
         newTile.CopyFrom(Style3x2);
         newTile.LavaDeath = false;
         newTile.CoordinateHeights = new int[2] { 16, 18 };
         addTile(486);
         newTile.CopyFrom(Style3x2);
         newTile.LavaDeath = false;
         addTile(488);
         newTile.CopyFrom(Style3x2);
         newTile.DrawYOffset = 2;
         newTile.StyleWrapLimitVisualOverride = 37;
         newSubTile.CopyFrom(newTile);
         newSubTile.LavaDeath = false;
         newSubTile.LavaPlacement = LiquidPlacement.Allowed;
         addSubTile(10, 46);
         addTile(89);
         newTile.CopyFrom(Style3x2);
         newTile.LavaDeath = false;
         addTile(114);
         newTile.CopyFrom(Style3x2);
         newTile.LavaDeath = false;
         newTile.DrawYOffset = 2;
         newSubTile.CopyFrom(newTile);
         newSubTile.AnchorValidTiles = new int[2] { 59, 70 };
         addSubTile(32, 33, 34);
         newSubTile.CopyFrom(newTile);
         newSubTile.AnchorValidTiles = new int[7] { 147, 161, 163, 200, 164, 162, 224 };
         addSubTile(26, 27, 28, 29, 30, 31);
         addTile(186);
         newTile.CopyFrom(Style3x2);
         newTile.StyleWrapLimit = 35;
         newTile.LavaDeath = false;
         newTile.DrawYOffset = 2;
         newSubTile.CopyFrom(newTile);
         newSubTile.AnchorValidTiles = new int[3] { 59, 60, 226 };
         addSubTile(0, 1, 2, 3, 4, 5);
         newSubTile.CopyFrom(newTile);
         newSubTile.AnchorValidTiles = new int[4] { 57, 58, 75, 76 };
         addSubTile(6, 7, 8);
         newSubTile.CopyFrom(newTile);
         newSubTile.AnchorValidTiles = new int[12]
         {
             53, 397, 396, 112, 398, 400, 234, 399, 401, 116,
             402, 403
         };
         addSubTile(29, 30, 31, 32, 33, 34);
         addTile(187);
         newTile.CopyFrom(Style3x2);
         newTile.AnchorValidTiles = new int[4] { 53, 112, 234, 116 };
         newTile.WaterDeath = true;
         newTile.LavaDeath = true;
         newTile.DrawYOffset = 2;
         newTile.WaterPlacement = LiquidPlacement.NotAllowed;
         newTile.LavaPlacement = LiquidPlacement.NotAllowed;
         newTile.RandomStyleRange = 4;
         addTile(552);
         newTile.CopyFrom(Style3x2);
         newTile.StyleWrapLimit = 16;
         newTile.WaterPlacement = LiquidPlacement.NotAllowed;
         newTile.LavaPlacement = LiquidPlacement.NotAllowed;
         newTile.WaterDeath = true;
         newTile.LavaDeath = true;
         newTile.DrawYOffset = 2;
         newSubTile.CopyFrom(newTile);
         newSubTile.WaterDeath = false;
         newSubTile.WaterPlacement = LiquidPlacement.Allowed;
         addSubTile(1);
         newSubTile.CopyFrom(newTile);
         newSubTile.WaterDeath = false;
         newSubTile.WaterPlacement = LiquidPlacement.Allowed;
         addSubTile(4);
         newSubTile.CopyFrom(newTile);
         newSubTile.WaterDeath = false;
         newSubTile.WaterPlacement = LiquidPlacement.Allowed;
         addSubTile(9);
         newSubTile.CopyFrom(newTile);
         newSubTile.WaterDeath = false;
         newSubTile.WaterPlacement = LiquidPlacement.Allowed;
         addSubTile(1 + newTile.StyleWrapLimit);
         newSubTile.CopyFrom(newTile);
         newSubTile.WaterDeath = false;
         newSubTile.WaterPlacement = LiquidPlacement.Allowed;
         addSubTile(4 + newTile.StyleWrapLimit);
         newSubTile.CopyFrom(newTile);
         newSubTile.WaterDeath = false;
         newSubTile.WaterPlacement = LiquidPlacement.Allowed;
         addSubTile(9 + newTile.StyleWrapLimit);
         addTile(215);
         newTile.CopyFrom(Style3x2);
         newTile.DrawYOffset = 2;
         addTile(217);
         newTile.CopyFrom(Style3x2);
         newTile.DrawYOffset = 2;
         addTile(218);
         newTile.CopyFrom(Style3x2);
         newTile.CoordinateHeights = new int[2] { 16, 18 };
         addTile(17);
         newTile.CopyFrom(Style3x2);
         newTile.CoordinateHeights = new int[2] { 16, 18 };
         newTile.LavaDeath = false;
         addTile(77);
         newTile.CopyFrom(Style3x2);
         newTile.CoordinateHeights = new int[2] { 16, 18 };
         newTile.DrawYOffset = 2;
         newTile.StyleHorizontal = true;
         newTile.LavaDeath = false;
         addTile(133);
         newTile.CopyFrom(Style3x2);
         addTile(405);
         newTile.Width = 3;
         newTile.Height = 1;
         newTile.Origin = new Point16(1, 0);
         newTile.AnchorBottom = new AnchorData(AnchorType.SolidTile | AnchorType.SolidWithTop | AnchorType.SolidSide, newTile.Width, 0);
         newTile.UsesCustomCanPlace = true;
         newTile.CoordinateHeights = new int[1] { 16 };
         newTile.CoordinateWidth = 16;
         newTile.CoordinatePadding = 2;
         addTile(235);
         newTile.Width = 3;
         newTile.Height = 4;
         newTile.Origin = new Point16(1, 3);
         newTile.AnchorBottom = new AnchorData(AnchorType.SolidTile | AnchorType.SolidWithTop | AnchorType.SolidSide, newTile.Width, 0);
         newTile.UsesCustomCanPlace = true;
         newTile.CoordinateHeights = new int[4] { 16, 16, 16, 16 };
         newTile.CoordinateWidth = 16;
         newTile.CoordinatePadding = 2;
         newTile.StyleHorizontal = true;
         newTile.LavaDeath = true;
         addBaseTile(out Style3x4);
         newTile.CopyFrom(Style3x4);
         newTile.StyleWrapLimitVisualOverride = 37;
         newSubTile.CopyFrom(newTile);
         newSubTile.LavaDeath = false;
         newSubTile.LavaPlacement = LiquidPlacement.Allowed;
         addSubTile(4, 43);
         addTile(101);
         newTile.CopyFrom(Style3x4);
         newTile.DrawYOffset = 2;
         addTile(102);
         newTile.CopyFrom(Style3x4);
         newTile.DrawYOffset = 2;
         addTile(463);
         newTile.CopyFrom(Style3x4);
         newTile.LavaDeath = false;
         newTile.DrawYOffset = 2;
         newTile.Direction = TileObjectDirection.PlaceLeft;
         newTile.HookPostPlaceMyPlayer = new PlacementHook(TEHatRack.Hook_AfterPlacement, -1, 0, processedCoordinates: false);
         newTile.AnchorInvalidTiles = new int[5] { 127, 138, 664, 665, 484 };
         newAlternate.CopyFrom(newTile);
         newAlternate.Direction = TileObjectDirection.PlaceRight;
         addAlternate(1);
         addTile(475);
         newTile.CopyFrom(Style3x4);
         newTile.LavaDeath = false;
         newTile.DrawYOffset = 2;
         newTile.HookCheckIfCanPlace = new PlacementHook(TETeleportationPylon.PlacementPreviewHook_CheckIfCanPlace, 1, 0, processedCoordinates: true);
         newTile.HookPostPlaceMyPlayer = new PlacementHook(TETeleportationPylon.PlacementPreviewHook_AfterPlacement, -1, 0, processedCoordinates: false);
         newTile.StyleHorizontal = true;
         addTile(597);
         newTile.CopyFrom(Style3x4);
         newTile.LavaDeath = false;
         newTile.DrawYOffset = 2;
         newTile.Direction = TileObjectDirection.PlaceLeft;
         newTile.StyleHorizontal = false;
         newTile.StyleWrapLimitVisualOverride = 2;
         newTile.StyleMultiplier = 2;
         newTile.StyleWrapLimit = 2;
         newTile.styleLineSkipVisualOverride = 0;
         newAlternate.CopyFrom(newTile);
         newAlternate.Direction = TileObjectDirection.PlaceRight;
         addAlternate(1);
         addTile(617);
         newTile.Width = 2;
         newTile.Height = 2;
         newTile.Origin = new Point16(0, 1);
         newTile.AnchorBottom = new AnchorData(AnchorType.SolidTile | AnchorType.SolidWithTop | AnchorType.Table | AnchorType.SolidSide, newTile.Width, 0);
         newTile.UsesCustomCanPlace = true;
         newTile.CoordinateHeights = new int[2] { 16, 16 };
         newTile.CoordinateWidth = 16;
         newTile.CoordinatePadding = 2;
         newTile.LavaDeath = true;
         addBaseTile(out Style2x2);
         newTile.CopyFrom(Style2x2);
         newTile.Origin = new Point16(0, 1);
         newTile.CoordinateHeights = new int[2] { 16, 18 };
         newTile.HookCheckIfCanPlace = new PlacementHook(Chest.FindEmptyChest, -1, 0, processedCoordinates: true);
         newTile.HookPostPlaceMyPlayer = new PlacementHook(Chest.AfterPlacement_Hook, -1, 0, processedCoordinates: false);
         newTile.AnchorInvalidTiles = new int[5] { 127, 138, 664, 665, 484 };
         newTile.StyleHorizontal = true;
         newTile.LavaDeath = false;
         newTile.AnchorBottom = new AnchorData(AnchorType.SolidTile | AnchorType.SolidWithTop | AnchorType.SolidSide, newTile.Width, 0);
         addTile(21);
         newTile.CopyFrom(Style2x2);
         newTile.Origin = new Point16(0, 1);
         newTile.CoordinateHeights = new int[2] { 16, 18 };
         newTile.HookCheckIfCanPlace = new PlacementHook(Chest.FindEmptyChest, -1, 0, processedCoordinates: true);
         newTile.HookPostPlaceMyPlayer = new PlacementHook(Chest.AfterPlacement_Hook, -1, 0, processedCoordinates: false);
         newTile.AnchorInvalidTiles = new int[5] { 127, 138, 664, 665, 484 };
         newTile.StyleHorizontal = true;
         newTile.LavaDeath = false;
         newTile.AnchorBottom = new AnchorData(AnchorType.SolidTile | AnchorType.SolidWithTop | AnchorType.SolidSide, newTile.Width, 0);
         addTile(467);
         newTile.CopyFrom(Style2x2);
         newTile.Origin = new Point16(0, 1);
         newTile.CoordinateHeights = new int[2] { 16, 18 };
         newTile.AnchorInvalidTiles = new int[5] { 127, 138, 664, 665, 484 };
         newTile.StyleHorizontal = true;
         newTile.LavaDeath = false;
         newTile.AnchorBottom = new AnchorData(AnchorType.SolidTile | AnchorType.SolidWithTop | AnchorType.SolidSide, newTile.Width, 0);
         addTile(441);
         newTile.CopyFrom(Style2x2);
         newTile.Origin = new Point16(0, 1);
         newTile.CoordinateHeights = new int[2] { 16, 18 };
         newTile.AnchorInvalidTiles = new int[5] { 127, 138, 664, 665, 484 };
         newTile.StyleHorizontal = true;
         newTile.LavaDeath = false;
         newTile.AnchorBottom = new AnchorData(AnchorType.SolidTile | AnchorType.SolidWithTop | AnchorType.SolidSide, newTile.Width, 0);
         addTile(468);
         newTile.CopyFrom(Style2x2);
         newTile.DrawYOffset = 2;
         newTile.AnchorBottom = new AnchorData(AnchorType.SolidTile, newTile.Width, 0);
         newTile.StyleWrapLimit = 6;
         newTile.StyleMultiplier = 6;
         newTile.RandomStyleRange = 6;
         newTile.AnchorValidTiles = new int[4] { 2, 477, 109, 492 };
         addTile(254);
         newTile.CopyFrom(Style2x2);
         newTile.AnchorBottom = new AnchorData(AnchorType.SolidTile | AnchorType.SolidWithTop | AnchorType.SolidSide, newTile.Width, 0);
         newTile.StyleHorizontal = true;
         addTile(96);
         newTile.CopyFrom(Style2x2);
         newTile.DrawYOffset = 2;
         newTile.AnchorBottom = new AnchorData(AnchorType.SolidTile, newTile.Width, 0);
         newTile.StyleWrapLimit = 4;
         newTile.StyleMultiplier = 1;
         newTile.RandomStyleRange = 4;
         newTile.StyleHorizontal = true;
         addTile(485);
         newTile.CopyFrom(Style2x2);
         newTile.Origin = new Point16(0, 1);
         newTile.DrawYOffset = 2;
         newTile.RandomStyleRange = 5;
         newTile.StyleHorizontal = true;
         addTile(457);
         newTile.CopyFrom(Style2x2);
         newTile.Origin = new Point16(0, 1);
         newTile.DrawYOffset = 2;
         newTile.StyleHorizontal = true;
         addTile(490);
         newTile.CopyFrom(Style2x2);
         newTile.Origin = new Point16(0, 1);
         newTile.LavaDeath = false;
         newTile.DrawYOffset = 2;
         newTile.StyleWrapLimitVisualOverride = 56;
         newTile.styleLineSkipVisualOverride = 2;
         addTile(139);
         newTile.CopyFrom(Style2x2);
         newTile.Origin = new Point16(0, 1);
         newTile.RandomStyleRange = 9;
         addTile(35);
         newTile.CopyFrom(Style2x2);
         newTile.DrawYOffset = 2;
         newTile.StyleHorizontal = true;
         addTile(652);
         int styleWrapLimit = 3;
         newTile.CopyFrom(Style2x2);
         newTile.DrawYOffset = 2;
         newTile.StyleHorizontal = true;
         newTile.StyleWrapLimit = styleWrapLimit;
         addTile(653);
         newTile.CopyFrom(Style2x2);
         newTile.Origin = new Point16(1, 0);
         newTile.AnchorTop = new AnchorData(AnchorType.SolidTile | AnchorType.SolidSide, 2, 0);
         newTile.AnchorBottom = AnchorData.Empty;
         newTile.DrawYOffset = -2;
         addTile(95);
         newTile.CopyFrom(Style2x2);
         newTile.Origin = new Point16(1, 0);
         newTile.AnchorTop = new AnchorData(AnchorType.SolidTile | AnchorType.SolidSide, 2, 0);
         newTile.AnchorBottom = AnchorData.Empty;
         newTile.DrawYOffset = -2;
         addTile(126);
         newTile.CopyFrom(Style2x2);
         newTile.Origin = new Point16(1, 0);
         newTile.AnchorTop = new AnchorData(AnchorType.SolidTile | AnchorType.SolidSide, 2, 0);
         newTile.AnchorBottom = AnchorData.Empty;
         newTile.DrawYOffset = -2;
         addTile(444);
         newTile.CopyFrom(Style2x2);
         newTile.WaterDeath = true;
         addTile(98);
         newTile.CopyFrom(Style2x2);
         newTile.CoordinateHeights = new int[2] { 16, 18 };
         newSubTile.CopyFrom(newTile);
         newSubTile.LavaDeath = false;
         newSubTile.LavaPlacement = LiquidPlacement.Allowed;
         addSubTile(13, 43);
         addTile(172);
         newTile.CopyFrom(Style2x2);
         addTile(94);
         newTile.CopyFrom(Style2x2);
         newTile.LavaDeath = false;
         addTile(411);
         newTile.CopyFrom(Style2x2);
         addTile(97);
         newTile.CopyFrom(Style2x2);
         newTile.LavaDeath = false;
         addTile(99);
         newTile.CopyFrom(Style2x2);
         newTile.DrawYOffset = 2;
         newSubTile.CopyFrom(newTile);
         newSubTile.LavaDeath = false;
         newSubTile.LavaPlacement = LiquidPlacement.Allowed;
         addSubTile(25, 42);
         newSubTile.CopyFrom(newTile);
         newSubTile.WaterDeath = false;
         newSubTile.WaterPlacement = LiquidPlacement.Allowed;
         addSubTile(40);
         addTile(100);
         newTile.CopyFrom(Style2x2);
         addTile(125);
         newTile.CopyFrom(Style2x2);
         newTile.DrawYOffset = 2;
         addTile(621);
         newTile.CopyFrom(Style2x2);
         newTile.DrawYOffset = 2;
         addTile(622);
         newTile.CopyFrom(Style2x2);
         addTile(173);
         newTile.CopyFrom(Style2x2);
         addTile(287);
         newTile.CopyFrom(Style2x2);
         addTile(319);
         newTile.CopyFrom(Style2x2);
         addTile(287);
         newTile.CopyFrom(Style2x2);
         newTile.CoordinateHeights = new int[2] { 16, 18 };
         newTile.StyleHorizontal = true;
         addTile(376);
         newTile.CopyFrom(Style2x2);
         newTile.CoordinateHeights = new int[2] { 16, 18 };
         newTile.LavaDeath = false;
         addTile(138);
         newTile.CopyFrom(Style2x2);
         newTile.CoordinateHeights = new int[2] { 16, 18 };
         newTile.LavaDeath = false;
         addTile(664);
         newTile.CopyFrom(Style2x2);
         newTile.CoordinateHeights = new int[2] { 16, 18 };
         newTile.DrawYOffset = 2;
         newTile.LavaDeath = true;
         addTile(654);
         newTile.CopyFrom(Style2x2);
         newTile.CoordinateHeights = new int[2] { 16, 16 };
         newTile.LavaDeath = true;
         addTile(484);
         newTile.CopyFrom(Style2x2);
         newTile.LavaDeath = false;
         newTile.DrawYOffset = 2;
         addTile(142);
         newTile.CopyFrom(Style2x2);
         newTile.LavaDeath = false;
         newTile.DrawYOffset = 2;
         addTile(143);
         newTile.CopyFrom(Style2x2);
         newTile.DrawYOffset = 2;
         addTile(282);
         newTile.CopyFrom(Style2x2);
         newTile.DrawYOffset = 2;
         addTile(543);
         newTile.CopyFrom(Style2x2);
         newTile.DrawYOffset = 2;
         addTile(598);
         newTile.CopyFrom(Style2x2);
         newTile.DrawYOffset = 2;
         addTile(568);
         newTile.CopyFrom(Style2x2);
         newTile.DrawYOffset = 2;
         addTile(569);
         newTile.CopyFrom(Style2x2);
         newTile.DrawYOffset = 2;
         addTile(570);
         newTile.CopyFrom(Style2x2);
         addTile(288);
         newTile.CopyFrom(Style2x2);
         addTile(289);
         newTile.CopyFrom(Style2x2);
         addTile(290);
         newTile.CopyFrom(Style2x2);
         addTile(291);
         newTile.CopyFrom(Style2x2);
         addTile(292);
         newTile.CopyFrom(Style2x2);
         addTile(293);
         newTile.CopyFrom(Style2x2);
         addTile(294);
         newTile.CopyFrom(Style2x2);
         addTile(295);
         newTile.CopyFrom(Style2x2);
         addTile(316);
         newTile.CopyFrom(Style2x2);
         addTile(317);
         newTile.CopyFrom(Style2x2);
         addTile(318);
         newTile.CopyFrom(Style2x2);
         addTile(360);
         newTile.CopyFrom(Style2x2);
         addTile(580);
         newTile.CopyFrom(Style2x2);
         addTile(620);
         newTile.CopyFrom(Style2x2);
         newTile.DrawYOffset = 2;
         addTile(565);
         newTile.CopyFrom(Style2x2);
         newTile.DrawYOffset = 2;
         addTile(521);
         newTile.CopyFrom(Style2x2);
         newTile.DrawYOffset = 2;
         addTile(522);
         newTile.CopyFrom(Style2x2);
         newTile.DrawYOffset = 2;
         addTile(523);
         newTile.CopyFrom(Style2x2);
         newTile.DrawYOffset = 2;
         addTile(524);
         newTile.CopyFrom(Style2x2);
         newTile.DrawYOffset = 2;
         addTile(525);
         newTile.CopyFrom(Style2x2);
         newTile.DrawYOffset = 2;
         addTile(526);
         newTile.CopyFrom(Style2x2);
         newTile.DrawYOffset = 2;
         addTile(527);
         newTile.CopyFrom(Style2x2);
         newTile.DrawYOffset = 2;
         addTile(505);
         newTile.CopyFrom(Style6x3);
         addTile(358);
         newTile.CopyFrom(Style6x3);
         addTile(359);
         newTile.CopyFrom(Style6x3);
         addTile(542);
         newTile.CopyFrom(StyleSmallCage);
         addTile(361);
         newTile.CopyFrom(StyleSmallCage);
         addTile(362);
         newTile.CopyFrom(StyleSmallCage);
         addTile(363);
         newTile.CopyFrom(StyleSmallCage);
         addTile(364);
         newTile.CopyFrom(StyleSmallCage);
         addTile(544);
         newTile.CopyFrom(StyleSmallCage);
         addTile(391);
         newTile.CopyFrom(StyleSmallCage);
         addTile(392);
         newTile.CopyFrom(StyleSmallCage);
         addTile(393);
         newTile.CopyFrom(StyleSmallCage);
         addTile(394);
         newTile.CopyFrom(Style2x2);
         addTile(287);
         newTile.CopyFrom(Style2x2);
         addTile(335);
         newTile.CopyFrom(Style2x2);
         newTile.DrawYOffset = 2;
         addTile(564);
         newTile.CopyFrom(Style2x2);
         newTile.DrawYOffset = 2;
         addTile(594);
         newTile.CopyFrom(Style3x3);
         newTile.DrawYOffset = 2;
         addTile(354);
         newTile.CopyFrom(Style3x3);
         newTile.DrawYOffset = 2;
         addTile(355);
         newTile.CopyFrom(Style3x3);
         newTile.DrawYOffset = 2;
         addTile(491);
         newTile.CopyFrom(Style2xX);
         addTile(356);
         newTile.CopyFrom(Style2xX);
         addTile(663);
         newTile.CopyFrom(Style2x2);
         newTile.StyleHorizontal = true;
         newTile.AnchorBottom = AnchorData.Empty;
         newTile.AnchorLeft = new AnchorData(AnchorType.SolidTile, 1, 1);
         newTile.AnchorRight = new AnchorData(AnchorType.SolidTile, 1, 1);
         newTile.Origin = new Point16(0, 1);
         addTile(386);
         newTile.CopyFrom(Style2x2);
         newTile.StyleHorizontal = true;
         newTile.LavaDeath = false;
         newTile.DrawYOffset = 2;
         newTile.CoordinateHeights = new int[2] { 16, 18 };
         newAlternate.CopyFrom(newTile);
         newAlternate.AnchorBottom = AnchorData.Empty;
         newAlternate.AnchorWall = true;
         addAlternate(2);
         addTile(132);
         newTile.CopyFrom(Style2x2);
         newTile.StyleHorizontal = true;
         newAlternate.CopyFrom(newTile);
         newAlternate.Origin = Point16.Zero;
         newAlternate.AnchorTop = new AnchorData(AnchorType.SolidTile | AnchorType.SolidSide, 2, 0);
         newAlternate.AnchorBottom = AnchorData.Empty;
         addAlternate(1);
         newAlternate.CopyFrom(newTile);
         newAlternate.Origin = new Point16(0, 0);
         newAlternate.AnchorLeft = new AnchorData(AnchorType.SolidTile | AnchorType.SolidSide, 2, 0);
         newAlternate.AnchorBottom = AnchorData.Empty;
         addAlternate(2);
         newAlternate.CopyFrom(newTile);
         newAlternate.Origin = new Point16(1, 0);
         newAlternate.AnchorRight = new AnchorData(AnchorType.SolidTile | AnchorType.SolidSide, 2, 0);
         newAlternate.AnchorBottom = AnchorData.Empty;
         addAlternate(3);
         newTile.Origin = new Point16(0, 1);
         newAlternate.CopyFrom(newTile);
         newAlternate.Origin = Point16.Zero;
         newAlternate.AnchorWall = true;
         newAlternate.AnchorBottom = AnchorData.Empty;
         addAlternate(4);
         addTile(55);
         newTile.CopyFrom(Style2x2);
         newTile.StyleHorizontal = true;
         newAlternate.CopyFrom(newTile);
         newAlternate.Origin = Point16.Zero;
         newAlternate.AnchorTop = new AnchorData(AnchorType.SolidTile | AnchorType.SolidSide, 2, 0);
         newAlternate.AnchorBottom = AnchorData.Empty;
         addAlternate(1);
         newAlternate.CopyFrom(newTile);
         newAlternate.Origin = new Point16(0, 0);
         newAlternate.AnchorLeft = new AnchorData(AnchorType.SolidTile | AnchorType.SolidSide, 2, 0);
         newAlternate.AnchorBottom = AnchorData.Empty;
         addAlternate(2);
         newAlternate.CopyFrom(newTile);
         newAlternate.Origin = new Point16(1, 0);
         newAlternate.AnchorRight = new AnchorData(AnchorType.SolidTile | AnchorType.SolidSide, 2, 0);
         newAlternate.AnchorBottom = AnchorData.Empty;
         addAlternate(3);
         newTile.Origin = new Point16(0, 1);
         newAlternate.CopyFrom(newTile);
         newAlternate.Origin = Point16.Zero;
         newAlternate.AnchorWall = true;
         newAlternate.AnchorBottom = AnchorData.Empty;
         addAlternate(4);
         addTile(573);
         newTile.CopyFrom(Style2x2);
         newTile.StyleHorizontal = true;
         newAlternate.CopyFrom(newTile);
         newAlternate.Origin = Point16.Zero;
         newAlternate.AnchorTop = new AnchorData(AnchorType.SolidTile | AnchorType.SolidSide, 2, 0);
         newAlternate.AnchorBottom = AnchorData.Empty;
         addAlternate(1);
         newAlternate.CopyFrom(newTile);
         newAlternate.Origin = new Point16(0, 0);
         newAlternate.AnchorLeft = new AnchorData(AnchorType.SolidTile | AnchorType.SolidSide, 2, 0);
         newAlternate.AnchorBottom = AnchorData.Empty;
         addAlternate(2);
         newAlternate.CopyFrom(newTile);
         newAlternate.Origin = new Point16(1, 0);
         newAlternate.AnchorRight = new AnchorData(AnchorType.SolidTile | AnchorType.SolidSide, 2, 0);
         newAlternate.AnchorBottom = AnchorData.Empty;
         addAlternate(3);
         newTile.Origin = new Point16(0, 1);
         newAlternate.CopyFrom(newTile);
         newAlternate.Origin = Point16.Zero;
         newAlternate.AnchorWall = true;
         newAlternate.AnchorBottom = AnchorData.Empty;
         addAlternate(4);
         addTile(425);
         newTile.CopyFrom(Style2x2);
         newTile.StyleHorizontal = true;
         newAlternate.CopyFrom(newTile);
         newAlternate.Origin = Point16.Zero;
         newAlternate.AnchorTop = new AnchorData(AnchorType.SolidTile | AnchorType.SolidSide, 2, 0);
         newAlternate.AnchorBottom = AnchorData.Empty;
         addAlternate(1);
         newAlternate.CopyFrom(newTile);
         newAlternate.Origin = new Point16(0, 0);
         newAlternate.AnchorLeft = new AnchorData(AnchorType.SolidTile | AnchorType.SolidSide, 2, 0);
         newAlternate.AnchorBottom = AnchorData.Empty;
         addAlternate(2);
         newAlternate.CopyFrom(newTile);
         newAlternate.Origin = new Point16(1, 0);
         newAlternate.AnchorRight = new AnchorData(AnchorType.SolidTile | AnchorType.SolidSide, 2, 0);
         newAlternate.AnchorBottom = AnchorData.Empty;
         addAlternate(3);
         newTile.Origin = new Point16(0, 1);
         newAlternate.CopyFrom(newTile);
         newAlternate.Origin = Point16.Zero;
         newAlternate.AnchorWall = true;
         newAlternate.AnchorBottom = AnchorData.Empty;
         addAlternate(4);
         addTile(510);
         newTile.CopyFrom(Style2x2);
         newTile.StyleHorizontal = true;
         newAlternate.CopyFrom(newTile);
         newAlternate.Origin = Point16.Zero;
         newAlternate.AnchorTop = new AnchorData(AnchorType.SolidTile | AnchorType.SolidSide, 2, 0);
         newAlternate.AnchorBottom = AnchorData.Empty;
         addAlternate(1);
         newAlternate.CopyFrom(newTile);
         newAlternate.Origin = new Point16(0, 0);
         newAlternate.AnchorLeft = new AnchorData(AnchorType.SolidTile | AnchorType.SolidSide, 2, 0);
         newAlternate.AnchorBottom = AnchorData.Empty;
         addAlternate(2);
         newAlternate.CopyFrom(newTile);
         newAlternate.Origin = new Point16(1, 0);
         newAlternate.AnchorRight = new AnchorData(AnchorType.SolidTile | AnchorType.SolidSide, 2, 0);
         newAlternate.AnchorBottom = AnchorData.Empty;
         addAlternate(3);
         newTile.Origin = new Point16(0, 1);
         newAlternate.CopyFrom(newTile);
         newAlternate.Origin = Point16.Zero;
         newAlternate.AnchorWall = true;
         newAlternate.AnchorBottom = AnchorData.Empty;
         addAlternate(4);
         addTile(511);
         newTile.CopyFrom(Style2x2);
         newTile.Origin = new Point16(0, 1);
         newTile.StyleHorizontal = true;
         newTile.DrawYOffset = 2;
         newTile.LavaDeath = false;
         addTile(85);
         newTile.CopyFrom(Style2x2);
         newTile.StyleHorizontal = true;
         newTile.HookPostPlaceMyPlayer = new PlacementHook(TEItemFrame.Hook_AfterPlacement, -1, 0, processedCoordinates: true);
         newAlternate.CopyFrom(newTile);
         newAlternate.Origin = Point16.Zero;
         newAlternate.AnchorTop = new AnchorData(AnchorType.SolidTile | AnchorType.SolidSide, 2, 0);
         newAlternate.AnchorBottom = AnchorData.Empty;
         addAlternate(1);
         newAlternate.CopyFrom(newTile);
         newAlternate.Origin = new Point16(0, 0);
         newAlternate.AnchorLeft = new AnchorData(AnchorType.SolidTile | AnchorType.SolidSide, 2, 0);
         newAlternate.AnchorBottom = AnchorData.Empty;
         addAlternate(2);
         newAlternate.CopyFrom(newTile);
         newAlternate.Origin = new Point16(1, 0);
         newAlternate.AnchorRight = new AnchorData(AnchorType.SolidTile | AnchorType.SolidSide, 2, 0);
         newAlternate.AnchorBottom = AnchorData.Empty;
         addAlternate(3);
         newTile.Origin = new Point16(0, 1);
         newAlternate.CopyFrom(newTile);
         newAlternate.Origin = Point16.Zero;
         newAlternate.AnchorWall = true;
         newAlternate.AnchorBottom = AnchorData.Empty;
         addAlternate(4);
         addTile(395);
         newTile.CopyFrom(Style2x2);
         addTile(12);
         newTile.CopyFrom(Style2x2);
         addTile(665);
         newTile.CopyFrom(Style2x2);
         addTile(639);
         newTile.Width = 3;
         newTile.Height = 3;
         newTile.Origin = new Point16(1, 2);
         newTile.AnchorBottom = new AnchorData(AnchorType.SolidTile | AnchorType.SolidWithTop | AnchorType.SolidSide, newTile.Width, 0);
         newTile.UsesCustomCanPlace = true;
         newTile.CoordinateHeights = new int[3] { 16, 16, 16 };
         newTile.CoordinateWidth = 16;
         newTile.CoordinatePadding = 2;
         newTile.LavaDeath = true;
         addBaseTile(out Style3x3);
         newTile.CopyFrom(Style3x3);
         addTile(106);
         newTile.CopyFrom(Style3x3);
         newTile.Direction = TileObjectDirection.PlaceLeft;
         newTile.StyleHorizontal = true;
         newAlternate.CopyFrom(newTile);
         newAlternate.Direction = TileObjectDirection.PlaceRight;
         addAlternate(1);
         addTile(212);
         newTile.CopyFrom(Style3x3);
         newTile.DrawYOffset = 2;
         addTile(219);
         newTile.CopyFrom(Style3x3);
         newTile.DrawYOffset = 2;
         addTile(642);
         newTile.CopyFrom(Style3x3);
         newTile.DrawYOffset = 2;
         addTile(220);
         newTile.CopyFrom(Style3x3);
         newTile.DrawYOffset = 2;
         addTile(228);
         newTile.CopyFrom(Style3x3);
         newTile.LavaDeath = false;
         newTile.DrawYOffset = 2;
         addTile(231);
         newTile.CopyFrom(Style3x3);
         newTile.DrawYOffset = 2;
         addTile(243);
         newTile.CopyFrom(Style3x3);
         newTile.DrawYOffset = 2;
         addTile(247);
         newTile.CopyFrom(Style3x3);
         newTile.DrawYOffset = 2;
         addTile(283);
         newTile.CopyFrom(Style3x3);
         newTile.DrawYOffset = 2;
         addTile(300);
         newTile.CopyFrom(Style3x3);
         newTile.DrawYOffset = 2;
         addTile(301);
         newTile.CopyFrom(Style3x3);
         newTile.DrawYOffset = 2;
         addTile(302);
         newTile.CopyFrom(Style3x3);
         newTile.DrawYOffset = 2;
         addTile(303);
         newTile.CopyFrom(Style3x3);
         newTile.DrawYOffset = 2;
         addTile(304);
         newTile.CopyFrom(Style3x3);
         newTile.DrawYOffset = 2;
         addTile(305);
         newTile.CopyFrom(Style3x3);
         newTile.DrawYOffset = 2;
         addTile(306);
         newTile.CopyFrom(Style3x3);
         newTile.DrawYOffset = 2;
         addTile(307);
         newTile.CopyFrom(Style3x3);
         newTile.DrawYOffset = 2;
         addTile(308);
         newTile.CopyFrom(Style3x3);
         addTile(406);
         newTile.CopyFrom(Style3x3);
         addTile(452);
         newTile.CopyFrom(Style3x3);
         newTile.DrawYOffset = 2;
         addTile(412);
         newTile.CopyFrom(Style3x3);
         newTile.DrawYOffset = 2;
         addTile(455);
         newTile.CopyFrom(Style3x3);
         newTile.DrawYOffset = 2;
         addTile(499);
         newTile.Width = 1;
         newTile.Height = 2;
         newTile.Origin = new Point16(0, 1);
         newTile.AnchorBottom = new AnchorData(AnchorType.SolidTile | AnchorType.SolidWithTop | AnchorType.SolidSide, newTile.Width, 0);
         newTile.UsesCustomCanPlace = true;
         newTile.CoordinateHeights = new int[2] { 16, 16 };
         newTile.CoordinateWidth = 16;
         newTile.CoordinatePadding = 2;
         newTile.LavaDeath = true;
         addBaseTile(out Style1x2);
         newTile.CopyFrom(Style1x2);
         newTile.CoordinateHeights = new int[2] { 16, 18 };
         newTile.Direction = TileObjectDirection.PlaceLeft;
         newTile.StyleWrapLimit = 2;
         newTile.StyleMultiplier = 2;
         newTile.CoordinatePaddingFix = new Point16(0, 2);
         newTile.StyleHorizontal = true;
         newAlternate.CopyFrom(newTile);
         newAlternate.Direction = TileObjectDirection.PlaceRight;
         addAlternate(1);
         newSubTile.CopyFrom(newTile);
         newSubTile.LinkedAlternates = true;
         newSubTile.LavaDeath = false;
         newSubTile.LavaPlacement = LiquidPlacement.Allowed;
         addSubTile(16, 47);
         addTile(15);
         newTile.CopyFrom(Style1x2);
         newTile.CoordinateHeights = new int[2] { 16, 18 };
         newTile.Direction = TileObjectDirection.PlaceLeft;
         newTile.StyleWrapLimit = 2;
         newTile.StyleMultiplier = 2;
         newTile.CoordinatePaddingFix = new Point16(0, 2);
         newTile.StyleHorizontal = true;
         newAlternate.CopyFrom(newTile);
         newAlternate.Direction = TileObjectDirection.PlaceRight;
         addAlternate(1);
         newSubTile.CopyFrom(newTile);
         newSubTile.LinkedAlternates = true;
         newSubTile.LavaDeath = false;
         newSubTile.LavaPlacement = LiquidPlacement.Allowed;
         addSubTile(14, 42);
         addTile(497);
         newTile.CopyFrom(Style1x2);
         newTile.CoordinateHeights = new int[2] { 16, 20 };
         addTile(216);
         newTile.CopyFrom(Style1x2);
         newTile.AnchorBottom = new AnchorData(AnchorType.SolidTile | AnchorType.SolidWithTop | AnchorType.Table | AnchorType.SolidSide, newTile.Width, 0);
         addTile(390);
         newTile.CopyFrom(Style1x2);
         addTile(338);
         newTile.CopyFrom(Style1x2);
         newTile.StyleHorizontal = true;
         newTile.StyleWrapLimit = 6;
         newTile.DrawStyleOffset = 13 * newTile.StyleWrapLimit;
         addTile(493);
         newTile.CopyFrom(Style1x2);
         newTile.RandomStyleRange = 5;
         newTile.CoordinateHeights = new int[2] { 18, 18 };
         newTile.CoordinateWidth = 26;
         newTile.CoordinatePadding = 2;
         newTile.StyleHorizontal = true;
         newTile.DrawFlipHorizontal = true;
         addTile(567);
         newTile.Width = 1;
         newTile.Height = 1;
         newTile.Origin = new Point16(0, 0);
         newTile.AnchorBottom = new AnchorData(AnchorType.SolidTile | AnchorType.SolidWithTop | AnchorType.SolidSide, newTile.Width, 0);
         newTile.UsesCustomCanPlace = true;
         newTile.CoordinateHeights = new int[1] { 16 };
         newTile.CoordinateWidth = 16;
         newTile.CoordinatePadding = 2;
         newTile.LavaDeath = true;
         addBaseTile(out Style1x1);
         newTile.CopyFrom(Style1x1);
         newTile.AnchorBottom = new AnchorData(AnchorType.None, 0, 0);
         newTile.LavaDeath = false;
         addTile(420);
         newTile.CopyFrom(Style1x1);
         addTile(624);
         newTile.CopyFrom(Style1x1);
         addTile(656);
         newTile.CopyFrom(Style1x1);
         newTile.AnchorBottom = new AnchorData(AnchorType.SolidTile | AnchorType.SolidWithTop | AnchorType.Table, newTile.Width, 0);
         newTile.CoordinateHeights = new int[1] { 18 };
         newTile.CoordinateWidth = 20;
         newTile.LavaDeath = false;
         addTile(476);
         newTile.CopyFrom(Style1x1);
         newTile.LavaDeath = false;
         newTile.AnchorBottom = new AnchorData(AnchorType.AlternateTile, newTile.Width, 0);
         newTile.AnchorAlternateTiles = new int[2] { 420, 419 };
         newTile.StyleHorizontal = true;
         newAlternate.CopyFrom(newTile);
         newAlternate.Origin = new Point16(0, 1);
         newAlternate.AnchorAlternateTiles = new int[1] { 419 };
         addTile(419);
         newTile.CopyFrom(Style1x1);
         newTile.AnchorBottom = new AnchorData(AnchorType.None, 0, 0);
         newTile.LavaDeath = false;
         newTile.HookPostPlaceMyPlayer = new PlacementHook(TELogicSensor.Hook_AfterPlacement, -1, 0, processedCoordinates: true);
         addTile(423);
         newTile.CopyFrom(Style1x1);
         newTile.AnchorBottom = new AnchorData(AnchorType.None, 0, 0);
         newTile.LavaDeath = false;
         addTile(424);
         newTile.CopyFrom(Style1x1);
         newTile.AnchorBottom = new AnchorData(AnchorType.None, 0, 0);
         newTile.LavaDeath = false;
         addTile(445);
         newTile.CopyFrom(Style1x1);
         newTile.AnchorBottom = new AnchorData(AnchorType.None, 0, 0);
         newTile.LavaDeath = false;
         addTile(429);
         newTile.CopyFrom(Style1x1);
         newTile.AnchorTop = new AnchorData(AnchorType.EmptyTile, newTile.Width, 0);
         newTile.AnchorBottom = new AnchorData(AnchorType.SolidTile | AnchorType.SolidWithTop | AnchorType.SolidSide, newTile.Width, 0);
         newTile.UsesCustomCanPlace = true;
         newTile.DrawFlipHorizontal = true;
         newTile.CoordinateHeights = new int[1] { 26 };
         newTile.CoordinateWidth = 24;
         newTile.DrawYOffset = -8;
         newTile.RandomStyleRange = 6;
         newTile.StyleHorizontal = true;
         addTile(81);
         newTile.CopyFrom(Style1x1);
         newTile.CoordinateHeights = new int[1] { 18 };
         newTile.CoordinatePadding = 0;
         newTile.DrawYOffset = 2;
         newTile.LavaDeath = false;
         addTile(135);
         newTile.CopyFrom(Style1x1);
         newTile.CoordinateHeights = new int[1] { 18 };
         newTile.CoordinatePadding = 0;
         newTile.DrawYOffset = 2;
         newTile.LavaDeath = false;
         addTile(428);
         newTile.CopyFrom(Style1x1);
         newTile.RandomStyleRange = 2;
         newTile.LavaDeath = false;
         addTile(141);
         newTile.CopyFrom(Style1x1);
         newTile.StyleHorizontal = true;
         newTile.LavaDeath = false;
         addTile(144);
         newTile.CopyFrom(Style1x1);
         newTile.DrawYOffset = 2;
         addTile(210);
         newTile.CopyFrom(Style1x1);
         newTile.StyleHorizontal = true;
         newTile.LavaDeath = false;
         addTile(239);
         newTile.CopyFrom(Style1x1);
         newTile.DrawYOffset = 2;
         newTile.StyleHorizontal = true;
         addTile(650);
         newTile.CopyFrom(Style1x1);
         newTile.StyleHorizontal = true;
         newTile.RandomStyleRange = 7;
         addTile(36);
         newTile.CopyFrom(Style1x1);
         newTile.UsesCustomCanPlace = true;
         newTile.DrawFlipHorizontal = true;
         newTile.RandomStyleRange = 3;
         newTile.StyleMultiplier = 3;
         newTile.StyleWrapLimit = 3;
         newTile.StyleHorizontal = true;
         newTile.CoordinateHeights = new int[1] { 20 };
         newTile.CoordinateWidth = 20;
         newTile.DrawYOffset = -2;
         newTile.AnchorBottom = new AnchorData(AnchorType.SolidTile | AnchorType.SolidWithTop | AnchorType.Table | AnchorType.SolidSide, newTile.Width, 0);
         addTile(324);
         newTile.CopyFrom(Style1x1);
         newTile.CoordinateHeights = new int[1] { 16 };
         newTile.CoordinateWidth = 16;
         newTile.DrawYOffset = 2;
         newTile.AnchorBottom = new AnchorData(AnchorType.SolidTile | AnchorType.SolidWithTop | AnchorType.Table | AnchorType.SolidSide, newTile.Width, 0);
         addTile(593);
         newTile.CopyFrom(Style1x1);
         newTile.AnchorBottom = new AnchorData(AnchorType.SolidTile | AnchorType.SolidWithTop | AnchorType.SolidSide | AnchorType.AlternateTile, newTile.Width, 0);
         newTile.AnchorAlternateTiles = new int[7] { 124, 561, 574, 575, 576, 577, 578 };
         newTile.StyleHorizontal = true;
         newAlternate.CopyFrom(newTile);
         newAlternate.AnchorBottom = AnchorData.Empty;
         newAlternate.AnchorTop = new AnchorData(AnchorType.SolidTile | AnchorType.SolidSide | AnchorType.AlternateTile | AnchorType.SolidBottom, newTile.Width, 0);
         addAlternate(1);
         newAlternate.CopyFrom(newTile);
         newAlternate.AnchorBottom = AnchorData.Empty;
         newAlternate.AnchorRight = new AnchorData(AnchorType.SolidTile | AnchorType.SolidSide | AnchorType.Tree | AnchorType.AlternateTile, newTile.Height, 0);
         addAlternate(2);
         newAlternate.CopyFrom(newTile);
         newAlternate.AnchorBottom = AnchorData.Empty;
         newAlternate.AnchorLeft = new AnchorData(AnchorType.SolidTile | AnchorType.SolidSide | AnchorType.Tree | AnchorType.AlternateTile, newTile.Height, 0);
         addAlternate(3);
         newAlternate.CopyFrom(newTile);
         newAlternate.AnchorBottom = AnchorData.Empty;
         newAlternate.AnchorWall = true;
         addAlternate(4);
         addTile(630);
         newTile.CopyFrom(Style1x1);
         newTile.AnchorBottom = new AnchorData(AnchorType.SolidTile | AnchorType.SolidWithTop | AnchorType.SolidSide | AnchorType.AlternateTile, newTile.Width, 0);
         newTile.AnchorAlternateTiles = new int[7] { 124, 561, 574, 575, 576, 577, 578 };
         newTile.StyleHorizontal = true;
         newAlternate.CopyFrom(newTile);
         newAlternate.AnchorBottom = AnchorData.Empty;
         newAlternate.AnchorTop = new AnchorData(AnchorType.SolidTile | AnchorType.SolidSide | AnchorType.AlternateTile | AnchorType.SolidBottom, newTile.Width, 0);
         addAlternate(1);
         newAlternate.CopyFrom(newTile);
         newAlternate.AnchorBottom = AnchorData.Empty;
         newAlternate.AnchorRight = new AnchorData(AnchorType.SolidTile | AnchorType.SolidSide | AnchorType.Tree | AnchorType.AlternateTile, newTile.Height, 0);
         addAlternate(2);
         newAlternate.CopyFrom(newTile);
         newAlternate.AnchorBottom = AnchorData.Empty;
         newAlternate.AnchorLeft = new AnchorData(AnchorType.SolidTile | AnchorType.SolidSide | AnchorType.Tree | AnchorType.AlternateTile, newTile.Height, 0);
         addAlternate(3);
         newAlternate.CopyFrom(newTile);
         newAlternate.AnchorBottom = AnchorData.Empty;
         newAlternate.AnchorWall = true;
         addAlternate(4);
         addTile(631);
         newTile.Width = 1;
         newTile.Height = 1;
         newTile.Origin = new Point16(0, 0);
         newTile.UsesCustomCanPlace = true;
         newTile.CoordinateHeights = new int[1] { 16 };
         newTile.CoordinateWidth = 16;
         newTile.CoordinatePadding = 2;
         newTile.StyleHorizontal = true;
         newTile.FlattenAnchors = true;
         addBaseTile(out StyleSwitch);
         newTile.CopyFrom(StyleSwitch);
         newTile.AnchorBottom = new AnchorData(AnchorType.SolidTile | AnchorType.SolidSide, newTile.Width, 0);
         newAlternate.CopyFrom(StyleSwitch);
         newAlternate.AnchorLeft = new AnchorData(AnchorType.SolidTile | AnchorType.SolidSide | AnchorType.Tree | AnchorType.AlternateTile, newTile.Height, 0);
         newAlternate.AnchorAlternateTiles = new int[7] { 124, 561, 574, 575, 576, 577, 578 };
         newAlternate.DrawXOffset = -2;
         addAlternate(1);
         newAlternate.CopyFrom(StyleSwitch);
         newAlternate.AnchorRight = new AnchorData(AnchorType.SolidTile | AnchorType.SolidSide | AnchorType.Tree | AnchorType.AlternateTile, newTile.Height, 0);
         newAlternate.AnchorAlternateTiles = new int[7] { 124, 561, 574, 575, 576, 577, 578 };
         newAlternate.DrawXOffset = 2;
         addAlternate(2);
         newAlternate.CopyFrom(StyleSwitch);
         newAlternate.AnchorWall = true;
         addAlternate(3);
         newTile.DrawYOffset = 2;
         addTile(136);
         newTile.Width = 1;
         newTile.Height = 1;
         newTile.Origin = new Point16(0, 0);
         newTile.FlattenAnchors = true;
         newTile.UsesCustomCanPlace = false;
         newTile.CoordinateHeights = new int[1] { 20 };
         newTile.DrawStepDown = 2;
         newTile.CoordinateWidth = 20;
         newTile.CoordinatePadding = 2;
         newTile.StyleMultiplier = 6;
         newTile.StyleWrapLimit = 6;
         newTile.StyleHorizontal = true;
         newTile.WaterPlacement = LiquidPlacement.NotAllowed;
         newTile.LavaPlacement = LiquidPlacement.NotAllowed;
         newTile.WaterDeath = true;
         newTile.LavaDeath = true;
         addBaseTile(out StyleTorch);
         newTile.CopyFrom(StyleTorch);
         newTile.AnchorBottom = new AnchorData(AnchorType.SolidTile | AnchorType.SolidSide, newTile.Width, 0);
         newAlternate.CopyFrom(StyleTorch);
         newAlternate.AnchorLeft = new AnchorData(AnchorType.SolidTile | AnchorType.SolidSide | AnchorType.Tree | AnchorType.AlternateTile, newTile.Height, 0);
         newAlternate.AnchorAlternateTiles = new int[7] { 124, 561, 574, 575, 576, 577, 578 };
         addAlternate(1);
         newAlternate.CopyFrom(StyleTorch);
         newAlternate.AnchorRight = new AnchorData(AnchorType.SolidTile | AnchorType.SolidSide | AnchorType.Tree | AnchorType.AlternateTile, newTile.Height, 0);
         newAlternate.AnchorAlternateTiles = new int[7] { 124, 561, 574, 575, 576, 577, 578 };
         addAlternate(2);
         newAlternate.CopyFrom(StyleTorch);
         newAlternate.AnchorWall = true;
         addAlternate(0);
         newSubTile.CopyFrom(newTile);
         newSubTile.LinkedAlternates = true;
         newSubTile.WaterDeath = false;
         newSubTile.LavaDeath = false;
         newSubTile.WaterPlacement = LiquidPlacement.Allowed;
         newSubTile.LavaPlacement = LiquidPlacement.Allowed;
         addSubTile(8);
         newSubTile.CopyFrom(newTile);
         newSubTile.LinkedAlternates = true;
         newSubTile.WaterDeath = false;
         newSubTile.LavaDeath = false;
         newSubTile.WaterPlacement = LiquidPlacement.Allowed;
         newSubTile.LavaPlacement = LiquidPlacement.Allowed;
         addSubTile(11);
         newSubTile.CopyFrom(newTile);
         newSubTile.LinkedAlternates = true;
         newSubTile.WaterDeath = false;
         newSubTile.LavaDeath = false;
         newSubTile.WaterPlacement = LiquidPlacement.Allowed;
         newSubTile.LavaPlacement = LiquidPlacement.Allowed;
         addSubTile(17);
         addTile(4);
         newTile.Width = 1;
         newTile.Height = 1;
         newTile.Origin = new Point16(0, 0);
         newTile.FlattenAnchors = true;
         newTile.UsesCustomCanPlace = true;
         newTile.CoordinateHeights = new int[1] { 20 };
         newTile.DrawStepDown = 2;
         newTile.CoordinateWidth = 20;
         newTile.CoordinatePadding = 2;
         newTile.StyleHorizontal = true;
         newTile.WaterDeath = false;
         newTile.LavaDeath = false;
         newTile.StyleWrapLimit = 4;
         newTile.StyleMultiplier = 4;
         newTile.HookCheckIfCanPlace = new PlacementHook(WorldGen.CanPlaceProjectilePressurePad, -1, 0, processedCoordinates: true);
         newAlternate.CopyFrom(newTile);
         newAlternate.AnchorTop = new AnchorData(AnchorType.SolidTile | AnchorType.SolidWithTop | AnchorType.Table | AnchorType.SolidSide | AnchorType.Tree | AnchorType.AlternateTile | AnchorType.EmptyTile | AnchorType.SolidBottom, newTile.Width, 0);
         newAlternate.DrawStepDown = 0;
         newAlternate.DrawYOffset = -4;
         addAlternate(1);
         newAlternate.CopyFrom(newTile);
         newAlternate.AnchorLeft = new AnchorData(AnchorType.SolidTile | AnchorType.SolidWithTop | AnchorType.Table | AnchorType.SolidSide | AnchorType.Tree | AnchorType.AlternateTile | AnchorType.EmptyTile | AnchorType.SolidBottom, newTile.Height, 0);
         newAlternate.AnchorAlternateTiles = new int[7] { 124, 561, 574, 575, 576, 577, 578 };
         newAlternate.DrawXOffset = -2;
         newAlternate.DrawYOffset = -2;
         addAlternate(2);
         newAlternate.CopyFrom(newTile);
         newAlternate.AnchorRight = new AnchorData(AnchorType.SolidTile | AnchorType.SolidWithTop | AnchorType.Table | AnchorType.SolidSide | AnchorType.Tree | AnchorType.AlternateTile | AnchorType.EmptyTile | AnchorType.SolidBottom, newTile.Height, 0);
         newAlternate.AnchorAlternateTiles = new int[7] { 124, 561, 574, 575, 576, 577, 578 };
         newAlternate.DrawXOffset = 2;
         newAlternate.DrawYOffset = -2;
         addAlternate(3);
         newTile.AnchorBottom = new AnchorData(AnchorType.SolidTile | AnchorType.SolidWithTop | AnchorType.Table | AnchorType.SolidSide | AnchorType.Tree | AnchorType.AlternateTile | AnchorType.EmptyTile | AnchorType.SolidBottom, newTile.Width, 0);
         addTile(442);
         newTile.Width = 1;
         newTile.Height = 1;
         newTile.Origin = Point16.Zero;
         newTile.UsesCustomCanPlace = true;
         newTile.CoordinateHeights = new int[1] { 20 };
         newTile.CoordinateWidth = 16;
         newTile.CoordinatePadding = 2;
         newTile.DrawYOffset = -1;
         newTile.StyleHorizontal = true;
         newTile.AnchorBottom = new AnchorData(AnchorType.SolidTile | AnchorType.AlternateTile, newTile.Width, 0);
         newTile.WaterPlacement = LiquidPlacement.NotAllowed;
         newTile.LavaDeath = true;
         newTile.LavaPlacement = LiquidPlacement.NotAllowed;
         addBaseTile(out StyleAlch);
         newTile.CopyFrom(StyleAlch);
         newTile.AnchorValidTiles = new int[4] { 2, 477, 109, 492 };
         newTile.AnchorAlternateTiles = new int[1] { 78 };
         newSubTile.CopyFrom(StyleAlch);
         newSubTile.AnchorValidTiles = new int[1] { 60 };
         newSubTile.AnchorAlternateTiles = new int[1] { 78 };
         addSubTile(1);
         newSubTile.CopyFrom(StyleAlch);
         newSubTile.AnchorValidTiles = new int[2] { 0, 59 };
         newSubTile.AnchorAlternateTiles = new int[1] { 78 };
         addSubTile(2);
         newSubTile.CopyFrom(StyleAlch);
         newSubTile.AnchorValidTiles = new int[4] { 199, 203, 25, 23 };
         newSubTile.AnchorAlternateTiles = new int[1] { 78 };
         addSubTile(3);
         newSubTile.CopyFrom(StyleAlch);
         newSubTile.AnchorValidTiles = new int[2] { 53, 116 };
         newSubTile.AnchorAlternateTiles = new int[1] { 78 };
         newSubTile.WaterPlacement = LiquidPlacement.Allowed;
         addSubTile(4);
         newSubTile.CopyFrom(StyleAlch);
         newSubTile.AnchorValidTiles = new int[2] { 57, 633 };
         newSubTile.AnchorAlternateTiles = new int[1] { 78 };
         newSubTile.LavaPlacement = LiquidPlacement.Allowed;
         newSubTile.LavaDeath = false;
         addSubTile(5);
         newSubTile.CopyFrom(StyleAlch);
         newSubTile.AnchorValidTiles = new int[5] { 147, 161, 163, 164, 200 };
         newSubTile.AnchorAlternateTiles = new int[1] { 78 };
         newSubTile.WaterPlacement = LiquidPlacement.Allowed;
         addSubTile(6);
         addTile(82);
         newTile.FullCopyFrom(82);
         addTile(83);
         newTile.FullCopyFrom(83);
         addTile(84);
         newTile.Width = 3;
         newTile.Height = 3;
         newTile.Origin = new Point16(1, 1);
         newTile.AnchorWall = true;
         newTile.UsesCustomCanPlace = true;
         newTile.CoordinateHeights = new int[3] { 16, 16, 16 };
         newTile.CoordinateWidth = 16;
         newTile.CoordinatePadding = 2;
         newTile.LavaDeath = true;
         addBaseTile(out Style3x3Wall);
         newTile.CopyFrom(Style3x3Wall);
         newTile.StyleHorizontal = true;
         newTile.StyleWrapLimit = 36;
         addTile(240);
         newTile.CopyFrom(Style3x3Wall);
         newTile.StyleHorizontal = true;
         newTile.StyleWrapLimit = 36;
         addTile(440);
         newTile.CopyFrom(Style3x3Wall);
         newTile.Direction = TileObjectDirection.PlaceLeft;
         newTile.StyleHorizontal = true;
         newTile.LavaDeath = false;
         newAlternate.CopyFrom(newTile);
         newAlternate.Direction = TileObjectDirection.PlaceRight;
         addAlternate(1);
         addTile(334);
         newTile.CopyFrom(Style3x3Wall);
         newTile.Direction = TileObjectDirection.PlaceLeft;
         newTile.StyleHorizontal = true;
         newTile.LavaDeath = false;
         newTile.HookPostPlaceMyPlayer = new PlacementHook(TEWeaponsRack.Hook_AfterPlacement, -1, 0, processedCoordinates: true);
         newAlternate.CopyFrom(newTile);
         newAlternate.Direction = TileObjectDirection.PlaceRight;
         addAlternate(1);
         addTile(471);
         newTile.CopyFrom(Style3x3Wall);
         newTile.Width = 2;
         newTile.Height = 3;
         newTile.Origin = new Point16(0, 1);
         newTile.StyleHorizontal = true;
         newSubTile.CopyFrom(newTile);
         newSubTile.RandomStyleRange = 4;
         addSubTile(15);
         addTile(245);
         newTile.CopyFrom(Style3x3Wall);
         newTile.Width = 3;
         newTile.Height = 2;
         newTile.Origin = new Point16(1, 0);
         newTile.CoordinateHeights = new int[2] { 16, 16 };
         addTile(246);
         newTile.CopyFrom(Style3x3Wall);
         newTile.Width = 4;
         newTile.Height = 3;
         newTile.Origin = new Point16(1, 1);
         newTile.RandomStyleRange = 9;
         addTile(241);
         newTile.CopyFrom(Style3x3Wall);
         newTile.Width = 6;
         newTile.Height = 4;
         newTile.Origin = new Point16(2, 2);
         newTile.CoordinateHeights = new int[4] { 16, 16, 16, 16 };
         newTile.StyleWrapLimit = 27;
         addTile(242);
         newTile.Width = 2;
         newTile.Height = 4;
         newTile.Origin = new Point16(0, 3);
         newTile.AnchorBottom = new AnchorData(AnchorType.SolidTile, newTile.Width, 0);
         newTile.UsesCustomCanPlace = true;
         newTile.CoordinateHeights = new int[4] { 16, 16, 16, 18 };
         newTile.CoordinateWidth = 16;
         newTile.CoordinatePadding = 2;
         newTile.AnchorValidTiles = new int[6] { 2, 477, 109, 60, 492, 633 };
         newTile.StyleHorizontal = true;
         newTile.RandomStyleRange = 3;
         newTile.LavaDeath = true;
         newTile.WaterPlacement = LiquidPlacement.NotAllowed;
         addTile(27);
         newTile.Width = 1;
         newTile.Height = 2;
         newTile.Origin = new Point16(0, 1);
         newTile.AnchorBottom = new AnchorData(AnchorType.SolidTile, newTile.Width, 0);
         newTile.UsesCustomCanPlace = true;
         newTile.CoordinateHeights = new int[2] { 16, 18 };
         newTile.CoordinateWidth = 16;
         newTile.CoordinatePadding = 2;
         newTile.AnchorValidTiles = new int[2] { 2, 477 };
         newTile.StyleHorizontal = true;
         newTile.DrawFlipHorizontal = true;
         newTile.WaterPlacement = LiquidPlacement.NotAllowed;
         newTile.LavaDeath = true;
         newTile.RandomStyleRange = 3;
         newAlternate.CopyFrom(newTile);
         newAlternate.AnchorValidTiles = new int[1] { 147 };
         addAlternate(3);
         newAlternate.CopyFrom(newTile);
         newAlternate.AnchorValidTiles = new int[1] { 60 };
         addAlternate(6);
         newAlternate.CopyFrom(newTile);
         newAlternate.AnchorValidTiles = new int[2] { 23, 661 };
         addAlternate(9);
         newAlternate.CopyFrom(newTile);
         newAlternate.AnchorValidTiles = new int[2] { 199, 662 };
         addAlternate(12);
         newAlternate.CopyFrom(newTile);
         newAlternate.AnchorValidTiles = new int[2] { 109, 492 };
         addAlternate(15);
         newAlternate.CopyFrom(newTile);
         newAlternate.AnchorValidTiles = new int[1] { 53 };
         addAlternate(18);
         newAlternate.CopyFrom(newTile);
         newAlternate.AnchorValidTiles = new int[1] { 116 };
         addAlternate(21);
         newAlternate.CopyFrom(newTile);
         newAlternate.AnchorValidTiles = new int[1] { 234 };
         addAlternate(24);
         newAlternate.CopyFrom(newTile);
         newAlternate.AnchorValidTiles = new int[1] { 112 };
         addAlternate(27);
         newAlternate.CopyFrom(newTile);
         newAlternate.AnchorValidTiles = new int[1] { 633 };
         addAlternate(30);
         addTile(20);
         newTile.Width = 1;
         newTile.Height = 2;
         newTile.Origin = new Point16(0, 1);
         newTile.AnchorBottom = new AnchorData(AnchorType.SolidTile, newTile.Width, 0);
         newTile.UsesCustomCanPlace = true;
         newTile.CoordinateHeights = new int[2] { 16, 18 };
         newTile.CoordinateWidth = 16;
         newTile.CoordinatePadding = 2;
         newTile.AnchorValidTiles = new int[15]
         {
             1, 25, 117, 203, 182, 180, 179, 381, 183, 181,
             534, 536, 539, 625, 627
         };
         newTile.StyleHorizontal = true;
         newTile.DrawFlipHorizontal = true;
         newTile.WaterPlacement = LiquidPlacement.NotAllowed;
         newTile.LavaDeath = false;
         newTile.RandomStyleRange = 3;
         newTile.StyleMultiplier = 3;
         newTile.StyleHorizontal = true;
         addTile(590);
         newTile.Width = 1;
         newTile.Height = 2;
         newTile.Origin = new Point16(0, 1);
         newTile.AnchorBottom = new AnchorData(AnchorType.SolidTile, newTile.Width, 0);
         newTile.UsesCustomCanPlace = true;
         newTile.CoordinateHeights = new int[2] { 16, 18 };
         newTile.CoordinateWidth = 16;
         newTile.CoordinatePadding = 2;
         newTile.AnchorValidTiles = new int[7] { 2, 477, 492, 60, 109, 199, 23 };
         newTile.StyleHorizontal = true;
         newTile.DrawFlipHorizontal = true;
         newTile.WaterPlacement = LiquidPlacement.NotAllowed;
         newTile.LavaDeath = false;
         newTile.RandomStyleRange = 3;
         newTile.StyleMultiplier = 3;
         newTile.StyleHorizontal = true;
         addTile(595);
         newTile.Width = 1;
         newTile.Height = 2;
         newTile.Origin = new Point16(0, 1);
         newTile.AnchorBottom = new AnchorData(AnchorType.SolidTile, newTile.Width, 0);
         newTile.UsesCustomCanPlace = true;
         newTile.CoordinateHeights = new int[2] { 16, 18 };
         newTile.CoordinateWidth = 16;
         newTile.CoordinatePadding = 2;
         newTile.AnchorValidTiles = new int[7] { 2, 477, 492, 60, 109, 199, 23 };
         newTile.StyleHorizontal = true;
         newTile.DrawFlipHorizontal = true;
         newTile.WaterPlacement = LiquidPlacement.NotAllowed;
         newTile.LavaDeath = false;
         newTile.RandomStyleRange = 3;
         newTile.StyleMultiplier = 3;
         newTile.StyleHorizontal = true;
         addTile(615);
         readOnlyData = true;
     }
References TileObjectData(), _baseObject, _data, addAlternate(), addBaseTile(), addSubTile(), addTile(), Chest.AfterPlacement_Hook(), AnchorAlternateTiles, AnchorBottom, AnchorInvalidTiles, AnchorLeft, AnchorRight, AnchorTop, AnchorValidTiles, AnchorValidWalls, AnchorWall, WorldGen.CanPlaceProjectilePressurePad(), CoordinateHeights, CoordinatePadding, CoordinatePaddingFix, CoordinateWidth, CopyFrom(), TileID.Count, Direction, DrawFlipHorizontal, DrawStepDown, DrawStyleOffset, DrawXOffset, DrawYOffset, AnchorData.Empty, Chest.FindEmptyChest(), FlattenAnchors, FullCopyFrom(), Height, TETrainingDummy.Hook_AfterPlacement(), TEItemFrame.Hook_AfterPlacement(), TELogicSensor.Hook_AfterPlacement(), TEDisplayDoll.Hook_AfterPlacement(), TEWeaponsRack.Hook_AfterPlacement(), TEHatRack.Hook_AfterPlacement(), TEFoodPlatter.Hook_AfterPlacement(), HookCheckIfCanPlace, HookPlaceOverride, HookPostPlaceMyPlayer, LavaDeath, LavaPlacement, LinkedAlternates, newAlternate, newSubTile, newTile, Origin, TETeleportationPylon.PlacementPreviewHook_AfterPlacement(), TETeleportationPylon.PlacementPreviewHook_CheckIfCanPlace(), WorldGen.PlaceXmasTree_Direct(), RandomStyleRange, readOnlyData, SetupBaseObject(), Style1x1, Style1x2, Style1x2Top, Style1xX, Style2x1, Style2x2, Style2xX, Style3x2, Style3x3, Style3x3Wall, Style3x4, Style4x2, Style5x4, Style6x3, StyleAlch, StyleDye, StyleHorizontal, StyleLineSkip, styleLineSkipVisualOverride, StyleMultiplier, StyleOnTable1x1, StyleSmallCage, StyleSwitch, StyleTorch, StyleWrapLimit, StyleWrapLimitVisualOverride, UsesCustomCanPlace, WaterDeath, WaterPlacement, Width, and Point16.Zero.
Referenced by Main.Initialize_AlmostEverything().