Terraria: UILinksInitializer.HandleOptionsSpecials
HandleOptionsSpecials()
static void UILinksInitializer.HandleOptionsSpecials () inline static
     {
         switch (UILinkPointNavigator.Shortcuts.OPTIONS_BUTTON_SPECIALFEATURE)
         {
         case 1:
             Main.bgScroll = (int)HandleSliderHorizontalInput(Main.bgScroll, 0f, 100f, PlayerInput.CurrentProfile.InterfaceDeadzoneX, 1f);
             Main.caveParallax = 1f - (float)Main.bgScroll / 500f;
             break;
         case 2:
             Main.musicVolume = HandleSliderHorizontalInput(Main.musicVolume, 0f, 1f, PlayerInput.CurrentProfile.InterfaceDeadzoneX, 0.35f);
             break;
         case 3:
             Main.soundVolume = HandleSliderHorizontalInput(Main.soundVolume, 0f, 1f, PlayerInput.CurrentProfile.InterfaceDeadzoneX, 0.35f);
             break;
         case 4:
             Main.ambientVolume = HandleSliderHorizontalInput(Main.ambientVolume, 0f, 1f, PlayerInput.CurrentProfile.InterfaceDeadzoneX, 0.35f);
             break;
         case 5:
         {
             float hBar = Main.hBar;
             float num3 = (Main.hBar = HandleSliderHorizontalInput(hBar, 0f, 1f));
             if (hBar != num3)
             {
                 switch (Main.menuMode)
                 {
                 case 17:
                     Main.player[Main.myPlayer].hairColor = (Main.selColor = Main.hslToRgb(Main.hBar, Main.sBar, Main.lBar));
                     break;
                 case 18:
                     Main.player[Main.myPlayer].eyeColor = (Main.selColor = Main.hslToRgb(Main.hBar, Main.sBar, Main.lBar));
                     break;
                 case 19:
                     Main.player[Main.myPlayer].skinColor = (Main.selColor = Main.hslToRgb(Main.hBar, Main.sBar, Main.lBar));
                     break;
                 case 21:
                     Main.player[Main.myPlayer].shirtColor = (Main.selColor = Main.hslToRgb(Main.hBar, Main.sBar, Main.lBar));
                     break;
                 case 22:
                     Main.player[Main.myPlayer].underShirtColor = (Main.selColor = Main.hslToRgb(Main.hBar, Main.sBar, Main.lBar));
                     break;
                 case 23:
                     Main.player[Main.myPlayer].pantsColor = (Main.selColor = Main.hslToRgb(Main.hBar, Main.sBar, Main.lBar));
                     break;
                 case 24:
                     Main.player[Main.myPlayer].shoeColor = (Main.selColor = Main.hslToRgb(Main.hBar, Main.sBar, Main.lBar));
                     break;
                 case 25:
                     Main.mouseColorSlider.Hue = num3;
                     break;
                 case 252:
                     Main.mouseBorderColorSlider.Hue = num3;
                     break;
                 }
                 SoundEngine.PlaySound(12);
             }
             break;
         }
         case 6:
         {
             float sBar = Main.sBar;
             float num2 = (Main.sBar = HandleSliderHorizontalInput(sBar, 0f, 1f, PlayerInput.CurrentProfile.InterfaceDeadzoneX));
             if (sBar != num2)
             {
                 switch (Main.menuMode)
                 {
                 case 17:
                     Main.player[Main.myPlayer].hairColor = (Main.selColor = Main.hslToRgb(Main.hBar, Main.sBar, Main.lBar));
                     break;
                 case 18:
                     Main.player[Main.myPlayer].eyeColor = (Main.selColor = Main.hslToRgb(Main.hBar, Main.sBar, Main.lBar));
                     break;
                 case 19:
                     Main.player[Main.myPlayer].skinColor = (Main.selColor = Main.hslToRgb(Main.hBar, Main.sBar, Main.lBar));
                     break;
                 case 21:
                     Main.player[Main.myPlayer].shirtColor = (Main.selColor = Main.hslToRgb(Main.hBar, Main.sBar, Main.lBar));
                     break;
                 case 22:
                     Main.player[Main.myPlayer].underShirtColor = (Main.selColor = Main.hslToRgb(Main.hBar, Main.sBar, Main.lBar));
                     break;
                 case 23:
                     Main.player[Main.myPlayer].pantsColor = (Main.selColor = Main.hslToRgb(Main.hBar, Main.sBar, Main.lBar));
                     break;
                 case 24:
                     Main.player[Main.myPlayer].shoeColor = (Main.selColor = Main.hslToRgb(Main.hBar, Main.sBar, Main.lBar));
                     break;
                 case 25:
                     Main.mouseColorSlider.Saturation = num2;
                     break;
                 case 252:
                     Main.mouseBorderColorSlider.Saturation = num2;
                     break;
                 }
                 SoundEngine.PlaySound(12);
             }
             break;
         }
         case 7:
         {
             float lBar = Main.lBar;
             float min = 0.15f;
             if (Main.menuMode == 252)
             {
                 min = 0f;
             }
             Main.lBar = HandleSliderHorizontalInput(lBar, min, 1f, PlayerInput.CurrentProfile.InterfaceDeadzoneX);
             float lBar2 = Main.lBar;
             if (lBar != lBar2)
             {
                 switch (Main.menuMode)
                 {
                 case 17:
                     Main.player[Main.myPlayer].hairColor = (Main.selColor = Main.hslToRgb(Main.hBar, Main.sBar, Main.lBar));
                     break;
                 case 18:
                     Main.player[Main.myPlayer].eyeColor = (Main.selColor = Main.hslToRgb(Main.hBar, Main.sBar, Main.lBar));
                     break;
                 case 19:
                     Main.player[Main.myPlayer].skinColor = (Main.selColor = Main.hslToRgb(Main.hBar, Main.sBar, Main.lBar));
                     break;
                 case 21:
                     Main.player[Main.myPlayer].shirtColor = (Main.selColor = Main.hslToRgb(Main.hBar, Main.sBar, Main.lBar));
                     break;
                 case 22:
                     Main.player[Main.myPlayer].underShirtColor = (Main.selColor = Main.hslToRgb(Main.hBar, Main.sBar, Main.lBar));
                     break;
                 case 23:
                     Main.player[Main.myPlayer].pantsColor = (Main.selColor = Main.hslToRgb(Main.hBar, Main.sBar, Main.lBar));
                     break;
                 case 24:
                     Main.player[Main.myPlayer].shoeColor = (Main.selColor = Main.hslToRgb(Main.hBar, Main.sBar, Main.lBar));
                     break;
                 case 25:
                     Main.mouseColorSlider.Luminance = lBar2;
                     break;
                 case 252:
                     Main.mouseBorderColorSlider.Luminance = lBar2;
                     break;
                 }
                 SoundEngine.PlaySound(12);
             }
             break;
         }
         case 8:
         {
             float aBar = Main.aBar;
             float num4 = (Main.aBar = HandleSliderHorizontalInput(aBar, 0f, 1f, PlayerInput.CurrentProfile.InterfaceDeadzoneX));
             if (aBar != num4)
             {
                 int menuMode = Main.menuMode;
                 if (menuMode == 252)
                 {
                     Main.mouseBorderColorSlider.Alpha = num4;
                 }
                 SoundEngine.PlaySound(12);
             }
             break;
         }
         case 9:
         {
             bool left = PlayerInput.Triggers.Current.Left;
             bool right = PlayerInput.Triggers.Current.Right;
             if (PlayerInput.Triggers.JustPressed.Left || PlayerInput.Triggers.JustPressed.Right)
             {
                 SomeVarsForUILinkers.HairMoveCD = 0;
             }
             else if (SomeVarsForUILinkers.HairMoveCD > 0)
             {
                 SomeVarsForUILinkers.HairMoveCD--;
             }
             if (SomeVarsForUILinkers.HairMoveCD == 0 && (left || right))
             {
                 if (left)
                 {
                     Main.PendingPlayer.hair--;
                 }
                 if (right)
                 {
                     Main.PendingPlayer.hair++;
                 }
                 SomeVarsForUILinkers.HairMoveCD = 12;
             }
             int num = 51;
             if (Main.PendingPlayer.hair >= num)
             {
                 Main.PendingPlayer.hair = 0;
             }
             if (Main.PendingPlayer.hair < 0)
             {
                 Main.PendingPlayer.hair = num - 1;
             }
             break;
         }
         case 10:
             Main.GameZoomTarget = HandleSliderHorizontalInput(Main.GameZoomTarget, 1f, 2f, PlayerInput.CurrentProfile.InterfaceDeadzoneX, 0.35f);
             break;
         case 11:
             Main.UIScale = HandleSliderHorizontalInput(Main.UIScaleWanted, 0.5f, 2f, PlayerInput.CurrentProfile.InterfaceDeadzoneX, 0.35f);
             Main.temporaryGUIScaleSlider = Main.UIScaleWanted;
             break;
         case 12:
             Main.MapScale = HandleSliderHorizontalInput(Main.MapScale, 0.5f, 1f, PlayerInput.CurrentProfile.InterfaceDeadzoneX, 0.7f);
             break;
         }
     }
References Main.aBar, ColorSlidersSet.Alpha, Main.ambientVolume, Main.bgScroll, Main.caveParallax, TriggersPack.Current, PlayerInput.CurrentProfile, Player.eyeColor, Main.GameZoomTarget, Player.hair, Player.hairColor, UILinksInitializer.SomeVarsForUILinkers.HairMoveCD, Main.hBar, Main.hslToRgb(), ColorSlidersSet.Hue, PlayerInputProfile.InterfaceDeadzoneX, TriggersPack.JustPressed, Main.lBar, TriggersSet.Left, ColorSlidersSet.Luminance, Main.MapScale, Main.menuMode, Main.mouseBorderColorSlider, Main.mouseColorSlider, Main.musicVolume, Main.myPlayer, UILinkPointNavigator.Shortcuts.OPTIONS_BUTTON_SPECIALFEATURE, Player.pantsColor, Main.PendingPlayer, Main.player, SoundEngine.PlaySound(), TriggersSet.Right, ColorSlidersSet.Saturation, Main.sBar, Main.selColor, Player.shirtColor, Player.shoeColor, Player.skinColor, Main.soundVolume, Main.temporaryGUIScaleSlider, PlayerInput.Triggers, Main.UIScale, Main.UIScaleWanted, and Player.underShirtColor.
Referenced by Load().