Terraria: UILinksInitializer.FancyExit
FancyExit()
static void UILinksInitializer.FancyExit () inline static
     {
         switch (UILinkPointNavigator.Shortcuts.BackButtonCommand)
         {
         case 1:
             SoundEngine.PlaySound(11);
             Main.menuMode = 0;
             break;
         case 2:
             SoundEngine.PlaySound(11);
             Main.menuMode = ((!Main.menuMultiplayer) ? 1 : 12);
             break;
         case 3:
             Main.menuMode = 0;
             IngameFancyUI.Close();
             break;
         case 4:
             SoundEngine.PlaySound(11);
             Main.menuMode = 11;
             break;
         case 5:
             SoundEngine.PlaySound(11);
             Main.menuMode = 11;
             break;
         case 6:
             UIVirtualKeyboard.Cancel();
             break;
         case 7:
             if (Main.MenuUI.CurrentState is IHaveBackButtonCommand haveBackButtonCommand)
             {
                 haveBackButtonCommand.HandleBackButtonUsage();
             }
             break;
         }
     }
References UILinkPointNavigator.Shortcuts.BackButtonCommand, UIVirtualKeyboard.Cancel(), IngameFancyUI.Close(), UserInterface.CurrentState, Main.menuMode, Main.menuMultiplayer, Main.MenuUI, and SoundEngine.PlaySound().
Referenced by Load().