Terraria: System.Xml.IXmlNamespaceResolver.LookupNamespace
LookupNamespace()
string? System.Xml.IXmlNamespaceResolver.LookupNamespace (string prefix)
Implemented in MS.Internal.Xml.XPath.CompiledXpathExpr.UndefinedXsltContext, System.Xml.Schema.DtdValidator.NamespaceManager, System.Xml.Schema.SchemaNamespaceManager, System.Xml.Schema.XmlAtomicValue.NamespacePrefixForQName, System.Xml.Schema.XsdBuilder.BuilderNamespaceManager, System.Xml.XPath.XPathNavigator, System.Xml.XPath.XPathNavigatorReader, System.Xml.XPath.XPathNavigatorReader, System.Xml.Xsl.XsltOld.XsltCompileContext, System.Xml.DocumentSchemaValidator, System.Xml.DocumentXmlWriter, System.Xml.DocumentXPathNavigator, System.Xml.XmlAsyncCheckReaderWithLineInfoNS, System.Xml.XmlAsyncCheckReaderWithNS, System.Xml.XmlCharCheckingReaderWithNS, System.Xml.XmlNamespaceManager, System.Xml.XmlNodeReader, System.Xml.XmlNodeReader, System.Xml.XmlSqlBinaryReader, System.Xml.XmlSubtreeReader, System.Xml.XmlSubtreeReader, System.Xml.XmlTextReader, System.Xml.XmlTextReader, System.Xml.XmlTextReaderImpl.NoNamespaceManager, System.Xml.XmlTextReaderImpl, System.Xml.XmlTextReaderImpl, System.Xml.XmlValidatingReader, System.Xml.XmlValidatingReader, System.Xml.XmlValidatingReaderImpl, System.Xml.XmlValidatingReaderImpl, System.Xml.XmlWellFormedWriter.NamespaceResolverProxy, System.Xml.XsdValidatingReader, and System.Xml.XsdValidatingReader.
Referenced by System.Xml.XmlWellFormedWriter.XmlWellFormedWriter(), System.Xml.XsdValidatingReader.GetAttributePSVI(), System.Xml.XsdValidatingReader.GetDefaultAttribute(), MS.Internal.Xml.XPath.CompiledXpathExpr.UndefinedXsltContext.LookupNamespace(), System.Xml.XmlAsyncCheckReaderWithLineInfoNS.LookupNamespace(), System.Xml.XmlAsyncCheckReaderWithNS.LookupNamespace(), System.Xml.XmlCharCheckingReaderWithNS.LookupNamespace(), System.Xml.XmlWellFormedWriter.LookupNamespace(), System.Xml.XsdValidatingReader.LookupNamespace(), System.Xml.XmlWellFormedWriter.PushNamespaceExplicit(), and System.Xml.XmlWellFormedWriter.PushNamespaceImplicit().