Terraria: System.Xml.IXmlNamespaceResolver.GetNamespacesInScope
GetNamespacesInScope()
IDictionary< string, string > System.Xml.IXmlNamespaceResolver.GetNamespacesInScope (XmlNamespaceScope scope)
Implemented in System.Xml.Schema.XmlAtomicValue.NamespacePrefixForQName, System.Xml.XPath.XPathNavigator, System.Xml.XPath.XPathNavigatorReader, System.Xml.DocumentSchemaValidator, System.Xml.DocumentXmlWriter, System.Xml.XmlAsyncCheckReaderWithLineInfoNS, System.Xml.XmlAsyncCheckReaderWithNS, System.Xml.XmlCharCheckingReaderWithNS, System.Xml.XmlNamespaceManager, System.Xml.XmlNodeReader, System.Xml.XmlSqlBinaryReader, System.Xml.XmlSubtreeReader, System.Xml.XmlTextReader, System.Xml.XmlTextReader, System.Xml.XmlTextReaderImpl.NoNamespaceManager, System.Xml.XmlTextReaderImpl, System.Xml.XmlTextReaderImpl, System.Xml.XmlValidatingReader, System.Xml.XmlValidatingReaderImpl, System.Xml.XmlValidatingReaderImpl, System.Xml.XmlWellFormedWriter.NamespaceResolverProxy, and System.Xml.XsdValidatingReader.
Referenced by System.Xml.Schema.XmlSchemaValidator.GetDefaultAttributePrefix(), System.Xml.DocumentSchemaValidator.GetDefaultPrefix(), System.Xml.XmlAsyncCheckReaderWithLineInfoNS.GetNamespacesInScope(), System.Xml.XmlAsyncCheckReaderWithNS.GetNamespacesInScope(), System.Xml.XmlCharCheckingReaderWithNS.GetNamespacesInScope(), System.Xml.XmlValidatingReaderImpl.GetNamespacesInScope(), and System.Xml.XsdValidatingReader.GetNamespacesInScope().