Terraria: System.Xml.IXmlNamespaceResolver.LookupPrefix
LookupPrefix()
string? System.Xml.IXmlNamespaceResolver.LookupPrefix (string namespaceName)
Implemented in System.Xml.Schema.XmlAtomicValue.NamespacePrefixForQName, System.Xml.XPath.XPathNavigatorReader, System.Xml.DocumentSchemaValidator, System.Xml.DocumentXmlWriter, System.Xml.XmlAsyncCheckReaderWithLineInfoNS, System.Xml.XmlAsyncCheckReaderWithNS, System.Xml.XmlCharCheckingReaderWithNS, System.Xml.XmlNodeReader, System.Xml.XmlSqlBinaryReader, System.Xml.XmlSubtreeReader, System.Xml.XmlTextReader, System.Xml.XmlTextReaderImpl, System.Xml.XmlTextReaderImpl, System.Xml.XmlValidatingReader, System.Xml.XmlValidatingReaderImpl, System.Xml.XmlValidatingReaderImpl, System.Xml.XmlWellFormedWriter.NamespaceResolverProxy, System.Xml.XsdValidatingReader, System.Xml.XPath.XPathNavigator, System.Xml.Schema.SchemaNamespaceManager, System.Xml.XmlNamespaceManager, and System.Xml.XmlTextReaderImpl.NoNamespaceManager.
Referenced by System.Xml.Schema.XmlSchemaValidator.GetExpectedAttributes(), System.Xml.XmlAsyncCheckReaderWithLineInfoNS.LookupPrefix(), System.Xml.XmlAsyncCheckReaderWithNS.LookupPrefix(), System.Xml.XmlCharCheckingReaderWithNS.LookupPrefix(), System.Xml.XmlValidatingReaderImpl.LookupPrefix(), System.Xml.XsdValidatingReader.LookupPrefix(), and System.Xml.XmlWellFormedWriter.LookupPrefix().