Terraria: TreeTopsInfo.RandomizeTreeStyleBasedOnWorldPosition
RandomizeTreeStyleBasedOnWorldPosition()
void TreeTopsInfo.RandomizeTreeStyleBasedOnWorldPosition (UnifiedRandom rand, Vector2 worldPosition) inline
     {
         Point pt = new Point((int)(worldPosition.X / 16f), (int)(worldPosition.Y / 16f) + 1);
         Tile tileSafely = Framing.GetTileSafely(pt);
         if (tileSafely.active())
         {
             int num = -1;
             if (tileSafely.type == 70)
             {
                 num = 11;
             }
             else if (tileSafely.type == 53 && WorldGen.oceanDepths(pt.X, pt.Y))
             {
                 num = 10;
             }
             else if (tileSafely.type == 23)
             {
                 num = 4;
             }
             else if (tileSafely.type == 199)
             {
                 num = 8;
             }
             else if (tileSafely.type == 109 || tileSafely.type == 492)
             {
                 num = 7;
             }
             else if (tileSafely.type == 53)
             {
                 num = 9;
             }
             else if (tileSafely.type == 147)
             {
                 num = 6;
             }
             else if (tileSafely.type == 60)
             {
                 num = 5;
             }
             else if (tileSafely.type == 633)
             {
                 num = 12;
             }
             else if (tileSafely.type == 2 || tileSafely.type == 477)
             {
                 num = ((pt.X >= Main.treeX[0]) ? ((pt.X < Main.treeX[1]) ? 1 : ((pt.X >= Main.treeX[2]) ? 3 : 2)) : 0);
             }
             if (num > -1)
             {
                 RandomizeTreeStyle(rand, num);
             }
         }
     }
References Tile.active(), Framing.GetTileSafely(), WorldGen.oceanDepths(), RandomizeTreeStyle(), Main.treeX, and Tile.type.
Referenced by Projectile.Kill().