Terraria: System.Net.WebResponse.Dispose
Dispose() [1/2]
void System.Net.WebResponse.Dispose () inline
Implements System.IDisposable.
Definition at line 77 of file WebResponse.cs.
    {
        Dispose(disposing: true);
        GC.SuppressFinalize(this);
    }
References System.Runtime.Serialization.Dictionary, System.Net.WebResponse.Dispose(), and System.GC.SuppressFinalize().
Referenced by System.Net.HttpWebResponse.Close(), System.Net.WebResponse.Dispose(), and System.Net.WebClient.WebClientWriteStream.Dispose().