Terraria: MS.Internal.Xml.XPath.ChildrenQuery.Advance
Advance()
override XPathNavigator MS.Internal.Xml.XPath.ChildrenQuery.Advance () inline
Definition at line 26 of file ChildrenQuery.cs.
    {
        while (!_iterator.MoveNext())
        {
            XPathNavigator xPathNavigator = qyInput.Advance();
            if (xPathNavigator == null)
            {
                return null;
            }
            if (base.NameTest)
            {
                if (base.TypeTest == XPathNodeType.ProcessingInstruction)
                {
                    _iterator = new IteratorFilter(xPathNavigator.SelectChildren(base.TypeTest), base.Name);
                }
                else
                {
                    _iterator = xPathNavigator.SelectChildren(base.Name, base.Namespace);
                }
            }
            else
            {
                _iterator = xPathNavigator.SelectChildren(base.TypeTest);
            }
            position = 0;
        }
        position++;
        currentNode = _iterator.Current;
        return currentNode;
    }
References MS.Internal.Xml.XPath.ChildrenQuery._iterator, MS.Internal.Xml.XPath.Query.Advance(), System.Xml.XPath.XPathNodeIterator.Current, MS.Internal.Xml.XPath.BaseAxisQuery.currentNode, System.Xml.XPath.XPathNodeIterator.MoveNext(), MS.Internal.Xml.XPath.BaseAxisQuery.position, MS.Internal.Xml.XPath.BaseAxisQuery.qyInput, and System.Xml.XPath.XPathNavigator.SelectChildren().