Terraria: System.Globalization.FormatProvider.Number.FormatFixed
FormatFixed()
static unsafe void System.Globalization.FormatProvider.Number.FormatFixed (ref System::Text::ValueStringBuilder sb, ref NumberBuffer number, int nMinDigits, int nMaxDigits, NumberFormatInfo info, int[] groupDigits, string sDecimal, string sGroup) inline static private
Definition at line 567 of file FormatProvider.cs.
        {
            int scale = number.scale;
            char* ptr = number.digits;
            int length = MemoryMarshal.CreateReadOnlySpanFromNullTerminated(ptr).Length;
            if (scale > 0)
            {
                if (groupDigits != null)
                {
                    int num = 0;
                    int num2 = groupDigits[num];
                    int num3 = groupDigits.Length;
                    int num4 = scale;
                    int length2 = sGroup.Length;
                    int num5 = 0;
                    if (num3 != 0)
                    {
                        while (scale > num2 && groupDigits[num] != 0)
{
                            num4 += length2;
                            if (num < num3 - 1)
{
                                num++;
                            }
                            num2 += groupDigits[num];
                            if (num2 < 0 || num4 < 0)
{
                                throw new ArgumentOutOfRangeException();
                            }
                        }
                        num5 = ((num2 != 0) ? groupDigits[0] : 0);
                    }
                    char* ptr2 = stackalloc char[num4];
                    num = 0;
                    int num6 = 0;
                    int num7 = ((scale < length) ? scale : length);
                    char* ptr3 = ptr2 + num4 - 1;
                    for (int num8 = scale - 1; num8 >= 0; num8--)
                    {
                        *(ptr3--) = ((num8 < num7) ? ptr[num8] : '0');
                        if (num5 > 0)
{
                            num6++;
                            if (num6 == num5 && num8 != 0)
{
                                for (int num9 = length2 - 1; num9 >= 0; num9--)
{
                                    *(ptr3--) = sGroup[num9];
                                }
                                if (num < num3 - 1)
{
                                    num++;
                                    num5 = groupDigits[num];
                                }
                                num6 = 0;
                            }
                        }
                    }
                    sb.Append(ptr2, num4);
                    ptr += num7;
                }
                else
                {
                    int num10 = Math.Min(length, scale);
                    sb.Append(ptr, num10);
                    ptr += num10;
                    if (scale > length)
                    {
                        sb.Append('0', scale - length);
                    }
                }
            }
            else
            {
                sb.Append('0');
            }
            if (nMaxDigits > 0)
            {
                sb.Append(sDecimal);
                if (scale < 0 && nMaxDigits > 0)
                {
                    int num11 = Math.Min(-scale, nMaxDigits);
                    sb.Append('0', num11);
                    scale += num11;
                    nMaxDigits -= num11;
                }
                while (nMaxDigits > 0)
                {
                    sb.Append((*ptr != 0) ? (*(ptr++)) : '0');
                    nMaxDigits--;
                }
            }
        }
References System.Runtime.InteropServices.MemoryMarshal.CreateReadOnlySpanFromNullTerminated(), System.length, System.length2, and System.Math.Min().
Referenced by System.Globalization.FormatProvider.Number.FormatCurrency(), System.Globalization.FormatProvider.Number.FormatNumber(), System.Globalization.FormatProvider.Number.FormatPercent(), and System.Globalization.FormatProvider.Number.NumberToString().