Terraria: System.Globalization.FormatProvider.Number.NumberToString
NumberToString()
static unsafe void System.Globalization.FormatProvider.Number.NumberToString (ref System::Text::ValueStringBuilder sb, ref NumberBuffer number, char format, int nMaxDigits, NumberFormatInfo info, bool isDecimal) inline static package
Definition at line 426 of file FormatProvider.cs.
        {
            int num = -1;
            switch (format)
            {
            case 'C':
            case 'c':
                num = ((nMaxDigits >= 0) ? nMaxDigits : info.CurrencyDecimalDigits);
                if (nMaxDigits < 0)
                {
                    nMaxDigits = info.CurrencyDecimalDigits;
                }
                RoundNumber(ref number, number.scale + nMaxDigits);
                FormatCurrency(ref sb, ref number, num, nMaxDigits, info);
                break;
            case 'F':
            case 'f':
                if (nMaxDigits < 0)
                {
                    nMaxDigits = (num = info.NumberDecimalDigits);
                }
                else
                {
                    num = nMaxDigits;
                }
                RoundNumber(ref number, number.scale + nMaxDigits);
                if (number.sign)
                {
                    sb.Append(info.NegativeSign);
                }
                FormatFixed(ref sb, ref number, num, nMaxDigits, info, null, info.NumberDecimalSeparator, null);
                break;
            case 'N':
            case 'n':
                if (nMaxDigits < 0)
                {
                    nMaxDigits = (num = info.NumberDecimalDigits);
                }
                else
                {
                    num = nMaxDigits;
                }
                RoundNumber(ref number, number.scale + nMaxDigits);
                FormatNumber(ref sb, ref number, num, nMaxDigits, info);
                break;
            case 'E':
            case 'e':
                if (nMaxDigits < 0)
                {
                    nMaxDigits = (num = 6);
                }
                else
                {
                    num = nMaxDigits;
                }
                nMaxDigits++;
                RoundNumber(ref number, nMaxDigits);
                if (number.sign)
                {
                    sb.Append(info.NegativeSign);
                }
                FormatScientific(ref sb, ref number, num, nMaxDigits, info, format);
                break;
            case 'G':
            case 'g':
            {
                bool flag = true;
                if (nMaxDigits < 1)
                {
                    if (isDecimal && nMaxDigits == -1)
                    {
                        nMaxDigits = (num = 29);
                        flag = false;
                    }
                    else
                    {
                        nMaxDigits = (num = number.precision);
                    }
                }
                else
                {
                    num = nMaxDigits;
                }
                if (flag)
                {
                    RoundNumber(ref number, nMaxDigits);
                }
                else if (isDecimal && *number.digits == '\0')
                {
                    number.sign = false;
                }
                if (number.sign)
                {
                    sb.Append(info.NegativeSign);
                }
                FormatGeneral(ref sb, ref number, num, nMaxDigits, info, (char)(format - 2), !flag);
                break;
            }
            case 'P':
            case 'p':
                if (nMaxDigits < 0)
                {
                    nMaxDigits = (num = info.PercentDecimalDigits);
                }
                else
                {
                    num = nMaxDigits;
                }
                number.scale += 2;
                RoundNumber(ref number, number.scale + nMaxDigits);
                FormatPercent(ref sb, ref number, num, nMaxDigits, info);
                break;
            default:
                throw new FormatException(System.SR.Argument_BadFormatSpecifier);
            }
        }
References System.SR.Argument_BadFormatSpecifier, System.format, System.Globalization.FormatProvider.Number.FormatCurrency(), System.Globalization.FormatProvider.Number.FormatFixed(), System.Globalization.FormatProvider.Number.FormatGeneral(), System.Globalization.FormatProvider.Number.FormatNumber(), System.Globalization.FormatProvider.Number.FormatPercent(), System.Globalization.FormatProvider.Number.FormatScientific(), System.info, and System.Globalization.FormatProvider.Number.RoundNumber().
Referenced by System.Globalization.FormatProvider.FormatBigInteger().