Terraria: System.Globalization.FormatProvider.Number.FormatExponent
FormatExponent()
static unsafe void System.Globalization.FormatProvider.Number.FormatExponent (ref System::Text::ValueStringBuilder sb, NumberFormatInfo info, int value, char expChar, int minDigits, bool positiveSign) inline static private
Definition at line 698 of file FormatProvider.cs.
        {
            sb.Append(expChar);
            if (value < 0)
            {
                sb.Append(info.NegativeSign);
                value = -value;
            }
            else if (positiveSign)
            {
                sb.Append(info.PositiveSign);
            }
            char* ptr = stackalloc char[11];
            int index = 10;
            Int32ToDecChars(ptr, ref index, (uint)value, minDigits);
            int num = 10 - index;
            while (--num >= 0)
            {
                sb.Append(ptr[index++]);
            }
        }
References System.index, System.info, System.Globalization.FormatProvider.Number.Int32ToDecChars(), and System.value.
Referenced by System.Globalization.FormatProvider.Number.FormatGeneral(), System.Globalization.FormatProvider.Number.FormatScientific(), and System.Globalization.FormatProvider.Number.NumberToStringFormat().