Terraria: System.Data.Common.DbDataAdapter.UpdatedRowStatus
UpdatedRowStatus()
int System.Data.Common.DbDataAdapter.UpdatedRowStatus (RowUpdatedEventArgs rowUpdatedEvent, BatchCommandInfo[] batchCommands, int commandCount) inline private
Definition at line 1371 of file DbDataAdapter.cs.
    {
        int num = 0;
        switch (rowUpdatedEvent.Status)
        {
        case UpdateStatus.Continue:
            return UpdatedRowStatusContinue(rowUpdatedEvent, batchCommands, commandCount);
        case UpdateStatus.ErrorsOccurred:
            return UpdatedRowStatusErrors(rowUpdatedEvent, batchCommands, commandCount);
        case UpdateStatus.SkipCurrentRow:
        case UpdateStatus.SkipAllRemainingRows:
            return UpdatedRowStatusSkip(batchCommands, commandCount);
        default:
            throw ADP.InvalidUpdateStatus(rowUpdatedEvent.Status);
        }
    }
References System.Data.Common.ADP.InvalidUpdateStatus(), System.Data.Common.DbDataAdapter.UpdatedRowStatusContinue(), System.Data.Common.DbDataAdapter.UpdatedRowStatusErrors(), and System.Data.Common.DbDataAdapter.UpdatedRowStatusSkip().
Referenced by System.Data.Common.DbDataAdapter.Update().