Terraria: System.Data.Common.DbDataAdapter.ParameterOutput
ParameterOutput() [1/2]
void System.Data.Common.DbDataAdapter.ParameterOutput (IDataParameter parameter, DataRow row, DataTableMapping mappings, MissingMappingAction missingMapping, MissingSchemaAction missingSchema) inline private
Definition at line 714 of file DbDataAdapter.cs.
    {
        if ((ParameterDirection.Output & parameter.Direction) == 0)
        {
            return;
        }
        object value = parameter.Value;
        if (value == null)
        {
            return;
        }
        string sourceColumn = parameter.SourceColumn;
        if (string.IsNullOrEmpty(sourceColumn))
        {
            return;
        }
        DataColumn dataColumn = mappings.GetDataColumn(sourceColumn, null, row.Table, missingMapping, missingSchema);
        if (dataColumn == null)
        {
            return;
        }
        if (dataColumn.ReadOnly)
        {
            try
            {
                dataColumn.ReadOnly = false;
                row[dataColumn] = value;
                return;
            }
            finally
            {
                dataColumn.ReadOnly = true;
            }
        }
        row[dataColumn] = value;
    }
References System.value.
Referenced by System.Data.Common.DbDataAdapter.ParameterOutput(), System.Data.Common.DbDataAdapter.UpdateBatchExecute(), and System.Data.Common.DbDataAdapter.UpdateRowExecute().