Terraria: System.Data.Common.DbDataAdapter.UpdateFromDataTable
UpdateFromDataTable()
int System.Data.Common.DbDataAdapter.UpdateFromDataTable (DataTable dataTable, DataTableMapping tableMapping) inline private
Definition at line 1298 of file DbDataAdapter.cs.
    {
        int result = 0;
        DataRow[] array = ADP.SelectAdapterRows(dataTable, sorted: false);
        if (array != null && array.Length != 0)
        {
            result = Update(array, tableMapping);
        }
        return result;
    }
References System.array, System.Data.Common.ADP.SelectAdapterRows(), and System.Data.Update.
Referenced by System.Data.Common.DbDataAdapter.Update(), and System.Data.Common.DbDataAdapter.Update().