Terraria: System.Data.Common.DbDataAdapter.Update
Update() [1/5]
int System.Data.Common.DbDataAdapter.Update (DataRow[] dataRows) inline
Definition at line 776 of file DbDataAdapter.cs.
    {
        long scopeId = DataCommonEventSource.Log.EnterScope("<comm.DbDataAdapter.Update|API> {0}, dataRows[]", base.ObjectID);
        try
        {
            int result = 0;
            if (dataRows == null)
            {
                throw ADP.ArgumentNull("dataRows");
            }
            if (dataRows.Length != 0)
            {
                DataTable dataTable = null;
                for (int i = 0; i < dataRows.Length; i++)
                {
                    if (dataRows[i] != null && dataTable != dataRows[i].Table)
                    {
                        if (dataTable != null)
{
                            throw ADP.UpdateMismatchRowTable(i);
                        }
                        dataTable = dataRows[i].Table;
                    }
                }
                if (dataTable != null)
                {
                    DataTableMapping tableMapping = GetTableMapping(dataTable);
                    result = Update(dataRows, tableMapping);
                }
            }
            return result;
        }
        finally
        {
            DataCommonEventSource.Log.ExitScope(scopeId);
        }
    }
References System.Data.Common.ADP.ArgumentNull(), System.Data.Common.DbDataAdapter.GetTableMapping(), System.Data.DataCommonEventSource.Log, System.Data.Update, and System.Data.Common.ADP.UpdateMismatchRowTable().