Terraria: System.Data.Common.DbDataAdapter.FillSchemaInternal
FillSchemaInternal()
object System.Data.Common.DbDataAdapter.FillSchemaInternal (DataSet dataset, DataTable datatable, SchemaType schemaType, IDbCommand command, string srcTable, CommandBehavior behavior) inline private
Definition at line 385 of file DbDataAdapter.cs.
    {
        object result = null;
        bool flag = command.Connection == null;
        try
        {
            IDbConnection connection = GetConnection3(this, command, "FillSchema");
            ConnectionState originalState = ConnectionState.Open;
            try
            {
                QuietOpen(connection, out originalState);
                using IDataReader dataReader = command.ExecuteReader(behavior | CommandBehavior.SchemaOnly | CommandBehavior.KeyInfo);
                result = ((datatable == null) ? ((object)FillSchema(dataset, schemaType, srcTable, dataReader)) : ((object)FillSchema(datatable, schemaType, dataReader)));
            }
            finally
            {
                QuietClose(connection, originalState);
            }
        }
        finally
        {
            if (flag)
            {
                command.Transaction = null;
                command.Connection = null;
            }
        }
        return result;
    }
References System.Data.Common.DbDataAdapter.FillSchema(), System.Data.Common.DbDataAdapter.GetConnection3(), System.Data.Common.DbDataAdapter.QuietClose(), and System.Data.Common.DbDataAdapter.QuietOpen().
Referenced by System.Data.Common.DbDataAdapter.FillSchema(), and System.Data.Common.DbDataAdapter.FillSchema().