Terraria: System.Data.Common.DbDataAdapter.Clone
Clone()
object ICloneable. System.Data.Common.DbDataAdapter.Clone () inline private
Implements System.ICloneable.
Definition at line 222 of file DbDataAdapter.cs.
    {
        DbDataAdapter dbDataAdapter = (DbDataAdapter)CloneInternals();
        dbDataAdapter.CloneFrom(this);
        return dbDataAdapter;
    }
References System.Data.Common.DbDataAdapter.DbDataAdapter(), and System.Data.Common.DataAdapter.CloneInternals().
Referenced by System.Data.Common.DbDataAdapter.CloneCommand().