Terraria: System.Data.Common.DbDataAdapter.UpdateRowExecute
UpdateRowExecute()
void System.Data.Common.DbDataAdapter.UpdateRowExecute (RowUpdatedEventArgs rowUpdatedEvent, IDbCommand dataCommand, StatementType cmdIndex) inline private
Definition at line 1310 of file DbDataAdapter.cs.
    {
        bool flag = true;
        UpdateRowSource updatedRowSource = dataCommand.UpdatedRowSource;
        if (StatementType.Delete == cmdIndex || (UpdateRowSource.FirstReturnedRecord & updatedRowSource) == 0)
        {
            int recordsAffected = dataCommand.ExecuteNonQuery();
            rowUpdatedEvent.AdapterInit(recordsAffected);
        }
        else if (StatementType.Insert == cmdIndex || StatementType.Update == cmdIndex)
        {
            using IDataReader dataReader = dataCommand.ExecuteReader(CommandBehavior.SequentialAccess);
            DataReaderContainer dataReaderContainer = DataReaderContainer.Create(dataReader, ReturnProviderSpecificTypes);
            try
            {
                bool flag2 = false;
                do
                {
                    if (0 < dataReaderContainer.FieldCount)
                    {
                        flag2 = true;
                        break;
                    }
                }
                while (dataReader.NextResult());
                if (flag2 && dataReader.RecordsAffected != 0)
                {
                    SchemaMapping schemaMapping = new SchemaMapping(this, null, rowUpdatedEvent.Row.Table, dataReaderContainer, keyInfo: false, SchemaType.Mapped, rowUpdatedEvent.TableMapping.SourceTable, gettingData: true, null, null);
                    if (schemaMapping.DataTable != null && schemaMapping.DataValues != null && dataReader.Read())
                    {
                        if (StatementType.Insert == cmdIndex && flag)
{
                            rowUpdatedEvent.Row.AcceptChanges();
                            flag = false;
                        }
                        schemaMapping.ApplyToDataRow(rowUpdatedEvent.Row);
                    }
                }
            }
            finally
            {
                dataReader.Close();
                int recordsAffected2 = dataReader.RecordsAffected;
                rowUpdatedEvent.AdapterInit(recordsAffected2);
            }
        }
        if ((StatementType.Insert == cmdIndex || StatementType.Update == cmdIndex) && (UpdateRowSource.OutputParameters & updatedRowSource) != 0 && rowUpdatedEvent.RecordsAffected != 0)
        {
            if (StatementType.Insert == cmdIndex && flag)
            {
                rowUpdatedEvent.Row.AcceptChanges();
            }
            ParameterOutput(dataCommand.Parameters, rowUpdatedEvent.Row, rowUpdatedEvent.TableMapping);
        }
        if (rowUpdatedEvent.Status == UpdateStatus.Continue && (uint)(cmdIndex - 2) <= 1u && rowUpdatedEvent.RecordsAffected == 0)
        {
            rowUpdatedEvent.Errors = ADP.UpdateConcurrencyViolation(cmdIndex, rowUpdatedEvent.RecordsAffected, 1, new DataRow[1] { rowUpdatedEvent.Row });
            rowUpdatedEvent.Status = UpdateStatus.ErrorsOccurred;
        }
    }
References System.Data.ProviderBase.DataReaderContainer.Create(), System.Data.Common.DbDataAdapter.ParameterOutput(), System.Data.Common.DataAdapter.ReturnProviderSpecificTypes, and System.Data.Common.ADP.UpdateConcurrencyViolation().
Referenced by System.Data.Common.DbDataAdapter.Update().