Terraria: System.Data.Common.DbDataAdapter.FillSchema
FillSchema() [7/7]
virtual ? DataTable System.Data.Common.DbDataAdapter.FillSchema (DataTable dataTable, SchemaType schemaType, IDbCommand command, CommandBehavior behavior) inline protected virtual
Definition at line 353 of file DbDataAdapter.cs.
    {
        long scopeId = DataCommonEventSource.Log.EnterScope("<comm.DbDataAdapter.FillSchema|API> {0}, dataTable, schemaType, command, behavior={1}", base.ObjectID, behavior);
        try
        {
            if (dataTable == null)
            {
                throw ADP.ArgumentNull("dataTable");
            }
            if (SchemaType.Source != schemaType && SchemaType.Mapped != schemaType)
            {
                throw ADP.InvalidSchemaType(schemaType);
            }
            if (command == null)
            {
                throw ADP.MissingSelectCommand("FillSchema");
            }
            string text = dataTable.TableName;
            int num = IndexOfDataSetTable(text);
            if (-1 != num)
            {
                text = base.TableMappings[num].SourceTable;
            }
            return (DataTable)FillSchemaInternal(null, dataTable, schemaType, command, text, behavior | CommandBehavior.SingleResult);
        }
        finally
        {
            DataCommonEventSource.Log.ExitScope(scopeId);
        }
    }
References System.Data.Common.ADP.ArgumentNull(), System.Data.Common.DbDataAdapter.FillSchemaInternal(), System.Data.Common.DataAdapter.IndexOfDataSetTable(), System.Data.Common.ADP.InvalidSchemaType(), System.Data.DataCommonEventSource.Log, System.Data.Common.ADP.MissingSelectCommand(), and System.text.