Terraria: System.Data.Common.DbDataAdapter.UpdateBatchExecute
UpdateBatchExecute()
void System.Data.Common.DbDataAdapter.UpdateBatchExecute (BatchCommandInfo[] batchCommands, int commandCount, RowUpdatedEventArgs rowUpdatedEvent) inline private
Definition at line 1216 of file DbDataAdapter.cs.
    {
        try
        {
            int recordsAffected = ExecuteBatch();
            rowUpdatedEvent.AdapterInit(recordsAffected);
        }
        catch (DbException ex)
        {
            ADP.TraceExceptionForCapture(ex);
            rowUpdatedEvent.Errors = ex;
            rowUpdatedEvent.Status = UpdateStatus.ErrorsOccurred;
        }
        MissingMappingAction updateMappingAction = UpdateMappingAction;
        MissingSchemaAction updateSchemaAction = UpdateSchemaAction;
        int num = 0;
        bool flag = false;
        List<DataRow> list = null;
        for (int i = 0; i < commandCount; i++)
        {
            BatchCommandInfo batchCommandInfo = batchCommands[i];
            StatementType statementType = batchCommandInfo._statementType;
            if (GetBatchedRecordsAffected(batchCommandInfo._commandIdentifier, out int recordsAffected2, out batchCommands[i]._errors))
            {
                batchCommands[i]._recordsAffected = recordsAffected2;
            }
            if (batchCommands[i]._errors != null || !batchCommands[i]._recordsAffected.HasValue)
            {
                continue;
            }
            if (StatementType.Update == statementType || StatementType.Delete == statementType)
            {
                num++;
                if (recordsAffected2 == 0)
                {
                    if (list == null)
                    {
                        list = new List<DataRow>();
                    }
                    batchCommands[i]._errors = ADP.UpdateConcurrencyViolation(batchCommands[i]._statementType, 0, 1, new DataRow[1] { rowUpdatedEvent.Rows[i] });
                    flag = true;
                    list.Add(rowUpdatedEvent.Rows[i]);
                }
            }
            if ((StatementType.Insert == statementType || StatementType.Update == statementType) && (UpdateRowSource.OutputParameters & batchCommandInfo._updatedRowSource) != 0 && recordsAffected2 != 0)
            {
                if (StatementType.Insert == statementType)
                {
                    rowUpdatedEvent.Rows[i].AcceptChanges();
                }
                for (int j = 0; j < batchCommandInfo._parameterCount; j++)
                {
                    IDataParameter batchedParameter = GetBatchedParameter(batchCommandInfo._commandIdentifier, j);
                    ParameterOutput(batchedParameter, batchCommandInfo._row, rowUpdatedEvent.TableMapping, updateMappingAction, updateSchemaAction);
                }
            }
        }
        if (rowUpdatedEvent.Errors == null && rowUpdatedEvent.Status == UpdateStatus.Continue && 0 < num && (rowUpdatedEvent.RecordsAffected == 0 || flag))
        {
            DataRow[] array = ((list != null) ? list.ToArray() : rowUpdatedEvent.Rows);
            rowUpdatedEvent.Errors = ADP.UpdateConcurrencyViolation(StatementType.Batch, commandCount - array.Length, commandCount, array);
            rowUpdatedEvent.Status = UpdateStatus.ErrorsOccurred;
        }
    }
References System.array, System.Data.Common.DbDataAdapter.ExecuteBatch(), System.Data.Common.DbDataAdapter.GetBatchedParameter(), System.Data.Common.DbDataAdapter.GetBatchedRecordsAffected(), System.list, System.Data.Common.DbDataAdapter.ParameterOutput(), System.Data.Common.ADP.TraceExceptionForCapture(), System.Data.Common.ADP.UpdateConcurrencyViolation(), System.Data.Common.DbDataAdapter.UpdateMappingAction, and System.Data.Common.DbDataAdapter.UpdateSchemaAction.
Referenced by System.Data.Common.DbDataAdapter.Update().