Terraria: System.Data.Common.DbDataAdapter.Fill
Fill() [10/11]
virtual int System.Data.Common.DbDataAdapter.Fill (DataTable[] dataTables, int startRecord, int maxRecords, IDbCommand command, CommandBehavior behavior) inline protected virtual
Definition at line 538 of file DbDataAdapter.cs.
    {
        long scopeId = DataCommonEventSource.Log.EnterScope("<comm.DbDataAdapter.Fill|API> {0}, dataTables[], startRecord, maxRecords, command, behavior={1}", base.ObjectID, behavior);
        try
        {
            if (dataTables == null || dataTables.Length == 0 || dataTables[0] == null)
            {
                throw ADP.FillRequires("dataTable");
            }
            if (startRecord < 0)
            {
                throw ADP.InvalidStartRecord("startRecord", startRecord);
            }
            if (maxRecords < 0)
            {
                throw ADP.InvalidMaxRecords("maxRecords", maxRecords);
            }
            if (1 < dataTables.Length && (startRecord != 0 || maxRecords != 0))
            {
                throw ADP.OnlyOneTableForStartRecordOrMaxRecords();
            }
            if (command == null)
            {
                throw ADP.MissingSelectCommand("Fill");
            }
            if (1 == dataTables.Length)
            {
                behavior |= CommandBehavior.SingleResult;
            }
            return FillInternal(null, dataTables, startRecord, maxRecords, null, command, behavior);
        }
        finally
        {
            DataCommonEventSource.Log.ExitScope(scopeId);
        }
    }
References System.Data.Common.DbDataAdapter.FillInternal(), System.Data.Common.ADP.FillRequires(), System.Data.Common.ADP.InvalidMaxRecords(), System.Data.Common.ADP.InvalidStartRecord(), System.Data.DataCommonEventSource.Log, System.Data.Common.ADP.MissingSelectCommand(), and System.Data.Common.ADP.OnlyOneTableForStartRecordOrMaxRecords().