Terraria: System.Data.Common.DbDataAdapter.ParameterInput
ParameterInput()
void System.Data.Common.DbDataAdapter.ParameterInput (IDataParameterCollection parameters, StatementType typeIndex, DataRow row, DataTableMapping mappings) inline private
Definition at line 683 of file DbDataAdapter.cs.
    {
        MissingMappingAction updateMappingAction = UpdateMappingAction;
        MissingSchemaAction updateSchemaAction = UpdateSchemaAction;
        foreach (IDataParameter parameter in parameters)
        {
            if (parameter == null || (ParameterDirection.Input & parameter.Direction) == 0)
            {
                continue;
            }
            string sourceColumn = parameter.SourceColumn;
            if (!string.IsNullOrEmpty(sourceColumn))
            {
                DataColumn dataColumn = mappings.GetDataColumn(sourceColumn, null, row.Table, updateMappingAction, updateSchemaAction);
                if (dataColumn != null)
                {
                    DataRowVersion parameterSourceVersion = GetParameterSourceVersion(typeIndex, parameter);
                    parameter.Value = row[dataColumn, parameterSourceVersion];
                }
                else
                {
                    parameter.Value = null;
                }
                if (parameter is DbParameter { SourceColumnNullMapping: not false })
                {
                    parameter.Value = (ADP.IsNull(parameter.Value) ? s_parameterValueNullValue : s_parameterValueNonNullValue);
                }
            }
        }
    }
References System.Data.Common.DbDataAdapter.GetParameterSourceVersion(), System.Data.Common.ADP.IsNull(), System.Data.Common.DbDataAdapter.s_parameterValueNonNullValue, System.Data.Common.DbDataAdapter.s_parameterValueNullValue, System.Data.Common.DbDataAdapter.UpdateMappingAction, and System.Data.Common.DbDataAdapter.UpdateSchemaAction.
Referenced by System.Data.Common.DbDataAdapter.Update().