Terraria: System.Data.Common.DbDataAdapter.Fill
Fill() [3/11]
virtual int System.Data.Common.DbDataAdapter.Fill (DataSet dataSet, int startRecord, int maxRecords, string srcTable, IDbCommand command, CommandBehavior behavior) inline protected virtual
Definition at line 460 of file DbDataAdapter.cs.
    {
        long scopeId = DataCommonEventSource.Log.EnterScope("<comm.DbDataAdapter.Fill|API> {0}, dataSet, startRecord, maxRecords, srcTable, command, behavior={1}", base.ObjectID, behavior);
        try
        {
            if (dataSet == null)
            {
                throw ADP.FillRequires("dataSet");
            }
            if (startRecord < 0)
            {
                throw ADP.InvalidStartRecord("startRecord", startRecord);
            }
            if (maxRecords < 0)
            {
                throw ADP.InvalidMaxRecords("maxRecords", maxRecords);
            }
            if (string.IsNullOrEmpty(srcTable))
            {
                throw ADP.FillRequiresSourceTableName("srcTable");
            }
            if (command == null)
            {
                throw ADP.MissingSelectCommand("Fill");
            }
            return FillInternal(dataSet, null, startRecord, maxRecords, srcTable, command, behavior);
        }
        finally
        {
            DataCommonEventSource.Log.ExitScope(scopeId);
        }
    }
References System.Data.Common.DbDataAdapter.FillInternal(), System.Data.Common.ADP.FillRequires(), System.Data.Common.ADP.FillRequiresSourceTableName(), System.Data.Common.ADP.InvalidMaxRecords(), System.Data.Common.ADP.InvalidStartRecord(), System.Data.DataCommonEventSource.Log, and System.Data.Common.ADP.MissingSelectCommand().