Terraria: System.Data.Common.DbDataAdapter.Update
Update() [5/5]
int System.Data.Common.DbDataAdapter.Update (DataTable dataTable) inline
Definition at line 815 of file DbDataAdapter.cs.
    {
        long scopeId = DataCommonEventSource.Log.EnterScope("<comm.DbDataAdapter.Update|API> {0}, dataTable", base.ObjectID);
        try
        {
            if (dataTable == null)
            {
                throw ADP.UpdateRequiresDataTable("dataTable");
            }
            DataTableMapping dataTableMapping = null;
            int num = IndexOfDataSetTable(dataTable.TableName);
            if (-1 != num)
            {
                dataTableMapping = base.TableMappings[num];
            }
            if (dataTableMapping == null)
            {
                if (MissingMappingAction.Error == base.MissingMappingAction)
                {
                    throw ADP.MissingTableMappingDestination(dataTable.TableName);
                }
                dataTableMapping = new DataTableMapping("Table", dataTable.TableName);
            }
            return UpdateFromDataTable(dataTable, dataTableMapping);
        }
        finally
        {
            DataCommonEventSource.Log.ExitScope(scopeId);
        }
    }
References System.Data.Common.DataAdapter.IndexOfDataSetTable(), System.Data.DataCommonEventSource.Log, System.Data.Common.ADP.MissingTableMappingDestination(), System.Data.Common.DbDataAdapter.UpdateFromDataTable(), and System.Data.Common.ADP.UpdateRequiresDataTable().