Terraria: System.Data.Common.DbDataAdapter.GetTableMapping
GetTableMapping()
DataTableMapping System.Data.Common.DbDataAdapter.GetTableMapping (DataTable dataTable) inline package
Definition at line 651 of file DbDataAdapter.cs.
    {
        DataTableMapping dataTableMapping = null;
        int num = IndexOfDataSetTable(dataTable.TableName);
        if (-1 != num)
        {
            dataTableMapping = base.TableMappings[num];
        }
        if (dataTableMapping == null)
        {
            if (MissingMappingAction.Error == base.MissingMappingAction)
            {
                throw ADP.MissingTableMappingDestination(dataTable.TableName);
            }
            dataTableMapping = new DataTableMapping(dataTable.TableName, dataTable.TableName);
        }
        return dataTableMapping;
    }
References System.Data.Common.DataAdapter.IndexOfDataSetTable(), and System.Data.Common.ADP.MissingTableMappingDestination().
Referenced by System.Data.Common.DbCommandBuilder.GetTableMapping(), and System.Data.Common.DbDataAdapter.Update().