Terraria: System.Data.Common.DbDataAdapter.FillInternal
FillInternal()
int System.Data.Common.DbDataAdapter.FillInternal (DataSet dataset, DataTable[] datatables, int startRecord, int maxRecords, string srcTable, IDbCommand command, CommandBehavior behavior) inline private
Definition at line 575 of file DbDataAdapter.cs.
    {
        int result = 0;
        bool flag = command.Connection == null;
        try
        {
            IDbConnection connection = GetConnection3(this, command, "Fill");
            ConnectionState originalState = ConnectionState.Open;
            if (MissingSchemaAction.AddWithKey == base.MissingSchemaAction)
            {
                behavior |= CommandBehavior.KeyInfo;
            }
            try
            {
                QuietOpen(connection, out originalState);
                behavior |= CommandBehavior.SequentialAccess;
                IDataReader dataReader = null;
                try
                {
                    dataReader = command.ExecuteReader(behavior);
                    result = ((datatables == null) ? Fill(dataset, srcTable, dataReader, startRecord, maxRecords) : Fill(datatables, dataReader, startRecord, maxRecords));
                }
                finally
                {
                    dataReader?.Dispose();
                }
            }
            finally
            {
                QuietClose(connection, originalState);
            }
        }
        finally
        {
            if (flag)
            {
                command.Transaction = null;
                command.Connection = null;
            }
        }
        return result;
    }
References System.ComponentModel.Fill, System.Data.Common.DbDataAdapter.GetConnection3(), System.Data.Common.DbDataAdapter.QuietClose(), and System.Data.Common.DbDataAdapter.QuietOpen().
Referenced by System.Data.Common.DbDataAdapter.Fill(), and System.Data.Common.DbDataAdapter.Fill().