Terraria: System.Xml.Xsl.XsltOld.Avt.Evaluate
Evaluate()
string System.Xml.Xsl.XsltOld.Avt.Evaluate (Processor processor, ActionFrame frame) inline package
Definition at line 37 of file Avt.cs.
    {
        if (IsConstant)
        {
            return _constAvt;
        }
        StringBuilder sharedStringBuilder = processor.GetSharedStringBuilder();
        for (int i = 0; i < _events.Length; i++)
        {
            sharedStringBuilder.Append(_events[i].Evaluate(processor, frame));
        }
        processor.ReleaseSharedStringBuilder();
        return sharedStringBuilder.ToString();
    }
References System.Xml.Xsl.XsltOld.Avt._constAvt, System.Xml.Xsl.XsltOld.Avt._events, System.Text.StringBuilder.Append(), System.Xml.Dictionary, System.Xml.Xsl.XsltOld.Avt.Evaluate(), System.Xml.Xsl.XsltOld.Avt.IsConstant, and System.Text.StringBuilder.ToString().
Referenced by System.Xml.Xsl.XsltOld.ProcessingInstructionAction.Compile(), System.Xml.Xsl.XsltOld.Avt.Evaluate(), System.Xml.Xsl.XsltOld.AttributeAction.Execute(), System.Xml.Xsl.XsltOld.ElementAction.Execute(), System.Xml.Xsl.XsltOld.NumberAction.Execute(), System.Xml.Xsl.XsltOld.ProcessingInstructionAction.Execute(), and System.Xml.Xsl.XsltOld.SortAction.Execute().