Terraria: System.Xml.Xsl.XsltOld.Avt.CompileAvt
CompileAvt()
static Avt System.Xml.Xsl.XsltOld.Avt.CompileAvt (Compiler compiler, string avtText) inline static package
Definition at line 52 of file Avt.cs.
    {
        bool constant;
        ArrayList eventList = compiler.CompileAvt(avtText, out constant);
        if (!constant)
        {
            return new Avt(eventList);
        }
        return new Avt(avtText);
    }
References System.Xml.Xsl.XsltOld.Avt.Avt(), and System.Xml.Dictionary.
Referenced by System.Xml.Xsl.XsltOld.AttributeAction.CompileAttribute(), System.Xml.Xsl.XsltOld.ElementAction.CompileAttribute(), System.Xml.Xsl.XsltOld.NumberAction.CompileAttribute(), System.Xml.Xsl.XsltOld.ProcessingInstructionAction.CompileAttribute(), and System.Xml.Xsl.XsltOld.SortAction.CompileAttribute().