Terraria: Terraria.GameContent.SmartCursorHelper.Step_MulticolorWrench
Step_MulticolorWrench()
static void Terraria.GameContent.SmartCursorHelper.Step_MulticolorWrench (SmartCursorUsageInfo providedInfo, ref int focusedX, ref int focusedY) inline static private
Definition at line 1669 of file SmartCursorHelper.cs.
    {
        if (providedInfo.item.type != 3625 || focusedX != -1 || focusedY != -1)
        {
            return;
        }
        _targets.Clear();
        WiresUI.Settings.MultiToolMode toolMode = WiresUI.Settings.ToolMode;
        WiresUI.Settings.MultiToolMode multiToolMode = (WiresUI.Settings.MultiToolMode)0;
        if (Main.tile[providedInfo.screenTargetX, providedInfo.screenTargetY].wire())
        {
            multiToolMode |= WiresUI.Settings.MultiToolMode.Red;
        }
        if (Main.tile[providedInfo.screenTargetX, providedInfo.screenTargetY].wire2())
        {
            multiToolMode |= WiresUI.Settings.MultiToolMode.Blue;
        }
        if (Main.tile[providedInfo.screenTargetX, providedInfo.screenTargetY].wire3())
        {
            multiToolMode |= WiresUI.Settings.MultiToolMode.Green;
        }
        if (Main.tile[providedInfo.screenTargetX, providedInfo.screenTargetY].wire4())
        {
            multiToolMode |= WiresUI.Settings.MultiToolMode.Yellow;
        }
        toolMode &= ~WiresUI.Settings.MultiToolMode.Cutter;
        bool num = toolMode == multiToolMode;
        toolMode = WiresUI.Settings.ToolMode;
        if (!num)
        {
            bool flag = toolMode.HasFlag(WiresUI.Settings.MultiToolMode.Red);
            bool flag2 = toolMode.HasFlag(WiresUI.Settings.MultiToolMode.Blue);
            bool flag3 = toolMode.HasFlag(WiresUI.Settings.MultiToolMode.Green);
            bool flag4 = toolMode.HasFlag(WiresUI.Settings.MultiToolMode.Yellow);
            bool flag5 = toolMode.HasFlag(WiresUI.Settings.MultiToolMode.Cutter);
            for (int i = providedInfo.reachableStartX; i <= providedInfo.reachableEndX; i++)
            {
                for (int j = providedInfo.reachableStartY; j <= providedInfo.reachableEndY; j++)
                {
                    Tile tile = Main.tile[i, j];
                    if (flag5)
                    {
                        if ((tile.wire() && flag) || (tile.wire2() && flag2) || (tile.wire3() && flag3) || (tile.wire4() && flag4))
{
                            _targets.Add(new Tuple<int, int>(i, j));
                        }
                    }
                    else
                    {
                        if (!(tile.wire() && flag) && !(tile.wire2() && flag2) && !(tile.wire3() && flag3) && !(tile.wire4() && flag4))
{
                            continue;
                        }
                        if (flag)
{
                            if (!Main.tile[i - 1, j].wire())
{
                                _targets.Add(new Tuple<int, int>(i - 1, j));
                            }
                            if (!Main.tile[i + 1, j].wire())
{
                                _targets.Add(new Tuple<int, int>(i + 1, j));
                            }
                            if (!Main.tile[i, j - 1].wire())
{
                                _targets.Add(new Tuple<int, int>(i, j - 1));
                            }
                            if (!Main.tile[i, j + 1].wire())
{
                                _targets.Add(new Tuple<int, int>(i, j + 1));
                            }
                        }
                        if (flag2)
{
                            if (!Main.tile[i - 1, j].wire2())
{
                                _targets.Add(new Tuple<int, int>(i - 1, j));
                            }
                            if (!Main.tile[i + 1, j].wire2())
{
                                _targets.Add(new Tuple<int, int>(i + 1, j));
                            }
                            if (!Main.tile[i, j - 1].wire2())
{
                                _targets.Add(new Tuple<int, int>(i, j - 1));
                            }
                            if (!Main.tile[i, j + 1].wire2())
{
                                _targets.Add(new Tuple<int, int>(i, j + 1));
                            }
                        }
                        if (flag3)
{
                            if (!Main.tile[i - 1, j].wire3())
{
                                _targets.Add(new Tuple<int, int>(i - 1, j));
                            }
                            if (!Main.tile[i + 1, j].wire3())
{
                                _targets.Add(new Tuple<int, int>(i + 1, j));
                            }
                            if (!Main.tile[i, j - 1].wire3())
{
                                _targets.Add(new Tuple<int, int>(i, j - 1));
                            }
                            if (!Main.tile[i, j + 1].wire3())
{
                                _targets.Add(new Tuple<int, int>(i, j + 1));
                            }
                        }
                        if (flag4)
{
                            if (!Main.tile[i - 1, j].wire4())
{
                                _targets.Add(new Tuple<int, int>(i - 1, j));
                            }
                            if (!Main.tile[i + 1, j].wire4())
{
                                _targets.Add(new Tuple<int, int>(i + 1, j));
                            }
                            if (!Main.tile[i, j - 1].wire4())
{
                                _targets.Add(new Tuple<int, int>(i, j - 1));
                            }
                            if (!Main.tile[i, j + 1].wire4())
{
                                _targets.Add(new Tuple<int, int>(i, j + 1));
                            }
                        }
                    }
                }
            }
        }
        if (_targets.Count > 0)
        {
            float num2 = -1f;
            Tuple<int, int> tuple = _targets[0];
            for (int k = 0; k < _targets.Count; k++)
            {
                float num3 = Vector2.Distance(new Vector2(_targets[k].Item1, _targets[k].Item2) * 16f + Vector2.One * 8f, providedInfo.mouse);
                if (num2 == -1f || num3 < num2)
                {
                    num2 = num3;
                    tuple = _targets[k];
                }
            }
            if (Collision.InTileBounds(tuple.Item1, tuple.Item2, providedInfo.reachableStartX, providedInfo.reachableStartY, providedInfo.reachableEndX, providedInfo.reachableEndY))
            {
                focusedX = tuple.Item1;
                focusedY = tuple.Item2;
            }
        }
        _targets.Clear();
    }
References Terraria.GameContent.SmartCursorHelper._targets, Terraria.Collision.InTileBounds(), Terraria.GameContent.SmartCursorHelper.SmartCursorUsageInfo.item, Terraria.GameContent.SmartCursorHelper.SmartCursorUsageInfo.mouse, Terraria.GameContent.SmartCursorHelper.SmartCursorUsageInfo.reachableEndX, Terraria.GameContent.SmartCursorHelper.SmartCursorUsageInfo.reachableEndY, Terraria.GameContent.SmartCursorHelper.SmartCursorUsageInfo.reachableStartX, Terraria.GameContent.SmartCursorHelper.SmartCursorUsageInfo.reachableStartY, Terraria.GameContent.SmartCursorHelper.SmartCursorUsageInfo.screenTargetX, Terraria.GameContent.SmartCursorHelper.SmartCursorUsageInfo.screenTargetY, Terraria.Main.tile, Terraria.GameContent.UI.WiresUI.Settings.ToolMode, Terraria.Item.type, Terraria.Tile.wire(), Terraria.Tile.wire2(), Terraria.Tile.wire3(), and Terraria.Tile.wire4().
Referenced by Terraria.GameContent.SmartCursorHelper.SmartCursorLookup().