Terraria: Terraria.GameContent.SmartCursorHelper.Step_BlocksLines
Step_BlocksLines()
static void Terraria.GameContent.SmartCursorHelper.Step_BlocksLines (SmartCursorUsageInfo providedInfo, ref int focusedX, ref int focusedY) inline static private
Definition at line 787 of file SmartCursorHelper.cs.
    {
        int type = providedInfo.item.type;
        if (type < 0 || type >= ItemID.Count || !Player.SmartCursorSettings.SmartBlocksEnabled || providedInfo.item.createTile <= -1 || type == 213 || type == 5295 || ItemID.Sets.GrassSeeds[type] || !Main.tileSolid[providedInfo.item.createTile] || Main.tileSolidTop[providedInfo.item.createTile] || Main.tileFrameImportant[providedInfo.item.createTile] || focusedX != -1 || focusedY != -1)
        {
            return;
        }
        _targets.Clear();
        bool flag = false;
        if (Main.tile[providedInfo.screenTargetX, providedInfo.screenTargetY].active())
        {
            flag = true;
        }
        if (!Collision.InTileBounds(providedInfo.screenTargetX, providedInfo.screenTargetY, providedInfo.reachableStartX, providedInfo.reachableStartY, providedInfo.reachableEndX, providedInfo.reachableEndY))
        {
            flag = true;
        }
        if (!flag)
        {
            for (int i = providedInfo.reachableStartX; i <= providedInfo.reachableEndX; i++)
            {
                for (int j = providedInfo.reachableStartY; j <= providedInfo.reachableEndY; j++)
                {
                    Tile tile = Main.tile[i, j];
                    if (!tile.active() || Main.tileCut[tile.type] || TileID.Sets.BreakableWhenPlacing[tile.type])
                    {
                        bool flag2 = false;
                        if (Main.tile[i - 1, j].active() && Main.tileSolid[Main.tile[i - 1, j].type] && !Main.tileSolidTop[Main.tile[i - 1, j].type])
{
                            flag2 = true;
                        }
                        if (Main.tile[i + 1, j].active() && Main.tileSolid[Main.tile[i + 1, j].type] && !Main.tileSolidTop[Main.tile[i + 1, j].type])
{
                            flag2 = true;
                        }
                        if (Main.tile[i, j - 1].active() && Main.tileSolid[Main.tile[i, j - 1].type] && !Main.tileSolidTop[Main.tile[i, j - 1].type])
{
                            flag2 = true;
                        }
                        if (Main.tile[i, j + 1].active() && Main.tileSolid[Main.tile[i, j + 1].type] && !Main.tileSolidTop[Main.tile[i, j + 1].type])
{
                            flag2 = true;
                        }
                        if (flag2)
{
                            _targets.Add(new Tuple<int, int>(i, j));
                        }
                    }
                }
            }
        }
        if (_targets.Count > 0)
        {
            float num = -1f;
            Tuple<int, int> tuple = _targets[0];
            for (int k = 0; k < _targets.Count; k++)
            {
                if (Collision.EmptyTile(_targets[k].Item1, _targets[k].Item2))
                {
                    float num2 = Vector2.Distance(new Vector2(_targets[k].Item1, _targets[k].Item2) * 16f + Vector2.One * 8f, providedInfo.mouse);
                    if (num == -1f || num2 < num)
                    {
                        num = num2;
                        tuple = _targets[k];
                    }
                }
            }
            if (Collision.InTileBounds(tuple.Item1, tuple.Item2, providedInfo.reachableStartX, providedInfo.reachableStartY, providedInfo.reachableEndX, providedInfo.reachableEndY) && num != -1f)
            {
                focusedX = tuple.Item1;
                focusedY = tuple.Item2;
            }
        }
        _targets.Clear();
    }
References Terraria.GameContent.SmartCursorHelper._targets, Terraria.Tile.active(), Terraria.ID.TileID.Sets.BreakableWhenPlacing, Terraria.ID.ItemID.Count, Microsoft.Xna.Framework.Vector2.Distance(), Terraria.Collision.EmptyTile(), Terraria.ID.ItemID.Sets.GrassSeeds, Terraria.Collision.InTileBounds(), Terraria.Player.SmartCursorSettings.SmartBlocksEnabled, Terraria.Main.tile, Terraria.Main.tileCut, Terraria.Main.tileFrameImportant, Terraria.Main.tileSolid, Terraria.Main.tileSolidTop, System.type, and Terraria.Tile.type.
Referenced by Terraria.GameContent.SmartCursorHelper.SmartCursorLookup().