Terraria: Terraria.GameContent.SmartCursorHelper.Step_PumpkinSeeds
Step_PumpkinSeeds()
static void Terraria.GameContent.SmartCursorHelper.Step_PumpkinSeeds (SmartCursorUsageInfo providedInfo, ref int focusedX, ref int focusedY) inline static private
    {
        if (providedInfo.item.createTile != 254 || focusedX != -1 || focusedY != -1)
        {
            return;
        }
        _targets.Clear();
        for (int i = providedInfo.reachableStartX; i <= providedInfo.reachableEndX; i++)
        {
            for (int j = providedInfo.reachableStartY; j <= providedInfo.reachableEndY; j++)
            {
                Tile tile = Main.tile[i, j + 1];
                Tile tile2 = Main.tile[i + 1, j + 1];
                if ((double)j > Main.worldSurface - 2.0)
                {
                    break;
                }
                bool flag = true;
                if (!tile2.active() || !tile.active())
                {
                    flag = false;
                }
                if (tile2.slope() > 0 || tile.slope() > 0 || tile2.halfBrick() || tile.halfBrick())
                {
                    flag = false;
                }
                if (tile2.type != 2 && tile2.type != 477 && tile2.type != 109 && tile2.type != 492)
                {
                    flag = false;
                }
                if (tile.type != 2 && tile.type != 477 && tile.type != 109 && tile.type != 492)
                {
                    flag = false;
                }
                for (int k = i; k <= i + 1; k++)
                {
                    for (int l = j - 1; l <= j; l++)
                    {
                        Tile tile3 = Main.tile[k, l];
                        if (tile3.active() && (tile3.type < 0 || tile3.type >= TileID.Count || Main.tileSolid[tile3.type] || !WorldGen.CanCutTile(k, l, TileCuttingContext.TilePlacement)))
{
                            flag = false;
                        }
                    }
                }
                if (flag)
                {
                    _targets.Add(new Tuple<int, int>(i, j));
                }
            }
        }
        if (_targets.Count > 0)
        {
            float num = -1f;
            Tuple<int, int> tuple = _targets[0];
            for (int m = 0; m < _targets.Count; m++)
            {
                float num2 = Vector2.Distance(new Vector2(_targets[m].Item1, _targets[m].Item2) * 16f + Vector2.One * 8f, providedInfo.mouse);
                if (num == -1f || num2 < num)
                {
                    num = num2;
                    tuple = _targets[m];
                }
            }
            if (Collision.InTileBounds(tuple.Item1, tuple.Item2, providedInfo.reachableStartX, providedInfo.reachableStartY, providedInfo.reachableEndX, providedInfo.reachableEndY))
            {
                focusedX = tuple.Item1;
                focusedY = tuple.Item2;
            }
        }
        _targets.Clear();
    }
References Terraria.GameContent.SmartCursorHelper._targets, Terraria.Tile.active(), Terraria.WorldGen.CanCutTile(), Terraria.Item.createTile, Terraria.Tile.halfBrick(), Terraria.Collision.InTileBounds(), Terraria.GameContent.SmartCursorHelper.SmartCursorUsageInfo.item, Terraria.GameContent.SmartCursorHelper.SmartCursorUsageInfo.mouse, Terraria.GameContent.SmartCursorHelper.SmartCursorUsageInfo.reachableEndX, Terraria.GameContent.SmartCursorHelper.SmartCursorUsageInfo.reachableEndY, Terraria.GameContent.SmartCursorHelper.SmartCursorUsageInfo.reachableStartX, Terraria.GameContent.SmartCursorHelper.SmartCursorUsageInfo.reachableStartY, Terraria.Tile.slope(), Terraria.Main.tile, Terraria.Main.tileSolid, and Terraria.Tile.type.
Referenced by Terraria.GameContent.SmartCursorHelper.SmartCursorLookup().