Terraria: Terraria.GameContent.SmartCursorHelper.Step_GemCorns
Step_GemCorns()
static void Terraria.GameContent.SmartCursorHelper.Step_GemCorns (SmartCursorUsageInfo providedInfo, ref int focusedX, ref int focusedY) inline static private
Definition at line 2094 of file SmartCursorHelper.cs.
    {
        if (!WorldGen.GrowTreeSettings.Profiles.TryGetFromItemId(providedInfo.item.type, out var profile) || focusedX != -1 || focusedY != -1 || providedInfo.reachableStartY <= 20)
        {
            return;
        }
        _targets.Clear();
        for (int i = providedInfo.reachableStartX; i <= providedInfo.reachableEndX; i++)
        {
            for (int j = providedInfo.reachableStartY; j <= providedInfo.reachableEndY; j++)
            {
                Tile tile = Main.tile[i, j];
                Tile tile2 = Main.tile[i, j - 1];
                Tile tile3 = Main.tile[i, j + 1];
                Tile tile4 = Main.tile[i - 1, j];
                Tile tile5 = Main.tile[i + 1, j];
                Tile tile6 = Main.tile[i - 2, j];
                Tile tile7 = Main.tile[i + 2, j];
                Tile tile8 = Main.tile[i - 3, j];
                Tile tile9 = Main.tile[i + 3, j];
                if (profile.GroundTest(tile3.type) && (!tile.active() || Main.tileCut[tile.type] || TileID.Sets.BreakableWhenPlacing[tile.type]) && (!tile2.active() || Main.tileCut[tile2.type] || TileID.Sets.BreakableWhenPlacing[tile2.type]) && (!tile4.active() || !TileID.Sets.CommonSapling[tile4.type]) && (!tile5.active() || !TileID.Sets.CommonSapling[tile5.type]) && (!tile6.active() || !TileID.Sets.CommonSapling[tile6.type]) && (!tile7.active() || !TileID.Sets.CommonSapling[tile7.type]) && (!tile8.active() || !TileID.Sets.CommonSapling[tile8.type]) && (!tile9.active() || !TileID.Sets.CommonSapling[tile9.type]) && tile3.active() && WorldGen.SolidTile2(tile3) && tile4.liquid == 0 && tile.liquid == 0 && tile5.liquid == 0 && WorldGen.EmptyTileCheck(i - 2, i + 2, j - profile.TreeHeightMax, j, profile.SaplingTileType))
                {
                    _targets.Add(new Tuple<int, int>(i, j));
                }
            }
        }
        _toRemove.Clear();
        for (int k = 0; k < _targets.Count; k++)
        {
            bool flag = false;
            for (int l = -1; l < 2; l += 2)
            {
                Tile tile10 = Main.tile[_targets[k].Item1 + l, _targets[k].Item2 + 1];
                if (tile10.active() && profile.GroundTest(tile10.type))
                {
                    flag = true;
                }
            }
            if (!flag)
            {
                _toRemove.Add(_targets[k]);
            }
        }
        for (int m = 0; m < _toRemove.Count; m++)
        {
            _targets.Remove(_toRemove[m]);
        }
        _toRemove.Clear();
        if (_targets.Count > 0)
        {
            float num = -1f;
            Tuple<int, int> tuple = _targets[0];
            for (int n = 0; n < _targets.Count; n++)
            {
                float num2 = Vector2.Distance(new Vector2(_targets[n].Item1, _targets[n].Item2) * 16f + Vector2.One * 8f, providedInfo.mouse);
                if (num == -1f || num2 < num)
                {
                    num = num2;
                    tuple = _targets[n];
                }
            }
            if (Collision.InTileBounds(tuple.Item1, tuple.Item2, providedInfo.reachableStartX, providedInfo.reachableStartY, providedInfo.reachableEndX, providedInfo.reachableEndY))
            {
                focusedX = tuple.Item1;
                focusedY = tuple.Item2;
            }
        }
        _targets.Clear();
    }
References Terraria.GameContent.SmartCursorHelper._targets, Terraria.GameContent.SmartCursorHelper._toRemove, Terraria.Tile.active(), Terraria.ID.TileID.Sets.BreakableWhenPlacing, Terraria.ID.TileID.Sets.CommonSapling, Terraria.WorldGen.EmptyTileCheck(), Terraria.Collision.InTileBounds(), Terraria.GameContent.SmartCursorHelper.SmartCursorUsageInfo.item, Terraria.GameContent.SmartCursorHelper.SmartCursorUsageInfo.mouse, Terraria.GameContent.SmartCursorHelper.SmartCursorUsageInfo.reachableEndX, Terraria.GameContent.SmartCursorHelper.SmartCursorUsageInfo.reachableEndY, Terraria.GameContent.SmartCursorHelper.SmartCursorUsageInfo.reachableStartX, Terraria.GameContent.SmartCursorHelper.SmartCursorUsageInfo.reachableStartY, Terraria.WorldGen.SolidTile2(), Terraria.Main.tile, Terraria.Main.tileCut, Terraria.WorldGen.GrowTreeSettings.Profiles.TryGetFromItemId(), Terraria.Item.type, and Terraria.Tile.type.
Referenced by Terraria.GameContent.SmartCursorHelper.SmartCursorLookup().