Terraria: Terraria.GameContent.SmartCursorHelper.Step_Axe
Step_Axe()
static void Terraria.GameContent.SmartCursorHelper.Step_Axe (SmartCursorUsageInfo providedInfo, ref int fX, ref int fY) inline static private
    {
        int reachableStartX = providedInfo.reachableStartX;
        int reachableStartY = providedInfo.reachableStartY;
        int reachableEndX = providedInfo.reachableEndX;
        int reachableEndY = providedInfo.reachableEndY;
        _ = providedInfo.screenTargetX;
        _ = providedInfo.screenTargetY;
        if (providedInfo.item.axe <= 0 || fX != -1 || fY != -1)
        {
            return;
        }
        float num = -1f;
        for (int i = reachableStartX; i <= reachableEndX; i++)
        {
            for (int j = reachableStartY; j <= reachableEndY; j++)
            {
                if (!Main.tile[i, j].active())
                {
                    continue;
                }
                Tile tile = Main.tile[i, j];
                if (!Main.tileAxe[tile.type] || TileID.Sets.IgnoreSmartCursorPriorityAxe[tile.type])
                {
                    continue;
                }
                int num2 = i;
                int k = j;
                int type = tile.type;
                if (TileID.Sets.IsATreeTrunk[type])
                {
                    if (Collision.InTileBounds(num2 + 1, k, reachableStartX, reachableStartY, reachableEndX, reachableEndY))
                    {
                        if (Main.tile[num2, k].frameY >= 198 && Main.tile[num2, k].frameX == 44)
{
                            num2++;
                        }
                        if (Main.tile[num2, k].frameX == 66 && Main.tile[num2, k].frameY <= 44)
{
                            num2++;
                        }
                        if (Main.tile[num2, k].frameX == 44 && Main.tile[num2, k].frameY >= 132 && Main.tile[num2, k].frameY <= 176)
{
                            num2++;
                        }
                    }
                    if (Collision.InTileBounds(num2 - 1, k, reachableStartX, reachableStartY, reachableEndX, reachableEndY))
                    {
                        if (Main.tile[num2, k].frameY >= 198 && Main.tile[num2, k].frameX == 66)
{
                            num2--;
                        }
                        if (Main.tile[num2, k].frameX == 88 && Main.tile[num2, k].frameY >= 66 && Main.tile[num2, k].frameY <= 110)
{
                            num2--;
                        }
                        if (Main.tile[num2, k].frameX == 22 && Main.tile[num2, k].frameY >= 132 && Main.tile[num2, k].frameY <= 176)
{
                            num2--;
                        }
                    }
                    for (; Main.tile[num2, k].active() && Main.tile[num2, k].type == type && Main.tile[num2, k + 1].type == type && Collision.InTileBounds(num2, k + 1, reachableStartX, reachableStartY, reachableEndX, reachableEndY); k++)
                    {
                    }
                }
                if (tile.type == 80)
                {
                    if (Collision.InTileBounds(num2 + 1, k, reachableStartX, reachableStartY, reachableEndX, reachableEndY))
                    {
                        if (Main.tile[num2, k].frameX == 54)
{
                            num2++;
                        }
                        if (Main.tile[num2, k].frameX == 108 && Main.tile[num2, k].frameY == 36)
{
                            num2++;
                        }
                    }
                    if (Collision.InTileBounds(num2 - 1, k, reachableStartX, reachableStartY, reachableEndX, reachableEndY))
                    {
                        if (Main.tile[num2, k].frameX == 36)
{
                            num2--;
                        }
                        if (Main.tile[num2, k].frameX == 108 && Main.tile[num2, k].frameY == 18)
{
                            num2--;
                        }
                    }
                    for (; Main.tile[num2, k].active() && Main.tile[num2, k].type == 80 && Main.tile[num2, k + 1].type == 80 && Collision.InTileBounds(num2, k + 1, reachableStartX, reachableStartY, reachableEndX, reachableEndY); k++)
                    {
                    }
                }
                if (tile.type == 323 || tile.type == 72)
                {
                    for (; Main.tile[num2, k].active() && ((Main.tile[num2, k].type == 323 && Main.tile[num2, k + 1].type == 323) || (Main.tile[num2, k].type == 72 && Main.tile[num2, k + 1].type == 72)) && Collision.InTileBounds(num2, k + 1, reachableStartX, reachableStartY, reachableEndX, reachableEndY); k++)
                    {
                    }
                }
                float num3 = Vector2.Distance(new Vector2(num2, k) * 16f + Vector2.One * 8f, providedInfo.mouse);
                if (num == -1f || num3 < num)
                {
                    num = num3;
                    fX = num2;
                    fY = k;
                }
            }
        }
    }
References Terraria.Tile.active(), Terraria.Item.axe, Terraria.Tile.frameX, Terraria.Tile.frameY, Terraria.ID.TileID.Sets.IgnoreSmartCursorPriorityAxe, Terraria.Collision.InTileBounds(), Terraria.ID.TileID.Sets.IsATreeTrunk, Terraria.GameContent.SmartCursorHelper.SmartCursorUsageInfo.item, Terraria.GameContent.SmartCursorHelper.SmartCursorUsageInfo.mouse, Terraria.GameContent.SmartCursorHelper.SmartCursorUsageInfo.reachableEndX, Terraria.GameContent.SmartCursorHelper.SmartCursorUsageInfo.reachableEndY, Terraria.GameContent.SmartCursorHelper.SmartCursorUsageInfo.reachableStartX, Terraria.GameContent.SmartCursorHelper.SmartCursorUsageInfo.reachableStartY, Terraria.GameContent.SmartCursorHelper.SmartCursorUsageInfo.screenTargetX, Terraria.GameContent.SmartCursorHelper.SmartCursorUsageInfo.screenTargetY, Terraria.Main.tile, Terraria.Main.tileAxe, and Terraria.Tile.type.
Referenced by Terraria.GameContent.SmartCursorHelper.SmartCursorLookup().