Terraria: Terraria.GameContent.SmartCursorHelper.Step_ForceCursorToAnyMinableThing
Step_ForceCursorToAnyMinableThing()
static void Terraria.GameContent.SmartCursorHelper.Step_ForceCursorToAnyMinableThing (SmartCursorUsageInfo providedInfo, ref int fX, ref int fY) inline static private
Definition at line 2164 of file SmartCursorHelper.cs.
    {
        int reachableStartX = providedInfo.reachableStartX;
        int reachableStartY = providedInfo.reachableStartY;
        int reachableEndX = providedInfo.reachableEndX;
        int reachableEndY = providedInfo.reachableEndY;
        _ = providedInfo.screenTargetX;
        _ = providedInfo.screenTargetY;
        Vector2 mouse = providedInfo.mouse;
        Item item = providedInfo.item;
        if (fX != -1 || fY != -1 || PlayerInput.UsingGamepad)
        {
            return;
        }
        Point point = mouse.ToTileCoordinates();
        int x = point.X;
        int y = point.Y;
        if (Collision.InTileBounds(x, y, reachableStartX, reachableStartY, reachableEndX, reachableEndY))
        {
            Tile tile = Main.tile[x, y];
            bool flag = tile.active() && WorldGen.CanKillTile(x, y) && (!Main.tileSolid[tile.type] || Main.tileSolidTop[tile.type]);
            if (flag && Main.tileAxe[tile.type] && item.axe < 1)
            {
                flag = false;
            }
            if (flag && Main.tileHammer[tile.type] && item.hammer < 1)
            {
                flag = false;
            }
            if (flag && !Main.tileHammer[tile.type] && !Main.tileAxe[tile.type] && item.pick < 1)
            {
                flag = false;
            }
            if (flag)
            {
                fX = x;
                fY = y;
            }
        }
    }
References Terraria.Tile.active(), Terraria.Item.axe, Terraria.WorldGen.CanKillTile(), Terraria.Item.hammer, Terraria.Collision.InTileBounds(), Terraria.GameContent.SmartCursorHelper.SmartCursorUsageInfo.item, Terraria.GameContent.SmartCursorHelper.SmartCursorUsageInfo.mouse, Terraria.Item.pick, Terraria.GameContent.SmartCursorHelper.SmartCursorUsageInfo.reachableEndX, Terraria.GameContent.SmartCursorHelper.SmartCursorUsageInfo.reachableEndY, Terraria.GameContent.SmartCursorHelper.SmartCursorUsageInfo.reachableStartX, Terraria.GameContent.SmartCursorHelper.SmartCursorUsageInfo.reachableStartY, Terraria.GameContent.SmartCursorHelper.SmartCursorUsageInfo.screenTargetX, Terraria.GameContent.SmartCursorHelper.SmartCursorUsageInfo.screenTargetY, Terraria.Main.tile, Terraria.Main.tileAxe, Terraria.Main.tileHammer, Terraria.Main.tileSolid, Terraria.Main.tileSolidTop, Terraria.Tile.type, and Terraria.GameInput.PlayerInput.UsingGamepad.
Referenced by Terraria.GameContent.SmartCursorHelper.SmartCursorLookup().