Terraria: Terraria.GameContent.SmartCursorHelper.Step_PlanterBox
Step_PlanterBox()
static void Terraria.GameContent.SmartCursorHelper.Step_PlanterBox (SmartCursorUsageInfo providedInfo, ref int focusedX, ref int focusedY) inline static private
    {
        if (providedInfo.item.createTile != 380 || focusedX != -1 || focusedY != -1)
        {
            return;
        }
        _targets.Clear();
        bool flag = false;
        if (Main.tile[providedInfo.screenTargetX, providedInfo.screenTargetY].active() && Main.tile[providedInfo.screenTargetX, providedInfo.screenTargetY].type == 380)
        {
            flag = true;
        }
        if (!flag)
        {
            for (int i = providedInfo.reachableStartX; i <= providedInfo.reachableEndX; i++)
            {
                for (int j = providedInfo.reachableStartY; j <= providedInfo.reachableEndY; j++)
                {
                    Tile tile = Main.tile[i, j];
                    if (tile.active() && tile.type == 380)
                    {
                        if (!Main.tile[i - 1, j].active() || Main.tileCut[Main.tile[i - 1, j].type] || TileID.Sets.BreakableWhenPlacing[Main.tile[i - 1, j].type])
{
                            _targets.Add(new Tuple<int, int>(i - 1, j));
                        }
                        if (!Main.tile[i + 1, j].active() || Main.tileCut[Main.tile[i + 1, j].type] || TileID.Sets.BreakableWhenPlacing[Main.tile[i + 1, j].type])
{
                            _targets.Add(new Tuple<int, int>(i + 1, j));
                        }
                    }
                }
            }
        }
        if (_targets.Count > 0)
        {
            float num = -1f;
            Tuple<int, int> tuple = _targets[0];
            for (int k = 0; k < _targets.Count; k++)
            {
                float num2 = Vector2.Distance(new Vector2(_targets[k].Item1, _targets[k].Item2) * 16f + Vector2.One * 8f, providedInfo.mouse);
                if (num == -1f || num2 < num)
                {
                    num = num2;
                    tuple = _targets[k];
                }
            }
            if (Collision.InTileBounds(tuple.Item1, tuple.Item2, providedInfo.reachableStartX, providedInfo.reachableStartY, providedInfo.reachableEndX, providedInfo.reachableEndY) && num != -1f)
            {
                focusedX = tuple.Item1;
                focusedY = tuple.Item2;
            }
        }
        _targets.Clear();
    }
References Terraria.GameContent.SmartCursorHelper._targets, Terraria.Tile.active(), Terraria.ID.TileID.Sets.BreakableWhenPlacing, Terraria.Item.createTile, Terraria.Collision.InTileBounds(), Terraria.GameContent.SmartCursorHelper.SmartCursorUsageInfo.item, Terraria.GameContent.SmartCursorHelper.SmartCursorUsageInfo.mouse, Terraria.GameContent.SmartCursorHelper.SmartCursorUsageInfo.reachableEndX, Terraria.GameContent.SmartCursorHelper.SmartCursorUsageInfo.reachableEndY, Terraria.GameContent.SmartCursorHelper.SmartCursorUsageInfo.reachableStartX, Terraria.GameContent.SmartCursorHelper.SmartCursorUsageInfo.reachableStartY, Terraria.GameContent.SmartCursorHelper.SmartCursorUsageInfo.screenTargetX, Terraria.GameContent.SmartCursorHelper.SmartCursorUsageInfo.screenTargetY, Terraria.Main.tile, Terraria.Main.tileCut, and Terraria.Tile.type.
Referenced by Terraria.GameContent.SmartCursorHelper.SmartCursorLookup().