Terraria: Terraria.GameContent.SmartCursorHelper.Step_EmptyBuckets
Step_EmptyBuckets()
static void Terraria.GameContent.SmartCursorHelper.Step_EmptyBuckets (SmartCursorUsageInfo providedInfo, ref int focusedX, ref int focusedY) inline static private
    {
        if (providedInfo.item.type != 205 || focusedX != -1 || focusedY != -1)
        {
            return;
        }
        _targets.Clear();
        for (int i = providedInfo.reachableStartX; i <= providedInfo.reachableEndX; i++)
        {
            for (int j = providedInfo.reachableStartY; j <= providedInfo.reachableEndY; j++)
            {
                Tile tile = Main.tile[i, j];
                if (tile.liquid <= 0)
                {
                    continue;
                }
                int num = tile.liquidType();
                int num2 = 0;
                for (int k = i - 1; k <= i + 1; k++)
                {
                    for (int l = j - 1; l <= j + 1; l++)
                    {
                        if (Main.tile[k, l].liquidType() == num)
{
                            num2 += Main.tile[k, l].liquid;
                        }
                    }
                }
                if (num2 > 100)
                {
                    _targets.Add(new Tuple<int, int>(i, j));
                }
            }
        }
        if (_targets.Count > 0)
        {
            float num3 = -1f;
            Tuple<int, int> tuple = _targets[0];
            for (int m = 0; m < _targets.Count; m++)
            {
                float num4 = Vector2.Distance(new Vector2(_targets[m].Item1, _targets[m].Item2) * 16f + Vector2.One * 8f, providedInfo.mouse);
                if (num3 == -1f || num4 < num3)
                {
                    num3 = num4;
                    tuple = _targets[m];
                }
            }
            if (Collision.InTileBounds(tuple.Item1, tuple.Item2, providedInfo.reachableStartX, providedInfo.reachableStartY, providedInfo.reachableEndX, providedInfo.reachableEndY))
            {
                focusedX = tuple.Item1;
                focusedY = tuple.Item2;
            }
        }
        _targets.Clear();
    }
References Terraria.GameContent.SmartCursorHelper._targets, Terraria.Collision.InTileBounds(), Terraria.GameContent.SmartCursorHelper.SmartCursorUsageInfo.item, Terraria.Tile.liquid, Terraria.Tile.liquidType(), Terraria.GameContent.SmartCursorHelper.SmartCursorUsageInfo.mouse, Terraria.GameContent.SmartCursorHelper.SmartCursorUsageInfo.reachableEndX, Terraria.GameContent.SmartCursorHelper.SmartCursorUsageInfo.reachableEndY, Terraria.GameContent.SmartCursorHelper.SmartCursorUsageInfo.reachableStartX, Terraria.GameContent.SmartCursorHelper.SmartCursorUsageInfo.reachableStartY, Terraria.Main.tile, and Terraria.Item.type.
Referenced by Terraria.GameContent.SmartCursorHelper.SmartCursorLookup().