Terraria: Terraria.GameContent.SmartCursorHelper.Step_ColoredWrenches
Step_ColoredWrenches()
static void Terraria.GameContent.SmartCursorHelper.Step_ColoredWrenches (SmartCursorUsageInfo providedInfo, ref int focusedX, ref int focusedY) inline static private
Definition at line 1824 of file SmartCursorHelper.cs.
    {
        if ((providedInfo.item.type != 509 && providedInfo.item.type != 850 && providedInfo.item.type != 851 && providedInfo.item.type != 3612) || focusedX != -1 || focusedY != -1)
        {
            return;
        }
        _targets.Clear();
        int num = 0;
        if (providedInfo.item.type == 509)
        {
            num = 1;
        }
        if (providedInfo.item.type == 850)
        {
            num = 2;
        }
        if (providedInfo.item.type == 851)
        {
            num = 3;
        }
        if (providedInfo.item.type == 3612)
        {
            num = 4;
        }
        bool flag = false;
        if (Main.tile[providedInfo.screenTargetX, providedInfo.screenTargetY].wire() && num == 1)
        {
            flag = true;
        }
        if (Main.tile[providedInfo.screenTargetX, providedInfo.screenTargetY].wire2() && num == 2)
        {
            flag = true;
        }
        if (Main.tile[providedInfo.screenTargetX, providedInfo.screenTargetY].wire3() && num == 3)
        {
            flag = true;
        }
        if (Main.tile[providedInfo.screenTargetX, providedInfo.screenTargetY].wire4() && num == 4)
        {
            flag = true;
        }
        if (!flag)
        {
            for (int i = providedInfo.reachableStartX; i <= providedInfo.reachableEndX; i++)
            {
                for (int j = providedInfo.reachableStartY; j <= providedInfo.reachableEndY; j++)
                {
                    Tile tile = Main.tile[i, j];
                    if ((!tile.wire() || num != 1) && (!tile.wire2() || num != 2) && (!tile.wire3() || num != 3) && (!tile.wire4() || num != 4))
                    {
                        continue;
                    }
                    if (num == 1)
                    {
                        if (!Main.tile[i - 1, j].wire())
{
                            _targets.Add(new Tuple<int, int>(i - 1, j));
                        }
                        if (!Main.tile[i + 1, j].wire())
{
                            _targets.Add(new Tuple<int, int>(i + 1, j));
                        }
                        if (!Main.tile[i, j - 1].wire())
{
                            _targets.Add(new Tuple<int, int>(i, j - 1));
                        }
                        if (!Main.tile[i, j + 1].wire())
{
                            _targets.Add(new Tuple<int, int>(i, j + 1));
                        }
                    }
                    if (num == 2)
                    {
                        if (!Main.tile[i - 1, j].wire2())
{
                            _targets.Add(new Tuple<int, int>(i - 1, j));
                        }
                        if (!Main.tile[i + 1, j].wire2())
{
                            _targets.Add(new Tuple<int, int>(i + 1, j));
                        }
                        if (!Main.tile[i, j - 1].wire2())
{
                            _targets.Add(new Tuple<int, int>(i, j - 1));
                        }
                        if (!Main.tile[i, j + 1].wire2())
{
                            _targets.Add(new Tuple<int, int>(i, j + 1));
                        }
                    }
                    if (num == 3)
                    {
                        if (!Main.tile[i - 1, j].wire3())
{
                            _targets.Add(new Tuple<int, int>(i - 1, j));
                        }
                        if (!Main.tile[i + 1, j].wire3())
{
                            _targets.Add(new Tuple<int, int>(i + 1, j));
                        }
                        if (!Main.tile[i, j - 1].wire3())
{
                            _targets.Add(new Tuple<int, int>(i, j - 1));
                        }
                        if (!Main.tile[i, j + 1].wire3())
{
                            _targets.Add(new Tuple<int, int>(i, j + 1));
                        }
                    }
                    if (num == 4)
                    {
                        if (!Main.tile[i - 1, j].wire4())
{
                            _targets.Add(new Tuple<int, int>(i - 1, j));
                        }
                        if (!Main.tile[i + 1, j].wire4())
{
                            _targets.Add(new Tuple<int, int>(i + 1, j));
                        }
                        if (!Main.tile[i, j - 1].wire4())
{
                            _targets.Add(new Tuple<int, int>(i, j - 1));
                        }
                        if (!Main.tile[i, j + 1].wire4())
{
                            _targets.Add(new Tuple<int, int>(i, j + 1));
                        }
                    }
                }
            }
        }
        if (_targets.Count > 0)
        {
            float num2 = -1f;
            Tuple<int, int> tuple = _targets[0];
            for (int k = 0; k < _targets.Count; k++)
            {
                float num3 = Vector2.Distance(new Vector2(_targets[k].Item1, _targets[k].Item2) * 16f + Vector2.One * 8f, providedInfo.mouse);
                if (num2 == -1f || num3 < num2)
                {
                    num2 = num3;
                    tuple = _targets[k];
                }
            }
            if (Collision.InTileBounds(tuple.Item1, tuple.Item2, providedInfo.reachableStartX, providedInfo.reachableStartY, providedInfo.reachableEndX, providedInfo.reachableEndY))
            {
                focusedX = tuple.Item1;
                focusedY = tuple.Item2;
            }
        }
        _targets.Clear();
    }
References Terraria.GameContent.SmartCursorHelper._targets, Terraria.Collision.InTileBounds(), Terraria.GameContent.SmartCursorHelper.SmartCursorUsageInfo.item, Terraria.GameContent.SmartCursorHelper.SmartCursorUsageInfo.mouse, Terraria.GameContent.SmartCursorHelper.SmartCursorUsageInfo.reachableEndX, Terraria.GameContent.SmartCursorHelper.SmartCursorUsageInfo.reachableEndY, Terraria.GameContent.SmartCursorHelper.SmartCursorUsageInfo.reachableStartX, Terraria.GameContent.SmartCursorHelper.SmartCursorUsageInfo.reachableStartY, Terraria.GameContent.SmartCursorHelper.SmartCursorUsageInfo.screenTargetX, Terraria.GameContent.SmartCursorHelper.SmartCursorUsageInfo.screenTargetY, Terraria.Main.tile, Terraria.Item.type, Terraria.Tile.wire(), Terraria.Tile.wire2(), Terraria.Tile.wire3(), and Terraria.Tile.wire4().
Referenced by Terraria.GameContent.SmartCursorHelper.SmartCursorLookup().