Terraria: Terraria.GameContent.SmartCursorHelper.Step_AlchemySeeds
Step_AlchemySeeds()
static void Terraria.GameContent.SmartCursorHelper.Step_AlchemySeeds (SmartCursorUsageInfo providedInfo, ref int focusedX, ref int focusedY) inline static private
Definition at line 460 of file SmartCursorHelper.cs.
    {
        if (providedInfo.item.createTile != 82 || focusedX != -1 || focusedY != -1)
        {
            return;
        }
        int placeStyle = providedInfo.item.placeStyle;
        _targets.Clear();
        for (int i = providedInfo.reachableStartX; i <= providedInfo.reachableEndX; i++)
        {
            for (int j = providedInfo.reachableStartY; j <= providedInfo.reachableEndY; j++)
            {
                Tile tile = Main.tile[i, j];
                Tile tile2 = Main.tile[i, j + 1];
                bool num = !tile.active() || TileID.Sets.BreakableWhenPlacing[tile.type] || (Main.tileCut[tile.type] && tile.type != 82 && tile.type != 83) || WorldGen.IsHarvestableHerbWithSeed(tile.type, tile.frameX / 18);
                bool flag = tile2.nactive() && !tile2.halfBrick() && tile2.slope() == 0;
                if (!num || !flag)
                {
                    continue;
                }
                switch (placeStyle)
                {
                case 0:
                    if ((tile2.type != 78 && tile2.type != 380 && tile2.type != 2 && tile2.type != 477 && tile2.type != 109 && tile2.type != 492) || tile.liquid > 0)
                    {
                        continue;
                    }
                    break;
                case 1:
                    if ((tile2.type != 78 && tile2.type != 380 && tile2.type != 60) || tile.liquid > 0)
                    {
                        continue;
                    }
                    break;
                case 2:
                    if ((tile2.type != 78 && tile2.type != 380 && tile2.type != 0 && tile2.type != 59) || tile.liquid > 0)
                    {
                        continue;
                    }
                    break;
                case 3:
                    if ((tile2.type != 78 && tile2.type != 380 && tile2.type != 203 && tile2.type != 199 && tile2.type != 23 && tile2.type != 25) || tile.liquid > 0)
                    {
                        continue;
                    }
                    break;
                case 4:
                    if ((tile2.type != 78 && tile2.type != 380 && tile2.type != 53 && tile2.type != 116) || (tile.liquid > 0 && tile.lava()))
                    {
                        continue;
                    }
                    break;
                case 5:
                    if ((tile2.type != 78 && tile2.type != 380 && tile2.type != 57 && tile2.type != 633) || (tile.liquid > 0 && !tile.lava()))
                    {
                        continue;
                    }
                    break;
                case 6:
                    if ((tile2.type != 78 && tile2.type != 380 && tile2.type != 147 && tile2.type != 161 && tile2.type != 163 && tile2.type != 164 && tile2.type != 200) || (tile.liquid > 0 && tile.lava()))
                    {
                        continue;
                    }
                    break;
                }
                _targets.Add(new Tuple<int, int>(i, j));
            }
        }
        if (_targets.Count > 0)
        {
            float num2 = -1f;
            Tuple<int, int> tuple = _targets[0];
            for (int k = 0; k < _targets.Count; k++)
            {
                float num3 = Vector2.Distance(new Vector2(_targets[k].Item1, _targets[k].Item2) * 16f + Vector2.One * 8f, providedInfo.mouse);
                if (num2 == -1f || num3 < num2)
                {
                    num2 = num3;
                    tuple = _targets[k];
                }
            }
            if (Collision.InTileBounds(tuple.Item1, tuple.Item2, providedInfo.reachableStartX, providedInfo.reachableStartY, providedInfo.reachableEndX, providedInfo.reachableEndY))
            {
                focusedX = tuple.Item1;
                focusedY = tuple.Item2;
            }
        }
        _targets.Clear();
    }
References Terraria.GameContent.SmartCursorHelper._targets, Terraria.Tile.active(), Terraria.ID.TileID.Sets.BreakableWhenPlacing, Terraria.Item.createTile, Terraria.Tile.frameX, Terraria.Tile.halfBrick(), Terraria.Collision.InTileBounds(), Terraria.WorldGen.IsHarvestableHerbWithSeed(), Terraria.GameContent.SmartCursorHelper.SmartCursorUsageInfo.item, Terraria.Tile.lava(), Terraria.GameContent.SmartCursorHelper.SmartCursorUsageInfo.mouse, Terraria.Tile.nactive(), Terraria.Item.placeStyle, Terraria.GameContent.SmartCursorHelper.SmartCursorUsageInfo.reachableEndX, Terraria.GameContent.SmartCursorHelper.SmartCursorUsageInfo.reachableEndY, Terraria.GameContent.SmartCursorHelper.SmartCursorUsageInfo.reachableStartX, Terraria.GameContent.SmartCursorHelper.SmartCursorUsageInfo.reachableStartY, Terraria.Tile.slope(), Terraria.Main.tile, Terraria.Main.tileCut, and Terraria.Tile.type.
Referenced by Terraria.GameContent.SmartCursorHelper.SmartCursorLookup().