Terraria: System.Security.AccessControl.CommonAcl.CheckAccessType
CheckAccessType()
void System.Security.AccessControl.CommonAcl.CheckAccessType (AccessControlType accessType) inline package inherited
Definition at line 794 of file CommonAcl.cs.
    {
        if (accessType != 0 && accessType != AccessControlType.Deny)
        {
            throw new ArgumentOutOfRangeException("accessType", System.SR.ArgumentOutOfRange_Enum);
        }
    }
References System.SR.ArgumentOutOfRange_Enum.
Referenced by System.Security.AccessControl.DiscretionaryAcl.AddAccess(), System.Security.AccessControl.DiscretionaryAcl.AddAccess(), System.Security.AccessControl.DiscretionaryAcl.RemoveAccess(), System.Security.AccessControl.DiscretionaryAcl.RemoveAccess(), System.Security.AccessControl.DiscretionaryAcl.RemoveAccessSpecific(), System.Security.AccessControl.DiscretionaryAcl.RemoveAccessSpecific(), System.Security.AccessControl.DiscretionaryAcl.SetAccess(), and System.Security.AccessControl.DiscretionaryAcl.SetAccess().