Terraria: System.Security.AccessControl.CommonAcl.MergeAces
MergeAces()
bool System.Security.AccessControl.CommonAcl.MergeAces (ref QualifiedAce ace, QualifiedAce newAce) inline private inherited
Definition at line 606 of file CommonAcl.cs.
    {
        if (!AcesAreMergeable(ace, newAce))
        {
            return false;
        }
        if (ace.AceFlags == newAce.AceFlags)
        {
            if (!(ace is ObjectAce) && !(newAce is ObjectAce))
            {
                ace.AccessMask |= newAce.AccessMask;
                return true;
            }
            if (InheritedObjectTypesMatch(ace, newAce) && AccessMasksAreMergeable(ace, newAce))
            {
                ace.AccessMask |= newAce.AccessMask;
                return true;
            }
        }
        if ((ace.AceFlags & AceFlags.InheritanceFlags) == (newAce.AceFlags & AceFlags.InheritanceFlags) && ace.AccessMask == newAce.AccessMask)
        {
            if (!(ace is ObjectAce) && !(newAce is ObjectAce))
            {
                ace.AceFlags |= newAce.AceFlags & AceFlags.AuditFlags;
                return true;
            }
            if (InheritedObjectTypesMatch(ace, newAce) && ObjectTypesMatch(ace, newAce))
            {
                ace.AceFlags |= newAce.AceFlags & AceFlags.AuditFlags;
                return true;
            }
        }
        if ((ace.AceFlags & AceFlags.AuditFlags) == (newAce.AceFlags & AceFlags.AuditFlags) && ace.AccessMask == newAce.AccessMask)
        {
            AceFlags result;
            if (ace is ObjectAce || newAce is ObjectAce)
            {
                if (ObjectTypesMatch(ace, newAce) && AceFlagsAreMergeable(ace, newAce) && MergeInheritanceBits(ace.AceFlags, newAce.AceFlags, IsDS, out result))
                {
                    ace.AceFlags = result | (ace.AceFlags & AceFlags.AuditFlags);
                    return true;
                }
            }
            else if (MergeInheritanceBits(ace.AceFlags, newAce.AceFlags, IsDS, out result))
            {
                ace.AceFlags = result | (ace.AceFlags & AceFlags.AuditFlags);
                return true;
            }
        }
        return false;
    }
References System.Security.AccessControl.KnownAce.AccessMask, System.Security.AccessControl.CommonAcl.AccessMasksAreMergeable(), System.Security.AccessControl.GenericAce.AceFlags, System.Security.AccessControl.CommonAcl.AceFlagsAreMergeable(), System.Security.AccessControl.CommonAcl.AcesAreMergeable(), System.Security.AccessControl.CommonAcl.InheritedObjectTypesMatch(), System.Security.AccessControl.CommonAcl.IsDS, System.Security.AccessControl.CommonAcl.MergeInheritanceBits(), and System.Security.AccessControl.CommonAcl.ObjectTypesMatch().
Referenced by System.Security.AccessControl.CommonAcl.AddQualifiedAce(), and System.Security.AccessControl.CommonAcl.Canonicalize().