Terraria: System.Security.AccessControl.CommonAcl.GetBinaryForm
GetBinaryForm()
override void System.Security.AccessControl.CommonAcl.GetBinaryForm (byte[] binaryForm, int offset) inline sealed inherited
Definition at line 1108 of file CommonAcl.cs.
    {
        CanonicalizeIfNecessary();
        _acl.GetBinaryForm(binaryForm, offset);
    }
References System.Security.AccessControl.CommonAcl._acl, System.Security.AccessControl.CommonAcl.CanonicalizeIfNecessary(), System.Security.AccessControl.RawAcl.GetBinaryForm(), and System.offset.
Referenced by System.Security.AccessControl.CommonAcl.RemoveQualifiedAces().