Terraria: System.Security.AccessControl.CommonAcl.QuickSort
QuickSort()
void System.Security.AccessControl.CommonAcl.QuickSort (int left, int right, bool isDacl) inline private inherited
Definition at line 314 of file CommonAcl.cs.
    {
        if (left >= right)
        {
            return;
        }
        int num = left;
        int num2 = right;
        GenericAce genericAce = _acl[left];
        int num3 = left;
        while (left < right)
        {
            while (CompareAces(_acl[right], genericAce, isDacl) != 0 && left < right)
            {
                right--;
            }
            if (left != right)
            {
                _acl[left] = _acl[right];
                left++;
            }
            while (ComparisonResult.GreaterThan != CompareAces(_acl[left], genericAce, isDacl) && left < right)
            {
                left++;
            }
            if (left != right)
            {
                _acl[right] = _acl[left];
                right--;
            }
        }
        _acl[left] = genericAce;
        num3 = left;
        left = num;
        right = num2;
        if (left < num3)
        {
            QuickSort(left, num3 - 1, isDacl);
        }
        if (right > num3)
        {
            QuickSort(num3 + 1, right, isDacl);
        }
    }
References System.Security.AccessControl.CommonAcl._acl, System.Security.AccessControl.CommonAcl.CompareAces(), and System.Security.AccessControl.CommonAcl.QuickSort().
Referenced by System.Security.AccessControl.CommonAcl.Canonicalize(), and System.Security.AccessControl.CommonAcl.QuickSort().