Terraria: BestiaryEntry.Critter
Critter()
static BestiaryEntry BestiaryEntry.Critter (int npcNetId) inline static
     {
         NPC nPC = ContentSamples.NpcsByNetId[npcNetId];
         List<IBestiaryInfoElement> list = new List<IBestiaryInfoElement>
         {
             new NPCNetIdBestiaryInfoElement(npcNetId),
             new NamePlateInfoElement(Lang.GetNPCName(npcNetId).Key, npcNetId),
             new NPCPortraitInfoElement(ContentSamples.NpcBestiaryRarityStars[npcNetId]),
             new NPCKillCounterInfoElement(npcNetId)
         };
         string key = Lang.GetNPCName(nPC.netID).Key;
         key = key.Replace("NPCName.", "");
         string text = "Bestiary_FlavorText.npc_" + key;
         if (Language.Exists(text))
         {
             list.Add(new FlavorTextBestiaryInfoElement(text));
         }
         return new BestiaryEntry
         {
             Icon = new UnlockableNPCEntryIcon(npcNetId),
             Info = list,
             UIInfoProvider = new CritterUICollectionInfoProvider(nPC.GetBestiaryCreditId())
         };
     }
References Language.Exists(), NPC.GetBestiaryCreditId(), Lang.GetNPCName(), Icon, Info, LocalizedText.Key, NPC.netID, ContentSamples.NpcBestiaryRarityStars, ContentSamples.NpcsByNetId, and UIInfoProvider.
Referenced by BestiaryDatabaseNPCsPopulator.AddEmptyEntries_CrittersAndEnemies_Automated().