Terraria: System.Data.DataColumn.SetMaxLengthSimpleType
SetMaxLengthSimpleType()
void System.Data.DataColumn.SetMaxLengthSimpleType () inline private
Definition at line 1117 of file DataColumn.cs.
    {
        if (_simpleType != null)
        {
            _simpleType.MaxLength = _maxLength;
            if (_simpleType.IsPlainString())
            {
                _simpleType = null;
            }
            else if (_simpleType.Name != null && XmlDataType != null)
            {
                _simpleType.ConvertToAnnonymousSimpleType();
                XmlDataType = null;
            }
        }
        else if (-1 < _maxLength)
        {
            SimpleType = System.Data.SimpleType.CreateLimitedStringType(_maxLength);
        }
    }
References System.Data.DataColumn._maxLength, System.Data.DataColumn._simpleType, System.Data.SimpleType.ConvertToAnnonymousSimpleType(), System.Data.SimpleType.CreateLimitedStringType(), System.Xml.Dictionary, System.Data.SimpleType.IsPlainString(), and System.Data.SimpleType.Name.