Terraria: System.Security.AccessControl.CommonAcl.InheritedObjectTypesMatch
InheritedObjectTypesMatch()
bool System.Security.AccessControl.CommonAcl.InheritedObjectTypesMatch (QualifiedAce ace, QualifiedAce newAce) inline private inherited
Definition at line 472 of file CommonAcl.cs.
    {
        Guid guid = ((ace is ObjectAce) ? ((ObjectAce)ace).InheritedObjectAceType : Guid.Empty);
        Guid g = ((newAce is ObjectAce) ? ((ObjectAce)newAce).InheritedObjectAceType : Guid.Empty);
        return guid.Equals(g);
    }
References System.Guid.Empty, and System.Guid.Equals().
Referenced by System.Security.AccessControl.CommonAcl.AceFlagsAreMergeable(), and System.Security.AccessControl.CommonAcl.MergeAces().