Terraria: System.Data.DataColumn.InsureStorage
InsureStorage()
DataStorage System.Data.DataColumn.InsureStorage () inline private
Definition at line 1544 of file DataColumn.cs.
    {
        if (_storage == null)
        {
            _storage = DataStorage.CreateStorage(this, _dataType, _storageType);
        }
        return _storage;
    }
References System.Data.DataColumn._dataType, System.Data.DataColumn._storage, System.Data.DataColumn._storageType, and System.Data.Common.DataStorage.CreateStorage().
Referenced by System.Data.DataColumn.ConvertObjectToXml(), System.Data.DataColumn.ConvertObjectToXml(), System.Data.DataColumn.ConvertXmlToObject(), System.Data.DataColumn.ConvertXmlToObject(), System.Data.DataColumn.GetEmptyColumnStore(), System.Data.DataColumn.SetCapacity(), and System.Data.DataColumn.SetStorage().