Terraria: System.Security.AccessControl.CommonAcl.RemoveInheritanceBits
RemoveInheritanceBits()
static bool System.Security.AccessControl.CommonAcl.RemoveInheritanceBits (AceFlags existing, AceFlags remove, bool isDS, out AceFlags result, out bool total) inline static private inherited
Definition at line 201 of file CommonAcl.cs.
    {
        result = AceFlags.None;
        total = false;
        AF aF = AFFromAceFlags(existing, isDS);
        AF aF2 = AFFromAceFlags(remove, isDS);
        PM pM = s_AFtoPM[(int)aF];
        PM pM2 = s_AFtoPM[(int)aF2];
        if (pM == PM.GO || pM2 == PM.GO)
        {
            return false;
        }
        PM pM3 = pM & ~pM2;
        if (pM3 == (PM)0)
        {
            total = true;
            return true;
        }
        AF aF3 = s_PMtoAF[(int)pM3];
        if (aF3 == AF.NP)
        {
            return false;
        }
        result = AceFlagsFromAF(aF3, isDS);
        return true;
    }
References System.Security.AccessControl.CommonAcl.AceFlagsFromAF(), System.Security.AccessControl.CommonAcl.AFFromAceFlags(), System.Security.AccessControl.CommonAcl.s_AFtoPM, and System.Security.AccessControl.CommonAcl.s_PMtoAF.
Referenced by System.Security.AccessControl.CommonAcl.RemoveQualifiedAces().