Terraria: System.Security.AccessControl.CommonAcl.AddQualifiedAce
AddQualifiedAce()
void System.Security.AccessControl.CommonAcl.AddQualifiedAce (SecurityIdentifier sid, AceQualifier qualifier, int accessMask, AceFlags flags, ObjectAceFlags objectFlags, Guid objectType, Guid inheritedObjectType) inline package inherited
Definition at line 822 of file CommonAcl.cs.
    {
        if (sid == null)
        {
            throw new ArgumentNullException("sid");
        }
        ThrowIfNotCanonical();
        bool flag = false;
        if (qualifier == AceQualifier.SystemAudit && (flags & AceFlags.AuditFlags) == 0)
        {
            throw new ArgumentException(System.SR.Arg_EnumAtLeastOneFlag, "flags");
        }
        if (accessMask == 0)
        {
            throw new ArgumentException(System.SR.Argument_ArgumentZero, "accessMask");
        }
        GenericAce ace = ((IsDS && objectFlags != 0) ? ((QualifiedAce)new ObjectAce(flags, qualifier, accessMask, sid, objectFlags, objectType, inheritedObjectType, isCallback: false, null)) : ((QualifiedAce)new CommonAce(flags, qualifier, accessMask, sid, isCallback: false, null)));
        if (!InspectAce(ref ace, this is DiscretionaryAcl))
        {
            return;
        }
        for (int i = 0; i < Count; i++)
        {
            QualifiedAce ace2 = _acl[i] as QualifiedAce;
            if (!(ace2 == null) && MergeAces(ref ace2, (QualifiedAce)ace))
            {
                flag = true;
                break;
            }
        }
        if (!flag)
        {
            _acl.InsertAce(_acl.Count, ace);
            _isDirty = true;
        }
        OnAclModificationTried();
    }
References System.Security.AccessControl.CommonAcl._acl, System.Security.AccessControl.CommonAcl._isDirty, System.SR.Arg_EnumAtLeastOneFlag, System.SR.Argument_ArgumentZero, System.Security.AccessControl.CommonAcl.Count, System.Security.AccessControl.RawAcl.Count, System.Security.AccessControl.RawAcl.InsertAce(), System.Security.AccessControl.CommonAcl.InspectAce(), System.Security.AccessControl.CommonAcl.IsDS, System.Security.AccessControl.CommonAcl.MergeAces(), System.Security.AccessControl.CommonAcl.OnAclModificationTried(), and System.Security.AccessControl.CommonAcl.ThrowIfNotCanonical().
Referenced by System.Security.AccessControl.DiscretionaryAcl.AddAccess(), System.Security.AccessControl.DiscretionaryAcl.AddAccess(), System.Security.AccessControl.SystemAcl.AddAudit(), and System.Security.AccessControl.SystemAcl.AddAudit().