Terraria: System.Data.DataColumn.Clone
Clone()
DataColumn System.Data.DataColumn.Clone () inline package
Definition at line 1364 of file DataColumn.cs.
    {
        DataColumn dataColumn = (DataColumn)Activator.CreateInstance(GetType());
        dataColumn.SimpleType = SimpleType;
        dataColumn._allowNull = _allowNull;
        if (_autoInc != null)
        {
            dataColumn._autoInc = _autoInc.Clone();
        }
        dataColumn._caption = _caption;
        dataColumn.ColumnName = ColumnName;
        dataColumn._columnUri = _columnUri;
        dataColumn._columnPrefix = _columnPrefix;
        dataColumn.DataType = DataType;
        dataColumn._defaultValue = _defaultValue;
        dataColumn._defaultValueIsNull = ((_defaultValue == DBNull.Value || (dataColumn.ImplementsINullable && DataStorage.IsObjectSqlNull(_defaultValue))) ? true : false);
        dataColumn._columnMapping = _columnMapping;
        dataColumn._readOnly = _readOnly;
        dataColumn.MaxLength = MaxLength;
        dataColumn.XmlDataType = XmlDataType;
        dataColumn._dateTimeMode = _dateTimeMode;
        if (_extendedProperties != null)
        {
            foreach (object key in _extendedProperties.Keys)
            {
                dataColumn.ExtendedProperties[key] = _extendedProperties[key];
            }
        }
        return dataColumn;
    }
References System.Data.DataColumn.DataColumn(), System.Data.DataColumn._allowNull, System.Data.DataColumn._autoInc, System.Data.DataColumn._caption, System.Data.DataColumn._columnMapping, System.Data.DataColumn._columnPrefix, System.Data.DataColumn._columnUri, System.Data.DataColumn._dateTimeMode, System.Data.DataColumn._defaultValue, System.Data.DataColumn._extendedProperties, System.Data.DataColumn._readOnly, System.Data.AutoIncrementValue.Clone(), System.Data.DataColumn.ColumnName, System.Activator.CreateInstance(), System.Data.DataColumn.DataType, System.Xml.Dictionary, System.Data.Common.DataStorage.IsObjectSqlNull(), System.key, System.Collections.Hashtable.Keys, System.Data.DataColumn.MaxLength, System.Data.DataColumn.SimpleType, and System.Data.DataColumn.XmlDataType.