Terraria: System.Security.AccessControl.CommonAcl.CompareAces
CompareAces()
static ComparisonResult System.Security.AccessControl.CommonAcl.CompareAces (GenericAce ace1, GenericAce ace2, bool isDacl) inline static private inherited
Definition at line 287 of file CommonAcl.cs.
    {
        int num = (isDacl ? DaclAcePriority(ace1) : SaclAcePriority(ace1));
        int num2 = (isDacl ? DaclAcePriority(ace2) : SaclAcePriority(ace2));
        if (num < num2)
        {
            return ComparisonResult.LessThan;
        }
        if (num > num2)
        {
            return ComparisonResult.GreaterThan;
        }
        if (ace1 is KnownAce knownAce && ace2 is KnownAce knownAce2)
        {
            int num3 = knownAce.SecurityIdentifier.CompareTo(knownAce2.SecurityIdentifier);
            if (num3 < 0)
            {
                return ComparisonResult.LessThan;
            }
            if (num3 > 0)
            {
                return ComparisonResult.GreaterThan;
            }
        }
        return ComparisonResult.EqualTo;
    }
References System.Security.AccessControl.CommonAcl.DaclAcePriority(), and System.Security.AccessControl.CommonAcl.SaclAcePriority().
Referenced by System.Security.AccessControl.CommonAcl.QuickSort().