Terraria: System.Data.DataColumn.SetTable
SetTable()
void System.Data.DataColumn.SetTable (DataTable table) inline package
Definition at line 1179 of file DataColumn.cs.
    {
        if (_table == table)
        {
            return;
        }
        if (Computed && (table == null || (!table.fInitInProgress && (table.DataSet == null || (!table.DataSet._fIsSchemaLoading && !table.DataSet._fInitInProgress)))))
        {
            DataExpression.Bind(table);
        }
        if (Unique && _table != null)
        {
            UniqueConstraint uniqueConstraint = table.Constraints.FindKeyConstraint(this);
            if (uniqueConstraint != null)
            {
                table.Constraints.CanRemove(uniqueConstraint, fThrowException: true);
            }
        }
        _table = table;
        _storage = null;
    }
References System.Data.DataSet._fInitInProgress, System.Data.DataSet._fIsSchemaLoading, System.Data.DataColumn._storage, System.Data.DataColumn._table, System.Data.DataExpression.Bind(), System.Data.ConstraintCollection.CanRemove(), System.Data.DataColumn.Computed, System.Data.DataTable.Constraints, System.Data.DataTable.DataSet, System.Data.ConstraintCollection.FindKeyConstraint(), System.Data.DataTable.fInitInProgress, and System.Data.DataColumn.Unique.