Terraria: System.Security.AccessControl.CommonAcl.CheckFlags
CheckFlags()
void System.Security.AccessControl.CommonAcl.CheckFlags (InheritanceFlags inheritanceFlags, PropagationFlags propagationFlags) inline package inherited
Definition at line 802 of file CommonAcl.cs.
    {
        if (IsContainer)
        {
            if (inheritanceFlags == InheritanceFlags.None && propagationFlags != 0)
            {
                throw new ArgumentException(System.SR.Argument_InvalidAnyFlag, "propagationFlags");
            }
            return;
        }
        if (inheritanceFlags != 0)
        {
            throw new ArgumentException(System.SR.Argument_InvalidAnyFlag, "inheritanceFlags");
        }
        if (propagationFlags != 0)
        {
            throw new ArgumentException(System.SR.Argument_InvalidAnyFlag, "propagationFlags");
        }
    }
References System.SR.Argument_InvalidAnyFlag, and System.Security.AccessControl.CommonAcl.IsContainer.
Referenced by System.Security.AccessControl.DiscretionaryAcl.AddAccess(), System.Security.AccessControl.DiscretionaryAcl.AddAccess(), System.Security.AccessControl.SystemAcl.AddAudit(), System.Security.AccessControl.SystemAcl.AddAudit(), System.Security.AccessControl.DiscretionaryAcl.SetAccess(), System.Security.AccessControl.DiscretionaryAcl.SetAccess(), System.Security.AccessControl.SystemAcl.SetAudit(), and System.Security.AccessControl.SystemAcl.SetAudit().