Terraria: System.Security.AccessControl.CommonAcl.CommonAcl
CommonAcl() [2/2]
System.Security.AccessControl.CommonAcl.CommonAcl (bool isContainer, bool isDS, RawAcl rawAcl, bool trusted, bool isDacl) inline package
Definition at line 758 of file CommonAcl.cs.
    {
        if (rawAcl == null)
        {
            throw new ArgumentNullException("rawAcl");
        }
        _isContainer = isContainer;
        _isDS = isDS;
        if (trusted)
        {
            _acl = rawAcl;
            RemoveMeaninglessAcesAndFlags(isDacl);
        }
        else
        {
            _acl = new RawAcl(rawAcl.Revision, rawAcl.Count);
            for (int i = 0; i < rawAcl.Count; i++)
            {
                GenericAce ace = rawAcl[i].Copy();
                if (InspectAce(ref ace, isDacl))
                {
                    _acl.InsertAce(_acl.Count, ace);
                }
            }
        }
        if (CanonicalCheck(isDacl))
        {
            Canonicalize(compact: true, isDacl);
            _isCanonical = true;
        }
        else
        {
            _isCanonical = false;
        }
    }
References System.Security.AccessControl.CommonAcl._acl, System.Security.AccessControl.CommonAcl._isCanonical, System.Security.AccessControl.CommonAcl._isContainer, System.Security.AccessControl.CommonAcl._isDS, System.Security.AccessControl.CommonAcl.CanonicalCheck(), System.Security.AccessControl.CommonAcl.Canonicalize(), System.Security.AccessControl.RawAcl.Count, System.Security.AccessControl.RawAcl.InsertAce(), System.Security.AccessControl.CommonAcl.InspectAce(), System.Security.AccessControl.CommonAcl.RawAcl, System.Security.AccessControl.CommonAcl.RemoveMeaninglessAcesAndFlags(), and System.Security.AccessControl.RawAcl.Revision.