Terraria: System.Data.DataColumn.GetAggregateValue
GetAggregateValue()
object System.Data.DataColumn.GetAggregateValue (int[] records, AggregateType kind) inline package
Definition at line 1395 of file DataColumn.cs.
    {
        if (_storage == null)
        {
            if (kind != AggregateType.Count)
            {
                return DBNull.Value;
            }
            return 0;
        }
        return _storage.Aggregate(records, kind);
    }
References System.Data.DataColumn._storage, System.Data.Common.DataStorage.Aggregate(), and System.DBNull.Value.
Referenced by System.Data.AggregateNode.Eval(), and System.Data.AggregateNode.Eval().