Terraria: System.Data.DataColumn.SetValue
SetValue()
void System.Data.DataColumn.SetValue (int record, object value) inline package
Definition at line 1211 of file DataColumn.cs.
    {
        try
        {
            _storage.Set(record, value);
        }
        catch (Exception ex)
        {
            ExceptionBuilder.TraceExceptionForCapture(ex);
            throw ExceptionBuilder.SetFailed(value, this, DataType, ex);
        }
        DataRow dataRow = GetDataRow(record);
        if (dataRow != null)
        {
            dataRow.LastChangedColumn = this;
        }
    }
References System.Data.DataColumn._storage, System.Data.DataColumn.DataType, System.Xml.Dictionary, System.Data.DataColumn.GetDataRow(), System.Data.Common.DataStorage.Set(), System.Data.ExceptionBuilder.SetFailed(), System.Data.ExceptionBuilder.TraceExceptionForCapture(), and System.value.