Terraria: System.Data.DataColumn.UpdateColumnType
UpdateColumnType()
void System.Data.DataColumn.UpdateColumnType ([DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicFields | DynamicallyAccessedMemberTypes.PublicProperties)] Type type, StorageType typeCode) inline private
Definition at line 1085 of file DataColumn.cs.
    {
        TypeLimiter.EnsureTypeIsAllowed(type);
        _dataType = type;
        _storageType = typeCode;
        if (StorageType.DateTime != typeCode)
        {
            _dateTimeMode = DataSetDateTime.UnspecifiedLocal;
        }
        DataStorage.ImplementsInterfaces(typeCode, type, out _isSqlType, out _implementsINullable, out _implementsIXMLSerializable, out _implementsIChangeTracking, out _implementsIRevertibleChangeTracking);
        if (!_isSqlType && _implementsINullable)
        {
            SqlUdtStorage.GetStaticNullForUdtType(type);
        }
    }
References System.Data.DataColumn._dataType, System.Data.DataColumn._dateTimeMode, System.Data.DataColumn._implementsIChangeTracking, System.Data.DataColumn._implementsINullable, System.Data.DataColumn._implementsIRevertibleChangeTracking, System.Data.DataColumn._implementsIXMLSerializable, System.Data.DataColumn._isSqlType, System.Data.DataColumn._storageType, System.Data.TypeLimiter.EnsureTypeIsAllowed(), System.Data.Common.SqlUdtStorage.GetStaticNullForUdtType(), System.Data.Common.DataStorage.ImplementsInterfaces(), and System.type.
Referenced by System.Data.DataColumn.DataColumn().