Terraria: System.Data.DataColumn.CompareValueTo
CompareValueTo() [2/2]
bool System.Data.DataColumn.CompareValueTo (int record1, object value, bool checkType) inline package
Definition at line 1326 of file DataColumn.cs.
    {
        if (CompareValueTo(record1, value) == 0)
        {
            Type type = value.GetType();
            Type type2 = _storage.Get(record1).GetType();
            if (type == typeof(string) && type2 == typeof(string))
            {
                if (string.CompareOrdinal((string)_storage.Get(record1), (string)value) != 0)
                {
                    return false;
                }
                return true;
            }
            if (type == type2)
            {
                return true;
            }
        }
        return false;
    }
References System.Data.DataColumn._storage, System.Data.DataColumn.CompareValueTo(), System.Xml.Dictionary, System.Data.Common.DataStorage.Get(), System.Type.GetType(), System.type, and System.value.
Referenced by System.Data.ForeignKeyConstraint.CheckConstraint(), System.Data.Index.CompareRecordToKey(), and System.Data.DataColumn.CompareValueTo().