Terraria: System.Security.AccessControl.CommonAcl.RemoveMeaninglessAcesAndFlags
RemoveMeaninglessAcesAndFlags()
void System.Security.AccessControl.CommonAcl.RemoveMeaninglessAcesAndFlags (bool isDacl) inline private inherited
Definition at line 411 of file CommonAcl.cs.
    {
        for (int num = _acl.Count - 1; num >= 0; num--)
        {
            GenericAce ace = _acl[num];
            if (!InspectAce(ref ace, isDacl))
            {
                _acl.RemoveAce(num);
            }
        }
    }
References System.Security.AccessControl.CommonAcl._acl, System.Security.AccessControl.RawAcl.Count, System.Security.AccessControl.CommonAcl.InspectAce(), and System.Security.AccessControl.RawAcl.RemoveAce().
Referenced by System.Security.AccessControl.CommonAcl.CommonAcl().