Terraria: System.Security.AccessControl.CommonAcl.SetQualifiedAce
SetQualifiedAce()
void System.Security.AccessControl.CommonAcl.SetQualifiedAce (SecurityIdentifier sid, AceQualifier qualifier, int accessMask, AceFlags flags, ObjectAceFlags objectFlags, Guid objectType, Guid inheritedObjectType) inline package inherited
Definition at line 860 of file CommonAcl.cs.
    {
        if (sid == null)
        {
            throw new ArgumentNullException("sid");
        }
        if (qualifier == AceQualifier.SystemAudit && (flags & AceFlags.AuditFlags) == 0)
        {
            throw new ArgumentException(System.SR.Arg_EnumAtLeastOneFlag, "flags");
        }
        if (accessMask == 0)
        {
            throw new ArgumentException(System.SR.Argument_ArgumentZero, "accessMask");
        }
        ThrowIfNotCanonical();
        GenericAce ace = ((IsDS && objectFlags != 0) ? ((QualifiedAce)new ObjectAce(flags, qualifier, accessMask, sid, objectFlags, objectType, inheritedObjectType, isCallback: false, null)) : ((QualifiedAce)new CommonAce(flags, qualifier, accessMask, sid, isCallback: false, null)));
        if (!InspectAce(ref ace, this is DiscretionaryAcl))
        {
            return;
        }
        for (int i = 0; i < Count; i++)
        {
            QualifiedAce qualifiedAce = _acl[i] as QualifiedAce;
            if (!(qualifiedAce == null) && (qualifiedAce.AceFlags & AceFlags.Inherited) == 0 && qualifiedAce.AceQualifier == qualifier && !(qualifiedAce.SecurityIdentifier != sid))
            {
                _acl.RemoveAce(i);
                i--;
            }
        }
        _acl.InsertAce(_acl.Count, ace);
        _isDirty = true;
        OnAclModificationTried();
    }
References System.Security.AccessControl.CommonAcl._acl, System.Security.AccessControl.CommonAcl._isDirty, System.Security.AccessControl.QualifiedAce.AceQualifier, System.SR.Arg_EnumAtLeastOneFlag, System.SR.Argument_ArgumentZero, System.Security.AccessControl.CommonAcl.Count, System.Security.AccessControl.RawAcl.Count, System.Security.AccessControl.RawAcl.InsertAce(), System.Security.AccessControl.CommonAcl.InspectAce(), System.Security.AccessControl.CommonAcl.IsDS, System.Security.AccessControl.CommonAcl.OnAclModificationTried(), System.Security.AccessControl.RawAcl.RemoveAce(), System.Security.AccessControl.KnownAce.SecurityIdentifier, and System.Security.AccessControl.CommonAcl.ThrowIfNotCanonical().
Referenced by System.Security.AccessControl.DiscretionaryAcl.SetAccess(), System.Security.AccessControl.DiscretionaryAcl.SetAccess(), System.Security.AccessControl.SystemAcl.SetAudit(), and System.Security.AccessControl.SystemAcl.SetAudit().