Terraria: System.Data.DataColumn.CheckNotAllowNull
CheckNotAllowNull()
void System.Data.DataColumn.CheckNotAllowNull () inline package
Definition at line 1271 of file DataColumn.cs.
    {
        if (_storage == null)
        {
            return;
        }
        if (_sortIndex != null)
        {
            if (!_sortIndex.IsKeyInIndex(_storage._nullValue))
            {
                return;
            }
            throw ExceptionBuilder.NullKeyValues(ColumnName);
        }
        foreach (DataRow row in _table.Rows)
        {
            if (row.RowState == DataRowState.Deleted)
            {
                continue;
            }
            if (!_implementsINullable)
            {
                if (row[this] == DBNull.Value)
                {
                    throw ExceptionBuilder.NullKeyValues(ColumnName);
                }
            }
            else if (DataStorage.IsObjectNull(row[this]))
            {
                throw ExceptionBuilder.NullKeyValues(ColumnName);
            }
        }
    }
References System.Data.DataColumn._implementsINullable, System.Data.Common.DataStorage._nullValue, System.Data.DataColumn._sortIndex, System.Data.DataColumn._storage, System.Data.DataColumn._table, System.Data.DataColumn.ColumnName, System.Data.Index.IsKeyInIndex(), System.Data.Common.DataStorage.IsObjectNull(), System.Data.ExceptionBuilder.NullKeyValues(), System.Data.DataTable.Rows, and System.DBNull.Value.