Terraria: System.Data.DataColumn.DataColumn
DataColumn() [5/5]
System.Data.DataColumn.DataColumn (string? columnName, [DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicFields | DynamicallyAccessedMemberTypes.PublicProperties)] Type dataType, string? expr, MappingType type) inline
Definition at line 1058 of file DataColumn.cs.
    {
        GC.SuppressFinalize(this);
        DataCommonEventSource.Log.Trace("<ds.DataColumn.DataColumn|API> {0}, columnName='{1}', expr='{2}', type={3}", ObjectID, columnName, expr, type);
        if (dataType == null)
        {
            throw ExceptionBuilder.ArgumentNull("dataType");
        }
        StorageType storageType = DataStorage.GetStorageType(dataType);
        if (DataStorage.ImplementsINullableValue(storageType, dataType))
        {
            throw ExceptionBuilder.ColumnTypeNotSupported();
        }
        _columnName = columnName ?? string.Empty;
        SimpleType simpleType = System.Data.SimpleType.CreateSimpleType(storageType, dataType);
        if (simpleType != null)
        {
            SimpleType = simpleType;
        }
        UpdateColumnType(dataType, storageType);
        if (!string.IsNullOrEmpty(expr))
        {
            Expression = expr;
        }
        _columnMapping = type;
    }
References System.Data.DataColumn._columnMapping, System.Data.DataColumn._columnName, System.Data.ExceptionBuilder.ArgumentNull(), System.Data.ExceptionBuilder.ColumnTypeNotSupported(), System.Data.SimpleType.CreateSimpleType(), System.Xml.Dictionary, System.Data.DataColumn.Expression, System.Data.Common.DataStorage.GetStorageType(), System.Data.Common.DataStorage.ImplementsINullableValue(), System.Data.DataCommonEventSource.Log, System.Data.DataColumn.ObjectID, System.GC.SuppressFinalize(), System.type, and System.Data.DataColumn.UpdateColumnType().