Terraria: System.Data.DataColumn.SetOrdinalInternal
SetOrdinalInternal()
void System.Data.DataColumn.SetOrdinalInternal (int ordinal) inline package
Definition at line 1150 of file DataColumn.cs.
    {
        if (_ordinal == ordinal)
        {
            return;
        }
        if (Unique && _ordinal != -1 && ordinal == -1)
        {
            UniqueConstraint uniqueConstraint = _table.Constraints.FindKeyConstraint(this);
            if (uniqueConstraint != null)
            {
                _table.Constraints.Remove(uniqueConstraint);
            }
        }
        if (_sortIndex != null && -1 == ordinal)
        {
            _sortIndex.RemoveRef();
            _sortIndex.RemoveRef();
            _sortIndex = null;
        }
        int ordinal2 = _ordinal;
        _ordinal = ordinal;
        if (ordinal2 == -1 && _ordinal != -1 && Unique)
        {
            UniqueConstraint constraint = new UniqueConstraint(this);
            _table.Constraints.Add(constraint);
        }
    }
References System.Data.DataColumn._ordinal, System.Data.DataColumn._sortIndex, System.Data.DataColumn._table, System.Data.ConstraintCollection.Add(), System.Data.DataTable.Constraints, System.Xml.Dictionary, System.Data.ConstraintCollection.FindKeyConstraint(), System.Data.ConstraintCollection.Remove(), System.Data.Index.RemoveRef(), and System.Data.DataColumn.Unique.