Terraria: System.Security.AccessControl.CommonAcl.ThrowIfNotCanonical
ThrowIfNotCanonical()
void System.Security.AccessControl.CommonAcl.ThrowIfNotCanonical () inline private inherited
Definition at line 742 of file CommonAcl.cs.
    {
        if (!_isCanonical)
        {
            throw new InvalidOperationException(System.SR.InvalidOperation_ModificationOfNonCanonicalAcl);
        }
    }
References System.Security.AccessControl.CommonAcl._isCanonical, and System.SR.InvalidOperation_ModificationOfNonCanonicalAcl.
Referenced by System.Security.AccessControl.CommonAcl.AddQualifiedAce(), System.Security.AccessControl.CommonAcl.Purge(), System.Security.AccessControl.CommonAcl.RemoveInheritedAces(), System.Security.AccessControl.CommonAcl.RemoveQualifiedAces(), System.Security.AccessControl.CommonAcl.RemoveQualifiedAcesSpecific(), and System.Security.AccessControl.CommonAcl.SetQualifiedAce().