Terraria: System.Security.AccessControl.CommonAcl.InspectAce
InspectAce()
bool System.Security.AccessControl.CommonAcl.InspectAce (ref GenericAce ace, bool isDacl) inline private inherited
Definition at line 359 of file CommonAcl.cs.
    {
        KnownAce knownAce = ace as KnownAce;
        if (knownAce != null && knownAce.AccessMask == 0)
        {
            return false;
        }
        if (!IsContainer)
        {
            if ((ace.AceFlags & AceFlags.InheritOnly) != 0)
            {
                return false;
            }
            if ((ace.AceFlags & AceFlags.InheritanceFlags) != 0)
            {
                ace.AceFlags &= ~AceFlags.InheritanceFlags;
            }
        }
        else
        {
            if ((ace.AceFlags & AceFlags.InheritOnly) != 0 && (ace.AceFlags & AceFlags.ContainerInherit) == 0 && (ace.AceFlags & AceFlags.ObjectInherit) == 0)
            {
                return false;
            }
            if ((ace.AceFlags & AceFlags.NoPropagateInherit) != 0 && (ace.AceFlags & AceFlags.ContainerInherit) == 0 && (ace.AceFlags & AceFlags.ObjectInherit) == 0)
            {
                ace.AceFlags &= ~AceFlags.NoPropagateInherit;
            }
        }
        QualifiedAce qualifiedAce = knownAce as QualifiedAce;
        if (isDacl)
        {
            ace.AceFlags &= ~AceFlags.AuditFlags;
            if (qualifiedAce != null && qualifiedAce.AceQualifier != 0 && qualifiedAce.AceQualifier != AceQualifier.AccessDenied)
            {
                return false;
            }
        }
        else
        {
            if ((ace.AceFlags & AceFlags.AuditFlags) == 0)
            {
                return false;
            }
            if (qualifiedAce != null && qualifiedAce.AceQualifier != AceQualifier.SystemAudit)
            {
                return false;
            }
        }
        return true;
    }
References System.Security.AccessControl.KnownAce.AccessMask, System.Security.AccessControl.QualifiedAce.AceQualifier, System.Security.AccessControl.GenericAce.AuditFlags, System.Security.AccessControl.GenericAce.InheritanceFlags, and System.Security.AccessControl.CommonAcl.IsContainer.
Referenced by System.Security.AccessControl.CommonAcl.CommonAcl(), System.Security.AccessControl.CommonAcl.AddQualifiedAce(), System.Security.AccessControl.CommonAcl.RemoveMeaninglessAcesAndFlags(), and System.Security.AccessControl.CommonAcl.SetQualifiedAce().