Terraria: System.Data.DataColumn.CheckColumnConstraint
CheckColumnConstraint()
void System.Data.DataColumn.CheckColumnConstraint (DataRow row, DataRowAction action) inline package
Definition at line 1239 of file DataColumn.cs.
    {
        if (_table.UpdatingCurrent(row, action))
        {
            CheckNullable(row);
            CheckMaxLength(row);
        }
    }
References System.Data.DataColumn._table, System.action, System.Data.DataColumn.CheckMaxLength(), System.Data.DataColumn.CheckNullable(), and System.Data.DataTable.UpdatingCurrent().