Terraria: System.Security.Cryptography.Asn1.FieldID.DecodeCore
DecodeCore() [1/2]
static void System.Security.Cryptography.Asn1.FieldID.DecodeCore (ref AsnValueReader reader, Asn1Tag expectedTag, ReadOnlyMemory< byte > rebind, out FieldID decoded) inline static private
Definition at line 55 of file FieldID.cs.
    {
        decoded = default(FieldID);
        AsnValueReader asnValueReader = reader.ReadSequence(expectedTag);
        ReadOnlySpan<byte> span = rebind.Span;
        decoded.FieldType = asnValueReader.ReadObjectIdentifier();
        ReadOnlySpan<byte> other = asnValueReader.ReadEncodedValue();
        decoded.Parameters = (span.Overlaps(other, out var elementOffset) ? rebind.Slice(elementOffset, other.Length) : ((ReadOnlyMemory<byte>)other.ToArray()));
        asnValueReader.ThrowIfNotEmpty();
    }
References System.other, System.Formats.Asn1.AsnValueReader.ReadEncodedValue(), System.Formats.Asn1.AsnValueReader.ReadObjectIdentifier(), System.Formats.Asn1.AsnValueReader.ReadSequence(), System.ReadOnlyMemory< T >.Slice(), System.ReadOnlyMemory< T >.Span, and System.Formats.Asn1.AsnValueReader.ThrowIfNotEmpty().
Referenced by System.Security.Cryptography.Asn1.FieldID.Decode(), and System.Security.Cryptography.Asn1.FieldID.Decode().