Terraria: AssetPathHelper.CleanPath
CleanPath()
static string AssetPathHelper.CleanPath (string path) inline static
     {
         path = path.Replace("/", "\\", StringComparison.Ordinal);
         path = path.Replace("\\.\\", "\\", StringComparison.Ordinal);
         while (path.StartsWith(".\\", StringComparison.Ordinal))
         {
             path = path.Substring(".\\".Length);
         }
         while (path.EndsWith("\\.", StringComparison.Ordinal))
         {
             path = ((path.Length <= "\\.".Length) ? "\\" : path.Substring(0, path.Length - "\\.".Length));
         }
         int num;
         for (num = 1; num < path.Length; num = CollapseParentDirectory(ref path, num, "\\..\\".Length))
         {
             num = path.IndexOf("\\..\\", num, StringComparison.Ordinal);
             if (num < 0)
             {
                 break;
             }
         }
         if (path.EndsWith("\\..", StringComparison.Ordinal))
         {
             int num2 = path.Length - "\\..".Length;
             if (num2 > 0)
             {
                 CollapseParentDirectory(ref path, num2, "\\..".Length);
             }
         }
         if (path == ".")
         {
             path = string.Empty;
         }
         if (Path.DirectorySeparatorChar != '\\')
         {
             path = path.Replace("\\", Path.DirectorySeparatorChar.ToString(), StringComparison.Ordinal);
         }
         return path;
     }
References CollapseParentDirectory().
Referenced by XnaDirectContentSource.XnaDirectContentSource(), ZipContentSource.BuildEntryList(), FileSystemContentSource.BuildNameToAbsolutePathDictionary(), ContentSource.GetExtension(), AssetRepository.Request< T >(), and ContentSource.SetAssetNames().