Terraria: System.Xml.Xsl.XsltOld.CopyNodeSetAction.Execute
Execute()
override void System.Xml.Xsl.XsltOld.CopyNodeSetAction.Execute (Processor processor, ActionFrame frame) inline package
Definition at line 14 of file CopyNodeSetAction.cs.
    {
        while (processor.CanContinue)
        {
            switch (frame.State)
            {
            default:
                return;
            case 0:
                if (frame.NextNode(processor))
                {
                    frame.State = 2;
                    goto case 2;
                }
                frame.Finished();
                return;
            case 2:
                if (SendBeginEvent(processor, frame.Node))
                {
                    frame.State = 3;
                    continue;
                }
                return;
            case 3:
            {
                XPathNodeType nodeType = frame.Node.NodeType;
                if (nodeType == XPathNodeType.Element || nodeType == XPathNodeType.Root)
                {
                    processor.PushActionFrame(CopyNamespacesAction.GetAction(), frame.NodeSet);
                    frame.State = 4;
                }
                else if (SendTextEvent(processor, frame.Node))
                {
                    frame.State = 7;
                    continue;
                }
                return;
            }
            case 4:
                processor.PushActionFrame(CopyAttributesAction.GetAction(), frame.NodeSet);
                frame.State = 5;
                return;
            case 5:
                if (frame.Node.HasChildren)
                {
                    processor.PushActionFrame(GetAction(), frame.Node.SelectChildren(XPathNodeType.All));
                    frame.State = 6;
                    return;
                }
                frame.State = 7;
                break;
            case 6:
                frame.State = 7;
                continue;
            case 7:
                break;
            case 1:
                return;
            }
            if (SendEndEvent(processor, frame.Node))
            {
                frame.State = 0;
                continue;
            }
            break;
        }
    }
References System.Xml.Dictionary, System.Xml.Xsl.XsltOld.ActionFrame.Finished(), System.Xml.Xsl.XsltOld.CopyAttributesAction.GetAction(), System.Xml.Xsl.XsltOld.CopyNamespacesAction.GetAction(), System.Xml.Xsl.XsltOld.CopyNodeSetAction.GetAction(), System.Xml.XPath.XPathNavigator.HasChildren, System.Xml.Xsl.XsltOld.ActionFrame.NextNode(), System.Xml.Xsl.XsltOld.ActionFrame.Node, System.Xml.Xsl.XsltOld.ActionFrame.NodeSet, System.Xml.XPath.XPathNavigator.NodeType, System.Xml.XPath.XPathNavigator.SelectChildren(), System.Xml.Xsl.XsltOld.CopyNodeSetAction.SendBeginEvent(), System.Xml.Xsl.XsltOld.CopyNodeSetAction.SendEndEvent(), System.Xml.Xsl.XsltOld.CopyNodeSetAction.SendTextEvent(), and System.Xml.Xsl.XsltOld.ActionFrame.State.