Terraria: ChromaHotkeyPainter.Step_KeybindsMenu
Step_KeybindsMenu()
void ChromaHotkeyPainter.Step_KeybindsMenu () inline private
     {
         SetGroupColorBase(_wasdKeys, PainterColors.MovementKeys);
         _jumpKey.SetSolid(PainterColors.MovementKeys);
         _grappleKey.SetSolid(PainterColors.QuickGrapple);
         _mountKey.SetSolid(PainterColors.QuickMount);
         _quickHealAlert = 0;
         _healKey.SetSolid(PainterColors.QuickHealReady);
         _manaKey.SetSolid(PainterColors.QuickMana);
         _throwKey.SetSolid(PainterColors.Throw);
         _smartCursorKey.SetSolid(PainterColors.SmartCursor);
         _smartSelectKey.SetSolid(PainterColors.SmartSelect);
     }
References _grappleKey, _healKey, _jumpKey, _manaKey, _mountKey, _quickHealAlert, _smartCursorKey, _smartSelectKey, _throwKey, _wasdKeys, ChromaHotkeyPainter.PainterColors.MovementKeys, ChromaHotkeyPainter.PainterColors.QuickGrapple, ChromaHotkeyPainter.PainterColors.QuickHealReady, ChromaHotkeyPainter.PainterColors.QuickMana, ChromaHotkeyPainter.PainterColors.QuickMount, SetGroupColorBase(), ChromaHotkeyPainter.PaintKey.SetSolid(), ChromaHotkeyPainter.PainterColors.SmartCursor, ChromaHotkeyPainter.PainterColors.SmartSelect, and ChromaHotkeyPainter.PainterColors.Throw.
Referenced by Update().