Terraria: System.Linq.Enumerable.SelectManySingleSelectorIterator.MoveNext
MoveNext()
override bool System.Linq.Enumerable.SelectManySingleSelectorIterator< TSource, TResult >.MoveNext () inline
Definition at line 2588 of file Enumerable.cs.
        {
            switch (_state)
            {
            case 1:
                _sourceEnumerator = _source.GetEnumerator();
                _state = 2;
                goto case 2;
            case 2:
            {
                if (!_sourceEnumerator.MoveNext())
                {
                    break;
                }
                TSource current = _sourceEnumerator.Current;
                _subEnumerator = _selector(current).GetEnumerator();
                _state = 3;
                goto case 3;
            }
            case 3:
                if (!_subEnumerator.MoveNext())
                {
                    _subEnumerator.Dispose();
                    _subEnumerator = null;
                    _state = 2;
                    goto case 2;
                }
                _current = _subEnumerator.Current;
                return true;
            }
            Dispose();
            return false;
        }
References System.Linq.Enumerable.Iterator< TResult >._current, System.Linq.Enumerable.SelectManySingleSelectorIterator< TSource, TResult >._selector, System.Linq.Enumerable.SelectManySingleSelectorIterator< TSource, TResult >._source, System.Linq.Enumerable.SelectManySingleSelectorIterator< TSource, TResult >._sourceEnumerator, System.Linq.Enumerable.Iterator< TResult >._state, System.Linq.Enumerable.SelectManySingleSelectorIterator< TSource, TResult >._subEnumerator, System.Collections.Generic.IEnumerator< out T >.Current, System.Collections.IEnumerator.Current, System.Linq.Enumerable.SelectManySingleSelectorIterator< TSource, TResult >.Dispose(), System.Collections.Generic.Dictionary< TKey, TValue >.GetEnumerator(), System.Collections.IEnumerable.GetEnumerator(), and System.Collections.IEnumerator.MoveNext().