Terraria: ChromaHotkeyPainter.Update
Update()
void ChromaHotkeyPainter.Update () inline
     {
         _player = Main.LocalPlayer;
         if (!Main.hasFocus)
         {
             Step_ClearAll();
             return;
         }
         if (PotionAlert)
         {
             foreach (KeyValuePair<string, PaintKey> key in _keys)
             {
                 if (key.Key != "QuickHeal")
                 {
                     key.Value.SetClear();
                 }
             }
             Step_QuickHeal();
         }
         else
         {
             Step_Movement();
             Step_QuickHeal();
         }
         if (Main.InGameUI.CurrentState == Main.ManageControlsMenu)
         {
             Step_ClearAll();
             Step_KeybindsMenu();
         }
         Step_UpdateReactiveKeys();
     }
References _keys, _player, UserInterface.CurrentState, Main.hasFocus, Main.InGameUI, Main.LocalPlayer, Main.ManageControlsMenu, PotionAlert, Step_ClearAll(), Step_KeybindsMenu(), Step_Movement(), Step_QuickHeal(), and Step_UpdateReactiveKeys().
Referenced by Main.DoUpdate().