Terraria: ChromaHotkeyPainter.Step_Movement
Step_Movement()
void ChromaHotkeyPainter.Step_Movement () inline private
     {
         List<PaintKey> wasdKeys = _wasdKeys;
         bool flag = _player.frozen || _player.tongued || _player.webbed || _player.stoned;
         if (_player.DeadOrGhost)
         {
             SetGroupClear(wasdKeys);
         }
         else if (flag)
         {
             SetGroupColorBase(wasdKeys, PainterColors.DangerKeyBlocked);
         }
         else
         {
             SetGroupColorBase(wasdKeys, PainterColors.MovementKeys);
         }
     }
References _player, _wasdKeys, ChromaHotkeyPainter.PainterColors.DangerKeyBlocked, Player.DeadOrGhost, Player.frozen, ChromaHotkeyPainter.PainterColors.MovementKeys, SetGroupClear(), SetGroupColorBase(), Player.stoned, Player.tongued, and Player.webbed.
Referenced by Update().