Terraria: ChromaHotkeyPainter.Step_Mount
Step_Mount()
void ChromaHotkeyPainter.Step_Mount () inline private
     {
         PaintKey mountKey = _mountKey;
         if (_player.QuickMount_GetItemToUse() == null || _player.DeadOrGhost)
         {
             mountKey.SetClear();
         }
         else if (_player.frozen || _player.tongued || _player.webbed || _player.stoned || _player.gravDir == -1f || _player.noItems)
         {
             mountKey.SetSolid(PainterColors.DangerKeyBlocked);
             if (_player.gravDir == -1f)
             {
                 mountKey.SetSolid(PainterColors.DangerKeyBlocked * 0.6f);
             }
         }
         else
         {
             mountKey.SetSolid(PainterColors.QuickMount);
         }
     }
References _mountKey, _player, ChromaHotkeyPainter.PainterColors.DangerKeyBlocked, Player.DeadOrGhost, Player.frozen, Player.gravDir, Player.noItems, ChromaHotkeyPainter.PainterColors.QuickMount, Player.QuickMount_GetItemToUse(), ChromaHotkeyPainter.PaintKey.SetClear(), ChromaHotkeyPainter.PaintKey.SetSolid(), Player.stoned, Player.tongued, and Player.webbed.