Terraria: WorldFileData.GetFullSeedText
GetFullSeedText()
string WorldFileData.GetFullSeedText (bool allowCropping = false) inline
     {
         int num = 0;
         if (WorldSizeX == 4200 && WorldSizeY == 1200)
         {
             num = 1;
         }
         if (WorldSizeX == 6400 && WorldSizeY == 1800)
         {
             num = 2;
         }
         if (WorldSizeX == 8400 && WorldSizeY == 2400)
         {
             num = 3;
         }
         int num2 = 0;
         if (HasCorruption)
         {
             num2 = 1;
         }
         if (HasCrimson)
         {
             num2 = 2;
         }
         int num3 = GameMode + 1;
         string text = _seedText;
         if (allowCropping)
         {
             int num4 = 340;
             text = FontAssets.MouseText.Value.CreateCroppedText(text, (float)num4);
         }
         return $"{num}.{num3}.{num2}.{text}";
     }
References _seedText, GameMode, HasCorruption, HasCrimson, FontAssets.MouseText, Asset< T >.Value, WorldSizeX, and WorldSizeY.
Referenced by UIWorldListItem.SeedButtonClick(), UIWorldListItem.SeedMouseOver(), and Main.startDedInputCallBack().