Terraria: WorldFileData.MoveToCloud
MoveToCloud()
override void WorldFileData.MoveToCloud () inline virtual
Implements FileData.
     {
         if (!base.IsCloudSave)
         {
             string worldPathFromName = Main.GetWorldPathFromName(Name, cloudSave: true);
             if (FileUtilities.MoveToCloud(base.Path, worldPathFromName))
             {
                 Main.LocalFavoriteData.ClearEntry(this);
                 _isCloudSave = true;
                 _path = worldPathFromName;
                 Main.CloudFavoritesData.SaveFavorite(this);
             }
         }
     }
References FileData._isCloudSave, FileData._path, FavoritesFile.ClearEntry(), Main.CloudFavoritesData, Main.GetWorldPathFromName(), Main.LocalFavoriteData, FileUtilities.MoveToCloud(), FileData.Name, and FavoritesFile.SaveFavorite().
Referenced by UIWorldListItem.CloudButtonClick().