Terraria: System.Text.Encodings.Web.DefaultHtmlEncoder.EscaperImplementation.EncodeUtf8
EncodeUtf8()
override int System.Text.Encodings.Web.DefaultHtmlEncoder.EscaperImplementation.EncodeUtf8 (Rune value, Span< byte > destination) inline package
Definition at line 17 of file DefaultHtmlEncoder.cs.
        {
            if (value.Value == 60)
            {
                if (SpanUtility.TryWriteBytes(destination, 38, 108, 116, 59))
                {
                    return 4;
                }
            }
            else if (value.Value == 62)
            {
                if (SpanUtility.TryWriteBytes(destination, 38, 103, 116, 59))
                {
                    return 4;
                }
            }
            else if (value.Value == 38)
            {
                if (SpanUtility.TryWriteBytes(destination, 38, 97, 109, 112, 59))
                {
                    return 5;
                }
            }
            else
            {
                if (value.Value != 34)
                {
                    return TryEncodeScalarAsHex(this, (uint)value.Value, destination);
                }
                if (SpanUtility.TryWriteBytes(destination, 38, 113, 117, 111, 116, 59))
                {
                    return 6;
                }
            }
            return -1;
            static int TryEncodeScalarAsHex(object @this, uint scalarValue, Span<byte> destination)
            {
                int num = (int)((uint)BitOperations.Log2(scalarValue) / 4u + 4);
                if (SpanUtility.IsValidIndex(destination, num))
                {
                    destination[num] = 59;
                    SpanUtility.TryWriteBytes(destination, 38, 35, 120, 48);
                    destination = destination.Slice(3, num - 3);
                    int num2 = destination.Length - 1;
                    while (SpanUtility.IsValidIndex(destination, num2))
                    {
                        char c = System.HexConverter.ToCharUpper((int)scalarValue);
                        destination[num2] = (byte)c;
                        scalarValue >>= 4;
                        num2--;
                    }
                    return destination.Length + 4;
                }
                return -1;
            }
        }
References System.destination, System.Numerics.BitOperations.Log2(), System.HexConverter.ToCharUpper(), System.Text.Encodings.Web.SpanUtility.TryWriteBytes(), and System.Text.Encodings.Web.value.