Terraria: System.Text.Encodings.Web.DefaultHtmlEncoder.EscaperImplementation.EncodeUtf16
EncodeUtf16()
override int System.Text.Encodings.Web.DefaultHtmlEncoder.EscaperImplementation.EncodeUtf16 (Rune value, Span< char > destination) inline package
Definition at line 74 of file DefaultHtmlEncoder.cs.
        {
            if (value.Value == 60)
            {
                if (SpanUtility.TryWriteChars(destination, '&', 'l', 't', ';'))
                {
                    return 4;
                }
            }
            else if (value.Value == 62)
            {
                if (SpanUtility.TryWriteChars(destination, '&', 'g', 't', ';'))
                {
                    return 4;
                }
            }
            else if (value.Value == 38)
            {
                if (SpanUtility.TryWriteChars(destination, '&', 'a', 'm', 'p', ';'))
                {
                    return 5;
                }
            }
            else
            {
                if (value.Value != 34)
                {
                    return TryEncodeScalarAsHex(this, (uint)value.Value, destination);
                }
                if (SpanUtility.TryWriteChars(destination, '&', 'q', 'u', 'o', 't', ';'))
                {
                    return 6;
                }
            }
            return -1;
            static int TryEncodeScalarAsHex(object @this, uint scalarValue, Span<char> destination)
            {
                int num = (int)((uint)BitOperations.Log2(scalarValue) / 4u + 4);
                if (SpanUtility.IsValidIndex(destination, num))
                {
                    destination[num] = ';';
                    SpanUtility.TryWriteChars(destination, '&', '#', 'x', '0');
                    destination = destination.Slice(3, num - 3);
                    int num2 = destination.Length - 1;
                    while (SpanUtility.IsValidIndex(destination, num2))
                    {
                        char c = System.HexConverter.ToCharUpper((int)scalarValue);
                        destination[num2] = c;
                        scalarValue >>= 4;
                        num2--;
                    }
                    return destination.Length + 4;
                }
                return -1;
            }
        }
References System.destination, System.Numerics.BitOperations.Log2(), System.HexConverter.ToCharUpper(), System.Text.Encodings.Web.SpanUtility.TryWriteChars(), and System.Text.Encodings.Web.value.