Terraria: System.Collections.Immutable.ImmutableSortedSet.Node.Freeze
Freeze()
void System.Collections.Immutable.ImmutableSortedSet< T >.Node.Freeze () inline package
Definition at line 749 of file ImmutableSortedSet.cs.
        {
            if (!_frozen)
            {
                _left.Freeze();
                _right.Freeze();
                _frozen = true;
            }
        }
References System.Collections.Immutable.ImmutableSortedSet< T >.Node._frozen, System.Collections.Immutable.ImmutableSortedSet< T >.Node._left, System.Collections.Immutable.ImmutableSortedSet< T >.Node._right, and System.Collections.Immutable.ImmutableSortedSet< T >.Node.Freeze().
Referenced by System.Collections.Immutable.ImmutableSortedSet< T >.ImmutableSortedSet(), and System.Collections.Immutable.ImmutableSortedSet< T >.Node.Freeze().