Terraria: System.Collections.Immutable.ImmutableSortedSet.Node.Add
Add()
Node System.Collections.Immutable.ImmutableSortedSet< T >.Node.Add (T key, IComparer< T > comparer, out bool mutated) inline package
Definition at line 645 of file ImmutableSortedSet.cs.
        {
            Requires.NotNull(comparer, "comparer");
            if (IsEmpty)
            {
                mutated = true;
                return new Node(key, this, this);
            }
            Node node = this;
            int num = comparer.Compare(key, _key);
            if (num > 0)
            {
                Node right = _right.Add(key, comparer, out mutated);
                if (mutated)
                {
                    node = Mutate(null, right);
                }
            }
            else
            {
                if (num >= 0)
                {
                    mutated = false;
                    return this;
                }
                Node left = _left.Add(key, comparer, out mutated);
                if (mutated)
                {
                    node = Mutate(left);
                }
            }
            if (!mutated)
            {
                return node;
            }
            return MakeBalanced(node);
        }
References System.Collections.Immutable.ImmutableSortedSet< T >.Node.Node(), System.Collections.Immutable.ImmutableSortedSet< T >.Node._key, System.Collections.Immutable.ImmutableSortedSet< T >.Node._left, System.Collections.Immutable.ImmutableSortedSet< T >.Node._right, System.Collections.Immutable.ImmutableSortedSet< T >.Node.Add(), System.comparer, System.Collections.Immutable.ImmutableSortedSet< T >.Node.IsEmpty, System.key, System.Collections.Immutable.ImmutableSortedSet< T >.Node.MakeBalanced(), and System.Collections.Immutable.ImmutableSortedSet< T >.Node.Mutate().
Referenced by System.Collections.Immutable.ImmutableSortedSet< T >.Builder.Add(), System.Collections.Immutable.ImmutableSortedSet< T >.Node.Add(), System.Collections.Immutable.ImmutableSortedSet< T >.Add(), and System.Collections.Immutable.ImmutableSortedSet< T >.Builder.UnionWith().