Terraria: System.Collections.Immutable.ImmutableSortedSet.Node.ItemRefUnchecked
ItemRefUnchecked()
ref readonly T System.Collections.Immutable.ImmutableSortedSet< T >.Node.ItemRefUnchecked (int index) inline private
Definition at line 584 of file ImmutableSortedSet.cs.
        {
            if (index < _left._count)
            {
                return ref _left.ItemRefUnchecked(index);
            }
            if (index > _left._count)
            {
                return ref _right.ItemRefUnchecked(index - _left._count - 1);
            }
            return ref _key;
        }
References System.Collections.Immutable.ImmutableSortedSet< T >.Node._count, System.Collections.Immutable.ImmutableSortedSet< T >.Node._key, System.Collections.Immutable.ImmutableSortedSet< T >.Node._left, System.Collections.Immutable.ImmutableSortedSet< T >.Node._right, System.index, and System.Collections.Immutable.ImmutableSortedSet< T >.Node.ItemRefUnchecked().
Referenced by System.Collections.Immutable.ImmutableSortedSet< T >.Node.ItemRef(), and System.Collections.Immutable.ImmutableSortedSet< T >.Node.ItemRefUnchecked().