Terraria: System.Collections.Immutable.ImmutableSortedSet.Node.Remove
Remove()
Node System.Collections.Immutable.ImmutableSortedSet< T >.Node.Remove (T key, IComparer< T > comparer, out bool mutated) inline package
Definition at line 683 of file ImmutableSortedSet.cs.
        {
            Requires.NotNull(comparer, "comparer");
            if (IsEmpty)
            {
                mutated = false;
                return this;
            }
            Node node = this;
            int num = comparer.Compare(key, _key);
            if (num == 0)
            {
                mutated = true;
                if (_right.IsEmpty && _left.IsEmpty)
                {
                    node = EmptyNode;
                }
                else if (_right.IsEmpty && !_left.IsEmpty)
                {
                    node = _left;
                }
                else if (!_right.IsEmpty && _left.IsEmpty)
                {
                    node = _right;
                }
                else
                {
                    Node node2 = _right;
                    while (!node2._left.IsEmpty)
                    {
                        node2 = node2._left;
                    }
                    bool mutated2;
                    Node right = _right.Remove(node2._key, comparer, out mutated2);
                    node = node2.Mutate(_left, right);
                }
            }
            else if (num < 0)
            {
                Node left = _left.Remove(key, comparer, out mutated);
                if (mutated)
                {
                    node = Mutate(left);
                }
            }
            else
            {
                Node right2 = _right.Remove(key, comparer, out mutated);
                if (mutated)
                {
                    node = Mutate(null, right2);
                }
            }
            if (!node.IsEmpty)
            {
                return MakeBalanced(node);
            }
            return node;
        }
References System.Collections.Immutable.ImmutableSortedSet< T >.Node._key, System.Collections.Immutable.ImmutableSortedSet< T >.Node._left, System.Collections.Immutable.ImmutableSortedSet< T >.Node._right, System.comparer, System.Collections.Immutable.ImmutableSortedSet< T >.Node.EmptyNode, System.Collections.Immutable.ImmutableSortedSet< T >.Node.IsEmpty, System.key, System.Collections.Immutable.ImmutableSortedSet< T >.Node.MakeBalanced(), System.Collections.Immutable.ImmutableSortedSet< T >.Node.Mutate(), and System.Collections.Immutable.ImmutableSortedSet< T >.Node.Remove().
Referenced by System.Collections.Immutable.ImmutableSortedSet< T >.Builder.ExceptWith(), System.Collections.Immutable.ImmutableSortedSet< T >.Builder.Remove(), System.Collections.Immutable.ImmutableSortedSet< T >.Node.Remove(), and System.Collections.Immutable.ImmutableSortedSet< T >.Remove().