Terraria: System.Collections.Immutable.ImmutableSortedSet.Node.Search
Search()
Node System.Collections.Immutable.ImmutableSortedSet< T >.Node.Search (T key, IComparer< T > comparer) inline package
Definition at line 759 of file ImmutableSortedSet.cs.
        {
            Requires.NotNull(comparer, "comparer");
            if (IsEmpty)
            {
                return this;
            }
            int num = comparer.Compare(key, _key);
            if (num == 0)
            {
                return this;
            }
            if (num > 0)
            {
                return _right.Search(key, comparer);
            }
            return _left.Search(key, comparer);
        }
References System.Collections.Immutable.ImmutableSortedSet< T >.Node._key, System.Collections.Immutable.ImmutableSortedSet< T >.Node._left, System.Collections.Immutable.ImmutableSortedSet< T >.Node._right, System.comparer, System.Collections.Immutable.ImmutableSortedSet< T >.Node.IsEmpty, System.key, and System.Collections.Immutable.ImmutableSortedSet< T >.Node.Search().
Referenced by System.Collections.Immutable.ImmutableSortedSet< T >.Node.Contains(), System.Collections.Immutable.ImmutableSortedSet< T >.Node.Search(), System.Collections.Immutable.ImmutableSortedSet< T >.Builder.TryGetValue(), and System.Collections.Immutable.ImmutableSortedSet< T >.TryGetValue().