Terraria: System.Collections.Immutable.ImmutableSortedSet.Node.MakeBalanced
MakeBalanced()
static Node System.Collections.Immutable.ImmutableSortedSet< T >.Node.MakeBalanced (Node tree) inline static private
Definition at line 875 of file ImmutableSortedSet.cs.
        {
            Requires.NotNull(tree, "tree");
            if (IsRightHeavy(tree))
            {
                if (Balance(tree._right) >= 0)
                {
                    return RotateLeft(tree);
                }
                return DoubleLeft(tree);
            }
            if (IsLeftHeavy(tree))
            {
                if (Balance(tree._left) <= 0)
                {
                    return RotateRight(tree);
                }
                return DoubleRight(tree);
            }
            return tree;
        }
References System.Collections.Immutable.ImmutableSortedSet< T >.Node.Balance(), System.Collections.Immutable.ImmutableSortedSet< T >.Node.DoubleLeft(), System.Collections.Immutable.ImmutableSortedSet< T >.Node.DoubleRight(), System.Collections.Immutable.ImmutableSortedSet< T >.Node.IsLeftHeavy(), System.Collections.Immutable.ImmutableSortedSet< T >.Node.IsRightHeavy(), System.Collections.Immutable.ImmutableSortedSet< T >.Node.RotateLeft(), and System.Collections.Immutable.ImmutableSortedSet< T >.Node.RotateRight().
Referenced by System.Collections.Immutable.ImmutableSortedSet< T >.Node.Add(), and System.Collections.Immutable.ImmutableSortedSet< T >.Node.Remove().