Terraria: System.Collections.Immutable.ImmutableSortedSet.Node.IndexOf
IndexOf()
int System.Collections.Immutable.ImmutableSortedSet< T >.Node.IndexOf (T key, IComparer< T > comparer) inline package
Definition at line 778 of file ImmutableSortedSet.cs.
        {
            Requires.NotNull(comparer, "comparer");
            if (IsEmpty)
            {
                return -1;
            }
            int num = comparer.Compare(key, _key);
            if (num == 0)
            {
                return _left.Count;
            }
            if (num > 0)
            {
                int num2 = _right.IndexOf(key, comparer);
                bool flag = num2 < 0;
                if (flag)
                {
                    num2 = ~num2;
                }
                num2 = _left.Count + 1 + num2;
                if (flag)
                {
                    num2 = ~num2;
                }
                return num2;
            }
            return _left.IndexOf(key, comparer);
        }
References System.Collections.Immutable.ImmutableSortedSet< T >.Node._key, System.Collections.Immutable.ImmutableSortedSet< T >.Node._left, System.Collections.Immutable.ImmutableSortedSet< T >.Node._right, System.comparer, System.Collections.Immutable.ImmutableSortedSet< T >.Node.Count, System.Collections.Immutable.ImmutableSortedSet< T >.Node.IndexOf(), System.Collections.Immutable.ImmutableSortedSet< T >.Node.IsEmpty, and System.key.
Referenced by System.Collections.Immutable.ImmutableSortedSet< T >.IndexOf(), and System.Collections.Immutable.ImmutableSortedSet< T >.Node.IndexOf().