Terraria: System.Threading.CountdownEvent.Reset
Reset() [2/2]
void System.Threading.CountdownEvent.Reset (int count) inline
Definition at line 174 of file CountdownEvent.cs.
    {
        ThrowIfDisposed();
        if (count < 0)
        {
            throw new ArgumentOutOfRangeException("count");
        }
        _currentCount = count;
        _initialCount = count;
        if (count == 0)
        {
            _event.Set();
        }
        else
        {
            _event.Reset();
        }
    }
References System.Threading.CountdownEvent._currentCount, System.Threading.CountdownEvent._event, System.Threading.CountdownEvent._initialCount, System.count, System.Threading.ManualResetEventSlim.Reset(), System.Threading.ManualResetEventSlim.Set(), and System.Threading.CountdownEvent.ThrowIfDisposed().