Terraria: System.Threading.CountdownEvent.Signal
Signal() [1/2]
bool System.Threading.CountdownEvent.Signal () inline
Definition at line 73 of file CountdownEvent.cs.
    {
        ThrowIfDisposed();
        if (_currentCount <= 0)
        {
            throw new InvalidOperationException(System.SR.CountdownEvent_Decrement_BelowZero);
        }
        int num = Interlocked.Decrement(ref _currentCount);
        if (num == 0)
        {
            _event.Set();
            return true;
        }
        if (num < 0)
        {
            throw new InvalidOperationException(System.SR.CountdownEvent_Decrement_BelowZero);
        }
        return false;
    }
References System.Threading.CountdownEvent._currentCount, System.Threading.CountdownEvent._event, System.SR.CountdownEvent_Decrement_BelowZero, System.Threading.Interlocked.Decrement(), System.Threading.ManualResetEventSlim.Set(), and System.Threading.CountdownEvent.ThrowIfDisposed().
Referenced by System.Linq.Parallel.HashRepartitionEnumerator< TInputOutput, THashKey, TIgnoreKey >.Dispose(), System.Linq.Parallel.OrderedHashRepartitionEnumerator< TInputOutput, THashKey, TOrderKey >.Dispose(), System.Linq.Parallel.HashRepartitionEnumerator< TInputOutput, THashKey, TIgnoreKey >.EnumerateAndRedistributeElements(), System.Linq.Parallel.OrderedHashRepartitionEnumerator< TInputOutput, THashKey, TOrderKey >.EnumerateAndRedistributeElements(), ReLogic.Threading.FastParallel.RangeTask.Invoke(), System.Linq.Parallel.TakeOrSkipQueryOperator< TResult >.TakeOrSkipQueryOperatorEnumerator< TKey >.MoveNext(), System.Linq.Parallel.TakeOrSkipWhileQueryOperator< TResult >.TakeOrSkipWhileQueryOperatorEnumerator< TKey >.MoveNext(), System.Linq.Parallel.DefaultIfEmptyQueryOperator< TSource >.DefaultIfEmptyQueryOperatorEnumerator< TKey >.MoveNext(), System.Linq.Parallel.FirstQueryOperator< TSource >.FirstQueryOperatorEnumerator< TKey >.MoveNext(), and System.Linq.Parallel.LastQueryOperator< TSource >.LastQueryOperatorEnumerator< TKey >.MoveNext().