Terraria: System.IO.Stream.ReadWriteTask.ReadWriteTask
ReadWriteTask()
System.IO.Stream.ReadWriteTask.ReadWriteTask (bool isRead, bool apm, Func< object, int > function, object state, Stream stream, byte[] buffer, int offset, int count, AsyncCallback callback) inline
Definition at line 51 of file Stream.cs.
            : base(function, state, CancellationToken.None, TaskCreationOptions.DenyChildAttach)
        {
            _isRead = isRead;
            _apm = apm;
            _stream = stream;
            _buffer = buffer;
            _offset = offset;
            _count = count;
            if (callback != null)
            {
                _callback = callback;
                _context = ExecutionContext.Capture();
                AddCompletionAction(this);
            }
        }
References System.IO.Stream.ReadWriteTask._apm, System.IO.Stream.ReadWriteTask._buffer, System.IO.Stream.ReadWriteTask._callback, System.IO.Stream.ReadWriteTask._context, System.IO.Stream.ReadWriteTask._count, System.IO.Stream.ReadWriteTask._isRead, System.IO.Stream.ReadWriteTask._offset, System.IO.Stream.ReadWriteTask._stream, System.Threading.Tasks.Task< int >.AddCompletionAction(), System.buffer, System.Threading.ExecutionContext.Capture(), System.count, System.offset, and System.stream.
Referenced by System.IO.Stream.ReadWriteTask.InvokeAsyncCallback().