Terraria: System.Threading.CountdownEvent.TryAddCount
TryAddCount() [2/2]
bool System.Threading.CountdownEvent.TryAddCount (int signalCount) inline
Definition at line 141 of file CountdownEvent.cs.
    {
        if (signalCount <= 0)
        {
            throw new ArgumentOutOfRangeException("signalCount");
        }
        ThrowIfDisposed();
        SpinWait spinWait = default(SpinWait);
        while (true)
        {
            int currentCount = _currentCount;
            if (currentCount <= 0)
            {
                return false;
            }
            if (currentCount > int.MaxValue - signalCount)
            {
                throw new InvalidOperationException(System.SR.CountdownEvent_Increment_AlreadyMax);
            }
            if (Interlocked.CompareExchange(ref _currentCount, currentCount + signalCount, currentCount) == currentCount)
            {
                break;
            }
            spinWait.SpinOnce(-1);
        }
        return true;
    }
References System.Threading.CountdownEvent._currentCount, System.Threading.Interlocked.CompareExchange(), System.SR.CountdownEvent_Increment_AlreadyMax, System.Threading.SpinWait.SpinOnce(), and System.Threading.CountdownEvent.ThrowIfDisposed().