Terraria: System.Threading.CountdownEvent.Wait
Wait() [1/6]
void System.Threading.CountdownEvent.Wait () inline
Definition at line 194 of file CountdownEvent.cs.
    {
        Wait(-1, CancellationToken.None);
    }
References System.Threading.CancellationToken.None, and System.Threading.CountdownEvent.Wait().
Referenced by ReLogic.Threading.FastParallel.For(), System.Linq.Parallel.TakeOrSkipQueryOperator< TResult >.TakeOrSkipQueryOperatorEnumerator< TKey >.MoveNext(), System.Linq.Parallel.TakeOrSkipWhileQueryOperator< TResult >.TakeOrSkipWhileQueryOperatorEnumerator< TKey >.MoveNext(), System.Linq.Parallel.DefaultIfEmptyQueryOperator< TSource >.DefaultIfEmptyQueryOperatorEnumerator< TKey >.MoveNext(), System.Linq.Parallel.FirstQueryOperator< TSource >.FirstQueryOperatorEnumerator< TKey >.MoveNext(), System.Linq.Parallel.LastQueryOperator< TSource >.LastQueryOperatorEnumerator< TKey >.MoveNext(), System.Linq.Parallel.OrderedHashRepartitionEnumerator< TInputOutput, THashKey, TOrderKey >.MoveNext(), System.Linq.Parallel.HashRepartitionEnumerator< TInputOutput, THashKey, TIgnoreKey >.MoveNext(), System.Threading.CountdownEvent.Wait(), System.Threading.CountdownEvent.Wait(), System.Threading.CountdownEvent.Wait(), System.Threading.CountdownEvent.Wait(), and System.Threading.CountdownEvent.Wait().