Terraria: System.Threading.CountdownEvent.Signal
Signal() [2/2]
bool System.Threading.CountdownEvent.Signal (int signalCount) inline
Definition at line 93 of file CountdownEvent.cs.
    {
        if (signalCount <= 0)
        {
            throw new ArgumentOutOfRangeException("signalCount");
        }
        ThrowIfDisposed();
        SpinWait spinWait = default(SpinWait);
        int currentCount;
        while (true)
        {
            currentCount = _currentCount;
            if (currentCount < signalCount)
            {
                throw new InvalidOperationException(System.SR.CountdownEvent_Decrement_BelowZero);
            }
            if (Interlocked.CompareExchange(ref _currentCount, currentCount - signalCount, currentCount) == currentCount)
            {
                break;
            }
            spinWait.SpinOnce(-1);
        }
        if (currentCount == signalCount)
        {
            _event.Set();
            return true;
        }
        return false;
    }
References System.Threading.CountdownEvent._currentCount, System.Threading.CountdownEvent._event, System.Threading.Interlocked.CompareExchange(), System.SR.CountdownEvent_Decrement_BelowZero, System.Threading.ManualResetEventSlim.Set(), System.Threading.SpinWait.SpinOnce(), and System.Threading.CountdownEvent.ThrowIfDisposed().