Terraria: System.Security.Cryptography.X509Certificates.ECDsaX509SignatureGenerator.BuildPublicKey
BuildPublicKey()
override PublicKey System.Security.Cryptography.X509Certificates.ECDsaX509SignatureGenerator.BuildPublicKey () inline protected
Definition at line 47 of file ECDsaX509SignatureGenerator.cs.
    {
        ECParameters eCParameters = _key.ExportParameters(includePrivateParameters: false);
        if (!eCParameters.Curve.IsNamed)
        {
            throw new InvalidOperationException(System.SR.Cryptography_ECC_NamedCurvesOnly);
        }
        string text = eCParameters.Curve.Oid.Value;
        if (string.IsNullOrEmpty(text))
        {
            string friendlyName = eCParameters.Curve.Oid.FriendlyName;
            text = friendlyName switch
            {
                "nistP256" => "1.2.840.10045.3.1.7",
                "nistP384" => "1.3.132.0.34",
                "nistP521" => "1.3.132.0.35",
                _ => new Oid(friendlyName).Value,
            };
        }
        AsnWriter asnWriter = new AsnWriter(AsnEncodingRules.DER);
        asnWriter.WriteObjectIdentifier(text);
        byte[] rawData = asnWriter.Encode();
        byte[] array = new byte[1 + eCParameters.Q.X.Length + eCParameters.Q.Y.Length];
        array[0] = 4;
        Buffer.BlockCopy(eCParameters.Q.X, 0, array, 1, eCParameters.Q.X.Length);
        Buffer.BlockCopy(eCParameters.Q.Y, 0, array, 1 + eCParameters.Q.X.Length, eCParameters.Q.Y.Length);
        Oid ecPublicKeyOid = System.Security.Cryptography.Oids.EcPublicKeyOid;
        return new PublicKey(ecPublicKeyOid, new AsnEncodedData(ecPublicKeyOid, rawData), new AsnEncodedData(ecPublicKeyOid, array));
    }
References System.Security.Cryptography.X509Certificates.ECDsaX509SignatureGenerator._key, System.array, System.Buffer.BlockCopy(), System.SR.Cryptography_ECC_NamedCurvesOnly, System.Security.Cryptography.ECParameters.Curve, System.Security.Cryptography.Oids.EcPublicKeyOid, System.Formats.Asn1.AsnWriter.Encode(), System.Security.Cryptography.ECDsa.ExportParameters(), System.Security.Cryptography.Oid.FriendlyName, System.Security.Cryptography.ECCurve.IsNamed, System.Security.Cryptography.ECCurve.Oid, System.Security.Cryptography.X509Certificates.X509SignatureGenerator.PublicKey, System.Security.Cryptography.ECParameters.Q, System.text, System.Security.Cryptography.Oid.Value, System.Formats.Asn1.AsnWriter.WriteObjectIdentifier(), System.Security.Cryptography.ECPoint.X, and System.Security.Cryptography.ECPoint.Y.