Terraria: System.Security.Cryptography.X509Certificates.ECDsaX509SignatureGenerator.GetSignatureAlgorithmIdentifier
GetSignatureAlgorithmIdentifier()
override byte[] System.Security.Cryptography.X509Certificates.ECDsaX509SignatureGenerator.GetSignatureAlgorithmIdentifier (HashAlgorithmName hashAlgorithm) inline
Definition at line 15 of file ECDsaX509SignatureGenerator.cs.
    {
        string oidValue;
        if (hashAlgorithm == HashAlgorithmName.SHA256)
        {
            oidValue = "1.2.840.10045.4.3.2";
        }
        else if (hashAlgorithm == HashAlgorithmName.SHA384)
        {
            oidValue = "1.2.840.10045.4.3.3";
        }
        else
        {
            if (!(hashAlgorithm == HashAlgorithmName.SHA512))
            {
                throw new ArgumentOutOfRangeException("hashAlgorithm", hashAlgorithm, System.SR.Format(System.SR.Cryptography_UnknownHashAlgorithm, hashAlgorithm.Name));
            }
            oidValue = "1.2.840.10045.4.3.4";
        }
        AsnWriter asnWriter = new AsnWriter(AsnEncodingRules.DER);
        asnWriter.PushSequence();
        asnWriter.WriteObjectIdentifier(oidValue);
        asnWriter.PopSequence();
        return asnWriter.Encode();
    }
References System.SR.Cryptography_UnknownHashAlgorithm, System.Formats.Asn1.AsnWriter.Encode(), System.SR.Format(), System.Security.Cryptography.HashAlgorithmName.Name, System.Formats.Asn1.AsnWriter.PopSequence(), System.Formats.Asn1.AsnWriter.PushSequence(), System.Security.Cryptography.HashAlgorithmName.SHA256, System.Security.Cryptography.HashAlgorithmName.SHA384, System.Security.Cryptography.HashAlgorithmName.SHA512, and System.Formats.Asn1.AsnWriter.WriteObjectIdentifier().