Terraria: System.AppContext.GetBaseDirectoryCore
GetBaseDirectoryCore()
static string System.AppContext.GetBaseDirectoryCore () inline static private
Definition at line 132 of file AppContext.cs.
    {
        string path = Assembly.GetEntryAssembly()?.Location;
        string text = Path.GetDirectoryName(path);
        if (text == null)
        {
            return string.Empty;
        }
        if (!Path.EndsInDirectorySeparator(text))
        {
            text += "\\";
        }
        return text;
    }
References System.IO.Path.EndsInDirectorySeparator(), System.IO.Path.GetDirectoryName(), System.Reflection.Assembly.GetEntryAssembly(), and System.text.