Terraria: System.AppContext.SetData
SetData()
static void System.AppContext.SetData (string name, object? data) inline static
Definition at line 48 of file AppContext.cs.
    {
        if (name == null)
        {
            throw new ArgumentNullException("name");
        }
        if (s_dataStore == null)
        {
            Interlocked.CompareExchange(ref s_dataStore, new Dictionary<string, object>(), null);
        }
        lock (s_dataStore)
        {
            s_dataStore[name] = data;
        }
    }
References System.Threading.Interlocked.CompareExchange(), and System.AppContext.s_dataStore.
Referenced by System.Threading.ThreadPool.InitializeConfigAndDetermineUsePortableThreadPool(), and System.AppDomain.SetData().