Terraria: System.Data.DataRowCollection.InsertAt
InsertAt()
void System.Data.DataRowCollection.InsertAt (DataRow row, int pos) inline
Definition at line 45 of file DataRowCollection.cs.
    {
        if (pos < 0)
        {
            throw ExceptionBuilder.RowInsertOutOfRange(pos);
        }
        if (pos >= _list.Count)
        {
            _table.AddRow(row, -1);
        }
        else
        {
            _table.InsertRow(row, -1, pos);
        }
    }
References System.Data.DataRowCollection._list, System.Data.DataRowCollection._table, System.Data.DataTable.AddRow(), System.Data.RBTree< K >.Count, System.Data.DataTable.InsertRow(), and System.Data.ExceptionBuilder.RowInsertOutOfRange().