Terraria: System.Data.DataRowCollection.IndexOf
IndexOf()
int System.Data.DataRowCollection.IndexOf (DataRow? row) inline
Definition at line 95 of file DataRowCollection.cs.
    {
        if (row != null && row.Table == _table && (row.RBTreeNodeId != 0 || row.RowState != DataRowState.Detached))
        {
            return _list.IndexOf(row.RBTreeNodeId, row);
        }
        return -1;
    }
References System.Data.DataRowCollection._list, System.Data.DataRowCollection._table, System.Data.RBTree< K >.IndexOf(), System.Data.DataRow.RBTreeNodeId, System.Data.DataRow.RowState, and System.Data.DataRow.Table.
Referenced by System.Data.Index.CompareRecords(), and System.Data.Index.InsertRecord().