Terraria: System.Data.DataRowCollection.Remove
Remove()
void System.Data.DataRowCollection.Remove (DataRow row) inline
Definition at line 185 of file DataRowCollection.cs.
    {
        if (row == null || row.Table != _table || -1 == row.rowID)
        {
            throw ExceptionBuilder.RowOutOfRange();
        }
        if (row.RowState != DataRowState.Deleted && row.RowState != DataRowState.Detached)
        {
            row.Delete();
        }
        if (row.RowState != DataRowState.Detached)
        {
            row.AcceptChanges();
        }
    }
References System.Data.DataRowCollection._table, System.Data.DataRow.AcceptChanges(), System.Data.DataRow.Delete(), System.Data.DataRow.rowID, System.Data.ExceptionBuilder.RowOutOfRange(), System.Data.DataRow.RowState, and System.Data.DataRow.Table.
Referenced by System.Data.DataRowCollection.RemoveAt().