Terraria: System.Data.DataRowCollection.ArrayRemove
ArrayRemove()
void System.Data.DataRowCollection.ArrayRemove (DataRow row) inline package
Definition at line 135 of file DataRowCollection.cs.
    {
        if (row.RBTreeNodeId == 0)
        {
            throw ExceptionBuilder.InternalRBTreeError(RBTreeError.AttachedNodeWithZerorbTreeNodeId);
        }
        _list.RBDelete(row.RBTreeNodeId);
        row.RBTreeNodeId = 0;
    }
References System.Data.DataRowCollection._list, System.Data.ExceptionBuilder.InternalRBTreeError(), System.Data.RBTree< K >.RBDelete(), and System.Data.DataRow.RBTreeNodeId.
Referenced by System.Data.DataTable.RemoveRow().