Terraria: BallCollision.IsNeighborSolid
IsNeighborSolid()
static bool BallCollision.IsNeighborSolid (Tile tile) inline static private
     {
         if (tile != null && tile.nactive() && Main.tileSolid[tile.type])
         {
             return !Main.tileSolidTop[tile.type];
         }
         return false;
     }
References Tile.nactive(), Main.tileSolid, Main.tileSolidTop, and Tile.type.
Referenced by GetLeftOrRightEdge(), and GetTopOrBottomEdge().