Terraria: BallCollision.GetCollisionPointForTile
GetCollisionPointForTile()
static bool BallCollision.GetCollisionPointForTile (TileEdges edgesToTest, int x, int y, Vector2 center, ref Vector2 closestPointOut, ref float distanceSquaredOut) inline static private
     {
         Tile tile = Main.tile[x, y];
         if (tile == null || !tile.nactive() || (!Main.tileSolid[tile.type] && !Main.tileSolidTop[tile.type]))
         {
             return false;
         }
         if (!Main.tileSolid[tile.type] && Main.tileSolidTop[tile.type] && tile.frameY != 0)
         {
             return false;
         }
         if (Main.tileSolidTop[tile.type])
         {
             edgesToTest &= TileEdges.Top | TileEdges.BottomLeftSlope | TileEdges.BottomRightSlope;
         }
         Vector2 tilePosition = new Vector2((float)x * 16f, (float)y * 16f);
         bool flag = false;
         LineSegment edge = default(LineSegment);
         if (GetSlopeEdge(ref edgesToTest, tile, tilePosition, ref edge))
         {
             closestPointOut = ClosestPointOnLineSegment(center, edge);
             distanceSquaredOut = Vector2.DistanceSquared(closestPointOut, center);
             flag = true;
         }
         if (GetTopOrBottomEdge(edgesToTest, x, y, tilePosition, ref edge))
         {
             Vector2 vector = ClosestPointOnLineSegment(center, edge);
             float num = Vector2.DistanceSquared(vector, center);
             if (!flag || num < distanceSquaredOut)
             {
                 distanceSquaredOut = num;
                 closestPointOut = vector;
             }
             flag = true;
         }
         if (GetLeftOrRightEdge(edgesToTest, x, y, tilePosition, ref edge))
         {
             Vector2 vector2 = ClosestPointOnLineSegment(center, edge);
             float num2 = Vector2.DistanceSquared(vector2, center);
             if (!flag || num2 < distanceSquaredOut)
             {
                 distanceSquaredOut = num2;
                 closestPointOut = vector2;
             }
             flag = true;
         }
         return flag;
     }
References ClosestPointOnLineSegment(), Tile.frameY, GetLeftOrRightEdge(), GetSlopeEdge(), GetTopOrBottomEdge(), Tile.nactive(), Main.tile, Main.tileSolid, Main.tileSolidTop, and Tile.type.
Referenced by GetClosestEdgeToCircle().