Terraria: BallCollision.GetLeftOrRightEdge
GetLeftOrRightEdge()
static bool BallCollision.GetLeftOrRightEdge (TileEdges edgesToTest, int x, int y, Vector2 tilePosition, ref LineSegment edge) inline static private
     {
         if ((edgesToTest & TileEdges.Left) != 0)
         {
             Tile tile = Main.tile[x, y];
             Tile tile2 = Main.tile[x - 1, y];
             if (IsNeighborSolid(tile2) && tile2.slope() != 1 && tile2.slope() != 3 && (!tile2.halfBrick() || tile.halfBrick()))
             {
                 return false;
             }
             edge.Start = new Vector2(tilePosition.X, tilePosition.Y);
             edge.End = new Vector2(tilePosition.X, tilePosition.Y + 16f);
             if (tile.halfBrick())
             {
                 edge.Start.Y += 8f;
             }
             return true;
         }
         if ((edgesToTest & TileEdges.Right) != 0)
         {
             Tile tile3 = Main.tile[x, y];
             Tile tile4 = Main.tile[x + 1, y];
             if (IsNeighborSolid(tile4) && tile4.slope() != 2 && tile4.slope() != 4 && (!tile4.halfBrick() || tile3.halfBrick()))
             {
                 return false;
             }
             edge.Start = new Vector2(tilePosition.X + 16f, tilePosition.Y);
             edge.End = new Vector2(tilePosition.X + 16f, tilePosition.Y + 16f);
             if (tile3.halfBrick())
             {
                 edge.Start.Y += 8f;
             }
             return true;
         }
         return false;
     }
References Tile.halfBrick(), IsNeighborSolid(), Tile.slope(), and Main.tile.
Referenced by GetCollisionPointForTile().