Terraria: BallCollision.CheckForPassThrough
CheckForPassThrough()
static bool BallCollision.CheckForPassThrough (Vector2 center, out BallPassThroughType type, out Tile contactTile) inline static private
     {
         Point tileCoordinates = center.ToTileCoordinates();
         Tile tile = (contactTile = Main.tile[tileCoordinates.X, tileCoordinates.Y]);
         type = BallPassThroughType.None;
         if (tile == null)
         {
             return false;
         }
         if (tile.nactive())
         {
             type = BallPassThroughType.Tile;
             return IsPositionInsideTile(center, tileCoordinates, tile);
         }
         if (tile.liquid > 0)
         {
             float num = (float)(tileCoordinates.Y + 1) * 16f - (float)(int)tile.liquid / 255f * 16f;
             switch (tile.liquidType())
             {
             case 1:
                 type = BallPassThroughType.Lava;
                 break;
             case 2:
                 type = BallPassThroughType.Honey;
                 break;
             default:
                 type = BallPassThroughType.Water;
                 break;
             }
             return num < center.Y;
         }
         return false;
     }
References Tile.Tile(), IsPositionInsideTile(), Tile.liquid, Tile.liquidType(), Tile.nactive(), and Main.tile.
Referenced by Step().