Terraria: TELogicSensor.FigureCheckType
FigureCheckType()
static LogicCheckType TELogicSensor.FigureCheckType (int x, int y, out bool on) inline static
     {
         on = false;
         if (!WorldGen.InWorld(x, y))
         {
             return LogicCheckType.None;
         }
         Tile tile = Main.tile[x, y];
         if (tile == null)
         {
             return LogicCheckType.None;
         }
         LogicCheckType result = LogicCheckType.None;
         switch (tile.frameY / 18)
         {
         case 0:
             result = LogicCheckType.Day;
             break;
         case 1:
             result = LogicCheckType.Night;
             break;
         case 2:
             result = LogicCheckType.PlayerAbove;
             break;
         case 3:
             result = LogicCheckType.Water;
             break;
         case 4:
             result = LogicCheckType.Lava;
             break;
         case 5:
             result = LogicCheckType.Honey;
             break;
         case 6:
             result = LogicCheckType.Liquid;
             break;
         }
         on = GetState(x, y, result);
         return result;
     }
References Tile.frameY, GetState(), WorldGen.InWorld(), and Main.tile.
Referenced by FigureCheckState(), and Hook_AfterPlacement().