Terraria: TELogicSensor.Hook_AfterPlacement
Hook_AfterPlacement()
static int TELogicSensor.Hook_AfterPlacement (int x, int y, int type = 423, int style = 0, int direction = 1, int alternate = 0) inline static
     {
         bool on;
         LogicCheckType logicCheckType = FigureCheckType(x, y, out on);
         GetFrame(x, y, logicCheckType, on);
         if (Main.netMode == 1)
         {
             NetMessage.SendTileSquare(Main.myPlayer, x, y);
             NetMessage.SendData(87, -1, -1, null, x, y, (int)_myEntityID);
             return -1;
         }
         int num = Place(x, y);
         ((TELogicSensor)TileEntity.ByID[num]).FigureCheckState();
         return num;
     }
References TELogicSensor(), _myEntityID, TileEntity.ByID, FigureCheckType(), GetFrame(), Main.myPlayer, Main.netMode, Place(), NetMessage.SendData(), and NetMessage.SendTileSquare().
Referenced by TileObjectData.Initialize().