Terraria: TELogicSensor.GetState
GetState()
static bool TELogicSensor.GetState (int x, int y, LogicCheckType type, TELogicSensor instance = null) inline static
     {
         switch (type)
         {
         case LogicCheckType.Day:
             return Main.dayTime;
         case LogicCheckType.Night:
             return !Main.dayTime;
         case LogicCheckType.PlayerAbove:
         {
             bool result = false;
             Rectangle value = new Rectangle(x * 16 - 32 - 1, y * 16 - 160 - 1, 82, 162);
             foreach (KeyValuePair<int, Rectangle> item in playerBox)
             {
                 if (item.Value.Intersects(value))
                 {
                     result = true;
                     break;
                 }
             }
             return result;
         }
         case LogicCheckType.Water:
         case LogicCheckType.Lava:
         case LogicCheckType.Honey:
         case LogicCheckType.Liquid:
         {
             if (instance == null)
             {
                 return false;
             }
             Tile tile = Main.tile[x, y];
             bool flag = true;
             if (tile == null || tile.liquid == 0)
             {
                 flag = false;
             }
             if (!tile.lava() && type == LogicCheckType.Lava)
             {
                 flag = false;
             }
             if (!tile.honey() && type == LogicCheckType.Honey)
             {
                 flag = false;
             }
             if ((tile.honey() || tile.lava()) && type == LogicCheckType.Water)
             {
                 flag = false;
             }
             if (!flag && instance.On)
             {
                 if (instance.CountedData == 0)
                 {
                     instance.CountedData = 15;
                 }
                 else if (instance.CountedData > 0)
                 {
                     instance.CountedData--;
                 }
                 flag = instance.CountedData > 0;
             }
             return flag;
         }
         default:
             return false;
         }
     }
References Main.dayTime, Tile.honey(), Tile.lava(), Tile.liquid, playerBox, Main.tile, and TileEntity.type.
Referenced by FigureCheckType(), and Update().