Terraria: Terraria.Graphics.Effects.FilterManager.Update
Update()
void Terraria.Graphics.Effects.FilterManager.Update (GameTime gameTime) inline
Definition at line 97 of file FilterManager.cs.
    {
        LinkedListNode<Filter> linkedListNode = _activeFilters.First;
        _ = _activeFilters.Count;
        int num = 0;
        while (linkedListNode != null)
        {
            Filter value = linkedListNode.Value;
            LinkedListNode<Filter> next = linkedListNode.Next;
            bool flag = false;
            if (value.Priority >= _priorityThreshold)
            {
                num++;
                if (num > _activeFilterCount - _filterLimit)
                {
                    value.Update(gameTime);
                    flag = true;
                }
            }
            if (value.Active && flag)
            {
                value.Opacity = Math.Min(value.Opacity + (float)gameTime.ElapsedGameTime.TotalSeconds * 1f, 1f);
            }
            else
            {
                value.Opacity = Math.Max(value.Opacity - (float)gameTime.ElapsedGameTime.TotalSeconds * 1f, 0f);
            }
            if (!value.Active && value.Opacity == 0f)
            {
                if (value.Priority >= _priorityThreshold)
                {
                    _activeFilterCount--;
                }
                _activeFilters.Remove(linkedListNode);
            }
            linkedListNode = next;
        }
    }
References Terraria.Graphics.Effects.FilterManager._activeFilterCount, Terraria.Graphics.Effects.FilterManager._activeFilters, Terraria.Graphics.Effects.FilterManager._filterLimit, Terraria.Graphics.Effects.FilterManager._priorityThreshold, System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Math.Max(), System.Math.Min(), System.Collections.Generic.Dictionary< TKey, TValue >.Remove(), and System.value.