Terraria: PlayerDrawSet.CreateCompositeData
CreateCompositeData()
void PlayerDrawSet.CreateCompositeData () inline private
     {
         frontShoulderOffset = Vector2.Zero;
         backShoulderOffset = Vector2.Zero;
         usesCompositeTorso = drawPlayer.body > 0 && drawPlayer.body < ArmorIDs.Body.Count && ArmorIDs.Body.Sets.UsesNewFramingCode[drawPlayer.body];
         usesCompositeFrontHandAcc = drawPlayer.handon > 0 && drawPlayer.handon < ArmorIDs.HandOn.Count && ArmorIDs.HandOn.Sets.UsesNewFramingCode[drawPlayer.handon];
         usesCompositeBackHandAcc = drawPlayer.handoff > 0 && drawPlayer.handoff < ArmorIDs.HandOff.Count && ArmorIDs.HandOff.Sets.UsesNewFramingCode[drawPlayer.handoff];
         if (drawPlayer.body < 1)
         {
             usesCompositeTorso = true;
         }
         if (!usesCompositeTorso)
         {
             return;
         }
         Point pt = new Point(1, 1);
         Point pt2 = new Point(0, 1);
         Point pt3 = default(Point);
         Point frameIndex = default(Point);
         Point frameIndex2 = default(Point);
         int num = drawPlayer.bodyFrame.Y / drawPlayer.bodyFrame.Height;
         compShoulderOverFrontArm = true;
         hideCompositeShoulders = false;
         bool flag = true;
         if (drawPlayer.body > 0)
         {
             flag = ArmorIDs.Body.Sets.showsShouldersWhileJumping[drawPlayer.body];
         }
         bool flag2 = false;
         if (drawPlayer.handon > 0)
         {
             flag2 = ArmorIDs.HandOn.Sets.UsesOldFramingTexturesForWalking[drawPlayer.handon];
         }
         bool flag3 = !flag2;
         switch (num)
         {
         case 0:
             frameIndex2.X = 2;
             flag3 = true;
             break;
         case 1:
             frameIndex2.X = 3;
             compShoulderOverFrontArm = false;
             flag3 = true;
             break;
         case 2:
             frameIndex2.X = 4;
             compShoulderOverFrontArm = false;
             flag3 = true;
             break;
         case 3:
             frameIndex2.X = 5;
             compShoulderOverFrontArm = true;
             flag3 = true;
             break;
         case 4:
             frameIndex2.X = 6;
             compShoulderOverFrontArm = true;
             flag3 = true;
             break;
         case 5:
             frameIndex2.X = 2;
             frameIndex2.Y = 1;
             pt3.X = 1;
             compShoulderOverFrontArm = false;
             flag3 = true;
             if (!flag)
             {
                 hideCompositeShoulders = true;
             }
             break;
         case 6:
             frameIndex2.X = 3;
             frameIndex2.Y = 1;
             break;
         case 7:
         case 8:
         case 9:
         case 10:
             frameIndex2.X = 4;
             frameIndex2.Y = 1;
             break;
         case 11:
         case 12:
         case 13:
             frameIndex2.X = 3;
             frameIndex2.Y = 1;
             break;
         case 14:
             frameIndex2.X = 5;
             frameIndex2.Y = 1;
             break;
         case 15:
         case 16:
             frameIndex2.X = 6;
             frameIndex2.Y = 1;
             break;
         case 17:
             frameIndex2.X = 5;
             frameIndex2.Y = 1;
             break;
         case 18:
         case 19:
             frameIndex2.X = 3;
             frameIndex2.Y = 1;
             break;
         }
         CreateCompositeData_DetermineShoulderOffsets(drawPlayer.body, num);
         backShoulderOffset *= new Vector2(drawPlayer.direction, drawPlayer.gravDir);
         frontShoulderOffset *= new Vector2(drawPlayer.direction, drawPlayer.gravDir);
         if (drawPlayer.body > 0 && ArmorIDs.Body.Sets.shouldersAreAlwaysInTheBack[drawPlayer.body])
         {
             compShoulderOverFrontArm = false;
         }
         usesCompositeFrontHandAcc = flag3;
         frameIndex.X = frameIndex2.X;
         frameIndex.Y = frameIndex2.Y + 2;
         UpdateCompositeArm(drawPlayer.compositeFrontArm, ref compositeFrontArmRotation, ref frameIndex2, 7);
         UpdateCompositeArm(drawPlayer.compositeBackArm, ref compositeBackArmRotation, ref frameIndex, 8);
         if (!drawPlayer.Male)
         {
             pt.Y += 2;
             pt2.Y += 2;
             pt3.Y += 2;
         }
         compBackShoulderFrame = CreateCompositeFrameRect(pt);
         compFrontShoulderFrame = CreateCompositeFrameRect(pt2);
         compBackArmFrame = CreateCompositeFrameRect(frameIndex);
         compFrontArmFrame = CreateCompositeFrameRect(frameIndex2);
         compTorsoFrame = CreateCompositeFrameRect(pt3);
     }
References backShoulderOffset, Player.body, Player.bodyFrame, compBackArmFrame, compBackShoulderFrame, compFrontArmFrame, compFrontShoulderFrame, Player.compositeBackArm, compositeBackArmRotation, Player.compositeFrontArm, compositeFrontArmRotation, compShoulderOverFrontArm, compTorsoFrame, ArmorIDs.Body.Count, ArmorIDs.HandOn.Count, ArmorIDs.HandOff.Count, CreateCompositeData_DetermineShoulderOffsets(), CreateCompositeFrameRect(), Entity.direction, drawPlayer, frontShoulderOffset, Player.gravDir, Player.handoff, Player.handon, hideCompositeShoulders, Player.Male, ArmorIDs.Body.Sets.shouldersAreAlwaysInTheBack, ArmorIDs.Body.Sets.showsShouldersWhileJumping, UpdateCompositeArm(), usesCompositeBackHandAcc, usesCompositeFrontHandAcc, usesCompositeTorso, ArmorIDs.Body.Sets.UsesNewFramingCode, ArmorIDs.HandOn.Sets.UsesNewFramingCode, ArmorIDs.HandOff.Sets.UsesNewFramingCode, and ArmorIDs.HandOn.Sets.UsesOldFramingTexturesForWalking.
Referenced by BoringSetup().