Terraria: Microsoft.Xna.Framework.Graphics.ModelMeshPart.Draw
Draw()
void Microsoft.Xna.Framework.Graphics.ModelMeshPart.Draw () inline package
Definition at line 99 of file ModelMeshPart.cs.
    {
        if (NumVertices > 0)
        {
            GraphicsDevice graphicsDevice = vertexBuffer.GraphicsDevice;
            graphicsDevice.SetVertexBuffer(vertexBuffer, vertexOffset);
            graphicsDevice.Indices = indexBuffer;
            graphicsDevice.DrawIndexedPrimitives(PrimitiveType.TriangleList, 0, 0, numVertices, startIndex, primitiveCount);
        }
    }
References Microsoft.Xna.Framework.Graphics.GraphicsDevice.DrawIndexedPrimitives(), Microsoft.Xna.Framework.Graphics.GraphicsResource.GraphicsDevice, Microsoft.Xna.Framework.Graphics.ModelMeshPart.indexBuffer, Microsoft.Xna.Framework.Graphics.ModelMeshPart.numVertices, Microsoft.Xna.Framework.Graphics.ModelMeshPart.NumVertices, Microsoft.Xna.Framework.Graphics.ModelMeshPart.primitiveCount, Microsoft.Xna.Framework.Graphics.GraphicsDevice.SetVertexBuffer(), Microsoft.Xna.Framework.Graphics.ModelMeshPart.startIndex, Microsoft.Xna.Framework.Graphics.ModelMeshPart.vertexBuffer, and Microsoft.Xna.Framework.Graphics.ModelMeshPart.vertexOffset.
Referenced by Microsoft.Xna.Framework.Graphics.ModelMesh.Draw().