Terraria: System.Xml.XmlDictionaryReader.XmlWrappedReader.ReadContentAsString
ReadContentAsString() [1/4]
override string System.Xml.XmlDictionaryReader.XmlWrappedReader.ReadContentAsString () inline virtual
Reimplemented from System.Xml.XmlDictionaryReader.
Definition at line 345 of file XmlDictionaryReader.cs.
        {
            try
            {
                return _reader.ReadContentAsString();
            }
            catch (ArgumentException exception)
            {
                throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(XmlExceptionHelper.CreateConversionException("String", exception));
            }
            catch (FormatException exception2)
            {
                throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(XmlExceptionHelper.CreateConversionException("String", exception2));
            }
        }
References System.Xml.XmlDictionaryReader.XmlWrappedReader._reader, System.Xml.XmlExceptionHelper.CreateConversionException(), System.Xml.Dictionary, System.exception, System.Xml.XmlReader.ReadContentAsString(), and System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperError().