Terraria: System.Xml.XmlDictionaryReader.XmlWrappedReader.ReadContentAsDouble
ReadContentAsDouble()
override double System.Xml.XmlDictionaryReader.XmlWrappedReader.ReadContentAsDouble () inline virtual
Reimplemented from System.Xml.XmlReader.
Definition at line 265 of file XmlDictionaryReader.cs.
        {
            try
            {
                return _reader.ReadContentAsDouble();
            }
            catch (ArgumentException exception)
            {
                throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(XmlExceptionHelper.CreateConversionException("Double", exception));
            }
            catch (FormatException exception2)
            {
                throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(XmlExceptionHelper.CreateConversionException("Double", exception2));
            }
            catch (OverflowException exception3)
            {
                throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(XmlExceptionHelper.CreateConversionException("Double", exception3));
            }
        }
References System.Xml.XmlDictionaryReader.XmlWrappedReader._reader, System.Xml.XmlExceptionHelper.CreateConversionException(), System.Xml.Dictionary, System.exception, System.Xml.XmlReader.ReadContentAsDouble(), and System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperError().