Terraria: System.Net.Http.HPack.HPackDecoder.ParseDynamicTableSizeUpdate
ParseDynamicTableSizeUpdate()
void System.Net.Http.HPack.HPackDecoder.ParseDynamicTableSizeUpdate (ReadOnlySpan< byte > data, ref int currentIndex) inline private
Definition at line 133 of file HPackDecoder.cs.
    {
        if (TryDecodeInteger(data, ref currentIndex, out var result))
        {
            SetDynamicHeaderTableSize(result);
            _state = State.Ready;
        }
    }
References System.Net.Http.HPack.HPackDecoder._state, System.Net.Http.HPack.HPackDecoder.SetDynamicHeaderTableSize(), and System.Net.Http.HPack.HPackDecoder.TryDecodeInteger().
Referenced by System.Net.Http.HPack.HPackDecoder.DecodeInternal(), and System.Net.Http.HPack.HPackDecoder.Parse().