Terraria: System.Net.Http.HPack.HPackDecoder.ParseHeaderNameLengthContinue
ParseHeaderNameLengthContinue()
void System.Net.Http.HPack.HPackDecoder.ParseHeaderNameLengthContinue (ReadOnlySpan< byte > data, ref int currentIndex, IHttpHeadersHandler handler) inline private
Definition at line 170 of file HPackDecoder.cs.
    {
        if (TryDecodeInteger(data, ref currentIndex, out var result))
        {
            OnStringLength(result, State.HeaderName);
            ParseHeaderName(data, ref currentIndex, handler);
        }
    }
References System.Net.Http.HPack.HPackDecoder.OnStringLength(), System.Net.Http.HPack.HPackDecoder.ParseHeaderName(), and System.Net.Http.HPack.HPackDecoder.TryDecodeInteger().
Referenced by System.Net.Http.HPack.HPackDecoder.DecodeInternal(), and System.Net.Http.HPack.HPackDecoder.ParseHeaderNameLength().