Terraria: System.Net.Http.HPack.HPackDecoder.ParseHeaderNameLength
ParseHeaderNameLength()
void System.Net.Http.HPack.HPackDecoder.ParseHeaderNameLength (ReadOnlySpan< byte > data, ref int currentIndex, IHttpHeadersHandler handler) inline private
Definition at line 205 of file HPackDecoder.cs.
    {
        if (currentIndex >= data.Length)
        {
            return;
        }
        byte b = data[currentIndex++];
        _huffman = IsHuffmanEncoded(b);
        if (_integerDecoder.BeginTryDecode((byte)(b & 0xFFFFFF7Fu), 7, out var result))
        {
            if (result == 0)
            {
                throw new HPackDecodingException(System.SR.Format(System.SR.net_http_invalid_header_name, ""));
            }
            OnStringLength(result, State.HeaderName);
            ParseHeaderName(data, ref currentIndex, handler);
        }
        else
        {
            _state = State.HeaderNameLengthContinue;
            ParseHeaderNameLengthContinue(data, ref currentIndex, handler);
        }
    }
References System.Net.Http.HPack.HPackDecoder._huffman, System.Net.Http.HPack.HPackDecoder._integerDecoder, System.Net.Http.HPack.HPackDecoder._state, System.Net.Http.HPack.IntegerDecoder.BeginTryDecode(), System.SR.Format(), System.Net.Http.HPack.HPackDecoder.IsHuffmanEncoded(), System.ReadOnlySpan< T >.Length, System.SR.net_http_invalid_header_name, System.Net.Http.HPack.HPackDecoder.OnStringLength(), System.Net.Http.HPack.HPackDecoder.ParseHeaderName(), and System.Net.Http.HPack.HPackDecoder.ParseHeaderNameLengthContinue().
Referenced by System.Net.Http.HPack.HPackDecoder.DecodeInternal(), and System.Net.Http.HPack.HPackDecoder.ParseLiteralHeaderField().