Terraria: System.Net.Http.HPack.HPackDecoder.GetDynamicHeader
GetDynamicHeader()
ref readonly HeaderField System.Net.Http.HPack.HPackDecoder.GetDynamicHeader (int index) inline private
Definition at line 489 of file HPackDecoder.cs.
    {
        try
        {
            return ref _dynamicTable[index - H2StaticTable.Count - 1];
        }
        catch (IndexOutOfRangeException)
        {
            throw new HPackDecodingException(System.SR.Format(System.SR.net_http_hpack_invalid_index, index));
        }
    }
References System.Net.Http.HPack.HPackDecoder._dynamicTable, System.SR.Format(), System.index, and System.SR.net_http_hpack_invalid_index.
Referenced by System.Net.Http.HPack.HPackDecoder.OnIndexedHeaderField(), and System.Net.Http.HPack.HPackDecoder.OnIndexedHeaderName().