Terraria: System.Net.Http.HPack.HPackDecoder.ParseHeaderValueLength
ParseHeaderValueLength()
void System.Net.Http.HPack.HPackDecoder.ParseHeaderValueLength (ReadOnlySpan< byte > data, ref int currentIndex, IHttpHeadersHandler handler) inline private
Definition at line 142 of file HPackDecoder.cs.
    {
        if (currentIndex >= data.Length)
        {
            return;
        }
        byte b = data[currentIndex++];
        _huffman = IsHuffmanEncoded(b);
        if (_integerDecoder.BeginTryDecode((byte)(b & 0xFFFFFF7Fu), 7, out var result))
        {
            OnStringLength(result, State.HeaderValue);
            if (result == 0)
            {
                OnString(State.Ready);
                ProcessHeaderValue(data, handler);
            }
            else
            {
                ParseHeaderValue(data, ref currentIndex, handler);
            }
        }
        else
        {
            _state = State.HeaderValueLengthContinue;
            ParseHeaderValueLengthContinue(data, ref currentIndex, handler);
        }
    }
References System.Net.Http.HPack.HPackDecoder._huffman, System.Net.Http.HPack.HPackDecoder._integerDecoder, System.Net.Http.HPack.HPackDecoder._state, System.Net.Http.HPack.IntegerDecoder.BeginTryDecode(), System.Net.Http.HPack.HPackDecoder.IsHuffmanEncoded(), System.ReadOnlySpan< T >.Length, System.Net.Http.HPack.HPackDecoder.OnString(), System.Net.Http.HPack.HPackDecoder.OnStringLength(), System.Net.Http.HPack.HPackDecoder.ParseHeaderValue(), System.Net.Http.HPack.HPackDecoder.ParseHeaderValueLengthContinue(), and System.Net.Http.HPack.HPackDecoder.ProcessHeaderValue().
Referenced by System.Net.Http.HPack.HPackDecoder.DecodeInternal(), System.Net.Http.HPack.HPackDecoder.ParseHeaderName(), System.Net.Http.HPack.HPackDecoder.ParseHeaderNameIndex(), and System.Net.Http.HPack.HPackDecoder.ParseLiteralHeaderField().