Terraria: System.Net.Http.HPack.HPackDecoder.OnString
OnString()
void System.Net.Http.HPack.HPackDecoder.OnString (State nextState) inline private
Definition at line 430 of file HPackDecoder.cs.
    {
        try
        {
            if (_state == State.HeaderName)
            {
                _headerNameLength = Decode(ref _headerNameOctets);
                _headerName = _headerNameOctets;
            }
            else
            {
                _headerValueLength = Decode(ref _headerValueOctets);
            }
        }
        catch (HuffmanDecodingException innerException)
        {
            throw new HPackDecodingException(System.SR.net_http_hpack_huffman_decode_failed, innerException);
        }
        _state = nextState;
        int Decode(ref byte[] dst)
        {
            if (_huffman)
            {
                return Huffman.Decode(new ReadOnlySpan<byte>(_stringOctets, 0, _stringLength), ref dst);
            }
            EnsureStringCapacity(ref dst);
            Buffer.BlockCopy(_stringOctets, 0, dst, 0, _stringLength);
            return _stringLength;
        }
    }
References System.Net.Http.HPack.HPackDecoder._headerName, System.Net.Http.HPack.HPackDecoder._headerNameLength, System.Net.Http.HPack.HPackDecoder._headerNameOctets, System.Net.Http.HPack.HPackDecoder._headerValueLength, System.Net.Http.HPack.HPackDecoder._headerValueOctets, System.Net.Http.HPack.HPackDecoder._huffman, System.Net.Http.HPack.HPackDecoder._state, System.Net.Http.HPack.HPackDecoder._stringLength, System.Net.Http.HPack.HPackDecoder._stringOctets, System.Buffer.BlockCopy(), System.Net.Http.HPack.HPackDecoder.Decode(), System.Net.Http.HPack.Huffman.Decode(), System.Net.Http.HPack.HPackDecoder.EnsureStringCapacity(), and System.SR.net_http_hpack_huffman_decode_failed.
Referenced by System.Net.Http.HPack.HPackDecoder.ParseHeaderName(), System.Net.Http.HPack.HPackDecoder.ParseHeaderValue(), and System.Net.Http.HPack.HPackDecoder.ParseHeaderValueLength().