Terraria: System.Net.Http.HPack.HPackDecoder.ParseHeaderName
ParseHeaderName()
void System.Net.Http.HPack.HPackDecoder.ParseHeaderName (ReadOnlySpan< byte > data, ref int currentIndex, IHttpHeadersHandler handler) inline private
Definition at line 301 of file HPackDecoder.cs.
    {
        int num = Math.Min(_stringLength - _stringIndex, data.Length - currentIndex);
        if (num == _stringLength && !_huffman)
        {
            _headerNameRange = (currentIndex, num);
            currentIndex += num;
            _state = State.HeaderValueLength;
            return;
        }
        data.Slice(currentIndex, num).CopyTo(_stringOctets.AsSpan(_stringIndex));
        _stringIndex += num;
        currentIndex += num;
        if (_stringIndex == _stringLength)
        {
            OnString(State.HeaderValueLength);
            ParseHeaderValueLength(data, ref currentIndex, handler);
        }
    }
References System.Net.Http.HPack.HPackDecoder._headerNameRange, System.Net.Http.HPack.HPackDecoder._huffman, System.Net.Http.HPack.HPackDecoder._state, System.Net.Http.HPack.HPackDecoder._stringIndex, System.Net.Http.HPack.HPackDecoder._stringLength, System.Net.Http.HPack.HPackDecoder._stringOctets, System.ReadOnlySpan< T >.Length, System.Math.Min(), System.Net.Http.HPack.HPackDecoder.OnString(), System.Net.Http.HPack.HPackDecoder.ParseHeaderValueLength(), and System.ReadOnlySpan< T >.Slice().
Referenced by System.Net.Http.HPack.HPackDecoder.DecodeInternal(), System.Net.Http.HPack.HPackDecoder.ParseHeaderNameLength(), and System.Net.Http.HPack.HPackDecoder.ParseHeaderNameLengthContinue().