Terraria: System.Net.Http.HPack.HPackDecoder.DecodeInternal
DecodeInternal()
void System.Net.Http.HPack.HPackDecoder.DecodeInternal (ReadOnlySpan< byte > data, IHttpHeadersHandler handler) inline private
Definition at line 80 of file HPackDecoder.cs.
    {
        int currentIndex = 0;
        do
        {
            switch (_state)
            {
            case State.Ready:
                Parse(data, ref currentIndex, handler);
                break;
            case State.HeaderFieldIndex:
                ParseHeaderFieldIndex(data, ref currentIndex, handler);
                break;
            case State.HeaderNameIndex:
                ParseHeaderNameIndex(data, ref currentIndex, handler);
                break;
            case State.HeaderNameLength:
                ParseHeaderNameLength(data, ref currentIndex, handler);
                break;
            case State.HeaderNameLengthContinue:
                ParseHeaderNameLengthContinue(data, ref currentIndex, handler);
                break;
            case State.HeaderName:
                ParseHeaderName(data, ref currentIndex, handler);
                break;
            case State.HeaderValueLength:
                ParseHeaderValueLength(data, ref currentIndex, handler);
                break;
            case State.HeaderValueLengthContinue:
                ParseHeaderValueLengthContinue(data, ref currentIndex, handler);
                break;
            case State.HeaderValue:
                ParseHeaderValue(data, ref currentIndex, handler);
                break;
            case State.DynamicTableSizeUpdate:
                ParseDynamicTableSizeUpdate(data, ref currentIndex);
                break;
            default:
                throw new NotImplementedException(_state.ToString());
            }
        }
        while (currentIndex < data.Length);
        if (_headerNameRange.HasValue)
        {
            EnsureStringCapacity(ref _headerNameOctets);
            _headerName = _headerNameOctets;
            ReadOnlySpan<byte> readOnlySpan = data.Slice(_headerNameRange.GetValueOrDefault().start, _headerNameRange.GetValueOrDefault().length);
            readOnlySpan.CopyTo(_headerName);
            _headerNameLength = readOnlySpan.Length;
            _headerNameRange = null;
        }
    }
References System.Net.Http.HPack.HPackDecoder._headerName, System.Net.Http.HPack.HPackDecoder._headerNameLength, System.Net.Http.HPack.HPackDecoder._headerNameOctets, System.Net.Http.HPack.HPackDecoder._headerNameRange, System.Net.Http.HPack.HPackDecoder._state, System.ReadOnlySpan< T >.CopyTo(), System.Net.Http.HPack.HPackDecoder.EnsureStringCapacity(), System.ReadOnlySpan< T >.Length, System.Net.Http.HPack.HPackDecoder.Parse(), System.Net.Http.HPack.HPackDecoder.ParseDynamicTableSizeUpdate(), System.Net.Http.HPack.HPackDecoder.ParseHeaderFieldIndex(), System.Net.Http.HPack.HPackDecoder.ParseHeaderName(), System.Net.Http.HPack.HPackDecoder.ParseHeaderNameIndex(), System.Net.Http.HPack.HPackDecoder.ParseHeaderNameLength(), System.Net.Http.HPack.HPackDecoder.ParseHeaderNameLengthContinue(), System.Net.Http.HPack.HPackDecoder.ParseHeaderValue(), System.Net.Http.HPack.HPackDecoder.ParseHeaderValueLength(), System.Net.Http.HPack.HPackDecoder.ParseHeaderValueLengthContinue(), and System.ReadOnlySpan< T >.Slice().
Referenced by System.Net.Http.HPack.HPackDecoder.Decode().