Terraria: System.Net.Http.HPack.HPackDecoder.OnStringLength
OnStringLength()
void System.Net.Http.HPack.HPackDecoder.OnStringLength (int length, State nextState) inline private
Definition at line 415 of file HPackDecoder.cs.
    {
        if (length > _stringOctets.Length)
        {
            if (length > _maxHeadersLength)
            {
                throw new HPackDecodingException(System.SR.Format(System.SR.net_http_headers_exceeded_length, _maxHeadersLength));
            }
            _stringOctets = new byte[Math.Max(length, _stringOctets.Length * 2)];
        }
        _stringLength = length;
        _stringIndex = 0;
        _state = nextState;
    }
References System.Net.Http.HPack.HPackDecoder._maxHeadersLength, System.Net.Http.HPack.HPackDecoder._state, System.Net.Http.HPack.HPackDecoder._stringIndex, System.Net.Http.HPack.HPackDecoder._stringLength, System.Net.Http.HPack.HPackDecoder._stringOctets, System.SR.Format(), System.length, System.Math.Max(), and System.SR.net_http_headers_exceeded_length.
Referenced by System.Net.Http.HPack.HPackDecoder.ParseHeaderNameLength(), System.Net.Http.HPack.HPackDecoder.ParseHeaderNameLengthContinue(), System.Net.Http.HPack.HPackDecoder.ParseHeaderValueLength(), and System.Net.Http.HPack.HPackDecoder.ParseHeaderValueLengthContinue().