Terraria: System.Xml.XmlEncodedRawTextWriterIndent.WriteIndentAsync
WriteIndentAsync()
async Task System.Xml.XmlEncodedRawTextWriterIndent.WriteIndentAsync () inline private
Definition at line 371 of file XmlEncodedRawTextWriterIndent.cs.
    {
        CheckAsyncCall();
        await RawTextAsync(_newLineChars).ConfigureAwait(continueOnCapturedContext: false);
        for (int i = _indentLevel; i > 0; i--)
        {
            await RawTextAsync(_indentChars).ConfigureAwait(continueOnCapturedContext: false);
        }
    }
References System.Xml.XmlEncodedRawTextWriterIndent._indentChars, System.Xml.XmlEncodedRawTextWriterIndent._indentLevel, System.Xml.XmlEncodedRawTextWriter._newLineChars, System.Xml.XmlEncodedRawTextWriter.CheckAsyncCall(), System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.Xml.Dictionary, and System.Xml.XmlEncodedRawTextWriter.RawTextAsync().
Referenced by System.Xml.XmlEncodedRawTextWriterIndent.WriteCommentAsync(), System.Xml.XmlEncodedRawTextWriterIndent.WriteDocTypeAsync(), System.Xml.XmlEncodedRawTextWriterIndent.WriteEndElementAsync(), System.Xml.XmlEncodedRawTextWriterIndent.WriteFullEndElementAsync(), System.Xml.XmlEncodedRawTextWriterIndent.WriteProcessingInstructionAsync(), System.Xml.XmlEncodedRawTextWriterIndent.WriteStartAttributeAsync(), and System.Xml.XmlEncodedRawTextWriterIndent.WriteStartElementAsync().