Terraria: System.Net.Http.HPack.HPackDecoder.ParseLiteralHeaderField
ParseLiteralHeaderField()
void System.Net.Http.HPack.HPackDecoder.ParseLiteralHeaderField (ReadOnlySpan< byte > data, ref int currentIndex, byte b, byte mask, byte indexPrefix, bool index, IHttpHeadersHandler handler) inline private
Definition at line 278 of file HPackDecoder.cs.
    {
        _headersObserved = true;
        _index = index;
        int num = b & ~mask;
        int result;
        if (num == 0)
        {
            _state = State.HeaderNameLength;
            ParseHeaderNameLength(data, ref currentIndex, handler);
        }
        else if (_integerDecoder.BeginTryDecode((byte)num, indexPrefix, out result))
        {
            OnIndexedHeaderName(result);
            ParseHeaderValueLength(data, ref currentIndex, handler);
        }
        else
        {
            _state = State.HeaderNameIndex;
            ParseHeaderNameIndex(data, ref currentIndex, handler);
        }
    }
References System.Net.Http.HPack.HPackDecoder._headersObserved, System.Net.Http.HPack.HPackDecoder._index, System.Net.Http.HPack.HPackDecoder._integerDecoder, System.Net.Http.HPack.HPackDecoder._state, System.Net.Http.HPack.IntegerDecoder.BeginTryDecode(), System.index, System.Net.Http.HPack.HPackDecoder.OnIndexedHeaderName(), System.Net.Http.HPack.HPackDecoder.ParseHeaderNameIndex(), System.Net.Http.HPack.HPackDecoder.ParseHeaderNameLength(), and System.Net.Http.HPack.HPackDecoder.ParseHeaderValueLength().
Referenced by System.Net.Http.HPack.HPackDecoder.Parse().