Terraria: System.Net.Http.HPack.HPackDecoder.SetDynamicHeaderTableSize
SetDynamicHeaderTableSize()
void System.Net.Http.HPack.HPackDecoder.SetDynamicHeaderTableSize (int size) inline private
Definition at line 501 of file HPackDecoder.cs.
    {
        if (size > _maxDynamicTableSize)
        {
            throw new HPackDecodingException(System.SR.Format(System.SR.net_http_hpack_large_table_size_update, size, _maxDynamicTableSize));
        }
        _dynamicTable.Resize(size);
    }
References System.Net.Http.HPack.HPackDecoder._dynamicTable, System.Net.Http.HPack.HPackDecoder._maxDynamicTableSize, System.SR.Format(), System.SR.net_http_hpack_large_table_size_update, and System.Net.Http.HPack.DynamicTable.Resize().
Referenced by System.Net.Http.HPack.HPackDecoder.Parse(), and System.Net.Http.HPack.HPackDecoder.ParseDynamicTableSizeUpdate().