Terraria: System.Xml.XmlEncodedRawTextWriterIndent.Init
Init()
void System.Xml.XmlEncodedRawTextWriterIndent.Init (XmlWriterSettings settings) inline private
Definition at line 193 of file XmlEncodedRawTextWriterIndent.cs.
    {
        _indentLevel = 0;
        _indentChars = settings.IndentChars;
        _newLineOnAttributes = settings.NewLineOnAttributes;
        _mixedContentStack = new BitStack();
        if (!_checkCharacters)
        {
            return;
        }
        if (_newLineOnAttributes)
        {
            ValidateContentChars(_indentChars, "IndentChars", allowOnlyWhitespace: true);
            ValidateContentChars(_newLineChars, "NewLineChars", allowOnlyWhitespace: true);
            return;
        }
        ValidateContentChars(_indentChars, "IndentChars", allowOnlyWhitespace: false);
        if (_newLineHandling != 0)
        {
            ValidateContentChars(_newLineChars, "NewLineChars", allowOnlyWhitespace: false);
        }
    }
References System.Xml.XmlEncodedRawTextWriter._checkCharacters, System.Xml.XmlEncodedRawTextWriterIndent._indentChars, System.Xml.XmlEncodedRawTextWriterIndent._indentLevel, System.Xml.XmlEncodedRawTextWriterIndent._mixedContentStack, System.Xml.XmlEncodedRawTextWriter._newLineChars, System.Xml.XmlEncodedRawTextWriter._newLineHandling, System.Xml.XmlEncodedRawTextWriterIndent._newLineOnAttributes, System.Xml.Dictionary, System.Xml.XmlWriterSettings.IndentChars, System.Xml.XmlWriterSettings.NewLineOnAttributes, and System.Xml.XmlEncodedRawTextWriter.ValidateContentChars().
Referenced by System.Xml.XmlEncodedRawTextWriterIndent.XmlEncodedRawTextWriterIndent(), and System.Xml.XmlEncodedRawTextWriterIndent.XmlEncodedRawTextWriterIndent().