Terraria: System.Net.Http.HPack.HPackDecoder.ParseHeaderValue
ParseHeaderValue()
void System.Net.Http.HPack.HPackDecoder.ParseHeaderValue (ReadOnlySpan< byte > data, ref int currentIndex, IHttpHeadersHandler handler) inline private
Definition at line 321 of file HPackDecoder.cs.
    {
        int num = Math.Min(_stringLength - _stringIndex, data.Length - currentIndex);
        if (num == _stringLength && !_huffman)
        {
            _headerValueRange = (currentIndex, num);
            currentIndex += num;
            _state = State.Ready;
            ProcessHeaderValue(data, handler);
            return;
        }
        data.Slice(currentIndex, num).CopyTo(_stringOctets.AsSpan(_stringIndex));
        _stringIndex += num;
        currentIndex += num;
        if (_stringIndex == _stringLength)
        {
            OnString(State.Ready);
            ProcessHeaderValue(data, handler);
        }
    }
References System.Net.Http.HPack.HPackDecoder._headerValueRange, System.Net.Http.HPack.HPackDecoder._huffman, System.Net.Http.HPack.HPackDecoder._state, System.Net.Http.HPack.HPackDecoder._stringIndex, System.Net.Http.HPack.HPackDecoder._stringLength, System.Net.Http.HPack.HPackDecoder._stringOctets, System.ReadOnlySpan< T >.Length, System.Math.Min(), System.Net.Http.HPack.HPackDecoder.OnString(), System.Net.Http.HPack.HPackDecoder.ProcessHeaderValue(), and System.ReadOnlySpan< T >.Slice().
Referenced by System.Net.Http.HPack.HPackDecoder.DecodeInternal(), System.Net.Http.HPack.HPackDecoder.ParseHeaderValueLength(), and System.Net.Http.HPack.HPackDecoder.ParseHeaderValueLengthContinue().