Terraria: System.Net.Http.HPack.HPackDecoder.Parse
Parse()
void System.Net.Http.HPack.HPackDecoder.Parse (ReadOnlySpan< byte > data, ref int currentIndex, IHttpHeadersHandler handler) inline private
Definition at line 229 of file HPackDecoder.cs.
    {
        if (currentIndex >= data.Length)
        {
            return;
        }
        byte b = data[currentIndex++];
        switch (BitOperations.LeadingZeroCount(b))
        {
        case 24:
        {
            _headersObserved = true;
            int num = b & -129;
            if (_integerDecoder.BeginTryDecode((byte)num, 7, out var result2))
            {
                OnIndexedHeaderField(result2, handler);
                break;
            }
            _state = State.HeaderFieldIndex;
            ParseHeaderFieldIndex(data, ref currentIndex, handler);
            break;
        }
        case 25:
            ParseLiteralHeaderField(data, ref currentIndex, b, 192, 6, index: true, handler);
            break;
        default:
            ParseLiteralHeaderField(data, ref currentIndex, b, 240, 4, index: false, handler);
            break;
        case 27:
            ParseLiteralHeaderField(data, ref currentIndex, b, 240, 4, index: false, handler);
            break;
        case 26:
        {
            if (_headersObserved)
            {
                throw new HPackDecodingException(System.SR.net_http_hpack_late_dynamic_table_size_update);
            }
            if (_integerDecoder.BeginTryDecode((byte)(b & 0xFFFFFF1Fu), 5, out var result))
            {
                SetDynamicHeaderTableSize(result);
                break;
            }
            _state = State.DynamicTableSizeUpdate;
            ParseDynamicTableSizeUpdate(data, ref currentIndex);
            break;
        }
        }
    }
References System.Net.Http.HPack.HPackDecoder._headersObserved, System.Net.Http.HPack.HPackDecoder._integerDecoder, System.Net.Http.HPack.HPackDecoder._state, System.Net.Http.HPack.IntegerDecoder.BeginTryDecode(), System.index, System.Numerics.BitOperations.LeadingZeroCount(), System.ReadOnlySpan< T >.Length, System.SR.net_http_hpack_late_dynamic_table_size_update, System.Net.Http.HPack.HPackDecoder.OnIndexedHeaderField(), System.Net.Http.HPack.HPackDecoder.ParseDynamicTableSizeUpdate(), System.Net.Http.HPack.HPackDecoder.ParseHeaderFieldIndex(), System.Net.Http.HPack.HPackDecoder.ParseLiteralHeaderField(), and System.Net.Http.HPack.HPackDecoder.SetDynamicHeaderTableSize().
Referenced by System.Net.Http.HPack.HPackDecoder.DecodeInternal().