Terraria: System.Net.Http.HPack.HPackDecoder.ProcessHeaderValue
ProcessHeaderValue()
void System.Net.Http.HPack.HPackDecoder.ProcessHeaderValue (ReadOnlySpan< byte > data, IHttpHeadersHandler handler) inline private
Definition at line 354 of file HPackDecoder.cs.
    {
        ReadOnlySpan<byte> value = ((!_headerValueRange.HasValue) ? ((ReadOnlySpan<byte>)_headerValueOctets.AsSpan(0, _headerValueLength)) : data.Slice(_headerValueRange.GetValueOrDefault().start, _headerValueRange.GetValueOrDefault().length));
        if (_headerStaticIndex > 0)
        {
            handler.OnStaticIndexedHeader(_headerStaticIndex, value);
            if (_index)
            {
                _dynamicTable.Insert(H2StaticTable.Get(_headerStaticIndex - 1).Name, value);
            }
        }
        else
        {
            ReadOnlySpan<byte> name = ((!_headerNameRange.HasValue) ? ((ReadOnlySpan<byte>)_headerName.AsSpan(0, _headerNameLength)) : data.Slice(_headerNameRange.GetValueOrDefault().start, _headerNameRange.GetValueOrDefault().length));
            handler.OnHeader(name, value);
            if (_index)
            {
                _dynamicTable.Insert(name, value);
            }
        }
        _headerStaticIndex = 0;
        _headerNameRange = null;
        _headerValueRange = null;
    }
References System.Net.Http.HPack.HPackDecoder._dynamicTable, System.Net.Http.HPack.HPackDecoder._headerName, System.Net.Http.HPack.HPackDecoder._headerNameLength, System.Net.Http.HPack.HPackDecoder._headerNameRange, System.Net.Http.HPack.HPackDecoder._headerStaticIndex, System.Net.Http.HPack.HPackDecoder._headerValueLength, System.Net.Http.HPack.HPackDecoder._headerValueOctets, System.Net.Http.HPack.HPackDecoder._headerValueRange, System.Net.Http.HPack.HPackDecoder._index, System.Net.Http.HPack.H2StaticTable.Get(), System.Net.Http.HPack.DynamicTable.Insert(), System.Net.Http.IHttpHeadersHandler.OnHeader(), System.Net.Http.IHttpHeadersHandler.OnStaticIndexedHeader(), System.ReadOnlySpan< T >.Slice(), and System.value.
Referenced by System.Net.Http.HPack.HPackDecoder.ParseHeaderValue(), and System.Net.Http.HPack.HPackDecoder.ParseHeaderValueLength().