Terraria: ReLogic.Peripherals.RGB.Logitech.LogitechDeviceGroup.Initialize
Initialize()
override void ReLogic.Peripherals.RGB.Logitech.LogitechDeviceGroup.Initialize () inline protected
Definition at line 22 of file LogitechDeviceGroup.cs.
    {
        if (_isInitialized || _initializationFailed)
        {
            return;
        }
        if (!NativeLibrary.TryLoad("LogitechLedEnginesWrapper ", out var _))
        {
            _initializationFailed = true;
            return;
        }
        try
        {
            if (!NativeMethods.LogiLedInit())
            {
                throw new DeviceInitializationException("LogitechGSDK failed to initialize.");
            }
            _isInitialized = true;
            if (!NativeMethods.LogiLedSetTargetDevice(6))
            {
                throw new DeviceInitializationException("LogitechGSDK failed to target RGB devices.");
            }
            _devices.Add(new LogitechKeyboard(_colorProfiles.Keyboard));
            _devices.Add(new LogitechSingleLightDevice(_colorProfiles.Generic));
            Console.WriteLine("Logitech RGB initialized.");
        }
        catch (DeviceInitializationException)
        {
            Console.WriteLine("Logitech RGB not supported. (Can be disabled via Config.json)");
            Uninitialize();
        }
        catch (Exception ex2)
        {
            Console.WriteLine("Logitech RGB not supported: " + ex2);
        }
    }
References ReLogic.Peripherals.RGB.Logitech.LogitechDeviceGroup._colorProfiles, ReLogic.Peripherals.RGB.Logitech.LogitechDeviceGroup._devices, ReLogic.Peripherals.RGB.Logitech.LogitechDeviceGroup._initializationFailed, ReLogic.Peripherals.RGB.Logitech.LogitechDeviceGroup._isInitialized, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), ReLogic.Peripherals.RGB.VendorColorProfile.Generic, ReLogic.Peripherals.RGB.VendorColorProfile.Keyboard, ReLogic.Peripherals.RGB.Logitech.NativeMethods.LogiLedInit(), ReLogic.Peripherals.RGB.Logitech.NativeMethods.LogiLedSetTargetDevice(), System.Runtime.InteropServices.NativeLibrary.TryLoad(), ReLogic.Peripherals.RGB.Logitech.LogitechDeviceGroup.Uninitialize(), and System.Console.WriteLine().