Terraria: System.Reflection.Emit.OpCodes.Ldfld
Ldfld
readonly OpCode System.Reflection.Emit.OpCodes.Ldfld = new OpCode(OpCodeValues.Ldfld, 6727329) static
Definition at line 245 of file OpCodes.cs.
Referenced by System.Reflection.DispatchProxyGenerator.ProxyBuilder.AddMethodImpl(), System.Reflection.Emit.IgnoreAccessChecksToAttributeBuilder.AddToModule(), System.Text.Json.Serialization.Metadata.ReflectionEmitMemberAccessor.CreateFieldGetter(), System.Linq.Expressions.Compiler.CompilerScope.EmitClosureToVariable(), System.Linq.Expressions.Compiler.BoundConstants.EmitConstantsArray(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitDynamicExpression(), System.Linq.Expressions.Compiler.ILGen.EmitFieldGet(), System.Linq.Expressions.Compiler.CompilerScope.ElementBoxStorage.EmitLoad(), System.Linq.Expressions.Compiler.CompilerScope.LocalBoxStorage.EmitLoad(), System.Reflection.Emit.ILGenerator.EmitWriteLine(), System.Text.RegularExpressions.RegexCompiler.Ldfld(), System.Runtime.Serialization.CodeGenerator.LoadMember(), and System.Xml.Serialization.CodeGenerator.LoadMember().