Terraria: System.Reflection.Emit.OpCodes.Nop
Nop
readonly OpCode System.Reflection.Emit.OpCodes.Nop = new OpCode(OpCodeValues.Nop, 6556325) static
Definition at line 5 of file OpCodes.cs.
Referenced by System.Reflection.DispatchProxyGenerator.ProxyBuilder.AddMethodImpl(), System.Reflection.Emit.DynamicILGenerator.BeginCatchBlock(), System.Reflection.Emit.DynamicILGenerator.BeginExceptFilterBlock(), System.Xml.Xsl.IlGen.XmlILVisitor.ClrCompare(), System.Xml.Xsl.IlGen.GenerateHelper.DebugSequencePoint(), System.Runtime.Serialization.CodeGenerator.GetConvOpCode(), System.Runtime.Serialization.CodeGenerator.GetLdelemOpCode(), System.Runtime.Serialization.CodeGenerator.GetLdindOpCode(), System.Runtime.Serialization.CodeGenerator.GetStelemOpCode(), System.Runtime.Serialization.CodeGenerator.InternalConvert(), System.Xml.Serialization.CodeGenerator.InternalConvert(), System.Runtime.Serialization.CodeGenerator.Ldelem(), System.Xml.Serialization.CodeGenerator.Ldelem(), System.Reflection.DispatchProxyGenerator.ProxyBuilder.Ldind(), System.Runtime.Serialization.CodeGenerator.Ldobj(), System.Xml.Serialization.CodeGenerator.Ldobj(), System.Xml.Xsl.IlGen.GenerateHelper.MethodBegin(), System.Xml.Serialization.CodeGenerator.Nop(), System.Runtime.Serialization.CodeGenerator.Stelem(), System.Xml.Serialization.CodeGenerator.Stelem(), and System.Reflection.DispatchProxyGenerator.ProxyBuilder.Stind().