Terraria: System.Reflection.Emit.OpCodes.Stobj
Stobj
readonly OpCode System.Reflection.Emit.OpCodes.Stobj = new OpCode(OpCodeValues.Stobj, -530298195) static
Definition at line 257 of file OpCodes.cs.
Referenced by System.Dynamic.Utils.DelegateHelpers.CreateObjectArrayDelegateRefEmit(), System.Linq.Expressions.Compiler.ILGen.EmitStoreValueIndirect(), System.Reflection.DispatchProxyGenerator.ProxyBuilder.Stind(), System.Runtime.Serialization.CodeGenerator.Stobj(), System.Xml.Serialization.CodeGenerator.Stobj(), and System.Xml.Xsl.IlGen.XmlILVisitor.VisitXsltInvokeLateBound().