Terraria: System.Reflection.Emit.OpCodes.Newobj
Newobj
readonly OpCode System.Reflection.Emit.OpCodes.Newobj = new OpCode(OpCodeValues.Newobj, 276014660) static
Definition at line 233 of file OpCodes.cs.
Referenced by System.Xml.Xsl.IlGen.GenerateHelper.Construct(), System.Text.Json.Serialization.Metadata.ReflectionEmitMemberAccessor.CreateConstructor(), System.Text.Json.Serialization.Metadata.ReflectionEmitMemberAccessor.CreateParameterizedConstructor(), System.Text.Json.Serialization.Metadata.ReflectionEmitMemberAccessor.CreateParameterizedConstructor(), System.Reflection.Emit.DynamicILGenerator.Emit(), System.Reflection.Emit.ILGenerator.Emit(), System.Reflection.Emit.DynamicILGenerator.EmitCall(), System.Reflection.Emit.ILGenerator.EmitCall(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitLift(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitLiftedBinaryArithmetic(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitLiftedToNullRelational(), System.Linq.Expressions.Compiler.ILGen.EmitNew(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitNewExpression(), System.Linq.Expressions.Compiler.CompilerScope.EmitNewHoistedLocals(), System.Linq.Expressions.Compiler.ILGen.EmitNonNullableToNullableConversion(), System.Linq.Expressions.Compiler.ILGen.EmitNullableToNullableConversion(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitUnary(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitUnaryOperator(), System.Runtime.Serialization.CodeGenerator.New(), System.Xml.Serialization.CodeGenerator.New(), System.Reflection.Emit.ILGenerator.ThrowException(), and System.Linq.Expressions.Compiler.ILGen.TryEmitILConstant().