Terraria: System.Reflection.Emit.OpCodes.Ldelem_Ref
Ldelem_Ref
readonly OpCode System.Reflection.Emit.OpCodes.Ldelem_Ref = new OpCode(OpCodeValues.Ldelem_Ref, -260913499) static
Definition at line 307 of file OpCodes.cs.
Referenced by System.Reflection.DispatchProxyGenerator.ProxyBuilder.AddMethodImpl(), System.Dynamic.Utils.DelegateHelpers.CreateObjectArrayDelegateRefEmit(), System.Text.Json.Serialization.Metadata.ReflectionEmitMemberAccessor.CreateParameterizedConstructor(), System.Linq.Expressions.Compiler.BoundConstants.EmitConstantFromArray(), System.Linq.Expressions.Compiler.CompilerScope.ElementBoxStorage.EmitLoadBox(), System.Linq.Expressions.Compiler.ILGen.EmitLoadElement(), System.Reflection.DispatchProxyGenerator.ProxyBuilder.GenericArray< T >.Get(), and System.Runtime.Serialization.CodeGenerator.GetLdelemOpCode().