Terraria: System.Reflection.Emit.OpCodes.Leave
Leave
readonly OpCode System.Reflection.Emit.OpCodes.Leave = new OpCode(OpCodeValues.Leave, 23333376) static
Definition at line 379 of file OpCodes.cs.
Referenced by System.Reflection.Emit.DynamicILGenerator.BeginCatchBlock(), System.Reflection.Emit.ILGenerator.BeginCatchBlock(), System.Reflection.Emit.DynamicILGenerator.BeginExceptFilterBlock(), System.Reflection.Emit.ILGenerator.BeginExceptFilterBlock(), System.Reflection.Emit.ILGenerator.BeginFaultBlock(), System.Reflection.Emit.ILGenerator.BeginFinallyBlock(), System.Reflection.Emit.ILGenerator.EndExceptionBlock(), System.Xml.Serialization.CodeGenerator.Leave(), and System.Linq.Expressions.Compiler.LabelInfo.ValidateJump().