Terraria: System.Reflection.Emit.OpCodes.Ldstr
Ldstr
readonly OpCode System.Reflection.Emit.OpCodes.Ldstr = new OpCode(OpCodeValues.Ldstr, 275908266) static
Definition at line 231 of file OpCodes.cs.
Referenced by System.Xml.Xsl.IlGen.GenerateHelper.CallConcatStrings(), System.Xml.Xsl.IlGen.GenerateHelper.CallGetParameter(), System.Xml.Xsl.IlGen.GenerateHelper.CallStartRtfConstruction(), System.Xml.Xsl.IlGen.GenerateHelper.ConstructLiteralQName(), System.Linq.Expressions.Compiler.ILGen.EmitString(), System.Reflection.Emit.ILGenerator.EmitWriteLine(), System.Text.RegularExpressions.RegexCompiler.Ldstr(), System.Runtime.Serialization.CodeGenerator.Ldstr(), System.Xml.Serialization.CodeGenerator.Ldstr(), System.Xml.Xsl.IlGen.XmlILVisitor.LoadNameAndType(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitGlobalValues(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitLiteralString(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitRtfCtor(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitXPathNodeValue(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitXsltGenerateId(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitXsltInvokeEarlyBound(), and System.Xml.Xsl.IlGen.XmlILVisitor.VisitXsltInvokeLateBound().