Terraria: System.Reflection.Emit.OpCodes.Call
Call
readonly OpCode System.Reflection.Emit.OpCodes.Call = new OpCode(OpCodeValues.Call, 7842372) static
Definition at line 83 of file OpCodes.cs.
Referenced by System.Reflection.DispatchProxyGenerator.ProxyBuilder.AddMethodImpl(), System.Runtime.Serialization.CodeGenerator.Call(), System.Xml.Serialization.CodeGenerator.Call(), System.Xml.Xsl.IlGen.GenerateHelper.Call(), System.Runtime.Serialization.CodeGenerator.Call(), System.Xml.Serialization.CodeGenerator.Call(), System.Text.RegularExpressions.RegexCompiler.Call(), System.Reflection.DispatchProxyGenerator.ProxyBuilder.Complete(), System.Text.Json.Serialization.Metadata.ReflectionEmitMemberAccessor.CreateImmutableDictionaryCreateRangeDelegate(), System.Text.Json.Serialization.Metadata.ReflectionEmitMemberAccessor.CreateImmutableEnumerableCreateRangeDelegate(), System.Dynamic.Utils.DelegateHelpers.CreateObjectArrayDelegateRefEmit(), System.Text.Json.Serialization.Metadata.ReflectionEmitMemberAccessor.CreatePropertyGetter(), System.Text.Json.Serialization.Metadata.ReflectionEmitMemberAccessor.CreatePropertySetter(), System.Reflection.Emit.TypeBuilder.DefineDefaultConstructorNoLock(), System.Reflection.Emit.ILGenerator.Emit(), System.Reflection.Emit.DynamicILGenerator.EmitCall(), System.Reflection.Emit.ILGenerator.EmitCall(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitCall(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitGetArrayElement(), System.Linq.Expressions.Compiler.ILGen.EmitGetValue(), System.Linq.Expressions.Compiler.ILGen.EmitGetValueOrDefault(), System.Linq.Expressions.Compiler.ILGen.EmitHasValue(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitMethodAndAlso(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitMethodCall(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitMethodOrElse(), System.Linq.Expressions.Compiler.ILGen.EmitNumericConversion(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitQuote(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitSetArrayElement(), System.Linq.Expressions.Compiler.ILGen.EmitType(), System.Linq.Expressions.Compiler.CompilerScope.EmitVariableAccess(), System.Reflection.Emit.ILGenerator.EmitWriteLine(), System.Reflection.Emit.ILGenerator.EmitWriteLine(), System.Reflection.Emit.ILGenerator.EmitWriteLine(), and System.Linq.Expressions.Compiler.ILGen.TryEmitConstant().