Terraria: System.Reflection.Emit.OpCodes.Dup
Dup
readonly OpCode System.Reflection.Emit.OpCodes.Dup = new OpCode(OpCodeValues.Dup, 275258021) static
Definition at line 77 of file OpCodes.cs.
Referenced by System.Linq.Expressions.Compiler.LambdaCompiler.AddressOfWriteBackCore(), System.Linq.Expressions.Compiler.LambdaCompiler.AddressOfWriteBackCore(), System.Xml.Xsl.XmlILGenerator.CreateTypeInitializer(), System.Runtime.Serialization.CodeGenerator.Dup(), System.Xml.Serialization.CodeGenerator.Dup(), System.Text.RegularExpressions.RegexCompiler.Dup(), System.Linq.Expressions.Compiler.BoundConstants.EmitCacheConstants(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitCatchStart(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitDynamicExpression(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitIndexAssignment(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitLambdaReferenceCoalesce(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitLift(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitListInit(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitMemberAssignment(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitMemberInit(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitMethodAndAlso(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitMethodOrElse(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitNewArrayExpression(), System.Linq.Expressions.Compiler.CompilerScope.EmitNewHoistedLocals(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitReferenceCoalesceWithoutConversion(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitVariableAssignment(), System.Xml.Xsl.IlGen.IteratorDescriptor.PushValue(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitLength(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitNodeProperty(), and System.Xml.Xsl.IlGen.XmlILVisitor.VisitXsltInvokeEarlyBound().