Terraria: System.Reflection.Emit.OpCodes.Brfalse_S
Brfalse_S
readonly OpCode System.Reflection.Emit.OpCodes.Brfalse_S = new OpCode(OpCodeValues.Brfalse_S, -261868945) static
Definition at line 91 of file OpCodes.cs.
Referenced by System.Text.RegularExpressions.RegexCompiler.Brfalse(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitLiftedBinaryArithmetic(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitLiftedBooleanAnd(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitLiftedBooleanOr(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitLiftedOrElse(), System.Linq.Expressions.Compiler.ILGen.EmitNullableToNullableConversion(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitUnary(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitUnaryOperator(), System.Xml.Xsl.IlGen.GenerateHelper.TestAndBranch(), and System.Xml.Xsl.IlGen.XmlILVisitor.VisitIsEmpty().