Terraria: System.Reflection.Emit.OpCodes.Brfalse
Brfalse
readonly OpCode System.Reflection.Emit.OpCodes.Brfalse = new OpCode(OpCodeValues.Brfalse, -261866912) static
Definition at line 117 of file OpCodes.cs.
Referenced by System.Runtime.Serialization.CodeGenerator.Brfalse(), System.Xml.Serialization.CodeGenerator.Brfalse(), System.Text.RegularExpressions.RegexCompiler.BrfalseFar(), System.Xml.Xsl.XmlILGenerator.CreateHelperFunctions(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitBranchOp(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitNullableCoalesce(), System.Xml.Xsl.IlGen.XmlILVisitor.EndNestedIterator(), System.Xml.Xsl.IlGen.XmlILVisitor.Function(), System.Xml.Xsl.IlGen.XmlILVisitor.GenerateSimpleIterator(), System.Runtime.Serialization.CodeGenerator.IfFalseBreak(), System.Xml.Xsl.IlGen.GenerateHelper.TestAndBranch(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitAttribute(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitConditional(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitDataSource(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitFalse(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitGlobalValues(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitParent(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitTrue(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitXsltCopy(), and System.Xml.Xsl.IlGen.XmlILVisitor.ZeroCompare().