Terraria: System.Reflection.Emit.OpCodes.Switch
Switch
readonly OpCode System.Reflection.Emit.OpCodes.Switch = new OpCode(OpCodeValues.Switch, -261866901) static
Definition at line 141 of file OpCodes.cs.
Referenced by System.Xml.Xsl.IlGen.XmlILVisitor.CreateSetIterator(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitSwitchBucket(), System.Xml.Xsl.IlGen.XmlILVisitor.GenerateContainerIterator(), System.Xml.Xsl.IlGen.XmlILVisitor.Sequence(), System.Runtime.Serialization.CodeGenerator.Switch(), System.Text.RegularExpressions.RegexCompiler.Switch(), and System.Xml.Xsl.IlGen.XmlILVisitor.VisitChoice().