Terraria: System.Reflection.Emit.OpCodes.Castclass
Castclass
readonly OpCode System.Reflection.Emit.OpCodes.Castclass = new OpCode(OpCodeValues.Castclass, 7513773) static
Definition at line 235 of file OpCodes.cs.
Referenced by System.Runtime.Serialization.CodeGenerator.Castclass(), System.Xml.Serialization.CodeGenerator.Castclass(), System.Reflection.DispatchProxyGenerator.ProxyBuilder.Convert(), System.Text.Json.Serialization.Metadata.ReflectionEmitMemberAccessor.CreateFieldGetter(), System.Text.Json.Serialization.Metadata.ReflectionEmitMemberAccessor.CreateFieldSetter(), System.Text.Json.Serialization.Metadata.ReflectionEmitMemberAccessor.CreatePropertyGetter(), System.Text.Json.Serialization.Metadata.ReflectionEmitMemberAccessor.CreatePropertySetter(), System.Linq.Expressions.Compiler.ILGen.EmitCastToType(), System.Linq.Expressions.Compiler.BoundConstants.EmitConstantFromArray(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitDelegateConstruction(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitExpressionAsType(), System.Linq.Expressions.Compiler.CompilerScope.ElementBoxStorage.EmitLoadBox(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitQuote(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitReferenceCoalesceWithoutConversion(), System.Xml.Xsl.IlGen.IteratorDescriptor.EnsureItemStorageType(), System.Xml.Xsl.IlGen.GenerateHelper.TreatAs(), and System.Linq.Expressions.Compiler.ILGen.TryEmitConstant().