Terraria: System.Reflection.Emit.OpCodes.Unbox_Any
Unbox_Any
readonly OpCode System.Reflection.Emit.OpCodes.Unbox_Any = new OpCode(OpCodeValues.Unbox_Any, 6727341) static
Definition at line 329 of file OpCodes.cs.
Referenced by System.Reflection.DispatchProxyGenerator.ProxyBuilder.Convert(), System.Text.Json.Serialization.Metadata.ReflectionEmitMemberAccessor.CreateFieldSetter(), System.Dynamic.Utils.DelegateHelpers.CreateObjectArrayDelegateRefEmit(), System.Text.Json.Serialization.Metadata.ReflectionEmitMemberAccessor.CreateParameterizedConstructor(), System.Text.Json.Serialization.Metadata.ReflectionEmitMemberAccessor.CreatePropertySetter(), System.Linq.Expressions.Compiler.ILGen.EmitCastToType(), System.Linq.Expressions.Compiler.BoundConstants.EmitConstantFromArray(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitUnaryOperator(), and System.Linq.Expressions.Compiler.LambdaCompiler.EmitUnboxUnaryExpression().