Terraria: System.Reflection.Emit.OpCodes.Pop
Pop
readonly OpCode System.Reflection.Emit.OpCodes.Pop = new OpCode(OpCodeValues.Pop, -261875035) static
Definition at line 79 of file OpCodes.cs.
Referenced by System.Reflection.DispatchProxyGenerator.ProxyBuilder.AddMethodImpl(), System.Xml.Xsl.IlGen.GenerateHelper.AddSortKey(), System.Xml.Xsl.IlGen.IteratorDescriptor.DiscardStack(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitCatchStart(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitExpressionAsVoid(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitListInit(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitMemberInit(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitReferenceCoalesceWithoutConversion(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitSaveExceptionOrPop(), System.Xml.Xsl.XmlILGenerator.EvaluateGlobalValues(), System.Xml.Xsl.IlGen.XmlILVisitor.NestedVisitEnsureCache(), System.Runtime.Serialization.CodeGenerator.Pop(), System.Xml.Serialization.CodeGenerator.Pop(), System.Text.RegularExpressions.RegexCompiler.Pop(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitSort(), and System.Xml.Xsl.IlGen.XmlILVisitor.VisitXsltGenerateId().