Terraria: System.Reflection.Emit.OpCodes.Ldloc
Ldloc
readonly OpCode System.Reflection.Emit.OpCodes.Ldloc = new OpCode(OpCodeValues.Ldloc, 279317166) static
Definition at line 425 of file OpCodes.cs.
Referenced by System.Reflection.DispatchProxyGenerator.ProxyBuilder.AddMethodImpl(), System.Linq.Expressions.Compiler.LambdaCompiler.AddressOfWriteBackCore(), System.Linq.Expressions.Compiler.LambdaCompiler.AddressOfWriteBackCore(), System.Reflection.DispatchProxyGenerator.ProxyBuilder.GenericArray< T >.BeginSet(), System.Text.Json.Serialization.Metadata.ReflectionEmitMemberAccessor.CreateConstructor(), System.Dynamic.Utils.DelegateHelpers.CreateObjectArrayDelegateRefEmit(), System.Xml.Xsl.IlGen.XmlILVisitor.CreateSetIterator(), System.Xml.Xsl.XmlILGenerator.CreateTypeInitializer(), System.Reflection.Emit.ILGenerator.Emit(), System.Linq.Expressions.Compiler.CompilerScope.LocalBoxStorage.EmitAddress(), System.Linq.Expressions.Compiler.BoundConstants.EmitConstant(), System.Linq.Expressions.Compiler.ILGen.EmitDefault(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitDynamicExpression(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitIndexAssignment(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitLambdaReferenceCoalesce(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitLift(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitLiftedAndAlso(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitLiftedBinaryArithmetic(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitLiftedBooleanAnd(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitLiftedBooleanOr(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitLiftedOrElse(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitListInit(), System.Linq.Expressions.Compiler.CompilerScope.LocalStorage.EmitLoad(), System.Linq.Expressions.Compiler.CompilerScope.LocalBoxStorage.EmitLoad(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitMemberAssignment(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitMemberInit(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitNewExpression(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitNullableCoalesce(), System.Linq.Expressions.Compiler.ILGen.EmitNullableToNullableConversion(), System.Linq.Expressions.Compiler.CompilerScope.ElementBoxStorage.EmitStore(), System.Linq.Expressions.Compiler.CompilerScope.LocalBoxStorage.EmitStore(), System.Linq.Expressions.Compiler.CompilerScope.LocalBoxStorage.EmitStore(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitSwitchBucket(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitSwitchBuckets(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitTryExpression(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitUnary(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitUnaryOperator(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitVariableAssignment(), System.Reflection.Emit.ILGenerator.EmitWriteLine(), System.Xml.Xsl.IlGen.IteratorDescriptor.EnsureNoCache(), System.Reflection.DispatchProxyGenerator.ProxyBuilder.GenericArray< T >.Get(), System.Xml.Xsl.IlGen.XmlILVisitor.HandleFilterPatterns(), System.Runtime.Serialization.CodeGenerator.Ldloc(), System.Xml.Serialization.CodeGenerator.Ldloc(), System.Text.RegularExpressions.RegexCompiler.Ldloc(), System.Reflection.DispatchProxyGenerator.ProxyBuilder.GenericArray< T >.Load(), System.Xml.Xsl.IlGen.GenerateHelper.LoadQueryOutput(), System.Linq.Expressions.Compiler.LabelInfo.MarkWithEmptyStack(), System.Xml.Xsl.IlGen.XmlILVisitor.NestedVisitEnsureCache(), System.Xml.Xsl.IlGen.IteratorDescriptor.PushValue(), System.Xml.Xsl.IlGen.XmlILVisitor.Sequence(), System.Xml.Xsl.IlGen.XmlILVisitor.StartForBinding(), System.Xml.Xsl.IlGen.XmlILVisitor.SyncToNavigator(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitAttribute(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitConditional(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitDataSource(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitGlobalValues(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitParent(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitRoot(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitSort(), and System.Xml.Xsl.IlGen.XmlILVisitor.VisitXsltInvokeLateBound().