Terraria: System.Reflection.Emit.OpCodes.Box
Box
readonly OpCode System.Reflection.Emit.OpCodes.Box = new OpCode(OpCodeValues.Box, 7477933) static
Definition at line 279 of file OpCodes.cs.
Referenced by System.Runtime.Serialization.CodeGenerator.Box(), System.Xml.Serialization.CodeGenerator.Box(), System.Reflection.DispatchProxyGenerator.ProxyBuilder.Convert(), System.Text.Json.Serialization.Metadata.ReflectionEmitMemberAccessor.CreateConstructor(), System.Text.Json.Serialization.Metadata.ReflectionEmitMemberAccessor.CreateFieldGetter(), System.Dynamic.Utils.DelegateHelpers.CreateObjectArrayDelegateRefEmit(), System.Text.Json.Serialization.Metadata.ReflectionEmitMemberAccessor.CreatePropertyGetter(), System.Linq.Expressions.Compiler.ILGen.EmitCastToType(), System.Linq.Expressions.Compiler.ILGen.EmitNullableToReferenceConversion(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitReferenceCoalesceWithoutConversion(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitTypeBinaryExpression(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitUnaryOperator(), and System.Xml.Xsl.IlGen.GenerateHelper.TreatAs().