Terraria: System.Reflection.Emit.OpCodes.Newarr
Newarr
readonly OpCode System.Reflection.Emit.OpCodes.Newarr = new OpCode(OpCodeValues.Newarr, 7485101) static
Definition at line 281 of file OpCodes.cs.
Referenced by System.Reflection.DispatchProxyGenerator.ProxyBuilder.GenericArray< T >.GenericArray(), System.Dynamic.Utils.DelegateHelpers.CreateObjectArrayDelegateRefEmit(), System.Xml.Xsl.XmlILGenerator.CreateTypeInitializer(), System.Linq.Expressions.Compiler.ILGen.EmitArray(), System.Linq.Expressions.Compiler.ILGen.EmitArray(), System.Linq.Expressions.Compiler.CompilerScope.EmitNewHoistedLocals(), System.Runtime.Serialization.CodeGenerator.NewArray(), System.Xml.Serialization.CodeGenerator.NewArray(), and System.Xml.Xsl.IlGen.XmlILVisitor.VisitXsltInvokeLateBound().