Terraria: System.Reflection.Emit.OpCodes.Ldtoken
Ldtoken
readonly OpCode System.Reflection.Emit.OpCodes.Ldtoken = new OpCode(OpCodeValues.Ldtoken, 275385004) static
Definition at line 353 of file OpCodes.cs.
Referenced by System.Reflection.DispatchProxyGenerator.ProxyBuilder.AddMethodImpl(), System.Xml.Xsl.XmlILGenerator.CreateTypeInitializer(), System.Reflection.Emit.DynamicILGenerator.Emit(), System.Reflection.Emit.ILGenerator.Emit(), System.Reflection.Emit.ILGenerator.Emit(), System.Linq.Expressions.Compiler.ILGen.EmitType(), System.Runtime.Serialization.CodeGenerator.Ldtoken(), System.Xml.Serialization.CodeGenerator.Ldtoken(), System.Xml.Xsl.IlGen.GenerateHelper.LoadType(), and System.Linq.Expressions.Compiler.ILGen.TryEmitConstant().