Terraria: System.Reflection.Emit.OpCodes.Ldc_I4_0
Ldc_I4_0
readonly OpCode System.Reflection.Emit.OpCodes.Ldc_I4_0 = new OpCode(OpCodeValues.Ldc_I4_0, 275382949) static
Definition at line 49 of file OpCodes.cs.
Referenced by System.Xml.Xsl.IlGen.XmlILVisitor.Compare(), System.Xml.Xsl.IlGen.GenerateHelper.ConvBranchToBool(), System.Reflection.Emit.ILGenerator.Emit(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitCatchStart(), System.Linq.Expressions.Compiler.ILGen.EmitDefault(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitLift(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitLiftedRelational(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitNullEquality(), System.Linq.Expressions.Compiler.ILGen.EmitPrimitive(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitUnaryOperator(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitUnliftedAndAlso(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitUnliftedBinaryOp(), System.Runtime.Serialization.CodeGenerator.Ldc(), System.Xml.Serialization.CodeGenerator.Ldc(), System.Xml.Xsl.IlGen.GenerateHelper.LoadBoolean(), System.Xml.Xsl.IlGen.XmlILVisitor.StartForBinding(), and System.Xml.Xsl.IlGen.XmlILVisitor.VisitLength().