Terraria: System.Reflection.Emit.OpCodes.Ldnull
Ldnull
readonly OpCode System.Reflection.Emit.OpCodes.Ldnull = new OpCode(OpCodeValues.Ldnull, 275909285) static
Definition at line 45 of file OpCodes.cs.
Referenced by System.Xml.Xsl.IlGen.GenerateHelper.CallValueAs(), System.Xml.Xsl.IlGen.XmlILVisitor.CreateSetIterator(), System.Linq.Expressions.Compiler.ILGen.EmitDefault(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitLift(), System.Linq.Expressions.Compiler.ILGen.EmitNull(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitTypeBinaryExpression(), System.Xml.Xsl.IlGen.XmlILVisitor.GenerateContainerIterator(), System.Xml.Serialization.CodeGenerator.Ldstr(), System.Runtime.Serialization.CodeGenerator.Load(), System.Xml.Serialization.CodeGenerator.Load(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitEmpty(), and System.Xml.Xsl.IlGen.XmlILVisitor.VisitError().