Terraria: System.Reflection.Emit.OpCodes.Stfld
Stfld
readonly OpCode System.Reflection.Emit.OpCodes.Stfld = new OpCode(OpCodeValues.Stfld, -530270559) static
Definition at line 249 of file OpCodes.cs.
Referenced by System.Reflection.Emit.IgnoreAccessChecksToAttributeBuilder.AddToModule(), System.Reflection.DispatchProxyGenerator.ProxyBuilder.Complete(), System.Text.Json.Serialization.Metadata.ReflectionEmitMemberAccessor.CreateFieldSetter(), System.Linq.Expressions.Compiler.ILGen.EmitFieldSet(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitMemberAssignment(), System.Linq.Expressions.Compiler.CompilerScope.ElementBoxStorage.EmitStore(), System.Linq.Expressions.Compiler.CompilerScope.LocalBoxStorage.EmitStore(), System.Linq.Expressions.Compiler.CompilerScope.ElementBoxStorage.EmitStore(), System.Linq.Expressions.Compiler.CompilerScope.LocalBoxStorage.EmitStore(), System.Text.RegularExpressions.RegexCompiler.Stfld(), System.Runtime.Serialization.CodeGenerator.StoreMember(), and System.Xml.Serialization.CodeGenerator.StoreMember().