Terraria: System.Reflection.Emit.OpCodes.Brtrue
Brtrue
readonly OpCode System.Reflection.Emit.OpCodes.Brtrue = new OpCode(OpCodeValues.Brtrue, -261866912) static
Definition at line 119 of file OpCodes.cs.
Referenced by System.Runtime.Serialization.CodeGenerator.Brtrue(), System.Xml.Serialization.CodeGenerator.Brtrue(), System.Text.RegularExpressions.RegexCompiler.BrtrueFar(), System.Xml.Xsl.IlGen.XmlILVisitor.CreateAggregator(), System.Xml.Xsl.IlGen.XmlILVisitor.CreateSetIterator(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitBranchOp(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitCatchStart(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitLambdaReferenceCoalesce(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitLift(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitLiftedAndAlso(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitLiftedOrElse(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitMethodAndAlso(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitMethodOrElse(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitReferenceCoalesceWithoutConversion(), System.Xml.Xsl.IlGen.XmlILVisitor.EndNestedIterator(), System.Xml.Xsl.IlGen.XmlILVisitor.HandleFilterPatterns(), System.Xml.Xsl.IlGen.XmlILVisitor.Sequence(), System.Xml.Xsl.IlGen.GenerateHelper.TestAndBranch(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitConditional(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitEmpty(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitFalse(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitGlobalValues(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitTrue(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitXsltInvokeEarlyBound(), and System.Xml.Xsl.IlGen.XmlILVisitor.ZeroCompare().