Terraria: System.Reflection.Emit.OpCodes.Br_S
Br_S
readonly OpCode System.Reflection.Emit.OpCodes.Br_S = new OpCode(OpCodeValues.Br_S, 23331343) static
Definition at line 89 of file OpCodes.cs.
Referenced by System.Text.RegularExpressions.RegexCompiler.Br(), System.Xml.Serialization.CodeGenerator.Br_S(), System.Xml.Xsl.IlGen.GenerateHelper.ConvBranchToBool(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitLift(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitLiftedAndAlso(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitLiftedBinaryArithmetic(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitLiftedBooleanAnd(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitLiftedBooleanOr(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitLiftedOrElse(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitLiftedToNullRelational(), System.Linq.Expressions.Compiler.ILGen.EmitNullableToNullableConversion(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitReferenceCoalesceWithoutConversion(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitUnary(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitUnaryOperator(), System.Xml.Xsl.IlGen.GenerateHelper.EmitUnconditionalBranch(), and System.Xml.Xsl.IlGen.XmlILVisitor.VisitSortKey().