Terraria: System.Reflection.Emit.OpCodes.Callvirt
Callvirt
readonly OpCode System.Reflection.Emit.OpCodes.Callvirt = new OpCode(OpCodeValues.Callvirt, 7841348) static
Definition at line 225 of file OpCodes.cs.
Referenced by System.Reflection.DispatchProxyGenerator.ProxyBuilder.AddMethodImpl(), System.Xml.Xsl.IlGen.GenerateHelper.Call(), System.Runtime.Serialization.CodeGenerator.Call(), System.Xml.Serialization.CodeGenerator.Call(), System.Text.RegularExpressions.RegexCompiler.Callvirt(), System.Text.Json.Serialization.Metadata.ReflectionEmitMemberAccessor.CreateAddMethodDelegate(), System.Dynamic.Utils.DelegateHelpers.CreateObjectArrayDelegateRefEmit(), System.Text.Json.Serialization.Metadata.ReflectionEmitMemberAccessor.CreatePropertyGetter(), System.Text.Json.Serialization.Metadata.ReflectionEmitMemberAccessor.CreatePropertySetter(), System.Reflection.Emit.ILGenerator.Emit(), System.Reflection.Emit.DynamicILGenerator.EmitCall(), System.Reflection.Emit.ILGenerator.EmitCall(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitCall(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitDelegateConstruction(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitDynamicExpression(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitLambdaReferenceCoalesce(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitMethodCall(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitNullableCoalesce(), System.Reflection.Emit.ILGenerator.EmitWriteLine(), and System.Reflection.Emit.ILGenerator.EmitWriteLine().