Terraria: System.Reflection.Emit.OpCodes.Ldc_I4
Ldc_I4
readonly OpCode System.Reflection.Emit.OpCodes.Ldc_I4 = new OpCode(OpCodeValues.Ldc_I4, 275384994) static
Definition at line 69 of file OpCodes.cs.
Referenced by System.Reflection.DispatchProxyGenerator.ProxyBuilder.GenericArray< T >.GenericArray(), System.Reflection.DispatchProxyGenerator.ProxyBuilder.AddMethodImpl(), System.Reflection.DispatchProxyGenerator.ProxyBuilder.GenericArray< T >.BeginSet(), System.Dynamic.Utils.DelegateHelpers.CreateObjectArrayDelegateRefEmit(), System.Reflection.Emit.ILGenerator.Emit(), System.Linq.Expressions.Compiler.ILGen.EmitPrimitive(), System.Reflection.DispatchProxyGenerator.ProxyBuilder.GenericArray< T >.Get(), System.Text.RegularExpressions.RegexCompiler.Ldc(), System.Runtime.Serialization.CodeGenerator.Ldc(), System.Xml.Serialization.CodeGenerator.Ldc(), and System.Xml.Xsl.IlGen.GenerateHelper.LoadInteger().