Terraria: System.Reflection.Emit.OpCodes.Stloc
Stloc
readonly OpCode System.Reflection.Emit.OpCodes.Stloc = new OpCode(OpCodeValues.Stloc, -257680722) static
Definition at line 429 of file OpCodes.cs.
Referenced by System.Reflection.DispatchProxyGenerator.ProxyBuilder.GenericArray< T >.GenericArray(), System.Reflection.DispatchProxyGenerator.ProxyBuilder.AddMethodImpl(), System.Linq.Expressions.Compiler.LambdaCompiler.AddressOfWriteBackCore(), System.Linq.Expressions.Compiler.LambdaCompiler.AddressOfWriteBackCore(), System.Dynamic.Utils.DelegateHelpers.CreateObjectArrayDelegateRefEmit(), System.Xml.Xsl.IlGen.XmlILVisitor.CreateSetIterator(), System.Xml.Xsl.XmlILGenerator.CreateTypeInitializer(), System.Reflection.Emit.ILGenerator.Emit(), System.Linq.Expressions.Compiler.BoundConstants.EmitCacheConstants(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitDynamicExpression(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitExpressionAddress(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitIndexAssignment(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitLambdaReferenceCoalesce(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitLift(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitLiftedAndAlso(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitLiftedBinaryArithmetic(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitLiftedBooleanAnd(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitLiftedBooleanOr(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitLiftedOrElse(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitLiftedRelational(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitLiftedToNullRelational(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitListInit(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitMemberAddress(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitMemberAssignment(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitMemberInit(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitNullableCoalesce(), System.Linq.Expressions.Compiler.ILGen.EmitNullableToNonNullableStructConversion(), System.Linq.Expressions.Compiler.ILGen.EmitNullableToNullableConversion(), System.Linq.Expressions.Compiler.CompilerScope.LocalStorage.EmitStore(), System.Linq.Expressions.Compiler.CompilerScope.ElementBoxStorage.EmitStore(), System.Linq.Expressions.Compiler.CompilerScope.LocalBoxStorage.EmitStore(), System.Linq.Expressions.Compiler.CompilerScope.LocalBoxStorage.EmitStoreBox(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitTryExpression(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitUnary(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitUnaryOperator(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitVariableAssignment(), System.Xml.Xsl.IlGen.IteratorDescriptor.EnsureLocal(), System.Xml.Xsl.IlGen.IteratorDescriptor.EnsureNoCache(), System.Xml.Xsl.IlGen.GenerateHelper.MethodBegin(), System.Xml.Xsl.IlGen.XmlILVisitor.NestedVisitEnsureCache(), System.Xml.Xsl.IlGen.XmlILVisitor.Sequence(), System.Xml.Xsl.IlGen.XmlILVisitor.StartForBinding(), System.Runtime.Serialization.CodeGenerator.Stloc(), System.Xml.Serialization.CodeGenerator.Stloc(), System.Text.RegularExpressions.RegexCompiler.Stloc(), System.Linq.Expressions.Compiler.LabelInfo.StoreValue(), System.Xml.Xsl.IlGen.XmlILVisitor.SyncToNavigator(), System.Linq.Expressions.Compiler.LambdaCompiler.TryEmitSwitchInstruction(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitDataSource(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitGlobalValues(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitSort(), and System.Xml.Xsl.IlGen.XmlILVisitor.VisitXsltInvokeLateBound().