Terraria: ReLogic.Text.WrappedTextBuilder.Append
Append() [2/2]
void ReLogic.Text.WrappedTextBuilder.Append (string text) inline
Definition at line 140 of file WrappedTextBuilder.cs.
    {
        StringReader stringReader = new StringReader(text);
        _completedText.EnsureCapacity(_completedText.Capacity + text.Length);
        while (stringReader.Peek() > 0)
        {
            if ((ushort)stringReader.Peek() == 10)
            {
                stringReader.Read();
                CommitWorkingLine();
            }
            else
            {
                string text2 = stringReader.ReadUntilBreakable(_culture);
                Append(new NonBreakingText(_font, text2));
            }
        }
    }
References ReLogic.Text.WrappedTextBuilder._completedText, ReLogic.Text.WrappedTextBuilder._culture, ReLogic.Text.WrappedTextBuilder._font, System.IO.Append, System.Text.StringBuilder.Capacity, ReLogic.Text.WrappedTextBuilder.CommitWorkingLine(), System.Text.StringBuilder.EnsureCapacity(), System.IO.StringReader.Peek(), and System.IO.StringReader.Read().