Terraria: System.Net.Http.Headers.MediaTypeHeaderValue.ToString
ToString()
override string System.Net.Http.Headers.MediaTypeHeaderValue.ToString () inline inherited
Definition at line 73 of file MediaTypeHeaderValue.cs.
    {
        if (_parameters == null || _parameters.Count == 0)
        {
            return _mediaType ?? string.Empty;
        }
        StringBuilder stringBuilder = System.Text.StringBuilderCache.Acquire();
        stringBuilder.Append(_mediaType);
        NameValueHeaderValue.ToString(_parameters, ';', leadingSeparator: true, stringBuilder);
        return System.Text.StringBuilderCache.GetStringAndRelease(stringBuilder);
    }
References System.Net.Http.Headers.MediaTypeHeaderValue._mediaType, System.Net.Http.Headers.MediaTypeHeaderValue._parameters, System.Text.StringBuilderCache.Acquire(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Text.StringBuilderCache.GetStringAndRelease(), and System.Net.Http.Headers.NameValueHeaderValue.ToString().