Terraria: StyleDimension.StyleDimension
StyleDimension()
StyleDimension.StyleDimension (float pixels, float precent) inline
     {
         Pixels = pixels;
         Precent = precent;
     }
References Pixels, and Precent.
Referenced by FromPercent(), FromPixels(), and FromPixelsAndPercent().