Terraria: StyleDimension.Set
Set()
void StyleDimension.Set (float pixels, float precent) inline
     {
         Pixels = pixels;
         Precent = precent;
     }
References Pixels, and Precent.
Referenced by EmoteButton.EmoteButton(), EmotesGroupListItem.EmotesGroupListItem(), UIAchievementListItem.UIAchievementListItem(), UIBestiaryEntryButton.UIBestiaryEntryButton(), UIBestiaryEntryIcon.UIBestiaryEntryIcon(), UIBestiaryEntryInfoPage.UIBestiaryEntryInfoPage(), UIBestiaryInfoItemLine.UIBestiaryInfoItemLine(), UIBestiaryNPCEntryPortrait.UIBestiaryNPCEntryPortrait(), UICharacter.UICharacter(), UICharacterListItem.UICharacterListItem(), UIColoredImageButton.UIColoredImageButton(), UICreativeItemsInfiniteFilteringOptions.UICreativeItemsInfiniteFilteringOptions(), UIHorizontalSeparator.UIHorizontalSeparator(), UIImageButton.UIImageButton(), UIImageFramed.UIImageFramed(), UIItemIcon.UIItemIcon(), UIList.UIList(), UIScrollbar.UIScrollbar(), UISlicedImage.UISlicedImage(), UIToggleImage.UIToggleImage(), UIVerticalSeparator.UIVerticalSeparator(), UIWorkshopImportWorldListItem.UIWorkshopImportWorldListItem(), UIWorkshopPublishWorldListItem.UIWorkshopPublishWorldListItem(), UIWorldCreationPreview.UIWorldCreationPreview(), UIWorldListItem.UIWorldListItem(), UIBestiaryTest.BuildPage(), UIReportsPage.BuildPage(), UIResourcePackInfoMenu.BuildPage(), UIResourcePackSelectionMenu.BuildPage(), UIBestiaryEntryInfoPage.CheckScrollBar(), UIManageControls.CreateBindingGroup(), UICharacterCreation.CreateColorPicker(), UIManageControls.CreateElementGroup(), UICharacterCreation.CreateHSLSlider(), UICharacterCreation.CreatePickerWithoutClick(), AWorkshopPublishInfoState< TPublishedObjectType >.CreateSteamDisclaimer(), AWorkshopPublishInfoState< TPublishedObjectType >.CreateTagOptionsPanel(), UIList.DrawSelf(), UIBestiaryEntryGrid.FillBestiarySpaceWithEntries(), UIWorkshopImportWorldListItem.InitializeAppearance(), UIWorkshopPublishResourcePackListItem.InitializeAppearance(), UIWorkshopPublishWorldListItem.InitializeAppearance(), UIWorldListItem.InitializeAppearance(), UIAchievementsMenu.InitializePage(), UIEmotesMenu.InitializePage(), UIText.InternalSetText(), UIWorkshopHub.MakeFancyButton(), UIAchievementsMenu.OnActivate(), UIEmotesMenu.OnActivate(), UIManageControls.OnActivate(), AWorkshopPublishInfoState< TPublishedObjectType >.OnInitialize(), UICharacterSelect.OnInitialize(), UIManageControls.OnInitialize(), UIWorkshopHub.OnInitialize(), UIWorkshopSelectResourcePackToPublish.OnInitialize(), UIWorkshopSelectWorldToPublish.OnInitialize(), UIWorkshopWorldImport.OnInitialize(), UIWorldSelect.OnInitialize(), UICharacterSelect.Recalculate(), UIEmotesMenu.Recalculate(), UIReportsPage.Recalculate(), UIResourcePackInfoMenu.Recalculate(), UIWorkshopSelectResourcePackToPublish.Recalculate(), UIWorkshopSelectWorldToPublish.Recalculate(), UIWorkshopWorldImport.Recalculate(), UIWorldSelect.Recalculate(), UIImageWithBorder.SetBorder(), UIImageFramed.SetFrame(), UIColoredImageButton.SetImage(), UIImage.SetImage(), UIImageButton.SetImage(), UIImageFramed.SetImage(), UIIconTextButton.SetText(), UIBestiaryInfoLine< T >.SetText(), UITextPanel< T >.SetText(), AWorkshopPublishInfoState< TPublishedObjectType >.UpdateScrollbar(), and UIDynamicItemCollection.UpdateSize().