Terraria: Terraria.GameContent.Events.BirthdayParty.NaturalAttempt
NaturalAttempt()
static void Terraria.GameContent.Events.BirthdayParty.NaturalAttempt () inline static private
Definition at line 73 of file BirthdayParty.cs.
    {
        if (Main.netMode == 1 || !NPC.AnyNPCs(208))
        {
            return;
        }
        if (PartyDaysOnCooldown > 0)
        {
            PartyDaysOnCooldown--;
            return;
        }
        int maxValue = 10;
        if (Main.tenthAnniversaryWorld)
        {
            maxValue = 7;
        }
        if (Main.rand.Next(maxValue) != 0)
        {
            return;
        }
        List<NPC> list = new List<NPC>();
        for (int j = 0; j < 200; j++)
        {
            NPC nPC = Main.npc[j];
            if (CanNPCParty(nPC))
            {
                list.Add(nPC);
            }
        }
        if (list.Count >= 5)
        {
            GenuineParty = true;
            PartyDaysOnCooldown = Main.rand.Next(5, 11);
            NPC.freeCake = true;
            CelebratingNPCs.Clear();
            List<int> list2 = new List<int>();
            int num = 1;
            if (Main.rand.Next(5) == 0 && list.Count > 12)
            {
                num = 3;
            }
            else if (Main.rand.Next(3) == 0)
            {
                num = 2;
            }
            list = list.OrderBy((NPC i) => Main.rand.Next()).ToList();
            for (int k = 0; k < num; k++)
            {
                list2.Add(k);
            }
            for (int l = 0; l < list2.Count; l++)
            {
                CelebratingNPCs.Add(list[list2[l]].whoAmI);
            }
            Color color = new Color(255, 0, 160);
            if (CelebratingNPCs.Count == 3)
            {
                WorldGen.BroadcastText(NetworkText.FromKey("Game.BirthdayParty_3", Main.npc[CelebratingNPCs[0]].GetGivenOrTypeNetName(), Main.npc[CelebratingNPCs[1]].GetGivenOrTypeNetName(), Main.npc[CelebratingNPCs[2]].GetGivenOrTypeNetName()), color);
            }
            else if (CelebratingNPCs.Count == 2)
            {
                WorldGen.BroadcastText(NetworkText.FromKey("Game.BirthdayParty_2", Main.npc[CelebratingNPCs[0]].GetGivenOrTypeNetName(), Main.npc[CelebratingNPCs[1]].GetGivenOrTypeNetName()), color);
            }
            else
            {
                WorldGen.BroadcastText(NetworkText.FromKey("Game.BirthdayParty_1", Main.npc[CelebratingNPCs[0]].GetGivenOrTypeNetName()), color);
            }
            NetMessage.SendData(7);
            CheckForAchievement();
        }
    }
References Terraria.NPC.AnyNPCs(), Terraria.WorldGen.BroadcastText(), Terraria.GameContent.Events.BirthdayParty.CanNPCParty(), Terraria.GameContent.Events.BirthdayParty.CelebratingNPCs, Terraria.GameContent.Events.BirthdayParty.CheckForAchievement(), Terraria.Localization.NetworkText.FromKey(), Terraria.GameContent.Events.BirthdayParty.GenuineParty, Terraria.NPC.GetGivenOrTypeNetName(), Terraria.Main.netMode, Terraria.Main.npc, Terraria.GameContent.Events.BirthdayParty.PartyDaysOnCooldown, Terraria.Main.rand, Terraria.NetMessage.SendData(), and Terraria.Main.tenthAnniversaryWorld.
Referenced by Terraria.GameContent.Events.BirthdayParty.CheckMorning().