Terraria: Terraria.GameContent.Events.BirthdayParty.CheckNight
CheckNight()
static void Terraria.GameContent.Events.BirthdayParty.CheckNight () inline static
Definition at line 40 of file BirthdayParty.cs.
    {
        bool flag = false;
        if (GenuineParty)
        {
            flag = true;
            GenuineParty = false;
            CelebratingNPCs.Clear();
        }
        if (ManualParty)
        {
            flag = true;
            ManualParty = false;
        }
        if (flag)
        {
            WorldGen.BroadcastText(color: new Color(255, 0, 160), text: NetworkText.FromKey(Lang.misc[99].Key));
        }
    }
References Terraria.WorldGen.BroadcastText(), Terraria.GameContent.Events.BirthdayParty.CelebratingNPCs, Terraria.Localization.NetworkText.FromKey(), Terraria.GameContent.Events.BirthdayParty.GenuineParty, Terraria.GameContent.Events.BirthdayParty.ManualParty, and Terraria.Lang.misc.
Referenced by Terraria.Main.UpdateTime_StartNight().