Terraria: System.Globalization.TimeSpanParse.StringParser.TryParse
TryParse()
bool System.Globalization.TimeSpanParse.StringParser.TryParse (ReadOnlySpan< char > input, ref TimeSpanResult result) inline package
Definition at line 538 of file TimeSpanParse.cs.
        {
            result.parsedTimeSpan = default(TimeSpan);
            _str = input;
            _len = input.Length;
            _pos = -1;
            NextChar();
            SkipBlanks();
            bool flag = false;
            if (_ch == '-')
            {
                flag = true;
                NextChar();
            }
            long time;
            if (NextNonDigit() == ':')
            {
                if (!ParseTime(out time, ref result))
                {
                    return false;
                }
            }
            else
            {
                if (!ParseInt(10675199, out var i, ref result))
                {
                    return false;
                }
                time = i * 864000000000L;
                if (_ch == '.')
                {
                    NextChar();
                    if (!ParseTime(out var time2, ref result))
                    {
                        return false;
                    }
                    time += time2;
                }
            }
            if (flag)
            {
                time = -time;
                if (time > 0)
                {
                    return result.SetOverflowFailure();
                }
            }
            else if (time < 0)
            {
                return result.SetOverflowFailure();
            }
            SkipBlanks();
            if (_pos < _len)
            {
                return result.SetBadTimeSpanFailure();
            }
            result.parsedTimeSpan = new TimeSpan(time);
            return true;
        }
References System.Globalization.TimeSpanParse.StringParser._ch, System.Globalization.TimeSpanParse.StringParser._len, System.Globalization.TimeSpanParse.StringParser._pos, System.Globalization.TimeSpanParse.StringParser._str, System.input, System.L, System.Globalization.TimeSpanParse.StringParser.NextChar(), System.Globalization.TimeSpanParse.StringParser.NextNonDigit(), System.Globalization.TimeSpanParse.StringParser.ParseInt(), System.Globalization.TimeSpanParse.StringParser.ParseTime(), and System.Globalization.TimeSpanParse.StringParser.SkipBlanks().