Terraria: System.Diagnostics.Metrics.Instrument.RecordMeasurement
RecordMeasurement() [1/6]
void System.Diagnostics.Metrics.Instrument< T >.RecordMeasurement (T measurement) inline protected inherited
Definition at line 126 of file Instrument.cs.
    {
        RecordMeasurement(measurement, Instrument.EmptyTags.AsSpan());
    }
References System.Diagnostics.Metrics.Instrument< T >.EmptyTags, and System.Diagnostics.Metrics.Instrument< T >.RecordMeasurement().
Referenced by System.Diagnostics.Metrics.Counter< T >.Add(), System.Diagnostics.Metrics.Counter< T >.Add(), System.Diagnostics.Metrics.Counter< T >.Add(), System.Diagnostics.Metrics.Counter< T >.Add(), System.Diagnostics.Metrics.Counter< T >.Add(), System.Diagnostics.Metrics.Counter< T >.Add(), System.Diagnostics.Metrics.Counter< T >.Add(), System.Diagnostics.Metrics.Histogram< T >.Record(), System.Diagnostics.Metrics.Histogram< T >.Record(), System.Diagnostics.Metrics.Histogram< T >.Record(), System.Diagnostics.Metrics.Histogram< T >.Record(), System.Diagnostics.Metrics.Histogram< T >.Record(), System.Diagnostics.Metrics.Histogram< T >.Record(), System.Diagnostics.Metrics.Histogram< T >.Record(), System.Diagnostics.Metrics.Instrument< T >.RecordMeasurement(), System.Diagnostics.Metrics.Instrument< T >.RecordMeasurement(), System.Diagnostics.Metrics.Instrument< T >.RecordMeasurement(), System.Diagnostics.Metrics.Instrument< T >.RecordMeasurement(), and System.Diagnostics.Metrics.Instrument< T >.RecordMeasurement().