Terraria: UISelectableTextPanel.DrawSelf
DrawSelf()
override void UISelectableTextPanel< T >.DrawSelf (SpriteBatch spriteBatch) inline protected virtual
Reimplemented from UIPanel.
     {
         if (_drawPanel)
         {
             CalculatedStyle dimensions = GetDimensions();
             int num = 4;
             int num2 = 10;
             int num3 = 10;
             Utils.DrawSplicedPanel(spriteBatch, _BasePanelTexture.Value, (int)dimensions.X, (int)dimensions.Y, (int)dimensions.Width, (int)dimensions.Height, num2, num2, num3, num3, Color.Lerp(Color.Black, _color, 0.8f) * 0.5f);
             if (IsSelected != null && IsSelected(this))
             {
                 Utils.DrawSplicedPanel(spriteBatch, _BasePanelTexture.Value, (int)dimensions.X + num, (int)dimensions.Y + num, (int)dimensions.Width - num * 2, (int)dimensions.Height - num * 2, num2, num2, num3, num3, Color.Lerp(_color, Color.White, 0.7f) * 0.5f);
             }
             if (base.IsMouseHovering)
             {
                 Utils.DrawSplicedPanel(spriteBatch, _hoveredBorderTexture.Value, (int)dimensions.X, (int)dimensions.Y, (int)dimensions.Width, (int)dimensions.Height, num2, num2, num3, num3, Color.White);
             }
         }
         DrawText(spriteBatch);
     }
References UISelectableTextPanel< T >._BasePanelTexture, UITextPanel< T >._color, UITextPanel< T >._drawPanel, UISelectableTextPanel< T >._hoveredBorderTexture, Color, Utils.DrawSplicedPanel(), UITextPanel< T >.DrawText(), UIElement.GetDimensions(), CalculatedStyle.Height, UISelectableTextPanel< T >.IsSelected, Asset< T >.Value, CalculatedStyle.Width, CalculatedStyle.X, and CalculatedStyle.Y.