Terraria: System.Diagnostics.Metrics.Instrument._subscriptions
_subscriptions
readonly DiagLinkedList<ListenerSubscription> System.Diagnostics.Metrics.Instrument< T >._subscriptions = new DiagLinkedList<ListenerSubscription>() package inherited
Definition at line 9 of file Instrument.cs.
Referenced by System.Diagnostics.Metrics.Instrument< T >.DisableMeasurements(), System.Diagnostics.Metrics.Instrument< T >.EnableMeasurement(), System.Diagnostics.Metrics.Instrument< T >.GetSubscriptionState(), System.Diagnostics.Metrics.Instrument< T >.NotifyForUnpublishedInstrument(), and System.Diagnostics.Metrics.Instrument< T >.RecordMeasurement().