Terraria: System.Diagnostics.Metrics.Instrument.SyncObject
SyncObject
object System.Diagnostics.Metrics.Instrument< T >.SyncObject = new object() static get package inherited
Definition at line 13 of file Instrument.cs.
{ get; } = new object();
Referenced by System.Diagnostics.Metrics.Meter.Meter(), System.Diagnostics.Metrics.MeterListener.DisableMeasurementEvents(), System.Diagnostics.Metrics.Meter.Dispose(), System.Diagnostics.Metrics.MeterListener.Dispose(), System.Diagnostics.Metrics.MeterListener.EnableMeasurementEvents(), System.Diagnostics.Metrics.Instrument< T >.Publish(), and System.Diagnostics.Metrics.MeterListener.Start().