Terraria: System.ModuleHandle.ResolveFieldHandle
ResolveFieldHandle() [2/2]
unsafe RuntimeFieldHandle System.ModuleHandle.ResolveFieldHandle (int fieldToken, RuntimeTypeHandle?[] typeInstantiationContext, RuntimeTypeHandle?[] methodInstantiationContext) inline
Definition at line 207 of file ModuleHandle.cs.
    {
        RuntimeModule module = GetRuntimeModule();
        ValidateModulePointer(module);
        IntPtr[] array = null;
        int length = 0;
        IntPtr[] array2 = null;
        int length2 = 0;
        if (typeInstantiationContext != null && typeInstantiationContext.Length != 0)
        {
            typeInstantiationContext = (RuntimeTypeHandle[])typeInstantiationContext.Clone();
            array = RuntimeTypeHandle.CopyRuntimeTypeHandles(typeInstantiationContext, out length);
        }
        if (methodInstantiationContext != null && methodInstantiationContext.Length != 0)
        {
            methodInstantiationContext = (RuntimeTypeHandle[])methodInstantiationContext.Clone();
            array2 = RuntimeTypeHandle.CopyRuntimeTypeHandles(methodInstantiationContext, out length2);
        }
        fixed (IntPtr* typeInstArgs = array)
        {
            fixed (IntPtr* methodInstArgs = array2)
            {
                try
                {
                    IRuntimeFieldInfo o = null;
                    ResolveField(new QCallModule(ref module), fieldToken, typeInstArgs, length, methodInstArgs, length2, ObjectHandleOnStack.Create(ref o));
                    GC.KeepAlive(typeInstantiationContext);
                    GC.KeepAlive(methodInstantiationContext);
                    return new RuntimeFieldHandle(o);
                }
                catch (Exception)
                {
                    if (!GetMetadataImport(module).IsValidToken(fieldToken))
                    {
                        throw new ArgumentOutOfRangeException("fieldToken", SR.Format(SR.Argument_InvalidToken, fieldToken, new ModuleHandle(module)));
                    }
                    throw;
                }
            }
        }
    }
References System.SR.Argument_InvalidToken, System.array, System.RuntimeTypeHandle.CopyRuntimeTypeHandles(), System.SR.Format(), System.ModuleHandle.GetMetadataImport(), System.ModuleHandle.GetRuntimeModule(), System.GC.KeepAlive(), System.length, System.length2, System.ModuleHandle.ResolveField(), and System.ModuleHandle.ValidateModulePointer().