Terraria: System.ModuleHandle.ResolveMethodHandleInternal
ResolveMethodHandleInternal()
static unsafe RuntimeMethodHandleInternal System.ModuleHandle.ResolveMethodHandleInternal (RuntimeModule module, int methodToken, IntPtr[] typeInstantiationContext, int typeInstCount, IntPtr[] methodInstantiationContext, int methodInstCount) inline static package
Definition at line 168 of file ModuleHandle.cs.
    {
        ValidateModulePointer(module);
        try
        {
            fixed (IntPtr* typeInstArgs = typeInstantiationContext)
            {
                fixed (IntPtr* methodInstArgs = methodInstantiationContext)
                {
                    return ResolveMethod(new QCallModule(ref module), methodToken, typeInstArgs, typeInstCount, methodInstArgs, methodInstCount);
                }
            }
        }
        catch (Exception)
        {
            if (!GetMetadataImport(module).IsValidToken(methodToken))
            {
                throw new ArgumentOutOfRangeException("methodToken", SR.Format(SR.Argument_InvalidToken, methodToken, new ModuleHandle(module)));
            }
            throw;
        }
    }
References System.SR.Argument_InvalidToken, System.SR.Format(), System.ModuleHandle.GetMetadataImport(), System.ModuleHandle.ResolveMethod(), and System.ModuleHandle.ValidateModulePointer().
Referenced by System.Reflection.Associates.AssignAssociates(), and System.ModuleHandle.ResolveMethodHandle().