Terraria: System.ModuleHandle.GetMetadataImport
GetMetadataImport()
static MetadataImport System.ModuleHandle.GetMetadataImport (RuntimeModule module) inline static package
Definition at line 288 of file ModuleHandle.cs.
    {
        return new MetadataImport(_GetMetadataImport(module), module);
    }
References System.ModuleHandle._GetMetadataImport().
Referenced by System.Reflection.PseudoCustomAttribute.GetDllImportCustomAttribute(), System.Reflection.PseudoCustomAttribute.GetMarshalAsCustomAttribute(), System.RuntimeType.RuntimeTypeCache.MemberInfoCache< T >.PopulateNestedClasses(), System.Reflection.RuntimeModule.ResolveField(), System.ModuleHandle.ResolveFieldHandle(), System.ModuleHandle.ResolveMethodHandleInternal(), and System.ModuleHandle.ResolveTypeHandle().