Terraria: System.IO.Compression.Deflater.GetDeflateOutput
GetDeflateOutput()
int System.IO.Compression.Deflater.GetDeflateOutput (byte[] outputBuffer) inline package
Definition at line 121 of file Deflater.cs.
    {
        try
        {
            ReadDeflateOutput(outputBuffer, ZLibNative.FlushCode.NoFlush, out var bytesRead);
            return bytesRead;
        }
        finally
        {
            if (_zlibStream.AvailIn == 0)
            {
                DeallocateInputBufferHandle();
            }
        }
    }
References System.IO.Compression.Deflater._zlibStream, System.IO.Compression.Deflater.DeallocateInputBufferHandle(), and System.IO.Compression.Deflater.ReadDeflateOutput().
Referenced by System.IO.Compression.DeflateStream.WriteDeflaterOutput(), and System.IO.Compression.DeflateStream.WriteDeflaterOutputAsync().