Terraria: System.IO.Compression.Deflater.ReadDeflateOutput
ReadDeflateOutput()
unsafe ZLibNative.ErrorCode System.IO.Compression.Deflater.ReadDeflateOutput (byte[] outputBuffer, ZLibNative::FlushCode flushCode, out int bytesRead) inline private
Definition at line 137 of file Deflater.cs.
    {
        lock (SyncLock)
        {
            fixed (byte* ptr = &outputBuffer[0])
            {
                _zlibStream.NextOut = (IntPtr)ptr;
                _zlibStream.AvailOut = (uint)outputBuffer.Length;
                ZLibNative.ErrorCode result = Deflate(flushCode);
                bytesRead = outputBuffer.Length - (int)_zlibStream.AvailOut;
                return result;
            }
        }
    }
References System.IO.Compression.Deflater._zlibStream, System.IO.Compression.Deflate, and System.IO.Compression.Deflater.SyncLock.
Referenced by System.IO.Compression.Deflater.Finish(), System.IO.Compression.Deflater.Flush(), and System.IO.Compression.Deflater.GetDeflateOutput().