Terraria: System.IO.Compression.Deflater.SetInput
SetInput() [2/2]
unsafe void System.IO.Compression.Deflater.SetInput (ReadOnlyMemory< byte > inputBuffer) inline package
Definition at line 94 of file Deflater.cs.
    {
        if (inputBuffer.Length == 0)
        {
            return;
        }
        lock (SyncLock)
        {
            _inputBufferHandle = inputBuffer.Pin();
            _zlibStream.NextIn = (IntPtr)_inputBufferHandle.Pointer;
            _zlibStream.AvailIn = (uint)inputBuffer.Length;
        }
    }
References System.IO.Compression.Deflater._inputBufferHandle, System.ReadOnlyMemory< T >.Length, System.ReadOnlyMemory< T >.Pin(), System.Buffers.MemoryHandle.Pointer, and System.IO.Compression.Deflater.SyncLock.
Referenced by System.IO.Compression.DeflateStream.WriteAsyncMemory(), and System.IO.Compression.DeflateStream.WriteCore().