Terraria: System.IO.Compression.Deflater.Flush
Flush()
bool System.IO.Compression.Deflater.Flush (byte[] outputBuffer, out int bytesRead) inline package
Definition at line 158 of file Deflater.cs.
    {
        return ReadDeflateOutput(outputBuffer, ZLibNative.FlushCode.SyncFlush, out bytesRead) == ZLibNative.ErrorCode.Ok;
    }
References System.IO.Compression.Deflater.ReadDeflateOutput().
Referenced by System.IO.Compression.DeflateStream.FlushAsync(), and System.IO.Compression.DeflateStream.FlushBuffers().