Terraria: Terraria.Animation.NewTemporaryAnimation
NewTemporaryAnimation()
static void Terraria.Animation.NewTemporaryAnimation (int type, ushort tileType, int x, int y) inline static
Definition at line 102 of file Animation.cs.
    {
        Point16 coordinates = new Point16(x, y);
        if (x >= 0 && x < Main.maxTilesX && y >= 0 && y < Main.maxTilesY)
        {
            Animation animation = new Animation();
            animation.SetDefaults(type);
            animation._tileType = tileType;
            animation._coordinates = coordinates;
            animation._temporary = true;
            _awaitingAddition.Add(animation);
            if (Main.netMode == 2)
            {
                NetMessage.SendTemporaryAnimation(-1, type, tileType, x, y);
            }
        }
    }
References Terraria.Animation._awaitingAddition, Terraria.Main.maxTilesY, Terraria.Main.netMode, and Terraria.NetMessage.SendTemporaryAnimation().
Referenced by Terraria.MessageBuffer.GetData(), Terraria.Wiring.HitWireSingle(), and Terraria.Player.TileInteractionsUse().