Terraria: System.Net.Quic.Implementations.Mock.MockConnection.OpenStream
OpenStream()
MockStream System.Net.Quic.Implementations.Mock.MockConnection.OpenStream (long streamId, bool bidirectional) inline package
Definition at line 339 of file MockConnection.cs.
    {
        CheckDisposed();
        ConnectionState state = _state;
        if (state == null)
        {
            throw new InvalidOperationException("Not connected");
        }
        MockStream.StreamState streamState = new MockStream.StreamState(streamId, bidirectional);
        state._streams[streamState._streamId] = streamState;
        Channel<MockStream.StreamState> channel = (_isClient ? state._clientInitiatedStreamChannel : state._serverInitiatedStreamChannel);
        channel.Writer.TryWrite(streamState);
        return new MockStream(this, streamState, isInitiator: true);
    }
References System.Net.Quic.Implementations.Mock.MockConnection._isClient, System.Net.Quic.Implementations.Mock.MockConnection._state, System.Net.Quic.Implementations.Mock.MockConnection.CheckDisposed(), and System.state.
Referenced by System.Net.Quic.Implementations.Mock.MockConnection.OpenBidirectionalStream(), and System.Net.Quic.Implementations.Mock.MockConnection.OpenUnidirectionalStream().