Terraria: Terraria.GameContent.UI.Elements.UIVerticalSeparator.DrawSelf
DrawSelf()
override void Terraria.GameContent.UI.Elements.UIVerticalSeparator.DrawSelf (SpriteBatch spriteBatch) inline protected virtual
Reimplemented from Terraria.UI.UIElement.
Definition at line 24 of file UIVerticalSeparator.cs.
    {
        CalculatedStyle dimensions = GetDimensions();
        spriteBatch.Draw(_texture.Value, dimensions.ToRectangle(), Color);
    }
References Terraria.GameContent.UI.Elements.UIVerticalSeparator._texture, Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(), Terraria.UI.UIElement.GetDimensions(), Terraria.UI.CalculatedStyle.ToRectangle(), and ReLogic.Content.Asset< T >.Value.