Terraria: ChromaEngine.Draw
Draw()
void ChromaEngine.Draw () inline private
     {
         lock (_updateLock)
         {
             try
             {
                 for (int i = 0; i <= 1; i++)
                 {
                     EffectDetailLevel detail = (EffectDetailLevel)i;
                     ICollection<ShaderOperation> shaders = _shaderSelector.AtDetailLevel(detail);
                     foreach (RgbDeviceGroup value in _deviceGroups.Values)
                     {
                         _pipeline.Process(value.Where((RgbDevice device) => device.PreferredLevelOfDetail == detail), shaders, _lastTime);
                     }
                 }
             }
             catch
             {
                 DisableAllDeviceGroups();
             }
             foreach (RgbDeviceGroup value2 in _deviceGroups.Values)
             {
                 value2.OnceProcessed();
             }
         }
     }
References _deviceGroups, _lastTime, _pipeline, _shaderSelector, _updateLock, ShaderSelector.AtDetailLevel(), DisableAllDeviceGroups(), RgbDeviceGroup.OnceProcessed(), RgbDevice.PreferredLevelOfDetail, and ChromaPipeline.Process().