Terraria: ChromaEngine.Update
Update()
void ChromaEngine.Update (float totalTime) inline
     {
         if (_deviceGroups.Count == 0)
         {
             return;
         }
         if (totalTime < _lastTime)
         {
             _lastTime = totalTime;
         }
         float num = totalTime - _lastTime;
         if (!(num >= FrameTimeInSeconds) || !Monitor.TryEnter(_updateLock))
         {
             return;
         }
         try
         {
             if (this.OnUpdate != null)
             {
                 this.OnUpdate(this, new ChromaEngineUpdateEventArgs(num));
             }
             _hotkeys.UpdateAll(num);
             _shaderSelector.Update(num);
             _lastTime = totalTime;
             ThreadPool.QueueUserWorkItem(delegate(object context)
             {
                 ((ChromaEngine)context).Draw();
             }, this);
         }
         catch
         {
             DisableAllDeviceGroups();
         }
         finally
         {
             Monitor.Exit(_updateLock);
         }
     }
References ChromaEngine(), _deviceGroups, _hotkeys, _lastTime, _shaderSelector, _updateLock, DisableAllDeviceGroups(), FrameTimeInSeconds, OnUpdate, ShaderSelector.Update(), and HotkeyCollection.UpdateAll().
Referenced by Main.DoUpdate().