Terraria: ReLogic.Localization.IME.WinImm32Ime.SetEnabled
SetEnabled()
void ReLogic.Localization.IME.WinImm32Ime.SetEnabled (bool bEnable) inline private
Definition at line 60 of file WinImm32Ime.cs.
    {
        ReLogic.Localization.IME.WinImm32.NativeMethods.ImmAssociateContext(_hWnd, bEnable ? _hImc : IntPtr.Zero);
    }
References ReLogic.Localization.IME.WinImm32Ime._hImc, ReLogic.Localization.IME.WinImm32Ime._hWnd, ReLogic.Localization.IME.WinImm32.NativeMethods.ImmAssociateContext(), and System.IntPtr.Zero.
Referenced by ReLogic.Localization.IME.WinImm32Ime.WinImm32Ime(), ReLogic.Localization.IME.WinImm32Ime.OnDisable(), ReLogic.Localization.IME.WinImm32Ime.OnEnable(), and ReLogic.Localization.IME.WinImm32Ime.PreFilterMessage().