Terraria: ReLogic.Localization.IME.WinImm32Ime.PreFilterMessage
PreFilterMessage()
bool ReLogic.Localization.IME.WinImm32Ime.PreFilterMessage (ref Message message) inline
Implements ReLogic.OS.Windows.IMessageFilter.
Definition at line 162 of file WinImm32Ime.cs.
    {
        if (message.Msg == 8)
        {
            SetEnabled(bEnable: false);
            _isFocused = false;
            return true;
        }
        if (message.Msg == 7)
        {
            if (base.IsEnabled)
            {
                SetEnabled(bEnable: true);
            }
            _isFocused = true;
            return true;
        }
        if (message.Msg == 641)
        {
            message.LParam = IntPtr.Zero;
            return false;
        }
        if (!base.IsEnabled)
        {
            return false;
        }
        switch (message.Msg)
        {
        case 81:
            return true;
        case 269:
            _compString = "";
            return true;
        case 271:
            _compString = GetCompositionString();
            break;
        case 270:
            _compString = "";
            UpdateCandidateList();
            break;
        case 642:
        {
            int num = message.WParam.ToInt32();
            if ((uint)(num - 3) <= 2u)
            {
                UpdateCandidateList();
            }
            return true;
        }
        case 258:
            OnKeyPress((char)message.WParam.ToInt32());
            break;
        }
        return false;
    }
References ReLogic.Localization.IME.WinImm32Ime._compString, ReLogic.Localization.IME.WinImm32Ime._isFocused, ReLogic.Localization.IME.WinImm32Ime.GetCompositionString(), ReLogic.Localization.IME.PlatformIme.OnKeyPress(), ReLogic.Localization.IME.WinImm32Ime.SetEnabled(), ReLogic.Localization.IME.WinImm32Ime.UpdateCandidateList(), and System.IntPtr.Zero.