Terraria: ReLogic.Localization.IME.WinImm32Ime.UpdateCandidateList
UpdateCandidateList()
void ReLogic.Localization.IME.WinImm32Ime.UpdateCandidateList () inline private
Definition at line 100 of file WinImm32Ime.cs.
    {
        IntPtr hImc = ReLogic.Localization.IME.WinImm32.NativeMethods.ImmGetContext(_hWnd);
        try
        {
            int size = ReLogic.Localization.IME.WinImm32.NativeMethods.ImmGetCandidateList(hImc, 0u, ref MemoryMarshal.GetReference(Span<byte>.Empty), 0);
            if (size == 0)
            {
                _candList = Array.Empty<string>();
                _candPageSize = 0u;
                _candSelection = 0u;
                return;
            }
            Span<byte> buf = stackalloc byte[size];
            ReLogic.Localization.IME.WinImm32.NativeMethods.ImmGetCandidateList(hImc, 0u, ref MemoryMarshal.GetReference(buf), size);
            ref CandidateList candList = ref MemoryMarshal.AsRef<CandidateList>(buf);
            ReadOnlySpan<uint> offsets = MemoryMarshal.CreateReadOnlySpan(ref candList.dwOffset, (int)candList.dwCount);
            string[] candStrList = new string[candList.dwCount];
            int next = buf.Length;
            for (int i = (int)(candList.dwCount - 1); i >= 0; i--)
            {
                int start = (int)offsets[i];
                int num = i;
                Encoding unicode = Encoding.Unicode;
                Span<byte> span = buf;
                int num2 = start;
                candStrList[num] = unicode.GetString(span.Slice(num2, next - 2 - num2));
                next = start;
            }
            _candList = candStrList;
            _candPageSize = candList.dwPageSize;
            _candSelection = candList.dwSelection;
        }
        finally
        {
            ReLogic.Localization.IME.WinImm32.NativeMethods.ImmReleaseContext(_hWnd, hImc);
        }
    }
References ReLogic.Localization.IME.WinImm32Ime._candList, ReLogic.Localization.IME.WinImm32Ime._candPageSize, ReLogic.Localization.IME.WinImm32Ime._candSelection, ReLogic.Localization.IME.WinImm32Ime._hWnd, System.Span< T >.Empty, System.Text.Encoding.GetString(), ReLogic.Localization.IME.WinImm32.NativeMethods.ImmGetCandidateList(), ReLogic.Localization.IME.WinImm32.NativeMethods.ImmGetContext(), ReLogic.Localization.IME.WinImm32.NativeMethods.ImmReleaseContext(), System.Span< T >.Length, System.Span< T >.Slice(), System.start, and System.Text.Encoding.Unicode.
Referenced by ReLogic.Localization.IME.WinImm32Ime.PreFilterMessage().