Terraria: ReLogic.Localization.IME.WinImm32Ime.GetCompositionString
GetCompositionString()
string ReLogic.Localization.IME.WinImm32Ime.GetCompositionString () inline private
Definition at line 80 of file WinImm32Ime.cs.
    {
        IntPtr hImc = ReLogic.Localization.IME.WinImm32.NativeMethods.ImmGetContext(_hWnd);
        try
        {
            int size = ReLogic.Localization.IME.WinImm32.NativeMethods.ImmGetCompositionString(hImc, 8u, ref MemoryMarshal.GetReference(Span<byte>.Empty), 0);
            if (size == 0)
            {
                return "";
            }
            Span<byte> buf = stackalloc byte[size];
            ReLogic.Localization.IME.WinImm32.NativeMethods.ImmGetCompositionString(hImc, 8u, ref MemoryMarshal.GetReference(buf), size);
            return Encoding.Unicode.GetString(buf.ToArray());
        }
        finally
        {
            ReLogic.Localization.IME.WinImm32.NativeMethods.ImmReleaseContext(_hWnd, hImc);
        }
    }
References ReLogic.Localization.IME.WinImm32Ime._hWnd, System.Span< T >.Empty, ReLogic.Localization.IME.WinImm32.NativeMethods.ImmGetCompositionString(), ReLogic.Localization.IME.WinImm32.NativeMethods.ImmGetContext(), ReLogic.Localization.IME.WinImm32.NativeMethods.ImmReleaseContext(), System.Span< T >.ToArray(), and System.Text.Encoding.Unicode.
Referenced by ReLogic.Localization.IME.WinImm32Ime.PreFilterMessage().