Terraria: ReLogic.Localization.IME.WinImm32Ime.FinalizeString
FinalizeString()
void ReLogic.Localization.IME.WinImm32Ime.FinalizeString (bool bSend = false) inline private
    {
        IntPtr hImc = ReLogic.Localization.IME.WinImm32.NativeMethods.ImmGetContext(_hWnd);
        try
        {
            ReLogic.Localization.IME.WinImm32.NativeMethods.ImmNotifyIME(hImc, 21u, 4u, 0u);
            ReLogic.Localization.IME.WinImm32.NativeMethods.ImmSetCompositionString(hImc, 9u, "", 0, null, 0);
            ReLogic.Localization.IME.WinImm32.NativeMethods.ImmNotifyIME(hImc, 16u, 0u, 0u);
        }
        finally
        {
            ReLogic.Localization.IME.WinImm32.NativeMethods.ImmReleaseContext(_hWnd, hImc);
        }
    }
References ReLogic.Localization.IME.WinImm32Ime._hWnd, ReLogic.Localization.IME.WinImm32.NativeMethods.ImmGetContext(), ReLogic.Localization.IME.WinImm32.NativeMethods.ImmNotifyIME(), ReLogic.Localization.IME.WinImm32.NativeMethods.ImmReleaseContext(), and ReLogic.Localization.IME.WinImm32.NativeMethods.ImmSetCompositionString().
Referenced by ReLogic.Localization.IME.WinImm32Ime.OnDisable().