Terraria: UIResourcePackSelectionMenu.SetupGamepadPoints
SetupGamepadPoints()
void UIResourcePackSelectionMenu.SetupGamepadPoints (SpriteBatch spriteBatch) inline private
     {
         UILinkPointNavigator.Shortcuts.BackButtonCommand = 7;
         int num = 3000;
         int currentID = num;
         List<SnapPoint> snapPoints = GetSnapPoints();
         List<SnapPoint> snapPoints2 = _availablePacksList.GetSnapPoints();
         _helper.CullPointsOutOfElementArea(spriteBatch, snapPoints2, _availablePacksList);
         List<SnapPoint> snapPoints3 = _enabledPacksList.GetSnapPoints();
         _helper.CullPointsOutOfElementArea(spriteBatch, snapPoints3, _enabledPacksList);
         UILinkPoint[] verticalStripFromCategoryName = _helper.GetVerticalStripFromCategoryName(ref currentID, snapPoints2, "ToggleToOn");
         UILinkPoint[] verticalStripFromCategoryName2 = _helper.GetVerticalStripFromCategoryName(ref currentID, snapPoints2, "InfoOff");
         UILinkPoint[] verticalStripFromCategoryName3 = _helper.GetVerticalStripFromCategoryName(ref currentID, snapPoints3, "ToggleToOff");
         UILinkPoint[] verticalStripFromCategoryName4 = _helper.GetVerticalStripFromCategoryName(ref currentID, snapPoints3, "InfoOn");
         UILinkPoint[] verticalStripFromCategoryName5 = _helper.GetVerticalStripFromCategoryName(ref currentID, snapPoints3, "OrderUp");
         UILinkPoint[] verticalStripFromCategoryName6 = _helper.GetVerticalStripFromCategoryName(ref currentID, snapPoints3, "OrderDown");
         UILinkPoint uILinkPoint = null;
         UILinkPoint uILinkPoint2 = null;
         for (int i = 0; i < snapPoints.Count; i++)
         {
             SnapPoint snapPoint = snapPoints[i];
             string name = snapPoint.Name;
             if (!(name == "GoBack"))
             {
                 if (name == "OpenFolder")
                 {
                     uILinkPoint2 = _helper.MakeLinkPointFromSnapPoint(currentID++, snapPoint);
                 }
             }
             else
             {
                 uILinkPoint = _helper.MakeLinkPointFromSnapPoint(currentID++, snapPoint);
             }
         }
         _helper.LinkVerticalStrips(verticalStripFromCategoryName2, verticalStripFromCategoryName, 0);
         _helper.LinkVerticalStrips(verticalStripFromCategoryName, verticalStripFromCategoryName3, 0);
         _helper.LinkVerticalStrips(verticalStripFromCategoryName3, verticalStripFromCategoryName4, 0);
         _helper.LinkVerticalStrips(verticalStripFromCategoryName4, verticalStripFromCategoryName5, 0);
         _helper.LinkVerticalStrips(verticalStripFromCategoryName5, verticalStripFromCategoryName6, 0);
         _helper.LinkVerticalStripBottomSideToSingle(verticalStripFromCategoryName, uILinkPoint);
         _helper.LinkVerticalStripBottomSideToSingle(verticalStripFromCategoryName2, uILinkPoint);
         _helper.LinkVerticalStripBottomSideToSingle(verticalStripFromCategoryName5, uILinkPoint2);
         _helper.LinkVerticalStripBottomSideToSingle(verticalStripFromCategoryName6, uILinkPoint2);
         _helper.LinkVerticalStripBottomSideToSingle(verticalStripFromCategoryName3, uILinkPoint2);
         _helper.LinkVerticalStripBottomSideToSingle(verticalStripFromCategoryName4, uILinkPoint2);
         _helper.PairLeftRight(uILinkPoint, uILinkPoint2);
         _helper.MoveToVisuallyClosestPoint(num, currentID);
     }
References _availablePacksList, _enabledPacksList, _helper, UILinkPointNavigator.Shortcuts.BackButtonCommand, UIGamepadHelper.CullPointsOutOfElementArea(), UIList.GetSnapPoints(), UIElement.GetSnapPoints(), UIGamepadHelper.GetVerticalStripFromCategoryName(), UIGamepadHelper.LinkVerticalStripBottomSideToSingle(), UIGamepadHelper.LinkVerticalStrips(), UIGamepadHelper.MakeLinkPointFromSnapPoint(), UIGamepadHelper.MoveToVisuallyClosestPoint(), SnapPoint.Name, and UIGamepadHelper.PairLeftRight().
Referenced by Draw().