Terraria: UIResourcePackSelectionMenu.CreateOffsetButton
CreateOffsetButton()
UIElement UIResourcePackSelectionMenu.CreateOffsetButton (ResourcePack resourcePack, int offset) inline private
     {
         GroupOptionButton<bool> groupOptionButton = new GroupOptionButton<bool>(option: true, null, null, Color.White, null, 0.8f)
         {
             Left = StyleDimension.FromPercent(0.5f),
             Width = StyleDimension.FromPixelsAndPercent(0f, 0.5f),
             Height = StyleDimension.Fill
         };
         bool num = (offset == -1 && resourcePack.SortingOrder == 0) | (offset == 1 && resourcePack.SortingOrder == _packsList.EnabledPacks.Count() - 1);
         Color lightCyan = Color.LightCyan;
         groupOptionButton.SetColorsBasedOnSelectionState(lightCyan, lightCyan, 0.7f, 0.7f);
         groupOptionButton.ShowHighlightWhenSelected = false;
         groupOptionButton.SetPadding(0f);
         Asset<Texture2D> obj = Main.Assets.Request<Texture2D>("Images/UI/TexturePackButtons", (AssetRequestMode)1);
         UIImageFramed element = new UIImageFramed(obj, obj.Frame(2, 2, (offset == 1) ? 1 : 0))
         {
             HAlign = 0.5f,
             VAlign = 0.5f,
             IgnoresMouseInteraction = true
         };
         groupOptionButton.Append(element);
         groupOptionButton.OnMouseOver += delegate
         {
             SoundEngine.PlaySound(12);
         };
         int offsetLocalForLambda = offset;
         if (num)
         {
             groupOptionButton.OnLeftClick += delegate
             {
                 SoundEngine.PlaySound(12);
             };
         }
         else
         {
             groupOptionButton.OnLeftClick += delegate
             {
                 SoundEngine.PlaySound(12);
                 OffsetResourcePackPriority(resourcePack, offsetLocalForLambda);
                 PopulatePackList();
                 Main.instance.ResetAllContentBasedRenderTargets();
             };
         }
         if (offset == 1)
         {
             groupOptionButton.OnUpdate += OffsetFrontwardUpdate;
         }
         else
         {
             groupOptionButton.OnUpdate += OffsetBackwardUpdate;
         }
         return groupOptionButton;
     }
References _packsList, UIElement.Append(), Main.Assets, Color, ResourcePackList.EnabledPacks, StyleDimension.Fill, StyleDimension.FromPercent(), StyleDimension.FromPixelsAndPercent(), UIElement.HAlign, UIElement.Height, UIElement.IgnoresMouseInteraction, Main.instance, UIElement.Left, OffsetBackwardUpdate(), OffsetFrontwardUpdate(), OffsetResourcePackPriority(), UIElement.OnLeftClick, UIElement.OnMouseOver, UIElement.OnUpdate, SoundEngine.PlaySound(), PopulatePackList(), Main.ResetAllContentBasedRenderTargets(), GroupOptionButton< T >.SetColorsBasedOnSelectionState(), UIElement.SetPadding(), GroupOptionButton< T >.ShowHighlightWhenSelected, ResourcePack.SortingOrder, UIElement.VAlign, and UIElement.Width.
Referenced by PopulatePackList().