Terraria: UIResourcePackSelectionMenu.CreatePackInfoButton
CreatePackInfoButton()
UIElement UIResourcePackSelectionMenu.CreatePackInfoButton (ResourcePack resourcePack) inline private
     {
         UIResourcePackInfoButton<string> uIResourcePackInfoButton = new UIResourcePackInfoButton<string>("", 0.8f);
         uIResourcePackInfoButton.Width = StyleDimension.FromPixelsAndPercent(0f, 0.5f);
         uIResourcePackInfoButton.Height = StyleDimension.Fill;
         uIResourcePackInfoButton.ResourcePack = resourcePack;
         uIResourcePackInfoButton.SetPadding(0f);
         UIImage element = new UIImage(Main.Assets.Request<Texture2D>("Images/UI/CharCreation/CharInfo", (AssetRequestMode)1))
         {
             HAlign = 0.5f,
             VAlign = 0.5f,
             IgnoresMouseInteraction = true
         };
         uIResourcePackInfoButton.Append(element);
         uIResourcePackInfoButton.OnMouseOver += delegate
         {
             SoundEngine.PlaySound(12);
         };
         uIResourcePackInfoButton.OnLeftClick += Click_Info;
         return uIResourcePackInfoButton;
     }
References UIElement.Append(), Main.Assets, Click_Info(), StyleDimension.Fill, StyleDimension.FromPixelsAndPercent(), UIElement.HAlign, UIElement.Height, UIElement.IgnoresMouseInteraction, UIElement.OnLeftClick, UIElement.OnMouseOver, SoundEngine.PlaySound(), UIResourcePackInfoButton< T >.ResourcePack, UIElement.SetPadding(), UIElement.VAlign, and UIElement.Width.
Referenced by PopulatePackList().