Terraria: System.Xml.Schema.XmlValueConverter.ToString
ToString() [1/10]
string System.Xml.Schema.XmlValueConverter.ToString (bool value) abstract
Referenced by System.Xml.Schema.StringFacetsChecker.CheckValueFacets(), System.Xml.XsdValidatingReader.GetIsDefault(), System.Xml.Schema.XmlSchemaValidator.GetUnspecifiedDefaultAttributes(), System.Xml.Schema.XmlListConverter.ListAsString(), System.Xml.Schema.StringFacetsChecker.MatchEnumeration(), System.Xml.XsdValidatingReader.ProcessEndElementEvent(), System.Xml.XsdValidatingReader.ProcessEndElementEventAsync(), System.Xml.XsdValidatingReader.ReadAheadForMemberType(), System.Xml.XsdValidatingReader.ReadElementContentAsString(), and System.Xml.XPath.XPathNavigator.SetTypedValue().