Terraria: System.Xml.Schema.XmlValueConverter.ChangeType
ChangeType() [1/9]
object System.Xml.Schema.XmlValueConverter.ChangeType (bool value, Type destinationType) abstract
Referenced by System.Xml.Schema.XmlUnionConverter.ChangeType(), System.Xml.Schema.XmlSchemaDatatype.ChangeType(), System.Xml.Schema.XmlSchemaDatatype.ChangeType(), System.Xml.Schema.DurationFacetsChecker.CheckValueFacets(), System.Xml.Schema.QNameFacetsChecker.CheckValueFacets(), System.Xml.Schema.QNameFacetsChecker.MatchEnumeration(), System.Xml.XsdValidatingReader.ReadElementContentAs(), System.Xml.XsdValidatingReader.ReturnBoxedValue(), System.Xml.Schema.XmlListConverter.ToArray< T >(), System.Xml.Schema.XmlListConverter.ToList(), System.Xml.Schema.Datatype_List.TryParseValue(), System.Xml.Schema.DatatypeImplementation.TryParseValue(), System.Xml.Schema.Datatype_union.TryParseValue(), and System.Xml.XmlSqlBinaryReader.ValueAs().