Terraria: NPCFollowState.Update
Update()
void NPCFollowState.Update () inline
     {
         if (IsFollowingPlayer)
         {
             Player playerBeingFollowed = PlayerBeingFollowed;
             if (!playerBeingFollowed.active || playerBeingFollowed.dead)
             {
                 StopFollowing();
                 return;
             }
             UpdateBreadcrumbs(playerBeingFollowed);
             Dust.QuickDust(_floorBreadcrumb, Color.Red);
         }
     }
References _floorBreadcrumb, Entity.active, Color, Player.dead, IsFollowingPlayer, PlayerBeingFollowed, Dust.QuickDust(), StopFollowing(), and UpdateBreadcrumbs().