Terraria: Terraria.GameContent.ChromaHotkeyPainter.ReactiveRGBKey.Update
Update()
void Terraria.GameContent.ChromaHotkeyPainter.ReactiveRGBKey.Update () inline
Definition at line 41 of file ChromaHotkeyPainter.cs.
        {
            float amount = (float)Utils.GetLerpValue(_startTime.TotalSeconds, _expireTime.TotalSeconds, Main.gameTimeCache.TotalGameTime.TotalSeconds, clamped: true);
            _rgbKey.SetSolid(Color.Lerp(_color, Color.Black, amount));
        }
References Terraria.GameContent.ChromaHotkeyPainter.ReactiveRGBKey._color, Terraria.GameContent.ChromaHotkeyPainter.ReactiveRGBKey._expireTime, Terraria.GameContent.ChromaHotkeyPainter.ReactiveRGBKey._rgbKey, Terraria.GameContent.ChromaHotkeyPainter.ReactiveRGBKey._startTime, Microsoft.Xna.Framework.Color.Black, Terraria.Main.gameTimeCache, Terraria.Utils.GetLerpValue(), Microsoft.Xna.Framework.Color.Lerp(), ReLogic.Peripherals.RGB.RgbKey.SetSolid(), and System.TimeSpan.TotalSeconds.