Terraria: System.Net.Sockets.UdpClient.GetEndpoint
GetEndpoint()
IPEndPoint System.Net.Sockets.UdpClient.GetEndpoint (string hostname, int port) inline private
Definition at line 273 of file UdpClient.cs.
    {
        if (_active && (hostname != null || port != 0))
        {
            throw new InvalidOperationException(System.SR.net_udpconnected);
        }
        IPEndPoint result = null;
        if (hostname != null && port != 0)
        {
            IPAddress[] hostAddresses = Dns.GetHostAddresses(hostname);
            int i;
            for (i = 0; i < hostAddresses.Length && !IsAddressFamilyCompatible(hostAddresses[i].AddressFamily); i++)
            {
            }
            if (hostAddresses.Length == 0 || i == hostAddresses.Length)
            {
                throw new ArgumentException(System.SR.net_invalidAddressList, "hostname");
            }
            CheckForBroadcast(hostAddresses[i]);
            result = new IPEndPoint(hostAddresses[i], port);
        }
        return result;
    }
References System.Net.Sockets.UdpClient._active, System.Net.Sockets.UdpClient.CheckForBroadcast(), System.Net.Dns.GetHostAddresses(), System.Net.Sockets.UdpClient.IsAddressFamilyCompatible(), System.SR.net_invalidAddressList, and System.SR.net_udpconnected.
Referenced by System.Net.Sockets.UdpClient.BeginSend(), System.Net.Sockets.UdpClient.Send(), System.Net.Sockets.UdpClient.Send(), System.Net.Sockets.UdpClient.SendAsync(), and System.Net.Sockets.UdpClient.SendAsync().