Terraria: System.Net.Sockets.UdpClient.JoinMulticastGroup
JoinMulticastGroup() [2/4]
void System.Net.Sockets.UdpClient.JoinMulticastGroup (IPAddress multicastAddr) inline
Definition at line 319 of file UdpClient.cs.
    {
        ThrowIfDisposed();
        if (multicastAddr == null)
        {
            throw new ArgumentNullException("multicastAddr");
        }
        if (multicastAddr.AddressFamily != _family)
        {
            throw new ArgumentException(System.SR.Format(System.SR.net_protocol_invalid_multicast_family, "UDP"), "multicastAddr");
        }
        if (_family == AddressFamily.InterNetwork)
        {
            MulticastOption optionValue = new MulticastOption(multicastAddr);
            _clientSocket.SetSocketOption(SocketOptionLevel.IP, SocketOptionName.AddMembership, optionValue);
        }
        else
        {
            IPv6MulticastOption optionValue2 = new IPv6MulticastOption(multicastAddr);
            _clientSocket.SetSocketOption(SocketOptionLevel.IPv6, SocketOptionName.AddMembership, optionValue2);
        }
    }
References System.Net.Sockets.UdpClient._clientSocket, System.Net.Sockets.UdpClient._family, System.Net.IPAddress.AddressFamily, System.SR.Format(), System.SR.net_protocol_invalid_multicast_family, System.Net.Sockets.Socket.SetSocketOption(), and System.Net.Sockets.UdpClient.ThrowIfDisposed().
Referenced by System.Net.Sockets.UdpClient.JoinMulticastGroup().