Terraria: System.Net.Sockets.UdpClient.Dispose
Dispose() [2/2]
virtual void System.Net.Sockets.UdpClient.Dispose (bool disposing) inline protected virtual
Definition at line 183 of file UdpClient.cs.
    {
        if (!disposing)
        {
            return;
        }
        if (System.Net.NetEventSource.Log.IsEnabled())
        {
            System.Net.NetEventSource.Info(this, null, "Dispose");
        }
        if (!_disposed)
        {
            Socket clientSocket = _clientSocket;
            if (clientSocket != null)
            {
                clientSocket.InternalShutdown(SocketShutdown.Both);
                clientSocket.Dispose();
                _clientSocket = null;
            }
            _disposed = true;
            GC.SuppressFinalize(this);
        }
    }
References System.Net.Sockets.UdpClient._clientSocket, System.Net.Sockets.UdpClient._disposed, System.Net.Sockets.Socket.Dispose(), System.Net.NetEventSource.Info(), System.Net.Sockets.Socket.InternalShutdown(), System.Net.NetEventSource.Log, and System.GC.SuppressFinalize().