Terraria: System.Net.Sockets.UdpClient.JoinMulticastGroup
JoinMulticastGroup() [3/4]
void System.Net.Sockets.UdpClient.JoinMulticastGroup (IPAddress multicastAddr, int timeToLive) inline
Definition at line 372 of file UdpClient.cs.
    {
        ThrowIfDisposed();
        if (multicastAddr == null)
        {
            throw new ArgumentNullException("multicastAddr");
        }
        if (!RangeValidationHelpers.ValidateRange(timeToLive, 0, 255))
        {
            throw new ArgumentOutOfRangeException("timeToLive");
        }
        JoinMulticastGroup(multicastAddr);
        _clientSocket.SetSocketOption((_family != AddressFamily.InterNetwork) ? SocketOptionLevel.IPv6 : SocketOptionLevel.IP, SocketOptionName.MulticastTimeToLive, timeToLive);
    }
References System.Net.Sockets.UdpClient._clientSocket, System.Net.Sockets.UdpClient._family, System.Net.Sockets.UdpClient.JoinMulticastGroup(), System.Net.Sockets.Socket.SetSocketOption(), System.Net.Sockets.UdpClient.ThrowIfDisposed(), and System.Net.RangeValidationHelpers.ValidateRange().