Terraria: System.Net.Sockets.UdpClient.Connect
Connect() [3/3]
void System.Net.Sockets.UdpClient.Connect (string hostname, int port) inline
Definition at line 522 of file UdpClient.cs.
    {
        ThrowIfDisposed();
        if (hostname == null)
        {
            throw new ArgumentNullException("hostname");
        }
        if (!System.Net.TcpValidationHelpers.ValidatePortNumber(port))
        {
            throw new ArgumentOutOfRangeException("port");
        }
        IPAddress[] hostAddresses = Dns.GetHostAddresses(hostname);
        Exception ex = null;
        Socket socket = null;
        Socket socket2 = null;
        try
        {
            if (_clientSocket == null)
            {
                if (Socket.OSSupportsIPv4)
                {
                    socket2 = new Socket(AddressFamily.InterNetwork, SocketType.Dgram, ProtocolType.Udp);
                }
                if (Socket.OSSupportsIPv6)
                {
                    socket = new Socket(AddressFamily.InterNetworkV6, SocketType.Dgram, ProtocolType.Udp);
                }
            }
            IPAddress[] array = hostAddresses;
            foreach (IPAddress iPAddress in array)
            {
                try
                {
                    if (_clientSocket == null)
                    {
                        if (iPAddress.AddressFamily == AddressFamily.InterNetwork && socket2 != null)
{
                            socket2.Connect(iPAddress, port);
                            _clientSocket = socket2;
                            socket?.Close();
                        }
                        else if (socket != null)
{
                            socket.Connect(iPAddress, port);
                            _clientSocket = socket;
                            socket2?.Close();
                        }
                        _family = iPAddress.AddressFamily;
                        _active = true;
                        break;
                    }
                    if (IsAddressFamilyCompatible(iPAddress.AddressFamily))
                    {
                        Connect(new IPEndPoint(iPAddress, port));
                        _active = true;
                        break;
                    }
                }
                catch (Exception ex2)
                {
                    if (ExceptionCheck.IsFatal(ex2))
                    {
                        throw;
                    }
                    ex = ex2;
                }
            }
        }
        catch (Exception ex3)
        {
            if (ExceptionCheck.IsFatal(ex3))
            {
                throw;
            }
            ex = ex3;
        }
        finally
        {
            if (!_active)
            {
                socket?.Close();
                socket2?.Close();
                if (ex != null)
                {
                    throw ex;
                }
                throw new SocketException(10057);
            }
        }
    }
References System.Net.Sockets.UdpClient._active, System.Net.Sockets.UdpClient._clientSocket, System.Net.Sockets.UdpClient._family, System.Net.IPAddress.AddressFamily, System.array, System.Net.Sockets.Socket.Close(), System.Net.Sockets.Socket.Connect(), System.Net.Sockets.Connect, System.Net.Dns.GetHostAddresses(), System.Net.Sockets.UdpClient.IsAddressFamilyCompatible(), System.Net.ExceptionCheck.IsFatal(), System.Net.Sockets.Socket.OSSupportsIPv4, System.Net.Sockets.Socket.OSSupportsIPv6, System.Net.Sockets.Socket, System.Net.Sockets.UdpClient.ThrowIfDisposed(), and System.Net.TcpValidationHelpers.ValidatePortNumber().