Terraria: System.Net.Sockets.UdpClient.ThrowIfDisposed
ThrowIfDisposed()
void System.Net.Sockets.UdpClient.ThrowIfDisposed () inline private
Definition at line 723 of file UdpClient.cs.
    {
        if (_disposed)
        {
            ThrowObjectDisposedException();
        }
        void ThrowObjectDisposedException()
        {
            throw new ObjectDisposedException(GetType().FullName);
        }
    }
References System.Net.Sockets.UdpClient._disposed, and System.FullName.
Referenced by System.Net.Sockets.UdpClient.BeginReceive(), System.Net.Sockets.UdpClient.Connect(), System.Net.Sockets.UdpClient.Connect(), System.Net.Sockets.UdpClient.Connect(), System.Net.Sockets.UdpClient.DropMulticastGroup(), System.Net.Sockets.UdpClient.DropMulticastGroup(), System.Net.Sockets.UdpClient.EndReceive(), System.Net.Sockets.UdpClient.EndSend(), System.Net.Sockets.UdpClient.JoinMulticastGroup(), System.Net.Sockets.UdpClient.JoinMulticastGroup(), System.Net.Sockets.UdpClient.JoinMulticastGroup(), System.Net.Sockets.UdpClient.JoinMulticastGroup(), System.Net.Sockets.UdpClient.Receive(), System.Net.Sockets.UdpClient.ReceiveAsync(), System.Net.Sockets.UdpClient.ReceiveAsync(), System.Net.Sockets.UdpClient.Send(), System.Net.Sockets.UdpClient.Send(), System.Net.Sockets.UdpClient.Send(), System.Net.Sockets.UdpClient.Send(), System.Net.Sockets.UdpClient.SendAsync(), and System.Net.Sockets.UdpClient.ValidateDatagram().