Terraria: System.Net.Sockets.UdpClient.CheckForBroadcast
CheckForBroadcast()
void System.Net.Sockets.UdpClient.CheckForBroadcast (IPAddress ipAddress) inline private
Definition at line 207 of file UdpClient.cs.
    {
        if (_clientSocket != null && !_isBroadcast && IsBroadcast(ipAddress))
        {
            _isBroadcast = true;
            _clientSocket.SetSocketOption(SocketOptionLevel.Socket, SocketOptionName.Broadcast, 1);
        }
    }
References System.Net.Sockets.UdpClient._clientSocket, System.Net.Sockets.UdpClient._isBroadcast, System.Net.Sockets.UdpClient.IsBroadcast(), and System.Net.Sockets.Socket.SetSocketOption().
Referenced by System.Net.Sockets.UdpClient.BeginSend(), System.Net.Sockets.UdpClient.Connect(), System.Net.Sockets.UdpClient.GetEndpoint(), System.Net.Sockets.UdpClient.Send(), System.Net.Sockets.UdpClient.Send(), System.Net.Sockets.UdpClient.SendAsync(), and System.Net.Sockets.UdpClient.SendAsync().