Terraria: System.Text.Json.JsonSerializer.ReadCore< TValue >
ReadCore< TValue >() [1/2]
static TValue System.Text.Json.JsonSerializer.ReadCore< TValue > (JsonConverter jsonConverter, ref Utf8JsonReader reader, JsonSerializerOptions options, ref ReadStack state) inline static private
Definition at line 763 of file JsonSerializer.cs.
    {
        if (jsonConverter is JsonConverter<TValue> jsonConverter2)
        {
            return jsonConverter2.ReadCore(ref reader, options, ref state);
        }
        object obj = jsonConverter.ReadCoreAsObject(ref reader, options, ref state);
        return (TValue)obj;
    }
References System.obj, System.options, and System.state.
Referenced by System.Text.Json.JsonSerializer.ContinueDeserialize< TValue >(), System.Text.Json.JsonSerializer.Read< TValue >(), and System.Text.Json.JsonSerializer.ReadCore< TValue >().