Terraria: System.Text.Json.JsonSerializer.ContinueDeserialize< TValue >
ContinueDeserialize< TValue >()
static TValue System.Text.Json.JsonSerializer.ContinueDeserialize< TValue > (ref ReadBufferState bufferState, ref JsonReaderState jsonReaderState, ref ReadStack readStack, JsonConverter converter, JsonSerializerOptions options) inline static package
Definition at line 1076 of file JsonSerializer.cs.
    {
        if (bufferState.BytesInBuffer > bufferState.ClearMax)
        {
            bufferState.ClearMax = bufferState.BytesInBuffer;
        }
        int num = 0;
        if (bufferState.IsFirstIteration)
        {
            bufferState.IsFirstIteration = false;
            if (bufferState.Buffer.AsSpan().StartsWith(JsonConstants.Utf8Bom))
            {
                num += JsonConstants.Utf8Bom.Length;
                bufferState.BytesInBuffer -= JsonConstants.Utf8Bom.Length;
            }
        }
        TValue result = ReadCore<TValue>(ref jsonReaderState, bufferState.IsFinalBlock, new ReadOnlySpan<byte>(bufferState.Buffer, num, bufferState.BytesInBuffer), options, ref readStack, converter);
        int num2 = checked((int)readStack.BytesConsumed);
        bufferState.BytesInBuffer -= num2;
        if (!bufferState.IsFinalBlock)
        {
            if ((uint)bufferState.BytesInBuffer > (uint)bufferState.Buffer.Length / 2u)
            {
                byte[] buffer = bufferState.Buffer;
                int clearMax = bufferState.ClearMax;
                byte[] array = ArrayPool<byte>.Shared.Rent((bufferState.Buffer.Length < 1073741823) ? (bufferState.Buffer.Length * 2) : int.MaxValue);
                Buffer.BlockCopy(buffer, num2 + num, array, 0, bufferState.BytesInBuffer);
                bufferState.Buffer = array;
                bufferState.ClearMax = bufferState.BytesInBuffer;
                new Span<byte>(buffer, 0, clearMax).Clear();
                ArrayPool<byte>.Shared.Return(buffer);
            }
            else if (bufferState.BytesInBuffer != 0)
            {
                Buffer.BlockCopy(bufferState.Buffer, num2 + num, bufferState.Buffer, 0, bufferState.BytesInBuffer);
            }
        }
        return result;
    }
References System.array, System.Buffer.BlockCopy(), System.buffer, System.Collections.Generic.Dictionary< TKey, TValue >.Clear(), System.converter, System.Text.Json.Dictionary, System.options, System.Text.Json.JsonSerializer.ReadCore< TValue >(), and System.Text.Json.JsonConstants.Utf8Bom.
Referenced by System.Text.Json.JsonSerializer.ReadAll< TValue >(), and System.Text.Json.JsonSerializer.ReadAllAsync< TValue >().