Terraria: System.Text.Json.JsonSerializer.GetPropertyName
GetPropertyName()
static ReadOnlySpan< byte > System.Text.Json.JsonSerializer.GetPropertyName (ref ReadStack state, ref Utf8JsonReader reader, JsonSerializerOptions options) inline static package
Definition at line 718 of file JsonSerializer.cs.
    {
        ReadOnlySpan<byte> span = reader.GetSpan();
        ReadOnlySpan<byte> result;
        if (reader._stringHasEscaping)
        {
            int idx = span.IndexOf<byte>(92);
            result = JsonReaderHelper.GetUnescapedSpan(span, idx);
        }
        else
        {
            result = span;
        }
        if (options.ReferenceHandlingStrategy == ReferenceHandlingStrategy.Preserve && span.Length > 0 && span[0] == 36)
        {
            ThrowHelper.ThrowUnexpectedMetadataException(span, ref reader, ref state);
        }
        return result;
    }
References System.Text.Json.Dictionary, System.Text.Json.JsonReaderHelper.GetUnescapedSpan(), System.options, System.state, and System.Text.Json.ThrowHelper.ThrowUnexpectedMetadataException().
Referenced by System.Text.Json.Serialization.Converters.ObjectDefaultConverter< T >.OnTryRead(), System.Text.Json.Serialization.Converters.ObjectWithParameterizedConstructorConverter< T >.ReadConstructorArguments(), System.Text.Json.Serialization.Converters.ObjectWithParameterizedConstructorConverter< T >.ReadConstructorArgumentsWithContinuation(), and System.Text.Json.Serialization.Converters.ObjectWithParameterizedConstructorConverter< T >.TryLookupConstructorParameter().