Terraria: System.Text.Json.JsonSerializer.GetRuntimeTypeAndValidateInputType
GetRuntimeTypeAndValidateInputType()
static Type System.Text.Json.JsonSerializer.GetRuntimeTypeAndValidateInputType (object value, Type inputType) inline static private
Definition at line 1625 of file JsonSerializer.cs.
    {
        if ((object)inputType == null)
        {
            throw new ArgumentNullException("inputType");
        }
        if (value != null)
        {
            Type type = value.GetType();
            if (!inputType.IsAssignableFrom(type))
            {
                ThrowHelper.ThrowArgumentException_DeserializeWrongType(inputType, value);
            }
            if (inputType == JsonTypeInfo.ObjectType)
            {
                return type;
            }
        }
        return inputType;
    }
References System.Text.Json.Dictionary, System.Type.GetType(), System.Text.Json.Serialization.Metadata.JsonTypeInfo< T >.ObjectType, System.Text.Json.ThrowHelper.ThrowArgumentException_DeserializeWrongType(), System.type, and System.value.
Referenced by System.Text.Json.JsonSerializer.Serialize(), System.Text.Json.JsonSerializer.Serialize(), System.Text.Json.JsonSerializer.Serialize(), System.Text.Json.JsonSerializer.Serialize(), System.Text.Json.JsonSerializer.Serialize(), System.Text.Json.JsonSerializer.Serialize(), System.Text.Json.JsonSerializer.SerializeAsync(), System.Text.Json.JsonSerializer.SerializeAsync(), System.Text.Json.JsonSerializer.SerializeToDocument(), System.Text.Json.JsonSerializer.SerializeToDocument(), System.Text.Json.JsonSerializer.SerializeToElement(), System.Text.Json.JsonSerializer.SerializeToElement(), System.Text.Json.JsonSerializer.SerializeToNode(), System.Text.Json.JsonSerializer.SerializeToNode(), System.Text.Json.JsonSerializer.SerializeToUtf8Bytes(), and System.Text.Json.JsonSerializer.SerializeToUtf8Bytes().