Terraria: System.Text.Json.JsonSerializer.ReadAll< TValue >
ReadAll< TValue >()
static TValue System.Text.Json.JsonSerializer.ReadAll< TValue > (Stream utf8Json, JsonTypeInfo jsonTypeInfo) inline static package
Definition at line 1019 of file JsonSerializer.cs.
    {
        JsonSerializerOptions options = jsonTypeInfo.Options;
        ReadBufferState bufferState = new ReadBufferState(options.DefaultBufferSize);
        ReadStack readStack = default(ReadStack);
        readStack.Initialize(jsonTypeInfo, supportContinuation: true);
        JsonConverter converterBase = readStack.Current.JsonPropertyInfo.ConverterBase;
        JsonReaderState jsonReaderState = new JsonReaderState(options.GetReaderOptions());
        try
        {
            TValue result;
            do
            {
                bufferState = ReadFromStream(utf8Json, bufferState);
                result = ContinueDeserialize<TValue>(ref bufferState, ref jsonReaderState, ref readStack, converterBase, options);
            }
            while (!bufferState.IsFinalBlock);
            return result;
        }
        finally
        {
            bufferState.Dispose();
        }
    }
References System.Text.Json.JsonSerializer.ContinueDeserialize< TValue >(), System.Collections.Generic.Dictionary< TKey, TValue >.Initialize(), System.options, and System.Text.Json.JsonSerializer.ReadFromStream().
Referenced by System.Text.Json.JsonSerializer.Deserialize< TValue >(), and System.Text.Json.JsonSerializer.ReadAllUsingOptions< TValue >().