Terraria: System.Text.Json.JsonSerializer.ResolveMetadataForJsonArray< T >
ResolveMetadataForJsonArray< T >()
static bool System.Text.Json.JsonSerializer.ResolveMetadataForJsonArray< T > (ref Utf8JsonReader reader, ref ReadStack state, JsonSerializerOptions options) inline static package
Definition at line 489 of file JsonSerializer.cs.
    {
        JsonConverter converterBase = state.Current.JsonTypeInfo.PropertyInfoForTypeInfo.ConverterBase;
        if ((int)state.Current.ObjectState < 2 && !TryReadAheadMetadataAndSetState(ref reader, ref state, StackFrameObjectState.ReadNameOrEndObject))
        {
            return false;
        }
        if (state.Current.ObjectState == StackFrameObjectState.ReadNameOrEndObject)
        {
            if (reader.TokenType != JsonTokenType.PropertyName)
            {
                ThrowHelper.ThrowJsonException_MetadataPreservedArrayValuesNotFound(ref state, converterBase.TypeToConvert);
            }
            ReadOnlySpan<byte> span = reader.GetSpan();
            switch (GetMetadataPropertyName(span))
            {
            case MetadataPropertyName.Id:
                state.Current.JsonPropertyName = s_idPropertyName;
                if (!converterBase.CanHaveIdMetadata)
                {
                    ThrowHelper.ThrowJsonException_MetadataCannotParsePreservedObjectIntoImmutable(converterBase.TypeToConvert);
                }
                state.Current.ObjectState = StackFrameObjectState.ReadAheadIdValue;
                break;
            case MetadataPropertyName.Ref:
                state.Current.JsonPropertyName = s_refPropertyName;
                if (converterBase.IsValueType)
                {
                    ThrowHelper.ThrowJsonException_MetadataInvalidReferenceToValueType(converterBase.TypeToConvert);
                }
                state.Current.ObjectState = StackFrameObjectState.ReadAheadRefValue;
                break;
            case MetadataPropertyName.Values:
                ThrowHelper.ThrowJsonException_MetadataMissingIdBeforeValues(ref state, span);
                break;
            default:
                ThrowHelper.ThrowJsonException_MetadataPreservedArrayInvalidProperty(ref state, converterBase.TypeToConvert, in reader);
                break;
            }
        }
        if (state.Current.ObjectState == StackFrameObjectState.ReadAheadRefValue)
        {
            if (!TryReadAheadMetadataAndSetState(ref reader, ref state, StackFrameObjectState.ReadRefValue))
            {
                return false;
            }
        }
        else if (state.Current.ObjectState == StackFrameObjectState.ReadAheadIdValue && !TryReadAheadMetadataAndSetState(ref reader, ref state, StackFrameObjectState.ReadIdValue))
        {
            return false;
        }
        if (state.Current.ObjectState == StackFrameObjectState.ReadRefValue)
        {
            if (reader.TokenType != JsonTokenType.String)
            {
                ThrowHelper.ThrowJsonException_MetadataValueWasNotString(reader.TokenType);
            }
            string @string = reader.GetString();
            object obj = state.ReferenceResolver.ResolveReference(@string);
            ValidateValueIsCorrectType<T>(obj, @string);
            state.Current.ReturnValue = obj;
            state.Current.ObjectState = StackFrameObjectState.ReadAheadRefEndObject;
        }
        else if (state.Current.ObjectState == StackFrameObjectState.ReadIdValue)
        {
            if (reader.TokenType != JsonTokenType.String)
            {
                ThrowHelper.ThrowJsonException_MetadataValueWasNotString(reader.TokenType);
            }
            converterBase.CreateInstanceForReferenceResolver(ref reader, ref state, options);
            string string2 = reader.GetString();
            state.ReferenceResolver.AddReference(string2, state.Current.ReturnValue);
            state.Current.ObjectState = StackFrameObjectState.ReadAheadValuesName;
        }
        state.Current.JsonPropertyName = null;
        if (state.Current.ObjectState == StackFrameObjectState.ReadAheadRefEndObject && !TryReadAheadMetadataAndSetState(ref reader, ref state, StackFrameObjectState.ReadRefEndObject))
        {
            return false;
        }
        if (state.Current.ObjectState == StackFrameObjectState.ReadRefEndObject)
        {
            if (reader.TokenType != JsonTokenType.EndObject)
            {
                ThrowHelper.ThrowJsonException_MetadataReferenceObjectCannotContainOtherProperties(reader.GetSpan(), ref state);
            }
            return true;
        }
        if (state.Current.ObjectState == StackFrameObjectState.ReadAheadValuesName && !TryReadAheadMetadataAndSetState(ref reader, ref state, StackFrameObjectState.ReadValuesName))
        {
            return false;
        }
        if (state.Current.ObjectState == StackFrameObjectState.ReadValuesName)
        {
            if (reader.TokenType != JsonTokenType.PropertyName)
            {
                ThrowHelper.ThrowJsonException_MetadataPreservedArrayValuesNotFound(ref state, converterBase.TypeToConvert);
            }
            ReadOnlySpan<byte> span2 = reader.GetSpan();
            if (GetMetadataPropertyName(span2) != MetadataPropertyName.Values)
            {
                ThrowHelper.ThrowJsonException_MetadataPreservedArrayInvalidProperty(ref state, converterBase.TypeToConvert, in reader);
            }
            state.Current.JsonPropertyName = s_valuesPropertyName;
            state.Current.ObjectState = StackFrameObjectState.ReadAheadValuesStartArray;
        }
        if (state.Current.ObjectState == StackFrameObjectState.ReadAheadValuesStartArray && !TryReadAheadMetadataAndSetState(ref reader, ref state, StackFrameObjectState.ReadValuesStartArray))
        {
            return false;
        }
        if (state.Current.ObjectState == StackFrameObjectState.ReadValuesStartArray)
        {
            if (reader.TokenType != JsonTokenType.StartArray)
            {
                ThrowHelper.ThrowJsonException_MetadataValuesInvalidToken(reader.TokenType);
            }
            state.Current.ValidateEndTokenOnArray = true;
            state.Current.ObjectState = StackFrameObjectState.CreatedObject;
        }
        return true;
    }
References System.Text.Json.Dictionary, System.Text.Json.JsonSerializer.GetMetadataPropertyName(), System.obj, System.options, System.Text.Json.JsonSerializer.s_idPropertyName, System.Text.Json.JsonSerializer.s_refPropertyName, System.Text.Json.JsonSerializer.s_valuesPropertyName, System.state, System.Text.Json.ThrowHelper.ThrowJsonException_MetadataCannotParsePreservedObjectIntoImmutable(), System.Text.Json.ThrowHelper.ThrowJsonException_MetadataInvalidReferenceToValueType(), System.Text.Json.ThrowHelper.ThrowJsonException_MetadataMissingIdBeforeValues(), System.Text.Json.ThrowHelper.ThrowJsonException_MetadataPreservedArrayInvalidProperty(), System.Text.Json.ThrowHelper.ThrowJsonException_MetadataPreservedArrayValuesNotFound(), System.Text.Json.ThrowHelper.ThrowJsonException_MetadataReferenceObjectCannotContainOtherProperties(), System.Text.Json.ThrowHelper.ThrowJsonException_MetadataValuesInvalidToken(), System.Text.Json.ThrowHelper.ThrowJsonException_MetadataValueWasNotString(), System.Text.Json.JsonSerializer.TryReadAheadMetadataAndSetState(), and System.Text.Json.JsonSerializer.ValidateValueIsCorrectType< T >().