Terraria: System.Text.Json.JsonSerializer.GetTypeInfo
GetTypeInfo() [2/2]
static JsonTypeInfo System.Text.Json.JsonSerializer.GetTypeInfo (JsonSerializerOptions options, Type runtimeType) inline static private
Definition at line 372 of file JsonSerializer.cs.
    {
        if (options == null)
        {
            options = JsonSerializerOptions.s_defaultOptions;
        }
        if (!options.IsInitializedForReflectionSerializer)
        {
            options.InitializeForReflectionSerializer();
        }
        return options.GetOrAddClassForRootType(runtimeType);
    }
References System.options, and System.Text.Json.JsonSerializerOptions.s_defaultOptions.
Referenced by System.Text.Json.JsonSerializer.Deserialize(), System.Text.Json.JsonSerializer.Deserialize(), System.Text.Json.JsonSerializer.Deserialize(), System.Text.Json.JsonSerializer.Deserialize(), System.Text.Json.JsonSerializer.Deserialize(), System.Text.Json.JsonSerializer.Deserialize(), System.Text.Json.JsonSerializer.Deserialize(), System.Text.Json.JsonSerializer.Deserialize(), System.Text.Json.JsonSerializer.Deserialize(), System.Text.Json.JsonSerializer.Deserialize(), System.Text.Json.JsonSerializer.Deserialize(), System.Text.Json.JsonSerializer.Deserialize(), System.Text.Json.JsonSerializer.Deserialize(), System.Text.Json.JsonSerializer.Deserialize(), System.Text.Json.JsonSerializer.Deserialize(), System.Text.Json.JsonSerializer.Deserialize< TValue >(), System.Text.Json.JsonSerializer.Deserialize< TValue >(), System.Text.Json.JsonSerializer.Deserialize< TValue >(), System.Text.Json.JsonSerializer.Deserialize< TValue >(), System.Text.Json.JsonSerializer.Deserialize< TValue >(), System.Text.Json.JsonSerializer.Deserialize< TValue >(), System.Text.Json.JsonSerializer.Deserialize< TValue >(), System.Text.Json.JsonSerializer.DeserializeAsync(), System.Text.Json.JsonSerializer.DeserializeAsync(), System.Text.Json.JsonSerializer.DeserializeAsync< TValue >(), System.Text.Json.JsonSerializer.ReadAllUsingOptions< TValue >(), System.Text.Json.JsonSerializer.Serialize(), System.Text.Json.JsonSerializer.Serialize(), System.Text.Json.JsonSerializer.Serialize(), System.Text.Json.JsonSerializer.Serialize(), System.Text.Json.JsonSerializer.Serialize(), System.Text.Json.JsonSerializer.Serialize(), System.Text.Json.JsonSerializer.Serialize< TValue >(), System.Text.Json.JsonSerializer.Serialize< TValue >(), System.Text.Json.JsonSerializer.Serialize< TValue >(), System.Text.Json.JsonSerializer.SerializeAsync(), System.Text.Json.JsonSerializer.SerializeAsync(), System.Text.Json.JsonSerializer.SerializeAsync< TValue >(), System.Text.Json.JsonSerializer.SerializeToDocument(), System.Text.Json.JsonSerializer.SerializeToDocument(), System.Text.Json.JsonSerializer.SerializeToDocument< TValue >(), System.Text.Json.JsonSerializer.SerializeToElement(), System.Text.Json.JsonSerializer.SerializeToElement(), System.Text.Json.JsonSerializer.SerializeToElement< TValue >(), System.Text.Json.JsonSerializer.SerializeToNode(), System.Text.Json.JsonSerializer.SerializeToNode(), System.Text.Json.JsonSerializer.SerializeToNode< TValue >(), System.Text.Json.JsonSerializer.SerializeToUtf8Bytes(), System.Text.Json.JsonSerializer.SerializeToUtf8Bytes(), and System.Text.Json.JsonSerializer.SerializeToUtf8Bytes< TValue >().