Terraria: System.Text.Json.JsonSerializer.LookupProperty
LookupProperty()
static JsonPropertyInfo System.Text.Json.JsonSerializer.LookupProperty (object obj, ReadOnlySpan< byte > unescapedPropertyName, ref ReadStack state, JsonSerializerOptions options, out bool useExtensionProperty, bool createExtensionProperty = true) inline static package
Definition at line 691 of file JsonSerializer.cs.
    {
        useExtensionProperty = false;
        byte[] utf8PropertyName;
        JsonPropertyInfo jsonPropertyInfo = state.Current.JsonTypeInfo.GetProperty(unescapedPropertyName, ref state.Current, out utf8PropertyName);
        state.Current.PropertyIndex++;
        state.Current.JsonPropertyName = utf8PropertyName;
        if (jsonPropertyInfo == JsonPropertyInfo.s_missingProperty)
        {
            JsonPropertyInfo dataExtensionProperty = state.Current.JsonTypeInfo.DataExtensionProperty;
            if (dataExtensionProperty != null && dataExtensionProperty.HasGetter && dataExtensionProperty.HasSetter)
            {
                state.Current.JsonPropertyNameAsString = JsonHelpers.Utf8GetString(unescapedPropertyName);
                if (createExtensionProperty)
                {
                    CreateDataExtensionProperty(obj, dataExtensionProperty, options);
                }
                jsonPropertyInfo = dataExtensionProperty;
                useExtensionProperty = true;
            }
        }
        state.Current.JsonPropertyInfo = jsonPropertyInfo;
        state.Current.NumberHandling = jsonPropertyInfo.NumberHandling;
        return jsonPropertyInfo;
    }
References System.Text.Json.JsonSerializer.CreateDataExtensionProperty(), System.Text.Json.Dictionary, System.obj, System.options, System.Text.Json.Serialization.Metadata.JsonPropertyInfo< T >.s_missingProperty, System.state, and System.Text.Json.JsonHelpers.Utf8GetString().
Referenced by System.Text.Json.Serialization.Converters.ObjectDefaultConverter< T >.OnTryRead(), System.Text.Json.Serialization.Converters.ObjectWithParameterizedConstructorConverter< T >.ReadConstructorArguments(), and System.Text.Json.Serialization.Converters.ObjectWithParameterizedConstructorConverter< T >.ReadConstructorArgumentsWithContinuation().