Terraria: System.Text.Json.JsonSerializer.CreateDataExtensionProperty
CreateDataExtensionProperty()
static void System.Text.Json.JsonSerializer.CreateDataExtensionProperty (object obj, JsonPropertyInfo jsonPropertyInfo, JsonSerializerOptions options) inline static package
Definition at line 738 of file JsonSerializer.cs.
    {
        object obj2 = jsonPropertyInfo.GetValueAsObject(obj);
        if (obj2 != null)
        {
            return;
        }
        if (jsonPropertyInfo.RuntimeTypeInfo.CreateObject == null)
        {
            if (jsonPropertyInfo.DeclaredPropertyType.FullName == "System.Text.Json.Nodes.JsonObject")
            {
                obj2 = jsonPropertyInfo.ConverterBase.CreateObject(options);
            }
            else
            {
                ThrowHelper.ThrowNotSupportedException_SerializationNotSupported(jsonPropertyInfo.DeclaredPropertyType);
            }
        }
        else
        {
            obj2 = jsonPropertyInfo.RuntimeTypeInfo.CreateObject();
        }
        jsonPropertyInfo.SetExtensionDictionaryAsObject(obj, obj2);
    }
References System.obj, System.options, and System.Text.Json.ThrowHelper.ThrowNotSupportedException_SerializationNotSupported().
Referenced by System.Text.Json.JsonSerializer.LookupProperty(), and System.Text.Json.Serialization.Converters.ObjectWithParameterizedConstructorConverter< T >.OnTryRead().