Terraria: System.Text.Json.JsonSerializer.ReadNode< TValue >
ReadNode< TValue >()
static TValue System.Text.Json.JsonSerializer.ReadNode< TValue > (JsonNode node, JsonTypeInfo jsonTypeInfo) inline static private
Definition at line 180 of file JsonSerializer.cs.
    {
        JsonSerializerOptions options = jsonTypeInfo.Options;
        using PooledByteBufferWriter pooledByteBufferWriter = new PooledByteBufferWriter(options.DefaultBufferSize);
        using (Utf8JsonWriter utf8JsonWriter = new Utf8JsonWriter(pooledByteBufferWriter, options.GetWriterOptions()))
        {
            if (node == null)
            {
                utf8JsonWriter.WriteNullValue();
            }
            else
            {
                node.WriteTo(utf8JsonWriter, options);
            }
        }
        return ReadFromSpan<TValue>(pooledByteBufferWriter.WrittenMemory.Span, jsonTypeInfo);
    }
References System.options, and System.Text.Json.JsonSerializer.ReadFromSpan< TValue >().
Referenced by System.Text.Json.JsonSerializer.Deserialize< TValue >(), and System.Text.Json.JsonSerializer.Deserialize< TValue >().