Terraria: System.Text.Json.JsonSerializer.ReadFromSpan< TValue >
ReadFromSpan< TValue >() [2/2]
static TValue System.Text.Json.JsonSerializer.ReadFromSpan< TValue > (ReadOnlySpan< char > json, JsonTypeInfo jsonTypeInfo) inline static private
Definition at line 1235 of file JsonSerializer.cs.
    {
        byte[] array = null;
        Span<byte> span = (((long)json.Length > 349525L) ? new byte[JsonReaderHelper.GetUtf8ByteCount(json)] : (array = ArrayPool<byte>.Shared.Rent(json.Length * 3)));
        try
        {
            int utf8FromText = JsonReaderHelper.GetUtf8FromText(json, span);
            span = span.Slice(0, utf8FromText);
            return ReadFromSpan<TValue>(span, jsonTypeInfo, utf8FromText);
        }
        finally
        {
            if (array != null)
            {
                span.Clear();
                ArrayPool<byte>.Shared.Return(array);
            }
        }
    }
References System.array, System.Collections.Generic.Dictionary< TKey, TValue >.Clear(), System.Text.Json.JsonReaderHelper.GetUtf8ByteCount(), System.Text.Json.JsonReaderHelper.GetUtf8FromText(), System.L, and System.Text.Json.JsonSerializer.ReadFromSpan< TValue >().