Terraria: System.Text.Json.JsonSerializer.DeserializeAsyncEnumerable< TValue >
DeserializeAsyncEnumerable< TValue >()
static IAsyncEnumerable< TValue?> System.Text.Json.JsonSerializer.DeserializeAsyncEnumerable< TValue > (Stream utf8Json, JsonSerializerOptions? options = null, CancellationToken cancellationToken = default(CancellationToken)) inline static
Definition at line 940 of file JsonSerializer.cs.
    {
        if (utf8Json == null)
        {
            throw new ArgumentNullException("utf8Json");
        }
        if (options == null)
        {
            options = JsonSerializerOptions.s_defaultOptions;
        }
        if (!options.IsInitializedForReflectionSerializer)
        {
            options.InitializeForReflectionSerializer();
        }
        return CreateAsyncEnumerableDeserializer(utf8Json, options, cancellationToken);
        [RequiresUnreferencedCode("JSON serialization and deserialization might require types that cannot be statically analyzed. Use the overload that takes a JsonTypeInfo or JsonSerializerContext, or make sure all of the required types are preserved.")]
        static async IAsyncEnumerable<TValue> CreateAsyncEnumerableDeserializer(Stream utf8Json, JsonSerializerOptions options, [EnumeratorCancellation] CancellationToken cancellationToken)
        {
            ReadBufferState bufferState = new ReadBufferState(options.DefaultBufferSize);
            JsonConverter converter = QueueOfTConverter<Queue<TValue>, TValue>.Instance;
            JsonTypeInfo jsonTypeInfo = CreateQueueJsonTypeInfo<TValue>(converter, options);
            ReadStack readStack = default(ReadStack);
            readStack.Initialize(jsonTypeInfo, supportContinuation: true);
            JsonReaderState jsonReaderState = new JsonReaderState(options.GetReaderOptions());
            try
            {
                do
                {
                    bufferState = await ReadFromStreamAsync(utf8Json, bufferState, cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
                    ContinueDeserialize<Queue<TValue>>(ref bufferState, ref jsonReaderState, ref readStack, converter, options);
                    object returnValue = readStack.Current.ReturnValue;
                    if (returnValue is Queue<TValue> queue)
                    {
                        while (queue.Count > 0)
{
                            yield return queue.Dequeue();
                        }
                    }
                }
                while (!bufferState.IsFinalBlock);
            }
            finally
            {
                bufferState.Dispose();
            }
        }
    }
References System.cancellationToken, System.converter, System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Text.Json.JsonSerializer.CreateQueueJsonTypeInfo< TValue >(), System.Text.Json.Dictionary, System.Collections.Generic.Dictionary< TKey, TValue >.Initialize(), System.options, System.Text.Json.JsonSerializer.ReadFromStreamAsync(), and System.Text.Json.JsonSerializerOptions.s_defaultOptions.