Terraria: System.Text.Json.JsonSerializer.ReadAllAsync< TValue >
ReadAllAsync< TValue >()
static async ValueTask< TValue > System.Text.Json.JsonSerializer.ReadAllAsync< TValue > (Stream utf8Json, JsonTypeInfo jsonTypeInfo, CancellationToken cancellationToken) inline static package
Definition at line 994 of file JsonSerializer.cs.
    {
        JsonSerializerOptions options = jsonTypeInfo.Options;
        ReadBufferState bufferState = new ReadBufferState(options.DefaultBufferSize);
        ReadStack readStack = default(ReadStack);
        readStack.Initialize(jsonTypeInfo, supportContinuation: true);
        JsonConverter converter = readStack.Current.JsonPropertyInfo.ConverterBase;
        JsonReaderState jsonReaderState = new JsonReaderState(options.GetReaderOptions());
        try
        {
            TValue result;
            do
            {
                bufferState = await ReadFromStreamAsync(utf8Json, bufferState, cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
                result = ContinueDeserialize<TValue>(ref bufferState, ref jsonReaderState, ref readStack, converter, options);
            }
            while (!bufferState.IsFinalBlock);
            return result;
        }
        finally
        {
            bufferState.Dispose();
        }
    }
References System.cancellationToken, System.Text.Json.JsonSerializer.ContinueDeserialize< TValue >(), System.converter, System.Collections.Generic.Dictionary< TKey, TValue >.Initialize(), System.options, and System.Text.Json.JsonSerializer.ReadFromStreamAsync().
Referenced by System.Text.Json.JsonSerializer.DeserializeAsync< TValue >(), and System.Text.Json.JsonSerializer.DeserializeAsync< TValue >().