Terraria: System.Text.Json.JsonSerializer.ResolveMetadataForJsonObject< T >
ResolveMetadataForJsonObject< T >()
static bool System.Text.Json.JsonSerializer.ResolveMetadataForJsonObject< T > (ref Utf8JsonReader reader, ref ReadStack state, JsonSerializerOptions options) inline static package
Definition at line 400 of file JsonSerializer.cs.
    {
        JsonConverter converterBase = state.Current.JsonTypeInfo.PropertyInfoForTypeInfo.ConverterBase;
        if ((int)state.Current.ObjectState < 2 && !TryReadAheadMetadataAndSetState(ref reader, ref state, StackFrameObjectState.ReadNameOrEndObject))
        {
            return false;
        }
        if (state.Current.ObjectState == StackFrameObjectState.ReadNameOrEndObject)
        {
            if (reader.TokenType != JsonTokenType.PropertyName)
            {
                state.Current.ObjectState = StackFrameObjectState.PropertyValue;
                state.Current.PropertyState = StackFramePropertyState.ReadName;
                return true;
            }
            ReadOnlySpan<byte> span = reader.GetSpan();
            switch (GetMetadataPropertyName(span))
            {
            case MetadataPropertyName.Id:
                state.Current.JsonPropertyName = s_idPropertyName;
                if (!converterBase.CanHaveIdMetadata)
                {
                    ThrowHelper.ThrowJsonException_MetadataCannotParsePreservedObjectIntoImmutable(converterBase.TypeToConvert);
                }
                state.Current.ObjectState = StackFrameObjectState.ReadAheadIdValue;
                break;
            case MetadataPropertyName.Ref:
                state.Current.JsonPropertyName = s_refPropertyName;
                if (converterBase.IsValueType)
                {
                    ThrowHelper.ThrowJsonException_MetadataInvalidReferenceToValueType(converterBase.TypeToConvert);
                }
                state.Current.ObjectState = StackFrameObjectState.ReadAheadRefValue;
                break;
            case MetadataPropertyName.Values:
                ThrowHelper.ThrowJsonException_MetadataInvalidPropertyWithLeadingDollarSign(span, ref state, in reader);
                break;
            default:
                state.Current.ObjectState = StackFrameObjectState.PropertyValue;
                state.Current.PropertyState = StackFramePropertyState.ReadName;
                return true;
            }
        }
        if (state.Current.ObjectState == StackFrameObjectState.ReadAheadRefValue)
        {
            if (!TryReadAheadMetadataAndSetState(ref reader, ref state, StackFrameObjectState.ReadRefValue))
            {
                return false;
            }
        }
        else if (state.Current.ObjectState == StackFrameObjectState.ReadAheadIdValue && !TryReadAheadMetadataAndSetState(ref reader, ref state, StackFrameObjectState.ReadIdValue))
        {
            return false;
        }
        if (state.Current.ObjectState == StackFrameObjectState.ReadRefValue)
        {
            if (reader.TokenType != JsonTokenType.String)
            {
                ThrowHelper.ThrowJsonException_MetadataValueWasNotString(reader.TokenType);
            }
            string @string = reader.GetString();
            object obj = state.ReferenceResolver.ResolveReference(@string);
            ValidateValueIsCorrectType<T>(obj, @string);
            state.Current.ReturnValue = obj;
            state.Current.ObjectState = StackFrameObjectState.ReadAheadRefEndObject;
        }
        else if (state.Current.ObjectState == StackFrameObjectState.ReadIdValue)
        {
            if (reader.TokenType != JsonTokenType.String)
            {
                ThrowHelper.ThrowJsonException_MetadataValueWasNotString(reader.TokenType);
            }
            converterBase.CreateInstanceForReferenceResolver(ref reader, ref state, options);
            string string2 = reader.GetString();
            state.ReferenceResolver.AddReference(string2, state.Current.ReturnValue);
            state.Current.ObjectState = StackFrameObjectState.CreatedObject;
        }
        state.Current.JsonPropertyName = null;
        if (state.Current.ObjectState == StackFrameObjectState.ReadAheadRefEndObject && !TryReadAheadMetadataAndSetState(ref reader, ref state, StackFrameObjectState.ReadRefEndObject))
        {
            return false;
        }
        if (state.Current.ObjectState == StackFrameObjectState.ReadRefEndObject && reader.TokenType != JsonTokenType.EndObject)
        {
            ThrowHelper.ThrowJsonException_MetadataReferenceObjectCannotContainOtherProperties(reader.GetSpan(), ref state);
        }
        return true;
    }
References System.Text.Json.Dictionary, System.Text.Json.JsonSerializer.GetMetadataPropertyName(), System.obj, System.options, System.Text.Json.JsonSerializer.s_idPropertyName, System.Text.Json.JsonSerializer.s_refPropertyName, System.state, System.Text.Json.ThrowHelper.ThrowJsonException_MetadataCannotParsePreservedObjectIntoImmutable(), System.Text.Json.ThrowHelper.ThrowJsonException_MetadataInvalidPropertyWithLeadingDollarSign(), System.Text.Json.ThrowHelper.ThrowJsonException_MetadataInvalidReferenceToValueType(), System.Text.Json.ThrowHelper.ThrowJsonException_MetadataReferenceObjectCannotContainOtherProperties(), System.Text.Json.ThrowHelper.ThrowJsonException_MetadataValueWasNotString(), System.Text.Json.JsonSerializer.TryReadAheadMetadataAndSetState(), and System.Text.Json.JsonSerializer.ValidateValueIsCorrectType< T >().