Terraria: System.Text.Json.JsonSerializer.ReadFromSpan< TValue >
ReadFromSpan< TValue >() [1/2]
static TValue System.Text.Json.JsonSerializer.ReadFromSpan< TValue > (ReadOnlySpan< byte > utf8Json, JsonTypeInfo jsonTypeInfo, int? actualByteCount = null) inline static private
Definition at line 773 of file JsonSerializer.cs.
    {
        JsonSerializerOptions options = jsonTypeInfo.Options;
        JsonReaderState state = new JsonReaderState(options.GetReaderOptions());
        Utf8JsonReader reader = new Utf8JsonReader(utf8Json, isFinalBlock: true, state);
        ReadStack state2 = default(ReadStack);
        state2.Initialize(jsonTypeInfo);
        JsonConverter converterBase = jsonTypeInfo.PropertyInfoForTypeInfo.ConverterBase;
        if (converterBase is JsonConverter<TValue> jsonConverter)
        {
            return jsonConverter.ReadCore(ref reader, options, ref state2);
        }
        object obj = converterBase.ReadCoreAsObject(ref reader, options, ref state2);
        return (TValue)obj;
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Initialize(), System.obj, System.options, and System.state.
Referenced by System.Text.Json.JsonSerializer.Deserialize< TValue >(), System.Text.Json.JsonSerializer.Deserialize< TValue >(), System.Text.Json.JsonSerializer.Deserialize< TValue >(), System.Text.Json.JsonSerializer.Deserialize< TValue >(), System.Text.Json.JsonSerializer.Deserialize< TValue >(), System.Text.Json.JsonSerializer.Deserialize< TValue >(), System.Text.Json.JsonSerializer.ReadDocument< TValue >(), System.Text.Json.JsonSerializer.ReadFromSpan< TValue >(), System.Text.Json.JsonSerializer.ReadNode< TValue >(), and System.Text.Json.JsonSerializer.ReadUsingMetadata< TValue >().