Terraria: System.Xml.Xsl.XslTransform.Compile
Compile()
void System.Xml.Xsl.XslTransform.Compile (XPathNavigator stylesheet, XmlResolver resolver) inline private
Definition at line 254 of file XslTransform.cs.
    {
        Compiler compiler = new Compiler();
        NavigatorInput input = new NavigatorInput(stylesheet);
        compiler.Compile(input, resolver ?? XmlNullResolver.Singleton);
        _CompiledStylesheet = compiler.CompiledStylesheet;
        _QueryStore = compiler.QueryStore;
        _RootAction = compiler.RootAction;
    }
References System.Xml.Xsl.XslTransform._CompiledStylesheet, System.Xml.Xsl.XslTransform._QueryStore, System.Xml.Xsl.XslTransform._RootAction, System.input, and System.Xml.XmlNullResolver.Singleton.
Referenced by System.Xml.Xsl.XslTransform.Load(), System.Xml.Xsl.XslTransform.Load(), and System.Xml.Xsl.XslTransform.Load().