Terraria: System.IO.TextWriter.WriteLine
WriteLine() [1/20]
virtual void System.IO.TextWriter.WriteLine () inline virtual
Reimplemented in System.CodeDom.Compiler.IndentedTextWriter, System.IO.TextWriter.NullTextWriter, and System.IO.TextWriter.SyncTextWriter.
Definition at line 671 of file TextWriter.cs.
    {
        Write(CoreNewLine);
    }
References System.IO.TextWriter.CoreNewLine, and System.IO.Write.
Referenced by System.Linq.Expressions.DebugViewWriter.WriteLine(), System.CodeDom.Compiler.IndentedTextWriter.WriteLine(), System.IO.TextWriter.SyncTextWriter.WriteLine(), System.Xml.Serialization.IndentedWriter.WriteLine(), System.CodeDom.Compiler.IndentedTextWriter.WriteLine(), System.IO.TextWriter.SyncTextWriter.WriteLine(), System.IO.TextWriter.WriteLine(), System.CodeDom.Compiler.IndentedTextWriter.WriteLine(), System.IO.TextWriter.SyncTextWriter.WriteLine(), System.IO.TextWriter.WriteLine(), System.IO.TextWriter.SyncTextWriter.WriteLine(), System.CodeDom.Compiler.IndentedTextWriter.WriteLine(), System.IO.TextWriter.SyncTextWriter.WriteLine(), System.IO.TextWriter.WriteLine(), System.CodeDom.Compiler.IndentedTextWriter.WriteLine(), System.IO.TextWriter.WriteLine(), System.IO.TextWriter.SyncTextWriter.WriteLine(), System.IO.TextWriter.WriteLine(), System.CodeDom.Compiler.IndentedTextWriter.WriteLine(), System.IO.TextWriter.SyncTextWriter.WriteLine(), System.IO.TextWriter.WriteLine(), System.CodeDom.Compiler.IndentedTextWriter.WriteLine(), System.IO.TextWriter.SyncTextWriter.WriteLine(), System.IO.TextWriter.WriteLine(), System.CodeDom.Compiler.IndentedTextWriter.WriteLine(), System.IO.TextWriter.SyncTextWriter.WriteLine(), System.IO.TextWriter.WriteLine(), System.CodeDom.Compiler.IndentedTextWriter.WriteLine(), System.IO.TextWriter.SyncTextWriter.WriteLine(), System.IO.TextWriter.WriteLine(), System.IO.TextWriter.SyncTextWriter.WriteLine(), System.CodeDom.Compiler.IndentedTextWriter.WriteLine(), System.IO.TextWriter.WriteLine(), System.IO.StringWriter.WriteLine(), System.IO.TextWriter.SyncTextWriter.WriteLine(), System.IO.TextWriter.WriteLine(), System.IO.TextWriter.SyncTextWriter.WriteLine(), System.IO.TextWriter.SyncTextWriter.WriteLine(), System.IO.TextWriter.SyncTextWriter.WriteLine(), System.CodeDom.Compiler.IndentedTextWriter.WriteLine(), System.IO.TextWriter.WriteLine(), System.CodeDom.Compiler.IndentedTextWriter.WriteLine(), System.IO.TextWriter.WriteLine(), System.IO.TextWriter.WriteLine(), System.CodeDom.Compiler.IndentedTextWriter.WriteLine(), System.IO.TextWriter.WriteLine(), System.IO.TextWriter.SyncTextWriter.WriteLine(), System.Xml.Serialization.IndentedWriter.WriteLine(), System.IO.TextWriter.SyncTextWriter.WriteLine(), System.Diagnostics.TextWriterTraceListener.WriteLine(), System.CodeDom.Compiler.IndentedTextWriter.WriteLine(), System.IO.TextWriter.SyncTextWriter.WriteLine(), System.IO.StringWriter.WriteLine(), System.IO.TextWriter.WriteLine(), System.CodeDom.Compiler.IndentedTextWriter.WriteLine(), System.IO.TextWriter.SyncTextWriter.WriteLine(), System.IO.TextWriter.WriteLine(), System.IO.TextWriter.SyncTextWriter.WriteLine(), System.IO.TextWriter.WriteLine(), System.IO.StringWriter.WriteLineAsync(), System.IO.StringWriter.WriteLineAsync(), System.IO.StringWriter.WriteLineAsync(), System.IO.StringWriter.WriteLineAsync(), System.IO.StringWriter.WriteLineAsync(), and System.CodeDom.Compiler.IndentedTextWriter.WriteLineNoTabs().