Terraria: System.Xml.XmlUtf8RawTextWriterIndent.WriteIndentAsync
WriteIndentAsync()
async Task System.Xml.XmlUtf8RawTextWriterIndent.WriteIndentAsync () inline private
Definition at line 365 of file XmlUtf8RawTextWriterIndent.cs.
    {
        CheckAsyncCall();
        await RawTextAsync(_newLineChars).ConfigureAwait(continueOnCapturedContext: false);
        for (int i = _indentLevel; i > 0; i--)
        {
            await RawTextAsync(_indentChars).ConfigureAwait(continueOnCapturedContext: false);
        }
    }
References System.Xml.XmlUtf8RawTextWriterIndent._indentChars, System.Xml.XmlUtf8RawTextWriterIndent._indentLevel, System.Xml.XmlUtf8RawTextWriter._newLineChars, System.Xml.XmlUtf8RawTextWriter.CheckAsyncCall(), System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.Xml.Dictionary, and System.Xml.XmlUtf8RawTextWriter.RawTextAsync().
Referenced by System.Xml.XmlUtf8RawTextWriterIndent.WriteCommentAsync(), System.Xml.XmlUtf8RawTextWriterIndent.WriteDocTypeAsync(), System.Xml.XmlUtf8RawTextWriterIndent.WriteEndElementAsync(), System.Xml.XmlUtf8RawTextWriterIndent.WriteFullEndElementAsync(), System.Xml.XmlUtf8RawTextWriterIndent.WriteProcessingInstructionAsync(), System.Xml.XmlUtf8RawTextWriterIndent.WriteStartAttributeAsync(), and System.Xml.XmlUtf8RawTextWriterIndent.WriteStartElementAsync().