Terraria: System.IO.TextWriter.DisposeAsync
DisposeAsync()
virtual ValueTask System.IO.TextWriter.DisposeAsync () inline virtual inherited
Implements System.IAsyncDisposable.
Reimplemented in System.CodeDom.Compiler.IndentedTextWriter, System.IO.StreamWriter, and System.IO.TextWriter.SyncTextWriter.
Definition at line 507 of file TextWriter.cs.
    {
        try
        {
            Dispose();
            return default(ValueTask);
        }
        catch (Exception exception)
        {
            return ValueTask.FromException(exception);
        }
    }
References System.IO.TextWriter.Dispose(), System.exception, and System.Threading.Tasks.ValueTask< TResult >.FromException().
Referenced by System.CodeDom.Compiler.IndentedTextWriter.DisposeAsync(), and System.Xml.XmlEncodedRawTextWriter.DisposeAsyncCore().