Terraria: System.IO.TextWriter.WriteLineAsync
WriteLineAsync() [1/7]
virtual Task System.IO.TextWriter.WriteLineAsync () inline virtual inherited
Reimplemented in System.CodeDom.Compiler.IndentedTextWriter, System.IO.StreamWriter, and System.IO.TextWriter.SyncTextWriter.
Definition at line 960 of file TextWriter.cs.
    {
        return WriteAsync(CoreNewLine);
    }
References System.IO.TextWriter.CoreNewLine, and System.IO.TextWriter.WriteAsync().
Referenced by System.IO.TextWriter.WriteLineAsync(), and System.IO.TextWriter.WriteLineAsync().