Terraria: System.IO.TextWriter.WriteLineAsync
WriteLineAsync() [9/9]
virtual Task System.IO.TextWriter.WriteLineAsync (StringBuilder? value, CancellationToken cancellationToken = default(CancellationToken)) inline virtual inherited
Reimplemented in System.CodeDom.Compiler.IndentedTextWriter, and System.IO.StringWriter.
Definition at line 902 of file TextWriter.cs.
    {
        if (!cancellationToken.IsCancellationRequested)
        {
            if (value != null)
            {
                return WriteLineAsyncCore(value, cancellationToken);
            }
            return WriteAsync(CoreNewLine, cancellationToken);
        }
        return Task.FromCanceled(cancellationToken);
        async Task WriteLineAsyncCore(StringBuilder sb, CancellationToken ct)
        {
            StringBuilder.ChunkEnumerator enumerator = sb.GetChunks().GetEnumerator();
            while (enumerator.MoveNext())
            {
                ReadOnlyMemory<char> current = enumerator.Current;
                await WriteAsync(current, ct).ConfigureAwait(continueOnCapturedContext: false);
            }
            await WriteAsync(CoreNewLine, ct).ConfigureAwait(continueOnCapturedContext: false);
        }
    }
References System.cancellationToken, System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.IO.TextWriter.CoreNewLine, System.Text.StringBuilder.ChunkEnumerator.Current, System.Threading.Tasks.Task< TResult >.FromCanceled(), System.Text.StringBuilder.GetChunks(), System.Text.StringBuilder.ChunkEnumerator.GetEnumerator(), System.Text.StringBuilder.ChunkEnumerator.MoveNext(), System.value, and System.IO.TextWriter.WriteAsync().