Terraria: System.IO.TextWriter.FlushAsync
FlushAsync()
virtual Task System.IO.TextWriter.FlushAsync () inline virtual inherited
Reimplemented in System.CodeDom.Compiler.IndentedTextWriter, System.IO.StreamWriter, System.IO.StringWriter, and System.IO.TextWriter.SyncTextWriter.
Definition at line 965 of file TextWriter.cs.
    {
        return Task.Factory.StartNew(delegate(object state)
        {
            ((TextWriter)state).Flush();
        }, this, CancellationToken.None, TaskCreationOptions.DenyChildAttach, TaskScheduler.Default);
    }
References System.IO.TextWriter.TextWriter(), System.Threading.Tasks.TaskScheduler.Default, System.Threading.Tasks.Task< TResult >.Factory, System.Threading.CancellationToken.None, and System.state.
Referenced by System.Xml.XmlEncodedRawTextWriter.DisposeAsyncCore(), System.CodeDom.Compiler.IndentedTextWriter.FlushAsync(), and System.Xml.XmlEncodedRawTextWriter.FlushAsync().