Terraria: System.IO.TextWriter.Write
Write() [2/19]
virtual void System.IO.TextWriter.Write (char value) inline virtual
Reimplemented in ReLogic.IO.ConsoleOutputMirror.DoubleWriter, System.CodeDom.Compiler.IndentedTextWriter, System.IO.StreamWriter, System.IO.StringWriter, System.IO.TextWriter.NullTextWriter, and System.IO.TextWriter.SyncTextWriter.
Definition at line 524 of file TextWriter.cs.
    {
    }
Referenced by System.Text.Encodings.Web.TextEncoder.Encode(), System.Text.Encodings.Web.TextEncoder.EncodeCore(), System.Xml.XmlEncodedRawTextWriter.FlushBuffer(), System.Web.Util.HttpEncoder.HtmlAttributeEncodeInternal(), System.Web.Util.HttpEncoder.HtmlDecode(), System.Web.Util.HttpEncoder.HtmlEncode(), System.Diagnostics.XmlWriterTraceListener.InternalWrite(), System.CodeDom.Compiler.IndentedTextWriter.OutputTabs(), System.Xml.Xsl.XsltOld.TextOnlyOutput.RecordDone(), System.CodeDom.Compiler.IndentedTextWriter.Write(), System.IO.TextWriter.SyncTextWriter.Write(), System.Xml.Serialization.IndentedWriter.Write(), System.Xml.Xsl.XsltOld.TextOutput.Write(), ReLogic.IO.ConsoleOutputMirror.DoubleWriter.Write(), System.CodeDom.Compiler.IndentedTextWriter.Write(), System.IO.TextWriter.SyncTextWriter.Write(), System.Xml.XmlTextEncoder.Write(), System.IO.TextWriter.SyncTextWriter.Write(), System.CodeDom.Compiler.IndentedTextWriter.Write(), System.IO.TextWriter.SyncTextWriter.Write(), System.CodeDom.Compiler.IndentedTextWriter.Write(), System.IO.TextWriter.SyncTextWriter.Write(), System.CodeDom.Compiler.IndentedTextWriter.Write(), System.IO.TextWriter.SyncTextWriter.Write(), System.CodeDom.Compiler.IndentedTextWriter.Write(), System.IO.TextWriter.SyncTextWriter.Write(), System.CodeDom.Compiler.IndentedTextWriter.Write(), System.IO.TextWriter.SyncTextWriter.Write(), System.CodeDom.Compiler.IndentedTextWriter.Write(), System.IO.TextWriter.SyncTextWriter.Write(), System.IO.TextWriter.SyncTextWriter.Write(), System.CodeDom.Compiler.IndentedTextWriter.Write(), System.IO.TextWriter.SyncTextWriter.Write(), System.IO.TextWriter.SyncTextWriter.Write(), System.IO.TextWriter.SyncTextWriter.Write(), System.IO.TextWriter.SyncTextWriter.Write(), System.CodeDom.Compiler.IndentedTextWriter.Write(), System.CodeDom.Compiler.IndentedTextWriter.Write(), System.CodeDom.Compiler.IndentedTextWriter.Write(), System.IO.TextWriter.SyncTextWriter.Write(), System.Xml.Xsl.XsltOld.TextOutput.Write(), System.Linq.Expressions.DebugViewWriter.Write(), System.Xml.Serialization.IndentedWriter.Write(), System.Xml.XmlTextEncoder.Write(), System.IO.TextWriter.SyncTextWriter.Write(), System.Diagnostics.TextWriterTraceListener.Write(), System.CodeDom.Compiler.IndentedTextWriter.Write(), System.IO.TextWriter.SyncTextWriter.Write(), System.IO.TextWriter.SyncTextWriter.Write(), System.IO.TextWriter.SyncTextWriter.Write(), System.Xml.XmlTextEncoder.WriteCharEntityImpl(), System.Xml.XmlTextEncoder.WriteEntityRefImpl(), System.Xml.Serialization.IndentedWriter.WriteIndent(), System.Xml.XmlTextEncoder.WriteRaw(), System.Xml.XmlTextEncoder.WriteRawWithSurrogateChecking(), System.Xml.XmlTextEncoder.WriteStringFragment(), System.Xml.XmlTextEncoder.WriteSurrogateChar(), and System.Xml.XmlTextEncoder.WriteSurrogateCharEntity().