Terraria: MysticLogFairiesEvent.UpdateTime
UpdateTime()
void MysticLogFairiesEvent.UpdateTime () inline
     {
         if (Main.netMode != 1 && _canSpawnFairies && IsAGoodTime())
         {
             _delayUntilNextAttempt = Math.Max(0, _delayUntilNextAttempt - Main.dayRate);
             if (_delayUntilNextAttempt == 0)
             {
                 _delayUntilNextAttempt = 60;
                 TrySpawningFairies();
             }
         }
     }
References _canSpawnFairies, _delayUntilNextAttempt, Main.dayRate, IsAGoodTime(), Main.netMode, and TrySpawningFairies().
Referenced by Main.UpdateTime().