Terraria: System.Xml.Schema.XmlSchemaSet.ParseSchema
ParseSchema()
XmlSchema System.Xml.Schema.XmlSchemaSet.ParseSchema (string targetNamespace, XmlReader reader) inline package
Definition at line 912 of file XmlSchemaSet.cs.
    {
        XmlNameTable nameTable = reader.NameTable;
        SchemaNames schemaNames = GetSchemaNames(nameTable);
        Parser parser = new Parser(SchemaType.XSD, nameTable, schemaNames, _eventHandler);
        parser.XmlResolver = _readerSettings.GetXmlResolver_CheckConfig();
        try
        {
            SchemaType schemaType = parser.Parse(reader, targetNamespace);
        }
        catch (XmlSchemaException e)
        {
            SendValidationEvent(e, XmlSeverityType.Error);
            return null;
        }
        return parser.XmlSchema;
    }
References System.Xml.Schema.XmlSchemaSet._eventHandler, System.Xml.Schema.XmlSchemaSet._readerSettings, System.Xml.Dictionary, System.Xml.Schema.XmlSchemaSet.GetSchemaNames(), System.Xml.XmlReaderSettings.GetXmlResolver_CheckConfig(), System.Xml.XmlReader.NameTable, and System.Xml.Schema.XmlSchemaSet.SendValidationEvent().
Referenced by System.Xml.Schema.XmlSchemaSet.Add(), System.Xml.Schema.XmlSchemaSet.Add(), and System.Xml.Schema.XmlSchemaSet.Add().