Terraria: System.Xml.Schema.XmlSchemaSet.RemoveSchemaFromGlobalTables
RemoveSchemaFromGlobalTables()
void System.Xml.Schema.XmlSchemaSet.RemoveSchemaFromGlobalTables (XmlSchema schema) inline private
Definition at line 1133 of file XmlSchemaSet.cs.
    {
        if (_schemas.Count == 0)
        {
            return;
        }
        VerifyTables();
        foreach (XmlSchemaElement value in schema.Elements.Values)
        {
            XmlSchemaElement xmlSchemaElement2 = (XmlSchemaElement)elements[value.QualifiedName];
            if (xmlSchemaElement2 == value)
            {
                elements.Remove(value.QualifiedName);
            }
        }
        foreach (XmlSchemaAttribute value2 in schema.Attributes.Values)
        {
            XmlSchemaAttribute xmlSchemaAttribute2 = (XmlSchemaAttribute)attributes[value2.QualifiedName];
            if (xmlSchemaAttribute2 == value2)
            {
                attributes.Remove(value2.QualifiedName);
            }
        }
        foreach (XmlSchemaType value3 in schema.SchemaTypes.Values)
        {
            XmlSchemaType xmlSchemaType2 = (XmlSchemaType)schemaTypes[value3.QualifiedName];
            if (xmlSchemaType2 == value3)
            {
                schemaTypes.Remove(value3.QualifiedName);
            }
        }
    }
References System.Xml.Schema.XmlSchemaSet._schemas, System.Xml.Schema.XmlSchemaSet.attributes, System.Collections.SortedList.Count, System.Xml.Schema.XmlSchemaSet.elements, System.Xml.Schema.XmlSchemaObjectTable.Remove(), System.Xml.Schema.XmlSchemaSet.schemaTypes, System.value, System.Collections.Generic.Dictionary< TKey, TValue >.Values, and System.Xml.Schema.XmlSchemaSet.VerifyTables().
Referenced by System.Xml.Schema.XmlSchemaSet.Remove(), and System.Xml.Schema.XmlSchemaSet.Reprocess().