Terraria: System.Xml.Schema.XmlSchemaSet.Add
Add() [1/6]
void System.Xml.Schema.XmlSchemaSet.Add (string targetNamespace, XmlReader reader, Hashtable validatedNamespaces) inline package
Definition at line 655 of file XmlSchemaSet.cs.
    {
        if (reader == null)
        {
            throw new ArgumentNullException("reader");
        }
        if (targetNamespace == null)
        {
            targetNamespace = string.Empty;
        }
        if (validatedNamespaces[targetNamespace] != null)
        {
            if (FindSchemaByNSAndUrl(new Uri(reader.BaseURI, UriKind.RelativeOrAbsolute), targetNamespace, null) == null)
            {
                throw new XmlSchemaException(System.SR.Sch_ComponentAlreadySeenForNS, targetNamespace);
            }
        }
        else
        {
            if (IsSchemaLoaded(new Uri(reader.BaseURI, UriKind.RelativeOrAbsolute), targetNamespace, out var schema))
            {
                return;
            }
            schema = ParseSchema(targetNamespace, reader);
            DictionaryEntry[] array = new DictionaryEntry[_schemaLocations.Count];
            _schemaLocations.CopyTo(array, 0);
            Add(targetNamespace, schema);
            if (schema.ImportedSchemas.Count <= 0)
            {
                return;
            }
            for (int i = 0; i < schema.ImportedSchemas.Count; i++)
            {
                XmlSchema xmlSchema = (XmlSchema)schema.ImportedSchemas[i];
                string text = xmlSchema.TargetNamespace;
                if (text == null)
                {
                    text = string.Empty;
                }
                if (validatedNamespaces[text] != null && FindSchemaByNSAndUrl(xmlSchema.BaseUri, text, array) == null)
                {
                    RemoveRecursive(schema);
                    throw new XmlSchemaException(System.SR.Sch_ComponentAlreadySeenForNS, text);
                }
            }
        }
    }
References System.Xml.Schema.XmlSchemaSet._schemaLocations, System.Add, System.array, System.Xml.XmlReader.BaseURI, System.Collections.Hashtable.CopyTo(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Collections.Hashtable.Count, System.Xml.Schema.XmlSchemaSet.FindSchemaByNSAndUrl(), System.Xml.Schema.XmlSchemaSet.IsSchemaLoaded(), System.Xml.Schema.XmlSchemaSet.ParseSchema(), System.Xml.Schema.XmlSchemaSet.RemoveRecursive(), System.SR.Sch_ComponentAlreadySeenForNS, and System.text.