Terraria: System.Xml.Schema.XmlSchemaSet.Remove
Remove() [2/2]
XmlSchema System.Xml.Schema.XmlSchemaSet.Remove (XmlSchema schema, bool forceCompile) inline package
Definition at line 855 of file XmlSchemaSet.cs.
    {
        if (schema == null)
        {
            throw new ArgumentNullException("schema");
        }
        lock (InternalSyncObject)
        {
            if (_schemas.ContainsKey(schema.SchemaId))
            {
                if (forceCompile)
                {
                    RemoveSchemaFromGlobalTables(schema);
                    RemoveSchemaFromCaches(schema);
                }
                _schemas.Remove(schema.SchemaId);
                if (schema.BaseUri != null)
                {
                    _schemaLocations.Remove(schema.BaseUri);
                }
                string targetNamespace = GetTargetNamespace(schema);
                if (Schemas(targetNamespace).Count == 0)
                {
                    _targetNamespaces.Remove(targetNamespace);
                }
                if (forceCompile)
                {
                    _isCompiled = false;
                    _compileAll = true;
                }
                return schema;
            }
        }
        return null;
    }
References System.Xml.Schema.XmlSchemaSet._compileAll, System.Xml.Schema.XmlSchemaSet._isCompiled, System.Xml.Schema.XmlSchemaSet._schemaLocations, System.Xml.Schema.XmlSchemaSet._schemas, System.Xml.Schema.XmlSchemaSet._targetNamespaces, System.Collections.SortedList.ContainsKey(), System.Xml.Schema.XmlSchemaSet.Count, System.Xml.Dictionary, System.Xml.Schema.XmlSchemaSet.GetTargetNamespace(), System.Xml.Schema.XmlSchemaSet.InternalSyncObject, System.Collections.SortedList.Remove(), System.Collections.Hashtable.Remove(), System.Xml.Schema.XmlSchemaSet.RemoveSchemaFromCaches(), System.Xml.Schema.XmlSchemaSet.RemoveSchemaFromGlobalTables(), and System.Xml.Schema.XmlSchemaSet.Schemas().