Terraria: System.Xml.Schema.XmlSchemaSet.Contains
Contains() [1/2]
bool System.Xml.Schema.XmlSchemaSet.Contains (string? targetNamespace) inline
Definition at line 435 of file XmlSchemaSet.cs.
    {
        if (targetNamespace == null)
        {
            targetNamespace = string.Empty;
        }
        return _targetNamespaces[targetNamespace] != null;
    }
References System.Xml.Schema.XmlSchemaSet._targetNamespaces, and System.Xml.Dictionary.
Referenced by System.Xml.Schema.XmlSchemaInference.AddAttribute(), System.Xml.Schema.XmlSchemaInference.AddElement(), System.Xml.Serialization.XmlSchemas.AddName(), System.Xml.Serialization.XmlSchemas.Compile(), System.Xml.Serialization.XmlSchemas.Contains(), and System.Runtime.Serialization.SchemaExporter.ExportSerializationSchema().