Terraria: System.Xml.Schema.XmlSchemaSet.CopyFromCompiledSet
CopyFromCompiledSet()
void System.Xml.Schema.XmlSchemaSet.CopyFromCompiledSet (XmlSchemaSet otherSet) inline package
Definition at line 930 of file XmlSchemaSet.cs.
    {
        SortedList sortedSchemas = otherSet.SortedSchemas;
        bool flag = _schemas.Count == 0;
        ArrayList arrayList = new ArrayList();
        SchemaInfo schemaInfo = new SchemaInfo();
        for (int i = 0; i < sortedSchemas.Count; i++)
        {
            XmlSchema xmlSchema = (XmlSchema)sortedSchemas.GetByIndex(i);
            Uri baseUri = xmlSchema.BaseUri;
            if (_schemas.ContainsKey(xmlSchema.SchemaId) || (baseUri != null && baseUri.OriginalString.Length != 0 && _schemaLocations[baseUri] != null))
            {
                arrayList.Add(xmlSchema);
                continue;
            }
            _schemas.Add(xmlSchema.SchemaId, xmlSchema);
            if (baseUri != null && baseUri.OriginalString.Length != 0)
            {
                _schemaLocations.Add(baseUri, xmlSchema);
            }
            string targetNamespace = GetTargetNamespace(xmlSchema);
            if (_targetNamespaces[targetNamespace] == null)
            {
                _targetNamespaces.Add(targetNamespace, targetNamespace);
            }
        }
        VerifyTables();
        foreach (XmlSchemaElement value in otherSet.GlobalElements.Values)
        {
            if (AddToTable(elements, value.QualifiedName, value))
            {
                continue;
            }
            goto IL_026e;
        }
        foreach (XmlSchemaAttribute value2 in otherSet.GlobalAttributes.Values)
        {
            if (AddToTable(attributes, value2.QualifiedName, value2))
            {
                continue;
            }
            goto IL_026e;
        }
        foreach (XmlSchemaType value3 in otherSet.GlobalTypes.Values)
        {
            if (AddToTable(schemaTypes, value3.QualifiedName, value3))
            {
                continue;
            }
            goto IL_026e;
        }
        ProcessNewSubstitutionGroups(otherSet.SubstitutionGroups, resolve: false);
        schemaInfo.Add(_cachedCompiledInfo, _eventHandler);
        schemaInfo.Add(otherSet.CompiledInfo, _eventHandler);
        _cachedCompiledInfo = schemaInfo;
        if (flag)
        {
            _isCompiled = true;
            _compileAll = false;
        }
        return;
        IL_026e:
        foreach (XmlSchema value4 in sortedSchemas.Values)
        {
            if (!arrayList.Contains(value4))
            {
                Remove(value4, forceCompile: false);
            }
        }
        foreach (XmlSchemaElement value5 in otherSet.GlobalElements.Values)
        {
            if (!arrayList.Contains((XmlSchema)value5.Parent))
            {
                elements.Remove(value5.QualifiedName);
            }
        }
        foreach (XmlSchemaAttribute value6 in otherSet.GlobalAttributes.Values)
        {
            if (!arrayList.Contains((XmlSchema)value6.Parent))
            {
                attributes.Remove(value6.QualifiedName);
            }
        }
        foreach (XmlSchemaType value7 in otherSet.GlobalTypes.Values)
        {
            if (!arrayList.Contains((XmlSchema)value7.Parent))
            {
                schemaTypes.Remove(value7.QualifiedName);
            }
        }
    }
References System.Xml.Schema.XmlSchemaSet._cachedCompiledInfo, System.Xml.Schema.XmlSchemaSet._compileAll, System.Xml.Schema.XmlSchemaSet._eventHandler, System.Xml.Schema.XmlSchemaSet._isCompiled, System.Xml.Schema.XmlSchemaSet._schemaLocations, System.Xml.Schema.XmlSchemaSet._schemas, System.Xml.Schema.XmlSchemaSet._targetNamespaces, System.Collections.SortedList.Add(), System.Collections.Hashtable.Add(), System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Xml.Schema.XmlSchemaSet.AddToTable(), System.Xml.Schema.XmlSchemaSet.attributes, System.Collections.Generic.Dictionary< TKey, TValue >.Contains(), System.Collections.SortedList.ContainsKey(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Xml.Dictionary, System.Xml.Schema.XmlSchemaSet.elements, System.Xml.Schema.XmlSchemaSet.GetTargetNamespace(), System.Uri.OriginalString, System.Xml.Schema.XmlSchemaSet.ProcessNewSubstitutionGroups(), System.Xml.Schema.XmlSchemaObjectTable.Remove(), System.Xml.Remove, System.Xml.Schema.XmlSchemaSet.schemaTypes, System.value, System.Collections.Generic.Dictionary< TKey, TValue >.Values, and System.Xml.Schema.XmlSchemaSet.VerifyTables().
Referenced by System.Xml.Schema.XmlSchemaSet.Add().