Terraria: System.Xml.Schema.XmlSchemaSet.AddSchemaToSet
AddSchemaToSet()
void System.Xml.Schema.XmlSchemaSet.AddSchemaToSet (XmlSchema schema) inline private
Definition at line 757 of file XmlSchemaSet.cs.
    {
        _schemas.Add(schema.SchemaId, schema);
        string targetNamespace = GetTargetNamespace(schema);
        if (_targetNamespaces[targetNamespace] == null)
        {
            _targetNamespaces.Add(targetNamespace, targetNamespace);
        }
        if (_schemaForSchema == null && targetNamespace == "http://www.w3.org/2001/XMLSchema" && schema.SchemaTypes[DatatypeImplementation.QnAnyType] != null)
        {
            _schemaForSchema = schema;
        }
        for (int i = 0; i < schema.ImportedSchemas.Count; i++)
        {
            XmlSchema xmlSchema = (XmlSchema)schema.ImportedSchemas[i];
            if (!_schemas.ContainsKey(xmlSchema.SchemaId))
            {
                _schemas.Add(xmlSchema.SchemaId, xmlSchema);
            }
            targetNamespace = GetTargetNamespace(xmlSchema);
            if (_targetNamespaces[targetNamespace] == null)
            {
                _targetNamespaces.Add(targetNamespace, targetNamespace);
            }
            if (_schemaForSchema == null && targetNamespace == "http://www.w3.org/2001/XMLSchema" && schema.SchemaTypes[DatatypeImplementation.QnAnyType] != null)
            {
                _schemaForSchema = schema;
            }
        }
    }
References System.Xml.Schema.XmlSchemaSet._schemaForSchema, System.Xml.Schema.XmlSchemaSet._schemas, System.Xml.Schema.XmlSchemaSet._targetNamespaces, System.Collections.SortedList.Add(), System.Collections.Hashtable.Add(), System.Collections.SortedList.ContainsKey(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Xml.Dictionary, System.Xml.Schema.XmlSchemaSet.GetTargetNamespace(), and System.Xml.Schema.DatatypeImplementation.QnAnyType.
Referenced by System.Xml.Schema.XmlSchemaSet.Add(), and System.Xml.Schema.XmlSchemaSet.IsSchemaLoaded().