Terraria: System.Xml.Schema.XmlSchemaSet.Compile
Compile()
void System.Xml.Schema.XmlSchemaSet.Compile () inline
Definition at line 453 of file XmlSchemaSet.cs.
    {
        if (_isCompiled)
        {
            return;
        }
        if (_schemas.Count == 0)
        {
            ClearTables();
            _cachedCompiledInfo = new SchemaInfo();
            _isCompiled = true;
            _compileAll = false;
            return;
        }
        lock (InternalSyncObject)
        {
            if (_isCompiled)
            {
                return;
            }
            Compiler compiler = new Compiler(_nameTable, _eventHandler, _schemaForSchema, _compilationSettings);
            SchemaInfo schemaInfo = new SchemaInfo();
            int i = 0;
            if (!_compileAll)
            {
                compiler.ImportAllCompiledSchemas(this);
            }
            try
            {
                XmlSchema buildInSchema = Preprocessor.GetBuildInSchema();
                for (i = 0; i < _schemas.Count; i++)
                {
                    XmlSchema xmlSchema = (XmlSchema)_schemas.GetByIndex(i);
                    Monitor.Enter(xmlSchema);
                    if (!xmlSchema.IsPreprocessed)
                    {
                        SendValidationEvent(new XmlSchemaException(System.SR.Sch_SchemaNotPreprocessed, string.Empty), XmlSeverityType.Error);
                        _isCompiled = false;
                        return;
                    }
                    if (xmlSchema.IsCompiledBySet)
                    {
                        if (!_compileAll)
{
                            continue;
                        }
                        if (xmlSchema == buildInSchema)
{
                            compiler.Prepare(xmlSchema, cleanup: false);
                            continue;
                        }
                    }
                    compiler.Prepare(xmlSchema, cleanup: true);
                }
                _isCompiled = compiler.Execute(this, schemaInfo);
                if (_isCompiled)
                {
                    if (!_compileAll)
                    {
                        schemaInfo.Add(_cachedCompiledInfo, _eventHandler);
                    }
                    _compileAll = false;
                    _cachedCompiledInfo = schemaInfo;
                }
            }
            finally
            {
                if (i == _schemas.Count)
                {
                    i--;
                }
                for (int num = i; num >= 0; num--)
                {
                    XmlSchema xmlSchema2 = (XmlSchema)_schemas.GetByIndex(num);
                    if (xmlSchema2 == Preprocessor.GetBuildInSchema())
                    {
                        Monitor.Exit(xmlSchema2);
                    }
                    else
                    {
                        xmlSchema2.IsCompiledBySet = _isCompiled;
                        Monitor.Exit(xmlSchema2);
                    }
                }
            }
        }
    }
References System.Xml.Schema.XmlSchemaSet._cachedCompiledInfo, System.Xml.Schema.XmlSchemaSet._compilationSettings, System.Xml.Schema.XmlSchemaSet._compileAll, System.Xml.Schema.XmlSchemaSet._eventHandler, System.Xml.Schema.XmlSchemaSet._isCompiled, System.Xml.Schema.XmlSchemaSet._nameTable, System.Xml.Schema.XmlSchemaSet._schemaForSchema, System.Xml.Schema.XmlSchemaSet._schemas, System.Xml.Schema.SchemaInfo.Add(), System.Xml.Schema.XmlSchemaSet.ClearTables(), System.Collections.SortedList.Count, System.Xml.Dictionary, System.Threading.Monitor.Enter(), System.Threading.Monitor.Exit(), System.Xml.Schema.Preprocessor.GetBuildInSchema(), System.Collections.SortedList.GetByIndex(), System.Xml.Schema.XmlSchemaSet.InternalSyncObject, System.SR.Sch_SchemaNotPreprocessed, and System.Xml.Schema.XmlSchemaSet.SendValidationEvent().
Referenced by System.Xml.Serialization.XmlSchemas.Compile(), System.Xml.Schema.XmlSchemaInference.InferSchema1(), System.Xml.Schema.XmlSchemaValidator.RecompileSchemaSet(), and System.Xml.Serialization.SerializableMapping.RetrieveSerializableSchema().