Terraria: System.Xml.Schema.XmlSchemaSet.PreprocessSchema
PreprocessSchema()
bool System.Xml.Schema.XmlSchemaSet.PreprocessSchema (ref XmlSchema schema, string targetNamespace) inline package
Definition at line 900 of file XmlSchemaSet.cs.
    {
        Preprocessor preprocessor = new Preprocessor(_nameTable, GetSchemaNames(_nameTable), _eventHandler, _compilationSettings);
        preprocessor.XmlResolver = _readerSettings.GetXmlResolver_CheckConfig();
        preprocessor.ReaderSettings = _readerSettings;
        preprocessor.SchemaLocations = _schemaLocations;
        preprocessor.ChameleonSchemas = _chameleonSchemas;
        bool result = preprocessor.Execute(schema, targetNamespace, loadExternals: true);
        schema = preprocessor.RootSchema;
        return result;
    }
References System.Xml.Schema.XmlSchemaSet._chameleonSchemas, System.Xml.Schema.XmlSchemaSet._compilationSettings, System.Xml.Schema.XmlSchemaSet._eventHandler, System.Xml.Schema.XmlSchemaSet._nameTable, System.Xml.Schema.XmlSchemaSet._readerSettings, System.Xml.Schema.XmlSchemaSet._schemaLocations, System.Xml.Dictionary, System.Xml.Schema.XmlSchemaSet.GetSchemaNames(), and System.Xml.XmlReaderSettings.GetXmlResolver_CheckConfig().
Referenced by System.Xml.Schema.XmlSchemaSet.Add(), and System.Xml.Schema.XmlSchemaSet.Reprocess().