Terraria: System.Xml.Schema.XmlSchemaSet.AddToTable
AddToTable()
bool System.Xml.Schema.XmlSchemaSet.AddToTable (XmlSchemaObjectTable table, XmlQualifiedName qname, XmlSchemaObject item) inline private
Definition at line 1166 of file XmlSchemaSet.cs.
    {
        if (qname.Name.Length == 0)
        {
            return true;
        }
        XmlSchemaObject xmlSchemaObject = table[qname];
        if (xmlSchemaObject != null)
        {
            if (xmlSchemaObject == item || xmlSchemaObject.SourceUri == item.SourceUri)
            {
                return true;
            }
            string res = string.Empty;
            if (item is XmlSchemaComplexType)
            {
                res = System.SR.Sch_DupComplexType;
            }
            else if (item is XmlSchemaSimpleType)
            {
                res = System.SR.Sch_DupSimpleType;
            }
            else if (item is XmlSchemaElement)
            {
                res = System.SR.Sch_DupGlobalElement;
            }
            else if (item is XmlSchemaAttribute)
            {
                if (qname.Namespace == "http://www.w3.org/XML/1998/namespace")
                {
                    XmlSchema buildInSchema = Preprocessor.GetBuildInSchema();
                    XmlSchemaObject xmlSchemaObject2 = buildInSchema.Attributes[qname];
                    if (xmlSchemaObject == xmlSchemaObject2)
                    {
                        table.Insert(qname, item);
                        return true;
                    }
                    if (item == xmlSchemaObject2)
                    {
                        return true;
                    }
                }
                res = System.SR.Sch_DupGlobalAttribute;
            }
            SendValidationEvent(new XmlSchemaException(res, qname.ToString()), XmlSeverityType.Error);
            return false;
        }
        table.Add(qname, item);
        return true;
    }
References System.Xml.Schema.XmlSchemaObjectTable.Add(), System.Xml.Schema.Preprocessor.GetBuildInSchema(), System.Xml.Schema.XmlSchemaObjectTable.Insert(), System.item, System.Xml.XmlQualifiedName.Name, System.Xml.XmlQualifiedName.Namespace, System.SR.Sch_DupComplexType, System.SR.Sch_DupGlobalAttribute, System.SR.Sch_DupGlobalElement, System.SR.Sch_DupSimpleType, System.Xml.Schema.XmlSchemaSet.SendValidationEvent(), and System.Xml.XmlQualifiedName.ToString().
Referenced by System.Xml.Schema.XmlSchemaSet.CopyFromCompiledSet(), and System.Xml.Schema.XmlSchemaSet.ProcessNewSubstitutionGroups().