Terraria: System.Xml.Schema.XmlSchemaSet.Add
Add() [6/6]
void System.Xml.Schema.XmlSchemaSet.Add (XmlSchemaSet schemas) inline
Definition at line 274 of file XmlSchemaSet.cs.
    {
        if (schemas == null)
        {
            throw new ArgumentNullException("schemas");
        }
        if (this == schemas)
        {
            return;
        }
        bool lockTaken = false;
        bool lockTaken2 = false;
        try
        {
            SpinWait spinWait = default(SpinWait);
            while (true)
            {
                Monitor.TryEnter(InternalSyncObject, ref lockTaken);
                if (lockTaken)
                {
                    Monitor.TryEnter(schemas.InternalSyncObject, ref lockTaken2);
                    if (lockTaken2)
                    {
                        break;
                    }
                    Monitor.Exit(InternalSyncObject);
                    lockTaken = false;
                    spinWait.SpinOnce();
                }
            }
            if (schemas.IsCompiled)
            {
                CopyFromCompiledSet(schemas);
                return;
            }
            bool flag = false;
            string text = null;
            foreach (XmlSchema value in schemas.SortedSchemas.Values)
            {
                text = value.TargetNamespace;
                if (text == null)
                {
                    text = string.Empty;
                }
                if (!_schemas.ContainsKey(value.SchemaId) && FindSchemaByNSAndUrl(value.BaseUri, text, null) == null)
                {
                    XmlSchema xmlSchema2 = Add(value.TargetNamespace, value);
                    if (xmlSchema2 == null)
                    {
                        flag = true;
                        break;
                    }
                }
            }
            if (!flag)
            {
                return;
            }
            foreach (XmlSchema value2 in schemas.SortedSchemas.Values)
            {
                _schemas.Remove(value2.SchemaId);
                _schemaLocations.Remove(value2.BaseUri);
            }
        }
        finally
        {
            if (lockTaken)
            {
                Monitor.Exit(InternalSyncObject);
            }
            if (lockTaken2)
            {
                Monitor.Exit(schemas.InternalSyncObject);
            }
        }
    }
References System.Xml.Schema.XmlSchemaSet._schemaLocations, System.Xml.Schema.XmlSchemaSet._schemas, System.Add, System.Collections.SortedList.ContainsKey(), System.Xml.Schema.XmlSchemaSet.CopyFromCompiledSet(), System.Threading.Monitor.Exit(), System.Xml.Schema.XmlSchemaSet.FindSchemaByNSAndUrl(), System.Xml.Schema.XmlSchemaSet.InternalSyncObject, System.Xml.Schema.XmlSchemaSet.IsCompiled, System.Collections.SortedList.Remove(), System.Collections.Hashtable.Remove(), System.Xml.Schema.XmlSchemaSet.SortedSchemas, System.text, System.Threading.Monitor.TryEnter(), System.value, and System.Collections.SortedList.Values.