Terraria: System.Xml.Schema.XmlSchemaSet.Add
Add() [4/6]
XmlSchema? System.Xml.Schema.XmlSchemaSet.Add (string? targetNamespace, XmlReader schemaDocument) inline
Definition at line 248 of file XmlSchemaSet.cs.
    {
        if (schemaDocument == null)
        {
            throw new ArgumentNullException("schemaDocument");
        }
        if (targetNamespace != null)
        {
            targetNamespace = XmlComplianceUtil.CDataNormalize(targetNamespace);
        }
        lock (InternalSyncObject)
        {
            XmlSchema schema = null;
            Uri schemaUri = new Uri(schemaDocument.BaseURI, UriKind.RelativeOrAbsolute);
            if (IsSchemaLoaded(schemaUri, targetNamespace, out schema))
            {
                return schema;
            }
            DtdProcessing dtdProcessing = _readerSettings.DtdProcessing;
            SetDtdProcessing(schemaDocument);
            schema = Add(targetNamespace, ParseSchema(targetNamespace, schemaDocument));
            _readerSettings.DtdProcessing = dtdProcessing;
            return schema;
        }
    }
References System.Xml.Schema.XmlSchemaSet._readerSettings, System.Add, System.Xml.XmlComplianceUtil.CDataNormalize(), System.Xml.Dictionary, System.Xml.XmlReaderSettings.DtdProcessing, System.Xml.Schema.XmlSchemaSet.InternalSyncObject, System.Xml.Schema.XmlSchemaSet.IsSchemaLoaded(), System.Xml.Schema.XmlSchemaSet.ParseSchema(), and System.Xml.Schema.XmlSchemaSet.SetDtdProcessing().