Terraria: System.Xml.Schema.XmlSchemaSet.IsSchemaLoaded
IsSchemaLoaded()
bool System.Xml.Schema.XmlSchemaSet.IsSchemaLoaded (Uri schemaUri, string targetNamespace, out XmlSchema schema) inline package
Definition at line 1045 of file XmlSchemaSet.cs.
    {
        schema = null;
        if (targetNamespace == null)
        {
            targetNamespace = string.Empty;
        }
        if (GetSchemaByUri(schemaUri, out schema))
        {
            if (!_schemas.ContainsKey(schema.SchemaId) || (targetNamespace.Length != 0 && !(targetNamespace == schema.TargetNamespace)))
            {
                if (schema.TargetNamespace == null)
                {
                    XmlSchema xmlSchema = FindSchemaByNSAndUrl(schemaUri, targetNamespace, null);
                    if (xmlSchema != null && _schemas.ContainsKey(xmlSchema.SchemaId))
                    {
                        schema = xmlSchema;
                    }
                    else
                    {
                        schema = Add(targetNamespace, schema);
                    }
                }
                else if (targetNamespace.Length != 0 && targetNamespace != schema.TargetNamespace)
                {
                    SendValidationEvent(new XmlSchemaException(System.SR.Sch_MismatchTargetNamespaceEx, new string[2] { targetNamespace, schema.TargetNamespace }), XmlSeverityType.Error);
                    schema = null;
                }
                else
                {
                    AddSchemaToSet(schema);
                }
            }
            return true;
        }
        return false;
    }
References System.Xml.Schema.XmlSchemaSet._schemas, System.Add, System.Xml.Schema.XmlSchemaSet.AddSchemaToSet(), System.Collections.SortedList.ContainsKey(), System.Xml.Dictionary, System.Xml.Schema.XmlSchemaSet.FindSchemaByNSAndUrl(), System.Xml.Schema.XmlSchemaSet.GetSchemaByUri(), System.SR.Sch_MismatchTargetNamespaceEx, and System.Xml.Schema.XmlSchemaSet.SendValidationEvent().
Referenced by System.Xml.Schema.XmlSchemaSet.Add(), System.Xml.Schema.XmlSchemaSet.Add(), and System.Xml.Schema.XmlSchemaSet.Add().