Terraria: System.Xml.Schema.XmlSchemaSet.RemoveSchemaFromCaches
RemoveSchemaFromCaches()
void System.Xml.Schema.XmlSchemaSet.RemoveSchemaFromCaches (XmlSchema schema) inline private
Definition at line 1107 of file XmlSchemaSet.cs.
    {
        List<XmlSchema> list = new List<XmlSchema>();
        schema.GetExternalSchemasList(list, schema);
        for (int i = 0; i < list.Count; i++)
        {
            if (list[i].BaseUri != null && list[i].BaseUri.OriginalString.Length != 0)
            {
                _schemaLocations.Remove(list[i].BaseUri);
            }
            ICollection keys = _chameleonSchemas.Keys;
            ArrayList arrayList = new ArrayList();
            foreach (ChameleonKey item in keys)
            {
                if (item.chameleonLocation.Equals(list[i].BaseUri) && (item.originalSchema == null || item.originalSchema == list[i]))
                {
                    arrayList.Add(item);
                }
            }
            for (int j = 0; j < arrayList.Count; j++)
            {
                _chameleonSchemas.Remove(arrayList[j]);
            }
        }
    }
References System.Xml.Schema.XmlSchemaSet._chameleonSchemas, System.Xml.Schema.XmlSchemaSet._schemaLocations, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Xml.Dictionary, System.item, System.Collections.Hashtable.Keys, System.keys, System.list, and System.Collections.Hashtable.Remove().
Referenced by System.Xml.Schema.XmlSchemaSet.Remove(), and System.Xml.Schema.XmlSchemaSet.Reprocess().