Terraria: System.Xml.Schema.XmlSchemaSet.ProcessNewSubstitutionGroups
ProcessNewSubstitutionGroups()
void System.Xml.Schema.XmlSchemaSet.ProcessNewSubstitutionGroups (XmlSchemaObjectTable substitutionGroupsTable, bool resolve) inline private
Definition at line 788 of file XmlSchemaSet.cs.
    {
        foreach (XmlSchemaSubstitutionGroup value in substitutionGroupsTable.Values)
        {
            if (resolve)
            {
                ResolveSubstitutionGroup(value, substitutionGroupsTable);
            }
            XmlQualifiedName examplar = value.Examplar;
            XmlSchemaSubstitutionGroup xmlSchemaSubstitutionGroup2 = (XmlSchemaSubstitutionGroup)substitutionGroups[examplar];
            if (xmlSchemaSubstitutionGroup2 != null)
            {
                for (int i = 0; i < value.Members.Count; i++)
                {
                    if (!xmlSchemaSubstitutionGroup2.Members.Contains(value.Members[i]))
                    {
                        xmlSchemaSubstitutionGroup2.Members.Add(value.Members[i]);
                    }
                }
            }
            else
            {
                AddToTable(substitutionGroups, examplar, value);
            }
        }
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Xml.Schema.XmlSchemaSet.AddToTable(), System.Collections.Generic.Dictionary< TKey, TValue >.Contains(), System.Xml.Schema.XmlSchemaSet.ResolveSubstitutionGroup(), System.Xml.Schema.XmlSchemaSet.substitutionGroups, System.value, and System.Collections.Generic.Dictionary< TKey, TValue >.Values.
Referenced by System.Xml.Schema.XmlSchemaSet.CopyFromCompiledSet().