Terraria: System.Xml.Schema.XmlSchemaSet.Schemas
Schemas() [1/2]
ICollection System.Xml.Schema.XmlSchemaSet.Schemas () inline
Definition at line 617 of file XmlSchemaSet.cs.
    {
        return _schemas.Values;
    }
References System.Xml.Schema.XmlSchemaSet._schemas, and System.Collections.SortedList.Values.
Referenced by System.Xml.Schema.XmlSchemaInference.AddAttribute(), System.Xml.Schema.XmlSchemaInference.AddElement(), System.Xml.Serialization.XmlSchemas.Compile(), System.Xml.Serialization.XmlSchemas.Find(), System.Xml.Schema.XmlSchemaInference.FindGlobalElement(), System.Data.XSDSchema.GetNamespaceFromPrefix(), System.Data.XSDSchema.GetPrefix(), System.Runtime.Serialization.SchemaHelper.GetSchema(), System.Runtime.Serialization.SchemaHelper.GetSchemaElement(), System.Xml.Serialization.XmlSchemas.GetSchemas(), System.Runtime.Serialization.SchemaHelper.GetSchemaType(), System.Runtime.Serialization.SchemaExporter.InvokeSchemaProviderMethod(), System.Xml.Serialization.XmlSchemas.Merge(), System.Xml.Schema.XmlSchemaSet.Remove(), System.Xml.Schema.XmlSchemaSet.Reprocess(), System.Xml.Serialization.SerializableMapping.RetrieveSerializableSchema(), and System.Xml.Serialization.XmlReflectionImporter.SetBase().