Terraria: System.Xml.Schema.XmlSchemaSet.ResolveSubstitutionGroup
ResolveSubstitutionGroup()
void System.Xml.Schema.XmlSchemaSet.ResolveSubstitutionGroup (XmlSchemaSubstitutionGroup substitutionGroup, XmlSchemaObjectTable substTable) inline private
Definition at line 815 of file XmlSchemaSet.cs.
    {
        List<XmlSchemaElement> list = null;
        XmlSchemaElement xmlSchemaElement = (XmlSchemaElement)elements[substitutionGroup.Examplar];
        if (substitutionGroup.Members.Contains(xmlSchemaElement))
        {
            return;
        }
        for (int i = 0; i < substitutionGroup.Members.Count; i++)
        {
            XmlSchemaElement xmlSchemaElement2 = (XmlSchemaElement)substitutionGroup.Members[i];
            XmlSchemaSubstitutionGroup xmlSchemaSubstitutionGroup = (XmlSchemaSubstitutionGroup)substTable[xmlSchemaElement2.QualifiedName];
            if (xmlSchemaSubstitutionGroup == null)
            {
                continue;
            }
            ResolveSubstitutionGroup(xmlSchemaSubstitutionGroup, substTable);
            for (int j = 0; j < xmlSchemaSubstitutionGroup.Members.Count; j++)
            {
                XmlSchemaElement xmlSchemaElement3 = (XmlSchemaElement)xmlSchemaSubstitutionGroup.Members[j];
                if (xmlSchemaElement3 != xmlSchemaElement2)
                {
                    if (list == null)
                    {
                        list = new List<XmlSchemaElement>();
                    }
                    list.Add(xmlSchemaElement3);
                }
            }
        }
        if (list != null)
        {
            for (int k = 0; k < list.Count; k++)
            {
                substitutionGroup.Members.Add(list[k]);
            }
        }
        substitutionGroup.Members.Add(xmlSchemaElement);
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Collections.Generic.Dictionary< TKey, TValue >.Contains(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Xml.Dictionary, System.Xml.Schema.XmlSchemaSet.elements, System.list, and System.Xml.Schema.XmlSchemaSet.ResolveSubstitutionGroup().
Referenced by System.Xml.Schema.XmlSchemaSet.ProcessNewSubstitutionGroups(), and System.Xml.Schema.XmlSchemaSet.ResolveSubstitutionGroup().