Terraria: System.Xml.Schema.XmlSchemaSet.Add
Add() [3/6]
XmlSchema? System.Xml.Schema.XmlSchemaSet.Add (string? targetNamespace, string schemaUri) inline
Definition at line 209 of file XmlSchemaSet.cs.
    {
        if (schemaUri == null || schemaUri.Length == 0)
        {
            throw new ArgumentNullException("schemaUri");
        }
        if (targetNamespace != null)
        {
            targetNamespace = XmlComplianceUtil.CDataNormalize(targetNamespace);
        }
        XmlSchema schema = null;
        lock (InternalSyncObject)
        {
            XmlResolver xmlResolver = _readerSettings.GetXmlResolver();
            if (xmlResolver == null)
            {
                xmlResolver = new XmlUrlResolver();
            }
            Uri schemaUri2 = xmlResolver.ResolveUri(null, schemaUri);
            if (IsSchemaLoaded(schemaUri2, targetNamespace, out schema))
            {
                return schema;
            }
            XmlReader xmlReader = XmlReader.Create(schemaUri, _readerSettings);
            try
            {
                schema = Add(targetNamespace, ParseSchema(targetNamespace, xmlReader));
                while (xmlReader.Read())
                {
                }
                return schema;
            }
            finally
            {
                xmlReader.Close();
            }
        }
    }
References System.Xml.Schema.XmlSchemaSet._readerSettings, System.Add, System.Xml.XmlComplianceUtil.CDataNormalize(), System.Xml.XmlReader.Create(), System.Xml.Dictionary, System.Xml.XmlReaderSettings.GetXmlResolver(), System.Xml.Schema.XmlSchemaSet.InternalSyncObject, System.Xml.Schema.XmlSchemaSet.IsSchemaLoaded(), and System.Xml.Schema.XmlSchemaSet.ParseSchema().
Referenced by System.Xml.Schema.XmlSchemaValidator.XmlSchemaValidator(), System.Xml.Schema.XmlSchemaInference.AddAttribute(), System.Runtime.Serialization.SchemaExporter.AddDefaultTypedDatasetType(), System.Xml.Serialization.XmlSchemas.AddName(), System.Xml.Schema.XmlSchemaValidator.AddSchema(), System.Xml.Schema.XmlSchemaValidator.AddXmlNamespaceSchema(), System.Xml.Serialization.XmlSchemas.Compile(), System.Runtime.Serialization.SchemaHelper.CreateSchema(), System.Xml.Schema.XmlSchemaInference.CreateXmlSchema(), System.Runtime.Serialization.SchemaExporter.ExportSerializationSchema(), and System.Xml.Schema.XmlSchemaValidator.LoadSchema().