Terraria: System.Xml.Schema.XmlSchemaSet.ClearTables
ClearTables()
void System.Xml.Schema.XmlSchemaSet.ClearTables () inline private
Definition at line 891 of file XmlSchemaSet.cs.
    {
        GlobalElements.Clear();
        GlobalAttributes.Clear();
        GlobalTypes.Clear();
        SubstitutionGroups.Clear();
        TypeExtensions.Clear();
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Clear(), System.Xml.Schema.XmlSchemaObjectTable.Clear(), System.Xml.Schema.XmlSchemaSet.GlobalAttributes, System.Xml.Schema.XmlSchemaSet.GlobalElements, System.Xml.Schema.XmlSchemaSet.GlobalTypes, and System.Xml.Schema.XmlSchemaSet.SubstitutionGroups.
Referenced by System.Xml.Schema.XmlSchemaSet.Compile().