Terraria: System.Xml.Schema.XmlSchemaSet.RemoveRecursive
RemoveRecursive()
bool System.Xml.Schema.XmlSchemaSet.RemoveRecursive (XmlSchema schemaToRemove) inline
Definition at line 372 of file XmlSchemaSet.cs.
    {
        if (schemaToRemove == null)
        {
            throw new ArgumentNullException("schemaToRemove");
        }
        if (!_schemas.ContainsKey(schemaToRemove.SchemaId))
        {
            return false;
        }
        lock (InternalSyncObject)
        {
            if (_schemas.ContainsKey(schemaToRemove.SchemaId))
            {
                Hashtable hashtable = new Hashtable();
                hashtable.Add(GetTargetNamespace(schemaToRemove), schemaToRemove);
                for (int i = 0; i < schemaToRemove.ImportedNamespaces.Count; i++)
                {
                    string text = (string)schemaToRemove.ImportedNamespaces[i];
                    if (hashtable[text] == null)
                    {
                        hashtable.Add(text, text);
                    }
                }
                ArrayList arrayList = new ArrayList();
                XmlSchema xmlSchema;
                for (int j = 0; j < _schemas.Count; j++)
                {
                    xmlSchema = (XmlSchema)_schemas.GetByIndex(j);
                    if (xmlSchema != schemaToRemove && !schemaToRemove.ImportedSchemas.Contains(xmlSchema))
                    {
                        arrayList.Add(xmlSchema);
                    }
                }
                xmlSchema = null;
                for (int k = 0; k < arrayList.Count; k++)
                {
                    xmlSchema = (XmlSchema)arrayList[k];
                    if (xmlSchema.ImportedNamespaces.Count <= 0)
                    {
                        continue;
                    }
                    foreach (string key in hashtable.Keys)
                    {
                        if (xmlSchema.ImportedNamespaces.Contains(key))
{
                            SendValidationEvent(new XmlSchemaException(System.SR.Sch_SchemaNotRemoved, string.Empty), XmlSeverityType.Warning);
                            return false;
                        }
                    }
                }
                Remove(schemaToRemove, forceCompile: true);
                for (int l = 0; l < schemaToRemove.ImportedSchemas.Count; l++)
                {
                    XmlSchema schema = (XmlSchema)schemaToRemove.ImportedSchemas[l];
                    Remove(schema, forceCompile: true);
                }
                return true;
            }
        }
        return false;
    }
References System.Xml.Schema.XmlSchemaSet._schemas, System.Collections.Hashtable.Add(), System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Collections.Generic.Dictionary< TKey, TValue >.Contains(), System.Collections.SortedList.ContainsKey(), System.Collections.SortedList.Count, System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Xml.Dictionary, System.Collections.SortedList.GetByIndex(), System.Xml.Schema.XmlSchemaSet.GetTargetNamespace(), System.Xml.Schema.XmlSchemaSet.InternalSyncObject, System.key, System.Collections.Hashtable.Keys, System.Xml.Remove, System.SR.Sch_SchemaNotRemoved, System.Xml.Schema.XmlSchemaSet.SendValidationEvent(), and System.text.
Referenced by System.Xml.Schema.XmlSchemaSet.Add(), and System.Xml.Schema.XmlSchemaValidator.AddSchema().