Terraria: System.Xml.Schema.XmlSchemaSet.Reprocess
Reprocess()
XmlSchema System.Xml.Schema.XmlSchemaSet.Reprocess (XmlSchema schema) inline
Definition at line 541 of file XmlSchemaSet.cs.
    {
        if (schema == null)
        {
            throw new ArgumentNullException("schema");
        }
        if (!_schemas.ContainsKey(schema.SchemaId))
        {
            throw new ArgumentException(System.SR.Sch_SchemaDoesNotExist, "schema");
        }
        XmlSchema result = schema;
        lock (InternalSyncObject)
        {
            RemoveSchemaFromGlobalTables(schema);
            RemoveSchemaFromCaches(schema);
            if (schema.BaseUri != null)
            {
                _schemaLocations.Remove(schema.BaseUri);
            }
            string targetNamespace = GetTargetNamespace(schema);
            if (Schemas(targetNamespace).Count == 0)
            {
                _targetNamespaces.Remove(targetNamespace);
            }
            _isCompiled = false;
            _compileAll = true;
            if (schema.ErrorCount != 0)
            {
                return result;
            }
            if (PreprocessSchema(ref schema, schema.TargetNamespace))
            {
                if (_targetNamespaces[targetNamespace] == null)
                {
                    _targetNamespaces.Add(targetNamespace, targetNamespace);
                }
                if (_schemaForSchema == null && targetNamespace == "http://www.w3.org/2001/XMLSchema" && schema.SchemaTypes[DatatypeImplementation.QnAnyType] != null)
                {
                    _schemaForSchema = schema;
                }
                for (int i = 0; i < schema.ImportedSchemas.Count; i++)
                {
                    XmlSchema xmlSchema = (XmlSchema)schema.ImportedSchemas[i];
                    if (!_schemas.ContainsKey(xmlSchema.SchemaId))
                    {
                        _schemas.Add(xmlSchema.SchemaId, xmlSchema);
                    }
                    targetNamespace = GetTargetNamespace(xmlSchema);
                    if (_targetNamespaces[targetNamespace] == null)
                    {
                        _targetNamespaces.Add(targetNamespace, targetNamespace);
                    }
                    if (_schemaForSchema == null && targetNamespace == "http://www.w3.org/2001/XMLSchema" && schema.SchemaTypes[DatatypeImplementation.QnAnyType] != null)
                    {
                        _schemaForSchema = schema;
                    }
                }
                return schema;
            }
            return result;
        }
    }
References System.Xml.Schema.XmlSchemaSet._compileAll, System.Xml.Schema.XmlSchemaSet._isCompiled, System.Xml.Schema.XmlSchemaSet._schemaForSchema, System.Xml.Schema.XmlSchemaSet._schemaLocations, System.Xml.Schema.XmlSchemaSet._schemas, System.Xml.Schema.XmlSchemaSet._targetNamespaces, System.Collections.SortedList.Add(), System.Collections.Hashtable.Add(), System.Xml.ArgumentException, System.Collections.SortedList.ContainsKey(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Xml.Schema.XmlSchemaSet.Count, System.Xml.Dictionary, System.Xml.Schema.XmlSchemaSet.GetTargetNamespace(), System.Xml.Schema.XmlSchemaSet.InternalSyncObject, System.Xml.Schema.XmlSchemaSet.PreprocessSchema(), System.Xml.Schema.DatatypeImplementation.QnAnyType, System.Collections.Hashtable.Remove(), System.Xml.Schema.XmlSchemaSet.RemoveSchemaFromCaches(), System.Xml.Schema.XmlSchemaSet.RemoveSchemaFromGlobalTables(), System.SR.Sch_SchemaDoesNotExist, and System.Xml.Schema.XmlSchemaSet.Schemas().
Referenced by System.Runtime.Serialization.SchemaExporter.AddDefaultDatasetType(), System.Runtime.Serialization.SchemaExporter.AddDefaultTypedDatasetType(), System.Runtime.Serialization.SchemaExporter.AddDefaultXmlType(), System.Xml.Serialization.XmlSchemas.AddName(), System.Runtime.Serialization.SchemaExporter.ExportDataContract(), and System.Xml.Schema.XmlSchemaInference.InferSchema1().