Terraria: Microsoft.Win32.OAVariantLib.ChangeType
ChangeType()
static Variant Microsoft.Win32.OAVariantLib.ChangeType (Variant source, Type targetClass, short options, CultureInfo culture) inline static package
Definition at line 37 of file OAVariantLib.cs.
    {
        if (targetClass == null)
        {
            throw new ArgumentNullException("targetClass");
        }
        if (culture == null)
        {
            throw new ArgumentNullException("culture");
        }
        Variant result = default(Variant);
        ChangeTypeEx(ref result, ref source, culture.LCID, targetClass.TypeHandle.Value, GetCVTypeFromClass(targetClass), options);
        return result;
    }
References Microsoft.Win32.OAVariantLib.ChangeTypeEx(), System.culture, Microsoft.Win32.OAVariantLib.GetCVTypeFromClass(), System.options, System.source, System.Type.TypeHandle, and System.RuntimeTypeHandle.Value.
Referenced by System.OleAutBinder.ChangeType().