Terraria: Internal.Cryptography.CngAlgorithmCore.GetOrGenerateKey
GetOrGenerateKey() [1/2]
CngKey Internal.Cryptography.CngAlgorithmCore.GetOrGenerateKey (ECCurve? curve) inline
Definition at line 68 of file CngAlgorithmCore.cs.
    {
        ThrowIfDisposed();
        if (_lazyKey != null)
        {
            return _lazyKey;
        }
        CngKeyCreationParameters cngKeyCreationParameters = new CngKeyCreationParameters
        {
            ExportPolicy = CngExportPolicies.AllowPlaintextExport
        };
        if (curve.Value.IsNamed)
        {
            cngKeyCreationParameters.Parameters.Add(CngKey.GetPropertyFromNamedCurve(curve.Value));
        }
        else
        {
            if (!curve.Value.IsPrime)
            {
                throw new PlatformNotSupportedException(System.SR.Format(System.SR.Cryptography_CurveNotSupported, curve.Value.CurveType.ToString()));
            }
            ECCurve curve2 = curve.Value;
            byte[] primeCurveParameterBlob = System.Security.Cryptography.ECCng.GetPrimeCurveParameterBlob(ref curve2);
            CngProperty item = new CngProperty("ECCParameters", primeCurveParameterBlob, CngPropertyOptions.None);
            cngKeyCreationParameters.Parameters.Add(item);
        }
        try
        {
            _lazyKey = CngKey.Create(DefaultKeyType ?? CngAlgorithm.ECDsa, null, cngKeyCreationParameters);
        }
        catch (CryptographicException ex)
        {
            global::Interop.NCrypt.ErrorCode hResult = (global::Interop.NCrypt.ErrorCode)ex.HResult;
            if ((curve.Value.IsNamed && hResult == global::Interop.NCrypt.ErrorCode.NTE_INVALID_PARAMETER) || hResult == global::Interop.NCrypt.ErrorCode.NTE_NOT_SUPPORTED)
            {
                throw new PlatformNotSupportedException(System.SR.Format(System.SR.Cryptography_CurveNotSupported, curve.Value.Oid.FriendlyName), ex);
            }
            throw;
        }
        return _lazyKey;
    }
References Internal.Cryptography.CngAlgorithmCore._lazyKey, System.Collections.ObjectModel.Collection< T >.Add(), System.Security.Cryptography.CngKey.Create(), System.SR.Cryptography_CurveNotSupported, System.Security.Cryptography.ECCurve.CurveType, Internal.Cryptography.CngAlgorithmCore.DefaultKeyType, System.Security.Cryptography.CngAlgorithm.ECDsa, System.SR.Format(), System.Security.Cryptography.Oid.FriendlyName, System.Security.Cryptography.ECCng.GetPrimeCurveParameterBlob(), System.Security.Cryptography.CngKey.GetPropertyFromNamedCurve(), System.Exception.HResult, System.Security.Cryptography.ECCurve.IsNamed, System.Security.Cryptography.ECCurve.IsPrime, System.item, System.Security.Cryptography.ECCurve.Oid, System.Security.Cryptography.CngKeyCreationParameters.Parameters, and Internal.Cryptography.CngAlgorithmCore.ThrowIfDisposed().