Terraria: Internal.Cryptography.CngAlgorithmCore.GetOrGenerateKey
GetOrGenerateKey() [2/2]
CngKey Internal.Cryptography.CngAlgorithmCore.GetOrGenerateKey (int keySize, CngAlgorithm algorithm) inline
Definition at line 48 of file CngAlgorithmCore.cs.
    {
        ThrowIfDisposed();
        if (_lazyKey != null && _lazyKey.KeySize != keySize)
        {
            DisposeKey();
        }
        if (_lazyKey == null)
        {
            CngKeyCreationParameters cngKeyCreationParameters = new CngKeyCreationParameters
            {
                ExportPolicy = CngExportPolicies.AllowPlaintextExport
            };
            CngProperty item = new CngProperty("Length", BitConverter.GetBytes(keySize), CngPropertyOptions.None);
            cngKeyCreationParameters.Parameters.Add(item);
            _lazyKey = CngKey.Create(algorithm, null, cngKeyCreationParameters);
        }
        return _lazyKey;
    }
References Internal.Cryptography.CngAlgorithmCore._lazyKey, System.Collections.ObjectModel.Collection< T >.Add(), System.Security.Cryptography.CngKey.Create(), Internal.Cryptography.CngAlgorithmCore.DisposeKey(), System.BitConverter.GetBytes(), System.item, System.Security.Cryptography.CngKey.KeySize, System.Security.Cryptography.CngKeyCreationParameters.Parameters, and Internal.Cryptography.CngAlgorithmCore.ThrowIfDisposed().
Referenced by System.Security.Cryptography.ECDiffieHellmanCng.GenerateKey(), System.Security.Cryptography.ECDsaCng.GenerateKey(), System.Security.Cryptography.ECDiffieHellmanCng.GetKey(), and System.Security.Cryptography.ECDsaCng.GetKey().