Terraria: Internal.Cryptography.CngAlgorithmCore.ThrowIfDisposed
ThrowIfDisposed()
void Internal.Cryptography.CngAlgorithmCore.ThrowIfDisposed () inline package
Definition at line 123 of file CngAlgorithmCore.cs.
    {
        if (_disposed)
        {
            throw new ObjectDisposedException(_disposedName);
        }
    }
References Internal.Cryptography.CngAlgorithmCore._disposed, and Internal.Cryptography.CngAlgorithmCore._disposedName.
Referenced by Internal.Cryptography.CngAlgorithmCore.GetOrGenerateKey(), Internal.Cryptography.CngAlgorithmCore.GetOrGenerateKey(), Internal.Cryptography.CngAlgorithmCore.IsKeyGeneratedNamedCurve(), Internal.Cryptography.CngAlgorithmCore.SetKey(), System.Security.Cryptography.DSACng.ThrowIfDisposed(), System.Security.Cryptography.ECDiffieHellmanCng.ThrowIfDisposed(), System.Security.Cryptography.ECDsaCng.ThrowIfDisposed(), and System.Security.Cryptography.RSACng.ThrowIfDisposed().