Terraria: Terraria.WorldGen.countTiles
countTiles()
static int Terraria.WorldGen.countTiles (int x, int y, bool jungle = false, bool lavaOk = false) inline static
Definition at line 5679 of file WorldGen.cs.
    {
        numTileCount = 0;
        shroomCount = 0;
        lavaCount = 0;
        iceCount = 0;
        sandCount = 0;
        rockCount = 0;
        CountedTiles.Clear();
        nextCount(x, y, jungle, lavaOk);
        return numTileCount;
    }
References Terraria.WorldGen.CountedTiles, Terraria.WorldGen.iceCount, Terraria.WorldGen.lavaCount, Terraria.WorldGen.nextCount(), Terraria.WorldGen.numTileCount, Terraria.WorldGen.rockCount, Terraria.WorldGen.sandCount, and Terraria.WorldGen.shroomCount.
Referenced by Terraria.WorldGen.gemCave(), and Terraria.GameContent.Biomes.DeadMansChestBiome.IsAGoodSpot().