Terraria: Terraria.WorldGen.BlockBelowMakesSandFall
BlockBelowMakesSandFall()
static bool Terraria.WorldGen.BlockBelowMakesSandFall (int i, int j) inline static
    {
        bool result = false;
        if (j >= Main.maxTilesY - 1)
        {
            return false;
        }
        Tile tile = Main.tile[i, j + 1];
        if (tile == null)
        {
            return false;
        }
        if (!tile.nactive())
        {
            result = true;
        }
        else if (!Main.tile[i, j + 2].nactive() && (!tile.active() || !Main.tileSolid[tile.type]))
        {
            result = true;
        }
        else if (tile.active() && tile.type == 165)
        {
            result = true;
        }
        return result;
    }
References Terraria.Tile.active(), Terraria.Main.maxTilesY, Terraria.Tile.nactive(), Terraria.Main.tile, Terraria.Main.tileSolid, and Terraria.Tile.type.
Referenced by Terraria.Projectile.Kill().