Terraria: Terraria.WorldGen.dropMeteor
dropMeteor()
static void Terraria.WorldGen.dropMeteor () inline static
    {
        bool flag = true;
        if (Main.netMode == 1)
        {
            return;
        }
        for (int i = 0; i < 255; i++)
        {
            if (Main.player[i].active)
            {
                flag = false;
                break;
            }
        }
        int num = 0;
        double num2 = (double)Main.maxTilesX / 4200.0;
        int num3 = (int)(400.0 * num2);
        for (int j = 5; j < Main.maxTilesX - 5; j++)
        {
            for (int k = 5; (double)k < Main.worldSurface; k++)
            {
                if (Main.tile[j, k].active() && Main.tile[j, k].type == 37)
                {
                    num++;
                    if (num > num3)
                    {
                        return;
                    }
                }
            }
        }
        double num4 = 600.0;
        int num5 = 0;
        while (!flag)
        {
            double num6 = (double)Main.maxTilesX * 0.08;
            int num7 = Main.rand.Next(150, Main.maxTilesX - 150);
            while ((double)num7 > (double)Main.spawnTileX - num6 && (double)num7 < (double)Main.spawnTileX + num6)
            {
                num7 = Main.rand.Next(150, Main.maxTilesX - 150);
            }
            for (int l = (int)(Main.worldSurface * 0.3); l < Main.maxTilesY; l++)
            {
                Tile tile = Main.tile[num7, l];
                if (!tile.active() || !Main.tileSolid[tile.type] || TileID.Sets.Platforms[tile.type])
                {
                    continue;
                }
                int num8 = 0;
                int num9 = 15;
                for (int m = num7 - num9; m < num7 + num9; m++)
                {
                    for (int n = l - num9; n < l + num9; n++)
                    {
                        if (SolidTile(m, n))
{
                            num8++;
                            if (Main.tile[m, n].type == 189 || Main.tile[m, n].type == 202)
{
                                num8 -= 100;
                            }
                        }
                        else if (Main.tile[m, n].liquid > 0)
{
                            num8--;
                        }
                    }
                }
                if ((double)num8 >= num4)
                {
                    flag = meteor(num7, l);
                    if (!flag)
                    {
                    }
                }
                else
                {
                    num4 -= 0.5;
                }
                break;
            }
            num5++;
            if (num4 < 100.0 || num5 >= Main.maxTilesX * 5)
            {
                break;
            }
        }
    }
References Terraria.Entity.active, Terraria.Tile.active(), Terraria.Tile.liquid, Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.WorldGen.meteor(), Terraria.Main.netMode, Terraria.Utilities.UnifiedRandom.Next(), Terraria.ID.TileID.Sets.Platforms, Terraria.Main.player, Terraria.Main.rand, Terraria.Enums.SolidTile, Terraria.Main.spawnTileX, Terraria.Main.tile, Terraria.Main.tileSolid, Terraria.Tile.type, and Terraria.Main.worldSurface.
Referenced by Terraria.Main.HandleMeteorFall().