Terraria: Terraria.WorldGen.PlaceDresserDirect
PlaceDresserDirect()
static void Terraria.WorldGen.PlaceDresserDirect (int x, int y, ushort type, int style, int id) inline static
    {
        Chest.CreateChest(x - 1, y - 1, id);
        for (int i = -1; i <= 1; i++)
        {
            for (int j = -1; j <= 0; j++)
            {
                if (Main.tile[x + i, y + j] == null)
                {
                    Main.tile[x + i, y + j] = new Tile();
                }
            }
        }
        short num = (short)(style * 54);
        Main.tile[x - 1, y - 1].active(active: true);
        Main.tile[x - 1, y - 1].frameY = 0;
        Main.tile[x - 1, y - 1].frameX = num;
        Main.tile[x - 1, y - 1].type = type;
        Main.tile[x, y - 1].active(active: true);
        Main.tile[x, y - 1].frameY = 0;
        Main.tile[x, y - 1].frameX = (short)(num + 18);
        Main.tile[x, y - 1].type = type;
        Main.tile[x + 1, y - 1].active(active: true);
        Main.tile[x + 1, y - 1].frameY = 0;
        Main.tile[x + 1, y - 1].frameX = (short)(num + 36);
        Main.tile[x + 1, y - 1].type = type;
        Main.tile[x - 1, y].active(active: true);
        Main.tile[x - 1, y].frameY = 18;
        Main.tile[x - 1, y].frameX = num;
        Main.tile[x - 1, y].type = type;
        Main.tile[x, y].active(active: true);
        Main.tile[x, y].frameY = 18;
        Main.tile[x, y].frameX = (short)(num + 18);
        Main.tile[x, y].type = type;
        Main.tile[x + 1, y].active(active: true);
        Main.tile[x + 1, y].frameY = 18;
        Main.tile[x + 1, y].frameX = (short)(num + 36);
        Main.tile[x + 1, y].type = type;
    }
References Terraria.Tile.active(), Terraria.Chest.CreateChest(), Terraria.Tile.frameX, Terraria.Tile.frameY, Terraria.DataStructures.Tile, Terraria.Main.tile, and Terraria.Tile.type.
Referenced by Terraria.MessageBuffer.GetData().