Terraria: Terraria.WorldGen.GetGemTreeFoliageData
GetGemTreeFoliageData()
static bool Terraria.WorldGen.GetGemTreeFoliageData (int i, int j, int xoffset, ref int treeFrame, ref int treeStyle, out int floorY, out int topTextureFrameWidth, out int topTextureFrameHeight) inline static
Definition at line 53502 of file WorldGen.cs.
    {
        Tile tile = Main.tile[i, j];
        int num = i + xoffset;
        topTextureFrameWidth = 116;
        topTextureFrameHeight = 96;
        floorY = j;
        if (!GrowTreeSettings.Profiles.TryGetFromTreeId(tile.type, out var profile))
        {
            return false;
        }
        for (int k = 0; k < 100; k++)
        {
            floorY = j + k;
            Tile tile2 = Main.tile[num, floorY];
            if (tile2 == null)
            {
                return false;
            }
            if (profile.GroundTest(tile2.type))
            {
                switch (tile.type)
                {
                case 583:
                    treeStyle = 22;
                    return true;
                case 584:
                    treeStyle = 23;
                    return true;
                case 585:
                    treeStyle = 24;
                    return true;
                case 586:
                    treeStyle = 25;
                    return true;
                case 587:
                    treeStyle = 26;
                    return true;
                case 588:
                    treeStyle = 27;
                    return true;
                case 589:
                    treeStyle = 28;
                    return true;
                }
            }
        }
        return false;
    }
References Terraria.Main.tile, Terraria.WorldGen.GrowTreeSettings.Profiles.TryGetFromTreeId(), and Terraria.Tile.type.
Referenced by Terraria.GameContent.Drawing.TileDrawing.DrawTrees(), and Terraria.GameContent.Drawing.TileDrawing.MakeExtraPreparations().