Terraria: System.Data.XmlToDatasetMap.BuildIdentityMap
BuildIdentityMap() [4/4]
void System.Data.XmlToDatasetMap.BuildIdentityMap (XmlNameTable nameTable, DataTable dataTable) inline private
Definition at line 295 of file XmlToDatasetMap.cs.
    {
        ArrayList selfAndDescendants = GetSelfAndDescendants(dataTable);
        _tableSchemaMap = new XmlNodeIdHashtable(selfAndDescendants.Count);
        foreach (DataTable item in selfAndDescendants)
        {
            TableSchemaInfo tableSchemaInfo = AddTableSchema(nameTable, item);
            if (tableSchemaInfo == null)
            {
                continue;
            }
            foreach (DataColumn column in item.Columns)
            {
                if (IsMappedColumn(column))
                {
                    AddColumnSchema(nameTable, column, tableSchemaInfo.ColumnsSchemaMap);
                }
            }
            foreach (DataRelation childRelation in item.ChildRelations)
            {
                if (childRelation.Nested)
                {
                    string array = XmlConvert.EncodeLocalName(childRelation.ChildTable.TableName);
                    string text = nameTable.Get(array);
                    if (text == null)
                    {
                        text = nameTable.Add(array);
                    }
                    string text2 = nameTable.Get(childRelation.ChildTable.Namespace);
                    if (text2 == null)
                    {
                        text2 = nameTable.Add(childRelation.ChildTable.Namespace);
                    }
                    XmlNodeIdentety key = new XmlNodeIdentety(text, text2);
                    tableSchemaInfo.ColumnsSchemaMap[key] = childRelation.ChildTable;
                }
            }
        }
    }
References System.Data.XmlToDatasetMap._tableSchemaMap, System.Data.XmlToDatasetMap.AddColumnSchema(), System.Data.XmlToDatasetMap.AddTableSchema(), System.array, System.Xml.Dictionary, System.Xml.XmlConvert.EncodeLocalName(), System.Data.XmlToDatasetMap.GetSelfAndDescendants(), System.Data.XmlToDatasetMap.IsMappedColumn(), System.item, System.key, and System.text.