Terraria: Terraria.WorldGen.Pyramid
Pyramid()
static bool Terraria.WorldGen.Pyramid (int i, int j) inline static
    {
        ushort num = 151;
        if (Main.tile[i, j].type == 151 || Main.tile[i, j].wall == 151)
        {
            return false;
        }
        int num2 = j - genRand.Next(0, 7);
        int num3 = genRand.Next(9, 13);
        int num4 = 1;
        int num5 = j + genRand.Next(75, 125);
        for (int k = num2; k < num5; k++)
        {
            for (int l = i - num4; l < i + num4 - 1; l++)
            {
                Main.tile[l, k].type = num;
                Main.tile[l, k].active(active: true);
                Main.tile[l, k].halfBrick(halfBrick: false);
                Main.tile[l, k].slope(0);
            }
            num4++;
        }
        for (int m = i - num4 - 5; m <= i + num4 + 5; m++)
        {
            for (int n = j - 1; n <= num5 + 1; n++)
            {
                bool flag = true;
                for (int num6 = m - 1; num6 <= m + 1; num6++)
                {
                    for (int num7 = n - 1; num7 <= n + 1; num7++)
                    {
                        if (Main.tile[num6, num7].type != num)
{
                            flag = false;
                        }
                    }
                }
                if (flag)
                {
                    Main.tile[m, n].wall = 34;
                    SquareWallFrame(m, n);
                }
            }
        }
        int num8 = 1;
        if (genRand.Next(2) == 0)
        {
            num8 = -1;
        }
        int num9 = i - num3 * num8;
        int num10 = j + num3;
        int num11 = genRand.Next(5, 8);
        bool flag2 = true;
        int num12 = genRand.Next(20, 30);
        while (flag2)
        {
            flag2 = false;
            bool flag3 = false;
            for (int num13 = num10; num13 <= num10 + num11; num13++)
            {
                int num14 = num9;
                if (Main.tile[num14, num13 - 1].type == 53)
                {
                    flag3 = true;
                }
                if (Main.tile[num14, num13].type == num)
                {
                    Main.tile[num14, num13 + 1].wall = 34;
                    Main.tile[num14 + num8, num13].wall = 34;
                    Main.tile[num14, num13].active(active: false);
                    flag2 = true;
                }
                if (flag3)
                {
                    Main.tile[num14, num13].type = 53;
                    Main.tile[num14, num13].active(active: true);
                    Main.tile[num14, num13].halfBrick(halfBrick: false);
                    Main.tile[num14, num13].slope(0);
                }
            }
            num9 -= num8;
        }
        num9 = i - num3 * num8;
        bool flag4 = true;
        bool flag5 = false;
        flag2 = true;
        while (flag2)
        {
            for (int num15 = num10; num15 <= num10 + num11; num15++)
            {
                int num16 = num9;
                Main.tile[num16, num15].active(active: false);
            }
            num9 += num8;
            num10++;
            num12--;
            if (num10 >= num5 - num11 * 2)
            {
                num12 = 10;
            }
            if (num12 <= 0)
            {
                bool flag6 = false;
                if (!flag4 && !flag5)
                {
                    flag5 = true;
                    flag6 = true;
                    int num17 = genRand.Next(7, 13);
                    int num18 = genRand.Next(23, 28);
                    int num19 = num18;
                    int num20 = num9;
                    while (num18 > 0)
                    {
                        for (int num21 = num10 - num17 + num11; num21 <= num10 + num11; num21++)
{
                            if (num18 == num19 || num18 == 1)
{
                                if (num21 >= num10 - num17 + num11 + 2)
{
                                    Main.tile[num9, num21].active(active: false);
                                }
                            }
                            else if (num18 == num19 - 1 || num18 == 2 || num18 == num19 - 2 || num18 == 3)
{
                                if (num21 >= num10 - num17 + num11 + 1)
{
                                    Main.tile[num9, num21].active(active: false);
                                }
                            }
                            else
{
                                Main.tile[num9, num21].active(active: false);
                            }
                        }
                        num18--;
                        num9 += num8;
                    }
                    int num22 = num9 - num8;
                    int num23 = num22;
                    int num24 = num20;
                    if (num22 > num20)
                    {
                        num23 = num20;
                        num24 = num22;
                    }
                    int num25 = genRand.Next(3);
                    if (num25 == 0)
                    {
                        num25 = genRand.Next(3);
                    }
                    if (Main.tenthAnniversaryWorld && num25 == 0)
                    {
                        num25 = 1;
                    }
                    switch (num25)
                    {
                    case 0:
                        num25 = 848;
                        break;
                    case 1:
                        num25 = 857;
                        break;
                    case 2:
                        num25 = 934;
                        break;
                    }
                    AddBuriedChest((num23 + num24) / 2, num10, num25, notNearOtherChests: false, 1, trySlope: false, 0);
                    int num26 = genRand.Next(1, 10);
                    for (int num27 = 0; num27 < num26; num27++)
                    {
                        int i2 = genRand.Next(num23, num24);
                        int j2 = num10 + num11;
                        PlaceSmallPile(i2, j2, genRand.Next(16, 19), 1, 185);
                    }
                    PlaceTile(num23 + 2, num10 - num17 + num11 + 1, 91, mute: true, forced: false, -1, genRand.Next(4, 7));
                    PlaceTile(num23 + 3, num10 - num17 + num11, 91, mute: true, forced: false, -1, genRand.Next(4, 7));
                    PlaceTile(num24 - 2, num10 - num17 + num11 + 1, 91, mute: true, forced: false, -1, genRand.Next(4, 7));
                    PlaceTile(num24 - 3, num10 - num17 + num11, 91, mute: true, forced: false, -1, genRand.Next(4, 7));
                    for (int num28 = num23; num28 <= num24; num28++)
                    {
                        PlacePot(num28, num10 + num11, 28, genRand.Next(25, 28));
                    }
                }
                if (flag4)
                {
                    flag4 = false;
                    num8 *= -1;
                    num12 = genRand.Next(15, 20);
                }
                else if (flag6)
                {
                    num12 = genRand.Next(10, 15);
                }
                else
                {
                    num8 *= -1;
                    num12 = genRand.Next(20, 40);
                }
            }
            if (num10 >= num5 - num11)
            {
                flag2 = false;
            }
        }
        int num29 = genRand.Next(100, 200);
        int num30 = genRand.Next(500, 800);
        flag2 = true;
        int num31 = num11;
        num12 = genRand.Next(10, 50);
        if (num8 == 1)
        {
            num9 -= num31;
        }
        int num32 = genRand.Next(5, 10);
        while (flag2)
        {
            num29--;
            num30--;
            num12--;
            for (int num33 = num9 - num32 - genRand.Next(0, 2); num33 <= num9 + num31 + num32 + genRand.Next(0, 2); num33++)
            {
                int num34 = num10;
                if (num33 >= num9 && num33 <= num9 + num31)
                {
                    Main.tile[num33, num34].active(active: false);
                }
                else
                {
                    Main.tile[num33, num34].type = num;
                    Main.tile[num33, num34].active(active: true);
                    Main.tile[num33, num34].halfBrick(halfBrick: false);
                    Main.tile[num33, num34].slope(0);
                }
                if (num33 >= num9 - 1 && num33 <= num9 + 1 + num31)
                {
                    Main.tile[num33, num34].wall = 34;
                }
            }
            num10++;
            num9 += num8;
            if (num29 <= 0)
            {
                flag2 = false;
                for (int num35 = num9 + 1; num35 <= num9 + num31 - 1; num35++)
                {
                    if (Main.tile[num35, num10].active())
                    {
                        flag2 = true;
                    }
                }
            }
            if (num12 < 0)
            {
                num12 = genRand.Next(10, 50);
                num8 *= -1;
            }
            if (num30 <= 0)
            {
                flag2 = false;
            }
        }
        return true;
    }
References Terraria.Tile.active(), Terraria.Tile.halfBrick(), Terraria.Tile.slope(), Terraria.Main.tenthAnniversaryWorld, Terraria.Main.tile, Terraria.Tile.type, and Terraria.Tile.wall.