Terraria: Terraria.WorldGen.GrowDungeonTree_MakePassage
GrowDungeonTree_MakePassage()
static void Terraria.WorldGen.GrowDungeonTree_MakePassage (int j, int W, ref int minl, ref int minr, bool noSecretRoom = false) inline static private
    {
        int num = minl;
        int num2 = minr;
        _ = (minl + minr) / 2;
        int num3 = 5;
        int num4 = j - 6;
        int num5 = 0;
        bool flag = true;
        genRand.Next(5, 16);
        while (true)
        {
            num4++;
            if (num4 > GenVars.dungeonY - 5)
            {
                break;
            }
            int num6 = (minl + minr) / 2;
            int num7 = 1;
            if (num4 > j && W <= 4)
            {
                num7++;
            }
            for (int i = minl - num7; i <= minr + num7; i++)
            {
                if (i > num6 - 2 && i <= num6 + 1)
                {
                    if (num4 > j - 4)
                    {
                        if (Main.tile[i, num4].type != 19 && Main.tile[i, num4].type != 15 && Main.tile[i, num4].type != 304 && Main.tile[i, num4].type != 21 && Main.tile[i, num4].type != 10 && Main.tile[i, num4 - 1].type != 15 && Main.tile[i, num4 - 1].type != 304 && Main.tile[i, num4 - 1].type != 21 && Main.tile[i, num4 - 1].type != 10 && Main.tile[i, num4 + 1].type != 10)
{
                            Main.tile[i, num4].active(active: false);
                        }
                        if (!Main.wallDungeon[Main.tile[i, num4].wall])
{
                            Main.tile[i, num4].wall = 244;
                        }
                        if (!Main.wallDungeon[Main.tile[i - 1, num4].wall] && (Main.tile[i - 1, num4].wall > 0 || (double)num4 >= Main.worldSurface))
{
                            Main.tile[i - 1, num4].wall = 244;
                        }
                        if (!Main.wallDungeon[Main.tile[i + 1, num4].wall] && (Main.tile[i + 1, num4].wall > 0 || (double)num4 >= Main.worldSurface))
{
                            Main.tile[i + 1, num4].wall = 244;
                        }
                        if (num4 == j && i > num6 - 2 && i <= num6 + 1)
{
                            Main.tile[i, num4 + 1].active(active: false);
                            PlaceTile(i, num4 + 1, 19, mute: true, forced: false, -1, 23);
                        }
                    }
                }
                else
                {
                    if (Main.tile[i, num4].type != 15 && Main.tile[i, num4].type != 304 && Main.tile[i, num4].type != 21 && Main.tile[i, num4].type != 10 && Main.tile[i - 1, num4].type != 10 && Main.tile[i + 1, num4].type != 10)
                    {
                        if (!Main.wallDungeon[Main.tile[i, num4].wall])
{
                            Main.tile[i, num4].type = 191;
                            Main.tile[i, num4].active(active: true);
                            Main.tile[i, num4].halfBrick(halfBrick: false);
                        }
                        if (Main.tile[i - 1, num4].type == 40)
{
                            Main.tile[i - 1, num4].type = 0;
                        }
                        if (Main.tile[i + 1, num4].type == 40)
{
                            Main.tile[i + 1, num4].type = 0;
                        }
                    }
                    if (num4 <= j && num4 > j - 4 && i > minl - num7 && i <= minr + num7 - 1)
                    {
                        Main.tile[i, num4].wall = 244;
                    }
                }
                if (!gen)
                {
                    SquareTileFrame(i, num4);
                    SquareWallFrame(i, num4);
                }
            }
            num5++;
            if (num5 < 6)
            {
                continue;
            }
            num5 = 0;
            int num8 = genRand.Next(3);
            if (num8 == 0)
            {
                num8 = -1;
            }
            if (flag)
            {
                num8 = 2;
            }
            if (num8 == -1 && Main.tile[minl - num3, num4].wall == 244)
            {
                num8 = 1;
            }
            else if (num8 == 1 && Main.tile[minr + num3, num4].wall == 244)
            {
                num8 = -1;
            }
            if (num8 == 2)
            {
                flag = false;
                int num9 = 23;
                if (Main.wallDungeon[Main.tile[minl, num4 + 1].wall] || Main.wallDungeon[Main.tile[minl + 1, num4 + 1].wall] || Main.wallDungeon[Main.tile[minl + 2, num4 + 1].wall])
                {
                    num9 = 12;
                }
                if (!SolidTile(minl - 1, num4 + 1) && !SolidTile(minr + 1, num4 + 1) && num9 == 12)
                {
                    continue;
                }
                for (int k = minl; k <= minr; k++)
                {
                    if (k > num6 - 2 && k <= num6 + 1)
                    {
                        Main.tile[k, num4 + 1].active(active: false);
                        Main.tile[k, num4 + 1].halfBrick(halfBrick: false);
                        Main.tile[k, num4 + 1].slope(0);
                        PlaceTile(k, num4 + 1, 19, mute: true, forced: false, -1, num9);
                    }
                }
            }
            else
            {
                minl += num8;
                minr += num8;
            }
        }
        minl = num;
        minr = num2;
        _ = (minl + minr) / 2;
        for (int l = minl; l <= minr; l++)
        {
            for (int m = j - 3; m <= j; m++)
            {
                Main.tile[l, m].active(active: false);
                if (!Main.wallDungeon[Main.tile[l, m].wall])
                {
                    Main.tile[l, m].wall = 244;
                }
            }
        }
    }
References Terraria.Tile.active(), Terraria.WorldBuilding.GenVars.dungeonY, Terraria.Tile.halfBrick(), Terraria.Tile.slope(), Terraria.Enums.SolidTile, Terraria.Main.tile, Terraria.Tile.type, Terraria.Tile.wall, Terraria.Main.wallDungeon, and Terraria.Main.worldSurface.