Terraria: Terraria.WorldGen.PlacePot
PlacePot()
static bool Terraria.WorldGen.PlacePot (int x, int y, ushort type = 28, int style = 0) inline static
Definition at line 45687 of file WorldGen.cs.
    {
        bool flag = true;
        if (remixWorldGen && (double)x > (double)Main.maxTilesX * 0.48 && (double)x < (double)Main.maxTilesX * 0.52 && y > Main.maxTilesY - 220)
        {
            flag = false;
        }
        for (int i = x; i < x + 2; i++)
        {
            for (int j = y - 1; j < y + 1; j++)
            {
                if (Main.tile[i, j] == null)
                {
                    Main.tile[i, j] = new Tile();
                }
                if (Main.tile[i, j].active())
                {
                    flag = false;
                }
            }
            if (Main.tile[i, y + 1] == null)
            {
                Main.tile[i, y + 1] = new Tile();
            }
            if (!Main.tile[i, y + 1].nactive() || Main.tile[i, y + 1].halfBrick() || Main.tile[i, y + 1].slope() != 0 || !Main.tileSolid[Main.tile[i, y + 1].type])
            {
                flag = false;
            }
        }
        if (flag)
        {
            int num = genRand.Next(3) * 36;
            for (int k = 0; k < 2; k++)
            {
                for (int l = -1; l < 1; l++)
                {
                    int num2 = k * 18 + num;
                    int num3 = (l + 1) * 18;
                    Main.tile[x + k, y + l].active(active: true);
                    Main.tile[x + k, y + l].frameX = (short)num2;
                    Main.tile[x + k, y + l].frameY = (short)(num3 + style * 36);
                    Main.tile[x + k, y + l].type = type;
                    Main.tile[x + k, y + l].halfBrick(halfBrick: false);
                }
            }
            return true;
        }
        return false;
    }
References Terraria.Tile.active(), Terraria.Tile.frameX, Terraria.Tile.frameY, Terraria.Tile.halfBrick(), Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.Tile.nactive(), Terraria.Tile.slope(), Terraria.DataStructures.Tile, Terraria.Main.tile, Terraria.Main.tileSolid, and Terraria.Tile.type.
Referenced by Terraria.WorldGen.Spread.Spider().