Terraria: Terraria.WorldGen.ExplodeMine
ExplodeMine()
static void Terraria.WorldGen.ExplodeMine (int i, int j, bool fromWiring) inline static
Definition at line 23276 of file WorldGen.cs.
    {
        _ = Main.tile[i, j].type;
        KillTile(i, j, fail: false, effectOnly: false, noItem: true);
        NetMessage.SendTileSquare(-1, i, j);
        Projectile.NewProjectile(GetProjectileSource_PlayerOrWires(i, j, fromWiring, Main.LocalPlayer), i * 16 + 8, j * 16 + 8, 0f, 0f, 164, 250, 10f, Main.myPlayer);
    }
References Terraria.Main.LocalPlayer, Terraria.Main.myPlayer, Terraria.Projectile.NewProjectile(), Terraria.NetMessage.SendTileSquare(), Terraria.Main.tile, and Terraria.Tile.type.
Referenced by Terraria.Wiring.HitWireSingle(), and Terraria.Collision.SwitchTiles().