Terraria: Terraria.WorldGen.WouldTileReplacementWork
WouldTileReplacementWork()
static bool Terraria.WorldGen.WouldTileReplacementWork (ushort attemptingToReplaceWith, int x, int y) inline static
Definition at line 53375 of file WorldGen.cs.
    {
        Tile tile = Main.tile[x, y];
        if (attemptingToReplaceWith >= TileID.Count)
        {
            return false;
        }
        if (TileID.Sets.Conversion.Grass[attemptingToReplaceWith] || attemptingToReplaceWith == 633)
        {
            return false;
        }
        if (Main.tileRope[tile.type] && InWorld(x, y, 2))
        {
            Tile tile2 = Main.tile[x - 1, y];
            Tile tile3 = Main.tile[x + 1, y];
            if (attemptingToReplaceWith == 314 && tile2 != null && tile3 != null && ((tile2.active() && tile2.type == 314) || (tile3.active() && tile3.type == 314)))
            {
                return true;
            }
            if (TileID.Sets.Platforms[attemptingToReplaceWith] && tile2 != null && tile3 != null && ((tile2.active() && TileID.Sets.Platforms[tile2.type]) || (tile3.active() && TileID.Sets.Platforms[tile3.type])))
            {
                return true;
            }
        }
        bool flag = !ReplaceTile_IsValidSolid(attemptingToReplaceWith) || !ReplaceTile_IsValidSolid(tile.type);
        bool flag2 = !ReplaceTile_IsValidTorch(attemptingToReplaceWith) || !ReplaceTile_IsValidTorch(tile.type);
        bool flag3 = !ReplaceTile_IsValidCampfire(attemptingToReplaceWith) || !ReplaceTile_IsValidCampfire(tile.type);
        bool num = !ReplaceTile_IsValidPlatform(attemptingToReplaceWith) || !ReplaceTile_IsValidPlatform(tile.type);
        bool flag4 = (!ReplaceTile_IsValidSolid(attemptingToReplaceWith) && !ReplaceTile_IsValidPlatform(attemptingToReplaceWith)) || (!ReplaceTile_IsValidSolid(tile.type) && !ReplaceTile_IsValidPlatform(tile.type));
        bool flag5 = !ReplaceTile_IsValidChest(attemptingToReplaceWith) || !ReplaceTile_IsValidChest(tile.type) || Chest.IsLocked(tile);
        bool flag6 = !ReplaceTile_IsValidDresser(attemptingToReplaceWith) || !ReplaceTile_IsValidDresser(tile.type);
        return !(num && flag2 && flag3 && flag && flag4 && flag5 && flag6);
    }
References Terraria.Tile.active(), Terraria.ID.TileID.Count, Terraria.ID.TileID.Sets.Conversion.Grass, Terraria.Chest.IsLocked(), Terraria.ID.TileID.Sets.Platforms, Terraria.Main.tile, Terraria.Main.tileRope, and Terraria.Tile.type.
Referenced by Terraria.Player.PlaceThing_ValidTileForReplacement().