Terraria: System.Data.XmlToDatasetMap.GetSchemaForNode
GetSchemaForNode()
object System.Data.XmlToDatasetMap.GetSchemaForNode (XmlNode node, bool fIgnoreNamespace) inline
Definition at line 386 of file XmlToDatasetMap.cs.
    {
        TableSchemaInfo tableSchemaInfo = null;
        if (node.NodeType == XmlNodeType.Element)
        {
            tableSchemaInfo = (TableSchemaInfo)(fIgnoreNamespace ? _tableSchemaMap[node.LocalName] : _tableSchemaMap[node]);
        }
        if (tableSchemaInfo != null)
        {
            return tableSchemaInfo.TableSchema;
        }
        return GetColumnSchema(node, fIgnoreNamespace);
    }
References System.Data.XmlToDatasetMap._tableSchemaMap, System.Xml.Dictionary, System.Data.XmlToDatasetMap.GetColumnSchema(), and System.Data.XmlToDatasetMap.TableSchemaInfo.TableSchema.
Referenced by System.Data.XmlDataLoader.LoadData(), System.Data.XmlDataLoader.LoadData(), System.Data.XmlDataLoader.LoadRowData(), and System.Data.XmlDataLoader.LoadRows().