Terraria: Terraria.WorldGen.RefreshStrip
RefreshStrip()
static void Terraria.WorldGen.RefreshStrip (int xStart, int yStart, int xEnd, int yEnd, ref int totalEcho, ref int totalFramed) inline static
Definition at line 70445 of file WorldGen.cs.
    {
        int num = xStart - 1;
        int num2 = yStart - 1;
        int num3 = xEnd - xStart;
        int num4 = yEnd - yStart;
        if (num4 > 50 || num3 > 200)
        {
            throw new IndexOutOfRangeException();
        }
        int num5 = 0;
        Vertical64BitStrips vertical64BitStrips = bitStrip;
        for (int i = 1; i <= num3; i++)
        {
            Bits64 value = default(Bits64);
            for (int j = 1; j <= num4; j++)
            {
                Tile tile = Main.tile[num + i, num2 + j];
                if (tile != null && (tile.invisibleBlock() || tile.invisibleWall()))
                {
                    num5++;
                    value[j] = true;
                }
            }
            vertical64BitStrips[i] = value;
        }
        if (num5 == 0)
        {
            return;
        }
        vertical64BitStrips.Expand3x3();
        for (int k = 0; k < num3 + 2; k++)
        {
            Bits64 bits = vertical64BitStrips[k];
            if (bits.IsEmpty)
            {
                continue;
            }
            for (int l = 0; l < num4 + 2; l++)
            {
                if (bits[l])
                {
                    totalFramed++;
                    Reframe(num + k, num2 + l);
                }
            }
        }
        vertical64BitStrips.Clear();
        totalEcho += num5;
    }
References Terraria.Utilities.Vertical64BitStrips.Clear(), Terraria.Utilities.Vertical64BitStrips.Expand3x3(), Terraria.Tile.invisibleBlock(), Terraria.Tile.invisibleWall(), Terraria.Utilities.Bits64.IsEmpty, and Terraria.Main.tile.