Terraria: Terraria.WorldGen.DungeonPitTrap
DungeonPitTrap()
static bool Terraria.WorldGen.DungeonPitTrap (int i, int j, ushort tileType, int wallType) inline static
Definition at line 29339 of file WorldGen.cs.
    {
        int num = 30;
        int num2 = j;
        int num3 = num2;
        int num4 = genRand.Next(8, 19);
        int num5 = genRand.Next(19, 46);
        int num6 = num4 + genRand.Next(6, 10);
        int num7 = num5 + genRand.Next(6, 10);
        if (!Main.wallDungeon[Main.tile[i, num2].wall])
        {
            return false;
        }
        if (Main.tile[i, num2].active())
        {
            return false;
        }
        for (int k = num2; k < Main.maxTilesY; k++)
        {
            if (k > Main.maxTilesY - 300)
            {
                return false;
            }
            if (Main.tile[i, k].active() && SolidTile(i, k))
            {
                if (Main.tile[i, k].type == 48)
                {
                    return false;
                }
                num2 = k;
                break;
            }
        }
        if (!Main.wallDungeon[Main.tile[i - num4, num2].wall] || !Main.wallDungeon[Main.tile[i + num4, num2].wall])
        {
            return false;
        }
        bool flag = true;
        for (int l = num2; l < num2 + num; l++)
        {
            flag = true;
            for (int m = i - num4; m <= i + num4; m++)
            {
                Tile tile = Main.tile[m, l];
                if (tile.active() && Main.tileDungeon[tile.type])
                {
                    flag = false;
                }
            }
            if (flag)
            {
                num2 = l;
                break;
            }
        }
        for (int n = i - num4; n <= i + num4; n++)
        {
            for (int num8 = num2; num8 <= num2 + num5; num8++)
            {
                Tile tile2 = Main.tile[n, num8];
                if (tile2.active() && (Main.tileDungeon[tile2.type] || tile2.type == GenVars.crackedType))
                {
                    return false;
                }
            }
        }
        bool flag2 = false;
        if (GenVars.dungeonLake)
        {
            flag2 = true;
            GenVars.dungeonLake = false;
        }
        else if (genRand.Next(8) == 0)
        {
            flag2 = true;
        }
        for (int num9 = i - num4; num9 <= i + num4; num9++)
        {
            for (int num10 = num3; num10 <= num2 + num5; num10++)
            {
                if (Main.tileDungeon[Main.tile[num9, num10].type])
                {
                    Main.tile[num9, num10].type = GenVars.crackedType;
                    Main.tile[num9, num10].wall = (ushort)wallType;
                }
            }
        }
        for (int num11 = i - num6; num11 <= i + num6; num11++)
        {
            for (int num12 = num3; num12 <= num2 + num7; num12++)
            {
                Main.tile[num11, num12].lava(lava: false);
                Main.tile[num11, num12].liquid = 0;
                if (!Main.wallDungeon[Main.tile[num11, num12].wall] && Main.tile[num11, num12].type != GenVars.crackedType)
                {
                    Main.tile[num11, num12].Clear(TileDataType.Slope);
                    Main.tile[num11, num12].type = tileType;
                    Main.tile[num11, num12].active(active: true);
                    if (num11 > i - num6 && num11 < i + num6 && num12 < num2 + num7)
                    {
                        Main.tile[num11, num12].wall = (ushort)wallType;
                    }
                }
            }
        }
        for (int num13 = i - num4; num13 <= i + num4; num13++)
        {
            for (int num14 = num3; num14 <= num2 + num5; num14++)
            {
                if (Main.tile[num13, num14].type != GenVars.crackedType)
                {
                    if (flag2)
                    {
                        Main.tile[num13, num14].liquid = byte.MaxValue;
                    }
                    if (num13 == i - num4 || num13 == i + num4 || num14 == num2 + num5)
                    {
                        Main.tile[num13, num14].type = 48;
                    }
                    else if ((num13 == i - num4 + 1 && num14 % 2 == 0) || (num13 == i + num4 - 1 && num14 % 2 == 0) || (num14 == num2 + num5 - 1 && num13 % 2 == 0))
                    {
                        Main.tile[num13, num14].type = 48;
                    }
                    else
                    {
                        Main.tile[num13, num14].active(active: false);
                    }
                }
            }
        }
        return true;
    }
References Terraria.Tile.active(), Terraria.Tile.Clear(), Terraria.WorldBuilding.GenVars.crackedType, Terraria.WorldBuilding.GenVars.dungeonLake, Terraria.Tile.lava(), Terraria.Tile.liquid, Terraria.Main.maxTilesY, Terraria.Enums.SolidTile, Terraria.Main.tile, Terraria.Main.tileDungeon, Terraria.Tile.type, Terraria.Tile.wall, and Terraria.Main.wallDungeon.