Terraria: System.Data.XmlToDatasetMap.GetColumnSchema
GetColumnSchema() [2/2]
object System.Data.XmlToDatasetMap.GetColumnSchema (XmlNode node, bool fIgnoreNamespace) inline
Definition at line 352 of file XmlToDatasetMap.cs.
    {
        TableSchemaInfo tableSchemaInfo = null;
        XmlNode xmlNode = ((node.NodeType == XmlNodeType.Attribute) ? ((XmlAttribute)node).OwnerElement : node.ParentNode);
        do
        {
            if (xmlNode == null || xmlNode.NodeType != XmlNodeType.Element)
            {
                return null;
            }
            tableSchemaInfo = (TableSchemaInfo)(fIgnoreNamespace ? _tableSchemaMap[xmlNode.LocalName] : _tableSchemaMap[xmlNode]);
            xmlNode = xmlNode.ParentNode;
        }
        while (tableSchemaInfo == null);
        if (fIgnoreNamespace)
        {
            return tableSchemaInfo.ColumnsSchemaMap[node.LocalName];
        }
        return tableSchemaInfo.ColumnsSchemaMap[node];
    }
References System.Data.XmlToDatasetMap._tableSchemaMap, System.Xml.Dictionary, and System.Xml.XmlNode.ParentNode.
Referenced by System.Data.XmlDataLoader.FColumnElement(), System.Data.XmlToDatasetMap.GetSchemaForNode(), System.Data.XmlDataLoader.LoadColumn(), System.Data.XmlDataLoader.LoadRowData(), System.Data.XmlDataLoader.LoadTable(), and System.Data.XmlDataLoader.LoadTopMostTable().