Terraria: Terraria.WorldGen.SolidTileAllowLeftSlope
SolidTileAllowLeftSlope()
static bool Terraria.WorldGen.SolidTileAllowLeftSlope (int i, int j) inline static
Definition at line 60782 of file WorldGen.cs.
    {
        try
        {
            Tile tile = Main.tile[i, j];
            if (tile == null)
            {
                return true;
            }
            if (tile.active() && Main.tileSolid[tile.type] && !tile.rightSlope() && !TileID.Sets.Platforms[tile.type] && !tile.inActive())
            {
                return true;
            }
        }
        catch
        {
        }
        return false;
    }
References Terraria.Tile.active(), Terraria.Tile.inActive(), Terraria.ID.TileID.Sets.Platforms, Terraria.Tile.rightSlope(), Terraria.Main.tile, Terraria.Main.tileSolid, and Terraria.Tile.type.