Terraria: Terraria.WorldGen.BroadcastText
BroadcastText() [2/5]
static void Terraria.WorldGen.BroadcastText (NetworkText text, Color color) inline static
Definition at line 76877 of file WorldGen.cs.
    {
        if (Main.netMode == 0)
        {
            Main.NewText(text.ToString(), color.R, color.G, color.B);
        }
        else if (Main.netMode == 2)
        {
            ChatHelper.BroadcastChatMessage(text, color);
        }
    }
References Terraria.Chat.ChatHelper.BroadcastChatMessage(), Terraria.Main.netMode, Terraria.Main.NewText(), and Terraria.Localization.NetworkText.ToString().