Terraria: Terraria.WorldGen.PlaceActuator
PlaceActuator()
static bool Terraria.WorldGen.PlaceActuator (int i, int j) inline static
Definition at line 49019 of file WorldGen.cs.
    {
        if (!Main.tile[i, j].actuator())
        {
            SoundEngine.PlaySound(0, i * 16, j * 16);
            Main.tile[i, j].actuator(actuator: true);
            return true;
        }
        return false;
    }
References Terraria.Tile.actuator(), Terraria.Audio.SoundEngine.PlaySound(), and Terraria.Main.tile.
Referenced by Terraria.MessageBuffer.GetData(), Terraria.Player.ItemCheck_UseWiringTools(), Terraria.Wiring.MassWireOperationStep(), and Terraria.Player.PlaceThing_Tiles_PlaceIt_AutoPaintAndActuate().