Terraria: Terraria.WorldGen.paintCoatWall
paintCoatWall()
static bool Terraria.WorldGen.paintCoatWall (int x, int y, byte paintCoatId, bool broadcast = false) inline static
Definition at line 35328 of file WorldGen.cs.
    {
        Tile tile = Main.tile[x, y];
        if (tile == null || tile.wall == 0)
        {
            return false;
        }
        List<Color> oldColors = coatingColors(tile, block: false);
        switch (paintCoatId)
        {
        default:
            return false;
        case 0:
            if (!tile.fullbrightWall() && !tile.invisibleWall())
            {
                return false;
            }
            tile.fullbrightWall(fullbrightWall: false);
            tile.invisibleWall(invisibleWall: false);
            SquareWallFrame(x, y, resetFrame: false);
            break;
        case 1:
            if (tile.fullbrightWall())
            {
                return false;
            }
            tile.fullbrightWall(fullbrightWall: true);
            break;
        case 2:
            if (tile.invisibleWall())
            {
                return false;
            }
            tile.invisibleWall(invisibleWall: true);
            SquareWallFrame(x, y, resetFrame: false);
            break;
        }
        if (broadcast)
        {
            NetMessage.SendData(64, -1, -1, null, x, y, (int)paintCoatId, 1f);
        }
        paintCoatEffect(x, y, paintCoatId, oldColors);
        return true;
    }
References Terraria.Tile.fullbrightWall(), Terraria.Tile.invisibleWall(), Terraria.NetMessage.SendData(), Terraria.Main.tile, and Terraria.Tile.wall.
Referenced by Terraria.Player.ApplyCoating(), Terraria.MessageBuffer.GetData(), and Terraria.Player.PlaceThing_PaintScrapper_TryScrapping().