Terraria: Terraria.WorldGen.CheckMB
CheckMB()
static void Terraria.WorldGen.CheckMB (int i, int j, int type) inline static
Definition at line 42526 of file WorldGen.cs.
    {
        if (destroyObject)
        {
            return;
        }
        bool flag = false;
        int num = i;
        int num2 = j;
        int num3 = 0;
        int num4;
        for (num4 = Main.tile[i, j].frameY / 18; num4 >= 2; num4 -= 2)
        {
            num3++;
        }
        int num5 = Main.tile[i, j].frameX / 18;
        int num6 = 0;
        if (num5 >= 2)
        {
            num5 -= 2;
            num6++;
        }
        num = i - num5;
        num2 = j - num4;
        for (int k = num; k < num + 2; k++)
        {
            for (int l = num2; l < num2 + 2; l++)
            {
                if (Main.tile[k, l] == null)
                {
                    Main.tile[k, l] = new Tile();
                }
                if (!Main.tile[k, l].active() || Main.tile[k, l].type != type || Main.tile[k, l].frameX != (k - num) * 18 + num6 * 36 || Main.tile[k, l].frameY != (l - num2) * 18 + num3 * 36)
                {
                    flag = true;
                }
            }
            if (!Main.tile[k, num2 + 2].nactive())
            {
                flag = true;
            }
            else if (!Main.tileSolid[Main.tile[k, num2 + 2].type] && !Main.tileTable[Main.tile[k, num2 + 2].type])
            {
                flag = true;
            }
        }
        if (!flag)
        {
            return;
        }
        destroyObject = true;
        for (int m = num; m < num + 2; m++)
        {
            for (int n = num2; n < num2 + 3; n++)
            {
                if (Main.tile[m, n].type == type && Main.tile[m, n].active())
                {
                    KillTile(m, n);
                }
            }
        }
        if (type == 35)
        {
            Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 1813);
        }
        else if (num3 == 28)
        {
            Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 1963);
        }
        else if (num3 == 29)
        {
            Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 1964);
        }
        else if (num3 == 30)
        {
            Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 1965);
        }
        else if (num3 == 31)
        {
            Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 2742);
        }
        else if (num3 == 32)
        {
            Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 3044);
        }
        else if (num3 == 33)
        {
            Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 3235);
        }
        else if (num3 == 34)
        {
            Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 3236);
        }
        else if (num3 == 35)
        {
            Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 3237);
        }
        else if (num3 == 36)
        {
            Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 3370);
        }
        else if (num3 == 37)
        {
            Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 3371);
        }
        else if (num3 == 38)
        {
            Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 3796);
        }
        else if (num3 == 39)
        {
            Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 3869);
        }
        else if (num3 == 43)
        {
            Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 4077);
        }
        else if (num3 == 41)
        {
            Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 4078);
        }
        else if (num3 == 42)
        {
            Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 4079);
        }
        else if (num3 == 44)
        {
            Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 4080);
        }
        else if (num3 == 45)
        {
            Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 4081);
        }
        else if (num3 == 40)
        {
            Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 4082);
        }
        else if (num3 == 46)
        {
            Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 4237);
        }
        else if (num3 == 47)
        {
            Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 4356);
        }
        else if (num3 == 48)
        {
            Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 4357);
        }
        else if (num3 == 49)
        {
            Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 4358);
        }
        else if (num3 == 50)
        {
            Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 4421);
        }
        else if (num3 == 51)
        {
            Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 4606);
        }
        else if (num3 == 52)
        {
            Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 4979);
        }
        else if (num3 == 53)
        {
            Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 4985);
        }
        else if (num3 == 54)
        {
            Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 4990);
        }
        else if (num3 == 55)
        {
            Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 4991);
        }
        else if (num3 == 56)
        {
            Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 4992);
        }
        else if (num3 == 57)
        {
            Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 5006);
        }
        else if (num3 == 58)
        {
            Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 5014);
        }
        else if (num3 == 59)
        {
            Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 5015);
        }
        else if (num3 == 60)
        {
            Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 5016);
        }
        else if (num3 == 61)
        {
            Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 5017);
        }
        else if (num3 == 62)
        {
            Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 5018);
        }
        else if (num3 == 63)
        {
            Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 5019);
        }
        else if (num3 == 64)
        {
            Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 5020);
        }
        else if (num3 == 65)
        {
            Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 5021);
        }
        else if (num3 == 66)
        {
            Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 5022);
        }
        else if (num3 == 67)
        {
            Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 5023);
        }
        else if (num3 == 68)
        {
            Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 5024);
        }
        else if (num3 == 69)
        {
            Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 5025);
        }
        else if (num3 == 70)
        {
            Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 5026);
        }
        else if (num3 == 71)
        {
            Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 5027);
        }
        else if (num3 == 72)
        {
            Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 5028);
        }
        else if (num3 == 73)
        {
            Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 5029);
        }
        else if (num3 == 74)
        {
            Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 5030);
        }
        else if (num3 == 75)
        {
            Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 5031);
        }
        else if (num3 == 76)
        {
            Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 5032);
        }
        else if (num3 == 77)
        {
            Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 5033);
        }
        else if (num3 == 78)
        {
            Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 5034);
        }
        else if (num3 == 79)
        {
            Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 5035);
        }
        else if (num3 == 80)
        {
            Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 5036);
        }
        else if (num3 == 81)
        {
            Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 5037);
        }
        else if (num3 == 82)
        {
            Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 5038);
        }
        else if (num3 == 83)
        {
            Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 5039);
        }
        else if (num3 == 84)
        {
            Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 5040);
        }
        else if (num3 == 85)
        {
            Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 5044);
        }
        else if (num3 == 86)
        {
            Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 5112);
        }
        else if (num3 == 87)
        {
            Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 5362);
        }
        else if (num3 >= 13)
        {
            Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 1596 + num3 - 13);
        }
        else
        {
            Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 562 + num3);
        }
        for (int num7 = num - 1; num7 < num + 3; num7++)
        {
            for (int num8 = num2 - 1; num8 < num2 + 3; num8++)
            {
                TileFrame(num7, num8);
            }
        }
        destroyObject = false;
    }
References Terraria.Tile.active(), Terraria.Tile.frameX, Terraria.Tile.frameY, Terraria.Tile.nactive(), Terraria.Item.NewItem(), Terraria.DataStructures.Tile, Terraria.Main.tile, Terraria.Main.tileSolid, Terraria.Main.tileTable, and Terraria.Tile.type.