Terraria: Terraria.WorldGen.oceanDepths
oceanDepths()
static bool Terraria.WorldGen.oceanDepths (int x, int y) inline static
Definition at line 7142 of file WorldGen.cs.
    {
        if ((double)y > oceanLevel)
        {
            return false;
        }
        if (x < beachDistance || x > Main.maxTilesX - beachDistance)
        {
            return true;
        }
        return false;
    }
References Terraria.WorldGen.beachDistance, Terraria.Main.maxTilesX, and Terraria.WorldGen.oceanLevel.
Referenced by Terraria.Main.DrawBackground(), Terraria.WorldGen.GenerateWorld(), Terraria.Main.GetPreferredBGStyleForPlayer(), Terraria.GameContent.Biomes.DeadMansChestBiome.IsAGoodSpot(), Terraria.GameContent.Generation.TrackGenerator.IsLocationInvalid(), Terraria.GameContent.TreeTopsInfo.RandomizeTreeStyleBasedOnWorldPosition(), Terraria.SceneMetrics.ScanAndExportToMain(), Terraria.Liquid.SettleWaterAt(), Terraria.NPC.SpawnNPC(), Terraria.Main.UpdateAudio_DecideOnNewMusic(), Terraria.Main.UpdateAudio_DecideOnTOWMusic(), Terraria.Player.UpdateBiomes(), and Terraria.Player.UpdateTorchLuck_ConsumeCountersAndCalculate().