Terraria: Terraria.WorldGen.TownManager
TownManager
TownRoomManager Terraria.WorldGen.TownManager = new TownRoomManager() static
Referenced by Terraria.WorldGen.clearWorld(), Terraria.Main.DrawNPCHousesInWorld(), Terraria.MessageBuffer.GetData(), Terraria.GameContent.ShopHelper.GetNearbyResidentNPCs(), Terraria.WorldGen.IsRoomConsideredAlreadyOccupied(), Terraria.WorldGen.IsRoomConsideredOccupiedForNPCIndex(), Terraria.WorldGen.IsThereASpawnablePrioritizedTownNPC(), Terraria.WorldGen.IsThereASpawnablePrioritizedTownNPC_Old(), Terraria.WorldGen.kickOut(), Terraria.IO.WorldFile.LoadTownManager(), Terraria.WorldGen.moveRoom(), Terraria.IO.WorldFile.SaveTownManager(), Terraria.WorldGen.ScoreRoom_IsThisRoomOccupiedBySomeone(), Terraria.NetMessage.SendNPCHousesAndTravelShop(), Terraria.WorldGen.SpawnTownNPC(), Terraria.NPC.UpdateHomeTileState(), and Terraria.NPC.UpdateNetworkCode().