Terraria: Terraria.WorldGen.CaveOpenater
CaveOpenater()
static void Terraria.WorldGen.CaveOpenater (int i, int j) inline static
Definition at line 70255 of file WorldGen.cs.
    {
        //IL_0081: Unknown result type (might be due to invalid IL or missing references)
        //IL_0088: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c0: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d5: Unknown result type (might be due to invalid IL or missing references)
        //IL_00eb: Unknown result type (might be due to invalid IL or missing references)
        //IL_0100: Unknown result type (might be due to invalid IL or missing references)
        //IL_01f2: Unknown result type (might be due to invalid IL or missing references)
        //IL_01f3: Unknown result type (might be due to invalid IL or missing references)
        //IL_01f4: Unknown result type (might be due to invalid IL or missing references)
        //IL_01f9: Unknown result type (might be due to invalid IL or missing references)
        //IL_0242: Unknown result type (might be due to invalid IL or missing references)
        //IL_026b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0170: Unknown result type (might be due to invalid IL or missing references)
        //IL_017f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0294: Unknown result type (might be due to invalid IL or missing references)
        //IL_02b5: Unknown result type (might be due to invalid IL or missing references)
        double num = genRand.Next(7, 12);
        double num2 = num;
        int num3 = 1;
        if (genRand.Next(2) == 0)
        {
            num3 = -1;
        }
        if (genRand.Next(10) != 0)
        {
            num3 = ((i < Main.maxTilesX / 2) ? 1 : (-1));
        }
        Vector2D val = default(Vector2D);
        val.X = i;
        val.Y = j;
        int num4 = 100;
        Vector2D val2 = default(Vector2D);
        val2.Y = 0.0;
        val2.X = num3;
        while (num4 > 0)
        {
            Tile tile = Main.tile[(int)val.X, (int)val.Y];
            if (tile.wall == 0 || (tile.active() && !TileID.Sets.CanBeClearedDuringGeneration[tile.type]))
            {
                num4 = 0;
            }
            num4--;
            int num5 = (int)(val.X - num * 0.5);
            int num6 = (int)(val.X + num * 0.5);
            int num7 = (int)(val.Y - num * 0.5);
            int num8 = (int)(val.Y + num * 0.5);
            if (num5 < 0)
            {
                num5 = 0;
            }
            if (num6 > Main.maxTilesX)
            {
                num6 = Main.maxTilesX;
            }
            if (num7 < 0)
            {
                num7 = 0;
            }
            if (num8 > Main.maxTilesY)
            {
                num8 = Main.maxTilesY;
            }
            num2 = num * (double)genRand.Next(80, 120) * 0.01;
            for (int k = num5; k < num6; k++)
            {
                for (int l = num7; l < num8; l++)
                {
                    double num9 = Math.Abs((double)k - val.X);
                    double num10 = Math.Abs((double)l - val.Y);
                    if (Math.Sqrt(num9 * num9 + num10 * num10) < num2 * 0.4 && TileID.Sets.CanBeClearedDuringGeneration[Main.tile[k, l].type])
                    {
                        Main.tile[k, l].active(active: false);
                    }
                }
            }
            val += val2;
            val2.X += (double)genRand.Next(-10, 11) * 0.05;
            val2.Y += (double)genRand.Next(-10, 11) * 0.05;
            if (val2.X > (double)num3 + 0.5)
            {
                val2.X = (double)num3 + 0.5;
            }
            if (val2.X < (double)num3 - 0.5)
            {
                val2.X = (double)num3 - 0.5;
            }
            if (val2.Y > 0.0)
            {
                val2.Y = 0.0;
            }
            if (val2.Y < -0.5)
            {
                val2.Y = -0.5;
            }
        }
    }
References System.Math.Abs(), Terraria.Tile.active(), Terraria.ID.TileID.Sets.CanBeClearedDuringGeneration, Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, System.Math.Sqrt(), Terraria.Main.tile, Terraria.Tile.type, Terraria.Tile.wall, ReLogic.Utilities.Vector2D.X, and ReLogic.Utilities.Vector2D.Y.
Referenced by Terraria.WorldGen.GenerateWorld().