Terraria: Terraria.WorldGen.nextDirtCount
nextDirtCount()
static void Terraria.WorldGen.nextDirtCount (int x, int y) inline static
Definition at line 5778 of file WorldGen.cs.
    {
        if (numTileCount >= maxTileCount)
        {
            return;
        }
        if (x <= 1 || x >= Main.maxTilesX - 1 || y <= 1 || y >= Main.maxTilesY - 1)
        {
            numTileCount = maxTileCount;
        }
        else if (!CountedTiles.ContainsKey(new Point(x, y)))
        {
            if (Main.tile[x, y].active() && (Main.tile[x, y].type == 147 || Main.tile[x, y].type == 161))
            {
                numTileCount = maxTileCount;
            }
            else if (Main.tile[x, y].wall == 244 || Main.tile[x, y].wall == 83 || Main.tile[x, y].wall == 3 || Main.tile[x, y].wall == 187 || Main.tile[x, y].wall == 216)
            {
                numTileCount = maxTileCount;
            }
            else if (!SolidTile(x, y) && (Main.tile[x, y].wall == 2 || Main.tile[x, y].wall == 59))
            {
                CountedTiles.Add(new Point(x, y), value: true);
                numTileCount++;
                nextDirtCount(x - 1, y);
                nextDirtCount(x + 1, y);
                nextDirtCount(x, y - 1);
                nextDirtCount(x, y + 1);
                nextDirtCount(x - 1, y - 1);
                nextDirtCount(x - 1, y + 1);
                nextDirtCount(x + 1, y - 1);
                nextDirtCount(x + 1, y + 1);
                nextDirtCount(x - 2, y);
                nextDirtCount(x + 2, y);
            }
        }
    }
References Terraria.WorldGen.CountedTiles, Terraria.WorldGen.maxTileCount, Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.WorldGen.nextDirtCount(), Terraria.WorldGen.numTileCount, Terraria.Enums.SolidTile, Terraria.Main.tile, and System.value.
Referenced by Terraria.WorldGen.countDirtTiles(), and Terraria.WorldGen.nextDirtCount().