Terraria: Terraria.WorldGen.UpdateWorld_OvergroundTile
UpdateWorld_OvergroundTile()
static void Terraria.WorldGen.UpdateWorld_OvergroundTile (int i, int j, bool checkNPCSpawns, int wallDist) inline static private
    {
        int num = i - 1;
        int num2 = i + 2;
        int num3 = j - 1;
        int num4 = j + 2;
        if (num < 10)
        {
            num = 10;
        }
        if (num2 > Main.maxTilesX - 10)
        {
            num2 = Main.maxTilesX - 10;
        }
        if (num3 < 10)
        {
            num3 = 10;
        }
        if (num4 > Main.maxTilesY - 10)
        {
            num4 = Main.maxTilesY - 10;
        }
        if (Main.tile[i, j] == null)
        {
            return;
        }
        if (Main.tile[i, j].type == 655 && !NPC.AnyNPCs(262))
        {
            KillTile(i, j);
            if (Main.netMode == 2)
            {
                NetMessage.SendData(17, -1, -1, null, 0, i, j);
            }
        }
        if (Main.tile[i, j].type == 85)
        {
            TryGrowingAbigailsFlower(i, j);
        }
        else if (Main.tileAlch[Main.tile[i, j].type])
        {
            GrowAlch(i, j);
        }
        else if ((double)j < Main.worldSurface + 10.0 && (i < beachDistance || i > Main.maxTilesX - beachDistance) && !Main.tile[i, j].active())
        {
            int num5 = 3000;
            num5 -= (int)(Math.Abs(Main.windSpeedCurrent) * 1250f);
            if (Main.raining)
            {
                num5 -= (int)(1250f * Main.maxRaining);
            }
            if (num5 < 300)
            {
                num5 = 300;
            }
            if (genRand.Next(num5) == 0)
            {
                int k;
                for (k = j; (double)k < Main.worldSurface + 10.0 && !Main.tile[i, k].active() && k - j < 15; k++)
                {
                }
                if (Main.tile[i, k].active() && Main.tile[i, k].type == 53 && SolidTileAllowBottomSlope(i, k))
                {
                    k--;
                    int num6 = genRand.Next(2, 5);
                    int num7 = genRand.Next(8, 11);
                    int num8 = 0;
                    for (int l = i - num7; l <= i + num7; l++)
                    {
                        for (int m = k - num7; m <= k + num7; m++)
{
                            if (Main.tile[l, m].active() && (Main.tile[l, m].type == 324 || Main.tile[l, m].type == 81))
{
                                num8++;
                            }
                        }
                    }
                    if (num8 < num6)
                    {
                        if (genRand.Next(2) == 0 && Main.tile[i, k].liquid >= 230)
{
                            PlaceTile(i, k, 81, mute: true);
                            if (Main.netMode == 2 && Main.tile[i, k].active())
{
                                NetMessage.SendTileSquare(-1, i, k);
                            }
                        }
                        else
{
                            PlaceTile(i, k, 324, mute: true, forced: false, -1, RollRandomSeaShellStyle());
                            if (Main.netMode == 2 && Main.tile[i, k].active())
{
                                NetMessage.SendTileSquare(-1, i, k);
                            }
                        }
                    }
                }
            }
        }
        if ((Main.tile[i, j].type == 596 || Main.tile[i, j].type == 616 || Main.tile[i, j].type == 595 || Main.tile[i, j].type == 615) && (Main.tile[i, j + 1].type == 199 || Main.tile[i, j + 1].type == 23))
        {
            KillTile(i, j);
            if (Main.netMode == 2)
            {
                NetMessage.SendTileSquare(-1, i, j);
            }
        }
        if ((Main.tile[i, j].type == 571 || (Main.tile[i, j].type == 60 && Main.tile[i, j - 1].liquid > 0)) && genRand.Next(5) == 0 && (!Main.tile[i, j - 1].active() || Main.tile[i, j - 1].type == 61 || Main.tile[i, j - 1].type == 74 || Main.tile[i, j - 1].type == 518) && (Main.tile[i, j].type != 60 || genRand.Next(30) == 0) && PlaceBamboo(i, j - 1))
        {
            NetMessage.SendTileSquare(-1, i, j - 1, 1, 2);
        }
        if (Main.tile[i, j].type == 518)
        {
            if (Main.tile[i, j].liquid == 0 || (Main.tile[i, j].liquid / 16 >= 9 && SolidTile(i, j - 1)) || (Main.tile[i, j - 1].liquid > 0 && Main.tile[i, j - 1].active()))
            {
                KillTile(i, j);
                if (Main.netMode == 2)
                {
                    NetMessage.SendData(17, -1, -1, null, 0, i, j);
                }
            }
            else
            {
                CheckLilyPad(i, j);
            }
        }
        else if (Main.tile[i, j].type == 519)
        {
            CheckCatTail(i, j);
            if (Main.tile[i, j].active() && genRand.Next(8) == 0)
            {
                GrowCatTail(i, j);
                CheckCatTail(i, j);
            }
        }
        else if (Main.tile[i, j].liquid > 32)
        {
            if (Main.tile[i, j].active())
            {
                if (TileID.Sets.SlowlyDiesInWater[Main.tile[i, j].type])
                {
                    KillTile(i, j);
                    if (Main.netMode == 2)
                    {
                        NetMessage.SendData(17, -1, -1, null, 0, i, j);
                    }
                }
                else if (Main.tile[i, j].type == 60)
                {
                    UpdateWorld_GrassGrowth(i, j, num, num2, num3, num4, underground: false);
                }
            }
            else if (genRand.Next(600) == 0)
            {
                PlaceTile(i, j, 518, mute: true);
                if (Main.netMode == 2)
                {
                    NetMessage.SendTileSquare(-1, i, j);
                }
            }
            else if (genRand.Next(600) == 0)
            {
                PlaceTile(i, j, 519, mute: true);
                if (Main.netMode == 2)
                {
                    NetMessage.SendTileSquare(-1, i, j);
                }
            }
        }
        else if (Main.tile[i, j].nactive())
        {
            hardUpdateWorld(i, j);
            if (Main.rand.Next(3000) == 0)
            {
                plantDye(i, j);
            }
            else if (Main.hardMode && ((double)i < (double)Main.maxTilesX * 0.4 || (double)i > (double)Main.maxTilesX * 0.6) && Main.rand.Next(15000) == 0)
            {
                plantDye(i, j, exoticPlant: true);
            }
            if (Main.tile[i, j].type == 80)
            {
                if (genRand.Next(15) == 0)
                {
                    GrowCactus(i, j);
                }
            }
            else if (Main.tile[i, j].type == 529)
            {
                if (CheckSeaOat(i, j) && genRand.Next(20) == 0)
                {
                    GrowSeaOat(i, j);
                }
            }
            else if (TileID.Sets.Conversion.Sand[Main.tile[i, j].type])
            {
                if (!Main.tile[i, num3].active())
                {
                    if (genRand.Next(25) == 0)
                    {
                        PlaceOasisPlant(i, num3, 530);
                        if (Main.tile[i, num3].type == 530 && Main.netMode == 2)
{
                            NetMessage.SendTileSquare(-1, i - 1, num3 - 1, 3, 2);
                        }
                    }
                    if (genRand.Next(20) != 0 || !PlantSeaOat(i, num3))
                    {
                        if (i < oceanDistance || i > Main.maxTilesX - oceanDistance)
{
                            if (genRand.Next(500) == 0)
{
                                int num9 = 7;
                                int num10 = 6;
                                int num11 = 0;
                                for (int n = i - num9; n <= i + num9; n++)
{
                                    for (int num12 = num3 - num9; num12 <= num3 + num9; num12++)
{
                                        if (Main.tile[n, num12].active() && Main.tile[n, num12].type == 81)
{
                                            num11++;
                                        }
                                    }
                                }
                                if (num11 < num10 && Main.tile[i, num3].liquid == byte.MaxValue && Main.tile[i, num3 - 1].liquid == byte.MaxValue && Main.tile[i, num3 - 2].liquid == byte.MaxValue && Main.tile[i, num3 - 3].liquid == byte.MaxValue && Main.tile[i, num3 - 4].liquid == byte.MaxValue)
{
                                    PlaceTile(i, num3, 81, mute: true);
                                    if (Main.netMode == 2 && Main.tile[i, num3].active())
{
                                        NetMessage.SendTileSquare(-1, i, num3);
                                    }
                                }
                            }
                        }
                        else if (i > beachDistance + 20 && i < Main.maxTilesX - beachDistance - 20 && genRand.Next(300) == 0)
{
                            GrowCactus(i, j);
                        }
                    }
                }
            }
            else if (Main.tile[i, j].type == 530)
            {
                if (!OasisPlantWaterCheck(i, j, boost: true))
                {
                    KillTile(i, j);
                    if (Main.netMode == 2)
                    {
                        NetMessage.SendData(17, -1, -1, null, 0, i, j);
                    }
                }
            }
            else if (Main.tile[i, j].type == 147 || Main.tile[i, j].type == 161 || Main.tile[i, j].type == 163 || Main.tile[i, j].type == 164 || Main.tile[i, j].type == 200)
            {
                if (Main.rand.Next(10) == 0 && !Main.tile[i, j + 1].active() && !Main.tile[i, j + 2].active())
                {
                    int num13 = i - 3;
                    int num14 = i + 4;
                    int num15 = 0;
                    for (int num16 = num13; num16 < num14; num16++)
                    {
                        if (Main.tile[num16, j].type == 165 && Main.tile[num16, j].active())
{
                            num15++;
                        }
                        if (Main.tile[num16, j + 1].type == 165 && Main.tile[num16, j + 1].active())
{
                            num15++;
                        }
                        if (Main.tile[num16, j + 2].type == 165 && Main.tile[num16, j + 2].active())
{
                            num15++;
                        }
                        if (Main.tile[num16, j + 3].type == 165 && Main.tile[num16, j + 3].active())
{
                            num15++;
                        }
                    }
                    if (num15 < 2)
                    {
                        PlaceTight(i, j + 1);
                        SquareTileFrame(i, j + 1);
                        if (Main.netMode == 2 && Main.tile[i, j + 1].active())
{
                            NetMessage.SendTileSquare(-1, i, j + 1, 1, 2);
                        }
                    }
                }
            }
            else if (Main.tile[i, j].type == 254)
            {
                if (Main.rand.Next((Main.tile[i, j].frameX + 10) / 10) == 0)
                {
                    GrowPumpkin(i, j, 254);
                }
            }
            else if (Main.tile[i, j].type == 78 || Main.tile[i, j].type == 380 || Main.tile[i, j].type == 579)
            {
                if (!Main.tile[i, num3].active() && genRand.Next(2) == 0)
                {
                    PlaceTile(i, num3, 3, mute: true);
                    if (Main.netMode == 2 && Main.tile[i, num3].active())
                    {
                        NetMessage.SendTileSquare(-1, i, num3);
                    }
                }
            }
            else if (TileID.Sets.SpreadOverground[Main.tile[i, j].type])
            {
                UpdateWorld_GrassGrowth(i, j, num, num2, num3, num4, underground: false);
                int type = Main.tile[i, j].type;
                if ((type == 32 || type == 352) && genRand.Next(3) == 0)
                {
                    if (type == 32)
                    {
                        GrowSpike(i, j, 32, 23);
                    }
                    else
                    {
                        GrowSpike(i, j, 352, 199);
                    }
                }
            }
            else if (Main.tileMoss[Main.tile[i, j].type] || TileID.Sets.tileMossBrick[Main.tile[i, j].type])
            {
                if (genRand.NextDouble() < 0.5)
                {
                    int type2 = Main.tile[i, j].type;
                    bool flag = false;
                    TileColorCache color = Main.tile[i, j].BlockColorAndCoating();
                    for (int num17 = num; num17 < num2; num17++)
                    {
                        for (int num18 = num3; num18 < num4; num18++)
{
                            if ((i != num17 || j != num18) && Main.tile[num17, num18].active() && (Main.tile[num17, num18].type == 1 || Main.tile[num17, num18].type == 38))
{
                                int type3 = Main.tile[num17, num18].type;
                                int num19 = MossConversion(type2, type3);
                                SpreadGrass(num17, num18, Main.tile[num17, num18].type, num19, repeat: false, color);
                                if (Main.tile[num17, num18].type == num19)
{
                                    SquareTileFrame(num17, num18);
                                    flag = true;
                                }
                            }
                        }
                    }
                    if (Main.netMode == 2 && flag)
                    {
                        NetMessage.SendTileSquare(-1, i, j, 3);
                    }
                    if (genRand.Next(6) == 0)
                    {
                        int num20 = i;
                        int num21 = j;
                        switch (genRand.Next(4))
{
                        case 0:
                            num20--;
                            break;
                        case 1:
                            num20++;
                            break;
                        case 2:
                            num21--;
                            break;
                        default:
                            num21++;
                            break;
                        }
                        if (!Main.tile[num20, num21].active())
{
                            if (PlaceTile(num20, num21, 184, mute: true))
{
                                Main.tile[num20, num21].CopyPaintAndCoating(Main.tile[i, j]);
                            }
                            if (Main.netMode == 2 && Main.tile[num20, num21].active())
{
                                NetMessage.SendTileSquare(-1, num20, num21);
                            }
                        }
                    }
                }
            }
            else if (Main.tile[i, j].type == 20)
            {
                if (genRand.Next(20) == 0)
                {
                    AttemptToGrowTreeFromSapling(i, j, underground: false);
                }
            }
            else if (Main.tile[i, j].type == 595)
            {
                if (genRand.Next(5) == 0)
                {
                    AttemptToGrowTreeFromSapling(i, j, underground: false);
                }
            }
            else if (Main.tile[i, j].type == 615)
            {
                if (genRand.Next(5) == 0)
                {
                    AttemptToGrowTreeFromSapling(i, j, underground: false);
                }
            }
            else if (Main.tile[i, j].type == 3 && genRand.Next(20) == 0)
            {
                if (Main.tile[i, j].frameX != 144)
                {
                    Main.tile[i, j].type = 73;
                    if (Main.netMode == 2)
                    {
                        NetMessage.SendTileSquare(-1, i, j);
                    }
                }
            }
            else if (Main.tile[i, j].type == 110 && genRand.Next(20) == 0 && Main.tile[i, j].frameX < 144)
            {
                Main.tile[i, j].type = 113;
                if (Main.netMode == 2)
                {
                    NetMessage.SendTileSquare(-1, i, j);
                }
            }
        }
        else
        {
            if (Main.tile[i, j].wall == 62 && Main.tile[i, j].liquid == 0)
            {
                GrowWeb(i, j);
            }
            if (checkNPCSpawns)
            {
                TrySpawningTownNPC(i, j);
            }
        }
        if (AllowedToSpreadInfections)
        {
            if (Main.tile[i, j].wall == 81 || Main.tile[i, j].wall == 83 || (Main.tile[i, j].type == 199 && Main.tile[i, j].active()))
            {
                int num22 = i + genRand.Next(-2, 3);
                int num23 = j + genRand.Next(-2, 3);
                if (InWorld(num22, num23, 10) && Main.tile[num22, num23].wall >= 63 && Main.tile[num22, num23].wall <= 68)
                {
                    bool flag2 = false;
                    for (int num24 = i - wallDist; num24 < i + wallDist; num24++)
                    {
                        for (int num25 = j - wallDist; num25 < j + wallDist; num25++)
{
                            if (Main.tile[num24, num25].active())
{
                                int type4 = Main.tile[num24, num25].type;
                                if (type4 == 199 || type4 == 200 || type4 == 201 || type4 == 203 || type4 == 205 || type4 == 234 || type4 == 352 || type4 == 662)
{
                                    flag2 = true;
                                    break;
                                }
                            }
                        }
                    }
                    if (flag2)
                    {
                        Main.tile[num22, num23].wall = 81;
                        if (Main.netMode == 2)
{
                            NetMessage.SendTileSquare(-1, num22, num23);
                        }
                    }
                }
            }
            else if (Main.tile[i, j].wall == 69 || Main.tile[i, j].wall == 3 || (Main.tile[i, j].type == 23 && Main.tile[i, j].active()))
            {
                int num26 = i + genRand.Next(-2, 3);
                int num27 = j + genRand.Next(-2, 3);
                if (InWorld(num26, num27, 10) && Main.tile[num26, num27].wall >= 63 && Main.tile[num26, num27].wall <= 68)
                {
                    bool flag3 = false;
                    for (int num28 = i - wallDist; num28 < i + wallDist; num28++)
                    {
                        for (int num29 = j - wallDist; num29 < j + wallDist; num29++)
{
                            if (Main.tile[num28, num29].active())
{
                                int type5 = Main.tile[num28, num29].type;
                                if (type5 == 22 || type5 == 23 || type5 == 24 || type5 == 25 || type5 == 32 || type5 == 112 || type5 == 163 || type5 == 636 || type5 == 661)
{
                                    flag3 = true;
                                    break;
                                }
                            }
                        }
                    }
                    if (flag3)
                    {
                        Main.tile[num26, num27].wall = 69;
                        if (Main.netMode == 2)
{
                            NetMessage.SendTileSquare(-1, num26, num27);
                        }
                    }
                }
            }
            else if (Main.tile[i, j].wall == 70 || (Main.tile[i, j].type == 109 && Main.tile[i, j].active()))
            {
                int num30 = i + genRand.Next(-2, 3);
                int num31 = j + genRand.Next(-2, 3);
                if ((InWorld(num30, num31, 10) && Main.tile[num30, num31].wall == 63) || Main.tile[num30, num31].wall == 65 || Main.tile[num30, num31].wall == 66 || Main.tile[num30, num31].wall == 68)
                {
                    bool flag4 = false;
                    for (int num32 = i - wallDist; num32 < i + wallDist; num32++)
                    {
                        for (int num33 = j - wallDist; num33 < j + wallDist; num33++)
{
                            if (Main.tile[num32, num33].active())
{
                                int type6 = Main.tile[num32, num33].type;
                                if (type6 == 109 || type6 == 110 || type6 == 113 || type6 == 115 || type6 == 116 || type6 == 117 || type6 == 164)
{
                                    flag4 = true;
                                    break;
                                }
                            }
                        }
                    }
                    if (flag4)
                    {
                        Main.tile[num30, num31].wall = 70;
                        if (Main.netMode == 2)
{
                            NetMessage.SendTileSquare(-1, num30, num31);
                        }
                    }
                }
            }
            SpreadDesertWalls(wallDist, i, j);
        }
        if (Main.tile[i, j].nactive())
        {
            if (Main.tile[i, j].type == 2 || Main.tile[i, j].type == 52 || Main.tile[i, j].type == 382 || (Main.tile[i, j].type == 192 && genRand.Next(10) == 0))
            {
                int num34 = 60;
                if (Main.tile[i, j].type == 52 || Main.tile[i, j].type == 382)
                {
                    num34 = 20;
                }
                num34 = 1;
                if (genRand.Next(num34) == 0 && GrowMoreVines(i, j) && !Main.tile[i, j + 1].active() && !Main.tile[i, j + 1].lava())
                {
                    bool flag5 = false;
                    ushort type7 = 52;
                    if (Main.tile[i, j].type == 382)
                    {
                        type7 = 382;
                    }
                    else if (Main.tile[i, j].type != 52)
                    {
                        if (Main.tile[i, j].wall == 68 || Main.tile[i, j].wall == 65 || Main.tile[i, j].wall == 66 || Main.tile[i, j].wall == 63)
{
                            type7 = 382;
                        }
                        else if (Main.tile[i, j + 1].wall == 68 || Main.tile[i, j + 1].wall == 65 || Main.tile[i, j + 1].wall == 66 || Main.tile[i, j + 1].wall == 63)
{
                            type7 = 382;
                        }
                        if (Main.remixWorld && genRand.Next(5) == 0)
{
                            type7 = 382;
                        }
                    }
                    for (int num35 = j; num35 > j - 10; num35--)
                    {
                        if (Main.tile[i, num35].bottomSlope())
{
                            flag5 = false;
                            break;
                        }
                        if (Main.tile[i, num35].active() && Main.tile[i, num35].type == 2 && !Main.tile[i, num35].bottomSlope())
{
                            flag5 = true;
                            break;
                        }
                    }
                    if (flag5)
                    {
                        int num36 = j + 1;
                        Main.tile[i, num36].type = type7;
                        Main.tile[i, num36].active(active: true);
                        Main.tile[i, num36].CopyPaintAndCoating(Main.tile[i, j]);
                        SquareTileFrame(i, num36);
                        if (Main.netMode == 2)
{
                            NetMessage.SendTileSquare(-1, i, num36);
                        }
                    }
                }
            }
            else if (Main.tile[i, j].type == 61 && genRand.Next(3) == 0 && Main.tile[i, j].frameX < 144)
            {
                if (Main.rand.Next(4) == 0)
                {
                    Main.tile[i, j].frameX = (short)(162 + genRand.Next(8) * 18);
                }
                Main.tile[i, j].type = 74;
                if (Main.netMode == 2)
                {
                    NetMessage.SendTileSquare(-1, i, j);
                }
            }
            if ((Main.tile[i, j].type == 60 || Main.tile[i, j].type == 62) && GrowMoreVines(i, j))
            {
                int maxValue = 30;
                if (Main.tile[i, j].type == 62)
                {
                    maxValue = 10;
                }
                if (genRand.Next(maxValue) == 0 && !Main.tile[i, j + 1].active() && !Main.tile[i, j + 1].lava())
                {
                    bool flag6 = false;
                    for (int num37 = j; num37 > j - 10; num37--)
                    {
                        if (Main.tile[i, num37].bottomSlope())
{
                            flag6 = false;
                            break;
                        }
                        if (Main.tile[i, num37].active() && Main.tile[i, num37].type == 60 && !Main.tile[i, num37].bottomSlope())
{
                            flag6 = true;
                            break;
                        }
                    }
                    if (flag6)
                    {
                        int num38 = j + 1;
                        Main.tile[i, num38].type = 62;
                        Main.tile[i, num38].active(active: true);
                        Main.tile[i, num38].CopyPaintAndCoating(Main.tile[i, j]);
                        SquareTileFrame(i, num38);
                        if (Main.netMode == 2)
{
                            NetMessage.SendTileSquare(-1, i, num38);
                        }
                    }
                }
            }
            else if ((Main.tile[i, j].type == 70 || Main.tile[i, j].type == 528) && GrowMoreVines(i, j))
            {
                int maxValue2 = 70;
                if (Main.tile[i, j].type == 528)
                {
                    maxValue2 = 7;
                }
                if (genRand.Next(maxValue2) == 0 && !Main.tile[i, j + 1].active() && !Main.tile[i, j + 1].lava())
                {
                    bool flag7 = false;
                    for (int num39 = j; num39 > j - 10; num39--)
                    {
                        if (Main.tile[i, num39].bottomSlope())
{
                            flag7 = false;
                            break;
                        }
                        if (Main.tile[i, num39].active() && Main.tile[i, num39].type == 70 && !Main.tile[i, num39].bottomSlope())
{
                            flag7 = true;
                            break;
                        }
                    }
                    if (flag7)
                    {
                        int num40 = j + 1;
                        Main.tile[i, num40].type = 528;
                        Main.tile[i, num40].active(active: true);
                        Main.tile[i, num40].CopyPaintAndCoating(Main.tile[i, j]);
                        SquareTileFrame(i, num40);
                        if (Main.netMode == 2)
{
                            NetMessage.SendTileSquare(-1, i, num40);
                        }
                    }
                }
            }
            else if ((Main.tile[i, j].type == 109 || Main.tile[i, j].type == 115) && GrowMoreVines(i, j))
            {
                int maxValue3 = 60;
                if (Main.tile[i, j].type == 115)
                {
                    maxValue3 = 20;
                }
                if (genRand.Next(maxValue3) == 0 && !Main.tile[i, j + 1].active() && !Main.tile[i, j + 1].lava())
                {
                    bool flag8 = false;
                    for (int num41 = j; num41 > j - 10; num41--)
                    {
                        if (Main.tile[i, num41].bottomSlope())
{
                            flag8 = false;
                            break;
                        }
                        if (Main.tile[i, num41].active() && Main.tile[i, num41].type == 109 && !Main.tile[i, num41].bottomSlope())
{
                            flag8 = true;
                            break;
                        }
                    }
                    if (flag8)
                    {
                        int num42 = j + 1;
                        Main.tile[i, num42].type = 115;
                        Main.tile[i, num42].active(active: true);
                        Main.tile[i, num42].CopyPaintAndCoating(Main.tile[i, j]);
                        SquareTileFrame(i, num42);
                        if (Main.netMode == 2)
{
                            NetMessage.SendTileSquare(-1, i, num42);
                        }
                    }
                }
            }
            else if ((Main.tile[i, j].type == 23 || Main.tile[i, j].type == 661 || Main.tile[i, j].type == 636) && GrowMoreVines(i, j))
            {
                int maxValue4 = 60;
                if (Main.tile[i, j].type == 636)
                {
                    maxValue4 = 20;
                }
                if (genRand.Next(maxValue4) == 0 && !Main.tile[i, j + 1].active() && !Main.tile[i, j + 1].lava())
                {
                    bool flag9 = false;
                    for (int num43 = j; num43 > j - 10; num43--)
                    {
                        if (Main.tile[i, num43].bottomSlope())
{
                            flag9 = false;
                            break;
                        }
                        if (Main.tile[i, num43].active() && (Main.tile[i, num43].type == 23 || Main.tile[i, num43].type == 661) && !Main.tile[i, num43].bottomSlope())
{
                            flag9 = true;
                            break;
                        }
                    }
                    if (flag9)
                    {
                        int num44 = j + 1;
                        Main.tile[i, num44].type = 636;
                        Main.tile[i, num44].active(active: true);
                        Main.tile[i, num44].CopyPaintAndCoating(Main.tile[i, j]);
                        SquareTileFrame(i, num44);
                        if (Main.netMode == 2)
{
                            NetMessage.SendTileSquare(-1, i, num44);
                        }
                    }
                }
            }
            else if ((Main.tile[i, j].type == 199 || Main.tile[i, j].type == 662 || Main.tile[i, j].type == 205) && GrowMoreVines(i, j))
            {
                int maxValue5 = 60;
                if (Main.tile[i, j].type == 205)
                {
                    maxValue5 = 20;
                }
                if (genRand.Next(maxValue5) == 0 && !Main.tile[i, j + 1].active() && !Main.tile[i, j + 1].lava())
                {
                    bool flag10 = false;
                    for (int num45 = j; num45 > j - 10; num45--)
                    {
                        if (Main.tile[i, num45].bottomSlope())
{
                            flag10 = false;
                            break;
                        }
                        if (Main.tile[i, num45].active() && (Main.tile[i, num45].type == 199 || Main.tile[i, num45].type == 662) && !Main.tile[i, num45].bottomSlope())
{
                            flag10 = true;
                            break;
                        }
                    }
                    if (flag10)
                    {
                        int num46 = j + 1;
                        Main.tile[i, num46].type = 205;
                        Main.tile[i, num46].active(active: true);
                        Main.tile[i, num46].CopyPaintAndCoating(Main.tile[i, j]);
                        SquareTileFrame(i, num46);
                        if (Main.netMode == 2)
{
                            NetMessage.SendTileSquare(-1, i, num46);
                        }
                    }
                }
            }
            else if ((Main.tile[i, j].type == 633 || Main.tile[i, j].type == 638) && GrowMoreVines(i, j))
            {
                int maxValue6 = 70;
                if (Main.tile[i, j].type == 638)
                {
                    maxValue6 = 7;
                }
                if (genRand.Next(maxValue6) == 0 && !Main.tile[i, j + 1].active() && !Main.tile[i, j + 1].lava())
                {
                    bool flag11 = false;
                    for (int num47 = j; num47 > j - 10; num47--)
                    {
                        if (Main.tile[i, num47].bottomSlope())
{
                            flag11 = false;
                            break;
                        }
                        if (Main.tile[i, num47].active() && Main.tile[i, num47].type == 633 && !Main.tile[i, num47].bottomSlope())
{
                            flag11 = true;
                            break;
                        }
                    }
                    if (flag11)
                    {
                        int num48 = j + 1;
                        Main.tile[i, num48].type = 638;
                        Main.tile[i, num48].active(active: true);
                        Main.tile[i, num48].CopyPaintAndCoating(Main.tile[i, j]);
                        SquareTileFrame(i, num48);
                        if (Main.netMode == 2)
{
                            NetMessage.SendTileSquare(-1, i, num48);
                        }
                    }
                }
            }
        }
        if (!Main.remixWorld && Main.dontStarveWorld && (float)Main.rand.Next(200) < 100f * Main.maxRaining && Main.maxRaining >= 0.2f)
        {
            DontStarveTryWateringTile(i, j);
        }
    }
References Terraria.Tile.active(), Terraria.NPC.AnyNPCs(), Terraria.Tile.BlockColorAndCoating(), Terraria.Tile.bottomSlope(), Terraria.Tile.CopyPaintAndCoating(), Terraria.Main.dontStarveWorld, Terraria.Tile.frameX, Terraria.Main.hardMode, Terraria.Tile.lava(), Terraria.Tile.liquid, Terraria.Main.maxRaining, Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.Tile.nactive(), Terraria.Main.netMode, Terraria.Utilities.UnifiedRandom.Next(), Terraria.Main.raining, Terraria.Main.rand, Terraria.Main.remixWorld, Terraria.ID.TileID.Sets.Conversion.Sand, Terraria.NetMessage.SendData(), Terraria.NetMessage.SendTileSquare(), Terraria.ID.TileID.Sets.SlowlyDiesInWater, Terraria.Enums.SolidTile, Terraria.ID.TileID.Sets.SpreadOverground, Terraria.Main.tile, Terraria.Main.tileAlch, Terraria.Main.tileMoss, Terraria.ID.TileID.Sets.tileMossBrick, Terraria.Tile.type, Terraria.Tile.wall, Terraria.Main.windSpeedCurrent, and Terraria.Main.worldSurface.