Terraria: Terraria.WorldGen.RoomNeeds
RoomNeeds()
static bool Terraria.WorldGen.RoomNeeds (int npcType) inline static
Definition at line 2178 of file WorldGen.cs.
    {
        roomChair = false;
        roomDoor = false;
        roomTable = false;
        roomTorch = false;
        for (int i = 0; i < TileID.Sets.RoomNeeds.CountsAsChair.Length; i++)
        {
            if (houseTile[TileID.Sets.RoomNeeds.CountsAsChair[i]])
            {
                roomChair = true;
                break;
            }
        }
        for (int j = 0; j < TileID.Sets.RoomNeeds.CountsAsTable.Length; j++)
        {
            if (houseTile[TileID.Sets.RoomNeeds.CountsAsTable[j]])
            {
                roomTable = true;
                break;
            }
        }
        for (int k = 0; k < TileID.Sets.RoomNeeds.CountsAsTorch.Length; k++)
        {
            if (houseTile[TileID.Sets.RoomNeeds.CountsAsTorch[k]])
            {
                roomTorch = true;
                break;
            }
        }
        for (int l = 0; l < TileID.Sets.RoomNeeds.CountsAsDoor.Length; l++)
        {
            if (houseTile[TileID.Sets.RoomNeeds.CountsAsDoor[l]])
            {
                roomDoor = true;
                break;
            }
        }
        if (roomChair && roomTable && roomDoor && roomTorch)
        {
            canSpawn = true;
        }
        else
        {
            canSpawn = false;
        }
        return canSpawn;
    }
References Terraria.WorldGen.canSpawn, Terraria.ID.TileID.Sets.RoomNeeds.CountsAsChair, Terraria.ID.TileID.Sets.RoomNeeds.CountsAsDoor, Terraria.ID.TileID.Sets.RoomNeeds.CountsAsTable, Terraria.ID.TileID.Sets.RoomNeeds.CountsAsTorch, Terraria.WorldGen.houseTile, Terraria.WorldGen.roomChair, Terraria.WorldGen.roomDoor, Terraria.WorldGen.roomTable, and Terraria.WorldGen.roomTorch.
Referenced by Terraria.WorldGen.MoveTownNPC(), Terraria.WorldGen.QuickFindHome(), and Terraria.WorldGen.SpawnTownNPC().