Terraria: Terraria.WorldGen.EmptyLiquid
EmptyLiquid()
static bool Terraria.WorldGen.EmptyLiquid (int x, int y) inline static
Definition at line 1342 of file WorldGen.cs.
    {
        if (!InWorld(x, y))
        {
            return false;
        }
        Tile tile = Main.tile[x, y];
        if (tile == null)
        {
            return false;
        }
        tile.liquidType();
        if (tile.nactive() && Main.tileSolid[tile.type] && !Main.tileSolidTop[tile.type])
        {
            return false;
        }
        tile.Clear(TileDataType.Liquid);
        SquareTileFrame(x, y, resetFrame: false);
        if (Main.netMode != 0)
        {
            NetMessage.sendWater(x, y);
        }
        else
        {
            Liquid.AddWater(x, y);
        }
        return true;
    }
References Terraria.Liquid.AddWater(), Terraria.Tile.Clear(), Terraria.WorldGen.InWorld(), Terraria.Tile.liquidType(), Terraria.Tile.nactive(), Terraria.Main.netMode, Terraria.NetMessage.sendWater(), Terraria.WorldGen.SquareTileFrame(), Terraria.Main.tile, Terraria.Main.tileSolid, Terraria.Main.tileSolidTop, and Terraria.Tile.type.
Referenced by Terraria.DelegateMethods.SpreadDry().