Terraria: Terraria.WorldGen.paintTile
paintTile()
static bool Terraria.WorldGen.paintTile (int x, int y, byte color, bool broadCast = false) inline static
    {
        Tile tile = Main.tile[x, y];
        if (tile == null || !tile.active())
        {
            return false;
        }
        byte b = tile.color();
        if (b == color)
        {
            return false;
        }
        paintEffect(x, y, color, b);
        tile.color(color);
        if (broadCast)
        {
            NetMessage.SendData(63, -1, -1, null, x, y, (int)color);
        }
        return true;
    }
References Terraria.Tile.active(), Terraria.Tile.color(), Terraria.NetMessage.SendData(), and Terraria.Main.tile.
Referenced by Terraria.Player.ApplyPaint(), Terraria.MessageBuffer.GetData(), and Terraria.Player.PlaceThing_PaintScrapper_TryScrapping().