Terraria: Terraria.WorldGen.PlantAlch
PlantAlch()
static void Terraria.WorldGen.PlantAlch () inline static
Definition at line 36832 of file WorldGen.cs.
    {
        int num = genRand.Next(20, Main.maxTilesX - 20);
        int num2 = 0;
        for (num2 = (Main.remixWorld ? genRand.Next(20, Main.maxTilesY - 20) : ((genRand.Next(40) == 0) ? genRand.Next((int)(Main.rockLayer + (double)Main.maxTilesY) / 2, Main.maxTilesY - 20) : ((genRand.Next(10) != 0) ? genRand.Next((int)Main.worldSurface, Main.maxTilesY - 20) : genRand.Next(20, Main.maxTilesY - 20)))); num2 < Main.maxTilesY - 20 && !Main.tile[num, num2].active(); num2++)
        {
        }
        if (!Main.tile[num, num2].nactive() || Main.tile[num, num2 - 1].active() || Main.tile[num, num2 - 1].liquid != 0)
        {
            return;
        }
        int num3 = 15;
        int num4 = 5;
        int num5 = 0;
        num3 = (int)((double)num3 * ((double)Main.maxTilesX / 4200.0));
        int num6 = Utils.Clamp(num - num3, 4, Main.maxTilesX - 4);
        int num7 = Utils.Clamp(num + num3, 4, Main.maxTilesX - 4);
        int num8 = Utils.Clamp(num2 - num3, 4, Main.maxTilesY - 4);
        int num9 = Utils.Clamp(num2 + num3, 4, Main.maxTilesY - 4);
        for (int i = num6; i <= num7; i++)
        {
            for (int j = num8; j <= num9; j++)
            {
                if (Main.tileAlch[Main.tile[i, j].type])
                {
                    num5++;
                }
            }
        }
        if (num5 < num4)
        {
            if (Main.tile[num, num2].type == 2 || Main.tile[num, num2].type == 109)
            {
                PlaceAlch(num, num2 - 1, 0);
            }
            if (Main.tile[num, num2].type == 60)
            {
                PlaceAlch(num, num2 - 1, 1);
            }
            if (Main.tile[num, num2].type == 0 || Main.tile[num, num2].type == 59)
            {
                PlaceAlch(num, num2 - 1, 2);
            }
            if (Main.tile[num, num2].type == 23 || Main.tile[num, num2].type == 661 || Main.tile[num, num2].type == 25 || Main.tile[num, num2].type == 203 || Main.tile[num, num2].type == 199 || Main.tile[num, num2].type == 662)
            {
                PlaceAlch(num, num2 - 1, 3);
            }
            if ((Main.tile[num, num2].type == 53 || Main.tile[num, num2].type == 116) && num >= beachDistance && num <= Main.maxTilesX - beachDistance)
            {
                PlaceAlch(num, num2 - 1, 4);
            }
            if (Main.tile[num, num2].type == 57 || Main.tile[num, num2].type == 633)
            {
                PlaceAlch(num, num2 - 1, 5);
            }
            if (Main.tile[num, num2].type == 147 || Main.tile[num, num2].type == 163 || Main.tile[num, num2].type == 164 || Main.tile[num, num2].type == 161 || Main.tile[num, num2].type == 200)
            {
                PlaceAlch(num, num2 - 1, 6);
            }
            if (Main.tile[num, num2 - 1].active() && Main.netMode == 2)
            {
                NetMessage.SendTileSquare(-1, num, num2 - 1);
            }
        }
    }
References Terraria.Tile.active(), Terraria.Tile.liquid, Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.Tile.nactive(), Terraria.Main.netMode, Terraria.Main.remixWorld, Terraria.NetMessage.SendTileSquare(), Terraria.Main.tile, Terraria.Main.tileAlch, Terraria.Tile.type, and Terraria.Main.worldSurface.