Terraria: Terraria.WorldGen.PaintThePyramids
PaintThePyramids()
static void Terraria.WorldGen.PaintThePyramids (byte tilePaintColor, byte wallPaintColor) inline static private
Definition at line 17067 of file WorldGen.cs.
    {
        for (int i = 0; i < Main.maxTilesX; i++)
        {
            for (int j = 0; j < Main.maxTilesY; j++)
            {
                Tile tile = Main.tile[i, j];
                if (tile.active() && tile.type == 151)
                {
                    tile.color(tilePaintColor);
                }
                if (tile.wall == 34)
                {
                    tile.wallColor(wallPaintColor);
                }
            }
        }
    }
References Terraria.Tile.active(), Terraria.Tile.color(), Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.Main.tile, Terraria.Tile.type, Terraria.Tile.wall, and Terraria.Tile.wallColor().