Terraria: Terraria.WorldGen.HasAnyWireNearby
HasAnyWireNearby()
static bool Terraria.WorldGen.HasAnyWireNearby (int sourceX, int sourceY, int boxSpread) inline static
Definition at line 63029 of file WorldGen.cs.
    {
        int num = Utils.Clamp(sourceX - boxSpread, 0, Main.maxTilesX - 1);
        int num2 = Utils.Clamp(sourceX + boxSpread, 0, Main.maxTilesX - 1);
        int num3 = Utils.Clamp(sourceY - boxSpread, 0, Main.maxTilesY - 1);
        int num4 = Utils.Clamp(sourceY + boxSpread, 0, Main.maxTilesY - 1);
        for (int i = num; i <= num2; i++)
        {
            for (int j = num3; j <= num4; j++)
            {
                Tile tile = Main.tile[i, j];
                if (tile != null && (tile.wire() || tile.wire2() || tile.wire3() || tile.wire4()))
                {
                    return true;
                }
            }
        }
        return false;
    }
References Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.Main.tile, Terraria.Tile.wire(), Terraria.Tile.wire2(), Terraria.Tile.wire3(), and Terraria.Tile.wire4().