Terraria: Terraria.WorldGen.CanPlaceSink
CanPlaceSink()
static bool Terraria.WorldGen.CanPlaceSink (int x, int y, ushort type, int style) inline static
    {
        if (x < 5 || x > Main.maxTilesX - 5 || y < 5 || y > Main.maxTilesY - 5)
        {
            return false;
        }
        bool result = true;
        x--;
        y--;
        for (int i = 0; i < 2; i++)
        {
            Tile tileSafely;
            for (int j = 0; j < 2; j++)
            {
                tileSafely = Framing.GetTileSafely(x + i, y + j);
                if (tileSafely.active())
                {
                    result = false;
                }
            }
            tileSafely = Framing.GetTileSafely(x + i, y + 2);
            if (!tileSafely.nactive() || !SolidTile(tileSafely))
            {
                result = false;
            }
        }
        return result;
    }
References Terraria.Tile.active(), Terraria.Framing.GetTileSafely(), Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.Tile.nactive(), and Terraria.Enums.SolidTile.