Terraria: Terraria.WorldGen.hardUpdateWorld
hardUpdateWorld()
static void Terraria.WorldGen.hardUpdateWorld (int i, int j) inline static
Definition at line 60111 of file WorldGen.cs.
    {
        if (!Main.hardMode || Main.tile[i, j].inActive())
        {
            return;
        }
        int type = Main.tile[i, j].type;
        if (type > 0 && type < TileID.Count && TileID.Sets.CanGrowCrystalShards[type] && ((double)j > Main.rockLayer || Main.remixWorld) && genRand.Next(5) == 0)
        {
            int num = genRand.Next(4);
            int num2 = 0;
            int num3 = 0;
            switch (num)
            {
            case 0:
                num2 = -1;
                break;
            case 1:
                num2 = 1;
                break;
            default:
                num3 = ((num != 0) ? 1 : (-1));
                break;
            }
            if (!Main.tile[i + num2, j + num3].active())
            {
                int num4 = 0;
                int num5 = 6;
                for (int k = i - num5; k <= i + num5; k++)
                {
                    for (int l = j - num5; l <= j + num5; l++)
                    {
                        if (Main.tile[k, l].active() && Main.tile[k, l].type == 129)
{
                            num4++;
                        }
                    }
                }
                if (num4 < 2)
                {
                    int style = (short)genRand.Next(18);
                    if (genRand.Next(50) == 0)
                    {
                        style = (short)(18 + genRand.Next(6));
                    }
                    PlaceTile(i + num2, j + num3, 129, mute: true, forced: false, -1, style);
                    NetMessage.SendTileSquare(-1, i + num2, j + num3);
                }
            }
        }
        if ((double)j > (Main.worldSurface + Main.rockLayer) / 2.0 || Main.remixWorld)
        {
            if (type == 60 && genRand.Next(300) == 0)
            {
                int num6 = i + genRand.Next(-10, 11);
                int num7 = j + genRand.Next(-10, 11);
                if (InWorld(num6, num7, 2) && Main.tile[num6, num7].active() && Main.tile[num6, num7].type == 59 && (!Main.tile[num6, num7 - 1].active() || (Main.tile[num6, num7 - 1].type != 5 && Main.tile[num6, num7 - 1].type != 236 && Main.tile[num6, num7 - 1].type != 238)) && Chlorophyte(num6, num7))
                {
                    Main.tile[num6, num7].type = 211;
                    SquareTileFrame(num6, num7);
                    if (Main.netMode == 2)
                    {
                        NetMessage.SendTileSquare(-1, num6, num7);
                    }
                }
            }
            if (type == 211 || type == 346)
            {
                int num8 = i;
                int num9 = j;
                if (genRand.Next(3) != 0)
                {
                    int num10 = genRand.Next(4);
                    if (num10 == 0)
                    {
                        num8++;
                    }
                    if (num10 == 1)
                    {
                        num8--;
                    }
                    if (num10 == 2)
                    {
                        num9++;
                    }
                    if (num10 == 3)
                    {
                        num9--;
                    }
                    if (InWorld(num8, num9, 2) && Main.tile[num8, num9].active() && (Main.tile[num8, num9].type == 59 || Main.tile[num8, num9].type == 60) && Chlorophyte(num8, num9))
                    {
                        Main.tile[num8, num9].type = 211;
                        SquareTileFrame(num8, num9);
                        if (Main.netMode == 2)
{
                            NetMessage.SendTileSquare(-1, num8, num9);
                        }
                    }
                }
                bool flag = true;
                while (flag)
                {
                    flag = false;
                    num8 = i + Main.rand.Next(-6, 7);
                    num9 = j + Main.rand.Next(-6, 7);
                    if (!InWorld(num8, num9, 2) || !Main.tile[num8, num9].active())
                    {
                        continue;
                    }
                    if (Main.tile[num8, num9].type == 661 || Main.tile[num8, num9].type == 662 || Main.tile[num8, num9].type == 23 || Main.tile[num8, num9].type == 199 || Main.tile[num8, num9].type == 2 || Main.tile[num8, num9].type == 477 || Main.tile[num8, num9].type == 492 || Main.tile[num8, num9].type == 109)
                    {
                        Main.tile[num8, num9].type = 60;
                        SquareTileFrame(num8, num9);
                        if (Main.netMode == 2)
{
                            NetMessage.SendTileSquare(-1, num8, num9);
                        }
                        flag = true;
                    }
                    else if (Main.tile[num8, num9].type == 0)
                    {
                        Main.tile[num8, num9].type = 59;
                        SquareTileFrame(num8, num9);
                        if (Main.netMode == 2)
{
                            NetMessage.SendTileSquare(-1, num8, num9);
                        }
                        flag = true;
                    }
                    else if (Main.tile[num8, num9].type == 25 || Main.tile[num8, num9].type == 203)
                    {
                        Main.tile[num8, num9].type = 1;
                        SquareTileFrame(num8, num9);
                        if (Main.netMode == 2)
{
                            NetMessage.SendTileSquare(-1, num8, num9);
                        }
                        flag = true;
                    }
                    else if (Main.tile[num8, num9].type == 112 || Main.tile[num8, num9].type == 234)
                    {
                        Main.tile[num8, num9].type = 53;
                        SquareTileFrame(num8, num9);
                        if (Main.netMode == 2)
{
                            NetMessage.SendTileSquare(-1, num8, num9);
                        }
                        flag = true;
                    }
                    else if (Main.tile[num8, num9].type == 398 || Main.tile[num8, num9].type == 399)
                    {
                        Main.tile[num8, num9].type = 397;
                        SquareTileFrame(num8, num9);
                        if (Main.netMode == 2)
{
                            NetMessage.SendTileSquare(-1, num8, num9);
                        }
                        flag = true;
                    }
                    else if (Main.tile[num8, num9].type == 400 || Main.tile[num8, num9].type == 401)
                    {
                        Main.tile[num8, num9].type = 396;
                        SquareTileFrame(num8, num9);
                        if (Main.netMode == 2)
{
                            NetMessage.SendTileSquare(-1, num8, num9);
                        }
                        flag = true;
                    }
                    else if (Main.tile[num8, num9].type == 24 || Main.tile[num8, num9].type == 201 || Main.tile[num8, num9].type == 32 || Main.tile[num8, num9].type == 352 || Main.tile[num8, num9].type == 636 || Main.tile[num8, num9].type == 205)
                    {
                        KillTile(num8, num9);
                        if (Main.netMode == 2)
{
                            NetMessage.SendTileSquare(-1, num8, num9);
                        }
                        flag = true;
                    }
                }
            }
        }
        if ((NPC.downedPlantBoss && genRand.Next(2) != 0) || !AllowedToSpreadInfections)
        {
            return;
        }
        if (type == 23 || type == 25 || type == 32 || type == 112 || type == 163 || type == 400 || type == 398 || type == 636 || type == 661)
        {
            bool flag2 = true;
            while (flag2)
            {
                flag2 = false;
                int num11 = i + genRand.Next(-3, 4);
                int num12 = j + genRand.Next(-3, 4);
                if (!InWorld(num11, num12, 10))
                {
                    continue;
                }
                if (nearbyChlorophyte(num11, num12))
                {
                    ChlorophyteDefense(num11, num12);
                }
                else
                {
                    if (CountNearBlocksTypes(num11, num12, 2, 1, 27) > 0)
                    {
                        continue;
                    }
                    if (Main.tile[num11, num12].type == 2)
                    {
                        if (genRand.Next(2) == 0)
{
                            flag2 = true;
                        }
                        Main.tile[num11, num12].type = 23;
                        SquareTileFrame(num11, num12);
                        NetMessage.SendTileSquare(-1, num11, num12);
                    }
                    else if (Main.tile[num11, num12].type == 1 || Main.tileMoss[Main.tile[num11, num12].type])
                    {
                        if (genRand.Next(2) == 0)
{
                            flag2 = true;
                        }
                        Main.tile[num11, num12].type = 25;
                        SquareTileFrame(num11, num12);
                        NetMessage.SendTileSquare(-1, num11, num12);
                    }
                    else if (Main.tile[num11, num12].type == 53)
                    {
                        if (genRand.Next(2) == 0)
{
                            flag2 = true;
                        }
                        Main.tile[num11, num12].type = 112;
                        SquareTileFrame(num11, num12);
                        NetMessage.SendTileSquare(-1, num11, num12);
                    }
                    else if (Main.tile[num11, num12].type == 396)
                    {
                        if (genRand.Next(2) == 0)
{
                            flag2 = true;
                        }
                        Main.tile[num11, num12].type = 400;
                        SquareTileFrame(num11, num12);
                        NetMessage.SendTileSquare(-1, num11, num12);
                    }
                    else if (Main.tile[num11, num12].type == 397)
                    {
                        if (genRand.Next(2) == 0)
{
                            flag2 = true;
                        }
                        Main.tile[num11, num12].type = 398;
                        SquareTileFrame(num11, num12);
                        NetMessage.SendTileSquare(-1, num11, num12);
                    }
                    else if (Main.tile[num11, num12].type == 60)
                    {
                        if (genRand.Next(2) == 0)
{
                            flag2 = true;
                        }
                        Main.tile[num11, num12].type = 661;
                        SquareTileFrame(num11, num12);
                        NetMessage.SendTileSquare(-1, num11, num12);
                    }
                    else if (Main.tile[num11, num12].type == 69)
                    {
                        if (genRand.Next(2) == 0)
{
                            flag2 = true;
                        }
                        Main.tile[num11, num12].type = 32;
                        SquareTileFrame(num11, num12);
                        NetMessage.SendTileSquare(-1, num11, num12);
                    }
                    else if (Main.tile[num11, num12].type == 161)
                    {
                        if (genRand.Next(2) == 0)
{
                            flag2 = true;
                        }
                        Main.tile[num11, num12].type = 163;
                        SquareTileFrame(num11, num12);
                        NetMessage.SendTileSquare(-1, num11, num12);
                    }
                }
            }
        }
        if (type == 199 || type == 200 || type == 201 || type == 203 || type == 205 || type == 234 || type == 352 || type == 401 || type == 399 || type == 662)
        {
            bool flag3 = true;
            while (flag3)
            {
                flag3 = false;
                int num13 = i + genRand.Next(-3, 4);
                int num14 = j + genRand.Next(-3, 4);
                if (!InWorld(num13, num14, 10))
                {
                    continue;
                }
                if (nearbyChlorophyte(num13, num14))
                {
                    ChlorophyteDefense(num13, num14);
                }
                else
                {
                    if (CountNearBlocksTypes(num13, num14, 2, 1, 27) > 0)
                    {
                        continue;
                    }
                    if (Main.tile[num13, num14].type == 2)
                    {
                        if (genRand.Next(2) == 0)
{
                            flag3 = true;
                        }
                        Main.tile[num13, num14].type = 199;
                        SquareTileFrame(num13, num14);
                        NetMessage.SendTileSquare(-1, num13, num14);
                    }
                    else if (Main.tile[num13, num14].type == 1 || Main.tileMoss[Main.tile[num13, num14].type])
                    {
                        if (genRand.Next(2) == 0)
{
                            flag3 = true;
                        }
                        Main.tile[num13, num14].type = 203;
                        SquareTileFrame(num13, num14);
                        NetMessage.SendTileSquare(-1, num13, num14);
                    }
                    else if (Main.tile[num13, num14].type == 53)
                    {
                        if (genRand.Next(2) == 0)
{
                            flag3 = true;
                        }
                        Main.tile[num13, num14].type = 234;
                        SquareTileFrame(num13, num14);
                        NetMessage.SendTileSquare(-1, num13, num14);
                    }
                    else if (Main.tile[num13, num14].type == 396)
                    {
                        if (genRand.Next(2) == 0)
{
                            flag3 = true;
                        }
                        Main.tile[num13, num14].type = 401;
                        SquareTileFrame(num13, num14);
                        NetMessage.SendTileSquare(-1, num13, num14);
                    }
                    else if (Main.tile[num13, num14].type == 397)
                    {
                        if (genRand.Next(2) == 0)
{
                            flag3 = true;
                        }
                        Main.tile[num13, num14].type = 399;
                        SquareTileFrame(num13, num14);
                        NetMessage.SendTileSquare(-1, num13, num14);
                    }
                    else if (Main.tile[num13, num14].type == 60)
                    {
                        if (genRand.Next(2) == 0)
{
                            flag3 = true;
                        }
                        Main.tile[num13, num14].type = 662;
                        SquareTileFrame(num13, num14);
                        NetMessage.SendTileSquare(-1, num13, num14);
                    }
                    else if (Main.tile[num13, num14].type == 69)
                    {
                        if (genRand.Next(2) == 0)
{
                            flag3 = true;
                        }
                        Main.tile[num13, num14].type = 352;
                        SquareTileFrame(num13, num14);
                        NetMessage.SendTileSquare(-1, num13, num14);
                    }
                    else if (Main.tile[num13, num14].type == 161)
                    {
                        if (genRand.Next(2) == 0)
{
                            flag3 = true;
                        }
                        Main.tile[num13, num14].type = 200;
                        SquareTileFrame(num13, num14);
                        NetMessage.SendTileSquare(-1, num13, num14);
                    }
                }
            }
        }
        if (type != 109 && type != 110 && type != 113 && type != 115 && type != 116 && type != 117 && type != 164 && type != 402 && type != 403 && type != 492)
        {
            return;
        }
        bool flag4 = true;
        while (flag4)
        {
            flag4 = false;
            int num15 = i + genRand.Next(-3, 4);
            int num16 = j + genRand.Next(-3, 4);
            if (!InWorld(num15, num16, 10) || CountNearBlocksTypes(num15, num16, 2, 1, 27) > 0)
            {
                continue;
            }
            if (Main.tile[num15, num16].type == 2)
            {
                if (genRand.Next(2) == 0)
                {
                    flag4 = true;
                }
                Main.tile[num15, num16].type = 109;
                SquareTileFrame(num15, num16);
                NetMessage.SendTileSquare(-1, num15, num16);
            }
            else if (Main.tile[num15, num16].type == 477)
            {
                if (genRand.Next(2) == 0)
                {
                    flag4 = true;
                }
                Main.tile[num15, num16].type = 492;
                SquareTileFrame(num15, num16);
                NetMessage.SendTileSquare(-1, num15, num16);
            }
            else if (Main.tile[num15, num16].type == 1 || Main.tileMoss[Main.tile[num15, num16].type])
            {
                if (genRand.Next(2) == 0)
                {
                    flag4 = true;
                }
                Main.tile[num15, num16].type = 117;
                SquareTileFrame(num15, num16);
                NetMessage.SendTileSquare(-1, num15, num16);
            }
            else if (Main.tile[num15, num16].type == 53)
            {
                if (genRand.Next(2) == 0)
                {
                    flag4 = true;
                }
                Main.tile[num15, num16].type = 116;
                SquareTileFrame(num15, num16);
                NetMessage.SendTileSquare(-1, num15, num16);
            }
            else if (Main.tile[num15, num16].type == 396)
            {
                if (genRand.Next(2) == 0)
                {
                    flag4 = true;
                }
                Main.tile[num15, num16].type = 403;
                SquareTileFrame(num15, num16);
                NetMessage.SendTileSquare(-1, num15, num16);
            }
            else if (Main.tile[num15, num16].type == 397)
            {
                if (genRand.Next(2) == 0)
                {
                    flag4 = true;
                }
                Main.tile[num15, num16].type = 402;
                SquareTileFrame(num15, num16);
                NetMessage.SendTileSquare(-1, num15, num16);
            }
            else if (Main.tile[num15, num16].type == 161)
            {
                if (genRand.Next(2) == 0)
                {
                    flag4 = true;
                }
                Main.tile[num15, num16].type = 164;
                SquareTileFrame(num15, num16);
                NetMessage.SendTileSquare(-1, num15, num16);
            }
        }
    }
References Terraria.Tile.active(), Terraria.ID.TileID.Sets.CanGrowCrystalShards, Terraria.Enums.Chlorophyte, Terraria.ID.TileID.Count, Terraria.NPC.downedPlantBoss, Terraria.Main.hardMode, Terraria.Tile.inActive(), Terraria.Main.netMode, Terraria.Utilities.UnifiedRandom.Next(), Terraria.Main.rand, Terraria.Main.remixWorld, Terraria.Main.rockLayer, Terraria.NetMessage.SendTileSquare(), Terraria.Main.tile, Terraria.Main.tileMoss, and Terraria.Tile.type.