Terraria: Terraria.WorldGen.CreateNewWorld
CreateNewWorld()
static Task Terraria.WorldGen.CreateNewWorld (GenerationProgress progress = null) inline static
Definition at line 3048 of file WorldGen.cs.
    {
        generatingWorld = true;
        Main.rand = new UnifiedRandom(Main.ActiveWorldFileData.Seed);
        gen = true;
        Main.menuMode = 888;
        try
        {
            Main.MenuUI.SetState(new UIWorldLoad());
        }
        catch
        {
        }
        return Task.Factory.StartNew(worldGenCallback, progress);
    }
References Terraria.Main.ActiveWorldFileData, System.Threading.Tasks.Task< TResult >.Factory, Terraria.WorldGen.gen, Terraria.WorldGen.generatingWorld, Terraria.Main.MenuUI, and Terraria.WorldGen.worldGenCallback().
Referenced by Terraria.Main.DedServ(), Terraria.GameContent.UI.States.UIWorldCreation.FinishCreatingWorld(), and Terraria.Main.OnSeedSelected().