Terraria: Terraria.WorldGen.DungeonEnt
DungeonEnt()
static void Terraria.WorldGen.DungeonEnt (int i, int j, ushort tileType, int wallType) inline static
Definition at line 30217 of file WorldGen.cs.
    {
        //IL_00a5: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d5: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f8: Unknown result type (might be due to invalid IL or missing references)
        //IL_011c: Unknown result type (might be due to invalid IL or missing references)
        //IL_013f: Unknown result type (might be due to invalid IL or missing references)
        //IL_057b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0590: Unknown result type (might be due to invalid IL or missing references)
        //IL_05a6: Unknown result type (might be due to invalid IL or missing references)
        //IL_05bb: Unknown result type (might be due to invalid IL or missing references)
        //IL_0660: Unknown result type (might be due to invalid IL or missing references)
        //IL_067f: Unknown result type (might be due to invalid IL or missing references)
        //IL_069f: Unknown result type (might be due to invalid IL or missing references)
        //IL_06be: Unknown result type (might be due to invalid IL or missing references)
        //IL_0778: Unknown result type (might be due to invalid IL or missing references)
        //IL_078d: Unknown result type (might be due to invalid IL or missing references)
        //IL_07a3: Unknown result type (might be due to invalid IL or missing references)
        //IL_07b8: Unknown result type (might be due to invalid IL or missing references)
        //IL_0859: Unknown result type (might be due to invalid IL or missing references)
        //IL_086e: Unknown result type (might be due to invalid IL or missing references)
        //IL_09bb: Unknown result type (might be due to invalid IL or missing references)
        //IL_09de: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a02: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a25: Unknown result type (might be due to invalid IL or missing references)
        //IL_08d2: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c2a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c3f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0adb: Unknown result type (might be due to invalid IL or missing references)
        //IL_0abe: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f8b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0fa0: Unknown result type (might be due to invalid IL or missing references)
        //IL_0fb6: Unknown result type (might be due to invalid IL or missing references)
        //IL_0fcb: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ebf: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ed4: Unknown result type (might be due to invalid IL or missing references)
        //IL_0eea: Unknown result type (might be due to invalid IL or missing references)
        //IL_0eff: Unknown result type (might be due to invalid IL or missing references)
        //IL_106b: Unknown result type (might be due to invalid IL or missing references)
        //IL_14b2: Unknown result type (might be due to invalid IL or missing references)
        //IL_14c7: Unknown result type (might be due to invalid IL or missing references)
        //IL_1665: Unknown result type (might be due to invalid IL or missing references)
        //IL_167a: Unknown result type (might be due to invalid IL or missing references)
        //IL_1690: Unknown result type (might be due to invalid IL or missing references)
        //IL_16a5: Unknown result type (might be due to invalid IL or missing references)
        //IL_1563: Unknown result type (might be due to invalid IL or missing references)
        //IL_1578: Unknown result type (might be due to invalid IL or missing references)
        //IL_1736: Unknown result type (might be due to invalid IL or missing references)
        //IL_173d: Unknown result type (might be due to invalid IL or missing references)
        int num = 60;
        for (int k = i - num; k < i + num; k++)
        {
            for (int l = j - num; l < j + num; l++)
            {
                if (InWorld(k, l))
                {
                    Main.tile[k, l].liquid = 0;
                    Main.tile[k, l].lava(lava: false);
                    Main.tile[k, l].Clear(TileDataType.Slope);
                }
            }
        }
        double dxStrength = GenVars.dxStrength1;
        double dyStrength = GenVars.dyStrength1;
        Vector2D val = default(Vector2D);
        val.X = i;
        val.Y = (double)j - dyStrength / 2.0;
        GenVars.dMinY = (int)val.Y;
        int num2 = 1;
        if (i > Main.maxTilesX / 2)
        {
            num2 = -1;
        }
        if (drunkWorldGen || getGoodWorldGen)
        {
            num2 *= -1;
        }
        int num3 = (int)(val.X - dxStrength * 0.6 - (double)genRand.Next(2, 5));
        int num4 = (int)(val.X + dxStrength * 0.6 + (double)genRand.Next(2, 5));
        int num5 = (int)(val.Y - dyStrength * 0.6 - (double)genRand.Next(2, 5));
        int num6 = (int)(val.Y + dyStrength * 0.6 + (double)genRand.Next(8, 16));
        if (num3 < 0)
        {
            num3 = 0;
        }
        if (num4 > Main.maxTilesX)
        {
            num4 = Main.maxTilesX;
        }
        if (num5 < 0)
        {
            num5 = 0;
        }
        if (num6 > Main.maxTilesY)
        {
            num6 = Main.maxTilesY;
        }
        for (int m = num3; m < num4; m++)
        {
            for (int n = num5; n < num6; n++)
            {
                Main.tile[m, n].liquid = 0;
                if (Main.tile[m, n].wall != wallType)
                {
                    Main.tile[m, n].wall = 0;
                    if (m > num3 + 1 && m < num4 - 2 && n > num5 + 1 && n < num6 - 2)
                    {
                        Main.tile[m, n].wall = (ushort)wallType;
                    }
                    Main.tile[m, n].active(active: true);
                    Main.tile[m, n].type = tileType;
                    Main.tile[m, n].Clear(TileDataType.Slope);
                }
            }
        }
        int num7 = num3;
        int num8 = num3 + 5 + genRand.Next(4);
        int num9 = num5 - 3 - genRand.Next(3);
        int num10 = num5;
        for (int num11 = num7; num11 < num8; num11++)
        {
            for (int num12 = num9; num12 < num10; num12++)
            {
                Main.tile[num11, num12].liquid = 0;
                if (Main.tile[num11, num12].wall != wallType)
                {
                    Main.tile[num11, num12].active(active: true);
                    Main.tile[num11, num12].type = tileType;
                    Main.tile[num11, num12].Clear(TileDataType.Slope);
                }
            }
        }
        num7 = num4 - 5 - genRand.Next(4);
        num8 = num4;
        num9 = num5 - 3 - genRand.Next(3);
        num10 = num5;
        for (int num13 = num7; num13 < num8; num13++)
        {
            for (int num14 = num9; num14 < num10; num14++)
            {
                Main.tile[num13, num14].liquid = 0;
                if (Main.tile[num13, num14].wall != wallType)
                {
                    Main.tile[num13, num14].active(active: true);
                    Main.tile[num13, num14].type = tileType;
                    Main.tile[num13, num14].Clear(TileDataType.Slope);
                }
            }
        }
        int num15 = 1 + genRand.Next(2);
        int num16 = 2 + genRand.Next(4);
        int num17 = 0;
        for (int num18 = num3; num18 < num4; num18++)
        {
            for (int num19 = num5 - num15; num19 < num5; num19++)
            {
                Main.tile[num18, num19].liquid = 0;
                if (Main.tile[num18, num19].wall != wallType)
                {
                    Main.tile[num18, num19].active(active: true);
                    Main.tile[num18, num19].type = tileType;
                    Main.tile[num18, num19].Clear(TileDataType.Slope);
                }
            }
            num17++;
            if (num17 >= num16)
            {
                num18 += num16;
                num17 = 0;
            }
        }
        for (int num20 = num3; num20 < num4; num20++)
        {
            for (int num21 = num6; (double)num21 < Main.worldSurface; num21++)
            {
                Main.tile[num20, num21].liquid = 0;
                if (!Main.wallDungeon[Main.tile[num20, num21].wall])
                {
                    Main.tile[num20, num21].active(active: true);
                    Main.tile[num20, num21].type = tileType;
                }
                if (num20 > num3 && num20 < num4 - 1)
                {
                    Main.tile[num20, num21].wall = (ushort)wallType;
                }
                Main.tile[num20, num21].Clear(TileDataType.Slope);
            }
        }
        num3 = (int)(val.X - dxStrength * 0.6);
        num4 = (int)(val.X + dxStrength * 0.6);
        num5 = (int)(val.Y - dyStrength * 0.6);
        num6 = (int)(val.Y + dyStrength * 0.6);
        if (num3 < 0)
        {
            num3 = 0;
        }
        if (num4 > Main.maxTilesX)
        {
            num4 = Main.maxTilesX;
        }
        if (num5 < 0)
        {
            num5 = 0;
        }
        if (num6 > Main.maxTilesY)
        {
            num6 = Main.maxTilesY;
        }
        for (int num22 = num3; num22 < num4; num22++)
        {
            for (int num23 = num5; num23 < num6; num23++)
            {
                Main.tile[num22, num23].liquid = 0;
                Main.tile[num22, num23].wall = (ushort)wallType;
                Main.tile[num22, num23].Clear(TileDataType.Slope);
            }
        }
        num3 = (int)(val.X - dxStrength * 0.6 - 1.0);
        num4 = (int)(val.X + dxStrength * 0.6 + 1.0);
        num5 = (int)(val.Y - dyStrength * 0.6 - 1.0);
        num6 = (int)(val.Y + dyStrength * 0.6 + 1.0);
        if (num3 < 0)
        {
            num3 = 0;
        }
        if (num4 > Main.maxTilesX)
        {
            num4 = Main.maxTilesX;
        }
        if (num5 < 0)
        {
            num5 = 0;
        }
        if (num6 > Main.maxTilesY)
        {
            num6 = Main.maxTilesY;
        }
        if (drunkWorldGen)
        {
            num3 -= 4;
        }
        for (int num24 = num3; num24 < num4; num24++)
        {
            for (int num25 = num5; num25 < num6; num25++)
            {
                Main.tile[num24, num25].liquid = 0;
                Main.tile[num24, num25].wall = (ushort)wallType;
                Main.tile[num24, num25].Clear(TileDataType.Slope);
            }
        }
        num3 = (int)(val.X - dxStrength * 0.5);
        num4 = (int)(val.X + dxStrength * 0.5);
        num5 = (int)(val.Y - dyStrength * 0.5);
        num6 = (int)(val.Y + dyStrength * 0.5);
        if (num3 < 0)
        {
            num3 = 0;
        }
        if (num4 > Main.maxTilesX)
        {
            num4 = Main.maxTilesX;
        }
        if (num5 < 0)
        {
            num5 = 0;
        }
        if (num6 > Main.maxTilesY)
        {
            num6 = Main.maxTilesY;
        }
        for (int num26 = num3; num26 < num4; num26++)
        {
            for (int num27 = num5; num27 < num6; num27++)
            {
                Main.tile[num26, num27].liquid = 0;
                Main.tile[num26, num27].active(active: false);
                Main.tile[num26, num27].wall = (ushort)wallType;
            }
        }
        int num28 = (int)val.X;
        int num29 = num6;
        for (int num30 = 0; num30 < 20; num30++)
        {
            num28 = (int)val.X - num30;
            if (!Main.tile[num28, num29].active() && Main.wallDungeon[Main.tile[num28, num29].wall])
            {
                GenVars.dungeonPlatformX[GenVars.numDungeonPlatforms] = num28;
                GenVars.dungeonPlatformY[GenVars.numDungeonPlatforms] = num29;
                GenVars.numDungeonPlatforms++;
                break;
            }
            num28 = (int)val.X + num30;
            if (!Main.tile[num28, num29].active() && Main.wallDungeon[Main.tile[num28, num29].wall])
            {
                GenVars.dungeonPlatformX[GenVars.numDungeonPlatforms] = num28;
                GenVars.dungeonPlatformY[GenVars.numDungeonPlatforms] = num29;
                GenVars.numDungeonPlatforms++;
                break;
            }
        }
        val.X += dxStrength * 0.6 * (double)num2;
        val.Y += dyStrength * 0.5;
        dxStrength = GenVars.dxStrength2;
        dyStrength = GenVars.dyStrength2;
        val.X += dxStrength * 0.55 * (double)num2;
        val.Y -= dyStrength * 0.5;
        num3 = (int)(val.X - dxStrength * 0.6 - (double)genRand.Next(1, 3));
        num4 = (int)(val.X + dxStrength * 0.6 + (double)genRand.Next(1, 3));
        num5 = (int)(val.Y - dyStrength * 0.6 - (double)genRand.Next(1, 3));
        num6 = (int)(val.Y + dyStrength * 0.6 + (double)genRand.Next(6, 16));
        if (num3 < 0)
        {
            num3 = 0;
        }
        if (num4 > Main.maxTilesX)
        {
            num4 = Main.maxTilesX;
        }
        if (num5 < 0)
        {
            num5 = 0;
        }
        if (num6 > Main.maxTilesY)
        {
            num6 = Main.maxTilesY;
        }
        for (int num31 = num3; num31 < num4; num31++)
        {
            for (int num32 = num5; num32 < num6; num32++)
            {
                Main.tile[num31, num32].liquid = 0;
                if (Main.tile[num31, num32].wall == wallType)
                {
                    continue;
                }
                bool flag = true;
                if (num2 < 0)
                {
                    if ((double)num31 < val.X - dxStrength * 0.5)
                    {
                        flag = false;
                    }
                }
                else if ((double)num31 > val.X + dxStrength * 0.5 - 1.0)
                {
                    flag = false;
                }
                if (flag)
                {
                    Main.tile[num31, num32].wall = 0;
                    Main.tile[num31, num32].active(active: true);
                    Main.tile[num31, num32].type = tileType;
                    Main.tile[num31, num32].Clear(TileDataType.Slope);
                }
            }
        }
        for (int num33 = num3; num33 < num4; num33++)
        {
            for (int num34 = num6; (double)num34 < Main.worldSurface; num34++)
            {
                Main.tile[num33, num34].liquid = 0;
                if (!Main.wallDungeon[Main.tile[num33, num34].wall])
                {
                    Main.tile[num33, num34].active(active: true);
                    Main.tile[num33, num34].type = tileType;
                }
                Main.tile[num33, num34].wall = (ushort)wallType;
                Main.tile[num33, num34].Clear(TileDataType.Slope);
            }
        }
        num3 = (int)(val.X - dxStrength * 0.5);
        num4 = (int)(val.X + dxStrength * 0.5);
        num7 = num3;
        if (num2 < 0)
        {
            num7++;
        }
        num8 = num7 + 5 + genRand.Next(4);
        num9 = num5 - 3 - genRand.Next(3);
        num10 = num5;
        for (int num35 = num7; num35 < num8; num35++)
        {
            for (int num36 = num9; num36 < num10; num36++)
            {
                Main.tile[num35, num36].liquid = 0;
                if (Main.tile[num35, num36].wall != wallType)
                {
                    Main.tile[num35, num36].active(active: true);
                    Main.tile[num35, num36].type = tileType;
                    Main.tile[num35, num36].Clear(TileDataType.Slope);
                }
            }
        }
        num7 = num4 - 5 - genRand.Next(4);
        num8 = num4;
        num9 = num5 - 3 - genRand.Next(3);
        num10 = num5;
        for (int num37 = num7; num37 < num8; num37++)
        {
            for (int num38 = num9; num38 < num10; num38++)
            {
                Main.tile[num37, num38].liquid = 0;
                if (Main.tile[num37, num38].wall != wallType)
                {
                    Main.tile[num37, num38].active(active: true);
                    Main.tile[num37, num38].type = tileType;
                    Main.tile[num37, num38].Clear(TileDataType.Slope);
                }
            }
        }
        num15 = 1 + genRand.Next(2);
        num16 = 2 + genRand.Next(4);
        num17 = 0;
        if (num2 < 0)
        {
            num4++;
        }
        for (int num39 = num3 + 1; num39 < num4 - 1; num39++)
        {
            for (int num40 = num5 - num15; num40 < num5; num40++)
            {
                Main.tile[num39, num40].liquid = 0;
                if (Main.tile[num39, num40].wall != wallType)
                {
                    Main.tile[num39, num40].active(active: true);
                    Main.tile[num39, num40].type = tileType;
                    Main.tile[num39, num40].Clear(TileDataType.Slope);
                }
            }
            num17++;
            if (num17 >= num16)
            {
                num39 += num16;
                num17 = 0;
            }
        }
        if (!drunkWorldGen)
        {
            num3 = (int)(val.X - dxStrength * 0.6);
            num4 = (int)(val.X + dxStrength * 0.6);
            num5 = (int)(val.Y - dyStrength * 0.6);
            num6 = (int)(val.Y + dyStrength * 0.6);
            if (num3 < 0)
            {
                num3 = 0;
            }
            if (num4 > Main.maxTilesX)
            {
                num4 = Main.maxTilesX;
            }
            if (num5 < 0)
            {
                num5 = 0;
            }
            if (num6 > Main.maxTilesY)
            {
                num6 = Main.maxTilesY;
            }
            for (int num41 = num3; num41 < num4; num41++)
            {
                for (int num42 = num5; num42 < num6; num42++)
                {
                    Main.tile[num41, num42].liquid = 0;
                    Main.tile[num41, num42].wall = 0;
                }
            }
        }
        num3 = (int)(val.X - dxStrength * 0.5);
        num4 = (int)(val.X + dxStrength * 0.5);
        num5 = (int)(val.Y - dyStrength * 0.5);
        num6 = (int)(val.Y + dyStrength * 0.5);
        if (num3 < 0)
        {
            num3 = 0;
        }
        if (num4 > Main.maxTilesX)
        {
            num4 = Main.maxTilesX;
        }
        if (num5 < 0)
        {
            num5 = 0;
        }
        if (num6 > Main.maxTilesY)
        {
            num6 = Main.maxTilesY;
        }
        for (int num43 = num3; num43 < num4; num43++)
        {
            for (int num44 = num5; num44 < num6; num44++)
            {
                Main.tile[num43, num44].liquid = 0;
                Main.tile[num43, num44].active(active: false);
                Main.tile[num43, num44].wall = 0;
            }
        }
        Main.dungeonX = (int)val.X;
        Main.dungeonY = num6;
        int num45 = NPC.NewNPC(new EntitySource_WorldGen(), Main.dungeonX * 16 + 8, Main.dungeonY * 16, 37);
        Main.npc[num45].homeless = false;
        Main.npc[num45].homeTileX = Main.dungeonX;
        Main.npc[num45].homeTileY = Main.dungeonY;
        if (drunkWorldGen)
        {
            int num46 = (int)Main.worldSurface;
            while (Main.tile[GenVars.dungeonX, num46].active() || Main.tile[GenVars.dungeonX, num46].wall > 0 || Main.tile[GenVars.dungeonX, num46 - 1].active() || Main.tile[GenVars.dungeonX, num46 - 1].wall > 0 || Main.tile[GenVars.dungeonX, num46 - 2].active() || Main.tile[GenVars.dungeonX, num46 - 2].wall > 0 || Main.tile[GenVars.dungeonX, num46 - 3].active() || Main.tile[GenVars.dungeonX, num46 - 3].wall > 0 || Main.tile[GenVars.dungeonX, num46 - 4].active() || Main.tile[GenVars.dungeonX, num46 - 4].wall > 0)
            {
                num46--;
                if (num46 < 50)
                {
                    break;
                }
            }
            if (num46 > 50)
            {
                GrowDungeonTree(GenVars.dungeonX, num46);
            }
        }
        if (!drunkWorldGen)
        {
            int num47 = 100;
            if (num2 == 1)
            {
                int num48 = 0;
                for (int num49 = num4; num49 < num4 + num47; num49++)
                {
                    num48++;
                    for (int num50 = num6 + num48; num50 < num6 + num47; num50++)
                    {
                        Main.tile[num49, num50].liquid = 0;
                        Main.tile[num49, num50 - 1].liquid = 0;
                        Main.tile[num49, num50 - 2].liquid = 0;
                        Main.tile[num49, num50 - 3].liquid = 0;
                        if (!Main.wallDungeon[Main.tile[num49, num50].wall] && Main.tile[num49, num50].wall != 3 && Main.tile[num49, num50].wall != 83)
{
                            Main.tile[num49, num50].active(active: true);
                            Main.tile[num49, num50].type = tileType;
                            Main.tile[num49, num50].Clear(TileDataType.Slope);
                        }
                    }
                }
            }
            else
            {
                int num51 = 0;
                for (int num52 = num3; num52 > num3 - num47; num52--)
                {
                    num51++;
                    for (int num53 = num6 + num51; num53 < num6 + num47; num53++)
                    {
                        Main.tile[num52, num53].liquid = 0;
                        Main.tile[num52, num53 - 1].liquid = 0;
                        Main.tile[num52, num53 - 2].liquid = 0;
                        Main.tile[num52, num53 - 3].liquid = 0;
                        if (!Main.wallDungeon[Main.tile[num52, num53].wall] && Main.tile[num52, num53].wall != 3 && Main.tile[num52, num53].wall != 83)
{
                            Main.tile[num52, num53].active(active: true);
                            Main.tile[num52, num53].type = tileType;
                            Main.tile[num52, num53].Clear(TileDataType.Slope);
                        }
                    }
                }
            }
        }
        num15 = 1 + genRand.Next(2);
        num16 = 2 + genRand.Next(4);
        num17 = 0;
        num3 = (int)(val.X - dxStrength * 0.5);
        num4 = (int)(val.X + dxStrength * 0.5);
        if (drunkWorldGen)
        {
            if (num2 == 1)
            {
                num4--;
                num3--;
            }
            else
            {
                num3++;
                num4++;
            }
        }
        else
        {
            num3 += 2;
            num4 -= 2;
        }
        for (int num54 = num3; num54 < num4; num54++)
        {
            for (int num55 = num5; num55 < num6 + 1; num55++)
            {
                PlaceWall(num54, num55, wallType, mute: true);
            }
            if (!drunkWorldGen)
            {
                num17++;
                if (num17 >= num16)
                {
                    num54 += num16 * 2;
                    num17 = 0;
                }
            }
        }
        if (drunkWorldGen)
        {
            num3 = (int)(val.X - dxStrength * 0.5);
            num4 = (int)(val.X + dxStrength * 0.5);
            if (num2 == 1)
            {
                num3 = num4 - 3;
            }
            else
            {
                num4 = num3 + 3;
            }
            for (int num56 = num3; num56 < num4; num56++)
            {
                for (int num57 = num5; num57 < num6 + 1; num57++)
                {
                    Main.tile[num56, num57].active(active: true);
                    Main.tile[num56, num57].type = tileType;
                    Main.tile[num56, num57].Clear(TileDataType.Slope);
                }
            }
        }
        val.X -= dxStrength * 0.6 * (double)num2;
        val.Y += dyStrength * 0.5;
        dxStrength = 15.0;
        dyStrength = 3.0;
        val.Y -= dyStrength * 0.5;
        num3 = (int)(val.X - dxStrength * 0.5);
        num4 = (int)(val.X + dxStrength * 0.5);
        num5 = (int)(val.Y - dyStrength * 0.5);
        num6 = (int)(val.Y + dyStrength * 0.5);
        if (num3 < 0)
        {
            num3 = 0;
        }
        if (num4 > Main.maxTilesX)
        {
            num4 = Main.maxTilesX;
        }
        if (num5 < 0)
        {
            num5 = 0;
        }
        if (num6 > Main.maxTilesY)
        {
            num6 = Main.maxTilesY;
        }
        for (int num58 = num3; num58 < num4; num58++)
        {
            for (int num59 = num5; num59 < num6; num59++)
            {
                Main.tile[num58, num59].active(active: false);
            }
        }
        if (num2 < 0)
        {
            val.X -= 1.0;
        }
        PlaceTile((int)val.X, (int)val.Y + 1, 10, mute: true, forced: false, -1, 13);
    }
References Terraria.Tile.active(), Terraria.Tile.Clear(), Terraria.WorldBuilding.GenVars.dungeonPlatformX, Terraria.WorldBuilding.GenVars.dungeonPlatformY, Terraria.WorldBuilding.GenVars.dungeonX, Terraria.Main.dungeonX, Terraria.Main.dungeonY, Terraria.WorldBuilding.GenVars.dxStrength1, Terraria.WorldBuilding.GenVars.dxStrength2, Terraria.WorldBuilding.GenVars.dyStrength1, Terraria.WorldBuilding.GenVars.dyStrength2, Terraria.NPC.homeless, Terraria.NPC.homeTileX, Terraria.NPC.homeTileY, Terraria.Tile.lava(), Terraria.Tile.liquid, Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.NPC.NewNPC(), Terraria.Main.npc, Terraria.WorldBuilding.GenVars.numDungeonPlatforms, Terraria.Main.tile, Terraria.Tile.type, Terraria.Tile.wall, Terraria.Main.wallDungeon, Terraria.Main.worldSurface, ReLogic.Utilities.Vector2D.X, and ReLogic.Utilities.Vector2D.Y.