Terraria: Terraria.WorldGen.ScanTileColumnAndRemoveClumps
ScanTileColumnAndRemoveClumps()
static void Terraria.WorldGen.ScanTileColumnAndRemoveClumps (int x) inline static private
    {
        int num = 0;
        int y = 0;
        for (int i = 10; i < Main.maxTilesY - 10; i++)
        {
            if (Main.tile[x, i].active() && Main.tileSolid[Main.tile[x, i].type] && TileID.Sets.CanBeClearedDuringGeneration[Main.tile[x, i].type])
            {
                if (num == 0)
                {
                    y = i;
                }
                num++;
                continue;
            }
            if (num > 0 && num < tileCounterMax)
            {
                SmallConsecutivesFound++;
                if (tileCounter(x, y) < tileCounterMax)
                {
                    SmallConsecutivesEliminated++;
                    tileCounterKill();
                }
            }
            num = 0;
        }
    }
References Terraria.Tile.active(), Terraria.ID.TileID.Sets.CanBeClearedDuringGeneration, Terraria.WorldGen.SmallConsecutivesEliminated, Terraria.WorldGen.SmallConsecutivesFound, Terraria.Main.tile, Terraria.WorldGen.tileCounter(), Terraria.WorldGen.tileCounterKill(), Terraria.WorldGen.tileCounterMax, Terraria.Main.tileSolid, and Terraria.Tile.type.
Referenced by Terraria.WorldGen.GenerateWorld().