Terraria: Terraria.WorldGen.StartRoomCheck
StartRoomCheck()
static bool Terraria.WorldGen.StartRoomCheck (int x, int y) inline static
Definition at line 2581 of file WorldGen.cs.
    {
        roomHasStinkbug = false;
        roomHasEchoStinkbug = false;
        roomX1 = x;
        roomX2 = x;
        roomY1 = y;
        roomY2 = y;
        numRoomTiles = 0;
        roomCeilingsCount = 0;
        for (int i = 0; i < TileID.Count; i++)
        {
            houseTile[i] = false;
        }
        canSpawn = true;
        if (Main.tile[x, y].nactive() && Main.tileSolid[Main.tile[x, y].type])
        {
            roomCheckFailureReason = TownNPCRoomCheckFailureReason.RoomCheckStartedInASolidTile;
            canSpawn = false;
            return false;
        }
        roomCheckFailureReason = TownNPCRoomCheckFailureReason.None;
        CheckRoom(x, y);
        if (!canSpawn)
        {
            return false;
        }
        if (numRoomTiles < 60)
        {
            roomCheckFailureReason = TownNPCRoomCheckFailureReason.RoomIsTooSmall;
            canSpawn = false;
            return false;
        }
        if (canSpawn)
        {
            return true;
        }
        return false;
    }
References Terraria.WorldGen.canSpawn, Terraria.WorldGen.CheckRoom(), Terraria.ID.TileID.Count, Terraria.WorldGen.houseTile, Terraria.WorldGen.numRoomTiles, Terraria.WorldGen.roomCeilingsCount, Terraria.WorldGen.roomCheckFailureReason, Terraria.WorldGen.roomHasEchoStinkbug, Terraria.WorldGen.roomHasStinkbug, Terraria.WorldGen.roomX1, Terraria.WorldGen.roomX2, Terraria.WorldGen.roomY1, Terraria.WorldGen.roomY2, Terraria.Main.tile, and Terraria.Main.tileSolid.
Referenced by Terraria.Player.CheckSpawn_Internal(), Terraria.WorldGen.MoveTownNPC(), Terraria.WorldGen.QuickFindHome(), and Terraria.WorldGen.SpawnTownNPC().