Terraria: System.Data.XmlToDatasetMap.BuildIdentityMap
BuildIdentityMap() [3/4]
void System.Data.XmlToDatasetMap.BuildIdentityMap (XmlNameTable nameTable, DataSet dataSet) inline private
Definition at line 231 of file XmlToDatasetMap.cs.
    {
        _tableSchemaMap = new XmlNodeIdHashtable(dataSet.Tables.Count);
        string text = nameTable.Get(dataSet.Namespace);
        if (text == null)
        {
            text = nameTable.Add(dataSet.Namespace);
        }
        dataSet._namespaceURI = text;
        foreach (DataTable table in dataSet.Tables)
        {
            TableSchemaInfo tableSchemaInfo = AddTableSchema(nameTable, table);
            if (tableSchemaInfo == null)
            {
                continue;
            }
            foreach (DataColumn column in table.Columns)
            {
                if (IsMappedColumn(column))
                {
                    AddColumnSchema(nameTable, column, tableSchemaInfo.ColumnsSchemaMap);
                }
            }
            foreach (DataRelation childRelation in table.ChildRelations)
            {
                if (childRelation.Nested)
                {
                    string array = XmlConvert.EncodeLocalName(childRelation.ChildTable.TableName);
                    string text2 = nameTable.Get(array);
                    if (text2 == null)
                    {
                        text2 = nameTable.Add(array);
                    }
                    string text3 = nameTable.Get(childRelation.ChildTable.Namespace);
                    if (text3 == null)
                    {
                        text3 = nameTable.Add(childRelation.ChildTable.Namespace);
                    }
                    XmlNodeIdentety key = new XmlNodeIdentety(text2, text3);
                    tableSchemaInfo.ColumnsSchemaMap[key] = childRelation.ChildTable;
                }
            }
        }
    }
References System.Data.XmlToDatasetMap._tableSchemaMap, System.Data.XmlToDatasetMap.AddColumnSchema(), System.Data.XmlToDatasetMap.AddTableSchema(), System.array, System.Data.DataTable.ChildRelations, System.Data.DataTable.Columns, System.Xml.Dictionary, System.Xml.XmlConvert.EncodeLocalName(), System.Data.XmlToDatasetMap.IsMappedColumn(), System.key, and System.text.