Terraria: Terraria.WorldGen.outerTempled
outerTempled()
static void Terraria.WorldGen.outerTempled (int x, int y) inline static
Definition at line 25035 of file WorldGen.cs.
    {
        if ((Main.tile[x, y].active() & (Main.tile[x, y].type == 226)) || Main.tile[x, y].wall == 87)
        {
            return;
        }
        int num = 6;
        for (int i = x - num; i <= x + num; i++)
        {
            for (int j = y - num; j <= y + num; j++)
            {
                if (!Main.tile[i, j].active() && Main.tile[i, j].wall == 87)
                {
                    i = x;
                    j = y;
                    Main.tile[i, j].active(active: true);
                    Main.tile[i, j].type = 226;
                    Main.tile[i, j].liquid = 0;
                    Main.tile[i, j].slope(0);
                    Main.tile[i, j].halfBrick(halfBrick: false);
                    return;
                }
            }
        }
    }
References Terraria.Tile.active(), Terraria.Tile.halfBrick(), Terraria.Tile.liquid, Terraria.Tile.slope(), Terraria.Main.tile, Terraria.Tile.type, and Terraria.Tile.wall.