Terraria: Terraria.WorldGen.UpdateWorld_UndergroundTile
UpdateWorld_UndergroundTile()
static void Terraria.WorldGen.UpdateWorld_UndergroundTile (int i, int j, bool checkNPCSpawns, int wallDist) inline static private
Definition at line 63262 of file WorldGen.cs.
    {
        int num = i - 1;
        int num2 = i + 2;
        int num3 = j - 1;
        int num4 = j + 2;
        if (num < 10)
        {
            num = 10;
        }
        if (num2 > Main.maxTilesX - 10)
        {
            num2 = Main.maxTilesX - 10;
        }
        if (num3 < 10)
        {
            num3 = 10;
        }
        if (num4 > Main.maxTilesY - 10)
        {
            num4 = Main.maxTilesY - 10;
        }
        if (Main.tile[i, j] == null)
        {
            return;
        }
        if (Main.tile[i, j].type == 655 && !NPC.AnyNPCs(262))
        {
            KillTile(i, j);
            if (Main.netMode == 2)
            {
                NetMessage.SendData(17, -1, -1, null, 0, i, j);
            }
        }
        if (Main.tileAlch[Main.tile[i, j].type])
        {
            GrowAlch(i, j);
        }
        else if (Main.tile[i, j].nactive())
        {
            hardUpdateWorld(i, j);
            if (Main.rand.Next(2500) == 0)
            {
                plantDye(i, j);
            }
            else if (Main.hardMode && Main.rand.Next(10000) == 0)
            {
                plantDye(i, j, exoticPlant: true);
            }
            if (Main.tile[i, j].type == 519)
            {
                CheckCatTail(i, j);
                if (Main.tile[i, j].active() && genRand.Next(2) == 0)
                {
                    GrowCatTail(i, j);
                    CheckCatTail(i, j);
                }
            }
            if (Main.tile[i, j].type == 549)
            {
                GrowCheckSeaweed(i, j);
            }
            else if (Main.tile[i, j].type == 53 && !Main.tile[i, j].topSlope() && !Main.tile[i, j].halfBrick() && !Main.tile[i, j - 1].active() && genRand.Next(20) == 0)
            {
                GrowCheckSeaweed(i, j);
            }
            else if (TileID.Sets.SpreadUnderground[Main.tile[i, j].type])
            {
                UpdateWorld_GrassGrowth(i, j, num, num2, num3, num4, underground: true);
                int type = Main.tile[i, j].type;
                if ((type == 32 || type == 352) && genRand.Next(3) == 0)
                {
                    if (type == 32)
                    {
                        GrowSpike(i, j, 32, 23);
                    }
                    else
                    {
                        GrowSpike(i, j, 352, 199);
                    }
                }
            }
            else if (Main.tile[i, j].type == 61 && genRand.Next(3) == 0)
            {
                if (Main.tile[i, j].frameX < 144)
                {
                    if (Main.rand.Next(4) == 0)
                    {
                        Main.tile[i, j].frameX = (short)(162 + genRand.Next(8) * 18);
                    }
                    Main.tile[i, j].type = 74;
                    if (Main.netMode == 2)
                    {
                        NetMessage.SendTileSquare(-1, i, j);
                    }
                }
            }
            else if ((Main.tile[i, j].type == 60 || Main.tile[i, j].type == 62) && genRand.Next(5) == 0 && GrowMoreVines(i, j))
            {
                if (!Main.tile[i, j + 1].active() && !Main.tile[i, j + 1].lava())
                {
                    bool flag = false;
                    for (int num5 = j; num5 > j - 10; num5--)
                    {
                        if (Main.tile[i, num5].bottomSlope())
{
                            flag = false;
                            break;
                        }
                        if (Main.tile[i, num5].active() && Main.tile[i, num5].type == 60 && !Main.tile[i, num5].bottomSlope())
{
                            flag = true;
                            break;
                        }
                    }
                    if (flag)
                    {
                        int num6 = j + 1;
                        Main.tile[i, num6].type = 62;
                        Main.tile[i, num6].active(active: true);
                        SquareTileFrame(i, num6);
                        Main.tile[i, num6].CopyPaintAndCoating(Main.tile[i, num6 - 1]);
                        if (Main.netMode == 2)
{
                            NetMessage.SendTileSquare(-1, i, num6);
                        }
                    }
                }
            }
            else if ((Main.tile[i, j].type == 633 || Main.tile[i, j].type == 638) && GrowMoreVines(i, j))
            {
                if (!Main.tile[i, j + 1].active() && !Main.tile[i, j + 1].lava())
                {
                    int maxValue = 70;
                    if (Main.tile[i, j].type == 638)
                    {
                        maxValue = 7;
                    }
                    if (genRand.Next(maxValue) == 0)
                    {
                        bool flag2 = false;
                        for (int num7 = j; num7 > j - 10; num7--)
{
                            if (Main.tile[i, num7].bottomSlope())
{
                                flag2 = false;
                                break;
                            }
                            if (Main.tile[i, num7].active() && Main.tile[i, num7].type == 633 && !Main.tile[i, num7].bottomSlope())
{
                                flag2 = true;
                                break;
                            }
                        }
                        if (flag2)
{
                            int num8 = j + 1;
                            Main.tile[i, num8].type = 638;
                            Main.tile[i, num8].active(active: true);
                            Main.tile[i, num8].CopyPaintAndCoating(Main.tile[i, num8 - 1]);
                            SquareTileFrame(i, num8);
                            if (Main.netMode == 2)
{
                                NetMessage.SendTileSquare(-1, i, num8);
                            }
                        }
                    }
                }
            }
            else if ((Main.tile[i, j].type == 70 || Main.tile[i, j].type == 528) && GrowMoreVines(i, j))
            {
                if (!Main.tile[i, j + 1].active() && !Main.tile[i, j + 1].lava())
                {
                    int maxValue2 = 70;
                    if (Main.tile[i, j].type == 528)
                    {
                        maxValue2 = 7;
                    }
                    if (genRand.Next(maxValue2) == 0)
                    {
                        bool flag3 = false;
                        for (int num9 = j; num9 > j - 10; num9--)
{
                            if (Main.tile[i, num9].bottomSlope())
{
                                flag3 = false;
                                break;
                            }
                            if (Main.tile[i, num9].active() && Main.tile[i, num9].type == 70 && !Main.tile[i, num9].bottomSlope())
{
                                flag3 = true;
                                break;
                            }
                        }
                        if (flag3)
{
                            int num10 = j + 1;
                            Main.tile[i, num10].type = 528;
                            Main.tile[i, num10].active(active: true);
                            Main.tile[i, num10].CopyPaintAndCoating(Main.tile[i, num10 - 1]);
                            SquareTileFrame(i, num10);
                            if (Main.netMode == 2)
{
                                NetMessage.SendTileSquare(-1, i, num10);
                            }
                        }
                    }
                }
            }
            else if ((Main.tile[i, j].type == 661 || Main.tile[i, j].type == 636) && GrowMoreVines(i, j))
            {
                if (!Main.tile[i, j + 1].active() && !Main.tile[i, j + 1].lava())
                {
                    int maxValue3 = 70;
                    if (Main.tile[i, j].type == 636)
                    {
                        maxValue3 = 7;
                    }
                    if (genRand.Next(maxValue3) == 0)
                    {
                        bool flag4 = false;
                        for (int num11 = j; num11 > j - 10; num11--)
{
                            if (Main.tile[i, num11].bottomSlope())
{
                                flag4 = false;
                                break;
                            }
                            if (Main.tile[i, num11].active() && Main.tile[i, num11].type == 661 && !Main.tile[i, num11].bottomSlope())
{
                                flag4 = true;
                                break;
                            }
                        }
                        if (flag4)
{
                            int num12 = j + 1;
                            Main.tile[i, num12].type = 636;
                            Main.tile[i, num12].active(active: true);
                            Main.tile[i, num12].CopyPaintAndCoating(Main.tile[i, num12 - 1]);
                            SquareTileFrame(i, num12);
                            if (Main.netMode == 2)
{
                                NetMessage.SendTileSquare(-1, i, num12);
                            }
                        }
                    }
                }
            }
            else if ((Main.tile[i, j].type == 662 || Main.tile[i, j].type == 205) && GrowMoreVines(i, j))
            {
                if (!Main.tile[i, j + 1].active() && !Main.tile[i, j + 1].lava())
                {
                    int maxValue4 = 70;
                    if (Main.tile[i, j].type == 205)
                    {
                        maxValue4 = 7;
                    }
                    if (genRand.Next(maxValue4) == 0)
                    {
                        bool flag5 = false;
                        for (int num13 = j; num13 > j - 10; num13--)
{
                            if (Main.tile[i, num13].bottomSlope())
{
                                flag5 = false;
                                break;
                            }
                            if (Main.tile[i, num13].active() && Main.tile[i, num13].type == 662 && !Main.tile[i, num13].bottomSlope())
{
                                flag5 = true;
                                break;
                            }
                        }
                        if (flag5)
{
                            int num14 = j + 1;
                            Main.tile[i, num14].type = 205;
                            Main.tile[i, num14].active(active: true);
                            Main.tile[i, num14].CopyPaintAndCoating(Main.tile[i, num14 - 1]);
                            SquareTileFrame(i, num14);
                            if (Main.netMode == 2)
{
                                NetMessage.SendTileSquare(-1, i, num14);
                            }
                        }
                    }
                }
            }
            else if ((Main.tile[i, j].type == 60 || Main.tile[i, j].type == 62) && genRand.Next(80) == 0 && !PlayerLOS(i, j))
            {
                bool flag6 = true;
                int num15 = j;
                if (Main.tile[i, j].type == 60)
                {
                    num15++;
                }
                for (int k = i; k < i + 2; k++)
                {
                    int num16 = num15 - 1;
                    if (!AnchorValid(Framing.GetTileSafely(k, num16), AnchorType.SolidTile) || Main.tile[k, num16].bottomSlope())
                    {
                        flag6 = false;
                    }
                    if (Main.tile[k, num16].liquid > 0 || Main.wallHouse[Main.tile[k, num16].wall])
                    {
                        flag6 = false;
                    }
                    if (!flag6)
                    {
                        break;
                    }
                    for (int l = num15; l < num15 + 2; l++)
                    {
                        if ((Main.tile[k, l].active() && (!Main.tileCut[Main.tile[k, l].type] || Main.tile[k, l].type == 444)) || Main.tile[k, l].lava())
{
                            flag6 = false;
                        }
                        if (!flag6)
{
                            break;
                        }
                    }
                    if (!flag6)
                    {
                        break;
                    }
                }
                if (flag6 && CountNearBlocksTypes(i, j, 20, 1, 444) > 0)
                {
                    flag6 = false;
                }
                if (flag6)
                {
                    for (int m = i; m < i + 2; m++)
                    {
                        Main.tile[m, num15 - 1].slope(0);
                        Main.tile[m, num15 - 1].halfBrick(halfBrick: false);
                        for (int n = num15; n < num15 + 2; n++)
{
                            if (Main.tile[m, n].active())
{
                                KillTile(m, n);
                            }
                        }
                    }
                    for (int num17 = i; num17 < i + 2; num17++)
                    {
                        for (int num18 = num15; num18 < num15 + 2; num18++)
{
                            Main.tile[num17, num18].active(active: true);
                            Main.tile[num17, num18].type = 444;
                            Main.tile[num17, num18].frameX = (short)((num17 - i) * 18);
                            Main.tile[num17, num18].frameY = (short)((num18 - num15) * 18);
                        }
                    }
                    if (Main.netMode == 2)
                    {
                        NetMessage.SendTileSquare(-1, i, num15 - 1, 2, 3);
                    }
                }
            }
            else if (Main.tile[i, j].type == 396 && genRand.Next(80) == 0 && !PlayerLOS(i, j))
            {
                bool flag7 = true;
                int num19 = j - 1;
                for (int num20 = i; num20 < i + 2; num20++)
                {
                    int num21 = num19 + 1;
                    if (!AnchorValid(Framing.GetTileSafely(num20, num21), AnchorType.SolidTile) || Main.tile[num20, num21].topSlope())
                    {
                        flag7 = false;
                    }
                    if (Main.tile[num20, num21].liquid > 0 || Main.wallHouse[Main.tile[num20, num21].wall])
                    {
                        flag7 = false;
                    }
                    if (!flag7)
                    {
                        break;
                    }
                    for (int num22 = num19 - 2; num22 < num19; num22++)
                    {
                        if ((Main.tile[num20, num22].active() && (!Main.tileCut[Main.tile[num20, num22].type] || Main.tile[num20, num22].type == 485)) || Main.tile[num20, num22].lava())
{
                            flag7 = false;
                        }
                        if (!flag7)
{
                            break;
                        }
                    }
                    if (!flag7)
                    {
                        break;
                    }
                }
                if (flag7 && CountNearBlocksTypes(i, j, 20, 1, 485) > 0)
                {
                    flag7 = false;
                }
                if (flag7)
                {
                    bool flag8 = true;
                    for (int num23 = -1; num23 >= -3; num23--)
                    {
                        if (Main.tile[i, j + num23].active())
{
                            flag8 = false;
                            break;
                        }
                    }
                    if (flag8)
                    {
                        PlaceTile(i, j - 1, 485, mute: true, forced: false, -1, genRand.Next(4));
                        if (Main.netMode == 2)
{
                            NetMessage.SendTileSquare(-1, i, j - 2, 2, 2);
                        }
                    }
                }
            }
            else if (Main.tile[i, j].type == 69)
            {
                GrowSpike(i, j, 69, 60);
            }
            else if (Main.tile[i, j].type == 147 || Main.tile[i, j].type == 161 || Main.tile[i, j].type == 163 || Main.tile[i, j].type == 164 || Main.tile[i, j].type == 200)
            {
                if (Main.rand.Next(10) == 0 && !Main.tile[i, j + 1].active() && !Main.tile[i, j + 2].active())
                {
                    int num24 = i - 3;
                    int num25 = i + 4;
                    int num26 = 0;
                    for (int num27 = num24; num27 < num25; num27++)
                    {
                        if (Main.tile[num27, j].type == 165 && Main.tile[num27, j].active())
{
                            num26++;
                        }
                        if (Main.tile[num27, j + 1].type == 165 && Main.tile[num27, j + 1].active())
{
                            num26++;
                        }
                        if (Main.tile[num27, j + 2].type == 165 && Main.tile[num27, j + 2].active())
{
                            num26++;
                        }
                        if (Main.tile[num27, j + 3].type == 165 && Main.tile[num27, j + 3].active())
{
                            num26++;
                        }
                    }
                    if (num26 < 2)
                    {
                        PlaceTight(i, j + 1);
                        SquareTileFrame(i, j + 1);
                        if (Main.netMode == 2 && Main.tile[i, j + 1].active())
{
                            NetMessage.SendTileSquare(-1, i, j + 1, 1, 2);
                        }
                    }
                }
            }
            else if (Main.tileMoss[Main.tile[i, j].type] || TileID.Sets.tileMossBrick[Main.tile[i, j].type])
            {
                int type2 = Main.tile[i, j].type;
                bool flag9 = false;
                TileColorCache color = Main.tile[i, j].BlockColorAndCoating();
                for (int num28 = num; num28 < num2; num28++)
                {
                    for (int num29 = num3; num29 < num4; num29++)
                    {
                        if ((i != num28 || j != num29) && Main.tile[num28, num29].active() && (Main.tile[num28, num29].type == 1 || Main.tile[num28, num29].type == 38))
{
                            int type3 = Main.tile[num28, num29].type;
                            int num30 = MossConversion(type2, type3);
                            SpreadGrass(num28, num29, Main.tile[num28, num29].type, num30, repeat: false, color);
                            if (Main.tile[num28, num29].type == num30)
{
                                SquareTileFrame(num28, num29);
                                flag9 = true;
                            }
                        }
                    }
                }
                if (Main.netMode == 2 && flag9)
                {
                    NetMessage.SendTileSquare(-1, i, j, 3);
                }
                if (genRand.Next(6) == 0)
                {
                    int num31 = i;
                    int num32 = j;
                    switch (genRand.Next(4))
                    {
                    case 0:
                        num31--;
                        break;
                    case 1:
                        num31++;
                        break;
                    case 2:
                        num32--;
                        break;
                    default:
                        num32++;
                        break;
                    }
                    if (!Main.tile[num31, num32].active())
                    {
                        if (PlaceTile(num31, num32, 184, mute: true))
{
                            Main.tile[num31, num32].CopyPaintAndCoating(Main.tile[i, j]);
                        }
                        if (Main.netMode == 2 && Main.tile[num31, num32].active())
{
                            NetMessage.SendTileSquare(-1, num31, num32);
                        }
                    }
                }
            }
            else if (Main.tile[i, j].type == 20)
            {
                if (genRand.Next(5) == 0)
                {
                    AttemptToGrowTreeFromSapling(i, j, underground: true);
                }
            }
            else if (Main.tile[i, j].type == 590)
            {
                if (genRand.Next(5) == 0)
                {
                    AttemptToGrowTreeFromSapling(i, j, underground: true);
                }
            }
            else if (Main.tile[i, j].type == 595)
            {
                if (genRand.Next(5) == 0)
                {
                    AttemptToGrowTreeFromSapling(i, j, underground: true);
                }
            }
            else if (Main.tile[i, j].type == 615 && genRand.Next(5) == 0)
            {
                AttemptToGrowTreeFromSapling(i, j, underground: true);
            }
        }
        else
        {
            if (Main.tile[i, j].wall == 62 && Main.tile[i, j].liquid == 0)
            {
                GrowWeb(i, j);
            }
            if (checkNPCSpawns)
            {
                TrySpawningTownNPC(i, j);
            }
        }
        if (AllowedToSpreadInfections)
        {
            if (Main.tile[i, j].wall == 81 || Main.tile[i, j].wall == 83 || (Main.tile[i, j].type == 199 && Main.tile[i, j].active()))
            {
                int num33 = i + genRand.Next(-2, 3);
                int num34 = j + genRand.Next(-2, 3);
                if (InWorld(num33, num34, 10) && Main.tile[num33, num34].wall >= 63 && Main.tile[num33, num34].wall <= 68)
                {
                    bool flag10 = false;
                    for (int num35 = i - wallDist; num35 < i + wallDist; num35++)
                    {
                        for (int num36 = j - wallDist; num36 < j + wallDist; num36++)
{
                            if (Main.tile[num35, num36].active())
{
                                int type4 = Main.tile[num35, num36].type;
                                if (type4 == 199 || type4 == 200 || type4 == 201 || type4 == 203 || type4 == 205 || type4 == 234 || type4 == 352 || type4 == 662)
{
                                    flag10 = true;
                                    break;
                                }
                            }
                        }
                    }
                    if (flag10)
                    {
                        Main.tile[num33, num34].wall = 81;
                        if (Main.netMode == 2)
{
                            NetMessage.SendTileSquare(-1, num33, num34);
                        }
                    }
                }
            }
            else if (Main.tile[i, j].wall == 69 || Main.tile[i, j].wall == 3 || (Main.tile[i, j].type == 23 && Main.tile[i, j].active()))
            {
                int num37 = i + genRand.Next(-2, 3);
                int num38 = j + genRand.Next(-2, 3);
                if (InWorld(num37, num38, 10) && Main.tile[num37, num38].wall >= 63 && Main.tile[num37, num38].wall <= 68)
                {
                    bool flag11 = false;
                    for (int num39 = i - wallDist; num39 < i + wallDist; num39++)
                    {
                        for (int num40 = j - wallDist; num40 < j + wallDist; num40++)
{
                            if (Main.tile[num39, num40].active())
{
                                int type5 = Main.tile[num39, num40].type;
                                if (type5 == 22 || type5 == 23 || type5 == 24 || type5 == 25 || type5 == 32 || type5 == 112 || type5 == 163 || type5 == 636 || type5 == 661)
{
                                    flag11 = true;
                                    break;
                                }
                            }
                        }
                    }
                    if (flag11)
                    {
                        Main.tile[num37, num38].wall = 69;
                        if (Main.netMode == 2)
{
                            NetMessage.SendTileSquare(-1, num37, num38);
                        }
                    }
                }
            }
            else if (Main.tile[i, j].wall == 70 || (Main.tile[i, j].type == 109 && Main.tile[i, j].active()))
            {
                int num41 = i + genRand.Next(-2, 3);
                int num42 = j + genRand.Next(-2, 3);
                if ((InWorld(num41, num42, 10) && Main.tile[num41, num42].wall == 63) || Main.tile[num41, num42].wall == 65 || Main.tile[num41, num42].wall == 66 || Main.tile[num41, num42].wall == 68)
                {
                    bool flag12 = false;
                    for (int num43 = i - wallDist; num43 < i + wallDist; num43++)
                    {
                        for (int num44 = j - wallDist; num44 < j + wallDist; num44++)
{
                            if (Main.tile[num43, num44].active())
{
                                int type6 = Main.tile[num43, num44].type;
                                if (type6 == 109 || type6 == 110 || type6 == 113 || type6 == 115 || type6 == 116 || type6 == 117 || type6 == 164)
{
                                    flag12 = true;
                                    break;
                                }
                            }
                        }
                    }
                    if (flag12)
                    {
                        Main.tile[num41, num42].wall = 70;
                        if (Main.netMode == 2)
{
                            NetMessage.SendTileSquare(-1, num41, num42);
                        }
                    }
                }
            }
            SpreadDesertWalls(wallDist, i, j);
        }
        if (!Main.tile[i, j].nactive())
        {
            return;
        }
        if (Main.tile[i, j].type == 61 && genRand.Next(3) == 0 && Main.tile[i, j].frameX < 144)
        {
            if (Main.rand.Next(4) == 0)
            {
                Main.tile[i, j].frameX = (short)(162 + genRand.Next(8) * 18);
            }
            Main.tile[i, j].type = 74;
            if (Main.netMode == 2)
            {
                NetMessage.SendTileSquare(-1, i, j);
            }
        }
        if ((Main.tile[i, j].type == 60 || Main.tile[i, j].type == 62) && GrowMoreVines(i, j))
        {
            int maxValue5 = 30;
            if (Main.tile[i, j].type == 62)
            {
                maxValue5 = 10;
            }
            if (genRand.Next(maxValue5) != 0 || Main.tile[i, j + 1].active() || Main.tile[i, j + 1].lava())
            {
                return;
            }
            bool flag13 = false;
            for (int num45 = j; num45 > j - 10; num45--)
            {
                if (Main.tile[i, num45].bottomSlope())
                {
                    flag13 = false;
                    break;
                }
                if (Main.tile[i, num45].active() && Main.tile[i, num45].type == 60 && !Main.tile[i, num45].bottomSlope())
                {
                    flag13 = true;
                    break;
                }
            }
            if (flag13)
            {
                int num46 = j + 1;
                Main.tile[i, num46].type = 62;
                Main.tile[i, num46].active(active: true);
                Main.tile[i, num46].CopyPaintAndCoating(Main.tile[i, num46 - 1]);
                SquareTileFrame(i, num46);
                if (Main.netMode == 2)
                {
                    NetMessage.SendTileSquare(-1, i, num46);
                }
            }
        }
        else if ((Main.tile[i, j].type == 633 || Main.tile[i, j].type == 638) && GrowMoreVines(i, j))
        {
            int maxValue6 = 70;
            if (Main.tile[i, j].type == 638)
            {
                maxValue6 = 7;
            }
            if (genRand.Next(maxValue6) != 0 || Main.tile[i, j + 1].active() || Main.tile[i, j + 1].lava())
            {
                return;
            }
            bool flag14 = false;
            for (int num47 = j; num47 > j - 10; num47--)
            {
                if (Main.tile[i, num47].bottomSlope())
                {
                    flag14 = false;
                    break;
                }
                if (Main.tile[i, num47].active() && Main.tile[i, num47].type == 633 && !Main.tile[i, num47].bottomSlope())
                {
                    flag14 = true;
                    break;
                }
            }
            if (flag14)
            {
                int num48 = j + 1;
                Main.tile[i, num48].type = 638;
                Main.tile[i, num48].active(active: true);
                Main.tile[i, num48].CopyPaintAndCoating(Main.tile[i, num48 - 1]);
                SquareTileFrame(i, num48);
                if (Main.netMode == 2)
                {
                    NetMessage.SendTileSquare(-1, i, num48);
                }
            }
        }
        else
        {
            if ((Main.tile[i, j].type != 70 && Main.tile[i, j].type != 528) || !GrowMoreVines(i, j))
            {
                return;
            }
            int maxValue7 = 70;
            if (Main.tile[i, j].type == 528)
            {
                maxValue7 = 7;
            }
            if (genRand.Next(maxValue7) != 0 || Main.tile[i, j + 1].active() || Main.tile[i, j + 1].lava())
            {
                return;
            }
            bool flag15 = false;
            for (int num49 = j; num49 > j - 10; num49--)
            {
                if (Main.tile[i, num49].bottomSlope())
                {
                    flag15 = false;
                    break;
                }
                if (Main.tile[i, num49].active() && Main.tile[i, num49].type == 70 && !Main.tile[i, num49].bottomSlope())
                {
                    flag15 = true;
                    break;
                }
            }
            if (flag15)
            {
                int num50 = j + 1;
                Main.tile[i, num50].type = 528;
                Main.tile[i, num50].active(active: true);
                Main.tile[i, num50].CopyPaintAndCoating(Main.tile[i, num50 - 1]);
                SquareTileFrame(i, num50);
                if (Main.netMode == 2)
                {
                    NetMessage.SendTileSquare(-1, i, num50);
                }
            }
        }
    }
References Terraria.Tile.active(), Terraria.NPC.AnyNPCs(), Terraria.Tile.BlockColorAndCoating(), Terraria.Tile.bottomSlope(), Terraria.Tile.CopyPaintAndCoating(), Terraria.Tile.frameX, Terraria.Tile.frameY, Terraria.Framing.GetTileSafely(), Terraria.Tile.halfBrick(), Terraria.Main.hardMode, Terraria.Tile.lava(), Terraria.Tile.liquid, Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.Tile.nactive(), Terraria.Main.netMode, Terraria.Utilities.UnifiedRandom.Next(), Terraria.Main.rand, Terraria.NetMessage.SendData(), Terraria.NetMessage.SendTileSquare(), Terraria.Tile.slope(), Terraria.ID.TileID.Sets.SpreadUnderground, Terraria.Main.tile, Terraria.Main.tileAlch, Terraria.Main.tileCut, Terraria.Main.tileMoss, Terraria.ID.TileID.Sets.tileMossBrick, Terraria.Tile.topSlope(), Terraria.Tile.type, Terraria.Tile.wall, and Terraria.Main.wallHouse.