Terraria: Terraria.WorldGen.TileRunner
TileRunner()
static void Terraria.WorldGen.TileRunner (int i, int j, double strength, int steps, int type, bool addTile = false, double speedX = 0::0, double speedY = 0::0, bool noYChange = false, bool overRide = true, int ignoreTileType = -1) inline static
Definition at line 66759 of file WorldGen.cs.
    {
        //IL_01f3: Unknown result type (might be due to invalid IL or missing references)
        //IL_0239: Unknown result type (might be due to invalid IL or missing references)
        //IL_024e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0264: Unknown result type (might be due to invalid IL or missing references)
        //IL_0279: Unknown result type (might be due to invalid IL or missing references)
        //IL_0958: Unknown result type (might be due to invalid IL or missing references)
        //IL_0959: Unknown result type (might be due to invalid IL or missing references)
        //IL_095a: Unknown result type (might be due to invalid IL or missing references)
        //IL_095f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0987: Unknown result type (might be due to invalid IL or missing references)
        //IL_0988: Unknown result type (might be due to invalid IL or missing references)
        //IL_0989: Unknown result type (might be due to invalid IL or missing references)
        //IL_098e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0eeb: Unknown result type (might be due to invalid IL or missing references)
        //IL_09f5: Unknown result type (might be due to invalid IL or missing references)
        //IL_09f6: Unknown result type (might be due to invalid IL or missing references)
        //IL_09f7: Unknown result type (might be due to invalid IL or missing references)
        //IL_09fc: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f0c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a63: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a64: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a65: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a6a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ad1: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ad2: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ad3: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ad8: Unknown result type (might be due to invalid IL or missing references)
        //IL_034a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0359: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f55: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b3f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b40: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b41: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b46: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f76: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bad: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bae: Unknown result type (might be due to invalid IL or missing references)
        //IL_0baf: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bb4: Unknown result type (might be due to invalid IL or missing references)
        //IL_0fac: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c1b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c1c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c1d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c22: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ffe: Unknown result type (might be due to invalid IL or missing references)
        //IL_0fcd: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c89: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c8a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c8b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c90: Unknown result type (might be due to invalid IL or missing references)
        //IL_0657: Unknown result type (might be due to invalid IL or missing references)
        //IL_0666: Unknown result type (might be due to invalid IL or missing references)
        //IL_101f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0cf7: Unknown result type (might be due to invalid IL or missing references)
        //IL_0cf8: Unknown result type (might be due to invalid IL or missing references)
        //IL_0cf9: Unknown result type (might be due to invalid IL or missing references)
        //IL_0cfe: Unknown result type (might be due to invalid IL or missing references)
        //IL_06ba: Unknown result type (might be due to invalid IL or missing references)
        //IL_06c9: Unknown result type (might be due to invalid IL or missing references)
        //IL_03ed: Unknown result type (might be due to invalid IL or missing references)
        //IL_03fc: Unknown result type (might be due to invalid IL or missing references)
        //IL_1040: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d65: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d66: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d67: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d6c: Unknown result type (might be due to invalid IL or missing references)
        //IL_1067: Unknown result type (might be due to invalid IL or missing references)
        //IL_0dd3: Unknown result type (might be due to invalid IL or missing references)
        //IL_0dd4: Unknown result type (might be due to invalid IL or missing references)
        //IL_0dd5: Unknown result type (might be due to invalid IL or missing references)
        //IL_0dda: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e3e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e3f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e40: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e45: Unknown result type (might be due to invalid IL or missing references)
        if (!GenVars.mudWall)
        {
            if (drunkWorldGen)
            {
                strength *= 1.0 + (double)genRand.Next(-80, 81) * 0.01;
                steps = (int)((double)steps * (1.0 + (double)genRand.Next(-80, 81) * 0.01));
            }
            else if (remixWorldGen)
            {
                strength *= 1.0 + (double)genRand.Next(-50, 51) * 0.01;
            }
            else if (getGoodWorldGen && type != 57)
            {
                strength *= 1.0 + (double)genRand.Next(-80, 81) * 0.015;
                steps += genRand.Next(3);
            }
        }
        double num = strength;
        double num2 = steps;
        Vector2D val = default(Vector2D);
        val.X = i;
        val.Y = j;
        Vector2D val2 = default(Vector2D);
        val2.X = (double)genRand.Next(-10, 11) * 0.1;
        val2.Y = (double)genRand.Next(-10, 11) * 0.1;
        if (speedX != 0.0 || speedY != 0.0)
        {
            val2.X = speedX;
            val2.Y = speedY;
        }
        bool flag = type == 368;
        bool flag2 = type == 367;
        bool lava = false;
        if (getGoodWorldGen && genRand.Next(4) == 0)
        {
            lava = true;
        }
        while (num > 0.0 && num2 > 0.0)
        {
            if (drunkWorldGen && genRand.Next(30) == 0)
            {
                val.X += (double)genRand.Next(-100, 101) * 0.05;
                val.Y += (double)genRand.Next(-100, 101) * 0.05;
            }
            if (val.Y < 0.0 && num2 > 0.0 && type == 59)
            {
                num2 = 0.0;
            }
            num = strength * (num2 / (double)steps);
            num2 -= 1.0;
            int num3 = (int)(val.X - num * 0.5);
            int num4 = (int)(val.X + num * 0.5);
            int num5 = (int)(val.Y - num * 0.5);
            int num6 = (int)(val.Y + num * 0.5);
            if (num3 < 1)
            {
                num3 = 1;
            }
            if (num4 > Main.maxTilesX - 1)
            {
                num4 = Main.maxTilesX - 1;
            }
            if (num5 < 1)
            {
                num5 = 1;
            }
            if (num6 > Main.maxTilesY - 1)
            {
                num6 = Main.maxTilesY - 1;
            }
            for (int k = num3; k < num4; k++)
            {
                if (k < beachDistance + 50 || k >= Main.maxTilesX - beachDistance - 50)
                {
                    lava = false;
                }
                for (int l = num5; l < num6; l++)
                {
                    if ((drunkWorldGen && l < Main.maxTilesY - 300 && type == 57) || (ignoreTileType >= 0 && Main.tile[k, l].active() && Main.tile[k, l].type == ignoreTileType) || !(Math.Abs((double)k - val.X) + Math.Abs((double)l - val.Y) < strength * 0.5 * (1.0 + (double)genRand.Next(-10, 11) * 0.015)))
                    {
                        continue;
                    }
                    if (GenVars.mudWall && (double)l > Main.worldSurface && Main.tile[k, l - 1].wall != 2 && l < Main.maxTilesY - 210 - genRand.Next(3) && Math.Abs((double)k - val.X) + Math.Abs((double)l - val.Y) < strength * 0.45 * (1.0 + (double)genRand.Next(-10, 11) * 0.01))
                    {
                        if (l > GenVars.lavaLine - genRand.Next(0, 4) - 50)
{
                            if (Main.tile[k, l - 1].wall != 64 && Main.tile[k, l + 1].wall != 64 && Main.tile[k - 1, l].wall != 64 && Main.tile[k + 1, l].wall != 64)
{
                                PlaceWall(k, l, 15, mute: true);
                            }
                        }
                        else if (Main.tile[k, l - 1].wall != 15 && Main.tile[k, l + 1].wall != 15 && Main.tile[k - 1, l].wall != 15 && Main.tile[k + 1, l].wall != 15)
{
                            PlaceWall(k, l, 64, mute: true);
                        }
                    }
                    if (type < 0)
                    {
                        if (Main.tile[k, l].type == 53)
{
                            continue;
                        }
                        if (type == -2 && Main.tile[k, l].active() && (l < GenVars.waterLine || l > GenVars.lavaLine))
{
                            Main.tile[k, l].liquid = byte.MaxValue;
                            Main.tile[k, l].lava(lava);
                            if (remixWorldGen)
{
                                if (l > GenVars.lavaLine && ((double)l < Main.rockLayer - 80.0 || l > Main.maxTilesY - 350) && !oceanDepths(k, l))
{
                                    Main.tile[k, l].lava(lava: true);
                                }
                            }
                            else if (l > GenVars.lavaLine)
{
                                Main.tile[k, l].lava(lava: true);
                            }
                        }
                        Main.tile[k, l].active(active: false);
                        continue;
                    }
                    if (flag && Math.Abs((double)k - val.X) + Math.Abs((double)l - val.Y) < strength * 0.3 * (1.0 + (double)genRand.Next(-10, 11) * 0.01))
                    {
                        PlaceWall(k, l, 180, mute: true);
                    }
                    if (flag2 && Math.Abs((double)k - val.X) + Math.Abs((double)l - val.Y) < strength * 0.3 * (1.0 + (double)genRand.Next(-10, 11) * 0.01))
                    {
                        PlaceWall(k, l, 178, mute: true);
                    }
                    if (overRide || !Main.tile[k, l].active())
                    {
                        Tile tile = Main.tile[k, l];
                        bool flag3 = false;
                        flag3 = Main.tileStone[type] && tile.type != 1;
                        if (!TileID.Sets.CanBeClearedDuringGeneration[tile.type])
{
                            flag3 = true;
                        }
                        switch (tile.type)
{
                        case 53:
                            if (type == 59 && GenVars.UndergroundDesertLocation.Contains(k, l))
{
                                flag3 = true;
                            }
                            if (type == 40)
{
                                flag3 = true;
                            }
                            if ((double)l < Main.worldSurface && type != 59)
{
                                flag3 = true;
                            }
                            break;
                        case 45:
                        case 147:
                        case 189:
                        case 190:
                        case 196:
                        case 460:
                            flag3 = true;
                            break;
                        case 396:
                        case 397:
                            flag3 = !TileID.Sets.Ore[type];
                            break;
                        case 1:
                            if (type == 59 && (double)l < Main.worldSurface + (double)genRand.Next(-50, 50))
{
                                flag3 = true;
                            }
                            break;
                        case 367:
                        case 368:
                            if (type == 59)
{
                                flag3 = true;
                            }
                            break;
                        }
                        if (!flag3)
{
                            tile.type = (ushort)type;
                        }
                    }
                    if (addTile)
                    {
                        Main.tile[k, l].active(active: true);
                        Main.tile[k, l].liquid = 0;
                        Main.tile[k, l].lava(lava: false);
                    }
                    if (noYChange && (double)l < Main.worldSurface && type != 59)
                    {
                        Main.tile[k, l].wall = 2;
                    }
                    if (type == 59 && l > GenVars.waterLine && Main.tile[k, l].liquid > 0)
                    {
                        Main.tile[k, l].lava(lava: false);
                        Main.tile[k, l].liquid = 0;
                    }
                }
            }
            val += val2;
            if ((!drunkWorldGen || genRand.Next(3) != 0) && num > 50.0)
            {
                val += val2;
                num2 -= 1.0;
                val2.Y += (double)genRand.Next(-10, 11) * 0.05;
                val2.X += (double)genRand.Next(-10, 11) * 0.05;
                if (num > 100.0)
                {
                    val += val2;
                    num2 -= 1.0;
                    val2.Y += (double)genRand.Next(-10, 11) * 0.05;
                    val2.X += (double)genRand.Next(-10, 11) * 0.05;
                    if (num > 150.0)
                    {
                        val += val2;
                        num2 -= 1.0;
                        val2.Y += (double)genRand.Next(-10, 11) * 0.05;
                        val2.X += (double)genRand.Next(-10, 11) * 0.05;
                        if (num > 200.0)
{
                            val += val2;
                            num2 -= 1.0;
                            val2.Y += (double)genRand.Next(-10, 11) * 0.05;
                            val2.X += (double)genRand.Next(-10, 11) * 0.05;
                            if (num > 250.0)
{
                                val += val2;
                                num2 -= 1.0;
                                val2.Y += (double)genRand.Next(-10, 11) * 0.05;
                                val2.X += (double)genRand.Next(-10, 11) * 0.05;
                                if (num > 300.0)
{
                                    val += val2;
                                    num2 -= 1.0;
                                    val2.Y += (double)genRand.Next(-10, 11) * 0.05;
                                    val2.X += (double)genRand.Next(-10, 11) * 0.05;
                                    if (num > 400.0)
{
                                        val += val2;
                                        num2 -= 1.0;
                                        val2.Y += (double)genRand.Next(-10, 11) * 0.05;
                                        val2.X += (double)genRand.Next(-10, 11) * 0.05;
                                        if (num > 500.0)
{
                                            val += val2;
                                            num2 -= 1.0;
                                            val2.Y += (double)genRand.Next(-10, 11) * 0.05;
                                            val2.X += (double)genRand.Next(-10, 11) * 0.05;
                                            if (num > 600.0)
{
                                                val += val2;
                                                num2 -= 1.0;
                                                val2.Y += (double)genRand.Next(-10, 11) * 0.05;
                                                val2.X += (double)genRand.Next(-10, 11) * 0.05;
                                                if (num > 700.0)
{
                                                    val += val2;
                                                    num2 -= 1.0;
                                                    val2.Y += (double)genRand.Next(-10, 11) * 0.05;
                                                    val2.X += (double)genRand.Next(-10, 11) * 0.05;
                                                    if (num > 800.0)
{
                                                        val += val2;
                                                        num2 -= 1.0;
                                                        val2.Y += (double)genRand.Next(-10, 11) * 0.05;
                                                        val2.X += (double)genRand.Next(-10, 11) * 0.05;
                                                        if (num > 900.0)
{
                                                            val += val2;
                                                            num2 -= 1.0;
                                                            val2.Y += (double)genRand.Next(-10, 11) * 0.05;
                                                            val2.X += (double)genRand.Next(-10, 11) * 0.05;
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
            val2.X += (double)genRand.Next(-10, 11) * 0.05;
            if (drunkWorldGen)
            {
                val2.X += (double)genRand.Next(-10, 11) * 0.25;
            }
            if (val2.X > 1.0)
            {
                val2.X = 1.0;
            }
            if (val2.X < -1.0)
            {
                val2.X = -1.0;
            }
            if (!noYChange)
            {
                val2.Y += (double)genRand.Next(-10, 11) * 0.05;
                if (val2.Y > 1.0)
                {
                    val2.Y = 1.0;
                }
                if (val2.Y < -1.0)
                {
                    val2.Y = -1.0;
                }
            }
            else if (type != 59 && num < 3.0)
            {
                if (val2.Y > 1.0)
                {
                    val2.Y = 1.0;
                }
                if (val2.Y < -1.0)
                {
                    val2.Y = -1.0;
                }
            }
            if (type == 59 && !noYChange)
            {
                if (val2.Y > 0.5)
                {
                    val2.Y = 0.5;
                }
                if (val2.Y < -0.5)
                {
                    val2.Y = -0.5;
                }
                if (val.Y < Main.rockLayer + 100.0)
                {
                    val2.Y = 1.0;
                }
                if (val.Y > (double)(Main.maxTilesY - 300))
                {
                    val2.Y = -1.0;
                }
            }
        }
    }
References Terraria.Tile.active(), Terraria.ID.TileID.Sets.CanBeClearedDuringGeneration, Terraria.Tile.lava(), Terraria.WorldBuilding.GenVars.lavaLine, Terraria.Tile.liquid, Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.WorldBuilding.GenVars.mudWall, Terraria.ID.TileID.Sets.Ore, Terraria.Main.rockLayer, Terraria.Main.tile, Terraria.Main.tileStone, Terraria.Tile.type, Terraria.WorldBuilding.GenVars.UndergroundDesertLocation, Terraria.Tile.wall, Terraria.WorldBuilding.GenVars.waterLine, ReLogic.Utilities.Vector2D.X, and ReLogic.Utilities.Vector2D.Y.
Referenced by Terraria.GameContent.Biomes.JunglePass.ApplyPass(), Terraria.GameContent.Biomes.JunglePass.GenerateFinishingTouches(), Terraria.GameContent.Biomes.JunglePass.GenerateTunnelToSurface(), Terraria.WorldGen.GenerateWorld(), Terraria.GameContent.Biomes.JunglePass.PlaceFirstPassMud(), and Terraria.GameContent.Biomes.JunglePass.PlaceGemsAt().