Terraria: System.IO.IsolatedStorage.IsolatedStorage.InitStore
InitStore() [2/2]
void System.IO.IsolatedStorage.IsolatedStorage.InitStore (IsolatedStorageScope scope, Type? domainEvidenceType, Type? assemblyEvidenceType) inline protected inherited
Definition at line 125 of file IsolatedStorage.cs.
    {
        VerifyScope(scope);
        Scope = scope;
        Helper.GetDefaultIdentityAndHash(out var identity, out var hash, SeparatorInternal);
        if (Helper.IsApplication(scope))
        {
            _applicationIdentity = identity;
        }
        else
        {
            if (Helper.IsDomain(scope))
            {
                _domainIdentity = identity;
                IFormatProvider formatProvider = null;
                IFormatProvider provider = formatProvider;
                Span<char> initialBuffer = stackalloc char[128];
                DefaultInterpolatedStringHandler handler = new DefaultInterpolatedStringHandler(0, 3, formatProvider, initialBuffer);
                handler.AppendFormatted(hash);
                handler.AppendFormatted(SeparatorExternal);
                handler.AppendFormatted(hash);
                hash = string.Create(provider, initialBuffer, ref handler);
            }
            _assemblyIdentity = identity;
        }
        IdentityHash = hash;
    }
References System.IO.IsolatedStorage.IsolatedStorage._applicationIdentity, System.IO.IsolatedStorage.IsolatedStorage._assemblyIdentity, System.IO.IsolatedStorage.IsolatedStorage._domainIdentity, System.Runtime.CompilerServices.DefaultInterpolatedStringHandler.AppendFormatted(), System.IO.IsolatedStorage.Helper.GetDefaultIdentityAndHash(), System.IO.IsolatedStorage.IsolatedStorage.IdentityHash, System.IO.IsolatedStorage.Helper.IsApplication(), System.IO.IsolatedStorage.Helper.IsDomain(), System.IO.IsolatedStorage.IsolatedStorage.Scope, System.IO.IsolatedStorage.IsolatedStorage.SeparatorExternal, System.IO.IsolatedStorage.IsolatedStorage.SeparatorInternal, and System.IO.IsolatedStorage.IsolatedStorage.VerifyScope().