Terraria: Terraria.WorldGen.IsRope
IsRope()
static bool Terraria.WorldGen.IsRope (int x, int y) inline static
    {
        if (Main.tile[x, y] == null || !Main.tile[x, y].active())
        {
            return false;
        }
        if (Main.tileRope[Main.tile[x, y].type])
        {
            return true;
        }
        if ((Main.tile[x, y].type == 314 || TileID.Sets.Platforms[Main.tile[x, y].type]) && Main.tile[x, y - 1] != null && Main.tile[x, y + 1] != null && Main.tile[x, y - 1].active() && Main.tile[x, y + 1].active() && Main.tileRope[Main.tile[x, y - 1].type] && Main.tileRope[Main.tile[x, y + 1].type])
        {
            return true;
        }
        return false;
    }
References Terraria.Tile.active(), Terraria.ID.TileID.Sets.Platforms, Terraria.Main.tile, Terraria.Main.tileRope, and Terraria.Tile.type.
Referenced by Terraria.GameContent.Drawing.TileDrawing.DrawBasicTile(), Terraria.GameContent.Drawing.TileDrawing.DrawTile_MinecartTrack(), Terraria.Player.FindPulley(), and Terraria.Player.Update().