Terraria: Terraria.WorldGen.GrowTree
GrowTree()
static bool Terraria.WorldGen.GrowTree (int i, int y) inline static
Definition at line 21606 of file WorldGen.cs.
    {
        int j;
        for (j = y; Main.tile[i, j].type == 20; j++)
        {
        }
        if ((Main.tile[i - 1, j - 1].liquid != 0 || Main.tile[i, j - 1].liquid != 0 || Main.tile[i + 1, j - 1].liquid != 0) && !notTheBees)
        {
            return false;
        }
        if (Main.tile[i, j].nactive() && !Main.tile[i, j].halfBrick() && Main.tile[i, j].slope() == 0 && IsTileTypeFitForTree(Main.tile[i, j].type) && ((Main.remixWorld && (double)j > Main.worldSurface) || Main.tile[i, j - 1].wall == 0 || DefaultTreeWallTest(Main.tile[i, j - 1].wall)) && ((Main.tile[i - 1, j].active() && IsTileTypeFitForTree(Main.tile[i - 1, j].type)) || (Main.tile[i + 1, j].active() && IsTileTypeFitForTree(Main.tile[i + 1, j].type))))
        {
            TileColorCache cache = Main.tile[i, j].BlockColorAndCoating();
            if (Main.tenthAnniversaryWorld && !gen)
            {
                cache.Color = (byte)genRand.Next(1, 13);
            }
            int num = 2;
            int num2 = genRand.Next(5, 17);
            int num3 = num2 + 4;
            if (Main.tile[i, j].type == 60)
            {
                num3 += 5;
            }
            bool flag = false;
            if (Main.tile[i, j].type == 70 && EmptyTileCheck(i - num, i + num, j - num3, j - 3, 20) && EmptyTileCheck(i - 1, i + 1, j - 2, j - 1, 20))
            {
                flag = true;
            }
            if (EmptyTileCheck(i - num, i + num, j - num3, j - 1, 20))
            {
                flag = true;
            }
            if (flag)
            {
                bool flag2 = Main.remixWorld && (double)j < Main.worldSurface;
                bool flag3 = false;
                bool flag4 = false;
                int num4;
                for (int k = j - num2; k < j; k++)
                {
                    Main.tile[i, k].frameNumber((byte)genRand.Next(3));
                    Main.tile[i, k].active(active: true);
                    Main.tile[i, k].type = 5;
                    Main.tile[i, k].UseBlockColors(cache);
                    num4 = genRand.Next(3);
                    int num5 = genRand.Next(10);
                    if (k == j - 1 || k == j - num2)
                    {
                        num5 = 0;
                    }
                    while (((num5 == 5 || num5 == 7) && flag3) || ((num5 == 6 || num5 == 7) && flag4))
                    {
                        num5 = genRand.Next(10);
                    }
                    flag3 = false;
                    flag4 = false;
                    if (num5 == 5 || num5 == 7)
                    {
                        flag3 = true;
                    }
                    if (num5 == 6 || num5 == 7)
                    {
                        flag4 = true;
                    }
                    switch (num5)
                    {
                    case 1:
                        if (num4 == 0)
{
                            Main.tile[i, k].frameX = 0;
                            Main.tile[i, k].frameY = 66;
                        }
                        if (num4 == 1)
{
                            Main.tile[i, k].frameX = 0;
                            Main.tile[i, k].frameY = 88;
                        }
                        if (num4 == 2)
{
                            Main.tile[i, k].frameX = 0;
                            Main.tile[i, k].frameY = 110;
                        }
                        break;
                    case 2:
                        if (num4 == 0)
{
                            Main.tile[i, k].frameX = 22;
                            Main.tile[i, k].frameY = 0;
                        }
                        if (num4 == 1)
{
                            Main.tile[i, k].frameX = 22;
                            Main.tile[i, k].frameY = 22;
                        }
                        if (num4 == 2)
{
                            Main.tile[i, k].frameX = 22;
                            Main.tile[i, k].frameY = 44;
                        }
                        break;
                    case 3:
                        if (num4 == 0)
{
                            Main.tile[i, k].frameX = 44;
                            Main.tile[i, k].frameY = 66;
                        }
                        if (num4 == 1)
{
                            Main.tile[i, k].frameX = 44;
                            Main.tile[i, k].frameY = 88;
                        }
                        if (num4 == 2)
{
                            Main.tile[i, k].frameX = 44;
                            Main.tile[i, k].frameY = 110;
                        }
                        break;
                    case 4:
                        if (num4 == 0)
{
                            Main.tile[i, k].frameX = 22;
                            Main.tile[i, k].frameY = 66;
                        }
                        if (num4 == 1)
{
                            Main.tile[i, k].frameX = 22;
                            Main.tile[i, k].frameY = 88;
                        }
                        if (num4 == 2)
{
                            Main.tile[i, k].frameX = 22;
                            Main.tile[i, k].frameY = 110;
                        }
                        break;
                    case 5:
                        if (num4 == 0)
{
                            Main.tile[i, k].frameX = 88;
                            Main.tile[i, k].frameY = 0;
                        }
                        if (num4 == 1)
{
                            Main.tile[i, k].frameX = 88;
                            Main.tile[i, k].frameY = 22;
                        }
                        if (num4 == 2)
{
                            Main.tile[i, k].frameX = 88;
                            Main.tile[i, k].frameY = 44;
                        }
                        break;
                    case 6:
                        if (num4 == 0)
{
                            Main.tile[i, k].frameX = 66;
                            Main.tile[i, k].frameY = 66;
                        }
                        if (num4 == 1)
{
                            Main.tile[i, k].frameX = 66;
                            Main.tile[i, k].frameY = 88;
                        }
                        if (num4 == 2)
{
                            Main.tile[i, k].frameX = 66;
                            Main.tile[i, k].frameY = 110;
                        }
                        break;
                    case 7:
                        if (num4 == 0)
{
                            Main.tile[i, k].frameX = 110;
                            Main.tile[i, k].frameY = 66;
                        }
                        if (num4 == 1)
{
                            Main.tile[i, k].frameX = 110;
                            Main.tile[i, k].frameY = 88;
                        }
                        if (num4 == 2)
{
                            Main.tile[i, k].frameX = 110;
                            Main.tile[i, k].frameY = 110;
                        }
                        break;
                    default:
                        if (num4 == 0)
{
                            Main.tile[i, k].frameX = 0;
                            Main.tile[i, k].frameY = 0;
                        }
                        if (num4 == 1)
{
                            Main.tile[i, k].frameX = 0;
                            Main.tile[i, k].frameY = 22;
                        }
                        if (num4 == 2)
{
                            Main.tile[i, k].frameX = 0;
                            Main.tile[i, k].frameY = 44;
                        }
                        break;
                    }
                    if (num5 == 5 || num5 == 7)
                    {
                        Main.tile[i - 1, k].active(active: true);
                        Main.tile[i - 1, k].type = 5;
                        Main.tile[i - 1, k].UseBlockColors(cache);
                        num4 = genRand.Next(3);
                        if (genRand.Next(3) < 2 && !flag2)
{
                            if (num4 == 0)
{
                                Main.tile[i - 1, k].frameX = 44;
                                Main.tile[i - 1, k].frameY = 198;
                            }
                            if (num4 == 1)
{
                                Main.tile[i - 1, k].frameX = 44;
                                Main.tile[i - 1, k].frameY = 220;
                            }
                            if (num4 == 2)
{
                                Main.tile[i - 1, k].frameX = 44;
                                Main.tile[i - 1, k].frameY = 242;
                            }
                        }
                        else
{
                            if (num4 == 0)
{
                                Main.tile[i - 1, k].frameX = 66;
                                Main.tile[i - 1, k].frameY = 0;
                            }
                            if (num4 == 1)
{
                                Main.tile[i - 1, k].frameX = 66;
                                Main.tile[i - 1, k].frameY = 22;
                            }
                            if (num4 == 2)
{
                                Main.tile[i - 1, k].frameX = 66;
                                Main.tile[i - 1, k].frameY = 44;
                            }
                        }
                    }
                    if (num5 != 6 && num5 != 7)
                    {
                        continue;
                    }
                    Main.tile[i + 1, k].active(active: true);
                    Main.tile[i + 1, k].type = 5;
                    Main.tile[i + 1, k].UseBlockColors(cache);
                    num4 = genRand.Next(3);
                    if (genRand.Next(3) < 2 && !flag2)
                    {
                        if (num4 == 0)
{
                            Main.tile[i + 1, k].frameX = 66;
                            Main.tile[i + 1, k].frameY = 198;
                        }
                        if (num4 == 1)
{
                            Main.tile[i + 1, k].frameX = 66;
                            Main.tile[i + 1, k].frameY = 220;
                        }
                        if (num4 == 2)
{
                            Main.tile[i + 1, k].frameX = 66;
                            Main.tile[i + 1, k].frameY = 242;
                        }
                    }
                    else
                    {
                        if (num4 == 0)
{
                            Main.tile[i + 1, k].frameX = 88;
                            Main.tile[i + 1, k].frameY = 66;
                        }
                        if (num4 == 1)
{
                            Main.tile[i + 1, k].frameX = 88;
                            Main.tile[i + 1, k].frameY = 88;
                        }
                        if (num4 == 2)
{
                            Main.tile[i + 1, k].frameX = 88;
                            Main.tile[i + 1, k].frameY = 110;
                        }
                    }
                }
                int num6 = genRand.Next(3);
                bool flag5 = false;
                bool flag6 = false;
                if (Main.tile[i - 1, j].nactive() && !Main.tile[i - 1, j].halfBrick() && Main.tile[i - 1, j].slope() == 0 && IsTileTypeFitForTree(Main.tile[i - 1, j].type))
                {
                    flag5 = true;
                }
                if (Main.tile[i + 1, j].nactive() && !Main.tile[i + 1, j].halfBrick() && Main.tile[i + 1, j].slope() == 0 && IsTileTypeFitForTree(Main.tile[i + 1, j].type))
                {
                    flag6 = true;
                }
                if (!flag5)
                {
                    if (num6 == 0)
                    {
                        num6 = 2;
                    }
                    if (num6 == 1)
                    {
                        num6 = 3;
                    }
                }
                if (!flag6)
                {
                    if (num6 == 0)
                    {
                        num6 = 1;
                    }
                    if (num6 == 2)
                    {
                        num6 = 3;
                    }
                }
                if (flag5 && !flag6)
                {
                    num6 = 2;
                }
                if (flag6 && !flag5)
                {
                    num6 = 1;
                }
                if (num6 == 0 || num6 == 1)
                {
                    Main.tile[i + 1, j - 1].active(active: true);
                    Main.tile[i + 1, j - 1].type = 5;
                    Main.tile[i + 1, j - 1].UseBlockColors(cache);
                    num4 = genRand.Next(3);
                    if (num4 == 0)
                    {
                        Main.tile[i + 1, j - 1].frameX = 22;
                        Main.tile[i + 1, j - 1].frameY = 132;
                    }
                    if (num4 == 1)
                    {
                        Main.tile[i + 1, j - 1].frameX = 22;
                        Main.tile[i + 1, j - 1].frameY = 154;
                    }
                    if (num4 == 2)
                    {
                        Main.tile[i + 1, j - 1].frameX = 22;
                        Main.tile[i + 1, j - 1].frameY = 176;
                    }
                }
                if (num6 == 0 || num6 == 2)
                {
                    Main.tile[i - 1, j - 1].active(active: true);
                    Main.tile[i - 1, j - 1].type = 5;
                    Main.tile[i - 1, j - 1].UseBlockColors(cache);
                    num4 = genRand.Next(3);
                    if (num4 == 0)
                    {
                        Main.tile[i - 1, j - 1].frameX = 44;
                        Main.tile[i - 1, j - 1].frameY = 132;
                    }
                    if (num4 == 1)
                    {
                        Main.tile[i - 1, j - 1].frameX = 44;
                        Main.tile[i - 1, j - 1].frameY = 154;
                    }
                    if (num4 == 2)
                    {
                        Main.tile[i - 1, j - 1].frameX = 44;
                        Main.tile[i - 1, j - 1].frameY = 176;
                    }
                }
                num4 = genRand.Next(3);
                switch (num6)
                {
                case 0:
                    if (num4 == 0)
                    {
                        Main.tile[i, j - 1].frameX = 88;
                        Main.tile[i, j - 1].frameY = 132;
                    }
                    if (num4 == 1)
                    {
                        Main.tile[i, j - 1].frameX = 88;
                        Main.tile[i, j - 1].frameY = 154;
                    }
                    if (num4 == 2)
                    {
                        Main.tile[i, j - 1].frameX = 88;
                        Main.tile[i, j - 1].frameY = 176;
                    }
                    break;
                case 1:
                    if (num4 == 0)
                    {
                        Main.tile[i, j - 1].frameX = 0;
                        Main.tile[i, j - 1].frameY = 132;
                    }
                    if (num4 == 1)
                    {
                        Main.tile[i, j - 1].frameX = 0;
                        Main.tile[i, j - 1].frameY = 154;
                    }
                    if (num4 == 2)
                    {
                        Main.tile[i, j - 1].frameX = 0;
                        Main.tile[i, j - 1].frameY = 176;
                    }
                    break;
                case 2:
                    if (num4 == 0)
                    {
                        Main.tile[i, j - 1].frameX = 66;
                        Main.tile[i, j - 1].frameY = 132;
                    }
                    if (num4 == 1)
                    {
                        Main.tile[i, j - 1].frameX = 66;
                        Main.tile[i, j - 1].frameY = 154;
                    }
                    if (num4 == 2)
                    {
                        Main.tile[i, j - 1].frameX = 66;
                        Main.tile[i, j - 1].frameY = 176;
                    }
                    break;
                }
                if (genRand.Next(13) != 0 && !flag2)
                {
                    num4 = genRand.Next(3);
                    if (num4 == 0)
                    {
                        Main.tile[i, j - num2].frameX = 22;
                        Main.tile[i, j - num2].frameY = 198;
                    }
                    if (num4 == 1)
                    {
                        Main.tile[i, j - num2].frameX = 22;
                        Main.tile[i, j - num2].frameY = 220;
                    }
                    if (num4 == 2)
                    {
                        Main.tile[i, j - num2].frameX = 22;
                        Main.tile[i, j - num2].frameY = 242;
                    }
                }
                else
                {
                    num4 = genRand.Next(3);
                    if (num4 == 0)
                    {
                        Main.tile[i, j - num2].frameX = 0;
                        Main.tile[i, j - num2].frameY = 198;
                    }
                    if (num4 == 1)
                    {
                        Main.tile[i, j - num2].frameX = 0;
                        Main.tile[i, j - num2].frameY = 220;
                    }
                    if (num4 == 2)
                    {
                        Main.tile[i, j - num2].frameX = 0;
                        Main.tile[i, j - num2].frameY = 242;
                    }
                }
                RangeFrame(i - 2, j - num2 - 1, i + 2, j + 1);
                if (Main.netMode == 2)
                {
                    NetMessage.SendTileSquare(-1, i - 1, j - num2, 3, num2);
                }
                return true;
            }
        }
        return false;
    }
References Terraria.Tile.active(), Terraria.Tile.BlockColorAndCoating(), Terraria.Tile.frameNumber(), Terraria.Tile.frameX, Terraria.Tile.frameY, Terraria.Tile.halfBrick(), Terraria.Tile.liquid, Terraria.Tile.nactive(), Terraria.Main.netMode, Terraria.Main.remixWorld, Terraria.NetMessage.SendTileSquare(), Terraria.Tile.slope(), Terraria.Main.tenthAnniversaryWorld, Terraria.Main.tile, Terraria.Tile.type, Terraria.Tile.UseBlockColors(), Terraria.Tile.wall, and Terraria.Main.worldSurface.