Terraria: Terraria.WorldGen.DontStarveTryWateringTile
DontStarveTryWateringTile()
static void Terraria.WorldGen.DontStarveTryWateringTile (int x, int y) inline static
    {
        Tile tile = Main.tile[x, y];
        if (tile.active() && TileObjectData.CheckWaterDeath(tile) && !IsSafeFromRain(x, y) && !HasAnyWireNearby(x, y, 0) && !TryToggleLight(x, y, false, skipWires: false))
        {
            KillTile(x, y);
            if (Main.netMode == 2)
            {
                NetMessage.SendData(17, -1, -1, null, 0, x, y);
            }
        }
    }
References Terraria.Tile.active(), Terraria.ObjectData.TileObjectData.CheckWaterDeath(), Terraria.Main.netMode, Terraria.NetMessage.SendData(), and Terraria.Main.tile.