Terraria: Terraria.WorldGen.EveryTileFrame
EveryTileFrame()
static void Terraria.WorldGen.EveryTileFrame () inline static
    {
        Stopwatch stopwatch = new Stopwatch();
        stopwatch.Start();
        noLiquidCheck = true;
        noTileActions = true;
        for (int i = 0; i < Main.maxTilesX; i++)
        {
            float num = (float)i / (float)Main.maxTilesX;
            Main.statusText = Lang.gen[55].Value + " " + (int)(num * 100f + 1f) + "%";
            for (int j = 0; j < Main.maxTilesY; j++)
            {
                if (Main.tile[i, j].active())
                {
                    TileFrame(i, j, resetFrame: true);
                }
                if (Main.tile[i, j].wall > 0)
                {
                    Framing.WallFrame(i, j, resetFrame: true);
                }
            }
        }
        noLiquidCheck = false;
        noTileActions = false;
        _ = stopwatch.ElapsedMilliseconds;
    }
References Terraria.Tile.active(), Terraria.Lang.gen, Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.Main.tile, Terraria.Localization.LocalizedText.Value, Terraria.Tile.wall, and Terraria.Framing.WallFrame().
Referenced by Terraria.Main.Initialize_AlmostEverything().