Terraria: Terraria.WorldGen.gemCave
gemCave()
static void Terraria.WorldGen.gemCave (int x, int y) inline static
    {
        countTiles(x, y);
        for (int i = 0; i < 6; i++)
        {
            gem[i] = false;
        }
        gem[genRand.Next(6)] = true;
        for (int j = 0; j < 6; j++)
        {
            if (genRand.Next(6) == 0)
            {
                gem[j] = true;
            }
        }
        Spread.Gem(x, y);
    }
References Terraria.WorldGen.countTiles(), Terraria.WorldGen.Spread.Gem(), Terraria.WorldGen.gem, Terraria.WorldGen.genRand, and Terraria.Utilities.UnifiedRandom.Next().