Terraria: Terraria.WorldGen.GrowTreeWithSettings
GrowTreeWithSettings()
static bool Terraria.WorldGen.GrowTreeWithSettings (int checkedX, int checkedY, GrowTreeSettings settings) inline static
    {
        int i;
        for (i = checkedY; Main.tile[checkedX, i].type == settings.SaplingTileType; i++)
        {
        }
        if (Main.tile[checkedX - 1, i - 1].liquid != 0 || Main.tile[checkedX, i - 1].liquid != 0 || Main.tile[checkedX + 1, i - 1].liquid != 0)
        {
            return false;
        }
        Tile tile = Main.tile[checkedX, i];
        if (!tile.nactive() || tile.halfBrick() || tile.slope() != 0)
        {
            return false;
        }
        bool flag = settings.WallTest(Main.tile[checkedX, i - 1].wall);
        if (!settings.GroundTest(tile.type) || !flag)
        {
            return false;
        }
        if ((!Main.tile[checkedX - 1, i].active() || !settings.GroundTest(Main.tile[checkedX - 1, i].type)) && (!Main.tile[checkedX + 1, i].active() || !settings.GroundTest(Main.tile[checkedX + 1, i].type)))
        {
            return false;
        }
        TileColorCache cache = Main.tile[checkedX, i].BlockColorAndCoating();
        if (Main.tenthAnniversaryWorld && !gen && (settings.TreeTileType == 596 || settings.TreeTileType == 616))
        {
            cache.Color = (byte)genRand.Next(1, 13);
        }
        int num = 2;
        int num2 = genRand.Next(settings.TreeHeightMin, settings.TreeHeightMax + 1);
        int num3 = num2 + settings.TreeTopPaddingNeeded;
        if (!EmptyTileCheck(checkedX - num, checkedX + num, i - num3, i - 1, 20))
        {
            return false;
        }
        bool flag2 = false;
        bool flag3 = false;
        int num4;
        for (int j = i - num2; j < i; j++)
        {
            Tile tile2 = Main.tile[checkedX, j];
            tile2.frameNumber((byte)genRand.Next(3));
            tile2.active(active: true);
            tile2.type = settings.TreeTileType;
            tile2.UseBlockColors(cache);
            num4 = genRand.Next(3);
            int num5 = genRand.Next(10);
            if (j == i - 1 || j == i - num2)
            {
                num5 = 0;
            }
            while (((num5 == 5 || num5 == 7) && flag2) || ((num5 == 6 || num5 == 7) && flag3))
            {
                num5 = genRand.Next(10);
            }
            flag2 = false;
            flag3 = false;
            if (num5 == 5 || num5 == 7)
            {
                flag2 = true;
            }
            if (num5 == 6 || num5 == 7)
            {
                flag3 = true;
            }
            switch (num5)
            {
            case 1:
                if (num4 == 0)
                {
                    tile2.frameX = 0;
                    tile2.frameY = 66;
                }
                if (num4 == 1)
                {
                    tile2.frameX = 0;
                    tile2.frameY = 88;
                }
                if (num4 == 2)
                {
                    tile2.frameX = 0;
                    tile2.frameY = 110;
                }
                break;
            case 2:
                if (num4 == 0)
                {
                    tile2.frameX = 22;
                    tile2.frameY = 0;
                }
                if (num4 == 1)
                {
                    tile2.frameX = 22;
                    tile2.frameY = 22;
                }
                if (num4 == 2)
                {
                    tile2.frameX = 22;
                    tile2.frameY = 44;
                }
                break;
            case 3:
                if (num4 == 0)
                {
                    tile2.frameX = 44;
                    tile2.frameY = 66;
                }
                if (num4 == 1)
                {
                    tile2.frameX = 44;
                    tile2.frameY = 88;
                }
                if (num4 == 2)
                {
                    tile2.frameX = 44;
                    tile2.frameY = 110;
                }
                break;
            case 4:
                if (num4 == 0)
                {
                    tile2.frameX = 22;
                    tile2.frameY = 66;
                }
                if (num4 == 1)
                {
                    tile2.frameX = 22;
                    tile2.frameY = 88;
                }
                if (num4 == 2)
                {
                    tile2.frameX = 22;
                    tile2.frameY = 110;
                }
                break;
            case 5:
                if (num4 == 0)
                {
                    tile2.frameX = 88;
                    tile2.frameY = 0;
                }
                if (num4 == 1)
                {
                    tile2.frameX = 88;
                    tile2.frameY = 22;
                }
                if (num4 == 2)
                {
                    tile2.frameX = 88;
                    tile2.frameY = 44;
                }
                break;
            case 6:
                if (num4 == 0)
                {
                    tile2.frameX = 66;
                    tile2.frameY = 66;
                }
                if (num4 == 1)
                {
                    tile2.frameX = 66;
                    tile2.frameY = 88;
                }
                if (num4 == 2)
                {
                    tile2.frameX = 66;
                    tile2.frameY = 110;
                }
                break;
            case 7:
                if (num4 == 0)
                {
                    tile2.frameX = 110;
                    tile2.frameY = 66;
                }
                if (num4 == 1)
                {
                    tile2.frameX = 110;
                    tile2.frameY = 88;
                }
                if (num4 == 2)
                {
                    tile2.frameX = 110;
                    tile2.frameY = 110;
                }
                break;
            default:
                if (num4 == 0)
                {
                    tile2.frameX = 0;
                    tile2.frameY = 0;
                }
                if (num4 == 1)
                {
                    tile2.frameX = 0;
                    tile2.frameY = 22;
                }
                if (num4 == 2)
                {
                    tile2.frameX = 0;
                    tile2.frameY = 44;
                }
                break;
            }
            if (num5 == 5 || num5 == 7)
            {
                Tile tile3 = Main.tile[checkedX - 1, j];
                tile3.active(active: true);
                tile3.type = settings.TreeTileType;
                tile3.UseBlockColors(cache);
                num4 = genRand.Next(3);
                if (genRand.Next(3) < 2)
                {
                    if (num4 == 0)
                    {
                        tile3.frameX = 44;
                        tile3.frameY = 198;
                    }
                    if (num4 == 1)
                    {
                        tile3.frameX = 44;
                        tile3.frameY = 220;
                    }
                    if (num4 == 2)
                    {
                        tile3.frameX = 44;
                        tile3.frameY = 242;
                    }
                }
                else
                {
                    if (num4 == 0)
                    {
                        tile3.frameX = 66;
                        tile3.frameY = 0;
                    }
                    if (num4 == 1)
                    {
                        tile3.frameX = 66;
                        tile3.frameY = 22;
                    }
                    if (num4 == 2)
                    {
                        tile3.frameX = 66;
                        tile3.frameY = 44;
                    }
                }
            }
            if (num5 != 6 && num5 != 7)
            {
                continue;
            }
            Tile tile4 = Main.tile[checkedX + 1, j];
            tile4.active(active: true);
            tile4.type = settings.TreeTileType;
            tile4.UseBlockColors(cache);
            num4 = genRand.Next(3);
            if (genRand.Next(3) < 2)
            {
                if (num4 == 0)
                {
                    tile4.frameX = 66;
                    tile4.frameY = 198;
                }
                if (num4 == 1)
                {
                    tile4.frameX = 66;
                    tile4.frameY = 220;
                }
                if (num4 == 2)
                {
                    tile4.frameX = 66;
                    tile4.frameY = 242;
                }
            }
            else
            {
                if (num4 == 0)
                {
                    tile4.frameX = 88;
                    tile4.frameY = 66;
                }
                if (num4 == 1)
                {
                    tile4.frameX = 88;
                    tile4.frameY = 88;
                }
                if (num4 == 2)
                {
                    tile4.frameX = 88;
                    tile4.frameY = 110;
                }
            }
        }
        bool flag4 = false;
        bool flag5 = false;
        if (Main.tile[checkedX - 1, i].nactive() && !Main.tile[checkedX - 1, i].halfBrick() && Main.tile[checkedX - 1, i].slope() == 0 && IsTileTypeFitForTree(Main.tile[checkedX - 1, i].type))
        {
            flag4 = true;
        }
        if (Main.tile[checkedX + 1, i].nactive() && !Main.tile[checkedX + 1, i].halfBrick() && Main.tile[checkedX + 1, i].slope() == 0 && IsTileTypeFitForTree(Main.tile[checkedX + 1, i].type))
        {
            flag5 = true;
        }
        if (genRand.Next(3) == 0)
        {
            flag4 = false;
        }
        if (genRand.Next(3) == 0)
        {
            flag5 = false;
        }
        if (flag5)
        {
            Main.tile[checkedX + 1, i - 1].active(active: true);
            Main.tile[checkedX + 1, i - 1].type = settings.TreeTileType;
            Main.tile[checkedX + 1, i - 1].UseBlockColors(cache);
            num4 = genRand.Next(3);
            if (num4 == 0)
            {
                Main.tile[checkedX + 1, i - 1].frameX = 22;
                Main.tile[checkedX + 1, i - 1].frameY = 132;
            }
            if (num4 == 1)
            {
                Main.tile[checkedX + 1, i - 1].frameX = 22;
                Main.tile[checkedX + 1, i - 1].frameY = 154;
            }
            if (num4 == 2)
            {
                Main.tile[checkedX + 1, i - 1].frameX = 22;
                Main.tile[checkedX + 1, i - 1].frameY = 176;
            }
        }
        if (flag4)
        {
            Main.tile[checkedX - 1, i - 1].active(active: true);
            Main.tile[checkedX - 1, i - 1].type = settings.TreeTileType;
            Main.tile[checkedX - 1, i - 1].UseBlockColors(cache);
            num4 = genRand.Next(3);
            if (num4 == 0)
            {
                Main.tile[checkedX - 1, i - 1].frameX = 44;
                Main.tile[checkedX - 1, i - 1].frameY = 132;
            }
            if (num4 == 1)
            {
                Main.tile[checkedX - 1, i - 1].frameX = 44;
                Main.tile[checkedX - 1, i - 1].frameY = 154;
            }
            if (num4 == 2)
            {
                Main.tile[checkedX - 1, i - 1].frameX = 44;
                Main.tile[checkedX - 1, i - 1].frameY = 176;
            }
        }
        num4 = genRand.Next(3);
        if (flag4 && flag5)
        {
            if (num4 == 0)
            {
                Main.tile[checkedX, i - 1].frameX = 88;
                Main.tile[checkedX, i - 1].frameY = 132;
            }
            if (num4 == 1)
            {
                Main.tile[checkedX, i - 1].frameX = 88;
                Main.tile[checkedX, i - 1].frameY = 154;
            }
            if (num4 == 2)
            {
                Main.tile[checkedX, i - 1].frameX = 88;
                Main.tile[checkedX, i - 1].frameY = 176;
            }
        }
        else if (flag4)
        {
            if (num4 == 0)
            {
                Main.tile[checkedX, i - 1].frameX = 0;
                Main.tile[checkedX, i - 1].frameY = 132;
            }
            if (num4 == 1)
            {
                Main.tile[checkedX, i - 1].frameX = 0;
                Main.tile[checkedX, i - 1].frameY = 154;
            }
            if (num4 == 2)
            {
                Main.tile[checkedX, i - 1].frameX = 0;
                Main.tile[checkedX, i - 1].frameY = 176;
            }
        }
        else if (flag5)
        {
            if (num4 == 0)
            {
                Main.tile[checkedX, i - 1].frameX = 66;
                Main.tile[checkedX, i - 1].frameY = 132;
            }
            if (num4 == 1)
            {
                Main.tile[checkedX, i - 1].frameX = 66;
                Main.tile[checkedX, i - 1].frameY = 154;
            }
            if (num4 == 2)
            {
                Main.tile[checkedX, i - 1].frameX = 66;
                Main.tile[checkedX, i - 1].frameY = 176;
            }
        }
        if (genRand.Next(13) != 0)
        {
            num4 = genRand.Next(3);
            if (num4 == 0)
            {
                Main.tile[checkedX, i - num2].frameX = 22;
                Main.tile[checkedX, i - num2].frameY = 198;
            }
            if (num4 == 1)
            {
                Main.tile[checkedX, i - num2].frameX = 22;
                Main.tile[checkedX, i - num2].frameY = 220;
            }
            if (num4 == 2)
            {
                Main.tile[checkedX, i - num2].frameX = 22;
                Main.tile[checkedX, i - num2].frameY = 242;
            }
        }
        else
        {
            num4 = genRand.Next(3);
            if (num4 == 0)
            {
                Main.tile[checkedX, i - num2].frameX = 0;
                Main.tile[checkedX, i - num2].frameY = 198;
            }
            if (num4 == 1)
            {
                Main.tile[checkedX, i - num2].frameX = 0;
                Main.tile[checkedX, i - num2].frameY = 220;
            }
            if (num4 == 2)
            {
                Main.tile[checkedX, i - num2].frameX = 0;
                Main.tile[checkedX, i - num2].frameY = 242;
            }
        }
        RangeFrame(checkedX - 2, i - num2 - 1, checkedX + 2, i + 1);
        if (Main.netMode == 2)
        {
            NetMessage.SendTileSquare(-1, checkedX - 1, i - num2, 3, num2);
        }
        return true;
    }
References Terraria.Tile.active(), Terraria.Tile.BlockColorAndCoating(), Terraria.Tile.frameNumber(), Terraria.Tile.frameX, Terraria.Tile.frameY, Terraria.WorldGen.GrowTreeSettings.GroundTest, Terraria.Tile.halfBrick(), Terraria.Tile.liquid, Terraria.Tile.nactive(), Terraria.Main.netMode, Terraria.WorldGen.GrowTreeSettings.SaplingTileType, Terraria.NetMessage.SendTileSquare(), Terraria.Tile.slope(), Terraria.Main.tenthAnniversaryWorld, Terraria.Main.tile, Terraria.WorldGen.GrowTreeSettings.TreeHeightMax, Terraria.WorldGen.GrowTreeSettings.TreeHeightMin, Terraria.WorldGen.GrowTreeSettings.TreeTileType, Terraria.WorldGen.GrowTreeSettings.TreeTopPaddingNeeded, Terraria.Tile.type, Terraria.Tile.UseBlockColors(), Terraria.Tile.wall, and Terraria.WorldGen.GrowTreeSettings.WallTest.