Terraria: Terraria.WorldGen.smCallBack
smCallBack()
static void Terraria.WorldGen.smCallBack (object threadContext) inline static
Definition at line 23420 of file WorldGen.cs.
    {
        IsGeneratingHardMode = true;
        TryProtectingSpawnedItems();
        if (Main.rand == null)
        {
            Main.rand = new UnifiedRandom((int)DateTime.Now.Ticks);
        }
        double num = (double)genRand.Next(300, 400) * 0.001;
        double num2 = (double)genRand.Next(200, 300) * 0.001;
        int num3 = (int)((double)Main.maxTilesX * num);
        int num4 = (int)((double)Main.maxTilesX * (1.0 - num));
        int num5 = 1;
        if (genRand.Next(2) == 0)
        {
            num4 = (int)((double)Main.maxTilesX * num);
            num3 = (int)((double)Main.maxTilesX * (1.0 - num));
            num5 = -1;
        }
        int num6 = 1;
        if (GenVars.dungeonX < Main.maxTilesX / 2)
        {
            num6 = -1;
        }
        if (num6 < 0)
        {
            if (num4 < num3)
            {
                num4 = (int)((double)Main.maxTilesX * num2);
            }
            else
            {
                num3 = (int)((double)Main.maxTilesX * num2);
            }
        }
        else if (num4 > num3)
        {
            num4 = (int)((double)Main.maxTilesX * (1.0 - num2));
        }
        else
        {
            num3 = (int)((double)Main.maxTilesX * (1.0 - num2));
        }
        if (Main.remixWorld)
        {
            int num7 = Main.maxTilesX / 7;
            int num8 = Main.maxTilesX / 14;
            if (Main.dungeonX < Main.maxTilesX / 2)
            {
                for (int i = Main.maxTilesX - num7 - num8; i < Main.maxTilesX; i++)
                {
                    for (int j = (int)Main.worldSurface + genRand.Next(-1, 2); j < Main.maxTilesY - 10; j++)
                    {
                        if (i > Main.maxTilesX - num7)
{
                            Convert(i, j, 2, 1);
                        }
                        else if (TileID.Sets.Crimson[Main.tile[i, j].type] || TileID.Sets.Corrupt[Main.tile[i, j].type])
{
                            Convert(i, j, 2, 1);
                        }
                    }
                }
            }
            else
            {
                for (int k = 0; k < num7 + num8; k++)
                {
                    for (int l = (int)Main.worldSurface + genRand.Next(-1, 2); l < Main.maxTilesY - 10; l++)
                    {
                        if (k < num7)
{
                            Convert(k, l, 2, 1);
                        }
                        else if (TileID.Sets.Crimson[Main.tile[k, l].type] || TileID.Sets.Corrupt[Main.tile[k, l].type])
{
                            Convert(k, l, 2, 1);
                        }
                    }
                }
            }
        }
        else
        {
            GERunner(num3, 0, 3 * num5, 5.0);
            GERunner(num4, 0, 3 * -num5, 5.0, good: false);
        }
        double num9 = (double)Main.maxTilesX / 4200.0;
        int num10 = (int)(25.0 * num9);
        ShapeData shapeData = new ShapeData();
        int num11 = 0;
        while (num10 > 0)
        {
            if (++num11 % 15000 == 0)
            {
                num10--;
            }
            Point point = RandomWorldPoint((int)Main.worldSurface - 100, 1, 190, 1);
            Tile tile = Main.tile[point.X, point.Y];
            Tile tile2 = Main.tile[point.X, point.Y - 1];
            ushort num12 = 0;
            if (TileID.Sets.Crimson[tile.type])
            {
                num12 = (ushort)(192 + genRand.Next(4));
            }
            else if (TileID.Sets.Corrupt[tile.type])
            {
                num12 = (ushort)(188 + genRand.Next(4));
            }
            else if (TileID.Sets.Hallow[tile.type])
            {
                num12 = (ushort)(200 + genRand.Next(4));
            }
            if (tile.active() && num12 != 0 && !tile2.active())
            {
                bool flag = WorldUtils.Gen(new Point(point.X, point.Y - 1), new ShapeFloodFill(1000), Actions.Chain(new Modifiers.IsNotSolid(), new Modifiers.OnlyWalls(0, 54, 55, 56, 57, 58, 59, 61, 185, 212, 213, 214, 215, 2, 196, 197, 198, 199, 15, 40, 71, 64, 204, 205, 206, 207, 208, 209, 210, 211, 71), new Actions.Blank().Output(shapeData)));
                if (shapeData.Count > 50 && flag)
                {
                    WorldUtils.Gen(new Point(point.X, point.Y), new ModShapes.OuterOutline(shapeData, useDiagonals: true, useInterior: true), new Actions.PlaceWall(num12));
                    num10--;
                }
                shapeData.Clear();
            }
        }
        if (Main.netMode == 0)
        {
            Main.NewText(Lang.misc[15].Value, 50, byte.MaxValue, 130);
        }
        else if (Main.netMode == 2)
        {
            ChatHelper.BroadcastChatMessage(NetworkText.FromKey(Lang.misc[15].Key), new Color(50, 255, 130));
        }
        AchievementsHelper.NotifyProgressionEvent(9);
        if (Main.netMode == 2)
        {
            Netplay.ResetSections();
        }
        UndoSpawnedItemProtection();
        IsGeneratingHardMode = false;
    }
References Terraria.Tile.active(), Terraria.Chat.ChatHelper.BroadcastChatMessage(), Terraria.WorldBuilding.Actions.Chain(), System.Collections.Generic.Dictionary< TKey, TValue >.Clear(), Terraria.ID.TileID.Sets.Corrupt, System.Collections.Generic.Dictionary< TKey, TValue >.Count, Terraria.ID.TileID.Sets.Crimson, Terraria.WorldBuilding.GenVars.dungeonX, Terraria.Main.dungeonX, Terraria.Localization.NetworkText.FromKey(), Terraria.WorldBuilding.WorldUtils.Gen(), Terraria.ID.TileID.Sets.Hallow, Terraria.Main.maxTilesX, Terraria.Lang.misc, Terraria.Main.netMode, Terraria.Main.NewText(), Terraria.GameContent.Achievements.AchievementsHelper.NotifyProgressionEvent(), System.DateTime.Now, Terraria.WorldBuilding.GenAction.Output(), Terraria.Main.rand, Terraria.Main.remixWorld, Terraria.Netplay.ResetSections(), Terraria.Main.tile, Terraria.Tile.type, Terraria.Main.worldSurface, Microsoft.Xna.Framework.Point.X, and Microsoft.Xna.Framework.Point.Y.