Terraria: Terraria.WorldGen.neonMossBiome
neonMossBiome()
static void Terraria.WorldGen.neonMossBiome (int i, int j, int maxY = 99999) inline static
Definition at line 5889 of file WorldGen.cs.
    {
        //IL_005c: Unknown result type (might be due to invalid IL or missing references)
        //IL_007f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0089: Unknown result type (might be due to invalid IL or missing references)
        //IL_008e: Unknown result type (might be due to invalid IL or missing references)
        //IL_010f: Unknown result type (might be due to invalid IL or missing references)
        //IL_011a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0125: Unknown result type (might be due to invalid IL or missing references)
        //IL_0130: Unknown result type (might be due to invalid IL or missing references)
        //IL_01c1: Unknown result type (might be due to invalid IL or missing references)
        //IL_018c: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ea: Unknown result type (might be due to invalid IL or missing references)
        //IL_0328: Unknown result type (might be due to invalid IL or missing references)
        //IL_0329: Unknown result type (might be due to invalid IL or missing references)
        //IL_032a: Unknown result type (might be due to invalid IL or missing references)
        //IL_032f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0384: Unknown result type (might be due to invalid IL or missing references)
        //IL_03a8: Unknown result type (might be due to invalid IL or missing references)
        //IL_024c: Unknown result type (might be due to invalid IL or missing references)
        //IL_025b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0267: Unknown result type (might be due to invalid IL or missing references)
        //IL_026c: Unknown result type (might be due to invalid IL or missing references)
        Vector2D val = default(Vector2D);
        val.X = i;
        val.Y = j;
        Vector2D val2 = default(Vector2D);
        val2.X = genRand.NextDouble() * 4.0 - 2.0;
        val2.Y = genRand.NextDouble() * 4.0 - 2.0;
        if (val2.X == 0.0)
        {
            val2.X = 1.0;
        }
        while (((Vector2D)(ref val2)).Length() < 4.0)
        {
            val2 *= 1.5;
        }
        double num = genRand.Next(60, 80);
        double num2 = genRand.Next(30, 40);
        double num3 = (double)Main.maxTilesX / 4200.0;
        if (getGoodWorldGen)
        {
            num3 *= 1.5;
        }
        num *= num3;
        num2 *= num3;
        while (num2 > 0.0)
        {
            num *= 0.98;
            num2 -= 1.0;
            int num4 = (int)(val.X - num);
            int num5 = (int)(val.X + num);
            int num6 = (int)(val.Y - num);
            int num7 = (int)(val.Y + num);
            if (num4 < 1)
            {
                num4 = 1;
            }
            if (num5 > Main.maxTilesX - 1)
            {
                num5 = Main.maxTilesX - 1;
            }
            if (num6 < 1)
            {
                num6 = 1;
            }
            if (num7 > Main.maxTilesY - 1)
            {
                num7 = Main.maxTilesY - 1;
            }
            if (Main.remixWorld)
            {
                if ((double)num6 < Main.worldSurface)
                {
                    num6 = (int)Main.worldSurface;
                    if (val2.Y < 5.0)
                    {
                        val2.Y = 5.0;
                    }
                }
            }
            else if ((double)num6 < Main.rockLayer)
            {
                num6 = (int)Main.rockLayer;
                if (val2.Y < 5.0)
                {
                    val2.Y = 5.0;
                }
            }
            if (num7 > maxY)
            {
                num7 = maxY;
                if (val2.Y > -5.0)
                {
                    val2.Y = -5.0;
                }
            }
            double num8 = num * (1.0 + genRand.NextDouble() * 0.4 - 0.2);
            for (int k = num4; k < num5; k++)
            {
                for (int l = num6; l < num7; l++)
                {
                    Vector2D val3 = new Vector2D(Math.Abs((double)k - val.X), Math.Abs((double)l - val.Y));
                    if (((Vector2D)(ref val3)).Length() < num8 * 0.8 && TileType(k, l) == 1 && (!Main.tile[k - 1, l].active() || !Main.tile[k + 1, l].active() || !Main.tile[k, l - 1].active() || !Main.tile[k, l + 1].active()))
                    {
                        SpreadGrass(k - 1, l, 1, neonMossType);
                    }
                }
            }
            val += val2;
            val2.X += genRand.NextDouble() * 4.0 - 2.0;
            val2.Y += genRand.NextDouble() * 4.0 - 2.0;
            val2.Y = Utils.Clamp(val2.Y, -10.0, 10.0);
            val2.X = Utils.Clamp(val2.X, -10.0, 10.0);
        }
    }
References Terraria.Tile.active(), Terraria.WorldGen.genRand, Terraria.WorldGen.getGoodWorldGen, Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.WorldGen.neonMossType, Terraria.Utilities.UnifiedRandom.Next(), Terraria.Utilities.UnifiedRandom.NextDouble(), Terraria.Main.remixWorld, Terraria.Main.rockLayer, Terraria.WorldGen.SpreadGrass(), Terraria.Main.tile, Terraria.WorldGen.TileType(), Terraria.Main.worldSurface, ReLogic.Utilities.Vector2D.X, and ReLogic.Utilities.Vector2D.Y.