Terraria: Terraria.WorldGen.LeftEdgeCanBeAttachedTo
LeftEdgeCanBeAttachedTo()
static bool Terraria.WorldGen.LeftEdgeCanBeAttachedTo (int i, int j) inline static
Definition at line 60862 of file WorldGen.cs.
    {
        try
        {
            Tile tile = Main.tile[i, j];
            if (tile == null)
            {
                return true;
            }
            if (tile.active() && Main.tileSolid[tile.type] && !Main.tileSolidTop[tile.type] && !tile.leftSlope() && !tile.halfBrick() && !tile.inActive() && !Main.tileNoAttach[tile.type])
            {
                return true;
            }
        }
        catch
        {
        }
        return false;
    }
References Terraria.Tile.active(), Terraria.Tile.halfBrick(), Terraria.Tile.inActive(), Terraria.Tile.leftSlope(), Terraria.Main.tile, Terraria.Main.tileNoAttach, Terraria.Main.tileSolid, Terraria.Main.tileSolidTop, and Terraria.Tile.type.