Terraria: Terraria.WorldGen.KillTile_DropItems
KillTile_DropItems()
static void Terraria.WorldGen.KillTile_DropItems (int x, int y, Tile tileCache, bool includeLargeObjectDrops = false) inline static private
    {
        KillTile_GetItemDrops(x, y, tileCache, out var dropItem, out var dropItemStack, out var secondaryItem, out var secondaryItemStack, includeLargeObjectDrops);
        if (!Main.getGoodWorld || tileCache.active())
        {
            if (dropItem > 0)
            {
                int num = Item.NewItem(GetItemSource_FromTileBreak(x, y), x * 16, y * 16, 16, 16, dropItem, dropItemStack, noBroadcast: false, -1);
                Main.item[num].TryCombiningIntoNearbyItems(num);
            }
            if (secondaryItem > 0)
            {
                int num2 = Item.NewItem(GetItemSource_FromTileBreak(x, y), x * 16, y * 16, 16, 16, secondaryItem, secondaryItemStack, noBroadcast: false, -1);
                Main.item[num2].TryCombiningIntoNearbyItems(num2);
            }
        }
    }
References Terraria.Tile.active(), Terraria.Main.getGoodWorld, Terraria.Main.item, Terraria.Item.NewItem(), and Terraria.Item.TryCombiningIntoNearbyItems().