Terraria: Terraria.WorldGen.RollRandomForestBGStyle
RollRandomForestBGStyle()
static int Terraria.WorldGen.RollRandomForestBGStyle (UnifiedRandom random) inline static private
Definition at line 4378 of file WorldGen.cs.
    {
        int num = random.Next(11);
        if ((num == 1 || num == 2) && random.Next(2) == 0)
        {
            num = random.Next(11);
        }
        if (num == 0)
        {
            num = random.Next(11);
        }
        if (num == 3 && random.Next(3) == 0)
        {
            num = 31;
        }
        if (num == 5 && random.Next(2) == 0)
        {
            num = 51;
        }
        if (num == 7 && random.Next(4) == 0)
        {
            num = random.Next(71, 74);
        }
        return num;
    }
References Terraria.Utilities.UnifiedRandom.Next().
Referenced by Terraria.WorldGen.RandomizeBackgroundBasedOnPlayer(), and Terraria.WorldGen.RandomizeBackgrounds().