Terraria: Terraria.WorldGen.CanKillTile
CanKillTile() [3/3]
static bool Terraria.WorldGen.CanKillTile (int i, int j, SpecialKillTileContext context) inline static
Definition at line 52892 of file WorldGen.cs.
    {
        if (context == SpecialKillTileContext.MowingTheGrass)
        {
            Tile tile = Main.tile[i, j];
            if (tile == null)
            {
                return false;
            }
            if (tile.type == 2 || tile.type == 109)
            {
                return true;
            }
        }
        return CanKillTile(i, j);
    }
References Terraria.Main.tile, and Terraria.Tile.type.
Referenced by Terraria.GameContent.MinecartDiggerHelper.CanGetPastTile(), Terraria.Wiring.DeActive(), Terraria.Mount.DrillSmartCursor_Blocks(), Terraria.Player.ItemCheck_UseMiningTools_ActuallyUseMiningTool(), Terraria.Player.MowGrassTile(), Terraria.Player.PickTile(), Terraria.GameContent.SmartCursorHelper.Step_ForceCursorToAnyMinableThing(), and Terraria.GameContent.SmartCursorHelper.Step_Pickaxe_MineSolids().