Terraria: Terraria.WorldGen.PlaceWire3
PlaceWire3()
static bool Terraria.WorldGen.PlaceWire3 (int i, int j) inline static
    {
        if (!Main.tile[i, j].wire3())
        {
            SoundEngine.PlaySound(0, i * 16, j * 16);
            Main.tile[i, j].wire3(wire3: true);
            return true;
        }
        return false;
    }
References Terraria.Audio.SoundEngine.PlaySound(), Terraria.Main.tile, and Terraria.Tile.wire3().
Referenced by Terraria.MessageBuffer.GetData(), Terraria.Player.ItemCheck_UseWiringTools(), and Terraria.Wiring.MassWireOperationStep().