Terraria: Terraria.WorldGen.StartImpendingDoom
StartImpendingDoom()
static void Terraria.WorldGen.StartImpendingDoom (int countdownTime) inline static
Definition at line 76804 of file WorldGen.cs.
    {
        NPC.LunarApocalypseIsUp = false;
        NPC.MaxMoonLordCountdown = countdownTime;
        NPC.MoonLordCountdown = NPC.MaxMoonLordCountdown;
        NetMessage.SendData(103);
        BroadcastText(NetworkText.FromKey(Lang.misc[52].Key), 50, 255, 130);
        if (Main.netMode != 1)
        {
            GetRidOfCultists();
        }
    }
References Terraria.Localization.NetworkText.FromKey(), Terraria.Localization.LocalizedText.Key, Terraria.NPC.MaxMoonLordCountdown, Terraria.Lang.misc, Terraria.Main.netMode, and Terraria.NetMessage.SendData().
Referenced by Terraria.MessageBuffer.GetData(), and Terraria.Player.ItemCheck_UseEventItems().