Terraria: Terraria.WorldGen.MarblePileWithStatues
MarblePileWithStatues()
static bool Terraria.WorldGen.MarblePileWithStatues (int X, int Y) inline static
    {
        //IL_0384: Unknown result type (might be due to invalid IL or missing references)
        //IL_0386: Unknown result type (might be due to invalid IL or missing references)
        //IL_0388: Unknown result type (might be due to invalid IL or missing references)
        //IL_038d: Unknown result type (might be due to invalid IL or missing references)
        //IL_03eb: Unknown result type (might be due to invalid IL or missing references)
        //IL_040a: Unknown result type (might be due to invalid IL or missing references)
        //IL_021b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0223: Unknown result type (might be due to invalid IL or missing references)
        //IL_0228: Unknown result type (might be due to invalid IL or missing references)
        //IL_022d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0469: Unknown result type (might be due to invalid IL or missing references)
        int num = Y;
        while (!SolidTile(X, num))
        {
            num++;
            if ((double)num > Main.worldSurface)
            {
                return false;
            }
        }
        if (Main.tile[X, num].type != 0 && Main.tile[X, num].type != 2)
        {
            return false;
        }
        if (Main.tile[X, num].wall > 0)
        {
            return false;
        }
        int num2 = 130;
        int num3 = 60;
        int num4 = (int)MathHelper.Clamp(X - num2, 30f, Main.maxTilesX - 30);
        int num5 = (int)MathHelper.Clamp(X + num2, 30f, Main.maxTilesX - 30);
        int num6 = (int)MathHelper.Clamp(num - num3, 30f, Main.maxTilesY - 30);
        int num7 = (int)MathHelper.Clamp(num + num3, 30f, Main.maxTilesY - 30);
        for (int i = num4; i <= num5; i++)
        {
            for (int j = num6; j <= num7; j++)
            {
                if (Main.tile[i, j].active() && (Main.tile[i, j].type == 367 || Main.tile[i, j].type == 191))
                {
                    return false;
                }
            }
        }
        num--;
        Vector2D val = default(Vector2D);
        ((Vector2D)(ref val))._002Ector((double)X, (double)num);
        Vector2D val2 = default(Vector2D);
        val2.X = genRand.NextDouble() * 0.6 - 0.3;
        val2.Y = genRand.NextDouble() * 0.5 + 0.5;
        double num8 = genRand.Next(2, 4);
        if (genRand.Next(10) == 0)
        {
            num8 += 1.0;
        }
        int num9 = genRand.Next(3, 6);
        while (num9 > 0)
        {
            num9--;
            for (int k = X - (int)num8 * 5; (double)k <= (double)X + num8 * 5.0; k++)
            {
                int num10 = num + (int)num8 * 3;
                while ((double)num10 > (double)num - num8 * 3.0)
                {
                    double num11 = num8 * (double)genRand.Next(70, 91) * 0.01 * 1.2;
                    Vector2D val3 = val - new Vector2D((double)k, (double)num10);
                    if (((Vector2D)(ref val3)).Length() > 30.0)
                    {
                        ((Vector2D)(ref val))._002Ector((double)X, (double)num);
                        val2.X = genRand.NextDouble() * 0.6 - 0.3;
                        val2.Y = genRand.NextDouble() * 0.5 + 0.5;
                    }
                    else
                    {
                        val3.X *= 0.25;
                        val3.Y *= 0.8;
                        if (((Vector2D)(ref val3)).Length() < num11 && Main.tile[k, num10].active())
{
                            Main.tile[k, num10].active(active: true);
                            Main.tile[k, num10].halfBrick(halfBrick: false);
                            Main.tile[k, num10].slope(0);
                            Main.tile[k, num10].type = 367;
                            if (!gen)
{
                                SquareTileFrame(k, num10);
                            }
                        }
                    }
                    num10--;
                }
            }
            val += val2;
            val2.X += genRand.NextDouble() * 0.2 - 0.1;
            val2.Y += (0.1 + genRand.NextDouble() * 0.1) * 0.8;
            Utils.Clamp(val2.X, -0.3, 0.3);
            Utils.Clamp(val2.Y, 0.5, 1.0);
        }
        int num12 = 0;
        for (int l = X - (int)num8 * 5; (double)l <= (double)X + num8 * 5.0; l++)
        {
            if (num12 >= 3)
            {
                break;
            }
            if (l % 2 != 1 && (num12 <= 0 || genRand.Next(5) == 0))
            {
                int num13 = (int)val.Y - 20;
                Tile tile = Main.tile[l, num13];
                while (tile != null && !tile.active())
                {
                    num13++;
                    tile = Main.tile[l, num13];
                }
                if (tile != null && tile.type == 367 && !Main.tile[l, num13 - 1].active() && Statue(l, num13 - 1, 26))
                {
                    num12++;
                }
            }
        }
        return true;
    }
References Terraria.Tile.active(), Terraria.WorldGen.gen, Terraria.WorldGen.genRand, Terraria.Tile.halfBrick(), Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.Utilities.UnifiedRandom.Next(), Terraria.Utilities.UnifiedRandom.NextDouble(), Terraria.Tile.slope(), Terraria.Enums.SolidTile, Terraria.WorldGen.SquareTileFrame(), Terraria.WorldGen.Statue(), Terraria.Main.tile, Terraria.Tile.type, Terraria.Tile.wall, Terraria.Main.worldSurface, ReLogic.Utilities.Vector2D.X, and ReLogic.Utilities.Vector2D.Y.