Terraria: Terraria.WorldGen.worldGenCallback
worldGenCallback()
static void Terraria.WorldGen.worldGenCallback (object threadContext) inline static
Definition at line 3034 of file WorldGen.cs.
    {
        SoundEngine.PlaySound(10);
        clearWorld();
        GenerateWorld(Main.ActiveWorldFileData.Seed, threadContext as GenerationProgress);
        WorldFile.SaveWorld(Main.ActiveWorldFileData.IsCloudSave, resetTime: true);
        if (Main.menuMode == 10 || Main.menuMode == 888)
        {
            Main.menuMode = 6;
        }
        SoundEngine.PlaySound(10);
        generatingWorld = false;
    }
References Terraria.Main.ActiveWorldFileData, Terraria.WorldGen.clearWorld(), Terraria.WorldGen.GenerateWorld(), Terraria.WorldGen.generatingWorld, Terraria.Main.menuMode, Terraria.Audio.SoundEngine.PlaySound(), and Terraria.IO.WorldFile.SaveWorld().
Referenced by Terraria.WorldGen.CreateNewWorld().