Terraria: Terraria.WorldGen.ReplaceTile
ReplaceTile()
static bool Terraria.WorldGen.ReplaceTile (int x, int y, ushort targetType, int targetStyle) inline static
Definition at line 53226 of file WorldGen.cs.
    {
        Tile tileSafely = Framing.GetTileSafely(x, y);
        if (!WouldTileReplacementWork(targetType, x, y))
        {
            return false;
        }
        if (!IsTileReplacable(x, y))
        {
            return false;
        }
        MoveReplaceTileAnchor(ref x, ref y, targetType, tileSafely);
        int num = KillTile_GetTileDustAmount(fail: false, tileSafely);
        for (int i = 0; i < num; i++)
        {
            KillTile_MakeTileDust(x, y, tileSafely);
        }
        KillTile_PlaySounds(x, y, fail: false, tileSafely);
        KillTile_DropItems(x, y, tileSafely, includeLargeObjectDrops: true);
        AttemptFossilShattering(x, y, tileSafely, fail: false);
        ReplaceTIle_DoActualReplacement(targetType, targetStyle, x, y, tileSafely);
        return true;
    }
References Terraria.Framing.GetTileSafely().
Referenced by Terraria.MessageBuffer.GetData(), and Terraria.Player.PlaceThing_TryReplacingTiles().