Terraria: Terraria.WorldGen.makeTemple
makeTemple()
static void Terraria.WorldGen.makeTemple (int x, int y) inline static
    {
        //IL_0940: Unknown result type (might be due to invalid IL or missing references)
        //IL_0946: Unknown result type (might be due to invalid IL or missing references)
        //IL_094b: Unknown result type (might be due to invalid IL or missing references)
        //IL_094d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0959: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c37: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c3d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c42: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c44: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c50: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b55: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b5b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b60: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b62: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b6e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e9b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ea8: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f6e: Unknown result type (might be due to invalid IL or missing references)
        Rectangle[] array = new Rectangle[100];
        double num = (double)Main.maxTilesX / 4200.0;
        int num2 = genRand.Next((int)(num * 10.0), (int)(num * 16.0));
        if (drunkWorldGen)
        {
            num2 *= 3;
        }
        else if (getGoodWorldGen)
        {
            num2 *= 3;
        }
        else if (remixWorldGen)
        {
            num2 *= 2;
        }
        int num3 = 1;
        if (genRand.Next(2) == 0)
        {
            num3 = -1;
        }
        int num4 = num3;
        int num5 = x;
        int num6 = y;
        int num7 = x;
        int num8 = y;
        int num9 = genRand.Next(1, 3);
        int num10 = 0;
        for (int i = 0; i < num2; i++)
        {
            num10++;
            int num11 = num3;
            int num12 = num7;
            int num13 = num8;
            bool flag = true;
            int num14 = 0;
            int num15 = 0;
            int num16 = -10;
            Rectangle rectangle = new Rectangle(num12 - num14 / 2, num13 - num15 / 2, num14, num15);
            while (flag)
            {
                num12 = num7;
                num13 = num8;
                num14 = genRand.Next(25, 50);
                num15 = genRand.Next(20, 35);
                if (num15 > num14)
                {
                    num15 = num14;
                }
                if (i == num2 - 1)
                {
                    num14 = genRand.Next(55, 65);
                    num15 = genRand.Next(45, 50);
                    if (num15 > num14)
                    {
                        num15 = num14;
                    }
                    num14 = (int)((double)num14 * 1.6);
                    num15 = (int)((double)num15 * 1.35);
                    num13 += genRand.Next(5, 10);
                }
                if (num10 > num9)
                {
                    num13 += genRand.Next(num15 + 1, num15 + 3) + num16;
                    num12 += genRand.Next(-5, 6);
                    num11 = num3 * -1;
                }
                else
                {
                    num12 += (genRand.Next(num14 + 1, num14 + 3) + num16) * num11;
                    num13 += genRand.Next(-5, 6);
                }
                flag = false;
                rectangle = new Rectangle(num12 - num14 / 2, num13 - num15 / 2, num14, num15);
                for (int j = 0; j < i; j++)
                {
                    if (rectangle.Intersects(array[j]))
                    {
                        flag = true;
                    }
                    if (genRand.Next(100) == 0)
                    {
                        num16++;
                    }
                }
            }
            if (num10 > num9)
            {
                num9++;
                num10 = 1;
            }
            array[i] = rectangle;
            num3 = num11;
            num7 = num12;
            num8 = num13;
        }
        for (int k = 0; k < num2; k++)
        {
            for (int l = 0; l < 2; l++)
            {
                for (int m = 0; m < num2; m++)
                {
                    for (int n = 0; n < 2; n++)
                    {
                        int num17 = array[k].X;
                        if (l == 1)
{
                            num17 += array[k].Width - 1;
                        }
                        int num18 = array[k].Y;
                        int num19 = num18 + array[k].Height;
                        int num20 = array[m].X;
                        if (n == 1)
{
                            num20 += array[m].Width - 1;
                        }
                        int y2 = array[m].Y;
                        int num21 = y2 + array[m].Height;
                        while (num17 != num20 || num18 != y2 || num19 != num21)
{
                            if (num17 < num20)
{
                                num17++;
                            }
                            if (num17 > num20)
{
                                num17--;
                            }
                            if (num18 < y2)
{
                                num18++;
                            }
                            if (num18 > y2)
{
                                num18--;
                            }
                            if (num19 < num21)
{
                                num19++;
                            }
                            if (num19 > num21)
{
                                num19--;
                            }
                            int num22 = num17;
                            for (int num23 = num18; num23 < num19; num23++)
{
                                Main.tile[num22, num23].active(active: true);
                                Main.tile[num22, num23].type = 226;
                                Main.tile[num22, num23].liquid = 0;
                                Main.tile[num22, num23].slope(0);
                                Main.tile[num22, num23].halfBrick(halfBrick: false);
                            }
                        }
                    }
                }
            }
        }
        for (int num24 = 0; num24 < num2; num24++)
        {
            if (false)
            {
                continue;
            }
            for (int num25 = array[num24].X; num25 < array[num24].X + array[num24].Width; num25++)
            {
                for (int num26 = array[num24].Y; num26 < array[num24].Y + array[num24].Height; num26++)
                {
                    Main.tile[num25, num26].active(active: true);
                    Main.tile[num25, num26].type = 226;
                    Main.tile[num25, num26].liquid = 0;
                    Main.tile[num25, num26].slope(0);
                    Main.tile[num25, num26].halfBrick(halfBrick: false);
                }
            }
            int x2 = array[num24].X;
            int num27 = x2 + array[num24].Width;
            int y3 = array[num24].Y;
            int num28 = y3 + array[num24].Height;
            x2 += genRand.Next(3, 8);
            num27 -= genRand.Next(3, 8);
            y3 += genRand.Next(3, 8);
            num28 -= genRand.Next(3, 8);
            int num29 = x2;
            int num30 = num27;
            int num31 = y3;
            int num32 = num28;
            int num33 = (x2 + num27) / 2;
            int num34 = (y3 + num28) / 2;
            for (int num35 = x2; num35 < num27; num35++)
            {
                for (int num36 = y3; num36 < num28; num36++)
                {
                    if (genRand.Next(20) == 0)
                    {
                        num31 += genRand.Next(-1, 2);
                    }
                    if (genRand.Next(20) == 0)
                    {
                        num32 += genRand.Next(-1, 2);
                    }
                    if (genRand.Next(20) == 0)
                    {
                        num29 += genRand.Next(-1, 2);
                    }
                    if (genRand.Next(20) == 0)
                    {
                        num30 += genRand.Next(-1, 2);
                    }
                    if (num29 < x2)
                    {
                        num29 = x2;
                    }
                    if (num30 > num27)
                    {
                        num30 = num27;
                    }
                    if (num31 < y3)
                    {
                        num31 = y3;
                    }
                    if (num32 > num28)
                    {
                        num32 = num28;
                    }
                    if (num29 > num33)
                    {
                        num29 = num33;
                    }
                    if (num30 < num33)
                    {
                        num30 = num33;
                    }
                    if (num31 > num34)
                    {
                        num31 = num34;
                    }
                    if (num32 < num34)
                    {
                        num32 = num34;
                    }
                    if (num35 >= num29 && num35 < num30 && num36 >= num31 && num36 <= num32)
                    {
                        Main.tile[num35, num36].active(active: false);
                        Main.tile[num35, num36].wall = 87;
                    }
                }
            }
            for (int num37 = num28; num37 > y3; num37--)
            {
                for (int num38 = num27; num38 > x2; num38--)
                {
                    if (genRand.Next(20) == 0)
                    {
                        num31 += genRand.Next(-1, 2);
                    }
                    if (genRand.Next(20) == 0)
                    {
                        num32 += genRand.Next(-1, 2);
                    }
                    if (genRand.Next(20) == 0)
                    {
                        num29 += genRand.Next(-1, 2);
                    }
                    if (genRand.Next(20) == 0)
                    {
                        num30 += genRand.Next(-1, 2);
                    }
                    if (num29 < x2)
                    {
                        num29 = x2;
                    }
                    if (num30 > num27)
                    {
                        num30 = num27;
                    }
                    if (num31 < y3)
                    {
                        num31 = y3;
                    }
                    if (num32 > num28)
                    {
                        num32 = num28;
                    }
                    if (num29 > num33)
                    {
                        num29 = num33;
                    }
                    if (num30 < num33)
                    {
                        num30 = num33;
                    }
                    if (num31 > num34)
                    {
                        num31 = num34;
                    }
                    if (num32 < num34)
                    {
                        num32 = num34;
                    }
                    if (num38 >= num29 && num38 < num30 && num37 >= num31 && num37 <= num32)
                    {
                        Main.tile[num38, num37].active(active: false);
                        Main.tile[num38, num37].wall = 87;
                    }
                }
            }
        }
        Vector2D val = default(Vector2D);
        ((Vector2D)(ref val))._002Ector((double)num5, (double)num6);
        for (int num39 = 0; num39 < num2; num39++)
        {
            Rectangle rectangle2 = array[num39];
            rectangle2.X += 8;
            rectangle2.Y += 8;
            rectangle2.Width -= 16;
            rectangle2.Height -= 16;
            bool flag2 = true;
            while (flag2)
            {
                int num40 = genRand.Next(rectangle2.X, rectangle2.X + rectangle2.Width);
                int num41 = genRand.Next(rectangle2.Y, rectangle2.Y + rectangle2.Height);
                if (num39 == num2 - 1)
                {
                    num40 = rectangle2.X + rectangle2.Width / 2 + genRand.Next(-10, 10);
                    num41 = rectangle2.Y + rectangle2.Height / 2 + genRand.Next(-10, 10);
                }
                val = templePather(val, num40, num41);
                if (val.X == (double)num40 && val.Y == (double)num41)
                {
                    flag2 = false;
                }
            }
            if (num39 >= num2 - 1)
            {
                continue;
            }
            if (genRand.Next(3) != 0)
            {
                int num42 = num39 + 1;
                if (array[num42].Y >= array[num39].Y + array[num39].Height)
                {
                    rectangle2.X = array[num42].X;
                    if (num39 == 0)
                    {
                        if (num3 > 0)
{
                            rectangle2.X += (int)((double)array[num42].Width * 0.8);
                        }
                        else
{
                            rectangle2.X += (int)((double)array[num42].Width * 0.2);
                        }
                    }
                    else if (array[num42].X < array[num39].X)
                    {
                        rectangle2.X += (int)((double)array[num42].Width * 0.2);
                    }
                    else
                    {
                        rectangle2.X += (int)((double)array[num42].Width * 0.8);
                    }
                    rectangle2.Y = array[num42].Y;
                }
                else
                {
                    rectangle2.X = (array[num39].X + array[num39].Width / 2 + array[num42].X + array[num42].Width / 2) / 2;
                    rectangle2.Y = (int)((double)array[num42].Y + (double)array[num42].Height * 0.8);
                }
                int x3 = rectangle2.X;
                int y4 = rectangle2.Y;
                flag2 = true;
                while (flag2)
                {
                    int num43 = genRand.Next(x3 - 6, x3 + 7);
                    int num44 = genRand.Next(y4 - 6, y4 + 7);
                    val = templePather(val, num43, num44);
                    if (val.X == (double)num43 && val.Y == (double)num44)
                    {
                        flag2 = false;
                    }
                }
                continue;
            }
            int num45 = num39 + 1;
            int num46 = (array[num39].X + array[num39].Width / 2 + array[num45].X + array[num45].Width / 2) / 2;
            int num47 = (array[num39].Y + array[num39].Height / 2 + array[num45].Y + array[num45].Height / 2) / 2;
            flag2 = true;
            while (flag2)
            {
                int num48 = genRand.Next(num46 - 6, num46 + 7);
                int num49 = genRand.Next(num47 - 6, num47 + 7);
                val = templePather(val, num48, num49);
                if (val.X == (double)num48 && val.Y == (double)num49)
                {
                    flag2 = false;
                }
            }
        }
        int num50 = Main.maxTilesX - 20;
        int num51 = 20;
        int num52 = Main.maxTilesY - 20;
        int num53 = 20;
        for (int num54 = 0; num54 < num2; num54++)
        {
            if (array[num54].X < num50)
            {
                num50 = array[num54].X;
            }
            if (array[num54].X + array[num54].Width > num51)
            {
                num51 = array[num54].X + array[num54].Width;
            }
            if (array[num54].Y < num52)
            {
                num52 = array[num54].Y;
            }
            if (array[num54].Y + array[num54].Height > num53)
            {
                num53 = array[num54].Y + array[num54].Height;
            }
        }
        num50 -= 10;
        num51 += 10;
        num52 -= 10;
        num53 += 10;
        for (int num55 = num50; num55 < num51; num55++)
        {
            for (int num56 = num52; num56 < num53; num56++)
            {
                outerTempled(num55, num56);
            }
        }
        for (int num57 = num51; num57 >= num50; num57--)
        {
            for (int num58 = num52; num58 < num53 / 2; num58++)
            {
                outerTempled(num57, num58);
            }
        }
        for (int num59 = num52; num59 < num53; num59++)
        {
            for (int num60 = num50; num60 < num51; num60++)
            {
                outerTempled(num60, num59);
            }
        }
        for (int num61 = num53; num61 >= num52; num61--)
        {
            for (int num62 = num50; num62 < num51; num62++)
            {
                outerTempled(num62, num61);
            }
        }
        int num63 = num6;
        num3 = -num4;
        Vector2D val2 = default(Vector2D);
        ((Vector2D)(ref val2))._002Ector((double)num5, (double)num6);
        int num64 = genRand.Next(2, 5);
        bool flag3 = true;
        int num65 = 0;
        int num66 = genRand.Next(9, 14);
        while (flag3)
        {
            num65++;
            if (num65 >= num66)
            {
                num65 = 0;
                val2.Y -= 1.0;
            }
            val2.X += num3;
            int num67 = (int)val2.X;
            flag3 = false;
            for (int num68 = (int)val2.Y - num64; (double)num68 < val2.Y + (double)num64; num68++)
            {
                if (Main.tile[num67, num68].wall == 87 || (Main.tile[num67, num68].active() && Main.tile[num67, num68].type == 226))
                {
                    flag3 = true;
                }
                if (Main.tile[num67, num68].active() && Main.tile[num67, num68].type == 226)
                {
                    if (num68 > num63)
                    {
                        num63 = num68;
                    }
                    Main.tile[num67, num68].active(active: false);
                    Main.tile[num67, num68].wall = 87;
                }
            }
        }
        num63 += 2;
        int num69 = num5;
        int num70 = num6;
        while (!Main.tile[num69, num70].active())
        {
            num70++;
            if (num70 >= num63)
            {
                num70 = num63;
                Main.tile[num69, num70].ClearEverything();
                Main.tile[num69, num70].active(active: true);
                Main.tile[num69, num70].type = 226;
                break;
            }
        }
        num70 -= 4;
        int num71 = num70;
        while ((Main.tile[num69, num71].active() && Main.tile[num69, num71].type == 226) || Main.tile[num69, num71].wall == 87)
        {
            num71--;
        }
        num71 += 2;
        for (int num72 = num69 - 1; num72 <= num69 + 1; num72++)
        {
            for (int num73 = num71; num73 <= num70; num73++)
            {
                Main.tile[num72, num73].active(active: true);
                Main.tile[num72, num73].type = 226;
                Main.tile[num72, num73].liquid = 0;
                Main.tile[num72, num73].slope(0);
                Main.tile[num72, num73].halfBrick(halfBrick: false);
            }
        }
        for (int num74 = num69 - 4; num74 <= num69 + 4; num74++)
        {
            for (int num75 = num70 - 1; num75 < num70 + 3; num75++)
            {
                Main.tile[num74, num75].active(active: false);
                Main.tile[num74, num75].wall = 87;
            }
        }
        for (int num76 = num69 - 1; num76 <= num69 + 1; num76++)
        {
            for (int num77 = num70 - 5; num77 <= num70 + 8; num77++)
            {
                Main.tile[num76, num77].active(active: true);
                Main.tile[num76, num77].type = 226;
                Main.tile[num76, num77].liquid = 0;
                Main.tile[num76, num77].slope(0);
                Main.tile[num76, num77].halfBrick(halfBrick: false);
            }
        }
        for (int num78 = num69 - 3; num78 <= num69 + 3; num78++)
        {
            for (int num79 = num70 - 2; num79 < num70 + 3; num79++)
            {
                if (num79 >= num70 || num78 < num5 - 1 || num78 > num5 + 1)
                {
                    Main.tile[num78, num79].active(active: false);
                    Main.tile[num78, num79].wall = 87;
                }
            }
        }
        PlaceTile(num69, num70, 10, mute: true, forced: false, -1, 11);
        for (int num80 = num50; num80 < num51; num80++)
        {
            for (int num81 = num52; num81 < num53; num81++)
            {
                templeCleaner(num80, num81);
            }
        }
        for (int num82 = num53; num82 >= num52; num82--)
        {
            for (int num83 = num51; num83 >= num50; num83--)
            {
                templeCleaner(num83, num82);
            }
        }
        for (int num84 = num50; num84 < num51; num84++)
        {
            for (int num85 = num52; num85 < num53; num85++)
            {
                bool flag4 = true;
                for (int num86 = num84 - 1; num86 <= num84 + 1; num86++)
                {
                    for (int num87 = num85 - 1; num87 <= num85 + 1; num87++)
                    {
                        if ((!Main.tile[num86, num87].active() || Main.tile[num86, num87].type != 226) && Main.tile[num86, num87].wall != 87)
{
                            flag4 = false;
                            break;
                        }
                    }
                }
                if (flag4)
                {
                    Main.tile[num84, num85].wall = 87;
                }
            }
        }
        int num88 = 0;
        Rectangle rectangle3 = array[num2 - 1];
        int num89 = rectangle3.Width / 2;
        int num90 = rectangle3.Height / 2;
        while (true)
        {
            num88++;
            int num91 = rectangle3.X + num89 + 15 - genRand.Next(30);
            int num92 = rectangle3.Y + num90 + 15 - genRand.Next(30);
            PlaceTile(num91, num92, 237);
            if (Main.tile[num91, num92].type == 237)
            {
                GenVars.lAltarX = num91 - Main.tile[num91, num92].frameX / 18;
                GenVars.lAltarY = num92 - Main.tile[num91, num92].frameY / 18;
                break;
            }
            if (num88 < 1000)
            {
                continue;
            }
            num91 = rectangle3.X + num89;
            num92 = rectangle3.Y + num90;
            num91 += genRand.Next(-10, 11);
            for (num92 += genRand.Next(-10, 11); !Main.tile[num91, num92].active(); num92++)
            {
            }
            Main.tile[num91 - 1, num92].active(active: true);
            Main.tile[num91 - 1, num92].slope(0);
            Main.tile[num91 - 1, num92].halfBrick(halfBrick: false);
            Main.tile[num91 - 1, num92].type = 226;
            Main.tile[num91, num92].active(active: true);
            Main.tile[num91, num92].slope(0);
            Main.tile[num91, num92].halfBrick(halfBrick: false);
            Main.tile[num91, num92].type = 226;
            Main.tile[num91 + 1, num92].active(active: true);
            Main.tile[num91 + 1, num92].slope(0);
            Main.tile[num91 + 1, num92].halfBrick(halfBrick: false);
            Main.tile[num91 + 1, num92].type = 226;
            num92 -= 2;
            num91--;
            for (int num93 = -1; num93 <= 3; num93++)
            {
                for (int num94 = -1; num94 <= 1; num94++)
                {
                    x = num91 + num93;
                    y = num92 + num94;
                    Main.tile[x, y].active(active: false);
                }
            }
            GenVars.lAltarX = num91;
            GenVars.lAltarY = num92;
            for (int num95 = 0; num95 <= 2; num95++)
            {
                for (int num96 = 0; num96 <= 1; num96++)
                {
                    x = num91 + num95;
                    y = num92 + num96;
                    Main.tile[x, y].active(active: true);
                    Main.tile[x, y].type = 237;
                    Main.tile[x, y].frameX = (short)(num95 * 18);
                    Main.tile[x, y].frameY = (short)(num96 * 18);
                }
            }
            for (int num97 = 0; num97 <= 2; num97++)
            {
                for (int num98 = 0; num98 <= 1; num98++)
                {
                    x = num91 + num97;
                    y = num92 + num98;
                    SquareTileFrame(x, y);
                }
            }
            break;
        }
        double num99 = (double)num2 * 1.1;
        num99 *= 1.0 + (double)genRand.Next(-25, 26) * 0.01;
        if (drunkWorldGen)
        {
            num99 *= 1.5;
        }
        int num100 = 0;
        while (num99 > 0.0)
        {
            num100++;
            int num101 = genRand.Next(num2);
            int num102 = genRand.Next(array[num101].X, array[num101].X + array[num101].Width);
            int num103 = genRand.Next(array[num101].Y, array[num101].Y + array[num101].Height);
            if (Main.tile[num102, num103].wall == 87 && !Main.tile[num102, num103].active())
            {
                bool flag5 = false;
                if (genRand.Next(2) == 0)
                {
                    int num104 = 1;
                    if (genRand.Next(2) == 0)
                    {
                        num104 = -1;
                    }
                    for (; !Main.tile[num102, num103].active(); num103 += num104)
                    {
                    }
                    num103 -= num104;
                    int num105 = genRand.Next(2);
                    int num106 = genRand.Next(3, 10);
                    bool flag6 = true;
                    for (int num107 = num102 - num106; num107 < num102 + num106; num107++)
                    {
                        for (int num108 = num103 - num106; num108 < num103 + num106; num108++)
{
                            if (Main.tile[num107, num108].active() && (Main.tile[num107, num108].type == 10 || Main.tile[num107, num108].type == 237))
{
                                flag6 = false;
                                break;
                            }
                        }
                    }
                    if (flag6)
                    {
                        for (int num109 = num102 - num106; num109 < num102 + num106; num109++)
{
                            for (int num110 = num103 - num106; num110 < num103 + num106; num110++)
{
                                if (!SolidTile(num109, num110) || Main.tile[num109, num110].type == 232 || SolidTile(num109, num110 - num104))
{
                                    continue;
                                }
                                Main.tile[num109, num110].type = 232;
                                flag5 = true;
                                if (num105 == 0)
{
                                    Main.tile[num109, num110 - 1].type = 232;
                                    Main.tile[num109, num110 - 1].active(active: true);
                                    if (drunkWorldGen)
{
                                        Main.tile[num109, num110 - 2].type = 232;
                                        Main.tile[num109, num110 - 2].active(active: true);
                                    }
                                }
                                else
{
                                    Main.tile[num109, num110 + 1].type = 232;
                                    Main.tile[num109, num110 + 1].active(active: true);
                                    if (drunkWorldGen)
{
                                        Main.tile[num109, num110 + 2].type = 232;
                                        Main.tile[num109, num110 + 2].active(active: true);
                                    }
                                }
                                num105++;
                                if (num105 > 1)
{
                                    num105 = 0;
                                }
                            }
                        }
                    }
                    if (flag5)
                    {
                        num100 = 0;
                        num99 -= 1.0;
                    }
                }
                else
                {
                    int num111 = 1;
                    if (genRand.Next(2) == 0)
                    {
                        num111 = -1;
                    }
                    for (; !Main.tile[num102, num103].active(); num102 += num111)
                    {
                    }
                    num102 -= num111;
                    int num112 = genRand.Next(2);
                    int num113 = genRand.Next(3, 10);
                    bool flag7 = true;
                    for (int num114 = num102 - num113; num114 < num102 + num113; num114++)
                    {
                        for (int num115 = num103 - num113; num115 < num103 + num113; num115++)
{
                            if (Main.tile[num114, num115].active() && Main.tile[num114, num115].type == 10)
{
                                flag7 = false;
                                break;
                            }
                        }
                    }
                    if (flag7)
                    {
                        for (int num116 = num102 - num113; num116 < num102 + num113; num116++)
{
                            for (int num117 = num103 - num113; num117 < num103 + num113; num117++)
{
                                if (!SolidTile(num116, num117) || Main.tile[num116, num117].type == 232 || SolidTile(num116 - num111, num117))
{
                                    continue;
                                }
                                Main.tile[num116, num117].type = 232;
                                flag5 = true;
                                if (num112 == 0)
{
                                    Main.tile[num116 - 1, num117].type = 232;
                                    Main.tile[num116 - 1, num117].active(active: true);
                                    if (drunkWorldGen)
{
                                        Main.tile[num116 - 2, num117].type = 232;
                                        Main.tile[num116 - 2, num117].active(active: true);
                                    }
                                }
                                else
{
                                    Main.tile[num116 + 1, num117].type = 232;
                                    Main.tile[num116 + 1, num117].active(active: true);
                                    if (drunkWorldGen)
{
                                        Main.tile[num116 - 2, num117].type = 232;
                                        Main.tile[num116 - 2, num117].active(active: true);
                                    }
                                }
                                num112++;
                                if (num112 > 1)
{
                                    num112 = 0;
                                }
                            }
                        }
                    }
                    if (flag5)
                    {
                        num100 = 0;
                        num99 -= 1.0;
                    }
                }
            }
            if (num100 > 1000)
            {
                num100 = 0;
                num99 -= 1.0;
            }
        }
        GenVars.tLeft = num50;
        GenVars.tRight = num51;
        GenVars.tTop = num52;
        GenVars.tBottom = num53;
        GenVars.tRooms = num2;
    }
References Terraria.Tile.active(), Terraria.Tile.ClearEverything(), Terraria.Tile.frameX, Terraria.Tile.frameY, Terraria.Tile.halfBrick(), Terraria.Tile.liquid, Terraria.Main.maxTilesX, Terraria.Tile.slope(), Terraria.Enums.SolidTile, Terraria.Main.tile, Terraria.Tile.type, Terraria.Tile.wall, ReLogic.Utilities.Vector2D.X, and ReLogic.Utilities.Vector2D.Y.