Terraria: Terraria.WorldGen.BiomeTileCheck
BiomeTileCheck()
static bool Terraria.WorldGen.BiomeTileCheck (int x, int y) inline static
Definition at line 7113 of file WorldGen.cs.
    {
        int num = 50;
        for (int i = x - num; i <= x + num; i++)
        {
            for (int j = y - num; j <= y + num; j++)
            {
                if (!InWorld(i, j))
                {
                    continue;
                }
                if (Main.tile[i, j].active())
                {
                    int type = Main.tile[i, j].type;
                    if (type == 368 || type == 367 || type == 147 || type == 161 || type == 162 || type == 70 || type == 72 || type == 396 || type == 397)
                    {
                        return true;
                    }
                }
                int wall = Main.tile[i, j].wall;
                if (wall == 187 || wall == 216)
                {
                    return true;
                }
            }
        }
        return false;
    }
References Terraria.WorldGen.InWorld(), Terraria.Main.tile, and System.type.
Referenced by Terraria.GameContent.Biomes.GraniteBiome.CanPlace(), and Terraria.GameContent.Biomes.MarbleBiome.Place().