Terraria: Terraria.WorldGen.RandomizeWeather
RandomizeWeather()
static void Terraria.WorldGen.RandomizeWeather () inline static
Definition at line 4140 of file WorldGen.cs.
    {
        Main.numClouds = genRand.Next(10, 200);
        Main.windSpeedCurrent = 0f;
        while (Main.windSpeedCurrent == 0f)
        {
            Main.windSpeedCurrent = (float)genRand.Next(-400, 401) * 0.001f;
            Main.windSpeedTarget = Main.windSpeedCurrent;
        }
        Cloud.resetClouds();
    }
References Terraria.WorldGen.genRand, Terraria.Utilities.UnifiedRandom.Next(), Terraria.Cloud.resetClouds(), and Terraria.Main.windSpeedCurrent.
Referenced by Terraria.WorldGen.GenerateWorld(), and Terraria.IO.WorldFile.LoadWorld_Version1_Old_BeforeRelease88().