Terraria: Terraria.WorldGen.Mountinater
Mountinater()
static void Terraria.WorldGen.Mountinater (int i, int j) inline static
Definition at line 69597 of file WorldGen.cs.
    {
        //IL_00cc: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e1: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f7: Unknown result type (might be due to invalid IL or missing references)
        //IL_010c: Unknown result type (might be due to invalid IL or missing references)
        //IL_020f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0210: Unknown result type (might be due to invalid IL or missing references)
        //IL_0211: Unknown result type (might be due to invalid IL or missing references)
        //IL_0216: Unknown result type (might be due to invalid IL or missing references)
        //IL_025f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0280: Unknown result type (might be due to invalid IL or missing references)
        //IL_017c: Unknown result type (might be due to invalid IL or missing references)
        //IL_018b: Unknown result type (might be due to invalid IL or missing references)
        //IL_02a1: Unknown result type (might be due to invalid IL or missing references)
        //IL_02c2: Unknown result type (might be due to invalid IL or missing references)
        double num = genRand.Next(80, 120);
        double num2 = num;
        double num3 = genRand.Next(40, 55);
        if (remixWorldGen)
        {
            num2 *= 1.5;
            num3 *= 1.5;
        }
        Vector2D val = default(Vector2D);
        val.X = i;
        val.Y = (double)j + num3 / 2.0;
        Vector2D val2 = default(Vector2D);
        val2.X = (double)genRand.Next(-10, 11) * 0.1;
        val2.Y = (double)genRand.Next(-20, -10) * 0.1;
        while (num > 0.0 && num3 > 0.0)
        {
            num -= (double)genRand.Next(4);
            num3 -= 1.0;
            int num4 = (int)(val.X - num * 0.5);
            int num5 = (int)(val.X + num * 0.5);
            int num6 = (int)(val.Y - num * 0.5);
            int num7 = (int)(val.Y + num * 0.5);
            if (num4 < 0)
            {
                num4 = 0;
            }
            if (num5 > Main.maxTilesX)
            {
                num5 = Main.maxTilesX;
            }
            if (num6 < 0)
            {
                num6 = 0;
            }
            if (num7 > Main.maxTilesY)
            {
                num7 = Main.maxTilesY;
            }
            num2 = num * (double)genRand.Next(80, 120) * 0.01;
            for (int k = num4; k < num5; k++)
            {
                for (int l = num6; l < num7; l++)
                {
                    double num8 = Math.Abs((double)k - val.X);
                    double num9 = Math.Abs((double)l - val.Y);
                    if (Math.Sqrt(num8 * num8 + num9 * num9) < num2 * 0.4 && !Main.tile[k, l].active())
                    {
                        Main.tile[k, l].active(active: true);
                        Main.tile[k, l].type = 0;
                    }
                }
            }
            val += val2;
            val2.X += (double)genRand.Next(-10, 11) * 0.05;
            val2.Y += (double)genRand.Next(-10, 11) * 0.05;
            if (val2.X > 0.5)
            {
                val2.X = 0.5;
            }
            if (val2.X < -0.5)
            {
                val2.X = -0.5;
            }
            if (val2.Y > -0.5)
            {
                val2.Y = -0.5;
            }
            if (val2.Y < -1.5)
            {
                val2.Y = -1.5;
            }
        }
    }
References System.Math.Abs(), Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, System.Math.Sqrt(), Terraria.Main.tile, ReLogic.Utilities.Vector2D.X, and ReLogic.Utilities.Vector2D.Y.
Referenced by Terraria.WorldGen.GenerateWorld().