Terraria: Terraria.WorldGen.ScoreRoom
ScoreRoom()
static void Terraria.WorldGen.ScoreRoom (int ignoreNPC = -1, int npcTypeAskingToScoreRoom = -1) inline static
Definition at line 2380 of file WorldGen.cs.
    {
        roomOccupied = false;
        roomEvil = false;
        sharedRoomX = -1;
        if (ScoreRoom_IsThisRoomOccupiedBySomeone(ignoreNPC, npcTypeAskingToScoreRoom))
        {
            roomOccupied = true;
            hiScore = -1;
            return;
        }
        hiScore = 0;
        int num = 0;
        int num2 = 50;
        Housing_GetTestedRoomBounds(out var startX, out var endX, out var startY, out var endY);
        int[] tileTypeCounts = new int[TileID.Count];
        CountTileTypesInArea(tileTypeCounts, startX + 1, endX - 1, startY + 2, endY + 1);
        int num3 = -GetTileTypeCountByCategory(tileTypeCounts, TileScanGroup.TotalGoodEvil);
        if (num3 < 50)
        {
            num3 = 0;
        }
        num2 -= num3;
        if (num3 > 0)
        {
            roomEvil = true;
        }
        if (num2 <= -250)
        {
            hiScore = num2;
            return;
        }
        startX = roomX1;
        endX = roomX2;
        startY = roomY1;
        endY = roomY2;
        for (int i = startX + 1; i < endX; i++)
        {
            for (int j = startY + 2; j < endY + 2; j++)
            {
                if (!Main.tile[i, j].nactive() || !ScoreRoom_CanBeHomeSpot(i, j))
                {
                    continue;
                }
                num = num2;
                if (!Main.tileSolid[Main.tile[i, j].type] || Main.tileSolidTop[Main.tile[i, j].type] || Collision.SolidTiles(i - 1, i + 1, j - 3, j - 1) || !Main.tile[i - 1, j].nactive() || !Main.tileSolid[Main.tile[i - 1, j].type] || !Main.tile[i + 1, j].nactive() || !Main.tileSolid[Main.tile[i + 1, j].type])
                {
                    continue;
                }
                int num4 = 0;
                int num5 = 0;
                for (int k = i - 2; k < i + 3; k++)
                {
                    for (int l = j - 4; l < j; l++)
                    {
                        Tile tile = Main.tile[k, l];
                        if (tile.nactive() && !TileID.Sets.IgnoredInHouseScore[tile.type] && (tile.type != 11 || IsOpenDoorAnchorFrame(k, l)))
{
                            if (k == i)
{
                                num4++;
                            }
                            else if (TileID.Sets.BasicChest[tile.type])
{
                                num5++;
                            }
                            else
{
                                num = ((tile.type != 10 && tile.type != 388) ? ((!IsOpenDoorAnchorFrame(k, l) && tile.type != 389) ? ((!Main.tileSolid[tile.type]) ? (num + 5) : (num - 5)) : (num - 20)) : (num - 20));
                            }
                        }
                    }
                }
                if (sharedRoomX >= 0 && num >= 1 && Math.Abs(sharedRoomX - i) < 3)
                {
                    num = 1;
                }
                if (num > 0 && num5 > 0)
                {
                    num -= 30 * num5;
                    if (num < 1)
                    {
                        num = 1;
                    }
                }
                if (num > 0 && num4 > 0)
                {
                    num -= 15 * num4;
                    if (num <= 0)
                    {
                        num = 0;
                    }
                }
                if (num <= hiScore)
                {
                    continue;
                }
                bool flag = Housing_CheckIfInRoom(i, j);
                bool[] array = new bool[3];
                for (int m = 1; m <= 3; m++)
                {
                    if (!Main.tile[i, j - m].active() || !Main.tileSolid[Main.tile[i, j - m].type])
                    {
                        array[m - 1] = true;
                    }
                    if (!Housing_CheckIfInRoom(i, j - m))
                    {
                        array[m - 1] = false;
                    }
                }
                bool[] array2 = array;
                for (int n = 0; n < array2.Length; n++)
                {
                    if (!array2[n])
                    {
                        flag = false;
                        break;
                    }
                }
                if (flag && !Housing_CheckIfIsCeiling(i, j))
                {
                    hiScore = num;
                    bestX = i;
                    bestY = j;
                }
            }
        }
    }
References Terraria.Tile.active(), Terraria.ID.TileID.Sets.BasicChest, Terraria.WorldGen.bestX, Terraria.WorldGen.bestY, Terraria.ID.TileID.Count, Terraria.WorldGen.CountTileTypesInArea(), Terraria.WorldGen.GetTileTypeCountByCategory(), Terraria.WorldGen.hiScore, Terraria.WorldGen.Housing_CheckIfInRoom(), Terraria.WorldGen.Housing_CheckIfIsCeiling(), Terraria.WorldGen.Housing_GetTestedRoomBounds(), Terraria.ID.TileID.Sets.IgnoredInHouseScore, Terraria.WorldGen.IsOpenDoorAnchorFrame(), Terraria.Tile.nactive(), Terraria.WorldGen.roomEvil, Terraria.WorldGen.roomOccupied, Terraria.WorldGen.roomX1, Terraria.WorldGen.roomX2, Terraria.WorldGen.roomY1, Terraria.WorldGen.roomY2, Terraria.WorldGen.ScoreRoom_CanBeHomeSpot(), Terraria.WorldGen.ScoreRoom_IsThisRoomOccupiedBySomeone(), Terraria.WorldGen.sharedRoomX, Terraria.Collision.SolidTiles(), Terraria.Main.tile, Terraria.Main.tileSolid, Terraria.Main.tileSolidTop, and Terraria.Tile.type.
Referenced by Terraria.WorldGen.MoveTownNPC(), Terraria.WorldGen.QuickFindHome(), and Terraria.WorldGen.SpawnTownNPC().