Terraria: Terraria.WorldGen.Check1x2Top
Check1x2Top()
static void Terraria.WorldGen.Check1x2Top (int x, int j, ushort type) inline static
    {
        if (destroyObject)
        {
            return;
        }
        int num = j;
        bool flag = true;
        int num2 = Main.tile[x, num].frameY / 18;
        int num3 = 0;
        while (num2 >= 2)
        {
            num2 -= 2;
            num3++;
        }
        num -= num2;
        num2 = num3 * 36;
        if (Main.tile[x, num] == null)
        {
            Main.tile[x, num] = new Tile();
        }
        if (Main.tile[x, num + 1] == null)
        {
            Main.tile[x, num + 1] = new Tile();
        }
        if (Main.tile[x, num] == null)
        {
            Main.tile[x, num] = new Tile();
        }
        if (Main.tile[x, num].frameY == num2 && Main.tile[x, num + 1].frameY == num2 + 18 && Main.tile[x, num].type == type && Main.tile[x, num + 1].type == type)
        {
            flag = false;
        }
        if (Main.tile[x, num - 1] == null)
        {
            Main.tile[x, num - 1] = new Tile();
        }
        bool flag2 = false;
        switch (type)
        {
        case 42:
        case 270:
        case 271:
        case 572:
        case 581:
        case 660:
            flag2 = true;
            break;
        }
        bool flag3 = Main.tile[x, num - 1].active() && (TileID.Sets.Platforms[Main.tile[x, num - 1].type] || Main.tile[x, num - 1].type == 380);
        if ((!flag2 || !flag3) && (!Main.tile[x, num - 1].nactive() || !Main.tileSolid[Main.tile[x, num - 1].type] || Main.tileSolidTop[Main.tile[x, num - 1].type]))
        {
            flag = true;
        }
        if (!flag)
        {
            return;
        }
        destroyObject = true;
        if (Main.tile[x, num].type == type)
        {
            KillTile(x, num);
        }
        if (Main.tile[x, num + 1].type == type)
        {
            KillTile(x, num + 1);
        }
        switch (type)
        {
        case 42:
        {
            int type2 = 0;
            if (num3 == 0)
            {
                type2 = 136;
            }
            else if (num3 == 7)
            {
                type2 = 1431;
            }
            else if (num3 == 8)
            {
                type2 = 1808;
            }
            else if (num3 == 9)
            {
                type2 = 1859;
            }
            else if (num3 < 10)
            {
                type2 = 1389 + num3;
            }
            else
            {
                switch (num3)
                {
                case 10:
                    type2 = 2032;
                    break;
                case 11:
                    type2 = 2033;
                    break;
                case 12:
                    type2 = 2034;
                    break;
                case 13:
                    type2 = 2035;
                    break;
                case 14:
                    type2 = 2036;
                    break;
                case 15:
                    type2 = 2037;
                    break;
                case 16:
                    type2 = 2038;
                    break;
                case 17:
                    type2 = 2039;
                    break;
                case 18:
                    type2 = 2040;
                    break;
                case 19:
                    type2 = 2041;
                    break;
                case 20:
                    type2 = 2042;
                    break;
                case 21:
                    type2 = 2043;
                    break;
                case 22:
                case 23:
                case 24:
                case 25:
                    type2 = 2145 + num3 - 22;
                    break;
                default:
                    switch (num3)
                    {
                    case 26:
                        type2 = 2226;
                        break;
                    case 27:
                        type2 = 2530;
                        break;
                    case 28:
                        type2 = 2546;
                        break;
                    case 29:
                        type2 = 2564;
                        break;
                    case 30:
                        type2 = 2579;
                        break;
                    case 31:
                        type2 = 2641;
                        break;
                    case 32:
                        type2 = 2642;
                        break;
                    case 33:
                        type2 = 2820;
                        break;
                    case 34:
                        type2 = 3138;
                        break;
                    case 35:
                        type2 = 3140;
                        break;
                    case 36:
                        type2 = 3139;
                        break;
                    case 37:
                        type2 = 3891;
                        break;
                    case 38:
                        type2 = 3943;
                        break;
                    case 39:
                        type2 = 3970;
                        break;
                    case 40:
                        type2 = 4157;
                        break;
                    case 41:
                        type2 = 4178;
                        break;
                    case 42:
                        type2 = 4199;
                        break;
                    case 43:
                        type2 = 4220;
                        break;
                    case 44:
                        type2 = 4309;
                        break;
                    case 45:
                        type2 = 4578;
                        break;
                    case 46:
                        type2 = 5160;
                        break;
                    case 47:
                        type2 = 5181;
                        break;
                    case 48:
                        type2 = 5202;
                        break;
                    }
                    break;
                }
            }
            Item.NewItem(GetItemSource_FromTileBreak(x, num), x * 16, num * 16, 32, 32, type2);
            break;
        }
        case 270:
            Item.NewItem(GetItemSource_FromTileBreak(x, num), x * 16, num * 16, 32, 32, 1993);
            break;
        case 271:
            Item.NewItem(GetItemSource_FromTileBreak(x, num), x * 16, num * 16, 32, 32, 2005);
            break;
        case 581:
            Item.NewItem(GetItemSource_FromTileBreak(x, num), x * 16, num * 16, 32, 32, 4848);
            break;
        case 660:
            Item.NewItem(GetItemSource_FromTileBreak(x, num), x * 16, num * 16, 32, 32, 5351);
            break;
        case 572:
            Item.NewItem(GetItemSource_FromTileBreak(x, num), x * 16, num * 16, 32, 32, 4695 + num3);
            break;
        }
        destroyObject = false;
    }
References Terraria.Tile.active(), Terraria.Tile.frameY, Terraria.Tile.nactive(), Terraria.Item.NewItem(), Terraria.ID.TileID.Sets.Platforms, Terraria.DataStructures.Tile, Terraria.Main.tile, Terraria.Main.tileSolid, Terraria.Main.tileSolidTop, and Terraria.Tile.type.