Terraria: Terraria.WorldGen.InAPlaceWithWind
InAPlaceWithWind() [2/2]
static bool Terraria.WorldGen.InAPlaceWithWind (Vector2 position, int width, int height) inline static
Definition at line 76902 of file WorldGen.cs.
    {
        Point point = position.ToTileCoordinates();
        Point point2 = (position + new Vector2(width, height)).ToTileCoordinates();
        return InAPlaceWithWind(point.X, point.Y, 1 + point2.X - point.X, 1 + point2.Y - point.Y);
    }
References Microsoft.Xna.Framework.Point.X, and Microsoft.Xna.Framework.Point.Y.
Referenced by Terraria.NPC.AI_003_Gnomes_ShouldTurnToStone(), Terraria.Projectile.AI_160_Kites(), Terraria.Mount.GetWitchBroomTrinketRotation(), Terraria.GameContent.Drawing.TileDrawing.InAPlaceWithWind(), and Terraria.Mount.UpdateEffects().