Terraria: Terraria.WorldGen.MoveTownNPC
MoveTownNPC()
static bool Terraria.WorldGen.MoveTownNPC (int x, int y, int n) inline static
Definition at line 1478 of file WorldGen.cs.
    {
        if (!StartRoomCheck(x, y))
        {
            string newText = Lang.inter[40].Value;
            switch (roomCheckFailureReason)
            {
            case TownNPCRoomCheckFailureReason.HoleInWallIsTooBig:
                newText = Language.GetTextValue("TownNPCHousingFailureReasons.HoleInWallIsTooBig");
                break;
            case TownNPCRoomCheckFailureReason.RoomCheckStartedInASolidTile:
                newText = Language.GetTextValue("TownNPCHousingFailureReasons.RoomCheckStartedInASolidTile");
                break;
            case TownNPCRoomCheckFailureReason.RoomIsTooBig:
                newText = Language.GetTextValue("TownNPCHousingFailureReasons.RoomIsTooBig");
                break;
            case TownNPCRoomCheckFailureReason.RoomIsTooSmall:
                newText = Language.GetTextValue("TownNPCHousingFailureReasons.RoomIsTooSmall");
                break;
            case TownNPCRoomCheckFailureReason.TooCloseToWorldEdge:
                newText = Language.GetTextValue("TownNPCHousingFailureReasons.TooCloseToWorldEdge");
                break;
            }
            Main.NewText(newText, byte.MaxValue, 240, 20);
            return false;
        }
        if (!RoomNeeds(prioritizedTownNPCType))
        {
            int num = 0;
            int num2 = ((!roomTorch) ? 1 : 0) + ((!roomDoor) ? 1 : 0) + ((!roomTable) ? 1 : 0) + ((!roomChair) ? 1 : 0);
            string[] array = new string[num2];
            if (!roomTorch)
            {
                array[num] = Language.GetTextValue("Game.HouseLightSource");
                num++;
            }
            if (!roomDoor)
            {
                array[num] = Language.GetTextValue("Game.HouseDoor");
                num++;
            }
            if (!roomTable)
            {
                array[num] = Language.GetTextValue("Game.HouseTable");
                num++;
            }
            if (!roomChair)
            {
                array[num] = Language.GetTextValue("Game.HouseChair");
                num++;
            }
            string key = "Game.HouseMissing_" + num2;
            object[] args = array;
            Main.NewText(Language.GetTextValue(key, args), byte.MaxValue, 240, 20);
            return false;
        }
        int type = prioritizedTownNPCType;
        if (n >= 0)
        {
            type = Main.npc[n].type;
        }
        bool flag = NPCID.Sets.IsTownPet[type];
        if (roomHasStinkbug && !flag)
        {
            Main.NewText(Language.GetTextValue("TownNPCHousingFailureReasons.RoomHasAStinkbug"), byte.MaxValue, 240, 20);
            return false;
        }
        if (roomHasEchoStinkbug && !flag)
        {
            Main.NewText(Language.GetTextValue("TownNPCHousingFailureReasons.RoomHasAnEchoStinkbug"), byte.MaxValue, 240, 20);
            return false;
        }
        ScoreRoom(-1, type);
        if (hiScore <= 0)
        {
            if (roomOccupied)
            {
                Main.NewText(Lang.inter[41].Value, byte.MaxValue, 240, 20);
            }
            else if (roomEvil)
            {
                Main.NewText(Lang.inter[42].Value, byte.MaxValue, 240, 20);
            }
            else
            {
                Main.NewText(Lang.inter[40].Value, byte.MaxValue, 240, 20);
            }
            return false;
        }
        if (n >= 0 && !CheckSpecialTownNPCSpawningConditions(Main.npc[n].type))
        {
            Main.NewText(Lang.inter[55].Value + " " + Main.npc[n].TypeName, byte.MaxValue, 240, 20);
            return false;
        }
        return true;
    }
References Terraria.WorldGen.CheckSpecialTownNPCSpawningConditions(), Terraria.Localization.Language.GetTextValue(), Terraria.WorldGen.hiScore, Terraria.Lang.inter, Terraria.ID.NPCID.Sets.IsTownPet, Terraria.Main.NewText(), Terraria.Main.npc, Terraria.WorldGen.prioritizedTownNPCType, Terraria.WorldGen.roomChair, Terraria.WorldGen.roomCheckFailureReason, Terraria.WorldGen.roomDoor, Terraria.WorldGen.roomEvil, Terraria.WorldGen.roomHasEchoStinkbug, Terraria.WorldGen.roomHasStinkbug, Terraria.WorldGen.RoomNeeds(), Terraria.WorldGen.roomOccupied, Terraria.WorldGen.roomTable, Terraria.WorldGen.roomTorch, Terraria.WorldGen.ScoreRoom(), Terraria.WorldGen.StartRoomCheck(), Terraria.NPC.type, Terraria.NPC.TypeName, and Terraria.Localization.LocalizedText.Value.
Referenced by Terraria.Main.DrawInterface_38_MouseCarriedObject(), and Terraria.Initializers.UILinksInitializer.Load().