Terraria: Terraria.WorldGen.ShroomPatch
ShroomPatch()
static void Terraria.WorldGen.ShroomPatch (int i, int j) inline static
    {
        //IL_00f6: Unknown result type (might be due to invalid IL or missing references)
        //IL_010b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0121: Unknown result type (might be due to invalid IL or missing references)
        //IL_0136: Unknown result type (might be due to invalid IL or missing references)
        //IL_032c: Unknown result type (might be due to invalid IL or missing references)
        //IL_032d: Unknown result type (might be due to invalid IL or missing references)
        //IL_032e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0333: Unknown result type (might be due to invalid IL or missing references)
        //IL_033d: Unknown result type (might be due to invalid IL or missing references)
        //IL_038b: Unknown result type (might be due to invalid IL or missing references)
        //IL_03e0: Unknown result type (might be due to invalid IL or missing references)
        //IL_039c: Unknown result type (might be due to invalid IL or missing references)
        //IL_01a9: Unknown result type (might be due to invalid IL or missing references)
        //IL_01b8: Unknown result type (might be due to invalid IL or missing references)
        //IL_0401: Unknown result type (might be due to invalid IL or missing references)
        //IL_03ad: Unknown result type (might be due to invalid IL or missing references)
        //IL_0422: Unknown result type (might be due to invalid IL or missing references)
        //IL_022b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0443: Unknown result type (might be due to invalid IL or missing references)
        //IL_02c7: Unknown result type (might be due to invalid IL or missing references)
        //IL_046c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0484: Unknown result type (might be due to invalid IL or missing references)
        //IL_049d: Unknown result type (might be due to invalid IL or missing references)
        //IL_04b5: Unknown result type (might be due to invalid IL or missing references)
        double num = genRand.Next(80, 100);
        double num2 = genRand.Next(20, 26);
        double num3 = (double)Main.maxTilesX / 4200.0;
        if (getGoodWorldGen && !Main.remixWorld)
        {
            num3 *= 1.5;
        }
        num *= num3;
        num2 *= num3;
        double num4 = num2 - 1.0;
        double num5 = num;
        Vector2D val = default(Vector2D);
        val.X = i;
        val.Y = (double)j - num2 * 0.3;
        Vector2D val2 = default(Vector2D);
        val2.X = (double)genRand.Next(-100, 101) * 0.005;
        val2.Y = (double)genRand.Next(-200, -100) * 0.005;
        while (num > 0.0 && num2 > 0.0)
        {
            num -= (double)genRand.Next(3);
            num2 -= 1.0;
            int num6 = (int)(val.X - num * 0.5);
            int num7 = (int)(val.X + num * 0.5);
            int num8 = (int)(val.Y - num * 0.5);
            int num9 = (int)(val.Y + num * 0.5);
            if (num6 < 0)
            {
                num6 = 0;
            }
            if (num7 > Main.maxTilesX)
            {
                num7 = Main.maxTilesX;
            }
            if (num8 < 0)
            {
                num8 = 0;
            }
            if (num9 > Main.maxTilesY)
            {
                num9 = Main.maxTilesY;
            }
            num5 = num * (double)genRand.Next(80, 120) * 0.01;
            for (int k = num6; k < num7; k++)
            {
                for (int l = num8; l < num9; l++)
                {
                    double num10 = Math.Abs((double)k - val.X);
                    double num11 = Math.Abs(((double)l - val.Y) * 2.3);
                    double num12 = Math.Sqrt(num10 * num10 + num11 * num11);
                    if (num12 < num5 * 0.8 && Main.tile[k, l].lava())
                    {
                        Main.tile[k, l].liquid = 0;
                    }
                    if (num12 < num5 * 0.2 && (double)l < val.Y)
                    {
                        Main.tile[k, l].active(active: false);
                        if (Main.tile[k, l].wall > 0)
{
                            Main.tile[k, l].wall = 80;
                        }
                    }
                    else if (num12 < num5 * 0.4 * (0.95 + genRand.NextDouble() * 0.1))
                    {
                        Main.tile[k, l].type = 59;
                        if (num2 == num4 && (double)l > val.Y)
{
                            Main.tile[k, l].active(active: true);
                        }
                        if (Main.tile[k, l].wall > 0)
{
                            Main.tile[k, l].wall = 80;
                        }
                    }
                }
            }
            val += val2;
            val.X += val2.X;
            val2.X += (double)genRand.Next(-100, 110) * 0.005;
            val2.Y -= (double)genRand.Next(110) * 0.005;
            if (val2.X > -0.5 && val2.X < 0.5)
            {
                if (val2.X < 0.0)
                {
                    val2.X = -0.5;
                }
                else
                {
                    val2.X = 0.5;
                }
            }
            if (val2.X > 0.5)
            {
                val2.X = 0.5;
            }
            if (val2.X < -0.5)
            {
                val2.X = -0.5;
            }
            if (val2.Y > 0.5)
            {
                val2.Y = 0.5;
            }
            if (val2.Y < -0.5)
            {
                val2.Y = -0.5;
            }
            for (int m = 0; m < 2; m++)
            {
                int num13 = (int)val.X + genRand.Next(-20, 20);
                int num14 = (int)val.Y + genRand.Next(0, 20);
                while (!Main.tile[num13, num14].active() && Main.tile[num13, num14].type != 59)
                {
                    num13 = (int)val.X + genRand.Next(-20, 20);
                    num14 = (int)val.Y + genRand.Next(0, 20);
                }
                int num15 = genRand.Next(10, 20);
                int steps = genRand.Next(10, 20);
                TileRunner(num13, num14, num15, steps, 59, addTile: false, 0.0, 2.0, noYChange: true);
            }
        }
    }
References Terraria.Tile.active(), Terraria.Tile.lava(), Terraria.Tile.liquid, Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.Main.remixWorld, Terraria.Main.tile, Terraria.Tile.type, Terraria.Tile.wall, ReLogic.Utilities.Vector2D.X, and ReLogic.Utilities.Vector2D.Y.
Referenced by Terraria.WorldGen.GenerateWorld().