Terraria: Terraria.WorldGen.PlaceSmallPile
PlaceSmallPile()
static bool Terraria.WorldGen.PlaceSmallPile (int i, int j, int X, int Y, ushort type = 185) inline static
    {
        short frameY = (short)(Y * 18);
        short frameX = (short)(X * 18);
        if (Main.tile[i, j] == null)
        {
            Main.tile[i, j] = new Tile();
        }
        if (Main.tile[i + 1, j] == null)
        {
            Main.tile[i + 1, j] = new Tile();
        }
        if (Main.tile[i, j + 1] == null)
        {
            Main.tile[i, j + 1] = new Tile();
        }
        if (Main.tile[i + 1, j + 1] == null)
        {
            Main.tile[i + 1, j + 1] = new Tile();
        }
        if (Main.tile[i, j].lava())
        {
            return false;
        }
        if (Y == 1)
        {
            frameX = (short)(X * 36);
            bool flag = false;
            if (SolidTile2(i, j + 1) && SolidTile2(i + 1, j + 1) && !Main.tile[i, j].active() && !Main.tile[i + 1, j].active())
            {
                flag = true;
            }
            if (flag)
            {
                Main.tile[i, j].active(active: true);
                Main.tile[i, j].frameY = frameY;
                Main.tile[i, j].frameX = frameX;
                Main.tile[i, j].type = type;
                Main.tile[i + 1, j].active(active: true);
                Main.tile[i + 1, j].frameY = frameY;
                Main.tile[i + 1, j].frameX = (short)(frameX + 18);
                Main.tile[i + 1, j].type = type;
                return true;
            }
        }
        else if (SolidTile2(i, j + 1) && !Main.tile[i, j].active())
        {
            Main.tile[i, j].active(active: true);
            Main.tile[i, j].frameY = frameY;
            Main.tile[i, j].frameX = frameX;
            Main.tile[i, j].type = type;
            return true;
        }
        return false;
    }
References Terraria.Tile.active(), Terraria.Tile.frameX, Terraria.Tile.frameY, Terraria.Tile.lava(), Terraria.DataStructures.Tile, Terraria.Main.tile, and Terraria.Tile.type.
Referenced by Terraria.GameContent.Biomes.CaveHouse.HouseBuilder.FillRooms(), Terraria.WorldGen.Spread.Spider(), and Terraria.WorldGen.StonePatch().