Terraria: Terraria.WorldGen.GenerateWorld
GenerateWorld()
static void Terraria.WorldGen.GenerateWorld (int seed, GenerationProgress customProgressObject = null) inline static
Definition at line 7175 of file WorldGen.cs.
    {
        remixWorldGen = tempRemixWorldGen;
        tenthAnniversaryWorldGen = tempTenthAnniversaryWorldGen;
        drunkWorldGen = false;
        drunkWorldGenText = false;
        Main.afterPartyOfDoom = false;
        if (seed == 5162020 || everythingWorldGen)
        {
            drunkWorldGen = true;
            drunkWorldGenText = true;
            Main.drunkWorld = true;
            Main.rand = new UnifiedRandom();
            seed = Main.rand.Next(999999999);
            if (!Main.dayTime)
            {
                Main.time = 0.0;
            }
        }
        else if (seed == 5162021 || seed == 5162011)
        {
            tenthAnniversaryWorldGen = true;
        }
        Main.notTheBeesWorld = notTheBees;
        if (notTheBees)
        {
            Main.rand = new UnifiedRandom();
            seed = Main.rand.Next(999999999);
        }
        Main.noTrapsWorld = noTrapsWorldGen;
        if (noTrapsWorldGen)
        {
            Main.rand = new UnifiedRandom();
            seed = Main.rand.Next(999999999);
        }
        if (getGoodWorldGen)
        {
            Main.getGoodWorld = true;
            Main.rand = new UnifiedRandom();
            seed = Main.rand.Next(999999999);
        }
        else
        {
            Main.getGoodWorld = false;
        }
        Main.tenthAnniversaryWorld = tenthAnniversaryWorldGen;
        if (tenthAnniversaryWorldGen)
        {
            Main.rand = new UnifiedRandom();
            seed = Main.rand.Next(999999999);
        }
        Main.dontStarveWorld = dontStarveWorldGen;
        if (dontStarveWorldGen)
        {
            Main.rand = new UnifiedRandom();
            seed = Main.rand.Next(999999999);
        }
        Main.remixWorld = remixWorldGen;
        if (remixWorldGen)
        {
            Main.rand = new UnifiedRandom();
            seed = Main.rand.Next(999999999);
        }
        Main.zenithWorld = everythingWorldGen;
        Console.WriteLine("Creating world - Seed: {0} Width: {1}, Height: {2}, Evil: {3}, IsExpert: {4}", seed, Main.maxTilesX, Main.maxTilesY, WorldGenParam_Evil, Main.expertMode);
        Main.lockMenuBGChange = true;
        GenVars.configuration = WorldGenConfiguration.FromEmbeddedPath("Terraria.GameContent.WorldBuilding.Configuration.json");
        Hooks.ProcessWorldGenConfig(ref GenVars.configuration);
        _lastSeed = seed;
        _generator = new WorldGenerator(seed, GenVars.configuration);
        _genRand = new UnifiedRandom(seed);
        Main.rand = new UnifiedRandom(seed);
        GenVars.structures = new StructureMap();
        GenVars.desertHiveHigh = Main.maxTilesY;
        GenVars.desertHiveLow = 0;
        GenVars.desertHiveLeft = Main.maxTilesX;
        GenVars.desertHiveRight = 0;
        GenVars.worldSurfaceLow = 0.0;
        GenVars.worldSurface = 0.0;
        GenVars.worldSurfaceHigh = 0.0;
        GenVars.rockLayerLow = 0.0;
        GenVars.rockLayer = 0.0;
        GenVars.rockLayerHigh = 0.0;
        GenVars.copper = 7;
        GenVars.iron = 6;
        GenVars.silver = 9;
        GenVars.gold = 8;
        GenVars.dungeonSide = 0;
        GenVars.jungleHut = (ushort)genRand.Next(5);
        GenVars.shellStartXLeft = 0;
        GenVars.shellStartYLeft = 0;
        GenVars.shellStartXRight = 0;
        GenVars.shellStartYRight = 0;
        GenVars.PyrX = null;
        GenVars.PyrY = null;
        GenVars.numPyr = 0;
        GenVars.jungleMinX = -1;
        GenVars.jungleMaxX = -1;
        GenVars.snowMinX = new int[Main.maxTilesY];
        GenVars.snowMaxX = new int[Main.maxTilesY];
        GenVars.snowTop = 0;
        GenVars.snowBottom = 0;
        GenVars.skyLakes = 1;
        if (Main.maxTilesX > 8000)
        {
            GenVars.skyLakes++;
        }
        if (Main.maxTilesX > 6000)
        {
            GenVars.skyLakes++;
        }
        GenVars.beachBordersWidth = 275;
        GenVars.beachSandRandomCenter = GenVars.beachBordersWidth + 5 + 40;
        GenVars.beachSandRandomWidthRange = 20;
        GenVars.beachSandDungeonExtraWidth = 40;
        GenVars.beachSandJungleExtraWidth = 20;
        GenVars.oceanWaterStartRandomMin = 220;
        GenVars.oceanWaterStartRandomMax = GenVars.oceanWaterStartRandomMin + 40;
        GenVars.oceanWaterForcedJungleLength = 275;
        GenVars.leftBeachEnd = 0;
        GenVars.rightBeachStart = 0;
        GenVars.evilBiomeBeachAvoidance = GenVars.beachSandRandomCenter + 60;
        GenVars.evilBiomeAvoidanceMidFixer = 50;
        GenVars.lakesBeachAvoidance = GenVars.beachSandRandomCenter + 20;
        GenVars.smallHolesBeachAvoidance = GenVars.beachSandRandomCenter + 20;
        GenVars.surfaceCavesBeachAvoidance = GenVars.beachSandRandomCenter + 20;
        GenVars.surfaceCavesBeachAvoidance2 = GenVars.beachSandRandomCenter + 20;
        GenVars.jungleOriginX = 0;
        GenVars.snowOriginLeft = 0;
        GenVars.snowOriginRight = 0;
        GenVars.logX = -1;
        GenVars.logY = -1;
        GenVars.dungeonLocation = 0;
        if (everythingWorldGen)
        {
            Main.starGame = true;
        }
        AddGenerationPass("Reset", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            if (genRand.Next(2) == 0)
            {
                GenVars.crimsonLeft = false;
            }
            else
            {
                GenVars.crimsonLeft = true;
            }
            GenVars.numOceanCaveTreasure = 0;
            GenVars.skipDesertTileCheck = false;
            growGrassUnderground = false;
            gen = true;
            Liquid.ReInit();
            noTileActions = true;
            progress.Message = "";
            SetupStatueList();
            RandomizeWeather();
            Main.cloudAlpha = 0f;
            Main.maxRaining = 0f;
            Main.raining = false;
            heartCount = 0;
            GenVars.extraBastStatueCount = 0;
            GenVars.extraBastStatueCountMax = 2;
            Main.checkXMas();
            Main.checkHalloween();
            ResetGenerator();
            GenVars.UndergroundDesertLocation = Rectangle.Empty;
            GenVars.UndergroundDesertHiveLocation = Rectangle.Empty;
            GenVars.numLarva = 0;
            List<int> list3 = new List<int> { 274, 220, 112, 218, 3019 };
            if (remixWorldGen)
            {
                list3 = new List<int> { 274, 220, 683, 218, 3019 };
            }
            List<int> list4 = new List<int>();
            while (list3.Count > 0)
            {
                int index = genRand.Next(list3.Count);
                int item = list3[index];
                list4.Add(item);
                list3.RemoveAt(index);
            }
            GenVars.hellChestItem = list4.ToArray();
            int num1086 = 86400;
            Main.slimeRainTime = -genRand.Next(num1086 * 2, num1086 * 3);
            Main.cloudBGActive = -genRand.Next(8640, 86400);
            skipFramingDuringGen = false;
            SavedOreTiers.Copper = 7;
            SavedOreTiers.Iron = 6;
            SavedOreTiers.Silver = 9;
            SavedOreTiers.Gold = 8;
            GenVars.copperBar = 20;
            GenVars.ironBar = 22;
            GenVars.silverBar = 21;
            GenVars.goldBar = 19;
            if (genRand.Next(2) == 0)
            {
                GenVars.copper = 166;
                GenVars.copperBar = 703;
                SavedOreTiers.Copper = 166;
            }
            if ((!dontStarveWorldGen || drunkWorldGen) && genRand.Next(2) == 0)
            {
                GenVars.iron = 167;
                GenVars.ironBar = 704;
                SavedOreTiers.Iron = 167;
            }
            if (genRand.Next(2) == 0)
            {
                GenVars.silver = 168;
                GenVars.silverBar = 705;
                SavedOreTiers.Silver = 168;
            }
            if ((!dontStarveWorldGen || drunkWorldGen) && genRand.Next(2) == 0)
            {
                GenVars.gold = 169;
                GenVars.goldBar = 706;
                SavedOreTiers.Gold = 169;
            }
            crimson = genRand.Next(2) == 0;
            if (WorldGenParam_Evil == 0)
            {
                crimson = false;
            }
            if (WorldGenParam_Evil == 1)
            {
                crimson = true;
            }
            if (GenVars.jungleHut == 0)
            {
                GenVars.jungleHut = 119;
            }
            else if (GenVars.jungleHut == 1)
            {
                GenVars.jungleHut = 120;
            }
            else if (GenVars.jungleHut == 2)
            {
                GenVars.jungleHut = 158;
            }
            else if (GenVars.jungleHut == 3)
            {
                GenVars.jungleHut = 175;
            }
            else if (GenVars.jungleHut == 4)
            {
                GenVars.jungleHut = 45;
            }
            Main.worldID = genRand.Next(int.MaxValue);
            RandomizeTreeStyle();
            RandomizeCaveBackgrounds();
            RandomizeBackgrounds(genRand);
            RandomizeMoonState(genRand);
            TreeTops.CopyExistingWorldInfoForWorldGeneration();
            GenVars.dungeonSide = ((genRand.Next(2) != 0) ? 1 : (-1));
            if (remixWorldGen)
            {
                if (GenVars.dungeonSide == -1)
                {
                    double num1087 = 1.0 - (double)genRand.Next(20, 35) * 0.01;
                    GenVars.jungleOriginX = (int)((double)Main.maxTilesX * num1087);
                }
                else
                {
                    double num1088 = (double)genRand.Next(20, 35) * 0.01;
                    GenVars.jungleOriginX = (int)((double)Main.maxTilesX * num1088);
                }
            }
            else
            {
                int minValue3 = 15;
                int maxValue12 = 30;
                if (tenthAnniversaryWorldGen && !remixWorldGen)
                {
                    minValue3 = 25;
                    maxValue12 = 35;
                }
                if (GenVars.dungeonSide == -1)
                {
                    double num1089 = 1.0 - (double)genRand.Next(minValue3, maxValue12) * 0.01;
                    GenVars.jungleOriginX = (int)((double)Main.maxTilesX * num1089);
                }
                else
                {
                    double num1090 = (double)genRand.Next(minValue3, maxValue12) * 0.01;
                    GenVars.jungleOriginX = (int)((double)Main.maxTilesX * num1090);
                }
            }
            int num1091 = genRand.Next(Main.maxTilesX);
            if (drunkWorldGen)
            {
                GenVars.dungeonSide *= -1;
            }
            if (GenVars.dungeonSide == 1)
            {
                while ((double)num1091 < (double)Main.maxTilesX * 0.6 || (double)num1091 > (double)Main.maxTilesX * 0.75)
                {
                    num1091 = genRand.Next(Main.maxTilesX);
                }
            }
            else
            {
                while ((double)num1091 < (double)Main.maxTilesX * 0.25 || (double)num1091 > (double)Main.maxTilesX * 0.4)
                {
                    num1091 = genRand.Next(Main.maxTilesX);
                }
            }
            if (drunkWorldGen)
            {
                GenVars.dungeonSide *= -1;
            }
            int num1092 = genRand.Next(50, 90);
            double num1093 = (double)Main.maxTilesX / 4200.0;
            num1092 += (int)((double)genRand.Next(20, 40) * num1093);
            num1092 += (int)((double)genRand.Next(20, 40) * num1093);
            int num1094 = num1091 - num1092;
            num1092 = genRand.Next(50, 90);
            num1092 += (int)((double)genRand.Next(20, 40) * num1093);
            num1092 += (int)((double)genRand.Next(20, 40) * num1093);
            int num1095 = num1091 + num1092;
            if (num1094 < 0)
            {
                num1094 = 0;
            }
            if (num1095 > Main.maxTilesX)
            {
                num1095 = Main.maxTilesX;
            }
            GenVars.snowOriginLeft = num1094;
            GenVars.snowOriginRight = num1095;
            GenVars.leftBeachEnd = genRand.Next(GenVars.beachSandRandomCenter - GenVars.beachSandRandomWidthRange, GenVars.beachSandRandomCenter + GenVars.beachSandRandomWidthRange);
            if (tenthAnniversaryWorldGen && !remixWorldGen)
            {
                GenVars.leftBeachEnd = GenVars.beachSandRandomCenter + GenVars.beachSandRandomWidthRange;
            }
            if (GenVars.dungeonSide == 1)
            {
                GenVars.leftBeachEnd += GenVars.beachSandDungeonExtraWidth;
            }
            else
            {
                GenVars.leftBeachEnd += GenVars.beachSandJungleExtraWidth;
            }
            GenVars.rightBeachStart = Main.maxTilesX - genRand.Next(GenVars.beachSandRandomCenter - GenVars.beachSandRandomWidthRange, GenVars.beachSandRandomCenter + GenVars.beachSandRandomWidthRange);
            if (tenthAnniversaryWorldGen && !remixWorldGen)
            {
                GenVars.rightBeachStart = Main.maxTilesX - (GenVars.beachSandRandomCenter + GenVars.beachSandRandomWidthRange);
            }
            if (GenVars.dungeonSide == -1)
            {
                GenVars.rightBeachStart -= GenVars.beachSandDungeonExtraWidth;
            }
            else
            {
                GenVars.rightBeachStart -= GenVars.beachSandJungleExtraWidth;
            }
            int num1096 = 50;
            if (GenVars.dungeonSide == -1)
            {
                GenVars.dungeonLocation = genRand.Next(GenVars.leftBeachEnd + num1096, (int)((double)Main.maxTilesX * 0.2));
            }
            else
            {
                GenVars.dungeonLocation = genRand.Next((int)((double)Main.maxTilesX * 0.8), GenVars.rightBeachStart - num1096);
            }
            int num1097 = 0;
            if (Main.maxTilesX >= 8400)
            {
                num1097 = 2;
            }
            else if (Main.maxTilesX >= 6400)
            {
                num1097 = 1;
            }
            GenVars.extraBastStatueCountMax = 2 + num1097;
            Main.tileSolid[659] = false;
        });
        AddGenerationPass(new TerrainPass());
        AddGenerationPass("Dunes", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            progress.Message = Lang.gen[1].Value;
            int random9 = passConfig.Get<WorldGenRange>("Count").GetRandom(genRand);
            double num1080 = passConfig.Get<double>("ChanceOfPyramid");
            if (drunkWorldGen)
            {
                num1080 = 1.0;
            }
            double num1081 = (double)Main.maxTilesX / 4200.0;
            GenVars.PyrX = new int[random9 + 3];
            GenVars.PyrY = new int[random9 + 3];
            DunesBiome dunesBiome = GenVars.configuration.CreateBiome<DunesBiome>();
            for (int num1082 = 0; num1082 < random9; num1082++)
            {
                progress.Set((double)num1082 / (double)random9);
                Point origin5 = Point.Zero;
                bool flag62 = false;
                int num1083 = 0;
                while (!flag62)
                {
                    origin5 = RandomWorldPoint(0, 500, 0, 500);
                    bool flag63 = Math.Abs(origin5.X - GenVars.jungleOriginX) < (int)(600.0 * num1081);
                    bool flag64 = Math.Abs(origin5.X - Main.maxTilesX / 2) < 300;
                    bool flag65 = origin5.X > GenVars.snowOriginLeft - 300 && origin5.X < GenVars.snowOriginRight + 300;
                    num1083++;
                    if (num1083 >= Main.maxTilesX)
                    {
                        flag63 = false;
                    }
                    if (num1083 >= Main.maxTilesX * 2)
                    {
                        flag65 = false;
                    }
                    flag62 = !(flag63 || flag64 || flag65);
                }
                dunesBiome.Place(origin5, GenVars.structures);
                if (genRand.NextDouble() <= num1080)
                {
                    int num1084 = genRand.Next(origin5.X - 200, origin5.X + 200);
                    for (int num1085 = 0; num1085 < Main.maxTilesY; num1085++)
                    {
                        if (Main.tile[num1084, num1085].active())
{
                            GenVars.PyrX[GenVars.numPyr] = num1084;
                            GenVars.PyrY[GenVars.numPyr] = num1085 + 20;
                            GenVars.numPyr++;
                            break;
                        }
                    }
                }
            }
        });
        AddGenerationPass("Ocean Sand", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            progress.Message = Language.GetTextValue("WorldGeneration.OceanSand");
            for (int num1069 = 0; num1069 < 3; num1069++)
            {
                progress.Set((double)num1069 / 3.0);
                int num1070 = genRand.Next(Main.maxTilesX);
                while ((double)num1070 > (double)Main.maxTilesX * 0.4 && (double)num1070 < (double)Main.maxTilesX * 0.6)
                {
                    num1070 = genRand.Next(Main.maxTilesX);
                }
                int num1071 = genRand.Next(35, 90);
                if (num1069 == 1)
                {
                    double num1072 = (double)Main.maxTilesX / 4200.0;
                    num1071 += (int)((double)genRand.Next(20, 40) * num1072);
                }
                if (genRand.Next(3) == 0)
                {
                    num1071 *= 2;
                }
                if (num1069 == 1)
                {
                    num1071 *= 2;
                }
                int num1073 = num1070 - num1071;
                num1071 = genRand.Next(35, 90);
                if (genRand.Next(3) == 0)
                {
                    num1071 *= 2;
                }
                if (num1069 == 1)
                {
                    num1071 *= 2;
                }
                int num1074 = num1070 + num1071;
                if (num1073 < 0)
                {
                    num1073 = 0;
                }
                if (num1074 > Main.maxTilesX)
                {
                    num1074 = Main.maxTilesX;
                }
                if (num1069 == 0)
                {
                    num1073 = 0;
                    num1074 = GenVars.leftBeachEnd;
                }
                else if (num1069 == 2)
                {
                    num1073 = GenVars.rightBeachStart;
                    num1074 = Main.maxTilesX;
                }
                else if (num1069 == 1)
                {
                    continue;
                }
                int num1075 = genRand.Next(50, 100);
                for (int num1076 = num1073; num1076 < num1074; num1076++)
                {
                    if (genRand.Next(2) == 0)
                    {
                        num1075 += genRand.Next(-1, 2);
                        if (num1075 < 50)
{
                            num1075 = 50;
                        }
                        if (num1075 > 200)
{
                            num1075 = 200;
                        }
                    }
                    for (int num1077 = 0; (double)num1077 < (Main.worldSurface + Main.rockLayer) / 2.0; num1077++)
                    {
                        if (Main.tile[num1076, num1077].active())
{
                            if (num1076 == (num1073 + num1074) / 2 && genRand.Next(6) == 0)
{
                                GenVars.PyrX[GenVars.numPyr] = num1076;
                                GenVars.PyrY[GenVars.numPyr] = num1077;
                                GenVars.numPyr++;
                            }
                            int num1078 = num1075;
                            if (num1076 - num1073 < num1078)
{
                                num1078 = num1076 - num1073;
                            }
                            if (num1074 - num1076 < num1078)
{
                                num1078 = num1074 - num1076;
                            }
                            num1078 += genRand.Next(5);
                            for (int num1079 = num1077; num1079 < num1077 + num1078; num1079++)
{
                                if (num1076 > num1073 + genRand.Next(5) && num1076 < num1074 - genRand.Next(5))
{
                                    Main.tile[num1076, num1079].type = 53;
                                }
                            }
                            break;
                        }
                    }
                }
            }
        });
        AddGenerationPass("Sand Patches", delegate
        {
            int num1064 = (int)((double)Main.maxTilesX * 0.013);
            if (remixWorldGen)
            {
                num1064 /= 4;
            }
            for (int num1065 = 0; num1065 < num1064; num1065++)
            {
                int num1066 = genRand.Next(0, Main.maxTilesX);
                int num1067 = genRand.Next((int)Main.worldSurface, (int)Main.rockLayer);
                if (remixWorldGen)
                {
                    num1067 = genRand.Next((int)Main.rockLayer - 100, Main.maxTilesY - 350);
                }
                while ((double)num1066 > (double)Main.maxTilesX * 0.46 && (double)num1066 < (double)Main.maxTilesX * 0.54 && (double)num1067 < Main.worldSurface + 150.0)
                {
                    num1066 = genRand.Next(0, Main.maxTilesX);
                    num1067 = genRand.Next((int)Main.worldSurface, (int)Main.rockLayer);
                }
                int num1068 = genRand.Next(15, 70);
                int steps2 = genRand.Next(20, 130);
                TileRunner(num1066, num1067, num1068, steps2, 53);
            }
        });
        AddGenerationPass("Tunnels", delegate
        {
            int num1058 = (int)((double)Main.maxTilesX * 0.0015);
            if (remixWorldGen)
            {
                num1058 = (int)((double)num1058 * 1.5);
            }
            for (int num1059 = 0; num1059 < num1058; num1059++)
            {
                if (GenVars.numTunnels >= GenVars.maxTunnels - 1)
                {
                    break;
                }
                int[] array = new int[10];
                int[] array2 = new int[10];
                int num1060 = genRand.Next(450, Main.maxTilesX - 450);
                if (!remixWorldGen)
                {
                    if (tenthAnniversaryWorldGen)
                    {
                        num1060 = genRand.Next((int)((double)Main.maxTilesX * 0.2), (int)((double)Main.maxTilesX * 0.8));
                    }
                    else
                    {
                        while ((double)num1060 > (double)Main.maxTilesX * 0.4 && (double)num1060 < (double)Main.maxTilesX * 0.6)
{
                            num1060 = genRand.Next(450, Main.maxTilesX - 450);
                        }
                    }
                }
                int num1061 = 0;
                bool flag61;
                do
                {
                    flag61 = false;
                    for (int num1062 = 0; num1062 < 10; num1062++)
                    {
                        for (num1060 %= Main.maxTilesX; !Main.tile[num1060, num1061].active(); num1061++)
{
                        }
                        if (Main.tile[num1060, num1061].type == 53)
{
                            flag61 = true;
                        }
                        array[num1062] = num1060;
                        array2[num1062] = num1061 - genRand.Next(11, 16);
                        num1060 += genRand.Next(5, 11);
                    }
                }
                while (flag61);
                GenVars.tunnelX[GenVars.numTunnels] = array[5];
                GenVars.numTunnels++;
                for (int num1063 = 0; num1063 < 10; num1063++)
                {
                    TileRunner(array[num1063], array2[num1063], genRand.Next(5, 8), genRand.Next(6, 9), 0, addTile: true, -2.0, -0.3);
                    TileRunner(array[num1063], array2[num1063], genRand.Next(5, 8), genRand.Next(6, 9), 0, addTile: true, 2.0, -0.3);
                }
            }
        });
        AddGenerationPass("Mount Caves", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            GenVars.numMCaves = 0;
            progress.Message = Lang.gen[2].Value;
            int num1050 = (int)((double)Main.maxTilesX * 0.001);
            if (remixWorldGen)
            {
                num1050 = (int)((double)num1050 * 1.5);
            }
            for (int num1051 = 0; num1051 < num1050; num1051++)
            {
                progress.Set((double)num1051 / (double)num1050);
                int num1052 = 0;
                bool flag59 = false;
                bool flag60 = false;
                int num1053 = genRand.Next((int)((double)Main.maxTilesX * 0.25), (int)((double)Main.maxTilesX * 0.75));
                while (!flag60)
                {
                    flag60 = true;
                    if (!remixWorldGen)
                    {
                        while (num1053 > Main.maxTilesX / 2 - 90 && num1053 < Main.maxTilesX / 2 + 90)
{
                            num1053 = genRand.Next((int)((double)Main.maxTilesX * 0.25), (int)((double)Main.maxTilesX * 0.75));
                        }
                    }
                    for (int num1054 = 0; num1054 < GenVars.numMCaves; num1054++)
                    {
                        if (Math.Abs(num1053 - GenVars.mCaveX[num1054]) < 100)
{
                            num1052++;
                            flag60 = false;
                            break;
                        }
                    }
                    if (num1052 >= Main.maxTilesX / 5)
                    {
                        flag59 = true;
                        break;
                    }
                }
                if (!flag59)
                {
                    for (int num1055 = 0; (double)num1055 < Main.worldSurface; num1055++)
                    {
                        if (Main.tile[num1053, num1055].active())
{
                            for (int num1056 = num1053 - 50; num1056 < num1053 + 50; num1056++)
{
                                for (int num1057 = num1055 - 25; num1057 < num1055 + 25; num1057++)
{
                                    if (Main.tile[num1056, num1057].active() && (Main.tile[num1056, num1057].type == 53 || Main.tile[num1056, num1057].type == 151 || Main.tile[num1056, num1057].type == 274))
{
                                        flag59 = true;
                                    }
                                }
                            }
                            if (!flag59)
{
                                Mountinater(num1053, num1055);
                                GenVars.mCaveX[GenVars.numMCaves] = num1053;
                                GenVars.mCaveY[GenVars.numMCaves] = num1055;
                                GenVars.numMCaves++;
                                break;
                            }
                        }
                    }
                }
            }
        });
        AddGenerationPass("Dirt Wall Backgrounds", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            progress.Message = Lang.gen[3].Value;
            int num1047 = 0;
            for (int num1048 = 1; num1048 < Main.maxTilesX - 1; num1048++)
            {
                ushort wall3 = 2;
                double value20 = (double)num1048 / (double)Main.maxTilesX;
                progress.Set(value20);
                bool flag58 = false;
                num1047 += genRand.Next(-1, 2);
                if (num1047 < 0)
                {
                    num1047 = 0;
                }
                if (num1047 > 10)
                {
                    num1047 = 10;
                }
                for (int num1049 = 0; (double)num1049 < Main.worldSurface + 10.0 && !((double)num1049 > Main.worldSurface + (double)num1047); num1049++)
                {
                    if (Main.tile[num1048, num1049].active())
                    {
                        wall3 = (ushort)((Main.tile[num1048, num1049].type != 147) ? 2 : 40);
                    }
                    if (flag58 && Main.tile[num1048, num1049].wall != 64)
                    {
                        Main.tile[num1048, num1049].wall = wall3;
                    }
                    if (Main.tile[num1048, num1049].active() && Main.tile[num1048 - 1, num1049].active() && Main.tile[num1048 + 1, num1049].active() && Main.tile[num1048, num1049 + 1].active() && Main.tile[num1048 - 1, num1049 + 1].active() && Main.tile[num1048 + 1, num1049 + 1].active())
                    {
                        flag58 = true;
                    }
                }
            }
        });
        AddGenerationPass("Rocks In Dirt", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            progress.Message = Lang.gen[4].Value;
            double num1041 = (double)(Main.maxTilesX * Main.maxTilesY) * 0.00015;
            for (int num1042 = 0; (double)num1042 < num1041; num1042++)
            {
                TileRunner(genRand.Next(0, Main.maxTilesX), genRand.Next(0, (int)GenVars.worldSurfaceLow + 1), genRand.Next(4, 15), genRand.Next(5, 40), 1);
            }
            progress.Set(0.34);
            num1041 = (double)(Main.maxTilesX * Main.maxTilesY) * 0.0002;
            for (int num1043 = 0; (double)num1043 < num1041; num1043++)
            {
                int num1044 = genRand.Next(0, Main.maxTilesX);
                int num1045 = genRand.Next((int)GenVars.worldSurfaceLow, (int)GenVars.worldSurfaceHigh + 1);
                if (!Main.tile[num1044, num1045 - 10].active())
                {
                    num1045 = genRand.Next((int)GenVars.worldSurfaceLow, (int)GenVars.worldSurfaceHigh + 1);
                }
                TileRunner(num1044, num1045, genRand.Next(4, 10), genRand.Next(5, 30), 1);
            }
            progress.Set(0.67);
            num1041 = (double)(Main.maxTilesX * Main.maxTilesY) * 0.0045;
            for (int num1046 = 0; (double)num1046 < num1041; num1046++)
            {
                TileRunner(genRand.Next(0, Main.maxTilesX), genRand.Next((int)GenVars.worldSurfaceHigh, (int)GenVars.rockLayerHigh + 1), genRand.Next(2, 7), genRand.Next(2, 23), 1);
            }
        });
        AddGenerationPass("Dirt In Rocks", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            progress.Message = Lang.gen[5].Value;
            double num1037 = (double)(Main.maxTilesX * Main.maxTilesY) * 0.005;
            for (int num1038 = 0; (double)num1038 < num1037; num1038++)
            {
                progress.Set((double)num1038 / num1037);
                TileRunner(genRand.Next(0, Main.maxTilesX), genRand.Next((int)GenVars.rockLayerLow, Main.maxTilesY), genRand.Next(2, 6), genRand.Next(2, 40), 0);
            }
            if (remixWorldGen)
            {
                for (int num1039 = 0; num1039 < Main.maxTilesX; num1039++)
                {
                    for (int num1040 = (int)Main.worldSurface + genRand.Next(-1, 3); num1040 < Main.maxTilesY; num1040++)
                    {
                        if (Main.tile[num1039, num1040].active())
{
                            if (Main.tile[num1039, num1040].type == 0)
{
                                Main.tile[num1039, num1040].type = 1;
                            }
                            else if (Main.tile[num1039, num1040].type == 1)
{
                                Main.tile[num1039, num1040].type = 0;
                            }
                        }
                    }
                }
            }
        });
        AddGenerationPass("Clay", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            progress.Message = Lang.gen[6].Value;
            for (int num1030 = 0; num1030 < (int)((double)(Main.maxTilesX * Main.maxTilesY) * 2E-05); num1030++)
            {
                TileRunner(genRand.Next(0, Main.maxTilesX), genRand.Next(0, (int)GenVars.worldSurfaceLow), genRand.Next(4, 14), genRand.Next(10, 50), 40);
            }
            progress.Set(0.25);
            if (remixWorldGen)
            {
                for (int num1031 = 0; num1031 < (int)((double)(Main.maxTilesX * Main.maxTilesY) * 7E-05); num1031++)
                {
                    TileRunner(genRand.Next(0, Main.maxTilesX), genRand.Next((int)GenVars.rockLayer - 25, Main.maxTilesY - 350), genRand.Next(8, 15), genRand.Next(5, 50), 40);
                }
            }
            else
            {
                for (int num1032 = 0; num1032 < (int)((double)(Main.maxTilesX * Main.maxTilesY) * 5E-05); num1032++)
                {
                    TileRunner(genRand.Next(0, Main.maxTilesX), genRand.Next((int)GenVars.worldSurfaceLow, (int)GenVars.worldSurfaceHigh + 1), genRand.Next(8, 14), genRand.Next(15, 45), 40);
                }
                progress.Set(0.5);
                for (int num1033 = 0; num1033 < (int)((double)(Main.maxTilesX * Main.maxTilesY) * 2E-05); num1033++)
                {
                    TileRunner(genRand.Next(0, Main.maxTilesX), genRand.Next((int)GenVars.worldSurfaceHigh, (int)GenVars.rockLayerHigh + 1), genRand.Next(8, 15), genRand.Next(5, 50), 40);
                }
            }
            progress.Set(0.75);
            for (int num1034 = 5; num1034 < Main.maxTilesX - 5; num1034++)
            {
                for (int num1035 = 1; (double)num1035 < Main.worldSurface - 1.0; num1035++)
                {
                    if (Main.tile[num1034, num1035].active())
                    {
                        for (int num1036 = num1035; num1036 < num1035 + 5; num1036++)
{
                            if (Main.tile[num1034, num1036].type == 40)
{
                                Main.tile[num1034, num1036].type = 0;
                            }
                        }
                        break;
                    }
                }
            }
        });
        AddGenerationPass("Small Holes", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            progress.Message = Lang.gen[7].Value;
            double worldSurfaceHigh2 = GenVars.worldSurfaceHigh;
            for (int num1025 = 0; num1025 < (int)((double)(Main.maxTilesX * Main.maxTilesY) * 0.0015); num1025++)
            {
                double value19 = (double)num1025 / ((double)(Main.maxTilesX * Main.maxTilesY) * 0.0015);
                progress.Set(value19);
                int type14 = -1;
                if (genRand.Next(5) == 0)
                {
                    type14 = -2;
                }
                int num1026 = genRand.Next(0, Main.maxTilesX);
                int num1027 = genRand.Next((int)GenVars.worldSurfaceHigh, Main.maxTilesY);
                if (!remixWorldGen && tenthAnniversaryWorldGen)
                {
                    while ((double)num1026 < (double)Main.maxTilesX * 0.2 && (double)num1026 > (double)Main.maxTilesX * 0.8 && (double)num1027 < GenVars.worldSurface)
                    {
                        num1026 = genRand.Next(0, Main.maxTilesX);
                        num1027 = genRand.Next((int)GenVars.worldSurfaceHigh, Main.maxTilesY);
                    }
                }
                else
                {
                    while (((num1026 < GenVars.smallHolesBeachAvoidance || num1026 > Main.maxTilesX - GenVars.smallHolesBeachAvoidance) && (double)num1027 < worldSurfaceHigh2) || ((double)num1026 > (double)Main.maxTilesX * 0.45 && (double)num1026 < (double)Main.maxTilesX * 0.55 && (double)num1027 < GenVars.worldSurface))
                    {
                        num1026 = genRand.Next(0, Main.maxTilesX);
                        num1027 = genRand.Next((int)GenVars.worldSurfaceHigh, Main.maxTilesY);
                    }
                }
                int num1028 = genRand.Next(2, 5);
                int num1029 = genRand.Next(2, 20);
                if (remixWorldGen && (double)num1027 > Main.rockLayer)
                {
                    num1028 = (int)((double)num1028 * 0.8);
                    num1029 = (int)((double)num1029 * 0.9);
                }
                TileRunner(num1026, num1027, num1028, num1029, type14);
                num1026 = genRand.Next(0, Main.maxTilesX);
                num1027 = genRand.Next((int)GenVars.worldSurfaceHigh, Main.maxTilesY);
                while (((num1026 < GenVars.smallHolesBeachAvoidance || num1026 > Main.maxTilesX - GenVars.smallHolesBeachAvoidance) && (double)num1027 < worldSurfaceHigh2) || ((double)num1026 > (double)Main.maxTilesX * 0.45 && (double)num1026 < (double)Main.maxTilesX * 0.55 && (double)num1027 < GenVars.worldSurface))
                {
                    num1026 = genRand.Next(0, Main.maxTilesX);
                    num1027 = genRand.Next((int)GenVars.worldSurfaceHigh, Main.maxTilesY);
                }
                num1028 = genRand.Next(8, 15);
                num1029 = genRand.Next(7, 30);
                if (remixWorldGen && (double)num1027 > Main.rockLayer)
                {
                    num1028 = (int)((double)num1028 * 0.7);
                    num1029 = (int)((double)num1029 * 0.9);
                }
                TileRunner(num1026, num1027, num1028, num1029, type14);
            }
        });
        AddGenerationPass("Dirt Layer Caves", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            progress.Message = Lang.gen[8].Value;
            double worldSurfaceHigh = GenVars.worldSurfaceHigh;
            int num1019 = (int)((double)(Main.maxTilesX * Main.maxTilesY) * 3E-05);
            if (remixWorldGen)
            {
                num1019 *= 2;
            }
            for (int num1020 = 0; num1020 < num1019; num1020++)
            {
                double value18 = (double)num1020 / (double)num1019;
                progress.Set(value18);
                if (GenVars.rockLayerHigh <= (double)Main.maxTilesY)
                {
                    int type13 = -1;
                    if (genRand.Next(6) == 0)
                    {
                        type13 = -2;
                    }
                    int num1021 = genRand.Next(0, Main.maxTilesX);
                    int num1022 = genRand.Next((int)GenVars.worldSurfaceLow, (int)GenVars.rockLayerHigh + 1);
                    while (((num1021 < GenVars.smallHolesBeachAvoidance || num1021 > Main.maxTilesX - GenVars.smallHolesBeachAvoidance) && (double)num1022 < worldSurfaceHigh) || ((double)num1021 >= (double)Main.maxTilesX * 0.45 && (double)num1021 <= (double)Main.maxTilesX * 0.55 && (double)num1022 < Main.worldSurface))
                    {
                        num1021 = genRand.Next(0, Main.maxTilesX);
                        num1022 = genRand.Next((int)GenVars.worldSurfaceLow, (int)GenVars.rockLayerHigh + 1);
                    }
                    int num1023 = genRand.Next(5, 15);
                    int num1024 = genRand.Next(30, 200);
                    if (remixWorldGen)
                    {
                        num1023 = (int)((double)num1023 * 1.1);
                        num1024 = (int)((double)num1024 * 1.9);
                    }
                    TileRunner(num1021, num1022, num1023, num1024, type13);
                }
            }
        });
        AddGenerationPass("Rock Layer Caves", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            progress.Message = Lang.gen[9].Value;
            int num1011 = (int)((double)(Main.maxTilesX * Main.maxTilesY) * 0.00013);
            if (remixWorldGen)
            {
                num1011 = (int)((double)num1011 * 1.1);
            }
            for (int num1012 = 0; num1012 < num1011; num1012++)
            {
                double value17 = (double)num1012 / (double)num1011;
                progress.Set(value17);
                if (GenVars.rockLayerHigh <= (double)Main.maxTilesY)
                {
                    int type11 = -1;
                    if (genRand.Next(10) == 0)
                    {
                        type11 = -2;
                    }
                    int num1013 = genRand.Next(6, 20);
                    int num1014 = genRand.Next(50, 300);
                    if (remixWorldGen)
                    {
                        num1013 = (int)((double)num1013 * 0.7);
                        num1014 = (int)((double)num1014 * 0.7);
                    }
                    TileRunner(genRand.Next(0, Main.maxTilesX), genRand.Next((int)GenVars.rockLayerHigh, Main.maxTilesY), num1013, num1014, type11);
                }
            }
            if (remixWorldGen)
            {
                num1011 = (int)((double)(Main.maxTilesX * Main.maxTilesY) * 0.00013 * 0.4);
                for (int num1015 = 0; num1015 < num1011; num1015++)
                {
                    if (GenVars.rockLayerHigh <= (double)Main.maxTilesY)
                    {
                        int type12 = -1;
                        if (genRand.Next(10) == 0)
{
                            type12 = -2;
                        }
                        int num1016 = genRand.Next(7, 26);
                        int steps = genRand.Next(50, 200);
                        double num1017 = (double)genRand.Next(100, 221) * 0.1;
                        double num1018 = (double)genRand.Next(-10, 11) * 0.02;
                        int i5 = genRand.Next(0, Main.maxTilesX);
                        int j7 = genRand.Next((int)GenVars.rockLayerHigh, Main.maxTilesY);
                        TileRunner(i5, j7, num1016, steps, type12, addTile: false, num1017, num1018, noYChange: true);
                        TileRunner(i5, j7, num1016, steps, type12, addTile: false, 0.0 - num1017, 0.0 - num1018, noYChange: true);
                    }
                }
            }
        });
        AddGenerationPass("Surface Caves", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            progress.Message = Lang.gen[10].Value;
            int num992 = (int)((double)Main.maxTilesX * 0.002);
            int num993 = (int)((double)Main.maxTilesX * 0.0007);
            int num994 = (int)((double)Main.maxTilesX * 0.0003);
            if (remixWorldGen)
            {
                num992 *= 3;
                num993 *= 3;
                num994 *= 3;
            }
            for (int num995 = 0; num995 < num992; num995++)
            {
                int num996 = genRand.Next(0, Main.maxTilesX);
                while (((double)num996 > (double)Main.maxTilesX * 0.45 && (double)num996 < (double)Main.maxTilesX * 0.55) || num996 < GenVars.leftBeachEnd + 20 || num996 > GenVars.rightBeachStart - 20)
                {
                    num996 = genRand.Next(0, Main.maxTilesX);
                }
                for (int num997 = 0; (double)num997 < GenVars.worldSurfaceHigh; num997++)
                {
                    if (Main.tile[num996, num997].active())
                    {
                        TileRunner(num996, num997, genRand.Next(3, 6), genRand.Next(5, 50), -1, addTile: false, (double)genRand.Next(-10, 11) * 0.1, 1.0);
                        break;
                    }
                }
            }
            progress.Set(0.2);
            for (int num998 = 0; num998 < num993; num998++)
            {
                int num999 = genRand.Next(0, Main.maxTilesX);
                while (((double)num999 > (double)Main.maxTilesX * 0.43 && (double)num999 < (double)Main.maxTilesX * 0.5700000000000001) || num999 < GenVars.leftBeachEnd + 20 || num999 > GenVars.rightBeachStart - 20)
                {
                    num999 = genRand.Next(0, Main.maxTilesX);
                }
                for (int num1000 = 0; (double)num1000 < GenVars.worldSurfaceHigh; num1000++)
                {
                    if (Main.tile[num999, num1000].active())
                    {
                        TileRunner(num999, num1000, genRand.Next(10, 15), genRand.Next(50, 130), -1, addTile: false, (double)genRand.Next(-10, 11) * 0.1, 2.0);
                        break;
                    }
                }
            }
            progress.Set(0.4);
            for (int num1001 = 0; num1001 < num994; num1001++)
            {
                int num1002 = genRand.Next(0, Main.maxTilesX);
                while (((double)num1002 > (double)Main.maxTilesX * 0.4 && (double)num1002 < (double)Main.maxTilesX * 0.6) || num1002 < GenVars.leftBeachEnd + 20 || num1002 > GenVars.rightBeachStart - 20)
                {
                    num1002 = genRand.Next(0, Main.maxTilesX);
                }
                for (int num1003 = 0; (double)num1003 < GenVars.worldSurfaceHigh; num1003++)
                {
                    if (Main.tile[num1002, num1003].active())
                    {
                        TileRunner(num1002, num1003, genRand.Next(12, 25), genRand.Next(150, 500), -1, addTile: false, (double)genRand.Next(-10, 11) * 0.1, 4.0);
                        TileRunner(num1002, num1003, genRand.Next(8, 17), genRand.Next(60, 200), -1, addTile: false, (double)genRand.Next(-10, 11) * 0.1, 2.0);
                        TileRunner(num1002, num1003, genRand.Next(5, 13), genRand.Next(40, 170), -1, addTile: false, (double)genRand.Next(-10, 11) * 0.1, 2.0);
                        break;
                    }
                }
            }
            progress.Set(0.6);
            for (int num1004 = 0; num1004 < (int)((double)Main.maxTilesX * 0.0004); num1004++)
            {
                int num1005 = genRand.Next(0, Main.maxTilesX);
                while (((double)num1005 > (double)Main.maxTilesX * 0.4 && (double)num1005 < (double)Main.maxTilesX * 0.6) || num1005 < GenVars.leftBeachEnd + 20 || num1005 > GenVars.rightBeachStart - 20)
                {
                    num1005 = genRand.Next(0, Main.maxTilesX);
                }
                for (int num1006 = 0; (double)num1006 < GenVars.worldSurfaceHigh; num1006++)
                {
                    if (Main.tile[num1005, num1006].active())
                    {
                        TileRunner(num1005, num1006, genRand.Next(7, 12), genRand.Next(150, 250), -1, addTile: false, 0.0, 1.0, noYChange: true);
                        break;
                    }
                }
            }
            progress.Set(0.8);
            double num1007 = (double)Main.maxTilesX / 4200.0;
            for (int num1008 = 0; (double)num1008 < 5.0 * num1007; num1008++)
            {
                try
                {
                    int num1009 = (int)Main.rockLayer;
                    int num1010 = Main.maxTilesY - 400;
                    if (num1009 >= num1010)
                    {
                        num1009 = num1010 - 1;
                    }
                    Caverer(genRand.Next(GenVars.surfaceCavesBeachAvoidance2, Main.maxTilesX - GenVars.surfaceCavesBeachAvoidance2), genRand.Next(num1009, num1010));
                }
                catch
                {
                }
            }
        });
        AddGenerationPass("Wavy Caves", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            if (dontStarveWorldGen)
            {
                progress.Message = Language.GetTextValue("WorldGeneration.WavyCaves");
                double num983 = (double)Main.maxTilesX / 4200.0;
                num983 *= num983;
                int num984 = (int)(35.0 * num983);
                if (Main.remixWorld)
                {
                    num984 /= 3;
                }
                int num985 = 0;
                int num986 = 80;
                for (int num987 = 0; num987 < num984; num987++)
                {
                    double num988 = (double)num987 / (double)(num984 - 1);
                    progress.Set(num988);
                    int num989 = genRand.Next((int)Main.worldSurface + 100, Main.UnderworldLayer - 100);
                    int num990 = 0;
                    while (Math.Abs(num989 - num985) < num986)
                    {
                        num990++;
                        if (num990 > 100)
{
                            break;
                        }
                        num989 = genRand.Next((int)Main.worldSurface + 100, Main.UnderworldLayer - 100);
                    }
                    num985 = num989;
                    int num991 = 80;
                    int startX = num991 + (int)((double)(Main.maxTilesX - num991 * 2) * num988);
                    try
                    {
                        WavyCaverer(startX, num989, 12 + genRand.Next(3, 6), 0.25 + genRand.NextDouble(), genRand.Next(300, 500), -1);
                    }
                    catch
                    {
                    }
                }
            }
        });
        AddGenerationPass("Generate Ice Biome", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            progress.Message = Lang.gen[56].Value;
            GenVars.snowTop = (int)Main.worldSurface;
            int num975 = GenVars.lavaLine - genRand.Next(160, 200);
            int num976 = GenVars.lavaLine;
            if (remixWorldGen)
            {
                num976 = Main.maxTilesY - 250;
                num975 = num976 - genRand.Next(160, 200);
            }
            int num977 = GenVars.snowOriginLeft;
            int num978 = GenVars.snowOriginRight;
            int num979 = 10;
            for (int num980 = 0; num980 <= num976 - 140; num980++)
            {
                progress.Set((double)num980 / (double)(num976 - 140));
                num977 += genRand.Next(-4, 4);
                num978 += genRand.Next(-3, 5);
                if (num980 > 0)
                {
                    num977 = (num977 + GenVars.snowMinX[num980 - 1]) / 2;
                    num978 = (num978 + GenVars.snowMaxX[num980 - 1]) / 2;
                }
                if (GenVars.dungeonSide > 0)
                {
                    if (genRand.Next(4) == 0)
                    {
                        num977++;
                        num978++;
                    }
                }
                else if (genRand.Next(4) == 0)
                {
                    num977--;
                    num978--;
                }
                GenVars.snowMinX[num980] = num977;
                GenVars.snowMaxX[num980] = num978;
                for (int num981 = num977; num981 < num978; num981++)
                {
                    if (num980 < num975)
                    {
                        if (Main.tile[num981, num980].wall == 2)
{
                            Main.tile[num981, num980].wall = 40;
                        }
                        switch (Main.tile[num981, num980].type)
{
                        case 0:
                        case 2:
                        case 23:
                        case 40:
                        case 53:
                            Main.tile[num981, num980].type = 147;
                            break;
                        case 1:
                            Main.tile[num981, num980].type = 161;
                            break;
                        }
                    }
                    else
                    {
                        num979 += genRand.Next(-3, 4);
                        if (genRand.Next(3) == 0)
{
                            num979 += genRand.Next(-4, 5);
                            if (genRand.Next(3) == 0)
{
                                num979 += genRand.Next(-6, 7);
                            }
                        }
                        if (num979 < 0)
{
                            num979 = genRand.Next(3);
                        }
                        else if (num979 > 50)
{
                            num979 = 50 - genRand.Next(3);
                        }
                        for (int num982 = num980; num982 < num980 + num979; num982++)
{
                            if (Main.tile[num981, num982].wall == 2)
{
                                Main.tile[num981, num982].wall = 40;
                            }
                            switch (Main.tile[num981, num982].type)
{
                            case 0:
                            case 2:
                            case 23:
                            case 40:
                            case 53:
                                Main.tile[num981, num982].type = 147;
                                break;
                            case 1:
                                Main.tile[num981, num982].type = 161;
                                break;
                            }
                        }
                    }
                }
                if (GenVars.snowBottom < num980)
                {
                    GenVars.snowBottom = num980;
                }
            }
        });
        AddGenerationPass("Grass", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            double num971 = (double)(Main.maxTilesX * Main.maxTilesY) * 0.002;
            for (int num972 = 0; (double)num972 < num971; num972++)
            {
                progress.Set((double)num972 / num971);
                int num973 = genRand.Next(1, Main.maxTilesX - 1);
                int num974 = genRand.Next((int)GenVars.worldSurfaceLow, (int)GenVars.worldSurfaceHigh);
                if (num974 >= Main.maxTilesY)
                {
                    num974 = Main.maxTilesY - 2;
                }
                if (Main.tile[num973 - 1, num974].active() && Main.tile[num973 - 1, num974].type == 0 && Main.tile[num973 + 1, num974].active() && Main.tile[num973 + 1, num974].type == 0 && Main.tile[num973, num974 - 1].active() && Main.tile[num973, num974 - 1].type == 0 && Main.tile[num973, num974 + 1].active() && Main.tile[num973, num974 + 1].type == 0)
                {
                    Main.tile[num973, num974].active(active: true);
                    Main.tile[num973, num974].type = 2;
                }
                num973 = genRand.Next(1, Main.maxTilesX - 1);
                num974 = genRand.Next(0, (int)GenVars.worldSurfaceLow);
                if (num974 >= Main.maxTilesY)
                {
                    num974 = Main.maxTilesY - 2;
                }
                if (Main.tile[num973 - 1, num974].active() && Main.tile[num973 - 1, num974].type == 0 && Main.tile[num973 + 1, num974].active() && Main.tile[num973 + 1, num974].type == 0 && Main.tile[num973, num974 - 1].active() && Main.tile[num973, num974 - 1].type == 0 && Main.tile[num973, num974 + 1].active() && Main.tile[num973, num974 + 1].type == 0)
                {
                    Main.tile[num973, num974].active(active: true);
                    Main.tile[num973, num974].type = 2;
                }
            }
        });
        AddGenerationPass(new JunglePass());
        AddGenerationPass("Mud Caves To Grass", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            progress.Message = Lang.gen[77].Value;
            NotTheBees();
            for (int num966 = 0; num966 < Main.maxTilesX; num966++)
            {
                for (int num967 = 0; num967 < Main.maxTilesY; num967++)
                {
                    if (Main.tile[num966, num967].active())
                    {
                        grassSpread = 0;
                        SpreadGrass(num966, num967, 59, 60);
                    }
                    progress.Set(0.2 * ((double)(num966 * Main.maxTilesY + num967) / (double)(Main.maxTilesX * Main.maxTilesY)));
                }
            }
            SmallConsecutivesFound = 0;
            SmallConsecutivesEliminated = 0;
            double num968 = Main.maxTilesX - 20;
            for (int num969 = 10; num969 < Main.maxTilesX - 10; num969++)
            {
                ScanTileColumnAndRemoveClumps(num969);
                double num970 = (double)(num969 - 10) / num968;
                progress.Set(0.2 + num970 * 0.8);
            }
        });
        AddGenerationPass("Full Desert", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            progress.Message = Lang.gen[78].Value;
            Main.tileSolid[484] = false;
            int num958 = 0;
            int num959 = GenVars.dungeonSide;
            int num960 = Main.maxTilesX / 2;
            int num961 = genRand.Next(num960) / 8;
            num961 += num960 / 8;
            int x16 = num960 + num961 * -num959;
            int num962 = 0;
            DesertBiome desertBiome = GenVars.configuration.CreateBiome<DesertBiome>();
            while (!desertBiome.Place(new Point(x16, (int)GenVars.worldSurfaceHigh + 25), GenVars.structures))
            {
                num961 = genRand.Next(num960) / 2;
                num961 += num960 / 8;
                num961 += genRand.Next(num962 / 12);
                x16 = num960 + num961 * -num959;
                if (++num962 > Main.maxTilesX / 4)
                {
                    num959 *= -1;
                    num962 = 0;
                    num958++;
                    if (num958 >= 2)
                    {
                        GenVars.skipDesertTileCheck = true;
                    }
                }
            }
            if (remixWorldGen)
            {
                for (int num963 = 50; num963 < Main.maxTilesX - 50; num963++)
                {
                    for (int num964 = (int)Main.rockLayer + genRand.Next(-1, 2); num964 < Main.maxTilesY - 50; num964++)
                    {
                        if ((Main.tile[num963, num964].type == 396 || Main.tile[num963, num964].type == 397 || Main.tile[num963, num964].type == 53) && !SolidTile(num963, num964 - 1))
{
                            for (int num965 = num964; num965 < num964 + genRand.Next(4, 7) && Main.tile[num963, num965 + 1].active() && (Main.tile[num963, num965].type == 396 || Main.tile[num963, num965].type == 397); num965++)
{
                                Main.tile[num963, num965].type = 53;
                            }
                        }
                    }
                }
            }
        });
        AddGenerationPass("Floating Islands", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            GenVars.numIslandHouses = 0;
            GenVars.skyIslandHouseCount = 0;
            progress.Message = Lang.gen[12].Value;
            int num948 = (int)((double)Main.maxTilesX * 0.0008);
            int num949 = 0;
            double num950 = num948 + GenVars.skyLakes;
            for (int num951 = 0; (double)num951 < num950; num951++)
            {
                progress.Set((double)num951 / num950);
                int num952 = Main.maxTilesX;
                while (--num952 > 0)
                {
                    bool flag57 = true;
                    int num953 = genRand.Next((int)((double)Main.maxTilesX * 0.1), (int)((double)Main.maxTilesX * 0.9));
                    while (num953 > Main.maxTilesX / 2 - 150 && num953 < Main.maxTilesX / 2 + 150)
                    {
                        num953 = genRand.Next((int)((double)Main.maxTilesX * 0.1), (int)((double)Main.maxTilesX * 0.9));
                    }
                    for (int num954 = 0; num954 < GenVars.numIslandHouses; num954++)
                    {
                        if (num953 > GenVars.floatingIslandHouseX[num954] - 180 && num953 < GenVars.floatingIslandHouseX[num954] + 180)
{
                            flag57 = false;
                            break;
                        }
                    }
                    if (flag57)
                    {
                        flag57 = false;
                        int num955 = 0;
                        for (int num956 = 200; (double)num956 < Main.worldSurface; num956++)
{
                            if (Main.tile[num953, num956].active())
{
                                num955 = num956;
                                flag57 = true;
                                break;
                            }
                        }
                        if (flag57)
{
                            int num957 = 0;
                            num952 = -1;
                            int val = genRand.Next(90, num955 - 100);
                            val = Math.Min(val, (int)GenVars.worldSurfaceLow - 50);
                            if (num949 >= num948)
{
                                GenVars.skyLake[GenVars.numIslandHouses] = true;
                                CloudLake(num953, val);
                            }
                            else
{
                                GenVars.skyLake[GenVars.numIslandHouses] = false;
                                if (drunkWorldGen && !remixWorldGen)
{
                                    if (genRand.Next(2) == 0)
{
                                        num957 = 3;
                                        SnowCloudIsland(num953, val);
                                    }
                                    else
{
                                        num957 = 1;
                                        DesertCloudIsland(num953, val);
                                    }
                                }
                                else
{
                                    if (remixWorldGen && drunkWorldGen)
{
                                        num957 = ((GenVars.crimsonLeft && num953 < Main.maxTilesX / 2) ? 5 : ((GenVars.crimsonLeft || num953 <= Main.maxTilesX / 2) ? 4 : 5));
                                    }
                                    else if (getGoodWorldGen || remixWorldGen)
{
                                        num957 = ((!crimson) ? 4 : 5);
                                    }
                                    else if (Main.tenthAnniversaryWorld)
{
                                        num957 = 6;
                                    }
                                    CloudIsland(num953, val);
                                }
                            }
                            GenVars.floatingIslandHouseX[GenVars.numIslandHouses] = num953;
                            GenVars.floatingIslandHouseY[GenVars.numIslandHouses] = val;
                            GenVars.floatingIslandStyle[GenVars.numIslandHouses] = num957;
                            GenVars.numIslandHouses++;
                            num949++;
                        }
                    }
                }
            }
        });
        AddGenerationPass("Mushroom Patches", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            //IL_0287: Unknown result type (might be due to invalid IL or missing references)
            //IL_0292: Unknown result type (might be due to invalid IL or missing references)
            progress.Message = Lang.gen[13].Value;
            if (remixWorldGen)
            {
                for (int num927 = 10; num927 < Main.maxTilesX - 10; num927++)
                {
                    for (int num928 = Main.maxTilesY + genRand.Next(3) - 350; num928 < Main.maxTilesY - 10; num928++)
                    {
                        if (Main.tile[num927, num928].type == 0)
{
                            Main.tile[num927, num928].type = 59;
                        }
                    }
                }
            }
            double num929 = (double)Main.maxTilesX / 700.0;
            if (num929 > (double)GenVars.maxMushroomBiomes)
            {
                num929 = GenVars.maxMushroomBiomes;
            }
            for (int num930 = 0; (double)num930 < num929; num930++)
            {
                int num931 = 0;
                bool flag56 = true;
                while (flag56)
                {
                    int num932 = genRand.Next((int)((double)Main.maxTilesX * 0.2), (int)((double)Main.maxTilesX * 0.8));
                    if (num931 > Main.maxTilesX / 4)
                    {
                        num932 = genRand.Next((int)((double)Main.maxTilesX * 0.25), (int)((double)Main.maxTilesX * 0.975));
                    }
                    int num933 = ((!remixWorldGen) ? genRand.Next((int)Main.rockLayer + 50, Main.maxTilesY - 300) : genRand.Next((int)Main.worldSurface + 50, (int)Main.rockLayer - 50));
                    flag56 = false;
                    int num934 = 100;
                    int num935 = 500;
                    for (int num936 = num932 - num934; num936 < num932 + num934; num936 += 3)
                    {
                        for (int num937 = num933 - num934; num937 < num933 + num934; num937 += 3)
{
                            if (InWorld(num936, num937))
{
                                if (Main.tile[num936, num937].type == 147 || Main.tile[num936, num937].type == 161 || Main.tile[num936, num937].type == 162 || Main.tile[num936, num937].type == 60 || Main.tile[num936, num937].type == 368 || Main.tile[num936, num937].type == 367)
{
                                    flag56 = true;
                                    break;
                                }
                                if (GenVars.UndergroundDesertLocation.Contains(new Point(num936, num937)))
{
                                    flag56 = true;
                                    break;
                                }
                            }
                            else
{
                                flag56 = true;
                            }
                        }
                    }
                    if (!flag56)
                    {
                        for (int num938 = 0; num938 < GenVars.numMushroomBiomes; num938++)
{
                            if (Vector2D.Distance(GenVars.mushroomBiomesPosition[num938].ToVector2D(), new Vector2D((double)num932, (double)num933)) < (double)num935)
{
                                flag56 = true;
                            }
                        }
                    }
                    if (!flag56 && GenVars.numMushroomBiomes < GenVars.maxMushroomBiomes)
                    {
                        ShroomPatch(num932, num933);
                        for (int num939 = 0; num939 < 5; num939++)
{
                            int i4 = num932 + genRand.Next(-40, 41);
                            int j6 = num933 + genRand.Next(-40, 41);
                            ShroomPatch(i4, j6);
                        }
                        GenVars.mushroomBiomesPosition[GenVars.numMushroomBiomes].X = num932;
                        GenVars.mushroomBiomesPosition[GenVars.numMushroomBiomes].Y = num933;
                        GenVars.numMushroomBiomes++;
                    }
                    num931++;
                    if (num931 > Main.maxTilesX / 2)
                    {
                        break;
                    }
                }
            }
            for (int num940 = 0; num940 < Main.maxTilesX; num940++)
            {
                progress.Set((double)num940 / (double)Main.maxTilesX);
                for (int num941 = (int)Main.worldSurface; num941 < Main.maxTilesY; num941++)
                {
                    if (InWorld(num940, num941, 50) && Main.tile[num940, num941].active())
                    {
                        grassSpread = 0;
                        SpreadGrass(num940, num941, 59, 70, repeat: false);
                    }
                }
            }
            for (int num942 = 0; num942 < Main.maxTilesX; num942++)
            {
                for (int num943 = (int)Main.worldSurface; num943 < Main.maxTilesY; num943++)
                {
                    if (Main.tile[num942, num943].active() && Main.tile[num942, num943].type == 70)
                    {
                        int type10 = 59;
                        for (int num944 = num942 - 1; num944 <= num942 + 1; num944++)
{
                            for (int num945 = num943 - 1; num945 <= num943 + 1; num945++)
{
                                if (Main.tile[num944, num945].active())
{
                                    if (!Main.tile[num944 - 1, num945].active() && !Main.tile[num944 + 1, num945].active())
{
                                        KillTile(num944, num945);
                                    }
                                    else if (!Main.tile[num944, num945 - 1].active() && !Main.tile[num944, num945 + 1].active())
{
                                        KillTile(num944, num945);
                                    }
                                }
                                else if (Main.tile[num944 - 1, num945].active() && Main.tile[num944 + 1, num945].active())
{
                                    PlaceTile(num944, num945, type10);
                                    if (Main.tile[num944 - 1, num943].type == 70)
{
                                        Main.tile[num944 - 1, num943].type = 59;
                                    }
                                    if (Main.tile[num944 + 1, num943].type == 70)
{
                                        Main.tile[num944 + 1, num943].type = 59;
                                    }
                                }
                                else if (Main.tile[num944, num945 - 1].active() && Main.tile[num944, num945 + 1].active())
{
                                    PlaceTile(num944, num945, type10);
                                    if (Main.tile[num944, num943 - 1].type == 70)
{
                                        Main.tile[num944, num943 - 1].type = 59;
                                    }
                                    if (Main.tile[num944, num943 + 1].type == 70)
{
                                        Main.tile[num944, num943 + 1].type = 59;
                                    }
                                }
                            }
                        }
                        if (genRand.Next(4) == 0)
{
                            int num946 = num942 + genRand.Next(-20, 21);
                            int num947 = num943 + genRand.Next(-20, 21);
                            if (InWorld(num946, num947) && Main.tile[num946, num947].type == 59)
{
                                Main.tile[num946, num947].type = 70;
                            }
                        }
                    }
                }
            }
        });
        AddGenerationPass("Marble", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            progress.Message = Lang.gen[80].Value;
            int num922 = passConfig.Get<WorldGenRange>("Count").GetRandom(genRand);
            double num923 = (double)(Main.maxTilesX - 160) / (double)num922;
            MarbleBiome marbleBiome = GenVars.configuration.CreateBiome<MarbleBiome>();
            int num924 = 0;
            int num925 = 0;
            while (num925 < num922)
            {
                double num926 = (double)num925 / (double)num922;
                progress.Set(num926);
                Point origin4 = RandomRectanglePoint((int)(num926 * (double)(Main.maxTilesX - 160)) + 80, (int)GenVars.rockLayer + 20, (int)num923, Main.maxTilesY - ((int)GenVars.rockLayer + 40) - 200);
                if (remixWorldGen)
                {
                    origin4 = RandomRectanglePoint((int)(num926 * (double)(Main.maxTilesX - 160)) + 80, (int)GenVars.worldSurface + 100, (int)num923, (int)GenVars.rockLayer - (int)GenVars.worldSurface - 100);
                }
                while ((double)origin4.X > (double)Main.maxTilesX * 0.45 && (double)origin4.X < (double)Main.maxTilesX * 0.55)
                {
                    origin4.X = genRand.Next(beachDistance, Main.maxTilesX - beachDistance);
                }
                num924++;
                if (marbleBiome.Place(origin4, GenVars.structures))
                {
                    num925++;
                    num924 = 0;
                }
                else if (num924 > Main.maxTilesX * 10)
                {
                    num922 = num925;
                    num925++;
                    num924 = 0;
                }
            }
        });
        AddGenerationPass("Granite", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            progress.Message = Lang.gen[81].Value;
            int num916 = passConfig.Get<WorldGenRange>("Count").GetRandom(genRand);
            double num917 = (double)(Main.maxTilesX - 200) / (double)num916;
            List<Point> list2 = new List<Point>(num916);
            int num918 = 0;
            int num919 = 0;
            while (num919 < num916)
            {
                double num920 = (double)num919 / (double)num916;
                progress.Set(num920);
                Point point3 = RandomRectanglePoint((int)(num920 * (double)(Main.maxTilesX - 200)) + 100, (int)GenVars.rockLayer + 20, (int)num917, Main.maxTilesY - ((int)GenVars.rockLayer + 40) - 200);
                if (remixWorldGen)
                {
                    point3 = RandomRectanglePoint((int)(num920 * (double)(Main.maxTilesX - 200)) + 100, (int)GenVars.worldSurface + 100, (int)num917, (int)GenVars.rockLayer - (int)GenVars.worldSurface - 100);
                }
                while ((double)point3.X > (double)Main.maxTilesX * 0.45 && (double)point3.X < (double)Main.maxTilesX * 0.55)
                {
                    point3.X = genRand.Next(beachDistance, Main.maxTilesX - beachDistance);
                }
                num918++;
                if (GraniteBiome.CanPlace(point3, GenVars.structures))
                {
                    list2.Add(point3);
                    num919++;
                }
                else if (num918 > Main.maxTilesX * 10)
                {
                    num916 = num919;
                    num919++;
                    num918 = 0;
                }
            }
            GraniteBiome graniteBiome = GenVars.configuration.CreateBiome<GraniteBiome>();
            for (int num921 = 0; num921 < num916; num921++)
            {
                graniteBiome.Place(list2[num921], GenVars.structures);
            }
        });
        AddGenerationPass("Dirt To Mud", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            progress.Message = Lang.gen[14].Value;
            double num914 = (double)(Main.maxTilesX * Main.maxTilesY) * 0.001;
            for (int num915 = 0; (double)num915 < num914; num915++)
            {
                progress.Set((double)num915 / num914);
                if (remixWorldGen)
                {
                    TileRunner(genRand.Next(0, Main.maxTilesX), genRand.Next((int)Main.worldSurface, (int)GenVars.rockLayerLow), genRand.Next(2, 6), genRand.Next(2, 40), 59, addTile: false, 0.0, 0.0, noYChange: false, overRide: true, 53);
                }
                else
                {
                    TileRunner(genRand.Next(0, Main.maxTilesX), genRand.Next((int)GenVars.rockLayerLow, Main.maxTilesY), genRand.Next(2, 6), genRand.Next(2, 40), 59, addTile: false, 0.0, 0.0, noYChange: false, overRide: true, 53);
                }
            }
        });
        AddGenerationPass("Silt", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            progress.Message = Lang.gen[15].Value;
            for (int num908 = 0; num908 < (int)((double)(Main.maxTilesX * Main.maxTilesY) * 0.0001); num908++)
            {
                int num909 = genRand.Next(0, Main.maxTilesX);
                int num910 = genRand.Next((int)GenVars.rockLayerHigh, Main.maxTilesY);
                if (remixWorldGen)
                {
                    num910 = genRand.Next((int)Main.worldSurface, (int)Main.rockLayer);
                }
                if (Main.tile[num909, num910].wall != 187 && Main.tile[num909, num910].wall != 216)
                {
                    TileRunner(num909, num910, genRand.Next(5, 12), genRand.Next(15, 50), 123);
                }
            }
            for (int num911 = 0; num911 < (int)((double)(Main.maxTilesX * Main.maxTilesY) * 0.0005); num911++)
            {
                int num912 = genRand.Next(0, Main.maxTilesX);
                int num913 = genRand.Next((int)GenVars.rockLayerHigh, Main.maxTilesY);
                if (remixWorldGen)
                {
                    num913 = genRand.Next((int)Main.worldSurface, (int)Main.rockLayer);
                }
                if (Main.tile[num912, num913].wall != 187 && Main.tile[num912, num913].wall != 216)
                {
                    TileRunner(num912, num913, genRand.Next(2, 5), genRand.Next(2, 5), 123);
                }
            }
        });
        AddGenerationPass("Shinies", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            progress.Message = Lang.gen[16].Value;
            if (remixWorldGen)
            {
                for (int num878 = 0; num878 < (int)((double)(Main.maxTilesX * Main.maxTilesY) * 6E-05); num878++)
                {
                    if (drunkWorldGen)
                    {
                        if (genRand.Next(2) == 0)
{
                            GenVars.copper = 7;
                        }
                        else
{
                            GenVars.copper = 166;
                        }
                    }
                    TileRunner(genRand.Next(0, Main.maxTilesX), genRand.Next((int)GenVars.worldSurfaceLow, (int)GenVars.worldSurfaceHigh), genRand.Next(3, 6), genRand.Next(2, 6), GenVars.copper);
                }
                for (int num879 = 0; num879 < (int)((double)(Main.maxTilesX * Main.maxTilesY) * 8E-05); num879++)
                {
                    if (drunkWorldGen)
                    {
                        if (genRand.Next(2) == 0)
{
                            GenVars.copper = 7;
                        }
                        else
{
                            GenVars.copper = 166;
                        }
                    }
                    TileRunner(genRand.Next(0, Main.maxTilesX), genRand.Next((int)GenVars.worldSurfaceHigh, (int)GenVars.rockLayerHigh), genRand.Next(3, 7), genRand.Next(3, 7), GenVars.copper);
                }
                for (int num880 = 0; num880 < (int)((double)(Main.maxTilesX * Main.maxTilesY) * 0.0002); num880++)
                {
                    if (drunkWorldGen)
                    {
                        if (genRand.Next(2) == 0)
{
                            GenVars.copper = 7;
                        }
                        else
{
                            GenVars.copper = 166;
                        }
                    }
                    TileRunner(genRand.Next(0, Main.maxTilesX), genRand.Next((int)GenVars.rockLayerLow, Main.maxTilesY), genRand.Next(4, 9), genRand.Next(4, 8), GenVars.copper);
                }
                for (int num881 = 0; num881 < (int)((double)(Main.maxTilesX * Main.maxTilesY) * 3E-05); num881++)
                {
                    if (drunkWorldGen)
                    {
                        if (genRand.Next(2) == 0)
{
                            GenVars.iron = 6;
                        }
                        else
{
                            GenVars.iron = 167;
                        }
                    }
                    TileRunner(genRand.Next(0, Main.maxTilesX), genRand.Next((int)GenVars.worldSurfaceLow, (int)GenVars.worldSurfaceHigh), genRand.Next(3, 7), genRand.Next(2, 5), GenVars.iron);
                }
                for (int num882 = 0; num882 < (int)((double)(Main.maxTilesX * Main.maxTilesY) * 8E-05); num882++)
                {
                    if (drunkWorldGen)
                    {
                        if (genRand.Next(2) == 0)
{
                            GenVars.iron = 6;
                        }
                        else
{
                            GenVars.iron = 167;
                        }
                    }
                    TileRunner(genRand.Next(0, Main.maxTilesX), genRand.Next((int)GenVars.worldSurfaceHigh, (int)GenVars.rockLayerHigh), genRand.Next(3, 6), genRand.Next(3, 6), GenVars.iron);
                }
                for (int num883 = 0; num883 < (int)((double)(Main.maxTilesX * Main.maxTilesY) * 0.0002); num883++)
                {
                    if (drunkWorldGen)
                    {
                        if (genRand.Next(2) == 0)
{
                            GenVars.iron = 6;
                        }
                        else
{
                            GenVars.iron = 167;
                        }
                    }
                    TileRunner(genRand.Next(0, Main.maxTilesX), genRand.Next((int)GenVars.rockLayerLow, Main.maxTilesY), genRand.Next(4, 9), genRand.Next(4, 8), GenVars.iron);
                }
                for (int num884 = 0; num884 < (int)((double)(Main.maxTilesX * Main.maxTilesY) * 2.6E-05); num884++)
                {
                    if (drunkWorldGen)
                    {
                        if (genRand.Next(2) == 0)
{
                            GenVars.silver = 9;
                        }
                        else
{
                            GenVars.silver = 168;
                        }
                    }
                    TileRunner(genRand.Next(0, Main.maxTilesX), genRand.Next((int)Main.rockLayer - 100, Main.maxTilesY - 250), genRand.Next(3, 6), genRand.Next(3, 6), GenVars.silver);
                }
                for (int num885 = 0; num885 < (int)((double)(Main.maxTilesX * Main.maxTilesY) * 0.00015); num885++)
                {
                    if (drunkWorldGen)
                    {
                        if (genRand.Next(2) == 0)
{
                            GenVars.silver = 9;
                        }
                        else
{
                            GenVars.silver = 168;
                        }
                    }
                    TileRunner(genRand.Next(0, Main.maxTilesX), genRand.Next((int)Main.worldSurface, (int)Main.rockLayer), genRand.Next(4, 9), genRand.Next(4, 8), GenVars.silver);
                }
                for (int num886 = 0; num886 < (int)((double)(Main.maxTilesX * Main.maxTilesY) * 0.00017); num886++)
                {
                    if (drunkWorldGen)
                    {
                        if (genRand.Next(2) == 0)
{
                            GenVars.silver = 9;
                        }
                        else
{
                            GenVars.silver = 168;
                        }
                    }
                    TileRunner(genRand.Next(0, Main.maxTilesX), genRand.Next(0, (int)GenVars.worldSurfaceLow), genRand.Next(4, 9), genRand.Next(4, 8), GenVars.silver);
                }
                for (int num887 = 0; num887 < (int)((double)(Main.maxTilesX * Main.maxTilesY) * 0.00012); num887++)
                {
                    if (drunkWorldGen)
                    {
                        if (genRand.Next(2) == 0)
{
                            GenVars.gold = 8;
                        }
                        else
{
                            GenVars.gold = 169;
                        }
                    }
                    TileRunner(genRand.Next(0, Main.maxTilesX), genRand.Next((int)Main.worldSurface, (int)Main.rockLayer), genRand.Next(4, 8), genRand.Next(4, 8), GenVars.gold);
                }
                for (int num888 = 0; num888 < (int)((double)(Main.maxTilesX * Main.maxTilesY) * 0.00012); num888++)
                {
                    if (drunkWorldGen)
                    {
                        if (genRand.Next(2) == 0)
{
                            GenVars.gold = 8;
                        }
                        else
{
                            GenVars.gold = 169;
                        }
                    }
                    TileRunner(genRand.Next(0, Main.maxTilesX), genRand.Next(0, (int)GenVars.worldSurfaceLow - 20), genRand.Next(4, 8), genRand.Next(4, 8), GenVars.gold);
                }
                if (drunkWorldGen)
                {
                    for (int num889 = 0; num889 < (int)((double)(Main.maxTilesX * Main.maxTilesY) * 2.25E-05 / 2.0); num889++)
                    {
                        TileRunner(genRand.Next(0, Main.maxTilesX), genRand.Next((int)Main.rockLayer, Main.maxTilesY), genRand.Next(3, 6), genRand.Next(4, 8), 204);
                    }
                    for (int num890 = 0; num890 < (int)((double)(Main.maxTilesX * Main.maxTilesY) * 2.25E-05 / 2.0); num890++)
                    {
                        TileRunner(genRand.Next(0, Main.maxTilesX), genRand.Next((int)Main.rockLayer, Main.maxTilesY), genRand.Next(3, 6), genRand.Next(4, 8), 22);
                    }
                }
                if (crimson)
                {
                    for (int num891 = 0; num891 < (int)((double)(Main.maxTilesX * Main.maxTilesY) * 4.25E-05); num891++)
                    {
                        TileRunner(genRand.Next(0, Main.maxTilesX), genRand.Next((int)Main.worldSurface, (int)Main.rockLayer), genRand.Next(3, 6), genRand.Next(4, 8), 204);
                    }
                }
                else
                {
                    for (int num892 = 0; num892 < (int)((double)(Main.maxTilesX * Main.maxTilesY) * 4.25E-05); num892++)
                    {
                        TileRunner(genRand.Next(0, Main.maxTilesX), genRand.Next((int)Main.worldSurface, (int)Main.rockLayer), genRand.Next(3, 6), genRand.Next(4, 8), 22);
                    }
                }
            }
            else
            {
                for (int num893 = 0; num893 < (int)((double)(Main.maxTilesX * Main.maxTilesY) * 6E-05); num893++)
                {
                    if (drunkWorldGen)
                    {
                        if (genRand.Next(2) == 0)
{
                            GenVars.copper = 7;
                        }
                        else
{
                            GenVars.copper = 166;
                        }
                    }
                    TileRunner(genRand.Next(0, Main.maxTilesX), genRand.Next((int)GenVars.worldSurfaceLow, (int)GenVars.worldSurfaceHigh), genRand.Next(3, 6), genRand.Next(2, 6), GenVars.copper);
                }
                for (int num894 = 0; num894 < (int)((double)(Main.maxTilesX * Main.maxTilesY) * 8E-05); num894++)
                {
                    if (drunkWorldGen)
                    {
                        if (genRand.Next(2) == 0)
{
                            GenVars.copper = 7;
                        }
                        else
{
                            GenVars.copper = 166;
                        }
                    }
                    TileRunner(genRand.Next(0, Main.maxTilesX), genRand.Next((int)GenVars.worldSurfaceHigh, (int)GenVars.rockLayerHigh), genRand.Next(3, 7), genRand.Next(3, 7), GenVars.copper);
                }
                for (int num895 = 0; num895 < (int)((double)(Main.maxTilesX * Main.maxTilesY) * 0.0002); num895++)
                {
                    if (drunkWorldGen)
                    {
                        if (genRand.Next(2) == 0)
{
                            GenVars.copper = 7;
                        }
                        else
{
                            GenVars.copper = 166;
                        }
                    }
                    TileRunner(genRand.Next(0, Main.maxTilesX), genRand.Next((int)GenVars.rockLayerLow, Main.maxTilesY), genRand.Next(4, 9), genRand.Next(4, 8), GenVars.copper);
                }
                for (int num896 = 0; num896 < (int)((double)(Main.maxTilesX * Main.maxTilesY) * 3E-05); num896++)
                {
                    if (drunkWorldGen)
                    {
                        if (genRand.Next(2) == 0)
{
                            GenVars.iron = 6;
                        }
                        else
{
                            GenVars.iron = 167;
                        }
                    }
                    TileRunner(genRand.Next(0, Main.maxTilesX), genRand.Next((int)GenVars.worldSurfaceLow, (int)GenVars.worldSurfaceHigh), genRand.Next(3, 7), genRand.Next(2, 5), GenVars.iron);
                }
                for (int num897 = 0; num897 < (int)((double)(Main.maxTilesX * Main.maxTilesY) * 8E-05); num897++)
                {
                    if (drunkWorldGen)
                    {
                        if (genRand.Next(2) == 0)
{
                            GenVars.iron = 6;
                        }
                        else
{
                            GenVars.iron = 167;
                        }
                    }
                    TileRunner(genRand.Next(0, Main.maxTilesX), genRand.Next((int)GenVars.worldSurfaceHigh, (int)GenVars.rockLayerHigh), genRand.Next(3, 6), genRand.Next(3, 6), GenVars.iron);
                }
                for (int num898 = 0; num898 < (int)((double)(Main.maxTilesX * Main.maxTilesY) * 0.0002); num898++)
                {
                    if (drunkWorldGen)
                    {
                        if (genRand.Next(2) == 0)
{
                            GenVars.iron = 6;
                        }
                        else
{
                            GenVars.iron = 167;
                        }
                    }
                    TileRunner(genRand.Next(0, Main.maxTilesX), genRand.Next((int)GenVars.rockLayerLow, Main.maxTilesY), genRand.Next(4, 9), genRand.Next(4, 8), GenVars.iron);
                }
                for (int num899 = 0; num899 < (int)((double)(Main.maxTilesX * Main.maxTilesY) * 2.6E-05); num899++)
                {
                    if (drunkWorldGen)
                    {
                        if (genRand.Next(2) == 0)
{
                            GenVars.silver = 9;
                        }
                        else
{
                            GenVars.silver = 168;
                        }
                    }
                    TileRunner(genRand.Next(0, Main.maxTilesX), genRand.Next((int)GenVars.worldSurfaceHigh, (int)GenVars.rockLayerHigh), genRand.Next(3, 6), genRand.Next(3, 6), GenVars.silver);
                }
                for (int num900 = 0; num900 < (int)((double)(Main.maxTilesX * Main.maxTilesY) * 0.00015); num900++)
                {
                    if (drunkWorldGen)
                    {
                        if (genRand.Next(2) == 0)
{
                            GenVars.silver = 9;
                        }
                        else
{
                            GenVars.silver = 168;
                        }
                    }
                    TileRunner(genRand.Next(0, Main.maxTilesX), genRand.Next((int)GenVars.rockLayerLow, Main.maxTilesY), genRand.Next(4, 9), genRand.Next(4, 8), GenVars.silver);
                }
                for (int num901 = 0; num901 < (int)((double)(Main.maxTilesX * Main.maxTilesY) * 0.00017); num901++)
                {
                    if (drunkWorldGen)
                    {
                        if (genRand.Next(2) == 0)
{
                            GenVars.silver = 9;
                        }
                        else
{
                            GenVars.silver = 168;
                        }
                    }
                    TileRunner(genRand.Next(0, Main.maxTilesX), genRand.Next(0, (int)GenVars.worldSurfaceLow), genRand.Next(4, 9), genRand.Next(4, 8), GenVars.silver);
                }
                for (int num902 = 0; num902 < (int)((double)(Main.maxTilesX * Main.maxTilesY) * 0.00012); num902++)
                {
                    if (drunkWorldGen)
                    {
                        if (genRand.Next(2) == 0)
{
                            GenVars.gold = 8;
                        }
                        else
{
                            GenVars.gold = 169;
                        }
                    }
                    TileRunner(genRand.Next(0, Main.maxTilesX), genRand.Next((int)GenVars.rockLayerLow, Main.maxTilesY), genRand.Next(4, 8), genRand.Next(4, 8), GenVars.gold);
                }
                for (int num903 = 0; num903 < (int)((double)(Main.maxTilesX * Main.maxTilesY) * 0.00012); num903++)
                {
                    if (drunkWorldGen)
                    {
                        if (genRand.Next(2) == 0)
{
                            GenVars.gold = 8;
                        }
                        else
{
                            GenVars.gold = 169;
                        }
                    }
                    TileRunner(genRand.Next(0, Main.maxTilesX), genRand.Next(0, (int)GenVars.worldSurfaceLow - 20), genRand.Next(4, 8), genRand.Next(4, 8), GenVars.gold);
                }
                if (drunkWorldGen)
                {
                    for (int num904 = 0; num904 < (int)((double)(Main.maxTilesX * Main.maxTilesY) * 2.25E-05 / 2.0); num904++)
                    {
                        TileRunner(genRand.Next(0, Main.maxTilesX), genRand.Next((int)Main.rockLayer, Main.maxTilesY), genRand.Next(3, 6), genRand.Next(4, 8), 204);
                    }
                    for (int num905 = 0; num905 < (int)((double)(Main.maxTilesX * Main.maxTilesY) * 2.25E-05 / 2.0); num905++)
                    {
                        TileRunner(genRand.Next(0, Main.maxTilesX), genRand.Next((int)Main.rockLayer, Main.maxTilesY), genRand.Next(3, 6), genRand.Next(4, 8), 22);
                    }
                }
                if (crimson)
                {
                    for (int num906 = 0; num906 < (int)((double)(Main.maxTilesX * Main.maxTilesY) * 2.25E-05); num906++)
                    {
                        TileRunner(genRand.Next(0, Main.maxTilesX), genRand.Next((int)Main.rockLayer, Main.maxTilesY), genRand.Next(3, 6), genRand.Next(4, 8), 204);
                    }
                }
                else
                {
                    for (int num907 = 0; num907 < (int)((double)(Main.maxTilesX * Main.maxTilesY) * 2.25E-05); num907++)
                    {
                        TileRunner(genRand.Next(0, Main.maxTilesX), genRand.Next((int)Main.rockLayer, Main.maxTilesY), genRand.Next(3, 6), genRand.Next(4, 8), 22);
                    }
                }
            }
        });
        AddGenerationPass("Webs", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            progress.Message = Lang.gen[17].Value;
            for (int num874 = 0; num874 < (int)((double)(Main.maxTilesX * Main.maxTilesY) * 0.0006); num874++)
            {
                int num875 = genRand.Next(20, Main.maxTilesX - 20);
                int num876 = genRand.Next((int)GenVars.worldSurfaceHigh, Main.maxTilesY - 20);
                if (num874 < GenVars.numMCaves)
                {
                    num875 = GenVars.mCaveX[num874];
                    num876 = GenVars.mCaveY[num874];
                }
                if (!Main.tile[num875, num876].active() && ((double)num876 > Main.worldSurface || Main.tile[num875, num876].wall > 0))
                {
                    while (!Main.tile[num875, num876].active() && num876 > (int)GenVars.worldSurfaceLow)
                    {
                        num876--;
                    }
                    num876++;
                    int num877 = 1;
                    if (genRand.Next(2) == 0)
                    {
                        num877 = -1;
                    }
                    for (; !Main.tile[num875, num876].active() && num875 > 10 && num875 < Main.maxTilesX - 10; num875 += num877)
                    {
                    }
                    num875 -= num877;
                    if ((double)num876 > Main.worldSurface || Main.tile[num875, num876].wall > 0)
                    {
                        TileRunner(num875, num876, genRand.Next(4, 11), genRand.Next(2, 4), 51, addTile: true, num877, -1.0, noYChange: false, overRide: false);
                    }
                }
            }
        });
        AddGenerationPass("Underworld", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            progress.Message = Lang.gen[18].Value;
            progress.Set(0.0);
            int num838 = Main.maxTilesY - genRand.Next(150, 190);
            for (int num839 = 0; num839 < Main.maxTilesX; num839++)
            {
                num838 += genRand.Next(-3, 4);
                if (num838 < Main.maxTilesY - 190)
                {
                    num838 = Main.maxTilesY - 190;
                }
                if (num838 > Main.maxTilesY - 160)
                {
                    num838 = Main.maxTilesY - 160;
                }
                for (int num840 = num838 - 20 - genRand.Next(3); num840 < Main.maxTilesY; num840++)
                {
                    if (num840 >= num838)
                    {
                        Main.tile[num839, num840].active(active: false);
                        Main.tile[num839, num840].lava(lava: false);
                        Main.tile[num839, num840].liquid = 0;
                    }
                    else
                    {
                        Main.tile[num839, num840].type = 57;
                    }
                }
            }
            int num841 = Main.maxTilesY - genRand.Next(40, 70);
            for (int num842 = 10; num842 < Main.maxTilesX - 10; num842++)
            {
                num841 += genRand.Next(-10, 11);
                if (num841 > Main.maxTilesY - 60)
                {
                    num841 = Main.maxTilesY - 60;
                }
                if (num841 < Main.maxTilesY - 100)
                {
                    num841 = Main.maxTilesY - 120;
                }
                for (int num843 = num841; num843 < Main.maxTilesY - 10; num843++)
                {
                    if (!Main.tile[num842, num843].active())
                    {
                        Main.tile[num842, num843].lava(lava: true);
                        Main.tile[num842, num843].liquid = byte.MaxValue;
                    }
                }
            }
            for (int num844 = 0; num844 < Main.maxTilesX; num844++)
            {
                if (genRand.Next(50) == 0)
                {
                    int num845 = Main.maxTilesY - 65;
                    while (!Main.tile[num844, num845].active() && num845 > Main.maxTilesY - 135)
                    {
                        num845--;
                    }
                    TileRunner(genRand.Next(0, Main.maxTilesX), num845 + genRand.Next(20, 50), genRand.Next(15, 20), 1000, 57, addTile: true, 0.0, genRand.Next(1, 3), noYChange: true);
                }
            }
            Liquid.QuickWater(-2);
            for (int num846 = 0; num846 < Main.maxTilesX; num846++)
            {
                double num847 = (double)num846 / (double)(Main.maxTilesX - 1);
                progress.Set(num847 / 2.0 + 0.5);
                if (genRand.Next(13) == 0)
                {
                    int num848 = Main.maxTilesY - 65;
                    while ((Main.tile[num846, num848].liquid > 0 || Main.tile[num846, num848].active()) && num848 > Main.maxTilesY - 140)
                    {
                        num848--;
                    }
                    if ((!drunkWorldGen && !remixWorldGen) || genRand.Next(3) == 0 || !((double)num846 > (double)Main.maxTilesX * 0.4) || !((double)num846 < (double)Main.maxTilesX * 0.6))
                    {
                        TileRunner(num846, num848 - genRand.Next(2, 5), genRand.Next(5, 30), 1000, 57, addTile: true, 0.0, genRand.Next(1, 3), noYChange: true);
                    }
                    double num849 = genRand.Next(1, 3);
                    if (genRand.Next(3) == 0)
                    {
                        num849 *= 0.5;
                    }
                    if ((!drunkWorldGen && !remixWorldGen) || genRand.Next(3) == 0 || !((double)num846 > (double)Main.maxTilesX * 0.4) || !((double)num846 < (double)Main.maxTilesX * 0.6))
                    {
                        if (genRand.Next(2) == 0)
{
                            TileRunner(num846, num848 - genRand.Next(2, 5), (int)((double)genRand.Next(5, 15) * num849), (int)((double)genRand.Next(10, 15) * num849), 57, addTile: true, 1.0, 0.3);
                        }
                        if (genRand.Next(2) == 0)
{
                            num849 = genRand.Next(1, 3);
                            TileRunner(num846, num848 - genRand.Next(2, 5), (int)((double)genRand.Next(5, 15) * num849), (int)((double)genRand.Next(10, 15) * num849), 57, addTile: true, -1.0, 0.3);
                        }
                    }
                    TileRunner(num846 + genRand.Next(-10, 10), num848 + genRand.Next(-10, 10), genRand.Next(5, 15), genRand.Next(5, 10), -2, addTile: false, genRand.Next(-1, 3), genRand.Next(-1, 3));
                    if (genRand.Next(3) == 0)
                    {
                        TileRunner(num846 + genRand.Next(-10, 10), num848 + genRand.Next(-10, 10), genRand.Next(10, 30), genRand.Next(10, 20), -2, addTile: false, genRand.Next(-1, 3), genRand.Next(-1, 3));
                    }
                    if (genRand.Next(5) == 0)
                    {
                        TileRunner(num846 + genRand.Next(-15, 15), num848 + genRand.Next(-15, 10), genRand.Next(15, 30), genRand.Next(5, 20), -2, addTile: false, genRand.Next(-1, 3), genRand.Next(-1, 3));
                    }
                }
            }
            for (int num850 = 0; num850 < Main.maxTilesX; num850++)
            {
                TileRunner(genRand.Next(20, Main.maxTilesX - 20), genRand.Next(Main.maxTilesY - 180, Main.maxTilesY - 10), genRand.Next(2, 7), genRand.Next(2, 7), -2);
            }
            if (drunkWorldGen || remixWorldGen)
            {
                for (int num851 = 0; num851 < Main.maxTilesX * 2; num851++)
                {
                    TileRunner(genRand.Next((int)((double)Main.maxTilesX * 0.35), (int)((double)Main.maxTilesX * 0.65)), genRand.Next(Main.maxTilesY - 180, Main.maxTilesY - 10), genRand.Next(5, 20), genRand.Next(5, 10), -2);
                }
            }
            for (int num852 = 0; num852 < Main.maxTilesX; num852++)
            {
                if (!Main.tile[num852, Main.maxTilesY - 145].active())
                {
                    Main.tile[num852, Main.maxTilesY - 145].liquid = byte.MaxValue;
                    Main.tile[num852, Main.maxTilesY - 145].lava(lava: true);
                }
                if (!Main.tile[num852, Main.maxTilesY - 144].active())
                {
                    Main.tile[num852, Main.maxTilesY - 144].liquid = byte.MaxValue;
                    Main.tile[num852, Main.maxTilesY - 144].lava(lava: true);
                }
            }
            for (int num853 = 0; num853 < (int)((double)(Main.maxTilesX * Main.maxTilesY) * 0.0008); num853++)
            {
                TileRunner(genRand.Next(0, Main.maxTilesX), genRand.Next(Main.maxTilesY - 140, Main.maxTilesY), genRand.Next(2, 7), genRand.Next(3, 7), 58);
            }
            if (remixWorldGen)
            {
                int num854 = (int)((double)Main.maxTilesX * 0.38);
                int num855 = (int)((double)Main.maxTilesX * 0.62);
                int num856 = num854;
                int num857 = Main.maxTilesY - 1;
                int num858 = Main.maxTilesY - 135;
                int num859 = Main.maxTilesY - 160;
                bool flag55 = false;
                Liquid.QuickWater(-2);
                for (; num857 < Main.maxTilesY - 1 || num856 < num855; num856++)
                {
                    if (!flag55)
                    {
                        num857 -= genRand.Next(1, 4);
                        if (num857 < num858)
{
                            flag55 = true;
                        }
                    }
                    else if (num856 >= num855)
                    {
                        num857 += genRand.Next(1, 4);
                        if (num857 > Main.maxTilesY - 1)
{
                            num857 = Main.maxTilesY - 1;
                        }
                    }
                    else
                    {
                        if ((num856 <= Main.maxTilesX / 2 - 5 || num856 >= Main.maxTilesX / 2 + 5) && genRand.Next(4) == 0)
{
                            if (genRand.Next(3) == 0)
{
                                num857 += genRand.Next(-1, 2);
                            }
                            else if (genRand.Next(6) == 0)
{
                                num857 += genRand.Next(-2, 3);
                            }
                            else if (genRand.Next(8) == 0)
{
                                num857 += genRand.Next(-4, 5);
                            }
                        }
                        if (num857 < num859)
{
                            num857 = num859;
                        }
                        if (num857 > num858)
{
                            num857 = num858;
                        }
                    }
                    for (int num860 = num857; num860 > num857 - 20; num860--)
                    {
                        Main.tile[num856, num860].liquid = 0;
                    }
                    for (int num861 = num857; num861 < Main.maxTilesY; num861++)
                    {
                        Main.tile[num856, num861] = new Tile();
                        Main.tile[num856, num861].active(active: true);
                        Main.tile[num856, num861].type = 57;
                    }
                }
                Liquid.QuickWater(-2);
                for (int num862 = num854; num862 < num855 + 15; num862++)
                {
                    for (int num863 = Main.maxTilesY - 300; num863 < num858 + 20; num863++)
                    {
                        Main.tile[num862, num863].liquid = 0;
                        if (Main.tile[num862, num863].type == 57 && Main.tile[num862, num863].active() && (!Main.tile[num862 - 1, num863 - 1].active() || !Main.tile[num862, num863 - 1].active() || !Main.tile[num862 + 1, num863 - 1].active() || !Main.tile[num862 - 1, num863].active() || !Main.tile[num862 + 1, num863].active() || !Main.tile[num862 - 1, num863 + 1].active() || !Main.tile[num862, num863 + 1].active() || !Main.tile[num862 + 1, num863 + 1].active()))
{
                            Main.tile[num862, num863].type = 633;
                        }
                    }
                }
                for (int num864 = num854; num864 < num855 + 15; num864++)
                {
                    for (int num865 = Main.maxTilesY - 200; num865 < num858 + 20; num865++)
                    {
                        if (Main.tile[num864, num865].type == 633 && Main.tile[num864, num865].active() && !Main.tile[num864, num865 - 1].active() && genRand.Next(3) == 0)
{
                            TryGrowingTreeByType(634, num864, num865);
                        }
                    }
                }
            }
            else if (!drunkWorldGen)
            {
                for (int num866 = 25; num866 < Main.maxTilesX - 25; num866++)
                {
                    if ((double)num866 < (double)Main.maxTilesX * 0.17 || (double)num866 > (double)Main.maxTilesX * 0.83)
                    {
                        for (int num867 = Main.maxTilesY - 300; num867 < Main.maxTilesY - 100 + genRand.Next(-1, 2); num867++)
{
                            if (Main.tile[num866, num867].type == 57 && Main.tile[num866, num867].active() && (!Main.tile[num866 - 1, num867 - 1].active() || !Main.tile[num866, num867 - 1].active() || !Main.tile[num866 + 1, num867 - 1].active() || !Main.tile[num866 - 1, num867].active() || !Main.tile[num866 + 1, num867].active() || !Main.tile[num866 - 1, num867 + 1].active() || !Main.tile[num866, num867 + 1].active() || !Main.tile[num866 + 1, num867 + 1].active()))
{
                                Main.tile[num866, num867].type = 633;
                            }
                        }
                    }
                }
                for (int num868 = 25; num868 < Main.maxTilesX - 25; num868++)
                {
                    if ((double)num868 < (double)Main.maxTilesX * 0.17 || (double)num868 > (double)Main.maxTilesX * 0.83)
                    {
                        for (int num869 = Main.maxTilesY - 200; num869 < Main.maxTilesY - 50; num869++)
{
                            if (Main.tile[num868, num869].type == 633 && Main.tile[num868, num869].active() && !Main.tile[num868, num869 - 1].active() && genRand.Next(3) == 0)
{
                                TryGrowingTreeByType(634, num868, num869);
                            }
                        }
                    }
                }
            }
            AddHellHouses();
            if (drunkWorldGen)
            {
                for (int num870 = 25; num870 < Main.maxTilesX - 25; num870++)
                {
                    for (int num871 = Main.maxTilesY - 300; num871 < Main.maxTilesY - 100 + genRand.Next(-1, 2); num871++)
                    {
                        if (Main.tile[num870, num871].type == 57 && Main.tile[num870, num871].active() && (!Main.tile[num870 - 1, num871 - 1].active() || !Main.tile[num870, num871 - 1].active() || !Main.tile[num870 + 1, num871 - 1].active() || !Main.tile[num870 - 1, num871].active() || !Main.tile[num870 + 1, num871].active() || !Main.tile[num870 - 1, num871 + 1].active() || !Main.tile[num870, num871 + 1].active() || !Main.tile[num870 + 1, num871 + 1].active()))
{
                            Main.tile[num870, num871].type = 633;
                        }
                    }
                }
                for (int num872 = 25; num872 < Main.maxTilesX - 25; num872++)
                {
                    for (int num873 = Main.maxTilesY - 200; num873 < Main.maxTilesY - 50; num873++)
                    {
                        if (Main.tile[num872, num873].type == 633 && Main.tile[num872, num873].active() && !Main.tile[num872, num873 - 1].active() && genRand.Next(3) == 0)
{
                            TryGrowingTreeByType(634, num872, num873);
                        }
                    }
                }
            }
        });
        AddGenerationPass("Corruption", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            int num778 = Main.maxTilesX;
            int num779 = 0;
            int num780 = Main.maxTilesX;
            int num781 = 0;
            for (int num782 = 0; num782 < Main.maxTilesX; num782++)
            {
                for (int num783 = 0; (double)num783 < Main.worldSurface; num783++)
                {
                    if (Main.tile[num782, num783].active())
                    {
                        if (Main.tile[num782, num783].type == 60)
{
                            if (num782 < num778)
{
                                num778 = num782;
                            }
                            if (num782 > num779)
{
                                num779 = num782;
                            }
                        }
                        else if (Main.tile[num782, num783].type == 147 || Main.tile[num782, num783].type == 161)
{
                            if (num782 < num780)
{
                                num780 = num782;
                            }
                            if (num782 > num781)
{
                                num781 = num782;
                            }
                        }
                    }
                }
            }
            int num784 = 10;
            num778 -= num784;
            num779 += num784;
            num780 -= num784;
            num781 += num784;
            int num785 = 500;
            int num786 = 100;
            bool flag49 = crimson;
            double num787 = (double)Main.maxTilesX * 0.00045;
            if (remixWorldGen)
            {
                num787 *= 2.0;
            }
            else if (tenthAnniversaryWorldGen)
            {
                num785 *= 2;
                num786 *= 2;
            }
            if (drunkWorldGen)
            {
                flag49 = true;
                num787 /= 2.0;
            }
            if (flag49)
            {
                progress.Message = Lang.gen[72].Value;
                for (int num788 = 0; (double)num788 < num787; num788++)
                {
                    int num789 = num780;
                    int num790 = num781;
                    int num791 = num778;
                    int num792 = num779;
                    double value15 = (double)num788 / num787;
                    progress.Set(value15);
                    bool flag50 = false;
                    int num793 = 0;
                    int num794 = 0;
                    int num795 = 0;
                    while (!flag50)
                    {
                        flag50 = true;
                        int num796 = Main.maxTilesX / 2;
                        int num797 = 200;
                        if (drunkWorldGen)
{
                            num797 = 100;
                            num793 = ((!GenVars.crimsonLeft) ? genRand.Next((int)((double)Main.maxTilesX * 0.5), Main.maxTilesX - num785) : genRand.Next(num785, (int)((double)Main.maxTilesX * 0.5)));
                        }
                        else
{
                            num793 = genRand.Next(num785, Main.maxTilesX - num785);
                        }
                        num794 = num793 - genRand.Next(200) - 100;
                        num795 = num793 + genRand.Next(200) + 100;
                        if (num794 < GenVars.evilBiomeBeachAvoidance)
{
                            num794 = GenVars.evilBiomeBeachAvoidance;
                        }
                        if (num795 > Main.maxTilesX - GenVars.evilBiomeBeachAvoidance)
{
                            num795 = Main.maxTilesX - GenVars.evilBiomeBeachAvoidance;
                        }
                        if (num793 < num794 + GenVars.evilBiomeAvoidanceMidFixer)
{
                            num793 = num794 + GenVars.evilBiomeAvoidanceMidFixer;
                        }
                        if (num793 > num795 - GenVars.evilBiomeAvoidanceMidFixer)
{
                            num793 = num795 - GenVars.evilBiomeAvoidanceMidFixer;
                        }
                        if (GenVars.dungeonSide < 0 && num794 < 400)
{
                            num794 = 400;
                        }
                        else if (GenVars.dungeonSide > 0 && num794 > Main.maxTilesX - 400)
{
                            num794 = Main.maxTilesX - 400;
                        }
                        if (num794 < GenVars.dungeonLocation + num786 && num795 > GenVars.dungeonLocation - num786)
{
                            flag50 = false;
                        }
                        if (!remixWorldGen)
{
                            if (!tenthAnniversaryWorldGen)
{
                                if (num793 > num796 - num797 && num793 < num796 + num797)
{
                                    flag50 = false;
                                }
                                if (num794 > num796 - num797 && num794 < num796 + num797)
{
                                    flag50 = false;
                                }
                                if (num795 > num796 - num797 && num795 < num796 + num797)
{
                                    flag50 = false;
                                }
                            }
                            if (num793 > GenVars.UndergroundDesertLocation.X && num793 < GenVars.UndergroundDesertLocation.X + GenVars.UndergroundDesertLocation.Width)
{
                                flag50 = false;
                            }
                            if (num794 > GenVars.UndergroundDesertLocation.X && num794 < GenVars.UndergroundDesertLocation.X + GenVars.UndergroundDesertLocation.Width)
{
                                flag50 = false;
                            }
                            if (num795 > GenVars.UndergroundDesertLocation.X && num795 < GenVars.UndergroundDesertLocation.X + GenVars.UndergroundDesertLocation.Width)
{
                                flag50 = false;
                            }
                            if (num794 < num790 && num795 > num789)
{
                                num789++;
                                num790--;
                                flag50 = false;
                            }
                            if (num794 < num792 && num795 > num791)
{
                                num791++;
                                num792--;
                                flag50 = false;
                            }
                        }
                    }
                    CrimStart(num793, (int)GenVars.worldSurfaceLow - 10);
                    for (int num798 = num794; num798 < num795; num798++)
                    {
                        for (int num799 = (int)GenVars.worldSurfaceLow; (double)num799 < Main.worldSurface - 1.0; num799++)
{
                            if (Main.tile[num798, num799].active())
{
                                int num800 = num799 + genRand.Next(10, 14);
                                for (int num801 = num799; num801 < num800; num801++)
{
                                    if (Main.tile[num798, num801].type == 60 && num798 >= num794 + genRand.Next(5) && num798 < num795 - genRand.Next(5))
{
                                        Main.tile[num798, num801].type = 662;
                                    }
                                }
                                break;
                            }
                        }
                    }
                    double num802 = Main.worldSurface + 40.0;
                    for (int num803 = num794; num803 < num795; num803++)
                    {
                        num802 += (double)genRand.Next(-2, 3);
                        if (num802 < Main.worldSurface + 30.0)
{
                            num802 = Main.worldSurface + 30.0;
                        }
                        if (num802 > Main.worldSurface + 50.0)
{
                            num802 = Main.worldSurface + 50.0;
                        }
                        bool flag51 = false;
                        for (int num804 = (int)GenVars.worldSurfaceLow; (double)num804 < num802; num804++)
{
                            if (Main.tile[num803, num804].active())
{
                                if (Main.tile[num803, num804].type == 53 && num803 >= num794 + genRand.Next(5) && num803 <= num795 - genRand.Next(5))
{
                                    Main.tile[num803, num804].type = 234;
                                }
                                if ((double)num804 < Main.worldSurface - 1.0 && !flag51)
{
                                    if (Main.tile[num803, num804].type == 0)
{
                                        grassSpread = 0;
                                        SpreadGrass(num803, num804, 0, 199);
                                    }
                                    else if (Main.tile[num803, num804].type == 59)
{
                                        grassSpread = 0;
                                        SpreadGrass(num803, num804, 59, 662);
                                    }
                                }
                                flag51 = true;
                                if (Main.tile[num803, num804].wall == 216)
{
                                    Main.tile[num803, num804].wall = 218;
                                }
                                else if (Main.tile[num803, num804].wall == 187)
{
                                    Main.tile[num803, num804].wall = 221;
                                }
                                if (Main.tile[num803, num804].type == 1)
{
                                    if (num803 >= num794 + genRand.Next(5) && num803 <= num795 - genRand.Next(5))
{
                                        Main.tile[num803, num804].type = 203;
                                    }
                                }
                                else if (Main.tile[num803, num804].type == 2)
{
                                    Main.tile[num803, num804].type = 199;
                                }
                                else if (Main.tile[num803, num804].type == 60)
{
                                    Main.tile[num803, num804].type = 662;
                                }
                                else if (Main.tile[num803, num804].type == 161)
{
                                    Main.tile[num803, num804].type = 200;
                                }
                                else if (Main.tile[num803, num804].type == 396)
{
                                    Main.tile[num803, num804].type = 401;
                                }
                                else if (Main.tile[num803, num804].type == 397)
{
                                    Main.tile[num803, num804].type = 399;
                                }
                            }
                        }
                    }
                    int num805 = genRand.Next(10, 15);
                    for (int num806 = 0; num806 < num805; num806++)
                    {
                        int num807 = 0;
                        bool flag52 = false;
                        int num808 = 0;
                        while (!flag52)
{
                            num807++;
                            int num809 = genRand.Next(num794 - num808, num795 + num808);
                            int num810 = genRand.Next((int)(Main.worldSurface - (double)(num808 / 2)), (int)(Main.worldSurface + 100.0 + (double)num808));
                            while (oceanDepths(num809, num810))
{
                                num809 = genRand.Next(num794 - num808, num795 + num808);
                                num810 = genRand.Next((int)(Main.worldSurface - (double)(num808 / 2)), (int)(Main.worldSurface + 100.0 + (double)num808));
                            }
                            if (num807 > 100)
{
                                num808++;
                                num807 = 0;
                            }
                            if (!Main.tile[num809, num810].active())
{
                                for (; !Main.tile[num809, num810].active(); num810++)
{
                                }
                                num810--;
                            }
                            else
{
                                while (Main.tile[num809, num810].active() && (double)num810 > Main.worldSurface)
{
                                    num810--;
                                }
                            }
                            if ((num808 > 10 || (Main.tile[num809, num810 + 1].active() && Main.tile[num809, num810 + 1].type == 203)) && !IsTileNearby(num809, num810, 26, 3))
{
                                Place3x2(num809, num810, 26, 1);
                                if (Main.tile[num809, num810].type == 26)
{
                                    flag52 = true;
                                }
                            }
                            if (num808 > 100)
{
                                flag52 = true;
                            }
                        }
                    }
                }
                CrimPlaceHearts();
            }
            if (drunkWorldGen)
            {
                flag49 = false;
            }
            if (!flag49)
            {
                progress.Message = Lang.gen[20].Value;
                for (int num811 = 0; (double)num811 < num787; num811++)
                {
                    int num812 = num780;
                    int num813 = num781;
                    int num814 = num778;
                    int num815 = num779;
                    double value16 = (double)num811 / num787;
                    progress.Set(value16);
                    bool flag53 = false;
                    int num816 = 0;
                    int num817 = 0;
                    int num818 = 0;
                    while (!flag53)
                    {
                        flag53 = true;
                        int num819 = Main.maxTilesX / 2;
                        int num820 = 200;
                        num816 = ((!drunkWorldGen) ? genRand.Next(num785, Main.maxTilesX - num785) : (GenVars.crimsonLeft ? genRand.Next((int)((double)Main.maxTilesX * 0.5), Main.maxTilesX - num785) : genRand.Next(num785, (int)((double)Main.maxTilesX * 0.5))));
                        num817 = num816 - genRand.Next(200) - 100;
                        num818 = num816 + genRand.Next(200) + 100;
                        if (num817 < GenVars.evilBiomeBeachAvoidance)
{
                            num817 = GenVars.evilBiomeBeachAvoidance;
                        }
                        if (num818 > Main.maxTilesX - GenVars.evilBiomeBeachAvoidance)
{
                            num818 = Main.maxTilesX - GenVars.evilBiomeBeachAvoidance;
                        }
                        if (num816 < num817 + GenVars.evilBiomeAvoidanceMidFixer)
{
                            num816 = num817 + GenVars.evilBiomeAvoidanceMidFixer;
                        }
                        if (num816 > num818 - GenVars.evilBiomeAvoidanceMidFixer)
{
                            num816 = num818 - GenVars.evilBiomeAvoidanceMidFixer;
                        }
                        if (num817 < GenVars.dungeonLocation + num786 && num818 > GenVars.dungeonLocation - num786)
{
                            flag53 = false;
                        }
                        if (!remixWorldGen)
{
                            if (!tenthAnniversaryWorldGen)
{
                                if (num816 > num819 - num820 && num816 < num819 + num820)
{
                                    flag53 = false;
                                }
                                if (num817 > num819 - num820 && num817 < num819 + num820)
{
                                    flag53 = false;
                                }
                                if (num818 > num819 - num820 && num818 < num819 + num820)
{
                                    flag53 = false;
                                }
                            }
                            if (num816 > GenVars.UndergroundDesertLocation.X && num816 < GenVars.UndergroundDesertLocation.X + GenVars.UndergroundDesertLocation.Width)
{
                                flag53 = false;
                            }
                            if (num817 > GenVars.UndergroundDesertLocation.X && num817 < GenVars.UndergroundDesertLocation.X + GenVars.UndergroundDesertLocation.Width)
{
                                flag53 = false;
                            }
                            if (num818 > GenVars.UndergroundDesertLocation.X && num818 < GenVars.UndergroundDesertLocation.X + GenVars.UndergroundDesertLocation.Width)
{
                                flag53 = false;
                            }
                            if (num817 < num813 && num818 > num812)
{
                                num812++;
                                num813--;
                                flag53 = false;
                            }
                            if (num817 < num815 && num818 > num814)
{
                                num814++;
                                num815--;
                                flag53 = false;
                            }
                        }
                    }
                    int num821 = 0;
                    for (int num822 = num817; num822 < num818; num822++)
                    {
                        if (num821 > 0)
{
                            num821--;
                        }
                        if (num822 == num816 || num821 == 0)
{
                            for (int num823 = (int)GenVars.worldSurfaceLow; (double)num823 < Main.worldSurface - 1.0; num823++)
{
                                if (Main.tile[num822, num823].active() || Main.tile[num822, num823].wall > 0)
{
                                    if (num822 == num816)
{
                                        num821 = 20;
                                        ChasmRunner(num822, num823, genRand.Next(150) + 150, makeOrb: true);
                                    }
                                    else if (genRand.Next(35) == 0 && num821 == 0)
{
                                        num821 = 30;
                                        bool makeOrb = true;
                                        ChasmRunner(num822, num823, genRand.Next(50) + 50, makeOrb);
                                    }
                                    break;
                                }
                            }
                        }
                        for (int num824 = (int)GenVars.worldSurfaceLow; (double)num824 < Main.worldSurface - 1.0; num824++)
{
                            if (Main.tile[num822, num824].active())
{
                                int num825 = num824 + genRand.Next(10, 14);
                                for (int num826 = num824; num826 < num825; num826++)
{
                                    if (Main.tile[num822, num826].type == 60 && num822 >= num817 + genRand.Next(5) && num822 < num818 - genRand.Next(5))
{
                                        Main.tile[num822, num826].type = 661;
                                    }
                                }
                                break;
                            }
                        }
                    }
                    double num827 = Main.worldSurface + 40.0;
                    for (int num828 = num817; num828 < num818; num828++)
                    {
                        num827 += (double)genRand.Next(-2, 3);
                        if (num827 < Main.worldSurface + 30.0)
{
                            num827 = Main.worldSurface + 30.0;
                        }
                        if (num827 > Main.worldSurface + 50.0)
{
                            num827 = Main.worldSurface + 50.0;
                        }
                        bool flag54 = false;
                        for (int num829 = (int)GenVars.worldSurfaceLow; (double)num829 < num827; num829++)
{
                            if (Main.tile[num828, num829].active())
{
                                if (Main.tile[num828, num829].type == 53 && num828 >= num817 + genRand.Next(5) && num828 <= num818 - genRand.Next(5))
{
                                    Main.tile[num828, num829].type = 112;
                                }
                                if ((double)num829 < Main.worldSurface - 1.0 && !flag54)
{
                                    if (Main.tile[num828, num829].type == 0)
{
                                        grassSpread = 0;
                                        SpreadGrass(num828, num829, 0, 23);
                                    }
                                    else if (Main.tile[num828, num829].type == 59)
{
                                        grassSpread = 0;
                                        SpreadGrass(num828, num829, 59, 661);
                                    }
                                }
                                flag54 = true;
                                if (Main.tile[num828, num829].wall == 216)
{
                                    Main.tile[num828, num829].wall = 217;
                                }
                                else if (Main.tile[num828, num829].wall == 187)
{
                                    Main.tile[num828, num829].wall = 220;
                                }
                                if (Main.tile[num828, num829].type == 1)
{
                                    if (num828 >= num817 + genRand.Next(5) && num828 <= num818 - genRand.Next(5))
{
                                        Main.tile[num828, num829].type = 25;
                                    }
                                }
                                else if (Main.tile[num828, num829].type == 2)
{
                                    Main.tile[num828, num829].type = 23;
                                }
                                else if (Main.tile[num828, num829].type == 60)
{
                                    Main.tile[num828, num829].type = 661;
                                }
                                else if (Main.tile[num828, num829].type == 161)
{
                                    Main.tile[num828, num829].type = 163;
                                }
                                else if (Main.tile[num828, num829].type == 396)
{
                                    Main.tile[num828, num829].type = 400;
                                }
                                else if (Main.tile[num828, num829].type == 397)
{
                                    Main.tile[num828, num829].type = 398;
                                }
                            }
                        }
                    }
                    for (int num830 = num817; num830 < num818; num830++)
                    {
                        for (int num831 = 0; num831 < Main.maxTilesY - 50; num831++)
{
                            if (Main.tile[num830, num831].active() && Main.tile[num830, num831].type == 31)
{
                                int num832 = num830 - 13;
                                int num833 = num830 + 13;
                                int num834 = num831 - 13;
                                int num835 = num831 + 13;
                                for (int num836 = num832; num836 < num833; num836++)
{
                                    if (num836 > 10 && num836 < Main.maxTilesX - 10)
{
                                        for (int num837 = num834; num837 < num835; num837++)
{
                                            if (Math.Abs(num836 - num830) + Math.Abs(num837 - num831) < 9 + genRand.Next(11) && genRand.Next(3) != 0 && Main.tile[num836, num837].type != 31)
{
                                                Main.tile[num836, num837].active(active: true);
                                                Main.tile[num836, num837].type = 25;
                                                if (Math.Abs(num836 - num830) <= 1 && Math.Abs(num837 - num831) <= 1)
{
                                                    Main.tile[num836, num837].active(active: false);
                                                }
                                            }
                                            if (Main.tile[num836, num837].type != 31 && Math.Abs(num836 - num830) <= 2 + genRand.Next(3) && Math.Abs(num837 - num831) <= 2 + genRand.Next(3))
{
                                                Main.tile[num836, num837].active(active: false);
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        });
        AddGenerationPass("Lakes", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            progress.Message = Lang.gen[19].Value;
            double num759 = (double)Main.maxTilesX / 4200.0;
            int num760 = genRand.Next((int)(num759 * 3.0), (int)(num759 * 6.0));
            for (int num761 = 0; num761 < num760; num761++)
            {
                int num762 = Main.maxTilesX / 4;
                if (GenVars.numLakes >= GenVars.maxLakes - 1)
                {
                    break;
                }
                double value14 = (double)num761 / (double)num760;
                progress.Set(value14);
                while (num762 > 0)
                {
                    bool flag48 = false;
                    num762--;
                    int num763 = genRand.Next(GenVars.lakesBeachAvoidance, Main.maxTilesX - GenVars.lakesBeachAvoidance);
                    if (tenthAnniversaryWorldGen && !remixWorldGen)
                    {
                        num763 = genRand.Next((int)((double)Main.maxTilesX * 0.15), (int)((double)Main.maxTilesX * 0.85));
                    }
                    else
                    {
                        while ((double)num763 > (double)Main.maxTilesX * 0.45 && (double)num763 < (double)Main.maxTilesX * 0.55)
{
                            num763 = genRand.Next(GenVars.lakesBeachAvoidance, Main.maxTilesX - GenVars.lakesBeachAvoidance);
                        }
                    }
                    for (int num764 = 0; num764 < GenVars.numLakes; num764++)
                    {
                        if (Math.Abs(num763 - GenVars.LakeX[num764]) < 150)
{
                            flag48 = true;
                            break;
                        }
                    }
                    for (int num765 = 0; num765 < GenVars.numMCaves; num765++)
                    {
                        if (Math.Abs(num763 - GenVars.mCaveX[num765]) < 100)
{
                            flag48 = true;
                            break;
                        }
                    }
                    for (int num766 = 0; num766 < GenVars.numTunnels; num766++)
                    {
                        if (Math.Abs(num763 - GenVars.tunnelX[num766]) < 100)
{
                            flag48 = true;
                            break;
                        }
                    }
                    if (!flag48)
                    {
                        int num767 = (int)GenVars.worldSurfaceLow - 20;
                        while (!Main.tile[num763, num767].active())
{
                            num767++;
                            if ((double)num767 >= Main.worldSurface || Main.tile[num763, num767].wall > 0)
{
                                flag48 = true;
                                break;
                            }
                        }
                        if (Main.tile[num763, num767].type == 53)
{
                            flag48 = true;
                        }
                        if (!flag48)
{
                            int num768 = 50;
                            for (int num769 = num763 - num768; num769 <= num763 + num768; num769++)
{
                                for (int num770 = num767 - num768; num770 <= num767 + num768; num770++)
{
                                    if (Main.tile[num769, num770].type == 203 || Main.tile[num769, num770].type == 25)
{
                                        flag48 = true;
                                        break;
                                    }
                                }
                            }
                            if (!flag48)
{
                                int num771 = num767;
                                num768 = 20;
                                while (!SolidTile(num763 - num768, num767) || !SolidTile(num763 + num768, num767))
{
                                    num767++;
                                    if ((double)num767 > Main.worldSurface - 50.0)
{
                                        flag48 = true;
                                    }
                                }
                                if (num767 - num771 <= 10)
{
                                    num768 = 60;
                                    for (int num772 = num763 - num768; num772 <= num763 + num768; num772++)
{
                                        int num773 = num767 - 20;
                                        if (Main.tile[num772, num773].active() || Main.tile[num772, num773].wall > 0)
{
                                            flag48 = true;
                                        }
                                    }
                                    if (!flag48)
{
                                        int num774 = 0;
                                        for (int num775 = num763 - num768; num775 <= num763 + num768; num775++)
{
                                            for (int num776 = num767; num776 <= num767 + num768 * 2; num776++)
{
                                                if (SolidTile(num775, num776))
{
                                                    num774++;
                                                }
                                            }
                                        }
                                        int num777 = (num768 * 2 + 1) * (num768 * 2 + 1);
                                        if (!((double)num774 < (double)num777 * 0.8) && !GenVars.UndergroundDesertLocation.Intersects(new Rectangle(num763 - 8, num767 - 8, 16, 16)))
{
                                            SonOfLakinater(num763, num767);
                                            GenVars.LakeX[GenVars.numLakes] = num763;
                                            GenVars.numLakes++;
                                            break;
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        });
        AddGenerationPass("Dungeon", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            progress.Set(1.0);
            int dungeonLocation = GenVars.dungeonLocation;
            int num755 = (int)((Main.worldSurface + Main.rockLayer) / 2.0) + genRand.Next(-200, 200);
            int num756 = (int)((Main.worldSurface + Main.rockLayer) / 2.0) + 200;
            int num757 = num755;
            bool flag47 = false;
            for (int num758 = 0; num758 < 10; num758++)
            {
                if (SolidTile(dungeonLocation, num757 + num758))
                {
                    flag47 = true;
                    break;
                }
            }
            if (!flag47)
            {
                for (; num757 < num756 && !SolidTile(dungeonLocation, num757 + 10); num757++)
                {
                }
            }
            if (drunkWorldGen)
            {
                num757 = (int)Main.worldSurface + 70;
            }
            MakeDungeon(dungeonLocation, num757);
        });
        AddGenerationPass("Slush", delegate
        {
            for (int num750 = GenVars.snowTop; num750 < GenVars.snowBottom; num750++)
            {
                for (int num751 = GenVars.snowMinX[num750]; num751 < GenVars.snowMaxX[num750]; num751++)
                {
                    switch (Main.tile[num751, num750].type)
                    {
                    case 123:
                        Main.tile[num751, num750].type = 224;
                        break;
                    case 59:
                    {
                        bool flag46 = true;
                        int num752 = 3;
                        for (int num753 = num751 - num752; num753 <= num751 + num752; num753++)
{
                            for (int num754 = num750 - num752; num754 <= num750 + num752; num754++)
{
                                if (Main.tile[num753, num754].type == 60 || Main.tile[num753, num754].type == 70 || Main.tile[num753, num754].type == 71 || Main.tile[num753, num754].type == 72)
{
                                    flag46 = false;
                                    break;
                                }
                            }
                        }
                        if (flag46)
{
                            Main.tile[num751, num750].type = 224;
                        }
                        break;
                    }
                    case 1:
                        Main.tile[num751, num750].type = 161;
                        break;
                    }
                }
            }
        });
        AddGenerationPass("Mountain Caves", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            progress.Message = Lang.gen[21].Value;
            for (int num749 = 0; num749 < GenVars.numMCaves; num749++)
            {
                int i3 = GenVars.mCaveX[num749];
                int j5 = GenVars.mCaveY[num749];
                CaveOpenater(i3, j5);
                Cavinator(i3, j5, genRand.Next(40, 50));
            }
        });
        AddGenerationPass("Beaches", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            int num731 = 50;
            progress.Message = Lang.gen[22].Value;
            bool floridaStyle = false;
            bool floridaStyle2 = false;
            if (genRand.Next(4) == 0)
            {
                if (genRand.Next(2) == 0)
                {
                    floridaStyle = true;
                }
                else
                {
                    floridaStyle2 = true;
                }
            }
            for (int num732 = 0; num732 < 2; num732++)
            {
                int num733 = 0;
                int num734 = 0;
                if (num732 == 0)
                {
                    num733 = 0;
                    num734 = genRand.Next(GenVars.oceanWaterStartRandomMin, GenVars.oceanWaterStartRandomMax);
                    if (GenVars.dungeonSide == 1)
                    {
                        num734 = GenVars.oceanWaterForcedJungleLength;
                    }
                    int num735 = GenVars.leftBeachEnd - num731;
                    if (num734 > num735)
                    {
                        num734 = num735;
                    }
                    int num736 = 0;
                    double num737 = 1.0;
                    int num738;
                    for (num738 = 0; !Main.tile[num734 - 1, num738].active(); num738++)
                    {
                    }
                    GenVars.shellStartYLeft = num738;
                    num738 += genRand.Next(1, 5);
                    for (int num739 = num734 - 1; num739 >= num733; num739--)
                    {
                        if (num739 > 30)
{
                            num736++;
                            num737 = TuneOceanDepth(num736, num737, floridaStyle);
                        }
                        else
{
                            num737 += 1.0;
                        }
                        int num740 = genRand.Next(15, 20);
                        for (int num741 = 0; (double)num741 < (double)num738 + num737 + (double)num740; num741++)
{
                            if ((double)num741 < (double)num738 + num737 * 0.75 - 3.0)
{
                                Main.tile[num739, num741].active(active: false);
                                if (num741 > num738)
{
                                    Main.tile[num739, num741].liquid = byte.MaxValue;
                                    Main.tile[num739, num741].lava(lava: false);
                                }
                                else if (num741 == num738)
{
                                    Main.tile[num739, num741].liquid = 127;
                                    if (GenVars.shellStartXLeft == 0)
{
                                        GenVars.shellStartXLeft = num739;
                                    }
                                }
                            }
                            else if (num741 > num738)
{
                                Main.tile[num739, num741].type = 53;
                                Main.tile[num739, num741].active(active: true);
                            }
                            Main.tile[num739, num741].wall = 0;
                        }
                    }
                }
                else
                {
                    num733 = Main.maxTilesX - genRand.Next(GenVars.oceanWaterStartRandomMin, GenVars.oceanWaterStartRandomMax);
                    num734 = Main.maxTilesX;
                    if (GenVars.dungeonSide == -1)
                    {
                        num733 = Main.maxTilesX - GenVars.oceanWaterForcedJungleLength;
                    }
                    int num742 = GenVars.rightBeachStart + num731;
                    if (num733 < num742)
                    {
                        num733 = num742;
                    }
                    double num743 = 1.0;
                    int num744 = 0;
                    int num745;
                    for (num745 = 0; !Main.tile[num733, num745].active(); num745++)
                    {
                    }
                    GenVars.shellStartXRight = 0;
                    GenVars.shellStartYRight = num745;
                    num745 += genRand.Next(1, 5);
                    for (int num746 = num733; num746 < num734; num746++)
                    {
                        if (num746 < num734 - 30)
{
                            num744++;
                            num743 = TuneOceanDepth(num744, num743, floridaStyle2);
                        }
                        else
{
                            num743 += 1.0;
                        }
                        int num747 = genRand.Next(15, 20);
                        for (int num748 = 0; (double)num748 < (double)num745 + num743 + (double)num747; num748++)
{
                            if ((double)num748 < (double)num745 + num743 * 0.75 - 3.0)
{
                                Main.tile[num746, num748].active(active: false);
                                if (num748 > num745)
{
                                    Main.tile[num746, num748].liquid = byte.MaxValue;
                                    Main.tile[num746, num748].lava(lava: false);
                                }
                                else if (num748 == num745)
{
                                    Main.tile[num746, num748].liquid = 127;
                                    if (GenVars.shellStartXRight == 0)
{
                                        GenVars.shellStartXRight = num746;
                                    }
                                }
                            }
                            else if (num748 > num745)
{
                                Main.tile[num746, num748].type = 53;
                                Main.tile[num746, num748].active(active: true);
                            }
                            Main.tile[num746, num748].wall = 0;
                        }
                    }
                }
            }
        });
        AddGenerationPass("Gems", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            progress.Message = Lang.gen[23].Value;
            Main.tileSolid[484] = false;
            for (int num718 = 63; num718 <= 68; num718++)
            {
                double value13 = (double)(num718 - 63) / 6.0;
                progress.Set(value13);
                double num719 = 0.0;
                switch (num718)
                {
                case 67:
                    num719 = (double)Main.maxTilesX * 0.5;
                    break;
                case 66:
                    num719 = (double)Main.maxTilesX * 0.45;
                    break;
                case 63:
                    num719 = (double)Main.maxTilesX * 0.3;
                    break;
                case 65:
                    num719 = (double)Main.maxTilesX * 0.25;
                    break;
                case 64:
                    num719 = (double)Main.maxTilesX * 0.1;
                    break;
                case 68:
                    num719 = (double)Main.maxTilesX * 0.05;
                    break;
                }
                num719 *= 0.2;
                for (int num720 = 0; (double)num720 < num719; num720++)
                {
                    int num721 = genRand.Next(0, Main.maxTilesX);
                    int num722 = genRand.Next((int)Main.worldSurface, Main.maxTilesY);
                    while (Main.tile[num721, num722].type != 1)
                    {
                        num721 = genRand.Next(0, Main.maxTilesX);
                        num722 = genRand.Next((int)Main.worldSurface, Main.maxTilesY);
                    }
                    TileRunner(num721, num722, genRand.Next(2, 6), genRand.Next(3, 7), num718);
                }
            }
            for (int num723 = 0; num723 < 2; num723++)
            {
                int num724 = 1;
                int num725 = 5;
                int num726 = Main.maxTilesX - 5;
                if (num723 == 1)
                {
                    num724 = -1;
                    num725 = Main.maxTilesX - 5;
                    num726 = 5;
                }
                for (int num727 = num725; num727 != num726; num727 += num724)
                {
                    if (num727 <= GenVars.UndergroundDesertLocation.Left || num727 >= GenVars.UndergroundDesertLocation.Right)
                    {
                        for (int num728 = 10; num728 < Main.maxTilesY - 10; num728++)
{
                            if (Main.tile[num727, num728].active() && Main.tile[num727, num728 + 1].active() && Main.tileSand[Main.tile[num727, num728].type] && Main.tileSand[Main.tile[num727, num728 + 1].type])
{
                                ushort type9 = Main.tile[num727, num728].type;
                                int num729 = num727 + num724;
                                int num730 = num728 + 1;
                                if (!Main.tile[num729, num728].active() && !Main.tile[num729, num730].active())
{
                                    for (; !Main.tile[num729, num730].active(); num730++)
{
                                    }
                                    num730--;
                                    Main.tile[num727, num728].active(active: false);
                                    Main.tile[num729, num730].active(active: true);
                                    Main.tile[num729, num730].type = type9;
                                }
                            }
                        }
                    }
                }
            }
        });
        AddGenerationPass("Gravitating Sand", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            progress.Message = Lang.gen[24].Value;
            for (int num714 = 0; num714 < Main.maxTilesX; num714++)
            {
                double value12 = (double)num714 / (double)(Main.maxTilesX - 1);
                progress.Set(value12);
                bool flag45 = false;
                int num715 = 0;
                for (int num716 = Main.maxTilesY - 1; num716 > 0; num716--)
                {
                    if (SolidOrSlopedTile(num714, num716))
                    {
                        ushort type8 = Main.tile[num714, num716].type;
                        if (flag45 && num716 < (int)Main.worldSurface && num716 != num715 - 1 && TileID.Sets.Falling[type8])
{
                            for (int num717 = num716; num717 < num715; num717++)
{
                                Main.tile[num714, num717].ResetToType(type8);
                            }
                        }
                        flag45 = true;
                        num715 = num716;
                    }
                }
            }
        });
        AddGenerationPass("Create Ocean Caves", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            int maxValue11 = 3;
            if (remixWorldGen)
            {
                maxValue11 = 2;
            }
            for (int num711 = 0; num711 < 2; num711++)
            {
                if ((num711 != 0 || GenVars.dungeonSide <= 0) && (num711 != 1 || GenVars.dungeonSide >= 0) && (genRand.Next(maxValue11) == 0 || drunkWorldGen || tenthAnniversaryWorldGen))
                {
                    progress.Message = Lang.gen[90].Value;
                    int num712 = genRand.Next(55, 95);
                    if (num711 == 1)
                    {
                        num712 = genRand.Next(Main.maxTilesX - 95, Main.maxTilesX - 55);
                    }
                    int num713;
                    for (num713 = 0; !Main.tile[num712, num713].active(); num713++)
                    {
                    }
                    oceanCave(num712, num713);
                }
            }
        });
        AddGenerationPass("Shimmer", delegate
        {
            //IL_028b: Unknown result type (might be due to invalid IL or missing references)
            //IL_0290: Unknown result type (might be due to invalid IL or missing references)
            int num702 = 50;
            int num703 = (int)(Main.worldSurface + Main.rockLayer) / 2 + num702;
            int num704 = (int)((double)((Main.maxTilesY - 250) * 2) + Main.rockLayer) / 3;
            if (num704 > Main.maxTilesY - 330 - 100 - 30)
            {
                num704 = Main.maxTilesY - 330 - 100 - 30;
            }
            if (num704 <= num703)
            {
                num704 = num703 + 50;
            }
            int num705 = genRand.Next(num703, num704);
            int num706 = ((GenVars.dungeonSide < 0) ? genRand.Next((int)((double)Main.maxTilesX * 0.89), Main.maxTilesX - 200) : genRand.Next(200, (int)((double)Main.maxTilesX * 0.11)));
            int num707 = (int)Main.worldSurface + 150;
            int num708 = (int)(Main.rockLayer + Main.worldSurface + 200.0) / 2;
            if (num708 <= num707)
            {
                num708 = num707 + 50;
            }
            if (tenthAnniversaryWorldGen)
            {
                num705 = genRand.Next(num707, num708);
            }
            int num709 = 0;
            while (!ShimmerMakeBiome(num706, num705))
            {
                num709++;
                if (tenthAnniversaryWorldGen && num709 < 10000)
                {
                    num705 = genRand.Next(num707, num708);
                    num706 = ((GenVars.dungeonSide < 0) ? genRand.Next((int)((double)Main.maxTilesX * 0.89), Main.maxTilesX - 200) : genRand.Next(200, (int)((double)Main.maxTilesX * 0.11)));
                }
                else if (num709 > 20000)
                {
                    num705 = genRand.Next((int)Main.worldSurface + 100 + 20, num704);
                    num706 = ((GenVars.dungeonSide < 0) ? genRand.Next((int)((double)Main.maxTilesX * 0.8), Main.maxTilesX - 200) : genRand.Next(200, (int)((double)Main.maxTilesX * 0.2)));
                }
                else
                {
                    num705 = genRand.Next((int)(Main.worldSurface + Main.rockLayer) / 2 + 20, num704);
                    num706 = ((GenVars.dungeonSide < 0) ? genRand.Next((int)((double)Main.maxTilesX * 0.89), Main.maxTilesX - 200) : genRand.Next(200, (int)((double)Main.maxTilesX * 0.11)));
                }
            }
            GenVars.shimmerPosition = new Vector2D((double)num706, (double)num705);
            int num710 = 200;
            GenVars.structures.AddProtectedStructure(new Rectangle(num706 - num710 / 2, num705 - num710 / 2, num710, num710));
        });
        AddGenerationPass("Clean Up Dirt", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            progress.Message = Lang.gen[25].Value;
            for (int num696 = 3; num696 < Main.maxTilesX - 3; num696++)
            {
                double num697 = (double)num696 / (double)Main.maxTilesX;
                progress.Set(0.5 * num697);
                bool flag43 = true;
                for (int num698 = 0; (double)num698 < Main.worldSurface; num698++)
                {
                    if (flag43)
                    {
                        if (Main.tile[num696, num698].wall == 2 || Main.tile[num696, num698].wall == 40 || Main.tile[num696, num698].wall == 64 || Main.tile[num696, num698].wall == 86)
{
                            Main.tile[num696, num698].wall = 0;
                        }
                        if (Main.tile[num696, num698].type != 53 && Main.tile[num696, num698].type != 112 && Main.tile[num696, num698].type != 234)
{
                            if (Main.tile[num696 - 1, num698].wall == 2 || Main.tile[num696 - 1, num698].wall == 40 || Main.tile[num696 - 1, num698].wall == 40)
{
                                Main.tile[num696 - 1, num698].wall = 0;
                            }
                            if ((Main.tile[num696 - 2, num698].wall == 2 || Main.tile[num696 - 2, num698].wall == 40 || Main.tile[num696 - 2, num698].wall == 40) && genRand.Next(2) == 0)
{
                                Main.tile[num696 - 2, num698].wall = 0;
                            }
                            if ((Main.tile[num696 - 3, num698].wall == 2 || Main.tile[num696 - 3, num698].wall == 40 || Main.tile[num696 - 3, num698].wall == 40) && genRand.Next(2) == 0)
{
                                Main.tile[num696 - 3, num698].wall = 0;
                            }
                            if (Main.tile[num696 + 1, num698].wall == 2 || Main.tile[num696 + 1, num698].wall == 40 || Main.tile[num696 + 1, num698].wall == 40)
{
                                Main.tile[num696 + 1, num698].wall = 0;
                            }
                            if ((Main.tile[num696 + 2, num698].wall == 2 || Main.tile[num696 + 2, num698].wall == 40 || Main.tile[num696 + 2, num698].wall == 40) && genRand.Next(2) == 0)
{
                                Main.tile[num696 + 2, num698].wall = 0;
                            }
                            if ((Main.tile[num696 + 3, num698].wall == 2 || Main.tile[num696 + 3, num698].wall == 40 || Main.tile[num696 + 3, num698].wall == 40) && genRand.Next(2) == 0)
{
                                Main.tile[num696 + 3, num698].wall = 0;
                            }
                            if (Main.tile[num696, num698].active())
{
                                flag43 = false;
                            }
                        }
                    }
                    else if (Main.tile[num696, num698].wall == 0 && Main.tile[num696, num698 + 1].wall == 0 && Main.tile[num696, num698 + 2].wall == 0 && Main.tile[num696, num698 + 3].wall == 0 && Main.tile[num696, num698 + 4].wall == 0 && Main.tile[num696 - 1, num698].wall == 0 && Main.tile[num696 + 1, num698].wall == 0 && Main.tile[num696 - 2, num698].wall == 0 && Main.tile[num696 + 2, num698].wall == 0 && !Main.tile[num696, num698].active() && !Main.tile[num696, num698 + 1].active() && !Main.tile[num696, num698 + 2].active() && !Main.tile[num696, num698 + 3].active())
                    {
                        flag43 = true;
                    }
                }
            }
            for (int num699 = Main.maxTilesX - 5; num699 >= 5; num699--)
            {
                double num700 = (double)num699 / (double)Main.maxTilesX;
                progress.Set(1.0 - 0.5 * num700);
                bool flag44 = true;
                for (int num701 = 0; (double)num701 < Main.worldSurface; num701++)
                {
                    if (flag44)
                    {
                        if (Main.tile[num699, num701].wall == 2 || Main.tile[num699, num701].wall == 40 || Main.tile[num699, num701].wall == 64)
{
                            Main.tile[num699, num701].wall = 0;
                        }
                        if (Main.tile[num699, num701].type != 53)
{
                            if (Main.tile[num699 - 1, num701].wall == 2 || Main.tile[num699 - 1, num701].wall == 40 || Main.tile[num699 - 1, num701].wall == 40)
{
                                Main.tile[num699 - 1, num701].wall = 0;
                            }
                            if ((Main.tile[num699 - 2, num701].wall == 2 || Main.tile[num699 - 2, num701].wall == 40 || Main.tile[num699 - 2, num701].wall == 40) && genRand.Next(2) == 0)
{
                                Main.tile[num699 - 2, num701].wall = 0;
                            }
                            if ((Main.tile[num699 - 3, num701].wall == 2 || Main.tile[num699 - 3, num701].wall == 40 || Main.tile[num699 - 3, num701].wall == 40) && genRand.Next(2) == 0)
{
                                Main.tile[num699 - 3, num701].wall = 0;
                            }
                            if (Main.tile[num699 + 1, num701].wall == 2 || Main.tile[num699 + 1, num701].wall == 40 || Main.tile[num699 + 1, num701].wall == 40)
{
                                Main.tile[num699 + 1, num701].wall = 0;
                            }
                            if ((Main.tile[num699 + 2, num701].wall == 2 || Main.tile[num699 + 2, num701].wall == 40 || Main.tile[num699 + 2, num701].wall == 40) && genRand.Next(2) == 0)
{
                                Main.tile[num699 + 2, num701].wall = 0;
                            }
                            if ((Main.tile[num699 + 3, num701].wall == 2 || Main.tile[num699 + 3, num701].wall == 40 || Main.tile[num699 + 3, num701].wall == 40) && genRand.Next(2) == 0)
{
                                Main.tile[num699 + 3, num701].wall = 0;
                            }
                            if (Main.tile[num699, num701].active())
{
                                flag44 = false;
                            }
                        }
                    }
                    else if (Main.tile[num699, num701].wall == 0 && Main.tile[num699, num701 + 1].wall == 0 && Main.tile[num699, num701 + 2].wall == 0 && Main.tile[num699, num701 + 3].wall == 0 && Main.tile[num699, num701 + 4].wall == 0 && Main.tile[num699 - 1, num701].wall == 0 && Main.tile[num699 + 1, num701].wall == 0 && Main.tile[num699 - 2, num701].wall == 0 && Main.tile[num699 + 2, num701].wall == 0 && !Main.tile[num699, num701].active() && !Main.tile[num699, num701 + 1].active() && !Main.tile[num699, num701 + 2].active() && !Main.tile[num699, num701 + 3].active())
                    {
                        flag44 = true;
                    }
                }
            }
        });
        AddGenerationPass("Pyramids", delegate
        {
            Rectangle undergroundDesertLocation = GenVars.UndergroundDesertLocation;
            if (Main.tenthAnniversaryWorld)
            {
                int x15 = undergroundDesertLocation.Center.X;
                int j4 = undergroundDesertLocation.Top - 10;
                Pyramid(x15, j4);
            }
            for (int num689 = 0; num689 < GenVars.numPyr; num689++)
            {
                int num690 = GenVars.PyrX[num689];
                int num691 = GenVars.PyrY[num689];
                if (num690 > 300 && num690 < Main.maxTilesX - 300 && (GenVars.dungeonSide >= 0 || !((double)num690 < (double)GenVars.dungeonX + (double)Main.maxTilesX * 0.15)) && (GenVars.dungeonSide <= 0 || !((double)num690 > (double)GenVars.dungeonX - (double)Main.maxTilesX * 0.15)) && (!Main.tenthAnniversaryWorld || !undergroundDesertLocation.Contains(num690, num691)))
                {
                    for (; !Main.tile[num690, num691].active() && (double)num691 < Main.worldSurface; num691++)
                    {
                    }
                    if (!((double)num691 >= Main.worldSurface) && Main.tile[num690, num691].type == 53)
                    {
                        int num692 = Main.maxTilesX;
                        for (int num693 = 0; num693 < num689; num693++)
{
                            int num694 = Math.Abs(num690 - GenVars.PyrX[num693]);
                            if (num694 < num692)
{
                                num692 = num694;
                            }
                        }
                        int num695 = 220;
                        if (drunkWorldGen)
{
                            num695 /= 2;
                        }
                        if (num692 >= num695)
{
                            num691--;
                            Pyramid(num690, num691);
                        }
                    }
                }
            }
        });
        AddGenerationPass("Dirt Rock Wall Runner", delegate
        {
            for (int num686 = 0; num686 < Main.maxTilesX; num686++)
            {
                int num687 = genRand.Next(10, Main.maxTilesX - 10);
                int num688 = genRand.Next(10, (int)Main.worldSurface);
                if (Main.tile[num687, num688].wall == 2)
                {
                    DirtyRockRunner(num687, num688);
                }
            }
        });
        AddGenerationPass("Living Trees", delegate
        {
            int num669 = 200;
            double num670 = (double)Main.maxTilesX / 4200.0;
            int num671 = genRand.Next(0, (int)(2.0 * num670) + 1);
            if (num671 == 0 && genRand.Next(2) == 0)
            {
                num671++;
            }
            if (drunkWorldGen)
            {
                num671 += (int)(2.0 * num670);
            }
            else if (Main.tenthAnniversaryWorld)
            {
                num671 += (int)(3.0 * num670);
            }
            else if (remixWorldGen)
            {
                num671 += (int)(2.0 * num670);
            }
            for (int num672 = 0; num672 < num671; num672++)
            {
                bool flag41 = false;
                int num673 = 0;
                while (!flag41)
                {
                    num673++;
                    if (num673 > Main.maxTilesX / 2)
                    {
                        flag41 = true;
                    }
                    int num674 = genRand.Next(beachDistance, Main.maxTilesX - beachDistance);
                    if (tenthAnniversaryWorldGen && !remixWorldGen)
                    {
                        num674 = genRand.Next((int)((double)Main.maxTilesX * 0.15), (int)((float)Main.maxTilesX * 0.85f));
                    }
                    if (num674 <= Main.maxTilesX / 2 - num669 || num674 >= Main.maxTilesX / 2 + num669)
                    {
                        int num675;
                        for (num675 = 0; !Main.tile[num674, num675].active() && (double)num675 < Main.worldSurface; num675++)
{
                        }
                        if (Main.tile[num674, num675].type == 0)
{
                            num675--;
                            if (num675 > 150)
{
                                bool flag42 = true;
                                for (int num676 = num674 - 50; num676 < num674 + 50; num676++)
{
                                    for (int num677 = num675 - 50; num677 < num675 + 50; num677++)
{
                                        if (Main.tile[num676, num677].active())
{
                                            switch (Main.tile[num676, num677].type)
{
                                            case 41:
                                            case 43:
                                            case 44:
                                            case 189:
                                            case 196:
                                            case 460:
                                            case 481:
                                            case 482:
                                            case 483:
                                                flag42 = false;
                                                break;
                                            }
                                        }
                                    }
                                }
                                for (int num678 = 0; num678 < GenVars.numMCaves; num678++)
{
                                    if (num674 > GenVars.mCaveX[num678] - 50 && num674 < GenVars.mCaveX[num678] + 50)
{
                                        flag42 = false;
                                        break;
                                    }
                                }
                                if (flag42)
{
                                    flag41 = GrowLivingTree(num674, num675);
                                    if (flag41)
{
                                        for (int num679 = -1; num679 <= 1; num679++)
{
                                            if (num679 != 0)
{
                                                int num680 = num674;
                                                int num681 = genRand.Next(4);
                                                if (drunkWorldGen || Main.tenthAnniversaryWorld)
{
                                                    num681 += genRand.Next(2, 5);
                                                }
                                                else if (remixWorldGen)
{
                                                    num681 += genRand.Next(1, 6);
                                                }
                                                for (int num682 = 0; num682 < num681; num682++)
{
                                                    num680 += genRand.Next(13, 31) * num679;
                                                    if (num680 <= Main.maxTilesX / 2 - num669 || num680 >= Main.maxTilesX / 2 + num669)
{
                                                        int num683 = num675;
                                                        if (Main.tile[num680, num683].active())
{
                                                            while (Main.tile[num680, num683].active())
{
                                                                num683--;
                                                            }
                                                        }
                                                        else
{
                                                            for (; !Main.tile[num680, num683].active(); num683++)
{
                                                            }
                                                            num683--;
                                                        }
                                                        flag42 = true;
                                                        for (int num684 = num674 - 50; num684 < num674 + 50; num684++)
{
                                                            for (int num685 = num675 - 50; num685 < num675 + 50; num685++)
{
                                                                if (Main.tile[num684, num685].active())
{
                                                                    switch (Main.tile[num684, num685].type)
{
                                                                    case 41:
                                                                    case 43:
                                                                    case 44:
                                                                    case 189:
                                                                    case 196:
                                                                    case 460:
                                                                    case 481:
                                                                    case 482:
                                                                    case 483:
                                                                        flag42 = false;
                                                                        break;
                                                                    }
                                                                }
                                                            }
                                                        }
                                                        if (flag42)
{
                                                            GrowLivingTree(num680, num683, patch: true);
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
            Main.tileSolid[192] = false;
        });
        AddGenerationPass("Wood Tree Walls", delegate
        {
            for (int num665 = 25; num665 < Main.maxTilesX - 25; num665++)
            {
                for (int num666 = 25; (double)num666 < Main.worldSurface; num666++)
                {
                    if (Main.tile[num665, num666].type == 191 || Main.tile[num665, num666 - 1].type == 191 || Main.tile[num665 - 1, num666].type == 191 || Main.tile[num665 + 1, num666].type == 191 || Main.tile[num665, num666 + 1].type == 191)
                    {
                        bool flag40 = true;
                        for (int num667 = num665 - 1; num667 <= num665 + 1; num667++)
{
                            for (int num668 = num666 - 1; num668 <= num666 + 1; num668++)
{
                                if (num667 != num665 && num668 != num666 && Main.tile[num667, num668].type != 191 && Main.tile[num667, num668].wall != 244)
{
                                    flag40 = false;
                                }
                            }
                        }
                        if (flag40)
{
                            Main.tile[num665, num666].wall = 244;
                        }
                    }
                }
            }
        });
        AddGenerationPass("Altars", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            //IL_01ff: Unknown result type (might be due to invalid IL or missing references)
            //IL_0204: Unknown result type (might be due to invalid IL or missing references)
            Main.tileSolid[484] = false;
            progress.Message = Lang.gen[26].Value;
            int num660 = (int)((double)(Main.maxTilesX * Main.maxTilesY) * 3.3E-06);
            if (remixWorldGen)
            {
                num660 *= 3;
            }
            for (int num661 = 0; num661 < num660; num661++)
            {
                progress.Set((double)num661 / (double)num660);
                for (int num662 = 0; num662 < 10000; num662++)
                {
                    int num663 = genRand.Next(281, Main.maxTilesX - 3 - 280);
                    while ((double)num663 > (double)Main.maxTilesX * 0.45 && (double)num663 < (double)Main.maxTilesX * 0.55)
                    {
                        num663 = genRand.Next(281, Main.maxTilesX - 3 - 280);
                    }
                    int num664 = genRand.Next((int)(Main.worldSurface * 2.0 + Main.rockLayer) / 3, (int)(Main.rockLayer + (double)((Main.maxTilesY - 350) * 2)) / 3);
                    if (remixWorldGen)
                    {
                        num664 = genRand.Next(100, (int)((double)Main.maxTilesY * 0.9));
                    }
                    while (oceanDepths(num663, num664) || Vector2D.Distance(new Vector2D((double)num663, (double)num664), GenVars.shimmerPosition) < (double)shimmerSafetyDistance)
                    {
                        num663 = genRand.Next(281, Main.maxTilesX - 3 - 280);
                        while ((double)num663 > (double)Main.maxTilesX * 0.45 && (double)num663 < (double)Main.maxTilesX * 0.55)
{
                            num663 = genRand.Next(281, Main.maxTilesX - 3 - 280);
                        }
                        num664 = genRand.Next((int)(Main.worldSurface * 2.0 + Main.rockLayer) / 3, (int)(Main.rockLayer + (double)((Main.maxTilesY - 350) * 2)) / 3);
                        if (remixWorldGen)
{
                            num664 = genRand.Next(100, (int)((double)Main.maxTilesY * 0.9));
                        }
                    }
                    int style2 = (crimson ? 1 : 0);
                    if (drunkWorldGen)
                    {
                        style2 = (GenVars.crimsonLeft ? ((num663 < Main.maxTilesX / 2) ? 1 : 0) : ((num663 >= Main.maxTilesX / 2) ? 1 : 0));
                    }
                    if (!IsTileNearby(num663, num664, 26, 3))
                    {
                        Place3x2(num663, num664, 26, style2);
                    }
                    if (Main.tile[num663, num664].type == 26)
                    {
                        break;
                    }
                }
            }
        });
        AddGenerationPass("Wet Jungle", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            progress.Set(1.0);
            for (int num658 = 0; num658 < Main.maxTilesX; num658++)
            {
                for (int num659 = (int)GenVars.worldSurfaceLow; (double)num659 < Main.worldSurface - 1.0; num659++)
                {
                    if (Main.tile[num658, num659].active())
                    {
                        if (Main.tile[num658, num659].type == 60)
{
                            Main.tile[num658, num659 - 1].liquid = byte.MaxValue;
                            Main.tile[num658, num659 - 2].liquid = byte.MaxValue;
                        }
                        break;
                    }
                }
            }
        });
        AddGenerationPass("Jungle Temple", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            int num648 = 0;
            progress.Message = Lang.gen[70].Value;
            long num649 = 0L;
            double num650 = 0.25;
            bool flag38 = false;
            while (true)
            {
                int num651 = (int)Main.rockLayer;
                int num652 = Main.maxTilesY - 500;
                if (num651 > num652 - 1)
                {
                    num651 = num652 - 1;
                }
                int num653 = genRand.Next(num651, num652);
                int num654 = (int)(((genRand.NextDouble() * num650 + 0.1) * (double)(-GenVars.dungeonSide) + 0.5) * (double)Main.maxTilesX);
                if (remixWorldGen)
                {
                    if (notTheBees)
                    {
                        num654 = ((GenVars.dungeonSide <= 0) ? genRand.Next((int)((double)Main.maxTilesX * 0.6), (int)((double)Main.maxTilesX * 0.8)) : genRand.Next((int)((double)Main.maxTilesX * 0.2), (int)((double)Main.maxTilesX * 0.4)));
                    }
                    else
                    {
                        num654 = genRand.Next((int)((double)Main.maxTilesX * 0.2), (int)((double)Main.maxTilesX * 0.8));
                        while ((double)num654 > (double)Main.maxTilesX * 0.4 && (double)num654 < (double)Main.maxTilesX * 0.6)
{
                            num654 = genRand.Next((int)((double)Main.maxTilesX * 0.2), (int)((double)Main.maxTilesX * 0.8));
                        }
                    }
                    while (Main.tile[num654, num653].active() || Main.tile[num654, num653].wall > 0 || (double)num653 > Main.worldSurface - 5.0)
                    {
                        num653--;
                    }
                    num653++;
                    if (Main.tile[num654, num653].active() && (Main.tile[num654, num653].type == 60 || Main.tile[num654, num653].type == 59))
                    {
                        int num655 = 10;
                        bool flag39 = false;
                        for (int num656 = num654 - num655; num656 <= num656 + num655; num656++)
{
                            for (int num657 = num653 - num655; num657 < num655; num657++)
{
                                if (Main.tile[num656, num657].type == 191 || Main.tileDungeon[Main.tile[num656, num657].type])
{
                                    flag39 = true;
                                }
                            }
                        }
                        if (!flag39)
{
                            flag38 = true;
                            num653 -= 10 + genRand.Next(10);
                            makeTemple(num654, num653);
                            break;
                        }
                    }
                }
                else if (Main.tile[num654, num653].active() && Main.tile[num654, num653].type == 60)
                {
                    flag38 = true;
                    makeTemple(num654, num653);
                    break;
                }
                if (num649++ > 2000000)
                {
                    if (num650 == 0.35)
                    {
                        num648++;
                        if (num648 > 10)
{
                            break;
                        }
                    }
                    num650 = Math.Min(0.35, num650 + 0.05);
                    num649 = 0L;
                }
            }
            if (!flag38)
            {
                int x14 = Main.maxTilesX - GenVars.dungeonX;
                int y14 = (int)Main.rockLayer + 100;
                if (remixWorldGen)
                {
                    x14 = ((!notTheBees) ? ((GenVars.dungeonSide > 0) ? ((int)((double)Main.maxTilesX * 0.4)) : ((int)((double)Main.maxTilesX * 0.6))) : ((GenVars.dungeonSide > 0) ? ((int)((double)Main.maxTilesX * 0.3)) : ((int)((double)Main.maxTilesX * 0.7))));
                }
                makeTemple(x14, y14);
            }
        });
        AddGenerationPass("Hives", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            progress.Message = Lang.gen[71].Value;
            double num639 = (double)Main.maxTilesX / 4200.0;
            double num640 = 1 + genRand.Next((int)(5.0 * num639), (int)(8.0 * num639));
            if (drunkWorldGen)
            {
                num640 *= 0.667;
            }
            int num641 = 10000;
            HiveBiome hiveBiome = GenVars.configuration.CreateBiome<HiveBiome>();
            HoneyPatchBiome honeyPatchBiome = GenVars.configuration.CreateBiome<HoneyPatchBiome>();
            while (num640 > 0.0 && num641 > 0)
            {
                num641--;
                Point origin3 = RandomWorldPoint((int)(Main.worldSurface + Main.rockLayer) >> 1, 20, 300, 20);
                if (drunkWorldGen)
                {
                    RandomWorldPoint((int)Main.worldSurface, 20, 300, 20);
                }
                if (hiveBiome.Place(origin3, GenVars.structures))
                {
                    num640 -= 1.0;
                    int num642 = genRand.Next(5);
                    int num643 = 0;
                    int num644 = 10000;
                    while (num643 < num642 && num644 > 0)
                    {
                        double num645 = genRand.NextDouble() * 60.0 + 30.0;
                        double num646 = genRand.NextDouble() * 6.2831854820251465;
                        int num647 = (int)(Math.Cos(num646) * num645) + origin3.X;
                        int y13 = (int)(Math.Sin(num646) * num645) + origin3.Y;
                        num644--;
                        if (num647 > 50 && num647 < Main.maxTilesX - 50 && honeyPatchBiome.Place(new Point(num647, y13), GenVars.structures))
{
                            num643++;
                        }
                    }
                }
            }
        });
        AddGenerationPass("Jungle Chests", delegate
        {
            int num613 = genRand.Next(40, Main.maxTilesX - 40);
            int num614 = genRand.Next((int)(Main.worldSurface + Main.rockLayer) / 2, Main.maxTilesY - 400);
            double num615 = genRand.Next(7, 12);
            num615 *= (double)Main.maxTilesX / 4200.0;
            int num616 = 0;
            for (int num617 = 0; (double)num617 < num615; num617++)
            {
                bool flag36 = true;
                while (flag36)
                {
                    num616++;
                    num613 = genRand.Next(40, Main.maxTilesX / 2 - 40);
                    if (GenVars.dungeonSide < 0)
                    {
                        num613 += Main.maxTilesX / 2;
                    }
                    num614 = genRand.Next((int)(Main.worldSurface + Main.rockLayer) / 2, Main.maxTilesY - 400);
                    int num618 = genRand.Next(2, 4);
                    int num619 = genRand.Next(2, 4);
                    Rectangle area = new Rectangle(num613 - num618 - 1, num614 - num619 - 1, num618 + 1, num619 + 1);
                    if (Main.tile[num613, num614].type == 60)
                    {
                        int num620 = 30;
                        flag36 = false;
                        for (int num621 = num613 - num620; num621 < num613 + num620; num621 += 3)
{
                            for (int num622 = num614 - num620; num622 < num614 + num620; num622 += 3)
{
                                if (Main.tile[num621, num622].active() && (Main.tile[num621, num622].type == 225 || Main.tile[num621, num622].type == 229 || Main.tile[num621, num622].type == 226 || Main.tile[num621, num622].type == 119 || Main.tile[num621, num622].type == 120))
{
                                    flag36 = true;
                                }
                                if (Main.tile[num621, num622].wall == 86 || Main.tile[num621, num622].wall == 87)
{
                                    flag36 = true;
                                }
                            }
                        }
                        if (!GenVars.structures.CanPlace(area, 1))
{
                            flag36 = true;
                        }
                    }
                    if (!flag36)
                    {
                        ushort wall2 = 0;
                        if (GenVars.jungleHut == 119)
{
                            wall2 = 23;
                        }
                        else if (GenVars.jungleHut == 120)
{
                            wall2 = 24;
                        }
                        else if (GenVars.jungleHut == 158)
{
                            wall2 = 42;
                        }
                        else if (GenVars.jungleHut == 175)
{
                            wall2 = 45;
                        }
                        else if (GenVars.jungleHut == 45)
{
                            wall2 = 10;
                        }
                        for (int num623 = num613 - num618 - 1; num623 <= num613 + num618 + 1; num623++)
{
                            for (int num624 = num614 - num619 - 1; num624 <= num614 + num619 + 1; num624++)
{
                                Main.tile[num623, num624].active(active: true);
                                Main.tile[num623, num624].type = GenVars.jungleHut;
                                Main.tile[num623, num624].liquid = 0;
                                Main.tile[num623, num624].lava(lava: false);
                            }
                        }
                        for (int num625 = num613 - num618; num625 <= num613 + num618; num625++)
{
                            for (int num626 = num614 - num619; num626 <= num614 + num619; num626++)
{
                                Main.tile[num625, num626].active(active: false);
                                Main.tile[num625, num626].wall = wall2;
                            }
                        }
                        bool flag37 = false;
                        int num627 = 0;
                        while (!flag37 && num627 < 100)
{
                            num627++;
                            int num628 = genRand.Next(num613 - num618, num613 + num618 + 1);
                            int num629 = genRand.Next(num614 - num619, num614 + num619 - 2);
                            PlaceTile(num628, num629, 4, mute: true, forced: false, -1, 3);
                            if (Main.tile[num628, num629].type == 4)
{
                                flag37 = true;
                            }
                        }
                        for (int num630 = num613 - num618 - 1; num630 <= num613 + num618 + 1; num630++)
{
                            for (int num631 = num614 + num619 - 2; num631 <= num614 + num619; num631++)
{
                                Main.tile[num630, num631].active(active: false);
                            }
                        }
                        for (int num632 = num613 - num618 - 1; num632 <= num613 + num618 + 1; num632++)
{
                            for (int num633 = num614 + num619 - 2; num633 <= num614 + num619 - 1; num633++)
{
                                Main.tile[num632, num633].active(active: false);
                            }
                        }
                        for (int num634 = num613 - num618 - 1; num634 <= num613 + num618 + 1; num634++)
{
                            int num635 = 4;
                            int num636 = num614 + num619 + 2;
                            while (!Main.tile[num634, num636].active() && num636 < Main.maxTilesY && num635 > 0)
{
                                Main.tile[num634, num636].active(active: true);
                                Main.tile[num634, num636].type = 59;
                                num636++;
                                num635--;
                            }
                        }
                        num618 -= genRand.Next(1, 3);
                        int num637 = num614 - num619 - 2;
                        while (num618 > -1)
{
                            for (int num638 = num613 - num618 - 1; num638 <= num613 + num618 + 1; num638++)
{
                                Main.tile[num638, num637].active(active: true);
                                Main.tile[num638, num637].type = GenVars.jungleHut;
                            }
                            num618 -= genRand.Next(1, 3);
                            num637--;
                        }
                        GenVars.JChestX[GenVars.numJChests] = num613;
                        GenVars.JChestY[GenVars.numJChests] = num614;
                        GenVars.structures.AddProtectedStructure(area);
                        GenVars.numJChests++;
                        num616 = 0;
                    }
                    else if (num616 > Main.maxTilesX * 10)
                    {
                        num617++;
                        num616 = 0;
                        break;
                    }
                }
            }
            Main.tileSolid[137] = false;
        });
        AddGenerationPass("Settle Liquids", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            progress.Message = Lang.gen[27].Value;
            if (notTheBees)
            {
                NotTheBees();
            }
            Liquid.worldGenTilesIgnoreWater(ignoreSolids: true);
            Liquid.QuickWater(3);
            WaterCheck();
            int num606 = 0;
            Liquid.quickSettle = true;
            int num607 = 10;
            while (num606 < num607)
            {
                int num608 = Liquid.numLiquid + LiquidBuffer.numLiquidBuffer;
                num606++;
                double num609 = 0.0;
                int num610 = num608 * 5;
                while (Liquid.numLiquid > 0)
                {
                    num610--;
                    if (num610 < 0)
                    {
                        break;
                    }
                    double num611 = (double)(num608 - (Liquid.numLiquid + LiquidBuffer.numLiquidBuffer)) / (double)num608;
                    if (Liquid.numLiquid + LiquidBuffer.numLiquidBuffer > num608)
                    {
                        num608 = Liquid.numLiquid + LiquidBuffer.numLiquidBuffer;
                    }
                    if (num611 > num609)
                    {
                        num609 = num611;
                    }
                    else
                    {
                        num611 = num609;
                    }
                    if (num606 == 1)
                    {
                        progress.Set(num611 / 3.0 + 0.33);
                    }
                    int num612 = 10;
                    if (num606 > num612)
                    {
                        num612 = num606;
                    }
                    Liquid.UpdateLiquid();
                }
                WaterCheck();
                progress.Set((double)num606 * 0.1 / 3.0 + 0.66);
            }
            Liquid.quickSettle = false;
            Liquid.worldGenTilesIgnoreWater(ignoreSolids: false);
            Main.tileSolid[484] = false;
        });
        AddGenerationPass("Remove Water From Sand", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            progress.Set(1.0);
            for (int num603 = 400; num603 < Main.maxTilesX - 400; num603++)
            {
                for (int num604 = 100; (double)num604 < Main.worldSurface - 1.0; num604++)
                {
                    if (Main.tile[num603, num604].active())
                    {
                        ushort type7 = Main.tile[num603, num604].type;
                        if (type7 == 53 || type7 == 396 || type7 == 397 || type7 == 404 || type7 == 407 || type7 == 151)
{
                            int num605 = num604;
                            while (num605 > 100)
{
                                num605--;
                                if (Main.tile[num603, num605].active())
{
                                    break;
                                }
                                Main.tile[num603, num605].liquid = 0;
                            }
                        }
                        break;
                    }
                }
            }
            Main.tileSolid[192] = true;
        });
        AddGenerationPass("Oasis", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            if (!notTheBees)
            {
                progress.Set(1.0);
                int num599 = Main.maxTilesX / 2100;
                num599 += genRand.Next(2);
                for (int num600 = 0; num600 < num599; num600++)
                {
                    int num601 = beachDistance + 300;
                    int num602 = Main.maxTilesX * 2;
                    while (num602 > 0)
                    {
                        num602--;
                        int x13 = genRand.Next(num601, Main.maxTilesX - num601);
                        int y12 = genRand.Next(100, (int)Main.worldSurface);
                        if (PlaceOasis(x13, y12))
{
                            num602 = -1;
                        }
                    }
                }
            }
        });
        AddGenerationPass("Shell Piles", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            if (dontStarveWorldGen)
            {
                int num587 = (int)(5.0 * ((double)Main.maxTilesX / 4200.0));
                int num588 = 0;
                int num589 = 100;
                int num590 = Main.maxTilesX / 2;
                int num591 = num590 - num589;
                int num592 = num590 + num589;
                for (int num593 = 0; num593 < 80; num593++)
                {
                    int num594 = genRand.Next(100, Main.maxTilesX - 100);
                    if (num594 >= num591 && num594 <= num592)
                    {
                        num594 = genRand.Next(100, Main.maxTilesX - 100);
                        if (num594 >= num591 && num594 <= num592)
{
                            continue;
                        }
                    }
                    int y11 = (int)Main.worldSurface / 2;
                    if (MarblePileWithStatues(num594, y11))
                    {
                        num588++;
                        if (num588 >= num587)
{
                            break;
                        }
                    }
                }
            }
            if (!notTheBees)
            {
                progress.Set(1.0);
                if (genRand.Next(2) == 0)
                {
                    int shellStartXLeft = GenVars.shellStartXLeft;
                    int shellStartYLeft = GenVars.shellStartYLeft;
                    for (int num595 = shellStartXLeft - 20; num595 <= shellStartXLeft + 20; num595++)
                    {
                        for (int num596 = shellStartYLeft - 10; num596 <= shellStartYLeft + 10; num596++)
{
                            if (Main.tile[num595, num596].active() && Main.tile[num595, num596].type == 53 && !Main.tile[num595, num596 - 1].active() && Main.tile[num595, num596 - 1].liquid == 0 && !Main.tile[num595 - 1, num596].active() && Main.tile[num595 - 1, num596].liquid > 0)
{
                                GenVars.shellStartXLeft = num595;
                                GenVars.shellStartYLeft = num596;
                            }
                        }
                    }
                    GenVars.shellStartYLeft -= 50;
                    GenVars.shellStartXLeft -= genRand.Next(5);
                    if (genRand.Next(2) == 0)
                    {
                        GenVars.shellStartXLeft -= genRand.Next(10);
                    }
                    if (genRand.Next(3) == 0)
                    {
                        GenVars.shellStartXLeft -= genRand.Next(15);
                    }
                    if (genRand.Next(4) != 0)
                    {
                        ShellPile(GenVars.shellStartXLeft, GenVars.shellStartYLeft);
                    }
                    int maxValue9 = genRand.Next(2, 4);
                    if (genRand.Next(maxValue9) == 0)
                    {
                        ShellPile(GenVars.shellStartXLeft - genRand.Next(10, 35), GenVars.shellStartYLeft);
                    }
                    if (genRand.Next(maxValue9) == 0)
                    {
                        ShellPile(GenVars.shellStartXLeft - genRand.Next(40, 65), GenVars.shellStartYLeft);
                    }
                    if (genRand.Next(maxValue9) == 0)
                    {
                        ShellPile(GenVars.shellStartXLeft - genRand.Next(70, 95), GenVars.shellStartYLeft);
                    }
                    if (genRand.Next(maxValue9) == 0)
                    {
                        ShellPile(GenVars.shellStartXLeft - genRand.Next(100, 125), GenVars.shellStartYLeft);
                    }
                    if (genRand.Next(maxValue9) == 0)
                    {
                        ShellPile(GenVars.shellStartXLeft + genRand.Next(10, 25), GenVars.shellStartYLeft);
                    }
                }
                if (genRand.Next(2) == 0)
                {
                    int shellStartXRight = GenVars.shellStartXRight;
                    int shellStartYRight = GenVars.shellStartYRight;
                    for (int num597 = shellStartXRight - 20; num597 <= shellStartXRight + 20; num597++)
                    {
                        for (int num598 = shellStartYRight - 10; num598 <= shellStartYRight + 10; num598++)
{
                            if (Main.tile[num597, num598].active() && Main.tile[num597, num598].type == 53 && !Main.tile[num597, num598 - 1].active() && Main.tile[num597, num598 - 1].liquid == 0 && !Main.tile[num597 + 1, num598].active() && Main.tile[num597 + 1, num598].liquid > 0)
{
                                GenVars.shellStartXRight = num597;
                                GenVars.shellStartYRight = num598;
                            }
                        }
                    }
                    GenVars.shellStartYRight -= 50;
                    GenVars.shellStartXRight += genRand.Next(5);
                    if (genRand.Next(2) == 0)
                    {
                        GenVars.shellStartXLeft += genRand.Next(10);
                    }
                    if (genRand.Next(3) == 0)
                    {
                        GenVars.shellStartXLeft += genRand.Next(15);
                    }
                    if (genRand.Next(4) != 0)
                    {
                        ShellPile(GenVars.shellStartXRight, GenVars.shellStartYRight);
                    }
                    int maxValue10 = genRand.Next(2, 4);
                    if (genRand.Next(maxValue10) == 0)
                    {
                        ShellPile(GenVars.shellStartXRight + genRand.Next(10, 35), GenVars.shellStartYRight);
                    }
                    if (genRand.Next(maxValue10) == 0)
                    {
                        ShellPile(GenVars.shellStartXRight + genRand.Next(40, 65), GenVars.shellStartYRight);
                    }
                    if (genRand.Next(maxValue10) == 0)
                    {
                        ShellPile(GenVars.shellStartXRight + genRand.Next(70, 95), GenVars.shellStartYRight);
                    }
                    if (genRand.Next(maxValue10) == 0)
                    {
                        ShellPile(GenVars.shellStartXRight + genRand.Next(100, 125), GenVars.shellStartYRight);
                    }
                    if (genRand.Next(maxValue10) == 0)
                    {
                        ShellPile(GenVars.shellStartXRight - genRand.Next(10, 25), GenVars.shellStartYRight);
                    }
                }
            }
        });
        AddGenerationPass("Smooth World", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            progress.Message = Lang.gen[60].Value;
            Main.tileSolid[GenVars.crackedType] = true;
            for (int num583 = 20; num583 < Main.maxTilesX - 20; num583++)
            {
                double value11 = (double)num583 / (double)Main.maxTilesX;
                progress.Set(value11);
                for (int num584 = 20; num584 < Main.maxTilesY - 20; num584++)
                {
                    if (Main.tile[num583, num584].type != 48 && Main.tile[num583, num584].type != 137 && Main.tile[num583, num584].type != 232 && Main.tile[num583, num584].type != 191 && Main.tile[num583, num584].type != 151 && Main.tile[num583, num584].type != 274)
                    {
                        if (!Main.tile[num583, num584 - 1].active() && Main.tile[num583 - 1, num584].type != 136 && Main.tile[num583 + 1, num584].type != 136)
{
                            if (SolidTile(num583, num584) && TileID.Sets.CanBeClearedDuringGeneration[Main.tile[num583, num584].type])
{
                                if (!Main.tile[num583 - 1, num584].halfBrick() && !Main.tile[num583 + 1, num584].halfBrick() && Main.tile[num583 - 1, num584].slope() == 0 && Main.tile[num583 + 1, num584].slope() == 0)
{
                                    if (SolidTile(num583, num584 + 1))
{
                                        if (!SolidTile(num583 - 1, num584) && !Main.tile[num583 - 1, num584 + 1].halfBrick() && SolidTile(num583 - 1, num584 + 1) && SolidTile(num583 + 1, num584) && !Main.tile[num583 + 1, num584 - 1].active())
{
                                            if (genRand.Next(2) == 0)
{
                                                SlopeTile(num583, num584, 2);
                                            }
                                            else
{
                                                PoundTile(num583, num584);
                                            }
                                        }
                                        else if (!SolidTile(num583 + 1, num584) && !Main.tile[num583 + 1, num584 + 1].halfBrick() && SolidTile(num583 + 1, num584 + 1) && SolidTile(num583 - 1, num584) && !Main.tile[num583 - 1, num584 - 1].active())
{
                                            if (genRand.Next(2) == 0)
{
                                                SlopeTile(num583, num584, 1);
                                            }
                                            else
{
                                                PoundTile(num583, num584);
                                            }
                                        }
                                        else if (SolidTile(num583 + 1, num584 + 1) && SolidTile(num583 - 1, num584 + 1) && !Main.tile[num583 + 1, num584].active() && !Main.tile[num583 - 1, num584].active())
{
                                            PoundTile(num583, num584);
                                        }
                                        if (SolidTile(num583, num584))
{
                                            if (SolidTile(num583 - 1, num584) && SolidTile(num583 + 1, num584 + 2) && !Main.tile[num583 + 1, num584].active() && !Main.tile[num583 + 1, num584 + 1].active() && !Main.tile[num583 - 1, num584 - 1].active())
{
                                                KillTile(num583, num584);
                                            }
                                            else if (SolidTile(num583 + 1, num584) && SolidTile(num583 - 1, num584 + 2) && !Main.tile[num583 - 1, num584].active() && !Main.tile[num583 - 1, num584 + 1].active() && !Main.tile[num583 + 1, num584 - 1].active())
{
                                                KillTile(num583, num584);
                                            }
                                            else if (!Main.tile[num583 - 1, num584 + 1].active() && !Main.tile[num583 - 1, num584].active() && SolidTile(num583 + 1, num584) && SolidTile(num583, num584 + 2))
{
                                                if (genRand.Next(5) == 0)
{
                                                    KillTile(num583, num584);
                                                }
                                                else if (genRand.Next(5) == 0)
{
                                                    PoundTile(num583, num584);
                                                }
                                                else
{
                                                    SlopeTile(num583, num584, 2);
                                                }
                                            }
                                            else if (!Main.tile[num583 + 1, num584 + 1].active() && !Main.tile[num583 + 1, num584].active() && SolidTile(num583 - 1, num584) && SolidTile(num583, num584 + 2))
{
                                                if (genRand.Next(5) == 0)
{
                                                    KillTile(num583, num584);
                                                }
                                                else if (genRand.Next(5) == 0)
{
                                                    PoundTile(num583, num584);
                                                }
                                                else
{
                                                    SlopeTile(num583, num584, 1);
                                                }
                                            }
                                        }
                                    }
                                    if (SolidTile(num583, num584) && !Main.tile[num583 - 1, num584].active() && !Main.tile[num583 + 1, num584].active())
{
                                        KillTile(num583, num584);
                                    }
                                }
                            }
                            else if (!Main.tile[num583, num584].active() && Main.tile[num583, num584 + 1].type != 151 && Main.tile[num583, num584 + 1].type != 274)
{
                                if (Main.tile[num583 + 1, num584].type != 190 && Main.tile[num583 + 1, num584].type != 48 && Main.tile[num583 + 1, num584].type != 232 && SolidTile(num583 - 1, num584 + 1) && SolidTile(num583 + 1, num584) && !Main.tile[num583 - 1, num584].active() && !Main.tile[num583 + 1, num584 - 1].active())
{
                                    if (Main.tile[num583 + 1, num584].type == 495)
{
                                        PlaceTile(num583, num584, Main.tile[num583 + 1, num584].type);
                                    }
                                    else
{
                                        PlaceTile(num583, num584, Main.tile[num583, num584 + 1].type);
                                    }
                                    if (genRand.Next(2) == 0)
{
                                        SlopeTile(num583, num584, 2);
                                    }
                                    else
{
                                        PoundTile(num583, num584);
                                    }
                                }
                                if (Main.tile[num583 - 1, num584].type != 190 && Main.tile[num583 - 1, num584].type != 48 && Main.tile[num583 - 1, num584].type != 232 && SolidTile(num583 + 1, num584 + 1) && SolidTile(num583 - 1, num584) && !Main.tile[num583 + 1, num584].active() && !Main.tile[num583 - 1, num584 - 1].active())
{
                                    if (Main.tile[num583 - 1, num584].type == 495)
{
                                        PlaceTile(num583, num584, Main.tile[num583 - 1, num584].type);
                                    }
                                    else
{
                                        PlaceTile(num583, num584, Main.tile[num583, num584 + 1].type);
                                    }
                                    if (genRand.Next(2) == 0)
{
                                        SlopeTile(num583, num584, 1);
                                    }
                                    else
{
                                        PoundTile(num583, num584);
                                    }
                                }
                            }
                        }
                        else if (!Main.tile[num583, num584 + 1].active() && genRand.Next(2) == 0 && SolidTile(num583, num584) && !Main.tile[num583 - 1, num584].halfBrick() && !Main.tile[num583 + 1, num584].halfBrick() && Main.tile[num583 - 1, num584].slope() == 0 && Main.tile[num583 + 1, num584].slope() == 0 && SolidTile(num583, num584 - 1))
{
                            if (SolidTile(num583 - 1, num584) && !SolidTile(num583 + 1, num584) && SolidTile(num583 - 1, num584 - 1))
{
                                SlopeTile(num583, num584, 3);
                            }
                            else if (SolidTile(num583 + 1, num584) && !SolidTile(num583 - 1, num584) && SolidTile(num583 + 1, num584 - 1))
{
                                SlopeTile(num583, num584, 4);
                            }
                        }
                        if (TileID.Sets.Conversion.Sand[Main.tile[num583, num584].type])
{
                            Tile.SmoothSlope(num583, num584, applyToNeighbors: false);
                        }
                    }
                }
            }
            for (int num585 = 20; num585 < Main.maxTilesX - 20; num585++)
            {
                for (int num586 = 20; num586 < Main.maxTilesY - 20; num586++)
                {
                    if (genRand.Next(2) == 0 && !Main.tile[num585, num586 - 1].active() && Main.tile[num585, num586].type != 137 && Main.tile[num585, num586].type != 48 && Main.tile[num585, num586].type != 232 && Main.tile[num585, num586].type != 191 && Main.tile[num585, num586].type != 151 && Main.tile[num585, num586].type != 274 && Main.tile[num585, num586].type != 75 && Main.tile[num585, num586].type != 76 && SolidTile(num585, num586) && Main.tile[num585 - 1, num586].type != 137 && Main.tile[num585 + 1, num586].type != 137)
                    {
                        if (SolidTile(num585, num586 + 1) && SolidTile(num585 + 1, num586) && !Main.tile[num585 - 1, num586].active())
{
                            SlopeTile(num585, num586, 2);
                        }
                        if (SolidTile(num585, num586 + 1) && SolidTile(num585 - 1, num586) && !Main.tile[num585 + 1, num586].active())
{
                            SlopeTile(num585, num586, 1);
                        }
                    }
                    if (Main.tile[num585, num586].slope() == 1 && !SolidTile(num585 - 1, num586))
                    {
                        SlopeTile(num585, num586);
                        PoundTile(num585, num586);
                    }
                    if (Main.tile[num585, num586].slope() == 2 && !SolidTile(num585 + 1, num586))
                    {
                        SlopeTile(num585, num586);
                        PoundTile(num585, num586);
                    }
                }
            }
            Main.tileSolid[137] = true;
            Main.tileSolid[190] = false;
            Main.tileSolid[192] = false;
            Main.tileSolid[GenVars.crackedType] = false;
        });
        AddGenerationPass("Waterfalls", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            progress.Message = Lang.gen[69].Value;
            Main.tileSolid[191] = false;
            for (int num574 = 20; num574 < Main.maxTilesX - 20; num574++)
            {
                double num575 = (double)num574 / (double)Main.maxTilesX;
                progress.Set(num575 * 0.5);
                for (int num576 = 20; num576 < Main.maxTilesY - 20; num576++)
                {
                    if (SolidTile(num574, num576) && !Main.tile[num574 - 1, num576].active() && SolidTile(num574, num576 + 1) && !Main.tile[num574 + 1, num576].active() && (Main.tile[num574 - 1, num576].liquid > 0 || Main.tile[num574 + 1, num576].liquid > 0))
                    {
                        bool flag35 = true;
                        int num577 = genRand.Next(8, 20);
                        int num578 = genRand.Next(8, 20);
                        num577 = num576 - num577;
                        num578 += num576;
                        for (int num579 = num577; num579 <= num578; num579++)
{
                            if (Main.tile[num574, num579].halfBrick())
{
                                flag35 = false;
                            }
                        }
                        if ((Main.tile[num574, num576].type == 75 || Main.tile[num574, num576].type == 76) && genRand.Next(10) != 0)
{
                            flag35 = false;
                        }
                        if (flag35)
{
                            PoundTile(num574, num576);
                        }
                    }
                }
            }
            for (int num580 = 20; num580 < Main.maxTilesX - 20; num580++)
            {
                double num581 = (double)num580 / (double)Main.maxTilesX;
                progress.Set(num581 * 0.5 + 0.5);
                for (int num582 = 20; num582 < Main.maxTilesY - 20; num582++)
                {
                    if (Main.tile[num580, num582].type != 48 && Main.tile[num580, num582].type != 232 && SolidTile(num580, num582) && SolidTile(num580, num582 + 1))
                    {
                        if (!SolidTile(num580 + 1, num582) && Main.tile[num580 - 1, num582].halfBrick() && Main.tile[num580 - 2, num582].liquid > 0)
{
                            PoundTile(num580, num582);
                        }
                        if (!SolidTile(num580 - 1, num582) && Main.tile[num580 + 1, num582].halfBrick() && Main.tile[num580 + 2, num582].liquid > 0)
{
                            PoundTile(num580, num582);
                        }
                    }
                }
            }
            Main.tileSolid[191] = true;
        });
        AddGenerationPass("Ice", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            if (notTheBees)
            {
                NotTheBees();
            }
            progress.Set(1.0);
            for (int num572 = 10; num572 < Main.maxTilesX - 10; num572++)
            {
                for (int num573 = (int)Main.worldSurface; num573 < Main.maxTilesY - 100; num573++)
                {
                    if (Main.tile[num572, num573].liquid > 0 && (!Main.tile[num572, num573].lava() || remixWorldGen))
                    {
                        MakeWateryIceThing(num572, num573);
                    }
                }
            }
            Main.tileSolid[226] = false;
            Main.tileSolid[162] = false;
        });
        AddGenerationPass("Wall Variety", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            //IL_0093: Unknown result type (might be due to invalid IL or missing references)
            //IL_0098: Unknown result type (might be due to invalid IL or missing references)
            progress.Message = Lang.gen[79].Value;
            double num568 = (double)(Main.maxTilesX * Main.maxTilesY) / 5040000.0;
            int num569 = (int)(300.0 * num568);
            int num570 = num569;
            ShapeData shapeData = new ShapeData();
            while (num569 > 0)
            {
                progress.Set(1.0 - (double)num569 / (double)num570);
                Point point2 = RandomWorldPoint((int)GenVars.worldSurface, 2, 190, 2);
                while (Vector2D.Distance(new Vector2D((double)point2.X, (double)point2.Y), GenVars.shimmerPosition) < (double)shimmerSafetyDistance)
                {
                    point2 = RandomWorldPoint((int)GenVars.worldSurface, 2, 190, 2);
                }
                Tile tile6 = Main.tile[point2.X, point2.Y];
                Tile tile7 = Main.tile[point2.X, point2.Y - 1];
                ushort num571 = 0;
                if (tile6.type == 60)
                {
                    num571 = (ushort)(204 + genRand.Next(4));
                }
                else if (tile6.type == 1 && tile7.wall == 0)
                {
                    num571 = (remixWorldGen ? (((double)point2.Y > GenVars.rockLayer) ? ((ushort)(196 + genRand.Next(4))) : ((point2.Y <= GenVars.lavaLine || genRand.Next(2) != 0) ? ((ushort)(212 + genRand.Next(4))) : ((ushort)(208 + genRand.Next(4))))) : (((double)point2.Y < GenVars.rockLayer) ? ((ushort)(196 + genRand.Next(4))) : ((point2.Y >= GenVars.lavaLine) ? ((ushort)(208 + genRand.Next(4))) : ((ushort)(212 + genRand.Next(4))))));
                }
                if (tile6.active() && num571 != 0 && !tile7.active())
                {
                    bool foundInvalidTile = false;
                    bool flag34 = ((tile6.type != 60) ? WorldUtils.Gen(new Point(point2.X, point2.Y - 1), new ShapeFloodFill(1000), Actions.Chain(new Modifiers.IsNotSolid(), new Actions.Blank().Output(shapeData), new Actions.ContinueWrapper(Actions.Chain(new Modifiers.IsTouching(true, 60, 147, 161, 396, 397, 70, 191), new Modifiers.IsTouching(true, 147, 161, 396, 397, 70, 191), new Actions.Custom(delegate
                    {
                        foundInvalidTile = true;
                        return true;
                    }))))) : WorldUtils.Gen(new Point(point2.X, point2.Y - 1), new ShapeFloodFill(1000), Actions.Chain(new Modifiers.IsNotSolid(), new Actions.Blank().Output(shapeData), new Actions.ContinueWrapper(Actions.Chain(new Modifiers.IsTouching(true, 147, 161, 396, 397, 70, 191), new Actions.Custom(delegate
                    {
                        foundInvalidTile = true;
                        return true;
                    }))))));
                    if (shapeData.Count > 50 && flag34 && !foundInvalidTile)
                    {
                        WorldUtils.Gen(new Point(point2.X, point2.Y), new ModShapes.OuterOutline(shapeData, useDiagonals: true, useInterior: true), Actions.Chain(new Modifiers.SkipWalls(87), new Actions.PlaceWall(num571)));
                        num569--;
                    }
                    shapeData.Clear();
                }
            }
        });
        AddGenerationPass("Life Crystals", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            if (getGoodWorldGen)
            {
                Main.tileSolid[56] = false;
            }
            if (notTheBees)
            {
                NotTheBees();
            }
            progress.Message = Lang.gen[28].Value;
            double num565 = (double)(Main.maxTilesX * Main.maxTilesY) * 2E-05;
            if (tenthAnniversaryWorldGen)
            {
                num565 *= 1.2;
            }
            if (Main.starGame)
            {
                num565 *= Main.starGameMath(0.2);
            }
            for (int num566 = 0; num566 < (int)num565; num566++)
            {
                double value10 = (double)num566 / ((double)(Main.maxTilesX * Main.maxTilesY) * 2E-05);
                progress.Set(value10);
                bool flag33 = false;
                int num567 = 0;
                while (!flag33)
                {
                    int j3 = genRand.Next((int)(Main.worldSurface * 2.0 + Main.rockLayer) / 3, Main.maxTilesY - 300);
                    if (remixWorldGen)
                    {
                        j3 = genRand.Next((int)Main.worldSurface, Main.maxTilesY - 400);
                    }
                    if (AddLifeCrystal(genRand.Next(Main.offLimitBorderTiles, Main.maxTilesX - Main.offLimitBorderTiles), j3))
                    {
                        flag33 = true;
                    }
                    else
                    {
                        num567++;
                        if (num567 >= 10000)
{
                            flag33 = true;
                        }
                    }
                }
            }
            Main.tileSolid[225] = false;
        });
        AddGenerationPass("Statues", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            progress.Message = Lang.gen[29].Value;
            int num558 = 0;
            double num559 = (double)Main.maxTilesX / 4200.0;
            int num560 = (int)((double)(GenVars.statueList.Length * 2) * num559);
            if (noTrapsWorldGen)
            {
                num560 *= 15;
                if (tenthAnniversaryWorldGen || notTheBees)
                {
                    num560 /= 5;
                }
            }
            if (Main.starGame)
            {
                num560 = (int)((double)num560 * Main.starGameMath(0.2));
            }
            for (int num561 = 0; num561 < num560; num561++)
            {
                if (num558 >= GenVars.statueList.Length)
                {
                    num558 = 0;
                }
                int x12 = GenVars.statueList[num558].X;
                int y10 = GenVars.statueList[num558].Y;
                double value9 = num561 / num560;
                progress.Set(value9);
                bool flag32 = false;
                int num562 = 0;
                while (!flag32)
                {
                    int num563 = genRand.Next(20, Main.maxTilesX - 20);
                    int num564 = genRand.Next((int)(Main.worldSurface * 2.0 + Main.rockLayer) / 3, Main.maxTilesY - 300);
                    if (remixWorldGen)
                    {
                        genRand.Next((int)Main.worldSurface, Main.maxTilesY - 400);
                    }
                    while (oceanDepths(num563, num564))
                    {
                        num563 = genRand.Next(20, Main.maxTilesX - 20);
                        num564 = genRand.Next((int)(Main.worldSurface * 2.0 + Main.rockLayer) / 3, Main.maxTilesY - 300);
                        if (remixWorldGen)
{
                            genRand.Next((int)Main.worldSurface, Main.maxTilesY - 400);
                        }
                    }
                    while (!Main.tile[num563, num564].active())
                    {
                        num564++;
                        if (num564 >= Main.maxTilesY)
{
                            break;
                        }
                    }
                    if (num564 < Main.maxTilesY)
                    {
                        num564--;
                        if (!Main.tile[num563, num564].shimmer())
{
                            PlaceTile(num563, num564, x12, mute: true, forced: true, -1, y10);
                        }
                        if (Main.tile[num563, num564].active() && Main.tile[num563, num564].type == x12)
{
                            flag32 = true;
                            if (GenVars.StatuesWithTraps.Contains(num558))
{
                                PlaceStatueTrap(num563, num564);
                            }
                            num558++;
                        }
                        else
{
                            num562++;
                            if (num562 >= 10000)
{
                                flag32 = true;
                            }
                        }
                    }
                }
            }
        });
        AddGenerationPass("Buried Chests", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            progress.Message = Lang.gen[30].Value;
            Main.tileSolid[226] = true;
            Main.tileSolid[162] = true;
            Main.tileSolid[225] = true;
            CaveHouseBiome caveHouseBiome = GenVars.configuration.CreateBiome<CaveHouseBiome>();
            int random6 = passConfig.Get<WorldGenRange>("CaveHouseCount").GetRandom(genRand);
            int random7 = passConfig.Get<WorldGenRange>("UnderworldChestCount").GetRandom(genRand);
            int num546 = passConfig.Get<WorldGenRange>("CaveChestCount").GetRandom(genRand);
            int random8 = passConfig.Get<WorldGenRange>("AdditionalDesertHouseCount").GetRandom(genRand);
            if (Main.starGame)
            {
                num546 = (int)((double)num546 * Main.starGameMath(0.2));
            }
            int num547 = random6 + random7 + num546 + random8;
            int num548 = 10000;
            for (int num549 = 0; num549 < num546; num549++)
            {
                if (num548 <= 0)
                {
                    break;
                }
                progress.Set((double)num549 / (double)num547);
                int num550 = genRand.Next(20, Main.maxTilesX - 20);
                int num551 = genRand.Next((int)((GenVars.worldSurfaceHigh + 20.0 + Main.rockLayer) / 2.0), Main.maxTilesY - 230);
                if (remixWorldGen)
                {
                    num551 = genRand.Next((int)Main.worldSurface, Main.maxTilesY - 400);
                }
                ushort wall = Main.tile[num550, num551].wall;
                if (Main.wallDungeon[wall] || wall == 87 || oceanDepths(num550, num551) || !AddBuriedChest(num550, num551, 0, notNearOtherChests: false, -1, trySlope: false, 0))
                {
                    num548--;
                    num549--;
                }
            }
            num548 = 10000;
            for (int num552 = 0; num552 < random7; num552++)
            {
                if (num548 <= 0)
                {
                    break;
                }
                progress.Set((double)(num552 + num546) / (double)num547);
                int num553 = genRand.Next(20, Main.maxTilesX - 20);
                int num554 = genRand.Next(Main.UnderworldLayer, Main.maxTilesY - 50);
                if (Main.wallDungeon[Main.tile[num553, num554].wall] || !AddBuriedChest(num553, num554, 0, notNearOtherChests: false, -1, trySlope: false, 0))
                {
                    num548--;
                    num552--;
                }
            }
            num548 = 10000;
            for (int num555 = 0; num555 < random6; num555++)
            {
                if (num548 <= 0)
                {
                    break;
                }
                progress.Set((double)(num555 + num546 + random7) / (double)num547);
                int x11 = genRand.Next(80, Main.maxTilesX - 80);
                int y9 = genRand.Next((int)(GenVars.worldSurfaceHigh + 20.0), Main.maxTilesY - 230);
                if (remixWorldGen)
                {
                    y9 = genRand.Next((int)Main.worldSurface, Main.maxTilesY - 400);
                }
                if (oceanDepths(x11, y9) || !caveHouseBiome.Place(new Point(x11, y9), GenVars.structures))
                {
                    num548--;
                    num555--;
                }
            }
            num548 = 10000;
            Rectangle undergroundDesertHiveLocation = GenVars.UndergroundDesertHiveLocation;
            if ((double)undergroundDesertHiveLocation.Y < Main.worldSurface + 26.0)
            {
                int num556 = (int)Main.worldSurface + 26 - undergroundDesertHiveLocation.Y;
                undergroundDesertHiveLocation.Y += num556;
                undergroundDesertHiveLocation.Height -= num556;
            }
            for (int num557 = 0; num557 < random8; num557++)
            {
                if (num548 <= 0)
                {
                    break;
                }
                progress.Set((double)(num557 + num546 + random7 + random6) / (double)num547);
                if (!caveHouseBiome.Place(RandomRectanglePoint(undergroundDesertHiveLocation), GenVars.structures))
                {
                    num548--;
                    num557--;
                }
            }
            Main.tileSolid[226] = false;
            Main.tileSolid[162] = false;
            Main.tileSolid[225] = false;
        });
        AddGenerationPass("Surface Chests", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            progress.Message = Lang.gen[31].Value;
            for (int num536 = 0; num536 < (int)((double)Main.maxTilesX * 0.005); num536++)
            {
                double value8 = (double)num536 / ((double)Main.maxTilesX * 0.005);
                progress.Set(value8);
                bool flag30 = false;
                int num537 = 0;
                while (!flag30)
                {
                    int num538 = genRand.Next(200, Main.maxTilesX - 200);
                    int num539 = genRand.Next((int)GenVars.worldSurfaceLow, (int)Main.worldSurface);
                    if (remixWorldGen)
                    {
                        num539 = genRand.Next(Main.maxTilesY - 400, Main.maxTilesY - 150);
                    }
                    else
                    {
                        while (oceanDepths(num538, num539))
{
                            num538 = genRand.Next(300, Main.maxTilesX - 300);
                            num539 = genRand.Next((int)GenVars.worldSurfaceLow, (int)Main.worldSurface);
                        }
                    }
                    bool flag31 = false;
                    if (!Main.tile[num538, num539].active())
                    {
                        if (Main.tile[num538, num539].wall == 2 || Main.tile[num538, num539].wall == 59 || Main.tile[num538, num539].wall == 244 || remixWorldGen)
{
                            flag31 = true;
                        }
                    }
                    else
                    {
                        int num540 = 50;
                        int num541 = num538;
                        int num542 = num539;
                        int num543 = 1;
                        for (int num544 = num541 - num540; num544 <= num541 + num540; num544 += 2)
{
                            for (int num545 = num542 - num540; num545 <= num542 + num540; num545 += 2)
{
                                if ((double)num545 < Main.worldSurface && !Main.tile[num544, num545].active() && Main.tile[num544, num545].wall == 244 && genRand.Next(num543) == 0)
{
                                    num543++;
                                    flag31 = true;
                                    num538 = num544;
                                    num539 = num545;
                                }
                            }
                        }
                    }
                    if (flag31 && AddBuriedChest(num538, num539, 0, notNearOtherChests: true, -1, trySlope: false, 0))
                    {
                        flag30 = true;
                    }
                    else
                    {
                        num537++;
                        if (num537 >= 2000)
{
                            flag30 = true;
                        }
                    }
                }
            }
        });
        AddGenerationPass("Jungle Chests Placement", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            progress.Message = Lang.gen[32].Value;
            for (int num531 = 0; num531 < GenVars.numJChests; num531++)
            {
                double value7 = (double)num531 / (double)GenVars.numJChests;
                progress.Set(value7);
                int nextJungleChestItem = GetNextJungleChestItem();
                if (!AddBuriedChest(GenVars.JChestX[num531] + genRand.Next(2), GenVars.JChestY[num531], nextJungleChestItem, notNearOtherChests: false, 10, trySlope: false, 0))
                {
                    for (int num532 = GenVars.JChestX[num531] - 1; num532 <= GenVars.JChestX[num531] + 1; num532++)
                    {
                        for (int num533 = GenVars.JChestY[num531]; num533 <= GenVars.JChestY[num531] + 2; num533++)
{
                            KillTile(num532, num533);
                        }
                    }
                    for (int num534 = GenVars.JChestX[num531] - 1; num534 <= GenVars.JChestX[num531] + 1; num534++)
                    {
                        for (int num535 = GenVars.JChestY[num531]; num535 <= GenVars.JChestY[num531] + 3; num535++)
{
                            if (num535 < Main.maxTilesY)
{
                                Main.tile[num534, num535].slope(0);
                                Main.tile[num534, num535].halfBrick(halfBrick: false);
                            }
                        }
                    }
                    AddBuriedChest(GenVars.JChestX[num531], GenVars.JChestY[num531], nextJungleChestItem, notNearOtherChests: false, 10, trySlope: false, 0);
                }
            }
        });
        AddGenerationPass("Water Chests", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            progress.Message = Lang.gen[33].Value;
            for (int num518 = 0; num518 < GenVars.numOceanCaveTreasure; num518++)
            {
                int contain = genRand.NextFromList(new short[5] { 863, 186, 277, 187, 4404 });
                bool flag28 = false;
                double num519 = 2.0;
                while (!flag28 && num519 < 50.0)
                {
                    num519 += 0.1;
                    int num520 = genRand.Next(GenVars.oceanCaveTreasure[num518].X - (int)num519, GenVars.oceanCaveTreasure[num518].X + (int)num519 + 1);
                    int num521 = genRand.Next(GenVars.oceanCaveTreasure[num518].Y - (int)num519 / 2, GenVars.oceanCaveTreasure[num518].Y + (int)num519 / 2 + 1);
                    num520 = ((num520 >= Main.maxTilesX) ? ((int)((double)num520 + num519 / 2.0)) : ((int)((double)num520 - num519 / 2.0)));
                    if (Main.tile[num520, num521].liquid > 250 && (Main.tile[num520, num521].liquidType() == 0 || notTheBees || remixWorldGen))
                    {
                        flag28 = AddBuriedChest(num520, num521, contain, notNearOtherChests: false, 17, trySlope: true, 0);
                    }
                }
            }
            int num522 = 0;
            double num523 = (double)Main.maxTilesX / 4200.0;
            for (int num524 = 0; (double)num524 < 9.0 * num523; num524++)
            {
                double value6 = (double)num524 / (9.0 * num523);
                progress.Set(value6);
                int num525 = 0;
                num522++;
                int maxValue8 = 10;
                if (tenthAnniversaryWorldGen)
                {
                    maxValue8 = 7;
                }
                if (genRand.Next(maxValue8) == 0)
                {
                    num525 = 863;
                }
                else
                {
                    switch (num522)
                    {
                    case 1:
                        num525 = 186;
                        break;
                    case 2:
                        num525 = 4404;
                        break;
                    case 3:
                        num525 = 277;
                        break;
                    default:
                        num525 = 187;
                        num522 = 0;
                        break;
                    }
                }
                bool flag29 = false;
                int num526 = 0;
                while (!flag29)
                {
                    int num527 = genRand.Next(50, Main.maxTilesX - 50);
                    int num528 = genRand.Next(1, Main.UnderworldLayer);
                    while (Main.tile[num527, num528].liquid < 250 || (Main.tile[num527, num528].liquidType() != 0 && !notTheBees && !remixWorldGen))
                    {
                        num527 = genRand.Next(50, Main.maxTilesX - 50);
                        num528 = genRand.Next(50, Main.UnderworldLayer);
                    }
                    flag29 = AddBuriedChest(num527, num528, num525, notNearOtherChests: false, 17, num527 < beachDistance || num527 > Main.maxTilesX - beachDistance, 0);
                    num526++;
                    if (num526 > 10000)
                    {
                        break;
                    }
                }
                flag29 = false;
                num526 = 0;
                while (!flag29)
                {
                    int num529 = genRand.Next(50, Main.maxTilesX - 50);
                    int num530 = genRand.Next((int)Main.worldSurface, Main.UnderworldLayer);
                    while (Main.tile[num529, num530].liquid < 250 || (Main.tile[num529, num530].liquidType() != 0 && !notTheBees))
                    {
                        num529 = genRand.Next(50, Main.maxTilesX - 50);
                        num530 = genRand.Next((int)Main.worldSurface, Main.UnderworldLayer);
                    }
                    flag29 = AddBuriedChest(num529, num530, num525, notNearOtherChests: false, 17, num529 < beachDistance || num529 > Main.maxTilesX - beachDistance, 0);
                    num526++;
                    if (num526 > 10000)
                    {
                        break;
                    }
                }
            }
        });
        AddGenerationPass("Spider Caves", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            progress.Message = Lang.gen[64].Value;
            maxTileCount = 3500;
            int num513 = Main.maxTilesX / 2;
            int num514 = (int)((double)Main.maxTilesX * 0.005);
            if (getGoodWorldGen)
            {
                num514 *= 3;
            }
            if (notTheBees)
            {
                Main.tileSolid[225] = true;
            }
            for (int num515 = 0; num515 < num514; num515++)
            {
                double value5 = (double)num515 / ((double)Main.maxTilesX * 0.005);
                progress.Set(value5);
                int num516 = 0;
                int x10 = genRand.Next(200, Main.maxTilesX - 200);
                int y8 = genRand.Next((int)(Main.worldSurface + Main.rockLayer) / 2, Main.maxTilesY - 230);
                if (remixWorldGen)
                {
                    y8 = genRand.Next((int)Main.worldSurface, (int)Main.rockLayer);
                }
                int num517 = countTiles(x10, y8, jungle: false, lavaOk: true);
                while ((num517 >= 3500 || num517 < 500) && num516 < num513)
                {
                    num516++;
                    x10 = genRand.Next(200, Main.maxTilesX - 200);
                    y8 = genRand.Next((int)Main.rockLayer + 30, Main.maxTilesY - 230);
                    if (remixWorldGen)
                    {
                        y8 = genRand.Next((int)Main.worldSurface, (int)Main.rockLayer);
                    }
                    num517 = countTiles(x10, y8, jungle: false, lavaOk: true);
                    if (shroomCount > 1)
                    {
                        num517 = 0;
                    }
                }
                if (num516 < num513)
                {
                    Spread.Spider(x10, y8);
                }
            }
            if (notTheBees)
            {
                Main.tileSolid[225] = false;
            }
            Main.tileSolid[162] = true;
        });
        AddGenerationPass("Gem Caves", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            if (!notTheBees)
            {
                progress.Message = Lang.gen[64].Value;
                maxTileCount = 300;
                double num509 = (double)Main.maxTilesX * 0.003;
                if (tenthAnniversaryWorldGen)
                {
                    num509 *= 1.5;
                }
                if (Main.starGame)
                {
                    num509 *= Main.starGameMath(0.2);
                }
                for (int num510 = 0; (double)num510 < num509; num510++)
                {
                    double value4 = (double)num510 / num509;
                    progress.Set(value4);
                    int num511 = 0;
                    int x9 = genRand.Next(200, Main.maxTilesX - 200);
                    int y7 = genRand.Next((int)Main.rockLayer + 30, Main.maxTilesY - 230);
                    if (remixWorldGen)
                    {
                        y7 = genRand.Next((int)Main.worldSurface + 30, (int)Main.rockLayer - 30);
                    }
                    int num512 = countTiles(x9, y7);
                    while ((num512 >= 300 || num512 < 50 || lavaCount > 0 || iceCount > 0 || rockCount == 0) && num511 < 1000)
                    {
                        num511++;
                        x9 = genRand.Next(200, Main.maxTilesX - 200);
                        y7 = genRand.Next((int)Main.rockLayer + 30, Main.maxTilesY - 230);
                        if (remixWorldGen)
{
                            y7 = genRand.Next((int)Main.worldSurface + 30, (int)Main.rockLayer - 30);
                        }
                        num512 = countTiles(x9, y7);
                    }
                    if (num511 < 1000)
                    {
                        gemCave(x9, y7);
                    }
                }
            }
        });
        AddGenerationPass("Moss", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            //IL_0393: Unknown result type (might be due to invalid IL or missing references)
            //IL_0398: Unknown result type (might be due to invalid IL or missing references)
            //IL_04e7: Unknown result type (might be due to invalid IL or missing references)
            //IL_04ec: Unknown result type (might be due to invalid IL or missing references)
            //IL_05be: Unknown result type (might be due to invalid IL or missing references)
            //IL_05c3: Unknown result type (might be due to invalid IL or missing references)
            if (!notTheBees || remixWorldGen)
            {
                progress.Message = Lang.gen[61].Value;
                randMoss();
                int num479 = Main.maxTilesX / 2100;
                if (remixWorldGen)
                {
                    num479 = (int)((double)num479 * 1.5);
                }
                else if (tenthAnniversaryWorldGen)
                {
                    num479 *= 2;
                }
                int num480 = 0;
                int num481 = 0;
                while (num481 < num479)
                {
                    int num482 = genRand.Next(100, Main.maxTilesX - 100);
                    if (remixWorldGen)
                    {
                        num482 = genRand.Next((int)((double)Main.maxTilesX * 0.3), (int)((double)Main.maxTilesX * 0.7));
                    }
                    else if (tenthAnniversaryWorldGen)
                    {
                        if (genRand.Next(2) == 0)
{
                            randMoss(justNeon: true);
                        }
                    }
                    else if (getGoodWorldGen)
                    {
                        while ((double)num482 > (double)Main.maxTilesX * 0.42 && (double)num482 < (double)Main.maxTilesX * 0.48)
{
                            num482 = genRand.Next(100, Main.maxTilesX - 100);
                        }
                    }
                    else if (!drunkWorldGen)
                    {
                        while ((double)num482 > (double)Main.maxTilesX * 0.38 && (double)num482 < (double)Main.maxTilesX * 0.62)
{
                            num482 = genRand.Next(100, Main.maxTilesX - 100);
                        }
                    }
                    int num483 = ((!remixWorldGen) ? genRand.Next((int)Main.rockLayer + 40, GenVars.lavaLine - 40) : genRand.Next((int)Main.worldSurface + 50, (int)Main.rockLayer - 50));
                    bool flag27 = false;
                    int num484 = 50;
                    for (int num485 = num482 - num484; num485 <= num482 + num484; num485++)
                    {
                        for (int num486 = num483 - num484; num486 <= num483 + num484; num486++)
{
                            if (Main.tile[num485, num486].active())
{
                                int type6 = Main.tile[num485, num486].type;
                                if (remixWorldGen)
{
                                    if (type6 == 60 || type6 == 161 || type6 == 147 || Main.tileDungeon[type6] || type6 == 25 || type6 == 203)
{
                                        flag27 = true;
                                        num485 = num482 + num484 + 1;
                                        break;
                                    }
                                }
                                else if (type6 == 70 || type6 == 60 || type6 == 367 || type6 == 368 || type6 == 161 || type6 == 147 || type6 == 396 || type6 == 397 || Main.tileDungeon[type6])
{
                                    flag27 = true;
                                    num485 = num482 + num484 + 1;
                                    break;
                                }
                            }
                        }
                    }
                    if (flag27)
                    {
                        num480++;
                        if (num480 > Main.maxTilesX)
{
                            num481++;
                        }
                    }
                    else
                    {
                        num480 = 0;
                        num481++;
                        int maxY = GenVars.lavaLine;
                        if (remixWorldGen)
{
                            maxY = (int)Main.rockLayer + 50;
                        }
                        neonMossBiome(num482, num483, maxY);
                    }
                }
                maxTileCount = 2500;
                for (int num487 = 0; num487 < (int)((double)Main.maxTilesX * 0.01); num487++)
                {
                    double value3 = (double)num487 / ((double)Main.maxTilesX * 0.01);
                    progress.Set(value3);
                    int num488 = 0;
                    int num489 = genRand.Next(200, Main.maxTilesX - 200);
                    int num490 = genRand.Next((int)(Main.worldSurface + Main.rockLayer) / 2, GenVars.waterLine);
                    if (remixWorldGen)
                    {
                        num490 = genRand.Next((int)Main.worldSurface, (int)Main.rockLayer);
                    }
                    if (!(Vector2D.Distance(new Vector2D((double)num489, (double)num490), GenVars.shimmerPosition) < (double)shimmerSafetyDistance))
                    {
                        int num491 = countTiles(num489, num490);
                        while ((num491 >= 2500 || num491 < 10 || lavaCount > 0 || iceCount > 0 || rockCount == 0 || shroomCount > 0) && num488 < 1000)
{
                            num488++;
                            num489 = genRand.Next(200, Main.maxTilesX - 200);
                            num490 = genRand.Next((int)Main.rockLayer + 30, Main.maxTilesY - 230);
                            num491 = countTiles(num489, num490);
                        }
                        if (num488 < 1000)
{
                            setMoss(num489, num490);
                            Spread.Moss(num489, num490);
                        }
                    }
                }
                for (int num492 = 0; num492 < Main.maxTilesX; num492++)
                {
                    int num493 = genRand.Next(50, Main.maxTilesX - 50);
                    int num494 = ((!remixWorldGen) ? genRand.Next((int)(Main.worldSurface + Main.rockLayer) / 2, GenVars.lavaLine) : genRand.Next((int)Main.worldSurface, Main.maxTilesY - 300));
                    if (!(Vector2D.Distance(new Vector2D((double)num493, (double)num494), GenVars.shimmerPosition) < (double)shimmerSafetyDistance) && Main.tile[num493, num494].type == 1)
                    {
                        setMoss(num493, num494);
                        Main.tile[num493, num494].type = GenVars.mossTile;
                    }
                }
                double num495 = (double)Main.maxTilesX * 0.05;
                while (num495 > 0.0)
                {
                    int num496 = genRand.Next(50, Main.maxTilesX - 50);
                    int num497 = ((!remixWorldGen) ? genRand.Next((int)(Main.worldSurface + Main.rockLayer) / 2, GenVars.lavaLine) : genRand.Next((int)Main.worldSurface, Main.maxTilesY - 300));
                    if (!(Vector2D.Distance(new Vector2D((double)num496, (double)num497), GenVars.shimmerPosition) < (double)shimmerSafetyDistance) && Main.tile[num496, num497].type == 1 && (!Main.tile[num496 - 1, num497].active() || !Main.tile[num496 + 1, num497].active() || !Main.tile[num496, num497 - 1].active() || !Main.tile[num496, num497 + 1].active()))
                    {
                        setMoss(num496, num497);
                        Main.tile[num496, num497].type = GenVars.mossTile;
                        num495 -= 1.0;
                    }
                }
                num495 = (double)Main.maxTilesX * 0.065;
                if (remixWorldGen)
                {
                    num495 *= 2.0;
                }
                while (num495 > 0.0)
                {
                    int num498 = genRand.Next(50, Main.maxTilesX - 50);
                    int num499 = ((!remixWorldGen) ? genRand.Next(GenVars.waterLine, Main.UnderworldLayer) : genRand.Next(GenVars.lavaLine, (int)Main.rockLayer + 50));
                    if (Main.tile[num498, num499].type == 1 && (!Main.tile[num498 - 1, num499].active() || !Main.tile[num498 + 1, num499].active() || !Main.tile[num498, num499 - 1].active() || !Main.tile[num498, num499 + 1].active()))
                    {
                        int num500 = 25;
                        int num501 = 0;
                        for (int num502 = num498 - num500; num502 < num498 + num500; num502++)
{
                            for (int num503 = num499 - num500; num503 < num499 + num500; num503++)
{
                                if (Main.tile[num502, num503].liquid > 0 && Main.tile[num502, num503].lava())
{
                                    num501++;
                                }
                            }
                        }
                        if (num501 > 20)
{
                            Main.tile[num498, num499].type = 381;
                            num495 -= 1.0;
                        }
                        else
{
                            num495 -= 0.002;
                        }
                    }
                    num495 -= 0.001;
                }
                for (int num504 = 0; num504 < Main.maxTilesX; num504++)
                {
                    for (int num505 = 0; num505 < Main.maxTilesY; num505++)
                    {
                        if (Main.tile[num504, num505].active() && Main.tileMoss[Main.tile[num504, num505].type])
{
                            for (int num506 = 0; num506 < 4; num506++)
{
                                int num507 = num504;
                                int num508 = num505;
                                if (num506 == 0)
{
                                    num507--;
                                }
                                if (num506 == 1)
{
                                    num507++;
                                }
                                if (num506 == 2)
{
                                    num508--;
                                }
                                if (num506 == 3)
{
                                    num508++;
                                }
                                try
{
                                    grassSpread = 0;
                                    SpreadGrass(num507, num508, 1, Main.tile[num504, num505].type);
                                }
                                catch
{
                                    grassSpread = 0;
                                    SpreadGrass(num507, num508, 1, Main.tile[num504, num505].type, repeat: false);
                                }
                            }
                        }
                    }
                }
            }
        });
        AddGenerationPass("Temple", delegate
        {
            Main.tileSolid[162] = false;
            Main.tileSolid[226] = true;
            templePart2();
            Main.tileSolid[232] = false;
        });
        AddGenerationPass("Cave Walls", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            progress.Message = Lang.gen[63].Value;
            maxTileCount = 1500;
            for (int num463 = 0; num463 < (int)((double)Main.maxTilesX * 0.04); num463++)
            {
                double num464 = (double)num463 / ((double)Main.maxTilesX * 0.04);
                progress.Set(num464 * 0.66);
                int num465 = 0;
                int x7 = genRand.Next(200, Main.maxTilesX - 200);
                int y5 = genRand.Next((int)(Main.worldSurface + Main.rockLayer) / 2, Main.maxTilesY - 220);
                if (remixWorldGen)
                {
                    y5 = genRand.Next((int)Main.worldSurface + 25, (int)Main.rockLayer);
                }
                int num466 = countTiles(x7, y5, jungle: false, lavaOk: true);
                while ((num466 >= maxTileCount || num466 < 10) && num465 < 500)
                {
                    num465++;
                    x7 = genRand.Next(200, Main.maxTilesX - 200);
                    y5 = genRand.Next((int)(Main.worldSurface + Main.rockLayer) / 2, Main.maxTilesY - 220);
                    if (remixWorldGen)
                    {
                        y5 = genRand.Next((int)Main.worldSurface + 25, (int)Main.rockLayer);
                    }
                    num466 = countTiles(x7, y5, jungle: false, lavaOk: true);
                }
                if (num465 < 500)
                {
                    int num467 = genRand.Next(2);
                    if ((double)shroomCount > (double)rockCount * 0.75)
                    {
                        num467 = 80;
                    }
                    else if (iceCount > 0)
                    {
                        switch (num467)
{
                        case 0:
                            num467 = 40;
                            break;
                        case 1:
                            num467 = 71;
                            break;
                        }
                    }
                    else if (lavaCount > 0)
                    {
                        num467 = 79;
                    }
                    else
                    {
                        num467 = genRand.Next(4);
                        switch (num467)
{
                        case 0:
                            num467 = 59;
                            break;
                        case 1:
                            num467 = 61;
                            break;
                        case 2:
                            num467 = 170;
                            break;
                        case 3:
                            num467 = 171;
                            break;
                        }
                    }
                    Spread.Wall(x7, y5, num467);
                }
            }
            if (remixWorldGen)
            {
                maxTileCount = 1500;
                for (int num468 = 0; num468 < (int)((double)Main.maxTilesX * 0.04); num468++)
                {
                    double num469 = (double)num468 / ((double)Main.maxTilesX * 0.04);
                    progress.Set(num469 * 0.66);
                    int num470 = 0;
                    int x8 = genRand.Next(200, Main.maxTilesX - 200);
                    int y6 = genRand.Next((int)Main.rockLayer, Main.maxTilesY - 350);
                    int num471 = countTiles(x8, y6, jungle: false, lavaOk: true);
                    while ((num471 >= maxTileCount || num471 < 10) && num470 < 500)
                    {
                        num470++;
                        x8 = genRand.Next(200, Main.maxTilesX - 200);
                        y6 = genRand.Next((int)Main.rockLayer, Main.maxTilesY - 350);
                        num471 = countTiles(x8, y6, jungle: false, lavaOk: true);
                    }
                    if (num470 < 500 && iceCount == 0 && lavaCount == 0 && sandCount == 0)
                    {
                        int wallType2 = ((genRand.Next(2) != 0) ? 63 : 2);
                        Spread.Wall(x8, y6, wallType2);
                    }
                }
            }
            maxTileCount = 1500;
            double num472 = (double)Main.maxTilesX * 0.02;
            for (int num473 = 0; (double)num473 < num472; num473++)
            {
                double num474 = (double)num473 / ((double)Main.maxTilesX * 0.02);
                progress.Set(num474 * 0.33 + 0.66);
                int num475 = 0;
                int num476 = genRand.Next(200, Main.maxTilesX - 200);
                int num477 = genRand.Next((int)Main.worldSurface, GenVars.lavaLine);
                int num478 = 0;
                if (Main.tile[num476, num477].wall == 64)
                {
                    num478 = countTiles(num476, num477, jungle: true);
                }
                while ((num478 >= maxTileCount || num478 < 10) && num475 < 1000)
                {
                    num475++;
                    num476 = genRand.Next(200, Main.maxTilesX - 200);
                    num477 = genRand.Next((int)Main.worldSurface, GenVars.lavaLine);
                    if (!Main.wallHouse[Main.tile[num476, num477].wall] && Main.tile[num476, num477].wall != 244)
                    {
                        num478 = ((Main.tile[num476, num477].wall == 64) ? countTiles(num476, num477, jungle: true) : 0);
                    }
                }
                if (num475 < 1000)
                {
                    Spread.Wall2(num476, num477, 15);
                }
            }
        });
        AddGenerationPass("Jungle Trees", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            progress.Message = Lang.gen[83].Value;
            for (int num461 = 0; num461 < Main.maxTilesX; num461++)
            {
                progress.Set((double)num461 / (double)Main.maxTilesX);
                for (int num462 = (int)Main.worldSurface - 1; num462 < Main.maxTilesY - 350; num462++)
                {
                    if (genRand.Next(10) == 0 || drunkWorldGen)
                    {
                        GrowUndergroundTree(num461, num462);
                    }
                }
            }
        });
        AddGenerationPass("Floating Island Houses", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            progress.Set(1.0);
            for (int num460 = 0; num460 < GenVars.numIslandHouses; num460++)
            {
                if (!GenVars.skyLake[num460])
                {
                    IslandHouse(GenVars.floatingIslandHouseX[num460], GenVars.floatingIslandHouseY[num460], GenVars.floatingIslandStyle[num460]);
                }
            }
        });
        AddGenerationPass("Quick Cleanup", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            progress.Set(1.0);
            if (notTheBees)
            {
                NotTheBees();
            }
            Main.tileSolid[137] = false;
            Main.tileSolid[130] = false;
            for (int num453 = 20; num453 < Main.maxTilesX - 20; num453++)
            {
                for (int num454 = 20; num454 < Main.maxTilesY - 20; num454++)
                {
                    if ((double)num454 < Main.worldSurface && oceanDepths(num453, num454) && Main.tile[num453, num454].type == 53 && Main.tile[num453, num454].active())
                    {
                        if (Main.tile[num453, num454].bottomSlope())
{
                            Main.tile[num453, num454].slope(0);
                        }
                        for (int num455 = num454 + 1; num455 < num454 + genRand.Next(4, 7) && (!Main.tile[num453, num455].active() || (Main.tile[num453, num455].type != 397 && Main.tile[num453, num455].type != 53)) && (!Main.tile[num453, num455 + 1].active() || (Main.tile[num453, num455 + 1].type != 397 && Main.tile[num453, num455 + 1].type != 53 && Main.tile[num453, num455 + 1].type != 495)) && (!Main.tile[num453, num455 + 2].active() || (Main.tile[num453, num455 + 2].type != 397 && Main.tile[num453, num455 + 2].type != 53 && Main.tile[num453, num455 + 2].type != 495)); num455++)
{
                            Main.tile[num453, num455].type = 0;
                            Main.tile[num453, num455].active(active: true);
                            Main.tile[num453, num455].halfBrick(halfBrick: false);
                            Main.tile[num453, num455].slope(0);
                        }
                    }
                    if (Main.tile[num453, num454].wall == 187 || Main.tile[num453, num454].wall == 216)
                    {
                        if (Main.tile[num453, num454].type == 59 || Main.tile[num453, num454].type == 123 || Main.tile[num453, num454].type == 224)
{
                            Main.tile[num453, num454].type = 397;
                        }
                        if (Main.tile[num453, num454].type == 368 || Main.tile[num453, num454].type == 367)
{
                            Main.tile[num453, num454].type = 397;
                        }
                        if ((double)num454 <= Main.rockLayer)
{
                            Main.tile[num453, num454].liquid = 0;
                        }
                        else if (Main.tile[num453, num454].liquid > 0)
{
                            Main.tile[num453, num454].liquid = byte.MaxValue;
                            Main.tile[num453, num454].lava(lava: true);
                        }
                    }
                    if ((double)num454 < Main.worldSurface && Main.tile[num453, num454].active() && Main.tile[num453, num454].type == 53 && Main.tile[num453, num454 + 1].wall == 0 && !SolidTile(num453, num454 + 1))
                    {
                        ushort num456 = 0;
                        int num457 = 3;
                        for (int num458 = num453 - num457; num458 <= num453 + num457; num458++)
{
                            for (int num459 = num454 - num457; num459 <= num454 + num457; num459++)
{
                                if (Main.tile[num458, num459].wall > 0)
{
                                    num456 = Main.tile[num458, num459].wall;
                                    break;
                                }
                            }
                        }
                        if (num456 > 0)
{
                            Main.tile[num453, num454 + 1].wall = num456;
                            if (Main.tile[num453, num454].wall == 0)
{
                                Main.tile[num453, num454].wall = num456;
                            }
                        }
                    }
                    if (Main.tile[num453, num454].type != 19 && TileID.Sets.CanBeClearedDuringGeneration[Main.tile[num453, num454].type])
                    {
                        if (Main.tile[num453, num454].topSlope() || Main.tile[num453, num454].halfBrick())
{
                            if (Main.tile[num453, num454].type != 225 || !Main.tile[num453, num454].halfBrick())
{
                                if (!SolidTile(num453, num454 + 1))
{
                                    Main.tile[num453, num454].active(active: false);
                                }
                                if (Main.tile[num453 + 1, num454].type == 137 || Main.tile[num453 - 1, num454].type == 137)
{
                                    Main.tile[num453, num454].active(active: false);
                                }
                            }
                        }
                        else if (Main.tile[num453, num454].bottomSlope())
{
                            if (!SolidTile(num453, num454 - 1))
{
                                Main.tile[num453, num454].active(active: false);
                            }
                            if (Main.tile[num453 + 1, num454].type == 137 || Main.tile[num453 - 1, num454].type == 137)
{
                                Main.tile[num453, num454].active(active: false);
                            }
                        }
                    }
                }
            }
        });
        AddGenerationPass("Pots", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            Main.tileSolid[137] = true;
            Main.tileSolid[130] = true;
            progress.Message = Lang.gen[35].Value;
            if (noTrapsWorldGen)
            {
                Main.tileSolid[138] = true;
                int num440 = (int)((double)(Main.maxTilesX * Main.maxTilesY) * 0.0004);
                if (remixWorldGen)
                {
                    num440 /= 2;
                }
                for (int num441 = 0; num441 < num440; num441++)
                {
                    int num442 = genRand.Next(50, Main.maxTilesX - 50);
                    int num443;
                    for (num443 = genRand.Next((int)Main.worldSurface, Main.maxTilesY - 250); !Main.tile[num442, num443].active() && num443 < Main.maxTilesY - 250; num443++)
                    {
                    }
                    num443--;
                    if (!Main.tile[num442, num443].shimmer())
                    {
                        PlaceTile(num442, num443, 138, mute: true);
                        PlaceTile(num442 + 2, num443, 138, mute: true);
                        PlaceTile(num442 + 1, num443 - 2, 138, mute: true);
                    }
                }
                Main.tileSolid[138] = false;
            }
            double num444 = (double)(Main.maxTilesX * Main.maxTilesY) * 0.0008;
            if (Main.starGame)
            {
                num444 *= Main.starGameMath(0.2);
            }
            for (int num445 = 0; (double)num445 < num444; num445++)
            {
                double num446 = (double)num445 / num444;
                progress.Set(num446);
                bool flag25 = false;
                int num447 = 0;
                while (!flag25)
                {
                    int num448 = genRand.Next((int)GenVars.worldSurfaceHigh, Main.maxTilesY - 10);
                    if (num446 > 0.93)
                    {
                        num448 = Main.maxTilesY - 150;
                    }
                    else if (num446 > 0.75)
                    {
                        num448 = (int)GenVars.worldSurfaceLow;
                    }
                    int num449 = genRand.Next(20, Main.maxTilesX - 20);
                    bool flag26 = false;
                    for (int num450 = num448; num450 < Main.maxTilesY - 20; num450++)
                    {
                        if (!flag26)
{
                            if (Main.tile[num449, num450].active() && Main.tileSolid[Main.tile[num449, num450].type] && !Main.tile[num449, num450 - 1].lava() && !Main.tile[num449, num450 - 1].shimmer())
{
                                flag26 = true;
                            }
                        }
                        else if (!((double)num450 < Main.worldSurface) || Main.tile[num449, num450].wall != 0)
{
                            int style = genRand.Next(0, 4);
                            int num451 = 0;
                            int num452 = 0;
                            if (num450 < Main.maxTilesY - 5)
{
                                num451 = Main.tile[num449, num450 + 1].type;
                                num452 = Main.tile[num449, num450].wall;
                            }
                            if (num451 == 147 || num451 == 161 || num451 == 162)
{
                                style = genRand.Next(4, 7);
                            }
                            if (num451 == 60)
{
                                style = genRand.Next(7, 10);
                            }
                            if (Main.wallDungeon[Main.tile[num449, num450].wall])
{
                                style = genRand.Next(10, 13);
                            }
                            if (num451 == 41 || num451 == 43 || num451 == 44 || num451 == 481 || num451 == 482 || num451 == 483)
{
                                style = genRand.Next(10, 13);
                            }
                            if (num451 == 22 || num451 == 23 || num451 == 25)
{
                                style = genRand.Next(16, 19);
                            }
                            if (num451 == 199 || num451 == 203 || num451 == 204 || num451 == 200)
{
                                style = genRand.Next(22, 25);
                            }
                            if (num451 == 367)
{
                                style = genRand.Next(31, 34);
                            }
                            if (num451 == 226)
{
                                style = genRand.Next(28, 31);
                            }
                            if (num452 == 187 || num452 == 216)
{
                                style = genRand.Next(34, 37);
                            }
                            if (num450 > Main.UnderworldLayer)
{
                                style = genRand.Next(13, 16);
                            }
                            if (!oceanDepths(num449, num450) && !Main.tile[num449, num450].shimmer() && PlacePot(num449, num450, 28, style))
{
                                flag25 = true;
                                break;
                            }
                            num447++;
                            if (num447 >= 10000)
{
                                flag25 = true;
                                break;
                            }
                        }
                    }
                }
            }
        });
        AddGenerationPass("Hellforge", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            progress.Message = Lang.gen[36].Value;
            for (int num436 = 0; num436 < Main.maxTilesX / 200; num436++)
            {
                double value2 = (double)num436 / (double)(Main.maxTilesX / 200);
                progress.Set(value2);
                bool flag24 = false;
                int num437 = 0;
                while (!flag24)
                {
                    int num438 = genRand.Next(1, Main.maxTilesX);
                    int num439 = genRand.Next(Main.maxTilesY - 250, Main.maxTilesY - 30);
                    try
                    {
                        if (Main.tile[num438, num439].wall == 13 || Main.tile[num438, num439].wall == 14)
{
                            for (; !Main.tile[num438, num439].active() && num439 < Main.maxTilesY - 20; num439++)
{
                            }
                            num439--;
                            PlaceTile(num438, num439, 77);
                            if (Main.tile[num438, num439].type == 77)
{
                                flag24 = true;
                            }
                            else
{
                                num437++;
                                if (num437 >= 10000)
{
                                    flag24 = true;
                                }
                            }
                        }
                    }
                    catch
                    {
                        num437++;
                        if (num437 >= 10000)
{
                            flag24 = true;
                        }
                    }
                }
            }
        });
        AddGenerationPass("Spreading Grass", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            if (!notTheBees || remixWorldGen)
            {
                progress.Message = Lang.gen[37].Value;
                for (int num414 = 50; num414 < Main.maxTilesX - 50; num414++)
                {
                    for (int num415 = 50; (double)num415 <= Main.worldSurface; num415++)
                    {
                        if (Main.tile[num414, num415].active())
{
                            int type5 = Main.tile[num414, num415].type;
                            if (Main.tile[num414, num415].active() && type5 == 60)
{
                                for (int num416 = num414 - 1; num416 <= num414 + 1; num416++)
{
                                    for (int num417 = num415 - 1; num417 <= num415 + 1; num417++)
{
                                        if (Main.tile[num416, num417].active() && Main.tile[num416, num417].type == 0)
{
                                            if (!Main.tile[num416, num417 - 1].active())
{
                                                Main.tile[num416, num417].type = 60;
                                            }
                                            else
{
                                                Main.tile[num416, num417].type = 59;
                                            }
                                        }
                                    }
                                }
                            }
                            else if (type5 == 1 || type5 == 40 || TileID.Sets.Ore[type5])
{
                                int num418 = 3;
                                bool flag22 = false;
                                ushort num419 = 0;
                                for (int num420 = num414 - num418; num420 <= num414 + num418; num420++)
{
                                    for (int num421 = num415 - num418; num421 <= num415 + num418; num421++)
{
                                        if (Main.tile[num420, num421].active())
{
                                            if (Main.tile[num420, num421].type == 53 || num419 == 53)
{
                                                num419 = 53;
                                            }
                                            else if (Main.tile[num420, num421].type == 59 || Main.tile[num420, num421].type == 60 || Main.tile[num420, num421].type == 147 || Main.tile[num420, num421].type == 161 || Main.tile[num420, num421].type == 199 || Main.tile[num420, num421].type == 23)
{
                                                num419 = Main.tile[num420, num421].type;
                                            }
                                        }
                                        else if (num421 < num415 && Main.tile[num420, num421].wall == 0)
{
                                            flag22 = true;
                                        }
                                    }
                                }
                                if (flag22)
{
                                    switch (num419)
{
                                    case 23:
                                    case 199:
                                        if (Main.tile[num414, num415 - 1].active())
{
                                            num419 = 0;
                                        }
                                        break;
                                    case 59:
                                    case 60:
                                        if (num414 >= GenVars.jungleMinX && num414 <= GenVars.jungleMaxX)
{
                                            num419 = (ushort)(Main.tile[num414, num415 - 1].active() ? 59 : 60);
                                        }
                                        break;
                                    }
                                    Main.tile[num414, num415].type = num419;
                                }
                            }
                        }
                    }
                }
                for (int num422 = 10; num422 < Main.maxTilesX - 10; num422++)
                {
                    bool flag23 = true;
                    for (int num423 = 0; (double)num423 < Main.worldSurface - 1.0; num423++)
                    {
                        if (Main.tile[num422, num423].active())
{
                            if (flag23 && Main.tile[num422, num423].type == 0)
{
                                try
{
                                    grassSpread = 0;
                                    SpreadGrass(num422, num423);
                                }
                                catch
{
                                    grassSpread = 0;
                                    SpreadGrass(num422, num423, 0, 2, repeat: false);
                                }
                            }
                            if ((double)num423 > GenVars.worldSurfaceHigh)
{
                                break;
                            }
                            flag23 = false;
                        }
                        else if (Main.tile[num422, num423].wall == 0)
{
                            flag23 = true;
                        }
                    }
                }
                if (remixWorldGen)
                {
                    for (int num424 = 5; num424 < Main.maxTilesX - 5; num424++)
                    {
                        for (int num425 = (int)GenVars.rockLayerLow + genRand.Next(-1, 2); num425 < Main.maxTilesY - 200; num425++)
{
                            if (Main.tile[num424, num425].type == 0 && Main.tile[num424, num425].active() && (!Main.tile[num424 - 1, num425 - 1].active() || !Main.tile[num424, num425 - 1].active() || !Main.tile[num424 + 1, num425 - 1].active() || !Main.tile[num424 - 1, num425].active() || !Main.tile[num424 + 1, num425].active() || !Main.tile[num424 - 1, num425 + 1].active() || !Main.tile[num424, num425 + 1].active() || !Main.tile[num424 + 1, num425 + 1].active()))
{
                                Main.tile[num424, num425].type = 2;
                            }
                        }
                    }
                    for (int num426 = 5; num426 < Main.maxTilesX - 5; num426++)
                    {
                        for (int num427 = (int)GenVars.rockLayerLow + genRand.Next(-1, 2); num427 < Main.maxTilesY - 200; num427++)
{
                            if (Main.tile[num426, num427].type == 2 && !Main.tile[num426, num427 - 1].active() && genRand.Next(20) == 0)
{
                                PlaceTile(num426, num427 - 1, 27, mute: true);
                            }
                        }
                    }
                    int conversionType = 1;
                    if (crimson)
                    {
                        conversionType = 4;
                    }
                    int num428 = Main.maxTilesX / 7;
                    for (int num429 = 10; num429 < Main.maxTilesX - 10; num429++)
                    {
                        for (int num430 = 10; num430 < Main.maxTilesY - 10; num430++)
{
                            if ((double)num430 < Main.worldSurface + (double)genRand.Next(3) || num429 < num428 + genRand.Next(3) || num429 >= Main.maxTilesX - num428 - genRand.Next(3))
{
                                if (drunkWorldGen)
{
                                    if (GenVars.crimsonLeft)
{
                                        if (num429 < Main.maxTilesX / 2 + genRand.Next(-2, 3))
{
                                            Convert(num429, num430, 4, 1);
                                        }
                                        else
{
                                            Convert(num429, num430, 1, 1);
                                        }
                                    }
                                    else if (num429 < Main.maxTilesX / 2 + genRand.Next(-2, 3))
{
                                        Convert(num429, num430, 1, 1);
                                    }
                                    else
{
                                        Convert(num429, num430, 4, 1);
                                    }
                                }
                                else
{
                                    Convert(num429, num430, conversionType, 1);
                                }
                                Main.tile[num429, num430].color(0);
                                Main.tile[num429, num430].wallColor(0);
                            }
                        }
                    }
                    if (remixWorldGen)
                    {
                        Main.tileSolid[225] = true;
                        int num431 = (int)((double)Main.maxTilesX * 0.31);
                        int num432 = (int)((double)Main.maxTilesX * 0.69);
                        _ = Main.maxTilesY;
                        int num433 = Main.maxTilesY - 135;
                        _ = Main.maxTilesY;
                        Liquid.QuickWater(-2);
                        for (int num434 = num431; num434 < num432 + 15; num434++)
{
                            for (int num435 = Main.maxTilesY - 200; num435 < num433; num435++)
{
                                Main.tile[num434, num435].liquid = 0;
                            }
                        }
                        Main.tileSolid[225] = false;
                        Main.tileSolid[484] = false;
                    }
                }
            }
        });
        AddGenerationPass("Surface Ore and Stone", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            progress.Set(1.0);
            int num405 = genRand.Next(Main.maxTilesX * 5 / 4200, Main.maxTilesX * 10 / 4200);
            for (int num406 = 0; num406 < num405; num406++)
            {
                int num407 = Main.maxTilesX / 420;
                while (num407 > 0)
                {
                    num407--;
                    int num408 = genRand.Next(beachDistance, Main.maxTilesX - beachDistance);
                    while ((double)num408 >= (double)Main.maxTilesX * 0.48 && (double)num408 <= (double)Main.maxTilesX * 0.52)
                    {
                        num408 = genRand.Next(beachDistance, Main.maxTilesX - beachDistance);
                    }
                    int y3 = genRand.Next((int)GenVars.worldSurfaceLow, (int)GenVars.worldSurface);
                    bool flag20 = false;
                    for (int num409 = 0; num409 < GenVars.numOrePatch; num409++)
                    {
                        if (Math.Abs(num408 - GenVars.orePatchX[num409]) < 200)
{
                            flag20 = true;
                        }
                    }
                    if (!flag20 && OrePatch(num408, y3))
                    {
                        if (GenVars.numOrePatch < GenVars.maxOrePatch - 1)
{
                            GenVars.orePatchX[GenVars.numOrePatch] = num408;
                            GenVars.numOrePatch++;
                        }
                        break;
                    }
                }
            }
            num405 = genRand.Next(1, Main.maxTilesX * 7 / 4200);
            for (int num410 = 0; num410 < num405; num410++)
            {
                int num411 = Main.maxTilesX / 420;
                while (num411 > 0)
                {
                    num411--;
                    int num412 = genRand.Next(beachDistance, Main.maxTilesX - beachDistance);
                    while ((double)num412 >= (double)Main.maxTilesX * 0.47 && (double)num412 <= (double)Main.maxTilesX * 0.53)
                    {
                        num412 = genRand.Next(beachDistance, Main.maxTilesX - beachDistance);
                    }
                    int y4 = genRand.Next((int)GenVars.worldSurfaceLow, (int)GenVars.worldSurface);
                    bool flag21 = false;
                    for (int num413 = 0; num413 < GenVars.numOrePatch; num413++)
                    {
                        if (Math.Abs(num412 - GenVars.orePatchX[num413]) < 100)
{
                            flag21 = true;
                        }
                    }
                    if (!flag21 && StonePatch(num412, y4))
                    {
                        break;
                    }
                }
            }
        });
        AddGenerationPass("Place Fallen Log", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            progress.Message = Lang.gen[85].Value;
            int num391 = Main.maxTilesX / 2100;
            num391 = ((!remixWorldGen) ? (num391 + genRand.Next(-1, 2)) : (num391 + genRand.Next(0, 2)));
            for (int num392 = 0; num392 < num391; num392++)
            {
                progress.Set((double)num392 / (double)num391);
                int num393 = beachDistance + 20;
                int num394 = 50000;
                int num395 = 5000;
                while (num394 > 0)
                {
                    num394--;
                    int num396 = genRand.Next(num393, Main.maxTilesX - num393);
                    int num397 = genRand.Next(10, (int)Main.worldSurface);
                    if (remixWorldGen)
                    {
                        num397 = genRand.Next((int)GenVars.rockLayerLow, Main.maxTilesY - 350);
                    }
                    bool flag18 = false;
                    if (num394 < num395)
                    {
                        flag18 = true;
                    }
                    if (num394 > num395 / 2)
                    {
                        while ((double)num396 > (double)Main.maxTilesX * 0.4 && (double)num396 < (double)Main.maxTilesX * 0.6)
{
                            num396 = genRand.Next(num393, Main.maxTilesX - num393);
                        }
                    }
                    if (!Main.tile[num396, num397].active() && Main.tile[num396, num397].wall == 0)
                    {
                        bool flag19 = true;
                        if (remixWorldGen)
{
                            for (; !Main.tile[num396, num397].active() && Main.tile[num396, num397].wall == 0 && num397 <= Main.maxTilesY - 350; num397++)
{
                            }
                        }
                        else
{
                            for (; !Main.tile[num396, num397].active() && Main.tile[num396, num397].wall == 0 && (double)num397 <= Main.worldSurface; num397++)
{
                            }
                        }
                        if ((double)num397 > Main.worldSurface - 10.0 && !remixWorldGen)
{
                            flag19 = false;
                        }
                        else if (!flag18)
{
                            int num398 = 50;
                            for (int num399 = num396 - num398; num399 < num396 + num398; num399++)
{
                                if (num399 > 10 && num399 < Main.maxTilesX - 10)
{
                                    for (int num400 = num397 - num398; num400 < num397 + num398; num400++)
{
                                        if (num400 > 10 && num400 < Main.maxTilesY - 10)
{
                                            int type4 = Main.tile[num399, num400].type;
                                            switch (type4)
{
                                            case 189:
                                                flag19 = false;
                                                break;
                                            case 53:
                                                flag19 = false;
                                                break;
                                            default:
                                                if (Main.tileDungeon[type4])
{
                                                    flag19 = false;
                                                }
                                                else if (TileID.Sets.Crimson[type4])
{
                                                    flag19 = false;
                                                }
                                                else if (TileID.Sets.Corrupt[type4])
{
                                                    flag19 = false;
                                                }
                                                break;
                                            }
                                        }
                                    }
                                }
                            }
                            if (flag19)
{
                                int num401 = 10;
                                int num402 = 10;
                                for (int num403 = num396 - num401; num403 < num396 + num401; num403++)
{
                                    for (int num404 = num397 - num402; num404 < num397 - 1; num404++)
{
                                        if (Main.tile[num403, num404].active() && Main.tileSolid[Main.tile[num403, num404].type])
{
                                            flag19 = false;
                                        }
                                        if (Main.tile[num403, num404].wall != 0)
{
                                            flag19 = false;
                                        }
                                    }
                                }
                            }
                        }
                        if (flag19 && (Main.tile[num396, num397 - 1].liquid == 0 || num394 < num395 / 5) && (Main.tile[num396, num397].type == 2 || (notTheBees && Main.tile[num396, num397].type == 60)) && (Main.tile[num396 - 1, num397].type == 2 || (notTheBees && Main.tile[num396 - 1, num397].type == 60)) && (Main.tile[num396 + 1, num397].type == 2 || (notTheBees && Main.tile[num396 + 1, num397].type == 60)))
{
                            num397--;
                            PlaceTile(num396, num397, 488);
                            if (Main.tile[num396, num397].active() && Main.tile[num396, num397].type == 488)
{
                                if (genRand.Next(2) == 0)
{
                                    GenVars.logX = num396;
                                    GenVars.logY = num397;
                                }
                                num394 = -1;
                            }
                        }
                    }
                }
            }
        });
        AddGenerationPass("Traps", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            if (!notTheBees || noTrapsWorldGen || remixWorldGen)
            {
                placingTraps = true;
                progress.Message = Lang.gen[34].Value;
                if (noTrapsWorldGen)
                {
                    progress.Message = Lang.gen[91].Value;
                }
                double num377 = (double)Main.maxTilesX * 0.05;
                if (noTrapsWorldGen)
                {
                    num377 = ((!tenthAnniversaryWorldGen && !notTheBees) ? (num377 * 100.0) : (num377 * 5.0));
                }
                else if (getGoodWorldGen)
                {
                    num377 *= 1.5;
                }
                if (Main.starGame)
                {
                    num377 *= Main.starGameMath(0.2);
                }
                for (int num378 = 0; (double)num378 < num377; num378++)
                {
                    progress.Set((double)num378 / num377 / 2.0);
                    for (int num379 = 0; num379 < 1150; num379++)
                    {
                        if (noTrapsWorldGen)
{
                            int num380 = genRand.Next(50, Main.maxTilesX - 50);
                            int num381 = genRand.Next(50, Main.maxTilesY - 50);
                            if (remixWorldGen)
{
                                num381 = genRand.Next(50, Main.maxTilesY - 210);
                            }
                            if (((double)num381 > Main.worldSurface || Main.tile[num380, num381].wall > 0) && placeTrap(num380, num381))
{
                                break;
                            }
                        }
                        else
{
                            int num382 = genRand.Next(200, Main.maxTilesX - 200);
                            int num383 = genRand.Next((int)Main.worldSurface, Main.maxTilesY - 210);
                            while (oceanDepths(num382, num383))
{
                                num382 = genRand.Next(200, Main.maxTilesX - 200);
                                num383 = genRand.Next((int)Main.worldSurface, Main.maxTilesY - 210);
                            }
                            if (Main.tile[num382, num383].wall == 0 && placeTrap(num382, num383))
{
                                break;
                            }
                        }
                    }
                }
                if (noTrapsWorldGen)
                {
                    num377 = Main.maxTilesX * 3;
                    if (Main.remixWorld)
                    {
                        num377 = Main.maxTilesX / 3;
                    }
                    if (Main.starGame)
                    {
                        num377 *= Main.starGameMath(0.2);
                    }
                    for (int num384 = 0; (double)num384 < num377; num384++)
                    {
                        if (Main.remixWorld)
{
                            placeTNTBarrel(genRand.Next(50, Main.maxTilesX - 50), genRand.Next((int)Main.worldSurface, (int)((double)(Main.maxTilesY - 350) + Main.rockLayer) / 2));
                        }
                        else
{
                            placeTNTBarrel(genRand.Next(50, Main.maxTilesX - 50), genRand.Next((int)Main.rockLayer, Main.maxTilesY - 200));
                        }
                    }
                }
                num377 = (double)Main.maxTilesX * 0.003;
                if (noTrapsWorldGen)
                {
                    num377 *= 5.0;
                }
                else if (getGoodWorldGen)
                {
                    num377 *= 1.5;
                }
                for (int num385 = 0; (double)num385 < num377; num385++)
                {
                    progress.Set((double)num385 / num377 / 2.0 + 0.5);
                    for (int num386 = 0; num386 < 20000; num386++)
                    {
                        int num387 = genRand.Next((int)((double)Main.maxTilesX * 0.15), (int)((double)Main.maxTilesX * 0.85));
                        int num388 = genRand.Next((int)Main.worldSurface + 20, Main.maxTilesY - 210);
                        if (Main.tile[num387, num388].wall == 187 && PlaceSandTrap(num387, num388))
{
                            break;
                        }
                    }
                }
                if (drunkWorldGen && !noTrapsWorldGen && !notTheBees)
                {
                    for (int num389 = 0; num389 < 8; num389++)
                    {
                        progress.Message = Lang.gen[34].Value;
                        num377 = 100.0;
                        for (int num390 = 0; (double)num390 < num377; num390++)
{
                            progress.Set((double)num390 / num377);
                            Thread.Sleep(10);
                        }
                    }
                }
                if (noTrapsWorldGen)
                {
                    Main.tileSolid[138] = true;
                }
                placingTraps = false;
            }
        });
        AddGenerationPass("Piles", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            progress.Message = Lang.gen[89].Value;
            Main.tileSolid[229] = false;
            Main.tileSolid[190] = false;
            Main.tileSolid[196] = false;
            Main.tileSolid[189] = false;
            Main.tileSolid[202] = false;
            Main.tileSolid[460] = false;
            Main.tileSolid[484] = false;
            if (noTrapsWorldGen)
            {
                Main.tileSolid[138] = false;
            }
            for (int num319 = 0; (double)num319 < (double)Main.maxTilesX * 0.06; num319++)
            {
                int num320 = Main.maxTilesX / 2;
                bool flag11 = false;
                while (!flag11 && num320 > 0)
                {
                    num320--;
                    int num321 = genRand.Next(25, Main.maxTilesX - 25);
                    int num322 = genRand.Next((int)Main.worldSurface, Main.maxTilesY - 300);
                    while (oceanDepths(num321, num322))
                    {
                        num321 = genRand.Next(25, Main.maxTilesX - 25);
                        num322 = genRand.Next((int)Main.worldSurface, Main.maxTilesY - 300);
                    }
                    if (!Main.tile[num321, num322].active())
                    {
                        int num323 = 186;
                        for (; !Main.tile[num321, num322 + 1].active() && num322 < Main.maxTilesY - 5; num322++)
{
                        }
                        int num324 = genRand.Next(22);
                        if (num324 >= 16 && num324 <= 22)
{
                            num324 = genRand.Next(22);
                        }
                        if ((Main.tile[num321, num322 + 1].type == 0 || Main.tile[num321, num322 + 1].type == 1 || Main.tileMoss[Main.tile[num321, num322 + 1].type]) && genRand.Next(5) == 0)
{
                            num324 = genRand.Next(23, 29);
                            num323 = 187;
                        }
                        if (num322 > Main.maxTilesY - 300 || Main.wallDungeon[Main.tile[num321, num322].wall] || Main.tile[num321, num322 + 1].type == 30 || Main.tile[num321, num322 + 1].type == 19 || Main.tile[num321, num322 + 1].type == 25 || Main.tile[num321, num322 + 1].type == 203)
{
                            num324 = genRand.Next(7);
                            num323 = 186;
                        }
                        if (Main.tile[num321, num322 + 1].type == 147 || Main.tile[num321, num322 + 1].type == 161 || Main.tile[num321, num322 + 1].type == 162)
{
                            num324 = genRand.Next(26, 32);
                            num323 = 186;
                        }
                        if (Main.tile[num321, num322 + 1].type == 60)
{
                            num323 = 187;
                            num324 = genRand.Next(6);
                        }
                        if ((Main.tile[num321, num322 + 1].type == 57 || Main.tile[num321, num322 + 1].type == 58) && genRand.Next(3) < 2)
{
                            num323 = 187;
                            num324 = genRand.Next(6, 9);
                        }
                        if (Main.tile[num321, num322 + 1].type == 226)
{
                            num323 = 187;
                            num324 = genRand.Next(18, 23);
                        }
                        if (Main.tile[num321, num322 + 1].type == 70)
{
                            num324 = genRand.Next(32, 35);
                            num323 = 186;
                        }
                        if (Main.tile[num321, num322 + 1].type == 396 || Main.tile[num321, num322 + 1].type == 397 || Main.tile[num321, num322 + 1].type == 404)
{
                            num324 = genRand.Next(29, 35);
                            num323 = 187;
                        }
                        if (Main.tile[num321, num322 + 1].type == 368)
{
                            num324 = genRand.Next(35, 41);
                            num323 = 187;
                        }
                        if (Main.tile[num321, num322 + 1].type == 367)
{
                            num324 = genRand.Next(41, 47);
                            num323 = 187;
                        }
                        if (num323 == 186 && num324 >= 7 && num324 <= 15 && genRand.Next(75) == 0)
{
                            num323 = 187;
                            num324 = 17;
                        }
                        if (Main.wallDungeon[Main.tile[num321, num322].wall] && genRand.Next(3) != 0)
{
                            flag11 = true;
                        }
                        else
{
                            if (!Main.tile[num321, num322].shimmer())
{
                                PlaceTile(num321, num322, num323, mute: true, forced: false, -1, num324);
                            }
                            if (Main.tile[num321, num322].type == 186 || Main.tile[num321, num322].type == 187)
{
                                flag11 = true;
                            }
                            if (flag11 && num323 == 186 && num324 <= 7)
{
                                int num325 = genRand.Next(1, 5);
                                for (int num326 = 0; num326 < num325; num326++)
{
                                    int num327 = num321 + genRand.Next(-10, 11);
                                    int num328 = num322 - genRand.Next(5);
                                    if (!Main.tile[num327, num328].active())
{
                                        for (; !Main.tile[num327, num328 + 1].active() && num328 < Main.maxTilesY - 5; num328++)
{
                                        }
                                        int x3 = genRand.Next(12, 36);
                                        PlaceSmallPile(num327, num328, x3, 0, 185);
                                    }
                                }
                            }
                        }
                    }
                }
            }
            for (int num329 = 0; (double)num329 < (double)Main.maxTilesX * 0.01; num329++)
            {
                int num330 = Main.maxTilesX / 2;
                bool flag12 = false;
                while (!flag12 && num330 > 0)
                {
                    num330--;
                    int num331 = genRand.Next(25, Main.maxTilesX - 25);
                    int num332 = genRand.Next(Main.maxTilesY - 300, Main.maxTilesY - 10);
                    if (!Main.tile[num331, num332].active())
                    {
                        int num333 = 186;
                        for (; !Main.tile[num331, num332 + 1].active() && num332 < Main.maxTilesY - 5; num332++)
{
                        }
                        int num334 = genRand.Next(22);
                        if (num334 >= 16 && num334 <= 22)
{
                            num334 = genRand.Next(22);
                        }
                        if (num332 > Main.maxTilesY - 300 || Main.wallDungeon[Main.tile[num331, num332].wall] || Main.tile[num331, num332 + 1].type == 30 || Main.tile[num331, num332 + 1].type == 19)
{
                            num334 = genRand.Next(7);
                        }
                        if ((Main.tile[num331, num332 + 1].type == 57 || Main.tile[num331, num332 + 1].type == 58) && genRand.Next(3) < 2)
{
                            num333 = 187;
                            num334 = genRand.Next(6, 9);
                        }
                        if (Main.tile[num331, num332 + 1].type == 147 || Main.tile[num331, num332 + 1].type == 161 || Main.tile[num331, num332 + 1].type == 162)
{
                            num334 = genRand.Next(26, 32);
                        }
                        PlaceTile(num331, num332, num333, mute: true, forced: false, -1, num334);
                        if (Main.tile[num331, num332].type == 186 || Main.tile[num331, num332].type == 187)
{
                            flag12 = true;
                        }
                        if (flag12 && num333 == 186 && num334 <= 7)
{
                            int num335 = genRand.Next(1, 5);
                            for (int num336 = 0; num336 < num335; num336++)
{
                                int num337 = num331 + genRand.Next(-10, 11);
                                int num338 = num332 - genRand.Next(5);
                                if (!Main.tile[num337, num338].active())
{
                                    for (; !Main.tile[num337, num338 + 1].active() && num338 < Main.maxTilesY - 5; num338++)
{
                                    }
                                    int x4 = genRand.Next(12, 36);
                                    PlaceSmallPile(num337, num338, x4, 0, 185);
                                }
                            }
                        }
                    }
                }
            }
            for (int num339 = 0; (double)num339 < (double)Main.maxTilesX * 0.003; num339++)
            {
                int num340 = Main.maxTilesX / 2;
                bool flag13 = false;
                while (!flag13 && num340 > 0)
                {
                    num340--;
                    int num341 = 186;
                    int num342 = genRand.Next(25, Main.maxTilesX - 25);
                    int num343 = genRand.Next(10, (int)Main.worldSurface);
                    while (oceanDepths(num342, num343))
                    {
                        num342 = genRand.Next(25, Main.maxTilesX - 25);
                        num343 = genRand.Next(10, (int)Main.worldSurface);
                    }
                    if (!Main.tile[num342, num343].active())
                    {
                        for (; !Main.tile[num342, num343 + 1].active() && num343 < Main.maxTilesY - 5; num343++)
{
                        }
                        int num344 = genRand.Next(7, 13);
                        if (num343 > Main.maxTilesY - 300 || Main.wallDungeon[Main.tile[num342, num343].wall] || Main.tile[num342, num343 + 1].type == 30 || Main.tile[num342, num343 + 1].type == 19 || Main.tile[num342, num343 + 1].type == 25 || Main.tile[num342, num343 + 1].type == 203 || Main.tile[num342, num343 + 1].type == 234 || Main.tile[num342, num343 + 1].type == 112)
{
                            num344 = -1;
                        }
                        if (Main.tile[num342, num343 + 1].type == 147 || Main.tile[num342, num343 + 1].type == 161 || Main.tile[num342, num343 + 1].type == 162)
{
                            num344 = genRand.Next(26, 32);
                        }
                        if (Main.tile[num342, num343 + 1].type == 53)
{
                            num341 = 187;
                            num344 = genRand.Next(52, 55);
                        }
                        if (Main.tile[num342, num343 + 1].type == 2 || Main.tile[num342 - 1, num343 + 1].type == 2 || Main.tile[num342 + 1, num343 + 1].type == 2)
{
                            num341 = 187;
                            num344 = genRand.Next(14, 17);
                        }
                        if (Main.tile[num342, num343 + 1].type == 151 || Main.tile[num342, num343 + 1].type == 274)
{
                            num341 = 186;
                            num344 = genRand.Next(7);
                        }
                        if (num344 >= 0)
{
                            PlaceTile(num342, num343, num341, mute: true, forced: false, -1, num344);
                        }
                        if (Main.tile[num342, num343].type == num341)
{
                            flag13 = true;
                        }
                    }
                }
            }
            for (int num345 = 0; (double)num345 < (double)Main.maxTilesX * 0.0035; num345++)
            {
                int num346 = Main.maxTilesX / 2;
                bool flag14 = false;
                while (!flag14 && num346 > 0)
                {
                    num346--;
                    int num347 = genRand.Next(25, Main.maxTilesX - 25);
                    int num348 = genRand.Next(10, (int)Main.worldSurface);
                    if (!Main.tile[num347, num348].active() && Main.tile[num347, num348].wall > 0)
                    {
                        int num349 = 186;
                        for (; !Main.tile[num347, num348 + 1].active() && num348 < Main.maxTilesY - 5; num348++)
{
                        }
                        int num350 = genRand.Next(7, 13);
                        if (num348 > Main.maxTilesY - 300 || Main.wallDungeon[Main.tile[num347, num348].wall] || Main.tile[num347, num348 + 1].type == 30 || Main.tile[num347, num348 + 1].type == 19)
{
                            num350 = -1;
                        }
                        if (Main.tile[num347, num348 + 1].type == 25)
{
                            num350 = genRand.Next(7);
                        }
                        if (Main.tile[num347, num348 + 1].type == 147 || Main.tile[num347, num348 + 1].type == 161 || Main.tile[num347, num348 + 1].type == 162)
{
                            num350 = genRand.Next(26, 32);
                        }
                        if (Main.tile[num347, num348 + 1].type == 2 || Main.tile[num347 - 1, num348 + 1].type == 2 || Main.tile[num347 + 1, num348 + 1].type == 2)
{
                            num349 = 187;
                            num350 = genRand.Next(14, 17);
                        }
                        if (Main.tile[num347, num348 + 1].type == 151 || Main.tile[num347, num348 + 1].type == 274)
{
                            num349 = 186;
                            num350 = genRand.Next(7);
                        }
                        if (num350 >= 0)
{
                            PlaceTile(num347, num348, num349, mute: true, forced: false, -1, num350);
                        }
                        if (Main.tile[num347, num348].type == num349)
{
                            flag14 = true;
                        }
                        if (flag14 && num350 <= 7)
{
                            int num351 = genRand.Next(1, 5);
                            for (int num352 = 0; num352 < num351; num352++)
{
                                int num353 = num347 + genRand.Next(-10, 11);
                                int num354 = num348 - genRand.Next(5);
                                if (!Main.tile[num353, num354].active())
{
                                    for (; !Main.tile[num353, num354 + 1].active() && num354 < Main.maxTilesY - 5; num354++)
{
                                    }
                                    int x5 = genRand.Next(12, 36);
                                    PlaceSmallPile(num353, num354, x5, 0, 185);
                                }
                            }
                        }
                    }
                }
            }
            for (int num355 = 0; (double)num355 < (double)Main.maxTilesX * 0.6; num355++)
            {
                int num356 = Main.maxTilesX / 2;
                bool flag15 = false;
                while (!flag15 && num356 > 0)
                {
                    num356--;
                    int num357 = genRand.Next(25, Main.maxTilesX - 25);
                    int num358 = genRand.Next((int)Main.worldSurface, Main.maxTilesY - 20);
                    if (Main.tile[num357, num358].wall == 87 && genRand.Next(2) == 0)
                    {
                        num357 = genRand.Next(25, Main.maxTilesX - 25);
                        num358 = genRand.Next((int)Main.worldSurface, Main.maxTilesY - 20);
                    }
                    while (oceanDepths(num357, num358))
                    {
                        num357 = genRand.Next(25, Main.maxTilesX - 25);
                        num358 = genRand.Next((int)Main.worldSurface, Main.maxTilesY - 20);
                    }
                    if (!Main.tile[num357, num358].active())
                    {
                        for (; !Main.tile[num357, num358 + 1].active() && num358 < Main.maxTilesY - 5; num358++)
{
                        }
                        int num359 = genRand.Next(2);
                        int num360 = genRand.Next(36);
                        if (num360 >= 28 && num360 <= 35)
{
                            num360 = genRand.Next(36);
                        }
                        if (num359 == 1)
{
                            num360 = genRand.Next(25);
                            if (num360 >= 16 && num360 <= 24)
{
                                num360 = genRand.Next(25);
                            }
                        }
                        if (num358 > Main.maxTilesY - 300)
{
                            if (num359 == 0)
{
                                num360 = genRand.Next(12, 28);
                            }
                            if (num359 == 1)
{
                                num360 = genRand.Next(6, 16);
                            }
                        }
                        if (Main.wallDungeon[Main.tile[num357, num358].wall] || Main.tile[num357, num358 + 1].type == 30 || Main.tile[num357, num358 + 1].type == 19 || Main.tile[num357, num358 + 1].type == 25 || Main.tile[num357, num358 + 1].type == 203 || Main.tile[num357, num358].wall == 87)
{
                            if (num359 == 0 && num360 < 12)
{
                                num360 += 12;
                            }
                            if (num359 == 1 && num360 < 6)
{
                                num360 += 6;
                            }
                            if (num359 == 1 && num360 >= 17)
{
                                num360 -= 10;
                            }
                        }
                        if (Main.tile[num357, num358 + 1].type == 147 || Main.tile[num357, num358 + 1].type == 161 || Main.tile[num357, num358 + 1].type == 162)
{
                            if (num359 == 0 && num360 < 12)
{
                                num360 += 36;
                            }
                            if (num359 == 1 && num360 >= 20)
{
                                num360 += 6;
                            }
                            if (num359 == 1 && num360 < 6)
{
                                num360 += 25;
                            }
                        }
                        if (Main.tile[num357, num358 + 1].type == 151 || Main.tile[num357, num358 + 1].type == 274)
{
                            if (num359 == 0)
{
                                num360 = genRand.Next(12, 28);
                            }
                            if (num359 == 1)
{
                                num360 = genRand.Next(12, 19);
                            }
                        }
                        if (Main.tile[num357, num358 + 1].type == 368)
{
                            if (num359 == 0)
{
                                num360 = genRand.Next(60, 66);
                            }
                            if (num359 == 1)
{
                                num360 = genRand.Next(47, 53);
                            }
                        }
                        if (Main.tile[num357, num358 + 1].type == 367)
{
                            if (num359 == 0)
{
                                num360 = genRand.Next(66, 72);
                            }
                            if (num359 == 1)
{
                                num360 = genRand.Next(53, 59);
                            }
                        }
                        if (Main.wallDungeon[Main.tile[num357, num358].wall] && genRand.Next(3) != 0)
{
                            flag15 = true;
                        }
                        else if (!Main.tile[num357, num358].shimmer())
{
                            flag15 = PlaceSmallPile(num357, num358, num360, num359, 185);
                        }
                        if (flag15 && num359 == 1 && num360 >= 6 && num360 <= 15)
{
                            int num361 = genRand.Next(1, 5);
                            for (int num362 = 0; num362 < num361; num362++)
{
                                int num363 = num357 + genRand.Next(-10, 11);
                                int num364 = num358 - genRand.Next(5);
                                if (!Main.tile[num363, num364].active())
{
                                    for (; !Main.tile[num363, num364 + 1].active() && num364 < Main.maxTilesY - 5; num364++)
{
                                    }
                                    int x6 = genRand.Next(12, 36);
                                    PlaceSmallPile(num363, num364, x6, 0, 185);
                                }
                            }
                        }
                    }
                }
            }
            for (int num365 = 0; (double)num365 < (double)Main.maxTilesX * 0.02; num365++)
            {
                int num366 = Main.maxTilesX / 2;
                bool flag16 = false;
                while (!flag16 && num366 > 0)
                {
                    num366--;
                    int num367 = genRand.Next(25, Main.maxTilesX - 25);
                    int num368 = genRand.Next(15, (int)Main.worldSurface);
                    while (oceanDepths(num367, num368))
                    {
                        num367 = genRand.Next(25, Main.maxTilesX - 25);
                        num368 = genRand.Next(15, (int)Main.worldSurface);
                    }
                    if (!Main.tile[num367, num368].active())
                    {
                        for (; !Main.tile[num367, num368 + 1].active() && num368 < Main.maxTilesY - 5; num368++)
{
                        }
                        int num369 = genRand.Next(2);
                        int num370 = genRand.Next(11);
                        if (num369 == 1)
{
                            num370 = genRand.Next(5);
                        }
                        if (Main.tile[num367, num368 + 1].type == 147 || Main.tile[num367, num368 + 1].type == 161 || Main.tile[num367, num368 + 1].type == 162)
{
                            if (num369 == 0 && num370 < 12)
{
                                num370 += 36;
                            }
                            if (num369 == 1 && num370 >= 20)
{
                                num370 += 6;
                            }
                            if (num369 == 1 && num370 < 6)
{
                                num370 += 25;
                            }
                        }
                        if (Main.tile[num367, num368 + 1].type == 2 && num369 == 1)
{
                            num370 = genRand.Next(38, 41);
                        }
                        if (Main.tile[num367, num368 + 1].type == 151 || Main.tile[num367, num368 + 1].type == 274)
{
                            if (num369 == 0)
{
                                num370 = genRand.Next(12, 28);
                            }
                            if (num369 == 1)
{
                                num370 = genRand.Next(12, 19);
                            }
                        }
                        if (!Main.wallDungeon[Main.tile[num367, num368].wall] && Main.tile[num367, num368 + 1].type != 30 && Main.tile[num367, num368 + 1].type != 19 && Main.tile[num367, num368 + 1].type != 41 && Main.tile[num367, num368 + 1].type != 43 && Main.tile[num367, num368 + 1].type != 44 && Main.tile[num367, num368 + 1].type != 481 && Main.tile[num367, num368 + 1].type != 482 && Main.tile[num367, num368 + 1].type != 483 && Main.tile[num367, num368 + 1].type != 45 && Main.tile[num367, num368 + 1].type != 46 && Main.tile[num367, num368 + 1].type != 47 && Main.tile[num367, num368 + 1].type != 175 && Main.tile[num367, num368 + 1].type != 176 && Main.tile[num367, num368 + 1].type != 177 && Main.tile[num367, num368 + 1].type != 53 && Main.tile[num367, num368 + 1].type != 25 && Main.tile[num367, num368 + 1].type != 203)
{
                            flag16 = PlaceSmallPile(num367, num368, num370, num369, 185);
                        }
                    }
                }
            }
            for (int num371 = 0; (double)num371 < (double)Main.maxTilesX * 0.15; num371++)
            {
                int num372 = Main.maxTilesX / 2;
                bool flag17 = false;
                while (!flag17 && num372 > 0)
                {
                    num372--;
                    int num373 = genRand.Next(25, Main.maxTilesX - 25);
                    int num374 = genRand.Next(15, (int)Main.worldSurface);
                    if (!Main.tile[num373, num374].active() && (Main.tile[num373, num374].wall == 2 || Main.tile[num373, num374].wall == 40))
                    {
                        for (; !Main.tile[num373, num374 + 1].active() && num374 < Main.maxTilesY - 5; num374++)
{
                        }
                        int num375 = genRand.Next(2);
                        int num376 = genRand.Next(11);
                        if (num375 == 1)
{
                            num376 = genRand.Next(5);
                        }
                        if (Main.tile[num373, num374 + 1].type == 147 || Main.tile[num373, num374 + 1].type == 161 || Main.tile[num373, num374 + 1].type == 162)
{
                            if (num375 == 0 && num376 < 12)
{
                                num376 += 36;
                            }
                            if (num375 == 1 && num376 >= 20)
{
                                num376 += 6;
                            }
                            if (num375 == 1 && num376 < 6)
{
                                num376 += 25;
                            }
                        }
                        if (Main.tile[num373, num374 + 1].type == 2 && num375 == 1)
{
                            num376 = genRand.Next(38, 41);
                        }
                        if (Main.tile[num373, num374 + 1].type == 151 || Main.tile[num373, num374 + 1].type == 274)
{
                            if (num375 == 0)
{
                                num376 = genRand.Next(12, 28);
                            }
                            if (num375 == 1)
{
                                num376 = genRand.Next(12, 19);
                            }
                        }
                        if ((Main.tile[num373, num374].liquid != byte.MaxValue || Main.tile[num373, num374 + 1].type != 53 || Main.tile[num373, num374].wall != 0) && !Main.wallDungeon[Main.tile[num373, num374].wall] && Main.tile[num373, num374 + 1].type != 30 && Main.tile[num373, num374 + 1].type != 19 && Main.tile[num373, num374 + 1].type != 41 && Main.tile[num373, num374 + 1].type != 43 && Main.tile[num373, num374 + 1].type != 44 && Main.tile[num373, num374 + 1].type != 481 && Main.tile[num373, num374 + 1].type != 482 && Main.tile[num373, num374 + 1].type != 483 && Main.tile[num373, num374 + 1].type != 45 && Main.tile[num373, num374 + 1].type != 46 && Main.tile[num373, num374 + 1].type != 47 && Main.tile[num373, num374 + 1].type != 175 && Main.tile[num373, num374 + 1].type != 176 && Main.tile[num373, num374 + 1].type != 177 && Main.tile[num373, num374 + 1].type != 25 && Main.tile[num373, num374 + 1].type != 203)
{
                            flag17 = PlaceSmallPile(num373, num374, num376, num375, 185);
                        }
                    }
                }
            }
            Main.tileSolid[190] = true;
            Main.tileSolid[192] = true;
            Main.tileSolid[196] = true;
            Main.tileSolid[189] = true;
            Main.tileSolid[202] = true;
            Main.tileSolid[225] = true;
            Main.tileSolid[460] = true;
            Main.tileSolid[138] = true;
        });
        AddGenerationPass("Spawn Point", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            progress.Set(1.0);
            int num310 = 5;
            bool flag10 = true;
            int num311 = Main.maxTilesX / 2;
            if (Main.tenthAnniversaryWorld && !remixWorldGen)
            {
                int num312 = GenVars.beachBordersWidth + 15;
                num311 = ((genRand.Next(2) != 0) ? (Main.maxTilesX - num312) : num312);
            }
            while (flag10)
            {
                int num313 = num311 + genRand.Next(-num310, num310 + 1);
                for (int num314 = 0; num314 < Main.maxTilesY; num314++)
                {
                    if (Main.tile[num313, num314].active())
                    {
                        Main.spawnTileX = num313;
                        Main.spawnTileY = num314;
                        break;
                    }
                }
                flag10 = false;
                num310++;
                if ((double)Main.spawnTileY > Main.worldSurface)
                {
                    flag10 = true;
                }
                if (Main.tile[Main.spawnTileX, Main.spawnTileY - 1].liquid > 0)
                {
                    flag10 = true;
                }
            }
            int num315 = 10;
            while ((double)Main.spawnTileY > Main.worldSurface)
            {
                int num316 = genRand.Next(num311 - num315, num311 + num315);
                for (int num317 = 0; num317 < Main.maxTilesY; num317++)
                {
                    if (Main.tile[num316, num317].active())
                    {
                        Main.spawnTileX = num316;
                        Main.spawnTileY = num317;
                        break;
                    }
                }
                num315++;
            }
            if (remixWorldGen)
            {
                int num318 = Main.maxTilesY - 10;
                while (SolidTile(Main.spawnTileX, num318))
                {
                    num318--;
                }
                Main.spawnTileY = num318 + 1;
            }
        });
        AddGenerationPass("Grass Wall", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            maxTileCount = 3500;
            progress.Set(1.0);
            for (int num298 = 50; num298 < Main.maxTilesX - 50; num298++)
            {
                for (int num299 = 0; (double)num299 < Main.worldSurface - 10.0; num299++)
                {
                    if (genRand.Next(4) == 0)
                    {
                        bool flag8 = false;
                        int num300 = -1;
                        int num301 = -1;
                        if (Main.tile[num298, num299].active() && Main.tile[num298, num299].type == 2 && (Main.tile[num298, num299].wall == 2 || Main.tile[num298, num299].wall == 63))
{
                            for (int num302 = num298 - 1; num302 <= num298 + 1; num302++)
{
                                for (int num303 = num299 - 1; num303 <= num299 + 1; num303++)
{
                                    if (Main.tile[num302, num303].wall == 0 && !SolidTile(num302, num303))
{
                                        flag8 = true;
                                    }
                                }
                            }
                            if (flag8)
{
                                for (int num304 = num298 - 1; num304 <= num298 + 1; num304++)
{
                                    for (int num305 = num299 - 1; num305 <= num299 + 1; num305++)
{
                                        if ((Main.tile[num304, num305].wall == 2 || Main.tile[num304, num305].wall == 15) && !SolidTile(num304, num305))
{
                                            num300 = num304;
                                            num301 = num305;
                                        }
                                    }
                                }
                            }
                        }
                        if (flag8 && num300 > -1 && num301 > -1 && countDirtTiles(num300, num301) < maxTileCount)
{
                            try
{
                                ushort wallType = 63;
                                if (dontStarveWorldGen && genRand.Next(3) != 0)
{
                                    wallType = 62;
                                }
                                Spread.Wall2(num300, num301, wallType);
                            }
                            catch
{
                            }
                        }
                    }
                }
            }
            for (int num306 = 5; num306 < Main.maxTilesX - 5; num306++)
            {
                for (int num307 = 10; (double)num307 < Main.worldSurface - 1.0; num307++)
                {
                    if (Main.tile[num306, num307].wall == 63 && genRand.Next(10) == 0)
                    {
                        Main.tile[num306, num307].wall = 65;
                    }
                    if (Main.tile[num306, num307].active() && Main.tile[num306, num307].type == 0)
                    {
                        bool flag9 = false;
                        for (int num308 = num306 - 1; num308 <= num306 + 1; num308++)
{
                            for (int num309 = num307 - 1; num309 <= num307 + 1; num309++)
{
                                if (Main.tile[num308, num309].wall == 63 || Main.tile[num308, num309].wall == 65)
{
                                    flag9 = true;
                                    break;
                                }
                            }
                        }
                        if (flag9)
{
                            SpreadGrass(num306, num307);
                        }
                    }
                }
            }
        });
        AddGenerationPass("Guide", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            progress.Set(1.0);
            if (Main.tenthAnniversaryWorld)
            {
                BirthdayParty.GenuineParty = true;
                BirthdayParty.PartyDaysOnCooldown = 5;
                if (getGoodWorldGen)
                {
                    Main.afterPartyOfDoom = true;
                }
                int num292;
                if (remixWorldGen)
                {
                    num292 = NPC.NewNPC(new EntitySource_WorldGen(), Main.spawnTileX * 16, Main.spawnTileY * 16, 441);
                    NPC.savedTaxCollector = true;
                }
                else
                {
                    num292 = NPC.NewNPC(new EntitySource_WorldGen(), Main.spawnTileX * 16, Main.spawnTileY * 16, 22);
                }
                Main.npc[num292].homeTileX = Main.spawnTileX;
                Main.npc[num292].homeTileY = Main.spawnTileY;
                Main.npc[num292].direction = 1;
                Main.npc[num292].homeless = true;
                Main.npc[num292].GivenName = Language.GetTextValue("GuideNames.Andrew");
                BirthdayParty.CelebratingNPCs.Add(num292);
                Point adjustedFloorPosition = GetAdjustedFloorPosition(Main.spawnTileX + 2, Main.spawnTileY);
                num292 = NPC.NewNPC(new EntitySource_WorldGen(), adjustedFloorPosition.X * 16, adjustedFloorPosition.Y * 16, 178);
                Main.npc[num292].homeTileX = adjustedFloorPosition.X;
                Main.npc[num292].homeTileY = adjustedFloorPosition.Y;
                Main.npc[num292].direction = -1;
                Main.npc[num292].homeless = true;
                Main.npc[num292].GivenName = Language.GetTextValue("SteampunkerNames.Whitney");
                BirthdayParty.CelebratingNPCs.Add(num292);
                adjustedFloorPosition = GetAdjustedFloorPosition(Main.spawnTileX - 2, Main.spawnTileY);
                num292 = NPC.NewNPC(new EntitySource_WorldGen(), adjustedFloorPosition.X * 16, adjustedFloorPosition.Y * 16, 663);
                Main.npc[num292].homeTileX = adjustedFloorPosition.X;
                Main.npc[num292].homeTileY = adjustedFloorPosition.Y;
                Main.npc[num292].direction = 1;
                Main.npc[num292].homeless = true;
                Main.npc[num292].GivenName = Language.GetTextValue("PrincessNames.Yorai");
                BirthdayParty.CelebratingNPCs.Add(num292);
                NPC.unlockedPrincessSpawn = true;
                adjustedFloorPosition = GetAdjustedFloorPosition(Main.spawnTileX + 4, Main.spawnTileY);
                num292 = NPC.NewNPC(new EntitySource_WorldGen(), adjustedFloorPosition.X * 16, adjustedFloorPosition.Y * 16, 208);
                Main.npc[num292].homeTileX = adjustedFloorPosition.X;
                Main.npc[num292].homeTileY = adjustedFloorPosition.Y;
                Main.npc[num292].direction = -1;
                Main.npc[num292].homeless = true;
                Main.npc[num292].GivenName = Language.GetTextValue("PartyGirlNames.Amanda");
                BirthdayParty.CelebratingNPCs.Add(num292);
                NPC.unlockedPartyGirlSpawn = true;
                adjustedFloorPosition = GetAdjustedFloorPosition(Main.spawnTileX - 4, Main.spawnTileY);
                if (Main.remixWorld)
                {
                    num292 = NPC.NewNPC(new EntitySource_WorldGen(), adjustedFloorPosition.X * 16, adjustedFloorPosition.Y * 16, 681);
                    Main.npc[num292].GivenName = Language.GetTextValue("SlimeNames_Rainbow.Slimestar");
                    NPC.unlockedSlimeRainbowSpawn = true;
                }
                else
                {
                    num292 = NPC.NewNPC(new EntitySource_WorldGen(), adjustedFloorPosition.X * 16, adjustedFloorPosition.Y * 16, 656);
                    NPC.boughtBunny = true;
                    Main.npc[num292].townNpcVariationIndex = 1;
                }
                Main.npc[num292].homeTileX = adjustedFloorPosition.X;
                Main.npc[num292].homeTileY = adjustedFloorPosition.Y;
                Main.npc[num292].direction = 1;
                Main.npc[num292].homeless = true;
            }
            else if (remixWorldGen)
            {
                int num293 = NPC.NewNPC(new EntitySource_WorldGen(), Main.spawnTileX * 16, Main.spawnTileY * 16, 441);
                Main.npc[num293].homeTileX = Main.spawnTileX;
                Main.npc[num293].homeTileY = Main.spawnTileY;
                Main.npc[num293].direction = 1;
                Main.npc[num293].homeless = true;
                NPC.savedTaxCollector = true;
            }
            else if (notTheBees)
            {
                int num294 = NPC.NewNPC(new EntitySource_WorldGen(), Main.spawnTileX * 16, Main.spawnTileY * 16, 17);
                Main.npc[num294].homeTileX = Main.spawnTileX;
                Main.npc[num294].homeTileY = Main.spawnTileY;
                Main.npc[num294].direction = 1;
                Main.npc[num294].homeless = true;
                NPC.unlockedMerchantSpawn = true;
            }
            else if (drunkWorldGen)
            {
                int num295 = NPC.NewNPC(new EntitySource_WorldGen(), Main.spawnTileX * 16, Main.spawnTileY * 16, 208);
                Main.npc[num295].homeTileX = Main.spawnTileX;
                Main.npc[num295].homeTileY = Main.spawnTileY;
                Main.npc[num295].direction = 1;
                Main.npc[num295].homeless = true;
                NPC.unlockedPartyGirlSpawn = true;
            }
            else if (getGoodWorldGen)
            {
                int num296 = NPC.NewNPC(new EntitySource_WorldGen(), Main.spawnTileX * 16, Main.spawnTileY * 16, 38);
                Main.npc[num296].homeTileX = Main.spawnTileX;
                Main.npc[num296].homeTileY = Main.spawnTileY;
                Main.npc[num296].direction = 1;
                Main.npc[num296].homeless = true;
                NPC.unlockedDemolitionistSpawn = true;
            }
            else
            {
                int num297 = NPC.NewNPC(new EntitySource_WorldGen(), Main.spawnTileX * 16, Main.spawnTileY * 16, 22);
                Main.npc[num297].homeTileX = Main.spawnTileX;
                Main.npc[num297].homeTileY = Main.spawnTileY;
                Main.npc[num297].direction = 1;
                Main.npc[num297].homeless = true;
            }
        });
        AddGenerationPass("Sunflowers", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            progress.Message = Lang.gen[39].Value;
            double num283 = (double)Main.maxTilesX * 0.002;
            for (int num284 = 0; (double)num284 < num283; num284++)
            {
                progress.Set((double)num284 / num283);
                int num285 = 0;
                int num286 = 0;
                _ = Main.maxTilesX / 2;
                int num287 = genRand.Next(Main.maxTilesX);
                num285 = num287 - genRand.Next(10) - 7;
                num286 = num287 + genRand.Next(10) + 7;
                if (num285 < 0)
                {
                    num285 = 0;
                }
                if (num286 > Main.maxTilesX - 1)
                {
                    num286 = Main.maxTilesX - 1;
                }
                int num288 = 1;
                int num289 = (int)Main.worldSurface - 1;
                for (int num290 = num285; num290 < num286; num290++)
                {
                    for (int num291 = num288; num291 < num289; num291++)
                    {
                        if (Main.tile[num290, num291].type == 2 && Main.tile[num290, num291].active() && !Main.tile[num290, num291 - 1].active())
{
                            PlaceTile(num290, num291 - 1, 27, mute: true);
                        }
                        if (Main.tile[num290, num291].active())
{
                            break;
                        }
                    }
                }
            }
        });
        AddGenerationPass("Planting Trees", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            progress.Message = Lang.gen[40].Value;
            if (!drunkWorldGen && !Main.tenthAnniversaryWorld)
            {
                for (int num278 = 0; (double)num278 < (double)Main.maxTilesX * 0.003; num278++)
                {
                    progress.Set((double)num278 / ((double)Main.maxTilesX * 0.003));
                    int num279 = genRand.Next(50, Main.maxTilesX - 50);
                    int num280 = genRand.Next(25, 50);
                    for (int num281 = num279 - num280; num281 < num279 + num280; num281++)
                    {
                        for (int num282 = 20; (double)num282 < Main.worldSurface; num282++)
{
                            GrowEpicTree(num281, num282);
                        }
                    }
                }
            }
            AddTrees();
        });
        AddGenerationPass("Herbs", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            double num276 = (double)Main.maxTilesX * 1.7;
            if (remixWorldGen)
            {
                num276 *= 5.0;
            }
            progress.Message = Lang.gen[41].Value;
            for (int num277 = 0; (double)num277 < num276; num277++)
            {
                progress.Set((double)num277 / num276);
                PlantAlch();
            }
        });
        AddGenerationPass("Dye Plants", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            progress.Set(1.0);
            for (int num275 = 0; num275 < Main.maxTilesX; num275++)
            {
                plantDye(genRand.Next(100, Main.maxTilesX - 100), genRand.Next(100, Main.UnderworldLayer));
            }
            MatureTheHerbPlants();
            GrowGlowTulips();
        });
        AddGenerationPass("Webs And Honey", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            progress.Set(1.0);
            for (int num265 = 100; num265 < Main.maxTilesX - 100; num265++)
            {
                int num266 = (int)Main.worldSurface;
                if (dontStarveWorldGen)
                {
                    num266 = 50;
                }
                for (int num267 = num266; num267 < Main.maxTilesY - 100; num267++)
                {
                    if (Main.tile[num265, num267].wall == 86)
                    {
                        if (Main.tile[num265, num267].liquid > 0)
{
                            Main.tile[num265, num267].honey(honey: true);
                        }
                        if (genRand.Next(3) == 0)
{
                            PlaceTight(num265, num267);
                        }
                    }
                    if (Main.tile[num265, num267].wall == 62)
                    {
                        Main.tile[num265, num267].liquid = 0;
                        Main.tile[num265, num267].lava(lava: false);
                    }
                    if (Main.tile[num265, num267].wall == 62 && !Main.tile[num265, num267].active() && genRand.Next(10) != 0)
                    {
                        int num268 = genRand.Next(2, 5);
                        int num269 = num265 - num268;
                        int num270 = num265 + num268;
                        int num271 = num267 - num268;
                        int num272 = num267 + num268;
                        bool flag7 = false;
                        for (int num273 = num269; num273 <= num270; num273++)
{
                            for (int num274 = num271; num274 <= num272; num274++)
{
                                if (SolidTile(num273, num274))
{
                                    flag7 = true;
                                    break;
                                }
                            }
                        }
                        if (flag7)
{
                            PlaceTile(num265, num267, 51, mute: true);
                            TileFrame(num265, num267);
                        }
                    }
                }
            }
        });
        AddGenerationPass("Weeds", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            progress.Message = Lang.gen[42].Value;
            if (Main.halloween)
            {
                for (int num259 = 40; num259 < Main.maxTilesX - 40; num259++)
                {
                    for (int num260 = 50; (double)num260 < Main.worldSurface; num260++)
                    {
                        if (Main.tile[num259, num260].active() && Main.tile[num259, num260].type == 2 && genRand.Next(15) == 0)
{
                            PlacePumpkin(num259, num260 - 1);
                            int num261 = genRand.Next(5);
                            for (int num262 = 0; num262 < num261; num262++)
{
                                GrowPumpkin(num259, num260 - 1, 254);
                            }
                        }
                    }
                }
            }
            for (int num263 = 0; num263 < Main.maxTilesX; num263++)
            {
                progress.Set((double)num263 / (double)Main.maxTilesX);
                for (int num264 = 1; num264 < Main.maxTilesY; num264++)
                {
                    if (Main.tile[num263, num264].type == 2 && Main.tile[num263, num264].nactive())
                    {
                        if (!Main.tile[num263, num264 - 1].active())
{
                            PlaceTile(num263, num264 - 1, 3, mute: true);
                            Main.tile[num263, num264 - 1].CopyPaintAndCoating(Main.tile[num263, num264]);
                        }
                    }
                    else if (Main.tile[num263, num264].type == 23 && Main.tile[num263, num264].nactive())
                    {
                        if (!Main.tile[num263, num264 - 1].active())
{
                            PlaceTile(num263, num264 - 1, 24, mute: true);
                        }
                    }
                    else if (Main.tile[num263, num264].type == 199 && Main.tile[num263, num264].nactive())
                    {
                        if (!Main.tile[num263, num264 - 1].active())
{
                            PlaceTile(num263, num264 - 1, 201, mute: true);
                        }
                    }
                    else if (Main.tile[num263, num264].type == 633 && Main.tile[num263, num264].nactive() && !Main.tile[num263, num264 - 1].active())
                    {
                        PlaceTile(num263, num264 - 1, 637, mute: true);
                    }
                }
            }
        });
        AddGenerationPass("Glowing Mushrooms and Jungle Plants", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            progress.Set(1.0);
            for (int num257 = 0; num257 < Main.maxTilesX; num257++)
            {
                for (int num258 = 0; num258 < Main.maxTilesY; num258++)
                {
                    if (Main.tile[num257, num258].active())
                    {
                        if (num258 >= (int)Main.worldSurface && Main.tile[num257, num258].type == 70 && !Main.tile[num257, num258 - 1].active())
{
                            GrowTree(num257, num258);
                            if (!Main.tile[num257, num258 - 1].active())
{
                                GrowTree(num257, num258);
                                if (!Main.tile[num257, num258 - 1].active())
{
                                    GrowTree(num257, num258);
                                    if (!Main.tile[num257, num258 - 1].active())
{
                                        PlaceTile(num257, num258 - 1, 71, mute: true);
                                    }
                                }
                            }
                        }
                        if (Main.tile[num257, num258].type == 60 && !Main.tile[num257, num258 - 1].active())
{
                            PlaceTile(num257, num258 - 1, 61, mute: true);
                        }
                    }
                }
            }
        });
        AddGenerationPass("Jungle Plants", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            progress.Set(1.0);
            for (int num254 = 0; num254 < Main.maxTilesX * 100; num254++)
            {
                int num255 = genRand.Next(40, Main.maxTilesX / 2 - 40);
                if (GenVars.dungeonSide < 0)
                {
                    num255 += Main.maxTilesX / 2;
                }
                int num256;
                for (num256 = genRand.Next(Main.maxTilesY - 300); !Main.tile[num255, num256].active() && num256 < Main.maxTilesY - 300; num256++)
                {
                }
                if (Main.tile[num255, num256].active() && Main.tile[num255, num256].type == 60)
                {
                    num256--;
                    PlaceJunglePlant(num255, num256, 233, genRand.Next(8), 0);
                    if (Main.tile[num255, num256].type != 233)
                    {
                        PlaceJunglePlant(num255, num256, 233, genRand.Next(12), 1);
                    }
                }
            }
        });
        AddGenerationPass("Vines", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            progress.Message = Lang.gen[43].Value;
            for (int num233 = 5; num233 < Main.maxTilesX - 5; num233++)
            {
                progress.Set((double)num233 / (double)Main.maxTilesX);
                int num234 = 0;
                ushort type3 = 52;
                int num235 = (int)Main.worldSurface;
                if (remixWorldGen)
                {
                    num235 = Main.maxTilesY - 200;
                }
                for (int num236 = 0; num236 < num235; num236++)
                {
                    if (num234 > 0 && !Main.tile[num233, num236].active())
                    {
                        Main.tile[num233, num236].active(active: true);
                        Main.tile[num233, num236].type = type3;
                        Main.tile[num233, num236].CopyPaintAndCoating(Main.tile[num233, num236 - 1]);
                        num234--;
                    }
                    else
                    {
                        num234 = 0;
                    }
                    if (Main.tile[num233, num236].active() && !Main.tile[num233, num236].bottomSlope() && (Main.tile[num233, num236].type == 2 || (Main.tile[num233, num236].type == 192 && genRand.Next(4) == 0)) && GrowMoreVines(num233, num236))
                    {
                        type3 = 52;
                        if (Main.tile[num233, num236].wall == 68 || Main.tile[num233, num236].wall == 65 || Main.tile[num233, num236].wall == 66 || Main.tile[num233, num236].wall == 63)
{
                            type3 = 382;
                        }
                        else if (Main.tile[num233, num236 + 1].wall == 68 || Main.tile[num233, num236 + 1].wall == 65 || Main.tile[num233, num236 + 1].wall == 66 || Main.tile[num233, num236 + 1].wall == 63)
{
                            type3 = 382;
                        }
                        if (remixWorldGen && genRand.Next(5) == 0)
{
                            type3 = 382;
                        }
                        if (genRand.Next(5) < 3)
{
                            num234 = genRand.Next(1, 10);
                        }
                    }
                }
                num234 = 0;
                for (int num237 = 5; num237 < Main.maxTilesY - 5; num237++)
                {
                    if (num234 > 0 && !Main.tile[num233, num237].active())
                    {
                        Main.tile[num233, num237].active(active: true);
                        Main.tile[num233, num237].type = 62;
                        num234--;
                    }
                    else
                    {
                        num234 = 0;
                    }
                    if (Main.tile[num233, num237].active() && Main.tile[num233, num237].type == 60 && !Main.tile[num233, num237].bottomSlope() && GrowMoreVines(num233, num237))
                    {
                        if (notTheBees && num237 < Main.maxTilesY - 10 && Main.tile[num233, num237 - 1].active() && !Main.tile[num233, num237 - 1].bottomSlope() && Main.tile[num233 + 1, num237 - 1].active() && !Main.tile[num233 + 1, num237 - 1].bottomSlope() && (Main.tile[num233, num237 - 1].type == 60 || Main.tile[num233, num237 - 1].type == 444 || Main.tile[num233, num237 - 1].type == 230))
{
                            bool flag5 = true;
                            for (int num238 = num233; num238 < num233 + 2; num238++)
{
                                for (int num239 = num237 + 1; num239 < num237 + 3; num239++)
{
                                    if (Main.tile[num238, num239].active() && (!Main.tileCut[Main.tile[num238, num239].type] || Main.tile[num238, num239].type == 444))
{
                                        flag5 = false;
                                        break;
                                    }
                                    if (Main.tile[num238, num239].liquid > 0 || Main.wallHouse[Main.tile[num238, num239].wall])
{
                                        flag5 = false;
                                        break;
                                    }
                                }
                                if (!flag5)
{
                                    break;
                                }
                            }
                            if (flag5 && CountNearBlocksTypes(num233, num237, genRand.Next(3, 10), 1, 444) > 0)
{
                                flag5 = false;
                            }
                            if (flag5)
{
                                for (int num240 = num233; num240 < num233 + 2; num240++)
{
                                    for (int num241 = num237 + 1; num241 < num237 + 3; num241++)
{
                                        KillTile(num240, num241);
                                    }
                                }
                                for (int num242 = num233; num242 < num233 + 2; num242++)
{
                                    for (int num243 = num237 + 1; num243 < num237 + 3; num243++)
{
                                        Main.tile[num242, num243].active(active: true);
                                        Main.tile[num242, num243].type = 444;
                                        Main.tile[num242, num243].frameX = (short)((num242 - num233) * 18);
                                        Main.tile[num242, num243].frameY = (short)((num243 - num237 - 1) * 18);
                                    }
                                }
                                continue;
                            }
                        }
                        else if (num233 < Main.maxTilesX - 1 && num237 < Main.maxTilesY - 2 && Main.tile[num233 + 1, num237].active() && Main.tile[num233 + 1, num237].type == 60 && !Main.tile[num233 + 1, num237].bottomSlope() && genRand.Next(40) == 0)
{
                            bool flag6 = true;
                            for (int num244 = num233; num244 < num233 + 2; num244++)
{
                                for (int num245 = num237 + 1; num245 < num237 + 3; num245++)
{
                                    if (Main.tile[num244, num245].active() && (!Main.tileCut[Main.tile[num244, num245].type] || Main.tile[num244, num245].type == 444))
{
                                        flag6 = false;
                                        break;
                                    }
                                    if (Main.tile[num244, num245].liquid > 0 || Main.wallHouse[Main.tile[num244, num245].wall])
{
                                        flag6 = false;
                                        break;
                                    }
                                }
                                if (!flag6)
{
                                    break;
                                }
                            }
                            if (flag6 && CountNearBlocksTypes(num233, num237, 20, 1, 444) > 0)
{
                                flag6 = false;
                            }
                            if (flag6)
{
                                for (int num246 = num233; num246 < num233 + 2; num246++)
{
                                    for (int num247 = num237 + 1; num247 < num237 + 3; num247++)
{
                                        KillTile(num246, num247);
                                    }
                                }
                                for (int num248 = num233; num248 < num233 + 2; num248++)
{
                                    for (int num249 = num237 + 1; num249 < num237 + 3; num249++)
{
                                        Main.tile[num248, num249].active(active: true);
                                        Main.tile[num248, num249].type = 444;
                                        Main.tile[num248, num249].frameX = (short)((num248 - num233) * 18);
                                        Main.tile[num248, num249].frameY = (short)((num249 - num237 - 1) * 18);
                                    }
                                }
                                continue;
                            }
                        }
                        if (genRand.Next(5) < 3)
{
                            num234 = genRand.Next(1, 10);
                        }
                    }
                }
                num234 = 0;
                for (int num250 = 0; num250 < Main.maxTilesY; num250++)
                {
                    if (num234 > 0 && !Main.tile[num233, num250].active())
                    {
                        Main.tile[num233, num250].active(active: true);
                        Main.tile[num233, num250].type = 528;
                        num234--;
                    }
                    else
                    {
                        num234 = 0;
                    }
                    if (Main.tile[num233, num250].active() && Main.tile[num233, num250].type == 70 && genRand.Next(5) == 0 && !Main.tile[num233, num250].bottomSlope() && GrowMoreVines(num233, num250) && genRand.Next(5) < 3)
                    {
                        num234 = genRand.Next(1, 10);
                    }
                }
                num234 = 0;
                for (int num251 = 0; num251 < Main.maxTilesY; num251++)
                {
                    if (num234 > 0 && !Main.tile[num233, num251].active())
                    {
                        Main.tile[num233, num251].active(active: true);
                        Main.tile[num233, num251].type = 636;
                        num234--;
                    }
                    else
                    {
                        num234 = 0;
                    }
                    if (Main.tile[num233, num251].active() && !Main.tile[num233, num251].bottomSlope() && Main.tile[num233, num251].type == 23 && GrowMoreVines(num233, num251) && genRand.Next(5) < 3)
                    {
                        num234 = genRand.Next(1, 10);
                    }
                }
                num234 = 0;
                for (int num252 = 0; num252 < Main.maxTilesY; num252++)
                {
                    if (num234 > 0 && !Main.tile[num233, num252].active())
                    {
                        Main.tile[num233, num252].active(active: true);
                        Main.tile[num233, num252].type = 205;
                        num234--;
                    }
                    else
                    {
                        num234 = 0;
                    }
                    if (Main.tile[num233, num252].active() && !Main.tile[num233, num252].bottomSlope() && Main.tile[num233, num252].type == 199 && GrowMoreVines(num233, num252) && genRand.Next(5) < 3)
                    {
                        num234 = genRand.Next(1, 10);
                    }
                }
                num234 = 0;
                for (int num253 = 0; num253 < Main.maxTilesY; num253++)
                {
                    if (num234 > 0 && !Main.tile[num233, num253].active())
                    {
                        Main.tile[num233, num253].active(active: true);
                        Main.tile[num233, num253].type = 638;
                        num234--;
                    }
                    else
                    {
                        num234 = 0;
                    }
                    if (Main.tile[num233, num253].active() && !Main.tile[num233, num253].bottomSlope() && Main.tile[num233, num253].type == 633 && GrowMoreVines(num233, num253) && genRand.Next(5) < 3)
                    {
                        num234 = genRand.Next(1, 10);
                    }
                }
            }
        });
        AddGenerationPass("Flowers", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            progress.Message = Lang.gen[44].Value;
            int num220 = (int)((double)Main.maxTilesX * 0.004);
            if (remixWorldGen)
            {
                num220 *= 6;
            }
            for (int num221 = 0; num221 < num220; num221++)
            {
                progress.Set((double)num221 / (double)num220);
                int num222 = genRand.Next(100, Main.maxTilesX - 100);
                int num223 = genRand.Next(15, 30);
                int num224 = genRand.Next(15, 30);
                if (remixWorldGen)
                {
                    num223 = genRand.Next(15, 45);
                    num224 = genRand.Next(15, 45);
                    int num225 = genRand.Next((int)Main.rockLayer, Main.maxTilesY - 350);
                    if (GenVars.logX >= 0)
                    {
                        num222 = GenVars.logX;
                        num225 = GenVars.logY;
                        GenVars.logX = -1;
                    }
                    int num226 = genRand.NextFromList<int>(21, 24, 27, 30, 33, 36, 39, 42);
                    for (int num227 = num222 - num223; num227 < num222 + num223; num227++)
                    {
                        for (int num228 = num225 - num224; num228 < num225 + num224; num228++)
{
                            if (Main.tile[num227, num228].type != 488 && !Main.tileSolid[Main.tile[num227, num228].type])
{
                                if (Main.tile[num227, num228].type == 3)
{
                                    Main.tile[num227, num228].frameX = (short)((num226 + genRand.Next(3)) * 18);
                                    if (genRand.Next(3) != 0)
{
                                        Main.tile[num227, num228].type = 73;
                                    }
                                }
                                else if (Main.tile[num227, num228 + 1].wall == 0 && (Main.tile[num227, num228 + 1].type == 2 || ((Main.tile[num227, num228 + 1].type == 40 || Main.tile[num227, num228 + 1].type == 1 || TileID.Sets.Ore[Main.tile[num227, num228 + 1].type]) && !Main.tile[num227, num228].active())) && (!Main.tile[num227, num228].active() || Main.tile[num227, num228].type == 185 || Main.tile[num227, num228].type == 186 || Main.tile[num227, num228].type == 187 || (Main.tile[num227, num228].type == 5 && (double)num227 < (double)Main.maxTilesX * 0.48) || (double)num227 > (double)Main.maxTilesX * 0.52))
{
                                    if (Main.tile[num227, num228 + 1].type == 40 || Main.tile[num227, num228 + 1].type == 1 || TileID.Sets.Ore[Main.tile[num227, num228 + 1].type])
{
                                        Main.tile[num227, num228 + 1].type = 2;
                                        if (Main.tile[num227, num228 + 2].type == 40 || Main.tile[num227, num228 + 2].type == 1 || TileID.Sets.Ore[Main.tile[num227, num228 + 2].type])
{
                                            Main.tile[num227, num228 + 2].type = 2;
                                        }
                                    }
                                    KillTile(num227, num228);
                                    if (genRand.Next(2) == 0)
{
                                        Main.tile[num227, num228 + 1].slope(0);
                                        Main.tile[num227, num228 + 1].halfBrick(halfBrick: false);
                                    }
                                    PlaceTile(num227, num228, 3);
                                    if (Main.tile[num227, num228].active() && Main.tile[num227, num228].type == 3)
{
                                        Main.tile[num227, num228].frameX = (short)((num226 + genRand.Next(3)) * 18);
                                        if (genRand.Next(3) != 0)
{
                                            Main.tile[num227, num228].type = 73;
                                        }
                                    }
                                    if (Main.tile[num227, num228 + 2].type == 40 || Main.tile[num227, num228 + 2].type == 1 || TileID.Sets.Ore[Main.tile[num227, num228 + 2].type])
{
                                        Main.tile[num227, num228 + 2].type = 0;
                                    }
                                }
                            }
                        }
                    }
                }
                else
                {
                    for (int num229 = num224; (double)num229 < Main.worldSurface - (double)num224 - 1.0; num229++)
                    {
                        if (Main.tile[num222, num229].active())
{
                            if (GenVars.logX >= 0)
{
                                num222 = GenVars.logX;
                                num229 = GenVars.logY;
                                GenVars.logX = -1;
                            }
                            int num230 = genRand.NextFromList<int>(21, 24, 27, 30, 33, 36, 39, 42);
                            for (int num231 = num222 - num223; num231 < num222 + num223; num231++)
{
                                for (int num232 = num229 - num224; num232 < num229 + num224; num232++)
{
                                    if (Main.tile[num231, num232].type != 488 && !Main.tileSolid[Main.tile[num231, num232].type])
{
                                        if (Main.tile[num231, num232].type == 3)
{
                                            Main.tile[num231, num232].frameX = (short)((num230 + genRand.Next(3)) * 18);
                                            if (genRand.Next(3) != 0)
{
                                                Main.tile[num231, num232].type = 73;
                                            }
                                        }
                                        else if (Main.tile[num231, num232 + 1].wall == 0 && (Main.tile[num231, num232 + 1].type == 2 || ((Main.tile[num231, num232 + 1].type == 40 || Main.tile[num231, num232 + 1].type == 1 || TileID.Sets.Ore[Main.tile[num231, num232 + 1].type]) && !Main.tile[num231, num232].active())) && (!Main.tile[num231, num232].active() || Main.tile[num231, num232].type == 185 || Main.tile[num231, num232].type == 186 || Main.tile[num231, num232].type == 187 || (Main.tile[num231, num232].type == 5 && (double)num231 < (double)Main.maxTilesX * 0.48) || (double)num231 > (double)Main.maxTilesX * 0.52))
{
                                            if (Main.tile[num231, num232 + 1].type == 40 || Main.tile[num231, num232 + 1].type == 1 || TileID.Sets.Ore[Main.tile[num231, num232 + 1].type])
{
                                                Main.tile[num231, num232 + 1].type = 2;
                                                if (Main.tile[num231, num232 + 2].type == 40 || Main.tile[num231, num232 + 2].type == 1 || TileID.Sets.Ore[Main.tile[num231, num232 + 2].type])
{
                                                    Main.tile[num231, num232 + 2].type = 2;
                                                }
                                            }
                                            KillTile(num231, num232);
                                            if (genRand.Next(2) == 0)
{
                                                Main.tile[num231, num232 + 1].slope(0);
                                                Main.tile[num231, num232 + 1].halfBrick(halfBrick: false);
                                            }
                                            PlaceTile(num231, num232, 3);
                                            if (Main.tile[num231, num232].active() && Main.tile[num231, num232].type == 3)
{
                                                Main.tile[num231, num232].frameX = (short)((num230 + genRand.Next(3)) * 18);
                                                if (genRand.Next(3) != 0)
{
                                                    Main.tile[num231, num232].type = 73;
                                                }
                                            }
                                            if (Main.tile[num231, num232 + 2].type == 40 || Main.tile[num231, num232 + 2].type == 1 || TileID.Sets.Ore[Main.tile[num231, num232 + 2].type])
{
                                                Main.tile[num231, num232 + 2].type = 0;
                                            }
                                        }
                                    }
                                }
                            }
                            break;
                        }
                    }
                }
            }
        });
        AddGenerationPass("Mushrooms", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            progress.Message = Lang.gen[45].Value;
            int num209 = (int)((double)Main.maxTilesX * 0.002);
            if (remixWorldGen)
            {
                num209 *= 9;
            }
            for (int num210 = 0; num210 < num209; num210++)
            {
                progress.Set((double)num210 / (double)num209);
                int num211 = genRand.Next(20, Main.maxTilesX - 20);
                int num212 = genRand.Next(4, 10);
                int num213 = genRand.Next(15, 30);
                if (remixWorldGen)
                {
                    num212 = genRand.Next(8, 17);
                    num213 = genRand.Next(8, 17);
                    int num214 = genRand.Next((int)Main.rockLayer, Main.maxTilesY - 350);
                    if (Main.tile[num211, num214].active())
                    {
                        for (int num215 = num211 - num212; num215 < num211 + num212; num215++)
{
                            for (int num216 = num214 - num213; num216 < num214 + num213; num216++)
{
                                if (num215 < 10)
{
                                    break;
                                }
                                if (num216 < 0)
{
                                    break;
                                }
                                if (num215 > Main.maxTilesX - 10)
{
                                    break;
                                }
                                if (num216 > Main.maxTilesY - 10)
{
                                    break;
                                }
                                if (Main.tile[num215, num216].type == 3 || Main.tile[num215, num216].type == 24)
{
                                    Main.tile[num215, num216].frameX = 144;
                                }
                                else if (Main.tile[num215, num216].type == 201)
{
                                    Main.tile[num215, num216].frameX = 270;
                                }
                            }
                        }
                    }
                }
                else
                {
                    for (int num217 = 1; (double)num217 < Main.worldSurface - 1.0; num217++)
                    {
                        if (Main.tile[num211, num217].active())
{
                            for (int num218 = num211 - num212; num218 < num211 + num212; num218++)
{
                                for (int num219 = num217 - num213; num219 < num217 + num213; num219++)
{
                                    if (num218 < 10)
{
                                        break;
                                    }
                                    if (num219 < 0)
{
                                        break;
                                    }
                                    if (num218 > Main.maxTilesX - 10)
{
                                        break;
                                    }
                                    if (num219 > Main.maxTilesY - 10)
{
                                        break;
                                    }
                                    if (Main.tile[num218, num219].type == 3 || Main.tile[num218, num219].type == 24)
{
                                        Main.tile[num218, num219].frameX = 144;
                                    }
                                    else if (Main.tile[num218, num219].type == 201)
{
                                        Main.tile[num218, num219].frameX = 270;
                                    }
                                }
                            }
                            break;
                        }
                    }
                }
            }
        });
        AddGenerationPass("Gems In Ice Biome", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            progress.Set(1.0);
            for (int num198 = 0; (double)num198 < (double)Main.maxTilesX * 0.25; num198++)
            {
                int num199 = ((!remixWorldGen) ? genRand.Next((int)(Main.worldSurface + Main.rockLayer) / 2, GenVars.lavaLine) : genRand.Next((int)Main.worldSurface, Main.maxTilesY - 300));
                int num200 = genRand.Next(GenVars.snowMinX[num199], GenVars.snowMaxX[num199]);
                if (Main.tile[num200, num199].active() && (Main.tile[num200, num199].type == 147 || Main.tile[num200, num199].type == 161 || Main.tile[num200, num199].type == 162 || Main.tile[num200, num199].type == 224))
                {
                    int num201 = genRand.Next(1, 4);
                    int num202 = genRand.Next(1, 4);
                    int num203 = genRand.Next(1, 4);
                    int num204 = genRand.Next(1, 4);
                    int num205 = genRand.Next(12);
                    int num206 = 0;
                    num206 = ((num205 >= 3) ? ((num205 < 6) ? 1 : ((num205 < 8) ? 2 : ((num205 < 10) ? 3 : ((num205 >= 11) ? 5 : 4)))) : 0);
                    for (int num207 = num200 - num201; num207 < num200 + num202; num207++)
                    {
                        for (int num208 = num199 - num203; num208 < num199 + num204; num208++)
{
                            if (!Main.tile[num207, num208].active())
{
                                PlaceTile(num207, num208, 178, mute: true, forced: false, -1, num206);
                            }
                        }
                    }
                }
            }
        });
        AddGenerationPass("Random Gems", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            progress.Set(1.0);
            for (int num184 = 0; num184 < Main.maxTilesX; num184++)
            {
                int num185 = genRand.Next(20, Main.maxTilesX - 20);
                int num186 = genRand.Next((int)Main.rockLayer, Main.maxTilesY - 300);
                if (!Main.tile[num185, num186].active() && !Main.tile[num185, num186].lava() && !Main.wallDungeon[Main.tile[num185, num186].wall] && Main.tile[num185, num186].wall != 27)
                {
                    int num187 = genRand.Next(12);
                    int num188 = 0;
                    num188 = ((num187 >= 3) ? ((num187 < 6) ? 1 : ((num187 < 8) ? 2 : ((num187 < 10) ? 3 : ((num187 >= 11) ? 5 : 4)))) : 0);
                    PlaceTile(num185, num186, 178, mute: true, forced: false, -1, num188);
                }
            }
            for (int num189 = 0; num189 < Main.maxTilesX; num189++)
            {
                int num190 = genRand.Next(20, Main.maxTilesX - 20);
                int num191 = genRand.Next((int)Main.worldSurface, Main.maxTilesY - 300);
                if (!Main.tile[num190, num191].active() && !Main.tile[num190, num191].lava() && (Main.tile[num190, num191].wall == 216 || Main.tile[num190, num191].wall == 187))
                {
                    int num192 = genRand.Next(1, 4);
                    int num193 = genRand.Next(1, 4);
                    int num194 = genRand.Next(1, 4);
                    int num195 = genRand.Next(1, 4);
                    for (int num196 = num190 - num192; num196 < num190 + num193; num196++)
                    {
                        for (int num197 = num191 - num194; num197 < num191 + num195; num197++)
{
                            if (!Main.tile[num196, num197].active())
{
                                PlaceTile(num196, num197, 178, mute: true, forced: false, -1, 6);
                            }
                        }
                    }
                }
            }
        });
        AddGenerationPass("Moss Grass", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            progress.Set(1.0);
            for (int num179 = 5; num179 < Main.maxTilesX - 5; num179++)
            {
                for (int num180 = 5; num180 < Main.maxTilesY - 5; num180++)
                {
                    if (Main.tile[num179, num180].active() && Main.tileMoss[Main.tile[num179, num180].type])
                    {
                        for (int num181 = 0; num181 < 4; num181++)
{
                            int num182 = num179;
                            int num183 = num180;
                            if (num181 == 0)
{
                                num182--;
                            }
                            if (num181 == 1)
{
                                num182++;
                            }
                            if (num181 == 2)
{
                                num183--;
                            }
                            if (num181 == 3)
{
                                num183++;
                            }
                            if (!Main.tile[num182, num183].active())
{
                                PlaceTile(num182, num183, 184, mute: true);
                            }
                        }
                    }
                }
            }
        });
        AddGenerationPass("Muds Walls In Jungle", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            progress.Set(1.0);
            int num171 = 0;
            int num172 = 0;
            bool flag4 = false;
            for (int num173 = 5; num173 < Main.maxTilesX - 5; num173++)
            {
                for (int num174 = 0; (double)num174 < Main.worldSurface + 20.0; num174++)
                {
                    if (Main.tile[num173, num174].active() && Main.tile[num173, num174].type == 60)
                    {
                        num171 = num173;
                        flag4 = true;
                        break;
                    }
                }
                if (flag4)
                {
                    break;
                }
            }
            flag4 = false;
            for (int num175 = Main.maxTilesX - 5; num175 > 5; num175--)
            {
                for (int num176 = 0; (double)num176 < Main.worldSurface + 20.0; num176++)
                {
                    if (Main.tile[num175, num176].active() && Main.tile[num175, num176].type == 60)
                    {
                        num172 = num175;
                        flag4 = true;
                        break;
                    }
                }
                if (flag4)
                {
                    break;
                }
            }
            GenVars.jungleMinX = num171;
            GenVars.jungleMaxX = num172;
            for (int num177 = num171; num177 <= num172; num177++)
            {
                for (int num178 = 0; (double)num178 < Main.worldSurface + 20.0; num178++)
                {
                    if (((num177 >= num171 + 2 && num177 <= num172 - 2) || genRand.Next(2) != 0) && ((num177 >= num171 + 3 && num177 <= num172 - 3) || genRand.Next(3) != 0) && (Main.tile[num177, num178].wall == 2 || Main.tile[num177, num178].wall == 59))
                    {
                        Main.tile[num177, num178].wall = 15;
                    }
                }
            }
        });
        AddGenerationPass("Larva", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            Main.tileSolid[229] = true;
            progress.Set(1.0);
            for (int num166 = 0; num166 < GenVars.numLarva; num166++)
            {
                int num167 = GenVars.larvaX[num166];
                int num168 = GenVars.larvaY[num166];
                for (int num169 = num167 - 1; num169 <= num167 + 1; num169++)
                {
                    for (int num170 = num168 - 2; num170 <= num168 + 1; num170++)
                    {
                        if (num170 != num168 + 1)
{
                            Main.tile[num169, num170].active(active: false);
                        }
                        else
{
                            Main.tile[num169, num170].active(active: true);
                            Main.tile[num169, num170].type = 225;
                            Main.tile[num169, num170].slope(0);
                            Main.tile[num169, num170].halfBrick(halfBrick: false);
                        }
                    }
                }
                PlaceTile(num167, num168, 231, mute: true);
            }
            Main.tileSolid[232] = true;
            Main.tileSolid[162] = true;
        });
        AddGenerationPass("Settle Liquids Again", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            if (getGoodWorldGen)
            {
                Main.tileSolid[56] = true;
            }
            progress.Message = Lang.gen[27].Value;
            if (notTheBees)
            {
                NotTheBees();
            }
            Liquid.worldGenTilesIgnoreWater(ignoreSolids: true);
            Liquid.QuickWater(3);
            WaterCheck();
            int num160 = 0;
            Liquid.quickSettle = true;
            int num161 = 10;
            while (num160 < num161)
            {
                int num162 = Liquid.numLiquid + LiquidBuffer.numLiquidBuffer;
                num160++;
                double num163 = 0.0;
                int num164 = num162 * 5;
                while (Liquid.numLiquid > 0)
                {
                    num164--;
                    if (num164 < 0)
                    {
                        break;
                    }
                    double num165 = (double)(num162 - (Liquid.numLiquid + LiquidBuffer.numLiquidBuffer)) / (double)num162;
                    if (Liquid.numLiquid + LiquidBuffer.numLiquidBuffer > num162)
                    {
                        num162 = Liquid.numLiquid + LiquidBuffer.numLiquidBuffer;
                    }
                    if (num165 > num163)
                    {
                        num163 = num165;
                    }
                    else
                    {
                        num165 = num163;
                    }
                    if (num160 == 1)
                    {
                        progress.Set(num165 / 3.0 + 0.33);
                    }
                    Liquid.UpdateLiquid();
                }
                WaterCheck();
                progress.Set((double)num160 / (double)num161 / 3.0 + 0.66);
            }
            Liquid.quickSettle = false;
            Liquid.worldGenTilesIgnoreWater(ignoreSolids: false);
            Main.tileSolid[484] = false;
        });
        AddGenerationPass("Cactus, Palm Trees, & Coral", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            progress.Message = Lang.gen[38].Value;
            int num132 = 8;
            if (remixWorldGen)
            {
                num132 = 2;
            }
            int num133 = 400;
            int num134 = genRand.Next(3, 13);
            int num135 = genRand.Next(3, 13);
            int num136 = genRand.Next(2, 6);
            int num137 = genRand.Next(2, 6);
            int num138 = 380;
            for (int num139 = 0; num139 < GenVars.numOasis; num139++)
            {
                int num140 = (int)((double)GenVars.oasisWidth[num139] * 1.5);
                for (int num141 = GenVars.oasisPosition[num139].X - num140; num141 <= GenVars.oasisPosition[num139].X + num140; num141++)
                {
                    for (int num142 = GenVars.oasisPosition[num139].Y - GenVars.oasisHeight; num142 <= GenVars.oasisPosition[num139].Y + GenVars.oasisHeight; num142++)
                    {
                        double num143 = 1.0;
                        int num144 = 8;
                        for (int num145 = num141 - num144; num145 <= num141 + num144; num145++)
{
                            for (int num146 = num142 - num144; num146 <= num142 + num144; num146++)
{
                                if (InWorld(num145, num146) && Main.tile[num145, num146] != null && Main.tile[num145, num146].active() && Main.tile[num145, num146].type == 323)
{
                                    num143 = 0.13;
                                }
                            }
                        }
                        if (genRand.NextDouble() < num143)
{
                            GrowPalmTree(num141, num142);
                        }
                        if (PlantSeaOat(num141, num142))
{
                            if (genRand.Next(2) == 0)
{
                                GrowSeaOat(num141, num142);
                            }
                            if (genRand.Next(2) == 0)
{
                                GrowSeaOat(num141, num142);
                            }
                        }
                        PlaceOasisPlant(num141, num142, 530);
                    }
                }
            }
            for (int num147 = 0; num147 < 3; num147++)
            {
                progress.Set((double)num147 / 3.0);
                int num148;
                int num149;
                bool flag3;
                int maxValue4;
                switch (num147)
                {
                default:
                    num148 = 5;
                    num149 = num138;
                    flag3 = false;
                    maxValue4 = num134;
                    break;
                case 1:
                    num148 = num133;
                    num149 = Main.maxTilesX - num133;
                    flag3 = true;
                    maxValue4 = num132;
                    break;
                case 2:
                    num148 = Main.maxTilesX - num138;
                    num149 = Main.maxTilesX - 5;
                    flag3 = false;
                    maxValue4 = num135;
                    break;
                }
                double num150 = Main.worldSurface - 1.0;
                if (remixWorldGen)
                {
                    num150 = Main.maxTilesY - 50;
                }
                for (int num151 = num148; num151 < num149; num151++)
                {
                    if (genRand.Next(maxValue4) == 0)
                    {
                        for (int num152 = 0; (double)num152 < num150; num152++)
{
                            Tile tile4 = Main.tile[num151, num152];
                            if (tile4.active() && (tile4.type == 53 || tile4.type == 112 || tile4.type == 234))
{
                                Tile tile5 = Main.tile[num151, num152 - 1];
                                if (!tile5.active() && tile5.wall == 0)
{
                                    if (flag3)
{
                                        if (remixWorldGen)
{
                                            if ((double)num152 > Main.worldSurface)
{
                                                if (SolidTile(num151, num152) && Main.tile[num151, num152 + 1].type == 53 && Main.tile[num151, num152 + 2].type == 53)
{
                                                    int maxValue5 = 3;
                                                    GrowPalmTree(num151, num152);
                                                    if (!Main.tile[num151, num152 - 1].active() && genRand.Next(maxValue5) == 0)
{
                                                        PlantCactus(num151, num152);
                                                    }
                                                }
                                            }
                                            else
{
                                                int num153 = 0;
                                                for (int num154 = num151 - cactusWaterWidth; num154 < num151 + cactusWaterWidth; num154++)
{
                                                    for (int num155 = num152 - cactusWaterHeight; num155 < num152 + cactusWaterHeight; num155++)
{
                                                        num153 += Main.tile[num154, num155].liquid;
                                                    }
                                                }
                                                if (num153 / 255 > cactusWaterLimit)
{
                                                    int maxValue6 = 4;
                                                    if (genRand.Next(maxValue6) == 0)
{
                                                        GrowPalmTree(num151, num152);
                                                    }
                                                }
                                                else
{
                                                    PlantCactus(num151, num152);
                                                }
                                            }
                                        }
                                        else
{
                                            int num156 = 0;
                                            for (int num157 = num151 - cactusWaterWidth; num157 < num151 + cactusWaterWidth; num157++)
{
                                                for (int num158 = num152 - cactusWaterHeight; num158 < num152 + cactusWaterHeight; num158++)
{
                                                    num156 += Main.tile[num157, num158].liquid;
                                                }
                                            }
                                            if (num156 / 255 > cactusWaterLimit)
{
                                                int maxValue7 = 4;
                                                if (genRand.Next(maxValue7) == 0)
{
                                                    GrowPalmTree(num151, num152);
                                                }
                                            }
                                            else
{
                                                PlantCactus(num151, num152);
                                            }
                                        }
                                    }
                                    else
{
                                        if (Main.tile[num151, num152 - 2].liquid == byte.MaxValue && Main.tile[num151, num152 - 3].liquid == byte.MaxValue && Main.tile[num151, num152 - 4].liquid == byte.MaxValue)
{
                                            if (genRand.Next(2) == 0)
{
                                                PlaceTile(num151, num152 - 1, 81, mute: true);
                                            }
                                            else
{
                                                PlaceTile(num151, num152 - 1, 324, mute: true, forced: false, -1, RollRandomSeaShellStyle());
                                            }
                                            break;
                                        }
                                        if (Main.tile[num151, num152 - 2].liquid == 0 && (double)num152 < Main.worldSurface)
{
                                            PlaceTile(num151, num152 - 1, 324, mute: true, forced: false, -1, RollRandomSeaShellStyle());
                                            break;
                                        }
                                    }
                                }
                            }
                        }
                    }
                    else
                    {
                        for (int num159 = 0; (double)num159 < num150; num159++)
{
                            if (PlantSeaOat(num151, num159))
{
                                if (genRand.Next(2) == 0)
{
                                    GrowSeaOat(num151, num159);
                                }
                                if (genRand.Next(2) == 0)
{
                                    GrowSeaOat(num151, num159);
                                }
                            }
                            PlaceOasisPlant(num151, num159, 530);
                        }
                    }
                }
            }
        });
        AddGenerationPass("Tile Cleanup", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            progress.Message = Lang.gen[84].Value;
            for (int num64 = 40; num64 < Main.maxTilesX - 40; num64++)
            {
                progress.Set((double)(num64 - 40) / (double)(Main.maxTilesX - 80));
                for (int num65 = 40; num65 < Main.maxTilesY - 40; num65++)
                {
                    if (Main.tile[num64, num65].active() && Main.tile[num64, num65].topSlope() && ((Main.tile[num64, num65].leftSlope() && Main.tile[num64 + 1, num65].halfBrick()) || (Main.tile[num64, num65].rightSlope() && Main.tile[num64 - 1, num65].halfBrick())))
                    {
                        Main.tile[num64, num65].slope(0);
                        Main.tile[num64, num65].halfBrick(halfBrick: true);
                    }
                    if (Main.tile[num64, num65].active() && Main.tile[num64, num65].liquid > 0 && TileID.Sets.SlowlyDiesInWater[Main.tile[num64, num65].type])
                    {
                        KillTile(num64, num65);
                    }
                    if (!Main.tile[num64, num65].active() && Main.tile[num64, num65].liquid == 0 && genRand.Next(3) != 0 && SolidTile(num64, num65 - 1))
                    {
                        int num66 = genRand.Next(15, 21);
                        for (int num67 = num65 - 2; num67 >= num65 - num66; num67--)
{
                            if (Main.tile[num64, num67].liquid >= 128 && !Main.tile[num64, num67].shimmer())
{
                                int num68 = 373;
                                if (Main.tile[num64, num67].lava())
{
                                    num68 = 374;
                                }
                                else if (Main.tile[num64, num67].honey())
{
                                    num68 = 375;
                                }
                                int maxValue3 = num65 - num67;
                                if (genRand.Next(maxValue3) <= 1)
{
                                    if (Main.tile[num64, num65].wall == 86)
{
                                        num68 = 375;
                                    }
                                    Main.tile[num64, num65].type = (ushort)num68;
                                    Main.tile[num64, num65].frameX = 0;
                                    Main.tile[num64, num65].frameY = 0;
                                    Main.tile[num64, num65].active(active: true);
                                    break;
                                }
                            }
                        }
                        if (!Main.tile[num64, num65].active())
{
                            num66 = genRand.Next(3, 11);
                            for (int num69 = num65 + 1; num69 <= num65 + num66; num69++)
{
                                if (Main.tile[num64, num69].liquid >= 200 && !Main.tile[num64, num69].shimmer())
{
                                    int num70 = 373;
                                    if (Main.tile[num64, num69].lava())
{
                                        num70 = 374;
                                    }
                                    else if (Main.tile[num64, num69].honey())
{
                                        num70 = 375;
                                    }
                                    int num71 = num69 - num65;
                                    if (genRand.Next(num71 * 3) <= 1)
{
                                        Main.tile[num64, num65].type = (ushort)num70;
                                        Main.tile[num64, num65].frameX = 0;
                                        Main.tile[num64, num65].frameY = 0;
                                        Main.tile[num64, num65].active(active: true);
                                        break;
                                    }
                                }
                            }
                        }
                        if (!Main.tile[num64, num65].active() && genRand.Next(4) == 0)
{
                            Tile tile3 = Main.tile[num64, num65 - 1];
                            if (TileID.Sets.Conversion.Sandstone[tile3.type] || TileID.Sets.Conversion.HardenedSand[tile3.type])
{
                                Main.tile[num64, num65].type = 461;
                                Main.tile[num64, num65].frameX = 0;
                                Main.tile[num64, num65].frameY = 0;
                                Main.tile[num64, num65].active(active: true);
                            }
                        }
                    }
                    if (Main.tile[num64, num65].type == 137)
                    {
                        int num72 = Main.tile[num64, num65].frameY / 18;
                        if (num72 <= 2 || num72 == 5)
{
                            int num73 = -1;
                            if (Main.tile[num64, num65].frameX >= 18)
{
                                num73 = 1;
                            }
                            if (Main.tile[num64 + num73, num65].halfBrick() || Main.tile[num64 + num73, num65].slope() != 0)
{
                                Main.tile[num64 + num73, num65].active(active: false);
                            }
                        }
                    }
                    else if (Main.tile[num64, num65].type == 162 && Main.tile[num64, num65 + 1].liquid == 0 && CanKillTile(num64, num65))
                    {
                        Main.tile[num64, num65].active(active: false);
                    }
                    if (Main.tile[num64, num65].wall == 13 || Main.tile[num64, num65].wall == 14)
                    {
                        Main.tile[num64, num65].liquid = 0;
                    }
                    if (Main.tile[num64, num65].type == 31)
                    {
                        int num74 = Main.tile[num64, num65].frameX / 18;
                        int num75 = 0;
                        int num76 = num64;
                        num75 += num74 / 2;
                        num75 = ((!drunkWorldGen) ? (crimson ? 1 : 0) : ((Main.tile[num64, num65].wall == 83) ? 1 : 0));
                        num74 %= 2;
                        num76 -= num74;
                        int num77 = Main.tile[num64, num65].frameY / 18;
                        int num78 = 0;
                        int num79 = num65;
                        num78 += num77 / 2;
                        num77 %= 2;
                        num79 -= num77;
                        for (int num80 = 0; num80 < 2; num80++)
{
                            for (int num81 = 0; num81 < 2; num81++)
{
                                int num82 = num76 + num80;
                                int num83 = num79 + num81;
                                Main.tile[num82, num83].active(active: true);
                                Main.tile[num82, num83].slope(0);
                                Main.tile[num82, num83].halfBrick(halfBrick: false);
                                Main.tile[num82, num83].type = 31;
                                Main.tile[num82, num83].frameX = (short)(num80 * 18 + 36 * num75);
                                Main.tile[num82, num83].frameY = (short)(num81 * 18 + 36 * num78);
                            }
                        }
                    }
                    if (Main.tile[num64, num65].type == 12)
                    {
                        int num84 = Main.tile[num64, num65].frameX / 18;
                        int num85 = 0;
                        int num86 = num64;
                        num85 += num84 / 2;
                        num84 %= 2;
                        num86 -= num84;
                        int num87 = Main.tile[num64, num65].frameY / 18;
                        int num88 = 0;
                        int num89 = num65;
                        num88 += num87 / 2;
                        num87 %= 2;
                        num89 -= num87;
                        for (int num90 = 0; num90 < 2; num90++)
{
                            for (int num91 = 0; num91 < 2; num91++)
{
                                int num92 = num86 + num90;
                                int num93 = num89 + num91;
                                Main.tile[num92, num93].active(active: true);
                                Main.tile[num92, num93].slope(0);
                                Main.tile[num92, num93].halfBrick(halfBrick: false);
                                Main.tile[num92, num93].type = 12;
                                Main.tile[num92, num93].frameX = (short)(num90 * 18 + 36 * num85);
                                Main.tile[num92, num93].frameY = (short)(num91 * 18 + 36 * num88);
                            }
                            if (!Main.tile[num90, num65 + 2].active())
{
                                Main.tile[num90, num65 + 2].active(active: true);
                                if (!Main.tileSolid[Main.tile[num90, num65 + 2].type] || Main.tileSolidTop[Main.tile[num90, num65 + 2].type])
{
                                    Main.tile[num90, num65 + 2].type = 0;
                                }
                            }
                            Main.tile[num90, num65 + 2].slope(0);
                            Main.tile[num90, num65 + 2].halfBrick(halfBrick: false);
                        }
                    }
                    if (Main.tile[num64, num65].type == 639)
                    {
                        int num94 = Main.tile[num64, num65].frameX / 18;
                        int num95 = 0;
                        int num96 = num64;
                        num95 += num94 / 2;
                        num94 %= 2;
                        num96 -= num94;
                        int num97 = Main.tile[num64, num65].frameY / 18;
                        int num98 = 0;
                        int num99 = num65;
                        num98 += num97 / 2;
                        num97 %= 2;
                        num99 -= num97;
                        for (int num100 = 0; num100 < 2; num100++)
{
                            for (int num101 = 0; num101 < 2; num101++)
{
                                int num102 = num96 + num100;
                                int num103 = num99 + num101;
                                Main.tile[num102, num103].active(active: true);
                                Main.tile[num102, num103].slope(0);
                                Main.tile[num102, num103].halfBrick(halfBrick: false);
                                Main.tile[num102, num103].type = 639;
                                Main.tile[num102, num103].frameX = (short)(num100 * 18 + 36 * num95);
                                Main.tile[num102, num103].frameY = (short)(num101 * 18 + 36 * num98);
                            }
                            if (!Main.tile[num100, num65 + 2].active())
{
                                Main.tile[num100, num65 + 2].active(active: true);
                                if (!Main.tileSolid[Main.tile[num100, num65 + 2].type] || Main.tileSolidTop[Main.tile[num100, num65 + 2].type])
{
                                    Main.tile[num100, num65 + 2].type = 0;
                                }
                            }
                            Main.tile[num100, num65 + 2].slope(0);
                            Main.tile[num100, num65 + 2].halfBrick(halfBrick: false);
                        }
                    }
                    if (TileID.Sets.BasicChest[Main.tile[num64, num65].type])
                    {
                        int num104 = Main.tile[num64, num65].frameX / 18;
                        int num105 = 0;
                        ushort type2 = 21;
                        int num106 = num64;
                        int num107 = num65 - Main.tile[num64, num65].frameY / 18;
                        if (Main.tile[num64, num65].type == 467)
{
                            type2 = 467;
                        }
                        while (num104 >= 2)
{
                            num105++;
                            num104 -= 2;
                        }
                        num106 -= num104;
                        int num108 = Chest.FindChest(num106, num107);
                        if (num108 != -1)
{
                            switch (Main.chest[num108].item[0].type)
{
                            case 1156:
                                num105 = 23;
                                break;
                            case 1571:
                                num105 = 24;
                                break;
                            case 1569:
                                num105 = 25;
                                break;
                            case 1260:
                                num105 = 26;
                                break;
                            case 1572:
                                num105 = 27;
                                break;
                            }
                        }
                        for (int num109 = 0; num109 < 2; num109++)
{
                            for (int num110 = 0; num110 < 2; num110++)
{
                                int num111 = num106 + num109;
                                int num112 = num107 + num110;
                                Main.tile[num111, num112].active(active: true);
                                Main.tile[num111, num112].slope(0);
                                Main.tile[num111, num112].halfBrick(halfBrick: false);
                                Main.tile[num111, num112].type = type2;
                                Main.tile[num111, num112].frameX = (short)(num109 * 18 + 36 * num105);
                                Main.tile[num111, num112].frameY = (short)(num110 * 18);
                            }
                            if (!Main.tile[num109, num65 + 2].active())
{
                                Main.tile[num109, num65 + 2].active(active: true);
                                if (!Main.tileSolid[Main.tile[num109, num65 + 2].type] || Main.tileSolidTop[Main.tile[num109, num65 + 2].type])
{
                                    Main.tile[num109, num65 + 2].type = 0;
                                }
                            }
                            Main.tile[num109, num65 + 2].slope(0);
                            Main.tile[num109, num65 + 2].halfBrick(halfBrick: false);
                        }
                    }
                    if (Main.tile[num64, num65].type == 28)
                    {
                        int num113 = Main.tile[num64, num65].frameX / 18;
                        int num114 = 0;
                        int num115 = num64;
                        while (num113 >= 2)
{
                            num114++;
                            num113 -= 2;
                        }
                        num115 -= num113;
                        int num116 = Main.tile[num64, num65].frameY / 18;
                        int num117 = 0;
                        int num118 = num65;
                        while (num116 >= 2)
{
                            num117++;
                            num116 -= 2;
                        }
                        num118 -= num116;
                        for (int num119 = 0; num119 < 2; num119++)
{
                            for (int num120 = 0; num120 < 2; num120++)
{
                                int num121 = num115 + num119;
                                int num122 = num118 + num120;
                                Main.tile[num121, num122].active(active: true);
                                Main.tile[num121, num122].slope(0);
                                Main.tile[num121, num122].halfBrick(halfBrick: false);
                                Main.tile[num121, num122].type = 28;
                                Main.tile[num121, num122].frameX = (short)(num119 * 18 + 36 * num114);
                                Main.tile[num121, num122].frameY = (short)(num120 * 18 + 36 * num117);
                            }
                            if (!Main.tile[num119, num65 + 2].active())
{
                                Main.tile[num119, num65 + 2].active(active: true);
                                if (!Main.tileSolid[Main.tile[num119, num65 + 2].type] || Main.tileSolidTop[Main.tile[num119, num65 + 2].type])
{
                                    Main.tile[num119, num65 + 2].type = 0;
                                }
                            }
                            Main.tile[num119, num65 + 2].slope(0);
                            Main.tile[num119, num65 + 2].halfBrick(halfBrick: false);
                        }
                    }
                    if (Main.tile[num64, num65].type == 26)
                    {
                        int num123 = Main.tile[num64, num65].frameX / 18;
                        int num124 = 0;
                        int num125 = num64;
                        int num126 = num65 - Main.tile[num64, num65].frameY / 18;
                        while (num123 >= 3)
{
                            num124++;
                            num123 -= 3;
                        }
                        num125 -= num123;
                        num124 = (drunkWorldGen ? ((Main.tile[num64, num65].wall == 83) ? 1 : 0) : (crimson ? 1 : 0));
                        for (int num127 = 0; num127 < 3; num127++)
{
                            for (int num128 = 0; num128 < 2; num128++)
{
                                int num129 = num125 + num127;
                                int num130 = num126 + num128;
                                Main.tile[num129, num130].active(active: true);
                                Main.tile[num129, num130].slope(0);
                                Main.tile[num129, num130].halfBrick(halfBrick: false);
                                Main.tile[num129, num130].type = 26;
                                Main.tile[num129, num130].frameX = (short)(num127 * 18 + 54 * num124);
                                Main.tile[num129, num130].frameY = (short)(num128 * 18);
                            }
                            if (!Main.tile[num125 + num127, num126 + 2].active() || !Main.tileSolid[Main.tile[num125 + num127, num126 + 2].type] || Main.tileSolidTop[Main.tile[num125 + num127, num126 + 2].type])
{
                                Main.tile[num125 + num127, num126 + 2].active(active: true);
                                if (!TileID.Sets.Platforms[Main.tile[num125 + num127, num126 + 2].type])
{
                                    if (Main.tile[num125 + num127, num126 + 2].type == 484)
{
                                        Main.tile[num125 + num127, num126 + 2].type = 397;
                                    }
                                    else if (TileID.Sets.Boulders[Main.tile[num125 + num127, num126 + 2].type] || !Main.tileSolid[Main.tile[num125 + num127, num126 + 2].type] || Main.tileSolidTop[Main.tile[num125 + num127, num126 + 2].type])
{
                                        Main.tile[num125 + num127, num126 + 2].type = 0;
                                    }
                                }
                            }
                            Main.tile[num125 + num127, num126 + 2].slope(0);
                            Main.tile[num125 + num127, num126 + 2].halfBrick(halfBrick: false);
                            if (Main.tile[num125 + num127, num126 + 3].type == 28 && Main.tile[num125 + num127, num126 + 3].frameY % 36 >= 18)
{
                                Main.tile[num125 + num127, num126 + 3].type = 0;
                                Main.tile[num125 + num127, num126 + 3].active(active: false);
                            }
                        }
                        for (int num131 = 0; num131 < 3; num131++)
{
                            if ((Main.tile[num125 - 1, num126 + num131].type == 28 || Main.tile[num125 - 1, num126 + num131].type == 12 || Main.tile[num125 - 1, num126 + num131].type == 639) && Main.tile[num125 - 1, num126 + num131].frameX % 36 < 18)
{
                                Main.tile[num125 - 1, num126 + num131].type = 0;
                                Main.tile[num125 - 1, num126 + num131].active(active: false);
                            }
                            if ((Main.tile[num125 + 3, num126 + num131].type == 28 || Main.tile[num125 + 3, num126 + num131].type == 12 || Main.tile[num125 - 1, num126 + num131].type == 639) && Main.tile[num125 + 3, num126 + num131].frameX % 36 >= 18)
{
                                Main.tile[num125 + 3, num126 + num131].type = 0;
                                Main.tile[num125 + 3, num126 + num131].active(active: false);
                            }
                        }
                    }
                    if (Main.tile[num64, num65].type == 237 && Main.tile[num64, num65 + 1].type == 232)
                    {
                        Main.tile[num64, num65 + 1].type = 226;
                    }
                    if (Main.tile[num64, num65].wall == 87)
                    {
                        Main.tile[num64, num65].liquid = 0;
                    }
                }
            }
        });
        AddGenerationPass("Lihzahrd Altars", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            progress.Set(1.0);
            for (int num58 = 0; num58 < 3; num58++)
            {
                for (int num59 = 0; num59 < 2; num59++)
                {
                    int num60 = GenVars.lAltarX + num58;
                    int num61 = GenVars.lAltarY + num59;
                    Main.tile[num60, num61].active(active: true);
                    Main.tile[num60, num61].type = 237;
                    Main.tile[num60, num61].frameX = (short)(num58 * 18);
                    Main.tile[num60, num61].frameY = (short)(num59 * 18);
                }
                Main.tile[GenVars.lAltarX + num58, GenVars.lAltarY + 2].active(active: true);
                Main.tile[GenVars.lAltarX + num58, GenVars.lAltarY + 2].slope(0);
                Main.tile[GenVars.lAltarX + num58, GenVars.lAltarY + 2].halfBrick(halfBrick: false);
                Main.tile[GenVars.lAltarX + num58, GenVars.lAltarY + 2].type = 226;
            }
            for (int num62 = 0; num62 < 3; num62++)
            {
                for (int num63 = 0; num63 < 2; num63++)
                {
                    int i2 = GenVars.lAltarX + num62;
                    int j2 = GenVars.lAltarY + num63;
                    SquareTileFrame(i2, j2);
                }
            }
        });
        AddGenerationPass("Micro Biomes", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            progress.Message = Lang.gen[76].Value;
            _ = (double)(Main.maxTilesX * Main.maxTilesY) / 5040000.0;
            double num36 = 10.0;
            if (getGoodWorldGen || noTrapsWorldGen)
            {
                num36 *= 3.0;
            }
            DeadMansChestBiome deadMansChestBiome = GenVars.configuration.CreateBiome<DeadMansChestBiome>();
            List<int> possibleChestsToTrapify = deadMansChestBiome.GetPossibleChestsToTrapify(GenVars.structures);
            int random = passConfig.Get<WorldGenRange>("DeadManChests").GetRandom(genRand);
            int num37 = 0;
            int num38 = 3000;
            while (num37 < random && possibleChestsToTrapify.Count > 0)
            {
                num38--;
                if (num38 <= 0)
                {
                    break;
                }
                int num39 = possibleChestsToTrapify[genRand.Next(possibleChestsToTrapify.Count)];
                Point origin = new Point(Main.chest[num39].x, Main.chest[num39].y);
                deadMansChestBiome.Place(origin, GenVars.structures);
                num37++;
                possibleChestsToTrapify.Remove(num39);
            }
            progress.Set(1.0 / num36);
            if (!notTheBees || remixWorldGen)
            {
                ThinIceBiome thinIceBiome = GenVars.configuration.CreateBiome<ThinIceBiome>();
                int random2 = passConfig.Get<WorldGenRange>("ThinIcePatchCount").GetRandom(genRand);
                int num40 = 0;
                int num41 = 1000;
                int num42 = 0;
                while (num42 < random2)
                {
                    if (thinIceBiome.Place(RandomWorldPoint((int)Main.worldSurface + 20, 50, 200, 50), GenVars.structures))
                    {
                        num42++;
                        num40 = 0;
                    }
                    else
                    {
                        num40++;
                        if (num40 > num41)
{
                            num42++;
                            num40 = 0;
                        }
                    }
                }
            }
            progress.Set(0.1);
            progress.Set(2.0 / num36);
            EnchantedSwordBiome enchantedSwordBiome = GenVars.configuration.CreateBiome<EnchantedSwordBiome>();
            int num43 = passConfig.Get<WorldGenRange>("SwordShrineAttempts").GetRandom(genRand);
            double num44 = passConfig.Get<double>("SwordShrinePlacementChance");
            if (tenthAnniversaryWorldGen)
            {
                num43 *= 2;
                num44 /= 2.0;
            }
            Point origin2 = default(Point);
            for (int num45 = 0; num45 < num43; num45++)
            {
                if ((num45 == 0 && tenthAnniversaryWorldGen) || !(genRand.NextDouble() > num44))
                {
                    int num46 = 0;
                    while (num46++ <= Main.maxTilesX)
                    {
                        origin2.Y = (int)GenVars.worldSurface + genRand.Next(50, 100);
                        if (genRand.Next(2) == 0)
{
                            origin2.X = genRand.Next(50, (int)((double)Main.maxTilesX * 0.3));
                        }
                        else
{
                            origin2.X = genRand.Next((int)((double)Main.maxTilesX * 0.7), Main.maxTilesX - 50);
                        }
                        if (enchantedSwordBiome.Place(origin2, GenVars.structures))
{
                            break;
                        }
                    }
                }
            }
            progress.Set(0.2);
            progress.Set(3.0 / num36);
            if (!notTheBees || remixWorldGen)
            {
                CampsiteBiome campsiteBiome = GenVars.configuration.CreateBiome<CampsiteBiome>();
                int random3 = passConfig.Get<WorldGenRange>("CampsiteCount").GetRandom(genRand);
                num38 = 1000;
                int num47 = 0;
                while (num47 < random3)
                {
                    num38--;
                    if (num38 <= 0)
                    {
                        break;
                    }
                    if (campsiteBiome.Place(RandomWorldPoint((int)Main.worldSurface, beachDistance, 200, beachDistance), GenVars.structures))
                    {
                        num47++;
                    }
                }
            }
            progress.Set(4.0 / num36);
            if (!notTheBees || remixWorldGen)
            {
                MiningExplosivesBiome miningExplosivesBiome = GenVars.configuration.CreateBiome<MiningExplosivesBiome>();
                int num48 = passConfig.Get<WorldGenRange>("ExplosiveTrapCount").GetRandom(genRand);
                if ((getGoodWorldGen || noTrapsWorldGen) && !notTheBees)
                {
                    num48 = (int)((double)num48 * 1.5);
                }
                num38 = 3000;
                int num49 = 0;
                while (num49 < num48)
                {
                    num38--;
                    if (num38 <= 0)
                    {
                        break;
                    }
                    if (remixWorldGen)
                    {
                        if (miningExplosivesBiome.Place(RandomWorldPoint((int)Main.worldSurface, beachDistance, (int)GenVars.rockLayer, beachDistance), GenVars.structures))
{
                            num49++;
                        }
                    }
                    else if (miningExplosivesBiome.Place(RandomWorldPoint((int)GenVars.rockLayer, beachDistance, 200, beachDistance), GenVars.structures))
                    {
                        num49++;
                    }
                }
            }
            progress.Set(0.3);
            progress.Set(5.0 / num36);
            MahoganyTreeBiome mahoganyTreeBiome = GenVars.configuration.CreateBiome<MahoganyTreeBiome>();
            int random4 = passConfig.Get<WorldGenRange>("LivingTreeCount").GetRandom(genRand);
            int num50 = 0;
            int num51 = 0;
            while (num50 < random4 && num51 < 20000)
            {
                if (mahoganyTreeBiome.Place(RandomWorldPoint((int)Main.worldSurface + 50, 50, 500, 50), GenVars.structures))
                {
                    num50++;
                }
                num51++;
            }
            progress.Set(0.4);
            progress.Set(6.0 / num36);
            progress.Set(7.0 / num36);
            TrackGenerator trackGenerator = new TrackGenerator();
            int random5 = passConfig.Get<WorldGenRange>("LongTrackCount").GetRandom(genRand);
            WorldGenRange worldGenRange = passConfig.Get<WorldGenRange>("LongTrackLength");
            int maxTilesX = Main.maxTilesX;
            int num52 = 0;
            int num53 = 0;
            while (num53 < random5)
            {
                if (trackGenerator.Place(RandomWorldPoint((int)Main.worldSurface, 10, 200, 10), worldGenRange.ScaledMinimum, worldGenRange.ScaledMaximum))
                {
                    num53++;
                    num52 = 0;
                }
                else
                {
                    num52++;
                    if (num52 > maxTilesX)
                    {
                        num53++;
                        num52 = 0;
                    }
                }
            }
            progress.Set(8.0 / num36);
            random5 = passConfig.Get<WorldGenRange>("StandardTrackCount").GetRandom(genRand);
            worldGenRange = passConfig.Get<WorldGenRange>("StandardTrackLength");
            num52 = 0;
            int num54 = 0;
            while (num54 < random5)
            {
                if (trackGenerator.Place(RandomWorldPoint((int)Main.worldSurface, 10, 200, 10), worldGenRange.ScaledMinimum, worldGenRange.ScaledMaximum))
                {
                    num54++;
                    num52 = 0;
                }
                else
                {
                    num52++;
                    if (num52 > maxTilesX)
                    {
                        num54++;
                        num52 = 0;
                    }
                }
            }
            progress.Set(9.0 / num36);
            if (!notTheBees)
            {
                double num55 = (double)Main.maxTilesX * 0.02;
                if (noTrapsWorldGen)
                {
                    num36 *= 5.0;
                }
                else if (getGoodWorldGen)
                {
                    num36 *= 2.0;
                }
                for (int num56 = 0; (double)num56 < num55; num56++)
                {
                    for (int num57 = 0; num57 < 10150; num57++)
                    {
                        int x2 = genRand.Next(200, Main.maxTilesX - 200);
                        int y2 = genRand.Next(GenVars.lavaLine - 100, Main.maxTilesY - 210);
                        if (placeLavaTrap(x2, y2))
{
                            break;
                        }
                    }
                }
            }
            progress.Set(1.0);
        });
        AddGenerationPass("Water Plants", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            progress.Message = Lang.gen[88].Value;
            int num28 = (int)Main.worldSurface;
            if (remixWorldGen)
            {
                num28 = Main.maxTilesY - 200;
            }
            for (int num29 = 20; num29 < Main.maxTilesX - 20; num29++)
            {
                progress.Set((double)num29 / (double)Main.maxTilesX);
                for (int num30 = 1; num30 < num28; num30++)
                {
                    if (genRand.Next(5) == 0 && Main.tile[num29, num30].liquid > 0)
                    {
                        if (!Main.tile[num29, num30].active())
{
                            if (genRand.Next(2) == 0)
{
                                PlaceLilyPad(num29, num30);
                            }
                            else
{
                                Point point = PlaceCatTail(num29, num30);
                                if (InWorld(point.X, point.Y))
{
                                    int num31 = genRand.Next(14);
                                    for (int num32 = 0; num32 < num31; num32++)
{
                                        GrowCatTail(point.X, point.Y);
                                    }
                                    SquareTileFrame(point.X, point.Y);
                                }
                            }
                        }
                        if ((!Main.tile[num29, num30].active() || Main.tile[num29, num30].type == 61 || Main.tile[num29, num30].type == 74) && PlaceBamboo(num29, num30))
{
                            int num33 = genRand.Next(10, 20);
                            for (int num34 = 0; num34 < num33 && PlaceBamboo(num29, num30 - num34); num34++)
{
                            }
                        }
                    }
                }
                int num35 = Main.UnderworldLayer;
                while ((double)num35 > Main.worldSurface)
                {
                    if (Main.tile[num29, num35].type == 53 && genRand.Next(3) != 0)
                    {
                        GrowCheckSeaweed(num29, num35);
                    }
                    else if (Main.tile[num29, num35].type == 549)
                    {
                        GrowCheckSeaweed(num29, num35);
                    }
                    num35--;
                }
            }
        });
        AddGenerationPass("Stalac", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            progress.Set(1.0);
            for (int num24 = 20; num24 < Main.maxTilesX - 20; num24++)
            {
                for (int num25 = (int)Main.worldSurface; num25 < Main.maxTilesY - 20; num25++)
                {
                    if ((Main.tenthAnniversaryWorld || drunkWorldGen || genRand.Next(5) == 0) && Main.tile[num24, num25 - 1].liquid == 0)
                    {
                        int num26 = genRand.Next(7);
                        int treeTileType = 0;
                        switch (num26)
{
                        case 0:
                            treeTileType = 583;
                            break;
                        case 1:
                            treeTileType = 584;
                            break;
                        case 2:
                            treeTileType = 585;
                            break;
                        case 3:
                            treeTileType = 586;
                            break;
                        case 4:
                            treeTileType = 587;
                            break;
                        case 5:
                            treeTileType = 588;
                            break;
                        case 6:
                            treeTileType = 589;
                            break;
                        }
                        TryGrowingTreeByType(treeTileType, num24, num25);
                    }
                    if (!oceanDepths(num24, num25) && !Main.tile[num24, num25].active() && genRand.Next(5) == 0)
                    {
                        if ((Main.tile[num24, num25 - 1].type == 1 || Main.tile[num24, num25 - 1].type == 147 || Main.tile[num24, num25 - 1].type == 161 || Main.tile[num24, num25 - 1].type == 25 || Main.tile[num24, num25 - 1].type == 203 || Main.tileStone[Main.tile[num24, num25 - 1].type] || Main.tileMoss[Main.tile[num24, num25 - 1].type]) && !Main.tile[num24, num25].active() && !Main.tile[num24, num25 + 1].active())
{
                            Main.tile[num24, num25 - 1].slope(0);
                        }
                        if ((Main.tile[num24, num25 + 1].type == 1 || Main.tile[num24, num25 + 1].type == 147 || Main.tile[num24, num25 + 1].type == 161 || Main.tile[num24, num25 + 1].type == 25 || Main.tile[num24, num25 + 1].type == 203 || Main.tileStone[Main.tile[num24, num25 + 1].type] || Main.tileMoss[Main.tile[num24, num25 + 1].type]) && !Main.tile[num24, num25].active() && !Main.tile[num24, num25 - 1].active())
{
                            Main.tile[num24, num25 + 1].slope(0);
                        }
                        PlaceTight(num24, num25);
                    }
                }
                for (int num27 = 5; num27 < (int)Main.worldSurface; num27++)
                {
                    if ((Main.tile[num24, num27 - 1].type == 147 || Main.tile[num24, num27 - 1].type == 161) && genRand.Next(5) == 0)
                    {
                        if (!Main.tile[num24, num27].active() && !Main.tile[num24, num27 + 1].active())
{
                            Main.tile[num24, num27 - 1].slope(0);
                        }
                        PlaceTight(num24, num27);
                    }
                    if ((Main.tile[num24, num27 - 1].type == 25 || Main.tile[num24, num27 - 1].type == 203) && genRand.Next(5) == 0)
                    {
                        if (!Main.tile[num24, num27].active() && !Main.tile[num24, num27 + 1].active())
{
                            Main.tile[num24, num27 - 1].slope(0);
                        }
                        PlaceTight(num24, num27);
                    }
                    if ((Main.tile[num24, num27 + 1].type == 25 || Main.tile[num24, num27 + 1].type == 203) && genRand.Next(5) == 0)
                    {
                        if (!Main.tile[num24, num27].active() && !Main.tile[num24, num27 - 1].active())
{
                            Main.tile[num24, num27 + 1].slope(0);
                        }
                        PlaceTight(num24, num27);
                    }
                }
            }
        });
        AddGenerationPass("Remove Broken Traps", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            if (!noTrapsWorldGen || tenthAnniversaryWorldGen || notTheBees)
            {
                progress.Message = Lang.gen[82].Value;
                List<Point> list = new List<Point>();
                int num21 = 50;
                for (int num22 = num21; num22 < Main.maxTilesX - num21; num22++)
                {
                    double value = (double)(num22 - num21) / (double)(Main.maxTilesX - num21 * 2);
                    progress.Set(value);
                    for (int num23 = 50; num23 < Main.maxTilesY - 50; num23++)
                    {
                        if (Main.tile[num22, num23].wire() && !list.Contains(new Point(num22, num23)))
{
                            ClearBrokenTraps(new Point(num22, num23), list);
                        }
                    }
                }
            }
        });
        AddGenerationPass("Final Cleanup", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            Main.tileSolid[484] = false;
            FillWallHolesInArea(new Rectangle(0, 0, Main.maxTilesX, (int)Main.worldSurface));
            progress.Message = Lang.gen[86].Value;
            for (int i = 0; i < Main.maxTilesX; i++)
            {
                progress.Set((double)i / (double)Main.maxTilesX);
                for (int j = 0; j < Main.maxTilesY; j++)
                {
                    if (Main.tile[i, j].active() && !SolidTile(i, j + 1) && (Main.tile[i, j].type == 53 || Main.tile[i, j].type == 112 || Main.tile[i, j].type == 234 || Main.tile[i, j].type == 224 || Main.tile[i, j].type == 123))
                    {
                        if ((double)j < Main.worldSurface + 10.0 && !Main.tile[i, j + 1].active() && Main.tile[i, j + 1].wall != 191 && !oceanDepths(i, j))
{
                            int num = 10;
                            int num2 = j + 1;
                            for (int k = num2; k < num2 + 10; k++)
{
                                if (Main.tile[i, k].active() && Main.tile[i, k].type == 314)
{
                                    num = 0;
                                    break;
                                }
                            }
                            while (!Main.tile[i, num2].active() && num > 0 && num2 < Main.maxTilesY - 50)
{
                                Main.tile[i, num2 - 1].slope(0);
                                Main.tile[i, num2 - 1].halfBrick(halfBrick: false);
                                Main.tile[i, num2].active(active: true);
                                Main.tile[i, num2].type = Main.tile[i, j].type;
                                Main.tile[i, num2].slope(0);
                                Main.tile[i, num2].halfBrick(halfBrick: false);
                                num2++;
                                num--;
                            }
                            if (num == 0 && !Main.tile[i, num2].active())
{
                                switch (Main.tile[i, j].type)
{
                                case 53:
                                    Main.tile[i, num2].type = 397;
                                    Main.tile[i, num2].active(active: true);
                                    break;
                                case 112:
                                    Main.tile[i, num2].type = 398;
                                    Main.tile[i, num2].active(active: true);
                                    break;
                                case 234:
                                    Main.tile[i, num2].type = 399;
                                    Main.tile[i, num2].active(active: true);
                                    break;
                                case 224:
                                    Main.tile[i, num2].type = 147;
                                    Main.tile[i, num2].active(active: true);
                                    break;
                                case 123:
                                    Main.tile[i, num2].type = 1;
                                    Main.tile[i, num2].active(active: true);
                                    break;
                                }
                            }
                            else if (Main.tile[i, num2].active() && Main.tileSolid[Main.tile[i, num2].type] && !Main.tileSolidTop[Main.tile[i, num2].type])
{
                                Main.tile[i, num2].slope(0);
                                Main.tile[i, num2].halfBrick(halfBrick: false);
                            }
                        }
                        else if (Main.tileSolid[Main.tile[i, j + 1].type] && !Main.tileSolidTop[Main.tile[i, j + 1].type] && (Main.tile[i, j + 1].topSlope() || Main.tile[i, j + 1].halfBrick()))
{
                            Main.tile[i, j + 1].slope(0);
                            Main.tile[i, j + 1].halfBrick(halfBrick: false);
                        }
                        else
{
                            switch (Main.tile[i, j].type)
{
                            case 53:
                                Main.tile[i, j].type = 397;
                                break;
                            case 112:
                                Main.tile[i, j].type = 398;
                                break;
                            case 234:
                                Main.tile[i, j].type = 399;
                                break;
                            case 224:
                                Main.tile[i, j].type = 147;
                                break;
                            case 123:
                                Main.tile[i, j].type = 1;
                                break;
                            }
                        }
                        if (Main.tile[i, j - 1].type == 323)
{
                            TileFrame(i, j - 1);
                        }
                    }
                    if ((Main.tile[i, j].wall == 187 || Main.tile[i, j].wall == 216) && Main.tile[i, j].liquid > 0 && !remixWorldGen)
                    {
                        Main.tile[i, j].liquid = byte.MaxValue;
                        Main.tile[i, j].lava(lava: true);
                    }
                    if (Main.tile[i, j].type == 485 || Main.tile[i, j].type == 187 || Main.tile[i, j].type == 165)
                    {
                        TileFrame(i, j);
                    }
                    if (Main.tile[i, j].type == 28)
                    {
                        TileFrame(i, j);
                    }
                    if (Main.tile[i, j].type == 10 || Main.tile[i, j].type == 11)
                    {
                        TileFrame(i, j);
                    }
                    if (Main.tile[i, j].type == 26)
                    {
                        TileFrame(i, j);
                    }
                    if (TileID.Sets.IsATreeTrunk[Main.tile[i, j].type] || Main.tile[i, j].type == 323)
                    {
                        TileFrame(i, j);
                    }
                    if (Main.tile[i, j].type == 137)
                    {
                        Main.tile[i, j].slope(0);
                        Main.tile[i, j].halfBrick(halfBrick: false);
                    }
                    if (Main.tile[i, j].active() && TileID.Sets.Boulders[Main.tile[i, j].type])
                    {
                        int num3 = Main.tile[i, j].frameX / 18;
                        int num4 = i;
                        num4 -= num3;
                        int num5 = Main.tile[i, j].frameY / 18;
                        int num6 = j;
                        num6 -= num5;
                        bool flag = false;
                        for (int l = 0; l < 2; l++)
{
                            Tile tile = Main.tile[num4 + l, num6 - 1];
                            if (tile != null && tile.active() && tile.type == 26)
{
                                flag = true;
                                break;
                            }
                            for (int m = 0; m < 2; m++)
{
                                int num7 = num4 + l;
                                int num8 = num6 + m;
                                Main.tile[num7, num8].active(active: true);
                                Main.tile[num7, num8].slope(0);
                                Main.tile[num7, num8].halfBrick(halfBrick: false);
                                Main.tile[num7, num8].type = Main.tile[i, j].type;
                                Main.tile[num7, num8].frameX = (short)(l * 18);
                                Main.tile[num7, num8].frameY = (short)(m * 18);
                            }
                        }
                        if (flag)
{
                            ushort type = 0;
                            if (Main.tile[i, j].type == 484)
{
                                type = 397;
                            }
                            for (int n = 0; n < 2; n++)
{
                                for (int num9 = 0; num9 < 2; num9++)
{
                                    int num10 = num4 + n;
                                    int num11 = num6 + num9;
                                    Main.tile[num10, num11].active(active: true);
                                    Main.tile[num10, num11].slope(0);
                                    Main.tile[num10, num11].halfBrick(halfBrick: false);
                                    Main.tile[num10, num11].type = type;
                                    Main.tile[num10, num11].frameX = 0;
                                    Main.tile[num10, num11].frameY = 0;
                                }
                            }
                        }
                    }
                    if (Main.tile[i, j].type == 323 && Main.tile[i, j].liquid > 0)
                    {
                        KillTile(i, j);
                    }
                    if (Main.wallDungeon[Main.tile[i, j].wall])
                    {
                        Main.tile[i, j].lava(lava: false);
                        if (Main.tile[i, j].active() && Main.tile[i, j].type == 56)
{
                            KillTile(i, j);
                            Main.tile[i, j].lava(lava: false);
                            Main.tile[i, j].liquid = byte.MaxValue;
                        }
                    }
                    if (Main.tile[i, j].active() && Main.tile[i, j].type == 314)
                    {
                        int num12 = 15;
                        int num13 = 1;
                        int num14 = j;
                        while (j - num14 < num12)
{
                            Main.tile[i, num14].liquid = 0;
                            num14--;
                        }
                        for (num14 = j; num14 - j < num13; num14++)
{
                            Main.tile[i, num14].liquid = 0;
                        }
                    }
                    if (Main.tile[i, j].active() && Main.tile[i, j].type == 332 && !Main.tile[i, j + 1].active())
                    {
                        Main.tile[i, j + 1].ClearEverything();
                        Main.tile[i, j + 1].active(active: true);
                        Main.tile[i, j + 1].type = 332;
                    }
                    if (i > beachDistance && i < Main.maxTilesX - beachDistance && (double)j < Main.worldSurface && Main.tile[i, j].liquid > 0 && Main.tile[i, j].liquid < byte.MaxValue && Main.tile[i - 1, j].liquid < byte.MaxValue && Main.tile[i + 1, j].liquid < byte.MaxValue && Main.tile[i, j + 1].liquid < byte.MaxValue && !TileID.Sets.Clouds[Main.tile[i - 1, j].type] && !TileID.Sets.Clouds[Main.tile[i + 1, j].type] && !TileID.Sets.Clouds[Main.tile[i, j + 1].type])
                    {
                        Main.tile[i, j].liquid = 0;
                    }
                }
            }
            int num15 = 0;
            int num16 = 3;
            num16 = GetWorldSize() switch
            {
                1 => 6,
                2 => 9,
                _ => 3,
            };
            if (tenthAnniversaryWorldGen)
            {
                num16 *= 5;
            }
            int num17 = 50;
            int minValue = num17;
            int minValue2 = num17;
            int maxValue = Main.maxTilesX - num17;
            int maxValue2 = Main.maxTilesY - 200;
            int num18 = 3000;
            while (num15 < num16)
            {
                num18--;
                if (num18 <= 0)
                {
                    break;
                }
                int num19 = genRand.Next(minValue, maxValue);
                int num20 = genRand.Next(minValue2, maxValue2);
                Tile tile2 = Main.tile[num19, num20];
                if (tile2.active() && tile2.type >= 0 && tile2.type < TileID.Count)
                {
                    bool flag2 = TileID.Sets.Dirt[tile2.type];
                    if (notTheBees)
                    {
                        flag2 = flag2 || TileID.Sets.Mud[tile2.type];
                    }
                    if (flag2)
                    {
                        num15++;
                        tile2.ClearTile();
                        tile2.active(active: true);
                        tile2.type = 668;
                    }
                }
            }
            if (noTrapsWorldGen)
            {
                FinishNoTraps();
            }
            if (Main.tenthAnniversaryWorld)
            {
                FinishTenthAnniversaryWorld();
            }
            if (drunkWorldGen)
            {
                FinishDrunkGen();
            }
            if (notTheBees)
            {
                NotTheBees();
                FinishNotTheBees();
            }
            if (getGoodWorldGen)
            {
                FinishGetGoodWorld();
            }
            if (remixWorldGen)
            {
                FinishRemixWorld();
            }
            ShimmerCleanUp();
            notTheBees = false;
            getGoodWorldGen = false;
            noTileActions = false;
            Main.tileSolid[659] = true;
            Main.tileSolid[GenVars.crackedType] = true;
            Main.tileSolid[484] = true;
            gen = false;
            Main.AnglerQuestSwap();
            skipFramingDuringGen = false;
            progress.Message = Lang.gen[87].Value;
        });
        _generator.GenerateWorld(customProgressObject);
        ConsumePostGenActions(GenVars.structures);
        Main.WorldFileMetadata = FileMetadata.FromCurrentSettings(FileType.World);
        Main.NotifyOfEvent(GameNotificationType.WorldGen);
        drunkWorldGenText = false;
    }
References Terraria.WorldGen._generator, Terraria.WorldGen._genRand, Terraria.WorldGen._lastSeed, System.Math.Abs(), System.Collections.Generic.Dictionary< TKey, TValue >.Add(), Terraria.WorldGen.AddGenerationPass(), Terraria.WorldGen.AddHellHouses(), System.array, Terraria.WorldGen.beachDistance, Terraria.WorldBuilding.GenVars.beachSandDungeonExtraWidth, Terraria.WorldBuilding.GenVars.beachSandJungleExtraWidth, Terraria.WorldBuilding.GenVars.beachSandRandomCenter, Terraria.WorldBuilding.GenVars.beachSandRandomWidthRange, Terraria.GameContent.Biomes.GraniteBiome.CanPlace(), Terraria.WorldGen.CaveOpenater(), Terraria.WorldGen.Caverer(), Terraria.WorldGen.Cavinator(), Terraria.WorldGen.ChasmRunner(), Terraria.Main.checkHalloween(), Terraria.Main.checkXMas(), Terraria.WorldGen.CloudIsland(), Terraria.WorldGen.CloudLake(), Terraria.WorldBuilding.GenVars.configuration, Terraria.WorldBuilding.GenVars.copper, System.Collections.Generic.Dictionary< TKey, TValue >.Count, Terraria.WorldGen.CrimPlaceHearts(), Terraria.WorldGen.crimson, Terraria.WorldBuilding.GenVars.crimsonLeft, Terraria.WorldGen.CrimStart(), Terraria.Main.dayTime, Terraria.WorldGen.DesertCloudIsland(), ReLogic.Utilities.Vector2D.Distance(), Terraria.WorldGen.dontStarveWorldGen, Terraria.WorldGen.drunkWorldGen, Terraria.WorldGen.drunkWorldGenText, Terraria.WorldBuilding.GenVars.dungeonLocation, Terraria.WorldBuilding.GenVars.dungeonSide, System.E, Microsoft.Xna.Framework.Rectangle.Empty, Terraria.WorldGen.everythingWorldGen, Terraria.WorldBuilding.GenVars.evilBiomeAvoidanceMidFixer, Terraria.WorldBuilding.GenVars.evilBiomeBeachAvoidance, Terraria.Main.expertMode, Terraria.WorldBuilding.GenVars.floatingIslandHouseX, Terraria.WorldBuilding.GenVars.floatingIslandHouseY, Terraria.WorldBuilding.GenVars.floatingIslandStyle, Terraria.WorldBuilding.WorldGenConfiguration.FromEmbeddedPath(), Terraria.Lang.gen, Terraria.WorldGen.gen, Terraria.WorldGen.genRand, Terraria.WorldGen.getGoodWorldGen, Terraria.Localization.Language.GetTextValue(), Terraria.WorldBuilding.GenVars.gold, Terraria.WorldGen.grassSpread, Terraria.WorldGen.growGrassUnderground, Terraria.WorldGen.heartCount, System.index, Terraria.WorldGen.InWorld(), Terraria.WorldBuilding.GenVars.iron, Terraria.WorldGen.IsTileNearby(), System.item, Terraria.WorldBuilding.GenVars.jungleHut, Terraria.WorldBuilding.GenVars.jungleOriginX, Terraria.WorldGen.KillTile(), Terraria.WorldBuilding.GenVars.lakesBeachAvoidance, Terraria.WorldBuilding.GenVars.LakeX, Terraria.WorldBuilding.GenVars.lavaLine, Terraria.WorldBuilding.GenVars.leftBeachEnd, Terraria.WorldGen.MakeDungeon(), Terraria.WorldBuilding.GenVars.maxLakes, Terraria.WorldBuilding.GenVars.maxMushroomBiomes, Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.WorldBuilding.GenVars.maxTunnels, Terraria.WorldBuilding.GenVars.mCaveX, Terraria.WorldBuilding.GenVars.mCaveY, System.Math.Min(), Terraria.WorldGen.Mountinater(), Terraria.WorldBuilding.GenVars.mushroomBiomesPosition, Terraria.WorldGen.noTileActions, Terraria.WorldGen.noTrapsWorldGen, Terraria.WorldGen.notTheBees, Terraria.WorldGen.NotTheBees(), Terraria.WorldBuilding.GenVars.numIslandHouses, Terraria.WorldBuilding.GenVars.numLakes, Terraria.WorldBuilding.GenVars.numMCaves, Terraria.WorldBuilding.GenVars.numMushroomBiomes, Terraria.WorldBuilding.GenVars.numOceanCaveTreasure, Terraria.WorldBuilding.GenVars.numPyr, Terraria.WorldBuilding.GenVars.numTunnels, Terraria.WorldGen.oceanDepths(), Terraria.WorldBuilding.GenVars.oceanWaterForcedJungleLength, Terraria.WorldBuilding.GenVars.oceanWaterStartRandomMax, Terraria.WorldBuilding.GenVars.oceanWaterStartRandomMin, Terraria.WorldGen.Place3x2(), Terraria.WorldGen.PlaceTile(), Terraria.WorldGen.Hooks.ProcessWorldGenConfig(), Terraria.WorldBuilding.GenVars.PyrX, Terraria.WorldBuilding.GenVars.PyrY, Terraria.Liquid.QuickWater(), Terraria.Main.rand, Terraria.WorldGen.RandomizeBackgrounds(), Terraria.WorldGen.RandomizeCaveBackgrounds(), Terraria.WorldGen.RandomizeMoonState(), Terraria.WorldGen.RandomizeTreeStyle(), Terraria.WorldGen.RandomizeWeather(), Terraria.WorldGen.RandomRectanglePoint(), Terraria.WorldGen.RandomWorldPoint(), Terraria.Liquid.ReInit(), Terraria.Main.remixWorld, Terraria.WorldGen.remixWorldGen, Terraria.WorldGen.ResetGenerator(), Terraria.WorldBuilding.GenVars.rightBeachStart, Terraria.WorldBuilding.GenVars.rockLayer, Terraria.Main.rockLayer, Terraria.WorldBuilding.GenVars.rockLayerHigh, Terraria.WorldBuilding.GenVars.rockLayerLow, Terraria.WorldGen.ScanTileColumnAndRemoveClumps(), Terraria.WorldGen.SetupStatueList(), Terraria.WorldBuilding.GenVars.shellStartXLeft, Terraria.WorldBuilding.GenVars.shellStartXRight, Terraria.WorldGen.ShroomPatch(), Terraria.WorldBuilding.GenVars.silver, Terraria.WorldGen.skipFramingDuringGen, Terraria.WorldBuilding.GenVars.skyLake, Terraria.WorldBuilding.GenVars.skyLakes, Terraria.WorldGen.SmallConsecutivesEliminated, Terraria.WorldGen.SmallConsecutivesFound, Terraria.WorldBuilding.GenVars.smallHolesBeachAvoidance, Terraria.WorldBuilding.GenVars.snowBottom, Terraria.WorldGen.SnowCloudIsland(), Terraria.WorldBuilding.GenVars.snowMaxX, Terraria.WorldBuilding.GenVars.snowMinX, Terraria.WorldBuilding.GenVars.snowOriginLeft, Terraria.WorldBuilding.GenVars.snowOriginRight, Terraria.WorldBuilding.GenVars.snowTop, Terraria.Enums.SolidTile, Terraria.WorldGen.SonOfLakinater(), Terraria.WorldGen.SpreadGrass(), Terraria.WorldBuilding.GenVars.structures, Terraria.WorldBuilding.GenVars.surfaceCavesBeachAvoidance2, Terraria.WorldGen.tempRemixWorldGen, Terraria.WorldGen.tempTenthAnniversaryWorldGen, Terraria.Main.tenthAnniversaryWorld, Terraria.WorldGen.tenthAnniversaryWorldGen, Terraria.DataStructures.Tile, Terraria.Main.tile, Terraria.WorldGen.TileRunner(), Terraria.Main.tileSolid, Terraria.WorldGen.TreeTops, Terraria.WorldGen.TryGrowingTreeByType(), Terraria.WorldGen.TuneOceanDepth(), Terraria.WorldBuilding.GenVars.tunnelX, Terraria.WorldBuilding.GenVars.UndergroundDesertLocation, Terraria.WorldGen.WavyCaverer(), Terraria.WorldGen.WorldGenParam_Evil, Terraria.WorldBuilding.GenVars.worldSurface, Terraria.Main.worldSurface, Terraria.WorldBuilding.GenVars.worldSurfaceHigh, Terraria.WorldBuilding.GenVars.worldSurfaceLow, System.Console.WriteLine(), and Microsoft.Xna.Framework.Point.Zero.
Referenced by Terraria.WorldBuilding.WorldUtils.DebugRegen(), Terraria.Main.Initialize_AlmostEverything(), Terraria.IO.WorldFile.LoadWorld(), and Terraria.WorldGen.worldGenCallback().