Terraria: Terraria.WorldGen.SolidTile
SolidTile() [1/3]
static bool Terraria.WorldGen.SolidTile (int i, int j, bool noDoors = false) inline static
    {
        try
        {
            if (Main.tile[i, j] == null)
            {
                return true;
            }
            if (Main.tile[i, j].active() && Main.tileSolid[Main.tile[i, j].type] && !Main.tileSolidTop[Main.tile[i, j].type] && !Main.tile[i, j].halfBrick() && Main.tile[i, j].slope() == 0 && !Main.tile[i, j].inActive())
            {
                if (noDoors && Main.tile[i, j].type == 10)
                {
                    return false;
                }
                return true;
            }
        }
        catch
        {
        }
        return false;
    }
References Terraria.Tile.active(), Terraria.Tile.halfBrick(), Terraria.Tile.inActive(), Terraria.Tile.slope(), Terraria.Main.tile, Terraria.Main.tileSolid, Terraria.Main.tileSolidTop, and Terraria.Tile.type.