Terraria: Terraria.WorldGen.TryKillingTreesAboveIfTheyWouldBecomeInvalid
TryKillingTreesAboveIfTheyWouldBecomeInvalid()
static bool Terraria.WorldGen.TryKillingTreesAboveIfTheyWouldBecomeInvalid (int i, int j, int newFloorType) inline static
Definition at line 46823 of file WorldGen.cs.
    {
        if (newFloorType < 0 || newFloorType >= TileID.Count)
        {
            return false;
        }
        if (!InWorld(i, j, 2))
        {
            return false;
        }
        Tile tile = Main.tile[i, j - 1];
        if (tile == null || !tile.active())
        {
            return false;
        }
        int type = tile.type;
        if (!IsTreeType(tile.type) && tile.type != 323)
        {
            return false;
        }
        bool flag = true;
        flag = type switch
        {
            72 => newFloorType == 70,
            323 => TileID.Sets.Conversion.Sand[newFloorType],
            _ => TileID.Sets.Conversion.Grass[newFloorType] || TileID.Sets.Conversion.JungleGrass[newFloorType] || TileID.Sets.Conversion.Snow[newFloorType],
        };
        if (flag && GrowTreeSettings.Profiles.TryGetFromTreeId(type, out var profile))
        {
            flag = profile.GroundTest(newFloorType);
        }
        if (!flag)
        {
            KillTile(i, j - 1);
            if (Main.netMode == 1)
            {
                NetMessage.SendData(17, -1, -1, null, 0, i, j - 1);
            }
        }
        return true;
    }
References Terraria.Tile.active(), Terraria.ID.TileID.Count, Terraria.ID.TileID.Sets.Conversion.Grass, Terraria.ID.TileID.Sets.Conversion.JungleGrass, Terraria.Main.netMode, Terraria.ID.TileID.Sets.Conversion.Sand, Terraria.NetMessage.SendData(), Terraria.ID.TileID.Sets.Conversion.Snow, Terraria.Main.tile, Terraria.WorldGen.GrowTreeSettings.Profiles.TryGetFromTreeId(), System.type, and Terraria.Tile.type.