Terraria: Terraria.WorldGen.SnowCloudIsland
SnowCloudIsland()
static void Terraria.WorldGen.SnowCloudIsland (int i, int j) inline static
Definition at line 67343 of file WorldGen.cs.
    {
        //IL_0089: Unknown result type (might be due to invalid IL or missing references)
        //IL_009a: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ef: Unknown result type (might be due to invalid IL or missing references)
        //IL_0104: Unknown result type (might be due to invalid IL or missing references)
        //IL_011a: Unknown result type (might be due to invalid IL or missing references)
        //IL_012f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0563: Unknown result type (might be due to invalid IL or missing references)
        //IL_0574: Unknown result type (might be due to invalid IL or missing references)
        //IL_018f: Unknown result type (might be due to invalid IL or missing references)
        //IL_05c9: Unknown result type (might be due to invalid IL or missing references)
        //IL_05de: Unknown result type (might be due to invalid IL or missing references)
        //IL_05f9: Unknown result type (might be due to invalid IL or missing references)
        //IL_02d3: Unknown result type (might be due to invalid IL or missing references)
        //IL_02d4: Unknown result type (might be due to invalid IL or missing references)
        //IL_02d5: Unknown result type (might be due to invalid IL or missing references)
        //IL_02da: Unknown result type (might be due to invalid IL or missing references)
        //IL_02ff: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ca: Unknown result type (might be due to invalid IL or missing references)
        //IL_0320: Unknown result type (might be due to invalid IL or missing references)
        //IL_01dc: Unknown result type (might be due to invalid IL or missing references)
        //IL_01d2: Unknown result type (might be due to invalid IL or missing references)
        //IL_0341: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ee: Unknown result type (might be due to invalid IL or missing references)
        //IL_0362: Unknown result type (might be due to invalid IL or missing references)
        //IL_0659: Unknown result type (might be due to invalid IL or missing references)
        //IL_077b: Unknown result type (might be due to invalid IL or missing references)
        //IL_077c: Unknown result type (might be due to invalid IL or missing references)
        //IL_077d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0782: Unknown result type (might be due to invalid IL or missing references)
        //IL_07a7: Unknown result type (might be due to invalid IL or missing references)
        //IL_0215: Unknown result type (might be due to invalid IL or missing references)
        //IL_0224: Unknown result type (might be due to invalid IL or missing references)
        //IL_0694: Unknown result type (might be due to invalid IL or missing references)
        //IL_07c8: Unknown result type (might be due to invalid IL or missing references)
        //IL_06a6: Unknown result type (might be due to invalid IL or missing references)
        //IL_069c: Unknown result type (might be due to invalid IL or missing references)
        //IL_07e9: Unknown result type (might be due to invalid IL or missing references)
        //IL_06b8: Unknown result type (might be due to invalid IL or missing references)
        //IL_080a: Unknown result type (might be due to invalid IL or missing references)
        //IL_06df: Unknown result type (might be due to invalid IL or missing references)
        //IL_06ee: Unknown result type (might be due to invalid IL or missing references)
        double num = genRand.Next(100, 150);
        double num2 = num;
        double num3 = genRand.Next(20, 30);
        int num4 = i;
        int num5 = i;
        int num6 = i;
        int num7 = j;
        Vector2D val = default(Vector2D);
        val.X = i;
        val.Y = j;
        Vector2D val2 = default(Vector2D);
        val2.X = (double)genRand.Next(-20, 21) * 0.2;
        while (val2.X > -2.0 && val2.X < 2.0)
        {
            val2.X = (double)genRand.Next(-20, 21) * 0.2;
        }
        val2.Y = (double)genRand.Next(-20, -10) * 0.02;
        while (num > 0.0 && num3 > 0.0)
        {
            num -= (double)genRand.Next(4);
            num3 -= 1.0;
            int num8 = (int)(val.X - num * 0.5);
            int num9 = (int)(val.X + num * 0.5);
            int num10 = (int)(val.Y - num * 0.5);
            int num11 = (int)(val.Y + num * 0.5);
            if (num8 < 0)
            {
                num8 = 0;
            }
            if (num9 > Main.maxTilesX)
            {
                num9 = Main.maxTilesX;
            }
            if (num10 < 0)
            {
                num10 = 0;
            }
            if (num11 > Main.maxTilesY)
            {
                num11 = Main.maxTilesY;
            }
            num2 = num * (double)genRand.Next(80, 120) * 0.01;
            double num12 = val.Y + 1.0;
            for (int k = num8; k < num9; k++)
            {
                if (genRand.Next(2) == 0)
                {
                    num12 += (double)genRand.Next(-1, 2);
                }
                if (num12 < val.Y)
                {
                    num12 = val.Y;
                }
                if (num12 > val.Y + 2.0)
                {
                    num12 = val.Y + 2.0;
                }
                for (int l = num10; l < num11; l++)
                {
                    if (!((double)l > num12))
                    {
                        continue;
                    }
                    double num13 = Math.Abs((double)k - val.X);
                    double num14 = Math.Abs((double)l - val.Y) * 3.0;
                    if (Math.Sqrt(num13 * num13 + num14 * num14) < num2 * 0.4)
                    {
                        if (k < num4)
{
                            num4 = k;
                        }
                        if (k > num5)
{
                            num5 = k;
                        }
                        if (l < num6)
{
                            num6 = l;
                        }
                        if (l > num7)
{
                            num7 = l;
                        }
                        Main.tile[k, l].active(active: true);
                        Main.tile[k, l].type = 189;
                        SquareTileFrame(k, l);
                    }
                }
            }
            val += val2;
            val2.X += (double)genRand.Next(-20, 21) * 0.05;
            if (val2.X > 1.0)
            {
                val2.X = 1.0;
            }
            if (val2.X < -1.0)
            {
                val2.X = -1.0;
            }
            if (val2.Y > 0.2)
            {
                val2.Y = -0.2;
            }
            if (val2.Y < -0.2)
            {
                val2.Y = -0.2;
            }
        }
        int num15 = num4;
        int num17;
        for (num15 += genRand.Next(5); num15 < num5; num15 += genRand.Next(num17, (int)((double)num17 * 1.5)))
        {
            int num16 = num7;
            while (!Main.tile[num15, num16].active())
            {
                num16--;
            }
            num16 += genRand.Next(-3, 4);
            num17 = genRand.Next(4, 8);
            int num18 = 189;
            if (genRand.Next(4) == 0)
            {
                num18 = 460;
            }
            for (int m = num15 - num17; m <= num15 + num17; m++)
            {
                for (int n = num16 - num17; n <= num16 + num17; n++)
                {
                    if (n > num6)
                    {
                        double num19 = Math.Abs(m - num15);
                        double num20 = Math.Abs(n - num16) * 2;
                        if (Math.Sqrt(num19 * num19 + num20 * num20) < (double)(num17 + genRand.Next(2)))
{
                            Main.tile[m, n].active(active: true);
                            Main.tile[m, n].type = (ushort)num18;
                            SquareTileFrame(m, n);
                        }
                    }
                }
            }
        }
        num = genRand.Next(80, 95);
        num2 = num;
        num3 = genRand.Next(10, 15);
        val.X = i;
        val.Y = num6;
        val2.X = (double)genRand.Next(-20, 21) * 0.2;
        while (val2.X > -2.0 && val2.X < 2.0)
        {
            val2.X = (double)genRand.Next(-20, 21) * 0.2;
        }
        val2.Y = (double)genRand.Next(-20, -10) * 0.02;
        while (num > 0.0 && num3 > 0.0)
        {
            num -= (double)genRand.Next(4);
            num3 -= 1.0;
            int num8 = (int)(val.X - num * 0.5);
            int num9 = (int)(val.X + num * 0.5);
            int num10 = num6 - 1;
            int num11 = (int)(val.Y + num * 0.5);
            if (num8 < 0)
            {
                num8 = 0;
            }
            if (num9 > Main.maxTilesX)
            {
                num9 = Main.maxTilesX;
            }
            if (num10 < 0)
            {
                num10 = 0;
            }
            if (num11 > Main.maxTilesY)
            {
                num11 = Main.maxTilesY;
            }
            num2 = num * (double)genRand.Next(80, 120) * 0.01;
            double num21 = val.Y + 1.0;
            for (int num22 = num8; num22 < num9; num22++)
            {
                if (genRand.Next(2) == 0)
                {
                    num21 += (double)genRand.Next(-1, 2);
                }
                if (num21 < val.Y)
                {
                    num21 = val.Y;
                }
                if (num21 > val.Y + 2.0)
                {
                    num21 = val.Y + 2.0;
                }
                for (int num23 = num10; num23 < num11; num23++)
                {
                    if ((double)num23 > num21)
                    {
                        double num24 = Math.Abs((double)num22 - val.X);
                        double num25 = Math.Abs((double)num23 - val.Y) * 3.0;
                        if (Math.Sqrt(num24 * num24 + num25 * num25) < num2 * 0.4 && Main.tile[num22, num23].type == 189)
{
                            Main.tile[num22, num23].type = 147;
                            SquareTileFrame(num22, num23);
                        }
                    }
                }
            }
            val += val2;
            val2.X += (double)genRand.Next(-20, 21) * 0.05;
            if (val2.X > 1.0)
            {
                val2.X = 1.0;
            }
            if (val2.X < -1.0)
            {
                val2.X = -1.0;
            }
            if (val2.Y > 0.2)
            {
                val2.Y = -0.2;
            }
            if (val2.Y < -0.2)
            {
                val2.Y = -0.2;
            }
        }
        int num26 = num4;
        num26 += genRand.Next(5);
        while (num26 < num5)
        {
            int num27 = num7;
            while ((!Main.tile[num26, num27].active() || Main.tile[num26, num27].type != 0) && num26 < num5)
            {
                num27--;
                if (num27 < num6)
                {
                    num27 = num7;
                    num26 += genRand.Next(1, 4);
                }
            }
            if (num26 >= num5)
            {
                continue;
            }
            num27 += genRand.Next(0, 4);
            int num28 = genRand.Next(2, 5);
            int num29 = 189;
            for (int num30 = num26 - num28; num30 <= num26 + num28; num30++)
            {
                for (int num31 = num27 - num28; num31 <= num27 + num28; num31++)
                {
                    if (num31 > num6)
                    {
                        double num32 = Math.Abs(num30 - num26);
                        double num33 = Math.Abs(num31 - num27) * 2;
                        if (Math.Sqrt(num32 * num32 + num33 * num33) < (double)num28)
{
                            Main.tile[num30, num31].type = (ushort)num29;
                            SquareTileFrame(num30, num31);
                        }
                    }
                }
            }
            num26 += genRand.Next(num28, (int)((double)num28 * 1.5));
        }
        for (int num34 = num4 - 20; num34 <= num5 + 20; num34++)
        {
            for (int num35 = num6 - 20; num35 <= num7 + 20; num35++)
            {
                bool flag = true;
                for (int num36 = num34 - 1; num36 <= num34 + 1; num36++)
                {
                    for (int num37 = num35 - 1; num37 <= num35 + 1; num37++)
                    {
                        if (!Main.tile[num36, num37].active())
{
                            flag = false;
                        }
                    }
                }
                if (flag)
                {
                    Main.tile[num34, num35].wall = 73;
                    SquareWallFrame(num34, num35);
                }
            }
        }
        for (int num38 = num4; num38 <= num5; num38++)
        {
            int num39;
            for (num39 = num6 - 10; !Main.tile[num38, num39 + 1].active(); num39++)
            {
            }
            if (num39 >= num7 || Main.tile[num38, num39 + 1].type != 189)
            {
                continue;
            }
            if (genRand.Next(10) == 0)
            {
                int num40 = genRand.Next(1, 3);
                for (int num41 = num38 - num40; num41 <= num38 + num40; num41++)
                {
                    if (Main.tile[num41, num39].type == 189 && WillWaterPlacedHereStayPut(num41, num39))
                    {
                        Main.tile[num41, num39].active(active: false);
                        Main.tile[num41, num39].liquid = byte.MaxValue;
                        Main.tile[num41, num39].lava(lava: false);
                        SquareTileFrame(num38, num39);
                    }
                    if (Main.tile[num41, num39 + 1].type == 189 && WillWaterPlacedHereStayPut(num41, num39 + 1))
                    {
                        Main.tile[num41, num39 + 1].active(active: false);
                        Main.tile[num41, num39 + 1].liquid = byte.MaxValue;
                        Main.tile[num41, num39 + 1].lava(lava: false);
                        SquareTileFrame(num38, num39 + 1);
                    }
                    if (num41 > num38 - num40 && num41 < num38 + 2 && Main.tile[num41, num39 + 2].type == 189 && WillWaterPlacedHereStayPut(num41, num39 + 2))
                    {
                        Main.tile[num41, num39 + 2].active(active: false);
                        Main.tile[num41, num39 + 2].liquid = byte.MaxValue;
                        Main.tile[num41, num39 + 2].lava(lava: false);
                        SquareTileFrame(num38, num39 + 2);
                    }
                }
            }
            if (genRand.Next(5) == 0 && WillWaterPlacedHereStayPut(num38, num39))
            {
                Main.tile[num38, num39].liquid = byte.MaxValue;
            }
            Main.tile[num38, num39].lava(lava: false);
            SquareTileFrame(num38, num39);
        }
        int num42 = genRand.Next(4);
        for (int num43 = 0; num43 <= num42; num43++)
        {
            int num44 = genRand.Next(num4 - 5, num5 + 5);
            int num45 = num6 - genRand.Next(20, 40);
            int num46 = genRand.Next(4, 8);
            int num47 = 189;
            if (genRand.Next(2) == 0)
            {
                num47 = 460;
            }
            for (int num48 = num44 - num46; num48 <= num44 + num46; num48++)
            {
                for (int num49 = num45 - num46; num49 <= num45 + num46; num49++)
                {
                    double num50 = Math.Abs(num48 - num44);
                    double num51 = Math.Abs(num49 - num45) * 2;
                    if (Math.Sqrt(num50 * num50 + num51 * num51) < (double)(num46 + genRand.Next(-1, 2)))
                    {
                        Main.tile[num48, num49].active(active: true);
                        Main.tile[num48, num49].type = (ushort)num47;
                        SquareTileFrame(num48, num49);
                    }
                }
            }
            for (int num52 = num44 - num46 + 2; num52 <= num44 + num46 - 2; num52++)
            {
                int num53;
                for (num53 = num45 - num46; !Main.tile[num52, num53].active(); num53++)
                {
                }
                if (WillWaterPlacedHereStayPut(num52, num53))
                {
                    Main.tile[num52, num53].active(active: false);
                    Main.tile[num52, num53].liquid = byte.MaxValue;
                    SquareTileFrame(num52, num53);
                }
            }
        }
    }
References Terraria.Tile.active(), Terraria.Tile.lava(), Terraria.Tile.liquid, Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.Main.tile, Terraria.Tile.type, Terraria.Tile.wall, ReLogic.Utilities.Vector2D.X, and ReLogic.Utilities.Vector2D.Y.
Referenced by Terraria.WorldGen.GenerateWorld().