Terraria: System.Collections.Generic.SortedSet.ExceptWith
ExceptWith()
void System.Collections.Generic.SortedSet< T >.ExceptWith (IEnumerable< T > other) inline inherited
Implements System.Collections.Generic.ISet< T >.
Definition at line 1525 of file SortedSet.cs.
    {
        if (other == null)
        {
            throw new ArgumentNullException("other");
        }
        if (count == 0)
        {
            return;
        }
        if (other == this)
        {
            Clear();
        }
        else
        {
            if (other is SortedSet<T> sortedSet && HasEqualComparer(sortedSet))
            {
                if (comparer.Compare(sortedSet.Max, Min) < 0 || comparer.Compare(sortedSet.Min, Max) > 0)
                {
                    return;
                }
                T min = Min;
                T max = Max;
                {
                    foreach (T item in other)
                    {
                        if (comparer.Compare(item, min) >= 0)
{
                            if (comparer.Compare(item, max) > 0)
{
                                break;
                            }
                            Remove(item);
                        }
                    }
                    return;
                }
            }
            RemoveAllElements(other);
        }
    }
References System.Collections.Generic.SortedSet< T >.Clear(), System.Collections.Generic.IComparer< in T >.Compare(), System.Collections.Generic.SortedSet< T >.comparer, System.Collections.Generic.SortedSet< T >.count, System.Collections.Generic.SortedSet< T >.HasEqualComparer(), System.item, System.Collections.Generic.SortedSet< T >.Max, System.Collections.Generic.SortedSet< T >.Min, System.other, System.Collections.Generic.SortedSet< T >.Remove(), and System.Collections.Generic.SortedSet< T >.RemoveAllElements().