Terraria: System.Text.RegularExpressions.RegexInterpreter.Go
Go()
override void System.Text.RegularExpressions.RegexInterpreter.Go () inline protected
Definition at line 572 of file RegexInterpreter.cs.
    {
        SetOperator(_code.Codes[0]);
        _codepos = 0;
        int num = -1;
        while (true)
        {
            if (num >= 0)
            {
                Advance(num);
                num = -1;
            }
            CheckTimeout();
            switch (_operator)
            {
            case 40:
                return;
            case 38:
                Goto(Operand(0));
                continue;
            case 37:
                if (IsMatched(Operand(0)))
                {
                    num = 1;
                    continue;
                }
                break;
            case 23:
                TrackPush(runtextpos);
                num = 1;
                continue;
            case 151:
                TrackPop();
                runtextpos = TrackPeek();
                Goto(Operand(0));
                continue;
            case 31:
                StackPush(runtextpos);
                TrackPush();
                num = 0;
                continue;
            case 30:
                StackPush(-1);
                TrackPush();
                num = 0;
                continue;
            case 158:
            case 159:
                StackPop();
                break;
            case 33:
                StackPop();
                TrackPush(StackPeek());
                runtextpos = StackPeek();
                num = 0;
                continue;
            case 161:
                TrackPop();
                StackPush(TrackPeek());
                break;
            case 32:
                if (Operand(1) == -1 || IsMatched(Operand(1)))
                {
                    StackPop();
                    if (Operand(1) != -1)
                    {
                        TransferCapture(Operand(0), Operand(1), StackPeek(), runtextpos);
                    }
                    else
                    {
                        Capture(Operand(0), StackPeek(), runtextpos);
                    }
                    TrackPush(StackPeek());
                    num = 2;
                    continue;
                }
                break;
            case 160:
                TrackPop();
                StackPush(TrackPeek());
                Uncapture();
                if (Operand(0) != -1 && Operand(1) != -1)
                {
                    Uncapture();
                }
                break;
            case 24:
                StackPop();
                if (runtextpos != StackPeek())
                {
                    TrackPush(StackPeek(), runtextpos);
                    StackPush(runtextpos);
                    Goto(Operand(0));
                }
                else
                {
                    TrackPush2(StackPeek());
                    num = 1;
                }
                continue;
            case 152:
                TrackPop(2);
                StackPop();
                runtextpos = TrackPeek(1);
                TrackPush2(TrackPeek());
                num = 1;
                continue;
            case 280:
                TrackPop();
                StackPush(TrackPeek());
                break;
            case 25:
            {
                StackPop();
                int num26 = StackPeek();
                if (runtextpos != num26)
                {
                    if (num26 != -1)
                    {
                        TrackPush(num26, runtextpos);
                    }
                    else
                    {
                        TrackPush(runtextpos, runtextpos);
                    }
                }
                else
                {
                    StackPush(num26);
                    TrackPush2(StackPeek());
                }
                num = 1;
                continue;
            }
            case 153:
            {
                TrackPop(2);
                int i2 = TrackPeek(1);
                TrackPush2(TrackPeek());
                StackPush(i2);
                runtextpos = i2;
                Goto(Operand(0));
                continue;
            }
            case 281:
                StackPop();
                TrackPop();
                StackPush(TrackPeek());
                break;
            case 27:
                StackPush(runtextpos, Operand(0));
                TrackPush();
                num = 1;
                continue;
            case 26:
                StackPush(-1, Operand(0));
                TrackPush();
                num = 1;
                continue;
            case 154:
            case 155:
            case 162:
                StackPop(2);
                break;
            case 28:
            {
                StackPop(2);
                int num17 = StackPeek();
                int num18 = StackPeek(1);
                int num19 = runtextpos - num17;
                if (num18 >= Operand(1) || (num19 == 0 && num18 >= 0))
                {
                    TrackPush2(num17, num18);
                    num = 2;
                }
                else
                {
                    TrackPush(num17);
                    StackPush(runtextpos, num18 + 1);
                    Goto(Operand(0));
                }
                continue;
            }
            case 156:
                TrackPop();
                StackPop(2);
                if (StackPeek(1) > 0)
                {
                    runtextpos = StackPeek();
                    TrackPush2(TrackPeek(), StackPeek(1) - 1);
                    num = 2;
                    continue;
                }
                StackPush(TrackPeek(), StackPeek(1) - 1);
                break;
            case 284:
                TrackPop(2);
                StackPush(TrackPeek(), TrackPeek(1));
                break;
            case 29:
            {
                StackPop(2);
                int i = StackPeek();
                int num8 = StackPeek(1);
                if (num8 < 0)
                {
                    TrackPush2(i);
                    StackPush(runtextpos, num8 + 1);
                    Goto(Operand(0));
                }
                else
                {
                    TrackPush(i, num8, runtextpos);
                    num = 2;
                }
                continue;
            }
            case 157:
            {
                TrackPop(3);
                int num29 = TrackPeek();
                int num30 = TrackPeek(2);
                if (TrackPeek(1) < Operand(1) && num30 != num29)
                {
                    runtextpos = num30;
                    StackPush(num30, TrackPeek(1) + 1);
                    TrackPush2(num29);
                    Goto(Operand(0));
                    continue;
                }
                StackPush(TrackPeek(), TrackPeek(1));
                break;
            }
            case 285:
                TrackPop();
                StackPop(2);
                StackPush(TrackPeek(), StackPeek(1) - 1);
                break;
            case 34:
                StackPush(Trackpos(), Crawlpos());
                TrackPush();
                num = 0;
                continue;
            case 35:
                StackPop(2);
                Trackto(StackPeek());
                while (Crawlpos() != StackPeek(1))
                {
                    Uncapture();
                }
                break;
            case 36:
                StackPop(2);
                Trackto(StackPeek());
                TrackPush(StackPeek(1));
                num = 0;
                continue;
            case 164:
                TrackPop();
                while (Crawlpos() != TrackPeek())
                {
                    Uncapture();
                }
                break;
            case 14:
                if (Leftchars() <= 0 || runtext[runtextpos - 1] == '\n')
                {
                    num = 0;
                    continue;
                }
                break;
            case 15:
                if (Rightchars() <= 0 || runtext[runtextpos] == '\n')
                {
                    num = 0;
                    continue;
                }
                break;
            case 16:
                if (IsBoundary(runtextpos, runtextbeg, runtextend))
                {
                    num = 0;
                    continue;
                }
                break;
            case 17:
                if (!IsBoundary(runtextpos, runtextbeg, runtextend))
                {
                    num = 0;
                    continue;
                }
                break;
            case 41:
                if (IsECMABoundary(runtextpos, runtextbeg, runtextend))
                {
                    num = 0;
                    continue;
                }
                break;
            case 42:
                if (!IsECMABoundary(runtextpos, runtextbeg, runtextend))
                {
                    num = 0;
                    continue;
                }
                break;
            case 18:
                if (Leftchars() <= 0)
                {
                    num = 0;
                    continue;
                }
                break;
            case 19:
                if (runtextpos == runtextstart)
                {
                    num = 0;
                    continue;
                }
                break;
            case 20:
                if (Rightchars() <= 1 && (Rightchars() != 1 || runtext[runtextpos] == '\n'))
                {
                    num = 0;
                    continue;
                }
                break;
            case 21:
                if (Rightchars() <= 0)
                {
                    num = 0;
                    continue;
                }
                break;
            case 9:
                if (Forwardchars() >= 1 && Forwardcharnext() == (ushort)Operand(0))
                {
                    num = 1;
                    continue;
                }
                break;
            case 10:
                if (Forwardchars() >= 1 && Forwardcharnext() != (ushort)Operand(0))
                {
                    num = 1;
                    continue;
                }
                break;
            case 11:
                if (Forwardchars() >= 1)
                {
                    int num7 = Operand(0);
                    if (RegexCharClass.CharInClass(Forwardcharnext(), _code.Strings[num7], ref _code.StringsAsciiLookup[num7]))
                    {
                        num = 1;
                        continue;
                    }
                }
                break;
            case 12:
                if (MatchString(_code.Strings[Operand(0)]))
                {
                    num = 1;
                    continue;
                }
                break;
            case 13:
            {
                int cap = Operand(0);
                if (IsMatched(cap))
                {
                    if (!MatchRef(MatchIndex(cap), MatchLength(cap)))
                    {
                        break;
                    }
                }
                else if ((runregex.roptions & RegexOptions.ECMAScript) == 0)
                {
                    break;
                }
                num = 1;
                continue;
            }
            case 0:
            {
                int num28 = Operand(1);
                if (Forwardchars() < num28)
                {
                    break;
                }
                char c4 = (char)Operand(0);
                while (num28-- > 0)
                {
                    if (Forwardcharnext() != c4)
                    {
                        goto end_IL_0037;
                    }
                }
                num = 2;
                continue;
            }
            case 1:
            {
                int num27 = Operand(1);
                if (Forwardchars() < num27)
                {
                    break;
                }
                char c3 = (char)Operand(0);
                while (num27-- > 0)
                {
                    if (Forwardcharnext() == c3)
                    {
                        goto end_IL_0037;
                    }
                }
                num = 2;
                continue;
            }
            case 2:
            {
                int num24 = Operand(1);
                if (Forwardchars() < num24)
                {
                    break;
                }
                int num25 = Operand(0);
                string set2 = _code.Strings[num25];
                ref int[] asciiResultCache2 = ref _code.StringsAsciiLookup[num25];
                while (num24-- > 0)
                {
                    if ((uint)num24 % 2048u == 0)
                    {
                        CheckTimeout();
                    }
                    if (!RegexCharClass.CharInClass(Forwardcharnext(), set2, ref asciiResultCache2))
                    {
                        goto end_IL_0037;
                    }
                }
                num = 2;
                continue;
            }
            case 3:
            case 43:
            {
                int num22 = Math.Min(Operand(1), Forwardchars());
                char c2 = (char)Operand(0);
                int num23;
                for (num23 = num22; num23 > 0; num23--)
                {
                    if (Forwardcharnext() != c2)
                    {
                        Backwardnext();
                        break;
                    }
                }
                if (num22 > num23 && _operator == 3)
                {
                    TrackPush(num22 - num23 - 1, runtextpos - Bump());
                }
                num = 2;
                continue;
            }
            case 4:
            case 44:
            {
                int num20 = Math.Min(Operand(1), Forwardchars());
                char c = (char)Operand(0);
                int num21;
                if (!_rightToLeft && !_caseInsensitive)
                {
                    num21 = runtext.AsSpan(runtextpos, num20).IndexOf(c);
                    if (num21 == -1)
                    {
                        runtextpos += num20;
                        num21 = 0;
                    }
                    else
                    {
                        runtextpos += num21;
                        num21 = num20 - num21;
                    }
                }
                else
                {
                    for (num21 = num20; num21 > 0; num21--)
                    {
                        if (Forwardcharnext() == c)
{
                            Backwardnext();
                            break;
                        }
                    }
                }
                if (num20 > num21 && _operator == 4)
                {
                    TrackPush(num20 - num21 - 1, runtextpos - Bump());
                }
                num = 2;
                continue;
            }
            case 5:
            case 45:
            {
                int num14 = Math.Min(Operand(1), Forwardchars());
                int num15 = Operand(0);
                string set = _code.Strings[num15];
                ref int[] asciiResultCache = ref _code.StringsAsciiLookup[num15];
                int num16;
                for (num16 = num14; num16 > 0; num16--)
                {
                    if ((uint)num16 % 2048u == 0)
                    {
                        CheckTimeout();
                    }
                    if (!RegexCharClass.CharInClass(Forwardcharnext(), set, ref asciiResultCache))
                    {
                        Backwardnext();
                        break;
                    }
                }
                if (num14 > num16 && _operator == 5)
                {
                    TrackPush(num14 - num16 - 1, runtextpos - Bump());
                }
                num = 2;
                continue;
            }
            case 131:
            case 132:
            case 133:
            {
                TrackPop(2);
                int num12 = TrackPeek();
                int num13 = (runtextpos = TrackPeek(1));
                if (num12 > 0)
                {
                    TrackPush(num12 - 1, num13 - Bump());
                }
                num = 2;
                continue;
            }
            case 6:
            case 7:
            case 8:
            {
                int num11 = Math.Min(Operand(1), Forwardchars());
                if (num11 > 0)
                {
                    TrackPush(num11 - 1, runtextpos);
                }
                num = 2;
                continue;
            }
            case 134:
            {
                TrackPop(2);
                int num9 = (runtextpos = TrackPeek(1));
                if (Forwardcharnext() == (ushort)Operand(0))
                {
                    int num10 = TrackPeek();
                    if (num10 > 0)
                    {
                        TrackPush(num10 - 1, num9 + Bump());
                    }
                    num = 2;
                    continue;
                }
                break;
            }
            case 135:
            {
                TrackPop(2);
                int num5 = (runtextpos = TrackPeek(1));
                if (Forwardcharnext() != (ushort)Operand(0))
                {
                    int num6 = TrackPeek();
                    if (num6 > 0)
                    {
                        TrackPush(num6 - 1, num5 + Bump());
                    }
                    num = 2;
                    continue;
                }
                break;
            }
            case 136:
            {
                TrackPop(2);
                int num2 = (runtextpos = TrackPeek(1));
                int num3 = Operand(0);
                if (RegexCharClass.CharInClass(Forwardcharnext(), _code.Strings[num3], ref _code.StringsAsciiLookup[num3]))
                {
                    int num4 = TrackPeek();
                    if (num4 > 0)
                    {
                        TrackPush(num4 - 1, num2 + Bump());
                    }
                    num = 2;
                    continue;
                }
                break;
            }
            case 46:
                {
                    runtrack[runtrack.Length - 1] = runtextpos;
                    num = 0;
                    continue;
                }
                end_IL_0037:
                break;
            }
            Backtrack();
        }
    }
References System.Text.RegularExpressions.RegexInterpreter._caseInsensitive, System.Text.RegularExpressions.RegexInterpreter._code, System.Text.RegularExpressions.RegexInterpreter._codepos, System.Text.RegularExpressions.RegexInterpreter._operator, System.Text.RegularExpressions.RegexInterpreter._rightToLeft, System.Text.RegularExpressions.RegexInterpreter.Advance(), System.Text.RegularExpressions.RegexInterpreter.Backtrack(), System.Text.RegularExpressions.RegexInterpreter.Backwardnext(), System.Text.RegularExpressions.RegexInterpreter.Bump(), System.Text.RegularExpressions.RegexRunner.Capture(), System.Text.RegularExpressions.RegexCharClass.CharInClass(), System.Text.RegularExpressions.RegexRunner.CheckTimeout(), System.Text.RegularExpressions.RegexCode.Codes, System.Text.RegularExpressions.RegexRunner.Crawlpos(), System.Text.RegularExpressions.RegexInterpreter.Forwardcharnext(), System.Text.RegularExpressions.RegexInterpreter.Forwardchars(), System.Text.RegularExpressions.RegexInterpreter.Goto(), System.Text.RegularExpressions.i, System.Text.RegularExpressions.RegexRunner.IsBoundary(), System.Text.RegularExpressions.RegexRunner.IsECMABoundary(), System.Text.RegularExpressions.RegexRunner.IsMatched(), System.Text.RegularExpressions.RegexInterpreter.Leftchars(), System.Text.RegularExpressions.RegexRunner.MatchIndex(), System.Text.RegularExpressions.RegexRunner.MatchLength(), System.Text.RegularExpressions.RegexInterpreter.MatchRef(), System.Text.RegularExpressions.RegexInterpreter.MatchString(), System.Math.Min(), System.Text.RegularExpressions.RegexInterpreter.Operand(), System.Text.RegularExpressions.RegexInterpreter.Rightchars(), System.Text.RegularExpressions.Regex.roptions, System.Text.RegularExpressions.RegexRunner.runregex, System.Text.RegularExpressions.RegexRunner.runtext, System.Text.RegularExpressions.RegexRunner.runtextbeg, System.Text.RegularExpressions.RegexRunner.runtextend, System.Text.RegularExpressions.RegexRunner.runtextpos, System.Text.RegularExpressions.RegexRunner.runtextstart, System.Text.RegularExpressions.RegexRunner.runtrack, System.Text.RegularExpressions.RegexInterpreter.SetOperator(), System.Text.RegularExpressions.RegexInterpreter.StackPeek(), System.Text.RegularExpressions.RegexInterpreter.StackPop(), System.Text.RegularExpressions.RegexInterpreter.StackPush(), System.Text.RegularExpressions.RegexCode.Strings, System.Text.RegularExpressions.RegexCode.StringsAsciiLookup, System.Text.RegularExpressions.RegexInterpreter.TrackPeek(), System.Text.RegularExpressions.RegexInterpreter.TrackPop(), System.Text.RegularExpressions.RegexInterpreter.Trackpos(), System.Text.RegularExpressions.RegexInterpreter.TrackPush(), System.Text.RegularExpressions.RegexInterpreter.TrackPush2(), System.Text.RegularExpressions.RegexInterpreter.Trackto(), System.Text.RegularExpressions.RegexRunner.TransferCapture(), and System.Text.RegularExpressions.RegexRunner.Uncapture().