Terraria: System.Collections.Generic.SortedSet.SymmetricExceptWithSameComparer
SymmetricExceptWithSameComparer() [2/2]
void System.Collections.Generic.SortedSet< T >.SymmetricExceptWithSameComparer (T[] other, int count) inline private inherited
Definition at line 1603 of file SortedSet.cs.
    {
        if (count == 0)
        {
            return;
        }
        T y = other[0];
        for (int i = 0; i < count; i++)
        {
            for (; i < count && i != 0 && comparer.Compare(other[i], y) == 0; i++)
            {
            }
            if (i < count)
            {
                T val = other[i];
                bool flag = (Contains(val) ? Remove(val) : Add(val));
                y = val;
                continue;
            }
            break;
        }
    }
References System.Add, System.Collections.Generic.IComparer< in T >.Compare(), System.Collections.Generic.SortedSet< T >.comparer, System.Collections.Generic.SortedSet< T >.Contains(), System.Collections.Generic.SortedSet< T >.count, System.other, and System.Collections.Generic.SortedSet< T >.Remove().