Terraria: System.Collections.Generic.SortedSet.CheckUniqueAndUnfoundElements
CheckUniqueAndUnfoundElements()
ElementCount System.Collections.Generic.SortedSet< T >.CheckUniqueAndUnfoundElements (IEnumerable< T > other, bool returnIfUnfound) inline private inherited
Definition at line 1821 of file SortedSet.cs.
    {
        Unsafe.SkipInit(out ElementCount result);
        if (Count == 0)
        {
            int num = 0;
            using (IEnumerator<T> enumerator = other.GetEnumerator())
            {
                if (enumerator.MoveNext())
                {
                    T current = enumerator.Current;
                    num++;
                }
            }
            result.UniqueCount = 0;
            result.UnfoundCount = num;
            return result;
        }
        int n = Count;
        int num2 = System.Collections.Generic.BitHelper.ToIntArrayLength(n);
        Span<int> span = stackalloc int[100];
        System.Collections.Generic.BitHelper bitHelper = ((num2 <= 100) ? new System.Collections.Generic.BitHelper(span.Slice(0, num2), clear: true) : new System.Collections.Generic.BitHelper(new int[num2], clear: false));
        int num3 = 0;
        int num4 = 0;
        foreach (T item in other)
        {
            int num5 = InternalIndexOf(item);
            if (num5 >= 0)
            {
                if (!bitHelper.IsMarked(num5))
                {
                    bitHelper.MarkBit(num5);
                    num4++;
                }
            }
            else
            {
                num3++;
                if (returnIfUnfound)
                {
                    break;
                }
            }
        }
        result.UniqueCount = num4;
        result.UnfoundCount = num3;
        return result;
    }
References System.Collections.Generic.SortedSet< T >.Count, System.Runtime.Serialization.Dictionary, System.Collections.Generic.Dictionary< TKey, TValue >.GetEnumerator(), System.Collections.Generic.SortedSet< T >.InternalIndexOf(), System.item, System.other, and System.Collections.Generic.BitHelper.ToIntArrayLength().
Referenced by System.Collections.Generic.SortedSet< T >.IsProperSubsetOf(), System.Collections.Generic.SortedSet< T >.IsProperSupersetOf(), System.Collections.Generic.SortedSet< T >.IsSubsetOf(), and System.Collections.Generic.SortedSet< T >.SetEquals().