Terraria: System.Collections.Generic.SortedSet.IsSubsetOfSortedSetWithSameComparer
IsSubsetOfSortedSetWithSameComparer()
bool System.Collections.Generic.SortedSet< T >.IsSubsetOfSortedSetWithSameComparer (SortedSet< T > asSorted) inline private inherited
Definition at line 1652 of file SortedSet.cs.
    {
        SortedSet<T> viewBetween = asSorted.GetViewBetween(Min, Max);
        using (Enumerator enumerator = GetEnumerator())
        {
            while (enumerator.MoveNext())
            {
                T current = enumerator.Current;
                if (!viewBetween.Contains(current))
                {
                    return false;
                }
            }
        }
        return true;
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Contains(), System.Collections.Generic.SortedSet< T >.GetEnumerator(), System.Collections.Generic.SortedSet< T >.Max, and System.Collections.Generic.SortedSet< T >.Min.
Referenced by System.Collections.Generic.SortedSet< T >.IsProperSubsetOf(), and System.Collections.Generic.SortedSet< T >.IsSubsetOf().