Terraria: System.Collections.Generic.SortedSet.Overlaps
Overlaps()
bool System.Collections.Generic.SortedSet< T >.Overlaps (IEnumerable< T > other) inline inherited
Implements System.Collections.Generic.ISet< T >.
Definition at line 1793 of file SortedSet.cs.
    {
        if (other == null)
        {
            throw new ArgumentNullException("other");
        }
        if (Count == 0)
        {
            return false;
        }
        if (other is ICollection<T> { Count: 0 })
        {
            return false;
        }
        if (other is SortedSet<T> sortedSet && HasEqualComparer(sortedSet) && (comparer.Compare(Min, sortedSet.Max) > 0 || comparer.Compare(Max, sortedSet.Min) < 0))
        {
            return false;
        }
        foreach (T item in other)
        {
            if (Contains(item))
            {
                return true;
            }
        }
        return false;
    }
References System.Collections.Generic.IComparer< in T >.Compare(), System.Collections.Generic.SortedSet< T >.comparer, System.Collections.Generic.SortedSet< T >.Contains(), System.Collections.Generic.SortedSet< T >.Count, System.Collections.Generic.SortedSet< T >.HasEqualComparer(), System.item, System.Collections.Generic.SortedSet< T >.Max, System.Collections.Generic.SortedSet< T >.Min, and System.other.