Terraria: System.Collections.Generic.SortedSet.AddIfNotPresent
AddIfNotPresent()
virtual bool System.Collections.Generic.SortedSet< T >.AddIfNotPresent (T item) inline package virtual
Reimplemented in System.Collections.Generic.SortedSet< T >.TreeSubSet, and System.Collections.Generic.TreeSet< T >.
Definition at line 918 of file SortedSet.cs.
    {
        if (root == null)
        {
            root = new Node(item, NodeColor.Black);
            count = 1;
            version++;
            return true;
        }
        Node node = root;
        Node parent = null;
        Node node2 = null;
        Node greatGrandParent = null;
        version++;
        int num = 0;
        while (node != null)
        {
            num = comparer.Compare(item, node.Item);
            if (num == 0)
            {
                root.ColorBlack();
                return false;
            }
            if (node.Is4Node)
            {
                node.Split4Node();
                if (Node.IsNonNullRed(parent))
                {
                    InsertionBalance(node, ref parent, node2, greatGrandParent);
                }
            }
            greatGrandParent = node2;
            node2 = parent;
            parent = node;
            node = ((num < 0) ? node.Left : node.Right);
        }
        Node node3 = new Node(item, NodeColor.Red);
        if (num > 0)
        {
            parent.Right = node3;
        }
        else
        {
            parent.Left = node3;
        }
        if (parent.IsRed)
        {
            InsertionBalance(node3, ref parent, node2, greatGrandParent);
        }
        root.ColorBlack();
        count++;
        return true;
    }
References System.Collections.Generic.SortedSet< T >.Node.ColorBlack(), System.Collections.Generic.IComparer< in T >.Compare(), System.Collections.Generic.SortedSet< T >.comparer, System.Collections.Generic.SortedSet< T >.count, System.Runtime.Serialization.Dictionary, System.Collections.Generic.SortedSet< T >.InsertionBalance(), System.Collections.Generic.SortedSet< T >.Node.IsNonNullRed(), System.Collections.Generic.SortedSet< T >.Node.IsRed, System.item, System.Collections.Generic.SortedSet< T >.root, and System.Collections.Generic.SortedSet< T >.version.
Referenced by System.Collections.Generic.SortedSet< T >.Add().