Terraria: System.Text.RegularExpressions.RegexInterpreter.Goto
Goto()
void System.Text.RegularExpressions.RegexInterpreter.Goto (int newpos) inline private
Definition at line 37 of file RegexInterpreter.cs.
    {
        if (newpos < _codepos)
        {
            EnsureStorage();
        }
        _codepos = newpos;
        SetOperator(_code.Codes[newpos]);
    }
References System.Text.RegularExpressions.RegexInterpreter._code, System.Text.RegularExpressions.RegexInterpreter._codepos, System.Text.RegularExpressions.RegexCode.Codes, System.Text.RegularExpressions.RegexRunner.EnsureStorage(), and System.Text.RegularExpressions.RegexInterpreter.SetOperator().
Referenced by System.Text.RegularExpressions.RegexInterpreter.Go().