Terraria: System.Collections.Generic.SortedSet.DoRemove
DoRemove()
virtual bool System.Collections.Generic.SortedSet< T >.DoRemove (T item) inline package virtual inherited
Reimplemented in System.Collections.Generic.SortedSet< T >.TreeSubSet.
Definition at line 977 of file SortedSet.cs.
    {
        if (root == null)
        {
            return false;
        }
        version++;
        Node node = root;
        Node node2 = null;
        Node node3 = null;
        Node node4 = null;
        Node parentOfMatch = null;
        bool flag = false;
        while (node != null)
        {
            if (node.Is2Node)
            {
                if (node2 == null)
                {
                    node.ColorRed();
                }
                else
                {
                    Node sibling = node2.GetSibling(node);
                    if (sibling.IsRed)
                    {
                        if (node2.Right == sibling)
{
                            node2.RotateLeft();
                        }
                        else
{
                            node2.RotateRight();
                        }
                        node2.ColorRed();
                        sibling.ColorBlack();
                        ReplaceChildOrRoot(node3, node2, sibling);
                        node3 = sibling;
                        if (node2 == node4)
{
                            parentOfMatch = sibling;
                        }
                        sibling = node2.GetSibling(node);
                    }
                    if (sibling.Is2Node)
                    {
                        node2.Merge2Nodes();
                    }
                    else
                    {
                        Node node5 = node2.Rotate(node2.GetRotation(node, sibling));
                        node5.Color = node2.Color;
                        node2.ColorBlack();
                        node.ColorRed();
                        ReplaceChildOrRoot(node3, node2, node5);
                        if (node2 == node4)
{
                            parentOfMatch = node5;
                        }
                        node3 = node5;
                    }
                }
            }
            int num = (flag ? (-1) : comparer.Compare(item, node.Item));
            if (num == 0)
            {
                flag = true;
                node4 = node;
                parentOfMatch = node2;
            }
            node3 = node2;
            node2 = node;
            node = ((num < 0) ? node.Left : node.Right);
        }
        if (node4 != null)
        {
            ReplaceNode(node4, parentOfMatch, node2, node3);
            count--;
        }
        root?.ColorBlack();
        return flag;
    }
References System.Collections.Generic.SortedSet< T >.Node.ColorBlack(), System.Collections.Generic.IComparer< in T >.Compare(), System.Collections.Generic.SortedSet< T >.comparer, System.Collections.Generic.SortedSet< T >.count, System.Runtime.Serialization.Dictionary, System.item, System.Collections.Generic.SortedSet< T >.ReplaceChildOrRoot(), System.Collections.Generic.SortedSet< T >.ReplaceNode(), System.Collections.Generic.SortedSet< T >.root, and System.Collections.Generic.SortedSet< T >.version.
Referenced by System.Collections.Generic.SortedSet< T >.Remove().