Terraria: System.Collections.Generic.SortedSet.IntersectWith
IntersectWith()
virtual void System.Collections.Generic.SortedSet< T >.IntersectWith (IEnumerable< T > other) inline virtual inherited
Implements System.Collections.Generic.ISet< T >.
Definition at line 1454 of file SortedSet.cs.
    {
        if (other == null)
        {
            throw new ArgumentNullException("other");
        }
        if (Count == 0 || other == this)
        {
            return;
        }
        SortedSet<T> sortedSet = other as SortedSet<T>;
        TreeSubSet treeSubSet = this as TreeSubSet;
        if (treeSubSet != null)
        {
            VersionCheck();
        }
        if (sortedSet != null && treeSubSet == null && HasEqualComparer(sortedSet))
        {
            T[] array = new T[Count];
            int num = 0;
            Enumerator enumerator = GetEnumerator();
            Enumerator enumerator2 = sortedSet.GetEnumerator();
            bool flag = !enumerator.MoveNext();
            bool flag2 = !enumerator2.MoveNext();
            T max = Max;
            while (!flag && !flag2 && Comparer.Compare(enumerator2.Current, max) <= 0)
            {
                int num2 = Comparer.Compare(enumerator.Current, enumerator2.Current);
                if (num2 < 0)
                {
                    flag = !enumerator.MoveNext();
                }
                else if (num2 == 0)
                {
                    array[num++] = enumerator2.Current;
                    flag = !enumerator.MoveNext();
                    flag2 = !enumerator2.MoveNext();
                }
                else
                {
                    flag2 = !enumerator2.MoveNext();
                }
            }
            root = null;
            root = ConstructRootFromSortedArray(array, 0, num - 1, null);
            count = num;
            version++;
        }
        else
        {
            IntersectWithEnumerable(other);
        }
    }
References System.array, System.Collections.Generic.Comparer< T >.Compare(), System.Collections.Generic.SortedSet< T >.ConstructRootFromSortedArray(), System.Collections.Generic.SortedSet< T >.count, System.Collections.Generic.SortedSet< T >.Count, System.Collections.Generic.SortedSet< T >.GetEnumerator(), System.Collections.Generic.Dictionary< TKey, TValue >.GetEnumerator(), System.Collections.Generic.SortedSet< T >.HasEqualComparer(), System.Collections.Generic.SortedSet< T >.IntersectWithEnumerable(), System.Collections.Generic.SortedSet< T >.Max, System.other, System.Collections.Generic.SortedSet< T >.root, System.Collections.Generic.SortedSet< T >.version, and System.Collections.Generic.SortedSet< T >.VersionCheck().