Terraria: System.Collections.Generic.SortedSet.SymmetricExceptWith
SymmetricExceptWith()
void System.Collections.Generic.SortedSet< T >.SymmetricExceptWith (IEnumerable< T > other) inline inherited
Implements System.Collections.Generic.ISet< T >.
Definition at line 1568 of file SortedSet.cs.
    {
        if (other == null)
        {
            throw new ArgumentNullException("other");
        }
        if (Count == 0)
        {
            UnionWith(other);
            return;
        }
        if (other == this)
        {
            Clear();
            return;
        }
        if (other is SortedSet<T> other2 && HasEqualComparer(other2))
        {
            SymmetricExceptWithSameComparer(other2);
            return;
        }
        int length;
        T[] array = System.Collections.Generic.EnumerableHelpers.ToArray(other, out length);
        Array.Sort(array, 0, length, Comparer);
        SymmetricExceptWithSameComparer(array, length);
    }
References System.array, System.Collections.Generic.SortedSet< T >.Clear(), System.Collections.Generic.SortedSet< T >.Count, System.Collections.Generic.SortedSet< T >.HasEqualComparer(), System.length, System.other, System.Array.Sort(), System.Collections.Generic.SortedSet< T >.SymmetricExceptWithSameComparer(), and System.Collections.Generic.SortedSet< T >.UnionWith().