Terraria: System.Collections.Generic.SortedSet.SetEquals
SetEquals()
bool System.Collections.Generic.SortedSet< T >.SetEquals (IEnumerable< T > other) inline inherited
Implements System.Collections.Generic.ISet< T >.
Definition at line 1762 of file SortedSet.cs.
    {
        if (other == null)
        {
            throw new ArgumentNullException("other");
        }
        if (other is SortedSet<T> sortedSet && HasEqualComparer(sortedSet))
        {
            Enumerator enumerator = GetEnumerator();
            Enumerator enumerator2 = sortedSet.GetEnumerator();
            bool flag = !enumerator.MoveNext();
            bool flag2 = !enumerator2.MoveNext();
            while (!flag && !flag2)
            {
                if (Comparer.Compare(enumerator.Current, enumerator2.Current) != 0)
                {
                    return false;
                }
                flag = !enumerator.MoveNext();
                flag2 = !enumerator2.MoveNext();
            }
            return flag && flag2;
        }
        ElementCount elementCount = CheckUniqueAndUnfoundElements(other, returnIfUnfound: true);
        if (elementCount.UniqueCount == Count)
        {
            return elementCount.UnfoundCount == 0;
        }
        return false;
    }
References System.Collections.Generic.SortedSet< T >.CheckUniqueAndUnfoundElements(), System.Collections.Generic.Comparer< T >.Compare(), System.Collections.Generic.SortedSet< T >.Count, System.Runtime.Serialization.Dictionary, System.Collections.Generic.SortedSet< T >.GetEnumerator(), System.Collections.Generic.Dictionary< TKey, TValue >.GetEnumerator(), System.Collections.Generic.SortedSet< T >.HasEqualComparer(), and System.other.