Terraria: System.Collections.Generic.SortedSet.IsSupersetOf
IsSupersetOf()
bool System.Collections.Generic.SortedSet< T >.IsSupersetOf (IEnumerable< T > other) inline inherited
Implements System.Collections.Generic.ISet< T >.
Definition at line 1695 of file SortedSet.cs.
    {
        if (other == null)
        {
            throw new ArgumentNullException("other");
        }
        if (other is ICollection { Count: 0 })
        {
            return true;
        }
        if (other is SortedSet<T> sortedSet && HasEqualComparer(sortedSet))
        {
            if (Count < sortedSet.Count)
            {
                return false;
            }
            SortedSet<T> viewBetween = GetViewBetween(sortedSet.Min, sortedSet.Max);
            foreach (T item in sortedSet)
            {
                if (!viewBetween.Contains(item))
                {
                    return false;
                }
            }
            return true;
        }
        return ContainsAllElements(other);
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Contains(), System.Collections.Generic.SortedSet< T >.ContainsAllElements(), System.Collections.Generic.SortedSet< T >.Count, System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Collections.Generic.SortedSet< T >.GetViewBetween(), System.Collections.Generic.SortedSet< T >.HasEqualComparer(), System.item, and System.other.