Terraria: System.Collections.Generic.SortedSet.SortedSet
SortedSet() [4/5]
System.Collections.Generic.SortedSet< T >.SortedSet (IEnumerable< T > collection, IComparer< T >? comparer) inline
Definition at line 763 of file SortedSet.cs.
        : this(comparer)
    {
        if (collection == null)
        {
            throw new ArgumentNullException("collection");
        }
        if (collection is SortedSet<T> sortedSet && !(sortedSet is TreeSubSet) && HasEqualComparer(sortedSet))
        {
            if (sortedSet.Count > 0)
            {
                count = sortedSet.count;
                root = sortedSet.root.DeepClone(count);
            }
            return;
        }
        int length;
        T[] array = System.Collections.Generic.EnumerableHelpers.ToArray(collection, out length);
        if (length <= 0)
        {
            return;
        }
        comparer = this.comparer;
        Array.Sort(array, 0, length, comparer);
        int num = 1;
        for (int i = 1; i < length; i++)
        {
            if (comparer.Compare(array[i], array[i - 1]) != 0)
            {
                array[num++] = array[i];
            }
        }
        length = num;
        root = ConstructRootFromSortedArray(array, 0, length - 1, null);
        count = length;
    }
References System.array, System.collection, System.Collections.Generic.IComparer< in T >.Compare(), System.Collections.Generic.SortedSet< T >.comparer, System.Collections.Generic.SortedSet< T >.ConstructRootFromSortedArray(), System.Collections.Generic.SortedSet< T >.count, System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Collections.Generic.SortedSet< T >.HasEqualComparer(), System.length, System.Collections.Generic.SortedSet< T >.root, and System.Array.Sort().