Terraria: System.Collections.Generic.SortedSet.HasEqualComparer
HasEqualComparer()
bool System.Collections.Generic.SortedSet< T >.HasEqualComparer (SortedSet< T > other) inline private inherited
Definition at line 1333 of file SortedSet.cs.
    {
        if (Comparer != other.Comparer)
        {
            return Comparer.Equals(other.Comparer);
        }
        return true;
    }
References System.other.
Referenced by System.Collections.Generic.SortedSet< T >.SortedSet(), System.Collections.Generic.SortedSet< T >.ExceptWith(), System.Collections.Generic.SortedSet< T >.IntersectWith(), System.Collections.Generic.SortedSet< T >.IsProperSubsetOf(), System.Collections.Generic.SortedSet< T >.IsProperSupersetOf(), System.Collections.Generic.SortedSet< T >.IsSubsetOf(), System.Collections.Generic.SortedSet< T >.IsSupersetOf(), System.Collections.Generic.SortedSet< T >.Overlaps(), System.Collections.Generic.SortedSet< T >.SetEquals(), System.Collections.Generic.SortedSet< T >.SymmetricExceptWith(), and System.Collections.Generic.SortedSet< T >.UnionWith().