Terraria: System.Text.RegularExpressions.RegexInterpreter.FindFirstChar
FindFirstChar()
override bool System.Text.RegularExpressions.RegexInterpreter.FindFirstChar () inline protected
Definition at line 338 of file RegexInterpreter.cs.
    {
        if (!_code.RightToLeft)
        {
            if (runtextpos > runtextend - _code.Tree.MinRequiredLength)
            {
                runtextpos = runtextend;
                return false;
            }
        }
        else if (runtextpos - _code.Tree.MinRequiredLength < runtextbeg)
        {
            runtextpos = runtextbeg;
            return false;
        }
        if (((uint)_code.LeadingAnchor & 0x35u) != 0)
        {
            if (!_code.RightToLeft)
            {
                int leadingAnchor = _code.LeadingAnchor;
                if (leadingAnchor <= 4)
                {
                    if (leadingAnchor != 1)
                    {
                        if (leadingAnchor == 4 && runtextpos > runtextstart)
{
                            goto IL_00da;
                        }
                    }
                    else if (runtextpos > runtextbeg)
                    {
                        goto IL_00da;
                    }
                }
                else
                {
                    switch (leadingAnchor)
                    {
                    case 16:
                        if (runtextpos < runtextend - 1)
{
                            runtextpos = runtextend - 1;
                        }
                        break;
                    case 32:
                        if (runtextpos < runtextend)
{
                            runtextpos = runtextend;
                        }
                        break;
                    }
                }
            }
            else
            {
                int leadingAnchor2 = _code.LeadingAnchor;
                if (leadingAnchor2 <= 4)
                {
                    if (leadingAnchor2 != 1)
                    {
                        if (leadingAnchor2 == 4 && runtextpos < runtextstart)
{
                            goto IL_01ac;
                        }
                    }
                    else if (runtextpos > runtextbeg)
                    {
                        runtextpos = runtextbeg;
                    }
                }
                else if (leadingAnchor2 != 16)
                {
                    if (leadingAnchor2 == 32 && runtextpos < runtextend)
                    {
                        goto IL_01ac;
                    }
                }
                else if (runtextpos < runtextend - 1 || (runtextpos == runtextend - 1 && runtext[runtextpos] != '\n'))
                {
                    goto IL_01ac;
                }
            }
            if (_code.BoyerMoorePrefix != null)
            {
                return _code.BoyerMoorePrefix.IsMatch(runtext, runtextpos, runtextbeg, runtextend);
            }
            return true;
        }
        if (_code.LeadingAnchor == 2 && !_code.RightToLeft && runtextpos > runtextbeg && runtext[runtextpos - 1] != '\n')
        {
            int num = runtext.IndexOf('\n', runtextpos);
            if (num == -1 || num + 1 > runtextend)
            {
                runtextpos = runtextend;
                return false;
            }
            runtextpos = num + 1;
        }
        if (_code.BoyerMoorePrefix != null)
        {
            runtextpos = _code.BoyerMoorePrefix.Scan(runtext, runtextpos, runtextbeg, runtextend);
            if (runtextpos == -1)
            {
                runtextpos = (_code.RightToLeft ? runtextbeg : runtextend);
                return false;
            }
            return true;
        }
        if (_code.LeadingCharClasses == null)
        {
            return true;
        }
        string item = _code.LeadingCharClasses[0].CharClass;
        if (RegexCharClass.IsSingleton(item))
        {
            char c = RegexCharClass.SingletonChar(item);
            if (!_code.RightToLeft)
            {
                ReadOnlySpan<char> span = runtext.AsSpan(runtextpos, runtextend - runtextpos);
                if (!_code.LeadingCharClasses[0].CaseInsensitive)
                {
                    int num2 = span.IndexOf(c);
                    if (num2 >= 0)
                    {
                        runtextpos += num2;
                        return true;
                    }
                }
                else
                {
                    TextInfo textInfo = _textInfo;
                    for (int i = 0; i < span.Length; i++)
                    {
                        if (c == textInfo.ToLower(span[i]))
{
                            runtextpos += i;
                            return true;
                        }
                    }
                }
                runtextpos = runtextend;
            }
            else
            {
                if (!_code.LeadingCharClasses[0].CaseInsensitive)
                {
                    for (int num3 = runtextpos - 1; num3 >= runtextbeg; num3--)
                    {
                        if (c == runtext[num3])
{
                            runtextpos = num3 + 1;
                            return true;
                        }
                    }
                }
                else
                {
                    TextInfo textInfo2 = _textInfo;
                    for (int num4 = runtextpos - 1; num4 >= runtextbeg; num4--)
                    {
                        if (c == textInfo2.ToLower(runtext[num4]))
{
                            runtextpos = num4 + 1;
                            return true;
                        }
                    }
                }
                runtextpos = runtextbeg;
            }
        }
        else if (!_code.RightToLeft)
        {
            ReadOnlySpan<char> readOnlySpan = runtext.AsSpan(runtextpos, runtextend - runtextpos);
            if (!_code.LeadingCharClasses[0].CaseInsensitive)
            {
                for (int j = 0; j < readOnlySpan.Length; j++)
                {
                    if (RegexCharClass.CharInClass(readOnlySpan[j], item, ref _code.LeadingCharClassAsciiLookup))
                    {
                        runtextpos += j;
                        return true;
                    }
                }
            }
            else
            {
                TextInfo textInfo3 = _textInfo;
                for (int k = 0; k < readOnlySpan.Length; k++)
                {
                    if (RegexCharClass.CharInClass(textInfo3.ToLower(readOnlySpan[k]), item, ref _code.LeadingCharClassAsciiLookup))
                    {
                        runtextpos += k;
                        return true;
                    }
                }
            }
            runtextpos = runtextend;
        }
        else
        {
            if (!_code.LeadingCharClasses[0].CaseInsensitive)
            {
                for (int num5 = runtextpos - 1; num5 >= runtextbeg; num5--)
                {
                    if (RegexCharClass.CharInClass(runtext[num5], item, ref _code.LeadingCharClassAsciiLookup))
                    {
                        runtextpos = num5 + 1;
                        return true;
                    }
                }
            }
            else
            {
                TextInfo textInfo4 = _textInfo;
                for (int num6 = runtextpos - 1; num6 >= runtextbeg; num6--)
                {
                    if (RegexCharClass.CharInClass(textInfo4.ToLower(runtext[num6]), item, ref _code.LeadingCharClassAsciiLookup))
                    {
                        runtextpos = num6 + 1;
                        return true;
                    }
                }
            }
            runtextpos = runtextbeg;
        }
        return false;
        IL_01ac:
        runtextpos = runtextbeg;
        return false;
        IL_00da:
        runtextpos = runtextend;
        return false;
    }
References System.Text.RegularExpressions.RegexInterpreter._code, System.Text.RegularExpressions.RegexInterpreter._textInfo, System.Text.RegularExpressions.RegexCode.BoyerMoorePrefix, System.Text.RegularExpressions.RegexCharClass.CharInClass(), System.Text.RegularExpressions.i, System.Text.RegularExpressions.RegexBoyerMoore.IsMatch(), System.Text.RegularExpressions.RegexCharClass.IsSingleton(), System.item, System.Text.RegularExpressions.RegexCode.LeadingAnchor, System.Text.RegularExpressions.RegexCode.LeadingCharClassAsciiLookup, System.ReadOnlySpan< T >.Length, System.Text.RegularExpressions.RegexTree.MinRequiredLength, System.Text.RegularExpressions.RegexCode.RightToLeft, System.Text.RegularExpressions.RegexRunner.runtext, System.Text.RegularExpressions.RegexRunner.runtextbeg, System.Text.RegularExpressions.RegexRunner.runtextend, System.Text.RegularExpressions.RegexRunner.runtextpos, System.Text.RegularExpressions.RegexRunner.runtextstart, System.Text.RegularExpressions.RegexBoyerMoore.Scan(), System.Text.RegularExpressions.RegexCharClass.SingletonChar(), System.Globalization.TextInfo.ToLower(), and System.Text.RegularExpressions.RegexCode.Tree.