Terraria: System.Collections.Generic.SortedSet.ConstructRootFromSortedArray
ConstructRootFromSortedArray()
static Node System.Collections.Generic.SortedSet< T >.ConstructRootFromSortedArray (T[] arr, int startIndex, int endIndex, Node redNode) inline static private inherited
Definition at line 1409 of file SortedSet.cs.
    {
        int num = endIndex - startIndex + 1;
        Node node;
        switch (num)
        {
        case 0:
            return null;
        case 1:
            node = new Node(arr[startIndex], NodeColor.Black);
            if (redNode != null)
            {
                node.Left = redNode;
            }
            break;
        case 2:
            node = new Node(arr[startIndex], NodeColor.Black);
            node.Right = new Node(arr[endIndex], NodeColor.Black);
            node.Right.ColorRed();
            if (redNode != null)
            {
                node.Left = redNode;
            }
            break;
        case 3:
            node = new Node(arr[startIndex + 1], NodeColor.Black);
            node.Left = new Node(arr[startIndex], NodeColor.Black);
            node.Right = new Node(arr[endIndex], NodeColor.Black);
            if (redNode != null)
            {
                node.Left.Left = redNode;
            }
            break;
        default:
        {
            int num2 = (startIndex + endIndex) / 2;
            node = new Node(arr[num2], NodeColor.Black);
            node.Left = ConstructRootFromSortedArray(arr, startIndex, num2 - 1, redNode);
            node.Right = ((num % 2 == 0) ? ConstructRootFromSortedArray(arr, num2 + 2, endIndex, new Node(arr[num2 + 1], NodeColor.Red)) : ConstructRootFromSortedArray(arr, num2 + 1, endIndex, null));
            break;
        }
        }
        return node;
    }
References System.Collections.Generic.SortedSet< T >.ConstructRootFromSortedArray(), System.Runtime.Serialization.Dictionary, System.endIndex, and System.startIndex.
Referenced by System.Collections.Generic.SortedSet< T >.SortedSet(), System.Collections.Generic.SortedSet< T >.ConstructRootFromSortedArray(), System.Collections.Generic.SortedSet< T >.IntersectWith(), and System.Collections.Generic.SortedSet< T >.UnionWith().