Terraria: System.Net.WebSockets.ManagedWebSocket._003CEnsureBufferContainsAsync_003Ed__74.MoveNext
MoveNext() [1/2]
void System.Net.WebSockets.ManagedWebSocket._003CEnsureBufferContainsAsync_003Ed__74.MoveNext () inline private
Implements System.Runtime.CompilerServices.IAsyncStateMachine.
Definition at line 491 of file ManagedWebSocket.cs.
        {
            int num = _003C_003E1__state;
            ManagedWebSocket managedWebSocket = _003C_003E4__this;
            try
            {
                ConfiguredValueTaskAwaitable<int>.ConfiguredValueTaskAwaiter awaiter;
                if (num == 0)
                {
                    awaiter = _003C_003Eu__1;
                    _003C_003Eu__1 = default(ConfiguredValueTaskAwaitable<int>.ConfiguredValueTaskAwaiter);
                    num = (_003C_003E1__state = -1);
                    goto IL_00ff;
                }
                if (managedWebSocket._receiveBufferCount < minimumRequiredBytes)
                {
                    if (managedWebSocket._receiveBufferCount > 0)
                    {
                        Span<byte> span = managedWebSocket._receiveBuffer.Span;
                        span = span.Slice(managedWebSocket._receiveBufferOffset, managedWebSocket._receiveBufferCount);
                        span.CopyTo(managedWebSocket._receiveBuffer.Span);
                    }
                    managedWebSocket._receiveBufferOffset = 0;
                    goto IL_012b;
                }
                goto end_IL_000e;
                IL_00ff:
                int result = awaiter.GetResult();
                int num2 = result;
                if (num2 > 0)
                {
                    managedWebSocket._receiveBufferCount += num2;
                    goto IL_012b;
                }
                managedWebSocket.ThrowIfEOFUnexpected(throwOnPrematureClosure);
                goto end_IL_000e;
                IL_012b:
                if (managedWebSocket._receiveBufferCount < minimumRequiredBytes)
                {
                    awaiter = managedWebSocket._stream.ReadAsync(managedWebSocket._receiveBuffer.Slice(managedWebSocket._receiveBufferCount, managedWebSocket._receiveBuffer.Length - managedWebSocket._receiveBufferCount), cancellationToken).ConfigureAwait(continueOnCapturedContext: false).GetAwaiter();
                    if (!awaiter.IsCompleted)
                    {
                        num = (_003C_003E1__state = 0);
                        _003C_003Eu__1 = awaiter;
                        _003C_003Et__builder.AwaitUnsafeOnCompleted(ref awaiter, ref this);
                        return;
                    }
                    goto IL_00ff;
                }
                end_IL_000e:;
            }
            catch (Exception exception)
            {
                _003C_003E1__state = -2;
                _003C_003Et__builder.SetException(exception);
                return;
            }
            _003C_003E1__state = -2;
            _003C_003Et__builder.SetResult();
        }
References System.Net.WebSockets.ManagedWebSocket._003CEnsureBufferContainsAsync_003Ed__74._003C_003E1__state, System.Net.WebSockets.ManagedWebSocket._003CEnsureBufferContainsAsync_003Ed__74._003C_003E4__this, System.Net.WebSockets.ManagedWebSocket._003CEnsureBufferContainsAsync_003Ed__74._003C_003Et__builder, System.Net.WebSockets.ManagedWebSocket._003CEnsureBufferContainsAsync_003Ed__74._003C_003Eu__1, System.Net.WebSockets.ManagedWebSocket._receiveBuffer, System.Net.WebSockets.ManagedWebSocket._receiveBufferCount, System.Net.WebSockets.ManagedWebSocket._receiveBufferOffset, System.Net.WebSockets.ManagedWebSocket._stream, System.Net.WebSockets.ManagedWebSocket._003CEnsureBufferContainsAsync_003Ed__74.cancellationToken, System.Span< T >.CopyTo(), System.exception, System.Memory< T >.Length, System.Net.WebSockets.ManagedWebSocket._003CEnsureBufferContainsAsync_003Ed__74.minimumRequiredBytes, System.IO.Stream.ReadAsync(), System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder< TResult >.SetException(), System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder< TResult >.SetResult(), System.Memory< T >.Slice(), System.Span< T >.Slice(), System.Memory< T >.Span, System.Net.WebSockets.ManagedWebSocket.ThrowIfEOFUnexpected(), and System.Net.WebSockets.ManagedWebSocket._003CEnsureBufferContainsAsync_003Ed__74.throwOnPrematureClosure.
Referenced by System.Net.WebSockets.ManagedWebSocket._003CEnsureBufferContainsAsync_003Ed__74.MoveNext().