Terraria: System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd
ValidateEnd()
static void System.Runtime.CompilerServices.TaskAwaiter< TResult >.ValidateEnd (Task task) inline static package
Definition at line 38 of file TaskAwaiter.cs.
    {
        if (task.IsWaitNotificationEnabledOrNotRanToCompletion)
        {
            HandleNonSuccessAndDebuggerNotification(task);
        }
    }
References System.Runtime.CompilerServices.TaskAwaiter< TResult >.HandleNonSuccessAndDebuggerNotification(), and System.task.
Referenced by System.Runtime.CompilerServices.ConfiguredTaskAwaitable< TResult >.ConfiguredTaskAwaiter.GetResult(), System.Runtime.CompilerServices.TaskAwaiter< TResult >.GetResult(), and System.Threading.Tasks.ValueTask< TResult >.ThrowIfCompletedUnsuccessfully().