Terraria: System.Runtime.CompilerServices.TaskAwaiter.OnCompletedInternal
OnCompletedInternal()
static void System.Runtime.CompilerServices.TaskAwaiter< TResult >.OnCompletedInternal (Task task, Action continuation, bool continueOnCapturedContext, bool flowExecutionContext) inline static package
Definition at line 81 of file TaskAwaiter.cs.
    {
        if (continuation == null)
        {
            throw new ArgumentNullException("continuation");
        }
        if (TplEventSource.Log.IsEnabled() || Task.s_asyncDebuggingEnabled)
        {
            continuation = OutputWaitEtwEvents(task, continuation);
        }
        task.SetContinuationForAwait(continuation, continueOnCapturedContext, flowExecutionContext);
    }
References System.Threading.Tasks.TplEventSource.Log, System.Runtime.CompilerServices.TaskAwaiter< TResult >.OutputWaitEtwEvents(), System.Threading.Tasks.Task< TResult >.s_asyncDebuggingEnabled, and System.task.
Referenced by System.Runtime.CompilerServices.ConfiguredTaskAwaitable< TResult >.ConfiguredTaskAwaiter.OnCompleted(), System.Runtime.CompilerServices.TaskAwaiter< TResult >.OnCompleted(), System.Runtime.CompilerServices.ConfiguredTaskAwaitable< TResult >.ConfiguredTaskAwaiter.UnsafeOnCompleted(), and System.Runtime.CompilerServices.TaskAwaiter< TResult >.UnsafeOnCompleted().