Terraria: System.Runtime.CompilerServices.TaskAwaiter.UnsafeOnCompletedInternal
UnsafeOnCompletedInternal()
static void System.Runtime.CompilerServices.TaskAwaiter< TResult >.UnsafeOnCompletedInternal (Task task, IAsyncStateMachineBox stateMachineBox, bool continueOnCapturedContext) inline static package
Definition at line 94 of file TaskAwaiter.cs.
    {
        if (TplEventSource.Log.IsEnabled() || Task.s_asyncDebuggingEnabled)
        {
            task.SetContinuationForAwait(OutputWaitEtwEvents(task, stateMachineBox.MoveNextAction), continueOnCapturedContext, flowExecutionContext: false);
        }
        else
        {
            task.UnsafeSetContinuationForAwait(stateMachineBox, continueOnCapturedContext);
        }
    }
References System.Threading.Tasks.TplEventSource.Log, System.Runtime.CompilerServices.TaskAwaiter< TResult >.OutputWaitEtwEvents(), System.Threading.Tasks.Task< TResult >.s_asyncDebuggingEnabled, and System.task.
Referenced by System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable< TResult >.ConfiguredValueTaskAwaiter.AwaitUnsafeOnCompleted(), System.Runtime.CompilerServices.ValueTaskAwaiter< TResult >.AwaitUnsafeOnCompleted(), and System.Runtime.CompilerServices.AsyncTaskMethodBuilder< TResult >.AwaitUnsafeOnCompleted< TAwaiter >().