Terraria: System.Runtime.CompilerServices.TaskAwaiter.OutputWaitEtwEvents
OutputWaitEtwEvents()
static Action System.Runtime.CompilerServices.TaskAwaiter< TResult >.OutputWaitEtwEvents (Task task, Action continuation) inline static private
Definition at line 106 of file TaskAwaiter.cs.
    {
        if (Task.s_asyncDebuggingEnabled)
        {
            Task.AddToActiveTasks(task);
        }
        TplEventSource log = TplEventSource.Log;
        if (log.IsEnabled())
        {
            Task internalCurrent = Task.InternalCurrent;
            Task task2 = AsyncMethodBuilderCore.TryGetContinuationTask(continuation);
            log.TaskWaitBegin(internalCurrent?.m_taskScheduler.Id ?? TaskScheduler.Default.Id, internalCurrent?.Id ?? 0, task.Id, TplEventSource.TaskWaitBehavior.Asynchronous, task2?.Id ?? 0);
        }
        return AsyncMethodBuilderCore.CreateContinuationWrapper(continuation, delegate(Action innerContinuation, Task innerTask)
        {
            if (Task.s_asyncDebuggingEnabled)
            {
                Task.RemoveFromActiveTasks(innerTask);
            }
            TplEventSource log2 = TplEventSource.Log;
            Guid oldActivityThatWillContinue = default(Guid);
            bool flag = log2.IsEnabled();
            if (flag)
            {
                Task internalCurrent2 = Task.InternalCurrent;
                log2.TaskWaitEnd(internalCurrent2?.m_taskScheduler.Id ?? TaskScheduler.Default.Id, internalCurrent2?.Id ?? 0, innerTask.Id);
                if (log2.TasksSetActivityIds && (innerTask.Options & (TaskCreationOptions)1024) != 0)
                {
                    EventSource.SetCurrentThreadActivityId(TplEventSource.CreateGuidForTaskID(innerTask.Id), out oldActivityThatWillContinue);
                }
            }
            innerContinuation();
            if (flag)
            {
                log2.TaskWaitContinuationComplete(innerTask.Id);
                if (log2.TasksSetActivityIds && (innerTask.Options & (TaskCreationOptions)1024) != 0)
                {
                    EventSource.SetCurrentThreadActivityId(oldActivityThatWillContinue);
                }
            }
        }, task);
    }
References System.Threading.Tasks.Task< TResult >.AddToActiveTasks(), System.Runtime.CompilerServices.AsyncMethodBuilderCore.CreateContinuationWrapper(), System.Threading.Tasks.TplEventSource.CreateGuidForTaskID(), System.Threading.Tasks.TaskScheduler.Default, System.Threading.Tasks.Task< TResult >.InternalCurrent, System.Threading.Tasks.TplEventSource.Log, System.Threading.Tasks.Task< TResult >.s_asyncDebuggingEnabled, System.Diagnostics.Tracing.EventSource.SetCurrentThreadActivityId(), System.task, and System.Runtime.CompilerServices.AsyncMethodBuilderCore.TryGetContinuationTask().
Referenced by System.Runtime.CompilerServices.TaskAwaiter< TResult >.OnCompletedInternal(), and System.Runtime.CompilerServices.TaskAwaiter< TResult >.UnsafeOnCompletedInternal().