Terraria: System.Globalization.Normalization.Normalize
Normalize()
static string System.Globalization.Normalization.Normalize (string strInput, NormalizationForm normalizationForm) inline static package
Definition at line 22 of file Normalization.cs.
    {
        if (GlobalizationMode.Invariant)
        {
            return strInput;
        }
        if (!GlobalizationMode.UseNls)
        {
            return IcuNormalize(strInput, normalizationForm);
        }
        return NlsNormalize(strInput, normalizationForm);
    }
References System.Globalization.Normalization.IcuNormalize(), System.Globalization.GlobalizationMode.Invariant, System.Globalization.Normalization.NlsNormalize(), and System.Globalization.GlobalizationMode.UseNls.
Referenced by System.String.Normalize().