Terraria: System.Globalization.Normalization.NlsNormalize
NlsNormalize()
static unsafe string System.Globalization.Normalization.NlsNormalize (string strInput, NormalizationForm normalizationForm) inline static private
Definition at line 169 of file Normalization.cs.
    {
        if (strInput.Length == 0)
        {
            return string.Empty;
        }
        char[] array = null;
        try
        {
            Span<char> span = ((strInput.Length > 512) ? ((Span<char>)(array = ArrayPool<char>.Shared.Rent(strInput.Length))) : stackalloc char[512]);
            Span<char> span2 = span;
            while (true)
            {
                int num;
                fixed (char* source = strInput)
                {
                    fixed (char* destination = &MemoryMarshal.GetReference(span2))
                    {
                        num = Interop.Normaliz.NormalizeString(normalizationForm, source, strInput.Length, destination, span2.Length);
                    }
                }
                int lastPInvokeError = Marshal.GetLastPInvokeError();
                switch (lastPInvokeError)
                {
                case 0:
                {
                    ReadOnlySpan<char> readOnlySpan = span2.Slice(0, num);
                    return readOnlySpan.SequenceEqual(strInput) ? strInput : new string(readOnlySpan);
                }
                case 122:
                    num = Math.Abs(num);
                    if (array != null)
                    {
                        char[] array2 = array;
                        array = null;
                        ArrayPool<char>.Shared.Return(array2);
                    }
                    break;
                case 87:
                case 1113:
                    if (normalizationForm != NormalizationForm.FormC && normalizationForm != NormalizationForm.FormD && normalizationForm != NormalizationForm.FormKC && normalizationForm != NormalizationForm.FormKD)
                    {
                        throw new ArgumentException(SR.Argument_InvalidNormalizationForm, "normalizationForm");
                    }
                    throw new ArgumentException(SR.Argument_InvalidCharSequenceNoIndex, "strInput");
                case 8:
                    throw new OutOfMemoryException();
                default:
                    throw new InvalidOperationException(SR.Format(SR.UnknownError_Num, lastPInvokeError));
                }
                span2 = (array = ArrayPool<char>.Shared.Rent(num));
            }
        }
        finally
        {
            if (array != null)
            {
                ArrayPool<char>.Shared.Return(array);
            }
        }
    }
References System.Math.Abs(), System.SR.Argument_InvalidCharSequenceNoIndex, System.SR.Argument_InvalidNormalizationForm, System.array, System.destination, System.SR.Format(), System.Runtime.InteropServices.Marshal.GetLastPInvokeError(), System.Span< T >.Length, Interop.Normaliz.NormalizeString(), System.Buffers.ArrayPool< T >.Shared, System.Span< T >.Slice(), System.source, and System.SR.UnknownError_Num.
Referenced by System.Globalization.Normalization.Normalize().