Terraria: System.Globalization.Normalization.IcuNormalize
IcuNormalize()
static unsafe string System.Globalization.Normalization.IcuNormalize (string strInput, NormalizationForm normalizationForm) inline static private
Definition at line 50 of file Normalization.cs.
    {
        ValidateArguments(strInput, normalizationForm);
        char[] array = null;
        try
        {
            Span<char> span = ((strInput.Length > 512) ? ((Span<char>)(array = ArrayPool<char>.Shared.Rent(strInput.Length))) : stackalloc char[512]);
            Span<char> span2 = span;
            for (int i = 0; i < 2; i++)
            {
                int num;
                fixed (char* src = strInput)
                {
                    fixed (char* dstBuffer = &MemoryMarshal.GetReference(span2))
                    {
                        num = Interop.Globalization.NormalizeString(normalizationForm, src, strInput.Length, dstBuffer, span2.Length);
                    }
                }
                if (num == -1)
                {
                    throw new ArgumentException(SR.Argument_InvalidCharSequenceNoIndex, "strInput");
                }
                if (num <= span2.Length)
                {
                    ReadOnlySpan<char> readOnlySpan = span2.Slice(0, num);
                    return readOnlySpan.SequenceEqual(strInput) ? strInput : new string(readOnlySpan);
                }
                if (i == 0)
                {
                    if (array != null)
                    {
                        char[] array2 = array;
                        array = null;
                        ArrayPool<char>.Shared.Return(array2);
                    }
                    span2 = (array = ArrayPool<char>.Shared.Rent(num));
                }
            }
            throw new ArgumentException(SR.Argument_InvalidCharSequenceNoIndex, "strInput");
        }
        finally
        {
            if (array != null)
            {
                ArrayPool<char>.Shared.Return(array);
            }
        }
    }
References System.SR.Argument_InvalidCharSequenceNoIndex, System.array, System.Span< T >.Length, Interop.Globalization.NormalizeString(), System.Buffers.ArrayPool< T >.Shared, System.Span< T >.Slice(), and System.Globalization.Normalization.ValidateArguments().
Referenced by System.Globalization.Normalization.Normalize().