Terraria: System.Globalization.Normalization.ValidateArguments
ValidateArguments()
static void System.Globalization.Normalization.ValidateArguments (string strInput, NormalizationForm normalizationForm) inline static private
Definition at line 99 of file Normalization.cs.
    {
        if (OperatingSystem.IsBrowser())
        {
        }
        if (normalizationForm != NormalizationForm.FormC && normalizationForm != NormalizationForm.FormD && normalizationForm != NormalizationForm.FormKC && normalizationForm != NormalizationForm.FormKD)
        {
            throw new ArgumentException(SR.Argument_InvalidNormalizationForm, "normalizationForm");
        }
        if (HasInvalidUnicodeSequence(strInput))
        {
            throw new ArgumentException(SR.Argument_InvalidCharSequenceNoIndex, "strInput");
        }
    }
References System.SR.Argument_InvalidCharSequenceNoIndex, System.SR.Argument_InvalidNormalizationForm, System.Globalization.Normalization.HasInvalidUnicodeSequence(), and System.OperatingSystem.IsBrowser().
Referenced by System.Globalization.Normalization.IcuIsNormalized(), and System.Globalization.Normalization.IcuNormalize().