Terraria: System.Globalization.Normalization.IsNormalized
IsNormalized()
static bool System.Globalization.Normalization.IsNormalized (string strInput, NormalizationForm normalizationForm) inline static package
Definition at line 9 of file Normalization.cs.
    {
        if (GlobalizationMode.Invariant)
        {
            return true;
        }
        if (!GlobalizationMode.UseNls)
        {
            return IcuIsNormalized(strInput, normalizationForm);
        }
        return NlsIsNormalized(strInput, normalizationForm);
    }
References System.Globalization.Normalization.IcuIsNormalized(), System.Globalization.GlobalizationMode.Invariant, System.Globalization.Normalization.NlsIsNormalized(), and System.Globalization.GlobalizationMode.UseNls.
Referenced by System.String.IsNormalized().