Terraria: PartySky.Update
Update()
override void PartySky.Update (GameTime gameTime) inline virtual
Implements CustomSky.
     {
         if (!MultipleSkyWorkaroundFix && Main.dayRate == 0)
         {
             return;
         }
         MultipleSkyWorkaroundFix = false;
         if (Main.gamePaused || !Main.hasFocus)
         {
             return;
         }
         _opacity = Utils.Clamp(_opacity + (float)IsNearParty().ToDirectionInt() * 0.01f, 0f, 1f);
         for (int i = 0; i < _balloons.Length; i++)
         {
             if (!_balloons[i].Active)
             {
                 continue;
             }
             _balloons[i].Frame++;
             _balloons[i].Position.Y += _balloons[i].Speed;
             _balloons[i].Position.X += Main.windSpeedCurrent * (3f - _balloons[i].Speed);
             if (!(_balloons[i].Position.Y < 300f))
             {
                 continue;
             }
             if (!_leaving)
             {
                 ResetBalloon(i);
                 _balloons[i].Position = new Vector2(_random.Next(0, Main.maxTilesX) * 16, (float)Main.worldSurface * 16f + 1600f);
                 if (_random.Next(30) == 0)
                 {
                     _balloons[i].Texture = _textures[2].Value;
                 }
             }
             else
             {
                 _balloons[i].Active = false;
                 _balloonsDrawing--;
             }
         }
         if (_balloonsDrawing == 0)
         {
             _active = false;
         }
         _active = true;
     }
References _active, _balloons, _balloonsDrawing, _leaving, _opacity, _random, _textures, PartySky.Balloon.Active, Active, Main.dayRate, PartySky.Balloon.Frame, Main.gamePaused, Main.hasFocus, IsNearParty(), Main.maxTilesX, MultipleSkyWorkaroundFix, UnifiedRandom.Next(), PartySky.Balloon.Position, ResetBalloon(), PartySky.Balloon.Speed, PartySky.Balloon.Texture, Asset< T >.Value, Main.windSpeedCurrent, and Main.worldSurface.