Terraria: UITextBox.Backspace
Backspace()
void UITextBox.Backspace () inline
     {
         if (_cursor != 0)
         {
             SetText(base.Text.Substring(0, base.Text.Length - 1));
         }
     }
References _cursor, and SetText().
Referenced by UIVirtualKeyboard.UIVirtualKeyboard(), and UIVirtualKeyboard.BackSpace().