Terraria: UITextBox.DrawSelf
DrawSelf()
override void UITextBox.DrawSelf (SpriteBatch spriteBatch) inline protected
     {
         if (HideSelf)
         {
             return;
         }
         _cursor = base.Text.Length;
         base.DrawSelf(spriteBatch);
         _frameCount++;
         if ((_frameCount %= 40) <= 20 && ShowInputTicker)
         {
             CalculatedStyle innerDimensions = GetInnerDimensions();
             Vector2 pos = innerDimensions.Position();
             Vector2 vector = new Vector2((base.IsLarge ? FontAssets.DeathText.Value : FontAssets.MouseText.Value).MeasureString(base.Text.Substring(0, _cursor)).X, base.IsLarge ? 32f : 16f) * base.TextScale;
             if (base.IsLarge)
             {
                 pos.Y -= 8f * base.TextScale;
             }
             else
             {
                 pos.Y -= 2f * base.TextScale;
             }
             pos.X += (innerDimensions.Width - base.TextSize.X) * TextHAlign + vector.X - (base.IsLarge ? 8f : 4f) * base.TextScale + 6f;
             if (base.IsLarge)
             {
                 Utils.DrawBorderStringBig(spriteBatch, "|", pos, base.TextColor, base.TextScale);
             }
             else
             {
                 Utils.DrawBorderString(spriteBatch, "|", pos, base.TextColor, base.TextScale);
             }
         }
     }
References _cursor, _frameCount, FontAssets.DeathText, Utils.DrawBorderString(), Utils.DrawBorderStringBig(), HideSelf, FontAssets.MouseText, CalculatedStyle.Position(), ShowInputTicker, UITextPanel< string >.TextHAlign, Asset< T >.Value, and CalculatedStyle.Width.