Terraria: System.Net.Mail.AuthCommand.PrepareCommand
PrepareCommand() [2/2]
static void System.Net.Mail.AuthCommand.PrepareCommand (SmtpConnection conn, string type, string message) inline static private
Definition at line 31 of file AuthCommand.cs.
    {
        conn.BufferBuilder.Append(SmtpCommands.Auth);
        conn.BufferBuilder.Append(type);
        conn.BufferBuilder.Append(32);
        conn.BufferBuilder.Append(message);
        conn.BufferBuilder.Append(SmtpCommands.CRLF);
    }
References System.Net.Mail.BufferBuilder.Append(), System.Net.Mail.SmtpCommands.Auth, System.Net.Mail.SmtpConnection.BufferBuilder, System.Net.Mail.SmtpCommands.CRLF, and System.type.
Referenced by System.Net.Mail.AuthCommand.BeginSend(), System.Net.Mail.AuthCommand.BeginSend(), System.Net.Mail.AuthCommand.Send(), and System.Net.Mail.AuthCommand.Send().