Terraria: System.Xml.XmlWellFormedWriter.AttributeValueCache.WriteSurrogateCharEntity
WriteSurrogateCharEntity()
void System.Xml.XmlWellFormedWriter.AttributeValueCache.WriteSurrogateCharEntity (char lowChar, char highChar) inline package
Definition at line 359 of file XmlWellFormedWriter.cs.
        {
            if (_singleStringValue != null)
            {
                StartComplexValue();
            }
            _stringValue.Append(highChar);
            _stringValue.Append(lowChar);
            AddItem(ItemType.SurrogateCharEntity, new char[2] { lowChar, highChar });
        }
References System.Xml.XmlWellFormedWriter.AttributeValueCache._singleStringValue, System.Xml.XmlWellFormedWriter.AttributeValueCache._stringValue, System.Xml.XmlWellFormedWriter.AttributeValueCache.AddItem(), System.Text.StringBuilder.Append(), and System.Xml.XmlWellFormedWriter.AttributeValueCache.StartComplexValue().
Referenced by System.Xml.XmlWellFormedWriter.WriteSurrogateCharEntity(), and System.Xml.XmlWellFormedWriter.WriteSurrogateCharEntityAsync().