Terraria: System.Xml.XmlWellFormedWriter.AttributeValueCache.WriteEntityRef
WriteEntityRef()
void System.Xml.XmlWellFormedWriter.AttributeValueCache.WriteEntityRef (string name) inline package
Definition at line 317 of file XmlWellFormedWriter.cs.
        {
            if (_singleStringValue != null)
            {
                StartComplexValue();
            }
            switch (name)
            {
            case "lt":
                _stringValue.Append('<');
                break;
            case "gt":
                _stringValue.Append('>');
                break;
            case "quot":
                _stringValue.Append('"');
                break;
            case "apos":
                _stringValue.Append('\'');
                break;
            case "amp":
                _stringValue.Append('&');
                break;
            default:
                _stringValue.Append('&');
                _stringValue.Append(name);
                _stringValue.Append(';');
                break;
            }
            AddItem(ItemType.EntityRef, name);
        }
References System.Xml.XmlWellFormedWriter.AttributeValueCache._singleStringValue, System.Xml.XmlWellFormedWriter.AttributeValueCache._stringValue, System.Xml.XmlWellFormedWriter.AttributeValueCache.AddItem(), System.Text.StringBuilder.Append(), and System.Xml.XmlWellFormedWriter.AttributeValueCache.StartComplexValue().
Referenced by System.Xml.XmlWellFormedWriter.WriteEntityRef(), and System.Xml.XmlWellFormedWriter.WriteEntityRefAsync().