Terraria: System.Xml.XmlWellFormedWriter.AttributeValueCache.WriteValue
WriteValue()
void System.Xml.XmlWellFormedWriter.AttributeValueCache.WriteValue (string value) inline package
Definition at line 425 of file XmlWellFormedWriter.cs.
        {
            if (_singleStringValue != null)
            {
                StartComplexValue();
            }
            _stringValue.Append(value);
            AddItem(ItemType.ValueString, value);
        }
References System.Xml.XmlWellFormedWriter.AttributeValueCache._singleStringValue, System.Xml.XmlWellFormedWriter.AttributeValueCache._stringValue, System.Xml.XmlWellFormedWriter.AttributeValueCache.AddItem(), System.Text.StringBuilder.Append(), System.Xml.XmlWellFormedWriter.AttributeValueCache.StartComplexValue(), and System.value.
Referenced by System.Xml.XmlWellFormedWriter.WriteValue(), and System.Xml.XmlWellFormedWriter.WriteValue().