Terraria: System.Xml.XmlWellFormedWriter.AttributeValueCache.WriteChars
WriteChars()
void System.Xml.XmlWellFormedWriter.AttributeValueCache.WriteChars (char[] buffer, int index, int count) inline package
Definition at line 395 of file XmlWellFormedWriter.cs.
        {
            if (_singleStringValue != null)
            {
                StartComplexValue();
            }
            _stringValue.Append(buffer, index, count);
            AddItem(ItemType.StringChars, new BufferChunk(buffer, index, count));
        }
References System.Xml.XmlWellFormedWriter.AttributeValueCache._singleStringValue, System.Xml.XmlWellFormedWriter.AttributeValueCache._stringValue, System.Xml.XmlWellFormedWriter.AttributeValueCache.AddItem(), System.Text.StringBuilder.Append(), System.buffer, System.count, System.index, and System.Xml.XmlWellFormedWriter.AttributeValueCache.StartComplexValue().
Referenced by System.Xml.XmlWellFormedWriter.WriteChars(), and System.Xml.XmlWellFormedWriter.WriteCharsAsync().