Terraria: System.Xml.XmlWellFormedWriter.AttributeValueCache.AddItem
AddItem()
void System.Xml.XmlWellFormedWriter.AttributeValueCache.AddItem (ItemType type, object data) inline private
Definition at line 588 of file XmlWellFormedWriter.cs.
        {
            int num = _lastItem + 1;
            if (_items == null)
            {
                _items = new Item[4];
            }
            else if (_items.Length == num)
            {
                Item[] array = new Item[num * 2];
                Array.Copy(_items, array, num);
                _items = array;
            }
            if (_items[num] == null)
            {
                _items[num] = new Item(type, data);
            }
            else
            {
                _items[num].Set(type, data);
            }
            _lastItem = num;
        }
References System.Xml.XmlWellFormedWriter.AttributeValueCache._items, System.Xml.XmlWellFormedWriter.AttributeValueCache._lastItem, System.array, System.Array.Copy(), System.Xml.Item, System.Xml.XmlWellFormedWriter.AttributeValueCache.Item.Set(), and System.type.
Referenced by System.Xml.XmlWellFormedWriter.AttributeValueCache.StartComplexValue(), System.Xml.XmlWellFormedWriter.AttributeValueCache.WriteCharEntity(), System.Xml.XmlWellFormedWriter.AttributeValueCache.WriteChars(), System.Xml.XmlWellFormedWriter.AttributeValueCache.WriteEntityRef(), System.Xml.XmlWellFormedWriter.AttributeValueCache.WriteRaw(), System.Xml.XmlWellFormedWriter.AttributeValueCache.WriteRaw(), System.Xml.XmlWellFormedWriter.AttributeValueCache.WriteString(), System.Xml.XmlWellFormedWriter.AttributeValueCache.WriteSurrogateCharEntity(), System.Xml.XmlWellFormedWriter.AttributeValueCache.WriteValue(), and System.Xml.XmlWellFormedWriter.AttributeValueCache.WriteWhitespace().