Terraria: System.Xml.XmlWellFormedWriter.AttributeValueCache.Trim
Trim()
void System.Xml.XmlWellFormedWriter.AttributeValueCache.Trim () inline package
Definition at line 487 of file XmlWellFormedWriter.cs.
        {
            if (_singleStringValue != null)
            {
                _singleStringValue = XmlConvert.TrimString(_singleStringValue);
                return;
            }
            string text = _stringValue.ToString();
            string text2 = XmlConvert.TrimString(text);
            if (text != text2)
            {
                _stringValue = new StringBuilder(text2);
            }
            int i;
            for (i = _firstItem; i == _firstItem && i <= _lastItem; i++)
            {
                Item item = _items[i];
                switch (item.type)
                {
                case ItemType.Whitespace:
                    _firstItem++;
                    break;
                case ItemType.String:
                case ItemType.Raw:
                case ItemType.ValueString:
                    item.data = XmlConvert.TrimStringStart((string)item.data);
                    if (((string)item.data).Length == 0)
                    {
                        _firstItem++;
                    }
                    break;
                case ItemType.StringChars:
                case ItemType.RawChars:
                {
                    BufferChunk bufferChunk = (BufferChunk)item.data;
                    int num = bufferChunk.index + bufferChunk.count;
                    while (bufferChunk.index < num && XmlCharType.IsWhiteSpace(bufferChunk.buffer[bufferChunk.index]))
                    {
                        bufferChunk.index++;
                        bufferChunk.count--;
                    }
                    if (bufferChunk.index == num)
                    {
                        _firstItem++;
                    }
                    break;
                }
                }
            }
            i = _lastItem;
            while (i == _lastItem && i >= _firstItem)
            {
                Item item2 = _items[i];
                switch (item2.type)
                {
                case ItemType.Whitespace:
                    _lastItem--;
                    break;
                case ItemType.String:
                case ItemType.Raw:
                case ItemType.ValueString:
                    item2.data = XmlConvert.TrimStringEnd((string)item2.data);
                    if (((string)item2.data).Length == 0)
                    {
                        _lastItem--;
                    }
                    break;
                case ItemType.StringChars:
                case ItemType.RawChars:
                {
                    BufferChunk bufferChunk2 = (BufferChunk)item2.data;
                    while (bufferChunk2.count > 0 && XmlCharType.IsWhiteSpace(bufferChunk2.buffer[bufferChunk2.index + bufferChunk2.count - 1]))
                    {
                        bufferChunk2.count--;
                    }
                    if (bufferChunk2.count == 0)
                    {
                        _lastItem--;
                    }
                    break;
                }
                }
                i--;
            }
        }
References System.Xml.XmlWellFormedWriter.AttributeValueCache._firstItem, System.Xml.XmlWellFormedWriter.AttributeValueCache._items, System.Xml.XmlWellFormedWriter.AttributeValueCache._lastItem, System.Xml.XmlWellFormedWriter.AttributeValueCache._singleStringValue, System.Xml.XmlWellFormedWriter.AttributeValueCache._stringValue, System.Xml.Dictionary, System.Xml.XmlCharType.IsWhiteSpace(), System.item, System.text, System.Text.StringBuilder.ToString(), System.Xml.XmlConvert.TrimString(), System.Xml.XmlConvert.TrimStringEnd(), and System.Xml.XmlConvert.TrimStringStart().
Referenced by System.Xml.XmlWellFormedWriter.WriteEndAttribute(), and System.Xml.XmlWellFormedWriter.WriteEndAttributeAsync_SepcialAtt().