Terraria: System.Xml.Xsl.Xslt.QilGenerator.VariableHelper.FinishVariables
FinishVariables()
QilNode System.Xml.Xsl.Xslt.QilGenerator.VariableHelper.FinishVariables (QilNode node, int varScope) inline
Definition at line 37 of file QilGenerator.cs.
        {
            int num = _vars.Count - varScope;
            while (num-- != 0)
            {
                node = _f.Loop(_vars.Pop(), node);
            }
            return node;
        }
References System.Xml.Xsl.Xslt.QilGenerator.VariableHelper._f, System.Xml.Xsl.Xslt.QilGenerator.VariableHelper._vars, System.Xml.Dictionary, System.Xml.Xsl.Qil.QilPatternFactory.Loop(), and System.Collections.Generic.Stack< T >.Pop().
Referenced by System.Xml.Xsl.Xslt.QilGenerator.CompileApplyTemplates(), System.Xml.Xsl.Xslt.QilGenerator.CompileCallTemplate(), and System.Xml.Xsl.Xslt.QilGenerator.CompileForEach().