Terraria: Terraria.Graphics.Light.LightMap.BlurPass
BlurPass()
void Terraria.Graphics.Light.LightMap.BlurPass () inline private
    {
        //IL_000e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0019: Expected O, but got Unknown
        //IL_0027: Unknown result type (might be due to invalid IL or missing references)
        //IL_0032: Expected O, but got Unknown
        FastParallel.For(0, Width, (ParallelForAction)delegate(int start, int end, object context)
        {
            for (int j = start; j < end; j++)
            {
                BlurLine(IndexOf(j, 0), IndexOf(j, Height - 1 - NonVisiblePadding), 1);
                BlurLine(IndexOf(j, Height - 1), IndexOf(j, NonVisiblePadding), -1);
            }
        }, (object)null);
        FastParallel.For(0, Height, (ParallelForAction)delegate(int start, int end, object context)
        {
            for (int i = start; i < end; i++)
            {
                BlurLine(IndexOf(0, i), IndexOf(Width - 1 - NonVisiblePadding, i), Height);
                BlurLine(IndexOf(Width - 1, i), IndexOf(NonVisiblePadding, i), -Height);
            }
        }, (object)null);
    }
References Terraria.Graphics.Light.LightMap.BlurLine(), ReLogic.Threading.FastParallel.For(), Terraria.Graphics.Light.LightMap.Height, Terraria.Graphics.Light.LightMap.IndexOf(), Terraria.Graphics.Light.LightMap.NonVisiblePadding, ReLogic.Threading.ParallelForAction(), and Terraria.Graphics.Light.LightMap.Width.
Referenced by Terraria.Graphics.Light.LightMap.Blur().