Terraria: System.Xml.Xsl.IlGen.XmlILTypeHelper.GetStorageType
GetStorageType()
static Type System.Xml.Xsl.IlGen.XmlILTypeHelper.GetStorageType (XmlQueryType qyTyp) inline static
Definition at line 126 of file XmlILTypeHelper.cs.
    {
        Type type;
        if (qyTyp.IsSingleton)
        {
            type = s_typeCodeToStorage[(int)qyTyp.TypeCode];
            if (!qyTyp.IsStrict && type != typeof(XPathNavigator))
            {
                return typeof(XPathItem);
            }
        }
        else
        {
            type = s_typeCodeToCachedStorage[(int)qyTyp.TypeCode];
            if (!qyTyp.IsStrict && type != typeof(IList<XPathNavigator>))
            {
                return typeof(IList<XPathItem>);
            }
        }
        return type;
    }
References System.Xml.Dictionary, System.Xml.Xsl.IlGen.XmlILTypeHelper.s_typeCodeToCachedStorage, System.Xml.Xsl.IlGen.XmlILTypeHelper.s_typeCodeToStorage, and System.type.
Referenced by System.Xml.Xsl.XmlILGenerator.CreateFunctionMetadata(), System.Xml.Xsl.XmlILGenerator.CreateGlobalValueMetadata(), System.Xml.Xsl.IlGen.XmlILVisitor.GetItemStorageType(), System.Xml.Xsl.IlGen.XmlILVisitor.GetItemStorageType(), System.Xml.Xsl.IlGen.XmlILVisitor.GetStorageType(), and System.Xml.Xsl.IlGen.XmlILVisitor.GetStorageType().