Terraria: System.Data.SqlTypes.SqlGuid.Compare
Compare()
static EComparison System.Data.SqlTypes.SqlGuid.Compare (SqlGuid x, SqlGuid y) inline static private
Definition at line 104 of file SqlGuid.cs.
    {
        for (int i = 0; i < 16; i++)
        {
            byte b = x.m_value[s_rgiGuidOrder[i]];
            byte b2 = y.m_value[s_rgiGuidOrder[i]];
            if (b != b2)
            {
                if (b >= b2)
                {
                    return EComparison.GT;
                }
                return EComparison.LT;
            }
        }
        return EComparison.EQ;
    }
References System.Xml.Dictionary, System.Data.SqlTypes.SqlGuid.m_value, and System.Data.SqlTypes.SqlGuid.s_rgiGuidOrder.
Referenced by System.Data.SqlTypes.SqlGuid.operator<(), System.Data.SqlTypes.SqlGuid.operator<=(), System.Data.SqlTypes.SqlGuid.operator==(), System.Data.SqlTypes.SqlGuid.operator>(), and System.Data.SqlTypes.SqlGuid.operator>=().