Terraria: Microsoft.Xna.Framework.MathHelper.WrapAngle
WrapAngle()
static float Microsoft.Xna.Framework.MathHelper.WrapAngle (float angle) inline static
Definition at line 87 of file MathHelper.cs.
    {
        angle = (float)Math.IEEERemainder(angle, 6.2831854820251465);
        if (angle <= -(float)Math.PI)
        {
            angle += (float)Math.PI * 2f;
        }
        else if (angle > (float)Math.PI)
        {
            angle -= (float)Math.PI * 2f;
        }
        return angle;
    }
References System.Math.IEEERemainder(), and System.Math.PI.
Referenced by Terraria.Graphics.VertexStrip.AddVertex(), Terraria.Projectile.AI_015_Flails(), Terraria.Projectile.AI_075(), Terraria.Projectile.AI_121_StardustDragon(), Terraria.Projectile.AI_140_MonkStaffT1(), Terraria.Projectile.AI_156_GetIdlePosition(), Terraria.Projectile.AI_156_Think(), Terraria.Projectile.AI_187_ShadowHand(), Terraria.Projectile.AI_195_JimsDrone(), Terraria.Utils.AngleLerp(), Terraria.Utils.AngleTowards(), Terraria.Mount.CastSuperCartLaser(), Terraria.Main.DrawNPCDirect(), Terraria.GameContent.PortalHelper.GetPortalOutingPoint(), Terraria.Projectile.HandleMovement(), Terraria.Graphics.VertexStrip.PrepareStrip(), Terraria.Graphics.VertexStrip.PrepareStripWithProceduralPadding(), and Terraria.GameContent.PortalHelper.SupportedTilesAreFine().