Terraria: Microsoft.Xna.Framework.MathHelper.Min
Min()
static float Microsoft.Xna.Framework.MathHelper.Min (float value1, float value2) inline static
Definition at line 36 of file MathHelper.cs.
    {
        return Math.Min(value1, value2);
    }
References System.Math.Min().
Referenced by Terraria.NPC.AI(), Terraria.NPC.AI_007_TownEntities(), Terraria.Projectile.AI_019_Spears(), Terraria.NPC.AI_109_DarkMage(), Terraria.NPC.AI_116_WaterStriders(), Microsoft.Xna.Framework.BoundingSphere.CreateMerged(), Microsoft.Xna.Framework.BoundingSphere.CreateMerged(), Terraria.Main.DrawProj_TrueNightsEdge(), Terraria.Main.DrawProjDirect(), Terraria.Dust.GetAlpha(), Microsoft.Xna.Framework.BoundingBox.Intersects(), Microsoft.Xna.Framework.BoundingBox.Intersects(), and Terraria.Utils.LineRectangleDistance().