Terraria: System.Collections.Concurrent.BlockingCollection.TryAddWithNoTimeValidation
TryAddWithNoTimeValidation()
bool System.Collections.Concurrent.BlockingCollection< T >.TryAddWithNoTimeValidation (T item, int millisecondsTimeout, CancellationToken cancellationToken) inline private
Definition at line 180 of file BlockingCollection.cs.
    {
        CheckDisposed();
        cancellationToken.ThrowIfCancellationRequested();
        if (IsAddingCompleted)
        {
            throw new InvalidOperationException(System.SR.BlockingCollection_Completed);
        }
        bool flag = true;
        if (_freeNodes != null)
        {
            CancellationTokenSource cancellationTokenSource = null;
            try
            {
                flag = _freeNodes.Wait(0, default(CancellationToken));
                if (!flag && millisecondsTimeout != 0)
                {
                    cancellationTokenSource = CancellationTokenSource.CreateLinkedTokenSource(cancellationToken, _producersCancellationTokenSource.Token);
                    flag = _freeNodes.Wait(millisecondsTimeout, cancellationTokenSource.Token);
                }
            }
            catch (OperationCanceledException)
            {
                cancellationToken.ThrowIfCancellationRequested();
                throw new InvalidOperationException(System.SR.BlockingCollection_Add_ConcurrentCompleteAdd);
            }
            finally
            {
                cancellationTokenSource?.Dispose();
            }
        }
        if (flag)
        {
            SpinWait spinWait = default(SpinWait);
            while (true)
            {
                int currentAdders = _currentAdders;
                if (((uint)currentAdders & 0x80000000u) != 0)
                {
                    spinWait.Reset();
                    while (_currentAdders != int.MinValue)
                    {
                        spinWait.SpinOnce();
                    }
                    throw new InvalidOperationException(System.SR.BlockingCollection_Completed);
                }
                if (Interlocked.CompareExchange(ref _currentAdders, currentAdders + 1, currentAdders) == currentAdders)
                {
                    break;
                }
                spinWait.SpinOnce(-1);
            }
            try
            {
                bool flag2 = false;
                try
                {
                    cancellationToken.ThrowIfCancellationRequested();
                    flag2 = _collection.TryAdd(item);
                }
                catch
                {
                    if (_freeNodes != null)
                    {
                        _freeNodes.Release();
                    }
                    throw;
                }
                if (!flag2)
                {
                    throw new InvalidOperationException(System.SR.BlockingCollection_Add_Failed);
                }
                _occupiedNodes.Release();
            }
            finally
            {
                Interlocked.Decrement(ref _currentAdders);
            }
        }
        return flag;
    }
References System.Collections.Concurrent.BlockingCollection< T >._collection, System.Collections.Concurrent.BlockingCollection< T >._currentAdders, System.Collections.Concurrent.BlockingCollection< T >._freeNodes, System.Collections.Concurrent.BlockingCollection< T >._occupiedNodes, System.Collections.Concurrent.BlockingCollection< T >._producersCancellationTokenSource, System.SR.BlockingCollection_Add_ConcurrentCompleteAdd, System.SR.BlockingCollection_Add_Failed, System.SR.BlockingCollection_Completed, System.cancellationToken, System.Collections.Concurrent.BlockingCollection< T >.CheckDisposed(), System.Threading.Interlocked.CompareExchange(), System.Threading.CancellationTokenSource.CreateLinkedTokenSource(), System.Threading.Interlocked.Decrement(), System.Collections.Concurrent.BlockingCollection< T >.IsAddingCompleted, System.item, System.millisecondsTimeout, System.Threading.SemaphoreSlim.Release(), System.Threading.CancellationTokenSource.Token, and System.Threading.SemaphoreSlim.Wait().
Referenced by System.Collections.Concurrent.BlockingCollection< T >.Add(), System.Collections.Concurrent.BlockingCollection< T >.Add(), System.Collections.Concurrent.BlockingCollection< T >.TryAdd(), System.Collections.Concurrent.BlockingCollection< T >.TryAdd(), System.Collections.Concurrent.BlockingCollection< T >.TryAdd(), and System.Collections.Concurrent.BlockingCollection< T >.TryAdd().