Terraria: System.Collections.Concurrent.BlockingCollection.TryTakeFromAnyCoreSlow
TryTakeFromAnyCoreSlow()
static int System.Collections.Concurrent.BlockingCollection< T >.TryTakeFromAnyCoreSlow (BlockingCollection< T >[] collections, out T item, int millisecondsTimeout, bool isTakeOperation, CancellationToken externalCancellationToken) inline static private
Definition at line 562 of file BlockingCollection.cs.
    {
        int num = millisecondsTimeout;
        uint startTime = 0u;
        if (millisecondsTimeout != -1)
        {
            startTime = (uint)Environment.TickCount;
        }
        while (millisecondsTimeout == -1 || num >= 0)
        {
            CancellationToken[] cancellationTokens;
            List<WaitHandle> handles = GetHandles(collections, externalCancellationToken, isAddOperation: false, out cancellationTokens);
            if (handles.Count == 0 && isTakeOperation)
            {
                throw new ArgumentException(System.SR.BlockingCollection_CantTakeAnyWhenAllDone, "collections");
            }
            if (handles.Count == 0)
            {
                break;
            }
            using (CancellationTokenSource cancellationTokenSource = CancellationTokenSource.CreateLinkedTokenSource(cancellationTokens))
            {
                handles.Add(cancellationTokenSource.Token.WaitHandle);
                int num2 = WaitHandle.WaitAny(handles.ToArray(), num);
                if (cancellationTokenSource.IsCancellationRequested)
                {
                    externalCancellationToken.ThrowIfCancellationRequested();
                }
                if (!cancellationTokenSource.IsCancellationRequested)
                {
                    if (num2 == 258)
                    {
                        break;
                    }
                    if (collections.Length != handles.Count - 1)
                    {
                        for (int i = 0; i < collections.Length; i++)
{
                            if (collections[i]._occupiedNodes.AvailableWaitHandle == handles[num2])
{
                                num2 = i;
                                break;
                            }
                        }
                    }
                    if (collections[num2].TryTake(out item))
                    {
                        return num2;
                    }
                }
            }
            if (millisecondsTimeout != -1)
            {
                num = UpdateTimeOut(startTime, millisecondsTimeout);
            }
        }
        item = default(T);
        return -1;
    }
References System.Collections.Concurrent.BlockingCollection< T >._occupiedNodes, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Threading.SemaphoreSlim.AvailableWaitHandle, System.SR.BlockingCollection_CantTakeAnyWhenAllDone, System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Threading.CancellationTokenSource.CreateLinkedTokenSource(), System.Collections.Concurrent.BlockingCollection< T >.GetHandles(), System.item, System.millisecondsTimeout, System.Environment.TickCount, System.Collections.Concurrent.BlockingCollection< T >.TryTake(), System.Collections.Concurrent.BlockingCollection< T >.UpdateTimeOut(), and System.Threading.WaitHandle.WaitAny().
Referenced by System.Collections.Concurrent.BlockingCollection< T >.TryTakeFromAnyCore().