Terraria: System.Collections.Concurrent.BlockingCollection.TryAddToAny
TryAddToAny() [1/4]
static int System.Collections.Concurrent.BlockingCollection< T >.TryAddToAny (BlockingCollection< T >[] collections, T item) inline static
Definition at line 384 of file BlockingCollection.cs.
    {
        return TryAddToAny(collections, item, 0, CancellationToken.None);
    }
References System.item, System.Threading.CancellationToken.None, and System.Collections.Concurrent.BlockingCollection< T >.TryAddToAny().
Referenced by System.Collections.Concurrent.BlockingCollection< T >.AddToAny(), System.Collections.Concurrent.BlockingCollection< T >.AddToAny(), and System.Collections.Concurrent.BlockingCollection< T >.TryAddToAny().