Terraria: System.Collections.Concurrent.BlockingCollection.TryAddToAnyCore
TryAddToAnyCore()
static int System.Collections.Concurrent.BlockingCollection< T >.TryAddToAnyCore (BlockingCollection< T >[] collections, T item, int millisecondsTimeout, CancellationToken externalCancellationToken) inline static private
Definition at line 407 of file BlockingCollection.cs.
    {
        ValidateCollectionsArray(collections, isAddOperation: true);
        int num = millisecondsTimeout;
        uint startTime = 0u;
        if (millisecondsTimeout != -1)
        {
            startTime = (uint)Environment.TickCount;
        }
        int num2 = TryAddToAnyFast(collections, item);
        if (num2 > -1)
        {
            return num2;
        }
        CancellationToken[] cancellationTokens;
        List<WaitHandle> handles = GetHandles(collections, externalCancellationToken, isAddOperation: true, out cancellationTokens);
        while (millisecondsTimeout == -1 || num >= 0)
        {
            num2 = -1;
            using (CancellationTokenSource cancellationTokenSource = CancellationTokenSource.CreateLinkedTokenSource(cancellationTokens))
            {
                handles.Add(cancellationTokenSource.Token.WaitHandle);
                num2 = WaitHandle.WaitAny(handles.ToArray(), num);
                handles.RemoveAt(handles.Count - 1);
                if (cancellationTokenSource.IsCancellationRequested)
                {
                    externalCancellationToken.ThrowIfCancellationRequested();
                    throw new ArgumentException(System.SR.BlockingCollection_CantAddAnyWhenCompleted, "collections");
                }
            }
            if (num2 == 258)
            {
                return -1;
            }
            if (collections[num2].TryAdd(item))
            {
                return num2;
            }
            if (millisecondsTimeout != -1)
            {
                num = UpdateTimeOut(startTime, millisecondsTimeout);
            }
        }
        return -1;
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.SR.BlockingCollection_CantAddAnyWhenCompleted, System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Threading.CancellationTokenSource.CreateLinkedTokenSource(), System.Collections.Concurrent.BlockingCollection< T >.GetHandles(), System.item, System.millisecondsTimeout, System.Environment.TickCount, System.Collections.Concurrent.BlockingCollection< T >.TryAdd(), System.Collections.Concurrent.BlockingCollection< T >.TryAddToAnyFast(), System.Collections.Concurrent.BlockingCollection< T >.UpdateTimeOut(), System.Collections.Concurrent.BlockingCollection< T >.ValidateCollectionsArray(), and System.Threading.WaitHandle.WaitAny().
Referenced by System.Collections.Concurrent.BlockingCollection< T >.TryAddToAny(), System.Collections.Concurrent.BlockingCollection< T >.TryAddToAny(), and System.Collections.Concurrent.BlockingCollection< T >.TryAddToAny().