Terraria: System.Collections.Concurrent.BlockingCollection.GetHandles
GetHandles()
static List< WaitHandle > System.Collections.Concurrent.BlockingCollection< T >.GetHandles (BlockingCollection< T >[] collections, CancellationToken externalCancellationToken, bool isAddOperation, out CancellationToken[] cancellationTokens) inline static private
Definition at line 466 of file BlockingCollection.cs.
    {
        List<WaitHandle> list = new List<WaitHandle>(collections.Length + 1);
        List<CancellationToken> list2 = new List<CancellationToken>(collections.Length + 1);
        list2.Add(externalCancellationToken);
        if (isAddOperation)
        {
            foreach (BlockingCollection<T> blockingCollection in collections)
            {
                if (blockingCollection._freeNodes != null)
                {
                    list.Add(blockingCollection._freeNodes.AvailableWaitHandle);
                    list2.Add(blockingCollection._producersCancellationTokenSource.Token);
                }
            }
        }
        else
        {
            for (int j = 0; j < collections.Length; j++)
            {
                if (!collections[j].IsCompleted)
                {
                    list.Add(collections[j]._occupiedNodes.AvailableWaitHandle);
                    list2.Add(collections[j]._consumersCancellationTokenSource.Token);
                }
            }
        }
        cancellationTokens = list2.ToArray();
        return list;
    }
References System.Collections.Concurrent.BlockingCollection< T >._consumersCancellationTokenSource, System.Collections.Concurrent.BlockingCollection< T >._occupiedNodes, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Threading.SemaphoreSlim.AvailableWaitHandle, System.Collections.Concurrent.BlockingCollection< T >.IsCompleted, System.list, and System.Threading.CancellationTokenSource.Token.
Referenced by System.Collections.Concurrent.BlockingCollection< T >.TryAddToAnyCore(), and System.Collections.Concurrent.BlockingCollection< T >.TryTakeFromAnyCoreSlow().