Terraria: System.Collections.Concurrent.BlockingCollection.TryTakeWithNoTimeValidation
TryTakeWithNoTimeValidation()
bool System.Collections.Concurrent.BlockingCollection< T >.TryTakeWithNoTimeValidation ([MaybeNullWhen(false)] out T item, int millisecondsTimeout, CancellationToken cancellationToken, CancellationTokenSource combinedTokenSource) inline private
Definition at line 303 of file BlockingCollection.cs.
    {
        CheckDisposed();
        item = default(T);
        cancellationToken.ThrowIfCancellationRequested();
        if (IsCompleted)
        {
            return false;
        }
        bool flag = false;
        CancellationTokenSource cancellationTokenSource = combinedTokenSource;
        try
        {
            flag = _occupiedNodes.Wait(0);
            if (!flag && millisecondsTimeout != 0)
            {
                if (cancellationTokenSource == null)
                {
                    cancellationTokenSource = CancellationTokenSource.CreateLinkedTokenSource(cancellationToken, _consumersCancellationTokenSource.Token);
                }
                flag = _occupiedNodes.Wait(millisecondsTimeout, cancellationTokenSource.Token);
            }
        }
        catch (OperationCanceledException)
        {
            cancellationToken.ThrowIfCancellationRequested();
            return false;
        }
        finally
        {
            if (cancellationTokenSource != null && combinedTokenSource == null)
            {
                cancellationTokenSource.Dispose();
            }
        }
        if (flag)
        {
            bool flag2 = false;
            bool flag3 = true;
            try
            {
                cancellationToken.ThrowIfCancellationRequested();
                flag2 = _collection.TryTake(out item);
                flag3 = false;
                if (!flag2)
                {
                    throw new InvalidOperationException(System.SR.BlockingCollection_Take_CollectionModified);
                }
            }
            finally
            {
                if (flag2)
                {
                    if (_freeNodes != null)
                    {
                        _freeNodes.Release();
                    }
                }
                else if (flag3)
                {
                    _occupiedNodes.Release();
                }
                if (IsCompleted)
                {
                    CancelWaitingConsumers();
                }
            }
        }
        return flag;
    }
References System.Collections.Concurrent.BlockingCollection< T >._collection, System.Collections.Concurrent.BlockingCollection< T >._consumersCancellationTokenSource, System.Collections.Concurrent.BlockingCollection< T >._freeNodes, System.Collections.Concurrent.BlockingCollection< T >._occupiedNodes, System.SR.BlockingCollection_Take_CollectionModified, System.cancellationToken, System.Collections.Concurrent.BlockingCollection< T >.CancelWaitingConsumers(), System.Collections.Concurrent.BlockingCollection< T >.CheckDisposed(), System.Threading.CancellationTokenSource.CreateLinkedTokenSource(), System.Collections.Concurrent.BlockingCollection< T >.IsCompleted, System.item, System.millisecondsTimeout, System.Threading.SemaphoreSlim.Release(), System.Threading.CancellationTokenSource.Token, and System.Threading.SemaphoreSlim.Wait().
Referenced by System.Collections.Concurrent.BlockingCollection< T >.GetConsumingEnumerable(), System.Collections.Concurrent.BlockingCollection< T >.TryTake(), System.Collections.Concurrent.BlockingCollection< T >.TryTake(), and System.Collections.Concurrent.BlockingCollection< T >.TryTake().