Terraria: System.Collections.Concurrent.BlockingCollection.TryTakeFromAnyCore
TryTakeFromAnyCore()
static int System.Collections.Concurrent.BlockingCollection< T >.TryTakeFromAnyCore (BlockingCollection< T >[] collections, out T item, int millisecondsTimeout, bool isTakeOperation, CancellationToken externalCancellationToken) inline static private
Definition at line 549 of file BlockingCollection.cs.
    {
        ValidateCollectionsArray(collections, isAddOperation: false);
        for (int i = 0; i < collections.Length; i++)
        {
            if (!collections[i].IsCompleted && collections[i]._occupiedNodes.CurrentCount > 0 && collections[i].TryTake(out item))
            {
                return i;
            }
        }
        return TryTakeFromAnyCoreSlow(collections, out item, millisecondsTimeout, isTakeOperation, externalCancellationToken);
    }
References System.Collections.Concurrent.BlockingCollection< T >._occupiedNodes, System.Threading.SemaphoreSlim.CurrentCount, System.Collections.Concurrent.BlockingCollection< T >.IsCompleted, System.item, System.millisecondsTimeout, System.Collections.Concurrent.BlockingCollection< T >.TryTakeFromAnyCoreSlow(), and System.Collections.Concurrent.BlockingCollection< T >.ValidateCollectionsArray().
Referenced by System.Collections.Concurrent.BlockingCollection< T >.TakeFromAny(), System.Collections.Concurrent.BlockingCollection< T >.TryTakeFromAny(), System.Collections.Concurrent.BlockingCollection< T >.TryTakeFromAny(), and System.Collections.Concurrent.BlockingCollection< T >.TryTakeFromAny().