Terraria: System.Diagnostics.StackTraceSymbols.TryGetReader
TryGetReader()
MetadataReader System.Diagnostics.StackTraceSymbols.TryGetReader (Assembly assembly, string assemblyPath, IntPtr loadedPeAddress, int loadedPeSize, bool isFileLayout, IntPtr inMemoryPdbAddress, int inMemoryPdbSize) inline private
Definition at line 72 of file StackTraceSymbols.cs.
    {
        if ((loadedPeAddress == IntPtr.Zero || assemblyPath == null) && inMemoryPdbAddress == IntPtr.Zero)
        {
            return null;
        }
        return _metadataCache.GetValue(assembly, (Assembly assembly) => (!(inMemoryPdbAddress != IntPtr.Zero)) ? TryOpenReaderFromAssemblyFile(assemblyPath, loadedPeAddress, loadedPeSize, isFileLayout) : TryOpenReaderForInMemoryPdb(inMemoryPdbAddress, inMemoryPdbSize))?.GetMetadataReader();
    }
References System.Diagnostics.StackTraceSymbols._metadataCache, System.Runtime.CompilerServices.ConditionalWeakTable< TKey, TValue >.GetValue(), System.Diagnostics.StackTraceSymbols.TryOpenReaderForInMemoryPdb(), System.Diagnostics.StackTraceSymbols.TryOpenReaderFromAssemblyFile(), and System.IntPtr.Zero.
Referenced by System.Diagnostics.StackTraceSymbols.GetSourceLineInfo().