Terraria: System.Diagnostics.StackTraceSymbols.TryOpenFile
TryOpenFile()
static Stream System.Diagnostics.StackTraceSymbols.TryOpenFile (string path) inline static private
Definition at line 130 of file StackTraceSymbols.cs.
    {
        if (!File.Exists(path))
        {
            return null;
        }
        try
        {
            return new FileStream(path, FileMode.Open, FileAccess.Read, FileShare.Read | FileShare.Delete);
        }
        catch
        {
            return null;
        }
    }
References System.IO.File.Exists().
Referenced by System.Diagnostics.StackTraceSymbols.TryGetPEReader(), and System.Diagnostics.StackTraceSymbols.TryOpenReaderFromAssemblyFile().