Terraria: LegacyPlayerRenderer.DrawPlayerFull
DrawPlayerFull()
void LegacyPlayerRenderer.DrawPlayerFull (Camera camera, Player drawPlayer) inline private
     {
         SpriteBatch spriteBatch = camera.SpriteBatch;
         SamplerState samplerState = camera.Sampler;
         if (drawPlayer.mount.Active && drawPlayer.fullRotation != 0f)
         {
             samplerState = MountedSamplerState;
         }
         spriteBatch.Begin(SpriteSortMode.Immediate, BlendState.AlphaBlend, samplerState, DepthStencilState.None, camera.Rasterizer, null, camera.GameViewMatrix.TransformationMatrix);
         if (Main.gamePaused)
         {
             drawPlayer.PlayerFrame();
         }
         if (drawPlayer.ghost)
         {
             for (int i = 0; i < 3; i++)
             {
                 Vector2 vector = drawPlayer.shadowPos[i];
                 vector = drawPlayer.position - drawPlayer.velocity * (2 + i * 2);
                 DrawGhost(camera, drawPlayer, vector, 0.5f + 0.2f * (float)i);
             }
             DrawGhost(camera, drawPlayer, drawPlayer.position);
         }
         else
         {
             if (drawPlayer.inventory[drawPlayer.selectedItem].flame || drawPlayer.head == 137 || drawPlayer.wings == 22)
             {
                 drawPlayer.itemFlameCount--;
                 if (drawPlayer.itemFlameCount <= 0)
                 {
                     drawPlayer.itemFlameCount = 5;
                     for (int j = 0; j < 7; j++)
                     {
                         drawPlayer.itemFlamePos[j].X = (float)Main.rand.Next(-10, 11) * 0.15f;
                         drawPlayer.itemFlamePos[j].Y = (float)Main.rand.Next(-10, 1) * 0.35f;
                     }
                 }
             }
             if (drawPlayer.armorEffectDrawShadowEOCShield)
             {
                 int num = drawPlayer.eocDash / 4;
                 if (num > 3)
                 {
                     num = 3;
                 }
                 for (int k = 0; k < num; k++)
                 {
                     DrawPlayer(camera, drawPlayer, drawPlayer.shadowPos[k], drawPlayer.shadowRotation[k], drawPlayer.shadowOrigin[k], 0.5f + 0.2f * (float)k);
                 }
             }
             Vector2 position = default(Vector2);
             if (drawPlayer.invis)
             {
                 drawPlayer.armorEffectDrawOutlines = false;
                 drawPlayer.armorEffectDrawShadow = false;
                 drawPlayer.armorEffectDrawShadowSubtle = false;
                 position = drawPlayer.position;
                 if (drawPlayer.aggro <= -750)
                 {
                     DrawPlayer(camera, drawPlayer, position, drawPlayer.fullRotation, drawPlayer.fullRotationOrigin, 1f);
                 }
                 else
                 {
                     drawPlayer.invis = false;
                     DrawPlayer(camera, drawPlayer, position, drawPlayer.fullRotation, drawPlayer.fullRotationOrigin);
                     drawPlayer.invis = true;
                 }
             }
             if (drawPlayer.armorEffectDrawOutlines)
             {
                 _ = drawPlayer.position;
                 if (!Main.gamePaused)
                 {
                     drawPlayer.ghostFade += drawPlayer.ghostDir * 0.075f;
                 }
                 if ((double)drawPlayer.ghostFade < 0.1)
                 {
                     drawPlayer.ghostDir = 1f;
                     drawPlayer.ghostFade = 0.1f;
                 }
                 else if ((double)drawPlayer.ghostFade > 0.9)
                 {
                     drawPlayer.ghostDir = -1f;
                     drawPlayer.ghostFade = 0.9f;
                 }
                 float num2 = drawPlayer.ghostFade * 5f;
                 for (int l = 0; l < 4; l++)
                 {
                     float num3;
                     float num4;
                     switch (l)
                     {
                     default:
                         num3 = num2;
                         num4 = 0f;
                         break;
                     case 1:
                         num3 = 0f - num2;
                         num4 = 0f;
                         break;
                     case 2:
                         num3 = 0f;
                         num4 = num2;
                         break;
                     case 3:
                         num3 = 0f;
                         num4 = 0f - num2;
                         break;
                     }
                     position = new Vector2(drawPlayer.position.X + num3, drawPlayer.position.Y + drawPlayer.gfxOffY + num4);
                     DrawPlayer(camera, drawPlayer, position, drawPlayer.fullRotation, drawPlayer.fullRotationOrigin, drawPlayer.ghostFade);
                 }
             }
             if (drawPlayer.armorEffectDrawOutlinesForbidden)
             {
                 _ = drawPlayer.position;
                 if (!Main.gamePaused)
                 {
                     drawPlayer.ghostFade += drawPlayer.ghostDir * 0.025f;
                 }
                 if ((double)drawPlayer.ghostFade < 0.1)
                 {
                     drawPlayer.ghostDir = 1f;
                     drawPlayer.ghostFade = 0.1f;
                 }
                 else if ((double)drawPlayer.ghostFade > 0.9)
                 {
                     drawPlayer.ghostDir = -1f;
                     drawPlayer.ghostFade = 0.9f;
                 }
                 float num5 = drawPlayer.ghostFade * 5f;
                 for (int m = 0; m < 4; m++)
                 {
                     float num6;
                     float num7;
                     switch (m)
                     {
                     default:
                         num6 = num5;
                         num7 = 0f;
                         break;
                     case 1:
                         num6 = 0f - num5;
                         num7 = 0f;
                         break;
                     case 2:
                         num6 = 0f;
                         num7 = num5;
                         break;
                     case 3:
                         num6 = 0f;
                         num7 = 0f - num5;
                         break;
                     }
                     position = new Vector2(drawPlayer.position.X + num6, drawPlayer.position.Y + drawPlayer.gfxOffY + num7);
                     DrawPlayer(camera, drawPlayer, position, drawPlayer.fullRotation, drawPlayer.fullRotationOrigin, drawPlayer.ghostFade);
                 }
             }
             if (drawPlayer.armorEffectDrawShadowBasilisk)
             {
                 int num8 = (int)(drawPlayer.basiliskCharge * 3f);
                 for (int n = 0; n < num8; n++)
                 {
                     DrawPlayer(camera, drawPlayer, drawPlayer.shadowPos[n], drawPlayer.shadowRotation[n], drawPlayer.shadowOrigin[n], 0.5f + 0.2f * (float)n);
                 }
             }
             else if (drawPlayer.armorEffectDrawShadow)
             {
                 for (int num9 = 0; num9 < 3; num9++)
                 {
                     DrawPlayer(camera, drawPlayer, drawPlayer.shadowPos[num9], drawPlayer.shadowRotation[num9], drawPlayer.shadowOrigin[num9], 0.5f + 0.2f * (float)num9);
                 }
             }
             if (drawPlayer.armorEffectDrawShadowLokis)
             {
                 for (int num10 = 0; num10 < 3; num10++)
                 {
                     DrawPlayer(camera, drawPlayer, Vector2.Lerp(drawPlayer.shadowPos[num10], drawPlayer.position + new Vector2(0f, drawPlayer.gfxOffY), 0.5f), drawPlayer.shadowRotation[num10], drawPlayer.shadowOrigin[num10], MathHelper.Lerp(1f, 0.5f + 0.2f * (float)num10, 0.5f));
                 }
             }
             if (drawPlayer.armorEffectDrawShadowSubtle)
             {
                 for (int num11 = 0; num11 < 4; num11++)
                 {
                     position.X = drawPlayer.position.X + (float)Main.rand.Next(-20, 21) * 0.1f;
                     position.Y = drawPlayer.position.Y + (float)Main.rand.Next(-20, 21) * 0.1f + drawPlayer.gfxOffY;
                     DrawPlayer(camera, drawPlayer, position, drawPlayer.fullRotation, drawPlayer.fullRotationOrigin, 0.9f);
                 }
             }
             if (drawPlayer.shadowDodge)
             {
                 drawPlayer.shadowDodgeCount += 1f;
                 if (drawPlayer.shadowDodgeCount > 30f)
                 {
                     drawPlayer.shadowDodgeCount = 30f;
                 }
             }
             else
             {
                 drawPlayer.shadowDodgeCount -= 1f;
                 if (drawPlayer.shadowDodgeCount < 0f)
                 {
                     drawPlayer.shadowDodgeCount = 0f;
                 }
             }
             if (drawPlayer.shadowDodgeCount > 0f)
             {
                 _ = drawPlayer.position;
                 position.X = drawPlayer.position.X + drawPlayer.shadowDodgeCount;
                 position.Y = drawPlayer.position.Y + drawPlayer.gfxOffY;
                 DrawPlayer(camera, drawPlayer, position, drawPlayer.fullRotation, drawPlayer.fullRotationOrigin, 0.5f + (float)Main.rand.Next(-10, 11) * 0.005f);
                 position.X = drawPlayer.position.X - drawPlayer.shadowDodgeCount;
                 DrawPlayer(camera, drawPlayer, position, drawPlayer.fullRotation, drawPlayer.fullRotationOrigin, 0.5f + (float)Main.rand.Next(-10, 11) * 0.005f);
             }
             if (drawPlayer.brainOfConfusionDodgeAnimationCounter > 0)
             {
                 Vector2 vector2 = drawPlayer.position + new Vector2(0f, drawPlayer.gfxOffY);
                 float lerpValue = Utils.GetLerpValue(300f, 270f, drawPlayer.brainOfConfusionDodgeAnimationCounter);
                 float y = MathHelper.Lerp(2f, 120f, lerpValue);
                 if (lerpValue >= 0f && lerpValue <= 1f)
                 {
                     for (float num12 = 0f; num12 < (float)Math.PI * 2f; num12 += (float)Math.PI / 3f)
                     {
                         position = vector2 + new Vector2(0f, y).RotatedBy((float)Math.PI * 2f * lerpValue * 0.5f + num12);
                         DrawPlayer(camera, drawPlayer, position, drawPlayer.fullRotation, drawPlayer.fullRotationOrigin, lerpValue);
                     }
                 }
             }
             position = drawPlayer.position;
             position.Y += drawPlayer.gfxOffY;
             if (drawPlayer.stoned)
             {
                 DrawPlayerStoned(camera, drawPlayer, position);
             }
             else if (!drawPlayer.invis)
             {
                 DrawPlayer(camera, drawPlayer, position, drawPlayer.fullRotation, drawPlayer.fullRotationOrigin);
             }
         }
         spriteBatch.End();
     }
References Mount.Active, Player.aggro, Player.armorEffectDrawOutlines, Player.armorEffectDrawOutlinesForbidden, Player.armorEffectDrawShadow, Player.armorEffectDrawShadowBasilisk, Player.armorEffectDrawShadowEOCShield, Player.armorEffectDrawShadowLokis, Player.armorEffectDrawShadowSubtle, Player.basiliskCharge, Player.brainOfConfusionDodgeAnimationCounter, DrawGhost(), DrawPlayer(), DrawPlayerStoned(), Player.eocDash, Item.flame, Player.fullRotation, Player.fullRotationOrigin, Main.gamePaused, Camera.GameViewMatrix, Utils.GetLerpValue(), Player.gfxOffY, Player.ghost, Player.ghostDir, Player.ghostFade, Player.head, Player.inventory, Player.invis, Player.itemFlameCount, Player.itemFlamePos, Player.mount, MountedSamplerState, UnifiedRandom.Next(), Player.PlayerFrame(), Entity.position, Main.rand, Camera.Rasterizer, Camera.Sampler, Player.selectedItem, Player.shadowDodge, Player.shadowDodgeCount, Player.shadowOrigin, Player.shadowPos, Player.shadowRotation, Camera.SpriteBatch, Player.stoned, SpriteViewMatrix.TransformationMatrix, Entity.velocity, and Player.wings.
Referenced by DrawPlayers().