Terraria: Terraria.PopupText.FindNextItemTextSlot
FindNextItemTextSlot()
static int Terraria.PopupText.FindNextItemTextSlot () inline static private
    {
        int num = -1;
        for (int i = 0; i < 20; i++)
        {
            if (!Main.popupText[i].active)
            {
                num = i;
                break;
            }
        }
        if (num == -1)
        {
            double num2 = Main.bottomWorld;
            for (int j = 0; j < 20; j++)
            {
                if (num2 > (double)Main.popupText[j].position.Y)
                {
                    num = j;
                    num2 = Main.popupText[j].position.Y;
                }
            }
        }
        return num;
    }
References Terraria.PopupText.active, Terraria.Main.bottomWorld, Terraria.Main.popupText, and Terraria.PopupText.position.
Referenced by Terraria.PopupText.NewText(), Terraria.PopupText.NewText(), and Terraria.PopupText.NewText().