Terraria: Terraria.PopupText.NewText
NewText() [2/3]
static int Terraria.PopupText.NewText (PopupTextContext context, int npcNetID, Vector2 position, bool stay5TimesLonger) inline static
Definition at line 125 of file PopupText.cs.
    {
        if (!Main.showItemText)
        {
            return -1;
        }
        if (npcNetID == 0)
        {
            return -1;
        }
        if (Main.netMode == 2)
        {
            return -1;
        }
        int num = FindNextItemTextSlot();
        if (num >= 0)
        {
            NPC nPC = new NPC();
            nPC.SetDefaults(npcNetID);
            string typeName = nPC.TypeName;
            Vector2 vector = FontAssets.MouseText.Value.MeasureString(typeName);
            PopupText popupText = Main.popupText[num];
            ResetText(popupText);
            popupText.active = true;
            popupText.position = position - vector / 2f;
            popupText.name = typeName;
            popupText.stack = 1L;
            popupText.velocity.Y = -7f;
            popupText.lifeTime = 60;
            popupText.context = context;
            if (stay5TimesLonger)
            {
                popupText.lifeTime *= 5;
            }
            popupText.npcNetID = npcNetID;
            popupText.color = Color.White;
            if (context == PopupTextContext.SonarAlert)
            {
                popupText.color = Color.Lerp(Color.White, Color.Crimson, 0.5f);
            }
        }
        return num;
    }
References Terraria.PopupText.context, Microsoft.Xna.Framework.Color.Crimson, Terraria.PopupText.FindNextItemTextSlot(), System.L, Microsoft.Xna.Framework.Color.Lerp(), Terraria.GameContent.FontAssets.MouseText, Terraria.Main.netMode, Terraria.PopupText.npcNetID, Terraria.Main.popupText, Terraria.PopupText.position, Terraria.PopupText.ResetText(), Terraria.NPC.SetDefaults(), Terraria.Main.showItemText, Terraria.NPC.TypeName, and Microsoft.Xna.Framework.Color.White.