Terraria: System.Net.WebSockets.Compression.WebSocketInflater.CreateInflater
CreateInflater()
ZLibNative.ZLibStreamHandle System.Net.WebSockets.Compression.WebSocketInflater.CreateInflater () inline private
Definition at line 200 of file WebSocketInflater.cs.
    {
        ZLibNative.ErrorCode errorCode;
        ZLibNative.ZLibStreamHandle zLibStreamHandle;
        try
        {
            errorCode = ZLibNative.CreateZLibStreamForInflate(out zLibStreamHandle, _windowBits);
        }
        catch (Exception innerException)
        {
            throw new WebSocketException(System.SR.ZLibErrorDLLLoadError, innerException);
        }
        if (errorCode == ZLibNative.ErrorCode.Ok)
        {
            return zLibStreamHandle;
        }
        zLibStreamHandle.Dispose();
        string message = ((errorCode == ZLibNative.ErrorCode.MemError) ? System.SR.ZLibErrorNotEnoughMemory : string.Format(System.SR.ZLibErrorUnexpected, (int)errorCode));
        throw new WebSocketException(message);
    }
References System.Net.WebSockets.Compression.WebSocketInflater._windowBits, System.IO.Compression.ZLibNative.CreateZLibStreamForInflate(), System.Runtime.InteropServices.SafeHandle.Dispose(), System.SR.ZLibErrorDLLLoadError, System.SR.ZLibErrorNotEnoughMemory, and System.SR.ZLibErrorUnexpected.
Referenced by System.Net.WebSockets.Compression.WebSocketInflater.Inflate().