Terraria: System.Net.WebSockets.Compression.WebSocketInflater.Inflate
Inflate() [1/2]
unsafe bool System.Net.WebSockets.Compression.WebSocketInflater.Inflate (Span< byte > output, out int written) inline
Definition at line 87 of file WebSocketInflater.cs.
    {
        if (_stream == null)
        {
            _stream = CreateInflater();
        }
        if (_available > 0 && output.Length > 0)
        {
            int num;
            fixed (byte* ptr = _buffer)
            {
                _stream.NextIn = (IntPtr)(ptr + _position);
                _stream.AvailIn = (uint)_available;
                written = Inflate(_stream, output, ZLibNative.FlushCode.NoFlush);
                num = _available - (int)_stream.AvailIn;
            }
            _position += num;
            _available -= num;
        }
        else
        {
            written = 0;
        }
        if (_available == 0)
        {
            ReleaseBuffer();
            if (!_endOfMessage)
            {
                return true;
            }
            return Finish(output, ref written);
        }
        return false;
    }
References System.Net.WebSockets.Compression.WebSocketInflater._available, System.Net.WebSockets.Compression.WebSocketInflater._buffer, System.Net.WebSockets.Compression.WebSocketInflater._endOfMessage, System.Net.WebSockets.Compression.WebSocketInflater._position, System.Net.WebSockets.Compression.WebSocketInflater._stream, System.Net.WebSockets.Compression.WebSocketInflater.CreateInflater(), System.IO.Compression.Finish, System.Net.WebSockets.Compression.WebSocketInflater.Inflate(), System.Span< T >.Length, and System.Net.WebSockets.Compression.WebSocketInflater.ReleaseBuffer().
Referenced by System.Net.WebSockets.Compression.WebSocketInflater.Finish(), System.Net.WebSockets.Compression.WebSocketInflater.Inflate(), System.Net.WebSockets.Compression.WebSocketInflater.IsFinished(), and System.Net.WebSockets.ManagedWebSocket._003CReceiveAsyncPrivate_003Ed__63< TResult >.MoveNext().