Terraria: System.Data.Common.SqlInt16Storage.Aggregate
Aggregate()
override object System.Data.Common.SqlInt16Storage.Aggregate (int[] records, AggregateType kind) inline virtual
Reimplemented from System.Data.Common.DataStorage.
Definition at line 19 of file SqlInt16Storage.cs.
    {
        bool flag = false;
        try
        {
            switch (kind)
            {
            case AggregateType.Sum:
            {
                SqlInt64 sqlInt2 = 0L;
                foreach (int num3 in records)
                {
                    if (!IsNull(num3))
                    {
                        sqlInt2 += (SqlInt64)_values[num3];
                        flag = true;
                    }
                }
                if (flag)
                {
                    return sqlInt2;
                }
                return _nullValue;
            }
            case AggregateType.Mean:
            {
                SqlInt64 sqlInt3 = 0L;
                int num5 = 0;
                foreach (int num6 in records)
                {
                    if (!IsNull(num6))
                    {
                        sqlInt3 += _values[num6].ToSqlInt64();
                        num5++;
                        flag = true;
                    }
                }
                if (flag)
                {
                    SqlInt16 sqlInt4 = (short)0;
                    sqlInt4 = (sqlInt3 / num5).ToSqlInt16();
                    return sqlInt4;
                }
                return _nullValue;
            }
            case AggregateType.Var:
            case AggregateType.StDev:
            {
                int num = 0;
                SqlDouble sqlDouble = 0.0;
                SqlDouble sqlDouble2 = 0.0;
                SqlDouble sqlDouble3 = 0.0;
                SqlDouble sqlDouble4 = 0.0;
                foreach (int num4 in records)
                {
                    if (!IsNull(num4))
                    {
                        sqlDouble3 += _values[num4].ToSqlDouble();
                        sqlDouble4 += _values[num4].ToSqlDouble() * _values[num4].ToSqlDouble();
                        num++;
                    }
                }
                if (num > 1)
                {
                    sqlDouble = num * sqlDouble4 - sqlDouble3 * sqlDouble3;
                    sqlDouble2 = sqlDouble / (sqlDouble3 * sqlDouble3);
                    if (sqlDouble2 < 1E-15 || sqlDouble < 0.0)
                    {
                        sqlDouble = 0.0;
                    }
                    else
                    {
                        sqlDouble /= (SqlDouble)(num * (num - 1));
                    }
                    if (kind == AggregateType.StDev)
                    {
                        return Math.Sqrt(sqlDouble.Value);
                    }
                    return sqlDouble;
                }
                return _nullValue;
            }
            case AggregateType.Min:
            {
                SqlInt16 sqlInt = SqlInt16.MaxValue;
                foreach (int num2 in records)
                {
                    if (!IsNull(num2))
                    {
                        if (SqlInt16.LessThan(_values[num2], sqlInt).IsTrue)
{
                            sqlInt = _values[num2];
                        }
                        flag = true;
                    }
                }
                if (flag)
                {
                    return sqlInt;
                }
                return _nullValue;
            }
            case AggregateType.Max:
            {
                SqlInt16 sqlInt5 = SqlInt16.MinValue;
                foreach (int num7 in records)
                {
                    if (!IsNull(num7))
                    {
                        if (SqlInt16.GreaterThan(_values[num7], sqlInt5).IsTrue)
{
                            sqlInt5 = _values[num7];
                        }
                        flag = true;
                    }
                }
                if (flag)
                {
                    return sqlInt5;
                }
                return _nullValue;
            }
            case AggregateType.First:
                if (records.Length != 0)
                {
                    return _values[records[0]];
                }
                return null;
            case AggregateType.Count:
            {
                int num = 0;
                for (int i = 0; i < records.Length; i++)
                {
                    if (!IsNull(records[i]))
                    {
                        num++;
                    }
                }
                return num;
            }
            }
        }
        catch (OverflowException)
        {
            throw ExprException.Overflow(typeof(SqlInt16));
        }
        throw ExceptionBuilder.AggregateException(kind, _dataType);
    }
References System.Data.Common.DataStorage._dataType, System.Data.Common.DataStorage._nullValue, System.Data.Common.SqlInt16Storage._values, System.Data.ExceptionBuilder.AggregateException(), System.Xml.Dictionary, System.E, System.Data.SqlTypes.SqlInt16.GreaterThan(), System.Data.IsNull, System.L, System.Data.SqlTypes.SqlInt16.LessThan(), System.Data.SqlTypes.SqlInt16.MaxValue, System.Data.SqlTypes.SqlInt16.MinValue, System.Data.ExprException.Overflow(), System.Data.Common.SqlDouble, System.Data.Common.SqlInt64, System.Math.Sqrt(), System.Data.SqlTypes.SqlInt16.ToSqlDouble(), and System.Data.SqlTypes.SqlInt16.ToSqlInt64().