Terraria: Terraria.ID.ProjectileID.Sets.IsAGolfBall
IsAGolfBall
bool [] Terraria.ID.ProjectileID.Sets.IsAGolfBall = Factory.CreateBoolSet(false, 721, 739, 740, 741, 742, 743, 744, 745, 746, 747, 748, 749, 750, 751, 752) static
Referenced by Terraria.Projectile.AI_150_GolfClubHelper(), Terraria.Projectile.CanCutTiles(), Terraria.Main.DrawProjDirect(), Terraria.GameContent.Golf.GolfHelper.FindGolfBallForHelper(), Terraria.GameContent.Golf.GolfState.GetLastHitBall(), Terraria.Player.GetPreferredGolfBallToUse(), Terraria.Item.IsAGolfingItem(), Terraria.Player.ItemCheck_Shoot(), Terraria.Projectile.NewProjectile(), Terraria.Player.TileInteractionsUse(), Terraria.Player.TryPlacingAGolfBallNearANearbyTee(), Terraria.Projectile.Update(), and Terraria.Projectile.UpdatePosition().