using System;
using System.Diagnostics;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.Versioning;
using System.Security;
using System.Security.Permissions;
using System.Transactions;

[assembly: CLSCompliant(true)]
[assembly: AssemblyDefaultAlias("System.Transactions")]
[assembly: AssemblyMetadata(".NETFrameworkAssembly", "")]
[assembly: AssemblyMetadata("Serviceable", "True")]
[assembly: AssemblyMetadata("PreferInbox", "True")]
[assembly: AssemblyMetadata("IsTrimmable", "True")]
[assembly: AssemblyCompany("Microsoft Corporation")]
[assembly: AssemblyCopyright("© Microsoft Corporation. All rights reserved.")]
[assembly: AssemblyDescription("System.Transactions")]
[assembly: AssemblyFileVersion("6.0.21.52210")]
[assembly: AssemblyInformationalVersion("6.0.0+4822e3c3aa77eb82b2fb33c9321f923cf11ddde6")]
[assembly: AssemblyProduct("Microsoft® .NET")]
[assembly: AssemblyTitle("System.Transactions")]
[assembly: AssemblyMetadata("RepositoryUrl", "https://github.com/dotnet/runtime")]
[assembly: AssemblyVersion("4.0.0.0")]
[assembly: TypeForwardedTo(typeof(CommittableTransaction))]
[assembly: TypeForwardedTo(typeof(DependentCloneOption))]
[assembly: TypeForwardedTo(typeof(DependentTransaction))]
[assembly: TypeForwardedTo(typeof(DistributedTransactionPermission))]
[assembly: TypeForwardedTo(typeof(DistributedTransactionPermissionAttribute))]
[assembly: TypeForwardedTo(typeof(Enlistment))]
[assembly: TypeForwardedTo(typeof(EnlistmentOptions))]
[assembly: TypeForwardedTo(typeof(EnterpriseServicesInteropOption))]
[assembly: TypeForwardedTo(typeof(HostCurrentTransactionCallback))]
[assembly: TypeForwardedTo(typeof(IDtcTransaction))]
[assembly: TypeForwardedTo(typeof(IEnlistmentNotification))]
[assembly: TypeForwardedTo(typeof(IPromotableSinglePhaseNotification))]
[assembly: TypeForwardedTo(typeof(ISimpleTransactionSuperior))]
[assembly: TypeForwardedTo(typeof(ISinglePhaseNotification))]
[assembly: TypeForwardedTo(typeof(IsolationLevel))]
[assembly: TypeForwardedTo(typeof(ITransactionPromoter))]
[assembly: TypeForwardedTo(typeof(PreparingEnlistment))]
[assembly: TypeForwardedTo(typeof(SinglePhaseEnlistment))]
[assembly: TypeForwardedTo(typeof(SubordinateTransaction))]
[assembly: TypeForwardedTo(typeof(Transaction))]
[assembly: TypeForwardedTo(typeof(TransactionAbortedException))]
[assembly: TypeForwardedTo(typeof(TransactionCompletedEventHandler))]
[assembly: TypeForwardedTo(typeof(TransactionEventArgs))]
[assembly: TypeForwardedTo(typeof(TransactionException))]
[assembly: TypeForwardedTo(typeof(TransactionInDoubtException))]
[assembly: TypeForwardedTo(typeof(TransactionInformation))]
[assembly: TypeForwardedTo(typeof(TransactionInterop))]
[assembly: TypeForwardedTo(typeof(TransactionManager))]
[assembly: TypeForwardedTo(typeof(TransactionManagerCommunicationException))]
[assembly: TypeForwardedTo(typeof(TransactionOptions))]
[assembly: TypeForwardedTo(typeof(TransactionPromotionException))]
[assembly: TypeForwardedTo(typeof(TransactionScope))]
[assembly: TypeForwardedTo(typeof(TransactionScopeAsyncFlowOption))]
[assembly: TypeForwardedTo(typeof(TransactionScopeOption))]
[assembly: TypeForwardedTo(typeof(TransactionStartedEventHandler))]
[assembly: TypeForwardedTo(typeof(TransactionStatus))]
[module: SkipLocalsInit]
