Terraria: System.Linq.Expressions.Compiler.BoundConstants.EmitConstant
EmitConstant()
void System.Linq.Expressions.Compiler.BoundConstants.EmitConstant (LambdaCompiler lc, object value, Type type) inline package
Definition at line 71 of file BoundConstants.cs.
    {
        if (_cache.TryGetValue(new TypedConstant(value, type), out var value2))
        {
            lc.IL.Emit(OpCodes.Ldloc, value2);
            return;
        }
        EmitConstantsArray(lc);
        EmitConstantFromArray(lc, value, type);
    }
References System.Linq.Expressions.Compiler.BoundConstants._cache, System.Linq.Expressions.Compiler.BoundConstants.EmitConstantFromArray(), System.Linq.Expressions.Compiler.BoundConstants.EmitConstantsArray(), System.Reflection.Emit.OpCodes.Ldloc, System.Collections.Generic.Dictionary< TKey, TValue >.TryGetValue(), System.type, and System.value.
Referenced by System.Linq.Expressions.Compiler.LambdaCompiler.EmitClosureCreation(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitConstant(), and System.Linq.Expressions.Compiler.LambdaCompiler.EmitDelegateConstruction().