Terraria: System.Linq.Expressions.Compiler.BoundConstants.EmitConstantFromArray
EmitConstantFromArray()
void System.Linq.Expressions.Compiler.BoundConstants.EmitConstantFromArray (LambdaCompiler lc, object value, Type type) inline private
Definition at line 125 of file BoundConstants.cs.
    {
        if (!_indexes.TryGetValue(value, out var value2))
        {
            _indexes.Add(value, value2 = _values.Count);
            _values.Add(value);
        }
        lc.IL.EmitPrimitive(value2);
        lc.IL.Emit(OpCodes.Ldelem_Ref);
        if (type.IsValueType)
        {
            lc.IL.Emit(OpCodes.Unbox_Any, type);
        }
        else if (type != typeof(object))
        {
            lc.IL.Emit(OpCodes.Castclass, type);
        }
    }
References System.Linq.Expressions.Compiler.BoundConstants._indexes, System.Linq.Expressions.Compiler.BoundConstants._values, System.Collections.Generic.List< T >.Add(), System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Reflection.Emit.OpCodes.Castclass, System.Collections.Generic.List< T >.Count, System.Reflection.Emit.OpCodes.Ldelem_Ref, System.Collections.Generic.Dictionary< TKey, TValue >.TryGetValue(), System.type, System.Reflection.Emit.OpCodes.Unbox_Any, and System.value.
Referenced by System.Linq.Expressions.Compiler.BoundConstants.EmitCacheConstants(), and System.Linq.Expressions.Compiler.BoundConstants.EmitConstant().