Terraria: System.Linq.Expressions.Compiler.BoundConstants.EmitCacheConstants
EmitCacheConstants()
void System.Linq.Expressions.Compiler.BoundConstants.EmitCacheConstants (LambdaCompiler lc) inline package
Definition at line 82 of file BoundConstants.cs.
    {
        int num = 0;
        foreach (KeyValuePair<TypedConstant, int> reference in _references)
        {
            if (ShouldCache(reference.Value))
            {
                num++;
            }
        }
        if (num == 0)
        {
            return;
        }
        EmitConstantsArray(lc);
        _cache.Clear();
        foreach (KeyValuePair<TypedConstant, int> reference2 in _references)
        {
            if (ShouldCache(reference2.Value))
            {
                if (--num > 0)
                {
                    lc.IL.Emit(OpCodes.Dup);
                }
                LocalBuilder localBuilder = lc.IL.DeclareLocal(reference2.Key.Type);
                EmitConstantFromArray(lc, reference2.Key.Value, localBuilder.LocalType);
                lc.IL.Emit(OpCodes.Stloc, localBuilder);
                _cache.Add(reference2.Key, localBuilder);
            }
        }
    }
References System.Linq.Expressions.Compiler.BoundConstants._cache, System.Linq.Expressions.Compiler.BoundConstants._references, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Collections.Generic.Dictionary< TKey, TValue >.Clear(), System.Reflection.Emit.OpCodes.Dup, System.Linq.Expressions.Compiler.BoundConstants.EmitConstantFromArray(), System.Linq.Expressions.Compiler.BoundConstants.EmitConstantsArray(), System.Linq.Expressions.Compiler.BoundConstants.ShouldCache(), and System.Reflection.Emit.OpCodes.Stloc.
Referenced by System.Linq.Expressions.Compiler.LambdaCompiler.InitializeMethod().