Terraria: System.Numerics.BigIntegerCalculator.FastReducer.SubMod
SubMod()
static unsafe int System.Numerics.BigIntegerCalculator.FastReducer.SubMod (uint[] left, int leftLength, uint[] right, int rightLength, uint[] modulus, int k) inline static private
Definition at line 215 of file BigIntegerCalculator.cs.
        {
            if (leftLength > k)
            {
                leftLength = k;
            }
            if (rightLength > k)
            {
                rightLength = k;
            }
            fixed (uint* left2 = left)
            {
                fixed (uint* right2 = right)
                {
                    fixed (uint* right3 = modulus)
                    {
                        SubtractSelf(left2, leftLength, right2, rightLength);
                        leftLength = ActualLength(left, leftLength);
                        while (Compare(left2, leftLength, right3, modulus.Length) >= 0)
{
                            SubtractSelf(left2, leftLength, right3, modulus.Length);
                            leftLength = ActualLength(left, leftLength);
                        }
                    }
                }
            }
            Array.Clear(left, leftLength, left.Length - leftLength);
            return leftLength;
        }
References System.Numerics.BigIntegerCalculator.ActualLength(), System.Array.Clear(), System.Numerics.BigIntegerCalculator.Compare(), and System.Numerics.BigIntegerCalculator.SubtractSelf().
Referenced by System.Numerics.BigIntegerCalculator.FastReducer.Reduce().