Terraria: System.Numerics.BigIntegerCalculator.FastReducer.DivMul
DivMul()
static unsafe int System.Numerics.BigIntegerCalculator.FastReducer.DivMul (uint[] left, int leftLength, uint[] right, int rightLength, uint[] bits, int k) inline static private
Definition at line 187 of file BigIntegerCalculator.cs.
        {
            Array.Clear(bits);
            if (leftLength > k)
            {
                leftLength -= k;
                fixed (uint* ptr2 = left)
                {
                    fixed (uint* ptr = right)
                    {
                        fixed (uint* bits2 = bits)
{
                            if (leftLength < rightLength)
{
                                Multiply(ptr, rightLength, ptr2 + k, leftLength, bits2, leftLength + rightLength);
                            }
                            else
{
                                Multiply(ptr2 + k, leftLength, ptr, rightLength, bits2, leftLength + rightLength);
                            }
                        }
                    }
                }
                return ActualLength(bits, leftLength + rightLength);
            }
            return 0;
        }
References System.Numerics.BigIntegerCalculator.ActualLength(), System.Array.Clear(), and System.Multiply.
Referenced by System.Numerics.BigIntegerCalculator.FastReducer.Reduce().