Terraria: System.Runtime.Serialization.EnumDataContract.EnumDataContractCriticalHelper.ImportDataMembers
ImportDataMembers()
void System.Runtime.Serialization.EnumDataContract.EnumDataContractCriticalHelper.ImportDataMembers () inline private
Definition at line 140 of file EnumDataContract.cs.
        {
            Type underlyingType = base.UnderlyingType;
            FieldInfo[] fields = underlyingType.GetFields(BindingFlags.Static | BindingFlags.Public);
            Dictionary<string, DataMember> memberNamesTable = new Dictionary<string, DataMember>();
            List<DataMember> members = new List<DataMember>(fields.Length);
            List<long> list = new List<long>(fields.Length);
            foreach (FieldInfo fieldInfo in fields)
            {
                bool flag = false;
                if (_hasDataContract)
                {
                    object[] array = fieldInfo.GetCustomAttributes(Globals.TypeOfEnumMemberAttribute, inherit: false).ToArray();
                    if (array != null && array.Length != 0)
                    {
                        if (array.Length > 1)
{
                            ThrowInvalidDataContractException(System.SR.Format(System.SR.TooManyEnumMembers, DataContract.GetClrTypeFullName(fieldInfo.DeclaringType), fieldInfo.Name));
                        }
                        EnumMemberAttribute enumMemberAttribute = (EnumMemberAttribute)array[0];
                        DataMember dataMember = new DataMember(fieldInfo);
                        if (enumMemberAttribute.IsValueSetExplicitly)
{
                            if (enumMemberAttribute.Value == null || enumMemberAttribute.Value.Length == 0)
{
                                ThrowInvalidDataContractException(System.SR.Format(System.SR.InvalidEnumMemberValue, fieldInfo.Name, DataContract.GetClrTypeFullName(underlyingType)));
                            }
                            dataMember.Name = enumMemberAttribute.Value;
                        }
                        else
{
                            dataMember.Name = fieldInfo.Name;
                        }
                        ClassDataContract.CheckAndAddMember(members, dataMember, memberNamesTable);
                        flag = true;
                    }
                    object[] array2 = fieldInfo.GetCustomAttributes(Globals.TypeOfDataMemberAttribute, inherit: false).ToArray();
                    if (array2 != null && array2.Length != 0)
                    {
                        ThrowInvalidDataContractException(System.SR.Format(System.SR.DataMemberOnEnumField, DataContract.GetClrTypeFullName(fieldInfo.DeclaringType), fieldInfo.Name));
                    }
                }
                else if (!fieldInfo.IsNotSerialized)
                {
                    DataMember dataMember2 = new DataMember(fieldInfo);
                    dataMember2.Name = fieldInfo.Name;
                    ClassDataContract.CheckAndAddMember(members, dataMember2, memberNamesTable);
                    flag = true;
                }
                if (flag)
                {
                    object value = fieldInfo.GetValue(null);
                    if (_isULong)
                    {
                        list.Add((long)Convert.ToUInt64(value, null));
                    }
                    else
                    {
                        list.Add(Convert.ToInt64(value, null));
                    }
                }
            }
            Interlocked.MemoryBarrier();
            _members = members;
            _values = list;
        }
References System.Runtime.Serialization.EnumDataContract.EnumDataContractCriticalHelper._hasDataContract, System.Runtime.Serialization.EnumDataContract.EnumDataContractCriticalHelper._isULong, System.Runtime.Serialization.EnumDataContract.EnumDataContractCriticalHelper._members, System.Runtime.Serialization.EnumDataContract.EnumDataContractCriticalHelper._values, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.array, System.Runtime.Serialization.ClassDataContract.CheckAndAddMember(), System.SR.DataMemberOnEnumField, System.Runtime.Serialization.Dictionary, System.SR.Format(), System.Runtime.Serialization.DataContract.GetClrTypeFullName(), System.SR.InvalidEnumMemberValue, System.list, System.Threading.Interlocked.MemoryBarrier(), System.Runtime.Serialization.DataContract.DataContractCriticalHelper.ThrowInvalidDataContractException(), System.Convert.ToInt64(), System.SR.TooManyEnumMembers, System.Convert.ToUInt64(), System.Runtime.Serialization.Globals.TypeOfDataMemberAttribute, System.Runtime.Serialization.Globals.TypeOfEnumMemberAttribute, and System.value.
Referenced by System.Runtime.Serialization.EnumDataContract.EnumDataContractCriticalHelper.EnumDataContractCriticalHelper().