Terraria: System.Runtime.Serialization.EnumDataContract.EnumDataContractCriticalHelper.EnumDataContractCriticalHelper
EnumDataContractCriticalHelper() [2/2]
System.Runtime.Serialization.EnumDataContract.EnumDataContractCriticalHelper.EnumDataContractCriticalHelper ([DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicConstructors | DynamicallyAccessedMemberTypes.NonPublicConstructors | DynamicallyAccessedMemberTypes.PublicMethods | DynamicallyAccessedMemberTypes.NonPublicMethods | DynamicallyAccessedMemberTypes.PublicFields | DynamicallyAccessedMemberTypes.PublicProperties)] Type type) inline package
Definition at line 112 of file EnumDataContract.cs.
            : base(type)
        {
            base.StableName = DataContract.GetStableName(type, out _hasDataContract);
            Type underlyingType = Enum.GetUnderlyingType(type);
            ImportBaseType(underlyingType);
            IsFlags = type.IsDefined(Globals.TypeOfFlagsAttribute, inherit: false);
            ImportDataMembers();
            XmlDictionary xmlDictionary = new XmlDictionary(2 + Members.Count);
            base.Name = xmlDictionary.Add(base.StableName.Name);
            base.Namespace = xmlDictionary.Add(base.StableName.Namespace);
            _childElementNames = new XmlDictionaryString[Members.Count];
            for (int i = 0; i < Members.Count; i++)
            {
                _childElementNames[i] = xmlDictionary.Add(Members[i].Name);
            }
            if (DataContract.TryGetDCAttribute(type, out var dataContractAttribute) && dataContractAttribute.IsReference)
            {
                DataContract.ThrowInvalidDataContractException(System.SR.Format(System.SR.EnumTypeCannotHaveIsReference, DataContract.GetClrTypeFullName(type), dataContractAttribute.IsReference, false), type);
            }
        }
References System.Runtime.Serialization.EnumDataContract.EnumDataContractCriticalHelper._childElementNames, System.Runtime.Serialization.EnumDataContract.EnumDataContractCriticalHelper._hasDataContract, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Runtime.Serialization.Dictionary, System.SR.EnumTypeCannotHaveIsReference, System.SR.Format(), System.Runtime.Serialization.DataContract.GetClrTypeFullName(), System.Runtime.Serialization.DataContract.GetStableName(), System.Enum.GetUnderlyingType(), System.Runtime.Serialization.EnumDataContract.EnumDataContractCriticalHelper.ImportBaseType(), System.Runtime.Serialization.EnumDataContract.EnumDataContractCriticalHelper.ImportDataMembers(), System.Runtime.Serialization.EnumDataContract.EnumDataContractCriticalHelper.IsFlags, System.Runtime.Serialization.EnumDataContract.EnumDataContractCriticalHelper.Members, System.Runtime.Serialization.DataContract.DataContractCriticalHelper.Name, System.Runtime.Serialization.DataContract.ThrowInvalidDataContractException(), System.Runtime.Serialization.DataContract.TryGetDCAttribute(), System.type, and System.Runtime.Serialization.Globals.TypeOfFlagsAttribute.