Terraria: System.Security.Cryptography.DSACryptoServiceProvider.SignHash
SignHash()
byte[] System.Security.Cryptography.DSACryptoServiceProvider.SignHash (byte[] rgbHash, string? str) inline
Definition at line 323 of file DSACryptoServiceProvider.cs.
    {
        if (rgbHash == null)
        {
            throw new ArgumentNullException("rgbHash");
        }
        if (PublicOnly)
        {
            throw new CryptographicException(System.SR.Cryptography_CSP_NoPrivateKey);
        }
        int calgHash = CapiHelper.NameOrOidToHashAlgId(str, OidGroup.HashAlgorithm);
        if (rgbHash.Length != _sha1.HashSize / 8)
        {
            throw new CryptographicException(System.SR.Format(System.SR.Cryptography_InvalidHashSize, "SHA1", _sha1.HashSize / 8));
        }
        return CapiHelper.SignValue(SafeProvHandle, SafeKeyHandle, _parameters.KeyNumber, 8704, calgHash, rgbHash);
    }
References System.Security.Cryptography.DSACryptoServiceProvider._parameters, System.Security.Cryptography.DSACryptoServiceProvider._sha1, System.SR.Cryptography_CSP_NoPrivateKey, System.SR.Cryptography_InvalidHashSize, System.SR.Format(), System.Security.Cryptography.HashAlgorithm.HashSize, System.Security.Cryptography.CspParameters.KeyNumber, Internal.NativeCrypto.CapiHelper.NameOrOidToHashAlgId(), System.Security.Cryptography.DSACryptoServiceProvider.PublicOnly, Internal.NativeCrypto.CapiHelper.SignValue(), and System.str.
Referenced by System.Security.Cryptography.DSACryptoServiceProvider.CreateSignature(), System.Security.Cryptography.DSACryptoServiceProvider.SignData(), System.Security.Cryptography.DSACryptoServiceProvider.SignData(), and System.Security.Cryptography.DSACryptoServiceProvider.SignData().