Terraria: UIWorldSelect.UpdateWorldsList
UpdateWorldsList()
void UIWorldSelect.UpdateWorldsList () inline private
     {
         _worldList.Clear();
         IOrderedEnumerable<WorldFileData> orderedEnumerable = new List<WorldFileData>(Main.WorldList).OrderByDescending(CanWorldBePlayed).ThenByDescending((WorldFileData x) => x.IsFavorite).ThenBy((WorldFileData x) => x.Name)
             .ThenBy((WorldFileData x) => x.GetFileName());
         int num = 0;
         foreach (WorldFileData item in orderedEnumerable)
         {
             _worldList.Add(new UIWorldListItem(item, num++, CanWorldBePlayed(item)));
         }
     }
References _worldList, UIList.Add(), CanWorldBePlayed(), UIList.Clear(), FileData.GetFileName(), FileData.IsFavorite, FileData.Name, and Main.WorldList.
Referenced by OnActivate(), and UpdateFavoritesCache().