Terraria: System.Collections.ArrayList.Range.RemoveAt
RemoveAt()
override void System.Collections.ArrayList.Range.RemoveAt (int index) inline virtual
Reimplemented from System.Collections.ArrayList.
Definition at line 1982 of file ArrayList.cs.
        {
            if (index < 0 || index >= _baseSize)
            {
                throw new ArgumentOutOfRangeException("index", SR.ArgumentOutOfRange_Index);
            }
            InternalUpdateRange();
            _baseList.RemoveAt(_baseIndex + index);
            InternalUpdateVersion();
            _baseSize--;
        }
References System.Collections.ArrayList.Range._baseIndex, System.Collections.ArrayList.Range._baseList, System.Collections.ArrayList.Range._baseSize, System.SR.ArgumentOutOfRange_Index, System.index, System.Collections.ArrayList.Range.InternalUpdateRange(), System.Collections.ArrayList.Range.InternalUpdateVersion(), and System.Collections.ArrayList.RemoveAt().