Terraria: System.Collections.ArrayList.Range.InternalUpdateVersion
InternalUpdateVersion()
void System.Collections.ArrayList.Range.InternalUpdateVersion () inline private
Definition at line 1688 of file ArrayList.cs.
        {
            _baseVersion++;
            _version++;
        }
References System.Collections.ArrayList.Range._baseVersion, and System.Collections.ArrayList._version.
Referenced by System.Collections.ArrayList.Range.Add(), System.Collections.ArrayList.Range.AddRange(), System.Collections.ArrayList.Range.Clear(), System.Collections.ArrayList.Range.Insert(), System.Collections.ArrayList.Range.InsertRange(), System.Collections.ArrayList.Range.RemoveAt(), System.Collections.ArrayList.Range.RemoveRange(), System.Collections.ArrayList.Range.Reverse(), System.Collections.ArrayList.Range.SetRange(), and System.Collections.ArrayList.Range.Sort().