Terraria: System.Collections.ArrayList.Range.Insert
Insert() [1/2]
override void System.Collections.ArrayList.Range.Insert (int index, object value) inline
Definition at line 1911 of file ArrayList.cs.
        {
            if (index < 0 || index > _baseSize)
            {
                throw new ArgumentOutOfRangeException("index", SR.ArgumentOutOfRange_Index);
            }
            InternalUpdateRange();
            _baseList.Insert(_baseIndex + index, value);
            InternalUpdateVersion();
            _baseSize++;
        }
References System.Collections.ArrayList.Range._baseIndex, System.Collections.ArrayList.Range._baseList, System.Collections.ArrayList.Range._baseSize, System.SR.ArgumentOutOfRange_Index, System.index, System.Collections.ArrayList.Insert(), System.Collections.ArrayList.Range.InternalUpdateRange(), System.Collections.ArrayList.Range.InternalUpdateVersion(), and System.value.