Terraria: System.Data.Common.DbCommand.ExecuteDbDataReaderAsync
ExecuteDbDataReaderAsync()
virtual Task< DbDataReader > System.Data.Common.DbCommand.ExecuteDbDataReaderAsync (CommandBehavior behavior, CancellationToken cancellationToken) inline protected virtual
Definition at line 201 of file DbCommand.cs.
    {
        if (cancellationToken.IsCancellationRequested)
        {
            return ADP.CreatedTaskWithCancellation<DbDataReader>();
        }
        CancellationTokenRegistration cancellationTokenRegistration = default(CancellationTokenRegistration);
        if (cancellationToken.CanBeCanceled)
        {
            cancellationTokenRegistration = cancellationToken.Register(delegate(object s)
            {
                ((DbCommand)s).CancelIgnoreFailure();
            }, this);
        }
        try
        {
            return Task.FromResult(ExecuteReader(behavior));
        }
        catch (Exception exception)
        {
            return Task.FromException<DbDataReader>(exception);
        }
        finally
        {
            cancellationTokenRegistration.Dispose();
        }
    }
References System.cancellationToken, System.Threading.CancellationTokenRegistration.Dispose(), System.exception, System.Data.Common.DbCommand.ExecuteReader(), System.Threading.Tasks.Task< TResult >.FromException(), and System.s.
Referenced by System.Data.Common.DbCommand.ExecuteReaderAsync().