Terraria: System.Threading.Tasks.Task.CancellationPromise.Cleanup
Cleanup()
void System.Threading.Tasks.Task< TResult >.CancellationPromise< TResult >.Cleanup () inline private
Definition at line 545 of file Task.cs.
        {
            _registration.Dispose();
            _timer?.Close();
            _task.RemoveContinuation(this);
        }
References System.Threading.Tasks.Task< TResult >.CancellationPromise< TResult >._registration, System.Threading.Tasks.Task< TResult >.CancellationPromise< TResult >._task, System.Threading.Tasks.Task< TResult >.CancellationPromise< TResult >._timer, System.Threading.TimerQueueTimer.Close(), System.Threading.CancellationTokenRegistration.Dispose(), and System.Threading.Tasks.Task< TResult >.RemoveContinuation().
Referenced by System.Threading.Tasks.Task< TResult >.CancellationPromise< TResult >.CancellationPromise(), and System.Threading.Tasks.Task< TResult >.CancellationPromise< TResult >.Invoke().