Terraria: UIWorkshopPublishResourcePackListItem.TryMovingToRejectionMenuIfNeeded
TryMovingToRejectionMenuIfNeeded()
bool UIWorkshopPublishResourcePackListItem.TryMovingToRejectionMenuIfNeeded () inline private
     {
         if (!_canPublish)
         {
             SoundEngine.PlaySound(10);
             Main.instance.RejectionMenuInfo = new RejectionMenuInfo
             {
                 TextToShow = Language.GetTextValue("Workshop.ReportIssue_CannotPublishZips"),
                 ExitAction = RejectionMenuExitAction
             };
             Main.menuMode = 1000001;
             return true;
         }
         return false;
     }
References _canPublish, Language.GetTextValue(), Main.instance, Main.menuMode, SoundEngine.PlaySound(), RejectionMenuExitAction(), and Main.RejectionMenuInfo.
Referenced by PublishButtonClick_ImportResourcePackToLocalFiles().