Terraria: System.Threading.Tasks.Task.CancellationPromise.CancellationPromise
CancellationPromise()
System.Threading.Tasks.Task< TResult >.CancellationPromise< TResult >.CancellationPromise (Task source, uint millisecondsDelay, CancellationToken token) inline package
Definition at line 503 of file Task.cs.
        {
            _task = source;
            source.AddCompletionAction(this);
            if (millisecondsDelay != uint.MaxValue)
            {
                _timer = new TimerQueueTimer(delegate(object state)
                {
                    CancellationPromise<TResult> cancellationPromise2 = (CancellationPromise<TResult>)state;
                    if (cancellationPromise2.TrySetException(new TimeoutException()))
                    {
                        cancellationPromise2.Cleanup();
                    }
                }, this, millisecondsDelay, uint.MaxValue, flowExecutionContext: false);
            }
            _registration = token.UnsafeRegister(delegate(object state, CancellationToken cancellationToken)
            {
                CancellationPromise<TResult> cancellationPromise = (CancellationPromise<TResult>)state;
                if (cancellationPromise.TrySetCanceled(cancellationToken))
                {
                    cancellationPromise.Cleanup();
                }
            }, this);
            if (base.IsCompleted)
            {
                Cleanup();
            }
        }
References System.Threading.Tasks.Task< TResult >.CancellationPromise< TResult >._registration, System.Threading.Tasks.Task< TResult >.CancellationPromise< TResult >._task, System.Threading.Tasks.Task< TResult >.CancellationPromise< TResult >._timer, System.Threading.Tasks.Task< TResult >.AddCompletionAction(), System.cancellationToken, System.Threading.Tasks.Task< TResult >.CancellationPromise< TResult >.Cleanup(), System.millisecondsDelay, System.source, System.state, and System.Threading.CancellationToken.UnsafeRegister().