Terraria: System.Xml.Serialization.StructMapping.FindDeclaringMapping
FindDeclaringMapping()
MemberMapping System.Xml.Serialization.StructMapping.FindDeclaringMapping (MemberMapping member, out StructMapping declaringMapping, string parent) inline package
Definition at line 205 of file StructMapping.cs.
    {
        declaringMapping = null;
        if (BaseMapping != null)
        {
            MemberMapping memberMapping = BaseMapping.FindDeclaringMapping(member, out declaringMapping, parent);
            if (memberMapping != null)
            {
                return memberMapping;
            }
        }
        if (_members == null)
        {
            return null;
        }
        for (int i = 0; i < _members.Length; i++)
        {
            if (_members[i].Name == member.Name)
            {
                if (_members[i].TypeDesc != member.TypeDesc)
                {
                    throw new InvalidOperationException(System.SR.Format(System.SR.XmlHiddenMember, parent, member.Name, member.TypeDesc.FullName, base.TypeName, _members[i].Name, _members[i].TypeDesc.FullName));
                }
                if (!_members[i].Match(member))
                {
                    throw new InvalidOperationException(System.SR.Format(System.SR.XmlInvalidXmlOverride, parent, member.Name, base.TypeName, _members[i].Name));
                }
                declaringMapping = this;
                return _members[i];
            }
        }
        return null;
    }
References System.Xml.Serialization.StructMapping._members, System.Xml.Serialization.StructMapping.BaseMapping, System.Xml.Dictionary, System.Xml.Serialization.StructMapping.FindDeclaringMapping(), System.SR.Format(), System.Xml.Serialization.TypeDesc.FullName, System.Xml.Serialization.MemberMapping.Name, System.Xml.Name, System.Xml.Serialization.AccessorMapping.TypeDesc, System.SR.XmlHiddenMember, and System.SR.XmlInvalidXmlOverride.
Referenced by System.Xml.Serialization.StructMapping.Declares(), and System.Xml.Serialization.StructMapping.FindDeclaringMapping().