Terraria: Terraria.GameContent.UI.Elements.UIScrollbar.LeftMouseDown
LeftMouseDown()
override void Terraria.GameContent.UI.Elements.UIScrollbar.LeftMouseDown (UIMouseEvent evt) inline virtual
Reimplemented from Terraria.UI.UIElement.
Definition at line 108 of file UIScrollbar.cs.
    {
        base.LeftMouseDown(evt);
        if (evt.Target == this)
        {
            Rectangle handleRectangle = GetHandleRectangle();
            if (handleRectangle.Contains(new Point((int)evt.MousePosition.X, (int)evt.MousePosition.Y)))
            {
                _isDragging = true;
                _dragYOffset = evt.MousePosition.Y - (float)handleRectangle.Y;
            }
            else
            {
                CalculatedStyle innerDimensions = GetInnerDimensions();
                float num = UserInterface.ActiveInstance.MousePosition.Y - innerDimensions.Y - (float)(handleRectangle.Height >> 1);
                _viewPosition = MathHelper.Clamp(num / innerDimensions.Height * _maxViewSize, 0f, _maxViewSize - _viewSize);
            }
        }
    }
References Terraria.GameContent.UI.Elements.UIScrollbar._dragYOffset, Terraria.GameContent.UI.Elements.UIScrollbar._isDragging, Terraria.GameContent.UI.Elements.UIScrollbar._maxViewSize, Terraria.GameContent.UI.Elements.UIScrollbar._viewPosition, Terraria.GameContent.UI.Elements.UIScrollbar._viewSize, Microsoft.Xna.Framework.MathHelper.Clamp(), Microsoft.Xna.Framework.Rectangle.Contains(), Terraria.GameContent.UI.Elements.UIScrollbar.GetHandleRectangle(), Terraria.UI.UIElement.GetInnerDimensions(), Microsoft.Xna.Framework.Rectangle.Height, Terraria.UI.CalculatedStyle.Height, Terraria.UI.UIMouseEvent.MousePosition, Terraria.UI.UIEvent.Target, Microsoft.Xna.Framework.Vector2.X, Microsoft.Xna.Framework.Rectangle.Y, and Microsoft.Xna.Framework.Vector2.Y.