Terraria: GolfState.Update
Update()
void GolfState.Update () inline
     {
         UpdateScoreTime();
         Projectile lastHitBall = GetLastHitBall();
         if (lastHitBall == null)
         {
             _waitingForBallToSettle = false;
             return;
         }
         if (_waitingForBallToSettle)
         {
             _waitingForBallToSettle = (int)lastHitBall.localAI[1] == 1;
         }
         bool flag = false;
         int type = Main.LocalPlayer.HeldItem.type;
         if (type == 3611)
         {
             flag = true;
         }
         if (!Item.IsAGolfingItem(Main.LocalPlayer.HeldItem) && !flag)
         {
             _waitingForBallToSettle = false;
         }
     }
References _waitingForBallToSettle, GetLastHitBall(), Player.HeldItem, Item.IsAGolfingItem(), Projectile.localAI, Main.LocalPlayer, Item.type, and UpdateScoreTime().
Referenced by Main.DoUpdate().