Terraria: GolfState.GetGolfBallScore
GetGolfBallScore()
int GolfState.GetGolfBallScore (Projectile golfBall) inline
     {
         int golfBallId = GetGolfBallId(golfBall);
         GolfBallTrackRecord golfBallTrackRecord = _hitRecords[golfBallId];
         if (golfBallTrackRecord == null)
         {
             return 0;
         }
         return (int)((float)golfBallTrackRecord.GetAccumulatedScore() * ScoreAdjustment);
     }
References _hitRecords, GolfBallTrackRecord.GetAccumulatedScore(), GetGolfBallId(), and ScoreAdjustment.
Referenced by GolfHelper.ContactListener.PutBallInCup().