Terraria: GolfState.GetLastHitBall
GetLastHitBall()
Projectile GolfState.GetLastHitBall () inline
     {
         if (_lastHitGolfBall == null || !_lastHitGolfBall.active || !ProjectileID.Sets.IsAGolfBall[_lastHitGolfBall.type] || _lastHitGolfBall.owner != Main.myPlayer || _lastRecordedSwingCount != (int)_lastHitGolfBall.ai[1])
         {
             return null;
         }
         return _lastHitGolfBall;
     }
References _lastHitGolfBall, _lastRecordedSwingCount, Entity.active, Projectile.ai, ProjectileID.Sets.IsAGolfBall, Main.myPlayer, Projectile.owner, and Projectile.type.
Referenced by Main.DoDraw_UpdateCameraPosition(), Main.DrawInterface_GolfBallIndicator(), Main.DrawMapIcons_LastGolfballHit(), RecordBallInfo(), ResetGolfBall(), and Update().