Terraria: GolfState.RecordSwing
RecordSwing()
void GolfState.RecordSwing (Projectile golfBall) inline
     {
         _lastSwingPosition = golfBall.position;
         _lastHitGolfBall = golfBall;
         _lastRecordedSwingCount = (int)golfBall.ai[1];
         _waitingForBallToSettle = true;
         int golfBallId = GetGolfBallId(golfBall);
         if (_hitRecords[golfBallId] == null || _lastRecordedSwingCount == 1)
         {
             _hitRecords[golfBallId] = new GolfBallTrackRecord();
         }
         _hitRecords[golfBallId].RecordHit(golfBall.position);
     }
References _hitRecords, _lastHitGolfBall, _lastRecordedSwingCount, _lastSwingPosition, _waitingForBallToSettle, Projectile.ai, GetGolfBallId(), Entity.position, and GolfBallTrackRecord.RecordHit().
Referenced by GolfHelper.HitGolfBall().