Terraria: System.Runtime.InteropServices.NativeMemory.AlignedRealloc
AlignedRealloc()
static unsafe void * System.Runtime.InteropServices.NativeMemory.AlignedRealloc (void * ptr, nuint byteCount, nuint alignment) inline static
Definition at line 57 of file NativeMemory.cs.
    {
        if (!BitOperations.IsPow2(alignment))
        {
            ThrowHelper.ThrowArgumentException(ExceptionResource.Argument_AlignmentMustBePow2);
        }
        void* ptr2 = Interop.Ucrtbase._aligned_realloc(ptr, (byteCount != 0) ? byteCount : 1, alignment);
        if (ptr2 == null)
        {
            ThrowHelper.ThrowOutOfMemoryException();
        }
        return ptr2;
    }
References Interop.Ucrtbase._aligned_realloc(), System.byteCount, System.Numerics.BitOperations.IsPow2(), System.ThrowHelper.ThrowArgumentException(), and System.ThrowHelper.ThrowOutOfMemoryException().