Terraria: System.Diagnostics.Tracing.CounterGroup.PollForValues
PollForValues()
static void System.Diagnostics.Tracing.CounterGroup.PollForValues () inline static private
Definition at line 203 of file CounterGroup.cs.
    {
        AutoResetEvent autoResetEvent = null;
        List<CounterGroup> list = new List<CounterGroup>();
        while (true)
        {
            int num = int.MaxValue;
            lock (s_counterGroupLock)
            {
                autoResetEvent = s_pollingThreadSleepEvent;
                foreach (CounterGroup s_counterGroupEnabled in s_counterGroupEnabledList)
                {
                    DateTime utcNow = DateTime.UtcNow;
                    if (s_counterGroupEnabled._nextPollingTimeStamp < utcNow + new TimeSpan(0, 0, 0, 0, 1))
                    {
                        list.Add(s_counterGroupEnabled);
                    }
                    int val = (int)(s_counterGroupEnabled._nextPollingTimeStamp - utcNow).TotalMilliseconds;
                    val = Math.Max(1, val);
                    num = Math.Min(num, val);
                }
            }
            foreach (CounterGroup item in list)
            {
                item.OnTimer();
            }
            list.Clear();
            if (num == int.MaxValue)
            {
                num = -1;
            }
            autoResetEvent?.WaitOne(num);
        }
    }
References System.item, System.list, System.Math.Max(), System.Math.Min(), System.Diagnostics.Tracing.CounterGroup.s_counterGroupEnabledList, System.Diagnostics.Tracing.CounterGroup.s_counterGroupLock, System.Diagnostics.Tracing.CounterGroup.s_pollingThreadSleepEvent, and System.DateTime.UtcNow.
Referenced by System.Diagnostics.Tracing.CounterGroup.EnableTimer().