Terraria: System.Diagnostics.Tracing.CounterGroup.OnEventSourceCommand
OnEventSourceCommand()
void System.Diagnostics.Tracing.CounterGroup.OnEventSourceCommand (object sender, EventCommandEventArgs e) inline private
Definition at line 58 of file CounterGroup.cs.
    {
        if (e.Command == EventCommand.Enable || e.Command == EventCommand.Update)
        {
            if (e.Arguments.TryGetValue("EventCounterIntervalSec", out string value) && float.TryParse(value, out var result))
            {
                lock (s_counterGroupLock)
                {
                    EnableTimer(result);
                }
            }
        }
        else if (e.Command == EventCommand.Disable)
        {
            lock (s_counterGroupLock)
            {
                DisableTimer();
            }
        }
    }
References System.Diagnostics.Tracing.EventCommandEventArgs.Arguments, System.Diagnostics.Tracing.EventCommandEventArgs.Command, System.Diagnostics.Tracing.CounterGroup.DisableTimer(), System.Diagnostics.Tracing.CounterGroup.EnableTimer(), System.Diagnostics.Tracing.CounterGroup.s_counterGroupLock, System.Collections.Generic.Dictionary< TKey, TValue >.TryGetValue(), and System.value.
Referenced by System.Diagnostics.Tracing.CounterGroup.RegisterCommandCallback().