Terraria: System.Threading.Timeout.InfiniteTimeSpan
InfiniteTimeSpan
readonly TimeSpan System.Threading.Timeout.InfiniteTimeSpan = new TimeSpan(0, 0, 0, 0, -1) static
Definition at line 5 of file Timeout.cs.
Referenced by System.Net.HttpWebRequest.HttpClientParameters.HttpClientParameters(), System.Net.Http.HttpConnectionPoolManager.HttpConnectionPoolManager(), System.Net.Http.HttpConnectionPool.CheckExpirationOnGet(), System.Net.Http.HttpConnectionPool.CheckExpirationOnReturn(), System.Net.Http.HttpConnectionPool.CleanCacheAndDisposeIfUnused(), System.Net.Quic.Implementations.MsQuic.Internal.SafeMsQuicConfigurationHandle.Create(), System.Net.WebSockets.WebSocket.CreateClientWebSocket(), System.Net.WebSockets.WebSocket.CreateFromStream(), System.Net.Http.HttpConnection.ChunkedEncodingReadStream.DrainAsync(), System.Net.Http.HttpConnection.ContentLengthReadStream.DrainAsync(), System.Net.Http.HttpConnectionPool.HandleAltSvc(), System.Net.Http.HttpConnectionPoolManager.RemoveStalePools(), System.Net.Http.HttpConnection.SendAsyncCore(), System.Net.Http.Http3RequestStream.SendContentAsync(), System.Net.Http.HttpConnectionPoolManager.SetCleaningTimer(), System.Net.WebSockets.HttpWebSocket.ValidateOptions(), and System.Net.Http.Http2Connection.Http2Stream.WaitFor100ContinueAsync().