Terraria: System.Diagnostics.Tracing.CounterGroup.OnTimer
OnTimer()
void System.Diagnostics.Tracing.CounterGroup.OnTimer () inline private
Definition at line 168 of file CounterGroup.cs.
    {
        if (!_eventSource.IsEnabled())
        {
            return;
        }
        DateTime utcNow;
        TimeSpan timeSpan;
        int pollingIntervalInMilliseconds;
        DiagnosticCounter[] array;
        lock (s_counterGroupLock)
        {
            utcNow = DateTime.UtcNow;
            timeSpan = utcNow - _timeStampSinceCollectionStarted;
            pollingIntervalInMilliseconds = _pollingIntervalInMilliseconds;
            array = new DiagnosticCounter[_counters.Count];
            _counters.CopyTo(array);
        }
        DiagnosticCounter[] array2 = array;
        foreach (DiagnosticCounter diagnosticCounter in array2)
        {
            diagnosticCounter.WritePayload((float)timeSpan.TotalSeconds, pollingIntervalInMilliseconds);
        }
        lock (s_counterGroupLock)
        {
            _timeStampSinceCollectionStarted = utcNow;
            TimeSpan timeSpan2 = utcNow - _nextPollingTimeStamp;
            timeSpan2 = (((double)_pollingIntervalInMilliseconds > timeSpan2.TotalMilliseconds) ? TimeSpan.FromMilliseconds(_pollingIntervalInMilliseconds) : timeSpan2);
            if (_pollingIntervalInMilliseconds > 0)
            {
                _nextPollingTimeStamp += TimeSpan.FromMilliseconds((double)_pollingIntervalInMilliseconds * Math.Ceiling(timeSpan2.TotalMilliseconds / (double)_pollingIntervalInMilliseconds));
            }
        }
    }
References System.Diagnostics.Tracing.CounterGroup._counters, System.Diagnostics.Tracing.CounterGroup._eventSource, System.Diagnostics.Tracing.CounterGroup._nextPollingTimeStamp, System.Diagnostics.Tracing.CounterGroup._pollingIntervalInMilliseconds, System.Diagnostics.Tracing.CounterGroup._timeStampSinceCollectionStarted, System.array, System.Math.Ceiling(), System.Collections.Generic.Dictionary< TKey, TValue >.CopyTo(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.TimeSpan.FromMilliseconds(), System.Diagnostics.Tracing.EventSource.IsEnabled(), System.Diagnostics.Tracing.CounterGroup.s_counterGroupLock, and System.DateTime.UtcNow.