Terraria: System.Diagnostics.Tracing.CounterGroup.EnableTimer
EnableTimer()
void System.Diagnostics.Tracing.CounterGroup.EnableTimer (float pollingIntervalInSeconds) inline private
Definition at line 109 of file CounterGroup.cs.
    {
        if (pollingIntervalInSeconds <= 0f)
        {
            DisableTimer();
        }
        else if (_pollingIntervalInMilliseconds == 0 || pollingIntervalInSeconds * 1000f < (float)_pollingIntervalInMilliseconds)
        {
            _pollingIntervalInMilliseconds = (int)(pollingIntervalInSeconds * 1000f);
            ResetCounters();
            _timeStampSinceCollectionStarted = DateTime.UtcNow;
            _nextPollingTimeStamp = DateTime.UtcNow + new TimeSpan(0, 0, (int)pollingIntervalInSeconds);
            if (s_pollingThread == null)
            {
                s_pollingThreadSleepEvent = new AutoResetEvent(initialState: false);
                s_counterGroupEnabledList = new List<CounterGroup>();
                s_pollingThread = new Thread(PollForValues)
                {
                    IsBackground = true,
                    Name = ".NET Counter Poller"
                };
                s_pollingThread.UnsafeStart();
            }
            if (!s_counterGroupEnabledList.Contains(this))
            {
                s_counterGroupEnabledList.Add(this);
            }
            s_pollingThreadSleepEvent.Set();
        }
    }
References System.Diagnostics.Tracing.CounterGroup._nextPollingTimeStamp, System.Diagnostics.Tracing.CounterGroup._pollingIntervalInMilliseconds, System.Diagnostics.Tracing.CounterGroup._timeStampSinceCollectionStarted, System.Diagnostics.Tracing.CounterGroup.DisableTimer(), System.Name, System.Diagnostics.Tracing.CounterGroup.PollForValues(), System.Diagnostics.Tracing.CounterGroup.ResetCounters(), System.Diagnostics.Tracing.CounterGroup.s_counterGroupEnabledList, System.Diagnostics.Tracing.CounterGroup.s_pollingThread, System.Diagnostics.Tracing.CounterGroup.s_pollingThreadSleepEvent, and System.DateTime.UtcNow.
Referenced by System.Diagnostics.Tracing.CounterGroup.OnEventSourceCommand().