Terraria: System.Globalization.HebrewCalendar.CheckTicksRange
CheckTicksRange()
static void System.Globalization.HebrewCalendar.CheckTicksRange (long ticks) inline static private
Definition at line 236 of file HebrewCalendar.cs.
    {
        if (ticks < s_calendarMinValue.Ticks || ticks > s_calendarMaxValue.Ticks)
        {
            throw new ArgumentOutOfRangeException("time", ticks, SR.Format(CultureInfo.InvariantCulture, SR.ArgumentOutOfRange_CalendarRange, s_calendarMinValue, s_calendarMaxValue));
        }
    }
References System.SR.ArgumentOutOfRange_CalendarRange, System.SR.Format(), System.Globalization.CultureInfo.InvariantCulture, System.Globalization.HebrewCalendar.s_calendarMaxValue, and System.Globalization.HebrewCalendar.s_calendarMinValue.
Referenced by System.Globalization.HebrewCalendar.GetDatePart(), and System.Globalization.HebrewCalendar.ToDateTime().