Terraria: System.Globalization.HebrewCalendar.IsLeapDay
IsLeapDay() [2/2]
override bool System.Globalization.HebrewCalendar.IsLeapDay (int year, int month, int day, int era) inline
Definition at line 471 of file HebrewCalendar.cs.
    {
        if (IsLeapMonth(year, month, era))
        {
            CheckHebrewDayValue(year, month, day, era);
            return true;
        }
        if (IsLeapYear(year, 0) && month == 6 && day == 30)
        {
            return true;
        }
        CheckHebrewDayValue(year, month, day, era);
        return false;
    }
References System.Globalization.HebrewCalendar.CheckHebrewDayValue(), System.Globalization.HebrewCalendar.IsLeapMonth(), System.Globalization.HebrewCalendar.IsLeapYear(), and System.year.