Terraria: Terraria.WorldGen.Spread.Moss
Moss()
static void Terraria.WorldGen.Spread.Moss (int x, int y) inline static
Definition at line 274 of file WorldGen.cs.
        {
            if (!InWorld(x, y))
            {
                return;
            }
            ushort mossWall = GenVars.mossWall;
            ushort mossTile = GenVars.mossTile;
            List<Point> list = new List<Point>();
            List<Point> list2 = new List<Point>();
            HashSet<Point> hashSet = new HashSet<Point>();
            list2.Add(new Point(x, y));
            while (list2.Count > 0)
            {
                list.Clear();
                list.AddRange(list2);
                list2.Clear();
                while (list.Count > 0)
                {
                    Point item = list[0];
                    if (!InWorld(item.X, item.Y, 1))
                    {
                        list.Remove(item);
                        continue;
                    }
                    hashSet.Add(item);
                    list.Remove(item);
                    Tile tile = Main.tile[item.X, item.Y];
                    if (SolidTile(item.X, item.Y) || tile.wall != 0)
                    {
                        if (tile.active())
{
                            if (tile.wall == 0)
{
                                tile.wall = mossWall;
                            }
                            if (tile.type == 1)
{
                                tile.type = mossTile;
                            }
                        }
                        continue;
                    }
                    tile.wall = mossWall;
                    Point item2 = new Point(item.X - 1, item.Y);
                    if (!hashSet.Contains(item2))
                    {
                        list2.Add(item2);
                    }
                    item2 = new Point(item.X + 1, item.Y);
                    if (!hashSet.Contains(item2))
                    {
                        list2.Add(item2);
                    }
                    item2 = new Point(item.X, item.Y - 1);
                    if (!hashSet.Contains(item2))
                    {
                        list2.Add(item2);
                    }
                    item2 = new Point(item.X, item.Y + 1);
                    if (!hashSet.Contains(item2))
                    {
                        list2.Add(item2);
                    }
                }
            }
        }
References Terraria.Tile.active(), System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Collections.Generic.Dictionary< TKey, TValue >.AddRange(), System.Collections.Generic.Dictionary< TKey, TValue >.Clear(), System.Collections.Generic.Dictionary< TKey, TValue >.Contains(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, Terraria.WorldGen.InWorld(), System.item, System.list, Terraria.WorldBuilding.GenVars.mossTile, Terraria.WorldBuilding.GenVars.mossWall, System.Collections.Generic.Dictionary< TKey, TValue >.Remove(), Terraria.Enums.SolidTile, Terraria.Main.tile, Terraria.Tile.type, and Terraria.Tile.wall.