Terraria: System.Runtime.Serialization.SchemaHelper.GetSchema
GetSchema()
static XmlSchema System.Runtime.Serialization.SchemaHelper.GetSchema (string ns, XmlSchemaSet schemas) inline static package
Definition at line 68 of file SchemaHelper.cs.
    {
        if (ns == null)
        {
            ns = string.Empty;
        }
        ICollection collection = schemas.Schemas();
        foreach (XmlSchema item in collection)
        {
            if ((item.TargetNamespace == null && ns.Length == 0) || ns.Equals(item.TargetNamespace))
            {
                return item;
            }
        }
        return CreateSchema(ns, schemas);
    }
References System.collection, System.Runtime.Serialization.SchemaHelper.CreateSchema(), System.item, and System.Xml.Schema.XmlSchemaSet.Schemas().
Referenced by System.Runtime.Serialization.SchemaExporter.AddDefaultDatasetType(), System.Runtime.Serialization.SchemaExporter.AddDefaultTypedDatasetType(), System.Runtime.Serialization.SchemaExporter.AddDefaultXmlType(), and System.Runtime.Serialization.SchemaExporter.GetSchema().