Terraria: System.Runtime.Serialization.SchemaHelper.AddSchemaImport
AddSchemaImport()
static void System.Runtime.Serialization.SchemaHelper.AddSchemaImport (string ns, XmlSchema schema) inline static package
Definition at line 106 of file SchemaHelper.cs.
    {
        if (NamespacesEqual(ns, schema.TargetNamespace) || NamespacesEqual(ns, "http://www.w3.org/2001/XMLSchema") || NamespacesEqual(ns, "http://www.w3.org/2001/XMLSchema-instance"))
        {
            return;
        }
        foreach (XmlSchemaObject include in schema.Includes)
        {
            if (include is XmlSchemaImport && NamespacesEqual(ns, ((XmlSchemaImport)include).Namespace))
            {
                return;
            }
        }
        XmlSchemaImport xmlSchemaImport = new XmlSchemaImport();
        if (ns != null && ns.Length > 0)
        {
            xmlSchemaImport.Namespace = ns;
        }
        schema.Includes.Add(xmlSchemaImport);
    }
References System.Runtime.Serialization.Dictionary, System.Xml.Schema.Namespace, and System.Runtime.Serialization.SchemaHelper.NamespacesEqual().
Referenced by System.Runtime.Serialization.SchemaExporter.AddReferenceAttributes(), System.Runtime.Serialization.SchemaExporter.CreateTypeContent(), System.Runtime.Serialization.SchemaExporter.ExportClassDataContract(), System.Runtime.Serialization.SchemaExporter.ExportEnumDataContract(), System.Runtime.Serialization.SchemaExporter.ExportISerializableDataContract(), System.Runtime.Serialization.SchemaExporter.GetAnnotationMarkup(), and System.Runtime.Serialization.SchemaExporter.SetElementType().