Terraria: System.Net.Http.Headers.KnownHeader.Initialize
Initialize()
void System.Net.Http.Headers.KnownHeader.Initialize (int? http2StaticTableIndex, int? http3StaticTableIndex) inline private
Definition at line 47 of file KnownHeader.cs.
    {
        Http2EncodedName = (http2StaticTableIndex.HasValue ? HPackEncoder.EncodeLiteralHeaderFieldWithoutIndexingToAllocatedArray(http2StaticTableIndex.GetValueOrDefault()) : HPackEncoder.EncodeLiteralHeaderFieldWithoutIndexingNewNameToAllocatedArray(Name));
        Http3EncodedName = (http3StaticTableIndex.HasValue ? QPackEncoder.EncodeLiteralHeaderFieldWithStaticNameReferenceToArray(http3StaticTableIndex.GetValueOrDefault()) : QPackEncoder.EncodeLiteralHeaderFieldWithoutNameReferenceToArray(Name));
    }
References System.Net.Http.HPack.HPackEncoder.EncodeLiteralHeaderFieldWithoutIndexingNewNameToAllocatedArray(), System.Net.Http.HPack.HPackEncoder.EncodeLiteralHeaderFieldWithoutIndexingToAllocatedArray(), System.Net.Http.QPack.QPackEncoder.EncodeLiteralHeaderFieldWithoutNameReferenceToArray(), System.Net.Http.QPack.QPackEncoder.EncodeLiteralHeaderFieldWithStaticNameReferenceToArray(), System.Net.Http.Headers.KnownHeader.Http2EncodedName, System.Net.Http.Headers.KnownHeader.Http3EncodedName, and System.Net.Http.Headers.KnownHeader.Name.
Referenced by System.Net.Http.Headers.KnownHeader.KnownHeader().