Terraria: Terraria.Main.TextDisplayCache.PrepareCache
PrepareCache()
void Terraria.Main.TextDisplayCache.PrepareCache (string text) inline
Definition at line 152 of file Main.cs.
        {
            if (false | (screenWidth != _lastScreenWidth) | (screenHeight != _lastScreenHeight) | (_originalText != text) | (PlayerInput.CurrentInputMode != _lastInputMode))
            {
                _lastScreenWidth = screenWidth;
                _lastScreenHeight = screenHeight;
                _originalText = text;
                _lastInputMode = PlayerInput.CurrentInputMode;
                text = Lang.SupportGlyphs(text);
                TextLines = Utils.WordwrapString(text, FontAssets.MouseText.Value, 460, 10, out var lineAmount);
                AmountOfLines = lineAmount;
            }
        }
References Terraria.Main.TextDisplayCache._lastInputMode, Terraria.Main.TextDisplayCache._lastScreenHeight, Terraria.Main.TextDisplayCache._lastScreenWidth, Terraria.Main.TextDisplayCache._originalText, Terraria.Main.TextDisplayCache.AmountOfLines, Terraria.GameInput.PlayerInput.CurrentInputMode, Terraria.GameContent.FontAssets.MouseText, Terraria.Main.screenHeight, Terraria.Main.screenWidth, Terraria.Lang.SupportGlyphs(), Terraria.Main.TextDisplayCache.TextLines, ReLogic.Content.Asset< T >.Value, and Terraria.Utils.WordwrapString().
Referenced by Terraria.Main.GUIChatDrawInner().