Terraria: MS.Internal.Xml.XPath.AttributeQuery.MatchNode
MatchNode()
override XPathNavigator MS.Internal.Xml.XPath.AttributeQuery.MatchNode (XPathNavigator context) inline virtual
Reimplemented from MS.Internal.Xml.XPath.Query.
Definition at line 51 of file AttributeQuery.cs.
    {
        if (context != null && context.NodeType == XPathNodeType.Attribute && matches(context))
        {
            XPathNavigator xPathNavigator = context.Clone();
            if (xPathNavigator.MoveToParent())
            {
                return qyInput.MatchNode(xPathNavigator);
            }
        }
        return null;
    }
References System.Xml.XPath.XPathNavigator.Clone(), MS.Internal.Xml.XPath.BaseAxisQuery.matches(), MS.Internal.Xml.XPath.Query.MatchNode(), System.Xml.XPath.XPathNavigator.MoveToParent(), System.Xml.XPath.XPathNavigator.NodeType, and MS.Internal.Xml.XPath.BaseAxisQuery.qyInput.