Terraria: Lang.CreateDeathMessage
CreateDeathMessage()
static NetworkText Lang.CreateDeathMessage (string deadPlayerName, int plr = -1, int npc = -1, int proj = -1, int other = -1, int projType = 0, int plrItemType = 0) inline static
     {
         NetworkText networkText = NetworkText.Empty;
         NetworkText networkText2 = NetworkText.Empty;
         NetworkText networkText3 = NetworkText.Empty;
         NetworkText networkText4 = NetworkText.Empty;
         if (proj >= 0)
         {
             networkText = NetworkText.FromKey(GetProjectileName(projType).Key);
         }
         if (npc >= 0)
         {
             networkText2 = Main.npc[npc].GetGivenOrTypeNetName();
         }
         if (plr >= 0 && plr < 255)
         {
             networkText3 = NetworkText.FromLiteral(Main.player[plr].name);
         }
         if (plrItemType >= 0)
         {
             networkText4 = NetworkText.FromKey(GetItemName(plrItemType).Key);
         }
         bool flag = networkText != NetworkText.Empty;
         bool flag2 = plr >= 0 && plr < 255;
         bool flag3 = networkText2 != NetworkText.Empty;
         NetworkText result = NetworkText.Empty;
         NetworkText empty = NetworkText.Empty;
         empty = NetworkText.FromKey(Language.RandomFromCategory("DeathTextGeneric").Key, deadPlayerName, Main.worldName);
         if (flag2)
         {
             result = NetworkText.FromKey("DeathSource.Player", empty, networkText3, flag ? networkText : networkText4);
         }
         else if (flag3)
         {
             result = NetworkText.FromKey("DeathSource.NPC", empty, networkText2);
         }
         else if (flag)
         {
             result = NetworkText.FromKey("DeathSource.Projectile", empty, networkText);
         }
         else
         {
             switch (other)
             {
             case 0:
                 result = NetworkText.FromKey("DeathText.Fell_" + (Main.rand.Next(9) + 1), deadPlayerName);
                 break;
             case 1:
                 result = NetworkText.FromKey("DeathText.Drowned_" + (Main.rand.Next(7) + 1), deadPlayerName);
                 break;
             case 2:
                 result = NetworkText.FromKey("DeathText.Lava_" + (Main.rand.Next(5) + 1), deadPlayerName);
                 break;
             case 3:
                 result = NetworkText.FromKey("DeathText.Default", empty);
                 break;
             case 4:
                 result = NetworkText.FromKey("DeathText.Slain", deadPlayerName);
                 break;
             case 5:
                 result = NetworkText.FromKey("DeathText.Petrified_" + (Main.rand.Next(4) + 1), deadPlayerName);
                 break;
             case 6:
                 result = NetworkText.FromKey("DeathText.Stabbed", deadPlayerName);
                 break;
             case 7:
                 result = NetworkText.FromKey("DeathText.Suffocated_" + (Main.rand.Next(2) + 1), deadPlayerName);
                 break;
             case 8:
                 result = NetworkText.FromKey("DeathText.Burned_" + (Main.rand.Next(4) + 1), deadPlayerName);
                 break;
             case 9:
                 result = NetworkText.FromKey("DeathText.Poisoned", deadPlayerName);
                 break;
             case 10:
                 result = NetworkText.FromKey("DeathText.Electrocuted_" + (Main.rand.Next(4) + 1), deadPlayerName);
                 break;
             case 11:
                 result = NetworkText.FromKey("DeathText.TriedToEscape", deadPlayerName);
                 break;
             case 12:
                 result = NetworkText.FromKey("DeathText.WasLicked_" + (Main.rand.Next(2) + 1), deadPlayerName);
                 break;
             case 13:
                 result = NetworkText.FromKey("DeathText.Teleport_1", deadPlayerName);
                 break;
             case 14:
                 result = NetworkText.FromKey("DeathText.Teleport_2_Male", deadPlayerName);
                 break;
             case 15:
                 result = NetworkText.FromKey("DeathText.Teleport_2_Female", deadPlayerName);
                 break;
             case 16:
                 result = NetworkText.FromKey("DeathText.Inferno", deadPlayerName);
                 break;
             case 17:
                 result = NetworkText.FromKey("DeathText.DiedInTheDark", deadPlayerName);
                 break;
             case 18:
                 result = NetworkText.FromKey("DeathText.Starved_" + (Main.rand.Next(3) + 1), deadPlayerName);
                 break;
             case 19:
                 result = NetworkText.FromKey("DeathText.Space_" + (Main.rand.Next(5) + 1), deadPlayerName, Main.worldName);
                 break;
             case 254:
                 result = NetworkText.Empty;
                 break;
             case 255:
                 result = NetworkText.FromKey("DeathText.Slain", deadPlayerName);
                 break;
             }
         }
         return result;
     }
References NetworkText.Empty, NetworkText.FromKey(), NetworkText.FromLiteral(), NPC.GetGivenOrTypeNetName(), GetItemName(), GetProjectileName(), LocalizedText.Key, Player.name, UnifiedRandom.Next(), Main.npc, Main.player, Main.rand, Language.RandomFromCategory(), and Main.worldName.
Referenced by PlayerDeathReason.GetDeathText().