Terraria: Lang.InitializeLegacyLocalization
InitializeLegacyLocalization()
static void Lang.InitializeLegacyLocalization () inline static
     {
         FillNameCacheArray<PrefixID, int>("Prefix", prefix);
         for (int i = 0; i < gen.Length; i++)
         {
             gen[i] = Language.GetText("LegacyWorldGen." + i);
         }
         for (int j = 0; j < menu.Length; j++)
         {
             menu[j] = Language.GetText("LegacyMenu." + j);
         }
         for (int k = 0; k < inter.Length; k++)
         {
             inter[k] = Language.GetText("LegacyInterface." + k);
         }
         for (int l = 0; l < misc.Length; l++)
         {
             misc[l] = Language.GetText("LegacyMisc." + l);
         }
         for (int m = 0; m < mp.Length; m++)
         {
             mp[m] = Language.GetText("LegacyMultiplayer." + m);
         }
         for (int n = 0; n < tip.Length; n++)
         {
             tip[n] = Language.GetText("LegacyTooltip." + n);
         }
         for (int num = 0; num < chestType.Length; num++)
         {
             chestType[num] = Language.GetText("LegacyChestType." + num);
         }
         for (int num2 = 0; num2 < chestType2.Length; num2++)
         {
             chestType2[num2] = Language.GetText("LegacyChestType2." + num2);
         }
         for (int num3 = 0; num3 < dresserType.Length; num3++)
         {
             dresserType[num3] = Language.GetText("LegacyDresserType." + num3);
         }
         FillNameCacheArray<ItemID, short>("ItemName", _itemNameCache);
         FillNameCacheArray<ProjectileID, short>("ProjectileName", _projectileNameCache);
         FillNameCacheArray<NPCID, short>("NPCName", _npcNameCache);
         FillNameCacheArray<BuffID, int>("BuffName", _buffNameCache);
         FillNameCacheArray<BuffID, int>("BuffDescription", _buffDescriptionCache);
         FillNameCacheArray<EmoteID, int>("EmojiName", _emojiNameCache, leaveMissingEntriesBlank: true);
         for (int num4 = -65; num4 < 0; num4++)
         {
             _negativeNpcNameCache[-num4 - 1] = _npcNameCache[NPCID.FromNetId(num4)];
         }
         _negativeNpcNameCache[0] = Language.GetText("NPCName.Slimeling");
         _negativeNpcNameCache[1] = Language.GetText("NPCName.Slimer2");
         _negativeNpcNameCache[2] = Language.GetText("NPCName.GreenSlime");
         _negativeNpcNameCache[3] = Language.GetText("NPCName.Pinky");
         _negativeNpcNameCache[4] = Language.GetText("NPCName.BabySlime");
         _negativeNpcNameCache[5] = Language.GetText("NPCName.BlackSlime");
         _negativeNpcNameCache[6] = Language.GetText("NPCName.PurpleSlime");
         _negativeNpcNameCache[7] = Language.GetText("NPCName.RedSlime");
         _negativeNpcNameCache[8] = Language.GetText("NPCName.YellowSlime");
         _negativeNpcNameCache[9] = Language.GetText("NPCName.JungleSlime");
         _negativeNpcNameCache[53] = Language.GetText("NPCName.SmallRainZombie");
         _negativeNpcNameCache[54] = Language.GetText("NPCName.BigRainZombie");
         ItemTooltip.AddGlobalProcessor(SupportGlyphs);
         for (int num5 = 0; num5 < _itemTooltipCache.Length; num5++)
         {
             _itemTooltipCache[num5] = ItemTooltip.None;
         }
         (from f in typeof(ItemID).GetFields(BindingFlags.Static | BindingFlags.Public)
             where f.FieldType == typeof(short)
             select f).ToList().ForEach(delegate(FieldInfo field)
         {
             short num6 = (short)field.GetValue(null);
             if (num6 > 0 && num6 < _itemTooltipCache.Length)
             {
                 _itemTooltipCache[num6] = ItemTooltip.FromLanguageKey("ItemTooltip." + field.Name);
             }
         });
     }
References _buffDescriptionCache, _buffNameCache, _emojiNameCache, _itemNameCache, _itemTooltipCache, _negativeNpcNameCache, _npcNameCache, _projectileNameCache, ItemTooltip.AddGlobalProcessor(), chestType, chestType2, dresserType, ItemTooltip.FromLanguageKey(), NPCID.FromNetId(), gen, Language.GetText(), inter, menu, misc, mp, ItemTooltip.None, prefix, SupportGlyphs(), and tip.
Referenced by Program.RunGame().