Terraria: Lang.BartenderHelpText
BartenderHelpText()
static string Lang.BartenderHelpText (NPC npc) inline static
     {
         object obj = CreateDialogSubstitutionObject(npc);
         Player player = Main.player[Main.myPlayer];
         if (player.bartenderQuestLog == 0)
         {
             player.bartenderQuestLog++;
             Item item = new Item();
             item.SetDefaults(3817);
             item.stack = 10;
             item.position = player.Center;
             item = player.GetItem(player.whoAmI, item, GetItemSettings.NPCEntityToPlayerInventorySettings);
             if (item.stack > 0)
             {
                 int number = Item.NewItem(new EntitySource_Gift(npc), (int)player.position.X, (int)player.position.Y, player.width, player.height, item.type, item.stack, noBroadcast: false, 0, noGrabDelay: true);
                 if (Main.netMode == 1)
                 {
                     NetMessage.SendData(21, -1, -1, null, number, 1f);
                 }
             }
             return Language.GetTextValueWith("BartenderSpecialText.FirstHelp", obj);
         }
         LocalizedText[] array = Language.FindAll(CreateDialogFilter("BartenderHelpText.", obj));
         if (Main.BartenderHelpTextIndex >= array.Length)
         {
             Main.BartenderHelpTextIndex = 0;
         }
         return array[Main.BartenderHelpTextIndex++].FormatWith(obj);
     }
References Main.BartenderHelpTextIndex, Player.bartenderQuestLog, Entity.Center, CreateDialogFilter(), CreateDialogSubstitutionObject(), Language.FindAll(), LocalizedText.FormatWith(), Player.GetItem(), Language.GetTextValueWith(), Entity.height, Main.myPlayer, Main.netMode, Item.NewItem(), GetItemSettings.NPCEntityToPlayerInventorySettings, Main.player, Entity.position, NetMessage.SendData(), Item.SetDefaults(), Item.stack, Item.type, Entity.whoAmI, and Entity.width.
Referenced by Main.GUIChatDrawInner().