Terraria: Lang.SupportGlyphs
SupportGlyphs()
static string Lang.SupportGlyphs (string tooltip) inline static
     {
         if (tooltip.Contains("<right>"))
         {
             InputMode inputMode = InputMode.XBoxGamepad;
             if (PlayerInput.UsingGamepad)
             {
                 inputMode = InputMode.XBoxGamepadUI;
             }
             if (inputMode == InputMode.XBoxGamepadUI)
             {
                 KeyConfiguration keyConfiguration = PlayerInput.CurrentProfile.InputModes[inputMode];
                 string text = PlayerInput.BuildCommand("", true, keyConfiguration.KeyStatus["MouseRight"]);
                 text = text.Replace(": ", "");
                 tooltip = tooltip.Replace("<right>", text);
             }
             else
             {
                 tooltip = tooltip.Replace("<right>", Language.GetTextValue("Controls.RightClick"));
             }
         }
         if (tooltip.Contains("<left>"))
         {
             InputMode inputMode2 = InputMode.XBoxGamepad;
             if (PlayerInput.UsingGamepad)
             {
                 inputMode2 = InputMode.XBoxGamepadUI;
             }
             if (inputMode2 == InputMode.XBoxGamepadUI)
             {
                 KeyConfiguration keyConfiguration2 = PlayerInput.CurrentProfile.InputModes[inputMode2];
                 string text2 = PlayerInput.BuildCommand("", true, keyConfiguration2.KeyStatus["MouseLeft"]);
                 text2 = text2.Replace(": ", "");
                 tooltip = tooltip.Replace("<left>", text2);
             }
             else
             {
                 tooltip = tooltip.Replace("<left>", Language.GetTextValue("Controls.LeftClick"));
             }
         }
         return tooltip;
     }
References PlayerInput.BuildCommand(), PlayerInput.CurrentProfile, Language.GetTextValue(), PlayerInputProfile.InputModes, KeyConfiguration.KeyStatus, and PlayerInput.UsingGamepad.
Referenced by GameTipsDisplay.GameTip.GameTip(), InitializeLegacyLocalization(), and Main.TextDisplayCache.PrepareCache().