Terraria: Lang.GetNPCName
GetNPCName()
static LocalizedText Lang.GetNPCName (int netID) inline static
     {
         if (netID > 0 && netID < NPCID.Count)
         {
             return _npcNameCache[netID];
         }
         if (netID < 0 && -netID - 1 < _negativeNpcNameCache.Length)
         {
             return _negativeNpcNameCache[-netID - 1];
         }
         return LocalizedText.Empty;
     }
References _negativeNpcNameCache, _npcNameCache, NPCID.Count, and LocalizedText.Empty.
Referenced by NPC.CountKillForBannersAndDropThem(), BestiaryEntry.Critter(), BestiaryEntry.Enemy(), GetInvasionWaveText(), GetNPCNameValue(), NPC.GetTypeNetName(), NPC.SpawnSkeletron(), and BestiaryEntry.TownNPC().