Terraria: Lang.CreateDialogSubstitutionObject
CreateDialogSubstitutionObject()
static object Lang.CreateDialogSubstitutionObject (NPC npc = null) inline static
     {
         return new
         {
             Nurse = NPC.GetFirstNPCNameOrNull(18),
             Merchant = NPC.GetFirstNPCNameOrNull(17),
             ArmsDealer = NPC.GetFirstNPCNameOrNull(19),
             Dryad = NPC.GetFirstNPCNameOrNull(20),
             Demolitionist = NPC.GetFirstNPCNameOrNull(38),
             Clothier = NPC.GetFirstNPCNameOrNull(54),
             Guide = NPC.GetFirstNPCNameOrNull(22),
             Wizard = NPC.GetFirstNPCNameOrNull(108),
             GoblinTinkerer = NPC.GetFirstNPCNameOrNull(107),
             Mechanic = NPC.GetFirstNPCNameOrNull(124),
             Truffle = NPC.GetFirstNPCNameOrNull(160),
             Steampunker = NPC.GetFirstNPCNameOrNull(178),
             DyeTrader = NPC.GetFirstNPCNameOrNull(207),
             PartyGirl = NPC.GetFirstNPCNameOrNull(208),
             Cyborg = NPC.GetFirstNPCNameOrNull(209),
             Painter = NPC.GetFirstNPCNameOrNull(227),
             WitchDoctor = NPC.GetFirstNPCNameOrNull(228),
             Pirate = NPC.GetFirstNPCNameOrNull(229),
             Stylist = NPC.GetFirstNPCNameOrNull(353),
             TravelingMerchant = NPC.GetFirstNPCNameOrNull(368),
             Angler = NPC.GetFirstNPCNameOrNull(369),
             Bartender = NPC.GetFirstNPCNameOrNull(550),
             WorldName = Main.worldName,
             Day = Main.dayTime,
             BloodMoon = Main.bloodMoon,
             Eclipse = Main.eclipse,
             MoonLordDefeated = NPC.downedMoonlord,
             GolemDefeated = NPC.downedGolemBoss,
             DukeFishronDefeated = NPC.downedFishron,
             FrostLegionDefeated = NPC.downedFrost,
             MartiansDefeated = NPC.downedMartians,
             PumpkingDefeated = NPC.downedHalloweenKing,
             IceQueenDefeated = NPC.downedChristmasIceQueen,
             HardMode = Main.hardMode,
             Homeless = (npc?.homeless ?? false),
             InventoryKey = Main.cInv,
             PlayerName = Main.player[Main.myPlayer].name,
             GolfGuy = NPC.GetFirstNPCNameOrNull(588),
             TaxCollector = NPC.GetFirstNPCNameOrNull(441),
             Rain = Main.raining,
             Graveyard = Main.LocalPlayer.ZoneGraveyard,
             AnglerCompletedQuestsCount = Main.LocalPlayer.anglerQuestsFinished,
             TotalDeathsCount = Main.LocalPlayer.numberOfDeathsPVE,
             WorldEvilStone = (WorldGen.crimson ? Language.GetTextValue("Misc.Crimstone") : Language.GetTextValue("Misc.Ebonstone")),
             InputTriggerUI_BuildFromInventory = PlayerInput.GenerateInputTag_ForCurrentGamemode(tagForGameplay: false, "QuickMount"),
             InputTriggerUI_SellItem = PlayerInput.GenerateInputTag_ForCurrentGamemode(tagForGameplay: false, "SmartSelect"),
             InputTriggerUI_Trash = PlayerInput.GenerateInputTag_ForCurrentGamemode_WithHacks(tagForGameplay: false, "SmartSelect"),
             InputTriggerUI_FavoriteItem = PlayerInput.GenerateInputTag_ForCurrentGamemode_WithHacks(tagForGameplay: false, "SmartCursor"),
             InputTrigger_QuickEquip = PlayerInput.GenerateInputTag_ForCurrentGamemode(tagForGameplay: false, "Grapple"),
             InputTrigger_LockOn = PlayerInput.GenerateInputTag_ForCurrentGamemode(tagForGameplay: true, "LockOn"),
             InputTrigger_RadialQuickbar = PlayerInput.GenerateInputTag_ForCurrentGamemode(tagForGameplay: true, "HotbarMinus"),
             InputTrigger_RadialHotbar = PlayerInput.GenerateInputTag_ForCurrentGamemode(tagForGameplay: true, "HotbarPlus"),
             InputTrigger_SmartCursor = PlayerInput.GenerateInputTag_ForCurrentGamemode(tagForGameplay: true, "SmartCursor"),
             InputTrigger_UseOrAttack = PlayerInput.GenerateInputTag_ForCurrentGamemode(tagForGameplay: true, "MouseLeft"),
             InputTrigger_InteractWithTile = PlayerInput.GenerateInputTag_ForCurrentGamemode(tagForGameplay: true, "MouseRight"),
             InputTrigger_SmartSelect = PlayerInput.GenerateInputTag_ForCurrentGamemode(tagForGameplay: true, "SmartSelect")
         };
     }
References Player.anglerQuestsFinished, Main.bloodMoon, Main.cInv, WorldGen.crimson, Main.dayTime, NPC.downedChristmasIceQueen, NPC.downedFishron, NPC.downedFrost, NPC.downedGolemBoss, NPC.downedHalloweenKing, NPC.downedMartians, NPC.downedMoonlord, Main.eclipse, PlayerInput.GenerateInputTag_ForCurrentGamemode(), PlayerInput.GenerateInputTag_ForCurrentGamemode_WithHacks(), NPC.GetFirstNPCNameOrNull(), Language.GetTextValue(), Main.hardMode, Main.LocalPlayer, Main.myPlayer, Player.name, Player.numberOfDeathsPVE, Main.player, Main.raining, Main.worldName, and Player.ZoneGraveyard.
Referenced by GameTipsDisplay.GameTip.GameTip(), AnglerQuestChat(), AnglerQuestCountChat(), BartenderChat(), BartenderHelpText(), BestiaryGirlChat(), BunnyChat(), CatChat(), dialog(), DogChat(), DyeTraderQuestChat(), NPC.GetChat(), HelpCommand.GetCommandAliasesByID(), GolferChat(), NPC.HasLuckTextForWizard(), NPC.HasSpecialEventText(), Main.HelpText(), PrincessChat(), and SlimeChat().