Terraria: ChestUI.RenameChestSubmit
RenameChestSubmit()
static void ChestUI.RenameChestSubmit (Player player) inline static
     {
         SoundEngine.PlaySound(12);
         Main.editChest = false;
         int chest = player.chest;
         if (chest < 0)
         {
             return;
         }
         if (Main.npcChatText == Main.defaultChestName)
         {
             Main.npcChatText = "";
         }
         if (Main.chest[chest].name != Main.npcChatText)
         {
             Main.chest[chest].name = Main.npcChatText;
             if (Main.netMode == 1)
             {
                 player.editedChestName = true;
             }
         }
     }
References Main.chest, Player.chest, Main.defaultChestName, Main.editChest, Player.editedChestName, Chest.name, Main.netMode, Main.npcChatText, and SoundEngine.PlaySound().
Referenced by UIVirtualKeyboard.DrawSelf(), Main.InputTextChest(), and RenameChest().