Terraria: ChestUI.GetContainerUsageInfo
GetContainerUsageInfo()
static void ChestUI.GetContainerUsageInfo (out bool sync, out Item[] chestinv) inline static
     {
         sync = false;
         Player player = Main.player[Main.myPlayer];
         chestinv = player.bank.item;
         if (player.chest > -1)
         {
             chestinv = Main.chest[player.chest].item;
             sync = Main.netMode == 1;
         }
         else if (player.chest == -2)
         {
             chestinv = player.bank.item;
         }
         else if (player.chest == -3)
         {
             chestinv = player.bank2.item;
         }
         else if (player.chest == -4)
         {
             chestinv = player.bank3.item;
         }
         else if (player.chest == -5)
         {
             chestinv = player.bank4.item;
         }
     }
References Player.bank, Player.bank2, Player.bank3, Player.bank4, Main.chest, Player.chest, Chest.item, Main.myPlayer, Main.netMode, and Main.player.
Referenced by Main.MouseText_DrawItemTooltip_GetLinesInfo(), ItemSlot.PickItemMovementAction(), and TryPlacingInChest().