Terraria: ChestUI.DrawSlots
DrawSlots()
static void ChestUI.DrawSlots (SpriteBatch spriteBatch) inline static private
     {
         Player player = Main.player[Main.myPlayer];
         int context = 0;
         Item[] inv = null;
         if (player.chest > -1)
         {
             context = 3;
             inv = Main.chest[player.chest].item;
         }
         if (player.chest == -2)
         {
             context = 4;
             inv = player.bank.item;
         }
         if (player.chest == -3)
         {
             context = 4;
             inv = player.bank2.item;
         }
         if (player.chest == -4)
         {
             context = 4;
             inv = player.bank3.item;
         }
         if (player.chest == -5)
         {
             context = 32;
             inv = player.bank4.item;
         }
         Main.inventoryScale = 0.755f;
         if (Utils.FloatIntersect(Main.mouseX, Main.mouseY, 0f, 0f, 73f, Main.instance.invBottom, 560f * Main.inventoryScale, 224f * Main.inventoryScale) && !PlayerInput.IgnoreMouseInterface)
         {
             player.mouseInterface = true;
         }
         for (int i = 0; i < 10; i++)
         {
             for (int j = 0; j < 4; j++)
             {
                 int num = (int)(73f + (float)(i * 56) * Main.inventoryScale);
                 int num2 = (int)((float)Main.instance.invBottom + (float)(j * 56) * Main.inventoryScale);
                 int slot = i + j * 10;
                 new Color(100, 100, 100, 100);
                 if (Utils.FloatIntersect(Main.mouseX, Main.mouseY, 0f, 0f, num, num2, (float)TextureAssets.InventoryBack.Width() * Main.inventoryScale, (float)TextureAssets.InventoryBack.Height() * Main.inventoryScale) && !PlayerInput.IgnoreMouseInterface)
                 {
                     player.mouseInterface = true;
                     ItemSlot.Handle(inv, context, slot);
                 }
                 ItemSlot.Draw(spriteBatch, inv, context, slot, new Vector2(num, num2));
             }
         }
     }
References Player.bank, Player.bank2, Player.bank3, Player.bank4, Main.chest, Player.chest, Color, ItemSlot.Draw(), Utils.FloatIntersect(), ItemSlot.Handle(), PlayerInput.IgnoreMouseInterface, Main.instance, Main.invBottom, TextureAssets.InventoryBack, Main.inventoryScale, Chest.item, Player.mouseInterface, Main.mouseX, Main.mouseY, Main.myPlayer, and Main.player.
Referenced by Draw().