Terraria: ChestUI.Draw
Draw()
static void ChestUI.Draw (SpriteBatch spritebatch) inline static
     {
         if (Main.player[Main.myPlayer].chest != -1 && !Main.recBigList)
         {
             Main.inventoryScale = 0.755f;
             if (Utils.FloatIntersect(Main.mouseX, Main.mouseY, 0f, 0f, 73f, Main.instance.invBottom, 560f * Main.inventoryScale, 224f * Main.inventoryScale))
             {
                 Main.player[Main.myPlayer].mouseInterface = true;
             }
             DrawName(spritebatch);
             DrawButtons(spritebatch);
             DrawSlots(spritebatch);
         }
         else
         {
             for (int i = 0; i < ButtonID.Count; i++)
             {
                 ButtonScale[i] = 0.75f;
                 ButtonHovered[i] = false;
             }
         }
     }
References ButtonHovered, ButtonScale, Player.chest, ChestUI.ButtonID.Count, DrawButtons(), DrawName(), DrawSlots(), Utils.FloatIntersect(), Main.instance, Main.invBottom, Main.inventoryScale, Player.mouseInterface, Main.mouseX, Main.mouseY, Main.myPlayer, Main.player, and Main.recBigList.
Referenced by Main.DrawInventory().