Terraria: ChestUI.DrawName
DrawName()
static void ChestUI.DrawName (SpriteBatch spritebatch) inline static private
     {
         Player player = Main.player[Main.myPlayer];
         string text = string.Empty;
         if (Main.editChest)
         {
             text = Main.npcChatText;
             Main.instance.textBlinkerCount++;
             if (Main.instance.textBlinkerCount >= 20)
             {
                 if (Main.instance.textBlinkerState == 0)
                 {
                     Main.instance.textBlinkerState = 1;
                 }
                 else
                 {
                     Main.instance.textBlinkerState = 0;
                 }
                 Main.instance.textBlinkerCount = 0;
             }
             if (Main.instance.textBlinkerState == 1)
             {
                 text += "|";
             }
             Main.instance.DrawWindowsIMEPanel(new Vector2(120f, 518f));
         }
         else if (player.chest > -1)
         {
             if (Main.chest[player.chest] == null)
             {
                 Main.chest[player.chest] = new Chest();
             }
             Chest chest = Main.chest[player.chest];
             if (chest.name != "")
             {
                 text = chest.name;
             }
             else
             {
                 Tile tile = Main.tile[player.chestX, player.chestY];
                 if (tile.type == 21)
                 {
                     text = Lang.chestType[tile.frameX / 36].Value;
                 }
                 else if (tile.type == 467 && tile.frameX / 36 == 4)
                 {
                     text = Lang.GetItemNameValue(3988);
                 }
                 else if (tile.type == 467)
                 {
                     text = Lang.chestType2[tile.frameX / 36].Value;
                 }
                 else if (tile.type == 88)
                 {
                     text = Lang.dresserType[tile.frameX / 54].Value;
                 }
             }
         }
         else if (player.chest == -2)
         {
             text = Lang.inter[32].Value;
         }
         else if (player.chest == -3)
         {
             text = Lang.inter[33].Value;
         }
         else if (player.chest == -4)
         {
             text = Lang.GetItemNameValue(3813);
         }
         else if (player.chest == -5)
         {
             text = Lang.GetItemNameValue(4076);
         }
         Color color = new Color(Main.mouseTextColor, Main.mouseTextColor, Main.mouseTextColor, Main.mouseTextColor);
         color = Color.White * (1f - (255f - (float)(int)Main.mouseTextColor) / 255f * 0.5f);
         color.A = byte.MaxValue;
         Utils.WordwrapString(text, FontAssets.MouseText.Value, 200, 1, out var lineAmount);
         lineAmount++;
         for (int i = 0; i < lineAmount; i++)
         {
             ChatManager.DrawColorCodedStringWithShadow(spritebatch, FontAssets.MouseText.Value, text, new Vector2(504f, Main.instance.invBottom + i * 26), color, 0f, Vector2.Zero, Vector2.One, -1f, 1.5f);
         }
     }
References Main.chest, Player.chest, Lang.chestType, Lang.chestType2, Player.chestX, Player.chestY, Color, ChatManager.DrawColorCodedStringWithShadow(), Main.DrawWindowsIMEPanel(), Lang.dresserType, Main.editChest, Tile.frameX, Lang.GetItemNameValue(), Main.instance, Lang.inter, Main.invBottom, FontAssets.MouseText, Main.mouseTextColor, Main.myPlayer, Chest.name, Main.npcChatText, Main.player, Main.textBlinkerCount, Main.textBlinkerState, Main.tile, Tile.type, Asset< T >.Value, LocalizedText.Value, and Utils.WordwrapString().
Referenced by Draw().