Terraria: ChestUI.Restock
Restock()
static void ChestUI.Restock () inline static
     {
         Player player = Main.player[Main.myPlayer];
         Item[] inventory = player.inventory;
         Item[] item = player.bank.item;
         if (player.chest > -1)
         {
             item = Main.chest[player.chest].item;
         }
         else if (player.chest == -2)
         {
             item = player.bank.item;
         }
         else if (player.chest == -3)
         {
             item = player.bank2.item;
         }
         else if (player.chest == -4)
         {
             item = player.bank3.item;
         }
         else if (player.chest == -5)
         {
             item = player.bank4.item;
         }
         HashSet<int> hashSet = new HashSet<int>();
         List<int> list = new List<int>();
         List<int> list2 = new List<int>();
         for (int num = 57; num >= 0; num--)
         {
             if ((num < 50 || num >= 54) && (inventory[num].type < 71 || inventory[num].type > 74))
             {
                 if (inventory[num].stack > 0 && inventory[num].maxStack > 1 && inventory[num].prefix == 0)
                 {
                     hashSet.Add(inventory[num].netID);
                     if (inventory[num].stack < inventory[num].maxStack)
                     {
                         list.Add(num);
                     }
                 }
                 else if (inventory[num].stack == 0 || inventory[num].netID == 0 || inventory[num].type == 0)
                 {
                     list2.Add(num);
                 }
             }
         }
         bool flag = false;
         for (int i = 0; i < item.Length; i++)
         {
             if (item[i].stack < 1 || item[i].prefix != 0 || !hashSet.Contains(item[i].netID))
             {
                 continue;
             }
             bool flag2 = false;
             for (int j = 0; j < list.Count; j++)
             {
                 int num2 = list[j];
                 int context = 0;
                 if (num2 >= 50)
                 {
                     context = 2;
                 }
                 if (inventory[num2].netID != item[i].netID || ItemSlot.PickItemMovementAction(inventory, context, num2, item[i]) == -1)
                 {
                     continue;
                 }
                 int num3 = item[i].stack;
                 if (inventory[num2].maxStack - inventory[num2].stack < num3)
                 {
                     num3 = inventory[num2].maxStack - inventory[num2].stack;
                 }
                 inventory[num2].stack += num3;
                 item[i].stack -= num3;
                 flag = true;
                 if (inventory[num2].stack == inventory[num2].maxStack)
                 {
                     if (Main.netMode == 1 && Main.player[Main.myPlayer].chest > -1)
                     {
                         NetMessage.SendData(32, -1, -1, null, Main.player[Main.myPlayer].chest, i);
                     }
                     list.RemoveAt(j);
                     j--;
                 }
                 if (item[i].stack == 0)
                 {
                     item[i] = new Item();
                     flag2 = true;
                     if (Main.netMode == 1 && Main.player[Main.myPlayer].chest > -1)
                     {
                         NetMessage.SendData(32, -1, -1, null, Main.player[Main.myPlayer].chest, i);
                     }
                     break;
                 }
             }
             if (flag2 || list2.Count <= 0 || item[i].ammo == 0)
             {
                 continue;
             }
             for (int k = 0; k < list2.Count; k++)
             {
                 int context2 = 0;
                 if (list2[k] >= 50)
                 {
                     context2 = 2;
                 }
                 if (ItemSlot.PickItemMovementAction(inventory, context2, list2[k], item[i]) != -1)
                 {
                     Utils.Swap(ref inventory[list2[k]], ref item[i]);
                     if (Main.netMode == 1 && Main.player[Main.myPlayer].chest > -1)
                     {
                         NetMessage.SendData(32, -1, -1, null, Main.player[Main.myPlayer].chest, i);
                     }
                     list.Add(list2[k]);
                     list2.RemoveAt(k);
                     flag = true;
                     break;
                 }
             }
         }
         if (flag)
         {
             SoundEngine.PlaySound(7);
         }
     }
References Item.ammo, Player.bank, Player.bank2, Player.bank3, Player.bank4, Main.chest, Player.chest, Player.inventory, Chest.item, Item.maxStack, Main.myPlayer, Item.netID, Main.netMode, ItemSlot.PickItemMovementAction(), Main.player, SoundEngine.PlaySound(), NetMessage.SendData(), and Item.stack.
Referenced by DrawButton().