Terraria: ChromaShader.BindProcessors
BindProcessors()
void ChromaShader.BindProcessors () inline private inherited
     {
         MethodInfo[] methods = GetType().GetMethods(BindingFlags.DeclaredOnly | BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic);
         foreach (MethodInfo methodInfo in methods)
         {
             RgbProcessorAttribute rgbProcessorAttribute = (RgbProcessorAttribute)Attribute.GetCustomAttribute(methodInfo, typeof(RgbProcessorAttribute));
             if (rgbProcessorAttribute != null)
             {
                 Processor processor = (Processor)Delegate.CreateDelegate(typeof(Processor), this, methodInfo, throwOnBindFailure: false);
                 if (processor != null)
                 {
                     BindProcessor(processor, rgbProcessorAttribute);
                 }
             }
         }
     }
References ChromaShader.BindProcessor(), and ChromaShader.Processor().
Referenced by ChromaShader.ChromaShader().