Terraria: System.Xml.Schema.XNodeValidator.Validate
Validate()
void System.Xml.Schema.XNodeValidator.Validate (XObject source, XmlSchemaObject partialValidationType, bool addSchemaInfo) inline
Definition at line 38 of file XNodeValidator.cs.
    {
        this.source = source;
        this.addSchemaInfo = addSchemaInfo;
        XmlSchemaValidationFlags xmlSchemaValidationFlags = XmlSchemaValidationFlags.AllowXmlAttributes;
        XmlNodeType nodeType = source.NodeType;
        if (nodeType != XmlNodeType.Element)
        {
            if (nodeType != XmlNodeType.Attribute)
            {
                if (nodeType != XmlNodeType.Document)
                {
                    goto IL_0066;
                }
                source = ((XDocument)source).Root;
                if (source == null)
                {
                    throw new InvalidOperationException(System.SR.InvalidOperation_MissingRoot);
                }
                xmlSchemaValidationFlags |= XmlSchemaValidationFlags.ProcessIdentityConstraints;
            }
            else
            {
                if (((XAttribute)source).IsNamespaceDeclaration)
                {
                    goto IL_0066;
                }
                if (source.Parent == null)
                {
                    throw new InvalidOperationException(System.SR.InvalidOperation_MissingParent);
                }
            }
        }
        namespaceManager = new XmlNamespaceManager(schemas.NameTable);
        PushAncestorsAndSelf(source.Parent);
        validator = new XmlSchemaValidator(schemas.NameTable, schemas, namespaceManager, xmlSchemaValidationFlags);
        validator.ValidationEventHandler += ValidationCallback;
        validator.XmlResolver = null;
        if (partialValidationType != null)
        {
            validator.Initialize(partialValidationType);
        }
        else
        {
            validator.Initialize();
        }
        IXmlLineInfo originalLineInfo = SaveLineInfo(source);
        if (nodeType == XmlNodeType.Attribute)
        {
            ValidateAttribute((XAttribute)source);
        }
        else
        {
            ValidateElement((XElement)source);
        }
        validator.EndValidation();
        RestoreLineInfo(originalLineInfo);
        return;
        IL_0066:
        throw new InvalidOperationException(System.SR.Format(System.SR.InvalidOperation_BadNodeType, nodeType));
    }
References System.Xml.Schema.XNodeValidator.addSchemaInfo, System.Xml.Dictionary, System.Xml.Schema.XmlSchemaValidator.EndValidation(), System.SR.Format(), System.Xml.Schema.XmlSchemaValidator.Initialize(), System.SR.InvalidOperation_BadNodeType, System.SR.InvalidOperation_MissingParent, System.SR.InvalidOperation_MissingRoot, System.Xml.Schema.XNodeValidator.namespaceManager, System.Xml.Schema.XmlSchemaSet.NameTable, System.Xml.Linq.XObject.NodeType, System.Xml.Linq.XObject.Parent, System.Xml.Schema.XNodeValidator.PushAncestorsAndSelf(), System.Xml.Schema.XNodeValidator.RestoreLineInfo(), System.Xml.Schema.XNodeValidator.SaveLineInfo(), System.Xml.Schema.XNodeValidator.schemas, System.Xml.Schema.XNodeValidator.source, System.Xml.Schema.XNodeValidator.ValidateAttribute(), System.Xml.Schema.XNodeValidator.ValidateElement(), System.Xml.Schema.XNodeValidator.ValidationCallback(), and System.Xml.Schema.XNodeValidator.validator.
Referenced by System.Xml.Schema.Extensions.Validate(), System.Xml.Schema.Extensions.Validate(), and System.Xml.Schema.Extensions.Validate().