Terraria: System.Net.Http.StreamToStreamCopy.CopyAsync
CopyAsync()
static Task System.Net.Http.StreamToStreamCopy.CopyAsync (Stream source, Stream destination, int bufferSize, bool disposeSource, CancellationToken cancellationToken = default(CancellationToken)) inline static
Definition at line 25 of file StreamToStreamCopy.cs.
    {
        try
        {
            Task task = ((bufferSize == 0) ? source.CopyToAsync(destination, cancellationToken) : source.CopyToAsync(destination, bufferSize, cancellationToken));
            if (!disposeSource)
            {
                return task;
            }
            switch (task.Status)
            {
            case TaskStatus.RanToCompletion:
                DisposeSource(source);
                return Task.CompletedTask;
            case TaskStatus.Canceled:
            case TaskStatus.Faulted:
                return task;
            default:
                return DisposeSourceAsync(task, source);
            }
        }
        catch (Exception exception)
        {
            return Task.FromException(exception);
        }
        static async Task DisposeSourceAsync(Task copyTask, Stream source)
        {
            await copyTask.ConfigureAwait(continueOnCapturedContext: false);
            DisposeSource(source);
        }
    }
References System.cancellationToken, System.Threading.Tasks.Task< TResult >.CompletedTask, System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.destination, System.Net.Http.StreamToStreamCopy.DisposeSource(), System.exception, System.Threading.Tasks.Task< TResult >.FromException(), System.source, and System.task.
Referenced by System.Net.Http.StreamContent.SerializeToStreamAsyncCore().