Terraria: System.Xml.Schema.XNodeValidator.PushElement
PushElement()
void System.Xml.Schema.XNodeValidator.PushElement (XElement e, ref string xsiType, ref string xsiNil) inline private
Definition at line 224 of file XNodeValidator.cs.
    {
        namespaceManager.PushScope();
        XAttribute xAttribute = e.lastAttr;
        if (xAttribute == null)
        {
            return;
        }
        do
        {
            xAttribute = xAttribute.next;
            if (xAttribute.IsNamespaceDeclaration)
            {
                string text = xAttribute.Name.LocalName;
                if (text == "xmlns")
                {
                    text = string.Empty;
                }
                namespaceManager.AddNamespace(text, xAttribute.Value);
                continue;
            }
            XName name = xAttribute.Name;
            if (name == xsiTypeName)
            {
                xsiType = xAttribute.Value;
            }
            else if (name == xsiNilName)
            {
                xsiNil = xAttribute.Value;
            }
        }
        while (xAttribute != e.lastAttr);
    }
References System.Xml.XmlNamespaceManager.AddNamespace(), System.Xml.Linq.XElement.lastAttr, System.Xml.Schema.XNodeValidator.namespaceManager, System.Xml.XmlNamespaceManager.PushScope(), System.text, System.Xml.Schema.XNodeValidator.xsiNilName, and System.Xml.Schema.XNodeValidator.xsiTypeName.
Referenced by System.Xml.Schema.XNodeValidator.ValidateElement().