Terraria: System.Xml.Schema.XNodeValidator.PushAncestorsAndSelf
PushAncestorsAndSelf()
void System.Xml.Schema.XNodeValidator.PushAncestorsAndSelf (XElement e) inline private
Definition at line 195 of file XNodeValidator.cs.
    {
        while (e != null)
        {
            XAttribute xAttribute = e.lastAttr;
            if (xAttribute != null)
            {
                do
                {
                    xAttribute = xAttribute.next;
                    if (xAttribute.IsNamespaceDeclaration)
                    {
                        string text = xAttribute.Name.LocalName;
                        if (text == "xmlns")
{
                            text = string.Empty;
                        }
                        if (!namespaceManager.HasNamespace(text))
{
                            namespaceManager.AddNamespace(text, xAttribute.Value);
                        }
                    }
                }
                while (xAttribute != e.lastAttr);
            }
            e = e.parent as XElement;
        }
    }
References System.Xml.XmlNamespaceManager.AddNamespace(), System.Xml.Dictionary, System.Xml.XmlNamespaceManager.HasNamespace(), System.Xml.Linq.XElement.lastAttr, System.Xml.Schema.XNodeValidator.namespaceManager, and System.text.
Referenced by System.Xml.Schema.XNodeValidator.Validate().