Terraria: System.Xml.Schema.XNodeValidator.ValidateNodes
ValidateNodes()
void System.Xml.Schema.XNodeValidator.ValidateNodes (XElement e) inline private
Definition at line 346 of file XNodeValidator.cs.
    {
        XNode xNode = e.content as XNode;
        IXmlLineInfo originalLineInfo = SaveLineInfo(xNode);
        if (xNode != null)
        {
            do
            {
                xNode = xNode.next;
                if (xNode is XElement e2)
                {
                    ValidateElement(e2);
                }
                else if (xNode is XText xText)
                {
                    string value = xText.Value;
                    if (value.Length > 0)
                    {
                        validator.LineInfoProvider = xText;
                        validator.ValidateText(value);
                    }
                }
            }
            while (xNode != e.content);
            source = e;
        }
        else if (e.content is string { Length: >0 } text)
        {
            validator.ValidateText(text);
        }
        RestoreLineInfo(originalLineInfo);
    }
References System.Xml.Linq.XContainer.content, System.Xml.Dictionary, System.Xml.Schema.XNodeValidator.RestoreLineInfo(), System.Xml.Schema.XNodeValidator.SaveLineInfo(), System.Xml.Schema.XNodeValidator.source, System.text, System.Xml.Schema.XNodeValidator.ValidateElement(), System.Xml.Schema.XmlSchemaValidator.ValidateText(), System.Xml.Schema.XNodeValidator.validator, and System.value.
Referenced by System.Xml.Schema.XNodeValidator.ValidateElement().