Terraria: System.Xml.Schema.XNodeValidator.ValidateAttribute
ValidateAttribute()
void System.Xml.Schema.XNodeValidator.ValidateAttribute (XAttribute a) inline private
Definition at line 270 of file XNodeValidator.cs.
    {
        IXmlLineInfo originalLineInfo = SaveLineInfo(a);
        XmlSchemaInfo schemaInfo = (addSchemaInfo ? new XmlSchemaInfo() : null);
        source = a;
        validator.ValidateAttribute(a.Name.LocalName, a.Name.NamespaceName, a.Value, schemaInfo);
        if (addSchemaInfo)
        {
            ReplaceSchemaInfo(a, schemaInfo);
        }
        RestoreLineInfo(originalLineInfo);
    }
References System.Xml.Schema.XNodeValidator.addSchemaInfo, System.Xml.Dictionary, System.Xml.Schema.XNodeValidator.ReplaceSchemaInfo(), System.Xml.Schema.XNodeValidator.RestoreLineInfo(), System.Xml.Schema.XNodeValidator.SaveLineInfo(), System.Xml.Schema.XNodeValidator.source, System.Xml.Schema.XmlSchemaValidator.ValidateAttribute(), and System.Xml.Schema.XNodeValidator.validator.
Referenced by System.Xml.Schema.XNodeValidator.Validate(), and System.Xml.Schema.XNodeValidator.ValidateAttributes().