Terraria: System.Xml.Schema.XNodeValidator.ValidateAttributes
ValidateAttributes()
void System.Xml.Schema.XNodeValidator.ValidateAttributes (XElement e) inline private
Definition at line 283 of file XNodeValidator.cs.
    {
        XAttribute xAttribute = e.lastAttr;
        IXmlLineInfo originalLineInfo = SaveLineInfo(xAttribute);
        if (xAttribute != null)
        {
            do
            {
                xAttribute = xAttribute.next;
                if (!xAttribute.IsNamespaceDeclaration)
                {
                    ValidateAttribute(xAttribute);
                }
            }
            while (xAttribute != e.lastAttr);
            source = e;
        }
        if (addSchemaInfo)
        {
            if (defaultAttributes == null)
            {
                defaultAttributes = new ArrayList();
            }
            else
            {
                defaultAttributes.Clear();
            }
            validator.GetUnspecifiedDefaultAttributes(defaultAttributes);
            foreach (XmlSchemaAttribute defaultAttribute in defaultAttributes)
            {
                xAttribute = new XAttribute(XNamespace.Get(defaultAttribute.QualifiedName.Namespace).GetName(defaultAttribute.QualifiedName.Name), GetDefaultValue(defaultAttribute));
                ReplaceSchemaInfo(xAttribute, GetDefaultAttributeSchemaInfo(defaultAttribute));
                e.Add(xAttribute);
            }
        }
        RestoreLineInfo(originalLineInfo);
    }
References System.Xml.Linq.XContainer.Add(), System.Xml.Schema.XNodeValidator.addSchemaInfo, System.Collections.ArrayList.Clear(), System.Xml.Schema.XNodeValidator.defaultAttributes, System.Xml.Linq.XNamespace.Get(), System.Xml.Schema.XNodeValidator.GetDefaultAttributeSchemaInfo(), System.Xml.Schema.XNodeValidator.GetDefaultValue(), System.Xml.Schema.XmlSchemaValidator.GetUnspecifiedDefaultAttributes(), System.Xml.Linq.XElement.lastAttr, System.Xml.Schema.XNodeValidator.ReplaceSchemaInfo(), System.Xml.Schema.XNodeValidator.RestoreLineInfo(), System.Xml.Schema.XNodeValidator.SaveLineInfo(), System.Xml.Schema.XNodeValidator.source, System.Xml.Schema.XNodeValidator.ValidateAttribute(), and System.Xml.Schema.XNodeValidator.validator.
Referenced by System.Xml.Schema.XNodeValidator.ValidateElement().