Terraria: System.Xml.Schema.XNodeValidator.ValidateElement
ValidateElement()
void System.Xml.Schema.XNodeValidator.ValidateElement (XElement e) inline private
Definition at line 321 of file XNodeValidator.cs.
    {
        XmlSchemaInfo xmlSchemaInfo = (addSchemaInfo ? new XmlSchemaInfo() : null);
        string xsiType = null;
        string xsiNil = null;
        PushElement(e, ref xsiType, ref xsiNil);
        IXmlLineInfo originalLineInfo = SaveLineInfo(e);
        source = e;
        validator.ValidateElement(e.Name.LocalName, e.Name.NamespaceName, xmlSchemaInfo, xsiType, xsiNil, null, null);
        ValidateAttributes(e);
        validator.ValidateEndOfAttributes(xmlSchemaInfo);
        ValidateNodes(e);
        validator.ValidateEndElement(xmlSchemaInfo);
        if (addSchemaInfo)
        {
            if (xmlSchemaInfo.Validity == XmlSchemaValidity.Valid && xmlSchemaInfo.IsDefault)
            {
                e.Value = GetDefaultValue(xmlSchemaInfo.SchemaElement);
            }
            ReplaceSchemaInfo(e, xmlSchemaInfo);
        }
        RestoreLineInfo(originalLineInfo);
        namespaceManager.PopScope();
    }
References System.Xml.Schema.XNodeValidator.addSchemaInfo, System.Xml.Dictionary, System.Xml.Schema.XNodeValidator.GetDefaultValue(), System.Xml.Linq.XName.LocalName, System.Xml.Linq.XElement.Name, System.Xml.Schema.XNodeValidator.namespaceManager, System.Xml.Linq.XName.NamespaceName, System.Xml.XmlNamespaceManager.PopScope(), System.Xml.Schema.XNodeValidator.PushElement(), System.Xml.Schema.XNodeValidator.ReplaceSchemaInfo(), System.Xml.Schema.XNodeValidator.RestoreLineInfo(), System.Xml.Schema.XNodeValidator.SaveLineInfo(), System.Xml.Schema.XNodeValidator.source, System.Xml.Schema.XNodeValidator.ValidateAttributes(), System.Xml.Schema.XmlSchemaValidator.ValidateElement(), System.Xml.Schema.XmlSchemaValidator.ValidateEndElement(), System.Xml.Schema.XmlSchemaValidator.ValidateEndOfAttributes(), System.Xml.Schema.XNodeValidator.ValidateNodes(), and System.Xml.Schema.XNodeValidator.validator.
Referenced by System.Xml.Schema.XNodeValidator.Validate(), and System.Xml.Schema.XNodeValidator.ValidateNodes().