Terraria: System.Diagnostics.StackFrame.StackFrame
StackFrame() [1/7]
System.Diagnostics.StackFrame.StackFrame (StackFrameHelper stackFrameHelper, int skipFrames, bool needFileInfo) inline package
Definition at line 27 of file StackFrame.cs.
    {
        _method = stackFrameHelper.GetMethodBase(skipFrames);
        _nativeOffset = stackFrameHelper.GetOffset(skipFrames);
        _ilOffset = stackFrameHelper.GetILOffset(skipFrames);
        _isLastFrameFromForeignExceptionStackTrace = stackFrameHelper.IsLastFrameFromForeignExceptionStackTrace(skipFrames);
        if (needFileInfo)
        {
            _fileName = stackFrameHelper.GetFilename(skipFrames);
            _lineNumber = stackFrameHelper.GetLineNumber(skipFrames);
            _columnNumber = stackFrameHelper.GetColumnNumber(skipFrames);
        }
    }
References System.Diagnostics.StackFrame._columnNumber, System.Diagnostics.StackFrame._fileName, System.Diagnostics.StackFrame._ilOffset, System.Diagnostics.StackFrame._isLastFrameFromForeignExceptionStackTrace, System.Diagnostics.StackFrame._lineNumber, System.Diagnostics.StackFrame._method, System.Diagnostics.StackFrame._nativeOffset, System.Diagnostics.StackFrameHelper.GetColumnNumber(), System.Diagnostics.StackFrameHelper.GetFilename(), System.Diagnostics.StackFrameHelper.GetILOffset(), System.Diagnostics.StackFrameHelper.GetLineNumber(), System.Diagnostics.StackFrameHelper.GetMethodBase(), System.Diagnostics.StackFrameHelper.GetOffset(), and System.Diagnostics.StackFrameHelper.IsLastFrameFromForeignExceptionStackTrace().