Terraria: System.Diagnostics.StackFrame.BuildStackFrame
BuildStackFrame()
void System.Diagnostics.StackFrame.BuildStackFrame (int skipFrames, bool needFileInfo) inline private
Definition at line 41 of file StackFrame.cs.
    {
        StackFrameHelper stackFrameHelper = new StackFrameHelper(null);
        stackFrameHelper.InitializeSourceInfo(0, needFileInfo, null);
        int numberOfFrames = stackFrameHelper.GetNumberOfFrames();
        skipFrames += StackTrace.CalculateFramesToSkip(stackFrameHelper, numberOfFrames);
        if (numberOfFrames - skipFrames > 0)
        {
            _method = stackFrameHelper.GetMethodBase(skipFrames);
            _nativeOffset = stackFrameHelper.GetOffset(skipFrames);
            _ilOffset = stackFrameHelper.GetILOffset(skipFrames);
            if (needFileInfo)
            {
                _fileName = stackFrameHelper.GetFilename(skipFrames);
                _lineNumber = stackFrameHelper.GetLineNumber(skipFrames);
                _columnNumber = stackFrameHelper.GetColumnNumber(skipFrames);
            }
        }
    }
References System.Diagnostics.StackFrame._columnNumber, System.Diagnostics.StackFrame._fileName, System.Diagnostics.StackFrame._ilOffset, System.Diagnostics.StackFrame._lineNumber, System.Diagnostics.StackFrame._method, System.Diagnostics.StackFrame._nativeOffset, System.Diagnostics.StackTrace.CalculateFramesToSkip(), System.Diagnostics.StackFrameHelper.GetColumnNumber(), System.Diagnostics.StackFrameHelper.GetFilename(), System.Diagnostics.StackFrameHelper.GetILOffset(), System.Diagnostics.StackFrameHelper.GetLineNumber(), System.Diagnostics.StackFrameHelper.GetMethodBase(), System.Diagnostics.StackFrameHelper.GetNumberOfFrames(), System.Diagnostics.StackFrameHelper.GetOffset(), and System.Diagnostics.StackFrameHelper.InitializeSourceInfo().
Referenced by System.Diagnostics.StackFrame.StackFrame(), System.Diagnostics.StackFrame.StackFrame(), System.Diagnostics.StackFrame.StackFrame(), System.Diagnostics.StackFrame.StackFrame(), System.Diagnostics.StackFrame.StackFrame(), and System.Diagnostics.StackFrame.StackFrame().