Terraria: System.Net.Mail.MailWriter.Close
Close()
override void System.Net.Mail.MailWriter.Close () inline package
Definition at line 31 of file MailWriter.cs.
    {
        _bufferBuilder.Append(BaseWriter.s_crlf);
        Flush(null);
        _stream.Close();
    }
References System.Net.Mime.BaseWriter._bufferBuilder, System.Net.Mime.BaseWriter._stream, System.IO.Stream.Close(), System.Net.Mime.BaseWriter.Flush(), and System.Net.Mime.BaseWriter.s_crlf.
Referenced by System.Net.Mail.SmtpClient.Complete(), System.Net.Mail.SmtpClient.Send(), and System.Net.Mail.SmtpClient.SendAsync().