Terraria: System.Diagnostics.StackFrame.InitMembers
InitMembers()
void System.Diagnostics.StackFrame.InitMembers () inline private
Definition at line 66 of file StackFrame.cs.
    {
        _nativeOffset = -1;
        _ilOffset = -1;
    }
References System.Diagnostics.StackFrame._ilOffset, and System.Diagnostics.StackFrame._nativeOffset.
Referenced by System.Diagnostics.StackFrame.StackFrame(), System.Diagnostics.StackFrame.StackFrame(), System.Diagnostics.StackFrame.StackFrame(), System.Diagnostics.StackFrame.StackFrame(), System.Diagnostics.StackFrame.StackFrame(), and System.Diagnostics.StackFrame.StackFrame().