Terraria: System.Diagnostics.StackFrame.ToString
ToString()
override string System.Diagnostics.StackFrame.ToString () inline
Definition at line 149 of file StackFrame.cs.
    {
        StringBuilder stringBuilder = new StringBuilder(255);
        bool flag2;
        if (_method != null)
        {
            stringBuilder.Append(_method.Name);
            if (_method is MethodInfo { IsGenericMethod: not false } methodInfo)
            {
                Type[] genericArguments = methodInfo.GetGenericArguments();
                stringBuilder.Append('<');
                int i = 0;
                bool flag = true;
                for (; i < genericArguments.Length; i++)
                {
                    if (!flag)
                    {
                        stringBuilder.Append(',');
                    }
                    else
                    {
                        flag = false;
                    }
                    stringBuilder.Append(genericArguments[i].Name);
                }
                stringBuilder.Append('>');
            }
            flag2 = true;
        }
        else
        {
            flag2 = AppendStackFrameWithoutMethodBase(stringBuilder);
        }
        if (flag2)
        {
            stringBuilder.Append(" at offset ");
            if (_nativeOffset == -1)
            {
                stringBuilder.Append("<offset unknown>");
            }
            else
            {
                stringBuilder.Append(_nativeOffset);
            }
            stringBuilder.Append(" in file:line:column ");
            stringBuilder.Append(_fileName ?? "<filename unknown>");
            stringBuilder.Append(':');
            stringBuilder.Append(_lineNumber);
            stringBuilder.Append(':');
            stringBuilder.Append(_columnNumber);
        }
        else
        {
            stringBuilder.Append("<null>");
        }
        stringBuilder.AppendLine();
        return stringBuilder.ToString();
    }
References System.Diagnostics.StackFrame._columnNumber, System.Diagnostics.StackFrame._fileName, System.Diagnostics.StackFrame._lineNumber, System.Diagnostics.StackFrame._method, System.Diagnostics.StackFrame._nativeOffset, System.Text.StringBuilder.Append(), System.Text.StringBuilder.AppendLine(), System.Diagnostics.StackFrame.AppendStackFrameWithoutMethodBase(), System.Type.GetGenericArguments(), System.Reflection.MemberInfo.Name, System.Name, and System.Text.StringBuilder.ToString().