Terraria: Terraria.GameContent.UI.Elements.UIDifficultyButton.UIDifficultyButton
UIDifficultyButton()
Terraria.GameContent.UI.Elements.UIDifficultyButton.UIDifficultyButton (Player player, LocalizedText title, LocalizedText description, byte difficulty, Color color) inline
Definition at line 28 of file UIDifficultyButton.cs.
    {
        _player = player;
        _difficulty = difficulty;
        Width = StyleDimension.FromPixels(44f);
        Height = StyleDimension.FromPixels(110f);
        _BasePanelTexture = Main.Assets.Request<Texture2D>("Images/UI/CharCreation/PanelGrayscale", (AssetRequestMode)1);
        _selectedBorderTexture = Main.Assets.Request<Texture2D>("Images/UI/CharCreation/CategoryPanelHighlight", (AssetRequestMode)1);
        _hoveredBorderTexture = Main.Assets.Request<Texture2D>("Images/UI/CharCreation/CategoryPanelBorder", (AssetRequestMode)1);
        _color = color;
        UIText element = new UIText(title, 0.9f)
        {
            HAlign = 0.5f,
            VAlign = 0f,
            Width = StyleDimension.FromPixelsAndPercent(-10f, 1f),
            Top = StyleDimension.FromPixels(5f)
        };
        Append(element);
    }
References Terraria.GameContent.UI.Elements.UIDifficultyButton._BasePanelTexture, Terraria.GameContent.UI.Elements.UIDifficultyButton._color, Terraria.GameContent.UI.Elements.UIDifficultyButton._difficulty, Terraria.GameContent.UI.Elements.UIDifficultyButton._hoveredBorderTexture, Terraria.GameContent.UI.Elements.UIDifficultyButton._player, Terraria.GameContent.UI.Elements.UIDifficultyButton._selectedBorderTexture, Terraria.UI.UIElement.Append(), Terraria.Main.Assets, Terraria.UI.StyleDimension.FromPixels(), Terraria.UI.StyleDimension.FromPixelsAndPercent(), Terraria.UI.UIElement.HAlign, Terraria.UI.UIElement.Height, Terraria.UI.UIElement.Top, Terraria.UI.UIElement.VAlign, and Terraria.UI.UIElement.Width.