Terraria: System.Reflection.Metadata.BlobWriter.WriteBytes
WriteBytes() [3/8]
unsafe void System.Reflection.Metadata.BlobWriter.WriteBytes (byte value, int byteCount) inline
Definition at line 109 of file BlobWriter.cs.
    {
        if (byteCount < 0)
        {
            Throw.ArgumentOutOfRange("byteCount");
        }
        int num = Advance(byteCount);
        fixed (byte* ptr = _buffer)
        {
            byte* ptr2 = ptr + num;
            for (int i = 0; i < byteCount; i++)
            {
                ptr2[i] = value;
            }
        }
    }
References System.Reflection.Metadata.BlobWriter._buffer, System.Reflection.Metadata.BlobWriter.Advance(), System.Reflection.Throw.ArgumentOutOfRange(), System.byteCount, and System.value.
Referenced by System.Reflection.Metadata.BlobWriter.Align(), System.Reflection.Metadata.BlobWriter.PadTo(), System.Reflection.PortableExecutable.ManagedTextSection.Serialize(), System.Reflection.PortableExecutable.PEBuilder.Sign(), System.Reflection.Metadata.BlobWriter.WriteBytes(), System.Reflection.Metadata.BlobWriter.WriteBytes(), System.Reflection.Metadata.BlobWriter.WriteBytes(), and System.Reflection.Metadata.BlobWriter.WriteBytes().