Terraria: System.Reflection.Metadata.BlobWriter.Advance
Advance()
int System.Reflection.Metadata.BlobWriter.Advance (int value) inline private
Definition at line 98 of file BlobWriter.cs.
    {
        int position = _position;
        if (position > _end - value)
        {
            Throw.OutOfBounds();
        }
        _position = position + value;
        return position;
    }
References System.Reflection.Metadata.BlobWriter._end, System.Reflection.Metadata.BlobWriter._position, System.Reflection.Throw.OutOfBounds(), and System.value.
Referenced by System.Reflection.Metadata.BlobWriter.WriteByte(), System.Reflection.Metadata.BlobWriter.WriteBytes(), System.Reflection.Metadata.BlobWriter.WriteBytes(), System.Reflection.Metadata.BlobWriter.WriteBytesUnchecked(), System.Reflection.Metadata.BlobWriter.WriteDecimal(), System.Reflection.Metadata.BlobWriter.WriteDouble(), System.Reflection.Metadata.BlobWriter.WriteGuid(), System.Reflection.Metadata.BlobWriter.WriteSingle(), System.Reflection.Metadata.BlobWriter.WriteUInt16(), System.Reflection.Metadata.BlobWriter.WriteUInt16BE(), System.Reflection.Metadata.BlobWriter.WriteUInt32(), System.Reflection.Metadata.BlobWriter.WriteUInt32BE(), System.Reflection.Metadata.BlobWriter.WriteUInt64(), and System.Reflection.Metadata.BlobWriter.WriteUTF8().