Terraria: System.Reflection.Metadata.BlobWriter.WriteBytesUnchecked
WriteBytesUnchecked()
unsafe void System.Reflection.Metadata.BlobWriter.WriteBytesUnchecked (byte * buffer, int byteCount) inline private
Definition at line 139 of file BlobWriter.cs.
    {
        int startIndex = Advance(byteCount);
        Marshal.Copy((IntPtr)buffer, _buffer, startIndex, byteCount);
    }
References System.Reflection.Metadata.BlobWriter._buffer, System.Reflection.Metadata.BlobWriter.Advance(), System.buffer, System.byteCount, System.Runtime.InteropServices.Marshal.Copy(), and System.startIndex.
Referenced by System.Reflection.Metadata.BlobWriter.WriteBytes(), System.Reflection.Metadata.BlobWriter.WriteUTF16(), and System.Reflection.Metadata.BlobWriter.WriteUTF16().