Terraria: System.Reflection.Metadata.BlobWriter.WriteUTF8
WriteUTF8() [1/2]
unsafe void System.Reflection.Metadata.BlobWriter.WriteUTF8 (string str, int start, int length, bool allowUnpairedSurrogates, bool prependSize) inline private
Definition at line 400 of file BlobWriter.cs.
    {
        fixed (char* ptr = str)
        {
            char* ptr2 = ptr + start;
            int uTF8ByteCount = BlobUtilities.GetUTF8ByteCount(ptr2, length);
            if (prependSize)
            {
                WriteCompressedInteger(uTF8ByteCount);
            }
            int start2 = Advance(uTF8ByteCount);
            _buffer.WriteUTF8(start2, ptr2, length, uTF8ByteCount, allowUnpairedSurrogates);
        }
    }
References System.Reflection.Metadata.BlobWriter._buffer, System.Reflection.Metadata.BlobWriter.Advance(), System.Reflection.BlobUtilities.GetUTF8ByteCount(), System.length, System.start, System.str, and System.Reflection.Metadata.BlobWriter.WriteCompressedInteger().