Terraria: System.Xml.Serialization.SoapReflectionImporter.GetTypeMapping
GetTypeMapping()
TypeMapping System.Xml.Serialization.SoapReflectionImporter.GetTypeMapping (string typeName, string ns, TypeDesc typeDesc) inline private
Definition at line 257 of file SoapReflectionImporter.cs.
    {
        TypeMapping typeMapping = (TypeMapping)_types[typeName, ns];
        if (typeMapping == null)
        {
            return null;
        }
        if (typeMapping.TypeDesc != typeDesc)
        {
            throw new InvalidOperationException(System.SR.Format(System.SR.XmlTypesDuplicate, typeDesc.FullName, typeMapping.TypeDesc.FullName, typeName, ns));
        }
        return typeMapping;
    }
References System.Xml.Serialization.SoapReflectionImporter._types, System.Xml.Dictionary, System.SR.Format(), and System.SR.XmlTypesDuplicate.
Referenced by System.Xml.Serialization.SoapReflectionImporter.ImportEnumMapping(), System.Xml.Serialization.SoapReflectionImporter.ImportStructLikeMapping(), and System.Xml.Serialization.SoapReflectionImporter.ImportTypeMapping().