Terraria: System.Xml.Serialization.SoapReflectionImporter.ImportArrayLikeMapping
ImportArrayLikeMapping()
ArrayMapping System.Xml.Serialization.SoapReflectionImporter.ImportArrayLikeMapping (ArrayModel model, RecursionLimiter limiter) inline private
Definition at line 434 of file SoapReflectionImporter.cs.
    {
        ArrayMapping arrayMapping = new ArrayMapping();
        arrayMapping.IsSoap = true;
        TypeMapping typeMapping = ImportTypeMapping(model.Element, limiter);
        if (typeMapping.TypeDesc.IsValueType && !typeMapping.TypeDesc.IsPrimitive && !typeMapping.TypeDesc.IsEnum)
        {
            throw new NotSupportedException(System.SR.Format(System.SR.XmlRpcArrayOfValueTypes, model.TypeDesc.FullName));
        }
        arrayMapping.TypeDesc = model.TypeDesc;
        arrayMapping.Elements = new ElementAccessor[1] { CreateElementAccessor(typeMapping, arrayMapping.Namespace) };
        SetArrayMappingType(arrayMapping);
        ArrayMapping arrayMapping2 = (ArrayMapping)_types[arrayMapping.TypeName, arrayMapping.Namespace];
        if (arrayMapping2 != null)
        {
            ArrayMapping next = arrayMapping2;
            while (arrayMapping2 != null)
            {
                if (arrayMapping2.TypeDesc == model.TypeDesc)
                {
                    return arrayMapping2;
                }
                arrayMapping2 = arrayMapping2.Next;
            }
            arrayMapping.Next = next;
            _types[arrayMapping.TypeName, arrayMapping.Namespace] = arrayMapping;
            return arrayMapping;
        }
        _typeScope.AddTypeMapping(arrayMapping);
        _types.Add(arrayMapping.TypeName, arrayMapping.Namespace, arrayMapping);
        IncludeTypes(model.Type);
        return arrayMapping;
    }
References System.Xml.Serialization.SoapReflectionImporter._types, System.Xml.Serialization.SoapReflectionImporter._typeScope, System.Xml.Serialization.NameTable.Add(), System.Xml.Serialization.TypeScope.AddTypeMapping(), System.Xml.Serialization.SoapReflectionImporter.CreateElementAccessor(), System.Xml.Dictionary, System.SR.Format(), System.Xml.Serialization.SoapReflectionImporter.ImportTypeMapping(), System.Xml.Serialization.SoapReflectionImporter.IncludeTypes(), System.Xml.Serialization.SoapReflectionImporter.SetArrayMappingType(), and System.SR.XmlRpcArrayOfValueTypes.
Referenced by System.Xml.Serialization.SoapReflectionImporter.ImportTypeMapping().