Terraria: System.Xml.Serialization.SoapReflectionImporter.SetArrayMappingType
SetArrayMappingType()
void System.Xml.Serialization.SoapReflectionImporter.SetArrayMappingType (ArrayMapping mapping) inline private
Definition at line 468 of file SoapReflectionImporter.cs.
    {
        bool flag = false;
        TypeMapping typeMapping = ((mapping.Elements.Length != 1) ? null : mapping.Elements[0].Mapping);
        string text;
        string identifier;
        if (typeMapping is EnumMapping)
        {
            text = typeMapping.Namespace;
            identifier = typeMapping.TypeName;
        }
        else if (typeMapping is PrimitiveMapping)
        {
            text = (typeMapping.TypeDesc.IsXsdType ? "http://www.w3.org/2001/XMLSchema" : "http://microsoft.com/wsdl/types/");
            identifier = typeMapping.TypeDesc.DataType.Name;
            flag = true;
        }
        else if (typeMapping is StructMapping)
        {
            if (typeMapping.TypeDesc.IsRoot)
            {
                text = "http://www.w3.org/2001/XMLSchema";
                identifier = "anyType";
                flag = true;
            }
            else
            {
                text = typeMapping.Namespace;
                identifier = typeMapping.TypeName;
            }
        }
        else
        {
            if (!(typeMapping is ArrayMapping))
            {
                throw new InvalidOperationException(System.SR.Format(System.SR.XmlInvalidSoapArray, mapping.TypeDesc.FullName));
            }
            text = typeMapping.Namespace;
            identifier = typeMapping.TypeName;
        }
        identifier = CodeIdentifier.MakePascal(identifier);
        string text2 = "ArrayOf" + identifier;
        string text3 = (flag ? _defaultNs : text);
        int num = 1;
        TypeMapping typeMapping2 = (TypeMapping)_types[text2, text3];
        while (typeMapping2 != null)
        {
            if (typeMapping2 is ArrayMapping)
            {
                ArrayMapping arrayMapping = (ArrayMapping)typeMapping2;
                if (AccessorMapping.ElementsMatch(arrayMapping.Elements, mapping.Elements))
                {
                    break;
                }
            }
            text2 = identifier + num.ToString(CultureInfo.InvariantCulture);
            typeMapping2 = (TypeMapping)_types[text2, text3];
            num++;
        }
        mapping.Namespace = text3;
        mapping.TypeName = text2;
    }
References System.Xml.Serialization.SoapReflectionImporter._defaultNs, System.Xml.Serialization.SoapReflectionImporter._types, System.Xml.Dictionary, System.Xml.Serialization.AccessorMapping.ElementsMatch(), System.SR.Format(), System.Globalization.CultureInfo.InvariantCulture, System.Xml.Serialization.CodeIdentifier.MakePascal(), System.text, and System.SR.XmlInvalidSoapArray.
Referenced by System.Xml.Serialization.SoapReflectionImporter.ImportArrayLikeMapping().