Terraria: System.Xml.Serialization.SoapReflectionImporter.ImportTypeMapping
ImportTypeMapping() [4/4]
TypeMapping System.Xml.Serialization.SoapReflectionImporter.ImportTypeMapping (TypeModel model, string dataType, RecursionLimiter limiter) inline private
Definition at line 172 of file SoapReflectionImporter.cs.
    {
        if (dataType.Length > 0)
        {
            if (!model.TypeDesc.IsPrimitive)
            {
                throw new InvalidOperationException(System.SR.Format(System.SR.XmlInvalidDataTypeUsage, dataType, "SoapElementAttribute.DataType"));
            }
            TypeDesc typeDesc = _typeScope.GetTypeDesc(dataType, "http://www.w3.org/2001/XMLSchema");
            if (typeDesc == null)
            {
                throw new InvalidOperationException(System.SR.Format(System.SR.XmlInvalidXsdDataType, dataType, "SoapElementAttribute.DataType", new XmlQualifiedName(dataType, "http://www.w3.org/2001/XMLSchema").ToString()));
            }
            if (model.TypeDesc.FullName != typeDesc.FullName)
            {
                throw new InvalidOperationException(System.SR.Format(System.SR.XmlDataTypeMismatch, dataType, "SoapElementAttribute.DataType", model.TypeDesc.FullName));
            }
        }
        SoapAttributes attributes = GetAttributes(model.Type);
        if (((uint)attributes.GetSoapFlags() & 0xFFFFFFFDu) != 0)
        {
            throw new InvalidOperationException(System.SR.Format(System.SR.XmlInvalidTypeAttributes, model.Type.FullName));
        }
        switch (model.TypeDesc.Kind)
        {
        case TypeKind.Enum:
            return ImportEnumMapping((EnumModel)model);
        case TypeKind.Primitive:
            return ImportPrimitiveMapping((PrimitiveModel)model, dataType);
        case TypeKind.Array:
        case TypeKind.Collection:
        case TypeKind.Enumerable:
            return ImportArrayLikeMapping((ArrayModel)model, limiter);
        case TypeKind.Root:
        case TypeKind.Struct:
        case TypeKind.Class:
            if (model.TypeDesc.IsOptionalValue)
            {
                TypeDesc baseTypeDesc = model.TypeDesc.BaseTypeDesc;
                SoapAttributes attributes2 = GetAttributes(baseTypeDesc.Type);
                string ns = _defaultNs;
                if (attributes2.SoapType != null && attributes2.SoapType.Namespace != null)
                {
                    ns = attributes2.SoapType.Namespace;
                }
                TypeDesc typeDesc2 = (string.IsNullOrEmpty(dataType) ? model.TypeDesc.BaseTypeDesc : _typeScope.GetTypeDesc(dataType, "http://www.w3.org/2001/XMLSchema"));
                string typeName = (string.IsNullOrEmpty(dataType) ? model.TypeDesc.BaseTypeDesc.Name : dataType);
                TypeMapping typeMapping = GetTypeMapping(typeName, ns, typeDesc2);
                if (typeMapping == null)
                {
                    typeMapping = ImportTypeMapping(_modelScope.GetTypeModel(baseTypeDesc.Type), dataType, limiter);
                }
                return CreateNullableMapping(typeMapping, model.TypeDesc.Type);
            }
            return ImportStructLikeMapping((StructModel)model, limiter);
        default:
            throw new NotSupportedException(System.SR.Format(System.SR.XmlUnsupportedSoapTypeKind, model.TypeDesc.FullName));
        }
    }
References System.Xml.Serialization.SoapReflectionImporter._defaultNs, System.Xml.Serialization.SoapReflectionImporter._modelScope, System.Xml.Serialization.SoapReflectionImporter._typeScope, System.Xml.Serialization.SoapReflectionImporter.CreateNullableMapping(), System.Xml.Dictionary, System.SR.Format(), System.Xml.Serialization.SoapReflectionImporter.GetAttributes(), System.Xml.Serialization.SoapAttributes.GetSoapFlags(), System.Xml.Serialization.TypeScope.GetTypeDesc(), System.Xml.Serialization.SoapReflectionImporter.GetTypeMapping(), System.Xml.Serialization.ModelScope.GetTypeModel(), System.Xml.Serialization.SoapReflectionImporter.ImportArrayLikeMapping(), System.Xml.Serialization.SoapReflectionImporter.ImportEnumMapping(), System.Xml.Serialization.SoapReflectionImporter.ImportPrimitiveMapping(), System.Xml.Serialization.SoapReflectionImporter.ImportStructLikeMapping(), System.Xml.Serialization.SoapReflectionImporter.ImportTypeMapping(), System.ToString, System.SR.XmlDataTypeMismatch, System.SR.XmlInvalidDataTypeUsage, System.SR.XmlInvalidTypeAttributes, System.SR.XmlInvalidXsdDataType, and System.SR.XmlUnsupportedSoapTypeKind.