Terraria: System.Xml.Serialization.SoapReflectionImporter.ImportEnumMapping
ImportEnumMapping()
EnumMapping System.Xml.Serialization.SoapReflectionImporter.ImportEnumMapping (EnumModel model) inline private
Definition at line 557 of file SoapReflectionImporter.cs.
    {
        SoapAttributes attributes = GetAttributes(model.Type);
        string text = _defaultNs;
        if (attributes.SoapType != null && attributes.SoapType.Namespace != null)
        {
            text = attributes.SoapType.Namespace;
        }
        string name = XsdTypeName(model.Type, attributes, model.TypeDesc.Name);
        name = XmlConvert.EncodeLocalName(name);
        EnumMapping enumMapping = (EnumMapping)GetTypeMapping(name, text, model.TypeDesc);
        if (enumMapping == null)
        {
            enumMapping = new EnumMapping();
            enumMapping.IsSoap = true;
            enumMapping.TypeDesc = model.TypeDesc;
            enumMapping.TypeName = name;
            enumMapping.Namespace = text;
            enumMapping.IsFlags = model.Type.IsDefined(typeof(FlagsAttribute), inherit: false);
            _typeScope.AddTypeMapping(enumMapping);
            _types.Add(name, text, enumMapping);
            List<ConstantMapping> list = new List<ConstantMapping>();
            for (int i = 0; i < model.Constants.Length; i++)
            {
                ConstantMapping constantMapping = ImportConstantMapping(model.Constants[i]);
                if (constantMapping != null)
                {
                    list.Add(constantMapping);
                }
            }
            if (list.Count == 0)
            {
                throw new InvalidOperationException(System.SR.Format(System.SR.XmlNoSerializableMembers, model.TypeDesc.FullName));
            }
            enumMapping.Constants = list.ToArray();
        }
        return enumMapping;
    }
References System.Xml.Serialization.SoapReflectionImporter._defaultNs, System.Xml.Serialization.SoapReflectionImporter._types, System.Xml.Serialization.SoapReflectionImporter._typeScope, System.Xml.Serialization.NameTable.Add(), System.Xml.Serialization.TypeScope.AddTypeMapping(), System.Xml.Dictionary, System.Xml.XmlConvert.EncodeLocalName(), System.SR.Format(), System.Xml.Serialization.SoapReflectionImporter.GetAttributes(), System.Xml.Serialization.SoapReflectionImporter.GetTypeMapping(), System.Xml.Serialization.SoapReflectionImporter.ImportConstantMapping(), System.list, System.Xml.Serialization.SoapTypeAttribute.Namespace, System.Xml.Serialization.SoapAttributes.SoapType, System.text, System.SR.XmlNoSerializableMembers, and System.Xml.Serialization.SoapReflectionImporter.XsdTypeName().
Referenced by System.Xml.Serialization.SoapReflectionImporter.ImportTypeMapping().