Terraria: System.Xml.Serialization.SoapReflectionImporter.ImportMemberMapping
ImportMemberMapping()
MemberMapping System.Xml.Serialization.SoapReflectionImporter.ImportMemberMapping (XmlReflectionMember xmlReflectionMember, string ns, XmlReflectionMember[] xmlReflectionMembers, XmlSchemaForm form, RecursionLimiter limiter) inline private
Definition at line 665 of file SoapReflectionImporter.cs.
    {
        SoapAttributes soapAttributes = xmlReflectionMember.SoapAttributes;
        if (soapAttributes.SoapIgnore)
        {
            return null;
        }
        MemberMapping memberMapping = new MemberMapping();
        memberMapping.IsSoap = true;
        memberMapping.Name = xmlReflectionMember.MemberName;
        bool checkSpecified = XmlReflectionImporter.FindSpecifiedMember(xmlReflectionMember.MemberName, xmlReflectionMembers) != null;
        FieldModel fieldModel = new FieldModel(xmlReflectionMember.MemberName, xmlReflectionMember.MemberType, _typeScope.GetTypeDesc(xmlReflectionMember.MemberType), checkSpecified, checkShouldPersist: false);
        memberMapping.CheckShouldPersist = fieldModel.CheckShouldPersist;
        memberMapping.CheckSpecified = fieldModel.CheckSpecified;
        memberMapping.ReadOnly = fieldModel.ReadOnly;
        ImportAccessorMapping(memberMapping, fieldModel, soapAttributes, ns, form, limiter);
        if (xmlReflectionMember.OverrideIsNullable)
        {
            memberMapping.Elements[0].IsNullable = false;
        }
        return memberMapping;
    }
References System.Xml.Serialization.SoapReflectionImporter._typeScope, System.Xml.Dictionary, System.Xml.Serialization.XmlReflectionImporter.FindSpecifiedMember(), System.Xml.Serialization.TypeScope.GetTypeDesc(), and System.Xml.Serialization.SoapReflectionImporter.ImportAccessorMapping().
Referenced by System.Xml.Serialization.SoapReflectionImporter.ImportMembersMapping().