Terraria: System.Xml.Serialization.SoapReflectionImporter.ImportAccessorMapping
ImportAccessorMapping()
void System.Xml.Serialization.SoapReflectionImporter.ImportAccessorMapping (MemberMapping accessor, FieldModel model, SoapAttributes a, string ns, XmlSchemaForm form, RecursionLimiter limiter) inline private
Definition at line 709 of file SoapReflectionImporter.cs.
    {
        Type fieldType = model.FieldType;
        string name = model.Name;
        accessor.TypeDesc = _typeScope.GetTypeDesc(fieldType);
        if (accessor.TypeDesc.IsVoid)
        {
            throw new InvalidOperationException(System.SR.XmlInvalidVoid);
        }
        SoapAttributeFlags soapFlags = a.GetSoapFlags();
        if ((soapFlags & SoapAttributeFlags.Attribute) == SoapAttributeFlags.Attribute)
        {
            if (!accessor.TypeDesc.IsPrimitive && !accessor.TypeDesc.IsEnum)
            {
                throw new InvalidOperationException(System.SR.Format(System.SR.XmlIllegalSoapAttribute, name, accessor.TypeDesc.FullName));
            }
            if ((soapFlags & SoapAttributeFlags.Attribute) != soapFlags)
            {
                throw new InvalidOperationException(System.SR.XmlInvalidElementAttribute);
            }
            AttributeAccessor attributeAccessor = new AttributeAccessor();
            attributeAccessor.Name = Accessor.EscapeQName((a.SoapAttribute == null || a.SoapAttribute.AttributeName.Length == 0) ? name : a.SoapAttribute.AttributeName);
            attributeAccessor.Namespace = ((a.SoapAttribute == null || a.SoapAttribute.Namespace == null) ? ns : a.SoapAttribute.Namespace);
            attributeAccessor.Form = XmlSchemaForm.Qualified;
            attributeAccessor.Mapping = ImportTypeMapping(_modelScope.GetTypeModel(fieldType), (a.SoapAttribute == null) ? string.Empty : a.SoapAttribute.DataType, limiter);
            attributeAccessor.Default = GetDefaultValue(model.FieldTypeDesc, a);
            accessor.Attribute = attributeAccessor;
            accessor.Elements = Array.Empty<ElementAccessor>();
        }
        else
        {
            if ((soapFlags & SoapAttributeFlags.Element) != soapFlags)
            {
                throw new InvalidOperationException(System.SR.XmlInvalidElementAttribute);
            }
            ElementAccessor elementAccessor = new ElementAccessor();
            elementAccessor.IsSoap = true;
            elementAccessor.Name = XmlConvert.EncodeLocalName((a.SoapElement == null || a.SoapElement.ElementName.Length == 0) ? name : a.SoapElement.ElementName);
            elementAccessor.Namespace = ns;
            elementAccessor.Form = form;
            elementAccessor.Mapping = ImportTypeMapping(_modelScope.GetTypeModel(fieldType), (a.SoapElement == null) ? string.Empty : a.SoapElement.DataType, limiter);
            if (a.SoapElement != null)
            {
                elementAccessor.IsNullable = a.SoapElement.IsNullable;
            }
            accessor.Elements = new ElementAccessor[1] { elementAccessor };
        }
    }
References System.Xml.Serialization.SoapReflectionImporter._modelScope, System.Xml.Serialization.SoapReflectionImporter._typeScope, System.Xml.Dictionary, System.Xml.XmlConvert.EncodeLocalName(), System.Xml.Serialization.Accessor.EscapeQName(), System.SR.Format(), System.Xml.Serialization.SoapReflectionImporter.GetDefaultValue(), System.Xml.Serialization.TypeScope.GetTypeDesc(), System.Xml.Serialization.ModelScope.GetTypeModel(), System.Xml.Serialization.SoapReflectionImporter.ImportTypeMapping(), System.SR.XmlIllegalSoapAttribute, System.SR.XmlInvalidElementAttribute, and System.SR.XmlInvalidVoid.
Referenced by System.Xml.Serialization.SoapReflectionImporter.ImportFieldMapping(), and System.Xml.Serialization.SoapReflectionImporter.ImportMemberMapping().