Terraria: System.Xml.Serialization.SoapReflectionImporter.GetDefaultValue
GetDefaultValue()
object System.Xml.Serialization.SoapReflectionImporter.GetDefaultValue (TypeDesc fieldTypeDesc, SoapAttributes a) inline private
Definition at line 769 of file SoapReflectionImporter.cs.
    {
        if (a.SoapDefaultValue == null || a.SoapDefaultValue == DBNull.Value)
        {
            return null;
        }
        if (fieldTypeDesc.Kind != TypeKind.Primitive && fieldTypeDesc.Kind != TypeKind.Enum)
        {
            a.SoapDefaultValue = null;
            return a.SoapDefaultValue;
        }
        if (fieldTypeDesc.Kind == TypeKind.Enum)
        {
            if (fieldTypeDesc != _typeScope.GetTypeDesc(a.SoapDefaultValue.GetType()))
            {
                throw new InvalidOperationException(System.SR.Format(System.SR.XmlInvalidDefaultEnumValue, a.SoapDefaultValue.GetType().FullName, fieldTypeDesc.FullName));
            }
            string text = Enum.Format(a.SoapDefaultValue.GetType(), a.SoapDefaultValue, "G").Replace(",", " ");
            string text2 = Enum.Format(a.SoapDefaultValue.GetType(), a.SoapDefaultValue, "D");
            if (text == text2)
            {
                throw new InvalidOperationException(System.SR.Format(System.SR.XmlInvalidDefaultValue, text, a.SoapDefaultValue.GetType().FullName));
            }
            return text;
        }
        return a.SoapDefaultValue;
    }
References System.Xml.Serialization.SoapReflectionImporter._typeScope, System.Xml.Dictionary, System.SR.Format(), System.Enum.Format(), System.Xml.Serialization.TypeScope.GetTypeDesc(), System.text, System.DBNull.Value, System.SR.XmlInvalidDefaultEnumValue, and System.SR.XmlInvalidDefaultValue.
Referenced by System.Xml.Serialization.SoapReflectionImporter.ImportAccessorMapping().