Terraria: System.Xml.Serialization.SoapReflectionImporter.InitializeStructMembers
InitializeStructMembers()
bool System.Xml.Serialization.SoapReflectionImporter.InitializeStructMembers (StructMapping mapping, StructModel model, RecursionLimiter limiter) inline private
Definition at line 358 of file SoapReflectionImporter.cs.
    {
        if (mapping.IsFullyInitialized)
        {
            return true;
        }
        if (model.TypeDesc.BaseTypeDesc != null)
        {
            StructMapping baseMapping = ImportStructLikeMapping((StructModel)_modelScope.GetTypeModel(model.Type.BaseType, directReference: false), limiter);
            int num = limiter.DeferredWorkItems.IndexOf(mapping.BaseMapping);
            if (num >= 0)
            {
                if (!limiter.DeferredWorkItems.Contains(mapping))
                {
                    limiter.DeferredWorkItems.Add(new ImportStructWorkItem(model, mapping));
                }
                int num2 = limiter.DeferredWorkItems.Count - 1;
                if (num < num2)
                {
                    ImportStructWorkItem value = limiter.DeferredWorkItems[num];
                    limiter.DeferredWorkItems[num] = limiter.DeferredWorkItems[num2];
                    limiter.DeferredWorkItems[num2] = value;
                }
                return false;
            }
            mapping.BaseMapping = baseMapping;
        }
        List<MemberMapping> list = new List<MemberMapping>();
        MemberInfo[] memberInfos = model.GetMemberInfos();
        foreach (MemberInfo memberInfo in memberInfos)
        {
            if (!(memberInfo is FieldInfo) && !(memberInfo is PropertyInfo))
            {
                continue;
            }
            SoapAttributes attributes = GetAttributes(memberInfo);
            if (attributes.SoapIgnore)
            {
                continue;
            }
            FieldModel fieldModel = model.GetFieldModel(memberInfo);
            if (fieldModel == null)
            {
                continue;
            }
            MemberMapping memberMapping = ImportFieldMapping(fieldModel, attributes, mapping.Namespace, limiter);
            if (memberMapping == null)
            {
                continue;
            }
            if (!memberMapping.TypeDesc.IsPrimitive && !memberMapping.TypeDesc.IsEnum && !memberMapping.TypeDesc.IsOptionalValue)
            {
                if (model.TypeDesc.IsValueType)
                {
                    throw new NotSupportedException(System.SR.Format(System.SR.XmlRpcRefsInValueType, model.TypeDesc.FullName));
                }
                if (memberMapping.TypeDesc.IsValueType)
                {
                    throw new NotSupportedException(System.SR.Format(System.SR.XmlRpcNestedValueType, memberMapping.TypeDesc.FullName));
                }
            }
            if (mapping.BaseMapping == null || !mapping.BaseMapping.Declares(memberMapping, mapping.TypeName))
            {
                list.Add(memberMapping);
            }
        }
        mapping.Members = list.ToArray();
        if (mapping.BaseMapping == null)
        {
            mapping.BaseMapping = GetRootMapping();
        }
        IncludeTypes(model.Type, limiter);
        return true;
    }
References System.Xml.Serialization.SoapReflectionImporter._modelScope, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Collections.Generic.Dictionary< TKey, TValue >.Contains(), System.Xml.Dictionary, System.SR.Format(), System.Xml.Serialization.SoapReflectionImporter.GetAttributes(), System.Xml.Serialization.SoapReflectionImporter.GetRootMapping(), System.Xml.Serialization.ModelScope.GetTypeModel(), System.Xml.Serialization.SoapReflectionImporter.ImportFieldMapping(), System.Xml.Serialization.SoapReflectionImporter.ImportStructLikeMapping(), System.Xml.Serialization.SoapReflectionImporter.IncludeTypes(), System.list, System.Xml.Serialization.SoapAttributes.SoapIgnore, System.value, System.SR.XmlRpcNestedValueType, and System.SR.XmlRpcRefsInValueType.
Referenced by System.Xml.Serialization.SoapReflectionImporter.ImportStructLikeMapping().