Terraria: System.Xml.Serialization.SoapReflectionImporter.ImportPrimitiveMapping
ImportPrimitiveMapping()
PrimitiveMapping System.Xml.Serialization.SoapReflectionImporter.ImportPrimitiveMapping (PrimitiveModel model, string dataType) inline private
Definition at line 531 of file SoapReflectionImporter.cs.
    {
        PrimitiveMapping primitiveMapping = new PrimitiveMapping();
        primitiveMapping.IsSoap = true;
        if (dataType.Length > 0)
        {
            primitiveMapping.TypeDesc = _typeScope.GetTypeDesc(dataType, "http://www.w3.org/2001/XMLSchema");
            if (primitiveMapping.TypeDesc == null)
            {
                primitiveMapping.TypeDesc = _typeScope.GetTypeDesc(dataType, "http://microsoft.com/wsdl/types/");
                if (primitiveMapping.TypeDesc == null)
                {
                    throw new InvalidOperationException(System.SR.Format(System.SR.XmlUdeclaredXsdType, dataType));
                }
            }
        }
        else
        {
            primitiveMapping.TypeDesc = model.TypeDesc;
        }
        primitiveMapping.TypeName = primitiveMapping.TypeDesc.DataType.Name;
        primitiveMapping.Namespace = (primitiveMapping.TypeDesc.IsXsdType ? "http://www.w3.org/2001/XMLSchema" : "http://microsoft.com/wsdl/types/");
        return primitiveMapping;
    }
References System.Xml.Serialization.SoapReflectionImporter._typeScope, System.Xml.Dictionary, System.SR.Format(), System.Xml.Serialization.TypeScope.GetTypeDesc(), and System.SR.XmlUdeclaredXsdType.
Referenced by System.Xml.Serialization.SoapReflectionImporter.ImportTypeMapping().