Terraria: System.Xml.Serialization.SoapReflectionImporter.ImportConstantMapping
ImportConstantMapping()
ConstantMapping System.Xml.Serialization.SoapReflectionImporter.ImportConstantMapping (ConstantModel model) inline private
Definition at line 596 of file SoapReflectionImporter.cs.
    {
        SoapAttributes attributes = GetAttributes(model.FieldInfo);
        if (attributes.SoapIgnore)
        {
            return null;
        }
        if (((uint)attributes.GetSoapFlags() & 0xFFFFFFFEu) != 0)
        {
            throw new InvalidOperationException(System.SR.XmlInvalidEnumAttribute);
        }
        if (attributes.SoapEnum == null)
        {
            attributes.SoapEnum = new SoapEnumAttribute();
        }
        ConstantMapping constantMapping = new ConstantMapping();
        constantMapping.XmlName = ((attributes.SoapEnum.Name.Length == 0) ? model.Name : attributes.SoapEnum.Name);
        constantMapping.Name = model.Name;
        constantMapping.Value = model.Value;
        return constantMapping;
    }
References System.Xml.Dictionary, System.Xml.Serialization.SoapReflectionImporter.GetAttributes(), System.Xml.Serialization.SoapAttributes.GetSoapFlags(), System.Xml.Serialization.SoapEnumAttribute.Name, System.Xml.Serialization.SoapAttributes.SoapEnum, System.Xml.Serialization.SoapAttributes.SoapIgnore, and System.SR.XmlInvalidEnumAttribute.
Referenced by System.Xml.Serialization.SoapReflectionImporter.ImportEnumMapping().