Terraria: System.Xml.Serialization.SoapReflectionImporter.ImportStructLikeMapping
ImportStructLikeMapping()
StructMapping System.Xml.Serialization.SoapReflectionImporter.ImportStructLikeMapping (StructModel model, RecursionLimiter limiter) inline private
Definition at line 308 of file SoapReflectionImporter.cs.
    {
        if (model.TypeDesc.Kind == TypeKind.Root)
        {
            return GetRootMapping();
        }
        SoapAttributes attributes = GetAttributes(model.Type);
        string text = _defaultNs;
        if (attributes.SoapType != null && attributes.SoapType.Namespace != null)
        {
            text = attributes.SoapType.Namespace;
        }
        string name = XsdTypeName(model.Type, attributes, model.TypeDesc.Name);
        name = XmlConvert.EncodeLocalName(name);
        StructMapping structMapping = (StructMapping)GetTypeMapping(name, text, model.TypeDesc);
        if (structMapping == null)
        {
            structMapping = new StructMapping();
            structMapping.IsSoap = true;
            structMapping.TypeDesc = model.TypeDesc;
            structMapping.Namespace = text;
            structMapping.TypeName = name;
            if (attributes.SoapType != null)
            {
                structMapping.IncludeInSchema = attributes.SoapType.IncludeInSchema;
            }
            _typeScope.AddTypeMapping(structMapping);
            _types.Add(name, text, structMapping);
            if (limiter.IsExceededLimit)
            {
                limiter.DeferredWorkItems.Add(new ImportStructWorkItem(model, structMapping));
                return structMapping;
            }
            limiter.Depth++;
            InitializeStructMembers(structMapping, model, limiter);
            while (limiter.DeferredWorkItems.Count > 0)
            {
                int index = limiter.DeferredWorkItems.Count - 1;
                ImportStructWorkItem importStructWorkItem = limiter.DeferredWorkItems[index];
                if (InitializeStructMembers(importStructWorkItem.Mapping, importStructWorkItem.Model, limiter))
                {
                    limiter.DeferredWorkItems.RemoveAt(index);
                }
            }
            limiter.Depth--;
        }
        return structMapping;
    }
References System.Xml.Serialization.SoapReflectionImporter._defaultNs, System.Xml.Serialization.SoapReflectionImporter._types, System.Xml.Serialization.SoapReflectionImporter._typeScope, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Xml.Serialization.NameTable.Add(), System.Xml.Serialization.TypeScope.AddTypeMapping(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Xml.Dictionary, System.Xml.XmlConvert.EncodeLocalName(), System.Xml.Serialization.SoapReflectionImporter.GetAttributes(), System.Xml.Serialization.SoapReflectionImporter.GetRootMapping(), System.Xml.Serialization.SoapReflectionImporter.GetTypeMapping(), System.Xml.Serialization.SoapTypeAttribute.IncludeInSchema, System.index, System.Xml.Serialization.SoapReflectionImporter.InitializeStructMembers(), System.Xml.Serialization.SoapTypeAttribute.Namespace, System.Xml.Serialization.SoapAttributes.SoapType, System.text, and System.Xml.Serialization.SoapReflectionImporter.XsdTypeName().
Referenced by System.Xml.Serialization.SoapReflectionImporter.ImportTypeMapping(), and System.Xml.Serialization.SoapReflectionImporter.InitializeStructMembers().