Terraria: System.Xml.Serialization.SoapReflectionImporter.ImportTypeMapping
ImportTypeMapping() [2/4]
XmlTypeMapping System.Xml.Serialization.SoapReflectionImporter.ImportTypeMapping (Type type, string? defaultNamespace) inline
Definition at line 91 of file SoapReflectionImporter.cs.
    {
        ElementAccessor elementAccessor = new ElementAccessor();
        elementAccessor.IsSoap = true;
        elementAccessor.Mapping = ImportTypeMapping(_modelScope.GetTypeModel(type), new RecursionLimiter());
        elementAccessor.Name = elementAccessor.Mapping.DefaultElementName;
        elementAccessor.Namespace = ((elementAccessor.Mapping.Namespace == null) ? defaultNamespace : elementAccessor.Mapping.Namespace);
        elementAccessor.Form = XmlSchemaForm.Qualified;
        XmlTypeMapping xmlTypeMapping = new XmlTypeMapping(_typeScope, elementAccessor);
        xmlTypeMapping.SetKeyInternal(XmlMapping.GenerateKey(type, null, defaultNamespace));
        xmlTypeMapping.IsSoap = true;
        xmlTypeMapping.GenerateSerializer = true;
        return xmlTypeMapping;
    }
References System.Xml.Serialization.SoapReflectionImporter._modelScope, System.Xml.Serialization.SoapReflectionImporter._typeScope, System.Xml.Dictionary, System.Xml.Serialization.XmlMapping.GenerateKey(), System.Xml.Serialization.ModelScope.GetTypeModel(), System.Xml.Serialization.SoapReflectionImporter.ImportTypeMapping(), and System.type.