Terraria: System.Xml.Serialization.SoapReflectionImporter.ImportMembersMapping
ImportMembersMapping() [5/5]
MembersMapping System.Xml.Serialization.SoapReflectionImporter.ImportMembersMapping (XmlReflectionMember[] xmlReflectionMembers, string ns, bool hasWrapperElement, bool writeAccessors, bool validateWrapperElement, RecursionLimiter limiter) inline private
Definition at line 619 of file SoapReflectionImporter.cs.
    {
        MembersMapping membersMapping = new MembersMapping();
        membersMapping.TypeDesc = _typeScope.GetTypeDesc(typeof(object[]));
        MemberMapping[] array = new MemberMapping[xmlReflectionMembers.Length];
        for (int i = 0; i < array.Length; i++)
        {
            try
            {
                XmlReflectionMember xmlReflectionMember = xmlReflectionMembers[i];
                MemberMapping memberMapping = ImportMemberMapping(xmlReflectionMember, ns, xmlReflectionMembers, (!hasWrapperElement) ? XmlSchemaForm.Qualified : XmlSchemaForm.Unqualified, limiter);
                if (xmlReflectionMember.IsReturnValue && writeAccessors)
                {
                    if (i > 0)
                    {
                        throw new InvalidOperationException(System.SR.XmlInvalidReturnPosition);
                    }
                    memberMapping.IsReturnValue = true;
                }
                array[i] = memberMapping;
            }
            catch (Exception ex)
            {
                if (ex is OutOfMemoryException)
                {
                    throw;
                }
                throw ReflectionException(xmlReflectionMembers[i].MemberName, ex);
            }
        }
        membersMapping.Members = array;
        membersMapping.HasWrapperElement = hasWrapperElement;
        if (hasWrapperElement)
        {
            membersMapping.ValidateRpcWrapperElement = validateWrapperElement;
        }
        membersMapping.WriteAccessors = writeAccessors;
        membersMapping.IsSoap = true;
        if (hasWrapperElement && !writeAccessors)
        {
            membersMapping.Namespace = ns;
        }
        return membersMapping;
    }
References System.Xml.Serialization.SoapReflectionImporter._typeScope, System.array, System.Xml.Dictionary, System.Xml.Serialization.TypeScope.GetTypeDesc(), System.Xml.Serialization.SoapReflectionImporter.ImportMemberMapping(), System.Xml.Serialization.SoapReflectionImporter.ReflectionException(), and System.SR.XmlInvalidReturnPosition.