Terraria: System.Runtime.InteropServices.Marshal.BindToMoniker
BindToMoniker()
static object System.Runtime.InteropServices.Marshal.BindToMoniker (string monikerName) inline static
Definition at line 591 of file Marshal.cs.
    {
        if (!IsBuiltInComSupported)
        {
            throw new NotSupportedException(SR.NotSupported_COM);
        }
        CreateBindCtx(0u, out var ppbc);
        MkParseDisplayName(ppbc, monikerName, out var _, out var ppmk);
        BindMoniker(ppmk, 0u, ref IID_IUnknown, out var ppvResult);
        return ppvResult;
    }
References System.Runtime.InteropServices.Marshal.BindMoniker(), System.Runtime.InteropServices.Marshal.CreateBindCtx(), System.Runtime.InteropServices.Marshal.IID_IUnknown, System.Runtime.InteropServices.Marshal.IsBuiltInComSupported, System.Runtime.InteropServices.Marshal.MkParseDisplayName(), and System.SR.NotSupported_COM.