Terraria: System.Runtime.InteropServices.Marshal.FreeCoTaskMem
FreeCoTaskMem()
static void System.Runtime.InteropServices.Marshal.FreeCoTaskMem (IntPtr ptr) inline static
Definition at line 1712 of file Marshal.cs.
    {
        if (!IsNullOrWin32Atom(ptr))
        {
            Interop.Ole32.CoTaskMemFree(ptr);
        }
    }
References Interop.Ole32.CoTaskMemFree(), and System.Runtime.InteropServices.Marshal.IsNullOrWin32Atom().
Referenced by System.StubHelpers.CSTRMarshaler.ClearNative(), System.StubHelpers.UTF8Marshaler.ClearNative(), System.StubHelpers.VBByValStrMarshaler.ClearNative(), System.StubHelpers.AsAnyMarshaler.ClearNative(), System.StubHelpers.CSTRMarshaler.ConvertToNative(), Interop.NCrypt.DeriveKeyMaterial(), System.Diagnostics.Tracing.EventPipeInternal.Enable(), Interop.Crypt32.FindOidInfo(), System.Security.SecureString.MarshalToString(), System.Diagnostics.Tracing.EventPipeInternal.EventPipeProviderConfigurationNative.Release(), System.Runtime.InteropServices.Marshal.ZeroFreeCoTaskMemUnicode(), and System.Runtime.InteropServices.Marshal.ZeroFreeCoTaskMemUTF8().