Terraria: System.Runtime.InteropServices.Marshal.GetLastPInvokeError
GetLastPInvokeError()
static int System.Runtime.InteropServices.Marshal.GetLastPInvokeError ()
Referenced by System.Net.HttpListenerSession.HttpListenerSession(), System.Net.CertificateValidation.BuildChainAndVerifyProperties(), System.IO.Strategies.Net5CompatFileStreamStrategy.CompletionSource.Cancel(), System.Runtime.InteropServices.CriticalHandle.Cleanup(), System.ConsolePal.Clear(), System.Threading.LowLevelLifoSemaphore.Create(), System.IO.MemoryMappedFiles.MemoryMappedFile.CreateCore(), System.Threading.EventWaitHandle.CreateEventCore(), Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(), System.Threading.Mutex.CreateMutexCore(), System.IO.MemoryMappedFiles.MemoryMappedFile.CreateOrOpenCore(), System.Threading.Semaphore.CreateSemaphoreCore(), System.IO.MemoryMappedFiles.MemoryMappedView.CreateView(), System.Net.NetworkInformation.Ping.DoSendPingCore(), System.IO.MemoryMappedFiles.MemoryMappedView.Flush(), System.ConsolePal.GetBufferInfo(), System.Environment.GetEnvironmentVariableCore(), Internal.NativeCrypto.CapiHelper.GetErrorCode(), System.IO.Error.GetExceptionForLastWin32DriveError(), System.Runtime.InteropServices.Marshal.GetHRForLastWin32Error(), System.IO.Pipes.NamedPipeServerStream.GetImpersonationUserName(), System.Runtime.InteropServices.Marshal.GetLastWin32Error(), System.IO.Strategies.FileStreamHelpers.GetLastWin32ErrorAndDisposeHandleIfInvalid(), System.Environment.GetUserName(), System.IO.Pipes.NamedPipeServerStream.HandleGetImpersonationUserNameError(), System.IO.Pipes.NamedPipeServerStream.ImpersonateAndTryCode(), System.Runtime.InteropServices.SafeHandle.InternalRelease(), System.ConsolePal.MoveBufferArea(), System.Globalization.CompareInfo.NlsGetSortKey(), System.Globalization.Normalization.NlsIsNormalized(), System.Globalization.Normalization.NlsNormalize(), System.Threading.EventWaitHandle.OpenExistingWorker(), System.Threading.Mutex.OpenExistingWorker(), System.Threading.Semaphore.OpenExistingWorker(), Microsoft.Win32.SafeHandles.SafeFileHandle.Preallocate(), System.Security.SecureString.ProtectMemory(), System.IO.Pipes.PipeStream.ReadAsyncCore(), System.IO.Pipes.PipeStream.ReadCore(), System.ConsolePal.WindowsConsoleStream.ReadFileNative(), System.Threading.LowLevelLifoSemaphore.ReleaseCore(), System.IO.Pipes.NamedPipeServerStream.RevertImpersonationOnBackout(), System.ConsolePal.SetBufferSize(), System.ConsolePal.SetConsoleInputEncoding(), System.ConsolePal.SetConsoleOutputEncoding(), System.ConsolePal.SetCursorPosition(), System.Environment.SetEnvironmentVariableCore(), System.ConsolePal.SetWindowPosition(), System.ConsolePal.SetWindowSize(), System.Globalization.IdnMapping.ThrowForZeroLength(), System.IO.Pipes.NamedPipeClientStream.TryConnect(), System.IO.Strategies.FileStreamHelpers.TrySetFileLength(), System.Security.SecureString.UnprotectMemory(), System.IO.Pipes.PipeStream.UpdateReadMode(), System.IO.Pipes.NamedPipeServerStream.WaitForConnection(), System.IO.Pipes.NamedPipeServerStream.WaitForConnectionCoreAsync(), System.IO.Pipes.PipeStream.WaitForPipeDrain(), System.IO.Pipes.PipeStream.WriteAsyncCore(), System.IO.Pipes.PipeStream.WriteCore(), and System.ConsolePal.WindowsConsoleStream.WriteFileNative().