Terraria: System.Runtime.InteropServices.Marshal.CreateWrapperOfType
CreateWrapperOfType()
static ? object System.Runtime.InteropServices.Marshal.CreateWrapperOfType (object? o, Type t) inline static
Definition at line 451 of file Marshal.cs.
    {
        if (!IsBuiltInComSupported)
        {
            throw new NotSupportedException(SR.NotSupported_COM);
        }
        if ((object)t == null)
        {
            throw new ArgumentNullException("t");
        }
        if (!t.IsCOMObject)
        {
            throw new ArgumentException(SR.Argument_TypeNotComObject, "t");
        }
        if (t.IsGenericType)
        {
            throw new ArgumentException(SR.Argument_NeedNonGenericType, "t");
        }
        if (o == null)
        {
            return null;
        }
        if (!o.GetType().IsCOMObject)
        {
            throw new ArgumentException(SR.Argument_ObjNotComObject, "o");
        }
        if (o.GetType() == t)
        {
            return o;
        }
        object obj = GetComObjectData(o, t);
        if (obj == null)
        {
            obj = InternalCreateWrapperOfType(o, t);
            if (!SetComObjectData(o, t, obj))
            {
                obj = GetComObjectData(o, t);
            }
        }
        return obj;
    }
References System.SR.Argument_NeedNonGenericType, System.SR.Argument_ObjNotComObject, System.SR.Argument_TypeNotComObject, System.Runtime.InteropServices.Marshal.GetComObjectData(), System.Runtime.InteropServices.Marshal.InternalCreateWrapperOfType(), System.Runtime.InteropServices.Marshal.IsBuiltInComSupported, System.Type.IsCOMObject, System.Type.IsGenericType, System.SR.NotSupported_COM, System.obj, and System.Runtime.InteropServices.Marshal.SetComObjectData().
Referenced by System.Runtime.InteropServices.Marshal.CreateWrapperOfType< T, TWrapper >().