Terraria: System.Runtime.InteropServices.Marshal.ZeroFreeCoTaskMemUTF8
ZeroFreeCoTaskMemUTF8()
static unsafe void System.Runtime.InteropServices.Marshal.ZeroFreeCoTaskMemUTF8 (IntPtr s) inline static
Definition at line 1504 of file Marshal.cs.
    {
        if (!(s == IntPtr.Zero))
        {
            Buffer.ZeroMemory((byte*)(void*)s, (nuint)string.strlen((byte*)(void*)s));
            FreeCoTaskMem(s);
        }
    }
References System.Runtime.InteropServices.Marshal.FreeCoTaskMem(), System.s, System.IntPtr.Zero, and System.Buffer.ZeroMemory().
Referenced by System.Runtime.InteropServices.Marshal.ZeroFreeCoTaskMemAnsi().