Terraria: System.Runtime.InteropServices.Marshal.OffsetOf
OffsetOf()
static IntPtr System.Runtime.InteropServices.Marshal.OffsetOf (Type t, string fieldName) inline static
Definition at line 28 of file Marshal.cs.
    {
        if ((object)t == null)
        {
            throw new ArgumentNullException("t");
        }
        FieldInfo field = t.GetField(fieldName, BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic);
        if ((object)field == null)
        {
            throw new ArgumentException(SR.Format(SR.Argument_OffsetOfFieldNotFound, t.FullName), "fieldName");
        }
        if (!(field is RtFieldInfo f))
        {
            throw new ArgumentException(SR.Argument_MustBeRuntimeFieldInfo, "fieldName");
        }
        return OffsetOfHelper(f);
    }
References System.SR.Argument_MustBeRuntimeFieldInfo, System.SR.Argument_OffsetOfFieldNotFound, System.SR.Format(), System.Type.FullName, System.Type.GetField(), and System.Runtime.InteropServices.Marshal.OffsetOfHelper().
Referenced by System.Security.Principal.WindowsIdentity.AddDeviceGroupSidClaims(), System.Security.Principal.WindowsIdentity.AddGroupSidClaims(), and System.Runtime.InteropServices.Marshal.OffsetOf< T >().