Terraria: System.Runtime.InteropServices.Marshal.SizeOf
SizeOf() [1/2]
static int System.Runtime.InteropServices.Marshal.SizeOf (object structure) inline static
Definition at line 697 of file Marshal.cs.
    {
        if (structure == null)
        {
            throw new ArgumentNullException("structure");
        }
        return SizeOfHelper(structure.GetType(), throwIfNotMarshalable: true);
    }
References System.Runtime.InteropServices.Marshal.SizeOfHelper().
Referenced by Microsoft.Xna.Framework.Graphics.DynamicIndexBuffer.DynamicIndexBuffer(), Microsoft.Xna.Framework.Graphics.IndexBuffer.IndexBuffer(), System.Security.Principal.WindowsIdentity.AddDeviceGroupSidClaims(), System.Security.Principal.WindowsIdentity.AddGroupSidClaims(), System.Security.Principal.WindowsIdentity.AddTokenClaims(), System.Net.HttpListener.AttachRequestQueueToUrlGroup(), Internal.Cryptography.Pal.ChainPal.BuildChain(), ReLogic.OS.Windows.NativeMethods.FlashInfo.CreateStart(), ReLogic.OS.Windows.NativeMethods.FlashInfo.CreateStop(), System.IO.MemoryMappedFiles.MemoryMappedView.CreateView(), System.Net.HttpListener.DetachRequestQueueFromUrlGroup(), Microsoft.Xna.Framework.Graphics.VertexDeclaration.FromType(), Internal.Cryptography.Pal.ChainPal.GetChainEngine(), ReLogic.Peripherals.RGB.Corsair.CorsairHelper.GetLedPositionsForMouseMatOrKeyboard(), Microsoft.Xna.Framework.Helpers.GetSizeOf< T >(), System.Security.Cryptography.ECCng.ImportKeyBlob(), System.Security.Principal.Win32.InitializeReferencedDomainsPointer(), System.Formats.Asn1.AsnDecoder.ReadEnumeratedValue(), System.Formats.Asn1.AsnDecoder.ReadNamedBitListValue(), System.Net.HttpListener.SetServerTimeout(), Microsoft.Xna.Framework.Helpers.SmartGetHashCode(), System.Security.Principal.SecurityIdentifier.TranslateToNTAccounts(), and System.Security.Principal.NTAccount.TranslateToSids().