Terraria: System.Runtime.InteropServices.Marshal.PtrToStringUni
PtrToStringUni() [1/2]
static unsafe? string System.Runtime.InteropServices.Marshal.PtrToStringUni (IntPtr ptr) inline static
Definition at line 652 of file Marshal.cs.
    {
        if (IsNullOrWin32Atom(ptr))
        {
            return null;
        }
        return new string((char*)(void*)ptr);
    }
References System.Runtime.InteropServices.Marshal.IsNullOrWin32Atom().
Referenced by System.Net.HttpListenerRequest.HttpListenerRequest(), System.Net.SecurityPackageInfoClass.SecurityPackageInfoClass(), System.Net.Http.WinInetProxyHelper.WinInetProxyHelper(), System.Security.AccessControl.Win32.ConvertSdToSddl(), Internal.Runtime.InteropServices.ComActivationContext.Create(), Internal.Cryptography.Pal.Native.SafeCertContextHandleWithKeyContainerDeletion.DeleteKeyContainer(), Internal.Cryptography.Pal.FindPal.FindByTemplateName(), System.Net.NegotiationInfoClass.GetAuthenticationPackageName(), System.Diagnostics.FileVersionInfo.GetFileVersionString(), System.Net.Http.HttpWindowsProxy.GetMultiProxy(), Internal.Cryptography.Pal.CertificatePal.GetPrivateKeyCsp(), Internal.Cryptography.Pal.X509Pal.GetPropertyAsString(), System.Security.Cryptography.CngKeyLite.GetPropertyAsString(), Internal.Cryptography.Helpers.GetPropertyAsString(), Internal.Runtime.InteropServices.InMemoryAssemblyLoader.LoadInMemoryAssembly(), System.Net.NetworkCredential.MarshalToString(), System.Net.NameResolutionPal.ParseAddressInfo(), System.Net.NameResolutionPal.ParseAddressInfoEx(), System.Runtime.InteropServices.Marshal.PtrToStringAuto(), System.Runtime.InteropServices.Marshal.PtrToStringAuto(), System.Runtime.InteropServices.Marshal.PtrToStringBSTR(), System.Net.SSPIWrapper.QueryStringContextAttributes(), System.Net.SSPIWrapper.QueryStringContextAttributes(), and System.Security.Principal.SecurityIdentifier.TranslateToNTAccounts().