Terraria: System.Runtime.InteropServices.Marshal.GetDelegateForFunctionPointer
GetDelegateForFunctionPointer()
static Delegate System.Runtime.InteropServices.Marshal.GetDelegateForFunctionPointer (IntPtr ptr, Type t) inline static
Definition at line 1414 of file Marshal.cs.
    {
        if (ptr == IntPtr.Zero)
        {
            throw new ArgumentNullException("ptr");
        }
        if ((object)t == null)
        {
            throw new ArgumentNullException("t");
        }
        if (!t.IsRuntimeImplemented())
        {
            throw new ArgumentException(SR.Argument_MustBeRuntimeType, "t");
        }
        if (t.IsGenericType)
        {
            throw new ArgumentException(SR.Argument_NeedNonGenericType, "t");
        }
        if (t.BaseType != typeof(MulticastDelegate) && t != typeof(MulticastDelegate))
        {
            throw new ArgumentException(SR.Arg_MustBeDelegate, "t");
        }
        return GetDelegateForFunctionPointerInternal(ptr, t);
    }
References System.SR.Arg_MustBeDelegate, System.SR.Argument_MustBeRuntimeType, System.SR.Argument_NeedNonGenericType, System.Type.BaseType, System.Runtime.InteropServices.Marshal.GetDelegateForFunctionPointerInternal(), System.Type.IsGenericType, System.Type.IsRuntimeImplemented(), and System.IntPtr.Zero.
Referenced by System.Net.Quic.Implementations.MsQuic.Internal.MsQuicApi.MsQuicApi(), System.Net.Sockets.DynamicWinsockMethods.CreateDelegate< T >(), System.Runtime.InteropServices.StandardOleMarshalObject.GetMarshalSizeMax(), and System.Runtime.InteropServices.StandardOleMarshalObject.MarshalInterface().