Terraria: System.Runtime.InteropServices.Marshal.StringToCoTaskMemAnsi
StringToCoTaskMemAnsi()
static unsafe IntPtr System.Runtime.InteropServices.Marshal.StringToCoTaskMemAnsi (string? s) inline static
Definition at line 1362 of file Marshal.cs.
    {
        if (s == null)
        {
            return IntPtr.Zero;
        }
        long num = (long)(s.Length + 1) * (long)SystemMaxDBCSCharSize;
        int num2 = (int)num;
        if (num2 != num)
        {
            ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument.s);
        }
        IntPtr intPtr = AllocCoTaskMem(num2);
        StringToAnsiString(s, (byte*)(void*)intPtr, num2);
        return intPtr;
    }
References System.Runtime.InteropServices.Marshal.AllocCoTaskMem(), System.s, System.Runtime.InteropServices.Marshal.StringToAnsiString(), System.Runtime.InteropServices.Marshal.SystemMaxDBCSCharSize, System.ThrowHelper.ThrowArgumentOutOfRangeException(), and System.IntPtr.Zero.
Referenced by Interop.Crypt32.FindOidInfo().