Terraria: System.Runtime.InteropServices.Marshal.GetTypeFromProgID
GetTypeFromProgID()
static Type System.Runtime.InteropServices.Marshal.GetTypeFromProgID (string progID, string server, bool throwOnError) inline static package
Definition at line 1758 of file Marshal.cs.
    {
        if (progID == null)
        {
            throw new ArgumentNullException("progID");
        }
        Guid lpclsid;
        int num = Interop.Ole32.CLSIDFromProgID(progID, out lpclsid);
        if (num < 0)
        {
            if (throwOnError)
            {
                throw GetExceptionForHR(num, new IntPtr(-1));
            }
            return null;
        }
        return GetTypeFromCLSID(lpclsid, server, throwOnError);
    }
References Interop.Ole32.CLSIDFromProgID(), System.Runtime.InteropServices.Marshal.GetExceptionForHR(), and System.Runtime.InteropServices.Marshal.GetTypeFromCLSID().
Referenced by System.Type.GetTypeFromProgID().