Terraria: System.Runtime.InteropServices.Marshal.Copy
Copy() [5/16]
static void System.Runtime.InteropServices.Marshal.Copy (int[] source, int startIndex, IntPtr destination, int length) inline static
Definition at line 800 of file Marshal.cs.
    {
        CopyToNative(source, startIndex, destination, length);
    }
References System.destination, System.length, System.source, and System.startIndex.
Referenced by System.Security.Principal.WindowsIdentity.WindowsIdentity(), System.Diagnostics.Tracing.DataCollector.AddNullTerminatedString(), System.Security.Principal.WindowsIdentity.AddTokenClaims(), System.Security.AccessControl.RawSecurityDescriptor.BinaryFormFromSddlForm(), System.Security.Principal.Win32.ConvertIntPtrSidToByteArraySid(), System.Reflection.Internal.StreamExtensions.CopyTo(), System.Net.NetworkInformation.Ping.CreatePingReplyFromIcmp6EchoReply(), System.Net.NetworkInformation.Ping.CreatePingReplyFromIcmpEchoReply(), System.Diagnostics.Tracing.EventSource.DecodeObjects(), System.Reflection.Internal.EncodingHelper.DecodeUtf8Prefixed(), Internal.Cryptography.Pal.StorePal.Export(), System.Net.Sockets.SocketAsyncEventArgs.FinishOperationAccept(), System.Net.HttpListener.GetChannelBindingFromTls(), System.Net.HttpListenerRequest.GetClientCertificateCore(), System.Diagnostics.Tracing.EventProvider.GetDataFromController(), System.Reflection.Metadata.Ecma335.StringHeap.GetNonVirtualStringBytes(), System.Security.AccessControl.Win32.GetSecurityInfo(), Microsoft.Xna.Framework.Graphics.EffectParameter.GetValueInt32Array(), Microsoft.Xna.Framework.Graphics.EffectParameter.GetValueMatrixArray(), Microsoft.Xna.Framework.Graphics.EffectParameter.GetValueMatrixTransposeArray(), Microsoft.Xna.Framework.Graphics.EffectParameter.GetValueQuaternionArray(), Microsoft.Xna.Framework.Graphics.EffectParameter.GetValueSingleArray(), Microsoft.Xna.Framework.Graphics.EffectParameter.GetValueVector2Array(), Microsoft.Xna.Framework.Graphics.EffectParameter.GetValueVector3Array(), Microsoft.Xna.Framework.Graphics.EffectParameter.GetValueVector4Array(), System.Net.ListenerClientCertAsyncResult.IOCompleted(), Interop.IpHlpApi.IpSocketAddress.MarshalIPAddress(), System.Reflection.Internal.ReadOnlyUnmanagedMemoryStream.Read(), System.Reflection.BlobUtilities.ReadBytes(), System.Reflection.Metadata.BlobReader.ReadBytes(), Terraria.Graphics.Capture.CaptureCamera.SaveImage(), Terraria.Graphics.Capture.CaptureCamera.SaveImage(), System.Net.Quic.Implementations.MsQuic.MsQuicConnection.SetNegotiatedAlpn(), Internal.Cryptography.Pal.Native.CRYPT_BIT_BLOB.ToByteArray(), Internal.Cryptography.Pal.Native.CRYPTOAPI_BLOB.ToByteArray(), System.Net.Security.SafeFreeContextBufferChannelBinding.ToString(), ReLogic.OS.Windows.NativeClipboard.TryGetText(), System.Reflection.Metadata.BlobBuilder.WriteBytesUnchecked(), System.Reflection.Metadata.BlobWriter.WriteBytesUnchecked(), and System.Net.HttpResponseStream.WriteCore().