Terraria: System.Runtime.InteropServices.Marshal.WriteInt64
WriteInt64() [3/3]
static void System.Runtime.InteropServices.Marshal.WriteInt64 (object ptr, int ofs, long val) inline static
Definition at line 113 of file Marshal.cs.
    {
        WriteValueSlow(ptr, ofs, val, delegate(IntPtr nativeHome, int offset, long value)
        {
            WriteInt64(nativeHome, offset, value);
        });
    }
References System.offset, System.value, and System.Runtime.InteropServices.Marshal.WriteInt64().
Referenced by System.Runtime.InteropServices.Marshal.WriteInt64(), System.Runtime.InteropServices.Marshal.WriteInt64(), System.Runtime.InteropServices.Marshal.WriteIntPtr(), and System.Runtime.InteropServices.Marshal.WriteIntPtr().