Terraria: System.Runtime.InteropServices.Marshal.AllocCoTaskMem
AllocCoTaskMem()
static IntPtr System.Runtime.InteropServices.Marshal.AllocCoTaskMem (int cb) inline static
Definition at line 1702 of file Marshal.cs.
    {
        IntPtr intPtr = Interop.Ole32.CoTaskMemAlloc((uint)cb);
        if (intPtr == IntPtr.Zero)
        {
            throw new OutOfMemoryException();
        }
        return intPtr;
    }
References Interop.Ole32.CoTaskMemAlloc(), and System.IntPtr.Zero.
Referenced by System.StubHelpers.AsAnyMarshaler.ConvertLayoutToNative(), System.StubHelpers.AsAnyMarshaler.ConvertStringBuilderToNative(), System.StubHelpers.AsAnyMarshaler.ConvertStringToNative(), System.StubHelpers.CSTRMarshaler.ConvertToNative(), System.StubHelpers.UTF8Marshaler.ConvertToNative(), System.StubHelpers.VBByValStrMarshaler.ConvertToNative(), System.Diagnostics.Tracing.EventPipeInternal.Enable(), System.Security.SecureString.MarshalToString(), System.Runtime.InteropServices.Marshal.StringToCoTaskMemAnsi(), System.Runtime.InteropServices.Marshal.StringToCoTaskMemUni(), and System.Runtime.InteropServices.Marshal.StringToCoTaskMemUTF8().