Terraria: System.Runtime.InteropServices.Marshal.GetHRForLastWin32Error
GetHRForLastWin32Error()
static int System.Runtime.InteropServices.Marshal.GetHRForLastWin32Error () inline static
Definition at line 1471 of file Marshal.cs.
    {
        int lastPInvokeError = GetLastPInvokeError();
        if ((lastPInvokeError & 0x80000000u) == 2147483648u)
        {
            return lastPInvokeError;
        }
        return (lastPInvokeError & 0xFFFF) | -2147024896;
    }
References System.Runtime.InteropServices.Marshal.GetLastPInvokeError().
Referenced by Interop.Kernel32.ProcessWaitHandle.ProcessWaitHandle(), Internal.Cryptography.Pal.X509Pal.ComputeCapiSha1OfPublicKey(), Internal.NativeCrypto.CapiHelper.CreateHashHandle(), Internal.NativeCrypto.CapiHelper.DeriveKey(), Internal.Cryptography.Pal.StorePal.Export(), Internal.Cryptography.Pal.CertificatePal.FilterPFXStore(), Internal.Cryptography.Pal.FindPal.FindCore< TState >(), Internal.Cryptography.Pal.CertificatePal.FromBlobOrFile(), Internal.Cryptography.Pal.StorePal.FromCertificate(), System.Security.Principal.WindowsIdentity.GetCurrentToken(), Internal.Cryptography.Pal.CertificatePal.GetSignerInPKCS7Store(), Internal.NativeCrypto.CapiHelper.ImportKeyBlob(), Internal.Cryptography.Pal.X509Pal.ImportPublicKeyInfo(), Internal.Cryptography.Pal.StorePal.LinkFromCertificateCollection(), System.Security.Principal.Win32.OpenThreadToken(), Internal.Cryptography.Pal.CertificatePal.PropagateKeyAlgorithmParametersFromChain(), System.Security.Principal.Win32.SetThreadToken(), Internal.NativeCrypto.CapiHelper.SignValue(), and Internal.NativeCrypto.CapiHelper.UnloadKey().