Terraria: System.Runtime.InteropServices.Marshal.AllocHGlobal
AllocHGlobal() [1/2]
static IntPtr System.Runtime.InteropServices.Marshal.AllocHGlobal (int cb) inline static
Definition at line 625 of file Marshal.cs.
    {
        return AllocHGlobal((IntPtr)cb);
    }
References System.Runtime.InteropServices.Marshal.AllocHGlobal().
Referenced by System.Reflection.Internal.NativeHeapMemoryBlock.DisposableData.DisposableData(), Microsoft.Win32.SafeHandles.SafePasswordHandle.SafePasswordHandle(), Microsoft.Win32.SafeHandles.SafeUnicodeStringHandle.SafeUnicodeStringHandle(), System.Security.SecureString.UnmanagedBuffer.Allocate(), System.Net.NameResolutionPal.GetAddrInfoExContext.AllocateContext(), System.Runtime.InteropServices.Marshal.AllocHGlobal(), Internal.Cryptography.Pal.Native.SafeLocalAllocHandle.Create(), System.Net.NetworkInformation.SystemIPGlobalProperties.GetActiveUdpListeners(), System.Net.NetworkInformation.SystemIPGlobalProperties.GetAllTcpConnections(), System.Net.NetworkInformation.HostInformationPal.GetFixedInfo(), System.Text.BaseCodePageEncoding.GetNativeMemory(), System.Net.NetworkInformation.SystemNetworkInterface.GetNetworkInterfaces(), System.Net.NetworkInformation.SystemIPv4InterfaceProperties.GetPerAdapterInfo(), System.Diagnostics.Tracing.EventProvider.GetSessionInfo(), System.Security.Cryptography.ECCng.ImportKeyBlob(), System.IO.Enumeration.FileSystemEnumerator< TResult >.Init(), System.Threading.LowLevelMonitor.Initialize(), Interop.HttpApi.SafeLocalFreeChannelBinding.LocalAlloc(), Microsoft.Win32.SafeHandles.SafeLocalAllocHandle.LocalAlloc(), System.Security.SecureString.MarshalToString(), System.Runtime.InteropServices.Marshal.ReAllocHGlobal(), System.Net.Quic.Implementations.MsQuic.MsQuicStream.SendReadOnlyMemoryAsync(), System.Net.Quic.Implementations.MsQuic.MsQuicStream.SendReadOnlyMemoryListAsync(), System.Net.Quic.Implementations.MsQuic.MsQuicStream.SendReadOnlySequenceAsync(), System.Net.RequestContextBase.SetBuffer(), System.Runtime.InteropServices.Marshal.StringToHGlobalAnsi(), System.Runtime.InteropServices.Marshal.StringToHGlobalUni(), and nativefiledialog.Utf8EncodeNullable().