Terraria: System.Runtime.InteropServices.Marshal.PtrToStructure
PtrToStructure() [1/2]
static ? object System.Runtime.InteropServices.Marshal.PtrToStructure (IntPtr ptr, [DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicConstructors | DynamicallyAccessedMemberTypes.NonPublicConstructors)] Type structureType) inline static
Definition at line 1164 of file Marshal.cs.
    {
        if (ptr == IntPtr.Zero)
        {
            return null;
        }
        if ((object)structureType == null)
        {
            throw new ArgumentNullException("structureType");
        }
        if (structureType.IsGenericType)
        {
            throw new ArgumentException(SR.Argument_NeedNonGenericType, "structureType");
        }
        if (!structureType.IsRuntimeImplemented())
        {
            throw new ArgumentException(SR.Argument_MustBeRuntimeType, "structureType");
        }
        object obj = Activator.CreateInstance(structureType, nonPublic: true);
        PtrToStructureHelper(ptr, obj, allowValueClasses: true);
        return obj;
    }
References System.SR.Argument_MustBeRuntimeType, System.SR.Argument_NeedNonGenericType, System.Activator.CreateInstance(), System.Type.IsGenericType, System.Type.IsRuntimeImplemented(), System.obj, System.Runtime.InteropServices.Marshal.PtrToStructureHelper(), and System.IntPtr.Zero.
Referenced by System.Security.Principal.WindowsIdentity.AddDeviceGroupSidClaims(), System.Security.Principal.WindowsIdentity.AddGroupSidClaims(), System.Security.Principal.WindowsIdentity.AddPrimarySidClaim(), System.Security.Principal.WindowsIdentity.AddTokenClaims(), System.Net.NetworkInformation.Ping.CreatePingReply(), Interop.Crypt32.FindAlgIdOidInfo(), Interop.Crypt32.FindOidInfo(), System.Diagnostics.FileVersionInfo.GetFixedFileInfo(), System.Net.NetworkInformation.HostInformationPal.GetFixedInfo(), ReLogic.Peripherals.RGB.Corsair.CorsairHelper.GetLedPositionsForMouseMatOrKeyboard(), System.Net.NetworkInformation.SystemNetworkInterface.GetNetworkInterfaces(), System.Net.NetworkInformation.SystemIPv4InterfaceProperties.GetPerAdapterInfo(), ReLogic.Peripherals.RGB.Corsair.CorsairDeviceGroup.Initialize(), Interop.IpHlpApi.IpAdapterAddress.MarshalIpAddressCollection(), Interop.IpHlpApi.IpAdapterAddress.MarshalIpAddressInformationCollection(), System.Net.NetworkInformation.SystemUnicastIPAddressInformation.MarshalUnicastIpAddressInformationCollection(), and System.Security.Principal.SecurityIdentifier.TranslateToNTAccounts().