Terraria: System.Runtime.InteropServices.Marshal.UnsafeAddrOfPinnedArrayElement
UnsafeAddrOfPinnedArrayElement()
static unsafe IntPtr System.Runtime.InteropServices.Marshal.UnsafeAddrOfPinnedArrayElement (Array arr, int index) inline static
Definition at line 775 of file Marshal.cs.
    {
        if (arr == null)
        {
            throw new ArgumentNullException("arr");
        }
        void* ptr = Unsafe.AsPointer(ref MemoryMarshal.GetArrayDataReference(arr));
        return (IntPtr)((byte*)ptr + (nuint)((nint)(uint)index * (nint)arr.GetElementSize()));
    }
References System.Runtime.InteropServices.MemoryMarshal.GetArrayDataReference(), and System.index.
Referenced by System.Net.HttpRequestStream.HttpRequestStreamAsyncResult.HttpRequestStreamAsyncResult(), System.Net.HttpResponseStreamAsyncResult.HttpResponseStreamAsyncResult(), System.Net.WebSockets.WebSocketBuffer.WebSocketBuffer(), System.Net.Quic.Implementations.MsQuic.Internal.SafeMsQuicConfigurationHandle.Create(), System.Net.Sockets.SocketAsyncEventArgs.DoOperationReceiveMessageFrom(), System.Net.Sockets.SocketAsyncEventArgs.DoOperationSendPackets(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.DrawUserIndexedPrimitives< T >(), System.Net.SSPIWrapper.EncryptDecryptHelper(), System.Net.SSPIWrapper.EncryptDecryptHelper(), System.Net.Sockets.SocketAsyncEventArgs.FinishOperationReceiveMessageFrom(), System.Net.WebSockets.WebSocketBuffer.PinSendBuffer(), System.Net.Sockets.SocketPal.Receive(), System.Net.ListenerClientCertAsyncResult.Reset(), System.Net.Sockets.SocketPal.Send(), System.Net.HttpListener.SendError(), System.Net.Sockets.SocketAsyncEventArgs.SetupMultipleBuffers(), and System.Net.Quic.Implementations.MsQuic.MsQuicListener.Start().