Terraria: System.Runtime.InteropServices.Marshal.StringToHGlobalUni
StringToHGlobalUni()
static unsafe IntPtr System.Runtime.InteropServices.Marshal.StringToHGlobalUni (string? s) inline static
Definition at line 1310 of file Marshal.cs.
    {
        if (s == null)
        {
            return IntPtr.Zero;
        }
        int num = (s.Length + 1) * 2;
        if (num < s.Length)
        {
            ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument.s);
        }
        IntPtr intPtr = AllocHGlobal((IntPtr)num);
        s.CopyTo(new Span<char>((void*)intPtr, s.Length));
        *(short*)((byte*)(void*)intPtr + (nint)s.Length * (nint)2) = 0;
        return intPtr;
    }
References System.Runtime.InteropServices.Marshal.AllocHGlobal(), System.s, System.ThrowHelper.ThrowArgumentOutOfRangeException(), and System.IntPtr.Zero.
Referenced by Microsoft.Win32.SafeHandles.SafePasswordHandle.SafePasswordHandle(), Microsoft.Win32.SafeHandles.SafeUnicodeStringHandle.SafeUnicodeStringHandle(), System.Security.Cryptography.RSAImplementation.RSACng.EncryptOrDecrypt(), System.Security.Cryptography.RSACng.EncryptOrDecrypt(), System.Net.Http.WinInetProxyHelper.GetProxyForUrl(), ReLogic.OS.Windows.NativeClipboard.SetText(), System.Security.Cryptography.RSAImplementation.RSACng.SignHash(), System.Security.Cryptography.RSACng.SignHash(), System.Runtime.InteropServices.Marshal.StringToHGlobalAuto(), System.Security.Cryptography.RSAImplementation.RSACng.TryEncryptOrDecrypt(), System.Security.Cryptography.RSACng.TryEncryptOrDecrypt(), System.Security.Cryptography.RSAImplementation.RSACng.TrySignHash(), System.Security.Cryptography.RSACng.TrySignHash(), System.Security.Cryptography.RSAImplementation.RSACng.VerifyHash(), and System.Security.Cryptography.RSACng.VerifyHash().