Terraria: System.Runtime.InteropServices.Marshal.GetExceptionForHR
GetExceptionForHR() [1/2]
static ? Exception System.Runtime.InteropServices.Marshal.GetExceptionForHR (int errorCode) inline static
Definition at line 1218 of file Marshal.cs.
    {
        return GetExceptionForHR(errorCode, IntPtr.Zero);
    }
References System.Runtime.InteropServices.Marshal.GetExceptionForHR(), and System.IntPtr.Zero.
Referenced by System.Runtime.InteropServices.Marshal.GetExceptionForHR(), System.Runtime.InteropServices.Marshal.GetTypeFromProgID(), System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(), and System.Runtime.InteropServices.Marshal.ThrowExceptionForHR().