Terraria: System.Runtime.InteropServices.Marshal.PtrToStringAnsi
PtrToStringAnsi() [1/2]
static unsafe? string System.Runtime.InteropServices.Marshal.PtrToStringAnsi (IntPtr ptr) inline static
Definition at line 630 of file Marshal.cs.
    {
        if (IsNullOrWin32Atom(ptr))
        {
            return null;
        }
        return new string((sbyte*)(void*)ptr);
    }
References System.Runtime.InteropServices.Marshal.IsNullOrWin32Atom().
Referenced by Microsoft.Xna.Framework.Graphics.EffectAnnotation.EffectAnnotation(), Microsoft.Xna.Framework.Graphics.EffectParameter.EffectParameter(), Microsoft.Xna.Framework.Graphics.EffectPass.EffectPass(), Microsoft.Xna.Framework.Graphics.EffectTechnique.EffectTechnique(), Microsoft.Xna.Framework.Graphics.GraphicsAdapter.GraphicsAdapter(), System.Net.HttpListenerRequest.HttpListenerRequest(), Internal.Cryptography.Pal.X509Pal.DecodeX509EnhancedKeyUsageExtension(), Internal.Cryptography.Pal.FindPal.FindByApplicationPolicy(), Internal.Cryptography.Pal.FindPal.FindByCertificatePolicy(), Internal.Cryptography.Pal.FindPal.FindByTemplateName(), System.IO.Compression.ZLibNative.ZLibStreamHandle.GetErrorMessage(), Microsoft.Xna.Framework.Graphics.EffectParameter.GetValueString(), System.Net.WebSockets.WebSocketProtocolComponent.MarshalAndVerifyHttpHeader(), and System.Net.Quic.Implementations.MsQuic.MsQuicListener.NativeCallbackHandler().