Terraria: System.Runtime.InteropServices.Marshal.IsComObject
IsComObject()
static bool System.Runtime.InteropServices.Marshal.IsComObject (object o) inline static
Definition at line 353 of file Marshal.cs.
    {
        if (o == null)
        {
            throw new ArgumentNullException("o");
        }
        return o is __ComObject;
    }
Referenced by System.Runtime.InteropServices.ComAwareEventInfo.AddEventHandler(), System.ComponentModel.ReferenceConverter.ConvertTo(), and System.Runtime.InteropServices.ComAwareEventInfo.RemoveEventHandler().