Terraria: System.Runtime.InteropServices.Marshal.GetLastWin32Error
GetLastWin32Error()
static int System.Runtime.InteropServices.Marshal.GetLastWin32Error () inline static
Definition at line 1567 of file Marshal.cs.
    {
        return GetLastPInvokeError();
    }
References System.Runtime.InteropServices.Marshal.GetLastPInvokeError().
Referenced by System.Security.AccessControl.Privilege.TlsContents.TlsContents(), System.Net.Http.WinInetProxyHelper.WinInetProxyHelper(), Internal.Cryptography.Pal.StorePal.Add(), System.Security.AccessControl.RawSecurityDescriptor.BinaryFormFromSddlForm(), Interop.crypt32.CertCreateCertificateChainEngine(), Interop.crypt32.CertGetNameString(), System.Security.AccessControl.Win32.ConvertSdToSddl(), Interop.Kernel32.CopyFile(), Internal.Cryptography.Pal.CertificatePal.CopyWithEphemeralKey(), Internal.Cryptography.Pal.CertificatePal.CopyWithPersistedCapiKey(), Internal.Cryptography.Pal.CertificatePal.CopyWithPersistedCngKey(), System.IO.FileSystem.CreateDirectory(), System.IO.Enumeration.FileSystemEnumerator< TResult >.CreateDirectoryHandle(), System.Security.Principal.Win32.CreateSidFromString(), Interop.Kernel32.CreateSymbolicLink(), System.Security.Principal.Win32.CreateWellKnownSid(), Internal.Cryptography.Pal.X509Pal.DecodeKeyBlob(), Internal.Cryptography.Pal.Native.Helpers.DecodeObject< TResult >(), Internal.Cryptography.Pal.Native.Helpers.DecodeObject< TResult >(), System.IO.FileSystem.DeleteFile(), System.Net.Sockets.SafeSocketHandle.DoCloseHandle(), System.Security.Principal.WindowsIdentity.DuplicateAccessToken(), Interop.crypt32.EncodeObject(), Interop.crypt32.EncodeObject(), System.IO.FileSystem.FillAttributeInfo(), System.IO.FileSystem.FillAttributeInfo(), Internal.Cryptography.Pal.FindPal.FindCore< TState >(), Internal.Cryptography.Pal.StorePal.FromBlobOrFile(), Internal.Cryptography.Pal.StorePal.FromSystemStore(), Internal.Cryptography.Pal.X509Pal.GetCertContentType(), Internal.Cryptography.Pal.X509Pal.GetCertContentType(), System.Security.Principal.WindowsIdentity.GetCurrentProcessToken(), System.IO.Win32Marshal.GetExceptionForLastWin32Error(), System.IO.FileSystem.GetFinalLinkTarget(), System.IO.FileSystem.GetFindData(), System.IO.PathHelper.GetFullPathName(), System.IO.FileSystem.GetImmediateLinkTarget(), System.Net.Sockets.SocketPal.GetLastSocketError(), Interop.Kernel32.GetMessage(), Internal.Cryptography.Pal.CertificatePal.GetPrivateKeyCsp(), System.Net.Http.WinInetProxyHelper.GetProxyForUrl(), System.Security.Principal.WindowsIdentity.GetTokenInformation(), System.Security.Principal.Win32.GetWindowsAccountDomainSid(), System.Diagnostics.NtProcessManager.HandleLastWin32Error(), System.Net.SocketProtocolSupportPal.IsSupported(), Internal.Cryptography.Pal.StorePal.LinkFromCertificateCollection(), System.Security.AccessControl.Privilege.LuidFromPrivilege(), System.IO.FileSystem.MoveDirectory(), System.IO.MemoryMappedFiles.MemoryMappedFile.OpenCore(), System.IO.FileSystem.OpenHandle(), System.Diagnostics.ProcessManager.OpenProcess(), System.Diagnostics.ProcessManager.OpenThread(), Internal.Cryptography.Pal.StorePal.Remove(), System.IO.FileSystem.RemoveDirectoryInternal(), System.IO.FileSystem.RemoveDirectoryRecursive(), System.IO.FileSystem.ReplaceFile(), System.Security.AccessControl.Privilege.Revert(), Internal.Cryptography.Pal.StorePal.SaveToMemoryStore(), System.IO.FileSystem.SetAttributes(), System.Diagnostics.Process.SetPrivilege(), System.Diagnostics.Process.ShellExecuteHelper.ShellExecuteFunction(), System.Diagnostics.Process.StartWithCreateProcess(), System.IO.FileSystem.ThrowExceptionEncryptDecryptFail(), System.Security.AccessControl.Privilege.ToggleState(), System.IO.PathHelper.TryExpandShortFileName(), System.IO.FileSystemAclExtensions.ValidateFileHandle(), Internal.Cryptography.Pal.ChainPal.Verify(), and Internal.Cryptography.Pal.X509Pal.X500DistinguishedNameEncode().