Terraria: System.Runtime.InteropServices.Marshal.WriteInt16
WriteInt16() [6/6]
static void System.Runtime.InteropServices.Marshal.WriteInt16 (object ptr, int ofs, short val) inline static
Definition at line 97 of file Marshal.cs.
    {
        WriteValueSlow(ptr, ofs, val, delegate(IntPtr nativeHome, int offset, short value)
        {
            WriteInt16(nativeHome, offset, value);
        });
    }
References System.offset, System.value, and System.Runtime.InteropServices.Marshal.WriteInt16().
Referenced by System.Net.HttpResponseStream.WriteCore(), System.Runtime.InteropServices.Marshal.WriteInt16(), System.Runtime.InteropServices.Marshal.WriteInt16(), System.Runtime.InteropServices.Marshal.WriteInt16(), System.Runtime.InteropServices.Marshal.WriteInt16(), and System.Runtime.InteropServices.Marshal.WriteInt16().