Terraria: System.Runtime.InteropServices.Marshal.ZeroFreeBSTR
ZeroFreeBSTR()
static unsafe void System.Runtime.InteropServices.Marshal.ZeroFreeBSTR (IntPtr s) inline static
Definition at line 1481 of file Marshal.cs.
    {
        if (!(s == IntPtr.Zero))
        {
            Buffer.ZeroMemory((byte*)(void*)s, SysStringByteLen(s));
            FreeBSTR(s);
        }
    }
References System.Runtime.InteropServices.Marshal.FreeBSTR(), System.s, System.Runtime.InteropServices.Marshal.SysStringByteLen(), System.IntPtr.Zero, and System.Buffer.ZeroMemory().