Terraria: GraniteBiome.Magma.Magma
Magma()
GraniteBiome.Magma.Magma (double pressure, double resistance, bool active) inline private
         {
             Pressure = pressure;
             Resistance = resistance;
             IsActive = active;
         }
References GraniteBiome.Magma.IsActive, GraniteBiome.Magma.Pressure, and GraniteBiome.Magma.Resistance.
Referenced by GraniteBiome.Magma.CreateEmpty(), GraniteBiome.Magma.CreateFlow(), and GraniteBiome.Magma.ToFlow().