Terraria: System.Diagnostics.Tracing.ActivityTracker.ActivityInfo.AddIdToGuid
AddIdToGuid()
static unsafe int System.Diagnostics.Tracing.ActivityTracker.ActivityInfo.AddIdToGuid (Guid * outPtr, int whereToAddId, uint id, bool overflow = false) inline static private
Definition at line 116 of file ActivityTracker.cs.
        {
            byte* ptr = (byte*)outPtr;
            byte* ptr2 = ptr + 12;
            ptr += whereToAddId;
            if (ptr2 <= ptr)
            {
                return 13;
            }
            if (0 < id && id <= 10 && !overflow)
            {
                WriteNibble(ref ptr, ptr2, id);
            }
            else
            {
                uint num = 4u;
                if (id <= 255)
                {
                    num = 1u;
                }
                else if (id <= 65535)
                {
                    num = 2u;
                }
                else if (id <= 16777215)
                {
                    num = 3u;
                }
                if (overflow)
                {
                    if (ptr2 <= ptr + 2)
                    {
                        return 13;
                    }
                    WriteNibble(ref ptr, ptr2, 11u);
                }
                WriteNibble(ref ptr, ptr2, 12 + (num - 1));
                if (ptr < ptr2 && *ptr != 0)
                {
                    if (id < 4096)
                    {
                        *ptr = (byte)(192 + (id >> 8));
                        id &= 0xFFu;
                    }
                    ptr++;
                }
                while (0 < num)
                {
                    if (ptr2 <= ptr)
                    {
                        ptr++;
                        break;
                    }
                    *(ptr++) = (byte)id;
                    id >>= 8;
                    num--;
                }
            }
            *(int*)((byte*)outPtr + (nint)3 * (nint)4) = (int)(*(uint*)outPtr + *(uint*)((byte*)outPtr + 4) + *(uint*)((byte*)outPtr + (nint)2 * (nint)4) + 1503500717) ^ Environment.ProcessId;
            return (int)(ptr - (byte*)outPtr);
        }
References System.Environment.ProcessId, and System.Diagnostics.Tracing.ActivityTracker.ActivityInfo.WriteNibble().
Referenced by System.Diagnostics.Tracing.ActivityTracker.ActivityInfo.CreateActivityPathGuid(), and System.Diagnostics.Tracing.ActivityTracker.ActivityInfo.CreateOverflowGuid().