Terraria: System.Diagnostics.Tracing.ActivityTracker.ActivityInfo.CreateOverflowGuid
CreateOverflowGuid()
unsafe void System.Diagnostics.Tracing.ActivityTracker.ActivityInfo.CreateOverflowGuid (Guid * outPtr) inline private
Definition at line 99 of file ActivityTracker.cs.
        {
            for (ActivityInfo creator = m_creator; creator != null; creator = creator.m_creator)
            {
                if (creator.m_activityPathGuidOffset <= 10)
                {
                    uint id = (uint)Interlocked.Increment(ref creator.m_lastChildID);
                    *outPtr = creator.m_guid;
                    int num = AddIdToGuid(outPtr, creator.m_activityPathGuidOffset, id, overflow: true);
                    if (num <= 12)
                    {
                        break;
                    }
                }
            }
        }
References System.Diagnostics.Tracing.ActivityTracker.ActivityInfo.AddIdToGuid(), System.Threading.Interlocked.Increment(), and System.Diagnostics.Tracing.ActivityTracker.ActivityInfo.m_creator.
Referenced by System.Diagnostics.Tracing.ActivityTracker.ActivityInfo.CreateActivityPathGuid().