Terraria: UIWorkshopSelectWorldToPublish.PopulateEntries
PopulateEntries()
void UIWorkshopSelectWorldToPublish.PopulateEntries () inline private
     {
         Main.LoadWorlds();
         _entryList.Clear();
         IOrderedEnumerable<WorldFileData> orderedEnumerable = from x in new List<WorldFileData>(Main.WorldList)
             orderby x.IsFavorite descending, x.Name, x.GetFileName()
             select x;
         _entryList.Clear();
         int num = 0;
         foreach (WorldFileData item in orderedEnumerable)
         {
             _entryList.Add(new UIWorkshopPublishWorldListItem(this, item, num++));
         }
     }
References _entryList, UIList.Add(), UIList.Clear(), Main.LoadWorlds(), and Main.WorldList.
Referenced by OnActivate().