Terraria: CaptureCamera.FinishCapture
FinishCapture()
void CaptureCamera.FinishCapture () inline private
     {
         if (_activeSettings.UseScaling)
         {
             int num = 0;
             while (!SaveImage(_outputImageSize.Width, _outputImageSize.Height, ImageFormat.Png, Main.SavePath + Path.DirectorySeparatorChar + "Captures" + Path.DirectorySeparatorChar + _activeSettings.OutputName + ".png"))
             {
                 GC.Collect();
                 Thread.Sleep(5);
                 num++;
                 Console.WriteLine(Language.GetTextValue("Error.CaptureError"));
                 if (num > 5)
                 {
                     Console.WriteLine(Language.GetTextValue("Error.UnableToCapture"));
                     break;
                 }
             }
         }
         _outputData = null;
         _scaledFrameData = null;
         Main.GlobalTimerPaused = false;
         CaptureInterface.EndCamera();
         if (_scaledFrameBuffer != null)
         {
             _scaledFrameBuffer.Dispose();
             _scaledFrameBuffer = null;
         }
         _activeSettings = null;
     }
References _activeSettings, _outputData, _outputImageSize, _scaledFrameBuffer, _scaledFrameData, CaptureInterface.EndCamera(), Language.GetTextValue(), Main.GlobalTimerPaused, CaptureSettings.OutputName, SaveImage(), Main.SavePath, and CaptureSettings.UseScaling.
Referenced by DrawTick().