Terraria: MS.Internal.Xml.XPath.XPathArrayIterator.XPathArrayIterator
XPathArrayIterator() [3/3]
MS.Internal.Xml.XPath.XPathArrayIterator.XPathArrayIterator (XPathNodeIterator nodeIterator) inline
Definition at line 56 of file XPathArrayIterator.cs.
    {
        list = new ArrayList();
        while (nodeIterator.MoveNext())
        {
            list.Add(nodeIterator.Current.Clone());
        }
    }
References System.Collections.IList.Add(), System.Xml.XPath.XPathNavigator.Clone(), System.Xml.XPath.XPathNodeIterator.Current, MS.Internal.Xml.XPath.XPathArrayIterator.list, and System.Xml.XPath.XPathNodeIterator.MoveNext().