Terraria: TETeleportationPylon.PlacementPreviewHook_CheckIfCanPlace
PlacementPreviewHook_CheckIfCanPlace()
static int TETeleportationPylon.PlacementPreviewHook_CheckIfCanPlace (int x, int y, int type = 597, int style = 0, int direction = 1, int alternate = 0) inline static
     {
         TeleportPylonType pylonTypeFromPylonTileStyle = GetPylonTypeFromPylonTileStyle(style);
         if (Main.PylonSystem.HasPylonOfType(pylonTypeFromPylonTileStyle))
         {
             return 1;
         }
         return 0;
     }
References GetPylonTypeFromPylonTileStyle(), TeleportPylonsSystem.HasPylonOfType(), and Main.PylonSystem.
Referenced by TileObjectData.Initialize().