Terraria: TETeleportationPylon.NetPlaceEntityAttempt
NetPlaceEntityAttempt()
override void TETeleportationPylon.NetPlaceEntityAttempt (int x, int y) inline virtual
Reimplemented from TileEntity.
     {
         if (!TryGetPylonTypeFromTileCoords(x, y, out var pylonType))
         {
             RejectPlacementFromNet(x, y);
             return;
         }
         if (Main.PylonSystem.HasPylonOfType(pylonType))
         {
             RejectPlacementFromNet(x, y);
             return;
         }
         int number = Place(x, y);
         NetMessage.SendData(86, -1, -1, null, number, x, y);
     }
References TeleportPylonsSystem.HasPylonOfType(), Place(), Main.PylonSystem, RejectPlacementFromNet(), NetMessage.SendData(), and TryGetPylonTypeFromTileCoords().