Terraria: UIWorkshopPublishWorldListItem.InitializeAppearance
InitializeAppearance()
void UIWorkshopPublishWorldListItem.InitializeAppearance () inline private
     {
         Height.Set(82f, 0f);
         Width.Set(0f, 1f);
         SetPadding(6f);
         SetColorsToNotHovered();
     }
References UIElement.Height, StyleDimension.Set(), SetColorsToNotHovered(), UIElement.SetPadding(), and UIElement.Width.
Referenced by UIWorkshopPublishWorldListItem().