Terraria: LegacyAudioSystem.LoadFromSources
LoadFromSources()
void LegacyAudioSystem.LoadFromSources () inline
Implements IAudioSystem.
     {
         List<IContentSource> fileSources = FileSources;
         for (int i = 0; i < AudioTracks.Length; i++)
         {
             if (TrackNamesByIndex.TryGetValue(i, out var value))
             {
                 string assetPath = "Music" + Path.DirectorySeparatorChar + value;
                 IAudioTrack audioTrack = DefaultTrackByIndex[i];
                 IAudioTrack audioTrack2 = audioTrack;
                 IAudioTrack audioTrack3 = FindReplacementTrack(fileSources, assetPath);
                 if (audioTrack3 != null)
                 {
                     audioTrack2 = audioTrack3;
                 }
                 if (AudioTracks[i] != audioTrack2)
                 {
                     AudioTracks[i].Stop(AudioStopOptions.Immediate);
                 }
                 if (AudioTracks[i] != audioTrack)
                 {
                     AudioTracks[i].Dispose();
                 }
                 AudioTracks[i] = audioTrack2;
             }
         }
     }
References AudioTracks, DefaultTrackByIndex, FileSources, FindReplacementTrack(), IAudioTrack.Stop(), and TrackNamesByIndex.
Referenced by UseSources().