Terraria: LegacyAudioSystem.UpdateAmbientCueState
UpdateAmbientCueState()
void LegacyAudioSystem.UpdateAmbientCueState (int i, bool gameIsActive, ref float trackVolume, float systemVolume) inline
Implements IAudioSystem.
     {
         if (!WaveBank.IsPrepared)
         {
             return;
         }
         if (systemVolume == 0f)
         {
             if (AudioTracks[i].IsPlaying)
             {
                 AudioTracks[i].Stop(AudioStopOptions.Immediate);
             }
             return;
         }
         if (!AudioTracks[i].IsPlaying)
         {
             AudioTracks[i].Reuse();
             AudioTracks[i].Play();
             AudioTracks[i].SetVariable("Volume", trackVolume * systemVolume);
             return;
         }
         if (AudioTracks[i].IsPaused && gameIsActive)
         {
             AudioTracks[i].Resume();
             return;
         }
         trackVolume += 0.005f;
         if (trackVolume > 1f)
         {
             trackVolume = 1f;
         }
         AudioTracks[i].SetVariable("Volume", trackVolume * systemVolume);
     }
References AudioTracks, IAudioTrack.Play(), IAudioTrack.Resume(), IAudioTrack.Reuse(), IAudioTrack.SetVariable(), IAudioTrack.Stop(), and WaveBank.