Terraria: Language.GetText
GetText()
static LocalizedText Language.GetText (string key) inline static
     {
         return LanguageManager.Instance.GetText(key);
     }
References LanguageManager.GetText(), and LanguageManager.Instance.
Referenced by Achievement.Achievement(), CustomEntryIcon.CustomEntryIcon(), GameTipsDisplay.GameTip.GameTip(), ItemTooltip.ItemTooltip(), Segments.LocalizedTextSegment.LocalizedTextSegment(), UICharacterNameButton.UICharacterNameButton(), UIVirtualKeyboard.UIVirtualKeyboard(), UIWorkshopPublishResourcePackListItem.UIWorkshopPublishResourcePackListItem(), UIWorkshopPublishWorldListItem.UIWorkshopPublishWorldListItem(), UIResourcePackSelectionMenu.AddBackAndFolderButtons(), AWorkshopPublishInfoState< TPublishedObjectType >.AddBackButton(), ChatCommandProcessor.AddCommand< T >(), UIWorkshopHub.AddDescriptionPanel(), UIWorldCreation.AddDescriptionPanel(), AWorkshopPublishInfoState< TPublishedObjectType >.AddDescriptionPanel(), AWorkshopPublishInfoState< TPublishedObjectType >.AddPublishButton(), UIBestiaryTest.AddSearchBar(), UICreativeInfiniteItemsDisplay.AddSearchBar(), UIWorldCreation.AddWorldDifficultyOptions(), UIWorldCreation.AddWorldEvilOptions(), UIWorldCreation.AddWorldSizeOptions(), UIBestiarySortingOptionsGrid.BuildGrid(), Lang.BuildMapAtlas(), UIReportsPage.BuildPage(), UIResourcePackInfoMenu.BuildPage(), UIResourcePackSelectionMenu.BuildPage(), UICreativeInfiniteItemsDisplay.BuildSacrificeMenuContents(), UIVirtualKeyboard.BuildSpaceBarArea(), AWorkshopPublishInfoState< TPublishedObjectType >.ClearOptionDescription(), UIWorkshopHub.ClearOptionDescription(), UIWorldCreation.ClearOptionDescription(), HelpCommand.ComposeMessage(), AWorkshopPublishInfoState< TPublishedObjectType >.CreateInsturctionsPanel(), UIResourcePackSelectionMenu.CreatePackToggleButton(), AWorkshopPublishInfoState< TPublishedObjectType >.CreatePreviewImageSelectionPanel(), AWorkshopPublishInfoState< TPublishedObjectType >.CreatePublicSettingsRow(), AWorkshopPublishInfoState< TPublishedObjectType >.CreateSteamDisclaimer(), AWorkshopPublishInfoState< TPublishedObjectType >.CreateStylizedCategoryPanel(), AWorkshopPublishInfoState< TPublishedObjectType >.CreateTagOptionsPanel(), Main.DrawMenu(), DD2Event.FailureMessage(), Lang.FillNameCacheArray< IdClass, IdType >(), BossBestiaryInfoElement.GetSearchString(), FilterProviderInfoElement.GetSearchString(), NamePlateInfoElement.GetSearchString(), RareSpawnBestiaryInfoElement.GetSearchString(), Main.HelpText(), Lang.InitializeLegacyLocalization(), UIAchievementsMenu.InitializePage(), UIEmotesMenu.InitializePage(), UICharacterCreation.MakeBackAndCreatebuttons(), UIWorldCreation.MakeBackAndCreatebuttons(), UIBestiaryTest.MakeExitButton(), UIWorkshopHub.MakeFancyButton(), UICharacterCreation.MakeInfoMenu(), UIWorldCreation.MakeInfoMenu(), UICharacterSelect.OnInitialize(), UIManageControls.OnInitialize(), UIWorkshopHub.OnInitialize(), UIWorkshopSelectResourcePackToPublish.OnInitialize(), UIWorkshopSelectWorldToPublish.OnInitialize(), UIWorkshopWorldImport.OnInitialize(), UIWorldSelect.OnInitialize(), UICreativeInfiniteItemsDisplay.OpenVirtualKeyboardWhenNeeded(), UIBestiaryTest.OpenVirtualKeyboardWhenNeeded(), ChatInitializer.PrepareAliases(), CreativePowers.ModifyWindDirectionAndStrength.ProvideSlider(), CreativePowers.ModifyRainPower.ProvideSlider(), FilterProviderInfoElement.ProvideUIElement(), FlavorTextBestiaryInfoElement.ProvideUIElement(), NamePlateInfoElement.ProvideUIElement(), NPCStatsReportInfoElement.ProvideUIElement(), WorldFileData.SetWorldSize(), AWorkshopPublishInfoState< TPublishedObjectType >.ShowOptionDescription(), UIWorkshopHub.ShowOptionDescription(), UICharacterCreation.UpdateDifficultyDescription(), and UIResourcePackSelectionMenu.UpdateTitles().