Terraria: Terraria.Social.Steam.WorkshopHelper.UGCBased.PublishedItemsFinder.Refresh
Refresh()
void Terraria.Social.Steam.WorkshopHelper.UGCBased.PublishedItemsFinder.Refresh () inline
Definition at line 145 of file WorkshopHelper.cs.
            {
                //IL_0001: Unknown result type (might be due to invalid IL or missing references)
                //IL_0006: Unknown result type (might be due to invalid IL or missing references)
                //IL_0009: Unknown result type (might be due to invalid IL or missing references)
                //IL_0011: Unknown result type (might be due to invalid IL or missing references)
                //IL_0016: Unknown result type (might be due to invalid IL or missing references)
                //IL_001c: Unknown result type (might be due to invalid IL or missing references)
                //IL_0021: Unknown result type (might be due to invalid IL or missing references)
                //IL_002d: Unknown result type (might be due to invalid IL or missing references)
                //IL_0032: Unknown result type (might be due to invalid IL or missing references)
                //IL_0037: Unknown result type (might be due to invalid IL or missing references)
                //IL_003e: Unknown result type (might be due to invalid IL or missing references)
                CSteamID steamID = SteamUser.GetSteamID();
                m_UGCQueryHandle = SteamUGC.CreateQueryUserUGCRequest(((CSteamID)(ref steamID)).GetAccountID(), (EUserUGCList)0, (EUGCMatchingUGCType)(-1), (EUserUGCListSortOrder)0, SteamUtils.GetAppID(), SteamUtils.GetAppID(), 1u);
                CoreSocialModule.SetSkipPulsing(shouldSkipPausing: true);
                SteamAPICall_t val = SteamUGC.SendQueryUGCRequest(m_UGCQueryHandle);
                OnSteamUGCQueryCompletedCallResult.Set(val, (APIDispatchDelegate<SteamUGCQueryCompleted_t>)OnSteamUGCQueryCompleted);
                CoreSocialModule.SetSkipPulsing(shouldSkipPausing: false);
            }
References Terraria.Social.Steam.WorkshopHelper.UGCBased.PublishedItemsFinder.m_UGCQueryHandle, Terraria.Social.Steam.WorkshopHelper.UGCBased.PublishedItemsFinder.OnSteamUGCQueryCompleted(), Terraria.Social.Steam.WorkshopHelper.UGCBased.PublishedItemsFinder.OnSteamUGCQueryCompletedCallResult, and Terraria.Social.Steam.CoreSocialModule.SetSkipPulsing().
Referenced by Terraria.Social.Steam.WorkshopHelper.UGCBased.PublishedItemsFinder.Prepare().