Terraria: Terraria.Social.Steam.WorkshopHelper.UGCBased.PublishedItemsFinder.OnSteamUGCQueryCompleted
OnSteamUGCQueryCompleted()
void Terraria.Social.Steam.WorkshopHelper.UGCBased.PublishedItemsFinder.OnSteamUGCQueryCompleted (SteamUGCQueryCompleted_t pCallback, bool bIOFailure) inline private
Definition at line 166 of file WorkshopHelper.cs.
            {
                //IL_000e: Unknown result type (might be due to invalid IL or missing references)
                //IL_000f: Unknown result type (might be due to invalid IL or missing references)
                //IL_0015: Invalid comparison between Unknown and I4
                //IL_0020: Unknown result type (might be due to invalid IL or missing references)
                //IL_0084: Unknown result type (might be due to invalid IL or missing references)
                //IL_0031: Unknown result type (might be due to invalid IL or missing references)
                //IL_003f: Unknown result type (might be due to invalid IL or missing references)
                //IL_0040: Unknown result type (might be due to invalid IL or missing references)
                //IL_008d: Unknown result type (might be due to invalid IL or missing references)
                _items.Clear();
                if (bIOFailure || (int)pCallback.m_eResult != 1)
                {
                    SteamUGC.ReleaseQueryUGCRequest(m_UGCQueryHandle);
                    return;
                }
                SteamUGCDetails_t val = default(SteamUGCDetails_t);
                for (uint num = 0u; num < pCallback.m_unNumResultsReturned; num++)
                {
                    SteamUGC.GetQueryUGCResult(m_UGCQueryHandle, num, ref val);
                    ulong publishedFileId = val.m_nPublishedFileId.m_PublishedFileId;
                    SteamWorkshopItem steamWorkshopItem = default(SteamWorkshopItem);
                    steamWorkshopItem.Title = ((SteamUGCDetails_t)(ref val)).m_rgchTitle;
                    steamWorkshopItem.Description = ((SteamUGCDetails_t)(ref val)).m_rgchDescription;
                    SteamWorkshopItem value = steamWorkshopItem;
                    _items.Add(publishedFileId, value);
                }
                SteamUGC.ReleaseQueryUGCRequest(m_UGCQueryHandle);
            }
References Terraria.Social.Steam.WorkshopHelper.UGCBased.PublishedItemsFinder._items, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Collections.Generic.Dictionary< TKey, TValue >.Clear(), Terraria.Social.Steam.WorkshopHelper.UGCBased.PublishedItemsFinder.m_UGCQueryHandle, and System.value.
Referenced by Terraria.Social.Steam.WorkshopHelper.UGCBased.PublishedItemsFinder.LoadHooks(), and Terraria.Social.Steam.WorkshopHelper.UGCBased.PublishedItemsFinder.Refresh().