Terraria: Terraria.GameContent.AnOutlinedDrawRenderTargetContent.HandleUseReqest
HandleUseReqest()
override void Terraria.GameContent.AnOutlinedDrawRenderTargetContent.HandleUseReqest (GraphicsDevice device, SpriteBatch spriteBatch) inline protected inherited
Definition at line 24 of file AnOutlinedDrawRenderTargetContent.cs.
    {
        Effect pixelShader = Main.pixelShader;
        if (_coloringShader == null)
        {
            _coloringShader = pixelShader.CurrentTechnique.Passes["ColorOnly"];
        }
        new Rectangle(0, 0, width, height);
        PrepareARenderTarget_AndListenToEvents(ref _target, device, width, height, RenderTargetUsage.PreserveContents);
        PrepareARenderTarget_WithoutListeningToEvents(ref _helperTarget, device, width, height, RenderTargetUsage.DiscardContents);
        device.SetRenderTarget(_helperTarget);
        device.Clear(Color.Transparent);
        spriteBatch.Begin(SpriteSortMode.Immediate, BlendState.AlphaBlend, SamplerState.PointClamp, DepthStencilState.None, RasterizerState.CullCounterClockwise, null);
        DrawTheContent(spriteBatch);
        spriteBatch.End();
        device.SetRenderTarget(_target);
        device.Clear(Color.Transparent);
        spriteBatch.Begin(SpriteSortMode.Immediate, BlendState.AlphaBlend, SamplerState.PointClamp, DepthStencilState.None, RasterizerState.CullCounterClockwise, null);
        _coloringShader.Apply();
        int num = 2;
        int num2 = num * 2;
        for (int i = -num2; i <= num2; i += num)
        {
            for (int j = -num2; j <= num2; j += num)
            {
                if (Math.Abs(i) + Math.Abs(j) == num2)
                {
                    spriteBatch.Draw(_helperTarget, new Vector2(i, j), Color.Black);
                }
            }
        }
        num2 = num;
        for (int k = -num2; k <= num2; k += num)
        {
            for (int l = -num2; l <= num2; l += num)
            {
                if (Math.Abs(k) + Math.Abs(l) == num2)
                {
                    spriteBatch.Draw(_helperTarget, new Vector2(k, l), _borderColor);
                }
            }
        }
        pixelShader.CurrentTechnique.Passes[0].Apply();
        spriteBatch.Draw(_helperTarget, Vector2.Zero, Color.White);
        spriteBatch.End();
        device.SetRenderTarget(null);
        _wasPrepared = true;
    }
References Terraria.GameContent.AnOutlinedDrawRenderTargetContent._borderColor, Terraria.GameContent.AnOutlinedDrawRenderTargetContent._coloringShader, Terraria.GameContent.AnOutlinedDrawRenderTargetContent._helperTarget, Terraria.GameContent.ARenderTargetContentByRequest._target, Terraria.GameContent.ARenderTargetContentByRequest._wasPrepared, System.Math.Abs(), Microsoft.Xna.Framework.Graphics.BlendState.AlphaBlend, Microsoft.Xna.Framework.Graphics.EffectPass.Apply(), Microsoft.Xna.Framework.Graphics.SpriteBatch.Begin(), Microsoft.Xna.Framework.Color.Black, Microsoft.Xna.Framework.Graphics.GraphicsDevice.Clear(), Microsoft.Xna.Framework.Graphics.RasterizerState.CullCounterClockwise, Microsoft.Xna.Framework.Graphics.Effect.CurrentTechnique, Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(), Terraria.GameContent.AnOutlinedDrawRenderTargetContent.DrawTheContent(), Microsoft.Xna.Framework.Graphics.SpriteBatch.End(), Terraria.GameContent.AnOutlinedDrawRenderTargetContent.height, Microsoft.Xna.Framework.Graphics.DepthStencilState.None, Microsoft.Xna.Framework.Graphics.EffectTechnique.Passes, Terraria.Main.pixelShader, Microsoft.Xna.Framework.Graphics.SamplerState.PointClamp, Terraria.GameContent.ARenderTargetContentByRequest.PrepareARenderTarget_AndListenToEvents(), Terraria.GameContent.ARenderTargetContentByRequest.PrepareARenderTarget_WithoutListeningToEvents(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.SetRenderTarget(), Microsoft.Xna.Framework.Color.Transparent, Microsoft.Xna.Framework.Graphics.Vector2, Microsoft.Xna.Framework.Color.White, Terraria.GameContent.AnOutlinedDrawRenderTargetContent.width, and Microsoft.Xna.Framework.Vector2.Zero.