Terraria: System.Data.ConstNode.ConstNode
ConstNode() [2/2]
System.Data.ConstNode.ConstNode (DataTable table, ValueType type, object constant, bool fParseQuotes) inline package
Definition at line 16 of file ConstNode.cs.
        : base(table)
    {
        switch (type)
        {
        case ValueType.Null:
            _val = DBNull.Value;
            break;
        case ValueType.Numeric:
            _val = SmallestNumeric(constant);
            break;
        case ValueType.Decimal:
            _val = SmallestDecimal(constant);
            break;
        case ValueType.Float:
            _val = Convert.ToDouble(constant, NumberFormatInfo.InvariantInfo);
            break;
        case ValueType.Bool:
            _val = Convert.ToBoolean(constant, CultureInfo.InvariantCulture);
            break;
        case ValueType.Str:
            if (fParseQuotes)
            {
                _val = ((string)constant).Replace("''", "'");
            }
            else
            {
                _val = (string)constant;
            }
            break;
        case ValueType.Date:
            _val = DateTime.Parse((string)constant, CultureInfo.InvariantCulture);
            break;
        default:
            _val = constant;
            break;
        }
    }
References System.Data.ConstNode._val, System.Globalization.CultureInfo.InvariantCulture, System.Globalization.NumberFormatInfo.InvariantInfo, System.DateTime.Parse(), System.Data.ConstNode.SmallestDecimal(), System.Data.ConstNode.SmallestNumeric(), System.Convert.ToBoolean(), System.Convert.ToDouble(), System.type, and System.DBNull.Value.