Terraria: System.Diagnostics.DelimitedListTraceListener.WriteFooter
WriteFooter()
void System.Diagnostics.DelimitedListTraceListener.WriteFooter (TraceEventCache eventCache) inline private
Definition at line 174 of file DelimitedListTraceListener.cs.
    {
        if (eventCache != null)
        {
            if (IsEnabled(TraceOptions.ProcessId))
            {
                Write(eventCache.ProcessId.ToString(CultureInfo.InvariantCulture));
            }
            Write(Delimiter);
            if (IsEnabled(TraceOptions.LogicalOperationStack))
            {
                WriteStackEscaped(eventCache.LogicalOperationStack);
            }
            Write(Delimiter);
            if (IsEnabled(TraceOptions.ThreadId))
            {
                WriteEscaped(eventCache.ThreadId);
            }
            Write(Delimiter);
            if (IsEnabled(TraceOptions.DateTime))
            {
                WriteEscaped(eventCache.DateTime.ToString("o", CultureInfo.InvariantCulture));
            }
            Write(Delimiter);
            if (IsEnabled(TraceOptions.Timestamp))
            {
                Write(eventCache.Timestamp.ToString(CultureInfo.InvariantCulture));
            }
            Write(Delimiter);
            if (IsEnabled(TraceOptions.Callstack))
            {
                WriteEscaped(eventCache.Callstack);
            }
        }
        else
        {
            for (int i = 0; i < 5; i++)
            {
                Write(Delimiter);
            }
        }
        WriteLine("");
    }
References System.Diagnostics.TraceEventCache.Callstack, System.Diagnostics.TraceEventCache.DateTime, System.Diagnostics.DelimitedListTraceListener.Delimiter, System.Globalization.CultureInfo.InvariantCulture, System.Diagnostics.TextWriterTraceListener.IsEnabled(), System.Diagnostics.TraceEventCache.LogicalOperationStack, System.Diagnostics.TraceEventCache.ProcessId, System.Diagnostics.TraceEventCache.ThreadId, System.Diagnostics.TraceEventCache.Timestamp, System.DateTime.ToString(), System.IO.Write, System.Diagnostics.DelimitedListTraceListener.WriteEscaped(), System.Diagnostics.TextWriterTraceListener.WriteLine(), and System.Diagnostics.DelimitedListTraceListener.WriteStackEscaped().
Referenced by System.Diagnostics.DelimitedListTraceListener.TraceData(), System.Diagnostics.DelimitedListTraceListener.TraceData(), System.Diagnostics.DelimitedListTraceListener.TraceEvent(), and System.Diagnostics.DelimitedListTraceListener.TraceEvent().