Terraria: System.Runtime.InteropServices.Variant.CopyFromIndirect
CopyFromIndirect()
unsafe void System.Runtime.InteropServices.Variant.CopyFromIndirect (object value) inline
Definition at line 202 of file Variant.cs.
    {
        VarEnum varEnum = VariantType & (VarEnum)(-16385);
        if (value == null)
        {
            if (varEnum == VarEnum.VT_DISPATCH || varEnum == VarEnum.VT_UNKNOWN || varEnum == VarEnum.VT_BSTR)
            {
                *(IntPtr*)(void*)_typeUnion._unionTypes._byref = IntPtr.Zero;
            }
            return;
        }
        if ((varEnum & VarEnum.VT_ARRAY) != 0)
        {
            System.Runtime.CompilerServices.Unsafe.SkipInit(out Variant variant);
            Marshal.GetNativeVariantForObject(value, (IntPtr)(&variant));
            *(IntPtr*)(void*)_typeUnion._unionTypes._byref = variant._typeUnion._unionTypes._byref;
            return;
        }
        switch (varEnum)
        {
        case VarEnum.VT_I1:
            *(sbyte*)(void*)_typeUnion._unionTypes._byref = (sbyte)value;
            break;
        case VarEnum.VT_UI1:
            *(byte*)(void*)_typeUnion._unionTypes._byref = (byte)value;
            break;
        case VarEnum.VT_I2:
            *(short*)(void*)_typeUnion._unionTypes._byref = (short)value;
            break;
        case VarEnum.VT_UI2:
            *(ushort*)(void*)_typeUnion._unionTypes._byref = (ushort)value;
            break;
        case VarEnum.VT_BOOL:
            *(short*)(void*)_typeUnion._unionTypes._byref = (short)(((bool)value) ? (-1) : 0);
            break;
        case VarEnum.VT_I4:
        case VarEnum.VT_INT:
            *(int*)(void*)_typeUnion._unionTypes._byref = (int)value;
            break;
        case VarEnum.VT_UI4:
        case VarEnum.VT_UINT:
            *(uint*)(void*)_typeUnion._unionTypes._byref = (uint)value;
            break;
        case VarEnum.VT_ERROR:
            *(int*)(void*)_typeUnion._unionTypes._byref = ((ErrorWrapper)value).ErrorCode;
            break;
        case VarEnum.VT_I8:
            *(long*)(void*)_typeUnion._unionTypes._byref = (long)value;
            break;
        case VarEnum.VT_UI8:
            *(ulong*)(void*)_typeUnion._unionTypes._byref = (ulong)value;
            break;
        case VarEnum.VT_R4:
            *(float*)(void*)_typeUnion._unionTypes._byref = (float)value;
            break;
        case VarEnum.VT_R8:
            *(double*)(void*)_typeUnion._unionTypes._byref = (double)value;
            break;
        case VarEnum.VT_DATE:
            *(double*)(void*)_typeUnion._unionTypes._byref = ((DateTime)value).ToOADate();
            break;
        case VarEnum.VT_UNKNOWN:
            *(IntPtr*)(void*)_typeUnion._unionTypes._byref = Marshal.GetIUnknownForObject(value);
            break;
        case VarEnum.VT_DISPATCH:
            *(IntPtr*)(void*)_typeUnion._unionTypes._byref = Marshal.GetIDispatchForObject(value);
            break;
        case VarEnum.VT_BSTR:
            *(IntPtr*)(void*)_typeUnion._unionTypes._byref = Marshal.StringToBSTR((string)value);
            break;
        case VarEnum.VT_CY:
            *(long*)(void*)_typeUnion._unionTypes._byref = decimal.ToOACurrency((decimal)value);
            break;
        case VarEnum.VT_DECIMAL:
            *(decimal*)(void*)_typeUnion._unionTypes._byref = (decimal)value;
            break;
        case VarEnum.VT_VARIANT:
            Marshal.GetNativeVariantForObject(value, _typeUnion._unionTypes._byref);
            break;
        default:
            throw new ArgumentException();
        }
    }
References System.Runtime.InteropServices.Variant.UnionTypes._byref, System.Runtime.InteropServices.Variant._typeUnion, System.Runtime.InteropServices.Variant.TypeUnion._unionTypes, System.DateTime, System.Runtime.InteropServices.Marshal.GetIDispatchForObject(), System.Runtime.InteropServices.Marshal.GetIUnknownForObject(), System.Runtime.InteropServices.Marshal.GetNativeVariantForObject(), System.Runtime.InteropServices.Marshal.StringToBSTR(), System.value, System.Runtime.InteropServices.Variant.VariantType, and System.IntPtr.Zero.