Terraria: System.Collections.Immutable.ImmutableSortedSet.Builder.ToImmutable
ToImmutable()
ImmutableSortedSet< T > System.Collections.Immutable.ImmutableSortedSet< T >.Builder.ToImmutable () inline
Definition at line 305 of file ImmutableSortedSet.cs.
        {
            if (_immutable == null)
            {
                _immutable = ImmutableSortedSet<T>.Wrap(Root, _comparer);
            }
            return _immutable;
        }
References System.Collections.Immutable.ImmutableSortedSet< T >.Builder._comparer, System.Collections.Immutable.ImmutableSortedSet< T >.Builder._immutable, and System.Collections.Immutable.ImmutableSortedSet< T >.Builder.Root.
Referenced by System.Collections.Immutable.ImmutableSortedSet< T >.Builder.IsProperSubsetOf(), System.Collections.Immutable.ImmutableSortedSet< T >.Builder.IsProperSupersetOf(), System.Collections.Immutable.ImmutableSortedSet< T >.Builder.IsSubsetOf(), System.Collections.Immutable.ImmutableSortedSet< T >.Builder.IsSupersetOf(), System.Collections.Immutable.ImmutableSortedSet< T >.Builder.Overlaps(), System.Collections.Immutable.ImmutableSortedSet< T >.Builder.SetEquals(), and System.Collections.Immutable.ImmutableSortedSet< T >.Builder.SymmetricExceptWith().