Terraria: System.Xml.XmlComplianceUtil.CDataNormalize
CDataNormalize()
static string System.Xml.XmlComplianceUtil.CDataNormalize (string value) inline static
Definition at line 76 of file XmlComplianceUtil.cs.
    {
        int length = value.Length;
        if (length <= 0)
        {
            return string.Empty;
        }
        int num = 0;
        int num2 = 0;
        StringBuilder stringBuilder = null;
        while (num < length)
        {
            char c = value[num];
            switch (c)
            {
            default:
                num++;
                break;
            case '\t':
            case '\n':
            case '\r':
                if (stringBuilder == null)
                {
                    stringBuilder = new StringBuilder(length);
                }
                if (num2 < num)
                {
                    stringBuilder.Append(value, num2, num - num2);
                }
                stringBuilder.Append(' ');
                num = ((c != '\r' || num + 1 >= length || value[num + 1] != '\n') ? (num + 1) : (num + 2));
                num2 = num;
                break;
            }
        }
        if (stringBuilder == null)
        {
            return value;
        }
        if (num > num2)
        {
            stringBuilder.Append(value, num2, num - num2);
        }
        return stringBuilder.ToString();
    }
References System.Xml.Dictionary, System.length, and System.value.
Referenced by System.Xml.Schema.XmlSchemaSet.Add(), System.Xml.Schema.XmlSchemaSet.Add(), and System.Xml.Schema.FacetsChecker.CheckWhitespaceFacets().