Terraria: System.Xml.XmlComplianceUtil.NonCDataNormalize
NonCDataNormalize()
static string System.Xml.XmlComplianceUtil.NonCDataNormalize (string value) inline static
Definition at line 7 of file XmlComplianceUtil.cs.
    {
        int length = value.Length;
        if (length <= 0)
        {
            return string.Empty;
        }
        int num = 0;
        StringBuilder stringBuilder = null;
        while (XmlCharType.IsWhiteSpace(value[num]))
        {
            num++;
            if (num == length)
            {
                return " ";
            }
        }
        int num2 = num;
        while (num2 < length)
        {
            if (!XmlCharType.IsWhiteSpace(value[num2]))
            {
                num2++;
                continue;
            }
            int i;
            for (i = num2 + 1; i < length && XmlCharType.IsWhiteSpace(value[i]); i++)
            {
            }
            if (i == length)
            {
                if (stringBuilder == null)
                {
                    return value.Substring(num, num2 - num);
                }
                stringBuilder.Append(value, num, num2 - num);
                return stringBuilder.ToString();
            }
            if (i > num2 + 1 || value[num2] != ' ')
            {
                if (stringBuilder == null)
                {
                    stringBuilder = new StringBuilder(length);
                }
                stringBuilder.Append(value, num, num2 - num);
                stringBuilder.Append(' ');
                num = i;
                num2 = i;
            }
            else
            {
                num2++;
            }
        }
        if (stringBuilder != null)
        {
            if (num < num2)
            {
                stringBuilder.Append(value, num, num2 - num);
            }
            return stringBuilder.ToString();
        }
        if (num > 0)
        {
            return value.Substring(num, length - num);
        }
        return value;
    }
References System.Xml.Dictionary, System.Xml.XmlCharType.IsWhiteSpace(), System.length, and System.value.
Referenced by System.Xml.Schema.FacetsChecker.CheckWhitespaceFacets(), System.Xml.Schema.XsdBuilder.ParseQName(), System.Xml.Schema.Datatype_anySimpleType.TryParseValue(), System.Xml.Schema.Preprocessor.ValidateNameAttribute(), and System.Xml.Schema.SchemaCollectionPreprocessor.ValidateNameAttribute().