Terraria: System.IO.PathHelper.TryExpandShortFileName
TryExpandShortFileName()
static string System.IO.PathHelper.TryExpandShortFileName (ref ValueStringBuilder outputBuilder, string originalPath) inline static package
Definition at line 64 of file PathHelper.cs.
    {
        int rootLength = PathInternal.GetRootLength(outputBuilder.AsSpan());
        bool flag = PathInternal.IsDevice(outputBuilder.AsSpan());
        ValueStringBuilder buffer = default(ValueStringBuilder);
        bool flag2 = false;
        int num = 0;
        bool flag3 = false;
        if (flag)
        {
            buffer.Append(outputBuilder.AsSpan());
            if (outputBuilder[2] == '.')
            {
                flag3 = true;
                buffer[2] = '?';
            }
        }
        else
        {
            flag2 = !PathInternal.IsDevice(outputBuilder.AsSpan()) && outputBuilder.Length > 1 && outputBuilder[0] == '\\' && outputBuilder[1] == '\\';
            num = PrependDevicePathChars(ref outputBuilder, flag2, ref buffer);
        }
        rootLength += num;
        int length = buffer.Length;
        bool flag4 = false;
        int num2 = buffer.Length - 1;
        while (!flag4)
        {
            uint longPathNameW = Interop.Kernel32.GetLongPathNameW(ref buffer.GetPinnableReference(terminate: true), ref outputBuilder.GetPinnableReference(), (uint)outputBuilder.Capacity);
            if (buffer[num2] == '\0')
            {
                buffer[num2] = '\\';
            }
            if (longPathNameW == 0)
            {
                int lastWin32Error = Marshal.GetLastWin32Error();
                if (lastWin32Error != 2 && lastWin32Error != 3)
                {
                    break;
                }
                num2--;
                while (num2 > rootLength && buffer[num2] != '\\')
                {
                    num2--;
                }
                if (num2 == rootLength)
                {
                    break;
                }
                buffer[num2] = '\0';
            }
            else if (longPathNameW > outputBuilder.Capacity)
            {
                outputBuilder.EnsureCapacity(checked((int)longPathNameW));
            }
            else
            {
                flag4 = true;
                outputBuilder.Length = checked((int)longPathNameW);
                if (num2 < length - 1)
                {
                    outputBuilder.Append(buffer.AsSpan(num2, buffer.Length - num2));
                }
            }
        }
        ref ValueStringBuilder reference = ref flag4 ? ref outputBuilder : ref buffer;
        if (flag3)
        {
            reference[2] = '.';
        }
        if (flag2)
        {
            reference[6] = '\\';
        }
        ReadOnlySpan<char> span = reference.AsSpan(num);
        string result = ((originalPath != null && MemoryExtensions.Equals(span, originalPath.AsSpan(), StringComparison.Ordinal)) ? originalPath : span.ToString());
        buffer.Dispose();
        return result;
    }
References System.Text.ValueStringBuilder.Append(), System.buffer, System.MemoryExtensions.Equals(), System.Runtime.InteropServices.Marshal.GetLastWin32Error(), Interop.Kernel32.GetLongPathNameW(), System.IO.PathInternal.GetRootLength(), System.IO.PathInternal.IsDevice(), System.length, System.IO.PathHelper.PrependDevicePathChars(), and System.ReadOnlySpan< T >.ToString().
Referenced by System.IO.PathHelper.Normalize(), and System.IO.PathHelper.Normalize().