Terraria: System.Net.Http.Headers.HttpResponseHeaders.AddHeaders
AddHeaders()
override void System.Net.Http.Headers.HttpResponseHeaders.AddHeaders (HttpHeaders sourceHeaders) inline package virtual
Reimplemented from System.Net.Http.Headers.HttpHeaders.
Definition at line 150 of file HttpResponseHeaders.cs.
    {
        base.AddHeaders(sourceHeaders);
        HttpResponseHeaders httpResponseHeaders = sourceHeaders as HttpResponseHeaders;
        if (httpResponseHeaders._generalHeaders != null)
        {
            GeneralHeaders.AddSpecialsFrom(httpResponseHeaders._generalHeaders);
        }
    }
References System.Net.Http.Headers.HttpResponseHeaders.HttpResponseHeaders(), System.Net.Http.Headers.HttpResponseHeaders._generalHeaders, System.Net.Http.Headers.HttpGeneralHeaders.AddSpecialsFrom(), and System.Net.Http.Headers.HttpResponseHeaders.GeneralHeaders.
Referenced by System.Net.Http.HttpResponseMessage.StoreReceivedTrailingHeaders().