Terraria: System.Xml.XmlAttributeCollection.InsertNodeAt
InsertNodeAt()
override XmlNode System.Xml.XmlAttributeCollection.InsertNodeAt (int i, XmlNode node) inline package virtual
Reimplemented from System.Xml.XmlNamedNodeMap.
Definition at line 273 of file XmlAttributeCollection.cs.
    {
        XmlNode result = base.InsertNodeAt(i, node);
        InsertParentIntoElementIdAttrMap((XmlAttribute)node);
        return result;
    }
References System.Xml.Dictionary, and System.Xml.XmlAttributeCollection.InsertParentIntoElementIdAttrMap().
Referenced by System.Xml.XmlAttributeCollection.InsertAfter(), System.Xml.XmlAttributeCollection.InsertBefore(), System.Xml.XmlAttributeCollection.Prepend(), System.Xml.XmlAttributeCollection.RemoveNodeAt(), and System.Xml.XmlAttributeCollection.SetNamedItem().