Terraria: Terraria.WorldBuilding.TileFont.HLineLabel
HLineLabel()
static void Terraria.WorldBuilding.TileFont.HLineLabel (Point start, int width, string text, DrawMode mode, bool rightSideText = false) inline static
Definition at line 360 of file TileFont.cs.
    {
        Point point = MeasureString(text);
        for (int i = start.X; i < start.X + width; i++)
        {
            Main.tile[i, start.Y].ResetToType(mode.ForegroundTile);
            WorldGen.TileFrame(i, start.Y);
        }
        DrawString(new Point(rightSideText ? (start.X + width + 1) : (start.X - point.X - 1), start.Y - point.Y / 2), text, mode);
    }
References Terraria.WorldBuilding.TileFont.DrawString(), Terraria.WorldBuilding.TileFont.DrawMode.ForegroundTile, Terraria.WorldBuilding.TileFont.MeasureString(), System.start, System.text, Terraria.Main.tile, Terraria.WorldGen.TileFrame(), and Microsoft.Xna.Framework.Point.Y.