Terraria: Terraria.WorldBuilding.TileFont.DrawString
DrawString()
static void Terraria.WorldBuilding.TileFont.DrawString (Point start, string text, DrawMode mode) inline static
Definition at line 292 of file TileFont.cs.
    {
        Point position = start;
        foreach (char c in text)
        {
            if (c == '\n')
            {
                position.X = start.X;
                position.Y += 6;
            }
            if (MicroFont.TryGetValue(c, out var value))
            {
                DrawChar(position, value, mode);
                position.X += 6;
            }
        }
    }
References Terraria.WorldBuilding.TileFont.DrawChar(), Terraria.WorldBuilding.TileFont.MicroFont, System.start, System.text, System.value, and Microsoft.Xna.Framework.Point.X.
Referenced by Terraria.WorldBuilding.TileFont.HLineLabel(), and Terraria.WorldBuilding.TileFont.VLineLabel().