Terraria: System.Xml.XmlAttributeCollection.InsertBefore
InsertBefore()
XmlAttribute System.Xml.XmlAttributeCollection.InsertBefore (XmlAttribute newNode, XmlAttribute? refNode) inline
Definition at line 144 of file XmlAttributeCollection.cs.
    {
        if (newNode == refNode)
        {
            return newNode;
        }
        if (refNode == null)
        {
            return Append(newNode);
        }
        if (refNode.OwnerElement != parent)
        {
            throw new ArgumentException(System.SR.Xdom_AttrCol_Insert);
        }
        if (newNode.OwnerDocument != null && newNode.OwnerDocument != parent.OwnerDocument)
        {
            throw new ArgumentException(System.SR.Xdom_NamedNode_Context);
        }
        if (newNode.OwnerElement != null)
        {
            Detach(newNode);
        }
        int num = FindNodeOffset(refNode.LocalName, refNode.NamespaceURI);
        int num2 = RemoveDuplicateAttribute(newNode);
        if (num2 >= 0 && num2 < num)
        {
            num--;
        }
        InsertNodeAt(num, newNode);
        return newNode;
    }
References System.Xml.XmlAttributeCollection.Append(), System.Xml.ArgumentException, System.Xml.XmlAttributeCollection.Detach(), System.Xml.Dictionary, System.Xml.XmlNamedNodeMap.FindNodeOffset(), System.Xml.XmlAttributeCollection.InsertNodeAt(), System.Xml.XmlNode.OwnerDocument, System.Xml.XmlNamedNodeMap.parent, System.Xml.XmlAttributeCollection.RemoveDuplicateAttribute(), System.SR.Xdom_AttrCol_Insert, and System.SR.Xdom_NamedNode_Context.