Terraria: System.Xml.Xsl.Runtime.XPathPrecedingMergeIterator.PushAncestors
PushAncestors()
void System.Xml.Xsl.Runtime.XPathPrecedingMergeIterator.PushAncestors () inline private
Definition at line 87 of file XPathPrecedingMergeIterator.cs.
    {
        _navStack.Reset();
        do
        {
            _navStack.Push(_navCurrent.Clone());
        }
        while (_navCurrent.MoveToParent());
        _navStack.Pop();
    }
References System.Xml.Xsl.Runtime.XPathPrecedingMergeIterator._navCurrent, System.Xml.Xsl.Runtime.XPathPrecedingMergeIterator._navStack, System.Xml.XPath.XPathNavigator.Clone(), System.Xml.XPath.XPathNavigator.MoveToParent(), System.Xml.Xsl.Runtime.XmlNavigatorStack.Pop(), System.Xml.Xsl.Runtime.XmlNavigatorStack.Push(), and System.Xml.Xsl.Runtime.XmlNavigatorStack.Reset().
Referenced by System.Xml.Xsl.Runtime.XPathPrecedingMergeIterator.MoveNext().