Terraria: System.Xml.Xsl.Runtime.XPathPrecedingMergeIterator.MoveNext
MoveNext()
IteratorResult System.Xml.Xsl.Runtime.XPathPrecedingMergeIterator.MoveNext (XPathNavigator input) inline
Definition at line 35 of file XPathPrecedingMergeIterator.cs.
    {
        switch (_state)
        {
        case IteratorState.NeedCandidateCurrent:
            if (input == null)
            {
                return IteratorResult.NoMoreNodes;
            }
            _navCurrent = XmlQueryRuntime.SyncToNavigator(_navCurrent, input);
            _state = IteratorState.HaveCandidateCurrent;
            return IteratorResult.NeedInputNode;
        case IteratorState.HaveCandidateCurrent:
            if (input == null)
            {
                _state = IteratorState.HaveCurrentNoNext;
            }
            else
            {
                if (_navCurrent.ComparePosition(input) != XmlNodeOrder.Unknown)
                {
                    _navCurrent = XmlQueryRuntime.SyncToNavigator(_navCurrent, input);
                    return IteratorResult.NeedInputNode;
                }
                _navNext = XmlQueryRuntime.SyncToNavigator(_navNext, input);
                _state = IteratorState.HaveCurrentHaveNext;
            }
            PushAncestors();
            break;
        }
        if (!_navStack.IsEmpty)
        {
            do
            {
                if (_filter.MoveToFollowing(_navCurrent, _navStack.Peek()))
                {
                    return IteratorResult.HaveCurrentNode;
                }
                _navCurrent.MoveTo(_navStack.Pop());
            }
            while (!_navStack.IsEmpty);
        }
        if (_state == IteratorState.HaveCurrentNoNext)
        {
            _state = IteratorState.NeedCandidateCurrent;
            return IteratorResult.NoMoreNodes;
        }
        _navCurrent = XmlQueryRuntime.SyncToNavigator(_navCurrent, _navNext);
        _state = IteratorState.HaveCandidateCurrent;
        return IteratorResult.HaveCurrentNode;
    }
References System.Xml.Xsl.Runtime.XPathPrecedingMergeIterator._filter, System.Xml.Xsl.Runtime.XPathPrecedingMergeIterator._navCurrent, System.Xml.Xsl.Runtime.XPathPrecedingMergeIterator._navNext, System.Xml.Xsl.Runtime.XPathPrecedingMergeIterator._navStack, System.Xml.Xsl.Runtime.XPathPrecedingMergeIterator._state, System.Xml.XPath.XPathNavigator.ComparePosition(), System.input, System.Xml.Xsl.Runtime.XmlNavigatorStack.IsEmpty, System.Xml.XPath.XPathNavigator.MoveTo(), System.Xml.Xsl.Runtime.XmlNavigatorFilter.MoveToFollowing(), System.Xml.Xsl.Runtime.XmlNavigatorStack.Peek(), System.Xml.Xsl.Runtime.XmlNavigatorStack.Pop(), System.Xml.Xsl.Runtime.XPathPrecedingMergeIterator.PushAncestors(), and System.Xml.Xsl.Runtime.XmlQueryRuntime.SyncToNavigator().