Terraria: System.Reflection.Metadata.MethodImplementationHandle.MethodImplementationHandle
MethodImplementationHandle()
System.Reflection.Metadata.MethodImplementationHandle.MethodImplementationHandle (int rowId) inline private
Definition at line 11 of file MethodImplementationHandle.cs.
    {
        _rowId = rowId;
    }
References System.Reflection.Metadata.MethodImplementationHandle._rowId.
Referenced by System.Reflection.Metadata.MethodImplementationHandle.FromRowId(), System.Reflection.Metadata.MethodImplementationHandle.operator MethodImplementationHandle(), and System.Reflection.Metadata.MethodImplementationHandle.operator MethodImplementationHandle().