Terraria: System.Xml.XmlBaseWriter.StartContent
StartContent() [1/4]
void System.Xml.XmlBaseWriter.StartContent () inline protected inherited
Definition at line 1453 of file XmlBaseWriter.cs.
    {
        FlushElement();
        if (_depth == 0)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new InvalidOperationException(System.SR.XmlIllegalOutsideRoot));
        }
    }
References System.Xml.XmlBaseWriter.NamespaceManager._depth, System.Xml.XmlBaseWriter.FlushElement(), System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperError(), and System.SR.XmlIllegalOutsideRoot.
Referenced by System.Xml.XmlBaseWriter.FlushTrailBytes(), System.Xml.XmlBaseWriter.WriteBase64(), System.Xml.XmlBaseWriter.WriteCData(), System.Xml.XmlBaseWriter.WriteCharEntity(), System.Xml.XmlBaseWriter.WriteChars(), System.Xml.XmlBaseWriter.WriteQualifiedName(), System.Xml.XmlBaseWriter.WriteRaw(), System.Xml.XmlBaseWriter.WriteRaw(), System.Xml.XmlBaseWriter.WriteString(), System.Xml.XmlBaseWriter.WriteString(), System.Xml.XmlBaseWriter.WriteSurrogateCharEntity(), System.Xml.XmlBaseWriter.WriteValue(), System.Xml.XmlBaseWriter.WriteValue(), System.Xml.XmlBaseWriter.WriteValue(), System.Xml.XmlBaseWriter.WriteValue(), System.Xml.XmlBaseWriter.WriteValue(), System.Xml.XmlBaseWriter.WriteValue(), System.Xml.XmlBaseWriter.WriteValue(), System.Xml.XmlBaseWriter.WriteValue(), System.Xml.XmlBaseWriter.WriteValue(), System.Xml.XmlBaseWriter.WriteValue(), System.Xml.XmlBaseWriter.WriteValue(), System.Xml.XmlBaseWriter.WriteValue(), and System.Xml.XmlBaseWriter.WriteValue().