Terraria: System.Xml.XmlBaseWriter.WriteXmlnsAttribute
WriteXmlnsAttribute() [1/4]
override void System.Xml.XmlBaseWriter.WriteXmlnsAttribute (string prefix, string ns) inline inherited
Definition at line 826 of file XmlBaseWriter.cs.
    {
        if (IsClosed)
        {
            ThrowClosed();
        }
        if (ns == null)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperArgumentNull("ns");
        }
        if (_writeState != WriteState.Element)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new InvalidOperationException(System.SR.Format(System.SR.XmlInvalidWriteState, "WriteXmlnsAttribute", WriteState.ToString())));
        }
        if (prefix == null)
        {
            prefix = _nsMgr.LookupPrefix(ns);
            if (prefix == null)
            {
                GeneratePrefix(ns, null);
            }
        }
        else
        {
            _nsMgr.AddNamespaceIfNotDeclared(prefix, ns, null);
        }
    }
References System.Xml.XmlBaseWriter._nsMgr, System.Xml.XmlBaseWriter._writeState, System.Xml.XmlBaseWriter.NamespaceManager.AddNamespaceIfNotDeclared(), System.SR.Format(), System.Xml.XmlBaseWriter.GeneratePrefix(), System.Xml.XmlBaseWriter.IsClosed, System.Xml.XmlBaseWriter.NamespaceManager.LookupPrefix(), System.prefix, System.Xml.XmlBaseWriter.ThrowClosed(), System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperArgumentNull(), System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperError(), and System.SR.XmlInvalidWriteState.