Terraria: System.Xml.XmlBaseWriter.StartElement
StartElement()
void System.Xml.XmlBaseWriter.StartElement (ref string prefix, string localName, string ns, XmlDictionaryString xNs) inline private inherited
Definition at line 1193 of file XmlBaseWriter.cs.
    {
        if (IsClosed)
        {
            ThrowClosed();
        }
        if (_documentState == DocumentState.Epilog)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new InvalidOperationException(System.SR.XmlOnlyOneRoot));
        }
        if (localName == null)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new ArgumentNullException("localName"));
        }
        if (localName.Length == 0)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new ArgumentException(System.SR.InvalidLocalNameEmpty, "localName"));
        }
        if (_writeState == WriteState.Attribute)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new InvalidOperationException(System.SR.Format(System.SR.XmlInvalidWriteState, "WriteStartElement", WriteState.ToString())));
        }
        FlushBase64();
        AutoComplete(WriteState.Element);
        Element element = EnterScope();
        if (ns == null)
        {
            if (prefix == null)
            {
                prefix = string.Empty;
            }
            ns = _nsMgr.LookupNamespace(prefix);
            if (ns == null)
            {
                throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new ArgumentException(System.SR.Format(System.SR.XmlUndefinedPrefix, prefix), "prefix"));
            }
        }
        else if (prefix == null)
        {
            prefix = _nsMgr.LookupPrefix(ns);
            if (prefix == null)
            {
                prefix = string.Empty;
                _nsMgr.AddNamespace(string.Empty, ns, xNs);
            }
        }
        else
        {
            _nsMgr.AddNamespaceIfNotDeclared(prefix, ns, xNs);
        }
        element.Prefix = prefix;
        element.LocalName = localName;
    }
References System.Xml.XmlBaseWriter._documentState, System.Xml.XmlBaseWriter._nsMgr, System.Xml.XmlBaseWriter._writeState, System.Xml.XmlBaseWriter.NamespaceManager.AddNamespace(), System.Xml.XmlBaseWriter.NamespaceManager.AddNamespaceIfNotDeclared(), System.Xml.ArgumentException, System.Xml.XmlBaseWriter.AutoComplete(), System.Xml.Dictionary, System.Xml.XmlBaseWriter.NamespaceManager.EnterScope(), System.Xml.XmlBaseWriter.FlushBase64(), System.SR.Format(), System.SR.InvalidLocalNameEmpty, System.Xml.XmlBaseWriter.IsClosed, System.Xml.XmlBaseWriter.NamespaceManager.LookupNamespace(), System.Xml.XmlBaseWriter.NamespaceManager.LookupPrefix(), System.prefix, System.Xml.XmlBaseWriter.ThrowClosed(), System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperError(), System.SR.XmlInvalidWriteState, System.SR.XmlOnlyOneRoot, and System.SR.XmlUndefinedPrefix.
Referenced by System.Xml.XmlBaseWriter.WriteStartElement(), and System.Xml.XmlBaseWriter.WriteStartElement().