Terraria: System.Xml.XmlBaseWriter.StartContentAsync
StartContentAsync()
async Task System.Xml.XmlBaseWriter.StartContentAsync () inline protected inherited
Definition at line 1462 of file XmlBaseWriter.cs.
    {
        await FlushElementAsync().ConfigureAwait(continueOnCapturedContext: false);
        if (_depth == 0)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new InvalidOperationException(System.SR.XmlIllegalOutsideRoot));
        }
    }
References System.Xml.XmlBaseWriter.NamespaceManager._depth, System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.Xml.Dictionary, System.Xml.XmlBaseWriter.FlushElementAsync(), System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperError(), and System.SR.XmlIllegalOutsideRoot.
Referenced by System.Xml.XmlBaseWriter.FlushTrailBytesAsync(), and System.Xml.XmlBaseWriter.WriteBase64AsyncImpl().