Terraria: System.Xml.XmlBaseWriter.StartElementAsync
StartElementAsync()
async Task< string > System.Xml.XmlBaseWriter.StartElementAsync (string prefix, string localName, string ns, XmlDictionaryString xNs) inline private inherited
Definition at line 1277 of file XmlBaseWriter.cs.
    {
        await FlushBase64Async().ConfigureAwait(continueOnCapturedContext: false);
        await AutoCompleteAsync(WriteState.Element).ConfigureAwait(continueOnCapturedContext: false);
        Element element = EnterScope();
        if (ns == null)
        {
            if (prefix == null)
            {
                prefix = string.Empty;
            }
            ns = _nsMgr.LookupNamespace(prefix);
            if (ns == null)
            {
                throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new ArgumentException(System.SR.Format(System.SR.XmlUndefinedPrefix, prefix), "prefix"));
            }
        }
        else if (prefix == null)
        {
            prefix = _nsMgr.LookupPrefix(ns);
            if (prefix == null)
            {
                prefix = string.Empty;
                _nsMgr.AddNamespace(string.Empty, ns, xNs);
            }
        }
        else
        {
            _nsMgr.AddNamespaceIfNotDeclared(prefix, ns, xNs);
        }
        element.Prefix = prefix;
        element.LocalName = localName;
        return prefix;
    }
References System.Xml.XmlBaseWriter._nsMgr, System.Xml.XmlBaseWriter.NamespaceManager.AddNamespace(), System.Xml.XmlBaseWriter.NamespaceManager.AddNamespaceIfNotDeclared(), System.Xml.ArgumentException, System.Xml.XmlBaseWriter.AutoCompleteAsync(), System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.Xml.Dictionary, System.Xml.XmlBaseWriter.NamespaceManager.EnterScope(), System.Xml.XmlBaseWriter.FlushBase64Async(), System.SR.Format(), System.Xml.XmlBaseWriter.NamespaceManager.LookupNamespace(), System.Xml.XmlBaseWriter.NamespaceManager.LookupPrefix(), System.prefix, System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperError(), and System.SR.XmlUndefinedPrefix.
Referenced by System.Xml.XmlBaseWriter.StartElementAndWriteStartElementAsync().