Terraria: System.Xml.XmlBaseWriter.WriteEndElementAsync
WriteEndElementAsync()
override Task System.Xml.XmlBaseWriter.WriteEndElementAsync () inline virtual inherited
Reimplemented from System.Xml.XmlWriter.
Definition at line 1359 of file XmlBaseWriter.cs.
    {
        if (IsClosed)
        {
            ThrowClosed();
        }
        if (_depth == 0)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new InvalidOperationException(System.SR.Format(System.SR.XmlInvalidDepth, "WriteEndElement", _depth.ToString(CultureInfo.InvariantCulture))));
        }
        return WriteEndElementAsyncImpl();
    }
References System.Xml.XmlBaseWriter.NamespaceManager._depth, System.SR.Format(), System.Globalization.CultureInfo.InvariantCulture, System.Xml.XmlBaseWriter.IsClosed, System.Xml.XmlBaseWriter.ThrowClosed(), System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperError(), System.Xml.XmlBaseWriter.WriteEndElementAsyncImpl(), and System.SR.XmlInvalidDepth.