Terraria: System.Xml.XmlBaseWriter.GeneratePrefix
GeneratePrefix()
string System.Xml.XmlBaseWriter.GeneratePrefix (string ns, XmlDictionaryString xNs) inline private inherited
Definition at line 2592 of file XmlBaseWriter.cs.
    {
        if (_writeState != WriteState.Element && _writeState != WriteState.Attribute)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new InvalidOperationException(System.SR.Format(System.SR.XmlInvalidPrefixState, WriteState.ToString())));
        }
        string text = _nsMgr.AddNamespace(ns, xNs);
        if (text != null)
        {
            return text;
        }
        do
        {
            int value = _elements[_depth].PrefixId++;
            IFormatProvider invariantCulture = CultureInfo.InvariantCulture;
            DefaultInterpolatedStringHandler handler = new DefaultInterpolatedStringHandler(2, 2, invariantCulture);
            handler.AppendLiteral("d");
            handler.AppendFormatted(_depth);
            handler.AppendLiteral("p");
            handler.AppendFormatted(value);
            text = string.Create(invariantCulture, ref handler);
        }
        while (_nsMgr.LookupNamespace(text) != null);
        _nsMgr.AddNamespace(text, ns, xNs);
        return text;
    }
References System.Xml.XmlBaseWriter.NamespaceManager._depth, System.Xml.XmlBaseWriter._elements, System.Xml.XmlBaseWriter._nsMgr, System.Xml.XmlBaseWriter._writeState, System.Xml.XmlBaseWriter.NamespaceManager.AddNamespace(), System.Runtime.CompilerServices.DefaultInterpolatedStringHandler.AppendFormatted(), System.Runtime.CompilerServices.DefaultInterpolatedStringHandler.AppendLiteral(), System.Xml.Dictionary, System.SR.Format(), System.Globalization.CultureInfo.InvariantCulture, System.Xml.XmlBaseWriter.NamespaceManager.LookupNamespace(), System.Xml.XmlBaseWriter.Element.PrefixId, System.text, System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperError(), System.value, and System.SR.XmlInvalidPrefixState.
Referenced by System.Xml.XmlBaseWriter.GetQualifiedNamePrefix(), System.Xml.XmlBaseWriter.StartAttribute(), System.Xml.XmlBaseWriter.WriteXmlnsAttribute(), and System.Xml.XmlBaseWriter.WriteXmlnsAttribute().