Terraria: System.Xml.XmlBaseWriter.FlushBase64
FlushBase64()
void System.Xml.XmlBaseWriter.FlushBase64 () inline private inherited
Definition at line 2485 of file XmlBaseWriter.cs.
    {
        if (_trailByteCount > 0)
        {
            FlushTrailBytes();
        }
    }
References System.Xml.XmlBaseWriter._trailByteCount, and System.Xml.XmlBaseWriter.FlushTrailBytes().
Referenced by System.Xml.XmlBaseWriter.StartArray(), System.Xml.XmlBaseWriter.StartElement(), System.Xml.XmlBaseWriter.WriteCData(), System.Xml.XmlBaseWriter.WriteCharEntity(), System.Xml.XmlBaseWriter.WriteChars(), System.Xml.XmlBaseWriter.WriteComment(), System.Xml.XmlBaseWriter.WriteEndAttribute(), System.Xml.XmlBaseWriter.WriteEndElement(), System.Xml.XmlBaseWriter.WriteEndElementAsyncImpl(), System.Xml.XmlBaseWriter.WriteQualifiedName(), System.Xml.XmlBaseWriter.WriteRaw(), System.Xml.XmlBaseWriter.WriteRaw(), System.Xml.XmlBaseWriter.WriteString(), System.Xml.XmlBaseWriter.WriteString(), System.Xml.XmlBaseWriter.WriteSurrogateCharEntity(), System.Xml.XmlBaseWriter.WriteValue(), System.Xml.XmlBaseWriter.WriteValue(), System.Xml.XmlBaseWriter.WriteValue(), System.Xml.XmlBaseWriter.WriteValue(), System.Xml.XmlBaseWriter.WriteValue(), System.Xml.XmlBaseWriter.WriteValue(), System.Xml.XmlBaseWriter.WriteValue(), System.Xml.XmlBaseWriter.WriteValue(), System.Xml.XmlBaseWriter.WriteValue(), System.Xml.XmlBaseWriter.WriteValue(), System.Xml.XmlBaseWriter.WriteValue(), System.Xml.XmlBaseWriter.WriteValue(), and System.Xml.XmlBaseWriter.WriteValue().