Terraria: System.Xml.XmlBaseWriter.WriteSurrogateCharEntity
WriteSurrogateCharEntity()
override void System.Xml.XmlBaseWriter.WriteSurrogateCharEntity (char lowChar, char highChar) inline inherited
Definition at line 1941 of file XmlBaseWriter.cs.
    {
        if (IsClosed)
        {
            ThrowClosed();
        }
        SurrogateChar surrogateChar = new SurrogateChar(lowChar, highChar);
        if (_attributeValue != null)
        {
            Span<char> span = stackalloc char[2] { highChar, lowChar };
            WriteAttributeText(new string(span));
        }
        if (!_isXmlnsAttribute)
        {
            StartContent();
            FlushBase64();
            _writer.WriteCharEntity(surrogateChar.Char);
            EndContent();
        }
    }
References System.Xml.XmlBaseWriter._attributeValue, System.Xml.XmlBaseWriter._isXmlnsAttribute, System.Xml.XmlBaseWriter._writer, System.Xml.Dictionary, System.Xml.XmlBaseWriter.EndContent(), System.Xml.XmlBaseWriter.FlushBase64(), System.Xml.XmlBaseWriter.IsClosed, System.Xml.XmlBaseWriter.StartContent(), System.Xml.XmlBaseWriter.ThrowClosed(), System.Xml.XmlBaseWriter.WriteAttributeText(), and System.Xml.XmlNodeWriter.WriteCharEntity().