Terraria: System.Xml.XmlBaseWriter.StartAttribute
StartAttribute()
void System.Xml.XmlBaseWriter.StartAttribute ([AllowNull] ref string prefix, string localName, string ns, XmlDictionaryString xNs) inline private inherited
Definition at line 882 of file XmlBaseWriter.cs.
    {
        if (IsClosed)
        {
            ThrowClosed();
        }
        if (_writeState == WriteState.Attribute)
        {
            WriteEndAttribute();
        }
        if (localName == null || (localName.Length == 0 && prefix != "xmlns"))
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new ArgumentNullException("localName"));
        }
        if (_writeState != WriteState.Element)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new InvalidOperationException(System.SR.Format(System.SR.XmlInvalidWriteState, "WriteStartAttribute", WriteState.ToString())));
        }
        if (prefix == null)
        {
            if (ns == "http://www.w3.org/2000/xmlns/" && localName != "xmlns")
            {
                prefix = "xmlns";
            }
            else if (ns == "http://www.w3.org/XML/1998/namespace")
            {
                prefix = "xml";
            }
            else
            {
                prefix = string.Empty;
            }
        }
        if (prefix.Length == 0 && localName == "xmlns")
        {
            prefix = "xmlns";
            localName = string.Empty;
        }
        _isXmlnsAttribute = false;
        _isXmlAttribute = false;
        if (prefix == "xml")
        {
            if (ns != null && ns != "http://www.w3.org/XML/1998/namespace")
            {
                throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new ArgumentException(System.SR.Format(System.SR.XmlPrefixBoundToNamespace, "xml", "http://www.w3.org/XML/1998/namespace", ns), "ns"));
            }
            _isXmlAttribute = true;
            _attributeValue = string.Empty;
            _attributeLocalName = localName;
        }
        else if (prefix == "xmlns")
        {
            if (ns != null && ns != "http://www.w3.org/2000/xmlns/")
            {
                throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new ArgumentException(System.SR.Format(System.SR.XmlPrefixBoundToNamespace, "xmlns", "http://www.w3.org/2000/xmlns/", ns), "ns"));
            }
            _isXmlnsAttribute = true;
            _attributeValue = string.Empty;
            _attributeLocalName = localName;
        }
        else if (ns == null)
        {
            if (prefix.Length == 0)
            {
                ns = string.Empty;
            }
            else
            {
                ns = _nsMgr.LookupNamespace(prefix);
                if (ns == null)
                {
                    throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new ArgumentException(System.SR.Format(System.SR.XmlUndefinedPrefix, prefix), "prefix"));
                }
            }
        }
        else if (ns.Length == 0)
        {
            if (prefix.Length != 0)
            {
                throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new ArgumentException(System.SR.XmlEmptyNamespaceRequiresNullPrefix, "prefix"));
            }
        }
        else if (prefix.Length == 0)
        {
            string text = _nsMgr.LookupAttributePrefix(ns);
            if (text == null)
            {
                if (ns.Length == "http://www.w3.org/2000/xmlns/".Length && ns == "http://www.w3.org/2000/xmlns/")
                {
                    throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new ArgumentException(System.SR.Format(System.SR.XmlSpecificBindingNamespace, "xmlns", ns)));
                }
                if (ns.Length == "http://www.w3.org/XML/1998/namespace".Length && ns == "http://www.w3.org/XML/1998/namespace")
                {
                    throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new ArgumentException(System.SR.Format(System.SR.XmlSpecificBindingNamespace, "xml", ns)));
                }
                text = GeneratePrefix(ns, xNs);
            }
            prefix = text;
        }
        else
        {
            _nsMgr.AddNamespaceIfNotDeclared(prefix, ns, xNs);
        }
        _writeState = WriteState.Attribute;
    }
References System.Xml.XmlBaseWriter._attributeLocalName, System.Xml.XmlBaseWriter._attributeValue, System.Xml.XmlBaseWriter._isXmlAttribute, System.Xml.XmlBaseWriter._isXmlnsAttribute, System.Xml.XmlBaseWriter._nsMgr, System.Xml.XmlBaseWriter._writeState, System.Xml.XmlBaseWriter.NamespaceManager.AddNamespaceIfNotDeclared(), System.Xml.ArgumentException, System.Xml.Dictionary, System.SR.Format(), System.Xml.XmlBaseWriter.GeneratePrefix(), System.Xml.XmlBaseWriter.IsClosed, System.Xml.XmlBaseWriter.NamespaceManager.LookupAttributePrefix(), System.Xml.XmlBaseWriter.NamespaceManager.LookupNamespace(), System.prefix, System.text, System.Xml.XmlBaseWriter.ThrowClosed(), System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperError(), System.Xml.XmlBaseWriter.WriteEndAttribute(), System.SR.XmlEmptyNamespaceRequiresNullPrefix, System.SR.XmlInvalidWriteState, System.SR.XmlPrefixBoundToNamespace, System.SR.XmlSpecificBindingNamespace, and System.SR.XmlUndefinedPrefix.
Referenced by System.Xml.XmlBaseWriter.WriteStartAttribute(), and System.Xml.XmlBaseWriter.WriteStartAttribute().