Terraria: System.Xml.XmlBaseWriter.WriteValue
WriteValue() [7/20]
override void System.Xml.XmlBaseWriter.WriteValue (float value) inline virtual inherited
Reimplemented from System.Xml.XmlWriter.
Definition at line 2172 of file XmlBaseWriter.cs.
    {
        if (IsClosed)
        {
            ThrowClosed();
        }
        FlushBase64();
        if (_attributeValue != null)
        {
            WriteAttributeText(XmlConverter.ToString(value));
        }
        if (!_isXmlnsAttribute)
        {
            StartContent();
            _writer.WriteFloatText(value);
            EndContent();
        }
    }
References System.Xml.XmlBaseWriter._attributeValue, System.Xml.XmlBaseWriter._isXmlnsAttribute, System.Xml.XmlBaseWriter._writer, System.Xml.XmlBaseWriter.EndContent(), System.Xml.XmlBaseWriter.FlushBase64(), System.Xml.XmlBaseWriter.IsClosed, System.Xml.XmlBaseWriter.StartContent(), System.Xml.XmlBaseWriter.ThrowClosed(), System.Xml.XmlConverter.ToString(), System.value, System.Xml.XmlBaseWriter.WriteAttributeText(), and System.Xml.XmlNodeWriter.WriteFloatText().