Terraria: System.Xml.XmlBaseWriter.WritePrimitiveValue
WritePrimitiveValue()
void System.Xml.XmlBaseWriter.WritePrimitiveValue (object value) inline protected inherited
Definition at line 1986 of file XmlBaseWriter.cs.
    {
        if (IsClosed)
        {
            ThrowClosed();
        }
        if (value == null)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new ArgumentNullException("value"));
        }
        if (value is ulong)
        {
            WriteValue((ulong)value);
            return;
        }
        if (value is string)
        {
            WriteValue((string)value);
            return;
        }
        if (value is int)
        {
            WriteValue((int)value);
            return;
        }
        if (value is long)
        {
            WriteValue((long)value);
            return;
        }
        if (value is bool)
        {
            WriteValue((bool)value);
            return;
        }
        if (value is double)
        {
            WriteValue((double)value);
            return;
        }
        if (value is DateTime)
        {
            WriteValue((DateTime)value);
            return;
        }
        if (value is float)
        {
            WriteValue((float)value);
            return;
        }
        if (value is decimal)
        {
            WriteValue((decimal)value);
            return;
        }
        if (value is XmlDictionaryString)
        {
            WriteValue((XmlDictionaryString)value);
            return;
        }
        if (value is UniqueId)
        {
            WriteValue((UniqueId)value);
            return;
        }
        if (value is Guid)
        {
            WriteValue((Guid)value);
            return;
        }
        if (value is TimeSpan)
        {
            WriteValue((TimeSpan)value);
            return;
        }
        if (value.GetType().IsArray)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new ArgumentException(System.SR.XmlNestedArraysNotSupported, "value"));
        }
        base.WriteValue(value);
    }
References System.Xml.ArgumentException, System.Xml.Dictionary, System.Xml.XmlBaseWriter.IsClosed, System.Xml.XmlBaseWriter.ThrowClosed(), System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperError(), System.value, System.Xml.XmlBaseWriter.WriteValue(), and System.SR.XmlNestedArraysNotSupported.
Referenced by System.Xml.XmlBaseWriter.WriteValue(), System.Xml.XmlBaseWriter.WriteValue(), and System.Xml.XmlBaseWriter.WriteValue().