Terraria: System.Xml.XmlBaseWriter.FlushBase64Async
FlushBase64Async()
Task System.Xml.XmlBaseWriter.FlushBase64Async () inline private inherited
Definition at line 2493 of file XmlBaseWriter.cs.
    {
        if (_trailByteCount <= 0)
        {
            return Task.CompletedTask;
        }
        return FlushTrailBytesAsync();
    }
References System.Xml.XmlBaseWriter._trailByteCount, System.Threading.Tasks.Task< TResult >.CompletedTask, and System.Xml.XmlBaseWriter.FlushTrailBytesAsync().
Referenced by System.Xml.XmlBaseWriter.StartElementAsync(), and System.Xml.XmlBaseWriter.WriteEndAttributeAsyncImpl().