Terraria: System.Xml.XmlBaseWriter.WriteValue
WriteValue() [13/20]
void System.Xml.XmlBaseWriter.WriteValue (object[] array) inline private inherited
Definition at line 2532 of file XmlBaseWriter.cs.
    {
        FlushBase64();
        StartContent();
        _writer.WriteStartListText();
        _inList = true;
        for (int i = 0; i < array.Length; i++)
        {
            if (i != 0)
            {
                _writer.WriteListSeparator();
            }
            WritePrimitiveValue(array[i]);
        }
        _inList = false;
        _writer.WriteEndListText();
        EndContent();
    }
References System.Xml.XmlBaseWriter._inList, System.Xml.XmlBaseWriter._writer, System.array, System.Xml.XmlBaseWriter.EndContent(), System.Xml.XmlBaseWriter.FlushBase64(), System.Xml.XmlBaseWriter.StartContent(), System.Xml.XmlNodeWriter.WriteEndListText(), System.Xml.XmlNodeWriter.WriteListSeparator(), System.Xml.XmlBaseWriter.WritePrimitiveValue(), and System.Xml.XmlNodeWriter.WriteStartListText().