Terraria: System.Xml.XmlBaseWriter.WriteComment
WriteComment() [1/2]
override void System.Xml.XmlBaseWriter.WriteComment (string text) inline inherited
Definition at line 1123 of file XmlBaseWriter.cs.
    {
        if (IsClosed)
        {
            ThrowClosed();
        }
        if (_writeState == WriteState.Attribute)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new InvalidOperationException(System.SR.Format(System.SR.XmlInvalidWriteState, "WriteComment", WriteState.ToString())));
        }
        if (text == null)
        {
            text = string.Empty;
        }
        else if (text.IndexOf("--", StringComparison.Ordinal) != -1 || (text.Length > 0 && text[text.Length - 1] == '-'))
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new ArgumentException(System.SR.XmlInvalidCommentChars, "text"));
        }
        StartComment();
        FlushBase64();
        _writer.WriteComment(text);
        EndComment();
    }
References System.Xml.XmlBaseWriter._writer, System.Xml.XmlBaseWriter._writeState, System.Xml.ArgumentException, System.Xml.XmlBaseWriter.EndComment(), System.Xml.XmlBaseWriter.FlushBase64(), System.SR.Format(), System.Xml.XmlBaseWriter.IsClosed, System.Xml.XmlBaseWriter.StartComment(), System.text, System.Xml.XmlBaseWriter.ThrowClosed(), System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperError(), System.Xml.XmlNodeWriter.WriteComment(), System.SR.XmlInvalidCommentChars, and System.SR.XmlInvalidWriteState.