Terraria: System.Xml.XmlBaseWriter.WriteEndElementAsyncImpl
WriteEndElementAsyncImpl()
async Task System.Xml.XmlBaseWriter.WriteEndElementAsyncImpl () inline private inherited
Definition at line 1372 of file XmlBaseWriter.cs.
    {
        if (_writeState == WriteState.Attribute)
        {
            await WriteEndAttributeAsync().ConfigureAwait(continueOnCapturedContext: false);
        }
        FlushBase64();
        if (_writeState == WriteState.Element)
        {
            _nsMgr.DeclareNamespaces(_writer);
            await _writer.WriteEndStartElementAsync(isEmpty: true).ConfigureAwait(continueOnCapturedContext: false);
        }
        else
        {
            Element element = _elements[_depth];
            await _writer.WriteEndElementAsync(element.Prefix, element.LocalName).ConfigureAwait(continueOnCapturedContext: false);
        }
        ExitScope();
        _writeState = WriteState.Content;
    }
References System.Xml.XmlBaseWriter.NamespaceManager._depth, System.Xml.XmlBaseWriter._elements, System.Xml.XmlBaseWriter._nsMgr, System.Xml.XmlBaseWriter._writer, System.Xml.XmlBaseWriter._writeState, System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.Xml.XmlBaseWriter.NamespaceManager.DeclareNamespaces(), System.Xml.Dictionary, System.Xml.XmlBaseWriter.NamespaceManager.ExitScope(), System.Xml.XmlBaseWriter.FlushBase64(), System.Xml.XmlBaseWriter.Element.LocalName, System.Xml.XmlBaseWriter.Element.Prefix, System.Xml.XmlBaseWriter.WriteEndAttributeAsync(), System.Xml.XmlNodeWriter.WriteEndElementAsync(), and System.Xml.XmlNodeWriter.WriteEndStartElementAsync().
Referenced by System.Xml.XmlBaseWriter.WriteEndElementAsync().