Terraria: System.Xml.XmlBaseWriter.WriteBase64Async
WriteBase64Async()
override Task System.Xml.XmlBaseWriter.WriteBase64Async (byte[] buffer, int offset, int count) inline virtual inherited
Reimplemented from System.Xml.XmlWriter.
Definition at line 2374 of file XmlBaseWriter.cs.
    {
        if (IsClosed)
        {
            ThrowClosed();
        }
        if (buffer == null)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new ArgumentNullException("buffer"));
        }
        if (offset < 0)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new ArgumentOutOfRangeException("offset", System.SR.ValueMustBeNonNegative));
        }
        if (count < 0)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new ArgumentOutOfRangeException("count", System.SR.ValueMustBeNonNegative));
        }
        if (count > buffer.Length - offset)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new ArgumentOutOfRangeException("count", System.SR.Format(System.SR.SizeExceedsRemainingBufferSpace, buffer.Length - offset)));
        }
        return WriteBase64AsyncImpl(buffer, offset, count);
    }
References System.buffer, System.count, System.SR.Format(), System.Xml.XmlBaseWriter.IsClosed, System.offset, System.SR.SizeExceedsRemainingBufferSpace, System.Xml.XmlBaseWriter.ThrowClosed(), System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperError(), System.SR.ValueMustBeNonNegative, and System.Xml.XmlBaseWriter.WriteBase64AsyncImpl().