Terraria: System.Xml.XmlBaseWriter.GetQualifiedNamePrefix
GetQualifiedNamePrefix()
string System.Xml.XmlBaseWriter.GetQualifiedNamePrefix (string namespaceUri, XmlDictionaryString xNs) inline private inherited
Definition at line 1584 of file XmlBaseWriter.cs.
    {
        string text = _nsMgr.LookupPrefix(namespaceUri);
        if (text == null)
        {
            if (_writeState != WriteState.Attribute)
            {
                throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new ArgumentException(System.SR.Format(System.SR.XmlNamespaceNotFound, namespaceUri), "namespaceUri"));
            }
            text = GeneratePrefix(namespaceUri, xNs);
        }
        return text;
    }
References System.Xml.XmlBaseWriter._nsMgr, System.Xml.XmlBaseWriter._writeState, System.Xml.ArgumentException, System.Xml.Dictionary, System.SR.Format(), System.Xml.XmlBaseWriter.GeneratePrefix(), System.Xml.XmlBaseWriter.NamespaceManager.LookupPrefix(), System.text, System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperError(), and System.SR.XmlNamespaceNotFound.
Referenced by System.Xml.XmlBaseWriter.WriteQualifiedName(), and System.Xml.XmlBaseWriter.WriteQualifiedName().