Terraria: System.Xml.XmlBaseWriter.EndStartElement
EndStartElement()
void System.Xml.XmlBaseWriter.EndStartElement () inline private inherited
Definition at line 1559 of file XmlBaseWriter.cs.
    {
        _nsMgr.DeclareNamespaces(_writer);
        _writer.WriteEndStartElement(isEmpty: false);
    }
References System.Xml.XmlBaseWriter._nsMgr, System.Xml.XmlBaseWriter._writer, System.Xml.XmlBaseWriter.NamespaceManager.DeclareNamespaces(), System.Xml.Dictionary, and System.Xml.XmlNodeWriter.WriteEndStartElement().
Referenced by System.Xml.XmlBaseWriter.AutoComplete().