Terraria: System.Xml.XmlBaseWriter.StartArray
StartArray()
void System.Xml.XmlBaseWriter.StartArray (int count) inline protected inherited
Definition at line 2570 of file XmlBaseWriter.cs.
    {
        FlushBase64();
        if (_documentState == DocumentState.Epilog)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new InvalidOperationException(System.SR.XmlOnlyOneRoot));
        }
        if (_documentState == DocumentState.Document && count > 1 && _depth == 0)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new InvalidOperationException(System.SR.XmlOnlyOneRoot));
        }
        if (_writeState == WriteState.Attribute)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new InvalidOperationException(System.SR.Format(System.SR.XmlInvalidWriteState, "WriteStartElement", WriteState.ToString())));
        }
        AutoComplete(WriteState.Content);
    }
References System.Xml.XmlBaseWriter.NamespaceManager._depth, System.Xml.XmlBaseWriter._documentState, System.Xml.XmlBaseWriter._writeState, System.Xml.XmlBaseWriter.AutoComplete(), System.count, System.Xml.XmlBaseWriter.FlushBase64(), System.SR.Format(), System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperError(), System.SR.XmlInvalidWriteState, and System.SR.XmlOnlyOneRoot.
Referenced by System.Xml.XmlBinaryWriter.WriteStartArray(), and System.Xml.XmlBinaryWriter.WriteStartArray().