Terraria: System.Xml.XmlBaseWriter.WriteEndAttribute
WriteEndAttribute()
override void System.Xml.XmlBaseWriter.WriteEndAttribute () inline inherited
Definition at line 1006 of file XmlBaseWriter.cs.
    {
        if (IsClosed)
        {
            ThrowClosed();
        }
        if (_writeState != WriteState.Attribute)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new InvalidOperationException(System.SR.Format(System.SR.XmlInvalidWriteState, "WriteEndAttribute", WriteState.ToString())));
        }
        FlushBase64();
        try
        {
            if (_isXmlAttribute)
            {
                if (_attributeLocalName == "lang")
                {
                    _nsMgr.AddLangAttribute(_attributeValue);
                }
                else if (_attributeLocalName == "space")
                {
                    if (_attributeValue == "preserve")
                    {
                        _nsMgr.AddSpaceAttribute(XmlSpace.Preserve);
                    }
                    else
                    {
                        if (!(_attributeValue == "default"))
{
                            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new ArgumentException(System.SR.Format(System.SR.XmlInvalidXmlSpace, _attributeValue)));
                        }
                        _nsMgr.AddSpaceAttribute(XmlSpace.Default);
                    }
                }
                _isXmlAttribute = false;
                _attributeLocalName = null;
                _attributeValue = null;
            }
            if (_isXmlnsAttribute)
            {
                _nsMgr.AddNamespaceIfNotDeclared(_attributeLocalName, _attributeValue, null);
                _isXmlnsAttribute = false;
                _attributeLocalName = null;
                _attributeValue = null;
            }
            else
            {
                _writer.WriteEndAttribute();
            }
        }
        finally
        {
            _writeState = WriteState.Element;
        }
    }
References System.Xml.XmlBaseWriter._attributeLocalName, System.Xml.XmlBaseWriter._attributeValue, System.Xml.XmlBaseWriter._isXmlAttribute, System.Xml.XmlBaseWriter._isXmlnsAttribute, System.Xml.XmlBaseWriter._nsMgr, System.Xml.XmlBaseWriter._writer, System.Xml.XmlBaseWriter._writeState, System.Xml.XmlBaseWriter.NamespaceManager.AddLangAttribute(), System.Xml.XmlBaseWriter.NamespaceManager.AddNamespaceIfNotDeclared(), System.Xml.XmlBaseWriter.NamespaceManager.AddSpaceAttribute(), System.Xml.ArgumentException, System.Xml.XmlBaseWriter.FlushBase64(), System.SR.Format(), System.Xml.XmlBaseWriter.IsClosed, System.Xml.XmlBaseWriter.ThrowClosed(), System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperError(), System.Xml.XmlNodeWriter.WriteEndAttribute(), System.SR.XmlInvalidWriteState, and System.SR.XmlInvalidXmlSpace.
Referenced by System.Xml.XmlBaseWriter.FinishDocument(), System.Xml.XmlBaseWriter.StartAttribute(), System.Xml.XmlBaseWriter.WriteEndElement(), and System.Xml.XmlBaseWriter.WriteFullEndElement().