Terraria: System.Xml.XmlBaseWriter.WriteBase64
WriteBase64()
override void System.Xml.XmlBaseWriter.WriteBase64 (byte[] buffer, int offset, int count) inline inherited
Definition at line 2304 of file XmlBaseWriter.cs.
    {
        if (IsClosed)
        {
            ThrowClosed();
        }
        if (buffer == null)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new ArgumentNullException("buffer"));
        }
        if (offset < 0)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new ArgumentOutOfRangeException("offset", System.SR.ValueMustBeNonNegative));
        }
        if (count < 0)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new ArgumentOutOfRangeException("count", System.SR.ValueMustBeNonNegative));
        }
        if (count > buffer.Length - offset)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new ArgumentOutOfRangeException("count", System.SR.Format(System.SR.SizeExceedsRemainingBufferSpace, buffer.Length - offset)));
        }
        if (count <= 0)
        {
            return;
        }
        if (_trailByteCount > 0)
        {
            while (_trailByteCount < 3 && count > 0)
            {
                _trailBytes[_trailByteCount++] = buffer[offset++];
                count--;
            }
        }
        int num = _trailByteCount + count;
        int num2 = num - num % 3;
        if (_trailBytes == null)
        {
            _trailBytes = new byte[3];
        }
        if (num2 >= 3)
        {
            if (_attributeValue != null)
            {
                WriteAttributeText(XmlConverter.Base64Encoding.GetString(_trailBytes, 0, _trailByteCount));
                WriteAttributeText(XmlConverter.Base64Encoding.GetString(buffer, offset, num2 - _trailByteCount));
            }
            if (!_isXmlnsAttribute)
            {
                StartContent();
                _writer.WriteBase64Text(_trailBytes, _trailByteCount, buffer, offset, num2 - _trailByteCount);
                EndContent();
            }
            _trailByteCount = num - num2;
            if (_trailByteCount > 0)
            {
                int num3 = offset + count - _trailByteCount;
                for (int i = 0; i < _trailByteCount; i++)
                {
                    _trailBytes[i] = buffer[num3++];
                }
            }
        }
        else
        {
            Buffer.BlockCopy(buffer, offset, _trailBytes, _trailByteCount, count);
            _trailByteCount += count;
        }
    }
References System.Xml.XmlBaseWriter._attributeValue, System.Xml.XmlBaseWriter._isXmlnsAttribute, System.Xml.XmlBaseWriter._trailByteCount, System.Xml.XmlBaseWriter._trailBytes, System.Xml.XmlBaseWriter._writer, System.Xml.XmlConverter.Base64Encoding, System.Buffer.BlockCopy(), System.buffer, System.count, System.Xml.Dictionary, System.Xml.XmlBaseWriter.EndContent(), System.SR.Format(), System.Xml.XmlBaseWriter.IsClosed, System.offset, System.SR.SizeExceedsRemainingBufferSpace, System.Xml.XmlBaseWriter.StartContent(), System.Xml.XmlBaseWriter.ThrowClosed(), System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperError(), System.SR.ValueMustBeNonNegative, System.Xml.XmlBaseWriter.WriteAttributeText(), and System.Xml.XmlNodeWriter.WriteBase64Text().
Referenced by System.Xml.XmlBinaryWriter.WriteTextNode().