Terraria: System.Xml.XmlBaseWriter.WriteEndElement
WriteEndElement()
override void System.Xml.XmlBaseWriter.WriteEndElement () inline inherited
Definition at line 1330 of file XmlBaseWriter.cs.
    {
        if (IsClosed)
        {
            ThrowClosed();
        }
        if (_depth == 0)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new InvalidOperationException(System.SR.Format(System.SR.XmlInvalidDepth, "WriteEndElement", _depth.ToString(CultureInfo.InvariantCulture))));
        }
        if (_writeState == WriteState.Attribute)
        {
            WriteEndAttribute();
        }
        FlushBase64();
        if (_writeState == WriteState.Element)
        {
            _nsMgr.DeclareNamespaces(_writer);
            _writer.WriteEndStartElement(isEmpty: true);
        }
        else
        {
            Element element = _elements[_depth];
            _writer.WriteEndElement(element.Prefix, element.LocalName);
        }
        ExitScope();
        _writeState = WriteState.Content;
    }
References System.Xml.XmlBaseWriter.NamespaceManager._depth, System.Xml.XmlBaseWriter._elements, System.Xml.XmlBaseWriter._nsMgr, System.Xml.XmlBaseWriter._writer, System.Xml.XmlBaseWriter._writeState, System.Xml.XmlBaseWriter.NamespaceManager.DeclareNamespaces(), System.Xml.Dictionary, System.Xml.XmlBaseWriter.NamespaceManager.ExitScope(), System.Xml.XmlBaseWriter.FlushBase64(), System.SR.Format(), System.Globalization.CultureInfo.InvariantCulture, System.Xml.XmlBaseWriter.IsClosed, System.Xml.XmlBaseWriter.Element.LocalName, System.Xml.XmlBaseWriter.Element.Prefix, System.Xml.XmlBaseWriter.ThrowClosed(), System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperError(), System.Xml.XmlBaseWriter.WriteEndAttribute(), System.Xml.XmlNodeWriter.WriteEndElement(), System.Xml.XmlNodeWriter.WriteEndStartElement(), and System.SR.XmlInvalidDepth.
Referenced by System.Xml.XmlBaseWriter.FinishDocument(), System.Xml.XmlBaseWriter.WriteFullEndElement(), System.Xml.XmlBinaryWriter.WriteStartArray(), and System.Xml.XmlBinaryWriter.WriteStartArray().