Terraria: System.Xml.XmlBaseWriter.AutoCompleteAsync
AutoCompleteAsync()
async Task System.Xml.XmlBaseWriter.AutoCompleteAsync (WriteState writeState) inline private inherited
Definition at line 1550 of file XmlBaseWriter.cs.
    {
        if (_writeState == WriteState.Element)
        {
            await EndStartElementAsync().ConfigureAwait(continueOnCapturedContext: false);
        }
        _writeState = writeState;
    }
References System.Xml.XmlBaseWriter._writeState, System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.Xml.Dictionary, and System.Xml.XmlBaseWriter.EndStartElementAsync().
Referenced by System.Xml.XmlBaseWriter.FlushElementAsync(), and System.Xml.XmlBaseWriter.StartElementAsync().