Terraria: System.Xml.XmlBaseWriter.WriteStartDocument
WriteStartDocument() [1/2]
override void System.Xml.XmlBaseWriter.WriteStartDocument () inline inherited
Definition at line 1657 of file XmlBaseWriter.cs.
    {
        if (IsClosed)
        {
            ThrowClosed();
        }
        if (_writeState != 0)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new InvalidOperationException(System.SR.Format(System.SR.XmlInvalidWriteState, "WriteStartDocument", WriteState.ToString())));
        }
        _writeState = WriteState.Prolog;
        _documentState = DocumentState.Document;
        _writer.WriteDeclaration();
    }
References System.Xml.XmlBaseWriter._documentState, System.Xml.XmlBaseWriter._writer, System.Xml.XmlBaseWriter._writeState, System.SR.Format(), System.Xml.XmlBaseWriter.IsClosed, System.Xml.XmlBaseWriter.ThrowClosed(), System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperError(), System.Xml.XmlNodeWriter.WriteDeclaration(), and System.SR.XmlInvalidWriteState.
Referenced by System.Xml.XmlBaseWriter.WriteStartDocument().