Terraria: System.Xml.XmlBaseWriter.StartCanonicalization
StartCanonicalization() [1/2]
override void System.Xml.XmlBaseWriter.StartCanonicalization (Stream stream, bool includeComments, string[] inclusivePrefixes) inline inherited
Definition at line 2449 of file XmlBaseWriter.cs.
    {
        if (IsClosed)
        {
            ThrowClosed();
        }
        if (Signing)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new InvalidOperationException(System.SR.XmlCanonicalizationStarted));
        }
        FlushElement();
        if (_signingWriter == null)
        {
            _signingWriter = CreateSigningNodeWriter();
        }
        _signingWriter.SetOutput(_writer, stream, includeComments, inclusivePrefixes);
        _writer = _signingWriter;
        SignScope(_signingWriter.CanonicalWriter);
    }
References System.Xml.XmlBaseWriter._signingWriter, System.Xml.XmlBaseWriter._writer, System.Xml.XmlSigningNodeWriter.CanonicalWriter, System.Xml.XmlBaseWriter.CreateSigningNodeWriter(), System.Xml.Dictionary, System.Xml.XmlBaseWriter.FlushElement(), System.Xml.XmlBaseWriter.IsClosed, System.Xml.XmlSigningNodeWriter.SetOutput(), System.Xml.XmlBaseWriter.Signing, System.Xml.XmlBaseWriter.SignScope(), System.stream, System.Xml.XmlBaseWriter.ThrowClosed(), System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperError(), and System.SR.XmlCanonicalizationStarted.