Terraria: System.Xml.XmlBaseWriter.WriteRaw
WriteRaw() [1/2]
override void System.Xml.XmlBaseWriter.WriteRaw (char[] chars, int offset, int count) inline inherited
Definition at line 1880 of file XmlBaseWriter.cs.
    {
        if (IsClosed)
        {
            ThrowClosed();
        }
        if (chars == null)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new ArgumentNullException("chars"));
        }
        if (offset < 0)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new ArgumentOutOfRangeException("offset", System.SR.ValueMustBeNonNegative));
        }
        if (count < 0)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new ArgumentOutOfRangeException("count", System.SR.ValueMustBeNonNegative));
        }
        if (count > chars.Length - offset)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new ArgumentOutOfRangeException("count", System.SR.Format(System.SR.SizeExceedsRemainingBufferSpace, chars.Length - offset)));
        }
        if (count > 0)
        {
            FlushBase64();
            if (_attributeValue != null)
            {
                WriteAttributeText(new string(chars, offset, count));
            }
            if (!_isXmlnsAttribute)
            {
                StartContent(chars, offset, count);
                _writer.WriteText(chars, offset, count);
                EndContent();
            }
        }
    }
References System.Xml.XmlBaseWriter._attributeValue, System.Xml.XmlBaseWriter._isXmlnsAttribute, System.Xml.XmlBaseWriter._writer, System.chars, System.count, System.Xml.XmlBaseWriter.EndContent(), System.Xml.XmlBaseWriter.FlushBase64(), System.SR.Format(), System.Xml.XmlBaseWriter.IsClosed, System.offset, System.SR.SizeExceedsRemainingBufferSpace, System.Xml.XmlBaseWriter.StartContent(), System.Xml.XmlBaseWriter.ThrowClosed(), System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperError(), System.SR.ValueMustBeNonNegative, System.Xml.XmlBaseWriter.WriteAttributeText(), and System.Xml.XmlNodeWriter.WriteText().