Terraria: System.Xml.XmlBaseWriter.EndCanonicalization
EndCanonicalization()
override void System.Xml.XmlBaseWriter.EndCanonicalization () inline virtual inherited
Reimplemented from System.Xml.XmlDictionaryWriter.
Definition at line 2469 of file XmlBaseWriter.cs.
    {
        if (IsClosed)
        {
            ThrowClosed();
        }
        if (!Signing)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new InvalidOperationException(System.SR.XmlCanonicalizationNotStarted));
        }
        _signingWriter.Flush();
        _writer = _signingWriter.NodeWriter;
    }
References System.Xml.XmlBaseWriter._signingWriter, System.Xml.XmlBaseWriter._writer, System.Xml.XmlSigningNodeWriter.Flush(), System.Xml.XmlBaseWriter.IsClosed, System.Xml.XmlSigningNodeWriter.NodeWriter, System.Xml.XmlBaseWriter.Signing, System.Xml.XmlBaseWriter.ThrowClosed(), System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperError(), and System.SR.XmlCanonicalizationNotStarted.