Terraria: System.Xml.XmlBaseWriter.WriteQualifiedName
WriteQualifiedName() [1/4]
override void System.Xml.XmlBaseWriter.WriteQualifiedName (string localName, string namespaceUri) inline inherited
Definition at line 1598 of file XmlBaseWriter.cs.
    {
        if (IsClosed)
        {
            ThrowClosed();
        }
        if (localName == null)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new ArgumentNullException("localName"));
        }
        if (localName.Length == 0)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new ArgumentException(System.SR.InvalidLocalNameEmpty, "localName"));
        }
        if (namespaceUri == null)
        {
            namespaceUri = string.Empty;
        }
        string qualifiedNamePrefix = GetQualifiedNamePrefix(namespaceUri, null);
        if (qualifiedNamePrefix.Length != 0)
        {
            WriteString(qualifiedNamePrefix);
            WriteString(":");
        }
        WriteString(localName);
    }
References System.Xml.ArgumentException, System.Xml.Dictionary, System.Xml.XmlBaseWriter.GetQualifiedNamePrefix(), System.SR.InvalidLocalNameEmpty, System.Xml.XmlBaseWriter.IsClosed, System.Xml.XmlBaseWriter.ThrowClosed(), System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperError(), and System.Xml.XmlBaseWriter.WriteString().