Terraria: System.Xml.XmlBaseWriter.Close
Close()
override void System.Xml.XmlBaseWriter.Close () inline virtual inherited
Reimplemented from System.Xml.XmlWriter.
Definition at line 790 of file XmlBaseWriter.cs.
    {
        if (IsClosed)
        {
            return;
        }
        try
        {
            FinishDocument();
            AutoComplete(WriteState.Closed);
            _writer.Flush();
        }
        finally
        {
            _nsMgr.Close();
            if (_depth != 0)
            {
                _elements = null;
                _depth = 0;
            }
            _attributeValue = null;
            _attributeLocalName = null;
            _nodeWriter.Close();
            if (_signingWriter != null)
            {
                _signingWriter.Close();
            }
        }
    }
References System.Xml.XmlBaseWriter._attributeLocalName, System.Xml.XmlBaseWriter._attributeValue, System.Xml.XmlBaseWriter.NamespaceManager._depth, System.Xml.XmlBaseWriter._elements, System.Xml.XmlBaseWriter._nodeWriter, System.Xml.XmlBaseWriter._nsMgr, System.Xml.XmlBaseWriter._signingWriter, System.Xml.XmlBaseWriter._writer, System.Xml.XmlBaseWriter.AutoComplete(), System.Xml.XmlBaseWriter.NamespaceManager.Close(), System.Xml.XmlSigningNodeWriter.Close(), System.Xml.XmlStreamNodeWriter.Close(), System.Xml.XmlBaseWriter.FinishDocument(), System.Xml.XmlNodeWriter.Flush(), and System.Xml.XmlBaseWriter.IsClosed.