Terraria: System.Xml.XmlBaseWriter.WriteBase64AsyncImpl
WriteBase64AsyncImpl()
async Task System.Xml.XmlBaseWriter.WriteBase64AsyncImpl (byte[] buffer, int offset, int count) inline private inherited
Definition at line 2399 of file XmlBaseWriter.cs.
    {
        if (count <= 0)
        {
            return;
        }
        if (_trailByteCount > 0)
        {
            while (_trailByteCount < 3 && count > 0)
            {
                _trailBytes[_trailByteCount++] = buffer[offset++];
                count--;
            }
        }
        int totalByteCount = _trailByteCount + count;
        int actualByteCount = totalByteCount - totalByteCount % 3;
        if (_trailBytes == null)
        {
            _trailBytes = new byte[3];
        }
        if (actualByteCount >= 3)
        {
            if (_attributeValue != null)
            {
                WriteAttributeText(XmlConverter.Base64Encoding.GetString(_trailBytes, 0, _trailByteCount));
                WriteAttributeText(XmlConverter.Base64Encoding.GetString(buffer, offset, actualByteCount - _trailByteCount));
            }
            if (!_isXmlnsAttribute)
            {
                await StartContentAsync().ConfigureAwait(continueOnCapturedContext: false);
                await _writer.WriteBase64TextAsync(_trailBytes, _trailByteCount, buffer, offset, actualByteCount - _trailByteCount).ConfigureAwait(continueOnCapturedContext: false);
                EndContent();
            }
            _trailByteCount = totalByteCount - actualByteCount;
            if (_trailByteCount > 0)
            {
                int num = offset + count - _trailByteCount;
                for (int i = 0; i < _trailByteCount; i++)
                {
                    _trailBytes[i] = buffer[num++];
                }
            }
        }
        else
        {
            Buffer.BlockCopy(buffer, offset, _trailBytes, _trailByteCount, count);
            _trailByteCount += count;
        }
    }
References System.Xml.XmlBaseWriter._attributeValue, System.Xml.XmlBaseWriter._isXmlnsAttribute, System.Xml.XmlBaseWriter._trailByteCount, System.Xml.XmlBaseWriter._trailBytes, System.Xml.XmlBaseWriter._writer, System.Xml.XmlConverter.Base64Encoding, System.Buffer.BlockCopy(), System.buffer, System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.count, System.Xml.Dictionary, System.Xml.XmlBaseWriter.EndContent(), System.offset, System.Xml.XmlBaseWriter.StartContentAsync(), System.Xml.XmlBaseWriter.WriteAttributeText(), and System.Xml.XmlNodeWriter.WriteBase64TextAsync().
Referenced by System.Xml.XmlBaseWriter.WriteBase64Async().