Terraria: System.Xml.XmlBaseWriter.WriteEndAttributeAsyncImpl
WriteEndAttributeAsyncImpl()
async Task System.Xml.XmlBaseWriter.WriteEndAttributeAsyncImpl () inline private inherited
Definition at line 1075 of file XmlBaseWriter.cs.
    {
        await FlushBase64Async().ConfigureAwait(continueOnCapturedContext: false);
        try
        {
            if (_isXmlAttribute)
            {
                if (_attributeLocalName == "lang")
                {
                    _nsMgr.AddLangAttribute(_attributeValue);
                }
                else if (_attributeLocalName == "space")
                {
                    if (_attributeValue == "preserve")
                    {
                        _nsMgr.AddSpaceAttribute(XmlSpace.Preserve);
                    }
                    else
                    {
                        if (!(_attributeValue == "default"))
{
                            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new ArgumentException(System.SR.Format(System.SR.XmlInvalidXmlSpace, _attributeValue)));
                        }
                        _nsMgr.AddSpaceAttribute(XmlSpace.Default);
                    }
                }
                _isXmlAttribute = false;
                _attributeLocalName = null;
                _attributeValue = null;
            }
            if (_isXmlnsAttribute)
            {
                _nsMgr.AddNamespaceIfNotDeclared(_attributeLocalName, _attributeValue, null);
                _isXmlnsAttribute = false;
                _attributeLocalName = null;
                _attributeValue = null;
            }
            else
            {
                await _writer.WriteEndAttributeAsync().ConfigureAwait(continueOnCapturedContext: false);
            }
        }
        finally
        {
            _writeState = WriteState.Element;
        }
    }
References System.Xml.XmlBaseWriter._attributeLocalName, System.Xml.XmlBaseWriter._attributeValue, System.Xml.XmlBaseWriter._isXmlAttribute, System.Xml.XmlBaseWriter._isXmlnsAttribute, System.Xml.XmlBaseWriter._nsMgr, System.Xml.XmlBaseWriter._writer, System.Xml.XmlBaseWriter._writeState, System.Xml.XmlBaseWriter.NamespaceManager.AddLangAttribute(), System.Xml.XmlBaseWriter.NamespaceManager.AddNamespaceIfNotDeclared(), System.Xml.XmlBaseWriter.NamespaceManager.AddSpaceAttribute(), System.Xml.ArgumentException, System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.Xml.Dictionary, System.Xml.XmlBaseWriter.FlushBase64Async(), System.SR.Format(), System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperError(), System.Xml.XmlNodeWriter.WriteEndAttributeAsync(), and System.SR.XmlInvalidXmlSpace.
Referenced by System.Xml.XmlBaseWriter.WriteEndAttributeAsync().