Terraria: System.Xml.XmlBaseWriter.FlushElement
FlushElement()
void System.Xml.XmlBaseWriter.FlushElement () inline protected inherited
Definition at line 1427 of file XmlBaseWriter.cs.
    {
        if (_writeState == WriteState.Element)
        {
            AutoComplete(WriteState.Content);
        }
    }
References System.Xml.XmlBaseWriter._writeState, and System.Xml.XmlBaseWriter.AutoComplete().
Referenced by System.Xml.XmlBaseWriter.StartCanonicalization(), System.Xml.XmlBaseWriter.StartComment(), System.Xml.XmlBaseWriter.StartContent(), System.Xml.XmlBaseWriter.StartContent(), System.Xml.XmlBaseWriter.StartContent(), and System.Xml.XmlBaseWriter.StartContent().