Terraria: System.IO.Compression.ZipFile.DoCreateFromDirectory
DoCreateFromDirectory()
static void System.IO.Compression.ZipFile.DoCreateFromDirectory (string sourceDirectoryName, string destinationArchiveFileName, CompressionLevel? compressionLevel, bool includeBaseDirectory, Encoding entryNameEncoding) inline static private
Definition at line 70 of file ZipFile.cs.
    {
        sourceDirectoryName = Path.GetFullPath(sourceDirectoryName);
        destinationArchiveFileName = Path.GetFullPath(destinationArchiveFileName);
        using ZipArchive zipArchive = Open(destinationArchiveFileName, ZipArchiveMode.Create, entryNameEncoding);
        bool flag = true;
        DirectoryInfo directoryInfo = new DirectoryInfo(sourceDirectoryName);
        string fullName = directoryInfo.FullName;
        if (includeBaseDirectory && directoryInfo.Parent != null)
        {
            fullName = directoryInfo.Parent.FullName;
        }
        char[] buffer = ArrayPool<char>.Shared.Rent(260);
        try
        {
            foreach (FileSystemInfo item in directoryInfo.EnumerateFileSystemInfos("*", SearchOption.AllDirectories))
            {
                flag = false;
                int length = item.FullName.Length - fullName.Length;
                if (item is FileInfo)
                {
                    string entryName = ZipFileUtils.EntryFromPath(item.FullName, fullName.Length, length, ref buffer);
                    zipArchive.DoCreateEntryFromFile(item.FullName, entryName, compressionLevel);
                }
                else if (item is DirectoryInfo possiblyEmptyDir && ZipFileUtils.IsDirEmpty(possiblyEmptyDir))
                {
                    string entryName2 = ZipFileUtils.EntryFromPath(item.FullName, fullName.Length, length, ref buffer, appendPathSeparator: true);
                    zipArchive.CreateEntry(entryName2);
                }
            }
            if (includeBaseDirectory && flag)
            {
                zipArchive.CreateEntry(ZipFileUtils.EntryFromPath(directoryInfo.Name, 0, directoryInfo.Name.Length, ref buffer, appendPathSeparator: true));
            }
        }
        finally
        {
            ArrayPool<char>.Shared.Return(buffer);
        }
    }
References System.buffer, System.IO.Compression.ZipFileUtils.EntryFromPath(), System.IO.DirectoryInfo.EnumerateFileSystemInfos(), System.IO.FileSystemInfo.FullName, System.IO.Path.GetFullPath(), System.IO.Compression.ZipFileUtils.IsDirEmpty(), System.item, System.length, System.IO.FileSystemInfo.Name, System.IO.Open, System.IO.DirectoryInfo.Parent, and System.Buffers.ArrayPool< T >.Shared.
Referenced by System.IO.Compression.ZipFile.CreateFromDirectory(), System.IO.Compression.ZipFile.CreateFromDirectory(), and System.IO.Compression.ZipFile.CreateFromDirectory().