Terraria: System.Xml.Schema.Compiler.CompileComplexType
CompileComplexType()
void System.Xml.Schema.Compiler.CompileComplexType (XmlSchemaComplexType complexType) inline private
Definition at line 730 of file Compiler.cs.
    {
        if (complexType.ElementDecl != null)
        {
            return;
        }
        if (complexType.IsProcessing)
        {
            SendValidationEvent(System.SR.Sch_TypeCircularRef, complexType);
            return;
        }
        complexType.IsProcessing = true;
        try
        {
            if (complexType.ContentModel != null)
            {
                if (complexType.ContentModel is XmlSchemaSimpleContent)
                {
                    XmlSchemaSimpleContent xmlSchemaSimpleContent = (XmlSchemaSimpleContent)complexType.ContentModel;
                    complexType.SetContentType(XmlSchemaContentType.TextOnly);
                    if (xmlSchemaSimpleContent.Content is XmlSchemaSimpleContentExtension)
                    {
                        CompileSimpleContentExtension(complexType, (XmlSchemaSimpleContentExtension)xmlSchemaSimpleContent.Content);
                    }
                    else
                    {
                        CompileSimpleContentRestriction(complexType, (XmlSchemaSimpleContentRestriction)xmlSchemaSimpleContent.Content);
                    }
                }
                else
                {
                    XmlSchemaComplexContent xmlSchemaComplexContent = (XmlSchemaComplexContent)complexType.ContentModel;
                    if (xmlSchemaComplexContent.Content is XmlSchemaComplexContentExtension)
                    {
                        CompileComplexContentExtension(complexType, xmlSchemaComplexContent, (XmlSchemaComplexContentExtension)xmlSchemaComplexContent.Content);
                    }
                    else
                    {
                        CompileComplexContentRestriction(complexType, xmlSchemaComplexContent, (XmlSchemaComplexContentRestriction)xmlSchemaComplexContent.Content);
                    }
                }
            }
            else
            {
                complexType.SetBaseSchemaType(XmlSchemaComplexType.AnyType);
                CompileLocalAttributes(XmlSchemaComplexType.AnyType, complexType, complexType.Attributes, complexType.AnyAttribute, XmlSchemaDerivationMethod.Restriction);
                complexType.SetDerivedBy(XmlSchemaDerivationMethod.Restriction);
                complexType.SetContentTypeParticle(CompileContentTypeParticle(complexType.Particle));
                complexType.SetContentType(GetSchemaContentType(complexType, null, complexType.ContentTypeParticle));
            }
            if (complexType.ContainsIdAttribute(findAll: true))
            {
                SendValidationEvent(System.SR.Sch_TwoIdAttrUses, complexType);
            }
            SchemaElementDecl schemaElementDecl = new SchemaElementDecl();
            schemaElementDecl.ContentValidator = CompileComplexContent(complexType);
            schemaElementDecl.SchemaType = complexType;
            schemaElementDecl.IsAbstract = complexType.IsAbstract;
            schemaElementDecl.Datatype = complexType.Datatype;
            schemaElementDecl.Block = complexType.BlockResolved;
            schemaElementDecl.AnyAttribute = complexType.AttributeWildcard;
            foreach (XmlSchemaAttribute value in complexType.AttributeUses.Values)
            {
                if (value.Use == XmlSchemaUse.Prohibited)
                {
                    if (!schemaElementDecl.ProhibitedAttributes.ContainsKey(value.QualifiedName))
                    {
                        schemaElementDecl.ProhibitedAttributes.Add(value.QualifiedName, value.QualifiedName);
                    }
                }
                else if (!schemaElementDecl.AttDefs.ContainsKey(value.QualifiedName) && value.AttDef != null && value.AttDef.Name != XmlQualifiedName.Empty && value.AttDef != SchemaAttDef.Empty)
                {
                    schemaElementDecl.AddAttDef(value.AttDef);
                }
            }
            complexType.ElementDecl = schemaElementDecl;
        }
        finally
        {
            complexType.IsProcessing = false;
        }
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Xml.Schema.XmlSchemaComplexType.AnyType, System.Xml.Schema.Compiler.CompileComplexContent(), System.Xml.Schema.Compiler.CompileComplexContentExtension(), System.Xml.Schema.Compiler.CompileComplexContentRestriction(), System.Xml.Schema.Compiler.CompileContentTypeParticle(), System.Xml.Schema.Compiler.CompileLocalAttributes(), System.Xml.Schema.Compiler.CompileSimpleContentExtension(), System.Xml.Schema.Compiler.CompileSimpleContentRestriction(), System.Collections.Generic.Dictionary< TKey, TValue >.ContainsKey(), System.Xml.Dictionary, System.Xml.Schema.SchemaAttDef.Empty, System.Xml.XmlQualifiedName.Empty, System.Xml.Schema.Compiler.GetSchemaContentType(), System.SR.Sch_TwoIdAttrUses, System.SR.Sch_TypeCircularRef, System.Xml.Schema.BaseProcessor.SendValidationEvent(), System.value, and System.Collections.Generic.Dictionary< TKey, TValue >.Values.
Referenced by System.Xml.Schema.Compiler.Compile(), System.Xml.Schema.Compiler.CompileComplexContentExtension(), System.Xml.Schema.Compiler.CompileComplexContentRestriction(), System.Xml.Schema.Compiler.CompileElement(), System.Xml.Schema.Compiler.CompileSimpleContentExtension(), System.Xml.Schema.Compiler.CompileSimpleContentRestriction(), System.Xml.Schema.Compiler.GetAnySchemaType(), and System.Xml.Schema.Compiler.GetComplexType().