Terraria: System.Xml.Schema.Compiler.GetMappingParticle
GetMappingParticle()
int System.Xml.Schema.Compiler.GetMappingParticle (XmlSchemaParticle particle, XmlSchemaObjectCollection collection) inline private
Definition at line 1723 of file Compiler.cs.
    {
        for (int i = 0; i < collection.Count; i++)
        {
            if (IsValidRestriction(particle, (XmlSchemaParticle)collection[i]))
            {
                return i;
            }
        }
        return -1;
    }
References System.collection, and System.Xml.Schema.Compiler.IsValidRestriction().
Referenced by System.Xml.Schema.Compiler.IsChoiceFromChoiceSubstGroup(), System.Xml.Schema.Compiler.IsSequenceFromAll(), and System.Xml.Schema.Compiler.IsSequenceFromChoice().