Terraria: System.Xml.Schema.Compiler.Prepare
Prepare()
void System.Xml.Schema.Compiler.Prepare (XmlSchema schema, bool cleanup) inline package
Definition at line 54 of file Compiler.cs.
    {
        if (_schemasToCompile[schema] != null)
        {
            return;
        }
        _schemasToCompile.Add(schema, schema);
        foreach (XmlSchemaElement value in schema.Elements.Values)
        {
            if (cleanup)
            {
                CleanupElement(value);
            }
            AddToTable(_elements, value.QualifiedName, value);
        }
        foreach (XmlSchemaAttribute value2 in schema.Attributes.Values)
        {
            if (cleanup)
            {
                CleanupAttribute(value2);
            }
            AddToTable(_attributes, value2.QualifiedName, value2);
        }
        foreach (XmlSchemaGroup value3 in schema.Groups.Values)
        {
            if (cleanup)
            {
                CleanupGroup(value3);
            }
            AddToTable(_groups, value3.QualifiedName, value3);
        }
        foreach (XmlSchemaAttributeGroup value4 in schema.AttributeGroups.Values)
        {
            if (cleanup)
            {
                CleanupAttributeGroup(value4);
            }
            AddToTable(_attributeGroups, value4.QualifiedName, value4);
        }
        foreach (XmlSchemaType value5 in schema.SchemaTypes.Values)
        {
            if (cleanup)
            {
                if (value5 is XmlSchemaComplexType complexType)
                {
                    CleanupComplexType(complexType);
                }
                else
                {
                    CleanupSimpleType(value5 as XmlSchemaSimpleType);
                }
            }
            AddToTable(_schemaTypes, value5.QualifiedName, value5);
        }
        foreach (XmlSchemaNotation value6 in schema.Notations.Values)
        {
            AddToTable(_notations, value6.QualifiedName, value6);
        }
        foreach (XmlSchemaIdentityConstraint value7 in schema.IdentityConstraints.Values)
        {
            AddToTable(_identityConstraints, value7.QualifiedName, value7);
        }
    }
References System.Xml.Schema.Compiler._attributeGroups, System.Xml.Schema.Compiler._attributes, System.Xml.Schema.Compiler._elements, System.Xml.Schema.Compiler._groups, System.Xml.Schema.Compiler._identityConstraints, System.Xml.Schema.Compiler._notations, System.Xml.Schema.Compiler._schemasToCompile, System.Xml.Schema.Compiler._schemaTypes, System.Collections.Hashtable.Add(), System.Xml.Schema.BaseProcessor.AddToTable(), System.Xml.Schema.Compiler.CleanupAttribute(), System.Xml.Schema.Compiler.CleanupAttributeGroup(), System.Xml.Schema.Compiler.CleanupComplexType(), System.Xml.Schema.Compiler.CleanupElement(), System.Xml.Schema.Compiler.CleanupGroup(), System.Xml.Schema.Compiler.CleanupSimpleType(), System.value, and System.Collections.Generic.Dictionary< TKey, TValue >.Values.
Referenced by System.Xml.Schema.Compiler.ImportAllCompiledSchemas().