Terraria: System.Transactions.TransactionScope.TransactionScope
TransactionScope() [11/14]
System.Transactions.TransactionScope.TransactionScope (Transaction transactionToUse, TransactionScopeAsyncFlowOption asyncFlowOption) inline
Definition at line 247 of file TransactionScope.cs.
    {
        TransactionsEtwProvider log = TransactionsEtwProvider.Log;
        if (log.IsEnabled())
        {
            log.MethodEnter(TraceSourceType.TraceSourceBase, this, ".ctor");
        }
        ValidateAndSetAsyncFlowOption(asyncFlowOption);
        Initialize(transactionToUse, TimeSpan.Zero, interopModeSpecified: false);
        if (log.IsEnabled())
        {
            log.MethodExit(TraceSourceType.TraceSourceBase, this, ".ctor");
        }
    }
References System.Transactions.TransactionScope.Initialize(), System.Diagnostics.Tracing.EventSource.IsEnabled(), System.Transactions.TransactionsEtwProvider.Log, System.Transactions.TransactionsEtwProvider.MethodEnter(), System.Transactions.TransactionsEtwProvider.MethodExit(), System.Transactions.TransactionScope.ValidateAndSetAsyncFlowOption(), and System.TimeSpan.Zero.