Terraria: System.Transactions.TransactionScope.Timeout
Timeout()
void System.Transactions.TransactionScope.Timeout () inline private
Definition at line 587 of file TransactionScope.cs.
    {
        if (_complete || !(null != _expectedCurrent))
        {
            return;
        }
        TransactionsEtwProvider log = TransactionsEtwProvider.Log;
        if (log.IsEnabled())
        {
            log.TransactionScopeTimeout(_expectedCurrent.TransactionTraceId);
        }
        try
        {
            _expectedCurrent.Rollback();
        }
        catch (ObjectDisposedException exception)
        {
            if (log.IsEnabled())
            {
                log.ExceptionConsumed(TraceSourceType.TraceSourceBase, exception);
            }
        }
        catch (TransactionException exception2)
        {
            if (log.IsEnabled())
            {
                log.ExceptionConsumed(TraceSourceType.TraceSourceBase, exception2);
            }
        }
    }
References System.Transactions.TransactionScope._complete, System.Transactions.TransactionScope._expectedCurrent, System.exception, System.Transactions.TransactionsEtwProvider.ExceptionConsumed(), System.Diagnostics.Tracing.EventSource.IsEnabled(), System.Transactions.TransactionsEtwProvider.Log, System.Transactions.Transaction.Rollback(), System.Transactions.TransactionsEtwProvider.TransactionScopeTimeout(), and System.Transactions.Transaction.TransactionTraceId.