Terraria: System.Transactions.TransactionScope.InternalDispose
InternalDispose()
void System.Transactions.TransactionScope.InternalDispose () inline private
Definition at line 489 of file TransactionScope.cs.
    {
        _disposed = true;
        try
        {
            PopScope();
            TransactionsEtwProvider log = TransactionsEtwProvider.Log;
            if (null == _expectedCurrent)
            {
                if (log.IsEnabled())
                {
                    log.TransactionScopeDisposed(TransactionTraceIdentifier.Empty);
                }
            }
            else if (log.IsEnabled())
            {
                log.TransactionScopeDisposed(_expectedCurrent.TransactionTraceId);
            }
            if (!(null != _expectedCurrent))
            {
                return;
            }
            if (!_complete)
            {
                if (log.IsEnabled())
                {
                    log.TransactionScopeIncomplete(_expectedCurrent.TransactionTraceId);
                }
                Transaction transaction = _committableTransaction;
                if (transaction == null)
                {
                    transaction = _dependentTransaction;
                }
                transaction.Rollback();
            }
            else if (null != _committableTransaction)
            {
                _committableTransaction.Commit();
            }
            else
            {
                _dependentTransaction.Complete();
            }
        }
        finally
        {
            if (_scopeTimer != null)
            {
                _scopeTimer.Dispose();
            }
            if (null != _committableTransaction)
            {
                _committableTransaction.Dispose();
                _expectedCurrent.Dispose();
            }
            if (null != _dependentTransaction)
            {
                _dependentTransaction.Dispose();
            }
        }
    }
References System.Transactions.TransactionScope._committableTransaction, System.Transactions.TransactionScope._complete, System.Transactions.TransactionScope._dependentTransaction, System.Transactions.TransactionScope._disposed, System.Transactions.TransactionScope._expectedCurrent, System.Transactions.TransactionScope._scopeTimer, System.Transactions.CommittableTransaction.Commit(), System.Transactions.DependentTransaction.Complete(), System.Transactions.Transaction.Dispose(), System.Threading.Timer.Dispose(), System.Transactions.TransactionTraceIdentifier.Empty, System.Diagnostics.Tracing.EventSource.IsEnabled(), System.Transactions.TransactionsEtwProvider.Log, System.Transactions.TransactionScope.PopScope(), System.Transactions.Transaction.Rollback(), System.Transactions.TransactionsEtwProvider.TransactionScopeDisposed(), System.Transactions.TransactionsEtwProvider.TransactionScopeIncomplete(), and System.Transactions.Transaction.TransactionTraceId.
Referenced by System.Transactions.TransactionScope.Dispose().