Terraria: System.Runtime.Serialization.XmlDataContract.XmlDataContractCriticalHelper.XmlDataContractCriticalHelper
XmlDataContractCriticalHelper()
System.Runtime.Serialization.XmlDataContract.XmlDataContractCriticalHelper.XmlDataContractCriticalHelper ([DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicConstructors | DynamicallyAccessedMemberTypes.NonPublicConstructors | DynamicallyAccessedMemberTypes.PublicMethods | DynamicallyAccessedMemberTypes.NonPublicMethods | DynamicallyAccessedMemberTypes.PublicFields | DynamicallyAccessedMemberTypes.PublicProperties)] Type type) inline package
Definition at line 135 of file XmlDataContract.cs.
            : base(type)
        {
            if (type.IsDefined(Globals.TypeOfDataContractAttribute, inherit: false))
            {
                throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new InvalidDataContractException(System.SR.Format(System.SR.IXmlSerializableCannotHaveDataContract, DataContract.GetClrTypeFullName(type))));
            }
            if (type.IsDefined(Globals.TypeOfCollectionDataContractAttribute, inherit: false))
            {
                throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new InvalidDataContractException(System.SR.Format(System.SR.IXmlSerializableCannotHaveCollectionDataContract, DataContract.GetClrTypeFullName(type))));
            }
            SchemaExporter.GetXmlTypeInfo(type, out var stableName, out var _, out var hasRoot);
            base.StableName = stableName;
            HasRoot = hasRoot;
            XmlDictionary xmlDictionary = new XmlDictionary();
            base.Name = xmlDictionary.Add(base.StableName.Name);
            base.Namespace = xmlDictionary.Add(base.StableName.Namespace);
            object[] array = ((base.UnderlyingType == null) ? null : base.UnderlyingType.GetCustomAttributes(Globals.TypeOfXmlRootAttribute, inherit: false).ToArray());
            if (array == null || array.Length == 0)
            {
                if (hasRoot)
                {
                    _topLevelElementName = base.Name;
                    _topLevelElementNamespace = ((base.StableName.Namespace == "http://www.w3.org/2001/XMLSchema") ? DictionaryGlobals.EmptyString : base.Namespace);
                    _isTopLevelElementNullable = true;
                }
                return;
            }
            if (hasRoot)
            {
                XmlRootAttribute xmlRootAttribute = (XmlRootAttribute)array[0];
                _isTopLevelElementNullable = xmlRootAttribute.IsNullable;
                string elementName = xmlRootAttribute.ElementName;
                _topLevelElementName = ((elementName == null || elementName.Length == 0) ? base.Name : xmlDictionary.Add(DataContract.EncodeLocalName(elementName)));
                string @namespace = xmlRootAttribute.Namespace;
                _topLevelElementNamespace = ((@namespace == null || @namespace.Length == 0) ? DictionaryGlobals.EmptyString : xmlDictionary.Add(@namespace));
                return;
            }
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new InvalidDataContractException(System.SR.Format(System.SR.IsAnyCannotHaveXmlRoot, DataContract.GetClrTypeFullName(base.UnderlyingType))));
        }
References System.Runtime.Serialization.XmlDataContract.XmlDataContractCriticalHelper._isTopLevelElementNullable, System.Runtime.Serialization.XmlDataContract.XmlDataContractCriticalHelper._topLevelElementName, System.Runtime.Serialization.XmlDataContract.XmlDataContractCriticalHelper._topLevelElementNamespace, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.array, System.Runtime.Serialization.Dictionary, System.Runtime.Serialization.DictionaryGlobals.EmptyString, System.Runtime.Serialization.DataContract.EncodeLocalName(), System.SR.Format(), System.Runtime.Serialization.DataContract.GetClrTypeFullName(), System.Runtime.Serialization.SchemaExporter.GetXmlTypeInfo(), System.Runtime.Serialization.XmlDataContract.XmlDataContractCriticalHelper.HasRoot, System.SR.IsAnyCannotHaveXmlRoot, System.SR.IXmlSerializableCannotHaveCollectionDataContract, System.SR.IXmlSerializableCannotHaveDataContract, System.Xml.Schema.Length, System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperError(), System.type, System.Runtime.Serialization.Globals.TypeOfCollectionDataContractAttribute, System.Runtime.Serialization.Globals.TypeOfDataContractAttribute, and System.Runtime.Serialization.Globals.TypeOfXmlRootAttribute.
Referenced by System.Runtime.Serialization.XmlDataContract.XmlDataContract().