Terraria: System.Transactions.TransactionScope.TimerCallback
TimerCallback()
static void System.Transactions.TransactionScope.TimerCallback (object state) inline static private
Definition at line 573 of file TransactionScope.cs.
    {
        if (!(state is TransactionScope transactionScope))
        {
            TransactionsEtwProvider log = TransactionsEtwProvider.Log;
            if (log.IsEnabled())
            {
                log.TransactionScopeInternalError("TransactionScopeTimerObjectInvalid");
            }
            throw TransactionException.Create(TraceSourceType.TraceSourceBase, System.SR.InternalError + System.SR.TransactionScopeTimerObjectInvalid, null);
        }
        transactionScope.Timeout();
    }
References System.Transactions.TransactionException.Create(), System.SR.InternalError, System.Diagnostics.Tracing.EventSource.IsEnabled(), System.Transactions.TransactionsEtwProvider.Log, System.state, System.Transactions.TransactionsEtwProvider.TransactionScopeInternalError(), and System.SR.TransactionScopeTimerObjectInvalid.
Referenced by System.Transactions.TransactionScope.TransactionScope(), System.Transactions.TransactionScope.TransactionScope(), System.Transactions.TransactionScope.TransactionScope(), and System.Transactions.TransactionScope.Initialize().