Terraria: System.Transactions.TransactionScope.PopScope
PopScope()
void System.Transactions.TransactionScope.PopScope () inline private
Definition at line 656 of file TransactionScope.cs.
    {
        bool flag = true;
        if (AsyncFlowEnabled)
        {
            CallContextCurrentData.ClearCurrentData(ContextKey, removeContextData: true);
        }
        if (_scopeThread == Thread.CurrentThread)
        {
            RestoreSavedTLSContextData();
        }
        if (_savedCurrentScope != null)
        {
            if (_savedCurrentScope.AsyncFlowEnabled)
            {
                _threadContextData = CallContextCurrentData.CreateOrGetCurrentData(_savedCurrentScope.ContextKey);
            }
            else
            {
                if (_savedCurrentScope._scopeThread != Thread.CurrentThread)
                {
                    flag = false;
                    ContextData.TLSCurrentData = null;
                }
                else
                {
                    _threadContextData = ContextData.TLSCurrentData;
                }
                CallContextCurrentData.ClearCurrentData(_savedCurrentScope.ContextKey, removeContextData: false);
            }
        }
        else
        {
            CallContextCurrentData.ClearCurrentData(null, removeContextData: false);
            if (_scopeThread != Thread.CurrentThread)
            {
                flag = false;
                ContextData.TLSCurrentData = null;
            }
            else
            {
                ContextData.TLSCurrentData = _threadContextData;
            }
        }
        if (flag)
        {
            _threadContextData.CurrentScope = _savedCurrentScope;
            RestoreCurrent();
        }
    }
References System.Transactions.TransactionScope._savedCurrentScope, System.Transactions.TransactionScope._scopeThread, System.Transactions.TransactionScope._threadContextData, System.Transactions.TransactionScope.AsyncFlowEnabled, System.Transactions.CallContextCurrentData.ClearCurrentData(), System.Transactions.TransactionScope.ContextKey, System.Transactions.CallContextCurrentData.CreateOrGetCurrentData(), System.Threading.Thread.CurrentThread, System.Transactions.TransactionScope.RestoreCurrent(), System.Transactions.TransactionScope.RestoreSavedTLSContextData(), and System.Transactions.ContextData.TLSCurrentData.
Referenced by System.Transactions.TransactionScope.Dispose(), and System.Transactions.TransactionScope.InternalDispose().