Terraria: System.Transactions.TransactionScope.CommonInitialize
CommonInitialize()
void System.Transactions.TransactionScope.CommonInitialize () inline private
Definition at line 618 of file TransactionScope.cs.
    {
        ContextKey = new ContextKey();
        _complete = false;
        _dependentTransaction = null;
        _disposed = false;
        _committableTransaction = null;
        _expectedCurrent = null;
        _scopeTimer = null;
        _scopeThread = Thread.CurrentThread;
        Transaction.GetCurrentTransactionAndScope(AsyncFlowEnabled ? TxLookup.DefaultCallContext : TxLookup.DefaultTLS, out _savedCurrent, out _savedCurrentScope, out _contextTransaction);
        ValidateAsyncFlowOptionAndESInteropOption();
    }
References System.Transactions.TransactionScope._committableTransaction, System.Transactions.TransactionScope._complete, System.Transactions.TransactionScope._contextTransaction, System.Transactions.TransactionScope._dependentTransaction, System.Transactions.TransactionScope._disposed, System.Transactions.TransactionScope._expectedCurrent, System.Transactions.TransactionScope._savedCurrent, System.Transactions.TransactionScope._savedCurrentScope, System.Transactions.TransactionScope._scopeThread, System.Transactions.TransactionScope._scopeTimer, System.Transactions.TransactionScope.AsyncFlowEnabled, System.Transactions.TransactionScope.ContextKey, System.Threading.Thread.CurrentThread, System.Transactions.Transaction.GetCurrentTransactionAndScope(), and System.Transactions.TransactionScope.ValidateAsyncFlowOptionAndESInteropOption().
Referenced by System.Transactions.TransactionScope.Initialize(), and System.Transactions.TransactionScope.NeedToCreateTransaction().