Terraria: System.Transactions.TransactionScope.PushScope
PushScope()
void System.Transactions.TransactionScope.PushScope () inline private
Definition at line 632 of file TransactionScope.cs.
    {
        if (!_interopModeSpecified)
        {
            _interopOption = Transaction.InteropMode(_savedCurrentScope);
        }
        SaveTLSContextData();
        if (AsyncFlowEnabled)
        {
            _threadContextData = CallContextCurrentData.CreateOrGetCurrentData(ContextKey);
            if (_savedCurrentScope == null && _savedCurrent == null)
            {
                ContextData.TLSCurrentData = null;
            }
        }
        else
        {
            _threadContextData = ContextData.TLSCurrentData;
            CallContextCurrentData.ClearCurrentData(ContextKey, removeContextData: false);
        }
        SetCurrent(_expectedCurrent);
        _threadContextData.CurrentScope = this;
    }
References System.Transactions.TransactionScope._expectedCurrent, System.Transactions.TransactionScope._interopModeSpecified, System.Transactions.TransactionScope._interopOption, System.Transactions.TransactionScope._savedCurrent, System.Transactions.TransactionScope._savedCurrentScope, System.Transactions.TransactionScope._threadContextData, System.Transactions.TransactionScope.AsyncFlowEnabled, System.Transactions.CallContextCurrentData.ClearCurrentData(), System.Transactions.CallContextCurrentData.CreateOrGetCurrentData(), System.Transactions.Transaction.InteropMode(), System.Transactions.TransactionScope.SaveTLSContextData(), System.Transactions.TransactionScope.SetCurrent(), and System.Transactions.ContextData.TLSCurrentData.
Referenced by System.Transactions.TransactionScope.TransactionScope(), System.Transactions.TransactionScope.TransactionScope(), System.Transactions.TransactionScope.TransactionScope(), System.Transactions.TransactionScope.TransactionScope(), and System.Transactions.TransactionScope.Initialize().