Terraria: System.Xml.Schema.Compiler.CleanupParticle
CleanupParticle()
void System.Xml.Schema.Compiler.CleanupParticle (XmlSchemaParticle particle) inline private
Definition at line 395 of file Compiler.cs.
    {
        if (particle is XmlSchemaElement element)
        {
            CleanupElement(element);
        }
        else if (particle is XmlSchemaGroupBase xmlSchemaGroupBase)
        {
            for (int i = 0; i < xmlSchemaGroupBase.Items.Count; i++)
            {
                CleanupParticle((XmlSchemaParticle)xmlSchemaGroupBase.Items[i]);
            }
        }
    }
References System.Xml.Schema.Compiler.CleanupElement(), System.Xml.Schema.Compiler.CleanupParticle(), and System.Collections.Generic.Dictionary< TKey, TValue >.Count.
Referenced by System.Xml.Schema.Compiler.CleanupComplexType(), System.Xml.Schema.Compiler.CleanupGroup(), and System.Xml.Schema.Compiler.CleanupParticle().