Terraria: System.Xml.Schema.Compiler._attributes
_attributes
readonly XmlSchemaObjectTable System.Xml.Schema.Compiler._attributes = new XmlSchemaObjectTable() private
Definition at line 12 of file Compiler.cs.
Referenced by System.Xml.Schema.Compiler.Compile(), System.Xml.Schema.Compiler.CompileAttribute(), System.Xml.Schema.Compiler.Execute(), System.Xml.Schema.Compiler.Output(), and System.Xml.Schema.Compiler.Prepare().