Terraria: System.Xml.Schema.Compiler.IsGroupBaseFromAny
IsGroupBaseFromAny()
bool System.Xml.Schema.Compiler.IsGroupBaseFromAny (XmlSchemaGroupBase derivedGroupBase, XmlSchemaAny baseAny) inline private
Definition at line 1543 of file Compiler.cs.
    {
        CalculateEffectiveTotalRange(derivedGroupBase, out var minOccurs, out var maxOccurs);
        if (!IsValidOccurrenceRangeRestriction(minOccurs, maxOccurs, baseAny.MinOccurs, baseAny.MaxOccurs))
        {
            _restrictionErrorMsg = System.SR.Format(System.SR.Sch_GroupBaseFromAny2, derivedGroupBase.LineNumber.ToString(NumberFormatInfo.InvariantInfo), derivedGroupBase.LinePosition.ToString(NumberFormatInfo.InvariantInfo), baseAny.LineNumber.ToString(NumberFormatInfo.InvariantInfo), baseAny.LinePosition.ToString(NumberFormatInfo.InvariantInfo));
            return false;
        }
        string minOccursString = baseAny.MinOccursString;
        baseAny.MinOccurs = 0m;
        for (int i = 0; i < derivedGroupBase.Items.Count; i++)
        {
            if (!IsValidRestriction((XmlSchemaParticle)derivedGroupBase.Items[i], baseAny))
            {
                _restrictionErrorMsg = System.SR.Sch_GroupBaseFromAny1;
                baseAny.MinOccursString = minOccursString;
                return false;
            }
        }
        baseAny.MinOccursString = minOccursString;
        return true;
    }
References System.Xml.Schema.Compiler._restrictionErrorMsg, System.Xml.Schema.Compiler.CalculateEffectiveTotalRange(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Xml.Dictionary, System.SR.Format(), System.Globalization.NumberFormatInfo.InvariantInfo, System.Xml.Schema.Compiler.IsValidOccurrenceRangeRestriction(), System.Xml.Schema.Compiler.IsValidRestriction(), System.SR.Sch_GroupBaseFromAny1, and System.SR.Sch_GroupBaseFromAny2.
Referenced by System.Xml.Schema.Compiler.IsValidRestriction().