Terraria: System.Xml.Schema.Compiler.CompileSimpleContentRestriction
CompileSimpleContentRestriction()
void System.Xml.Schema.Compiler.CompileSimpleContentRestriction (XmlSchemaComplexType complexType, XmlSchemaSimpleContentRestriction simpleRestriction) inline private
Definition at line 852 of file Compiler.cs.
    {
        XmlSchemaComplexType xmlSchemaComplexType = null;
        XmlSchemaDatatype xmlSchemaDatatype = null;
        if (complexType.Redefined != null && simpleRestriction.BaseTypeName == complexType.Redefined.QualifiedName)
        {
            xmlSchemaComplexType = (XmlSchemaComplexType)complexType.Redefined;
            CompileComplexType(xmlSchemaComplexType);
            xmlSchemaDatatype = xmlSchemaComplexType.Datatype;
        }
        else
        {
            xmlSchemaComplexType = GetComplexType(simpleRestriction.BaseTypeName);
            if (xmlSchemaComplexType == null)
            {
                SendValidationEvent(System.SR.Sch_UndefBaseRestriction, simpleRestriction.BaseTypeName.ToString(), simpleRestriction);
                return;
            }
            if (xmlSchemaComplexType.ContentType == XmlSchemaContentType.TextOnly)
            {
                if (simpleRestriction.BaseType == null)
                {
                    xmlSchemaDatatype = xmlSchemaComplexType.Datatype;
                }
                else
                {
                    CompileSimpleType(simpleRestriction.BaseType);
                    if (!XmlSchemaType.IsDerivedFromDatatype(simpleRestriction.BaseType.Datatype, xmlSchemaComplexType.Datatype, XmlSchemaDerivationMethod.None))
                    {
                        SendValidationEvent(System.SR.Sch_DerivedNotFromBase, simpleRestriction);
                    }
                    xmlSchemaDatatype = simpleRestriction.BaseType.Datatype;
                }
            }
            else if (xmlSchemaComplexType.ContentType == XmlSchemaContentType.Mixed && xmlSchemaComplexType.ElementDecl.ContentValidator.IsEmptiable)
            {
                if (simpleRestriction.BaseType != null)
                {
                    CompileSimpleType(simpleRestriction.BaseType);
                    complexType.SetBaseSchemaType(simpleRestriction.BaseType);
                    xmlSchemaDatatype = simpleRestriction.BaseType.Datatype;
                }
                else
                {
                    SendValidationEvent(System.SR.Sch_NeedSimpleTypeChild, simpleRestriction);
                }
            }
            else
            {
                SendValidationEvent(System.SR.Sch_NotSimpleContent, complexType);
            }
        }
        if (xmlSchemaComplexType != null && xmlSchemaComplexType.ElementDecl != null && (xmlSchemaComplexType.FinalResolved & XmlSchemaDerivationMethod.Restriction) != 0)
        {
            SendValidationEvent(System.SR.Sch_BaseFinalRestriction, complexType);
        }
        if (xmlSchemaComplexType != null)
        {
            complexType.SetBaseSchemaType(xmlSchemaComplexType);
        }
        if (xmlSchemaDatatype != null)
        {
            try
            {
                complexType.SetDatatype(xmlSchemaDatatype.DeriveByRestriction(simpleRestriction.Facets, base.NameTable, complexType));
            }
            catch (XmlSchemaException ex)
            {
                if (ex.SourceSchemaObject == null)
                {
                    ex.SetSource(complexType);
                }
                SendValidationEvent(ex);
                complexType.SetDatatype(DatatypeImplementation.AnySimpleType.Datatype);
            }
        }
        complexType.SetDerivedBy(XmlSchemaDerivationMethod.Restriction);
        CompileLocalAttributes(xmlSchemaComplexType, complexType, simpleRestriction.Attributes, simpleRestriction.AnyAttribute, XmlSchemaDerivationMethod.Restriction);
    }
References System.Xml.Schema.DatatypeImplementation.AnySimpleType, System.Xml.Schema.Compiler.CompileComplexType(), System.Xml.Schema.Compiler.CompileLocalAttributes(), System.Xml.Schema.Compiler.CompileSimpleType(), System.Xml.Schema.Compiler.GetComplexType(), System.Xml.Schema.XmlSchemaType.IsDerivedFromDatatype(), System.SR.Sch_BaseFinalRestriction, System.SR.Sch_DerivedNotFromBase, System.SR.Sch_NeedSimpleTypeChild, System.SR.Sch_NotSimpleContent, System.SR.Sch_UndefBaseRestriction, and System.Xml.Schema.BaseProcessor.SendValidationEvent().
Referenced by System.Xml.Schema.Compiler.CompileComplexType().