Terraria: System.Xml.Schema.Compiler.CleanupElement
CleanupElement()
void System.Xml.Schema.Compiler.CleanupElement (XmlSchemaElement element) inline private
Definition at line 353 of file Compiler.cs.
    {
        if (element.SchemaType != null)
        {
            if (element.SchemaType is XmlSchemaComplexType complexType)
            {
                CleanupComplexType(complexType);
            }
            else
            {
                CleanupSimpleType((XmlSchemaSimpleType)element.SchemaType);
            }
        }
        for (int i = 0; i < element.Constraints.Count; i++)
        {
            ((XmlSchemaIdentityConstraint)element.Constraints[i]).CompiledConstraint = null;
        }
        element.ElementDecl = null;
        element.IsLocalTypeDerivationChecked = false;
    }
References System.Xml.Schema.Compiler.CleanupComplexType(), System.Xml.Schema.Compiler.CleanupSimpleType(), System.Xml.Schema.XmlSchemaElement.Constraints, System.Collections.CollectionBase.Count, System.Xml.Dictionary, and System.Xml.Schema.XmlSchemaElement.SchemaType.
Referenced by System.Xml.Schema.Compiler.CleanupParticle(), and System.Xml.Schema.Compiler.Prepare().