Terraria: System.Xml.Schema.Compiler.IsSequenceFromChoice
IsSequenceFromChoice()
bool System.Xml.Schema.Compiler.IsSequenceFromChoice (XmlSchemaSequence derivedSequence, XmlSchemaChoice baseChoice) inline private
Definition at line 1691 of file Compiler.cs.
    {
        decimal minOccurs = derivedSequence.MinOccurs * (decimal)derivedSequence.Items.Count;
        decimal maxOccurs = ((!(derivedSequence.MaxOccurs == decimal.MaxValue)) ? (derivedSequence.MaxOccurs * (decimal)derivedSequence.Items.Count) : decimal.MaxValue);
        if (!IsValidOccurrenceRangeRestriction(minOccurs, maxOccurs, baseChoice.MinOccurs, baseChoice.MaxOccurs))
        {
            return false;
        }
        for (int i = 0; i < derivedSequence.Items.Count; i++)
        {
            if (GetMappingParticle((XmlSchemaParticle)derivedSequence.Items[i], baseChoice.Items) < 0)
            {
                return false;
            }
        }
        return true;
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Xml.Dictionary, System.Xml.Schema.Compiler.GetMappingParticle(), and System.Xml.Schema.Compiler.IsValidOccurrenceRangeRestriction().
Referenced by System.Xml.Schema.Compiler.IsValidRestriction().