Terraria: System.Xml.Schema.Compiler.IsGroupBaseFromGroupBase
IsGroupBaseFromGroupBase()
bool System.Xml.Schema.Compiler.IsGroupBaseFromGroupBase (XmlSchemaGroupBase derivedGroupBase, XmlSchemaGroupBase baseGroupBase, bool skipEmptableOnly) inline private
Definition at line 1624 of file Compiler.cs.
    {
        if (!IsValidOccurrenceRangeRestriction(derivedGroupBase, baseGroupBase))
        {
            _restrictionErrorMsg = System.SR.Sch_GroupBaseRestRangeInvalid;
            return false;
        }
        if (derivedGroupBase.Items.Count > baseGroupBase.Items.Count)
        {
            _restrictionErrorMsg = System.SR.Sch_GroupBaseRestNoMap;
            return false;
        }
        int num = 0;
        for (int i = 0; i < baseGroupBase.Items.Count; i++)
        {
            XmlSchemaParticle xmlSchemaParticle = (XmlSchemaParticle)baseGroupBase.Items[i];
            if (num < derivedGroupBase.Items.Count && IsValidRestriction((XmlSchemaParticle)derivedGroupBase.Items[num], xmlSchemaParticle))
            {
                num++;
            }
            else if (skipEmptableOnly && !IsParticleEmptiable(xmlSchemaParticle))
            {
                if (_restrictionErrorMsg == null)
                {
                    _restrictionErrorMsg = System.SR.Sch_GroupBaseRestNotEmptiable;
                }
                return false;
            }
        }
        if (num < derivedGroupBase.Items.Count)
        {
            return false;
        }
        return true;
    }
References System.Xml.Schema.Compiler._restrictionErrorMsg, System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Xml.Schema.Compiler.IsParticleEmptiable(), System.Xml.Schema.Compiler.IsValidOccurrenceRangeRestriction(), System.Xml.Schema.Compiler.IsValidRestriction(), System.SR.Sch_GroupBaseRestNoMap, System.SR.Sch_GroupBaseRestNotEmptiable, and System.SR.Sch_GroupBaseRestRangeInvalid.
Referenced by System.Xml.Schema.Compiler.IsElementFromGroupBase(), and System.Xml.Schema.Compiler.IsValidRestriction().