Terraria: System.Transactions.TransactionScope.SetCurrent
SetCurrent()
void System.Transactions.TransactionScope.SetCurrent (Transaction newCurrent) inline private
Definition at line 707 of file TransactionScope.cs.
    {
        if (_dependentTransaction == null && _committableTransaction == null && newCurrent != null)
        {
            _dependentTransaction = newCurrent.DependentClone(DependentCloneOption.RollbackIfNotComplete);
        }
        switch (_interopOption)
        {
        case EnterpriseServicesInteropOption.None:
            _threadContextData.CurrentTransaction = newCurrent;
            break;
        case EnterpriseServicesInteropOption.Automatic:
            EnterpriseServices.VerifyEnterpriseServicesOk();
            if (EnterpriseServices.UseServiceDomainForCurrent())
            {
            }
            _threadContextData.CurrentTransaction = newCurrent;
            break;
        case EnterpriseServicesInteropOption.Full:
            EnterpriseServices.VerifyEnterpriseServicesOk();
            EnterpriseServices.PushServiceDomain(newCurrent);
            break;
        }
    }
References System.Transactions.TransactionScope._committableTransaction, System.Transactions.TransactionScope._dependentTransaction, System.Transactions.TransactionScope._interopOption, System.Transactions.Transaction.DependentClone(), System.Transactions.EnterpriseServices.PushServiceDomain(), System.Transactions.EnterpriseServices.UseServiceDomainForCurrent(), and System.Transactions.EnterpriseServices.VerifyEnterpriseServicesOk().
Referenced by System.Transactions.TransactionScope.PushScope().