Terraria: System.Transactions.TransactionScope.TransactionScope
TransactionScope() [6/14]
System.Transactions.TransactionScope.TransactionScope (TransactionScopeOption scopeOption, TimeSpan scopeTimeout, TransactionScopeAsyncFlowOption asyncFlowOption) inline
Definition at line 100 of file TransactionScope.cs.
    {
        TransactionsEtwProvider log = TransactionsEtwProvider.Log;
        if (log.IsEnabled())
        {
            log.MethodEnter(TraceSourceType.TraceSourceBase, this, ".ctor");
        }
        ValidateScopeTimeout("scopeTimeout", scopeTimeout);
        TimeSpan timeout = TransactionManager.ValidateTimeout(scopeTimeout);
        ValidateAndSetAsyncFlowOption(asyncFlowOption);
        if (NeedToCreateTransaction(scopeOption))
        {
            _committableTransaction = new CommittableTransaction(timeout);
            _expectedCurrent = _committableTransaction.Clone();
        }
        if (null != _expectedCurrent && null == _committableTransaction && TimeSpan.Zero != scopeTimeout)
        {
            _scopeTimer = new Timer(TimerCallback, this, scopeTimeout, TimeSpan.Zero);
        }
        if (null == _expectedCurrent)
        {
            if (log.IsEnabled())
            {
                log.TransactionScopeCreated(TransactionTraceIdentifier.Empty, TransactionScopeResult.NoTransaction);
            }
        }
        else
        {
            TransactionScopeResult transactionScopeResult = ((null == _committableTransaction) ? TransactionScopeResult.UsingExistingCurrent : TransactionScopeResult.CreatedTransaction);
            if (log.IsEnabled())
            {
                log.TransactionScopeCreated(_expectedCurrent.TransactionTraceId, transactionScopeResult);
            }
        }
        PushScope();
        if (log.IsEnabled())
        {
            log.MethodExit(TraceSourceType.TraceSourceBase, this, ".ctor");
        }
    }
References System.Transactions.TransactionScope._committableTransaction, System.Transactions.TransactionScope._expectedCurrent, System.Transactions.TransactionScope._scopeTimer, System.Transactions.Transaction.Clone(), System.Transactions.TransactionTraceIdentifier.Empty, System.Diagnostics.Tracing.EventSource.IsEnabled(), System.Transactions.TransactionsEtwProvider.Log, System.Transactions.TransactionsEtwProvider.MethodEnter(), System.Transactions.TransactionsEtwProvider.MethodExit(), System.Transactions.TransactionScope.NeedToCreateTransaction(), System.Transactions.TransactionScope.PushScope(), System.timeout, System.Transactions.TransactionScope.TimerCallback(), System.Transactions.TransactionsEtwProvider.TransactionScopeCreated(), System.Transactions.Transaction.TransactionTraceId, System.Transactions.TransactionScope.ValidateAndSetAsyncFlowOption(), System.Transactions.TransactionScope.ValidateScopeTimeout(), System.Transactions.TransactionManager.ValidateTimeout(), and System.TimeSpan.Zero.