Terraria: System.Transactions.TransactionScope.TransactionScope
TransactionScope() [14/14]
System.Transactions.TransactionScope.TransactionScope (Transaction transactionToUse, TimeSpan scopeTimeout, EnterpriseServicesInteropOption interopOption) inline
Definition at line 282 of file TransactionScope.cs.
    {
        TransactionsEtwProvider log = TransactionsEtwProvider.Log;
        if (log.IsEnabled())
        {
            log.MethodEnter(TraceSourceType.TraceSourceBase, this, ".ctor");
        }
        ValidateInteropOption(interopOption);
        _interopOption = interopOption;
        Initialize(transactionToUse, scopeTimeout, interopModeSpecified: true);
        if (log.IsEnabled())
        {
            log.MethodExit(TraceSourceType.TraceSourceBase, this, ".ctor");
        }
    }
References System.Transactions.TransactionScope._interopOption, System.Transactions.TransactionScope.Initialize(), System.Diagnostics.Tracing.EventSource.IsEnabled(), System.Transactions.TransactionsEtwProvider.Log, System.Transactions.TransactionsEtwProvider.MethodEnter(), System.Transactions.TransactionsEtwProvider.MethodExit(), and System.Transactions.TransactionScope.ValidateInteropOption().