Terraria: System.Xml.Schema.Compiler.CompileAttribute
CompileAttribute()
void System.Xml.Schema.Compiler.CompileAttribute (XmlSchemaAttribute xa) inline private
Definition at line 2133 of file Compiler.cs.
    {
        if (xa.IsProcessing)
        {
            SendValidationEvent(System.SR.Sch_AttributeCircularRef, xa);
        }
        else
        {
            if (xa.AttDef != null)
            {
                return;
            }
            xa.IsProcessing = true;
            SchemaAttDef schemaAttDef = null;
            try
            {
                if (!xa.RefName.IsEmpty)
                {
                    XmlSchemaAttribute xmlSchemaAttribute = (XmlSchemaAttribute)_attributes[xa.RefName];
                    if (xmlSchemaAttribute == null)
                    {
                        throw new XmlSchemaException(System.SR.Sch_UndeclaredAttribute, xa.RefName.ToString(), xa);
                    }
                    CompileAttribute(xmlSchemaAttribute);
                    if (xmlSchemaAttribute.AttDef == null)
                    {
                        throw new XmlSchemaException(System.SR.Sch_RefInvalidAttribute, xa.RefName.ToString(), xa);
                    }
                    schemaAttDef = xmlSchemaAttribute.AttDef.Clone();
                    XmlSchemaDatatype datatype = schemaAttDef.Datatype;
                    if (datatype != null)
                    {
                        if (xmlSchemaAttribute.FixedValue == null && xmlSchemaAttribute.DefaultValue == null)
{
                            SetDefaultFixed(xa, schemaAttDef);
                        }
                        else if (xmlSchemaAttribute.FixedValue != null)
{
                            if (xa.DefaultValue != null)
{
                                throw new XmlSchemaException(System.SR.Sch_FixedDefaultInRef, xa.RefName.ToString(), xa);
                            }
                            if (xa.FixedValue != null)
{
                                object o = datatype.ParseValue(xa.FixedValue, base.NameTable, new SchemaNamespaceManager(xa), createAtomicValue: true);
                                if (!datatype.IsEqual(schemaAttDef.DefaultValueTyped, o))
{
                                    throw new XmlSchemaException(System.SR.Sch_FixedInRef, xa.RefName.ToString(), xa);
                                }
                            }
                        }
                    }
                    xa.SetAttributeType(xmlSchemaAttribute.AttributeSchemaType);
                }
                else
                {
                    schemaAttDef = new SchemaAttDef(xa.QualifiedName);
                    if (xa.SchemaType != null)
                    {
                        CompileSimpleType(xa.SchemaType);
                        xa.SetAttributeType(xa.SchemaType);
                        schemaAttDef.SchemaType = xa.SchemaType;
                        schemaAttDef.Datatype = xa.SchemaType.Datatype;
                    }
                    else if (!xa.SchemaTypeName.IsEmpty)
                    {
                        XmlSchemaSimpleType simpleType = GetSimpleType(xa.SchemaTypeName);
                        if (simpleType == null)
{
                            throw new XmlSchemaException(System.SR.Sch_UndeclaredSimpleType, xa.SchemaTypeName.ToString(), xa);
                        }
                        xa.SetAttributeType(simpleType);
                        schemaAttDef.Datatype = simpleType.Datatype;
                        schemaAttDef.SchemaType = simpleType;
                    }
                    else
                    {
                        schemaAttDef.SchemaType = DatatypeImplementation.AnySimpleType;
                        schemaAttDef.Datatype = DatatypeImplementation.AnySimpleType.Datatype;
                        xa.SetAttributeType(DatatypeImplementation.AnySimpleType);
                    }
                    if (schemaAttDef.Datatype != null)
                    {
                        schemaAttDef.Datatype.VerifySchemaValid(_notations, xa);
                    }
                    SetDefaultFixed(xa, schemaAttDef);
                }
                schemaAttDef.SchemaAttribute = xa;
                xa.AttDef = schemaAttDef;
            }
            catch (XmlSchemaException ex)
            {
                if (ex.SourceSchemaObject == null)
                {
                    ex.SetSource(xa);
                }
                SendValidationEvent(ex);
                xa.AttDef = SchemaAttDef.Empty;
            }
            finally
            {
                xa.IsProcessing = false;
            }
        }
    }
References System.Xml.Schema.Compiler._attributes, System.Xml.Schema.Compiler._notations, System.Xml.Schema.DatatypeImplementation.AnySimpleType, System.Xml.Schema.Compiler.CompileAttribute(), System.Xml.Schema.Compiler.CompileSimpleType(), System.Xml.Dictionary, System.Xml.Schema.SchemaAttDef.Empty, System.Xml.Schema.Compiler.GetSimpleType(), System.Xml.Schema.XmlSchemaDatatype.IsEqual(), System.Xml.Schema.XmlSchemaDatatype.ParseValue(), System.SR.Sch_AttributeCircularRef, System.SR.Sch_FixedDefaultInRef, System.SR.Sch_FixedInRef, System.SR.Sch_RefInvalidAttribute, System.SR.Sch_UndeclaredAttribute, System.SR.Sch_UndeclaredSimpleType, System.Xml.Schema.BaseProcessor.SendValidationEvent(), and System.Xml.Schema.Compiler.SetDefaultFixed().
Referenced by System.Xml.Schema.Compiler.Compile(), System.Xml.Schema.Compiler.CompileAttribute(), System.Xml.Schema.Compiler.CompileAttributeGroup(), and System.Xml.Schema.Compiler.CompileLocalAttributes().