Terraria: System.Xml.Schema.Compiler.IsElementFromGroupBase
IsElementFromGroupBase()
bool System.Xml.Schema.Compiler.IsElementFromGroupBase (XmlSchemaElement derivedElement, XmlSchemaGroupBase baseGroupBase) inline private
Definition at line 1566 of file Compiler.cs.
    {
        if (baseGroupBase is XmlSchemaSequence)
        {
            XmlSchemaSequence xmlSchemaSequence = new XmlSchemaSequence();
            xmlSchemaSequence.MinOccurs = 1m;
            xmlSchemaSequence.MaxOccurs = 1m;
            xmlSchemaSequence.Items.Add(derivedElement);
            if (IsGroupBaseFromGroupBase(xmlSchemaSequence, baseGroupBase, skipEmptableOnly: true))
            {
                return true;
            }
            _restrictionErrorMsg = System.SR.Format(System.SR.Sch_ElementFromGroupBase1, derivedElement.QualifiedName.ToString(), derivedElement.LineNumber.ToString(NumberFormatInfo.InvariantInfo), derivedElement.LinePosition.ToString(NumberFormatInfo.InvariantInfo), baseGroupBase.LineNumber.ToString(NumberFormatInfo.InvariantInfo), baseGroupBase.LinePosition.ToString(NumberFormatInfo.InvariantInfo));
        }
        else if (baseGroupBase is XmlSchemaChoice)
        {
            XmlSchemaChoice xmlSchemaChoice = new XmlSchemaChoice();
            xmlSchemaChoice.MinOccurs = 1m;
            xmlSchemaChoice.MaxOccurs = 1m;
            xmlSchemaChoice.Items.Add(derivedElement);
            if (IsGroupBaseFromGroupBase(xmlSchemaChoice, baseGroupBase, skipEmptableOnly: false))
            {
                return true;
            }
            _restrictionErrorMsg = System.SR.Format(System.SR.Sch_ElementFromGroupBase2, derivedElement.QualifiedName.ToString(), derivedElement.LineNumber.ToString(NumberFormatInfo.InvariantInfo), derivedElement.LinePosition.ToString(NumberFormatInfo.InvariantInfo), baseGroupBase.LineNumber.ToString(NumberFormatInfo.InvariantInfo), baseGroupBase.LinePosition.ToString(NumberFormatInfo.InvariantInfo));
        }
        else if (baseGroupBase is XmlSchemaAll)
        {
            XmlSchemaAll xmlSchemaAll = new XmlSchemaAll();
            xmlSchemaAll.MinOccurs = 1m;
            xmlSchemaAll.MaxOccurs = 1m;
            xmlSchemaAll.Items.Add(derivedElement);
            if (IsGroupBaseFromGroupBase(xmlSchemaAll, baseGroupBase, skipEmptableOnly: true))
            {
                return true;
            }
            _restrictionErrorMsg = System.SR.Format(System.SR.Sch_ElementFromGroupBase3, derivedElement.QualifiedName.ToString(), derivedElement.LineNumber.ToString(NumberFormatInfo.InvariantInfo), derivedElement.LinePosition.ToString(NumberFormatInfo.InvariantInfo), baseGroupBase.LineNumber.ToString(NumberFormatInfo.InvariantInfo), baseGroupBase.LinePosition.ToString(NumberFormatInfo.InvariantInfo));
        }
        return false;
    }
References System.Xml.Schema.Compiler._restrictionErrorMsg, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Xml.Dictionary, System.SR.Format(), System.Globalization.NumberFormatInfo.InvariantInfo, System.Xml.Schema.Compiler.IsGroupBaseFromGroupBase(), System.SR.Sch_ElementFromGroupBase1, System.SR.Sch_ElementFromGroupBase2, and System.SR.Sch_ElementFromGroupBase3.
Referenced by System.Xml.Schema.Compiler.IsValidRestriction().