Terraria: System.Xml.Schema.Compiler.CleanupComplexType
CleanupComplexType()
void System.Xml.Schema.Compiler.CleanupComplexType (XmlSchemaComplexType complexType) inline private
Definition at line 285 of file Compiler.cs.
    {
        if (complexType.QualifiedName == DatatypeImplementation.QnAnyType)
        {
            return;
        }
        if (complexType.ContentModel != null)
        {
            if (complexType.ContentModel is XmlSchemaSimpleContent)
            {
                XmlSchemaSimpleContent xmlSchemaSimpleContent = (XmlSchemaSimpleContent)complexType.ContentModel;
                if (xmlSchemaSimpleContent.Content is XmlSchemaSimpleContentExtension)
                {
                    XmlSchemaSimpleContentExtension xmlSchemaSimpleContentExtension = (XmlSchemaSimpleContentExtension)xmlSchemaSimpleContent.Content;
                    CleanupAttributes(xmlSchemaSimpleContentExtension.Attributes);
                }
                else
                {
                    XmlSchemaSimpleContentRestriction xmlSchemaSimpleContentRestriction = (XmlSchemaSimpleContentRestriction)xmlSchemaSimpleContent.Content;
                    CleanupAttributes(xmlSchemaSimpleContentRestriction.Attributes);
                }
            }
            else
            {
                XmlSchemaComplexContent xmlSchemaComplexContent = (XmlSchemaComplexContent)complexType.ContentModel;
                if (xmlSchemaComplexContent.Content is XmlSchemaComplexContentExtension)
                {
                    XmlSchemaComplexContentExtension xmlSchemaComplexContentExtension = (XmlSchemaComplexContentExtension)xmlSchemaComplexContent.Content;
                    CleanupParticle(xmlSchemaComplexContentExtension.Particle);
                    CleanupAttributes(xmlSchemaComplexContentExtension.Attributes);
                }
                else
                {
                    XmlSchemaComplexContentRestriction xmlSchemaComplexContentRestriction = (XmlSchemaComplexContentRestriction)xmlSchemaComplexContent.Content;
                    CleanupParticle(xmlSchemaComplexContentRestriction.Particle);
                    CleanupAttributes(xmlSchemaComplexContentRestriction.Attributes);
                }
            }
        }
        else
        {
            CleanupParticle(complexType.Particle);
            CleanupAttributes(complexType.Attributes);
        }
        complexType.LocalElements.Clear();
        complexType.AttributeUses.Clear();
        complexType.SetAttributeWildcard(null);
        complexType.SetContentTypeParticle(XmlSchemaParticle.Empty);
        complexType.ElementDecl = null;
        complexType.HasWildCard = false;
        if (complexType.Redefined != null)
        {
            CleanupComplexType(complexType.Redefined as XmlSchemaComplexType);
        }
    }
References System.Xml.Schema.Compiler.CleanupAttributes(), System.Xml.Schema.Compiler.CleanupComplexType(), System.Xml.Schema.Compiler.CleanupParticle(), System.Collections.Generic.Dictionary< TKey, TValue >.Clear(), System.Xml.Dictionary, System.Xml.Schema.XmlSchemaParticle.Empty, and System.Xml.Schema.DatatypeImplementation.QnAnyType.
Referenced by System.Xml.Schema.Compiler.CleanupComplexType(), System.Xml.Schema.Compiler.CleanupElement(), and System.Xml.Schema.Compiler.Prepare().