Terraria: System.Xml.Schema.Compiler.CompileSubstitutionGroup
CompileSubstitutionGroup()
void System.Xml.Schema.Compiler.CompileSubstitutionGroup (XmlSchemaSubstitutionGroup substitutionGroup) inline private
Definition at line 446 of file Compiler.cs.
    {
        if (substitutionGroup.IsProcessing && substitutionGroup.Members.Count > 0)
        {
            SendValidationEvent(System.SR.Sch_SubstitutionCircularRef, (XmlSchemaElement)substitutionGroup.Members[0]);
            return;
        }
        XmlSchemaElement xmlSchemaElement = (XmlSchemaElement)_elements[substitutionGroup.Examplar];
        if (substitutionGroup.Members.Contains(xmlSchemaElement))
        {
            return;
        }
        substitutionGroup.IsProcessing = true;
        try
        {
            if (xmlSchemaElement.FinalResolved == XmlSchemaDerivationMethod.All)
            {
                SendValidationEvent(System.SR.Sch_InvalidExamplar, xmlSchemaElement.Name, xmlSchemaElement);
            }
            ArrayList arrayList = null;
            for (int i = 0; i < substitutionGroup.Members.Count; i++)
            {
                XmlSchemaElement xmlSchemaElement2 = (XmlSchemaElement)substitutionGroup.Members[i];
                if ((xmlSchemaElement2.ElementDecl.Block & XmlSchemaDerivationMethod.Substitution) != 0)
                {
                    continue;
                }
                XmlSchemaSubstitutionGroup xmlSchemaSubstitutionGroup = (XmlSchemaSubstitutionGroup)_examplars[xmlSchemaElement2.QualifiedName];
                if (xmlSchemaSubstitutionGroup == null)
                {
                    continue;
                }
                CompileSubstitutionGroup(xmlSchemaSubstitutionGroup);
                for (int j = 0; j < xmlSchemaSubstitutionGroup.Members.Count; j++)
                {
                    if (xmlSchemaSubstitutionGroup.Members[j] != xmlSchemaElement2)
                    {
                        if (arrayList == null)
{
                            arrayList = new ArrayList();
                        }
                        arrayList.Add(xmlSchemaSubstitutionGroup.Members[j]);
                    }
                }
            }
            if (arrayList != null)
            {
                for (int k = 0; k < arrayList.Count; k++)
                {
                    substitutionGroup.Members.Add(arrayList[k]);
                }
            }
            substitutionGroup.Members.Add(xmlSchemaElement);
        }
        finally
        {
            substitutionGroup.IsProcessing = false;
        }
    }
References System.Xml.Schema.Compiler._elements, System.Xml.Schema.Compiler._examplars, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Xml.Schema.Compiler.CompileSubstitutionGroup(), System.Collections.Generic.Dictionary< TKey, TValue >.Contains(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Xml.Dictionary, System.SR.Sch_InvalidExamplar, System.SR.Sch_SubstitutionCircularRef, and System.Xml.Schema.BaseProcessor.SendValidationEvent().
Referenced by System.Xml.Schema.Compiler.CompileSubstitutionGroup(), and System.Xml.Schema.Compiler.ProcessSubstitutionGroups().