Terraria: System.Xml.Schema.Compiler.CompileElement
CompileElement()
void System.Xml.Schema.Compiler.CompileElement (XmlSchemaElement xe) inline private
Definition at line 2349 of file Compiler.cs.
    {
        if (xe.IsProcessing)
        {
            SendValidationEvent(System.SR.Sch_ElementCircularRef, xe);
        }
        else
        {
            if (xe.ElementDecl != null)
            {
                return;
            }
            xe.IsProcessing = true;
            SchemaElementDecl schemaElementDecl = null;
            try
            {
                if (!xe.RefName.IsEmpty)
                {
                    XmlSchemaElement xmlSchemaElement = (XmlSchemaElement)_elements[xe.RefName];
                    if (xmlSchemaElement == null)
                    {
                        throw new XmlSchemaException(System.SR.Sch_UndeclaredElement, xe.RefName.ToString(), xe);
                    }
                    CompileElement(xmlSchemaElement);
                    if (xmlSchemaElement.ElementDecl == null)
                    {
                        throw new XmlSchemaException(System.SR.Sch_RefInvalidElement, xe.RefName.ToString(), xe);
                    }
                    xe.SetElementType(xmlSchemaElement.ElementSchemaType);
                    schemaElementDecl = xmlSchemaElement.ElementDecl.Clone();
                }
                else
                {
                    if (xe.SchemaType != null)
                    {
                        xe.SetElementType(xe.SchemaType);
                    }
                    else if (!xe.SchemaTypeName.IsEmpty)
                    {
                        xe.SetElementType(GetAnySchemaType(xe.SchemaTypeName));
                        if (xe.ElementSchemaType == null)
{
                            throw new XmlSchemaException(System.SR.Sch_UndeclaredType, xe.SchemaTypeName.ToString(), xe);
                        }
                    }
                    else if (!xe.SubstitutionGroup.IsEmpty)
                    {
                        XmlSchemaElement xmlSchemaElement2 = (XmlSchemaElement)_elements[xe.SubstitutionGroup];
                        if (xmlSchemaElement2 == null)
{
                            throw new XmlSchemaException(System.SR.Sch_UndeclaredEquivClass, xe.SubstitutionGroup.Name, xe);
                        }
                        if (xmlSchemaElement2.IsProcessing)
{
                            return;
                        }
                        CompileElement(xmlSchemaElement2);
                        if (xmlSchemaElement2.ElementDecl == null)
{
                            xe.SetElementType(XmlSchemaComplexType.AnyType);
                            schemaElementDecl = XmlSchemaComplexType.AnyType.ElementDecl.Clone();
                        }
                        else
{
                            xe.SetElementType(xmlSchemaElement2.ElementSchemaType);
                            schemaElementDecl = xmlSchemaElement2.ElementDecl.Clone();
                        }
                    }
                    else
                    {
                        xe.SetElementType(XmlSchemaComplexType.AnyType);
                        schemaElementDecl = XmlSchemaComplexType.AnyType.ElementDecl.Clone();
                    }
                    if (schemaElementDecl == null)
                    {
                        if (xe.ElementSchemaType is XmlSchemaComplexType)
{
                            XmlSchemaComplexType xmlSchemaComplexType = (XmlSchemaComplexType)xe.ElementSchemaType;
                            CompileComplexType(xmlSchemaComplexType);
                            if (xmlSchemaComplexType.ElementDecl != null)
{
                                schemaElementDecl = xmlSchemaComplexType.ElementDecl.Clone();
                            }
                        }
                        else if (xe.ElementSchemaType is XmlSchemaSimpleType)
{
                            XmlSchemaSimpleType xmlSchemaSimpleType = (XmlSchemaSimpleType)xe.ElementSchemaType;
                            CompileSimpleType(xmlSchemaSimpleType);
                            if (xmlSchemaSimpleType.ElementDecl != null)
{
                                schemaElementDecl = xmlSchemaSimpleType.ElementDecl.Clone();
                            }
                        }
                    }
                    schemaElementDecl.Name = xe.QualifiedName;
                    schemaElementDecl.IsAbstract = xe.IsAbstract;
                    if (xe.ElementSchemaType is XmlSchemaComplexType xmlSchemaComplexType2)
                    {
                        schemaElementDecl.IsAbstract |= xmlSchemaComplexType2.IsAbstract;
                    }
                    schemaElementDecl.IsNillable = xe.IsNillable;
                    schemaElementDecl.Block |= xe.BlockResolved;
                }
                if (schemaElementDecl.Datatype != null)
                {
                    schemaElementDecl.Datatype.VerifySchemaValid(_notations, xe);
                }
                if ((xe.DefaultValue != null || xe.FixedValue != null) && schemaElementDecl.ContentValidator != null)
                {
                    if (schemaElementDecl.ContentValidator.ContentType != 0 && (schemaElementDecl.ContentValidator.ContentType != XmlSchemaContentType.Mixed || !schemaElementDecl.ContentValidator.IsEmptiable))
                    {
                        throw new XmlSchemaException(System.SR.Sch_ElementCannotHaveValue, xe);
                    }
                    if (xe.DefaultValue != null)
                    {
                        schemaElementDecl.Presence = SchemaDeclBase.Use.Default;
                        schemaElementDecl.DefaultValueRaw = xe.DefaultValue;
                    }
                    else
                    {
                        schemaElementDecl.Presence = SchemaDeclBase.Use.Fixed;
                        schemaElementDecl.DefaultValueRaw = xe.FixedValue;
                    }
                    if (schemaElementDecl.Datatype != null)
                    {
                        if (schemaElementDecl.Datatype.TypeCode == XmlTypeCode.Id)
{
                            SendValidationEvent(System.SR.Sch_DefaultIdValue, xe);
                        }
                        else
{
                            schemaElementDecl.DefaultValueTyped = schemaElementDecl.Datatype.ParseValue(schemaElementDecl.DefaultValueRaw, base.NameTable, new SchemaNamespaceManager(xe), createAtomicValue: true);
                        }
                    }
                    else
                    {
                        schemaElementDecl.DefaultValueTyped = DatatypeImplementation.AnySimpleType.Datatype.ParseValue(schemaElementDecl.DefaultValueRaw, base.NameTable, new SchemaNamespaceManager(xe));
                    }
                }
                if (xe.HasConstraints)
                {
                    XmlSchemaObjectCollection constraints = xe.Constraints;
                    CompiledIdentityConstraint[] array = new CompiledIdentityConstraint[constraints.Count];
                    int num = 0;
                    for (int i = 0; i < constraints.Count; i++)
                    {
                        XmlSchemaIdentityConstraint xmlSchemaIdentityConstraint = (XmlSchemaIdentityConstraint)constraints[i];
                        CompileIdentityConstraint(xmlSchemaIdentityConstraint);
                        array[num++] = xmlSchemaIdentityConstraint.CompiledConstraint;
                    }
                    schemaElementDecl.Constraints = array;
                }
                schemaElementDecl.SchemaElement = xe;
                xe.ElementDecl = schemaElementDecl;
            }
            catch (XmlSchemaException ex)
            {
                if (ex.SourceSchemaObject == null)
                {
                    ex.SetSource(xe);
                }
                SendValidationEvent(ex);
                xe.ElementDecl = SchemaElementDecl.Empty;
            }
            finally
            {
                xe.IsProcessing = false;
            }
        }
    }
References System.Xml.Schema.Compiler._elements, System.Xml.Schema.Compiler._notations, System.Xml.Schema.DatatypeImplementation.AnySimpleType, System.Xml.Schema.XmlSchemaComplexType.AnyType, System.array, System.Xml.Schema.Compiler.CompileComplexType(), System.Xml.Schema.Compiler.CompileElement(), System.Xml.Schema.Compiler.CompileIdentityConstraint(), System.Xml.Schema.Compiler.CompileSimpleType(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Xml.Dictionary, System.Xml.Schema.SchemaElementDecl.Empty, System.Xml.Schema.Compiler.GetAnySchemaType(), System.SR.Sch_DefaultIdValue, System.SR.Sch_ElementCannotHaveValue, System.SR.Sch_ElementCircularRef, System.SR.Sch_RefInvalidElement, System.SR.Sch_UndeclaredElement, System.SR.Sch_UndeclaredEquivClass, System.SR.Sch_UndeclaredType, and System.Xml.Schema.BaseProcessor.SendValidationEvent().
Referenced by System.Xml.Schema.Compiler.Compile(), System.Xml.Schema.Compiler.CompileElement(), System.Xml.Schema.Compiler.CompileParticleElements(), and System.Xml.Schema.Compiler.CompileParticleElements().