Terraria: System.Xml.Schema.Compiler.IsElementFromElement
IsElementFromElement()
bool System.Xml.Schema.Compiler.IsElementFromElement (XmlSchemaElement derivedElement, XmlSchemaElement baseElement) inline private
Definition at line 1496 of file Compiler.cs.
    {
        XmlSchemaDerivationMethod xmlSchemaDerivationMethod = ((baseElement.ElementDecl.Block == XmlSchemaDerivationMethod.All) ? (XmlSchemaDerivationMethod.Substitution | XmlSchemaDerivationMethod.Extension | XmlSchemaDerivationMethod.Restriction) : baseElement.ElementDecl.Block);
        XmlSchemaDerivationMethod xmlSchemaDerivationMethod2 = ((derivedElement.ElementDecl.Block == XmlSchemaDerivationMethod.All) ? (XmlSchemaDerivationMethod.Substitution | XmlSchemaDerivationMethod.Extension | XmlSchemaDerivationMethod.Restriction) : derivedElement.ElementDecl.Block);
        if (!(derivedElement.QualifiedName == baseElement.QualifiedName) || (!baseElement.IsNillable && derivedElement.IsNillable) || !IsValidOccurrenceRangeRestriction(derivedElement, baseElement) || (baseElement.FixedValue != null && !IsFixedEqual(baseElement.ElementDecl, derivedElement.ElementDecl)) || (xmlSchemaDerivationMethod2 | xmlSchemaDerivationMethod) != xmlSchemaDerivationMethod2 || derivedElement.ElementSchemaType == null || baseElement.ElementSchemaType == null || !XmlSchemaType.IsDerivedFrom(derivedElement.ElementSchemaType, baseElement.ElementSchemaType, ~(XmlSchemaDerivationMethod.Restriction | XmlSchemaDerivationMethod.List | XmlSchemaDerivationMethod.Union)))
        {
            _restrictionErrorMsg = System.SR.Format(System.SR.Sch_ElementFromElement, derivedElement.QualifiedName, baseElement.QualifiedName);
            return false;
        }
        return true;
    }
References System.Xml.Schema.Compiler._restrictionErrorMsg, System.Xml.Dictionary, System.SR.Format(), System.Xml.Schema.XmlSchemaType.IsDerivedFrom(), System.Xml.Schema.Compiler.IsFixedEqual(), System.Xml.Schema.Compiler.IsValidOccurrenceRangeRestriction(), and System.SR.Sch_ElementFromElement.
Referenced by System.Xml.Schema.Compiler.IsValidRestriction().