Terraria: System.Xml.Schema.Compiler.CheckAtrributeGroupRestriction
CheckAtrributeGroupRestriction()
void System.Xml.Schema.Compiler.CheckAtrributeGroupRestriction (XmlSchemaAttributeGroup baseAttributeGroup, XmlSchemaAttributeGroup derivedAttributeGroup) inline private
Definition at line 2036 of file Compiler.cs.
    {
        XmlSchemaAnyAttribute attributeWildcard = baseAttributeGroup.AttributeWildcard;
        XmlSchemaAnyAttribute attributeWildcard2 = derivedAttributeGroup.AttributeWildcard;
        if (attributeWildcard2 != null && (attributeWildcard == null || !XmlSchemaAnyAttribute.IsSubset(attributeWildcard2, attributeWildcard) || !IsProcessContentsRestricted(null, attributeWildcard2, attributeWildcard)))
        {
            SendValidationEvent(System.SR.Sch_InvalidAnyAttributeRestriction, derivedAttributeGroup);
        }
        foreach (XmlSchemaAttribute value in baseAttributeGroup.AttributeUses.Values)
        {
            XmlSchemaAttribute xmlSchemaAttribute2 = (XmlSchemaAttribute)derivedAttributeGroup.AttributeUses[value.QualifiedName];
            if (xmlSchemaAttribute2 != null)
            {
                if (value.Use == XmlSchemaUse.Prohibited && xmlSchemaAttribute2.Use != XmlSchemaUse.Prohibited)
                {
                    SendValidationEvent(System.SR.Sch_AttributeRestrictionProhibited, xmlSchemaAttribute2);
                }
                else if (value.Use == XmlSchemaUse.Required && xmlSchemaAttribute2.Use != XmlSchemaUse.Required)
                {
                    SendValidationEvent(System.SR.Sch_AttributeUseInvalid, xmlSchemaAttribute2);
                }
                else if (xmlSchemaAttribute2.Use != XmlSchemaUse.Prohibited)
                {
                    if (value.AttributeSchemaType == null || xmlSchemaAttribute2.AttributeSchemaType == null || !XmlSchemaType.IsDerivedFrom(xmlSchemaAttribute2.AttributeSchemaType, value.AttributeSchemaType, XmlSchemaDerivationMethod.Empty))
                    {
                        SendValidationEvent(System.SR.Sch_AttributeRestrictionInvalid, xmlSchemaAttribute2);
                    }
                    else if (!IsFixedEqual(value.AttDef, xmlSchemaAttribute2.AttDef))
                    {
                        SendValidationEvent(System.SR.Sch_AttributeFixedInvalid, xmlSchemaAttribute2);
                    }
                }
            }
            else if (value.Use == XmlSchemaUse.Required)
            {
                SendValidationEvent(System.SR.Sch_NoDerivedAttribute, value.QualifiedName.ToString(), baseAttributeGroup.QualifiedName.ToString(), derivedAttributeGroup);
            }
        }
        foreach (XmlSchemaAttribute value2 in derivedAttributeGroup.AttributeUses.Values)
        {
            XmlSchemaAttribute xmlSchemaAttribute4 = (XmlSchemaAttribute)baseAttributeGroup.AttributeUses[value2.QualifiedName];
            if (xmlSchemaAttribute4 == null && (attributeWildcard == null || !attributeWildcard.Allows(value2.QualifiedName)))
            {
                SendValidationEvent(System.SR.Sch_AttributeRestrictionInvalidFromWildcard, value2);
            }
        }
    }
References System.Xml.Schema.XmlSchemaType.IsDerivedFrom(), System.Xml.Schema.Compiler.IsFixedEqual(), System.Xml.Schema.Compiler.IsProcessContentsRestricted(), System.Xml.Schema.XmlSchemaAnyAttribute.IsSubset(), System.SR.Sch_AttributeFixedInvalid, System.SR.Sch_AttributeRestrictionInvalid, System.SR.Sch_AttributeRestrictionInvalidFromWildcard, System.SR.Sch_AttributeRestrictionProhibited, System.SR.Sch_AttributeUseInvalid, System.SR.Sch_InvalidAnyAttributeRestriction, System.SR.Sch_NoDerivedAttribute, System.Xml.Schema.BaseProcessor.SendValidationEvent(), System.value, and System.Collections.Generic.Dictionary< TKey, TValue >.Values.
Referenced by System.Xml.Schema.Compiler.RecursivelyCheckRedefinedAttributeGroups().