Terraria: System.Xml.Schema.Compiler.ProcessSubstitutionGroups
ProcessSubstitutionGroups()
void System.Xml.Schema.Compiler.ProcessSubstitutionGroups () inline private
Definition at line 410 of file Compiler.cs.
    {
        foreach (XmlSchemaElement value in _elements.Values)
        {
            if (value.SubstitutionGroup.IsEmpty)
            {
                continue;
            }
            if (!(_elements[value.SubstitutionGroup] is XmlSchemaElement xmlSchemaElement2))
            {
                SendValidationEvent(System.SR.Sch_NoExamplar, value);
                continue;
            }
            if (!XmlSchemaType.IsDerivedFrom(value.ElementSchemaType, xmlSchemaElement2.ElementSchemaType, xmlSchemaElement2.FinalResolved))
            {
                SendValidationEvent(System.SR.Sch_InvalidSubstitutionMember, value.QualifiedName.ToString(), xmlSchemaElement2.QualifiedName.ToString(), value);
            }
            XmlSchemaSubstitutionGroup xmlSchemaSubstitutionGroup = (XmlSchemaSubstitutionGroup)_examplars[value.SubstitutionGroup];
            if (xmlSchemaSubstitutionGroup == null)
            {
                xmlSchemaSubstitutionGroup = new XmlSchemaSubstitutionGroup();
                xmlSchemaSubstitutionGroup.Examplar = value.SubstitutionGroup;
                _examplars.Add(value.SubstitutionGroup, xmlSchemaSubstitutionGroup);
            }
            ArrayList members = xmlSchemaSubstitutionGroup.Members;
            if (!members.Contains(value))
            {
                members.Add(value);
            }
        }
        foreach (XmlSchemaSubstitutionGroup value2 in _examplars.Values)
        {
            CompileSubstitutionGroup(value2);
        }
    }
References System.Xml.Schema.Compiler._elements, System.Xml.Schema.Compiler._examplars, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Xml.Schema.XmlSchemaObjectTable.Add(), System.Xml.Schema.Compiler.CompileSubstitutionGroup(), System.Collections.Generic.Dictionary< TKey, TValue >.Contains(), System.Xml.Dictionary, System.Xml.Schema.XmlSchemaType.IsDerivedFrom(), System.SR.Sch_InvalidSubstitutionMember, System.SR.Sch_NoExamplar, System.Xml.Schema.BaseProcessor.SendValidationEvent(), System.value, and System.Xml.Schema.XmlSchemaObjectTable.Values.
Referenced by System.Xml.Schema.Compiler.Compile().