Terraria: System.Xml.Schema.Compiler.CompileSimpleType
CompileSimpleType()
void System.Xml.Schema.Compiler.CompileSimpleType (XmlSchemaSimpleType simpleType) inline private
Definition at line 558 of file Compiler.cs.
    {
        if (simpleType.IsProcessing)
        {
            throw new XmlSchemaException(System.SR.Sch_TypeCircularRef, simpleType);
        }
        if (simpleType.ElementDecl != null)
        {
            return;
        }
        simpleType.IsProcessing = true;
        try
        {
            if (simpleType.Content is XmlSchemaSimpleTypeList)
            {
                XmlSchemaSimpleTypeList xmlSchemaSimpleTypeList = (XmlSchemaSimpleTypeList)simpleType.Content;
                simpleType.SetBaseSchemaType(DatatypeImplementation.AnySimpleType);
                XmlSchemaDatatype datatype;
                if (xmlSchemaSimpleTypeList.ItemTypeName.IsEmpty)
                {
                    CompileSimpleType(xmlSchemaSimpleTypeList.ItemType);
                    xmlSchemaSimpleTypeList.BaseItemType = xmlSchemaSimpleTypeList.ItemType;
                    datatype = xmlSchemaSimpleTypeList.ItemType.Datatype;
                }
                else
                {
                    XmlSchemaSimpleType simpleType2 = GetSimpleType(xmlSchemaSimpleTypeList.ItemTypeName);
                    if (simpleType2 == null)
                    {
                        throw new XmlSchemaException(System.SR.Sch_UndeclaredSimpleType, xmlSchemaSimpleTypeList.ItemTypeName.ToString(), xmlSchemaSimpleTypeList);
                    }
                    if ((simpleType2.FinalResolved & XmlSchemaDerivationMethod.List) != 0)
                    {
                        SendValidationEvent(System.SR.Sch_BaseFinalList, simpleType);
                    }
                    xmlSchemaSimpleTypeList.BaseItemType = simpleType2;
                    datatype = simpleType2.Datatype;
                }
                simpleType.SetDatatype(datatype.DeriveByList(simpleType));
                simpleType.SetDerivedBy(XmlSchemaDerivationMethod.List);
            }
            else if (simpleType.Content is XmlSchemaSimpleTypeRestriction)
            {
                XmlSchemaSimpleTypeRestriction xmlSchemaSimpleTypeRestriction = (XmlSchemaSimpleTypeRestriction)simpleType.Content;
                XmlSchemaDatatype datatype2;
                if (xmlSchemaSimpleTypeRestriction.BaseTypeName.IsEmpty)
                {
                    CompileSimpleType(xmlSchemaSimpleTypeRestriction.BaseType);
                    simpleType.SetBaseSchemaType(xmlSchemaSimpleTypeRestriction.BaseType);
                    datatype2 = xmlSchemaSimpleTypeRestriction.BaseType.Datatype;
                }
                else if (simpleType.Redefined != null && xmlSchemaSimpleTypeRestriction.BaseTypeName == simpleType.Redefined.QualifiedName)
                {
                    CompileSimpleType((XmlSchemaSimpleType)simpleType.Redefined);
                    simpleType.SetBaseSchemaType(simpleType.Redefined.BaseXmlSchemaType);
                    datatype2 = simpleType.Redefined.Datatype;
                }
                else
                {
                    if (xmlSchemaSimpleTypeRestriction.BaseTypeName.Equals(DatatypeImplementation.QnAnySimpleType))
                    {
                        XmlSchema parentSchema = Preprocessor.GetParentSchema(simpleType);
                        if (parentSchema.TargetNamespace != "http://www.w3.org/2001/XMLSchema")
{
                            throw new XmlSchemaException(System.SR.Sch_InvalidSimpleTypeRestriction, xmlSchemaSimpleTypeRestriction.BaseTypeName.ToString(), simpleType);
                        }
                    }
                    XmlSchemaSimpleType simpleType3 = GetSimpleType(xmlSchemaSimpleTypeRestriction.BaseTypeName);
                    if (simpleType3 == null)
                    {
                        throw new XmlSchemaException(System.SR.Sch_UndeclaredSimpleType, xmlSchemaSimpleTypeRestriction.BaseTypeName.ToString(), xmlSchemaSimpleTypeRestriction);
                    }
                    if ((simpleType3.FinalResolved & XmlSchemaDerivationMethod.Restriction) != 0)
                    {
                        SendValidationEvent(System.SR.Sch_BaseFinalRestriction, simpleType);
                    }
                    simpleType.SetBaseSchemaType(simpleType3);
                    datatype2 = simpleType3.Datatype;
                }
                simpleType.SetDatatype(datatype2.DeriveByRestriction(xmlSchemaSimpleTypeRestriction.Facets, base.NameTable, simpleType));
                simpleType.SetDerivedBy(XmlSchemaDerivationMethod.Restriction);
            }
            else
            {
                XmlSchemaSimpleType[] types = CompileBaseMemberTypes(simpleType);
                simpleType.SetBaseSchemaType(DatatypeImplementation.AnySimpleType);
                simpleType.SetDatatype(XmlSchemaDatatype.DeriveByUnion(types, simpleType));
                simpleType.SetDerivedBy(XmlSchemaDerivationMethod.Union);
            }
        }
        catch (XmlSchemaException ex)
        {
            if (ex.SourceSchemaObject == null)
            {
                ex.SetSource(simpleType);
            }
            SendValidationEvent(ex);
            simpleType.SetDatatype(DatatypeImplementation.AnySimpleType.Datatype);
        }
        finally
        {
            SchemaElementDecl schemaElementDecl = new SchemaElementDecl();
            schemaElementDecl.ContentValidator = ContentValidator.TextOnly;
            schemaElementDecl.SchemaType = simpleType;
            schemaElementDecl.Datatype = simpleType.Datatype;
            simpleType.ElementDecl = schemaElementDecl;
            simpleType.IsProcessing = false;
        }
    }
References System.Xml.Schema.DatatypeImplementation.AnySimpleType, System.Xml.Schema.Compiler.CompileBaseMemberTypes(), System.Xml.Schema.Compiler.CompileSimpleType(), System.Xml.Schema.XmlSchemaDatatype.DeriveByList(), System.Xml.Schema.XmlSchemaDatatype.DeriveByUnion(), System.Xml.Dictionary, System.Xml.Schema.Preprocessor.GetParentSchema(), System.Xml.Schema.Compiler.GetSimpleType(), System.Xml.Schema.DatatypeImplementation.QnAnySimpleType, System.SR.Sch_BaseFinalList, System.SR.Sch_BaseFinalRestriction, System.SR.Sch_InvalidSimpleTypeRestriction, System.SR.Sch_TypeCircularRef, System.SR.Sch_UndeclaredSimpleType, System.Xml.Schema.BaseProcessor.SendValidationEvent(), and System.Xml.Schema.ContentValidator.TextOnly.
Referenced by System.Xml.Schema.Compiler.Compile(), System.Xml.Schema.Compiler.CompileAttribute(), System.Xml.Schema.Compiler.CompileBaseMemberTypes(), System.Xml.Schema.Compiler.CompileElement(), System.Xml.Schema.Compiler.CompileSimpleContentRestriction(), System.Xml.Schema.Compiler.CompileSimpleType(), System.Xml.Schema.Compiler.GetAnySchemaType(), and System.Xml.Schema.Compiler.GetSimpleType().