Terraria: System.Xml.Schema.Compiler.IsValidRestriction
IsValidRestriction()
bool System.Xml.Schema.Compiler.IsValidRestriction (XmlSchemaParticle derivedParticle, XmlSchemaParticle baseParticle) inline private
Definition at line 1368 of file Compiler.cs.
    {
        if (derivedParticle == baseParticle)
        {
            return true;
        }
        if (derivedParticle == null || derivedParticle == XmlSchemaParticle.Empty)
        {
            return IsParticleEmptiable(baseParticle);
        }
        if (baseParticle == null || baseParticle == XmlSchemaParticle.Empty)
        {
            return false;
        }
        if (derivedParticle is XmlSchemaElement)
        {
            XmlSchemaElement element = (XmlSchemaElement)derivedParticle;
            derivedParticle = CannonicalizeElement(element);
        }
        if (baseParticle is XmlSchemaElement)
        {
            XmlSchemaElement xmlSchemaElement = (XmlSchemaElement)baseParticle;
            XmlSchemaParticle xmlSchemaParticle = CannonicalizeElement(xmlSchemaElement);
            if (xmlSchemaParticle is XmlSchemaChoice)
            {
                return IsValidRestriction(derivedParticle, xmlSchemaParticle);
            }
            if (derivedParticle is XmlSchemaElement)
            {
                return IsElementFromElement((XmlSchemaElement)derivedParticle, xmlSchemaElement);
            }
            _restrictionErrorMsg = System.SR.Sch_ForbiddenDerivedParticleForElem;
            return false;
        }
        if (baseParticle is XmlSchemaAny)
        {
            if (derivedParticle is XmlSchemaElement)
            {
                return IsElementFromAny((XmlSchemaElement)derivedParticle, (XmlSchemaAny)baseParticle);
            }
            if (derivedParticle is XmlSchemaAny)
            {
                return IsAnyFromAny((XmlSchemaAny)derivedParticle, (XmlSchemaAny)baseParticle);
            }
            return IsGroupBaseFromAny((XmlSchemaGroupBase)derivedParticle, (XmlSchemaAny)baseParticle);
        }
        if (baseParticle is XmlSchemaAll)
        {
            if (derivedParticle is XmlSchemaElement)
            {
                return IsElementFromGroupBase((XmlSchemaElement)derivedParticle, (XmlSchemaGroupBase)baseParticle);
            }
            if (derivedParticle is XmlSchemaAll)
            {
                if (IsGroupBaseFromGroupBase((XmlSchemaGroupBase)derivedParticle, (XmlSchemaGroupBase)baseParticle, skipEmptableOnly: true))
                {
                    return true;
                }
            }
            else if (derivedParticle is XmlSchemaSequence)
            {
                if (IsSequenceFromAll((XmlSchemaSequence)derivedParticle, (XmlSchemaAll)baseParticle))
                {
                    return true;
                }
                _restrictionErrorMsg = System.SR.Format(System.SR.Sch_SeqFromAll, derivedParticle.LineNumber.ToString(NumberFormatInfo.InvariantInfo), derivedParticle.LinePosition.ToString(NumberFormatInfo.InvariantInfo), baseParticle.LineNumber.ToString(NumberFormatInfo.InvariantInfo), baseParticle.LinePosition.ToString(NumberFormatInfo.InvariantInfo));
            }
            else if (derivedParticle is XmlSchemaChoice || derivedParticle is XmlSchemaAny)
            {
                _restrictionErrorMsg = System.SR.Sch_ForbiddenDerivedParticleForAll;
            }
            return false;
        }
        if (baseParticle is XmlSchemaChoice)
        {
            if (derivedParticle is XmlSchemaElement)
            {
                return IsElementFromGroupBase((XmlSchemaElement)derivedParticle, (XmlSchemaGroupBase)baseParticle);
            }
            if (derivedParticle is XmlSchemaChoice)
            {
                XmlSchemaChoice xmlSchemaChoice = baseParticle as XmlSchemaChoice;
                XmlSchemaChoice xmlSchemaChoice2 = derivedParticle as XmlSchemaChoice;
                if (xmlSchemaChoice.Parent == null || xmlSchemaChoice2.Parent == null)
                {
                    return IsChoiceFromChoiceSubstGroup(xmlSchemaChoice2, xmlSchemaChoice);
                }
                if (IsGroupBaseFromGroupBase(xmlSchemaChoice2, xmlSchemaChoice, skipEmptableOnly: false))
                {
                    return true;
                }
            }
            else if (derivedParticle is XmlSchemaSequence)
            {
                if (IsSequenceFromChoice((XmlSchemaSequence)derivedParticle, (XmlSchemaChoice)baseParticle))
                {
                    return true;
                }
                _restrictionErrorMsg = System.SR.Format(System.SR.Sch_SeqFromChoice, derivedParticle.LineNumber.ToString(NumberFormatInfo.InvariantInfo), derivedParticle.LinePosition.ToString(NumberFormatInfo.InvariantInfo), baseParticle.LineNumber.ToString(NumberFormatInfo.InvariantInfo), baseParticle.LinePosition.ToString(NumberFormatInfo.InvariantInfo));
            }
            else
            {
                _restrictionErrorMsg = System.SR.Sch_ForbiddenDerivedParticleForChoice;
            }
            return false;
        }
        if (baseParticle is XmlSchemaSequence)
        {
            if (derivedParticle is XmlSchemaElement)
            {
                return IsElementFromGroupBase((XmlSchemaElement)derivedParticle, (XmlSchemaGroupBase)baseParticle);
            }
            if (derivedParticle is XmlSchemaSequence || (derivedParticle is XmlSchemaAll && ((XmlSchemaGroupBase)derivedParticle).Items.Count == 1))
            {
                if (IsGroupBaseFromGroupBase((XmlSchemaGroupBase)derivedParticle, (XmlSchemaGroupBase)baseParticle, skipEmptableOnly: true))
                {
                    return true;
                }
            }
            else
            {
                _restrictionErrorMsg = System.SR.Sch_ForbiddenDerivedParticleForSeq;
            }
            return false;
        }
        return false;
    }
References System.Xml.Schema.Compiler._restrictionErrorMsg, System.Xml.Schema.Compiler.CannonicalizeElement(), System.Xml.Dictionary, System.Xml.Schema.XmlSchemaParticle.Empty, System.SR.Format(), System.Globalization.NumberFormatInfo.InvariantInfo, System.Xml.Schema.Compiler.IsAnyFromAny(), System.Xml.Schema.Compiler.IsChoiceFromChoiceSubstGroup(), System.Xml.Schema.Compiler.IsElementFromAny(), System.Xml.Schema.Compiler.IsElementFromElement(), System.Xml.Schema.Compiler.IsElementFromGroupBase(), System.Xml.Schema.Compiler.IsGroupBaseFromAny(), System.Xml.Schema.Compiler.IsGroupBaseFromGroupBase(), System.Xml.Schema.Compiler.IsParticleEmptiable(), System.Xml.Schema.Compiler.IsSequenceFromAll(), System.Xml.Schema.Compiler.IsSequenceFromChoice(), System.Xml.Schema.Compiler.IsValidRestriction(), System.SR.Sch_ForbiddenDerivedParticleForAll, System.SR.Sch_ForbiddenDerivedParticleForChoice, System.SR.Sch_ForbiddenDerivedParticleForElem, System.SR.Sch_ForbiddenDerivedParticleForSeq, System.SR.Sch_SeqFromAll, and System.SR.Sch_SeqFromChoice.
Referenced by System.Xml.Schema.Compiler.CheckParticleDerivation(), System.Xml.Schema.Compiler.CheckParticleDerivation(), System.Xml.Schema.Compiler.GetMappingParticle(), System.Xml.Schema.Compiler.IsGroupBaseFromAny(), System.Xml.Schema.Compiler.IsGroupBaseFromGroupBase(), and System.Xml.Schema.Compiler.IsValidRestriction().