Terraria: System.Xml.Schema.Compiler.CompileComplexContentRestriction
CompileComplexContentRestriction()
void System.Xml.Schema.Compiler.CompileComplexContentRestriction (XmlSchemaComplexType complexType, XmlSchemaComplexContent complexContent, XmlSchemaComplexContentRestriction complexRestriction) inline private
Definition at line 993 of file Compiler.cs.
    {
        XmlSchemaComplexType xmlSchemaComplexType = null;
        if (complexType.Redefined != null && complexRestriction.BaseTypeName == complexType.Redefined.QualifiedName)
        {
            xmlSchemaComplexType = (XmlSchemaComplexType)complexType.Redefined;
            CompileComplexType(xmlSchemaComplexType);
        }
        else
        {
            xmlSchemaComplexType = GetComplexType(complexRestriction.BaseTypeName);
            if (xmlSchemaComplexType == null)
            {
                SendValidationEvent(System.SR.Sch_UndefBaseRestriction, complexRestriction.BaseTypeName.ToString(), complexRestriction);
                return;
            }
        }
        complexType.SetBaseSchemaType(xmlSchemaComplexType);
        if ((xmlSchemaComplexType.FinalResolved & XmlSchemaDerivationMethod.Restriction) != 0)
        {
            SendValidationEvent(System.SR.Sch_BaseFinalRestriction, complexType);
        }
        CompileLocalAttributes(xmlSchemaComplexType, complexType, complexRestriction.Attributes, complexRestriction.AnyAttribute, XmlSchemaDerivationMethod.Restriction);
        complexType.SetContentTypeParticle(CompileContentTypeParticle(complexRestriction.Particle));
        XmlSchemaContentType schemaContentType = GetSchemaContentType(complexType, complexContent, complexType.ContentTypeParticle);
        complexType.SetContentType(schemaContentType);
        switch (schemaContentType)
        {
        case XmlSchemaContentType.Empty:
            if (xmlSchemaComplexType.ElementDecl != null && !xmlSchemaComplexType.ElementDecl.ContentValidator.IsEmptiable)
            {
                SendValidationEvent(System.SR.Sch_InvalidContentRestrictionDetailed, System.SR.Sch_InvalidBaseToEmpty, complexType);
            }
            break;
        case XmlSchemaContentType.Mixed:
            if (xmlSchemaComplexType.ContentType != XmlSchemaContentType.Mixed)
            {
                SendValidationEvent(System.SR.Sch_InvalidContentRestrictionDetailed, System.SR.Sch_InvalidBaseToMixed, complexType);
            }
            break;
        }
        complexType.SetDerivedBy(XmlSchemaDerivationMethod.Restriction);
    }
References System.Xml.Schema.Compiler.CompileComplexType(), System.Xml.Schema.Compiler.CompileContentTypeParticle(), System.Xml.Schema.Compiler.CompileLocalAttributes(), System.Xml.Schema.Compiler.GetComplexType(), System.Xml.Schema.Compiler.GetSchemaContentType(), System.SR.Sch_BaseFinalRestriction, System.SR.Sch_InvalidBaseToEmpty, System.SR.Sch_InvalidBaseToMixed, System.SR.Sch_InvalidContentRestrictionDetailed, System.SR.Sch_UndefBaseRestriction, and System.Xml.Schema.BaseProcessor.SendValidationEvent().
Referenced by System.Xml.Schema.Compiler.CompileComplexType().