Terraria: System.Xml.Schema.Compiler.CompileComplexContent
CompileComplexContent()
ContentValidator System.Xml.Schema.Compiler.CompileComplexContent (XmlSchemaComplexType complexType) inline private
Definition at line 2520 of file Compiler.cs.
    {
        if (complexType.ContentType == XmlSchemaContentType.Empty)
        {
            return ContentValidator.Empty;
        }
        if (complexType.ContentType == XmlSchemaContentType.TextOnly)
        {
            return ContentValidator.TextOnly;
        }
        XmlSchemaParticle contentTypeParticle = complexType.ContentTypeParticle;
        if (contentTypeParticle == null || contentTypeParticle == XmlSchemaParticle.Empty)
        {
            if (complexType.ContentType == XmlSchemaContentType.ElementOnly)
            {
                return ContentValidator.Empty;
            }
            return ContentValidator.Mixed;
        }
        PushComplexType(complexType);
        if (contentTypeParticle is XmlSchemaAll)
        {
            XmlSchemaAll xmlSchemaAll = (XmlSchemaAll)contentTypeParticle;
            AllElementsContentValidator allElementsContentValidator = new AllElementsContentValidator(complexType.ContentType, xmlSchemaAll.Items.Count, xmlSchemaAll.MinOccurs == 0m);
            for (int i = 0; i < xmlSchemaAll.Items.Count; i++)
            {
                XmlSchemaElement xmlSchemaElement = (XmlSchemaElement)xmlSchemaAll.Items[i];
                if (!allElementsContentValidator.AddElement(xmlSchemaElement.QualifiedName, xmlSchemaElement, xmlSchemaElement.MinOccurs == 0m))
                {
                    SendValidationEvent(System.SR.Sch_DupElement, xmlSchemaElement.QualifiedName.ToString(), xmlSchemaElement);
                }
            }
            return allElementsContentValidator;
        }
        ParticleContentValidator particleContentValidator = new ParticleContentValidator(complexType.ContentType, base.CompilationSettings.EnableUpaCheck);
        try
        {
            particleContentValidator.Start();
            complexType.HasWildCard = BuildParticleContentModel(particleContentValidator, contentTypeParticle);
            return particleContentValidator.Finish(useDFA: true);
        }
        catch (UpaException ex)
        {
            if (ex.Particle1 is XmlSchemaElement)
            {
                if (ex.Particle2 is XmlSchemaElement)
                {
                    SendValidationEvent(System.SR.Sch_NonDeterministic, ((XmlSchemaElement)ex.Particle1).QualifiedName.ToString(), (XmlSchemaElement)ex.Particle2);
                }
                else
                {
                    SendValidationEvent(System.SR.Sch_NonDeterministicAnyEx, ((XmlSchemaAny)ex.Particle2).ResolvedNamespace, ((XmlSchemaElement)ex.Particle1).QualifiedName.ToString(), (XmlSchemaAny)ex.Particle2);
                }
            }
            else if (ex.Particle2 is XmlSchemaElement)
            {
                SendValidationEvent(System.SR.Sch_NonDeterministicAnyEx, ((XmlSchemaAny)ex.Particle1).ResolvedNamespace, ((XmlSchemaElement)ex.Particle2).QualifiedName.ToString(), (XmlSchemaElement)ex.Particle2);
            }
            else
            {
                SendValidationEvent(System.SR.Sch_NonDeterministicAnyAny, ((XmlSchemaAny)ex.Particle1).ResolvedNamespace, ((XmlSchemaAny)ex.Particle2).ResolvedNamespace, (XmlSchemaAny)ex.Particle2);
            }
            return XmlSchemaComplexType.AnyTypeContentValidator;
        }
        catch (NotSupportedException)
        {
            SendValidationEvent(System.SR.Sch_ComplexContentModel, complexType, XmlSeverityType.Warning);
            return XmlSchemaComplexType.AnyTypeContentValidator;
        }
    }
References System.Xml.Schema.XmlSchemaComplexType.AnyTypeContentValidator, System.Xml.Schema.Compiler.BuildParticleContentModel(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Xml.Dictionary, System.Xml.Schema.ContentValidator.Empty, System.Xml.Schema.XmlSchemaParticle.Empty, System.Xml.Schema.ContentValidator.Mixed, System.Xml.Schema.Compiler.PushComplexType(), System.SR.Sch_ComplexContentModel, System.SR.Sch_DupElement, System.SR.Sch_NonDeterministic, System.SR.Sch_NonDeterministicAnyAny, System.SR.Sch_NonDeterministicAnyEx, System.Xml.Schema.BaseProcessor.SendValidationEvent(), and System.Xml.Schema.ContentValidator.TextOnly.
Referenced by System.Xml.Schema.Compiler.CompileComplexType().