Terraria: System.Xml.Schema.Compiler.Compile
Compile()
bool System.Xml.Schema.Compiler.Compile () inline package
Definition at line 178 of file Compiler.cs.
    {
        _schemaTypes.Insert(DatatypeImplementation.QnAnyType, XmlSchemaComplexType.AnyType);
        if (_schemaForSchema != null)
        {
            _schemaForSchema.SchemaTypes.Replace(DatatypeImplementation.QnAnyType, XmlSchemaComplexType.AnyType);
            UpdateSForSSimpleTypes();
        }
        foreach (XmlSchemaGroup value in _groups.Values)
        {
            CompileGroup(value);
        }
        foreach (XmlSchemaAttributeGroup value2 in _attributeGroups.Values)
        {
            CompileAttributeGroup(value2);
        }
        foreach (XmlSchemaType value3 in _schemaTypes.Values)
        {
            if (value3 is XmlSchemaComplexType complexType)
            {
                CompileComplexType(complexType);
            }
            else
            {
                CompileSimpleType((XmlSchemaSimpleType)value3);
            }
        }
        foreach (XmlSchemaElement value4 in _elements.Values)
        {
            if (value4.ElementDecl == null)
            {
                CompileElement(value4);
            }
        }
        foreach (XmlSchemaAttribute value5 in _attributes.Values)
        {
            if (value5.AttDef == null)
            {
                CompileAttribute(value5);
            }
        }
        foreach (XmlSchemaIdentityConstraint value6 in _identityConstraints.Values)
        {
            if (value6.CompiledConstraint == null)
            {
                CompileIdentityConstraint(value6);
            }
        }
        while (_complexTypeStack.Count > 0)
        {
            XmlSchemaComplexType complexType2 = _complexTypeStack.Pop();
            CompileComplexTypeElements(complexType2);
        }
        ProcessSubstitutionGroups();
        foreach (XmlSchemaType value7 in _schemaTypes.Values)
        {
            if (value7 is XmlSchemaComplexType complexType3)
            {
                CheckParticleDerivation(complexType3);
            }
        }
        foreach (XmlSchemaElement value8 in _elements.Values)
        {
            if (value8.ElementSchemaType is XmlSchemaComplexType complexType4 && value8.SchemaTypeName == XmlQualifiedName.Empty)
            {
                CheckParticleDerivation(complexType4);
            }
        }
        foreach (XmlSchemaGroup value9 in _groups.Values)
        {
            XmlSchemaGroup redefined = value9.Redefined;
            if (redefined != null)
            {
                RecursivelyCheckRedefinedGroups(value9, redefined);
            }
        }
        foreach (XmlSchemaAttributeGroup value10 in _attributeGroups.Values)
        {
            XmlSchemaAttributeGroup redefined2 = value10.Redefined;
            if (redefined2 != null)
            {
                RecursivelyCheckRedefinedAttributeGroups(value10, redefined2);
            }
        }
        return !base.HasErrors;
    }
References System.Xml.Schema.Compiler._attributeGroups, System.Xml.Schema.Compiler._attributes, System.Xml.Schema.Compiler._complexTypeStack, System.Xml.Schema.Compiler._elements, System.Xml.Schema.Compiler._groups, System.Xml.Schema.Compiler._identityConstraints, System.Xml.Schema.Compiler._schemaForSchema, System.Xml.Schema.Compiler._schemaTypes, System.Xml.Schema.XmlSchemaComplexType.AnyType, System.Xml.Schema.Compiler.CheckParticleDerivation(), System.Xml.Schema.Compiler.CompileAttribute(), System.Xml.Schema.Compiler.CompileAttributeGroup(), System.Xml.Schema.Compiler.CompileComplexType(), System.Xml.Schema.Compiler.CompileComplexTypeElements(), System.Xml.Schema.Compiler.CompileElement(), System.Xml.Schema.Compiler.CompileGroup(), System.Xml.Schema.Compiler.CompileIdentityConstraint(), System.Xml.Schema.Compiler.CompileSimpleType(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Xml.XmlQualifiedName.Empty, System.Xml.Schema.XmlSchemaObjectTable.Insert(), System.Xml.Schema.Compiler.ProcessSubstitutionGroups(), System.Xml.Schema.DatatypeImplementation.QnAnyType, System.Xml.Schema.Compiler.RecursivelyCheckRedefinedAttributeGroups(), System.Xml.Schema.Compiler.RecursivelyCheckRedefinedGroups(), System.Xml.Schema.XmlSchemaObjectTable.Replace(), System.Xml.Schema.XmlSchema.SchemaTypes, System.Xml.Schema.Compiler.UpdateSForSSimpleTypes(), System.value, and System.Xml.Schema.XmlSchemaObjectTable.Values.
Referenced by System.Xml.Schema.Compiler.Execute().