Terraria: System.Xml.Schema.Compiler.CannonicalizeParticle
CannonicalizeParticle()
XmlSchemaParticle System.Xml.Schema.Compiler.CannonicalizeParticle (XmlSchemaParticle particle, bool root) inline private
Definition at line 1106 of file Compiler.cs.
    {
        if (particle == null || particle.IsEmpty)
        {
            return XmlSchemaParticle.Empty;
        }
        if (particle is XmlSchemaElement)
        {
            return particle;
        }
        if (particle is XmlSchemaGroupRef)
        {
            return CannonicalizeGroupRef((XmlSchemaGroupRef)particle, root);
        }
        if (particle is XmlSchemaAll)
        {
            return CannonicalizeAll((XmlSchemaAll)particle, root);
        }
        if (particle is XmlSchemaChoice)
        {
            return CannonicalizeChoice((XmlSchemaChoice)particle, root);
        }
        if (particle is XmlSchemaSequence)
        {
            return CannonicalizeSequence((XmlSchemaSequence)particle, root);
        }
        return particle;
    }
References System.Xml.Schema.Compiler.CannonicalizeAll(), System.Xml.Schema.Compiler.CannonicalizeChoice(), System.Xml.Schema.Compiler.CannonicalizeGroupRef(), System.Xml.Schema.Compiler.CannonicalizeSequence(), System.Xml.Schema.XmlSchemaParticle.Empty, and System.Xml.Schema.XmlSchemaParticle.IsEmpty.
Referenced by System.Xml.Schema.Compiler.CannonicalizeAll(), System.Xml.Schema.Compiler.CannonicalizeChoice(), System.Xml.Schema.Compiler.CannonicalizeSequence(), System.Xml.Schema.Compiler.CompileComplexContentExtension(), System.Xml.Schema.Compiler.CompileContentTypeParticle(), System.Xml.Schema.Compiler.CompileGroup(), and System.Xml.Schema.Compiler.RecursivelyCheckRedefinedGroups().