Terraria: System.Transactions.TransactionScope.TransactionScope
TransactionScope() [9/14]
System.Transactions.TransactionScope.TransactionScope (TransactionScopeOption scopeOption, TransactionOptions transactionOptions, EnterpriseServicesInteropOption interopOption) inline
Definition at line 193 of file TransactionScope.cs.
    {
        TransactionsEtwProvider log = TransactionsEtwProvider.Log;
        if (log.IsEnabled())
        {
            log.MethodEnter(TraceSourceType.TraceSourceBase, this, ".ctor");
        }
        ValidateScopeTimeout("transactionOptions.Timeout", transactionOptions.Timeout);
        TimeSpan timeout = transactionOptions.Timeout;
        transactionOptions.Timeout = TransactionManager.ValidateTimeout(transactionOptions.Timeout);
        TransactionManager.ValidateIsolationLevel(transactionOptions.IsolationLevel);
        ValidateInteropOption(interopOption);
        _interopModeSpecified = true;
        _interopOption = interopOption;
        if (NeedToCreateTransaction(scopeOption))
        {
            _committableTransaction = new CommittableTransaction(transactionOptions);
            _expectedCurrent = _committableTransaction.Clone();
        }
        else if (null != _expectedCurrent && IsolationLevel.Unspecified != transactionOptions.IsolationLevel && _expectedCurrent.IsolationLevel != transactionOptions.IsolationLevel)
        {
            throw new ArgumentException(System.SR.TransactionScopeIsolationLevelDifferentFromTransaction, "transactionOptions");
        }
        if (null != _expectedCurrent && null == _committableTransaction && TimeSpan.Zero != timeout)
        {
            _scopeTimer = new Timer(TimerCallback, this, timeout, TimeSpan.Zero);
        }
        if (null == _expectedCurrent)
        {
            if (log.IsEnabled())
            {
                log.TransactionScopeCreated(TransactionTraceIdentifier.Empty, TransactionScopeResult.NoTransaction);
            }
        }
        else
        {
            TransactionScopeResult transactionScopeResult = ((null == _committableTransaction) ? TransactionScopeResult.UsingExistingCurrent : TransactionScopeResult.CreatedTransaction);
            if (log.IsEnabled())
            {
                log.TransactionScopeCreated(_expectedCurrent.TransactionTraceId, transactionScopeResult);
            }
        }
        PushScope();
        if (log.IsEnabled())
        {
            log.MethodExit(TraceSourceType.TraceSourceBase, this, ".ctor");
        }
    }
References System.Transactions.TransactionScope._committableTransaction, System.Transactions.TransactionScope._expectedCurrent, System.Transactions.TransactionScope._interopModeSpecified, System.Transactions.TransactionScope._interopOption, System.Transactions.TransactionScope._scopeTimer, System.Transactions.Transaction.Clone(), System.Transactions.TransactionTraceIdentifier.Empty, System.Diagnostics.Tracing.EventSource.IsEnabled(), System.Transactions.Transaction.IsolationLevel, System.Transactions.TransactionOptions.IsolationLevel, System.Transactions.TransactionsEtwProvider.Log, System.Transactions.TransactionsEtwProvider.MethodEnter(), System.Transactions.TransactionsEtwProvider.MethodExit(), System.Transactions.TransactionScope.NeedToCreateTransaction(), System.Transactions.TransactionScope.PushScope(), System.timeout, System.Transactions.TransactionOptions.Timeout, System.Transactions.TransactionScope.TimerCallback(), System.Transactions.TransactionsEtwProvider.TransactionScopeCreated(), System.SR.TransactionScopeIsolationLevelDifferentFromTransaction, System.Transactions.Transaction.TransactionTraceId, System.Transactions.TransactionScope.ValidateInteropOption(), System.Transactions.TransactionManager.ValidateIsolationLevel(), System.Transactions.TransactionScope.ValidateScopeTimeout(), System.Transactions.TransactionManager.ValidateTimeout(), and System.TimeSpan.Zero.