Terraria: System.Xml.Schema.Compiler.CompileComplexContentExtension
CompileComplexContentExtension()
void System.Xml.Schema.Compiler.CompileComplexContentExtension (XmlSchemaComplexType complexType, XmlSchemaComplexContent complexContent, XmlSchemaComplexContentExtension complexExtension) inline private
Definition at line 932 of file Compiler.cs.
    {
        XmlSchemaComplexType xmlSchemaComplexType = null;
        if (complexType.Redefined != null && complexExtension.BaseTypeName == complexType.Redefined.QualifiedName)
        {
            xmlSchemaComplexType = (XmlSchemaComplexType)complexType.Redefined;
            CompileComplexType(xmlSchemaComplexType);
        }
        else
        {
            xmlSchemaComplexType = GetComplexType(complexExtension.BaseTypeName);
            if (xmlSchemaComplexType == null)
            {
                SendValidationEvent(System.SR.Sch_UndefBaseExtension, complexExtension.BaseTypeName.ToString(), complexExtension);
                return;
            }
        }
        if ((xmlSchemaComplexType.FinalResolved & XmlSchemaDerivationMethod.Extension) != 0)
        {
            SendValidationEvent(System.SR.Sch_BaseFinalExtension, complexType);
        }
        CompileLocalAttributes(xmlSchemaComplexType, complexType, complexExtension.Attributes, complexExtension.AnyAttribute, XmlSchemaDerivationMethod.Extension);
        XmlSchemaParticle contentTypeParticle = xmlSchemaComplexType.ContentTypeParticle;
        XmlSchemaParticle xmlSchemaParticle = CannonicalizeParticle(complexExtension.Particle, root: true);
        if (contentTypeParticle != XmlSchemaParticle.Empty)
        {
            if (xmlSchemaParticle != XmlSchemaParticle.Empty)
            {
                XmlSchemaSequence xmlSchemaSequence = new XmlSchemaSequence();
                xmlSchemaSequence.Items.Add(contentTypeParticle);
                xmlSchemaSequence.Items.Add(xmlSchemaParticle);
                complexType.SetContentTypeParticle(CompileContentTypeParticle(xmlSchemaSequence));
            }
            else
            {
                complexType.SetContentTypeParticle(contentTypeParticle);
            }
        }
        else
        {
            complexType.SetContentTypeParticle(xmlSchemaParticle);
        }
        XmlSchemaContentType xmlSchemaContentType = GetSchemaContentType(complexType, complexContent, xmlSchemaParticle);
        if (xmlSchemaContentType == XmlSchemaContentType.Empty)
        {
            xmlSchemaContentType = xmlSchemaComplexType.ContentType;
            if (xmlSchemaContentType == XmlSchemaContentType.TextOnly)
            {
                complexType.SetDatatype(xmlSchemaComplexType.Datatype);
            }
        }
        complexType.SetContentType(xmlSchemaContentType);
        if (xmlSchemaComplexType.ContentType != XmlSchemaContentType.Empty && complexType.ContentType != xmlSchemaComplexType.ContentType)
        {
            SendValidationEvent(System.SR.Sch_DifContentType, complexType);
            return;
        }
        complexType.SetBaseSchemaType(xmlSchemaComplexType);
        complexType.SetDerivedBy(XmlSchemaDerivationMethod.Extension);
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Xml.Schema.Compiler.CannonicalizeParticle(), System.Xml.Schema.Compiler.CompileComplexType(), System.Xml.Schema.Compiler.CompileContentTypeParticle(), System.Xml.Schema.Compiler.CompileLocalAttributes(), System.Xml.Schema.XmlSchemaParticle.Empty, System.Xml.Schema.Compiler.GetComplexType(), System.Xml.Schema.Compiler.GetSchemaContentType(), System.SR.Sch_BaseFinalExtension, System.SR.Sch_DifContentType, System.SR.Sch_UndefBaseExtension, and System.Xml.Schema.BaseProcessor.SendValidationEvent().
Referenced by System.Xml.Schema.Compiler.CompileComplexType().