Terraria: System.Transactions.TransactionScope.Initialize
Initialize()
void System.Transactions.TransactionScope.Initialize (Transaction transactionToUse, TimeSpan scopeTimeout, bool interopModeSpecified) inline private
Definition at line 324 of file TransactionScope.cs.
    {
        if (null == transactionToUse)
        {
            throw new ArgumentNullException("transactionToUse");
        }
        ValidateScopeTimeout("scopeTimeout", scopeTimeout);
        CommonInitialize();
        if (TimeSpan.Zero != scopeTimeout)
        {
            _scopeTimer = new Timer(TimerCallback, this, scopeTimeout, TimeSpan.Zero);
        }
        _expectedCurrent = transactionToUse;
        _interopModeSpecified = interopModeSpecified;
        TransactionsEtwProvider log = TransactionsEtwProvider.Log;
        if (log.IsEnabled())
        {
            log.TransactionScopeCreated(_expectedCurrent.TransactionTraceId, TransactionScopeResult.TransactionPassed);
        }
        PushScope();
    }
References System.Transactions.TransactionScope._expectedCurrent, System.Transactions.TransactionScope._interopModeSpecified, System.Transactions.TransactionScope._scopeTimer, System.Transactions.TransactionScope.CommonInitialize(), System.Diagnostics.Tracing.EventSource.IsEnabled(), System.Transactions.TransactionsEtwProvider.Log, System.Transactions.TransactionScope.PushScope(), System.Transactions.TransactionScope.TimerCallback(), System.Transactions.TransactionsEtwProvider.TransactionScopeCreated(), System.Transactions.Transaction.TransactionTraceId, System.Transactions.TransactionScope.ValidateScopeTimeout(), and System.TimeSpan.Zero.
Referenced by System.Transactions.TransactionScope.TransactionScope(), System.Transactions.TransactionScope.TransactionScope(), and System.Transactions.TransactionScope.TransactionScope().