Terraria: System.Xml.Schema.Compiler.IsFixedEqual
IsFixedEqual()
bool System.Xml.Schema.Compiler.IsFixedEqual (SchemaDeclBase baseDecl, SchemaDeclBase derivedDecl) inline private
Definition at line 2770 of file Compiler.cs.
    {
        if (baseDecl.Presence == SchemaDeclBase.Use.Fixed || baseDecl.Presence == SchemaDeclBase.Use.RequiredFixed)
        {
            object defaultValueTyped = baseDecl.DefaultValueTyped;
            if (derivedDecl.Presence != SchemaDeclBase.Use.Fixed && derivedDecl.Presence != SchemaDeclBase.Use.RequiredFixed)
            {
                return false;
            }
            object defaultValueTyped2 = derivedDecl.DefaultValueTyped;
            XmlSchemaDatatype datatype = baseDecl.Datatype;
            XmlSchemaDatatype datatype2 = derivedDecl.Datatype;
            if (datatype.Variety == XmlSchemaDatatypeVariety.Union)
            {
                if (datatype2.Variety == XmlSchemaDatatypeVariety.Union)
                {
                    if (!datatype2.IsEqual(defaultValueTyped, defaultValueTyped2))
                    {
                        return false;
                    }
                }
                else
                {
                    XsdSimpleValue xsdSimpleValue = baseDecl.DefaultValueTyped as XsdSimpleValue;
                    XmlSchemaDatatype datatype3 = xsdSimpleValue.XmlType.Datatype;
                    if (!datatype3.IsComparable(datatype2) || !datatype2.IsEqual(xsdSimpleValue.TypedValue, defaultValueTyped2))
                    {
                        return false;
                    }
                }
            }
            else if (!datatype2.IsEqual(defaultValueTyped, defaultValueTyped2))
            {
                return false;
            }
        }
        return true;
    }
References System.Xml.Dictionary, and System.Xml.Schema.XmlSchemaDatatype.Variety.
Referenced by System.Xml.Schema.Compiler.CheckAtrributeGroupRestriction(), System.Xml.Schema.Compiler.CompileLocalAttributes(), and System.Xml.Schema.Compiler.IsElementFromElement().