Terraria: System.Xml.Schema.Compiler.CompileAttributeGroup
CompileAttributeGroup()
void System.Xml.Schema.Compiler.CompileAttributeGroup (XmlSchemaAttributeGroup attributeGroup) inline private
Definition at line 1841 of file Compiler.cs.
    {
        if (attributeGroup.IsProcessing)
        {
            SendValidationEvent(System.SR.Sch_AttributeGroupCircularRef, attributeGroup);
        }
        else
        {
            if (attributeGroup.AttributeUses.Count > 0)
            {
                return;
            }
            attributeGroup.IsProcessing = true;
            XmlSchemaAnyAttribute xmlSchemaAnyAttribute = attributeGroup.AnyAttribute;
            try
            {
                for (int i = 0; i < attributeGroup.Attributes.Count; i++)
                {
                    if (attributeGroup.Attributes[i] is XmlSchemaAttribute xmlSchemaAttribute)
                    {
                        if (xmlSchemaAttribute.Use != XmlSchemaUse.Prohibited)
{
                            CompileAttribute(xmlSchemaAttribute);
                            if (attributeGroup.AttributeUses[xmlSchemaAttribute.QualifiedName] == null)
{
                                attributeGroup.AttributeUses.Add(xmlSchemaAttribute.QualifiedName, xmlSchemaAttribute);
                            }
                            else
{
                                SendValidationEvent(System.SR.Sch_DupAttributeUse, xmlSchemaAttribute.QualifiedName.ToString(), xmlSchemaAttribute);
                            }
                        }
                        continue;
                    }
                    XmlSchemaAttributeGroupRef xmlSchemaAttributeGroupRef = (XmlSchemaAttributeGroupRef)attributeGroup.Attributes[i];
                    XmlSchemaAttributeGroup xmlSchemaAttributeGroup = ((attributeGroup.Redefined == null || !(xmlSchemaAttributeGroupRef.RefName == attributeGroup.Redefined.QualifiedName)) ? ((XmlSchemaAttributeGroup)_attributeGroups[xmlSchemaAttributeGroupRef.RefName]) : attributeGroup.Redefined);
                    if (xmlSchemaAttributeGroup != null)
                    {
                        CompileAttributeGroup(xmlSchemaAttributeGroup);
                        foreach (XmlSchemaAttribute value in xmlSchemaAttributeGroup.AttributeUses.Values)
{
                            if (attributeGroup.AttributeUses[value.QualifiedName] == null)
{
                                attributeGroup.AttributeUses.Add(value.QualifiedName, value);
                            }
                            else
{
                                SendValidationEvent(System.SR.Sch_DupAttributeUse, value.QualifiedName.ToString(), value);
                            }
                        }
                        xmlSchemaAnyAttribute = CompileAnyAttributeIntersection(xmlSchemaAnyAttribute, xmlSchemaAttributeGroup.AttributeWildcard);
                    }
                    else
                    {
                        SendValidationEvent(System.SR.Sch_UndefAttributeGroupRef, xmlSchemaAttributeGroupRef.RefName.ToString(), xmlSchemaAttributeGroupRef);
                    }
                }
                attributeGroup.AttributeWildcard = xmlSchemaAnyAttribute;
            }
            finally
            {
                attributeGroup.IsProcessing = false;
            }
        }
    }
References System.Xml.Schema.Compiler._attributeGroups, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Xml.Schema.Compiler.CompileAnyAttributeIntersection(), System.Xml.Schema.Compiler.CompileAttribute(), System.Xml.Schema.Compiler.CompileAttributeGroup(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Xml.Dictionary, System.SR.Sch_AttributeGroupCircularRef, System.SR.Sch_DupAttributeUse, System.SR.Sch_UndefAttributeGroupRef, System.Xml.Schema.BaseProcessor.SendValidationEvent(), System.value, and System.Collections.Generic.Dictionary< TKey, TValue >.Values.
Referenced by System.Xml.Schema.Compiler.Compile(), System.Xml.Schema.Compiler.CompileAttributeGroup(), System.Xml.Schema.Compiler.CompileLocalAttributes(), and System.Xml.Schema.Compiler.RecursivelyCheckRedefinedAttributeGroups().