Terraria: Terraria.Utilities.FileUtilities.MoveToCloud
MoveToCloud()
static bool Terraria.Utilities.FileUtilities.MoveToCloud (string localPath, string cloudPath) inline static
Definition at line 155 of file FileUtilities.cs.
    {
        if (SocialAPI.Cloud == null)
        {
            return false;
        }
        WriteAllBytes(cloudPath, ReadAllBytes(localPath, cloud: false), cloud: true);
        Delete(localPath, cloud: false);
        return true;
    }
References Terraria.Social.SocialAPI.Cloud, System.Delete, Terraria.Utilities.FileUtilities.ReadAllBytes(), and Terraria.Utilities.FileUtilities.WriteAllBytes().
Referenced by Terraria.IO.PlayerFileData.MoveToCloud(), and Terraria.IO.WorldFileData.MoveToCloud().