Terraria: Terraria.Utilities.FileUtilities.Move
Move()
static void Terraria.Utilities.FileUtilities.Move (string source, string destination, bool cloud, bool overwrite = true, bool forceDeleteSourceFile = false) inline static
Definition at line 75 of file FileUtilities.cs.
    {
        Copy(source, destination, cloud, overwrite);
        Delete(source, cloud, forceDeleteSourceFile);
    }
References Terraria.Utilities.FileUtilities.Copy(), System.Delete, System.destination, and System.source.
Referenced by Terraria.IO.WorldFile.DoRollingBackups(), Terraria.Main.DrawMenu(), and Terraria.Player.GetFileData().