Terraria: Terraria.Utilities.FileUtilities.Copy
Copy()
static void Terraria.Utilities.FileUtilities.Copy (string source, string destination, bool cloud, bool overwrite = true) inline static
Definition at line 48 of file FileUtilities.cs.
    {
        if (!cloud)
        {
            try
            {
                File.Copy(source, destination, overwrite);
                return;
            }
            catch (IOException ex)
            {
                if (ex.GetType() != typeof(IOException))
                {
                    throw;
                }
                using FileStream fileStream = File.OpenRead(source);
                using FileStream destination2 = File.Create(destination);
                fileStream.CopyTo(destination2);
                return;
            }
        }
        if (SocialAPI.Cloud != null && (overwrite || !SocialAPI.Cloud.HasFile(destination)))
        {
            SocialAPI.Cloud.Write(destination, SocialAPI.Cloud.Read(source));
        }
    }
References Terraria.Social.SocialAPI.Cloud, System.IO.File.Copy(), System.IO.File.Create(), System.destination, System.Exception.GetType(), System.IO.File.OpenRead(), and System.source.
Referenced by Terraria.IO.WorldFileData.CopyToLocal(), Terraria.Player.InternalSavePlayerFile(), Terraria.Utilities.FileUtilities.Move(), Terraria.WorldGen.playWorldCallBack(), Terraria.Social.Steam.WorkshopHelper.UGCBased.WorldPublisherInstance.PrepareContentForUpdate(), and Terraria.WorldGen.serverLoadWorldCallBack().