Terraria: Terraria.Utilities.FileUtilities.RemoveReadOnlyAttribute
RemoveReadOnlyAttribute()
static void Terraria.Utilities.FileUtilities.RemoveReadOnlyAttribute (string path) inline static
Definition at line 135 of file FileUtilities.cs.
    {
        if (!File.Exists(path))
        {
            return;
        }
        try
        {
            FileAttributes attributes = File.GetAttributes(path);
            if ((attributes & FileAttributes.ReadOnly) == FileAttributes.ReadOnly)
            {
                attributes &= ~FileAttributes.ReadOnly;
                File.SetAttributes(path, attributes);
            }
        }
        catch (Exception)
        {
        }
    }
References System.IO.File.Exists(), System.IO.File.GetAttributes(), and System.IO.File.SetAttributes().
Referenced by Terraria.Utilities.FileUtilities.Write().