Terraria: Terraria.Utilities.FileUtilities.ProtectedInvoke
ProtectedInvoke()
static void Terraria.Utilities.FileUtilities.ProtectedInvoke (Action action) inline static
    {
        bool isBackground = Thread.CurrentThread.IsBackground;
        try
        {
            Thread.CurrentThread.IsBackground = false;
            action();
        }
        finally
        {
            Thread.CurrentThread.IsBackground = isBackground;
        }
    }
Referenced by Terraria.Achievements.AchievementManager.Save(), Terraria.Map.MapHelper.SaveMap(), Terraria.Player.SavePlayer(), and Terraria.IO.WorldFile.SaveWorld().