Terraria: Terraria.Utilities.FileUtilities.Delete
Delete()
static void Terraria.Utilities.FileUtilities.Delete (string path, bool cloud, bool forceDeleteFile = false) inline static
Definition at line 23 of file FileUtilities.cs.
    {
        if (cloud && SocialAPI.Cloud != null)
        {
            SocialAPI.Cloud.Delete(path);
        }
        else if (forceDeleteFile)
        {
            File.Delete(path);
        }
        else
        {
            Platform.Get<IPathService>().MoveToRecycleBin(path);
        }
    }
References Terraria.Social.SocialAPI.Cloud.
Referenced by Terraria.Main.ErasePlayer(), Terraria.Player.KillMeForGood(), Terraria.Achievements.AchievementManager.Load(), Terraria.Utilities.FileUtilities.Move(), Terraria.Utilities.FileUtilities.MoveToCloud(), Terraria.Utilities.FileUtilities.MoveToLocal(), Terraria.WorldGen.playWorldCallBack(), and Terraria.WorldGen.serverLoadWorldCallBack().