Terraria: Terraria.Utilities.FileUtilities.Write
Write()
static void Terraria.Utilities.FileUtilities.Write (string path, byte[] data, int length, bool cloud) inline static
Definition at line 115 of file FileUtilities.cs.
    {
        if (cloud && SocialAPI.Cloud != null)
        {
            SocialAPI.Cloud.Write(path, data, length);
            return;
        }
        string parentFolderPath = GetParentFolderPath(path);
        if (parentFolderPath != "")
        {
            Utils.TryCreatingDirectory(parentFolderPath);
        }
        RemoveReadOnlyAttribute(path);
        using FileStream fileStream = File.Open(path, FileMode.Create);
        while (fileStream.Position < length)
        {
            fileStream.Write(data, (int)fileStream.Position, Math.Min(length - (int)fileStream.Position, 2048));
        }
    }
References Terraria.Social.SocialAPI.Cloud, Terraria.Utilities.FileUtilities.GetParentFolderPath(), System.length, System.Math.Min(), System.IO.File.Open(), Terraria.Utilities.FileUtilities.RemoveReadOnlyAttribute(), and Terraria.Utils.TryCreatingDirectory().
Referenced by Terraria.IO.WorldFile.InternalSaveWorld().