Terraria: Terraria.Utilities.FileUtilities.CopyToLocal
CopyToLocal()
static bool Terraria.Utilities.FileUtilities.CopyToLocal (string cloudPath, string localPath) inline static
Definition at line 177 of file FileUtilities.cs.
    {
        if (SocialAPI.Cloud == null)
        {
            return false;
        }
        WriteAllBytes(localPath, ReadAllBytes(cloudPath, cloud: true), cloud: false);
        return true;
    }
References Terraria.Social.SocialAPI.Cloud, Terraria.Utilities.FileUtilities.ReadAllBytes(), and Terraria.Utilities.FileUtilities.WriteAllBytes().
Referenced by Terraria.Social.Steam.WorkshopHelper.UGCBased.WorldPublisherInstance.PrepareContentForUpdate().