Terraria: Terraria.Utilities.FileUtilities.CopyFolder
CopyFolder()
static void Terraria.Utilities.FileUtilities.CopyFolder (string sourcePath, string destinationPath) inline static
Definition at line 208 of file FileUtilities.cs.
    {
        Directory.CreateDirectory(destinationPath);
        string[] directories = Directory.GetDirectories(sourcePath, "*", SearchOption.AllDirectories);
        for (int i = 0; i < directories.Length; i++)
        {
            Directory.CreateDirectory(directories[i].Replace(sourcePath, destinationPath));
        }
        directories = Directory.GetFiles(sourcePath, "*.*", SearchOption.AllDirectories);
        foreach (string obj in directories)
        {
            File.Copy(obj, obj.Replace(sourcePath, destinationPath), overwrite: true);
        }
    }
References System.IO.File.Copy(), System.IO.Directory.CreateDirectory(), System.IO.Directory.GetDirectories(), System.IO.Directory.GetFiles(), System.Text.RegularExpressions.i, and System.obj.