Terraria: System.Security.Cryptography.KeyFormatHelper.WritePkcs8
WritePkcs8() [2/2]
static AsnWriter System.Security.Cryptography.KeyFormatHelper.WritePkcs8 (AsnWriter algorithmIdentifierWriter, AsnWriter privateKeyWriter, AsnWriter attributesWriter = null) inline static package
Definition at line 8 of file KeyFormatHelper.cs.
    {
        int encodedLength = algorithmIdentifierWriter.GetEncodedLength();
        int encodedLength2 = privateKeyWriter.GetEncodedLength();
        AsnWriter asnWriter = new AsnWriter(AsnEncodingRules.DER);
        asnWriter.PushSequence();
        asnWriter.WriteInteger(0L);
        algorithmIdentifierWriter.CopyTo(asnWriter);
        using (asnWriter.PushOctetString())
        {
            privateKeyWriter.CopyTo(asnWriter);
        }
        attributesWriter?.CopyTo(asnWriter);
        asnWriter.PopSequence();
        return asnWriter;
    }
References System.Formats.Asn1.AsnWriter.CopyTo(), System.Formats.Asn1.AsnWriter.GetEncodedLength(), System.L, System.Formats.Asn1.AsnWriter.PopSequence(), System.Formats.Asn1.AsnWriter.PushOctetString(), System.Formats.Asn1.AsnWriter.PushSequence(), and System.Formats.Asn1.AsnWriter.WriteInteger().