Terraria: System.Security.Cryptography.KeyFormatHelper.DecryptPkcs8
DecryptPkcs8() [6/6]
static ArraySegment< byte > System.Security.Cryptography.KeyFormatHelper.DecryptPkcs8 (ReadOnlySpan< char > inputPassword, ReadOnlySpan< byte > inputPasswordBytes, ReadOnlyMemory< byte > source, out int bytesRead) inline static private
Definition at line 76 of file KeyFormatHelper.cs.
    {
        int length;
        System.Security.Cryptography.Asn1.EncryptedPrivateKeyInfoAsn decoded;
        try
        {
            System.Formats.Asn1.AsnValueReader reader = new System.Formats.Asn1.AsnValueReader(source.Span, AsnEncodingRules.BER);
            length = reader.PeekEncodedValue().Length;
            System.Security.Cryptography.Asn1.EncryptedPrivateKeyInfoAsn.Decode(ref reader, source, out decoded);
        }
        catch (AsnContentException inner)
        {
            throw new CryptographicException(System.SR.Cryptography_Der_Invalid_Encoding, inner);
        }
        byte[] array = System.Security.Cryptography.CryptoPool.Rent(decoded.EncryptedData.Length);
        try
        {
            int count = System.Security.Cryptography.PasswordBasedEncryption.Decrypt(in decoded.EncryptionAlgorithm, inputPassword, inputPasswordBytes, decoded.EncryptedData.Span, array);
            bytesRead = length;
            return new ArraySegment<byte>(array, 0, count);
        }
        catch (CryptographicException inner2)
        {
            System.Security.Cryptography.CryptoPool.Return(array);
            throw new CryptographicException(System.SR.Cryptography_Pkcs8_EncryptedReadFailed, inner2);
        }
    }
References System.array, System.count, System.SR.Cryptography_Der_Invalid_Encoding, System.SR.Cryptography_Pkcs8_EncryptedReadFailed, System.Security.Cryptography.Asn1.EncryptedPrivateKeyInfoAsn.Decode(), System.Security.Cryptography.PasswordBasedEncryption.Decrypt(), System.Security.Cryptography.Asn1.EncryptedPrivateKeyInfoAsn.EncryptedData, System.Security.Cryptography.Asn1.EncryptedPrivateKeyInfoAsn.EncryptionAlgorithm, System.length, System.ReadOnlyMemory< T >.Length, System.ReadOnlySpan< T >.Length, System.Formats.Asn1.AsnValueReader.PeekEncodedValue(), System.Security.Cryptography.CryptoPool.Rent(), System.Security.Cryptography.CryptoPool.Return(), System.source, and System.ReadOnlyMemory< T >.Span.