Terraria: System.Security.Cryptography.KeyFormatHelper.WriteEncryptedPkcs8
WriteEncryptedPkcs8() [6/6]
static AsnWriter System.Security.Cryptography.KeyFormatHelper.WriteEncryptedPkcs8 (ReadOnlySpan< char > password, ReadOnlySpan< byte > passwordBytes, AsnWriter pkcs8Writer, PbeParameters pbeParameters) inline static private
Definition at line 35 of file KeyFormatHelper.cs.
    {
        System.Security.Cryptography.PasswordBasedEncryption.InitiateEncryption(pbeParameters, out var cipher, out var hmacOid, out var encryptionAlgorithmOid, out var isPkcs);
        Span<byte> span = default(Span<byte>);
        AsnWriter asnWriter = null;
        Span<byte> span2 = stackalloc byte[cipher.BlockSize / 8];
        Span<byte> span3 = stackalloc byte[16];
        checked
        {
            byte[] array = System.Security.Cryptography.CryptoPool.Rent(pkcs8Writer.GetEncodedLength() + unchecked(cipher.BlockSize / 8));
            try
            {
                RandomNumberGenerator.Fill(span3);
                int length = System.Security.Cryptography.PasswordBasedEncryption.Encrypt(password, passwordBytes, cipher, isPkcs, pkcs8Writer, pbeParameters, span3, array, span2);
                span = array.AsSpan(0, length);
                asnWriter = new AsnWriter(AsnEncodingRules.DER);
                asnWriter.PushSequence();
                System.Security.Cryptography.PasswordBasedEncryption.WritePbeAlgorithmIdentifier(asnWriter, isPkcs, encryptionAlgorithmOid, span3, pbeParameters.IterationCount, hmacOid, span2);
                asnWriter.WriteOctetString(span);
                asnWriter.PopSequence();
                return asnWriter;
            }
            finally
            {
                CryptographicOperations.ZeroMemory(span);
                System.Security.Cryptography.CryptoPool.Return(array, 0);
                cipher.Dispose();
            }
        }
    }
References System.array, System.Security.Cryptography.PasswordBasedEncryption.Encrypt(), System.Security.Cryptography.RandomNumberGenerator.Fill(), System.Formats.Asn1.AsnWriter.GetEncodedLength(), System.Security.Cryptography.PasswordBasedEncryption.InitiateEncryption(), System.Security.Cryptography.PbeParameters.IterationCount, System.length, System.Formats.Asn1.AsnWriter.PopSequence(), System.Formats.Asn1.AsnWriter.PushSequence(), System.Security.Cryptography.CryptoPool.Rent(), System.Security.Cryptography.CryptoPool.Return(), System.Formats.Asn1.AsnWriter.WriteOctetString(), System.Security.Cryptography.PasswordBasedEncryption.WritePbeAlgorithmIdentifier(), and System.Security.Cryptography.CryptographicOperations.ZeroMemory().