Terraria: System.Security.Cryptography.KeyFormatHelper.ReadSubjectPublicKeyInfo
ReadSubjectPublicKeyInfo()
static ReadOnlyMemory< byte > System.Security.Cryptography.KeyFormatHelper.ReadSubjectPublicKeyInfo (string[] validOids, ReadOnlyMemory< byte > source, out int bytesRead) inline static package
Definition at line 21 of file KeyFormatHelper.cs.
    {
        int length;
        SubjectPublicKeyInfoAsn decoded;
        try
        {
            AsnValueReader reader = new AsnValueReader(source.Span, AsnEncodingRules.DER);
            length = reader.PeekEncodedValue().Length;
            SubjectPublicKeyInfoAsn.Decode(ref reader, source, out decoded);
        }
        catch (AsnContentException inner)
        {
            throw new CryptographicException(System.SR.Cryptography_Der_Invalid_Encoding, inner);
        }
        if (Array.IndexOf(validOids, decoded.Algorithm.Algorithm) < 0)
        {
            throw new CryptographicException(System.SR.Cryptography_NotValidPublicOrPrivateKey);
        }
        bytesRead = length;
        return decoded.SubjectPublicKey;
    }
References System.Security.Cryptography.Asn1.AlgorithmIdentifierAsn.Algorithm, System.Security.Cryptography.Asn1.SubjectPublicKeyInfoAsn.Algorithm, System.SR.Cryptography_Der_Invalid_Encoding, System.SR.Cryptography_NotValidPublicOrPrivateKey, System.Security.Cryptography.Asn1.SubjectPublicKeyInfoAsn.Decode(), System.Array.IndexOf(), System.length, System.ReadOnlySpan< T >.Length, System.Formats.Asn1.AsnValueReader.PeekEncodedValue(), System.source, and System.Security.Cryptography.Asn1.SubjectPublicKeyInfoAsn.SubjectPublicKey.
Referenced by System.Security.Cryptography.ECDiffieHellman.ImportSubjectPublicKeyInfo(), System.Security.Cryptography.ECDsa.ImportSubjectPublicKeyInfo(), System.Security.Cryptography.RSAKeyFormatHelper.ReadSubjectPublicKeyInfo(), System.Security.Cryptography.DSAKeyFormatHelper.ReadSubjectPublicKeyInfo(), and System.Security.Cryptography.KeyFormatHelper.ReadSubjectPublicKeyInfo< TRet >().