Terraria: System.Security.Cryptography.KeyFormatHelper.ReadPkcs8< TRet >
ReadPkcs8< TRet >() [1/2]
static void System.Security.Cryptography.KeyFormatHelper.ReadPkcs8< TRet > (string[] validOids, ReadOnlyMemory< byte > source, KeyReader< TRet > keyReader, out int bytesRead, out TRet ret) inline static private
Definition at line 94 of file KeyFormatHelper.cs.
    {
        try
        {
            AsnValueReader reader = new AsnValueReader(source.Span, AsnEncodingRules.BER);
            int length = reader.PeekEncodedValue().Length;
            PrivateKeyInfoAsn.Decode(ref reader, source, out var decoded);
            if (Array.IndexOf(validOids, decoded.PrivateKeyAlgorithm.Algorithm) < 0)
            {
                throw new CryptographicException(System.SR.Cryptography_NotValidPublicOrPrivateKey);
            }
            keyReader(decoded.PrivateKey, in decoded.PrivateKeyAlgorithm, out ret);
            bytesRead = length;
        }
        catch (AsnContentException inner)
        {
            throw new CryptographicException(System.SR.Cryptography_Der_Invalid_Encoding, inner);
        }
    }
References System.SR.Cryptography_Der_Invalid_Encoding, System.SR.Cryptography_NotValidPublicOrPrivateKey, System.Security.Cryptography.Asn1.PrivateKeyInfoAsn.Decode(), System.Array.IndexOf(), System.length, System.ReadOnlySpan< T >.Length, System.Formats.Asn1.AsnValueReader.PeekEncodedValue(), and System.source.