Terraria: System.Security.Cryptography.KeyFormatHelper.ReadPkcs8
ReadPkcs8()
static ReadOnlyMemory< byte > System.Security.Cryptography.KeyFormatHelper.ReadPkcs8 (string[] validOids, ReadOnlyMemory< byte > source, out int bytesRead) inline static package
Definition at line 74 of file KeyFormatHelper.cs.
    {
        try
        {
            AsnValueReader reader = new AsnValueReader(source.Span, AsnEncodingRules.BER);
            int length = reader.PeekEncodedValue().Length;
            PrivateKeyInfoAsn.Decode(ref reader, source, out var decoded);
            if (Array.IndexOf(validOids, decoded.PrivateKeyAlgorithm.Algorithm) < 0)
            {
                throw new CryptographicException(System.SR.Cryptography_NotValidPublicOrPrivateKey);
            }
            bytesRead = length;
            return decoded.PrivateKey;
        }
        catch (AsnContentException inner)
        {
            throw new CryptographicException(System.SR.Cryptography_Der_Invalid_Encoding, inner);
        }
    }
References System.SR.Cryptography_Der_Invalid_Encoding, System.SR.Cryptography_NotValidPublicOrPrivateKey, System.Security.Cryptography.Asn1.PrivateKeyInfoAsn.Decode(), System.Array.IndexOf(), System.length, System.ReadOnlySpan< T >.Length, System.Formats.Asn1.AsnValueReader.PeekEncodedValue(), and System.source.
Referenced by System.Security.Cryptography.ECDiffieHellman.ImportPkcs8PrivateKey(), System.Security.Cryptography.ECDsa.ImportPkcs8PrivateKey(), System.Security.Cryptography.KeyFormatHelper.ReadEncryptedPkcs8< TRet >(), System.Security.Cryptography.RSAKeyFormatHelper.ReadPkcs8(), System.Security.Cryptography.DSAKeyFormatHelper.ReadPkcs8(), and System.Security.Cryptography.KeyFormatHelper.ReadPkcs8< TRet >().