Terraria: System.Security.Cryptography.KeyFormatHelper.ReencryptPkcs8
ReencryptPkcs8() [2/4]
static AsnWriter System.Security.Cryptography.KeyFormatHelper.ReencryptPkcs8 (ReadOnlySpan< char > inputPassword, ReadOnlyMemory< byte > current, ReadOnlySpan< byte > newPasswordBytes, PbeParameters pbeParameters) inline static package
Definition at line 128 of file KeyFormatHelper.cs.
    {
        int bytesRead;
        ArraySegment<byte> arraySegment = DecryptPkcs8(inputPassword, current, out bytesRead);
        try
        {
            if (bytesRead != current.Length)
            {
                throw new CryptographicException(System.SR.Cryptography_Der_Invalid_Encoding);
            }
            AsnWriter asnWriter = new AsnWriter(AsnEncodingRules.BER);
            asnWriter.WriteEncodedValueForCrypto(arraySegment);
            return WriteEncryptedPkcs8(newPasswordBytes, asnWriter, pbeParameters);
        }
        catch (CryptographicException inner)
        {
            throw new CryptographicException(System.SR.Cryptography_Pkcs8_EncryptedReadFailed, inner);
        }
        finally
        {
            System.Security.Cryptography.CryptoPool.Return(arraySegment);
        }
    }
References System.SR.Cryptography_Der_Invalid_Encoding, System.SR.Cryptography_Pkcs8_EncryptedReadFailed, System.Security.Cryptography.KeyFormatHelper.DecryptPkcs8(), System.ReadOnlyMemory< T >.Length, System.Security.Cryptography.CryptoPool.Return(), and System.Security.Cryptography.KeyFormatHelper.WriteEncryptedPkcs8().