Terraria: System.Net.Sockets.IOControlKeepAlive.Set
Set() [1/2]
static SocketError System.Net.Sockets.IOControlKeepAlive.Set (SafeSocketHandle handle, SocketOptionName optionName, byte[] optionValueSeconds) inline static
Definition at line 47 of file IOControlKeepAlive.cs.
    {
        if (optionValueSeconds == null || optionValueSeconds.Length < 4)
        {
            return SocketError.Fault;
        }
        return Set(handle, optionName, BitConverter.ToInt32(optionValueSeconds, 0));
    }
References System.handle, System.Net.Sockets.IOControlKeepAlive.Set(), and System.BitConverter.ToInt32().
Referenced by System.Net.Sockets.IOControlKeepAlive.Set(), System.Net.Sockets.SocketPal.SetSockOpt(), and System.Net.Sockets.SocketPal.SetSockOpt().