Terraria: System.Net.Sockets.IOControlKeepAlive.Get
Get() [2/2]
static SocketError System.Net.Sockets.IOControlKeepAlive.Get (SafeSocketHandle handle, SocketOptionName optionName, byte[] optionValueSeconds, ref int optionLength) inline static
Definition at line 20 of file IOControlKeepAlive.cs.
    {
        if (optionValueSeconds == null || !BitConverter.TryWriteBytes(optionValueSeconds.AsSpan(), Get(handle, optionName)))
        {
            return SocketError.Fault;
        }
        optionLength = optionValueSeconds.Length;
        return SocketError.Success;
    }
References System.Net.Sockets.IOControlKeepAlive.Get(), System.handle, and System.BitConverter.TryWriteBytes().
Referenced by System.Net.Sockets.IOControlKeepAlive.Get(), System.Net.Sockets.SocketPal.GetSockOpt(), and System.Net.Sockets.SocketPal.GetSockOpt().