Terraria: System.ComponentModel.AttributeCollection.FromExisting
FromExisting()
static AttributeCollection System.ComponentModel.AttributeCollection.FromExisting (AttributeCollection existing, params Attribute?[] newAttributes) inline static
Definition at line 120 of file AttributeCollection.cs.
    {
        if (existing == null)
        {
            throw new ArgumentNullException("existing");
        }
        if (newAttributes == null)
        {
            newAttributes = Array.Empty<Attribute>();
        }
        Attribute[] array = new Attribute[existing.Count + newAttributes.Length];
        int count = existing.Count;
        existing.CopyTo(array, 0);
        for (int i = 0; i < newAttributes.Length; i++)
        {
            if (newAttributes[i] == null)
            {
                throw new ArgumentNullException("newAttributes");
            }
            bool flag = false;
            for (int j = 0; j < existing.Count; j++)
            {
                if (array[j].TypeId.Equals(newAttributes[i].TypeId))
                {
                    flag = true;
                    array[j] = newAttributes[i];
                    break;
                }
            }
            if (!flag)
            {
                array[count++] = newAttributes[i];
            }
        }
        Attribute[] array2;
        if (count < array.Length)
        {
            array2 = new Attribute[count];
            Array.Copy(array, array2, count);
        }
        else
        {
            array2 = array;
        }
        return new AttributeCollection(array2);
    }
References System.ComponentModel.AttributeCollection.AttributeCollection(), System.array, System.Array.Copy(), System.ComponentModel.AttributeCollection.CopyTo(), System.ComponentModel.AttributeCollection.Count, and System.count.
Referenced by System.ComponentModel.DataAnnotations.AssociatedMetadataTypeTypeDescriptor.GetAttributes().