Terraria: System.ComponentModel.AttributeCollection.GetDefaultAttribute
GetDefaultAttribute()
Attribute? System.ComponentModel.AttributeCollection.GetDefaultAttribute ([DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicParameterlessConstructor | DynamicallyAccessedMemberTypes.PublicFields)] Type attributeType) inline protected
Definition at line 194 of file AttributeCollection.cs.
    {
        if (attributeType == null)
        {
            throw new ArgumentNullException("attributeType");
        }
        lock (s_internalSyncObject)
        {
            if (s_defaultAttributes == null)
            {
                s_defaultAttributes = new Hashtable();
            }
            if (s_defaultAttributes.ContainsKey(attributeType))
            {
                return (Attribute)s_defaultAttributes[attributeType];
            }
            Attribute attribute = null;
            Type reflectionType = TypeDescriptor.GetReflectionType(attributeType);
            FieldInfo field = reflectionType.GetField("Default", BindingFlags.Static | BindingFlags.Public | BindingFlags.GetField);
            if (field != null && field.IsStatic)
            {
                attribute = (Attribute)field.GetValue(null);
            }
            else
            {
                ConstructorInfo constructor = reflectionType.UnderlyingSystemType.GetConstructor(Type.EmptyTypes);
                if (constructor != null)
                {
                    attribute = (Attribute)constructor.Invoke(Array.Empty<object>());
                    if (!attribute.IsDefaultAttribute())
                    {
                        attribute = null;
                    }
                }
            }
            s_defaultAttributes[attributeType] = attribute;
            return attribute;
        }
    }
References System.ComponentModel.AttributeCollection.attributeType, System.Type.EmptyTypes, System.Type.GetConstructor(), System.Type.GetField(), System.ComponentModel.TypeDescriptor.GetReflectionType(), System.Reflection.FieldInfo.GetValue(), System.Reflection.ConstructorInfo.Invoke(), System.Attribute.IsDefaultAttribute(), System.Reflection.FieldInfo.IsStatic, System.ComponentModel.AttributeCollection.s_defaultAttributes, System.ComponentModel.AttributeCollection.s_internalSyncObject, and System.Type.UnderlyingSystemType.