Terraria: System.Reflection.Emit.AssemblyBuilder.CheckContext
CheckContext() [2/2]
static void System.Reflection.Emit.AssemblyBuilder.CheckContext (params Type typess[][]) inline static package
Definition at line 172 of file AssemblyBuilder.cs.
    {
        if (typess == null)
        {
            return;
        }
        foreach (Type[] array in typess)
        {
            if (array != null)
            {
                CheckContext(array);
            }
        }
    }
References System.array, and System.Reflection.Emit.AssemblyBuilder.CheckContext().
Referenced by System.Reflection.Emit.TypeBuilder.AddInterfaceImplementation(), System.Reflection.Emit.AssemblyBuilder.CheckContext(), System.Reflection.Emit.TypeBuilder.DefineConstructorNoLock(), System.Reflection.Emit.ModuleBuilder.DefineEnum(), System.Reflection.Emit.TypeBuilder.DefineEventNoLock(), System.Reflection.Emit.TypeBuilder.DefineFieldNoLock(), System.Reflection.Emit.ModuleBuilder.DefineGlobalMethodNoLock(), System.Reflection.Emit.TypeBuilder.DefineMethodNoLock(), System.Reflection.Emit.TypeBuilder.DefineNestedType(), System.Reflection.Emit.ModuleBuilder.DefinePInvokeMethod(), System.Reflection.Emit.TypeBuilder.DefinePInvokeMethodHelper(), System.Reflection.Emit.TypeBuilder.DefinePropertyNoLock(), System.Reflection.Emit.ModuleBuilder.DefineType(), System.Reflection.Emit.ModuleBuilder.GetArrayMethod(), System.Reflection.Emit.ModuleBuilder.GetArrayMethodTokenNoLock(), System.Reflection.Emit.ModuleBuilder.GetTypeTokenWorkerNoLock(), System.Reflection.Emit.TypeBuilder.MakeGenericType(), System.Reflection.Emit.GenericTypeParameterBuilder.SetBaseTypeConstraint(), System.Reflection.Emit.GenericTypeParameterBuilder.SetInterfaceConstraints(), System.Reflection.Emit.MethodBuilder.SetParameters(), System.Reflection.Emit.TypeBuilder.SetParent(), System.Reflection.Emit.MethodBuilder.SetReturnType(), and System.Reflection.Emit.MethodBuilder.SetSignature().