Terraria: System.Reflection.Emit.AssemblyBuilder.AssemblyBuilder
AssemblyBuilder()
System.Reflection.Emit.AssemblyBuilder.AssemblyBuilder (AssemblyName name, AssemblyBuilderAccess access, ref StackCrawlMark stackMark, AssemblyLoadContext assemblyLoadContext, IEnumerable< CustomAttributeBuilder > unsafeAssemblyAttributes) inline package
Definition at line 74 of file AssemblyBuilder.cs.
    {
        if (name == null)
        {
            throw new ArgumentNullException("name");
        }
        if (access != AssemblyBuilderAccess.Run && access != AssemblyBuilderAccess.RunAndCollect)
        {
            throw new ArgumentException(SR.Format(SR.Arg_EnumIllegalVal, (int)access), "access");
        }
        name = (AssemblyName)name.Clone();
        List<CustomAttributeBuilder> list = null;
        if (unsafeAssemblyAttributes != null)
        {
            list = new List<CustomAttributeBuilder>(unsafeAssemblyAttributes);
        }
        Assembly o = null;
        CreateDynamicAssembly(ObjectHandleOnStack.Create(ref name), new StackCrawlMarkHandle(ref stackMark), (int)access, ObjectHandleOnStack.Create(ref assemblyLoadContext), ObjectHandleOnStack.Create(ref o));
        _internalAssemblyBuilder = (InternalAssemblyBuilder)o;
        _assemblyData = new AssemblyBuilderData(access);
        InitManifestModule();
        if (list == null)
        {
            return;
        }
        foreach (CustomAttributeBuilder item in list)
        {
            SetCustomAttribute(item);
        }
    }
References System.Reflection.Emit.AssemblyBuilder._assemblyData, System.Reflection.Emit.AssemblyBuilder._internalAssemblyBuilder, System.SR.Arg_EnumIllegalVal, System.Reflection.Emit.AssemblyBuilder.CreateDynamicAssembly(), System.SR.Format(), System.Reflection.Emit.AssemblyBuilder.InitManifestModule(), System.item, System.list, and System.Reflection.Emit.AssemblyBuilder.SetCustomAttribute().
Referenced by System.Reflection.Emit.AssemblyBuilder.InternalDefineDynamicAssembly().