Terraria: System.Net.Quic.Implementations.MsQuic.Internal.QuicExceptionHelpers.ThrowIfFailed
ThrowIfFailed()
static void System.Net.Quic.Implementations.MsQuic.Internal.QuicExceptionHelpers.ThrowIfFailed (uint status, string message = null, Exception innerException = null) inline static package
Definition at line 5 of file QuicExceptionHelpers.cs.
    {
        if (!MsQuicStatusHelper.SuccessfulStatusCode(status))
        {
            throw CreateExceptionForHResult(status, message, innerException);
        }
    }
References System.Net.Quic.Implementations.MsQuic.Internal.QuicExceptionHelpers.CreateExceptionForHResult(), and System.Net.Quic.Implementations.MsQuic.Internal.MsQuicStatusHelper.SuccessfulStatusCode().
Referenced by System.Net.Quic.Implementations.MsQuic.Internal.MsQuicApi.MsQuicApi(), System.Net.Quic.Implementations.MsQuic.MsQuicConnection.MsQuicConnection(), System.Net.Quic.Implementations.MsQuic.MsQuicListener.MsQuicListener(), System.Net.Quic.Implementations.MsQuic.MsQuicStream.MsQuicStream(), System.Net.Quic.Implementations.MsQuic.MsQuicConnection.ConnectAsync(), System.Net.Quic.Implementations.MsQuic.Internal.SafeMsQuicConfigurationHandle.Create(), System.Net.Quic.Implementations.MsQuic.MsQuicStream.EnableReceive(), System.Net.Quic.Implementations.MsQuic.Internal.MsQuicParameterHelpers.GetINetParam(), System.Net.Quic.Implementations.MsQuic.Internal.MsQuicParameterHelpers.GetULongParam(), System.Net.Quic.Implementations.MsQuic.Internal.MsQuicParameterHelpers.GetUShortParam(), System.Net.Quic.Implementations.MsQuic.MsQuicStream.ReceiveComplete(), System.Net.Quic.Implementations.MsQuic.MsQuicStream.SendReadOnlyMemoryAsync(), System.Net.Quic.Implementations.MsQuic.MsQuicStream.SendReadOnlyMemoryListAsync(), System.Net.Quic.Implementations.MsQuic.MsQuicStream.SendReadOnlySequenceAsync(), System.Net.Quic.Implementations.MsQuic.MsQuicListener.Start(), and System.Net.Quic.Implementations.MsQuic.MsQuicStream.StartShutdown().