Terraria: System.Reflection.Emit.AssemblyBuilder.InitManifestModule
InitManifestModule()
void System.Reflection.Emit.AssemblyBuilder.InitManifestModule () inline private
Definition at line 106 of file AssemblyBuilder.cs.
    {
        InternalModuleBuilder internalModuleBuilder = (InternalModuleBuilder)GetInMemoryAssemblyModule(InternalAssembly);
        _manifestModuleBuilder = new ModuleBuilder(this, internalModuleBuilder);
        _manifestModuleBuilder.Init("RefEmit_InMemoryManifestModule");
        _isManifestModuleUsedAsDefinedModule = false;
    }
References System.Reflection.Emit.AssemblyBuilder._isManifestModuleUsedAsDefinedModule, System.Reflection.Emit.AssemblyBuilder._manifestModuleBuilder, System.Reflection.Emit.AssemblyBuilder.GetInMemoryAssemblyModule(), System.Reflection.Emit.ModuleBuilder.Init(), and System.Reflection.Emit.AssemblyBuilder.InternalAssembly.
Referenced by System.Reflection.Emit.AssemblyBuilder.AssemblyBuilder().