Terraria: System.Reflection.Emit.AssemblyBuilder.DefineDynamicAssembly
DefineDynamicAssembly() [1/2]
static AssemblyBuilder System.Reflection.Emit.AssemblyBuilder.DefineDynamicAssembly (AssemblyName name, AssemblyBuilderAccess access) inline static
Definition at line 114 of file AssemblyBuilder.cs.
    {
        StackCrawlMark stackMark = StackCrawlMark.LookForMyCaller;
        return InternalDefineDynamicAssembly(name, access, ref stackMark, AssemblyLoadContext.CurrentContextualReflectionContext, null);
    }
References System.Runtime.Loader.AssemblyLoadContext.CurrentContextualReflectionContext, and System.Reflection.Emit.AssemblyBuilder.InternalDefineDynamicAssembly().
Referenced by System.Linq.Expressions.Compiler.AssemblyGen.AssemblyGen(), System.Reflection.DispatchProxyGenerator.ProxyAssembly.ProxyAssembly(), System.Xml.Xsl.IlGen.XmlILModule.XmlILModule(), System.Xml.Serialization.CodeGenerator.CreateAssemblyBuilder(), and System.Xml.Xsl.IlGen.XmlILModule.CreateLREModule().