Terraria: System.Text.Json.JsonHelpers.TryParseAsISO
TryParseAsISO() [1/2]
static bool System.Text.Json.JsonHelpers.TryParseAsISO (ReadOnlySpan< byte > source, out DateTime value) inline static
Definition at line 127 of file JsonHelpers.cs.
    {
        if (!TryParseDateTimeOffset(source, out var parseData))
        {
            value = default(DateTime);
            return false;
        }
        if (parseData.OffsetToken == 90)
        {
            return TryCreateDateTime(parseData, DateTimeKind.Utc, out value);
        }
        if (parseData.OffsetToken == 43 || parseData.OffsetToken == 45)
        {
            if (!TryCreateDateTimeOffset(ref parseData, out var value2))
            {
                value = default(DateTime);
                return false;
            }
            value = value2.LocalDateTime;
            return true;
        }
        return TryCreateDateTime(parseData, DateTimeKind.Unspecified, out value);
    }
References System.source, System.Text.Json.JsonHelpers.TryCreateDateTime(), System.Text.Json.JsonHelpers.TryCreateDateTimeOffset(), System.Text.Json.JsonHelpers.TryParseDateTimeOffset(), and System.value.
Referenced by System.Text.Json.Utf8JsonReader.TryGetDateTimeCore(), System.Text.Json.Utf8JsonReader.TryGetDateTimeOffsetCore(), System.Text.Json.JsonReaderHelper.TryGetEscapedDateTime(), System.Text.Json.JsonReaderHelper.TryGetEscapedDateTimeOffset(), System.Text.Json.JsonDocument.TryGetValue(), and System.Text.Json.JsonDocument.TryGetValue().