Terraria: System.Text.Json.JsonHelpers.TryCreateDateTime
TryCreateDateTime()
static bool System.Text.Json.JsonHelpers.TryCreateDateTime (DateTimeParseData parseData, DateTimeKind kind, out DateTime value) inline static private
Definition at line 378 of file JsonHelpers.cs.
    {
        if (parseData.Year == 0)
        {
            value = default(DateTime);
            return false;
        }
        if ((uint)(parseData.Month - 1) >= 12u)
        {
            value = default(DateTime);
            return false;
        }
        uint num = (uint)(parseData.Day - 1);
        if (num >= 28 && num >= DateTime.DaysInMonth(parseData.Year, parseData.Month))
        {
            value = default(DateTime);
            return false;
        }
        if ((uint)parseData.Hour > 23u)
        {
            value = default(DateTime);
            return false;
        }
        if ((uint)parseData.Minute > 59u)
        {
            value = default(DateTime);
            return false;
        }
        if ((uint)parseData.Second > 59u)
        {
            value = default(DateTime);
            return false;
        }
        int[] array = (DateTime.IsLeapYear(parseData.Year) ? s_daysToMonth366 : s_daysToMonth365);
        int num2 = parseData.Year - 1;
        int num3 = num2 * 365 + num2 / 4 - num2 / 100 + num2 / 400 + array[parseData.Month - 1] + parseData.Day - 1;
        long num4 = num3 * 864000000000L;
        int num5 = parseData.Hour * 3600 + parseData.Minute * 60 + parseData.Second;
        num4 += (long)num5 * 10000000L;
        num4 += parseData.Fraction;
        value = new DateTime(num4, kind);
        return true;
    }
References System.array, System.Text.Json.DateTime, System.DateTime.DaysInMonth(), System.Text.Json.Dictionary, System.DateTime.IsLeapYear(), System.L, System.Text.Json.JsonHelpers.s_daysToMonth365, System.Text.Json.JsonHelpers.s_daysToMonth366, and System.value.
Referenced by System.Text.Json.JsonHelpers.TryCreateDateTimeOffset(), System.Text.Json.JsonHelpers.TryCreateDateTimeOffsetInterpretingDataAsLocalTime(), and System.Text.Json.JsonHelpers.TryParseAsISO().