Terraria: System.Text.Json.JsonHelpers.TryParseDateTimeOffset
TryParseDateTimeOffset()
static bool System.Text.Json.JsonHelpers.TryParseDateTimeOffset (ReadOnlySpan< byte > source, out DateTimeParseData parseData) inline static private
Definition at line 165 of file JsonHelpers.cs.
    {
        parseData = default(DateTimeParseData);
        uint num = (uint)(source[0] - 48);
        uint num2 = (uint)(source[1] - 48);
        uint num3 = (uint)(source[2] - 48);
        uint num4 = (uint)(source[3] - 48);
        if (num > 9 || num2 > 9 || num3 > 9 || num4 > 9)
        {
            return false;
        }
        parseData.Year = (int)(num * 1000 + num2 * 100 + num3 * 10 + num4);
        if (source[4] != 45 || !TryGetNextTwoDigits(source.Slice(5, 2), ref parseData.Month) || source[7] != 45 || !TryGetNextTwoDigits(source.Slice(8, 2), ref parseData.Day))
        {
            return false;
        }
        if (source.Length == 10)
        {
            return true;
        }
        if (source.Length < 16)
        {
            return false;
        }
        if (source[10] != 84 || source[13] != 58 || !TryGetNextTwoDigits(source.Slice(11, 2), ref parseData.Hour) || !TryGetNextTwoDigits(source.Slice(14, 2), ref parseData.Minute))
        {
            return false;
        }
        if (source.Length == 16)
        {
            return true;
        }
        byte b = source[16];
        int num5 = 17;
        switch (b)
        {
        case 90:
            parseData.OffsetToken = 90;
            return num5 == source.Length;
        case 43:
        case 45:
            parseData.OffsetToken = b;
            return ParseOffset(ref parseData, source.Slice(num5));
        default:
            return false;
        case 58:
            if (source.Length < 19 || !TryGetNextTwoDigits(source.Slice(17, 2), ref parseData.Second))
            {
                return false;
            }
            if (source.Length == 19)
            {
                return true;
            }
            b = source[19];
            num5 = 20;
            switch (b)
            {
            case 90:
                parseData.OffsetToken = 90;
                return num5 == source.Length;
            case 43:
            case 45:
                parseData.OffsetToken = b;
                return ParseOffset(ref parseData, source.Slice(num5));
            default:
                return false;
            case 46:
            {
                if (source.Length < 21)
                {
                    return false;
                }
                int i = 0;
                for (int num6 = Math.Min(num5 + 16, source.Length); num5 < num6; num5++)
                {
                    if (!IsDigit(b = source[num5]))
                    {
                        break;
                    }
                    if (i < 7)
                    {
                        parseData.Fraction = parseData.Fraction * 10 + (b - 48);
                        i++;
                    }
                }
                if (parseData.Fraction != 0)
                {
                    for (; i < 7; i++)
                    {
                        parseData.Fraction *= 10;
                    }
                }
                if (num5 == source.Length)
                {
                    return true;
                }
                b = source[num5++];
                switch (b)
                {
                case 90:
                    parseData.OffsetToken = 90;
                    return num5 == source.Length;
                case 43:
                case 45:
                    parseData.OffsetToken = b;
                    return ParseOffset(ref parseData, source.Slice(num5));
                default:
                    return false;
                }
            }
            }
        }
        static bool ParseOffset(ref DateTimeParseData parseData, ReadOnlySpan<byte> offsetData)
        {
            if (offsetData.Length < 2 || !TryGetNextTwoDigits(offsetData.Slice(0, 2), ref parseData.OffsetHours))
            {
                return false;
            }
            if (offsetData.Length == 2)
            {
                return true;
            }
            if (offsetData.Length != 5 || offsetData[2] != 58 || !TryGetNextTwoDigits(offsetData.Slice(3), ref parseData.OffsetMinutes))
            {
                return false;
            }
            return true;
        }
    }
References System.Text.Json.Dictionary, System.Text.Json.JsonHelpers.IsDigit(), System.Math.Min(), System.source, and System.Text.Json.JsonHelpers.TryGetNextTwoDigits().
Referenced by System.Text.Json.JsonHelpers.TryParseAsISO(), and System.Text.Json.JsonHelpers.TryParseAsISO().