Terraria: System.Text.Json.JsonHelpers.IsDigit
IsDigit()
static bool System.Text.Json.JsonHelpers.IsDigit (byte value) inline static
Definition at line 81 of file JsonHelpers.cs.
    {
        return (uint)(value - 48) <= 9u;
    }
References System.value.
Referenced by System.Text.Json.Utf8JsonReader.ConsumeDecimalDigits(), System.Text.Json.Utf8JsonReader.ConsumeDecimalDigitsMultiSegment(), System.Text.Json.Utf8JsonReader.ConsumeIntegerDigits(), System.Text.Json.Utf8JsonReader.ConsumeIntegerDigitsMultiSegment(), System.Text.Json.Utf8JsonReader.ConsumeNegativeSign(), System.Text.Json.Utf8JsonReader.ConsumeNegativeSignMultiSegment(), System.Text.Json.Utf8JsonReader.ConsumeSign(), System.Text.Json.Utf8JsonReader.ConsumeSignMultiSegment(), System.Text.Json.Utf8JsonReader.ConsumeValue(), System.Text.Json.Utf8JsonReader.ConsumeValueMultiSegment(), System.Text.Json.Serialization.Converters.TimeSpanConverter.Read(), System.Text.Json.Utf8JsonReader.ReadFirstToken(), System.Text.Json.Utf8JsonReader.ReadFirstTokenMultiSegment(), System.Text.Json.JsonHelpers.TryParseDateTimeOffset(), and System.Text.Json.JsonWriterHelper.ValidateNumber().