Terraria: System.Xml.XPathNodeList.ReadUntil
ReadUntil()
int System.Xml.XPathNodeList.ReadUntil (int index) inline package
Definition at line 40 of file XPathNodeList.cs.
    {
        int num = _list.Count;
        while (!_done && num <= index)
        {
            if (_nodeIterator.MoveNext())
            {
                XmlNode node = GetNode(_nodeIterator.Current);
                if (node != null)
                {
                    _list.Add(node);
                    num++;
                }
                continue;
            }
            _done = true;
            break;
        }
        return num;
    }
References System.Xml.XPathNodeList._done, System.Xml.XPathNodeList._list, System.Xml.XPathNodeList._nodeIterator, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Xml.XPath.XPathNodeIterator.Current, System.Xml.XPathNodeList.GetNode(), System.index, and System.Xml.XPath.XPathNodeIterator.MoveNext().
Referenced by System.Xml.XPathNodeList.Item(), and System.Xml.XmlNodeListEnumerator.MoveNext().