Terraria: WrappedTextBuilder.Append
Append() [1/2]
void WrappedTextBuilder.Append (NonBreakingText textToken) inline private
     {
         float num = ((!_workingLine.IsEmpty()) ? (_workingLineWidth + _font.CharacterSpacing + textToken.Width) : textToken.WidthOnNewLine);
         if (textToken.WidthOnNewLine > _maxWidth)
         {
             if (!_workingLine.IsEmpty())
             {
                 CommitWorkingLine();
             }
             if (textToken.Text.Length == 1)
             {
                 _workingLineWidth = num;
                 _workingLine.Append(textToken.Text);
             }
             else
             {
                 Append(textToken.GetAsWrappedText(_maxWidth));
             }
         }
         else if (num <= _maxWidth)
         {
             _workingLineWidth = num;
             _workingLine.Append(textToken.Text);
         }
         else if (_workingLine.IsEmpty())
         {
             _completedText.Append(textToken.Text);
             _workingLine.Clear();
             _workingLineWidth = 0f;
         }
         else
         {
             CommitWorkingLine();
             if (!textToken.IsWhitespace)
             {
                 _workingLine.Append(textToken.Text);
                 _workingLineWidth = textToken.WidthOnNewLine;
             }
         }
     }
References _completedText, _font, _maxWidth, _workingLine, _workingLineWidth, IFontMetrics.CharacterSpacing, CommitWorkingLine(), WrappedTextBuilder.NonBreakingText.GetAsWrappedText(), WrappedTextBuilder.NonBreakingText.IsWhitespace, WrappedTextBuilder.NonBreakingText.Text, WrappedTextBuilder.NonBreakingText.Width, and WrappedTextBuilder.NonBreakingText.WidthOnNewLine.
Referenced by Append(), and DynamicSpriteFont.CreateWrappedText().