Terraria: System.Security.AccessControl.RawAcl.InsertAce
InsertAce()
void System.Security.AccessControl.RawAcl.InsertAce (int index, GenericAce ace) inline
Definition at line 172 of file RawAcl.cs.
    {
        if (ace == null)
        {
            throw new ArgumentNullException("ace");
        }
        if (BinaryLength + ace.BinaryLength > GenericAcl.MaxBinaryLength)
        {
            throw new OverflowException(System.SR.AccessControl_AclTooLong);
        }
        _aces.Insert(index, ace);
    }
References System.Security.AccessControl.RawAcl._aces, System.SR.AccessControl_AclTooLong, System.Security.AccessControl.RawAcl.BinaryLength, System.index, and System.Security.AccessControl.GenericAcl.MaxBinaryLength.
Referenced by System.Security.AccessControl.CommonAcl.CommonAcl(), System.Security.AccessControl.CommonAcl.AddQualifiedAce(), System.Security.AccessControl.CommonAcl.RemoveQualifiedAces(), and System.Security.AccessControl.CommonAcl.SetQualifiedAce().