Terraria: System.Runtime.InteropServices.SafeBuffer.Read< T >
Read< T >()
unsafe T System.Runtime.InteropServices.SafeBuffer.Read< T > (ulong byteOffset) inline inherited
Type Constraints
T : struct
Definition at line 80 of file SafeBuffer.cs.
                                                      : struct
    {
        if (_numBytes == Uninitialized)
        {
            throw NotInitialized();
        }
        uint num = SizeOf<T>();
        byte* ptr = (byte*)(void*)handle + byteOffset;
        SpaceCheck(ptr, num);
        T source = default(T);
        bool success = false;
        try
        {
            DangerousAddRef(ref success);
            Buffer.Memmove(ref Unsafe.As<T, byte>(ref source), ref *ptr, num);
            return source;
        }
        finally
        {
            if (success)
            {
                DangerousRelease();
            }
        }
    }
References System.Runtime.InteropServices.SafeBuffer._numBytes, System.Runtime.InteropServices.SafeHandle.DangerousAddRef(), System.Runtime.InteropServices.SafeHandle.DangerousRelease(), System.Runtime.InteropServices.SafeHandle.handle, System.Buffer.Memmove(), System.Runtime.InteropServices.SafeBuffer.NotInitialized(), System.Runtime.InteropServices.SafeBuffer.SizeOf< T >(), System.source, System.Runtime.InteropServices.SafeBuffer.SpaceCheck(), and System.Runtime.InteropServices.SafeBuffer.Uninitialized.