Terraria: System.Runtime.InteropServices.SafeBuffer.AlignedSizeOf< T >
AlignedSizeOf< T >()
static uint System.Runtime.InteropServices.SafeBuffer.AlignedSizeOf< T > () inline static package inherited
Type Constraints
T : struct
Definition at line 255 of file SafeBuffer.cs.
                                                    : struct
    {
        uint num = SizeOf<T>();
        if (num == 1 || num == 2)
        {
            return num;
        }
        return (uint)((num + 3) & -4);
    }
References System.Runtime.InteropServices.SafeBuffer.SizeOf< T >().
Referenced by System.Runtime.InteropServices.SafeBuffer.Initialize< T >(), System.Runtime.InteropServices.SafeBuffer.ReadSpan< T >(), and System.Runtime.InteropServices.SafeBuffer.WriteSpan< T >().