Terraria: System.Runtime.InteropServices.SafeBuffer.SpaceCheck
SpaceCheck()
unsafe void System.Runtime.InteropServices.SafeBuffer.SpaceCheck (byte * ptr, nuint sizeInBytes) inline private inherited
Definition at line 233 of file SafeBuffer.cs.
    {
        if (_numBytes < sizeInBytes)
        {
            NotEnoughRoom();
        }
        if ((ulong)(ptr - (byte*)(void*)handle) > (ulong)(_numBytes - sizeInBytes))
        {
            NotEnoughRoom();
        }
    }
References System.Runtime.InteropServices.SafeBuffer._numBytes, System.Runtime.InteropServices.SafeHandle.handle, and System.Runtime.InteropServices.SafeBuffer.NotEnoughRoom().
Referenced by System.Runtime.InteropServices.SafeBuffer.Read< T >(), System.Runtime.InteropServices.SafeBuffer.ReadSpan< T >(), System.Runtime.InteropServices.SafeBuffer.Write< T >(), and System.Runtime.InteropServices.SafeBuffer.WriteSpan< T >().