Terraria: System.Runtime.InteropServices.SafeBuffer.AcquirePointer
AcquirePointer()
unsafe void System.Runtime.InteropServices.SafeBuffer.AcquirePointer (ref byte * pointer) inline inherited
Definition at line 58 of file SafeBuffer.cs.
    {
        if (_numBytes == Uninitialized)
        {
            throw NotInitialized();
        }
        pointer = null;
        bool success = false;
        DangerousAddRef(ref success);
        pointer = (byte*)(void*)handle;
    }
References System.Runtime.InteropServices.SafeBuffer._numBytes, System.Runtime.InteropServices.SafeHandle.DangerousAddRef(), System.Runtime.InteropServices.SafeHandle.handle, System.Runtime.InteropServices.SafeBuffer.NotInitialized(), System.pointer, and System.Runtime.InteropServices.SafeBuffer.Uninitialized.
Referenced by System.Reflection.Internal.MemoryMappedFileBlock.DisposableData.DisposableData(), System.IO.MemoryMappedFiles.MemoryMappedView.Flush(), System.Security.Principal.Win32.InitializeReferencedDomainsPointer(), System.IO.UnmanagedMemoryStream.ReadByte(), System.IO.UnmanagedMemoryAccessor.ReadByte(), System.IO.UnmanagedMemoryStream.ReadCore(), System.IO.UnmanagedMemoryAccessor.ReadDecimal(), System.IO.UnmanagedMemoryAccessor.ReadInt16(), System.IO.UnmanagedMemoryAccessor.ReadInt32(), System.IO.UnmanagedMemoryAccessor.ReadInt64(), System.IO.UnmanagedMemoryAccessor.Write(), System.IO.UnmanagedMemoryAccessor.Write(), System.IO.UnmanagedMemoryAccessor.Write(), System.IO.UnmanagedMemoryAccessor.Write(), System.IO.UnmanagedMemoryAccessor.Write(), System.IO.UnmanagedMemoryStream.WriteByte(), and System.IO.UnmanagedMemoryStream.WriteCore().