Terraria: System.Runtime.InteropServices.SafeBuffer.WriteSpan< T >
WriteSpan< T >()
unsafe void System.Runtime.InteropServices.SafeBuffer.WriteSpan< T > (ulong byteOffset, ReadOnlySpan< T > data) inline inherited
Type Constraints
T : struct
Definition at line 205 of file SafeBuffer.cs.
                                                                                    : struct
    {
        if (_numBytes == Uninitialized)
        {
            throw NotInitialized();
        }
        uint num = AlignedSizeOf<T>();
        byte* ptr = (byte*)(void*)handle + byteOffset;
        SpaceCheck(ptr, checked((nuint)(num * data.Length)));
        bool success = false;
        try
        {
            DangerousAddRef(ref success);
            ref T reference = ref MemoryMarshal.GetReference(data);
            for (int i = 0; i < data.Length; i++)
            {
                Buffer.Memmove(ref Unsafe.AsRef<T>(ptr + num * i), ref Unsafe.Add(ref reference, i), 1u);
            }
        }
        finally
        {
            if (success)
            {
                DangerousRelease();
            }
        }
    }
References System.Runtime.InteropServices.SafeBuffer._numBytes, System.Runtime.InteropServices.SafeBuffer.AlignedSizeOf< T >(), System.Runtime.InteropServices.SafeHandle.DangerousAddRef(), System.Runtime.InteropServices.SafeHandle.DangerousRelease(), System.Runtime.InteropServices.SafeHandle.handle, System.Buffer.Memmove(), System.Runtime.InteropServices.SafeBuffer.NotInitialized(), System.Runtime.InteropServices.SafeBuffer.SpaceCheck(), and System.Runtime.InteropServices.SafeBuffer.Uninitialized.