Terraria: System.Runtime.InteropServices.SafeBuffer.Initialize
Initialize() [2/2]
void System.Runtime.InteropServices.SafeBuffer.Initialize (ulong numBytes) inline inherited
Definition at line 33 of file SafeBuffer.cs.
    {
        if (IntPtr.Size == 4)
        {
        }
        if (numBytes >= Uninitialized)
        {
            throw new ArgumentOutOfRangeException("numBytes", SR.ArgumentOutOfRange_UIntPtrMax);
        }
        _numBytes = (nuint)numBytes;
    }
References System.Runtime.InteropServices.SafeBuffer._numBytes, System.SR.ArgumentOutOfRange_UIntPtrMax, System.IntPtr.Size, and System.Runtime.InteropServices.SafeBuffer.Uninitialized.
Referenced by System.Security.SecureString.UnmanagedBuffer.Allocate(), System.IO.MemoryMappedFiles.MemoryMappedView.CreateView(), System.Runtime.InteropServices.SafeBuffer.Initialize(), System.Runtime.InteropServices.SafeBuffer.Initialize< T >(), System.Security.Principal.Win32.InitializeReferencedDomainsPointer(), and Microsoft.Win32.SafeHandles.SafeLocalAllocHandle.LocalAlloc().