Terraria: System.Security.Cryptography.ECDiffieHellman.ImportSubjectPublicKeyInfo
ImportSubjectPublicKeyInfo()
override void System.Security.Cryptography.ECDiffieHellman.ImportSubjectPublicKeyInfo (ReadOnlySpan< byte > source, out int bytesRead) inline virtual inherited
Reimplemented from System.Security.Cryptography.AsymmetricAlgorithm.
Definition at line 205 of file ECDiffieHellman.cs.
    {
        KeyFormatHelper.ReadSubjectPublicKeyInfo(s_validOids, source, (KeyFormatHelper.KeyReader<ECParameters>)EccKeyFormatHelper.FromECPublicKey, out int bytesRead2, out ECParameters ret);
        ImportParameters(ret);
        bytesRead = bytesRead2;
    }
References System.Security.Cryptography.EccKeyFormatHelper.FromECPublicKey(), System.Security.Cryptography.ECDiffieHellman.ImportParameters(), System.Security.Cryptography.KeyFormatHelper.ReadSubjectPublicKeyInfo(), System.Security.Cryptography.ECDiffieHellman.s_validOids, and System.source.
Referenced by System.Security.Cryptography.X509Certificates.PublicKey.GetECDiffieHellmanPublicKey().