Terraria: System.Security.Cryptography.ECDiffieHellman.ImportEncryptedPkcs8PrivateKey
ImportEncryptedPkcs8PrivateKey() [1/2]
unsafe override void System.Security.Cryptography.ECDiffieHellman.ImportEncryptedPkcs8PrivateKey (ReadOnlySpan< byte > passwordBytes, ReadOnlySpan< byte > source, out int bytesRead) inline virtual inherited
Reimplemented from System.Security.Cryptography.AsymmetricAlgorithm.
Reimplemented in System.Security.Cryptography.ECDiffieHellmanImplementation.ECDiffieHellmanCng, and System.Security.Cryptography.ECDiffieHellmanCng.
Definition at line 154 of file ECDiffieHellman.cs.
    {
        KeyFormatHelper.ReadEncryptedPkcs8(s_validOids, source, passwordBytes, (KeyFormatHelper.KeyReader<ECParameters>)EccKeyFormatHelper.FromECPrivateKey, out int bytesRead2, out ECParameters ret);
        fixed (byte* ptr = ret.D)
        {
            try
            {
                ImportParameters(ret);
                bytesRead = bytesRead2;
            }
            finally
            {
                CryptographicOperations.ZeroMemory(ret.D);
            }
        }
    }
References System.Security.Cryptography.EccKeyFormatHelper.FromECPrivateKey(), System.Security.Cryptography.ECDiffieHellman.ImportParameters(), System.Security.Cryptography.ECDiffieHellman.s_validOids, System.source, and System.Security.Cryptography.CryptographicOperations.ZeroMemory().
Referenced by System.Security.Cryptography.ECDiffieHellman.ImportFromEncryptedPem(), and System.Security.Cryptography.ECDiffieHellman.ImportFromEncryptedPem().