Terraria: System.Security.Cryptography.ECDiffieHellman.DerivedClassMustOverride
DerivedClassMustOverride()
static Exception System.Security.Cryptography.ECDiffieHellman.DerivedClassMustOverride () inline static private inherited
Definition at line 59 of file ECDiffieHellman.cs.
    {
        return new NotImplementedException(System.SR.NotSupported_SubclassOverride);
    }
References System.SR.NotSupported_SubclassOverride.
Referenced by System.Security.Cryptography.ECDiffieHellman.DeriveKeyFromHash(), System.Security.Cryptography.ECDiffieHellman.DeriveKeyFromHmac(), System.Security.Cryptography.ECDiffieHellman.DeriveKeyMaterial(), System.Security.Cryptography.ECDiffieHellman.DeriveKeyTls(), System.Security.Cryptography.ECDiffieHellman.ExportExplicitParameters(), System.Security.Cryptography.ECDiffieHellman.ExportParameters(), and System.Security.Cryptography.ECDiffieHellman.ImportParameters().