Terraria: System.Security.Cryptography.ECDiffieHellman.TryExportEncryptedPkcs8PrivateKey
TryExportEncryptedPkcs8PrivateKey() [1/2]
unsafe override bool System.Security.Cryptography.ECDiffieHellman.TryExportEncryptedPkcs8PrivateKey (ReadOnlySpan< byte > passwordBytes, PbeParameters pbeParameters, Span< byte > destination, out int bytesWritten) inline virtual inherited
Reimplemented from System.Security.Cryptography.AsymmetricAlgorithm.
Reimplemented in System.Security.Cryptography.ECDiffieHellmanImplementation.ECDiffieHellmanCng, and System.Security.Cryptography.ECDiffieHellmanCng.
Definition at line 84 of file ECDiffieHellman.cs.
    {
        if (pbeParameters == null)
        {
            throw new ArgumentNullException("pbeParameters");
        }
        PasswordBasedEncryption.ValidatePbeParameters(pbeParameters, ReadOnlySpan<char>.Empty, passwordBytes);
        ECParameters ecParameters = ExportParameters(includePrivateParameters: true);
        fixed (byte* ptr = ecParameters.D)
        {
            try
            {
                AsnWriter pkcs8Writer = EccKeyFormatHelper.WritePkcs8PrivateKey(ecParameters);
                AsnWriter asnWriter = KeyFormatHelper.WriteEncryptedPkcs8(passwordBytes, pkcs8Writer, pbeParameters);
                return asnWriter.TryEncode(destination, out bytesWritten);
            }
            finally
            {
                CryptographicOperations.ZeroMemory(ecParameters.D);
            }
        }
    }
References System.Security.Cryptography.ECParameters.D, System.destination, System.Security.Cryptography.ECDiffieHellman.ExportParameters(), System.Formats.Asn1.AsnWriter.TryEncode(), System.Security.Cryptography.PasswordBasedEncryption.ValidatePbeParameters(), System.Security.Cryptography.KeyFormatHelper.WriteEncryptedPkcs8(), System.Security.Cryptography.EccKeyFormatHelper.WritePkcs8PrivateKey(), and System.Security.Cryptography.CryptographicOperations.ZeroMemory().