Terraria: System.Security.Cryptography.ECDiffieHellman.ExportECPrivateKey
ExportECPrivateKey()
virtual unsafe byte[] System.Security.Cryptography.ECDiffieHellman.ExportECPrivateKey () inline virtual inherited
Definition at line 230 of file ECDiffieHellman.cs.
    {
        ECParameters ecParameters = ExportParameters(includePrivateParameters: true);
        fixed (byte* ptr = ecParameters.D)
        {
            try
            {
                AsnWriter asnWriter = EccKeyFormatHelper.WriteECPrivateKey(in ecParameters);
                return asnWriter.Encode();
            }
            finally
            {
                CryptographicOperations.ZeroMemory(ecParameters.D);
            }
        }
    }
References System.Security.Cryptography.ECParameters.D, System.Formats.Asn1.AsnWriter.Encode(), System.Security.Cryptography.ECDiffieHellman.ExportParameters(), System.Security.Cryptography.EccKeyFormatHelper.WriteECPrivateKey(), and System.Security.Cryptography.CryptographicOperations.ZeroMemory().