Terraria: BirthdayParty.ToggleManualParty
ToggleManualParty()
static void BirthdayParty.ToggleManualParty () inline static
     {
         bool partyIsUp = PartyIsUp;
         if (Main.netMode != 1)
         {
             ManualParty = !ManualParty;
         }
         else
         {
             NetMessage.SendData(111);
         }
         if (partyIsUp != PartyIsUp)
         {
             if (Main.netMode == 2)
             {
                 NetMessage.SendData(7);
             }
             CheckForAchievement();
         }
     }
References CheckForAchievement(), ManualParty, Main.netMode, PartyIsUp, and NetMessage.SendData().
Referenced by MessageBuffer.GetData(), Wiring.HitWireSingle(), and Player.TileInteractionsUse().