Terraria: System.Drawing.RectangleConverter.ConvertFrom
ConvertFrom() [1/2]
override? object System.Drawing.RectangleConverter.ConvertFrom (ITypeDescriptorContext? context, CultureInfo? culture, object value) inline virtual
Reimplemented from System.ComponentModel.TypeConverter.
Definition at line 32 of file RectangleConverter.cs.
    {
        if (value is string text)
        {
            string text2 = text.Trim();
            if (text2.Length == 0)
            {
                return null;
            }
            if (culture == null)
            {
                culture = CultureInfo.CurrentCulture;
            }
            char separator = culture.TextInfo.ListSeparator[0];
            string[] array = text2.Split(separator);
            int[] array2 = new int[array.Length];
            TypeConverter converterTrimUnsafe = TypeDescriptor.GetConverterTrimUnsafe(typeof(int));
            for (int i = 0; i < array2.Length; i++)
            {
                array2[i] = (int)converterTrimUnsafe.ConvertFromString(context, culture, array[i]);
            }
            if (array2.Length != 4)
            {
                throw new ArgumentException(System.SR.Format(System.SR.TextParseFailedFormat, "text", text2, "x, y, width, height"));
            }
            return new Rectangle(array2[0], array2[1], array2[2], array2[3]);
        }
        return base.ConvertFrom(context, culture, value);
    }
References System.array, System.ComponentModel.TypeConverter.ConvertFromString(), System.culture, System.Globalization.CultureInfo.CurrentCulture, System.SR.Format(), System.ComponentModel.TypeDescriptor.GetConverterTrimUnsafe(), System.text, System.SR.TextParseFailedFormat, and System.value.