Terraria: LockOnHelper.SetUP
SetUP()
static void LockOnHelper.SetUP () inline static
     {
         if (_canLockOn)
         {
             _ = AimedTarget;
             SetLockPosition(Main.ReverseGravitySupport(PredictedPosition - Main.screenPosition));
         }
     }
References _canLockOn, AimedTarget, PredictedPosition, Main.ReverseGravitySupport(), Main.screenPosition, and SetLockPosition().
Referenced by Main.DoUpdateInWorld(), and Player.ItemCheckWrapped().