Terraria: LockOnHelper.HandlePressing
HandlePressing()
static void LockOnHelper.HandlePressing () inline static private
     {
         if (UseMode == LockOnMode.TargetClosest)
         {
             SetActive(!_enabled);
         }
         else if (UseMode == LockOnMode.ThreeDS)
         {
             if (!_enabled)
             {
                 SetActive(on: true);
             }
             else
             {
                 CycleTargetThreeDS();
             }
         }
         else if (!_enabled)
         {
             SetActive(on: true);
         }
         else
         {
             CycleTargetFocus();
         }
     }
References _enabled, CycleTargetFocus(), CycleTargetThreeDS(), SetActive(), and UseMode.
Referenced by Toggle(), and Update().