Terraria: LockOnHelper.GetClosestTarget
GetClosestTarget()
static void LockOnHelper.GetClosestTarget (Vector2 position) inline static private
     {
         _pickedTarget = -1;
         float num = -1f;
         if (UseMode == LockOnMode.ThreeDS)
         {
             Vector2 center = Main.player[Main.myPlayer].Center;
             Vector2 value = Main.player[Main.myPlayer].DirectionTo(Main.MouseWorld);
             for (int i = 0; i < _targets.Count; i++)
             {
                 int num2 = _targets[i];
                 NPC obj = Main.npc[num2];
                 float num3 = Vector2.Dot(obj.DirectionFrom(center), value);
                 if (ValidTarget(obj) && (_pickedTarget == -1 || !(num3 <= num)))
                 {
                     _pickedTarget = i;
                     num = num3;
                 }
             }
             return;
         }
         for (int j = 0; j < _targets.Count; j++)
         {
             int num4 = _targets[j];
             NPC nPC = Main.npc[num4];
             if (ValidTarget(nPC) && (_pickedTarget == -1 || !(nPC.Distance(position) >= num)))
             {
                 _pickedTarget = j;
                 num = nPC.Distance(position);
             }
         }
     }
References _pickedTarget, _targets, Entity.Center, Entity.DirectionFrom(), Entity.DirectionTo(), Entity.Distance(), Main.MouseWorld, Main.myPlayer, Main.npc, Main.player, UseMode, and ValidTarget().
Referenced by CycleTargetThreeDS(), FindMostViableTarget(), and SetActive().