Terraria: LockOnHelper.Update
Update()
static void LockOnHelper.Update () inline static
     {
         _canLockOn = false;
         if (!CanUseLockonSystem())
         {
             SetActive(on: false);
             return;
         }
         if (--_lifeTimeArrowDisplay < 0)
         {
             _lifeTimeArrowDisplay = 0;
         }
         FindMostViableTarget(LockOnMode.ThreeDS, ref _threeDSTarget);
         FindMostViableTarget(LockOnMode.TargetClosest, ref _targetClosestTarget);
         if (PlayerInput.Triggers.JustPressed.LockOn && !PlayerInput.WritingText)
         {
             _lifeTimeCounter = 40;
             _lifeTimeArrowDisplay = 30;
             HandlePressing();
         }
         if (!_enabled)
         {
             return;
         }
         if (UseMode == LockOnMode.FocusTarget && PlayerInput.Triggers.Current.LockOn)
         {
             if (_lifeTimeCounter <= 0)
             {
                 SetActive(on: false);
                 return;
             }
             _lifeTimeCounter--;
         }
         NPC aimedTarget = AimedTarget;
         if (!ValidTarget(aimedTarget))
         {
             SetActive(on: false);
         }
         if (UseMode == LockOnMode.TargetClosest)
         {
             SetActive(on: false);
             SetActive(CanEnable());
         }
         if (_enabled)
         {
             Player player = Main.player[Main.myPlayer];
             Vector2 predictedPosition = PredictedPosition;
             bool flag = false;
             if (ShouldLockOn(player) && (ItemID.Sets.LockOnIgnoresCollision[player.inventory[player.selectedItem].type] || Collision.CanHit(player.Center, 0, 0, predictedPosition, 0, 0) || Collision.CanHitLine(player.Center, 0, 0, predictedPosition, 0, 0) || Collision.CanHit(player.Center, 0, 0, aimedTarget.Center, 0, 0) || Collision.CanHitLine(player.Center, 0, 0, aimedTarget.Center, 0, 0)))
             {
                 flag = true;
             }
             if (flag)
             {
                 _canLockOn = true;
             }
         }
     }
References _canLockOn, _enabled, _lifeTimeArrowDisplay, _lifeTimeCounter, _targetClosestTarget, _threeDSTarget, AimedTarget, CanEnable(), Collision.CanHit(), Collision.CanHitLine(), CanUseLockonSystem(), Entity.Center, TriggersPack.Current, FindMostViableTarget(), HandlePressing(), Player.inventory, TriggersPack.JustPressed, TriggersSet.LockOn, ItemID.Sets.LockOnIgnoresCollision, Main.myPlayer, Main.player, PredictedPosition, Player.selectedItem, SetActive(), ShouldLockOn(), PlayerInput.Triggers, Item.type, UseMode, ValidTarget(), and PlayerInput.WritingText.
Referenced by Player.Update().