Terraria: LockOnHelper.CycleTargetThreeDS
CycleTargetThreeDS()
static void LockOnHelper.CycleTargetThreeDS () inline static private
     {
         int num = _targets[_pickedTarget];
         RefreshTargets(Main.MouseWorld, 2000f);
         GetClosestTarget(Main.MouseWorld);
         if (_targets.Count < 1 || (_targets.Count == 1 && num == _targets[0]) || num == _targets[_pickedTarget])
         {
             SetActive(on: false);
         }
     }
References _pickedTarget, _targets, GetClosestTarget(), Main.MouseWorld, RefreshTargets(), and SetActive().
Referenced by HandlePressing().