Terraria: LockOnHelper.CycleTargetFocus
CycleTargetFocus()
static void LockOnHelper.CycleTargetFocus () inline static private
     {
         int num = _targets[_pickedTarget];
         RefreshTargets(Main.MouseWorld, 2000f);
         if (_targets.Count < 1 || (_targets.Count == 1 && num == _targets[0]))
         {
             SetActive(on: false);
             return;
         }
         _pickedTarget = 0;
         for (int i = 0; i < _targets.Count; i++)
         {
             if (_targets[i] > num)
             {
                 _pickedTarget = i;
                 break;
             }
         }
     }
References _pickedTarget, _targets, Main.MouseWorld, RefreshTargets(), and SetActive().
Referenced by HandlePressing().