Terraria: LockOnHelper.Draw
Draw()
static void LockOnHelper.Draw (SpriteBatch spriteBatch) inline static
     {
         if (Main.gameMenu)
         {
             return;
         }
         Texture2D value = TextureAssets.LockOnCursor.Value;
         Rectangle rectangle = new Rectangle(0, 0, value.Width, 12);
         Rectangle rectangle2 = new Rectangle(0, 16, value.Width, 12);
         Color t = Main.OurFavoriteColor.MultiplyRGBA(new Color(0.75f, 0.75f, 0.75f, 1f));
         t.A = 220;
         Color t2 = Main.OurFavoriteColor;
         t2.A = 220;
         float num = 0.94f + (float)Math.Sin(Main.GlobalTimeWrappedHourly * ((float)Math.PI * 2f)) * 0.06f;
         t2 *= num;
         t *= num;
         Utils.Swap(ref t, ref t2);
         Color color = t.MultiplyRGBA(new Color(0.8f, 0.8f, 0.8f, 0.8f));
         Color color2 = t.MultiplyRGBA(new Color(0.8f, 0.8f, 0.8f, 0.8f));
         float gravDir = Main.player[Main.myPlayer].gravDir;
         float num2 = 1f;
         float num3 = 0.1f;
         float num4 = 0.8f;
         float num5 = 1f;
         float num6 = 10f;
         float num7 = 10f;
         bool flag = false;
         for (int i = 0; i < _drawProgress.GetLength(0); i++)
         {
             int num8 = 0;
             if (_pickedTarget != -1 && _targets.Count > 0 && i == _targets[_pickedTarget])
             {
                 num8 = 2;
             }
             else if ((flag && _targets.Contains(i)) || (UseMode == LockOnMode.ThreeDS && _threeDSTarget == i) || (UseMode == LockOnMode.TargetClosest && _targetClosestTarget == i))
             {
                 num8 = 1;
             }
             _drawProgress[i, 0] = MathHelper.Clamp(_drawProgress[i, 0] + ((num8 == 1) ? num3 : (0f - num3)), 0f, 1f);
             _drawProgress[i, 1] = MathHelper.Clamp(_drawProgress[i, 1] + ((num8 == 2) ? num3 : (0f - num3)), 0f, 1f);
             float num9 = _drawProgress[i, 0];
             if (num9 > 0f)
             {
                 float num10 = 1f - num9 * num9;
                 Vector2 pos = Main.npc[i].Top + new Vector2(0f, 0f - num7 - num10 * num6) * gravDir - Main.screenPosition;
                 pos = Main.ReverseGravitySupport(pos, Main.npc[i].height);
                 spriteBatch.Draw(value, pos, rectangle, color * num9, 0f, rectangle.Size() / 2f, new Vector2(0.58f, 1f) * num2 * num4 * (1f + num9) / 2f, SpriteEffects.None, 0f);
                 spriteBatch.Draw(value, pos, rectangle2, color2 * num9 * num9, 0f, rectangle2.Size() / 2f, new Vector2(0.58f, 1f) * num2 * num4 * (1f + num9) / 2f, SpriteEffects.None, 0f);
             }
             float num11 = _drawProgress[i, 1];
             if (num11 > 0f)
             {
                 int num12 = Main.npc[i].width;
                 if (Main.npc[i].height > num12)
                 {
                     num12 = Main.npc[i].height;
                 }
                 num12 += 20;
                 if ((float)num12 < 70f)
                 {
                     num5 *= (float)num12 / 70f;
                 }
                 float num13 = 3f;
                 Vector2 vector = Main.npc[i].Center;
                 if (_targets.Count >= 0 && _pickedTarget >= 0 && _pickedTarget < _targets.Count && i == _targets[_pickedTarget] && NPC.GetNPCLocation(i, seekHead: true, averageDirection: false, out var _, out var pos2))
                 {
                     vector = pos2;
                 }
                 for (int j = 0; (float)j < num13; j++)
                 {
                     float num14 = (float)Math.PI * 2f / num13 * (float)j + Main.GlobalTimeWrappedHourly * ((float)Math.PI * 2f) * 0.25f;
                     Vector2 vector2 = new Vector2(0f, num12 / 2).RotatedBy(num14);
                     Vector2 pos3 = vector + vector2 - Main.screenPosition;
                     pos3 = Main.ReverseGravitySupport(pos3);
                     float rotation = num14 * (float)((gravDir == 1f) ? 1 : (-1)) + (float)Math.PI * (float)((gravDir == 1f) ? 1 : 0);
                     spriteBatch.Draw(value, pos3, rectangle, t * num11, rotation, rectangle.Size() / 2f, new Vector2(0.58f, 1f) * num2 * num5 * (1f + num11) / 2f, SpriteEffects.None, 0f);
                     spriteBatch.Draw(value, pos3, rectangle2, t2 * num11 * num11, rotation, rectangle2.Size() / 2f, new Vector2(0.58f, 1f) * num2 * num5 * (1f + num11) / 2f, SpriteEffects.None, 0f);
                 }
             }
         }
     }
References _drawProgress, _pickedTarget, _targetClosestTarget, _targets, _threeDSTarget, Entity.Center, Color, Main.gameMenu, NPC.GetNPCLocation(), Main.GlobalTimeWrappedHourly, Player.gravDir, Entity.height, TextureAssets.LockOnCursor, Main.myPlayer, Main.npc, Main.OurFavoriteColor, Main.player, Main.ReverseGravitySupport(), Main.screenPosition, Entity.Top, UseMode, Asset< T >.Value, and Entity.width.
Referenced by Main.DrawInterface_5_GamepadLockOn().