Terraria: System.ArraySegment.ThrowInvalidOperationIfDefault
ThrowInvalidOperationIfDefault()
void System.ArraySegment< T >.ThrowInvalidOperationIfDefault () inline private
Definition at line 322 of file ArraySegment.cs.
    {
        if (_array == null)
        {
            ThrowHelper.ThrowInvalidOperationException(ExceptionResource.InvalidOperation_NullArray);
        }
    }
References System.ArraySegment< T >._array, and System.ThrowHelper.ThrowInvalidOperationException().
Referenced by System.ArraySegment< T >.Contains(), System.ArraySegment< T >.CopyTo(), System.ArraySegment< T >.CopyTo(), System.ArraySegment< T >.GetEnumerator(), System.ArraySegment< T >.IndexOf(), System.ArraySegment< T >.Slice(), System.ArraySegment< T >.Slice(), and System.ArraySegment< T >.ToArray().