Terraria: Terraria.GameContent.Generation.ShapeFloodFill.Perform
Perform()
override bool Terraria.GameContent.Generation.ShapeFloodFill.Perform (Point origin, GenAction action) inline
Definition at line 17 of file ShapeFloodFill.cs.
    {
        Queue<Point> queue = new Queue<Point>();
        HashSet<Point16> hashSet = new HashSet<Point16>();
        queue.Enqueue(origin);
        int num = _maximumActions;
        while (queue.Count > 0 && num > 0)
        {
            Point point = queue.Dequeue();
            if (!hashSet.Contains(new Point16(point.X, point.Y)) && UnitApply(action, origin, point.X, point.Y))
            {
                hashSet.Add(new Point16(point));
                num--;
                if (point.X + 1 < Main.maxTilesX - 1)
                {
                    queue.Enqueue(new Point(point.X + 1, point.Y));
                }
                if (point.X - 1 >= 1)
                {
                    queue.Enqueue(new Point(point.X - 1, point.Y));
                }
                if (point.Y + 1 < Main.maxTilesY - 1)
                {
                    queue.Enqueue(new Point(point.X, point.Y + 1));
                }
                if (point.Y - 1 >= 1)
                {
                    queue.Enqueue(new Point(point.X, point.Y - 1));
                }
            }
        }
        while (queue.Count > 0)
        {
            Point item = queue.Dequeue();
            if (!hashSet.Contains(new Point16(item.X, item.Y)))
            {
                queue.Enqueue(item);
                break;
            }
        }
        return queue.Count == 0;
    }
References Terraria.GameContent.Generation.ShapeFloodFill._maximumActions, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Collections.Generic.Dictionary< TKey, TValue >.Contains(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.WorldBuilding.GenShape.UnitApply(), Microsoft.Xna.Framework.Point.X, and Microsoft.Xna.Framework.Point.Y.