Terraria: System.Xml.XmlReader.GetValueAsync
GetValueAsync()
virtual Task< string > System.Xml.XmlReader.GetValueAsync () inline virtual inherited
Reimplemented in System.Xml.XmlAsyncCheckReader, System.Xml.XmlSubtreeReader, System.Xml.XmlTextReaderImpl, System.Xml.XmlValidatingReaderImpl, System.Xml.XmlWrappingReader, System.Xml.XsdCachingReader, and System.Xml.XsdValidatingReader.
Definition at line 1495 of file XmlReader.cs.
    {
        throw new NotImplementedException();
    }
Referenced by System.Xml.XmlAsyncCheckReader.GetValueAsync(), System.Xml.XmlSubtreeReader.GetValueAsync(), System.Xml.XmlValidatingReaderImpl.GetValueAsync(), System.Xml.XmlWrappingReader.GetValueAsync(), System.Xml.XsdValidatingReader.GetValueAsync(), System.Xml.XmlReader.InternalReadContentAsStringAsync(), System.Xml.XmlCharCheckingReader.ReadAsync(), System.Xml.XsdCachingReader.ReadAsync(), System.Xml.ReadContentAsBinaryHelper.ReadContentAsBinaryAsync(), System.Xml.XmlReader.WriteNodeAsync(), and System.Xml.XmlWriter.WriteNodeAsync_CallAsyncReader().