Terraria: System.Xml.XmlReader.GetAttribute
GetAttribute() [2/3]
string? System.Xml.XmlReader.GetAttribute (string name) abstract
Referenced by System.Data.DataSet.DetermineSchemaSerializationMode(), System.Xml.Serialization.XmlSerializationReader.GetArrayLength(), System.Data.DataTextReader.GetAttribute(), System.Runtime.Serialization.XmlReaderDelegator.GetAttribute(), System.Runtime.Serialization.XmlSerializableReader.GetAttribute(), System.Xml.XmlAsyncCheckReader.GetAttribute(), System.Xml.XmlSqlBinaryReader.GetAttribute(), System.Xml.XmlSubtreeReader.GetAttribute(), System.Xml.XmlValidatingReaderImpl.GetAttribute(), System.Xml.XmlWrappingReader.GetAttribute(), System.Xml.XsdValidatingReader.GetAttribute(), System.Xml.XmlDictionaryReader.XmlWrappedReader.GetAttribute(), System.Data.DataTextReader.GetAttribute(), System.Xml.XmlValidatingReaderImpl.GetAttribute(), System.Data.DataTextReader.GetAttribute(), System.Runtime.Serialization.XmlReaderDelegator.GetAttribute(), System.Runtime.Serialization.XmlSerializableReader.GetAttribute(), System.Xml.XmlDictionaryReader.XmlWrappedReader.GetAttribute(), System.Xml.XmlAsyncCheckReader.GetAttribute(), System.Xml.XmlSqlBinaryReader.GetAttribute(), System.Xml.XmlSubtreeReader.GetAttribute(), System.Xml.XmlValidatingReaderImpl.GetAttribute(), System.Xml.XmlWrappingReader.GetAttribute(), System.Xml.XsdValidatingReader.GetAttribute(), System.Runtime.Serialization.XmlReaderDelegator.GetAttribute(), System.Runtime.Serialization.XmlSerializableReader.GetAttribute(), System.Xml.XmlDictionaryReader.XmlWrappedReader.GetAttribute(), System.Xml.XmlAsyncCheckReader.GetAttribute(), System.Xml.XmlSubtreeReader.GetAttribute(), System.Xml.XmlWrappingReader.GetAttribute(), System.Xml.XsdValidatingReader.GetAttribute(), System.Xml.XmlSqlBinaryReader.GetAttribute(), System.Xml.Serialization.XmlSerializationReader.GetNullAttr(), System.Xml.Serialization.XmlSerializationReader.GetXsiType(), System.Data.XmlDataLoader.LoadColumn(), System.Xml.XmlCharCheckingReader.Read(), System.Xml.Serialization.XmlSerializationReader.ReadArray(), System.Xml.XmlCharCheckingReader.ReadAsync(), System.Xml.Linq.XNode.ReadFromAsyncInternal(), System.Xml.Serialization.XmlSerializationReader.ReadReference(), System.Xml.Serialization.XmlSerializationReader.ReadReferencingElement(), System.Data.SqlTypes.SqlBinary.ReadXml(), System.Data.SqlTypes.SqlBoolean.ReadXml(), System.Data.SqlTypes.SqlByte.ReadXml(), System.Data.SqlTypes.SqlDateTime.ReadXml(), System.Data.SqlTypes.SqlDecimal.ReadXml(), System.Data.SqlTypes.SqlDouble.ReadXml(), System.Data.SqlTypes.SqlGuid.ReadXml(), System.Data.SqlTypes.SqlInt16.ReadXml(), System.Data.SqlTypes.SqlInt32.ReadXml(), System.Data.SqlTypes.SqlInt64.ReadXml(), System.Data.SqlTypes.SqlMoney.ReadXml(), System.Data.SqlTypes.SqlSingle.ReadXml(), System.Data.SqlTypes.SqlString.ReadXml(), System.Data.DataSet.ReadXml(), System.Data.DataTable.ReadXml(), System.Data.DataSet.ReadXml(), System.Data.DataTable.ReadXml(), System.Data.DataSet.ReadXmlSchema(), System.Data.DataSet.ReadXmlSerializable(), System.Data.DataSet.ReadXSDSchema(), System.Xml.XmlReader.XmlReaderDebuggerDisplayProxy.ToString(), System.Xml.XmlWriter.WriteNode(), System.Xml.XmlReader.WriteNode(), System.Xml.XmlReader.WriteNodeAsync(), System.Xml.XmlWriter.WriteNodeAsync_CallAsyncReader(), and System.Xml.XmlWriter.WriteNodeAsync_CallSyncReader().