Terraria: System.Xml.XmlReader.ReadAsync
ReadAsync()
virtual Task< bool > System.Xml.XmlReader.ReadAsync () inline virtual inherited
Reimplemented in System.Xml.XmlAsyncCheckReader, System.Xml.XmlCharCheckingReader, System.Xml.XmlSubtreeReader, System.Xml.XmlTextReaderImpl, System.Xml.XmlValidatingReaderImpl, System.Xml.XmlWrappingReader, System.Xml.XsdCachingReader, and System.Xml.XsdValidatingReader.
Definition at line 1576 of file XmlReader.cs.
    {
        throw new NotImplementedException();
    }
Referenced by System.Xml.ReadContentAsBinaryHelper.FinishAsync(), System.Xml.XmlTextReaderImpl.FinishReadElementContentAsBinaryAsync(), System.Xml.XmlReader.FinishReadElementContentAsXxxAsync(), System.Xml.ReadContentAsBinaryHelper.InitOnElementAsync(), System.Xml.XmlTextReaderImpl.InitReadElementContentAsBinaryAsync(), System.Xml.XmlReader.InternalReadContentAsStringAsync(), System.Xml.Linq.XDocument.LoadAsyncInternal(), System.Xml.XmlReader.MoveToContentAsync(), System.Xml.ReadContentAsBinaryHelper.MoveToNextContentNodeAsync(), System.Xml.XmlTextReaderImpl.MoveToNextContentNodeAsync(), System.Xml.XsdValidatingReader.ProcessInlineSchemaAsync(), System.Xml.XmlAsyncCheckReader.ReadAsync(), System.Xml.XmlCharCheckingReader.ReadAsync(), System.Xml.XmlSubtreeReader.ReadAsync(), System.Xml.XmlValidatingReaderImpl.ReadAsync(), System.Xml.XmlWrappingReader.ReadAsync(), System.Xml.XsdCachingReader.ReadAsync(), System.Xml.XsdValidatingReader.ReadAsync(), System.Xml.ReadContentAsBinaryHelper.ReadElementContentAsBinaryAsync(), System.Xml.XmlTextReaderImpl.ReadElementContentAsBinaryAsync(), System.Xml.Linq.XNode.ReadFromAsyncInternal(), System.Xml.XmlReader.ReadInnerXmlAsync(), System.Xml.XmlReader.ReadOuterXmlAsync(), System.Xml.XsdValidatingReader.ReadTillEndElementAsync(), System.Xml.XmlValidatingReaderImpl.ResolveEntityInternallyAsync(), System.Xml.XmlReader.SetupReadElementContentAsXxxAsync(), System.Xml.XmlSubtreeReader.SkipAsync(), System.Xml.XmlTextReaderImpl.SkipAsync(), System.Xml.XsdCachingReader.SkipAsync(), System.Xml.XmlReader.SkipSubtreeAsync(), System.Xml.Schema.Parser.StartParsingAsync(), System.Xml.XmlReader.WriteNodeAsync(), and System.Xml.XmlWriter.WriteNodeAsync_CallAsyncReader().