Terraria: System.Xml.XmlReader.ReadContentAsBoolean
ReadContentAsBoolean()
virtual bool System.Xml.XmlReader.ReadContentAsBoolean () inline virtual inherited
Reimplemented in System.Runtime.Serialization.XmlSerializableReader, System.Xml.XmlBaseReader, System.Xml.XmlDictionaryReader.XmlWrappedReader, System.Xml.XmlAsyncCheckReader, System.Xml.XmlSqlBinaryReader, System.Xml.XmlSubtreeReader, and System.Xml.XsdValidatingReader.
Definition at line 158 of file XmlReader.cs.
    {
        if (!CanReadContentAs())
        {
            throw CreateReadContentAsException("ReadContentAsBoolean");
        }
        try
        {
            return XmlConvert.ToBoolean(InternalReadContentAsString());
        }
        catch (FormatException innerException)
        {
            throw new XmlException(System.SR.Xml_ReadContentAsFormatException, "Boolean", innerException, this as IXmlLineInfo);
        }
    }
References System.Xml.XmlReader.CanReadContentAs(), System.Xml.XmlReader.CreateReadContentAsException(), System.Xml.Dictionary, System.Xml.XmlReader.InternalReadContentAsString(), System.Xml.XmlConvert.ToBoolean(), System.SR.Xml_ReadContentAsFormatException, and System.Xml.XmlException.
Referenced by System.Runtime.Serialization.XmlReaderDelegator.ReadContentAsBoolean(), System.Runtime.Serialization.XmlSerializableReader.ReadContentAsBoolean(), System.Xml.XmlDictionaryReader.XmlWrappedReader.ReadContentAsBoolean(), System.Xml.XmlAsyncCheckReader.ReadContentAsBoolean(), System.Xml.XmlSubtreeReader.ReadContentAsBoolean(), System.Xml.XmlDictionaryReader.ReadElementContentAsBoolean(), System.Xml.XmlReader.ReadElementContentAsBoolean(), and System.Xml.XmlBinaryWriter.WriteTextNode().