Terraria: System.Xml.XmlReader.ReadValueChunkAsync
ReadValueChunkAsync()
virtual Task< int > System.Xml.XmlReader.ReadValueChunkAsync (char[] buffer, int index, int count) inline virtual inherited
Reimplemented in System.Xml.XmlAsyncCheckReader, System.Xml.XmlSubtreeReader, and System.Xml.XmlTextReaderImpl.
Definition at line 1610 of file XmlReader.cs.
    {
        throw new NotSupportedException(System.SR.Xml_ReadValueChunkNotSupported);
    }
References System.SR.Xml_ReadValueChunkNotSupported.
Referenced by System.Xml.ReadContentAsBinaryHelper.ReadContentAsBinaryAsync(), System.Xml.XmlAsyncCheckReader.ReadValueChunkAsync(), System.Xml.XmlSubtreeReader.ReadValueChunkAsync(), and System.Xml.XmlWriter.WriteNodeAsync_CallAsyncReader().