Terraria: System.Xml.XmlReader.ReadContentAsDouble
ReadContentAsDouble()
virtual double System.Xml.XmlReader.ReadContentAsDouble () inline virtual inherited
Reimplemented in System.Runtime.Serialization.XmlSerializableReader, System.Xml.XmlBaseReader, System.Xml.XmlDictionaryReader.XmlWrappedReader, System.Xml.XmlAsyncCheckReader, System.Xml.XmlSqlBinaryReader, System.Xml.XmlSubtreeReader, and System.Xml.XsdValidatingReader.
Definition at line 206 of file XmlReader.cs.
    {
        if (!CanReadContentAs())
        {
            throw CreateReadContentAsException("ReadContentAsDouble");
        }
        try
        {
            return XmlConvert.ToDouble(InternalReadContentAsString());
        }
        catch (FormatException innerException)
        {
            throw new XmlException(System.SR.Xml_ReadContentAsFormatException, "Double", innerException, this as IXmlLineInfo);
        }
    }
References System.Xml.XmlReader.CanReadContentAs(), System.Xml.XmlReader.CreateReadContentAsException(), System.Xml.Dictionary, System.Xml.XmlReader.InternalReadContentAsString(), System.Xml.XmlConvert.ToDouble(), System.SR.Xml_ReadContentAsFormatException, and System.Xml.XmlException.
Referenced by System.Runtime.Serialization.XmlReaderDelegator.ReadContentAsDouble(), System.Runtime.Serialization.XmlSerializableReader.ReadContentAsDouble(), System.Xml.XmlDictionaryReader.XmlWrappedReader.ReadContentAsDouble(), System.Xml.XmlAsyncCheckReader.ReadContentAsDouble(), System.Xml.XmlSubtreeReader.ReadContentAsDouble(), System.Xml.XmlDictionaryReader.ReadElementContentAsDouble(), System.Xml.XmlReader.ReadElementContentAsDouble(), and System.Xml.XmlBinaryWriter.WriteTextNode().