Terraria: System.Xml.XmlReader.MoveToElement
MoveToElement()
bool System.Xml.XmlReader.MoveToElement () abstract
Referenced by System.Xml.XPath.XPathNavigator.BuildSubtree(), System.Xml.XmlSubtreeReader.Close(), System.Xml.Schema.Parser.LoadElementNode(), System.Xml.XmlLoader.LoadNode(), System.Xml.XmlReader.MoveToAttribute(), System.Xml.XmlReader.MoveToContent(), System.Xml.XmlReader.MoveToContentAsync(), System.Data.DataTextReader.MoveToElement(), System.Runtime.Serialization.XmlReaderDelegator.MoveToElement(), System.Runtime.Serialization.XmlSerializableReader.MoveToElement(), System.Xml.XmlDictionaryReader.XmlWrappedReader.MoveToElement(), System.Xml.XmlAsyncCheckReader.MoveToElement(), System.Xml.XmlCharCheckingReader.MoveToElement(), System.Xml.XmlSqlBinaryReader.MoveToElement(), System.Xml.XmlSubtreeReader.MoveToElement(), System.Xml.XmlValidatingReaderImpl.MoveToElement(), System.Xml.XmlWrappingReader.MoveToElement(), System.Xml.XsdValidatingReader.MoveToElement(), System.Xml.XmlSubtreeReader.MoveToNsAttribute(), System.Xml.Schema.Parser.ParseReaderNode(), System.Xml.XsdValidatingReader.ProcessElementEvent(), System.Xml.XsdValidatingReader.ProcessElementEventAsync(), System.Xml.XmlSubtreeReader.ProcessNamespaces(), System.Runtime.Serialization.XmlReaderDelegator.Read(), System.Xml.XmlCharCheckingReader.Read(), System.Xml.XmlSubtreeReader.Read(), System.Xml.XmlCharCheckingReader.ReadAsync(), System.Xml.XmlSubtreeReader.ReadAsync(), System.Xml.Xsl.Xslt.XsltInput.ReadElement(), System.Xml.XmlReader.ReadString(), System.Xml.XmlDictionaryReader.ReadString(), System.Xml.XsdCachingReader.RecordAttributes(), System.Xml.XmlSubtreeReader.Skip(), System.Xml.XmlTextReaderImpl.Skip(), System.Xml.XmlSubtreeReader.SkipAsync(), System.Xml.XmlTextReaderImpl.SkipAsync(), System.Xml.XmlReader.SkipSubtree(), System.Xml.XmlReader.SkipSubtreeAsync(), System.Xml.XsdValidatingReader.ValidateAttributes(), System.Xml.XmlWriter.WriteAttributes(), System.Xml.XmlWriter.WriteAttributesAsync(), and System.Xml.XmlDictionaryWriter.WriteElementNode().