Terraria: System.Xml.XmlReader.ResolveEntity
ResolveEntity()
void System.Xml.XmlReader.ResolveEntity () abstract
Referenced by System.Xml.XPath.XPathNavigator.BuildSubtree(), System.Xml.Xsl.Xslt.XsltInput.FillupCharacterEntityRecord(), System.Xml.XmlReader.InternalReadContentAsString(), System.Xml.XmlReader.InternalReadContentAsStringAsync(), System.Xml.XmlLoader.LoadAttributeNode(), System.Xml.XmlLoader.LoadAttributeValue(), System.Xml.Schema.Parser.LoadEntityReferenceInAttribute(), System.Xml.XmlLoader.LoadEntityReferenceNode(), System.Xml.XPath.XPathDocument.LoadFromReader(), System.Xml.ReadContentAsBinaryHelper.MoveToNextContentNode(), System.Xml.XmlTextReaderImpl.MoveToNextContentNode(), System.Xml.ReadContentAsBinaryHelper.MoveToNextContentNodeAsync(), System.Xml.XmlTextReaderImpl.MoveToNextContentNodeAsync(), System.Xml.Xsl.Xslt.XsltInput.ReadAttribute(), System.Xml.XmlDictionaryReader.ReadContentAsString(), System.Xml.Xsl.Xslt.XsltInput.ReadTextNodes(), System.Data.DataTextReader.ResolveEntity(), System.Runtime.Serialization.XmlSerializableReader.ResolveEntity(), System.Xml.XmlDictionaryReader.XmlWrappedReader.ResolveEntity(), System.Xml.XmlAsyncCheckReader.ResolveEntity(), System.Xml.XmlValidatingReaderImpl.ResolveEntity(), System.Xml.XmlWrappingReader.ResolveEntity(), System.Xml.XmlValidatingReaderImpl.ResolveEntityInternally(), and System.Xml.XmlValidatingReaderImpl.ResolveEntityInternallyAsync().