Terraria: System.Xml.XmlReader.ReadOuterXml
ReadOuterXml()
virtual string System.Xml.XmlReader.ReadOuterXml () inline virtual inherited
Reimplemented in System.Xml.XmlDictionaryReader.XmlWrappedReader, System.Xml.Xsl.XsltOld.ReaderOutput, and System.Xml.XmlAsyncCheckReader.
Definition at line 1057 of file XmlReader.cs.
    {
        if (ReadState != ReadState.Interactive)
        {
            return string.Empty;
        }
        if (NodeType != XmlNodeType.Attribute && NodeType != XmlNodeType.Element)
        {
            Read();
            return string.Empty;
        }
        StringWriter stringWriter = new StringWriter(CultureInfo.InvariantCulture);
        XmlWriter xmlWriter = CreateWriterForInnerOuterXml(stringWriter);
        try
        {
            if (NodeType == XmlNodeType.Attribute)
            {
                xmlWriter.WriteStartAttribute(Prefix, LocalName, NamespaceURI);
                WriteAttributeValue(xmlWriter);
                xmlWriter.WriteEndAttribute();
            }
            else
            {
                xmlWriter.WriteNode(this, defattr: false);
            }
        }
        finally
        {
            xmlWriter.Close();
        }
        return stringWriter.ToString();
    }
References System.Xml.XmlReader.CreateWriterForInnerOuterXml(), System.Xml.Dictionary, System.Globalization.CultureInfo.InvariantCulture, System.Xml.XmlReader.LocalName, System.Xml.XmlReader.NamespaceURI, System.Xml.XmlReader.NodeType, System.Xml.XmlReader.Prefix, System.Xml.XmlReader.Read(), and System.Xml.XmlReader.WriteAttributeValue().
Referenced by System.Xml.XmlDictionaryReader.XmlWrappedReader.ReadOuterXml(), and System.Xml.XmlAsyncCheckReader.ReadOuterXml().