Terraria: System.Xml.XmlReader.MoveToContentAsync
MoveToContentAsync()
virtual async Task< XmlNodeType > System.Xml.XmlReader.MoveToContentAsync () inline virtual inherited
Reimplemented in System.Xml.XmlAsyncCheckReader.
Definition at line 1615 of file XmlReader.cs.
    {
        do
        {
            switch (NodeType)
            {
            case XmlNodeType.Attribute:
                MoveToElement();
                break;
            case XmlNodeType.Element:
            case XmlNodeType.Text:
            case XmlNodeType.CDATA:
            case XmlNodeType.EntityReference:
            case XmlNodeType.EndElement:
            case XmlNodeType.EndEntity:
                break;
            default:
                continue;
            }
            return NodeType;
        }
        while (await ReadAsync().ConfigureAwait(continueOnCapturedContext: false));
        return NodeType;
    }
References System.Xml.Dictionary, System.Xml.XmlReader.MoveToElement(), System.Xml.XmlReader.NodeType, and System.Xml.XmlReader.ReadAsync().
Referenced by System.Xml.Linq.XElement.LoadAsyncInternal(), and System.Xml.XmlAsyncCheckReader.MoveToContentAsync().