Terraria: System.Xml.XmlReader.ReadElementString
ReadElementString() [3/3]
virtual string System.Xml.XmlReader.ReadElementString (string name) inline virtual inherited
Reimplemented in System.Xml.XmlAsyncCheckReader.
Definition at line 696 of file XmlReader.cs.
    {
        string result = string.Empty;
        if (MoveToContent() != XmlNodeType.Element)
        {
            throw new XmlException(System.SR.Xml_InvalidNodeType, NodeType.ToString(), this as IXmlLineInfo);
        }
        if (Name != name)
        {
            throw new XmlException(System.SR.Xml_ElementNotFound, name, this as IXmlLineInfo);
        }
        if (!IsEmptyElement)
        {
            result = ReadString();
            if (NodeType != XmlNodeType.EndElement)
            {
                throw new XmlException(System.SR.Xml_InvalidNodeType, NodeType.ToString(), this as IXmlLineInfo);
            }
            Read();
        }
        else
        {
            Read();
        }
        return result;
    }
References System.Xml.Dictionary, System.Xml.XmlReader.IsEmptyElement, System.Xml.XmlReader.MoveToContent(), System.Xml.XmlReader.Name, System.Xml.XmlReader.NodeType, System.Xml.XmlReader.Read(), System.Xml.XmlReader.ReadString(), System.SR.Xml_ElementNotFound, System.SR.Xml_InvalidNodeType, and System.Xml.XmlException.