Terraria: System.Xml.XmlReader.ReadToFollowing
ReadToFollowing() [2/2]
virtual bool System.Xml.XmlReader.ReadToFollowing (string name) inline virtual inherited
Reimplemented in System.Xml.XmlAsyncCheckReader.
Definition at line 787 of file XmlReader.cs.
    {
        if (name == null || name.Length == 0)
        {
            throw XmlConvert.CreateInvalidNameArgumentException(name, "name");
        }
        name = NameTable.Add(name);
        while (Read())
        {
            if (NodeType == XmlNodeType.Element && Ref.Equal(name, Name))
            {
                return true;
            }
        }
        return false;
    }
References System.Xml.NameTable.Add(), System.Xml.XmlConvert.CreateInvalidNameArgumentException(), System.Xml.Ref.Equal(), System.Xml.XmlReader.Name, System.Xml.XmlReader.NodeType, and System.Xml.XmlReader.Read().
Referenced by System.Xml.XmlAsyncCheckReader.ReadToFollowing(), and System.Xml.XmlAsyncCheckReader.ReadToFollowing().