Terraria: System.Xml.XmlReader.ReadElementContentAsBoolean
ReadElementContentAsBoolean() [1/2]
virtual bool System.Xml.XmlReader.ReadElementContentAsBoolean () inline virtual inherited
Reimplemented in System.Xml.XmlBinaryReader, System.Xml.XmlDictionaryReader, System.Xml.XmlAsyncCheckReader, and System.Xml.XsdValidatingReader.
Definition at line 337 of file XmlReader.cs.
    {
        if (SetupReadElementContentAsXxx("ReadElementContentAsBoolean"))
        {
            bool result = ReadContentAsBoolean();
            FinishReadElementContentAsXxx();
            return result;
        }
        return XmlConvert.ToBoolean(string.Empty);
    }
References System.Xml.XmlReader.FinishReadElementContentAsXxx(), System.Xml.XmlReader.ReadContentAsBoolean(), System.Xml.XmlReader.SetupReadElementContentAsXxx(), and System.Xml.XmlConvert.ToBoolean().
Referenced by System.Runtime.Serialization.XmlReaderDelegator.ReadElementContentAsBoolean(), System.Xml.XmlAsyncCheckReader.ReadElementContentAsBoolean(), System.Xml.XmlAsyncCheckReader.ReadElementContentAsBoolean(), and System.Xml.XmlReader.ReadElementContentAsBoolean().