Terraria: System.Xml.XmlReader.ReadContentAsString
ReadContentAsString()
virtual string System.Xml.XmlReader.ReadContentAsString () inline virtual inherited
Reimplemented in System.Runtime.Serialization.XmlSerializableReader, System.Xml.XmlBaseReader, System.Xml.XmlDictionaryReader.XmlWrappedReader, System.Xml.XmlDictionaryReader, System.Xml.XmlAsyncCheckReader, System.Xml.XmlSubtreeReader, and System.Xml.XsdValidatingReader.
Definition at line 286 of file XmlReader.cs.
    {
        if (!CanReadContentAs())
        {
            throw CreateReadContentAsException("ReadContentAsString");
        }
        return InternalReadContentAsString();
    }
References System.Xml.XmlReader.CanReadContentAs(), System.Xml.XmlReader.CreateReadContentAsException(), and System.Xml.XmlReader.InternalReadContentAsString().
Referenced by System.Runtime.Serialization.XmlReaderDelegator.ReadContentAsBase64(), System.Runtime.Serialization.XmlReaderDelegator.ReadContentAsGuid(), System.Runtime.Serialization.XmlReaderDelegator.ReadContentAsString(), System.Runtime.Serialization.XmlSerializableReader.ReadContentAsString(), System.Xml.XmlDictionaryReader.XmlWrappedReader.ReadContentAsString(), System.Xml.XmlAsyncCheckReader.ReadContentAsString(), System.Xml.XmlSubtreeReader.ReadContentAsString(), System.Runtime.Serialization.XmlReaderDelegator.ReadContentAsTimeSpan(), System.Runtime.Serialization.Json.JsonReaderDelegator.ReadContentAsUnsignedLong(), System.Runtime.Serialization.XmlReaderDelegator.ReadContentAsUnsignedLong(), and System.Xml.XmlReader.ReadElementContentAsString().