Terraria: System.Xml.XmlReader.ReadContentAsLong
ReadContentAsLong()
virtual long System.Xml.XmlReader.ReadContentAsLong () inline virtual inherited
Reimplemented in System.Runtime.Serialization.Json.XmlJsonReader, System.Runtime.Serialization.XmlSerializableReader, System.Xml.XmlBaseReader, System.Xml.XmlDictionaryReader.XmlWrappedReader, System.Xml.XmlAsyncCheckReader, System.Xml.XmlSqlBinaryReader, System.Xml.XmlSubtreeReader, and System.Xml.XsdValidatingReader.
Definition at line 270 of file XmlReader.cs.
    {
        if (!CanReadContentAs())
        {
            throw CreateReadContentAsException("ReadContentAsLong");
        }
        try
        {
            return XmlConvert.ToInt64(InternalReadContentAsString());
        }
        catch (FormatException innerException)
        {
            throw new XmlException(System.SR.Xml_ReadContentAsFormatException, "Long", innerException, this as IXmlLineInfo);
        }
    }
References System.Xml.XmlReader.CanReadContentAs(), System.Xml.XmlReader.CreateReadContentAsException(), System.Xml.Dictionary, System.Xml.XmlReader.InternalReadContentAsString(), System.Xml.XmlConvert.ToInt64(), System.SR.Xml_ReadContentAsFormatException, and System.Xml.XmlException.
Referenced by System.Runtime.Serialization.XmlReaderDelegator.ReadContentAsLong(), System.Runtime.Serialization.XmlSerializableReader.ReadContentAsLong(), System.Xml.XmlDictionaryReader.XmlWrappedReader.ReadContentAsLong(), System.Xml.XmlAsyncCheckReader.ReadContentAsLong(), System.Xml.XmlSubtreeReader.ReadContentAsLong(), System.Xml.XmlDictionaryReader.ReadElementContentAsLong(), System.Xml.XmlReader.ReadElementContentAsLong(), and System.Xml.XmlBinaryWriter.WriteTextNode().