Terraria: System.Xml.XmlReader.ReadString
ReadString()
virtual string System.Xml.XmlReader.ReadString () inline virtual inherited
Reimplemented in System.Data.DataTextReader, System.Xml.XmlDictionaryReader, System.Xml.Xsl.XsltOld.ReaderOutput, System.Xml.XmlAsyncCheckReader, System.Xml.XmlNodeReader, System.Xml.XmlTextReader, System.Xml.XmlTextReaderImpl, System.Xml.XmlValidatingReader, and System.Xml.XmlValidatingReaderImpl.
Definition at line 570 of file XmlReader.cs.
    {
        if (ReadState != ReadState.Interactive)
        {
            return string.Empty;
        }
        MoveToElement();
        if (NodeType == XmlNodeType.Element)
        {
            if (IsEmptyElement)
            {
                return string.Empty;
            }
            if (!Read())
            {
                throw new InvalidOperationException(System.SR.Xml_InvalidOperation);
            }
            if (NodeType == XmlNodeType.EndElement)
            {
                return string.Empty;
            }
        }
        string text = string.Empty;
        while (IsTextualNode(NodeType))
        {
            text += Value;
            if (!Read())
            {
                break;
            }
        }
        return text;
    }
References System.Xml.XmlReader.IsEmptyElement, System.Xml.XmlReader.IsTextualNode(), System.Xml.XmlReader.MoveToElement(), System.Xml.XmlReader.NodeType, System.Xml.XmlReader.Read(), System.text, System.Xml.XmlReader.Value, and System.SR.Xml_InvalidOperation.
Referenced by System.Data.XmlDataLoader.LoadColumn(), System.Data.XmlDataLoader.LoadTable(), System.Data.XmlDataLoader.LoadTopMostTable(), System.Xml.Serialization.XmlSerializationReader.ReadElementQualifiedName(), System.Xml.XmlReader.ReadElementString(), System.Xml.XmlReader.ReadElementString(), System.Xml.XmlReader.ReadElementString(), System.Data.DataTextReader.ReadString(), System.Xml.XmlAsyncCheckReader.ReadString(), System.Xml.Serialization.XmlSerializationReader.ReadString(), System.Xml.Serialization.XmlSerializationReader.ReadStringValue(), and System.Xml.Serialization.XmlSerializationReader.ReadXmlQualifiedName().