Terraria: System.IO.Strategies.FileStreamHelpers.TrySetFileLength
TrySetFileLength()
static unsafe bool System.IO.Strategies.FileStreamHelpers.TrySetFileLength (SafeFileHandle handle, long length, out int errorCode) inline static package
Definition at line 294 of file FileStreamHelpers.cs.
    {
        Interop.Kernel32.FILE_END_OF_FILE_INFO fILE_END_OF_FILE_INFO = default(Interop.Kernel32.FILE_END_OF_FILE_INFO);
        fILE_END_OF_FILE_INFO.EndOfFile = length;
        Interop.Kernel32.FILE_END_OF_FILE_INFO fILE_END_OF_FILE_INFO2 = fILE_END_OF_FILE_INFO;
        if (!Interop.Kernel32.SetFileInformationByHandle(handle, 6, &fILE_END_OF_FILE_INFO2, (uint)sizeof(Interop.Kernel32.FILE_END_OF_FILE_INFO)))
        {
            errorCode = Marshal.GetLastPInvokeError();
            return false;
        }
        errorCode = 0;
        return true;
    }
References System.Runtime.Serialization.Dictionary, System.Runtime.InteropServices.Marshal.GetLastPInvokeError(), System.handle, System.length, and Interop.Kernel32.SetFileInformationByHandle().
Referenced by System.IO.Strategies.FileStreamHelpers.SetFileLength().