Terraria: System.Xml.XmlReader.Create
Create() [5/12]
static XmlReader System.Xml.XmlReader.Create (string inputUri) inline static inherited
Definition at line 1334 of file XmlReader.cs.
    {
        if (inputUri == null)
        {
            throw new ArgumentNullException("inputUri");
        }
        if (inputUri.Length == 0)
        {
            throw new ArgumentException(System.SR.XmlConvert_BadUri, "inputUri");
        }
        return new XmlTextReaderImpl(inputUri, XmlReaderSettings.s_defaultReaderSettings, null, new XmlUrlResolver());
    }
References System.Xml.ArgumentException, System.Xml.Dictionary, System.Xml.XmlReaderSettings.s_defaultReaderSettings, and System.SR.XmlConvert_BadUri.
Referenced by System.Xml.Schema.XmlSchemaSet.Add(), System.Xml.Xsl.QueryReaderSettings.CreateReader(), System.Xml.Serialization.XmlSerializer.Deserialize(), System.Data.ProviderBase.SchemaMapping.GetMappedValues(), System.Xml.XPath.XPathNavigator.GetValidatingReader(), System.Xml.Linq.XDocument.Load(), System.Xml.Linq.XElement.Load(), System.Xml.Linq.XDocument.Load(), System.Xml.Linq.XElement.Load(), System.Xml.Linq.XDocument.Load(), System.Xml.Linq.XElement.Load(), System.Xml.Linq.XDocument.LoadAsync(), System.Xml.Linq.XElement.LoadAsync(), System.Xml.Linq.XDocument.LoadAsync(), System.Xml.Linq.XElement.LoadAsync(), System.Xml.Schema.Preprocessor.LoadExternals(), System.Xml.Schema.XmlSchemaValidator.LoadSchema(), System.Xml.Linq.XDocument.Parse(), System.Xml.Linq.XElement.Parse(), System.Xml.Xsl.XslCompiledTransform.Transform(), System.Xml.Xsl.XslCompiledTransform.Transform(), System.Xml.Xsl.XslCompiledTransform.Transform(), System.Xml.Xsl.XslCompiledTransform.Transform(), and System.Xml.Xsl.XslCompiledTransform.Transform().