Terraria: System.Xml.XmlReader.FinishReadElementContentAsXxxAsync
FinishReadElementContentAsXxxAsync()
Task System.Xml.XmlReader.FinishReadElementContentAsXxxAsync () inline private inherited
Definition at line 1852 of file XmlReader.cs.
    {
        if (NodeType != XmlNodeType.EndElement)
        {
            throw new XmlException(System.SR.Xml_InvalidNodeType, NodeType.ToString());
        }
        return ReadAsync();
    }
References System.Xml.XmlReader.NodeType, System.Xml.XmlReader.ReadAsync(), System.SR.Xml_InvalidNodeType, and System.Xml.XmlException.
Referenced by System.Xml.XmlReader.ReadElementContentAsAsync(), System.Xml.XmlReader.ReadElementContentAsObjectAsync(), and System.Xml.XmlReader.ReadElementContentAsStringAsync().