Terraria: System.Xml.XmlReader.ReadContentAsBase64
ReadContentAsBase64()
virtual int System.Xml.XmlReader.ReadContentAsBase64 (byte[] buffer, int index, int count) inline virtual inherited
Reimplemented in System.Data.DataTextReader, System.Runtime.Serialization.XmlSerializableReader, System.Xml.XPath.XPathNavigatorReader, System.Xml.XmlAsyncCheckReader, System.Xml.XmlCharCheckingReader, System.Xml.XmlNodeReader, System.Xml.XmlSubtreeReader, System.Xml.XmlTextReader, System.Xml.XmlTextReaderImpl, System.Xml.XmlValidatingReader, System.Xml.XmlValidatingReaderImpl, System.Xml.XsdValidatingReader, System.Xml.XmlBaseReader, and System.Xml.XmlDictionaryReader.XmlWrappedReader.
Definition at line 544 of file XmlReader.cs.
    {
        throw new NotSupportedException(System.SR.Format(System.SR.Xml_ReadBinaryContentNotSupported, "ReadContentAsBase64"));
    }
References System.SR.Format(), and System.SR.Xml_ReadBinaryContentNotSupported.
Referenced by System.Xml.XmlSubtreeReader.FinishReadContentAsBinary(), System.Xml.XmlSubtreeReader.FinishReadElementContentAsBinary(), System.Data.DataTextReader.ReadContentAsBase64(), System.Runtime.Serialization.XmlSerializableReader.ReadContentAsBase64(), System.Xml.XmlAsyncCheckReader.ReadContentAsBase64(), System.Xml.XmlSubtreeReader.ReadContentAsBase64(), System.Xml.XmlDictionaryReader.XmlWrappedReader.ReadContentAsBase64(), and System.Xml.XmlSubtreeReader.ReadElementContentAsBase64().