Terraria: System.Xml.XmlReader.ReadElementContentAsString
ReadElementContentAsString() [1/2]
virtual string System.Xml.XmlReader.ReadElementContentAsString () inline virtual inherited
Reimplemented in System.Xml.XmlBaseReader, System.Xml.XmlBinaryReader, System.Xml.XmlDictionaryReader, System.Xml.XmlAsyncCheckReader, and System.Xml.XsdValidatingReader.
Definition at line 456 of file XmlReader.cs.
    {
        if (SetupReadElementContentAsXxx("ReadElementContentAsString"))
        {
            string result = ReadContentAsString();
            FinishReadElementContentAsXxx();
            return result;
        }
        return string.Empty;
    }
References System.Xml.XmlReader.FinishReadElementContentAsXxx(), System.Xml.XmlReader.ReadContentAsString(), and System.Xml.XmlReader.SetupReadElementContentAsXxx().
Referenced by System.Runtime.Serialization.Json.JsonReaderDelegator.DateTimeArrayJsonHelperWithString.ReadArray(), System.Runtime.Serialization.XmlReaderDelegator.ReadElementContentAsBase64(), System.Runtime.Serialization.XmlReaderDelegator.ReadElementContentAsDateTime(), System.Runtime.Serialization.XmlReaderDelegator.ReadElementContentAsGuid(), System.Runtime.Serialization.XmlReaderDelegator.ReadElementContentAsString(), System.Xml.XmlAsyncCheckReader.ReadElementContentAsString(), System.Xml.XmlAsyncCheckReader.ReadElementContentAsString(), System.Xml.XmlReader.ReadElementContentAsString(), System.Runtime.Serialization.XmlReaderDelegator.ReadElementContentAsTimeSpan(), System.Runtime.Serialization.Json.JsonReaderDelegator.ReadElementContentAsUnsignedLong(), and System.Runtime.Serialization.XmlReaderDelegator.ReadElementContentAsUnsignedLong().