Terraria: System.Xml.XmlReader.SkipSubtreeAsync
SkipSubtreeAsync()
async Task< bool > System.Xml.XmlReader.SkipSubtreeAsync () inline private inherited
Definition at line 1761 of file XmlReader.cs.
    {
        MoveToElement();
        if (NodeType == XmlNodeType.Element && !IsEmptyElement)
        {
            int depth = Depth;
            while (await ReadAsync().ConfigureAwait(continueOnCapturedContext: false) && depth < Depth)
            {
            }
            if (NodeType == XmlNodeType.EndElement)
            {
                return await ReadAsync().ConfigureAwait(continueOnCapturedContext: false);
            }
            return false;
        }
        return await ReadAsync().ConfigureAwait(continueOnCapturedContext: false);
    }
References System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.Xml.XmlReader.Depth, System.Xml.Dictionary, System.Xml.XmlReader.IsEmptyElement, System.Xml.XmlReader.MoveToElement(), System.Xml.XmlReader.NodeType, and System.Xml.XmlReader.ReadAsync().
Referenced by System.Xml.XmlReader.SkipAsync().