Terraria: System.Xml.XmlReader.FinishReadElementContentAsXxx
FinishReadElementContentAsXxx()
void System.Xml.XmlReader.FinishReadElementContentAsXxx () inline private inherited
Definition at line 1299 of file XmlReader.cs.
    {
        if (NodeType != XmlNodeType.EndElement)
        {
            throw new XmlException(System.SR.Xml_InvalidNodeType, NodeType.ToString());
        }
        Read();
    }
References System.Xml.XmlReader.NodeType, System.Xml.XmlReader.Read(), System.SR.Xml_InvalidNodeType, and System.Xml.XmlException.
Referenced by System.Xml.XmlReader.ReadElementContentAs(), System.Xml.XmlReader.ReadElementContentAsBoolean(), System.Xml.XmlReader.ReadElementContentAsDateTime(), System.Xml.XmlReader.ReadElementContentAsDecimal(), System.Xml.XmlReader.ReadElementContentAsDouble(), System.Xml.XmlReader.ReadElementContentAsFloat(), System.Xml.XmlReader.ReadElementContentAsInt(), System.Xml.XmlReader.ReadElementContentAsLong(), System.Xml.XmlReader.ReadElementContentAsObject(), and System.Xml.XmlReader.ReadElementContentAsString().