Terraria: System.Xml.XmlReader.ReadToFollowing
ReadToFollowing() [1/2]
virtual bool System.Xml.XmlReader.ReadToFollowing (string localName, string namespaceURI) inline virtual inherited
Reimplemented in System.Xml.Linq.XNodeReader, and System.Xml.XmlAsyncCheckReader.
Definition at line 804 of file XmlReader.cs.
    {
        if (localName == null || localName.Length == 0)
        {
            throw XmlConvert.CreateInvalidNameArgumentException(localName, "localName");
        }
        if (namespaceURI == null)
        {
            throw new ArgumentNullException("namespaceURI");
        }
        localName = NameTable.Add(localName);
        namespaceURI = NameTable.Add(namespaceURI);
        while (Read())
        {
            if (NodeType == XmlNodeType.Element && Ref.Equal(localName, LocalName) && Ref.Equal(namespaceURI, NamespaceURI))
            {
                return true;
            }
        }
        return false;
    }
References System.Xml.NameTable.Add(), System.Xml.XmlConvert.CreateInvalidNameArgumentException(), System.Xml.Dictionary, System.Xml.Ref.Equal(), System.Xml.XmlReader.LocalName, System.Xml.XmlReader.NamespaceURI, System.Xml.XmlReader.NodeType, and System.Xml.XmlReader.Read().