Terraria: System.Xml.XmlReader.CreateSqlReader
CreateSqlReader()
static XmlReader System.Xml.XmlReader.CreateSqlReader (Stream input, XmlReaderSettings settings, XmlParserContext inputContext) inline static package inherited
Definition at line 1434 of file XmlReader.cs.
    {
        if (input == null)
        {
            throw new ArgumentNullException("input");
        }
        if (settings == null)
        {
            settings = XmlReaderSettings.s_defaultReaderSettings;
        }
        byte[] array = new byte[CalcBufferSize(input)];
        int num = 0;
        int num2;
        do
        {
            num2 = input.Read(array, num, array.Length - num);
            num += num2;
        }
        while (num2 > 0 && num < 2);
        XmlReader xmlReader;
        if (num >= 2 && array[0] == 223 && array[1] == byte.MaxValue)
        {
            if (inputContext != null)
            {
                throw new ArgumentException(System.SR.XmlBinary_NoParserContext, "inputContext");
            }
            xmlReader = new XmlSqlBinaryReader(input, array, num, string.Empty, settings.CloseInput, settings);
        }
        else
        {
            xmlReader = new XmlTextReaderImpl(input, array, num, settings, null, string.Empty, inputContext, settings.CloseInput);
        }
        if (settings.ValidationType != 0)
        {
            xmlReader = settings.AddValidation(xmlReader);
        }
        if (settings.Async)
        {
            xmlReader = XmlAsyncCheckReader.CreateAsyncCheckWrapper(xmlReader);
        }
        return xmlReader;
    }
References System.Xml.XmlReaderSettings.AddValidation(), System.Xml.ArgumentException, System.array, System.Xml.XmlReaderSettings.Async, System.Xml.XmlReader.CalcBufferSize(), System.Xml.XmlReaderSettings.CloseInput, System.Xml.XmlAsyncCheckReader.CreateAsyncCheckWrapper(), System.Xml.Dictionary, System.input, System.Xml.XmlReaderSettings.s_defaultReaderSettings, System.Xml.XmlReaderSettings.ValidationType, and System.SR.XmlBinary_NoParserContext.