Terraria: System.Xml.XmlReader.ReadContentAsBinHex
ReadContentAsBinHex()
virtual int System.Xml.XmlReader.ReadContentAsBinHex (byte[] buffer, int index, int count) inline virtual inherited
Reimplemented in System.Data.DataTextReader, System.Runtime.Serialization.XmlSerializableReader, System.Xml.XPath.XPathNavigatorReader, System.Xml.XmlAsyncCheckReader, System.Xml.XmlCharCheckingReader, System.Xml.XmlNodeReader, System.Xml.XmlSubtreeReader, System.Xml.XmlTextReader, System.Xml.XmlTextReaderImpl, System.Xml.XmlValidatingReader, System.Xml.XmlValidatingReaderImpl, System.Xml.XsdValidatingReader, System.Xml.XmlBaseReader, and System.Xml.XmlDictionaryReader.XmlWrappedReader.
Definition at line 554 of file XmlReader.cs.
    {
        throw new NotSupportedException(System.SR.Format(System.SR.Xml_ReadBinaryContentNotSupported, "ReadContentAsBinHex"));
    }
References System.SR.Format(), and System.SR.Xml_ReadBinaryContentNotSupported.
Referenced by System.Xml.XmlSubtreeReader.FinishReadContentAsBinary(), System.Xml.XmlSubtreeReader.FinishReadElementContentAsBinary(), System.Data.DataTextReader.ReadContentAsBinHex(), System.Runtime.Serialization.XmlSerializableReader.ReadContentAsBinHex(), System.Xml.XmlAsyncCheckReader.ReadContentAsBinHex(), System.Xml.XmlSubtreeReader.ReadContentAsBinHex(), System.Xml.XmlDictionaryReader.XmlWrappedReader.ReadContentAsBinHex(), and System.Xml.XmlSubtreeReader.ReadElementContentAsBinHex().