Terraria: System.Xml.XmlReader.WriteNode
WriteNode()
void System.Xml.XmlReader.WriteNode (XmlWriter xtw, bool defattr) inline private inherited
Definition at line 990 of file XmlReader.cs.
    {
        int num = ((NodeType == XmlNodeType.None) ? (-1) : Depth);
        while (Read() && num < Depth)
        {
            switch (NodeType)
            {
            case XmlNodeType.Element:
                xtw.WriteStartElement(Prefix, LocalName, NamespaceURI);
                ((XmlTextWriter)xtw).QuoteChar = QuoteChar;
                xtw.WriteAttributes(this, defattr);
                if (IsEmptyElement)
                {
                    xtw.WriteEndElement();
                }
                break;
            case XmlNodeType.Text:
                xtw.WriteString(Value);
                break;
            case XmlNodeType.Whitespace:
            case XmlNodeType.SignificantWhitespace:
                xtw.WriteWhitespace(Value);
                break;
            case XmlNodeType.CDATA:
                xtw.WriteCData(Value);
                break;
            case XmlNodeType.EntityReference:
                xtw.WriteEntityRef(Name);
                break;
            case XmlNodeType.ProcessingInstruction:
            case XmlNodeType.XmlDeclaration:
                xtw.WriteProcessingInstruction(Name, Value);
                break;
            case XmlNodeType.DocumentType:
                xtw.WriteDocType(Name, GetAttribute("PUBLIC"), GetAttribute("SYSTEM"), Value);
                break;
            case XmlNodeType.Comment:
                xtw.WriteComment(Value);
                break;
            case XmlNodeType.EndElement:
                xtw.WriteFullEndElement();
                break;
            }
        }
        if (num == Depth && NodeType == XmlNodeType.EndElement)
        {
            Read();
        }
    }
References System.Xml.XmlReader.Depth, System.Xml.Dictionary, System.Xml.XmlReader.GetAttribute(), System.Xml.XmlReader.IsEmptyElement, System.Xml.XmlReader.LocalName, System.Xml.XmlReader.Name, System.Xml.XmlReader.NamespaceURI, System.Xml.XmlReader.NodeType, System.Xml.XmlReader.Prefix, System.Xml.XmlReader.QuoteChar, System.Xml.XmlReader.Read(), and System.Xml.XmlReader.Value.
Referenced by System.Xml.XmlReader.ReadInnerXml().