Terraria: System.Xml.XmlReader.CanReadContentAs
CanReadContentAs() [2/2]
static bool System.Xml.XmlReader.CanReadContentAs (XmlNodeType nodeType) inline static package inherited
Definition at line 1136 of file XmlReader.cs.
    {
        return (0x1E1BCuL & (ulong)(1 << (int)nodeType)) != 0;
    }
References System.Xml.Dictionary.
Referenced by System.Xml.XsdValidatingReader.ReadContentAs(), System.Xml.XsdValidatingReader.ReadContentAsAsync(), System.Xml.ReadContentAsBinaryHelper.ReadContentAsBase64(), System.Xml.XmlTextReaderImpl.ReadContentAsBase64(), System.Xml.ReadContentAsBinaryHelper.ReadContentAsBase64Async(), System.Xml.XmlTextReaderImpl.ReadContentAsBase64Async(), System.Xml.ReadContentAsBinaryHelper.ReadContentAsBinHex(), System.Xml.XmlTextReaderImpl.ReadContentAsBinHex(), System.Xml.ReadContentAsBinaryHelper.ReadContentAsBinHexAsync(), System.Xml.XmlTextReaderImpl.ReadContentAsBinHexAsync(), System.Xml.XsdValidatingReader.ReadContentAsBoolean(), System.Xml.XsdValidatingReader.ReadContentAsDateTime(), System.Xml.XsdValidatingReader.ReadContentAsDecimal(), System.Xml.XsdValidatingReader.ReadContentAsDouble(), System.Xml.XsdValidatingReader.ReadContentAsFloat(), System.Xml.XsdValidatingReader.ReadContentAsInt(), System.Xml.XsdValidatingReader.ReadContentAsLong(), System.Xml.XsdValidatingReader.ReadContentAsObject(), System.Xml.XsdValidatingReader.ReadContentAsObjectAsync(), System.Xml.XsdValidatingReader.ReadContentAsString(), System.Xml.XsdValidatingReader.ReadContentAsStringAsync(), and System.Xml.XmlSqlBinaryReader.SetupContentAsXXX().