Terraria: System.Xml.XmlReader.CreateReadElementContentAsException
CreateReadElementContentAsException() [1/2]
Exception System.Xml.XmlReader.CreateReadElementContentAsException (string methodName) inline package inherited
Definition at line 1189 of file XmlReader.cs.
    {
        return CreateReadElementContentAsException(methodName, NodeType, this as IXmlLineInfo);
    }
References System.Xml.XmlReader.CreateReadElementContentAsException(), System.Xml.Dictionary, and System.Xml.XmlReader.NodeType.
Referenced by System.Xml.XmlReader.CreateReadElementContentAsException(), System.Xml.XmlSubtreeReader.InitReadElementContentAsBinary(), System.Xml.XmlSubtreeReader.InitReadElementContentAsBinaryAsync(), System.Xml.XsdValidatingReader.ReadElementContentAs(), System.Xml.XsdValidatingReader.ReadElementContentAsAsync(), System.Xml.ReadContentAsBinaryHelper.ReadElementContentAsBase64(), System.Xml.XmlTextReaderImpl.ReadElementContentAsBase64(), System.Xml.ReadContentAsBinaryHelper.ReadElementContentAsBase64Async(), System.Xml.XmlTextReaderImpl.ReadElementContentAsBase64Async(), System.Xml.ReadContentAsBinaryHelper.ReadElementContentAsBinHex(), System.Xml.XmlTextReaderImpl.ReadElementContentAsBinHex(), System.Xml.ReadContentAsBinaryHelper.ReadElementContentAsBinHexAsync(), System.Xml.XmlTextReaderImpl.ReadElementContentAsBinHexAsync(), System.Xml.XsdValidatingReader.ReadElementContentAsBoolean(), System.Xml.XsdValidatingReader.ReadElementContentAsDateTime(), System.Xml.XsdValidatingReader.ReadElementContentAsDecimal(), System.Xml.XsdValidatingReader.ReadElementContentAsDouble(), System.Xml.XsdValidatingReader.ReadElementContentAsFloat(), System.Xml.XsdValidatingReader.ReadElementContentAsInt(), System.Xml.XsdValidatingReader.ReadElementContentAsLong(), System.Xml.XsdValidatingReader.ReadElementContentAsObject(), System.Xml.XsdValidatingReader.ReadElementContentAsObjectAsync(), System.Xml.XsdValidatingReader.ReadElementContentAsString(), System.Xml.XsdValidatingReader.ReadElementContentAsStringAsync(), System.Xml.XmlReader.SetupReadElementContentAsXxx(), and System.Xml.XmlReader.SetupReadElementContentAsXxxAsync().