Terraria: System.Xml.XmlReader.ReadContentAsDateTime
ReadContentAsDateTime()
virtual DateTime System.Xml.XmlReader.ReadContentAsDateTime () inline virtual inherited
Reimplemented in System.Runtime.Serialization.XmlSerializableReader, System.Xml.XmlBaseReader, System.Xml.XmlDictionaryReader.XmlWrappedReader, System.Xml.XmlAsyncCheckReader, System.Xml.XmlSqlBinaryReader, System.Xml.XmlSubtreeReader, and System.Xml.XsdValidatingReader.
Definition at line 174 of file XmlReader.cs.
    {
        if (!CanReadContentAs())
        {
            throw CreateReadContentAsException("ReadContentAsDateTime");
        }
        try
        {
            return XmlConvert.ToDateTime(InternalReadContentAsString(), XmlDateTimeSerializationMode.RoundtripKind);
        }
        catch (FormatException innerException)
        {
            throw new XmlException(System.SR.Xml_ReadContentAsFormatException, "DateTime", innerException, this as IXmlLineInfo);
        }
    }
References System.Xml.XmlReader.CanReadContentAs(), System.Xml.XmlReader.CreateReadContentAsException(), System.Xml.Dictionary, System.Xml.XmlReader.InternalReadContentAsString(), System.Xml.XmlConvert.ToDateTime(), System.SR.Xml_ReadContentAsFormatException, and System.Xml.XmlException.
Referenced by System.Runtime.Serialization.XmlReaderDelegator.ReadContentAsDateTime(), System.Xml.XmlDictionaryReader.XmlWrappedReader.ReadContentAsDateTime(), System.Xml.XmlAsyncCheckReader.ReadContentAsDateTime(), System.Xml.XmlSubtreeReader.ReadContentAsDateTime(), System.Xml.XmlDictionaryReader.ReadElementContentAsDateTime(), and System.Xml.XmlReader.ReadElementContentAsDateTime().