Terraria: System.Xml.XmlReader.Read
Read()
bool System.Xml.XmlReader.Read () abstract
Referenced by System.Xml.XPath.XPathNavigator.BuildSubtree(), System.Xml.XmlSubtreeReader.Close(), System.Data.SqlTypes.SqlXml.CreateMemoryStreamFromXmlReader(), System.Xml.Xsl.Xslt.XsltInput.FillupCharacterEntityRecord(), System.Xml.ReadContentAsBinaryHelper.Finish(), System.Xml.XmlTextReaderImpl.FinishReadElementContentAsBinary(), System.Xml.XmlReader.FinishReadElementContentAsXxx(), System.Xml.XsdValidatingReader.GetIsDefault(), System.Xml.XmlSqlBinaryReader.ImplReadXmlText(), System.Xml.XmlTextReaderImpl.IncrementalRead(), System.Xml.Schema.XmlSchemaInference.InferElement(), System.Xml.Schema.XmlSchemaInference.InferSchema1(), System.Xml.ReadContentAsBinaryHelper.InitOnElement(), System.Xml.XmlTextReaderImpl.InitReadElementContentAsBinary(), System.Xml.XmlReader.InternalReadContentAsString(), System.Xml.XmlBaseReader.IsStartElement(), System.Xml.XmlLoader.Load(), System.Xml.Linq.XDocument.Load(), System.Data.XmlDataLoader.LoadColumn(), System.Data.XmlDataLoader.LoadData(), System.Xml.XmlLoader.LoadDocSequence(), System.Xml.XmlLoader.LoadEntityReferenceNode(), System.Xml.XPath.XPathDocument.LoadFromReader(), System.Xml.XmlLoader.LoadNode(), System.Xml.XmlLoader.LoadNodeDirect(), System.Data.XmlDataLoader.LoadTable(), System.Data.XmlDataLoader.LoadTopMostTable(), System.Xml.XmlTextReaderImpl.MoveOffEntityReference(), System.Xml.XmlValidatingReaderImpl.MoveOffEntityReference(), System.Xml.XmlBaseReader.MoveToContent(), System.Xml.XmlReader.MoveToContent(), System.Data.DataSet.MoveToElement(), System.Data.DataSet.MoveToElement(), System.Data.DataTable.MoveToElement(), System.Xml.ReadContentAsBinaryHelper.MoveToNextContentNode(), System.Xml.XmlTextReaderImpl.MoveToNextContentNode(), System.Xml.Schema.Parser.Parse(), System.Xml.XmlLoader.ParsePartialContent(), System.Xml.XsdValidatingReader.ProcessInlineSchema(), System.Data.DataTextReader.Read(), System.Runtime.Serialization.XmlReaderDelegator.Read(), System.Runtime.Serialization.XmlSerializableReader.Read(), System.Xml.XmlDictionaryReader.XmlWrappedReader.Read(), System.Xml.XmlAsyncCheckReader.Read(), System.Xml.XmlCharCheckingReader.Read(), System.Xml.XmlSqlBinaryReader.Read(), System.Xml.XmlSubtreeReader.Read(), System.Xml.XmlValidatingReaderImpl.Read(), System.Xml.XmlWrappingReader.Read(), System.Xml.XsdCachingReader.Read(), System.Xml.XsdValidatingReader.Read(), System.Xml.XsdValidatingReader.ReadAheadForMemberType(), System.Xml.XmlTextReaderImpl.ReadBase64(), System.Xml.XmlTextReaderImpl.ReadBinHex(), System.Xml.XmlTextReaderImpl.ReadChars(), System.Xml.XmlBaseReader.ReadContentAsBase64(), System.Xml.XmlDictionaryReader.ReadContentAsChars(), System.Xml.XmlDictionaryReader.ReadContentAsString(), System.Xml.XmlLoader.ReadCurrentNode(), System.Xml.Xsl.Xslt.XsltInput.ReadElement(), System.Runtime.Serialization.Json.JsonReaderDelegator.ReadElementContentAsBase64(), System.Xml.XmlDictionaryReader.ReadElementContentAsBase64(), System.Xml.XmlBaseReader.ReadElementContentAsBase64(), System.Xml.ReadContentAsBinaryHelper.ReadElementContentAsBinary(), System.Xml.XmlTextReaderImpl.ReadElementContentAsBinary(), System.Xml.XmlDictionaryReader.ReadElementContentAsBinHex(), System.Xml.XmlBaseReader.ReadElementContentAsBinHex(), System.Xml.XmlDictionaryReader.ReadElementContentAsBoolean(), System.Xml.XmlDictionaryReader.ReadElementContentAsDateTime(), System.Xml.XmlDictionaryReader.ReadElementContentAsDecimal(), System.Xml.XmlDictionaryReader.ReadElementContentAsDouble(), System.Xml.XmlDictionaryReader.ReadElementContentAsFloat(), System.Xml.XmlDictionaryReader.ReadElementContentAsGuid(), System.Xml.XmlDictionaryReader.ReadElementContentAsInt(), System.Xml.XmlDictionaryReader.ReadElementContentAsLong(), System.Xml.XmlBaseReader.ReadElementContentAsString(), System.Xml.XmlDictionaryReader.ReadElementContentAsString(), System.Xml.XmlDictionaryReader.ReadElementContentAsTimeSpan(), System.Xml.XmlDictionaryReader.ReadElementContentAsUniqueId(), System.Xml.XmlReader.ReadElementString(), System.Xml.XmlReader.ReadElementString(), System.Xml.XmlReader.ReadElementString(), System.Xml.XmlBaseReader.ReadEndElement(), System.Xml.XmlReader.ReadEndElement(), System.Xml.XmlDictionaryReader.ReadFullStartElement(), System.Xml.XmlDictionaryReader.ReadFullStartElement(), System.Xml.XmlDictionaryReader.ReadFullStartElement(), System.Xml.XmlDictionaryReader.ReadFullStartElement(), System.Xml.XmlReader.ReadInnerXml(), System.Xml.Xsl.Xslt.XsltInput.ReadNextSibling(), System.Xml.XmlReader.ReadOuterXml(), System.Xml.Serialization.XmlSerializationReader.ReadSerializable(), System.Xml.XmlBaseReader.ReadStartElement(), System.Xml.XmlReader.ReadStartElement(), System.Xml.XmlBaseReader.ReadStartElement(), System.Xml.XmlReader.ReadStartElement(), System.Xml.XmlBaseReader.ReadStartElement(), System.Xml.XmlReader.ReadStartElement(), System.Xml.XmlDictionaryReader.ReadStartElement(), System.Xml.XmlReader.ReadString(), System.Xml.XmlDictionaryReader.ReadString(), System.Xml.Xsl.Xslt.XsltInput.ReadTextNodes(), System.Xml.XsdValidatingReader.ReadTillEndElement(), System.Xml.XmlReader.ReadToDescendant(), System.Xml.XmlReader.ReadToDescendant(), System.Xml.XmlReader.ReadToFollowing(), System.Xml.XmlReader.ReadToFollowing(), System.Xml.XmlValidatingReaderImpl.ReadTypedValue(), System.Data.DataSet.ReadXml(), System.Data.DataTable.ReadXml(), System.Data.DataSet.ReadXml(), System.Data.DataTable.ReadXml(), System.Data.DataSet.ReadXmlDiffgram(), System.Data.DataTable.ReadXmlDiffgram(), System.Data.DataSet.ReadXmlSchema(), System.Xml.XmlValidatingReaderImpl.ResolveEntityInternally(), System.Xml.XmlReader.SetupReadElementContentAsXxx(), System.Xml.XmlBaseReader.Skip(), System.Xml.XmlSubtreeReader.Skip(), System.Xml.XmlTextReaderImpl.Skip(), System.Xml.XsdCachingReader.Skip(), System.Xml.XmlReader.SkipSubtree(), System.Xml.XmlBaseReader.SkipValue(), System.Data.XMLDiffLoader.SkipWhitespaces(), System.Xml.Schema.Parser.StartParsing(), System.Xml.Serialization.XmlSerializationReader.UnknownNode(), System.Xml.XmlDictionaryWriter.WriteArrayNode(), System.Xml.XmlDictionaryWriter.WriteArrayNode(), System.Xml.XmlDictionaryWriter.WriteNode(), System.Xml.XmlWriter.WriteNode(), System.Xml.XmlReader.WriteNode(), System.Xml.XmlWriter.WriteNodeAsync_CallSyncReader(), System.Xml.XmlBinaryWriter.WriteTextNode(), and System.Xml.XmlDictionaryWriter.WriteTextNode().