Terraria: System.Xml.XmlReader.Skip
Skip()
virtual void System.Xml.XmlReader.Skip () inline virtual inherited
Reimplemented in System.Data.DataTextReader, System.Runtime.Serialization.ExtensionDataReader, System.Xml.XmlBaseReader, System.Xml.Linq.XNodeReader, System.Xml.XmlAsyncCheckReader, System.Xml.XmlNodeReader, System.Xml.XmlSubtreeReader, System.Xml.XmlTextReader, System.Xml.XmlTextReaderImpl, System.Xml.XmlWrappingReader, System.Xml.XsdCachingReader, and System.Xml.XsdValidatingReader.
Definition at line 532 of file XmlReader.cs.
    {
        if (ReadState == ReadState.Interactive)
        {
            SkipSubtree();
        }
    }
References System.Xml.XmlReader.SkipSubtree().
Referenced by System.Xml.Xsl.Xslt.XsltInput.Finish(), System.Data.XmlDataLoader.ProcessXsdSchema(), System.Xml.Serialization.XmlSerializationReader.ReadArray(), System.Xml.Serialization.XmlSerializationReader.ReadElementQualifiedName(), System.Xml.Serialization.XmlSerializationReader.ReadEndElement(), System.Data.DataSet.ReadEndElement(), System.Data.DataTable.ReadEndElement(), System.Xml.Serialization.XmlSerializationReader.ReadNull(), System.Xml.Serialization.XmlSerializationReader.ReadReference(), System.Xml.Serialization.XmlSerializationReader.ReadSerializable(), System.Xml.Serialization.XmlSerializationReader.ReadStringValue(), System.Data.DataSet.ReadXml(), System.Data.DataTable.ReadXml(), System.Xml.Serialization.XmlSerializationReader.ReadXmlQualifiedName(), System.Data.DataSet.ReadXSDSchema(), System.Data.DataTextReader.Skip(), System.Runtime.Serialization.XmlReaderDelegator.Skip(), System.Xml.XmlAsyncCheckReader.Skip(), System.Xml.XmlSubtreeReader.Skip(), System.Xml.XmlWrappingReader.Skip(), System.Xml.XsdValidatingReader.Skip(), and System.Xml.Serialization.XmlSerializationReader.UnknownNode().