Terraria: System.Xml.XmlReader.InternalReadContentAsString
InternalReadContentAsString()
string System.Xml.XmlReader.InternalReadContentAsString () inline package inherited
Definition at line 1223 of file XmlReader.cs.
    {
        string text = string.Empty;
        StringBuilder stringBuilder = null;
        bool num;
        do
        {
            switch (NodeType)
            {
            case XmlNodeType.Attribute:
                return Value;
            case XmlNodeType.Text:
            case XmlNodeType.CDATA:
            case XmlNodeType.Whitespace:
            case XmlNodeType.SignificantWhitespace:
                if (text.Length == 0)
                {
                    text = Value;
                }
                else
                {
                    if (stringBuilder == null)
                    {
                        stringBuilder = new StringBuilder();
                        stringBuilder.Append(text);
                    }
                    stringBuilder.Append(Value);
                }
                goto case XmlNodeType.ProcessingInstruction;
            case XmlNodeType.EntityReference:
                if (!CanResolveEntity)
                {
                    break;
                }
                ResolveEntity();
                goto case XmlNodeType.ProcessingInstruction;
            case XmlNodeType.ProcessingInstruction:
            case XmlNodeType.Comment:
            case XmlNodeType.EndEntity:
                num = ((AttributeCount != 0) ? ReadAttributeValue() : Read());
                continue;
            }
            break;
        }
        while (num);
        if (stringBuilder != null)
        {
            return stringBuilder.ToString();
        }
        return text;
    }
References System.Xml.XmlReader.AttributeCount, System.Xml.XmlReader.CanResolveEntity, System.Xml.Dictionary, System.Xml.XmlReader.NodeType, System.Xml.XmlReader.Read(), System.Xml.XmlReader.ReadAttributeValue(), System.Xml.XmlReader.ResolveEntity(), System.text, and System.Xml.XmlReader.Value.
Referenced by System.Xml.XsdValidatingReader.InternalReadContentAsObject(), System.Xml.XmlReader.ReadContentAs(), System.Xml.XmlReader.ReadContentAsBoolean(), System.Xml.XmlReader.ReadContentAsDateTime(), System.Xml.XmlReader.ReadContentAsDateTimeOffset(), System.Xml.XmlReader.ReadContentAsDecimal(), System.Xml.XmlReader.ReadContentAsDouble(), System.Xml.XmlReader.ReadContentAsFloat(), System.Xml.XmlReader.ReadContentAsInt(), System.Xml.XmlReader.ReadContentAsLong(), System.Xml.XmlReader.ReadContentAsObject(), System.Xml.XmlReader.ReadContentAsString(), and System.Xml.XsdCachingReader.ReadOriginalContentAsString().