Terraria: System.Xml.XmlReader.ReadElementString
ReadElementString() [1/3]
virtual string System.Xml.XmlReader.ReadElementString () inline virtual inherited
Reimplemented in System.Xml.XmlAsyncCheckReader.
Definition at line 667 of file XmlReader.cs.
    {
        string result = string.Empty;
        if (MoveToContent() != XmlNodeType.Element)
        {
            throw new XmlException(System.SR.Xml_InvalidNodeType, NodeType.ToString(), this as IXmlLineInfo);
        }
        if (!IsEmptyElement)
        {
            Read();
            result = ReadString();
            if (NodeType != XmlNodeType.EndElement)
            {
                throw new XmlException(System.SR.Xml_UnexpectedNodeInSimpleContent, new string[2]
                {
                    NodeType.ToString(),
                    "ReadElementString"
                }, this as IXmlLineInfo);
            }
            Read();
        }
        else
        {
            Read();
        }
        return result;
    }
References System.Xml.Dictionary, System.Xml.XmlReader.IsEmptyElement, System.Xml.XmlReader.MoveToContent(), System.Xml.XmlReader.NodeType, System.Xml.XmlReader.Read(), System.Xml.XmlReader.ReadString(), System.SR.Xml_InvalidNodeType, System.SR.Xml_UnexpectedNodeInSimpleContent, and System.Xml.XmlException.
Referenced by System.Xml.XmlAsyncCheckReader.ReadElementString(), System.Xml.XmlAsyncCheckReader.ReadElementString(), System.Xml.XmlAsyncCheckReader.ReadElementString(), System.Xml.Serialization.XmlSerializationReader.ReadNullableString(), System.Data.SqlTypes.SqlBinary.ReadXml(), System.Data.SqlTypes.SqlBoolean.ReadXml(), System.Data.SqlTypes.SqlByte.ReadXml(), System.Data.SqlTypes.SqlDateTime.ReadXml(), System.Data.SqlTypes.SqlDecimal.ReadXml(), System.Data.SqlTypes.SqlDouble.ReadXml(), System.Data.SqlTypes.SqlGuid.ReadXml(), System.Data.SqlTypes.SqlInt16.ReadXml(), System.Data.SqlTypes.SqlInt32.ReadXml(), System.Data.SqlTypes.SqlInt64.ReadXml(), System.Data.SqlTypes.SqlMoney.ReadXml(), System.Data.SqlTypes.SqlSingle.ReadXml(), and System.Data.SqlTypes.SqlString.ReadXml().