Terraria: System.Xml.XmlReader.MoveToContent
MoveToContent()
virtual XmlNodeType System.Xml.XmlReader.MoveToContent () inline virtual inherited
Reimplemented in System.Runtime.Serialization.XmlSerializableReader, System.Xml.XmlBaseReader, and System.Xml.XmlAsyncCheckReader.
Definition at line 604 of file XmlReader.cs.
    {
        do
        {
            switch (NodeType)
            {
            case XmlNodeType.Attribute:
                MoveToElement();
                break;
            case XmlNodeType.Element:
            case XmlNodeType.Text:
            case XmlNodeType.CDATA:
            case XmlNodeType.EntityReference:
            case XmlNodeType.EndElement:
            case XmlNodeType.EndEntity:
                break;
            default:
                continue;
            }
            return NodeType;
        }
        while (Read());
        return NodeType;
    }
References System.Xml.XmlReader.MoveToElement(), System.Xml.XmlReader.NodeType, and System.Xml.XmlReader.Read().
Referenced by System.Data.DataSet.DetermineSchemaSerializationMode(), System.Xml.XmlReader.IsStartElement(), System.Xml.XmlReader.IsStartElement(), System.Xml.XmlReader.IsStartElement(), System.Xml.Linq.XElement.Load(), System.Runtime.Serialization.XmlReaderDelegator.MoveToContent(), System.Runtime.Serialization.XmlSerializableReader.MoveToContent(), System.Xml.XmlAsyncCheckReader.MoveToContent(), System.Xml.Serialization.XmlSerializationReader.ReadArray(), System.Xml.XmlReader.ReadElementString(), System.Xml.XmlReader.ReadElementString(), System.Xml.XmlReader.ReadElementString(), System.Xml.XmlReader.ReadEndElement(), System.Xml.Serialization.XmlSerializationReader.ReadReferencedElements(), System.Xml.Serialization.XmlSerializationReader.ReadReferencingElement(), System.Xml.Serialization.XmlSerializationReader.ReadSerializable(), System.Xml.XmlReader.ReadStartElement(), System.Xml.XmlReader.ReadStartElement(), System.Xml.XmlReader.ReadStartElement(), System.Xml.Linq.XElement.ReadXml(), System.Data.DataSet.ReadXml(), System.Data.DataTable.ReadXml(), System.Data.DataSet.ReadXml(), System.Data.DataTable.ReadXml(), System.Data.DataSet.ReadXmlDiffgram(), System.Data.DataTable.ReadXmlDiffgram(), System.Xml.Serialization.XmlSerializationReader.ReadXmlNode(), and System.Data.DataSet.ReadXmlSchema().