Terraria: System.Xml.XmlReader.Close
Close()
virtual void System.Xml.XmlReader.Close () inline virtual
Reimplemented in System.Data.DataTextReader, System.Runtime.Serialization.Json.XmlJsonReader, System.Runtime.Serialization.XmlSerializableReader, System.Xml.XmlBaseReader, System.Xml.XmlBinaryReader, System.Xml.XmlDictionaryReader.XmlWrappedReader, System.Xml.XmlUTF8TextReader, System.Xml.Linq.XNodeReader, System.Xml.XPath.XPathNavigatorReader, System.Xml.Xsl.XsltOld.ReaderOutput, System.Xml.XmlAsyncCheckReader, System.Xml.XmlNodeReader, System.Xml.XmlSqlBinaryReader, System.Xml.XmlSubtreeReader, System.Xml.XmlTextReader, System.Xml.XmlTextReaderImpl, System.Xml.XmlValidatingReader, System.Xml.XmlValidatingReaderImpl, System.Xml.XmlWrappingReader, System.Xml.XsdCachingReader, and System.Xml.XsdValidatingReader.
Definition at line 528 of file XmlReader.cs.
    {
    }
Referenced by System.Data.DataTextReader.Close(), System.Xml.XmlAsyncCheckReader.Close(), System.Xml.XmlSqlBinaryReader.Close(), System.Xml.XmlValidatingReaderImpl.Close(), System.Xml.XmlWrappingReader.Close(), System.Xml.XsdCachingReader.Close(), System.Xml.XsdValidatingReader.Close(), System.Xml.XmlReader.Dispose(), and System.Xml.XmlLoader.ParsePartialContent().