Terraria: System.Xml.XmlReader.ReadContentAsAsync
ReadContentAsAsync()
virtual async Task< object > System.Xml.XmlReader.ReadContentAsAsync (Type returnType, IXmlNamespaceResolver? namespaceResolver) inline virtual inherited
Definition at line 1518 of file XmlReader.cs.
    {
        if (!CanReadContentAs())
        {
            throw CreateReadContentAsException("ReadContentAs");
        }
        string text = await InternalReadContentAsStringAsync().ConfigureAwait(continueOnCapturedContext: false);
        if (returnType == typeof(string))
        {
            return text;
        }
        try
        {
            return XmlUntypedConverter.Untyped.ChangeType(text, returnType, namespaceResolver ?? (this as IXmlNamespaceResolver));
        }
        catch (FormatException innerException)
        {
            throw new XmlException(System.SR.Xml_ReadContentAsFormatException, returnType.ToString(), innerException, this as IXmlLineInfo);
        }
        catch (InvalidCastException innerException2)
        {
            throw new XmlException(System.SR.Xml_ReadContentAsFormatException, returnType.ToString(), innerException2, this as IXmlLineInfo);
        }
    }
References System.Xml.XmlReader.CanReadContentAs(), System.Xml.XmlReader.CreateReadContentAsException(), System.Xml.Dictionary, System.Xml.XmlReader.InternalReadContentAsStringAsync(), System.text, System.Xml.Schema.XmlUntypedConverter.Untyped, System.SR.Xml_ReadContentAsFormatException, and System.Xml.XmlException.
Referenced by System.Xml.XmlAsyncCheckReader.ReadContentAsAsync(), System.Xml.XmlSubtreeReader.ReadContentAsAsync(), and System.Xml.XmlReader.ReadElementContentAsAsync().