Terraria: System.Xml.XmlReader.ReadStartElement
ReadStartElement() [1/3]
virtual void System.Xml.XmlReader.ReadStartElement () inline virtual inherited
Reimplemented in System.Xml.XmlBaseReader, System.Xml.XmlUTF8TextReader, and System.Xml.XmlAsyncCheckReader.
Definition at line 629 of file XmlReader.cs.
    {
        if (MoveToContent() != XmlNodeType.Element)
        {
            throw new XmlException(System.SR.Xml_InvalidNodeType, NodeType.ToString(), this as IXmlLineInfo);
        }
        Read();
    }
References System.Xml.Dictionary, System.Xml.XmlReader.MoveToContent(), System.Xml.XmlReader.NodeType, System.Xml.XmlReader.Read(), System.SR.Xml_InvalidNodeType, and System.Xml.XmlException.
Referenced by System.Xml.Serialization.XmlSerializationReader.ReadArray(), System.Runtime.Serialization.Json.JsonReaderDelegator.ReadElementContentAsBase64(), System.Xml.XmlDictionaryReader.ReadElementContentAsBase64(), System.Xml.XmlDictionaryReader.ReadElementContentAsBinHex(), System.Xml.XmlDictionaryReader.ReadElementContentAsBoolean(), System.Xml.XmlDictionaryReader.ReadElementContentAsDateTime(), System.Xml.XmlDictionaryReader.ReadElementContentAsDecimal(), System.Xml.XmlDictionaryReader.ReadElementContentAsDouble(), System.Xml.XmlDictionaryReader.ReadElementContentAsFloat(), System.Xml.XmlDictionaryReader.ReadElementContentAsGuid(), System.Xml.XmlDictionaryReader.ReadElementContentAsInt(), System.Xml.XmlDictionaryReader.ReadElementContentAsLong(), System.Xml.XmlDictionaryReader.ReadElementContentAsString(), System.Xml.XmlDictionaryReader.ReadElementContentAsTimeSpan(), System.Xml.XmlDictionaryReader.ReadElementContentAsUniqueId(), System.Xml.Serialization.XmlSerializationReader.ReadNull(), System.Xml.Serialization.XmlSerializationReader.ReadReference(), System.Xml.XmlAsyncCheckReader.ReadStartElement(), System.Xml.XmlDictionaryReader.XmlWrappedReader.ReadStartElement(), System.Xml.XmlAsyncCheckReader.ReadStartElement(), System.Xml.XmlDictionaryReader.XmlWrappedReader.ReadStartElement(), System.Xml.XmlAsyncCheckReader.ReadStartElement(), System.Xml.Serialization.XmlSerializationReader.ReadStringValue(), System.Xml.Serialization.XmlSerializationReader.ReadXmlNode(), and System.Xml.Serialization.XmlSerializationReader.ReadXmlQualifiedName().