Terraria: System.IO.Strategies.FileStreamHelpers.SerializationGuard
SerializationGuard()
static void System.IO.Strategies.FileStreamHelpers.SerializationGuard (FileAccess access) inline static package
Definition at line 200 of file FileStreamHelpers.cs.
    {
        if ((access & FileAccess.Write) == FileAccess.Write)
        {
            SerializationInfo.ThrowIfDeserializationInProgress("AllowFileWrites", ref s_cachedSerializationSwitch);
        }
    }
References System.Runtime.Serialization.Dictionary, System.IO.Strategies.FileStreamHelpers.s_cachedSerializationSwitch, and System.Runtime.Serialization.SerializationInfo.ThrowIfDeserializationInProgress().
Referenced by System.IO.FileStream.FileStream(), and System.IO.Strategies.FileStreamHelpers.ValidateArguments().