Terraria: System.Xml.XmlReader.MoveToNextAttribute
MoveToNextAttribute()
bool System.Xml.XmlReader.MoveToNextAttribute () abstract
Referenced by System.Xml.XPath.XPathNavigator.BuildSubtree(), System.Xml.XmlLoader.LoadDeclarationNode(), System.Xml.XmlLoader.LoadDocumentTypeNode(), System.Xml.Schema.Parser.LoadElementNode(), System.Xml.XPath.XPathDocument.LoadFromReader(), System.Xml.XmlLoader.LoadNode(), System.Xml.XmlLoader.LoadNodeDirect(), System.Xml.XmlReader.MoveToAttribute(), System.Data.DataTextReader.MoveToNextAttribute(), System.Runtime.Serialization.XmlReaderDelegator.MoveToNextAttribute(), System.Runtime.Serialization.XmlSerializableReader.MoveToNextAttribute(), System.Xml.XmlDictionaryReader.XmlWrappedReader.MoveToNextAttribute(), System.Xml.XmlAsyncCheckReader.MoveToNextAttribute(), System.Xml.XmlCharCheckingReader.MoveToNextAttribute(), System.Xml.XmlSqlBinaryReader.MoveToNextAttribute(), System.Xml.XmlSubtreeReader.MoveToNextAttribute(), System.Xml.XmlValidatingReaderImpl.MoveToNextAttribute(), System.Xml.XmlWrappingReader.MoveToNextAttribute(), System.Xml.XsdValidatingReader.MoveToNextAttribute(), System.Xml.Schema.Parser.ParseReaderNode(), System.Xml.Schema.XmlSchemaInference.ProcessAttributes(), System.Xml.XsdValidatingReader.ProcessElementEvent(), System.Xml.XsdValidatingReader.ProcessElementEventAsync(), System.Xml.XmlSubtreeReader.ProcessNamespaces(), System.Xml.XmlCharCheckingReader.Read(), System.Xml.XmlCharCheckingReader.ReadAsync(), System.Xml.Xsl.Xslt.XsltInput.ReadElement(), System.Xml.XsdCachingReader.RecordAttributes(), System.Xml.XsdValidatingReader.ValidateAttributes(), System.Xml.XmlWriter.WriteAttributes(), System.Xml.XmlWriter.WriteAttributesAsync(), and System.Xml.XmlDictionaryWriter.WriteElementNode().