Terraria: System.Xml.XmlReader.ReadElementContentAsBase64
ReadElementContentAsBase64()
virtual int System.Xml.XmlReader.ReadElementContentAsBase64 (byte[] buffer, int index, int count) inline virtual inherited
Reimplemented in System.Data.DataTextReader, System.Xml.XPath.XPathNavigatorReader, System.Xml.XmlAsyncCheckReader, System.Xml.XmlCharCheckingReader, System.Xml.XmlNodeReader, System.Xml.XmlSubtreeReader, System.Xml.XmlTextReader, System.Xml.XmlTextReaderImpl, System.Xml.XmlValidatingReader, System.Xml.XmlValidatingReaderImpl, System.Xml.XsdValidatingReader, System.Xml.XmlBaseReader, and System.Xml.XmlDictionaryReader.XmlWrappedReader.
Definition at line 549 of file XmlReader.cs.
    {
        throw new NotSupportedException(System.SR.Format(System.SR.Xml_ReadBinaryContentNotSupported, "ReadElementContentAsBase64"));
    }
References System.SR.Format(), and System.SR.Xml_ReadBinaryContentNotSupported.
Referenced by System.Xml.Serialization.XmlSerializationReader.ReadByteArray(), System.Data.DataTextReader.ReadElementContentAsBase64(), System.Xml.XmlAsyncCheckReader.ReadElementContentAsBase64(), and System.Xml.XmlDictionaryReader.XmlWrappedReader.ReadElementContentAsBase64().