Terraria: System.Xml.XmlReader.InternalReadContentAsStringAsync
InternalReadContentAsStringAsync()
async Task< string > System.Xml.XmlReader.InternalReadContentAsStringAsync () inline package inherited
Definition at line 1779 of file XmlReader.cs.
    {
        string value = string.Empty;
        StringBuilder sb = null;
        bool flag;
        do
        {
            switch (NodeType)
            {
            case XmlNodeType.Attribute:
                return Value;
            case XmlNodeType.Text:
            case XmlNodeType.CDATA:
            case XmlNodeType.Whitespace:
            case XmlNodeType.SignificantWhitespace:
                if (value.Length == 0)
                {
                    value = await GetValueAsync().ConfigureAwait(continueOnCapturedContext: false);
                }
                else
                {
                    if (sb == null)
                    {
                        sb = new StringBuilder();
                        sb.Append(value);
                    }
                    StringBuilder stringBuilder = sb;
                    stringBuilder.Append(await GetValueAsync().ConfigureAwait(continueOnCapturedContext: false));
                }
                goto case XmlNodeType.ProcessingInstruction;
            case XmlNodeType.EntityReference:
                if (!CanResolveEntity)
                {
                    break;
                }
                ResolveEntity();
                goto case XmlNodeType.ProcessingInstruction;
            case XmlNodeType.ProcessingInstruction:
            case XmlNodeType.Comment:
            case XmlNodeType.EndEntity:
                flag = ((AttributeCount == 0) ? (await ReadAsync().ConfigureAwait(continueOnCapturedContext: false)) : ReadAttributeValue());
                continue;
            }
            break;
        }
        while (flag);
        return (sb == null) ? value : sb.ToString();
    }
References System.Text.StringBuilder.Append(), System.Xml.XmlReader.AttributeCount, System.Xml.XmlReader.CanResolveEntity, System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.Xml.Dictionary, System.Xml.XmlReader.GetValueAsync(), System.Xml.XmlReader.NodeType, System.Xml.XmlReader.ReadAsync(), System.Xml.XmlReader.ReadAttributeValue(), System.Xml.XmlReader.ResolveEntity(), System.Text.StringBuilder.ToString(), System.value, and System.Xml.XmlReader.Value.
Referenced by System.Xml.XsdValidatingReader.InternalReadContentAsObjectTupleAsync(), System.Xml.XmlReader.ReadContentAsAsync(), System.Xml.XmlReader.ReadContentAsObjectAsync(), and System.Xml.XmlReader.ReadContentAsStringAsync().