Terraria: System.Xml.XmlReader.CanReadContentAs
CanReadContentAs() [1/2]
bool System.Xml.XmlReader.CanReadContentAs () inline package inherited
Definition at line 1194 of file XmlReader.cs.
    {
        return CanReadContentAs(NodeType);
    }
References System.Xml.XmlReader.CanReadContentAs(), and System.Xml.XmlReader.NodeType.
Referenced by System.Xml.XmlReader.CanReadContentAs(), System.Xml.XmlReader.ReadContentAs(), System.Xml.XmlReader.ReadContentAsAsync(), System.Xml.XmlReader.ReadContentAsBoolean(), System.Xml.XmlReader.ReadContentAsDateTime(), System.Xml.XmlReader.ReadContentAsDateTimeOffset(), System.Xml.XmlReader.ReadContentAsDecimal(), System.Xml.XmlReader.ReadContentAsDouble(), System.Xml.XmlReader.ReadContentAsFloat(), System.Xml.XmlReader.ReadContentAsInt(), System.Xml.XmlReader.ReadContentAsLong(), System.Xml.XmlReader.ReadContentAsObject(), System.Xml.XmlReader.ReadContentAsObjectAsync(), System.Xml.XmlReader.ReadContentAsString(), and System.Xml.XmlReader.ReadContentAsStringAsync().