Terraria: System.Xml.XmlReader.ReadEndElement
ReadEndElement()
virtual void System.Xml.XmlReader.ReadEndElement () inline virtual inherited
Reimplemented in System.Xml.XmlBaseReader, System.Xml.XmlDictionaryReader.XmlWrappedReader, System.Xml.XmlUTF8TextReader, and System.Xml.XmlAsyncCheckReader.
Definition at line 751 of file XmlReader.cs.
    {
        if (MoveToContent() != XmlNodeType.EndElement)
        {
            throw new XmlException(System.SR.Xml_InvalidNodeType, NodeType.ToString(), this as IXmlLineInfo);
        }
        Read();
    }
References System.Xml.Dictionary, System.Xml.XmlReader.MoveToContent(), System.Xml.XmlReader.NodeType, System.Xml.XmlReader.Read(), System.SR.Xml_InvalidNodeType, and System.Xml.XmlException.
Referenced by System.Runtime.Serialization.Json.JsonReaderDelegator.ReadElementContentAsBase64(), System.Xml.XmlDictionaryReader.ReadElementContentAsBase64(), System.Xml.XmlDictionaryReader.ReadElementContentAsBinHex(), System.Xml.XmlDictionaryReader.ReadElementContentAsBoolean(), System.Xml.XmlDictionaryReader.ReadElementContentAsDateTime(), System.Xml.XmlDictionaryReader.ReadElementContentAsDecimal(), System.Xml.XmlDictionaryReader.ReadElementContentAsDouble(), System.Xml.XmlDictionaryReader.ReadElementContentAsFloat(), System.Xml.XmlDictionaryReader.ReadElementContentAsGuid(), System.Xml.XmlDictionaryReader.ReadElementContentAsInt(), System.Xml.XmlDictionaryReader.ReadElementContentAsLong(), System.Xml.XmlDictionaryReader.ReadElementContentAsString(), System.Xml.XmlDictionaryReader.ReadElementContentAsTimeSpan(), System.Xml.XmlDictionaryReader.ReadElementContentAsUniqueId(), System.Xml.Serialization.XmlSerializationReader.ReadElementQualifiedName(), System.Runtime.Serialization.XmlReaderDelegator.ReadEndElement(), System.Xml.XmlDictionaryReader.XmlWrappedReader.ReadEndElement(), System.Xml.Serialization.XmlSerializationReader.ReadEndElement(), System.Xml.XmlAsyncCheckReader.ReadEndElement(), System.Data.DataSet.ReadEndElement(), System.Data.DataTable.ReadEndElement(), System.Xml.Serialization.XmlSerializationReader.ReadXmlNode(), and System.Runtime.Serialization.ExtensionDataReader.Skip().