Terraria: System.Xml.XmlReader.CheckElement
CheckElement()
void System.Xml.XmlReader.CheckElement (string localName, string namespaceURI) inline package inherited
Definition at line 1164 of file XmlReader.cs.
    {
        if (localName == null || localName.Length == 0)
        {
            throw XmlConvert.CreateInvalidNameArgumentException(localName, "localName");
        }
        if (namespaceURI == null)
        {
            throw new ArgumentNullException("namespaceURI");
        }
        if (NodeType != XmlNodeType.Element)
        {
            throw new XmlException(System.SR.Xml_InvalidNodeType, NodeType.ToString(), this as IXmlLineInfo);
        }
        if (LocalName != localName || NamespaceURI != namespaceURI)
        {
            throw new XmlException(System.SR.Xml_ElementNotFoundNs, new string[2] { localName, namespaceURI }, this as IXmlLineInfo);
        }
    }
References System.Xml.XmlConvert.CreateInvalidNameArgumentException(), System.Xml.Dictionary, System.Xml.XmlReader.LocalName, System.Xml.XmlReader.NamespaceURI, System.Xml.XmlReader.NodeType, System.SR.Xml_ElementNotFoundNs, System.SR.Xml_InvalidNodeType, and System.Xml.XmlException.
Referenced by System.Xml.XmlReader.ReadElementContentAs(), System.Xml.XmlReader.ReadElementContentAsBoolean(), System.Xml.XmlReader.ReadElementContentAsDateTime(), System.Xml.XmlReader.ReadElementContentAsDecimal(), System.Xml.XmlReader.ReadElementContentAsDouble(), System.Xml.XmlReader.ReadElementContentAsFloat(), System.Xml.XmlReader.ReadElementContentAsInt(), System.Xml.XmlReader.ReadElementContentAsLong(), System.Xml.XmlReader.ReadElementContentAsObject(), and System.Xml.XmlReader.ReadElementContentAsString().