Terraria: System.Xml.XmlReader.ReadElementContentAsAsync
ReadElementContentAsAsync()
virtual async Task< object > System.Xml.XmlReader.ReadElementContentAsAsync (Type returnType, IXmlNamespaceResolver namespaceResolver) inline virtual inherited
Reimplemented in System.Xml.XmlAsyncCheckReader, and System.Xml.XsdValidatingReader.
Definition at line 1565 of file XmlReader.cs.
    {
        if (await SetupReadElementContentAsXxxAsync("ReadElementContentAs").ConfigureAwait(continueOnCapturedContext: false))
        {
            object value = await ReadContentAsAsync(returnType, namespaceResolver).ConfigureAwait(continueOnCapturedContext: false);
            await FinishReadElementContentAsXxxAsync().ConfigureAwait(continueOnCapturedContext: false);
            return value;
        }
        return (returnType == typeof(string)) ? string.Empty : XmlUntypedConverter.Untyped.ChangeType(string.Empty, returnType, namespaceResolver);
    }
References System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.Xml.Dictionary, System.Xml.XmlReader.FinishReadElementContentAsXxxAsync(), System.Xml.XmlReader.ReadContentAsAsync(), System.Xml.XmlReader.SetupReadElementContentAsXxxAsync(), System.Xml.Schema.XmlUntypedConverter.Untyped, and System.value.
Referenced by System.Xml.XmlAsyncCheckReader.ReadElementContentAsAsync().