Terraria: System.Xml.XmlReader.ReadElementString
ReadElementString() [2/3]
virtual string System.Xml.XmlReader.ReadElementString (string localname, string ns) inline virtual inherited
Reimplemented in System.Xml.XmlAsyncCheckReader.
Definition at line 724 of file XmlReader.cs.
    {
        string result = string.Empty;
        if (MoveToContent() != XmlNodeType.Element)
        {
            throw new XmlException(System.SR.Xml_InvalidNodeType, NodeType.ToString(), this as IXmlLineInfo);
        }
        if (LocalName != localname || NamespaceURI != ns)
        {
            throw new XmlException(System.SR.Xml_ElementNotFoundNs, new string[2] { localname, ns }, this as IXmlLineInfo);
        }
        if (!IsEmptyElement)
        {
            result = ReadString();
            if (NodeType != XmlNodeType.EndElement)
            {
                throw new XmlException(System.SR.Xml_InvalidNodeType, NodeType.ToString(), this as IXmlLineInfo);
            }
            Read();
        }
        else
        {
            Read();
        }
        return result;
    }
References System.Xml.Dictionary, System.Xml.XmlReader.IsEmptyElement, System.Xml.XmlReader.LocalName, System.Xml.XmlReader.MoveToContent(), System.Xml.XmlReader.NamespaceURI, System.Xml.XmlReader.NodeType, System.Xml.XmlReader.Read(), System.Xml.XmlReader.ReadString(), System.SR.Xml_ElementNotFoundNs, System.SR.Xml_InvalidNodeType, and System.Xml.XmlException.