Terraria: System.Xml.XmlReader.SkipSubtree
SkipSubtree()
bool System.Xml.XmlReader.SkipSubtree () inline private inherited
Definition at line 1146 of file XmlReader.cs.
    {
        MoveToElement();
        if (NodeType == XmlNodeType.Element && !IsEmptyElement)
        {
            int depth = Depth;
            while (Read() && depth < Depth)
            {
            }
            if (NodeType == XmlNodeType.EndElement)
            {
                return Read();
            }
            return false;
        }
        return Read();
    }
References System.Xml.XmlReader.Depth, System.Xml.XmlReader.IsEmptyElement, System.Xml.XmlReader.MoveToElement(), System.Xml.XmlReader.NodeType, and System.Xml.XmlReader.Read().
Referenced by System.Xml.XmlReader.ReadToNextSibling(), System.Xml.XmlReader.ReadToNextSibling(), and System.Xml.XmlReader.Skip().