Terraria: System.IO.Strategies.FileStreamHelpers.GetLastWin32ErrorAndDisposeHandleIfInvalid
GetLastWin32ErrorAndDisposeHandleIfInvalid()
static int System.IO.Strategies.FileStreamHelpers.GetLastWin32ErrorAndDisposeHandleIfInvalid (SafeFileHandle handle) inline static package
Definition at line 252 of file FileStreamHelpers.cs.
    {
        int lastPInvokeError = Marshal.GetLastPInvokeError();
        if (lastPInvokeError == 6)
        {
            handle.Dispose();
        }
        return lastPInvokeError;
    }
References System.Runtime.Serialization.Dictionary, System.Runtime.InteropServices.Marshal.GetLastPInvokeError(), and System.handle.
Referenced by System.IO.RandomAccess.ReadAtOffset(), System.IO.Strategies.FileStreamHelpers.ReadFileNative(), System.IO.RandomAccess.ReadFileScatterAsync(), System.IO.RandomAccess.ReadSyncUsingAsyncHandle(), System.IO.Strategies.FileStreamHelpers.Seek(), System.IO.RandomAccess.WriteAtOffset(), System.IO.RandomAccess.WriteFileGatherAsync(), System.IO.Strategies.Net5CompatFileStreamStrategy.WriteFileNative(), and System.IO.RandomAccess.WriteSyncUsingAsyncHandle().