Terraria: System.Xml.XmlReader.IsStartElement
IsStartElement() [1/3]
virtual bool System.Xml.XmlReader.IsStartElement () inline virtual inherited
Reimplemented in System.Runtime.Serialization.XmlSerializableReader, System.Xml.XmlBaseReader, and System.Xml.XmlAsyncCheckReader.
Definition at line 760 of file XmlReader.cs.
    {
        return MoveToContent() == XmlNodeType.Element;
    }
References System.Xml.XmlReader.MoveToContent().
Referenced by System.Runtime.Serialization.XmlReaderDelegator.IsStartElement(), System.Runtime.Serialization.XmlSerializableReader.IsStartElement(), System.Xml.XmlAsyncCheckReader.IsStartElement(), System.Xml.XmlDictionaryReader.XmlWrappedReader.IsStartElement(), System.Runtime.Serialization.XmlReaderDelegator.IsStartElement(), System.Runtime.Serialization.XmlSerializableReader.IsStartElement(), System.Xml.XmlAsyncCheckReader.IsStartElement(), System.Runtime.Serialization.XmlSerializableReader.IsStartElement(), System.Xml.XmlDictionaryReader.XmlWrappedReader.IsStartElement(), System.Xml.XmlAsyncCheckReader.IsStartElement(), System.Xml.XmlDictionaryReader.IsStartElement(), System.Runtime.Serialization.XmlReaderDelegator.IsStartElement(), System.Xml.XmlDictionaryReader.MoveToStartElement(), System.Xml.XmlDictionaryReader.MoveToStartElement(), System.Xml.XmlDictionaryReader.MoveToStartElement(), System.Xml.XmlDictionaryReader.MoveToStartElement(), System.Xml.XmlDictionaryReader.ReadArray(), System.Xml.XmlDictionaryReader.ReadArray(), System.Xml.XmlDictionaryReader.ReadArray(), System.Xml.XmlDictionaryReader.ReadArray(), System.Xml.XmlDictionaryReader.ReadArray(), System.Xml.XmlDictionaryReader.ReadArray(), System.Xml.XmlDictionaryReader.ReadArray(), System.Xml.XmlDictionaryReader.ReadArray(), System.Xml.XmlDictionaryReader.ReadArray(), System.Xml.XmlDictionaryReader.ReadArray(), System.Runtime.Serialization.Json.JsonReaderDelegator.DateTimeArrayJsonHelperWithString.ReadArray(), System.Runtime.Serialization.Json.JsonReaderDelegator.ReadElementContentAsBase64(), System.Xml.XmlDictionaryReader.ReadElementContentAsBase64(), System.Xml.XmlDictionaryReader.ReadElementContentAsBinHex(), System.Xml.XmlDictionaryReader.ReadElementContentAsBoolean(), System.Xml.XmlDictionaryReader.ReadElementContentAsDateTime(), System.Xml.XmlDictionaryReader.ReadElementContentAsDecimal(), System.Xml.XmlDictionaryReader.ReadElementContentAsDouble(), System.Xml.XmlDictionaryReader.ReadElementContentAsFloat(), System.Xml.XmlDictionaryReader.ReadElementContentAsGuid(), System.Xml.XmlDictionaryReader.ReadElementContentAsInt(), System.Xml.XmlDictionaryReader.ReadElementContentAsLong(), System.Xml.XmlDictionaryReader.ReadElementContentAsString(), System.Xml.XmlDictionaryReader.ReadElementContentAsTimeSpan(), and System.Xml.XmlDictionaryReader.ReadElementContentAsUniqueId().