Terraria: System.Xml.XmlReader.ReadContentAsObject
ReadContentAsObject()
virtual object System.Xml.XmlReader.ReadContentAsObject () inline virtual inherited
Reimplemented in System.Runtime.Serialization.XmlSerializableReader, System.Xml.XmlBaseReader, System.Xml.XmlAsyncCheckReader, System.Xml.XmlSqlBinaryReader, System.Xml.XmlSubtreeReader, and System.Xml.XsdValidatingReader.
Definition at line 149 of file XmlReader.cs.
    {
        if (!CanReadContentAs())
        {
            throw CreateReadContentAsException("ReadContentAsObject");
        }
        return InternalReadContentAsString();
    }
References System.Xml.XmlReader.CanReadContentAs(), System.Xml.XmlReader.CreateReadContentAsException(), and System.Xml.XmlReader.InternalReadContentAsString().
Referenced by System.Runtime.Serialization.XmlSerializableReader.ReadContentAsObject(), System.Xml.XmlAsyncCheckReader.ReadContentAsObject(), System.Xml.XmlSubtreeReader.ReadContentAsObject(), System.Xml.XmlReader.ReadElementContentAsObject(), and System.Xml.XmlBinaryWriter.WriteTextNode().