Terraria: System.Xml.XmlReader.CalcBufferSize
CalcBufferSize()
static int System.Xml.XmlReader.CalcBufferSize (Stream input) inline static package inherited
Definition at line 1477 of file XmlReader.cs.
    {
        int num = 4096;
        if (input.CanSeek)
        {
            long length = input.Length;
            if (length < num)
            {
                num = checked((int)length);
            }
            else if (length > 65536)
            {
                num = 8192;
            }
        }
        return num;
    }
References System.Xml.Dictionary, System.input, and System.length.
Referenced by System.Xml.XmlReader.CreateSqlReader(), System.Xml.XmlTextReaderImpl.InitStreamInput(), and System.Xml.XmlTextReaderImpl.InitStreamInputAsync().