Terraria: System.Xml.XmlReader.CreateReadContentAsException
CreateReadContentAsException() [1/2]
Exception System.Xml.XmlReader.CreateReadContentAsException (string methodName) inline package inherited
Definition at line 1184 of file XmlReader.cs.
    {
        return CreateReadContentAsException(methodName, NodeType, this as IXmlLineInfo);
    }
References System.Xml.XmlReader.CreateReadContentAsException(), System.Xml.Dictionary, and System.Xml.XmlReader.NodeType.
Referenced by System.Xml.XmlReader.CreateReadContentAsException(), System.Xml.XmlSubtreeReader.InitReadContentAsType(), System.Xml.XsdValidatingReader.ReadContentAs(), System.Xml.XmlReader.ReadContentAs(), System.Xml.XsdValidatingReader.ReadContentAsAsync(), System.Xml.XmlReader.ReadContentAsAsync(), System.Xml.ReadContentAsBinaryHelper.ReadContentAsBase64(), System.Xml.XmlSubtreeReader.ReadContentAsBase64(), System.Xml.XmlTextReaderImpl.ReadContentAsBase64(), System.Xml.ReadContentAsBinaryHelper.ReadContentAsBase64Async(), System.Xml.XmlSubtreeReader.ReadContentAsBase64Async(), System.Xml.XmlTextReaderImpl.ReadContentAsBase64Async(), System.Xml.ReadContentAsBinaryHelper.ReadContentAsBinHex(), System.Xml.XmlSubtreeReader.ReadContentAsBinHex(), System.Xml.XmlTextReaderImpl.ReadContentAsBinHex(), System.Xml.ReadContentAsBinaryHelper.ReadContentAsBinHexAsync(), System.Xml.XmlSubtreeReader.ReadContentAsBinHexAsync(), System.Xml.XmlTextReaderImpl.ReadContentAsBinHexAsync(), System.Xml.XmlReader.ReadContentAsBoolean(), System.Xml.XsdValidatingReader.ReadContentAsBoolean(), System.Xml.XmlReader.ReadContentAsDateTime(), System.Xml.XsdValidatingReader.ReadContentAsDateTime(), System.Xml.XmlReader.ReadContentAsDateTimeOffset(), System.Xml.XmlReader.ReadContentAsDecimal(), System.Xml.XsdValidatingReader.ReadContentAsDecimal(), System.Xml.XmlReader.ReadContentAsDouble(), System.Xml.XsdValidatingReader.ReadContentAsDouble(), System.Xml.XmlReader.ReadContentAsFloat(), System.Xml.XsdValidatingReader.ReadContentAsFloat(), System.Xml.XmlReader.ReadContentAsInt(), System.Xml.XsdValidatingReader.ReadContentAsInt(), System.Xml.XmlReader.ReadContentAsLong(), System.Xml.XsdValidatingReader.ReadContentAsLong(), System.Xml.XmlReader.ReadContentAsObject(), System.Xml.XsdValidatingReader.ReadContentAsObject(), System.Xml.XmlReader.ReadContentAsObjectAsync(), System.Xml.XsdValidatingReader.ReadContentAsObjectAsync(), System.Xml.XmlReader.ReadContentAsString(), System.Xml.XsdValidatingReader.ReadContentAsString(), System.Xml.XmlReader.ReadContentAsStringAsync(), System.Xml.XsdValidatingReader.ReadContentAsStringAsync(), and System.Xml.XmlSqlBinaryReader.SetupContentAsXXX().