Terraria: System.Xml.XmlReader.MoveToAttribute
MoveToAttribute() [2/3]
bool System.Xml.XmlReader.MoveToAttribute (string name) abstract
Referenced by System.Data.DataTable.IsEmptyXml(), System.Data.XmlDataLoader.LoadTable(), System.Data.DataTextReader.MoveToAttribute(), System.Runtime.Serialization.XmlReaderDelegator.MoveToAttribute(), System.Runtime.Serialization.XmlSerializableReader.MoveToAttribute(), System.Xml.XmlAsyncCheckReader.MoveToAttribute(), System.Xml.XmlCharCheckingReader.MoveToAttribute(), System.Xml.XmlSqlBinaryReader.MoveToAttribute(), System.Xml.XmlSubtreeReader.MoveToAttribute(), System.Xml.XmlValidatingReaderImpl.MoveToAttribute(), System.Xml.XmlWrappingReader.MoveToAttribute(), System.Xml.XsdValidatingReader.MoveToAttribute(), System.Xml.XmlDictionaryReader.XmlWrappedReader.MoveToAttribute(), System.Data.DataTextReader.MoveToAttribute(), System.Xml.XmlValidatingReaderImpl.MoveToAttribute(), System.Data.DataTextReader.MoveToAttribute(), System.Runtime.Serialization.XmlReaderDelegator.MoveToAttribute(), System.Runtime.Serialization.XmlSerializableReader.MoveToAttribute(), System.Xml.XmlDictionaryReader.XmlWrappedReader.MoveToAttribute(), System.Xml.XmlAsyncCheckReader.MoveToAttribute(), System.Xml.XmlCharCheckingReader.MoveToAttribute(), System.Xml.XmlSqlBinaryReader.MoveToAttribute(), System.Xml.XmlSubtreeReader.MoveToAttribute(), System.Xml.XmlValidatingReaderImpl.MoveToAttribute(), System.Xml.XmlWrappingReader.MoveToAttribute(), System.Xml.XsdValidatingReader.MoveToAttribute(), System.Xml.XmlDictionaryReader.XmlWrappedReader.MoveToAttribute(), System.Runtime.Serialization.XmlReaderDelegator.MoveToAttribute(), System.Runtime.Serialization.XmlSerializableReader.MoveToAttribute(), System.Xml.XmlAsyncCheckReader.MoveToAttribute(), System.Xml.XmlCharCheckingReader.MoveToAttribute(), System.Xml.XmlSqlBinaryReader.MoveToAttribute(), System.Xml.XmlSubtreeReader.MoveToAttribute(), System.Xml.XmlWrappingReader.MoveToAttribute(), System.Xml.XsdValidatingReader.MoveToAttribute(), System.Data.DataSet.ReadXml(), System.Data.DataTable.ReadXml(), System.Data.DataSet.ReadXml(), System.Data.DataTable.ReadXml(), System.Data.DataSet.ReadXmlSchema(), System.Data.DataSet.ReadXmlSerializable(), and System.Xml.XmlReader.WriteAttributeValue().