Terraria: System.Xml.XmlReader.ReadElementContentAsObjectAsync
ReadElementContentAsObjectAsync()
virtual async Task< object > System.Xml.XmlReader.ReadElementContentAsObjectAsync () inline virtual inherited
Reimplemented in System.Xml.XmlAsyncCheckReader, and System.Xml.XsdValidatingReader.
Definition at line 1543 of file XmlReader.cs.
    {
        if (await SetupReadElementContentAsXxxAsync("ReadElementContentAsObject").ConfigureAwait(continueOnCapturedContext: false))
        {
            object value = await ReadContentAsObjectAsync().ConfigureAwait(continueOnCapturedContext: false);
            await FinishReadElementContentAsXxxAsync().ConfigureAwait(continueOnCapturedContext: false);
            return value;
        }
        return string.Empty;
    }
References System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.Xml.Dictionary, System.Xml.XmlReader.FinishReadElementContentAsXxxAsync(), System.Xml.XmlReader.ReadContentAsObjectAsync(), System.Xml.XmlReader.SetupReadElementContentAsXxxAsync(), and System.value.
Referenced by System.Xml.XmlAsyncCheckReader.ReadElementContentAsObjectAsync().