Terraria: System.Xml.XmlReader.SetupReadElementContentAsXxx
SetupReadElementContentAsXxx()
bool System.Xml.XmlReader.SetupReadElementContentAsXxx (string methodName) inline private inherited
Definition at line 1275 of file XmlReader.cs.
    {
        if (NodeType != XmlNodeType.Element)
        {
            throw CreateReadElementContentAsException(methodName);
        }
        bool isEmptyElement = IsEmptyElement;
        Read();
        if (isEmptyElement)
        {
            return false;
        }
        switch (NodeType)
        {
        case XmlNodeType.EndElement:
            Read();
            return false;
        case XmlNodeType.Element:
            throw new XmlException(System.SR.Xml_MixedReadElementContentAs, string.Empty, this as IXmlLineInfo);
        default:
            return true;
        }
    }
References System.Xml.XmlReader.CreateReadElementContentAsException(), System.Xml.Dictionary, System.Xml.XmlReader.IsEmptyElement, System.Xml.XmlReader.NodeType, System.Xml.XmlReader.Read(), System.SR.Xml_MixedReadElementContentAs, and System.Xml.XmlException.
Referenced by System.Xml.XmlReader.ReadElementContentAs(), System.Xml.XmlReader.ReadElementContentAsBoolean(), System.Xml.XmlReader.ReadElementContentAsDateTime(), System.Xml.XmlReader.ReadElementContentAsDecimal(), System.Xml.XmlReader.ReadElementContentAsDouble(), System.Xml.XmlReader.ReadElementContentAsFloat(), System.Xml.XmlReader.ReadElementContentAsInt(), System.Xml.XmlReader.ReadElementContentAsLong(), System.Xml.XmlReader.ReadElementContentAsObject(), and System.Xml.XmlReader.ReadElementContentAsString().