Terraria: System.Xml.XmlReader.ReadOuterXmlAsync
ReadOuterXmlAsync()
virtual async Task< string > System.Xml.XmlReader.ReadOuterXmlAsync () inline virtual inherited
Reimplemented in System.Xml.XmlAsyncCheckReader.
Definition at line 1728 of file XmlReader.cs.
    {
        if (ReadState != ReadState.Interactive)
        {
            return string.Empty;
        }
        if (NodeType != XmlNodeType.Attribute && NodeType != XmlNodeType.Element)
        {
            await ReadAsync().ConfigureAwait(continueOnCapturedContext: false);
            return string.Empty;
        }
        StringWriter stringWriter = new StringWriter(CultureInfo.InvariantCulture);
        XmlWriter xmlWriter = CreateWriterForInnerOuterXml(stringWriter);
        try
        {
            if (NodeType == XmlNodeType.Attribute)
            {
                xmlWriter.WriteStartAttribute(Prefix, LocalName, NamespaceURI);
                WriteAttributeValue(xmlWriter);
                xmlWriter.WriteEndAttribute();
            }
            else
            {
                xmlWriter.WriteNode(this, defattr: false);
            }
        }
        finally
        {
            xmlWriter.Close();
        }
        return stringWriter.ToString();
    }
References System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.Xml.XmlReader.CreateWriterForInnerOuterXml(), System.Xml.Dictionary, System.Globalization.CultureInfo.InvariantCulture, System.Xml.XmlReader.LocalName, System.Xml.XmlReader.NamespaceURI, System.Xml.XmlReader.NodeType, System.Xml.XmlReader.Prefix, System.Xml.XmlReader.ReadAsync(), and System.Xml.XmlReader.WriteAttributeValue().
Referenced by System.Xml.XmlAsyncCheckReader.ReadOuterXmlAsync().