Terraria: System.IO.Strategies.FileStreamHelpers.ValidateArguments
ValidateArguments()
static void System.IO.Strategies.FileStreamHelpers.ValidateArguments (string path, FileMode mode, FileAccess access, FileShare share, int bufferSize, FileOptions options, long preallocationSize) inline static package
Definition at line 133 of file FileStreamHelpers.cs.
    {
        if (path == null)
        {
            throw new ArgumentNullException("path", SR.ArgumentNull_Path);
        }
        if (path.Length == 0)
        {
            throw new ArgumentException(SR.Argument_EmptyPath, "path");
        }
        FileShare fileShare = share & ~FileShare.Inheritable;
        string text = null;
        if (mode < FileMode.CreateNew || mode > FileMode.Append)
        {
            text = "mode";
        }
        else if (access < FileAccess.Read || access > FileAccess.ReadWrite)
        {
            text = "access";
        }
        else if ((fileShare < FileShare.None) || fileShare > (FileShare.ReadWrite | FileShare.Delete))
        {
            text = "share";
        }
        if (text != null)
        {
            throw new ArgumentOutOfRangeException(text, SR.ArgumentOutOfRange_Enum);
        }
        if (options != 0 && (options & (FileOptions)67092479) != 0)
        {
            throw new ArgumentOutOfRangeException("options", SR.ArgumentOutOfRange_Enum);
        }
        if (bufferSize < 0)
        {
            ThrowHelper.ThrowArgumentOutOfRangeException_NeedNonNegNum("bufferSize");
        }
        else if (preallocationSize < 0)
        {
            ThrowHelper.ThrowArgumentOutOfRangeException_NeedNonNegNum("preallocationSize");
        }
        if ((access & FileAccess.Write) == 0 && (mode == FileMode.Truncate || mode == FileMode.CreateNew || mode == FileMode.Create || mode == FileMode.Append))
        {
            throw new ArgumentException(SR.Format(SR.Argument_InvalidFileModeAndAccessCombo, mode, access), "access");
        }
        if ((access & FileAccess.Read) != 0 && mode == FileMode.Append)
        {
            throw new ArgumentException(SR.Argument_InvalidAppendMode, "access");
        }
        if (preallocationSize > 0)
        {
            ValidateArgumentsForPreallocation(mode, access);
        }
        SerializationGuard(access);
    }
References System.SR.Argument_EmptyPath, System.SR.Argument_InvalidAppendMode, System.SR.Argument_InvalidFileModeAndAccessCombo, System.SR.ArgumentNull_Path, System.SR.ArgumentOutOfRange_Enum, System.Runtime.Serialization.Dictionary, System.SR.Format(), System.options, System.IO.Strategies.FileStreamHelpers.SerializationGuard(), System.text, System.ThrowHelper.ThrowArgumentOutOfRangeException_NeedNonNegNum(), and System.IO.Strategies.FileStreamHelpers.ValidateArgumentsForPreallocation().
Referenced by System.IO.FileStream.FileStream(), and System.IO.File.OpenHandle().