Terraria: System.Xml.XmlReader.MoveToAttribute
MoveToAttribute() [1/4]
virtual void System.Xml.XmlReader.MoveToAttribute (int i) inline virtual inherited
Reimplemented in System.Xml.XmlNodeReader, System.Data.DataTextReader, System.Runtime.Serialization.XmlSerializableReader, System.Xml.Xsl.XsltOld.ReaderOutput, System.Xml.XmlAsyncCheckReader, System.Xml.XmlCharCheckingReader, System.Xml.XmlSqlBinaryReader, System.Xml.XmlSubtreeReader, System.Xml.XmlTextReader, System.Xml.XmlTextReaderImpl, System.Xml.XmlValidatingReader, System.Xml.XmlValidatingReaderImpl, System.Xml.XmlWrappingReader, System.Xml.XsdCachingReader, System.Xml.XsdValidatingReader, System.Runtime.Serialization.ExtensionDataReader, System.Xml.XmlBaseReader, System.Xml.XmlDictionaryReader.XmlWrappedReader, and System.Xml.Linq.XNodeReader.
Definition at line 504 of file XmlReader.cs.
    {
        if (i < 0 || i >= AttributeCount)
        {
            throw new ArgumentOutOfRangeException("i");
        }
        MoveToElement();
        MoveToFirstAttribute();
        for (int j = 0; j < i; j++)
        {
            MoveToNextAttribute();
        }
    }
References System.Xml.XmlReader.AttributeCount, System.Xml.Dictionary, System.Xml.XmlReader.MoveToElement(), System.Xml.XmlReader.MoveToFirstAttribute(), and System.Xml.XmlReader.MoveToNextAttribute().