Terraria: System.Xml.XmlReader.MoveToFirstAttribute
MoveToFirstAttribute()
bool System.Xml.XmlReader.MoveToFirstAttribute () abstract
Referenced by System.Xml.Schema.XmlSchemaInference.InferElement(), System.Xml.Schema.Parser.LoadElementNode(), System.Xml.XmlLoader.LoadNode(), System.Xml.XmlLoader.LoadNodeDirect(), System.Xml.XmlReader.MoveToAttribute(), System.Data.DataTextReader.MoveToFirstAttribute(), System.Runtime.Serialization.XmlReaderDelegator.MoveToFirstAttribute(), System.Runtime.Serialization.XmlSerializableReader.MoveToFirstAttribute(), System.Xml.XmlDictionaryReader.XmlWrappedReader.MoveToFirstAttribute(), System.Xml.XmlAsyncCheckReader.MoveToFirstAttribute(), System.Xml.XmlCharCheckingReader.MoveToFirstAttribute(), System.Xml.XmlSqlBinaryReader.MoveToFirstAttribute(), System.Xml.XmlSubtreeReader.MoveToFirstAttribute(), System.Xml.XmlValidatingReaderImpl.MoveToFirstAttribute(), System.Xml.XmlWrappingReader.MoveToFirstAttribute(), System.Xml.XsdValidatingReader.MoveToFirstAttribute(), System.Xml.Schema.Parser.ParseReaderNode(), System.Xml.XsdValidatingReader.ProcessElementEvent(), System.Xml.XsdValidatingReader.ProcessElementEventAsync(), System.Xml.XmlSubtreeReader.ProcessNamespaces(), System.Xml.XmlCharCheckingReader.Read(), System.Xml.XmlCharCheckingReader.ReadAsync(), System.Xml.Xsl.Xslt.XsltInput.ReadElement(), System.Xml.XsdCachingReader.RecordAttributes(), System.Xml.XsdValidatingReader.ValidateAttributes(), System.Xml.XmlWriter.WriteAttributes(), System.Xml.XmlWriter.WriteAttributesAsync(), and System.Xml.XmlDictionaryWriter.WriteElementNode().