Terraria: System.Xml.XmlReader.WriteAttributeValue
WriteAttributeValue()
void System.Xml.XmlReader.WriteAttributeValue (XmlWriter xtw) inline private inherited
Definition at line 1040 of file XmlReader.cs.
    {
        string name = Name;
        while (ReadAttributeValue())
        {
            if (NodeType == XmlNodeType.EntityReference)
            {
                xtw.WriteEntityRef(Name);
            }
            else
            {
                xtw.WriteString(Value);
            }
        }
        MoveToAttribute(name);
    }
References System.Xml.Dictionary, System.Xml.XmlReader.MoveToAttribute(), System.Xml.XmlReader.Name, System.Xml.XmlReader.NodeType, System.Xml.XmlReader.ReadAttributeValue(), and System.Xml.XmlReader.Value.
Referenced by System.Xml.XmlReader.ReadInnerXml(), System.Xml.XmlReader.ReadInnerXmlAsync(), System.Xml.XmlReader.ReadOuterXml(), and System.Xml.XmlReader.ReadOuterXmlAsync().