Terraria: System.Xml.XmlReader.ReadElementContentAsDateTime
ReadElementContentAsDateTime() [1/2]
virtual DateTime System.Xml.XmlReader.ReadElementContentAsDateTime () inline virtual inherited
Reimplemented in System.Xml.XmlBinaryReader, System.Xml.XmlDictionaryReader, System.Xml.XmlAsyncCheckReader, and System.Xml.XsdValidatingReader.
Definition at line 354 of file XmlReader.cs.
    {
        if (SetupReadElementContentAsXxx("ReadElementContentAsDateTime"))
        {
            DateTime result = ReadContentAsDateTime();
            FinishReadElementContentAsXxx();
            return result;
        }
        return XmlConvert.ToDateTime(string.Empty, XmlDateTimeSerializationMode.RoundtripKind);
    }
References System.Xml.XmlReader.FinishReadElementContentAsXxx(), System.Xml.XmlReader.ReadContentAsDateTime(), System.Xml.XmlReader.SetupReadElementContentAsXxx(), and System.Xml.XmlConvert.ToDateTime().
Referenced by System.Xml.XmlAsyncCheckReader.ReadElementContentAsDateTime(), System.Xml.XmlAsyncCheckReader.ReadElementContentAsDateTime(), and System.Xml.XmlReader.ReadElementContentAsDateTime().