Terraria: System.Xml.XmlReader.ReadElementContentAsFloat
ReadElementContentAsFloat() [1/2]
virtual float System.Xml.XmlReader.ReadElementContentAsFloat () inline virtual inherited
Reimplemented in System.Xml.XmlBinaryReader, System.Xml.XmlDictionaryReader, System.Xml.XmlAsyncCheckReader, and System.Xml.XsdValidatingReader.
Definition at line 388 of file XmlReader.cs.
    {
        if (SetupReadElementContentAsXxx("ReadElementContentAsFloat"))
        {
            float result = ReadContentAsFloat();
            FinishReadElementContentAsXxx();
            return result;
        }
        return XmlConvert.ToSingle(string.Empty);
    }
References System.Xml.XmlReader.FinishReadElementContentAsXxx(), System.Xml.XmlReader.ReadContentAsFloat(), System.Xml.XmlReader.SetupReadElementContentAsXxx(), and System.Xml.XmlConvert.ToSingle().
Referenced by System.Runtime.Serialization.XmlReaderDelegator.ReadElementContentAsFloat(), System.Xml.XmlAsyncCheckReader.ReadElementContentAsFloat(), System.Xml.XmlAsyncCheckReader.ReadElementContentAsFloat(), and System.Xml.XmlReader.ReadElementContentAsFloat().