Terraria: System.Xml.XmlReader.WriteNodeAsync
WriteNodeAsync()
async Task System.Xml.XmlReader.WriteNodeAsync (XmlWriter xtw, bool defattr) inline private inherited
Definition at line 1672 of file XmlReader.cs.
    {
        int d = ((NodeType == XmlNodeType.None) ? (-1) : Depth);
        while (await ReadAsync().ConfigureAwait(continueOnCapturedContext: false) && d < Depth)
        {
            switch (NodeType)
            {
            case XmlNodeType.Element:
                xtw.WriteStartElement(Prefix, LocalName, NamespaceURI);
                ((XmlTextWriter)xtw).QuoteChar = QuoteChar;
                xtw.WriteAttributes(this, defattr);
                if (IsEmptyElement)
                {
                    xtw.WriteEndElement();
                }
                break;
            case XmlNodeType.Text:
            {
                XmlWriter xmlWriter = xtw;
                xmlWriter.WriteString(await GetValueAsync().ConfigureAwait(continueOnCapturedContext: false));
                break;
            }
            case XmlNodeType.Whitespace:
            case XmlNodeType.SignificantWhitespace:
            {
                XmlWriter xmlWriter = xtw;
                xmlWriter.WriteWhitespace(await GetValueAsync().ConfigureAwait(continueOnCapturedContext: false));
                break;
            }
            case XmlNodeType.CDATA:
                xtw.WriteCData(Value);
                break;
            case XmlNodeType.EntityReference:
                xtw.WriteEntityRef(Name);
                break;
            case XmlNodeType.ProcessingInstruction:
            case XmlNodeType.XmlDeclaration:
                xtw.WriteProcessingInstruction(Name, Value);
                break;
            case XmlNodeType.DocumentType:
                xtw.WriteDocType(Name, GetAttribute("PUBLIC"), GetAttribute("SYSTEM"), Value);
                break;
            case XmlNodeType.Comment:
                xtw.WriteComment(Value);
                break;
            case XmlNodeType.EndElement:
                xtw.WriteFullEndElement();
                break;
            }
        }
        if (d == Depth && NodeType == XmlNodeType.EndElement)
        {
            await ReadAsync().ConfigureAwait(continueOnCapturedContext: false);
        }
    }
References System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.Xml.XmlReader.Depth, System.Xml.Dictionary, System.Xml.XmlReader.GetAttribute(), System.Xml.XmlReader.GetValueAsync(), System.Xml.XmlReader.IsEmptyElement, System.Xml.XmlReader.LocalName, System.Xml.XmlReader.Name, System.Xml.XmlReader.NamespaceURI, System.Xml.XmlReader.NodeType, System.Xml.XmlReader.Prefix, System.Xml.XmlReader.QuoteChar, System.Xml.XmlReader.ReadAsync(), System.Xml.XmlReader.Value, System.Xml.XmlWriter.WriteString(), and System.Xml.XmlWriter.WriteWhitespace().
Referenced by System.Xml.XmlReader.ReadInnerXmlAsync().