Terraria: System.Xml.XmlReader.ReadElementContentAsInt
ReadElementContentAsInt() [1/2]
virtual int System.Xml.XmlReader.ReadElementContentAsInt () inline virtual inherited
Reimplemented in System.Xml.XmlBinaryReader, System.Xml.XmlDictionaryReader, System.Xml.XmlAsyncCheckReader, and System.Xml.XsdValidatingReader.
Definition at line 422 of file XmlReader.cs.
    {
        if (SetupReadElementContentAsXxx("ReadElementContentAsInt"))
        {
            int result = ReadContentAsInt();
            FinishReadElementContentAsXxx();
            return result;
        }
        return XmlConvert.ToInt32(string.Empty);
    }
References System.Xml.XmlReader.FinishReadElementContentAsXxx(), System.Xml.XmlReader.ReadContentAsInt(), System.Xml.XmlReader.SetupReadElementContentAsXxx(), and System.Xml.XmlConvert.ToInt32().
Referenced by System.Runtime.Serialization.XmlReaderDelegator.ReadElementContentAsInt(), System.Xml.XmlAsyncCheckReader.ReadElementContentAsInt(), System.Xml.XmlAsyncCheckReader.ReadElementContentAsInt(), and System.Xml.XmlReader.ReadElementContentAsInt().