Terraria: System.Xml.XmlReader.ReadElementContentAs
ReadElementContentAs() [1/2]
virtual object System.Xml.XmlReader.ReadElementContentAs (Type returnType, IXmlNamespaceResolver namespaceResolver) inline virtual inherited
Reimplemented in System.Xml.XmlAsyncCheckReader, and System.Xml.XsdValidatingReader.
Definition at line 473 of file XmlReader.cs.
    {
        if (SetupReadElementContentAsXxx("ReadElementContentAs"))
        {
            object result = ReadContentAs(returnType, namespaceResolver);
            FinishReadElementContentAsXxx();
            return result;
        }
        if (!(returnType == typeof(string)))
        {
            return XmlUntypedStringConverter.Instance.FromString(string.Empty, returnType, namespaceResolver);
        }
        return string.Empty;
    }
References System.Xml.Dictionary, System.Xml.XmlReader.FinishReadElementContentAsXxx(), System.Xml.Schema.XmlUntypedStringConverter.Instance, System.Xml.XmlReader.ReadContentAs(), and System.Xml.XmlReader.SetupReadElementContentAsXxx().
Referenced by System.Xml.XmlAsyncCheckReader.ReadElementContentAs(), System.Xml.XmlAsyncCheckReader.ReadElementContentAs(), and System.Xml.XmlReader.ReadElementContentAs().