Terraria: System.Xml.XmlReader.ReadAttributeValue
ReadAttributeValue()
bool System.Xml.XmlReader.ReadAttributeValue () abstract
Referenced by System.Xml.XmlReader.InternalReadContentAsString(), System.Xml.XmlReader.InternalReadContentAsStringAsync(), System.Xml.Schema.Parser.LoadAttributeNode(), System.Xml.XmlLoader.LoadAttributeNode(), System.Xml.XmlLoader.LoadAttributeValue(), System.Xml.Schema.Parser.LoadEntityReferenceInAttribute(), System.Xml.Xsl.Xslt.XsltInput.ReadAttribute(), System.Data.DataTextReader.ReadAttributeValue(), System.Runtime.Serialization.XmlReaderDelegator.ReadAttributeValue(), System.Runtime.Serialization.XmlSerializableReader.ReadAttributeValue(), System.Xml.XmlDictionaryReader.XmlWrappedReader.ReadAttributeValue(), System.Xml.XmlAsyncCheckReader.ReadAttributeValue(), System.Xml.XmlCharCheckingReader.ReadAttributeValue(), System.Xml.XmlSqlBinaryReader.ReadAttributeValue(), System.Xml.XmlSubtreeReader.ReadAttributeValue(), System.Xml.XmlValidatingReaderImpl.ReadAttributeValue(), System.Xml.XmlWrappingReader.ReadAttributeValue(), System.Xml.XsdValidatingReader.ReadAttributeValue(), System.Xml.XmlDictionaryReader.ReadContentAsString(), System.Xml.XmlWriter.WriteAttributes(), System.Xml.XmlWriter.WriteAttributesAsync(), System.Xml.XmlReader.WriteAttributeValue(), and System.Xml.XmlDictionaryWriter.WriteElementNode().