Terraria: System.Reflection.Metadata.Ecma335.CodedIndex.TypeDefOrRefOrSpec
TypeDefOrRefOrSpec()
static int System.Reflection.Metadata.Ecma335.CodedIndex.TypeDefOrRefOrSpec (EntityHandle handle) inline static
Definition at line 224 of file CodedIndex.cs.
    {
        return (handle.RowId << 2) | (int)ToTypeDefOrRefOrSpecTag(handle.Kind);
    }
References System.handle, and System.Reflection.Metadata.Ecma335.CodedIndex.ToTypeDefOrRefOrSpecTag().
Referenced by System.Reflection.Metadata.Ecma335.MetadataBuilder.AddEvent(), System.Reflection.Metadata.Ecma335.MetadataBuilder.AddGenericParameterConstraint(), System.Reflection.Metadata.Ecma335.MetadataBuilder.AddInterfaceImplementation(), System.Reflection.Metadata.Ecma335.CustomModifiersEncoder.AddModifier(), and System.Reflection.Metadata.Ecma335.MetadataBuilder.AddTypeDefinition().