Terraria: Terraria.Graphics.Light.LightingEngine.ProcessArea
ProcessArea()
void Terraria.Graphics.Light.LightingEngine.ProcessArea (Rectangle area) inline
Implements Terraria.Graphics.Light.ILightingEngine.
    {
        Main.renderCount = (Main.renderCount + 1) % 4;
        _timer.Start();
        TimeLogger.LightingTime(0, 0.0);
        switch (_state)
        {
        case EngineState.MinimapUpdate:
            if (Main.mapDelay > 0)
            {
                Main.mapDelay--;
            }
            else
            {
                ExportToMiniMap();
            }
            TimeLogger.LightingTime(1, _timer.Elapsed.TotalMilliseconds);
            break;
        case EngineState.ExportMetrics:
            area.Inflate(28, 28);
            Main.SceneMetrics.ScanAndExportToMain(new SceneMetricsScanSettings
            {
                VisualScanArea = area,
                BiomeScanCenterPositionInWorld = Main.LocalPlayer.Center,
                ScanOreFinderData = Main.LocalPlayer.accOreFinder
            });
            TimeLogger.LightingTime(2, _timer.Elapsed.TotalMilliseconds);
            break;
        case EngineState.Scan:
            ProcessScan(area);
            TimeLogger.LightingTime(3, _timer.Elapsed.TotalMilliseconds);
            break;
        case EngineState.Blur:
            ProcessBlur();
            Present();
            TimeLogger.LightingTime(4, _timer.Elapsed.TotalMilliseconds);
            break;
        }
        IncrementState();
        _timer.Reset();
    }
References Terraria.Graphics.Light.LightingEngine._state, Terraria.Graphics.Light.LightingEngine._timer, Terraria.Entity.Center, Terraria.Graphics.Light.LightingEngine.ExportToMiniMap(), Terraria.Graphics.Light.LightingEngine.IncrementState(), Terraria.TimeLogger.LightingTime(), Terraria.Main.LocalPlayer, Terraria.Main.mapDelay, Terraria.Graphics.Light.LightingEngine.Present(), Terraria.Graphics.Light.LightingEngine.ProcessBlur(), Terraria.Graphics.Light.LightingEngine.ProcessScan(), Terraria.SceneMetrics.ScanAndExportToMain(), and Terraria.Main.SceneMetrics.