Terraria: System.Threading.Tasks.Dataflow.Internal.SpscTargetCore.ProcessMessagesLoopCore
ProcessMessagesLoopCore()
void System.Threading.Tasks.Dataflow.Internal.SpscTargetCore< TInput >.ProcessMessagesLoopCore () inline private
Definition at line 158 of file SpscTargetCore.cs.
    {
        int num = 0;
        int actualMaxMessagesPerTask = _dataflowBlockOptions.ActualMaxMessagesPerTask;
        bool flag = true;
        while (flag)
        {
            flag = false;
            TInput result = default(TInput);
            try
            {
                while (_exceptions == null && num < actualMaxMessagesPerTask && _messages.TryDequeue(out result))
                {
                    num++;
                    _action(result);
                }
            }
            catch (Exception ex)
            {
                if (!Common.IsCooperativeCancellation(ex))
                {
                    _decliningPermanently = true;
                    Common.StoreDataflowMessageValueIntoExceptionData(ex, result);
                    StoreException(ex);
                }
            }
            finally
            {
                if (!_messages.IsEmpty && _exceptions == null && num < actualMaxMessagesPerTask)
                {
                    flag = true;
                }
                else
                {
                    bool decliningPermanently = _decliningPermanently;
                    if ((decliningPermanently && _messages.IsEmpty) || _exceptions != null)
                    {
                        if (!_completionReserved)
{
                            _completionReserved = true;
                            CompleteBlockOncePossible();
                        }
                    }
                    else
                    {
                        Task task = Interlocked.Exchange(ref _activeConsumer, null);
                        if (!_messages.IsEmpty || (!decliningPermanently && _decliningPermanently) || _exceptions != null)
{
                            ScheduleConsumerIfNecessary(isReplica: true);
                        }
                    }
                }
            }
        }
    }
References System.Threading.Tasks.Dataflow.Internal.SpscTargetCore< TInput >._action, System.Threading.Tasks.Dataflow.Internal.SpscTargetCore< TInput >._activeConsumer, System.Threading.Tasks.Dataflow.Internal.SpscTargetCore< TInput >._completionReserved, System.Threading.Tasks.Dataflow.Internal.SpscTargetCore< TInput >._dataflowBlockOptions, System.Threading.Tasks.Dataflow.Internal.SpscTargetCore< TInput >._decliningPermanently, System.Threading.Tasks.Dataflow.Internal.SpscTargetCore< TInput >._exceptions, System.Threading.Tasks.Dataflow.Internal.SpscTargetCore< TInput >._messages, System.Threading.Tasks.Dataflow.DataflowBlockOptions.ActualMaxMessagesPerTask, System.Threading.Tasks.Dataflow.Internal.SpscTargetCore< TInput >.CompleteBlockOncePossible(), System.Threading.Interlocked.Exchange(), System.Threading.Tasks.Dataflow.Internal.Common.IsCooperativeCancellation(), System.Threading.Tasks.Dataflow.Internal.SpscTargetCore< TInput >.ScheduleConsumerIfNecessary(), System.Threading.Tasks.Dataflow.Internal.SpscTargetCore< TInput >.StoreException(), and System.task.