Terraria: System.Threading.Tasks.Dataflow.Internal.SpscTargetCore.Post
Post()
bool System.Threading.Tasks.Dataflow.Internal.SpscTargetCore< TInput >.Post (TInput messageValue) inline package
Definition at line 82 of file SpscTargetCore.cs.
    {
        if (_decliningPermanently)
        {
            return false;
        }
        _messages.Enqueue(messageValue);
        Interlocked.MemoryBarrier();
        if (_activeConsumer == null)
        {
            ScheduleConsumerIfNecessary(isReplica: false);
        }
        return true;
    }
References System.Threading.Tasks.Dataflow.Internal.SpscTargetCore< TInput >._activeConsumer, System.Threading.Tasks.Dataflow.Internal.SpscTargetCore< TInput >._decliningPermanently, System.Threading.Tasks.Dataflow.Internal.SpscTargetCore< TInput >._messages, System.Threading.Interlocked.MemoryBarrier(), and System.Threading.Tasks.Dataflow.Internal.SpscTargetCore< TInput >.ScheduleConsumerIfNecessary().
Referenced by System.Threading.Tasks.Dataflow.Internal.SpscTargetCore< TInput >.OfferMessage().