Terraria: System.Threading.Tasks.Dataflow.Internal.SpscTargetCore.ScheduleConsumerIfNecessary
ScheduleConsumerIfNecessary()
void System.Threading.Tasks.Dataflow.Internal.SpscTargetCore< TInput >.ScheduleConsumerIfNecessary (bool isReplica) inline private
Definition at line 137 of file SpscTargetCore.cs.
    {
        if (_activeConsumer != null)
        {
            return;
        }
        Task task = new Task(delegate(object state)
        {
            ((SpscTargetCore<TInput>)state).ProcessMessagesLoopCore();
        }, this, CancellationToken.None, Common.GetCreationOptionsForTask(isReplica));
        if (Interlocked.CompareExchange(ref _activeConsumer, task, null) == null)
        {
            DataflowEtwProvider log = DataflowEtwProvider.Log;
            if (log.IsEnabled())
            {
                log.TaskLaunchedForMessageHandling(_owningTarget, task, DataflowEtwProvider.TaskLaunchedReason.ProcessingInputMessages, _messages.Count);
            }
            task.Start(_dataflowBlockOptions.TaskScheduler);
        }
    }
References System.Threading.Tasks.Dataflow.Internal.SpscTargetCore< TInput >._activeConsumer, System.Threading.Tasks.Dataflow.Internal.SpscTargetCore< TInput >._dataflowBlockOptions, System.Threading.Tasks.Dataflow.Internal.SpscTargetCore< TInput >._messages, System.Threading.Tasks.Dataflow.Internal.SpscTargetCore< TInput >._owningTarget, System.Threading.Interlocked.CompareExchange(), System.Threading.Tasks.Dataflow.Internal.Common.GetCreationOptionsForTask(), System.Threading.Tasks.Dataflow.Internal.DataflowEtwProvider.Log, System.Threading.CancellationToken.None, System.state, System.task, and System.Threading.Tasks.Dataflow.DataflowBlockOptions.TaskScheduler.
Referenced by System.Threading.Tasks.Dataflow.Internal.SpscTargetCore< TInput >.Complete(), System.Threading.Tasks.Dataflow.Internal.SpscTargetCore< TInput >.OfferMessage_Slow(), System.Threading.Tasks.Dataflow.Internal.SpscTargetCore< TInput >.Post(), and System.Threading.Tasks.Dataflow.Internal.SpscTargetCore< TInput >.ProcessMessagesLoopCore().