Terraria: System.Threading.Tasks.Dataflow.Internal.SpscTargetCore.OfferMessage_Slow
OfferMessage_Slow()
DataflowMessageStatus System.Threading.Tasks.Dataflow.Internal.SpscTargetCore< TInput >.OfferMessage_Slow (DataflowMessageHeader messageHeader, TInput messageValue, ISourceBlock< TInput > source, bool consumeToAccept) inline private
Definition at line 106 of file SpscTargetCore.cs.
    {
        if (_decliningPermanently)
        {
            return DataflowMessageStatus.DecliningPermanently;
        }
        if (!messageHeader.IsValid)
        {
            throw new ArgumentException(System.SR.Argument_InvalidMessageHeader, "messageHeader");
        }
        if (consumeToAccept)
        {
            if (source == null)
            {
                throw new ArgumentException(System.SR.Argument_CantConsumeFromANullSource, "consumeToAccept");
            }
            messageValue = source.ConsumeMessage(messageHeader, _owningTarget, out var messageConsumed);
            if (!messageConsumed)
            {
                return DataflowMessageStatus.NotAvailable;
            }
        }
        _messages.Enqueue(messageValue);
        Interlocked.MemoryBarrier();
        if (_activeConsumer == null)
        {
            ScheduleConsumerIfNecessary(isReplica: false);
        }
        return DataflowMessageStatus.Accepted;
    }
References System.Threading.Tasks.Dataflow.Internal.SpscTargetCore< TInput >._activeConsumer, System.Threading.Tasks.Dataflow.Internal.SpscTargetCore< TInput >._decliningPermanently, System.Threading.Tasks.Dataflow.Internal.SpscTargetCore< TInput >._messages, System.Threading.Tasks.Dataflow.Internal.SpscTargetCore< TInput >._owningTarget, System.SR.Argument_CantConsumeFromANullSource, System.SR.Argument_InvalidMessageHeader, System.Threading.Interlocked.MemoryBarrier(), System.Threading.Tasks.Dataflow.Internal.SpscTargetCore< TInput >.ScheduleConsumerIfNecessary(), and System.source.
Referenced by System.Threading.Tasks.Dataflow.Internal.SpscTargetCore< TInput >.OfferMessage().