Terraria: System.Threading._IOCompletionCallback.PerformIOCompletionCallback
PerformIOCompletionCallback()
static unsafe void System.Threading._IOCompletionCallback.PerformIOCompletionCallback (uint errorCode, uint numBytes, NativeOverlapped * pNativeOverlapped) inline static package
Definition at line 29 of file _IOCompletionCallback.cs.
    {
        do
        {
            OverlappedData overlappedFromNative = OverlappedData.GetOverlappedFromNative(pNativeOverlapped);
            if (overlappedFromNative._callback is IOCompletionCallback iOCompletionCallback)
            {
                iOCompletionCallback(errorCode, numBytes, pNativeOverlapped);
            }
            else
            {
                _IOCompletionCallback iOCompletionCallback2 = (_IOCompletionCallback)overlappedFromNative._callback;
                iOCompletionCallback2._errorCode = errorCode;
                iOCompletionCallback2._numBytes = numBytes;
                iOCompletionCallback2._pNativeOverlapped = pNativeOverlapped;
                ExecutionContext.RunInternal(iOCompletionCallback2._executionContext, _ccb, iOCompletionCallback2);
            }
            OverlappedData.CheckVMForIOPacket(out pNativeOverlapped, out errorCode, out numBytes);
        }
        while (pNativeOverlapped != null);
    }
References System.Threading._IOCompletionCallback._IOCompletionCallback(), System.Threading.OverlappedData._callback, System.Threading._IOCompletionCallback._ccb, System.Threading._IOCompletionCallback._executionContext, System.Threading.OverlappedData.CheckVMForIOPacket(), System.Threading.OverlappedData.GetOverlappedFromNative(), System.Threading.IOCompletionCallback(), and System.Threading.ExecutionContext.RunInternal().