Terraria: System.Net.NetworkInformation.SystemIPGlobalProperties.GetUnicastAddressesAsync
GetUnicastAddressesAsync()
override async Task< UnicastIPAddressInformationCollection > System.Net.NetworkInformation.SystemIPGlobalProperties.GetUnicastAddressesAsync () inline virtual
Reimplemented from System.Net.NetworkInformation.IPGlobalProperties.
Definition at line 305 of file SystemIPGlobalProperties.cs.
    {
        TaskCompletionSource<bool> taskCompletionSource = new TaskCompletionSource<bool>(TaskCreationOptions.RunContinuationsAsynchronously);
        if (!TeredoHelper.UnsafeNotifyStableUnicastIpAddressTable(delegate(object s)
        {
            ((TaskCompletionSource<bool>)s).TrySetResult(result: true);
        }, taskCompletionSource))
        {
            await taskCompletionSource.Task.ConfigureAwait(continueOnCapturedContext: false);
        }
        UnicastIPAddressInformationCollection unicastIPAddressInformationCollection = new UnicastIPAddressInformationCollection();
        NetworkInterface[] allNetworkInterfaces = NetworkInterface.GetAllNetworkInterfaces();
        foreach (NetworkInterface networkInterface in allNetworkInterfaces)
        {
            foreach (UnicastIPAddressInformation unicastAddress in networkInterface.GetIPProperties().UnicastAddresses)
            {
                if (!unicastIPAddressInformationCollection.Contains(unicastAddress))
                {
                    unicastIPAddressInformationCollection.InternalAdd(unicastAddress);
                }
            }
        }
        return unicastIPAddressInformationCollection;
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Contains(), System.Net.NetworkInformation.NetworkInterface.GetAllNetworkInterfaces(), System.s, and System.Net.NetworkInformation.TeredoHelper.UnsafeNotifyStableUnicastIpAddressTable().
Referenced by System.Net.NetworkInformation.SystemIPGlobalProperties.BeginGetUnicastAddresses(), and System.Net.NetworkInformation.SystemIPGlobalProperties.GetUnicastAddresses().