Terraria: System.Net.NetworkInformation.SystemIPGlobalProperties.GetAllTcpConnections
GetAllTcpConnections()
unsafe List< SystemTcpConnectionInformation > System.Net.NetworkInformation.SystemIPGlobalProperties.GetAllTcpConnections () inline private
Definition at line 52 of file SystemIPGlobalProperties.cs.
    {
        uint dwOutBufLen = 0u;
        uint num = 0u;
        List<SystemTcpConnectionInformation> list = new List<SystemTcpConnectionInformation>();
        if (Socket.OSSupportsIPv4)
        {
            num = global::Interop.IpHlpApi.GetTcpTable(IntPtr.Zero, ref dwOutBufLen, order: true);
            while (true)
            {
                switch (num)
                {
                case 122u:
                {
                    IntPtr intPtr = Marshal.AllocHGlobal((int)dwOutBufLen);
                    try
                    {
                        num = global::Interop.IpHlpApi.GetTcpTable(intPtr, ref dwOutBufLen, order: true);
                        if (num != 0)
{
                            continue;
                        }
                        ReadOnlySpan<byte> span = new ReadOnlySpan<byte>((void*)intPtr, (int)dwOutBufLen);
                        ref readonly global::Interop.IpHlpApi.MibTcpTable reference = ref MemoryMarshal.AsRef<global::Interop.IpHlpApi.MibTcpTable>(span);
                        if (reference.numberOfEntries != 0)
{
                            span = span.Slice(sizeof(global::Interop.IpHlpApi.MibTcpTable));
                            for (int i = 0; i < reference.numberOfEntries; i++)
{
                                list.Add(new SystemTcpConnectionInformation(in MemoryMarshal.AsRef<global::Interop.IpHlpApi.MibTcpRow>(span)));
                                span = span.Slice(sizeof(global::Interop.IpHlpApi.MibTcpRow));
                            }
                        }
                    }
                    finally
                    {
                        Marshal.FreeHGlobal(intPtr);
                    }
                    continue;
                }
                default:
                    throw new NetworkInformationException((int)num);
                case 0u:
                case 232u:
                    break;
                }
                break;
            }
        }
        if (Socket.OSSupportsIPv6)
        {
            dwOutBufLen = 0u;
            num = global::Interop.IpHlpApi.GetExtendedTcpTable(IntPtr.Zero, ref dwOutBufLen, order: true, 23u, global::Interop.IpHlpApi.TcpTableClass.TcpTableOwnerPidAll, 0u);
            while (true)
            {
                switch (num)
                {
                case 122u:
                {
                    IntPtr intPtr2 = Marshal.AllocHGlobal((int)dwOutBufLen);
                    try
                    {
                        num = global::Interop.IpHlpApi.GetExtendedTcpTable(intPtr2, ref dwOutBufLen, order: true, 23u, global::Interop.IpHlpApi.TcpTableClass.TcpTableOwnerPidAll, 0u);
                        if (num != 0)
{
                            continue;
                        }
                        ReadOnlySpan<byte> span2 = new ReadOnlySpan<byte>((void*)intPtr2, (int)dwOutBufLen);
                        ref readonly global::Interop.IpHlpApi.MibTcp6TableOwnerPid reference2 = ref MemoryMarshal.AsRef<global::Interop.IpHlpApi.MibTcp6TableOwnerPid>(span2);
                        if (reference2.numberOfEntries != 0)
{
                            span2 = span2.Slice(sizeof(global::Interop.IpHlpApi.MibTcp6TableOwnerPid));
                            for (int j = 0; j < reference2.numberOfEntries; j++)
{
                                list.Add(new SystemTcpConnectionInformation(in MemoryMarshal.AsRef<global::Interop.IpHlpApi.MibTcp6RowOwnerPid>(span2)));
                                span2 = span2.Slice(sizeof(global::Interop.IpHlpApi.MibTcp6RowOwnerPid));
                            }
                        }
                    }
                    finally
                    {
                        Marshal.FreeHGlobal(intPtr2);
                    }
                    continue;
                }
                default:
                    throw new NetworkInformationException((int)num);
                case 0u:
                case 232u:
                    break;
                }
                break;
            }
        }
        return list;
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Runtime.InteropServices.Marshal.AllocHGlobal(), System.Runtime.InteropServices.Marshal.FreeHGlobal(), System.list, System.Net.Sockets.Socket.OSSupportsIPv4, System.Net.Sockets.Socket.OSSupportsIPv6, and System.IntPtr.Zero.
Referenced by System.Net.NetworkInformation.SystemIPGlobalProperties.GetActiveTcpConnections(), and System.Net.NetworkInformation.SystemIPGlobalProperties.GetActiveTcpListeners().