Terraria: PartyChatCommand.ProcessIncomingMessage
ProcessIncomingMessage()
void PartyChatCommand.ProcessIncomingMessage (string text, byte clientId) inline
Implements IChatCommand.
     {
         int team = Main.player[clientId].team;
         Color color = Main.teamColor[team];
         if (team == 0)
         {
             SendNoTeamError(clientId);
         }
         else
         {
             if (text == "")
             {
                 return;
             }
             for (int i = 0; i < 255; i++)
             {
                 if (Main.player[i].team == team)
                 {
                     ChatHelper.SendChatMessageToClientAs(clientId, NetworkText.FromLiteral(text), color, i);
                 }
             }
         }
     }
References Color, NetworkText.FromLiteral(), Main.player, ChatHelper.SendChatMessageToClientAs(), SendNoTeamError(), Player.team, and Main.teamColor.