Terraria: System.Reflection.MemberInfo.GetCustomAttributes
GetCustomAttributes() [1/2]
object[] System.Reflection.MemberInfo.GetCustomAttributes (bool inherit) abstract inherited
Implements System.Reflection.ICustomAttributeProvider.
Referenced by System.Diagnostics.SwitchAttribute.GetAllRecursive(), System.Reflection.Emit.ConstructorOnTypeBuilderInstantiation.GetCustomAttributes(), System.Reflection.Emit.FieldOnTypeBuilderInstantiation.GetCustomAttributes(), System.Reflection.Emit.MethodBuilderInstantiation.GetCustomAttributes(), System.Reflection.Emit.MethodOnTypeBuilderInstantiation.GetCustomAttributes(), System.Reflection.TypeDelegator.GetCustomAttributes(), System.Runtime.InteropServices.ComAwareEventInfo.GetCustomAttributes(), System.Runtime.Serialization.SerializationFieldInfo.GetCustomAttributes(), System.Attribute.GetCustomAttributes(), System.Attribute.GetCustomAttributes(), System.Reflection.Emit.ConstructorOnTypeBuilderInstantiation.GetCustomAttributes(), System.Reflection.Emit.FieldOnTypeBuilderInstantiation.GetCustomAttributes(), System.Reflection.Emit.MethodBuilderInstantiation.GetCustomAttributes(), System.Reflection.Emit.MethodOnTypeBuilderInstantiation.GetCustomAttributes(), System.Reflection.TypeDelegator.GetCustomAttributes(), System.Runtime.InteropServices.ComAwareEventInfo.GetCustomAttributes(), System.Runtime.Serialization.SerializationFieldInfo.GetCustomAttributes(), System.Attribute.InternalGetCustomAttributes(), System.Attribute.InternalGetCustomAttributes(), and System.ComponentModel.ReflectTypeDescriptionProvider.ReflectGetAttributes().