Terraria: System.Reflection.MemberInfo.IsDefined
IsDefined()
bool System.Reflection.MemberInfo.IsDefined (Type attributeType, bool inherit) abstract inherited
Implements System.Reflection.ICustomAttributeProvider.
Referenced by System.ComponentModel.EnumConverter.ConvertTo(), System.ComponentModel.EnumConverter.GetStandardValuesExclusive(), System.Attribute.InternalIsDefined(), System.Attribute.InternalIsDefined(), System.Diagnostics.Tracing.EventSource.IsCustomAttributeDefinedHelper(), System.Attribute.IsDefined(), System.Reflection.Emit.ConstructorOnTypeBuilderInstantiation.IsDefined(), System.Reflection.Emit.FieldOnTypeBuilderInstantiation.IsDefined(), System.Reflection.Emit.MethodBuilderInstantiation.IsDefined(), System.Reflection.Emit.MethodOnTypeBuilderInstantiation.IsDefined(), System.Reflection.TypeDelegator.IsDefined(), System.Runtime.InteropServices.ComAwareEventInfo.IsDefined(), System.Runtime.Serialization.SerializationFieldInfo.IsDefined(), and System.ComponentModel.DataAnnotations.EnumDataTypeAttribute.IsEnumTypeInFlagsMode().