Terraria: UIGenProgressBar.DrawSelf
DrawSelf()
override void UIGenProgressBar.DrawSelf (SpriteBatch spriteBatch) inline protected virtual
Reimplemented from UIElement.
     {
         if (_texOuterCorrupt.IsLoaded && _texOuterCrimson.IsLoaded && _texOuterLower.IsLoaded)
         {
             bool flag = WorldGen.crimson;
             if (WorldGen.drunkWorldGen && Main.rand.Next(2) == 0)
             {
                 flag = !flag;
             }
             _visualOverallProgress = _targetOverallProgress;
             _visualCurrentProgress = _targetCurrentProgress;
             CalculatedStyle dimensions = GetDimensions();
             int completedWidth = (int)(_visualOverallProgress * (float)_longBarWidth);
             int completedWidth2 = (int)(_visualCurrentProgress * (float)_smallBarWidth);
             Vector2 vector = new Vector2(dimensions.X, dimensions.Y);
             Color color = default(Color);
             color.PackedValue = (flag ? 4286836223u : 4283888223u);
             DrawFilling2(spriteBatch, vector + new Vector2(20f, 40f), 16, completedWidth, _longBarWidth, color, Color.Lerp(color, Color.Black, 0.5f), new Color(48, 48, 48));
             color.PackedValue = 4290947159u;
             DrawFilling2(spriteBatch, vector + new Vector2(50f, 60f), 8, completedWidth2, _smallBarWidth, color, Color.Lerp(color, Color.Black, 0.5f), new Color(33, 33, 33));
             Rectangle r = GetDimensions().ToRectangle();
             r.X -= 8;
             spriteBatch.Draw(flag ? _texOuterCrimson.Value : _texOuterCorrupt.Value, r.TopLeft(), Color.White);
             spriteBatch.Draw(_texOuterLower.Value, r.TopLeft() + new Vector2(44f, 60f), Color.White);
         }
     }
References _longBarWidth, _smallBarWidth, _targetCurrentProgress, _targetOverallProgress, _texOuterCorrupt, _texOuterCrimson, _texOuterLower, _visualCurrentProgress, _visualOverallProgress, Color, WorldGen.crimson, DrawFilling2(), WorldGen.drunkWorldGen, UIElement.GetDimensions(), Asset< T >.IsLoaded, UnifiedRandom.Next(), Main.rand, CalculatedStyle.ToRectangle(), Asset< T >.Value, CalculatedStyle.X, and CalculatedStyle.Y.