Terraria: Preferences.Save
Save()
bool Preferences.Save (bool canCreateFile = true) inline
     {
         //IL_00c5: Unknown result type (might be due to invalid IL or missing references)
         //IL_00cc: Expected O, but got Unknown
         lock (_lock)
         {
             try
             {
                 if (this.OnSave != null)
                 {
                     this.OnSave(this);
                 }
                 if (!canCreateFile && !File.Exists(_path))
                 {
                     return false;
                 }
                 Directory.GetParent(_path).Create();
                 if (File.Exists(_path))
                 {
                     File.SetAttributes(_path, FileAttributes.Normal);
                 }
                 if (!UseBson)
                 {
                     string text = JsonConvert.SerializeObject((object)_data, _serializerSettings);
                     if (this.OnProcessText != null)
                     {
                         this.OnProcessText(ref text);
                     }
                     File.WriteAllText(_path, text);
                     File.SetAttributes(_path, FileAttributes.Normal);
                 }
                 else
                 {
                     using FileStream fileStream = File.Create(_path);
                     BsonWriter val = new BsonWriter((Stream)fileStream);
                     try
                     {
                         File.SetAttributes(_path, FileAttributes.Normal);
                         JsonSerializer.Create(_serializerSettings).Serialize((JsonWriter)(object)val, (object)_data);
                     }
                     finally
                     {
                         ((IDisposable)val)?.Dispose();
                     }
                 }
             }
             catch (Exception ex)
             {
                 Console.WriteLine(Language.GetTextValue("Error.UnableToWritePreferences", _path));
                 Console.WriteLine(ex.ToString());
                 return false;
             }
             return true;
         }
     }
References _data, _lock, _path, _serializerSettings, Language.GetTextValue(), OnProcessText, OnSave, and UseBson.
Referenced by Put(), PlayerInput.Save(), Main.SaveSettings(), and Main.TryPickingDefaultUIScale().