Terraria: System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperError
ThrowHelperError()
static Exception System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperError (Exception e) inline static
Definition at line 15 of file DiagnosticUtility.cs.
        {
            return e;
        }
Referenced by System.Runtime.Serialization.ClassDataContract.ClassDataContractCriticalHelper.ClassDataContractCriticalHelper(), System.Runtime.Serialization.CollectionDataContract.CollectionDataContractCriticalHelper.CollectionDataContractCriticalHelper(), System.Runtime.Serialization.CollectionDataContract.CollectionDataContractCriticalHelper.CollectionDataContractCriticalHelper(), System.Runtime.Serialization.CollectionDataContract.CollectionDataContractCriticalHelper.CollectionDataContractCriticalHelper(), System.Runtime.Serialization.DataContractSet.DataContractSet(), System.Text.SurrogateChar.SurrogateChar(), System.Text.SurrogateChar.SurrogateChar(), System.Xml.UniqueId.UniqueId(), System.Xml.UniqueId.UniqueId(), System.Xml.UniqueId.UniqueId(), System.Runtime.Serialization.XmlDataContract.XmlDataContractCriticalHelper.XmlDataContractCriticalHelper(), System.Xml.XmlDictionaryString.XmlDictionaryString(), System.Xml.XmlBinaryReaderSession.Add(), System.Runtime.Serialization.HybridObjectCache.Add(), System.Runtime.Serialization.XsdDataContractExporter.AddKnownTypes(), System.Xml.XmlBaseWriter.NamespaceManager.AddNamespace(), System.Runtime.Serialization.XmlSerializableReader.BeginRead(), System.Runtime.Serialization.XsdDataContractExporter.CanExport(), System.Runtime.Serialization.XsdDataContractExporter.CanExport(), System.Runtime.Serialization.XsdDataContractExporter.CanExport(), System.Runtime.Serialization.XmlReaderDelegator.CheckActualArrayLength(), System.Runtime.Serialization.DataContract.CheckAndAdd(), System.Xml.XmlBinaryReader.CheckArray(), System.Xml.XmlBinaryWriter.CheckArray(), System.Xml.XmlDictionaryReader.CheckArray(), System.Xml.XmlDictionaryWriter.CheckArray(), System.Runtime.Serialization.CollectionDataContract.CheckConstructor(), System.Runtime.Serialization.XmlObjectSerializerReadContext.CheckEndOfArray(), System.Runtime.Serialization.Json.DataContractJsonSerializer.CheckIfTypeIsReference(), System.Runtime.Serialization.XmlObjectSerializerContext.CheckIfTypeSerializable(), System.Runtime.Serialization.XmlObjectSerializerReadContextComplex.CheckIfTypeSerializable(), System.Runtime.Serialization.XmlObjectSerializerWriteContextComplex.CheckIfTypeSerializable(), System.Runtime.Serialization.XmlObjectSerializer.CheckNull(), System.Runtime.Serialization.XmlSerializableReader.Close(), System.Runtime.Serialization.XmlSerializableWriter.Close(), System.Xml.XmlDictionaryReaderQuotas.CopyTo(), System.Runtime.Serialization.XPathQueryGenerator.CreateFromDataContractSerializer(), System.Runtime.Serialization.FastInvokerBuilder.CreateGetter(), System.Runtime.Serialization.FastInvokerBuilder.CreateSetter(), System.Runtime.Serialization.Json.XmlJsonReader.CreateSigningNodeWriter(), System.Xml.XmlBaseReader.EndCanonicalization(), System.Xml.XmlBaseWriter.EndCanonicalization(), System.Xml.XmlDictionaryReader.EndCanonicalization(), System.Xml.XmlDictionaryWriter.EndCanonicalization(), System.Runtime.Serialization.XmlSerializableReader.EndRead(), System.Runtime.Serialization.XmlSerializableWriter.EndWrite(), System.Runtime.Serialization.XmlObjectSerializerReadContext.EnsureArraySize< T >(), System.Runtime.Serialization.DataContractSet.EnsureTypeNotGeneric(), System.Runtime.Serialization.DataContract.ExpandGenericParameters(), System.Runtime.Serialization.XsdDataContractExporter.Export(), System.Runtime.Serialization.XsdDataContractExporter.Export(), System.Runtime.Serialization.XsdDataContractExporter.Export(), System.Runtime.Serialization.SchemaExporter.ExportSerializationSchema(), System.Runtime.Serialization.SchemaExporter.ExportXmlDataContract(), System.Runtime.Serialization.ObjectToIdCache.FindElement(), System.Xml.XmlNodeWriter.FlushAsync(), System.Xml.XmlBaseWriter.GeneratePrefix(), System.Runtime.Serialization.XmlReaderDelegator.GetAttribute(), System.Xml.XmlBaseReader.GetAttributeNode(), System.Xml.XmlBaseReader.GetAttributeNode(), System.Xml.XmlBaseReader.GetAttributeNode(), System.Xml.XmlBaseReader.GetAttributeNode(), System.Text.Base64Encoding.GetByteCount(), System.Text.Base64Encoding.GetBytes(), System.Text.Base64Encoding.GetBytes(), System.Text.Base64Encoding.GetChars(), System.Text.Base64Encoding.GetChars(), System.Runtime.Serialization.ReflectionReader.GetCollectionSetItemDelegate< T >(), System.Runtime.Serialization.DataContract.GetCollectionStableName(), System.Runtime.Serialization.XmlDataContract.GetConstructor(), System.Runtime.Serialization.DataContract.DataContractCriticalHelper.GetDataContractForInitialization(), System.Runtime.Serialization.XmlObjectSerializerContext.GetDataContractsForKnownTypes(), System.Runtime.Serialization.DateTimeOffsetAdapter.GetDateTimeOffset(), System.Runtime.Serialization.DataContract.GetDCTypeStableName(), System.Runtime.Serialization.XmlObjectSerializerReadContext.GetExistingObject(), System.Runtime.Serialization.XmlObjectSerializerReadContext.GetExistingObjectOrExtensionData(), System.Runtime.Serialization.DataContract.GetGetOnlyCollectionDataContract(), System.Runtime.Serialization.DataContract.GetGlobalDataContractNamespace(), System.Runtime.Serialization.DataContract.DataContractCriticalHelper.GetId(), System.Runtime.Serialization.DataContract.DataContractCriticalHelper.GetIdForInitialization(), System.Runtime.Serialization.ClassDataContract.ClassDataContractCriticalHelper.GetISerializableConstructor(), System.Text.Base64Encoding.GetMaxByteCount(), System.Text.Base64Encoding.GetMaxCharCount(), System.Runtime.Serialization.ClassDataContract.ClassDataContractCriticalHelper.GetNonAttributedTypeConstructor(), System.Xml.XmlBaseWriter.GetQualifiedNamePrefix(), System.Runtime.Serialization.XmlObjectSerializerReadContext.GetRealObject(), System.Runtime.Serialization.XsdDataContractExporter.GetRootElementName(), System.Runtime.Serialization.XsdDataContractExporter.GetSchemaType(), System.Runtime.Serialization.XsdDataContractExporter.GetSchemaTypeName(), System.Xml.ValueHandle.GetString(), System.Runtime.Serialization.XmlObjectSerializerReadContextComplex.GetSurrogatedType(), System.Runtime.Serialization.XmlObjectSerializerWriteContextComplex.GetSurrogatedType(), System.Runtime.Serialization.CollectionDataContract.GetValidContract(), System.Runtime.Serialization.SchemaExporter.GetXmlTypeInfo(), System.Runtime.Serialization.CollectionDataContract.HandleIfInvalidCollection(), System.Runtime.Serialization.XmlObjectSerializerReadContext.HandleMemberNotFound(), System.Runtime.Serialization.XmlObjectSerializerContext.IncrementItemCount(), System.Runtime.Serialization.CollectionDataContract.CollectionDataContractCriticalHelper.Init(), System.Runtime.Serialization.DataContractSerializer.Initialize(), System.Runtime.Serialization.DataContractSet.InternalAdd(), System.Runtime.Serialization.CodeGenerator.InternalConvert(), System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(), System.Runtime.Serialization.XmlObjectSerializerReadContextComplex.InternalDeserializeWithSurrogate(), System.Runtime.Serialization.XmlObjectSerializer.InternalIsStartObject(), System.Runtime.Serialization.DataContractSerializer.InternalReadObject(), System.Runtime.Serialization.XmlObjectSerializer.InternalWriteEndObject(), System.Runtime.Serialization.XmlObjectSerializer.InternalWriteObjectContent(), System.Runtime.Serialization.DataContractSerializer.InternalWriteObjectContent(), System.Runtime.Serialization.XmlObjectSerializer.InternalWriteStartObject(), System.Runtime.Serialization.SchemaExporter.InvokeGetSchemaMethod(), System.Runtime.Serialization.SchemaExporter.InvokeSchemaProviderMethod(), System.Xml.XmlBaseReader.IsLocalName(), System.Xml.XmlBaseReader.IsLocalName(), System.Runtime.Serialization.XmlObjectSerializer.IsStartObjectHandleExceptions(), System.Runtime.Serialization.CodeGenerator.Ldc(), System.Runtime.Serialization.CodeGenerator.Ldelem(), System.Runtime.Serialization.CodeGenerator.LoadMember(), System.Xml.XmlBaseWriter.LookupPrefix(), System.Runtime.Serialization.XmlReaderDelegator.MoveToAttribute(), System.Runtime.Serialization.XmlObjectSerializerWriteContext.OnHandleReference(), System.Xml.XmlBaseWriter.PreStartElementAsyncCheck(), System.Runtime.Serialization.XPathQueryGenerator.ProcessClassDataContract(), System.Runtime.Serialization.XPathQueryGenerator.ProcessDataContract(), System.Runtime.Serialization.XmlObjectSerializerReadContext.Read(), System.Runtime.Serialization.XmlObjectSerializerReadContext.ReadAndResolveUnknownXmlData(), System.Runtime.Serialization.Attributes.ReadArraySize(), System.Xml.XmlBaseReader.ReadBytes(), System.Runtime.Serialization.XmlReaderDelegator.ReadContentAsAnyType(), System.Xml.XmlBaseReader.ReadContentAsBase64(), System.Runtime.Serialization.XmlReaderDelegator.ReadContentAsBase64(), System.Xml.XmlBaseReader.ReadContentAsBinHex(), System.Xml.XmlDictionaryReader.XmlWrappedReader.ReadContentAsBoolean(), System.Xml.XmlDictionaryReader.XmlWrappedReader.ReadContentAsDecimal(), System.Xml.XmlDictionaryReader.XmlWrappedReader.ReadContentAsDouble(), System.Xml.XmlDictionaryReader.XmlWrappedReader.ReadContentAsFloat(), System.Runtime.Serialization.XmlReaderDelegator.ReadContentAsGuid(), System.Xml.XmlDictionaryReader.XmlWrappedReader.ReadContentAsInt(), System.Xml.XmlDictionaryReader.XmlWrappedReader.ReadContentAsLong(), System.Xml.XmlDictionaryReader.XmlWrappedReader.ReadContentAsString(), System.Runtime.Serialization.XmlReaderDelegator.ReadContentAsUri(), System.Xml.XmlBufferReader.ReadDateTime(), System.Xml.XmlDictionaryReader.ReadElementContentAsDateTime(), System.Runtime.Serialization.XmlReaderDelegator.ReadElementContentAsGuid(), System.Xml.XmlDictionaryReader.ReadElementContentAsGuid(), System.Xml.XmlDictionaryReader.ReadElementContentAsUniqueId(), System.Runtime.Serialization.XmlReaderDelegator.ReadElementContentAsUri(), System.Xml.XmlBaseReader.ReadEndElement(), System.Runtime.Serialization.EnumDataContract.ReadEnumValue(), System.Runtime.Serialization.EnumDataContract.ReadEnumValue(), System.Runtime.Serialization.XmlReaderDelegator.ReadExtensionData(), System.Runtime.Serialization.XmlObjectSerializerReadContext.ReadExtensionDataValue(), System.Runtime.Serialization.Attributes.ReadId(), System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.ReadISerializable(), System.Runtime.Serialization.XmlObjectSerializerReadContext.ReadIXmlSerializable(), System.Runtime.Serialization.XmlSerializableServices.ReadNodes(), System.Runtime.Serialization.XmlObjectSerializer.ReadObjectHandleExceptions(), System.Runtime.Serialization.Json.XmlObjectSerializerReadContextComplexJson.ReadPrimitiveExtensionDataValue(), System.Runtime.Serialization.Attributes.ReadRef(), System.Runtime.Serialization.XmlObjectSerializerReadContext.ReadSerializationInfo(), System.Runtime.Serialization.Json.ReflectionJsonReader.ReadSimpleDictionary(), System.Xml.XmlDictionaryReader.ReadString(), System.Xml.XmlBufferReader.ReadTimeSpan(), System.Runtime.Serialization.XmlObjectSerializerReadContext.ReadUnknownClassData(), System.Runtime.Serialization.XmlObjectSerializerReadContext.ReadUnknownCollectionData(), System.Runtime.Serialization.XmlObjectSerializerReadContext.ReadUnknownISerializableData(), System.Runtime.Serialization.XmlObjectSerializerReadContext.ReadUnknownXmlData(), System.Xml.XmlBaseReader.ReadValueAsBase64(), System.Xml.XmlDictionaryReader.ReadValueAsBase64(), System.Xml.XmlBaseReader.ReadValueChunk(), System.Runtime.Serialization.DataContract.ReadXmlElement(), System.Runtime.Serialization.ObjectDataContract.ReadXmlValue(), System.Runtime.Serialization.ClassDataContract.ReadXmlValue(), System.Runtime.Serialization.DataContract.ReadXmlValue(), System.Runtime.Serialization.ObjectToIdCache.RemoveAt(), System.Runtime.Serialization.XmlObjectSerializerReadContext.ReplaceDeserializedObject(), System.Runtime.Serialization.XmlDataContract.RequiresMemberAccessForCreate(), System.Runtime.Serialization.ClassDataContract.RequiresMemberAccessForRead(), System.Runtime.Serialization.CollectionDataContract.RequiresMemberAccessForRead(), System.Runtime.Serialization.ClassDataContract.RequiresMemberAccessForWrite(), System.Runtime.Serialization.CollectionDataContract.RequiresMemberAccessForWrite(), System.Xml.XmlBaseReader.ResolveEntity(), System.Runtime.Serialization.XmlObjectSerializerWriteContext.ResolveType(), System.Runtime.Serialization.XmlObjectSerializerWriteContext.SerializeAndVerifyType(), System.Xml.XmlUTF8TextReader.SetInput(), System.Xml.XmlBinaryReader.SetInput(), System.Xml.XmlBinaryWriter.SetOutput(), System.Xml.XmlBaseReader.SignNode(), System.Xml.XmlBaseWriter.StartArray(), System.Xml.XmlBaseWriter.StartAttribute(), System.Xml.XmlBaseReader.StartCanonicalization(), System.Xml.XmlBaseWriter.StartCanonicalization(), System.Xml.XmlDictionaryReader.StartCanonicalization(), System.Xml.XmlDictionaryWriter.StartCanonicalization(), System.Xml.XmlBaseWriter.StartContent(), System.Xml.XmlBaseWriter.StartContentAsync(), System.Xml.XmlBaseWriter.StartElement(), System.Xml.XmlBaseWriter.StartElementAsync(), System.Runtime.Serialization.CodeGenerator.Stelem(), System.Runtime.Serialization.CodeGenerator.Store(), System.Runtime.Serialization.CodeGenerator.StoreMember(), System.Runtime.Serialization.XmlObjectSerializerReadContext.ThrowArrayExceededSizeException(), System.Xml.XmlBaseWriter.ThrowClosed(), System.Xml.XmlCanonicalWriter.ThrowClosed(), System.Runtime.Serialization.XmlReaderDelegator.ThrowConversionException(), System.Runtime.Serialization.Json.XmlObjectSerializerReadContextComplexJson.ThrowDuplicateMemberException(), System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperCallback(), System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperFatal(), System.Runtime.Serialization.DataContract.DataContractCriticalHelper.ThrowInvalidDataContractException(), System.Runtime.Serialization.CodeGenerator.ThrowMismatchException(), System.Runtime.Serialization.Json.XmlObjectSerializerReadContextComplexJson.ThrowMissingRequiredMembers(), System.Runtime.Serialization.XmlReaderDelegator.ThrowNotAtElement(), System.Runtime.Serialization.XmlObjectSerializerReadContext.ThrowNullValueReturnedForGetOnlyCollectionException(), System.Runtime.Serialization.XmlObjectSerializerReadContext.ThrowRequiredMemberMissingException(), System.Runtime.Serialization.XmlObjectSerializerWriteContext.ThrowRequiredMemberMustBeEmitted(), System.Xml.XmlExceptionHelper.ThrowXmlException(), System.Xml.XmlExceptionHelper.ThrowXmlException(), System.Xml.XmlConverter.ToBoolean(), System.Xml.ValueHandle.ToByteArray(), System.Xml.XmlConverter.ToBytes(), System.Xml.UniqueId.ToCharArray(), System.Xml.XmlConverter.ToChars(), System.Xml.XmlConverter.ToChars(), System.Xml.XmlConverter.ToDateTime(), System.Xml.XmlConverter.ToDateTime(), System.Xml.XmlConverter.ToDecimal(), System.Xml.XmlConverter.ToDouble(), System.Xml.XmlConverter.ToGuid(), System.Xml.XmlConverter.ToInt32(), System.Xml.XmlConverter.ToInt64(), System.Xml.ValueHandle.ToObject(), System.Xml.XmlConverter.ToQualifiedName(), System.Xml.XmlConverter.ToSingle(), System.Xml.XmlConverter.ToString(), System.Xml.XmlConverter.ToStringUnicode(), System.Xml.XmlConverter.ToTimeSpan(), System.Xml.ValueHandle.ToType(), System.Xml.XmlConverter.ToUInt64(), System.Xml.XmlConverter.ToUniqueId(), System.Xml.XmlBinaryWriterSession.TryAdd(), System.Xml.UniqueId.TryGetGuid(), System.Runtime.Serialization.XmlObjectSerializerReadContext.TryHandleNullOrRef(), System.Xml.XmlDictionaryString.EmptyStringDictionary.TryLookup(), System.Xml.XmlBinaryReaderSession.TryLookup(), System.Xml.XmlDictionary.TryLookup(), System.Xml.ValueHandle.TryReadChars(), System.Runtime.Serialization.PrimitiveDataContract.TryReadNullAtTopLevel(), System.Runtime.Serialization.DataContract.ValidatePreviousCollectionTypes(), System.Runtime.Serialization.Json.XmlObjectSerializerWriteContextComplexJson.VerifyObjectCompatibilityWithInterface(), System.Runtime.Serialization.CodeGenerator.VerifyParameterCount(), System.Xml.XmlBaseWriter.VerifyWhitespace(), System.Xml.XmlBaseWriter.VerifyWhitespace(), System.Xml.XmlBaseWriter.VerifyWhitespace(), System.Runtime.Serialization.XmlWriterDelegator.WriteAnyType(), System.Xml.XmlBaseWriter.WriteBase64(), System.Xml.XmlBaseWriter.WriteBase64Async(), System.Xml.XmlNodeWriter.WriteBase64TextAsync(), System.Xml.XmlBaseWriter.WriteCData(), System.Xml.XmlBaseWriter.WriteCharEntity(), System.Xml.XmlBaseWriter.WriteChars(), System.Xml.XmlBaseWriter.WriteComment(), System.Xml.XmlBaseWriter.WriteDocType(), System.Xml.XmlBaseWriter.WriteEndAttribute(), System.Xml.XmlBaseWriter.WriteEndAttributeAsync(), System.Xml.XmlNodeWriter.WriteEndAttributeAsync(), System.Xml.XmlBaseWriter.WriteEndAttributeAsyncImpl(), System.Xml.XmlBaseWriter.WriteEndDocument(), System.Runtime.Serialization.XmlSerializableWriter.WriteEndElement(), System.Xml.XmlBaseWriter.WriteEndElement(), System.Xml.XmlBaseWriter.WriteEndElementAsync(), System.Xml.XmlNodeWriter.WriteEndElementAsync(), System.Runtime.Serialization.XmlObjectSerializer.WriteEndObjectHandleExceptions(), System.Xml.XmlNodeWriter.WriteEndStartElementAsync(), System.Xml.XmlBaseWriter.WriteEntityRef(), System.Runtime.Serialization.EnumDataContract.WriteEnumValue(), System.Xml.XmlCanonicalWriter.WriteEscapedText(), System.Runtime.Serialization.XmlWriterDelegator.WriteExtensionData(), System.Runtime.Serialization.XmlSerializableWriter.WriteFullEndElement(), System.Xml.XmlBaseWriter.WriteFullEndElement(), System.Runtime.Serialization.XmlObjectSerializerWriteContext.WriteISerializable(), System.Runtime.Serialization.XmlObjectSerializerWriteContext.WriteIXmlSerializable(), System.Runtime.Serialization.Json.XmlObjectSerializerWriteContextComplexJson.WriteJsonISerializable(), System.Xml.XmlBaseWriter.WriteNmToken(), System.Xml.XmlDictionaryWriter.WriteNode(), System.Runtime.Serialization.XmlObjectSerializer.WriteObjectContentHandleExceptions(), System.Runtime.Serialization.XmlObjectSerializer.WriteObjectHandleExceptions(), System.Xml.XmlBaseWriter.WritePrimitiveValue(), System.Xml.XmlBaseWriter.WriteProcessingInstruction(), System.Xml.XmlBaseWriter.WriteQualifiedName(), System.Xml.XmlBaseWriter.WriteQualifiedName(), System.Xml.XmlDictionaryWriter.WriteQualifiedName(), System.Xml.XmlBaseWriter.WriteRaw(), System.Xml.XmlCanonicalWriter.WriteStartAttribute(), System.Xml.XmlBaseWriter.WriteStartDocument(), System.Xml.XmlCanonicalWriter.WriteStartElement(), System.Xml.XmlNodeWriter.WriteStartElementAsync(), System.Runtime.Serialization.XmlObjectSerializer.WriteStartObjectHandleExceptions(), System.Xml.XmlCanonicalWriter.WriteText(), System.Xml.XmlCanonicalWriter.WriteText(), System.Xml.XmlCanonicalWriter.WriteText(), System.Xml.XmlDictionaryWriter.WriteValue(), System.Xml.XmlBaseWriter.WriteValue(), System.Xml.XmlBaseWriter.WriteWhitespace(), System.Runtime.Serialization.DataContract.WriteXmlElement(), System.Xml.XmlCanonicalWriter.WriteXmlnsAttribute(), System.Xml.XmlBaseWriter.WriteXmlnsAttribute(), System.Xml.XmlCanonicalWriter.WriteXmlnsAttribute(), System.Xml.XmlBaseWriter.WriteXmlnsAttribute(), System.Runtime.Serialization.ClassDataContract.WriteXmlValue(), System.Runtime.Serialization.DataContract.WriteXmlValue(), and System.Xml.XmlBinaryNodeWriter.WroteAttributeValue().