Terraria: System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperArgumentNull
ThrowHelperArgumentNull()
static Exception System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperArgumentNull (string message) inline static
Definition at line 10 of file DiagnosticUtility.cs.
        {
            return new ArgumentNullException(message);
        }
Referenced by System.Runtime.Serialization.DateTimeFormat.DateTimeFormat(), System.Xml.UniqueId.UniqueId(), System.Xml.XmlBinaryReaderSession.Add(), System.Runtime.Serialization.XmlSerializableServices.AddDefaultSchema(), System.Xml.XmlDictionaryReader.CreateBinaryReader(), System.Xml.XmlDictionaryReader.CreateDictionaryReader(), System.Xml.XmlDictionaryWriter.CreateDictionaryWriter(), System.Xml.XmlDictionaryReader.CreateMtomReader(), System.Xml.XmlDictionaryReader.CreateMtomReader(), System.Xml.XmlDictionaryReader.CreateTextReader(), System.Xml.XmlBaseReader.IndexOfLocalName(), System.Xml.XmlDictionaryReader.IndexOfLocalName(), System.Xml.XmlBaseReader.IndexOfLocalName(), System.Xml.XmlDictionaryReader.IndexOfLocalName(), System.Xml.XmlDictionaryReader.IsLocalName(), System.Xml.XmlBaseReader.IsNamespaceUri(), System.Xml.XmlDictionaryReader.IsNamespaceUri(), System.Xml.XmlBaseReader.IsNamespaceUri(), System.Xml.XmlDictionaryReader.IsNamespaceUri(), System.Xml.XmlBaseReader.IsStartElement(), System.Xml.XmlBaseReader.MoveToInitial(), System.Xml.XmlDictionaryReader.ReadContentAsString(), System.Xml.XmlDictionaryReader.ReadContentAsString(), System.Runtime.Serialization.XmlSerializableServices.ReadNodes(), System.Xml.XmlBinaryReader.SetInput(), System.Xml.XmlUTF8TextReader.SetInput(), System.Xml.XmlBinaryReader.SetInput(), System.Xml.XmlCanonicalWriter.SetOutput(), System.Xml.XmlBinaryWriterSession.TryAdd(), System.Xml.XmlDictionaryString.EmptyStringDictionary.TryLookup(), System.Xml.XmlBinaryReaderSession.TryLookup(), System.Xml.XmlCanonicalWriter.WriteComment(), System.Xml.XmlCanonicalWriter.WriteEndElement(), System.Xml.XmlCanonicalWriter.WriteEscapedText(), System.Runtime.Serialization.XmlSerializableServices.WriteNodes(), System.Xml.XmlCanonicalWriter.WriteStartAttribute(), System.Xml.XmlCanonicalWriter.WriteStartElement(), System.Xml.XmlBaseWriter.WriteString(), System.Xml.XmlBaseWriter.WriteValue(), System.Xml.XmlDictionaryWriter.WriteValue(), System.Xml.XmlBaseWriter.WriteWhitespace(), System.Xml.XmlDictionaryWriter.XmlWrappedWriter.WriteXmlnsAttribute(), System.Xml.XmlBaseWriter.WriteXmlnsAttribute(), System.Xml.XmlCanonicalWriter.WriteXmlnsAttribute(), System.Xml.XmlBaseWriter.WriteXmlnsAttribute(), and System.Xml.XmlDictionaryWriter.WriteXmlnsAttribute().