Terraria: System.Data.SqlTypes.SqlByte.CompareTo
CompareTo() [1/3]
int System.Data.SqlTypes.SqlByte.CompareTo (object? value) inline
Implements System.IComparable< in T >.
Definition at line 477 of file SqlByte.cs.
    {
        if (value is SqlByte value2)
        {
            return CompareTo(value2);
        }
        throw ADP.WrongType(value.GetType(), typeof(SqlByte));
    }
References System.Data.SqlTypes.SqlByte.CompareTo(), System.Xml.Dictionary, System.value, and System.Data.Common.ADP.WrongType().
Referenced by System.Data.Common.SqlByteStorage.Compare(), System.Data.SqlTypes.SqlByte.CompareTo(), and System.Data.Common.SqlByteStorage.CompareValueTo().