Terraria: System.ComponentModel.CultureInfoConverter.GetStandardValues
GetStandardValues() [2/2]
override StandardValuesCollection System.ComponentModel.CultureInfoConverter.GetStandardValues (ITypeDescriptorContext? context) inline virtual
Reimplemented from System.ComponentModel.TypeConverter.
Definition at line 453 of file CultureInfoConverter.cs.
    {
        if (_values == null)
        {
            CultureInfo[] cultures = CultureInfo.GetCultures(CultureTypes.NeutralCultures | CultureTypes.SpecificCultures);
            int num = Array.IndexOf(cultures, CultureInfo.InvariantCulture);
            CultureInfo[] array;
            if (num != -1)
            {
                cultures[num] = null;
                array = new CultureInfo[cultures.Length];
            }
            else
            {
                array = new CultureInfo[cultures.Length + 1];
            }
            Array.Copy(cultures, array, cultures.Length);
            Array.Sort(array, new CultureComparer(this));
            if (array[0] == null)
            {
                array[0] = CultureInfo.InvariantCulture;
            }
            _values = new StandardValuesCollection(array);
        }
        return _values;
    }
References System.ComponentModel.CultureInfoConverter._values, System.array, System.Array.Copy(), System.Globalization.CultureInfo.GetCultures(), System.Array.IndexOf(), System.Globalization.CultureInfo.InvariantCulture, and System.Array.Sort().