Terraria: System.ComponentModel.CultureInfoConverter.ConvertFrom
ConvertFrom() [1/2]
override? object System.ComponentModel.CultureInfoConverter.ConvertFrom (ITypeDescriptorContext? context, CultureInfo? culture, object value) inline virtual
Reimplemented from System.ComponentModel.TypeConverter.
Definition at line 367 of file CultureInfoConverter.cs.
    {
        string text = value as string;
        if (text != null)
        {
            if (GetCultureName(CultureInfo.InvariantCulture).Equals(string.Empty))
            {
                text = CultureInfoMapper.GetCultureInfoName((string)value);
            }
            string b = DefaultCultureString;
            if (culture != null && culture.Equals(CultureInfo.InvariantCulture))
            {
                b = "(Default)";
            }
            CultureInfo cultureInfo = null;
            if (string.IsNullOrEmpty(text) || string.Equals(text, b, StringComparison.Ordinal))
            {
                cultureInfo = CultureInfo.InvariantCulture;
            }
            if (cultureInfo == null)
            {
                foreach (CultureInfo standardValue in GetStandardValues(context))
                {
                    if (standardValue != null && string.Equals(GetCultureName(standardValue), text, StringComparison.Ordinal))
                    {
                        cultureInfo = standardValue;
                        break;
                    }
                }
            }
            if (cultureInfo == null)
            {
                try
                {
                    cultureInfo = new CultureInfo(text);
                }
                catch
                {
                }
            }
            if (cultureInfo == null)
            {
                foreach (CultureInfo value2 in _values)
                {
                    if (value2 != null && GetCultureName(value2).StartsWith(text, StringComparison.CurrentCulture))
                    {
                        cultureInfo = value2;
                        break;
                    }
                }
            }
            if (cultureInfo == null)
            {
                throw new ArgumentException(System.SR.Format(System.SR.CultureInfoConverterInvalidCulture, (string)value), "value");
            }
            return cultureInfo;
        }
        return base.ConvertFrom(context, culture, value);
    }
References System.ComponentModel.CultureInfoConverter._values, System.culture, System.SR.CultureInfoConverterInvalidCulture, System.ComponentModel.CultureInfoConverter.DefaultCultureString, System.SR.Format(), System.ComponentModel.CultureInfoConverter.CultureInfoMapper.GetCultureInfoName(), System.ComponentModel.CultureInfoConverter.GetCultureName(), System.ComponentModel.TypeConverter.GetStandardValues(), System.Globalization.CultureInfo.InvariantCulture, System.text, and System.value.