Terraria: System.Security.Cryptography.ECDiffieHellmanCng.ProcessPkcs8Response
ProcessPkcs8Response()
void System.Security.Cryptography.ECDiffieHellmanCng.ProcessPkcs8Response (System::Security::Cryptography::CngPkcs8::Pkcs8Response response) inline private
Definition at line 598 of file ECDiffieHellmanCng.cs.
    {
        if (response.GetAlgorithmGroup() != "ECDH")
        {
            response.FreeKey();
            throw new CryptographicException(System.SR.Cryptography_NotValidPublicOrPrivateKey);
        }
        AcceptImport(response);
    }
References System.Security.Cryptography.ECDiffieHellmanCng.AcceptImport(), and System.SR.Cryptography_NotValidPublicOrPrivateKey.
Referenced by System.Security.Cryptography.ECDiffieHellmanCng.ImportEncryptedPkcs8PrivateKey(), System.Security.Cryptography.ECDiffieHellmanCng.ImportEncryptedPkcs8PrivateKey(), and System.Security.Cryptography.ECDiffieHellmanCng.ImportPkcs8PrivateKey().