Terraria: Terraria.DelegateMethods.Minecart.BumperSoundFart
BumperSoundFart()
static void Terraria.DelegateMethods.Minecart.BumperSoundFart (Player Player, Vector2 Position, int Width, int Height) inline static
        {
            SoundEngine.PlaySound(SoundID.Item16, (int)Position.X + Width / 2, (int)Position.Y + Height / 2);
            SoundEngine.PlaySound(SoundID.Item56, (int)Position.X + Width / 2, (int)Position.Y + Height / 2);
            SpawnFartCloud(Player, Position, Width, Height);
        }
References Terraria.ID.SoundID.Item16, Terraria.ID.SoundID.Item56, Terraria.Audio.SoundEngine.PlaySound(), and Terraria.DelegateMethods.Minecart.SpawnFartCloud().
Referenced by Terraria.Mount.Initialize().