Terraria: Terraria.DelegateMethods.Minecart.SparksMeow
SparksMeow()
static void Terraria.DelegateMethods.Minecart.SparksMeow (Vector2 dustPosition) inline static
Definition at line 329 of file DelegateMethods.cs.
        {
            dustPosition += new Vector2((Main.rand.Next(2) == 0) ? 13 : (-13), 0f).RotatedBy(rotation);
            int num = Dust.NewDust(dustPosition, 1, 1, 213, Main.rand.Next(-2, 3), Main.rand.Next(-2, 3));
            Main.dust[num].shader = GameShaders.Armor.GetShaderFromItemId(2870);
            Main.dust[num].noGravity = true;
            Main.dust[num].fadeIn = Main.dust[num].scale + 1f + 0.01f * (float)Main.rand.Next(0, 51);
            Main.dust[num].noGravity = true;
            Main.dust[num].velocity *= (float)Main.rand.Next(15, 51) * 0.01f;
            Main.dust[num].velocity.X *= (float)Main.rand.Next(25, 101) * 0.01f;
            Main.dust[num].velocity.Y -= (float)Main.rand.Next(15, 31) * 0.1f;
            Main.dust[num].position.Y -= 4f;
            if (Main.rand.Next(3) != 0)
            {
                Main.dust[num].noGravity = false;
            }
            else
            {
                Main.dust[num].scale *= 0.6f;
            }
        }
References Terraria.Graphics.Shaders.GameShaders.Armor, Terraria.Main.dust, Terraria.Dust.fadeIn, Terraria.Graphics.Shaders.ArmorShaderDataSet.GetShaderFromItemId(), Terraria.Dust.NewDust(), Terraria.Dust.noGravity, Terraria.Dust.position, Terraria.Main.rand, Terraria.DelegateMethods.Minecart.rotation, Terraria.Dust.scale, Terraria.Dust.shader, and Terraria.Dust.velocity.
Referenced by Terraria.Mount.Initialize().