Terraria: System.Security.Cryptography.ECDiffieHellmanCng.GenerateKey
GenerateKey()
override void System.Security.Cryptography.ECDiffieHellmanCng.GenerateKey (ECCurve curve) inline virtual
Reimplemented from System.Security.Cryptography.ECDiffieHellman.
Definition at line 333 of file ECDiffieHellmanCng.cs.
    {
        curve.Validate();
        _core.DisposeKey();
        if (curve.IsNamed)
        {
            if (string.IsNullOrEmpty(curve.Oid.FriendlyName))
            {
                throw new PlatformNotSupportedException(System.SR.Format(System.SR.Cryptography_InvalidCurveOid, curve.Oid.Value));
            }
            CngAlgorithm cngAlgorithm = CngKey.EcdhCurveNameToAlgorithm(curve.Oid.FriendlyName);
            if (CngKey.IsECNamedCurve(cngAlgorithm.Algorithm))
            {
                CngKey orGenerateKey = _core.GetOrGenerateKey(curve);
                ForceSetKeySize(orGenerateKey.KeySize);
                return;
            }
            int num = 0;
            if (cngAlgorithm == CngAlgorithm.ECDiffieHellmanP256)
            {
                num = 256;
            }
            else if (cngAlgorithm == CngAlgorithm.ECDiffieHellmanP384)
            {
                num = 384;
            }
            else
            {
                if (!(cngAlgorithm == CngAlgorithm.ECDiffieHellmanP521))
                {
                    throw new ArgumentException(System.SR.Cryptography_InvalidKeySize);
                }
                num = 521;
            }
            _core.GetOrGenerateKey(num, cngAlgorithm);
            ForceSetKeySize(num);
        }
        else
        {
            if (!curve.IsExplicit)
            {
                throw new PlatformNotSupportedException(System.SR.Format(System.SR.Cryptography_CurveNotSupported, curve.CurveType.ToString()));
            }
            CngKey orGenerateKey2 = _core.GetOrGenerateKey(curve);
            ForceSetKeySize(orGenerateKey2.KeySize);
        }
    }
References System.Security.Cryptography.ECDiffieHellmanCng._core, System.Security.Cryptography.CngAlgorithm.Algorithm, System.SR.Cryptography_CurveNotSupported, System.SR.Cryptography_InvalidCurveOid, System.SR.Cryptography_InvalidKeySize, System.Security.Cryptography.ECCurve.CurveType, Internal.Cryptography.CngAlgorithmCore.DisposeKey(), System.Security.Cryptography.CngKey.EcdhCurveNameToAlgorithm(), System.Security.Cryptography.CngAlgorithm.ECDiffieHellmanP256, System.Security.Cryptography.CngAlgorithm.ECDiffieHellmanP384, System.Security.Cryptography.CngAlgorithm.ECDiffieHellmanP521, System.Security.Cryptography.ECDiffieHellmanCng.ForceSetKeySize(), System.SR.Format(), System.Security.Cryptography.Oid.FriendlyName, Internal.Cryptography.CngAlgorithmCore.GetOrGenerateKey(), System.Security.Cryptography.CngKey.IsECNamedCurve(), System.Security.Cryptography.ECCurve.IsExplicit, System.Security.Cryptography.ECCurve.IsNamed, System.Security.Cryptography.CngKey.KeySize, System.Security.Cryptography.ECCurve.Oid, System.Security.Cryptography.ECCurve.Validate(), and System.Security.Cryptography.Oid.Value.
Referenced by System.Security.Cryptography.ECDiffieHellmanCng.ECDiffieHellmanCng().