Terraria: System.Security.Cryptography.ECDiffieHellmanCng.DeriveKeyMaterial
DeriveKeyMaterial() [2/2]
override byte[] System.Security.Cryptography.ECDiffieHellmanCng.DeriveKeyMaterial (ECDiffieHellmanPublicKey otherPartyPublicKey) inline virtual
Reimplemented from System.Security.Cryptography.ECDiffieHellman.
Definition at line 239 of file ECDiffieHellmanCng.cs.
    {
        if (otherPartyPublicKey == null)
        {
            throw new ArgumentNullException("otherPartyPublicKey");
        }
        if (otherPartyPublicKey is ECDiffieHellmanCngPublicKey eCDiffieHellmanCngPublicKey)
        {
            using CngKey otherPartyPublicKey2 = eCDiffieHellmanCngPublicKey.Import();
            return DeriveKeyMaterial(otherPartyPublicKey2);
        }
        ECParameters parameters = otherPartyPublicKey.ExportParameters();
        using ECDiffieHellmanCng eCDiffieHellmanCng = new ECDiffieHellmanCng();
        eCDiffieHellmanCng.ImportParameters(parameters);
        ECDiffieHellmanCngPublicKey eCDiffieHellmanCngPublicKey2;
        using (eCDiffieHellmanCngPublicKey2 = (ECDiffieHellmanCngPublicKey)eCDiffieHellmanCng.PublicKey)
        {
            using CngKey otherPartyPublicKey3 = eCDiffieHellmanCngPublicKey2.Import();
            return DeriveKeyMaterial(otherPartyPublicKey3);
        }
    }
References System.Security.Cryptography.ECDiffieHellmanCng.ECDiffieHellmanCng(), System.Security.Cryptography.ECDiffieHellmanCng.DeriveKeyMaterial(), System.Security.Cryptography.ECDiffieHellmanPublicKey.ExportParameters(), System.Security.Cryptography.ECDiffieHellmanCngPublicKey.Import(), and System.Security.Cryptography.CngKey.Import().
Referenced by System.Security.Cryptography.ECDiffieHellmanCng.DeriveKeyMaterial().