Terraria: SoundPlayer.StopAll
StopAll()
void SoundPlayer.StopAll () inline
     {
         //IL_000f: Unknown result type (might be due to invalid IL or missing references)
         foreach (ItemPair<ActiveSound> item in (IEnumerable<ItemPair<ActiveSound>>)_trackedSounds)
         {
             item.Value.Stop();
         }
         _trackedSounds.Clear();
     }
References _trackedSounds, and SlotVector< T >.Clear().
Referenced by Reload(), and SoundEngine.StopTrackedSounds().