Terraria: AchievementAdvisor.DrawOneAchievement
DrawOneAchievement()
void AchievementAdvisor.DrawOneAchievement (SpriteBatch spriteBatch, Vector2 position, bool large) inline
     {
         List<AchievementAdvisorCard> bestCards = GetBestCards(1);
         if (bestCards.Count < 1)
         {
             return;
         }
         AchievementAdvisorCard hoveredCard = bestCards[0];
         float num = 0.35f;
         if (large)
         {
             num = 0.75f;
         }
         _hoveredCard = null;
         DrawCard(bestCards[0], spriteBatch, position + new Vector2(8f) * num, num, out var hovered);
         if (!hovered)
         {
             return;
         }
         _hoveredCard = hoveredCard;
         if (!PlayerInput.IgnoreMouseInterface)
         {
             Main.player[Main.myPlayer].mouseInterface = true;
             if (Main.mouseLeft && Main.mouseLeftRelease)
             {
                 Main.ingameOptionsWindow = false;
                 IngameFancyUI.OpenAchievementsAndGoto(_hoveredCard.achievement);
             }
         }
     }
References _hoveredCard, AchievementAdvisorCard.achievement, DrawCard(), GetBestCards(), PlayerInput.IgnoreMouseInterface, Main.ingameOptionsWindow, Player.mouseInterface, Main.mouseLeft, Main.mouseLeftRelease, Main.myPlayer, IngameFancyUI.OpenAchievementsAndGoto(), and Main.player.
Referenced by Main.DrawInventory().