Terraria: AchievementAdvisor.DrawMouseHover
DrawMouseHover()
void AchievementAdvisor.DrawMouseHover () inline
     {
         if (_hoveredCard != null)
         {
             Main.spriteBatch.End();
             Main.spriteBatch.Begin(SpriteSortMode.Deferred, null, null, null, null, null, Main.UIScaleMatrix);
             PlayerInput.SetZoom_UI();
             Item item = new Item();
             item.SetDefaults(0, noMatCheck: true);
             item.SetNameOverride(_hoveredCard.achievement.FriendlyName.Value);
             item.ToolTip = ItemTooltip.FromLanguageKey(_hoveredCard.achievement.Description.Key);
             item.type = 1;
             item.scale = 0f;
             item.rare = 10;
             item.value = -1;
             Main.HoverItem = item;
             Main.instance.MouseText("", 0, 0);
             Main.mouseText = true;
         }
     }
References _hoveredCard, AchievementAdvisorCard.achievement, Achievement.Description, Achievement.FriendlyName, ItemTooltip.FromLanguageKey(), Main.HoverItem, Main.instance, LocalizedText.Key, Main.mouseText, Main.MouseText(), Item.rare, Item.scale, Item.SetDefaults(), Item.SetNameOverride(), PlayerInput.SetZoom_UI(), Main.spriteBatch, Item.ToolTip, Item.type, Main.UIScaleMatrix, LocalizedText.Value, and Item.value.
Referenced by Main.DrawMouseOver().