Terraria: AchievementAdvisor.DrawOptionsPanel
DrawOptionsPanel()
void AchievementAdvisor.DrawOptionsPanel (SpriteBatch spriteBatch, Vector2 leftPosition, Vector2 rightPosition) inline
     {
         List<AchievementAdvisorCard> bestCards = GetBestCards();
         _hoveredCard = null;
         int num = bestCards.Count;
         if (num > 5)
         {
             num = 5;
         }
         bool hovered;
         for (int i = 0; i < num; i++)
         {
             DrawCard(bestCards[i], spriteBatch, leftPosition + new Vector2(42 * i, 0f), 0.5f, out hovered);
             if (hovered)
             {
                 _hoveredCard = bestCards[i];
             }
         }
         for (int j = 5; j < bestCards.Count; j++)
         {
             DrawCard(bestCards[j], spriteBatch, rightPosition + new Vector2(42 * j, 0f), 0.5f, out hovered);
             if (hovered)
             {
                 _hoveredCard = bestCards[j];
             }
         }
         if (_hoveredCard == null)
         {
             return;
         }
         if (_hoveredCard.achievement.IsCompleted)
         {
             _hoveredCard = null;
         }
         else if (!PlayerInput.IgnoreMouseInterface)
         {
             Main.player[Main.myPlayer].mouseInterface = true;
             if (Main.mouseLeft && Main.mouseLeftRelease)
             {
                 Main.ingameOptionsWindow = false;
                 IngameFancyUI.OpenAchievementsAndGoto(_hoveredCard.achievement);
             }
         }
     }
References _hoveredCard, AchievementAdvisorCard.achievement, DrawCard(), GetBestCards(), PlayerInput.IgnoreMouseInterface, Main.ingameOptionsWindow, Achievement.IsCompleted, Player.mouseInterface, Main.mouseLeft, Main.mouseLeftRelease, Main.myPlayer, IngameFancyUI.OpenAchievementsAndGoto(), and Main.player.