Terraria: System.Runtime.Serialization.XmlObjectSerializerReadContextComplex.InternalDeserializeInSharedTypeMode
InternalDeserializeInSharedTypeMode()
object System.Runtime.Serialization.XmlObjectSerializerReadContextComplex.InternalDeserializeInSharedTypeMode (XmlReaderDelegator xmlReader, int declaredTypeID, Type declaredType, string name, string ns) inline private inherited
Definition at line 72 of file XmlObjectSerializerReadContextComplex.cs.
    {
        object retObj = null;
        if (TryHandleNullOrRef(xmlReader, declaredType, name, ns, ref retObj))
        {
            return retObj;
        }
        string clrAssembly = attributes.ClrAssembly;
        string clrType = attributes.ClrType;
        DataContract dataContract2;
        if (clrAssembly != null && clrType != null)
        {
            Assembly assembly;
            Type type;
            DataContract dataContract = ResolveDataContractInSharedTypeMode(clrAssembly, clrType, out assembly, out type);
            if (dataContract == null)
            {
                if (assembly == null)
                {
                    throw XmlObjectSerializer.CreateSerializationException(System.SR.Format(System.SR.AssemblyNotFound, clrAssembly));
                }
                throw XmlObjectSerializer.CreateSerializationException(System.SR.Format(System.SR.ClrTypeNotFound, assembly.FullName, clrType));
            }
            dataContract2 = dataContract;
            if (declaredType != null && declaredType.IsArray)
            {
                dataContract2 = ((declaredTypeID < 0) ? GetDataContract(declaredType) : GetDataContract(declaredTypeID, declaredType.TypeHandle));
            }
        }
        else
        {
            if (clrAssembly != null)
            {
                throw XmlObjectSerializer.CreateSerializationException(XmlObjectSerializer.TryAddLineInfo(xmlReader, System.SR.Format(System.SR.AttributeNotFound, "http://schemas.microsoft.com/2003/10/Serialization/", "Type", xmlReader.NodeType, xmlReader.NamespaceURI, xmlReader.LocalName)));
            }
            if (clrType != null)
            {
                throw XmlObjectSerializer.CreateSerializationException(XmlObjectSerializer.TryAddLineInfo(xmlReader, System.SR.Format(System.SR.AttributeNotFound, "http://schemas.microsoft.com/2003/10/Serialization/", "Assembly", xmlReader.NodeType, xmlReader.NamespaceURI, xmlReader.LocalName)));
            }
            if (declaredType == null)
            {
                throw XmlObjectSerializer.CreateSerializationException(XmlObjectSerializer.TryAddLineInfo(xmlReader, System.SR.Format(System.SR.AttributeNotFound, "http://schemas.microsoft.com/2003/10/Serialization/", "Type", xmlReader.NodeType, xmlReader.NamespaceURI, xmlReader.LocalName)));
            }
            dataContract2 = ((declaredTypeID < 0) ? GetDataContract(declaredType) : GetDataContract(declaredTypeID, declaredType.TypeHandle));
        }
        return ReadDataContractValue(dataContract2, xmlReader);
    }
References System.SR.AssemblyNotFound, System.SR.AttributeNotFound, System.Runtime.Serialization.XmlObjectSerializerReadContext.attributes, System.Runtime.Serialization.Attributes.ClrAssembly, System.Runtime.Serialization.Attributes.ClrType, System.SR.ClrTypeNotFound, System.Runtime.Serialization.XmlObjectSerializer.CreateSerializationException(), System.Runtime.Serialization.Dictionary, System.SR.Format(), System.Runtime.Serialization.XmlObjectSerializerContext.GetDataContract(), System.Runtime.Serialization.XmlObjectSerializerReadContext.ReadDataContractValue(), System.Runtime.Serialization.XmlObjectSerializerReadContextComplex.ResolveDataContractInSharedTypeMode(), System.Runtime.Serialization.XmlObjectSerializer.TryAddLineInfo(), System.Runtime.Serialization.XmlObjectSerializerReadContext.TryHandleNullOrRef(), and System.type.
Referenced by System.Runtime.Serialization.XmlObjectSerializerReadContextComplex.InternalDeserialize(), System.Runtime.Serialization.XmlObjectSerializerReadContextComplex.InternalDeserialize(), and System.Runtime.Serialization.XmlObjectSerializerReadContextComplex.InternalDeserialize().