Terraria: System.Runtime.Serialization.XmlObjectSerializerReadContextComplex.ResolveDataContractInSharedTypeMode
ResolveDataContractInSharedTypeMode()
DataContract System.Runtime.Serialization.XmlObjectSerializerReadContextComplex.ResolveDataContractInSharedTypeMode (string assemblyName, string typeName, out Assembly assembly, out Type type) inline private inherited
Definition at line 142 of file XmlObjectSerializerReadContextComplex.cs.
    {
        type = ResolveDataContractTypeInSharedTypeMode(assemblyName, typeName, out assembly);
        if (type != null)
        {
            return GetDataContract(type);
        }
        return null;
    }
References System.Runtime.Serialization.Dictionary, System.Runtime.Serialization.XmlObjectSerializerContext.GetDataContract(), System.Runtime.Serialization.XmlObjectSerializerReadContextComplex.ResolveDataContractTypeInSharedTypeMode(), and System.type.
Referenced by System.Runtime.Serialization.XmlObjectSerializerReadContextComplex.InternalDeserializeInSharedTypeMode(), and System.Runtime.Serialization.XmlObjectSerializerReadContextComplex.ResolveDataContractFromTypeName().