Terraria: System.Runtime.Serialization.XmlObjectSerializerReadContextComplex.InternalDeserializeWithSurrogate
InternalDeserializeWithSurrogate()
object System.Runtime.Serialization.XmlObjectSerializerReadContextComplex.InternalDeserializeWithSurrogate (XmlReaderDelegator xmlReader, Type declaredType, DataContract surrogateDataContract, string name, string ns) inline private inherited
Definition at line 121 of file XmlObjectSerializerReadContextComplex.cs.
    {
        DataContract dataContract = surrogateDataContract ?? GetDataContract(DataContractSurrogateCaller.GetDataContractType(_serializationSurrogateProvider, declaredType));
        if (IsGetOnlyCollection && dataContract.UnderlyingType != declaredType)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new InvalidDataContractException(System.SR.Format(System.SR.SurrogatesWithGetOnlyCollectionsNotSupportedSerDeser, DataContract.GetClrTypeFullName(declaredType))));
        }
        ReadAttributes(xmlReader);
        string objectId = GetObjectId();
        object obj = InternalDeserialize(xmlReader, name, ns, declaredType, ref dataContract);
        object deserializedObject = DataContractSurrogateCaller.GetDeserializedObject(_serializationSurrogateProvider, obj, dataContract.UnderlyingType, declaredType);
        ReplaceDeserializedObject(objectId, obj, deserializedObject);
        return deserializedObject;
    }
References System.Runtime.Serialization.XmlObjectSerializerReadContextComplex._serializationSurrogateProvider, System.Runtime.Serialization.Dictionary, System.SR.Format(), System.Runtime.Serialization.DataContract.GetClrTypeFullName(), System.Runtime.Serialization.XmlObjectSerializerContext.GetDataContract(), System.Runtime.Serialization.DataContractSurrogateCaller.GetDataContractType(), System.Runtime.Serialization.DataContractSurrogateCaller.GetDeserializedObject(), System.Runtime.Serialization.XmlObjectSerializerReadContext.GetObjectId(), System.Runtime.Serialization.XmlObjectSerializerReadContextComplex.InternalDeserialize(), System.Runtime.Serialization.XmlObjectSerializerReadContext.IsGetOnlyCollection, System.obj, System.Runtime.Serialization.XmlObjectSerializerReadContext.ReadAttributes(), System.Runtime.Serialization.XmlObjectSerializerReadContext.ReplaceDeserializedObject(), System.SR.SurrogatesWithGetOnlyCollectionsNotSupportedSerDeser, and System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperError().
Referenced by System.Runtime.Serialization.XmlObjectSerializerReadContextComplex.InternalDeserialize(), System.Runtime.Serialization.XmlObjectSerializerReadContextComplex.InternalDeserialize(), and System.Runtime.Serialization.XmlObjectSerializerReadContextComplex.InternalDeserialize().