Terraria: System.Runtime.Serialization.XmlObjectSerializerReadContextComplex.InternalDeserialize
InternalDeserialize() [2/4]
override object System.Runtime.Serialization.XmlObjectSerializerReadContextComplex.InternalDeserialize (XmlReaderDelegator xmlReader, int declaredTypeID, RuntimeTypeHandle declaredTypeHandle, string name, string ns) inline package virtual inherited
Reimplemented from System.Runtime.Serialization.XmlObjectSerializerReadContext.
Definition at line 30 of file XmlObjectSerializerReadContextComplex.cs.
    {
        if (_mode == SerializationMode.SharedContract)
        {
            if (_serializationSurrogateProvider == null)
            {
                return base.InternalDeserialize(xmlReader, declaredTypeID, declaredTypeHandle, name, ns);
            }
            return InternalDeserializeWithSurrogate(xmlReader, Type.GetTypeFromHandle(declaredTypeHandle), null, name, ns);
        }
        return InternalDeserializeInSharedTypeMode(xmlReader, declaredTypeID, Type.GetTypeFromHandle(declaredTypeHandle), name, ns);
    }
References System.Runtime.Serialization.XmlObjectSerializerReadContextComplex._mode, System.Runtime.Serialization.XmlObjectSerializerReadContextComplex._serializationSurrogateProvider, System.Runtime.Serialization.Dictionary, System.Type.GetTypeFromHandle(), System.Runtime.Serialization.XmlObjectSerializerReadContextComplex.InternalDeserializeInSharedTypeMode(), and System.Runtime.Serialization.XmlObjectSerializerReadContextComplex.InternalDeserializeWithSurrogate().
Referenced by System.Runtime.Serialization.XmlObjectSerializerReadContextComplex.InternalDeserializeWithSurrogate().