Terraria: Terraria.IO.FileData.GetFileName
GetFileName()
string Terraria.IO.FileData.GetFileName (bool includeExtension = true) inline inherited
    {
        return FileUtilities.GetFileName(Path, includeExtension);
    }
References Terraria.Utilities.FileUtilities.GetFileName(), and Terraria.IO.FileData.Path.
Referenced by Terraria.IO.FavoritesFile.ClearEntry(), Terraria.GameContent.UI.Elements.UICharacterListItem.CompareTo(), Terraria.IO.FavoritesFile.IsFavorite(), Terraria.IO.PlayerFileData.MoveToCloud(), Terraria.IO.PlayerFileData.MoveToLocal(), Terraria.Social.Steam.WorkshopSocialModule.PublishWorld(), Terraria.IO.FavoritesFile.SaveFavorite(), Terraria.Social.Steam.WorkshopSocialModule.TryGetInfoForWorld(), Terraria.GameContent.UI.States.UICharacterSelect.UpdateFavoritesCache(), Terraria.GameContent.UI.States.UIWorldSelect.UpdateFavoritesCache(), Terraria.GameContent.UI.States.UICharacterSelect.UpdatePlayersList(), and Terraria.GameContent.UI.States.UIWorldSelect.UpdateWorldsList().