Terraria: System.Reflection.Metadata.Ecma335.TypeRefTableReader.GetName
GetName()
StringHandle System.Reflection.Metadata.Ecma335.TypeRefTableReader.GetName (TypeReferenceHandle handle) inline package
Definition at line 41 of file TypeRefTableReader.cs.
    {
        int num = (handle.RowId - 1) * RowSize;
        return StringHandle.FromOffset(Block.PeekHeapReference(num + _NameOffset, _IsStringHeapRefSizeSmall));
    }
References System.Reflection.Metadata.Ecma335.TypeRefTableReader._IsStringHeapRefSizeSmall, System.Reflection.Metadata.Ecma335.TypeRefTableReader._NameOffset, System.Reflection.Metadata.Ecma335.TypeRefTableReader.Block, System.Reflection.Metadata.StringHandle.FromOffset(), System.Reflection.Internal.MemoryBlock.PeekHeapReference(), and System.Reflection.Metadata.Ecma335.TypeRefTableReader.RowSize.
Referenced by System.Reflection.Metadata.MetadataReader.CalculateFieldDefTreatmentAndRowId(), System.Reflection.Metadata.MetadataReader.GetAttributeTypeNameRaw(), System.Reflection.Metadata.TypeReference.GetProjectedName(), System.Reflection.Metadata.MetadataReader.GetProjectionIndexForTypeReference(), System.Reflection.Metadata.MetadataReader.GetSpecialTypeRefTreatment(), System.Reflection.Metadata.MetadataReader.IsSystemAttribute(), System.Reflection.Metadata.MetadataReader.IsWindowsAttributeUsageAttribute(), and System.Reflection.Metadata.MetadataReader.NeedsWinRTPrefix().