Terraria: System.Threading.Tasks.Parallel.s_defaultParallelOptions
s_defaultParallelOptions
readonly ParallelOptions System.Threading.Tasks.Parallel.s_defaultParallelOptions = new ParallelOptions() static package
Definition at line 148 of file Parallel.cs.
Referenced by System.Threading.Tasks.Parallel.For(), System.Threading.Tasks.Parallel.For(), System.Threading.Tasks.Parallel.For(), System.Threading.Tasks.Parallel.For(), System.Threading.Tasks.Parallel.For< TLocal >(), System.Threading.Tasks.Parallel.For< TLocal >(), System.Threading.Tasks.Parallel.ForEach< TSource >(), System.Threading.Tasks.Parallel.ForEach< TSource >(), System.Threading.Tasks.Parallel.ForEach< TSource >(), System.Threading.Tasks.Parallel.ForEach< TSource >(), System.Threading.Tasks.Parallel.ForEach< TSource >(), System.Threading.Tasks.Parallel.ForEach< TSource >(), System.Threading.Tasks.Parallel.ForEach< TSource, TLocal >(), System.Threading.Tasks.Parallel.ForEach< TSource, TLocal >(), System.Threading.Tasks.Parallel.ForEach< TSource, TLocal >(), System.Threading.Tasks.Parallel.ForEach< TSource, TLocal >(), and System.Threading.Tasks.Parallel.Invoke().