Terraria: System.Threading.Tasks.Parallel.ThrowSingleCancellationExceptionOrOtherException
ThrowSingleCancellationExceptionOrOtherException()
static void System.Threading.Tasks.Parallel.ThrowSingleCancellationExceptionOrOtherException (ICollection exceptions, CancellationToken cancelToken, Exception otherException) inline static private
Definition at line 1447 of file Parallel.cs.
    {
        OperationCanceledException ex = ReduceToSingleCancellationException(exceptions, cancelToken);
        ExceptionDispatchInfo.Throw(ex ?? otherException);
    }
References System.exceptions, System.Threading.Tasks.Parallel.ReduceToSingleCancellationException(), and System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw().
Referenced by System.Threading.Tasks.Parallel.ForWorker64< TLocal >(), System.Threading.Tasks.Parallel.ForWorker< TLocal >(), System.Threading.Tasks.Parallel.Invoke(), and System.Threading.Tasks.Parallel.PartitionerForEachWorker< TSource, TLocal >().