Terraria: System.Threading.Tasks.Parallel.CheckTimeoutReached
CheckTimeoutReached()
static bool System.Threading.Tasks.Parallel.CheckTimeoutReached (int timeoutOccursAt) inline static private
Definition at line 429 of file Parallel.cs.
    {
        int tickCount = Environment.TickCount;
        if (tickCount < timeoutOccursAt)
        {
            return false;
        }
        if (0 > timeoutOccursAt && 0 < tickCount)
        {
            return false;
        }
        return true;
    }
References System.Environment.TickCount.
Referenced by System.Threading.Tasks.Parallel.ForWorker64< TLocal >(), System.Threading.Tasks.Parallel.ForWorker< TLocal >(), and System.Threading.Tasks.Parallel.PartitionerForEachWorker< TSource, TLocal >().