Terraria: TileID.Sets.Platforms
Platforms
bool [] TileID.Sets.Platforms = Factory.CreateBoolSet(19, 427, 435, 436, 437, 438, 439) static
Referenced by NPC.AI(), NPC.AI_003_Fighters(), Projectile.AI_007_GrapplingHooks(), Projectile.AI_010(), Projectile.AI_016(), Projectile.AI_026(), Projectile.AI_067_FreakingPirates(), WorldGen.AnchorValid(), TileObject.CanPlace(), WorldGen.Check1x2(), WorldGen.Check1x2Top(), WorldGen.Check2xX(), WorldGen.Check3x2(), WorldGen.Check4x2(), WorldGen.CheckBanner(), CultistRitual.CheckFloor(), WorldGen.CheckGnome(), WorldGen.CheckLilyPad(), WorldGen.CheckOnTable1x1(), WorldGen.CheckProjectilePressurePad_GetPossiblePlacementDirections(), WorldGen.CheckTorch(), Recipe.CreateReversePlatformRecipes(), TileDrawing.DrawBasicTile(), TileDrawing.DrawSingleTile(), WaterfallManager.DrawWaterfall(), WorldGen.dropMeteor(), ContentSamples.CreativeHelper.GetItemGroup(), LiquidRenderer.InternalPrepareDraw(), WorldGen.IsBelowANonHammeredPlatform(), WorldGen.IsRope(), Collision.IsWorldPointSolid(), Player.ItemCheck_Shoot(), Player.ItemCheck_UseMiningTools_TryPoundingTile(), NPC.NPCCanStickToWalls(), Player.PlaceThing_Tiles_BlockPlacementForAssortedThings(), Player.PlaceThing_Tiles_CheckRopeUsability(), Player.PlaceThing_Tiles_PlaceIt_AutoPaintAndActuate(), Player.PlaceThing_Tiles_PlaceIt_SpinSmartPlatform(), Player.PlaceThing_Tiles_PlaceIt_UnslopeForSolids(), Player.PlaceThing_ValidTileForReplacement(), WorldGen.PlaceTile(), WorldGen.PlatformProperSides(), WorldGen.PoundPlatform(), WorldGen.ReplaceTile_DoActualReplacement_Single(), WorldGen.ReplaceTile_IsValidPlatform(), Collision.SlopeCollision(), WorldGen.SolidTile2(), WorldGen.SolidTileAllowBottomSlope(), WorldGen.SolidTileAllowLeftSlope(), WorldGen.SolidTileAllowRightSlope(), WorldGen.SolidTileAllowTopSlope(), DelegateMethods.SpreadDirt(), SmartCursorHelper.Step_Platforms(), SmartCursorHelper.Step_Torch(), Collision.StepConveyorBelt(), Collision.StepUp(), WorldGen.TileFrame(), WorldGen.TileIsExposedToAir(), WorldGen.TopEdgeCanBeAttachedTo(), and WorldGen.WouldTileReplacementWork().