Terraria: CoinLossRevengeSystem.RevengeMarker.SpawnEnemy
SpawnEnemy()
void CoinLossRevengeSystem.RevengeMarker.SpawnEnemy () inline
         {
             int num = NPC.NewNPC(new EntitySource_RevengeSystem(), (int)_location.X, (int)_location.Y, _npcNetID);
             NPC nPC = Main.npc[num];
             if (_npcNetID < 0)
             {
                 nPC.SetDefaults(_npcNetID);
             }
             if (NPCID.Sets.SpecialSpawningRules.TryGetValue(_npcNetID, out var value) && value == 0)
             {
                 Point point = nPC.position.ToTileCoordinates();
                 nPC.ai[0] = point.X;
                 nPC.ai[1] = point.Y;
                 nPC.netUpdate = true;
             }
             nPC.timeLeft += 3600;
             nPC.extraValue = _coinsValue;
             nPC.value = _baseValue;
             nPC.SpawnedFromStatue = _spawnedFromStatue;
             float num2 = Math.Max(0.5f, _npcHPPercent);
             nPC.life = (int)((float)nPC.lifeMax * num2);
             if (num < 200)
             {
                 if (Main.netMode == 0)
                 {
                     nPC.moneyPing(_location);
                 }
                 else
                 {
                     NetMessage.SendData(23, -1, -1, null, num);
                     NetMessage.SendData(92, -1, -1, null, num, _coinsValue, _location.X, _location.Y);
                 }
             }
             if (DisplayCaching)
             {
                 Main.NewText("Spawned " + nPC.GivenOrTypeName);
             }
         }
References CoinLossRevengeSystem.RevengeMarker._baseValue, CoinLossRevengeSystem.RevengeMarker._coinsValue, CoinLossRevengeSystem.RevengeMarker._location, CoinLossRevengeSystem.RevengeMarker._npcHPPercent, CoinLossRevengeSystem.RevengeMarker._npcNetID, CoinLossRevengeSystem.RevengeMarker._spawnedFromStatue, NPC.ai, CoinLossRevengeSystem.DisplayCaching, NPC.extraValue, NPC.GivenOrTypeName, NPC.life, NPC.lifeMax, NPC.moneyPing(), Main.netMode, NPC.netUpdate, NPC.NewNPC(), Main.NewText(), Main.npc, Entity.position, NetMessage.SendData(), NPC.SetDefaults(), NPC.SpawnedFromStatue, NPCID.Sets.SpecialSpawningRules, NPC.timeLeft, and NPC.value.