Terraria: System.IO.Compression.InflaterManaged.DecodeUncompressedBlock
DecodeUncompressedBlock()
bool System.IO.Compression.InflaterManaged.DecodeUncompressedBlock (out bool end_of_block) inline private
Definition at line 212 of file InflaterManaged.cs.
    {
        end_of_block = false;
        while (true)
        {
            switch (_state)
            {
            case InflaterState.UncompressedAligning:
                _input.SkipToByteBoundary();
                _state = InflaterState.UncompressedByte1;
                goto case InflaterState.UncompressedByte1;
            case InflaterState.UncompressedByte1:
            case InflaterState.UncompressedByte2:
            case InflaterState.UncompressedByte3:
            case InflaterState.UncompressedByte4:
            {
                int bits = _input.GetBits(8);
                if (bits < 0)
                {
                    return false;
                }
                _blockLengthBuffer[(int)(_state - 16)] = (byte)bits;
                if (_state == InflaterState.UncompressedByte4)
                {
                    _blockLength = _blockLengthBuffer[0] + _blockLengthBuffer[1] * 256;
                    int num2 = _blockLengthBuffer[2] + _blockLengthBuffer[3] * 256;
                    if ((ushort)_blockLength != (ushort)(~num2))
                    {
                        throw new InvalidDataException(System.SR.InvalidBlockLength);
                    }
                }
                break;
            }
            case InflaterState.DecodingUncompressed:
            {
                int num = _output.CopyFrom(_input, _blockLength);
                _blockLength -= num;
                if (_blockLength == 0)
                {
                    _state = InflaterState.ReadingBFinal;
                    end_of_block = true;
                    return true;
                }
                if (_output.FreeBytes == 0)
                {
                    return true;
                }
                return false;
            }
            default:
                throw new InvalidDataException(System.SR.UnknownState);
            }
            _state++;
        }
    }
References System.IO.Compression.InflaterManaged._blockLength, System.IO.Compression.InflaterManaged._blockLengthBuffer, System.IO.Compression.InflaterManaged._input, System.IO.Compression.InflaterManaged._output, System.IO.Compression.InflaterManaged._state, System.IO.Compression.OutputWindow.CopyFrom(), System.IO.Compression.OutputWindow.FreeBytes, System.IO.Compression.InputBuffer.GetBits(), System.SR.InvalidBlockLength, System.IO.Compression.InputBuffer.SkipToByteBoundary(), and System.SR.UnknownState.
Referenced by System.IO.Compression.InflaterManaged.Decode().