Terraria: System.Runtime.Serialization.CodeTypeReference.Initialize
Initialize() [2/2]
void System.Runtime.Serialization.CodeTypeReference.Initialize (string typeName, CodeTypeReferenceOptions options) inline private
Definition at line 156 of file CodeTypeReference.cs.
    {
        Options = options;
        if (string.IsNullOrEmpty(typeName))
        {
            typeName = typeof(void).FullName;
            _baseType = typeName;
            ArrayRank = 0;
            ArrayElementType = null;
            return;
        }
        typeName = RipOffAssemblyInformationFromTypeName(typeName);
        int num = typeName.Length - 1;
        int num2 = num;
        _needsFixup = true;
        Queue<int> queue = new Queue<int>();
        while (num2 >= 0)
        {
            int num3 = 1;
            if (typeName[num2--] != ']')
            {
                break;
            }
            while (num2 >= 0 && typeName[num2] == ',')
            {
                num3++;
                num2--;
            }
            if (num2 < 0 || typeName[num2] != '[')
            {
                break;
            }
            queue.Enqueue(num3);
            num2--;
            num = num2;
        }
        num2 = num;
        List<CodeTypeReference> list = new List<CodeTypeReference>();
        Stack<string> stack = new Stack<string>();
        if (num2 > 0 && typeName[num2--] == ']')
        {
            _needsFixup = false;
            int num4 = 1;
            int num5 = num;
            while (num2 >= 0)
            {
                if (typeName[num2] == '[')
                {
                    if (--num4 == 0)
                    {
                        break;
                    }
                }
                else if (typeName[num2] == ']')
                {
                    num4++;
                }
                else if (typeName[num2] == ',' && num4 == 1)
                {
                    if (num2 + 1 < num5)
                    {
                        stack.Push(typeName.Substring(num2 + 1, num5 - num2 - 1));
                    }
                    num5 = num2;
                }
                num2--;
            }
            if (num2 > 0 && num - num2 - 1 > 0)
            {
                if (num2 + 1 < num5)
                {
                    stack.Push(typeName.Substring(num2 + 1, num5 - num2 - 1));
                }
                while (stack.Count > 0)
                {
                    string typeName2 = RipOffAssemblyInformationFromTypeName(stack.Pop());
                    list.Add(new CodeTypeReference(typeName2));
                }
                num = num2 - 1;
            }
        }
        if (num < 0)
        {
            _baseType = typeName;
            return;
        }
        if (queue.Count > 0)
        {
            CodeTypeReference codeTypeReference = new CodeTypeReference(typeName.Substring(0, num + 1), Options);
            for (int i = 0; i < list.Count; i++)
            {
                codeTypeReference.TypeArguments.Add(list[i]);
            }
            while (queue.Count > 1)
            {
                codeTypeReference = new CodeTypeReference(codeTypeReference, queue.Dequeue());
            }
            _baseType = null;
            ArrayRank = queue.Dequeue();
            ArrayElementType = codeTypeReference;
        }
        else if (list.Count > 0)
        {
            for (int j = 0; j < list.Count; j++)
            {
                TypeArguments.Add(list[j]);
            }
            _baseType = typeName.Substring(0, num + 1);
        }
        else
        {
            _baseType = typeName;
        }
        if (_baseType != null && _baseType.IndexOf('`') != -1)
        {
            _needsFixup = false;
        }
    }
References System.Runtime.Serialization.CodeTypeReference.CodeTypeReference(), System.Runtime.Serialization.CodeTypeReference._baseType, System.Runtime.Serialization.CodeTypeReference._needsFixup, System.Runtime.Serialization.CodeTypeReferenceCollection.Add(), System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Runtime.Serialization.CodeTypeReference.ArrayElementType, System.Runtime.Serialization.CodeTypeReference.ArrayRank, System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Runtime.Serialization.Dictionary, System.list, System.options, System.Runtime.Serialization.CodeTypeReference.Options, System.Runtime.Serialization.CodeTypeReference.RipOffAssemblyInformationFromTypeName(), and System.Runtime.Serialization.CodeTypeReference.TypeArguments.