Terraria: System.IO.Compression.InflaterManaged.Finished
Finished()
bool System.IO.Compression.InflaterManaged.Finished () inline
Definition at line 105 of file InflaterManaged.cs.
    {
        if (_state != InflaterState.Done)
        {
            return _state == InflaterState.VerifyingFooter;
        }
        return true;
    }
References System.IO.Compression.InflaterManaged._state.
Referenced by System.IO.Compression.InflaterManaged.Decode(), System.IO.Compression.InflaterManaged.Inflate(), System.IO.Compression.DeflateManagedStream.Read(), System.IO.Compression.DeflateManagedStream.ReadAsyncCore(), and System.IO.Compression.DeflateManagedStream.ReadAsyncInternal().