Terraria: System.IO.Compression.InflaterManaged.Inflate
Inflate()
int System.IO.Compression.InflaterManaged.Inflate (Span< byte > bytes) inline
Definition at line 114 of file InflaterManaged.cs.
    {
        int num = 0;
        do
        {
            int num2 = 0;
            if (_uncompressedSize == -1)
            {
                num2 = _output.CopyTo(bytes);
            }
            else if (_uncompressedSize > _currentInflatedCount)
            {
                bytes = bytes.Slice(0, (int)Math.Min(bytes.Length, _uncompressedSize - _currentInflatedCount));
                num2 = _output.CopyTo(bytes);
                _currentInflatedCount += num2;
            }
            else
            {
                _state = InflaterState.Done;
                _output.ClearBytesUsed();
            }
            if (num2 > 0)
            {
                bytes = bytes.Slice(num2, bytes.Length - num2);
                num += num2;
            }
        }
        while (!bytes.IsEmpty && !Finished() && Decode());
        return num;
    }
References System.IO.Compression.InflaterManaged._currentInflatedCount, System.IO.Compression.InflaterManaged._output, System.IO.Compression.InflaterManaged._state, System.IO.Compression.InflaterManaged._uncompressedSize, System.bytes, System.IO.Compression.OutputWindow.ClearBytesUsed(), System.IO.Compression.OutputWindow.CopyTo(), System.IO.Compression.InflaterManaged.Decode(), System.IO.Compression.InflaterManaged.Finished(), and System.Math.Min().
Referenced by System.IO.Compression.DeflateManagedStream.Read(), System.IO.Compression.DeflateManagedStream.ReadAsyncCore(), and System.IO.Compression.DeflateManagedStream.ReadAsyncInternal().