Terraria: System.IO.Compression.InflaterManaged.Decode
Decode()
bool System.IO.Compression.InflaterManaged.Decode () inline private
Definition at line 145 of file InflaterManaged.cs.
    {
        bool end_of_block = false;
        bool flag = false;
        if (Finished())
        {
            return true;
        }
        if (_state == InflaterState.ReadingBFinal)
        {
            if (!_input.EnsureBitsAvailable(1))
            {
                return false;
            }
            _bfinal = _input.GetBits(1);
            _state = InflaterState.ReadingBType;
        }
        if (_state == InflaterState.ReadingBType)
        {
            if (!_input.EnsureBitsAvailable(2))
            {
                _state = InflaterState.ReadingBType;
                return false;
            }
            _blockType = (BlockType)_input.GetBits(2);
            if (_blockType == BlockType.Dynamic)
            {
                _state = InflaterState.ReadingNumLitCodes;
            }
            else if (_blockType == BlockType.Static)
            {
                _literalLengthTree = HuffmanTree.StaticLiteralLengthTree;
                _distanceTree = HuffmanTree.StaticDistanceTree;
                _state = InflaterState.DecodeTop;
            }
            else
            {
                if (_blockType != 0)
                {
                    throw new InvalidDataException(System.SR.UnknownBlockType);
                }
                _state = InflaterState.UncompressedAligning;
            }
        }
        if (_blockType == BlockType.Dynamic)
        {
            flag = ((_state >= InflaterState.DecodeTop) ? DecodeBlock(out end_of_block) : DecodeDynamicBlockHeader());
        }
        else if (_blockType == BlockType.Static)
        {
            flag = DecodeBlock(out end_of_block);
        }
        else
        {
            if (_blockType != 0)
            {
                throw new InvalidDataException(System.SR.UnknownBlockType);
            }
            flag = DecodeUncompressedBlock(out end_of_block);
        }
        if (end_of_block && _bfinal != 0)
        {
            _state = InflaterState.Done;
        }
        return flag;
    }
References System.IO.Compression.InflaterManaged._bfinal, System.IO.Compression.InflaterManaged._blockType, System.IO.Compression.InflaterManaged._distanceTree, System.IO.Compression.InflaterManaged._input, System.IO.Compression.InflaterManaged._literalLengthTree, System.IO.Compression.InflaterManaged._state, System.IO.Compression.InflaterManaged.DecodeBlock(), System.IO.Compression.InflaterManaged.DecodeDynamicBlockHeader(), System.IO.Compression.InflaterManaged.DecodeUncompressedBlock(), System.IO.Compression.InputBuffer.EnsureBitsAvailable(), System.IO.Compression.InflaterManaged.Finished(), System.IO.Compression.InputBuffer.GetBits(), System.IO.Compression.HuffmanTree.StaticDistanceTree, System.IO.Compression.HuffmanTree.StaticLiteralLengthTree, and System.SR.UnknownBlockType.
Referenced by System.IO.Compression.InflaterManaged.Inflate().