Terraria: System.IO.Compression.InflaterManaged.DecodeBlock
DecodeBlock()
bool System.IO.Compression.InflaterManaged.DecodeBlock (out bool end_of_block_code_seen) inline private
Definition at line 268 of file InflaterManaged.cs.
    {
        end_of_block_code_seen = false;
        int num = _output.FreeBytes;
        while (num > 65536)
        {
            switch (_state)
            {
            case InflaterState.DecodeTop:
            {
                int nextSymbol = _literalLengthTree.GetNextSymbol(_input);
                if (nextSymbol < 0)
                {
                    return false;
                }
                if (nextSymbol < 256)
                {
                    _output.Write((byte)nextSymbol);
                    num--;
                    break;
                }
                if (nextSymbol == 256)
                {
                    end_of_block_code_seen = true;
                    _state = InflaterState.ReadingBFinal;
                    return true;
                }
                nextSymbol -= 257;
                if (nextSymbol < 8)
                {
                    nextSymbol += 3;
                    _extraBits = 0;
                }
                else if (!_deflate64 && nextSymbol == 28)
                {
                    nextSymbol = 258;
                    _extraBits = 0;
                }
                else
                {
                    if (nextSymbol < 0 || nextSymbol >= s_extraLengthBits.Length)
                    {
                        throw new InvalidDataException(System.SR.GenericInvalidData);
                    }
                    _extraBits = s_extraLengthBits[nextSymbol];
                }
                _length = nextSymbol;
                goto case InflaterState.HaveInitialLength;
            }
            case InflaterState.HaveInitialLength:
                if (_extraBits > 0)
                {
                    _state = InflaterState.HaveInitialLength;
                    int bits2 = _input.GetBits(_extraBits);
                    if (bits2 < 0)
                    {
                        return false;
                    }
                    if (_length < 0 || _length >= s_lengthBase.Length)
                    {
                        throw new InvalidDataException(System.SR.GenericInvalidData);
                    }
                    _length = s_lengthBase[_length] + bits2;
                }
                _state = InflaterState.HaveFullLength;
                goto case InflaterState.HaveFullLength;
            case InflaterState.HaveFullLength:
                if (_blockType == BlockType.Dynamic)
                {
                    _distanceCode = _distanceTree.GetNextSymbol(_input);
                }
                else
                {
                    _distanceCode = _input.GetBits(5);
                    if (_distanceCode >= 0)
                    {
                        _distanceCode = s_staticDistanceTreeTable[_distanceCode];
                    }
                }
                if (_distanceCode < 0)
                {
                    return false;
                }
                _state = InflaterState.HaveDistCode;
                goto case InflaterState.HaveDistCode;
            case InflaterState.HaveDistCode:
            {
                int distance;
                if (_distanceCode > 3)
                {
                    _extraBits = _distanceCode - 2 >> 1;
                    int bits = _input.GetBits(_extraBits);
                    if (bits < 0)
                    {
                        return false;
                    }
                    distance = s_distanceBasePosition[_distanceCode] + bits;
                }
                else
                {
                    distance = _distanceCode + 1;
                }
                _output.WriteLengthDistance(_length, distance);
                num -= _length;
                _state = InflaterState.DecodeTop;
                break;
            }
            default:
                throw new InvalidDataException(System.SR.UnknownState);
            }
        }
        return true;
    }
References System.IO.Compression.InflaterManaged._blockType, System.IO.Compression.InflaterManaged._deflate64, System.IO.Compression.InflaterManaged._distanceCode, System.IO.Compression.InflaterManaged._distanceTree, System.IO.Compression.InflaterManaged._extraBits, System.IO.Compression.InflaterManaged._input, System.IO.Compression.InflaterManaged._length, System.IO.Compression.InflaterManaged._literalLengthTree, System.IO.Compression.InflaterManaged._output, System.IO.Compression.InflaterManaged._state, System.IO.Compression.OutputWindow.FreeBytes, System.SR.GenericInvalidData, System.IO.Compression.InputBuffer.GetBits(), System.IO.Compression.HuffmanTree.GetNextSymbol(), System.IO.Compression.InflaterManaged.s_distanceBasePosition, System.IO.Compression.InflaterManaged.s_extraLengthBits, System.IO.Compression.InflaterManaged.s_lengthBase, System.IO.Compression.InflaterManaged.s_staticDistanceTreeTable, System.SR.UnknownState, System.IO.Compression.OutputWindow.Write(), and System.IO.Compression.OutputWindow.WriteLengthDistance().
Referenced by System.IO.Compression.InflaterManaged.Decode().