Terraria: ReLogic.Graphics.DynamicSpriteFontExtensionMethods.DrawString
DrawString() [1/6]
static void ReLogic.Graphics.DynamicSpriteFontExtensionMethods.DrawString (this SpriteBatch spriteBatch, DynamicSpriteFont spriteFont, string text, Vector2 position, Color color) inline static
Definition at line 9 of file DynamicSpriteFontExtensionMethods.cs.
    {
        //IL_0000: Unknown result type (might be due to invalid IL or missing references)
        //IL_0005: Unknown result type (might be due to invalid IL or missing references)
        //IL_0009: Unknown result type (might be due to invalid IL or missing references)
        //IL_000a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0011: Unknown result type (might be due to invalid IL or missing references)
        Vector2 scale = Vector2.One;
        spriteFont.InternalDraw(text, spriteBatch, position, color, 0f, Vector2.Zero, ref scale, (SpriteEffects)0, 0f);
    }
References ReLogic.Graphics.DynamicSpriteFont.InternalDraw(), Microsoft.Xna.Framework.Vector2.One, and Microsoft.Xna.Framework.Vector2.Zero.
Referenced by Terraria.Main.DoDraw(), Terraria.Utils.DrawBorderStringBig(), Terraria.Utils.DrawBorderStringFourWay(), Terraria.Main.DrawBuffIcon(), Terraria.Main.DrawClothesWindow(), Terraria.UI.Chat.ChatManager.DrawColorCodedString(), Terraria.UI.Chat.ChatManager.DrawColorCodedString(), Terraria.Main.DrawFPS(), Terraria.Main.DrawGuideCraftText(), Terraria.Main.DrawGuideCraftText_Old(), Terraria.Main.DrawHairWindow(), Terraria.Main.DrawInfoAccs(), Terraria.Main.DrawInterface_18_DiagnoseVideo(), Terraria.Main.DrawInterface_35_YouDied(), Terraria.Main.DrawInventory(), Terraria.Main.DrawItemTextPopups(), Terraria.GameContent.UI.ResourceSets.ClassicPlayerResourcesDisplaySet.DrawLife(), Terraria.GameContent.UI.ResourceSets.FancyClassicPlayerResourcesDisplaySet.DrawLifeBarText(), Terraria.GameContent.UI.ResourceSets.HorizontalBarsPlayerResourcesDisplaySet.DrawLifeBarText(), Terraria.GameContent.UI.ResourceSets.ClassicPlayerResourcesDisplaySet.DrawMana(), Terraria.GameContent.UI.ResourceSets.FancyClassicPlayerResourcesDisplaySet.DrawManaText(), Terraria.GameContent.UI.ResourceSets.HorizontalBarsPlayerResourcesDisplaySet.DrawManaText(), Terraria.Main.DrawMenu(), Terraria.GameContent.UI.NewMultiplayerClosePlayersOverlay.PlayerOffScreenCache.DrawPlayerDistance(), Terraria.GameContent.UI.LegacyMultiplayerClosePlayersOverlay.DrawPlayerName(), Terraria.GameContent.UI.LegacyMultiplayerClosePlayersOverlay.DrawPlayerName2(), Terraria.GameContent.UI.NewMultiplayerClosePlayersOverlay.PlayerOnScreenCache.DrawPlayerName_WhenPlayerIsOnScreen(), Terraria.GameContent.UI.Elements.UIHeader.DrawSelf(), Terraria.Main.DrawSettingButton(), Terraria.UI.NetDiagnosticsUI.DrawText(), Terraria.UI.LegacyNetDiagnosticsUI.DrawTitles(), Terraria.Main.DrawVersionNumber(), Terraria.Main.GUIHotbarDrawInner(), Terraria.Main.MouseText_DrawBuffTooltip(), and Terraria.UI.LegacyNetDiagnosticsUI.PrintNetDiagnosticsLineForMessage().