Terraria: System.ComponentModel.Design.RuntimeLicenseContext.CaseInsensitiveManifestResourceStreamLookup
CaseInsensitiveManifestResourceStreamLookup()
Stream System.ComponentModel.Design.RuntimeLicenseContext.CaseInsensitiveManifestResourceStreamLookup (Assembly satellite, string name) inline private
Definition at line 85 of file RuntimeLicenseContext.cs.
    {
        CompareInfo compareInfo = CultureInfo.InvariantCulture.CompareInfo;
        string name2 = satellite.GetName().Name;
        string[] manifestResourceNames = satellite.GetManifestResourceNames();
        foreach (string text in manifestResourceNames)
        {
            if (compareInfo.Compare(text, name, CompareOptions.IgnoreCase) == 0 || compareInfo.Compare(text, name2 + ".exe.licenses") == 0 || compareInfo.Compare(text, name2 + ".dll.licenses") == 0)
            {
                name = text;
                break;
            }
        }
        return satellite.GetManifestResourceStream(name);
    }
References System.Reflection.Assembly.GetManifestResourceNames(), System.Reflection.Assembly.GetName(), System.Globalization.CultureInfo.InvariantCulture, System.Reflection.AssemblyName.Name, and System.text.
Referenced by System.ComponentModel.Design.RuntimeLicenseContext.GetSavedLicenseKey().