Terraria: System.ComponentModel.Design.RuntimeLicenseContext.GetSavedLicenseKey
GetSavedLicenseKey() [1/2]
override string System.ComponentModel.Design.RuntimeLicenseContext.GetSavedLicenseKey (Type type, Assembly resourceAssembly) inline
Definition at line 14 of file RuntimeLicenseContext.cs.
    {
        if (_savedLicenseKeys == null || _savedLicenseKeys[type.AssemblyQualifiedName] == null)
        {
            if (_savedLicenseKeys == null)
            {
                _savedLicenseKeys = new Hashtable();
            }
            if (resourceAssembly == null)
            {
                resourceAssembly = Assembly.GetEntryAssembly();
            }
            if (resourceAssembly == null)
            {
                Assembly[] assemblies = AppDomain.CurrentDomain.GetAssemblies();
                foreach (Assembly assembly in assemblies)
                {
                    string location = assembly.Location;
                    if (!(location == string.Empty))
                    {
                        string name = new FileInfo(location).Name;
                        Stream stream = assembly.GetManifestResourceStream(name + ".licenses");
                        if (stream == null)
{
                            stream = CaseInsensitiveManifestResourceStreamLookup(assembly, name + ".licenses");
                        }
                        if (stream != null)
{
                            DesigntimeLicenseContextSerializer.Deserialize(stream, name.ToUpperInvariant(), this);
                            break;
                        }
                    }
                }
            }
            else
            {
                string location2 = resourceAssembly.Location;
                if (location2 != string.Empty)
                {
                    string fileName = Path.GetFileName(location2);
                    string text = fileName + ".licenses";
                    Stream manifestResourceStream = resourceAssembly.GetManifestResourceStream(text);
                    if (manifestResourceStream == null)
                    {
                        string text2 = null;
                        CompareInfo compareInfo = CultureInfo.InvariantCulture.CompareInfo;
                        string name2 = resourceAssembly.GetName().Name;
                        string[] manifestResourceNames = resourceAssembly.GetManifestResourceNames();
                        foreach (string text3 in manifestResourceNames)
{
                            if (compareInfo.Compare(text3, text, CompareOptions.IgnoreCase) == 0 || compareInfo.Compare(text3, name2 + ".exe.licenses", CompareOptions.IgnoreCase) == 0 || compareInfo.Compare(text3, name2 + ".dll.licenses", CompareOptions.IgnoreCase) == 0)
{
                                text2 = text3;
                                break;
                            }
                        }
                        if (text2 != null)
{
                            manifestResourceStream = resourceAssembly.GetManifestResourceStream(text2);
                        }
                    }
                    if (manifestResourceStream != null)
                    {
                        DesigntimeLicenseContextSerializer.Deserialize(manifestResourceStream, fileName.ToUpperInvariant(), this);
                    }
                }
            }
        }
        return (string)_savedLicenseKeys[type.AssemblyQualifiedName];
    }
References System.ComponentModel.Design.RuntimeLicenseContext._savedLicenseKeys, System.ComponentModel.Design.RuntimeLicenseContext.CaseInsensitiveManifestResourceStreamLookup(), System.AppDomain.CurrentDomain, System.ComponentModel.Design.DesigntimeLicenseContextSerializer.Deserialize(), System.Reflection.Assembly.GetEntryAssembly(), System.IO.Path.GetFileName(), System.Reflection.Assembly.GetManifestResourceNames(), System.Reflection.Assembly.GetManifestResourceStream(), System.Reflection.Assembly.GetName(), System.Globalization.CultureInfo.InvariantCulture, System.Reflection.Assembly.Location, System.IO.FileSystemInfo.Name, System.Reflection.AssemblyName.Name, System.stream, System.text, and System.type.