Terraria: ABasicParticle.SetBasicInfo
SetBasicInfo()
virtual void ABasicParticle.SetBasicInfo (Asset< Texture2D > textureAsset, Rectangle? frame, Vector2 initialVelocity, Vector2 initialLocalPosition) inline virtual inherited
Reimplemented in FlameParticle.
     {
         _texture = textureAsset;
         _frame = (frame.HasValue ? frame.Value : _texture.Frame());
         _origin = _frame.Size() / 2f;
         Velocity = initialVelocity;
         LocalPosition = initialLocalPosition;
         ShouldBeRemovedFromRenderer = false;
     }
References ABasicParticle._frame, ABasicParticle._origin, ABasicParticle._texture, ABasicParticle.LocalPosition, ABasicParticle.ShouldBeRemovedFromRenderer, and ABasicParticle.Velocity.
Referenced by ParticleOrchestrator.Spawn_BlackLightningHit(), ParticleOrchestrator.Spawn_BlackLightningSmall(), ParticleOrchestrator.Spawn_Keybrand(), and ParticleOrchestrator.Spawn_ShimmerBlock().