Terraria: System.Xml.Serialization.Accessor.UnescapeName
UnescapeName()
static string System.Xml.Serialization.Accessor.UnescapeName (string name) inline static package inherited
Definition at line 191 of file Accessor.cs.
    {
        return XmlConvert.DecodeName(name);
    }
References System.Xml.XmlConvert.DecodeName().
Referenced by System.Xml.Serialization.XmlSerializationCodeGen.GenerateTypedSerializer(), System.Xml.Serialization.XmlSerializationILGen.GenerateTypedSerializer(), System.Xml.Serialization.XmlSchemaImporter.ImportAttributeMember(), System.Xml.Serialization.XmlSchemaImporter.ImportElement(), System.Xml.Serialization.XmlSchemaImporter.ImportElementMember(), System.Xml.Serialization.XmlSchemaImporter.ImportEnumeratedChoice(), System.Xml.Serialization.XmlSchemaImporter.ImportEnumeratedDataType(), System.Xml.Serialization.XmlSchemaImporter.ImportMembersMapping(), System.Xml.Serialization.XmlSchemaImporter.ImportStructDataType(), System.Xml.Serialization.XmlSchemaImporter.ImportStructType(), System.Xml.Serialization.XmlSchemaImporter.ImportSubstitutionGroupMember(), and System.Xml.Serialization.XmlSchemaImporter.IsCyclicReferencedType().