Terraria: CultistRitual.CheckRitual
CheckRitual()
static bool CultistRitual.CheckRitual (int x, int y) inline static private
     {
         if (delay != 0 || !Main.hardMode || !NPC.downedGolemBoss || !NPC.downedBoss3)
         {
             return false;
         }
         if (y < 7 || WorldGen.SolidTile(Main.tile[x, y - 7]))
         {
             return false;
         }
         if (NPC.AnyNPCs(437))
         {
             return false;
         }
         Vector2 center = new Vector2(x * 16 + 8, y * 16 - 64 - 8 - 27);
         Point[] spawnPoints = null;
         if (!CheckFloor(center, out spawnPoints))
         {
             return false;
         }
         return true;
     }
References NPC.AnyNPCs(), CheckFloor(), delay, NPC.downedBoss3, NPC.downedGolemBoss, Main.hardMode, WorldGen.SolidTile(), and Main.tile.
Referenced by TrySpawning().