Terraria: CultistRitual.UpdateTime
UpdateTime()
static void CultistRitual.UpdateTime () inline static
     {
         if (Main.netMode == 1)
         {
             return;
         }
         delay -= Main.dayRate;
         if (delay < 0)
         {
             delay = 0;
         }
         recheck -= Main.dayRate;
         if (recheck < 0)
         {
             recheck = 0;
         }
         if (delay == 0 && recheck == 0)
         {
             recheck = 600;
             if (NPC.AnyDanger())
             {
                 recheck *= 6;
             }
             else
             {
                 TrySpawning(Main.dungeonX, Main.dungeonY);
             }
         }
     }
References NPC.AnyDanger(), Main.dayRate, delay, Main.dungeonX, Main.dungeonY, Main.netMode, recheck, and TrySpawning().
Referenced by Main.UpdateTime().