Terraria: System.Xml.Serialization.Accessor.EscapeQName
EscapeQName()
static string System.Xml.Serialization.Accessor.EscapeQName (string name) inline static package inherited
Definition at line 172 of file Accessor.cs.
    {
        if (name == null || name.Length == 0)
        {
            return name;
        }
        int num = name.LastIndexOf(':');
        if (num < 0)
        {
            return XmlConvert.EncodeLocalName(name);
        }
        if (num == 0 || num == name.Length - 1)
        {
            throw new ArgumentException(System.SR.Format(System.SR.Xml_InvalidNameChars, name), "name");
        }
        return new XmlQualifiedName(XmlConvert.EncodeLocalName(name.Substring(num + 1)), XmlConvert.EncodeLocalName(name.Substring(0, num))).ToString();
    }
References System.Xml.ArgumentException, System.Xml.XmlConvert.EncodeLocalName(), System.SR.Format(), System.Xml.XmlQualifiedName.ToString(), and System.SR.Xml_InvalidNameChars.
Referenced by System.Xml.Serialization.SoapReflectionImporter.ImportAccessorMapping(), and System.Xml.Serialization.XmlReflectionImporter.ImportAccessorMapping().