Terraria: UIWorkshopHub.SetupGamepadPoints
SetupGamepadPoints()
void UIWorkshopHub.SetupGamepadPoints (SpriteBatch spriteBatch) inline private
     {
         UILinkPointNavigator.Shortcuts.BackButtonCommand = 7;
         int num = 3000;
         int idRangeEndExclusive = num;
         UILinkPoint linkPoint = _helper.GetLinkPoint(idRangeEndExclusive++, _buttonUseResourcePacks);
         UILinkPoint linkPoint2 = _helper.GetLinkPoint(idRangeEndExclusive++, _buttonPublishResourcePacks);
         UILinkPoint linkPoint3 = _helper.GetLinkPoint(idRangeEndExclusive++, _buttonImportWorlds);
         UILinkPoint linkPoint4 = _helper.GetLinkPoint(idRangeEndExclusive++, _buttonPublishWorlds);
         UILinkPoint linkPoint5 = _helper.GetLinkPoint(idRangeEndExclusive++, _buttonBack);
         UILinkPoint linkPoint6 = _helper.GetLinkPoint(idRangeEndExclusive++, _buttonLogs);
         _helper.PairLeftRight(linkPoint3, linkPoint);
         _helper.PairLeftRight(linkPoint4, linkPoint2);
         _helper.PairLeftRight(linkPoint5, linkPoint6);
         _helper.PairUpDown(linkPoint3, linkPoint4);
         _helper.PairUpDown(linkPoint, linkPoint2);
         _helper.PairUpDown(linkPoint4, linkPoint5);
         _helper.PairUpDown(linkPoint2, linkPoint6);
         _helper.MoveToVisuallyClosestPoint(num, idRangeEndExclusive);
     }
References _buttonBack, _buttonImportWorlds, _buttonLogs, _buttonPublishResourcePacks, _buttonPublishWorlds, _buttonUseResourcePacks, _helper, UILinkPointNavigator.Shortcuts.BackButtonCommand, UIGamepadHelper.GetLinkPoint(), UIGamepadHelper.MoveToVisuallyClosestPoint(), UIGamepadHelper.PairLeftRight(), and UIGamepadHelper.PairUpDown().
Referenced by Draw().