Terraria: UIWorkshopHub.ShowOptionDescription
ShowOptionDescription()
void UIWorkshopHub.ShowOptionDescription (UIMouseEvent evt, UIElement listeningElement) inline
     {
         LocalizedText localizedText = null;
         if (listeningElement == _buttonUseResourcePacks)
         {
             localizedText = Language.GetText("Workshop.HubDescriptionUseResourcePacks");
         }
         if (listeningElement == _buttonPublishResourcePacks)
         {
             localizedText = Language.GetText("Workshop.HubDescriptionPublishResourcePacks");
         }
         if (listeningElement == _buttonImportWorlds)
         {
             localizedText = Language.GetText("Workshop.HubDescriptionImportWorlds");
         }
         if (listeningElement == _buttonPublishWorlds)
         {
             localizedText = Language.GetText("Workshop.HubDescriptionPublishWorlds");
         }
         if (localizedText != null)
         {
             _descriptionText.SetText(localizedText);
         }
     }
References _buttonImportWorlds, _buttonPublishResourcePacks, _buttonPublishWorlds, _buttonUseResourcePacks, _descriptionText, Language.GetText(), and UIText.SetText().
Referenced by MakeFancyButton().