Terraria: System.Xml.Xsl.XPath.XPathQilFactory.ConvertToType
ConvertToType()
QilNode System.Xml.Xsl.XPath.XPathQilFactory.ConvertToType (XmlTypeCode requiredType, QilNode n) inline inherited
Definition at line 102 of file XPathQilFactory.cs.
    {
        return requiredType switch
        {
            XmlTypeCode.String => ConvertToString(n),
            XmlTypeCode.Double => ConvertToNumber(n),
            XmlTypeCode.Boolean => ConvertToBoolean(n),
            XmlTypeCode.Node => EnsureNodeSet(n),
            XmlTypeCode.Item => n,
            _ => null,
        };
    }
References System.Xml.Xsl.XPath.XPathQilFactory.ConvertToBoolean(), System.Xml.Xsl.XPath.XPathQilFactory.ConvertToNumber(), System.Xml.Xsl.XPath.XPathQilFactory.ConvertToString(), System.Xml.Dictionary, and System.Xml.Xsl.XPath.XPathQilFactory.EnsureNodeSet().
Referenced by System.Xml.Xsl.XPath.XPathBuilder.FunctionInfo< T >.CastArguments(), and System.Xml.Xsl.XPath.XPathBuilder.CompareValues().