Terraria: System.Xml.Xsl.XPath.XPathQilFactory.Id
Id()
QilNode System.Xml.Xsl.XPath.XPathQilFactory.Id (QilNode context, QilNode id) inline inherited
Definition at line 249 of file XPathQilFactory.cs.
    {
        if (id.XmlType.IsSingleton)
        {
            return Deref(context, ConvertToString(id));
        }
        QilIterator n;
        return Loop(n = For(id), Deref(context, ConvertToString(n)));
    }
References System.Xml.Xsl.XPath.XPathQilFactory.ConvertToString(), System.Xml.Xsl.Qil.Deref, System.Xml.Dictionary, System.Xml.Xsl.Qil.For, and System.Xml.Xsl.Qil.Loop.
Referenced by System.Xml.Xsl.XPath.XPathBuilder.Function(), and System.Xml.Xsl.Xslt.XPathPatternBuilder.Function().