Terraria: System.Xml.Xsl.XPath.XPathQilFactory.FirstNode
FirstNode()
QilIterator System.Xml.Xsl.XPath.XPathQilFactory.FirstNode (QilNode n) inline inherited
Definition at line 24 of file XPathQilFactory.cs.
    {
        QilIterator qilIterator = For(DocOrderDistinct(n));
        return For(Filter(qilIterator, Eq(PositionOf(qilIterator), Int32(1))));
    }
References System.Xml.Dictionary, System.Xml.Xsl.Qil.DocOrderDistinct, System.Xml.Xsl.XPath.Eq, System.Xml.Xsl.Qil.Filter, System.Xml.Xsl.Qil.For, System.Xml.Int32, and System.Xml.Xsl.Qil.PositionOf.
Referenced by System.Xml.Xsl.Xslt.QilGenerator.CompileGenerateId(), System.Xml.Xsl.Xslt.QilGenerator.CompileSingleDocument(), System.Xml.Xsl.XPath.XPathBuilder.LocalNameOfFirstNode(), System.Xml.Xsl.XPath.XPathBuilder.NameOfFirstNode(), and System.Xml.Xsl.XPath.XPathBuilder.NamespaceOfFirstNode().