Terraria: Terraria.Utilities.UnifiedRandom.InternalSample
InternalSample()
int Terraria.Utilities.UnifiedRandom.InternalSample () inline private
    {
        int num = inext;
        int num2 = inextp;
        if (++num >= 56)
        {
            num = 1;
        }
        if (++num2 >= 56)
        {
            num2 = 1;
        }
        int num3 = SeedArray[num] - SeedArray[num2];
        if (num3 == int.MaxValue)
        {
            num3--;
        }
        if (num3 < 0)
        {
            num3 += int.MaxValue;
        }
        SeedArray[num] = num3;
        inext = num;
        inextp = num2;
        return num3;
    }
References Terraria.Utilities.UnifiedRandom.inext, Terraria.Utilities.UnifiedRandom.inextp, and Terraria.Utilities.UnifiedRandom.SeedArray.
Referenced by Terraria.Utilities.UnifiedRandom.GetSampleForLargeRange(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Utilities.UnifiedRandom.NextBytes(), and Terraria.Utilities.UnifiedRandom.Sample().