Terraria: System.Xml.Xsl.XPath.XPathQilFactory.SafeDocOrderDistinct
SafeDocOrderDistinct()
QilNode System.Xml.Xsl.XPath.XPathQilFactory.SafeDocOrderDistinct (QilNode n) inline inherited
Definition at line 46 of file XPathQilFactory.cs.
    {
        XmlQueryType xmlType = n.XmlType;
        if (xmlType.MaybeMany)
        {
            if (xmlType.IsNode && xmlType.IsNotRtf)
            {
                return DocOrderDistinct(n);
            }
            QilIterator qilIterator;
            if (!xmlType.IsAtomicValue)
            {
                return Loop(qilIterator = Let(n), Conditional(Gt(Length(qilIterator), Int32(1)), DocOrderDistinct(TypeAssert(qilIterator, XmlQueryTypeFactory.NodeNotRtfS)), qilIterator));
            }
        }
        return n;
    }
References System.Xml.Xsl.Qil.Conditional, System.Xml.Dictionary, System.Xml.Xsl.Qil.DocOrderDistinct, System.Xml.Xsl.XPath.Gt, System.Xml.Int32, System.Xml.Xsl.XmlQueryType.IsAtomicValue, System.Xml.Xsl.XmlQueryType.IsNode, System.Xml.Xsl.XmlQueryType.IsNotRtf, System.Xml.Schema.Length, System.Xml.Xsl.Qil.Let, System.Xml.Xsl.Qil.Loop, System.Xml.Xsl.XmlQueryType.MaybeMany, System.Xml.Xsl.XmlQueryTypeFactory.NodeNotRtfS, and System.Xml.Xsl.Qil.TypeAssert.
Referenced by System.Xml.Xsl.XPath.XPathQilFactory.ConvertToNumber(), System.Xml.Xsl.XPath.XPathQilFactory.ConvertToString(), and System.Xml.Xsl.Xslt.QilGenerator.ResolveFunction().