Terraria: System.Xml.Xsl.XPath.XPathQilFactory.TryEnsureNodeSet
TryEnsureNodeSet()
QilNode System.Xml.Xsl.XPath.XPathQilFactory.TryEnsureNodeSet (QilNode n) inline inherited
Definition at line 221 of file XPathQilFactory.cs.
    {
        if (n.XmlType.IsNode && n.XmlType.IsNotRtf)
        {
            return n;
        }
        if (CannotBeNodeSet(n))
        {
            return null;
        }
        return InvokeEnsureNodeSet(n);
    }
References System.Xml.Xsl.XPath.XPathQilFactory.CannotBeNodeSet(), System.Xml.Dictionary, and System.Xml.Xsl.XPath.XPathQilFactory.InvokeEnsureNodeSet().
Referenced by System.Xml.Xsl.Xslt.QilGenerator.CompileNodeSetExpression(), and System.Xml.Xsl.XPath.XPathQilFactory.EnsureNodeSet().