Terraria: System.Xml.Xsl.XPath.XPathQilFactory.ConvertToString
ConvertToString()
QilNode System.Xml.Xsl.XPath.XPathQilFactory.ConvertToString (QilNode n) inline inherited
Definition at line 115 of file XPathQilFactory.cs.
    {
        switch (n.XmlType.TypeCode)
        {
        case XmlTypeCode.Boolean:
            if (n.NodeType != QilNodeType.True)
            {
                if (n.NodeType != QilNodeType.False)
                {
                    return Conditional(n, String("true"), String("false"));
                }
                return String("false");
            }
            return String("true");
        case XmlTypeCode.Double:
            if (n.NodeType != QilNodeType.LiteralDouble)
            {
                return XsltConvert(n, XmlQueryTypeFactory.StringX);
            }
            return String(XPathConvert.DoubleToString((QilLiteral)n));
        case XmlTypeCode.String:
            return n;
        default:
            if (n.XmlType.IsNode)
            {
                return XPathNodeValue(SafeDocOrderDistinct(n));
            }
            return XsltConvert(n, XmlQueryTypeFactory.StringX);
        }
    }
References System.Xml.Xsl.Qil.Conditional, System.Xml.Dictionary, System.Xml.Xsl.XPathConvert.DoubleToString(), System.Xml.Xsl.XPath.XPathQilFactory.SafeDocOrderDistinct(), System.Xml.Xsl.XPath.String, System.Xml.Xsl.XmlQueryTypeFactory.StringX, System.Xml.Xsl.Qil.XPathNodeValue, and System.Xml.Xsl.Qil.XsltConvert.
Referenced by System.Xml.Xsl.Xslt.QilGenerator.CompileAvt(), System.Xml.Xsl.Xslt.QilGenerator.CompileCopyOf(), System.Xml.Xsl.Xslt.QilGenerator.CompileDataTypeAttribute(), System.Xml.Xsl.Xslt.QilGenerator.CompileFnDocument(), System.Xml.Xsl.Xslt.QilGenerator.CompileFnKey(), System.Xml.Xsl.Xslt.QilGenerator.CompileKeys(), System.Xml.Xsl.Xslt.QilGenerator.CompileSort(), System.Xml.Xsl.Xslt.QilGenerator.CompileValueOf(), System.Xml.Xsl.Xslt.QilGenerator.CompileValueOfDoe(), System.Xml.Xsl.XPath.XPathQilFactory.ConvertToType(), System.Xml.Xsl.XPath.XPathBuilder.Function(), System.Xml.Xsl.Xslt.QilGenerator.GenerateScriptCall(), System.Xml.Xsl.XPath.XPathQilFactory.Id(), and System.Xml.Xsl.Xslt.QilGenerator.ResolveFunction().