Terraria: System.Xml.Xsl.XPath.XPathQilFactory.ConvertToNumber
ConvertToNumber()
QilNode System.Xml.Xsl.XPath.XPathQilFactory.ConvertToNumber (QilNode n) inline inherited
Definition at line 176 of file XPathQilFactory.cs.
    {
        switch (n.XmlType.TypeCode)
        {
        case XmlTypeCode.Boolean:
            if (n.NodeType != QilNodeType.True)
            {
                if (n.NodeType != QilNodeType.False)
                {
                    return Conditional(n, Double(1.0), Double(0.0));
                }
                return Double(0.0);
            }
            return Double(1.0);
        case XmlTypeCode.Double:
            return n;
        case XmlTypeCode.String:
            return XsltConvert(n, XmlQueryTypeFactory.DoubleX);
        default:
            if (n.XmlType.IsNode)
            {
                return XsltConvert(XPathNodeValue(SafeDocOrderDistinct(n)), XmlQueryTypeFactory.DoubleX);
            }
            return XsltConvert(n, XmlQueryTypeFactory.DoubleX);
        }
    }
References System.Xml.Xsl.Qil.Conditional, System.Xml.Dictionary, System.Xml.Double, System.Xml.Xsl.XmlQueryTypeFactory.DoubleX, System.Xml.Xsl.XPath.XPathQilFactory.SafeDocOrderDistinct(), System.Xml.Xsl.Qil.XPathNodeValue, and System.Xml.Xsl.Qil.XsltConvert.
Referenced by System.Xml.Xsl.XPath.XPathBuilder.ArithmeticOperator(), System.Xml.Xsl.Xslt.QilGenerator.CompileDataTypeAttribute(), System.Xml.Xsl.Xslt.QilGenerator.CompileGroupingSizeAttribute(), System.Xml.Xsl.Xslt.QilGenerator.CompileNumber(), System.Xml.Xsl.XPath.XPathQilFactory.ConvertToType(), System.Xml.Xsl.XPath.XPathBuilder.Function(), System.Xml.Xsl.Xslt.QilGenerator.GenerateScriptCall(), System.Xml.Xsl.XPath.XPathBuilder.NegateOperator(), and System.Xml.Xsl.XPath.XPathBuilder.Sum().