Terraria: Terraria.Utilities.UnifiedRandom.NextDouble
NextDouble()
virtual double Terraria.Utilities.UnifiedRandom.NextDouble () inline virtual
    {
        return Sample();
    }
References Terraria.Utilities.UnifiedRandom.Sample().
Referenced by Terraria.Projectile.AI_001(), Terraria.Projectile.AI_062(), Terraria.Projectile.AI_075(), Terraria.Projectile.AI_178_FireExplosion(), Terraria.Player.DropAnglerAccByMissing(), Terraria.GameContent.Biomes.Desert.DesertHive.ClusterGroup.Generate(), Terraria.GameContent.Skies.SlimeSky.GenerateSlimes(), Terraria.GameContent.Skies.MartianSky.GenerateUfos(), Terraria.WorldGen.GenerateWorld(), Terraria.Utilities.WeightedRandom< T >.Get(), Terraria.Player.GetAnglerReward_MainReward(), Terraria.GameContent.Skies.MartianSky.ZipBehavior.InitializeUfo(), Terraria.GameContent.Skies.MartianSky.HoverBehavior.InitializeUfo(), Terraria.Player.ItemCheck_Shoot(), Terraria.Projectile.Kill(), Terraria.WorldGen.MarblePileWithStatues(), Terraria.WorldGen.neonMossBiome(), Terraria.WorldGen.OrePatch(), Terraria.GameContent.Biomes.CaveHouse.HouseBuilder.PlaceChests(), Terraria.WorldGen.PlaceOasis(), Terraria.Utils.RandomVector2(), Terraria.Utils.RandomVector2D(), Terraria.GameContent.Skies.PartySky.ResetBalloon(), Terraria.GameContent.Skies.LanternSky.ResetLantern(), Terraria.WorldGen.ShellPile(), Terraria.WorldGen.StonePatch(), Terraria.GameContent.RGB.EyeballShader.Update(), Terraria.GameContent.Skies.SlimeSky.Update(), and Terraria.Projectile.Update().