Terraria: System.Xml.Xsl.XPath.XPathQilFactory.ConvertToBoolean
ConvertToBoolean()
QilNode System.Xml.Xsl.XPath.XPathQilFactory.ConvertToBoolean (QilNode n) inline inherited
Definition at line 146 of file XPathQilFactory.cs.
    {
        switch (n.XmlType.TypeCode)
        {
        case XmlTypeCode.Boolean:
            return n;
        case XmlTypeCode.Double:
        {
            QilIterator qilIterator;
            if (n.NodeType != QilNodeType.LiteralDouble)
            {
                return Loop(qilIterator = Let(n), Or(Lt(qilIterator, Double(0.0)), Lt(Double(0.0), qilIterator)));
            }
            return Boolean((double)(QilLiteral)n < 0.0 || 0.0 < (double)(QilLiteral)n);
        }
        case XmlTypeCode.String:
            if (n.NodeType != QilNodeType.LiteralString)
            {
                return Ne(StrLength(n), Int32(0));
            }
            return Boolean(((string)(QilLiteral)n).Length != 0);
        default:
            if (n.XmlType.IsNode)
            {
                return Not(IsEmpty(n));
            }
            return XsltConvert(n, XmlQueryTypeFactory.BooleanX);
        }
    }
References System.Xml.Xsl.Boolean, System.Xml.Xsl.XmlQueryTypeFactory.BooleanX, System.Xml.Dictionary, System.Xml.Double, System.Xml.Int32, System.Xml.Xsl.Qil.IsEmpty, System.Xml.Schema.Length, System.Xml.Xsl.Qil.Let, System.Xml.Xsl.Qil.Loop, System.Xml.Xsl.XPath.Lt, System.Xml.Xsl.XPath.Ne, System.Xml.Xsl.Qil.Not, System.Xml.Xsl.XPath.Or, System.Xml.Xsl.Qil.StrLength, and System.Xml.Xsl.Qil.XsltConvert.
Referenced by System.Xml.Xsl.Xslt.QilGenerator.CompileWhen(), System.Xml.Xsl.XPath.XPathQilFactory.ConvertToType(), System.Xml.Xsl.XPath.XPathBuilder.Function(), System.Xml.Xsl.Xslt.QilGenerator.GenerateScriptCall(), System.Xml.Xsl.XPath.XPathBuilder.LogicalOperator(), and System.Xml.Xsl.XPath.XPathBuilder.PredicateToBoolean().