Terraria: System.Xml.Xsl.Xslt.XPathPatternBuilder.BuildPredicates
BuildPredicates()
QilNode System.Xml.Xsl.Xslt.XPathPatternBuilder.BuildPredicates (QilNode nodeset, List< QilNode > predicates) inline
Definition at line 239 of file XPathPatternBuilder.cs.
    {
        List<QilNode> list = new List<QilNode>(predicates.Count);
        foreach (QilNode predicate in predicates)
        {
            list.Add(XPathBuilder.PredicateToBoolean(predicate, _f, _predicateEnvironment));
        }
        QilLoop qilLoop = (QilLoop)nodeset;
        QilIterator variable = qilLoop.Variable;
        if (_predicateEnvironment.numFixupLast == 0 && _predicateEnvironment.numFixupPosition == 0)
        {
            foreach (QilNode item in list)
            {
                qilLoop.Body = _f.And(qilLoop.Body, item);
            }
            qilLoop.Body = _predicateEnvironment.fixupVisitor.Fixup(qilLoop.Body, variable, null);
        }
        else
        {
            QilIterator qilIterator = _f.For(_f.Parent(variable));
            QilNode binding = _f.Content(qilIterator);
            QilLoop qilLoop2 = (QilLoop)nodeset.DeepClone(_f.BaseFactory);
            qilLoop2.Variable.Binding = binding;
            qilLoop2 = (QilLoop)_f.Loop(qilIterator, qilLoop2);
            QilNode qilNode = qilLoop2;
            foreach (QilNode item2 in list)
            {
                qilNode = XPathBuilder.BuildOnePredicate(qilNode, item2, isReverseStep: false, _f, _predicateEnvironment.fixupVisitor, ref _predicateEnvironment.numFixupCurrent, ref _predicateEnvironment.numFixupPosition, ref _predicateEnvironment.numFixupLast);
            }
            QilIterator qilIterator2 = _f.For(qilNode);
            QilNode set = _f.Filter(qilIterator2, _f.Is(qilIterator2, variable));
            qilLoop.Body = _f.Not(_f.IsEmpty(set));
            qilLoop.Body = _f.And(_f.IsType(variable, qilLoop.XmlType), qilLoop.Body);
        }
        SetPriority(nodeset, 0.5);
        return nodeset;
    }
References System.Xml.Xsl.Xslt.XPathPatternBuilder._f, System.Xml.Xsl.Xslt.XPathPatternBuilder._predicateEnvironment, System.Xml.Xsl.Qil.QilPatternFactory.And(), System.Xml.Xsl.Qil.QilPatternFactory.BaseFactory, System.Xml.Xsl.XPath.XPathBuilder.BuildOnePredicate(), System.Xml.Xsl.Qil.QilPatternFactory.Content(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Xml.Dictionary, System.Xml.Xsl.Qil.QilPatternFactory.Filter(), System.Xml.Xsl.Xslt.XPathPatternBuilder.XPathPredicateEnvironment.fixupVisitor, System.Xml.Xsl.Qil.QilPatternFactory.For(), System.Xml.Xsl.Qil.QilPatternFactory.Is(), System.Xml.Xsl.Qil.QilPatternFactory.IsEmpty(), System.Xml.Xsl.Qil.QilPatternFactory.IsType(), System.item, System.list, System.Xml.Xsl.Qil.QilPatternFactory.Loop(), System.Xml.Xsl.Qil.QilPatternFactory.Not(), System.Xml.Xsl.Xslt.XPathPatternBuilder.XPathPredicateEnvironment.numFixupCurrent, System.Xml.Xsl.Xslt.XPathPatternBuilder.XPathPredicateEnvironment.numFixupLast, System.Xml.Xsl.Xslt.XPathPatternBuilder.XPathPredicateEnvironment.numFixupPosition, System.Xml.Xsl.Qil.QilPatternFactory.Parent(), System.Xml.Xsl.XPath.XPathBuilder.PredicateToBoolean(), and System.Xml.Xsl.Xslt.XPathPatternBuilder.SetPriority().