Terraria: System.Xml.Xsl.Xslt.XPathPatternBuilder.Axis
Axis() [3/3]
QilNode System.Xml.Xsl.Xslt.XPathPatternBuilder.Axis (XPathAxis xpathAxis, XPathNodeType nodeType, string prefix, string name) inline
Definition at line 169 of file XPathPatternBuilder.cs.
    {
        QilLoop qilLoop;
        double priority;
        switch (xpathAxis)
        {
        case XPathAxis.DescendantOrSelf:
            return _f.Nop(_fixupNode);
        case XPathAxis.Root:
        {
            QilIterator expr;
            qilLoop = _f.BaseFactory.Filter(expr = _f.For(_fixupNode), _f.IsType(expr, XmlQueryTypeFactory.Document));
            priority = 0.5;
            break;
        }
        default:
        {
            string nsUri = ((prefix == null) ? null : _environment.ResolvePrefix(prefix));
            qilLoop = BuildAxisFilter(_f, _f.For(_fixupNode), xpathAxis, nodeType, name, nsUri);
            switch (nodeType)
            {
            case XPathNodeType.Element:
            case XPathNodeType.Attribute:
                priority = ((name == null) ? ((prefix == null) ? (-0.5) : (-0.25)) : 0.0);
                break;
            case XPathNodeType.ProcessingInstruction:
                priority = ((name != null) ? 0.0 : (-0.5));
                break;
            default:
                priority = -0.5;
                break;
            }
            break;
        }
        }
        SetPriority(qilLoop, priority);
        SetLastParent(qilLoop, qilLoop);
        return qilLoop;
    }
References System.Xml.Xsl.Xslt.XPathPatternBuilder._environment, System.Xml.Xsl.Xslt.XPathPatternBuilder._f, System.Xml.Xsl.Xslt.XPathPatternBuilder._fixupNode, System.Xml.Xsl.Qil.QilPatternFactory.BaseFactory, System.Xml.Xsl.Xslt.XPathPatternBuilder.BuildAxisFilter(), System.Xml.Dictionary, System.Xml.Xsl.XmlQueryTypeFactory.Document, System.Xml.Xsl.Qil.QilFactory.Filter(), System.Xml.Xsl.Qil.QilPatternFactory.For(), System.Xml.Xsl.Qil.QilPatternFactory.IsType(), System.Xml.Xsl.Qil.QilPatternFactory.Nop(), System.prefix, System.Xml.Xsl.XPath.IXPathEnvironment.ResolvePrefix(), System.Xml.Xsl.Xslt.XPathPatternBuilder.SetLastParent(), and System.Xml.Xsl.Xslt.XPathPatternBuilder.SetPriority().