Terraria: System.Xml.Xsl.Xslt.XPathPatternBuilder.SetPriority
SetPriority()
static void System.Xml.Xsl.Xslt.XPathPatternBuilder.SetPriority (QilNode node, double priority) inline static
Definition at line 303 of file XPathPatternBuilder.cs.
    {
        Annotation annotation = ((Annotation)node.Annotation) ?? new Annotation();
        annotation.Priority = priority;
        node.Annotation = annotation;
    }
References System.Xml.Dictionary.
Referenced by System.Xml.Xsl.Xslt.XPathPatternBuilder.Axis(), System.Xml.Xsl.Xslt.XPathPatternBuilder.BuildPredicates(), System.Xml.Xsl.Xslt.QilGenerator.CompileMatchPattern(), System.Xml.Xsl.Xslt.XPathPatternBuilder.Function(), and System.Xml.Xsl.Xslt.XPathPatternBuilder.JoinStep().