Terraria: TELogicSensor.ChangeState
ChangeState()
void TELogicSensor.ChangeState (bool onState, bool TripWire) inline
     {
         if (onState == On || SanityCheck(Position.X, Position.Y))
         {
             Main.tile[Position.X, Position.Y].frameX = (short)(onState ? 18 : 0);
             On = onState;
             if (Main.netMode == 2)
             {
                 NetMessage.SendTileSquare(-1, Position.X, Position.Y);
             }
             if (TripWire && Main.netMode != 1)
             {
                 tripPoints.Add(Tuple.Create(Position, logicCheck == LogicCheckType.PlayerAbove));
             }
         }
     }
References Tile.frameX, logicCheck, Main.netMode, On, TileEntity.Position, SanityCheck(), NetMessage.SendTileSquare(), Main.tile, tripPoints, Point16.X, and Point16.Y.
Referenced by Update().