Terraria: TELogicSensor.Place
Place()
static int TELogicSensor.Place (int x, int y) inline static
     {
         TELogicSensor tELogicSensor = new TELogicSensor();
         tELogicSensor.Position = new Point16(x, y);
         tELogicSensor.ID = TileEntity.AssignNewID();
         tELogicSensor.type = _myEntityID;
         lock (TileEntity.EntityCreationLock)
         {
             TileEntity.ByID[tELogicSensor.ID] = tELogicSensor;
             TileEntity.ByPosition[tELogicSensor.Position] = tELogicSensor;
         }
         return tELogicSensor.ID;
     }
References TELogicSensor(), _myEntityID, TileEntity.AssignNewID(), TileEntity.ByID, TileEntity.ByPosition, TileEntity.EntityCreationLock, TileEntity.ID, TileEntity.Position, and TileEntity.type.
Referenced by Hook_AfterPlacement(), and NetPlaceEntity().