Terraria: TELogicSensor.UpdateEndInternal
UpdateEndInternal()
static void TELogicSensor.UpdateEndInternal () inline static private
     {
         inUpdateLoop = false;
         foreach (Tuple<Point16, bool> tripPoint in tripPoints)
         {
             Wiring.blockPlayerTeleportationForOneIteration = tripPoint.Item2;
             Wiring.HitSwitch(tripPoint.Item1.X, tripPoint.Item1.Y);
             if (Main.netMode == 2)
             {
                 NetMessage.SendData(59, -1, -1, null, tripPoint.Item1.X, tripPoint.Item1.Y);
             }
         }
         Wiring.blockPlayerTeleportationForOneIteration = false;
         tripPoints.Clear();
         foreach (int item in markedIDsForRemoval)
         {
             if (TileEntity.ByID.TryGetValue(item, out var value) && value.type == _myEntityID)
             {
                 lock (TileEntity.EntityCreationLock)
                 {
                     TileEntity.ByID.Remove(item);
                     TileEntity.ByPosition.Remove(value.Position);
                 }
             }
         }
         markedIDsForRemoval.Clear();
     }
References _myEntityID, Wiring.blockPlayerTeleportationForOneIteration, TileEntity.ByID, TileEntity.ByPosition, TileEntity.EntityCreationLock, Wiring.HitSwitch(), inUpdateLoop, markedIDsForRemoval, Main.netMode, NetMessage.SendData(), and tripPoints.
Referenced by RegisterTileEntityID().