Terraria: TELogicSensor.Kill
Kill()
static void TELogicSensor.Kill (int x, int y) inline static
     {
         if (!TileEntity.ByPosition.TryGetValue(new Point16(x, y), out var value) || value.type != _myEntityID)
         {
             return;
         }
         Wiring.blockPlayerTeleportationForOneIteration = ((TELogicSensor)value).logicCheck == LogicCheckType.PlayerAbove;
         bool flag = false;
         if (((TELogicSensor)value).logicCheck == LogicCheckType.PlayerAbove && ((TELogicSensor)value).On)
         {
             flag = true;
         }
         else if (((TELogicSensor)value).logicCheck == LogicCheckType.Water && ((TELogicSensor)value).On)
         {
             flag = true;
         }
         else if (((TELogicSensor)value).logicCheck == LogicCheckType.Lava && ((TELogicSensor)value).On)
         {
             flag = true;
         }
         else if (((TELogicSensor)value).logicCheck == LogicCheckType.Honey && ((TELogicSensor)value).On)
         {
             flag = true;
         }
         else if (((TELogicSensor)value).logicCheck == LogicCheckType.Liquid && ((TELogicSensor)value).On)
         {
             flag = true;
         }
         if (flag)
         {
             Wiring.HitSwitch(value.Position.X, value.Position.Y);
             NetMessage.SendData(59, -1, -1, null, value.Position.X, value.Position.Y);
         }
         Wiring.blockPlayerTeleportationForOneIteration = false;
         if (inUpdateLoop)
         {
             markedIDsForRemoval.Add(value.ID);
             return;
         }
         lock (TileEntity.EntityCreationLock)
         {
             TileEntity.ByPosition.Remove(new Point16(x, y));
             TileEntity.ByID.Remove(value.ID);
         }
     }
References TELogicSensor(), _myEntityID, Wiring.blockPlayerTeleportationForOneIteration, TileEntity.ByID, TileEntity.ByPosition, TileEntity.EntityCreationLock, Wiring.HitSwitch(), inUpdateLoop, logicCheck, markedIDsForRemoval, On, and NetMessage.SendData().
Referenced by WorldGen.KillTile(), WorldGen.KillTile_GetItemDrops(), and SanityCheck().