Terraria: System.Xml.Schema.BitSet.EnsureLength
EnsureLength()
void System.Xml.Schema.BitSet.EnsureLength (int nRequiredLength) inline private
Definition at line 208 of file BitSet.cs.
    {
        if (nRequiredLength > _bits.Length)
        {
            int num = 2 * _bits.Length;
            if (num < nRequiredLength)
            {
                num = nRequiredLength;
            }
            uint[] array = new uint[num];
            Array.Copy(_bits, array, _bits.Length);
            _bits = array;
        }
    }
References System.Xml.Schema.BitSet._bits, System.array, System.Array.Copy(), and System.Xml.Dictionary.
Referenced by System.Xml.Schema.BitSet.Or(), and System.Xml.Schema.BitSet.Set().