Terraria: System.Xml.Schema.BitSet.Or
Or()
void System.Xml.Schema.BitSet.Or (BitSet other) inline
Definition at line 113 of file BitSet.cs.
    {
        if (this != other)
        {
            int num = other._bits.Length;
            EnsureLength(num);
            int num2 = num;
            while (num2-- > 0)
            {
                _bits[num2] |= other._bits[num2];
            }
        }
    }
References System.Xml.Schema.BitSet._bits, System.Xml.Dictionary, System.Xml.Schema.BitSet.EnsureLength(), and System.other.
Referenced by System.Xml.Schema.ChoiceNode.ConstructChildPos(), System.Xml.Schema.ChoiceNode.ConstructPos(), and System.Xml.Schema.ParticleContentValidator.GetApplicableMinMaxFollowPos().