Terraria: System.Collections.IEnumerable.GetEnumerator
GetEnumerator()
IEnumerator System.Collections.IEnumerable.GetEnumerator () inherited
Implemented in Microsoft.Xna.Framework.Graphics.DisplayModeCollection, Microsoft.Xna.Framework.Graphics.DisplayModeCollection, Microsoft.Xna.Framework.CurveKeyCollection, Microsoft.Xna.Framework.CurveKeyCollection, ReLogic.Peripherals.RGB.Corsair.CorsairDeviceGroup, ReLogic.Peripherals.RGB.Logitech.LogitechDeviceGroup, ReLogic.Peripherals.RGB.Razer.RazerDeviceGroup, ReLogic.Peripherals.RGB.SteelSeries.SteelSeriesDeviceGroup, ReLogic.Peripherals.RGB.HotkeyCollection, ReLogic.Peripherals.RGB.HotkeyCollection, ReLogic.Peripherals.RGB.RgbDeviceGroup, ReLogic.Peripherals.RGB.RgbDeviceGroup, ReLogic.Peripherals.RGB.VirtualRgbDeviceGroup, ReLogic.Utilities.SlotVector< T >, ReLogic.Utilities.SlotVector< T >, System.Collections.Concurrent.BlockingCollection< T >, System.Collections.Concurrent.BlockingCollection< T >, System.Collections.Concurrent.ConcurrentBag< T >, System.Collections.Concurrent.ConcurrentBag< T >, System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >, System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >, System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >, System.Collections.Concurrent.ConcurrentStack< T >, System.Collections.Concurrent.ConcurrentStack< T >, System.Collections.Concurrent.OrderablePartitioner< TSource >.EnumerableDropIndices, System.Collections.Concurrent.OrderablePartitioner< TSource >.EnumerableDropIndices, System.Collections.Concurrent.Partitioner< TSource >.DynamicPartitionerForIEnumerable< TSource >.InternalPartitionEnumerable, System.Collections.Concurrent.Partitioner< TSource >.DynamicPartitionerForIEnumerable< TSource >.InternalPartitionEnumerable, System.Collections.Concurrent.Partitioner< TSource >.DynamicPartitionerForIList< TSource >.InternalPartitionEnumerable, System.Collections.Concurrent.Partitioner< TSource >.DynamicPartitionerForIList< TSource >.InternalPartitionEnumerable, System.Collections.Concurrent.Partitioner< TSource >.DynamicPartitionerForArray< TSource >.InternalPartitionEnumerable, System.Collections.Concurrent.Partitioner< TSource >.DynamicPartitionerForArray< TSource >.InternalPartitionEnumerable, System.Collections.Immutable.ImmutableArray< T >.Builder, System.Collections.Immutable.ImmutableArray< T >.Builder, System.Collections.Immutable.ImmutableArray< T >.Builder, System.Collections.Immutable.ImmutableArray< T >, System.Collections.Immutable.ImmutableArray< T >, System.Collections.Immutable.ImmutableArray< T >, System.Collections.Immutable.ImmutableDictionary< TKey, TValue >.Builder, System.Collections.Immutable.ImmutableDictionary< TKey, TValue >.Builder, System.Collections.Immutable.ImmutableDictionary< TKey, TValue >.Builder, System.Collections.Immutable.ImmutableDictionary< TKey, TValue >.Builder, System.Collections.Immutable.ImmutableDictionary< TKey, TValue >.HashBucket, System.Collections.Immutable.ImmutableDictionary< TKey, TValue >.HashBucket, System.Collections.Immutable.ImmutableDictionary< TKey, TValue >.HashBucket, System.Collections.Immutable.ImmutableDictionary< TKey, TValue >, System.Collections.Immutable.ImmutableDictionary< TKey, TValue >, System.Collections.Immutable.ImmutableDictionary< TKey, TValue >, System.Collections.Immutable.ImmutableDictionary< TKey, TValue >, System.Collections.Immutable.ImmutableExtensions.ListOfTWrapper< T >, System.Collections.Immutable.ImmutableExtensions.ListOfTWrapper< T >, System.Collections.Immutable.ImmutableExtensions.FallbackWrapper< T >, System.Collections.Immutable.ImmutableExtensions.FallbackWrapper< T >, System.Collections.Immutable.ImmutableHashSet< T >.Builder, System.Collections.Immutable.ImmutableHashSet< T >.Builder, System.Collections.Immutable.ImmutableHashSet< T >.Builder, System.Collections.Immutable.ImmutableHashSet< T >.NodeEnumerable, System.Collections.Immutable.ImmutableHashSet< T >.NodeEnumerable, System.Collections.Immutable.ImmutableHashSet< T >.NodeEnumerable, System.Collections.Immutable.ImmutableHashSet< T >, System.Collections.Immutable.ImmutableHashSet< T >, System.Collections.Immutable.ImmutableHashSet< T >, System.Collections.Immutable.ImmutableList< T >.Builder, System.Collections.Immutable.ImmutableList< T >.Builder, System.Collections.Immutable.ImmutableList< T >.Builder, System.Collections.Immutable.ImmutableList< T >.Node, System.Collections.Immutable.ImmutableList< T >.Node, System.Collections.Immutable.ImmutableList< T >.Node, System.Collections.Immutable.ImmutableList< T >, System.Collections.Immutable.ImmutableList< T >, System.Collections.Immutable.ImmutableList< T >, System.Collections.Immutable.ImmutableQueue< T >, System.Collections.Immutable.ImmutableQueue< T >, System.Collections.Immutable.ImmutableQueue< T >, System.Collections.Immutable.ImmutableSortedDictionary< TKey, TValue >.Builder, System.Collections.Immutable.ImmutableSortedDictionary< TKey, TValue >.Builder, System.Collections.Immutable.ImmutableSortedDictionary< TKey, TValue >.Builder, System.Collections.Immutable.ImmutableSortedDictionary< TKey, TValue >.Builder, System.Collections.Immutable.ImmutableSortedDictionary< TKey, TValue >.Node, System.Collections.Immutable.ImmutableSortedDictionary< TKey, TValue >.Node, System.Collections.Immutable.ImmutableSortedDictionary< TKey, TValue >.Node, System.Collections.Immutable.ImmutableSortedDictionary< TKey, TValue >, System.Collections.Immutable.ImmutableSortedDictionary< TKey, TValue >, System.Collections.Immutable.ImmutableSortedDictionary< TKey, TValue >, System.Collections.Immutable.ImmutableSortedDictionary< TKey, TValue >, System.Collections.Immutable.ImmutableSortedSet< T >.Builder, System.Collections.Immutable.ImmutableSortedSet< T >.Builder, System.Collections.Immutable.ImmutableSortedSet< T >.Builder, System.Collections.Immutable.ImmutableSortedSet< T >.ReverseEnumerable, System.Collections.Immutable.ImmutableSortedSet< T >.ReverseEnumerable, System.Collections.Immutable.ImmutableSortedSet< T >.Node, System.Collections.Immutable.ImmutableSortedSet< T >.Node, System.Collections.Immutable.ImmutableSortedSet< T >.Node, System.Collections.Immutable.ImmutableSortedSet< T >, System.Collections.Immutable.ImmutableSortedSet< T >, System.Collections.Immutable.ImmutableSortedSet< T >, System.Collections.Immutable.ImmutableStack< T >, System.Collections.Immutable.ImmutableStack< T >, System.Collections.Immutable.ImmutableStack< T >, System.Collections.Immutable.KeysOrValuesCollectionAccessor< TKey, TValue, T >, System.Collections.Immutable.KeysOrValuesCollectionAccessor< TKey, TValue, T >, System.Collections.CollectionBase, System.Collections.DictionaryBase, System.Collections.DictionaryBase, System.Collections.Queue.SynchronizedQueue, System.Collections.Queue, System.Collections.ReadOnlyCollectionBase, System.Collections.SortedList.SyncSortedList, System.Collections.SortedList.KeyList, System.Collections.SortedList.ValueList, System.Collections.SortedList, System.Collections.SortedList, System.Collections.Stack.SyncStack, System.Collections.Stack, System.Collections.Specialized.HybridDictionary, System.Collections.Specialized.HybridDictionary, System.Collections.Specialized.IOrderedDictionary, System.Collections.Specialized.ListDictionary.NodeKeyValueCollection, System.Collections.Specialized.ListDictionary, System.Collections.Specialized.ListDictionary, System.Collections.Specialized.NameObjectCollectionBase.KeysCollection, System.Collections.Specialized.NameObjectCollectionBase, System.Collections.Specialized.OrderedDictionary.OrderedDictionaryKeyValueCollection, System.Collections.Specialized.OrderedDictionary, System.Collections.Specialized.OrderedDictionary, System.Collections.Specialized.StringCollection, System.Collections.Specialized.StringCollection, System.Collections.Specialized.StringDictionary, System.Collections.Generic.LinkedList< T >, System.Collections.Generic.LinkedList< T >, System.Collections.Generic.LinkedList< T >, System.Collections.Generic.PriorityQueue< TElement, TPriority >.UnorderedItemsCollection, System.Collections.Generic.PriorityQueue< TElement, TPriority >.UnorderedItemsCollection, System.Collections.Generic.PriorityQueue< TElement, TPriority >.UnorderedItemsCollection, System.Collections.Generic.SortedDictionary< TKey, TValue >.KeyCollection, System.Collections.Generic.SortedDictionary< TKey, TValue >.KeyCollection, System.Collections.Generic.SortedDictionary< TKey, TValue >.KeyCollection, System.Collections.Generic.SortedDictionary< TKey, TValue >.ValueCollection, System.Collections.Generic.SortedDictionary< TKey, TValue >.ValueCollection, System.Collections.Generic.SortedDictionary< TKey, TValue >.ValueCollection, System.Collections.Generic.SortedDictionary< TKey, TValue >, System.Collections.Generic.SortedDictionary< TKey, TValue >, System.Collections.Generic.SortedDictionary< TKey, TValue >, System.Collections.Generic.SortedDictionary< TKey, TValue >, System.Collections.Generic.SortedList< TKey, TValue >.KeyList, System.Collections.Generic.SortedList< TKey, TValue >.KeyList, System.Collections.Generic.SortedList< TKey, TValue >.ValueList, System.Collections.Generic.SortedList< TKey, TValue >.ValueList, System.Collections.Generic.SortedList< TKey, TValue >, System.Collections.Generic.SortedList< TKey, TValue >, System.Collections.Generic.SortedList< TKey, TValue >, System.Collections.Generic.SortedList< TKey, TValue >, System.Collections.Generic.SortedSet< T >, System.Collections.Generic.SortedSet< T >, System.Collections.Generic.SortedSet< T >, System.Collections.Generic.Stack< T >, System.Collections.Generic.Stack< T >, System.Collections.Generic.Stack< T >, System.Collections.BitArray, MS.Internal.Xml.Linq.ComponentModel.XDeferredAxis< T >, MS.Internal.Xml.Linq.ComponentModel.XDeferredAxis< T >, System.ComponentModel.Design.DesignerCollection, System.ComponentModel.Design.DesignerCollection, System.ComponentModel.Design.DesignerOptionService.DesignerOptionCollection, System.ComponentModel.AttributeCollection, System.ComponentModel.AttributeCollection, System.ComponentModel.EventDescriptorCollection, System.ComponentModel.EventDescriptorCollection, System.ComponentModel.ListSortDescriptionCollection, System.ComponentModel.PropertyDescriptorCollection, System.ComponentModel.PropertyDescriptorCollection, System.ComponentModel.PropertyDescriptorCollection, System.ComponentModel.TypeConverter.StandardValuesCollection, System.Data.Common.DataColumnMappingCollection, System.Data.Common.DataTableMappingCollection, System.Data.Common.DbBatchCommandCollection, System.Data.Common.DbBatchCommandCollection, System.Data.Common.DbConnectionStringBuilder, System.Data.Common.DbConnectionStringBuilder, System.Data.Common.DbDataReader, System.Data.Common.DbParameterCollection, System.Data.DataRowCollection, System.Data.DataTableReader, System.Data.DataView, System.Data.DataViewManager, System.Data.DataViewSettingCollection, System.Data.EnumerableRowCollection< TRow >, System.Data.EnumerableRowCollection< TRow >, System.Data.EnumerableRowCollection< TRow >, System.Data.InternalDataCollectionBase, System.Data.RBTree< K >, System.Data.TypedTableBase< T >, System.Data.TypedTableBase< T >, System.Diagnostics.Activity.BaggageLinkedList, System.Diagnostics.Activity.BaggageLinkedList, System.Diagnostics.Activity.BaggageLinkedList, System.Diagnostics.Activity.TagsLinkedList, System.Diagnostics.Activity.TagsLinkedList, System.Diagnostics.Activity.TagsLinkedList, System.Diagnostics.ActivityTagsCollection, System.Diagnostics.ActivityTagsCollection, System.Diagnostics.ActivityTagsCollection, System.Diagnostics.DiagLinkedList< T >, System.Diagnostics.DiagLinkedList< T >, System.Diagnostics.DiagLinkedList< T >, System.Diagnostics.TagList, System.Diagnostics.TagList, System.Collections.Specialized.DictionaryWrapper, System.Collections.Specialized.DictionaryWrapper, System.Collections.Specialized.DictionaryWrapper, System.Collections.Specialized.StringDictionaryWrapper, System.Diagnostics.CorrelationManager.AsyncLocalStackWrapper, System.Diagnostics.TraceListenerCollection, System.IO.FileSystemWatcher.NormalizedFilterCollection.ImmutableStringList, System.IO.FileSystemWatcher.NormalizedFilterCollection.ImmutableStringList, System.Dynamic.Utils.ListProvider< T >, System.Dynamic.Utils.ListProvider< T >, System.Dynamic.ExpandoObject.KeyCollection, System.Dynamic.ExpandoObject.KeyCollection, System.Dynamic.ExpandoObject.ValueCollection, System.Dynamic.ExpandoObject.ValueCollection, System.Dynamic.ExpandoObject, System.Dynamic.ExpandoObject, System.Linq.Expressions.Compiler.ParameterList, System.Linq.Expressions.Compiler.ParameterList, System.Linq.Expressions.BlockExpressionList, System.Linq.Expressions.BlockExpressionList, System.Runtime.CompilerServices.ReadOnlyCollectionBuilder< T >, System.Runtime.CompilerServices.ReadOnlyCollectionBuilder< T >, System.Linq.Parallel.EnumerableWrapperWeakToStrong, System.Linq.Parallel.EnumerableWrapperWeakToStrong, System.Linq.Parallel.GroupByGrouping< TGroupKey, TElement >, System.Linq.Parallel.GroupByGrouping< TGroupKey, TElement >, System.Linq.Parallel.ListChunk< TInputOutput >, System.Linq.Parallel.ListChunk< TInputOutput >, System.Linq.Parallel.Lookup< TKey, TElement >, System.Linq.Parallel.Lookup< TKey, TElement >, System.Linq.Parallel.MergeExecutor< TInputOutput >, System.Linq.Parallel.MergeExecutor< TInputOutput >, System.Linq.Parallel.OrderedGroupByGrouping< TGroupKey, TOrderKey, TElement >, System.Linq.Parallel.OrderedGroupByGrouping< TGroupKey, TOrderKey, TElement >, System.Linq.Parallel.QueryResults< T >, System.Linq.Parallel.QueryResults< T >, System.Linq.OrderedParallelQuery< TSource >, System.Linq.ParallelQuery< TSource >, System.Linq.ParallelQuery< TSource >, System.Linq.EnumerableQuery< T >, System.Linq.EnumerableQuery< T >, System.Linq.EnumerableQuery< T >, System.Linq.EmptyPartition< TElement >, System.Linq.EmptyPartition< TElement >, System.Linq.Enumerable.Iterator< TSource >, System.Linq.Enumerable.Iterator< TSource >, System.Linq.GroupedEnumerable< TSource, TKey >, System.Linq.GroupedEnumerable< TSource, TKey >, System.Linq.GroupedEnumerable< TSource, TKey >, System.Linq.GroupedEnumerable< TSource, TKey >, System.Linq.GroupedResultEnumerable< TSource, TKey, TResult >, System.Linq.GroupedResultEnumerable< TSource, TKey, TResult >, System.Linq.GroupedResultEnumerable< TSource, TKey, TResult >, System.Linq.GroupedResultEnumerable< TSource, TKey, TResult >, System.Linq.Grouping< TKey, TElement >, System.Linq.Grouping< TKey, TElement >, System.Linq.Lookup< TKey, TElement >, System.Linq.Lookup< TKey, TElement >, System.Linq.OrderedEnumerable< TElement, TKey >, System.Linq.OrderedEnumerable< TElement, TKey >, System.Linq.OrderedPartition< TElement >, System.Linq.OrderedPartition< TElement >, System.Collections.Generic.BidirectionalDictionary< T1, T2 >, System.Collections.Generic.BidirectionalDictionary< T1, T2 >, System.Collections.Generic.BidirectionalDictionary< T1, T2 >, System.Net.Http.Headers.HeaderStringValues, System.Net.Http.Headers.HeaderStringValues, System.Net.Http.Headers.HeaderStringValues, System.Net.Http.Headers.HttpHeaders, System.Net.Http.Headers.HttpHeaders, System.Net.Http.Headers.HttpHeadersNonValidated, System.Net.Http.Headers.HttpHeadersNonValidated, System.Net.Http.Headers.HttpHeadersNonValidated, System.Net.Http.Headers.HttpHeaderValueCollection< T >, System.Net.Http.Headers.HttpHeaderValueCollection< T >, System.Net.Http.Headers.ObjectCollection< T >, System.Net.Http.Headers.ObjectCollection< T >, System.Net.Http.Headers.ObjectCollection< T >, System.Net.Http.HttpRequestOptions, System.Net.Http.HttpRequestOptions, System.Net.Http.MultipartContent, System.Net.Http.MultipartContent, System.Collections.Generic.BidirectionalDictionary< T1, T2 >, System.Collections.Generic.BidirectionalDictionary< T1, T2 >, System.Collections.Generic.BidirectionalDictionary< T1, T2 >, System.Net.HttpListenerPrefixCollection, System.Net.HttpListenerPrefixCollection, System.Collections.Generic.BidirectionalDictionary< T1, T2 >, System.Collections.Generic.BidirectionalDictionary< T1, T2 >, System.Collections.Generic.BidirectionalDictionary< T1, T2 >, System.Net.NetworkInformation.GatewayIPAddressInformationCollection, System.Net.NetworkInformation.GatewayIPAddressInformationCollection, System.Net.NetworkInformation.InternalIPAddressCollection, System.Net.NetworkInformation.IPAddressInformationCollection, System.Net.NetworkInformation.IPAddressInformationCollection, System.Net.NetworkInformation.MulticastIPAddressInformationCollection, System.Net.NetworkInformation.MulticastIPAddressInformationCollection, System.Net.NetworkInformation.UnicastIPAddressInformationCollection, System.Net.NetworkInformation.UnicastIPAddressInformationCollection, System.Net.NetworkInformation.IPAddressCollection, System.Net.NetworkInformation.IPAddressCollection, System.Net.CookieCollection, System.Net.CookieCollection, System.Net.CredentialCache, System.Collections.Generic.BidirectionalDictionary< T1, T2 >, System.Collections.Generic.BidirectionalDictionary< T1, T2 >, System.Collections.Generic.BidirectionalDictionary< T1, T2 >, System.Net.WebHeaderCollection, System.Collections.ObjectModel.ReadOnlyDictionary< TKey, TValue >.KeyCollection, System.Collections.ObjectModel.ReadOnlyDictionary< TKey, TValue >.KeyCollection, System.Collections.ObjectModel.ReadOnlyDictionary< TKey, TValue >.ValueCollection, System.Collections.ObjectModel.ReadOnlyDictionary< TKey, TValue >.ValueCollection, System.Collections.ObjectModel.ReadOnlyDictionary< TKey, TValue >, System.Collections.ObjectModel.ReadOnlyDictionary< TKey, TValue >, System.Collections.ObjectModel.ReadOnlyDictionary< TKey, TValue >, System.Collections.Specialized.ReadOnlyList, System.Collections.Specialized.SingleItemReadOnlyList, System.Collections.Concurrent.ConcurrentQueue< T >, System.Collections.Concurrent.ConcurrentQueue< T >, System.Collections.Generic.Dictionary< TKey, TValue >.KeyCollection, System.Collections.Generic.Dictionary< TKey, TValue >.KeyCollection, System.Collections.Generic.Dictionary< TKey, TValue >.KeyCollection, System.Collections.Generic.Dictionary< TKey, TValue >.ValueCollection, System.Collections.Generic.Dictionary< TKey, TValue >.ValueCollection, System.Collections.Generic.Dictionary< TKey, TValue >.ValueCollection, System.Collections.Generic.Dictionary< TKey, TValue >, System.Collections.Generic.Dictionary< TKey, TValue >, System.Collections.Generic.Dictionary< TKey, TValue >, System.Collections.Generic.Dictionary< TKey, TValue >, System.Collections.Generic.HashSet< T >, System.Collections.Generic.HashSet< T >, System.Collections.Generic.HashSet< T >, System.Collections.Generic.IEnumerable< out T >, System.Collections.Generic.List< T >, System.Collections.Generic.List< T >, System.Collections.Generic.List< T >, System.Collections.Generic.Queue< T >, System.Collections.Generic.Queue< T >, System.Collections.Generic.Queue< T >, System.Collections.ObjectModel.Collection< T >, System.Collections.ObjectModel.Collection< T >, System.Collections.ObjectModel.ReadOnlyCollection< T >, System.Collections.ObjectModel.ReadOnlyCollection< T >, System.Collections.ArrayList.IListWrapper, System.Collections.ArrayList.SyncArrayList, System.Collections.ArrayList.SyncIList, System.Collections.ArrayList.FixedSizeList, System.Collections.ArrayList.FixedSizeArrayList, System.Collections.ArrayList.ReadOnlyList, System.Collections.ArrayList.ReadOnlyArrayList, System.Collections.ArrayList.Range, System.Collections.ArrayList, System.Collections.EmptyReadOnlyDictionaryInternal, System.Collections.EmptyReadOnlyDictionaryInternal, System.Collections.Hashtable.KeyCollection, System.Collections.Hashtable.ValueCollection, System.Collections.Hashtable.SyncHashtable, System.Collections.Hashtable.SyncHashtable, System.Collections.Hashtable, System.Collections.Hashtable, System.Collections.IDictionary, System.Collections.ListDictionaryInternal.NodeKeyValueCollection, System.Collections.ListDictionaryInternal, System.Collections.ListDictionaryInternal, System.Diagnostics.Tracing.CounterPayload, System.Diagnostics.Tracing.CounterPayload, System.Diagnostics.Tracing.EventPayload, System.Diagnostics.Tracing.EventPayload, System.Diagnostics.Tracing.IncrementingCounterPayload, System.Diagnostics.Tracing.IncrementingCounterPayload, System.IO.Enumeration.FileSystemEnumerable< TResult >, System.IO.Enumeration.FileSystemEnumerable< TResult >, System.IO.Iterator< TSource >, System.IO.Iterator< TSource >, System.Resources.IResourceReader, System.Resources.ResourceFallbackManager, System.Resources.ResourceFallbackManager, System.Resources.ResourceReader, System.Resources.ResourceReader, System.Resources.ResourceSet, System.Resources.ResourceSet, System.Resources.RuntimeResourceSet, System.Resources.RuntimeResourceSet, System.Runtime.CompilerServices.ConditionalWeakTable< TKey, TValue >, System.Runtime.CompilerServices.ConditionalWeakTable< TKey, TValue >, System.Runtime.InteropServices.CustomMarshalers.EnumerableViewOfDispatch, System.Security.PermissionSet, System.Text.StringRuneEnumerator, System.Text.StringRuneEnumerator, System.Text.StringRuneEnumerator, System.Threading.Tasks.SingleProducerSingleConsumerQueue< T >, System.Threading.Tasks.SingleProducerSingleConsumerQueue< T >, System.Array, System.ArraySegment< T >, System.ArraySegment< T >, System.ArraySegment< T >, System.String, System.String, System.String, MS.Internal.Xml.XPath.XPathArrayIterator, System.Xml.Schema.XmlSchemaCollection, System.Xml.Schema.XmlSchemaCollection, System.Xml.Schema.XmlSchemaObjectCollection, System.Xml.Schema.XmlSchemaObjectTable.NamesCollection, System.Xml.Schema.XmlSchemaObjectTable.ValuesCollection, System.Xml.Serialization.XmlSchemas, System.Xml.XPath.XPathNodeIterator, System.Xml.Xsl.Qil.QilNode, System.Xml.Xsl.Qil.QilNode, System.Xml.Xsl.Runtime.XmlQueryNodeSequence, System.Xml.Xsl.Runtime.XmlQuerySequence< T >, System.Xml.Xsl.Runtime.XmlQuerySequence< T >, System.Xml.Xsl.ListBase< T >, System.Xml.Xsl.ListBase< T >, System.Xml.Xsl.ListBase< T >, System.Xml.XmlChildNodes, System.Xml.XmlElementList, System.Xml.XmlNamedNodeMap, System.Xml.XmlNamespaceManager, System.Xml.XmlNode, System.Xml.XmlNode, System.Xml.XmlNodeList, System.Xml.XmlTextReaderImpl.NoNamespaceManager, System.Xml.XPathNodeList, System.Reflection.Metadata.AssemblyFileHandleCollection, System.Reflection.Metadata.AssemblyFileHandleCollection, System.Reflection.Metadata.AssemblyFileHandleCollection, System.Reflection.Metadata.AssemblyReferenceHandleCollection, System.Reflection.Metadata.AssemblyReferenceHandleCollection, System.Reflection.Metadata.AssemblyReferenceHandleCollection, System.Reflection.Metadata.BlobBuilder.Chunks, System.Reflection.Metadata.BlobBuilder.Chunks, System.Reflection.Metadata.BlobBuilder.Chunks, System.Reflection.Metadata.BlobBuilder.Blobs, System.Reflection.Metadata.BlobBuilder.Blobs, System.Reflection.Metadata.BlobBuilder.Blobs, System.Reflection.Metadata.CustomAttributeHandleCollection, System.Reflection.Metadata.CustomAttributeHandleCollection, System.Reflection.Metadata.CustomAttributeHandleCollection, System.Reflection.Metadata.CustomDebugInformationHandleCollection, System.Reflection.Metadata.CustomDebugInformationHandleCollection, System.Reflection.Metadata.CustomDebugInformationHandleCollection, System.Reflection.Metadata.DeclarativeSecurityAttributeHandleCollection, System.Reflection.Metadata.DeclarativeSecurityAttributeHandleCollection, System.Reflection.Metadata.DeclarativeSecurityAttributeHandleCollection, System.Reflection.Metadata.DocumentHandleCollection, System.Reflection.Metadata.DocumentHandleCollection, System.Reflection.Metadata.DocumentHandleCollection, System.Reflection.Metadata.EventDefinitionHandleCollection, System.Reflection.Metadata.EventDefinitionHandleCollection, System.Reflection.Metadata.EventDefinitionHandleCollection, System.Reflection.Metadata.ExportedTypeHandleCollection, System.Reflection.Metadata.ExportedTypeHandleCollection, System.Reflection.Metadata.ExportedTypeHandleCollection, System.Reflection.Metadata.FieldDefinitionHandleCollection, System.Reflection.Metadata.FieldDefinitionHandleCollection, System.Reflection.Metadata.FieldDefinitionHandleCollection, System.Reflection.Metadata.GenericParameterConstraintHandleCollection, System.Reflection.Metadata.GenericParameterConstraintHandleCollection, System.Reflection.Metadata.GenericParameterConstraintHandleCollection, System.Reflection.Metadata.GenericParameterHandleCollection, System.Reflection.Metadata.GenericParameterHandleCollection, System.Reflection.Metadata.GenericParameterHandleCollection, System.Reflection.Metadata.ImportDefinitionCollection, System.Reflection.Metadata.ImportDefinitionCollection, System.Reflection.Metadata.ImportDefinitionCollection, System.Reflection.Metadata.ImportScopeCollection, System.Reflection.Metadata.ImportScopeCollection, System.Reflection.Metadata.ImportScopeCollection, System.Reflection.Metadata.InterfaceImplementationHandleCollection, System.Reflection.Metadata.InterfaceImplementationHandleCollection, System.Reflection.Metadata.InterfaceImplementationHandleCollection, System.Reflection.Metadata.LocalConstantHandleCollection, System.Reflection.Metadata.LocalConstantHandleCollection, System.Reflection.Metadata.LocalConstantHandleCollection, System.Reflection.Metadata.LocalScopeHandleCollection, System.Reflection.Metadata.LocalScopeHandleCollection, System.Reflection.Metadata.LocalScopeHandleCollection, System.Reflection.Metadata.LocalVariableHandleCollection, System.Reflection.Metadata.LocalVariableHandleCollection, System.Reflection.Metadata.LocalVariableHandleCollection, System.Reflection.Metadata.ManifestResourceHandleCollection, System.Reflection.Metadata.ManifestResourceHandleCollection, System.Reflection.Metadata.ManifestResourceHandleCollection, System.Reflection.Metadata.MemberReferenceHandleCollection, System.Reflection.Metadata.MemberReferenceHandleCollection, System.Reflection.Metadata.MemberReferenceHandleCollection, System.Reflection.Metadata.MethodDebugInformationHandleCollection, System.Reflection.Metadata.MethodDebugInformationHandleCollection, System.Reflection.Metadata.MethodDebugInformationHandleCollection, System.Reflection.Metadata.MethodDefinitionHandleCollection, System.Reflection.Metadata.MethodDefinitionHandleCollection, System.Reflection.Metadata.MethodDefinitionHandleCollection, System.Reflection.Metadata.MethodImplementationHandleCollection, System.Reflection.Metadata.MethodImplementationHandleCollection, System.Reflection.Metadata.MethodImplementationHandleCollection, System.Reflection.Metadata.ParameterHandleCollection, System.Reflection.Metadata.ParameterHandleCollection, System.Reflection.Metadata.ParameterHandleCollection, System.Reflection.Metadata.PropertyDefinitionHandleCollection, System.Reflection.Metadata.PropertyDefinitionHandleCollection, System.Reflection.Metadata.PropertyDefinitionHandleCollection, System.Reflection.Metadata.SequencePointCollection, System.Reflection.Metadata.SequencePointCollection, System.Reflection.Metadata.SequencePointCollection, System.Reflection.Metadata.TypeDefinitionHandleCollection, System.Reflection.Metadata.TypeDefinitionHandleCollection, System.Reflection.Metadata.TypeDefinitionHandleCollection, System.Reflection.Metadata.TypeReferenceHandleCollection, System.Reflection.Metadata.TypeReferenceHandleCollection, System.Reflection.Metadata.TypeReferenceHandleCollection, System.Security.AccessControl.GenericAcl, System.Security.AccessControl.GenericAcl, System.Security.Policy.Evidence, System.Security.Cryptography.AsnEncodedDataCollection, System.Security.Cryptography.AsnEncodedDataCollection, System.Security.Cryptography.OidCollection, System.Security.Cryptography.OidCollection, System.Security.Cryptography.X509Certificates.X509Certificate2Collection, System.Security.Cryptography.X509Certificates.X509Certificate2Collection, System.Security.Cryptography.X509Certificates.X509CertificateCollection, System.Security.Cryptography.X509Certificates.X509ChainElementCollection, System.Security.Cryptography.X509Certificates.X509ChainElementCollection, System.Security.Cryptography.X509Certificates.X509ChainElementCollection, System.Security.Cryptography.X509Certificates.X509ExtensionCollection, System.Security.Cryptography.X509Certificates.X509ExtensionCollection, System.Security.Cryptography.X509Certificates.X509ExtensionCollection, System.Security.Principal.IdentityReferenceCollection, System.Security.Principal.IdentityReferenceCollection, System.Text.Json.Nodes.JsonArray, System.Text.Json.Nodes.JsonArray, System.Text.Json.Nodes.JsonObject, System.Text.Json.Nodes.JsonObject, System.Text.Json.Serialization.ConverterList, System.Text.Json.Serialization.ConverterList, System.Text.Json.JsonElement.ArrayEnumerator, System.Text.Json.JsonElement.ArrayEnumerator, System.Text.Json.JsonElement.ArrayEnumerator, System.Text.Json.JsonElement.ObjectEnumerator, System.Text.Json.JsonElement.ObjectEnumerator, System.Text.Json.JsonElement.ObjectEnumerator, System.Text.Json.JsonPropertyDictionary< T >.KeyCollection, System.Text.Json.JsonPropertyDictionary< T >.KeyCollection, System.Text.Json.JsonPropertyDictionary< T >.ValueCollection, System.Text.Json.JsonPropertyDictionary< T >.ValueCollection, System.Text.RegularExpressions.CaptureCollection, System.Text.RegularExpressions.CaptureCollection, System.Text.RegularExpressions.GroupCollection, System.Text.RegularExpressions.GroupCollection, System.Text.RegularExpressions.GroupCollection, System.Text.RegularExpressions.MatchCollection, System.Text.RegularExpressions.MatchCollection, System.Collections.Concurrent.SingleProducerSingleConsumerQueue< T >, System.Collections.Concurrent.SingleProducerSingleConsumerQueue< T >, System.Threading.Tasks.SingleProducerSingleConsumerQueue< T >, System.Threading.Tasks.SingleProducerSingleConsumerQueue< T >, Terraria.GameContent.Personalities.BiomePreferenceListTrait, Terraria.GameContent.Personalities.BiomePreferenceListTrait, Terraria.GameContent.UI.Elements.UIList, Terraria.GameContent.UI.Elements.UIList, Terraria.Testing.ChatCommands.ArgumentListResult, and Terraria.Testing.ChatCommands.ArgumentListResult.
Referenced by System.Collections.Queue.Queue(), System.Collections.Stack.Stack(), System.Collections.Specialized.StringEnumerator.StringEnumerator(), System.Linq.Enumerable.EnumerablePartition< TSource >.GetCount(), System.Collections.Concurrent.OrderablePartitioner< TSource >.EnumerableDropIndices.GetEnumerator(), System.ComponentModel.Design.DesignerCollection.GetEnumerator(), System.ComponentModel.TypeConverter.StandardValuesCollection.GetEnumerator(), System.Collections.Specialized.ReadOnlyList.GetEnumerator(), System.Collections.ArrayList.IListWrapper.GetEnumerator(), System.Collections.ArrayList.SyncIList.GetEnumerator(), System.Collections.ArrayList.FixedSizeList.GetEnumerator(), System.Collections.ArrayList.ReadOnlyList.GetEnumerator(), MS.Internal.Xml.XPath.XPathArrayIterator.GetEnumerator(), System.Collections.Concurrent.Partitioner< TSource >.DynamicPartitionerForIEnumerable< TSource >.GetOrderableDynamicPartitions(), System.Collections.Concurrent.Partitioner< TSource >.DynamicPartitionerForIEnumerable< TSource >.GetOrderablePartitions(), System.Linq.Enumerable.AppendPrependIterator< TSource >.GetSourceEnumerator(), System.Security.Cryptography.XmlKeyHelper.ParseState.GetValue(), System.Collections.ArrayList.IListWrapper.InsertRange(), System.Linq.Enumerable.ConcatIterator< TSource >.MoveNext(), System.Linq.Enumerable.DefaultIfEmptyIterator< TSource >.MoveNext(), System.Linq.Enumerable.DistinctIterator< TSource >.MoveNext(), System.Linq.Enumerable.EnumerablePartition< TSource >.MoveNext(), System.Linq.Enumerable.SelectEnumerableIterator< TSource, TResult >.MoveNext(), System.Linq.Enumerable.SelectManySingleSelectorIterator< TSource, TResult >.MoveNext(), System.Linq.Enumerable.WhereEnumerableIterator< TSource >.MoveNext(), System.Linq.Enumerable.WhereSelectEnumerableIterator< TSource, TResult >.MoveNext(), System.ComponentModel.TypeDescriptor.PipelineInitialize(), System.ComponentModel.TypeDescriptor.PipelineMerge(), System.Collections.ArrayList.IListWrapper.SetRange(), System.Linq.Enumerable.EnumerablePartition< TSource >.ToArray(), System.Linq.Enumerable.EnumerablePartition< TSource >.ToList(), System.Linq.Enumerable.EnumerablePartition< TSource >.TryGetElementAt(), System.Linq.Enumerable.EnumerablePartition< TSource >.TryGetFirst(), and System.Linq.Enumerable.EnumerablePartition< TSource >.TryGetLast().