Terraria: System.Xml.Schema.Numeric10FacetsChecker.CheckValueFacets
CheckValueFacets() [3/12]
override Exception System.Xml.Schema.Numeric10FacetsChecker.CheckValueFacets (decimal value, XmlSchemaDatatype datatype) inline package virtual
Reimplemented from System.Xml.Schema.FacetsChecker.
Definition at line 24 of file Numeric10FacetsChecker.cs.
    {
        RestrictionFacets restriction = datatype.Restriction;
        RestrictionFlags restrictionFlags = restriction?.Flags ?? ((RestrictionFlags)0);
        XmlValueConverter valueConverter = datatype.ValueConverter;
        if (value > _maxValue || value < _minValue)
        {
            return new OverflowException(System.SR.Format(System.SR.XmlConvert_Overflow, value.ToString(CultureInfo.InvariantCulture), datatype.TypeCodeString));
        }
        if (restrictionFlags != 0)
        {
            if ((restrictionFlags & RestrictionFlags.MaxInclusive) != 0 && value > valueConverter.ToDecimal(restriction.MaxInclusive))
            {
                return new XmlSchemaException(System.SR.Sch_MaxInclusiveConstraintFailed, string.Empty);
            }
            if ((restrictionFlags & RestrictionFlags.MaxExclusive) != 0 && value >= valueConverter.ToDecimal(restriction.MaxExclusive))
            {
                return new XmlSchemaException(System.SR.Sch_MaxExclusiveConstraintFailed, string.Empty);
            }
            if ((restrictionFlags & RestrictionFlags.MinInclusive) != 0 && value < valueConverter.ToDecimal(restriction.MinInclusive))
            {
                return new XmlSchemaException(System.SR.Sch_MinInclusiveConstraintFailed, string.Empty);
            }
            if ((restrictionFlags & RestrictionFlags.MinExclusive) != 0 && value <= valueConverter.ToDecimal(restriction.MinExclusive))
            {
                return new XmlSchemaException(System.SR.Sch_MinExclusiveConstraintFailed, string.Empty);
            }
            if ((restrictionFlags & RestrictionFlags.Enumeration) != 0 && !MatchEnumeration(value, restriction.Enumeration, valueConverter))
            {
                return new XmlSchemaException(System.SR.Sch_EnumerationConstraintFailed, string.Empty);
            }
            return CheckTotalAndFractionDigits(value, restriction.TotalDigits, restriction.FractionDigits, (restrictionFlags & RestrictionFlags.TotalDigits) != 0, (restrictionFlags & RestrictionFlags.FractionDigits) != 0);
        }
        return null;
    }
References System.Xml.Schema.Numeric10FacetsChecker._maxValue, System.Xml.Schema.Numeric10FacetsChecker._minValue, System.Xml.Schema.Numeric10FacetsChecker.CheckTotalAndFractionDigits(), System.Xml.Dictionary, System.Xml.Schema.RestrictionFacets.Flags, System.SR.Format(), System.Globalization.CultureInfo.InvariantCulture, System.Xml.Schema.Numeric10FacetsChecker.MatchEnumeration(), System.Xml.Schema.XmlSchemaDatatype.Restriction, System.SR.Sch_EnumerationConstraintFailed, System.SR.Sch_MaxExclusiveConstraintFailed, System.SR.Sch_MaxInclusiveConstraintFailed, System.SR.Sch_MinExclusiveConstraintFailed, System.SR.Sch_MinInclusiveConstraintFailed, System.Xml.Schema.XmlSchemaDatatype.TypeCodeString, System.value, System.Xml.Schema.XmlSchemaDatatype.ValueConverter, and System.SR.XmlConvert_Overflow.