Terraria: System.Security.Cryptography.PemEncoding.TryFind
TryFind()
static bool System.Security.Cryptography.PemEncoding.TryFind (ReadOnlySpan< char > pemData, out PemFields fields) inline static
Definition at line 16 of file PemEncoding.cs.
    {
        if (pemData.Length < "-----BEGIN ".Length + "-----".Length * 2 + "-----END ".Length)
        {
            fields = default(PemFields);
            return false;
        }
        Span<char> span = stackalloc char[256];
        int num = 0;
        int num2;
        while ((num2 = pemData.IndexOfByOffset("-----BEGIN ", num)) >= 0)
        {
            int num3 = num2 + "-----BEGIN ".Length;
            if (num2 > 0 && !IsWhiteSpaceCharacter(pemData[num2 - 1]))
            {
                num = num3;
                continue;
            }
            int num4 = pemData.IndexOfByOffset("-----", num3);
            if (num4 < 0)
            {
                fields = default(PemFields);
                return false;
            }
            Range range = num3..num4;
            ReadOnlySpan<char> readOnlySpan = pemData;
            ReadOnlySpan<char> readOnlySpan2 = readOnlySpan[range];
            if (IsValidLabel(readOnlySpan2))
            {
                int num5 = num4 + "-----".Length;
                int num6 = "-----END ".Length + readOnlySpan2.Length + "-----".Length;
                Span<char> destination2 = ((num6 > 256) ? ((Span<char>)new char[num6]) : span);
                ReadOnlySpan<char> value = WritePostEB(readOnlySpan2, destination2);
                int num7 = pemData.IndexOfByOffset(value, num5);
                if (num7 >= 0)
                {
                    int num8 = num7 + num6;
                    if (num8 >= pemData.Length - 1 || IsWhiteSpaceCharacter(pemData[num8]))
                    {
                        Range range2 = num5..num7;
                        readOnlySpan = pemData;
                        if (TryCountBase64(readOnlySpan[range2], out var base64Start, out var base64End, out var base64DecodedSize))
{
                            Range location = num2..num8;
                            Range base64data = (num5 + base64Start)..(num5 + base64End);
                            fields = new PemFields(range, base64data, location, base64DecodedSize);
                            return true;
                        }
                    }
                }
            }
            if (num4 <= num)
            {
                fields = default(PemFields);
                return false;
            }
            num = num4;
        }
        fields = default(PemFields);
        return false;
        static ReadOnlySpan<char> WritePostEB(ReadOnlySpan<char> label, Span<char> destination)
        {
            int length = "-----END ".Length + label.Length + "-----".Length;
            "-----END ".CopyTo(destination);
            label.CopyTo(destination.Slice("-----END ".Length));
            "-----".CopyTo(destination.Slice("-----END ".Length + label.Length));
            return destination.Slice(0, length);
        }
    }
References System.ReadOnlySpan< T >.CopyTo(), System.destination, System.Security.Cryptography.PemEncoding.IsValidLabel(), System.Security.Cryptography.PemEncoding.IsWhiteSpaceCharacter(), System.length, System.ReadOnlySpan< T >.Length, System.Security.Cryptography.PemEncoding.TryCountBase64(), and System.value.
Referenced by System.Security.Cryptography.PemEncoding.Find(), Internal.Cryptography.PemKeyImportHelpers.ImportEncryptedPem< TPass >(), Internal.Cryptography.PemKeyImportHelpers.ImportPem(), and Internal.Cryptography.PemEnumerator.Enumerator.MoveNext().