Terraria: System.Security.Cryptography.PemEncoding.Write
Write()
static char[] System.Security.Cryptography.PemEncoding.Write (ReadOnlySpan< char > label, ReadOnlySpan< byte > data) inline static
Definition at line 283 of file PemEncoding.cs.
    {
        if (!IsValidLabel(label))
        {
            throw new ArgumentException(System.SR.Argument_PemEncoding_InvalidLabel, "label");
        }
        int encodedSize = GetEncodedSize(label.Length, data.Length);
        char[] array = new char[encodedSize];
        if (!TryWrite(label, data, array, out var _))
        {
            throw new ArgumentException(null, "data");
        }
        return array;
    }
References System.SR.Argument_PemEncoding_InvalidLabel, System.array, System.Security.Cryptography.PemEncoding.GetEncodedSize(), System.Security.Cryptography.PemEncoding.IsValidLabel(), System.ReadOnlySpan< T >.Length, and System.Security.Cryptography.PemEncoding.TryWrite().