Terraria: System.Security.Cryptography.PemEncoding.GetEncodedSize
GetEncodedSize()
static int System.Security.Cryptography.PemEncoding.GetEncodedSize (int labelLength, int dataLength) inline static
Definition at line 198 of file PemEncoding.cs.
    {
        if (labelLength < 0)
        {
            throw new ArgumentOutOfRangeException("labelLength", System.SR.ArgumentOutOfRange_NeedPositiveNumber);
        }
        if (dataLength < 0)
        {
            throw new ArgumentOutOfRangeException("dataLength", System.SR.ArgumentOutOfRange_NeedPositiveNumber);
        }
        if (labelLength > 1073741808)
        {
            throw new ArgumentOutOfRangeException("labelLength", System.SR.Argument_PemEncoding_EncodedSizeTooLarge);
        }
        if (dataLength > 1585834053)
        {
            throw new ArgumentOutOfRangeException("dataLength", System.SR.Argument_PemEncoding_EncodedSizeTooLarge);
        }
        int num = "-----BEGIN ".Length + labelLength + "-----".Length;
        int num2 = "-----END ".Length + labelLength + "-----".Length;
        int num3 = num + num2 + 1;
        int num4 = (dataLength + 2) / 3 << 2;
        int result;
        int num5 = Math.DivRem(num4, 64, out result);
        if (result > 0)
        {
            num5++;
        }
        int num6 = num4 + num5;
        if (int.MaxValue - num6 < num3)
        {
            throw new ArgumentException(System.SR.Argument_PemEncoding_EncodedSizeTooLarge);
        }
        return num6 + num3;
    }
References System.SR.Argument_PemEncoding_EncodedSizeTooLarge, System.SR.ArgumentOutOfRange_NeedPositiveNumber, and System.Math.DivRem().
Referenced by System.Security.Cryptography.PemEncoding.TryWrite(), and System.Security.Cryptography.PemEncoding.Write().