Terraria: System.Security.Cryptography.PemEncoding.TryWrite
TryWrite()
static bool System.Security.Cryptography.PemEncoding.TryWrite (ReadOnlySpan< char > label, ReadOnlySpan< byte > data, Span< char > destination, out int charsWritten) inline static
Definition at line 234 of file PemEncoding.cs.
    {
        if (!IsValidLabel(label))
        {
            throw new ArgumentException(System.SR.Argument_PemEncoding_InvalidLabel, "label");
        }
        int encodedSize = GetEncodedSize(label.Length, data.Length);
        if (destination.Length < encodedSize)
        {
            charsWritten = 0;
            return false;
        }
        charsWritten = 0;
        charsWritten += Write("-----BEGIN ", destination, charsWritten);
        charsWritten += Write(label, destination, charsWritten);
        charsWritten += Write("-----", destination, charsWritten);
        charsWritten += Write("\n", destination, charsWritten);
        ReadOnlySpan<byte> bytes2 = data;
        while (bytes2.Length >= 48)
        {
            charsWritten += WriteBase64(bytes2.Slice(0, 48), destination, charsWritten);
            charsWritten += Write("\n", destination, charsWritten);
            bytes2 = bytes2.Slice(48);
        }
        if (bytes2.Length > 0)
        {
            charsWritten += WriteBase64(bytes2, destination, charsWritten);
            charsWritten += Write("\n", destination, charsWritten);
            bytes2 = default(ReadOnlySpan<byte>);
        }
        charsWritten += Write("-----END ", destination, charsWritten);
        charsWritten += Write(label, destination, charsWritten);
        charsWritten += Write("-----", destination, charsWritten);
        return true;
        static int Write(ReadOnlySpan<char> str, Span<char> dest, int offset)
        {
            str.CopyTo(dest.Slice(offset));
            return str.Length;
        }
        static int WriteBase64(ReadOnlySpan<byte> bytes, Span<char> dest, int offset)
        {
            if (!Convert.TryToBase64Chars(bytes, dest.Slice(offset), out var charsWritten2))
            {
                throw new ArgumentException(null, "destination");
            }
            return charsWritten2;
        }
    }
References System.SR.Argument_PemEncoding_InvalidLabel, System.bytes, System.destination, System.Security.Cryptography.PemEncoding.GetEncodedSize(), System.Security.Cryptography.PemEncoding.IsValidLabel(), System.ReadOnlySpan< T >.Length, System.offset, System.ReadOnlySpan< T >.Slice(), System.Span< T >.Slice(), System.str, System.Convert.TryToBase64Chars(), and System.Security.Cryptography.Write.
Referenced by System.Security.Cryptography.PemEncoding.Write().