Terraria: System.ComponentModel.DataAnnotations.CountPropertyHelper.TryGetCount
TryGetCount()
static bool System.ComponentModel.DataAnnotations.CountPropertyHelper.TryGetCount (object value, out int count) inline static
Definition at line 10 of file CountPropertyHelper.cs.
    {
        if (value is ICollection collection)
        {
            count = collection.Count;
            return true;
        }
        PropertyInfo runtimeProperty = value.GetType().GetRuntimeProperty("Count");
        if (runtimeProperty != null && runtimeProperty.CanRead && runtimeProperty.PropertyType == typeof(int))
        {
            count = (int)runtimeProperty.GetValue(value);
            return true;
        }
        count = -1;
        return false;
    }
References System.Reflection.PropertyInfo.CanRead, System.collection, System.count, System.Reflection.PropertyInfo.GetValue(), System.Reflection.PropertyInfo.PropertyType, and System.value.
Referenced by System.ComponentModel.DataAnnotations.MaxLengthAttribute.IsValid(), and System.ComponentModel.DataAnnotations.MinLengthAttribute.IsValid().