Terraria: System.Security.Cryptography.PemEncoding.TryCountBase64
TryCountBase64()
static bool System.Security.Cryptography.PemEncoding.TryCountBase64 (ReadOnlySpan< char > str, out int base64Start, out int base64End, out int base64DecodedSize) inline static private
Definition at line 128 of file PemEncoding.cs.
    {
        base64Start = 0;
        base64End = str.Length;
        if (str.IsEmpty)
        {
            base64DecodedSize = 0;
            return true;
        }
        int num = 0;
        int num2 = 0;
        for (int i = 0; i < str.Length; i++)
        {
            char c = str[i];
            if (IsWhiteSpaceCharacter(c))
            {
                if (num == 0)
                {
                    base64Start++;
                }
                else
                {
                    base64End--;
                }
                continue;
            }
            base64End = str.Length;
            if (c == '=')
            {
                num2++;
                continue;
            }
            if (num2 == 0 && IsBase64Character(c))
            {
                num++;
                continue;
            }
            base64DecodedSize = 0;
            return false;
        }
        int num3 = num2 + num;
        if (num2 > 2 || ((uint)num3 & 3u) != 0)
        {
            base64DecodedSize = 0;
            return false;
        }
        base64DecodedSize = (num3 >> 2) * 3 - num2;
        return true;
    }
References System.Security.Cryptography.PemEncoding.IsBase64Character(), System.Security.Cryptography.PemEncoding.IsWhiteSpaceCharacter(), and System.str.
Referenced by System.Security.Cryptography.PemEncoding.TryFind().