Terraria: System.Linq.EnumerableRewriter.VisitLabelTarget
VisitLabelTarget() [1/2]
override LabelTarget System.Linq.EnumerableRewriter.VisitLabelTarget (LabelTarget node) inline protected
Definition at line 424 of file EnumerableRewriter.cs.
    {
        LabelTarget value;
        if (_targetCache == null)
        {
            _targetCache = new Dictionary<LabelTarget, LabelTarget>();
        }
        else if (_targetCache.TryGetValue(node, out value))
        {
            return value;
        }
        Type type = node.Type;
        value = (typeof(IQueryable).IsAssignableFrom(type) ? Expression.Label(GetEquivalentType(type), node.Name) : base.VisitLabelTarget(node));
        _targetCache.Add(node, value);
        return value;
    }
References System.Linq.EnumerableRewriter._targetCache, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Linq.EnumerableRewriter.GetEquivalentType(), System.Linq.Expressions.Expression< TDelegate >.Label(), System.Collections.Generic.Dictionary< TKey, TValue >.TryGetValue(), System.type, and System.value.
Referenced by System.Linq.EnumerableRewriter.VisitGoto().