Terraria: System.Linq.EnumerableRewriter.GetPublicType
GetPublicType()
static Type System.Linq.EnumerableRewriter.GetPublicType (Type t) inline static private
Definition at line 118 of file EnumerableRewriter.cs.
    {
        if (t.IsGenericType && ImplementsIGrouping(t))
        {
            return typeof(IGrouping<, >).MakeGenericType(t.GetGenericArguments());
        }
        if (!t.IsNestedPrivate)
        {
            return t;
        }
        if (TryGetImplementedIEnumerable(t, out var interfaceType2))
        {
            return interfaceType2;
        }
        if (typeof(IEnumerable).IsAssignableFrom(t))
        {
            return typeof(IEnumerable);
        }
        return t;
        [UnconditionalSuppressMessage("ReflectionAnalysis", "IL2075:UnrecognizedReflectionPattern", Justification = "The IGrouping<,> is kept since it's directly referenced hereand so it will also be preserved in all places where it's implemented.The GetInterfaces may return less after trimming but it will includethe IGrouping<,> if it was there before trimming, which is enough for thismethod to work.")]
        static bool ImplementsIGrouping(Type type)
        {
            return type.GetGenericTypeDefinition().GetInterfaces().Contains(typeof(IGrouping<, >));
        }
        [UnconditionalSuppressMessage("ReflectionAnalysis", "IL2070:UnrecognizedReflectionPattern", Justification = "The IEnumerable<> is kept since it's directly referenced hereand so it will also be preserved in all places where it's implemented.The GetInterfaces may return less after trimming but it will includethe IEnumerable<> if it was there before trimming, which is enough for thismethod to work.")]
        static bool TryGetImplementedIEnumerable(Type type, [NotNullWhen(true)] out Type interfaceType)
        {
            Type[] interfaces = type.GetInterfaces();
            foreach (Type type2 in interfaces)
            {
                if (type2.IsGenericType && type2.GetGenericTypeDefinition() == typeof(IEnumerable<>))
                {
                    interfaceType = type2;
                    return true;
                }
            }
            interfaceType = null;
            return false;
        }
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Contains(), System.Type.GetGenericArguments(), System.Type.GetInterfaces(), System.Type.IsGenericType, System.Type.IsNestedPrivate, and System.type.
Referenced by System.Linq.EnumerableRewriter.GetEquivalentType(), and System.Linq.EnumerableRewriter.VisitConstant().