Terraria: System.Linq.EnumerableRewriter.ArgsMatch
ArgsMatch()
static bool System.Linq.EnumerableRewriter.ArgsMatch (MethodInfo m, ReadOnlyCollection< Expression > args, Type[] typeArgs) inline static private
Definition at line 292 of file EnumerableRewriter.cs.
    {
        ParameterInfo[] array = m.GetParameters();
        if (array.Length != args.Count)
        {
            return false;
        }
        if (!m.IsGenericMethod && typeArgs != null && typeArgs.Length != 0)
        {
            return false;
        }
        if (!m.IsGenericMethodDefinition && m.IsGenericMethod && m.ContainsGenericParameters)
        {
            m = m.GetGenericMethodDefinition();
        }
        if (m.IsGenericMethodDefinition)
        {
            if (typeArgs == null || typeArgs.Length == 0)
            {
                return false;
            }
            if (m.GetGenericArguments().Length != typeArgs.Length)
            {
                return false;
            }
            array = GetConstrutedGenericParameters(m, typeArgs);
        }
        int i = 0;
        for (int count = args.Count; i < count; i++)
        {
            Type type = array[i].ParameterType;
            if (type == null)
            {
                return false;
            }
            if (type.IsByRef)
            {
                type = type.GetElementType();
            }
            Expression expression = args[i];
            if (!type.IsAssignableFrom(expression.Type))
            {
                if (expression.NodeType == ExpressionType.Quote)
                {
                    expression = ((UnaryExpression)expression).Operand;
                }
                if (!type.IsAssignableFrom(expression.Type) && !type.IsAssignableFrom(StripExpression(expression.Type)))
                {
                    return false;
                }
            }
        }
        return true;
        [UnconditionalSuppressMessage("ReflectionAnalysis", "IL2060:MakeGenericMethod", Justification = "MakeGenericMethod is only called to get the parameter types, which are only used to make a 'match' decision. The generic method is not invoked.")]
        static ParameterInfo[] GetConstrutedGenericParameters(MethodInfo method, Type[] genericTypes)
        {
            return method.MakeGenericMethod(genericTypes).GetParameters();
        }
    }
References System.array, System.Linq.count, System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Type.GetElementType(), System.Linq.EnumerableRewriter.StripExpression(), and System.type.
Referenced by System.Linq.EnumerableRewriter.FindEnumerableMethodForQueryable(), System.Linq.EnumerableRewriter.FindMethod(), and System.Linq.EnumerableRewriter.VisitMethodCall().