Terraria: System.Linq.EnumerableRewriter.VisitConstant
VisitConstant()
override Expression System.Linq.EnumerableRewriter.VisitConstant (ConstantExpression c) inline protected virtual
Reimplemented from System.Linq.Expressions.ExpressionVisitor.
Definition at line 230 of file EnumerableRewriter.cs.
    {
        if (c.Value is EnumerableQuery enumerableQuery)
        {
            if (enumerableQuery.Enumerable != null)
            {
                Type publicType = GetPublicType(enumerableQuery.Enumerable.GetType());
                return Expression.Constant(enumerableQuery.Enumerable, publicType);
            }
            Expression expression = enumerableQuery.Expression;
            if (expression != c)
            {
                return Visit(expression);
            }
        }
        return c;
    }
References System.Linq.Expressions.Expression< TDelegate >.Constant(), System.Linq.EnumerableRewriter.GetPublicType(), System.Linq.Expressions.ConstantExpression.Value, and System.Linq.Expressions.ExpressionVisitor.Visit().