Terraria: System.Linq.EnumerableRewriter.VisitConditional
VisitConditional()
override Expression System.Linq.EnumerableRewriter.VisitConditional (ConditionalExpression c) inline protected virtual
Reimplemented from System.Linq.Expressions.ExpressionVisitor.
Definition at line 373 of file EnumerableRewriter.cs.
    {
        Type type = c.Type;
        if (!typeof(IQueryable).IsAssignableFrom(type))
        {
            return base.VisitConditional(c);
        }
        Expression test = Visit(c.Test);
        Expression expression = Visit(c.IfTrue);
        Expression expression2 = Visit(c.IfFalse);
        Type type2 = expression.Type;
        Type type3 = expression2.Type;
        if (type2.IsAssignableFrom(type3))
        {
            return Expression.Condition(test, expression, expression2, type2);
        }
        if (type3.IsAssignableFrom(type2))
        {
            return Expression.Condition(test, expression, expression2, type3);
        }
        return Expression.Condition(test, expression, expression2, GetEquivalentType(type));
    }
References System.Linq.Expressions.Expression< TDelegate >.Condition(), System.Linq.EnumerableRewriter.GetEquivalentType(), System.Linq.Expressions.ConditionalExpression.IfFalse, System.Linq.Expressions.ConditionalExpression.IfTrue, System.Linq.Expressions.ConditionalExpression.Test, System.Linq.Expressions.ConditionalExpression.Type, System.type, and System.Linq.Expressions.ExpressionVisitor.Visit().