Terraria: System.Linq.EnumerableRewriter.VisitBlock
VisitBlock()
override Expression System.Linq.EnumerableRewriter.VisitBlock (BlockExpression node) inline protected virtual
Reimplemented from System.Linq.Expressions.ExpressionVisitor.
Definition at line 396 of file EnumerableRewriter.cs.
    {
        Type type = node.Type;
        if (!typeof(IQueryable).IsAssignableFrom(type))
        {
            return base.VisitBlock(node);
        }
        ReadOnlyCollection<Expression> expressions = Visit(node.Expressions);
        ReadOnlyCollection<ParameterExpression> variables = VisitAndConvert(node.Variables, "EnumerableRewriter.VisitBlock");
        if (type == node.Expressions.Last().Type)
        {
            return Expression.Block(variables, expressions);
        }
        return Expression.Block(GetEquivalentType(type), variables, expressions);
    }
References System.Linq.Expressions.Expression< TDelegate >.Block(), System.Linq.EnumerableRewriter.GetEquivalentType(), System.type, and System.Linq.Expressions.ExpressionVisitor.Visit().