Terraria: System.Linq.EnumerableRewriter.FindMethod
FindMethod()
static MethodInfo System.Linq.EnumerableRewriter.FindMethod (Type type, string name, ReadOnlyCollection< Expression > args, Type[] typeArgs) inline static private
Definition at line 269 of file EnumerableRewriter.cs.
    {
        using (IEnumerator<MethodInfo> enumerator = (from m in type.GetMethods(BindingFlags.Static | BindingFlags.Public | BindingFlags.NonPublic)
            where m.Name == name
            select m).GetEnumerator())
        {
            if (!enumerator.MoveNext())
            {
                throw Error.NoMethodOnType(name, type);
            }
            do
            {
                MethodInfo current = enumerator.Current;
                if (ArgsMatch(current, args, typeArgs))
                {
                    return (typeArgs != null) ? current.MakeGenericMethod(typeArgs) : current;
                }
            }
            while (enumerator.MoveNext());
        }
        throw Error.NoMethodOnTypeMatchingArguments(name, type);
    }
References System.Linq.EnumerableRewriter.ArgsMatch(), System.Reflection.MethodInfo.MakeGenericMethod(), System.Linq.Error.NoMethodOnType(), System.Linq.Error.NoMethodOnTypeMatchingArguments(), and System.type.
Referenced by System.Linq.EnumerableRewriter.VisitMethodCall().