Terraria: System.Linq.EnumerableRewriter.FixupQuotedExpression
FixupQuotedExpression()
Expression System.Linq.EnumerableRewriter.FixupQuotedExpression (Type type, Expression expression) inline private
Definition at line 79 of file EnumerableRewriter.cs.
    {
        Expression expression2 = expression;
        while (true)
        {
            if (type.IsAssignableFrom(expression2.Type))
            {
                return expression2;
            }
            if (expression2.NodeType != ExpressionType.Quote)
            {
                break;
            }
            expression2 = ((UnaryExpression)expression2).Operand;
        }
        if (!type.IsAssignableFrom(expression2.Type) && type.IsArray && expression2.NodeType == ExpressionType.NewArrayInit)
        {
            Type c = StripExpression(expression2.Type);
            if (type.IsAssignableFrom(c))
            {
                Type elementType = type.GetElementType();
                NewArrayExpression newArrayExpression = (NewArrayExpression)expression2;
                List<Expression> list = new List<Expression>(newArrayExpression.Expressions.Count);
                int i = 0;
                for (int count = newArrayExpression.Expressions.Count; i < count; i++)
                {
                    list.Add(FixupQuotedExpression(elementType, newArrayExpression.Expressions[i]));
                }
                expression = Expression.NewArrayInit(elementType, list);
            }
        }
        return expression;
    }
References System.Linq.count, System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.elementType, System.Linq.EnumerableRewriter.FixupQuotedExpression(), System.Type.GetElementType(), System.list, System.Linq.Expressions.Expression< TDelegate >.NewArrayInit(), System.Linq.EnumerableRewriter.StripExpression(), and System.type.
Referenced by System.Linq.EnumerableRewriter.FixupQuotedArgs(), and System.Linq.EnumerableRewriter.FixupQuotedExpression().