Terraria: System.Linq.EnumerableRewriter.GetEquivalentType
GetEquivalentType()
Type System.Linq.EnumerableRewriter.GetEquivalentType (Type type) inline private
Definition at line 159 of file EnumerableRewriter.cs.
    {
        if (_equivalentTypeCache == null)
        {
            _equivalentTypeCache = new Dictionary<Type, Type>
            {
                {
                    typeof(IQueryable),
                    typeof(IEnumerable)
                },
                {
                    typeof(IEnumerable),
                    typeof(IEnumerable)
                }
            };
        }
        if (!_equivalentTypeCache.TryGetValue(type, out var value))
        {
            Type publicType = GetPublicType(type);
            if (publicType.IsInterface && publicType.IsGenericType)
            {
                Type genericTypeDefinition = publicType.GetGenericTypeDefinition();
                if (genericTypeDefinition == typeof(IOrderedEnumerable<>))
                {
                    value = publicType;
                }
                else if (genericTypeDefinition == typeof(IOrderedQueryable<>))
                {
                    value = typeof(IOrderedEnumerable<>).MakeGenericType(publicType.GenericTypeArguments[0]);
                }
                else if (genericTypeDefinition == typeof(IEnumerable<>))
                {
                    value = publicType;
                }
                else if (genericTypeDefinition == typeof(IQueryable<>))
                {
                    value = typeof(IEnumerable<>).MakeGenericType(publicType.GenericTypeArguments[0]);
                }
            }
            if (value == null)
            {
                value = GetEquivalentTypeToEnumerables(publicType);
            }
            _equivalentTypeCache.Add(type, value);
        }
        return value;
        [UnconditionalSuppressMessage("ReflectionAnalysis", "IL2070:UnrecognizedReflectionPattern", Justification = "The enumerable interface type (IOrderedQueryable<>, IOrderedEnumerable<>, IQueryable<> and IEnumerable<>) is kept since it's directly referenced hereand so it will also be preserved in all places where it's implemented.The GetInterfaces may return less after trimming but it will includethe enumerable interface type if it was there before trimming, which is enough for thismethod to work.")]
        static Type GetEquivalentTypeToEnumerables(Type sourceType)
        {
            Type[] interfaces = sourceType.GetInterfaces();
            var source = (from i in interfaces
                where i.IsGenericType && i.GenericTypeArguments.Length == 1
                select new
                {
                    Info = i,
                    GenType = i.GetGenericTypeDefinition()
                }).ToArray();
            Type type2 = (from i in source
                where i.GenType == typeof(IOrderedQueryable<>) || i.GenType == typeof(IOrderedEnumerable<>)
                select i.Info.GenericTypeArguments[0]).Distinct().SingleOrDefault();
            if (type2 != null)
            {
                return typeof(IOrderedEnumerable<>).MakeGenericType(type2);
            }
            type2 = (from i in source
                where i.GenType == typeof(IQueryable<>) || i.GenType == typeof(IEnumerable<>)
                select i.Info.GenericTypeArguments[0]).Distinct().Single();
            return typeof(IEnumerable<>).MakeGenericType(type2);
        }
    }
References System.Linq.EnumerableRewriter._equivalentTypeCache, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Linq.EnumerableRewriter.GetPublicType(), System.Linq.source, System.Collections.Generic.Dictionary< TKey, TValue >.TryGetValue(), System.type, and System.value.
Referenced by System.Linq.EnumerableRewriter.VisitBlock(), System.Linq.EnumerableRewriter.VisitConditional(), System.Linq.EnumerableRewriter.VisitGoto(), and System.Linq.EnumerableRewriter.VisitLabelTarget().