Terraria: Microsoft.Xna.Framework.BoundingBox.Intersects
Intersects() [9/9]
void Microsoft.Xna.Framework.BoundingBox.Intersects (ref Ray ray, out float? result) inline
Definition at line 341 of file BoundingBox.cs.
    {
        result = null;
        float num = 0f;
        float num2 = float.MaxValue;
        if (Math.Abs(ray.Direction.X) < 1E-06f)
        {
            if (ray.Position.X < Min.X || ray.Position.X > Max.X)
            {
                return;
            }
        }
        else
        {
            float num3 = 1f / ray.Direction.X;
            float num4 = (Min.X - ray.Position.X) * num3;
            float num5 = (Max.X - ray.Position.X) * num3;
            if (num4 > num5)
            {
                float num6 = num4;
                num4 = num5;
                num5 = num6;
            }
            num = MathHelper.Max(num4, num);
            num2 = MathHelper.Min(num5, num2);
            if (num > num2)
            {
                return;
            }
        }
        if (Math.Abs(ray.Direction.Y) < 1E-06f)
        {
            if (ray.Position.Y < Min.Y || ray.Position.Y > Max.Y)
            {
                return;
            }
        }
        else
        {
            float num7 = 1f / ray.Direction.Y;
            float num8 = (Min.Y - ray.Position.Y) * num7;
            float num9 = (Max.Y - ray.Position.Y) * num7;
            if (num8 > num9)
            {
                float num10 = num8;
                num8 = num9;
                num9 = num10;
            }
            num = MathHelper.Max(num8, num);
            num2 = MathHelper.Min(num9, num2);
            if (num > num2)
            {
                return;
            }
        }
        if (Math.Abs(ray.Direction.Z) < 1E-06f)
        {
            if (ray.Position.Z < Min.Z || ray.Position.Z > Max.Z)
            {
                return;
            }
        }
        else
        {
            float num11 = 1f / ray.Direction.Z;
            float num12 = (Min.Z - ray.Position.Z) * num11;
            float num13 = (Max.Z - ray.Position.Z) * num11;
            if (num12 > num13)
            {
                float num14 = num12;
                num12 = num13;
                num13 = num14;
            }
            num = MathHelper.Max(num12, num);
            num2 = MathHelper.Min(num13, num2);
            if (num > num2)
            {
                return;
            }
        }
        result = num;
    }
References System.Math.Abs(), System.E, Microsoft.Xna.Framework.BoundingBox.Max, Microsoft.Xna.Framework.MathHelper.Max(), Microsoft.Xna.Framework.BoundingBox.Min, Microsoft.Xna.Framework.MathHelper.Min(), Microsoft.Xna.Framework.Vector3.X, Microsoft.Xna.Framework.Vector3.Y, and Microsoft.Xna.Framework.Vector3.Z.