Terraria: Microsoft.Xna.Framework.BoundingBox.CreateFromPoints
CreateFromPoints()
static BoundingBox Microsoft.Xna.Framework.BoundingBox.CreateFromPoints (IEnumerable< Vector3 > points) inline static
Definition at line 151 of file BoundingBox.cs.
    {
        if (points == null)
        {
            throw new ArgumentNullException();
        }
        bool flag = false;
        Vector3 value = new Vector3(float.MaxValue);
        Vector3 value2 = new Vector3(float.MinValue);
        foreach (Vector3 point in points)
        {
            Vector3 value3 = point;
            Vector3.Min(ref value, ref value3, out value);
            Vector3.Max(ref value2, ref value3, out value2);
            flag = true;
        }
        if (!flag)
        {
            throw new ArgumentException(FrameworkResources.BoundingBoxZeroPoints);
        }
        return new BoundingBox(value, value2);
    }
References Microsoft.Xna.Framework.BoundingBox.BoundingBox(), Microsoft.Xna.Framework.FrameworkResources.BoundingBoxZeroPoints, Microsoft.Xna.Framework.Vector3.Max(), Microsoft.Xna.Framework.Vector3.Min(), and System.value.