Terraria: System.Linq.Parallel.FirstQueryOperator.FirstQueryOperatorEnumerator.MoveNext
MoveNext() [2/2]
override bool System.Linq.Parallel.FirstQueryOperator< TSource >.FirstQueryOperatorEnumerator< TKey >.MoveNext ([AllowNull] ref TSource currentElement, ref int currentKey) inline package
Definition at line 38 of file FirstQueryOperator.cs.
        {
            if (_alreadySearched)
            {
                return false;
            }
            TSource val = default(TSource);
            TKey val2 = default(TKey);
            try
            {
                TSource currentElement2 = default(TSource);
                TKey currentKey2 = default(TKey);
                int num = 0;
                while (_source.MoveNext(ref currentElement2, ref currentKey2))
                {
                    if ((num++ & 0x3F) == 0)
                    {
                        _cancellationToken.ThrowIfCancellationRequested();
                    }
                    if (_predicate != null && !_predicate(currentElement2))
                    {
                        continue;
                    }
                    val = currentElement2;
                    val2 = currentKey2;
                    lock (_operatorState)
                    {
                        if (_operatorState._partitionId == -1 || _keyComparer.Compare(val2, _operatorState._key) < 0)
{
                            _operatorState._key = val2;
                            _operatorState._partitionId = _partitionId;
                        }
                    }
                    break;
                }
            }
            finally
            {
                _sharedBarrier.Signal();
            }
            _alreadySearched = true;
            if (_partitionId == _operatorState._partitionId)
            {
                _sharedBarrier.Wait(_cancellationToken);
                if (_partitionId == _operatorState._partitionId)
                {
                    currentElement = val;
                    currentKey = 0;
                    return true;
                }
            }
            return false;
        }
References System.Linq.Parallel.FirstQueryOperator< TSource >.FirstQueryOperatorEnumerator< TKey >._alreadySearched, System.Linq.Parallel.FirstQueryOperator< TSource >.FirstQueryOperatorEnumerator< TKey >._cancellationToken, System.Linq.Parallel.FirstQueryOperator< TSource >.FirstQueryOperatorEnumerator< TKey >._keyComparer, System.Linq.Parallel.FirstQueryOperator< TSource >.FirstQueryOperatorEnumerator< TKey >._operatorState, System.Linq.Parallel.FirstQueryOperator< TSource >.FirstQueryOperatorEnumerator< TKey >._partitionId, System.Linq.Parallel.FirstQueryOperator< TSource >.FirstQueryOperatorEnumerator< TKey >._predicate, System.Linq.Parallel.FirstQueryOperator< TSource >.FirstQueryOperatorEnumerator< TKey >._sharedBarrier, System.Linq.Parallel.FirstQueryOperator< TSource >.FirstQueryOperatorEnumerator< TKey >._source, System.Collections.Generic.IComparer< in T >.Compare(), System.Linq.Parallel.QueryOperatorEnumerator< TElement, TKey >.MoveNext(), System.Threading.CountdownEvent.Signal(), System.Threading.CancellationToken.ThrowIfCancellationRequested(), and System.Threading.CountdownEvent.Wait().