Terraria: System.Xml.Serialization.TypeScope.AddTypeMapping
AddTypeMapping()
void System.Xml.Serialization.TypeScope.AddTypeMapping (TypeMapping typeMapping) inline package
Definition at line 930 of file TypeScope.cs.
    {
        _typeMappings.Add(typeMapping);
    }
References System.Xml.Serialization.TypeScope._typeMappings, and System.Collections.ArrayList.Add().
Referenced by System.Xml.Serialization.SoapReflectionImporter.CreateNullableMapping(), System.Xml.Serialization.XmlReflectionImporter.CreateNullableMapping(), System.Xml.Serialization.SoapReflectionImporter.GetRootMapping(), System.Xml.Serialization.XmlReflectionImporter.GetRootMapping(), System.Xml.Serialization.SoapReflectionImporter.ImportArrayLikeMapping(), System.Xml.Serialization.XmlReflectionImporter.ImportArrayLikeMapping(), System.Xml.Serialization.SoapReflectionImporter.ImportEnumMapping(), System.Xml.Serialization.XmlReflectionImporter.ImportEnumMapping(), System.Xml.Serialization.XmlReflectionImporter.ImportSpecialMapping(), System.Xml.Serialization.SoapReflectionImporter.ImportStructLikeMapping(), and System.Xml.Serialization.XmlReflectionImporter.InitializeStructMembers().