Terraria: System.Xml.Serialization.TypeScope.PopulateMemberInfos
PopulateMemberInfos()
static void System.Xml.Serialization.TypeScope.PopulateMemberInfos (StructMapping structMapping, MemberMapping[] mappings, Dictionary< string, MemberInfo > memberInfos) inline static private
Definition at line 678 of file TypeScope.cs.
    {
        memberInfos.Clear();
        for (int i = 0; i < mappings.Length; i++)
        {
            memberInfos[mappings[i].Name] = mappings[i].MemberInfo;
            if (mappings[i].ChoiceIdentifier != null)
            {
                memberInfos[mappings[i].ChoiceIdentifier.MemberName] = mappings[i].ChoiceIdentifier.MemberInfo;
            }
            if (mappings[i].CheckSpecifiedMemberInfo != null)
            {
                memberInfos[mappings[i].Name + "Specified"] = mappings[i].CheckSpecifiedMemberInfo;
            }
        }
        Dictionary<string, MemberInfo> dictionary = null;
        MemberInfo replacedInfo = null;
        foreach (KeyValuePair<string, MemberInfo> memberInfo in memberInfos)
        {
            if (ShouldBeReplaced(memberInfo.Value, structMapping.TypeDesc.Type, out replacedInfo))
            {
                if (dictionary == null)
                {
                    dictionary = new Dictionary<string, MemberInfo>();
                }
                dictionary.Add(memberInfo.Key, replacedInfo);
            }
        }
        if (dictionary == null)
        {
            return;
        }
        foreach (KeyValuePair<string, MemberInfo> item in dictionary)
        {
            memberInfos[item.Key] = item.Value;
        }
        for (int j = 0; j < mappings.Length; j++)
        {
            if (dictionary.TryGetValue(mappings[j].Name, out var value))
            {
                MemberMapping memberMapping = mappings[j].Clone();
                memberMapping.MemberInfo = value;
                mappings[j] = memberMapping;
            }
        }
    }
References System.Xml.Serialization.ChoiceIdentifier, System.Collections.Generic.Dictionary< TKey, TValue >.Clear(), System.dictionary, System.Xml.Dictionary, System.item, System.Xml.Serialization.TypeScope.ShouldBeReplaced(), and System.value.
Referenced by System.Xml.Serialization.TypeScope.GetAllMembers(), and System.Xml.Serialization.TypeScope.GetSettableMembers().