Terraria: System.Xml.Serialization.TypeScope.ParseWsdlArrayType
ParseWsdlArrayType()
static XmlQualifiedName System.Xml.Serialization.TypeScope.ParseWsdlArrayType (string type, out string dims, XmlSchemaObject parent) inline static package
Definition at line 907 of file TypeScope.cs.
    {
        int num = type.LastIndexOf(':');
        string text = ((num > 0) ? type.Substring(0, num) : "");
        int num2 = type.IndexOf('[', num + 1);
        if (num2 <= num)
        {
            throw new InvalidOperationException(System.SR.Format(System.SR.XmlInvalidArrayTypeSyntax, type));
        }
        string name = type.Substring(num + 1, num2 - num - 1);
        dims = type.Substring(num2);
        while (parent != null)
        {
            if (parent.Namespaces != null && parent.Namespaces.TryLookupNamespace(text, out var ns) && ns != null)
            {
                text = ns;
                break;
            }
            parent = parent.Parent;
        }
        return new XmlQualifiedName(name, text);
    }
References System.SR.Format(), System.Xml.Schema.XmlSchemaObject.Namespaces, System.Xml.Schema.XmlSchemaObject.Parent, System.text, System.type, and System.SR.XmlInvalidArrayTypeSyntax.
Referenced by System.Xml.Serialization.SchemaGraph.Depends(), and System.Xml.Serialization.XmlSerializationWriter.WriteXmlAttribute().