Terraria: System.Xml.Serialization.TypeScope.TypeName
TypeName()
static string System.Xml.Serialization.TypeScope.TypeName (Type t) inline static package
Definition at line 546 of file TypeScope.cs.
    {
        if (t.IsArray)
        {
            return "ArrayOf" + TypeName(t.GetElementType());
        }
        if (t.IsGenericType)
        {
            StringBuilder stringBuilder = new StringBuilder();
            StringBuilder stringBuilder2 = new StringBuilder();
            string text = t.Name;
            int num = text.IndexOf('`');
            if (num >= 0)
            {
                text = text.Substring(0, num);
            }
            stringBuilder.Append(text);
            stringBuilder.Append("Of");
            Type[] genericArguments = t.GetGenericArguments();
            for (int i = 0; i < genericArguments.Length; i++)
            {
                stringBuilder.Append(TypeName(genericArguments[i]));
                stringBuilder2.Append(genericArguments[i].Namespace);
            }
            return stringBuilder.ToString();
        }
        return t.Name;
    }
References System.Type.GetElementType(), System.Type.GetGenericArguments(), System.Type.IsArray, System.Type.IsGenericType, System.Reflection.MemberInfo.Name, System.Xml.Schema.Namespace, System.text, and System.Xml.Serialization.TypeScope.TypeName().
Referenced by System.Xml.Serialization.TypeScope.ImportTypeDesc(), and System.Xml.Serialization.TypeScope.TypeName().