Terraria: System.Xml.Serialization.TypeScope.GetDefaultIndexer
GetDefaultIndexer()
static PropertyInfo System.Xml.Serialization.TypeScope.GetDefaultIndexer ([DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicConstructors | DynamicallyAccessedMemberTypes.PublicMethods | DynamicallyAccessedMemberTypes.PublicFields | DynamicallyAccessedMemberTypes.PublicNestedTypes | DynamicallyAccessedMemberTypes.PublicProperties | DynamicallyAccessedMemberTypes.PublicEvents)] Type type, string memberInfo) inline static package
Definition at line 848 of file TypeScope.cs.
    {
        if (typeof(IDictionary).IsAssignableFrom(type))
        {
            if (memberInfo == null)
            {
                throw new NotSupportedException(System.SR.Format(System.SR.XmlUnsupportedIDictionary, type.FullName));
            }
            throw new NotSupportedException(System.SR.Format(System.SR.XmlUnsupportedIDictionaryDetails, memberInfo, type.FullName));
        }
        MemberInfo[] defaultMembers = type.GetDefaultMembers();
        PropertyInfo propertyInfo = null;
        if (defaultMembers != null && defaultMembers.Length != 0)
        {
            Type type2 = type;
            while (type2 != null)
            {
                for (int i = 0; i < defaultMembers.Length; i++)
                {
                    if (!(defaultMembers[i] is PropertyInfo))
                    {
                        continue;
                    }
                    PropertyInfo propertyInfo2 = (PropertyInfo)defaultMembers[i];
                    if (!(propertyInfo2.DeclaringType != type2) && propertyInfo2.CanRead)
                    {
                        MethodInfo getMethod = propertyInfo2.GetMethod;
                        ParameterInfo[] parameters = getMethod.GetParameters();
                        if (parameters.Length == 1 && parameters[0].ParameterType == typeof(int))
{
                            propertyInfo = propertyInfo2;
                            break;
                        }
                    }
                }
                if (propertyInfo != null)
                {
                    break;
                }
                type2 = type2.BaseType;
            }
        }
        if (propertyInfo == null)
        {
            throw new InvalidOperationException(System.SR.Format(System.SR.XmlNoDefaultAccessors, type.FullName));
        }
        MethodInfo method = type.GetMethod("Add", new Type[1] { propertyInfo.PropertyType });
        if (method == null)
        {
            throw new InvalidOperationException(System.SR.Format(System.SR.XmlNoAddMethod, type.FullName, propertyInfo.PropertyType, "ICollection"));
        }
        return propertyInfo;
    }
References System.Xml.Dictionary, System.SR.Format(), System.Reflection.ParameterInfo.ParameterType, System.Reflection.PropertyInfo.PropertyType, System.type, System.SR.XmlNoAddMethod, System.SR.XmlNoDefaultAccessors, System.SR.XmlUnsupportedIDictionary, and System.SR.XmlUnsupportedIDictionaryDetails.
Referenced by System.Xml.Serialization.TypeScope.GetCollectionElementType(), and System.Xml.Serialization.ReflectionAwareCodeGen.WriteDefaultIndexerInit().