Terraria: System.Xml.Serialization.TypeScope.GetArrayTypeDesc
GetArrayTypeDesc()
TypeDesc System.Xml.Serialization.TypeScope.GetArrayTypeDesc (Type type) inline package
Definition at line 280 of file TypeScope.cs.
    {
        TypeDesc typeDesc = (TypeDesc)_arrayTypeDescs[type];
        if (typeDesc == null)
        {
            typeDesc = GetTypeDesc(type);
            if (!typeDesc.IsArrayLike)
            {
                typeDesc = ImportTypeDesc(type, null, directReference: false);
            }
            typeDesc.CheckSupported();
            _arrayTypeDescs.Add(type, typeDesc);
        }
        return typeDesc;
    }
References System.Xml.Serialization.TypeScope._arrayTypeDescs, System.Collections.Hashtable.Add(), System.Xml.Dictionary, System.Xml.Serialization.TypeScope.GetTypeDesc(), System.Xml.Serialization.TypeScope.ImportTypeDesc(), and System.type.
Referenced by System.Xml.Serialization.ModelScope.GetArrayModel(), and System.Xml.Serialization.XmlReflectionImporter.ImportAccessorMapping().