Terraria: System.Xml.Serialization.TypeScope.GetTypeDesc
GetTypeDesc() [1/6]
TypeDesc System.Xml.Serialization.TypeScope.GetTypeDesc (string name, string ns) inline package
Definition at line 224 of file TypeScope.cs.
    {
        return GetTypeDesc(name, ns, (TypeFlags)56);
    }
References System.Xml.Serialization.TypeScope.GetTypeDesc().
Referenced by System.Xml.Serialization.XmlSerializationCodeGen.XmlSerializationCodeGen(), System.Xml.Serialization.XmlSerializationILGen.XmlSerializationILGen(), System.Xml.Serialization.XmlReflectionImporter.CreateArrayElementsFromAttributes(), System.Xml.Serialization.SchemaImporter.CreateRootMapping(), System.Xml.Serialization.SoapReflectionImporter.CreateRootMapping(), System.Xml.Serialization.XmlReflectionImporter.CreateRootMapping(), System.Xml.Serialization.XmlSerializationWriter.CreateUnknownTypeException(), System.Xml.Serialization.TypeScope.GetArrayTypeDesc(), System.Xml.Serialization.SoapReflectionImporter.GetDefaultValue(), System.Xml.Serialization.XmlReflectionImporter.GetTopLevelMapping(), System.Xml.Serialization.TypeScope.GetTypeDesc(), System.Xml.Serialization.TypeScope.GetTypeDesc(), System.Xml.Serialization.TypeScope.GetTypeDesc(), System.Xml.Serialization.ModelScope.GetTypeModel(), System.Xml.Serialization.SoapReflectionImporter.ImportAccessorMapping(), System.Xml.Serialization.XmlReflectionImporter.ImportAccessorMapping(), System.Xml.Serialization.XmlReflectionImporter.ImportArrayLikeMapping(), System.Xml.Serialization.XmlReflectionImporter.ImportMemberMapping(), System.Xml.Serialization.SoapReflectionImporter.ImportMemberMapping(), System.Xml.Serialization.XmlReflectionImporter.ImportMembersMapping(), System.Xml.Serialization.SoapReflectionImporter.ImportMembersMapping(), System.Xml.Serialization.XmlReflectionImporter.ImportPrimitiveMapping(), System.Xml.Serialization.SoapReflectionImporter.ImportPrimitiveMapping(), System.Xml.Serialization.TypeScope.ImportTypeDesc(), System.Xml.Serialization.SoapReflectionImporter.ImportTypeMapping(), System.Xml.Serialization.XmlReflectionImporter.ImportTypeMapping(), System.Xml.Serialization.SchemaImporter.MakeDerived(), System.Xml.Serialization.ReflectionAwareCodeGen.WriteTypeInfo(), System.Xml.Serialization.SoapReflectionImporter.XsdTypeName(), and System.Xml.Serialization.XmlReflectionImporter.XsdTypeName().