Terraria: System.Xml.Serialization.TypeScope.GetEnumeratorElementType
GetEnumeratorElementType()
static Type System.Xml.Serialization.TypeScope.GetEnumeratorElementType (Type type, ref TypeFlags flags) inline static private
Definition at line 797 of file TypeScope.cs.
    {
        if (typeof(IEnumerable).IsAssignableFrom(type))
        {
            MethodInfo methodInfo = type.GetMethod("GetEnumerator", Type.EmptyTypes);
            if (methodInfo == null || !typeof(IEnumerator).IsAssignableFrom(methodInfo.ReturnType))
            {
                methodInfo = null;
                MemberInfo[] member = type.GetMember("System.Collections.Generic.IEnumerable<*", BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic);
                foreach (MemberInfo memberInfo in member)
                {
                    methodInfo = memberInfo as MethodInfo;
                    if (methodInfo != null && typeof(IEnumerator).IsAssignableFrom(methodInfo.ReturnType))
                    {
                        flags |= TypeFlags.GenericInterface;
                        break;
                    }
                    methodInfo = null;
                }
                if (methodInfo == null)
                {
                    flags |= TypeFlags.UsePrivateImplementation;
                    methodInfo = type.GetMethod("System.Collections.IEnumerable.GetEnumerator", BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, Type.EmptyTypes);
                }
            }
            if (methodInfo == null || !typeof(IEnumerator).IsAssignableFrom(methodInfo.ReturnType))
            {
                return null;
            }
            XmlAttributes xmlAttributes = new XmlAttributes(methodInfo);
            if (xmlAttributes.XmlIgnore)
            {
                return null;
            }
            PropertyInfo property = methodInfo.ReturnType.GetProperty("Current");
            Type type2 = ((property == null) ? typeof(object) : property.PropertyType);
            MethodInfo method = type.GetMethod("Add", new Type[1] { type2 });
            if (method == null && type2 != typeof(object))
            {
                type2 = typeof(object);
                method = type.GetMethod("Add", new Type[1] { type2 });
            }
            if (method == null)
            {
                throw new InvalidOperationException(System.SR.Format(System.SR.XmlNoAddMethod, type.FullName, type2, "IEnumerable"));
            }
            return type2;
        }
        return null;
    }
References System.Xml.Dictionary, System.Type.EmptyTypes, System.SR.Format(), System.type, and System.SR.XmlNoAddMethod.
Referenced by System.Xml.Serialization.TypeScope.GetArrayElementType(), and System.Xml.Serialization.TypeScope.ImportTypeDesc().