Terraria: System.Xml.Serialization.TypeScope.GetSettableMembers
GetSettableMembers() [3/3]
static MemberMapping[] System.Xml.Serialization.TypeScope.GetSettableMembers (StructMapping structMapping) inline static package
Definition at line 628 of file TypeScope.cs.
    {
        List<MemberMapping> list = new List<MemberMapping>();
        GetSettableMembers(structMapping, list);
        return list.ToArray();
    }
References System.Xml.Dictionary, System.Xml.Serialization.TypeScope.GetSettableMembers(), and System.list.
Referenced by System.Xml.Serialization.TypeScope.GetSettableMembers(), System.Xml.Serialization.TypeScope.GetSettableMembers(), System.Xml.Serialization.TypeScope.GetSettableMembers(), System.Xml.Serialization.ReflectionXmlSerializationReader.WriteEncodedStructMethod(), System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteEncodedStructMethod(), System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteLiteralStructMethod(), System.Xml.Serialization.XmlSerializationReaderILGen.WriteLiteralStructMethod(), and System.Xml.Serialization.ReflectionXmlSerializationReader.WriteLiteralStructMethod().