Terraria: SteelSeriesDeviceGroup.UpdateDeviceList
UpdateDeviceList()
void SteelSeriesDeviceGroup.UpdateDeviceList (List< RgbDevice > deviceList) inline private
     {
         foreach (RgbDevice device in deviceList)
         {
             if (!(device is IGameSenseDevice gameSenseDevice))
             {
                 continue;
             }
             List<JObject> list = gameSenseDevice.TryGetEventUpdateRequest();
             if (list == null)
             {
                 continue;
             }
             for (int i = 0; i < list.Count; i++)
             {
                 JObject jObject = list[i];
                 if (jObject != null)
                 {
                     jObject.Add("game", JToken.op_Implicit(_gameSenseConnection.GameName));
                     string fullEventJson = ((JToken)jObject).ToString((Formatting)0, Array.Empty<JsonConverter>());
                     _gameSenseConnection.SendEvent(fullEventJson);
                 }
             }
         }
         foreach (IGameSenseUpdater miscEvent in _miscEvents)
         {
             List<JObject> list2 = miscEvent.TryGetEventUpdateRequest();
             if (list2 == null)
             {
                 continue;
             }
             for (int j = 0; j < list2.Count; j++)
             {
                 JObject jObject2 = list2[j];
                 if (jObject2 != null)
                 {
                     jObject2.Add("game", JToken.op_Implicit(_gameSenseConnection.GameName));
                     string fullEventJson2 = ((JToken)jObject2).ToString((Formatting)0, Array.Empty<JsonConverter>());
                     _gameSenseConnection.SendEvent(fullEventJson2);
                 }
             }
         }
     }
References _gameSenseConnection, _miscEvents, GameSenseConnection.GameName, GameSenseConnection.SendEvent(), and IGameSenseUpdater.TryGetEventUpdateRequest().
Referenced by SendRelevantChangesToGameSense().