Terraria: System.Xml.Serialization.TypeScope.GetSettableMembers
GetSettableMembers() [2/3]
static void System.Xml.Serialization.TypeScope.GetSettableMembers (StructMapping mapping, List< MemberMapping > list) inline static private
Definition at line 635 of file TypeScope.cs.
    {
        if (mapping.BaseMapping != null)
        {
            GetSettableMembers(mapping.BaseMapping, list);
        }
        if (mapping.Members == null)
        {
            return;
        }
        MemberMapping[] members = mapping.Members;
        foreach (MemberMapping memberMapping in members)
        {
            MemberInfo memberInfo = memberMapping.MemberInfo;
            PropertyInfo propertyInfo = memberInfo as PropertyInfo;
            if (propertyInfo != null && !CanWriteProperty(propertyInfo, memberMapping.TypeDesc))
            {
                throw new InvalidOperationException(System.SR.Format(System.SR.XmlReadOnlyPropertyError, propertyInfo.DeclaringType, propertyInfo.Name));
            }
            list.Add(memberMapping);
        }
    }
References System.Xml.Serialization.TypeScope.CanWriteProperty(), System.Reflection.MemberInfo.DeclaringType, System.SR.Format(), System.Xml.Serialization.TypeScope.GetSettableMembers(), System.list, System.Reflection.MemberInfo.Name, and System.SR.XmlReadOnlyPropertyError.