Terraria: System.Xml.Serialization.TypeScope.AddNonXsdPrimitive
AddNonXsdPrimitive()
static void System.Xml.Serialization.TypeScope.AddNonXsdPrimitive ([DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.All)] Type type, string dataTypeName, string ns, string formatterName, XmlQualifiedName baseTypeName, XmlSchemaFacet[] facets, TypeFlags flags) inline static private
Definition at line 199 of file TypeScope.cs.
    {
        XmlSchemaSimpleType xmlSchemaSimpleType = new XmlSchemaSimpleType();
        xmlSchemaSimpleType.Name = dataTypeName;
        XmlSchemaSimpleTypeRestriction xmlSchemaSimpleTypeRestriction = new XmlSchemaSimpleTypeRestriction();
        xmlSchemaSimpleTypeRestriction.BaseTypeName = baseTypeName;
        foreach (XmlSchemaFacet item in facets)
        {
            xmlSchemaSimpleTypeRestriction.Facets.Add(item);
        }
        xmlSchemaSimpleType.Content = xmlSchemaSimpleTypeRestriction;
        TypeDesc value = new TypeDesc(type, isXsdType: false, xmlSchemaSimpleType, formatterName, flags);
        if (s_primitiveTypes[type] == null)
        {
            s_primitiveTypes.Add(type, value);
        }
        s_primitiveDataTypes.Add(xmlSchemaSimpleType, value);
        s_primitiveNames.Add(dataTypeName, ns, value);
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Xml.Dictionary, System.item, System.Xml.Serialization.TypeScope.s_primitiveDataTypes, System.Xml.Serialization.TypeScope.s_primitiveNames, System.Xml.Serialization.TypeScope.s_primitiveTypes, System.type, and System.value.
Referenced by System.Xml.Serialization.TypeScope.TypeScope(), and System.Xml.Serialization.TypeScope.AddSoapEncodedPrimitive().