Terraria: System.Xml.Serialization.TypeScope.TypeScope
TypeScope()
static System.Xml.Serialization.TypeScope.TypeScope () inline static private
Definition at line 32 of file TypeScope.cs.
    {
        s_primitiveTypes = new Hashtable();
        s_primitiveDataTypes = new Hashtable();
        s_primitiveNames = new NameTable();
        s_unsupportedTypes = new string[20]
        {
            "anyURI", "duration", "ENTITY", "ENTITIES", "gDay", "gMonth", "gMonthDay", "gYear", "gYearMonth", "ID",
            "IDREF", "IDREFS", "integer", "language", "negativeInteger", "nonNegativeInteger", "nonPositiveInteger", "NOTATION", "positiveInteger", "token"
        };
        AddPrimitive(typeof(string), "string", "String", (TypeFlags)2106);
        AddPrimitive(typeof(int), "int", "Int32", (TypeFlags)4136);
        AddPrimitive(typeof(bool), "boolean", "Boolean", (TypeFlags)4136);
        AddPrimitive(typeof(short), "short", "Int16", (TypeFlags)4136);
        AddPrimitive(typeof(long), "long", "Int64", (TypeFlags)4136);
        AddPrimitive(typeof(float), "float", "Single", (TypeFlags)4136);
        AddPrimitive(typeof(double), "double", "Double", (TypeFlags)4136);
        AddPrimitive(typeof(decimal), "decimal", "Decimal", (TypeFlags)4136);
        AddPrimitive(typeof(DateTime), "dateTime", "DateTime", (TypeFlags)4200);
        AddPrimitive(typeof(XmlQualifiedName), "QName", "XmlQualifiedName", (TypeFlags)5226);
        AddPrimitive(typeof(byte), "unsignedByte", "Byte", (TypeFlags)4136);
        AddPrimitive(typeof(sbyte), "byte", "SByte", (TypeFlags)4136);
        AddPrimitive(typeof(ushort), "unsignedShort", "UInt16", (TypeFlags)4136);
        AddPrimitive(typeof(uint), "unsignedInt", "UInt32", (TypeFlags)4136);
        AddPrimitive(typeof(ulong), "unsignedLong", "UInt64", (TypeFlags)4136);
        AddPrimitive(typeof(DateTime), "date", "Date", (TypeFlags)4328);
        AddPrimitive(typeof(DateTime), "time", "Time", (TypeFlags)4328);
        AddPrimitive(typeof(string), "Name", "XmlName", (TypeFlags)234);
        AddPrimitive(typeof(string), "NCName", "XmlNCName", (TypeFlags)234);
        AddPrimitive(typeof(string), "NMTOKEN", "XmlNmToken", (TypeFlags)234);
        AddPrimitive(typeof(string), "NMTOKENS", "XmlNmTokens", (TypeFlags)234);
        AddPrimitive(typeof(byte[]), "base64Binary", "ByteArrayBase64", (TypeFlags)6890);
        AddPrimitive(typeof(byte[]), "hexBinary", "ByteArrayHex", (TypeFlags)6890);
        XmlSchemaPatternFacet xmlSchemaPatternFacet = new XmlSchemaPatternFacet
        {
            Value = "[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}"
        };
        AddNonXsdPrimitive(typeof(Guid), "guid", "http://microsoft.com/wsdl/types/", "Guid", new XmlQualifiedName("string", "http://www.w3.org/2001/XMLSchema"), new XmlSchemaFacet[1] { xmlSchemaPatternFacet }, (TypeFlags)4648);
        AddNonXsdPrimitive(typeof(char), "char", "http://microsoft.com/wsdl/types/", "Char", new XmlQualifiedName("unsignedShort", "http://www.w3.org/2001/XMLSchema"), Array.Empty<XmlSchemaFacet>(), (TypeFlags)616);
        AddNonXsdPrimitive(typeof(TimeSpan), "TimeSpan", "http://microsoft.com/wsdl/types/", "TimeSpan", new XmlQualifiedName("duration", "http://www.w3.org/2001/XMLSchema"), Array.Empty<XmlSchemaFacet>(), (TypeFlags)4136);
        AddNonXsdPrimitive(typeof(DateTimeOffset), "dateTimeOffset", "http://microsoft.com/wsdl/types/", "DateTimeOffset", new XmlQualifiedName("dateTime", "http://www.w3.org/2001/XMLSchema"), Array.Empty<XmlSchemaFacet>(), (TypeFlags)4136);
        AddSoapEncodedTypes("http://schemas.xmlsoap.org/soap/encoding/");
        AddPrimitive(typeof(string), "normalizedString", "String", (TypeFlags)2234);
        for (int i = 0; i < s_unsupportedTypes.Length; i++)
        {
            AddPrimitive(typeof(string), s_unsupportedTypes[i], "String", (TypeFlags)32954);
        }
    }
References System.Xml.Serialization.TypeScope.AddNonXsdPrimitive(), System.Xml.Serialization.TypeScope.AddPrimitive(), System.Xml.Serialization.TypeScope.AddSoapEncodedTypes(), System.Xml.Dictionary, System.Xml.Serialization.TypeScope.s_primitiveDataTypes, System.Xml.Serialization.TypeScope.s_primitiveNames, System.Xml.Serialization.TypeScope.s_primitiveTypes, and System.Xml.Serialization.TypeScope.s_unsupportedTypes.