Terraria: System.Xml.Serialization.TypeScope.ImportTypeDesc
ImportTypeDesc()
TypeDesc System.Xml.Serialization.TypeScope.ImportTypeDesc (Type type, MemberInfo memberInfo, bool directReference) inline private
Definition at line 325 of file TypeScope.cs.
    {
        TypeDesc typeDesc = null;
        Type type2 = null;
        Type type3 = null;
        TypeFlags flags = TypeFlags.None;
        Exception exception = null;
        if (!type.IsVisible)
        {
            flags |= TypeFlags.Unsupported;
            exception = new InvalidOperationException(System.SR.Format(System.SR.XmlTypeInaccessible, type.FullName));
        }
        else if (directReference && type.IsAbstract && type.IsSealed)
        {
            flags |= TypeFlags.Unsupported;
            exception = new InvalidOperationException(System.SR.Format(System.SR.XmlTypeStatic, type.FullName));
        }
        if (DynamicAssemblies.IsTypeDynamic(type))
        {
            flags |= TypeFlags.UseReflection;
        }
        if (!type.IsValueType)
        {
            flags |= TypeFlags.Reference;
        }
        TypeKind typeKind;
        if (type == typeof(object))
        {
            typeKind = TypeKind.Root;
            flags |= TypeFlags.HasDefaultConstructor;
        }
        else if (type == typeof(ValueType))
        {
            typeKind = TypeKind.Enum;
            flags |= TypeFlags.Unsupported;
            if (exception == null)
            {
                exception = new NotSupportedException(System.SR.Format(System.SR.XmlSerializerUnsupportedType, type.FullName));
            }
        }
        else if (type == typeof(void))
        {
            typeKind = TypeKind.Void;
        }
        else if (typeof(IXmlSerializable).IsAssignableFrom(type))
        {
            typeKind = TypeKind.Serializable;
            flags |= (TypeFlags)36;
            flags |= GetConstructorFlags(type, ref exception);
        }
        else if (type.IsArray)
        {
            typeKind = TypeKind.Array;
            if (type.GetArrayRank() > 1)
            {
                flags |= TypeFlags.Unsupported;
                if (exception == null)
                {
                    exception = new NotSupportedException(System.SR.Format(System.SR.XmlUnsupportedRank, type.FullName));
                }
            }
            type2 = type.GetElementType();
            flags |= TypeFlags.HasDefaultConstructor;
        }
        else if (typeof(ICollection).IsAssignableFrom(type) && !IsArraySegment(type))
        {
            typeKind = TypeKind.Collection;
            type2 = GetCollectionElementType(type, (memberInfo == null) ? null : (memberInfo.DeclaringType.FullName + "." + memberInfo.Name));
            flags |= GetConstructorFlags(type, ref exception);
        }
        else if (type == typeof(XmlQualifiedName))
        {
            typeKind = TypeKind.Primitive;
        }
        else if (type.IsPrimitive)
        {
            typeKind = TypeKind.Primitive;
            flags |= TypeFlags.Unsupported;
            if (exception == null)
            {
                exception = new NotSupportedException(System.SR.Format(System.SR.XmlSerializerUnsupportedType, type.FullName));
            }
        }
        else if (type.IsEnum)
        {
            typeKind = TypeKind.Enum;
        }
        else if (type.IsValueType)
        {
            typeKind = TypeKind.Struct;
            if (IsOptionalValue(type))
            {
                type3 = type.GetGenericArguments()[0];
                flags |= TypeFlags.OptionalValue;
            }
            else
            {
                type3 = type.BaseType;
            }
            if (type.IsAbstract)
            {
                flags |= TypeFlags.Abstract;
            }
        }
        else if (type.IsClass)
        {
            if (type == typeof(XmlAttribute))
            {
                typeKind = TypeKind.Attribute;
                flags |= (TypeFlags)12;
            }
            else if (typeof(XmlNode).IsAssignableFrom(type))
            {
                typeKind = TypeKind.Node;
                type3 = type.BaseType;
                flags |= (TypeFlags)52;
                if (typeof(XmlText).IsAssignableFrom(type))
                {
                    flags &= (TypeFlags)(-33);
                }
                else if (typeof(XmlElement).IsAssignableFrom(type))
                {
                    flags &= (TypeFlags)(-17);
                }
                else if (type.IsAssignableFrom(typeof(XmlAttribute)))
                {
                    flags |= TypeFlags.CanBeAttributeValue;
                }
            }
            else
            {
                typeKind = TypeKind.Class;
                type3 = type.BaseType;
                if (type.IsAbstract)
                {
                    flags |= TypeFlags.Abstract;
                }
            }
        }
        else if (type.IsInterface)
        {
            typeKind = TypeKind.Void;
            flags |= TypeFlags.Unsupported;
            if (exception == null)
            {
                exception = ((!(memberInfo == null)) ? new NotSupportedException(System.SR.Format(System.SR.XmlUnsupportedInterfaceDetails, memberInfo.DeclaringType.FullName + "." + memberInfo.Name, type.FullName)) : new NotSupportedException(System.SR.Format(System.SR.XmlUnsupportedInterface, type.FullName)));
            }
        }
        else
        {
            typeKind = TypeKind.Void;
            flags |= TypeFlags.Unsupported;
            if (exception == null)
            {
                exception = new NotSupportedException(System.SR.Format(System.SR.XmlSerializerUnsupportedType, type.FullName));
            }
        }
        if (typeKind == TypeKind.Class && !type.IsAbstract)
        {
            flags |= GetConstructorFlags(type, ref exception);
        }
        if ((typeKind == TypeKind.Struct || typeKind == TypeKind.Class) && typeof(IEnumerable).IsAssignableFrom(type) && !IsArraySegment(type))
        {
            type2 = GetEnumeratorElementType(type, ref flags);
            typeKind = TypeKind.Enumerable;
            flags |= GetConstructorFlags(type, ref exception);
        }
        typeDesc = new TypeDesc(type, CodeIdentifier.MakeValid(TypeName(type)), type.ToString(), typeKind, null, flags, null);
        typeDesc.Exception = exception;
        if (directReference && (typeDesc.IsClass || typeKind == TypeKind.Serializable))
        {
            typeDesc.CheckNeedConstructor();
        }
        if (typeDesc.IsUnsupported)
        {
            return typeDesc;
        }
        _typeDescs.Add(type, typeDesc);
        if (type2 != null)
        {
            TypeDesc typeDesc2 = GetTypeDesc(type2, memberInfo, directReference: true, throwOnError: false);
            if (directReference && (typeDesc2.IsCollection || typeDesc2.IsEnumerable) && !typeDesc2.IsPrimitive)
            {
                typeDesc2.CheckNeedConstructor();
            }
            typeDesc.ArrayElementTypeDesc = typeDesc2;
        }
        if (type3 != null && type3 != typeof(object) && type3 != typeof(ValueType))
        {
            typeDesc.BaseTypeDesc = GetTypeDesc(type3, memberInfo, directReference: false, throwOnError: false);
        }
        if (type.IsNestedPublic)
        {
            Type declaringType = type.DeclaringType;
            while (declaringType != null && !declaringType.ContainsGenericParameters && (!declaringType.IsAbstract || !declaringType.IsSealed))
            {
                GetTypeDesc(declaringType, null, directReference: false);
                declaringType = declaringType.DeclaringType;
            }
        }
        return typeDesc;
    }
References System.Xml.Serialization.TypeScope._typeDescs, System.Collections.Hashtable.Add(), System.Xml.Dictionary, System.exception, System.SR.Format(), System.Xml.Serialization.TypeScope.GetCollectionElementType(), System.Xml.Serialization.TypeScope.GetConstructorFlags(), System.Xml.Serialization.TypeScope.GetEnumeratorElementType(), System.Xml.Serialization.TypeScope.GetTypeDesc(), System.Xml.Serialization.TypeScope.IsArraySegment(), System.Xml.Serialization.TypeScope.IsOptionalValue(), System.Xml.Serialization.DynamicAssemblies.IsTypeDynamic(), System.Xml.Serialization.CodeIdentifier.MakeValid(), System.type, System.Xml.Serialization.TypeScope.TypeName(), System.SR.XmlSerializerUnsupportedType, System.SR.XmlTypeInaccessible, System.SR.XmlTypeStatic, System.SR.XmlUnsupportedInterface, System.SR.XmlUnsupportedInterfaceDetails, and System.SR.XmlUnsupportedRank.
Referenced by System.Xml.Serialization.TypeScope.GetArrayTypeDesc(), and System.Xml.Serialization.TypeScope.GetTypeDesc().