Terraria: System.Xml.Serialization.TypeScope.GetArrayElementType
GetArrayElementType()
static Type System.Xml.Serialization.TypeScope.GetArrayElementType (Type type, string memberInfo) inline static package
Definition at line 576 of file TypeScope.cs.
    {
        if (type.IsArray)
        {
            return type.GetElementType();
        }
        if (IsArraySegment(type))
        {
            return null;
        }
        if (typeof(ICollection).IsAssignableFrom(type))
        {
            return GetCollectionElementType(type, memberInfo);
        }
        if (typeof(IEnumerable).IsAssignableFrom(type))
        {
            TypeFlags flags = TypeFlags.None;
            return GetEnumeratorElementType(type, ref flags);
        }
        return null;
    }
References System.Xml.Dictionary, System.Xml.Serialization.TypeScope.GetCollectionElementType(), System.Xml.Serialization.TypeScope.GetEnumeratorElementType(), System.Xml.Serialization.TypeScope.IsArraySegment(), and System.type.
Referenced by System.Xml.Serialization.XmlReflectionImporter.ImportAccessorMapping(), System.Xml.Serialization.XmlSerializationReader.ReadArray(), and System.Xml.Serialization.XmlSerializationWriter.WriteArray().