Terraria: System.Int16.Parse
Parse() [7/13]
static short System.Int16.Parse (string s) inline static
Definition at line 103 of file Int16.cs.
    {
        if (s == null)
        {
            ThrowHelper.ThrowArgumentNullException(ExceptionArgument.s);
        }
        return Parse((ReadOnlySpan<char>)s, NumberStyles.Integer, NumberFormatInfo.CurrentInfo);
    }
References System.Globalization.NumberFormatInfo.CurrentInfo, System.Int16.Parse(), System.s, and System.ThrowHelper.ThrowArgumentNullException().
Referenced by System.Int16.Parse(), System.Int16.Parse(), System.Int16.Parse(), System.Int16.Parse(), System.Int16.Parse(), System.Int16.Parse(), System.Int16.Parse(), System.Int16.Parse(), and System.Int16.Parse().