Terraria: System.Int16.TryParse
TryParse() [6/13]
static bool System.Int16.TryParse ([NotNullWhen(true)] string? s, out short result) inline static
Definition at line 162 of file Int16.cs.
    {
        if (s == null)
        {
            result = 0;
            return false;
        }
        return TryParse((ReadOnlySpan<char>)s, NumberStyles.Integer, NumberFormatInfo.CurrentInfo, out result);
    }
References System.Globalization.NumberFormatInfo.CurrentInfo, System.s, and System.Int16.TryParse().
Referenced by System.Int16.TryParse(), System.Int16.TryParse(), System.Int16.TryParse(), System.Int16.TryParse(), System.Int16.TryParse(), System.Int16.TryParse(), System.Int16.TryParse(), and System.Int16.TryParse().