Terraria: System.Net.HttpListener._uriPrefixes
_uriPrefixes
Hashtable System.Net.HttpListener._uriPrefixes = new Hashtable() package
Definition at line 192 of file HttpListener.cs.
Referenced by System.Net.HttpListener.AddAllPrefixes(), System.Net.HttpListener.AddPrefix(), System.Net.HttpListener.ContainsPrefix(), System.Net.HttpListener.GetContext(), System.Net.HttpListener.RemoveAll(), and System.Net.HttpListener.RemovePrefix().