Terraria: System.Net.HttpListener.AttachRequestQueueToUrlGroup
AttachRequestQueueToUrlGroup()
unsafe void System.Net.HttpListener.AttachRequestQueueToUrlGroup () inline private
Definition at line 704 of file HttpListener.cs.
    {
        global::Interop.HttpApi.HTTP_BINDING_INFO hTTP_BINDING_INFO = default(global::Interop.HttpApi.HTTP_BINDING_INFO);
        hTTP_BINDING_INFO.Flags = global::Interop.HttpApi.HTTP_FLAGS.HTTP_RECEIVE_REQUEST_FLAG_COPY_BODY;
        hTTP_BINDING_INFO.RequestQueueHandle = _currentSession.RequestQueueHandle.DangerousGetHandle();
        IntPtr info = new IntPtr(&hTTP_BINDING_INFO);
        SetUrlGroupProperty(global::Interop.HttpApi.HTTP_SERVER_PROPERTY.HttpServerBindingProperty, info, (uint)Marshal.SizeOf(typeof(global::Interop.HttpApi.HTTP_BINDING_INFO)));
    }
References System.Net.HttpListener._currentSession, System.Runtime.InteropServices.SafeHandle.DangerousGetHandle(), System.info, System.Net.HttpListenerSession.RequestQueueHandle, System.Net.HttpListener.SetUrlGroupProperty(), and System.Runtime.InteropServices.Marshal.SizeOf().
Referenced by System.Net.HttpListener.Start().