Terraria: System.Net.HttpListener.RemovePrefix
RemovePrefix()
bool System.Net.HttpListener.RemovePrefix (string uriPrefix) inline package
Definition at line 482 of file HttpListener.cs.
    {
        try
        {
            CheckDisposed();
            if (System.Net.NetEventSource.Log.IsEnabled())
            {
                System.Net.NetEventSource.Info(this, $"uriPrefix: {uriPrefix}", "RemovePrefix");
            }
            if (uriPrefix == null)
            {
                throw new ArgumentNullException("uriPrefix");
            }
            if (!_uriPrefixes.Contains(uriPrefix))
            {
                return false;
            }
            if (_state == State.Started)
            {
                RemovePrefixCore((string)_uriPrefixes[uriPrefix]);
            }
            _uriPrefixes.Remove(uriPrefix);
            _defaultServiceNames.Remove(uriPrefix);
        }
        catch (Exception message)
        {
            if (System.Net.NetEventSource.Log.IsEnabled())
            {
                System.Net.NetEventSource.Error(this, message, "RemovePrefix");
            }
            throw;
        }
        return true;
    }
References System.Net.HttpListener._defaultServiceNames, System.Net.HttpListener._state, System.Net.HttpListener._uriPrefixes, System.Net.HttpListener.CheckDisposed(), System.Collections.Hashtable.Contains(), System.Net.NetEventSource.Error(), System.Net.NetEventSource.Info(), System.Net.NetEventSource.Log, System.Collections.Hashtable.Remove(), System.Net.ServiceNameStore.Remove(), and System.Net.HttpListener.RemovePrefixCore().
Referenced by System.Net.HttpListenerPrefixCollection.Remove().