Terraria: System.Net.HttpResponseStreamAsyncResult.Callback
Callback()
static unsafe void System.Net.HttpResponseStreamAsyncResult.Callback (uint errorCode, uint numBytes, NativeOverlapped * nativeOverlapped) inline static private
Definition at line 187 of file HttpResponseStreamAsyncResult.cs.
    {
        object nativeOverlappedState = ThreadPoolBoundHandle.GetNativeOverlappedState(nativeOverlapped);
        HttpResponseStreamAsyncResult asyncResult = nativeOverlappedState as HttpResponseStreamAsyncResult;
        if (System.Net.NetEventSource.Log.IsEnabled())
        {
            System.Net.NetEventSource.Info(null, "errorCode:0x" + errorCode.ToString("x8") + " numBytes:" + numBytes + " nativeOverlapped:0x" + ((IntPtr)nativeOverlapped).ToString("x8"), "Callback");
        }
        IOCompleted(asyncResult, errorCode, numBytes);
    }
References System.Net.HttpResponseStreamAsyncResult.HttpResponseStreamAsyncResult(), System.asyncResult, System.Threading.ThreadPoolBoundHandle.GetNativeOverlappedState(), System.Net.NetEventSource.Info(), System.Net.HttpResponseStreamAsyncResult.IOCompleted(), and System.Net.NetEventSource.Log.