Terraria: System.Net.HttpListener.RemoveAll
RemoveAll()
void System.Net.HttpListener.RemoveAll (bool clear) inline package
Definition at line 517 of file HttpListener.cs.
    {
        CheckDisposed();
        if (_uriPrefixes.Count <= 0)
        {
            return;
        }
        if (_state == State.Started)
        {
            foreach (string value in _uriPrefixes.Values)
            {
                RemovePrefixCore(value);
            }
        }
        if (clear)
        {
            _uriPrefixes.Clear();
            _defaultServiceNames.Clear();
        }
    }
References System.Net.HttpListener._defaultServiceNames, System.Net.HttpListener._state, System.Net.HttpListener._uriPrefixes, System.Net.HttpListener.CheckDisposed(), System.Net.ServiceNameStore.Clear(), System.Collections.Hashtable.Clear(), System.Collections.Hashtable.Count, System.Net.HttpListener.RemovePrefixCore(), System.value, and System.Collections.Hashtable.Values.
Referenced by System.Net.HttpListenerPrefixCollection.Clear(), and System.Net.HttpListener.Stop().