Terraria: System.Net.HttpListener.GetChannelBindingFromTls
GetChannelBindingFromTls()
static unsafe ChannelBinding System.Net.HttpListener.GetChannelBindingFromTls (HttpListenerSession session, ulong connectionId) inline static package
Definition at line 1908 of file HttpListener.cs.
    {
        int num = sizeof(global::Interop.HttpApi.HTTP_REQUEST_CHANNEL_BIND_STATUS) + 128;
        byte[] array = null;
        global::Interop.HttpApi.SafeLocalFreeChannelBinding safeLocalFreeChannelBinding = null;
        uint num2 = 0u;
        uint num3;
        do
        {
            array = new byte[num];
            fixed (byte* ptr = &array[0])
            {
                num3 = global::Interop.HttpApi.HttpReceiveClientCertificate(session.RequestQueueHandle, connectionId, 1u, ptr, (uint)num, &num2, null);
                switch (num3)
                {
                case 0u:
                {
                    int tokenOffsetFromBlob = GetTokenOffsetFromBlob((IntPtr)ptr);
                    int tokenSizeFromBlob = GetTokenSizeFromBlob((IntPtr)ptr);
                    safeLocalFreeChannelBinding = global::Interop.HttpApi.SafeLocalFreeChannelBinding.LocalAlloc(tokenSizeFromBlob);
                    if (safeLocalFreeChannelBinding.IsInvalid)
                    {
                        throw new OutOfMemoryException();
                    }
                    Marshal.Copy(array, tokenOffsetFromBlob, safeLocalFreeChannelBinding.DangerousGetHandle(), tokenSizeFromBlob);
                    break;
                }
                case 234u:
                {
                    int tokenSizeFromBlob2 = GetTokenSizeFromBlob((IntPtr)ptr);
                    num = sizeof(global::Interop.HttpApi.HTTP_REQUEST_CHANNEL_BIND_STATUS) + tokenSizeFromBlob2;
                    break;
                }
                case 87u:
                    if (System.Net.NetEventSource.Log.IsEnabled())
                    {
                        System.Net.NetEventSource.Error(session.Listener, System.SR.net_ssp_dont_support_cbt, "GetChannelBindingFromTls");
                    }
                    return null;
                default:
                    throw new HttpListenerException((int)num3);
                }
            }
        }
        while (num3 != 0);
        return safeLocalFreeChannelBinding;
    }
References System.array, System.Runtime.InteropServices.Marshal.Copy(), System.Net.NetEventSource.Error(), System.Net.HttpListener.GetTokenOffsetFromBlob(), System.Net.HttpListener.GetTokenSizeFromBlob(), System.Net.NetEventSource.Log, and System.SR.net_ssp_dont_support_cbt.
Referenced by System.Net.HttpListenerRequest.GetChannelBinding(), and System.Net.HttpListener.GetChannelBinding().