Terraria: System.Net.HttpListener.BeginGetContext
BeginGetContext()
IAsyncResult System.Net.HttpListener.BeginGetContext (AsyncCallback? callback, object? state) inline
Definition at line 957 of file HttpListener.cs.
    {
        ListenerAsyncResult listenerAsyncResult = null;
        try
        {
            CheckDisposed();
            if (_state == State.Stopped)
            {
                throw new InvalidOperationException(System.SR.Format(System.SR.net_listener_mustcall, "Start()"));
            }
            listenerAsyncResult = new ListenerAsyncResult(_currentSession, state, callback);
            uint num = listenerAsyncResult.QueueBeginGetContext();
            if (num != 0 && num != 997)
            {
                throw new HttpListenerException((int)num);
            }
        }
        catch (Exception ex)
        {
            if (System.Net.NetEventSource.Log.IsEnabled())
            {
                System.Net.NetEventSource.Error(this, $"BeginGetContext {ex}", "BeginGetContext");
            }
            throw;
        }
        return listenerAsyncResult;
    }
References System.Net.HttpListener._currentSession, System.Net.HttpListener._state, System.Net.HttpListener.CheckDisposed(), System.Net.NetEventSource.Error(), System.SR.Format(), System.Net.NetEventSource.Log, System.SR.net_listener_mustcall, and System.state.
Referenced by System.Net.HttpListener.GetContextAsync().