Terraria: System.Net.HttpListener.EndGetContext
EndGetContext()
HttpListenerContext System.Net.HttpListener.EndGetContext (IAsyncResult asyncResult) inline
Definition at line 985 of file HttpListener.cs.
    {
        HttpListenerContext httpListenerContext = null;
        try
        {
            CheckDisposed();
            if (asyncResult == null)
            {
                throw new ArgumentNullException("asyncResult");
            }
            if (System.Net.NetEventSource.Log.IsEnabled())
            {
                System.Net.NetEventSource.Info(this, $"asyncResult: {asyncResult}", "EndGetContext");
            }
            if (!(asyncResult is ListenerAsyncResult { AsyncObject: HttpListenerSession asyncObject } listenerAsyncResult) || asyncObject.Listener != this)
            {
                throw new ArgumentException(System.SR.net_io_invalidasyncresult, "asyncResult");
            }
            if (listenerAsyncResult.EndCalled)
            {
                throw new InvalidOperationException(System.SR.Format(System.SR.net_io_invalidendcall, "EndGetContext"));
            }
            listenerAsyncResult.EndCalled = true;
            httpListenerContext = listenerAsyncResult.InternalWaitForCompletion() as HttpListenerContext;
            if (httpListenerContext == null)
            {
                ExceptionDispatchInfo.Throw(listenerAsyncResult.Result as Exception);
            }
        }
        catch (Exception ex)
        {
            if (System.Net.NetEventSource.Log.IsEnabled())
            {
                System.Net.NetEventSource.Error(this, $"EndGetContext {ex}", "EndGetContext");
            }
            throw;
        }
        return httpListenerContext;
    }
References System.asyncResult, System.Net.HttpListener.CheckDisposed(), System.Net.NetEventSource.Error(), System.SR.Format(), System.Net.NetEventSource.Info(), System.Net.NetEventSource.Log, System.SR.net_io_invalidasyncresult, System.SR.net_io_invalidendcall, and System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw().