Terraria: System.Net.HttpListener.SetAuthenticationHeaders
SetAuthenticationHeaders()
void System.Net.HttpListener.SetAuthenticationHeaders (HttpListenerContext context) inline package
Definition at line 1514 of file HttpListener.cs.
    {
        HttpListenerRequest request = context.Request;
        HttpListenerResponse response = context.Response;
        System.Net.NTAuthentication newContext;
        ArrayList arrayList = BuildChallenge(context.AuthenticationSchemes, request._connectionId, out newContext, context.ExtendedProtectionPolicy, request.IsSecureConnection);
        if (arrayList == null)
        {
            return;
        }
        foreach (string item in arrayList)
        {
            response.Headers.Add("WWW-Authenticate", item);
        }
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Net.HttpListenerContext.AuthenticationSchemes, System.Net.HttpListener.BuildChallenge(), System.Net.HttpListenerContext.ExtendedProtectionPolicy, System.item, System.Net.HttpListenerContext.Request, and System.Net.HttpListenerContext.Response.
Referenced by System.Net.HttpListenerContext.SetAuthenticationHeaders().