Terraria: System.Net.HttpListener.GetContext
GetContext()
unsafe HttpListenerContext System.Net.HttpListener.GetContext () inline
Definition at line 855 of file HttpListener.cs.
    {
        SyncRequestContext syncRequestContext = null;
        HttpListenerContext httpListenerContext = null;
        bool stoleBlob = false;
        try
        {
            CheckDisposed();
            if (_state == State.Stopped)
            {
                throw new InvalidOperationException(System.SR.Format(System.SR.net_listener_mustcall, "Start()"));
            }
            if (_uriPrefixes.Count == 0)
            {
                throw new InvalidOperationException(System.SR.Format(System.SR.net_listener_mustcall, "AddPrefix()"));
            }
            uint num = 0u;
            uint num2 = 4096u;
            ulong num3 = 0uL;
            syncRequestContext = new SyncRequestContext((int)num2);
            HttpListenerSession currentSession = _currentSession;
            while (true)
            {
                if (System.Net.NetEventSource.Log.IsEnabled())
                {
                    System.Net.NetEventSource.Info(this, $"Calling Interop.HttpApi.HttpReceiveHttpRequest RequestId: {num3}", "GetContext");
                }
                uint num4 = 0u;
                num = global::Interop.HttpApi.HttpReceiveHttpRequest(currentSession.RequestQueueHandle, num3, 1u, syncRequestContext.RequestBlob, num2, &num4, null);
                if (System.Net.NetEventSource.Log.IsEnabled())
                {
                    System.Net.NetEventSource.Info(this, "Call to Interop.HttpApi.HttpReceiveHttpRequest returned:" + num, "GetContext");
                }
                if (num == 87 && num3 != 0L)
                {
                    num3 = 0uL;
                    continue;
                }
                switch (num)
                {
                case 234u:
                    num2 = num4;
                    num3 = syncRequestContext.RequestBlob->RequestId;
                    syncRequestContext.Reset(checked((int)num2));
                    break;
                default:
                    throw new HttpListenerException((int)num);
                case 0u:
                    if (ValidateRequest(currentSession, syncRequestContext))
                    {
                        httpListenerContext = HandleAuthentication(currentSession, syncRequestContext, out stoleBlob);
                    }
                    if (stoleBlob)
                    {
                        syncRequestContext = null;
                        stoleBlob = false;
                    }
                    if (System.Net.NetEventSource.Log.IsEnabled())
                    {
                        System.Net.NetEventSource.Info(this, ":HandleAuthentication() returned httpContext" + httpListenerContext, "GetContext");
                    }
                    if (httpListenerContext != null)
                    {
                        return httpListenerContext;
                    }
                    if (syncRequestContext == null)
                    {
                        syncRequestContext = new SyncRequestContext(checked((int)num2));
                    }
                    num3 = 0uL;
                    break;
                }
            }
        }
        catch (Exception ex)
        {
            if (System.Net.NetEventSource.Log.IsEnabled())
            {
                System.Net.NetEventSource.Error(this, $"{ex}", "GetContext");
            }
            throw;
        }
        finally
        {
            if (syncRequestContext != null && !stoleBlob)
            {
                syncRequestContext.ReleasePins();
                syncRequestContext.Close();
            }
        }
    }
References System.Net.HttpListener._currentSession, System.Net.HttpListener._state, System.Net.HttpListener._uriPrefixes, System.Net.HttpListener.CheckDisposed(), System.Collections.Hashtable.Count, System.Net.NetEventSource.Error(), System.SR.Format(), System.Net.HttpListener.HandleAuthentication(), System.Net.NetEventSource.Info(), System.L, System.Net.NetEventSource.Log, System.SR.net_listener_mustcall, and System.Net.HttpListener.ValidateRequest().