Terraria: System.Net.HttpListener.HandleAuthentication
HandleAuthentication()
unsafe HttpListenerContext System.Net.HttpListener.HandleAuthentication (HttpListenerSession session, RequestContextBase memoryBlob, out bool stoleBlob) inline package
Definition at line 1025 of file HttpListener.cs.
    {
        if (System.Net.NetEventSource.Log.IsEnabled())
        {
            System.Net.NetEventSource.Info(this, "HandleAuthentication() memoryBlob:0x" + ((IntPtr)memoryBlob.RequestBlob).ToString("x"), "HandleAuthentication");
        }
        string text = null;
        stoleBlob = false;
        string knownHeader = global::Interop.HttpApi.GetKnownHeader(memoryBlob.RequestBlob, 24);
        ulong connectionId = memoryBlob.RequestBlob->ConnectionId;
        ulong requestId = memoryBlob.RequestBlob->RequestId;
        bool isSecureConnection = memoryBlob.RequestBlob->pSslInfo != null;
        if (System.Net.NetEventSource.Log.IsEnabled())
        {
            System.Net.NetEventSource.Info(this, $"HandleAuthentication() authorizationHeader: ({knownHeader})", "HandleAuthentication");
        }
        DisconnectResults.TryGetValue(connectionId, out DisconnectAsyncResult value);
        if (UnsafeConnectionNtlmAuthentication)
        {
            if (knownHeader == null)
            {
                WindowsPrincipal windowsPrincipal = value?.AuthenticatedConnection;
                if (windowsPrincipal != null)
                {
                    if (System.Net.NetEventSource.Log.IsEnabled())
                    {
                        System.Net.NetEventSource.Info(this, $"Principal: {windowsPrincipal} principal.Identity.Name: {windowsPrincipal.Identity.Name} creating request", "HandleAuthentication");
                    }
                    stoleBlob = true;
                    HttpListenerContext httpListenerContext = new HttpListenerContext(session, memoryBlob);
                    httpListenerContext.SetIdentity(windowsPrincipal, null);
                    httpListenerContext.Request.ReleasePins();
                    return httpListenerContext;
                }
            }
            else
            {
                if (System.Net.NetEventSource.Log.IsEnabled())
                {
                    System.Net.NetEventSource.Info(this, "Clearing principal cache", "HandleAuthentication");
                }
                if (value != null)
                {
                    value.AuthenticatedConnection = null;
                }
            }
        }
        stoleBlob = true;
        HttpListenerContext httpContext = null;
        System.Net.NTAuthentication nTAuthentication = null;
        System.Net.NTAuthentication newContext = null;
        System.Net.NTAuthentication nTAuthentication2 = null;
        AuthenticationSchemes authenticationSchemes = AuthenticationSchemes.None;
        AuthenticationSchemes authenticationSchemes2 = AuthenticationSchemes;
        ExtendedProtectionPolicy extendedProtectionPolicy = _extendedProtectionPolicy;
        try
        {
            if (value != null && !value.StartOwningDisconnectHandling())
            {
                value = null;
            }
            if (value != null)
            {
                nTAuthentication = value.Session;
            }
            httpContext = new HttpListenerContext(session, memoryBlob);
            AuthenticationSchemeSelector authenticationDelegate = _authenticationDelegate;
            if (authenticationDelegate != null)
            {
                try
                {
                    httpContext.Request.ReleasePins();
                    authenticationSchemes2 = (httpContext.AuthenticationSchemes = authenticationDelegate(httpContext.Request));
                    if (System.Net.NetEventSource.Log.IsEnabled())
                    {
                        System.Net.NetEventSource.Info(this, $"AuthenticationScheme: {authenticationSchemes2}", "HandleAuthentication");
                    }
                }
                catch (Exception ex) when (!System.Net.ExceptionCheck.IsFatal(ex))
                {
                    if (System.Net.NetEventSource.Log.IsEnabled())
                    {
                        System.Net.NetEventSource.Error(this, System.SR.Format(System.SR.net_log_listener_delegate_exception, ex), "HandleAuthentication");
                        System.Net.NetEventSource.Info(this, $"authenticationScheme: {authenticationSchemes2}", "HandleAuthentication");
                    }
                    SendError(session, requestId, HttpStatusCode.InternalServerError, null);
                    FreeContext(ref httpContext, memoryBlob);
                    return null;
                }
            }
            else
            {
                stoleBlob = false;
            }
            ExtendedProtectionSelector extendedProtectionSelectorDelegate = _extendedProtectionSelectorDelegate;
            if (extendedProtectionSelectorDelegate != null)
            {
                extendedProtectionPolicy = extendedProtectionSelectorDelegate(httpContext.Request);
                if (extendedProtectionPolicy == null)
                {
                    extendedProtectionPolicy = new ExtendedProtectionPolicy(PolicyEnforcement.Never);
                }
                httpContext.ExtendedProtectionPolicy = extendedProtectionPolicy;
            }
            int i = -1;
            if (knownHeader != null && ((uint)authenticationSchemes2 & 0xFFFF7FFFu) != 0)
            {
                for (i = 0; i < knownHeader.Length && knownHeader[i] != ' ' && knownHeader[i] != '\t' && knownHeader[i] != '\r' && knownHeader[i] != '\n'; i++)
                {
                }
                if (i < knownHeader.Length)
                {
                    if ((authenticationSchemes2 & AuthenticationSchemes.Negotiate) != 0 && string.Compare(knownHeader, 0, "Negotiate", 0, i, StringComparison.OrdinalIgnoreCase) == 0)
                    {
                        authenticationSchemes = AuthenticationSchemes.Negotiate;
                    }
                    else if ((authenticationSchemes2 & AuthenticationSchemes.Ntlm) != 0 && string.Compare(knownHeader, 0, "NTLM", 0, i, StringComparison.OrdinalIgnoreCase) == 0)
                    {
                        authenticationSchemes = AuthenticationSchemes.Ntlm;
                    }
                    else if ((authenticationSchemes2 & AuthenticationSchemes.Basic) != 0 && string.Compare(knownHeader, 0, "Basic", 0, i, StringComparison.OrdinalIgnoreCase) == 0)
                    {
                        authenticationSchemes = AuthenticationSchemes.Basic;
                    }
                    else if (System.Net.NetEventSource.Log.IsEnabled())
                    {
                        System.Net.NetEventSource.Error(this, System.SR.Format(System.SR.net_log_listener_unsupported_authentication_scheme, knownHeader, authenticationSchemes2), "HandleAuthentication");
                    }
                }
            }
            HttpStatusCode httpStatusCode = HttpStatusCode.InternalServerError;
            bool flag = false;
            if (authenticationSchemes == AuthenticationSchemes.None)
            {
                if (System.Net.NetEventSource.Log.IsEnabled())
                {
                    System.Net.NetEventSource.Error(this, System.SR.Format(System.SR.net_log_listener_unmatched_authentication_scheme, authenticationSchemes2.ToString(), (knownHeader == null) ? "<null>" : knownHeader), "HandleAuthentication");
                }
                if ((authenticationSchemes2 & AuthenticationSchemes.Anonymous) != 0)
                {
                    if (!stoleBlob)
                    {
                        stoleBlob = true;
                        httpContext.Request.ReleasePins();
                    }
                    return httpContext;
                }
                httpStatusCode = HttpStatusCode.Unauthorized;
                FreeContext(ref httpContext, memoryBlob);
            }
            else
            {
                byte[] array = null;
                byte[] array2 = null;
                string text2 = null;
                for (i++; i < knownHeader.Length && (knownHeader[i] == ' ' || knownHeader[i] == '\t' || knownHeader[i] == '\r' || knownHeader[i] == '\n'); i++)
                {
                }
                string s = ((i < knownHeader.Length) ? knownHeader.Substring(i) : "");
                IPrincipal principal = null;
                if (System.Net.NetEventSource.Log.IsEnabled())
                {
                    System.Net.NetEventSource.Info(this, $"Performing Authentication headerScheme: {authenticationSchemes}", "HandleAuthentication");
                }
                switch (authenticationSchemes)
                {
                case AuthenticationSchemes.Negotiate:
                case AuthenticationSchemes.Ntlm:
                {
                    if (System.Net.NetEventSource.Log.IsEnabled())
                    {
                        System.Net.NetEventSource.Info(this, $"context: {nTAuthentication} for connectionId: {connectionId}", "HandleAuthentication");
                    }
                    string text4 = ((authenticationSchemes == AuthenticationSchemes.Ntlm) ? "NTLM" : "Negotiate");
                    if (nTAuthentication != null && nTAuthentication.Package == text4)
                    {
                        nTAuthentication2 = nTAuthentication;
                    }
                    else
                    {
                        ChannelBinding channelBinding = GetChannelBinding(session, connectionId, isSecureConnection, extendedProtectionPolicy);
                        System.Net.ContextFlagsPal contextFlags = GetContextFlags(extendedProtectionPolicy, isSecureConnection);
                        nTAuthentication2 = new System.Net.NTAuthentication(isServer: true, text4, CredentialCache.DefaultNetworkCredentials, null, contextFlags, channelBinding);
                    }
                    try
                    {
                        array = Convert.FromBase64String(s);
                    }
                    catch (FormatException)
                    {
                        if (System.Net.NetEventSource.Log.IsEnabled())
{
                            System.Net.NetEventSource.Info(this, $"FormatException from FormBase64String", "HandleAuthentication");
                        }
                        httpStatusCode = HttpStatusCode.BadRequest;
                        flag = true;
                    }
                    System.Net.SecurityStatusPal statusCode;
                    if (!flag)
                    {
                        array2 = nTAuthentication2.GetOutgoingBlob(array, throwOnError: false, out statusCode);
                        if (System.Net.NetEventSource.Log.IsEnabled())
{
                            System.Net.NetEventSource.Info(this, $"GetOutgoingBlob returned IsCompleted: {nTAuthentication2.IsCompleted} and statusCodeNew: {statusCode}", "HandleAuthentication");
                        }
                        flag = !nTAuthentication2.IsValidContext;
                        if (flag)
{
                            if (statusCode.ErrorCode == System.Net.SecurityStatusPalErrorCode.InvalidHandle && nTAuthentication == null && array != null && array.Length != 0)
{
                                statusCode = new System.Net.SecurityStatusPal(System.Net.SecurityStatusPalErrorCode.InvalidToken);
                            }
                            httpStatusCode = HttpStatusFromSecurityStatus(statusCode.ErrorCode);
                        }
                    }
                    if (array2 != null)
                    {
                        text2 = ((authenticationSchemes == AuthenticationSchemes.Ntlm) ? "NTLM" : "Negotiate") + " " + Convert.ToBase64String(array2);
                    }
                    if (flag)
                    {
                        break;
                    }
                    if (nTAuthentication2.IsCompleted)
                    {
                        System.Net.Security.SecurityContextTokenHandle token = null;
                        try
{
                            if (!CheckSpn(nTAuthentication2, isSecureConnection, extendedProtectionPolicy))
{
                                httpStatusCode = HttpStatusCode.Unauthorized;
                                break;
                            }
                            httpContext.Request.ServiceName = nTAuthentication2.ClientSpecifiedSpn;
                            System.Net.Security.SafeDeleteContext context = nTAuthentication2.GetContext(out statusCode);
                            if (statusCode.ErrorCode != System.Net.SecurityStatusPalErrorCode.OK)
{
                                if (System.Net.NetEventSource.Log.IsEnabled())
{
                                    System.Net.NetEventSource.Info(this, $"HandleAuthentication GetContextToken failed with statusCodeNew: {statusCode}", "HandleAuthentication");
                                }
                                httpStatusCode = HttpStatusFromSecurityStatus(statusCode.ErrorCode);
                                break;
                            }
                            System.Net.SSPIWrapper.QuerySecurityContextToken(System.Net.GlobalSSPI.SSPIAuth, context, out token);
                            if (System.Net.NetEventSource.Log.IsEnabled())
{
                                System.Net.NetEventSource.Info(this, $"HandleAuthentication creating new WindowsIdentity from user context: {token.DangerousGetHandle():x8}", "HandleAuthentication");
                            }
                            WindowsPrincipal windowsPrincipal2 = new WindowsPrincipal(new WindowsIdentity(token.DangerousGetHandle(), nTAuthentication2.ProtocolName));
                            principal = windowsPrincipal2;
                            if (!UnsafeConnectionNtlmAuthentication || !(nTAuthentication2.ProtocolName == "NTLM"))
{
                                break;
                            }
                            if (System.Net.NetEventSource.Log.IsEnabled())
{
                                System.Net.NetEventSource.Info(this, $"HandleAuthentication inserting principal: {principal} for connectionId: {connectionId}", "HandleAuthentication");
                            }
                            if (value == null)
{
                                RegisterForDisconnectNotification(session, connectionId, ref value);
                            }
                            if (value != null)
{
                                lock (((ICollection)DisconnectResults).SyncRoot)
{
                                    if (UnsafeConnectionNtlmAuthentication)
{
                                        value.AuthenticatedConnection = windowsPrincipal2;
                                    }
                                }
                            }
                            else if (System.Net.NetEventSource.Log.IsEnabled())
{
                                System.Net.NetEventSource.Info(this, $"HandleAuthentication RegisterForDisconnectNotification failed.", "HandleAuthentication");
                            }
                        }
                        finally
{
                            token?.Close();
                        }
                    }
                    else
                    {
                        newContext = nTAuthentication2;
                        text = ((!string.IsNullOrEmpty(text2)) ? text2 : ((authenticationSchemes == AuthenticationSchemes.Ntlm) ? "NTLM" : "Negotiate"));
                    }
                    break;
                }
                case AuthenticationSchemes.Basic:
                    try
                    {
                        array = Convert.FromBase64String(s);
                        s = WebHeaderEncoding.GetString(array, 0, array.Length);
                        i = s.IndexOf(':');
                        if (i != -1)
{
                            string text3 = s.Substring(0, i);
                            string password = s.Substring(i + 1);
                            if (System.Net.NetEventSource.Log.IsEnabled())
{
                                System.Net.NetEventSource.Info(this, $"Basic Identity found, userName: {text3}", "HandleAuthentication");
                            }
                            principal = new GenericPrincipal(new HttpListenerBasicIdentity(text3, password), null);
                        }
                        else
{
                            httpStatusCode = HttpStatusCode.BadRequest;
                        }
                    }
                    catch (FormatException)
                    {
                        if (System.Net.NetEventSource.Log.IsEnabled())
{
                            System.Net.NetEventSource.Info(this, $"FromBase64String threw a FormatException.", "HandleAuthentication");
                        }
                    }
                    break;
                }
                if (principal != null)
                {
                    if (System.Net.NetEventSource.Log.IsEnabled())
                    {
                        System.Net.NetEventSource.Info(this, $"Got principal: {principal}, IdentityName: {principal.Identity.Name} for creating request.", "HandleAuthentication");
                    }
                    httpContext.SetIdentity(principal, text2);
                }
                else
                {
                    if (System.Net.NetEventSource.Log.IsEnabled())
                    {
                        System.Net.NetEventSource.Info(this, "Handshake has failed.", "HandleAuthentication");
                    }
                    FreeContext(ref httpContext, memoryBlob);
                }
            }
            ArrayList challenges = null;
            if (httpContext == null)
            {
                if (text != null)
                {
                    AddChallenge(ref challenges, text);
                }
                else
                {
                    if (newContext != null)
                    {
                        if (newContext == nTAuthentication2)
{
                            nTAuthentication2 = null;
                        }
                        if (newContext != nTAuthentication)
{
                            System.Net.NTAuthentication nTAuthentication3 = newContext;
                            newContext = null;
                            nTAuthentication3.CloseContext();
                        }
                        else
{
                            newContext = null;
                        }
                    }
                    if (httpStatusCode != HttpStatusCode.Unauthorized)
                    {
                        if (System.Net.NetEventSource.Log.IsEnabled())
{
                            System.Net.NetEventSource.Info(this, "ConnectionId:" + connectionId + " because of error:" + httpStatusCode, "HandleAuthentication");
                        }
                        SendError(session, requestId, httpStatusCode, null);
                        return null;
                    }
                    challenges = BuildChallenge(authenticationSchemes2, connectionId, out newContext, extendedProtectionPolicy, isSecureConnection);
                }
            }
            if (value == null && newContext != null)
            {
                RegisterForDisconnectNotification(session, connectionId, ref value);
                if (value == null)
                {
                    if (newContext != null)
                    {
                        if (newContext == nTAuthentication2)
{
                            nTAuthentication2 = null;
                        }
                        if (newContext != nTAuthentication)
{
                            System.Net.NTAuthentication nTAuthentication4 = newContext;
                            newContext = null;
                            nTAuthentication4.CloseContext();
                        }
                        else
{
                            newContext = null;
                        }
                    }
                    if (System.Net.NetEventSource.Log.IsEnabled())
                    {
                        System.Net.NetEventSource.Info(this, "connectionId:" + connectionId + " because of failed HttpWaitForDisconnect", "HandleAuthentication");
                    }
                    SendError(session, requestId, HttpStatusCode.InternalServerError, null);
                    FreeContext(ref httpContext, memoryBlob);
                    return null;
                }
            }
            if (nTAuthentication != newContext)
            {
                if (nTAuthentication == nTAuthentication2)
                {
                    nTAuthentication2 = null;
                }
                System.Net.NTAuthentication nTAuthentication5 = nTAuthentication;
                nTAuthentication = newContext;
                value.Session = newContext;
                nTAuthentication5?.CloseContext();
            }
            if (httpContext == null)
            {
                SendError(session, requestId, (challenges != null && challenges.Count > 0) ? HttpStatusCode.Unauthorized : HttpStatusCode.Forbidden, challenges);
                if (System.Net.NetEventSource.Log.IsEnabled())
                {
                    System.Net.NetEventSource.Info(this, "Scheme:" + authenticationSchemes2, "HandleAuthentication");
                }
                return null;
            }
            if (!stoleBlob)
            {
                stoleBlob = true;
                httpContext.Request.ReleasePins();
            }
            return httpContext;
        }
        catch
        {
            FreeContext(ref httpContext, memoryBlob);
            if (newContext != null)
            {
                if (newContext == nTAuthentication2)
                {
                    nTAuthentication2 = null;
                }
                if (newContext != nTAuthentication)
                {
                    System.Net.NTAuthentication nTAuthentication6 = newContext;
                    newContext = null;
                    nTAuthentication6.CloseContext();
                }
                else
                {
                    newContext = null;
                }
            }
            throw;
        }
        finally
        {
            try
            {
                if (nTAuthentication != null && nTAuthentication != newContext)
                {
                    if (newContext == null && value != null)
                    {
                        value.Session = null;
                    }
                    nTAuthentication.CloseContext();
                }
                if (nTAuthentication2 != null && nTAuthentication != nTAuthentication2 && newContext != nTAuthentication2)
                {
                    nTAuthentication2.CloseContext();
                }
            }
            finally
            {
                value?.FinishOwningDisconnectHandling();
            }
        }
    }
References System.Net.HttpListener._authenticationDelegate, System.Net.HttpListener._extendedProtectionPolicy, System.Net.HttpListener._extendedProtectionSelectorDelegate, System.Net.HttpListener.AddChallenge(), System.array, System.Net.HttpListener.AuthenticationSchemes, System.Net.HttpListener.BuildChallenge(), System.Net.HttpListener.CheckSpn(), System.Runtime.InteropServices.CriticalHandle.Close(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Net.CredentialCache.DefaultNetworkCredentials, System.Net.HttpListener.DisconnectResults, System.Net.NetEventSource.Error(), System.Net.HttpListener.ExtendedProtectionPolicy, System.SR.Format(), System.Net.HttpListener.FreeContext(), System.Convert.FromBase64String(), System.Net.HttpListener.GetChannelBinding(), System.Net.HttpListener.GetContextFlags(), System.Net.WebHeaderEncoding.GetString(), System.Net.HttpListener.HttpStatusFromSecurityStatus(), System.Net.NetEventSource.Info(), System.Net.ExceptionCheck.IsFatal(), System.Net.NetEventSource.Log, System.SR.net_log_listener_delegate_exception, System.SR.net_log_listener_unmatched_authentication_scheme, System.SR.net_log_listener_unsupported_authentication_scheme, System.Net.SSPIWrapper.QuerySecurityContextToken(), System.Net.HttpListener.RegisterForDisconnectNotification(), System.s, System.Net.HttpListener.SendError(), System.Net.GlobalSSPI.SSPIAuth, System.text, System.Convert.ToBase64String(), System.Collections.Generic.Dictionary< TKey, TValue >.TryGetValue(), System.Net.HttpListener.UnsafeConnectionNtlmAuthentication, System.value, and System.Security.Principal.WindowsPrincipal.
Referenced by System.Net.HttpListener.GetContext(), and System.Net.ListenerAsyncResult.IOCompleted().