Terraria: System.Net.HttpListener.CheckDisposed
CheckDisposed()
void System.Net.HttpListener.CheckDisposed () inline package
Definition at line 563 of file HttpListener.cs.
    {
        if (_state == State.Closed)
        {
            throw new ObjectDisposedException(GetType().FullName);
        }
    }
References System.Net.HttpListener._state, and System.FullName.
Referenced by System.Net.HttpListener.AddPrefix(), System.Net.HttpListener.BeginGetContext(), System.Net.HttpListenerPrefixCollection.CopyTo(), System.Net.HttpListenerPrefixCollection.CopyTo(), System.Net.HttpListener.EndGetContext(), System.Net.HttpListener.GetContext(), System.Net.HttpListener.RemoveAll(), System.Net.HttpListener.RemovePrefix(), System.Net.HttpListener.Start(), System.Net.HttpListener.Stop(), and System.Net.HttpListener.ValidateV2Property().