Terraria: System.Net.HttpListener.Start
Start()
void System.Net.HttpListener.Start () inline
Definition at line 652 of file HttpListener.cs.
    {
        lock (_internalLock)
        {
            try
            {
                CheckDisposed();
                if (_state != State.Started)
                {
                    SetupV2Config();
                    CreateRequestQueueHandle();
                    AttachRequestQueueToUrlGroup();
                    try
                    {
                        AddAllPrefixes();
                    }
                    catch (HttpListenerException)
                    {
                        DetachRequestQueueFromUrlGroup();
                        throw;
                    }
                    _state = State.Started;
                }
            }
            catch (Exception ex2)
            {
                _state = State.Closed;
                CloseRequestQueueHandle();
                CleanupV2Config();
                if (System.Net.NetEventSource.Log.IsEnabled())
                {
                    System.Net.NetEventSource.Error(this, $"Start {ex2}", "Start");
                }
                throw;
            }
        }
    }
References System.Net.HttpListener._internalLock, System.Net.HttpListener._state, System.Net.HttpListener.AddAllPrefixes(), System.Net.HttpListener.AttachRequestQueueToUrlGroup(), System.Net.HttpListener.CheckDisposed(), System.Net.HttpListener.CleanupV2Config(), System.Net.HttpListener.CloseRequestQueueHandle(), System.Net.HttpListener.CreateRequestQueueHandle(), System.Net.HttpListener.DetachRequestQueueFromUrlGroup(), System.Net.NetEventSource.Error(), System.Net.NetEventSource.Log, and System.Net.HttpListener.SetupV2Config().