Terraria: System.Net.HttpListener.Dispose
Dispose() [2/2]
void System.Net.HttpListener.Dispose () inline private
Implements System.IDisposable.
Definition at line 793 of file HttpListener.cs.
    {
        lock (_internalLock)
        {
            try
            {
                if (_state != State.Closed)
                {
                    Stop();
                    CleanupV2Config();
                }
            }
            catch (Exception ex)
            {
                if (System.Net.NetEventSource.Log.IsEnabled())
                {
                    System.Net.NetEventSource.Error(this, $"Dispose {ex}", "Dispose");
                }
                throw;
            }
            finally
            {
                _state = State.Closed;
            }
        }
    }
References System.Net.HttpListener._internalLock, System.Net.HttpListener._state, System.Net.HttpListener.CleanupV2Config(), System.Net.NetEventSource.Error(), System.Net.NetEventSource.Log, and System.Net.HttpListener.Stop().