Terraria: System.Net.HttpResponseStreamAsyncResult.HttpResponseStreamAsyncResult
HttpResponseStreamAsyncResult() [2/2]
unsafe System.Net.HttpResponseStreamAsyncResult.HttpResponseStreamAsyncResult (object asyncObject, object userState, AsyncCallback callback, byte[] buffer, int offset, int size, bool chunked, bool sentHeaders, ThreadPoolBoundHandle boundHandle) inline package
Definition at line 81 of file HttpResponseStreamAsyncResult.cs.
        : base(asyncObject, userState, callback)
    {
        _boundHandle = boundHandle;
        _sentHeaders = sentHeaders;
        if (size == 0)
        {
            _dataChunks = null;
            _pOverlapped = boundHandle.AllocateNativeOverlapped(s_IOCallback, this, null);
            return;
        }
        _dataChunks = new global::Interop.HttpApi.HTTP_DATA_CHUNK[(!chunked) ? 1 : 3];
        if (System.Net.NetEventSource.Log.IsEnabled())
        {
            System.Net.NetEventSource.Info(this, "m_pOverlapped:0x" + ((IntPtr)_pOverlapped).ToString("x8"), ".ctor");
        }
        object[] array = new object[1 + _dataChunks.Length];
        array[_dataChunks.Length] = _dataChunks;
        int offset2 = 0;
        byte[] array2 = null;
        if (chunked)
        {
            array2 = GetChunkHeader(size, out offset2);
            _dataChunks[0] = default(global::Interop.HttpApi.HTTP_DATA_CHUNK);
            _dataChunks[0].DataChunkType = global::Interop.HttpApi.HTTP_DATA_CHUNK_TYPE.HttpDataChunkFromMemory;
            _dataChunks[0].BufferLength = (uint)(array2.Length - offset2);
            array[0] = array2;
            _dataChunks[1] = default(global::Interop.HttpApi.HTTP_DATA_CHUNK);
            _dataChunks[1].DataChunkType = global::Interop.HttpApi.HTTP_DATA_CHUNK_TYPE.HttpDataChunkFromMemory;
            _dataChunks[1].BufferLength = (uint)size;
            array[1] = buffer;
            _dataChunks[2] = default(global::Interop.HttpApi.HTTP_DATA_CHUNK);
            _dataChunks[2].DataChunkType = global::Interop.HttpApi.HTTP_DATA_CHUNK_TYPE.HttpDataChunkFromMemory;
            _dataChunks[2].BufferLength = (uint)s_CRLFArray.Length;
            array[2] = s_CRLFArray;
        }
        else
        {
            _dataChunks[0] = default(global::Interop.HttpApi.HTTP_DATA_CHUNK);
            _dataChunks[0].DataChunkType = global::Interop.HttpApi.HTTP_DATA_CHUNK_TYPE.HttpDataChunkFromMemory;
            _dataChunks[0].BufferLength = (uint)size;
            array[0] = buffer;
        }
        _pOverlapped = boundHandle.AllocateNativeOverlapped(s_IOCallback, this, array);
        if (chunked)
        {
            _dataChunks[0].pBuffer = (byte*)(void*)Marshal.UnsafeAddrOfPinnedArrayElement(array2, offset2);
            _dataChunks[1].pBuffer = (byte*)(void*)Marshal.UnsafeAddrOfPinnedArrayElement(buffer, offset);
            _dataChunks[2].pBuffer = (byte*)(void*)Marshal.UnsafeAddrOfPinnedArrayElement(s_CRLFArray, 0);
        }
        else
        {
            _dataChunks[0].pBuffer = (byte*)(void*)Marshal.UnsafeAddrOfPinnedArrayElement(buffer, offset);
        }
    }
References System.Net.HttpResponseStreamAsyncResult._boundHandle, System.Net.HttpResponseStreamAsyncResult._dataChunks, System.Net.HttpResponseStreamAsyncResult._pOverlapped, System.Net.HttpResponseStreamAsyncResult._sentHeaders, System.Threading.ThreadPoolBoundHandle.AllocateNativeOverlapped(), System.array, System.buffer, System.Net.HttpResponseStreamAsyncResult.GetChunkHeader(), System.Net.NetEventSource.Info(), System.Net.NetEventSource.Log, System.offset, System.Net.HttpResponseStreamAsyncResult.s_CRLFArray, System.Net.HttpResponseStreamAsyncResult.s_IOCallback, System.ToString, and System.Runtime.InteropServices.Marshal.UnsafeAddrOfPinnedArrayElement().