Terraria: System.Net.HttpListener.GetChannelBinding
GetChannelBinding()
ChannelBinding System.Net.HttpListener.GetChannelBinding (HttpListenerSession session, ulong connectionId, bool isSecureConnection, ExtendedProtectionPolicy policy) inline private
Definition at line 1530 of file HttpListener.cs.
    {
        if (policy.PolicyEnforcement == PolicyEnforcement.Never)
        {
            if (System.Net.NetEventSource.Log.IsEnabled())
            {
                System.Net.NetEventSource.Info(this, System.SR.net_log_listener_no_cbt_disabled, "GetChannelBinding");
            }
            return null;
        }
        if (!isSecureConnection)
        {
            if (System.Net.NetEventSource.Log.IsEnabled())
            {
                System.Net.NetEventSource.Info(this, System.SR.net_log_listener_no_cbt_http, "GetChannelBinding");
            }
            return null;
        }
        if (policy.ProtectionScenario == ProtectionScenario.TrustedProxy)
        {
            if (System.Net.NetEventSource.Log.IsEnabled())
            {
                System.Net.NetEventSource.Info(this, System.SR.net_log_listener_no_cbt_trustedproxy, "GetChannelBinding");
            }
            return null;
        }
        ChannelBinding channelBindingFromTls = GetChannelBindingFromTls(session, connectionId);
        if (System.Net.NetEventSource.Log.IsEnabled() && channelBindingFromTls != null)
        {
            System.Net.NetEventSource.Info(this, "GetChannelBindingFromTls returned null even though OS supposedly supports Extended Protection", "GetChannelBinding");
        }
        if (System.Net.NetEventSource.Log.IsEnabled())
        {
            System.Net.NetEventSource.Info(this, System.SR.net_log_listener_cbt, "GetChannelBinding");
        }
        return channelBindingFromTls;
    }
References System.Net.HttpListener.GetChannelBindingFromTls(), System.Net.NetEventSource.Info(), System.Net.NetEventSource.Log, System.SR.net_log_listener_cbt, System.SR.net_log_listener_no_cbt_disabled, System.SR.net_log_listener_no_cbt_http, and System.SR.net_log_listener_no_cbt_trustedproxy.
Referenced by System.Net.HttpListener.HandleAuthentication().