Terraria: System.Net.HttpListener.AddPrefix
AddPrefix()
void System.Net.HttpListener.AddPrefix (string uriPrefix) inline package
Definition at line 391 of file HttpListener.cs.
    {
        string text = null;
        try
        {
            if (uriPrefix == null)
            {
                throw new ArgumentNullException("uriPrefix");
            }
            CheckDisposed();
            int num;
            if (string.Compare(uriPrefix, 0, "http://", 0, 7, StringComparison.OrdinalIgnoreCase) == 0)
            {
                num = 7;
            }
            else
            {
                if (string.Compare(uriPrefix, 0, "https://", 0, 8, StringComparison.OrdinalIgnoreCase) != 0)
                {
                    throw new ArgumentException(System.SR.net_listener_scheme, "uriPrefix");
                }
                num = 8;
            }
            bool flag = false;
            int i;
            for (i = num; i < uriPrefix.Length && uriPrefix[i] != '/' && (uriPrefix[i] != ':' || flag); i++)
            {
                if (uriPrefix[i] == '[')
                {
                    if (flag)
                    {
                        i = num;
                        break;
                    }
                    flag = true;
                }
                if (flag && uriPrefix[i] == ']')
                {
                    flag = false;
                }
            }
            if (num == i)
            {
                throw new ArgumentException(System.SR.net_listener_host, "uriPrefix");
            }
            if (uriPrefix[uriPrefix.Length - 1] != '/')
            {
                throw new ArgumentException(System.SR.net_listener_slash, "uriPrefix");
            }
            StringBuilder stringBuilder = new StringBuilder();
            if (uriPrefix[i] == ':')
            {
                stringBuilder.Append(uriPrefix);
            }
            else
            {
                stringBuilder.Append(uriPrefix, 0, i);
                stringBuilder.Append((num == 7) ? ":80" : ":443");
                stringBuilder.Append(uriPrefix, i, uriPrefix.Length - i);
            }
            for (num = 0; stringBuilder[num] != ':'; num++)
            {
                stringBuilder[num] = (char)System.Net.CaseInsensitiveAscii.AsciiToLower[(byte)stringBuilder[num]];
            }
            text = stringBuilder.ToString();
            if (System.Net.NetEventSource.Log.IsEnabled())
            {
                System.Net.NetEventSource.Info(this, $"mapped uriPrefix: {uriPrefix} to registeredPrefix: {text}", "AddPrefix");
            }
            if (_state == State.Started)
            {
                AddPrefixCore(text);
            }
            _uriPrefixes[uriPrefix] = text;
            _defaultServiceNames.Add(uriPrefix);
        }
        catch (Exception message)
        {
            if (System.Net.NetEventSource.Log.IsEnabled())
            {
                System.Net.NetEventSource.Error(this, message, "AddPrefix");
            }
            throw;
        }
    }
References System.Net.HttpListener._defaultServiceNames, System.Net.HttpListener._state, System.Net.HttpListener._uriPrefixes, System.Net.ServiceNameStore.Add(), System.Net.HttpListener.AddPrefixCore(), System.Net.CaseInsensitiveAscii.AsciiToLower, System.Net.HttpListener.CheckDisposed(), System.Net.NetEventSource.Error(), System.Net.NetEventSource.Info(), System.Net.NetEventSource.Log, System.SR.net_listener_host, System.SR.net_listener_scheme, System.SR.net_listener_slash, and System.text.
Referenced by System.Net.HttpListenerPrefixCollection.Add().