Terraria: System.Net.HttpListener.AddPrefixCore
AddPrefixCore()
void System.Net.HttpListener.AddPrefixCore (string registeredPrefix) inline private
Definition at line 837 of file HttpListener.cs.
    {
        if (System.Net.NetEventSource.Log.IsEnabled())
        {
            System.Net.NetEventSource.Info(this, "Calling Interop.HttpApi.HttpAddUrl[ToUrlGroup]", "AddPrefixCore");
        }
        uint num = global::Interop.HttpApi.HttpAddUrlToUrlGroup(_urlGroupId, registeredPrefix, 0uL, 0u);
        switch (num)
        {
        case 183u:
            throw new HttpListenerException((int)num, System.SR.Format(System.SR.net_listener_already, registeredPrefix));
        default:
            throw new HttpListenerException((int)num);
        case 0u:
            break;
        }
    }
References System.Net.HttpListener._urlGroupId, System.SR.Format(), System.Net.NetEventSource.Info(), System.Net.NetEventSource.Log, and System.SR.net_listener_already.
Referenced by System.Net.HttpListener.AddAllPrefixes(), and System.Net.HttpListener.AddPrefix().