Terraria: System.Net.HttpListener.SendError
SendError()
static unsafe void System.Net.HttpListener.SendError (HttpListenerSession session, ulong requestId, HttpStatusCode httpStatusCode, ArrayList challenges) inline static private
Definition at line 1802 of file HttpListener.cs.
    {
        if (System.Net.NetEventSource.Log.IsEnabled())
        {
            System.Net.NetEventSource.Info(session.Listener, $"RequestId: {requestId}", "SendError");
        }
        global::Interop.HttpApi.HTTP_RESPONSE hTTP_RESPONSE = default(global::Interop.HttpApi.HTTP_RESPONSE);
        hTTP_RESPONSE.Version = default(global::Interop.HttpApi.HTTP_VERSION);
        hTTP_RESPONSE.Version.MajorVersion = 1;
        hTTP_RESPONSE.Version.MinorVersion = 1;
        hTTP_RESPONSE.StatusCode = (ushort)httpStatusCode;
        string s = HttpStatusDescription.Get(httpStatusCode);
        uint num = 0u;
        byte[] bytes = Encoding.Default.GetBytes(s);
        uint num2;
        fixed (byte* pReason = bytes)
        {
            hTTP_RESPONSE.pReason = (sbyte*)pReason;
            hTTP_RESPONSE.ReasonLength = (ushort)bytes.Length;
            byte[] bytes2 = Encoding.Default.GetBytes("0");
            fixed (byte* pRawValue = &bytes2[0])
            {
                (&hTTP_RESPONSE.Headers.KnownHeaders)[11].pRawValue = (sbyte*)pRawValue;
                (&hTTP_RESPONSE.Headers.KnownHeaders)[11].RawValueLength = (ushort)bytes2.Length;
                hTTP_RESPONSE.Headers.UnknownHeaderCount = checked((ushort)(challenges?.Count ?? 0));
                GCHandle[] array = null;
                global::Interop.HttpApi.HTTP_UNKNOWN_HEADER[] array2 = null;
                GCHandle gCHandle = default(GCHandle);
                GCHandle gCHandle2 = default(GCHandle);
                if (hTTP_RESPONSE.Headers.UnknownHeaderCount > 0)
                {
                    array = new GCHandle[hTTP_RESPONSE.Headers.UnknownHeaderCount];
                    array2 = new global::Interop.HttpApi.HTTP_UNKNOWN_HEADER[hTTP_RESPONSE.Headers.UnknownHeaderCount];
                }
                try
                {
                    if (hTTP_RESPONSE.Headers.UnknownHeaderCount > 0)
                    {
                        gCHandle = GCHandle.Alloc(array2, GCHandleType.Pinned);
                        hTTP_RESPONSE.Headers.pUnknownHeaders = (global::Interop.HttpApi.HTTP_UNKNOWN_HEADER*)(void*)Marshal.UnsafeAddrOfPinnedArrayElement(array2, 0);
                        gCHandle2 = GCHandle.Alloc(s_wwwAuthenticateBytes, GCHandleType.Pinned);
                        sbyte* pName = (sbyte*)(void*)Marshal.UnsafeAddrOfPinnedArrayElement(s_wwwAuthenticateBytes, 0);
                        for (int i = 0; i < array.Length; i++)
{
                            byte[] bytes3 = Encoding.Default.GetBytes((string)challenges[i]);
                            array[i] = GCHandle.Alloc(bytes3, GCHandleType.Pinned);
                            array2[i].pName = pName;
                            array2[i].NameLength = (ushort)s_wwwAuthenticateBytes.Length;
                            array2[i].pRawValue = (sbyte*)(void*)Marshal.UnsafeAddrOfPinnedArrayElement(bytes3, 0);
                            array2[i].RawValueLength = checked((ushort)bytes3.Length);
                        }
                    }
                    if (System.Net.NetEventSource.Log.IsEnabled())
                    {
                        System.Net.NetEventSource.Info(session.Listener, "Calling Interop.HttpApi.HttpSendHtthttpResponse", "SendError");
                    }
                    num2 = global::Interop.HttpApi.HttpSendHttpResponse(session.RequestQueueHandle, requestId, 0u, &hTTP_RESPONSE, null, &num, Microsoft.Win32.SafeHandles.SafeLocalAllocHandle.Zero, 0u, null, null);
                }
                finally
                {
                    if (gCHandle.IsAllocated)
                    {
                        gCHandle.Free();
                    }
                    if (gCHandle2.IsAllocated)
                    {
                        gCHandle2.Free();
                    }
                    if (array != null)
                    {
                        for (int j = 0; j < array.Length; j++)
{
                            if (array[j].IsAllocated)
{
                                array[j].Free();
                            }
                        }
                    }
                }
            }
        }
        if (System.Net.NetEventSource.Log.IsEnabled())
        {
            System.Net.NetEventSource.Info(session.Listener, "Call to Interop.HttpApi.HttpSendHttpResponse returned:" + num2, "SendError");
        }
        if (num2 != 0)
        {
            if (System.Net.NetEventSource.Log.IsEnabled())
            {
                System.Net.NetEventSource.Info(session.Listener, "SendUnauthorized returned:" + num2, "SendError");
            }
            HttpListenerContext.CancelRequest(session.RequestQueueHandle, requestId);
        }
    }
References System.Runtime.InteropServices.GCHandle.Alloc(), System.array, System.bytes, System.Net.HttpListenerContext.CancelRequest(), System.Text.Encoding.Default, System.Net.HttpStatusDescription.Get(), System.Net.NetEventSource.Info(), System.Net.NetEventSource.Log, System.s, System.Net.HttpListener.s_wwwAuthenticateBytes, System.Runtime.InteropServices.Marshal.UnsafeAddrOfPinnedArrayElement(), and Microsoft.Win32.SafeHandles.SafeLocalAllocHandle.Zero.
Referenced by System.Net.HttpListener.HandleAuthentication(), and System.Net.HttpListener.ValidateRequest().