Terraria: System.Net.HttpListener.CheckSpn
CheckSpn()
bool System.Net.HttpListener.CheckSpn (System::Net::NTAuthentication context, bool isSecureConnection, ExtendedProtectionPolicy policy) inline private
Definition at line 1568 of file HttpListener.cs.
    {
        if (context.IsKerberos)
        {
            if (System.Net.NetEventSource.Log.IsEnabled())
            {
                System.Net.NetEventSource.Info(this, System.SR.net_log_listener_no_spn_kerberos, "CheckSpn");
            }
            return true;
        }
        if (policy.PolicyEnforcement == PolicyEnforcement.Never)
        {
            if (System.Net.NetEventSource.Log.IsEnabled())
            {
                System.Net.NetEventSource.Info(this, System.SR.net_log_listener_no_spn_disabled, "CheckSpn");
            }
            return true;
        }
        if (ScenarioChecksChannelBinding(isSecureConnection, policy.ProtectionScenario))
        {
            if (System.Net.NetEventSource.Log.IsEnabled())
            {
                System.Net.NetEventSource.Info(this, System.SR.net_log_listener_no_spn_cbt, "CheckSpn");
            }
            return true;
        }
        string clientSpecifiedSpn = context.ClientSpecifiedSpn;
        if (string.IsNullOrEmpty(clientSpecifiedSpn))
        {
            if (policy.PolicyEnforcement == PolicyEnforcement.WhenSupported)
            {
                if (System.Net.NetEventSource.Log.IsEnabled())
                {
                    System.Net.NetEventSource.Info(this, System.SR.net_log_listener_no_spn_whensupported, "CheckSpn");
                }
                return true;
            }
            if (System.Net.NetEventSource.Log.IsEnabled())
            {
                System.Net.NetEventSource.Info(this, System.SR.net_log_listener_spn_failed_always, "CheckSpn");
            }
            return false;
        }
        if (string.Equals(clientSpecifiedSpn, "http/localhost", StringComparison.OrdinalIgnoreCase))
        {
            if (System.Net.NetEventSource.Log.IsEnabled())
            {
                System.Net.NetEventSource.Info(this, System.SR.net_log_listener_no_spn_loopback, "CheckSpn");
            }
            return true;
        }
        if (System.Net.NetEventSource.Log.IsEnabled())
        {
            System.Net.NetEventSource.Info(this, System.SR.net_log_listener_spn, clientSpecifiedSpn);
        }
        ServiceNameCollection serviceNames = GetServiceNames(policy);
        bool flag = serviceNames.Contains(clientSpecifiedSpn);
        if (System.Net.NetEventSource.Log.IsEnabled())
        {
            if (flag)
            {
                System.Net.NetEventSource.Info(this, System.SR.net_log_listener_spn_passed, "CheckSpn");
            }
            else
            {
                System.Net.NetEventSource.Info(this, System.SR.net_log_listener_spn_failed, "CheckSpn");
                if (serviceNames.Count == 0)
                {
                    if (System.Net.NetEventSource.Log.IsEnabled())
                    {
                        System.Net.NetEventSource.Info(this, System.SR.net_log_listener_spn_failed_empty, "CheckSpn");
                    }
                }
                else
                {
                    System.Net.NetEventSource.Info(this, System.SR.net_log_listener_spn_failed_dump, "CheckSpn");
                    foreach (string item in serviceNames)
                    {
                        System.Net.NetEventSource.Info(this, "\t" + item, "CheckSpn");
                    }
                }
            }
        }
        return flag;
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Contains(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Net.Equals, System.Net.HttpListener.GetServiceNames(), System.Net.NetEventSource.Info(), System.item, System.Net.NetEventSource.Log, System.SR.net_log_listener_no_spn_cbt, System.SR.net_log_listener_no_spn_disabled, System.SR.net_log_listener_no_spn_kerberos, System.SR.net_log_listener_no_spn_loopback, System.SR.net_log_listener_no_spn_whensupported, System.SR.net_log_listener_spn, System.SR.net_log_listener_spn_failed, System.SR.net_log_listener_spn_failed_always, System.SR.net_log_listener_spn_failed_dump, System.SR.net_log_listener_spn_failed_empty, System.SR.net_log_listener_spn_passed, and System.Net.HttpListener.ScenarioChecksChannelBinding().
Referenced by System.Net.HttpListener.HandleAuthentication().