Terraria: System.Net.IPEndPoint.Create
Create()
override EndPoint System.Net.IPEndPoint.Create (SocketAddress socketAddress) inline virtual
Reimplemented from System.Net.EndPoint.
Definition at line 133 of file IPEndPoint.cs.
    {
        if (socketAddress == null)
        {
            throw new ArgumentNullException("socketAddress");
        }
        if (socketAddress.Family != AddressFamily)
        {
            throw new ArgumentException(System.SR.Format(System.SR.net_InvalidAddressFamily, socketAddress.Family.ToString(), GetType().FullName, AddressFamily.ToString()), "socketAddress");
        }
        int num = ((AddressFamily == AddressFamily.InterNetworkV6) ? SocketAddress.IPv6AddressSize : SocketAddress.IPv4AddressSize);
        if (socketAddress.Size < num)
        {
            throw new ArgumentException(System.SR.Format(System.SR.net_InvalidSocketAddressSize, socketAddress.GetType().FullName, GetType().FullName), "socketAddress");
        }
        return socketAddress.GetIPEndPoint();
    }
References System.Net.SocketAddress.Family, System.SR.Format(), System.FullName, System.Net.SocketAddress.GetIPEndPoint(), System.Net.SocketAddress.IPv4AddressSize, System.Net.SocketAddress.IPv6AddressSize, System.SR.net_InvalidAddressFamily, System.SR.net_InvalidSocketAddressSize, and System.Net.SocketAddress.Size.
Referenced by Interop.HttpApi.GetRemoteEndPoint().