Terraria: LanguageManager.LoadFilesForCulture
LoadFilesForCulture()
void LanguageManager.LoadFilesForCulture (GameCulture culture) inline private
     {
         string[] languageFilesForCulture = GetLanguageFilesForCulture(culture);
         foreach (string text in languageFilesForCulture)
         {
             try
             {
                 string text2 = Utils.ReadEmbeddedResource(text);
                 if (text2 == null || text2.Length < 2)
                 {
                     throw new FormatException();
                 }
                 LoadLanguageFromFileTextJson(text2, canCreateCategories: true);
             }
             catch (Exception)
             {
                 if (Debugger.IsAttached)
                 {
                     Debugger.Break();
                 }
                 Console.WriteLine("Failed to load language file: " + text);
                 break;
             }
         }
     }
References GetLanguageFilesForCulture(), LoadLanguageFromFileTextJson(), and Utils.ReadEmbeddedResource().
Referenced by LoadLanguage().