Terraria: LanguageManager.LoadLanguage
LoadLanguage()
void LanguageManager.LoadLanguage (GameCulture culture, bool processCopyCommands = true) inline private
     {
         LoadFilesForCulture(culture);
         if (this.OnLanguageChanging != null)
         {
             this.OnLanguageChanging(this);
         }
         if (processCopyCommands)
         {
             ProcessCopyCommandsInTexts();
         }
         ChatInitializer.PrepareAliases();
     }
References LoadFilesForCulture(), OnLanguageChanging, ChatInitializer.PrepareAliases(), and ProcessCopyCommandsInTexts().
Referenced by SetLanguage(), and UseSources().