Terraria: LanguageManager.UseSources
UseSources()
void LanguageManager.UseSources (List< IContentSource > sourcesFromLowestToHighest) inline
     {
         string name = ActiveCulture.Name;
         string text = ("Localization" + Path.DirectorySeparatorChar + name).ToLower();
         LoadLanguage(ActiveCulture, processCopyCommands: false);
         foreach (IContentSource item in sourcesFromLowestToHighest)
         {
             foreach (string item2 in item.GetAllAssetsStartingWith(text))
             {
                 string extension = item.GetExtension(item2);
                 if (!(extension == ".json") && !(extension == ".csv"))
                 {
                     continue;
                 }
                 using Stream stream = item.OpenStream(item2);
                 using StreamReader streamReader = new StreamReader(stream);
                 string fileText = streamReader.ReadToEnd();
                 if (extension == ".json")
                 {
                     LoadLanguageFromFileTextJson(fileText, canCreateCategories: false);
                 }
                 if (extension == ".csv")
                 {
                     LoadLanguageFromFileTextCsv(fileText);
                 }
             }
         }
         ProcessCopyCommandsInTexts();
         ChatInitializer.PrepareAliases();
     }
References ActiveCulture, IContentSource.GetAllAssetsStartingWith(), IContentSource.GetExtension(), LoadLanguage(), LoadLanguageFromFileTextCsv(), LoadLanguageFromFileTextJson(), GameCulture.Name, IContentSource.OpenStream(), ChatInitializer.PrepareAliases(), and ProcessCopyCommandsInTexts().
Referenced by AssetSourceController.UseResourcePacks().