Terraria: ItemShopSellbackHelper.ItemMemo.Matches
Matches()
bool ItemShopSellbackHelper.ItemMemo.Matches (Item item) inline
         {
             if (item.netID == itemNetID)
             {
                 return item.prefix == itemPrefix;
             }
             return false;
         }
References ItemShopSellbackHelper.ItemMemo.itemNetID, ItemShopSellbackHelper.ItemMemo.itemPrefix, Item.netID, and Item.prefix.
Referenced by ItemShopSellbackHelper.Add(), ItemShopSellbackHelper.GetAmount(), and ItemShopSellbackHelper.Remove().