Terraria: System.Xml.Xsl.Runtime.NumberFormatter.FormatItem
FormatItem()
void System.Xml.Xsl.Runtime.NumberFormatter.FormatItem (StringBuilder sb, XPathItem item, char startChar, int length) inline private
Definition at line 115 of file NumberFormatter.cs.
    {
        double num = ((!(item.ValueType == typeof(int))) ? XsltFunctions.Round(item.ValueAsDouble) : ((double)item.ValueAsInt));
        char zero = '0';
        switch (startChar)
        {
        case 'A':
        case 'a':
            if (num <= 2147483647.0)
            {
                NumberFormatterBase.ConvertToAlphabetic(sb, num, startChar, 26);
                return;
            }
            break;
        case 'I':
        case 'i':
            if (num <= 32767.0)
            {
                NumberFormatterBase.ConvertToRoman(sb, num, startChar == 'I');
                return;
            }
            break;
        default:
            zero = (char)(startChar - 1);
            break;
        case '1':
            break;
        }
        sb.Append(ConvertToDecimal(num, length, zero, _groupingSeparator, _groupingSize));
    }
References System.Xml.Xsl.Runtime.NumberFormatter._groupingSeparator, System.Xml.Xsl.Runtime.NumberFormatter._groupingSize, System.Text.StringBuilder.Append(), System.Xml.Xsl.Runtime.NumberFormatterBase.ConvertToAlphabetic(), System.Xml.Xsl.Runtime.NumberFormatter.ConvertToDecimal(), System.Xml.Xsl.Runtime.NumberFormatterBase.ConvertToRoman(), System.Xml.Dictionary, System.item, System.length, and System.Xml.Xsl.Runtime.XsltFunctions.Round().
Referenced by System.Xml.Xsl.Runtime.NumberFormatter.FormatSequence().