Terraria: System.Net.WebSockets.ClientWebSocket.ConnectAsync
ConnectAsync()
Task System.Net.WebSockets.ClientWebSocket.ConnectAsync (Uri uri, CancellationToken cancellationToken) inline
Definition at line 67 of file ClientWebSocket.cs.
    {
        if (uri == null)
        {
            throw new ArgumentNullException("uri");
        }
        if (!uri.IsAbsoluteUri)
        {
            throw new ArgumentException(System.SR.net_uri_NotAbsolute, "uri");
        }
        if (uri.Scheme != "ws" && uri.Scheme != "wss")
        {
            throw new ArgumentException(System.SR.net_WebSockets_Scheme, "uri");
        }
        switch ((InternalState)Interlocked.CompareExchange(ref _state, 1, 0))
        {
        case InternalState.Disposed:
            throw new ObjectDisposedException(GetType().FullName);
        default:
            throw new InvalidOperationException(System.SR.net_WebSockets_AlreadyStarted);
        case InternalState.Created:
            Options.SetToReadOnly();
            return ConnectAsyncCore(uri, cancellationToken);
        }
    }
References System.Net.WebSockets.ClientWebSocket._state, System.cancellationToken, System.Threading.Interlocked.CompareExchange(), System.Net.WebSockets.ClientWebSocket.ConnectAsyncCore(), System.FullName, System.Uri.IsAbsoluteUri, System.SR.net_uri_NotAbsolute, System.SR.net_WebSockets_AlreadyStarted, System.SR.net_WebSockets_Scheme, System.Net.WebSockets.ClientWebSocket.Options, System.Uri.Scheme, and System.Net.WebSockets.ClientWebSocketOptions.SetToReadOnly().