Terraria: System.Xml.Xsl.Runtime.NumberFormatter.NumberFormatter
NumberFormatter()
System.Xml.Xsl.Runtime.NumberFormatter.NumberFormatter (string formatString, int lang, string letterValue, string groupingSeparator, int groupingSize) inline
Definition at line 25 of file NumberFormatter.cs.
    {
        _formatString = formatString;
        _lang = lang;
        _letterValue = letterValue;
        _groupingSeparator = groupingSeparator;
        _groupingSize = ((groupingSeparator.Length > 0) ? groupingSize : 0);
        if (formatString == "1" || formatString.Length == 0)
        {
            return;
        }
        _tokens = new List<TokenInfo>();
        int num = 0;
        bool flag = CharUtil.IsAlphaNumeric(formatString[num]);
        if (flag)
        {
            _tokens.Add(null);
        }
        for (int i = 0; i <= formatString.Length; i++)
        {
            if (i == formatString.Length || flag != CharUtil.IsAlphaNumeric(formatString[i]))
            {
                if (flag)
                {
                    _tokens.Add(TokenInfo.CreateFormat(formatString, num, i - num));
                }
                else
                {
                    _tokens.Add(TokenInfo.CreateSeparator(formatString, num, i - num));
                }
                num = i;
                flag = !flag;
            }
        }
    }
References System.Xml.Xsl.Runtime.NumberFormatter._formatString, System.Xml.Xsl.Runtime.NumberFormatter._groupingSeparator, System.Xml.Xsl.Runtime.NumberFormatter._groupingSize, System.Xml.Xsl.Runtime.NumberFormatter._lang, System.Xml.Xsl.Runtime.NumberFormatter._letterValue, System.Xml.Xsl.Runtime.NumberFormatter._tokens, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Xml.Xsl.Runtime.TokenInfo.CreateFormat(), System.Xml.Xsl.Runtime.TokenInfo.CreateSeparator(), System.Xml.Dictionary, and System.Xml.Xsl.Runtime.CharUtil.IsAlphaNumeric().