Terraria: System.Xml.Xsl.Runtime.NumberFormatter.ConvertToDecimal
ConvertToDecimal()
static unsafe string System.Xml.Xsl.Runtime.NumberFormatter.ConvertToDecimal (double val, int minLen, char zero, string groupSeparator, int groupSize) inline static private
Definition at line 146 of file NumberFormatter.cs.
    {
        string text = XPathConvert.DoubleToString(val);
        int num = zero - 48;
        int length = text.Length;
        int num2 = Math.Max(length, minLen);
        char* ptr;
        char c;
        checked
        {
            if (groupSize != 0)
            {
                num2 += unchecked(checked(num2 - 1) / groupSize);
            }
            if (num2 == length && num == 0)
            {
                return text;
            }
            if (groupSize == 0 && num == 0)
            {
                return text.PadLeft(num2, zero);
            }
            ptr = stackalloc char[num2];
            c = ((groupSeparator.Length > 0) ? groupSeparator[0] : ' ');
        }
        fixed (char* ptr2 = text)
        {
            char* ptr3 = ptr2 + length - 1;
            char* ptr4 = ptr + num2 - 1;
            int num3 = groupSize;
            while (true)
            {
                *(ptr4--) = ((ptr3 >= ptr2) ? ((char)(*(ptr3--) + num)) : zero);
                if (ptr4 < ptr)
                {
                    break;
                }
                if (--num3 == 0)
                {
                    *(ptr4--) = c;
                    num3 = groupSize;
                }
            }
        }
        return new string(ptr, 0, num2);
    }
References System.Xml.Dictionary, System.Xml.Xsl.XPathConvert.DoubleToString(), System.length, System.Math.Max(), and System.text.
Referenced by System.Xml.Xsl.Runtime.NumberFormatter.FormatItem().