Terraria: System.Net.WebSockets.ClientWebSocket.ConnectAsyncCore
ConnectAsyncCore()
async Task System.Net.WebSockets.ClientWebSocket.ConnectAsyncCore (Uri uri, CancellationToken cancellationToken) inline private
Definition at line 93 of file ClientWebSocket.cs.
    {
        _innerWebSocket = new WebSocketHandle();
        try
        {
            await _innerWebSocket.ConnectAsync(uri, cancellationToken, Options).ConfigureAwait(continueOnCapturedContext: false);
        }
        catch
        {
            Dispose();
            throw;
        }
        if (Interlocked.CompareExchange(ref _state, 2, 1) != 1)
        {
            throw new ObjectDisposedException(GetType().FullName);
        }
    }
References System.Net.WebSockets.ClientWebSocket._innerWebSocket, System.Net.WebSockets.ClientWebSocket._state, System.cancellationToken, System.Threading.Interlocked.CompareExchange(), System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.Net.WebSockets.WebSocketHandle.ConnectAsync(), System.Net.WebSockets.ClientWebSocket.Dispose(), System.FullName, and System.Net.WebSockets.ClientWebSocket.Options.
Referenced by System.Net.WebSockets.ClientWebSocket.ConnectAsync().