Terraria: System.Threading.Tasks.Dataflow.WriteOnceBlock.CompleteBlockAsync
CompleteBlockAsync()
void System.Threading.Tasks.Dataflow.WriteOnceBlock< T >.CompleteBlockAsync (IList< Exception > exceptions) inline private
Definition at line 121 of file WriteOnceBlock.cs.
    {
        if (exceptions == null)
        {
            Task task = new Task(delegate(object state)
            {
                ((WriteOnceBlock<T>)state).OfferToTargetsAndCompleteBlock();
            }, this, Common.GetCreationOptionsForTask());
            DataflowEtwProvider log = DataflowEtwProvider.Log;
            if (log.IsEnabled())
            {
                log.TaskLaunchedForMessageHandling(this, task, DataflowEtwProvider.TaskLaunchedReason.OfferingOutputMessages, _header.IsValid ? 1 : 0);
            }
            Exception ex = Common.StartTaskSafe(task, _dataflowBlockOptions.TaskScheduler);
            if (ex != null)
            {
                CompleteCore(ex, storeExceptionEvenIfAlreadyCompleting: true);
            }
        }
        else
        {
            Task.Factory.StartNew(delegate(object state)
            {
                Tuple<WriteOnceBlock<T>, IList<Exception>> tuple = (Tuple<WriteOnceBlock<T>, IList<Exception>>)state;
                tuple.Item1.CompleteBlock(tuple.Item2);
            }, Tuple.Create(this, exceptions), CancellationToken.None, Common.GetCreationOptionsForTask(), TaskScheduler.Default);
        }
    }
References System.Threading.Tasks.Dataflow.WriteOnceBlock< T >._dataflowBlockOptions, System.Threading.Tasks.Dataflow.WriteOnceBlock< T >._header, System.Threading.Tasks.Dataflow.WriteOnceBlock< T >.CompleteCore(), System.Threading.Tasks.TaskScheduler.Default, System.exceptions, System.Threading.Tasks.Task< TResult >.Factory, System.Threading.Tasks.Dataflow.Internal.Common.GetCreationOptionsForTask(), System.Threading.Tasks.Dataflow.DataflowMessageHeader.IsValid, System.Threading.Tasks.Dataflow.Internal.DataflowEtwProvider.Log, System.Threading.CancellationToken.None, System.Threading.Tasks.Dataflow.Internal.Common.StartTaskSafe(), System.state, System.task, and System.Threading.Tasks.Dataflow.DataflowBlockOptions.TaskScheduler.
Referenced by System.Threading.Tasks.Dataflow.WriteOnceBlock< T >.CompleteCore(), and System.Threading.Tasks.Dataflow.WriteOnceBlock< T >.OfferMessage().