Terraria: System.Threading.Tasks.Dataflow.WriteOnceBlock.CompleteCore
CompleteCore()
void System.Threading.Tasks.Dataflow.WriteOnceBlock< T >.CompleteCore (Exception exception, bool storeExceptionEvenIfAlreadyCompleting) inline private
Definition at line 193 of file WriteOnceBlock.cs.
    {
        bool flag = false;
        lock (ValueLock)
        {
            if (_decliningPermanently && !storeExceptionEvenIfAlreadyCompleting)
            {
                return;
            }
            _decliningPermanently = true;
            if (!_completionReserved || storeExceptionEvenIfAlreadyCompleting)
            {
                flag = (_completionReserved = true);
            }
        }
        if (flag)
        {
            List<Exception> list = null;
            if (exception != null)
            {
                list = new List<Exception>();
                list.Add(exception);
            }
            CompleteBlockAsync(list);
        }
    }
References System.Threading.Tasks.Dataflow.WriteOnceBlock< T >._completionReserved, System.Threading.Tasks.Dataflow.WriteOnceBlock< T >._decliningPermanently, System.Threading.Tasks.Dataflow.WriteOnceBlock< T >.CompleteBlockAsync(), System.exception, System.list, and System.Threading.Tasks.Dataflow.WriteOnceBlock< T >.ValueLock.
Referenced by System.Threading.Tasks.Dataflow.WriteOnceBlock< T >.Complete(), System.Threading.Tasks.Dataflow.WriteOnceBlock< T >.CompleteBlockAsync(), and System.Threading.Tasks.Dataflow.WriteOnceBlock< T >.Fault().