Terraria: System.Net.Mail.SmtpReplyReader.Close
Close()
void System.Net.Mail.SmtpReplyReader.Close () inline
Definition at line 22 of file SmtpReplyReader.cs.
    {
        _reader.Close(this);
    }
References System.Net.Mail.SmtpReplyReader._reader, and System.Net.Mail.SmtpReplyReaderFactory.Close().
Referenced by System.Net.Mail.SmtpReplyReaderFactory.GetNextReplyReader(), and System.Net.Mail.CheckCommand.Send().