Terraria: System.Net.Mail.SmtpReplyReader.EndReadLines
EndReadLines()
LineInfo[] System.Net.Mail.SmtpReplyReader.EndReadLines (IAsyncResult result) inline package
Definition at line 27 of file SmtpReplyReader.cs.
    {
        return _reader.EndReadLines(result);
    }
References System.Net.Mail.SmtpReplyReader._reader, and System.Net.Mail.SmtpReplyReaderFactory.EndReadLines().
Referenced by System.Net.Mail.ReadLinesCommand.BeginSend(), and System.Net.Mail.ReadLinesCommand.OnReadLines().