Terraria: Terraria.Social.Steam.Lobby.SetPlayedWith
SetPlayedWith()
void Terraria.Social.Steam.Lobby.SetPlayedWith (CSteamID userId) inline
Definition at line 128 of file Lobby.cs.
    {
        //IL_0006: Unknown result type (might be due to invalid IL or missing references)
        //IL_000f: Unknown result type (might be due to invalid IL or missing references)
        //IL_001b: Unknown result type (might be due to invalid IL or missing references)
        if (!_usersSeen.Contains(userId))
        {
            SteamFriends.SetPlayedWith(userId);
            _usersSeen.Add(userId);
        }
    }
References Terraria.Social.Steam.Lobby._usersSeen, System.Collections.Generic.HashSet< T >.Add(), and System.Collections.Generic.HashSet< T >.Contains().
Referenced by Terraria.Social.Steam.NetSocialModule.OnLobbyChatMessage().