Terraria: CreativePowers.ModifyRainPower.UpdateSliderAndShowMultiplierMouseOver
UpdateSliderAndShowMultiplierMouseOver()
void CreativePowers.ModifyRainPower.UpdateSliderAndShowMultiplierMouseOver (UIElement affectedElement) inline private
         {
             if (affectedElement.IsMouseHovering)
             {
                 string originalText = Main.maxRaining.ToString("P0");
                 CreativePowersHelper.AddPermissionTextIfNeeded(this, ref originalText);
                 Main.instance.MouseTextNoOverride(originalText, 0, 0);
             }
         }
References CreativePowersHelper.AddPermissionTextIfNeeded(), Main.instance, UIElement.IsMouseHovering, Main.maxRaining, and Main.MouseTextNoOverride().
Referenced by CreativePowers.ModifyRainPower.ProvideSlider().