Terraria: Internal.Cryptography.HashProviderDispenser.CreateHashProvider
CreateHashProvider()
static HashProvider Internal.Cryptography.HashProviderDispenser.CreateHashProvider (string hashAlgorithmId) inline static
Definition at line 117 of file HashProviderDispenser.cs.
    {
        return new HashProviderCng(hashAlgorithmId, null);
    }
Referenced by System.Security.Cryptography.MD5.Implementation.Implementation(), System.Security.Cryptography.SHA1.Implementation.Implementation(), System.Security.Cryptography.SHA256.Implementation.Implementation(), System.Security.Cryptography.SHA384.Implementation.Implementation(), System.Security.Cryptography.SHA512.Implementation.Implementation(), System.Security.Cryptography.SHA1Managed.SHA1Managed(), System.Security.Cryptography.SHA256Managed.SHA256Managed(), System.Security.Cryptography.SHA384Managed.SHA384Managed(), System.Security.Cryptography.SHA512Managed.SHA512Managed(), Internal.Cryptography.HMACCommon.ChangeKeyImpl(), and System.Security.Cryptography.IncrementalHash.CreateHash().