Terraria: System.ComponentModel.TypeDescriptor.CheckDefaultProvider
CheckDefaultProvider()
static void System.ComponentModel.TypeDescriptor.CheckDefaultProvider (Type type) inline static private
Definition at line 1199 of file TypeDescriptor.cs.
    {
        if (s_defaultProviders.ContainsKey(type))
        {
            return;
        }
        lock (s_internalSyncObject)
        {
            if (s_defaultProviders.ContainsKey(type))
            {
                return;
            }
            s_defaultProviders[type] = null;
        }
        object[] customAttributes = type.GetCustomAttributes(typeof(TypeDescriptionProviderAttribute), inherit: false);
        bool flag = false;
        for (int num = customAttributes.Length - 1; num >= 0; num--)
        {
            TypeDescriptionProviderAttribute typeDescriptionProviderAttribute = (TypeDescriptionProviderAttribute)customAttributes[num];
            Type type2 = Type.GetType(typeDescriptionProviderAttribute.TypeName);
            if (type2 != null && typeof(TypeDescriptionProvider).IsAssignableFrom(type2))
            {
                TypeDescriptionProvider provider = (TypeDescriptionProvider)Activator.CreateInstance(type2);
                AddProvider(provider, type);
                flag = true;
            }
        }
        if (!flag)
        {
            Type baseType = type.BaseType;
            if (baseType != null && baseType != type)
            {
                CheckDefaultProvider(baseType);
            }
        }
    }
References System.ComponentModel.TypeDescriptor.AddProvider(), System.Type.BaseType, System.ComponentModel.TypeDescriptor.CheckDefaultProvider(), System.Activator.CreateInstance(), System.Type.GetType(), System.Type.IsAssignableFrom(), System.ComponentModel.TypeDescriptor.s_defaultProviders, System.ComponentModel.TypeDescriptor.s_internalSyncObject, System.type, and System.ComponentModel.TypeDescriptionProviderAttribute.TypeName.
Referenced by System.ComponentModel.TypeDescriptor.CheckDefaultProvider(), and System.ComponentModel.TypeDescriptor.NodeFor().