Terraria: System.ComponentModel.TypeDescriptor.PipelineAttributeFilter
PipelineAttributeFilter()
static ICollection System.ComponentModel.TypeDescriptor.PipelineAttributeFilter (int pipelineType, ICollection members, Attribute[] filter, object instance, IDictionary cache) inline static private
Definition at line 2071 of file TypeDescriptor.cs.
    {
        IList list = members as ArrayList;
        if (filter == null || filter.Length == 0)
        {
            return members;
        }
        if (cache != null && (list == null || list.IsReadOnly) && cache[s_pipelineAttributeFilterKeys[pipelineType]] is AttributeFilterCacheItem attributeFilterCacheItem && attributeFilterCacheItem.IsValid(filter))
        {
            return attributeFilterCacheItem.FilteredMembers;
        }
        if (list == null || list.IsReadOnly)
        {
            list = new ArrayList(members);
        }
        ArrayList arrayList = FilterMembers(list, filter);
        if (arrayList != null)
        {
            list = arrayList;
        }
        if (cache != null)
        {
            ICollection filteredMembers;
            switch (pipelineType)
            {
            case 1:
            {
                PropertyDescriptor[] array2 = new PropertyDescriptor[list.Count];
                list.CopyTo(array2, 0);
                filteredMembers = new PropertyDescriptorCollection(array2, readOnly: true);
                break;
            }
            case 2:
            {
                EventDescriptor[] array = new EventDescriptor[list.Count];
                list.CopyTo(array, 0);
                filteredMembers = new EventDescriptorCollection(array, readOnly: true);
                break;
            }
            default:
                filteredMembers = null;
                break;
            }
            AttributeFilterCacheItem value = new AttributeFilterCacheItem(filter, filteredMembers);
            cache[s_pipelineAttributeFilterKeys[pipelineType]] = value;
        }
        return list;
    }
References System.array, System.ComponentModel.TypeDescriptor.FilterMembers(), System.ComponentModel.TypeDescriptor.AttributeFilterCacheItem.IsValid(), System.list, System.ComponentModel.TypeDescriptor.s_pipelineAttributeFilterKeys, and System.value.
Referenced by System.ComponentModel.TypeDescriptor.GetEvents(), and System.ComponentModel.TypeDescriptor.GetPropertiesImpl().