Terraria: System.ComponentModel.TypeDescriptor.GetAttributes
GetAttributes() [1/3]
static AttributeCollection System.ComponentModel.TypeDescriptor.GetAttributes ([DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.All)] Type componentType) inline static
Definition at line 1422 of file TypeDescriptor.cs.
    {
        if (componentType == null)
        {
            return new AttributeCollection((Attribute[]?)null);
        }
        return GetDescriptor(componentType, "componentType").GetAttributes();
    }
References System.ComponentModel.TypeDescriptor.GetDescriptor().
Referenced by System.ComponentModel.TypeDescriptor.CreateDesigner(), System.ComponentModel.ReflectPropertyDescriptor.FillAttributes(), System.ComponentModel.DataAnnotations.AssociatedMetadataTypeTypeDescriptor.GetAttributes(), System.ComponentModel.ReflectTypeDescriptionProvider.ReflectedTypeData.GetAttributes(), System.Data.Common.DbConnectionStringBuilder.GetAttributes(), System.ComponentModel.TypeDescriptor.GetAttributes(), System.ComponentModel.ReflectTypeDescriptionProvider.ReflectedTypeData.GetConverter(), System.ComponentModel.ReflectTypeDescriptionProvider.ReflectedTypeData.GetDefaultEvent(), System.ComponentModel.ReflectTypeDescriptionProvider.ReflectedTypeData.GetDefaultProperty(), System.ComponentModel.ReflectTypeDescriptionProvider.ReflectedTypeData.GetEditor(), System.ComponentModel.DataAnnotations.ValidationAttributeStore.TypeStoreItem.GetExplicitAttributes(), System.ComponentModel.DataAnnotations.ValidationAttributeStore.GetTypeStoreItem(), System.ComponentModel.ReflectTypeDescriptionProvider.ReflectGetExtendedProperties(), and System.ComponentModel.Container.ValidateName().