Terraria: System.ComponentModel.TypeDescriptor.PipelineFilter
PipelineFilter()
static ICollection System.ComponentModel.TypeDescriptor.PipelineFilter (int pipelineType, ICollection members, object instance, IDictionary cache) inline static private
Definition at line 2120 of file TypeDescriptor.cs.
    {
        IComponent component = instance as IComponent;
        ITypeDescriptorFilterService typeDescriptorFilterService = null;
        ISite site = component?.Site;
        if (site != null)
        {
            typeDescriptorFilterService = site.GetService(typeof(ITypeDescriptorFilterService)) as ITypeDescriptorFilterService;
        }
        IList list = members as ArrayList;
        if (typeDescriptorFilterService == null)
        {
            return members;
        }
        if (cache != null && (list == null || list.IsReadOnly) && cache[s_pipelineFilterKeys[pipelineType]] is FilterCacheItem filterCacheItem && filterCacheItem.IsValid(typeDescriptorFilterService))
        {
            return filterCacheItem.FilteredMembers;
        }
        OrderedDictionary orderedDictionary = new OrderedDictionary(members.Count);
        bool flag;
        switch (pipelineType)
        {
        case 0:
            foreach (Attribute member in members)
            {
                orderedDictionary[member.TypeId] = member;
            }
            flag = typeDescriptorFilterService.FilterAttributes(component, orderedDictionary);
            break;
        case 1:
        case 2:
            foreach (MemberDescriptor member2 in members)
            {
                string name = member2.Name;
                if (orderedDictionary.Contains(name))
                {
                    string extenderCollisionSuffix = GetExtenderCollisionSuffix(member2);
                    if (extenderCollisionSuffix != null)
                    {
                        orderedDictionary[name + extenderCollisionSuffix] = member2;
                    }
                    MemberDescriptor memberDescriptor2 = (MemberDescriptor)orderedDictionary[name];
                    extenderCollisionSuffix = GetExtenderCollisionSuffix(memberDescriptor2);
                    if (extenderCollisionSuffix != null)
                    {
                        orderedDictionary.Remove(name);
                        orderedDictionary[memberDescriptor2.Name + extenderCollisionSuffix] = memberDescriptor2;
                    }
                }
                else
                {
                    orderedDictionary[name] = member2;
                }
            }
            flag = ((pipelineType != 1) ? typeDescriptorFilterService.FilterEvents(component, orderedDictionary) : typeDescriptorFilterService.FilterProperties(component, orderedDictionary));
            break;
        default:
            flag = false;
            break;
        }
        if (list == null || list.IsReadOnly)
        {
            list = new ArrayList(orderedDictionary.Values);
        }
        else
        {
            list.Clear();
            foreach (object value2 in orderedDictionary.Values)
            {
                list.Add(value2);
            }
        }
        if (flag && cache != null)
        {
            ICollection filteredMembers;
            switch (pipelineType)
            {
            case 0:
            {
                Attribute[] array2 = new Attribute[list.Count];
                try
                {
                    list.CopyTo(array2, 0);
                }
                catch (InvalidCastException)
                {
                    throw new ArgumentException(System.SR.Format(System.SR.TypeDescriptorExpectedElementType, typeof(Attribute).FullName));
                }
                filteredMembers = new AttributeCollection(array2);
                break;
            }
            case 1:
            {
                PropertyDescriptor[] array3 = new PropertyDescriptor[list.Count];
                try
                {
                    list.CopyTo(array3, 0);
                }
                catch (InvalidCastException)
                {
                    throw new ArgumentException(System.SR.Format(System.SR.TypeDescriptorExpectedElementType, typeof(PropertyDescriptor).FullName));
                }
                filteredMembers = new PropertyDescriptorCollection(array3, readOnly: true);
                break;
            }
            case 2:
            {
                EventDescriptor[] array = new EventDescriptor[list.Count];
                try
                {
                    list.CopyTo(array, 0);
                }
                catch (InvalidCastException)
                {
                    throw new ArgumentException(System.SR.Format(System.SR.TypeDescriptorExpectedElementType, typeof(EventDescriptor).FullName));
                }
                filteredMembers = new EventDescriptorCollection(array, readOnly: true);
                break;
            }
            default:
                filteredMembers = null;
                break;
            }
            FilterCacheItem value = new FilterCacheItem(typeDescriptorFilterService, filteredMembers);
            cache[s_pipelineFilterKeys[pipelineType]] = value;
            cache.Remove(s_pipelineAttributeFilterKeys[pipelineType]);
        }
        return list;
    }
References System.array, System.Collections.Specialized.OrderedDictionary.Contains(), System.Collections.ICollection.Count, System.ComponentModel.Design.ITypeDescriptorFilterService.FilterAttributes(), System.ComponentModel.Design.ITypeDescriptorFilterService.FilterEvents(), System.ComponentModel.Design.ITypeDescriptorFilterService.FilterProperties(), System.SR.Format(), System.FullName, System.ComponentModel.TypeDescriptor.GetExtenderCollisionSuffix(), System.IServiceProvider.GetService(), System.ComponentModel.TypeDescriptor.FilterCacheItem.IsValid(), System.list, System.ComponentModel.MemberDescriptor.Name, System.Collections.Specialized.OrderedDictionary.Remove(), System.Collections.IDictionary.Remove(), System.ComponentModel.TypeDescriptor.s_pipelineAttributeFilterKeys, System.ComponentModel.TypeDescriptor.s_pipelineFilterKeys, System.ComponentModel.IComponent.Site, System.SR.TypeDescriptorExpectedElementType, System.Attribute.TypeId, System.value, and System.Collections.Specialized.OrderedDictionary.Values.
Referenced by System.ComponentModel.TypeDescriptor.GetAttributes(), System.ComponentModel.TypeDescriptor.GetEvents(), and System.ComponentModel.TypeDescriptor.GetPropertiesImpl().