Terraria: System.ComponentModel.TypeDescriptor.GetDefaultProperty
GetDefaultProperty() [1/3]
static ? PropertyDescriptor System.ComponentModel.TypeDescriptor.GetDefaultProperty ([DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.All)] Type componentType) inline static
Definition at line 1580 of file TypeDescriptor.cs.
    {
        if (componentType == null)
        {
            return null;
        }
        return GetDescriptor(componentType, "componentType").GetDefaultProperty();
    }
References System.ComponentModel.TypeDescriptor.GetDescriptor().
Referenced by System.Data.Common.DbConnectionStringBuilder.GetDefaultProperty(), and System.ComponentModel.TypeDescriptor.GetDefaultProperty().