Terraria: System.ComponentModel.TypeDescriptor.FilterMembers
FilterMembers()
static ArrayList System.ComponentModel.TypeDescriptor.FilterMembers (IList members, Attribute[] attributes) inline static private
Definition at line 1338 of file TypeDescriptor.cs.
    {
        ArrayList arrayList = null;
        int count = members.Count;
        for (int i = 0; i < count; i++)
        {
            bool flag = false;
            for (int j = 0; j < attributes.Length; j++)
            {
                if (ShouldHideMember((MemberDescriptor)members[i], attributes[j]))
                {
                    flag = true;
                    break;
                }
            }
            if (flag)
            {
                if (arrayList == null)
                {
                    arrayList = new ArrayList(count);
                    for (int k = 0; k < i; k++)
                    {
                        arrayList.Add(members[k]);
                    }
                }
            }
            else
            {
                arrayList?.Add(members[i]);
            }
        }
        return arrayList;
    }
References System.Collections.ArrayList.Add(), System.count, System.Collections.ICollection.Count, and System.ComponentModel.TypeDescriptor.ShouldHideMember().
Referenced by System.ComponentModel.TypeDescriptor.GetEvents(), System.ComponentModel.TypeDescriptor.GetProperties(), and System.ComponentModel.TypeDescriptor.PipelineAttributeFilter().