Terraria: System.ComponentModel.TypeDescriptor.NodeFor
NodeFor() [3/4]
static TypeDescriptionNode System.ComponentModel.TypeDescriptor.NodeFor (Type type) inline static private
Definition at line 1966 of file TypeDescriptor.cs.
    {
        return NodeFor(type, createDelegator: false);
    }
References System.ComponentModel.TypeDescriptor.NodeFor(), and System.type.
Referenced by System.ComponentModel.TypeDescriptor.AddProvider(), System.ComponentModel.TypeDescriptor.AddProvider(), System.ComponentModel.TypeDescriptor.CreateInstance(), System.ComponentModel.TypeDescriptor.GetCache(), System.ComponentModel.TypeDescriptor.GetDescriptor(), System.ComponentModel.TypeDescriptor.GetDescriptor(), System.ComponentModel.TypeDescriptor.GetExtendedDescriptor(), System.ComponentModel.TypeDescriptor.GetProvider(), System.ComponentModel.TypeDescriptor.GetProvider(), System.ComponentModel.TypeDescriptor.GetProviderRecursive(), System.ComponentModel.TypeDescriptor.GetReflectionType(), System.ComponentModel.TypeDescriptor.GetReflectionType(), System.ComponentModel.TypeDescriptor.NodeFor(), System.ComponentModel.TypeDescriptor.NodeFor(), and System.ComponentModel.TypeDescriptor.NodeFor().