Terraria: System.ComponentModel.TypeDescriptor.GetDescriptor
GetDescriptor() [1/2]
static ICustomTypeDescriptor System.ComponentModel.TypeDescriptor.GetDescriptor ([DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.All)] Type type, string typeName) inline static package
Definition at line 1606 of file TypeDescriptor.cs.
    {
        if (type == null)
        {
            throw new ArgumentNullException(typeName);
        }
        return NodeFor(type).GetTypeDescriptor(type);
    }
References System.ComponentModel.TypeDescriptor.NodeFor(), and System.type.
Referenced by System.ComponentModel.TypeDescriptor.GetAttributes(), System.ComponentModel.TypeDescriptor.GetAttributes(), System.ComponentModel.TypeDescriptor.GetClassName(), System.ComponentModel.TypeDescriptor.GetClassName(), System.ComponentModel.TypeDescriptor.GetComponentName(), System.ComponentModel.TypeDescriptor.GetConverter(), System.ComponentModel.TypeDescriptor.GetConverter(), System.ComponentModel.TypeDescriptor.GetDefaultEvent(), System.ComponentModel.TypeDescriptor.GetDefaultEvent(), System.ComponentModel.TypeDescriptor.GetDefaultProperty(), System.ComponentModel.TypeDescriptor.GetDefaultProperty(), System.ComponentModel.TypeDescriptor.GetEditor(), System.ComponentModel.TypeDescriptor.GetEditor(), System.ComponentModel.TypeDescriptor.GetEvents(), System.ComponentModel.TypeDescriptor.GetEvents(), System.ComponentModel.TypeDescriptor.GetEvents(), System.ComponentModel.TypeDescriptor.GetProperties(), System.ComponentModel.TypeDescriptor.GetProperties(), and System.ComponentModel.TypeDescriptor.GetPropertiesImpl().