Terraria: System.ComponentModel.TypeDescriptor.NodeRemove
NodeRemove()
static void System.ComponentModel.TypeDescriptor.NodeRemove (object key, TypeDescriptionProvider provider) inline static private
Definition at line 2032 of file TypeDescriptor.cs.
    {
        lock (s_providerTable)
        {
            TypeDescriptionNode typeDescriptionNode = (TypeDescriptionNode)s_providerTable[key];
            TypeDescriptionNode typeDescriptionNode2 = typeDescriptionNode;
            TypeDescriptionNode typeDescriptionNode3 = null;
            while (typeDescriptionNode2 != null && typeDescriptionNode2.Provider != provider)
            {
                typeDescriptionNode3 = typeDescriptionNode2;
                typeDescriptionNode2 = typeDescriptionNode2.Next;
            }
            if (typeDescriptionNode2 == null)
            {
                return;
            }
            if (typeDescriptionNode2.Next != null)
            {
                typeDescriptionNode2.Provider = typeDescriptionNode2.Next.Provider;
                typeDescriptionNode2.Next = typeDescriptionNode2.Next.Next;
                if (typeDescriptionNode2 == typeDescriptionNode && typeDescriptionNode2.Provider is DelegatingTypeDescriptionProvider)
                {
                    s_providerTable.Remove(key);
                }
            }
            else if (typeDescriptionNode2 != typeDescriptionNode)
            {
                Type type = (key as Type) ?? key.GetType();
                typeDescriptionNode2.Provider = new DelegatingTypeDescriptionProvider(type.BaseType);
            }
            else
            {
                s_providerTable.Remove(key);
            }
            s_providerTypeTable.Clear();
        }
    }
References System.Type.GetType(), System.key, System.ComponentModel.TypeDescriptor.TypeDescriptionNode.Next, System.ComponentModel.TypeDescriptor.TypeDescriptionNode.Provider, System.ComponentModel.TypeDescriptor.s_providerTable, System.ComponentModel.TypeDescriptor.s_providerTypeTable, System.Reflection.Type, and System.type.
Referenced by System.ComponentModel.TypeDescriptor.RemoveProvider(), and System.ComponentModel.TypeDescriptor.RemoveProvider().