Terraria: System.ComponentModel.TypeDescriptor.GetAssociation
GetAssociation()
static object System.ComponentModel.TypeDescriptor.GetAssociation (Type type, object primary) inline static
Definition at line 1373 of file TypeDescriptor.cs.
    {
        if (type == null)
        {
            throw new ArgumentNullException("type");
        }
        if (primary == null)
        {
            throw new ArgumentNullException("primary");
        }
        object obj = primary;
        if (!type.IsInstanceOfType(primary))
        {
            IList list = (IList)(AssociationTable?[primary]);
            if (list != null)
            {
                lock (list)
                {
                    for (int num = list.Count - 1; num >= 0; num--)
                    {
                        WeakReference weakReference = (WeakReference)list[num];
                        object target = weakReference.Target;
                        if (target == null)
{
                            list.RemoveAt(num);
                        }
                        else if (type.IsInstanceOfType(target))
{
                            obj = target;
                        }
                    }
                }
            }
            if (obj == primary && primary is IComponent component)
            {
                ISite site = component.Site;
                if (site != null && site.DesignMode && site.GetService(typeof(IDesignerHost)) is IDesignerHost designerHost)
                {
                    object designer = designerHost.GetDesigner(component);
                    if (designer != null && type.IsInstanceOfType(designer))
                    {
                        obj = designer;
                    }
                }
            }
        }
        return obj;
    }
References System.ComponentModel.TypeDescriptor.AssociationTable, System.ComponentModel.ISite.DesignMode, System.IServiceProvider.GetService(), System.list, System.obj, System.WeakReference< T >.Target, and System.type.
Referenced by System.ComponentModel.MemberDescriptor.GetInvocationTarget(), System.ComponentModel.MemberDescriptor.GetInvokee(), and System.ComponentModel.ReflectTypeDescriptionProvider.GetPropertyOwner().