Terraria: System.ComponentModel.TypeDescriptor.GetAttributes
GetAttributes() [3/3]
static AttributeCollection System.ComponentModel.TypeDescriptor.GetAttributes (object component, bool noCustomTypeDesc) inline static
Definition at line 1439 of file TypeDescriptor.cs.
    {
        if (component == null)
        {
            return new AttributeCollection((Attribute[]?)null);
        }
        ICustomTypeDescriptor descriptor = GetDescriptor(component, noCustomTypeDesc);
        ICollection collection = descriptor.GetAttributes();
        if (component is ICustomTypeDescriptor)
        {
            if (noCustomTypeDesc)
            {
                ICustomTypeDescriptor extendedDescriptor = GetExtendedDescriptor(component);
                if (extendedDescriptor != null)
                {
                    ICollection attributes = extendedDescriptor.GetAttributes();
                    collection = PipelineMerge(0, collection, attributes, component, null);
                }
            }
            else
            {
                collection = PipelineFilter(0, collection, component, null);
            }
        }
        else
        {
            IDictionary cache = GetCache(component);
            collection = PipelineInitialize(0, collection, cache);
            ICustomTypeDescriptor extendedDescriptor2 = GetExtendedDescriptor(component);
            if (extendedDescriptor2 != null)
            {
                ICollection attributes2 = extendedDescriptor2.GetAttributes();
                collection = PipelineMerge(0, collection, attributes2, component, cache);
            }
            collection = PipelineFilter(0, collection, component, cache);
        }
        AttributeCollection attributeCollection = collection as AttributeCollection;
        if (attributeCollection == null)
        {
            Attribute[] array = new Attribute[collection.Count];
            collection.CopyTo(array, 0);
            attributeCollection = new AttributeCollection(array);
        }
        return attributeCollection;
    }
References System.array, System.collection, System.ComponentModel.ICustomTypeDescriptor.GetAttributes(), System.ComponentModel.TypeDescriptor.GetCache(), System.ComponentModel.TypeDescriptor.GetDescriptor(), System.ComponentModel.TypeDescriptor.GetExtendedDescriptor(), System.ComponentModel.TypeDescriptor.PipelineFilter(), System.ComponentModel.TypeDescriptor.PipelineInitialize(), and System.ComponentModel.TypeDescriptor.PipelineMerge().