Terraria: System.ComponentModel.TypeDescriptor.GetEvents
GetEvents() [1/6]
static EventDescriptorCollection System.ComponentModel.TypeDescriptor.GetEvents ([DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.All)] Type componentType) inline static
Definition at line 1668 of file TypeDescriptor.cs.
    {
        if (componentType == null)
        {
            return new EventDescriptorCollection(null, readOnly: true);
        }
        return GetDescriptor(componentType, "componentType").GetEvents();
    }
References System.ComponentModel.TypeDescriptor.GetDescriptor().
Referenced by System.ComponentModel.ReflectTypeDescriptionProvider.ReflectedTypeData.GetDefaultEvent(), System.Data.Common.DbConnectionStringBuilder.GetEvents(), System.Data.Common.DbConnectionStringBuilder.GetEvents(), System.ComponentModel.TypeDescriptor.GetEvents(), System.ComponentModel.TypeDescriptor.GetEvents(), and System.ComponentModel.TypeDescriptor.GetEvents().