Terraria: System.ComponentModel.TypeDescriptor.GetEvents
GetEvents() [5/6]
static EventDescriptorCollection System.ComponentModel.TypeDescriptor.GetEvents (object component, Attribute?[] attributes, bool noCustomTypeDesc) inline static
Definition at line 1719 of file TypeDescriptor.cs.
    {
        if (component == null)
        {
            return new EventDescriptorCollection(null, readOnly: true);
        }
        ICustomTypeDescriptor descriptor = GetDescriptor(component, noCustomTypeDesc);
        ICollection collection;
        if (component is ICustomTypeDescriptor)
        {
            collection = descriptor.GetEvents(attributes);
            if (noCustomTypeDesc)
            {
                ICustomTypeDescriptor extendedDescriptor = GetExtendedDescriptor(component);
                if (extendedDescriptor != null)
                {
                    ICollection events = extendedDescriptor.GetEvents(attributes);
                    collection = PipelineMerge(2, collection, events, component, null);
                }
            }
            else
            {
                collection = PipelineFilter(2, collection, component, null);
                collection = PipelineAttributeFilter(2, collection, attributes, component, null);
            }
        }
        else
        {
            IDictionary cache = GetCache(component);
            collection = descriptor.GetEvents(attributes);
            collection = PipelineInitialize(2, collection, cache);
            ICustomTypeDescriptor extendedDescriptor2 = GetExtendedDescriptor(component);
            if (extendedDescriptor2 != null)
            {
                ICollection events2 = extendedDescriptor2.GetEvents(attributes);
                collection = PipelineMerge(2, collection, events2, component, cache);
            }
            collection = PipelineFilter(2, collection, component, cache);
            collection = PipelineAttributeFilter(2, collection, attributes, component, cache);
        }
        EventDescriptorCollection eventDescriptorCollection = collection as EventDescriptorCollection;
        if (eventDescriptorCollection == null)
        {
            EventDescriptor[] array = new EventDescriptor[collection.Count];
            collection.CopyTo(array, 0);
            eventDescriptorCollection = new EventDescriptorCollection(array, readOnly: true);
        }
        return eventDescriptorCollection;
    }
References System.array, System.collection, System.ComponentModel.TypeDescriptor.GetCache(), System.ComponentModel.TypeDescriptor.GetDescriptor(), System.ComponentModel.ICustomTypeDescriptor.GetEvents(), System.ComponentModel.TypeDescriptor.GetExtendedDescriptor(), System.ComponentModel.TypeDescriptor.PipelineAttributeFilter(), System.ComponentModel.TypeDescriptor.PipelineFilter(), System.ComponentModel.TypeDescriptor.PipelineInitialize(), and System.ComponentModel.TypeDescriptor.PipelineMerge().