Terraria: System.ComponentModel.TypeDescriptor.Refresh
Refresh() [2/5]
static void System.ComponentModel.TypeDescriptor.Refresh (Module module) inline static
Definition at line 2475 of file TypeDescriptor.cs.
    {
        if (module == null)
        {
            return;
        }
        Hashtable hashtable = null;
        lock (s_providerTable)
        {
            IDictionaryEnumerator enumerator = s_providerTable.GetEnumerator();
            while (enumerator.MoveNext())
            {
                DictionaryEntry entry = enumerator.Entry;
                Type type = entry.Key as Type;
                if ((!(type != null) || !type.Module.Equals(module)) && !(type == typeof(object)))
                {
                    continue;
                }
                TypeDescriptionNode typeDescriptionNode = (TypeDescriptionNode)entry.Value;
                while (typeDescriptionNode != null && !(typeDescriptionNode.Provider is ReflectTypeDescriptionProvider))
                {
                    if (hashtable == null)
                    {
                        hashtable = new Hashtable();
                    }
                    hashtable[type] = type;
                    typeDescriptionNode = typeDescriptionNode.Next;
                }
                if (typeDescriptionNode == null)
                {
                    continue;
                }
                ReflectTypeDescriptionProvider reflectTypeDescriptionProvider = (ReflectTypeDescriptionProvider)typeDescriptionNode.Provider;
                Type[] populatedTypes = reflectTypeDescriptionProvider.GetPopulatedTypes(module);
                Type[] array = populatedTypes;
                foreach (Type type2 in array)
                {
                    reflectTypeDescriptionProvider.Refresh(type2);
                    if (hashtable == null)
                    {
                        hashtable = new Hashtable();
                    }
                    hashtable[type2] = type2;
                }
            }
        }
        if (hashtable == null || TypeDescriptor.Refreshed == null)
        {
            return;
        }
        foreach (Type key in hashtable.Keys)
        {
            RaiseRefresh(key);
        }
    }
References System.array, System.Collections.IDictionaryEnumerator.Entry, System.ComponentModel.ReflectTypeDescriptionProvider.GetPopulatedTypes(), System.key, System.Collections.IEnumerator.MoveNext(), System.ComponentModel.TypeDescriptor.TypeDescriptionNode.Next, System.ComponentModel.TypeDescriptor.TypeDescriptionNode.Provider, System.ComponentModel.TypeDescriptor.RaiseRefresh(), System.ComponentModel.TypeDescriptor.Refreshed, System.ComponentModel.TypeDescriptor.s_providerTable, System.Reflection.Type, System.type, and System.Collections.DictionaryEntry.Value.