Terraria: System.ComponentModel.TypeDescriptor.GetProperties
GetProperties() [2/6]
static PropertyDescriptorCollection System.ComponentModel.TypeDescriptor.GetProperties ([DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.All)] Type componentType, Attribute?[] attributes) inline static
Definition at line 1823 of file TypeDescriptor.cs.
    {
        if (componentType == null)
        {
            return new PropertyDescriptorCollection(null, readOnly: true);
        }
        PropertyDescriptorCollection propertyDescriptorCollection = GetDescriptor(componentType, "componentType").GetProperties(attributes);
        if (attributes != null && attributes.Length != 0)
        {
            ArrayList arrayList = FilterMembers(propertyDescriptorCollection, attributes);
            if (arrayList != null)
            {
                PropertyDescriptor[] array = new PropertyDescriptor[arrayList.Count];
                arrayList.CopyTo(array);
                propertyDescriptorCollection = new PropertyDescriptorCollection(array, readOnly: true);
            }
        }
        return propertyDescriptorCollection;
    }
References System.array, System.Collections.ArrayList.CopyTo(), System.Collections.ArrayList.Count, System.ComponentModel.TypeDescriptor.FilterMembers(), and System.ComponentModel.TypeDescriptor.GetDescriptor().