Terraria: System.ComponentModel.TypeDescriptor.PipelineMerge
PipelineMerge()
static ICollection System.ComponentModel.TypeDescriptor.PipelineMerge (int pipelineType, ICollection primary, ICollection secondary, object instance, IDictionary cache) inline static private
Definition at line 2279 of file TypeDescriptor.cs.
    {
        if (secondary == null || secondary.Count == 0)
        {
            return primary;
        }
        if (cache?[s_pipelineMergeKeys[pipelineType]] is ICollection collection && collection.Count == primary.Count + secondary.Count)
        {
            IEnumerator enumerator = collection.GetEnumerator();
            IEnumerator enumerator2 = primary.GetEnumerator();
            bool flag = true;
            while (enumerator2.MoveNext() && enumerator.MoveNext())
            {
                if (enumerator2.Current != enumerator.Current)
                {
                    flag = false;
                    break;
                }
            }
            if (flag)
            {
                IEnumerator enumerator3 = secondary.GetEnumerator();
                while (enumerator3.MoveNext() && enumerator.MoveNext())
                {
                    if (enumerator3.Current != enumerator.Current)
                    {
                        flag = false;
                        break;
                    }
                }
            }
            if (flag)
            {
                return collection;
            }
        }
        ArrayList arrayList = new ArrayList(primary.Count + secondary.Count);
        foreach (object item in primary)
        {
            arrayList.Add(item);
        }
        foreach (object item2 in secondary)
        {
            arrayList.Add(item2);
        }
        if (cache != null)
        {
            ICollection value;
            switch (pipelineType)
            {
            case 0:
            {
                Attribute[] array3 = new Attribute[arrayList.Count];
                arrayList.CopyTo(array3, 0);
                value = new AttributeCollection(array3);
                break;
            }
            case 1:
            {
                PropertyDescriptor[] array2 = new PropertyDescriptor[arrayList.Count];
                arrayList.CopyTo(array2, 0);
                value = new PropertyDescriptorCollection(array2, readOnly: true);
                break;
            }
            case 2:
            {
                EventDescriptor[] array = new EventDescriptor[arrayList.Count];
                arrayList.CopyTo(array, 0);
                value = new EventDescriptorCollection(array, readOnly: true);
                break;
            }
            default:
                value = null;
                break;
            }
            cache[s_pipelineMergeKeys[pipelineType]] = value;
            cache.Remove(s_pipelineFilterKeys[pipelineType]);
            cache.Remove(s_pipelineAttributeFilterKeys[pipelineType]);
        }
        return arrayList;
    }
References System.array, System.collection, System.Collections.ICollection.Count, System.Collections.IEnumerator.Current, System.Collections.IEnumerable.GetEnumerator(), System.item, System.Collections.IEnumerator.MoveNext(), System.ComponentModel.EventDescriptorCollection.Remove(), System.ComponentModel.TypeDescriptor.s_pipelineAttributeFilterKeys, System.ComponentModel.TypeDescriptor.s_pipelineFilterKeys, System.ComponentModel.TypeDescriptor.s_pipelineMergeKeys, and System.value.
Referenced by System.ComponentModel.TypeDescriptor.GetAttributes(), System.ComponentModel.TypeDescriptor.GetEvents(), and System.ComponentModel.TypeDescriptor.GetPropertiesImpl().