Terraria: System.ComponentModel.TypeDescriptor.AddProvider
AddProvider() [2/2]
static void System.ComponentModel.TypeDescriptor.AddProvider (TypeDescriptionProvider provider, Type type) inline static
Definition at line 1119 of file TypeDescriptor.cs.
    {
        if (provider == null)
        {
            throw new ArgumentNullException("provider");
        }
        if (type == null)
        {
            throw new ArgumentNullException("type");
        }
        lock (s_providerTable)
        {
            TypeDescriptionNode next = NodeFor(type, createDelegator: true);
            TypeDescriptionNode value = new TypeDescriptionNode(provider)
            {
                Next = next
            };
            s_providerTable[type] = value;
            s_providerTypeTable.Clear();
        }
        Refresh(type);
    }
References System.ComponentModel.TypeDescriptor.NodeFor(), System.ComponentModel.Refresh, System.ComponentModel.TypeDescriptor.s_providerTable, System.ComponentModel.TypeDescriptor.s_providerTypeTable, System.type, and System.value.
Referenced by System.ComponentModel.TypeDescriptor.AddAttributes(), System.ComponentModel.TypeDescriptor.AddAttributes(), System.ComponentModel.TypeDescriptor.AddProviderTransparent(), System.ComponentModel.TypeDescriptor.AddProviderTransparent(), and System.ComponentModel.TypeDescriptor.CheckDefaultProvider().