Terraria: System.ComponentModel.TypeDescriptor.Refresh
Refresh() [5/5]
static void System.ComponentModel.TypeDescriptor.Refresh (Type type) inline static
Definition at line 2433 of file TypeDescriptor.cs.
    {
        if (type == null)
        {
            return;
        }
        bool flag = false;
        lock (s_providerTable)
        {
            IDictionaryEnumerator enumerator = s_providerTable.GetEnumerator();
            while (enumerator.MoveNext())
            {
                DictionaryEntry entry = enumerator.Entry;
                Type type2 = entry.Key as Type;
                if ((!(type2 != null) || !type.IsAssignableFrom(type2)) && !(type2 == typeof(object)))
                {
                    continue;
                }
                TypeDescriptionNode typeDescriptionNode = (TypeDescriptionNode)entry.Value;
                while (typeDescriptionNode != null && !(typeDescriptionNode.Provider is ReflectTypeDescriptionProvider))
                {
                    flag = true;
                    typeDescriptionNode = typeDescriptionNode.Next;
                }
                if (typeDescriptionNode != null)
                {
                    ReflectTypeDescriptionProvider reflectTypeDescriptionProvider = (ReflectTypeDescriptionProvider)typeDescriptionNode.Provider;
                    if (reflectTypeDescriptionProvider.IsPopulated(type))
                    {
                        flag = true;
                        reflectTypeDescriptionProvider.Refresh(type);
                    }
                }
            }
        }
        if (flag)
        {
            Interlocked.Increment(ref s_metadataVersion);
            RaiseRefresh(type);
        }
    }
References System.Collections.IDictionaryEnumerator.Entry, System.Threading.Interlocked.Increment(), System.ComponentModel.ReflectTypeDescriptionProvider.IsPopulated(), System.Collections.IEnumerator.MoveNext(), System.ComponentModel.TypeDescriptor.TypeDescriptionNode.Next, System.ComponentModel.TypeDescriptor.TypeDescriptionNode.Provider, System.ComponentModel.TypeDescriptor.RaiseRefresh(), System.ComponentModel.ReflectTypeDescriptionProvider.Refresh(), System.ComponentModel.TypeDescriptor.s_metadataVersion, System.ComponentModel.TypeDescriptor.s_providerTable, System.Reflection.Type, System.type, and System.Collections.DictionaryEntry.Value.