Terraria: System.ComponentModel.TypeDescriptor.GetExtendedDescriptor
GetExtendedDescriptor()
static ICustomTypeDescriptor System.ComponentModel.TypeDescriptor.GetExtendedDescriptor (object component) inline static package
Definition at line 1632 of file TypeDescriptor.cs.
    {
        if (component == null)
        {
            throw new ArgumentException("component");
        }
        return NodeFor(component).GetExtendedTypeDescriptor(component);
    }
References System.ComponentModel.TypeDescriptor.NodeFor().
Referenced by System.ComponentModel.TypeDescriptor.GetAttributes(), System.ComponentModel.TypeDescriptor.GetEvents(), and System.ComponentModel.TypeDescriptor.GetPropertiesImpl().