Terraria: System.ComponentModel.TypeDescriptor.GetPropertiesImpl
GetPropertiesImpl()
static PropertyDescriptorCollection System.ComponentModel.TypeDescriptor.GetPropertiesImpl (object component, Attribute[] attributes, bool noCustomTypeDesc, bool noAttributes) inline static private
Definition at line 1869 of file TypeDescriptor.cs.
    {
        if (component == null)
        {
            return new PropertyDescriptorCollection(null, readOnly: true);
        }
        ICustomTypeDescriptor descriptor = GetDescriptor(component, noCustomTypeDesc);
        ICollection collection;
        if (component is ICustomTypeDescriptor)
        {
            collection = (noAttributes ? descriptor.GetProperties() : descriptor.GetProperties(attributes));
            if (noCustomTypeDesc)
            {
                ICustomTypeDescriptor extendedDescriptor = GetExtendedDescriptor(component);
                if (extendedDescriptor != null)
                {
                    ICollection secondary = (noAttributes ? extendedDescriptor.GetProperties() : extendedDescriptor.GetProperties(attributes));
                    collection = PipelineMerge(1, collection, secondary, component, null);
                }
            }
            else
            {
                collection = PipelineFilter(1, collection, component, null);
                collection = PipelineAttributeFilter(1, collection, attributes, component, null);
            }
        }
        else
        {
            IDictionary cache = GetCache(component);
            collection = (noAttributes ? descriptor.GetProperties() : descriptor.GetProperties(attributes));
            collection = PipelineInitialize(1, collection, cache);
            ICustomTypeDescriptor extendedDescriptor2 = GetExtendedDescriptor(component);
            if (extendedDescriptor2 != null)
            {
                ICollection secondary2 = (noAttributes ? extendedDescriptor2.GetProperties() : extendedDescriptor2.GetProperties(attributes));
                collection = PipelineMerge(1, collection, secondary2, component, cache);
            }
            collection = PipelineFilter(1, collection, component, cache);
            collection = PipelineAttributeFilter(1, collection, attributes, component, cache);
        }
        PropertyDescriptorCollection propertyDescriptorCollection = collection as PropertyDescriptorCollection;
        if (propertyDescriptorCollection == null)
        {
            PropertyDescriptor[] array = new PropertyDescriptor[collection.Count];
            collection.CopyTo(array, 0);
            propertyDescriptorCollection = new PropertyDescriptorCollection(array, readOnly: true);
        }
        return propertyDescriptorCollection;
    }
References System.array, System.collection, System.ComponentModel.TypeDescriptor.GetCache(), System.ComponentModel.TypeDescriptor.GetDescriptor(), System.ComponentModel.TypeDescriptor.GetExtendedDescriptor(), System.ComponentModel.ICustomTypeDescriptor.GetProperties(), System.ComponentModel.TypeDescriptor.PipelineAttributeFilter(), System.ComponentModel.TypeDescriptor.PipelineFilter(), System.ComponentModel.TypeDescriptor.PipelineInitialize(), and System.ComponentModel.TypeDescriptor.PipelineMerge().
Referenced by System.ComponentModel.TypeDescriptor.GetProperties(), and System.ComponentModel.TypeDescriptor.GetProperties().