Terraria: System.ComponentModel.TypeDescriptor.GetProperties
GetProperties() [1/6]
static PropertyDescriptorCollection System.ComponentModel.TypeDescriptor.GetProperties ([DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.All)] Type componentType) inline static
Definition at line 1813 of file TypeDescriptor.cs.
    {
        if (componentType == null)
        {
            return new PropertyDescriptorCollection(null, readOnly: true);
        }
        return GetDescriptor(componentType, "componentType").GetProperties();
    }
References System.ComponentModel.TypeDescriptor.GetDescriptor().
Referenced by System.Data.XmlTreeGen.AddXdoProperties(), System.ComponentModel.ComponentResourceManager.ApplyResources(), Terraria.Localization.LocalizedText.CanFormatWith(), System.ComponentModel.BindingList< T >.Child_PropertyChanged(), System.ComponentModel.DataAnnotations.ValidationAttributeStore.TypeStoreItem.CreatePropertyStoreItems(), Terraria.Localization.LocalizedText.FormatWith(), Terraria.Utils.FormatWith(), System.ComponentModel.PropertyDescriptor.GetChildProperties(), System.ComponentModel.ReflectTypeDescriptionProvider.ReflectedTypeData.GetDefaultProperty(), System.Data.Common.DbConnectionStringBuilder.GetProperties(), System.ComponentModel.ComponentConverter.GetProperties(), System.ComponentModel.ExpandableObjectConverter.GetProperties(), System.Drawing.SizeConverter.GetProperties(), System.Drawing.SizeFConverter.GetProperties(), System.Drawing.PointConverter.GetProperties(), System.Drawing.RectangleConverter.GetProperties(), System.ComponentModel.TypeDescriptor.GetProperties(), System.ComponentModel.TypeDescriptor.GetProperties(), System.ComponentModel.DataAnnotations.Validator.GetPropertyValues(), System.Data.XSDSchema.SetExtProperties(), System.Data.XSDSchema.SetExtProperties(), System.Data.XSDSchema.SetProperties(), and System.Data.XMLSchema.SetProperties().