Terraria: System.ComponentModel.TypeDescriptor.GetConverterTrimUnsafe
GetConverterTrimUnsafe()
static TypeConverter System.ComponentModel.TypeDescriptor.GetConverterTrimUnsafe ([DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.All)] Type type) inline static package
Definition at line 1541 of file TypeDescriptor.cs.
    {
        return GetConverter(type);
    }
References System.ComponentModel.TypeDescriptor.GetConverter(), and System.type.
Referenced by System.Drawing.PointConverter.ConvertFrom(), System.Drawing.RectangleConverter.ConvertFrom(), System.Drawing.SizeConverter.ConvertFrom(), System.Drawing.SizeFConverter.ConvertFrom(), System.Drawing.ColorConverter.ConvertTo(), System.Drawing.PointConverter.ConvertTo(), System.Drawing.RectangleConverter.ConvertTo(), System.Drawing.SizeConverter.ConvertTo(), System.Drawing.SizeFConverter.ConvertTo(), and System.ComponentModel.InheritanceAttribute.ToString().