Terraria: System.ComponentModel.TypeDescriptor.Refresh
Refresh() [4/5]
static void System.ComponentModel.TypeDescriptor.Refresh (object component, bool refreshReflectionProvider) inline static private
Definition at line 2376 of file TypeDescriptor.cs.
    {
        if (component == null)
        {
            return;
        }
        bool flag = false;
        if (refreshReflectionProvider)
        {
            Type type = component.GetType();
            lock (s_providerTable)
            {
                IDictionaryEnumerator enumerator = s_providerTable.GetEnumerator();
                while (enumerator.MoveNext())
                {
                    DictionaryEntry entry = enumerator.Entry;
                    Type type2 = entry.Key as Type;
                    if ((!(type2 != null) || !type.IsAssignableFrom(type2)) && !(type2 == typeof(object)))
                    {
                        continue;
                    }
                    TypeDescriptionNode typeDescriptionNode = (TypeDescriptionNode)entry.Value;
                    while (typeDescriptionNode != null && !(typeDescriptionNode.Provider is ReflectTypeDescriptionProvider))
                    {
                        flag = true;
                        typeDescriptionNode = typeDescriptionNode.Next;
                    }
                    if (typeDescriptionNode != null)
                    {
                        ReflectTypeDescriptionProvider reflectTypeDescriptionProvider = (ReflectTypeDescriptionProvider)typeDescriptionNode.Provider;
                        if (reflectTypeDescriptionProvider.IsPopulated(type))
{
                            flag = true;
                            reflectTypeDescriptionProvider.Refresh(type);
                        }
                    }
                }
            }
        }
        IDictionary cache = GetCache(component);
        if (!flag && cache == null)
        {
            return;
        }
        if (cache != null)
        {
            for (int i = 0; i < s_pipelineFilterKeys.Length; i++)
            {
                cache.Remove(s_pipelineFilterKeys[i]);
                cache.Remove(s_pipelineMergeKeys[i]);
                cache.Remove(s_pipelineAttributeFilterKeys[i]);
            }
        }
        Interlocked.Increment(ref s_metadataVersion);
        RaiseRefresh(component);
    }
References System.Collections.IDictionaryEnumerator.Entry, System.ComponentModel.TypeDescriptor.GetCache(), System.Threading.Interlocked.Increment(), System.ComponentModel.ReflectTypeDescriptionProvider.IsPopulated(), System.Collections.IEnumerator.MoveNext(), System.ComponentModel.TypeDescriptor.TypeDescriptionNode.Next, System.ComponentModel.TypeDescriptor.TypeDescriptionNode.Provider, System.ComponentModel.TypeDescriptor.RaiseRefresh(), System.ComponentModel.ReflectTypeDescriptionProvider.Refresh(), System.Collections.IDictionary.Remove(), System.ComponentModel.TypeDescriptor.s_metadataVersion, System.ComponentModel.TypeDescriptor.s_pipelineAttributeFilterKeys, System.ComponentModel.TypeDescriptor.s_pipelineFilterKeys, System.ComponentModel.TypeDescriptor.s_pipelineMergeKeys, System.ComponentModel.TypeDescriptor.s_providerTable, System.Reflection.Type, System.type, and System.Collections.DictionaryEntry.Value.