Terraria: System.ComponentModel.TypeDescriptor.PipelineInitialize
PipelineInitialize()
static ICollection System.ComponentModel.TypeDescriptor.PipelineInitialize (int pipelineType, ICollection members, IDictionary cache) inline static private
Definition at line 2250 of file TypeDescriptor.cs.
    {
        if (cache != null)
        {
            bool flag = true;
            if (cache[s_pipelineInitializeKeys[pipelineType]] is ICollection collection && collection.Count == members.Count)
            {
                IEnumerator enumerator = collection.GetEnumerator();
                IEnumerator enumerator2 = members.GetEnumerator();
                while (enumerator.MoveNext() && enumerator2.MoveNext())
                {
                    if (enumerator.Current != enumerator2.Current)
                    {
                        flag = false;
                        break;
                    }
                }
            }
            if (!flag)
            {
                cache.Remove(s_pipelineMergeKeys[pipelineType]);
                cache.Remove(s_pipelineFilterKeys[pipelineType]);
                cache.Remove(s_pipelineAttributeFilterKeys[pipelineType]);
                cache[s_pipelineInitializeKeys[pipelineType]] = members;
            }
        }
        return members;
    }
References System.collection, System.Collections.ICollection.Count, System.Collections.IEnumerator.Current, System.Collections.IEnumerable.GetEnumerator(), System.Collections.IEnumerator.MoveNext(), System.Collections.IDictionary.Remove(), System.ComponentModel.TypeDescriptor.s_pipelineAttributeFilterKeys, System.ComponentModel.TypeDescriptor.s_pipelineFilterKeys, System.ComponentModel.TypeDescriptor.s_pipelineInitializeKeys, and System.ComponentModel.TypeDescriptor.s_pipelineMergeKeys.
Referenced by System.ComponentModel.TypeDescriptor.GetAttributes(), System.ComponentModel.TypeDescriptor.GetEvents(), and System.ComponentModel.TypeDescriptor.GetPropertiesImpl().