Terraria: System.Text.StringBuilder.ChunkEnumerator.MoveNext
MoveNext()
bool System.Text.StringBuilder.ChunkEnumerator.MoveNext () inline
Definition at line 70 of file StringBuilder.cs.
        {
            if (_currentChunk == _firstChunk)
            {
                return false;
            }
            if (_manyChunks != null)
            {
                return _manyChunks.MoveNext(ref _currentChunk);
            }
            StringBuilder stringBuilder = _firstChunk;
            while (stringBuilder.m_ChunkPrevious != _currentChunk)
            {
                stringBuilder = stringBuilder.m_ChunkPrevious;
            }
            _currentChunk = stringBuilder;
            return true;
        }
References System.Text.StringBuilder.ChunkEnumerator._currentChunk, System.Text.StringBuilder.ChunkEnumerator._firstChunk, System.Text.StringBuilder.ChunkEnumerator._manyChunks, System.Runtime.Serialization.Dictionary, and System.Text.StringBuilder.ChunkEnumerator.ManyChunkInfo.MoveNext().
Referenced by System.Numerics.BigNumber.HexNumberToBigInteger(), System.Numerics.BigNumber.NumberToBigInteger(), System.IO.TextWriter.Write(), System.IO.TextWriter.WriteAsync(), System.IO.StreamWriter.WriteFormatHelper(), and System.IO.TextWriter.WriteLineAsync().