Terraria: System.ParseNumbers.StringToInt
StringToInt() [2/2]
static int System.ParseNumbers.StringToInt (ReadOnlySpan< char > s, int radix, int flags, ref int currPos) inline static
Definition at line 85 of file ParseNumbers.cs.
    {
        int i = currPos;
        int num = ((-1 == radix) ? 10 : radix);
        if (num != 2 && num != 10 && num != 8 && num != 16)
        {
            throw new ArgumentException(SR.Arg_InvalidBase, "radix");
        }
        int length = s.Length;
        if (i < 0 || i >= length)
        {
            throw new ArgumentOutOfRangeException(SR.ArgumentOutOfRange_Index);
        }
        if ((flags & 0x1000) == 0 && (flags & 0x2000) == 0)
        {
            EatWhiteSpace(s, ref i);
            if (i == length)
            {
                throw new FormatException(SR.Format_EmptyInputString);
            }
        }
        int num2 = 1;
        if (s[i] == '-')
        {
            if (num != 10)
            {
                throw new ArgumentException(SR.Arg_CannotHaveNegativeValue);
            }
            if (((uint)flags & 0x200u) != 0)
            {
                throw new OverflowException(SR.Overflow_NegativeUnsigned);
            }
            num2 = -1;
            i++;
        }
        else if (s[i] == '+')
        {
            i++;
        }
        if ((radix == -1 || radix == 16) && i + 1 < length && s[i] == '0' && (s[i + 1] == 'x' || s[i + 1] == 'X'))
        {
            num = 16;
            i += 2;
        }
        int num3 = i;
        int num4 = GrabInts(num, s, ref i, (flags & 0x200) != 0);
        if (i == num3)
        {
            throw new FormatException(SR.Format_NoParsibleDigits);
        }
        if (((uint)flags & 0x1000u) != 0 && i < length)
        {
            throw new FormatException(SR.Format_ExtraJunkAtEnd);
        }
        currPos = i;
        if (((uint)flags & 0x400u) != 0)
        {
            if ((uint)num4 > 255u)
            {
                Number.ThrowOverflowException(TypeCode.SByte);
            }
        }
        else if (((uint)flags & 0x800u) != 0)
        {
            if ((uint)num4 > 65535u)
            {
                Number.ThrowOverflowException(TypeCode.Int16);
            }
        }
        else if (num4 == int.MinValue && num2 == 1 && num == 10 && (flags & 0x200) == 0)
        {
            Number.ThrowOverflowException(TypeCode.Int32);
        }
        if (num == 10)
        {
            num4 *= num2;
        }
        return num4;
    }
References System.SR.Arg_CannotHaveNegativeValue, System.SR.Arg_InvalidBase, System.SR.ArgumentOutOfRange_Index, System.ParseNumbers.EatWhiteSpace(), System.SR.Format_EmptyInputString, System.SR.Format_ExtraJunkAtEnd, System.SR.Format_NoParsibleDigits, System.ParseNumbers.GrabInts(), System.length, System.SR.Overflow_NegativeUnsigned, System.s, and System.Number.ThrowOverflowException().