Terraria: System.ParseNumbers.GrabLongs
GrabLongs()
static long System.ParseNumbers.GrabLongs (int radix, ReadOnlySpan< char > s, ref int i, bool isUnsigned) inline static private
Definition at line 396 of file ParseNumbers.cs.
    {
        ulong num = 0uL;
        if (radix == 10 && !isUnsigned)
        {
            ulong num2 = 922337203685477580uL;
            int result;
            while (i < s.Length && IsDigit(s[i], radix, out result))
            {
                if (num > num2 || (long)num < 0L)
                {
                    Number.ThrowOverflowException(TypeCode.Int64);
                }
                num = (ulong)((long)num * (long)radix + result);
                i++;
            }
            if ((long)num < 0L && num != 9223372036854775808uL)
            {
                Number.ThrowOverflowException(TypeCode.Int64);
            }
        }
        else
        {
            ulong num2 = radix switch
            {
                8 => 2305843009213693951uL,
                16 => 1152921504606846975uL,
                10 => 1844674407370955161uL,
                _ => 9223372036854775807uL,
            };
            int result2;
            while (i < s.Length && IsDigit(s[i], radix, out result2))
            {
                if (num > num2)
                {
                    Number.ThrowOverflowException(TypeCode.UInt64);
                }
                ulong num3 = (ulong)((long)num * (long)radix + result2);
                if (num3 < num)
                {
                    Number.ThrowOverflowException(TypeCode.UInt64);
                }
                num = num3;
                i++;
            }
        }
        return (long)num;
    }
References System.ParseNumbers.IsDigit(), System.L, System.s, and System.Number.ThrowOverflowException().
Referenced by System.ParseNumbers.StringToLong().