Terraria: System.ParseNumbers.GrabInts
GrabInts()
static int System.ParseNumbers.GrabInts (int radix, ReadOnlySpan< char > s, ref int i, bool isUnsigned) inline static private
Definition at line 445 of file ParseNumbers.cs.
    {
        uint num = 0u;
        if (radix == 10 && !isUnsigned)
        {
            uint num2 = 214748364u;
            int result;
            while (i < s.Length && IsDigit(s[i], radix, out result))
            {
                if (num > num2 || (int)num < 0)
                {
                    Number.ThrowOverflowException(TypeCode.Int32);
                }
                num = (uint)((int)num * radix + result);
                i++;
            }
            if ((int)num < 0 && num != 2147483648u)
            {
                Number.ThrowOverflowException(TypeCode.Int32);
            }
        }
        else
        {
            uint num2 = radix switch
            {
                8 => 536870911u,
                16 => 268435455u,
                10 => 429496729u,
                _ => 2147483647u,
            };
            int result2;
            while (i < s.Length && IsDigit(s[i], radix, out result2))
            {
                if (num > num2)
                {
                    Number.ThrowOverflowException(TypeCode.UInt32);
                }
                uint num3 = (uint)((int)num * radix + result2);
                if (num3 < num)
                {
                    Number.ThrowOverflowException(TypeCode.UInt32);
                }
                num = num3;
                i++;
            }
        }
        return (int)num;
    }
References System.ParseNumbers.IsDigit(), System.s, and System.Number.ThrowOverflowException().
Referenced by System.ParseNumbers.StringToInt().