Terraria: PlayerEyeHelper.SetStateByPlayerInfo
SetStateByPlayerInfo()
void PlayerEyeHelper.SetStateByPlayerInfo (Player player) inline private
     {
         if (player.blackout || player.blind)
         {
             SwitchToState(EyeState.IsBlind);
         }
         else
         {
             if (_state == EyeState.JustTookDamage && _timeInState < 20)
             {
                 return;
             }
             if (player.sleeping.isSleeping)
             {
                 bool resetStateTimerEvenIfAlreadyInState = player.itemAnimation > 0;
                 SwitchToState(EyeState.InBed, resetStateTimerEvenIfAlreadyInState);
                 return;
             }
             if (DoesPlayerCountAsModeratelyDamaged(player))
             {
                 SwitchToState(EyeState.IsModeratelyDamaged);
                 return;
             }
             if (player.tipsy)
             {
                 SwitchToState(EyeState.IsTipsy);
                 return;
             }
             if (player.poisoned || player.venom || player.starving)
             {
                 SwitchToState(EyeState.IsPoisoned);
                 return;
             }
             bool flag = player.ZoneSandstorm || (player.ZoneSnow && Main.IsItRaining);
             if (player.behindBackWall)
             {
                 flag = false;
             }
             if (flag)
             {
                 SwitchToState(EyeState.InStorm);
             }
             else
             {
                 SwitchToState(EyeState.NormalBlinking);
             }
         }
     }
References _state, _timeInState, Player.behindBackWall, Player.blackout, Player.blind, DoesPlayerCountAsModeratelyDamaged(), Main.IsItRaining, PlayerSleepingHelper.isSleeping, Player.itemAnimation, Player.poisoned, Player.sleeping, Player.starving, SwitchToState(), Player.tipsy, Player.venom, Player.ZoneSandstorm, and Player.ZoneSnow.
Referenced by Update().