Terraria: System.Net.CookieTokenizer.Next
Next() [2/2]
CookieToken System.Net.CookieTokenizer.Next (bool first, bool parseResponseCookies) inline package
Definition at line 232 of file CookieTokenizer.cs.
    {
        Reset();
        if (first)
        {
            _cookieStartIndex = _index;
            _cookieLength = 0;
        }
        CookieToken cookieToken = FindNext(ignoreComma: false, ignoreEquals: false);
        if (cookieToken == CookieToken.EndCookie)
        {
            EndOfCookie = true;
        }
        if (cookieToken == CookieToken.End || cookieToken == CookieToken.EndCookie)
        {
            string text2 = (Name = Extract());
            if (text2.Length != 0)
            {
                Token = TokenFromName(parseResponseCookies);
                return CookieToken.Attribute;
            }
            return cookieToken;
        }
        Name = Extract();
        if (first)
        {
            Token = CookieToken.CookieName;
        }
        else
        {
            Token = TokenFromName(parseResponseCookies);
        }
        if (cookieToken == CookieToken.Equals)
        {
            cookieToken = FindNext(!first && Token == CookieToken.Expires, ignoreEquals: true);
            if (cookieToken == CookieToken.EndCookie)
            {
                EndOfCookie = true;
            }
            Value = Extract();
            return CookieToken.NameValuePair;
        }
        return CookieToken.Attribute;
    }
References System.Net.CookieTokenizer._cookieLength, System.Net.CookieTokenizer._cookieStartIndex, System.Net.CookieTokenizer._index, System.Net.CookieTokenizer.EndOfCookie, System.Net.CookieTokenizer.Extract(), System.Net.CookieTokenizer.FindNext(), System.Net.CookieTokenizer.Name, System.Net.CookieTokenizer.Reset(), System.Net.CookieTokenizer.TokenFromName(), and System.Net.CookieTokenizer.Value.