Terraria: System.Xml.Schema.SchemaCollectionCompiler.Cleanup
Cleanup() [2/2]
static void System.Xml.Schema.SchemaCollectionCompiler.Cleanup (XmlSchema schema) inline static package
Definition at line 85 of file SchemaCollectionCompiler.cs.
    {
        for (int i = 0; i < schema.Includes.Count; i++)
        {
            XmlSchemaExternal xmlSchemaExternal = (XmlSchemaExternal)schema.Includes[i];
            if (xmlSchemaExternal.Schema != null)
            {
                Cleanup(xmlSchemaExternal.Schema);
            }
            if (!(xmlSchemaExternal is XmlSchemaRedefine xmlSchemaRedefine))
            {
                continue;
            }
            xmlSchemaRedefine.AttributeGroups.Clear();
            xmlSchemaRedefine.Groups.Clear();
            xmlSchemaRedefine.SchemaTypes.Clear();
            for (int j = 0; j < xmlSchemaRedefine.Items.Count; j++)
            {
                object obj = xmlSchemaRedefine.Items[j];
                if (obj is XmlSchemaAttribute attribute)
                {
                    CleanupAttribute(attribute);
                }
                else if (obj is XmlSchemaAttributeGroup attributeGroup)
                {
                    CleanupAttributeGroup(attributeGroup);
                }
                else if (obj is XmlSchemaComplexType complexType)
                {
                    CleanupComplexType(complexType);
                }
                else if (obj is XmlSchemaSimpleType simpleType)
                {
                    CleanupSimpleType(simpleType);
                }
                else if (obj is XmlSchemaElement element)
                {
                    CleanupElement(element);
                }
                else if (obj is XmlSchemaGroup group)
                {
                    CleanupGroup(group);
                }
            }
        }
        for (int k = 0; k < schema.Items.Count; k++)
        {
            object obj2 = schema.Items[k];
            if (obj2 is XmlSchemaAttribute attribute2)
            {
                CleanupAttribute(attribute2);
            }
            else if (schema.Items[k] is XmlSchemaAttributeGroup attributeGroup2)
            {
                CleanupAttributeGroup(attributeGroup2);
            }
            else if (schema.Items[k] is XmlSchemaComplexType complexType2)
            {
                CleanupComplexType(complexType2);
            }
            else if (schema.Items[k] is XmlSchemaSimpleType simpleType2)
            {
                CleanupSimpleType(simpleType2);
            }
            else if (schema.Items[k] is XmlSchemaElement element2)
            {
                CleanupElement(element2);
            }
            else if (schema.Items[k] is XmlSchemaGroup group2)
            {
                CleanupGroup(group2);
            }
        }
        schema.Attributes.Clear();
        schema.AttributeGroups.Clear();
        schema.SchemaTypes.Clear();
        schema.Elements.Clear();
        schema.Groups.Clear();
        schema.Notations.Clear();
        schema.Ids.Clear();
        schema.IdentityConstraints.Clear();
    }
References System.Xml.Schema.SchemaCollectionCompiler.Cleanup(), System.Xml.Schema.SchemaCollectionCompiler.CleanupAttribute(), System.Xml.Schema.SchemaCollectionCompiler.CleanupAttributeGroup(), System.Xml.Schema.SchemaCollectionCompiler.CleanupComplexType(), System.Xml.Schema.SchemaCollectionCompiler.CleanupElement(), System.Xml.Schema.SchemaCollectionCompiler.CleanupGroup(), System.Xml.Schema.SchemaCollectionCompiler.CleanupSimpleType(), System.Collections.Generic.Dictionary< TKey, TValue >.Clear(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Xml.Dictionary, and System.obj.