Terraria: System.Xml.Schema.SchemaCollectionCompiler.IsElementFromGroupBase
IsElementFromGroupBase()
bool System.Xml.Schema.SchemaCollectionCompiler.IsElementFromGroupBase (XmlSchemaElement derivedElement, XmlSchemaGroupBase baseGroupBase, bool skipEmptableOnly) inline private
Definition at line 1329 of file SchemaCollectionCompiler.cs.
    {
        bool flag = false;
        for (int i = 0; i < baseGroupBase.Items.Count; i++)
        {
            XmlSchemaParticle xmlSchemaParticle = (XmlSchemaParticle)baseGroupBase.Items[i];
            if (!flag)
            {
                string minOccursString = xmlSchemaParticle.MinOccursString;
                string maxOccursString = xmlSchemaParticle.MaxOccursString;
                xmlSchemaParticle.MinOccurs *= baseGroupBase.MinOccurs;
                if (xmlSchemaParticle.MaxOccurs != decimal.MaxValue)
                {
                    if (baseGroupBase.MaxOccurs == decimal.MaxValue)
                    {
                        xmlSchemaParticle.MaxOccurs = decimal.MaxValue;
                    }
                    else
                    {
                        xmlSchemaParticle.MaxOccurs *= baseGroupBase.MaxOccurs;
                    }
                }
                flag = IsValidRestriction(derivedElement, xmlSchemaParticle);
                xmlSchemaParticle.MinOccursString = minOccursString;
                xmlSchemaParticle.MaxOccursString = maxOccursString;
            }
            else if (skipEmptableOnly && !IsParticleEmptiable(xmlSchemaParticle))
            {
                return false;
            }
        }
        return flag;
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Xml.Dictionary, System.Xml.Schema.SchemaCollectionCompiler.IsParticleEmptiable(), and System.Xml.Schema.SchemaCollectionCompiler.IsValidRestriction().
Referenced by System.Xml.Schema.SchemaCollectionCompiler.IsValidRestriction().