Terraria: System.Xml.Schema.SchemaCollectionCompiler.CompileBaseMemberTypes
CompileBaseMemberTypes()
XmlSchemaSimpleType[] System.Xml.Schema.SchemaCollectionCompiler.CompileBaseMemberTypes (XmlSchemaSimpleType simpleType) inline private
Definition at line 580 of file SchemaCollectionCompiler.cs.
    {
        List<XmlSchemaSimpleType> list = new List<XmlSchemaSimpleType>();
        XmlSchemaSimpleTypeUnion xmlSchemaSimpleTypeUnion = (XmlSchemaSimpleTypeUnion)simpleType.Content;
        XmlQualifiedName[] memberTypes = xmlSchemaSimpleTypeUnion.MemberTypes;
        if (memberTypes != null)
        {
            for (int i = 0; i < memberTypes.Length; i++)
            {
                XmlSchemaSimpleType simpleType2 = GetSimpleType(memberTypes[i]);
                if (simpleType2 != null)
                {
                    if (simpleType2.Datatype.Variety == XmlSchemaDatatypeVariety.Union)
                    {
                        CheckUnionType(simpleType2, list, simpleType);
                    }
                    else
                    {
                        list.Add(simpleType2);
                    }
                    if ((simpleType2.FinalResolved & XmlSchemaDerivationMethod.Union) != 0)
                    {
                        SendValidationEvent(System.SR.Sch_BaseFinalUnion, simpleType);
                    }
                    continue;
                }
                throw new XmlSchemaException(System.SR.Sch_UndeclaredSimpleType, memberTypes[i].ToString(), simpleType);
            }
        }
        XmlSchemaObjectCollection baseTypes = xmlSchemaSimpleTypeUnion.BaseTypes;
        if (baseTypes != null)
        {
            for (int j = 0; j < baseTypes.Count; j++)
            {
                XmlSchemaSimpleType xmlSchemaSimpleType = (XmlSchemaSimpleType)baseTypes[j];
                CompileSimpleType(xmlSchemaSimpleType);
                if (xmlSchemaSimpleType.Datatype.Variety == XmlSchemaDatatypeVariety.Union)
                {
                    CheckUnionType(xmlSchemaSimpleType, list, simpleType);
                }
                else
                {
                    list.Add(xmlSchemaSimpleType);
                }
            }
        }
        xmlSchemaSimpleTypeUnion.SetBaseMemberTypes(list.ToArray());
        return xmlSchemaSimpleTypeUnion.BaseMemberTypes;
    }
References System.Xml.Schema.SchemaCollectionCompiler.CheckUnionType(), System.Xml.Schema.SchemaCollectionCompiler.CompileSimpleType(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Xml.Dictionary, System.Xml.Schema.SchemaCollectionCompiler.GetSimpleType(), System.list, System.SR.Sch_BaseFinalUnion, System.SR.Sch_UndeclaredSimpleType, and System.Xml.Schema.BaseProcessor.SendValidationEvent().
Referenced by System.Xml.Schema.SchemaCollectionCompiler.CompileSimpleType().