Terraria: System.Xml.Schema.SchemaCollectionCompiler.CompileSimpleContentExtension
CompileSimpleContentExtension()
void System.Xml.Schema.SchemaCollectionCompiler.CompileSimpleContentExtension (XmlSchemaComplexType complexType, XmlSchemaSimpleContentExtension simpleExtension) inline private
Definition at line 735 of file SchemaCollectionCompiler.cs.
    {
        XmlSchemaComplexType xmlSchemaComplexType = null;
        if (complexType.Redefined != null && simpleExtension.BaseTypeName == complexType.Redefined.QualifiedName)
        {
            xmlSchemaComplexType = (XmlSchemaComplexType)complexType.Redefined;
            CompileComplexType(xmlSchemaComplexType);
            complexType.SetBaseSchemaType(xmlSchemaComplexType);
            complexType.SetDatatype(xmlSchemaComplexType.Datatype);
        }
        else
        {
            XmlSchemaType anySchemaType = GetAnySchemaType(simpleExtension.BaseTypeName);
            if (anySchemaType == null)
            {
                SendValidationEvent(System.SR.Sch_UndeclaredType, simpleExtension.BaseTypeName.ToString(), complexType);
            }
            else
            {
                complexType.SetBaseSchemaType(anySchemaType);
                complexType.SetDatatype(anySchemaType.Datatype);
            }
            xmlSchemaComplexType = anySchemaType as XmlSchemaComplexType;
        }
        if (xmlSchemaComplexType != null)
        {
            if ((xmlSchemaComplexType.FinalResolved & XmlSchemaDerivationMethod.Extension) != 0)
            {
                SendValidationEvent(System.SR.Sch_BaseFinalExtension, complexType);
            }
            if (xmlSchemaComplexType.ContentType != 0)
            {
                SendValidationEvent(System.SR.Sch_NotSimpleContent, complexType);
            }
        }
        complexType.SetDerivedBy(XmlSchemaDerivationMethod.Extension);
        CompileLocalAttributes(xmlSchemaComplexType, complexType, simpleExtension.Attributes, simpleExtension.AnyAttribute, XmlSchemaDerivationMethod.Extension);
    }
References System.Xml.Schema.SchemaCollectionCompiler.CompileComplexType(), System.Xml.Schema.SchemaCollectionCompiler.CompileLocalAttributes(), System.Xml.Schema.SchemaCollectionCompiler.GetAnySchemaType(), System.SR.Sch_BaseFinalExtension, System.SR.Sch_NotSimpleContent, System.SR.Sch_UndeclaredType, and System.Xml.Schema.BaseProcessor.SendValidationEvent().
Referenced by System.Xml.Schema.SchemaCollectionCompiler.CompileComplexType().