Terraria: System.Xml.Schema.SchemaCollectionCompiler.GetComplexType
GetComplexType()
XmlSchemaComplexType System.Xml.Schema.SchemaCollectionCompiler.GetComplexType (XmlQualifiedName name) inline private
Definition at line 2380 of file SchemaCollectionCompiler.cs.
    {
        XmlSchemaComplexType xmlSchemaComplexType = _schema.SchemaTypes[name] as XmlSchemaComplexType;
        if (xmlSchemaComplexType != null)
        {
            CompileComplexType(xmlSchemaComplexType);
        }
        return xmlSchemaComplexType;
    }
References System.Xml.Schema.SchemaCollectionCompiler._schema, System.Xml.Schema.SchemaCollectionCompiler.CompileComplexType(), System.Xml.Dictionary, and System.Xml.Schema.XmlSchema.SchemaTypes.
Referenced by System.Xml.Schema.SchemaCollectionCompiler.CompileComplexContentExtension(), System.Xml.Schema.SchemaCollectionCompiler.CompileComplexContentRestriction(), and System.Xml.Schema.SchemaCollectionCompiler.CompileSimpleContentRestriction().