Terraria: System.Xml.Schema.SchemaCollectionCompiler.CompileAttribute
CompileAttribute()
void System.Xml.Schema.SchemaCollectionCompiler.CompileAttribute (XmlSchemaAttribute xa) inline private
Definition at line 1814 of file SchemaCollectionCompiler.cs.
    {
        if (xa.IsProcessing)
        {
            SendValidationEvent(System.SR.Sch_AttributeCircularRef, xa);
        }
        else
        {
            if (xa.AttDef != null)
            {
                return;
            }
            xa.IsProcessing = true;
            SchemaAttDef schemaAttDef = null;
            try
            {
                if (!xa.RefName.IsEmpty)
                {
                    XmlSchemaAttribute xmlSchemaAttribute = (XmlSchemaAttribute)_schema.Attributes[xa.RefName];
                    if (xmlSchemaAttribute == null)
                    {
                        throw new XmlSchemaException(System.SR.Sch_UndeclaredAttribute, xa.RefName.ToString(), xa);
                    }
                    CompileAttribute(xmlSchemaAttribute);
                    if (xmlSchemaAttribute.AttDef == null)
                    {
                        throw new XmlSchemaException(System.SR.Sch_RefInvalidAttribute, xa.RefName.ToString(), xa);
                    }
                    schemaAttDef = xmlSchemaAttribute.AttDef.Clone();
                    if (schemaAttDef.Datatype != null)
                    {
                        if (xmlSchemaAttribute.FixedValue != null)
{
                            if (xa.DefaultValue != null)
{
                                throw new XmlSchemaException(System.SR.Sch_FixedDefaultInRef, xa.RefName.ToString(), xa);
                            }
                            if (xa.FixedValue != null)
{
                                if (xa.FixedValue != xmlSchemaAttribute.FixedValue)
{
                                    throw new XmlSchemaException(System.SR.Sch_FixedInRef, xa.RefName.ToString(), xa);
                                }
                            }
                            else
{
                                schemaAttDef.Presence = SchemaDeclBase.Use.Fixed;
                                SchemaAttDef schemaAttDef2 = schemaAttDef;
                                string defaultValueRaw = (schemaAttDef.DefaultValueExpanded = xmlSchemaAttribute.FixedValue);
                                schemaAttDef2.DefaultValueRaw = defaultValueRaw;
                                schemaAttDef.DefaultValueTyped = schemaAttDef.Datatype.ParseValue(schemaAttDef.DefaultValueRaw, base.NameTable, new SchemaNamespaceManager(xa), createAtomicValue: true);
                            }
                        }
                        else if (xmlSchemaAttribute.DefaultValue != null && xa.DefaultValue == null && xa.FixedValue == null)
{
                            schemaAttDef.Presence = SchemaDeclBase.Use.Default;
                            SchemaAttDef schemaAttDef3 = schemaAttDef;
                            string defaultValueRaw = (schemaAttDef.DefaultValueExpanded = xmlSchemaAttribute.DefaultValue);
                            schemaAttDef3.DefaultValueRaw = defaultValueRaw;
                            schemaAttDef.DefaultValueTyped = schemaAttDef.Datatype.ParseValue(schemaAttDef.DefaultValueRaw, base.NameTable, new SchemaNamespaceManager(xa), createAtomicValue: true);
                        }
                    }
                    xa.SetAttributeType(xmlSchemaAttribute.AttributeSchemaType);
                }
                else
                {
                    schemaAttDef = new SchemaAttDef(xa.QualifiedName);
                    if (xa.SchemaType != null)
                    {
                        CompileSimpleType(xa.SchemaType);
                        xa.SetAttributeType(xa.SchemaType);
                        schemaAttDef.SchemaType = xa.SchemaType;
                        schemaAttDef.Datatype = xa.SchemaType.Datatype;
                    }
                    else if (!xa.SchemaTypeName.IsEmpty)
                    {
                        XmlSchemaSimpleType simpleType = GetSimpleType(xa.SchemaTypeName);
                        if (simpleType == null)
{
                            throw new XmlSchemaException(System.SR.Sch_UndeclaredSimpleType, xa.SchemaTypeName.ToString(), xa);
                        }
                        xa.SetAttributeType(simpleType);
                        schemaAttDef.Datatype = simpleType.Datatype;
                        schemaAttDef.SchemaType = simpleType;
                    }
                    else
                    {
                        schemaAttDef.SchemaType = DatatypeImplementation.AnySimpleType;
                        schemaAttDef.Datatype = DatatypeImplementation.AnySimpleType.Datatype;
                        xa.SetAttributeType(DatatypeImplementation.AnySimpleType);
                    }
                }
                if (schemaAttDef.Datatype != null)
                {
                    schemaAttDef.Datatype.VerifySchemaValid(_schema.Notations, xa);
                }
                if (xa.DefaultValue != null || xa.FixedValue != null)
                {
                    if (xa.DefaultValue != null)
                    {
                        schemaAttDef.Presence = SchemaDeclBase.Use.Default;
                        SchemaAttDef schemaAttDef4 = schemaAttDef;
                        string defaultValueRaw = (schemaAttDef.DefaultValueExpanded = xa.DefaultValue);
                        schemaAttDef4.DefaultValueRaw = defaultValueRaw;
                    }
                    else
                    {
                        schemaAttDef.Presence = SchemaDeclBase.Use.Fixed;
                        SchemaAttDef schemaAttDef5 = schemaAttDef;
                        string defaultValueRaw = (schemaAttDef.DefaultValueExpanded = xa.FixedValue);
                        schemaAttDef5.DefaultValueRaw = defaultValueRaw;
                    }
                    if (schemaAttDef.Datatype != null)
                    {
                        schemaAttDef.DefaultValueTyped = schemaAttDef.Datatype.ParseValue(schemaAttDef.DefaultValueRaw, base.NameTable, new SchemaNamespaceManager(xa), createAtomicValue: true);
                    }
                }
                else
                {
                    switch (xa.Use)
                    {
                    case XmlSchemaUse.None:
                    case XmlSchemaUse.Optional:
                        schemaAttDef.Presence = SchemaDeclBase.Use.Implied;
                        break;
                    case XmlSchemaUse.Required:
                        schemaAttDef.Presence = SchemaDeclBase.Use.Required;
                        break;
                    }
                }
                schemaAttDef.SchemaAttribute = xa;
                xa.AttDef = schemaAttDef;
            }
            catch (XmlSchemaException ex)
            {
                if (ex.SourceSchemaObject == null)
                {
                    ex.SetSource(xa);
                }
                SendValidationEvent(ex);
                xa.AttDef = SchemaAttDef.Empty;
            }
            finally
            {
                xa.IsProcessing = false;
            }
        }
    }
References System.Xml.Schema.SchemaCollectionCompiler._schema, System.Xml.Schema.DatatypeImplementation.AnySimpleType, System.Xml.Schema.XmlSchema.Attributes, System.Xml.Schema.SchemaCollectionCompiler.CompileAttribute(), System.Xml.Schema.SchemaCollectionCompiler.CompileSimpleType(), System.Xml.Dictionary, System.Xml.Schema.SchemaAttDef.Empty, System.Xml.Schema.SchemaCollectionCompiler.GetSimpleType(), System.Xml.Schema.XmlSchema.Notations, System.SR.Sch_AttributeCircularRef, System.SR.Sch_FixedDefaultInRef, System.SR.Sch_FixedInRef, System.SR.Sch_RefInvalidAttribute, System.SR.Sch_UndeclaredAttribute, System.SR.Sch_UndeclaredSimpleType, and System.Xml.Schema.BaseProcessor.SendValidationEvent().
Referenced by System.Xml.Schema.SchemaCollectionCompiler.Compile(), System.Xml.Schema.SchemaCollectionCompiler.CompileAttribute(), System.Xml.Schema.SchemaCollectionCompiler.CompileAttributeGroup(), and System.Xml.Schema.SchemaCollectionCompiler.CompileLocalAttributes().