Terraria: System.Xml.Schema.SchemaCollectionCompiler.CheckSubstitutionGroup
CheckSubstitutionGroup()
void System.Xml.Schema.SchemaCollectionCompiler.CheckSubstitutionGroup (XmlSchemaSubstitutionGroup substitutionGroup) inline private
Definition at line 441 of file SchemaCollectionCompiler.cs.
    {
        XmlSchemaElement xmlSchemaElement = (XmlSchemaElement)_schema.Elements[substitutionGroup.Examplar];
        if (xmlSchemaElement == null)
        {
            return;
        }
        for (int i = 0; i < substitutionGroup.Members.Count; i++)
        {
            XmlSchemaElement xmlSchemaElement2 = (XmlSchemaElement)substitutionGroup.Members[i];
            if (xmlSchemaElement2 != xmlSchemaElement && !XmlSchemaType.IsDerivedFrom(xmlSchemaElement2.ElementSchemaType, xmlSchemaElement.ElementSchemaType, xmlSchemaElement.FinalResolved))
            {
                SendValidationEvent(System.SR.Sch_InvalidSubstitutionMember, xmlSchemaElement2.QualifiedName.ToString(), xmlSchemaElement.QualifiedName.ToString(), xmlSchemaElement2);
            }
        }
    }
References System.Xml.Schema.SchemaCollectionCompiler._schema, System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Xml.Schema.XmlSchema.Elements, System.Xml.Schema.XmlSchemaType.IsDerivedFrom(), System.SR.Sch_InvalidSubstitutionMember, and System.Xml.Schema.BaseProcessor.SendValidationEvent().
Referenced by System.Xml.Schema.SchemaCollectionCompiler.Compile().