Terraria: System.Xml.Schema.SchemaCollectionCompiler.CannonicalizeChoice
CannonicalizeChoice()
XmlSchemaParticle System.Xml.Schema.SchemaCollectionCompiler.CannonicalizeChoice (XmlSchemaChoice choice, bool root, bool substitution) inline private
Definition at line 1118 of file SchemaCollectionCompiler.cs.
    {
        XmlSchemaChoice source = choice;
        if (choice.Items.Count > 0)
        {
            XmlSchemaChoice xmlSchemaChoice = new XmlSchemaChoice();
            xmlSchemaChoice.MinOccurs = choice.MinOccurs;
            xmlSchemaChoice.MaxOccurs = choice.MaxOccurs;
            for (int i = 0; i < choice.Items.Count; i++)
            {
                XmlSchemaParticle xmlSchemaParticle = CannonicalizeParticle((XmlSchemaParticle)choice.Items[i], root: false, substitution);
                if (xmlSchemaParticle == XmlSchemaParticle.Empty)
                {
                    continue;
                }
                if (xmlSchemaParticle.MinOccurs == 1m && xmlSchemaParticle.MaxOccurs == 1m && xmlSchemaParticle is XmlSchemaChoice)
                {
                    XmlSchemaChoice xmlSchemaChoice2 = (XmlSchemaChoice)xmlSchemaParticle;
                    for (int j = 0; j < xmlSchemaChoice2.Items.Count; j++)
                    {
                        xmlSchemaChoice.Items.Add(xmlSchemaChoice2.Items[j]);
                    }
                }
                else
                {
                    xmlSchemaChoice.Items.Add(xmlSchemaParticle);
                }
            }
            choice = xmlSchemaChoice;
        }
        if (!root && choice.Items.Count == 0)
        {
            if (choice.MinOccurs != 0m)
            {
                SendValidationEvent(System.SR.Sch_EmptyChoice, source, XmlSeverityType.Warning);
            }
            return XmlSchemaParticle.Empty;
        }
        if (!root && choice.Items.Count == 1 && choice.MinOccurs == 1m && choice.MaxOccurs == 1m)
        {
            return (XmlSchemaParticle)choice.Items[0];
        }
        return choice;
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Xml.Schema.SchemaCollectionCompiler.CannonicalizeParticle(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Xml.Dictionary, System.Xml.Schema.XmlSchemaParticle.Empty, System.SR.Sch_EmptyChoice, System.Xml.Schema.BaseProcessor.SendValidationEvent(), and System.source.
Referenced by System.Xml.Schema.SchemaCollectionCompiler.CannonicalizeParticle().