Terraria: System.Xml.Schema.SchemaCollectionCompiler.CleanupComplexType
CleanupComplexType()
static void System.Xml.Schema.SchemaCollectionCompiler.CleanupComplexType (XmlSchemaComplexType complexType) inline static private
Definition at line 290 of file SchemaCollectionCompiler.cs.
    {
        if (complexType.ContentModel != null)
        {
            if (complexType.ContentModel is XmlSchemaSimpleContent)
            {
                XmlSchemaSimpleContent xmlSchemaSimpleContent = (XmlSchemaSimpleContent)complexType.ContentModel;
                if (xmlSchemaSimpleContent.Content is XmlSchemaSimpleContentExtension)
                {
                    XmlSchemaSimpleContentExtension xmlSchemaSimpleContentExtension = (XmlSchemaSimpleContentExtension)xmlSchemaSimpleContent.Content;
                    CleanupAttributes(xmlSchemaSimpleContentExtension.Attributes);
                }
                else
                {
                    XmlSchemaSimpleContentRestriction xmlSchemaSimpleContentRestriction = (XmlSchemaSimpleContentRestriction)xmlSchemaSimpleContent.Content;
                    CleanupAttributes(xmlSchemaSimpleContentRestriction.Attributes);
                }
            }
            else
            {
                XmlSchemaComplexContent xmlSchemaComplexContent = (XmlSchemaComplexContent)complexType.ContentModel;
                if (xmlSchemaComplexContent.Content is XmlSchemaComplexContentExtension)
                {
                    XmlSchemaComplexContentExtension xmlSchemaComplexContentExtension = (XmlSchemaComplexContentExtension)xmlSchemaComplexContent.Content;
                    CleanupParticle(xmlSchemaComplexContentExtension.Particle);
                    CleanupAttributes(xmlSchemaComplexContentExtension.Attributes);
                }
                else
                {
                    XmlSchemaComplexContentRestriction xmlSchemaComplexContentRestriction = (XmlSchemaComplexContentRestriction)xmlSchemaComplexContent.Content;
                    CleanupParticle(xmlSchemaComplexContentRestriction.Particle);
                    CleanupAttributes(xmlSchemaComplexContentRestriction.Attributes);
                }
            }
        }
        else
        {
            CleanupParticle(complexType.Particle);
            CleanupAttributes(complexType.Attributes);
        }
        complexType.LocalElements.Clear();
        complexType.AttributeUses.Clear();
        complexType.SetAttributeWildcard(null);
        complexType.SetContentTypeParticle(XmlSchemaParticle.Empty);
        complexType.ElementDecl = null;
    }
References System.Xml.Schema.SchemaCollectionCompiler.CleanupAttributes(), System.Xml.Schema.SchemaCollectionCompiler.CleanupParticle(), System.Collections.Generic.Dictionary< TKey, TValue >.Clear(), System.Xml.Dictionary, and System.Xml.Schema.XmlSchemaParticle.Empty.
Referenced by System.Xml.Schema.SchemaCollectionCompiler.Cleanup(), System.Xml.Schema.SchemaCollectionCompiler.Cleanup(), and System.Xml.Schema.SchemaCollectionCompiler.CleanupElement().