Terraria: System.Xml.Schema.SchemaCollectionCompiler.CompileLocalAttributes
CompileLocalAttributes()
void System.Xml.Schema.SchemaCollectionCompiler.CompileLocalAttributes (XmlSchemaComplexType baseType, XmlSchemaComplexType derivedType, XmlSchemaObjectCollection attributes, XmlSchemaAnyAttribute anyAttribute, XmlSchemaDerivationMethod derivedBy) inline private
Definition at line 1657 of file SchemaCollectionCompiler.cs.
    {
        XmlSchemaAnyAttribute xmlSchemaAnyAttribute = baseType?.AttributeWildcard;
        for (int i = 0; i < attributes.Count; i++)
        {
            if (attributes[i] is XmlSchemaAttribute xmlSchemaAttribute)
            {
                if (xmlSchemaAttribute.Use != XmlSchemaUse.Prohibited)
                {
                    CompileAttribute(xmlSchemaAttribute);
                }
                if (xmlSchemaAttribute.Use != XmlSchemaUse.Prohibited || (xmlSchemaAttribute.Use == XmlSchemaUse.Prohibited && derivedBy == XmlSchemaDerivationMethod.Restriction && baseType != XmlSchemaComplexType.AnyType))
                {
                    if (derivedType.AttributeUses[xmlSchemaAttribute.QualifiedName] == null)
                    {
                        derivedType.AttributeUses.Add(xmlSchemaAttribute.QualifiedName, xmlSchemaAttribute);
                    }
                    else
                    {
                        SendValidationEvent(System.SR.Sch_DupAttributeUse, xmlSchemaAttribute.QualifiedName.ToString(), xmlSchemaAttribute);
                    }
                }
                else
                {
                    SendValidationEvent(System.SR.Sch_AttributeIgnored, xmlSchemaAttribute.QualifiedName.ToString(), xmlSchemaAttribute, XmlSeverityType.Warning);
                }
                continue;
            }
            XmlSchemaAttributeGroupRef xmlSchemaAttributeGroupRef = (XmlSchemaAttributeGroupRef)attributes[i];
            XmlSchemaAttributeGroup xmlSchemaAttributeGroup = (XmlSchemaAttributeGroup)_schema.AttributeGroups[xmlSchemaAttributeGroupRef.RefName];
            if (xmlSchemaAttributeGroup != null)
            {
                CompileAttributeGroup(xmlSchemaAttributeGroup);
                foreach (XmlSchemaAttribute value in xmlSchemaAttributeGroup.AttributeUses.Values)
                {
                    if (value.Use != XmlSchemaUse.Prohibited || (value.Use == XmlSchemaUse.Prohibited && derivedBy == XmlSchemaDerivationMethod.Restriction && baseType != XmlSchemaComplexType.AnyType))
                    {
                        if (derivedType.AttributeUses[value.QualifiedName] == null)
{
                            derivedType.AttributeUses.Add(value.QualifiedName, value);
                        }
                        else
{
                            SendValidationEvent(System.SR.Sch_DupAttributeUse, value.QualifiedName.ToString(), xmlSchemaAttributeGroupRef);
                        }
                    }
                    else
                    {
                        SendValidationEvent(System.SR.Sch_AttributeIgnored, value.QualifiedName.ToString(), value, XmlSeverityType.Warning);
                    }
                }
                anyAttribute = CompileAnyAttributeIntersection(anyAttribute, xmlSchemaAttributeGroup.AttributeWildcard);
            }
            else
            {
                SendValidationEvent(System.SR.Sch_UndefAttributeGroupRef, xmlSchemaAttributeGroupRef.RefName.ToString(), xmlSchemaAttributeGroupRef);
            }
        }
        if (baseType != null)
        {
            if (derivedBy == XmlSchemaDerivationMethod.Extension)
            {
                derivedType.SetAttributeWildcard(CompileAnyAttributeUnion(anyAttribute, xmlSchemaAnyAttribute));
                {
                    foreach (XmlSchemaAttribute value2 in baseType.AttributeUses.Values)
                    {
                        XmlSchemaAttribute xmlSchemaAttribute4 = (XmlSchemaAttribute)derivedType.AttributeUses[value2.QualifiedName];
                        if (xmlSchemaAttribute4 != null)
{
                            if (xmlSchemaAttribute4.AttributeSchemaType != value2.AttributeSchemaType || value2.Use == XmlSchemaUse.Prohibited)
{
                                SendValidationEvent(System.SR.Sch_InvalidAttributeExtension, xmlSchemaAttribute4);
                            }
                        }
                        else
{
                            derivedType.AttributeUses.Add(value2.QualifiedName, value2);
                        }
                    }
                    return;
                }
            }
            if (anyAttribute != null && (xmlSchemaAnyAttribute == null || !XmlSchemaAnyAttribute.IsSubset(anyAttribute, xmlSchemaAnyAttribute)))
            {
                SendValidationEvent(System.SR.Sch_InvalidAnyAttributeRestriction, derivedType);
            }
            else
            {
                derivedType.SetAttributeWildcard(anyAttribute);
            }
            foreach (XmlSchemaAttribute value3 in baseType.AttributeUses.Values)
            {
                XmlSchemaAttribute xmlSchemaAttribute6 = (XmlSchemaAttribute)derivedType.AttributeUses[value3.QualifiedName];
                if (xmlSchemaAttribute6 == null)
                {
                    derivedType.AttributeUses.Add(value3.QualifiedName, value3);
                }
                else if (value3.Use == XmlSchemaUse.Prohibited && xmlSchemaAttribute6.Use != XmlSchemaUse.Prohibited)
                {
                    SendValidationEvent(System.SR.Sch_AttributeRestrictionProhibited, xmlSchemaAttribute6);
                }
                else if (xmlSchemaAttribute6.Use != XmlSchemaUse.Prohibited && (value3.AttributeSchemaType == null || xmlSchemaAttribute6.AttributeSchemaType == null || !XmlSchemaType.IsDerivedFrom(xmlSchemaAttribute6.AttributeSchemaType, value3.AttributeSchemaType, XmlSchemaDerivationMethod.Empty)))
                {
                    SendValidationEvent(System.SR.Sch_AttributeRestrictionInvalid, xmlSchemaAttribute6);
                }
            }
            {
                foreach (XmlSchemaAttribute value4 in derivedType.AttributeUses.Values)
                {
                    XmlSchemaAttribute xmlSchemaAttribute8 = (XmlSchemaAttribute)baseType.AttributeUses[value4.QualifiedName];
                    if (xmlSchemaAttribute8 == null && (xmlSchemaAnyAttribute == null || !xmlSchemaAnyAttribute.Allows(value4.QualifiedName)))
                    {
                        SendValidationEvent(System.SR.Sch_AttributeRestrictionInvalidFromWildcard, value4);
                    }
                }
                return;
            }
        }
        derivedType.SetAttributeWildcard(anyAttribute);
    }
References System.Xml.Schema.SchemaCollectionCompiler._schema, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Xml.Schema.XmlSchemaComplexType.AnyType, System.Xml.Schema.XmlSchema.AttributeGroups, System.Xml.Schema.SchemaCollectionCompiler.CompileAnyAttributeIntersection(), System.Xml.Schema.SchemaCollectionCompiler.CompileAnyAttributeUnion(), System.Xml.Schema.SchemaCollectionCompiler.CompileAttribute(), System.Xml.Schema.SchemaCollectionCompiler.CompileAttributeGroup(), System.Collections.CollectionBase.Count, System.Xml.Schema.XmlSchemaType.IsDerivedFrom(), System.Xml.Schema.XmlSchemaAnyAttribute.IsSubset(), System.SR.Sch_AttributeIgnored, System.SR.Sch_AttributeRestrictionInvalid, System.SR.Sch_AttributeRestrictionInvalidFromWildcard, System.SR.Sch_AttributeRestrictionProhibited, System.SR.Sch_DupAttributeUse, System.SR.Sch_InvalidAnyAttributeRestriction, System.SR.Sch_InvalidAttributeExtension, System.SR.Sch_UndefAttributeGroupRef, System.Xml.Schema.BaseProcessor.SendValidationEvent(), System.value, and System.Collections.Generic.Dictionary< TKey, TValue >.Values.
Referenced by System.Xml.Schema.SchemaCollectionCompiler.CompileComplexContentExtension(), System.Xml.Schema.SchemaCollectionCompiler.CompileComplexContentRestriction(), System.Xml.Schema.SchemaCollectionCompiler.CompileComplexType(), System.Xml.Schema.SchemaCollectionCompiler.CompileSimpleContentExtension(), and System.Xml.Schema.SchemaCollectionCompiler.CompileSimpleContentRestriction().