Terraria: System.Xml.Schema.SchemaCollectionCompiler.CompileIdentityConstraint
CompileIdentityConstraint()
void System.Xml.Schema.SchemaCollectionCompiler.CompileIdentityConstraint (XmlSchemaIdentityConstraint xi) inline private
Definition at line 1963 of file SchemaCollectionCompiler.cs.
    {
        if (xi.IsProcessing)
        {
            xi.CompiledConstraint = CompiledIdentityConstraint.Empty;
            SendValidationEvent(System.SR.Sch_IdentityConstraintCircularRef, xi);
        }
        else
        {
            if (xi.CompiledConstraint != null)
            {
                return;
            }
            xi.IsProcessing = true;
            CompiledIdentityConstraint compiledIdentityConstraint = null;
            try
            {
                SchemaNamespaceManager nsmgr = new SchemaNamespaceManager(xi);
                compiledIdentityConstraint = new CompiledIdentityConstraint(xi, nsmgr);
                if (xi is XmlSchemaKeyref)
                {
                    XmlSchemaIdentityConstraint xmlSchemaIdentityConstraint = (XmlSchemaIdentityConstraint)_schema.IdentityConstraints[((XmlSchemaKeyref)xi).Refer];
                    if (xmlSchemaIdentityConstraint == null)
                    {
                        throw new XmlSchemaException(System.SR.Sch_UndeclaredIdentityConstraint, ((XmlSchemaKeyref)xi).Refer.ToString(), xi);
                    }
                    CompileIdentityConstraint(xmlSchemaIdentityConstraint);
                    if (xmlSchemaIdentityConstraint.CompiledConstraint == null)
                    {
                        throw new XmlSchemaException(System.SR.Sch_RefInvalidIdentityConstraint, ((XmlSchemaKeyref)xi).Refer.ToString(), xi);
                    }
                    if (xmlSchemaIdentityConstraint.Fields.Count != xi.Fields.Count)
                    {
                        throw new XmlSchemaException(System.SR.Sch_RefInvalidCardin, xi.QualifiedName.ToString(), xi);
                    }
                    if (xmlSchemaIdentityConstraint.CompiledConstraint.Role == CompiledIdentityConstraint.ConstraintRole.Keyref)
                    {
                        throw new XmlSchemaException(System.SR.Sch_ReftoKeyref, xi.QualifiedName.ToString(), xi);
                    }
                }
                xi.CompiledConstraint = compiledIdentityConstraint;
            }
            catch (XmlSchemaException ex)
            {
                if (ex.SourceSchemaObject == null)
                {
                    ex.SetSource(xi);
                }
                SendValidationEvent(ex);
                xi.CompiledConstraint = CompiledIdentityConstraint.Empty;
            }
            finally
            {
                xi.IsProcessing = false;
            }
        }
    }
References System.Xml.Schema.SchemaCollectionCompiler._schema, System.Xml.Schema.SchemaCollectionCompiler.CompileIdentityConstraint(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Xml.Dictionary, System.Xml.Schema.CompiledIdentityConstraint.Empty, System.Xml.Schema.XmlSchema.IdentityConstraints, System.SR.Sch_IdentityConstraintCircularRef, System.SR.Sch_RefInvalidCardin, System.SR.Sch_RefInvalidIdentityConstraint, System.SR.Sch_ReftoKeyref, System.SR.Sch_UndeclaredIdentityConstraint, and System.Xml.Schema.BaseProcessor.SendValidationEvent().
Referenced by System.Xml.Schema.SchemaCollectionCompiler.Compile(), System.Xml.Schema.SchemaCollectionCompiler.CompileElement(), and System.Xml.Schema.SchemaCollectionCompiler.CompileIdentityConstraint().