Terraria: System.Xml.Schema.SchemaCollectionCompiler.CompileParticleElements
CompileParticleElements()
void System.Xml.Schema.SchemaCollectionCompiler.CompileParticleElements (XmlSchemaComplexType complexType, XmlSchemaParticle particle) inline private
Definition at line 2313 of file SchemaCollectionCompiler.cs.
    {
        if (particle is XmlSchemaElement)
        {
            XmlSchemaElement xmlSchemaElement = (XmlSchemaElement)particle;
            CompileElement(xmlSchemaElement);
            if (complexType.LocalElements[xmlSchemaElement.QualifiedName] == null)
            {
                complexType.LocalElements.Add(xmlSchemaElement.QualifiedName, xmlSchemaElement);
                return;
            }
            XmlSchemaElement xmlSchemaElement2 = (XmlSchemaElement)complexType.LocalElements[xmlSchemaElement.QualifiedName];
            if (xmlSchemaElement2.ElementSchemaType != xmlSchemaElement.ElementSchemaType)
            {
                SendValidationEvent(System.SR.Sch_ElementTypeCollision, particle);
            }
        }
        else if (particle is XmlSchemaGroupBase)
        {
            XmlSchemaObjectCollection items = ((XmlSchemaGroupBase)particle).Items;
            for (int i = 0; i < items.Count; i++)
            {
                CompileParticleElements(complexType, (XmlSchemaParticle)items[i]);
            }
        }
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Xml.Schema.SchemaCollectionCompiler.CompileElement(), System.Xml.Schema.SchemaCollectionCompiler.CompileParticleElements(), System.Collections.CollectionBase.Count, System.SR.Sch_ElementTypeCollision, and System.Xml.Schema.BaseProcessor.SendValidationEvent().
Referenced by System.Xml.Schema.SchemaCollectionCompiler.CompileCompexTypeElements(), and System.Xml.Schema.SchemaCollectionCompiler.CompileParticleElements().