Terraria: System.Xml.Schema.SchemaCollectionCompiler.GetSchemaContentType
GetSchemaContentType()
XmlSchemaContentType System.Xml.Schema.SchemaCollectionCompiler.GetSchemaContentType (XmlSchemaComplexType complexType, XmlSchemaComplexContent complexContent, XmlSchemaParticle particle) inline private
Definition at line 1584 of file SchemaCollectionCompiler.cs.
    {
        if ((complexContent != null && complexContent.IsMixed) || (complexContent == null && complexType.IsMixed))
        {
            return XmlSchemaContentType.Mixed;
        }
        if (particle != null && !particle.IsEmpty)
        {
            return XmlSchemaContentType.ElementOnly;
        }
        return XmlSchemaContentType.Empty;
    }
References System.Xml.Schema.XmlSchemaParticle.IsEmpty.
Referenced by System.Xml.Schema.SchemaCollectionCompiler.CompileComplexContentExtension(), System.Xml.Schema.SchemaCollectionCompiler.CompileComplexContentRestriction(), and System.Xml.Schema.SchemaCollectionCompiler.CompileComplexType().