Terraria: System.Xml.Schema.SchemaCollectionCompiler.BuildParticleContentModel
BuildParticleContentModel()
void System.Xml.Schema.SchemaCollectionCompiler.BuildParticleContentModel (ParticleContentValidator contentValidator, XmlSchemaParticle particle) inline private
Definition at line 2255 of file SchemaCollectionCompiler.cs.
    {
        if (particle is XmlSchemaElement)
        {
            XmlSchemaElement xmlSchemaElement = (XmlSchemaElement)particle;
            contentValidator.AddName(xmlSchemaElement.QualifiedName, xmlSchemaElement);
        }
        else if (particle is XmlSchemaAny)
        {
            XmlSchemaAny xmlSchemaAny = (XmlSchemaAny)particle;
            contentValidator.AddNamespaceList(xmlSchemaAny.NamespaceList, xmlSchemaAny);
        }
        else if (particle is XmlSchemaGroupBase)
        {
            XmlSchemaObjectCollection items = ((XmlSchemaGroupBase)particle).Items;
            bool flag = particle is XmlSchemaChoice;
            contentValidator.OpenGroup();
            bool flag2 = true;
            for (int i = 0; i < items.Count; i++)
            {
                XmlSchemaParticle particle2 = (XmlSchemaParticle)items[i];
                if (flag2)
                {
                    flag2 = false;
                }
                else if (flag)
                {
                    contentValidator.AddChoice();
                }
                else
                {
                    contentValidator.AddSequence();
                }
                BuildParticleContentModel(contentValidator, particle2);
            }
            contentValidator.CloseGroup();
        }
        if (!(particle.MinOccurs == 1m) || !(particle.MaxOccurs == 1m))
        {
            if (particle.MinOccurs == 0m && particle.MaxOccurs == 1m)
            {
                contentValidator.AddQMark();
            }
            else if (particle.MinOccurs == 0m && particle.MaxOccurs == decimal.MaxValue)
            {
                contentValidator.AddStar();
            }
            else if (particle.MinOccurs == 1m && particle.MaxOccurs == decimal.MaxValue)
            {
                contentValidator.AddPlus();
            }
            else
            {
                contentValidator.AddLeafRange(particle.MinOccurs, particle.MaxOccurs);
            }
        }
    }
References System.Xml.Schema.SchemaCollectionCompiler.BuildParticleContentModel(), System.Collections.CollectionBase.Count, System.Xml.Schema.XmlSchemaParticle.MaxOccurs, and System.Xml.Schema.XmlSchemaParticle.MinOccurs.
Referenced by System.Xml.Schema.SchemaCollectionCompiler.BuildParticleContentModel(), and System.Xml.Schema.SchemaCollectionCompiler.CompileComplexContent().