Terraria: System.Xml.Schema.SchemaCollectionCompiler.GetSimpleType
GetSimpleType()
XmlSchemaSimpleType System.Xml.Schema.SchemaCollectionCompiler.GetSimpleType (XmlQualifiedName name) inline private
Definition at line 2355 of file SchemaCollectionCompiler.cs.
    {
        XmlSchemaSimpleType xmlSchemaSimpleType = _schema.SchemaTypes[name] as XmlSchemaSimpleType;
        if (xmlSchemaSimpleType != null)
        {
            CompileSimpleType(xmlSchemaSimpleType);
        }
        else
        {
            xmlSchemaSimpleType = DatatypeImplementation.GetSimpleTypeFromXsdType(name);
            if (xmlSchemaSimpleType != null)
            {
                if (xmlSchemaSimpleType.TypeCode == XmlTypeCode.NormalizedString)
                {
                    xmlSchemaSimpleType = DatatypeImplementation.GetNormalizedStringTypeV1Compat();
                }
                else if (xmlSchemaSimpleType.TypeCode == XmlTypeCode.Token)
                {
                    xmlSchemaSimpleType = DatatypeImplementation.GetTokenTypeV1Compat();
                }
            }
        }
        return xmlSchemaSimpleType;
    }
References System.Xml.Schema.SchemaCollectionCompiler._schema, System.Xml.Schema.SchemaCollectionCompiler.CompileSimpleType(), System.Xml.Dictionary, System.Xml.Schema.DatatypeImplementation.GetNormalizedStringTypeV1Compat(), System.Xml.Schema.DatatypeImplementation.GetSimpleTypeFromXsdType(), System.Xml.Schema.DatatypeImplementation.GetTokenTypeV1Compat(), and System.Xml.Schema.XmlSchema.SchemaTypes.
Referenced by System.Xml.Schema.SchemaCollectionCompiler.CompileAttribute(), System.Xml.Schema.SchemaCollectionCompiler.CompileBaseMemberTypes(), and System.Xml.Schema.SchemaCollectionCompiler.CompileSimpleType().