Terraria: System.Xml.Schema.SchemaCollectionCompiler.IsGroupBaseFromAny
IsGroupBaseFromAny()
bool System.Xml.Schema.SchemaCollectionCompiler.IsGroupBaseFromAny (XmlSchemaGroupBase derivedGroupBase, XmlSchemaAny baseAny) inline private
Definition at line 1308 of file SchemaCollectionCompiler.cs.
    {
        CalculateEffectiveTotalRange(derivedGroupBase, out var minOccurs, out var maxOccurs);
        if (!IsValidOccurrenceRangeRestriction(minOccurs, maxOccurs, baseAny.MinOccurs, baseAny.MaxOccurs))
        {
            return false;
        }
        string minOccursString = baseAny.MinOccursString;
        baseAny.MinOccurs = 0m;
        for (int i = 0; i < derivedGroupBase.Items.Count; i++)
        {
            if (!IsValidRestriction((XmlSchemaParticle)derivedGroupBase.Items[i], baseAny))
            {
                baseAny.MinOccursString = minOccursString;
                return false;
            }
        }
        baseAny.MinOccursString = minOccursString;
        return true;
    }
References System.Xml.Schema.SchemaCollectionCompiler.CalculateEffectiveTotalRange(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Xml.Dictionary, System.Xml.Schema.SchemaCollectionCompiler.IsValidOccurrenceRangeRestriction(), and System.Xml.Schema.SchemaCollectionCompiler.IsValidRestriction().
Referenced by System.Xml.Schema.SchemaCollectionCompiler.IsValidRestriction().