Terraria: System.Xml.Schema.SchemaCollectionCompiler.CannonicalizeGroupRef
CannonicalizeGroupRef()
XmlSchemaParticle System.Xml.Schema.SchemaCollectionCompiler.CannonicalizeGroupRef (XmlSchemaGroupRef groupRef, bool root, bool substitution) inline private
Definition at line 1025 of file SchemaCollectionCompiler.cs.
    {
        XmlSchemaGroup xmlSchemaGroup = ((groupRef.Redefined == null) ? ((XmlSchemaGroup)_schema.Groups[groupRef.RefName]) : groupRef.Redefined);
        if (xmlSchemaGroup == null)
        {
            SendValidationEvent(System.SR.Sch_UndefGroupRef, groupRef.RefName.ToString(), groupRef);
            return XmlSchemaParticle.Empty;
        }
        if (xmlSchemaGroup.CanonicalParticle == null)
        {
            CompileGroup(xmlSchemaGroup);
        }
        if (xmlSchemaGroup.CanonicalParticle == XmlSchemaParticle.Empty)
        {
            return XmlSchemaParticle.Empty;
        }
        XmlSchemaGroupBase xmlSchemaGroupBase = (XmlSchemaGroupBase)xmlSchemaGroup.CanonicalParticle;
        if (xmlSchemaGroupBase is XmlSchemaAll)
        {
            if (!root)
            {
                SendValidationEvent(System.SR.Sch_AllRefNotRoot, "", groupRef);
                return XmlSchemaParticle.Empty;
            }
            if (groupRef.MinOccurs != 1m || groupRef.MaxOccurs != 1m)
            {
                SendValidationEvent(System.SR.Sch_AllRefMinMax, groupRef);
                return XmlSchemaParticle.Empty;
            }
        }
        else if (xmlSchemaGroupBase is XmlSchemaChoice && xmlSchemaGroupBase.Items.Count == 0)
        {
            if (groupRef.MinOccurs != 0m)
            {
                SendValidationEvent(System.SR.Sch_EmptyChoice, groupRef, XmlSeverityType.Warning);
            }
            return XmlSchemaParticle.Empty;
        }
        XmlSchemaGroupBase xmlSchemaGroupBase2 = ((xmlSchemaGroupBase is XmlSchemaSequence) ? new XmlSchemaSequence() : ((xmlSchemaGroupBase is XmlSchemaChoice) ? ((XmlSchemaGroupBase)new XmlSchemaChoice()) : ((XmlSchemaGroupBase)new XmlSchemaAll())));
        xmlSchemaGroupBase2.MinOccurs = groupRef.MinOccurs;
        xmlSchemaGroupBase2.MaxOccurs = groupRef.MaxOccurs;
        for (int i = 0; i < xmlSchemaGroupBase.Items.Count; i++)
        {
            xmlSchemaGroupBase2.Items.Add((XmlSchemaParticle)xmlSchemaGroupBase.Items[i]);
        }
        groupRef.SetParticle(xmlSchemaGroupBase2);
        return xmlSchemaGroupBase2;
    }
References System.Xml.Schema.SchemaCollectionCompiler._schema, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Xml.Schema.SchemaCollectionCompiler.CompileGroup(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Xml.Dictionary, System.Xml.Schema.XmlSchemaParticle.Empty, System.Xml.Schema.XmlSchema.Groups, System.SR.Sch_AllRefMinMax, System.SR.Sch_AllRefNotRoot, System.SR.Sch_EmptyChoice, System.SR.Sch_UndefGroupRef, and System.Xml.Schema.BaseProcessor.SendValidationEvent().
Referenced by System.Xml.Schema.SchemaCollectionCompiler.CannonicalizeParticle().