Terraria: System.Xml.Schema.SchemaCollectionCompiler.CannonicalizeParticle
CannonicalizeParticle()
XmlSchemaParticle System.Xml.Schema.SchemaCollectionCompiler.CannonicalizeParticle (XmlSchemaParticle particle, bool root, bool substitution) inline private
Definition at line 979 of file SchemaCollectionCompiler.cs.
    {
        if (particle == null || particle.IsEmpty)
        {
            return XmlSchemaParticle.Empty;
        }
        if (particle is XmlSchemaElement)
        {
            return CannonicalizeElement((XmlSchemaElement)particle, substitution);
        }
        if (particle is XmlSchemaGroupRef)
        {
            return CannonicalizeGroupRef((XmlSchemaGroupRef)particle, root, substitution);
        }
        if (particle is XmlSchemaAll)
        {
            return CannonicalizeAll((XmlSchemaAll)particle, root, substitution);
        }
        if (particle is XmlSchemaChoice)
        {
            return CannonicalizeChoice((XmlSchemaChoice)particle, root, substitution);
        }
        if (particle is XmlSchemaSequence)
        {
            return CannonicalizeSequence((XmlSchemaSequence)particle, root, substitution);
        }
        return particle;
    }
References System.Xml.Schema.SchemaCollectionCompiler.CannonicalizeAll(), System.Xml.Schema.SchemaCollectionCompiler.CannonicalizeChoice(), System.Xml.Schema.SchemaCollectionCompiler.CannonicalizeElement(), System.Xml.Schema.SchemaCollectionCompiler.CannonicalizeGroupRef(), System.Xml.Schema.SchemaCollectionCompiler.CannonicalizeSequence(), System.Xml.Schema.XmlSchemaParticle.Empty, and System.Xml.Schema.XmlSchemaParticle.IsEmpty.
Referenced by System.Xml.Schema.SchemaCollectionCompiler.CannonicalizeAll(), System.Xml.Schema.SchemaCollectionCompiler.CannonicalizeChoice(), System.Xml.Schema.SchemaCollectionCompiler.CannonicalizeSequence(), System.Xml.Schema.SchemaCollectionCompiler.CompileComplexContentExtension(), System.Xml.Schema.SchemaCollectionCompiler.CompileContentTypeParticle(), and System.Xml.Schema.SchemaCollectionCompiler.CompileGroup().