Terraria: System.Xml.Schema.SchemaCollectionCompiler.CompileAnyAttributeIntersection
CompileAnyAttributeIntersection()
XmlSchemaAnyAttribute System.Xml.Schema.SchemaCollectionCompiler.CompileAnyAttributeIntersection (XmlSchemaAnyAttribute a, XmlSchemaAnyAttribute b) inline private
Definition at line 1796 of file SchemaCollectionCompiler.cs.
    {
        if (a == null)
        {
            return b;
        }
        if (b == null)
        {
            return a;
        }
        XmlSchemaAnyAttribute xmlSchemaAnyAttribute = XmlSchemaAnyAttribute.Intersection(a, b, v1Compat: true);
        if (xmlSchemaAnyAttribute == null)
        {
            SendValidationEvent(System.SR.Sch_UnexpressibleAnyAttribute, a);
        }
        return xmlSchemaAnyAttribute;
    }
References System.Xml.Dictionary, System.Xml.Schema.XmlSchemaAnyAttribute.Intersection(), System.SR.Sch_UnexpressibleAnyAttribute, and System.Xml.Schema.BaseProcessor.SendValidationEvent().
Referenced by System.Xml.Schema.SchemaCollectionCompiler.CompileAttributeGroup(), and System.Xml.Schema.SchemaCollectionCompiler.CompileLocalAttributes().