Terraria: System.Xml.Schema.SchemaCollectionCompiler.CompileSubstitutionGroup
CompileSubstitutionGroup()
void System.Xml.Schema.SchemaCollectionCompiler.CompileSubstitutionGroup (XmlSchemaSubstitutionGroupV1Compat substitutionGroup) inline private
Definition at line 395 of file SchemaCollectionCompiler.cs.
    {
        if (substitutionGroup.IsProcessing && substitutionGroup.Members.Count > 0)
        {
            SendValidationEvent(System.SR.Sch_SubstitutionCircularRef, (XmlSchemaElement)substitutionGroup.Members[0]);
            return;
        }
        XmlSchemaElement xmlSchemaElement = (XmlSchemaElement)_schema.Elements[substitutionGroup.Examplar];
        if (substitutionGroup.Members.Contains(xmlSchemaElement))
        {
            return;
        }
        substitutionGroup.IsProcessing = true;
        if (xmlSchemaElement != null)
        {
            if (xmlSchemaElement.FinalResolved == XmlSchemaDerivationMethod.All)
            {
                SendValidationEvent(System.SR.Sch_InvalidExamplar, xmlSchemaElement.Name, xmlSchemaElement);
            }
            for (int i = 0; i < substitutionGroup.Members.Count; i++)
            {
                XmlSchemaElement xmlSchemaElement2 = (XmlSchemaElement)substitutionGroup.Members[i];
                XmlSchemaSubstitutionGroupV1Compat xmlSchemaSubstitutionGroupV1Compat = (XmlSchemaSubstitutionGroupV1Compat)_examplars[xmlSchemaElement2.QualifiedName];
                if (xmlSchemaSubstitutionGroupV1Compat != null)
                {
                    CompileSubstitutionGroup(xmlSchemaSubstitutionGroupV1Compat);
                    for (int j = 0; j < xmlSchemaSubstitutionGroupV1Compat.Choice.Items.Count; j++)
                    {
                        substitutionGroup.Choice.Items.Add(xmlSchemaSubstitutionGroupV1Compat.Choice.Items[j]);
                    }
                }
                else
                {
                    substitutionGroup.Choice.Items.Add(xmlSchemaElement2);
                }
            }
            substitutionGroup.Choice.Items.Add(xmlSchemaElement);
            substitutionGroup.Members.Add(xmlSchemaElement);
        }
        else if (substitutionGroup.Members.Count > 0)
        {
            SendValidationEvent(System.SR.Sch_NoExamplar, (XmlSchemaElement)substitutionGroup.Members[0]);
        }
        substitutionGroup.IsProcessing = false;
    }
References System.Xml.Schema.SchemaCollectionCompiler._examplars, System.Xml.Schema.SchemaCollectionCompiler._schema, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Xml.Schema.SchemaCollectionCompiler.CompileSubstitutionGroup(), System.Collections.Generic.Dictionary< TKey, TValue >.Contains(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Xml.Dictionary, System.Xml.Schema.XmlSchema.Elements, System.SR.Sch_InvalidExamplar, System.SR.Sch_NoExamplar, System.SR.Sch_SubstitutionCircularRef, and System.Xml.Schema.BaseProcessor.SendValidationEvent().
Referenced by System.Xml.Schema.SchemaCollectionCompiler.Compile(), and System.Xml.Schema.SchemaCollectionCompiler.CompileSubstitutionGroup().