Terraria: System.Xml.Schema.SchemaCollectionCompiler.Compile
Compile()
void System.Xml.Schema.SchemaCollectionCompiler.Compile () inline private
Definition at line 168 of file SchemaCollectionCompiler.cs.
    {
        _schema.SchemaTypes.Insert(DatatypeImplementation.QnAnyType, XmlSchemaComplexType.AnyType);
        foreach (XmlSchemaSubstitutionGroupV1Compat value in _examplars.Values)
        {
            CompileSubstitutionGroup(value);
        }
        foreach (XmlSchemaGroup value2 in _schema.Groups.Values)
        {
            CompileGroup(value2);
        }
        foreach (XmlSchemaAttributeGroup value3 in _schema.AttributeGroups.Values)
        {
            CompileAttributeGroup(value3);
        }
        foreach (XmlSchemaType value4 in _schema.SchemaTypes.Values)
        {
            if (value4 is XmlSchemaComplexType)
            {
                CompileComplexType((XmlSchemaComplexType)value4);
            }
            else
            {
                CompileSimpleType((XmlSchemaSimpleType)value4);
            }
        }
        foreach (XmlSchemaElement value5 in _schema.Elements.Values)
        {
            if (value5.ElementDecl == null)
            {
                CompileElement(value5);
            }
        }
        foreach (XmlSchemaAttribute value6 in _schema.Attributes.Values)
        {
            if (value6.AttDef == null)
            {
                CompileAttribute(value6);
            }
        }
        foreach (XmlSchemaIdentityConstraint value7 in _schema.IdentityConstraints.Values)
        {
            if (value7.CompiledConstraint == null)
            {
                CompileIdentityConstraint(value7);
            }
        }
        while (_complexTypeStack.Count > 0)
        {
            XmlSchemaComplexType complexType = _complexTypeStack.Pop();
            CompileCompexTypeElements(complexType);
        }
        foreach (XmlSchemaType value8 in _schema.SchemaTypes.Values)
        {
            if (value8 is XmlSchemaComplexType)
            {
                CheckParticleDerivation((XmlSchemaComplexType)value8);
            }
        }
        foreach (XmlSchemaElement value9 in _schema.Elements.Values)
        {
            if (value9.ElementSchemaType is XmlSchemaComplexType && value9.SchemaTypeName == XmlQualifiedName.Empty)
            {
                CheckParticleDerivation((XmlSchemaComplexType)value9.ElementSchemaType);
            }
        }
        foreach (XmlSchemaSubstitutionGroup value10 in _examplars.Values)
        {
            CheckSubstitutionGroup(value10);
        }
        _schema.SchemaTypes.Remove(DatatypeImplementation.QnAnyType);
    }
References System.Xml.Schema.SchemaCollectionCompiler._complexTypeStack, System.Xml.Schema.SchemaCollectionCompiler._examplars, System.Xml.Schema.SchemaCollectionCompiler._schema, System.Xml.Schema.XmlSchemaComplexType.AnyType, System.Xml.Schema.XmlSchema.AttributeGroups, System.Xml.Schema.XmlSchema.Attributes, System.Xml.Schema.SchemaCollectionCompiler.CheckParticleDerivation(), System.Xml.Schema.SchemaCollectionCompiler.CheckSubstitutionGroup(), System.Xml.Schema.SchemaCollectionCompiler.CompileAttribute(), System.Xml.Schema.SchemaCollectionCompiler.CompileAttributeGroup(), System.Xml.Schema.SchemaCollectionCompiler.CompileCompexTypeElements(), System.Xml.Schema.SchemaCollectionCompiler.CompileComplexType(), System.Xml.Schema.SchemaCollectionCompiler.CompileElement(), System.Xml.Schema.SchemaCollectionCompiler.CompileGroup(), System.Xml.Schema.SchemaCollectionCompiler.CompileIdentityConstraint(), System.Xml.Schema.SchemaCollectionCompiler.CompileSimpleType(), System.Xml.Schema.SchemaCollectionCompiler.CompileSubstitutionGroup(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Xml.Schema.XmlSchema.Elements, System.Xml.XmlQualifiedName.Empty, System.Xml.Schema.XmlSchema.Groups, System.Xml.Schema.XmlSchema.IdentityConstraints, System.Xml.Schema.XmlSchemaObjectTable.Insert(), System.Xml.Schema.DatatypeImplementation.QnAnyType, System.Xml.Schema.XmlSchemaObjectTable.Remove(), System.Xml.Schema.XmlSchema.SchemaTypes, System.value, and System.Xml.Schema.XmlSchemaObjectTable.Values.
Referenced by System.Xml.Schema.SchemaCollectionCompiler.Execute().