Terraria: System.Xml.Schema.SchemaCollectionCompiler.IsValidRestriction
IsValidRestriction()
bool System.Xml.Schema.SchemaCollectionCompiler.IsValidRestriction (XmlSchemaParticle derivedParticle, XmlSchemaParticle baseParticle) inline private
Definition at line 1203 of file SchemaCollectionCompiler.cs.
    {
        if (derivedParticle == baseParticle)
        {
            return true;
        }
        if (derivedParticle == null || derivedParticle == XmlSchemaParticle.Empty)
        {
            return IsParticleEmptiable(baseParticle);
        }
        if (baseParticle == null || baseParticle == XmlSchemaParticle.Empty)
        {
            return false;
        }
        if (baseParticle is XmlSchemaElement)
        {
            if (derivedParticle is XmlSchemaElement)
            {
                return IsElementFromElement((XmlSchemaElement)derivedParticle, (XmlSchemaElement)baseParticle);
            }
            return false;
        }
        if (baseParticle is XmlSchemaAny)
        {
            if (derivedParticle is XmlSchemaElement)
            {
                return IsElementFromAny((XmlSchemaElement)derivedParticle, (XmlSchemaAny)baseParticle);
            }
            if (derivedParticle is XmlSchemaAny)
            {
                return IsAnyFromAny((XmlSchemaAny)derivedParticle, (XmlSchemaAny)baseParticle);
            }
            return IsGroupBaseFromAny((XmlSchemaGroupBase)derivedParticle, (XmlSchemaAny)baseParticle);
        }
        if (baseParticle is XmlSchemaAll)
        {
            if (derivedParticle is XmlSchemaElement)
            {
                return IsElementFromGroupBase((XmlSchemaElement)derivedParticle, (XmlSchemaGroupBase)baseParticle, skipEmptableOnly: true);
            }
            if (derivedParticle is XmlSchemaAll)
            {
                return IsGroupBaseFromGroupBase((XmlSchemaGroupBase)derivedParticle, (XmlSchemaGroupBase)baseParticle, skipEmptableOnly: true);
            }
            if (derivedParticle is XmlSchemaSequence)
            {
                return IsSequenceFromAll((XmlSchemaSequence)derivedParticle, (XmlSchemaAll)baseParticle);
            }
        }
        else if (baseParticle is XmlSchemaChoice)
        {
            if (derivedParticle is XmlSchemaElement)
            {
                return IsElementFromGroupBase((XmlSchemaElement)derivedParticle, (XmlSchemaGroupBase)baseParticle, skipEmptableOnly: false);
            }
            if (derivedParticle is XmlSchemaChoice)
            {
                return IsGroupBaseFromGroupBase((XmlSchemaGroupBase)derivedParticle, (XmlSchemaGroupBase)baseParticle, skipEmptableOnly: false);
            }
            if (derivedParticle is XmlSchemaSequence)
            {
                return IsSequenceFromChoice((XmlSchemaSequence)derivedParticle, (XmlSchemaChoice)baseParticle);
            }
        }
        else if (baseParticle is XmlSchemaSequence)
        {
            if (derivedParticle is XmlSchemaElement)
            {
                return IsElementFromGroupBase((XmlSchemaElement)derivedParticle, (XmlSchemaGroupBase)baseParticle, skipEmptableOnly: true);
            }
            if (derivedParticle is XmlSchemaSequence)
            {
                return IsGroupBaseFromGroupBase((XmlSchemaGroupBase)derivedParticle, (XmlSchemaGroupBase)baseParticle, skipEmptableOnly: true);
            }
        }
        return false;
    }
References System.Xml.Schema.XmlSchemaParticle.Empty, System.Xml.Schema.SchemaCollectionCompiler.IsAnyFromAny(), System.Xml.Schema.SchemaCollectionCompiler.IsElementFromAny(), System.Xml.Schema.SchemaCollectionCompiler.IsElementFromElement(), System.Xml.Schema.SchemaCollectionCompiler.IsElementFromGroupBase(), System.Xml.Schema.SchemaCollectionCompiler.IsGroupBaseFromAny(), System.Xml.Schema.SchemaCollectionCompiler.IsGroupBaseFromGroupBase(), System.Xml.Schema.SchemaCollectionCompiler.IsParticleEmptiable(), System.Xml.Schema.SchemaCollectionCompiler.IsSequenceFromAll(), and System.Xml.Schema.SchemaCollectionCompiler.IsSequenceFromChoice().
Referenced by System.Xml.Schema.SchemaCollectionCompiler.CheckParticleDerivation(), System.Xml.Schema.SchemaCollectionCompiler.GetMappingParticle(), System.Xml.Schema.SchemaCollectionCompiler.IsElementFromGroupBase(), System.Xml.Schema.SchemaCollectionCompiler.IsGroupBaseFromAny(), and System.Xml.Schema.SchemaCollectionCompiler.IsGroupBaseFromGroupBase().