Terraria: System.Xml.Schema.SchemaCollectionCompiler.Cleanup
Cleanup() [1/2]
void System.Xml.Schema.SchemaCollectionCompiler.Cleanup () inline private
Definition at line 54 of file SchemaCollectionCompiler.cs.
    {
        foreach (XmlSchemaGroup value in _schema.Groups.Values)
        {
            CleanupGroup(value);
        }
        foreach (XmlSchemaAttributeGroup value2 in _schema.AttributeGroups.Values)
        {
            CleanupAttributeGroup(value2);
        }
        foreach (XmlSchemaType value3 in _schema.SchemaTypes.Values)
        {
            if (value3 is XmlSchemaComplexType)
            {
                CleanupComplexType((XmlSchemaComplexType)value3);
            }
            else
            {
                CleanupSimpleType((XmlSchemaSimpleType)value3);
            }
        }
        foreach (XmlSchemaElement value4 in _schema.Elements.Values)
        {
            CleanupElement(value4);
        }
        foreach (XmlSchemaAttribute value5 in _schema.Attributes.Values)
        {
            CleanupAttribute(value5);
        }
    }
References System.Xml.Schema.SchemaCollectionCompiler._schema, System.Xml.Schema.XmlSchema.AttributeGroups, System.Xml.Schema.XmlSchema.Attributes, System.Xml.Schema.SchemaCollectionCompiler.CleanupAttribute(), System.Xml.Schema.SchemaCollectionCompiler.CleanupAttributeGroup(), System.Xml.Schema.SchemaCollectionCompiler.CleanupComplexType(), System.Xml.Schema.SchemaCollectionCompiler.CleanupElement(), System.Xml.Schema.SchemaCollectionCompiler.CleanupGroup(), System.Xml.Schema.SchemaCollectionCompiler.CleanupSimpleType(), System.Xml.Schema.XmlSchema.Elements, System.Xml.Schema.XmlSchema.Groups, System.Xml.Schema.XmlSchema.SchemaTypes, System.value, and System.Xml.Schema.XmlSchemaObjectTable.Values.
Referenced by System.Xml.Schema.SchemaCollectionCompiler.Cleanup(), System.Xml.Schema.XmlSchema.Clone(), and System.Xml.Schema.SchemaCollectionCompiler.Execute().