Terraria: System.Xml.Schema.SchemaCollectionCompiler.CompileComplexContentRestriction
CompileComplexContentRestriction()
void System.Xml.Schema.SchemaCollectionCompiler.CompileComplexContentRestriction (XmlSchemaComplexType complexType, XmlSchemaComplexContent complexContent, XmlSchemaComplexContentRestriction complexRestriction) inline private
Definition at line 916 of file SchemaCollectionCompiler.cs.
    {
        XmlSchemaComplexType xmlSchemaComplexType = null;
        if (complexType.Redefined != null && complexRestriction.BaseTypeName == complexType.Redefined.QualifiedName)
        {
            xmlSchemaComplexType = (XmlSchemaComplexType)complexType.Redefined;
            CompileComplexType(xmlSchemaComplexType);
        }
        else
        {
            xmlSchemaComplexType = GetComplexType(complexRestriction.BaseTypeName);
            if (xmlSchemaComplexType == null)
            {
                SendValidationEvent(System.SR.Sch_UndefBaseRestriction, complexRestriction.BaseTypeName.ToString(), complexRestriction);
                return;
            }
        }
        if (xmlSchemaComplexType != null && xmlSchemaComplexType.ElementDecl != null && xmlSchemaComplexType.ContentType == XmlSchemaContentType.TextOnly)
        {
            SendValidationEvent(System.SR.Sch_NotComplexContent, complexType);
            return;
        }
        complexType.SetBaseSchemaType(xmlSchemaComplexType);
        if ((xmlSchemaComplexType.FinalResolved & XmlSchemaDerivationMethod.Restriction) != 0)
        {
            SendValidationEvent(System.SR.Sch_BaseFinalRestriction, complexType);
        }
        CompileLocalAttributes(xmlSchemaComplexType, complexType, complexRestriction.Attributes, complexRestriction.AnyAttribute, XmlSchemaDerivationMethod.Restriction);
        complexType.SetContentTypeParticle(CompileContentTypeParticle(complexRestriction.Particle, substitution: true));
        complexType.SetContentType(GetSchemaContentType(complexType, complexContent, complexType.ContentTypeParticle));
        if (complexType.ContentType == XmlSchemaContentType.Empty)
        {
            _ = xmlSchemaComplexType.ElementDecl;
            if (xmlSchemaComplexType.ElementDecl != null && !xmlSchemaComplexType.ElementDecl.ContentValidator.IsEmptiable)
            {
                SendValidationEvent(System.SR.Sch_InvalidContentRestriction, complexType);
            }
        }
        complexType.SetDerivedBy(XmlSchemaDerivationMethod.Restriction);
    }
References System.Xml.Schema.SchemaCollectionCompiler.CompileComplexType(), System.Xml.Schema.SchemaCollectionCompiler.CompileContentTypeParticle(), System.Xml.Schema.SchemaCollectionCompiler.CompileLocalAttributes(), System.Xml.Schema.SchemaCollectionCompiler.GetComplexType(), System.Xml.Schema.SchemaCollectionCompiler.GetSchemaContentType(), System.SR.Sch_BaseFinalRestriction, System.SR.Sch_InvalidContentRestriction, System.SR.Sch_NotComplexContent, System.SR.Sch_UndefBaseRestriction, and System.Xml.Schema.BaseProcessor.SendValidationEvent().
Referenced by System.Xml.Schema.SchemaCollectionCompiler.CompileComplexType().