Terraria: System.Xml.Schema.SchemaCollectionCompiler.IsSequenceFromChoice
IsSequenceFromChoice()
bool System.Xml.Schema.SchemaCollectionCompiler.IsSequenceFromChoice (XmlSchemaSequence derivedSequence, XmlSchemaChoice baseChoice) inline private
Definition at line 1420 of file SchemaCollectionCompiler.cs.
    {
        CalculateSequenceRange(derivedSequence, out var minOccurs, out var maxOccurs);
        if (!IsValidOccurrenceRangeRestriction(minOccurs, maxOccurs, baseChoice.MinOccurs, baseChoice.MaxOccurs))
        {
            return false;
        }
        for (int i = 0; i < derivedSequence.Items.Count; i++)
        {
            if (GetMappingParticle((XmlSchemaParticle)derivedSequence.Items[i], baseChoice.Items) < 0)
            {
                return false;
            }
        }
        return true;
    }
References System.Xml.Schema.SchemaCollectionCompiler.CalculateSequenceRange(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Xml.Schema.SchemaCollectionCompiler.GetMappingParticle(), and System.Xml.Schema.SchemaCollectionCompiler.IsValidOccurrenceRangeRestriction().
Referenced by System.Xml.Schema.SchemaCollectionCompiler.IsValidRestriction().