Terraria: System.Xml.Schema.SchemaCollectionCompiler.CompileComplexType
CompileComplexType()
void System.Xml.Schema.SchemaCollectionCompiler.CompileComplexType (XmlSchemaComplexType complexType) inline private
Definition at line 642 of file SchemaCollectionCompiler.cs.
    {
        if (complexType.ElementDecl != null)
        {
            return;
        }
        if (complexType.IsProcessing)
        {
            SendValidationEvent(System.SR.Sch_TypeCircularRef, complexType);
            return;
        }
        complexType.IsProcessing = true;
        if (complexType.ContentModel != null)
        {
            if (complexType.ContentModel is XmlSchemaSimpleContent)
            {
                XmlSchemaSimpleContent xmlSchemaSimpleContent = (XmlSchemaSimpleContent)complexType.ContentModel;
                complexType.SetContentType(XmlSchemaContentType.TextOnly);
                if (xmlSchemaSimpleContent.Content is XmlSchemaSimpleContentExtension)
                {
                    CompileSimpleContentExtension(complexType, (XmlSchemaSimpleContentExtension)xmlSchemaSimpleContent.Content);
                }
                else
                {
                    CompileSimpleContentRestriction(complexType, (XmlSchemaSimpleContentRestriction)xmlSchemaSimpleContent.Content);
                }
            }
            else
            {
                XmlSchemaComplexContent xmlSchemaComplexContent = (XmlSchemaComplexContent)complexType.ContentModel;
                if (xmlSchemaComplexContent.Content is XmlSchemaComplexContentExtension)
                {
                    CompileComplexContentExtension(complexType, xmlSchemaComplexContent, (XmlSchemaComplexContentExtension)xmlSchemaComplexContent.Content);
                }
                else
                {
                    CompileComplexContentRestriction(complexType, xmlSchemaComplexContent, (XmlSchemaComplexContentRestriction)xmlSchemaComplexContent.Content);
                }
            }
        }
        else
        {
            complexType.SetBaseSchemaType(XmlSchemaComplexType.AnyType);
            CompileLocalAttributes(XmlSchemaComplexType.AnyType, complexType, complexType.Attributes, complexType.AnyAttribute, XmlSchemaDerivationMethod.Restriction);
            complexType.SetDerivedBy(XmlSchemaDerivationMethod.Restriction);
            complexType.SetContentTypeParticle(CompileContentTypeParticle(complexType.Particle, substitution: true));
            complexType.SetContentType(GetSchemaContentType(complexType, null, complexType.ContentTypeParticle));
        }
        bool flag = false;
        foreach (XmlSchemaAttribute value in complexType.AttributeUses.Values)
        {
            if (value.Use == XmlSchemaUse.Prohibited)
            {
                continue;
            }
            XmlSchemaDatatype datatype = value.Datatype;
            if (datatype != null && datatype.TokenizedType == XmlTokenizedType.ID)
            {
                if (flag)
                {
                    SendValidationEvent(System.SR.Sch_TwoIdAttrUses, complexType);
                }
                else
                {
                    flag = true;
                }
            }
        }
        SchemaElementDecl schemaElementDecl = new SchemaElementDecl();
        schemaElementDecl.ContentValidator = CompileComplexContent(complexType);
        schemaElementDecl.SchemaType = complexType;
        schemaElementDecl.IsAbstract = complexType.IsAbstract;
        schemaElementDecl.Datatype = complexType.Datatype;
        schemaElementDecl.Block = complexType.BlockResolved;
        schemaElementDecl.AnyAttribute = complexType.AttributeWildcard;
        foreach (XmlSchemaAttribute value2 in complexType.AttributeUses.Values)
        {
            if (value2.Use == XmlSchemaUse.Prohibited)
            {
                if (!schemaElementDecl.ProhibitedAttributes.ContainsKey(value2.QualifiedName))
                {
                    schemaElementDecl.ProhibitedAttributes.Add(value2.QualifiedName, value2.QualifiedName);
                }
            }
            else if (!schemaElementDecl.AttDefs.ContainsKey(value2.QualifiedName) && value2.AttDef != null && value2.AttDef.Name != XmlQualifiedName.Empty && value2.AttDef != SchemaAttDef.Empty)
            {
                schemaElementDecl.AddAttDef(value2.AttDef);
            }
        }
        complexType.ElementDecl = schemaElementDecl;
        complexType.IsProcessing = false;
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Xml.Schema.XmlSchemaComplexType.AnyType, System.Xml.Schema.SchemaCollectionCompiler.CompileComplexContent(), System.Xml.Schema.SchemaCollectionCompiler.CompileComplexContentExtension(), System.Xml.Schema.SchemaCollectionCompiler.CompileComplexContentRestriction(), System.Xml.Schema.SchemaCollectionCompiler.CompileContentTypeParticle(), System.Xml.Schema.SchemaCollectionCompiler.CompileLocalAttributes(), System.Xml.Schema.SchemaCollectionCompiler.CompileSimpleContentExtension(), System.Xml.Schema.SchemaCollectionCompiler.CompileSimpleContentRestriction(), System.Collections.Generic.Dictionary< TKey, TValue >.ContainsKey(), System.Xml.Dictionary, System.Xml.Schema.SchemaAttDef.Empty, System.Xml.XmlQualifiedName.Empty, System.Xml.Schema.SchemaCollectionCompiler.GetSchemaContentType(), System.SR.Sch_TwoIdAttrUses, System.SR.Sch_TypeCircularRef, System.Xml.Schema.BaseProcessor.SendValidationEvent(), System.Xml.Schema.XmlSchemaDatatype.TokenizedType, System.value, and System.Collections.Generic.Dictionary< TKey, TValue >.Values.
Referenced by System.Xml.Schema.SchemaCollectionCompiler.Compile(), System.Xml.Schema.SchemaCollectionCompiler.CompileComplexContentExtension(), System.Xml.Schema.SchemaCollectionCompiler.CompileComplexContentRestriction(), System.Xml.Schema.SchemaCollectionCompiler.CompileElement(), System.Xml.Schema.SchemaCollectionCompiler.CompileSimpleContentExtension(), System.Xml.Schema.SchemaCollectionCompiler.CompileSimpleContentRestriction(), System.Xml.Schema.SchemaCollectionCompiler.GetAnySchemaType(), and System.Xml.Schema.SchemaCollectionCompiler.GetComplexType().