Terraria: System.Xml.Schema.SchemaCollectionCompiler.CalculateEffectiveTotalRange
CalculateEffectiveTotalRange()
void System.Xml.Schema.SchemaCollectionCompiler.CalculateEffectiveTotalRange (XmlSchemaParticle particle, out decimal minOccurs, out decimal maxOccurs) inline private
Definition at line 1497 of file SchemaCollectionCompiler.cs.
    {
        if (particle is XmlSchemaElement || particle is XmlSchemaAny)
        {
            minOccurs = particle.MinOccurs;
            maxOccurs = particle.MaxOccurs;
            return;
        }
        if (particle is XmlSchemaChoice)
        {
            if (((XmlSchemaChoice)particle).Items.Count == 0)
            {
                minOccurs = (maxOccurs = 0m);
                return;
            }
            minOccurs = decimal.MaxValue;
            maxOccurs = default(decimal);
            XmlSchemaChoice xmlSchemaChoice = (XmlSchemaChoice)particle;
            for (int i = 0; i < xmlSchemaChoice.Items.Count; i++)
            {
                CalculateEffectiveTotalRange((XmlSchemaParticle)xmlSchemaChoice.Items[i], out var minOccurs2, out var maxOccurs2);
                if (minOccurs2 < minOccurs)
                {
                    minOccurs = minOccurs2;
                }
                if (maxOccurs2 > maxOccurs)
                {
                    maxOccurs = maxOccurs2;
                }
            }
            minOccurs *= particle.MinOccurs;
            if (maxOccurs != decimal.MaxValue)
            {
                if (particle.MaxOccurs == decimal.MaxValue)
                {
                    maxOccurs = decimal.MaxValue;
                }
                else
                {
                    maxOccurs *= particle.MaxOccurs;
                }
            }
            return;
        }
        XmlSchemaObjectCollection items = ((XmlSchemaGroupBase)particle).Items;
        if (items.Count == 0)
        {
            minOccurs = (maxOccurs = 0m);
            return;
        }
        minOccurs = default(decimal);
        maxOccurs = default(decimal);
        for (int j = 0; j < items.Count; j++)
        {
            CalculateEffectiveTotalRange((XmlSchemaParticle)items[j], out var minOccurs3, out var maxOccurs3);
            minOccurs += minOccurs3;
            if (maxOccurs != decimal.MaxValue)
            {
                if (maxOccurs3 == decimal.MaxValue)
                {
                    maxOccurs = decimal.MaxValue;
                }
                else
                {
                    maxOccurs += maxOccurs3;
                }
            }
        }
        minOccurs *= particle.MinOccurs;
        if (maxOccurs != decimal.MaxValue)
        {
            if (particle.MaxOccurs == decimal.MaxValue)
            {
                maxOccurs = decimal.MaxValue;
            }
            else
            {
                maxOccurs *= particle.MaxOccurs;
            }
        }
    }
References System.Xml.Schema.SchemaCollectionCompiler.CalculateEffectiveTotalRange(), System.Collections.CollectionBase.Count, System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Xml.Dictionary, System.Xml.Schema.XmlSchemaParticle.MaxOccurs, and System.Xml.Schema.XmlSchemaParticle.MinOccurs.
Referenced by System.Xml.Schema.SchemaCollectionCompiler.CalculateEffectiveTotalRange(), System.Xml.Schema.SchemaCollectionCompiler.IsGroupBaseFromAny(), and System.Xml.Schema.SchemaCollectionCompiler.IsParticleEmptiable().