Terraria: ResourcePackList.Publishable
Publishable()
static ResourcePackList ResourcePackList.Publishable (JArray serializedState, IServiceProvider services, string searchPath) inline static
     {
         if (!Directory.Exists(searchPath))
         {
             return new ResourcePackList();
         }
         List<ResourcePack> resourcePacks = new List<ResourcePack>();
         CreatePacksFromZips(services, searchPath, resourcePacks);
         CreatePacksFromDirectories(services, searchPath, resourcePacks);
         return new ResourcePackList(resourcePacks);
     }
References ResourcePackList(), CreatePacksFromDirectories(), and CreatePacksFromZips().
Referenced by AssetInitializer.CreatePublishableResourcePacksList().