Terraria: MS.Internal.Xml.XPath.FollSiblingQuery.Advance
Advance()
override XPathNavigator MS.Internal.Xml.XPath.FollSiblingQuery.Advance () inline
Definition at line 67 of file FollSiblingQuery.cs.
    {
        while (true)
        {
            if (currentNode == null)
            {
                if (_nextInput == null)
                {
                    _nextInput = FetchInput();
                }
                if (_elementStk.Count == 0)
                {
                    if (_nextInput == null)
                    {
                        break;
                    }
                    currentNode = _nextInput;
                    _nextInput = FetchInput();
                }
                else
                {
                    currentNode = _elementStk.Pop();
                }
            }
            while (currentNode.IsDescendant(_nextInput))
            {
                _elementStk.Push(currentNode);
                currentNode = _nextInput;
                _nextInput = qyInput.Advance();
                if (_nextInput != null)
                {
                    _nextInput = _nextInput.Clone();
                }
            }
            while (currentNode.MoveToNext())
            {
                if (matches(currentNode))
                {
                    position++;
                    return currentNode;
                }
            }
            currentNode = null;
        }
        return null;
    }
References MS.Internal.Xml.XPath.FollSiblingQuery._elementStk, MS.Internal.Xml.XPath.FollSiblingQuery._nextInput, MS.Internal.Xml.XPath.Query.Advance(), System.Xml.XPath.XPathNavigator.Clone(), MS.Internal.Xml.XPath.BaseAxisQuery.currentNode, MS.Internal.Xml.XPath.FollSiblingQuery.FetchInput(), System.Xml.XPath.XPathNavigator.IsDescendant(), MS.Internal.Xml.XPath.BaseAxisQuery.matches(), System.Xml.XPath.XPathNavigator.MoveToNext(), MS.Internal.Xml.XPath.ClonableStack< T >.Pop(), MS.Internal.Xml.XPath.BaseAxisQuery.position, MS.Internal.Xml.XPath.ClonableStack< T >.Push(), and MS.Internal.Xml.XPath.BaseAxisQuery.qyInput.