Terraria: MS.Internal.Xml.XPath.FollSiblingQuery.Visited
Visited()
bool MS.Internal.Xml.XPath.FollSiblingQuery.Visited (XPathNavigator nav) inline private
Definition at line 37 of file FollSiblingQuery.cs.
    {
        XPathNavigator xPathNavigator = nav.Clone();
        xPathNavigator.MoveToParent();
        for (int i = 0; i < _parentStk.Count; i++)
        {
            if (xPathNavigator.IsSamePosition(_parentStk[i]))
            {
                return true;
            }
        }
        _parentStk.Add(xPathNavigator);
        return false;
    }
References MS.Internal.Xml.XPath.FollSiblingQuery._parentStk, System.Collections.Generic.List< T >.Add(), System.Xml.XPath.XPathNavigator.Clone(), and System.Collections.Generic.List< T >.Count.
Referenced by MS.Internal.Xml.XPath.FollSiblingQuery.FetchInput().