Terraria: Terraria.DelegateMethods.CharacterPreview.Float
Float()
static void Terraria.DelegateMethods.CharacterPreview.Float (Projectile proj, bool walking) inline static
        {
            float num = 0.5f;
            float num2 = (float)Main.timeForVisualEffects % 60f / 60f;
            proj.position.Y += 0f - num + (float)(Math.Cos(num2 * ((float)Math.PI * 2f) * 2f) * (double)(num * 2f));
        }
References Terraria.Main.timeForVisualEffects.
Referenced by Terraria.DelegateMethods.CharacterPreview.EtsyPet(), Terraria.DelegateMethods.CharacterPreview.FloatAndRotateForwardWhenWalking(), and Terraria.DelegateMethods.CharacterPreview.FloatAndSpinWhenWalking().