Terraria: System.Linq.Expressions.Interpreter.CallInstruction.TryGetLightLambdaTarget
TryGetLightLambdaTarget()
static bool System.Linq.Expressions.Interpreter.CallInstruction.TryGetLightLambdaTarget (object instance, [NotNullWhen(true)] out LightLambda lightLambda) inline static protected inherited
Definition at line 189 of file CallInstruction.cs.
    {
        if (instance is Delegate { Target: Func<object[], object> target })
        {
            lightLambda = target.Target as LightLambda;
            if (lightLambda != null)
            {
                return true;
            }
        }
        lightLambda = null;
        return false;
    }
Referenced by System.Linq.Expressions.Interpreter.ActionCallInstruction< T0, T1, T2, T3 >.Run(), System.Linq.Expressions.Interpreter.ByRefMethodInfoCallInstruction.Run(), System.Linq.Expressions.Interpreter.FuncCallInstruction< T0, T1, T2, T3, TRet >.Run(), and System.Linq.Expressions.Interpreter.MethodInfoCallInstruction.Run().