Terraria: System.Linq.Expressions.Interpreter.CallInstruction.SlowCreate
SlowCreate()
static CallInstruction System.Linq.Expressions.Interpreter.CallInstruction.SlowCreate (MethodInfo info, ParameterInfo[] pis) inline static private inherited
Definition at line 162 of file CallInstruction.cs.
    {
        List<Type> list = new List<Type>();
        if (!info.IsStatic)
        {
            list.Add(info.DeclaringType);
        }
        foreach (ParameterInfo parameterInfo in pis)
        {
            list.Add(parameterInfo.ParameterType);
        }
        if (info.ReturnType != typeof(void))
        {
            list.Add(info.ReturnType);
        }
        Type[] arrTypes = list.ToArray();
        try
        {
            return (CallInstruction)Activator.CreateInstance(GetHelperType(info, arrTypes), info);
        }
        catch (TargetInvocationException exception)
        {
            ExceptionHelpers.UnwrapAndRethrow(exception);
            throw ContractUtils.Unreachable;
        }
    }
References System.Activator.CreateInstance(), System.exception, System.Linq.Expressions.Interpreter.CallInstruction.GetHelperType(), System.info, System.list, System.Dynamic.Utils.ContractUtils.Unreachable, and System.Linq.Expressions.Interpreter.ExceptionHelpers.UnwrapAndRethrow().
Referenced by System.Linq.Expressions.Interpreter.CallInstruction.Create(), System.Linq.Expressions.Interpreter.CallInstruction.FastCreate(), System.Linq.Expressions.Interpreter.CallInstruction.FastCreate< T0 >(), and System.Linq.Expressions.Interpreter.CallInstruction.FastCreate< T0, T1 >().