Terraria: System.Linq.Expressions.Interpreter.CallInstruction.Create
Create() [2/2]
static CallInstruction System.Linq.Expressions.Interpreter.CallInstruction.Create (MethodInfo info, ParameterInfo[] parameters) inline static inherited
Definition at line 23 of file CallInstruction.cs.
    {
        int num = parameters.Length;
        if (!info.IsStatic)
        {
            num++;
        }
        if (info.DeclaringType != null && info.DeclaringType.IsArray && (info.Name == "Get" || info.Name == "Set"))
        {
            return GetArrayAccessor(info, num);
        }
        if (!info.IsStatic && info.DeclaringType.IsValueType)
        {
            return new MethodInfoCallInstruction(info, num);
        }
        if (num >= 5)
        {
            return new MethodInfoCallInstruction(info, num);
        }
        foreach (ParameterInfo parameterInfo in parameters)
        {
            if (parameterInfo.ParameterType.IsByRef)
            {
                return new MethodInfoCallInstruction(info, num);
            }
        }
        ShouldCache(info);
        if (s_cache.TryGetValue(info, out var value))
        {
            return value;
        }
        try
        {
            value = ((num >= 3) ? SlowCreate(info, parameters) : FastCreate(info, parameters));
        }
        catch (TargetInvocationException ex)
        {
            if (!(ex.InnerException is NotSupportedException))
            {
                throw;
            }
            value = new MethodInfoCallInstruction(info, num);
        }
        catch (NotSupportedException)
        {
            value = new MethodInfoCallInstruction(info, num);
        }
        ShouldCache(info);
        s_cache[info] = value;
        return value;
    }
References System.Linq.Expressions.Interpreter.CallInstruction.FastCreate(), System.Linq.Expressions.Interpreter.CallInstruction.GetArrayAccessor(), System.info, System.Linq.Expressions.Interpreter.CallInstruction.s_cache, System.Linq.Expressions.Interpreter.CallInstruction.ShouldCache(), System.Linq.Expressions.Interpreter.CallInstruction.SlowCreate(), and System.value.