Terraria: System.Linq.Expressions.Interpreter.CallInstruction.FastCreate
FastCreate()
static CallInstruction System.Linq.Expressions.Interpreter.CallInstruction.FastCreate (MethodInfo target, ParameterInfo[] pi) inline static private inherited
Definition at line 212 of file CallInstruction.cs.
    {
        Type type = TryGetParameterOrReturnType(target, pi, 0);
        if (type == null)
        {
            return new ActionCallInstruction(target);
        }
        if (type.IsEnum)
        {
            return SlowCreate(target, pi);
        }
        switch (type.GetTypeCode())
        {
        case TypeCode.Object:
            if (!(type != typeof(object)) || (!IndexIsNotReturnType(0, target, pi) && !type.IsValueType))
            {
                return FastCreate<object>(target, pi);
            }
            break;
        case TypeCode.Int16:
            return FastCreate<short>(target, pi);
        case TypeCode.Int32:
            return FastCreate<int>(target, pi);
        case TypeCode.Int64:
            return FastCreate<long>(target, pi);
        case TypeCode.Boolean:
            return FastCreate<bool>(target, pi);
        case TypeCode.Char:
            return FastCreate<char>(target, pi);
        case TypeCode.Byte:
            return FastCreate<byte>(target, pi);
        case TypeCode.Decimal:
            return FastCreate<decimal>(target, pi);
        case TypeCode.DateTime:
            return FastCreate<DateTime>(target, pi);
        case TypeCode.Double:
            return FastCreate<double>(target, pi);
        case TypeCode.Single:
            return FastCreate<float>(target, pi);
        case TypeCode.UInt16:
            return FastCreate<ushort>(target, pi);
        case TypeCode.UInt32:
            return FastCreate<uint>(target, pi);
        case TypeCode.UInt64:
            return FastCreate<ulong>(target, pi);
        case TypeCode.String:
            return FastCreate<string>(target, pi);
        case TypeCode.SByte:
            return FastCreate<sbyte>(target, pi);
        }
        return SlowCreate(target, pi);
    }
References System.Linq.Expressions.Interpreter.CallInstruction.IndexIsNotReturnType(), System.Linq.Expressions.Interpreter.CallInstruction.SlowCreate(), System.Linq.Expressions.Interpreter.CallInstruction.TryGetParameterOrReturnType(), and System.type.
Referenced by System.Linq.Expressions.Interpreter.CallInstruction.Create().