Terraria: System.Linq.Expressions.Interpreter.CallInstruction.FastCreate< T0 >
FastCreate< T0 >()
static CallInstruction System.Linq.Expressions.Interpreter.CallInstruction.FastCreate< T0 > (MethodInfo target, ParameterInfo[] pi) inline static private inherited
Definition at line 265 of file CallInstruction.cs.
    {
        Type type = TryGetParameterOrReturnType(target, pi, 1);
        if (type == null)
        {
            if (target.ReturnType == typeof(void))
            {
                return new ActionCallInstruction<T0>(target);
            }
            return new FuncCallInstruction<T0>(target);
        }
        if (type.IsEnum)
        {
            return SlowCreate(target, pi);
        }
        switch (type.GetTypeCode())
        {
        case TypeCode.Object:
            if (!(type != typeof(object)) || (!IndexIsNotReturnType(1, target, pi) && !type.IsValueType))
            {
                return FastCreate<T0, object>(target, pi);
            }
            break;
        case TypeCode.Int16:
            return FastCreate<T0, short>(target, pi);
        case TypeCode.Int32:
            return FastCreate<T0, int>(target, pi);
        case TypeCode.Int64:
            return FastCreate<T0, long>(target, pi);
        case TypeCode.Boolean:
            return FastCreate<T0, bool>(target, pi);
        case TypeCode.Char:
            return FastCreate<T0, char>(target, pi);
        case TypeCode.Byte:
            return FastCreate<T0, byte>(target, pi);
        case TypeCode.Decimal:
            return FastCreate<T0, decimal>(target, pi);
        case TypeCode.DateTime:
            return FastCreate<T0, DateTime>(target, pi);
        case TypeCode.Double:
            return FastCreate<T0, double>(target, pi);
        case TypeCode.Single:
            return FastCreate<T0, float>(target, pi);
        case TypeCode.UInt16:
            return FastCreate<T0, ushort>(target, pi);
        case TypeCode.UInt32:
            return FastCreate<T0, uint>(target, pi);
        case TypeCode.UInt64:
            return FastCreate<T0, ulong>(target, pi);
        case TypeCode.String:
            return FastCreate<T0, string>(target, pi);
        case TypeCode.SByte:
            return FastCreate<T0, sbyte>(target, pi);
        }
        return SlowCreate(target, pi);
    }
References System.Linq.Expressions.Interpreter.CallInstruction.IndexIsNotReturnType(), System.Reflection.MethodInfo.ReturnType, System.Linq.Expressions.Interpreter.CallInstruction.SlowCreate(), System.Linq.Expressions.Interpreter.CallInstruction.TryGetParameterOrReturnType(), and System.type.