Terraria: System.Linq.Expressions.Interpreter.CallInstruction.TryGetParameterOrReturnType
TryGetParameterOrReturnType()
static Type System.Linq.Expressions.Interpreter.CallInstruction.TryGetParameterOrReturnType (MethodInfo target, ParameterInfo[] pi, int index) inline static private inherited
Definition at line 128 of file CallInstruction.cs.
    {
        if (!target.IsStatic)
        {
            index--;
            if (index < 0)
            {
                return target.DeclaringType;
            }
        }
        if (index < pi.Length)
        {
            return pi[index].ParameterType;
        }
        if (target.ReturnType == typeof(void) || index > pi.Length)
        {
            return null;
        }
        return target.ReturnType;
    }
References System.Reflection.MemberInfo.DeclaringType, System.Linq.index, System.Reflection.MethodBase.IsStatic, and System.Reflection.MethodInfo.ReturnType.
Referenced by System.Linq.Expressions.Interpreter.CallInstruction.FastCreate(), System.Linq.Expressions.Interpreter.CallInstruction.FastCreate< T0 >(), and System.Linq.Expressions.Interpreter.CallInstruction.FastCreate< T0, T1 >().