Terraria: System.Linq.Expressions.Interpreter.CallInstruction.InterpretLambdaInvoke
InterpretLambdaInvoke()
object System.Linq.Expressions.Interpreter.CallInstruction.InterpretLambdaInvoke (LightLambda targetLambda, object[] args) inline protected inherited
Definition at line 203 of file CallInstruction.cs.
    {
        if (ProducedStack > 0)
        {
            return targetLambda.Run(args);
        }
        return targetLambda.RunVoid(args);
    }
References System.Linq.Expressions.Interpreter.Instruction.ProducedStack.
Referenced by System.Linq.Expressions.Interpreter.ActionCallInstruction< T0, T1, T2, T3 >.Run(), System.Linq.Expressions.Interpreter.ByRefMethodInfoCallInstruction.Run(), System.Linq.Expressions.Interpreter.FuncCallInstruction< T0, T1, T2, T3, TRet >.Run(), and System.Linq.Expressions.Interpreter.MethodInfoCallInstruction.Run().