Terraria: System.TimeZoneInfo.TryCreateAdjustmentRules
TryCreateAdjustmentRules()
static bool System.TimeZoneInfo.TryCreateAdjustmentRules (string id, in Interop::Kernel32::REG_TZI_FORMAT defaultTimeZoneInformation, out AdjustmentRule[] rules, out Exception e, int defaultBaseUtcOffset) inline static private
Definition at line 2593 of file TimeZoneInfo.cs.
    {
        rules = null;
        e = null;
        try
        {
            using RegistryKey registryKey = Registry.LocalMachine.OpenSubKey("SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Time Zones\\" + id + "\\Dynamic DST", writable: false);
            if (registryKey == null)
            {
                AdjustmentRule adjustmentRule = CreateAdjustmentRuleFromTimeZoneInformation(in defaultTimeZoneInformation, DateTime.MinValue.Date, DateTime.MaxValue.Date, defaultBaseUtcOffset);
                if (adjustmentRule != null)
                {
                    rules = new AdjustmentRule[1] { adjustmentRule };
                }
                return true;
            }
            int num = (int)registryKey.GetValue("FirstEntry", -1);
            int num2 = (int)registryKey.GetValue("LastEntry", -1);
            if (num == -1 || num2 == -1 || num > num2)
            {
                return false;
            }
            if (!TryGetTimeZoneEntryFromRegistry(registryKey, num.ToString(CultureInfo.InvariantCulture), out var dtzi))
            {
                return false;
            }
            if (num == num2)
            {
                AdjustmentRule adjustmentRule2 = CreateAdjustmentRuleFromTimeZoneInformation(in dtzi, DateTime.MinValue.Date, DateTime.MaxValue.Date, defaultBaseUtcOffset);
                if (adjustmentRule2 != null)
                {
                    rules = new AdjustmentRule[1] { adjustmentRule2 };
                }
                return true;
            }
            List<AdjustmentRule> list = new List<AdjustmentRule>(1);
            AdjustmentRule adjustmentRule3 = CreateAdjustmentRuleFromTimeZoneInformation(in dtzi, DateTime.MinValue.Date, new DateTime(num, 12, 31), defaultBaseUtcOffset);
            if (adjustmentRule3 != null)
            {
                list.Add(adjustmentRule3);
            }
            for (int i = num + 1; i < num2; i++)
            {
                if (!TryGetTimeZoneEntryFromRegistry(registryKey, i.ToString(CultureInfo.InvariantCulture), out dtzi))
                {
                    return false;
                }
                AdjustmentRule adjustmentRule4 = CreateAdjustmentRuleFromTimeZoneInformation(in dtzi, new DateTime(i, 1, 1), new DateTime(i, 12, 31), defaultBaseUtcOffset);
                if (adjustmentRule4 != null)
                {
                    list.Add(adjustmentRule4);
                }
            }
            if (!TryGetTimeZoneEntryFromRegistry(registryKey, num2.ToString(CultureInfo.InvariantCulture), out dtzi))
            {
                return false;
            }
            AdjustmentRule adjustmentRule5 = CreateAdjustmentRuleFromTimeZoneInformation(in dtzi, new DateTime(num2, 1, 1), DateTime.MaxValue.Date, defaultBaseUtcOffset);
            if (adjustmentRule5 != null)
            {
                list.Add(adjustmentRule5);
            }
            if (list.Count != 0)
            {
                rules = list.ToArray();
            }
        }
        catch (InvalidCastException ex)
        {
            e = ex;
            return false;
        }
        catch (ArgumentOutOfRangeException ex2)
        {
            e = ex2;
            return false;
        }
        catch (ArgumentException ex3)
        {
            e = ex3;
            return false;
        }
        return true;
    }
References System.TimeZoneInfo.CreateAdjustmentRuleFromTimeZoneInformation(), System.DateTime, System.Runtime.Serialization.Dictionary, System.Globalization.CultureInfo.InvariantCulture, System.list, Internal.Win32.Registry.LocalMachine, System.DateTime.MaxValue, System.DateTime.MinValue, and System.TimeZoneInfo.TryGetTimeZoneEntryFromRegistry().
Referenced by System.TimeZoneInfo.TryGetTimeZoneFromLocalMachine().