Terraria: System.TimeZoneInfo.TransitionTimeToDateTime
TransitionTimeToDateTime()
static DateTime System.TimeZoneInfo.TransitionTimeToDateTime (int year, TransitionTime transitionTime) inline static package
Definition at line 2054 of file TimeZoneInfo.cs.
    {
        TimeSpan timeOfDay = transitionTime.TimeOfDay.TimeOfDay;
        DateTime result;
        if (transitionTime.IsFixedDateRule)
        {
            int num = transitionTime.Day;
            if (num > 28)
            {
                int num2 = DateTime.DaysInMonth(year, transitionTime.Month);
                if (num > num2)
                {
                    num = num2;
                }
            }
            result = new DateTime(year, transitionTime.Month, num) + timeOfDay;
        }
        else if (transitionTime.Week <= 4)
        {
            result = new DateTime(year, transitionTime.Month, 1) + timeOfDay;
            int dayOfWeek = (int)result.DayOfWeek;
            int num3 = (int)(transitionTime.DayOfWeek - dayOfWeek);
            if (num3 < 0)
            {
                num3 += 7;
            }
            num3 += 7 * (transitionTime.Week - 1);
            if (num3 > 0)
            {
                result = result.AddDays(num3);
            }
        }
        else
        {
            int day = DateTime.DaysInMonth(year, transitionTime.Month);
            result = new DateTime(year, transitionTime.Month, day) + timeOfDay;
            int dayOfWeek2 = (int)result.DayOfWeek;
            int num4 = (int)(dayOfWeek2 - transitionTime.DayOfWeek);
            if (num4 < 0)
            {
                num4 += 7;
            }
            if (num4 > 0)
            {
                result = result.AddDays(-num4);
            }
        }
        return result;
    }
References System.DateTime.AddDays(), System.DateTime, System.DateTime.DayOfWeek, System.DateTime.DaysInMonth(), System.Runtime.Serialization.Dictionary, and System.year.
Referenced by System.CurrentSystemTimeZone.CreateDaylightChanges(), and System.TimeZoneInfo.GetDaylightTime().