Terraria: System.TimeZoneInfo.TryGetTimeZoneFromLocalMachine
TryGetTimeZoneFromLocalMachine() [2/2]
static TimeZoneInfoResult System.TimeZoneInfo.TryGetTimeZoneFromLocalMachine (string id, out TimeZoneInfo value, out Exception e) inline static private
Definition at line 2823 of file TimeZoneInfo.cs.
    {
        e = null;
        using RegistryKey registryKey = Registry.LocalMachine.OpenSubKey("SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Time Zones\\" + id, writable: false);
        if (registryKey == null)
        {
            value = null;
            return TimeZoneInfoResult.TimeZoneNotFoundException;
        }
        if (!TryGetTimeZoneEntryFromRegistry(registryKey, "TZI", out var dtzi))
        {
            value = null;
            return TimeZoneInfoResult.InvalidTimeZoneException;
        }
        if (!TryCreateAdjustmentRules(id, in dtzi, out var rules, out e, dtzi.Bias))
        {
            value = null;
            return TimeZoneInfoResult.InvalidTimeZoneException;
        }
        GetLocalizedNamesByRegistryKey(registryKey, out var displayName, out var standardName, out var daylightName);
        try
        {
            value = new TimeZoneInfo(id, new TimeSpan(0, -dtzi.Bias, 0), displayName, standardName, daylightName, rules, disableDaylightSavingTime: false);
            return TimeZoneInfoResult.Success;
        }
        catch (ArgumentException ex)
        {
            value = null;
            e = ex;
            return TimeZoneInfoResult.InvalidTimeZoneException;
        }
        catch (InvalidTimeZoneException ex2)
        {
            value = null;
            e = ex2;
            return TimeZoneInfoResult.InvalidTimeZoneException;
        }
    }
References System.TimeZoneInfo.TimeZoneInfo(), System.Runtime.Serialization.Dictionary, System.TimeZoneInfo.GetLocalizedNamesByRegistryKey(), Internal.Win32.Registry.LocalMachine, System.TimeZoneInfo.TryCreateAdjustmentRules(), System.TimeZoneInfo.TryGetTimeZoneEntryFromRegistry(), and System.value.