Terraria: System.TimeZoneInfo.TryGetTimeZoneUsingId
TryGetTimeZoneUsingId()
static TimeZoneInfoResult System.TimeZoneInfo.TryGetTimeZoneUsingId (string id, bool dstDisabled, out TimeZoneInfo value, out Exception e, CachedData cachedData, bool alwaysFallbackToLocalMachine) inline static private
Definition at line 2152 of file TimeZoneInfo.cs.
    {
        TimeZoneInfoResult result = TimeZoneInfoResult.Success;
        e = null;
        if (cachedData._systemTimeZones != null && cachedData._systemTimeZones.TryGetValue(id, out var value2))
        {
            if (dstDisabled && value2._supportsDaylightSavingTime)
            {
                value = CreateCustomTimeZone(value2._id, value2._baseUtcOffset, value2._displayName, value2._standardDisplayName);
            }
            else
            {
                value = new TimeZoneInfo(value2._id, value2._baseUtcOffset, value2._displayName, value2._standardDisplayName, value2._daylightDisplayName, value2._adjustmentRules, disableDaylightSavingTime: false, value2.HasIanaId);
            }
            return result;
        }
        if (!cachedData._allSystemTimeZonesRead || alwaysFallbackToLocalMachine)
        {
            result = TryGetTimeZoneFromLocalMachine(id, dstDisabled, out value, out e, cachedData);
        }
        else
        {
            result = TimeZoneInfoResult.TimeZoneNotFoundException;
            value = null;
        }
        return result;
    }
References System.TimeZoneInfo.TimeZoneInfo(), System.TimeZoneInfo.CreateCustomTimeZone(), System.TimeZoneInfo.TryGetTimeZoneFromLocalMachine(), System.Collections.Generic.Dictionary< TKey, TValue >.TryGetValue(), and System.value.
Referenced by System.TimeZoneInfo.TryGetTimeZone().