Terraria: System.TimeZoneInfo.s_utcTimeZone
s_utcTimeZone
readonly TimeZoneInfo System.TimeZoneInfo.s_utcTimeZone = CreateUtcTimeZone() static private
Definition at line 951 of file TimeZoneInfo.cs.
Referenced by System.TimeZoneInfo.ConvertTime(), System.TimeZoneInfo.ConvertTimeBySystemTimeZoneId(), System.TimeZoneInfo.ConvertTimeFromUtc(), System.TimeZoneInfo.ConvertTimeToUtc(), System.TimeZoneInfo.ConvertTimeToUtc(), System.TimeZoneInfo.ConvertTimeToUtc(), System.TimeZoneInfo.GetAmbiguousTimeOffsets(), System.TimeZoneInfo.CachedData.GetCorrespondingKind(), System.TimeZoneInfo.GetUtcOffset(), System.TimeZoneInfo.IsAmbiguousTime(), and System.TimeZoneInfo.TryGetTimeZoneFromLocalMachine().