Terraria: System.TimeZoneInfo.GetAmbiguousTimeOffsets
GetAmbiguousTimeOffsets() [2/2]
TimeSpan[] System.TimeZoneInfo.GetAmbiguousTimeOffsets (DateTimeOffset dateTimeOffset) inline
Definition at line 981 of file TimeZoneInfo.cs.
    {
        if (!SupportsDaylightSavingTime)
        {
            throw new ArgumentException(SR.Argument_DateTimeOffsetIsNotAmbiguous, "dateTimeOffset");
        }
        DateTime dateTime = ConvertTime(dateTimeOffset, this).DateTime;
        bool flag = false;
        int? ruleIndex;
        AdjustmentRule adjustmentRuleForAmbiguousOffsets = GetAdjustmentRuleForAmbiguousOffsets(dateTime, out ruleIndex);
        if (adjustmentRuleForAmbiguousOffsets != null && adjustmentRuleForAmbiguousOffsets.HasDaylightSaving)
        {
            DaylightTimeStruct daylightTime = GetDaylightTime(dateTime.Year, adjustmentRuleForAmbiguousOffsets, ruleIndex);
            flag = GetIsAmbiguousTime(dateTime, adjustmentRuleForAmbiguousOffsets, daylightTime);
        }
        if (!flag)
        {
            throw new ArgumentException(SR.Argument_DateTimeOffsetIsNotAmbiguous, "dateTimeOffset");
        }
        TimeSpan[] array = new TimeSpan[2];
        TimeSpan timeSpan = _baseUtcOffset + adjustmentRuleForAmbiguousOffsets.BaseUtcOffsetDelta;
        if (adjustmentRuleForAmbiguousOffsets.DaylightDelta > TimeSpan.Zero)
        {
            array[0] = timeSpan;
            array[1] = timeSpan + adjustmentRuleForAmbiguousOffsets.DaylightDelta;
        }
        else
        {
            array[0] = timeSpan + adjustmentRuleForAmbiguousOffsets.DaylightDelta;
            array[1] = timeSpan;
        }
        return array;
    }
References System.TimeZoneInfo._baseUtcOffset, System.SR.Argument_DateTimeOffsetIsNotAmbiguous, System.array, System.TimeZoneInfo.ConvertTime(), System.Runtime.Serialization.Dictionary, System.TimeZoneInfo.GetAdjustmentRuleForAmbiguousOffsets(), System.TimeZoneInfo.GetDaylightTime(), System.TimeZoneInfo.GetIsAmbiguousTime(), System.TimeZoneInfo.SupportsDaylightSavingTime, and System.TimeSpan.Zero.