Terraria: System.TimeZoneInfo.GetIsDaylightSavingsFromUtc
GetIsDaylightSavingsFromUtc()
static bool System.TimeZoneInfo.GetIsDaylightSavingsFromUtc (DateTime time, int year, TimeSpan utc, AdjustmentRule rule, int? ruleIndex, out bool isAmbiguousLocalDst, TimeZoneInfo zone) inline static private
Definition at line 1747 of file TimeZoneInfo.cs.
    {
        isAmbiguousLocalDst = false;
        if (rule == null)
        {
            return false;
        }
        DaylightTimeStruct daylightTime = zone.GetDaylightTime(year, rule, ruleIndex);
        bool ignoreYearAdjustment = false;
        TimeSpan daylightSavingsStartOffsetFromUtc = zone.GetDaylightSavingsStartOffsetFromUtc(utc, rule, ruleIndex);
        DateTime dateTime;
        if (rule.IsStartDateMarkerForBeginningOfYear() && daylightTime.Start.Year > DateTime.MinValue.Year)
        {
            int? ruleIndex2;
            AdjustmentRule adjustmentRuleForTime = zone.GetAdjustmentRuleForTime(new DateTime(daylightTime.Start.Year - 1, 12, 31), out ruleIndex2);
            if (adjustmentRuleForTime != null && adjustmentRuleForTime.IsEndDateMarkerForEndOfYear())
            {
                dateTime = zone.GetDaylightTime(daylightTime.Start.Year - 1, adjustmentRuleForTime, ruleIndex2).Start - utc - adjustmentRuleForTime.BaseUtcOffsetDelta;
                ignoreYearAdjustment = true;
            }
            else
            {
                dateTime = new DateTime(daylightTime.Start.Year, 1, 1, 0, 0, 0) - daylightSavingsStartOffsetFromUtc;
            }
        }
        else
        {
            dateTime = daylightTime.Start - daylightSavingsStartOffsetFromUtc;
        }
        TimeSpan daylightSavingsEndOffsetFromUtc = GetDaylightSavingsEndOffsetFromUtc(utc, rule);
        DateTime dateTime2;
        if (rule.IsEndDateMarkerForEndOfYear() && daylightTime.End.Year < DateTime.MaxValue.Year)
        {
            int? ruleIndex3;
            AdjustmentRule adjustmentRuleForTime2 = zone.GetAdjustmentRuleForTime(new DateTime(daylightTime.End.Year + 1, 1, 1), out ruleIndex3);
            if (adjustmentRuleForTime2 != null && adjustmentRuleForTime2.IsStartDateMarkerForBeginningOfYear())
            {
                dateTime2 = ((!adjustmentRuleForTime2.IsEndDateMarkerForEndOfYear()) ? (zone.GetDaylightTime(daylightTime.End.Year + 1, adjustmentRuleForTime2, ruleIndex3).End - utc - adjustmentRuleForTime2.BaseUtcOffsetDelta - adjustmentRuleForTime2.DaylightDelta) : (new DateTime(daylightTime.End.Year + 1, 12, 31) - utc - adjustmentRuleForTime2.BaseUtcOffsetDelta - adjustmentRuleForTime2.DaylightDelta));
                ignoreYearAdjustment = true;
            }
            else
            {
                dateTime2 = new DateTime(daylightTime.End.Year + 1, 1, 1, 0, 0, 0).AddTicks(-1L) - daylightSavingsEndOffsetFromUtc;
            }
        }
        else
        {
            dateTime2 = daylightTime.End - daylightSavingsEndOffsetFromUtc;
        }
        DateTime dateTime3;
        DateTime dateTime4;
        if (daylightTime.Delta.Ticks > 0)
        {
            dateTime3 = dateTime2 - daylightTime.Delta;
            dateTime4 = dateTime2;
        }
        else
        {
            dateTime3 = dateTime;
            dateTime4 = dateTime - daylightTime.Delta;
        }
        bool flag = CheckIsDst(dateTime, time, dateTime2, ignoreYearAdjustment, rule);
        if (flag)
        {
            isAmbiguousLocalDst = time >= dateTime3 && time < dateTime4;
            if (!isAmbiguousLocalDst && dateTime3.Year != dateTime4.Year)
            {
                try
                {
                    DateTime dateTime5 = dateTime3.AddYears(1);
                    DateTime dateTime6 = dateTime4.AddYears(1);
                    isAmbiguousLocalDst = time >= dateTime5 && time < dateTime6;
                }
                catch (ArgumentOutOfRangeException)
                {
                }
                if (!isAmbiguousLocalDst)
                {
                    try
                    {
                        DateTime dateTime5 = dateTime3.AddYears(-1);
                        DateTime dateTime6 = dateTime4.AddYears(-1);
                        isAmbiguousLocalDst = time >= dateTime5 && time < dateTime6;
                    }
                    catch (ArgumentOutOfRangeException)
                    {
                    }
                }
            }
        }
        return flag;
    }
References System.TimeZoneInfo.CheckIsDst(), System.DateTime, System.Runtime.Serialization.Dictionary, System.TimeZoneInfo.GetDaylightSavingsEndOffsetFromUtc(), System.L, System.DateTime.MaxValue, System.DateTime.MinValue, and System.year.
Referenced by System.TimeZoneInfo.GetDateTimeNowUtcOffsetFromUtc(), and System.TimeZoneInfo.GetUtcOffsetFromUtc().