Terraria: System.TimeZoneInfo.GetAdjustmentRuleForAmbiguousOffsets
GetAdjustmentRuleForAmbiguousOffsets()
AdjustmentRule System.TimeZoneInfo.GetAdjustmentRuleForAmbiguousOffsets (DateTime adjustedTime, out int? ruleIndex) inline private
Definition at line 1063 of file TimeZoneInfo.cs.
    {
        AdjustmentRule adjustmentRuleForTime = GetAdjustmentRuleForTime(adjustedTime, out ruleIndex);
        if (adjustmentRuleForTime != null && adjustmentRuleForTime.NoDaylightTransitions && !adjustmentRuleForTime.HasDaylightSaving)
        {
            return GetPreviousAdjustmentRule(adjustmentRuleForTime, ruleIndex);
        }
        return adjustmentRuleForTime;
    }
References System.Runtime.Serialization.Dictionary, System.TimeZoneInfo.GetAdjustmentRuleForTime(), and System.TimeZoneInfo.GetPreviousAdjustmentRule().
Referenced by System.TimeZoneInfo.GetAmbiguousTimeOffsets(), and System.TimeZoneInfo.GetAmbiguousTimeOffsets().