Terraria: System.TimeZoneInfo.Equals
Equals() [2/3]
bool System.TimeZoneInfo.Equals ([NotNullWhen(true)] TimeZoneInfo? other) inline
Definition at line 1387 of file TimeZoneInfo.cs.
    {
        if (other != null && string.Equals(_id, other._id, StringComparison.OrdinalIgnoreCase))
        {
            return HasSameRules(other);
        }
        return false;
    }
References System.TimeZoneInfo._id, System.TimeZoneInfo.Equals(), System.TimeZoneInfo.HasSameRules(), and System.other.
Referenced by System.TimeZoneInfo.Equals(), System.TimeZoneInfo.Equals(), System.TimeZoneInfo.FindSystemTimeZoneById(), and System.TimeZoneInfo.TryGetTimeZoneFromLocalMachine().