Terraria: System.TimeZoneInfo.TryGetTimeZone
TryGetTimeZone()
static TimeZoneInfoResult System.TimeZoneInfo.TryGetTimeZone (string id, bool dstDisabled, out TimeZoneInfo value, out Exception e, CachedData cachedData, bool alwaysFallbackToLocalMachine = false) inline static private
Definition at line 2104 of file TimeZoneInfo.cs.
    {
        TimeZoneInfoResult timeZoneInfoResult = TryGetTimeZoneUsingId(id, dstDisabled, out value, out e, cachedData, alwaysFallbackToLocalMachine);
        if (timeZoneInfoResult != 0)
        {
            bool idIsIana;
            string alternativeId = GetAlternativeId(id, out idIsIana);
            if (alternativeId != null)
            {
                timeZoneInfoResult = TryGetTimeZoneUsingId(alternativeId, dstDisabled, out value, out e, cachedData, alwaysFallbackToLocalMachine);
                if (timeZoneInfoResult == TimeZoneInfoResult.Success)
                {
                    TimeZoneInfo timeZoneInfo = null;
                    if (value._equivalentZones == null)
                    {
                        timeZoneInfo = new TimeZoneInfo(id, value._baseUtcOffset, value._displayName, value._standardDisplayName, value._daylightDisplayName, value._adjustmentRules, dstDisabled && value._supportsDaylightSavingTime, idIsIana);
                        value._equivalentZones = new List<TimeZoneInfo>();
                        lock (value._equivalentZones)
{
                            value._equivalentZones.Add(timeZoneInfo);
                        }
                    }
                    else
                    {
                        foreach (TimeZoneInfo equivalentZone in value._equivalentZones)
{
                            if (equivalentZone.Id == id)
{
                                timeZoneInfo = equivalentZone;
                                break;
                            }
                        }
                        if (timeZoneInfo == null)
{
                            timeZoneInfo = new TimeZoneInfo(id, value._baseUtcOffset, value._displayName, value._standardDisplayName, value._daylightDisplayName, value._adjustmentRules, dstDisabled && value._supportsDaylightSavingTime, idIsIana);
                            lock (value._equivalentZones)
{
                                value._equivalentZones.Add(timeZoneInfo);
                            }
                        }
                    }
                    value = timeZoneInfo;
                }
            }
        }
        return timeZoneInfoResult;
    }
References System.TimeZoneInfo.TimeZoneInfo(), System.Runtime.Serialization.Dictionary, System.TimeZoneInfo.GetAlternativeId(), System.TimeZoneInfo.TryGetTimeZoneUsingId(), and System.value.
Referenced by System.TimeZoneInfo.FindSystemTimeZoneById(), System.TimeZoneInfo.GetLocalTimeZone(), and System.TimeZoneInfo.PopulateAllSystemTimeZones().