Terraria: System.TimeZoneInfo.GetIsAmbiguousTime
GetIsAmbiguousTime()
static bool System.TimeZoneInfo.GetIsAmbiguousTime (DateTime time, AdjustmentRule rule, DaylightTimeStruct daylightTime) inline static private
Definition at line 1879 of file TimeZoneInfo.cs.
    {
        bool result = false;
        if (rule == null || rule.DaylightDelta == TimeSpan.Zero)
        {
            return result;
        }
        DateTime dateTime;
        DateTime dateTime2;
        if (rule.DaylightDelta > TimeSpan.Zero)
        {
            if (rule.IsEndDateMarkerForEndOfYear())
            {
                return false;
            }
            dateTime = daylightTime.End;
            dateTime2 = daylightTime.End - rule.DaylightDelta;
        }
        else
        {
            if (rule.IsStartDateMarkerForBeginningOfYear())
            {
                return false;
            }
            dateTime = daylightTime.Start;
            dateTime2 = daylightTime.Start + rule.DaylightDelta;
        }
        result = time >= dateTime2 && time < dateTime;
        if (!result && dateTime.Year != dateTime2.Year)
        {
            try
            {
                DateTime dateTime3 = dateTime.AddYears(1);
                DateTime dateTime4 = dateTime2.AddYears(1);
                result = time >= dateTime4 && time < dateTime3;
            }
            catch (ArgumentOutOfRangeException)
            {
            }
            if (!result)
            {
                try
                {
                    DateTime dateTime3 = dateTime.AddYears(-1);
                    DateTime dateTime4 = dateTime2.AddYears(-1);
                    result = time >= dateTime4 && time < dateTime3;
                }
                catch (ArgumentOutOfRangeException)
                {
                }
            }
        }
        return result;
    }
References System.Runtime.Serialization.Dictionary, and System.TimeSpan.Zero.
Referenced by System.TimeZoneInfo.GetAmbiguousTimeOffsets(), System.TimeZoneInfo.GetAmbiguousTimeOffsets(), System.TimeZoneInfo.GetIsDaylightSavings(), and System.TimeZoneInfo.IsAmbiguousTime().