Terraria: System.TimeZoneInfo.ValidateTimeZoneInfo
ValidateTimeZoneInfo()
static void System.TimeZoneInfo.ValidateTimeZoneInfo (string id, TimeSpan baseUtcOffset, AdjustmentRule[] adjustmentRules, out bool adjustmentRulesSupportDst) inline static private
Definition at line 2210 of file TimeZoneInfo.cs.
    {
        if (id == null)
        {
            throw new ArgumentNullException("id");
        }
        if (id.Length == 0)
        {
            throw new ArgumentException(SR.Format(SR.Argument_InvalidId, id), "id");
        }
        if (UtcOffsetOutOfRange(baseUtcOffset))
        {
            throw new ArgumentOutOfRangeException("baseUtcOffset", SR.ArgumentOutOfRange_UtcOffset);
        }
        if (baseUtcOffset.Ticks % 600000000 != 0L)
        {
            throw new ArgumentException(SR.Argument_TimeSpanHasSeconds, "baseUtcOffset");
        }
        adjustmentRulesSupportDst = false;
        if (adjustmentRules == null || adjustmentRules.Length == 0)
        {
            return;
        }
        adjustmentRulesSupportDst = true;
        AdjustmentRule adjustmentRule = null;
        AdjustmentRule adjustmentRule2 = null;
        for (int i = 0; i < adjustmentRules.Length; i++)
        {
            adjustmentRule = adjustmentRule2;
            adjustmentRule2 = adjustmentRules[i];
            if (adjustmentRule2 == null)
            {
                throw new InvalidTimeZoneException(SR.Argument_AdjustmentRulesNoNulls);
            }
            if (!IsValidAdjustmentRuleOffset(baseUtcOffset, adjustmentRule2))
            {
                throw new InvalidTimeZoneException(SR.ArgumentOutOfRange_UtcOffsetAndDaylightDelta);
            }
            if (adjustmentRule != null && adjustmentRule2.DateStart <= adjustmentRule.DateEnd)
            {
                throw new InvalidTimeZoneException(SR.Argument_AdjustmentRulesOutOfOrder);
            }
        }
    }
References System.SR.Argument_AdjustmentRulesNoNulls, System.SR.Argument_AdjustmentRulesOutOfOrder, System.SR.Argument_InvalidId, System.SR.Argument_TimeSpanHasSeconds, System.SR.ArgumentOutOfRange_UtcOffset, System.SR.ArgumentOutOfRange_UtcOffsetAndDaylightDelta, System.Runtime.Serialization.Dictionary, System.SR.Format(), System.TimeZoneInfo.InvalidTimeZoneException, System.TimeZoneInfo.IsValidAdjustmentRuleOffset(), System.L, and System.TimeZoneInfo.UtcOffsetOutOfRange().
Referenced by System.TimeZoneInfo.TimeZoneInfo(), System.TimeZoneInfo.TimeZoneInfo(), and System.TimeZoneInfo.OnDeserialization().