Terraria: System.TimeZoneInfo.TryCompareTimeZoneInformationToRegistry
TryCompareTimeZoneInformationToRegistry()
static bool System.TimeZoneInfo.TryCompareTimeZoneInformationToRegistry (in Interop::Kernel32::TIME_ZONE_INFORMATION timeZone, string id, out bool dstDisabled) inline static private
Definition at line 2701 of file TimeZoneInfo.cs.
    {
        dstDisabled = false;
        using RegistryKey registryKey = Registry.LocalMachine.OpenSubKey("SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Time Zones\\" + id, writable: false);
        if (registryKey == null)
        {
            return false;
        }
        if (!TryGetTimeZoneEntryFromRegistry(registryKey, "TZI", out var dtzi))
        {
            return false;
        }
        if (!TryCompareStandardDate(in timeZone, in dtzi))
        {
            return false;
        }
        bool flag = dstDisabled || CheckDaylightSavingTimeNotSupported(in timeZone) || (timeZone.DaylightBias == dtzi.DaylightBias && timeZone.DaylightDate.Equals(in dtzi.DaylightDate));
        if (flag)
        {
            string a = registryKey.GetValue("Std", string.Empty) as string;
            flag = string.Equals(a, timeZone.GetStandardName(), StringComparison.Ordinal);
        }
        return flag;
    }
References System.TimeZoneInfo.CheckDaylightSavingTimeNotSupported(), System.Runtime.Serialization.Dictionary, Internal.Win32.Registry.LocalMachine, System.TimeZoneInfo.TryCompareStandardDate(), and System.TimeZoneInfo.TryGetTimeZoneEntryFromRegistry().
Referenced by System.TimeZoneInfo.FindIdFromTimeZoneInformation().