Terraria: System.TimeZoneInfo.TimeZoneInfo
TimeZoneInfo() [1/3]
System.TimeZoneInfo.TimeZoneInfo (string id, TimeSpan baseUtcOffset, string displayName, string standardDisplayName, string daylightDisplayName, AdjustmentRule[] adjustmentRules, bool disableDaylightSavingTime, bool hasIanaId = false) inline private
Definition at line 1469 of file TimeZoneInfo.cs.
    {
        ValidateTimeZoneInfo(id, baseUtcOffset, adjustmentRules, out var adjustmentRulesSupportDst);
        _id = id;
        _baseUtcOffset = baseUtcOffset;
        _displayName = displayName;
        _standardDisplayName = standardDisplayName;
        _daylightDisplayName = (disableDaylightSavingTime ? null : daylightDisplayName);
        _supportsDaylightSavingTime = adjustmentRulesSupportDst && !disableDaylightSavingTime;
        _adjustmentRules = adjustmentRules;
        HasIanaId = _id.Equals("UTC", StringComparison.OrdinalIgnoreCase) || hasIanaId;
    }
References System.TimeZoneInfo._adjustmentRules, System.TimeZoneInfo._baseUtcOffset, System.TimeZoneInfo._daylightDisplayName, System.TimeZoneInfo._displayName, System.TimeZoneInfo._id, System.TimeZoneInfo._standardDisplayName, System.TimeZoneInfo._supportsDaylightSavingTime, System.Runtime.Serialization.Dictionary, System.TimeZoneInfo.HasIanaId, and System.TimeZoneInfo.ValidateTimeZoneInfo().
Referenced by System.TimeZoneInfo.CreateCustomTimeZone(), System.TimeZoneInfo.CreateCustomTimeZone(), System.TimeZoneInfo.CachedData.CreateLocal(), System.TimeZoneInfo.StringSerializer.GetDeserializedTimeZoneInfo(), System.TimeZoneInfo.GetLocalTimeZoneFromWin32Data(), System.TimeZoneInfo.TryGetTimeZone(), System.TimeZoneInfo.TryGetTimeZoneFromLocalMachine(), System.TimeZoneInfo.TryGetTimeZoneFromLocalMachine(), and System.TimeZoneInfo.TryGetTimeZoneUsingId().