Terraria: System.TimeZoneInfo.GetIsDaylightSavings
GetIsDaylightSavings()
static bool System.TimeZoneInfo.GetIsDaylightSavings (DateTime time, AdjustmentRule rule, DaylightTimeStruct daylightTime) inline static private
Definition at line 1705 of file TimeZoneInfo.cs.
    {
        if (rule == null)
        {
            return false;
        }
        DateTime startTime;
        DateTime endTime;
        if (time.Kind == DateTimeKind.Local)
        {
            startTime = (rule.IsStartDateMarkerForBeginningOfYear() ? new DateTime(daylightTime.Start.Year, 1, 1, 0, 0, 0) : (daylightTime.Start + daylightTime.Delta));
            endTime = (rule.IsEndDateMarkerForEndOfYear() ? new DateTime(daylightTime.End.Year + 1, 1, 1, 0, 0, 0).AddTicks(-1L) : daylightTime.End);
        }
        else
        {
            bool flag = rule.DaylightDelta > TimeSpan.Zero;
            startTime = (rule.IsStartDateMarkerForBeginningOfYear() ? new DateTime(daylightTime.Start.Year, 1, 1, 0, 0, 0) : (daylightTime.Start + (flag ? rule.DaylightDelta : TimeSpan.Zero)));
            endTime = (rule.IsEndDateMarkerForEndOfYear() ? new DateTime(daylightTime.End.Year + 1, 1, 1, 0, 0, 0).AddTicks(-1L) : (daylightTime.End + (flag ? (-rule.DaylightDelta) : TimeSpan.Zero)));
        }
        bool flag2 = CheckIsDst(startTime, time, endTime, ignoreYearAdjustment: false, rule);
        if (flag2 && time.Kind == DateTimeKind.Local && GetIsAmbiguousTime(time, rule, daylightTime))
        {
            flag2 = time.IsAmbiguousDaylightSavingTime();
        }
        return flag2;
    }
References System.TimeZoneInfo.CheckIsDst(), System.DateTime, System.Runtime.Serialization.Dictionary, System.TimeZoneInfo.GetIsAmbiguousTime(), System.DateTime.IsAmbiguousDaylightSavingTime(), System.DateTime.Kind, System.L, and System.TimeSpan.Zero.
Referenced by System.TimeZoneInfo.ConvertTime(), System.TimeZoneInfo.GetUtcOffset(), and System.TimeZoneInfo.IsDaylightSavingTime().