Terraria: System.TimeZoneInfo.s_cachedData
s_cachedData
CachedData System.TimeZoneInfo.s_cachedData = new CachedData() static private
Definition at line 953 of file TimeZoneInfo.cs.
Referenced by System.TimeZoneInfo.ClearCachedData(), System.TimeZoneInfo.ConvertTime(), System.TimeZoneInfo.ConvertTime(), System.TimeZoneInfo.ConvertTime(), System.TimeZoneInfo.ConvertTimeBySystemTimeZoneId(), System.TimeZoneInfo.ConvertTimeFromUtc(), System.TimeZoneInfo.ConvertTimeToUtc(), System.TimeZoneInfo.ConvertTimeToUtc(), System.TimeZoneInfo.ConvertTimeToUtc(), System.TimeZoneInfo.FindSystemTimeZoneById(), System.TimeZoneInfo.GetAmbiguousTimeOffsets(), System.TimeZoneInfo.GetDateTimeNowUtcOffsetFromUtc(), System.TimeZoneInfo.GetLocalUtcOffset(), System.TimeZoneInfo.GetSystemTimeZones(), System.TimeZoneInfo.GetUtcOffset(), System.TimeZoneInfo.GetUtcOffset(), System.TimeZoneInfo.IsAmbiguousTime(), System.TimeZoneInfo.IsDaylightSavingTime(), System.TimeZoneInfo.IsDaylightSavingTime(), and System.TimeZoneInfo.IsInvalidTime().