Terraria: System.TimeZoneInfo.GetLocalTimeZoneFromWin32Data
GetLocalTimeZoneFromWin32Data()
static TimeZoneInfo System.TimeZoneInfo.GetLocalTimeZoneFromWin32Data (in Interop::Kernel32::TIME_ZONE_INFORMATION timeZoneInformation, bool dstDisabled) inline static private
Definition at line 2487 of file TimeZoneInfo.cs.
    {
        try
        {
            return new TimeZoneInfo(in timeZoneInformation, dstDisabled);
        }
        catch (ArgumentException)
        {
        }
        catch (InvalidTimeZoneException)
        {
        }
        if (!dstDisabled)
        {
            try
            {
                return new TimeZoneInfo(in timeZoneInformation, dstDisabled: true);
            }
            catch (ArgumentException)
            {
            }
            catch (InvalidTimeZoneException)
            {
            }
        }
        return CreateCustomTimeZone("Local", TimeSpan.Zero, "Local", "Local");
    }
References System.TimeZoneInfo.TimeZoneInfo(), System.TimeZoneInfo.CreateCustomTimeZone(), and System.TimeSpan.Zero.
Referenced by System.TimeZoneInfo.CachedData.GetCurrentOneYearLocal(), and System.TimeZoneInfo.GetLocalTimeZone().