Terraria: System.TimeZoneInfo.GetLocalizedNameByMuiNativeResource
GetLocalizedNameByMuiNativeResource()
static string System.TimeZoneInfo.GetLocalizedNameByMuiNativeResource (string resource) inline static private
Definition at line 2726 of file TimeZoneInfo.cs.
    {
        if (string.IsNullOrEmpty(resource) || (GlobalizationMode.Invariant && GlobalizationMode.PredefinedCulturesOnly))
        {
            return string.Empty;
        }
        string[] array = resource.Split(',');
        if (array.Length != 2)
        {
            return string.Empty;
        }
        if (!int.TryParse(array[1], NumberStyles.Integer, CultureInfo.InvariantCulture, out var result))
        {
            return string.Empty;
        }
        result = -result;
        CultureInfo cultureInfo = CultureInfo.CurrentUICulture;
        string systemDirectory = Environment.SystemDirectory;
        string path = $"{array[0].AsSpan().TrimStart('@')}.mui";
        try
        {
            while (cultureInfo.Name.Length != 0)
            {
                string text = Path.Join(systemDirectory, cultureInfo.Name, path);
                if (File.Exists(text))
                {
                    return GetLocalizedNameByNativeResource(text, result);
                }
                cultureInfo = cultureInfo.Parent;
            }
        }
        catch (ArgumentException)
        {
        }
        return string.Empty;
    }
References System.array, System.Globalization.CultureInfo.CurrentUICulture, System.IO.File.Exists(), System.TimeZoneInfo.GetLocalizedNameByNativeResource(), System.Globalization.GlobalizationMode.Invariant, System.Globalization.CultureInfo.InvariantCulture, System.IO.Path.Join(), System.Globalization.GlobalizationMode.PredefinedCulturesOnly, System.Environment.SystemDirectory, and System.text.
Referenced by System.TimeZoneInfo.GetLocalizedNamesByRegistryKey(), and System.TimeZoneInfo.GetUtcStandardDisplayName().