Terraria: System.TimeZoneInfo.GetLocalizedNameByNativeResource
GetLocalizedNameByNativeResource()
static unsafe string System.TimeZoneInfo.GetLocalizedNameByNativeResource (string filePath, int resource) inline static private
Definition at line 2763 of file TimeZoneInfo.cs.
    {
        IntPtr intPtr = IntPtr.Zero;
        try
        {
            intPtr = Interop.Kernel32.LoadLibraryEx(filePath, IntPtr.Zero, 2);
            if (intPtr != IntPtr.Zero)
            {
                char* ptr = stackalloc char[500];
                int num = Interop.User32.LoadString(intPtr, (uint)resource, ptr, 500);
                if (num != 0)
                {
                    return new string(ptr, 0, num);
                }
            }
        }
        finally
        {
            if (intPtr != IntPtr.Zero)
            {
                Interop.Kernel32.FreeLibrary(intPtr);
            }
        }
        return string.Empty;
    }
References Interop.Kernel32.FreeLibrary(), Interop.Kernel32.LoadLibraryEx(), Interop.User32.LoadString(), and System.IntPtr.Zero.
Referenced by System.TimeZoneInfo.GetLocalizedNameByMuiNativeResource().