Terraria: System.TimeZoneInfo.GetLocalTimeZone
GetLocalTimeZone()
static TimeZoneInfo System.TimeZoneInfo.GetLocalTimeZone (CachedData cachedData) inline static private
Definition at line 2464 of file TimeZoneInfo.cs.
    {
        Interop.Kernel32.TIME_DYNAMIC_ZONE_INFORMATION pTimeZoneInformation;
        uint dynamicTimeZoneInformation = Interop.Kernel32.GetDynamicTimeZoneInformation(out pTimeZoneInformation);
        if (dynamicTimeZoneInformation == uint.MaxValue)
        {
            return CreateCustomTimeZone("Local", TimeSpan.Zero, "Local", "Local");
        }
        string timeZoneKeyName = pTimeZoneInformation.GetTimeZoneKeyName();
        if (timeZoneKeyName.Length != 0 && TryGetTimeZone(timeZoneKeyName, pTimeZoneInformation.DynamicDaylightTimeDisabled != 0, out var value, out var e, cachedData) == TimeZoneInfoResult.Success)
        {
            return value;
        }
        Interop.Kernel32.TIME_ZONE_INFORMATION timeZone = new Interop.Kernel32.TIME_ZONE_INFORMATION(in pTimeZoneInformation);
        bool dstDisabled;
        string text = FindIdFromTimeZoneInformation(in timeZone, out dstDisabled);
        if (text != null && TryGetTimeZone(text, dstDisabled, out var value2, out e, cachedData) == TimeZoneInfoResult.Success)
        {
            return value2;
        }
        return GetLocalTimeZoneFromWin32Data(in timeZone, dstDisabled);
    }
References System.TimeZoneInfo.CreateCustomTimeZone(), System.Runtime.Serialization.Dictionary, System.TimeZoneInfo.FindIdFromTimeZoneInformation(), Interop.Kernel32.GetDynamicTimeZoneInformation(), System.TimeZoneInfo.GetLocalTimeZoneFromWin32Data(), System.text, System.TimeZoneInfo.TryGetTimeZone(), System.value, and System.TimeSpan.Zero.
Referenced by System.TimeZoneInfo.CachedData.CreateLocal().