Terraria: System.TimeZoneInfo.GetDaylightTime
GetDaylightTime()
DaylightTimeStruct System.TimeZoneInfo.GetDaylightTime (int year, AdjustmentRule rule, int? ruleIndex) inline private
Definition at line 1686 of file TimeZoneInfo.cs.
    {
        TimeSpan daylightDelta = rule.DaylightDelta;
        DateTime start;
        DateTime end;
        if (rule.NoDaylightTransitions)
        {
            AdjustmentRule previousAdjustmentRule = GetPreviousAdjustmentRule(rule, ruleIndex);
            start = ConvertFromUtc(rule.DateStart, previousAdjustmentRule.DaylightDelta, previousAdjustmentRule.BaseUtcOffsetDelta);
            end = ConvertFromUtc(rule.DateEnd, rule.DaylightDelta, rule.BaseUtcOffsetDelta);
        }
        else
        {
            start = TransitionTimeToDateTime(year, rule.DaylightTransitionStart);
            end = TransitionTimeToDateTime(year, rule.DaylightTransitionEnd);
        }
        return new DaylightTimeStruct(start, end, daylightDelta);
    }
References System.TimeZoneInfo.ConvertFromUtc(), System.TimeZoneInfo.GetPreviousAdjustmentRule(), System.start, System.TimeZoneInfo.TransitionTimeToDateTime(), and System.year.
Referenced by System.TimeZoneInfo.GetAmbiguousTimeOffsets(), System.TimeZoneInfo.GetAmbiguousTimeOffsets(), System.TimeZoneInfo.IsAmbiguousTime(), System.TimeZoneInfo.IsDaylightSavingTime(), and System.TimeZoneInfo.IsInvalidTime().