Terraria: System.TimeZoneInfo.TransitionTimeFromTimeZoneInformation
TransitionTimeFromTimeZoneInformation()
static bool System.TimeZoneInfo.TransitionTimeFromTimeZoneInformation (in Interop::Kernel32::REG_TZI_FORMAT timeZoneInformation, out TransitionTime transitionTime, bool readStartDate) inline static private
Definition at line 2564 of file TimeZoneInfo.cs.
    {
        if (timeZoneInformation.StandardDate.Month == 0)
        {
            transitionTime = default(TransitionTime);
            return false;
        }
        if (readStartDate)
        {
            if (timeZoneInformation.DaylightDate.Year == 0)
            {
                transitionTime = TransitionTime.CreateFloatingDateRule(new DateTime(1, 1, 1, timeZoneInformation.DaylightDate.Hour, timeZoneInformation.DaylightDate.Minute, timeZoneInformation.DaylightDate.Second, timeZoneInformation.DaylightDate.Milliseconds), timeZoneInformation.DaylightDate.Month, timeZoneInformation.DaylightDate.Day, (DayOfWeek)timeZoneInformation.DaylightDate.DayOfWeek);
            }
            else
            {
                transitionTime = TransitionTime.CreateFixedDateRule(new DateTime(1, 1, 1, timeZoneInformation.DaylightDate.Hour, timeZoneInformation.DaylightDate.Minute, timeZoneInformation.DaylightDate.Second, timeZoneInformation.DaylightDate.Milliseconds), timeZoneInformation.DaylightDate.Month, timeZoneInformation.DaylightDate.Day);
            }
        }
        else if (timeZoneInformation.StandardDate.Year == 0)
        {
            transitionTime = TransitionTime.CreateFloatingDateRule(new DateTime(1, 1, 1, timeZoneInformation.StandardDate.Hour, timeZoneInformation.StandardDate.Minute, timeZoneInformation.StandardDate.Second, timeZoneInformation.StandardDate.Milliseconds), timeZoneInformation.StandardDate.Month, timeZoneInformation.StandardDate.Day, (DayOfWeek)timeZoneInformation.StandardDate.DayOfWeek);
        }
        else
        {
            transitionTime = TransitionTime.CreateFixedDateRule(new DateTime(1, 1, 1, timeZoneInformation.StandardDate.Hour, timeZoneInformation.StandardDate.Minute, timeZoneInformation.StandardDate.Second, timeZoneInformation.StandardDate.Milliseconds), timeZoneInformation.StandardDate.Month, timeZoneInformation.StandardDate.Day);
        }
        return true;
    }
References System.TimeZoneInfo.TransitionTime.CreateFixedDateRule(), System.TimeZoneInfo.TransitionTime.CreateFloatingDateRule(), and System.DateTime.
Referenced by System.TimeZoneInfo.CreateAdjustmentRuleFromTimeZoneInformation().