Terraria: System.TimeZoneInfo.ConvertTime
ConvertTime() [4/5]
static DateTime System.TimeZoneInfo.ConvertTime (DateTime dateTime, TimeZoneInfo sourceTimeZone, TimeZoneInfo destinationTimeZone, TimeZoneInfoOptions flags, CachedData cachedData) inline static private
Definition at line 1309 of file TimeZoneInfo.cs.
    {
        if (sourceTimeZone == null)
        {
            throw new ArgumentNullException("sourceTimeZone");
        }
        if (destinationTimeZone == null)
        {
            throw new ArgumentNullException("destinationTimeZone");
        }
        DateTimeKind correspondingKind = cachedData.GetCorrespondingKind(sourceTimeZone);
        if ((flags & TimeZoneInfoOptions.NoThrowOnInvalidTime) == 0 && dateTime.Kind != 0 && dateTime.Kind != correspondingKind)
        {
            throw new ArgumentException(SR.Argument_ConvertMismatch, "sourceTimeZone");
        }
        int? ruleIndex;
        AdjustmentRule adjustmentRuleForTime = sourceTimeZone.GetAdjustmentRuleForTime(dateTime, out ruleIndex);
        TimeSpan baseUtcOffset = sourceTimeZone.BaseUtcOffset;
        if (adjustmentRuleForTime != null)
        {
            baseUtcOffset += adjustmentRuleForTime.BaseUtcOffsetDelta;
            if (adjustmentRuleForTime.HasDaylightSaving)
            {
                bool flag = false;
                DaylightTimeStruct daylightTime = sourceTimeZone.GetDaylightTime(dateTime.Year, adjustmentRuleForTime, ruleIndex);
                if ((flags & TimeZoneInfoOptions.NoThrowOnInvalidTime) == 0 && GetIsInvalidTime(dateTime, adjustmentRuleForTime, daylightTime))
                {
                    throw new ArgumentException(SR.Argument_DateTimeIsInvalid, "dateTime");
                }
                flag = GetIsDaylightSavings(dateTime, adjustmentRuleForTime, daylightTime);
                baseUtcOffset += (flag ? adjustmentRuleForTime.DaylightDelta : TimeSpan.Zero);
            }
        }
        DateTimeKind correspondingKind2 = cachedData.GetCorrespondingKind(destinationTimeZone);
        if (dateTime.Kind != 0 && correspondingKind != 0 && correspondingKind == correspondingKind2)
        {
            return dateTime;
        }
        long ticks = dateTime.Ticks - baseUtcOffset.Ticks;
        bool isAmbiguousLocalDst;
        DateTime dateTime2 = ConvertUtcToTimeZone(ticks, destinationTimeZone, out isAmbiguousLocalDst);
        if (correspondingKind2 == DateTimeKind.Local)
        {
            return new DateTime(dateTime2.Ticks, DateTimeKind.Local, isAmbiguousLocalDst);
        }
        return new DateTime(dateTime2.Ticks, correspondingKind2);
    }
References System.SR.Argument_ConvertMismatch, System.SR.Argument_DateTimeIsInvalid, System.TimeZoneInfo.ConvertUtcToTimeZone(), System.DateTime, System.Runtime.Serialization.Dictionary, System.TimeZoneInfo.GetIsDaylightSavings(), System.TimeZoneInfo.GetIsInvalidTime(), and System.TimeSpan.Zero.