Terraria: System.Net.HttpListenerResponse.ComputeCookies
ComputeCookies()
void System.Net.HttpListenerResponse.ComputeCookies () inline private
Definition at line 319 of file HttpListenerResponse.cs.
    {
        if (System.Net.NetEventSource.Log.IsEnabled())
        {
            System.Net.NetEventSource.Info(this, FormattableStringFactory.Create("Entering Set-Cookie: {0}, Set-Cookie2: {1}", Headers[HttpResponseHeader.SetCookie], Headers["Set-Cookie2"]), "ComputeCookies");
        }
        if (_cookies != null)
        {
            string text = null;
            string text2 = null;
            for (int i = 0; i < _cookies.Count; i++)
            {
                Cookie cookie = _cookies[i];
                string text3 = cookie.ToServerString();
                if (text3 != null && text3.Length != 0)
                {
                    if (System.Net.NetEventSource.Log.IsEnabled())
                    {
                        System.Net.NetEventSource.Info(this, $"Now looking at index:{i} cookie: {cookie}", "ComputeCookies");
                    }
                    if (cookie.IsRfc2965Variant())
                    {
                        text = ((text == null) ? text3 : (text + ", " + text3));
                    }
                    else
                    {
                        text2 = ((text2 == null) ? text3 : (text2 + ", " + text3));
                    }
                }
            }
            if (!string.IsNullOrEmpty(text2))
            {
                Headers.Set("Set-Cookie", text2);
                if (string.IsNullOrEmpty(text))
                {
                    Headers.Remove("Set-Cookie2");
                }
            }
            if (!string.IsNullOrEmpty(text))
            {
                Headers.Set("Set-Cookie2", text);
                if (string.IsNullOrEmpty(text2))
                {
                    Headers.Remove("Set-Cookie");
                }
            }
        }
        if (System.Net.NetEventSource.Log.IsEnabled())
        {
            System.Net.NetEventSource.Info(this, FormattableStringFactory.Create("Exiting Set-Cookie: {0} Set-Cookie2: {1}", Headers[HttpResponseHeader.SetCookie], Headers["Set-Cookie2"]), "ComputeCookies");
        }
    }
References System.Net.HttpListenerResponse._cookies, System.Net.CookieCollection.Count, System.Runtime.CompilerServices.FormattableStringFactory.Create(), System.Net.NetEventSource.Info(), System.Net.NetEventSource.Log, System.Collections.Generic.Dictionary< TKey, TValue >.Remove(), and System.text.
Referenced by System.Net.HttpListenerResponse.ComputeCoreHeaders().