Terraria: System.Net.HttpListenerResponse.Close
Close() [2/2]
void System.Net.HttpListenerResponse.Close (byte[] responseEntity, bool willBlock) inline
Definition at line 481 of file HttpListenerResponse.cs.
    {
        CheckDisposed();
        if (responseEntity == null)
        {
            throw new ArgumentNullException("responseEntity");
        }
        if (System.Net.NetEventSource.Log.IsEnabled())
        {
            System.Net.NetEventSource.Info(this, $"ResponseState:{_responseState}, BoundaryType:{_boundaryType}, ContentLength:{_contentLength}", "Close");
        }
        if (!SentHeaders && _boundaryType != BoundaryType.Chunked)
        {
            ContentLength64 = responseEntity.Length;
        }
        EnsureResponseStream();
        if (willBlock)
        {
            try
            {
                _responseStream.Write(responseEntity, 0, responseEntity.Length);
                return;
            }
            catch (Win32Exception)
            {
                return;
            }
            finally
            {
                _responseStream.Close();
                _responseState = ResponseState.Closed;
                HttpListenerContext.Close();
            }
        }
        _responseStream.BeginWrite(responseEntity, 0, responseEntity.Length, NonBlockingCloseCallback, null);
    }
References System.Net.HttpListenerResponse._boundaryType, System.Net.HttpListenerResponse._responseState, System.Net.HttpListenerResponse._responseStream, System.Net.HttpResponseStream.BeginWrite(), System.Net.HttpListenerResponse.CheckDisposed(), System.Net.HttpListenerContext.Close(), System.IO.Stream.Close(), System.Net.HttpListenerResponse.ContentLength64, System.Net.HttpListenerResponse.EnsureResponseStream(), System.Net.NetEventSource.Info(), System.Net.NetEventSource.Log, System.Net.HttpListenerResponse.NonBlockingCloseCallback(), System.Net.HttpListenerResponse.SentHeaders, and System.Net.HttpResponseStream.Write().