Terraria: System.Net.WebSockets.WebSocket.CreateFromStream
CreateFromStream() [1/2]
static WebSocket System.Net.WebSockets.WebSocket.CreateFromStream (Stream stream, bool isServer, string? subProtocol, TimeSpan keepAliveInterval) inline static inherited
Definition at line 130 of file WebSocket.cs.
    {
        if (stream == null)
        {
            throw new ArgumentNullException("stream");
        }
        if (!stream.CanRead || !stream.CanWrite)
        {
            throw new ArgumentException((!stream.CanRead) ? System.SR.NotReadableStream : System.SR.NotWriteableStream, "stream");
        }
        if (subProtocol != null)
        {
            WebSocketValidate.ValidateSubprotocol(subProtocol);
        }
        if (keepAliveInterval != Timeout.InfiniteTimeSpan && keepAliveInterval < TimeSpan.Zero)
        {
            throw new ArgumentOutOfRangeException("keepAliveInterval", keepAliveInterval, System.SR.Format(System.SR.net_WebSockets_ArgumentOutOfRange_TooSmall, 0));
        }
        return new ManagedWebSocket(stream, isServer, subProtocol, keepAliveInterval);
    }
References System.SR.Format(), System.Threading.Timeout.InfiniteTimeSpan, System.SR.net_WebSockets_ArgumentOutOfRange_TooSmall, System.SR.NotReadableStream, System.SR.NotWriteableStream, System.stream, System.Net.WebSockets.WebSocketValidate.ValidateSubprotocol(), and System.TimeSpan.Zero.
Referenced by System.Net.WebSockets.WebSocketHandle.ConnectAsync().