Terraria: System.Net.WebSockets.WebSocket.IsStateTerminal
IsStateTerminal()
static bool System.Net.WebSockets.WebSocket.IsStateTerminal (WebSocketState state) inline static protected inherited
Definition at line 99 of file WebSocket.cs.
    {
        if (state != WebSocketState.Closed)
        {
            return state == WebSocketState.Aborted;
        }
        return true;
    }
References System.state.
Referenced by System.Net.WebSockets.WebSocketBase.Abort(), System.Net.WebSockets.WebSocketBase.CloseAsyncCore(), System.Net.WebSockets.WebSocketBase.CloseOutputAsyncCore(), System.Net.WebSockets.WebSocketBase.Dispose(), System.Net.WebSockets.WebSocketBase.OnCloseOutputCompleted(), System.Net.WebSockets.WebSocketBase.StartOnCloseCompleted(), and System.Net.WebSockets.WebSocketBase.StartOnCloseReceived().