Terraria: System.Net.HttpListenerResponse.SerializeHeaders
SerializeHeaders()
unsafe List< GCHandle > System.Net.HttpListenerResponse.SerializeHeaders (ref global::Interop::HttpApi::HTTP_RESPONSE_HEADERS headers, bool isWebSocketHandshake) inline private
Definition at line 730 of file HttpListenerResponse.cs.
    {
        global::Interop.HttpApi.HTTP_UNKNOWN_HEADER[] array = null;
        if (System.Net.NetEventSource.Log.IsEnabled())
        {
            System.Net.NetEventSource.Info(this, "SerializeHeaders(HTTP_RESPONSE_HEADERS)", "SerializeHeaders");
        }
        if (Headers.Count == 0)
        {
            return null;
        }
        byte[] array2 = null;
        List<GCHandle> list = new List<GCHandle>();
        int num = 0;
        for (int i = 0; i < Headers.Count; i++)
        {
            string key = Headers.GetKey(i);
            int num2 = global::Interop.HttpApi.HTTP_RESPONSE_HEADER_ID.IndexOfKnownHeader(key);
            if (num2 == 27 || (isWebSocketHandshake && num2 == 1))
            {
                num2 = -1;
            }
            if (num2 == -1)
            {
                string[] values = Headers.GetValues(i);
                num += values.Length;
            }
        }
        try
        {
            fixed (global::Interop.HttpApi.HTTP_KNOWN_HEADER* ptr = &headers.KnownHeaders)
            {
                for (int j = 0; j < Headers.Count; j++)
                {
                    string key = Headers.GetKey(j);
                    string text = Headers.Get(j);
                    int num2 = global::Interop.HttpApi.HTTP_RESPONSE_HEADER_ID.IndexOfKnownHeader(key);
                    if (num2 == 27 || (isWebSocketHandshake && num2 == 1))
                    {
                        num2 = -1;
                    }
                    if (System.Net.NetEventSource.Log.IsEnabled())
                    {
                        System.Net.NetEventSource.Info(this, $"index={j},headers.count={Headers.Count},headerName:{key},lookup:{num2} headerValue:{text}", "SerializeHeaders");
                    }
                    if (num2 == -1)
                    {
                        if (array == null)
{
                            array = new global::Interop.HttpApi.HTTP_UNKNOWN_HEADER[num];
                            GCHandle item = GCHandle.Alloc(array, GCHandleType.Pinned);
                            list.Add(item);
                            headers.pUnknownHeaders = (global::Interop.HttpApi.HTTP_UNKNOWN_HEADER*)(void*)item.AddrOfPinnedObject();
                        }
                        string[] values2 = Headers.GetValues(j);
                        for (int k = 0; k < values2.Length; k++)
{
                            array2 = new byte[WebHeaderEncoding.GetByteCount(key)];
                            array[headers.UnknownHeaderCount].NameLength = (ushort)array2.Length;
                            WebHeaderEncoding.GetBytes(key, 0, array2.Length, array2, 0);
                            GCHandle item = GCHandle.Alloc(array2, GCHandleType.Pinned);
                            list.Add(item);
                            array[headers.UnknownHeaderCount].pName = (sbyte*)(void*)item.AddrOfPinnedObject();
                            text = values2[k];
                            array2 = new byte[WebHeaderEncoding.GetByteCount(text)];
                            array[headers.UnknownHeaderCount].RawValueLength = (ushort)array2.Length;
                            WebHeaderEncoding.GetBytes(text, 0, array2.Length, array2, 0);
                            item = GCHandle.Alloc(array2, GCHandleType.Pinned);
                            list.Add(item);
                            array[headers.UnknownHeaderCount].pRawValue = (sbyte*)(void*)item.AddrOfPinnedObject();
                            headers.UnknownHeaderCount++;
                            if (System.Net.NetEventSource.Log.IsEnabled())
{
                                System.Net.NetEventSource.Info(this, "UnknownHeaderCount:" + headers.UnknownHeaderCount, "SerializeHeaders");
                            }
                        }
                        continue;
                    }
                    if (System.Net.NetEventSource.Log.IsEnabled())
                    {
                        System.Net.NetEventSource.Info(this, $"HttpResponseHeader[{num2}]:{(HttpResponseHeader)num2} headerValue:{text}", "SerializeHeaders");
                    }
                    if (text != null)
                    {
                        array2 = new byte[WebHeaderEncoding.GetByteCount(text)];
                        ptr[num2].RawValueLength = (ushort)array2.Length;
                        WebHeaderEncoding.GetBytes(text, 0, array2.Length, array2, 0);
                        GCHandle item = GCHandle.Alloc(array2, GCHandleType.Pinned);
                        list.Add(item);
                        ptr[num2].pRawValue = (sbyte*)(void*)item.AddrOfPinnedObject();
                        if (System.Net.NetEventSource.Log.IsEnabled())
{
                            System.Net.NetEventSource.Info(this, $"pRawValue:{(IntPtr)ptr[num2].pRawValue} RawValueLength:{ptr[num2].RawValueLength} lookup: {num2}", "SerializeHeaders");
                        }
                    }
                }
                return list;
            }
        }
        catch
        {
            FreePinnedHeaders(list);
            throw;
        }
    }
References System.Runtime.InteropServices.GCHandle.Alloc(), System.array, System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Net.HttpListenerResponse.FreePinnedHeaders(), System.Net.WebHeaderEncoding.GetByteCount(), System.Net.WebHeaderEncoding.GetBytes(), System.Net.NetEventSource.Info(), System.item, System.key, System.list, System.Net.NetEventSource.Log, System.text, and System.values.
Referenced by System.Net.HttpListenerResponse.SendHeaders().