Terraria: System.Net.HttpListenerResponse.ComputeHeaders
ComputeHeaders()
global.Interop.HttpApi.HTTP_FLAGS System.Net.HttpListenerResponse.ComputeHeaders () inline package
Definition at line 646 of file HttpListenerResponse.cs.
    {
        global::Interop.HttpApi.HTTP_FLAGS hTTP_FLAGS = global::Interop.HttpApi.HTTP_FLAGS.NONE;
        if (System.Net.NetEventSource.Log.IsEnabled())
        {
            System.Net.NetEventSource.Info(this, null, "ComputeHeaders");
        }
        _responseState = ResponseState.ComputedHeaders;
        ComputeCoreHeaders();
        if (System.Net.NetEventSource.Log.IsEnabled())
        {
            System.Net.NetEventSource.Info(this, $"flags: {hTTP_FLAGS} _boundaryType: {_boundaryType} _contentLength: {_contentLength} _keepAlive: {_keepAlive}", "ComputeHeaders");
        }
        if (_boundaryType == BoundaryType.None)
        {
            if (HttpListenerRequest.ProtocolVersion.Minor == 0)
            {
                _keepAlive = false;
            }
            else
            {
                _boundaryType = BoundaryType.Chunked;
            }
            if (CanSendResponseBody(_httpContext.Response.StatusCode))
            {
                _contentLength = -1L;
            }
            else
            {
                ContentLength64 = 0L;
            }
        }
        if (System.Net.NetEventSource.Log.IsEnabled())
        {
            System.Net.NetEventSource.Info(this, $"flags:{hTTP_FLAGS} _BoundaryType:{_boundaryType} _contentLength:{_contentLength} _keepAlive: {_keepAlive}", "ComputeHeaders");
        }
        if (_boundaryType == BoundaryType.ContentLength)
        {
            Headers[HttpResponseHeader.ContentLength] = _contentLength.ToString("D", NumberFormatInfo.InvariantInfo);
            if (_contentLength == 0L)
            {
                hTTP_FLAGS = global::Interop.HttpApi.HTTP_FLAGS.NONE;
            }
        }
        else if (_boundaryType == BoundaryType.Chunked)
        {
            Headers[HttpResponseHeader.TransferEncoding] = "chunked";
        }
        else if (_boundaryType == BoundaryType.None)
        {
            hTTP_FLAGS = global::Interop.HttpApi.HTTP_FLAGS.NONE;
        }
        else
        {
            _keepAlive = false;
        }
        if (!_keepAlive)
        {
            Headers.Add(HttpResponseHeader.Connection, "close");
            if (hTTP_FLAGS == global::Interop.HttpApi.HTTP_FLAGS.NONE)
            {
                hTTP_FLAGS = global::Interop.HttpApi.HTTP_FLAGS.HTTP_RECEIVE_REQUEST_FLAG_COPY_BODY;
            }
        }
        else if (HttpListenerRequest.ProtocolVersion.Minor == 0)
        {
            Headers[HttpResponseHeader.KeepAlive] = "true";
        }
        if (System.Net.NetEventSource.Log.IsEnabled())
        {
            System.Net.NetEventSource.Info(this, $"flags:{hTTP_FLAGS} _BoundaryType:{_boundaryType} _contentLength:{_contentLength} _keepAlive: {_keepAlive}", "ComputeHeaders");
        }
        return hTTP_FLAGS;
    }
References System.Net.HttpListenerResponse._boundaryType, System.Net.HttpListenerResponse._contentLength, System.Net.HttpListenerResponse._httpContext, System.Net.HttpListenerResponse._keepAlive, System.Net.HttpListenerResponse._responseState, System.Net.HttpListenerResponse.CanSendResponseBody(), System.Net.HttpListenerResponse.ComputeCoreHeaders(), System.Net.HttpListenerResponse.ContentLength64, System.Net.NetEventSource.Info(), System.Globalization.NumberFormatInfo.InvariantInfo, System.L, System.Net.NetEventSource.Log, System.Version.Minor, System.Net.HttpListenerRequest.ProtocolVersion, System.Net.HttpListenerContext.Response, and System.Net.HttpListenerResponse.StatusCode.
Referenced by System.Net.HttpResponseStream.ComputeLeftToWrite().