Terraria: System.Net.HttpListenerResponse.SendHeaders
SendHeaders()
unsafe uint System.Net.HttpListenerResponse.SendHeaders (global::Interop::HttpApi::HTTP_DATA_CHUNK * pDataChunk, HttpResponseStreamAsyncResult asyncResult, global::Interop::HttpApi::HTTP_FLAGS flags, bool isWebSocketHandshake) inline package
Definition at line 554 of file HttpListenerResponse.cs.
    {
        if (System.Net.NetEventSource.Log.IsEnabled())
        {
            System.Net.NetEventSource.Info(this, $"pDataChunk: {(IntPtr)pDataChunk}, asyncResult: {asyncResult}", "SendHeaders");
        }
        if (StatusCode == 401)
        {
            HttpListenerContext.SetAuthenticationHeaders();
        }
        if (System.Net.NetEventSource.Log.IsEnabled())
        {
            StringBuilder stringBuilder = new StringBuilder("HttpListenerResponse Headers:\n");
            for (int i = 0; i < Headers.Count; i++)
            {
                stringBuilder.Append('\t');
                stringBuilder.Append(Headers.GetKey(i));
                stringBuilder.Append(" : ");
                stringBuilder.Append(Headers.Get(i));
                stringBuilder.Append('\n');
            }
            if (System.Net.NetEventSource.Log.IsEnabled())
            {
                System.Net.NetEventSource.Info(this, stringBuilder.ToString(), "SendHeaders");
            }
        }
        _responseState = ResponseState.SentHeaders;
        List<GCHandle> pinnedHeaders = SerializeHeaders(ref _nativeResponse.Headers, isWebSocketHandshake);
        uint num;
        try
        {
            if (pDataChunk != null)
            {
                _nativeResponse.EntityChunkCount = 1;
                _nativeResponse.pEntityChunks = pDataChunk;
            }
            else if (asyncResult != null && asyncResult.pDataChunks != null)
            {
                _nativeResponse.EntityChunkCount = asyncResult.dataChunkCount;
                _nativeResponse.pEntityChunks = asyncResult.pDataChunks;
            }
            else
            {
                _nativeResponse.EntityChunkCount = 0;
                _nativeResponse.pEntityChunks = null;
            }
            if (System.Net.NetEventSource.Log.IsEnabled())
            {
                System.Net.NetEventSource.Info(this, "Calling Interop.HttpApi.HttpSendHttpResponse flags:" + flags, "SendHeaders");
            }
            Unsafe.SkipInit(out uint numBytes);
            if (StatusDescription.Length > 0)
            {
                byte[] array = new byte[WebHeaderEncoding.GetByteCount(StatusDescription)];
                fixed (byte* pReason = &array[0])
                {
                    _nativeResponse.ReasonLength = (ushort)array.Length;
                    WebHeaderEncoding.GetBytes(StatusDescription, 0, array.Length, array, 0);
                    _nativeResponse.pReason = (sbyte*)pReason;
                    fixed (global::Interop.HttpApi.HTTP_RESPONSE* pHttpResponse = &_nativeResponse)
                    {
                        num = global::Interop.HttpApi.HttpSendHttpResponse(HttpListenerContext.RequestQueueHandle, HttpListenerRequest.RequestId, (uint)flags, pHttpResponse, null, &numBytes, Microsoft.Win32.SafeHandles.SafeLocalAllocHandle.Zero, 0u, (asyncResult == null) ? null : asyncResult._pOverlapped, null);
                        if (asyncResult != null && num == 0 && HttpListener.SkipIOCPCallbackOnSuccess)
{
                            asyncResult.IOCompleted(num, numBytes);
                        }
                    }
                }
            }
            else
            {
                fixed (global::Interop.HttpApi.HTTP_RESPONSE* pHttpResponse2 = &_nativeResponse)
                {
                    num = global::Interop.HttpApi.HttpSendHttpResponse(HttpListenerContext.RequestQueueHandle, HttpListenerRequest.RequestId, (uint)flags, pHttpResponse2, null, &numBytes, Microsoft.Win32.SafeHandles.SafeLocalAllocHandle.Zero, 0u, (asyncResult == null) ? null : asyncResult._pOverlapped, null);
                    if (asyncResult != null && num == 0 && HttpListener.SkipIOCPCallbackOnSuccess)
                    {
                        asyncResult.IOCompleted(num, numBytes);
                    }
                }
            }
            if (System.Net.NetEventSource.Log.IsEnabled())
            {
                System.Net.NetEventSource.Info(this, "Call to Interop.HttpApi.HttpSendHttpResponse returned:" + num, "SendHeaders");
            }
        }
        finally
        {
            FreePinnedHeaders(pinnedHeaders);
        }
        return num;
    }
References System.Net.HttpListenerResponse._nativeResponse, System.Net.HttpListenerResponse._responseState, System.array, System.asyncResult, System.Net.HttpListenerResponse.FreePinnedHeaders(), System.Net.WebHeaderEncoding.GetByteCount(), System.Net.WebHeaderEncoding.GetBytes(), System.Net.NetEventSource.Info(), System.Net.NetEventSource.Log, System.Net.HttpListenerRequest.RequestId, System.Net.HttpListenerContext.RequestQueueHandle, System.Net.HttpListenerResponse.SerializeHeaders(), System.Net.HttpListenerContext.SetAuthenticationHeaders(), System.Net.HttpListener.SkipIOCPCallbackOnSuccess, System.Net.HttpListenerResponse.StatusCode, System.Net.HttpListenerResponse.StatusDescription, and Microsoft.Win32.SafeHandles.SafeLocalAllocHandle.Zero.
Referenced by System.Net.HttpResponseStream.BeginWriteCore(), System.Net.HttpResponseStream.DisposeCore(), and System.Net.HttpResponseStream.WriteCore().