Terraria: System.Net.WebSockets.WebSocket.ThrowOnInvalidState
ThrowOnInvalidState()
static void System.Net.WebSockets.WebSocket.ThrowOnInvalidState (WebSocketState state, params WebSocketState[] validStates) inline static protected inherited
Definition at line 82 of file WebSocket.cs.
    {
        string p = string.Empty;
        if (validStates != null && validStates.Length != 0)
        {
            foreach (WebSocketState webSocketState in validStates)
            {
                if (state == webSocketState)
                {
                    return;
                }
            }
            p = string.Join(", ", validStates);
        }
        throw new WebSocketException(WebSocketError.InvalidState, System.SR.Format(System.SR.net_WebSockets_InvalidState, state, p));
    }
References System.SR.Format(), System.SR.net_WebSockets_InvalidState, and System.state.
Referenced by System.Net.WebSockets.WebSocketBase.CloseAsyncCore(), System.Net.WebSockets.WebSocketBase.CloseOutputAsyncCore(), System.Net.WebSockets.WebSocketBase.ReceiveAsyncCore(), and System.Net.WebSockets.WebSocketBase.SendAsyncCore().