Terraria: System.Net.Mail.ReadLinesCommand.EndSend
EndSend()
static LineInfo[] System.Net.Mail.ReadLinesCommand.EndSend (IAsyncResult result) inline static package
Definition at line 38 of file ReadLinesCommand.cs.
    {
        object obj = MultiAsyncResult.End(result);
        if (obj is Exception source)
        {
            ExceptionDispatchInfo.Throw(source);
        }
        return (LineInfo[])obj;
    }
References System.Net.Mime.MultiAsyncResult.End(), System.obj, System.source, and System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw().
Referenced by System.Net.Mail.AuthCommand.EndSend(), and System.Net.Mail.EHelloCommand.EndSend().