Terraria: System.Threading.Tasks.Task.TwoTaskWhenAnyPromise.Invoke
Invoke()
void System.Threading.Tasks.Task< TResult >.TwoTaskWhenAnyPromise< TTask >.Invoke (Task completingTask) inline
Implements System.Threading.Tasks.ITaskCompletionAction.
Definition at line 912 of file Task.cs.
        {
            Task task;
            if ((task = Interlocked.Exchange(ref _task1, null)) != null)
            {
                Task task2 = _task2;
                _task2 = null;
                if (TplEventSource.Log.IsEnabled())
                {
                    TplEventSource.Log.TraceOperationRelation(base.Id, CausalityRelation.Choice);
                    TplEventSource.Log.TraceOperationEnd(base.Id, AsyncCausalityStatus.Completed);
                }
                if (s_asyncDebuggingEnabled)
                {
                    RemoveFromActiveTasks(this);
                }
                if (!task.IsCompleted)
                {
                    task.RemoveContinuation(this);
                }
                else
                {
                    task2.RemoveContinuation(this);
                }
                bool flag = TrySetResult((TTask)completingTask);
            }
        }
References System.Threading.Tasks.Task< TResult >.TwoTaskWhenAnyPromise< TTask >._task1, System.Threading.Tasks.Task< TResult >.TwoTaskWhenAnyPromise< TTask >._task2, System.Threading.Interlocked.Exchange(), System.Threading.Tasks.TplEventSource.Log, System.Threading.Tasks.Task< TTask >.RemoveFromActiveTasks(), System.Threading.Tasks.Task< TTask >.s_asyncDebuggingEnabled, System.task, and System.Threading.Tasks.Task< TTask >.TrySetResult().