Terraria: System.Net.Mail.ReadLinesCommand.Send
Send()
static LineInfo[] System.Net.Mail.ReadLinesCommand.Send (SmtpConnection conn) inline static package
Definition at line 89 of file ReadLinesCommand.cs.
    {
        conn.Flush();
        return conn.Reader.GetNextReplyReader().ReadLines();
    }
References System.Net.Mail.SmtpConnection.Flush(), System.Net.Mail.SmtpReplyReaderFactory.GetNextReplyReader(), System.Net.Mail.SmtpConnection.Reader, and System.Net.Mail.SmtpReplyReader.ReadLines().
Referenced by System.Net.Mail.EHelloCommand.Send(), System.Net.Mail.AuthCommand.Send(), and System.Net.Mail.AuthCommand.Send().