Terraria: System.Net.Mail.ReadLinesCommand.BeginSend
BeginSend()
static IAsyncResult System.Net.Mail.ReadLinesCommand.BeginSend (SmtpConnection conn, AsyncCallback callback, object state) inline static package
Definition at line 12 of file ReadLinesCommand.cs.
    {
        MultiAsyncResult multiAsyncResult = new MultiAsyncResult(conn, callback, state);
        multiAsyncResult.Enter();
        IAsyncResult asyncResult = conn.BeginFlush(s_onWrite, multiAsyncResult);
        if (asyncResult.CompletedSynchronously)
        {
            conn.EndFlush(asyncResult);
            multiAsyncResult.Leave();
        }
        SmtpReplyReader nextReplyReader = conn.Reader.GetNextReplyReader();
        multiAsyncResult.Enter();
        IAsyncResult asyncResult2 = nextReplyReader.BeginReadLines(s_onReadLines, multiAsyncResult);
        if (asyncResult2.CompletedSynchronously)
        {
            LineInfo[] result = conn.Reader.CurrentReader.EndReadLines(asyncResult2);
            if (!(multiAsyncResult.Result is Exception))
            {
                multiAsyncResult.Result = result;
            }
            multiAsyncResult.Leave();
        }
        multiAsyncResult.CompleteSequence();
        return multiAsyncResult;
    }
References System.asyncResult, System.Net.Mail.SmtpConnection.BeginFlush(), System.Net.Mail.SmtpReplyReader.BeginReadLines(), System.IAsyncResult.CompletedSynchronously, System.Net.Mime.MultiAsyncResult.CompleteSequence(), System.Net.Mail.SmtpReplyReaderFactory.CurrentReader, System.Net.Mail.SmtpConnection.EndFlush(), System.Net.Mail.SmtpReplyReader.EndReadLines(), System.Net.Mime.MultiAsyncResult.Enter(), System.Net.Mail.SmtpReplyReaderFactory.GetNextReplyReader(), System.Net.Mime.MultiAsyncResult.Leave(), System.Net.Mail.SmtpConnection.Reader, System.Net.LazyAsyncResult.Result, System.Net.Mail.ReadLinesCommand.s_onReadLines, System.Net.Mail.ReadLinesCommand.s_onWrite, and System.state.
Referenced by System.Net.Mail.EHelloCommand.BeginSend(), System.Net.Mail.AuthCommand.BeginSend(), and System.Net.Mail.AuthCommand.BeginSend().