Terraria: Animation.NewTemporaryAnimation
NewTemporaryAnimation()
static void Animation.NewTemporaryAnimation (int type, ushort tileType, int x, int y) inline static
     {
         Point16 coordinates = new Point16(x, y);
         if (x >= 0 && x < Main.maxTilesX && y >= 0 && y < Main.maxTilesY)
         {
             Animation animation = new Animation();
             animation.SetDefaults(type);
             animation._tileType = tileType;
             animation._coordinates = coordinates;
             animation._temporary = true;
             _awaitingAddition.Add(animation);
             if (Main.netMode == 2)
             {
                 NetMessage.SendTemporaryAnimation(-1, type, tileType, x, y);
             }
         }
     }
References _awaitingAddition, _coordinates, _temporary, _tileType, Main.maxTilesY, Main.netMode, NetMessage.SendTemporaryAnimation(), and SetDefaults().
Referenced by MessageBuffer.GetData(), Wiring.HitWireSingle(), and Player.TileInteractionsUse().