Terraria: System.Net.MultiArrayBuffer.GrowAvailableSpace
GrowAvailableSpace() [2/2]
void System.Net.MultiArrayBuffer.GrowAvailableSpace (int byteCount) inline
Definition at line 101 of file MultiArrayBuffer.cs.
    {
        uint num = (uint)(byteCount - AvailableMemory.Length);
        uint num2 = (num + 16384 - 1) / 16384;
        if (_blocks == null)
        {
            int num3;
            for (num3 = 4; num3 < num2; num3 *= 2)
            {
            }
            _blocks = new byte[num3][];
        }
        else
        {
            uint num4 = _allocatedEnd / 16384;
            uint num5 = (uint)_blocks.Length;
            if (num4 + num2 > num5)
            {
                uint num6 = _activeStart / 16384;
                uint num7 = num4 - num6;
                uint num8 = num7 + num2;
                Span<byte[]> span;
                if (num8 > num5)
                {
                    while (num5 < num8)
                    {
                        num5 *= 2;
                    }
                    byte[][] array = new byte[num5][];
                    span = _blocks.AsSpan();
                    span = span.Slice((int)num6, (int)num7);
                    span.CopyTo(array);
                    _blocks = array;
                }
                else
                {
                    span = _blocks.AsSpan();
                    span = span.Slice((int)num6, (int)num7);
                    span.CopyTo(_blocks);
                    span = _blocks.AsSpan();
                    span = span.Slice((int)num7, (int)num6);
                    span.Clear();
                }
                uint num9 = num6 * 16384;
                _allocatedEnd -= num9;
                _activeStart -= num9;
                _availableStart -= num9;
            }
        }
        uint num10 = _allocatedEnd / 16384;
        for (uint num11 = 0u; num11 < num2; num11++)
        {
            _blocks[num10++] = ArrayPool<byte>.Shared.Rent(16384);
        }
        _allocatedEnd = num10 * 16384;
    }
References System.Net.MultiArrayBuffer._activeStart, System.Net.MultiArrayBuffer._allocatedEnd, System.Net.MultiArrayBuffer._availableStart, System.Net.MultiArrayBuffer._blocks, System.array, System.Net.MultiArrayBuffer.AvailableMemory, System.byteCount, System.Span< T >.Clear(), System.Span< T >.CopyTo(), System.Buffers.ArrayPool< T >.Shared, and System.Span< T >.Slice().