Terraria: System.Numerics.Vector2.Vector2
Vector2() [1/3]
System.Numerics.Vector2.Vector2 (float value) inline
Definition at line 40 of file Vector2.cs.
        : this(value, value)
    {
    }
Referenced by System.Numerics.Vector2.Abs(), System.Numerics.Vector2.Max(), System.Numerics.Vector2.Min(), System.Numerics.Vector2.operator*(), System.Numerics.Vector2.operator*(), System.Numerics.Vector2.operator+(), System.Numerics.Vector2.operator-(), System.Numerics.Vector2.operator/(), System.Numerics.Vector2.operator/(), System.Numerics.Vector2.SquareRoot(), System.Numerics.Vector2.Transform(), System.Numerics.Vector2.Transform(), System.Numerics.Vector2.Transform(), System.Numerics.Vector2.TransformNormal(), and System.Numerics.Vector2.TransformNormal().