Terraria: System.Net.MultiArrayBuffer.EnsureAvailableSpaceUpToLimit
EnsureAvailableSpaceUpToLimit()
void System.Net.MultiArrayBuffer.EnsureAvailableSpaceUpToLimit (int byteCount, int limit) inline
Definition at line 84 of file MultiArrayBuffer.cs.
    {
        if (ActiveMemory.Length < limit)
        {
            byteCount = Math.Min(byteCount, limit - ActiveMemory.Length);
            EnsureAvailableSpace(byteCount);
        }
    }
References System.Net.MultiArrayBuffer.ActiveMemory, System.byteCount, System.Net.MultiArrayBuffer.EnsureAvailableSpace(), and System.Math.Min().
Referenced by System.IO.StreamBuffer.TryWriteToBuffer().