Terraria: System.Runtime.Serialization.XmlObjectSerializerContext.GetDataContract
GetDataContract() [2/3]
virtual DataContract System.Runtime.Serialization.XmlObjectSerializerContext.GetDataContract (RuntimeTypeHandle typeHandle, Type type) inline package virtual inherited
Reimplemented in System.Runtime.Serialization.Json.XmlObjectSerializerReadContextComplexJson, and System.Runtime.Serialization.Json.XmlObjectSerializerWriteContextComplexJson.
Definition at line 121 of file XmlObjectSerializerContext.cs.
    {
        if (IsGetOnlyCollection)
        {
            return DataContract.GetGetOnlyCollectionDataContract(DataContract.GetId(typeHandle), typeHandle, type, Mode);
        }
        return DataContract.GetDataContract(typeHandle, type, Mode);
    }
References System.Runtime.Serialization.DataContract.GetDataContract(), System.Runtime.Serialization.DataContract.GetGetOnlyCollectionDataContract(), System.Runtime.Serialization.DataContract.GetId(), System.Runtime.Serialization.XmlObjectSerializerContext.IsGetOnlyCollection, and System.type.