Terraria: System.Runtime.Serialization.XmlObjectSerializerContext.GetDataContractSkipValidation
GetDataContractSkipValidation()
virtual DataContract System.Runtime.Serialization.XmlObjectSerializerContext.GetDataContractSkipValidation (int typeId, RuntimeTypeHandle typeHandle, Type type) inline package virtual inherited
Reimplemented in System.Runtime.Serialization.Json.XmlObjectSerializerReadContextComplexJson, and System.Runtime.Serialization.Json.XmlObjectSerializerWriteContextComplexJson.
Definition at line 131 of file XmlObjectSerializerContext.cs.
    {
        if (IsGetOnlyCollection)
        {
            return DataContract.GetGetOnlyCollectionDataContractSkipValidation(typeId, typeHandle, type);
        }
        return DataContract.GetDataContractSkipValidation(typeId, typeHandle, type);
    }
References System.Runtime.Serialization.DataContract.GetDataContractSkipValidation(), System.Runtime.Serialization.DataContract.GetGetOnlyCollectionDataContractSkipValidation(), System.Runtime.Serialization.XmlObjectSerializerContext.IsGetOnlyCollection, and System.type.
Referenced by System.Runtime.Serialization.XmlObjectSerializerWriteContext.SerializeWithXsiType().