Terraria: System.Runtime.Serialization.XmlObjectSerializerContext.CheckIfTypeSerializable
CheckIfTypeSerializable()
virtual void System.Runtime.Serialization.XmlObjectSerializerContext.CheckIfTypeSerializable (Type memberType, bool isMemberTypeSerializable) inline package virtual inherited
Reimplemented in System.Runtime.Serialization.XmlObjectSerializerReadContextComplex, and System.Runtime.Serialization.XmlObjectSerializerWriteContextComplex.
Definition at line 151 of file XmlObjectSerializerContext.cs.
    {
        if (!isMemberTypeSerializable)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new InvalidDataContractException(System.SR.Format(System.SR.TypeNotSerializable, memberType)));
        }
    }
References System.SR.Format(), System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperError(), and System.SR.TypeNotSerializable.
Referenced by System.Runtime.Serialization.XmlObjectSerializerReadContext.ReadIfNullOrRef(), and System.Runtime.Serialization.XmlObjectSerializerWriteContext.WriteNull().