Terraria: System.Runtime.Serialization.XmlObjectSerializerContext.IncrementItemCount
IncrementItemCount()
void System.Runtime.Serialization.XmlObjectSerializerContext.IncrementItemCount (int count) inline package inherited
Definition at line 105 of file XmlObjectSerializerContext.cs.
    {
        if (count > _maxItemsInObjectGraph - _itemCount)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(XmlObjectSerializer.CreateSerializationException(System.SR.Format(System.SR.ExceededMaxItemsQuota, _maxItemsInObjectGraph)));
        }
        _itemCount += count;
    }
References System.Runtime.Serialization.XmlObjectSerializerContext._itemCount, System.Runtime.Serialization.XmlObjectSerializerContext._maxItemsInObjectGraph, System.count, System.Runtime.Serialization.XmlObjectSerializer.CreateSerializationException(), System.SR.ExceededMaxItemsQuota, System.SR.Format(), and System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperError().
Referenced by System.Runtime.Serialization.XmlReaderDelegator.CheckExpectedArrayLength(), System.Runtime.Serialization.XmlObjectSerializerWriteContext.IncrementCollectionCount(), System.Runtime.Serialization.XmlObjectSerializerReadContext.ReadExtensionDataValue(), System.Runtime.Serialization.XmlObjectSerializerReadContext.ReadSerializationInfo(), System.Runtime.Serialization.Json.ReflectionJsonReader.ReadSimpleDictionary(), System.Runtime.Serialization.ReflectionReader.ReflectionReadCollectionCore(), System.Runtime.Serialization.Json.ReflectionJsonReader.ReflectionReadMembers(), System.Runtime.Serialization.ReflectionXmlReader.ReflectionReadMembers(), System.Runtime.Serialization.ReflectionXmlFormatWriter.ReflectionWriteCollection(), System.Runtime.Serialization.Json.ReflectionJsonFormatWriter.ReflectionWriteCollection(), System.Runtime.Serialization.ReflectionXmlClassWriter.ReflectionWriteMembers(), System.Runtime.Serialization.Json.ReflectionJsonClassWriter.ReflectionWriteMembers(), System.Runtime.Serialization.XmlReaderDelegator.TryReadBooleanArray(), System.Runtime.Serialization.XmlReaderDelegator.TryReadDateTimeArray(), System.Runtime.Serialization.XmlReaderDelegator.TryReadDecimalArray(), System.Runtime.Serialization.XmlReaderDelegator.TryReadDoubleArray(), System.Runtime.Serialization.XmlReaderDelegator.TryReadInt32Array(), System.Runtime.Serialization.XmlReaderDelegator.TryReadInt64Array(), System.Runtime.Serialization.Json.JsonReaderDelegator.TryReadJsonDateTimeArray(), System.Runtime.Serialization.XmlReaderDelegator.TryReadSingleArray(), System.Runtime.Serialization.XmlObjectSerializerWriteContext.WriteExtensionDataValue(), and System.Runtime.Serialization.XmlObjectSerializerWriteContext.WriteSerializationInfo().