Terraria: System.Runtime.Serialization.XmlObjectSerializerContext.ResolveDataContractFromKnownTypes
ResolveDataContractFromKnownTypes() [2/2]
DataContract System.Runtime.Serialization.XmlObjectSerializerContext.ResolveDataContractFromKnownTypes (XmlQualifiedName typeName) inline private inherited
Definition at line 236 of file XmlObjectSerializerContext.cs.
    {
        DataContract dataContract = PrimitiveDataContract.GetPrimitiveDataContract(typeName.Name, typeName.Namespace);
        if (dataContract == null)
        {
            dataContract = scopedKnownTypes.GetDataContract(typeName);
            if (dataContract == null)
            {
                dataContract = GetDataContractFromSerializerKnownTypes(typeName);
            }
        }
        return dataContract;
    }
References System.Runtime.Serialization.Dictionary, System.Runtime.Serialization.ScopedKnownTypes.GetDataContract(), System.Runtime.Serialization.XmlObjectSerializerContext.GetDataContractFromSerializerKnownTypes(), System.Runtime.Serialization.PrimitiveDataContract.GetPrimitiveDataContract(), System.Xml.XmlQualifiedName.Name, System.Xml.XmlQualifiedName.Namespace, and System.Runtime.Serialization.XmlObjectSerializerContext.scopedKnownTypes.
Referenced by System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(), System.Runtime.Serialization.XmlObjectSerializerContext.IsKnownType(), System.Runtime.Serialization.XmlObjectSerializerContext.ResolveDataContractFromKnownTypes(), System.Runtime.Serialization.XmlObjectSerializerReadContext.ResolveDataContractFromTypeName(), System.Runtime.Serialization.XmlObjectSerializerContext.ResolveNameFromKnownTypes(), and System.Runtime.Serialization.XmlObjectSerializerWriteContext.SerializeAndVerifyType().