Terraria: ContentSamples.BestiaryHelper.GetSortedBestiaryEntriesList
GetSortedBestiaryEntriesList()
static List<KeyValuePair<int, NPC> > ContentSamples.BestiaryHelper.GetSortedBestiaryEntriesList (BestiaryDatabase database) inline static
         {
             List<IBestiaryInfoElement> commonFilters = BestiaryDatabaseNPCsPopulator.CommonTags.GetCommonInfoElementsForFilters();
             List<KeyValuePair<int, NPC>> list = (from x in NpcsByNetId.ToList()
                 orderby GetBestiaryTownPriority(x.Value), !x.Value.isLikeATownNPC, GetBestiaryNormalGoldCritterPriority(x.Value), !x.Value.CountsAsACritter, GetBestiaryBossPriority(x.Value), x.Value.boss || NPCID.Sets.ShouldBeCountedAsBoss[x.Value.type], GetLowestBiomeGroupIndex(x.Value, database, commonFilters), x.Value.aiStyle, GetBestiaryPowerLevel(x.Value), GetBestiaryStarsPriority(x.Value)
                 select x).ToList();
             list.RemoveAll((KeyValuePair<int, NPC> x) => ShouldHideBestiaryEntry(x.Value));
             return list;
         }
References ContentSamples.BestiaryHelper.GetBestiaryBossPriority(), ContentSamples.BestiaryHelper.GetBestiaryNormalGoldCritterPriority(), ContentSamples.BestiaryHelper.GetBestiaryPowerLevel(), ContentSamples.BestiaryHelper.GetBestiaryStarsPriority(), ContentSamples.BestiaryHelper.GetBestiaryTownPriority(), BestiaryDatabaseNPCsPopulator.CommonTags.GetCommonInfoElementsForFilters(), ContentSamples.BestiaryHelper.GetLowestBiomeGroupIndex(), ContentSamples.NpcsByNetId, NPCID.Sets.ShouldBeCountedAsBoss, and ContentSamples.BestiaryHelper.ShouldHideBestiaryEntry().
Referenced by ContentSamples.CreateBestiarySortingIds().