Terraria: System.Data.ExceptionBuilder.ConvertFailed
ConvertFailed()
static Exception System.Data.ExceptionBuilder.ConvertFailed (Type type1, Type type2) inline static
Definition at line 1422 of file ExceptionBuilder.cs.
    {
        return _Data(System.SR.Format(System.SR.SqlConvert_ConvertFailed, type1.FullName, type2.FullName));
    }
References System.Data.ExceptionBuilder._Data(), System.SR.Format(), System.Type.FullName, and System.SR.SqlConvert_ConvertFailed.
Referenced by System.Data.Common.SqlConvert.ChangeType2(), System.Data.Common.BigIntegerStorage.ConvertFromBigInteger(), System.Data.Common.BigIntegerStorage.ConvertToBigInteger(), System.Data.Common.SqlConvert.ConvertToSqlBinary(), System.Data.Common.SqlConvert.ConvertToSqlBoolean(), System.Data.Common.SqlConvert.ConvertToSqlByte(), System.Data.Common.SqlConvert.ConvertToSqlBytes(), System.Data.Common.SqlConvert.ConvertToSqlChars(), System.Data.Common.SqlConvert.ConvertToSqlDateTime(), System.Data.Common.SqlConvert.ConvertToSqlDecimal(), System.Data.Common.SqlConvert.ConvertToSqlDouble(), System.Data.Common.SqlConvert.ConvertToSqlGuid(), System.Data.Common.SqlConvert.ConvertToSqlInt16(), System.Data.Common.SqlConvert.ConvertToSqlInt32(), System.Data.Common.SqlConvert.ConvertToSqlInt64(), System.Data.Common.SqlConvert.ConvertToSqlMoney(), System.Data.Common.SqlConvert.ConvertToSqlSingle(), and System.Data.Common.SqlConvert.ConvertToSqlString().