Terraria: System.Data.ExceptionBuilder._InvalidOperation
_InvalidOperation()
static Exception System.Data.ExceptionBuilder._InvalidOperation (string error) inline static private
Definition at line 65 of file ExceptionBuilder.cs.
    {
        return TraceExceptionAsReturnValue(new InvalidOperationException(error));
    }
References System.Data.ExceptionBuilder.TraceExceptionAsReturnValue().
Referenced by System.Data.ExceptionBuilder.BadObjectPropertyAccess(), System.Data.ExceptionBuilder.CannotChangeSchemaSerializationMode(), System.Data.ExceptionBuilder.CanNotDeserializeObjectType(), System.Data.ExceptionBuilder.CanNotRemoteDataTable(), System.Data.ExceptionBuilder.CanNotSerializeDataTableHierarchy(), System.Data.ExceptionBuilder.CanNotSerializeDataTableWithEmptyName(), System.Data.ExceptionBuilder.CannotSetDateTimeModeForNonDateTimeColumns(), System.Data.ExceptionBuilder.CantChangeDateTimeMode(), System.Data.ExceptionBuilder.DataTableInferenceNotSupported(), System.Data.ExceptionBuilder.DataTableReaderSchemaIsInvalid(), System.Data.ExceptionBuilder.EnumeratorModified(), System.Data.ExceptionBuilder.InternalRBTreeError(), System.Data.ExceptionBuilder.InvalidDataTableReader(), System.Data.ExceptionBuilder.InValidNestedRelation(), System.Data.ExceptionBuilder.InvalidParentNamespaceinNestedRelation(), System.Data.ExceptionBuilder.PolymorphismNotSupported(), System.Data.ExceptionBuilder.SetAddedAndModifiedCalledOnnonUnchanged(), System.Data.ExceptionBuilder.TypeNotAllowed(), and System.Data.ExceptionBuilder.UDTImplementsIChangeTrackingButnotIRevertible().