Terraria: System.Data.ExceptionBuilder.GetElementIndex
GetElementIndex()
static Exception System.Data.ExceptionBuilder.GetElementIndex (int index) inline static
Definition at line 683 of file ExceptionBuilder.cs.
    {
        return _IndexOutOfRange(System.SR.Format(System.SR.DataView_GetElementIndex, index.ToString(CultureInfo.InvariantCulture)));
    }
References System.Data.ExceptionBuilder._IndexOutOfRange(), System.SR.DataView_GetElementIndex, System.SR.Format(), System.index, and System.Globalization.CultureInfo.InvariantCulture.
Referenced by System.Data.DataView.GetRow().