Terraria: System.Data.ExceptionBuilder.RangeArgument
RangeArgument()
static Exception System.Data.ExceptionBuilder.RangeArgument (int min, int max) inline static
Definition at line 1221 of file ExceptionBuilder.cs.
    {
        return _Argument(System.SR.Format(System.SR.Range_Argument, min.ToString(CultureInfo.InvariantCulture), max.ToString(CultureInfo.InvariantCulture)));
    }
References System.Data.ExceptionBuilder._Argument(), System.SR.Format(), System.Globalization.CultureInfo.InvariantCulture, and System.SR.Range_Argument.
Referenced by System.Data.Range.Range().