Terraria: System.Data.ExceptionBuilder.TraceExceptionAsReturnValue
TraceExceptionAsReturnValue()
static Exception System.Data.ExceptionBuilder.TraceExceptionAsReturnValue (Exception e) inline static package
Definition at line 17 of file ExceptionBuilder.cs.
    {
        TraceException("<comm.ADP.TraceException|ERR|THROW> '{0}'", e);
        return e;
    }
References System.Data.ExceptionBuilder.TraceException().
Referenced by System.Data.ExceptionBuilder._Argument(), System.Data.ExceptionBuilder._Argument(), System.Data.ExceptionBuilder._Argument(), System.Data.ExceptionBuilder._ArgumentNull(), System.Data.ExceptionBuilder._ArgumentOutOfRange(), System.Data.ExceptionBuilder._Constraint(), System.Data.ExceptionBuilder._Data(), System.Data.ExceptionBuilder._DeletedRowInaccessible(), System.Data.ExceptionBuilder._DuplicateName(), System.Data.ExprException._Eval(), System.Data.ExprException._Eval(), System.Data.ExprException._Expr(), System.Data.ExceptionBuilder._IndexOutOfRange(), System.Data.ExceptionBuilder._InRowChangingEvent(), System.Data.ExceptionBuilder._InvalidConstraint(), System.Data.ExceptionBuilder._InvalidEnumArgumentException(), System.Data.ExceptionBuilder._InvalidOperation(), System.Data.ExceptionBuilder._MissingPrimaryKey(), System.Data.ExceptionBuilder._NoNullAllowed(), System.Data.ExprException._Overflow(), System.Data.ExceptionBuilder._ReadOnly(), System.Data.ExceptionBuilder._RowNotInTable(), System.Data.ExprException._Syntax(), System.Data.ExceptionBuilder._VersionNotFound(), and System.Data.ExceptionBuilder.ThrowDataException().