Terraria: System.Data.ExceptionBuilder._IndexOutOfRange
_IndexOutOfRange()
static Exception System.Data.ExceptionBuilder._IndexOutOfRange (string error) inline static private
Definition at line 60 of file ExceptionBuilder.cs.
    {
        return TraceExceptionAsReturnValue(new IndexOutOfRangeException(error));
    }
References System.Data.ExceptionBuilder.TraceExceptionAsReturnValue().
Referenced by System.Data.ExceptionBuilder.ColumnOutOfRange(), System.Data.ExceptionBuilder.ColumnOutOfRange(), System.Data.ExceptionBuilder.ConstraintOutOfRange(), System.Data.ExceptionBuilder.GetElementIndex(), System.Data.ExceptionBuilder.RelationOutOfRange(), System.Data.ExceptionBuilder.RowInsertMissing(), System.Data.ExceptionBuilder.RowInsertOutOfRange(), System.Data.ExceptionBuilder.RowInsertTwice(), System.Data.ExceptionBuilder.RowOutOfRange(), System.Data.ExceptionBuilder.RowOutOfRange(), and System.Data.ExceptionBuilder.TableOutOfRange().