Terraria: System.Data.ExceptionBuilder.TraceExceptionWithoutRethrow
TraceExceptionWithoutRethrow()
static Exception System.Data.ExceptionBuilder.TraceExceptionWithoutRethrow (Exception e) inline static package
Definition at line 29 of file ExceptionBuilder.cs.
    {
        TraceException("<comm.ADP.TraceException|ERR|CATCH> '{0}'", e);
        return e;
    }
References System.Data.ExceptionBuilder.TraceException().
Referenced by System.Data.DataRelationCollection.DataSetRelationCollection.AddCore(), System.Data.BinaryNode.BinaryCompare(), System.Data.Common.ObjectStorage.Compare(), System.Data.Common.ObjectStorage.CompareTo(), System.Data.DataTableReader.GetBoolean(), System.Data.DataTableReader.GetByte(), System.Data.DataTableReader.GetBytes(), System.Data.DataTableReader.GetChar(), System.Data.DataTableReader.GetChars(), System.Data.DataTableReader.GetDateTime(), System.Data.DataTableReader.GetDecimal(), System.Data.DataTableReader.GetDouble(), System.Data.DataTableReader.GetFieldType(), System.Data.DataTableReader.GetFloat(), System.Data.DataTableReader.GetGuid(), System.Data.DataTableReader.GetInt16(), System.Data.DataTableReader.GetInt32(), System.Data.DataTableReader.GetInt64(), System.Data.DataTableReader.GetName(), System.Data.DataTableReader.GetString(), System.Data.DataTableReader.GetValue(), System.Data.DataTableReader.IsDBNull(), System.Data.DataView.OnListChanged(), System.Data.DataViewManager.OnListChanged(), System.Data.DataTable.RaiseRowChanged(), System.Data.DataTable.RestoreIndexEvents(), System.Data.DataView.SetDataViewManager(), System.Data.DataTable.SetNewRecordWorker(), System.Data.ConstNode.SmallestDecimal(), and System.Data.ConstNode.SmallestNumeric().