Terraria: System.Data.ExceptionBuilder.SelfnestedDatasetConflictingName
SelfnestedDatasetConflictingName()
static Exception System.Data.ExceptionBuilder.SelfnestedDatasetConflictingName (string table) inline static
Definition at line 1146 of file ExceptionBuilder.cs.
    {
        return _DuplicateName(System.SR.Format(System.SR.DataTable_SelfnestedDatasetConflictingName, table));
    }
References System.Data.ExceptionBuilder._DuplicateName(), System.SR.DataTable_SelfnestedDatasetConflictingName, and System.SR.Format().
Referenced by System.Data.DataRelation.CheckNestedRelations().