Terraria: System.Data.ExceptionBuilder.ForeignKeyViolation
ForeignKeyViolation()
static Exception System.Data.ExceptionBuilder.ForeignKeyViolation (string constraint, object[] keys) inline static
Definition at line 384 of file ExceptionBuilder.cs.
    {
        return _InvalidConstraint(System.SR.Format(System.SR.DataConstraint_ForeignKeyViolation, constraint, KeysToString(keys)));
    }
References System.Data.ExceptionBuilder._InvalidConstraint(), System.SR.DataConstraint_ForeignKeyViolation, System.SR.Format(), System.keys, and System.Data.ExceptionBuilder.KeysToString().
Referenced by System.Data.ForeignKeyConstraint.CheckConstraint().