Terraria: System.Data.ExceptionBuilder.CaseLocaleMismatch
CaseLocaleMismatch()
static Exception System.Data.ExceptionBuilder.CaseLocaleMismatch () inline static
Definition at line 1081 of file ExceptionBuilder.cs.
    {
        return _Argument(System.SR.DataRelation_CaseLocaleMismatch);
    }
References System.Data.ExceptionBuilder._Argument(), and System.SR.DataRelation_CaseLocaleMismatch.
Referenced by System.Data.DataRelationCollection.AddCore(), and System.Data.ForeignKeyConstraint.CheckCanAddToCollection().