Terraria: System.Data.ExceptionBuilder._Argument
_Argument() [1/3]
static Exception System.Data.ExceptionBuilder._Argument (string error) inline static package
Definition at line 35 of file ExceptionBuilder.cs.
    {
        return TraceExceptionAsReturnValue(new ArgumentException(error));
    }
References System.Data.ExceptionBuilder.TraceExceptionAsReturnValue().
Referenced by System.Data.ExceptionBuilder.AddExternalObject(), System.Data.ExceptionBuilder.AddPrimaryKeyConstraint(), System.Data.ExceptionBuilder.ArgumentContainsNull(), System.Data.ExceptionBuilder.ArgumentContainsNullValue(), System.Data.ExceptionBuilder.AutoIncrementAndDefaultValue(), System.Data.ExceptionBuilder.AutoIncrementAndExpression(), System.Data.ExceptionBuilder.AutoIncrementCannotSetIfHasData(), System.Data.ExceptionBuilder.AutoIncrementSeed(), System.Data.ExceptionBuilder.CannotAddColumn1(), System.Data.ExceptionBuilder.CannotAddColumn2(), System.Data.ExceptionBuilder.CannotAddColumn3(), System.Data.ExceptionBuilder.CannotAddColumn4(), System.Data.ExceptionBuilder.CannotChangeCaseLocale(), System.Data.ExceptionBuilder.CannotChangeNamespace(), System.Data.ExceptionBuilder.CanNotClear(), System.Data.ExceptionBuilder.CannotCreateDataReaderOnEmptyDataSet(), System.Data.ExceptionBuilder.CannotModifyCollection(), System.Data.ExceptionBuilder.CannotRemoveChildKey(), System.Data.ExceptionBuilder.CannotRemoveColumn(), System.Data.ExceptionBuilder.CannotRemoveConstraint(), System.Data.ExceptionBuilder.CannotRemoveExpression(), System.Data.ExceptionBuilder.CannotRemovePrimaryKey(), System.Data.ExceptionBuilder.CannotSetMaxLength(), System.Data.ExceptionBuilder.CannotSetMaxLength2(), System.Data.ExceptionBuilder.CanNotSetRemotingFormat(), System.Data.ExceptionBuilder.CannotSetSimpleContent(), System.Data.ExceptionBuilder.CannotSetSimpleContentType(), System.Data.ExceptionBuilder.CannotSetToNull(), System.Data.ExceptionBuilder.CantAddConstraintToMultipleNestedTable(), System.Data.ExceptionBuilder.CantChangeDataType(), System.Data.ExceptionBuilder.CaseInsensitiveNameConflict(), System.Data.ExceptionBuilder.CaseLocaleMismatch(), System.Data.ExceptionBuilder.ChildTableMismatch(), System.Data.ExceptionBuilder.ColumnNameRequired(), System.Data.ExceptionBuilder.ColumnNotInAnyTable(), System.Data.ExceptionBuilder.ColumnNotInTheTable(), System.Data.ExceptionBuilder.ColumnNotInTheUnderlyingTable(), System.Data.ExceptionBuilder.ColumnToSortIsOutOfRange(), System.Data.ExceptionBuilder.ConstraintForeignTable(), System.Data.ExceptionBuilder.ConstraintNotInTheTable(), System.Data.ExceptionBuilder.ConstraintParentValues(), System.Data.ExceptionBuilder.ConstraintRemoveFailed(), System.Data.ExceptionBuilder.CreateChildView(), System.Data.ExceptionBuilder.DataSetUnsupportedSchema(), System.Data.ExceptionBuilder.DataTableReaderArgumentIsEmpty(), System.Data.ExceptionBuilder.DefaultValueAndAutoIncrement(), System.Data.ExceptionBuilder.DefaultValueColumnDataType(), System.Data.ExceptionBuilder.DefaultValueDataType(), System.Data.ExceptionBuilder.ExpressionAndConstraint(), System.Data.ExceptionBuilder.ExpressionAndReadOnly(), System.Data.ExceptionBuilder.ExpressionAndUnique(), System.Data.ExceptionBuilder.ExpressionCircular(), System.Data.ExceptionBuilder.ExpressionInConstraint(), System.Data.ExceptionBuilder.ForeignRelation(), System.Data.ExceptionBuilder.HasToBeStringType(), System.Data.ExceptionBuilder.IndexKeyLength(), System.Data.ExceptionBuilder.InsertExternalObject(), System.Data.ExceptionBuilder.INullableUDTwithoutStaticNull(), System.Data.ExceptionBuilder.InvalidDataColumnMapping(), System.Data.ExceptionBuilder.InvalidDuplicateNamedSimpleTypeDelaration(), System.Data.ExceptionBuilder.InvalidOffsetLength(), System.Data.ExceptionBuilder.InvalidRowBitPattern(), System.Data.ExceptionBuilder.InvalidSortString(), System.Data.ExprException.InvokeArgument(), System.Data.ExceptionBuilder.KeyLengthMismatch(), System.Data.ExceptionBuilder.KeyLengthZero(), System.Data.ExceptionBuilder.LongerThanMaxLength(), System.Data.ExceptionBuilder.LoopInNestedRelations(), System.Data.ExceptionBuilder.MergeMissingDefinition(), System.Data.ExceptionBuilder.MultipleTextOnlyColumns(), System.Data.ExceptionBuilder.NamespaceNameConflict(), System.Data.ExceptionBuilder.NeededForForeignKeyConstraint(), System.Data.ExceptionBuilder.NegativeMinimumCapacity(), System.Data.ExceptionBuilder.NoConstraintName(), System.Data.ExceptionBuilder.NoRelationName(), System.Data.ExceptionBuilder.NoTableName(), System.Data.ExceptionBuilder.NullDataType(), System.Data.ExceptionBuilder.ParentRowNotInTheDataSet(), System.Data.ExceptionBuilder.ParentTableMismatch(), System.Data.ExceptionBuilder.ProblematicChars(), System.Data.ExceptionBuilder.PropertyNotFound(), System.Data.ExceptionBuilder.RangeArgument(), System.Data.ExceptionBuilder.RecordStateRange(), System.Data.ExceptionBuilder.RelationAlreadyExists(), System.Data.ExceptionBuilder.RelationAlreadyInOtherDataSet(), System.Data.ExceptionBuilder.RelationAlreadyInTheDataSet(), System.Data.ExceptionBuilder.RelationDataSetNull(), System.Data.ExceptionBuilder.RelationDoesNotExist(), System.Data.ExceptionBuilder.RelationForeignRow(), System.Data.ExceptionBuilder.RelationNestedReadOnly(), System.Data.ExceptionBuilder.RelationNotInTheDataSet(), System.Data.ExceptionBuilder.RelationTableNull(), System.Data.ExceptionBuilder.RelationTableWasRemoved(), System.Data.ExceptionBuilder.RemoveExternalObject(), System.Data.ExceptionBuilder.RemovePrimaryKey(), System.Data.ExceptionBuilder.RowAlreadyInOtherCollection(), System.Data.ExceptionBuilder.RowAlreadyInTheCollection(), System.Data.ExceptionBuilder.RowEmpty(), System.Data.ExceptionBuilder.RowNotInTheDataSet(), System.Data.ExceptionBuilder.SetDataSetNameConflicting(), System.Data.ExceptionBuilder.SetDataSetNameToEmpty(), System.Data.ExceptionBuilder.SetFailed(), System.Data.ExceptionBuilder.SetIListObject(), System.Data.ExceptionBuilder.StorageSetFailed(), System.Data.ExceptionBuilder.TableAlreadyInOtherDataSet(), System.Data.ExceptionBuilder.TableAlreadyInTheDataSet(), System.Data.ExceptionBuilder.TableCannotAddToSimpleContent(), System.Data.ExceptionBuilder.TableCantBeNestedInTwoTables(), System.Data.ExceptionBuilder.TableForeignPrimaryKey(), System.Data.ExceptionBuilder.TableInConstraint(), System.Data.ExceptionBuilder.TableInRelation(), System.Data.ExceptionBuilder.TableNotFound(), System.Data.ExceptionBuilder.TableNotInTheDataSet(), System.Data.ExceptionBuilder.TablesInDifferentSets(), System.Data.ExceptionBuilder.UniqueAndExpression(), System.Data.ExceptionBuilder.UniqueConstraintViolation(), System.Data.ExprException.UnsupportedDataType(), and System.Data.ExceptionBuilder.ValueArrayLength().