Terraria: System.Data.ExceptionBuilder._InvalidConstraint
_InvalidConstraint()
static Exception System.Data.ExceptionBuilder._InvalidConstraint (string error) inline static private
Definition at line 95 of file ExceptionBuilder.cs.
    {
        return TraceExceptionAsReturnValue(new InvalidConstraintException(error));
    }
References System.Data.ExceptionBuilder.TraceExceptionAsReturnValue().
Referenced by System.Data.ExceptionBuilder.ColumnsTypeMismatch(), System.Data.ExceptionBuilder.ConstraintAddFailed(), System.Data.ExceptionBuilder.FailedCascadeDelete(), System.Data.ExceptionBuilder.FailedCascadeUpdate(), System.Data.ExceptionBuilder.FailedClearParentTable(), System.Data.ExceptionBuilder.ForeignKeyViolation(), System.Data.ExceptionBuilder.GetParentRowTableMismatch(), System.Data.ExceptionBuilder.KeyColumnsIdentical(), System.Data.ExceptionBuilder.KeyDuplicateColumns(), System.Data.ExceptionBuilder.KeyNoColumns(), System.Data.ExceptionBuilder.KeyTableMismatch(), System.Data.ExceptionBuilder.KeyTooManyColumns(), System.Data.ExceptionBuilder.NonUniqueValues(), System.Data.ExceptionBuilder.ParentOrChildColumnsDoNotHaveDataSet(), System.Data.ExceptionBuilder.RelationDataSetMismatch(), System.Data.ExceptionBuilder.RelationForeignTable(), System.Data.ExceptionBuilder.RemoveParentRow(), and System.Data.ExceptionBuilder.SetParentRowTableMismatch().