Terraria: System.Data.ExceptionBuilder._Data
_Data()
static Exception System.Data.ExceptionBuilder._Data (string error) inline static private
Definition at line 85 of file ExceptionBuilder.cs.
    {
        return TraceExceptionAsReturnValue(new DataException(error));
    }
References System.Data.ExceptionBuilder.TraceExceptionAsReturnValue().
Referenced by System.Data.ExceptionBuilder.AddNewNotAllowNull(), System.Data.ExceptionBuilder.AggregateException(), System.Data.ExceptionBuilder.AttributeValues(), System.Data.ExceptionBuilder.CanNotBindTable(), System.Data.ExceptionBuilder.CannotConvert(), System.Data.ExceptionBuilder.CanNotDelete(), System.Data.ExceptionBuilder.CanNotEdit(), System.Data.ExceptionBuilder.CannotInstantiateAbstract(), System.Data.ExceptionBuilder.CanNotSetDataSet(), System.Data.ExceptionBuilder.CanNotSetTable(), System.Data.ExceptionBuilder.CanNotUse(), System.Data.ExceptionBuilder.CanNotUseDataViewManager(), System.Data.ExceptionBuilder.CircularComplexType(), System.Data.ExceptionBuilder.ColumnTypeConflict(), System.Data.ExceptionBuilder.ConvertFailed(), System.Data.ExceptionBuilder.DatatypeNotDefined(), System.Data.ExceptionBuilder.DiffgramMissingSQL(), System.Data.ExceptionBuilder.DuplicateConstraint(), System.Data.ExceptionBuilder.DuplicateConstraintRead(), System.Data.ExceptionBuilder.DuplicateDeclaration(), System.Data.ExceptionBuilder.ElementTypeNotFound(), System.Data.ExceptionBuilder.FoundEntity(), System.Data.ExceptionBuilder.IComparableNotImplemented(), System.Data.ExceptionBuilder.InvalidAttributeValue(), System.Data.ExceptionBuilder.InvalidField(), System.Data.ExceptionBuilder.InvalidKey(), System.Data.ExceptionBuilder.InvalidPrefix(), System.Data.ExceptionBuilder.InvalidRowVersion(), System.Data.ExceptionBuilder.InvalidSelector(), System.Data.ExceptionBuilder.InvalidStorageType(), System.Data.ExceptionBuilder.IsDataSetAttributeMissingInSchema(), System.Data.ExceptionBuilder.MergeFailed(), System.Data.ExceptionBuilder.MismatchKeyLength(), System.Data.ExceptionBuilder.MissingAttribute(), System.Data.ExceptionBuilder.MissingRefer(), System.Data.ExceptionBuilder.MultipleParentRows(), System.Data.ExceptionBuilder.MultipleParents(), System.Data.ExceptionBuilder.NestedCircular(), System.Data.ExceptionBuilder.NotOpen(), System.Data.ExceptionBuilder.NullKeyValues(), System.Data.ExceptionBuilder.NullRange(), System.Data.ExceptionBuilder.RelationChildKeyMissing(), System.Data.ExceptionBuilder.RelationChildNameMissing(), System.Data.ExceptionBuilder.RelationParentNameMissing(), System.Data.ExceptionBuilder.RelationTableKeyMissing(), System.Data.ExceptionBuilder.RowAlreadyRemoved(), System.Data.ExceptionBuilder.SetDataSetFailed(), System.Data.ExceptionBuilder.SetFailed(), System.Data.ExceptionBuilder.SetRowStateFilter(), System.Data.ExceptionBuilder.SetTable(), System.Data.ExceptionBuilder.SimpleTypeNotSupported(), System.Data.ExceptionBuilder.TooManyIsDataSetAttributesInSchema(), and System.Data.ExceptionBuilder.UndefinedDatatype().