Terraria: System.Data.ExceptionBuilder.ArgumentNull
ArgumentNull()
static Exception System.Data.ExceptionBuilder.ArgumentNull (string paramName) inline static
Definition at line 140 of file ExceptionBuilder.cs.
    {
        return _ArgumentNull(paramName, System.SR.Format(System.SR.Data_ArgumentNull, paramName));
    }
References System.Data.ExceptionBuilder._ArgumentNull(), System.SR.Data_ArgumentNull, and System.SR.Format().
Referenced by System.Data.DataColumn.DataColumn(), System.Data.DataKey.DataKey(), System.Data.DataTableReader.DataTableReader(), System.Data.DataTableReader.DataTableReader(), System.Data.DataTableReaderListener.DataTableReaderListener(), System.Data.DataViewSettingCollection.DataViewSettingCollection(), System.Data.RecordManager.RecordManager(), System.Data.RelatedView.RelatedView(), System.Data.ConstraintCollection.Add(), System.Data.DataRelationCollection.AddCore(), System.Data.DataView.ApplySort(), System.Data.DataColumnCollection.BaseAdd(), System.Data.DataTableCollection.BaseAdd(), System.Data.ConstraintCollection.BaseAdd(), System.Data.ConstraintCollection.BaseRemove(), System.Data.DataTableCollection.CanRemove(), System.Data.DataColumnCollection.CanRemove(), System.Data.DataRow.CheckColumn(), System.Data.DataTableCollection.Contains(), System.Data.RBTree< K >.CopyTo(), System.Data.ConstraintCollection.CopyTo(), System.Data.DataColumnCollection.CopyTo(), System.Data.DataRelationCollection.CopyTo(), System.Data.DataTableCollection.CopyTo(), System.Data.RBTree< K >.CopyTo(), System.Data.DataTableReader.GetSchemaTableFromDataTable(), System.Data.DataTableReader.GetValues(), System.Data.DataTableCollection.IndexOf(), System.Data.DataTable.InsertRow(), System.Data.DataSet.Merge(), System.Data.DataSet.Merge(), System.Data.DataSet.Merge(), System.Data.DataTable.Merge(), System.Data.Merger.MergeRows(), System.Data.ConstraintCollection.Remove(), System.Data.DataTableCollection.Remove(), System.Data.DataRelationCollection.RemoveCore(), System.Data.DataView.ToTable(), and System.Data.DataTableReaderListener.UpdataTable().