Terraria: System.Data.ExceptionBuilder.ConstraintViolation
ConstraintViolation() [2/2]
static Exception System.Data.ExceptionBuilder.ConstraintViolation (string constraint) inline static
Definition at line 285 of file ExceptionBuilder.cs.
    {
        return _Constraint(System.SR.Format(System.SR.DataConstraint_Violation, constraint));
    }
References System.Data.ExceptionBuilder._Constraint(), System.SR.DataConstraint_Violation, and System.SR.Format().
Referenced by System.Data.Constraint.CheckConstraint(), and System.Data.UniqueConstraint.CheckConstraint().