Terraria: System.Data.ExceptionBuilder.KeysToString
KeysToString()
static string System.Data.ExceptionBuilder.KeysToString (object[] keys) inline static
Definition at line 295 of file ExceptionBuilder.cs.
    {
        string text = string.Empty;
        for (int i = 0; i < keys.Length; i++)
        {
            text = text + Convert.ToString(keys[i], null) + ((i < keys.Length - 1) ? ", " : string.Empty);
        }
        return text;
    }
References System.keys, System.text, and System.Convert.ToString().
Referenced by System.Data.ExceptionBuilder.ForeignKeyViolation(), System.Data.ForeignKeyConstraint.IsConstraintViolated(), and System.Data.ExceptionBuilder.UniqueConstraintViolationText().