Terraria: System.Data.ExceptionBuilder.InternalRBTreeError
InternalRBTreeError()
static Exception System.Data.ExceptionBuilder.InternalRBTreeError (RBTreeError internalError) inline static package
Definition at line 1467 of file ExceptionBuilder.cs.
    {
        return _InvalidOperation(System.SR.Format(System.SR.RbTree_InvalidState, (int)internalError));
    }
References System.Data.ExceptionBuilder._InvalidOperation(), System.SR.Format(), and System.SR.RbTree_InvalidState.
Referenced by System.Data.RBTree< K >.RBTreeEnumerator.RBTreeEnumerator(), System.Data.RBTree< K >.TreePage.TreePage(), System.Data.DataRowCollection.ArrayRemove(), System.Data.DataRowCollection.DataRowTree.CompareNode(), System.Data.DataRowCollection.DataRowTree.CompareSateliteTreeNode(), System.Data.RBTree< K >.GetIndexOfPageWithFreeSlot(), System.Data.RBTree< K >.GetNewNode(), System.Data.RBTree< K >.GetNodeByIndex(), System.Data.RBTree< K >.RBDeleteFixup(), System.Data.RBTree< K >.RBDeleteX(), System.Data.RBTree< K >.RBInsert(), System.Data.RBTree< K >.SearchSubTree(), and System.Data.RBTree< K >.Successor().