Terraria: System.Data.ExceptionBuilder._DeletedRowInaccessible
_DeletedRowInaccessible()
static Exception System.Data.ExceptionBuilder._DeletedRowInaccessible (string error) inline static private
Definition at line 100 of file ExceptionBuilder.cs.
    {
        return TraceExceptionAsReturnValue(new DeletedRowInaccessibleException(error));
    }
References System.Data.ExceptionBuilder.TraceExceptionAsReturnValue().
Referenced by System.Data.ExceptionBuilder.DeletedRowInaccessible(), System.Data.ExceptionBuilder.EmptyDataTableReader(), System.Data.ExceptionBuilder.InvalidCurrentRowInDataTableReader(), and System.Data.ExceptionBuilder.RowAlreadyDeleted().