Terraria: System.Data.ExceptionBuilder.ArgumentOutOfRange
ArgumentOutOfRange()
static Exception System.Data.ExceptionBuilder.ArgumentOutOfRange (string paramName) inline static
Definition at line 145 of file ExceptionBuilder.cs.
    {
        return _ArgumentOutOfRange(paramName, System.SR.Format(System.SR.Data_ArgumentOutOfRange, paramName));
    }
References System.Data.ExceptionBuilder._ArgumentOutOfRange(), System.SR.Data_ArgumentOutOfRange, and System.SR.Format().
Referenced by System.Data.RBTree< K >.CopyTo(), System.Data.ConstraintCollection.CopyTo(), System.Data.DataColumnCollection.CopyTo(), System.Data.DataRelationCollection.CopyTo(), System.Data.DataTableCollection.CopyTo(), System.Data.RBTree< K >.CopyTo(), System.Data.DataTableReader.GetBoolean(), System.Data.DataTableReader.GetByte(), System.Data.DataTableReader.GetBytes(), System.Data.DataTableReader.GetChar(), System.Data.DataTableReader.GetChars(), System.Data.DataTableReader.GetDateTime(), System.Data.DataTableReader.GetDecimal(), System.Data.DataTableReader.GetDouble(), System.Data.DataTableReader.GetFieldType(), System.Data.DataTableReader.GetFloat(), System.Data.DataTableReader.GetGuid(), System.Data.DataTableReader.GetInt16(), System.Data.DataTableReader.GetInt32(), System.Data.DataTableReader.GetInt64(), System.Data.DataTableReader.GetName(), System.Data.DataTableReader.GetString(), System.Data.DataTableReader.GetValue(), System.Data.DataSet.HasChanges(), System.Data.DataTableReader.IsDBNull(), System.Data.DataTable.LoadRow(), and System.Data.DataTable.SetDataRowWithLoadOption().