Terraria: Terraria.RemoteServer.ClientReadCallBack
ClientReadCallBack()
void Terraria.RemoteServer.ClientReadCallBack (object state, int length) inline
    {
        try
        {
            if (!Netplay.Disconnect)
            {
                if (length == 0)
                {
                    Netplay.Disconnect = true;
                    Main.statusText = Language.GetTextValue("Net.LostConnection");
                }
                else if (Main.ignoreErrors)
                {
                    try
                    {
                        NetMessage.ReceiveBytes(ReadBuffer, length);
                    }
                    catch
                    {
                    }
                }
                else
                {
                    NetMessage.ReceiveBytes(ReadBuffer, length);
                }
            }
            IsReading = false;
        }
        catch (Exception value)
        {
            try
            {
                using StreamWriter streamWriter = new StreamWriter("client-crashlog.txt", append: true);
                streamWriter.WriteLine(DateTime.Now);
                streamWriter.WriteLine(value);
                streamWriter.WriteLine("");
            }
            catch
            {
            }
            Netplay.Disconnect = true;
        }
    }
References Terraria.Netplay.Disconnect, Terraria.Localization.Language.GetTextValue(), Terraria.Main.ignoreErrors, Terraria.RemoteServer.IsReading, Terraria.RemoteServer.ReadBuffer, and Terraria.NetMessage.ReceiveBytes().
Referenced by Terraria.Netplay.InnerClientLoop().