Terraria: MusicCueHolder.TryPlaying
TryPlaying()
void MusicCueHolder.TryPlaying (float volume) inline
     {
         LoadTrack(forceReload: false);
         if (_loadedCue.IsPrepared)
         {
             SetVolume(volume);
             if (!_loadedCue.IsPlaying)
             {
                 _loadedCue.Play();
             }
         }
     }
References _loadedCue, LoadTrack(), and SetVolume().
Referenced by RestartAndTryPlaying().