Terraria: ReLogic.Localization.IME.PlatformIme.Dispose
Dispose() [1/2]
void ReLogic.Localization.IME.PlatformIme.Dispose () inline inherited
Definition at line 86 of file PlatformIme.cs.
    {
        Dispose(disposing: true);
        GC.SuppressFinalize(this);
    }
References ReLogic.Localization.IME.PlatformIme.Dispose().
Referenced by ReLogic.Localization.IME.FnaIme.~FnaIme(), ReLogic.Localization.IME.PlatformIme.~PlatformIme(), ReLogic.Localization.IME.WinImm32Ime.~WinImm32Ime(), and ReLogic.Localization.IME.PlatformIme.Dispose().