Terraria: System.Diagnostics.StackFrameHelper.InitializeSourceInfo
InitializeSourceInfo()
void System.Diagnostics.StackFrameHelper.InitializeSourceInfo (int iSkip, bool fNeedFileInfo, Exception exception) inline package
Definition at line 73 of file StackFrameHelper.cs.
    {
        StackTrace.GetStackFramesInternal(this, iSkip, fNeedFileInfo, exception);
        if (!fNeedFileInfo || t_reentrancy > 0)
        {
            return;
        }
        t_reentrancy++;
        try
        {
            if (s_getSourceLineInfo == null)
            {
                Type type = Type.GetType("System.Diagnostics.StackTraceSymbols, System.Diagnostics.StackTrace, Version=4.0.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a", throwOnError: false);
                if (type == null)
                {
                    return;
                }
                Type[] types = new Type[12]
                {
                    typeof(Assembly),
                    typeof(string),
                    typeof(IntPtr),
                    typeof(int),
                    typeof(bool),
                    typeof(IntPtr),
                    typeof(int),
                    typeof(int),
                    typeof(int),
                    typeof(string).MakeByRefType(),
                    typeof(int).MakeByRefType(),
                    typeof(int).MakeByRefType()
                };
                MethodInfo method = type.GetMethod("GetSourceLineInfo", BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, null, types, null);
                if (method == null)
                {
                    return;
                }
                object target = Activator.CreateInstance(type);
                GetSourceLineInfoDelegate value = method.CreateDelegate<GetSourceLineInfoDelegate>(target);
                Interlocked.CompareExchange(ref s_getSourceLineInfo, value, null);
            }
            for (int i = 0; i < iFrameCount; i++)
            {
                if (rgiMethodToken[i] != 0)
                {
                    s_getSourceLineInfo(rgAssembly[i], rgAssemblyPath[i], rgLoadedPeAddress[i], rgiLoadedPeSize[i], rgiIsFileLayout[i], rgInMemoryPdbAddress[i], rgiInMemoryPdbSize[i], rgiMethodToken[i], rgiILOffset[i], out rgFilename[i], out rgiLineNumber[i], out rgiColumnNumber[i]);
                }
            }
        }
        catch
        {
        }
        finally
        {
            t_reentrancy--;
        }
    }
References System.Threading.Interlocked.CompareExchange(), System.Reflection.MethodInfo.CreateDelegate(), System.Activator.CreateInstance(), System.exception, System.Diagnostics.StackFrameHelper.GetSourceLineInfoDelegate(), System.Diagnostics.StackTrace.GetStackFramesInternal(), System.Type.GetType(), System.Diagnostics.StackFrameHelper.iFrameCount, System.Type.MakeByRefType(), System.Diagnostics.StackFrameHelper.rgAssembly, System.Diagnostics.StackFrameHelper.rgAssemblyPath, System.Diagnostics.StackFrameHelper.rgFilename, System.Diagnostics.StackFrameHelper.rgiColumnNumber, System.Diagnostics.StackFrameHelper.rgiILOffset, System.Diagnostics.StackFrameHelper.rgiInMemoryPdbSize, System.Diagnostics.StackFrameHelper.rgiIsFileLayout, System.Diagnostics.StackFrameHelper.rgiLineNumber, System.Diagnostics.StackFrameHelper.rgiLoadedPeSize, System.Diagnostics.StackFrameHelper.rgiMethodToken, System.Diagnostics.StackFrameHelper.rgInMemoryPdbAddress, System.Diagnostics.StackFrameHelper.rgLoadedPeAddress, System.Diagnostics.StackFrameHelper.s_getSourceLineInfo, System.Diagnostics.StackFrameHelper.t_reentrancy, System.type, and System.value.
Referenced by System.Diagnostics.StackFrame.BuildStackFrame().