Terraria: LanternSky.GenerateLanterns
GenerateLanterns()
void LanternSky.GenerateLanterns (bool onlyMissing) inline private
     {
         if (!onlyMissing)
         {
             _lanterns = new Lantern[Main.maxTilesY / 4];
         }
         for (int i = 0; i < _lanterns.Length; i++)
         {
             if (!onlyMissing || !_lanterns[i].Active)
             {
                 int num = (int)((double)Main.screenPosition.Y * 0.7 - (double)Main.screenHeight);
                 int minValue = (int)((double)num - Main.worldSurface * 16.0);
                 _lanterns[i].Position = new Vector2(_random.Next(0, Main.maxTilesX) * 16, _random.Next(minValue, num));
                 ResetLantern(i);
                 _lanterns[i].Active = true;
             }
         }
         _lanternsDrawing = _lanterns.Length;
     }
References _lanterns, _lanternsDrawing, _random, LanternSky.Lantern.Active, Active, Main.maxTilesX, Main.maxTilesY, UnifiedRandom.Next(), LanternSky.Lantern.Position, ResetLantern(), Main.screenHeight, Main.screenPosition, and Main.worldSurface.
Referenced by Activate(), and OnLoad().