Terraria: System.Diagnostics.StackFrameHelper.GetMethodBase
GetMethodBase()
MethodBase System.Diagnostics.StackFrameHelper.GetMethodBase (int i) inline
Definition at line 131 of file StackFrameHelper.cs.
    {
        IntPtr intPtr = rgMethodHandle[i];
        if (intPtr == IntPtr.Zero)
        {
            return null;
        }
        IRuntimeMethodInfo typicalMethodDefinition = RuntimeMethodHandle.GetTypicalMethodDefinition(new RuntimeMethodInfoStub(intPtr, this));
        return RuntimeType.GetMethodBase(typicalMethodDefinition);
    }
References System.RuntimeType.GetMethodBase(), System.RuntimeMethodHandle.GetTypicalMethodDefinition(), System.Diagnostics.StackFrameHelper.rgMethodHandle, and System.IntPtr.Zero.
Referenced by System.Diagnostics.StackFrame.StackFrame(), and System.Diagnostics.StackFrame.BuildStackFrame().