Terraria: System.Reflection.Metadata.Ecma335.UserStringHeap.GetString
GetString()
string System.Reflection.Metadata.Ecma335.UserStringHeap.GetString (UserStringHandle handle) inline package
Definition at line 14 of file UserStringHeap.cs.
    {
        if (!Block.PeekHeapValueOffsetAndSize(handle.GetHeapOffset(), out var offset, out var size))
        {
            return string.Empty;
        }
        return Block.PeekUtf16(offset, size & -2);
    }
References System.Reflection.Metadata.Ecma335.UserStringHeap.Block, System.handle, System.offset, System.Reflection.Internal.MemoryBlock.PeekHeapValueOffsetAndSize(), and System.Reflection.Internal.MemoryBlock.PeekUtf16().
Referenced by System.Reflection.Metadata.MetadataReader.GetUserString().