Terraria: ItemDropDatabase.RegisterBoss_Plantera
RegisterBoss_Plantera()
void ItemDropDatabase.RegisterBoss_Plantera () inline private
     {
         short type = 262;
         RegisterToNPC(type, ItemDropRule.BossBag(3328));
         RegisterToNPC(type, ItemDropRule.MasterModeCommonDrop(4934));
         RegisterToNPC(type, ItemDropRule.MasterModeDropOnAllPlayers(4806, _masterModeDropRng));
         LeadingConditionRule leadingConditionRule = new LeadingConditionRule(new Conditions.NotExpert());
         RegisterToNPC(type, leadingConditionRule);
         LeadingConditionRule leadingConditionRule2 = new LeadingConditionRule(new Conditions.FirstTimeKillingPlantera());
         leadingConditionRule.OnSuccess(leadingConditionRule2);
         leadingConditionRule.OnSuccess(ItemDropRule.Common(2109, 7));
         leadingConditionRule.OnSuccess(ItemDropRule.Common(1141));
         leadingConditionRule.OnSuccess(ItemDropRule.Common(1182, 20));
         leadingConditionRule.OnSuccess(ItemDropRule.Common(1305, 50));
         leadingConditionRule.OnSuccess(ItemDropRule.Common(1157, 4));
         leadingConditionRule.OnSuccess(ItemDropRule.Common(3021, 10));
         IItemDropRule itemDropRule = ItemDropRule.Common(758);
         itemDropRule.OnSuccess(ItemDropRule.Common(771, 1, 50, 150), hideLootReport: true);
         leadingConditionRule2.OnSuccess(itemDropRule, hideLootReport: true);
         leadingConditionRule2.OnFailedConditions(new OneFromRulesRule(1, itemDropRule, ItemDropRule.Common(1255), ItemDropRule.Common(788), ItemDropRule.Common(1178), ItemDropRule.Common(1259), ItemDropRule.Common(1155), ItemDropRule.Common(3018)));
     }
References _masterModeDropRng, ItemDropRule.BossBag(), ItemDropRule.Common(), ItemDropRule.MasterModeCommonDrop(), ItemDropRule.MasterModeDropOnAllPlayers(), and RegisterToNPC().
Referenced by RegisterBosses().