Terraria: ItemDropDatabase.RegisterMartianDrops
RegisterMartianDrops()
void ItemDropDatabase.RegisterMartianDrops () inline private
     {
         RegisterToMultipleNPCs(ItemDropRule.Common(2860, 8, 8, 20), 520, 383, 389, 385, 382, 381, 390, 386);
         int[] npcNetIds = new int[8] { 520, 383, 389, 385, 382, 381, 390, 386 };
         RegisterToMultipleNPCs(ItemDropRule.Common(2798, 800), npcNetIds);
         RegisterToMultipleNPCs(ItemDropRule.Common(2800, 800), npcNetIds);
         RegisterToMultipleNPCs(ItemDropRule.Common(2882, 800), npcNetIds);
         int[] npcNetIds2 = new int[3] { 383, 389, 386 };
         RegisterToMultipleNPCs(ItemDropRule.Common(2806, 200), npcNetIds2);
         RegisterToMultipleNPCs(ItemDropRule.Common(2807, 200), npcNetIds2);
         RegisterToMultipleNPCs(ItemDropRule.Common(2808, 200), npcNetIds2);
         int[] npcNetIds3 = new int[4] { 385, 382, 381, 390 };
         RegisterToMultipleNPCs(ItemDropRule.Common(2803, 200), npcNetIds3);
         RegisterToMultipleNPCs(ItemDropRule.Common(2804, 200), npcNetIds3);
         RegisterToMultipleNPCs(ItemDropRule.Common(2805, 200), npcNetIds3);
         RegisterToNPC(395, ItemDropRule.OneFromOptionsNotScalingWithLuck(1, 2797, 2749, 2795, 2796, 2880, 2769));
         RegisterToNPC(395, ItemDropRule.MasterModeCommonDrop(4939));
         RegisterToNPC(395, ItemDropRule.MasterModeDropOnAllPlayers(4815, _masterModeDropRng));
         RegisterToNPC(390, ItemDropRule.Common(2771, 30));
     }
References _masterModeDropRng, ItemDropRule.Common(), ItemDropRule.MasterModeCommonDrop(), ItemDropRule.MasterModeDropOnAllPlayers(), ItemDropRule.OneFromOptionsNotScalingWithLuck(), RegisterToMultipleNPCs(), and RegisterToNPC().
Referenced by Populate().