Terraria: ItemDropDatabase.RegisterEclipse
RegisterEclipse()
void ItemDropDatabase.RegisterEclipse () inline private
     {
         RegisterToNPC(461, ItemDropRule.ExpertGetsRerolls(497, 50, 1));
         RegisterToMultipleNPCs(ItemDropRule.ExpertGetsRerolls(900, 35, 1), 159, 158);
         RegisterToNPC(251, ItemDropRule.ExpertGetsRerolls(1311, 15, 1));
         RegisterToNPC(251, ItemDropRule.Common(5239, 15));
         RegisterToNPC(251, ItemDropRule.Common(5236, 15));
         RegisterToNPC(477, ItemDropRule.Common(5237, 15));
         RegisterToNPC(253, ItemDropRule.Common(5223, 60));
         RegisterToNPC(460, ItemDropRule.Common(5227, 60));
         RegisterToNPC(469, ItemDropRule.Common(5260, 60));
         RegisterToMultipleNPCs(ItemDropRule.Common(5261, 450), 166, 162);
         RegisterToNPC(462, ItemDropRule.Common(5262, 60));
         Conditions.DownedAllMechBosses condition = new Conditions.DownedAllMechBosses();
         Conditions.DownedPlantera condition2 = new Conditions.DownedPlantera();
         IItemDropRule rule = RegisterToNPC(477, new LeadingConditionRule(condition));
         IItemDropRule rule2 = rule.OnSuccess(new LeadingConditionRule(condition2));
         rule.OnSuccess(ItemDropRule.ExpertGetsRerolls(1570, 4, 1));
         rule2.OnSuccess(ItemDropRule.ExpertGetsRerolls(2770, 20, 1));
         rule2.OnSuccess(ItemDropRule.ExpertGetsRerolls(3292, 3, 1));
         RegisterToNPC(253, new LeadingConditionRule(condition)).OnSuccess(ItemDropRule.ExpertGetsRerolls(1327, 40, 1));
         RegisterToNPC(460, new LeadingConditionRule(condition2)).OnSuccess(ItemDropRule.ExpertGetsRerolls(3098, 40, 1));
         RegisterToNPC(460, ItemDropRule.ExpertGetsRerolls(4740, 50, 1));
         RegisterToNPC(460, ItemDropRule.ExpertGetsRerolls(4741, 50, 1));
         RegisterToNPC(460, ItemDropRule.ExpertGetsRerolls(4742, 50, 1));
         RegisterToNPC(468, new LeadingConditionRule(condition2)).OnSuccess(ItemDropRule.ExpertGetsRerolls(3105, 40, 1));
         RegisterToNPC(468, ItemDropRule.ExpertGetsRerolls(4738, 50, 1));
         RegisterToNPC(468, ItemDropRule.ExpertGetsRerolls(4739, 50, 1));
         RegisterToNPC(466, new LeadingConditionRule(condition2)).OnSuccess(ItemDropRule.ExpertGetsRerolls(3106, 40, 1));
         RegisterToNPC(467, new LeadingConditionRule(condition2)).OnSuccess(ItemDropRule.ExpertGetsRerolls(3249, 30, 1));
         IItemDropRule itemDropRule = ItemDropRule.Common(3107, 25);
         IItemDropRule itemDropRule2 = ItemDropRule.WithRerolls(3107, 1, 25);
         itemDropRule.OnSuccess(ItemDropRule.Common(3108, 1, 100, 200), hideLootReport: true);
         itemDropRule2.OnSuccess(ItemDropRule.Common(3108, 1, 100, 200), hideLootReport: true);
         RegisterToNPC(463, new LeadingConditionRule(condition2)).OnSuccess(new DropBasedOnExpertMode(itemDropRule, itemDropRule2));
     }
References ItemDropRule.Common(), ItemDropRule.ExpertGetsRerolls(), RegisterToMultipleNPCs(), RegisterToNPC(), and ItemDropRule.WithRerolls().
Referenced by Populate().