Terraria: ItemDropDatabase.RegisterBosses
RegisterBosses()
void ItemDropDatabase.RegisterBosses () inline private
     {
         RegisterBoss_EOC();
         RegisterBoss_BOC();
         RegisterBoss_EOW();
         RegisterBoss_QueenBee();
         RegisterBoss_Skeletron();
         RegisterBoss_WOF();
         RegisterBoss_AncientCultist();
         RegisterBoss_MoonLord();
         RegisterBoss_LunarTowers();
         RegisterBoss_Betsy();
         RegisterBoss_Golem();
         RegisterBoss_DukeFishron();
         RegisterBoss_SkeletronPrime();
         RegisterBoss_TheDestroyer();
         RegisterBoss_Twins();
         RegisterBoss_Plantera();
         RegisterBoss_KingSlime();
         RegisterBoss_FrostMoon();
         RegisterBoss_PumpkinMoon();
         RegisterBoss_HallowBoss();
         RegisterBoss_QueenSlime();
         RegisterBoss_Deerclops();
     }
References RegisterBoss_AncientCultist(), RegisterBoss_Betsy(), RegisterBoss_BOC(), RegisterBoss_Deerclops(), RegisterBoss_DukeFishron(), RegisterBoss_EOC(), RegisterBoss_EOW(), RegisterBoss_FrostMoon(), RegisterBoss_Golem(), RegisterBoss_HallowBoss(), RegisterBoss_KingSlime(), RegisterBoss_LunarTowers(), RegisterBoss_MoonLord(), RegisterBoss_Plantera(), RegisterBoss_PumpkinMoon(), RegisterBoss_QueenBee(), RegisterBoss_QueenSlime(), RegisterBoss_Skeletron(), RegisterBoss_SkeletronPrime(), RegisterBoss_TheDestroyer(), RegisterBoss_Twins(), and RegisterBoss_WOF().
Referenced by Populate().