Terraria: ItemDropDatabase.RegisterBossTrophies
RegisterBossTrophies()
void ItemDropDatabase.RegisterBossTrophies () inline private
     {
         Conditions.LegacyHack_IsABoss condition = new Conditions.LegacyHack_IsABoss();
         RegisterToNPC(4, ItemDropRule.ByCondition(condition, 1360, 10));
         RegisterToNPC(13, ItemDropRule.ByCondition(condition, 1361, 10));
         RegisterToNPC(14, ItemDropRule.ByCondition(condition, 1361, 10));
         RegisterToNPC(15, ItemDropRule.ByCondition(condition, 1361, 10));
         RegisterToNPC(266, ItemDropRule.ByCondition(condition, 1362, 10));
         RegisterToNPC(35, ItemDropRule.ByCondition(condition, 1363, 10));
         RegisterToNPC(222, ItemDropRule.ByCondition(condition, 1364, 10));
         RegisterToNPC(113, ItemDropRule.ByCondition(condition, 1365, 10));
         RegisterToNPC(134, ItemDropRule.ByCondition(condition, 1366, 10));
         RegisterToNPC(127, ItemDropRule.ByCondition(condition, 1367, 10));
         RegisterToNPC(262, ItemDropRule.ByCondition(condition, 1370, 10));
         RegisterToNPC(245, ItemDropRule.ByCondition(condition, 1371, 10));
         RegisterToNPC(50, ItemDropRule.ByCondition(condition, 2489, 10));
         RegisterToNPC(370, ItemDropRule.ByCondition(condition, 2589, 10));
         RegisterToNPC(439, ItemDropRule.ByCondition(condition, 3357, 10));
         RegisterToNPC(395, ItemDropRule.ByCondition(condition, 3358, 10));
         RegisterToNPC(398, ItemDropRule.ByCondition(condition, 3595, 10));
         RegisterToNPC(636, ItemDropRule.ByCondition(condition, 4783, 10));
         RegisterToNPC(657, ItemDropRule.ByCondition(condition, 4958, 10));
         RegisterToNPC(668, ItemDropRule.ByCondition(condition, 5108, 10));
         RegisterToNPC(125, ItemDropRule.Common(1368, 10));
         RegisterToNPC(126, ItemDropRule.Common(1369, 10));
         RegisterToNPC(491, ItemDropRule.Common(3359, 10));
         RegisterToNPC(551, ItemDropRule.Common(3866, 10));
         RegisterToNPC(564, ItemDropRule.Common(3867, 10));
         RegisterToNPC(565, ItemDropRule.Common(3867, 10));
         RegisterToNPC(576, ItemDropRule.Common(3868, 10));
         RegisterToNPC(577, ItemDropRule.Common(3868, 10));
     }
References ItemDropRule.ByCondition(), ItemDropRule.Common(), and RegisterToNPC().
Referenced by Populate().