Terraria: ItemDropDatabase.RegisterBoss_BOC
RegisterBoss_BOC()
void ItemDropDatabase.RegisterBoss_BOC () inline private
     {
         Conditions.NotExpert condition = new Conditions.NotExpert();
         short type = 266;
         RegisterToNPC(type, ItemDropRule.BossBag(3321));
         RegisterToNPC(type, ItemDropRule.MasterModeCommonDrop(4926));
         RegisterToNPC(type, ItemDropRule.MasterModeDropOnAllPlayers(4800, _masterModeDropRng));
         RegisterToNPC(type, ItemDropRule.ByCondition(condition, 880, 1, 40, 90));
         RegisterToNPC(type, ItemDropRule.ByCondition(condition, 2104, 7));
         RegisterToNPC(type, ItemDropRule.ByCondition(condition, 3060, 20));
         short type2 = 267;
         RegisterToNPC(type2, new DropBasedOnMasterAndExpertMode(new CommonDrop(1329, 3, 2, 5, 2), new CommonDrop(1329, 3, 1, 3, 2), new CommonDrop(1329, 4, 1, 2, 2)));
         RegisterToNPC(type2, new DropBasedOnMasterAndExpertMode(new CommonDrop(880, 3, 5, 12, 2), new CommonDrop(880, 3, 5, 7, 2), new CommonDrop(880, 3, 2, 4, 2)));
     }
References _masterModeDropRng, ItemDropRule.BossBag(), ItemDropRule.ByCondition(), ItemDropRule.MasterModeCommonDrop(), ItemDropRule.MasterModeDropOnAllPlayers(), and RegisterToNPC().
Referenced by RegisterBosses().