Terraria: ItemDropDatabase.RegisterPirateDrops
RegisterPirateDrops()
void ItemDropDatabase.RegisterPirateDrops () inline private
     {
         int[] npcNetIds = new int[4] { 212, 213, 214, 215 };
         RegisterToMultipleNPCs(ItemDropRule.Common(905, 4000), npcNetIds);
         RegisterToMultipleNPCs(ItemDropRule.Common(855, 2000), npcNetIds);
         RegisterToMultipleNPCs(ItemDropRule.Common(854, 1000), npcNetIds);
         RegisterToMultipleNPCs(ItemDropRule.Common(2584, 1000), npcNetIds);
         RegisterToMultipleNPCs(ItemDropRule.Common(3033, 500), npcNetIds);
         RegisterToMultipleNPCs(ItemDropRule.Common(672, 200), npcNetIds);
         RegisterToMultipleNPCs(ItemDropRule.Common(1277, 500), npcNetIds);
         RegisterToMultipleNPCs(ItemDropRule.Common(1278, 500), npcNetIds);
         RegisterToMultipleNPCs(ItemDropRule.Common(1279, 500), npcNetIds);
         RegisterToMultipleNPCs(ItemDropRule.Common(1280, 500), npcNetIds);
         RegisterToMultipleNPCs(ItemDropRule.Common(1704, 300), npcNetIds);
         RegisterToMultipleNPCs(ItemDropRule.Common(1705, 300), npcNetIds);
         RegisterToMultipleNPCs(ItemDropRule.Common(1710, 300), npcNetIds);
         RegisterToMultipleNPCs(ItemDropRule.Common(1716, 300), npcNetIds);
         RegisterToMultipleNPCs(ItemDropRule.Common(1720, 300), npcNetIds);
         RegisterToMultipleNPCs(ItemDropRule.Common(2379, 300), npcNetIds);
         RegisterToMultipleNPCs(ItemDropRule.Common(2389, 300), npcNetIds);
         RegisterToMultipleNPCs(ItemDropRule.Common(2405, 300), npcNetIds);
         RegisterToMultipleNPCs(ItemDropRule.Common(2843, 300), npcNetIds);
         RegisterToMultipleNPCs(ItemDropRule.Common(3885, 300), npcNetIds);
         RegisterToMultipleNPCs(ItemDropRule.Common(2663, 300), npcNetIds);
         RegisterToMultipleNPCs(ItemDropRule.Common(3904, 150, 80, 130), npcNetIds);
         RegisterToMultipleNPCs(ItemDropRule.Common(3910, 300), npcNetIds);
         RegisterToMultipleNPCs(ItemDropRule.Common(2238, 300), npcNetIds);
         RegisterToMultipleNPCs(ItemDropRule.Common(2133, 300), npcNetIds);
         RegisterToMultipleNPCs(ItemDropRule.Common(2137, 300), npcNetIds);
         RegisterToMultipleNPCs(ItemDropRule.Common(2143, 300), npcNetIds);
         RegisterToMultipleNPCs(ItemDropRule.Common(2147, 300), npcNetIds);
         RegisterToMultipleNPCs(ItemDropRule.Common(2151, 300), npcNetIds);
         RegisterToMultipleNPCs(ItemDropRule.Common(2155, 300), npcNetIds);
         RegisterToMultipleNPCs(ItemDropRule.Common(3263, 500), npcNetIds);
         RegisterToMultipleNPCs(ItemDropRule.Common(3264, 500), npcNetIds);
         RegisterToMultipleNPCs(ItemDropRule.Common(3265, 500), npcNetIds);
         RegisterToNPC(216, ItemDropRule.Common(905, 1000));
         RegisterToNPC(216, ItemDropRule.Common(855, 500));
         RegisterToNPC(216, ItemDropRule.Common(854, 250));
         RegisterToNPC(216, ItemDropRule.Common(2584, 250));
         RegisterToNPC(216, ItemDropRule.Common(3033, 125));
         RegisterToNPC(216, ItemDropRule.Common(672, 50));
         RegisterToNPC(491, ItemDropRule.Common(905, 50));
         RegisterToNPC(491, ItemDropRule.Common(855, 15));
         RegisterToNPC(491, ItemDropRule.Common(854, 15));
         RegisterToNPC(491, ItemDropRule.Common(2584, 15));
         RegisterToNPC(491, ItemDropRule.Common(3033, 15));
         RegisterToNPC(491, ItemDropRule.Common(4471, 20));
         RegisterToNPC(491, ItemDropRule.Common(672, 10));
         RegisterToNPC(491, ItemDropRule.MasterModeCommonDrop(4940));
         RegisterToNPC(491, ItemDropRule.MasterModeDropOnAllPlayers(4792, _masterModeDropRng));
         RegisterToNPC(491, ItemDropRule.OneFromOptions(1, 1704, 1705, 1710, 1716, 1720, 2379, 2389, 2405, 2843, 3885, 2663, 3910, 2238, 2133, 2137, 2143, 2147, 2151, 2155));
     }
References _masterModeDropRng, ItemDropRule.Common(), ItemDropRule.MasterModeCommonDrop(), ItemDropRule.MasterModeDropOnAllPlayers(), ItemDropRule.OneFromOptions(), RegisterToMultipleNPCs(), and RegisterToNPC().
Referenced by Populate().