Terraria: ItemDropDatabase.RegisterBloodMoonFishing
RegisterBloodMoonFishing()
void ItemDropDatabase.RegisterBloodMoonFishing () inline private
     {
         RegisterToMultipleNPCs(ItemDropRule.Common(4608, 2, 4, 6), 587, 586);
         RegisterToMultipleNPCs(ItemDropRule.Common(4608, 2, 7, 10), 620, 621, 618);
         RegisterToMultipleNPCs(ItemDropRule.OneFromOptions(8, 4273), 587, 586);
         RegisterToMultipleNPCs(ItemDropRule.OneFromOptions(8, 4381), 587, 586);
         RegisterToMultipleNPCs(ItemDropRule.OneFromOptions(8, 4325), 587, 586);
         RegisterToMultipleNPCs(ItemDropRule.Common(3213, 15), 587, 586);
         RegisterToNPC(620, ItemDropRule.Common(4270, 8));
         RegisterToNPC(620, ItemDropRule.Common(4317, 8));
         RegisterToNPC(621, ItemDropRule.Common(4272, 8));
         RegisterToNPC(621, ItemDropRule.Common(4317, 8));
         RegisterToNPC(618, ItemDropRule.NormalvsExpert(4269, 2, 1));
         RegisterToNPC(618, ItemDropRule.Common(4054, 10));
         RegisterToNPC(618, ItemDropRule.NormalvsExpert(4271, 2, 1));
         RegisterToMultipleNPCs(ItemDropRule.Common(4271, 5), 53, 536);
         Conditions.IsBloodMoonAndNotFromStatue condition = new Conditions.IsBloodMoonAndNotFromStatue();
         RegisterToMultipleNPCs(ItemDropRule.ByCondition(condition, 4271, 100), 489, 490);
         RegisterToMultipleNPCs(ItemDropRule.ByCondition(condition, 4271, 25), 587, 586, 621, 620);
     }
References ItemDropRule.ByCondition(), ItemDropRule.Common(), ItemDropRule.NormalvsExpert(), ItemDropRule.OneFromOptions(), RegisterToMultipleNPCs(), and RegisterToNPC().
Referenced by Populate().