Terraria: System.Reflection.RuntimeCustomAttributeData.GetCustomAttributes
GetCustomAttributes() [5/5]
static IList< CustomAttributeData > System.Reflection.RuntimeCustomAttributeData.GetCustomAttributes (RuntimeModule module, int tkTarget) inline static private
Definition at line 274 of file RuntimeCustomAttributeData.cs.
    {
        CustomAttributeRecord[] customAttributeRecords = GetCustomAttributeRecords(module, tkTarget);
        if (customAttributeRecords.Length == 0)
        {
            return Array.Empty<CustomAttributeData>();
        }
        CustomAttributeData[] array = new CustomAttributeData[customAttributeRecords.Length];
        for (int i = 0; i < customAttributeRecords.Length; i++)
        {
            array[i] = new RuntimeCustomAttributeData(module, customAttributeRecords[i].tkCtor, in customAttributeRecords[i].blob);
        }
        return Array.AsReadOnly(array);
    }
References System.Reflection.RuntimeCustomAttributeData.RuntimeCustomAttributeData(), System.array, and System.Reflection.RuntimeCustomAttributeData.GetCustomAttributeRecords().
Referenced by System.Reflection.RuntimeCustomAttributeData.GetCustomAttributesInternal(), System.Reflection.RuntimeCustomAttributeData.GetCustomAttributesInternal(), System.Reflection.RuntimeCustomAttributeData.GetCustomAttributesInternal(), System.Reflection.RuntimeCustomAttributeData.GetCustomAttributesInternal(), System.Reflection.RuntimeCustomAttributeData.GetCustomAttributesInternal(), System.Reflection.RuntimeCustomAttributeData.GetCustomAttributesInternal(), System.Reflection.RuntimeCustomAttributeData.GetCustomAttributesInternal(), System.Reflection.RuntimeCustomAttributeData.GetCustomAttributesInternal(), and System.Reflection.RuntimeCustomAttributeData.GetCustomAttributesInternal().