Terraria: System.Reflection.RuntimeCustomAttributeData.GetCustomAttributesInternal
GetCustomAttributesInternal() [4/9]
static IList< CustomAttributeData > System.Reflection.RuntimeCustomAttributeData.GetCustomAttributesInternal (RuntimeFieldInfo target) inline static package
Definition at line 90 of file RuntimeCustomAttributeData.cs.
    {
        IList<CustomAttributeData> customAttributes = GetCustomAttributes(target.GetRuntimeModule(), target.MetadataToken);
        RuntimeType.ListBuilder<Attribute> pcas = default(RuntimeType.ListBuilder<Attribute>);
        PseudoCustomAttribute.GetCustomAttributes(target, (RuntimeType)typeof(object), ref pcas);
        if (pcas.Count <= 0)
        {
            return customAttributes;
        }
        return GetCombinedList(customAttributes, ref pcas);
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Reflection.RuntimeCustomAttributeData.GetCombinedList(), System.Reflection.RuntimeCustomAttributeData.GetCustomAttributes(), System.Reflection.PseudoCustomAttribute.GetCustomAttributes(), System.Reflection.RuntimeFieldInfo.GetRuntimeModule(), and System.Reflection.MemberInfo.MetadataToken.