Terraria: System.Reflection.RuntimeCustomAttributeData.RuntimeCustomAttributeData
RuntimeCustomAttributeData() [1/2]
System.Reflection.RuntimeCustomAttributeData.RuntimeCustomAttributeData (RuntimeModule scope, MetadataToken caCtorToken, in ConstArray blob) inline private
Definition at line 319 of file RuntimeCustomAttributeData.cs.
    {
        m_scope = scope;
        m_ctor = (RuntimeConstructorInfo)RuntimeType.GetMethodBase(scope, caCtorToken);
        if (m_ctor.DeclaringType.IsGenericType)
        {
            Type type = scope.ResolveType(scope.MetadataImport.GetParentToken(caCtorToken), null, null);
            m_ctor = (RuntimeConstructorInfo)scope.ResolveMethod(caCtorToken, type.GenericTypeArguments, null).MethodHandle.GetMethodInfo();
        }
        ParameterInfo[] parametersNoCopy = m_ctor.GetParametersNoCopy();
        m_ctorParams = new CustomAttributeCtorParameter[parametersNoCopy.Length];
        for (int i = 0; i < parametersNoCopy.Length; i++)
        {
            m_ctorParams[i] = new CustomAttributeCtorParameter(InitCustomAttributeType((RuntimeType)parametersNoCopy[i].ParameterType));
        }
        FieldInfo[] fields = m_ctor.DeclaringType.GetFields(BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic);
        PropertyInfo[] properties = m_ctor.DeclaringType.GetProperties(BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic);
        m_namedParams = new CustomAttributeNamedParameter[properties.Length + fields.Length];
        for (int j = 0; j < fields.Length; j++)
        {
            m_namedParams[j] = new CustomAttributeNamedParameter(fields[j].Name, CustomAttributeEncoding.Field, InitCustomAttributeType((RuntimeType)fields[j].FieldType));
        }
        for (int k = 0; k < properties.Length; k++)
        {
            m_namedParams[k + fields.Length] = new CustomAttributeNamedParameter(properties[k].Name, CustomAttributeEncoding.Property, InitCustomAttributeType((RuntimeType)properties[k].PropertyType));
        }
        m_members = new MemberInfo[fields.Length + properties.Length];
        fields.CopyTo(m_members, 0);
        properties.CopyTo(m_members, fields.Length);
        CustomAttributeEncodedArgument.ParseAttributeArguments(blob, ref m_ctorParams, ref m_namedParams, m_scope);
    }
References System.Reflection.MemberInfo.DeclaringType, System.Type.GetFields(), System.RuntimeType.GetMethodBase(), System.Reflection.MethodBase.GetParametersNoCopy(), System.Reflection.MetadataImport.GetParentToken(), System.Type.GetProperties(), System.Reflection.RuntimeCustomAttributeData.InitCustomAttributeType(), System.Type.IsGenericType, System.Reflection.RuntimeCustomAttributeData.m_ctor, System.Reflection.RuntimeCustomAttributeData.m_ctorParams, System.Reflection.RuntimeCustomAttributeData.m_members, System.Reflection.RuntimeCustomAttributeData.m_namedParams, System.Reflection.RuntimeCustomAttributeData.m_scope, System.Reflection.RuntimeModule.MetadataImport, System.Reflection.Name, System.Reflection.CustomAttributeEncodedArgument.ParseAttributeArguments(), System.Reflection.RuntimeModule.ResolveMethod(), System.Reflection.RuntimeModule.ResolveType(), and System.type.
Referenced by System.Reflection.RuntimeCustomAttributeData.GetCombinedList(), and System.Reflection.RuntimeCustomAttributeData.GetCustomAttributes().