Terraria: System.Reflection.RuntimeCustomAttributeData.InitCustomAttributeType
InitCustomAttributeType()
static CustomAttributeType System.Reflection.RuntimeCustomAttributeData.InitCustomAttributeType (RuntimeType parameterType) inline static private
Definition at line 255 of file RuntimeCustomAttributeData.cs.
    {
        CustomAttributeEncoding customAttributeEncoding = TypeToCustomAttributeEncoding(parameterType);
        CustomAttributeEncoding customAttributeEncoding2 = CustomAttributeEncoding.Undefined;
        CustomAttributeEncoding encodedEnumType = CustomAttributeEncoding.Undefined;
        string enumName = null;
        if (customAttributeEncoding == CustomAttributeEncoding.Array)
        {
            parameterType = (RuntimeType)parameterType.GetElementType();
            customAttributeEncoding2 = TypeToCustomAttributeEncoding(parameterType);
        }
        if (customAttributeEncoding == CustomAttributeEncoding.Enum || customAttributeEncoding2 == CustomAttributeEncoding.Enum)
        {
            encodedEnumType = TypeToCustomAttributeEncoding((RuntimeType)Enum.GetUnderlyingType(parameterType));
            enumName = parameterType.AssemblyQualifiedName;
        }
        return new CustomAttributeType(customAttributeEncoding, customAttributeEncoding2, encodedEnumType, enumName);
    }
References System.Enum.GetUnderlyingType(), and System.Reflection.RuntimeCustomAttributeData.TypeToCustomAttributeEncoding().
Referenced by System.Reflection.RuntimeCustomAttributeData.RuntimeCustomAttributeData().