Terraria: ArmorShaderData.Apply
Apply() [2/2]
virtual void ArmorShaderData.Apply (Entity entity, DrawData? drawData = null) inline virtual
Reimplemented in TwilightDyeShaderData, TeamArmorShaderData, and ReflectiveArmorShaderData.
     {
         base.Shader.Parameters["uColor"].SetValue(_uColor);
         base.Shader.Parameters["uSaturation"].SetValue(_uSaturation);
         base.Shader.Parameters["uSecondaryColor"].SetValue(_uSecondaryColor);
         base.Shader.Parameters["uTime"].SetValue(Main.GlobalTimeWrappedHourly);
         base.Shader.Parameters["uOpacity"].SetValue(_uOpacity);
         base.Shader.Parameters["uTargetPosition"].SetValue(_uTargetPosition);
         if (drawData.HasValue)
         {
             DrawData value = drawData.Value;
             Vector4 value2 = ((!value.sourceRect.HasValue) ? new Vector4(0f, 0f, value.texture.Width, value.texture.Height) : new Vector4(value.sourceRect.Value.X, value.sourceRect.Value.Y, value.sourceRect.Value.Width, value.sourceRect.Value.Height));
             base.Shader.Parameters["uSourceRect"].SetValue(value2);
             base.Shader.Parameters["uLegacyArmorSourceRect"].SetValue(value2);
             base.Shader.Parameters["uWorldPosition"].SetValue(Main.screenPosition + value.position);
             base.Shader.Parameters["uImageSize0"].SetValue(new Vector2(value.texture.Width, value.texture.Height));
             base.Shader.Parameters["uLegacyArmorSheetSize"].SetValue(new Vector2(value.texture.Width, value.texture.Height));
             base.Shader.Parameters["uRotation"].SetValue(value.rotation * (value.effect.HasFlag(SpriteEffects.FlipHorizontally) ? (-1f) : 1f));
             base.Shader.Parameters["uDirection"].SetValue((!value.effect.HasFlag(SpriteEffects.FlipHorizontally)) ? 1 : (-1));
         }
         else
         {
             Vector4 value3 = new Vector4(0f, 0f, 4f, 4f);
             base.Shader.Parameters["uSourceRect"].SetValue(value3);
             base.Shader.Parameters["uLegacyArmorSourceRect"].SetValue(value3);
             base.Shader.Parameters["uRotation"].SetValue(0f);
         }
         if (_uImage != null)
         {
             Main.graphics.GraphicsDevice.Textures[1] = _uImage.Value;
             base.Shader.Parameters["uImageSize1"].SetValue(new Vector2(_uImage.Width(), _uImage.Height()));
         }
         if (entity != null)
         {
             base.Shader.Parameters["uDirection"].SetValue((float)entity.direction);
         }
         if (entity is Player { bodyFrame: var bodyFrame })
         {
             base.Shader.Parameters["uLegacyArmorSourceRect"].SetValue(new Vector4(bodyFrame.X, bodyFrame.Y, bodyFrame.Width, bodyFrame.Height));
             base.Shader.Parameters["uLegacyArmorSheetSize"].SetValue(new Vector2(40f, 1120f));
         }
         Apply();
     }
References _uColor, _uImage, _uOpacity, _uSaturation, _uSecondaryColor, _uTargetPosition, ShaderData.Apply(), Entity.direction, DrawData.effect, Main.GlobalTimeWrappedHourly, Main.graphics, DrawData.position, DrawData.rotation, Main.screenPosition, DrawData.sourceRect, DrawData.texture, and Asset< T >.Value.
Referenced by TeamArmorShaderData.Apply(), and Main.DrawDust().