Terraria: System.Security.IdentityHelper.ToBase32StringSuitableForDirName
ToBase32StringSuitableForDirName()
static string System.Security.IdentityHelper.ToBase32StringSuitableForDirName (byte[] buff) inline static package
Definition at line 54 of file IdentityHelper.cs.
    {
        StringBuilder stringBuilder = new StringBuilder();
        int num = buff.Length;
        int num2 = 0;
        do
        {
            byte b = (byte)((num2 < num) ? buff[num2++] : 0);
            byte b2 = (byte)((num2 < num) ? buff[num2++] : 0);
            byte b3 = (byte)((num2 < num) ? buff[num2++] : 0);
            byte b4 = (byte)((num2 < num) ? buff[num2++] : 0);
            byte b5 = (byte)((num2 < num) ? buff[num2++] : 0);
            stringBuilder.Append(s_base32Char[b & 0x1F]);
            stringBuilder.Append(s_base32Char[b2 & 0x1F]);
            stringBuilder.Append(s_base32Char[b3 & 0x1F]);
            stringBuilder.Append(s_base32Char[b4 & 0x1F]);
            stringBuilder.Append(s_base32Char[b5 & 0x1F]);
            stringBuilder.Append(s_base32Char[((b & 0xE0) >> 5) | ((b4 & 0x60) >> 2)]);
            stringBuilder.Append(s_base32Char[((b2 & 0xE0) >> 5) | ((b5 & 0x60) >> 2)]);
            b3 >>= 5;
            if ((b4 & 0x80u) != 0)
            {
                b3 = (byte)(b3 | 8u);
            }
            if ((b5 & 0x80u) != 0)
            {
                b3 = (byte)(b3 | 0x10u);
            }
            stringBuilder.Append(s_base32Char[b3]);
        }
        while (num2 < num);
        return stringBuilder.ToString();
    }
References System.Text.StringBuilder.Append(), System.Security.IdentityHelper.s_base32Char, and System.Text.StringBuilder.ToString().
Referenced by System.Security.IdentityHelper.GetStrongHashSuitableForObjectName().