Terraria: Terraria.MessageBuffer.Reset
Reset()
void Terraria.MessageBuffer.Reset () inline
Definition at line 67 of file MessageBuffer.cs.
    {
        Array.Clear(readBuffer, 0, readBuffer.Length);
        Array.Clear(writeBuffer, 0, writeBuffer.Length);
        writeLocked = false;
        messageLength = 0;
        totalData = 0;
        spamCount = 0;
        broadcast = false;
        checkBytes = false;
        ResetReader();
        ResetWriter();
    }
References Terraria.MessageBuffer.broadcast, Terraria.MessageBuffer.checkBytes, System.Array.Clear(), Terraria.MessageBuffer.messageLength, Terraria.MessageBuffer.readBuffer, Terraria.MessageBuffer.ResetReader(), Terraria.MessageBuffer.ResetWriter(), Terraria.MessageBuffer.spamCount, Terraria.MessageBuffer.totalData, Terraria.MessageBuffer.writeBuffer, and Terraria.MessageBuffer.writeLocked.