Terraria: Terraria.MessageBuffer.ResetReader
ResetReader()
void Terraria.MessageBuffer.ResetReader () inline
Definition at line 81 of file MessageBuffer.cs.
    {
        if (readerStream != null)
        {
            readerStream.Close();
        }
        readerStream = new MemoryStream(readBuffer);
        reader = new BinaryReader(readerStream);
    }
References System.IO.Stream.Close(), Terraria.MessageBuffer.readBuffer, Terraria.MessageBuffer.reader, and Terraria.MessageBuffer.readerStream.
Referenced by Terraria.MessageBuffer.GetData(), and Terraria.MessageBuffer.Reset().