Terraria: System.Security.IdentityHelper.GetNormalizedUriHash
GetNormalizedUriHash()
static string System.Security.IdentityHelper.GetNormalizedUriHash (Uri uri) inline static package
Definition at line 18 of file IdentityHelper.cs.
    {
        return GetStrongHashSuitableForObjectName(uri.ToString());
    }
References System.Security.IdentityHelper.GetStrongHashSuitableForObjectName(), and System.Uri.ToString().
Referenced by System.IO.IsolatedStorage.Helper.GetDefaultIdentityAndHash().