Terraria: ItemsSacrificedUnlocksTracker.TryGetSacrificeNumbers
TryGetSacrificeNumbers()
bool ItemsSacrificedUnlocksTracker.TryGetSacrificeNumbers (int itemId, out int amountWeHave, out int amountNeededTotal) inline
     {
         if (ContentSamples.CreativeResearchItemPersistentIdOverride.TryGetValue(itemId, out var value))
         {
             itemId = value;
         }
         amountWeHave = (amountNeededTotal = 0);
         if (!CreativeItemSacrificesCatalog.Instance.TryGetSacrificeCountCapToUnlockInfiniteItems(itemId, out amountNeededTotal))
         {
             return false;
         }
         _sacrificesCountByItemIdCache.TryGetValue(itemId, out amountWeHave);
         return true;
     }
References _sacrificesCountByItemIdCache, ContentSamples.CreativeResearchItemPersistentIdOverride, CreativeItemSacrificesCatalog.Instance, and CreativeItemSacrificesCatalog.TryGetSacrificeCountCapToUnlockInfiniteItems().
Referenced by FillListOfItemsThatCanBeObtainedInfinitely(), CreativeUI.GetSacrificeNumbers(), and CreativeUI.SacrificeItem().