Terraria: System.Globalization.CalendarData.IcuLoadCalendarDataFromSystem
IcuLoadCalendarDataFromSystem()
bool System.Globalization.CalendarData.IcuLoadCalendarDataFromSystem (string localeName, CalendarId calendarId) inline private
Definition at line 394 of file CalendarData.cs.
    {
        bool flag = true;
        flag &= GetCalendarInfo(localeName, calendarId, CalendarDataType.NativeName, out sNativeName);
        flag &= GetCalendarInfo(localeName, calendarId, CalendarDataType.MonthDay, out sMonthDay);
        if (sMonthDay != null)
        {
            sMonthDay = NormalizeDatePattern(sMonthDay);
        }
        flag &= EnumDatePatterns(localeName, calendarId, CalendarDataType.ShortDates, out saShortDates);
        flag &= EnumDatePatterns(localeName, calendarId, CalendarDataType.LongDates, out saLongDates);
        flag &= EnumDatePatterns(localeName, calendarId, CalendarDataType.YearMonths, out saYearMonths);
        flag &= EnumCalendarInfo(localeName, calendarId, CalendarDataType.DayNames, out saDayNames);
        flag &= EnumCalendarInfo(localeName, calendarId, CalendarDataType.AbbrevDayNames, out saAbbrevDayNames);
        flag &= EnumCalendarInfo(localeName, calendarId, CalendarDataType.SuperShortDayNames, out saSuperShortDayNames);
        string leapHebrewMonthName = null;
        flag &= EnumMonthNames(localeName, calendarId, CalendarDataType.MonthNames, out saMonthNames, ref leapHebrewMonthName);
        if (leapHebrewMonthName != null)
        {
            saLeapYearMonthNames = (string[])saMonthNames.Clone();
            saLeapYearMonthNames[6] = leapHebrewMonthName;
            saMonthNames[5] = saMonthNames[6];
            saMonthNames[6] = leapHebrewMonthName;
        }
        flag &= EnumMonthNames(localeName, calendarId, CalendarDataType.AbbrevMonthNames, out saAbbrevMonthNames, ref leapHebrewMonthName);
        flag &= EnumMonthNames(localeName, calendarId, CalendarDataType.MonthGenitiveNames, out saMonthGenitiveNames, ref leapHebrewMonthName);
        flag &= EnumMonthNames(localeName, calendarId, CalendarDataType.AbbrevMonthGenitiveNames, out saAbbrevMonthGenitiveNames, ref leapHebrewMonthName);
        flag &= EnumEraNames(localeName, calendarId, CalendarDataType.EraNames, out saEraNames);
        return flag & EnumEraNames(localeName, calendarId, CalendarDataType.AbbrevEraNames, out saAbbrevEraNames);
    }
References System.Globalization.CalendarData.EnumCalendarInfo(), System.Globalization.CalendarData.EnumDatePatterns(), System.Globalization.CalendarData.EnumEraNames(), System.Globalization.CalendarData.EnumMonthNames(), System.Globalization.CalendarData.GetCalendarInfo(), System.Globalization.CalendarData.NormalizeDatePattern(), System.Globalization.CalendarData.saAbbrevDayNames, System.Globalization.CalendarData.saAbbrevEraNames, System.Globalization.CalendarData.saAbbrevMonthGenitiveNames, System.Globalization.CalendarData.saAbbrevMonthNames, System.Globalization.CalendarData.saDayNames, System.Globalization.CalendarData.saEraNames, System.Globalization.CalendarData.saLeapYearMonthNames, System.Globalization.CalendarData.saLongDates, System.Globalization.CalendarData.saMonthGenitiveNames, System.Globalization.CalendarData.saMonthNames, System.Globalization.CalendarData.saShortDates, System.Globalization.CalendarData.saSuperShortDayNames, System.Globalization.CalendarData.saYearMonths, System.Globalization.CalendarData.sMonthDay, and System.Globalization.CalendarData.sNativeName.
Referenced by System.Globalization.CalendarData.LoadCalendarDataFromSystemCore().