Terraria: System.Globalization.CalendarData.CallEnumCalendarInfo
CallEnumCalendarInfo()
static unsafe bool System.Globalization.CalendarData.CallEnumCalendarInfo (string localeName, CalendarId calendar, uint calType, uint lcType, out string[] data) inline static private
Definition at line 905 of file CalendarData.cs.
    {
        EnumData value = default(EnumData);
        value.userOverride = null;
        value.strings = new List<string>();
        if (lcType != 0 && (lcType & 0x80000000u) == 0)
        {
            CalendarId calendarId = (CalendarId)CultureData.GetLocaleInfoExInt(localeName, 4105u);
            if (calendarId == calendar)
            {
                string localeInfoEx = CultureData.GetLocaleInfoEx(localeName, lcType);
                if (localeInfoEx != null)
                {
                    value.userOverride = localeInfoEx;
                    value.strings.Add(localeInfoEx);
                }
            }
        }
        Interop.Kernel32.EnumCalendarInfoExEx((delegate* unmanaged<char*, uint, IntPtr, void*, Interop.BOOL>)(delegate*<char*, uint, IntPtr, void*, Interop.BOOL>)(&EnumCalendarInfoCallback), localeName, (uint)calendar, null, calType, Unsafe.AsPointer(ref value));
        if (value.strings.Count == 0)
        {
            data = null;
            return false;
        }
        string[] array = value.strings.ToArray();
        if (calType == 57 || calType == 4)
        {
            Array.Reverse(array, 0, array.Length);
        }
        data = array;
        return true;
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.array, System.Globalization.CalendarData.EnumCalendarInfoCallback(), Interop.Kernel32.EnumCalendarInfoExEx(), System.Globalization.CultureData.GetLocaleInfoEx(), System.Globalization.CultureData.GetLocaleInfoExInt(), System.Array.Reverse(), and System.value.
Referenced by System.Globalization.CalendarData.NlsLoadCalendarDataFromSystem().