Terraria: System.Data.Common.DataColumnMappingCollection.Validate
Validate()
void System.Data.Common.DataColumnMappingCollection.Validate (int index, [NotNull] DataColumnMapping value) inline private
Definition at line 371 of file DataColumnMappingCollection.cs.
    {
        if (value == null)
        {
            throw ADP.ColumnsAddNullAttempt("value");
        }
        if (value.Parent != null)
        {
            if (this != value.Parent)
            {
                throw ADP.ColumnsIsNotParent(this);
            }
            if (index != IndexOf(value))
            {
                throw ADP.ColumnsIsParent(this);
            }
        }
        string sourceColumn = value.SourceColumn;
        if (string.IsNullOrEmpty(sourceColumn))
        {
            index = 1;
            do
            {
                sourceColumn = "SourceColumn" + index.ToString(CultureInfo.InvariantCulture);
                index++;
            }
            while (-1 != IndexOf(sourceColumn));
            value.SourceColumn = sourceColumn;
        }
        else
        {
            ValidateSourceColumn(index, sourceColumn);
        }
    }
References System.Data.Common.ADP.ColumnsAddNullAttempt(), System.Data.Common.ADP.ColumnsIsNotParent(), System.Data.Common.ADP.ColumnsIsParent(), System.index, System.Data.Common.DataColumnMappingCollection.IndexOf(), System.Globalization.CultureInfo.InvariantCulture, System.Data.Common.DataColumnMappingCollection.ValidateSourceColumn(), and System.value.
Referenced by System.Data.Common.DataColumnMappingCollection.AddWithoutEvents(), System.Data.Common.DataColumnMappingCollection.Insert(), and System.Data.Common.DataColumnMappingCollection.Replace().