Terraria: System.Data.Common.DataColumnMappingCollection.AddEnumerableRange
AddEnumerableRange()
void System.Data.Common.DataColumnMappingCollection.AddEnumerableRange (IEnumerable values, bool doClone) inline private
Definition at line 133 of file DataColumnMappingCollection.cs.
    {
        if (values == null)
        {
            throw ADP.ArgumentNull("values");
        }
        foreach (object value2 in values)
        {
            ValidateType(value2);
        }
        if (doClone)
        {
            foreach (ICloneable value3 in values)
            {
                AddWithoutEvents(value3.Clone() as DataColumnMapping);
            }
            return;
        }
        foreach (DataColumnMapping value4 in values)
        {
            AddWithoutEvents(value4);
        }
    }
References System.Data.Common.DataColumnMappingCollection.AddWithoutEvents(), System.Data.Common.ADP.ArgumentNull(), System.Data.Common.DataColumnMappingCollection.ValidateType(), and System.values.
Referenced by System.Data.Common.DataColumnMappingCollection.AddRange(), and System.Data.Common.DataColumnMappingCollection.AddRange().