Terraria: System.Globalization.CalendarData.LoadCalendarDataFromSystemCore
LoadCalendarDataFromSystemCore()
bool System.Globalization.CalendarData.LoadCalendarDataFromSystemCore (string localeName, CalendarId calendarId) inline private
Definition at line 780 of file CalendarData.cs.
    {
        if (GlobalizationMode.UseNls)
        {
            return NlsLoadCalendarDataFromSystem(localeName, calendarId);
        }
        bool flag = IcuLoadCalendarDataFromSystem(localeName, calendarId);
        if (flag && bUseUserOverrides)
        {
            NormalizeCalendarId(ref calendarId, ref localeName);
            flag &= CallGetCalendarInfoEx(localeName, calendarId, 48u, out iTwoDigitYearMax);
            CalendarId calendarId2 = (CalendarId)CultureData.GetLocaleInfoExInt(localeName, 4105u);
            if (calendarId2 == calendarId)
            {
                string value = CultureData.ReescapeWin32String(CultureData.GetLocaleInfoEx(localeName, 31u));
                string value2 = CultureData.ReescapeWin32String(CultureData.GetLocaleInfoEx(localeName, 32u));
                InsertOrSwapOverride(value, ref saShortDates);
                InsertOrSwapOverride(value2, ref saLongDates);
            }
        }
        return flag;
    }
References System.Globalization.CalendarData.bUseUserOverrides, System.Globalization.CalendarData.CallGetCalendarInfoEx(), System.Globalization.CultureData.GetLocaleInfoEx(), System.Globalization.CultureData.GetLocaleInfoExInt(), System.Globalization.CalendarData.IcuLoadCalendarDataFromSystem(), System.Globalization.CalendarData.InsertOrSwapOverride(), System.Globalization.CalendarData.iTwoDigitYearMax, System.Globalization.CalendarData.NlsLoadCalendarDataFromSystem(), System.Globalization.CalendarData.NormalizeCalendarId(), System.Globalization.CultureData.ReescapeWin32String(), System.Globalization.CalendarData.saLongDates, System.Globalization.CalendarData.saShortDates, System.Globalization.GlobalizationMode.UseNls, and System.value.
Referenced by System.Globalization.CalendarData.CalendarData().