Terraria: System.Globalization.CalendarData.NlsLoadCalendarDataFromSystem
NlsLoadCalendarDataFromSystem()
bool System.Globalization.CalendarData.NlsLoadCalendarDataFromSystem (string localeName, CalendarId calendarId) inline private
Definition at line 828 of file CalendarData.cs.
    {
        bool flag = true;
        uint num = ((!bUseUserOverrides) ? 2147483648u : 0u);
        NormalizeCalendarId(ref calendarId, ref localeName);
        flag &= CallGetCalendarInfoEx(localeName, calendarId, 0x30u | num, out iTwoDigitYearMax);
        flag &= CallGetCalendarInfoEx(localeName, calendarId, 2u, out sNativeName);
        flag &= CallGetCalendarInfoEx(localeName, calendarId, 56u, out sMonthDay);
        flag &= CallEnumCalendarInfo(localeName, calendarId, 5u, 0x1Fu | num, out saShortDates);
        flag &= CallEnumCalendarInfo(localeName, calendarId, 6u, 0x20u | num, out saLongDates);
        flag &= CallEnumCalendarInfo(localeName, calendarId, 47u, 4102u, out saYearMonths);
        flag &= GetCalendarDayInfo(localeName, calendarId, 13u, out saDayNames);
        flag &= GetCalendarDayInfo(localeName, calendarId, 20u, out saAbbrevDayNames);
        flag &= GetCalendarMonthInfo(localeName, calendarId, 21u, out saMonthNames);
        flag &= GetCalendarMonthInfo(localeName, calendarId, 34u, out saAbbrevMonthNames);
        GetCalendarDayInfo(localeName, calendarId, 55u, out saSuperShortDayNames);
        if (calendarId == CalendarId.GREGORIAN)
        {
            GetCalendarMonthInfo(localeName, calendarId, 268435477u, out saMonthGenitiveNames);
            GetCalendarMonthInfo(localeName, calendarId, 268435490u, out saAbbrevMonthGenitiveNames);
        }
        CallEnumCalendarInfo(localeName, calendarId, 4u, 0u, out saEraNames);
        CallEnumCalendarInfo(localeName, calendarId, 57u, 0u, out saAbbrevEraNames);
        saShortDates = CultureData.ReescapeWin32Strings(saShortDates);
        saLongDates = CultureData.ReescapeWin32Strings(saLongDates);
        saYearMonths = CultureData.ReescapeWin32Strings(saYearMonths);
        sMonthDay = CultureData.ReescapeWin32String(sMonthDay);
        return flag;
    }
References System.Globalization.CalendarData.bUseUserOverrides, System.Globalization.CalendarData.CallEnumCalendarInfo(), System.Globalization.CalendarData.CallGetCalendarInfoEx(), System.Globalization.CalendarData.GetCalendarDayInfo(), System.Globalization.CalendarData.GetCalendarMonthInfo(), System.Globalization.CalendarData.iTwoDigitYearMax, System.Globalization.CalendarData.NormalizeCalendarId(), System.Globalization.CultureData.ReescapeWin32String(), System.Globalization.CultureData.ReescapeWin32Strings(), System.Globalization.CalendarData.saAbbrevDayNames, System.Globalization.CalendarData.saAbbrevEraNames, System.Globalization.CalendarData.saAbbrevMonthGenitiveNames, System.Globalization.CalendarData.saAbbrevMonthNames, System.Globalization.CalendarData.saDayNames, System.Globalization.CalendarData.saEraNames, System.Globalization.CalendarData.saLongDates, System.Globalization.CalendarData.saMonthGenitiveNames, System.Globalization.CalendarData.saMonthNames, System.Globalization.CalendarData.saShortDates, System.Globalization.CalendarData.saSuperShortDayNames, System.Globalization.CalendarData.saYearMonths, System.Globalization.CalendarData.sMonthDay, and System.Globalization.CalendarData.sNativeName.
Referenced by System.Globalization.CalendarData.LoadCalendarDataFromSystemCore().