Terraria: System.Globalization.CalendarData.EnumDatePatterns
EnumDatePatterns()
static bool System.Globalization.CalendarData.EnumDatePatterns (string localeName, CalendarId calendarId, CalendarDataType dataType, out string[] datePatterns) inline static private
Definition at line 457 of file CalendarData.cs.
    {
        datePatterns = null;
        IcuEnumCalendarsData callbackContext = default(IcuEnumCalendarsData);
        callbackContext.Results = new List<string>();
        callbackContext.DisallowDuplicates = true;
        bool flag = EnumCalendarInfo(localeName, calendarId, dataType, ref callbackContext);
        if (flag)
        {
            List<string> results = callbackContext.Results;
            for (int i = 0; i < results.Count; i++)
            {
                results[i] = NormalizeDatePattern(results[i]);
            }
            if (dataType == CalendarDataType.ShortDates)
            {
                FixDefaultShortDatePattern(results);
            }
            datePatterns = results.ToArray();
        }
        return flag;
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Globalization.CalendarData.EnumCalendarInfo(), System.Globalization.CalendarData.FixDefaultShortDatePattern(), and System.Globalization.CalendarData.NormalizeDatePattern().
Referenced by System.Globalization.CalendarData.IcuLoadCalendarDataFromSystem().