Terraria: System.Data.Common.DataColumnMappingCollection.GetDataColumn
GetDataColumn()
static ? DataColumn System.Data.Common.DataColumnMappingCollection.GetDataColumn (DataColumnMappingCollection? columnMappings, string sourceColumn, [DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicFields | DynamicallyAccessedMemberTypes.PublicProperties)] Type? dataType, DataTable dataTable, MissingMappingAction mappingAction, MissingSchemaAction schemaAction) inline static
Definition at line 416 of file DataColumnMappingCollection.cs.
    {
        if (columnMappings != null)
        {
            int num = columnMappings.IndexOf(sourceColumn);
            if (-1 != num)
            {
                return columnMappings._items[num].GetDataColumnBySchemaAction(dataTable, dataType, schemaAction);
            }
        }
        if (string.IsNullOrEmpty(sourceColumn))
        {
            throw ADP.InvalidSourceColumn("sourceColumn");
        }
        return mappingAction switch
        {
            MissingMappingAction.Passthrough => DataColumnMapping.GetDataColumnBySchemaAction(sourceColumn, sourceColumn, dataTable, dataType, schemaAction),
            MissingMappingAction.Ignore => null,
            MissingMappingAction.Error => throw ADP.MissingColumnMapping(sourceColumn),
            _ => throw ADP.InvalidMissingMappingAction(mappingAction),
        };
    }
References System.Data.Common.DataColumnMapping.GetDataColumnBySchemaAction(), System.Data.Common.ADP.InvalidMissingMappingAction(), System.Data.Common.ADP.InvalidSourceColumn(), and System.Data.Common.ADP.MissingColumnMapping().
Referenced by System.Data.Common.DataTableMapping.GetDataColumn().