Terraria: System.Globalization.CalendarData.NormalizeDayOfWeek
NormalizeDayOfWeek()
static void System.Globalization.CalendarData.NormalizeDayOfWeek (string input, StringBuilder destination, ref int index) inline static private
Definition at line 598 of file CalendarData.cs.
    {
        char value = input[index];
        int val = CountOccurrences(input, value, ref index);
        val = Math.Max(val, 3);
        if (val > 4)
        {
            val = 3;
        }
        destination.Append('d', val);
    }
References System.Globalization.CalendarData.CountOccurrences(), System.destination, System.index, System.input, System.Math.Max(), and System.value.
Referenced by System.Globalization.CalendarData.NormalizeDatePattern().