Terraria: System.Globalization.CalendarData.CalendarData
CalendarData() [2/2]
System.Globalization.CalendarData.CalendarData (string localeName, CalendarId calendarId, bool bUseUserOverrides) inline package
Definition at line 130 of file CalendarData.cs.
    {
        this.bUseUserOverrides = bUseUserOverrides;
        if (!LoadCalendarDataFromSystemCore(localeName, calendarId))
        {
            if (sNativeName == null)
            {
                sNativeName = string.Empty;
            }
            if (saShortDates == null)
            {
                saShortDates = Invariant.saShortDates;
            }
            if (saYearMonths == null)
            {
                saYearMonths = Invariant.saYearMonths;
            }
            if (saLongDates == null)
            {
                saLongDates = Invariant.saLongDates;
            }
            if (sMonthDay == null)
            {
                sMonthDay = Invariant.sMonthDay;
            }
            if (saEraNames == null)
            {
                saEraNames = Invariant.saEraNames;
            }
            if (saAbbrevEraNames == null)
            {
                saAbbrevEraNames = Invariant.saAbbrevEraNames;
            }
            if (saAbbrevEnglishEraNames == null)
            {
                saAbbrevEnglishEraNames = Invariant.saAbbrevEnglishEraNames;
            }
            if (saDayNames == null)
            {
                saDayNames = Invariant.saDayNames;
            }
            if (saAbbrevDayNames == null)
            {
                saAbbrevDayNames = Invariant.saAbbrevDayNames;
            }
            if (saSuperShortDayNames == null)
            {
                saSuperShortDayNames = Invariant.saSuperShortDayNames;
            }
            if (saMonthNames == null)
            {
                saMonthNames = Invariant.saMonthNames;
            }
            if (saAbbrevMonthNames == null)
            {
                saAbbrevMonthNames = Invariant.saAbbrevMonthNames;
            }
        }
        if (calendarId == CalendarId.TAIWAN)
        {
            if (SystemSupportsTaiwaneseCalendar())
            {
                sNativeName = "中華民國曆";
            }
            else
            {
                sNativeName = string.Empty;
            }
        }
        if (saMonthGenitiveNames == null || saMonthGenitiveNames.Length == 0 || string.IsNullOrEmpty(saMonthGenitiveNames[0]))
        {
            saMonthGenitiveNames = saMonthNames;
        }
        if (saAbbrevMonthGenitiveNames == null || saAbbrevMonthGenitiveNames.Length == 0 || string.IsNullOrEmpty(saAbbrevMonthGenitiveNames[0]))
        {
            saAbbrevMonthGenitiveNames = saAbbrevMonthNames;
        }
        if (saLeapYearMonthNames == null || saLeapYearMonthNames.Length == 0 || string.IsNullOrEmpty(saLeapYearMonthNames[0]))
        {
            saLeapYearMonthNames = saMonthNames;
        }
        InitializeEraNames(localeName, calendarId);
        InitializeAbbreviatedEraNames(localeName, calendarId);
        if (calendarId == CalendarId.JAPAN)
        {
            saAbbrevEnglishEraNames = JapaneseCalendar.EnglishEraNames();
        }
        else
        {
            saAbbrevEnglishEraNames = new string[1] { "" };
        }
        iCurrentEra = saEraNames.Length;
    }
References System.Globalization.CalendarData.bUseUserOverrides, System.Globalization.JapaneseCalendar.EnglishEraNames(), System.Globalization.CalendarData.iCurrentEra, System.Globalization.CalendarData.InitializeAbbreviatedEraNames(), System.Globalization.CalendarData.InitializeEraNames(), System.Globalization.CalendarData.Invariant, System.Globalization.CalendarData.LoadCalendarDataFromSystemCore(), System.Globalization.CalendarData.saAbbrevDayNames, System.Globalization.CalendarData.saAbbrevEnglishEraNames, System.Globalization.CalendarData.saAbbrevEraNames, System.Globalization.CalendarData.saAbbrevMonthGenitiveNames, System.Globalization.CalendarData.saAbbrevMonthNames, System.Globalization.CalendarData.saDayNames, System.Globalization.CalendarData.saEraNames, System.Globalization.CalendarData.saLeapYearMonthNames, System.Globalization.CalendarData.saLongDates, System.Globalization.CalendarData.saMonthGenitiveNames, System.Globalization.CalendarData.saMonthNames, System.Globalization.CalendarData.saShortDates, System.Globalization.CalendarData.saSuperShortDayNames, System.Globalization.CalendarData.saYearMonths, System.Globalization.CalendarData.sMonthDay, System.Globalization.CalendarData.sNativeName, and System.Globalization.CalendarData.SystemSupportsTaiwaneseCalendar().