Terraria: System.Globalization.CalendarData.NlsGetCalendars
NlsGetCalendars()
static unsafe int System.Globalization.CalendarData.NlsGetCalendars (string localeName, bool useUserOverride, CalendarId[] calendars) inline static private
Definition at line 1007 of file CalendarData.cs.
    {
        NlsEnumCalendarsData value = default(NlsEnumCalendarsData);
        value.userOverride = 0;
        value.calendars = new List<int>();
        if (useUserOverride)
        {
            int localeInfoExInt = CultureData.GetLocaleInfoExInt(localeName, 4105u);
            if (localeInfoExInt != 0)
            {
                value.userOverride = localeInfoExInt;
                value.calendars.Add(localeInfoExInt);
            }
        }
        Interop.Kernel32.EnumCalendarInfoExEx((delegate* unmanaged<char*, uint, IntPtr, void*, Interop.BOOL>)(delegate*<char*, uint, IntPtr, void*, Interop.BOOL>)(&EnumCalendarsCallback), localeName, uint.MaxValue, null, 1u, Unsafe.AsPointer(ref value));
        for (int i = 0; i < Math.Min(calendars.Length, value.calendars.Count); i++)
        {
            calendars[i] = (CalendarId)value.calendars[i];
        }
        return value.calendars.Count;
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Add(), Interop.Kernel32.EnumCalendarInfoExEx(), System.Globalization.CalendarData.EnumCalendarsCallback(), System.Globalization.CultureData.GetLocaleInfoExInt(), System.Math.Min(), and System.value.
Referenced by System.Globalization.CalendarData.GetCalendarsCore().