Terraria: System.Globalization.CalendarData.Invariant
Invariant
readonly CalendarData System.Globalization.CalendarData.Invariant = CreateInvariant() static package
Definition at line 69 of file CalendarData.cs.
Referenced by System.Globalization.CalendarData.CalendarData(), System.Globalization.CultureData.CreateCultureWithInvariantData(), System.Globalization.CultureData.GetCalendar(), System.Globalization.CalendarData.GetCalendarCurrentEra(), System.Globalization.CalendarData.InitializeEraNames(), and System.Globalization.CalendarData.NlsGetTwoDigitYearMax().