Terraria: System.Globalization.CalendarData.EnumCalendarInfo
EnumCalendarInfo() [1/2]
static bool System.Globalization.CalendarData.EnumCalendarInfo (string localeName, CalendarId calendarId, CalendarDataType dataType, out string[] calendarData) inline static package
Definition at line 660 of file CalendarData.cs.
    {
        calendarData = null;
        IcuEnumCalendarsData callbackContext = default(IcuEnumCalendarsData);
        callbackContext.Results = new List<string>();
        bool flag = EnumCalendarInfo(localeName, calendarId, dataType, ref callbackContext);
        if (flag)
        {
            calendarData = callbackContext.Results.ToArray();
        }
        return flag;
    }
References System.Globalization.CalendarData.EnumCalendarInfo().
Referenced by System.Globalization.CalendarData.EnumCalendarInfo(), System.Globalization.CalendarData.EnumDatePatterns(), System.Globalization.CalendarData.EnumEraNames(), System.Globalization.CalendarData.EnumMonthNames(), System.Globalization.JapaneseCalendar.IcuGetJapaneseEras(), and System.Globalization.CalendarData.IcuLoadCalendarDataFromSystem().