Terraria: System.Globalization.CalendarData.SystemSupportsTaiwaneseCalendar
SystemSupportsTaiwaneseCalendar()
static bool System.Globalization.CalendarData.SystemSupportsTaiwaneseCalendar () inline static private
Definition at line 385 of file CalendarData.cs.
    {
        if (!GlobalizationMode.UseNls)
        {
            return IcuSystemSupportsTaiwaneseCalendar();
        }
        return NlsSystemSupportsTaiwaneseCalendar();
    }
References System.Globalization.CalendarData.IcuSystemSupportsTaiwaneseCalendar(), System.Globalization.CalendarData.NlsSystemSupportsTaiwaneseCalendar(), and System.Globalization.GlobalizationMode.UseNls.
Referenced by System.Globalization.CalendarData.CalendarData(), and System.Globalization.CalendarData.InitializeEraNames().