Terraria: System.Globalization.CalendarData.EnumCalendarInfoCallback
EnumCalendarInfoCallback() [1/2]
static unsafe void System.Globalization.CalendarData.EnumCalendarInfoCallback (char * calendarStringPtr, IntPtr context) inline static private
Definition at line 679 of file CalendarData.cs.
    {
        try
        {
            ReadOnlySpan<char> strA = MemoryMarshal.CreateReadOnlySpanFromNullTerminated(calendarStringPtr);
            ref IcuEnumCalendarsData reference = ref Unsafe.As<byte, IcuEnumCalendarsData>(ref *(byte*)(void*)context);
            if (reference.DisallowDuplicates)
            {
                foreach (string result in reference.Results)
                {
                    if (string.CompareOrdinal(strA, result) == 0)
                    {
                        return;
                    }
                }
            }
            reference.Results.Add(strA.ToString());
        }
        catch (Exception)
        {
        }
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Add(), and System.Runtime.InteropServices.MemoryMarshal.CreateReadOnlySpanFromNullTerminated().
Referenced by System.Globalization.CalendarData.CallEnumCalendarInfo(), and System.Globalization.CalendarData.EnumCalendarInfo().