Terraria: System.Globalization.CalendarData.NormalizeDatePattern
NormalizeDatePattern()
static string System.Globalization.CalendarData.NormalizeDatePattern (string input) inline static private
Definition at line 538 of file CalendarData.cs.
    {
        StringBuilder stringBuilder = StringBuilderCache.Acquire(input.Length);
        int index = 0;
        while (index < input.Length)
        {
            switch (input[index])
            {
            case '\'':
                stringBuilder.Append(input[index++]);
                while (index < input.Length)
                {
                    char c = input[index++];
                    stringBuilder.Append(c);
                    if (c == '\'')
                    {
                        break;
                    }
                }
                break;
            case 'E':
            case 'c':
            case 'e':
                NormalizeDayOfWeek(input, stringBuilder, ref index);
                break;
            case 'L':
            case 'M':
            {
                int num = CountOccurrences(input, input[index], ref index);
                if (num > 4)
                {
                    num = 3;
                }
                stringBuilder.Append('M', num);
                break;
            }
            case 'G':
            {
                int num = CountOccurrences(input, 'G', ref index);
                stringBuilder.Append('g');
                break;
            }
            case 'y':
            {
                int num = CountOccurrences(input, 'y', ref index);
                if (num == 1)
                {
                    num = 4;
                }
                stringBuilder.Append('y', num);
                break;
            }
            default:
                stringBuilder.Append(input[index++]);
                break;
            }
        }
        return StringBuilderCache.GetStringAndRelease(stringBuilder);
    }
References System.Text.StringBuilderCache.Acquire(), System.Globalization.CalendarData.CountOccurrences(), System.Text.StringBuilderCache.GetStringAndRelease(), System.index, System.input, and System.Globalization.CalendarData.NormalizeDayOfWeek().
Referenced by System.Globalization.CalendarData.EnumDatePatterns(), and System.Globalization.CalendarData.IcuLoadCalendarDataFromSystem().