Terraria: System.Globalization.CalendarData.InitializeEraNames
InitializeEraNames()
void System.Globalization.CalendarData.InitializeEraNames (string localeName, CalendarId calendarId) inline private
Definition at line 224 of file CalendarData.cs.
    {
        switch (calendarId)
        {
        case CalendarId.GREGORIAN:
            if (saEraNames == null || saEraNames.Length == 0 || string.IsNullOrEmpty(saEraNames[0]))
            {
                saEraNames = new string[1] { "A.D." };
            }
            break;
        case CalendarId.GREGORIAN_US:
        case CalendarId.JULIAN:
            saEraNames = new string[1] { "A.D." };
            break;
        case CalendarId.HEBREW:
            saEraNames = new string[1] { "C.E." };
            break;
        case CalendarId.HIJRI:
        case CalendarId.UMALQURA:
            if (localeName == "dv-MV")
            {
                saEraNames = new string[1] { "ހ\u07a8ޖ\u07b0ރ\u07a9" };
            }
            else
            {
                saEraNames = new string[1] { "بعد الهجرة" };
            }
            break;
        case CalendarId.GREGORIAN_ARABIC:
        case CalendarId.GREGORIAN_XLIT_ENGLISH:
        case CalendarId.GREGORIAN_XLIT_FRENCH:
            saEraNames = new string[1] { "م" };
            break;
        case CalendarId.GREGORIAN_ME_FRENCH:
            saEraNames = new string[1] { "ap. J.-C." };
            break;
        case CalendarId.TAIWAN:
            if (SystemSupportsTaiwaneseCalendar())
            {
                saEraNames = new string[1] { "中華民國" };
            }
            else
            {
                saEraNames = new string[1] { string.Empty };
            }
            break;
        case CalendarId.KOREA:
            saEraNames = new string[1] { "단기" };
            break;
        case CalendarId.THAI:
            saEraNames = new string[1] { "พ.ศ." };
            break;
        case CalendarId.JAPAN:
        case CalendarId.JAPANESELUNISOLAR:
            saEraNames = JapaneseCalendar.EraNames();
            break;
        case CalendarId.PERSIAN:
            if (saEraNames == null || saEraNames.Length == 0 || string.IsNullOrEmpty(saEraNames[0]))
            {
                saEraNames = new string[1] { "ه.ش" };
            }
            break;
        default:
            saEraNames = Invariant.saEraNames;
            break;
        }
    }
References System.Globalization.JapaneseCalendar.EraNames(), System.Globalization.CalendarData.Invariant, System.Globalization.CalendarData.saEraNames, and System.Globalization.CalendarData.SystemSupportsTaiwaneseCalendar().
Referenced by System.Globalization.CalendarData.CalendarData().