Terraria: System.Globalization.CalendarData.EnumMonthNames
EnumMonthNames()
static bool System.Globalization.CalendarData.EnumMonthNames (string localeName, CalendarId calendarId, CalendarDataType dataType, out string[] monthNames, ref string leapHebrewMonthName) inline static private
Definition at line 620 of file CalendarData.cs.
    {
        monthNames = null;
        IcuEnumCalendarsData callbackContext = default(IcuEnumCalendarsData);
        callbackContext.Results = new List<string>();
        bool flag = EnumCalendarInfo(localeName, calendarId, dataType, ref callbackContext);
        if (flag)
        {
            if (callbackContext.Results.Count == 12)
            {
                callbackContext.Results.Add(string.Empty);
            }
            if (callbackContext.Results.Count > 13)
            {
                if (calendarId == CalendarId.HEBREW)
                {
                    leapHebrewMonthName = callbackContext.Results[13];
                }
                callbackContext.Results.RemoveRange(13, callbackContext.Results.Count - 13);
            }
            monthNames = callbackContext.Results.ToArray();
        }
        return flag;
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, and System.Globalization.CalendarData.EnumCalendarInfo().
Referenced by System.Globalization.CalendarData.IcuLoadCalendarDataFromSystem().