Terraria: System.Data.Common.DataColumnMappingCollection.IndexOf
IndexOf() [1/3]
int System.Data.Common.DataColumnMappingCollection.IndexOf (object? value) inline
Implements System.Collections.IList.
Definition at line 229 of file DataColumnMappingCollection.cs.
    {
        if (value != null)
        {
            ValidateType(value);
            for (int i = 0; i < Count; i++)
            {
                if (_items[i] == value)
                {
                    return i;
                }
            }
        }
        return -1;
    }
References System.Data.Common.DataColumnMappingCollection._items, System.Data.Common.DataColumnMappingCollection.Count, System.Data.Common.DataColumnMappingCollection.ValidateType(), and System.value.
Referenced by System.Data.Common.DataColumnMappingCollection.Contains(), System.Data.Common.DataColumnMappingCollection.Contains(), System.Data.Common.DataColumnMappingCollection.RangeCheck(), System.Data.Common.DataColumnMappingCollection.Remove(), System.Data.Common.DataColumnMappingCollection.Validate(), and System.Data.Common.DataColumnMappingCollection.ValidateSourceColumn().