Terraria: System.Data.SqlTypes.SqlDateTime.ReadXml
ReadXml()
void IXmlSerializable. System.Data.SqlTypes.SqlDateTime.ReadXml (XmlReader reader) inline
Implements System.Xml.Serialization.IXmlSerializable.
Definition at line 448 of file SqlDateTime.cs.
    {
        string attribute = reader.GetAttribute("nil", "http://www.w3.org/2001/XMLSchema-instance");
        if (attribute != null && XmlConvert.ToBoolean(attribute))
        {
            reader.ReadElementString();
            m_fNotNull = false;
            return;
        }
        DateTime value = XmlConvert.ToDateTime(reader.ReadElementString(), XmlDateTimeSerializationMode.RoundtripKind);
        if (value.Kind != 0)
        {
            throw new SqlTypeException(SQLResource.TimeZoneSpecifiedMessage);
        }
        SqlDateTime sqlDateTime = FromDateTime(value);
        m_day = sqlDateTime.DayTicks;
        m_time = sqlDateTime.TimeTicks;
        m_fNotNull = true;
    }
References System.Xml.Dictionary, System.Data.SqlTypes.SqlDateTime.FromDateTime(), System.Xml.XmlReader.GetAttribute(), System.Data.SqlTypes.SqlDateTime.m_day, System.Data.SqlTypes.SqlDateTime.m_fNotNull, System.Data.SqlTypes.SqlDateTime.m_time, System.Xml.XmlReader.ReadElementString(), System.Data.SqlTypes.SQLResource.TimeZoneSpecifiedMessage, System.Xml.XmlConvert.ToBoolean(), System.Xml.XmlConvert.ToDateTime(), and System.value.