Terraria: System.Buffers.ArrayBufferWriter.CheckAndResizeBuffer
CheckAndResizeBuffer()
void System.Buffers.ArrayBufferWriter< T >.CheckAndResizeBuffer (int sizeHint) inline private
Definition at line 66 of file ArrayBufferWriter.cs.
    {
        if (sizeHint < 0)
        {
            throw new ArgumentException("sizeHint");
        }
        if (sizeHint == 0)
        {
            sizeHint = 1;
        }
        if (sizeHint <= FreeCapacity)
        {
            return;
        }
        int num = _buffer.Length;
        int num2 = Math.Max(sizeHint, num);
        if (num == 0)
        {
            num2 = Math.Max(num2, 256);
        }
        int num3 = num + num2;
        if ((uint)num3 > 2147483647u)
        {
            uint num4 = (uint)(num - FreeCapacity + sizeHint);
            if (num4 > 2147483591)
            {
                ThrowOutOfMemoryException(num4);
            }
            num3 = 2147483591;
        }
        Array.Resize(ref _buffer, num3);
    }
References System.Buffers.ArrayBufferWriter< T >._buffer, System.Buffers.ArrayBufferWriter< T >.FreeCapacity, System.Math.Max(), and System.Buffers.ArrayBufferWriter< T >.ThrowOutOfMemoryException().
Referenced by System.Buffers.ArrayBufferWriter< T >.GetMemory(), and System.Buffers.ArrayBufferWriter< T >.GetSpan().