Terraria: System.Xml.XmlBinaryWriterSession.TryAdd
TryAdd()
virtual bool System.Xml.XmlBinaryWriterSession.TryAdd (XmlDictionaryString value, out int key) inline virtual
Definition at line 176 of file XmlBinaryWriterSession.cs.
    {
        if (value == null)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperArgumentNull("value");
        }
        if (_maps.TryGetValue(value.Dictionary, out var value2))
        {
            key = value2[value.Key] - 1;
            if (key != -1)
            {
                throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new InvalidOperationException(System.SR.XmlKeyAlreadyExists));
            }
            key = Add(value.Value);
            value2[value.Key] = key + 1;
            return true;
        }
        key = Add(value.Value);
        value2 = AddKeys(value.Dictionary, value.Key + 1);
        value2[value.Key] = key + 1;
        return true;
    }
References System.Xml.XmlBinaryWriterSession._maps, System.Add, System.Xml.XmlBinaryWriterSession.AddKeys(), System.key, System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperArgumentNull(), System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperError(), System.Collections.Generic.Dictionary< TKey, TValue >.TryGetValue(), System.value, and System.SR.XmlKeyAlreadyExists.
Referenced by System.Xml.XmlBinaryNodeWriter.TryGetKey().