Terraria: System.Xml.XmlBinaryWriterSession.AddKeys
AddKeys()
IntArray System.Xml.XmlBinaryWriterSession.AddKeys (IXmlDictionary dictionary, int minCount) inline private
Definition at line 206 of file XmlBinaryWriterSession.cs.
    {
        IntArray intArray = new IntArray(Math.Max(minCount, 16));
        _maps.Add(dictionary, intArray);
        return intArray;
    }
References System.Xml.XmlBinaryWriterSession._maps, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.dictionary, System.Xml.Dictionary, and System.Math.Max().
Referenced by System.Xml.XmlBinaryWriterSession.TryAdd(), and System.Xml.XmlBinaryWriterSession.TryLookup().