Terraria: System.Net.Http.HttpConnection.ConnectionCloseReadStream.CopyToAsync
CopyToAsync() [4/4]
override Task System.Net.Http.HttpConnection.ConnectionCloseReadStream.CopyToAsync (Stream destination, int bufferSize, CancellationToken cancellationToken) inline virtual
Reimplemented from System.IO.Stream.
Definition at line 478 of file HttpConnection.cs.
        {
            Stream.ValidateCopyToArguments(destination, bufferSize);
            if (cancellationToken.IsCancellationRequested)
            {
                return Task.FromCanceled(cancellationToken);
            }
            HttpConnection connection = _connection;
            if (connection == null)
            {
                return Task.CompletedTask;
            }
            Task task = connection.CopyToUntilEofAsync(destination, async: true, bufferSize, cancellationToken);
            if (task.IsCompletedSuccessfully)
            {
                Finish(connection);
                return Task.CompletedTask;
            }
            return CompleteCopyToAsync(task, connection, cancellationToken);
        }
References System.Net.Http.HttpContentStream._connection, System.cancellationToken, System.Net.Http.HttpConnection.ConnectionCloseReadStream.CompleteCopyToAsync(), System.Threading.Tasks.Task< TResult >.CompletedTask, System.Net.Http.HttpConnection.CopyToUntilEofAsync(), System.destination, System.Net.Http.HttpConnection.ConnectionCloseReadStream.Finish(), System.Threading.Tasks.Task< TResult >.FromCanceled(), System.task, and System.IO.Stream.ValidateCopyToArguments().