Terraria: System.Security.Cryptography.RsaPaddingProcessor.Mgf1
Mgf1() [2/2]
void System.Security.Cryptography.RsaPaddingProcessor.Mgf1 (IncrementalHash hasher, ReadOnlySpan< byte > mgfSeed, Span< byte > mask) inline private
Definition at line 164 of file RsaPaddingProcessor.cs.
    {
        Span<byte> destination = mask;
        int num = 0;
        Span<byte> span = stackalloc byte[4];
        while (destination.Length > 0)
        {
            hasher.AppendData(mgfSeed);
            BinaryPrimitives.WriteInt32BigEndian(span, num);
            hasher.AppendData(span);
            if (destination.Length >= _hLen)
            {
                if (!hasher.TryGetHashAndReset(destination, out var bytesWritten))
                {
                    throw new CryptographicException();
                }
                destination = destination.Slice(bytesWritten);
                num++;
                continue;
            }
            Span<byte> destination2 = stackalloc byte[_hLen];
            if (!hasher.TryGetHashAndReset(destination2, out var _))
            {
                throw new CryptographicException();
            }
            destination2.Slice(0, destination.Length).CopyTo(destination);
            break;
        }
    }
References System.Security.Cryptography.IncrementalHash.AppendData(), System.destination, System.Span< T >.Slice(), System.Security.Cryptography.IncrementalHash.TryGetHashAndReset(), and System.Buffers.Binary.BinaryPrimitives.WriteInt32BigEndian().