Terraria: System.Security.Cryptography.RsaPaddingProcessor.PadOaep
PadOaep() [2/2]
void System.Security.Cryptography.RsaPaddingProcessor.PadOaep (ReadOnlySpan< byte > source, Span< byte > destination) inline package
Definition at line 115 of file RsaPaddingProcessor.cs.
    {
        byte[] array = null;
        Span<byte> span = Span<byte>.Empty;
        try
        {
            int num = checked(destination.Length - _hLen - _hLen - 2);
            if (source.Length > num)
            {
                throw new CryptographicException(System.SR.Format(System.SR.Cryptography_Encryption_MessageTooLong, num));
            }
            Span<byte> span2 = destination.Slice(1, _hLen);
            Span<byte> span3 = destination.Slice(1 + _hLen);
            using IncrementalHash incrementalHash = IncrementalHash.CreateHash(_hashAlgorithmName);
            Span<byte> destination2 = span3.Slice(0, _hLen);
            Span<byte> destination3 = span3.Slice(span3.Length - source.Length);
            Span<byte> span4 = span3.Slice(_hLen, span3.Length - _hLen - 1 - destination3.Length);
            Span<byte> span5 = span3.Slice(_hLen + span4.Length, 1);
            if (!incrementalHash.TryGetHashAndReset(destination2, out var bytesWritten) || bytesWritten != _hLen)
            {
                throw new CryptographicException();
            }
            span4.Clear();
            span5[0] = 1;
            source.CopyTo(destination3);
            RandomNumberGenerator.Fill(span2);
            array = System.Security.Cryptography.CryptoPool.Rent(span3.Length);
            span = new Span<byte>(array, 0, span3.Length);
            Mgf1(incrementalHash, span2, span);
            Xor(span3, span);
            Span<byte> span6 = stackalloc byte[_hLen];
            Mgf1(incrementalHash, span3, span6);
            Xor(span2, span6);
            destination[0] = 0;
        }
        catch (Exception ex) when (!(ex is CryptographicException))
        {
            throw new CryptographicException();
        }
        finally
        {
            if (array != null)
            {
                CryptographicOperations.ZeroMemory(span);
                System.Security.Cryptography.CryptoPool.Return(array, 0);
            }
        }
    }
References System.array, System.Span< T >.Clear(), System.Span< T >.CopyTo(), System.Security.Cryptography.IncrementalHash.CreateHash(), System.SR.Cryptography_Encryption_MessageTooLong, System.destination, System.Span< T >.Empty, System.Security.Cryptography.RandomNumberGenerator.Fill(), System.SR.Format(), System.Span< T >.Length, System.Security.Cryptography.CryptoPool.Rent(), System.Security.Cryptography.CryptoPool.Return(), System.Span< T >.Slice(), System.source, and System.Security.Cryptography.CryptographicOperations.ZeroMemory().