Terraria: System.Net.Http.HttpConnection.ConnectionCloseReadStream.Finish
Finish()
void System.Net.Http.HttpConnection.ConnectionCloseReadStream.Finish (HttpConnection connection) inline private
Definition at line 518 of file HttpConnection.cs.
        {
            _connection = null;
            connection.Dispose();
        }
References System.Net.Http.HttpContentStream._connection, and System.Net.Http.HttpConnection.Dispose().
Referenced by System.Net.Http.HttpConnection.ConnectionCloseReadStream.CompleteCopyToAsync(), and System.Net.Http.HttpConnection.ConnectionCloseReadStream.CopyToAsync().