Terraria: System.Text.Unicode.UnicodeHelpers.GetUtf8RepresentationForScalarValue
GetUtf8RepresentationForScalarValue()
static int System.Text.Unicode.UnicodeHelpers.GetUtf8RepresentationForScalarValue (uint scalar) inline static package
Definition at line 843 of file UnicodeHelpers.cs.
    {
        if (scalar <= 127)
        {
            return (byte)scalar;
        }
        if (scalar <= 2047)
        {
            byte b = (byte)(0xC0u | (scalar >> 6));
            byte b2 = (byte)(0x80u | (scalar & 0x3Fu));
            return (b2 << 8) | b;
        }
        if (scalar <= 65535)
        {
            byte b3 = (byte)(0xE0u | (scalar >> 12));
            byte b4 = (byte)(0x80u | ((scalar >> 6) & 0x3Fu));
            byte b5 = (byte)(0x80u | (scalar & 0x3Fu));
            return (((b5 << 8) | b4) << 8) | b3;
        }
        byte b6 = (byte)(0xF0u | (scalar >> 18));
        byte b7 = (byte)(0x80u | ((scalar >> 12) & 0x3Fu));
        byte b8 = (byte)(0x80u | ((scalar >> 6) & 0x3Fu));
        byte b9 = (byte)(0x80u | (scalar & 0x3Fu));
        return (((((b9 << 8) | b8) << 8) | b7) << 8) | b6;
    }
Referenced by System.Text.Encodings.Web.DefaultUrlEncoder.EscaperImplementation.EncodeUtf16(), System.Text.Encodings.Web.DefaultUrlEncoder.EscaperImplementation.EncodeUtf8(), System.Text.Encodings.Web.TextEncoder.EncodeUtf8Core(), and System.Text.Encodings.Web.TextEncoder.TryEncodeUnicodeScalarUtf8().