Terraria: System.Runtime.Intrinsics.X86.Bmi1.X64.TrailingZeroCount
TrailingZeroCount()
static ulong System.Runtime.Intrinsics.X86.Bmi1.X64.TrailingZeroCount (ulong value) inline static
Definition at line 44 of file Bmi1.cs.
        {
            return TrailingZeroCount(value);
        }
References System.Runtime.Intrinsics.X86.Bmi1.X64.TrailingZeroCount(), and System.value.
Referenced by System.Text.Latin1Utility.GetIndexOfFirstNonLatin1Char_Sse2(), System.Numerics.BitOperations.TrailingZeroCount(), and System.Runtime.Intrinsics.X86.Bmi1.X64.TrailingZeroCount().