Terraria: Terraria.Localization.GameCulture.FromCultureName
FromCultureName()
static GameCulture Terraria.Localization.GameCulture.FromCultureName (CultureName name) inline static
Definition at line 37 of file GameCulture.cs.
    {
        if (!_NamedCultures.ContainsKey(name))
        {
            return DefaultCulture;
        }
        return _NamedCultures[name];
    }
References Terraria.Localization.GameCulture._NamedCultures, and Terraria.Localization.GameCulture.DefaultCulture.
Referenced by Terraria.IngameOptions.Draw(), Terraria.Main.DrawInfoAccs(), Terraria.GameContent.UI.Elements.UICharacterListItem.DrawSelf(), Terraria.GameContent.UI.Elements.UIWorkshopImportWorldListItem.DrawSelf(), Terraria.GameContent.UI.Elements.UIWorkshopPublishWorldListItem.DrawSelf(), Terraria.GameContent.UI.Elements.UIWorldListItem.DrawSelf(), Terraria.Player.DropTombstone(), and Terraria.Lang.LocalizedDuration().