Terraria: Microsoft.Xna.Framework.Graphics.RenderTargetCube.RecreateAndPopulateObject
RecreateAndPopulateObject() [1/2]
unsafe override int Microsoft.Xna.Framework.Graphics.RenderTargetCube.RecreateAndPopulateObject () inline package virtual
Reimplemented from Microsoft.Xna.Framework.Graphics.TextureCube.
Definition at line 107 of file RenderTargetCube.cs.
    {
        if (pComPtr != null)
        {
            return -2147467259;
        }
        int num = ((_levelCount > 1) ? 1 : 0);
        CreateTexture(_parent, _size, (byte)num != 0, 1u, (_D3DPOOL)0, _format);
        helper.CreateSurfaces(_parent);
        return 0;
    }
References Microsoft.Xna.Framework.Graphics.Texture._format, Microsoft.Xna.Framework.Graphics.Texture._levelCount, Microsoft.Xna.Framework.Graphics.GraphicsResource._parent, Microsoft.Xna.Framework.Graphics.TextureCube._size, Microsoft.Xna.Framework.Graphics.RenderTargetHelper.CreateSurfaces(), Microsoft.Xna.Framework.Graphics.TextureCube.CreateTexture(), Microsoft.Xna.Framework.Graphics.RenderTargetCube.helper, and Microsoft.Xna.Framework.Graphics.TextureCube.pComPtr.
Referenced by Microsoft.Xna.Framework.Graphics.RenderTargetCube.RecreateAndPopulateObject().