Terraria: System.Threading.Tasks.TplEventSource.Log
Log
readonly TplEventSource System.Threading.Tasks.TplEventSource.Log = new TplEventSource() static
Definition at line 75 of file TplEventSource.cs.
Referenced by System.Threading.Tasks.TaskFactory< TResult >.CompleteOnCountdownPromise< T >.CompleteOnCountdownPromise(), System.Threading.Tasks.TaskFactory< TResult >.CompleteOnCountdownPromise< T >.CompleteOnCountdownPromise(), System.Threading.Tasks.TaskFactory< TResult >.CompleteOnInvokePromise.CompleteOnInvokePromise(), System.Threading.Tasks.ContinueWithTaskContinuation.ContinueWithTaskContinuation(), System.Threading.Tasks.Task< TResult >.DelayPromise.DelayPromise(), System.Threading.Tasks.Task< TResult >.TwoTaskWhenAnyPromise< TTask >.TwoTaskWhenAnyPromise(), System.Threading.Tasks.UnwrapPromise< TResult >.UnwrapPromise(), System.Threading.Tasks.Task< TResult >.WhenAllPromise< T >.WhenAllPromise(), System.Threading.Tasks.Task< TResult >.WhenAllPromise< T >.WhenAllPromise(), System.Runtime.CompilerServices.AsyncTaskMethodBuilder< TResult >.DebugFinalizableAsyncStateMachineBox< TStateMachine >.~DebugFinalizableAsyncStateMachineBox(), System.Runtime.CompilerServices.YieldAwaitable.YieldAwaiter.AwaitUnsafeOnCompleted(), System.Threading.Tasks.Task< TResult >.CancellationCleanupLogic(), System.Threading.Tasks.Task< TResult >.DelayPromise.CompleteTimedOut(), System.Threading.Tasks.Task< TResult >.ContinueWithCore(), System.Threading.Tasks.AwaitTaskContinuation.Execute(), System.Threading.Tasks.Task< TResult >.ExecuteWithThreadLocal(), System.Threading.Tasks.Task< TResult >.FinishStageTwo(), System.Threading.Tasks.Task< TResult >.FireTaskScheduledIfNeeded(), System.Threading.Tasks.TaskFactory< TResult >.FromAsyncCoreLogic(), System.Threading.Tasks.TaskFactory< TResult >.FromAsyncImpl(), System.Threading.Tasks.TaskFactory< TResult >.FromAsyncImpl(), System.Threading.Tasks.TaskFactory< TResult >.FromAsyncImpl< TArg1 >(), System.Threading.Tasks.TaskFactory< TResult >.FromAsyncImpl< TArg1, TArg2 >(), System.Threading.Tasks.TaskFactory< TResult >.FromAsyncImpl< TArg1, TArg2, TArg3 >(), System.Runtime.CompilerServices.AsyncTaskMethodBuilder< TResult >.GetStateMachineBox< TStateMachine >(), System.Threading.Tasks.TaskScheduler.InternalQueueTask(), System.Threading.Tasks.Task< TResult >.InternalWaitCore(), System.Threading.Tasks.Task< TResult >.WhenAllPromise< T >.Invoke(), System.Threading.Tasks.Task< TResult >.TwoTaskWhenAnyPromise< TTask >.Invoke(), System.Threading.Tasks.TaskFactory< TResult >.CompleteOnCountdownPromise< T >.Invoke(), System.Threading.Tasks.TaskFactory< TResult >.CompleteOnInvokePromise.Invoke(), System.Threading.Tasks.Task< TResult >.WhenAllPromise< T >.Invoke(), System.Threading.Tasks.Task< TResult >.LogFinishCompletionNotification(), System.Runtime.CompilerServices.AsyncTaskMethodBuilder< TResult >.AsyncStateMachineBox< TStateMachine >.MoveNext(), System.Threading.Tasks.Task< TResult >.NewId(), System.Runtime.CompilerServices.TaskAwaiter< TResult >.OnCompletedInternal(), System.Diagnostics.Tracing.ActivityTracker.OnStart(), System.Runtime.CompilerServices.YieldAwaitable.YieldAwaiter.OutputCorrelationEtwEvent(), System.Runtime.CompilerServices.TaskAwaiter< TResult >.OutputWaitEtwEvents(), System.Threading.Tasks.SynchronizationContextAwaitTaskContinuation.PostAction(), System.Runtime.CompilerServices.YieldAwaitable.YieldAwaiter.QueueContinuation(), System.Threading.Tasks.ContinueWithTaskContinuation.Run(), System.Threading.Tasks.AwaitTaskContinuation.Run(), System.Threading.Tasks.SynchronizationContextAwaitTaskContinuation.Run(), System.Threading.Tasks.Task< TResult >.RunContinuations(), System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(), System.Threading.Tasks.Task< TResult >.ScheduleAndStart(), System.Diagnostics.Tracing.EventSource.SetCurrentThreadActivityId(), System.Diagnostics.Tracing.EventSource.SetCurrentThreadActivityId(), System.Runtime.CompilerServices.AsyncVoidMethodBuilder.SetException(), System.Runtime.CompilerServices.AsyncTaskMethodBuilder< TResult >.SetExistingTaskResult(), System.Runtime.CompilerServices.AsyncVoidMethodBuilder.SetResult(), System.Threading.Tasks.TaskScheduler.TryRunInline(), System.Threading.Tasks.UnwrapPromise< TResult >.TrySetFromTask(), System.Runtime.CompilerServices.TaskAwaiter< TResult >.UnsafeOnCompletedInternal(), and System.Threading.Tasks.AwaitTaskContinuation.UnsafeScheduleAction().