Terraria: System.Xml.Schema.Asttree.CompileXPath
CompileXPath()
void System.Xml.Schema.Asttree.CompileXPath (string xPath, bool isField, XmlNamespaceManager nsmgr) inline
Definition at line 63 of file Asttree.cs.
    {
        if (xPath == null || xPath.Length == 0)
        {
            throw new XmlSchemaException(System.SR.Sch_EmptyXPath, string.Empty);
        }
        string[] array = xPath.Split('|');
        ArrayList arrayList = new ArrayList(array.Length);
        _fAxisArray = new ArrayList(array.Length);
        try
        {
            for (int i = 0; i < array.Length; i++)
            {
                Axis value = (Axis)XPathParser.ParseXPathExpression(array[i]);
                arrayList.Add(value);
            }
        }
        catch
        {
            throw new XmlSchemaException(System.SR.Sch_ICXpathError, xPath);
        }
        for (int j = 0; j < arrayList.Count; j++)
        {
            Axis axis = (Axis)arrayList[j];
            Axis axis2;
            if ((axis2 = axis) == null)
            {
                throw new XmlSchemaException(System.SR.Sch_ICXpathError, xPath);
            }
            Axis axis3 = axis2;
            if (IsAttribute(axis2))
            {
                if (!isField)
                {
                    throw new XmlSchemaException(System.SR.Sch_SelectorAttr, xPath);
                }
                SetURN(axis2, nsmgr);
                try
                {
                    axis2 = (Axis)axis2.Input;
                }
                catch
                {
                    throw new XmlSchemaException(System.SR.Sch_ICXpathError, xPath);
                }
            }
            while (axis2 != null && (IsNameTest(axis2) || IsSelf(axis2)))
            {
                if (IsSelf(axis2) && axis != axis2)
                {
                    axis3.Input = axis2.Input;
                }
                else
                {
                    axis3 = axis2;
                    if (IsNameTest(axis2))
                    {
                        SetURN(axis2, nsmgr);
                    }
                }
                try
                {
                    axis2 = (Axis)axis2.Input;
                }
                catch
                {
                    throw new XmlSchemaException(System.SR.Sch_ICXpathError, xPath);
                }
            }
            axis3.Input = null;
            if (axis2 == null)
            {
                if (IsSelf(axis) && axis.Input != null)
                {
                    _fAxisArray.Add(new ForwardAxis(DoubleLinkAxis.ConvertTree((Axis)axis.Input), isdesorself: false));
                }
                else
                {
                    _fAxisArray.Add(new ForwardAxis(DoubleLinkAxis.ConvertTree(axis), isdesorself: false));
                }
                continue;
            }
            if (!IsDescendantOrSelf(axis2))
            {
                throw new XmlSchemaException(System.SR.Sch_ICXpathError, xPath);
            }
            try
            {
                axis2 = (Axis)axis2.Input;
            }
            catch
            {
                throw new XmlSchemaException(System.SR.Sch_ICXpathError, xPath);
            }
            if (axis2 == null || !IsSelf(axis2) || axis2.Input != null)
            {
                throw new XmlSchemaException(System.SR.Sch_ICXpathError, xPath);
            }
            if (IsSelf(axis) && axis.Input != null)
            {
                _fAxisArray.Add(new ForwardAxis(DoubleLinkAxis.ConvertTree((Axis)axis.Input), isdesorself: true));
            }
            else
            {
                _fAxisArray.Add(new ForwardAxis(DoubleLinkAxis.ConvertTree(axis), isdesorself: true));
            }
        }
    }
References System.Xml.Schema.Asttree._fAxisArray, System.Collections.ArrayList.Add(), System.array, System.Xml.Schema.DoubleLinkAxis.ConvertTree(), System.Xml.Dictionary, System.Xml.Schema.Asttree.IsAttribute(), System.Xml.Schema.Asttree.IsDescendantOrSelf(), System.Xml.Schema.Asttree.IsNameTest(), System.Xml.Schema.Asttree.IsSelf(), MS.Internal.Xml.XPath.XPathParser.ParseXPathExpression(), System.SR.Sch_EmptyXPath, System.SR.Sch_ICXpathError, System.SR.Sch_SelectorAttr, System.Xml.Schema.Asttree.SetURN(), and System.value.
Referenced by System.Xml.Schema.Asttree.Asttree().