Terraria: System.Threading.Tasks.TplEventSource.IncompleteAsyncMethod
IncompleteAsyncMethod() [1/2]
void System.Threading.Tasks.TplEventSource.IncompleteAsyncMethod (IAsyncStateMachineBox stateMachineBox) inline
Definition at line 414 of file TplEventSource.cs.
    {
        if (IsEnabled() && IsEnabled(EventLevel.Warning, (EventKeywords)256L))
        {
            IAsyncStateMachine stateMachineObject = stateMachineBox.GetStateMachineObject();
            if (stateMachineObject != null)
            {
                string asyncStateMachineDescription = AsyncMethodBuilderCore.GetAsyncStateMachineDescription(stateMachineObject);
                IncompleteAsyncMethod(asyncStateMachineDescription);
            }
        }
    }
References System.Runtime.CompilerServices.AsyncMethodBuilderCore.GetAsyncStateMachineDescription(), System.Runtime.CompilerServices.IAsyncStateMachineBox.GetStateMachineObject(), System.Threading.Tasks.TplEventSource.IncompleteAsyncMethod(), System.Diagnostics.Tracing.EventSource.IsEnabled(), and System.L.
Referenced by System.Threading.Tasks.TplEventSource.IncompleteAsyncMethod().