Terraria: System.Linq.Parallel.QueryTaskGroupState.QueryEnd
QueryEnd()
void System.Linq.Parallel.QueryTaskGroupState.QueryEnd (bool userInitiatedDispose) inline package
Definition at line 33 of file QueryTaskGroupState.cs.
    {
        if (Interlocked.Exchange(ref _alreadyEnded, 1) != 0)
        {
            return;
        }
        try
        {
            _rootTask.Wait();
        }
        catch (AggregateException ex)
        {
            AggregateException ex2 = ex.Flatten();
            bool flag = true;
            for (int i = 0; i < ex2.InnerExceptions.Count; i++)
            {
                if (!(ex2.InnerExceptions[i] is OperationCanceledException { CancellationToken: { IsCancellationRequested: not false } } ex3) || ex3.CancellationToken != _cancellationState.ExternalCancellationToken)
                {
                    flag = false;
                    break;
                }
            }
            if (!flag || ex2.InnerExceptions.Count == 0)
            {
                throw ex2;
            }
        }
        finally
        {
            ((IDisposable)_rootTask)?.Dispose();
        }
        if (_cancellationState.MergedCancellationToken.IsCancellationRequested)
        {
            if (!_cancellationState.TopLevelDisposedFlag.Value)
            {
                CancellationState.ThrowWithStandardMessageIfCanceled(_cancellationState.ExternalCancellationToken);
            }
            if (!userInitiatedDispose)
            {
                throw new ObjectDisposedException("enumerator", System.SR.PLINQ_DisposeRequested);
            }
        }
    }
References System.Linq.Parallel.QueryTaskGroupState._alreadyEnded, System.Linq.Parallel.QueryTaskGroupState._cancellationState, System.Linq.Parallel.QueryTaskGroupState._rootTask, System.Threading.Interlocked.Exchange(), System.Linq.Parallel.CancellationState.ExternalCancellationToken, System.AggregateException.Flatten(), System.AggregateException.InnerExceptions, and System.Threading.Tasks.Task< TResult >.Wait().
Referenced by System.Linq.Parallel.MergeEnumerator< TInputOutput >.Dispose(), System.Linq.Parallel.AsynchronousChannelMergeEnumerator< T >.MoveNextSlowPath(), System.Linq.Parallel.OrderPreservingSpoolingTask< TInputOutput, TKey >.Spool(), System.Linq.Parallel.SpoolingTask.SpoolForAll< TInputOutput, TIgnoreKey >(), System.Linq.Parallel.SpoolingTask.SpoolStopAndGo< TInputOutput, TIgnoreKey >(), and System.Linq.Parallel.OrderPreservingPipeliningMergeHelper< TOutput, TKey >.OrderedPipeliningMergeEnumerator.ThrowIfInTearDown().