Terraria: System.IO.Compression.BrotliStream.WriteAsyncMemoryCore
WriteAsyncMemoryCore()
async ValueTask System.IO.Compression.BrotliStream.WriteAsyncMemoryCore (ReadOnlyMemory< byte > buffer, CancellationToken cancellationToken, bool isFinalBlock = false) inline private
Definition at line 163 of file BrotliStream.cs.
    {
        AsyncOperationStarting();
        try
        {
            OperationStatus lastResult = OperationStatus.DestinationTooSmall;
            while (lastResult == OperationStatus.DestinationTooSmall)
            {
                Memory<byte> destination = new Memory<byte>(_buffer);
                int bytesConsumed = 0;
                int bytesWritten = 0;
                lastResult = _encoder.Compress(buffer, destination, out bytesConsumed, out bytesWritten, isFinalBlock);
                if (lastResult == OperationStatus.InvalidData)
                {
                    throw new InvalidOperationException(System.SR.BrotliStream_Compress_InvalidData);
                }
                if (bytesConsumed > 0)
                {
                    buffer = buffer.Slice(bytesConsumed);
                }
                if (bytesWritten > 0)
                {
                    await _stream.WriteAsync(new ReadOnlyMemory<byte>(_buffer, 0, bytesWritten), cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
                }
            }
        }
        finally
        {
            AsyncOperationCompleting();
        }
    }
References System.IO.Compression.BrotliStream._buffer, System.IO.Compression.BrotliStream._encoder, System.IO.Compression.BrotliStream._stream, System.IO.Compression.BrotliStream.AsyncOperationCompleting(), System.IO.Compression.BrotliStream.AsyncOperationStarting(), System.SR.BrotliStream_Compress_InvalidData, System.buffer, System.cancellationToken, System.IO.Compression.BrotliEncoder.Compress(), System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.destination, and System.IO.Stream.WriteAsync().
Referenced by System.IO.Compression.BrotliStream.DisposeAsync(), and System.IO.Compression.BrotliStream.WriteAsync().