Terraria: System.IO.Compression.BrotliStream.WriteCore
WriteCore()
void System.IO.Compression.BrotliStream.WriteCore (ReadOnlySpan< byte > buffer, bool isFinalBlock = false) inline package
Definition at line 105 of file BrotliStream.cs.
    {
        if (_mode != CompressionMode.Compress)
        {
            throw new InvalidOperationException(System.SR.BrotliStream_Decompress_UnsupportedOperation);
        }
        EnsureNotDisposed();
        OperationStatus operationStatus = OperationStatus.DestinationTooSmall;
        Span<byte> destination = new Span<byte>(_buffer);
        while (operationStatus == OperationStatus.DestinationTooSmall)
        {
            operationStatus = _encoder.Compress(buffer, destination, out var bytesConsumed, out var bytesWritten, isFinalBlock);
            if (operationStatus == OperationStatus.InvalidData)
            {
                throw new InvalidOperationException(System.SR.BrotliStream_Compress_InvalidData);
            }
            if (bytesWritten > 0)
            {
                _stream.Write(destination.Slice(0, bytesWritten));
            }
            if (bytesConsumed > 0)
            {
                buffer = buffer.Slice(bytesConsumed);
            }
        }
    }
References System.IO.Compression.BrotliStream._buffer, System.IO.Compression.BrotliStream._encoder, System.IO.Compression.BrotliStream._mode, System.IO.Compression.BrotliStream._stream, System.SR.BrotliStream_Compress_InvalidData, System.SR.BrotliStream_Decompress_UnsupportedOperation, System.buffer, System.IO.Compression.BrotliEncoder.Compress(), System.destination, System.IO.Compression.BrotliStream.EnsureNotDisposed(), and System.IO.Stream.Write().
Referenced by System.IO.Compression.BrotliStream.Dispose(), System.IO.Compression.BrotliStream.Write(), System.IO.Compression.BrotliStream.Write(), and System.IO.Compression.BrotliStream.WriteByte().