Terraria: System.IO.Compression.BrotliStream.FlushAsyncCore
FlushAsyncCore()
async Task System.IO.Compression.BrotliStream.FlushAsyncCore (CancellationToken cancellationToken) inline private
Definition at line 234 of file BrotliStream.cs.
    {
        AsyncOperationStarting();
        try
        {
            if (_encoder._state == null || _encoder._state.IsClosed)
            {
                return;
            }
            OperationStatus lastResult = OperationStatus.DestinationTooSmall;
            while (lastResult == OperationStatus.DestinationTooSmall)
            {
                Memory<byte> destination = new Memory<byte>(_buffer);
                int bytesWritten = 0;
                lastResult = _encoder.Flush(destination, out bytesWritten);
                if (lastResult == OperationStatus.InvalidData)
                {
                    throw new InvalidDataException(System.SR.BrotliStream_Compress_InvalidData);
                }
                if (bytesWritten > 0)
                {
                    await _stream.WriteAsync(destination.Slice(0, bytesWritten), cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
                }
            }
            await _stream.FlushAsync(cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
        }
        finally
        {
            AsyncOperationCompleting();
        }
    }
References System.IO.Compression.BrotliStream._buffer, System.IO.Compression.BrotliStream._encoder, System.IO.Compression.BrotliEncoder._state, System.IO.Compression.BrotliStream._stream, System.IO.Compression.BrotliStream.AsyncOperationCompleting(), System.IO.Compression.BrotliStream.AsyncOperationStarting(), System.SR.BrotliStream_Compress_InvalidData, System.cancellationToken, System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.destination, System.IO.Compression.BrotliEncoder.Flush(), System.IO.Stream.FlushAsync(), and System.IO.Stream.WriteAsync().
Referenced by System.IO.Compression.BrotliStream.FlushAsync().