Terraria: System.IO.Compression.BrotliStream.ReleaseStateForDispose
ReleaseStateForDispose()
void System.IO.Compression.BrotliStream.ReleaseStateForDispose () inline private
Definition at line 485 of file BrotliStream.cs.
    {
        _stream = null;
        _encoder.Dispose();
        _decoder.Dispose();
        byte[] buffer = _buffer;
        if (buffer != null)
        {
            _buffer = null;
            if (!AsyncOperationIsActive)
            {
                ArrayPool<byte>.Shared.Return(buffer);
            }
        }
    }
References System.IO.Compression.BrotliStream._buffer, System.IO.Compression.BrotliStream._decoder, System.IO.Compression.BrotliStream._encoder, System.IO.Compression.BrotliStream._stream, System.IO.Compression.BrotliStream.AsyncOperationIsActive, System.buffer, System.IO.Compression.BrotliDecoder.Dispose(), System.IO.Compression.BrotliEncoder.Dispose(), and System.Buffers.ArrayPool< T >.Shared.
Referenced by System.IO.Compression.BrotliStream.Dispose(), and System.IO.Compression.BrotliStream.DisposeAsync().