Terraria: System.IO.Compression.BrotliStream.Dispose
Dispose() [2/2]
override void System.IO.Compression.BrotliStream.Dispose (bool disposing) inline protected virtual
Reimplemented from System.IO.Stream.
Definition at line 439 of file BrotliStream.cs.
    {
        try
        {
            if (disposing && _stream != null)
            {
                if (_mode == CompressionMode.Compress)
                {
                    WriteCore(ReadOnlySpan<byte>.Empty, isFinalBlock: true);
                }
                if (!_leaveOpen)
                {
                    _stream.Dispose();
                }
            }
        }
        finally
        {
            ReleaseStateForDispose();
            base.Dispose(disposing);
        }
    }
References System.IO.Compression.BrotliStream._leaveOpen, System.IO.Compression.BrotliStream._mode, System.IO.Compression.BrotliStream._stream, System.IO.Stream.Dispose(), System.IO.Compression.BrotliStream.ReleaseStateForDispose(), and System.IO.Compression.BrotliStream.WriteCore().