Terraria: System.IO.Compression.BrotliStream.DisposeAsync
DisposeAsync()
override async ValueTask System.IO.Compression.BrotliStream.DisposeAsync () inline virtual
Reimplemented from System.IO.Stream.
Definition at line 462 of file BrotliStream.cs.
    {
        _ = 1;
        try
        {
            if (_stream != null)
            {
                if (_mode == CompressionMode.Compress)
                {
                    await WriteAsyncMemoryCore(ReadOnlyMemory<byte>.Empty, CancellationToken.None, isFinalBlock: true).ConfigureAwait(continueOnCapturedContext: false);
                }
                if (!_leaveOpen)
                {
                    await _stream.DisposeAsync().ConfigureAwait(continueOnCapturedContext: false);
                }
            }
        }
        finally
        {
            ReleaseStateForDispose();
        }
    }
References System.IO.Compression.BrotliStream._leaveOpen, System.IO.Compression.BrotliStream._mode, System.IO.Compression.BrotliStream._stream, System.Threading.Tasks.ValueTask< TResult >.ConfigureAwait(), System.IO.Stream.DisposeAsync(), System.Threading.CancellationToken.None, System.IO.Compression.BrotliStream.ReleaseStateForDispose(), and System.IO.Compression.BrotliStream.WriteAsyncMemoryCore().