Terraria: System.IO.Compression.BrotliStream.TryDecompress
TryDecompress()
bool System.IO.Compression.BrotliStream.TryDecompress (Span< byte > destination, out int bytesWritten) inline private
Definition at line 363 of file BrotliStream.cs.
    {
        int bytesConsumed;
        OperationStatus operationStatus = _decoder.Decompress(new ReadOnlySpan<byte>(_buffer, _bufferOffset, _bufferCount), destination, out bytesConsumed, out bytesWritten);
        if (operationStatus == OperationStatus.InvalidData)
        {
            throw new InvalidOperationException(System.SR.BrotliStream_Decompress_InvalidData);
        }
        if (bytesConsumed != 0)
        {
            _bufferOffset += bytesConsumed;
            _bufferCount -= bytesConsumed;
        }
        if (bytesWritten != 0 || operationStatus == OperationStatus.Done)
        {
            return true;
        }
        if (destination.IsEmpty && _bufferCount != 0)
        {
            return true;
        }
        if (_bufferCount != 0 && _bufferOffset != 0)
        {
            new ReadOnlySpan<byte>(_buffer, _bufferOffset, _bufferCount).CopyTo(_buffer);
        }
        _bufferOffset = 0;
        return false;
    }
References System.IO.Compression.BrotliStream._buffer, System.IO.Compression.BrotliStream._bufferCount, System.IO.Compression.BrotliStream._bufferOffset, System.IO.Compression.BrotliStream._decoder, System.SR.BrotliStream_Decompress_InvalidData, System.ReadOnlySpan< T >.CopyTo(), System.IO.Compression.BrotliDecoder.Decompress(), and System.destination.
Referenced by System.IO.Compression.BrotliStream.Read(), and System.IO.Compression.BrotliStream.ReadAsync().