Terraria: System.IO.Compression.BrotliStream.Flush
Flush()
override void System.IO.Compression.BrotliStream.Flush () inline
Definition at line 195 of file BrotliStream.cs.
    {
        EnsureNotDisposed();
        if (_mode != CompressionMode.Compress || _encoder._state == null || _encoder._state.IsClosed)
        {
            return;
        }
        OperationStatus operationStatus = OperationStatus.DestinationTooSmall;
        Span<byte> destination = new Span<byte>(_buffer);
        while (operationStatus == OperationStatus.DestinationTooSmall)
        {
            operationStatus = _encoder.Flush(destination, out var bytesWritten);
            if (operationStatus == OperationStatus.InvalidData)
            {
                throw new InvalidDataException(System.SR.BrotliStream_Compress_InvalidData);
            }
            if (bytesWritten > 0)
            {
                _stream.Write(destination.Slice(0, bytesWritten));
            }
        }
        _stream.Flush();
    }
References System.IO.Compression.BrotliStream._buffer, System.IO.Compression.BrotliStream._encoder, System.IO.Compression.BrotliStream._mode, System.IO.Compression.BrotliEncoder._state, System.IO.Compression.BrotliStream._stream, System.SR.BrotliStream_Compress_InvalidData, System.destination, System.IO.Compression.BrotliStream.EnsureNotDisposed(), System.IO.Stream.Flush(), System.IO.Compression.BrotliEncoder.Flush(), and System.IO.Stream.Write().