Terraria: System.IO.Compression.BrotliStream.EnsureNotDisposed
EnsureNotDisposed()
void System.IO.Compression.BrotliStream.EnsureNotDisposed () inline private
Definition at line 431 of file BrotliStream.cs.
    {
        if (_stream == null)
        {
            throw new ObjectDisposedException(GetType().Name, System.SR.ObjectDisposed_StreamClosed);
        }
    }
References System.IO.Compression.BrotliStream._stream, System.Name, and System.SR.ObjectDisposed_StreamClosed.
Referenced by System.IO.Compression.BrotliStream.Flush(), System.IO.Compression.BrotliStream.FlushAsync(), System.IO.Compression.BrotliStream.Read(), System.IO.Compression.BrotliStream.ReadAsync(), System.IO.Compression.BrotliStream.WriteAsync(), and System.IO.Compression.BrotliStream.WriteCore().