Terraria: System.IO.Compression.BrotliStream.ReadAsync
ReadAsync() [3/3]
override ValueTask< int > System.IO.Compression.BrotliStream.ReadAsync (Memory< byte > buffer, CancellationToken cancellationToken = default(CancellationToken)) inline virtual
Reimplemented from System.IO.Stream.
Definition at line 322 of file BrotliStream.cs.
    {
        if (_mode != 0)
        {
            throw new InvalidOperationException(System.SR.BrotliStream_Compress_UnsupportedOperation);
        }
        EnsureNoActiveAsyncOperation();
        EnsureNotDisposed();
        if (cancellationToken.IsCancellationRequested)
        {
            return ValueTask.FromCanceled<int>(cancellationToken);
        }
        return Core(buffer, cancellationToken);
        async ValueTask<int> Core(Memory<byte> buffer, CancellationToken cancellationToken)
        {
            AsyncOperationStarting();
            try
            {
                int bytesWritten;
                while (!TryDecompress(buffer.Span, out bytesWritten))
                {
                    int num = await _stream.ReadAsync(_buffer.AsMemory(_bufferCount), cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
                    if (num <= 0)
                    {
                        break;
                    }
                    _bufferCount += num;
                    if (_bufferCount > _buffer.Length)
                    {
                        ThrowInvalidStream();
                    }
                }
                return bytesWritten;
            }
            finally
            {
                AsyncOperationCompleting();
            }
        }
    }
References System.IO.Compression.BrotliStream._buffer, System.IO.Compression.BrotliStream._bufferCount, System.IO.Compression.BrotliStream._mode, System.IO.Compression.BrotliStream._stream, System.IO.Compression.BrotliStream.AsyncOperationCompleting(), System.IO.Compression.BrotliStream.AsyncOperationStarting(), System.SR.BrotliStream_Compress_UnsupportedOperation, System.buffer, System.cancellationToken, System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.IO.Compression.BrotliStream.EnsureNoActiveAsyncOperation(), System.IO.Compression.BrotliStream.EnsureNotDisposed(), System.Threading.Tasks.ValueTask< TResult >.FromCanceled(), System.IO.Stream.ReadAsync(), System.IO.Compression.BrotliStream.ThrowInvalidStream(), and System.IO.Compression.BrotliStream.TryDecompress().