Terraria: System.Reflection.Metadata.CustomAttribute.GetProjectedValue
GetProjectedValue() [1/2]
BlobHandle System.Reflection.Metadata.CustomAttribute.GetProjectedValue () inline private
Definition at line 44 of file CustomAttribute.cs.
    {
        CustomAttributeValueTreatment customAttributeValueTreatment = _reader.CalculateCustomAttributeValueTreatment(Handle);
        if (customAttributeValueTreatment == CustomAttributeValueTreatment.None)
        {
            return _reader.CustomAttributeTable.GetValue(Handle);
        }
        return GetProjectedValue(customAttributeValueTreatment);
    }
References System.Reflection.Metadata.CustomAttribute._reader, System.Reflection.Metadata.MetadataReader.CalculateCustomAttributeValueTreatment(), System.Reflection.Metadata.MetadataReader.CustomAttributeTable, System.Reflection.Metadata.CustomAttribute.GetProjectedValue(), and System.Reflection.Metadata.Ecma335.CustomAttributeTableReader.GetValue().
Referenced by System.Reflection.Metadata.CustomAttribute.GetProjectedValue().