Terraria: System.Reflection.Metadata.CustomAttribute.GetProjectedValue
GetProjectedValue() [2/2]
BlobHandle System.Reflection.Metadata.CustomAttribute.GetProjectedValue (CustomAttributeValueTreatment treatment) inline private
Definition at line 54 of file CustomAttribute.cs.
    {
        BlobHandle.VirtualIndex virtualIndex;
        bool flag;
        switch (treatment)
        {
        case CustomAttributeValueTreatment.AttributeUsageVersionAttribute:
        case CustomAttributeValueTreatment.AttributeUsageDeprecatedAttribute:
            virtualIndex = BlobHandle.VirtualIndex.AttributeUsage_AllowMultiple;
            flag = true;
            break;
        case CustomAttributeValueTreatment.AttributeUsageAllowMultiple:
            virtualIndex = BlobHandle.VirtualIndex.AttributeUsage_AllowMultiple;
            flag = false;
            break;
        case CustomAttributeValueTreatment.AttributeUsageAllowSingle:
            virtualIndex = BlobHandle.VirtualIndex.AttributeUsage_AllowSingle;
            flag = false;
            break;
        default:
            return default(BlobHandle);
        }
        BlobHandle value = _reader.CustomAttributeTable.GetValue(Handle);
        BlobReader blobReader = _reader.GetBlobReader(value);
        if (blobReader.Length != 8)
        {
            return value;
        }
        if (blobReader.ReadInt16() != 1)
        {
            return value;
        }
        AttributeTargets attributeTargets = ProjectAttributeTargetValue(blobReader.ReadUInt32());
        if (flag)
        {
            attributeTargets |= AttributeTargets.Constructor | AttributeTargets.Property;
        }
        return BlobHandle.FromVirtualIndex(virtualIndex, (ushort)attributeTargets);
    }
References System.Reflection.Metadata.CustomAttribute._reader, System.Reflection.Metadata.MetadataReader.CustomAttributeTable, System.Reflection.Metadata.BlobHandle.FromVirtualIndex(), System.Reflection.Metadata.MetadataReader.GetBlobReader(), System.Reflection.Metadata.Ecma335.CustomAttributeTableReader.GetValue(), System.Reflection.Metadata.BlobReader.Length, System.Reflection.Metadata.CustomAttribute.ProjectAttributeTargetValue(), System.Reflection.Metadata.BlobReader.ReadInt16(), System.Reflection.Metadata.BlobReader.ReadUInt32(), and System.value.