Terraria: System.Reflection.Metadata.Ecma335.SignatureDecoder.DecodeArrayType
DecodeArrayType()
TType System.Reflection.Metadata.Ecma335.SignatureDecoder< TType, TGenericContext >.DecodeArrayType (ref BlobReader blobReader) inline private
Definition at line 180 of file SignatureDecoder.cs.
    {
        TType elementType = DecodeType(ref blobReader);
        int rank = blobReader.ReadCompressedInteger();
        ImmutableArray<int> sizes = ImmutableArray<int>.Empty;
        ImmutableArray<int> lowerBounds = ImmutableArray<int>.Empty;
        int num = blobReader.ReadCompressedInteger();
        if (num > 0)
        {
            ImmutableArray<int>.Builder builder = ImmutableArray.CreateBuilder<int>(num);
            for (int i = 0; i < num; i++)
            {
                builder.Add(blobReader.ReadCompressedInteger());
            }
            sizes = builder.MoveToImmutable();
        }
        int num2 = blobReader.ReadCompressedInteger();
        if (num2 > 0)
        {
            ImmutableArray<int>.Builder builder2 = ImmutableArray.CreateBuilder<int>(num2);
            for (int j = 0; j < num2; j++)
            {
                builder2.Add(blobReader.ReadCompressedSignedInteger());
            }
            lowerBounds = builder2.MoveToImmutable();
        }
        ArrayShape shape = new ArrayShape(rank, sizes, lowerBounds);
        return _provider.GetArrayType(elementType, shape);
    }
References System.Reflection.Metadata.Ecma335.SignatureDecoder< TType, TGenericContext >._provider, System.Collections.Immutable.ImmutableArray< T >.Add(), System.Reflection.Metadata.Ecma335.SignatureDecoder< TType, TGenericContext >.DecodeType(), System.elementType, System.Collections.Immutable.ImmutableArray< T >.Empty, and System.lowerBounds.
Referenced by System.Reflection.Metadata.Ecma335.SignatureDecoder< TType, TGenericContext >.DecodeType().