Terraria: System.Reflection.Metadata.Ecma335.SignatureDecoder.DecodeGenericTypeInstance
DecodeGenericTypeInstance()
TType System.Reflection.Metadata.Ecma335.SignatureDecoder< TType, TGenericContext >.DecodeGenericTypeInstance (ref BlobReader blobReader) inline private
Definition at line 210 of file SignatureDecoder.cs.
    {
        TType genericType = DecodeType(ref blobReader);
        ImmutableArray<TType> typeArguments = DecodeTypeSequence(ref blobReader);
        return _provider.GetGenericInstantiation(genericType, typeArguments);
    }
References System.Reflection.Metadata.Ecma335.SignatureDecoder< TType, TGenericContext >._provider, System.Reflection.Metadata.Ecma335.SignatureDecoder< TType, TGenericContext >.DecodeType(), and System.Reflection.Metadata.Ecma335.SignatureDecoder< TType, TGenericContext >.DecodeTypeSequence().
Referenced by System.Reflection.Metadata.Ecma335.SignatureDecoder< TType, TGenericContext >.DecodeType().