Terraria: System.Reflection.Metadata.Ecma335.SignatureDecoder.DecodeTypeSequence
DecodeTypeSequence()
ImmutableArray< TType > System.Reflection.Metadata.Ecma335.SignatureDecoder< TType, TGenericContext >.DecodeTypeSequence (ref BlobReader blobReader) inline private
Definition at line 103 of file SignatureDecoder.cs.
    {
        int num = blobReader.ReadCompressedInteger();
        if (num == 0)
        {
            throw new BadImageFormatException(System.SR.SignatureTypeSequenceMustHaveAtLeastOneElement);
        }
        ImmutableArray<TType>.Builder builder = ImmutableArray.CreateBuilder<TType>(num);
        for (int i = 0; i < num; i++)
        {
            builder.Add(DecodeType(ref blobReader));
        }
        return builder.MoveToImmutable();
    }
References System.Collections.Immutable.ImmutableArray< T >.Add(), System.Reflection.Metadata.Ecma335.SignatureDecoder< TType, TGenericContext >.DecodeType(), and System.SR.SignatureTypeSequenceMustHaveAtLeastOneElement.
Referenced by System.Reflection.Metadata.Ecma335.SignatureDecoder< TType, TGenericContext >.DecodeGenericTypeInstance(), System.Reflection.Metadata.Ecma335.SignatureDecoder< TType, TGenericContext >.DecodeLocalSignature(), and System.Reflection.Metadata.Ecma335.SignatureDecoder< TType, TGenericContext >.DecodeMethodSpecificationSignature().