Terraria: System.Reflection.Metadata.Ecma335.SignatureDecoder.DecodeFieldSignature
DecodeFieldSignature()
TType System.Reflection.Metadata.Ecma335.SignatureDecoder< TType, TGenericContext >.DecodeFieldSignature (ref BlobReader blobReader) inline
Definition at line 173 of file SignatureDecoder.cs.
    {
        SignatureHeader header = blobReader.ReadSignatureHeader();
        CheckHeader(header, SignatureKind.Field);
        return DecodeType(ref blobReader);
    }
References System.Reflection.Metadata.Ecma335.SignatureDecoder< TType, TGenericContext >.CheckHeader(), and System.Reflection.Metadata.Ecma335.SignatureDecoder< TType, TGenericContext >.DecodeType().
Referenced by System.Reflection.Metadata.MemberReference.DecodeFieldSignature< TType, TGenericContext >(), and System.Reflection.Metadata.FieldDefinition.DecodeSignature< TType, TGenericContext >().