Terraria: System.Reflection.Metadata.Ecma335.SignatureDecoder.DecodeType
DecodeType() [1/2]
TType System.Reflection.Metadata.Ecma335.SignatureDecoder< TType, TGenericContext >.DecodeType (ref BlobReader blobReader, bool allowTypeSpecifications, int typeCode) inline private
Definition at line 29 of file SignatureDecoder.cs.
    {
        switch (typeCode)
        {
        case 1:
        case 2:
        case 3:
        case 4:
        case 5:
        case 6:
        case 7:
        case 8:
        case 9:
        case 10:
        case 11:
        case 12:
        case 13:
        case 14:
        case 22:
        case 24:
        case 25:
        case 28:
            return _provider.GetPrimitiveType((PrimitiveTypeCode)typeCode);
        case 15:
        {
            TType elementType = DecodeType(ref blobReader);
            return _provider.GetPointerType(elementType);
        }
        case 16:
        {
            TType elementType = DecodeType(ref blobReader);
            return _provider.GetByReferenceType(elementType);
        }
        case 69:
        {
            TType elementType = DecodeType(ref blobReader);
            return _provider.GetPinnedType(elementType);
        }
        case 29:
        {
            TType elementType = DecodeType(ref blobReader);
            return _provider.GetSZArrayType(elementType);
        }
        case 27:
        {
            MethodSignature<TType> signature = DecodeMethodSignature(ref blobReader);
            return _provider.GetFunctionPointerType(signature);
        }
        case 20:
            return DecodeArrayType(ref blobReader);
        case 31:
            return DecodeModifiedType(ref blobReader, isRequired: true);
        case 32:
            return DecodeModifiedType(ref blobReader, isRequired: false);
        case 21:
            return DecodeGenericTypeInstance(ref blobReader);
        case 19:
        {
            int index = blobReader.ReadCompressedInteger();
            return _provider.GetGenericTypeParameter(_genericContext, index);
        }
        case 30:
        {
            int index = blobReader.ReadCompressedInteger();
            return _provider.GetGenericMethodParameter(_genericContext, index);
        }
        case 17:
        case 18:
            return DecodeTypeHandle(ref blobReader, (byte)typeCode, allowTypeSpecifications);
        default:
            throw new BadImageFormatException(System.SR.Format(System.SR.UnexpectedSignatureTypeCode, typeCode));
        }
    }
References System.Reflection.Metadata.Ecma335.SignatureDecoder< TType, TGenericContext >._genericContext, System.Reflection.Metadata.Ecma335.SignatureDecoder< TType, TGenericContext >._provider, System.Reflection.Metadata.Ecma335.SignatureDecoder< TType, TGenericContext >.DecodeArrayType(), System.Reflection.Metadata.Ecma335.SignatureDecoder< TType, TGenericContext >.DecodeGenericTypeInstance(), System.Reflection.Metadata.Ecma335.SignatureDecoder< TType, TGenericContext >.DecodeMethodSignature(), System.Reflection.Metadata.Ecma335.SignatureDecoder< TType, TGenericContext >.DecodeModifiedType(), System.Reflection.Metadata.Ecma335.SignatureDecoder< TType, TGenericContext >.DecodeType(), System.Reflection.Metadata.Ecma335.SignatureDecoder< TType, TGenericContext >.DecodeTypeHandle(), System.elementType, System.SR.Format(), System.index, and System.SR.UnexpectedSignatureTypeCode.