Terraria: SlimeSky.GenerateSlimes
GenerateSlimes()
void SlimeSky.GenerateSlimes () inline private
     {
         _slimes = new Slime[Main.maxTilesY / 6];
         for (int i = 0; i < _slimes.Length; i++)
         {
             int num = (int)((double)Main.screenPosition.Y * 0.7 - (double)Main.screenHeight);
             int minValue = (int)((double)num - Main.worldSurface * 16.0);
             _slimes[i].Position = new Vector2(_random.Next(0, Main.maxTilesX) * 16, _random.Next(minValue, num));
             _slimes[i].Speed = 5f + 3f * (float)_random.NextDouble();
             _slimes[i].Depth = (float)i / (float)_slimes.Length * 1.75f + 1.6f;
             _slimes[i].Texture = _textures[_random.Next(2)].Value;
             if (_random.Next(60) == 0)
             {
                 _slimes[i].Texture = _textures[3].Value;
                 _slimes[i].Speed = 6f + 3f * (float)_random.NextDouble();
                 _slimes[i].Depth += 0.5f;
             }
             else if (_random.Next(30) == 0)
             {
                 _slimes[i].Texture = _textures[2].Value;
                 _slimes[i].Speed = 6f + 2f * (float)_random.NextDouble();
             }
             _slimes[i].Active = true;
         }
         _slimesRemaining = _slimes.Length;
     }
References _random, _slimes, _slimesRemaining, _textures, SlimeSky.Slime.Active, SlimeSky.Slime.Depth, Main.maxTilesX, Main.maxTilesY, UnifiedRandom.Next(), UnifiedRandom.NextDouble(), SlimeSky.Slime.Position, Main.screenHeight, Main.screenPosition, SlimeSky.Slime.Speed, SlimeSky.Slime.Texture, Asset< T >.Value, and Main.worldSurface.
Referenced by Activate(), and OnLoad().