Terraria: System.Linq.Expressions.Interpreter.TryCatchFinallyHandler.FilterPasses
FilterPasses()
static bool System.Linq.Expressions.Interpreter.TryCatchFinallyHandler.FilterPasses (InterpretedFrame frame, ref object exception, ExceptionFilter filter) inline static private
Definition at line 67 of file TryCatchFinallyHandler.cs.
    {
        Interpreter interpreter = frame.Interpreter;
        Instruction[] instructions = interpreter.Instructions.Instructions;
        int stackIndex = frame.StackIndex;
        int instructionIndex = frame.InstructionIndex;
        try
        {
            int num = (frame.InstructionIndex = interpreter._labels[filter.LabelIndex].Index);
            frame.Push(exception);
            while (num >= filter.StartIndex && num < filter.EndIndex)
            {
                num = (frame.InstructionIndex = num + instructions[num].Run(frame));
            }
            object obj = frame.Pop();
            if ((bool)frame.Pop())
            {
                exception = obj;
                return true;
            }
        }
        catch
        {
        }
        frame.StackIndex = stackIndex;
        frame.InstructionIndex = instructionIndex;
        return false;
    }
References System.Linq.Expressions.Interpreter.Interpreter._labels, System.Linq.Expressions.Interpreter.ExceptionFilter.EndIndex, System.exception, System.Linq.Expressions.Interpreter.RuntimeLabel.Index, System.Linq.Expressions.Interpreter.InterpretedFrame.InstructionIndex, System.Linq.Expressions.Interpreter.InstructionArray.Instructions, System.Linq.Expressions.Interpreter.Interpreter.Instructions, System.Linq.Expressions.Interpreter.InterpretedFrame.Interpreter, System.Linq.Expressions.Interpreter.ExceptionFilter.LabelIndex, System.obj, System.Linq.Expressions.Interpreter.InterpretedFrame.Pop(), System.Linq.Expressions.Interpreter.InterpretedFrame.Push(), System.Linq.Expressions.Interpreter.Instruction.Run(), System.Linq.Expressions.Interpreter.InterpretedFrame.StackIndex, and System.Linq.Expressions.Interpreter.ExceptionFilter.StartIndex.
Referenced by System.Linq.Expressions.Interpreter.TryCatchFinallyHandler.HasHandler().