Terraria: System.Linq.Expressions.Interpreter.TryCatchFinallyHandler.HasHandler
HasHandler()
bool System.Linq.Expressions.Interpreter.TryCatchFinallyHandler.HasHandler (InterpretedFrame frame, Exception exception, [NotNullWhen(true)] out ExceptionHandler handler, out object unwrappedException) inline package
Definition at line 41 of file TryCatchFinallyHandler.cs.
    {
        frame.SaveTraceToException(exception);
        if (IsCatchBlockExist)
        {
            RuntimeWrappedException ex = exception as RuntimeWrappedException;
            unwrappedException = ((ex != null) ? ex.WrappedException : exception);
            Type type = unwrappedException.GetType();
            ExceptionHandler[] handlers = _handlers;
            foreach (ExceptionHandler exceptionHandler in handlers)
            {
                if (exceptionHandler.Matches(type) && (exceptionHandler.Filter == null || FilterPasses(frame, ref unwrappedException, exceptionHandler.Filter)))
                {
                    handler = exceptionHandler;
                    return true;
                }
            }
        }
        else
        {
            unwrappedException = null;
        }
        handler = null;
        return false;
    }
References System.Linq.Expressions.Interpreter.TryCatchFinallyHandler._handlers, System.exception, System.Linq.Expressions.Interpreter.ExceptionHandler.Filter, System.Linq.Expressions.Interpreter.TryCatchFinallyHandler.FilterPasses(), System.Type.GetType(), System.Linq.Expressions.Interpreter.TryCatchFinallyHandler.IsCatchBlockExist, System.Linq.Expressions.Interpreter.ExceptionHandler.Matches(), System.Linq.Expressions.Interpreter.InterpretedFrame.SaveTraceToException(), System.type, and System.Runtime.CompilerServices.RuntimeWrappedException.WrappedException.
Referenced by System.Linq.Expressions.Interpreter.EnterTryCatchFinallyInstruction.Run().