Terraria: System.Xml.BinXmlDateTime.XsdKatmaiDateTimeToDateTime
XsdKatmaiDateTimeToDateTime()
static DateTime System.Xml.BinXmlDateTime.XsdKatmaiDateTimeToDateTime (byte[] data, int offset) inline static
Definition at line 262 of file BinXmlDateTime.cs.
    {
        long katmaiTimeTicks = GetKatmaiTimeTicks(data, ref offset);
        long katmaiDateTicks = GetKatmaiDateTicks(data, ref offset);
        return new DateTime(katmaiDateTicks + katmaiTimeTicks);
    }
References System.Xml.DateTime, System.Xml.Dictionary, System.Xml.BinXmlDateTime.GetKatmaiDateTicks(), System.Xml.BinXmlDateTime.GetKatmaiTimeTicks(), and System.offset.
Referenced by System.Xml.XmlSqlBinaryReader.ValueAsDateTime(), System.Xml.BinXmlDateTime.XsdKatmaiDateTimeToString(), and System.Xml.BinXmlDateTime.XsdKatmaiTimeToDateTime().