Terraria: System.Xml.BinXmlDateTime.XsdKatmaiTimeOffsetToString
XsdKatmaiTimeOffsetToString()
static string System.Xml.BinXmlDateTime.XsdKatmaiTimeOffsetToString (byte[] data, int offset) inline static
Definition at line 353 of file BinXmlDateTime.cs.
    {
        DateTimeOffset dt = XsdKatmaiTimeOffsetToDateTimeOffset(data, offset);
        StringBuilder stringBuilder = new StringBuilder(22);
        WriteTimeFullPrecision(stringBuilder, dt.Hour, dt.Minute, dt.Second, GetFractions(dt));
        WriteTimeZone(stringBuilder, dt.Offset);
        return stringBuilder.ToString();
    }
References System.Xml.Dictionary, System.Xml.BinXmlDateTime.GetFractions(), System.offset, System.Xml.BinXmlDateTime.WriteTimeFullPrecision(), System.Xml.BinXmlDateTime.WriteTimeZone(), and System.Xml.BinXmlDateTime.XsdKatmaiTimeOffsetToDateTimeOffset().
Referenced by System.Xml.XmlSqlBinaryReader.ValueAsDateTimeString().