Terraria: System.Xml.BinXmlDateTime.XsdDateTimeToString
XsdDateTimeToString()
static string System.Xml.BinXmlDateTime.XsdDateTimeToString (long val) inline static
Definition at line 183 of file BinXmlDateTime.cs.
    {
        BreakDownXsdDateTime(val, out var yr, out var mnth, out var day, out var hr, out var min, out var sec, out var ms);
        StringBuilder stringBuilder = new StringBuilder(20);
        WriteDate(stringBuilder, yr, mnth, day);
        stringBuilder.Append('T');
        WriteTime(stringBuilder, hr, min, sec, ms);
        stringBuilder.Append('Z');
        return stringBuilder.ToString();
    }
References System.Xml.BinXmlDateTime.BreakDownXsdDateTime(), System.Xml.Dictionary, System.Xml.BinXmlDateTime.WriteDate(), and System.Xml.BinXmlDateTime.WriteTime().
Referenced by System.Xml.XmlSqlBinaryReader.ValueAsDateTimeString().