Terraria: System.Xml.BinXmlDateTime.XsdKatmaiDateTimeToString
XsdKatmaiDateTimeToString()
static string System.Xml.BinXmlDateTime.XsdKatmaiDateTimeToString (byte[] data, int offset) inline static
Definition at line 315 of file BinXmlDateTime.cs.
    {
        DateTime dt = XsdKatmaiDateTimeToDateTime(data, offset);
        StringBuilder stringBuilder = new StringBuilder(33);
        WriteDate(stringBuilder, dt.Year, dt.Month, dt.Day);
        stringBuilder.Append('T');
        WriteTimeFullPrecision(stringBuilder, dt.Hour, dt.Minute, dt.Second, GetFractions(dt));
        return stringBuilder.ToString();
    }
References System.Xml.Dictionary, System.Xml.BinXmlDateTime.GetFractions(), System.offset, System.Xml.BinXmlDateTime.WriteDate(), System.Xml.BinXmlDateTime.WriteTimeFullPrecision(), and System.Xml.BinXmlDateTime.XsdKatmaiDateTimeToDateTime().
Referenced by System.Xml.XmlSqlBinaryReader.ValueAsDateTimeString().