Terraria: System.Xml.BinXmlDateTime.XsdTimeToString
XsdTimeToString()
static string System.Xml.BinXmlDateTime.XsdTimeToString (long val) inline static
Definition at line 217 of file BinXmlDateTime.cs.
    {
        BreakDownXsdTime(val, out var hr, out var min, out var sec, out var ms);
        StringBuilder stringBuilder = new StringBuilder(16);
        WriteTime(stringBuilder, hr, min, sec, ms);
        stringBuilder.Append('Z');
        return stringBuilder.ToString();
    }
References System.Xml.BinXmlDateTime.BreakDownXsdTime(), System.Xml.Dictionary, and System.Xml.BinXmlDateTime.WriteTime().
Referenced by System.Xml.XmlSqlBinaryReader.ValueAsDateTimeString().