Terraria: System.Xml.BinXmlDateTime.XsdKatmaiDateTimeOffsetToDateTimeOffset
XsdKatmaiDateTimeOffsetToDateTimeOffset()
static DateTimeOffset System.Xml.BinXmlDateTime.XsdKatmaiDateTimeOffsetToDateTimeOffset (byte[] data, int offset) inline static
Definition at line 294 of file BinXmlDateTime.cs.
    {
        long katmaiTimeTicks = GetKatmaiTimeTicks(data, ref offset);
        long katmaiDateTicks = GetKatmaiDateTicks(data, ref offset);
        long katmaiTimeZoneTicks = GetKatmaiTimeZoneTicks(data, offset);
        return new DateTimeOffset(katmaiDateTicks + katmaiTimeTicks + katmaiTimeZoneTicks, new TimeSpan(katmaiTimeZoneTicks));
    }
References System.Xml.Dictionary, System.Xml.BinXmlDateTime.GetKatmaiDateTicks(), System.Xml.BinXmlDateTime.GetKatmaiTimeTicks(), System.Xml.BinXmlDateTime.GetKatmaiTimeZoneTicks(), System.offset, and System.Xml.TimeSpan.
Referenced by System.Xml.XmlSqlBinaryReader.ValueAsDateTimeOffset(), System.Xml.BinXmlDateTime.XsdKatmaiDateOffsetToDateTimeOffset(), System.Xml.BinXmlDateTime.XsdKatmaiDateTimeOffsetToDateTime(), System.Xml.BinXmlDateTime.XsdKatmaiDateTimeOffsetToString(), and System.Xml.BinXmlDateTime.XsdKatmaiTimeOffsetToDateTimeOffset().