Terraria: System.Collections.ObjectModel.ObservableCollection.CheckReentrancy
CheckReentrancy()
void System.Collections.ObjectModel.ObservableCollection< T >.CheckReentrancy () inline protected
Definition at line 160 of file ObservableCollection.cs.
    {
        if (_blockReentrancyCount > 0)
        {
            NotifyCollectionChangedEventHandler collectionChanged = this.CollectionChanged;
            if (collectionChanged != null && collectionChanged.GetInvocationList().Length > 1)
            {
                throw new InvalidOperationException(System.SR.ObservableCollectionReentrancyNotAllowed);
            }
        }
    }
References System.Collections.ObjectModel.ObservableCollection< T >._blockReentrancyCount, System.Collections.ObjectModel.ObservableCollection< T >.CollectionChanged, System.Collections.Specialized.NotifyCollectionChangedEventHandler(), and System.SR.ObservableCollectionReentrancyNotAllowed.
Referenced by System.Collections.ObjectModel.ObservableCollection< T >.ClearItems(), System.Collections.ObjectModel.ObservableCollection< T >.InsertItem(), System.Collections.ObjectModel.ObservableCollection< T >.MoveItem(), System.Collections.ObjectModel.ObservableCollection< T >.RemoveItem(), and System.Collections.ObjectModel.ObservableCollection< T >.SetItem().