Terraria: System.Collections.ObjectModel.ObservableCollection.InsertItem
InsertItem()
override void System.Collections.ObjectModel.ObservableCollection< T >.InsertItem (int index, T item) inline protected virtual
Reimplemented from System.Collections.ObjectModel.Collection< T >.
Definition at line 104 of file ObservableCollection.cs.
    {
        CheckReentrancy();
        base.InsertItem(index, item);
        OnCountPropertyChanged();
        OnIndexerPropertyChanged();
        OnCollectionChanged(NotifyCollectionChangedAction.Add, item, index);
    }
References System.Collections.ObjectModel.ObservableCollection< T >.CheckReentrancy(), System.index, System.item, System.Collections.ObjectModel.ObservableCollection< T >.OnCollectionChanged(), System.Collections.ObjectModel.ObservableCollection< T >.OnCountPropertyChanged(), and System.Collections.ObjectModel.ObservableCollection< T >.OnIndexerPropertyChanged().