Terraria: System.Security.Cryptography.FromBase64Transform.ReturnToCryptoPool
ReturnToCryptoPool()
void System.Security.Cryptography.FromBase64Transform.ReturnToCryptoPool (byte[] array, int clearSize) inline private
Definition at line 166 of file FromBase64Transform.cs.
    {
        if (array != null)
        {
            System.Security.Cryptography.CryptoPool.Return(array, clearSize);
        }
    }
References System.array, and System.Security.Cryptography.CryptoPool.Return().
Referenced by System.Security.Cryptography.FromBase64Transform.ConvertFromBase64(), System.Security.Cryptography.FromBase64Transform.TransformBlock(), and System.Security.Cryptography.FromBase64Transform.TransformFinalBlock().