Terraria: System.Collections.ObjectModel.ObservableCollection.ClearItems
ClearItems()
override void System.Collections.ObjectModel.ObservableCollection< T >.ClearItems () inline protected virtual
Reimplemented from System.Collections.ObjectModel.Collection< T >.
Definition at line 85 of file ObservableCollection.cs.
    {
        CheckReentrancy();
        base.ClearItems();
        OnCountPropertyChanged();
        OnIndexerPropertyChanged();
        OnCollectionReset();
    }
References System.Collections.ObjectModel.ObservableCollection< T >.CheckReentrancy(), System.Collections.ObjectModel.ObservableCollection< T >.OnCollectionReset(), System.Collections.ObjectModel.ObservableCollection< T >.OnCountPropertyChanged(), and System.Collections.ObjectModel.ObservableCollection< T >.OnIndexerPropertyChanged().