Terraria: System.Security.Cryptography.FromBase64Transform.TransformBlock
TransformBlock()
int System.Security.Cryptography.FromBase64Transform.TransformBlock (byte[] inputBuffer, int inputOffset, int inputCount, byte[] outputBuffer, int outputOffset) inline
Implements System.Security.Cryptography.ICryptoTransform.
Definition at line 32 of file FromBase64Transform.cs.
    {
        ThrowHelper.ValidateTransformBlock(inputBuffer, inputOffset, inputCount);
        if (_inputBuffer == null)
        {
            ThrowHelper.ThrowObjectDisposed();
        }
        if (outputBuffer == null)
        {
            ThrowHelper.ThrowArgumentNull(ThrowHelper.ExceptionArgument.outputBuffer);
        }
        byte[] array = null;
        Span<byte> tmpBuffer = stackalloc byte[32];
        if (inputCount > 32)
        {
            tmpBuffer = (array = System.Security.Cryptography.CryptoPool.Rent(inputCount));
        }
        tmpBuffer = GetTempBuffer(inputBuffer.AsSpan(inputOffset, inputCount), tmpBuffer);
        int num = _inputIndex + tmpBuffer.Length;
        if (num < InputBlockSize)
        {
            tmpBuffer.CopyTo(_inputBuffer.AsSpan(_inputIndex));
            _inputIndex = num;
            ReturnToCryptoPool(array, tmpBuffer.Length);
            return 0;
        }
        ConvertFromBase64(tmpBuffer, outputBuffer.AsSpan(outputOffset), out var _, out var written);
        ReturnToCryptoPool(array, tmpBuffer.Length);
        return written;
    }
References System.Security.Cryptography.FromBase64Transform._inputBuffer, System.Security.Cryptography.FromBase64Transform._inputIndex, System.array, System.Security.Cryptography.FromBase64Transform.ConvertFromBase64(), System.Span< T >.CopyTo(), System.Security.Cryptography.FromBase64Transform.GetTempBuffer(), System.Security.Cryptography.FromBase64Transform.InputBlockSize, System.Span< T >.Length, System.Security.Cryptography.CryptoPool.Rent(), System.Security.Cryptography.FromBase64Transform.ReturnToCryptoPool(), System.Security.Cryptography.ThrowHelper.ThrowArgumentNull(), System.Security.Cryptography.ThrowHelper.ThrowObjectDisposed(), and System.Security.Cryptography.ThrowHelper.ValidateTransformBlock().