Terraria: System.ComponentModel.Container.ValidateName
ValidateName()
virtual void System.ComponentModel.Container.ValidateName (IComponent component, string? name) inline protected virtual inherited
Definition at line 224 of file Container.cs.
    {
        if (component == null)
        {
            throw new ArgumentNullException("component");
        }
        if (name == null)
        {
            return;
        }
        for (int i = 0; i < Math.Min(_siteCount, _sites.Length); i++)
        {
            ISite site = _sites[i];
            if (site != null && site.Name != null && string.Equals(site.Name, name, StringComparison.OrdinalIgnoreCase) && site.Component != component)
            {
                InheritanceAttribute inheritanceAttribute = (InheritanceAttribute)TypeDescriptor.GetAttributes(site.Component)[typeof(InheritanceAttribute)];
                if (inheritanceAttribute.InheritanceLevel != InheritanceLevel.InheritedReadOnly)
                {
                    throw new ArgumentException(System.SR.Format(System.SR.DuplicateComponentName, name));
                }
            }
        }
    }
References System.ComponentModel.Container._siteCount, System.ComponentModel.Container._sites, System.ComponentModel.ISite.Component, System.SR.DuplicateComponentName, System.SR.Format(), System.ComponentModel.TypeDescriptor.GetAttributes(), System.ComponentModel.InheritanceAttribute.InheritanceLevel, System.Math.Min(), and System.ComponentModel.ISite.Name.
Referenced by System.ComponentModel.Container.Add().