Terraria: System.ComponentModel.Container.Add
Add() [2/2]
virtual void System.ComponentModel.Container.Add (IComponent? component, string? name) inline virtual inherited
Implements System.ComponentModel.IContainer.
Definition at line 112 of file Container.cs.
    {
        lock (_syncObj)
        {
            if (component == null)
            {
                return;
            }
            ISite site = component.Site;
            if (site != null && site.Container == this)
            {
                return;
            }
            if (_sites == null)
            {
                _sites = new ISite[4];
            }
            else
            {
                ValidateName(component, name);
                if (_sites.Length == _siteCount)
                {
                    ISite[] array = new ISite[_siteCount * 2];
                    Array.Copy(_sites, array, _siteCount);
                    _sites = array;
                }
            }
            site?.Container.Remove(component);
            ISite site2 = CreateSite(component, name);
            _sites[_siteCount++] = site2;
            component.Site = site2;
            _components = null;
        }
    }
References System.ComponentModel.Container._components, System.ComponentModel.Container._siteCount, System.ComponentModel.Container._sites, System.ComponentModel.Container._syncObj, System.array, System.ComponentModel.ISite.Container, System.Array.Copy(), System.ComponentModel.Container.CreateSite(), System.ComponentModel.IContainer.Remove(), System.ComponentModel.IComponent.Site, and System.ComponentModel.Container.ValidateName().