Terraria: System.Collections.ObjectModel.ObservableCollection.MoveItem
MoveItem()
virtual void System.Collections.ObjectModel.ObservableCollection< T >.MoveItem (int oldIndex, int newIndex) inline protected virtual
Definition at line 122 of file ObservableCollection.cs.
    {
        CheckReentrancy();
        T val = base[oldIndex];
        base.RemoveItem(oldIndex);
        base.InsertItem(newIndex, val);
        OnIndexerPropertyChanged();
        OnCollectionChanged(NotifyCollectionChangedAction.Move, val, newIndex, oldIndex);
    }
References System.Collections.ObjectModel.ObservableCollection< T >.CheckReentrancy(), System.Runtime.Serialization.Dictionary, System.Collections.ObjectModel.ObservableCollection< T >.OnCollectionChanged(), and System.Collections.ObjectModel.ObservableCollection< T >.OnIndexerPropertyChanged().
Referenced by System.Collections.ObjectModel.ObservableCollection< T >.Move().