Terraria: System.Security.Cryptography.FromBase64Transform.ConvertFromBase64
ConvertFromBase64()
void System.Security.Cryptography.FromBase64Transform.ConvertFromBase64 (Span< byte > tmpBuffer, Span< byte > outputBuffer, out int consumed, out int written) inline private
Definition at line 144 of file FromBase64Transform.cs.
    {
        int num = _inputIndex + tmpBuffer.Length;
        byte[] array = null;
        Span<byte> span = stackalloc byte[32];
        if (num > 32)
        {
            span = (array = System.Security.Cryptography.CryptoPool.Rent(num));
        }
        _inputBuffer.AsSpan(0, _inputIndex).CopyTo(span);
        tmpBuffer.CopyTo(span.Slice(_inputIndex));
        _inputIndex = num & 3;
        num -= _inputIndex;
        tmpBuffer.Slice(tmpBuffer.Length - _inputIndex).CopyTo(_inputBuffer);
        span = span.Slice(0, num);
        if (Base64.DecodeFromUtf8(span, outputBuffer, out consumed, out written) != 0)
        {
            ThrowHelper.ThrowBase64FormatException();
        }
        ReturnToCryptoPool(array, span.Length);
    }
References System.Security.Cryptography.FromBase64Transform._inputBuffer, System.Security.Cryptography.FromBase64Transform._inputIndex, System.array, System.Span< T >.CopyTo(), System.Buffers.Text.Base64.DecodeFromUtf8(), System.Span< T >.Length, System.Security.Cryptography.CryptoPool.Rent(), System.Security.Cryptography.FromBase64Transform.ReturnToCryptoPool(), System.Span< T >.Slice(), and System.Security.Cryptography.ThrowHelper.ThrowBase64FormatException().
Referenced by System.Security.Cryptography.FromBase64Transform.TransformBlock(), and System.Security.Cryptography.FromBase64Transform.TransformFinalBlock().