Terraria: System.Net.Http.QPack.QPackDecoder.OnString
OnString()
void System.Net.Http.QPack.QPackDecoder.OnString (State nextState) inline private
Definition at line 344 of file QPackDecoder.cs.
    {
        try
        {
            if (_state == State.HeaderName)
            {
                _headerNameLength = Decode(ref _headerNameOctets);
                _headerName = _headerNameOctets;
            }
            else
            {
                _headerValueLength = Decode(ref _headerValueOctets);
            }
        }
        catch (HuffmanDecodingException innerException)
        {
            throw new QPackDecodingException(System.SR.net_http_hpack_huffman_decode_failed, innerException);
        }
        _state = nextState;
        int Decode(ref byte[] dst)
        {
            if (_huffman)
            {
                return Huffman.Decode(new ReadOnlySpan<byte>(_stringOctets, 0, _stringLength), ref dst);
            }
            if (dst.Length < _stringLength)
            {
                ReturnAndGetNewPooledArray(ref dst, _stringLength);
            }
            Buffer.BlockCopy(_stringOctets, 0, dst, 0, _stringLength);
            return _stringLength;
        }
    }
References System.Net.Http.QPack.QPackDecoder._headerName, System.Net.Http.QPack.QPackDecoder._headerNameLength, System.Net.Http.QPack.QPackDecoder._headerNameOctets, System.Net.Http.QPack.QPackDecoder._headerValueLength, System.Net.Http.QPack.QPackDecoder._headerValueOctets, System.Net.Http.QPack.QPackDecoder._huffman, System.Net.Http.QPack.QPackDecoder._state, System.Net.Http.QPack.QPackDecoder._stringLength, System.Net.Http.QPack.QPackDecoder._stringOctets, System.Buffer.BlockCopy(), System.Net.Http.QPack.QPackDecoder.Decode(), System.Net.Http.HPack.Huffman.Decode(), System.SR.net_http_hpack_huffman_decode_failed, and System.Net.Http.QPack.QPackDecoder.ReturnAndGetNewPooledArray().
Referenced by System.Net.Http.QPack.QPackDecoder.OnByte(), and System.Net.Http.QPack.QPackDecoder.ProcessHeaderValue().