Terraria: System.Net.Http.QPack.QPackDecoder.OnByte
OnByte()
void System.Net.Http.QPack.QPackDecoder.OnByte (byte b, IHttpHeadersHandler handler) inline private
Definition at line 108 of file QPackDecoder.cs.
    {
        int result;
        switch (_state)
        {
        case State.RequiredInsertCount:
            if (_integerDecoder.BeginTryDecode(b, 8, out result))
            {
                OnRequiredInsertCount(result);
            }
            else
            {
                _state = State.RequiredInsertCountContinue;
            }
            break;
        case State.RequiredInsertCountContinue:
            if (_integerDecoder.TryDecode(b, out result))
            {
                OnRequiredInsertCount(result);
            }
            break;
        case State.Base:
        {
            int num = -129 & b;
            if (_integerDecoder.BeginTryDecode(b, 7, out result))
            {
                OnBase(result);
            }
            else
            {
                _state = State.BaseContinue;
            }
            break;
        }
        case State.BaseContinue:
            if (_integerDecoder.TryDecode(b, out result))
            {
                OnBase(result);
            }
            break;
        case State.CompressedHeaders:
            switch (BitOperations.LeadingZeroCount(b))
            {
            case 24:
            {
                int num = 0x3F & b;
                if ((b & 0x40) != 64)
                {
                    ThrowDynamicTableNotSupported();
                }
                if (_integerDecoder.BeginTryDecode((byte)num, 6, out result))
                {
                    OnIndexedHeaderField(result, handler);
                }
                else
                {
                    _state = State.HeaderFieldIndex;
                }
                break;
            }
            case 25:
            {
                if ((0x10 & b) != 16)
                {
                    ThrowDynamicTableNotSupported();
                }
                int num = b & 0xF;
                if (_integerDecoder.BeginTryDecode((byte)num, 4, out result))
                {
                    OnIndexedHeaderName(result);
                }
                else
                {
                    _state = State.HeaderNameIndex;
                }
                break;
            }
            case 26:
            {
                _huffman = (b & 8) != 0;
                int num = b & 7;
                if (_integerDecoder.BeginTryDecode((byte)num, 3, out result))
                {
                    if (result == 0)
                    {
                        throw new QPackDecodingException(System.SR.Format(System.SR.net_http_invalid_header_name, ""));
                    }
                    OnStringLength(result, State.HeaderName);
                }
                else
                {
                    _state = State.HeaderNameLength;
                }
                break;
            }
            case 27:
            {
                int num = -241 & b;
                if (_integerDecoder.BeginTryDecode((byte)num, 4, out result))
                {
                    OnPostBaseIndex(result, handler);
                }
                else
                {
                    _state = State.PostBaseIndex;
                }
                break;
            }
            default:
            {
                int num = b & 7;
                if (_integerDecoder.BeginTryDecode((byte)num, 3, out result))
                {
                    OnIndexedHeaderNamePostBase(result);
                }
                else
                {
                    _state = State.HeaderNameIndexPostBase;
                }
                break;
            }
            }
            break;
        case State.HeaderNameLength:
            if (_integerDecoder.TryDecode(b, out result))
            {
                if (result == 0)
                {
                    throw new QPackDecodingException(System.SR.Format(System.SR.net_http_invalid_header_name, ""));
                }
                OnStringLength(result, State.HeaderName);
            }
            break;
        case State.HeaderName:
            _stringOctets[_stringIndex++] = b;
            if (_stringIndex == _stringLength)
            {
                OnString(State.HeaderValueLength);
            }
            break;
        case State.HeaderNameIndex:
            if (_integerDecoder.TryDecode(b, out result))
            {
                OnIndexedHeaderName(result);
            }
            break;
        case State.HeaderNameIndexPostBase:
            if (_integerDecoder.TryDecode(b, out result))
            {
                OnIndexedHeaderNamePostBase(result);
            }
            break;
        case State.HeaderValueLength:
            _huffman = (b & 0x80) != 0;
            if (_integerDecoder.BeginTryDecode((byte)(b & 0xFFFFFF7Fu), 7, out result))
            {
                OnStringLength(result, State.HeaderValue);
                if (result == 0)
                {
                    ProcessHeaderValue(handler);
                }
            }
            else
            {
                _state = State.HeaderValueLengthContinue;
            }
            break;
        case State.HeaderValueLengthContinue:
            if (_integerDecoder.TryDecode(b, out result))
            {
                OnStringLength(result, State.HeaderValue);
                if (result == 0)
                {
                    ProcessHeaderValue(handler);
                }
            }
            break;
        case State.HeaderValue:
            _stringOctets[_stringIndex++] = b;
            if (_stringIndex == _stringLength)
            {
                ProcessHeaderValue(handler);
            }
            break;
        case State.HeaderFieldIndex:
            if (_integerDecoder.TryDecode(b, out result))
            {
                OnIndexedHeaderField(result, handler);
            }
            break;
        case State.PostBaseIndex:
            if (_integerDecoder.TryDecode(b, out result))
            {
                OnPostBaseIndex(result, handler);
            }
            break;
        case State.HeaderNameLengthContinue:
        case State.DynamicTableSizeUpdate:
        case State.LiteralHeaderFieldWithNameReference:
            break;
        }
    }
References System.Net.Http.QPack.QPackDecoder._huffman, System.Net.Http.QPack.QPackDecoder._integerDecoder, System.Net.Http.QPack.QPackDecoder._state, System.Net.Http.QPack.QPackDecoder._stringIndex, System.Net.Http.QPack.QPackDecoder._stringLength, System.Net.Http.QPack.QPackDecoder._stringOctets, System.Net.Http.HPack.IntegerDecoder.BeginTryDecode(), System.SR.Format(), System.Numerics.BitOperations.LeadingZeroCount(), System.SR.net_http_invalid_header_name, System.Net.Http.QPack.QPackDecoder.OnBase(), System.Net.Http.QPack.QPackDecoder.OnIndexedHeaderField(), System.Net.Http.QPack.QPackDecoder.OnIndexedHeaderName(), System.Net.Http.QPack.QPackDecoder.OnIndexedHeaderNamePostBase(), System.Net.Http.QPack.QPackDecoder.OnPostBaseIndex(), System.Net.Http.QPack.QPackDecoder.OnRequiredInsertCount(), System.Net.Http.QPack.QPackDecoder.OnString(), System.Net.Http.QPack.QPackDecoder.OnStringLength(), System.Net.Http.QPack.QPackDecoder.ProcessHeaderValue(), System.Net.Http.QPack.QPackDecoder.ThrowDynamicTableNotSupported(), and System.Net.Http.HPack.IntegerDecoder.TryDecode().
Referenced by System.Net.Http.QPack.QPackDecoder.Decode().