Terraria: System.Net.Http.QPack.QPackDecoder.Decode
Decode()
void System.Net.Http.QPack.QPackDecoder.Decode (ReadOnlySpan< byte > headerBlock, IHttpHeadersHandler handler) inline
Definition at line 98 of file QPackDecoder.cs.
    {
        ReadOnlySpan<byte> readOnlySpan = headerBlock;
        for (int i = 0; i < readOnlySpan.Length; i++)
        {
            byte b = readOnlySpan[i];
            OnByte(b, handler);
        }
    }
References System.ReadOnlySpan< T >.Length, and System.Net.Http.QPack.QPackDecoder.OnByte().
Referenced by System.Net.Http.QPack.QPackDecoder.OnString(), and System.Net.Http.Http3RequestStream.ReadHeadersAsync().