Terraria: System.Net.Http.QPack.QPackDecoder.ThrowDynamicTableNotSupported
ThrowDynamicTableNotSupported()
static void System.Net.Http.QPack.QPackDecoder.ThrowDynamicTableNotSupported () inline static private
Definition at line 418 of file QPackDecoder.cs.
    {
        throw new QPackDecodingException(System.SR.net_http_qpack_no_dynamic_table);
    }
References System.SR.net_http_qpack_no_dynamic_table.
Referenced by System.Net.Http.QPack.QPackDecoder.OnBase(), System.Net.Http.QPack.QPackDecoder.OnByte(), System.Net.Http.QPack.QPackDecoder.OnIndexedHeaderNamePostBase(), System.Net.Http.QPack.QPackDecoder.OnPostBaseIndex(), and System.Net.Http.QPack.QPackDecoder.OnRequiredInsertCount().