Terraria: System.Threading.Mutex.OpenExistingWorker
OpenExistingWorker()
static OpenExistingResult System.Threading.Mutex.OpenExistingWorker (string name, out Mutex result) inline static private
Definition at line 70 of file Mutex.cs.
    {
        if (name == null)
        {
            throw new ArgumentNullException("name");
        }
        if (name.Length == 0)
        {
            throw new ArgumentException(SR.Argument_EmptyName, "name");
        }
        result = null;
        SafeWaitHandle safeWaitHandle = Interop.Kernel32.OpenMutex(34603009u, inheritHandle: false, name);
        if (safeWaitHandle.IsInvalid)
        {
            int lastPInvokeError = Marshal.GetLastPInvokeError();
            if (2 == lastPInvokeError || 123 == lastPInvokeError)
            {
                return OpenExistingResult.NameNotFound;
            }
            if (3 == lastPInvokeError)
            {
                return OpenExistingResult.PathNotFound;
            }
            if (6 == lastPInvokeError)
            {
                return OpenExistingResult.NameInvalid;
            }
            throw Win32Marshal.GetExceptionForWin32Error(lastPInvokeError, name);
        }
        result = new Mutex(safeWaitHandle);
        return OpenExistingResult.Success;
    }
References System.Threading.Mutex.Mutex(), System.SR.Argument_EmptyName, System.IO.Win32Marshal.GetExceptionForWin32Error(), System.Runtime.InteropServices.Marshal.GetLastPInvokeError(), Microsoft.Win32.SafeHandles.SafeHandleZeroOrMinusOneIsInvalid.IsInvalid, and Interop.Kernel32.OpenMutex().
Referenced by System.Threading.Mutex.OpenExisting(), and System.Threading.Mutex.TryOpenExisting().