Terraria: System.Net.Http.QPack.QPackDecoder.ProcessHeaderValue
ProcessHeaderValue()
void System.Net.Http.QPack.QPackDecoder.ProcessHeaderValue (IHttpHeadersHandler handler) inline private
Definition at line 326 of file QPackDecoder.cs.
    {
        OnString(State.CompressedHeaders);
        Span<byte> span = _headerValueOctets.AsSpan(0, _headerValueLength);
        int? index = _index;
        if (index.HasValue)
        {
            int valueOrDefault = index.GetValueOrDefault();
            handler.OnStaticIndexedHeader(valueOrDefault, span);
            _index = null;
        }
        else
        {
            Span<byte> span2 = _headerNameOctets.AsSpan(0, _headerNameLength);
            handler.OnHeader(span2, span);
        }
    }
References System.Net.Http.QPack.QPackDecoder._headerNameLength, System.Net.Http.QPack.QPackDecoder._headerNameOctets, System.Net.Http.QPack.QPackDecoder._headerValueLength, System.Net.Http.QPack.QPackDecoder._headerValueOctets, System.Net.Http.QPack.QPackDecoder._index, System.index, System.Net.Http.IHttpHeadersHandler.OnHeader(), System.Net.Http.IHttpHeadersHandler.OnStaticIndexedHeader(), and System.Net.Http.QPack.QPackDecoder.OnString().
Referenced by System.Net.Http.QPack.QPackDecoder.OnByte().