Terraria: System.Xml.Xsl.XsltOld.NumberAction.CompileAttribute
CompileAttribute()
override bool System.Xml.Xsl.XsltOld.NumberAction.CompileAttribute (Compiler compiler) inline package virtual
Reimplemented from System.Xml.Xsl.XsltOld.CompiledAction.
Definition at line 173 of file NumberAction.cs.
    {
        string localName = compiler.Input.LocalName;
        string value = compiler.Input.Value;
        if (Ref.Equal(localName, compiler.Atoms.Level))
        {
            if (value != "any" && value != "multiple" && value != "single")
            {
                throw XsltException.Create(System.SR.Xslt_InvalidAttrValue, "level", value);
            }
            _level = value;
        }
        else if (Ref.Equal(localName, compiler.Atoms.Count))
        {
            _countPattern = value;
            _countKey = compiler.AddQuery(value, allowVar: true, allowKey: true, isPattern: true);
        }
        else if (Ref.Equal(localName, compiler.Atoms.From))
        {
            _from = value;
            _fromKey = compiler.AddQuery(value, allowVar: true, allowKey: true, isPattern: true);
        }
        else if (Ref.Equal(localName, compiler.Atoms.Value))
        {
            _value = value;
            _valueKey = compiler.AddQuery(value);
        }
        else if (Ref.Equal(localName, compiler.Atoms.Format))
        {
            _formatAvt = Avt.CompileAvt(compiler, value);
        }
        else if (Ref.Equal(localName, compiler.Atoms.Lang))
        {
            _langAvt = Avt.CompileAvt(compiler, value);
        }
        else if (Ref.Equal(localName, compiler.Atoms.LetterValue))
        {
            _letterAvt = Avt.CompileAvt(compiler, value);
        }
        else if (Ref.Equal(localName, compiler.Atoms.GroupingSeparator))
        {
            _groupingSepAvt = Avt.CompileAvt(compiler, value);
        }
        else
        {
            if (!Ref.Equal(localName, compiler.Atoms.GroupingSize))
            {
                return false;
            }
            _groupingSizeAvt = Avt.CompileAvt(compiler, value);
        }
        return true;
    }
References System.Xml.Xsl.XsltOld.NumberAction._countKey, System.Xml.Xsl.XsltOld.NumberAction._countPattern, System.Xml.Xsl.XsltOld.NumberAction._formatAvt, System.Xml.Xsl.XsltOld.NumberAction._from, System.Xml.Xsl.XsltOld.NumberAction._fromKey, System.Xml.Xsl.XsltOld.NumberAction._groupingSepAvt, System.Xml.Xsl.XsltOld.NumberAction._groupingSizeAvt, System.Xml.Xsl.XsltOld.NumberAction._langAvt, System.Xml.Xsl.XsltOld.NumberAction._letterAvt, System.Xml.Xsl.XsltOld.NumberAction._level, System.Xml.Xsl.XsltOld.NumberAction._value, System.Xml.Xsl.XsltOld.NumberAction._valueKey, System.Xml.Xsl.XsltOld.Avt.CompileAvt(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Xml.Xsl.XsltException.Create(), System.Xml.Dictionary, System.Xml.Ref.Equal(), System.value, and System.SR.Xslt_InvalidAttrValue.