Terraria: System.Xml.Xsl.XsltOld.NumberAction.ParseFormat
ParseFormat()
static List< FormatInfo > System.Xml.Xsl.XsltOld.NumberAction.ParseFormat (string formatString) inline static private
Definition at line 682 of file NumberAction.cs.
    {
        if (formatString == null || formatString.Length == 0)
        {
            return null;
        }
        int num = 0;
        bool flag = CharUtil.IsAlphaNumeric(formatString[num]);
        List<FormatInfo> list = new List<FormatInfo>();
        int num2 = 0;
        if (flag)
        {
            list.Add(null);
        }
        while (num <= formatString.Length)
        {
            bool flag2 = ((num < formatString.Length) ? CharUtil.IsAlphaNumeric(formatString[num]) : (!flag));
            if (flag != flag2)
            {
                FormatInfo formatInfo = new FormatInfo();
                if (flag)
                {
                    mapFormatToken(formatString, num2, num - num2, out formatInfo.numSequence, out formatInfo.length);
                }
                else
                {
                    formatInfo.isSeparator = true;
                    formatInfo.formatString = formatString.Substring(num2, num - num2);
                }
                num2 = num;
                num++;
                list.Add(formatInfo);
                flag = flag2;
            }
            else
            {
                num++;
            }
        }
        return list;
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Xml.Dictionary, System.Xml.Xsl.Runtime.CharUtil.IsAlphaNumeric(), System.list, and System.Xml.Xsl.XsltOld.NumberAction.mapFormatToken().
Referenced by System.Xml.Xsl.XsltOld.NumberAction.Compile(), and System.Xml.Xsl.XsltOld.NumberAction.Execute().