Terraria: Terraria.GameContent.UI.Elements.UITextPanel.DrawText
DrawText()
void Terraria.GameContent.UI.Elements.UITextPanel< T >.DrawText (SpriteBatch spriteBatch) inline protected
Definition at line 115 of file UITextPanel.cs.
    {
        CalculatedStyle innerDimensions = GetInnerDimensions();
        Vector2 pos = innerDimensions.Position();
        if (_isLarge)
        {
            pos.Y -= 10f * _textScale * _textScale;
        }
        else
        {
            pos.Y -= 2f * _textScale;
        }
        pos.X += (innerDimensions.Width - _textSize.X) * TextHAlign;
        string text = Text;
        if (HideContents)
        {
            if (_asterisks == null || _asterisks.Length != text.Length)
            {
                _asterisks = new string('*', text.Length);
            }
            text = _asterisks;
        }
        if (_isLarge)
        {
            Utils.DrawBorderStringBig(spriteBatch, text, pos, _color, _textScale);
        }
        else
        {
            Utils.DrawBorderString(spriteBatch, text, pos, _color, _textScale);
        }
    }
References Terraria.GameContent.UI.Elements.UITextPanel< T >._asterisks, Terraria.GameContent.UI.Elements.UITextPanel< T >._color, Terraria.GameContent.UI.Elements.UITextPanel< T >._isLarge, Terraria.GameContent.UI.Elements.UITextPanel< T >._textScale, Terraria.GameContent.UI.Elements.UITextPanel< T >._textSize, Terraria.Utils.DrawBorderString(), Terraria.Utils.DrawBorderStringBig(), Terraria.UI.UIElement.GetInnerDimensions(), Terraria.GameContent.UI.Elements.UITextPanel< T >.HideContents, Terraria.UI.CalculatedStyle.Position(), Terraria.GameContent.UI.Elements.UITextPanel< T >.Text, and Terraria.GameContent.UI.Elements.UITextPanel< T >.TextHAlign.
Referenced by Terraria.GameContent.UI.Elements.UIResourcePackInfoButton< T >.DrawSelf(), Terraria.GameContent.UI.Elements.UISelectableTextPanel< T >.DrawSelf(), and Terraria.GameContent.UI.Elements.UITextPanel< T >.DrawSelf().