Terraria: System.Xml.Xsl.XsltOld.NumberAction.Execute
Execute()
override void System.Xml.Xsl.XsltOld.NumberAction.Execute (Processor processor, ActionFrame frame) inline package
Definition at line 382 of file NumberAction.cs.
    {
        ArrayList numberList = processor.NumberList;
        switch (frame.State)
        {
        default:
            return;
        case 0:
            numberList.Clear();
            if (_valueKey != -1)
            {
                numberList.Add(SimplifyValue(processor.Evaluate(frame, _valueKey)));
            }
            else if (_level == "any")
            {
                int num = numberAny(processor, frame);
                if (num != 0)
                {
                    numberList.Add(num);
                }
            }
            else
            {
                bool flag = _level == "multiple";
                XPathNavigator node = frame.Node;
                XPathNavigator xPathNavigator = frame.Node.Clone();
                if (xPathNavigator.NodeType == XPathNodeType.Attribute || xPathNavigator.NodeType == XPathNodeType.Namespace)
                {
                    xPathNavigator.MoveToParent();
                }
                while (moveToCount(xPathNavigator, processor, node))
                {
                    numberList.Insert(0, numberCount(xPathNavigator, processor, node));
                    if (!flag || !xPathNavigator.MoveToParent())
                    {
                        break;
                    }
                }
                if (!checkFrom(processor, xPathNavigator))
                {
                    numberList.Clear();
                }
            }
            frame.StoredOutput = Format(numberList, (_formatAvt == null) ? _formatTokens : ParseFormat(_formatAvt.Evaluate(processor, frame)), (_langAvt == null) ? _lang : _langAvt.Evaluate(processor, frame), (_letterAvt == null) ? _letter : ParseLetter(_letterAvt.Evaluate(processor, frame)), (_groupingSepAvt == null) ? _groupingSep : _groupingSepAvt.Evaluate(processor, frame), (_groupingSizeAvt == null) ? _groupingSize : _groupingSizeAvt.Evaluate(processor, frame));
            break;
        case 2:
            break;
        }
        if (!processor.TextEvent(frame.StoredOutput))
        {
            frame.State = 2;
        }
        else
        {
            frame.Finished();
        }
    }
References System.Xml.Xsl.XsltOld.NumberAction._formatAvt, System.Xml.Xsl.XsltOld.NumberAction._formatTokens, System.Xml.Xsl.XsltOld.NumberAction._groupingSep, System.Xml.Xsl.XsltOld.NumberAction._groupingSepAvt, System.Xml.Xsl.XsltOld.NumberAction._groupingSize, System.Xml.Xsl.XsltOld.NumberAction._groupingSizeAvt, System.Xml.Xsl.XsltOld.NumberAction._lang, System.Xml.Xsl.XsltOld.NumberAction._langAvt, System.Xml.Xsl.XsltOld.NumberAction._letter, System.Xml.Xsl.XsltOld.NumberAction._letterAvt, System.Xml.Xsl.XsltOld.NumberAction._level, System.Xml.Xsl.XsltOld.NumberAction._valueKey, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Xml.Xsl.XsltOld.NumberAction.checkFrom(), System.Collections.Generic.Dictionary< TKey, TValue >.Clear(), System.Xml.XPath.XPathNavigator.Clone(), System.Xml.Dictionary, System.Xml.Xsl.XsltOld.Avt.Evaluate(), System.Xml.Xsl.XsltOld.ActionFrame.Finished(), System.Format, System.Xml.Xsl.XsltOld.NumberAction.moveToCount(), System.Xml.Xsl.XsltOld.ActionFrame.Node, System.Xml.Xsl.XsltOld.NumberAction.numberAny(), System.Xml.Xsl.XsltOld.NumberAction.numberCount(), System.Xml.Xsl.XsltOld.NumberAction.ParseFormat(), System.Xml.Xsl.XsltOld.NumberAction.ParseLetter(), System.Xml.Xsl.XsltOld.NumberAction.SimplifyValue(), System.Xml.Xsl.XsltOld.ActionFrame.State, and System.Xml.Xsl.XsltOld.ActionFrame.StoredOutput.