Terraria: System.Xml.Xsl.XsltOld.NumberAction.moveToCount
moveToCount()
bool System.Xml.Xsl.XsltOld.NumberAction.moveToCount (XPathNavigator nav, Processor processor, XPathNavigator contextNode) inline private
Definition at line 323 of file NumberAction.cs.
    {
        do
        {
            if (_fromKey != -1 && processor.Matches(nav, _fromKey))
            {
                return false;
            }
            if (MatchCountKey(processor, contextNode, nav))
            {
                return true;
            }
        }
        while (nav.MoveToParent());
        return false;
    }
References System.Xml.Xsl.XsltOld.NumberAction._fromKey, System.Xml.Xsl.XsltOld.NumberAction.MatchCountKey(), and System.Xml.XPath.XPathNavigator.MoveToParent().
Referenced by System.Xml.Xsl.XsltOld.NumberAction.Execute().