Terraria: System.Xml.Xsl.XsltOld.NumberAction.Compile
Compile()
override void System.Xml.Xsl.XsltOld.NumberAction.Compile (Compiler compiler) inline package
Definition at line 227 of file NumberAction.cs.
    {
        CompileAttributes(compiler);
        CheckEmpty(compiler);
        _forwardCompatibility = compiler.ForwardCompatibility;
        _formatTokens = ParseFormat(CompiledAction.PrecalculateAvt(ref _formatAvt));
        _letter = ParseLetter(CompiledAction.PrecalculateAvt(ref _letterAvt));
        _lang = CompiledAction.PrecalculateAvt(ref _langAvt);
        _groupingSep = CompiledAction.PrecalculateAvt(ref _groupingSepAvt);
        if (_groupingSep != null && _groupingSep.Length > 1)
        {
            throw XsltException.Create(System.SR.Xslt_CharAttribute, "grouping-separator");
        }
        _groupingSize = CompiledAction.PrecalculateAvt(ref _groupingSizeAvt);
    }
References System.Xml.Xsl.XsltOld.NumberAction._formatAvt, System.Xml.Xsl.XsltOld.NumberAction._formatTokens, System.Xml.Xsl.XsltOld.NumberAction._forwardCompatibility, System.Xml.Xsl.XsltOld.NumberAction._groupingSep, System.Xml.Xsl.XsltOld.NumberAction._groupingSepAvt, System.Xml.Xsl.XsltOld.NumberAction._groupingSize, System.Xml.Xsl.XsltOld.NumberAction._groupingSizeAvt, System.Xml.Xsl.XsltOld.NumberAction._lang, System.Xml.Xsl.XsltOld.NumberAction._langAvt, System.Xml.Xsl.XsltOld.NumberAction._letter, System.Xml.Xsl.XsltOld.NumberAction._letterAvt, System.Xml.Xsl.XsltOld.CompiledAction.CheckEmpty(), System.Xml.Xsl.XsltOld.CompiledAction.CompileAttributes(), System.Xml.Xsl.XsltException.Create(), System.Xml.Xsl.XsltOld.NumberAction.ParseFormat(), System.Xml.Xsl.XsltOld.NumberAction.ParseLetter(), System.Xml.Xsl.XsltOld.CompiledAction.PrecalculateAvt(), and System.SR.Xslt_CharAttribute.