Terraria: System.Xml.Xsl.XsltOld.NumberAction.numberCount
numberCount()
int System.Xml.Xsl.XsltOld.NumberAction.numberCount (XPathNavigator nav, Processor processor, XPathNavigator contextNode) inline private
Definition at line 340 of file NumberAction.cs.
    {
        XPathNavigator xPathNavigator = nav.Clone();
        int num = 1;
        if (xPathNavigator.MoveToParent())
        {
            xPathNavigator.MoveToFirstChild();
            while (!xPathNavigator.IsSamePosition(nav))
            {
                if (MatchCountKey(processor, contextNode, xPathNavigator))
                {
                    num++;
                }
                if (!xPathNavigator.MoveToNext())
                {
                    break;
                }
            }
        }
        return num;
    }
References System.Xml.XPath.XPathNavigator.Clone(), and System.Xml.Xsl.XsltOld.NumberAction.MatchCountKey().
Referenced by System.Xml.Xsl.XsltOld.NumberAction.Execute().