Terraria: Internal.Cryptography.CngSymmetricAlgorithmCore.CreateCryptoTransform
CreateCryptoTransform() [2/3]
Internal.Cryptography.UniversalCryptoTransform Internal.Cryptography.CngSymmetricAlgorithmCore.CreateCryptoTransform (byte[] iv, bool encrypting, PaddingMode padding, CipherMode mode, int feedbackSizeInBits) inline
Definition at line 114 of file CngSymmetricAlgorithmCore.cs.
    {
        if (KeyInPlainText)
        {
            return CreateCryptoTransform(_outer.BaseKey, iv, encrypting, padding, mode, feedbackSizeInBits);
        }
        return CreatePersistedCryptoTransformCore(ProduceCngKey, iv, encrypting, padding, mode, feedbackSizeInBits);
    }
References Internal.Cryptography.CngSymmetricAlgorithmCore._outer, Internal.Cryptography.ICngSymmetricAlgorithm.BaseKey, Internal.Cryptography.CngSymmetricAlgorithmCore.CreateCryptoTransform(), Internal.Cryptography.CngSymmetricAlgorithmCore.CreatePersistedCryptoTransformCore(), Internal.Cryptography.CngSymmetricAlgorithmCore.KeyInPlainText, and Internal.Cryptography.CngSymmetricAlgorithmCore.ProduceCngKey().