Terraria: Internal.Cryptography.CngSymmetricAlgorithmCore.CngSymmetricAlgorithmCore
CngSymmetricAlgorithmCore() [2/2]
Internal.Cryptography.CngSymmetricAlgorithmCore.CngSymmetricAlgorithmCore (ICngSymmetricAlgorithm outer, string keyName, CngProvider provider, CngKeyOpenOptions openOptions) inline
Definition at line 27 of file CngSymmetricAlgorithmCore.cs.
    {
        if (keyName == null)
        {
            throw new ArgumentNullException("keyName");
        }
        if (provider == null)
        {
            throw new ArgumentNullException("provider");
        }
        _outer = outer;
        _keyName = keyName;
        _provider = provider;
        _optionOptions = openOptions;
        using CngKey cngKey = ProduceCngKey();
        CngAlgorithm algorithm = cngKey.Algorithm;
        string nCryptAlgorithmIdentifier = _outer.GetNCryptAlgorithmIdentifier();
        if (nCryptAlgorithmIdentifier != algorithm.Algorithm)
        {
            throw new CryptographicException(System.SR.Format(System.SR.Cryptography_CngKeyWrongAlgorithm, algorithm.Algorithm, nCryptAlgorithmIdentifier));
        }
        _outer.BaseKeySize = cngKey.KeySize;
    }
References Internal.Cryptography.CngSymmetricAlgorithmCore._keyName, Internal.Cryptography.CngSymmetricAlgorithmCore._optionOptions, Internal.Cryptography.CngSymmetricAlgorithmCore._outer, Internal.Cryptography.CngSymmetricAlgorithmCore._provider, System.Security.Cryptography.CngAlgorithm.Algorithm, System.SR.Cryptography_CngKeyWrongAlgorithm, System.SR.Format(), Internal.Cryptography.ICngSymmetricAlgorithm.GetNCryptAlgorithmIdentifier(), and Internal.Cryptography.CngSymmetricAlgorithmCore.ProduceCngKey().