Terraria: Internal.Cryptography.CngSymmetricAlgorithmCore.ProduceCngKey
ProduceCngKey()
CngKey Internal.Cryptography.CngSymmetricAlgorithmCore.ProduceCngKey () inline private
Definition at line 165 of file CngSymmetricAlgorithmCore.cs.
    {
        return CngKey.Open(_keyName, _provider, _optionOptions);
    }
References Internal.Cryptography.CngSymmetricAlgorithmCore._keyName, Internal.Cryptography.CngSymmetricAlgorithmCore._optionOptions, Internal.Cryptography.CngSymmetricAlgorithmCore._provider, and System.Security.Cryptography.CngKey.Open().
Referenced by Internal.Cryptography.CngSymmetricAlgorithmCore.CngSymmetricAlgorithmCore(), Internal.Cryptography.CngSymmetricAlgorithmCore.CreateCryptoTransform(), Internal.Cryptography.CngSymmetricAlgorithmCore.CreateCryptoTransform(), and Internal.Cryptography.CngSymmetricAlgorithmCore.GetKeyIfExportable().