Terraria: Internal.Cryptography.CngSymmetricAlgorithmCore.CreatePersistedCryptoTransformCore
CreatePersistedCryptoTransformCore()
Internal.Cryptography.UniversalCryptoTransform Internal.Cryptography.CngSymmetricAlgorithmCore.CreatePersistedCryptoTransformCore (Func< CngKey > cngKeyFactory, byte[] iv, bool encrypting, PaddingMode padding, CipherMode mode, int feedbackSizeInBits) inline private
Definition at line 157 of file CngSymmetricAlgorithmCore.cs.
    {
        ValidateFeedbackSize(mode, feedbackSizeInBits);
        int blockSizeInBytes = _outer.BlockSize.BitSizeToByteSize();
        Internal.Cryptography.BasicSymmetricCipher cipher = new BasicSymmetricCipherNCrypt(cngKeyFactory, mode, blockSizeInBytes, iv, encrypting, _outer.GetPaddingSize(mode, feedbackSizeInBits));
        return Internal.Cryptography.UniversalCryptoTransform.Create(padding, cipher, encrypting);
    }
References Internal.Cryptography.CngSymmetricAlgorithmCore._outer, Internal.Cryptography.ICngSymmetricAlgorithm.BlockSize, Internal.Cryptography.UniversalCryptoTransform.Create(), Internal.Cryptography.ICngSymmetricAlgorithm.GetPaddingSize(), and Internal.Cryptography.CngSymmetricAlgorithmCore.ValidateFeedbackSize().
Referenced by Internal.Cryptography.CngSymmetricAlgorithmCore.CreateCryptoTransform(), and Internal.Cryptography.CngSymmetricAlgorithmCore.CreateCryptoTransform().