Terraria: Internal.Cryptography.CngSymmetricAlgorithmCore.CreateCryptoTransform
CreateCryptoTransform() [1/3]
ICryptoTransform Internal.Cryptography.CngSymmetricAlgorithmCore.CreateCryptoTransform (bool encrypting) inline private
Definition at line 105 of file CngSymmetricAlgorithmCore.cs.
    {
        if (KeyInPlainText)
        {
            return CreateCryptoTransform(_outer.BaseKey, _outer.IV, encrypting, _outer.Padding, _outer.Mode, _outer.FeedbackSize);
        }
        return CreatePersistedCryptoTransformCore(ProduceCngKey, _outer.IV, encrypting, _outer.Padding, _outer.Mode, _outer.FeedbackSize);
    }
References Internal.Cryptography.CngSymmetricAlgorithmCore._outer, Internal.Cryptography.ICngSymmetricAlgorithm.BaseKey, Internal.Cryptography.CngSymmetricAlgorithmCore.CreateCryptoTransform(), Internal.Cryptography.CngSymmetricAlgorithmCore.CreatePersistedCryptoTransformCore(), Internal.Cryptography.ICngSymmetricAlgorithm.FeedbackSize, Internal.Cryptography.ICngSymmetricAlgorithm.IV, Internal.Cryptography.CngSymmetricAlgorithmCore.KeyInPlainText, Internal.Cryptography.ICngSymmetricAlgorithm.Mode, Internal.Cryptography.ICngSymmetricAlgorithm.Padding, and Internal.Cryptography.CngSymmetricAlgorithmCore.ProduceCngKey().
Referenced by Internal.Cryptography.CngSymmetricAlgorithmCore.CreateCryptoTransform(), Internal.Cryptography.CngSymmetricAlgorithmCore.CreateCryptoTransform(), Internal.Cryptography.CngSymmetricAlgorithmCore.CreateDecryptor(), Internal.Cryptography.CngSymmetricAlgorithmCore.CreateDecryptor(), Internal.Cryptography.CngSymmetricAlgorithmCore.CreateEncryptor(), Internal.Cryptography.CngSymmetricAlgorithmCore.CreateEncryptor(), System.Security.Cryptography.AesCng.TryDecryptCbcCore(), System.Security.Cryptography.TripleDESCng.TryDecryptCbcCore(), System.Security.Cryptography.AesCng.TryDecryptCfbCore(), System.Security.Cryptography.TripleDESCng.TryDecryptCfbCore(), System.Security.Cryptography.AesCng.TryDecryptEcbCore(), System.Security.Cryptography.TripleDESCng.TryDecryptEcbCore(), System.Security.Cryptography.AesCng.TryEncryptCbcCore(), System.Security.Cryptography.TripleDESCng.TryEncryptCbcCore(), System.Security.Cryptography.AesCng.TryEncryptCfbCore(), System.Security.Cryptography.TripleDESCng.TryEncryptCfbCore(), System.Security.Cryptography.AesCng.TryEncryptEcbCore(), and System.Security.Cryptography.TripleDESCng.TryEncryptEcbCore().