Terraria: Internal.Cryptography.CngSymmetricAlgorithmCore.CreateCryptoTransform
CreateCryptoTransform() [3/3]
Internal.Cryptography.UniversalCryptoTransform Internal.Cryptography.CngSymmetricAlgorithmCore.CreateCryptoTransform (byte[] rgbKey, byte[] rgbIV, bool encrypting, PaddingMode padding, CipherMode mode, int feedbackSizeInBits) inline private
Definition at line 123 of file CngSymmetricAlgorithmCore.cs.
    {
        if (rgbKey == null)
        {
            throw new ArgumentNullException("rgbKey");
        }
        ValidateFeedbackSize(mode, feedbackSizeInBits);
        byte[] array = rgbKey.CloneByteArray();
        long num = (long)array.Length * 8L;
        if (num > int.MaxValue || !((int)num).IsLegalSize(_outer.LegalKeySizes))
        {
            throw new ArgumentException(System.SR.Cryptography_InvalidKeySize, "rgbKey");
        }
        if (_outer.IsWeakKey(array))
        {
            throw new CryptographicException(System.SR.Cryptography_WeakKey);
        }
        if (rgbIV != null && rgbIV.Length != _outer.BlockSize.BitSizeToByteSize())
        {
            throw new ArgumentException(System.SR.Cryptography_InvalidIVSize, "rgbIV");
        }
        byte[] iv = mode.GetCipherIv(rgbIV).CloneByteArray();
        array = _outer.PreprocessKey(array);
        return CreateEphemeralCryptoTransformCore(array, iv, encrypting, padding, mode, feedbackSizeInBits);
    }
References Internal.Cryptography.CngSymmetricAlgorithmCore._outer, System.array, Internal.Cryptography.ICngSymmetricAlgorithm.BlockSize, Internal.Cryptography.CngSymmetricAlgorithmCore.CreateEphemeralCryptoTransformCore(), System.SR.Cryptography_InvalidIVSize, System.SR.Cryptography_InvalidKeySize, System.SR.Cryptography_WeakKey, Internal.Cryptography.ICngSymmetricAlgorithm.IsWeakKey(), System.L, Internal.Cryptography.ICngSymmetricAlgorithm.LegalKeySizes, Internal.Cryptography.ICngSymmetricAlgorithm.PreprocessKey(), and Internal.Cryptography.CngSymmetricAlgorithmCore.ValidateFeedbackSize().