Terraria: ItemSorting.SortCoins
SortCoins()
static void ItemSorting.SortCoins () inline static private
     {
         Item[] inventory = Main.LocalPlayer.inventory;
         bool overFlowing;
         long count = Utils.CoinsCount(out overFlowing, inventory, 58);
         int commonMaxStack = Item.CommonMaxStack;
         if (overFlowing)
         {
             return;
         }
         int[] array = Utils.CoinsSplit(count);
         int num = 0;
         for (int i = 0; i < 3; i++)
         {
             int num2 = array[i];
             while (num2 > 0)
             {
                 num2 -= 99;
                 num++;
             }
         }
         int num3 = array[3];
         while (num3 > commonMaxStack)
         {
             num3 -= commonMaxStack;
             num++;
         }
         int num4 = 0;
         for (int j = 0; j < 58; j++)
         {
             if (inventory[j].type >= 71 && inventory[j].type <= 74 && inventory[j].stack > 0)
             {
                 num4++;
             }
         }
         if (num4 < num)
         {
             return;
         }
         for (int k = 0; k < 58; k++)
         {
             if (inventory[k].type >= 71 && inventory[k].type <= 74 && inventory[k].stack > 0)
             {
                 inventory[k].TurnToAir();
             }
         }
         int num5 = 100;
         while (true)
         {
             int num6 = -1;
             for (int num7 = 3; num7 >= 0; num7--)
             {
                 if (array[num7] > 0)
                 {
                     num6 = num7;
                     break;
                 }
             }
             if (num6 == -1)
             {
                 break;
             }
             int num8 = array[num6];
             if (num6 == 3 && num8 > commonMaxStack)
             {
                 num8 = commonMaxStack;
             }
             bool flag = false;
             if (!flag)
             {
                 for (int l = 50; l < 54; l++)
                 {
                     if (inventory[l].IsAir)
                     {
                         inventory[l].SetDefaults(71 + num6);
                         inventory[l].stack = num8;
                         array[num6] -= num8;
                         flag = true;
                         break;
                     }
                 }
             }
             if (!flag)
             {
                 for (int m = 0; m < 50; m++)
                 {
                     if (inventory[m].IsAir)
                     {
                         inventory[m].SetDefaults(71 + num6);
                         inventory[m].stack = num8;
                         array[num6] -= num8;
                         flag = true;
                         break;
                     }
                 }
             }
             num5--;
             if (num5 > 0)
             {
                 continue;
             }
             for (int num9 = 3; num9 >= 0; num9--)
             {
                 if (array[num9] > 0)
                 {
                     Main.LocalPlayer.QuickSpawnItem(Main.LocalPlayer.GetItemSource_Misc(7), 71 + num9, array[num9]);
                 }
             }
             break;
         }
     }
References Utils.CoinsCount(), Utils.CoinsSplit(), Item.CommonMaxStack, Player.GetItemSource_Misc(), Player.inventory, Main.LocalPlayer, Player.QuickSpawnItem(), Item.SetDefaults(), Item.stack, and Item.TurnToAir().
Referenced by SortInventory().