Terraria: ItemSorting.RefillItemStack
RefillItemStack()
static void ItemSorting.RefillItemStack (Item[] inv, Item itemToRefill, int loopStartIndex, int loopEndIndex) inline static private
     {
         int num = itemToRefill.maxStack - itemToRefill.stack;
         if (num <= 0)
         {
             return;
         }
         for (int i = loopStartIndex; i < loopEndIndex; i++)
         {
             Item item = inv[i];
             if (item.stack >= 1 && item.type == itemToRefill.type)
             {
                 int num2 = item.stack;
                 if (num2 > num)
                 {
                     num2 = num;
                 }
                 num -= num2;
                 itemToRefill.stack += num2;
                 item.stack -= num2;
                 if (item.stack <= 0)
                 {
                     item.TurnToAir();
                 }
                 if (num <= 0)
                 {
                     break;
                 }
             }
         }
     }
References Item.maxStack, Item.stack, Item.TurnToAir(), and Item.type.
Referenced by ClearAmmoSlotSpaces(), and FillAmmoFromInventory().