Terraria: ItemSorting.FillAmmoFromInventory
FillAmmoFromInventory()
static void ItemSorting.FillAmmoFromInventory () inline static
     {
         List<int> list = new List<int>();
         List<int> list2 = new List<int>();
         Item[] inventory = Main.player[Main.myPlayer].inventory;
         for (int i = 54; i < 58; i++)
         {
             ItemSlot.SetGlow(i, 0.31f, chest: false);
             Item item = inventory[i];
             if (item.IsAir)
             {
                 list2.Add(i);
             }
             else if (item.ammo != AmmoID.None)
             {
                 if (!list.Contains(item.type))
                 {
                     list.Add(item.type);
                 }
                 RefillItemStack(inventory, inventory[i], 0, 50);
             }
         }
         if (list2.Count < 1)
         {
             return;
         }
         for (int j = 0; j < 50; j++)
         {
             Item item2 = inventory[j];
             if (item2.stack >= 1 && item2.CanFillEmptyAmmoSlot() && list.Contains(item2.type))
             {
                 int num = list2[0];
                 list2.Remove(num);
                 Utils.Swap(ref inventory[j], ref inventory[num]);
                 RefillItemStack(inventory, inventory[num], 0, 50);
                 if (list2.Count == 0)
                 {
                     break;
                 }
             }
         }
         if (list2.Count < 1)
         {
             return;
         }
         for (int k = 0; k < 50; k++)
         {
             Item item3 = inventory[k];
             if (item3.stack >= 1 && item3.CanFillEmptyAmmoSlot() && item3.FitsAmmoSlot())
             {
                 int num2 = list2[0];
                 list2.Remove(num2);
                 Utils.Swap(ref inventory[k], ref inventory[num2]);
                 RefillItemStack(inventory, inventory[num2], 0, 50);
                 if (list2.Count == 0)
                 {
                     break;
                 }
             }
         }
     }
References Item.ammo, Item.CanFillEmptyAmmoSlot(), Item.FitsAmmoSlot(), Player.inventory, Item.IsAir, Main.myPlayer, AmmoID.None, Main.player, RefillItemStack(), ItemSlot.SetGlow(), Item.stack, and Item.type.
Referenced by SortAmmo().