Terraria: ItemSorting.SortChest
SortChest()
static void ItemSorting.SortChest () inline static
     {
         int chest = Main.player[Main.myPlayer].chest;
         if (chest == -1)
         {
             return;
         }
         Item[] item = Main.player[Main.myPlayer].bank.item;
         if (chest == -3)
         {
             item = Main.player[Main.myPlayer].bank2.item;
         }
         if (chest == -4)
         {
             item = Main.player[Main.myPlayer].bank3.item;
         }
         if (chest == -5)
         {
             item = Main.player[Main.myPlayer].bank4.item;
         }
         if (chest > -1)
         {
             item = Main.chest[chest].item;
         }
         Tuple<int, int, int>[] array = new Tuple<int, int, int>[40];
         for (int i = 0; i < 40; i++)
         {
             array[i] = Tuple.Create(item[i].netID, item[i].stack, (int)item[i].prefix);
         }
         Sort(item);
         Tuple<int, int, int>[] array2 = new Tuple<int, int, int>[40];
         for (int j = 0; j < 40; j++)
         {
             array2[j] = Tuple.Create(item[j].netID, item[j].stack, (int)item[j].prefix);
         }
         if (Main.netMode != 1 || Main.player[Main.myPlayer].chest <= -1)
         {
             return;
         }
         for (int k = 0; k < 40; k++)
         {
             if (array2[k] != array[k])
             {
                 NetMessage.SendData(32, -1, -1, null, Main.player[Main.myPlayer].chest, k);
             }
         }
     }
References Player.bank, Player.bank2, Player.bank3, Player.bank4, Main.chest, Player.chest, Chest.item, Main.myPlayer, Main.netMode, Main.player, NetMessage.SendData(), and Sort().
Referenced by ChestUI.DrawButton().