Terraria: System.Text.Json.Serialization.Converters.KeyValuePairConverter.TryLookupConstructorParameter
TryLookupConstructorParameter()
override bool System.Text.Json.Serialization.Converters.KeyValuePairConverter< TKey, TValue >.TryLookupConstructorParameter (ref ReadStack state, ref Utf8JsonReader reader, JsonSerializerOptions options, out JsonParameterInfo jsonParameterInfo) inline protected
Definition at line 35 of file KeyValuePairConverter.cs.
    {
        JsonTypeInfo jsonTypeInfo = state.Current.JsonTypeInfo;
        ArgumentState ctorArgumentState = state.Current.CtorArgumentState;
        bool propertyNameCaseInsensitive = options.PropertyNameCaseInsensitive;
        string @string = reader.GetString();
        state.Current.JsonPropertyNameAsString = @string;
        if (!ctorArgumentState.FoundKey && FoundKeyProperty(@string, propertyNameCaseInsensitive))
        {
            jsonParameterInfo = jsonTypeInfo.ParameterCache[_keyName];
            ctorArgumentState.FoundKey = true;
        }
        else
        {
            if (ctorArgumentState.FoundValue || !FoundValueProperty(@string, propertyNameCaseInsensitive))
            {
                ThrowHelper.ThrowJsonException();
                jsonParameterInfo = null;
                return false;
            }
            jsonParameterInfo = jsonTypeInfo.ParameterCache[_valueName];
            ctorArgumentState.FoundValue = true;
        }
        ctorArgumentState.ParameterIndex++;
        ctorArgumentState.JsonParameterInfo = jsonParameterInfo;
        state.Current.NumberHandling = jsonParameterInfo.NumberHandling;
        return true;
    }
References System.Text.Json.Serialization.Converters.KeyValuePairConverter< TKey, TValue >._keyName, System.Text.Json.Serialization.Converters.KeyValuePairConverter< TKey, TValue >._valueName, System.Text.Json.Dictionary, System.Text.Json.Serialization.Converters.KeyValuePairConverter< TKey, TValue >.FoundKeyProperty(), System.Text.Json.Serialization.Converters.KeyValuePairConverter< TKey, TValue >.FoundValueProperty(), System.options, System.state, and System.Text.Json.ThrowHelper.ThrowJsonException().