Terraria: System.Xml.XmlCanonicalWriter.ResolvePrefix
ResolvePrefix() [1/2]
void System.Xml.XmlCanonicalWriter.ResolvePrefix (int prefixOffset, int prefixLength, out int nsOffset, out int nsLength) inline private
Definition at line 960 of file XmlCanonicalWriter.cs.
    {
        int xmlnsAttributeCount = _scopes[_depth - 1].xmlnsAttributeCount;
        int num = _xmlnsAttributeCount - 1;
        while (!Equals(_elementBuffer, prefixOffset, prefixLength, _xmlnsBuffer, _xmlnsAttributes[num].prefixOffset, _xmlnsAttributes[num].prefixLength))
        {
            num--;
        }
        nsOffset = _xmlnsAttributes[num].nsOffset;
        nsLength = _xmlnsAttributes[num].nsLength;
        if (num < xmlnsAttributeCount)
        {
            if (!_xmlnsAttributes[num].referred)
            {
                XmlnsAttribute xmlnsAttribute = _xmlnsAttributes[num];
                xmlnsAttribute.referred = true;
                AddXmlnsAttribute(ref xmlnsAttribute);
            }
        }
        else
        {
            _xmlnsAttributes[num].referred = true;
        }
    }
References System.Xml.XmlCanonicalWriter._depth, System.Xml.XmlCanonicalWriter._elementBuffer, System.Xml.XmlCanonicalWriter._scopes, System.Xml.XmlCanonicalWriter._xmlnsAttributeCount, System.Xml.XmlCanonicalWriter._xmlnsAttributes, System.Xml.XmlCanonicalWriter._xmlnsBuffer, System.Xml.XmlCanonicalWriter.AddXmlnsAttribute(), System.Xml.Dictionary, System.Xml.XmlCanonicalWriter.Equals(), System.Xml.XmlCanonicalWriter.XmlnsAttribute.nsLength, System.Xml.XmlCanonicalWriter.XmlnsAttribute.nsOffset, System.Xml.XmlCanonicalWriter.XmlnsAttribute.referred, and System.Xml.XmlCanonicalWriter.Scope.xmlnsAttributeCount.
Referenced by System.Xml.XmlCanonicalWriter.ResolvePrefix(), and System.Xml.XmlCanonicalWriter.ResolvePrefixes().