Terraria: System.Xml.XmlCanonicalWriter.StartElement
StartElement()
void System.Xml.XmlCanonicalWriter.StartElement () inline private
Definition at line 269 of file XmlCanonicalWriter.cs.
    {
        if (_scopes == null)
        {
            _scopes = new Scope[4];
        }
        else if (_depth == _scopes.Length)
        {
            Scope[] array = new Scope[_depth * 2];
            Array.Copy(_scopes, array, _depth);
            _scopes = array;
        }
        _scopes[_depth].xmlnsAttributeCount = _xmlnsAttributeCount;
        _scopes[_depth].xmlnsOffset = _xmlnsOffset;
        _depth++;
        _inStartElement = true;
        _attributeCount = 0;
        _elementStream.Position = 0L;
    }
References System.Xml.XmlCanonicalWriter._attributeCount, System.Xml.XmlCanonicalWriter._depth, System.Xml.XmlCanonicalWriter._inStartElement, System.Xml.XmlCanonicalWriter._scopes, System.Xml.XmlCanonicalWriter._xmlnsAttributeCount, System.Xml.XmlCanonicalWriter._xmlnsOffset, System.array, System.Array.Copy(), System.Xml.Dictionary, System.Xml.L, System.Xml.XmlCanonicalWriter.Scope.xmlnsAttributeCount, and System.Xml.XmlCanonicalWriter.Scope.xmlnsOffset.
Referenced by System.Xml.XmlCanonicalWriter.WriteStartElement(), and System.Xml.XmlCanonicalWriter.WriteStartElement().