Terraria: System.Xml.XmlCanonicalWriter.ThrowIfClosed
ThrowIfClosed()
void System.Xml.XmlCanonicalWriter.ThrowIfClosed () inline private
Definition at line 850 of file XmlCanonicalWriter.cs.
    {
        if (_writer == null)
        {
            ThrowClosed();
        }
    }
References System.Xml.XmlCanonicalWriter._writer, and System.Xml.XmlCanonicalWriter.ThrowClosed().
Referenced by System.Xml.XmlCanonicalWriter.Flush(), System.Xml.XmlCanonicalWriter.WriteCharEntity(), System.Xml.XmlCanonicalWriter.WriteComment(), System.Xml.XmlCanonicalWriter.WriteEndAttribute(), System.Xml.XmlCanonicalWriter.WriteEndElement(), System.Xml.XmlCanonicalWriter.WriteEndStartElement(), System.Xml.XmlCanonicalWriter.WriteEscapedText(), System.Xml.XmlCanonicalWriter.WriteEscapedText(), System.Xml.XmlCanonicalWriter.WriteEscapedText(), System.Xml.XmlCanonicalWriter.WriteStartAttribute(), System.Xml.XmlCanonicalWriter.WriteStartAttribute(), System.Xml.XmlCanonicalWriter.WriteStartElement(), System.Xml.XmlCanonicalWriter.WriteStartElement(), System.Xml.XmlCanonicalWriter.WriteText(), System.Xml.XmlCanonicalWriter.WriteText(), System.Xml.XmlCanonicalWriter.WriteText(), System.Xml.XmlCanonicalWriter.WriteXmlnsAttribute(), and System.Xml.XmlCanonicalWriter.WriteXmlnsAttribute().