Terraria: System.Xml.XmlCanonicalWriter.WriteText
WriteText() [1/4]
void System.Xml.XmlCanonicalWriter.WriteText (byte[] chars, int offset, int count) inline
Definition at line 765 of file XmlCanonicalWriter.cs.
    {
        ThrowIfClosed();
        if (chars == null)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new ArgumentNullException("chars"));
        }
        if (offset < 0)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new ArgumentOutOfRangeException("offset", System.SR.ValueMustBeNonNegative));
        }
        if (offset > chars.Length)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new ArgumentOutOfRangeException("offset", System.SR.Format(System.SR.OffsetExceedsBufferSize, chars.Length)));
        }
        if (count < 0)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new ArgumentOutOfRangeException("count", System.SR.ValueMustBeNonNegative));
        }
        if (count > chars.Length - offset)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new ArgumentOutOfRangeException("count", System.SR.Format(System.SR.SizeExceedsRemainingBufferSpace, chars.Length - offset)));
        }
        if (_inStartElement)
        {
            _elementWriter.WriteText(chars, offset, count);
        }
        else
        {
            _writer.WriteText(chars, offset, count);
        }
    }
References System.Xml.XmlCanonicalWriter._elementWriter, System.Xml.XmlCanonicalWriter._inStartElement, System.Xml.XmlCanonicalWriter._writer, System.chars, System.count, System.SR.Format(), System.offset, System.SR.OffsetExceedsBufferSize, System.SR.SizeExceedsRemainingBufferSpace, System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperError(), System.Xml.XmlCanonicalWriter.ThrowIfClosed(), System.SR.ValueMustBeNonNegative, and System.Xml.XmlUTF8NodeWriter.WriteText().