Terraria: System.Xml.XmlCanonicalWriter.IsInclusivePrefix
IsInclusivePrefix()
bool System.Xml.XmlCanonicalWriter.IsInclusivePrefix (ref XmlnsAttribute xmlnsAttribute) inline private
Definition at line 392 of file XmlCanonicalWriter.cs.
    {
        for (int i = 0; i < _inclusivePrefixes.Length; i++)
        {
            if (_inclusivePrefixes[i].Length == xmlnsAttribute.prefixLength && string.Equals(Encoding.UTF8.GetString(_xmlnsBuffer, xmlnsAttribute.prefixOffset, xmlnsAttribute.prefixLength), _inclusivePrefixes[i], StringComparison.Ordinal))
            {
                return true;
            }
        }
        return false;
    }
References System.Xml.XmlCanonicalWriter._inclusivePrefixes, System.Xml.XmlCanonicalWriter._xmlnsBuffer, System.Xml.Dictionary, and System.Text.Encoding.UTF8.
Referenced by System.Xml.XmlCanonicalWriter.AddXmlnsAttribute(), System.Xml.XmlCanonicalWriter.WriteStartElement(), and System.Xml.XmlCanonicalWriter.WriteStartElement().