Terraria: System.Xml.XmlCanonicalWriter.WriteStartElement
WriteStartElement() [1/2]
void System.Xml.XmlCanonicalWriter.WriteStartElement (byte[] prefixBuffer, int prefixOffset, int prefixLength, byte[] localNameBuffer, int localNameOffset, int localNameLength) inline
Definition at line 328 of file XmlCanonicalWriter.cs.
    {
        if (prefixBuffer == null)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new ArgumentNullException("prefixBuffer"));
        }
        if (prefixOffset < 0)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new ArgumentOutOfRangeException("prefixOffset", System.SR.ValueMustBeNonNegative));
        }
        if (prefixOffset > prefixBuffer.Length)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new ArgumentOutOfRangeException("prefixOffset", System.SR.Format(System.SR.OffsetExceedsBufferSize, prefixBuffer.Length)));
        }
        if (prefixLength < 0)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new ArgumentOutOfRangeException("prefixLength", System.SR.ValueMustBeNonNegative));
        }
        if (prefixLength > prefixBuffer.Length - prefixOffset)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new ArgumentOutOfRangeException("prefixLength", System.SR.Format(System.SR.SizeExceedsRemainingBufferSpace, prefixBuffer.Length - prefixOffset)));
        }
        if (localNameBuffer == null)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new ArgumentNullException("localNameBuffer"));
        }
        if (localNameOffset < 0)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new ArgumentOutOfRangeException("localNameOffset", System.SR.ValueMustBeNonNegative));
        }
        if (localNameOffset > localNameBuffer.Length)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new ArgumentOutOfRangeException("localNameOffset", System.SR.Format(System.SR.OffsetExceedsBufferSize, localNameBuffer.Length)));
        }
        if (localNameLength < 0)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new ArgumentOutOfRangeException("localNameLength", System.SR.ValueMustBeNonNegative));
        }
        if (localNameLength > localNameBuffer.Length - localNameOffset)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new ArgumentOutOfRangeException("localNameLength", System.SR.Format(System.SR.SizeExceedsRemainingBufferSpace, localNameBuffer.Length - localNameOffset)));
        }
        ThrowIfClosed();
        bool flag = _depth == 0;
        StartElement();
        _element.prefixOffset = _elementWriter.Position + 1;
        _element.prefixLength = prefixLength;
        _element.localNameOffset = _element.prefixOffset + prefixLength + ((prefixLength != 0) ? 1 : 0);
        _element.localNameLength = localNameLength;
        _elementWriter.WriteStartElement(prefixBuffer, prefixOffset, prefixLength, localNameBuffer, localNameOffset, localNameLength);
        if (!flag || _inclusivePrefixes == null)
        {
            return;
        }
        for (int i = 0; i < _scopes[0].xmlnsAttributeCount; i++)
        {
            if (IsInclusivePrefix(ref _xmlnsAttributes[i]))
            {
                XmlnsAttribute xmlnsAttribute = _xmlnsAttributes[i];
                AddXmlnsAttribute(ref xmlnsAttribute);
            }
        }
    }
References System.Xml.XmlCanonicalWriter._depth, System.Xml.XmlCanonicalWriter._elementWriter, System.Xml.XmlCanonicalWriter._inclusivePrefixes, System.Xml.XmlCanonicalWriter._scopes, System.Xml.XmlCanonicalWriter._xmlnsAttributes, System.Xml.XmlCanonicalWriter.AddXmlnsAttribute(), System.Xml.Dictionary, System.SR.Format(), System.Xml.XmlCanonicalWriter.IsInclusivePrefix(), System.SR.OffsetExceedsBufferSize, System.SR.SizeExceedsRemainingBufferSpace, System.Xml.XmlCanonicalWriter.StartElement(), System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperError(), System.Xml.XmlCanonicalWriter.ThrowIfClosed(), System.SR.ValueMustBeNonNegative, System.Xml.XmlUTF8NodeWriter.WriteStartElement(), and System.Xml.XmlCanonicalWriter.Scope.xmlnsAttributeCount.