Terraria: System.Xml.XmlCanonicalWriter.SortAttributes
SortAttributes()
void System.Xml.XmlCanonicalWriter.SortAttributes () inline private
Definition at line 871 of file XmlCanonicalWriter.cs.
    {
        if (_attributeCount < 16)
        {
            for (int i = 0; i < _attributeCount - 1; i++)
            {
                int num = i;
                for (int j = i + 1; j < _attributeCount; j++)
                {
                    if (Compare(ref _attributes[j], ref _attributes[num]) < 0)
                    {
                        num = j;
                    }
                }
                if (num != i)
                {
                    Attribute attribute = _attributes[i];
                    _attributes[i] = _attributes[num];
                    _attributes[num] = attribute;
                }
            }
        }
        else
        {
            new AttributeSorter(this).Sort();
        }
    }
References System.Xml.XmlCanonicalWriter._attributeCount, System.Xml.XmlCanonicalWriter._attributes, System.Xml.XmlCanonicalWriter.Compare(), System.Xml.Dictionary, and System.Xml.XmlCanonicalWriter.AttributeSorter.Sort().
Referenced by System.Xml.XmlCanonicalWriter.WriteEndStartElement().