Terraria: System.Xml.XmlCanonicalWriter.WriteStartAttribute
WriteStartAttribute() [1/2]
void System.Xml.XmlCanonicalWriter.WriteStartAttribute (byte[] prefixBuffer, int prefixOffset, int prefixLength, byte[] localNameBuffer, int localNameOffset, int localNameLength) inline
Definition at line 604 of file XmlCanonicalWriter.cs.
    {
        if (prefixBuffer == null)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new ArgumentNullException("prefixBuffer"));
        }
        if (prefixOffset < 0)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new ArgumentOutOfRangeException("prefixOffset", System.SR.ValueMustBeNonNegative));
        }
        if (prefixOffset > prefixBuffer.Length)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new ArgumentOutOfRangeException("prefixOffset", System.SR.Format(System.SR.OffsetExceedsBufferSize, prefixBuffer.Length)));
        }
        if (prefixLength < 0)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new ArgumentOutOfRangeException("prefixLength", System.SR.ValueMustBeNonNegative));
        }
        if (prefixLength > prefixBuffer.Length - prefixOffset)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new ArgumentOutOfRangeException("prefixLength", System.SR.Format(System.SR.SizeExceedsRemainingBufferSpace, prefixBuffer.Length - prefixOffset)));
        }
        if (localNameBuffer == null)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new ArgumentNullException("localNameBuffer"));
        }
        if (localNameOffset < 0)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new ArgumentOutOfRangeException("localNameOffset", System.SR.ValueMustBeNonNegative));
        }
        if (localNameOffset > localNameBuffer.Length)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new ArgumentOutOfRangeException("localNameOffset", System.SR.Format(System.SR.OffsetExceedsBufferSize, localNameBuffer.Length)));
        }
        if (localNameLength < 0)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new ArgumentOutOfRangeException("localNameLength", System.SR.ValueMustBeNonNegative));
        }
        if (localNameLength > localNameBuffer.Length - localNameOffset)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new ArgumentOutOfRangeException("localNameLength", System.SR.Format(System.SR.SizeExceedsRemainingBufferSpace, localNameBuffer.Length - localNameOffset)));
        }
        ThrowIfClosed();
        _attribute.offset = _elementWriter.Position;
        _attribute.length = 0;
        _attribute.prefixOffset = _attribute.offset + 1;
        _attribute.prefixLength = prefixLength;
        _attribute.localNameOffset = _attribute.prefixOffset + prefixLength + ((prefixLength != 0) ? 1 : 0);
        _attribute.localNameLength = localNameLength;
        _attribute.nsOffset = 0;
        _attribute.nsLength = 0;
        _elementWriter.WriteStartAttribute(prefixBuffer, prefixOffset, prefixLength, localNameBuffer, localNameOffset, localNameLength);
    }
References System.Xml.XmlCanonicalWriter._elementWriter, System.Xml.Dictionary, System.SR.Format(), System.SR.OffsetExceedsBufferSize, System.Xml.XmlStreamNodeWriter.Position, System.SR.SizeExceedsRemainingBufferSpace, System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperError(), System.Xml.XmlCanonicalWriter.ThrowIfClosed(), System.SR.ValueMustBeNonNegative, and System.Xml.XmlUTF8NodeWriter.WriteStartAttribute().