Terraria: System.Xml.XmlCanonicalWriter.WriteXmlnsAttribute
WriteXmlnsAttribute() [3/3]
void System.Xml.XmlCanonicalWriter.WriteXmlnsAttribute (string prefix, string ns) inline
Definition at line 488 of file XmlCanonicalWriter.cs.
    {
        if (prefix == null)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperArgumentNull("prefix");
        }
        if (ns == null)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperArgumentNull("ns");
        }
        ThrowIfClosed();
        if (prefix.Length > int.MaxValue - ns.Length)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new ArgumentOutOfRangeException("ns", System.SR.Format(System.SR.CombinedPrefixNSLength, 715827882)));
        }
        int num = prefix.Length + ns.Length;
        if (num > 715827882)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new ArgumentOutOfRangeException("ns", System.SR.Format(System.SR.CombinedPrefixNSLength, 715827882)));
        }
        EnsureXmlnsBuffer(num * 3);
        Unsafe.SkipInit(out XmlnsAttribute xmlnsAttribute);
        xmlnsAttribute.prefixOffset = _xmlnsOffset;
        xmlnsAttribute.prefixLength = Encoding.UTF8.GetBytes(prefix, 0, prefix.Length, _xmlnsBuffer, _xmlnsOffset);
        _xmlnsOffset += xmlnsAttribute.prefixLength;
        xmlnsAttribute.nsOffset = _xmlnsOffset;
        xmlnsAttribute.nsLength = Encoding.UTF8.GetBytes(ns, 0, ns.Length, _xmlnsBuffer, _xmlnsOffset);
        _xmlnsOffset += xmlnsAttribute.nsLength;
        xmlnsAttribute.referred = false;
        AddXmlnsAttribute(ref xmlnsAttribute);
    }
References System.Xml.XmlCanonicalWriter._xmlnsBuffer, System.Xml.XmlCanonicalWriter._xmlnsOffset, System.Xml.XmlCanonicalWriter.AddXmlnsAttribute(), System.SR.CombinedPrefixNSLength, System.Xml.Dictionary, System.Xml.XmlCanonicalWriter.EnsureXmlnsBuffer(), System.SR.Format(), System.prefix, System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperArgumentNull(), System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperError(), System.Xml.XmlCanonicalWriter.ThrowIfClosed(), and System.Text.Encoding.UTF8.
Referenced by System.Xml.XmlCanonicalWriter.SetOutput(), System.Xml.XmlCanonicalWriter.WriteEndStartElement(), System.Xml.XmlSigningNodeWriter.WriteXmlnsAttribute(), System.Xml.XmlSigningNodeWriter.WriteXmlnsAttribute(), and System.Xml.XmlSigningNodeWriter.WriteXmlnsAttribute().