Terraria: System.Xml.XmlCanonicalWriter.WriteEndElement
WriteEndElement()
void System.Xml.XmlCanonicalWriter.WriteEndElement (string prefix, string localName) inline
Definition at line 457 of file XmlCanonicalWriter.cs.
    {
        if (prefix == null)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperArgumentNull("prefix");
        }
        if (localName == null)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperArgumentNull("localName");
        }
        ThrowIfClosed();
        _writer.WriteEndElement(prefix, localName);
        EndElement();
    }
References System.Xml.XmlCanonicalWriter._writer, System.Xml.XmlCanonicalWriter.EndElement(), System.prefix, System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperArgumentNull(), System.Xml.XmlCanonicalWriter.ThrowIfClosed(), and System.Xml.XmlUTF8NodeWriter.WriteEndElement().
Referenced by System.Xml.XmlSigningNodeWriter.WriteEndElement().