Terraria: System.Xml.XmlCanonicalWriter.AddXmlnsAttribute
AddXmlnsAttribute()
void System.Xml.XmlCanonicalWriter.AddXmlnsAttribute (ref XmlnsAttribute xmlnsAttribute) inline private
Definition at line 916 of file XmlCanonicalWriter.cs.
    {
        if (_xmlnsAttributes == null)
        {
            _xmlnsAttributes = new XmlnsAttribute[4];
        }
        else if (_xmlnsAttributes.Length == _xmlnsAttributeCount)
        {
            XmlnsAttribute[] array = new XmlnsAttribute[_xmlnsAttributeCount * 2];
            Array.Copy(_xmlnsAttributes, array, _xmlnsAttributeCount);
            _xmlnsAttributes = array;
        }
        if (_depth > 0 && _inclusivePrefixes != null && IsInclusivePrefix(ref xmlnsAttribute))
        {
            xmlnsAttribute.referred = true;
        }
        if (_depth == 0)
        {
            _xmlnsAttributes[_xmlnsAttributeCount++] = xmlnsAttribute;
            return;
        }
        int i = _scopes[_depth - 1].xmlnsAttributeCount;
        bool flag = true;
        for (; i < _xmlnsAttributeCount; i++)
        {
            int num = Compare(ref xmlnsAttribute, ref _xmlnsAttributes[i]);
            if (num <= 0)
            {
                if (num == 0)
                {
                    _xmlnsAttributes[i] = xmlnsAttribute;
                    flag = false;
                }
                break;
            }
        }
        if (flag)
        {
            Array.Copy(_xmlnsAttributes, i, _xmlnsAttributes, i + 1, _xmlnsAttributeCount - i);
            _xmlnsAttributes[i] = xmlnsAttribute;
            _xmlnsAttributeCount++;
        }
    }
References System.Xml.XmlCanonicalWriter._depth, System.Xml.XmlCanonicalWriter._inclusivePrefixes, System.Xml.XmlCanonicalWriter._scopes, System.Xml.XmlCanonicalWriter._xmlnsAttributeCount, System.Xml.XmlCanonicalWriter._xmlnsAttributes, System.array, System.Xml.XmlCanonicalWriter.Compare(), System.Array.Copy(), System.Xml.Dictionary, System.Xml.XmlCanonicalWriter.IsInclusivePrefix(), and System.Xml.XmlCanonicalWriter.Scope.xmlnsAttributeCount.
Referenced by System.Xml.XmlCanonicalWriter.ResolvePrefix(), System.Xml.XmlCanonicalWriter.WriteStartElement(), System.Xml.XmlCanonicalWriter.WriteStartElement(), System.Xml.XmlCanonicalWriter.WriteXmlnsAttribute(), and System.Xml.XmlCanonicalWriter.WriteXmlnsAttribute().