Terraria: System.Xml.XmlCanonicalWriter.WriteStartAttribute
WriteStartAttribute() [2/2]
void System.Xml.XmlCanonicalWriter.WriteStartAttribute (string prefix, string localName) inline
Definition at line 582 of file XmlCanonicalWriter.cs.
    {
        if (prefix == null)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperArgumentNull("prefix");
        }
        if (localName == null)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperArgumentNull("localName");
        }
        ThrowIfClosed();
        _attribute.offset = _elementWriter.Position;
        _attribute.length = 0;
        _attribute.prefixOffset = _attribute.offset + 1;
        _attribute.prefixLength = Encoding.UTF8.GetByteCount(prefix);
        _attribute.localNameOffset = _attribute.prefixOffset + _attribute.prefixLength + ((_attribute.prefixLength != 0) ? 1 : 0);
        _attribute.localNameLength = Encoding.UTF8.GetByteCount(localName);
        _attribute.nsOffset = 0;
        _attribute.nsLength = 0;
        _elementWriter.WriteStartAttribute(prefix, localName);
    }
References System.Xml.XmlCanonicalWriter._elementWriter, System.Xml.Dictionary, System.Xml.XmlStreamNodeWriter.Position, System.prefix, System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperArgumentNull(), System.Xml.XmlCanonicalWriter.ThrowIfClosed(), System.Text.Encoding.UTF8, and System.Xml.XmlUTF8NodeWriter.WriteStartAttribute().
Referenced by System.Xml.XmlSigningNodeWriter.WriteStartAttribute(), System.Xml.XmlSigningNodeWriter.WriteStartAttribute(), and System.Xml.XmlSigningNodeWriter.WriteStartAttribute().