Terraria: System.Xml.XmlCanonicalWriter.WriteEndStartElement
WriteEndStartElement()
void System.Xml.XmlCanonicalWriter.WriteEndStartElement (bool isEmpty) inline
Definition at line 404 of file XmlCanonicalWriter.cs.
    {
        ThrowIfClosed();
        _elementWriter.Flush();
        _elementBuffer = _elementStream.GetBuffer();
        _inStartElement = false;
        ResolvePrefixes();
        _writer.WriteStartElement(_elementBuffer, _element.prefixOffset, _element.prefixLength, _elementBuffer, _element.localNameOffset, _element.localNameLength);
        for (int i = _scopes[_depth - 1].xmlnsAttributeCount; i < _xmlnsAttributeCount; i++)
        {
            int num = i - 1;
            bool flag = false;
            while (num >= 0)
            {
                if (Equals(_xmlnsBuffer, _xmlnsAttributes[i].prefixOffset, _xmlnsAttributes[i].prefixLength, _xmlnsBuffer, _xmlnsAttributes[num].prefixOffset, _xmlnsAttributes[num].prefixLength))
                {
                    if (!Equals(_xmlnsBuffer, _xmlnsAttributes[i].nsOffset, _xmlnsAttributes[i].nsLength, _xmlnsBuffer, _xmlnsAttributes[num].nsOffset, _xmlnsAttributes[num].nsLength))
                    {
                        break;
                    }
                    if (_xmlnsAttributes[num].referred)
                    {
                        flag = true;
                        break;
                    }
                }
                num--;
            }
            if (!flag)
            {
                WriteXmlnsAttribute(ref _xmlnsAttributes[i]);
            }
        }
        if (_attributeCount > 0)
        {
            if (_attributeCount > 1)
            {
                SortAttributes();
            }
            for (int j = 0; j < _attributeCount; j++)
            {
                _writer.WriteText(_elementBuffer, _attributes[j].offset, _attributes[j].length);
            }
        }
        _writer.WriteEndStartElement(isEmpty: false);
        if (isEmpty)
        {
            _writer.WriteEndElement(_elementBuffer, _element.prefixOffset, _element.prefixLength, _elementBuffer, _element.localNameOffset, _element.localNameLength);
            EndElement();
        }
        _elementBuffer = null;
    }
References System.Xml.XmlCanonicalWriter._attributeCount, System.Xml.XmlCanonicalWriter._attributes, System.Xml.XmlCanonicalWriter._depth, System.Xml.XmlCanonicalWriter._element, System.Xml.XmlCanonicalWriter._elementBuffer, System.Xml.XmlCanonicalWriter._elementStream, System.Xml.XmlCanonicalWriter._elementWriter, System.Xml.XmlCanonicalWriter._inStartElement, System.Xml.XmlCanonicalWriter._scopes, System.Xml.XmlCanonicalWriter._writer, System.Xml.XmlCanonicalWriter._xmlnsAttributeCount, System.Xml.XmlCanonicalWriter._xmlnsAttributes, System.Xml.XmlCanonicalWriter._xmlnsBuffer, System.Xml.Dictionary, System.Xml.XmlCanonicalWriter.EndElement(), System.Xml.XmlCanonicalWriter.Equals(), System.Xml.XmlStreamNodeWriter.Flush(), System.IO.MemoryStream.GetBuffer(), System.length, System.Xml.XmlCanonicalWriter.Element.localNameLength, System.Xml.XmlCanonicalWriter.Element.localNameOffset, System.offset, System.Xml.XmlCanonicalWriter.Element.prefixLength, System.Xml.XmlCanonicalWriter.Element.prefixOffset, System.Xml.XmlCanonicalWriter.ResolvePrefixes(), System.Xml.XmlCanonicalWriter.SortAttributes(), System.Xml.XmlCanonicalWriter.ThrowIfClosed(), System.Xml.XmlUTF8NodeWriter.WriteEndElement(), System.Xml.XmlUTF8NodeWriter.WriteEndStartElement(), System.Xml.XmlUTF8NodeWriter.WriteStartElement(), System.Xml.XmlUTF8NodeWriter.WriteText(), and System.Xml.XmlCanonicalWriter.WriteXmlnsAttribute().
Referenced by System.Xml.XmlSigningNodeWriter.WriteEndStartElement().