Terraria: System.Xml.XmlCanonicalWriter.EnsureXmlnsBuffer
EnsureXmlnsBuffer()
void System.Xml.XmlCanonicalWriter.EnsureXmlnsBuffer (int byteCount) inline private
Definition at line 473 of file XmlCanonicalWriter.cs.
    {
        if (_xmlnsBuffer == null)
        {
            _xmlnsBuffer = new byte[Math.Max(byteCount, 128)];
        }
        else if (_xmlnsOffset + byteCount > _xmlnsBuffer.Length)
        {
            byte[] array = new byte[Math.Max(_xmlnsOffset + byteCount, _xmlnsBuffer.Length * 2)];
            Buffer.BlockCopy(_xmlnsBuffer, 0, array, 0, _xmlnsOffset);
            _xmlnsBuffer = array;
        }
    }
References System.Xml.XmlCanonicalWriter._xmlnsBuffer, System.Xml.XmlCanonicalWriter._xmlnsOffset, System.array, System.Buffer.BlockCopy(), System.byteCount, and System.Math.Max().
Referenced by System.Xml.XmlCanonicalWriter.WriteXmlnsAttribute(), and System.Xml.XmlCanonicalWriter.WriteXmlnsAttribute().