Terraria: System.Xml.XmlCanonicalWriter.WriteStartElement
WriteStartElement() [2/2]
void System.Xml.XmlCanonicalWriter.WriteStartElement (string prefix, string localName) inline
Definition at line 296 of file XmlCanonicalWriter.cs.
    {
        if (prefix == null)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperArgumentNull("prefix");
        }
        if (localName == null)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperArgumentNull("localName");
        }
        ThrowIfClosed();
        bool flag = _depth == 0;
        StartElement();
        _element.prefixOffset = _elementWriter.Position + 1;
        _element.prefixLength = Encoding.UTF8.GetByteCount(prefix);
        _element.localNameOffset = _element.prefixOffset + _element.prefixLength + ((_element.prefixLength != 0) ? 1 : 0);
        _element.localNameLength = Encoding.UTF8.GetByteCount(localName);
        _elementWriter.WriteStartElement(prefix, localName);
        if (!flag || _inclusivePrefixes == null)
        {
            return;
        }
        for (int i = 0; i < _scopes[0].xmlnsAttributeCount; i++)
        {
            if (IsInclusivePrefix(ref _xmlnsAttributes[i]))
            {
                XmlnsAttribute xmlnsAttribute = _xmlnsAttributes[i];
                AddXmlnsAttribute(ref xmlnsAttribute);
            }
        }
    }
References System.Xml.XmlCanonicalWriter._depth, System.Xml.XmlCanonicalWriter._elementWriter, System.Xml.XmlCanonicalWriter._inclusivePrefixes, System.Xml.XmlCanonicalWriter._scopes, System.Xml.XmlCanonicalWriter._xmlnsAttributes, System.Xml.XmlCanonicalWriter.AddXmlnsAttribute(), System.Xml.Dictionary, System.Xml.XmlCanonicalWriter.IsInclusivePrefix(), System.prefix, System.Xml.XmlCanonicalWriter.StartElement(), System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperArgumentNull(), System.Xml.XmlCanonicalWriter.ThrowIfClosed(), System.Text.Encoding.UTF8, System.Xml.XmlUTF8NodeWriter.WriteStartElement(), and System.Xml.XmlCanonicalWriter.Scope.xmlnsAttributeCount.
Referenced by System.Xml.XmlSigningNodeWriter.WriteStartElement(), System.Xml.XmlSigningNodeWriter.WriteStartElement(), and System.Xml.XmlSigningNodeWriter.WriteStartElement().