Terraria: System.Xml.XmlCanonicalWriter.WriteText
WriteText() [3/4]
void System.Xml.XmlCanonicalWriter.WriteText (int ch) inline
Definition at line 752 of file XmlCanonicalWriter.cs.
    {
        ThrowIfClosed();
        if (_inStartElement)
        {
            _elementWriter.WriteText(ch);
        }
        else
        {
            _writer.WriteText(ch);
        }
    }
References System.Xml.XmlCanonicalWriter._elementWriter, System.Xml.XmlCanonicalWriter._inStartElement, System.Xml.XmlCanonicalWriter._writer, System.ch, System.Xml.XmlCanonicalWriter.ThrowIfClosed(), and System.Xml.XmlUTF8NodeWriter.WriteText().
Referenced by System.Xml.XmlSigningNodeWriter.WriteBase64Text(), System.Xml.XmlSigningNodeWriter.WriteBoolText(), System.Xml.XmlCanonicalWriter.WriteCharEntity(), System.Xml.XmlSigningNodeWriter.WriteDateTimeText(), System.Xml.XmlSigningNodeWriter.WriteDecimalText(), System.Xml.XmlSigningNodeWriter.WriteDoubleText(), System.Xml.XmlSigningNodeWriter.WriteFloatText(), System.Xml.XmlSigningNodeWriter.WriteGuidText(), System.Xml.XmlSigningNodeWriter.WriteInt32Text(), System.Xml.XmlSigningNodeWriter.WriteInt64Text(), System.Xml.XmlSigningNodeWriter.WriteListSeparator(), System.Xml.XmlSigningNodeWriter.WriteQualifiedName(), System.Xml.XmlSigningNodeWriter.WriteText(), System.Xml.XmlSigningNodeWriter.WriteText(), System.Xml.XmlSigningNodeWriter.WriteText(), System.Xml.XmlSigningNodeWriter.WriteText(), System.Xml.XmlSigningNodeWriter.WriteTimeSpanText(), System.Xml.XmlSigningNodeWriter.WriteUInt64Text(), and System.Xml.XmlSigningNodeWriter.WriteUniqueIdText().