Terraria: System.Xml.XmlCanonicalWriter.WriteEndAttribute
WriteEndAttribute()
void System.Xml.XmlCanonicalWriter.WriteEndAttribute () inline
Definition at line 658 of file XmlCanonicalWriter.cs.
    {
        ThrowIfClosed();
        _elementWriter.WriteEndAttribute();
        _attribute.length = _elementWriter.Position - _attribute.offset;
        AddAttribute(ref _attribute);
    }
References System.Xml.XmlCanonicalWriter._attribute, System.Xml.XmlCanonicalWriter._elementWriter, System.Xml.XmlCanonicalWriter.AddAttribute(), System.Xml.Dictionary, System.Xml.XmlCanonicalWriter.Attribute.offset, System.Xml.XmlCanonicalWriter.ThrowIfClosed(), and System.Xml.XmlUTF8NodeWriter.WriteEndAttribute().
Referenced by System.Xml.XmlSigningNodeWriter.WriteEndAttribute().