Terraria: System.Xml.XmlCanonicalWriter.SetOutput
SetOutput()
void System.Xml.XmlCanonicalWriter.SetOutput (Stream stream, bool includeComments, string[] inclusivePrefixes) inline
Definition at line 157 of file XmlCanonicalWriter.cs.
    {
        if (stream == null)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperArgumentNull("stream");
        }
        if (_writer == null)
        {
            _writer = new XmlUTF8NodeWriter(s_isEscapedAttributeChar, s_isEscapedElementChar);
        }
        _writer.SetOutput(stream, ownsStream: false, null);
        if (_elementStream == null)
        {
            _elementStream = new MemoryStream();
        }
        if (_elementWriter == null)
        {
            _elementWriter = new XmlUTF8NodeWriter(s_isEscapedAttributeChar, s_isEscapedElementChar);
        }
        _elementWriter.SetOutput(_elementStream, ownsStream: false, null);
        if (_xmlnsAttributes == null)
        {
            _xmlnsAttributeCount = 0;
            _xmlnsOffset = 0;
            WriteXmlnsAttribute("xml", "http://www.w3.org/XML/1998/namespace");
            WriteXmlnsAttribute("xmlns", "http://www.w3.org/2000/xmlns/");
            WriteXmlnsAttribute(string.Empty, string.Empty);
            _xmlnsStartOffset = _xmlnsOffset;
            for (int i = 0; i < 3; i++)
            {
                _xmlnsAttributes[i].referred = true;
            }
        }
        else
        {
            _xmlnsAttributeCount = 3;
            _xmlnsOffset = _xmlnsStartOffset;
        }
        _depth = 0;
        _inStartElement = false;
        _includeComments = includeComments;
        _inclusivePrefixes = null;
        if (inclusivePrefixes == null)
        {
            return;
        }
        _inclusivePrefixes = new string[inclusivePrefixes.Length];
        for (int j = 0; j < inclusivePrefixes.Length; j++)
        {
            if (inclusivePrefixes[j] == null)
            {
                throw DiagnosticUtility.ExceptionUtility.ThrowHelperArgument(System.SR.InvalidInclusivePrefixListCollection);
            }
            _inclusivePrefixes[j] = inclusivePrefixes[j];
        }
    }
References System.Xml.XmlCanonicalWriter._depth, System.Xml.XmlCanonicalWriter._elementStream, System.Xml.XmlCanonicalWriter._elementWriter, System.Xml.XmlCanonicalWriter._includeComments, System.Xml.XmlCanonicalWriter._inclusivePrefixes, System.Xml.XmlCanonicalWriter._inStartElement, System.Xml.XmlCanonicalWriter._writer, System.Xml.XmlCanonicalWriter._xmlnsAttributeCount, System.Xml.XmlCanonicalWriter._xmlnsAttributes, System.Xml.XmlCanonicalWriter._xmlnsOffset, System.Xml.XmlCanonicalWriter._xmlnsStartOffset, System.Xml.Dictionary, System.SR.InvalidInclusivePrefixListCollection, System.Xml.XmlCanonicalWriter.XmlnsAttribute.referred, System.Xml.XmlCanonicalWriter.s_isEscapedAttributeChar, System.Xml.XmlCanonicalWriter.s_isEscapedElementChar, System.Xml.XmlUTF8NodeWriter.SetOutput(), System.stream, System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperArgument(), System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperArgumentNull(), and System.Xml.XmlCanonicalWriter.WriteXmlnsAttribute().
Referenced by System.Xml.XmlSigningNodeWriter.SetOutput().