Terraria: System.Xml.Serialization.XmlCustomFormatter.ToTime
ToTime()
static DateTime System.Xml.Serialization.XmlCustomFormatter.ToTime (string value) inline static package
Definition at line 249 of file XmlCustomFormatter.cs.
    {
        if (!System.LocalAppContextSwitches.IgnoreKindInUtcTimeSerialization)
        {
            return DateTime.ParseExact(value, s_allTimeFormats, DateTimeFormatInfo.InvariantInfo, DateTimeStyles.AllowLeadingWhite | DateTimeStyles.AllowTrailingWhite | DateTimeStyles.NoCurrentDateDefault | DateTimeStyles.RoundtripKind);
        }
        return DateTime.ParseExact(value, s_allTimeFormats, DateTimeFormatInfo.InvariantInfo, DateTimeStyles.AllowLeadingWhite | DateTimeStyles.AllowTrailingWhite | DateTimeStyles.NoCurrentDateDefault);
    }
References System.LocalAppContextSwitches.IgnoreKindInUtcTimeSerialization, System.Globalization.DateTimeFormatInfo.InvariantInfo, System.DateTime.ParseExact(), System.Xml.Serialization.XmlCustomFormatter.s_allTimeFormats, and System.value.
Referenced by System.Xml.Serialization.XmlCustomFormatter.ToDefaultValue(), and System.Xml.Serialization.XmlSerializationReader.ToTime().