Terraria: ReLogic.Peripherals.RGB.RgbDevice.GetProcessedLedColor
GetProcessedLedColor()
Vector4 ReLogic.Peripherals.RGB.RgbDevice.GetProcessedLedColor (int index) inline protected inherited
Definition at line 37 of file RgbDevice.cs.
    {
        //IL_000c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0011: Unknown result type (might be due to invalid IL or missing references)
        //IL_001f: Unknown result type (might be due to invalid IL or missing references)
        Vector4 color = _backBuffer.Colors[index];
        _colorProfile.Apply(ref color);
        return color;
    }
References ReLogic.Peripherals.RGB.RgbDevice._backBuffer, ReLogic.Peripherals.RGB.RgbDevice._colorProfile, ReLogic.Peripherals.RGB.DeviceColorProfile.Apply(), and ReLogic.Peripherals.RGB.Fragment.Colors.
Referenced by ReLogic.Peripherals.RGB.Corsair.CorsairGenericDevice.Present(), ReLogic.Peripherals.RGB.Corsair.CorsairKeyboard.Present(), ReLogic.Peripherals.RGB.Logitech.LogitechKeyboard.Present(), ReLogic.Peripherals.RGB.Logitech.LogitechSingleLightDevice.Present(), ReLogic.Peripherals.RGB.Razer.RazerHeadset.Present(), ReLogic.Peripherals.RGB.Razer.RazerKeyboard.Present(), ReLogic.Peripherals.RGB.Razer.RazerKeypad.Present(), ReLogic.Peripherals.RGB.Razer.RazerLink.Present(), ReLogic.Peripherals.RGB.Razer.RazerMouse.Present(), ReLogic.Peripherals.RGB.Razer.RazerMousepad.Present(), ReLogic.Peripherals.RGB.SteelSeries.SteelSeriesKeyboard.Present(), and ReLogic.Peripherals.RGB.SteelSeries.SteelSeriesSecondaryDeviceByZone.Present().