Terraria: System.Xml.Serialization.XmlCustomFormatter.FromTime
FromTime()
static string System.Xml.Serialization.XmlCustomFormatter.FromTime (DateTime value) inline static package
Definition at line 91 of file XmlCustomFormatter.cs.
    {
        if (!System.LocalAppContextSwitches.IgnoreKindInUtcTimeSerialization && value.Kind == DateTimeKind.Utc)
        {
            return XmlConvert.ToString(DateTime.MinValue + value.TimeOfDay, "HH:mm:ss.fffffffZ");
        }
        return XmlConvert.ToString(DateTime.MinValue + value.TimeOfDay, "HH:mm:ss.fffffffzzzzzz");
    }
References System.LocalAppContextSwitches.IgnoreKindInUtcTimeSerialization, System.DateTime.MinValue, System.Xml.XmlConvert.ToString(), and System.value.
Referenced by System.Xml.Serialization.XmlCustomFormatter.FromDefaultValue(), and System.Xml.Serialization.XmlSerializationWriter.FromTime().