Terraria: System.Xml.Serialization.XmlCustomFormatter.FromDefaultValue
FromDefaultValue()
static string System.Xml.Serialization.XmlCustomFormatter.FromDefaultValue (object value, string formatter) inline static package
Definition at line 50 of file XmlCustomFormatter.cs.
    {
        if (value == null)
        {
            return null;
        }
        Type type = value.GetType();
        if (type == typeof(DateTime))
        {
            switch (formatter)
            {
            case "DateTime":
                return FromDateTime((DateTime)value);
            case "Date":
                return FromDate((DateTime)value);
            case "Time":
                return FromTime((DateTime)value);
            }
        }
        else if (type == typeof(string))
        {
            switch (formatter)
            {
            case "XmlName":
                return FromXmlName((string)value);
            case "XmlNCName":
                return FromXmlNCName((string)value);
            case "XmlNmToken":
                return FromXmlNmToken((string)value);
            case "XmlNmTokens":
                return FromXmlNmTokens((string)value);
            }
        }
        throw new XmlException(System.SR.Format(System.SR.XmlUnsupportedDefaultType, type.FullName));
    }
References System.Xml.Dictionary, System.SR.Format(), System.Xml.Serialization.XmlCustomFormatter.FromDate(), System.Xml.Serialization.XmlCustomFormatter.FromDateTime(), System.Xml.Serialization.XmlCustomFormatter.FromTime(), System.Xml.Serialization.XmlCustomFormatter.FromXmlName(), System.Xml.Serialization.XmlCustomFormatter.FromXmlNCName(), System.Xml.Serialization.XmlCustomFormatter.FromXmlNmToken(), System.Xml.Serialization.XmlCustomFormatter.FromXmlNmTokens(), System.Type.GetType(), System.type, System.value, System.Xml.XmlException, and System.SR.XmlUnsupportedDefaultType.
Referenced by System.Xml.Serialization.XmlSchemaExporter.ExportDefaultValue().