Terraria: System.Xml.Serialization.XmlCustomFormatter.ToEnum
ToEnum()
static long System.Xml.Serialization.XmlCustomFormatter.ToEnum (string val, Hashtable vals, string typeName, bool validate) inline static package
Definition at line 313 of file XmlCustomFormatter.cs.
    {
        long num = 0L;
        string[] array = val.Split((char[]?)null);
        for (int i = 0; i < array.Length; i++)
        {
            object obj = vals[array[i]];
            if (obj != null)
            {
                num |= (long)obj;
            }
            else if (validate && array[i].Length > 0)
            {
                throw new InvalidOperationException(System.SR.Format(System.SR.XmlUnknownConstant, array[i], typeName));
            }
        }
        return num;
    }
References System.array, System.Xml.Dictionary, System.SR.Format(), System.Xml.L, System.obj, and System.SR.XmlUnknownConstant.
Referenced by System.Xml.Serialization.XmlSchemaExporter.ExportDefaultValue(), and System.Xml.Serialization.XmlSerializationReader.ToEnum().