Terraria: System.Xml.Serialization.XmlCustomFormatter.ToDefaultValue
ToDefaultValue()
static object System.Xml.Serialization.XmlCustomFormatter.ToDefaultValue (string value, string formatter) inline static package
Definition at line 215 of file XmlCustomFormatter.cs.
    {
        return formatter switch
        {
            "DateTime" => ToDateTime(value),
            "Date" => ToDate(value),
            "Time" => ToTime(value),
            "XmlName" => ToXmlName(value),
            "XmlNCName" => ToXmlNCName(value),
            "XmlNmToken" => ToXmlNmToken(value),
            "XmlNmTokens" => ToXmlNmTokens(value),
            _ => throw new XmlException(System.SR.Format(System.SR.XmlUnsupportedDefaultValue, formatter)),
        };
    }
References System.Xml.Dictionary, System.SR.Format(), System.Xml.Serialization.XmlCustomFormatter.ToDate(), System.Xml.Serialization.XmlCustomFormatter.ToDateTime(), System.Xml.Serialization.XmlCustomFormatter.ToTime(), System.Xml.Serialization.XmlCustomFormatter.ToXmlName(), System.Xml.Serialization.XmlCustomFormatter.ToXmlNCName(), System.Xml.Serialization.XmlCustomFormatter.ToXmlNmToken(), System.Xml.Serialization.XmlCustomFormatter.ToXmlNmTokens(), System.value, System.Xml.XmlException, and System.SR.XmlUnsupportedDefaultValue.
Referenced by System.Xml.Serialization.XmlSchemaImporter.ImportEnumeratedDataType().