Terraria: System.Xml.Serialization.XmlCustomFormatter.ToXmlNmToken
ToXmlNmToken()
static string System.Xml.Serialization.XmlCustomFormatter.ToXmlNmToken (string value) inline static package
Definition at line 276 of file XmlCustomFormatter.cs.
    {
        return XmlConvert.DecodeName(CollapseWhitespace(value));
    }
References System.Xml.Serialization.CollapseWhitespace, System.Xml.XmlConvert.DecodeName(), and System.value.
Referenced by System.Xml.Serialization.XmlCustomFormatter.ToDefaultValue(), and System.Xml.Serialization.XmlSerializationReader.ToXmlNmToken().