Terraria: System.Xml.Serialization.XmlCustomFormatter.ToDateTime
ToDateTime() [1/2]
static DateTime System.Xml.Serialization.XmlCustomFormatter.ToDateTime (string value) inline static package
Definition at line 230 of file XmlCustomFormatter.cs.
    {
        if (Mode == DateTimeSerializationSection.DateTimeSerializationMode.Local)
        {
            return ToDateTime(value, s_allDateTimeFormats);
        }
        return XmlConvert.ToDateTime(value, XmlDateTimeSerializationMode.RoundtripKind);
    }
References System.Xml.Serialization.XmlCustomFormatter.s_allDateTimeFormats, System.Xml.XmlConvert.ToDateTime(), System.Xml.Serialization.XmlCustomFormatter.ToDateTime(), and System.value.
Referenced by System.Xml.Serialization.XmlCustomFormatter.ToDate(), System.Xml.Serialization.XmlCustomFormatter.ToDateTime(), System.Xml.Serialization.XmlSerializationReader.ToDateTime(), and System.Xml.Serialization.XmlCustomFormatter.ToDefaultValue().