Terraria: ReLogic.Peripherals.RGB.RgbDevice.DebugDraw
DebugDraw()
virtual void ReLogic.Peripherals.RGB.RgbDevice.DebugDraw (IDebugDrawer drawer, Vector2 position, float scale) inline virtual inherited
Reimplemented in Terraria.GameContent.RGB.DebugKeyboard.
Definition at line 126 of file RgbDevice.cs.
    {
        //IL_000e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0013: Unknown result type (might be due to invalid IL or missing references)
        //IL_0020: Unknown result type (might be due to invalid IL or missing references)
        //IL_0025: Unknown result type (might be due to invalid IL or missing references)
        //IL_002f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0040: Unknown result type (might be due to invalid IL or missing references)
        //IL_0051: Unknown result type (might be due to invalid IL or missing references)
        //IL_005a: Unknown result type (might be due to invalid IL or missing references)
        //IL_005c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0061: Unknown result type (might be due to invalid IL or missing references)
        //IL_0062: Unknown result type (might be due to invalid IL or missing references)
        //IL_0075: Unknown result type (might be due to invalid IL or missing references)
        //IL_007a: Unknown result type (might be due to invalid IL or missing references)
        //IL_007b: Unknown result type (might be due to invalid IL or missing references)
        for (int i = 0; i < LedCount; i++)
        {
            Vector2 canvasPositionOfIndex = _backBuffer.GetCanvasPositionOfIndex(i);
            Vector4 vector = _backBuffer.Colors[i];
            vector.X *= vector.W;
            vector.Y *= vector.W;
            vector.Z *= vector.W;
            drawer.DrawSquare(new Vector4(canvasPositionOfIndex * scale + position, scale / 10f, scale / 10f), new Color(vector));
        }
    }
References ReLogic.Peripherals.RGB.RgbDevice._backBuffer, ReLogic.Peripherals.RGB.Fragment.Colors, ReLogic.Graphics.IDebugDrawer.DrawSquare(), ReLogic.Peripherals.RGB.Fragment.GetCanvasPositionOfIndex(), and ReLogic.Peripherals.RGB.RgbDevice.LedCount.
Referenced by ReLogic.Peripherals.RGB.ChromaEngine.DebugDraw().