Terraria: System.Xml.Serialization.XmlCustomFormatter.FromDateTime
FromDateTime()
static string System.Xml.Serialization.XmlCustomFormatter.FromDateTime (DateTime value) inline static package
Definition at line 100 of file XmlCustomFormatter.cs.
    {
        if (Mode == DateTimeSerializationSection.DateTimeSerializationMode.Local)
        {
            return XmlConvert.ToString(value, "yyyy-MM-ddTHH:mm:ss.fffffffzzzzzz");
        }
        return XmlConvert.ToString(value, XmlDateTimeSerializationMode.RoundtripKind);
    }
References System.Xml.XmlConvert.ToString(), and System.value.
Referenced by System.Xml.Serialization.XmlSerializationWriter.FromDateTime(), and System.Xml.Serialization.XmlCustomFormatter.FromDefaultValue().