Terraria: ReLogic.Peripherals.RGB.RgbDevice.RgbDevice
RgbDevice()
ReLogic.Peripherals.RGB.RgbDevice.RgbDevice (RgbDeviceVendor vendor, RgbDeviceType type, Fragment fragment, DeviceColorProfile colorProfile) inline protected
Definition at line 22 of file RgbDevice.cs.
    {
        PreferredLevelOfDetail = EffectDetailLevel.High;
        Vendor = vendor;
        Type = type;
        _backBuffer = fragment;
        _workingFragment = fragment.CreateCopy();
        _colorProfile = colorProfile;
    }
References ReLogic.Peripherals.RGB.RgbDevice._backBuffer, ReLogic.Peripherals.RGB.RgbDevice._colorProfile, ReLogic.Peripherals.RGB.RgbDevice._workingFragment, ReLogic.Peripherals.RGB.Fragment.CreateCopy(), ReLogic.Peripherals.RGB.RgbDevice.PreferredLevelOfDetail, ReLogic.Peripherals.RGB.RgbDevice.Type, and ReLogic.Peripherals.RGB.RgbDevice.Vendor.
Referenced by Terraria.GameContent.RGB.DebugKeyboard.DebugDraw(), and Terraria.GameContent.RGB.VirtualKeyboard.Render().