Terraria: System.Text.Json.BitStack.Pop
Pop()
bool System.Text.Json.BitStack.Pop () inline
Definition at line 63 of file BitStack.cs.
    {
        _currentDepth--;
        bool flag = false;
        if (_currentDepth < 64)
        {
            _allocationFreeContainer >>= 1;
            return (_allocationFreeContainer & 1) != 0;
        }
        if (_currentDepth == 64)
        {
            return (_allocationFreeContainer & 1) != 0;
        }
        return PopFromArray();
    }
References System.Text.Json.BitStack._allocationFreeContainer, System.Text.Json.BitStack._currentDepth, and System.Text.Json.BitStack.PopFromArray().
Referenced by System.Text.Json.Utf8JsonReader.UpdateBitStackOnEndToken(), and System.Text.Json.Utf8JsonWriter.ValidateEnd().