Terraria: System.Xml.Xsl.Xslt.MatcherBuilder.AddPatterns
AddPatterns()
void System.Xml.Xsl.Xslt.MatcherBuilder.AddPatterns (List< TemplateMatch > matches) inline private
Definition at line 53 of file MatcherBuilder.cs.
    {
        foreach (TemplateMatch match in matches)
        {
            Pattern pattern = new Pattern(match, ++_priority);
            switch (match.NodeKind)
            {
            case XmlNodeKindFlags.Element:
                _elementPatterns.Add(pattern);
                break;
            case XmlNodeKindFlags.Attribute:
                _attributePatterns.Add(pattern);
                break;
            case XmlNodeKindFlags.Text:
                _textPatterns.Add(pattern);
                break;
            case XmlNodeKindFlags.Document:
                _documentPatterns.Add(pattern);
                break;
            case XmlNodeKindFlags.Comment:
                _commentPatterns.Add(pattern);
                break;
            case XmlNodeKindFlags.PI:
                _piPatterns.Add(pattern);
                break;
            default:
                _heterogenousPatterns.Add(pattern);
                break;
            }
        }
    }
References System.Xml.Xsl.Xslt.MatcherBuilder._attributePatterns, System.Xml.Xsl.Xslt.MatcherBuilder._commentPatterns, System.Xml.Xsl.Xslt.MatcherBuilder._documentPatterns, System.Xml.Xsl.Xslt.MatcherBuilder._elementPatterns, System.Xml.Xsl.Xslt.MatcherBuilder._heterogenousPatterns, System.Xml.Xsl.Xslt.MatcherBuilder._piPatterns, System.Xml.Xsl.Xslt.MatcherBuilder._priority, System.Xml.Xsl.Xslt.MatcherBuilder._textPatterns, System.Xml.Xsl.Xslt.PatternBag.Add(), System.Collections.Generic.Dictionary< TKey, TValue >.Add(), and System.match.
Referenced by System.Xml.Xsl.Xslt.MatcherBuilder.CollectPatternsInternal().