Terraria: System.Xml.Serialization.XmlSchemaExporter._types
_types
readonly Hashtable System.Xml.Serialization.XmlSchemaExporter._types = new Hashtable() private
Definition at line 16 of file XmlSchemaExporter.cs.
Referenced by System.Xml.Serialization.XmlSchemaExporter.ExportArrayMapping(), System.Xml.Serialization.XmlSchemaExporter.ExportEnumMapping(), and System.Xml.Serialization.XmlSchemaExporter.ExportStructMapping().