Terraria: System.Xml.Xsl.Xslt.MatcherBuilder.Clear
Clear()
void System.Xml.Xsl.Xslt.MatcherBuilder.Clear () inline private
Definition at line 40 of file MatcherBuilder.cs.
    {
        _priority = -1;
        _elementPatterns.Clear();
        _attributePatterns.Clear();
        _textPatterns.Clear();
        _documentPatterns.Clear();
        _commentPatterns.Clear();
        _piPatterns.Clear();
        _heterogenousPatterns.Clear();
        _allMatches.Clear();
    }
References System.Xml.Xsl.Xslt.MatcherBuilder._allMatches, System.Xml.Xsl.Xslt.MatcherBuilder._attributePatterns, System.Xml.Xsl.Xslt.MatcherBuilder._commentPatterns, System.Xml.Xsl.Xslt.MatcherBuilder._documentPatterns, System.Xml.Xsl.Xslt.MatcherBuilder._elementPatterns, System.Xml.Xsl.Xslt.MatcherBuilder._heterogenousPatterns, System.Xml.Xsl.Xslt.MatcherBuilder._piPatterns, System.Xml.Xsl.Xslt.MatcherBuilder._priority, System.Xml.Xsl.Xslt.MatcherBuilder._textPatterns, System.Collections.Generic.Dictionary< TKey, TValue >.Clear(), and System.Xml.Xsl.Xslt.PatternBag.Clear().
Referenced by System.Xml.Xsl.Xslt.MatcherBuilder.CollectPatterns().