Terraria: System.Xml.Xsl.Xslt.MatcherBuilder.MatchPatternsWhosePriorityGreater
MatchPatternsWhosePriorityGreater()
QilNode System.Xml.Xsl.Xslt.MatcherBuilder.MatchPatternsWhosePriorityGreater (QilIterator it, List< Pattern > patternList, QilNode matcher) inline private
Definition at line 148 of file MatcherBuilder.cs.
    {
        if (patternList.Count == 0)
        {
            return matcher;
        }
        if (IsNoMatch(matcher))
        {
            return MatchPatterns(it, patternList);
        }
        QilIterator qilIterator = _f.Let(matcher);
        QilNode qilNode = _f.Int32(-1);
        int num = -1;
        foreach (Pattern pattern in patternList)
        {
            if (pattern.Priority > num + 1)
            {
                qilNode = _f.Conditional(_f.Gt(qilIterator, _f.Int32(num)), qilIterator, qilNode);
            }
            qilNode = _f.Conditional(MatchPattern(it, pattern.Match), _f.Int32(pattern.Priority), qilNode);
            num = pattern.Priority;
        }
        if (num != _priority)
        {
            qilNode = _f.Conditional(_f.Gt(qilIterator, _f.Int32(num)), qilIterator, qilNode);
        }
        return _f.Loop(qilIterator, qilNode);
    }
References System.Xml.Xsl.Xslt.MatcherBuilder._f, System.Xml.Xsl.Xslt.MatcherBuilder._priority, System.Xml.Xsl.Qil.QilPatternFactory.Conditional(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Xml.Dictionary, System.Xml.Xsl.Qil.QilPatternFactory.Gt(), System.Xml.Xsl.Qil.QilPatternFactory.Int32(), System.Xml.Xsl.Xslt.MatcherBuilder.IsNoMatch(), System.Xml.Xsl.Qil.QilPatternFactory.Let(), System.Xml.Xsl.Qil.QilPatternFactory.Loop(), System.Xml.Xsl.Xslt.MatcherBuilder.MatchPattern(), and System.Xml.Xsl.Xslt.MatcherBuilder.MatchPatterns().
Referenced by System.Xml.Xsl.Xslt.MatcherBuilder.BuildMatcher(), and System.Xml.Xsl.Xslt.MatcherBuilder.MatchPatterns().