Terraria: System.Xml.Serialization.XmlSchemaExporter.ExportElement
ExportElement()
XmlSchemaElement System.Xml.Serialization.XmlSchemaExporter.ExportElement (ElementAccessor accessor) inline private
Definition at line 235 of file XmlSchemaExporter.cs.
    {
        if (!accessor.Mapping.IncludeInSchema && !accessor.Mapping.TypeDesc.IsRoot)
        {
            return null;
        }
        if (accessor.Any && accessor.Name.Length == 0)
        {
            throw new InvalidOperationException(System.SR.XmlIllegalWildcard);
        }
        XmlSchemaElement xmlSchemaElement = (XmlSchemaElement)_elements[accessor];
        if (xmlSchemaElement != null)
        {
            return xmlSchemaElement;
        }
        xmlSchemaElement = new XmlSchemaElement();
        xmlSchemaElement.Name = accessor.Name;
        xmlSchemaElement.IsNillable = accessor.IsNullable;
        _elements.Add(accessor, xmlSchemaElement);
        xmlSchemaElement.Form = accessor.Form;
        AddSchemaItem(xmlSchemaElement, accessor.Namespace, null);
        ExportElementMapping(xmlSchemaElement, accessor.Mapping, accessor.Namespace, accessor.Any);
        return xmlSchemaElement;
    }
References System.Xml.Serialization.XmlSchemaExporter._elements, System.Collections.Hashtable.Add(), System.Xml.Serialization.XmlSchemaExporter.AddSchemaItem(), System.Xml.Dictionary, System.Xml.Serialization.XmlSchemaExporter.ExportElementMapping(), and System.SR.XmlIllegalWildcard.
Referenced by System.Xml.Serialization.XmlSchemaExporter.ExportMembersMapping(), and System.Xml.Serialization.XmlSchemaExporter.ExportTypeMapping().