Terraria: System.Xml.Serialization.XmlSchemaExporter.ExportDefaultValue
ExportDefaultValue()
static string System.Xml.Serialization.XmlSchemaExporter.ExportDefaultValue (TypeMapping mapping, object value) inline static package
Definition at line 907 of file XmlSchemaExporter.cs.
    {
        if (!(mapping is PrimitiveMapping))
        {
            return null;
        }
        if (value == null || value == DBNull.Value)
        {
            return null;
        }
        if (mapping is EnumMapping)
        {
            EnumMapping enumMapping = (EnumMapping)mapping;
            ConstantMapping[] constants = enumMapping.Constants;
            if (enumMapping.IsFlags)
            {
                string[] array = new string[constants.Length];
                long[] array2 = new long[constants.Length];
                Hashtable hashtable = new Hashtable();
                for (int i = 0; i < constants.Length; i++)
                {
                    array[i] = constants[i].XmlName;
                    array2[i] = 1 << i;
                    hashtable.Add(constants[i].Name, array2[i]);
                }
                long num = XmlCustomFormatter.ToEnum((string)value, hashtable, enumMapping.TypeName, validate: false);
                if (num == 0L)
                {
                    return null;
                }
                return XmlCustomFormatter.FromEnum(num, array, array2, mapping.TypeDesc.FullName);
            }
            for (int j = 0; j < constants.Length; j++)
            {
                if (constants[j].Name == (string)value)
                {
                    return constants[j].XmlName;
                }
            }
            return null;
        }
        PrimitiveMapping primitiveMapping = (PrimitiveMapping)mapping;
        if (!primitiveMapping.TypeDesc.HasCustomFormatter)
        {
            if (primitiveMapping.TypeDesc.FormatterName == "String")
            {
                return (string)value;
            }
            Type typeFromHandle = typeof(XmlConvert);
            MethodInfo method = typeFromHandle.GetMethod("ToString", new Type[1] { primitiveMapping.TypeDesc.Type });
            if (method != null)
            {
                return (string)method.Invoke(typeFromHandle, new object[1] { value });
            }
            throw new InvalidOperationException(System.SR.Format(System.SR.XmlInvalidDefaultValue, value, primitiveMapping.TypeDesc.Name));
        }
        string text = XmlCustomFormatter.FromDefaultValue(value, primitiveMapping.TypeDesc.FormatterName);
        if (text == null)
        {
            throw new InvalidOperationException(System.SR.Format(System.SR.XmlInvalidDefaultValue, value, primitiveMapping.TypeDesc.Name));
        }
        return text;
    }
References System.Collections.Hashtable.Add(), System.array, System.Xml.Dictionary, System.SR.Format(), System.Xml.Serialization.XmlCustomFormatter.FromDefaultValue(), System.Xml.Serialization.XmlCustomFormatter.FromEnum(), System.Reflection.MethodBase.Invoke(), System.Xml.L, System.Xml.Name, System.text, System.Xml.Serialization.XmlCustomFormatter.ToEnum(), System.DBNull.Value, System.value, and System.SR.XmlInvalidDefaultValue.
Referenced by System.Xml.Serialization.XmlSchemaExporter.ExportAttributeAccessor(), and System.Xml.Serialization.XmlSchemaExporter.ExportElementAccessor().