Terraria: System.Xml.Serialization.XmlSchemaExporter.ExportMembersMapping
ExportMembersMapping() [3/3]
void System.Xml.Serialization.XmlSchemaExporter.ExportMembersMapping (XmlMembersMapping xmlMembersMapping, bool exportEnclosingType) inline
Definition at line 62 of file XmlSchemaExporter.cs.
    {
        xmlMembersMapping.CheckShallow();
        MembersMapping membersMapping = (MembersMapping)xmlMembersMapping.Accessor.Mapping;
        CheckScope(xmlMembersMapping.Scope);
        if (membersMapping.HasWrapperElement && exportEnclosingType)
        {
            ExportElement(xmlMembersMapping.Accessor);
        }
        else
        {
            MemberMapping[] members = membersMapping.Members;
            foreach (MemberMapping memberMapping in members)
            {
                if (memberMapping.Attribute != null)
                {
                    throw new InvalidOperationException(System.SR.Format(System.SR.XmlBareAttributeMember, memberMapping.Attribute.Name));
                }
                if (memberMapping.Text != null)
                {
                    throw new InvalidOperationException(System.SR.Format(System.SR.XmlBareTextMember, memberMapping.Text.Name));
                }
                if (memberMapping.Elements != null && memberMapping.Elements.Length != 0)
                {
                    if (memberMapping.TypeDesc.IsArrayLike && !(memberMapping.Elements[0].Mapping is ArrayMapping))
                    {
                        throw new InvalidOperationException(System.SR.Format(System.SR.XmlIllegalArrayElement, memberMapping.Elements[0].Name));
                    }
                    if (exportEnclosingType)
                    {
                        ExportElement(memberMapping.Elements[0]);
                    }
                    else
                    {
                        ExportMapping(memberMapping.Elements[0].Mapping, memberMapping.Elements[0].Namespace, memberMapping.Elements[0].Any);
                    }
                }
            }
        }
        ExportRootIfNecessary(xmlMembersMapping.Scope);
    }
References System.Xml.Serialization.Mapping.Mapping(), System.Xml.Serialization.XmlSchemaExporter.CheckScope(), System.Xml.Dictionary, System.Xml.Serialization.XmlSchemaExporter.ExportElement(), System.Xml.Serialization.XmlSchemaExporter.ExportMapping(), System.Xml.Serialization.XmlSchemaExporter.ExportRootIfNecessary(), System.SR.Format(), System.SR.XmlBareAttributeMember, System.SR.XmlBareTextMember, and System.SR.XmlIllegalArrayElement.