Terraria: System.Xml.Serialization.XmlSchemaExporter.ExportAnyType
ExportAnyType() [1/2]
string System.Xml.Serialization.XmlSchemaExporter.ExportAnyType (string? ns) inline
Definition at line 137 of file XmlSchemaExporter.cs.
    {
        string text = "any";
        int num = 0;
        XmlSchema xmlSchema = _schemas[ns];
        if (xmlSchema != null)
        {
            while (true)
            {
                XmlSchemaType xmlSchemaType = FindSchemaType(text, xmlSchema.Items);
                if (xmlSchemaType == null)
                {
                    break;
                }
                if (IsAnyType(xmlSchemaType, mixed: true, unbounded: true))
                {
                    return text;
                }
                num++;
                text = "any" + num.ToString(CultureInfo.InvariantCulture);
            }
        }
        XmlSchemaComplexType xmlSchemaComplexType = new XmlSchemaComplexType();
        xmlSchemaComplexType.Name = text;
        xmlSchemaComplexType.IsMixed = true;
        XmlSchemaSequence xmlSchemaSequence = new XmlSchemaSequence();
        XmlSchemaAny xmlSchemaAny = new XmlSchemaAny();
        xmlSchemaAny.MinOccurs = 0m;
        xmlSchemaAny.MaxOccurs = decimal.MaxValue;
        xmlSchemaSequence.Items.Add(xmlSchemaAny);
        xmlSchemaComplexType.Particle = xmlSchemaSequence;
        AddSchemaItem(xmlSchemaComplexType, ns, null);
        return text;
    }
References System.Xml.Serialization.XmlSchemaExporter._schemas, System.Xml.Serialization.XmlSchemaExporter.AddSchemaItem(), System.Xml.Dictionary, System.Xml.Serialization.XmlSchemaExporter.FindSchemaType(), System.Globalization.CultureInfo.InvariantCulture, System.Xml.Serialization.XmlSchemaExporter.IsAnyType(), and System.text.