Terraria: System.Xml.Serialization.XmlSchemaExporter.ExportAnonymousPrimitiveMapping
ExportAnonymousPrimitiveMapping()
XmlSchemaType System.Xml.Serialization.XmlSchemaExporter.ExportAnonymousPrimitiveMapping (PrimitiveMapping mapping) inline private
Definition at line 609 of file XmlSchemaExporter.cs.
    {
        if (mapping is EnumMapping)
        {
            return ExportEnumMapping((EnumMapping)mapping, null);
        }
        throw new InvalidOperationException(System.SR.Format(System.SR.XmlInternalErrorDetails, "Unsupported anonymous mapping type: " + mapping.ToString()));
    }
References System.Xml.Dictionary, System.Xml.Serialization.XmlSchemaExporter.ExportEnumMapping(), System.SR.Format(), and System.SR.XmlInternalErrorDetails.
Referenced by System.Xml.Serialization.XmlSchemaExporter.ExportAttributeAccessor(), and System.Xml.Serialization.XmlSchemaExporter.ExportElementMapping().