Terraria: System.Xml.Xsl.Xslt.MatcherBuilder.CollectPatternsInternal
CollectPatternsInternal()
void System.Xml.Xsl.Xslt.MatcherBuilder.CollectPatternsInternal (Stylesheet sheet, QilName mode) inline private
Definition at line 85 of file MatcherBuilder.cs.
    {
        Stylesheet[] imports = sheet.Imports;
        foreach (Stylesheet sheet2 in imports)
        {
            CollectPatternsInternal(sheet2, mode);
        }
        if (sheet.TemplateMatches.TryGetValue(mode, out var value))
        {
            AddPatterns(value);
            _allMatches.Add(value);
        }
    }
References System.Xml.Xsl.Xslt.MatcherBuilder._allMatches, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Xml.Xsl.Xslt.MatcherBuilder.AddPatterns(), System.Xml.Xsl.Xslt.MatcherBuilder.CollectPatternsInternal(), System.Collections.Generic.Dictionary< TKey, TValue >.TryGetValue(), and System.value.
Referenced by System.Xml.Xsl.Xslt.MatcherBuilder.CollectPatterns(), and System.Xml.Xsl.Xslt.MatcherBuilder.CollectPatternsInternal().