Terraria: System.Xml.Serialization.XmlSchemaExporter.ExportArrayMapping
ExportArrayMapping()
void System.Xml.Serialization.XmlSchemaExporter.ExportArrayMapping (ArrayMapping mapping, string ns, XmlSchemaElement element) inline private
Definition at line 632 of file XmlSchemaExporter.cs.
    {
        ArrayMapping arrayMapping = mapping;
        while (arrayMapping.Next != null)
        {
            arrayMapping = arrayMapping.Next;
        }
        XmlSchemaComplexType xmlSchemaComplexType = (XmlSchemaComplexType)_types[arrayMapping];
        if (xmlSchemaComplexType == null)
        {
            CheckForDuplicateType(arrayMapping, arrayMapping.Namespace);
            xmlSchemaComplexType = new XmlSchemaComplexType();
            if (!mapping.IsAnonymousType)
            {
                xmlSchemaComplexType.Name = mapping.TypeName;
                AddSchemaItem(xmlSchemaComplexType, mapping.Namespace, ns);
            }
            if (!arrayMapping.IsAnonymousType)
            {
                _types.Add(arrayMapping, xmlSchemaComplexType);
            }
            XmlSchemaSequence xmlSchemaSequence = new XmlSchemaSequence();
            ExportElementAccessors(xmlSchemaSequence, mapping.Elements, repeats: true, valueTypeOptional: false, mapping.Namespace);
            if (xmlSchemaSequence.Items.Count > 0)
            {
                if (xmlSchemaSequence.Items[0] is XmlSchemaChoice)
                {
                    xmlSchemaComplexType.Particle = (XmlSchemaChoice)xmlSchemaSequence.Items[0];
                }
                else
                {
                    xmlSchemaComplexType.Particle = xmlSchemaSequence;
                }
            }
        }
        else
        {
            AddSchemaImport(mapping.Namespace, ns);
        }
        if (element != null)
        {
            if (mapping.IsAnonymousType)
            {
                element.SchemaType = xmlSchemaComplexType;
            }
            else
            {
                element.SchemaTypeName = new XmlQualifiedName(xmlSchemaComplexType.Name, mapping.Namespace);
            }
        }
    }
References System.Xml.Serialization.XmlSchemaExporter._types, System.Collections.Hashtable.Add(), System.Xml.Serialization.XmlSchemaExporter.AddSchemaImport(), System.Xml.Serialization.XmlSchemaExporter.AddSchemaItem(), System.Xml.Serialization.XmlSchemaExporter.CheckForDuplicateType(), System.Xml.Dictionary, System.Xml.Serialization.XmlSchemaExporter.ExportElementAccessors(), and System.Xml.Serialization.ArrayMapping.Next.
Referenced by System.Xml.Serialization.XmlSchemaExporter.ExportElementMapping(), System.Xml.Serialization.XmlSchemaExporter.ExportMapping(), and System.Xml.Serialization.XmlSchemaExporter.ExportRootIfNecessary().