Terraria: System.Xml.Serialization.XmlSchemaExporter.ExportStructMapping
ExportStructMapping()
XmlQualifiedName System.Xml.Serialization.XmlSchemaExporter.ExportStructMapping (StructMapping mapping, string ns, XmlSchemaElement element) inline private
Definition at line 994 of file XmlSchemaExporter.cs.
    {
        if (mapping.TypeDesc.IsRoot)
        {
            _needToExportRoot = true;
            return XmlQualifiedName.Empty;
        }
        if (mapping.IsAnonymousType)
        {
            if (_references[mapping] != null)
            {
                throw new InvalidOperationException(System.SR.Format(System.SR.XmlCircularReference2, mapping.TypeDesc.Name, "AnonymousType", "false"));
            }
            _references[mapping] = mapping;
        }
        XmlSchemaComplexType xmlSchemaComplexType = (XmlSchemaComplexType)_types[mapping];
        if (xmlSchemaComplexType == null)
        {
            if (!mapping.IncludeInSchema)
            {
                throw new InvalidOperationException(System.SR.Format(System.SR.XmlCannotIncludeInSchema, mapping.TypeDesc.Name));
            }
            CheckForDuplicateType(mapping, mapping.Namespace);
            xmlSchemaComplexType = new XmlSchemaComplexType();
            if (!mapping.IsAnonymousType)
            {
                xmlSchemaComplexType.Name = mapping.TypeName;
                AddSchemaItem(xmlSchemaComplexType, mapping.Namespace, ns);
                _types.Add(mapping, xmlSchemaComplexType);
            }
            xmlSchemaComplexType.IsAbstract = mapping.TypeDesc.IsAbstract;
            bool openModel = mapping.IsOpenModel;
            if (mapping.BaseMapping != null && mapping.BaseMapping.IncludeInSchema)
            {
                if (mapping.BaseMapping.IsAnonymousType)
                {
                    throw new InvalidOperationException(System.SR.Format(System.SR.XmlAnonymousBaseType, mapping.TypeDesc.Name, mapping.BaseMapping.TypeDesc.Name, "AnonymousType", "false"));
                }
                if (mapping.HasSimpleContent)
                {
                    XmlSchemaSimpleContent xmlSchemaSimpleContent = new XmlSchemaSimpleContent();
                    XmlSchemaSimpleContentExtension xmlSchemaSimpleContentExtension = new XmlSchemaSimpleContentExtension();
                    xmlSchemaSimpleContentExtension.BaseTypeName = ExportStructMapping(mapping.BaseMapping, mapping.Namespace, null);
                    xmlSchemaSimpleContent.Content = xmlSchemaSimpleContentExtension;
                    xmlSchemaComplexType.ContentModel = xmlSchemaSimpleContent;
                }
                else
                {
                    XmlSchemaComplexContentExtension xmlSchemaComplexContentExtension = new XmlSchemaComplexContentExtension();
                    xmlSchemaComplexContentExtension.BaseTypeName = ExportStructMapping(mapping.BaseMapping, mapping.Namespace, null);
                    XmlSchemaComplexContent xmlSchemaComplexContent = new XmlSchemaComplexContent();
                    xmlSchemaComplexContent.Content = xmlSchemaComplexContentExtension;
                    xmlSchemaComplexContent.IsMixed = XmlSchemaImporter.IsMixed((XmlSchemaComplexType)_types[mapping.BaseMapping]);
                    xmlSchemaComplexType.ContentModel = xmlSchemaComplexContent;
                }
                openModel = false;
            }
            ExportTypeMembers(xmlSchemaComplexType, mapping.Members, mapping.TypeName, mapping.Namespace, mapping.HasSimpleContent, openModel);
            ExportDerivedMappings(mapping);
            if (mapping.XmlnsMember != null)
            {
                AddXmlnsAnnotation(xmlSchemaComplexType, mapping.XmlnsMember.Name);
            }
        }
        else
        {
            AddSchemaImport(mapping.Namespace, ns);
        }
        if (mapping.IsAnonymousType)
        {
            _references[mapping] = null;
            if (element != null)
            {
                element.SchemaType = xmlSchemaComplexType;
            }
            return XmlQualifiedName.Empty;
        }
        XmlQualifiedName xmlQualifiedName = new XmlQualifiedName(xmlSchemaComplexType.Name, mapping.Namespace);
        if (element != null)
        {
            element.SchemaTypeName = xmlQualifiedName;
        }
        return xmlQualifiedName;
    }
References System.Xml.Serialization.XmlSchemaExporter._needToExportRoot, System.Xml.Serialization.XmlSchemaExporter._references, System.Xml.Serialization.XmlSchemaExporter._types, System.Collections.Hashtable.Add(), System.Xml.Serialization.XmlSchemaExporter.AddSchemaImport(), System.Xml.Serialization.XmlSchemaExporter.AddSchemaItem(), System.Xml.Serialization.XmlSchemaExporter.AddXmlnsAnnotation(), System.Xml.Serialization.XmlSchemaExporter.CheckForDuplicateType(), System.Xml.Dictionary, System.Xml.XmlQualifiedName.Empty, System.Xml.Serialization.XmlSchemaExporter.ExportDerivedMappings(), System.Xml.Serialization.XmlSchemaExporter.ExportStructMapping(), System.Xml.Serialization.XmlSchemaExporter.ExportTypeMembers(), System.SR.Format(), System.Xml.Serialization.XmlSchemaImporter.IsMixed(), System.SR.XmlAnonymousBaseType, System.SR.XmlCannotIncludeInSchema, and System.SR.XmlCircularReference2.
Referenced by System.Xml.Serialization.XmlSchemaExporter.ExportDerivedMappings(), System.Xml.Serialization.XmlSchemaExporter.ExportElementMapping(), System.Xml.Serialization.XmlSchemaExporter.ExportMapping(), and System.Xml.Serialization.XmlSchemaExporter.ExportStructMapping().