Terraria: System.Xml.Serialization.XmlSchemaExporter.ExportElementAccessor
ExportElementAccessor()
void System.Xml.Serialization.XmlSchemaExporter.ExportElementAccessor (XmlSchemaGroupBase group, ElementAccessor accessor, bool repeats, bool valueTypeOptional, string ns) inline private
Definition at line 844 of file XmlSchemaExporter.cs.
    {
        if (accessor.Any && accessor.Name.Length == 0)
        {
            XmlSchemaAny xmlSchemaAny = new XmlSchemaAny();
            xmlSchemaAny.MinOccurs = 0m;
            xmlSchemaAny.MaxOccurs = (repeats ? decimal.MaxValue : 1m);
            if (accessor.Namespace != null && accessor.Namespace.Length > 0 && accessor.Namespace != ns)
            {
                xmlSchemaAny.Namespace = accessor.Namespace;
            }
            group.Items.Add(xmlSchemaAny);
            return;
        }
        XmlSchemaElement xmlSchemaElement = (XmlSchemaElement)_elements[accessor];
        int num = ((!(repeats || accessor.HasDefault || (!accessor.IsNullable && !accessor.Mapping.TypeDesc.IsValueType) || valueTypeOptional)) ? 1 : 0);
        decimal maxOccurs = ((repeats || accessor.IsUnbounded) ? decimal.MaxValue : 1m);
        if (xmlSchemaElement == null)
        {
            xmlSchemaElement = new XmlSchemaElement();
            xmlSchemaElement.IsNillable = accessor.IsNullable;
            xmlSchemaElement.Name = accessor.Name;
            if (accessor.HasDefault)
            {
                xmlSchemaElement.DefaultValue = ExportDefaultValue(accessor.Mapping, accessor.Default);
            }
            if (accessor.IsTopLevelInSchema)
            {
                _elements.Add(accessor, xmlSchemaElement);
                xmlSchemaElement.Form = accessor.Form;
                AddSchemaItem(xmlSchemaElement, accessor.Namespace, ns);
            }
            else
            {
                xmlSchemaElement.MinOccurs = num;
                xmlSchemaElement.MaxOccurs = maxOccurs;
                XmlSchema xmlSchema = _schemas[ns];
                if (xmlSchema == null)
                {
                    xmlSchemaElement.Form = ((accessor.Form != XmlSchemaForm.Qualified) ? accessor.Form : XmlSchemaForm.None);
                }
                else
                {
                    xmlSchemaElement.Form = ((accessor.Form != xmlSchema.ElementFormDefault) ? accessor.Form : XmlSchemaForm.None);
                }
            }
            ExportElementMapping(xmlSchemaElement, accessor.Mapping, accessor.Namespace, accessor.Any);
        }
        if (accessor.IsTopLevelInSchema)
        {
            XmlSchemaElement xmlSchemaElement2 = new XmlSchemaElement();
            xmlSchemaElement2.RefName = new XmlQualifiedName(accessor.Name, accessor.Namespace);
            xmlSchemaElement2.MinOccurs = num;
            xmlSchemaElement2.MaxOccurs = maxOccurs;
            group.Items.Add(xmlSchemaElement2);
            AddSchemaImport(accessor.Namespace, ns);
        }
        else
        {
            group.Items.Add(xmlSchemaElement);
        }
    }
References System.Xml.Serialization.XmlSchemaExporter._elements, System.Xml.Serialization.XmlSchemaExporter._schemas, System.Collections.Hashtable.Add(), System.Xml.Serialization.XmlSchemaExporter.AddSchemaImport(), System.Xml.Serialization.XmlSchemaExporter.AddSchemaItem(), System.Xml.Dictionary, System.Xml.Serialization.XmlSchemaExporter.ExportDefaultValue(), and System.Xml.Serialization.XmlSchemaExporter.ExportElementMapping().
Referenced by System.Xml.Serialization.XmlSchemaExporter.ExportElementAccessors().