Terraria: System.Xml.Serialization.XmlSchemaExporter.ExportEnumMapping
ExportEnumMapping()
XmlSchemaType System.Xml.Serialization.XmlSchemaExporter.ExportEnumMapping (EnumMapping mapping, string ns) inline private
Definition at line 1191 of file XmlSchemaExporter.cs.
    {
        if (!mapping.IncludeInSchema)
        {
            throw new InvalidOperationException(System.SR.Format(System.SR.XmlCannotIncludeInSchema, mapping.TypeDesc.Name));
        }
        XmlSchemaSimpleType xmlSchemaSimpleType = (XmlSchemaSimpleType)_types[mapping];
        if (xmlSchemaSimpleType == null)
        {
            CheckForDuplicateType(mapping, mapping.Namespace);
            xmlSchemaSimpleType = new XmlSchemaSimpleType();
            xmlSchemaSimpleType.Name = mapping.TypeName;
            if (!mapping.IsAnonymousType)
            {
                _types.Add(mapping, xmlSchemaSimpleType);
                AddSchemaItem(xmlSchemaSimpleType, mapping.Namespace, ns);
            }
            XmlSchemaSimpleTypeRestriction xmlSchemaSimpleTypeRestriction = new XmlSchemaSimpleTypeRestriction();
            xmlSchemaSimpleTypeRestriction.BaseTypeName = new XmlQualifiedName("string", "http://www.w3.org/2001/XMLSchema");
            for (int i = 0; i < mapping.Constants.Length; i++)
            {
                ConstantMapping constantMapping = mapping.Constants[i];
                XmlSchemaEnumerationFacet xmlSchemaEnumerationFacet = new XmlSchemaEnumerationFacet();
                xmlSchemaEnumerationFacet.Value = constantMapping.XmlName;
                xmlSchemaSimpleTypeRestriction.Facets.Add(xmlSchemaEnumerationFacet);
            }
            if (!mapping.IsFlags)
            {
                xmlSchemaSimpleType.Content = xmlSchemaSimpleTypeRestriction;
            }
            else
            {
                XmlSchemaSimpleTypeList xmlSchemaSimpleTypeList = new XmlSchemaSimpleTypeList();
                XmlSchemaSimpleType xmlSchemaSimpleType2 = new XmlSchemaSimpleType();
                xmlSchemaSimpleType2.Content = xmlSchemaSimpleTypeRestriction;
                xmlSchemaSimpleTypeList.ItemType = xmlSchemaSimpleType2;
                xmlSchemaSimpleType.Content = xmlSchemaSimpleTypeList;
            }
        }
        if (!mapping.IsAnonymousType)
        {
            AddSchemaImport(mapping.Namespace, ns);
        }
        return xmlSchemaSimpleType;
    }
References System.Xml.Serialization.XmlSchemaExporter._types, System.Collections.Hashtable.Add(), System.Xml.Serialization.XmlSchemaExporter.AddSchemaImport(), System.Xml.Serialization.XmlSchemaExporter.AddSchemaItem(), System.Xml.Serialization.XmlSchemaExporter.CheckForDuplicateType(), System.Xml.Dictionary, System.SR.Format(), and System.SR.XmlCannotIncludeInSchema.
Referenced by System.Xml.Serialization.XmlSchemaExporter.ExportAnonymousPrimitiveMapping(), and System.Xml.Serialization.XmlSchemaExporter.ExportPrimitiveMapping().