Terraria: System.Xml.Serialization.XmlSchemaExporter.ExportMapping
ExportMapping()
void System.Xml.Serialization.XmlSchemaExporter.ExportMapping (Mapping mapping, string ns, bool isAny) inline private
Definition at line 376 of file XmlSchemaExporter.cs.
    {
        if (mapping is ArrayMapping)
        {
            ExportArrayMapping((ArrayMapping)mapping, ns, null);
            return;
        }
        if (mapping is PrimitiveMapping)
        {
            ExportPrimitiveMapping((PrimitiveMapping)mapping, ns);
            return;
        }
        if (mapping is StructMapping)
        {
            ExportStructMapping((StructMapping)mapping, ns, null);
            return;
        }
        if (mapping is MembersMapping)
        {
            ExportMembersMapping((MembersMapping)mapping, ns);
            return;
        }
        if (mapping is SpecialMapping)
        {
            ExportSpecialMapping((SpecialMapping)mapping, ns, isAny, null);
            return;
        }
        if (mapping is NullableMapping)
        {
            ExportMapping(((NullableMapping)mapping).BaseMapping, ns, isAny);
            return;
        }
        throw new ArgumentException(System.SR.XmlInternalError, "mapping");
    }
References System.Xml.ArgumentException, System.Xml.Dictionary, System.Xml.Serialization.XmlSchemaExporter.ExportArrayMapping(), System.Xml.Serialization.XmlSchemaExporter.ExportMapping(), System.Xml.Serialization.XmlSchemaExporter.ExportMembersMapping(), System.Xml.Serialization.XmlSchemaExporter.ExportPrimitiveMapping(), System.Xml.Serialization.XmlSchemaExporter.ExportSpecialMapping(), System.Xml.Serialization.XmlSchemaExporter.ExportStructMapping(), and System.SR.XmlInternalError.
Referenced by System.Xml.Serialization.XmlSchemaExporter.ExportMapping(), and System.Xml.Serialization.XmlSchemaExporter.ExportMembersMapping().