Terraria: System.Xml.Serialization.XmlSchemaExporter.ExportRootIfNecessary
ExportRootIfNecessary()
void System.Xml.Serialization.XmlSchemaExporter.ExportRootIfNecessary (TypeScope typeScope) inline private
Definition at line 971 of file XmlSchemaExporter.cs.
    {
        if (!_needToExportRoot)
        {
            return;
        }
        foreach (TypeMapping typeMapping in typeScope.TypeMappings)
        {
            if (typeMapping is StructMapping && typeMapping.TypeDesc.IsRoot)
            {
                ExportDerivedMappings((StructMapping)typeMapping);
            }
            else if (typeMapping is ArrayMapping)
            {
                ExportArrayMapping((ArrayMapping)typeMapping, typeMapping.Namespace, null);
            }
            else if (typeMapping is SerializableMapping)
            {
                ExportSpecialMapping((SerializableMapping)typeMapping, typeMapping.Namespace, isAny: false, null);
            }
        }
    }
References System.Xml.Serialization.XmlSchemaExporter._needToExportRoot, System.Xml.Dictionary, System.Xml.Serialization.XmlSchemaExporter.ExportArrayMapping(), System.Xml.Serialization.XmlSchemaExporter.ExportDerivedMappings(), System.Xml.Serialization.XmlSchemaExporter.ExportSpecialMapping(), System.Xml.Serialization.TypeDesc.IsRoot, and System.Xml.Serialization.TypeMapping.TypeDesc.
Referenced by System.Xml.Serialization.XmlSchemaExporter.ExportMembersMapping(), System.Xml.Serialization.XmlSchemaExporter.ExportTypeMapping(), and System.Xml.Serialization.XmlSchemaExporter.ExportTypeMapping().