Terraria: System.Xml.Serialization.XmlSchemaExporter.ExportElementMapping
ExportElementMapping()
void System.Xml.Serialization.XmlSchemaExporter.ExportElementMapping (XmlSchemaElement element, Mapping mapping, string ns, bool isAny) inline private
Definition at line 411 of file XmlSchemaExporter.cs.
    {
        if (mapping is ArrayMapping)
        {
            ExportArrayMapping((ArrayMapping)mapping, ns, element);
        }
        else if (mapping is PrimitiveMapping)
        {
            PrimitiveMapping primitiveMapping = (PrimitiveMapping)mapping;
            if (primitiveMapping.IsAnonymousType)
            {
                element.SchemaType = ExportAnonymousPrimitiveMapping(primitiveMapping);
            }
            else
            {
                element.SchemaTypeName = ExportPrimitiveMapping(primitiveMapping, ns);
            }
        }
        else if (mapping is StructMapping)
        {
            ExportStructMapping((StructMapping)mapping, ns, element);
        }
        else if (mapping is MembersMapping)
        {
            element.SchemaType = ExportMembersMapping((MembersMapping)mapping, ns);
        }
        else if (mapping is SpecialMapping)
        {
            ExportSpecialMapping((SpecialMapping)mapping, ns, isAny, element);
        }
        else
        {
            if (!(mapping is NullableMapping))
            {
                throw new ArgumentException(System.SR.XmlInternalError, "mapping");
            }
            ExportElementMapping(element, ((NullableMapping)mapping).BaseMapping, ns, isAny);
        }
    }
References System.Xml.ArgumentException, System.Xml.Dictionary, System.Xml.Serialization.XmlSchemaExporter.ExportAnonymousPrimitiveMapping(), System.Xml.Serialization.XmlSchemaExporter.ExportArrayMapping(), System.Xml.Serialization.XmlSchemaExporter.ExportElementMapping(), System.Xml.Serialization.XmlSchemaExporter.ExportMembersMapping(), System.Xml.Serialization.XmlSchemaExporter.ExportPrimitiveMapping(), System.Xml.Serialization.XmlSchemaExporter.ExportSpecialMapping(), System.Xml.Serialization.XmlSchemaExporter.ExportStructMapping(), and System.SR.XmlInternalError.
Referenced by System.Xml.Serialization.XmlSchemaExporter.ExportElement(), System.Xml.Serialization.XmlSchemaExporter.ExportElementAccessor(), and System.Xml.Serialization.XmlSchemaExporter.ExportElementMapping().