Terraria: System.Xml.Serialization.XmlSchemaExporter.CheckForDuplicateType
CheckForDuplicateType()
void System.Xml.Serialization.XmlSchemaExporter.CheckForDuplicateType (TypeMapping mapping, string newNamespace) inline private
Definition at line 260 of file XmlSchemaExporter.cs.
    {
        if (mapping.IsAnonymousType)
        {
            return;
        }
        string typeName = mapping.TypeName;
        XmlSchema xmlSchema = _schemas[newNamespace];
        if (xmlSchema == null)
        {
            return;
        }
        foreach (XmlSchemaObject item in xmlSchema.Items)
        {
            if (item is XmlSchemaType xmlSchemaType && xmlSchemaType.Name == typeName)
            {
                throw new InvalidOperationException(System.SR.Format(System.SR.XmlDuplicateTypeName, typeName, newNamespace));
            }
        }
    }
References System.Xml.Serialization.XmlSchemaExporter._schemas, System.Xml.Dictionary, System.SR.Format(), System.item, System.Xml.Schema.XmlSchemaType.Name, and System.SR.XmlDuplicateTypeName.
Referenced by System.Xml.Serialization.XmlSchemaExporter.ExportArrayMapping(), System.Xml.Serialization.XmlSchemaExporter.ExportEnumMapping(), and System.Xml.Serialization.XmlSchemaExporter.ExportStructMapping().