Terraria: System.Xml.Xsl.Xslt.MatcherBuilder.BuildMatcher
BuildMatcher()
QilNode System.Xml.Xsl.Xslt.MatcherBuilder.BuildMatcher (QilIterator it, IList< XslNode > actualArgs, QilNode otherwise) inline
Definition at line 192 of file MatcherBuilder.cs.
    {
        QilNode otherwise2 = _f.Int32(-1);
        otherwise2 = MatchPatterns(it, XmlQueryTypeFactory.PI, _piPatterns, otherwise2);
        otherwise2 = MatchPatterns(it, XmlQueryTypeFactory.Comment, _commentPatterns, otherwise2);
        otherwise2 = MatchPatterns(it, XmlQueryTypeFactory.Document, _documentPatterns, otherwise2);
        otherwise2 = MatchPatterns(it, XmlQueryTypeFactory.Text, _textPatterns, otherwise2);
        otherwise2 = MatchPatterns(it, XmlQueryTypeFactory.Attribute, _attributePatterns, otherwise2);
        otherwise2 = MatchPatterns(it, XmlQueryTypeFactory.Element, _elementPatterns, otherwise2);
        otherwise2 = MatchPatternsWhosePriorityGreater(it, _heterogenousPatterns, otherwise2);
        if (IsNoMatch(otherwise2))
        {
            return otherwise;
        }
        QilNode[] array = new QilNode[_priority + 2];
        int num = -1;
        foreach (List<TemplateMatch> allMatch in _allMatches)
        {
            foreach (TemplateMatch item in allMatch)
            {
                array[++num] = _invkGen.GenerateInvoke(item.TemplateFunction, actualArgs);
            }
        }
        array[++num] = otherwise;
        return _f.Choice(otherwise2, _f.BranchList(array));
    }
References System.Xml.Xsl.Xslt.MatcherBuilder._allMatches, System.Xml.Xsl.Xslt.MatcherBuilder._attributePatterns, System.Xml.Xsl.Xslt.MatcherBuilder._commentPatterns, System.Xml.Xsl.Xslt.MatcherBuilder._documentPatterns, System.Xml.Xsl.Xslt.MatcherBuilder._elementPatterns, System.Xml.Xsl.Xslt.MatcherBuilder._f, System.Xml.Xsl.Xslt.MatcherBuilder._heterogenousPatterns, System.Xml.Xsl.Xslt.MatcherBuilder._invkGen, System.Xml.Xsl.Xslt.MatcherBuilder._piPatterns, System.Xml.Xsl.Xslt.MatcherBuilder._priority, System.Xml.Xsl.Xslt.MatcherBuilder._textPatterns, System.array, System.Xml.Xsl.XmlQueryTypeFactory.Attribute, System.Xml.Xsl.Qil.QilPatternFactory.BranchList(), System.Xml.Xsl.Qil.QilPatternFactory.Choice(), System.Xml.Xsl.XmlQueryTypeFactory.Comment, System.Xml.Dictionary, System.Xml.Xsl.XmlQueryTypeFactory.Document, System.Xml.Xsl.XmlQueryTypeFactory.Element, System.Xml.Xsl.Xslt.InvokeGenerator.GenerateInvoke(), System.Xml.Xsl.Qil.QilPatternFactory.Int32(), System.Xml.Xsl.Xslt.MatcherBuilder.IsNoMatch(), System.item, System.Xml.Xsl.Xslt.MatcherBuilder.MatchPatterns(), System.Xml.Xsl.Xslt.MatcherBuilder.MatchPatternsWhosePriorityGreater(), System.Xml.Xsl.XmlQueryTypeFactory.PI, and System.Xml.Xsl.XmlQueryTypeFactory.Text.
Referenced by System.Xml.Xsl.Xslt.QilGenerator.InvokeApplyFunction().