Terraria: Terraria.WorldBuilding.GenAction.UnitApply
UnitApply()
bool Terraria.WorldBuilding.GenAction.UnitApply (Point origin, int x, int y, params object[] args) inline protected inherited
Definition at line 15 of file GenAction.cs.
    {
        if (OutputData != null)
        {
            OutputData.Add(x - origin.X, y - origin.Y);
        }
        if (NextAction != null)
        {
            return NextAction.Apply(origin, x, y, args);
        }
        return true;
    }
References Terraria.WorldBuilding.ShapeData.Add(), Terraria.WorldBuilding.GenAction.Apply(), Terraria.WorldBuilding.GenAction.NextAction, Terraria.WorldBuilding.GenAction.OutputData, Microsoft.Xna.Framework.Point.X, and Microsoft.Xna.Framework.Point.Y.
Referenced by Terraria.GameContent.Generation.ActionGrass.Apply(), Terraria.GameContent.Generation.ActionPlaceStatue.Apply(), Terraria.GameContent.Generation.ActionStalagtite.Apply(), Terraria.GameContent.Generation.ActionVines.Apply(), Terraria.WorldBuilding.Actions.ContinueWrapper.Apply(), Terraria.WorldBuilding.Actions.Count.Apply(), Terraria.WorldBuilding.Actions.Scanner.Apply(), Terraria.WorldBuilding.Actions.TileScanner.Apply(), Terraria.WorldBuilding.Actions.Blank.Apply(), Terraria.WorldBuilding.Actions.Custom.Apply(), Terraria.WorldBuilding.Actions.ClearMetadata.Apply(), Terraria.WorldBuilding.Actions.Clear.Apply(), Terraria.WorldBuilding.Actions.ClearTile.Apply(), Terraria.WorldBuilding.Actions.ClearWall.Apply(), Terraria.WorldBuilding.Actions.HalfBlock.Apply(), Terraria.WorldBuilding.Actions.SetTile.Apply(), Terraria.WorldBuilding.Actions.SetTileKeepWall.Apply(), Terraria.WorldBuilding.Actions.DebugDraw.Apply(), Terraria.WorldBuilding.Actions.SetSlope.Apply(), Terraria.WorldBuilding.Actions.SetHalfTile.Apply(), Terraria.WorldBuilding.Actions.SetTileAndWallRainbowPaint.Apply(), Terraria.WorldBuilding.Actions.PlaceTile.Apply(), Terraria.WorldBuilding.Actions.RemoveWall.Apply(), Terraria.WorldBuilding.Actions.PlaceWall.Apply(), Terraria.WorldBuilding.Actions.SetLiquid.Apply(), Terraria.WorldBuilding.Actions.SwapSolidTile.Apply(), Terraria.WorldBuilding.Actions.SetFrames.Apply(), Terraria.WorldBuilding.Actions.Smooth.Apply(), Terraria.WorldBuilding.Modifiers.ShapeScale.Apply(), Terraria.WorldBuilding.Modifiers.Expand.Apply(), Terraria.WorldBuilding.Modifiers.RadialDither.Apply(), Terraria.WorldBuilding.Modifiers.Blotches.Apply(), Terraria.WorldBuilding.Modifiers.InShape.Apply(), Terraria.WorldBuilding.Modifiers.NotInShape.Apply(), Terraria.WorldBuilding.Modifiers.Conditions.Apply(), Terraria.WorldBuilding.Modifiers.OnlyWalls.Apply(), Terraria.WorldBuilding.Modifiers.OnlyTiles.Apply(), Terraria.WorldBuilding.Modifiers.IsTouching.Apply(), Terraria.WorldBuilding.Modifiers.NotTouching.Apply(), Terraria.WorldBuilding.Modifiers.IsTouchingAir.Apply(), Terraria.WorldBuilding.Modifiers.SkipTiles.Apply(), Terraria.WorldBuilding.Modifiers.HasLiquid.Apply(), Terraria.WorldBuilding.Modifiers.SkipWalls.Apply(), Terraria.WorldBuilding.Modifiers.IsEmpty.Apply(), Terraria.WorldBuilding.Modifiers.IsSolid.Apply(), Terraria.WorldBuilding.Modifiers.IsNotSolid.Apply(), Terraria.WorldBuilding.Modifiers.RectangleMask.Apply(), Terraria.WorldBuilding.Modifiers.Offset.Apply(), Terraria.WorldBuilding.Modifiers.Dither.Apply(), and Terraria.WorldBuilding.Modifiers.Flip.Apply().