Terraria: System.Xml.Serialization.XmlSchemaExporter.ExportTypeMapping
ExportTypeMapping() [1/2]
XmlQualifiedName? System.Xml.Serialization.XmlSchemaExporter.ExportTypeMapping (XmlMembersMapping xmlMembersMapping) inline
Definition at line 37 of file XmlSchemaExporter.cs.
    {
        xmlMembersMapping.CheckShallow();
        CheckScope(xmlMembersMapping.Scope);
        MembersMapping membersMapping = (MembersMapping)xmlMembersMapping.Accessor.Mapping;
        if (membersMapping.Members.Length == 1 && membersMapping.Members[0].Elements[0].Mapping is SpecialMapping)
        {
            SpecialMapping mapping = (SpecialMapping)membersMapping.Members[0].Elements[0].Mapping;
            XmlSchemaType xmlSchemaType = ExportSpecialMapping(mapping, xmlMembersMapping.Accessor.Namespace, isAny: false, null);
            if (xmlSchemaType != null && xmlSchemaType.Name != null && xmlSchemaType.Name.Length > 0)
            {
                xmlSchemaType.Name = xmlMembersMapping.Accessor.Name;
                AddSchemaItem(xmlSchemaType, xmlMembersMapping.Accessor.Namespace, null);
            }
            ExportRootIfNecessary(xmlMembersMapping.Scope);
            return new XmlQualifiedName(xmlMembersMapping.Accessor.Name, xmlMembersMapping.Accessor.Namespace);
        }
        return null;
    }
References System.Xml.Serialization.Mapping.Mapping(), System.Xml.Serialization.XmlSchemaExporter.AddSchemaItem(), System.Xml.Serialization.XmlSchemaExporter.CheckScope(), System.Xml.Dictionary, System.Xml.Serialization.XmlSchemaExporter.ExportRootIfNecessary(), System.Xml.Serialization.XmlSchemaExporter.ExportSpecialMapping(), and System.Xml.Schema.XmlSchemaType.Name.