Terraria: System.Xml.Serialization.XmlSchemaExporter.ExportAttributeAccessor
ExportAttributeAccessor()
void System.Xml.Serialization.XmlSchemaExporter.ExportAttributeAccessor (XmlSchemaComplexType type, AttributeAccessor accessor, bool valueTypeOptional, string ns) inline private
Definition at line 708 of file XmlSchemaExporter.cs.
    {
        if (accessor == null)
        {
            return;
        }
        XmlSchemaObjectCollection attributes;
        if (type.ContentModel != null)
        {
            if (type.ContentModel.Content is XmlSchemaComplexContentRestriction)
            {
                attributes = ((XmlSchemaComplexContentRestriction)type.ContentModel.Content).Attributes;
            }
            else if (type.ContentModel.Content is XmlSchemaComplexContentExtension)
            {
                attributes = ((XmlSchemaComplexContentExtension)type.ContentModel.Content).Attributes;
            }
            else
            {
                if (!(type.ContentModel.Content is XmlSchemaSimpleContentExtension))
                {
                    throw new InvalidOperationException(System.SR.Format(System.SR.XmlInvalidContent, type.ContentModel.Content.GetType().Name));
                }
                attributes = ((XmlSchemaSimpleContentExtension)type.ContentModel.Content).Attributes;
            }
        }
        else
        {
            attributes = type.Attributes;
        }
        if (accessor.IsSpecialXmlNamespace)
        {
            AddSchemaImport("http://www.w3.org/XML/1998/namespace", ns);
            XmlSchemaAttribute xmlSchemaAttribute = new XmlSchemaAttribute();
            xmlSchemaAttribute.Use = XmlSchemaUse.Optional;
            xmlSchemaAttribute.RefName = new XmlQualifiedName(accessor.Name, "http://www.w3.org/XML/1998/namespace");
            attributes.Add(xmlSchemaAttribute);
            return;
        }
        if (accessor.Any)
        {
            if (type.ContentModel == null)
            {
                type.AnyAttribute = new XmlSchemaAnyAttribute();
                return;
            }
            XmlSchemaContent content = type.ContentModel.Content;
            if (content is XmlSchemaComplexContentExtension)
            {
                XmlSchemaComplexContentExtension xmlSchemaComplexContentExtension = (XmlSchemaComplexContentExtension)content;
                xmlSchemaComplexContentExtension.AnyAttribute = new XmlSchemaAnyAttribute();
            }
            else if (content is XmlSchemaComplexContentRestriction)
            {
                XmlSchemaComplexContentRestriction xmlSchemaComplexContentRestriction = (XmlSchemaComplexContentRestriction)content;
                xmlSchemaComplexContentRestriction.AnyAttribute = new XmlSchemaAnyAttribute();
            }
            else if (type.ContentModel.Content is XmlSchemaSimpleContentExtension)
            {
                XmlSchemaSimpleContentExtension xmlSchemaSimpleContentExtension = (XmlSchemaSimpleContentExtension)content;
                xmlSchemaSimpleContentExtension.AnyAttribute = new XmlSchemaAnyAttribute();
            }
            return;
        }
        XmlSchemaAttribute xmlSchemaAttribute2 = new XmlSchemaAttribute();
        xmlSchemaAttribute2.Use = XmlSchemaUse.None;
        if (!accessor.HasDefault && !valueTypeOptional && accessor.Mapping.TypeDesc.IsValueType)
        {
            xmlSchemaAttribute2.Use = XmlSchemaUse.Required;
        }
        xmlSchemaAttribute2.Name = accessor.Name;
        if (accessor.Namespace == null || accessor.Namespace == ns)
        {
            XmlSchema xmlSchema = _schemas[ns];
            if (xmlSchema == null)
            {
                xmlSchemaAttribute2.Form = ((accessor.Form != XmlSchemaForm.Unqualified) ? accessor.Form : XmlSchemaForm.None);
            }
            else
            {
                xmlSchemaAttribute2.Form = ((accessor.Form != xmlSchema.AttributeFormDefault) ? accessor.Form : XmlSchemaForm.None);
            }
            attributes.Add(xmlSchemaAttribute2);
        }
        else
        {
            if (_attributes[accessor] == null)
            {
                xmlSchemaAttribute2.Use = XmlSchemaUse.None;
                xmlSchemaAttribute2.Form = accessor.Form;
                AddSchemaItem(xmlSchemaAttribute2, accessor.Namespace, ns);
                _attributes.Add(accessor, accessor);
            }
            XmlSchemaAttribute xmlSchemaAttribute3 = new XmlSchemaAttribute();
            xmlSchemaAttribute3.Use = XmlSchemaUse.None;
            xmlSchemaAttribute3.RefName = new XmlQualifiedName(accessor.Name, accessor.Namespace);
            attributes.Add(xmlSchemaAttribute3);
            AddSchemaImport(accessor.Namespace, ns);
        }
        if (accessor.Mapping is PrimitiveMapping)
        {
            PrimitiveMapping primitiveMapping = (PrimitiveMapping)accessor.Mapping;
            if (primitiveMapping.IsList)
            {
                XmlSchemaSimpleType xmlSchemaSimpleType = new XmlSchemaSimpleType();
                XmlSchemaSimpleTypeList xmlSchemaSimpleTypeList = new XmlSchemaSimpleTypeList();
                if (primitiveMapping.IsAnonymousType)
                {
                    xmlSchemaSimpleTypeList.ItemType = (XmlSchemaSimpleType)ExportAnonymousPrimitiveMapping(primitiveMapping);
                }
                else
                {
                    xmlSchemaSimpleTypeList.ItemTypeName = ExportPrimitiveMapping(primitiveMapping, (accessor.Namespace == null) ? ns : accessor.Namespace);
                }
                xmlSchemaSimpleType.Content = xmlSchemaSimpleTypeList;
                xmlSchemaAttribute2.SchemaType = xmlSchemaSimpleType;
            }
            else if (primitiveMapping.IsAnonymousType)
            {
                xmlSchemaAttribute2.SchemaType = (XmlSchemaSimpleType)ExportAnonymousPrimitiveMapping(primitiveMapping);
            }
            else
            {
                xmlSchemaAttribute2.SchemaTypeName = ExportPrimitiveMapping(primitiveMapping, (accessor.Namespace == null) ? ns : accessor.Namespace);
            }
        }
        else if (!(accessor.Mapping is SpecialMapping))
        {
            throw new InvalidOperationException(System.SR.XmlInternalError);
        }
        if (accessor.HasDefault)
        {
            xmlSchemaAttribute2.DefaultValue = ExportDefaultValue(accessor.Mapping, accessor.Default);
        }
    }
References System.Xml.Serialization.Mapping.Mapping(), System.Xml.Serialization.XmlSchemaExporter._attributes, System.Xml.Serialization.XmlSchemaExporter._schemas, System.Collections.Hashtable.Add(), System.Xml.Schema.XmlSchemaObjectCollection.Add(), System.Xml.Serialization.XmlSchemaExporter.AddSchemaImport(), System.Xml.Serialization.XmlSchemaExporter.AddSchemaItem(), System.Xml.Dictionary, System.Xml.Serialization.XmlSchemaExporter.ExportAnonymousPrimitiveMapping(), System.Xml.Serialization.XmlSchemaExporter.ExportDefaultValue(), System.Xml.Serialization.XmlSchemaExporter.ExportPrimitiveMapping(), System.SR.Format(), System.type, System.SR.XmlInternalError, and System.SR.XmlInvalidContent.
Referenced by System.Xml.Serialization.XmlSchemaExporter.ExportTypeMembers().