Terraria: System.Xml.Xsl.Xslt.MatcherBuilder.MatchPatterns
MatchPatterns() [2/3]
QilNode System.Xml.Xsl.Xslt.MatcherBuilder.MatchPatterns (QilIterator it, XmlQueryType xt, List< Pattern > patternList, QilNode otherwise) inline private
Definition at line 130 of file MatcherBuilder.cs.
    {
        if (patternList.Count == 0)
        {
            return otherwise;
        }
        return _f.Conditional(_f.IsType(it, xt), MatchPatterns(it, patternList), otherwise);
    }
References System.Xml.Xsl.Xslt.MatcherBuilder._f, System.Xml.Xsl.Qil.QilPatternFactory.Conditional(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Xml.Dictionary, System.Xml.Xsl.Qil.QilPatternFactory.IsType(), and System.Xml.Xsl.Xslt.MatcherBuilder.MatchPatterns().