Terraria: System.Xml.Xsl.Xslt.MatcherBuilder.MatchPatterns
MatchPatterns() [1/3]
QilNode System.Xml.Xsl.Xslt.MatcherBuilder.MatchPatterns (QilIterator it, List< Pattern > patternList) inline private
Definition at line 120 of file MatcherBuilder.cs.
    {
        QilNode qilNode = _f.Int32(-1);
        foreach (Pattern pattern in patternList)
        {
            qilNode = _f.Conditional(MatchPattern(it, pattern.Match), _f.Int32(pattern.Priority), qilNode);
        }
        return qilNode;
    }
References System.Xml.Xsl.Xslt.MatcherBuilder._f, System.Xml.Xsl.Qil.QilPatternFactory.Conditional(), System.Xml.Dictionary, System.Xml.Xsl.Qil.QilPatternFactory.Int32(), and System.Xml.Xsl.Xslt.MatcherBuilder.MatchPattern().
Referenced by System.Xml.Xsl.Xslt.MatcherBuilder.BuildMatcher(), System.Xml.Xsl.Xslt.MatcherBuilder.MatchPatterns(), System.Xml.Xsl.Xslt.MatcherBuilder.MatchPatterns(), and System.Xml.Xsl.Xslt.MatcherBuilder.MatchPatternsWhosePriorityGreater().