Terraria: System.Xml.Serialization.XmlSchemaExporter.AddSchemaItem
AddSchemaItem()
void System.Xml.Serialization.XmlSchemaExporter.AddSchemaItem (XmlSchemaObject item, string ns, string referencingNs) inline private
Definition at line 291 of file XmlSchemaExporter.cs.
    {
        XmlSchema xmlSchema = _schemas[ns];
        if (xmlSchema == null)
        {
            xmlSchema = AddSchema(ns);
        }
        if (item is XmlSchemaElement)
        {
            XmlSchemaElement xmlSchemaElement = (XmlSchemaElement)item;
            if (xmlSchemaElement.Form == XmlSchemaForm.Unqualified)
            {
                throw new InvalidOperationException(System.SR.Format(System.SR.XmlIllegalForm, xmlSchemaElement.Name));
            }
            xmlSchemaElement.Form = XmlSchemaForm.None;
        }
        else if (item is XmlSchemaAttribute)
        {
            XmlSchemaAttribute xmlSchemaAttribute = (XmlSchemaAttribute)item;
            if (xmlSchemaAttribute.Form == XmlSchemaForm.Unqualified)
            {
                throw new InvalidOperationException(System.SR.Format(System.SR.XmlIllegalForm, xmlSchemaAttribute.Name));
            }
            xmlSchemaAttribute.Form = XmlSchemaForm.None;
        }
        xmlSchema.Items.Add(item);
        AddSchemaImport(ns, referencingNs);
    }
References System.Xml.Serialization.XmlSchemaExporter._schemas, System.Xml.Serialization.XmlSchemaExporter.AddSchema(), System.Xml.Serialization.XmlSchemaExporter.AddSchemaImport(), System.Xml.Dictionary, System.SR.Format(), System.item, and System.SR.XmlIllegalForm.
Referenced by System.Xml.Serialization.XmlSchemaExporter.ExportAnyType(), System.Xml.Serialization.XmlSchemaExporter.ExportArrayMapping(), System.Xml.Serialization.XmlSchemaExporter.ExportAttributeAccessor(), System.Xml.Serialization.XmlSchemaExporter.ExportElement(), System.Xml.Serialization.XmlSchemaExporter.ExportElementAccessor(), System.Xml.Serialization.XmlSchemaExporter.ExportEnumMapping(), System.Xml.Serialization.XmlSchemaExporter.ExportNonXsdPrimitiveMapping(), System.Xml.Serialization.XmlSchemaExporter.ExportStructMapping(), and System.Xml.Serialization.XmlSchemaExporter.ExportTypeMapping().