Terraria: System.Xml.Schema.SchemaElementDecl.CheckAttributes
CheckAttributes()
void System.Xml.Schema.SchemaElementDecl.CheckAttributes (Hashtable presence, bool standalone) inline package
Definition at line 254 of file SchemaElementDecl.cs.
    {
        foreach (SchemaAttDef value in _attdefs.Values)
        {
            if (presence[value.Name] == null)
            {
                if (value.Presence == Use.Required)
                {
                    throw new XmlSchemaException(System.SR.Sch_MissRequiredAttribute, value.Name.ToString());
                }
                if (standalone && value.IsDeclaredInExternal && (value.Presence == Use.Default || value.Presence == Use.Fixed))
                {
                    throw new XmlSchemaException(System.SR.Sch_StandAlone, string.Empty);
                }
            }
        }
    }
References System.Xml.Schema.SchemaElementDecl._attdefs, System.Xml.Schema.SchemaDeclBase.presence, System.SR.Sch_MissRequiredAttribute, System.SR.Sch_StandAlone, System.value, and System.Collections.Generic.Dictionary< TKey, TValue >.Values.
Referenced by System.Xml.Schema.DtdValidator.ValidateEndStartElement(), System.Xml.Schema.XdrValidator.ValidateEndStartElement(), and System.Xml.Schema.XsdValidator.ValidateEndStartElement().