Terraria: System.Threading.Tasks.Dataflow.Internal.TargetCore.ProcessMessagesLoopCore
ProcessMessagesLoopCore()
void System.Threading.Tasks.Dataflow.Internal.TargetCore< TInput >.ProcessMessagesLoopCore () inline private
Definition at line 289 of file TargetCore.cs.
    {
        KeyValuePair<TInput, long> messageWithId = default(KeyValuePair<TInput, long>);
        try
        {
            bool usesAsyncCompletion = UsesAsyncCompletion;
            bool flag = _boundingState != null && _boundingState.BoundedCapacity > 1;
            int num = 0;
            int num2 = 0;
            int actualMaxMessagesPerTask = _dataflowBlockOptions.ActualMaxMessagesPerTask;
            while (num < actualMaxMessagesPerTask && !CanceledOrFaulted)
            {
                if (flag && TryConsumePostponedMessage(forPostponementTransfer: true, out var result))
                {
                    lock (IncomingLock)
                    {
                        _boundingState.OutstandingTransfers--;
                        _messages.Enqueue(result);
                        ProcessAsyncIfNecessary();
                    }
                }
                if (usesAsyncCompletion)
                {
                    if (!TryGetNextMessageForNewAsyncOperation(out messageWithId))
                    {
                        break;
                    }
                }
                else if (!TryGetNextAvailableOrPostponedMessage(out messageWithId))
                {
                    if (_dataflowBlockOptions.MaxDegreeOfParallelism != 1 || num2 > 1)
                    {
                        break;
                    }
                    if (_keepAliveBanCounter > 0)
                    {
                        _keepAliveBanCounter--;
                        break;
                    }
                    num2 = 0;
                    if (!Common.TryKeepAliveUntil(_keepAlivePredicate, this, out messageWithId))
                    {
                        _keepAliveBanCounter = 1000;
                        break;
                    }
                }
                num++;
                num2++;
                _callAction(messageWithId);
            }
        }
        catch (Exception ex)
        {
            Common.StoreDataflowMessageValueIntoExceptionData(ex, messageWithId.Key);
            Complete(ex, dropPendingMessages: true, storeExceptionEvenIfAlreadyCompleting: true);
        }
        finally
        {
            lock (IncomingLock)
            {
                _numberOfOutstandingOperations--;
                if (UsesAsyncCompletion)
                {
                    _numberOfOutstandingServiceTasks--;
                }
                ProcessAsyncIfNecessary(repeat: true);
                CompleteBlockIfPossible();
            }
        }
    }
References System.Threading.Tasks.Dataflow.Internal.TargetCore< TInput >._boundingState, System.Threading.Tasks.Dataflow.Internal.TargetCore< TInput >._callAction, System.Threading.Tasks.Dataflow.Internal.TargetCore< TInput >._dataflowBlockOptions, System.Threading.Tasks.Dataflow.Internal.TargetCore< TInput >._keepAliveBanCounter, System.Threading.Tasks.Dataflow.Internal.TargetCore< TInput >._keepAlivePredicate, System.Threading.Tasks.Dataflow.Internal.TargetCore< TInput >._messages, System.Threading.Tasks.Dataflow.Internal.TargetCore< TInput >._numberOfOutstandingOperations, System.Threading.Tasks.Dataflow.Internal.TargetCore< TInput >._numberOfOutstandingServiceTasks, System.Threading.Tasks.Dataflow.DataflowBlockOptions.ActualMaxMessagesPerTask, System.Threading.Tasks.Dataflow.Internal.TargetCore< TInput >.CanceledOrFaulted, System.Threading.Tasks.Dataflow.Internal.TargetCore< TInput >.Complete(), System.Threading.Tasks.Dataflow.Internal.TargetCore< TInput >.CompleteBlockIfPossible(), System.Threading.Tasks.Dataflow.Internal.TargetCore< TInput >.IncomingLock, System.Threading.Tasks.Dataflow.ExecutionDataflowBlockOptions.MaxDegreeOfParallelism, System.Threading.Tasks.Dataflow.Internal.TargetCore< TInput >.ProcessAsyncIfNecessary(), System.Threading.Tasks.Dataflow.Internal.TargetCore< TInput >.TryConsumePostponedMessage(), System.Threading.Tasks.Dataflow.Internal.TargetCore< TInput >.TryGetNextAvailableOrPostponedMessage(), System.Threading.Tasks.Dataflow.Internal.TargetCore< TInput >.TryGetNextMessageForNewAsyncOperation(), and System.Threading.Tasks.Dataflow.Internal.TargetCore< TInput >.UsesAsyncCompletion.