Terraria: System.Threading.Tasks.Dataflow.Internal.TargetCore.TryGetNextAvailableOrPostponedMessage
TryGetNextAvailableOrPostponedMessage()
bool System.Threading.Tasks.Dataflow.Internal.TargetCore< TInput >.TryGetNextAvailableOrPostponedMessage (out KeyValuePair< TInput, long > messageWithId) inline private
Definition at line 393 of file TargetCore.cs.
    {
        if (_messages.TryDequeue(out messageWithId))
        {
            return true;
        }
        if (_boundingState != null && TryConsumePostponedMessage(forPostponementTransfer: false, out messageWithId))
        {
            return true;
        }
        messageWithId = default(KeyValuePair<TInput, long>);
        return false;
    }
References System.Threading.Tasks.Dataflow.Internal.TargetCore< TInput >._boundingState, System.Threading.Tasks.Dataflow.Internal.TargetCore< TInput >._messages, and System.Threading.Tasks.Dataflow.Internal.TargetCore< TInput >.TryConsumePostponedMessage().
Referenced by System.Threading.Tasks.Dataflow.Internal.TargetCore< TInput >.ProcessMessagesLoopCore(), and System.Threading.Tasks.Dataflow.Internal.TargetCore< TInput >.TryGetNextMessageForNewAsyncOperation().