Terraria: System.Threading.Tasks.Dataflow.Internal.TargetCore.Complete
Complete()
void System.Threading.Tasks.Dataflow.Internal.TargetCore< TInput >.Complete (Exception exception, bool dropPendingMessages, bool storeExceptionEvenIfAlreadyCompleting = false, bool unwrapInnerExceptions = false, bool revertProcessingState = false) inline package
Definition at line 155 of file TargetCore.cs.
    {
        lock (IncomingLock)
        {
            if (exception != null && (!_decliningPermanently || storeExceptionEvenIfAlreadyCompleting))
            {
                Common.AddException(ref _exceptions, exception, unwrapInnerExceptions);
            }
            if (dropPendingMessages)
            {
                KeyValuePair<TInput, long> result;
                while (_messages.TryDequeue(out result))
                {
                }
            }
            if (revertProcessingState)
            {
                _numberOfOutstandingOperations--;
                if (UsesAsyncCompletion)
                {
                    _numberOfOutstandingServiceTasks--;
                }
            }
            _decliningPermanently = true;
            CompleteBlockIfPossible();
        }
    }
References System.Threading.Tasks.Dataflow.Internal.TargetCore< TInput >._decliningPermanently, System.Threading.Tasks.Dataflow.Internal.TargetCore< TInput >._exceptions, System.Threading.Tasks.Dataflow.Internal.TargetCore< TInput >._messages, System.Threading.Tasks.Dataflow.Internal.TargetCore< TInput >._numberOfOutstandingOperations, System.Threading.Tasks.Dataflow.Internal.TargetCore< TInput >._numberOfOutstandingServiceTasks, System.Threading.Tasks.Dataflow.Internal.Common.AddException(), System.Threading.Tasks.Dataflow.Internal.TargetCore< TInput >.CompleteBlockIfPossible(), System.exception, System.Threading.Tasks.Dataflow.Internal.TargetCore< TInput >.IncomingLock, and System.Threading.Tasks.Dataflow.Internal.TargetCore< TInput >.UsesAsyncCompletion.
Referenced by System.Threading.Tasks.Dataflow.Internal.TargetCore< TInput >.ProcessAsyncIfNecessary_Slow(), and System.Threading.Tasks.Dataflow.Internal.TargetCore< TInput >.ProcessMessagesLoopCore().