Terraria: System.Threading.Tasks.Dataflow.Internal.TargetCore.CompleteBlockIfPossible
CompleteBlockIfPossible()
void System.Threading.Tasks.Dataflow.Internal.TargetCore< TInput >.CompleteBlockIfPossible () inline private
Definition at line 470 of file TargetCore.cs.
    {
        if ((_decliningPermanently && _messages.IsEmpty) || CanceledOrFaulted)
        {
            CompleteBlockIfPossible_Slow();
        }
    }
References System.Threading.Tasks.Dataflow.Internal.TargetCore< TInput >._decliningPermanently, System.Threading.Tasks.Dataflow.Internal.TargetCore< TInput >._messages, System.Threading.Tasks.Dataflow.Internal.TargetCore< TInput >.CanceledOrFaulted, and System.Threading.Tasks.Dataflow.Internal.TargetCore< TInput >.CompleteBlockIfPossible_Slow().
Referenced by System.Threading.Tasks.Dataflow.Internal.TargetCore< TInput >.ChangeBoundingCount(), System.Threading.Tasks.Dataflow.Internal.TargetCore< TInput >.Complete(), System.Threading.Tasks.Dataflow.Internal.TargetCore< TInput >.OfferMessage(), System.Threading.Tasks.Dataflow.Internal.TargetCore< TInput >.ProcessMessagesLoopCore(), and System.Threading.Tasks.Dataflow.Internal.TargetCore< TInput >.SignalOneAsyncMessageCompleted().