Terraria: System.Threading.Tasks.Dataflow.Internal.TargetCore.ProcessAsyncIfNecessary_Slow
ProcessAsyncIfNecessary_Slow()
void System.Threading.Tasks.Dataflow.Internal.TargetCore< TInput >.ProcessAsyncIfNecessary_Slow (bool repeat) inline private
Definition at line 259 of file TargetCore.cs.
    {
        if ((_messages.IsEmpty && (_decliningPermanently || _boundingState == null || !_boundingState.CountIsLessThanBound || _boundingState.PostponedMessages.Count <= 0)) || CanceledOrFaulted)
        {
            return;
        }
        _numberOfOutstandingOperations++;
        if (UsesAsyncCompletion)
        {
            _numberOfOutstandingServiceTasks++;
        }
        Task task = new Task(delegate(object thisTargetCore)
        {
            ((TargetCore<TInput>)thisTargetCore).ProcessMessagesLoopCore();
        }, this, Common.GetCreationOptionsForTask(repeat));
        DataflowEtwProvider log = DataflowEtwProvider.Log;
        if (log.IsEnabled())
        {
            log.TaskLaunchedForMessageHandling(_owningTarget, task, DataflowEtwProvider.TaskLaunchedReason.ProcessingInputMessages, _messages.Count + ((_boundingState != null) ? _boundingState.PostponedMessages.Count : 0));
        }
        Exception ex = Common.StartTaskSafe(task, _dataflowBlockOptions.TaskScheduler);
        if (ex != null)
        {
            Task.Factory.StartNew(delegate(object exc)
            {
                Complete((Exception)exc, dropPendingMessages: true, storeExceptionEvenIfAlreadyCompleting: true, unwrapInnerExceptions: false, revertProcessingState: true);
            }, ex, CancellationToken.None, Common.GetCreationOptionsForTask(), TaskScheduler.Default);
        }
    }
References System.Threading.Tasks.Dataflow.Internal.TargetCore< TInput >._boundingState, System.Threading.Tasks.Dataflow.Internal.TargetCore< TInput >._dataflowBlockOptions, System.Threading.Tasks.Dataflow.Internal.TargetCore< TInput >._decliningPermanently, System.Threading.Tasks.Dataflow.Internal.TargetCore< TInput >._messages, System.Threading.Tasks.Dataflow.Internal.TargetCore< TInput >._numberOfOutstandingOperations, System.Threading.Tasks.Dataflow.Internal.TargetCore< TInput >._numberOfOutstandingServiceTasks, System.Threading.Tasks.Dataflow.Internal.TargetCore< TInput >._owningTarget, System.Threading.Tasks.Dataflow.Internal.TargetCore< TInput >.CanceledOrFaulted, System.Threading.Tasks.Dataflow.Internal.TargetCore< TInput >.Complete(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Threading.Tasks.TaskScheduler.Default, System.Threading.Tasks.Task< TResult >.Factory, System.Threading.Tasks.Dataflow.Internal.Common.GetCreationOptionsForTask(), System.Threading.Tasks.Dataflow.Internal.DataflowEtwProvider.Log, System.Threading.CancellationToken.None, System.Threading.Tasks.Dataflow.Internal.Common.StartTaskSafe(), System.task, System.Threading.Tasks.Dataflow.DataflowBlockOptions.TaskScheduler, and System.Threading.Tasks.Dataflow.Internal.TargetCore< TInput >.UsesAsyncCompletion.
Referenced by System.Threading.Tasks.Dataflow.Internal.TargetCore< TInput >.ProcessAsyncIfNecessary().