Terraria: System.Threading.Tasks.Dataflow.Internal.TargetCore.ChangeBoundingCount
ChangeBoundingCount()
void System.Threading.Tasks.Dataflow.Internal.TargetCore< TInput >.ChangeBoundingCount (int count) inline package
Definition at line 521 of file TargetCore.cs.
    {
        if (_boundingState != null)
        {
            lock (IncomingLock)
            {
                _boundingState.CurrentCount += count;
                ProcessAsyncIfNecessary();
                CompleteBlockIfPossible();
            }
        }
    }
References System.Threading.Tasks.Dataflow.Internal.TargetCore< TInput >._boundingState, System.Threading.Tasks.Dataflow.Internal.TargetCore< TInput >.CompleteBlockIfPossible(), System.count, System.Threading.Tasks.Dataflow.Internal.TargetCore< TInput >.IncomingLock, and System.Threading.Tasks.Dataflow.Internal.TargetCore< TInput >.ProcessAsyncIfNecessary().
Referenced by System.Threading.Tasks.Dataflow.Internal.TargetCore< TInput >.TryConsumePostponedMessage().