Terraria: System.Threading.Tasks.Dataflow.Internal.TargetCore.TryConsumePostponedMessage
TryConsumePostponedMessage()
bool System.Threading.Tasks.Dataflow.Internal.TargetCore< TInput >.TryConsumePostponedMessage (bool forPostponementTransfer, out KeyValuePair< TInput, long > result) inline private
Definition at line 407 of file TargetCore.cs.
    {
        bool flag = false;
        long num = -1L;
        while (true)
        {
            KeyValuePair<ISourceBlock<TInput>, DataflowMessageHeader> item;
            lock (IncomingLock)
            {
                if (_decliningPermanently)
                {
                    break;
                }
                if (!forPostponementTransfer && _messages.TryDequeue(out result))
                {
                    return true;
                }
                if (!_boundingState.CountIsLessThanBound || !_boundingState.PostponedMessages.TryPop(out item))
                {
                    if (flag)
                    {
                        flag = false;
                        _boundingState.CurrentCount--;
                    }
                    break;
                }
                if (!flag)
                {
                    flag = true;
                    num = _nextAvailableInputMessageId.Value++;
                    _boundingState.CurrentCount++;
                    if (forPostponementTransfer)
                    {
                        _boundingState.OutstandingTransfers++;
                    }
                }
                goto IL_00d1;
            }
            IL_00d1:
            bool messageConsumed;
            TInput key = item.Key.ConsumeMessage(item.Value, _owningTarget, out messageConsumed);
            if (messageConsumed)
            {
                result = new KeyValuePair<TInput, long>(key, num);
                return true;
            }
            if (forPostponementTransfer)
            {
                _boundingState.OutstandingTransfers--;
            }
        }
        if (_reorderingBuffer != null && num != -1)
        {
            _reorderingBuffer.IgnoreItem(num);
        }
        if (flag)
        {
            ChangeBoundingCount(-1);
        }
        result = default(KeyValuePair<TInput, long>);
        return false;
    }
References System.Threading.Tasks.Dataflow.Internal.TargetCore< TInput >._boundingState, System.Threading.Tasks.Dataflow.Internal.TargetCore< TInput >._decliningPermanently, System.Threading.Tasks.Dataflow.Internal.TargetCore< TInput >._messages, System.Threading.Tasks.Dataflow.Internal.TargetCore< TInput >._nextAvailableInputMessageId, System.Threading.Tasks.Dataflow.Internal.TargetCore< TInput >._owningTarget, System.Threading.Tasks.Dataflow.Internal.TargetCore< TInput >._reorderingBuffer, System.Threading.Tasks.Dataflow.Internal.TargetCore< TInput >.ChangeBoundingCount(), System.Threading.Tasks.Dataflow.Internal.IReorderingBuffer.IgnoreItem(), System.Threading.Tasks.Dataflow.Internal.TargetCore< TInput >.IncomingLock, System.item, System.key, System.L, and System.Threading.Tasks.Dataflow.Internal.PaddedInt64.Value.
Referenced by System.Threading.Tasks.Dataflow.Internal.TargetCore< TInput >.ProcessMessagesLoopCore(), and System.Threading.Tasks.Dataflow.Internal.TargetCore< TInput >.TryGetNextAvailableOrPostponedMessage().