Terraria: System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitNe
VisitNe()
override QilNode System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitNe (QilBinary local0) inline protected virtual
Reimplemented from System.Xml.Xsl.Qil.QilVisitor.
Definition at line 1007 of file XmlILOptimizerVisitor.cs.
    {
        QilNode qilNode = local0[0];
        QilNode qilNode2 = local0[1];
        if (this[XmlILOptimization.FoldNone] && (object)qilNode.XmlType == XmlQueryTypeFactory.None && AllowReplace(XmlILOptimization.FoldNone, local0))
        {
            return Replace(XmlILOptimization.FoldNone, local0, VisitNop(f.Nop(qilNode)));
        }
        if (this[XmlILOptimization.FoldNone] && (object)qilNode2.XmlType == XmlQueryTypeFactory.None && AllowReplace(XmlILOptimization.FoldNone, local0))
        {
            return Replace(XmlILOptimization.FoldNone, local0, VisitNop(f.Nop(qilNode2)));
        }
        if (this[XmlILOptimization.EliminateNe] && IsLiteral(qilNode) && IsLiteral(qilNode2) && AllowReplace(XmlILOptimization.EliminateNe, local0))
        {
            return Replace(XmlILOptimization.EliminateNe, local0, FoldComparison(QilNodeType.Ne, qilNode, qilNode2));
        }
        if (this[XmlILOptimization.NormalizeNeLiteral] && IsLiteral(qilNode) && !IsLiteral(qilNode2) && AllowReplace(XmlILOptimization.NormalizeNeLiteral, local0))
        {
            return Replace(XmlILOptimization.NormalizeNeLiteral, local0, VisitNe(f.Ne(qilNode2, qilNode)));
        }
        if (this[XmlILOptimization.NormalizeXsltConvertNe] && qilNode.NodeType == QilNodeType.XsltConvert)
        {
            QilNode qilNode3 = qilNode[0];
            QilNode qilNode4 = qilNode[1];
            if (qilNode4.NodeType == QilNodeType.LiteralType)
            {
                XmlQueryType typ = (XmlQueryType)((QilLiteral)qilNode4).Value;
                if (IsPrimitiveNumeric(qilNode3.XmlType) && IsPrimitiveNumeric(typ) && IsLiteral(qilNode2) && CanFoldXsltConvertNonLossy(qilNode2, qilNode3.XmlType) && AllowReplace(XmlILOptimization.NormalizeXsltConvertNe, local0))
                {
                    return Replace(XmlILOptimization.NormalizeXsltConvertNe, local0, VisitNe(f.Ne(qilNode3, FoldXsltConvert(qilNode2, qilNode3.XmlType))));
                }
            }
        }
        if (this[XmlILOptimization.NormalizeIdNe] && qilNode.NodeType == QilNodeType.XsltGenerateId)
        {
            QilNode qilNode5 = qilNode[0];
            if (qilNode5.XmlType.IsSingleton && qilNode2.NodeType == QilNodeType.XsltGenerateId)
            {
                QilNode qilNode6 = qilNode2[0];
                if (qilNode6.XmlType.IsSingleton && AllowReplace(XmlILOptimization.NormalizeIdNe, local0))
                {
                    return Replace(XmlILOptimization.NormalizeIdNe, local0, VisitNot(f.Not(VisitIs(f.Is(qilNode5, qilNode6)))));
                }
            }
        }
        if (this[XmlILOptimization.NormalizeLengthNe] && qilNode.NodeType == QilNodeType.Length)
        {
            QilNode child = qilNode[0];
            if (qilNode2.NodeType == QilNodeType.LiteralInt32 && (int)((QilLiteral)qilNode2).Value == 0 && AllowReplace(XmlILOptimization.NormalizeLengthNe, local0))
            {
                return Replace(XmlILOptimization.NormalizeLengthNe, local0, VisitNot(f.Not(VisitIsEmpty(f.IsEmpty(child)))));
            }
        }
        if (this[XmlILOptimization.AnnotateMaxLengthNe] && qilNode.NodeType == QilNodeType.Length && qilNode2.NodeType == QilNodeType.LiteralInt32)
        {
            int num = (int)((QilLiteral)qilNode2).Value;
            if (AllowReplace(XmlILOptimization.AnnotateMaxLengthNe, local0))
            {
                OptimizerPatterns.Write(qilNode).AddPattern(OptimizerPatternName.MaxPosition);
                OptimizerPatterns.Write(qilNode).AddArgument(OptimizerPatternArgument.ElementQName, num);
            }
        }
        return NoReplace(local0);
    }
References System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.AllowReplace(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.CanFoldXsltConvertNonLossy(), System.Xml.Dictionary, System.Xml.Xsl.Qil.QilReplaceVisitor.f, System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.FoldComparison(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.FoldXsltConvert(), System.Xml.Xsl.Qil.QilFactory.Is(), System.Xml.Xsl.Qil.QilFactory.IsEmpty(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.IsLiteral(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.IsPrimitiveNumeric(), System.Xml.Xsl.Qil.QilFactory.Ne(), System.Xml.Xsl.XmlQueryTypeFactory.None, System.Xml.Xsl.Qil.QilFactory.Nop(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.NoReplace(), System.Xml.Xsl.Qil.QilFactory.Not(), System.Xml.Replace, System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitIs(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitIsEmpty(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitNe(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitNop(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitNot(), and System.Xml.Xsl.IlGen.OptimizerPatterns.Write().
Referenced by System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitNe().