Terraria: System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.FoldXsltConvert
FoldXsltConvert()
QilNode System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.FoldXsltConvert (QilNode ndLiteral, XmlQueryType typTarget) inline private
Definition at line 3019 of file XmlILOptimizerVisitor.cs.
    {
        try
        {
            if (typTarget.IsAtomicValue)
            {
                XmlAtomicValue value = new XmlAtomicValue(ndLiteral.XmlType.SchemaType, ExtractLiteralValue(ndLiteral));
                value = XsltConvert.ConvertToType(value, typTarget);
                if (typTarget == XmlQueryTypeFactory.StringX)
                {
                    return f.LiteralString(value.Value);
                }
                if (typTarget == XmlQueryTypeFactory.IntX)
                {
                    return f.LiteralInt32(value.ValueAsInt);
                }
                if (typTarget == XmlQueryTypeFactory.IntegerX)
                {
                    return f.LiteralInt64(value.ValueAsLong);
                }
                if (typTarget == XmlQueryTypeFactory.DecimalX)
                {
                    return f.LiteralDecimal((decimal)value.ValueAs(XsltConvert.DecimalType));
                }
                if (typTarget == XmlQueryTypeFactory.DoubleX)
                {
                    return f.LiteralDouble(value.ValueAsDouble);
                }
                if (typTarget == XmlQueryTypeFactory.BooleanX)
                {
                    return value.ValueAsBoolean ? f.True() : f.False();
                }
            }
        }
        catch (OverflowException)
        {
        }
        catch (FormatException)
        {
        }
        return f.XsltConvert(ndLiteral, typTarget);
    }
References System.Xml.Xsl.XmlQueryTypeFactory.BooleanX, System.Xml.Xsl.Runtime.XsltConvert.ConvertToType(), System.Xml.Xsl.Runtime.XsltConvert.DecimalType, System.Xml.Xsl.XmlQueryTypeFactory.DecimalX, System.Xml.Dictionary, System.Xml.Xsl.XmlQueryTypeFactory.DoubleX, System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.ExtractLiteralValue(), System.Xml.Xsl.Qil.QilReplaceVisitor.f, System.Xml.Xsl.Qil.QilFactory.False(), System.Xml.Xsl.XmlQueryTypeFactory.IntegerX, System.Xml.Xsl.XmlQueryTypeFactory.IntX, System.Xml.Xsl.Qil.QilFactory.LiteralDecimal(), System.Xml.Xsl.Qil.QilFactory.LiteralDouble(), System.Xml.Xsl.Qil.QilFactory.LiteralInt32(), System.Xml.Xsl.Qil.QilFactory.LiteralInt64(), System.Xml.Xsl.Qil.QilFactory.LiteralString(), System.Xml.Xsl.XmlQueryTypeFactory.StringX, System.Xml.Xsl.Qil.QilFactory.True(), System.value, and System.Xml.Xsl.Qil.QilFactory.XsltConvert().
Referenced by System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.CanFoldXsltConvert(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.CanFoldXsltConvertNonLossy(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitEq(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitGe(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitGt(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitLe(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitLt(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitNe(), and System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitXsltConvert().