Terraria: System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.Visit
Visit()
override QilNode System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.Visit (QilNode nd) inline protected virtual
Reimplemented from System.Xml.Xsl.Qil.QilVisitor.
Definition at line 213 of file XmlILOptimizerVisitor.cs.
    {
        if (nd != null && this[XmlILOptimization.EliminateNamespaceDecl])
        {
            switch (nd.NodeType)
            {
            case QilNodeType.QilExpression:
                _nmspAnalyzer.Analyze(((QilExpression)nd).Root, defaultNmspInScope: true);
                break;
            case QilNodeType.ElementCtor:
                if (!XmlILConstructInfo.Read(nd).IsNamespaceInScope)
                {
                    _nmspAnalyzer.Analyze(nd, defaultNmspInScope: false);
                }
                break;
            case QilNodeType.DocumentCtor:
                _nmspAnalyzer.Analyze(nd, defaultNmspInScope: true);
                break;
            }
        }
        return base.Visit(nd);
    }
References System.Xml.Xsl.IlGen.XmlILOptimizerVisitor._nmspAnalyzer, System.Xml.Xsl.IlGen.XmlILNamespaceAnalyzer.Analyze(), System.Xml.Xsl.IlGen.XmlILConstructInfo.Read(), and System.Xml.Root.
Referenced by System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.Optimize(), and System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.Subs().