Terraria: System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitFilter
VisitFilter()
override QilNode System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitFilter (QilLoop local0) inline protected virtual
Reimplemented from System.Xml.Xsl.Qil.QilVisitor.
Definition at line 1617 of file XmlILOptimizerVisitor.cs.
    {
        QilNode qilNode = local0[0];
        QilNode qilNode2 = local0[1];
        if (this[XmlILOptimization.FoldNone] && (object)qilNode.XmlType == XmlQueryTypeFactory.None && AllowReplace(XmlILOptimization.FoldNone, local0))
        {
            return Replace(XmlILOptimization.FoldNone, local0, VisitNop(f.Nop(qilNode[0])));
        }
        if (this[XmlILOptimization.FoldNone] && (object)qilNode2.XmlType == XmlQueryTypeFactory.None && AllowReplace(XmlILOptimization.FoldNone, local0))
        {
            return Replace(XmlILOptimization.FoldNone, local0, VisitLoop(f.Loop(qilNode, qilNode2)));
        }
        if (this[XmlILOptimization.EliminateFilter] && !OptimizerPatterns.Read(qilNode).MatchesPattern(OptimizerPatternName.MaybeSideEffects) && qilNode2.NodeType == QilNodeType.False && AllowReplace(XmlILOptimization.EliminateFilter, local0))
        {
            return Replace(XmlILOptimization.EliminateFilter, local0, VisitSequence(f.Sequence()));
        }
        if (this[XmlILOptimization.EliminateFilter] && qilNode2.NodeType == QilNodeType.True && AllowReplace(XmlILOptimization.EliminateFilter, local0))
        {
            return Replace(XmlILOptimization.EliminateFilter, local0, qilNode[0]);
        }
        if (this[XmlILOptimization.NormalizeAttribute] && qilNode.NodeType == QilNodeType.For)
        {
            QilNode qilNode3 = qilNode[0];
            if (qilNode3.NodeType == QilNodeType.Content)
            {
                QilNode left = qilNode3[0];
                if (qilNode2.NodeType == QilNodeType.And)
                {
                    QilNode qilNode4 = qilNode2[0];
                    QilNode qilNode5 = qilNode2[1];
                    if (qilNode4.NodeType == QilNodeType.IsType)
                    {
                        QilNode qilNode6 = qilNode4[0];
                        QilNode qilNode7 = qilNode4[1];
                        if (qilNode6 == qilNode && qilNode7.NodeType == QilNodeType.LiteralType)
{
                            XmlQueryType xmlQueryType = (XmlQueryType)((QilLiteral)qilNode7).Value;
                            if (xmlQueryType == XmlQueryTypeFactory.Attribute && qilNode5.NodeType == QilNodeType.Eq)
{
                                QilNode qilNode8 = qilNode5[0];
                                QilNode qilNode9 = qilNode5[1];
                                if (qilNode8.NodeType == QilNodeType.NameOf)
{
                                    QilNode qilNode10 = qilNode8[0];
                                    if (qilNode10 == qilNode && qilNode9.NodeType == QilNodeType.LiteralQName && AllowReplace(XmlILOptimization.NormalizeAttribute, local0))
{
                                        return Replace(XmlILOptimization.NormalizeAttribute, local0, VisitAttribute(f.Attribute(left, qilNode9)));
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
        if (this[XmlILOptimization.CommuteFilterLoop] && qilNode.NodeType == QilNodeType.For)
        {
            QilNode qilNode11 = qilNode[0];
            if (qilNode11.NodeType == QilNodeType.Loop)
            {
                QilNode variable = qilNode11[0];
                QilNode binding = qilNode11[1];
                if (NonPositional(qilNode2, qilNode) && !IsDocOrderDistinct(qilNode11) && AllowReplace(XmlILOptimization.CommuteFilterLoop, local0))
                {
                    QilNode qilNode12 = VisitFor(f.For(binding));
                    return Replace(XmlILOptimization.CommuteFilterLoop, local0, VisitLoop(f.Loop(variable, VisitFilter(f.Filter(qilNode12, Subs(qilNode2, qilNode, qilNode12))))));
                }
            }
        }
        if (this[XmlILOptimization.NormalizeLoopInvariant] && !OptimizerPatterns.Read(qilNode).MatchesPattern(OptimizerPatternName.MaybeSideEffects) && qilNode[0].NodeType != QilNodeType.OptimizeBarrier && !DependsOn(qilNode2, qilNode) && !OptimizerPatterns.Read(qilNode2).MatchesPattern(OptimizerPatternName.MaybeSideEffects) && AllowReplace(XmlILOptimization.NormalizeLoopInvariant, local0))
        {
            return Replace(XmlILOptimization.NormalizeLoopInvariant, local0, VisitConditional(f.Conditional(qilNode2, qilNode[0], VisitSequence(f.Sequence()))));
        }
        if (this[XmlILOptimization.AnnotateMaxPositionEq] && qilNode2.NodeType == QilNodeType.Eq)
        {
            QilNode qilNode13 = qilNode2[0];
            QilNode qilNode14 = qilNode2[1];
            if (qilNode13.NodeType == QilNodeType.PositionOf)
            {
                QilNode qilNode15 = qilNode13[0];
                if (qilNode15 == qilNode && qilNode14.NodeType == QilNodeType.LiteralInt32)
                {
                    int num = (int)((QilLiteral)qilNode14).Value;
                    if (AllowReplace(XmlILOptimization.AnnotateMaxPositionEq, local0))
                    {
                        OptimizerPatterns.Write(qilNode).AddPattern(OptimizerPatternName.MaxPosition);
                        OptimizerPatterns.Write(qilNode).AddArgument(OptimizerPatternArgument.ElementQName, num);
                    }
                }
            }
        }
        if (this[XmlILOptimization.AnnotateMaxPositionLe] && qilNode2.NodeType == QilNodeType.Le)
        {
            QilNode qilNode16 = qilNode2[0];
            QilNode qilNode17 = qilNode2[1];
            if (qilNode16.NodeType == QilNodeType.PositionOf)
            {
                QilNode qilNode18 = qilNode16[0];
                if (qilNode18 == qilNode && qilNode17.NodeType == QilNodeType.LiteralInt32)
                {
                    int num2 = (int)((QilLiteral)qilNode17).Value;
                    if (AllowReplace(XmlILOptimization.AnnotateMaxPositionLe, local0))
                    {
                        OptimizerPatterns.Write(qilNode).AddPattern(OptimizerPatternName.MaxPosition);
                        OptimizerPatterns.Write(qilNode).AddArgument(OptimizerPatternArgument.ElementQName, num2);
                    }
                }
            }
        }
        if (this[XmlILOptimization.AnnotateMaxPositionLt] && qilNode2.NodeType == QilNodeType.Lt)
        {
            QilNode qilNode19 = qilNode2[0];
            QilNode qilNode20 = qilNode2[1];
            if (qilNode19.NodeType == QilNodeType.PositionOf)
            {
                QilNode qilNode21 = qilNode19[0];
                if (qilNode21 == qilNode && qilNode20.NodeType == QilNodeType.LiteralInt32)
                {
                    int num3 = (int)((QilLiteral)qilNode20).Value;
                    if (AllowReplace(XmlILOptimization.AnnotateMaxPositionLt, local0))
                    {
                        OptimizerPatterns.Write(qilNode).AddPattern(OptimizerPatternName.MaxPosition);
                        OptimizerPatterns.Write(qilNode).AddArgument(OptimizerPatternArgument.ElementQName, num3 - 1);
                    }
                }
            }
        }
        if (this[XmlILOptimization.AnnotateFilter] && qilNode.NodeType == QilNodeType.For)
        {
            QilNode ndSrc = qilNode[0];
            if (AllowReplace(XmlILOptimization.AnnotateFilter, local0))
            {
                OptimizerPatterns.Inherit(ndSrc, local0, OptimizerPatternName.Step);
                OptimizerPatterns.Inherit(ndSrc, local0, OptimizerPatternName.IsDocOrderDistinct);
                OptimizerPatterns.Inherit(ndSrc, local0, OptimizerPatternName.SameDepth);
            }
        }
        if (this[XmlILOptimization.AnnotateFilterElements] && qilNode.NodeType == QilNodeType.For)
        {
            QilNode nd = qilNode[0];
            if (OptimizerPatterns.Read(nd).MatchesPattern(OptimizerPatternName.Axis) && qilNode2.NodeType == QilNodeType.And)
            {
                QilNode qilNode22 = qilNode2[0];
                QilNode qilNode23 = qilNode2[1];
                if (qilNode22.NodeType == QilNodeType.IsType)
                {
                    QilNode qilNode24 = qilNode22[0];
                    QilNode qilNode25 = qilNode22[1];
                    if (qilNode24 == qilNode && qilNode25.NodeType == QilNodeType.LiteralType)
                    {
                        XmlQueryType xmlQueryType2 = (XmlQueryType)((QilLiteral)qilNode25).Value;
                        if (xmlQueryType2 == XmlQueryTypeFactory.Element && qilNode23.NodeType == QilNodeType.Eq)
{
                            QilNode qilNode26 = qilNode23[0];
                            QilNode qilNode27 = qilNode23[1];
                            if (qilNode26.NodeType == QilNodeType.NameOf)
{
                                QilNode qilNode28 = qilNode26[0];
                                if (qilNode28 == qilNode && qilNode27.NodeType == QilNodeType.LiteralQName && AllowReplace(XmlILOptimization.AnnotateFilterElements, local0))
{
                                    OptimizerPatterns.Write(local0).AddPattern(OptimizerPatternName.FilterElements);
                                    OptimizerPatterns.Write(local0).AddArgument(OptimizerPatternArgument.ElementQName, qilNode27);
                                }
                            }
                        }
                    }
                }
            }
        }
        if (this[XmlILOptimization.AnnotateFilterContentKind] && qilNode.NodeType == QilNodeType.For)
        {
            QilNode nd2 = qilNode[0];
            if (OptimizerPatterns.Read(nd2).MatchesPattern(OptimizerPatternName.Axis) && qilNode2.NodeType == QilNodeType.IsType)
            {
                QilNode qilNode29 = qilNode2[0];
                QilNode qilNode30 = qilNode2[1];
                if (qilNode29 == qilNode && qilNode30.NodeType == QilNodeType.LiteralType)
                {
                    XmlQueryType xmlQueryType3 = (XmlQueryType)((QilLiteral)qilNode30).Value;
                    if (MatchesContentTest(xmlQueryType3) && AllowReplace(XmlILOptimization.AnnotateFilterContentKind, local0))
                    {
                        OptimizerPatterns.Write(local0).AddPattern(OptimizerPatternName.FilterContentKind);
                        OptimizerPatterns.Write(local0).AddArgument(OptimizerPatternArgument.ElementQName, xmlQueryType3);
                    }
                }
            }
        }
        if (this[XmlILOptimization.AnnotateFilterAttributeKind] && qilNode.NodeType == QilNodeType.For)
        {
            QilNode qilNode31 = qilNode[0];
            if (qilNode31.NodeType == QilNodeType.Content && qilNode2.NodeType == QilNodeType.IsType)
            {
                QilNode qilNode32 = qilNode2[0];
                QilNode qilNode33 = qilNode2[1];
                if (qilNode32 == qilNode && qilNode33.NodeType == QilNodeType.LiteralType)
                {
                    XmlQueryType xmlQueryType4 = (XmlQueryType)((QilLiteral)qilNode33).Value;
                    if (xmlQueryType4 == XmlQueryTypeFactory.Attribute && AllowReplace(XmlILOptimization.AnnotateFilterAttributeKind, local0))
                    {
                        OptimizerPatterns.Write(local0).AddPattern(OptimizerPatternName.FilterAttributeKind);
                    }
                }
            }
        }
        return NoReplace(local0);
    }
References System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.AllowReplace(), System.Xml.Xsl.Qil.QilFactory.Attribute(), System.Xml.Xsl.XmlQueryTypeFactory.Attribute, System.Xml.Xsl.Qil.QilFactory.Conditional(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.DependsOn(), System.Xml.Dictionary, System.Xml.Xsl.XmlQueryTypeFactory.Element, System.Xml.Xsl.Qil.QilReplaceVisitor.f, System.Xml.Xsl.Qil.QilFactory.Filter(), System.Xml.Xsl.Qil.QilFactory.For(), System.Xml.Xsl.IlGen.OptimizerPatterns.Inherit(), System.Xml.Xsl.IlGen.IsDocOrderDistinct, System.Xml.Xsl.Qil.QilFactory.Loop(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.MatchesContentTest(), System.Xml.Xsl.XmlQueryTypeFactory.None, System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.NonPositional(), System.Xml.Xsl.Qil.QilFactory.Nop(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.NoReplace(), System.Xml.Xsl.IlGen.OptimizerPatterns.Read(), System.Xml.Replace, System.Xml.Xsl.Qil.QilFactory.Sequence(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.Subs(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitAttribute(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitConditional(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitFilter(), System.Xml.Xsl.Qil.QilPatternVisitor.VisitFor(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitLoop(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitNop(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitSequence(), and System.Xml.Xsl.IlGen.OptimizerPatterns.Write().
Referenced by System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitDocOrderDistinct(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitEq(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitFilter(), and System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitLoop().