Terraria: System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitFunction
VisitFunction()
override QilNode System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitFunction (QilFunction local0) inline protected virtual
Reimplemented from System.Xml.Xsl.Qil.QilVisitor.
Definition at line 2029 of file XmlILOptimizerVisitor.cs.
    {
        QilNode qilNode = local0[0];
        QilNode qilNode2 = local0[1];
        QilNode qilNode3 = local0[2];
        XmlQueryType xmlType = local0.XmlType;
        if (local0.XmlType.IsSubtypeOf(XmlQueryTypeFactory.NodeS) && this[XmlILOptimization.AnnotateIndex1] && qilNode.Count == 2 && qilNode[0].XmlType.IsSubtypeOf(XmlQueryTypeFactory.Node) && qilNode[1].XmlType == XmlQueryTypeFactory.StringX && qilNode2.NodeType == QilNodeType.Filter)
        {
            QilNode qilNode4 = qilNode2[0];
            QilNode qilNode5 = qilNode2[1];
            if (qilNode4.NodeType == QilNodeType.For)
            {
                QilNode expr = qilNode4[0];
                if (qilNode5.NodeType == QilNodeType.Not)
                {
                    QilNode qilNode6 = qilNode5[0];
                    if (qilNode6.NodeType == QilNodeType.IsEmpty)
                    {
                        QilNode qilNode7 = qilNode6[0];
                        if (qilNode7.NodeType == QilNodeType.Filter)
{
                            QilNode qilNode8 = qilNode7[0];
                            QilNode qilNode9 = qilNode7[1];
                            if (qilNode8.NodeType == QilNodeType.For)
{
                                QilNode qilNode10 = qilNode8[0];
                                if (qilNode9.NodeType == QilNodeType.Eq)
{
                                    QilNode qilNode11 = qilNode9[0];
                                    QilNode qilNode12 = qilNode9[1];
                                    if (qilNode11 == qilNode8 && qilNode12.NodeType == QilNodeType.Parameter && qilNode12 == qilNode[1] && IsDocOrderDistinct(qilNode2) && AllowReplace(XmlILOptimization.AnnotateIndex1, local0))
{
                                        EqualityIndexVisitor equalityIndexVisitor = new EqualityIndexVisitor();
                                        if (equalityIndexVisitor.Scan(expr, qilNode[0], qilNode12) && equalityIndexVisitor.Scan(qilNode10, qilNode[0], qilNode12))
{
                                            OptimizerPatterns optimizerPatterns = OptimizerPatterns.Write(qilNode2);
                                            optimizerPatterns.AddPattern(OptimizerPatternName.EqualityIndex);
                                            optimizerPatterns.AddArgument(OptimizerPatternArgument.StepNode, qilNode4);
                                            optimizerPatterns.AddArgument(OptimizerPatternArgument.StepInput, qilNode10);
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
        if (local0.XmlType.IsSubtypeOf(XmlQueryTypeFactory.NodeS) && this[XmlILOptimization.AnnotateIndex2] && qilNode.Count == 2 && qilNode[0].XmlType == XmlQueryTypeFactory.Node && qilNode[1].XmlType == XmlQueryTypeFactory.StringX && qilNode2.NodeType == QilNodeType.Filter)
        {
            QilNode qilNode13 = qilNode2[0];
            QilNode qilNode14 = qilNode2[1];
            if (qilNode13.NodeType == QilNodeType.For)
            {
                QilNode expr2 = qilNode13[0];
                if (qilNode14.NodeType == QilNodeType.Eq)
                {
                    QilNode qilNode15 = qilNode14[0];
                    QilNode qilNode16 = qilNode14[1];
                    if (qilNode16.NodeType == QilNodeType.Parameter && qilNode16 == qilNode[1] && IsDocOrderDistinct(qilNode2) && AllowReplace(XmlILOptimization.AnnotateIndex2, local0))
                    {
                        EqualityIndexVisitor equalityIndexVisitor2 = new EqualityIndexVisitor();
                        if (equalityIndexVisitor2.Scan(expr2, qilNode[0], qilNode16) && equalityIndexVisitor2.Scan(qilNode15, qilNode[0], qilNode16))
{
                            OptimizerPatterns optimizerPatterns2 = OptimizerPatterns.Write(qilNode2);
                            optimizerPatterns2.AddPattern(OptimizerPatternName.EqualityIndex);
                            optimizerPatterns2.AddArgument(OptimizerPatternArgument.StepNode, qilNode13);
                            optimizerPatterns2.AddArgument(OptimizerPatternArgument.StepInput, qilNode15);
                        }
                    }
                }
            }
        }
        return NoReplace(local0);
    }
References System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.AllowReplace(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Xml.Xsl.IlGen.IsDocOrderDistinct, System.Xml.Xsl.XmlQueryTypeFactory.Node, System.Xml.Xsl.XmlQueryTypeFactory.NodeS, System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.NoReplace(), System.Xml.Xsl.XmlQueryTypeFactory.StringX, and System.Xml.Xsl.IlGen.OptimizerPatterns.Write().