Terraria: System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitInvoke
VisitInvoke()
override QilNode System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitInvoke (QilInvoke local0) inline protected virtual
Reimplemented from System.Xml.Xsl.Qil.QilVisitor.
Definition at line 2105 of file XmlILOptimizerVisitor.cs.
    {
        QilNode qilNode = local0[0];
        QilNode qilNode2 = local0[1];
        if (this[XmlILOptimization.NormalizeInvokeEmpty] && qilNode.NodeType == QilNodeType.Function)
        {
            QilNode qilNode3 = qilNode[1];
            if (qilNode3.NodeType == QilNodeType.Sequence && qilNode3.Count == 0 && AllowReplace(XmlILOptimization.NormalizeInvokeEmpty, local0))
            {
                return Replace(XmlILOptimization.NormalizeInvokeEmpty, local0, VisitSequence(f.Sequence()));
            }
        }
        if (this[XmlILOptimization.AnnotateTrackCallers] && AllowReplace(XmlILOptimization.AnnotateTrackCallers, local0))
        {
            XmlILConstructInfo.Write(qilNode).CallersInfo.Add(XmlILConstructInfo.Write(local0));
        }
        if (this[XmlILOptimization.AnnotateInvoke] && qilNode.NodeType == QilNodeType.Function)
        {
            QilNode ndSrc = qilNode[1];
            if (AllowReplace(XmlILOptimization.AnnotateInvoke, local0))
            {
                OptimizerPatterns.Inherit(ndSrc, local0, OptimizerPatternName.IsDocOrderDistinct);
                OptimizerPatterns.Inherit(ndSrc, local0, OptimizerPatternName.SameDepth);
            }
        }
        return NoReplace(local0);
    }
References System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.AllowReplace(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Xml.Xsl.Qil.QilReplaceVisitor.f, System.Xml.Xsl.IlGen.OptimizerPatterns.Inherit(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.NoReplace(), System.Xml.Replace, System.Xml.Xsl.Qil.QilFactory.Sequence(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitSequence(), and System.Xml.Xsl.IlGen.XmlILConstructInfo.Write().