Terraria: System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.FoldArithmetic
FoldArithmetic()
QilNode System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.FoldArithmetic (QilNodeType opType, QilLiteral left, QilLiteral right) inline private
Definition at line 3129 of file XmlILOptimizerVisitor.cs.
    {
        checked
        {
            try
            {
                switch (left.NodeType)
                {
                case QilNodeType.LiteralInt32:
                {
                    int num7 = left;
                    int num8 = right;
                    switch (opType)
                    {
                    case QilNodeType.Add:
                        return f.LiteralInt32(num7 + num8);
                    case QilNodeType.Subtract:
                        return f.LiteralInt32(num7 - num8);
                    case QilNodeType.Multiply:
                        return f.LiteralInt32(num7 * num8);
                    case QilNodeType.Divide:
                        return f.LiteralInt32(unchecked(num7 / num8));
                    case QilNodeType.Modulo:
                        return f.LiteralInt32(unchecked(num7 % num8));
                    }
                    break;
                }
                case QilNodeType.LiteralInt64:
                {
                    long num5 = left;
                    long num6 = right;
                    switch (opType)
                    {
                    case QilNodeType.Add:
                        return f.LiteralInt64(num5 + num6);
                    case QilNodeType.Subtract:
                        return f.LiteralInt64(num5 - num6);
                    case QilNodeType.Multiply:
                        return f.LiteralInt64(num5 * num6);
                    case QilNodeType.Divide:
                        return f.LiteralInt64(unchecked(num5 / num6));
                    case QilNodeType.Modulo:
                        return f.LiteralInt64(unchecked(num5 % num6));
                    }
                    break;
                }
                case QilNodeType.LiteralDecimal:
                {
                    decimal num3 = left;
                    decimal num4 = right;
                    switch (opType)
                    {
                    case QilNodeType.Add:
                        return f.LiteralDecimal(num3 + num4);
                    case QilNodeType.Subtract:
                        return f.LiteralDecimal(num3 - num4);
                    case QilNodeType.Multiply:
                        return f.LiteralDecimal(num3 * num4);
                    case QilNodeType.Divide:
                        return f.LiteralDecimal(num3 / num4);
                    case QilNodeType.Modulo:
                        return f.LiteralDecimal(num3 % num4);
                    }
                    break;
                }
                case QilNodeType.LiteralDouble:
                {
                    double num = left;
                    double num2 = right;
                    switch (opType)
                    {
                    case QilNodeType.Add:
                        return f.LiteralDouble(num + num2);
                    case QilNodeType.Subtract:
                        return f.LiteralDouble(num - num2);
                    case QilNodeType.Multiply:
                        return f.LiteralDouble(num * num2);
                    case QilNodeType.Divide:
                        return f.LiteralDouble(num / num2);
                    case QilNodeType.Modulo:
                        return f.LiteralDouble(num % num2);
                    }
                    break;
                }
                }
            }
            catch (OverflowException)
            {
            }
            catch (DivideByZeroException)
            {
            }
            return opType switch
            {
                QilNodeType.Add => f.Add(left, right),
                QilNodeType.Subtract => f.Subtract(left, right),
                QilNodeType.Multiply => f.Multiply(left, right),
                QilNodeType.Divide => f.Divide(left, right),
                QilNodeType.Modulo => f.Modulo(left, right),
                _ => null,
            };
        }
    }
References System.Xml.Xsl.Qil.QilFactory.Add(), System.Xml.Xsl.Qil.QilNode.Add(), System.Xml.Dictionary, System.Xml.Xsl.Qil.QilFactory.Divide(), System.Xml.Xsl.Qil.QilReplaceVisitor.f, System.Xml.Xsl.Qil.QilFactory.LiteralDecimal(), System.Xml.Xsl.Qil.QilFactory.LiteralDouble(), System.Xml.Xsl.Qil.QilFactory.LiteralInt32(), System.Xml.Xsl.Qil.QilFactory.LiteralInt64(), System.Xml.Xsl.Qil.QilFactory.Modulo(), System.Xml.Xsl.Qil.QilFactory.Multiply(), System.Xml.Xsl.Qil.QilNode.NodeType, and System.Xml.Xsl.Qil.QilFactory.Subtract().
Referenced by System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.CanFoldArithmetic(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitAdd(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitDivide(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitEq(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitModulo(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitMultiply(), and System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitSubtract().