Terraria: System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitLoop
VisitLoop()
override QilNode System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitLoop (QilLoop local0) inline protected virtual
Reimplemented from System.Xml.Xsl.Qil.QilVisitor.
Definition at line 1471 of file XmlILOptimizerVisitor.cs.
    {
        QilNode qilNode = local0[0];
        QilNode qilNode2 = local0[1];
        if (this[XmlILOptimization.FoldNone] && (object)qilNode.XmlType == XmlQueryTypeFactory.None && AllowReplace(XmlILOptimization.FoldNone, local0))
        {
            return Replace(XmlILOptimization.FoldNone, local0, VisitNop(f.Nop(qilNode[0])));
        }
        if (this[XmlILOptimization.EliminateIterator] && qilNode.NodeType == QilNodeType.For)
        {
            QilNode qilNode3 = qilNode[0];
            if (qilNode3.NodeType == QilNodeType.For && !OptimizerPatterns.Read(qilNode).MatchesPattern(OptimizerPatternName.IsPositional) && AllowReplace(XmlILOptimization.EliminateIterator, local0))
            {
                return Replace(XmlILOptimization.EliminateIterator, local0, Subs(qilNode2, qilNode, qilNode3));
            }
        }
        if (this[XmlILOptimization.EliminateLoop] && qilNode.NodeType == QilNodeType.For)
        {
            QilNode qilNode4 = qilNode[0];
            if (qilNode4.NodeType == QilNodeType.Sequence && qilNode4.Count == 0 && AllowReplace(XmlILOptimization.EliminateLoop, local0))
            {
                return Replace(XmlILOptimization.EliminateLoop, local0, VisitSequence(f.Sequence()));
            }
        }
        if (this[XmlILOptimization.EliminateLoop] && !OptimizerPatterns.Read(qilNode).MatchesPattern(OptimizerPatternName.MaybeSideEffects) && qilNode2.NodeType == QilNodeType.Sequence && qilNode2.Count == 0 && AllowReplace(XmlILOptimization.EliminateLoop, local0))
        {
            return Replace(XmlILOptimization.EliminateLoop, local0, VisitSequence(f.Sequence()));
        }
        if (this[XmlILOptimization.EliminateLoop] && qilNode2 == qilNode && AllowReplace(XmlILOptimization.EliminateLoop, local0))
        {
            return Replace(XmlILOptimization.EliminateLoop, local0, qilNode[0]);
        }
        if (this[XmlILOptimization.NormalizeLoopText] && qilNode.NodeType == QilNodeType.For)
        {
            QilNode qilNode5 = qilNode[0];
            if (qilNode5.XmlType.IsSingleton && qilNode2.NodeType == QilNodeType.TextCtor)
            {
                QilNode body = qilNode2[0];
                if (AllowReplace(XmlILOptimization.NormalizeLoopText, local0))
                {
                    return Replace(XmlILOptimization.NormalizeLoopText, local0, VisitTextCtor(f.TextCtor(VisitLoop(f.Loop(qilNode, body)))));
                }
            }
        }
        if (this[XmlILOptimization.EliminateIteratorUsedAtMostOnce] && (qilNode.NodeType == QilNodeType.Let || qilNode[0].XmlType.IsSingleton) && !OptimizerPatterns.Read(qilNode).MatchesPattern(OptimizerPatternName.MaybeSideEffects) && _nodeCounter.Count(qilNode2, qilNode) <= 1 && AllowReplace(XmlILOptimization.EliminateIteratorUsedAtMostOnce, local0))
        {
            return Replace(XmlILOptimization.EliminateIteratorUsedAtMostOnce, local0, Subs(qilNode2, qilNode, qilNode[0]));
        }
        if (this[XmlILOptimization.NormalizeLoopConditional] && qilNode2.NodeType == QilNodeType.Conditional)
        {
            QilNode child = qilNode2[0];
            QilNode qilNode6 = qilNode2[1];
            QilNode qilNode7 = qilNode2[2];
            if (qilNode6.NodeType == QilNodeType.Sequence && qilNode6.Count == 0 && qilNode7 == qilNode && AllowReplace(XmlILOptimization.NormalizeLoopConditional, local0))
            {
                return Replace(XmlILOptimization.NormalizeLoopConditional, local0, VisitFilter(f.Filter(qilNode, VisitNot(f.Not(child)))));
            }
        }
        if (this[XmlILOptimization.NormalizeLoopConditional] && qilNode2.NodeType == QilNodeType.Conditional)
        {
            QilNode body2 = qilNode2[0];
            QilNode qilNode8 = qilNode2[1];
            QilNode qilNode9 = qilNode2[2];
            if (qilNode8 == qilNode && qilNode9.NodeType == QilNodeType.Sequence && qilNode9.Count == 0 && AllowReplace(XmlILOptimization.NormalizeLoopConditional, local0))
            {
                return Replace(XmlILOptimization.NormalizeLoopConditional, local0, VisitFilter(f.Filter(qilNode, body2)));
            }
        }
        if (this[XmlILOptimization.NormalizeLoopConditional] && qilNode.NodeType == QilNodeType.For && qilNode2.NodeType == QilNodeType.Conditional)
        {
            QilNode child2 = qilNode2[0];
            QilNode qilNode10 = qilNode2[1];
            QilNode expr = qilNode2[2];
            if (qilNode10.NodeType == QilNodeType.Sequence && qilNode10.Count == 0 && NonPositional(expr, qilNode) && AllowReplace(XmlILOptimization.NormalizeLoopConditional, local0))
            {
                QilNode qilNode11 = VisitFor(f.For(VisitFilter(f.Filter(qilNode, VisitNot(f.Not(child2))))));
                return Replace(XmlILOptimization.NormalizeLoopConditional, local0, VisitLoop(f.Loop(qilNode11, Subs(expr, qilNode, qilNode11))));
            }
        }
        if (this[XmlILOptimization.NormalizeLoopConditional] && qilNode.NodeType == QilNodeType.For && qilNode2.NodeType == QilNodeType.Conditional)
        {
            QilNode body3 = qilNode2[0];
            QilNode expr2 = qilNode2[1];
            QilNode qilNode12 = qilNode2[2];
            if (NonPositional(expr2, qilNode) && qilNode12.NodeType == QilNodeType.Sequence && qilNode12.Count == 0 && AllowReplace(XmlILOptimization.NormalizeLoopConditional, local0))
            {
                QilNode qilNode13 = VisitFor(f.For(VisitFilter(f.Filter(qilNode, body3))));
                return Replace(XmlILOptimization.NormalizeLoopConditional, local0, VisitLoop(f.Loop(qilNode13, Subs(expr2, qilNode, qilNode13))));
            }
        }
        if (this[XmlILOptimization.NormalizeLoopLoop] && qilNode2.NodeType == QilNodeType.Loop)
        {
            QilNode qilNode14 = qilNode2[0];
            QilNode expr3 = qilNode2[1];
            if (qilNode14.NodeType == QilNodeType.For)
            {
                QilNode body4 = qilNode14[0];
                if (!DependsOn(expr3, qilNode) && NonPositional(expr3, qilNode14) && AllowReplace(XmlILOptimization.NormalizeLoopLoop, local0))
                {
                    QilNode qilNode15 = VisitFor(f.For(VisitLoop(f.Loop(qilNode, body4))));
                    return Replace(XmlILOptimization.NormalizeLoopLoop, local0, VisitLoop(f.Loop(qilNode15, Subs(expr3, qilNode14, qilNode15))));
                }
            }
        }
        if (this[XmlILOptimization.AnnotateSingletonLoop] && qilNode.NodeType == QilNodeType.For)
        {
            QilNode qilNode16 = qilNode[0];
            if (!qilNode16.XmlType.MaybeMany && AllowReplace(XmlILOptimization.AnnotateSingletonLoop, local0))
            {
                OptimizerPatterns.Inherit(qilNode2, local0, OptimizerPatternName.IsDocOrderDistinct);
                OptimizerPatterns.Inherit(qilNode2, local0, OptimizerPatternName.SameDepth);
            }
        }
        if (this[XmlILOptimization.AnnotateRootLoop] && IsStepPattern(qilNode2, QilNodeType.Root) && AllowReplace(XmlILOptimization.AnnotateRootLoop, local0))
        {
            OptimizerPatterns.Write(local0).AddPattern(OptimizerPatternName.SameDepth);
        }
        if (this[XmlILOptimization.AnnotateContentLoop] && qilNode.NodeType == QilNodeType.For)
        {
            QilNode qilNode17 = qilNode[0];
            if (OptimizerPatterns.Read(qilNode17).MatchesPattern(OptimizerPatternName.SameDepth) && (IsStepPattern(qilNode2, QilNodeType.Content) || IsStepPattern(qilNode2, QilNodeType.Union)) && qilNode == OptimizerPatterns.Read(qilNode2).GetArgument(OptimizerPatternArgument.StepInput) && AllowReplace(XmlILOptimization.AnnotateContentLoop, local0))
            {
                OptimizerPatterns.Write(local0).AddPattern(OptimizerPatternName.SameDepth);
                OptimizerPatterns.Inherit(qilNode17, local0, OptimizerPatternName.IsDocOrderDistinct);
            }
        }
        if (this[XmlILOptimization.AnnotateAttrNmspLoop] && qilNode.NodeType == QilNodeType.For)
        {
            QilNode ndSrc = qilNode[0];
            if ((IsStepPattern(qilNode2, QilNodeType.Attribute) || IsStepPattern(qilNode2, QilNodeType.XPathNamespace) || OptimizerPatterns.Read(qilNode2).MatchesPattern(OptimizerPatternName.FilterAttributeKind)) && qilNode == OptimizerPatterns.Read(qilNode2).GetArgument(OptimizerPatternArgument.StepInput) && AllowReplace(XmlILOptimization.AnnotateAttrNmspLoop, local0))
            {
                OptimizerPatterns.Inherit(ndSrc, local0, OptimizerPatternName.SameDepth);
                OptimizerPatterns.Inherit(ndSrc, local0, OptimizerPatternName.IsDocOrderDistinct);
            }
        }
        if (this[XmlILOptimization.AnnotateDescendantLoop] && qilNode.NodeType == QilNodeType.For)
        {
            QilNode qilNode18 = qilNode[0];
            if (OptimizerPatterns.Read(qilNode18).MatchesPattern(OptimizerPatternName.SameDepth) && (IsStepPattern(qilNode2, QilNodeType.Descendant) || IsStepPattern(qilNode2, QilNodeType.DescendantOrSelf)) && qilNode == OptimizerPatterns.Read(qilNode2).GetArgument(OptimizerPatternArgument.StepInput) && AllowReplace(XmlILOptimization.AnnotateDescendantLoop, local0))
            {
                OptimizerPatterns.Inherit(qilNode18, local0, OptimizerPatternName.IsDocOrderDistinct);
            }
        }
        return NoReplace(local0);
    }
References System.Xml.Xsl.IlGen.XmlILOptimizerVisitor._nodeCounter, System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.AllowReplace(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.NodeCounter.Count(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.DependsOn(), System.Xml.Xsl.Qil.QilReplaceVisitor.f, System.Xml.Xsl.Qil.QilFactory.Filter(), System.Xml.Xsl.Qil.QilFactory.For(), System.Xml.Xsl.IlGen.OptimizerPatterns.Inherit(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.IsStepPattern(), System.Xml.Xsl.Qil.QilFactory.Loop(), System.Xml.Xsl.XmlQueryTypeFactory.None, System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.NonPositional(), System.Xml.Xsl.Qil.QilFactory.Nop(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.NoReplace(), System.Xml.Xsl.Qil.QilFactory.Not(), System.Xml.Xsl.IlGen.OptimizerPatterns.Read(), System.Xml.Replace, System.Xml.Xsl.Qil.QilFactory.Sequence(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.Subs(), System.Xml.Xsl.Qil.QilFactory.TextCtor(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitFilter(), System.Xml.Xsl.Qil.QilPatternVisitor.VisitFor(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitLoop(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitNop(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitNot(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitSequence(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitTextCtor(), and System.Xml.Xsl.IlGen.OptimizerPatterns.Write().
Referenced by System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitDocOrderDistinct(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitFilter(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitIsEmpty(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitIsType(), and System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitLoop().