Terraria: System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.FoldComparison
FoldComparison()
QilNode System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.FoldComparison (QilNodeType opType, QilNode left, QilNode right) inline private
Definition at line 3062 of file XmlILOptimizerVisitor.cs.
    {
        object obj = ExtractLiteralValue(left);
        object obj2 = ExtractLiteralValue(right);
        if (left.NodeType == QilNodeType.LiteralDouble && (double.IsNaN((double)obj) || double.IsNaN((double)obj2)))
        {
            if (opType != QilNodeType.Ne)
            {
                return f.False();
            }
            return f.True();
        }
        switch (opType)
        {
        case QilNodeType.Eq:
            if (!obj.Equals(obj2))
            {
                return f.False();
            }
            return f.True();
        case QilNodeType.Ne:
            if (!obj.Equals(obj2))
            {
                return f.True();
            }
            return f.False();
        default:
        {
            int num = ((left.NodeType != QilNodeType.LiteralString) ? ((IComparable)obj).CompareTo(obj2) : string.CompareOrdinal((string)obj, (string)obj2));
            switch (opType)
            {
            case QilNodeType.Gt:
                if (num <= 0)
                {
                    return f.False();
                }
                return f.True();
            case QilNodeType.Ge:
                if (num < 0)
                {
                    return f.False();
                }
                return f.True();
            case QilNodeType.Lt:
                if (num >= 0)
                {
                    return f.False();
                }
                return f.True();
            case QilNodeType.Le:
                if (num > 0)
                {
                    return f.False();
                }
                return f.True();
            default:
                return null;
            }
        }
        }
    }
References System.Xml.Dictionary, System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.ExtractLiteralValue(), System.Xml.Xsl.Qil.QilReplaceVisitor.f, System.Xml.Xsl.Qil.QilFactory.False(), System.Xml.Xsl.Qil.QilNode.NodeType, System.obj, and System.Xml.Xsl.Qil.QilFactory.True().
Referenced by System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitEq(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitGe(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitGt(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitLe(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitLt(), and System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitNe().