Terraria: System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.Optimize
Optimize()
QilExpression System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.Optimize () inline
Definition at line 203 of file XmlILOptimizerVisitor.cs.
    {
        QilExpression qilExpression = (QilExpression)Visit(_qil);
        if (this[XmlILOptimization.TailCall])
        {
            TailCallAnalyzer.Analyze(qilExpression);
        }
        return qilExpression;
    }
References System.Xml.Xsl.IlGen.XmlILOptimizerVisitor._qil, System.Xml.Xsl.IlGen.TailCallAnalyzer.Analyze(), System.Xml.Dictionary, System.Xml.Xsl.Qil.QilExpression, and System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.Visit().
Referenced by System.Xml.Xsl.XmlILGenerator.Generate().