Terraria: System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.IsLiteral
IsLiteral()
bool System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.IsLiteral (QilNode nd) inline private
Definition at line 2928 of file XmlILOptimizerVisitor.cs.
    {
        QilNodeType nodeType = nd.NodeType;
        if ((uint)(nodeType - 18) <= 7u)
        {
            return true;
        }
        return false;
    }
Referenced by System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.AreLiteralArgs(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitAdd(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitDivide(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitEq(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitGe(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitGt(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitLe(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitLt(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitModulo(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitMultiply(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitNe(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitReference(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitSubtract(), and System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitXsltConvert().