Terraria: System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitReference
VisitReference()
override QilNode System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitReference (QilNode oldNode) inline protected virtual
Reimplemented from System.Xml.Xsl.Qil.QilVisitor.
Definition at line 236 of file XmlILOptimizerVisitor.cs.
    {
        QilNode qilNode = _subs.FindReplacement(oldNode);
        if (qilNode == null)
        {
            qilNode = oldNode;
        }
        if (this[XmlILOptimization.EliminateLiteralVariables] && qilNode != null && (qilNode.NodeType == QilNodeType.Let || qilNode.NodeType == QilNodeType.For))
        {
            QilNode binding = ((QilIterator)oldNode).Binding;
            if (IsLiteral(binding))
            {
                return Replace(XmlILOptimization.EliminateLiteralVariables, qilNode, binding.ShallowClone(f));
            }
        }
        if (this[XmlILOptimization.EliminateUnusedGlobals] && IsGlobalValue(qilNode))
        {
            OptimizerPatterns.Write(qilNode).AddPattern(OptimizerPatternName.IsReferenced);
        }
        return base.VisitReference(qilNode);
    }
References System.Xml.Xsl.IlGen.XmlILOptimizerVisitor._subs, System.Xml.Dictionary, System.Xml.Xsl.Qil.QilReplaceVisitor.f, System.Xml.Xsl.Qil.SubstitutionList.FindReplacement(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.IsGlobalValue(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.IsLiteral(), System.Xml.Replace, and System.Xml.Xsl.IlGen.OptimizerPatterns.Write().
Referenced by System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.Subs().