Terraria: System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitLet
VisitLet()
override QilNode System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitLet (QilIterator local0) inline protected virtual
Reimplemented from System.Xml.Xsl.Qil.QilVisitor.
Definition at line 392 of file XmlILOptimizerVisitor.cs.
    {
        QilNode ndSrc = local0[0];
        if (local0.XmlType.IsSingleton && !IsGlobalVariable(local0) && this[XmlILOptimization.NormalizeSingletonLet] && AllowReplace(XmlILOptimization.NormalizeSingletonLet, local0))
        {
            local0.NodeType = QilNodeType.For;
            VisitFor(local0);
        }
        if (this[XmlILOptimization.AnnotateLet] && AllowReplace(XmlILOptimization.AnnotateLet, local0))
        {
            OptimizerPatterns.Inherit(ndSrc, local0, OptimizerPatternName.Step);
            OptimizerPatterns.Inherit(ndSrc, local0, OptimizerPatternName.IsDocOrderDistinct);
            OptimizerPatterns.Inherit(ndSrc, local0, OptimizerPatternName.SameDepth);
        }
        return NoReplace(local0);
    }
References System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.AllowReplace(), System.Xml.Dictionary, System.Xml.Xsl.IlGen.OptimizerPatterns.Inherit(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.IsGlobalVariable(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.NoReplace(), and System.Xml.Xsl.Qil.QilPatternVisitor.VisitFor().
Referenced by System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitIsEmpty(), and System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitIsType().