Terraria: System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitSortKey
VisitSortKey()
override QilNode System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitSortKey (QilSortKey local0) inline protected virtual
Reimplemented from System.Xml.Xsl.Qil.QilVisitor.
Definition at line 1843 of file XmlILOptimizerVisitor.cs.
    {
        QilNode qilNode = local0[0];
        QilNode collation = local0[1];
        if (this[XmlILOptimization.NormalizeSortXsltConvert] && qilNode.NodeType == QilNodeType.XsltConvert)
        {
            QilNode qilNode2 = qilNode[0];
            QilNode qilNode3 = qilNode[1];
            if (qilNode3.NodeType == QilNodeType.LiteralType)
            {
                XmlQueryType xmlQueryType = (XmlQueryType)((QilLiteral)qilNode3).Value;
                if (qilNode2.XmlType == XmlQueryTypeFactory.IntX && xmlQueryType == XmlQueryTypeFactory.DoubleX && AllowReplace(XmlILOptimization.NormalizeSortXsltConvert, local0))
                {
                    return Replace(XmlILOptimization.NormalizeSortXsltConvert, local0, VisitSortKey(f.SortKey(qilNode2, collation)));
                }
            }
        }
        return NoReplace(local0);
    }
References System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.AllowReplace(), System.Xml.Dictionary, System.Xml.Xsl.XmlQueryTypeFactory.DoubleX, System.Xml.Xsl.Qil.QilReplaceVisitor.f, System.Xml.Xsl.XmlQueryTypeFactory.IntX, System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.NoReplace(), System.Xml.Replace, System.Xml.Xsl.Qil.QilFactory.SortKey(), and System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitSortKey().
Referenced by System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitSortKey().