Terraria: System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.ExtractLiteralValue
ExtractLiteralValue()
object System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.ExtractLiteralValue (QilNode nd) inline private
Definition at line 2950 of file XmlILOptimizerVisitor.cs.
    {
        if (nd.NodeType == QilNodeType.True)
        {
            return true;
        }
        if (nd.NodeType == QilNodeType.False)
        {
            return false;
        }
        if (nd.NodeType == QilNodeType.LiteralQName)
        {
            return nd;
        }
        return ((QilLiteral)nd).Value;
    }
References System.Xml.Dictionary.
Referenced by System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.CanFoldXsltConvertNonLossy(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.FoldComparison(), and System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.FoldXsltConvert().