Terraria: System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitEq
VisitEq()
override QilNode System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitEq (QilBinary local0) inline protected virtual
Reimplemented from System.Xml.Xsl.Qil.QilVisitor.
Definition at line 1072 of file XmlILOptimizerVisitor.cs.
    {
        QilNode qilNode = local0[0];
        QilNode qilNode2 = local0[1];
        if (this[XmlILOptimization.FoldNone] && (object)qilNode.XmlType == XmlQueryTypeFactory.None && AllowReplace(XmlILOptimization.FoldNone, local0))
        {
            return Replace(XmlILOptimization.FoldNone, local0, VisitNop(f.Nop(qilNode)));
        }
        if (this[XmlILOptimization.FoldNone] && (object)qilNode2.XmlType == XmlQueryTypeFactory.None && AllowReplace(XmlILOptimization.FoldNone, local0))
        {
            return Replace(XmlILOptimization.FoldNone, local0, VisitNop(f.Nop(qilNode2)));
        }
        if (this[XmlILOptimization.EliminateEq] && IsLiteral(qilNode) && IsLiteral(qilNode2) && AllowReplace(XmlILOptimization.EliminateEq, local0))
        {
            return Replace(XmlILOptimization.EliminateEq, local0, FoldComparison(QilNodeType.Eq, qilNode, qilNode2));
        }
        if (this[XmlILOptimization.NormalizeEqLiteral] && IsLiteral(qilNode) && !IsLiteral(qilNode2) && AllowReplace(XmlILOptimization.NormalizeEqLiteral, local0))
        {
            return Replace(XmlILOptimization.NormalizeEqLiteral, local0, VisitEq(f.Eq(qilNode2, qilNode)));
        }
        if (this[XmlILOptimization.NormalizeXsltConvertEq] && qilNode.NodeType == QilNodeType.XsltConvert)
        {
            QilNode qilNode3 = qilNode[0];
            QilNode qilNode4 = qilNode[1];
            if (qilNode4.NodeType == QilNodeType.LiteralType)
            {
                XmlQueryType typ = (XmlQueryType)((QilLiteral)qilNode4).Value;
                if (IsPrimitiveNumeric(qilNode3.XmlType) && IsPrimitiveNumeric(typ) && IsLiteral(qilNode2) && CanFoldXsltConvertNonLossy(qilNode2, qilNode3.XmlType) && AllowReplace(XmlILOptimization.NormalizeXsltConvertEq, local0))
                {
                    return Replace(XmlILOptimization.NormalizeXsltConvertEq, local0, VisitEq(f.Eq(qilNode3, FoldXsltConvert(qilNode2, qilNode3.XmlType))));
                }
            }
        }
        if (this[XmlILOptimization.NormalizeAddEq] && qilNode.NodeType == QilNodeType.Add)
        {
            QilNode left = qilNode[0];
            QilNode qilNode5 = qilNode[1];
            if (IsLiteral(qilNode5) && IsLiteral(qilNode2) && CanFoldArithmetic(QilNodeType.Subtract, (QilLiteral)qilNode2, (QilLiteral)qilNode5) && AllowReplace(XmlILOptimization.NormalizeAddEq, local0))
            {
                return Replace(XmlILOptimization.NormalizeAddEq, local0, VisitEq(f.Eq(left, FoldArithmetic(QilNodeType.Subtract, (QilLiteral)qilNode2, (QilLiteral)qilNode5))));
            }
        }
        if (this[XmlILOptimization.NormalizeIdEq] && qilNode.NodeType == QilNodeType.XsltGenerateId)
        {
            QilNode qilNode6 = qilNode[0];
            if (qilNode6.XmlType.IsSingleton && qilNode2.NodeType == QilNodeType.XsltGenerateId)
            {
                QilNode qilNode7 = qilNode2[0];
                if (qilNode7.XmlType.IsSingleton && AllowReplace(XmlILOptimization.NormalizeIdEq, local0))
                {
                    return Replace(XmlILOptimization.NormalizeIdEq, local0, VisitIs(f.Is(qilNode6, qilNode7)));
                }
            }
        }
        if (this[XmlILOptimization.NormalizeIdEq] && qilNode.NodeType == QilNodeType.XsltGenerateId)
        {
            QilNode qilNode8 = qilNode[0];
            if (qilNode8.XmlType.IsSingleton && qilNode2.NodeType == QilNodeType.StrConcat)
            {
                QilNode qilNode9 = qilNode2[1];
                if (qilNode9.NodeType == QilNodeType.Loop)
                {
                    QilNode qilNode10 = qilNode9[0];
                    QilNode qilNode11 = qilNode9[1];
                    if (qilNode10.NodeType == QilNodeType.For)
                    {
                        QilNode qilNode12 = qilNode10[0];
                        if (!qilNode12.XmlType.MaybeMany && qilNode11.NodeType == QilNodeType.XsltGenerateId)
{
                            QilNode qilNode13 = qilNode11[0];
                            if (qilNode13 == qilNode10 && AllowReplace(XmlILOptimization.NormalizeIdEq, local0))
{
                                QilNode qilNode14 = VisitFor(f.For(qilNode12));
                                return Replace(XmlILOptimization.NormalizeIdEq, local0, VisitNot(f.Not(VisitIsEmpty(f.IsEmpty(VisitFilter(f.Filter(qilNode14, VisitIs(f.Is(qilNode8, qilNode14)))))))));
                            }
                        }
                    }
                }
            }
        }
        if (this[XmlILOptimization.NormalizeIdEq] && qilNode.NodeType == QilNodeType.StrConcat)
        {
            QilNode qilNode15 = qilNode[1];
            if (qilNode15.NodeType == QilNodeType.Loop)
            {
                QilNode qilNode16 = qilNode15[0];
                QilNode qilNode17 = qilNode15[1];
                if (qilNode16.NodeType == QilNodeType.For)
                {
                    QilNode qilNode18 = qilNode16[0];
                    if (!qilNode18.XmlType.MaybeMany && qilNode17.NodeType == QilNodeType.XsltGenerateId)
                    {
                        QilNode qilNode19 = qilNode17[0];
                        if (qilNode19 == qilNode16 && qilNode2.NodeType == QilNodeType.XsltGenerateId)
{
                            QilNode qilNode20 = qilNode2[0];
                            if (qilNode20.XmlType.IsSingleton && AllowReplace(XmlILOptimization.NormalizeIdEq, local0))
{
                                QilNode qilNode21 = VisitFor(f.For(qilNode18));
                                return Replace(XmlILOptimization.NormalizeIdEq, local0, VisitNot(f.Not(VisitIsEmpty(f.IsEmpty(VisitFilter(f.Filter(qilNode21, VisitIs(f.Is(qilNode20, qilNode21)))))))));
                            }
                        }
                    }
                }
            }
        }
        if (this[XmlILOptimization.NormalizeMuenchian] && qilNode.NodeType == QilNodeType.Length)
        {
            QilNode qilNode22 = qilNode[0];
            if (qilNode22.NodeType == QilNodeType.Union)
            {
                QilNode qilNode23 = qilNode22[0];
                QilNode qilNode24 = qilNode22[1];
                if (qilNode23.XmlType.IsSingleton && !qilNode24.XmlType.MaybeMany && qilNode2.NodeType == QilNodeType.LiteralInt32)
                {
                    int num = (int)((QilLiteral)qilNode2).Value;
                    if (num == 1 && AllowReplace(XmlILOptimization.NormalizeMuenchian, local0))
                    {
                        QilNode qilNode25 = VisitFor(f.For(qilNode24));
                        return Replace(XmlILOptimization.NormalizeMuenchian, local0, VisitIsEmpty(f.IsEmpty(VisitFilter(f.Filter(qilNode25, VisitNot(f.Not(VisitIs(f.Is(qilNode23, qilNode25)))))))));
                    }
                }
            }
        }
        if (this[XmlILOptimization.NormalizeMuenchian] && qilNode.NodeType == QilNodeType.Length)
        {
            QilNode qilNode26 = qilNode[0];
            if (qilNode26.NodeType == QilNodeType.Union)
            {
                QilNode qilNode27 = qilNode26[0];
                QilNode qilNode28 = qilNode26[1];
                if (!qilNode27.XmlType.MaybeMany && qilNode28.XmlType.IsSingleton && qilNode2.NodeType == QilNodeType.LiteralInt32)
                {
                    int num2 = (int)((QilLiteral)qilNode2).Value;
                    if (num2 == 1 && AllowReplace(XmlILOptimization.NormalizeMuenchian, local0))
                    {
                        QilNode qilNode29 = VisitFor(f.For(qilNode27));
                        return Replace(XmlILOptimization.NormalizeMuenchian, local0, VisitIsEmpty(f.IsEmpty(VisitFilter(f.Filter(qilNode29, VisitNot(f.Not(VisitIs(f.Is(qilNode29, qilNode28)))))))));
                    }
                }
            }
        }
        if (this[XmlILOptimization.AnnotateMaxLengthEq] && qilNode.NodeType == QilNodeType.Length && qilNode2.NodeType == QilNodeType.LiteralInt32)
        {
            int num3 = (int)((QilLiteral)qilNode2).Value;
            if (AllowReplace(XmlILOptimization.AnnotateMaxLengthEq, local0))
            {
                OptimizerPatterns.Write(qilNode).AddPattern(OptimizerPatternName.MaxPosition);
                OptimizerPatterns.Write(qilNode).AddArgument(OptimizerPatternArgument.ElementQName, num3);
            }
        }
        return NoReplace(local0);
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.AllowReplace(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.CanFoldArithmetic(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.CanFoldXsltConvertNonLossy(), System.Xml.Dictionary, System.Xml.Xsl.Qil.QilFactory.Eq(), System.Xml.Xsl.Qil.QilReplaceVisitor.f, System.Xml.Xsl.Qil.QilFactory.Filter(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.FoldArithmetic(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.FoldComparison(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.FoldXsltConvert(), System.Xml.Xsl.Qil.QilFactory.For(), System.Xml.Xsl.Qil.QilFactory.Is(), System.Xml.Xsl.Qil.QilFactory.IsEmpty(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.IsLiteral(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.IsPrimitiveNumeric(), System.Xml.Xsl.XmlQueryTypeFactory.None, System.Xml.Xsl.Qil.QilFactory.Nop(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.NoReplace(), System.Xml.Xsl.Qil.QilFactory.Not(), System.Xml.Replace, System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitEq(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitFilter(), System.Xml.Xsl.Qil.QilPatternVisitor.VisitFor(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitIs(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitIsEmpty(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitNop(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitNot(), and System.Xml.Xsl.IlGen.OptimizerPatterns.Write().
Referenced by System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitEq().