Terraria: System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitQilExpression
VisitQilExpression()
override QilNode System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitQilExpression (QilExpression local0) inline protected virtual
Reimplemented from System.Xml.Xsl.Qil.QilVisitor.
Definition at line 312 of file XmlILOptimizerVisitor.cs.
    {
        QilNode qilNode = local0[0];
        if (this[XmlILOptimization.EliminateUnusedGlobals] && AllowReplace(XmlILOptimization.EliminateUnusedGlobals, local0))
        {
            EliminateUnusedGlobals(local0.GlobalVariableList);
            EliminateUnusedGlobals(local0.GlobalParameterList);
            EliminateUnusedGlobals(local0.FunctionList);
        }
        if (this[XmlILOptimization.AnnotateConstruction] && AllowReplace(XmlILOptimization.AnnotateConstruction, local0))
        {
            foreach (QilFunction function in local0.FunctionList)
            {
                if (IsConstructedExpression(function.Definition))
                {
                    function.Definition = _contentAnalyzer.Analyze(function, function.Definition);
                }
            }
            local0.Root = _contentAnalyzer.Analyze(null, local0.Root);
            XmlILConstructInfo.Write(local0.Root).PushToWriterLast = true;
        }
        return NoReplace(local0);
    }
References System.Xml.Xsl.IlGen.XmlILOptimizerVisitor._contentAnalyzer, System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.AllowReplace(), System.Xml.Xsl.IlGen.XmlILStateAnalyzer.Analyze(), System.Xml.Dictionary, System.Xml.Xsl.IlGen.EliminateUnusedGlobals, System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.IsConstructedExpression(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.NoReplace(), and System.Xml.Xsl.IlGen.XmlILConstructInfo.Write().