Terraria: System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.CanFoldArithmetic
CanFoldArithmetic()
bool System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.CanFoldArithmetic (QilNodeType opType, QilLiteral left, QilLiteral right) inline private
Definition at line 3124 of file XmlILOptimizerVisitor.cs.
    {
        return FoldArithmetic(opType, left, right) is QilLiteral;
    }
References System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.FoldArithmetic().
Referenced by System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitAdd(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitDivide(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitEq(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitModulo(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitMultiply(), and System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitSubtract().