Terraria: System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitMultiply
VisitMultiply()
override QilNode System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitMultiply (QilBinary local0) inline protected virtual
Reimplemented from System.Xml.Xsl.Qil.QilVisitor.
Definition at line 880 of file XmlILOptimizerVisitor.cs.
    {
        QilNode qilNode = local0[0];
        QilNode qilNode2 = local0[1];
        if (this[XmlILOptimization.FoldNone] && (object)qilNode.XmlType == XmlQueryTypeFactory.None && AllowReplace(XmlILOptimization.FoldNone, local0))
        {
            return Replace(XmlILOptimization.FoldNone, local0, VisitNop(f.Nop(qilNode)));
        }
        if (this[XmlILOptimization.FoldNone] && (object)qilNode2.XmlType == XmlQueryTypeFactory.None && AllowReplace(XmlILOptimization.FoldNone, local0))
        {
            return Replace(XmlILOptimization.FoldNone, local0, VisitNop(f.Nop(qilNode2)));
        }
        if (this[XmlILOptimization.EliminateMultiply] && IsLiteral(qilNode) && IsLiteral(qilNode2) && CanFoldArithmetic(QilNodeType.Multiply, (QilLiteral)qilNode, (QilLiteral)qilNode2) && AllowReplace(XmlILOptimization.EliminateMultiply, local0))
        {
            return Replace(XmlILOptimization.EliminateMultiply, local0, FoldArithmetic(QilNodeType.Multiply, (QilLiteral)qilNode, (QilLiteral)qilNode2));
        }
        if (this[XmlILOptimization.NormalizeMultiplyLiteral] && IsLiteral(qilNode) && !IsLiteral(qilNode2) && AllowReplace(XmlILOptimization.NormalizeMultiplyLiteral, local0))
        {
            return Replace(XmlILOptimization.NormalizeMultiplyLiteral, local0, VisitMultiply(f.Multiply(qilNode2, qilNode)));
        }
        return NoReplace(local0);
    }
References System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.AllowReplace(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.CanFoldArithmetic(), System.Xml.Xsl.Qil.QilReplaceVisitor.f, System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.FoldArithmetic(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.IsLiteral(), System.Xml.Xsl.Qil.QilFactory.Multiply(), System.Xml.Xsl.XmlQueryTypeFactory.None, System.Xml.Xsl.Qil.QilFactory.Nop(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.NoReplace(), System.Xml.Replace, System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitMultiply(), and System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitNop().
Referenced by System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitMultiply().