Terraria: System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitDocOrderDistinct
VisitDocOrderDistinct()
override QilNode System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitDocOrderDistinct (QilUnary local0) inline protected virtual
Reimplemented from System.Xml.Xsl.Qil.QilVisitor.
Definition at line 1863 of file XmlILOptimizerVisitor.cs.
    {
        QilNode qilNode = local0[0];
        if (this[XmlILOptimization.FoldNone] && (object)qilNode.XmlType == XmlQueryTypeFactory.None && AllowReplace(XmlILOptimization.FoldNone, local0))
        {
            return Replace(XmlILOptimization.FoldNone, local0, VisitNop(f.Nop(qilNode)));
        }
        if (this[XmlILOptimization.EliminateDod] && IsDocOrderDistinct(qilNode) && AllowReplace(XmlILOptimization.EliminateDod, local0))
        {
            return Replace(XmlILOptimization.EliminateDod, local0, qilNode);
        }
        if (this[XmlILOptimization.FoldNamedDescendants] && qilNode.NodeType == QilNodeType.Loop)
        {
            QilNode qilNode2 = qilNode[0];
            QilNode qilNode3 = qilNode[1];
            if (qilNode2.NodeType == QilNodeType.For)
            {
                QilNode qilNode4 = qilNode2[0];
                if (qilNode4.NodeType == QilNodeType.Loop)
                {
                    QilNode variable = qilNode4[0];
                    QilNode qilNode5 = qilNode4[1];
                    if (qilNode5.NodeType == QilNodeType.DescendantOrSelf)
                    {
                        QilNode child = qilNode5[0];
                        if (qilNode3.NodeType == QilNodeType.Filter)
{
                            QilNode refOld = qilNode3[0];
                            QilNode expr = qilNode3[1];
                            if ((OptimizerPatterns.Read(qilNode3).MatchesPattern(OptimizerPatternName.FilterElements) || OptimizerPatterns.Read(qilNode3).MatchesPattern(OptimizerPatternName.FilterContentKind)) && IsStepPattern(qilNode3, QilNodeType.Content) && AllowReplace(XmlILOptimization.FoldNamedDescendants, local0))
{
                                QilNode qilNode6 = VisitFor(f.For(VisitDescendant(f.Descendant(child))));
                                return Replace(XmlILOptimization.FoldNamedDescendants, local0, VisitDocOrderDistinct(f.DocOrderDistinct(VisitLoop(f.Loop(variable, VisitFilter(f.Filter(qilNode6, Subs(expr, refOld, qilNode6))))))));
                            }
                        }
                    }
                }
            }
        }
        if (this[XmlILOptimization.FoldNamedDescendants] && qilNode.NodeType == QilNodeType.Loop)
        {
            QilNode qilNode7 = qilNode[0];
            QilNode qilNode8 = qilNode[1];
            if (qilNode7.NodeType == QilNodeType.For)
            {
                QilNode qilNode9 = qilNode7[0];
                if (qilNode9.NodeType == QilNodeType.DescendantOrSelf)
                {
                    QilNode child2 = qilNode9[0];
                    if (qilNode8.NodeType == QilNodeType.Filter)
                    {
                        QilNode refOld2 = qilNode8[0];
                        QilNode expr2 = qilNode8[1];
                        if ((OptimizerPatterns.Read(qilNode8).MatchesPattern(OptimizerPatternName.FilterElements) || OptimizerPatterns.Read(qilNode8).MatchesPattern(OptimizerPatternName.FilterContentKind)) && IsStepPattern(qilNode8, QilNodeType.Content) && AllowReplace(XmlILOptimization.FoldNamedDescendants, local0))
{
                            QilNode qilNode10 = VisitFor(f.For(VisitDescendant(f.Descendant(child2))));
                            return Replace(XmlILOptimization.FoldNamedDescendants, local0, VisitFilter(f.Filter(qilNode10, Subs(expr2, refOld2, qilNode10))));
                        }
                    }
                }
            }
        }
        if (this[XmlILOptimization.CommuteDodFilter] && qilNode.NodeType == QilNodeType.Filter)
        {
            QilNode qilNode11 = qilNode[0];
            QilNode expr3 = qilNode[1];
            if (qilNode11.NodeType == QilNodeType.For)
            {
                QilNode child3 = qilNode11[0];
                if (!OptimizerPatterns.Read(qilNode11).MatchesPattern(OptimizerPatternName.IsPositional) && !OptimizerPatterns.Read(qilNode).MatchesPattern(OptimizerPatternName.FilterElements) && !OptimizerPatterns.Read(qilNode).MatchesPattern(OptimizerPatternName.FilterContentKind) && !OptimizerPatterns.Read(qilNode).MatchesPattern(OptimizerPatternName.FilterAttributeKind) && AllowReplace(XmlILOptimization.CommuteDodFilter, local0))
                {
                    QilNode qilNode12 = VisitFor(f.For(VisitDocOrderDistinct(f.DocOrderDistinct(child3))));
                    return Replace(XmlILOptimization.CommuteDodFilter, local0, VisitFilter(f.Filter(qilNode12, Subs(expr3, qilNode11, qilNode12))));
                }
            }
        }
        if (this[XmlILOptimization.CommuteDodFilter] && qilNode.NodeType == QilNodeType.Loop)
        {
            QilNode qilNode13 = qilNode[0];
            QilNode qilNode14 = qilNode[1];
            if (qilNode14.NodeType == QilNodeType.Filter)
            {
                QilNode qilNode15 = qilNode14[0];
                QilNode expr4 = qilNode14[1];
                if (qilNode15.NodeType == QilNodeType.For)
                {
                    QilNode body = qilNode15[0];
                    if (!OptimizerPatterns.Read(qilNode15).MatchesPattern(OptimizerPatternName.IsPositional) && !DependsOn(expr4, qilNode13) && !OptimizerPatterns.Read(qilNode14).MatchesPattern(OptimizerPatternName.FilterElements) && !OptimizerPatterns.Read(qilNode14).MatchesPattern(OptimizerPatternName.FilterContentKind) && !OptimizerPatterns.Read(qilNode14).MatchesPattern(OptimizerPatternName.FilterAttributeKind) && AllowReplace(XmlILOptimization.CommuteDodFilter, local0))
                    {
                        QilNode qilNode16 = VisitFor(f.For(VisitDocOrderDistinct(f.DocOrderDistinct(VisitLoop(f.Loop(qilNode13, body))))));
                        return Replace(XmlILOptimization.CommuteDodFilter, local0, VisitFilter(f.Filter(qilNode16, Subs(expr4, qilNode15, qilNode16))));
                    }
                }
            }
        }
        if (this[XmlILOptimization.IntroduceDod] && qilNode.NodeType == QilNodeType.Loop)
        {
            QilNode qilNode17 = qilNode[0];
            QilNode expr5 = qilNode[1];
            if (qilNode17.NodeType == QilNodeType.For)
            {
                QilNode qilNode18 = qilNode17[0];
                if (!IsDocOrderDistinct(qilNode18) && !OptimizerPatterns.Read(qilNode17).MatchesPattern(OptimizerPatternName.IsPositional) && qilNode18.XmlType.IsSubtypeOf(XmlQueryTypeFactory.NodeNotRtfS) && !OptimizerPatterns.Read(qilNode).MatchesPattern(OptimizerPatternName.FilterElements) && !OptimizerPatterns.Read(qilNode).MatchesPattern(OptimizerPatternName.FilterContentKind) && !OptimizerPatterns.Read(qilNode).MatchesPattern(OptimizerPatternName.FilterAttributeKind) && AllowReplace(XmlILOptimization.IntroduceDod, local0))
                {
                    QilNode qilNode19 = VisitFor(f.For(VisitDocOrderDistinct(f.DocOrderDistinct(qilNode18))));
                    return Replace(XmlILOptimization.IntroduceDod, local0, VisitDocOrderDistinct(f.DocOrderDistinct(VisitLoop(f.Loop(qilNode19, Subs(expr5, qilNode17, qilNode19))))));
                }
            }
        }
        if (this[XmlILOptimization.IntroducePrecedingDod] && qilNode.NodeType == QilNodeType.Loop)
        {
            QilNode variable2 = qilNode[0];
            QilNode qilNode20 = qilNode[1];
            if (!IsDocOrderDistinct(qilNode20) && IsStepPattern(qilNode20, QilNodeType.PrecedingSibling) && AllowReplace(XmlILOptimization.IntroducePrecedingDod, local0))
            {
                return Replace(XmlILOptimization.IntroducePrecedingDod, local0, VisitDocOrderDistinct(f.DocOrderDistinct(VisitLoop(f.Loop(variable2, VisitDocOrderDistinct(f.DocOrderDistinct(qilNode20)))))));
            }
        }
        if (this[XmlILOptimization.EliminateReturnDod] && qilNode.NodeType == QilNodeType.Loop)
        {
            QilNode variable3 = qilNode[0];
            QilNode qilNode21 = qilNode[1];
            if (qilNode21.NodeType == QilNodeType.DocOrderDistinct)
            {
                QilNode qilNode22 = qilNode21[0];
                if (!IsStepPattern(qilNode22, QilNodeType.PrecedingSibling) && AllowReplace(XmlILOptimization.EliminateReturnDod, local0))
                {
                    return Replace(XmlILOptimization.EliminateReturnDod, local0, VisitDocOrderDistinct(f.DocOrderDistinct(VisitLoop(f.Loop(variable3, qilNode22)))));
                }
            }
        }
        if (this[XmlILOptimization.AnnotateDod] && AllowReplace(XmlILOptimization.AnnotateDod, local0))
        {
            OptimizerPatterns.Write(local0).AddPattern(OptimizerPatternName.IsDocOrderDistinct);
            OptimizerPatterns.Inherit(qilNode, local0, OptimizerPatternName.SameDepth);
        }
        if (this[XmlILOptimization.AnnotateDodReverse] && AllowDodReverse(qilNode) && AllowReplace(XmlILOptimization.AnnotateDodReverse, local0))
        {
            OptimizerPatterns.Write(local0).AddPattern(OptimizerPatternName.DodReverse);
            OptimizerPatterns.Write(local0).AddArgument(OptimizerPatternArgument.ElementQName, qilNode);
        }
        if (this[XmlILOptimization.AnnotateJoinAndDod] && qilNode.NodeType == QilNodeType.Loop)
        {
            QilNode qilNode23 = qilNode[0];
            QilNode qilNode24 = qilNode[1];
            if (qilNode23.NodeType == QilNodeType.For)
            {
                QilNode nd = qilNode23[0];
                if (IsDocOrderDistinct(nd) && AllowJoinAndDod(qilNode24) && qilNode23 == OptimizerPatterns.Read(qilNode24).GetArgument(OptimizerPatternArgument.StepInput) && AllowReplace(XmlILOptimization.AnnotateJoinAndDod, local0))
                {
                    OptimizerPatterns.Write(local0).AddPattern(OptimizerPatternName.JoinAndDod);
                    OptimizerPatterns.Write(local0).AddArgument(OptimizerPatternArgument.ElementQName, qilNode24);
                }
            }
        }
        if (this[XmlILOptimization.AnnotateDodMerge] && qilNode.NodeType == QilNodeType.Loop)
        {
            QilNode qilNode25 = qilNode[1];
            if (qilNode25.NodeType == QilNodeType.Invoke && IsDocOrderDistinct(qilNode25) && AllowReplace(XmlILOptimization.AnnotateDodMerge, local0))
            {
                OptimizerPatterns.Write(local0).AddPattern(OptimizerPatternName.DodMerge);
            }
        }
        return NoReplace(local0);
    }
References System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.AllowDodReverse(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.AllowJoinAndDod(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.AllowReplace(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.DependsOn(), System.Xml.Xsl.Qil.QilFactory.Descendant(), System.Xml.Xsl.Qil.QilFactory.DocOrderDistinct(), System.Xml.Xsl.Qil.QilReplaceVisitor.f, System.Xml.Xsl.Qil.QilFactory.Filter(), System.Xml.Xsl.Qil.QilFactory.For(), System.Xml.Xsl.IlGen.OptimizerPatterns.Inherit(), System.Xml.Xsl.IlGen.IsDocOrderDistinct, System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.IsStepPattern(), System.Xml.Xsl.Qil.QilFactory.Loop(), System.Xml.Xsl.XmlQueryTypeFactory.NodeNotRtfS, System.Xml.Xsl.XmlQueryTypeFactory.None, System.Xml.Xsl.Qil.QilFactory.Nop(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.NoReplace(), System.Xml.Xsl.IlGen.OptimizerPatterns.Read(), System.Xml.Replace, System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.Subs(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitDescendant(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitDocOrderDistinct(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitFilter(), System.Xml.Xsl.Qil.QilPatternVisitor.VisitFor(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitLoop(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitNop(), and System.Xml.Xsl.IlGen.OptimizerPatterns.Write().
Referenced by System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitDifference(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitDocOrderDistinct(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitIntersection(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitLength(), and System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitUnion().