Terraria: System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.IsStepPattern
IsStepPattern() [2/2]
bool System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.IsStepPattern (QilNode nd, QilNodeType stepType) inline private
Definition at line 3246 of file XmlILOptimizerVisitor.cs.
    {
        return IsStepPattern(OptimizerPatterns.Read(nd), stepType);
    }
References System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.IsStepPattern(), and System.Xml.Xsl.IlGen.OptimizerPatterns.Read().
Referenced by System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.AllowDodReverse(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.AllowJoinAndDod(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.IsStepPattern(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitDocOrderDistinct(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitLength(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitLoop(), and System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitUnion().