Terraria: System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.AddStepPattern
AddStepPattern()
void System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.AddStepPattern (QilNode nd, QilNode input) inline private
Definition at line 3233 of file XmlILOptimizerVisitor.cs.
    {
        OptimizerPatterns optimizerPatterns = OptimizerPatterns.Write(nd);
        optimizerPatterns.AddPattern(OptimizerPatternName.Step);
        optimizerPatterns.AddArgument(OptimizerPatternArgument.StepNode, nd);
        optimizerPatterns.AddArgument(OptimizerPatternArgument.StepInput, input);
    }
References System.input, and System.Xml.Xsl.IlGen.OptimizerPatterns.Write().
Referenced by System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitAncestor(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitAncestorOrSelf(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitAttribute(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitContent(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitDescendant(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitDescendantOrSelf(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitFollowingSibling(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitNodeRange(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitParent(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitPreceding(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitPrecedingSibling(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitRoot(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitUnion(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitXPathFollowing(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitXPathNamespace(), and System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitXPathPreceding().