Terraria: System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.Subs
Subs()
QilNode System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.Subs (QilNode expr, QilNode refOld, QilNode refNew) inline private
Definition at line 2799 of file XmlILOptimizerVisitor.cs.
    {
        _subs.AddSubstitutionPair(refOld, refNew);
        QilNode result = ((!(expr is QilReference)) ? Visit(expr) : VisitReference(expr));
        _subs.RemoveLastSubstitutionPair();
        return result;
    }
References System.Xml.Xsl.IlGen.XmlILOptimizerVisitor._subs, System.Xml.Xsl.Qil.SubstitutionList.AddSubstitutionPair(), System.Xml.Xsl.Qil.SubstitutionList.RemoveLastSubstitutionPair(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.Visit(), and System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitReference().
Referenced by System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitDocOrderDistinct(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitFilter(), and System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitLoop().