Terraria: System.Xml.Xsl.QueryReaderSettings.CreateReader
CreateReader()
XmlReader System.Xml.Xsl.QueryReaderSettings.CreateReader (Stream stream, string baseUri) inline
Definition at line 90 of file QueryReaderSettings.cs.
    {
        XmlReader xmlReader;
        if (_xmlReaderSettings != null)
        {
            xmlReader = XmlReader.Create(stream, _xmlReaderSettings, baseUri);
        }
        else
        {
            XmlTextReaderImpl xmlTextReaderImpl = new XmlTextReaderImpl(baseUri, stream, _xmlNameTable);
            xmlTextReaderImpl.EntityHandling = _entityHandling;
            xmlTextReaderImpl.Namespaces = _namespaces;
            xmlTextReaderImpl.Normalization = _normalization;
            xmlTextReaderImpl.DtdProcessing = ((!_prohibitDtd) ? DtdProcessing.Parse : DtdProcessing.Prohibit);
            xmlTextReaderImpl.WhitespaceHandling = _whitespaceHandling;
            xmlTextReaderImpl.XmlResolver = _xmlResolver;
            xmlReader = xmlTextReaderImpl;
        }
        if (_validatingReader)
        {
            xmlReader = new XmlValidatingReader(xmlReader);
        }
        return xmlReader;
    }
References System.Xml.Xsl.QueryReaderSettings._entityHandling, System.Xml.Xsl.QueryReaderSettings._namespaces, System.Xml.Xsl.QueryReaderSettings._normalization, System.Xml.Xsl.QueryReaderSettings._prohibitDtd, System.Xml.Xsl.QueryReaderSettings._validatingReader, System.Xml.Xsl.QueryReaderSettings._whitespaceHandling, System.Xml.Xsl.QueryReaderSettings._xmlNameTable, System.Xml.Xsl.QueryReaderSettings._xmlReaderSettings, System.Xml.Xsl.QueryReaderSettings._xmlResolver, System.Xml.XmlReader.Create(), System.Xml.Dictionary, and System.stream.
Referenced by System.Xml.Xsl.Runtime.XmlQueryContext.ConstructDocument(), and System.Xml.Xsl.Xslt.XsltLoader.CreateReader().