Terraria: Terraria.Recipe.SetupRecipeGroups
SetupRecipeGroups()
static void Terraria.Recipe.SetupRecipeGroups () inline static
Definition at line 696 of file Recipe.cs.
    {
        RecipeGroup rec = new RecipeGroup(() => Lang.misc[37].Value + " " + Lang.GetNPCNameValue(74), 2015, 2016, 2017);
        RecipeGroupID.Birds = RecipeGroup.RegisterGroup("Birds", rec);
        rec = new RecipeGroup(() => Lang.misc[37].Value + " " + Lang.GetNPCNameValue(367), 2157, 2156);
        RecipeGroupID.Scorpions = RecipeGroup.RegisterGroup("Scorpions", rec);
        rec = new RecipeGroup(() => Lang.misc[37].Value + " " + Lang.GetNPCNameValue(299), 2018, 3563);
        RecipeGroupID.Squirrels = RecipeGroup.RegisterGroup("Squirrels", rec);
        rec = new RecipeGroup(() => Lang.misc[37].Value + " " + Lang.misc[85].Value, 3194, 3192, 3193);
        RecipeGroupID.Bugs = RecipeGroup.RegisterGroup("Bugs", rec);
        rec = new RecipeGroup(() => Lang.misc[37].Value + " " + Lang.misc[86].Value, 2123, 2122);
        RecipeGroupID.Ducks = RecipeGroup.RegisterGroup("Ducks", rec);
        rec = new RecipeGroup(() => Lang.misc[37].Value + " " + Lang.misc[87].Value, 1998, 2001, 1994, 1995, 1996, 1999, 1997, 2000);
        RecipeGroupID.Butterflies = RecipeGroup.RegisterGroup("Butterflies", rec);
        rec = new RecipeGroup(() => Lang.misc[37].Value + " " + Lang.misc[88].Value, 1992, 2004);
        RecipeGroupID.Fireflies = RecipeGroup.RegisterGroup("Fireflies", rec);
        rec = new RecipeGroup(() => Lang.misc[37].Value + " " + Lang.misc[95].Value, 2006, 2007);
        RecipeGroupID.Snails = RecipeGroup.RegisterGroup("Snails", rec);
        rec = new RecipeGroup(() => Lang.misc[37].Value + " " + Lang.misc[105].Value, 4334, 4335, 4336, 4338, 4339, 4337);
        RecipeGroupID.Dragonflies = RecipeGroup.RegisterGroup("Dragonflies", rec);
        rec = new RecipeGroup(() => Lang.misc[37].Value + " " + Lang.GetNPCNameValue(616), 4464, 4465);
        RecipeGroupID.Turtles = RecipeGroup.RegisterGroup("Turtles", rec);
        rec = new RecipeGroup(() => Lang.misc[37].Value + " " + Language.GetTextValue("Misc.Macaw"), 5212, 5300);
        RecipeGroupID.Macaws = RecipeGroup.RegisterGroup("Macaws", rec);
        rec = new RecipeGroup(() => Lang.misc[37].Value + " " + Language.GetTextValue("Misc.Cockatiel"), 5312, 5313);
        RecipeGroupID.Cockatiels = RecipeGroup.RegisterGroup("Cockatiels", rec);
        rec = new RecipeGroup(() => Lang.misc[37].Value + " " + Language.GetTextValue("Misc.CloudBalloon"), 399, 1250);
        RecipeGroupID.CloudBalloons = RecipeGroup.RegisterGroup("Cloud Balloons", rec);
        rec = new RecipeGroup(() => Lang.misc[37].Value + " " + Language.GetTextValue("Misc.BlizzardBalloon"), 1163, 1251);
        RecipeGroupID.BlizzardBalloons = RecipeGroup.RegisterGroup("Blizzard Balloons", rec);
        rec = new RecipeGroup(() => Lang.misc[37].Value + " " + Language.GetTextValue("Misc.SandstormBalloon"), 983, 1252);
        RecipeGroupID.SandstormBalloons = RecipeGroup.RegisterGroup("Sandstorm Balloons", rec);
        rec = new RecipeGroup(() => Lang.misc[37].Value + " " + Language.GetTextValue("Misc.CritterGuides"), 4767, 5453);
        RecipeGroupID.CritterGuides = RecipeGroup.RegisterGroup("Guide to Critter Companionship", rec);
        rec = new RecipeGroup(() => Lang.misc[37].Value + " " + Language.GetTextValue("Misc.NatureGuides"), 5309, 5454);
        RecipeGroupID.NatureGuides = RecipeGroup.RegisterGroup("Guide to Nature Preservation", rec);
        rec = new RecipeGroup(() => Lang.misc[37].Value + " " + Language.GetTextValue("Misc.Fruit"), 4009, 4282, 4283, 4284, 4285, 4286, 4287, 4288, 4289, 4290, 4291, 4292, 4293, 4294, 4295, 4296, 4297, 5277, 5278);
        RecipeGroupID.Fruit = RecipeGroup.RegisterGroup("Fruit", rec);
        rec = new RecipeGroup(() => Lang.misc[37].Value + " " + Language.GetTextValue("Misc.Balloon"), 3738, 3736, 3737);
        RecipeGroupID.Balloons = RecipeGroup.RegisterGroup("Balloons", rec);
        rec = new RecipeGroup(() => "replaceme wood", 9, 619, 620, 621, 911, 1729, 2504, 2503, 5215);
        RecipeGroupID.Wood = RecipeGroup.RegisterGroup("Wood", rec);
        rec = new RecipeGroup(() => "replaceme sand", 169, 408, 1246, 370, 3272, 3338, 3274, 3275);
        RecipeGroupID.Sand = RecipeGroup.RegisterGroup("Sand", rec);
        rec = new RecipeGroup(() => "replaceme ironbar", 22, 704);
        RecipeGroupID.IronBar = RecipeGroup.RegisterGroup("IronBar", rec);
        rec = new RecipeGroup(() => "replaceme fragment", 3458, 3456, 3457, 3459);
        RecipeGroupID.Fragment = RecipeGroup.RegisterGroup("Fragment", rec);
        rec = new RecipeGroup(() => "replaceme pressureplate", 852, 543, 542, 541, 1151, 529, 853, 4261);
        RecipeGroupID.PressurePlate = RecipeGroup.RegisterGroup("PressurePlate", rec);
    }
References Terraria.Lang.GetNPCNameValue(), Terraria.Localization.Language.GetTextValue(), Terraria.Lang.misc, and Terraria.RecipeGroup.RegisterGroup().
Referenced by Terraria.Recipe.SetupRecipes().