Terraria: Terraria.Recipe.FindRecipes
FindRecipes()
static void Terraria.Recipe.FindRecipes (bool canDelayCheck = false) inline static
    {
        if (canDelayCheck)
        {
            _hasDelayedFindRecipes = true;
            return;
        }
        int oldRecipe = Main.availableRecipe[Main.focusRecipe];
        float focusY = Main.availableRecipeY[Main.focusRecipe];
        ClearAvailableRecipes();
        if (!Main.guideItem.IsAir && Main.guideItem.Name != "")
        {
            CollectGuideRecipes();
            TryRefocusingRecipe(oldRecipe);
            VisuallyRepositionRecipes(focusY);
            return;
        }
        Player localPlayer = Main.LocalPlayer;
        CollectItemsToCraftWithFrom(localPlayer);
        for (int i = 0; i < maxRecipes; i++)
        {
            Recipe recipe = Main.recipe[i];
            if (recipe.createItem.type == 0)
            {
                break;
            }
            if (PlayerMeetsTileRequirements(localPlayer, recipe) && PlayerMeetsEnvironmentConditions(localPlayer, recipe) && CollectedEnoughItemsToCraftRecipeNew(recipe))
            {
                AddToAvailableRecipes(i);
            }
        }
        TryRefocusingRecipe(oldRecipe);
        VisuallyRepositionRecipes(focusY);
    }
References Terraria.Recipe._hasDelayedFindRecipes, Terraria.Recipe.AddToAvailableRecipes(), Terraria.Main.availableRecipe, Terraria.Main.availableRecipeY, Terraria.Recipe.ClearAvailableRecipes(), Terraria.Recipe.CollectedEnoughItemsToCraftRecipeNew(), Terraria.Recipe.CollectGuideRecipes(), Terraria.Recipe.CollectItemsToCraftWithFrom(), Terraria.Recipe.createItem, Terraria.Main.focusRecipe, Terraria.Main.guideItem, Terraria.Item.IsAir, Terraria.Main.LocalPlayer, Terraria.Recipe.maxRecipes, Terraria.Item.Name, Terraria.Recipe.PlayerMeetsEnvironmentConditions(), Terraria.Recipe.PlayerMeetsTileRequirements(), Terraria.Main.recipe, Terraria.Recipe.TryRefocusingRecipe(), Terraria.Item.type, and Terraria.Recipe.VisuallyRepositionRecipes().
Referenced by Terraria.Player.AdjTiles(), Terraria.UI.ItemSlot.AfterItemSwap(), Terraria.UI.ItemSlot.ArmorSwap(), Terraria.DataStructures.TileEntity.BasicOpenCloseInteraction(), Terraria.IngameOptions.Close(), Terraria.Recipe.Create(), Terraria.Chest.DestroyChest(), Terraria.Chest.DestroyChestDirect(), Terraria.UI.ChestUI.DrawButton(), Terraria.Main.DrawInterface_26_InterfaceLogic3(), Terraria.Main.DrawInventory(), Terraria.Main.DrawTrashItemSlot(), Terraria.Player.dropItemCheck(), Terraria.Player.DropSelectedItem(), Terraria.UI.ItemSlot.DyeSwap(), Terraria.UI.ItemSlot.EquipSwap(), Terraria.Player.FillAmmo(), Terraria.NPC.GetChat(), Terraria.MessageBuffer.GetData(), Terraria.Player.GetItem_FillEmptyInventorySlot(), Terraria.Player.GetItem_FillEmptyInventorySlot_VoidBag(), Terraria.Player.GetItem_FillIntoOccupiedSlot(), Terraria.Recipe.GetThroughDelayedFindRecipes(), Terraria.UI.ItemSlot.Handle(), Terraria.UI.ItemSlot.Handle(), Terraria.Player.HandleBeingInChestRange(), Terraria.Main.HoverOverNPCs(), Terraria.Player.ItemCheck_ManageRightClickFeatures(), Terraria.Player.ItemCheckWrapped(), Terraria.UI.ItemSlot.LeftClick(), Terraria.GameContent.Tile_Entities.TEDisplayDoll.OnInventoryDraw(), Terraria.GameContent.Tile_Entities.TEHatRack.OnInventoryDraw(), Terraria.GameContent.Tile_Entities.TEFoodPlatter.OnPlayerInteraction(), Terraria.GameContent.Tile_Entities.TEItemFrame.OnPlayerInteraction(), Terraria.GameContent.Tile_Entities.TEWeaponsRack.OnPlayerInteraction(), Terraria.GameContent.Tile_Entities.TEDisplayDoll.OnPlayerUpdate(), Terraria.GameContent.Tile_Entities.TEHatRack.OnPlayerUpdate(), Terraria.Player.OpenInventory(), Terraria.UI.ItemSlot.OverrideLeftClick(), Terraria.UI.ItemSlot.PickupItemIntoMouse(), Terraria.Player.QuickBuff(), Terraria.Player.QuickHeal(), Terraria.Player.QuickMana(), Terraria.UI.ItemSlot.SellOrTrash(), Terraria.UI.ItemSlot.SwapEquip(), Terraria.UI.ItemSlot.SwapVanityEquip(), Terraria.Player.TileInteractionsUse(), Terraria.Player.ToggleCreativeMenu(), Terraria.GameContent.Creative.CreativeUI.ToggleMenu(), Terraria.Main.TryFreeingElderSlime(), Terraria.Main.TryInteractingWithMoneyTrough(), Terraria.Main.TryInteractingWithMoneyTrough2(), Terraria.Main.TryInteractingWithVoidLens(), and Terraria.UI.ItemSlot.TryOpenContainer().