Terraria: Terraria.Recipe.Create
Create()
void Terraria.Recipe.Create () inline
    {
        Item[] array = null;
        Item item = null;
        Item item2 = null;
        for (int i = 0; i < maxRequirements; i++)
        {
            item2 = requiredItem[i];
            if (item2.type == 0)
            {
                break;
            }
            int num = item2.stack;
            if (alchemy && Main.player[Main.myPlayer].alchemyTable)
            {
                if (num > 1)
                {
                    int num2 = 0;
                    for (int j = 0; j < num; j++)
                    {
                        if (Main.rand.Next(3) == 0)
{
                            num2++;
                        }
                    }
                    num -= num2;
                }
                else if (Main.rand.Next(3) == 0)
                {
                    num = 0;
                }
            }
            if (num <= 0)
            {
                continue;
            }
            array = Main.player[Main.myPlayer].inventory;
            for (int k = 0; k < 58; k++)
            {
                item = array[k];
                if (num <= 0)
                {
                    break;
                }
                if (item.IsTheSameAs(item2) || useWood(item.type, item2.type) || useSand(item.type, item2.type) || useFragment(item.type, item2.type) || useIronBar(item.type, item2.type) || usePressurePlate(item.type, item2.type) || AcceptedByItemGroups(item.type, item2.type))
                {
                    if (item.stack > num)
                    {
                        item.stack -= num;
                        num = 0;
                    }
                    else
                    {
                        num -= item.stack;
                        array[k] = new Item();
                    }
                }
            }
            if (Main.player[Main.myPlayer].chest != -1)
            {
                if (Main.player[Main.myPlayer].chest > -1)
                {
                    array = Main.chest[Main.player[Main.myPlayer].chest].item;
                }
                else if (Main.player[Main.myPlayer].chest == -2)
                {
                    array = Main.player[Main.myPlayer].bank.item;
                }
                else if (Main.player[Main.myPlayer].chest == -3)
                {
                    array = Main.player[Main.myPlayer].bank2.item;
                }
                else if (Main.player[Main.myPlayer].chest == -4)
                {
                    array = Main.player[Main.myPlayer].bank3.item;
                }
                else if (Main.player[Main.myPlayer].chest == -5)
                {
                    array = Main.player[Main.myPlayer].bank4.item;
                }
                for (int l = 0; l < 40; l++)
                {
                    item = array[l];
                    if (num <= 0)
                    {
                        break;
                    }
                    if (!item.IsTheSameAs(item2) && !useWood(item.type, item2.type) && !useSand(item.type, item2.type) && !useIronBar(item.type, item2.type) && !usePressurePlate(item.type, item2.type) && !useFragment(item.type, item2.type) && !AcceptedByItemGroups(item.type, item2.type))
                    {
                        continue;
                    }
                    if (item.stack > num)
                    {
                        item.stack -= num;
                        if (Main.netMode == 1 && Main.player[Main.myPlayer].chest >= 0)
{
                            NetMessage.SendData(32, -1, -1, null, Main.player[Main.myPlayer].chest, l);
                        }
                        num = 0;
                    }
                    else
                    {
                        num -= item.stack;
                        array[l] = new Item();
                        if (Main.netMode == 1 && Main.player[Main.myPlayer].chest >= 0)
{
                            NetMessage.SendData(32, -1, -1, null, Main.player[Main.myPlayer].chest, l);
                        }
                    }
                }
            }
            if (!Main.player[Main.myPlayer].useVoidBag() || Main.player[Main.myPlayer].chest == -5)
            {
                continue;
            }
            array = Main.player[Main.myPlayer].bank4.item;
            for (int m = 0; m < 40; m++)
            {
                item = array[m];
                if (num <= 0)
                {
                    break;
                }
                if (!item.IsTheSameAs(item2) && !useWood(item.type, item2.type) && !useSand(item.type, item2.type) && !useIronBar(item.type, item2.type) && !usePressurePlate(item.type, item2.type) && !useFragment(item.type, item2.type) && !AcceptedByItemGroups(item.type, item2.type))
                {
                    continue;
                }
                if (item.stack > num)
                {
                    item.stack -= num;
                    if (Main.netMode == 1 && Main.player[Main.myPlayer].chest >= 0)
                    {
                        NetMessage.SendData(32, -1, -1, null, Main.player[Main.myPlayer].chest, m);
                    }
                    num = 0;
                }
                else
                {
                    num -= item.stack;
                    array[m] = new Item();
                    if (Main.netMode == 1 && Main.player[Main.myPlayer].chest >= 0)
                    {
                        NetMessage.SendData(32, -1, -1, null, Main.player[Main.myPlayer].chest, m);
                    }
                }
            }
        }
        AchievementsHelper.NotifyItemCraft(this);
        AchievementsHelper.NotifyItemPickup(Main.player[Main.myPlayer], createItem);
        FindRecipes();
    }
References Terraria.Recipe.AcceptedByItemGroups(), Terraria.Recipe.alchemy, Terraria.Player.alchemyTable, Terraria.Player.bank, Terraria.Player.bank2, Terraria.Player.bank3, Terraria.Player.bank4, Terraria.Main.chest, Terraria.Player.chest, Terraria.Recipe.createItem, Terraria.Recipe.FindRecipes(), Terraria.Player.inventory, Terraria.Item.IsTheSameAs(), Terraria.Chest.item, Terraria.Recipe.maxRequirements, Terraria.Main.myPlayer, Terraria.Main.netMode, Terraria.GameContent.Achievements.AchievementsHelper.NotifyItemCraft(), Terraria.GameContent.Achievements.AchievementsHelper.NotifyItemPickup(), Terraria.Main.player, Terraria.Main.rand, Terraria.Recipe.requiredItem, Terraria.NetMessage.SendData(), Terraria.Item.stack, Terraria.Item.type, Terraria.Recipe.useFragment(), Terraria.Recipe.useIronBar(), Terraria.Recipe.usePressurePlate(), Terraria.Recipe.useSand(), Terraria.Player.useVoidBag(), and Terraria.Recipe.useWood().