Terraria: Terraria.Recipe.usePressurePlate
usePressurePlate()
bool Terraria.Recipe.usePressurePlate (int invType, int reqType) inline
Definition at line 409 of file Recipe.cs.
    {
        if (!anyPressurePlate)
        {
            return false;
        }
        switch (reqType)
        {
        default:
            return false;
        case 529:
        case 541:
        case 542:
        case 543:
        case 852:
        case 853:
        case 1151:
        case 4261:
            switch (invType)
            {
            default:
                return false;
            case 529:
            case 541:
            case 542:
            case 543:
            case 852:
            case 853:
            case 1151:
            case 4261:
                return true;
            }
        }
    }
References Terraria.Recipe.anyPressurePlate.
Referenced by Terraria.Recipe.CollectedEnoughItemsToCraftRecipeOld(), Terraria.Recipe.CollectGuideRecipes(), and Terraria.Recipe.Create().