Terraria: Terraria.Recipe.createItem
createItem
Item Terraria.Recipe.createItem = new Item()
Definition at line 27 of file Recipe.cs.
Referenced by Terraria.Recipe.AddAshWoodFurnitureArmorAndItems(), Terraria.Recipe.AddBalloonFurniture(), Terraria.Recipe.AddBambooFurniture(), Terraria.Recipe.AddCoralFurniture(), Terraria.Recipe.AddLesionFurniture(), Terraria.Recipe.AddNebulaFurniture(), Terraria.Recipe.AddSandstoneFurniture(), Terraria.Recipe.AddSolarFurniture(), Terraria.Recipe.AddSpiderFurniture(), Terraria.Recipe.AddStardustFurniture(), Terraria.Recipe.AddVortexFurniture(), Terraria.Recipe.CollectGuideRecipes(), Terraria.Recipe.Create(), Terraria.Recipe.CreateReversePlatformRecipes(), Terraria.Recipe.CreateReverseWallRecipes(), Terraria.Item.FindDecraftAmount(), Terraria.Recipe.FindRecipes(), Terraria.Initializers.DyeInitializer.FixRecipes(), Terraria.Initializers.UILinksInitializer.Load(), Terraria.GameContent.Achievements.AchievementsHelper.NotifyItemCraft(), Terraria.Recipe.SetupRecipes(), Terraria.Main.TryAllowingToCraftRecipe(), Terraria.Recipe.UpdateItemVariants(), Terraria.Recipe.UpdateMaterialFieldForAllRecipes(), and Terraria.Recipe.UpdateWhichItemsAreCrafted().