Terraria: Terraria.GameContent.UI.Elements.UIList.UpdateScrollbar
UpdateScrollbar()
void Terraria.GameContent.UI.Elements.UIList.UpdateScrollbar () inline private
Definition at line 132 of file UIList.cs.
    {
        if (_scrollbar != null)
        {
            float height = GetInnerDimensions().Height;
            _scrollbar.SetView(height, _innerListHeight);
        }
    }
References Terraria.GameContent.UI.Elements.UIList._innerListHeight, Terraria.GameContent.UI.Elements.UIList._scrollbar, Terraria.UI.UIElement.GetInnerDimensions(), Terraria.UI.CalculatedStyle.Height, and Terraria.GameContent.UI.Elements.UIScrollbar.SetView().
Referenced by Terraria.GameContent.UI.Elements.UIList.Recalculate(), Terraria.GameContent.UI.Elements.UIList.SetScrollbar(), and Terraria.GameContent.UI.Elements.UIList.UpdateOrder().