Terraria: Terraria.Recipe.CollectItemsToCraftWithFrom
CollectItemsToCraftWithFrom()
static void Terraria.Recipe.CollectItemsToCraftWithFrom (Player player) inline static private
Definition at line 569 of file Recipe.cs.
    {
        _ownedItems.Clear();
        CollectItems(player.inventory, 58);
        if (player.useVoidBag() && player.chest != -5)
        {
            CollectItems(player.bank4.item, 40);
        }
        if (player.chest != -1)
        {
            Item[] currentInventory = null;
            if (player.chest > -1)
            {
                currentInventory = Main.chest[player.chest].item;
            }
            else if (player.chest == -2)
            {
                currentInventory = player.bank.item;
            }
            else if (player.chest == -3)
            {
                currentInventory = player.bank2.item;
            }
            else if (player.chest == -4)
            {
                currentInventory = player.bank3.item;
            }
            else if (player.chest == -5)
            {
                currentInventory = player.bank4.item;
            }
            CollectItems(currentInventory, 40);
        }
        AddFakeCountsForItemGroups();
    }
References Terraria.Recipe._ownedItems, Terraria.Recipe.AddFakeCountsForItemGroups(), Terraria.Player.bank, Terraria.Player.bank2, Terraria.Player.bank3, Terraria.Player.bank4, Terraria.Main.chest, Terraria.Player.chest, Terraria.Recipe.CollectItems(), Terraria.Player.inventory, Terraria.Chest.item, and Terraria.Player.useVoidBag().
Referenced by Terraria.Recipe.FindRecipes().