Terraria: DD2Film.DryadPortalFade
DryadPortalFade()
void DD2Film.DryadPortalFade (FrameEventData evt) inline private
     {
         if (_dryad == null || _portal == null)
         {
             return;
         }
         if (evt.IsFirstFrame)
         {
             SoundEngine.PlaySound(SoundID.DD2_EtherianPortalDryadTouch, _dryad.Center);
         }
         float val = (float)(evt.Frame - 7) / (float)(evt.Duration - 7);
         val = Math.Max(0f, val);
         _dryad.color = new Color(Vector3.Lerp(Vector3.One, new Vector3(0.5f, 0f, 0.8f), val));
         _dryad.Opacity = 1f - val;
         _dryad.rotation += 0.05f * (val * 4f + 1f);
         _dryad.scale = 1f - val;
         if (_dryad.position.X < _portal.Right.X)
         {
             _dryad.velocity.X *= 0.95f;
             _dryad.velocity.Y *= 0.55f;
         }
         int num = (int)(6f * val);
         float num2 = _dryad.Size.Length() / 2f;
         num2 /= 20f;
         for (int i = 0; i < num; i++)
         {
             if (Main.rand.Next(5) == 0)
             {
                 Dust dust = Dust.NewDustDirect(_dryad.position, _dryad.width, _dryad.height, 27, _dryad.velocity.X * 1f, 0f, 100);
                 dust.scale = 0.55f;
                 dust.fadeIn = 0.7f;
                 dust.velocity *= 0.1f * num2;
                 dust.velocity += _dryad.velocity;
             }
         }
     }
References _dryad, _portal, Entity.Center, Color, NPC.color, SoundID.DD2_EtherianPortalDryadTouch, FrameEventData.Duration, Dust.fadeIn, FrameEventData.Frame, Entity.height, FrameEventData.IsFirstFrame, Dust.NewDustDirect(), UnifiedRandom.Next(), NPC.Opacity, SoundEngine.PlaySound(), Entity.position, Main.rand, Entity.Right, NPC.rotation, Dust.scale, NPC.scale, Entity.Size, Dust.velocity, Entity.velocity, and Entity.width.
Referenced by DD2Film().