Terraria: Terraria.GameContent.UI.States.UIWorkshopWorldImport.UpdateWorkshopWorldList
UpdateWorkshopWorldList()
void Terraria.GameContent.UI.States.UIWorkshopWorldImport.UpdateWorkshopWorldList () inline
Definition at line 142 of file UIWorkshopWorldImport.cs.
    {
        WorkshopWorldList.Clear();
        if (SocialAPI.Workshop == null)
        {
            return;
        }
        foreach (string listOfSubscribedWorldPath in SocialAPI.Workshop.GetListOfSubscribedWorldPaths())
        {
            WorldFileData allMetadata = WorldFile.GetAllMetadata(listOfSubscribedWorldPath, cloudSave: false);
            if (allMetadata != null)
            {
                WorkshopWorldList.Add(allMetadata);
            }
            else
            {
                WorkshopWorldList.Add(WorldFileData.FromInvalidWorld(listOfSubscribedWorldPath, cloudSave: false));
            }
        }
    }
References Terraria.IO.WorldFileData.FromInvalidWorld(), Terraria.IO.WorldFile.GetAllMetadata(), Terraria.Social.SocialAPI.Workshop, and Terraria.GameContent.UI.States.UIWorkshopWorldImport.WorkshopWorldList.
Referenced by Terraria.GameContent.UI.States.UIWorkshopWorldImport.OnActivate().