Terraria: System.Xml.Xsl.XsltOld.ActionFrame.SortNewNodeSet
SortNewNodeSet()
void System.Xml.Xsl.XsltOld.ActionFrame.SortNewNodeSet (Processor proc, ArrayList sortarray) inline package
Definition at line 182 of file ActionFrame.cs.
    {
        int count = sortarray.Count;
        XPathSortComparer xPathSortComparer = new XPathSortComparer(count);
        for (int i = 0; i < count; i++)
        {
            Sort sort = (Sort)sortarray[i];
            Query compiledQuery = proc.GetCompiledQuery(sort.select);
            xPathSortComparer.AddSort(compiledQuery, new XPathComparerHelper(sort.order, sort.caseOrder, sort.lang, sort.dataType));
        }
        List<SortKey> list = new List<SortKey>();
        while (NewNextNode(proc))
        {
            XPathNodeIterator nodeSet = _nodeSet;
            _nodeSet = _newNodeSet;
            SortKey sortKey = new SortKey(count, list.Count, _newNodeSet.Current.Clone());
            for (int j = 0; j < count; j++)
            {
                sortKey[j] = xPathSortComparer.Expression(j).Evaluate(_newNodeSet);
            }
            list.Add(sortKey);
            _nodeSet = nodeSet;
        }
        list.Sort(xPathSortComparer);
        _newNodeSet = new XPathSortArrayIterator(list);
    }
References System.Xml.Xsl.XsltOld.ActionFrame._newNodeSet, System.Xml.Xsl.XsltOld.ActionFrame._nodeSet, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Xml.XPath.XPathNavigator.Clone(), System.count, System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Xml.XPath.XPathNodeIterator.Current, System.Xml.Dictionary, System.list, and System.Xml.Xsl.XsltOld.ActionFrame.NewNextNode().
Referenced by System.Xml.Xsl.XsltOld.ApplyTemplatesAction.Execute(), and System.Xml.Xsl.XsltOld.ForEachAction.Execute().