Terraria: System.Xml.Xsl.XsltOld.ActionFrame.NextNode
NextNode()
bool System.Xml.Xsl.XsltOld.ActionFrame.NextNode (Processor proc) inline package
Definition at line 286 of file ActionFrame.cs.
    {
        bool flag = _nodeSet.MoveNext();
        if (flag && proc.Stylesheet.Whitespace)
        {
            XPathNodeType nodeType = _nodeSet.Current.NodeType;
            if (nodeType == XPathNodeType.Whitespace)
            {
                XPathNavigator xPathNavigator = _nodeSet.Current.Clone();
                bool flag2;
                do
                {
                    xPathNavigator.MoveTo(_nodeSet.Current);
                    xPathNavigator.MoveToParent();
                    flag2 = !proc.Stylesheet.PreserveWhiteSpace(proc, xPathNavigator) && (flag = _nodeSet.MoveNext());
                    nodeType = _nodeSet.Current.NodeType;
                }
                while (flag2 && nodeType == XPathNodeType.Whitespace);
            }
        }
        return flag;
    }
References System.Xml.Xsl.XsltOld.ActionFrame._nodeSet, System.Xml.XPath.XPathNavigator.Clone(), System.Xml.XPath.XPathNodeIterator.Current, System.Xml.Dictionary, System.Xml.XPath.XPathNodeIterator.MoveNext(), and System.Xml.XPath.XPathNavigator.NodeType.
Referenced by System.Xml.Xsl.XsltOld.CopyNodeSetAction.Execute(), and System.Xml.Xsl.XsltOld.RootAction.Execute().