Terraria: Terraria.GameContent.UI.States.UIWorkshopWorldImport.UpdateWorldsList
UpdateWorldsList()
void Terraria.GameContent.UI.States.UIWorkshopWorldImport.UpdateWorldsList () inline private
Definition at line 163 of file UIWorkshopWorldImport.cs.
    {
        _worldList.Clear();
        IOrderedEnumerable<WorldFileData> orderedEnumerable = from x in new List<WorldFileData>(WorkshopWorldList)
            orderby x.IsFavorite descending, x.Name, x.GetFileName()
            select x;
        int num = 0;
        foreach (WorldFileData item in orderedEnumerable)
        {
            _worldList.Add(new UIWorkshopImportWorldListItem(this, item, num++));
        }
    }
References Terraria.GameContent.UI.States.UIWorkshopWorldImport._worldList, Terraria.GameContent.UI.Elements.UIList.Add(), Terraria.GameContent.UI.Elements.UIList.Clear(), System.item, and Terraria.GameContent.UI.States.UIWorkshopWorldImport.WorkshopWorldList.
Referenced by Terraria.GameContent.UI.States.UIWorkshopWorldImport.OnActivate().