Terraria: System.Net.Http.AuthenticationHelper.DigestResponse.Parse
Parse()
void System.Net.Http.AuthenticationHelper.DigestResponse.Parse (string challenge) inline private
Definition at line 162 of file AuthenticationHelper.cs.
        {
            int parsedIndex = 0;
            while (parsedIndex < challenge.Length)
            {
                string nextKey = GetNextKey(challenge, parsedIndex, out parsedIndex);
                if (!string.IsNullOrEmpty(nextKey) && parsedIndex < challenge.Length)
                {
                    string nextValue = GetNextValue(challenge, parsedIndex, MustValueBeQuoted(nextKey), out parsedIndex);
                    if (nextValue != null && (!(nextValue == string.Empty) || nextKey.Equals("opaque", StringComparison.OrdinalIgnoreCase) || nextKey.Equals("domain", StringComparison.OrdinalIgnoreCase) || nextKey.Equals("realm", StringComparison.OrdinalIgnoreCase)))
                    {
                        Parameters.Add(nextKey, nextValue);
                        continue;
                    }
                    break;
                }
                break;
            }
        }
References System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Net.Http.AuthenticationHelper.DigestResponse.GetNextKey(), System.Net.Http.AuthenticationHelper.DigestResponse.GetNextValue(), System.Net.Http.AuthenticationHelper.DigestResponse.MustValueBeQuoted(), and System.Net.Http.AuthenticationHelper.DigestResponse.Parameters.
Referenced by System.Net.Http.AuthenticationHelper.DigestResponse.DigestResponse().