Terraria: System.Text.StringBuilder.AppendInterpolatedStringHandler.AppendFormatted
AppendFormatted() [2/5]
void System.Text.StringBuilder.AppendInterpolatedStringHandler.AppendFormatted (ReadOnlySpan< char > value) inline
Definition at line 249 of file StringBuilder.cs.
        {
            _stringBuilder.Append(value);
        }
References System.Text.StringBuilder.AppendInterpolatedStringHandler._stringBuilder, System.Text.StringBuilder.Append(), and System.value.
Referenced by System.Diagnostics.Tracing.ManifestBuilder.ManifestBuilder(), System.Net.WebSockets.WebSocketHandle.AddWebSocketHeaders(), System.Web.Util.HttpEncoder.AppendCharAsUnicodeJavaScript(), System.Text.StringBuilder.AppendInterpolatedStringHandler.AppendFormatted< T >(), System.Text.StringBuilder.AppendInterpolatedStringHandler.AppendFormatted< T >(), System.Text.StringBuilder.AppendInterpolatedStringHandler.AppendFormattedWithTempSpace< T >(), System.Net.HttpListenerRequestUriBuilder.AppendOctetsPercentEncoded(), System.Xml.XmlConvert.EncodeName(), System.DateTimeFormat.FormatCustomizedTimeZone(), System.Net.HttpListenerRequestUriBuilder.GetOctetsAsString(), System.Text.DecoderExceptionFallbackBuffer.Throw(), System.Text.Json.ThrowHelper.ThrowArgumentException_InvalidUTF8(), System.Text.DecoderFallbackBuffer.ThrowLastBytesRecursive(), System.Linq.Expressions.Interpreter.LightLambda.DebugViewPrinter.ToString(), System.Net.Http.Headers.AltSvcHeaderValue.ToString(), System.Net.Http.Headers.CacheControlHeaderValue.ToString(), System.Net.Http.Headers.WarningHeaderValue.ToString(), System.Security.Authentication.ExtendedProtection.ExtendedProtectionPolicy.ToString(), System.Runtime.InteropServices.COMException.ToString(), MS.Internal.Xml.Cache.XPathNodeInfoTable.ToString(), and System.Net.Cookie.ToString().