Terraria: System.Text.StringBuilder.AppendInterpolatedStringHandler.AppendFormatted< T >
AppendFormatted< T >() [1/4]
void System.Text.StringBuilder.AppendInterpolatedStringHandler.AppendFormatted< T > (T value) inline
Definition at line 142 of file StringBuilder.cs.
        {
            if (_hasCustomFormatter)
            {
                AppendCustomFormatter(value, null);
            }
            else if (value is IFormattable)
            {
                if (value is ISpanFormattable)
                {
                    Span<char> remainingCurrentChunk = _stringBuilder.RemainingCurrentChunk;
                    if (((ISpanFormattable)(object)value).TryFormat(remainingCurrentChunk, out var charsWritten, default(ReadOnlySpan<char>), _provider))
                    {
                        if ((uint)charsWritten > (uint)remainingCurrentChunk.Length)
{
                            FormatError();
                        }
                        _stringBuilder.m_ChunkLength += charsWritten;
                    }
                    else
                    {
                        AppendFormattedWithTempSpace(value, 0, null);
                    }
                }
                else
                {
                    _stringBuilder.Append(((IFormattable)(object)value).ToString(null, _provider));
                }
            }
            else if (value != null)
            {
                _stringBuilder.Append(value.ToString());
            }
        }
References System.Text.StringBuilder.AppendInterpolatedStringHandler._hasCustomFormatter, System.Text.StringBuilder.AppendInterpolatedStringHandler._provider, System.Text.StringBuilder.AppendInterpolatedStringHandler._stringBuilder, System.Text.StringBuilder.Append(), System.Runtime.Serialization.Dictionary, System.Text.StringBuilder.FormatError(), System.Text.StringBuilder.RemainingCurrentChunk, System.Text.StringBuilder.ToString(), and System.value.