Terraria: System.Runtime.Serialization.Formatters.Binary.Converter.FromString
FromString()
static object System.Runtime.Serialization.Formatters.Binary.Converter.FromString (string value, InternalPrimitiveTypeE code) inline static package
Definition at line 375 of file Converter.cs.
    {
        if (code == InternalPrimitiveTypeE.Invalid)
        {
            return value;
        }
        return Convert.ChangeType(value, ToTypeCode(code), CultureInfo.InvariantCulture);
    }
References System.Convert.ChangeType(), System.Runtime.Serialization.Dictionary, System.Globalization.CultureInfo.InvariantCulture, System.Runtime.Serialization.Formatters.Binary.Converter.ToTypeCode(), and System.value.
Referenced by System.Runtime.Serialization.Formatters.Binary.ObjectReader.ParseArrayMember(), and System.Runtime.Serialization.Formatters.Binary.ObjectReader.ParseMember().