Terraria: System.Runtime.CompilerServices.CallSiteBinder.GetRuleCache< T >
GetRuleCache< T >()
RuleCache< T > System.Runtime.CompilerServices.CallSiteBinder.GetRuleCache< T > () inline package
Type Constraints
T : class
Definition at line 104 of file CallSiteBinder.cs.
                                                    : class
    {
        if (Cache == null)
        {
            Interlocked.CompareExchange(ref Cache, new Dictionary<Type, object>(), null);
        }
        Dictionary<Type, object> cache = Cache;
        object value;
        lock (cache)
        {
            if (!cache.TryGetValue(typeof(T), out value))
            {
                value = (cache[typeof(T)] = new RuleCache<T>());
            }
        }
        return value as RuleCache<T>;
    }
References System.Runtime.CompilerServices.CallSiteBinder.Cache, System.Threading.Interlocked.CompareExchange(), System.Collections.Generic.Dictionary< TKey, TValue >.TryGetValue(), and System.value.
Referenced by System.Runtime.CompilerServices.CallSiteBinder.CacheTarget< T >().