Terraria: System.Runtime.Serialization.Formatters.Binary.Converter.s_typeofString
s_typeofString
readonly Type System.Runtime.Serialization.Formatters.Binary.Converter.s_typeofString = typeof(string) static package
Definition at line 11 of file Converter.cs.
Referenced by System.Runtime.Serialization.Formatters.Binary.BinaryTypeConverter.GetBinaryTypeInfo(), System.Runtime.Serialization.Formatters.Binary.BinaryTypeConverter.GetParserBinaryTypeInfo(), System.Runtime.Serialization.Formatters.Binary.ObjectReader.ParseArray(), System.Runtime.Serialization.Formatters.Binary.ObjectReader.ParseArrayMember(), System.Runtime.Serialization.Formatters.Binary.ObjectReader.ParseMember(), System.Runtime.Serialization.Formatters.Binary.ObjectReader.ParseObject(), System.Runtime.Serialization.Formatters.Binary.ObjectReader.ParseObjectEnd(), System.Runtime.Serialization.Formatters.Binary.BinaryParser.ReadObjectString(), System.Runtime.Serialization.Formatters.Binary.BinaryTypeConverter.TypeFromInfo(), System.Runtime.Serialization.Formatters.Binary.ObjectWriter.Write(), System.Runtime.Serialization.Formatters.Binary.ObjectWriter.Write(), and System.Runtime.Serialization.Formatters.Binary.ObjectWriter.WriteKnownValueClass().