Terraria: AmbientSky.WyvernSkyEntity.WyvernSkyEntity
WyvernSkyEntity()
AmbientSky.WyvernSkyEntity.WyvernSkyEntity (Player player, FastRandom random) inline
References Main.Assets, AmbientSky.FadingSkyEntity.BrightnessLerper, AmbientSky.SkyEntity.Depth, AmbientSky.SkyEntity.Effects, AmbientSky.FadingSkyEntity.FinalOpacityMultiplier, AmbientSky.SkyEntity.Frame, AmbientSky.FadingSkyEntity.FramingSpeed, AmbientSky.FadingSkyEntity.LifeTime, FastRandom.Next(), FastRandom.NextFloat(), AmbientSky.FadingSkyEntity.OpacityNormalizedTimeToFadeIn, AmbientSky.FadingSkyEntity.OpacityNormalizedTimeToFadeOut, AmbientSky.SkyEntity.Position, VirtualCamera.Position, AmbientSky.SkyEntity.SetPositionInWorldBasedOnScreenSpace(), VirtualCamera.Size, AmbientSky.SkyEntity.Texture, Main.WindForVisuals, and Main.worldSurface.