Terraria: System.Runtime.Serialization.Formatters.Binary.Converter.ToType
ToType()
static Type System.Runtime.Serialization.Formatters.Binary.Converter.ToType (InternalPrimitiveTypeE code) inline static package
Definition at line 199 of file Converter.cs.
    {
        if (s_typeA == null)
        {
            InitTypeA();
        }
        return s_typeA[(int)code];
    }
References System.Runtime.Serialization.Dictionary, System.Runtime.Serialization.Formatters.Binary.Converter.InitTypeA(), and System.Runtime.Serialization.Formatters.Binary.Converter.s_typeA.
Referenced by System.Runtime.Serialization.Formatters.Binary.BinaryParser.ReadMemberPrimitiveTyped(), System.Runtime.Serialization.Formatters.Binary.BinaryParser.ReadMemberPrimitiveUnTyped(), and System.Runtime.Serialization.Formatters.Binary.BinaryTypeConverter.TypeFromInfo().