Terraria: System.Runtime.CompilerServices.CallSiteBinder.Stitch< T >
Stitch< T >()
static Expression< T > System.Runtime.CompilerServices.CallSiteBinder.Stitch< T > (Expression binding, LambdaSignature< T > signature) inline static private
Type Constraints
T : class
Definition at line 91 of file CallSiteBinder.cs.
                                                                                                     : class
    {
        Type typeFromHandle = typeof(CallSite<T>);
        ReadOnlyCollectionBuilder<Expression> readOnlyCollectionBuilder = new ReadOnlyCollectionBuilder<Expression>(3);
        readOnlyCollectionBuilder.Add(binding);
        ParameterExpression parameterExpression = Expression.Parameter(typeof(CallSite), "$site");
        TrueReadOnlyCollection<ParameterExpression> trueReadOnlyCollection = signature.Parameters.AddFirst(parameterExpression);
        Expression item = Expression.Label(UpdateLabel);
        readOnlyCollectionBuilder.Add(item);
        readOnlyCollectionBuilder.Add(Expression.Label(signature.ReturnLabel, Expression.Condition(Expression.Call(CachedReflectionInfo.CallSiteOps_SetNotMatched, parameterExpression), Expression.Default(signature.ReturnLabel.Type), Expression.Invoke(Expression.Property(Expression.Convert(parameterExpression, typeFromHandle), typeof(CallSite<T>).GetProperty("Update")), trueReadOnlyCollection))));
        return Expression.Lambda<T>(Expression.Block(readOnlyCollectionBuilder), "CallSite.Target", tailCall: true, trueReadOnlyCollection);
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Linq.Expressions.Expression< TDelegate >.Block(), System.Linq.Expressions.Expression< TDelegate >.Call(), System.Linq.Expressions.CachedReflectionInfo.CallSiteOps_SetNotMatched, System.Linq.Expressions.Expression< TDelegate >.Condition(), System.Linq.Expressions.Expression< TDelegate >.Convert(), System.Linq.Expressions.Expression< TDelegate >.Default(), System.Reflection.GetProperty, System.Linq.Expressions.Expression< TDelegate >.Invoke(), System.item, System.Linq.Expressions.Expression< TDelegate >.Label(), System.Linq.Expressions.Expression< TDelegate >.Lambda(), System.Linq.Expressions.Expression< TDelegate >.Parameter(), System.Linq.Expressions.Expression< TDelegate >.Property(), and System.Runtime.CompilerServices.CallSiteBinder.UpdateLabel.