Terraria: System.Net.HttpResponseStream.WriteCore
WriteCore()
unsafe void System.Net.HttpResponseStream.WriteCore (byte[] buffer, int offset, int size) inline private
Definition at line 185 of file HttpResponseStream.cs.
    {
        global::Interop.HttpApi.HTTP_FLAGS hTTP_FLAGS = ComputeLeftToWrite();
        if (size == 0 && _leftToWrite != 0L)
        {
            return;
        }
        if (_leftToWrite >= 0 && size > _leftToWrite)
        {
            throw new ProtocolViolationException(System.SR.net_entitytoobig);
        }
        uint num = (uint)size;
        Microsoft.Win32.SafeHandles.SafeLocalAllocHandle safeLocalAllocHandle = null;
        IntPtr zero = IntPtr.Zero;
        bool sentHeaders = _httpContext.Response.SentHeaders;
        uint num2;
        try
        {
            if (size == 0)
            {
                num2 = _httpContext.Response.SendHeaders(null, null, hTTP_FLAGS, isWebSocketHandshake: false);
            }
            else
            {
                fixed (byte* ptr = buffer)
                {
                    byte* ptr2 = ptr;
                    if (_httpContext.Response.BoundaryType == BoundaryType.Chunked)
                    {
                        string text = size.ToString("x", CultureInfo.InvariantCulture);
                        num += (uint)(text.Length + 4);
                        safeLocalAllocHandle = Microsoft.Win32.SafeHandles.SafeLocalAllocHandle.LocalAlloc((int)num);
                        zero = safeLocalAllocHandle.DangerousGetHandle();
                        for (int i = 0; i < text.Length; i++)
{
                            Marshal.WriteByte(zero, i, (byte)text[i]);
                        }
                        Marshal.WriteInt16(zero, text.Length, 2573);
                        Marshal.Copy(buffer, offset, zero + text.Length + 2, size);
                        Marshal.WriteInt16(zero, (int)(num - 2), 2573);
                        ptr2 = (byte*)(void*)zero;
                        offset = 0;
                    }
                    global::Interop.HttpApi.HTTP_DATA_CHUNK hTTP_DATA_CHUNK = default(global::Interop.HttpApi.HTTP_DATA_CHUNK);
                    hTTP_DATA_CHUNK.DataChunkType = global::Interop.HttpApi.HTTP_DATA_CHUNK_TYPE.HttpDataChunkFromMemory;
                    hTTP_DATA_CHUNK.pBuffer = ptr2 + offset;
                    hTTP_DATA_CHUNK.BufferLength = num;
                    hTTP_FLAGS |= ((_leftToWrite != size) ? global::Interop.HttpApi.HTTP_FLAGS.HTTP_SEND_RESPONSE_FLAG_MORE_DATA : global::Interop.HttpApi.HTTP_FLAGS.NONE);
                    if (!sentHeaders)
                    {
                        num2 = _httpContext.Response.SendHeaders(&hTTP_DATA_CHUNK, null, hTTP_FLAGS, isWebSocketHandshake: false);
                    }
                    else
                    {
                        if (System.Net.NetEventSource.Log.IsEnabled())
{
                            System.Net.NetEventSource.Info(this, "Calling Interop.HttpApi.HttpSendResponseEntityBody", "WriteCore");
                        }
                        num2 = global::Interop.HttpApi.HttpSendResponseEntityBody(_httpContext.RequestQueueHandle, _httpContext.RequestId, (uint)hTTP_FLAGS, 1, &hTTP_DATA_CHUNK, null, Microsoft.Win32.SafeHandles.SafeLocalAllocHandle.Zero, 0u, null, null);
                        if (System.Net.NetEventSource.Log.IsEnabled())
{
                            System.Net.NetEventSource.Info(this, "Call to Interop.HttpApi.HttpSendResponseEntityBody returned:" + num2, "WriteCore");
                        }
                        if (_httpContext.Listener.IgnoreWriteExceptions)
{
                            if (System.Net.NetEventSource.Log.IsEnabled())
{
                                System.Net.NetEventSource.Info(this, "Write() suppressing error", "WriteCore");
                            }
                            num2 = 0u;
                        }
                    }
                }
            }
        }
        finally
        {
            safeLocalAllocHandle?.Close();
        }
        if (num2 != 0 && num2 != 38)
        {
            Exception ex = new HttpListenerException((int)num2);
            if (System.Net.NetEventSource.Log.IsEnabled())
            {
                System.Net.NetEventSource.Error(this, ex.ToString(), "WriteCore");
            }
            _closed = true;
            _httpContext.Abort();
            throw ex;
        }
        UpdateAfterWrite(num);
        if (System.Net.NetEventSource.Log.IsEnabled())
        {
            System.Net.NetEventSource.DumpBuffer(this, buffer, offset, (int)num, "WriteCore");
        }
    }
References System.Net.HttpResponseStream._closed, System.Net.HttpResponseStream._httpContext, System.Net.HttpResponseStream._leftToWrite, System.Net.HttpListenerContext.Abort(), System.Net.HttpListenerResponse.BoundaryType, System.buffer, System.Runtime.InteropServices.SafeHandle.Close(), System.Net.HttpResponseStream.ComputeLeftToWrite(), System.Runtime.InteropServices.Marshal.Copy(), System.Runtime.InteropServices.SafeHandle.DangerousGetHandle(), System.Net.NetEventSource.DumpBuffer(), System.Net.NetEventSource.Error(), System.Net.HttpListener.IgnoreWriteExceptions, System.Net.NetEventSource.Info(), System.Globalization.CultureInfo.InvariantCulture, System.L, System.Net.HttpListenerContext.Listener, Microsoft.Win32.SafeHandles.SafeLocalAllocHandle.LocalAlloc(), System.Net.NetEventSource.Log, System.SR.net_entitytoobig, System.offset, System.Net.HttpListenerContext.RequestId, System.Net.HttpListenerContext.RequestQueueHandle, System.Net.HttpListenerContext.Response, System.Net.HttpListenerResponse.SendHeaders(), System.Net.HttpListenerResponse.SentHeaders, System.text, System.Exception.ToString(), System.Net.HttpResponseStream.UpdateAfterWrite(), System.Runtime.InteropServices.Marshal.WriteByte(), System.Runtime.InteropServices.Marshal.WriteInt16(), Microsoft.Win32.SafeHandles.SafeLocalAllocHandle.Zero, and System.IntPtr.Zero.
Referenced by System.Net.HttpResponseStream.Write().