Terraria: System.Net.HttpResponseStream.BeginWriteCore
BeginWriteCore()
unsafe IAsyncResult System.Net.HttpResponseStream.BeginWriteCore (byte[] buffer, int offset, int size, AsyncCallback callback, object state) inline private
Definition at line 282 of file HttpResponseStream.cs.
    {
        global::Interop.HttpApi.HTTP_FLAGS hTTP_FLAGS = ComputeLeftToWrite();
        if (_closed || (size == 0 && _leftToWrite != 0L))
        {
            HttpResponseStreamAsyncResult httpResponseStreamAsyncResult = new HttpResponseStreamAsyncResult(this, state, callback);
            httpResponseStreamAsyncResult.InvokeCallback(0u);
            return httpResponseStreamAsyncResult;
        }
        if (_leftToWrite >= 0 && size > _leftToWrite)
        {
            throw new ProtocolViolationException(System.SR.net_entitytoobig);
        }
        uint numBytes = 0u;
        hTTP_FLAGS |= ((_leftToWrite != size) ? global::Interop.HttpApi.HTTP_FLAGS.HTTP_SEND_RESPONSE_FLAG_MORE_DATA : global::Interop.HttpApi.HTTP_FLAGS.NONE);
        bool sentHeaders = _httpContext.Response.SentHeaders;
        HttpResponseStreamAsyncResult httpResponseStreamAsyncResult2 = new HttpResponseStreamAsyncResult(this, state, callback, buffer, offset, size, _httpContext.Response.BoundaryType == BoundaryType.Chunked, sentHeaders, _httpContext.RequestQueueBoundHandle);
        UpdateAfterWrite((_httpContext.Response.BoundaryType != BoundaryType.Chunked) ? ((uint)size) : 0u);
        uint num;
        try
        {
            if (!sentHeaders)
            {
                num = _httpContext.Response.SendHeaders(null, httpResponseStreamAsyncResult2, hTTP_FLAGS, isWebSocketHandshake: false);
            }
            else
            {
                if (System.Net.NetEventSource.Log.IsEnabled())
                {
                    System.Net.NetEventSource.Info(this, "Calling Interop.HttpApi.HttpSendResponseEntityBody", "BeginWriteCore");
                }
                num = global::Interop.HttpApi.HttpSendResponseEntityBody(_httpContext.RequestQueueHandle, _httpContext.RequestId, (uint)hTTP_FLAGS, httpResponseStreamAsyncResult2.dataChunkCount, httpResponseStreamAsyncResult2.pDataChunks, &numBytes, Microsoft.Win32.SafeHandles.SafeLocalAllocHandle.Zero, 0u, httpResponseStreamAsyncResult2._pOverlapped, null);
                if (System.Net.NetEventSource.Log.IsEnabled())
                {
                    System.Net.NetEventSource.Info(this, "Call to Interop.HttpApi.HttpSendResponseEntityBody returned:" + num, "BeginWriteCore");
                }
            }
        }
        catch (Exception ex)
        {
            if (System.Net.NetEventSource.Log.IsEnabled())
            {
                System.Net.NetEventSource.Error(this, ex.ToString(), "BeginWriteCore");
            }
            httpResponseStreamAsyncResult2.InternalCleanup();
            _closed = true;
            _httpContext.Abort();
            throw;
        }
        if (num != 0 && num != 997)
        {
            httpResponseStreamAsyncResult2.InternalCleanup();
            if (!(_httpContext.Listener.IgnoreWriteExceptions && sentHeaders))
            {
                Exception ex2 = new HttpListenerException((int)num);
                if (System.Net.NetEventSource.Log.IsEnabled())
                {
                    System.Net.NetEventSource.Error(this, ex2.ToString(), "BeginWriteCore");
                }
                _closed = true;
                _httpContext.Abort();
                throw ex2;
            }
            if (System.Net.NetEventSource.Log.IsEnabled())
            {
                System.Net.NetEventSource.Info(this, "BeginWrite() Suppressing error", "BeginWriteCore");
            }
        }
        if (num == 0 && HttpListener.SkipIOCPCallbackOnSuccess)
        {
            httpResponseStreamAsyncResult2.IOCompleted(num, numBytes);
        }
        if ((hTTP_FLAGS & global::Interop.HttpApi.HTTP_FLAGS.HTTP_SEND_RESPONSE_FLAG_MORE_DATA) == 0)
        {
            _lastWrite = httpResponseStreamAsyncResult2;
        }
        return httpResponseStreamAsyncResult2;
    }
References System.Net.HttpResponseStream._closed, System.Net.HttpResponseStream._httpContext, System.Net.HttpResponseStream._lastWrite, System.Net.HttpResponseStream._leftToWrite, System.Net.HttpResponseStreamAsyncResult._pOverlapped, System.Net.HttpListenerContext.Abort(), System.Net.HttpListenerResponse.BoundaryType, System.buffer, System.Net.HttpResponseStream.ComputeLeftToWrite(), System.Net.HttpResponseStreamAsyncResult.dataChunkCount, System.Net.NetEventSource.Error(), System.Net.HttpListener.IgnoreWriteExceptions, System.Net.NetEventSource.Info(), System.Net.LazyAsyncResult.InternalCleanup(), System.Net.LazyAsyncResult.InvokeCallback(), System.Net.HttpResponseStreamAsyncResult.IOCompleted(), System.L, System.Net.HttpListenerContext.Listener, System.Net.NetEventSource.Log, System.SR.net_entitytoobig, System.offset, System.Net.HttpResponseStreamAsyncResult.pDataChunks, System.Net.HttpListenerContext.RequestId, System.Net.HttpListenerContext.RequestQueueBoundHandle, System.Net.HttpListenerContext.RequestQueueHandle, System.Net.HttpListenerContext.Response, System.Net.HttpListenerResponse.SendHeaders(), System.Net.HttpListenerResponse.SentHeaders, System.Net.HttpListener.SkipIOCPCallbackOnSuccess, System.state, System.Exception.ToString(), System.Net.HttpResponseStream.UpdateAfterWrite(), and Microsoft.Win32.SafeHandles.SafeLocalAllocHandle.Zero.
Referenced by System.Net.HttpResponseStream.BeginWrite().