Terraria: System.Net.HttpResponseStream.EndWriteCore
EndWriteCore()
void System.Net.HttpResponseStream.EndWriteCore (IAsyncResult asyncResult) inline private
Definition at line 361 of file HttpResponseStream.cs.
    {
        if (!(asyncResult is HttpResponseStreamAsyncResult httpResponseStreamAsyncResult) || httpResponseStreamAsyncResult.AsyncObject != this)
        {
            throw new ArgumentException(System.SR.net_io_invalidasyncresult, "asyncResult");
        }
        if (httpResponseStreamAsyncResult.EndCalled)
        {
            throw new InvalidOperationException(System.SR.Format(System.SR.net_io_invalidendcall, "EndWrite"));
        }
        httpResponseStreamAsyncResult.EndCalled = true;
        object obj = httpResponseStreamAsyncResult.InternalWaitForCompletion();
        if (obj is Exception ex)
        {
            if (System.Net.NetEventSource.Log.IsEnabled())
            {
                System.Net.NetEventSource.Error(this, "Rethrowing exception:" + ex, "EndWriteCore");
            }
            _closed = true;
            _httpContext.Abort();
            ExceptionDispatchInfo.Throw(ex);
        }
    }
References System.Net.HttpResponseStream._closed, System.Net.HttpResponseStream._httpContext, System.Net.HttpListenerContext.Abort(), System.asyncResult, System.Net.NetEventSource.Error(), System.SR.Format(), System.Net.NetEventSource.Log, System.SR.net_io_invalidasyncresult, System.SR.net_io_invalidendcall, System.obj, and System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw().
Referenced by System.Net.HttpResponseStream.EndWrite().