Terraria: System.Net.HttpResponseStream.DisposeCore
DisposeCore()
unsafe void System.Net.HttpResponseStream.DisposeCore () inline private
Definition at line 408 of file HttpResponseStream.cs.
    {
        global::Interop.HttpApi.HTTP_FLAGS hTTP_FLAGS = ComputeLeftToWrite();
        if (_leftToWrite > 0 && !_inOpaqueMode)
        {
            throw new InvalidOperationException(System.SR.net_io_notenoughbyteswritten);
        }
        bool sentHeaders = _httpContext.Response.SentHeaders;
        if (sentHeaders && _leftToWrite == 0L)
        {
            return;
        }
        uint num = 0u;
        if ((_httpContext.Response.BoundaryType == BoundaryType.Chunked || _httpContext.Response.BoundaryType == BoundaryType.None) && !string.Equals(_httpContext.Request.HttpMethod, "HEAD", StringComparison.OrdinalIgnoreCase))
        {
            if (_httpContext.Response.BoundaryType == BoundaryType.None)
            {
                hTTP_FLAGS |= global::Interop.HttpApi.HTTP_FLAGS.HTTP_RECEIVE_REQUEST_FLAG_COPY_BODY;
            }
            fixed (byte* ptr = &s_chunkTerminator[0])
            {
                void* pBuffer = ptr;
                global::Interop.HttpApi.HTTP_DATA_CHUNK* ptr2 = null;
                if (_httpContext.Response.BoundaryType == BoundaryType.Chunked)
                {
                    global::Interop.HttpApi.HTTP_DATA_CHUNK hTTP_DATA_CHUNK = default(global::Interop.HttpApi.HTTP_DATA_CHUNK);
                    hTTP_DATA_CHUNK.DataChunkType = global::Interop.HttpApi.HTTP_DATA_CHUNK_TYPE.HttpDataChunkFromMemory;
                    hTTP_DATA_CHUNK.pBuffer = (byte*)pBuffer;
                    hTTP_DATA_CHUNK.BufferLength = (uint)s_chunkTerminator.Length;
                    ptr2 = &hTTP_DATA_CHUNK;
                }
                if (!sentHeaders)
                {
                    num = _httpContext.Response.SendHeaders(ptr2, null, hTTP_FLAGS, isWebSocketHandshake: false);
                }
                else
                {
                    if (System.Net.NetEventSource.Log.IsEnabled())
                    {
                        System.Net.NetEventSource.Info(this, "Calling Interop.HttpApi.HttpSendResponseEntityBody", "DisposeCore");
                    }
                    num = global::Interop.HttpApi.HttpSendResponseEntityBody(_httpContext.RequestQueueHandle, _httpContext.RequestId, (uint)hTTP_FLAGS, (ushort)((ptr2 != null) ? 1 : 0), ptr2, null, Microsoft.Win32.SafeHandles.SafeLocalAllocHandle.Zero, 0u, null, null);
                    if (System.Net.NetEventSource.Log.IsEnabled())
                    {
                        System.Net.NetEventSource.Info(this, "Call to Interop.HttpApi.HttpSendResponseEntityBody returned:" + num, "DisposeCore");
                    }
                    if (_httpContext.Listener.IgnoreWriteExceptions)
                    {
                        if (System.Net.NetEventSource.Log.IsEnabled())
{
                            System.Net.NetEventSource.Info(this, "Suppressing error", "DisposeCore");
                        }
                        num = 0u;
                    }
                }
            }
        }
        else if (!sentHeaders)
        {
            num = _httpContext.Response.SendHeaders(null, null, hTTP_FLAGS, isWebSocketHandshake: false);
        }
        if (num != 0 && num != 38)
        {
            Exception ex = new HttpListenerException((int)num);
            if (System.Net.NetEventSource.Log.IsEnabled())
            {
                System.Net.NetEventSource.Error(this, ex.ToString(), "DisposeCore");
            }
            _httpContext.Abort();
            throw ex;
        }
        _leftToWrite = 0L;
    }
References System.Net.HttpResponseStream._httpContext, System.Net.HttpResponseStream._inOpaqueMode, System.Net.HttpResponseStream._leftToWrite, System.Net.HttpListenerContext.Abort(), System.Net.HttpListenerResponse.BoundaryType, System.Net.HttpResponseStream.ComputeLeftToWrite(), System.Net.NetEventSource.Error(), System.Net.HttpListenerRequest.HttpMethod, System.Net.HttpListener.IgnoreWriteExceptions, System.Net.NetEventSource.Info(), System.L, System.Net.HttpListenerContext.Listener, System.Net.NetEventSource.Log, System.SR.net_io_notenoughbyteswritten, System.Net.HttpListenerContext.Request, System.Net.HttpListenerContext.RequestId, System.Net.HttpListenerContext.RequestQueueHandle, System.Net.HttpListenerContext.Response, System.Net.HttpResponseStream.s_chunkTerminator, System.Net.HttpListenerResponse.SendHeaders(), System.Net.HttpListenerResponse.SentHeaders, System.Exception.ToString(), and Microsoft.Win32.SafeHandles.SafeLocalAllocHandle.Zero.
Referenced by System.Net.HttpResponseStream.Dispose().