Terraria: System.Reflection.Metadata.BlobContentId.GetTimeBasedProvider
GetTimeBasedProvider()
static Func< IEnumerable< Blob >, BlobContentId > System.Reflection.Metadata.BlobContentId.GetTimeBasedProvider () inline static
Definition at line 88 of file BlobContentId.cs.
    {
        uint timestamp = (uint)(DateTime.UtcNow - new DateTime(1970, 1, 1)).TotalSeconds;
        return (IEnumerable<Blob> content) => new BlobContentId(Guid.NewGuid(), timestamp);
    }
References System.Reflection.Metadata.BlobContentId.BlobContentId(), System.Guid.NewGuid(), and System.DateTime.UtcNow.
Referenced by System.Reflection.PortableExecutable.PEBuilder.PEBuilder(), and System.Reflection.Metadata.Ecma335.PortablePdbBuilder.PortablePdbBuilder().