Terraria: System.Net.Quic.Implementations.MsQuic.Internal.MsQuicAddressHelpers.IPEndPointToINet
IPEndPointToINet()
static unsafe MsQuicNativeMethods.SOCKADDR_INET System.Net.Quic.Implementations.MsQuic.Internal.MsQuicAddressHelpers.IPEndPointToINet (IPEndPoint endpoint) inline static package
Definition at line 17 of file MsQuicAddressHelpers.cs.
    {
        MsQuicNativeMethods.SOCKADDR_INET socketAddrInet = default(MsQuicNativeMethods.SOCKADDR_INET);
        if (!endpoint.Address.Equals(IPAddress.Any) && !endpoint.Address.Equals(IPAddress.IPv6Any))
        {
            int bytesWritten;
            switch (endpoint.Address.AddressFamily)
            {
            case AddressFamily.InterNetwork:
                endpoint.Address.TryWriteBytes(MemoryMarshal.CreateSpan(ref socketAddrInet.Ipv4.sin_addr[0], 4), out bytesWritten);
                socketAddrInet.Ipv4.sin_family = 2;
                break;
            case AddressFamily.InterNetworkV6:
                endpoint.Address.TryWriteBytes(MemoryMarshal.CreateSpan(ref socketAddrInet.Ipv6.sin6_addr[0], 16), out bytesWritten);
                socketAddrInet.Ipv6.sin6_family = 23;
                break;
            default:
                throw new ArgumentException(System.SR.net_quic_addressfamily_notsupported);
            }
        }
        SetPort(endpoint.Address.AddressFamily, ref socketAddrInet, endpoint.Port);
        return socketAddrInet;
    }
References System.Net.IPEndPoint.Address, System.Net.IPAddress.AddressFamily, System.Net.IPAddress.Any, System.Net.IPAddress.Equals(), System.Net.Quic.Implementations.MsQuic.Internal.MsQuicNativeMethods.SOCKADDR_INET.Ipv4, System.Net.Quic.Implementations.MsQuic.Internal.MsQuicNativeMethods.SOCKADDR_INET.Ipv6, System.Net.IPAddress.IPv6Any, System.SR.net_quic_addressfamily_notsupported, System.Net.IPEndPoint.Port, System.Net.Quic.Implementations.MsQuic.Internal.MsQuicAddressHelpers.SetPort(), System.Net.Quic.Implementations.MsQuic.Internal.MsQuicNativeMethods.SOCKADDR_IN6.sin6_addr, System.Net.Quic.Implementations.MsQuic.Internal.MsQuicNativeMethods.SOCKADDR_IN.sin_addr, and System.Net.IPAddress.TryWriteBytes().
Referenced by System.Net.Quic.Implementations.MsQuic.MsQuicConnection.ConnectAsync(), and System.Net.Quic.Implementations.MsQuic.MsQuicListener.Start().