Terraria: System.Net.Quic.Implementations.MsQuic.Internal.MsQuicAddressHelpers.INetToIPEndPoint
INetToIPEndPoint()
static unsafe IPEndPoint System.Net.Quic.Implementations.MsQuic.Internal.MsQuicAddressHelpers.INetToIPEndPoint (ref MsQuicNativeMethods::SOCKADDR_INET inetAddress) inline static package
Definition at line 8 of file MsQuicAddressHelpers.cs.
    {
        if (inetAddress.si_family == 2)
        {
            return new IPEndPoint(new IPAddress(MemoryMarshal.CreateReadOnlySpan(ref inetAddress.Ipv4.sin_addr[0], 4)), (ushort)IPAddress.NetworkToHostOrder((short)inetAddress.Ipv4.sin_port));
        }
        return new IPEndPoint(new IPAddress(MemoryMarshal.CreateReadOnlySpan(ref inetAddress.Ipv6.sin6_addr[0], 16)), (ushort)IPAddress.NetworkToHostOrder((short)inetAddress.Ipv6.sin6_port));
    }
References System.Net.IPAddress.NetworkToHostOrder().
Referenced by System.Net.Quic.Implementations.MsQuic.MsQuicConnection.HandleEventConnected(), System.Net.Quic.Implementations.MsQuic.MsQuicListener.NativeCallbackHandler(), and System.Net.Quic.Implementations.MsQuic.MsQuicListener.Start().