Terraria: System.Data.ConstraintCollection.FinishInitConstraints
FinishInitConstraints()
void System.Data.ConstraintCollection.FinishInitConstraints () inline package
Definition at line 630 of file ConstraintCollection.cs.
    {
        if (_delayLoadingConstraints == null)
        {
            return;
        }
        for (int i = 0; i < _delayLoadingConstraints.Length; i++)
        {
            int num;
            DataColumn[] array;
            if (_delayLoadingConstraints[i] is UniqueConstraint)
            {
                if (_fLoadForeignKeyConstraintsOnly)
                {
                    continue;
                }
                UniqueConstraint uniqueConstraint = (UniqueConstraint)_delayLoadingConstraints[i];
                if (uniqueConstraint._columnNames == null)
                {
                    Add(uniqueConstraint);
                    continue;
                }
                num = uniqueConstraint._columnNames.Length;
                array = new DataColumn[num];
                for (int j = 0; j < num; j++)
                {
                    array[j] = _table.Columns[uniqueConstraint._columnNames[j]];
                }
                if (uniqueConstraint._bPrimaryKey)
                {
                    if (_table._primaryKey != null)
                    {
                        throw ExceptionBuilder.AddPrimaryKeyConstraint();
                    }
                    Add(uniqueConstraint.ConstraintName, array, primaryKey: true);
                }
                else
                {
                    UniqueConstraint constraint = new UniqueConstraint(uniqueConstraint._constraintName, array);
                    if (FindConstraint(constraint) == null)
                    {
                        Add(constraint);
                    }
                }
                continue;
            }
            ForeignKeyConstraint foreignKeyConstraint = (ForeignKeyConstraint)_delayLoadingConstraints[i];
            if (foreignKeyConstraint._parentColumnNames == null || foreignKeyConstraint._childColumnNames == null)
            {
                Add(foreignKeyConstraint);
                continue;
            }
            if (_table.DataSet == null)
            {
                _fLoadForeignKeyConstraintsOnly = true;
                continue;
            }
            num = foreignKeyConstraint._parentColumnNames.Length;
            array = new DataColumn[num];
            DataColumn[] array2 = new DataColumn[num];
            for (int k = 0; k < num; k++)
            {
                if (foreignKeyConstraint._parentTableNamespace == null)
                {
                    array[k] = _table.DataSet.Tables[foreignKeyConstraint._parentTableName].Columns[foreignKeyConstraint._parentColumnNames[k]];
                }
                else
                {
                    array[k] = _table.DataSet.Tables[foreignKeyConstraint._parentTableName, foreignKeyConstraint._parentTableNamespace].Columns[foreignKeyConstraint._parentColumnNames[k]];
                }
                array2[k] = _table.Columns[foreignKeyConstraint._childColumnNames[k]];
            }
            ForeignKeyConstraint foreignKeyConstraint2 = new ForeignKeyConstraint(foreignKeyConstraint._constraintName, array, array2);
            foreignKeyConstraint2.AcceptRejectRule = foreignKeyConstraint._acceptRejectRule;
            foreignKeyConstraint2.DeleteRule = foreignKeyConstraint._deleteRule;
            foreignKeyConstraint2.UpdateRule = foreignKeyConstraint._updateRule;
            Add(foreignKeyConstraint2);
        }
        if (!_fLoadForeignKeyConstraintsOnly)
        {
            _delayLoadingConstraints = null;
        }
    }
References System.Data.ForeignKeyConstraint._acceptRejectRule, System.Data.UniqueConstraint._bPrimaryKey, System.Data.ForeignKeyConstraint._childColumnNames, System.Data.UniqueConstraint._columnNames, System.Data.ForeignKeyConstraint._constraintName, System.Data.UniqueConstraint._constraintName, System.Data.ConstraintCollection._delayLoadingConstraints, System.Data.ForeignKeyConstraint._deleteRule, System.Data.ConstraintCollection._fLoadForeignKeyConstraintsOnly, System.Data.ForeignKeyConstraint._parentColumnNames, System.Data.ForeignKeyConstraint._parentTableName, System.Data.ForeignKeyConstraint._parentTableNamespace, System.Data.DataTable._primaryKey, System.Data.ConstraintCollection._table, System.Data.ForeignKeyConstraint._updateRule, System.Data.Add, System.Data.ExceptionBuilder.AddPrimaryKeyConstraint(), System.array, System.Data.DataTable.Columns, System.Data.Constraint.ConstraintName, System.Data.DataTable.DataSet, System.Data.ConstraintCollection.FindConstraint(), and System.Data.DataSet.Tables.
Referenced by System.Data.DataTable.EndInit().