Terraria: System.Data.ConstraintCollection.Clear
Clear()
void System.Data.ConstraintCollection.Clear () inline
Definition at line 348 of file ConstraintCollection.cs.
    {
        _table.PrimaryKey = null;
        for (int i = 0; i < _table.ParentRelations.Count; i++)
        {
            _table.ParentRelations[i].SetChildKeyConstraint(null);
        }
        for (int j = 0; j < _table.ChildRelations.Count; j++)
        {
            _table.ChildRelations[j].SetParentKeyConstraint(null);
        }
        if (_table.fInitInProgress && _delayLoadingConstraints != null)
        {
            _delayLoadingConstraints = null;
            _fLoadForeignKeyConstraintsOnly = false;
        }
        int count = List.Count;
        Constraint[] array = new Constraint[List.Count];
        List.CopyTo(array, 0);
        try
        {
            BaseGroupSwitch(array, count, Array.Empty<Constraint>(), 0);
        }
        catch (Exception e) when (ADP.IsCatchableOrSecurityExceptionType(e))
        {
            BaseGroupSwitch(Array.Empty<Constraint>(), 0, array, count);
            List.Clear();
            for (int k = 0; k < count; k++)
            {
                List.Add(array[k]);
            }
            throw;
        }
        List.Clear();
        OnCollectionChanged(InternalDataCollectionBase.s_refreshEventArgs);
    }
References System.Data.ConstraintCollection._delayLoadingConstraints, System.Data.ConstraintCollection._fLoadForeignKeyConstraintsOnly, System.Data.ConstraintCollection._table, System.Collections.ArrayList.Add(), System.array, System.Data.ConstraintCollection.BaseGroupSwitch(), System.Data.DataTable.ChildRelations, System.Collections.ArrayList.Clear(), System.Collections.ArrayList.CopyTo(), System.Data.InternalDataCollectionBase.Count, System.count, System.Collections.ArrayList.Count, System.Data.DataTable.fInitInProgress, System.Data.Common.ADP.IsCatchableOrSecurityExceptionType(), System.Data.ConstraintCollection.List, System.Data.ConstraintCollection.OnCollectionChanged(), System.Data.DataTable.ParentRelations, and System.Data.InternalDataCollectionBase.s_refreshEventArgs.
Referenced by System.Data.DataTable.ResetConstraints().