Terraria: System.Data.ConstraintCollection.UnregisterName
UnregisterName()
void System.Data.ConstraintCollection.UnregisterName (string name) inline package
Definition at line 618 of file ConstraintCollection.cs.
    {
        if (NamesEqual(name, MakeName(_defaultNameIndex - 1), fCaseSensitive: true, _table.Locale) != 0)
        {
            do
            {
                _defaultNameIndex--;
            }
            while (_defaultNameIndex > 1 && !Contains(MakeName(_defaultNameIndex - 1)));
        }
    }
References System.Data.ConstraintCollection._defaultNameIndex, System.Data.ConstraintCollection._table, System.Data.ConstraintCollection.Contains(), System.Data.DataTable.Locale, System.Data.ConstraintCollection.MakeName(), and System.Data.InternalDataCollectionBase.NamesEqual().
Referenced by System.Data.ConstraintCollection.BaseRemove().