Terraria: System.Data.ConstraintCollection.Add
Add() [2/6]
void System.Data.ConstraintCollection.Add (Constraint constraint, bool addUniqueWhenAddingForeign) inline package
Definition at line 79 of file ConstraintCollection.cs.
    {
        if (constraint == null)
        {
            throw ExceptionBuilder.ArgumentNull("constraint");
        }
        Constraint constraint2 = FindConstraint(constraint);
        if (constraint2 != null)
        {
            throw ExceptionBuilder.DuplicateConstraint(constraint2.ConstraintName);
        }
        if (1 < _table.NestedParentRelations.Length && !AutoGenerated(constraint))
        {
            throw ExceptionBuilder.CantAddConstraintToMultipleNestedTable(_table.TableName);
        }
        if (constraint is UniqueConstraint)
        {
            if (((UniqueConstraint)constraint)._bPrimaryKey && Table._primaryKey != null)
            {
                throw ExceptionBuilder.AddPrimaryKeyConstraint();
            }
            AddUniqueConstraint((UniqueConstraint)constraint);
        }
        else if (constraint is ForeignKeyConstraint)
        {
            ForeignKeyConstraint foreignKeyConstraint = (ForeignKeyConstraint)constraint;
            if (addUniqueWhenAddingForeign)
            {
                UniqueConstraint uniqueConstraint = foreignKeyConstraint.RelatedTable.Constraints.FindKeyConstraint(foreignKeyConstraint.RelatedColumnsReference);
                if (uniqueConstraint == null)
                {
                    if (constraint.ConstraintName.Length == 0)
                    {
                        constraint.ConstraintName = AssignName();
                    }
                    else
                    {
                        RegisterName(constraint.ConstraintName);
                    }
                    uniqueConstraint = new UniqueConstraint(foreignKeyConstraint.RelatedColumnsReference);
                    foreignKeyConstraint.RelatedTable.Constraints.Add(uniqueConstraint);
                }
            }
            AddForeignKeyConstraint((ForeignKeyConstraint)constraint);
        }
        BaseAdd(constraint);
        ArrayAdd(constraint);
        OnCollectionChanged(new CollectionChangeEventArgs(CollectionChangeAction.Add, constraint));
        if (constraint is UniqueConstraint && ((UniqueConstraint)constraint)._bPrimaryKey)
        {
            Table.PrimaryKey = ((UniqueConstraint)constraint).ColumnsReference;
        }
    }
References System.Data.DataTable._primaryKey, System.Data.ConstraintCollection._table, System.Data.ConstraintCollection.Add(), System.Data.ConstraintCollection.AddForeignKeyConstraint(), System.Data.ExceptionBuilder.AddPrimaryKeyConstraint(), System.Data.ConstraintCollection.AddUniqueConstraint(), System.Data.ExceptionBuilder.ArgumentNull(), System.Data.ConstraintCollection.ArrayAdd(), System.Data.ConstraintCollection.AssignName(), System.Data.ConstraintCollection.AutoGenerated(), System.Data.ConstraintCollection.BaseAdd(), System.Data.ExceptionBuilder.CantAddConstraintToMultipleNestedTable(), System.Data.Constraint.ConstraintName, System.Data.DataTable.Constraints, System.Data.ExceptionBuilder.DuplicateConstraint(), System.Data.ConstraintCollection.FindConstraint(), System.Data.ConstraintCollection.FindKeyConstraint(), System.Data.DataTable.NestedParentRelations, System.Data.ConstraintCollection.OnCollectionChanged(), System.Data.ConstraintCollection.RegisterName(), System.Data.ForeignKeyConstraint.RelatedColumnsReference, System.Data.ForeignKeyConstraint.RelatedTable, System.Data.ConstraintCollection.Table, and System.Data.DataTable.TableName.