Terraria: System.Data.ConstraintCollection.InternalIndexOf
InternalIndexOf()
int System.Data.ConstraintCollection.InternalIndexOf (string constraintName) inline package
Definition at line 527 of file ConstraintCollection.cs.
    {
        int num = -1;
        if (constraintName != null && 0 < constraintName.Length)
        {
            int count = List.Count;
            int num2 = 0;
            for (int i = 0; i < count; i++)
            {
                Constraint constraint = (Constraint)List[i];
                switch (NamesEqual(constraint.ConstraintName, constraintName, fCaseSensitive: false, _table.Locale))
                {
                case 1:
                    return i;
                case -1:
                    num = ((num == -1) ? i : (-2));
                    break;
                }
            }
        }
        return num;
    }
References System.Data.ConstraintCollection._table, System.Data.Constraint.ConstraintName, System.count, System.Collections.ArrayList.Count, System.Data.ConstraintCollection.List, System.Data.DataTable.Locale, and System.Data.InternalDataCollectionBase.NamesEqual().
Referenced by System.Data.ConstraintCollection.Contains(), System.Data.ConstraintCollection.Contains(), and System.Data.ConstraintCollection.IndexOf().