Terraria: System.Data.ConstraintCollection.AddUniqueConstraint
AddUniqueConstraint()
void System.Data.ConstraintCollection.AddUniqueConstraint (UniqueConstraint constraint) inline private
Definition at line 192 of file ConstraintCollection.cs.
    {
        DataColumn[] columnsReference = constraint.ColumnsReference;
        for (int i = 0; i < columnsReference.Length; i++)
        {
            if (columnsReference[i].Table != _table)
            {
                throw ExceptionBuilder.ConstraintForeignTable();
            }
        }
        constraint.ConstraintIndexInitialize();
        if (!constraint.CanEnableConstraint())
        {
            constraint.ConstraintIndexClear();
            throw ExceptionBuilder.UniqueConstraintViolation();
        }
    }
References System.Data.ConstraintCollection._table, System.Data.UniqueConstraint.CanEnableConstraint(), System.Data.UniqueConstraint.ColumnsReference, System.Data.ExceptionBuilder.ConstraintForeignTable(), System.Data.UniqueConstraint.ConstraintIndexClear(), System.Data.UniqueConstraint.ConstraintIndexInitialize(), System.Data.ConstraintCollection.Table, and System.Data.ExceptionBuilder.UniqueConstraintViolation().
Referenced by System.Data.ConstraintCollection.Add().