Terraria: System.Data.ConstraintCollection.FindKeyConstraint
FindKeyConstraint() [2/2]
UniqueConstraint System.Data.ConstraintCollection.FindKeyConstraint (DataColumn[] columns) inline package
Definition at line 437 of file ConstraintCollection.cs.
    {
        int count = List.Count;
        for (int i = 0; i < count; i++)
        {
            if (List[i] is UniqueConstraint { Key: var key } uniqueConstraint && CompareArrays(key.ColumnsReference, columns))
            {
                return uniqueConstraint;
            }
        }
        return null;
    }
References System.Data.ConstraintCollection.CompareArrays(), System.count, System.Collections.ArrayList.Count, System.key, and System.Data.ConstraintCollection.List.
Referenced by System.Data.ConstraintCollection.Add(), System.Data.DataRelationCollection.DataSetRelationCollection.AddCore(), System.Data.DataColumn.SetOrdinalInternal(), and System.Data.DataColumn.SetTable().