Terraria: System.Data.ConstraintCollection.Remove
Remove() [1/2]
void System.Data.ConstraintCollection.Remove (Constraint constraint) inline
Definition at line 580 of file ConstraintCollection.cs.
    {
        if (constraint == null)
        {
            throw ExceptionBuilder.ArgumentNull("constraint");
        }
        if (CanRemove(constraint, fThrowException: true))
        {
            BaseRemove(constraint);
            ArrayRemove(constraint);
            if (constraint is UniqueConstraint && ((UniqueConstraint)constraint).IsPrimaryKey)
            {
                Table.PrimaryKey = null;
            }
            OnCollectionChanged(new CollectionChangeEventArgs(CollectionChangeAction.Remove, constraint));
        }
    }
References System.Data.ExceptionBuilder.ArgumentNull(), System.Data.ConstraintCollection.ArrayRemove(), System.Data.ConstraintCollection.BaseRemove(), System.Data.ConstraintCollection.CanRemove(), and System.Data.ConstraintCollection.OnCollectionChanged().
Referenced by System.Data.DataColumn.SetOrdinalInternal().