Terraria: System.Data.ConstraintCollection.CopyTo
CopyTo() [2/2]
void System.Data.ConstraintCollection.CopyTo (Constraint[] array, int index) inline
Definition at line 404 of file ConstraintCollection.cs.
    {
        if (array == null)
        {
            throw ExceptionBuilder.ArgumentNull("array");
        }
        if (index < 0)
        {
            throw ExceptionBuilder.ArgumentOutOfRange("index");
        }
        if (array.Length - index < _list.Count)
        {
            throw ExceptionBuilder.InvalidOffsetLength();
        }
        for (int i = 0; i < _list.Count; i++)
        {
            array[index + i] = (Constraint)_list[i];
        }
    }
References System.Data.ConstraintCollection._list, System.Data.ExceptionBuilder.ArgumentNull(), System.Data.ExceptionBuilder.ArgumentOutOfRange(), System.array, System.Collections.ArrayList.Count, System.index, and System.Data.ExceptionBuilder.InvalidOffsetLength().