Terraria: System.Data.ConstraintCollection.BaseRemove
BaseRemove()
void System.Data.ConstraintCollection.BaseRemove (Constraint constraint) inline private
Definition at line 297 of file ConstraintCollection.cs.
    {
        if (constraint == null)
        {
            throw ExceptionBuilder.ArgumentNull("constraint");
        }
        if (constraint.Table != _table)
        {
            throw ExceptionBuilder.ConstraintRemoveFailed();
        }
        UnregisterName(constraint.ConstraintName);
        constraint.InCollection = false;
        if (constraint is UniqueConstraint)
        {
            for (int i = 0; i < Table.ChildRelations.Count; i++)
            {
                DataRelation dataRelation = Table.ChildRelations[i];
                if (dataRelation.ParentKeyConstraint == constraint)
                {
                    dataRelation.SetParentKeyConstraint(null);
                }
            }
            ((UniqueConstraint)constraint).ConstraintIndexClear();
        }
        else
        {
            if (!(constraint is ForeignKeyConstraint))
            {
                return;
            }
            for (int j = 0; j < Table.ParentRelations.Count; j++)
            {
                DataRelation dataRelation2 = Table.ParentRelations[j];
                if (dataRelation2.ChildKeyConstraint == constraint)
                {
                    dataRelation2.SetChildKeyConstraint(null);
                }
            }
        }
    }
References System.Data.ConstraintCollection._table, System.Data.ExceptionBuilder.ArgumentNull(), System.Data.DataRelation.ChildKeyConstraint, System.Data.DataTable.ChildRelations, System.Data.Constraint.ConstraintName, System.Data.ExceptionBuilder.ConstraintRemoveFailed(), System.Data.InternalDataCollectionBase.Count, System.Data.DataRelation.ParentKeyConstraint, System.Data.DataTable.ParentRelations, System.Data.DataRelation.SetChildKeyConstraint(), System.Data.DataRelation.SetParentKeyConstraint(), System.Data.Constraint.Table, System.Data.ConstraintCollection.Table, and System.Data.ConstraintCollection.UnregisterName().
Referenced by System.Data.ConstraintCollection.BaseGroupSwitch(), and System.Data.ConstraintCollection.Remove().