Terraria: System.Data.ConstraintCollection.BaseGroupSwitch
BaseGroupSwitch()
void System.Data.ConstraintCollection.BaseGroupSwitch (Constraint[] oldArray, int oldLength, Constraint[] newArray, int newLength) inline private
Definition at line 263 of file ConstraintCollection.cs.
    {
        int num = 0;
        for (int i = 0; i < oldLength; i++)
        {
            bool flag = false;
            for (int j = num; j < newLength; j++)
            {
                if (oldArray[i] == newArray[j])
                {
                    if (num == j)
                    {
                        num++;
                    }
                    flag = true;
                    break;
                }
            }
            if (!flag)
            {
                BaseRemove(oldArray[i]);
                List.Remove(oldArray[i]);
            }
        }
        for (int k = 0; k < newLength; k++)
        {
            if (!newArray[k].InCollection)
            {
                BaseAdd(newArray[k]);
            }
            List.Add(newArray[k]);
        }
    }
References System.Collections.ArrayList.Add(), System.Data.ConstraintCollection.BaseAdd(), System.Data.ConstraintCollection.BaseRemove(), System.Data.ConstraintCollection.List, and System.Collections.ArrayList.Remove().
Referenced by System.Data.ConstraintCollection.Clear().