Terraria: System.Transactions.PreparingEnlistment.RecoveryInformation
RecoveryInformation()
byte[] System.Transactions.PreparingEnlistment.RecoveryInformation () inline
Definition at line 64 of file PreparingEnlistment.cs.
    {
        TransactionsEtwProvider log = TransactionsEtwProvider.Log;
        if (log.IsEnabled())
        {
            log.MethodEnter(TraceSourceType.TraceSourceLtm, this, "RecoveryInformation");
        }
        try
        {
            lock (_internalEnlistment.SyncRoot)
            {
                return _internalEnlistment.State.RecoveryInformation(_internalEnlistment);
            }
        }
        finally
        {
            if (log.IsEnabled())
            {
                log.MethodExit(TraceSourceType.TraceSourceLtm, this, "RecoveryInformation");
            }
        }
    }
References System.Transactions.Enlistment._internalEnlistment, System.Diagnostics.Tracing.EventSource.IsEnabled(), System.Transactions.TransactionsEtwProvider.Log, System.Transactions.TransactionsEtwProvider.MethodEnter(), System.Transactions.TransactionsEtwProvider.MethodExit(), System.Transactions.EnlistmentState.RecoveryInformation(), System.Transactions.InternalEnlistment.State, and System.Transactions.InternalEnlistment.SyncRoot.