Terraria: System.Runtime.CompilerServices.CallSiteBinder.LambdaSignature.LambdaSignature
LambdaSignature()
System.Runtime.CompilerServices.CallSiteBinder.LambdaSignature< T >.LambdaSignature () inline private
Definition at line 32 of file CallSiteBinder.cs.
        {
            Type typeFromHandle = typeof(T);
            if (!typeFromHandle.IsSubclassOf(typeof(MulticastDelegate)))
            {
                throw Error.TypeParameterIsNotDelegate(typeFromHandle);
            }
            MethodInfo invokeMethod = typeFromHandle.GetInvokeMethod();
            ParameterInfo[] parametersCached = invokeMethod.GetParametersCached();
            if (parametersCached[0].ParameterType != typeof(CallSite))
            {
                throw Error.FirstArgumentMustBeCallSite();
            }
            ParameterExpression[] array = new ParameterExpression[parametersCached.Length - 1];
            for (int i = 0; i < array.Length; i++)
            {
                array[i] = Expression.Parameter(parametersCached[i + 1].ParameterType, "$arg" + i);
            }
            Parameters = new TrueReadOnlyCollection<ParameterExpression>(array);
            ReturnLabel = Expression.Label(invokeMethod.GetReturnType());
        }
References System.array, System.Linq.Expressions.Error.FirstArgumentMustBeCallSite(), System.Linq.Expressions.Expression< TDelegate >.Label(), System.Linq.Expressions.Expression< TDelegate >.Parameter(), System.Runtime.CompilerServices.CallSiteBinder.LambdaSignature< T >.Parameters, System.Runtime.CompilerServices.CallSiteBinder.LambdaSignature< T >.ReturnLabel, and System.Linq.Expressions.Error.TypeParameterIsNotDelegate().