Terraria: Microsoft.Xna.Framework.Graphics.GraphicsDevice.DrawPrimitives
DrawPrimitives()
unsafe void Microsoft.Xna.Framework.Graphics.GraphicsDevice.DrawPrimitives (PrimitiveType primitiveType, int startVertex, int primitiveCount) inline
Definition at line 1280 of file GraphicsDevice.cs.
    {
        IntPtr intPtr = (IntPtr)pComPtr;
        Helpers.CheckDisposed(this, intPtr);
        if (primitiveCount <= 0)
        {
            throw new ArgumentOutOfRangeException("primitiveCount", FrameworkResources.MustDrawSomething);
        }
        int maxPrimitiveCount = _profileCapabilities.MaxPrimitiveCount;
        if (primitiveCount > maxPrimitiveCount)
        {
            _profileCapabilities.ThrowNotSupportedException(FrameworkResources.ProfileMaxPrimitiveCount, maxPrimitiveCount);
        }
        VerifyCanDraw(bUserPrimitives: false, bIndexedPrimitives: false);
        if (instanceStreamMask != 0)
        {
            throw new InvalidOperationException(FrameworkResources.NonZeroInstanceFrequency);
        }
        if (!_insideScene)
        {
            IDirect3DDevice9* intPtr2 = pComPtr;
            ((delegate* unmanaged[Stdcall, Stdcall]<IntPtr, int>)(int)(*(uint*)(*(int*)intPtr2 + 164)))((nint)intPtr2);
            _insideScene = true;
        }
        int num = *(int*)pComPtr + 324;
        int num2 = ((delegate* unmanaged[Stdcall, Stdcall]<IntPtr, _D3DPRIMITIVETYPE, uint, uint, int>)(int)(*(uint*)num))((nint)pComPtr, _003CModule_003E.ConvertXnaPrimitiveTypeToDx(primitiveType), (uint)startVertex, (uint)primitiveCount);
        if (num2 < 0)
        {
            throw GraphicsHelpers.GetExceptionFromResult((uint)num2);
        }
    }
References Microsoft.Xna.Framework.Graphics.GraphicsDevice._insideScene, Microsoft.Xna.Framework.Graphics.GraphicsDevice._profileCapabilities, Microsoft.Xna.Framework.Helpers.CheckDisposed(), Microsoft.Xna.Framework.Graphics.GraphicsHelpers.GetExceptionFromResult(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.instanceStreamMask, Microsoft.Xna.Framework.Graphics.ProfileCapabilities.MaxPrimitiveCount, Microsoft.Xna.Framework.FrameworkResources.MustDrawSomething, Microsoft.Xna.Framework.FrameworkResources.NonZeroInstanceFrequency, Microsoft.Xna.Framework.Graphics.GraphicsDevice.pComPtr, Microsoft.Xna.Framework.FrameworkResources.ProfileMaxPrimitiveCount, Microsoft.Xna.Framework.Graphics.ProfileCapabilities.ThrowNotSupportedException(), and Microsoft.Xna.Framework.Graphics.GraphicsDevice.VerifyCanDraw().