Terraria: Microsoft.Xna.Framework.Graphics.GraphicsDevice.DrawIndexedPrimitives
DrawIndexedPrimitives()
unsafe void Microsoft.Xna.Framework.Graphics.GraphicsDevice.DrawIndexedPrimitives (PrimitiveType primitiveType, int baseVertex, int minVertexIndex, int numVertices, int startIndex, int primitiveCount) inline
Definition at line 1312 of file GraphicsDevice.cs.
    {
        IntPtr intPtr = (IntPtr)pComPtr;
        Helpers.CheckDisposed(this, intPtr);
        if (numVertices <= 0)
        {
            throw new ArgumentOutOfRangeException("numVertices", FrameworkResources.NumberVerticesMustBeGreaterZero);
        }
        if (primitiveCount <= 0)
        {
            throw new ArgumentOutOfRangeException("primitiveCount", FrameworkResources.MustDrawSomething);
        }
        int maxPrimitiveCount = _profileCapabilities.MaxPrimitiveCount;
        if (primitiveCount > maxPrimitiveCount)
        {
            _profileCapabilities.ThrowNotSupportedException(FrameworkResources.ProfileMaxPrimitiveCount, maxPrimitiveCount);
        }
        VerifyCanDraw(bUserPrimitives: false, bIndexedPrimitives: true);
        if (instanceStreamMask != 0)
        {
            throw new InvalidOperationException(FrameworkResources.NonZeroInstanceFrequency);
        }
        if (!_insideScene)
        {
            IDirect3DDevice9* intPtr2 = pComPtr;
            ((delegate* unmanaged[Stdcall, Stdcall]<IntPtr, int>)(int)(*(uint*)(*(int*)intPtr2 + 164)))((nint)intPtr2);
            _insideScene = true;
        }
        int num = *(int*)pComPtr + 328;
        int num2 = ((delegate* unmanaged[Stdcall, Stdcall]<IntPtr, _D3DPRIMITIVETYPE, int, uint, uint, uint, uint, int>)(int)(*(uint*)num))((nint)pComPtr, _003CModule_003E.ConvertXnaPrimitiveTypeToDx(primitiveType), baseVertex, (uint)minVertexIndex, (uint)numVertices, (uint)startIndex, (uint)primitiveCount);
        if (num2 < 0)
        {
            throw GraphicsHelpers.GetExceptionFromResult((uint)num2);
        }
    }
References Microsoft.Xna.Framework.Graphics.GraphicsDevice._insideScene, Microsoft.Xna.Framework.Graphics.GraphicsDevice._profileCapabilities, Microsoft.Xna.Framework.Helpers.CheckDisposed(), Microsoft.Xna.Framework.Graphics.GraphicsHelpers.GetExceptionFromResult(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.instanceStreamMask, Microsoft.Xna.Framework.Graphics.ProfileCapabilities.MaxPrimitiveCount, Microsoft.Xna.Framework.FrameworkResources.MustDrawSomething, Microsoft.Xna.Framework.FrameworkResources.NonZeroInstanceFrequency, Microsoft.Xna.Framework.FrameworkResources.NumberVerticesMustBeGreaterZero, Microsoft.Xna.Framework.Graphics.GraphicsDevice.pComPtr, Microsoft.Xna.Framework.FrameworkResources.ProfileMaxPrimitiveCount, System.startIndex, Microsoft.Xna.Framework.Graphics.ProfileCapabilities.ThrowNotSupportedException(), and Microsoft.Xna.Framework.Graphics.GraphicsDevice.VerifyCanDraw().
Referenced by Microsoft.Xna.Framework.Graphics.ModelMeshPart.Draw(), Terraria.DataStructures.SpriteDrawBuffer.DrawRange(), Microsoft.Xna.Framework.Graphics.SpriteBatch.PlatformRenderBatch(), and Terraria.Graphics.TileBatch.RenderBatch().