Terraria: Microsoft.Xna.Framework.Graphics.GraphicsDevice.ClearDirtyBuffers
ClearDirtyBuffers()
unsafe void Microsoft.Xna.Framework.Graphics.GraphicsDevice.ClearDirtyBuffers () inline private
Definition at line 2138 of file GraphicsDevice.cs.
    {
        Color color = new Color(68, 34, 136, 255);
        int num = currentRenderTargetCount;
        if (num <= 0)
        {
            Clear((ClearOptions)lazyClearFlags, color, 1f, 0);
        }
        else
        {
            if (((uint)lazyClearFlags & (true ? 1u : 0u)) != 0)
            {
                int num2 = 0;
                if (0 < num)
                {
                    do
                    {
                        RenderTargetHelper renderTargetHelper = currentRenderTargets[num2];
                        if (renderTargetHelper.usage == RenderTargetUsage.DiscardContents)
{
                            IDirect3DSurface9* renderTargetSurface = renderTargetHelper.GetRenderTargetSurface(currentRenderTargetBindings[num2]._cubeMapFace);
                            uint num3 = (uint)(color.A << 8);
                            uint num4 = (color.R | num3) << 8;
                            uint num5 = (color.G | num4) << 8;
                            uint num6 = color.B | num5;
                            IDirect3DDevice9* ptr = pComPtr;
                            int num7 = ((delegate* unmanaged[Stdcall, Stdcall]<IntPtr, IDirect3DSurface9*, tagRECT*, uint, int>)(int)(*(uint*)(*(int*)ptr + 140)))((nint)ptr, renderTargetSurface, null, num6);
                            if (renderTargetSurface != null)
{
                                ((delegate* unmanaged[Stdcall, Stdcall]<IntPtr, uint>)(int)(*(uint*)(*(int*)renderTargetSurface + 8)))((nint)renderTargetSurface);
                            }
                            if (num7 < 0)
{
                                throw GraphicsHelpers.GetExceptionFromResult((uint)num7);
                            }
                        }
                        num2++;
                    }
                    while (num2 < currentRenderTargetCount);
                }
            }
            int num8 = lazyClearFlags & 6;
            if (num8 != 0)
            {
                Clear((ClearOptions)num8, color, 1f, 0);
            }
        }
        lazyClearFlags = 0;
    }
References Microsoft.Xna.Framework.Color.A, System.Clear, Microsoft.Xna.Framework.Graphics.Color, Microsoft.Xna.Framework.Graphics.GraphicsDevice.currentRenderTargetBindings, Microsoft.Xna.Framework.Graphics.GraphicsDevice.currentRenderTargetCount, Microsoft.Xna.Framework.Graphics.GraphicsDevice.currentRenderTargets, Microsoft.Xna.Framework.Graphics.GraphicsHelpers.GetExceptionFromResult(), Microsoft.Xna.Framework.Graphics.RenderTargetHelper.GetRenderTargetSurface(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.lazyClearFlags, Microsoft.Xna.Framework.Graphics.GraphicsDevice.pComPtr, and Microsoft.Xna.Framework.Graphics.RenderTargetHelper.usage.
Referenced by Microsoft.Xna.Framework.Graphics.GraphicsDevice.GetBackBufferData< T >(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.Present(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.SetRenderTargets(), and Microsoft.Xna.Framework.Graphics.GraphicsDevice.VerifyCanDraw().