Terraria: Microsoft.Xna.Framework.Graphics.GraphicsDevice.Present
Present() [3/3]
unsafe void Microsoft.Xna.Framework.Graphics.GraphicsDevice.Present (tagRECT * pSource, tagRECT * pDest, HWND__ * hOverride) inline private
Definition at line 796 of file GraphicsDevice.cs.
    {
        IntPtr intPtr = (IntPtr)pComPtr;
        Helpers.CheckDisposed(this, intPtr);
        if (currentRenderTargetCount > 0)
        {
            throw new InvalidOperationException(FrameworkResources.CannotPresentActiveRenderTargets);
        }
        EffectPass effectPass = activePass;
        if (effectPass != null)
        {
            effectPass.EndPass();
            activePass = null;
        }
        if (lazyClearFlags != 0)
        {
            ClearDirtyBuffers();
        }
        if (pSource == null && pDest == null && hOverride == null)
        {
            raise_DrawGuide(this, EventArgs.Empty);
        }
        if (_insideScene)
        {
            IDirect3DDevice9* intPtr2 = pComPtr;
            ((delegate* unmanaged[Stdcall, Stdcall]<IntPtr, int>)(int)(*(uint*)(*(int*)intPtr2 + 168)))((nint)intPtr2);
            _insideScene = false;
        }
        try
        {
            IDirect3DDevice9* ptr = pComPtr;
            int num = ((delegate* unmanaged[Stdcall, Stdcall]<IntPtr, tagRECT*, tagRECT*, HWND__*, _RGNDATA*, int>)(int)(*(uint*)(*(int*)ptr + 68)))((nint)ptr, pSource, pDest, hOverride, null);
            lazyClearFlags = (int)DefaultClearOptions;
            if (num < 0)
            {
                if (num == -2005530520)
                {
                    raise_DeviceLost(this, EventArgs.Empty);
                }
                throw GraphicsHelpers.GetExceptionFromResult((uint)num);
            }
        }
        catch (InvalidOperationException)
        {
        }
    }
References Microsoft.Xna.Framework.Graphics.GraphicsDevice._insideScene, Microsoft.Xna.Framework.Graphics.GraphicsDevice.activePass, Microsoft.Xna.Framework.FrameworkResources.CannotPresentActiveRenderTargets, Microsoft.Xna.Framework.Helpers.CheckDisposed(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.ClearDirtyBuffers(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.currentRenderTargetCount, Microsoft.Xna.Framework.Graphics.GraphicsDevice.DefaultClearOptions, System.EventArgs.Empty, Microsoft.Xna.Framework.Graphics.EffectPass.EndPass(), Microsoft.Xna.Framework.Graphics.GraphicsHelpers.GetExceptionFromResult(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.lazyClearFlags, Microsoft.Xna.Framework.Graphics.GraphicsDevice.pComPtr, Microsoft.Xna.Framework.Graphics.GraphicsDevice.raise_DeviceLost(), and Microsoft.Xna.Framework.Graphics.GraphicsDevice.raise_DrawGuide().