Terraria: Microsoft.Xna.Framework.Graphics.GraphicsDevice.DrawUserPrimitives< T >
DrawUserPrimitives< T >() [2/2]
unsafe void Microsoft.Xna.Framework.Graphics.GraphicsDevice.DrawUserPrimitives< T > (PrimitiveType primitiveType, T[] vertexData, int vertexOffset, int primitiveCount, VertexDeclaration vertexDeclaration) inline
Type Constraints
T : struct
Definition at line 1664 of file GraphicsDevice.cs.
                                                                                                                                                                             : struct
    {
        IntPtr intPtr = (IntPtr)pComPtr;
        Helpers.CheckDisposed(this, intPtr);
        if (vertexData == null)
        {
            throw new ArgumentNullException("vertexData", FrameworkResources.NullNotAllowed);
        }
        if (vertexDeclaration == null)
        {
            throw new ArgumentNullException("vertexDeclaration", FrameworkResources.NullNotAllowed);
        }
        if (primitiveCount <= 0)
        {
            throw new ArgumentOutOfRangeException("primitiveCount", FrameworkResources.MustDrawSomething);
        }
        int maxPrimitiveCount = _profileCapabilities.MaxPrimitiveCount;
        if (primitiveCount > maxPrimitiveCount)
        {
            _profileCapabilities.ThrowNotSupportedException(FrameworkResources.ProfileMaxPrimitiveCount, maxPrimitiveCount);
        }
        if (vertexOffset >= 0)
        {
            int num = vertexData.Length;
            if (vertexOffset < num)
            {
                if ((uint)((int)GetElementCountFromPrimitiveType(primitiveType, primitiveCount) + vertexOffset) > (uint)num)
                {
                    throw new ArgumentOutOfRangeException("primitiveCount", FrameworkResources.MustBeValidIndex);
                }
                BeginUserPrimitives(vertexDeclaration);
                VerifyCanDraw(bUserPrimitives: true, bIndexedPrimitives: false);
                fixed (T* ptr = &vertexData[vertexOffset])
                {
                    int num2 = *(int*)pComPtr + 332;
                    int num3 = ((delegate* unmanaged[Stdcall, Stdcall]<IntPtr, _D3DPRIMITIVETYPE, uint, void*, uint, int>)(int)(*(uint*)num2))((nint)pComPtr, _003CModule_003E.ConvertXnaPrimitiveTypeToDx(primitiveType), (uint)primitiveCount, ptr, (uint)System.Runtime.CompilerServices.Unsafe.SizeOf<T>());
                    if (num3 < 0)
                    {
                        throw GraphicsHelpers.GetExceptionFromResult((uint)num3);
                    }
                    return;
                }
            }
        }
        throw new ArgumentOutOfRangeException("vertexOffset", FrameworkResources.OffsetNotValid);
    }
References Microsoft.Xna.Framework.Graphics.GraphicsDevice._profileCapabilities, Microsoft.Xna.Framework.Graphics.GraphicsDevice.BeginUserPrimitives(), Microsoft.Xna.Framework.Helpers.CheckDisposed(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.GetElementCountFromPrimitiveType(), Microsoft.Xna.Framework.Graphics.GraphicsHelpers.GetExceptionFromResult(), Microsoft.Xna.Framework.Graphics.ProfileCapabilities.MaxPrimitiveCount, Microsoft.Xna.Framework.FrameworkResources.MustBeValidIndex, Microsoft.Xna.Framework.FrameworkResources.MustDrawSomething, Microsoft.Xna.Framework.FrameworkResources.NullNotAllowed, Microsoft.Xna.Framework.FrameworkResources.OffsetNotValid, Microsoft.Xna.Framework.Graphics.GraphicsDevice.pComPtr, Microsoft.Xna.Framework.FrameworkResources.ProfileMaxPrimitiveCount, Microsoft.Xna.Framework.Graphics.ProfileCapabilities.ThrowNotSupportedException(), and Microsoft.Xna.Framework.Graphics.GraphicsDevice.VerifyCanDraw().