Terraria: Microsoft.Xna.Framework.Graphics.GraphicsDevice.InitializeDeviceState
InitializeDeviceState()
void Microsoft.Xna.Framework.Graphics.GraphicsDevice.InitializeDeviceState () inline private
Definition at line 2527 of file GraphicsDevice.cs.
    {
        cachedBlendState = null;
        cachedDepthStencilState = null;
        cachedRasterizerState = null;
        BlendState = BlendState.Opaque;
        DepthStencilState = DepthStencilState.Default;
        RasterizerState = RasterizerState.CullCounterClockwise;
        pSamplerState.InitializeDeviceState();
        pVertexSamplerState.InitializeDeviceState();
        currentViewport = default(Viewport);
        currentViewport.Width = pInternalCachedParams.BackBufferWidth;
        currentViewport.Height = pInternalCachedParams.BackBufferHeight;
        currentViewport.MaxDepth = 1f;
        lazyClearFlags = (int)DefaultClearOptions;
    }
References Microsoft.Xna.Framework.Graphics.PresentationParameters.BackBufferHeight, Microsoft.Xna.Framework.Graphics.PresentationParameters.BackBufferWidth, Microsoft.Xna.Framework.Graphics.GraphicsDevice.cachedBlendState, Microsoft.Xna.Framework.Graphics.GraphicsDevice.cachedDepthStencilState, Microsoft.Xna.Framework.Graphics.GraphicsDevice.cachedRasterizerState, Microsoft.Xna.Framework.Graphics.RasterizerState.CullCounterClockwise, Microsoft.Xna.Framework.Graphics.GraphicsDevice.currentViewport, Microsoft.Xna.Framework.Graphics.DepthStencilState.Default, Microsoft.Xna.Framework.Graphics.GraphicsDevice.DefaultClearOptions, Microsoft.Xna.Framework.Graphics.SamplerStateCollection.InitializeDeviceState(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.lazyClearFlags, Microsoft.Xna.Framework.Graphics.BlendState.Opaque, Microsoft.Xna.Framework.Graphics.GraphicsDevice.pInternalCachedParams, Microsoft.Xna.Framework.Graphics.GraphicsDevice.pSamplerState, and Microsoft.Xna.Framework.Graphics.GraphicsDevice.pVertexSamplerState.
Referenced by Microsoft.Xna.Framework.Graphics.GraphicsDevice.GraphicsDevice(), and Microsoft.Xna.Framework.Graphics.GraphicsDevice.Reset().