Terraria: Microsoft.Xna.Framework.Graphics.GraphicsDevice.GetBackBufferData< T >
GetBackBufferData< T >() [1/3]
unsafe void Microsoft.Xna.Framework.Graphics.GraphicsDevice.GetBackBufferData< T > (Rectangle? rect, T[] data, int startIndex, int elementCount) inline
Type Constraints
T : struct
Definition at line 2222 of file GraphicsDevice.cs.
                                                                                                                 : struct
    {
        IntPtr intPtr = (IntPtr)pComPtr;
        Helpers.CheckDisposed(this, intPtr);
        if (!_profileCapabilities.GetBackBufferData)
        {
            _profileCapabilities.ThrowNotSupportedException(FrameworkResources.ProfileFeatureNotSupported, "GetBackBufferData");
        }
        if (data != null)
        {
            int num = data.Length;
            if (num != 0)
            {
                Helpers.ValidateCopyParameters(num, startIndex, elementCount);
                if (currentRenderTargetCount > 0)
                {
                    throw new InvalidOperationException(FrameworkResources.CannotGetBackBufferActiveRenderTargets);
                }
                if (lazyClearFlags != 0)
                {
                    ClearDirtyBuffers();
                }
                IDirect3DSurface9* ptr = null;
                IDirect3DTexture9* ptr2 = null;
                IDirect3DSurface9* ptr3 = null;
                bool flag = false;
                try
                {
                    IDirect3DDevice9* ptr4 = pComPtr;
                    int num2 = ((delegate* unmanaged[Stdcall, Stdcall]<IntPtr, uint, uint, _D3DBACKBUFFER_TYPE, IDirect3DSurface9**, int>)(int)(*(uint*)(*(int*)ptr4 + 72)))((nint)ptr4, 0u, 0u, (_D3DBACKBUFFER_TYPE)0, &ptr);
                    if (num2 >= 0)
                    {
                        System.Runtime.CompilerServices.Unsafe.SkipInit(out _D3DSURFACE_DESC d3DSURFACE_DESC);
                        num2 = ((delegate* unmanaged[Stdcall, Stdcall]<IntPtr, _D3DSURFACE_DESC*, int>)(int)(*(uint*)(*(int*)ptr + 48)))((nint)ptr, &d3DSURFACE_DESC);
                        if (num2 >= 0)
{
                            System.Runtime.CompilerServices.Unsafe.SkipInit(out uint dwFormatSize);
                            System.Runtime.CompilerServices.Unsafe.SkipInit(out uint dwElementSize);
                            Texture.GetAndValidateSizes<T>(&d3DSURFACE_DESC, &dwFormatSize, &dwElementSize);
                            System.Runtime.CompilerServices.Unsafe.SkipInit(out uint dwLockWidth);
                            System.Runtime.CompilerServices.Unsafe.SkipInit(out uint dwLockHeight);
                            Texture.GetAndValidateRect(&d3DSURFACE_DESC, &dwLockWidth, &dwLockHeight, rect);
                            Texture.ValidateTotalSize(&d3DSURFACE_DESC, dwLockWidth, dwLockHeight, dwFormatSize, dwElementSize, (uint)elementCount);
                            if (_insideScene)
{
                                ptr4 = pComPtr;
                                IDirect3DDevice9* intPtr2 = ptr4;
                                ((delegate* unmanaged[Stdcall, Stdcall]<IntPtr, int>)(int)(*(uint*)(*(int*)intPtr2 + 168)))((nint)intPtr2);
                                flag = true;
                            }
                            ptr4 = pComPtr;
                            num2 = ((delegate* unmanaged[Stdcall, Stdcall]<IntPtr, uint, uint, uint, uint, _D3DFORMAT, _D3DPOOL, IDirect3DTexture9**, void**, int>)(int)(*(uint*)(*(int*)ptr4 + 92)))((nint)ptr4, System.Runtime.CompilerServices.Unsafe.As<_D3DSURFACE_DESC, uint>(ref System.Runtime.CompilerServices.Unsafe.AddByteOffset(ref d3DSURFACE_DESC, 24)), System.Runtime.CompilerServices.Unsafe.As<_D3DSURFACE_DESC, uint>(ref System.Runtime.CompilerServices.Unsafe.AddByteOffset(ref d3DSURFACE_DESC, 28)), 1u, 0u, *(_D3DFORMAT*)(&d3DSURFACE_DESC), (_D3DPOOL)2, &ptr2, null);
                            if (num2 >= 0)
{
                                num2 = ((delegate* unmanaged[Stdcall, Stdcall]<IntPtr, uint, IDirect3DSurface9**, int>)(int)(*(uint*)(*(int*)ptr2 + 72)))((nint)ptr2, 0u, &ptr3);
                                if (num2 >= 0)
{
                                    num2 = _003CModule_003E.D3DXLoadSurfaceFromSurface(ptr3, null, null, ptr, null, null, uint.MaxValue, 0u);
                                    if (num2 >= 0)
{
                                        tagRECT* ptr5 = null;
                                        Rectangle rectangle = default(Rectangle);
                                        if (rect.HasValue)
{
                                            rectangle = rect.Value;
                                            ptr5 = (tagRECT*)(int)(ref rectangle);
                                            if (ptr5 != null)
{
                                                *(int*)((byte*)ptr5 + 8) += *(int*)ptr5;
                                                *(int*)((byte*)ptr5 + 12) += *(int*)((byte*)ptr5 + 4);
                                            }
                                        }
                                        System.Runtime.CompilerServices.Unsafe.SkipInit(out _D3DLOCKED_RECT d3DLOCKED_RECT);
                                        num2 = ((delegate* unmanaged[Stdcall, Stdcall]<IntPtr, _D3DLOCKED_RECT*, tagRECT*, uint, int>)(int)(*(uint*)(*(int*)ptr3 + 52)))((nint)ptr3, &d3DLOCKED_RECT, ptr5, 0u);
                                        if (num2 >= 0)
{
                                            try
{
                                                Texture.CopyData((void*)(int)System.Runtime.CompilerServices.Unsafe.As<_D3DLOCKED_RECT, uint>(ref System.Runtime.CompilerServices.Unsafe.AddByteOffset(ref d3DLOCKED_RECT, 4)), *(int*)(&d3DLOCKED_RECT), data, startIndex, elementCount, &d3DSURFACE_DESC, dwLockWidth, dwLockHeight, isSetting: false);
                                            }
                                            finally
{
                                                IDirect3DSurface9* intPtr3 = ptr3;
                                                ((delegate* unmanaged[Stdcall, Stdcall]<IntPtr, int>)(int)(*(uint*)(*(int*)intPtr3 + 56)))((nint)intPtr3);
                                            }
                                            if (pInternalCachedParams.RenderTargetUsage == RenderTargetUsage.DiscardContents)
{
                                                lazyClearFlags = (int)DefaultClearOptions;
                                            }
                                            if (num2 >= 0)
{
                                                return;
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                    throw GraphicsHelpers.GetExceptionFromResult((uint)num2);
                }
                finally
                {
                    if (ptr3 != null)
                    {
                        IDirect3DSurface9* intPtr4 = ptr3;
                        ((delegate* unmanaged[Stdcall, Stdcall]<IntPtr, uint>)(int)(*(uint*)(*(int*)intPtr4 + 8)))((nint)intPtr4);
                        ptr3 = null;
                    }
                    if (ptr2 != null)
                    {
                        IDirect3DTexture9* intPtr5 = ptr2;
                        ((delegate* unmanaged[Stdcall, Stdcall]<IntPtr, uint>)(int)(*(uint*)(*(int*)intPtr5 + 8)))((nint)intPtr5);
                        ptr2 = null;
                    }
                    if (ptr != null)
                    {
                        IDirect3DSurface9* intPtr6 = ptr;
                        ((delegate* unmanaged[Stdcall, Stdcall]<IntPtr, uint>)(int)(*(uint*)(*(int*)intPtr6 + 8)))((nint)intPtr6);
                        ptr = null;
                    }
                    if (flag)
                    {
                        IDirect3DDevice9* intPtr7 = pComPtr;
                        ((delegate* unmanaged[Stdcall, Stdcall]<IntPtr, int>)(int)(*(uint*)(*(int*)intPtr7 + 164)))((nint)intPtr7);
                    }
                }
            }
        }
        throw new ArgumentNullException("data", FrameworkResources.NullNotAllowed);
    }
References Microsoft.Xna.Framework.Graphics.GraphicsDevice._insideScene, Microsoft.Xna.Framework.Graphics.GraphicsDevice._profileCapabilities, Microsoft.Xna.Framework.FrameworkResources.CannotGetBackBufferActiveRenderTargets, Microsoft.Xna.Framework.Helpers.CheckDisposed(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.ClearDirtyBuffers(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.currentRenderTargetCount, Microsoft.Xna.Framework.Graphics.GraphicsDevice.DefaultClearOptions, Microsoft.Xna.Framework.Graphics.Texture.GetAndValidateRect(), Microsoft.Xna.Framework.Graphics.ProfileCapabilities.GetBackBufferData, Microsoft.Xna.Framework.Graphics.GraphicsHelpers.GetExceptionFromResult(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.lazyClearFlags, Microsoft.Xna.Framework.FrameworkResources.NullNotAllowed, Microsoft.Xna.Framework.Graphics.GraphicsDevice.pComPtr, Microsoft.Xna.Framework.Graphics.GraphicsDevice.pInternalCachedParams, Microsoft.Xna.Framework.FrameworkResources.ProfileFeatureNotSupported, Microsoft.Xna.Framework.Graphics.PresentationParameters.RenderTargetUsage, System.startIndex, Microsoft.Xna.Framework.Graphics.ProfileCapabilities.ThrowNotSupportedException(), Microsoft.Xna.Framework.Helpers.ValidateCopyParameters(), and Microsoft.Xna.Framework.Graphics.Texture.ValidateTotalSize().