Terraria: Microsoft.Xna.Framework.Graphics.GraphicsDevice.DrawInstancedPrimitives
DrawInstancedPrimitives()
unsafe void Microsoft.Xna.Framework.Graphics.GraphicsDevice.DrawInstancedPrimitives (PrimitiveType primitiveType, int baseVertex, int minVertexIndex, int numVertices, int startIndex, int primitiveCount, int instanceCount) inline
Definition at line 1348 of file GraphicsDevice.cs.
    {
        IntPtr intPtr = (IntPtr)pComPtr;
        Helpers.CheckDisposed(this, intPtr);
        if (numVertices <= 0)
        {
            throw new ArgumentOutOfRangeException("numVertices", FrameworkResources.NumberVerticesMustBeGreaterZero);
        }
        if (primitiveCount <= 0)
        {
            throw new ArgumentOutOfRangeException("primitiveCount", FrameworkResources.MustDrawSomething);
        }
        int maxPrimitiveCount = _profileCapabilities.MaxPrimitiveCount;
        if (primitiveCount > maxPrimitiveCount)
        {
            _profileCapabilities.ThrowNotSupportedException(FrameworkResources.ProfileMaxPrimitiveCount, maxPrimitiveCount);
        }
        if (instanceCount <= 0)
        {
            throw new ArgumentOutOfRangeException("instanceCount", FrameworkResources.MustDrawSomething);
        }
        maxPrimitiveCount = _profileCapabilities.MaxPrimitiveCount;
        if (instanceCount > maxPrimitiveCount)
        {
            _profileCapabilities.ThrowNotSupportedException(FrameworkResources.ProfileMaxPrimitiveCount, maxPrimitiveCount);
        }
        VerifyCanDraw(bUserPrimitives: false, bIndexedPrimitives: true);
        int num = instanceStreamMask;
        bool flag = num == 0;
        bool flag2 = num == (1 << currentVertexBufferCount) - 1;
        if (!flag && !flag2)
        {
            _D3DPRIMITIVETYPE d3DPRIMITIVETYPE = _003CModule_003E.ConvertXnaPrimitiveTypeToDx(primitiveType);
            if (!_insideScene)
            {
                IDirect3DDevice9* intPtr2 = pComPtr;
                ((delegate* unmanaged[Stdcall, Stdcall]<IntPtr, int>)(int)(*(uint*)(*(int*)intPtr2 + 164)))((nint)intPtr2);
                _insideScene = true;
            }
            if ((uint)(*(int*)((byte*)pStateTracker + 20)) >= 768u)
            {
                try
                {
                    for (int i = 0; i < currentVertexBufferCount; i++)
                    {
                        uint num2 = 1073741823u;
                        uint instanceFrequency = (uint)currentVertexBuffers[i]._instanceFrequency;
                        uint num3 = ((instanceFrequency == 0) ? ((uint)instanceCount | 0x40000000u) : (((instanceFrequency >= 1073741823) ? 1073741823u : instanceFrequency) | 0x80000000u));
                        IDirect3DDevice9* ptr = pComPtr;
                        int num4 = ((delegate* unmanaged[Stdcall, Stdcall]<IntPtr, uint, uint, int>)(int)(*(uint*)(*(int*)ptr + 408)))((nint)ptr, (uint)i, num3);
                        if (num4 < 0)
{
                            throw GraphicsHelpers.GetExceptionFromResult((uint)num4);
                        }
                    }
                    IDirect3DDevice9* ptr2 = pComPtr;
                    int num5 = ((delegate* unmanaged[Stdcall, Stdcall]<IntPtr, _D3DPRIMITIVETYPE, int, uint, uint, uint, uint, int>)(int)(*(uint*)(*(int*)ptr2 + 328)))((nint)ptr2, d3DPRIMITIVETYPE, baseVertex, (uint)minVertexIndex, (uint)numVertices, (uint)startIndex, (uint)primitiveCount);
                    if (num5 < 0)
                    {
                        throw GraphicsHelpers.GetExceptionFromResult((uint)num5);
                    }
                    return;
                }
                finally
                {
                    int num6 = 0;
                    if (0 < currentVertexBufferCount)
                    {
                        do
{
                            IDirect3DDevice9* ptr3 = pComPtr;
                            ((delegate* unmanaged[Stdcall, Stdcall]<IntPtr, uint, uint, int>)(int)(*(uint*)(*(int*)ptr3 + 408)))((nint)ptr3, (uint)num6, 1u);
                            num6++;
                        }
                        while (num6 < currentVertexBufferCount);
                    }
                }
            }
            int num7 = 0;
            int num8 = 0;
            System.Runtime.CompilerServices.Unsafe.SkipInit(out _0024ArrayType_0024_0024_0024BY0BA_0040H _0024ArrayType_0024_0024_0024BY0BA_0040H);
            System.Runtime.CompilerServices.Unsafe.SkipInit(out _0024ArrayType_0024_0024_0024BY0BA_0040I _0024ArrayType_0024_0024_0024BY0BA_0040I);
            System.Runtime.CompilerServices.Unsafe.SkipInit(out _0024ArrayType_0024_0024_0024BY0BA_0040I _0024ArrayType_0024_0024_0024BY0BA_0040I2);
            System.Runtime.CompilerServices.Unsafe.SkipInit(out _0024ArrayType_0024_0024_0024BY0BA_0040I _0024ArrayType_0024_0024_0024BY0BA_0040I3);
            System.Runtime.CompilerServices.Unsafe.SkipInit(out _0024ArrayType_0024_0024_0024BY0BA_0040PAUIDirect3DVertexBuffer9_0040_0040 _0024ArrayType_0024_0024_0024BY0BA_0040PAUIDirect3DVertexBuffer9_0040_0040);
            if (0 < currentVertexBufferCount)
            {
                do
                {
                    if (num8 < 16)
                    {
                        if ((instanceStreamMask & (1 << num8)) != 0)
{
                            *(int*)((ref *(_003F*)(num7 * 4)) + (ref *(_003F*)(&_0024ArrayType_0024_0024_0024BY0BA_0040H))) = num8;
                            VertexBufferBinding[] array = currentVertexBuffers;
                            *(int*)((ref *(_003F*)(num7 * 4)) + (ref *(_003F*)(&_0024ArrayType_0024_0024_0024BY0BA_0040I))) = array[num8]._vertexOffset;
                            *(int*)((ref *(_003F*)(num7 * 4)) + (ref *(_003F*)(&_0024ArrayType_0024_0024_0024BY0BA_0040I2))) = array[num8]._instanceFrequency;
                            VertexBuffer vertexBuffer = array[num8]._vertexBuffer;
                            *(int*)((ref *(_003F*)(num7 * 4)) + (ref *(_003F*)(&_0024ArrayType_0024_0024_0024BY0BA_0040I3))) = vertexBuffer._vertexDeclaration._vertexStride;
                            *(int*)((ref *(_003F*)(num7 * 4)) + (ref *(_003F*)(&_0024ArrayType_0024_0024_0024BY0BA_0040PAUIDirect3DVertexBuffer9_0040_0040))) = (int)vertexBuffer.pComPtr;
                            num7++;
                        }
                        num8++;
                        continue;
                    }
                    throw new InvalidOperationException();
                }
                while (num8 < currentVertexBufferCount);
            }
            int num9 = 0;
            if (0 >= instanceCount)
            {
                return;
            }
            int num13;
            while (true)
            {
                int num10 = 0;
                if (0 < num7)
                {
                    do
                    {
                        uint num11 = (uint)(((int)((uint)num9 / (uint)(*(int*)((ref *(_003F*)(num10 * 4)) + (ref *(_003F*)(&_0024ArrayType_0024_0024_0024BY0BA_0040I2))))) + *(int*)((ref *(_003F*)(num10 * 4)) + (ref *(_003F*)(&_0024ArrayType_0024_0024_0024BY0BA_0040I)))) * *(int*)((ref *(_003F*)(num10 * 4)) + (ref *(_003F*)(&_0024ArrayType_0024_0024_0024BY0BA_0040I3))));
                        IDirect3DDevice9* ptr4 = pComPtr;
                        int num12 = ((delegate* unmanaged[Stdcall, Stdcall]<IntPtr, uint, IDirect3DVertexBuffer9*, uint, uint, int>)(int)(*(uint*)(*(int*)ptr4 + 400)))((nint)ptr4, *(uint*)((ref *(_003F*)(num10 * 4)) + (ref *(_003F*)(&_0024ArrayType_0024_0024_0024BY0BA_0040H))), (IDirect3DVertexBuffer9*)(int)(*(uint*)((ref *(_003F*)(num10 * 4)) + (ref *(_003F*)(&_0024ArrayType_0024_0024_0024BY0BA_0040PAUIDirect3DVertexBuffer9_0040_0040)))), num11, 0u);
                        if (num12 >= 0)
{
                            num10++;
                            continue;
                        }
                        throw GraphicsHelpers.GetExceptionFromResult((uint)num12);
                    }
                    while (num10 < num7);
                }
                IDirect3DDevice9* ptr5 = pComPtr;
                num13 = ((delegate* unmanaged[Stdcall, Stdcall]<IntPtr, _D3DPRIMITIVETYPE, int, uint, uint, uint, uint, int>)(int)(*(uint*)(*(int*)ptr5 + 328)))((nint)ptr5, d3DPRIMITIVETYPE, baseVertex, (uint)minVertexIndex, (uint)numVertices, (uint)startIndex, (uint)primitiveCount);
                if (num13 < 0)
                {
                    break;
                }
                num9++;
                if (num9 >= instanceCount)
                {
                    return;
                }
            }
            throw GraphicsHelpers.GetExceptionFromResult((uint)num13);
        }
        throw new InvalidOperationException(FrameworkResources.InvalidInstanceStreams);
    }
References Microsoft.Xna.Framework.Graphics.GraphicsDevice._insideScene, Microsoft.Xna.Framework.Graphics.GraphicsDevice._profileCapabilities, Microsoft.Xna.Framework.Graphics.VertexBuffer._vertexDeclaration, Microsoft.Xna.Framework.Graphics.VertexBufferBinding._vertexOffset, Microsoft.Xna.Framework.Graphics.VertexDeclaration._vertexStride, System.array, Microsoft.Xna.Framework.Helpers.CheckDisposed(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.currentVertexBufferCount, Microsoft.Xna.Framework.Graphics.GraphicsDevice.currentVertexBuffers, Microsoft.Xna.Framework.Graphics.GraphicsHelpers.GetExceptionFromResult(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.instanceStreamMask, Microsoft.Xna.Framework.FrameworkResources.InvalidInstanceStreams, Microsoft.Xna.Framework.Graphics.ProfileCapabilities.MaxPrimitiveCount, Microsoft.Xna.Framework.FrameworkResources.MustDrawSomething, Microsoft.Xna.Framework.FrameworkResources.NumberVerticesMustBeGreaterZero, Microsoft.Xna.Framework.Graphics.GraphicsDevice.pComPtr, Microsoft.Xna.Framework.Graphics.VertexBuffer.pComPtr, Microsoft.Xna.Framework.FrameworkResources.ProfileMaxPrimitiveCount, Microsoft.Xna.Framework.Graphics.GraphicsDevice.pStateTracker, System.startIndex, Microsoft.Xna.Framework.Graphics.ProfileCapabilities.ThrowNotSupportedException(), and Microsoft.Xna.Framework.Graphics.GraphicsDevice.VerifyCanDraw().