Terraria: Microsoft.Xna.Framework.Graphics.GraphicsDevice.Dispose
Dispose() [2/2]
virtual void Microsoft.Xna.Framework.Graphics.GraphicsDevice.Dispose ([MarshalAs(UnmanagedType.U1)] bool P_0) inline protected virtual
Definition at line 2617 of file GraphicsDevice.cs.
    {
        if (P_0)
        {
            try
            {
                _007EGraphicsDevice();
                return;
            }
            finally
            {
                ((IDisposable)d3dCaps).Dispose();
            }
        }
        try
        {
            _0021GraphicsDevice();
        }
        finally
        {
            base.Finalize();
        }
    }
References Microsoft.Xna.Framework.Graphics.GraphicsDevice._0021GraphicsDevice(), Microsoft.Xna.Framework.Graphics.GraphicsDevice._007EGraphicsDevice(), and Microsoft.Xna.Framework.Graphics.GraphicsDevice.d3dCaps.
Referenced by Microsoft.Xna.Framework.Graphics.IndexBuffer.IndexBuffer(), Microsoft.Xna.Framework.Graphics.OcclusionQuery.OcclusionQuery(), and Microsoft.Xna.Framework.Graphics.VertexBuffer.VertexBuffer().