Terraria: Microsoft.Xna.Framework.Graphics.GraphicsDevice.BeginUserPrimitives
BeginUserPrimitives()
unsafe void Microsoft.Xna.Framework.Graphics.GraphicsDevice.BeginUserPrimitives (VertexDeclaration vertexDeclaration) inline private
Definition at line 1520 of file GraphicsDevice.cs.
    {
        int num = 0;
        if (0 < currentVertexBufferCount)
        {
            do
            {
                if (num > 0)
                {
                    IDirect3DDevice9* ptr = pComPtr;
                    ((delegate* unmanaged[Stdcall, Stdcall]<IntPtr, uint, IDirect3DVertexBuffer9*, uint, uint, int>)(int)(*(uint*)(*(int*)ptr + 400)))((nint)ptr, (uint)num, null, 0u, 0u);
                }
                currentVertexBuffers[num] = default(VertexBufferBinding);
                num++;
            }
            while (num < currentVertexBufferCount);
        }
        currentVertexBufferCount = 0;
        instanceStreamMask = 0;
        vertexDeclarationManager.SetVertexDeclaration(vertexDeclaration);
        if (!_insideScene)
        {
            IDirect3DDevice9* intPtr = pComPtr;
            ((delegate* unmanaged[Stdcall, Stdcall]<IntPtr, int>)(int)(*(uint*)(*(int*)intPtr + 164)))((nint)intPtr);
            _insideScene = true;
        }
    }
References Microsoft.Xna.Framework.Graphics.GraphicsDevice._insideScene, Microsoft.Xna.Framework.Graphics.GraphicsDevice.currentVertexBufferCount, Microsoft.Xna.Framework.Graphics.GraphicsDevice.currentVertexBuffers, Microsoft.Xna.Framework.Graphics.GraphicsDevice.instanceStreamMask, Microsoft.Xna.Framework.Graphics.GraphicsDevice.pComPtr, Microsoft.Xna.Framework.Graphics.DeclarationManager.SetVertexDeclaration(), and Microsoft.Xna.Framework.Graphics.GraphicsDevice.vertexDeclarationManager.
Referenced by Microsoft.Xna.Framework.Graphics.GraphicsDevice.DrawUserIndexedPrimitives< T >(), and Microsoft.Xna.Framework.Graphics.GraphicsDevice.DrawUserPrimitives< T >().