Terraria: Microsoft.Xna.Framework.Graphics.GraphicsDevice.ResolveRenderTarget
ResolveRenderTarget()
unsafe void Microsoft.Xna.Framework.Graphics.GraphicsDevice.ResolveRenderTarget (int index) inline private
Definition at line 2055 of file GraphicsDevice.cs.
    {
        int num = 0;
        RenderTargetHelper renderTargetHelper = currentRenderTargets[index];
        RenderTargetBinding[] array = currentRenderTargetBindings;
        Texture renderTarget = array[index]._renderTarget;
        CubeMapFace cubeMapFace = array[index]._cubeMapFace;
        renderTarget.isActiveRenderTarget = false;
        if (renderTarget.GetComPtr() == null)
        {
            return;
        }
        if (_insideScene)
        {
            IDirect3DDevice9* intPtr = pComPtr;
            ((delegate* unmanaged[Stdcall, Stdcall]<IntPtr, int>)(int)(*(uint*)(*(int*)intPtr + 168)))((nint)intPtr);
        }
        IDirect3DSurface9* ptr = renderTargetHelper.GetDestinationSurface(cubeMapFace, 0);
        IDirect3DSurface9* pRenderTargetSurface = renderTargetHelper.pRenderTargetSurface;
        if (pRenderTargetSurface != null)
        {
            IDirect3DSurface9* ptr2 = pRenderTargetSurface;
            IDirect3DDevice9* ptr3 = pComPtr;
            int num2 = ((delegate* unmanaged[Stdcall, Stdcall]<IntPtr, IDirect3DSurface9*, tagRECT*, IDirect3DSurface9*, tagRECT*, _D3DTEXTUREFILTERTYPE, int>)(int)(*(uint*)(*(int*)ptr3 + 136)))((nint)ptr3, ptr2, null, ptr, null, (_D3DTEXTUREFILTERTYPE)2);
            if (num2 >= 0)
            {
                num = num2;
            }
            else
            {
                IDirect3DDevice9* ptr4 = pComPtr;
                int num3 = ((delegate* unmanaged[Stdcall, Stdcall]<IntPtr, IDirect3DSurface9*, tagRECT*, IDirect3DSurface9*, tagRECT*, _D3DTEXTUREFILTERTYPE, int>)(int)(*(uint*)(*(int*)ptr4 + 136)))((nint)ptr4, ptr2, null, ptr, null, (_D3DTEXTUREFILTERTYPE)0);
                num = ((num3 < 0) ? _003CModule_003E.D3DXLoadSurfaceFromSurface(ptr, null, null, ptr2, null, null, uint.MaxValue, 0u) : num3);
            }
        }
        uint levelCount = (uint)renderTarget.LevelCount;
        uint num4 = 1u;
        if (1 < levelCount)
        {
            do
            {
                if (num >= 0)
                {
                    IDirect3DSurface9* destinationSurface = renderTargetHelper.GetDestinationSurface(cubeMapFace, (int)num4);
                    IDirect3DDevice9* ptr5 = pComPtr;
                    int num5 = ((delegate* unmanaged[Stdcall, Stdcall]<IntPtr, IDirect3DSurface9*, tagRECT*, IDirect3DSurface9*, tagRECT*, _D3DTEXTUREFILTERTYPE, int>)(int)(*(uint*)(*(int*)ptr5 + 136)))((nint)ptr5, ptr, null, destinationSurface, null, (_D3DTEXTUREFILTERTYPE)2);
                    if (num5 >= 0)
                    {
                        num = num5;
                    }
                    else
                    {
                        ptr5 = pComPtr;
                        num5 = ((delegate* unmanaged[Stdcall, Stdcall]<IntPtr, IDirect3DSurface9*, tagRECT*, IDirect3DSurface9*, tagRECT*, _D3DTEXTUREFILTERTYPE, int>)(int)(*(uint*)(*(int*)ptr5 + 136)))((nint)ptr5, ptr, null, destinationSurface, null, (_D3DTEXTUREFILTERTYPE)0);
                        num = ((num5 < 0) ? _003CModule_003E.D3DXLoadSurfaceFromSurface(destinationSurface, null, null, ptr, null, null, uint.MaxValue, 0u) : num5);
                    }
                    if (ptr != null)
                    {
                        IDirect3DSurface9* intPtr2 = ptr;
                        ((delegate* unmanaged[Stdcall, Stdcall]<IntPtr, uint>)(int)(*(uint*)(*(int*)intPtr2 + 8)))((nint)intPtr2);
                    }
                    ptr = destinationSurface;
                }
                num4++;
            }
            while (num4 < levelCount);
        }
        if (ptr != null)
        {
            IDirect3DSurface9* intPtr3 = ptr;
            ((delegate* unmanaged[Stdcall, Stdcall]<IntPtr, uint>)(int)(*(uint*)(*(int*)intPtr3 + 8)))((nint)intPtr3);
        }
        if (_insideScene)
        {
            IDirect3DDevice9* intPtr4 = pComPtr;
            ((delegate* unmanaged[Stdcall, Stdcall]<IntPtr, int>)(int)(*(uint*)(*(int*)intPtr4 + 164)))((nint)intPtr4);
        }
        if (num < 0)
        {
            throw GraphicsHelpers.GetExceptionFromResult((uint)num);
        }
    }
References Microsoft.Xna.Framework.Graphics.GraphicsDevice._insideScene, System.array, Microsoft.Xna.Framework.Graphics.GraphicsDevice.currentRenderTargetBindings, Microsoft.Xna.Framework.Graphics.GraphicsDevice.currentRenderTargets, Microsoft.Xna.Framework.Graphics.Texture.GetComPtr(), Microsoft.Xna.Framework.Graphics.RenderTargetHelper.GetDestinationSurface(), Microsoft.Xna.Framework.Graphics.GraphicsHelpers.GetExceptionFromResult(), System.index, Microsoft.Xna.Framework.Graphics.Texture.LevelCount, Microsoft.Xna.Framework.Graphics.GraphicsDevice.pComPtr, and Microsoft.Xna.Framework.Graphics.RenderTargetHelper.pRenderTargetSurface.
Referenced by Microsoft.Xna.Framework.Graphics.GraphicsDevice.SetRenderTargets().