Terraria: Microsoft.Xna.Framework.Graphics.GraphicsDevice.ConvertPresentationParametersToNative
ConvertPresentationParametersToNative()
unsafe void Microsoft.Xna.Framework.Graphics.GraphicsDevice.ConvertPresentationParametersToNative (GraphicsAdapter adapter, PresentationParameters presentationParameters, _D3DPRESENT_PARAMETERS_ * pp) inline private
Definition at line 1007 of file GraphicsDevice.cs.
    {
        if (presentationParameters.DeviceWindowHandle == IntPtr.Zero)
        {
            throw new ArgumentException(FrameworkResources.NullWindowHandleNotAllowed);
        }
        Helpers.ValidateOrientation(presentationParameters.DisplayOrientation);
        if (presentationParameters.BackBufferWidth <= 0 || presentationParameters.BackBufferHeight <= 0)
        {
            System.Runtime.CompilerServices.Unsafe.SkipInit(out tagRECT tagRECT);
            if (!presentationParameters.IsFullScreen && _003CModule_003E.GetClientRect((HWND__*)presentationParameters.DeviceWindowHandle.ToPointer(), &tagRECT) != 0)
            {
                presentationParameters.BackBufferWidth = System.Runtime.CompilerServices.Unsafe.As<tagRECT, int>(ref System.Runtime.CompilerServices.Unsafe.AddByteOffset(ref tagRECT, 8)) - *(int*)(&tagRECT);
                presentationParameters.BackBufferHeight = System.Runtime.CompilerServices.Unsafe.As<tagRECT, int>(ref System.Runtime.CompilerServices.Unsafe.AddByteOffset(ref tagRECT, 12)) - System.Runtime.CompilerServices.Unsafe.As<tagRECT, int>(ref System.Runtime.CompilerServices.Unsafe.AddByteOffset(ref tagRECT, 4));
            }
            else
            {
                presentationParameters.BackBufferWidth = adapter.CurrentDisplayMode.Width;
                presentationParameters.BackBufferHeight = adapter.CurrentDisplayMode.Height;
            }
        }
        SurfaceFormat selectedFormat = presentationParameters.BackBufferFormat;
        DepthFormat selectedDepthFormat = presentationParameters.DepthStencilFormat;
        int selectedMultiSampleCount = presentationParameters.MultiSampleCount;
        adapter.QueryFormat(isBackBuffer: true, _deviceType, _graphicsProfile, selectedFormat, selectedDepthFormat, selectedMultiSampleCount, out selectedFormat, out selectedDepthFormat, out selectedMultiSampleCount);
        *(int*)pp = presentationParameters.BackBufferWidth;
        *(int*)((byte*)pp + 4) = presentationParameters.BackBufferHeight;
        *(_D3DFORMAT*)((byte*)pp + 8) = _003CModule_003E.ConvertXnaFormatToWindows(selectedFormat);
        *(int*)((byte*)pp + 12) = 1;
        int num = (((*(_D3DFORMAT*)((byte*)pp + 40) = _003CModule_003E.ConvertXnaFormatToWindows(selectedDepthFormat)) != 0) ? 1 : 0);
        *(int*)((byte*)pp + 36) = num;
        *(int*)((byte*)pp + 16) = selectedMultiSampleCount;
        *(int*)((byte*)pp + 28) = (int)presentationParameters.DeviceWindowHandle.ToPointer();
        int num2 = ((!presentationParameters.IsFullScreen) ? 1 : 0);
        *(int*)((byte*)pp + 32) = num2;
        *(int*)((byte*)pp + 24) = 1;
        switch (presentationParameters.PresentationInterval)
        {
        default:
            *(int*)((byte*)pp + 52) = 0;
            break;
        case PresentInterval.Immediate:
            *(int*)((byte*)pp + 52) = int.MinValue;
            break;
        case PresentInterval.Two:
            if (presentationParameters.IsFullScreen && ((uint)(*(int*)((byte*)d3dCaps.t + 20)) & 2u) != 0)
            {
                *(int*)((byte*)pp + 52) = 2;
            }
            else
            {
                *(int*)((byte*)pp + 52) = 1;
            }
            break;
        case PresentInterval.One:
            *(int*)((byte*)pp + 52) = 1;
            break;
        }
    }
References Microsoft.Xna.Framework.Graphics.GraphicsDevice._deviceType, Microsoft.Xna.Framework.Graphics.GraphicsDevice._graphicsProfile, Microsoft.Xna.Framework.Graphics.PresentationParameters.BackBufferFormat, Microsoft.Xna.Framework.Graphics.PresentationParameters.BackBufferHeight, Microsoft.Xna.Framework.Graphics.PresentationParameters.BackBufferWidth, Microsoft.Xna.Framework.Graphics.GraphicsAdapter.CurrentDisplayMode, Microsoft.Xna.Framework.Graphics.PresentationParameters.DepthStencilFormat, Microsoft.Xna.Framework.Graphics.PresentationParameters.DeviceWindowHandle, Microsoft.Xna.Framework.Graphics.PresentationParameters.DisplayOrientation, Microsoft.Xna.Framework.Graphics.DisplayMode.Height, Microsoft.Xna.Framework.Graphics.PresentationParameters.IsFullScreen, Microsoft.Xna.Framework.Graphics.PresentationParameters.MultiSampleCount, Microsoft.Xna.Framework.FrameworkResources.NullWindowHandleNotAllowed, Microsoft.Xna.Framework.Graphics.PresentationParameters.PresentationInterval, Microsoft.Xna.Framework.Graphics.GraphicsAdapter.QueryFormat(), System.IntPtr.ToPointer(), Microsoft.Xna.Framework.Helpers.ValidateOrientation(), Microsoft.Xna.Framework.Graphics.DisplayMode.Width, and System.IntPtr.Zero.
Referenced by Microsoft.Xna.Framework.Graphics.GraphicsDevice.CreateDevice(), and Microsoft.Xna.Framework.Graphics.GraphicsDevice.Reset().