Terraria: Microsoft.Xna.Framework.Graphics.GraphicsDevice.GraphicsDevice
GraphicsDevice() [2/2]
Microsoft.Xna.Framework.Graphics.GraphicsDevice.GraphicsDevice (GraphicsAdapter adapter, GraphicsProfile graphicsProfile, PresentationParameters presentationParameters) inline
Definition at line 1133 of file GraphicsDevice.cs.
    {
        EmbeddedNativeType_003C_D3DCAPS9_003E embeddedNativeType_003C_D3DCAPS9_003E = new EmbeddedNativeType_003C_D3DCAPS9_003E();
        try
        {
            d3dCaps = embeddedNativeType_003C_D3DCAPS9_003E;
            base._002Ector();
            if (presentationParameters == null)
            {
                throw new ArgumentNullException("presentationParameters", FrameworkResources.NullNotAllowed);
            }
            if (adapter == null)
            {
                throw new ArgumentNullException("adapter", FrameworkResources.NullNotAllowed);
            }
            _deviceType = GraphicsAdapter.CurrentDeviceType;
            _graphicsProfile = graphicsProfile;
            _profileCapabilities = ProfileCapabilities.GetInstance(graphicsProfile);
            if (!adapter.IsProfileSupported(_deviceType, _graphicsProfile))
            {
                _profileCapabilities.ThrowNotSupportedException(FrameworkResources.ProfileInvalidDevice);
            }
            CreateDevice(adapter, presentationParameters);
            pCurrentAdapter = adapter;
            _DrawGuideHandler = null;
            pInternalCachedParams = presentationParameters.Clone();
            pPublicCachedParams = presentationParameters.Clone();
            CreateHelperClasses();
            InitializeDeviceState();
            GuideRendererConnector.GuideRendererType = typeof(GuideRenderer);
            return;
        }
        catch
        {
            //try-fault
            ((IDisposable)d3dCaps).Dispose();
            throw;
        }
    }
References Microsoft.Xna.Framework.Graphics.GraphicsDevice._deviceType, Microsoft.Xna.Framework.Graphics.GraphicsDevice._DrawGuideHandler, Microsoft.Xna.Framework.Graphics.GraphicsDevice._graphicsProfile, Microsoft.Xna.Framework.Graphics.GraphicsDevice._profileCapabilities, Microsoft.Xna.Framework.Graphics.PresentationParameters.Clone(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.CreateDevice(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.CreateHelperClasses(), Microsoft.Xna.Framework.Graphics.GraphicsAdapter.CurrentDeviceType, Microsoft.Xna.Framework.Graphics.GraphicsDevice.d3dCaps, Microsoft.Xna.Framework.Graphics.ProfileCapabilities.GetInstance(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.InitializeDeviceState(), Microsoft.Xna.Framework.Graphics.GraphicsAdapter.IsProfileSupported(), Microsoft.Xna.Framework.FrameworkResources.NullNotAllowed, Microsoft.Xna.Framework.Graphics.GraphicsDevice.pCurrentAdapter, Microsoft.Xna.Framework.Graphics.GraphicsDevice.pInternalCachedParams, Microsoft.Xna.Framework.Graphics.GraphicsDevice.pPublicCachedParams, Microsoft.Xna.Framework.FrameworkResources.ProfileInvalidDevice, and Microsoft.Xna.Framework.Graphics.ProfileCapabilities.ThrowNotSupportedException().