Terraria: Microsoft.Xna.Framework.Graphics.GraphicsDevice.GetManagedObject
GetManagedObject()
static unsafe GraphicsDevice Microsoft.Xna.Framework.Graphics.GraphicsDevice.GetManagedObject (IDirect3DDevice9 * pInterface, GraphicsDevice pDevice, uint pool) inline static package
Definition at line 2588 of file GraphicsDevice.cs.
    {
        GraphicsDevice graphicsDevice = pDevice.pResourceManager.GetCachedObject(pInterface) as GraphicsDevice;
        if (graphicsDevice != null)
        {
            ((delegate* unmanaged[Stdcall, Stdcall]<IntPtr, uint>)(int)(*(uint*)(*(int*)pInterface + 8)))((nint)pInterface);
            graphicsDevice.isDisposed = false;
            GC.ReRegisterForFinalize(graphicsDevice);
        }
        else
        {
            graphicsDevice = new GraphicsDevice(pInterface, pDevice);
            pDevice.pResourceManager.AddTrackedObject(graphicsDevice, pInterface, pool, 0uL, ref graphicsDevice._internalHandle);
        }
        return graphicsDevice;
    }
References Microsoft.Xna.Framework.Graphics.GraphicsDevice.GraphicsDevice(), Microsoft.Xna.Framework.Graphics.GraphicsDevice._internalHandle, Microsoft.Xna.Framework.Graphics.DeviceResourceManager.AddTrackedObject(), Microsoft.Xna.Framework.Graphics.DeviceResourceManager.GetCachedObject(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.pResourceManager, and System.GC.ReRegisterForFinalize().