Terraria: Microsoft.Xna.Framework.Graphics.GraphicsDevice._0021GraphicsDevice
_0021GraphicsDevice()
unsafe void Microsoft.Xna.Framework.Graphics.GraphicsDevice._0021GraphicsDevice () inline private
Definition at line 2550 of file GraphicsDevice.cs.
    {
        if (!isDisposed)
        {
            isDisposed = true;
            pResourceManager?.ReleaseAllDeviceResources();
            vertexDeclarationManager?.ReleaseAllDeclarations();
            IDirect3DSurface9* ptr = pImplicitDepthSurface;
            if (ptr != null)
            {
                ((delegate* unmanaged[Stdcall, Stdcall]<IntPtr, uint>)(int)(*(uint*)(*(int*)ptr + 8)))((nint)ptr);
                pImplicitDepthSurface = null;
            }
            StateTrackerDevice* ptr2 = pStateTracker;
            if (ptr2 != null)
            {
                ((delegate* unmanaged[Stdcall, Stdcall]<IntPtr, uint>)(int)(*(uint*)(*(int*)ptr2 + 8)))((nint)ptr2);
                pStateTracker = null;
            }
            IDirect3DDevice9* ptr3 = pComPtr;
            if (ptr3 != null)
            {
                ((delegate* unmanaged[Stdcall, Stdcall]<IntPtr, uint>)(int)(*(uint*)(*(int*)ptr3 + 8)))((nint)ptr3);
                pComPtr = null;
            }
        }
    }
References Microsoft.Xna.Framework.Graphics.GraphicsDevice.isDisposed, Microsoft.Xna.Framework.Graphics.GraphicsDevice.pComPtr, Microsoft.Xna.Framework.Graphics.GraphicsDevice.pImplicitDepthSurface, Microsoft.Xna.Framework.Graphics.GraphicsDevice.pResourceManager, Microsoft.Xna.Framework.Graphics.GraphicsDevice.pStateTracker, Microsoft.Xna.Framework.Graphics.DeclarationManager.ReleaseAllDeclarations(), Microsoft.Xna.Framework.Graphics.DeviceResourceManager.ReleaseAllDeviceResources(), and Microsoft.Xna.Framework.Graphics.GraphicsDevice.vertexDeclarationManager.
Referenced by Microsoft.Xna.Framework.Graphics.GraphicsDevice._007EGraphicsDevice(), and Microsoft.Xna.Framework.Graphics.GraphicsDevice.Dispose().