Terraria: Microsoft.Xna.Framework.Graphics.GraphicsDevice.GetBufferUsage
GetBufferUsage()
uint Microsoft.Xna.Framework.Graphics.GraphicsDevice.GetBufferUsage (uint usage) inline package
Definition at line 2499 of file GraphicsDevice.cs.
    {
        usage = (((_creationFlags & 0x20) == 0) ? (usage & 0xFFFFFFEFu) : (usage | 0x10u));
        return usage;
    }
References Microsoft.Xna.Framework.Graphics.GraphicsDevice._creationFlags.
Referenced by Microsoft.Xna.Framework.Graphics.IndexBuffer.CreateBuffer(), Microsoft.Xna.Framework.Graphics.VertexBuffer.CreateBuffer(), Microsoft.Xna.Framework.Graphics.DynamicIndexBuffer.RecreateAndPopulateObject(), Microsoft.Xna.Framework.Graphics.DynamicVertexBuffer.RecreateAndPopulateObject(), Microsoft.Xna.Framework.Graphics.IndexBuffer.RecreateAndPopulateObject(), and Microsoft.Xna.Framework.Graphics.VertexBuffer.RecreateAndPopulateObject().