Terraria: Microsoft.Xna.Framework.Graphics.GraphicsDevice.Reset
Reset() [3/3]
unsafe void Microsoft.Xna.Framework.Graphics.GraphicsDevice.Reset (PresentationParameters presentationParameters, GraphicsAdapter graphicsAdapter) inline
Definition at line 1183 of file GraphicsDevice.cs.
    {
        IntPtr intPtr = (IntPtr)pComPtr;
        Helpers.CheckDisposed(this, intPtr);
        bool flag = false;
        if (presentationParameters == null)
        {
            throw new ArgumentNullException("presentationParameters", FrameworkResources.NullNotAllowed);
        }
        if (graphicsAdapter == null)
        {
            throw new ArgumentNullException("graphicsAdapter", FrameworkResources.NullNotAllowed);
        }
        EventArgs empty = EventArgs.Empty;
        _003Cbacking_store_003EDeviceResetting?.Invoke(this, empty);
        int num = ((currentRenderTargetCount == 0 && presentationParameters.BackBufferWidth == pInternalCachedParams.BackBufferWidth && presentationParameters.BackBufferHeight == pInternalCachedParams.BackBufferHeight) ? 1 : 0);
        bool saveViewport = (byte)num != 0;
        SavedDeviceState savedDeviceState = new SavedDeviceState(this, saveViewport);
        if (graphicsAdapter != pCurrentAdapter && _deviceType == (_D3DDEVTYPE)1 && graphicsAdapter.IsProfileSupported((_D3DDEVTYPE)1, _graphicsProfile))
        {
            flag = true;
        }
        EffectPass effectPass = activePass;
        if (effectPass != null)
        {
            effectPass.EndPass();
            activePass = null;
        }
        pResourceManager.ReleaseAllDefaultPoolResources();
        lazyClearFlags = 0;
        savedBackBufferClearFlags = 0;
        Indices = null;
        SetVertexBuffers(null, 0);
        SetRenderTargets(null, 0);
        pTextureCollection.ResetState();
        pVertexTextureCollection.ResetState();
        StateTrackerDevice* ptr = pStateTracker;
        ((delegate* unmanaged[Stdcall, Stdcall]<IntPtr, IDirect3DVertexDeclaration9*, int>)(int)(*(uint*)(*(int*)ptr + 348)))((nint)ptr, null);
        ptr = pStateTracker;
        ((delegate* unmanaged[Stdcall, Stdcall]<IntPtr, IDirect3DVertexShader9*, int>)(int)(*(uint*)(*(int*)ptr + 368)))((nint)ptr, null);
        ptr = pStateTracker;
        ((delegate* unmanaged[Stdcall, Stdcall]<IntPtr, IDirect3DPixelShader9*, int>)(int)(*(uint*)(*(int*)ptr + 428)))((nint)ptr, null);
        vertexDeclarationManager.ReleaseAllDeclarations();
        IDirect3DSurface9* ptr2 = pImplicitDepthSurface;
        if (ptr2 != null)
        {
            ((delegate* unmanaged[Stdcall, Stdcall]<IntPtr, uint>)(int)(*(uint*)(*(int*)ptr2 + 8)))((nint)ptr2);
            pImplicitDepthSurface = null;
        }
        if (flag)
        {
            pResourceManager.ReleaseAutomaticResources();
            ptr = pStateTracker;
            if (ptr != null)
            {
                StateTrackerDevice* intPtr2 = ptr;
                ((delegate* unmanaged[Stdcall, Stdcall]<IntPtr, uint>)(int)(*(uint*)(*(int*)intPtr2 + 8)))((nint)intPtr2);
                pStateTracker = null;
            }
            IDirect3DDevice9* ptr3 = pComPtr;
            IDirect3DDevice9* intPtr3 = ptr3;
            ((delegate* unmanaged[Stdcall, Stdcall]<IntPtr, uint>)(int)(*(uint*)(*(int*)intPtr3 + 8)))((nint)intPtr3);
            pComPtr = null;
            CreateDevice(graphicsAdapter, presentationParameters);
            pResourceManager.RecreateResources((_D3DPOOL)1, flag);
            pCurrentAdapter = graphicsAdapter;
        }
        else
        {
            System.Runtime.CompilerServices.Unsafe.SkipInit(out _D3DPRESENT_PARAMETERS_ d3DPRESENT_PARAMETERS_);
            *(int*)(&d3DPRESENT_PARAMETERS_) = 0;
            // IL initblk instruction
            System.Runtime.CompilerServices.Unsafe.InitBlock(ref System.Runtime.CompilerServices.Unsafe.AddByteOffset(ref d3DPRESENT_PARAMETERS_, 4), 0, 52);
            ConvertPresentationParametersToNative(pCurrentAdapter, presentationParameters, &d3DPRESENT_PARAMETERS_);
            IDirect3DDevice9* ptr3 = pComPtr;
            int num2 = ((delegate* unmanaged[Stdcall, Stdcall]<IntPtr, _D3DPRESENT_PARAMETERS_*, int>)(int)(*(uint*)(*(int*)ptr3 + 64)))((nint)ptr3, &d3DPRESENT_PARAMETERS_);
            ConvertPresentationParametersToManaged(&d3DPRESENT_PARAMETERS_, presentationParameters);
            if (num2 < 0)
            {
                throw GraphicsHelpers.GetExceptionFromResult((uint)num2);
            }
        }
        fixed (IDirect3DSurface9** ptr4 = &pImplicitDepthSurface)
        {
            int num3 = *(int*)pComPtr + 160;
            ((delegate* unmanaged[Stdcall, Stdcall]<IntPtr, IDirect3DSurface9**, int>)(int)(*(uint*)num3))((nint)pComPtr, ptr4);
            pResourceManager.RecreateResources((_D3DPOOL)0, flag);
            pInternalCachedParams = presentationParameters.Clone();
            pPublicCachedParams = presentationParameters.Clone();
            InitializeDeviceState();
            savedDeviceState.Restore();
            EventArgs empty2 = EventArgs.Empty;
            _003Cbacking_store_003EDeviceReset?.Invoke(this, empty2);
            _insideScene = false;
        }
    }
References Microsoft.Xna.Framework.Graphics.GraphicsDevice._003Cbacking_store_003EDeviceReset, Microsoft.Xna.Framework.Graphics.GraphicsDevice._003Cbacking_store_003EDeviceResetting, Microsoft.Xna.Framework.Graphics.GraphicsDevice._deviceType, Microsoft.Xna.Framework.Graphics.GraphicsDevice._graphicsProfile, Microsoft.Xna.Framework.Graphics.GraphicsDevice._insideScene, Microsoft.Xna.Framework.Graphics.GraphicsDevice.activePass, Microsoft.Xna.Framework.Graphics.PresentationParameters.BackBufferHeight, Microsoft.Xna.Framework.Helpers.CheckDisposed(), Microsoft.Xna.Framework.Graphics.PresentationParameters.Clone(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.ConvertPresentationParametersToManaged(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.ConvertPresentationParametersToNative(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.CreateDevice(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.currentRenderTargetCount, System.EventArgs.Empty, Microsoft.Xna.Framework.Graphics.EffectPass.EndPass(), Microsoft.Xna.Framework.Graphics.GraphicsHelpers.GetExceptionFromResult(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.Indices, System.Runtime.CompilerServices.Unsafe.InitBlock(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.InitializeDeviceState(), Microsoft.Xna.Framework.Graphics.GraphicsAdapter.IsProfileSupported(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.lazyClearFlags, Microsoft.Xna.Framework.FrameworkResources.NullNotAllowed, Microsoft.Xna.Framework.Graphics.GraphicsDevice.pComPtr, Microsoft.Xna.Framework.Graphics.GraphicsDevice.pCurrentAdapter, Microsoft.Xna.Framework.Graphics.GraphicsDevice.pImplicitDepthSurface, Microsoft.Xna.Framework.Graphics.GraphicsDevice.pInternalCachedParams, Microsoft.Xna.Framework.Graphics.GraphicsDevice.pPublicCachedParams, Microsoft.Xna.Framework.Graphics.GraphicsDevice.pResourceManager, Microsoft.Xna.Framework.Graphics.GraphicsDevice.pStateTracker, Microsoft.Xna.Framework.Graphics.GraphicsDevice.pTextureCollection, Microsoft.Xna.Framework.Graphics.GraphicsDevice.pVertexTextureCollection, Microsoft.Xna.Framework.Graphics.DeviceResourceManager.RecreateResources(), Microsoft.Xna.Framework.Graphics.DeclarationManager.ReleaseAllDeclarations(), Microsoft.Xna.Framework.Graphics.DeviceResourceManager.ReleaseAllDefaultPoolResources(), Microsoft.Xna.Framework.Graphics.DeviceResourceManager.ReleaseAutomaticResources(), Microsoft.Xna.Framework.Graphics.TextureCollection.ResetState(), Microsoft.Xna.Framework.Graphics.SavedDeviceState.Restore(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.savedBackBufferClearFlags, Microsoft.Xna.Framework.Graphics.GraphicsDevice.SetRenderTargets(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.SetVertexBuffers(), and Microsoft.Xna.Framework.Graphics.GraphicsDevice.vertexDeclarationManager.