Terraria: Microsoft.Xna.Framework.Graphics.GraphicsDevice.SetVertexBuffer
SetVertexBuffer() [2/2]
unsafe void Microsoft.Xna.Framework.Graphics.GraphicsDevice.SetVertexBuffer (VertexBuffer vertexBuffer, int vertexOffset) inline
Definition at line 2373 of file GraphicsDevice.cs.
    {
        if (vertexBuffer != null)
        {
            VertexBufferBinding vertexBufferBinding = new VertexBufferBinding(vertexBuffer, vertexOffset);
            SetVertexBuffers(&vertexBufferBinding, 1);
        }
        else
        {
            SetVertexBuffers(null, 0);
        }
    }
References Microsoft.Xna.Framework.Graphics.GraphicsDevice.SetVertexBuffers().
Referenced by Terraria.DataStructures.SpriteDrawBuffer.Bind(), Microsoft.Xna.Framework.Graphics.ModelMeshPart.Draw(), Terraria.Graphics.TileBatch.FlushRenderState(), and Microsoft.Xna.Framework.Graphics.SpriteBatch.SetPlatformRenderState().