Terraria: Microsoft.Xna.Framework.Graphics.GraphicsDevice.CreateDevice
CreateDevice()
unsafe void Microsoft.Xna.Framework.Graphics.GraphicsDevice.CreateDevice (GraphicsAdapter adapter, PresentationParameters presentationParameters) inline private
Definition at line 638 of file GraphicsDevice.cs.
    {
        _creationFlags = 38u;
        _D3DCAPS9* t = d3dCaps.t;
        int num = *(int*)GraphicsAdapter.pComPtr + 56;
        int num2 = ((delegate* unmanaged[Stdcall, Stdcall]<IntPtr, uint, _D3DDEVTYPE, _D3DCAPS9*, int>)(int)(*(uint*)num))((nint)GraphicsAdapter.pComPtr, adapter.adapter, _deviceType, t);
        if (num2 < 0)
        {
            throw GraphicsHelpers.GetExceptionFromResult((uint)num2);
        }
        if (_deviceType == (_D3DDEVTYPE)1 && ((uint)(*(int*)((byte*)d3dCaps.t + 28)) & 0x10000u) != 0)
        {
            _creationFlags = (_creationFlags & 0xFFFFFFDFu) | 0x40u;
        }
        System.Runtime.CompilerServices.Unsafe.SkipInit(out _D3DPRESENT_PARAMETERS_ d3DPRESENT_PARAMETERS_);
        *(int*)(&d3DPRESENT_PARAMETERS_) = 0;
        // IL initblk instruction
        System.Runtime.CompilerServices.Unsafe.InitBlock(ref System.Runtime.CompilerServices.Unsafe.AddByteOffset(ref d3DPRESENT_PARAMETERS_, 4), 0, 52);
        ConvertPresentationParametersToNative(adapter, presentationParameters, &d3DPRESENT_PARAMETERS_);
        fixed (IDirect3DDevice9** ptr = &pComPtr)
        {
            try
            {
                int num3 = *(int*)GraphicsAdapter.pComPtr + 64;
                int num4 = ((delegate* unmanaged[Stdcall, Stdcall]<IntPtr, uint, _D3DDEVTYPE, HWND__*, uint, _D3DPRESENT_PARAMETERS_*, IDirect3DDevice9**, int>)(int)(*(uint*)num3))((nint)GraphicsAdapter.pComPtr, adapter.adapter, _deviceType, (HWND__*)(int)System.Runtime.CompilerServices.Unsafe.As<_D3DPRESENT_PARAMETERS_, uint>(ref System.Runtime.CompilerServices.Unsafe.AddByteOffset(ref d3DPRESENT_PARAMETERS_, 28)), _creationFlags, &d3DPRESENT_PARAMETERS_, ptr);
                if (num4 < 0)
                {
                    throw GraphicsHelpers.GetExceptionFromResult((uint)num4);
                }
            }
            catch
            {
                //try-fault
                ptr = null;
                throw;
            }
        }
        StateTrackerDevice* ptr2 = (StateTrackerDevice*)_003CModule_003E.@new(144u, (nothrow_t*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref _003CModule_003E.std_002Enothrow));
        StateTrackerDevice* ptr3;
        try
        {
            if (ptr2 != null)
            {
                ProfileCapabilities profileCapabilities = _profileCapabilities;
                ptr3 = _003CModule_003E.Microsoft_002EXna_002EFramework_002EGraphics_002EStateTrackerDevice_002E_007Bctor_007D(ptr2, pComPtr, profileCapabilities.VertexShaderVersion, profileCapabilities.PixelShaderVersion);
            }
            else
            {
                ptr3 = null;
            }
        }
        catch
        {
            //try-fault
            _003CModule_003E.delete(ptr2, (nothrow_t*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref _003CModule_003E.std_002Enothrow));
            throw;
        }
        pStateTracker = ptr3;
        if (ptr3 == null)
        {
            throw new OutOfMemoryException();
        }
        ConvertPresentationParametersToManaged(&d3DPRESENT_PARAMETERS_, presentationParameters);
        if (_profileCapabilities.OcclusionQuery)
        {
            IDirect3DQuery9* ptr4 = null;
            IDirect3DDevice9* ptr5 = pComPtr;
            int num5 = ((delegate* unmanaged[Stdcall, Stdcall]<IntPtr, _D3DQUERYTYPE, IDirect3DQuery9**, int>)(int)(*(uint*)(*(int*)ptr5 + 472)))((nint)ptr5, (_D3DQUERYTYPE)9, &ptr4);
            if (ptr4 != null)
            {
                IDirect3DQuery9* intPtr = ptr4;
                ((delegate* unmanaged[Stdcall, Stdcall]<IntPtr, uint>)(int)(*(uint*)(*(int*)intPtr + 8)))((nint)intPtr);
                ptr4 = null;
            }
            if (num5 < 0)
            {
                StateTrackerDevice* ptr6 = pStateTracker;
                if (ptr6 != null)
                {
                    ((delegate* unmanaged[Stdcall, Stdcall]<IntPtr, uint>)(int)(*(uint*)(*(int*)ptr6 + 8)))((nint)ptr6);
                    pStateTracker = null;
                }
                IDirect3DDevice9* ptr7 = pComPtr;
                if (ptr7 != null)
                {
                    ((delegate* unmanaged[Stdcall, Stdcall]<IntPtr, uint>)(int)(*(uint*)(*(int*)ptr7 + 8)))((nint)ptr7);
                    pComPtr = null;
                }
                _profileCapabilities.ThrowNotSupportedException(FrameworkResources.ProfileInvalidDevice);
            }
        }
        try
        {
            return;
        }
        catch
        {
            //try-fault
            throw;
        }
    }
References Microsoft.Xna.Framework.Graphics.GraphicsDevice._creationFlags, Microsoft.Xna.Framework.Graphics.GraphicsDevice._deviceType, Microsoft.Xna.Framework.Graphics.GraphicsDevice._profileCapabilities, Microsoft.Xna.Framework.Graphics.GraphicsAdapter.adapter, Microsoft.Xna.Framework.Graphics.GraphicsDevice.ConvertPresentationParametersToManaged(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.ConvertPresentationParametersToNative(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.d3dCaps, Microsoft.Xna.Framework.Graphics.GraphicsHelpers.GetExceptionFromResult(), System.Runtime.CompilerServices.Unsafe.InitBlock(), Microsoft.Xna.Framework.Graphics.ProfileCapabilities.OcclusionQuery, Microsoft.Xna.Framework.Graphics.GraphicsAdapter.pComPtr, Microsoft.Xna.Framework.Graphics.GraphicsDevice.pComPtr, Microsoft.Xna.Framework.Graphics.ProfileCapabilities.PixelShaderVersion, Microsoft.Xna.Framework.FrameworkResources.ProfileInvalidDevice, Microsoft.Xna.Framework.Graphics.GraphicsDevice.pStateTracker, Microsoft.Xna.Framework.Graphics.ProfileCapabilities.ThrowNotSupportedException(), and Microsoft.Xna.Framework.Graphics.ProfileCapabilities.VertexShaderVersion.
Referenced by Microsoft.Xna.Framework.Graphics.GraphicsDevice.GraphicsDevice(), and Microsoft.Xna.Framework.Graphics.GraphicsDevice.Reset().