Terraria: Microsoft.Xna.Framework.Graphics.GraphicsDevice.VerifyCanDraw
VerifyCanDraw()
unsafe void Microsoft.Xna.Framework.Graphics.GraphicsDevice.VerifyCanDraw ([MarshalAs(UnmanagedType.U1)] bool bUserPrimitives, [MarshalAs(UnmanagedType.U1)] bool bIndexedPrimitives) inline package
Definition at line 881 of file GraphicsDevice.cs.
    {
        if (lazyClearFlags != 0)
        {
            ClearDirtyBuffers();
        }
        int num = 0;
        if (0 < currentRenderTargetCount)
        {
            do
            {
                currentRenderTargets[num].pTexture.SetContentLost(isContentLost: false);
                num++;
            }
            while (num < currentRenderTargetCount);
        }
        StateTrackerDevice* ptr = pStateTracker;
        uint num2 = *(uint*)((byte*)ptr + 20);
        uint num3 = *(uint*)((byte*)ptr + 24);
        Texture texture;
        if (num2 != 0 && num3 != 0)
        {
            bool num4 = num2 < 768;
            int num5 = ((num3 < 768) ? 1 : 0);
            if ((num4 ? 1 : 0) != num5)
            {
                throw new InvalidOperationException(FrameworkResources.CannotMixShader2and3);
            }
            if (!_003CModule_003E.Microsoft_002EXna_002EFramework_002EGraphics_002EVertexShaderInputSemantics_002EIsCompatibleWithDecl((VertexShaderInputSemantics*)((byte*)ptr + 28), (VertexShaderInputSemantics*)((byte*)ptr + 60)))
            {
                string text = FrameworkResources.MissingVertexShaderInput;
                ptr = pStateTracker;
                System.Runtime.CompilerServices.Unsafe.SkipInit(out _D3DDECLUSAGE usage);
                System.Runtime.CompilerServices.Unsafe.SkipInit(out int num6);
                if (_003CModule_003E.Microsoft_002EXna_002EFramework_002EGraphics_002EVertexShaderInputSemantics_002EGetMissingSemantic((VertexShaderInputSemantics*)((byte*)ptr + 28), (VertexShaderInputSemantics*)((byte*)ptr + 60), &usage, &num6))
                {
                    text = string.Format(args: new object[3]
                    {
                        text,
                        _003CModule_003E.ConvertDxVertexElementUsageToXna(usage),
                        num6
                    }, provider: CultureInfo.CurrentCulture, format: FrameworkResources.MissingVertexShaderInputDetails);
                }
                throw new InvalidOperationException(text);
            }
            if (!willItBlend && *(int*)((byte*)pStateTracker + 112) != 0)
            {
                _profileCapabilities.ThrowNotSupportedException(FrameworkResources.ProfileInvalidBlendFormat, whyWontItBlend);
            }
            StateTrackerDevice* ptr2 = pStateTracker;
            uint num7 = (*(uint*)((byte*)ptr2 + 124) | *(uint*)((byte*)ptr2 + 120) | *(uint*)((byte*)ptr2 + 116)) & *(uint*)((byte*)ptr2 + 136);
            if (num7 != 0)
            {
                int num8 = 0;
                if ((num7 & 1) == 0)
                {
                    do
                    {
                        num8++;
                    }
                    while (((uint)(1 << num8) & num7) == 0);
                    if (num8 >= 16)
                    {
                        texture = pVertexTextureCollection[num8 - 16];
                        goto IL_0183;
                    }
                }
                texture = pTextureCollection[num8];
                goto IL_0183;
            }
            goto IL_01ad;
        }
        throw new InvalidOperationException(FrameworkResources.CannotDrawNoShader);
        IL_0183:
        SurfaceFormat surfaceFormat = texture?.Format ?? ((SurfaceFormat)(-1));
        _profileCapabilities.ThrowNotSupportedException(FrameworkResources.ProfileInvalidFilterFormat, surfaceFormat);
        goto IL_01ad;
        IL_01ad:
        ptr = pStateTracker;
        if (((*(int*)((byte*)ptr + 132) | *(int*)((byte*)ptr + 128)) & *(int*)((byte*)ptr + 140)) != 0)
        {
            _profileCapabilities.ThrowNotSupportedException(FrameworkResources.ProfileNoWrapNonPow2);
        }
        if (!bUserPrimitives)
        {
            if (bIndexedPrimitives && _currentIB == null)
            {
                throw new InvalidOperationException(FrameworkResources.CannotDrawNoData);
            }
            if (currentVertexBufferCount <= 0)
            {
                throw new InvalidOperationException(FrameworkResources.CannotDrawNoData);
            }
        }
    }
References Microsoft.Xna.Framework.Graphics.GraphicsDevice._currentIB, Microsoft.Xna.Framework.Graphics.GraphicsDevice._profileCapabilities, Microsoft.Xna.Framework.FrameworkResources.CannotDrawNoData, Microsoft.Xna.Framework.FrameworkResources.CannotDrawNoShader, Microsoft.Xna.Framework.FrameworkResources.CannotMixShader2and3, Microsoft.Xna.Framework.Graphics.GraphicsDevice.ClearDirtyBuffers(), System.Globalization.CultureInfo.CurrentCulture, Microsoft.Xna.Framework.Graphics.GraphicsDevice.currentRenderTargetCount, Microsoft.Xna.Framework.Graphics.GraphicsDevice.currentRenderTargets, Microsoft.Xna.Framework.Graphics.GraphicsDevice.currentVertexBufferCount, Microsoft.Xna.Framework.Graphics.Texture.Format, System.format, Microsoft.Xna.Framework.Graphics.GraphicsDevice.lazyClearFlags, Microsoft.Xna.Framework.FrameworkResources.MissingVertexShaderInput, Microsoft.Xna.Framework.FrameworkResources.MissingVertexShaderInputDetails, Microsoft.Xna.Framework.FrameworkResources.ProfileInvalidBlendFormat, Microsoft.Xna.Framework.FrameworkResources.ProfileInvalidFilterFormat, Microsoft.Xna.Framework.FrameworkResources.ProfileNoWrapNonPow2, Microsoft.Xna.Framework.Graphics.GraphicsDevice.pStateTracker, Microsoft.Xna.Framework.Graphics.RenderTargetHelper.pTexture, Microsoft.Xna.Framework.Graphics.GraphicsDevice.pTextureCollection, Microsoft.Xna.Framework.Graphics.GraphicsDevice.pVertexTextureCollection, Microsoft.Xna.Framework.Graphics.IDynamicGraphicsResource.SetContentLost(), System.text, Microsoft.Xna.Framework.Graphics.ProfileCapabilities.ThrowNotSupportedException(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.whyWontItBlend, and Microsoft.Xna.Framework.Graphics.GraphicsDevice.willItBlend.
Referenced by Microsoft.Xna.Framework.Graphics.GraphicsDevice.DrawIndexedPrimitives(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.DrawInstancedPrimitives(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.DrawPrimitives(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.DrawUserIndexedPrimitives< T >(), and Microsoft.Xna.Framework.Graphics.GraphicsDevice.DrawUserPrimitives< T >().