Terraria: Microsoft.Xna.Framework.Graphics.GraphicsDevice.GetVertexBuffers
GetVertexBuffers()
VertexBufferBinding[] Microsoft.Xna.Framework.Graphics.GraphicsDevice.GetVertexBuffers () inline
Definition at line 2365 of file GraphicsDevice.cs.
    {
        int num = currentVertexBufferCount;
        VertexBufferBinding[] array = new VertexBufferBinding[num];
        Array.Copy(currentVertexBuffers, array, num);
        return array;
    }
References System.array, System.Array.Copy(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.currentVertexBufferCount, and Microsoft.Xna.Framework.Graphics.GraphicsDevice.currentVertexBuffers.
Referenced by Microsoft.Xna.Framework.Graphics.SavedDeviceState.SavedDeviceState(), and Terraria.DataStructures.SpriteDrawBuffer.Bind().