Terraria: Microsoft.Xna.Framework.Graphics.GraphicsDevice.CreateHelperClasses
CreateHelperClasses()
unsafe void Microsoft.Xna.Framework.Graphics.GraphicsDevice.CreateHelperClasses () inline private
Definition at line 740 of file GraphicsDevice.cs.
    {
        pImplicitDepthSurface = null;
        pSamplerState = new SamplerStateCollection(this, 0, _profileCapabilities.MaxSamplers);
        pVertexSamplerState = new SamplerStateCollection(this, 257, _profileCapabilities.MaxVertexSamplers);
        pTextureCollection = new TextureCollection(this, 0, _profileCapabilities.MaxSamplers);
        pVertexTextureCollection = new TextureCollection(this, 257, _profileCapabilities.MaxVertexSamplers);
        currentVertexBuffers = new VertexBufferBinding[_profileCapabilities.MaxVertexStreams];
        vertexDeclarationManager = new DeclarationManager(this);
        pResourceManager = new DeviceResourceManager(this);
        ProfileCapabilities profileCapabilities = _profileCapabilities;
        currentRenderTargets = new RenderTargetHelper[profileCapabilities.MaxRenderTargets];
        currentRenderTargetBindings = new RenderTargetBinding[profileCapabilities.MaxRenderTargets];
        willItBlend = true;
        fixed (IDirect3DSurface9** ptr = &pImplicitDepthSurface)
        {
            int num = *(int*)pComPtr + 160;
            ((delegate* unmanaged[Stdcall, Stdcall]<IntPtr, IDirect3DSurface9**, int>)(int)(*(uint*)num))((nint)pComPtr, ptr);
        }
    }
References Microsoft.Xna.Framework.Graphics.GraphicsDevice._profileCapabilities, Microsoft.Xna.Framework.Graphics.GraphicsDevice.currentRenderTargetBindings, Microsoft.Xna.Framework.Graphics.GraphicsDevice.currentRenderTargets, Microsoft.Xna.Framework.Graphics.GraphicsDevice.currentVertexBuffers, Microsoft.Xna.Framework.Graphics.ProfileCapabilities.MaxRenderTargets, Microsoft.Xna.Framework.Graphics.ProfileCapabilities.MaxSamplers, Microsoft.Xna.Framework.Graphics.ProfileCapabilities.MaxVertexSamplers, Microsoft.Xna.Framework.Graphics.ProfileCapabilities.MaxVertexStreams, Microsoft.Xna.Framework.Graphics.GraphicsDevice.pComPtr, Microsoft.Xna.Framework.Graphics.GraphicsDevice.pImplicitDepthSurface, Microsoft.Xna.Framework.Graphics.GraphicsDevice.pResourceManager, Microsoft.Xna.Framework.Graphics.GraphicsDevice.pSamplerState, Microsoft.Xna.Framework.Graphics.GraphicsDevice.pTextureCollection, Microsoft.Xna.Framework.Graphics.GraphicsDevice.pVertexSamplerState, Microsoft.Xna.Framework.Graphics.GraphicsDevice.pVertexTextureCollection, Microsoft.Xna.Framework.Graphics.GraphicsDevice.vertexDeclarationManager, and Microsoft.Xna.Framework.Graphics.GraphicsDevice.willItBlend.
Referenced by Microsoft.Xna.Framework.Graphics.GraphicsDevice.GraphicsDevice(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.GraphicsDevice(), and Microsoft.Xna.Framework.Graphics.GraphicsDevice.OnObjectCreation().