Terraria: Microsoft.Xna.Framework.Graphics.GraphicsDevice.Clear
Clear() [1/3]
unsafe void Microsoft.Xna.Framework.Graphics.GraphicsDevice.Clear (ClearOptions options, Color color, float depth, int stencil) inline
Definition at line 1717 of file GraphicsDevice.cs.
    {
        IntPtr intPtr = (IntPtr)pComPtr;
        Helpers.CheckDisposed(this, intPtr);
        uint num = 0u;
        IDirect3DDevice9* ptr = pComPtr;
        ((delegate* unmanaged[Stdcall, Stdcall]<IntPtr, _D3DRENDERSTATETYPE, uint*, int>)(int)(*(uint*)(*(int*)ptr + 232)))((nint)ptr, (_D3DRENDERSTATETYPE)174, &num);
        if (num != 0)
        {
            ptr = pComPtr;
            ((delegate* unmanaged[Stdcall, Stdcall]<IntPtr, _D3DRENDERSTATETYPE, uint, int>)(int)(*(uint*)(*(int*)ptr + 228)))((nint)ptr, (_D3DRENDERSTATETYPE)174, 0u);
        }
        int num2;
        int num3;
        if (currentRenderTargetCount > 0)
        {
            RenderTargetHelper renderTargetHelper = currentRenderTargets[0];
            num2 = renderTargetHelper.width;
            num3 = renderTargetHelper.height;
        }
        else
        {
            num2 = pInternalCachedParams.BackBufferWidth;
            num3 = pInternalCachedParams.BackBufferHeight;
        }
        bool flag = false;
        if (currentViewport.X != 0 || currentViewport.Y != 0 || currentViewport.Width != num2 || currentViewport.Height != num3)
        {
            System.Runtime.CompilerServices.Unsafe.SkipInit(out _D3DVIEWPORT9 d3DVIEWPORT);
            *(int*)(&d3DVIEWPORT) = 0;
            System.Runtime.CompilerServices.Unsafe.As<_D3DVIEWPORT9, int>(ref System.Runtime.CompilerServices.Unsafe.AddByteOffset(ref d3DVIEWPORT, 4)) = 0;
            System.Runtime.CompilerServices.Unsafe.As<_D3DVIEWPORT9, int>(ref System.Runtime.CompilerServices.Unsafe.AddByteOffset(ref d3DVIEWPORT, 8)) = num2;
            System.Runtime.CompilerServices.Unsafe.As<_D3DVIEWPORT9, int>(ref System.Runtime.CompilerServices.Unsafe.AddByteOffset(ref d3DVIEWPORT, 12)) = num3;
            System.Runtime.CompilerServices.Unsafe.As<_D3DVIEWPORT9, float>(ref System.Runtime.CompilerServices.Unsafe.AddByteOffset(ref d3DVIEWPORT, 16)) = 0f;
            System.Runtime.CompilerServices.Unsafe.As<_D3DVIEWPORT9, float>(ref System.Runtime.CompilerServices.Unsafe.AddByteOffset(ref d3DVIEWPORT, 20)) = 1f;
            ptr = pComPtr;
            ((delegate* unmanaged[Stdcall, Stdcall]<IntPtr, _D3DVIEWPORT9*, int>)(int)(*(uint*)(*(int*)ptr + 188)))((nint)ptr, &d3DVIEWPORT);
            flag = true;
        }
        uint num4 = (uint)(color.A << 8);
        uint num5 = (color.R | num4) << 8;
        uint num6 = (color.G | num5) << 8;
        uint num7 = color.B | num6;
        IDirect3DDevice9* ptr2 = pComPtr;
        int num8 = ((delegate* unmanaged[Stdcall, Stdcall]<IntPtr, uint, _D3DRECT*, uint, uint, float, uint, int>)(int)(*(uint*)(*(int*)ptr2 + 172)))((nint)ptr2, 0u, null, (uint)options, num7, depth, (uint)stencil);
        if (num != 0)
        {
            ptr2 = pComPtr;
            ((delegate* unmanaged[Stdcall, Stdcall]<IntPtr, _D3DRENDERSTATETYPE, uint, int>)(int)(*(uint*)(*(int*)ptr2 + 228)))((nint)ptr2, (_D3DRENDERSTATETYPE)174, num);
        }
        if (flag)
        {
            Viewport viewport = currentViewport;
            ptr2 = pComPtr;
            ((delegate* unmanaged[Stdcall, Stdcall]<IntPtr, _D3DVIEWPORT9*, int>)(int)(*(uint*)(*(int*)ptr2 + 188)))((nint)ptr2, (_D3DVIEWPORT9*)(int)(ref viewport));
        }
        if (num8 < 0)
        {
            ClearOptions clearOptions = options & (ClearOptions.DepthBuffer | ClearOptions.Stencil);
            if ((DefaultClearOptions & clearOptions) != clearOptions)
            {
                throw new InvalidOperationException(FrameworkResources.CannotClearNullDepth);
            }
            throw GraphicsHelpers.GetExceptionFromResult((uint)num8);
        }
        int num9 = 0;
        if (0 < currentRenderTargetCount)
        {
            do
            {
                currentRenderTargets[num9].pTexture.SetContentLost(isContentLost: false);
                num9++;
            }
            while (num9 < currentRenderTargetCount);
        }
        lazyClearFlags &= (int)(~options);
    }
References Microsoft.Xna.Framework.Color.A, Microsoft.Xna.Framework.Graphics.PresentationParameters.BackBufferHeight, Microsoft.Xna.Framework.Graphics.PresentationParameters.BackBufferWidth, Microsoft.Xna.Framework.FrameworkResources.CannotClearNullDepth, Microsoft.Xna.Framework.Helpers.CheckDisposed(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.currentRenderTargetCount, Microsoft.Xna.Framework.Graphics.GraphicsDevice.currentRenderTargets, Microsoft.Xna.Framework.Graphics.GraphicsDevice.currentViewport, Microsoft.Xna.Framework.Graphics.GraphicsDevice.DefaultClearOptions, Microsoft.Xna.Framework.Graphics.GraphicsHelpers.GetExceptionFromResult(), Microsoft.Xna.Framework.Graphics.RenderTargetHelper.height, Microsoft.Xna.Framework.Graphics.Viewport.Height, Microsoft.Xna.Framework.Graphics.GraphicsDevice.lazyClearFlags, System.options, Microsoft.Xna.Framework.Graphics.GraphicsDevice.pComPtr, Microsoft.Xna.Framework.Graphics.GraphicsDevice.pInternalCachedParams, Microsoft.Xna.Framework.Graphics.RenderTargetHelper.pTexture, Microsoft.Xna.Framework.Graphics.IDynamicGraphicsResource.SetContentLost(), Microsoft.Xna.Framework.Graphics.RenderTargetHelper.width, Microsoft.Xna.Framework.Graphics.Viewport.Width, Microsoft.Xna.Framework.Graphics.Viewport.X, and Microsoft.Xna.Framework.Graphics.Viewport.Y.