Terraria: Microsoft.Xna.Framework.Graphics.GraphicsDevice.DrawUserIndexedPrimitives< T >
DrawUserIndexedPrimitives< T >() [1/5]
unsafe void Microsoft.Xna.Framework.Graphics.GraphicsDevice.DrawUserIndexedPrimitives< T > (PrimitiveType primitiveType, T[] vertexData, int vertexOffset, int numVertices, Array indexData, int indexOffset, int primitiveCount, VertexDeclaration vertexDeclaration, _D3DFORMAT indexFormat) inline private
Type Constraints
T : struct
Definition at line 1578 of file GraphicsDevice.cs.
                                                                                                                                                                                                                                                                : struct
    {
        IntPtr intPtr = (IntPtr)pComPtr;
        Helpers.CheckDisposed(this, intPtr);
        if (vertexData != null && vertexData.Length != 0)
        {
            if (indexData != null && indexData.Length != 0)
            {
                if (vertexDeclaration == null)
                {
                    throw new ArgumentNullException("vertexDeclaration", FrameworkResources.NullNotAllowed);
                }
                if (numVertices <= 0)
                {
                    throw new ArgumentOutOfRangeException("numVertices", FrameworkResources.NumberVerticesMustBeGreaterZero);
                }
                if (primitiveCount <= 0)
                {
                    throw new ArgumentOutOfRangeException("primitiveCount", FrameworkResources.MustDrawSomething);
                }
                int maxPrimitiveCount = _profileCapabilities.MaxPrimitiveCount;
                if (primitiveCount > maxPrimitiveCount)
                {
                    _profileCapabilities.ThrowNotSupportedException(FrameworkResources.ProfileMaxPrimitiveCount, maxPrimitiveCount);
                }
                if (vertexOffset >= 0 && vertexOffset < (nint)vertexData.LongLength)
                {
                    if (indexOffset >= 0 && indexOffset < indexData.Length)
                    {
                        if ((uint)((int)GetElementCountFromPrimitiveType(primitiveType, primitiveCount) + indexOffset) > (uint)indexData.Length)
{
                            throw new ArgumentOutOfRangeException("primitiveCount", FrameworkResources.MustBeValidIndex);
                        }
                        if (vertexOffset + numVertices > (nint)vertexData.LongLength)
{
                            throw new ArgumentOutOfRangeException("vertexData", FrameworkResources.MustBeValidIndex);
                        }
                        BeginUserPrimitives(vertexDeclaration);
                        VerifyCanDraw(bUserPrimitives: true, bIndexedPrimitives: true);
                        GCHandle gCHandle = GCHandle.Alloc(indexData, GCHandleType.Pinned);
                        try
{
                            fixed (T* ptr2 = &vertexData[vertexOffset])
{
                                try
{
                                    void* ptr = Marshal.UnsafeAddrOfPinnedArrayElement(indexData, indexOffset).ToPointer();
                                    int num = *(int*)pComPtr + 336;
                                    int num2 = ((delegate* unmanaged[Stdcall, Stdcall]<IntPtr, _D3DPRIMITIVETYPE, uint, uint, uint, void*, _D3DFORMAT, void*, uint, int>)(int)(*(uint*)num))((nint)pComPtr, _003CModule_003E.ConvertXnaPrimitiveTypeToDx(primitiveType), 0u, (uint)numVertices, (uint)primitiveCount, ptr, indexFormat, ptr2, (uint)System.Runtime.CompilerServices.Unsafe.SizeOf<T>());
                                    if (num2 >= 0)
{
                                        return;
                                    }
                                    throw GraphicsHelpers.GetExceptionFromResult((uint)num2);
                                }
                                catch
{
                                    //try-fault
                                    ptr2 = null;
                                    throw;
                                }
                            }
                        }
                        finally
{
                            if (gCHandle.IsAllocated)
{
                                gCHandle.Free();
                            }
                            _currentIB = null;
                        }
                    }
                    throw new ArgumentOutOfRangeException("indexOffset", FrameworkResources.OffsetNotValid);
                }
                throw new ArgumentOutOfRangeException("vertexOffset", FrameworkResources.OffsetNotValid);
            }
            throw new ArgumentNullException("indexData", FrameworkResources.NullNotAllowed);
        }
        throw new ArgumentNullException("vertexData", FrameworkResources.NullNotAllowed);
    }
References Microsoft.Xna.Framework.Graphics.GraphicsDevice._currentIB, Microsoft.Xna.Framework.Graphics.GraphicsDevice._profileCapabilities, System.Runtime.InteropServices.GCHandle.Alloc(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.BeginUserPrimitives(), Microsoft.Xna.Framework.Helpers.CheckDisposed(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.GetElementCountFromPrimitiveType(), Microsoft.Xna.Framework.Graphics.GraphicsHelpers.GetExceptionFromResult(), Microsoft.Xna.Framework.Graphics.ProfileCapabilities.MaxPrimitiveCount, Microsoft.Xna.Framework.FrameworkResources.MustBeValidIndex, Microsoft.Xna.Framework.FrameworkResources.MustDrawSomething, Microsoft.Xna.Framework.FrameworkResources.NullNotAllowed, Microsoft.Xna.Framework.FrameworkResources.NumberVerticesMustBeGreaterZero, Microsoft.Xna.Framework.FrameworkResources.OffsetNotValid, Microsoft.Xna.Framework.Graphics.GraphicsDevice.pComPtr, Microsoft.Xna.Framework.FrameworkResources.ProfileMaxPrimitiveCount, Microsoft.Xna.Framework.Graphics.ProfileCapabilities.ThrowNotSupportedException(), System.Runtime.InteropServices.Marshal.UnsafeAddrOfPinnedArrayElement(), and Microsoft.Xna.Framework.Graphics.GraphicsDevice.VerifyCanDraw().