Terraria: Microsoft.Xna.Framework.Graphics.GraphicsDevice.SetVertexBuffers
SetVertexBuffers() [2/2]
unsafe void Microsoft.Xna.Framework.Graphics.GraphicsDevice.SetVertexBuffers (VertexBufferBinding * pBindings, int vertexBufferCount) inline package
Definition at line 2399 of file GraphicsDevice.cs.
    {
        IntPtr intPtr = (IntPtr)pComPtr;
        Helpers.CheckDisposed(this, intPtr);
        int maxVertexStreams = _profileCapabilities.MaxVertexStreams;
        if (vertexBufferCount > maxVertexStreams)
        {
            _profileCapabilities.ThrowNotSupportedException(FrameworkResources.ProfileMaxVertexStreams, maxVertexStreams);
        }
        int i = 0;
        try
        {
            for (i = 0; i < vertexBufferCount; i++)
            {
                VertexBuffer vertexBuffer = ((VertexBufferBinding*)(System.Runtime.CompilerServices.Unsafe.SizeOf<VertexBufferBinding>() * i + (byte*)pBindings))->_vertexBuffer;
                if (vertexBuffer == null)
                {
                    throw new ArgumentException(FrameworkResources.NullNotAllowed);
                }
                IntPtr intPtr2 = (IntPtr)vertexBuffer.pComPtr;
                IntPtr intPtr3 = intPtr2;
                Helpers.CheckDisposed(vertexBuffer, intPtr2);
                if (vertexBuffer.GraphicsDevice != this)
                {
                    throw new InvalidOperationException(FrameworkResources.InvalidDevice);
                }
                VertexBufferBinding[] array = currentVertexBuffers;
                VertexBuffer vertexBuffer2 = array[i]._vertexBuffer;
                VertexBufferBinding* ptr = (VertexBufferBinding*)((byte*)pBindings + System.Runtime.CompilerServices.Unsafe.SizeOf<VertexBufferBinding>() * i);
                int vertexOffset = ptr->_vertexOffset;
                int instanceFrequency = ptr->_instanceFrequency;
                if (vertexBuffer != vertexBuffer2 || vertexOffset != array[i]._vertexOffset || instanceFrequency != array[i]._instanceFrequency)
                {
                    int vertexStride = vertexBuffer._vertexDeclaration._vertexStride;
                    IDirect3DDevice9* ptr2 = pComPtr;
                    int num = ((delegate* unmanaged[Stdcall, Stdcall]<IntPtr, uint, IDirect3DVertexBuffer9*, uint, uint, int>)(int)(*(uint*)(*(int*)ptr2 + 400)))((nint)ptr2, (uint)i, vertexBuffer.pComPtr, (uint)(vertexStride * vertexOffset), (uint)vertexStride);
                    if (num < 0)
                    {
                        throw GraphicsHelpers.GetExceptionFromResult((uint)num);
                    }
                    ref VertexBufferBinding reference = ref currentVertexBuffers[i];
                    reference = System.Runtime.CompilerServices.Unsafe.Read<VertexBufferBinding>(System.Runtime.CompilerServices.Unsafe.SizeOf<VertexBufferBinding>() * i + (byte*)pBindings);
                    if (instanceFrequency != 0)
                    {
                        instanceStreamMask |= 1 << i;
                    }
                    else
                    {
                        instanceStreamMask &= ~(1 << i);
                    }
                }
            }
        }
        finally
        {
            int num2 = i;
            if (i < currentVertexBufferCount)
            {
                do
                {
                    IDirect3DDevice9* ptr2 = pComPtr;
                    ((delegate* unmanaged[Stdcall, Stdcall]<IntPtr, uint, IDirect3DVertexBuffer9*, uint, uint, int>)(int)(*(uint*)(*(int*)ptr2 + 400)))((nint)ptr2, (uint)num2, null, 0u, 0u);
                    currentVertexBuffers[num2] = default(VertexBufferBinding);
                    instanceStreamMask &= ~(1 << num2);
                    num2++;
                }
                while (num2 < currentVertexBufferCount);
            }
            currentVertexBufferCount = i;
        }
        if (vertexBufferCount > 0)
        {
            vertexDeclarationManager.SetVertexDeclaration(pBindings, vertexBufferCount);
        }
    }
References Microsoft.Xna.Framework.Graphics.VertexBufferBinding._instanceFrequency, Microsoft.Xna.Framework.Graphics.GraphicsDevice._profileCapabilities, Microsoft.Xna.Framework.Graphics.VertexBuffer._vertexDeclaration, Microsoft.Xna.Framework.Graphics.VertexBufferBinding._vertexOffset, Microsoft.Xna.Framework.Graphics.VertexDeclaration._vertexStride, System.array, Microsoft.Xna.Framework.Helpers.CheckDisposed(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.currentVertexBufferCount, Microsoft.Xna.Framework.Graphics.GraphicsDevice.currentVertexBuffers, Microsoft.Xna.Framework.Graphics.GraphicsHelpers.GetExceptionFromResult(), Microsoft.Xna.Framework.Graphics.GraphicsResource.GraphicsDevice, Microsoft.Xna.Framework.Graphics.GraphicsDevice.instanceStreamMask, Microsoft.Xna.Framework.FrameworkResources.InvalidDevice, Microsoft.Xna.Framework.Graphics.ProfileCapabilities.MaxVertexStreams, Microsoft.Xna.Framework.FrameworkResources.NullNotAllowed, Microsoft.Xna.Framework.Graphics.GraphicsDevice.pComPtr, Microsoft.Xna.Framework.Graphics.VertexBuffer.pComPtr, Microsoft.Xna.Framework.FrameworkResources.ProfileMaxVertexStreams, Microsoft.Xna.Framework.Graphics.DeclarationManager.SetVertexDeclaration(), Microsoft.Xna.Framework.Graphics.ProfileCapabilities.ThrowNotSupportedException(), and Microsoft.Xna.Framework.Graphics.GraphicsDevice.vertexDeclarationManager.
Referenced by Microsoft.Xna.Framework.Graphics.GraphicsDevice.Reset(), Microsoft.Xna.Framework.Graphics.SavedDeviceState.Restore(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.SetVertexBuffer(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.SetVertexBuffer(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.SetVertexBuffers(), and Terraria.DataStructures.SpriteDrawBuffer.Unbind().