Terraria: MS.Internal.Xml.Cache.XPathNodeInfoTable.ToString
ToString()
override string MS.Internal.Xml.Cache.XPathNodeInfoTable.ToString () inline
Definition at line 74 of file XPathNodeInfoTable.cs.
    {
        StringBuilder stringBuilder = new StringBuilder();
        for (int i = 0; i < _hashTable.Length; i++)
        {
            StringBuilder stringBuilder2 = stringBuilder;
            StringBuilder.AppendInterpolatedStringHandler handler = new StringBuilder.AppendInterpolatedStringHandler(2, 1, stringBuilder2);
            handler.AppendFormatted(i, 4);
            handler.AppendLiteral(": ");
            stringBuilder2.Append(ref handler);
            for (XPathNodeInfoAtom xPathNodeInfoAtom = _hashTable[i]; xPathNodeInfoAtom != null; xPathNodeInfoAtom = xPathNodeInfoAtom.Next)
            {
                if (xPathNodeInfoAtom != _hashTable[i])
                {
                    stringBuilder.Append("\n      ");
                }
                stringBuilder.Append(xPathNodeInfoAtom);
            }
            stringBuilder.Append('\n');
        }
        return stringBuilder.ToString();
    }
References MS.Internal.Xml.Cache.XPathNodeInfoTable._hashTable, System.Text.StringBuilder.Append(), System.Text.StringBuilder.AppendInterpolatedStringHandler.AppendFormatted(), System.Text.StringBuilder.AppendInterpolatedStringHandler.AppendLiteral(), MS.Internal.Xml.Cache.XPathNodeInfoAtom.Next, and System.Text.StringBuilder.ToString().