Terraria: System.Net.Http.Headers.ByteArrayHeaderParser.TryParseValue
TryParseValue()
override bool System.Net.Http.Headers.ByteArrayHeaderParser.TryParseValue ([NotNullWhen(true)] string value, object storeValue, ref int index, [NotNullWhen(true)] out object parsedValue) inline
Definition at line 19 of file ByteArrayHeaderParser.cs.
    {
        parsedValue = null;
        if (string.IsNullOrEmpty(value) || index == value.Length)
        {
            return false;
        }
        string text = value;
        if (index > 0)
        {
            text = value.Substring(index);
        }
        try
        {
            parsedValue = Convert.FromBase64String(text);
            index = value.Length;
            return true;
        }
        catch (FormatException ex)
        {
            if (System.Net.NetEventSource.Log.IsEnabled())
            {
                System.Net.NetEventSource.Error(this, System.SR.Format(System.SR.net_http_parser_invalid_base64_string, text, ex.Message), "TryParseValue");
            }
        }
        return false;
    }
References System.Net.NetEventSource.Error(), System.SR.Format(), System.Convert.FromBase64String(), System.index, System.Net.NetEventSource.Log, System.Exception.Message, System.SR.net_http_parser_invalid_base64_string, System.text, and System.value.