Terraria: MS.Internal.Xml.Cache.XPathNodeInfoTable.Create
Create()
XPathNodeInfoAtom MS.Internal.Xml.Cache.XPathNodeInfoTable.Create (string localName, string namespaceUri, string prefix, string baseUri, XPathNode[] pageParent, XPathNode[] pageSibling, XPathNode[] pageSimilar, XPathDocument doc, int lineNumBase, int linePosBase) inline
Definition at line 20 of file XPathNodeInfoTable.cs.
    {
        XPathNodeInfoAtom xPathNodeInfoAtom;
        if (_infoCached == null)
        {
            xPathNodeInfoAtom = new XPathNodeInfoAtom(localName, namespaceUri, prefix, baseUri, pageParent, pageSibling, pageSimilar, doc, lineNumBase, linePosBase);
        }
        else
        {
            xPathNodeInfoAtom = _infoCached;
            _infoCached = xPathNodeInfoAtom.Next;
            xPathNodeInfoAtom.Init(localName, namespaceUri, prefix, baseUri, pageParent, pageSibling, pageSimilar, doc, lineNumBase, linePosBase);
        }
        return Atomize(xPathNodeInfoAtom);
    }
References MS.Internal.Xml.Cache.XPathNodeInfoTable._infoCached, MS.Internal.Xml.Cache.XPathNodeInfoTable.Atomize(), MS.Internal.Xml.Cache.XPathNodeInfoAtom.Init(), and MS.Internal.Xml.Cache.XPathNodeInfoAtom.Next.
Referenced by MS.Internal.Xml.Cache.XPathDocumentBuilder.NewNamespaceNode(), MS.Internal.Xml.Cache.XPathDocumentBuilder.NewNode(), MS.Internal.Xml.Cache.XPathNode.SetSibling(), and MS.Internal.Xml.Cache.XPathNode.SetSimilarElement().