Terraria: ModShapes.OuterOutline.Perform
Perform()
override bool ModShapes.OuterOutline.Perform (Point origin, GenAction action) inline virtual
Implements GenShape.
         {
             int num = (_useDiagonals ? 16 : 8);
             foreach (Point16 datum in _data.GetData())
             {
                 if (_useInterior && !UnitApply(action, origin, datum.X + origin.X, datum.Y + origin.Y) && _quitOnFail)
                 {
                     return false;
                 }
                 for (int i = 0; i < num; i += 2)
                 {
                     if (!_data.Contains(datum.X + POINT_OFFSETS[i], datum.Y + POINT_OFFSETS[i + 1]) && !UnitApply(action, origin, origin.X + datum.X + POINT_OFFSETS[i], origin.Y + datum.Y + POINT_OFFSETS[i + 1]) && _quitOnFail)
                     {
                         return false;
                     }
                 }
             }
             return true;
         }
References GenModShape._data, GenShape._quitOnFail, ModShapes.OuterOutline._useDiagonals, ModShapes.OuterOutline._useInterior, ShapeData.Contains(), ShapeData.GetData(), ModShapes.OuterOutline.POINT_OFFSETS, GenShape.UnitApply(), Point16.X, and Point16.Y.