Terraria: System.Linq.Lookup.GetGrouping
GetGrouping()
Grouping< TKey, TElement > System.Linq.Lookup< TKey, TElement >.GetGrouping (TKey key, bool create) inline package
Definition at line 193 of file Lookup.cs.
    {
        int num = InternalGetHashCode(key);
        for (Grouping<TKey, TElement> grouping = _groupings[num % _groupings.Length]; grouping != null; grouping = grouping._hashNext)
        {
            if (grouping._hashCode == num && _comparer.Equals(grouping._key, key))
            {
                return grouping;
            }
        }
        if (create)
        {
            if (_count == _groupings.Length)
            {
                Resize();
            }
            int num2 = num % _groupings.Length;
            Grouping<TKey, TElement> grouping2 = new Grouping<TKey, TElement>(key, num);
            grouping2._hashNext = _groupings[num2];
            _groupings[num2] = grouping2;
            if (_lastGrouping == null)
            {
                grouping2._next = grouping2;
            }
            else
            {
                grouping2._next = _lastGrouping._next;
                _lastGrouping._next = grouping2;
            }
            _lastGrouping = grouping2;
            _count++;
            return grouping2;
        }
        return null;
    }
References System.Linq.Lookup< TKey, TElement >._comparer, System.Linq.Lookup< TKey, TElement >._count, System.Linq.Lookup< TKey, TElement >._groupings, System.Linq.Lookup< TKey, TElement >._lastGrouping, System.Collections.IEqualityComparer.Equals(), System.Linq.Lookup< TKey, TElement >.InternalGetHashCode(), System.key, and System.Linq.Lookup< TKey, TElement >.Resize().
Referenced by System.Linq.Lookup< TKey, TElement >.Contains().