Terraria: System.Security.Claims.Claim.Claim
Claim() [2/10]
System.Security.Claims.Claim.Claim (BinaryReader reader, ClaimsIdentity? subject) inline
Definition at line 68 of file Claim.cs.
    {
        if (reader == null)
        {
            throw new ArgumentNullException("reader");
        }
        _subject = subject;
        SerializationMask serializationMask = (SerializationMask)reader.ReadInt32();
        int num = 1;
        int num2 = reader.ReadInt32();
        _value = reader.ReadString();
        if ((serializationMask & SerializationMask.NameClaimType) == SerializationMask.NameClaimType)
        {
            _type = "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name";
        }
        else if ((serializationMask & SerializationMask.RoleClaimType) == SerializationMask.RoleClaimType)
        {
            _type = "http://schemas.microsoft.com/ws/2008/06/identity/claims/role";
        }
        else
        {
            _type = reader.ReadString();
            num++;
        }
        if ((serializationMask & SerializationMask.StringType) == SerializationMask.StringType)
        {
            _valueType = reader.ReadString();
            num++;
        }
        else
        {
            _valueType = "http://www.w3.org/2001/XMLSchema#string";
        }
        if ((serializationMask & SerializationMask.Issuer) == SerializationMask.Issuer)
        {
            _issuer = reader.ReadString();
            num++;
        }
        else
        {
            _issuer = "LOCAL AUTHORITY";
        }
        if ((serializationMask & SerializationMask.OriginalIssuerEqualsIssuer) == SerializationMask.OriginalIssuerEqualsIssuer)
        {
            _originalIssuer = _issuer;
        }
        else if ((serializationMask & SerializationMask.OriginalIssuer) == SerializationMask.OriginalIssuer)
        {
            _originalIssuer = reader.ReadString();
            num++;
        }
        else
        {
            _originalIssuer = "LOCAL AUTHORITY";
        }
        if ((serializationMask & SerializationMask.HasProperties) == SerializationMask.HasProperties)
        {
            int num3 = reader.ReadInt32();
            num++;
            for (int i = 0; i < num3; i++)
            {
                Properties.Add(reader.ReadString(), reader.ReadString());
            }
        }
        if ((serializationMask & SerializationMask.UserData) == SerializationMask.UserData)
        {
            int count = reader.ReadInt32();
            _userSerializationData = reader.ReadBytes(count);
            num++;
        }
        for (int j = num; j < num2; j++)
        {
            reader.ReadString();
        }
    }
References System.Security.Claims.Claim._issuer, System.Security.Claims.Claim._originalIssuer, System.Security.Claims.Claim._subject, System.Security.Claims.Claim._type, System.Security.Claims.Claim._userSerializationData, System.Security.Claims.Claim._value, System.Security.Claims.Claim._valueType, System.Collections.IDictionary.Add(), System.count, System.Security.Claims.Claim.Properties, System.IO.BinaryReader.ReadBytes(), System.IO.BinaryReader.ReadInt32(), and System.IO.BinaryReader.ReadString().