Terraria: Internal.Cryptography.Pal.CertificatePal.GetPrivateKeyCsp
GetPrivateKeyCsp()
unsafe CspParameters Internal.Cryptography.Pal.CertificatePal.GetPrivateKeyCsp () inline private
Definition at line 830 of file CertificatePal.cs.
    {
        int pcbData = 0;
        if (!global::Interop.crypt32.CertGetCertificateContextProperty(_certContext, CertContextPropId.CERT_KEY_PROV_INFO_PROP_ID, null, ref pcbData))
        {
            int lastWin32Error = Marshal.GetLastWin32Error();
            if (lastWin32Error == -2146885628)
            {
                return null;
            }
            throw lastWin32Error.ToCryptographicException();
        }
        byte[] array = new byte[pcbData];
        fixed (byte* ptr = array)
        {
            if (!global::Interop.crypt32.CertGetCertificateContextProperty(_certContext, CertContextPropId.CERT_KEY_PROV_INFO_PROP_ID, array, ref pcbData))
            {
                throw Marshal.GetLastWin32Error().ToCryptographicException();
            }
            CRYPT_KEY_PROV_INFO* ptr2 = (CRYPT_KEY_PROV_INFO*)ptr;
            CspParameters cspParameters = new CspParameters();
            cspParameters.ProviderName = Marshal.PtrToStringUni((IntPtr)ptr2->pwszProvName);
            cspParameters.KeyContainerName = Marshal.PtrToStringUni((IntPtr)ptr2->pwszContainerName);
            cspParameters.ProviderType = ptr2->dwProvType;
            cspParameters.KeyNumber = ptr2->dwKeySpec;
            cspParameters.Flags = (((ptr2->dwFlags & CryptAcquireContextFlags.CRYPT_MACHINE_KEYSET) == CryptAcquireContextFlags.CRYPT_MACHINE_KEYSET) ? CspProviderFlags.UseMachineKeyStore : CspProviderFlags.NoFlags);
            return cspParameters;
        }
    }
References Internal.Cryptography.Pal.CertificatePal._certContext, System.array, System.Runtime.InteropServices.Marshal.GetLastWin32Error(), and System.Runtime.InteropServices.Marshal.PtrToStringUni().
Referenced by Internal.Cryptography.Pal.CertificatePal.AppendPrivateKeyInfo(), and Internal.Cryptography.Pal.CertificatePal.GetPrivateKey< T >().