Terraria: Internal.Cryptography.Pal.CertificatePal.CopyWithPersistedCngKey
CopyWithPersistedCngKey()
unsafe ICertificatePal Internal.Cryptography.Pal.CertificatePal.CopyWithPersistedCngKey (CngKey cngKey) inline private
Definition at line 860 of file CertificatePal.cs.
    {
        //The blocks IL_0090, IL_00a9, IL_00ac, IL_00ae, IL_00ce are reachable both inside and outside the pinned region starting at IL_008b. ILSpy has duplicated these blocks in order to place them both within and outside the `fixed` statement.
        if (string.IsNullOrEmpty(cngKey.KeyName))
        {
            return null;
        }
        CertificatePal certificatePal = (CertificatePal)FromBlob(RawData, SafePasswordHandle.InvalidHandle, X509KeyStorageFlags.PersistKeySet);
        CngProvider provider = cngKey.Provider;
        string keyName = cngKey.KeyName;
        bool isMachineKey = cngKey.IsMachineKey;
        int dwKeySpec = GuessKeySpec(provider, keyName, isMachineKey, cngKey.AlgorithmGroup);
        CRYPT_KEY_PROV_INFO cRYPT_KEY_PROV_INFO = default(CRYPT_KEY_PROV_INFO);
        fixed (char* pwszContainerName = cngKey.KeyName)
        {
            string provider2 = cngKey.Provider.Provider;
            char* intPtr;
            ref CRYPT_KEY_PROV_INFO reference;
            int dwFlags;
            if (provider2 == null)
            {
                char* pwszProvName;
                intPtr = (pwszProvName = null);
                cRYPT_KEY_PROV_INFO.pwszContainerName = pwszContainerName;
                cRYPT_KEY_PROV_INFO.pwszProvName = pwszProvName;
                reference = ref cRYPT_KEY_PROV_INFO;
                dwFlags = (isMachineKey ? 32 : 0);
                reference.dwFlags = (CryptAcquireContextFlags)dwFlags;
                cRYPT_KEY_PROV_INFO.dwKeySpec = dwKeySpec;
                if (!global::Interop.crypt32.CertSetCertificateContextProperty(certificatePal._certContext, CertContextPropId.CERT_KEY_PROV_INFO_PROP_ID, CertSetPropertyFlags.None, &cRYPT_KEY_PROV_INFO))
                {
                    certificatePal.Dispose();
                    throw Marshal.GetLastWin32Error().ToCryptographicException();
                }
            }
            else
            {
                fixed (char* ptr = &provider2.GetPinnableReference())
                {
                    char* pwszProvName;
                    intPtr = (pwszProvName = ptr);
                    cRYPT_KEY_PROV_INFO.pwszContainerName = pwszContainerName;
                    cRYPT_KEY_PROV_INFO.pwszProvName = pwszProvName;
                    reference = ref cRYPT_KEY_PROV_INFO;
                    dwFlags = (int)(reference.dwFlags = (isMachineKey ? CryptAcquireContextFlags.CRYPT_MACHINE_KEYSET : CryptAcquireContextFlags.None));
                    cRYPT_KEY_PROV_INFO.dwKeySpec = dwKeySpec;
                    if (!global::Interop.crypt32.CertSetCertificateContextProperty(certificatePal._certContext, CertContextPropId.CERT_KEY_PROV_INFO_PROP_ID, CertSetPropertyFlags.None, &cRYPT_KEY_PROV_INFO))
                    {
                        certificatePal.Dispose();
                        throw Marshal.GetLastWin32Error().ToCryptographicException();
                    }
                }
            }
        }
        return certificatePal;
    }
References Internal.Cryptography.Pal.CertificatePal.CertificatePal(), Internal.Cryptography.Pal.CertificatePal.FromBlob(), System.Runtime.InteropServices.Marshal.GetLastWin32Error(), Internal.Cryptography.Pal.CertificatePal.GuessKeySpec(), Microsoft.Win32.SafeHandles.SafePasswordHandle.InvalidHandle, and Internal.Cryptography.Pal.CertificatePal.RawData.
Referenced by Internal.Cryptography.Pal.CertificatePal.CopyWithPrivateKey(), Internal.Cryptography.Pal.CertificatePal.CopyWithPrivateKey(), Internal.Cryptography.Pal.CertificatePal.CopyWithPrivateKey(), and Internal.Cryptography.Pal.CertificatePal.CopyWithPrivateKey().