Terraria: Internal.Cryptography.Pal.CertificatePal.CopyWithPrivateKey
CopyWithPrivateKey() [4/4]
ICertificatePal Internal.Cryptography.Pal.CertificatePal.CopyWithPrivateKey (RSA rsa) inline
Implements Internal.Cryptography.ICertificatePal.
Definition at line 719 of file CertificatePal.cs.
    {
        RSACng rSACng = rsa as RSACng;
        ICertificatePal certificatePal = null;
        if (rSACng != null)
        {
            certificatePal = CopyWithPersistedCngKey(rSACng.Key);
            if (certificatePal != null)
            {
                return certificatePal;
            }
        }
        if (rsa is RSACryptoServiceProvider rSACryptoServiceProvider)
        {
            certificatePal = CopyWithPersistedCapiKey(rSACryptoServiceProvider.CspKeyContainerInfo);
            if (certificatePal != null)
            {
                return certificatePal;
            }
        }
        RSAParameters parameters = rsa.ExportParameters(includePrivateParameters: true);
        using (PinAndClear.Track(parameters.D))
        {
            using (PinAndClear.Track(parameters.P))
            {
                using (PinAndClear.Track(parameters.Q))
                {
                    using (PinAndClear.Track(parameters.DP))
                    {
                        using (PinAndClear.Track(parameters.DQ))
{
                            using (PinAndClear.Track(parameters.InverseQ))
{
                                using RSACng rSACng2 = new RSACng();
                                rSACng2.ImportParameters(parameters);
                                return CopyWithEphemeralKey(rSACng2.Key);
                            }
                        }
                    }
                }
            }
        }
    }
References Internal.Cryptography.Pal.CertificatePal.CopyWithEphemeralKey(), Internal.Cryptography.Pal.CertificatePal.CopyWithPersistedCapiKey(), Internal.Cryptography.Pal.CertificatePal.CopyWithPersistedCngKey(), System.Security.Cryptography.RSAParameters.D, System.Security.Cryptography.RSAParameters.DP, System.Security.Cryptography.RSAParameters.DQ, System.Security.Cryptography.RSAParameters.InverseQ, System.Security.Cryptography.RSAParameters.P, System.Security.Cryptography.RSAParameters.Q, and Internal.Cryptography.PinAndClear.Track().