Terraria: Internal.Cryptography.Pal.CertificatePal.FilterPFXStore
FilterPFXStore()
static unsafe SafeCertContextHandle Internal.Cryptography.Pal.CertificatePal.FilterPFXStore (ReadOnlySpan< byte > rawData, SafePasswordHandle password, PfxCertStoreFlags pfxCertStoreFlags) inline static private
Definition at line 546 of file CertificatePal.cs.
    {
        SafeCertStoreHandle safeCertStoreHandle;
        fixed (byte* pbData = rawData)
        {
            CRYPTOAPI_BLOB pPFX = new CRYPTOAPI_BLOB(rawData.Length, pbData);
            safeCertStoreHandle = global::Interop.crypt32.PFXImportCertStore(ref pPFX, password, pfxCertStoreFlags);
            if (safeCertStoreHandle.IsInvalid)
            {
                throw Marshal.GetHRForLastWin32Error().ToCryptographicException();
            }
        }
        try
        {
            SafeCertContextHandle safeCertContextHandle = SafePointerHandle<SafeCertContextHandle>.InvalidHandle;
            SafeCertContextHandle pCertContext = null;
            while (global::Interop.crypt32.CertEnumCertificatesInStore(safeCertStoreHandle, ref pCertContext))
            {
                if (pCertContext.ContainsPrivateKey)
                {
                    if (!safeCertContextHandle.IsInvalid && safeCertContextHandle.ContainsPrivateKey)
                    {
                        if (pCertContext.HasPersistedPrivateKey)
{
                            SafeCertContextHandleWithKeyContainerDeletion.DeleteKeyContainer(pCertContext);
                        }
                    }
                    else
                    {
                        safeCertContextHandle.Dispose();
                        safeCertContextHandle = pCertContext.Duplicate();
                    }
                }
                else if (safeCertContextHandle.IsInvalid)
                {
                    safeCertContextHandle = pCertContext.Duplicate();
                }
            }
            if (safeCertContextHandle.IsInvalid)
            {
                throw new CryptographicException(System.SR.Cryptography_Pfx_NoCertificates);
            }
            return safeCertContextHandle;
        }
        finally
        {
            safeCertStoreHandle.Dispose();
        }
    }
References Internal.Cryptography.Pal.Native.SafeCertContextHandle.ContainsPrivateKey, System.SR.Cryptography_Pfx_NoCertificates, Internal.Cryptography.Pal.Native.SafeCertContextHandleWithKeyContainerDeletion.DeleteKeyContainer(), Internal.Cryptography.Pal.Native.SafeCertContextHandle.Duplicate(), System.Runtime.InteropServices.Marshal.GetHRForLastWin32Error(), and Internal.Cryptography.Pal.Native.SafeCertContextHandle.HasPersistedPrivateKey.
Referenced by Internal.Cryptography.Pal.CertificatePal.FromBlobOrFile().