Terraria: Internal.Cryptography.Pal.CertificatePal.FromBlobOrFile
FromBlobOrFile()
static unsafe ICertificatePal Internal.Cryptography.Pal.CertificatePal.FromBlobOrFile (ReadOnlySpan< byte > rawData, string fileName, SafePasswordHandle password, X509KeyStorageFlags keyStorageFlags) inline static private
Definition at line 457 of file CertificatePal.cs.
    {
        bool flag = fileName != null;
        PfxCertStoreFlags pfxCertStoreFlags = MapKeyStorageFlags(keyStorageFlags);
        bool deleteKeyContainer = false;
        SafeCertStoreHandle phCertStore = null;
        SafeCryptMsgHandle phMsg = null;
        SafeCertContextHandle ppvContext = null;
        try
        {
            ContentType pdwContentType;
            fixed (byte* pbData = rawData)
            {
                fixed (char* ptr = fileName)
                {
                    CRYPTOAPI_BLOB cRYPTOAPI_BLOB = new CRYPTOAPI_BLOB((!flag) ? rawData.Length : 0, pbData);
                    CertQueryObjectType dwObjectType = (flag ? CertQueryObjectType.CERT_QUERY_OBJECT_FILE : CertQueryObjectType.CERT_QUERY_OBJECT_BLOB);
                    void* pvObject = (flag ? ((void*)ptr) : ((void*)(&cRYPTOAPI_BLOB)));
                    if (!global::Interop.crypt32.CryptQueryObject(dwObjectType, pvObject, ExpectedContentTypeFlags.CERT_QUERY_CONTENT_FLAG_CERT | ExpectedContentTypeFlags.CERT_QUERY_CONTENT_FLAG_SERIALIZED_CERT | ExpectedContentTypeFlags.CERT_QUERY_CONTENT_FLAG_PKCS7_SIGNED | ExpectedContentTypeFlags.CERT_QUERY_CONTENT_FLAG_PKCS7_SIGNED_EMBED | ExpectedContentTypeFlags.CERT_QUERY_CONTENT_FLAG_PFX, ExpectedFormatTypeFlags.CERT_QUERY_FORMAT_FLAG_ALL, 0, out var _, out pdwContentType, out var _, out phCertStore, out phMsg, out ppvContext))
                    {
                        int hRForLastWin32Error = Marshal.GetHRForLastWin32Error();
                        throw hRForLastWin32Error.ToCryptographicException();
                    }
                }
            }
            switch (pdwContentType)
            {
            case ContentType.CERT_QUERY_CONTENT_PKCS7_SIGNED:
            case ContentType.CERT_QUERY_CONTENT_PKCS7_SIGNED_EMBED:
                ppvContext = GetSignerInPKCS7Store(phCertStore, phMsg);
                break;
            case ContentType.CERT_QUERY_CONTENT_PFX:
                if (flag)
                {
                    rawData = File.ReadAllBytes(fileName);
                }
                ppvContext = FilterPFXStore(rawData, password, pfxCertStoreFlags);
                deleteKeyContainer = (keyStorageFlags & (X509KeyStorageFlags.PersistKeySet | X509KeyStorageFlags.EphemeralKeySet)) == 0;
                break;
            }
            CertificatePal result = new CertificatePal(ppvContext, deleteKeyContainer);
            ppvContext = null;
            return result;
        }
        finally
        {
            phCertStore?.Dispose();
            phMsg?.Dispose();
            ppvContext?.Dispose();
        }
    }
References Internal.Cryptography.Pal.CertificatePal.CertificatePal(), Internal.Cryptography.Pal.CertificatePal.FilterPFXStore(), System.Runtime.InteropServices.Marshal.GetHRForLastWin32Error(), Internal.Cryptography.Pal.CertificatePal.GetSignerInPKCS7Store(), Internal.Cryptography.Pal.CertificatePal.MapKeyStorageFlags(), and System.IO.File.ReadAllBytes().
Referenced by Internal.Cryptography.Pal.CertificatePal.FromBlob(), and Internal.Cryptography.Pal.CertificatePal.FromFile().