Terraria: Internal.Cryptography.Pal.CertificatePal.CertificatePal
CertificatePal() [1/2]
Internal.Cryptography.Pal.CertificatePal.CertificatePal (CertificatePal copyFrom) inline private
Definition at line 425 of file CertificatePal.cs.
    {
        _certContext = new SafeCertContextHandle(copyFrom._certContext);
    }
References Internal.Cryptography.Pal.CertificatePal._certContext.
Referenced by Internal.Cryptography.Pal.CertificatePal.CopyWithEphemeralKey(), Internal.Cryptography.Pal.CertificatePal.CopyWithPersistedCapiKey(), Internal.Cryptography.Pal.CertificatePal.CopyWithPersistedCngKey(), Internal.Cryptography.Pal.CertificatePal.FromBlobOrFile(), Internal.Cryptography.Pal.CertificatePal.FromHandle(), and Internal.Cryptography.Pal.CertificatePal.FromOtherCert().