Terraria: Internal.Cryptography.Pal.CertificatePal.FromBlob
FromBlob()
static ICertificatePal Internal.Cryptography.Pal.CertificatePal.FromBlob (ReadOnlySpan< byte > rawData, SafePasswordHandle password, X509KeyStorageFlags keyStorageFlags) inline static
Definition at line 447 of file CertificatePal.cs.
    {
        return FromBlobOrFile(rawData, null, password, keyStorageFlags);
    }
References Internal.Cryptography.Pal.CertificatePal.FromBlobOrFile().
Referenced by System.Security.Cryptography.X509Certificates.X509Certificate.X509Certificate(), System.Security.Cryptography.X509Certificates.X509Certificate.X509Certificate(), System.Security.Cryptography.X509Certificates.X509Certificate.X509Certificate(), System.Security.Cryptography.X509Certificates.X509Certificate.X509Certificate(), Internal.Cryptography.Pal.CertificatePal.CopyWithEphemeralKey(), Internal.Cryptography.Pal.CertificatePal.CopyWithPersistedCapiKey(), and Internal.Cryptography.Pal.CertificatePal.CopyWithPersistedCngKey().