Terraria: Internal.Cryptography.Pal.CertificatePal.CopyWithPrivateKey
CopyWithPrivateKey() [1/4]
ICertificatePal Internal.Cryptography.Pal.CertificatePal.CopyWithPrivateKey (DSA dsa) inline
Implements Internal.Cryptography.ICertificatePal.
Definition at line 652 of file CertificatePal.cs.
    {
        DSACng dSACng = dsa as DSACng;
        ICertificatePal certificatePal = null;
        if (dSACng != null)
        {
            certificatePal = CopyWithPersistedCngKey(dSACng.Key);
            if (certificatePal != null)
            {
                return certificatePal;
            }
        }
        if (dsa is DSACryptoServiceProvider dSACryptoServiceProvider)
        {
            certificatePal = CopyWithPersistedCapiKey(dSACryptoServiceProvider.CspKeyContainerInfo);
            if (certificatePal != null)
            {
                return certificatePal;
            }
        }
        DSAParameters parameters = dsa.ExportParameters(includePrivateParameters: true);
        using (PinAndClear.Track(parameters.X))
        {
            using DSACng dSACng2 = new DSACng();
            dSACng2.ImportParameters(parameters);
            return CopyWithEphemeralKey(dSACng2.Key);
        }
    }
References Internal.Cryptography.Pal.CertificatePal.CopyWithEphemeralKey(), Internal.Cryptography.Pal.CertificatePal.CopyWithPersistedCapiKey(), Internal.Cryptography.Pal.CertificatePal.CopyWithPersistedCngKey(), Internal.Cryptography.PinAndClear.Track(), and System.Security.Cryptography.DSAParameters.X.