Terraria: Internal.Cryptography.Pal.CertificatePal.GuessKeySpec
GuessKeySpec()
static int Internal.Cryptography.Pal.CertificatePal.GuessKeySpec (CngProvider provider, string keyName, bool machineKey, CngAlgorithmGroup algorithmGroup) inline static private
Definition at line 917 of file CertificatePal.cs.
    {
        if (provider == CngProvider.MicrosoftSoftwareKeyStorageProvider || provider == CngProvider.MicrosoftSmartCardKeyStorageProvider)
        {
            return 0;
        }
        try
        {
            CngKeyOpenOptions openOptions = (machineKey ? CngKeyOpenOptions.MachineKey : CngKeyOpenOptions.None);
            using (CngKey.Open(keyName, provider, openOptions))
            {
                return 0;
            }
        }
        catch (CryptographicException)
        {
            CspParameters cspParameters = new CspParameters
            {
                ProviderName = provider.Provider,
                KeyContainerName = keyName,
                Flags = CspProviderFlags.UseExistingKey,
                KeyNumber = 2
            };
            if (machineKey)
            {
                cspParameters.Flags |= CspProviderFlags.UseMachineKeyStore;
            }
            if (TryGuessKeySpec(cspParameters, algorithmGroup, out var keySpec))
            {
                return keySpec;
            }
            throw;
        }
    }
References System.Security.Cryptography.CngProvider.MicrosoftSmartCardKeyStorageProvider, System.Security.Cryptography.CngProvider.MicrosoftSoftwareKeyStorageProvider, System.Security.Cryptography.CngKey.Open(), and Internal.Cryptography.Pal.CertificatePal.TryGuessKeySpec().
Referenced by Internal.Cryptography.Pal.CertificatePal.CopyWithPersistedCngKey().