Terraria: Internal.Cryptography.Pal.CertificatePal.GetPrivateKey< T >
GetPrivateKey< T >()
T Internal.Cryptography.Pal.CertificatePal.GetPrivateKey< T > (Func< CspParameters, T > createCsp, Func< CngKey, T > createCng) inline private
Type Constraints
T : AsymmetricAlgorithm
Definition at line 763 of file CertificatePal.cs.
                                                                                                    : AsymmetricAlgorithm
    {
        CngKeyHandleOpenOptions handleOptions;
        SafeNCryptKeyHandle safeNCryptKeyHandle = TryAcquireCngPrivateKey(CertContext, out handleOptions);
        if (safeNCryptKeyHandle != null)
        {
            CngKey arg = CngKey.Open(safeNCryptKeyHandle, handleOptions);
            return createCng(arg);
        }
        CspParameters privateKeyCsp = GetPrivateKeyCsp();
        if (privateKeyCsp == null)
        {
            return null;
        }
        if (privateKeyCsp.ProviderType == 0)
        {
            string providerName = privateKeyCsp.ProviderName;
            string keyContainerName = privateKeyCsp.KeyContainerName;
            CngKey arg2 = CngKey.Open(keyContainerName, new CngProvider(providerName));
            return createCng(arg2);
        }
        privateKeyCsp.Flags |= CspProviderFlags.UseExistingKey;
        return createCsp(privateKeyCsp);
    }
References Internal.Cryptography.Pal.CertificatePal.CertContext, Internal.Cryptography.Pal.CertificatePal.GetPrivateKeyCsp(), System.Security.Cryptography.CngKey.Open(), and Internal.Cryptography.Pal.CertificatePal.TryAcquireCngPrivateKey().