Terraria: Internal.Cryptography.Pal.CertificatePal.TryGuessKeySpec
TryGuessKeySpec()
static bool Internal.Cryptography.Pal.CertificatePal.TryGuessKeySpec (CspParameters cspParameters, CngAlgorithmGroup algorithmGroup, out int keySpec) inline static private
Definition at line 952 of file CertificatePal.cs.
    {
        if (algorithmGroup == CngAlgorithmGroup.Rsa)
        {
            return TryGuessRsaKeySpec(cspParameters, out keySpec);
        }
        if (algorithmGroup == CngAlgorithmGroup.Dsa)
        {
            return TryGuessDsaKeySpec(cspParameters, out keySpec);
        }
        keySpec = 0;
        return false;
    }
References System.Security.Cryptography.CngAlgorithmGroup.Dsa, System.Security.Cryptography.CngAlgorithmGroup.Rsa, Internal.Cryptography.Pal.CertificatePal.TryGuessDsaKeySpec(), and Internal.Cryptography.Pal.CertificatePal.TryGuessRsaKeySpec().
Referenced by Internal.Cryptography.Pal.CertificatePal.GuessKeySpec().