Terraria: System.Linq.Parallel.DefaultIfEmptyQueryOperator.DefaultIfEmptyQueryOperatorEnumerator.MoveNext
MoveNext() [2/2]
override bool System.Linq.Parallel.DefaultIfEmptyQueryOperator< TSource >.DefaultIfEmptyQueryOperatorEnumerator< TKey >.MoveNext ([AllowNull] ref TSource currentElement, [AllowNull] ref TKey currentKey) inline package
Definition at line 38 of file DefaultIfEmptyQueryOperator.cs.
        {
            bool flag = _source.MoveNext(ref currentElement, ref currentKey);
            if (!_lookedForEmpty)
            {
                _lookedForEmpty = true;
                if (!flag)
                {
                    if (_partitionIndex == 0)
                    {
                        _sharedLatch.Wait(_cancelToken);
                        _sharedLatch.Dispose();
                        if (_sharedEmptyCount.Value == _partitionCount - 1)
{
                            currentElement = _defaultValue;
                            currentKey = default(TKey);
                            return true;
                        }
                        return false;
                    }
                    Interlocked.Increment(ref _sharedEmptyCount.Value);
                }
                if (_partitionIndex != 0)
                {
                    _sharedLatch.Signal();
                }
            }
            return flag;
        }
References System.Linq.Parallel.DefaultIfEmptyQueryOperator< TSource >.DefaultIfEmptyQueryOperatorEnumerator< TKey >._cancelToken, System.Linq.Parallel.DefaultIfEmptyQueryOperator< TSource >.DefaultIfEmptyQueryOperatorEnumerator< TKey >._defaultValue, System.Linq.Parallel.DefaultIfEmptyQueryOperator< TSource >.DefaultIfEmptyQueryOperatorEnumerator< TKey >._lookedForEmpty, System.Linq.Parallel.DefaultIfEmptyQueryOperator< TSource >.DefaultIfEmptyQueryOperatorEnumerator< TKey >._partitionCount, System.Linq.Parallel.DefaultIfEmptyQueryOperator< TSource >.DefaultIfEmptyQueryOperatorEnumerator< TKey >._partitionIndex, System.Linq.Parallel.DefaultIfEmptyQueryOperator< TSource >.DefaultIfEmptyQueryOperatorEnumerator< TKey >._sharedEmptyCount, System.Linq.Parallel.DefaultIfEmptyQueryOperator< TSource >.DefaultIfEmptyQueryOperatorEnumerator< TKey >._sharedLatch, System.Linq.Parallel.DefaultIfEmptyQueryOperator< TSource >.DefaultIfEmptyQueryOperatorEnumerator< TKey >._source, System.Threading.CountdownEvent.Dispose(), System.Threading.Interlocked.Increment(), System.Linq.Parallel.QueryOperatorEnumerator< TElement, TKey >.MoveNext(), System.Threading.CountdownEvent.Signal(), System.Linq.Parallel.Shared< T >.Value, and System.Threading.CountdownEvent.Wait().