Terraria: FrameSkipTest.UpdateServerTest
UpdateServerTest()
static void FrameSkipTest.UpdateServerTest () inline static
     {
         serverFramerateTest.Record("frame time");
         serverFramerateTest.StopAndPrint();
         serverFramerateTest.Start();
     }
References MultiTimer.Record(), serverFramerateTest, MultiTimer.Start(), and MultiTimer.StopAndPrint().