Terraria: ShapeRoot.DoRoot
DoRoot()
bool ShapeRoot.DoRoot (Point origin, GenAction action, double angle, double distance, double startingSize) inline private
     {
         double num = origin.X;
         double num2 = origin.Y;
         for (double num3 = 0.0; num3 < distance * 0.85; num3 += 1.0)
         {
             double num4 = num3 / distance;
             double num5 = Utils.Lerp(startingSize, _endingSize, num4);
             num += Math.Cos(angle);
             num2 += Math.Sin(angle);
             angle += (double)GenBase._random.NextFloat() - 0.5 + (double)GenBase._random.NextFloat() * (_angle - 1.5707963705062866) * 0.1 * (1.0 - num4);
             angle = angle * 0.4 + 0.45 * Utils.Clamp(angle, _angle - 2.0 * (1.0 - 0.5 * num4), _angle + 2.0 * (1.0 - 0.5 * num4)) + Utils.Lerp(_angle, 1.5707963705062866, num4) * 0.15;
             for (int i = 0; i < (int)num5; i++)
             {
                 for (int j = 0; j < (int)num5; j++)
                 {
                     if (!UnitApply(action, origin, (int)num + i, (int)num2 + j) && _quitOnFail)
                     {
                         return false;
                     }
                 }
             }
         }
         return true;
     }
References _angle, _endingSize, GenShape._quitOnFail, GenBase._random, Utils.Lerp(), and GenShape.UnitApply().
Referenced by Perform().