Terraria: System.ComponentModel.AsyncOperation.PostCore
PostCore()
void System.ComponentModel.AsyncOperation.PostCore (SendOrPostCallback d, object arg, bool markCompleted) inline private
Definition at line 49 of file AsyncOperation.cs.
    {
        VerifyNotCompleted();
        VerifyDelegateNotNull(d);
        if (markCompleted)
        {
            _alreadyCompleted = true;
        }
        _syncContext.Post(d, arg);
    }
References System.ComponentModel.AsyncOperation._alreadyCompleted, System.ComponentModel.AsyncOperation._syncContext, System.Threading.SynchronizationContext.Post(), System.ComponentModel.AsyncOperation.VerifyDelegateNotNull(), and System.ComponentModel.AsyncOperation.VerifyNotCompleted().
Referenced by System.ComponentModel.AsyncOperation.Post(), and System.ComponentModel.AsyncOperation.PostOperationCompleted().