Terraria: Internal.Runtime.InteropServices.ComActivator.UnregisterClassForTypeInternal
UnregisterClassForTypeInternal()
static unsafe int Internal.Runtime.InteropServices.ComActivator.UnregisterClassForTypeInternal (ComActivationContextInternal * pCxtInt) inline static
Definition at line 296 of file ComActivator.cs.
    {
        if (!Marshal.IsBuiltInComSupported)
        {
            throw new NotSupportedException(SR.NotSupported_COM);
        }
        ref ComActivationContextInternal reference = ref *pCxtInt;
        if (IsLoggingEnabled())
        {
        }
        if (reference.InterfaceId != Guid.Empty || reference.ClassFactoryDest != IntPtr.Zero)
        {
            throw new ArgumentException(null, "pCxtInt");
        }
        try
        {
            ComActivationContext cxt = ComActivationContext.Create(ref reference);
            ClassRegistrationScenarioForType(cxt, register: false);
        }
        catch (Exception ex)
        {
            return ex.HResult;
        }
        return 0;
    }
References Internal.Runtime.InteropServices.ComActivator.ClassRegistrationScenarioForType(), Internal.Runtime.InteropServices.ComActivationContext.Create(), System.Guid.Empty, System.Runtime.InteropServices.Marshal.IsBuiltInComSupported, Internal.Runtime.InteropServices.ComActivator.IsLoggingEnabled(), System.SR.NotSupported_COM, and System.IntPtr.Zero.