Terraria: Internal.Runtime.InteropServices.ComActivator.GetClassFactoryForTypeInternal
GetClassFactoryForTypeInternal()
static unsafe int Internal.Runtime.InteropServices.ComActivator.GetClassFactoryForTypeInternal (ComActivationContextInternal * pCxtInt) inline static
Definition at line 240 of file ComActivator.cs.
    {
        if (!Marshal.IsBuiltInComSupported)
        {
            throw new NotSupportedException(SR.NotSupported_COM);
        }
        ref ComActivationContextInternal reference = ref *pCxtInt;
        if (IsLoggingEnabled())
        {
        }
        try
        {
            ComActivationContext cxt = ComActivationContext.Create(ref reference);
            object classFactoryForType = GetClassFactoryForType(cxt);
            IntPtr iUnknownForObject = Marshal.GetIUnknownForObject(classFactoryForType);
            Marshal.WriteIntPtr(reference.ClassFactoryDest, iUnknownForObject);
        }
        catch (Exception ex)
        {
            return ex.HResult;
        }
        return 0;
    }
References Internal.Runtime.InteropServices.ComActivationContext.Create(), Internal.Runtime.InteropServices.ComActivator.GetClassFactoryForType(), System.Runtime.InteropServices.Marshal.GetIUnknownForObject(), System.Runtime.InteropServices.Marshal.IsBuiltInComSupported, Internal.Runtime.InteropServices.ComActivator.IsLoggingEnabled(), System.SR.NotSupported_COM, and System.Runtime.InteropServices.Marshal.WriteIntPtr().