Terraria: Internal.Runtime.InteropServices.ComActivator.GetClassFactoryForType
GetClassFactoryForType()
static object Internal.Runtime.InteropServices.ComActivator.GetClassFactoryForType (ComActivationContext cxt) inline static
Definition at line 154 of file ComActivator.cs.
    {
        if (!Marshal.IsBuiltInComSupported)
        {
            throw new NotSupportedException(SR.NotSupported_COM);
        }
        if (cxt.InterfaceId != typeof(IClassFactory).GUID && cxt.InterfaceId != typeof(IClassFactory2).GUID)
        {
            throw new NotSupportedException();
        }
        if (!Path.IsPathRooted(cxt.AssemblyPath))
        {
            throw new ArgumentException(null, "cxt");
        }
        Type type = FindClassType(cxt.ClassId, cxt.AssemblyPath, cxt.AssemblyName, cxt.TypeName);
        if (LicenseInteropProxy.HasLicense(type))
        {
            return new LicenseClassFactory(cxt.ClassId, type);
        }
        return new BasicClassFactory(cxt.ClassId, type);
    }
References Internal.Runtime.InteropServices.ComActivator.FindClassType(), Internal.Runtime.InteropServices.LicenseInteropProxy.HasLicense(), System.Runtime.InteropServices.Marshal.IsBuiltInComSupported, System.IO.Path.IsPathRooted(), System.SR.NotSupported_COM, and System.type.
Referenced by Internal.Runtime.InteropServices.ComActivator.GetClassFactoryForTypeInternal().