Terraria: Internal.Runtime.InteropServices.ComActivator.FindClassType
FindClassType()
static Type Internal.Runtime.InteropServices.ComActivator.FindClassType (Guid clsid, string assemblyPath, string assemblyName, string typeName) inline static private
Definition at line 328 of file ComActivator.cs.
    {
        try
        {
            AssemblyLoadContext aLC = GetALC(assemblyPath);
            AssemblyName assemblyName2 = new AssemblyName(assemblyName);
            Assembly assembly = aLC.LoadFromAssemblyName(assemblyName2);
            Type type = assembly.GetType(typeName);
            if (type != null)
            {
                return type;
            }
        }
        catch (Exception)
        {
            if (!IsLoggingEnabled())
            {
            }
        }
        throw new COMException(string.Empty, -2147221231);
    }
References System.Runtime.Versioning.AssemblyName, Internal.Runtime.InteropServices.ComActivator.GetALC(), Internal.Runtime.InteropServices.ComActivator.IsLoggingEnabled(), and System.type.
Referenced by Internal.Runtime.InteropServices.ComActivator.ClassRegistrationScenarioForType(), and Internal.Runtime.InteropServices.ComActivator.GetClassFactoryForType().