Terraria: TEHatRack.OnInventoryDraw
OnInventoryDraw()
override void TEHatRack.OnInventoryDraw (Player player, SpriteBatch spriteBatch) inline virtual
Reimplemented from TileEntity.
     {
         if (Main.tile[player.tileEntityAnchor.X, player.tileEntityAnchor.Y].type != 475)
         {
             player.tileEntityAnchor.Clear();
             Recipe.FindRecipes();
         }
         else
         {
             DrawInner(player, spriteBatch);
         }
     }
References PlayerInteractionAnchor.Clear(), DrawInner(), Recipe.FindRecipes(), Main.tile, Player.tileEntityAnchor, Tile.type, PlayerInteractionAnchor.X, and PlayerInteractionAnchor.Y.