Terraria: TEHatRack.Draw
Draw()
void TEHatRack.Draw (int tileLeftX, int tileTopY) inline
     {
         Player dollPlayer = _dollPlayer;
         dollPlayer.direction = -1;
         dollPlayer.Male = true;
         if (Framing.GetTileSafely(tileLeftX, tileTopY).frameX % 216 == 54)
         {
             dollPlayer.direction = 1;
         }
         dollPlayer.isDisplayDollOrInanimate = true;
         dollPlayer.isHatRackDoll = true;
         dollPlayer.armor[0] = _items[0];
         dollPlayer.dye[0] = _dyes[0];
         dollPlayer.ResetEffects();
         dollPlayer.ResetVisibleAccessories();
         dollPlayer.invis = true;
         dollPlayer.UpdateDyes();
         dollPlayer.DisplayDollUpdate();
         dollPlayer.PlayerFrame();
         Vector2 vector = new Vector2((float)tileLeftX + 1.5f, tileTopY + 4) * 16f;
         dollPlayer.direction *= -1;
         Vector2 vector2 = new Vector2(-dollPlayer.width / 2, -dollPlayer.height - 6) + new Vector2(dollPlayer.direction * 14, -2f);
         dollPlayer.position = vector + vector2;
         Main.PlayerRenderer.DrawPlayer(Main.Camera, dollPlayer, dollPlayer.position, 0f, dollPlayer.fullRotationOrigin);
         dollPlayer.armor[0] = _items[1];
         dollPlayer.dye[0] = _dyes[1];
         dollPlayer.ResetEffects();
         dollPlayer.ResetVisibleAccessories();
         dollPlayer.invis = true;
         dollPlayer.UpdateDyes();
         dollPlayer.DisplayDollUpdate();
         dollPlayer.skipAnimatingValuesInPlayerFrame = true;
         dollPlayer.PlayerFrame();
         dollPlayer.skipAnimatingValuesInPlayerFrame = false;
         dollPlayer.direction *= -1;
         vector2 = new Vector2(-dollPlayer.width / 2, -dollPlayer.height - 6) + new Vector2(dollPlayer.direction * 12, 16f);
         dollPlayer.position = vector + vector2;
         Main.PlayerRenderer.DrawPlayer(Main.Camera, dollPlayer, dollPlayer.position, 0f, dollPlayer.fullRotationOrigin);
     }
References _dollPlayer, _dyes, _items, Player.armor, Main.Camera, Entity.direction, Player.DisplayDollUpdate(), IPlayerRenderer.DrawPlayer(), Player.dye, Tile.frameX, Player.fullRotationOrigin, Framing.GetTileSafely(), Entity.height, Player.invis, Player.isDisplayDollOrInanimate, Player.isHatRackDoll, Player.Male, Player.PlayerFrame(), Main.PlayerRenderer, Entity.position, Player.ResetEffects(), Player.ResetVisibleAccessories(), Player.skipAnimatingValuesInPlayerFrame, Player.UpdateDyes(), and Entity.width.