Terraria: TEHatRack.TryFitting
TryFitting()
bool TEHatRack.TryFitting (Item[] inv, int context = 0, int slot = 0, bool justCheck = false) inline private
     {
         if (!FitsHatRack(inv[slot]))
         {
             return false;
         }
         if (justCheck)
         {
             return true;
         }
         int num = hatTargetSlot;
         hatTargetSlot++;
         for (int i = 0; i < 2; i++)
         {
             if (_items[i].IsAir)
             {
                 num = i;
                 hatTargetSlot = i + 1;
                 break;
             }
         }
         for (int j = 0; j < 2; j++)
         {
             if (inv[slot].type == _items[j].type)
             {
                 num = j;
             }
         }
         if (hatTargetSlot >= 2)
         {
             hatTargetSlot = 0;
         }
         SoundEngine.PlaySound(7);
         Utils.Swap(ref _items[num], ref inv[slot]);
         if (Main.netMode == 1)
         {
             NetMessage.SendData(124, -1, -1, null, Main.myPlayer, ID, num);
         }
         return true;
     }
References _items, FitsHatRack(), hatTargetSlot, TileEntity.ID, Main.myPlayer, Main.netMode, SoundEngine.PlaySound(), NetMessage.SendData(), and TileEntity.type.
Referenced by OverrideItemSlotLeftClick().