Terraria: TEHatRack.OnPlayerUpdate
OnPlayerUpdate()
override void TEHatRack.OnPlayerUpdate (Player player) inline virtual
Reimplemented from TileEntity.
     {
         if (!player.InInteractionRange(player.tileEntityAnchor.X, player.tileEntityAnchor.Y, TileReachCheckSettings.Simple) || player.chest != -1 || player.talkNPC != -1)
         {
             if (player.chest == -1 && player.talkNPC == -1)
             {
                 SoundEngine.PlaySound(11);
             }
             player.tileEntityAnchor.Clear();
             Recipe.FindRecipes();
         }
     }
References Player.chest, PlayerInteractionAnchor.Clear(), Recipe.FindRecipes(), Player.InInteractionRange(), SoundEngine.PlaySound(), TileReachCheckSettings.Simple, Player.talkNPC, Player.tileEntityAnchor, PlayerInteractionAnchor.X, and PlayerInteractionAnchor.Y.