Terraria: Terraria.GameContent.Tile_Entities.TEDisplayDoll.OverrideItemSlotLeftClick
OverrideItemSlotLeftClick()
override bool Terraria.GameContent.Tile_Entities.TEDisplayDoll.OverrideItemSlotLeftClick (Item[] inv, int context = 0, int slot = 0) inline virtual
Reimplemented from Terraria.DataStructures.TileEntity.
    {
        if (!ItemSlot.ShiftInUse)
        {
            return false;
        }
        if (Main.cursorOverride == 9 && context == 0)
        {
            Item item = inv[slot];
            if (!item.IsAir && !item.favorited && FitsDisplayDoll(item))
            {
                return TryFitting(inv, context, slot);
            }
        }
        if ((Main.cursorOverride == 8 && context == 23) || context == 24 || context == 25)
        {
            inv[slot] = Main.player[Main.myPlayer].GetItem(Main.myPlayer, inv[slot], GetItemSettings.InventoryEntityToPlayerInventorySettings);
            if (Main.netMode == 1)
            {
                if (context == 25)
                {
                    NetMessage.SendData(121, -1, -1, null, Main.myPlayer, ID, slot, 1f);
                }
                else
                {
                    NetMessage.SendData(121, -1, -1, null, Main.myPlayer, ID, slot);
                }
            }
            return true;
        }
        return false;
    }
References Terraria.Main.cursorOverride, Terraria.Item.favorited, Terraria.GameContent.Tile_Entities.TEDisplayDoll.FitsDisplayDoll(), Terraria.Player.GetItem(), Terraria.GetItemSettings.InventoryEntityToPlayerInventorySettings, Terraria.Item.IsAir, Terraria.Main.myPlayer, Terraria.Main.netMode, Terraria.Main.player, Terraria.NetMessage.SendData(), Terraria.UI.ItemSlot.ShiftInUse, and Terraria.GameContent.Tile_Entities.TEDisplayDoll.TryFitting().