Terraria: Terraria.GameContent.Tile_Entities.TEDisplayDoll.IsBreakable
IsBreakable()
static bool Terraria.GameContent.Tile_Entities.TEDisplayDoll.IsBreakable (int clickX, int clickY) inline static
Definition at line 591 of file TEDisplayDoll.cs.
    {
        int num = clickX;
        int num2 = clickY;
        if (Main.tile[num, num2].frameX % 36 != 0)
        {
            num--;
        }
        num2 -= Main.tile[num, num2].frameY / 18;
        int num3 = Find(num, num2);
        if (num3 != -1)
        {
            return !(TileEntity.ByID[num3] as TEDisplayDoll).ContainsItems();
        }
        return true;
    }
References Terraria.GameContent.Tile_Entities.TEDisplayDoll.TEDisplayDoll(), Terraria.DataStructures.TileEntity.ByID, Terraria.GameContent.Tile_Entities.TEDisplayDoll.ContainsItems(), Terraria.GameContent.Tile_Entities.TEDisplayDoll.Find(), and Terraria.Main.tile.
Referenced by Terraria.WorldGen.CheckTileBreakability2_ShouldTileSurvive().