Terraria: Terraria.GameContent.Tile_Entities.TEDisplayDoll.TEDisplayDoll
TEDisplayDoll()
Terraria.GameContent.Tile_Entities.TEDisplayDoll.TEDisplayDoll () inline
Definition at line 29 of file TEDisplayDoll.cs.
    {
        _items = new Item[8];
        for (int i = 0; i < _items.Length; i++)
        {
            _items[i] = new Item();
        }
        _dyes = new Item[8];
        for (int j = 0; j < _dyes.Length; j++)
        {
            _dyes[j] = new Item();
        }
        _dollPlayer = new Player();
        _dollPlayer.hair = 15;
        _dollPlayer.skinColor = Color.White;
        _dollPlayer.skinVariant = 10;
    }
References Terraria.GameContent.Tile_Entities.TEDisplayDoll._dollPlayer, Terraria.GameContent.Tile_Entities.TEDisplayDoll._dyes, and Terraria.GameContent.Tile_Entities.TEDisplayDoll._items.
Referenced by Terraria.GameContent.Tile_Entities.TEDisplayDoll.GenerateInstance(), Terraria.GameContent.Tile_Entities.TEDisplayDoll.IsBreakable(), and Terraria.GameContent.Tile_Entities.TEDisplayDoll.Place().