Terraria: Terraria.GameContent.Tile_Entities.TEDisplayDoll.ReadExtraData
ReadExtraData()
override void Terraria.GameContent.Tile_Entities.TEDisplayDoll.ReadExtraData (BinaryReader reader, bool networkSend) inline virtual
Reimplemented from Terraria.DataStructures.TileEntity.
Definition at line 153 of file TEDisplayDoll.cs.
    {
        BitsByte bitsByte = reader.ReadByte();
        BitsByte bitsByte2 = reader.ReadByte();
        for (int i = 0; i < 8; i++)
        {
            _items[i] = new Item();
            Item item = _items[i];
            if (bitsByte[i])
            {
                item.netDefaults(reader.ReadInt16());
                item.Prefix(reader.ReadByte());
                item.stack = reader.ReadInt16();
            }
        }
        for (int j = 0; j < 8; j++)
        {
            _dyes[j] = new Item();
            Item item2 = _dyes[j];
            if (bitsByte2[j])
            {
                item2.netDefaults(reader.ReadInt16());
                item2.Prefix(reader.ReadByte());
                item2.stack = reader.ReadInt16();
            }
        }
    }
References Terraria.GameContent.Tile_Entities.TEDisplayDoll._dyes, Terraria.GameContent.Tile_Entities.TEDisplayDoll._items, Terraria.Item.netDefaults(), Terraria.Item.Prefix(), System.IO.BinaryReader.ReadByte(), and System.IO.BinaryReader.ReadInt16().