Terraria: Terraria.GameContent.Tile_Entities.TEDisplayDoll.OnInventoryDraw
OnInventoryDraw()
override void Terraria.GameContent.Tile_Entities.TEDisplayDoll.OnInventoryDraw (Player player, SpriteBatch spriteBatch) inline virtual
Reimplemented from Terraria.DataStructures.TileEntity.
Definition at line 304 of file TEDisplayDoll.cs.
    {
        if (Main.tile[player.tileEntityAnchor.X, player.tileEntityAnchor.Y].type != 470)
        {
            player.tileEntityAnchor.Clear();
            Recipe.FindRecipes();
        }
        else
        {
            DrawInner(player, spriteBatch);
        }
    }
References Terraria.DataStructures.PlayerInteractionAnchor.Clear(), Terraria.GameContent.Tile_Entities.TEDisplayDoll.DrawInner(), Terraria.Recipe.FindRecipes(), Terraria.Main.tile, Terraria.Player.tileEntityAnchor, Terraria.DataStructures.PlayerInteractionAnchor.X, and Terraria.DataStructures.PlayerInteractionAnchor.Y.