Terraria: Terraria.GameContent.Tile_Entities.TEDisplayDoll.TryFitting
TryFitting()
bool Terraria.GameContent.Tile_Entities.TEDisplayDoll.TryFitting (Item[] inv, int context = 0, int slot = 0, bool justCheck = false) inline private
    {
        Item item = inv[slot];
        int num = -1;
        if (item.headSlot > 0)
        {
            num = 0;
        }
        if (item.bodySlot > 0)
        {
            num = 1;
        }
        if (item.legSlot > 0)
        {
            num = 2;
        }
        if (item.accessory)
        {
            num = accessoryTargetSlot;
        }
        if (num == -1)
        {
            return false;
        }
        if (justCheck)
        {
            return true;
        }
        if (item.accessory)
        {
            accessoryTargetSlot++;
            if (accessoryTargetSlot >= 8)
            {
                accessoryTargetSlot = 3;
            }
            bool flag = ItemSlot.AccCheck(_items, inv[slot], -1);
            for (int i = 3; i < 8; i++)
            {
                if (_items[i].IsAir)
                {
                    num = i;
                    accessoryTargetSlot = i;
                    break;
                }
            }
            for (int j = 3; j < 8; j++)
            {
                if (inv[slot].type == _items[j].type || (flag && !ItemSlot.AccCheck(_items, inv[slot], j)))
                {
                    num = j;
                    if (flag)
                    {
                        flag = false;
                        break;
                    }
                }
            }
            if (flag && num > -1)
            {
                return false;
            }
        }
        SoundEngine.PlaySound(7);
        Utils.Swap(ref _items[num], ref inv[slot]);
        if (Main.netMode == 1)
        {
            NetMessage.SendData(121, -1, -1, null, Main.myPlayer, ID, num);
        }
        return true;
    }
References Terraria.GameContent.Tile_Entities.TEDisplayDoll._items, Terraria.UI.ItemSlot.AccCheck(), Terraria.Item.accessory, Terraria.GameContent.Tile_Entities.TEDisplayDoll.accessoryTargetSlot, Terraria.Item.bodySlot, Terraria.Item.headSlot, Terraria.Item.legSlot, Terraria.Main.myPlayer, Terraria.Main.netMode, Terraria.Audio.SoundEngine.PlaySound(), Terraria.NetMessage.SendData(), and Terraria.DataStructures.TileEntity.type.
Referenced by Terraria.GameContent.Tile_Entities.TEDisplayDoll.OverrideItemSlotLeftClick().