Terraria: System.Xml.Xsl.Runtime.XmlSortKeyAccumulator.AppendSortKey
AppendSortKey()
void System.Xml.Xsl.Runtime.XmlSortKeyAccumulator.AppendSortKey (XmlSortKey key) inline private
Definition at line 71 of file XmlSortKeyAccumulator.cs.
    {
        key.Priority = _pos;
        if (_keys[_pos] == null)
        {
            _keys[_pos] = key;
        }
        else
        {
            _keys[_pos].AddSortKey(key);
        }
    }
References System.Xml.Xsl.Runtime.XmlSortKeyAccumulator._keys, System.Xml.Xsl.Runtime.XmlSortKeyAccumulator._pos, System.Xml.Xsl.Runtime.XmlSortKey.AddSortKey(), System.Xml.Dictionary, and System.key.
Referenced by System.Xml.Xsl.Runtime.XmlSortKeyAccumulator.AddDateTimeSortKey(), System.Xml.Xsl.Runtime.XmlSortKeyAccumulator.AddDecimalSortKey(), System.Xml.Xsl.Runtime.XmlSortKeyAccumulator.AddDoubleSortKey(), System.Xml.Xsl.Runtime.XmlSortKeyAccumulator.AddEmptySortKey(), System.Xml.Xsl.Runtime.XmlSortKeyAccumulator.AddIntegerSortKey(), System.Xml.Xsl.Runtime.XmlSortKeyAccumulator.AddIntSortKey(), and System.Xml.Xsl.Runtime.XmlSortKeyAccumulator.AddStringSortKey().