Terraria: System.Text.Encodings.Web.AllowedBmpCodePointsBitmap.IsCharAllowed
IsCharAllowed()
unsafe readonly bool System.Text.Encodings.Web.AllowedBmpCodePointsBitmap.IsCharAllowed (char value) inline
Definition at line 62 of file AllowedBmpCodePointsBitmap.cs.
    {
        _GetIndexAndOffset(value, out UIntPtr index, out int offset);
        if ((Bitmap[(ulong)index] & (uint)(1 << offset)) != 0)
        {
            return true;
        }
        return false;
    }
References System.Text.Encodings.Web.AllowedBmpCodePointsBitmap._GetIndexAndOffset(), System.Text.Encodings.Web.AllowedBmpCodePointsBitmap.Bitmap, System.index, System.offset, and System.Text.Encodings.Web.value.
Referenced by System.Text.Encodings.Web.TextEncoderSettings.GetAllowedCodePoints(), System.Text.Encodings.Web.OptimizedInboxTextEncoder.GetIndexOfFirstByteToEncode(), and System.Text.Encodings.Web.OptimizedInboxTextEncoder.GetIndexOfFirstCharToEncode().