Terraria: System.Text.Encodings.Web.AllowedBmpCodePointsBitmap.AllowChar
AllowChar()
unsafe void System.Text.Encodings.Web.AllowedBmpCodePointsBitmap.AllowChar (char value) inline
Definition at line 13 of file AllowedBmpCodePointsBitmap.cs.
    {
        _GetIndexAndOffset(value, out UIntPtr index, out int offset);
        ref uint reference = ref Bitmap[(ulong)index];
        reference |= (uint)(1 << offset);
    }
References System.Text.Encodings.Web.AllowedBmpCodePointsBitmap._GetIndexAndOffset(), System.Text.Encodings.Web.AllowedBmpCodePointsBitmap.Bitmap, System.index, System.offset, and System.Text.Encodings.Web.value.
Referenced by System.Text.Encodings.Web.TextEncoderSettings.AllowCharacter(), System.Text.Encodings.Web.TextEncoderSettings.AllowCharacters(), System.Text.Encodings.Web.TextEncoderSettings.AllowCodePoints(), and System.Text.Encodings.Web.TextEncoderSettings.AllowRange().