Terraria: System.Text.Encodings.Web.AllowedBmpCodePointsBitmap.ForbidChar
ForbidChar()
unsafe void System.Text.Encodings.Web.AllowedBmpCodePointsBitmap.ForbidChar (char value) inline
Definition at line 21 of file AllowedBmpCodePointsBitmap.cs.
    {
        _GetIndexAndOffset(value, out UIntPtr index, out int offset);
        ref uint reference = ref Bitmap[(ulong)index];
        reference &= (uint)(~(1 << offset));
    }
References System.Text.Encodings.Web.AllowedBmpCodePointsBitmap._GetIndexAndOffset(), System.Text.Encodings.Web.AllowedBmpCodePointsBitmap.Bitmap, System.index, System.offset, and System.Text.Encodings.Web.value.
Referenced by System.Text.Encodings.Web.OptimizedInboxTextEncoder.OptimizedInboxTextEncoder(), System.Text.Encodings.Web.TextEncoderSettings.ForbidCharacter(), System.Text.Encodings.Web.TextEncoderSettings.ForbidCharacters(), System.Text.Encodings.Web.AllowedBmpCodePointsBitmap.ForbidHtmlCharacters(), and System.Text.Encodings.Web.TextEncoderSettings.ForbidRange().