Terraria: System.Text.Encodings.Web.AllowedBmpCodePointsBitmap.IsCodePointAllowed
IsCodePointAllowed()
unsafe readonly bool System.Text.Encodings.Web.AllowedBmpCodePointsBitmap.IsCodePointAllowed (uint value) inline
Definition at line 73 of file AllowedBmpCodePointsBitmap.cs.
    {
        if (!System.Text.UnicodeUtility.IsBmpCodePoint(value))
        {
            return false;
        }
        _GetIndexAndOffset(value, out UIntPtr index, out int offset);
        if ((Bitmap[(ulong)index] & (uint)(1 << offset)) != 0)
        {
            return true;
        }
        return false;
    }
References System.Text.Encodings.Web.AllowedBmpCodePointsBitmap._GetIndexAndOffset(), System.Text.Encodings.Web.AllowedBmpCodePointsBitmap.Bitmap, System.index, System.Text.UnicodeUtility.IsBmpCodePoint(), System.offset, and System.Text.Encodings.Web.value.
Referenced by System.Text.Encodings.Web.OptimizedInboxTextEncoder.IsScalarValueAllowed(), and System.Text.Encodings.Web.OptimizedInboxTextEncoder.TryEncodeUnicodeScalar().