Terraria: System.Security.Cryptography.X509Certificates.PublicKey.EncodeSubjectPublicKeyInfo
EncodeSubjectPublicKeyInfo()
AsnWriter System.Security.Cryptography.X509Certificates.PublicKey.EncodeSubjectPublicKeyInfo () inline private
Definition at line 154 of file PublicKey.cs.
    {
        System.Security.Cryptography.Asn1.SubjectPublicKeyInfoAsn subjectPublicKeyInfoAsn = default(System.Security.Cryptography.Asn1.SubjectPublicKeyInfoAsn);
        subjectPublicKeyInfoAsn.Algorithm = new System.Security.Cryptography.Asn1.AlgorithmIdentifierAsn
        {
            Algorithm = (_oid.Value ?? string.Empty),
            Parameters = EncodedParameters.RawData
        };
        subjectPublicKeyInfoAsn.SubjectPublicKey = EncodedKeyValue.RawData;
        System.Security.Cryptography.Asn1.SubjectPublicKeyInfoAsn subjectPublicKeyInfoAsn2 = subjectPublicKeyInfoAsn;
        AsnWriter asnWriter = new AsnWriter(AsnEncodingRules.DER);
        subjectPublicKeyInfoAsn2.Encode(asnWriter);
        return asnWriter;
    }
References System.Security.Cryptography.Asn1.SubjectPublicKeyInfoAsn.Encode(), System.Security.Cryptography.X509Certificates.PublicKey.EncodedKeyValue, System.Security.Cryptography.X509Certificates.PublicKey.EncodedParameters, and System.Security.Cryptography.AsnEncodedData.RawData.
Referenced by System.Security.Cryptography.X509Certificates.PublicKey.ExportSubjectPublicKeyInfo(), and System.Security.Cryptography.X509Certificates.PublicKey.TryExportSubjectPublicKeyInfo().