Terraria: System.Security.Cryptography.X509Certificates.PublicKey.DecodeSubjectPublicKeyInfo
DecodeSubjectPublicKeyInfo()
static unsafe int System.Security.Cryptography.X509Certificates.PublicKey.DecodeSubjectPublicKeyInfo (ReadOnlySpan< byte > source, out Oid oid, out AsnEncodedData parameters, out AsnEncodedData keyValue) inline static private
Definition at line 169 of file PublicKey.cs.
    {
        fixed (byte* pointer = &MemoryMarshal.GetReference(source))
        {
            using MemoryManager<byte> memoryManager = new System.Buffers.PointerMemoryManager<byte>(pointer, source.Length);
            System.Formats.Asn1.AsnValueReader reader = new System.Formats.Asn1.AsnValueReader(source, AsnEncodingRules.DER);
            int length;
            System.Security.Cryptography.Asn1.SubjectPublicKeyInfoAsn decoded;
            try
            {
                length = reader.PeekEncodedValue().Length;
                System.Security.Cryptography.Asn1.SubjectPublicKeyInfoAsn.Decode(ref reader, memoryManager.Memory, out decoded);
            }
            catch (AsnContentException inner)
            {
                throw new CryptographicException(System.SR.Cryptography_Der_Invalid_Encoding, inner);
            }
            oid = new Oid(decoded.Algorithm.Algorithm, null);
            parameters = new AsnEncodedData(decoded.Algorithm.Parameters?.ToArray() ?? Array.Empty<byte>());
            keyValue = new AsnEncodedData(decoded.SubjectPublicKey.ToArray());
            return length;
        }
    }
References System.Security.Cryptography.Asn1.AlgorithmIdentifierAsn.Algorithm, System.Security.Cryptography.Asn1.SubjectPublicKeyInfoAsn.Algorithm, System.SR.Cryptography_Der_Invalid_Encoding, System.Security.Cryptography.Asn1.SubjectPublicKeyInfoAsn.Decode(), System.length, System.Security.Cryptography.X509Certificates.PublicKey.Oid, System.Security.Cryptography.Asn1.AlgorithmIdentifierAsn.Parameters, System.pointer, System.source, System.Security.Cryptography.Asn1.SubjectPublicKeyInfoAsn.SubjectPublicKey, and System.ReadOnlyMemory< T >.ToArray().
Referenced by System.Security.Cryptography.X509Certificates.PublicKey.PublicKey(), and System.Security.Cryptography.X509Certificates.PublicKey.CreateFromSubjectPublicKeyInfo().