Terraria: System.Runtime.InteropServices.MemoryMarshal.GetArrayDataReference
GetArrayDataReference()
static unsafe ref byte System.Runtime.InteropServices.MemoryMarshal.GetArrayDataReference (Array array) inline static
Definition at line 21 of file MemoryMarshal.cs.
    {
        return ref Unsafe.AddByteOffset(ref Unsafe.As<RawData>(array).Data, (nuint)RuntimeHelpers.GetMethodTable(array)->BaseSize - (nuint)(2 * sizeof(IntPtr)));
    }
References System.array, System.Runtime.CompilerServices.RawData.Data, and System.Runtime.CompilerServices.RuntimeHelpers.GetMethodTable().
Referenced by System.ReadOnlySpan< T >.ReadOnlySpan(), System.ReadOnlySpan< T >.ReadOnlySpan(), System.Span< T >.Span(), System.Span< T >.Span(), System.Runtime.InteropServices.GCHandle.AddrOfPinnedObject(), System.Text.StringBuilder.Append(), System.MemoryExtensions.AsSpan< T >(), System.MemoryExtensions.AsSpan< T >(), System.MemoryExtensions.AsSpan< T >(), System.Buffer.BlockCopy(), System.Array.Clear(), System.StubHelpers.AnsiBSTRMarshaler.ConvertToNative(), System.StubHelpers.CSTRMarshaler.ConvertToNative(), System.StubHelpers.VBByValStrMarshaler.ConvertToNative(), System.Array.Copy(), System.String.CopyTo(), System.String.Ctor(), System.String.Ctor(), System.Array.Fill< T >(), System.Buffer.GetByte(), System.Runtime.CompilerServices.RuntimeHelpers.GetSubArray< T >(), System.Array.IndexOf< T >(), System.Array.LastIndexOf< T >(), System.Buffer.Memcpy(), System.Memory< T >.Pin(), System.ReadOnlyMemory< T >.Pin(), System.Array.Resize< T >(), System.Array.Reverse< T >(), System.Buffer.SetByte(), System.Array.Sort< T >(), System.Array.Sort< T >(), System.Array.Sort< T >(), System.Array.Sort< TKey, TValue >(), System.Runtime.CompilerServices.CastHelpers.TableData(), System.ReadOnlySpan< T >.ToArray(), System.Span< T >.ToArray(), System.String.ToCharArray(), System.String.ToCharArray(), System.Text.StringBuilder.ToString(), System.Runtime.InteropServices.Marshal.UnsafeAddrOfPinnedArrayElement(), System.Runtime.InteropServices.Marshal.UnsafeAddrOfPinnedArrayElement< T >(), and System.Array.UnsafeArrayAsSpan< T >().