Terraria: System.Formats.Asn1.AsnReader.ThrowIfNotEmpty
ThrowIfNotEmpty()
void System.Formats.Asn1.AsnReader.ThrowIfNotEmpty () inline
Definition at line 24 of file AsnReader.cs.
    {
        if (HasData)
        {
            throw new AsnContentException(System.SR.ContentException_TooMuchData);
        }
    }
References System.SR.ContentException_TooMuchData, and System.Formats.Asn1.AsnReader.HasData.
Referenced by System.Security.Cryptography.EccKeyFormatHelper.GetSpecifiedECCurveCore(), System.Security.Cryptography.EccKeyFormatHelper.GetSpecifiedECCurveCore(), and System.Formats.Asn1.AsnValueReader.ThrowIfNotEmpty().