Terraria: System.Security.Cryptography.RSACryptoServiceProvider.VerifyHash
VerifyHash() [1/4]
override bool System.Security.Cryptography.RSACryptoServiceProvider.VerifyHash (byte[] hash, byte[] signature, HashAlgorithmName hashAlgorithm, RSASignaturePadding padding) inline virtual
Reimplemented from System.Security.Cryptography.RSA.
Definition at line 506 of file RSACryptoServiceProvider.cs.
    {
        if (hash == null)
        {
            throw new ArgumentNullException("hash");
        }
        if (signature == null)
        {
            throw new ArgumentNullException("signature");
        }
        if (string.IsNullOrEmpty(hashAlgorithm.Name))
        {
            throw HashAlgorithmNameNullOrEmpty();
        }
        if (padding == null)
        {
            throw new ArgumentNullException("padding");
        }
        if (padding != RSASignaturePadding.Pkcs1)
        {
            throw PaddingModeNotSupported();
        }
        return VerifyHash(hash, GetAlgorithmId(hashAlgorithm), signature);
    }
References System.Security.Cryptography.RSACryptoServiceProvider.GetAlgorithmId(), System.Security.Cryptography.RSACryptoServiceProvider.HashAlgorithmNameNullOrEmpty(), System.Security.Cryptography.HashAlgorithmName.Name, System.Security.Cryptography.RSACryptoServiceProvider.PaddingModeNotSupported(), System.Security.Cryptography.RSASignaturePadding.Pkcs1, and System.Security.Cryptography.RSACryptoServiceProvider.VerifyHash().