Terraria: System.Security.Cryptography.RSACryptoServiceProvider.SignData
SignData() [1/6]
byte[] System.Security.Cryptography.RSACryptoServiceProvider.SignData (byte[] buffer, int offset, int count, object halg) inline
Definition at line 318 of file RSACryptoServiceProvider.cs.
    {
        int calgHash = CapiHelper.ObjToHashAlgId(halg);
        HashAlgorithm hashAlgorithm = CapiHelper.ObjToHashAlgorithm(halg);
        byte[] rgbHash = hashAlgorithm.ComputeHash(buffer, offset, count);
        return SignHash(rgbHash, calgHash);
    }
References System.buffer, System.Security.Cryptography.HashAlgorithm.ComputeHash(), System.count, Internal.NativeCrypto.CapiHelper.ObjToHashAlgId(), Internal.NativeCrypto.CapiHelper.ObjToHashAlgorithm(), System.offset, and System.Security.Cryptography.RSACryptoServiceProvider.SignHash().