Terraria: System.Net.Http.Headers.ContentDispositionHeaderValue.EncodeAndQuoteMime
EncodeAndQuoteMime()
static string System.Net.Http.Headers.ContentDispositionHeaderValue.EncodeAndQuoteMime (string input) inline static private
Definition at line 348 of file ContentDispositionHeaderValue.cs.
    {
        string text = input;
        bool flag = false;
        if (IsQuoted(text))
        {
            text = text.Substring(1, text.Length - 2);
            flag = true;
        }
        if (text.Contains('"'))
        {
            throw new ArgumentException(System.SR.Format(CultureInfo.InvariantCulture, System.SR.net_http_headers_invalid_value, input));
        }
        if (HeaderUtilities.ContainsNonAscii(text))
        {
            flag = true;
            text = EncodeMime(text);
        }
        else if (!flag && HttpRuleParser.GetTokenLength(text, 0) != text.Length)
        {
            flag = true;
        }
        if (flag)
        {
            text = "\"" + text + "\"";
        }
        return text;
    }
References System.Net.Http.Headers.HeaderUtilities.ContainsNonAscii(), System.Net.Http.Headers.ContentDispositionHeaderValue.EncodeMime(), System.SR.Format(), System.Net.Http.HttpRuleParser.GetTokenLength(), System.input, System.Globalization.CultureInfo.InvariantCulture, System.Net.Http.Headers.ContentDispositionHeaderValue.IsQuoted(), System.SR.net_http_headers_invalid_value, and System.text.
Referenced by System.Net.Http.Headers.ContentDispositionHeaderValue.SetName().