Terraria: System.Net.Http.Headers.ContentDispositionHeaderValue.TryDecode5987
TryDecode5987()
static bool System.Net.Http.Headers.ContentDispositionHeaderValue.TryDecode5987 (string input, out string output) inline static private
Definition at line 421 of file ContentDispositionHeaderValue.cs.
    {
        output = null;
        int num = input.IndexOf('\'');
        if (num == -1)
        {
            return false;
        }
        int num2 = input.LastIndexOf('\'');
        if (num == num2 || input.IndexOf('\'', num + 1) != num2)
        {
            return false;
        }
        string name = input.Substring(0, num);
        string text = input.Substring(num2 + 1, input.Length - (num2 + 1));
        StringBuilder stringBuilder = new StringBuilder();
        try
        {
            Encoding encoding = Encoding.GetEncoding(name);
            byte[] array = new byte[text.Length];
            int num3 = 0;
            for (int i = 0; i < text.Length; i++)
            {
                if (Uri.IsHexEncoding(text, i))
                {
                    array[num3++] = (byte)Uri.HexUnescape(text, ref i);
                    i--;
                    continue;
                }
                if (num3 > 0)
                {
                    stringBuilder.Append(encoding.GetString(array, 0, num3));
                    num3 = 0;
                }
                stringBuilder.Append(text[i]);
            }
            if (num3 > 0)
            {
                stringBuilder.Append(encoding.GetString(array, 0, num3));
            }
        }
        catch (ArgumentException)
        {
            return false;
        }
        output = stringBuilder.ToString();
        return true;
    }
References System.array, System.Text.Encoding.GetEncoding(), System.Text.Encoding.GetString(), System.Uri.HexUnescape(), System.input, System.Uri.IsHexEncoding(), and System.text.
Referenced by System.Net.Http.Headers.ContentDispositionHeaderValue.GetName().