Terraria: System.Xml.ByteStack.Push
Push()
void System.Xml.ByteStack.Push (byte data) inline
Definition at line 21 of file ByteStack.cs.
    {
        if (_size == _top)
        {
            byte[] array = new byte[_size + _growthRate];
            if (_top > 0)
            {
                Buffer.BlockCopy(_stack, 0, array, 0, _top);
            }
            _stack = array;
            _size += _growthRate;
        }
        _stack[_top++] = data;
    }
References System.Xml.ByteStack._growthRate, System.Xml.ByteStack._size, System.Xml.ByteStack._stack, System.Xml.ByteStack._top, System.array, and System.Buffer.BlockCopy().
Referenced by System.Xml.HtmlEncodedRawTextWriter.WriteStartElement(), System.Xml.HtmlEncodedRawTextWriterIndent.WriteStartElement(), System.Xml.HtmlUtf8RawTextWriter.WriteStartElement(), and System.Xml.HtmlUtf8RawTextWriterIndent.WriteStartElement().