Terraria: System.Net.Http.Headers.ContentDispositionHeaderValue.ToString
ToString()
override string System.Net.Http.Headers.ContentDispositionHeaderValue.ToString () inline
Definition at line 157 of file ContentDispositionHeaderValue.cs.
    {
        StringBuilder stringBuilder = System.Text.StringBuilderCache.Acquire();
        stringBuilder.Append(_dispositionType);
        NameValueHeaderValue.ToString(_parameters, ';', leadingSeparator: true, stringBuilder);
        return System.Text.StringBuilderCache.GetStringAndRelease(stringBuilder);
    }
References System.Net.Http.Headers.ContentDispositionHeaderValue._dispositionType, System.Net.Http.Headers.ContentDispositionHeaderValue._parameters, System.Text.StringBuilderCache.Acquire(), System.Text.StringBuilderCache.GetStringAndRelease(), and System.Net.Http.Headers.NameValueHeaderValue.ToString().