Terraria: System.Net.Http.Headers.ContentDispositionHeaderValue.GetDate
GetDate()
DateTimeOffset? System.Net.Http.Headers.ContentDispositionHeaderValue.GetDate (string parameter) inline private
Definition at line 262 of file ContentDispositionHeaderValue.cs.
    {
        NameValueHeaderValue nameValueHeaderValue = NameValueHeaderValue.Find(_parameters, parameter);
        if (nameValueHeaderValue != null)
        {
            ReadOnlySpan<char> readOnlySpan = nameValueHeaderValue.Value;
            if (IsQuoted(readOnlySpan))
            {
                readOnlySpan = readOnlySpan.Slice(1, readOnlySpan.Length - 2);
            }
            if (HttpDateParser.TryParse(readOnlySpan, out var result))
            {
                return result;
            }
        }
        return null;
    }
References System.Net.Http.Headers.ContentDispositionHeaderValue._parameters, System.Net.Http.Headers.NameValueHeaderValue.Find(), System.Net.Http.Headers.ContentDispositionHeaderValue.IsQuoted(), and System.Net.HttpDateParser.TryParse().