Terraria: Microsoft.Xna.Framework.Vector2.Clamp
Clamp() [2/2]
static Vector2 Microsoft.Xna.Framework.Vector2.Clamp (Vector2 value1, Vector2 min, Vector2 max) inline static
Definition at line 201 of file Vector2.cs.
    {
        float x = value1.X;
        x = ((x > max.X) ? max.X : x);
        x = ((x < min.X) ? min.X : x);
        float y = value1.Y;
        y = ((y > max.Y) ? max.Y : y);
        y = ((y < min.Y) ? min.Y : y);
        Vector2 result = default(Vector2);
        result.X = x;
        result.Y = y;
        return result;
    }
References Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.NPC.AI(), Terraria.GameContent.Skies.AmbientSky.EOCSkyEntity.ChasePlayerTop(), Terraria.Main.ClampScreenPositionToWorld(), Terraria.Graphics.Capture.CaptureInterface.ModeEdgeSelection.DrawCursors(), and Terraria.Main.DrawInterface_GolfBallIndicator().