Terraria: Microsoft.Xna.Framework.Vector2.CatmullRom
CatmullRom() [2/2]
static Vector2 Microsoft.Xna.Framework.Vector2.CatmullRom (Vector2 value1, Vector2 value2, Vector2 value3, Vector2 value4, float amount) inline static
Definition at line 273 of file Vector2.cs.
    {
        float num = amount * amount;
        float num2 = amount * num;
        Vector2 result = default(Vector2);
        result.X = 0.5f * (2f * value2.X + (0f - value1.X + value3.X) * amount + (2f * value1.X - 5f * value2.X + 4f * value3.X - value4.X) * num + (0f - value1.X + 3f * value2.X - 3f * value3.X + value4.X) * num2);
        result.Y = 0.5f * (2f * value2.Y + (0f - value1.Y + value3.Y) * amount + (2f * value1.Y - 5f * value2.Y + 4f * value3.Y - value4.Y) * num + (0f - value1.Y + 3f * value2.Y - 3f * value3.Y + value4.Y) * num2);
        return result;
    }
References Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.NPC.AI(), Terraria.Projectile.AI_162_TigerPounce(), Terraria.Projectile.AI_167_SparkleGuitar(), and Terraria.Graphics.VertexStrip.PrepareStripWithProceduralPadding().