Terraria: Microsoft.Xna.Framework.Vector2.SmoothStep
SmoothStep() [2/2]
static Vector2 Microsoft.Xna.Framework.Vector2.SmoothStep (Vector2 value1, Vector2 value2, float amount) inline static
Definition at line 255 of file Vector2.cs.
    {
        amount = ((amount > 1f) ? 1f : ((amount < 0f) ? 0f : amount));
        amount = amount * amount * (3f - 2f * amount);
        Vector2 result = default(Vector2);
        result.X = value1.X + (value2.X - value1.X) * amount;
        result.Y = value1.Y + (value2.Y - value1.Y) * amount;
        return result;
    }
References Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.NPC.AI(), Terraria.Projectile.AI_156_Think(), Terraria.Projectile.AI_171_HallowBossRainbowStreak(), Terraria.Main.DrawProjDirect(), and Terraria.Projectile.Kill().