Terraria: Microsoft.Xna.Framework.Vector2.DistanceSquared
DistanceSquared() [2/2]
static float Microsoft.Xna.Framework.Vector2.DistanceSquared (Vector2 value1, Vector2 value2) inline static
Definition at line 107 of file Vector2.cs.
    {
        float num = value1.X - value2.X;
        float num2 = value1.Y - value2.Y;
        return num * num + num2 * num2;
    }
References Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.GameContent.Events.DD2Event.CanRaiseGoblinsHere(), Terraria.Utils.DistanceSQ(), Terraria.Entity.DistanceSQ(), Terraria.NPC.FindClosestPlayer(), Terraria.Physics.BallCollision.GetCollisionPointForTile(), Terraria.MessageBuffer.GetData(), Terraria.Audio.SoundPlayer.Play(), Terraria.Audio.SoundPlayer.PlayLooped(), Terraria.GameContent.Events.DD2Event.RaiseGoblins(), Terraria.Utilities.NPCUtils.SearchForTarget(), Terraria.Utils.WithinRange(), and Terraria.Entity.WithinRange().