Terraria: ChatHelper.SendChatMessageFromClient
SendChatMessageFromClient()
static void ChatHelper.SendChatMessageFromClient (ChatMessage message) inline static
     {
         if (!message.IsConsumed)
         {
             NetPacket packet = NetTextModule.SerializeClientMessage(message);
             NetManager.Instance.SendToServer(packet);
         }
     }
References NetManager.Instance, ChatMessage.IsConsumed, NetManager.SendToServer(), and NetTextModule.SerializeClientMessage().
Referenced by Main.DoUpdate_HandleChat().