Terraria: ChatHelper.BroadcastChatMessageAs
BroadcastChatMessageAs()
static void ChatHelper.BroadcastChatMessageAs (byte messageAuthor, NetworkText text, Color color, int excludedPlayer = -1) inline static
     {
         if (Main.dedServ)
         {
             NetPacket packet = NetTextModule.SerializeServerMessage(text, color, messageAuthor);
             NetManager.Instance.Broadcast(packet, OnlySendToPlayersWhoAreLoggedIn, excludedPlayer);
         }
         else if (excludedPlayer != Main.myPlayer)
         {
             DisplayMessage(text, color, messageAuthor);
         }
     }
References NetManager.Broadcast(), Main.dedServ, DisplayMessage(), NetManager.Instance, Main.myPlayer, OnlySendToPlayersWhoAreLoggedIn(), and NetTextModule.SerializeServerMessage().
Referenced by BroadcastChatMessage(), and SayChatCommand.ProcessIncomingMessage().