Terraria: System.Reflection.Emit.DynamicMethod.Invoke
Invoke() [1/2]
override? object System.Reflection.Emit.DynamicMethod.Invoke (object? obj, BindingFlags invokeAttr, Binder? binder, object??[] parameters, CultureInfo? culture) inline
Definition at line 480 of file DynamicMethod.cs.
    {
        if ((CallingConvention & CallingConventions.VarArgs) == CallingConventions.VarArgs)
        {
            throw new NotSupportedException(SR.NotSupported_CallToVarArg);
        }
        GetMethodDescriptor();
        Signature signature = new Signature(m_methodHandle, m_parameterTypes, m_returnType, CallingConvention);
        int num = signature.Arguments.Length;
        int num2 = ((parameters != null) ? parameters.Length : 0);
        if (num != num2)
        {
            throw new TargetParameterCountException(SR.Arg_ParmCnt);
        }
        bool wrapExceptions = (invokeAttr & BindingFlags.DoNotWrapExceptions) == 0;
        StackAllocedArguments stackArgs = default(StackAllocedArguments);
        Span<object> arguments = default(Span<object>);
        if (num2 != 0)
        {
            arguments = CheckArguments(ref stackArgs, parameters, binder, invokeAttr, culture, signature);
        }
        object result = RuntimeMethodHandle.InvokeMethod(null, in arguments, signature, constructor: false, wrapExceptions);
        for (int i = 0; i < arguments.Length; i++)
        {
            parameters[i] = arguments[i];
        }
        GC.KeepAlive(this);
        return result;
    }
References System.SR.Arg_ParmCnt, System.Signature.Arguments, System.Reflection.MethodBase.CheckArguments(), System.culture, System.Reflection.Emit.DynamicMethod.GetMethodDescriptor(), System.RuntimeMethodHandle.InvokeMethod(), System.GC.KeepAlive(), System.Span< T >.Length, System.Reflection.Emit.DynamicMethod.m_methodHandle, System.Reflection.Emit.DynamicMethod.m_parameterTypes, System.Reflection.Emit.DynamicMethod.m_returnType, System.SR.NotSupported_CallToVarArg, and System.Reflection.Signature.