Terraria: System.Reflection.Emit.DynamicMethod.CreateDelegate
CreateDelegate() [2/2]
override Delegate System.Reflection.Emit.DynamicMethod.CreateDelegate (Type delegateType, object? target) inline sealed virtual
Reimplemented from System.Reflection.MethodInfo.
Definition at line 420 of file DynamicMethod.cs.
    {
        if (m_restrictedSkipVisibility)
        {
            GetMethodDescriptor();
            IRuntimeMethodInfo methodHandle = m_methodHandle;
            RuntimeHelpers.CompileMethod(methodHandle?.Value ?? RuntimeMethodHandleInternal.EmptyHandle);
            GC.KeepAlive(methodHandle);
        }
        MulticastDelegate multicastDelegate = (MulticastDelegate)Delegate.CreateDelegateNoSecurityCheck(delegateType, target, GetMethodDescriptor());
        multicastDelegate.StoreDynamicMethod(GetMethodInfo());
        return multicastDelegate;
    }
References System.Runtime.CompilerServices.RuntimeHelpers.CompileMethod(), System.Delegate.CreateDelegateNoSecurityCheck(), System.RuntimeMethodHandleInternal.EmptyHandle, System.Reflection.Emit.DynamicMethod.GetMethodDescriptor(), System.Reflection.Emit.DynamicMethod.GetMethodInfo(), System.GC.KeepAlive(), System.Reflection.Emit.DynamicMethod.m_methodHandle, System.Reflection.Emit.DynamicMethod.m_restrictedSkipVisibility, and System.MulticastDelegate.StoreDynamicMethod().