Terraria: System.Reflection.Emit.DynamicMethod.GetMethodDescriptor
GetMethodDescriptor()
RuntimeMethodHandle System.Reflection.Emit.DynamicMethod.GetMethodDescriptor () inline package
Definition at line 434 of file DynamicMethod.cs.
    {
        if (m_methodHandle == null)
        {
            lock (this)
            {
                if (m_methodHandle == null)
                {
                    if (m_DynamicILInfo != null)
                    {
                        m_DynamicILInfo.GetCallableMethod(m_module, this);
                    }
                    else
                    {
                        if (m_ilGenerator == null || m_ilGenerator.ILOffset == 0)
{
                            throw new InvalidOperationException(SR.Format(SR.InvalidOperation_BadEmptyMethodBody, Name));
                        }
                        m_ilGenerator.GetCallableMethod(m_module, this);
                    }
                }
            }
        }
        return new RuntimeMethodHandle(m_methodHandle);
    }
References System.SR.Format(), System.Reflection.Emit.DynamicILGenerator.GetCallableMethod(), System.Reflection.Emit.DynamicILInfo.GetCallableMethod(), System.Reflection.Emit.ILGenerator.ILOffset, System.SR.InvalidOperation_BadEmptyMethodBody, System.Reflection.Emit.DynamicMethod.m_DynamicILInfo, System.Reflection.Emit.DynamicMethod.m_ilGenerator, System.Reflection.Emit.DynamicMethod.m_methodHandle, System.Reflection.Emit.DynamicMethod.m_module, and System.Reflection.Emit.DynamicMethod.Name.
Referenced by System.Reflection.Emit.DynamicMethod.CreateDelegate(), System.Reflection.Emit.DynamicMethod.CreateDelegate(), System.Reflection.Emit.DynamicMethod.Invoke(), and System.Reflection.Emit.DynamicResolver.ResolveToken().