Terraria: System.Reflection.Emit.DynamicMethod.Init
Init()
void System.Reflection.Emit.DynamicMethod.Init (string name, MethodAttributes attributes, CallingConventions callingConvention, Type returnType, Type[] signature, Type owner, Module m, bool skipVisibility, bool transparentMethod) inline private
Definition at line 335 of file DynamicMethod.cs.
    {
        CheckConsistency(attributes, callingConvention);
        if (signature != null)
        {
            m_parameterTypes = new RuntimeType[signature.Length];
            for (int i = 0; i < signature.Length; i++)
            {
                if (signature[i] == null)
                {
                    throw new ArgumentException(SR.Arg_InvalidTypeInSignature);
                }
                m_parameterTypes[i] = signature[i].UnderlyingSystemType as RuntimeType;
                if (m_parameterTypes[i] == null || m_parameterTypes[i] == typeof(void))
                {
                    throw new ArgumentException(SR.Arg_InvalidTypeInSignature);
                }
            }
        }
        else
        {
            m_parameterTypes = Array.Empty<RuntimeType>();
        }
        m_returnType = ((returnType == null) ? ((RuntimeType)typeof(void)) : (returnType.UnderlyingSystemType as RuntimeType));
        if (m_returnType == null)
        {
            throw new NotSupportedException(SR.Arg_InvalidTypeInRetType);
        }
        if (transparentMethod)
        {
            m_module = GetDynamicMethodsModule();
            if (skipVisibility)
            {
                m_restrictedSkipVisibility = true;
            }
        }
        else
        {
            if (m != null)
            {
                m_module = m.ModuleHandle.GetRuntimeModule();
            }
            else
            {
                RuntimeType runtimeType = null;
                if (owner != null)
                {
                    runtimeType = owner.UnderlyingSystemType as RuntimeType;
                }
                if (runtimeType != null)
                {
                    if (runtimeType.HasElementType || runtimeType.ContainsGenericParameters || runtimeType.IsGenericParameter || runtimeType.IsInterface)
                    {
                        throw new ArgumentException(SR.Argument_InvalidTypeForDynamicMethod);
                    }
                    m_typeOwner = runtimeType;
                    m_module = runtimeType.GetRuntimeModule();
                }
            }
            m_skipVisibility = skipVisibility;
        }
        m_ilGenerator = null;
        m_fInitLocals = true;
        m_methodHandle = null;
        if (name == null)
        {
            throw new ArgumentNullException("name");
        }
        m_dynMethod = new RTDynamicMethod(this, name, attributes, callingConvention);
    }
References System.SR.Arg_InvalidTypeInRetType, System.SR.Arg_InvalidTypeInSignature, System.SR.Argument_InvalidTypeForDynamicMethod, System.Reflection.Emit.DynamicMethod.CheckConsistency(), System.RuntimeType.ContainsGenericParameters, System.Reflection.Emit.DynamicMethod.GetDynamicMethodsModule(), System.ModuleHandle.GetRuntimeModule(), System.RuntimeType.GetRuntimeModule(), System.Type.HasElementType, System.RuntimeType.IsGenericParameter, System.Type.IsInterface, System.Reflection.Emit.DynamicMethod.m_dynMethod, System.Reflection.Emit.DynamicMethod.m_fInitLocals, System.Reflection.Emit.DynamicMethod.m_ilGenerator, System.Reflection.Emit.DynamicMethod.m_methodHandle, System.Reflection.Emit.DynamicMethod.m_module, System.Reflection.Emit.DynamicMethod.m_parameterTypes, System.Reflection.Emit.DynamicMethod.m_restrictedSkipVisibility, System.Reflection.Emit.DynamicMethod.m_returnType, System.Reflection.Emit.DynamicMethod.m_skipVisibility, System.Reflection.Emit.DynamicMethod.m_typeOwner, System.Reflection.Module.ModuleHandle, and System.Type.UnderlyingSystemType.
Referenced by System.Reflection.Emit.DynamicMethod.DynamicMethod(), System.Reflection.Emit.DynamicMethod.DynamicMethod(), System.Reflection.Emit.DynamicMethod.DynamicMethod(), System.Reflection.Emit.DynamicMethod.DynamicMethod(), System.Reflection.Emit.DynamicMethod.DynamicMethod(), System.Reflection.Emit.DynamicMethod.DynamicMethod(), System.Reflection.Emit.DynamicMethod.DynamicMethod(), and System.Reflection.Emit.DynamicMethod.DynamicMethod().