Terraria: Internal.Cryptography.Pal.X509Pal.DecodePublicKey
DecodePublicKey()
AsymmetricAlgorithm Internal.Cryptography.Pal.X509Pal.DecodePublicKey (Oid oid, byte[] encodedKeyValue, byte[] encodedParameters, ICertificatePal certificatePal) inline
Implements Internal.Cryptography.Pal.IX509Pal.
Definition at line 229 of file X509Pal.cs.
    {
        switch (global::Interop.Crypt32.FindOidInfo(global::Interop.Crypt32.CryptOidInfoKeyType.CRYPT_OID_INFO_OID_KEY, oid.Value, OidGroup.PublicKeyAlgorithm, fallBackToAllGroups: true).AlgId)
        {
        case 9216:
        case 41984:
        {
            byte[] keyBlob2 = DecodeKeyBlob(CryptDecodeObjectStructType.CNG_RSA_PUBLIC_KEY_BLOB, encodedKeyValue);
            CngKey key = CngKey.Import(keyBlob2, CngKeyBlobFormat.GenericPublicBlob);
            return new RSACng(key);
        }
        case 8704:
        {
            byte[] keyBlob = ConstructDSSPublicKeyCspBlob(encodedKeyValue, encodedParameters);
            DSACryptoServiceProvider dSACryptoServiceProvider = new DSACryptoServiceProvider();
            dSACryptoServiceProvider.ImportCspBlob(keyBlob);
            return dSACryptoServiceProvider;
        }
        default:
            throw new NotSupportedException(System.SR.NotSupported_KeyAlgorithm);
        }
    }
References Internal.Cryptography.Pal.X509Pal.ConstructDSSPublicKeyCspBlob(), Internal.Cryptography.Pal.X509Pal.DecodeKeyBlob(), System.Security.Cryptography.CngKeyBlobFormat.GenericPublicBlob, System.Security.Cryptography.CngKey.Import(), System.Security.Cryptography.DSACryptoServiceProvider.ImportCspBlob(), System.key, System.SR.NotSupported_KeyAlgorithm, and System.Security.Cryptography.Oid.Value.