Terraria: Internal.Cryptography.Pal.X509Pal.ConstructDSSPublicKeyCspBlob
ConstructDSSPublicKeyCspBlob()
static byte[] Internal.Cryptography.Pal.X509Pal.ConstructDSSPublicKeyCspBlob (byte[] encodedKeyValue, byte[] encodedParameters) inline static private
Definition at line 352 of file X509Pal.cs.
    {
        byte[] array = DecodeDssKeyValue(encodedKeyValue);
        DecodeDssParameters(encodedParameters, out var p, out var q, out var g);
        int num = p.Length;
        if (num == 0)
        {
            throw (-2146893803).ToCryptographicException();
        }
        int capacity = 16 + num + 20 + num + num + 24;
        MemoryStream memoryStream = new MemoryStream(capacity);
        BinaryWriter binaryWriter = new BinaryWriter(memoryStream);
        binaryWriter.Write((byte)6);
        binaryWriter.Write((byte)2);
        binaryWriter.Write((short)0);
        binaryWriter.Write(8704u);
        binaryWriter.Write(827544388);
        binaryWriter.Write(num * 8);
        binaryWriter.Write(p);
        int num2 = q.Length;
        if (num2 == 0 || num2 > 20)
        {
            throw (-2146893803).ToCryptographicException();
        }
        binaryWriter.Write(q);
        if (20 > num2)
        {
            binaryWriter.Write(new byte[20 - num2]);
        }
        num2 = g.Length;
        if (num2 == 0 || num2 > num)
        {
            throw (-2146893803).ToCryptographicException();
        }
        binaryWriter.Write(g);
        if (num > num2)
        {
            binaryWriter.Write(new byte[num - num2]);
        }
        num2 = array.Length;
        if (num2 == 0 || num2 > num)
        {
            throw (-2146893803).ToCryptographicException();
        }
        binaryWriter.Write(array);
        if (num > num2)
        {
            binaryWriter.Write(new byte[num - num2]);
        }
        binaryWriter.Write(uint.MaxValue);
        binaryWriter.Write(new byte[20]);
        return memoryStream.ToArray();
    }
References System.array, System.capacity, Internal.Cryptography.Pal.X509Pal.DecodeDssKeyValue(), Internal.Cryptography.Pal.X509Pal.DecodeDssParameters(), System.IO.MemoryStream.ToArray(), and System.IO.BinaryWriter.Write().
Referenced by Internal.Cryptography.Pal.X509Pal.DecodePublicKey().