Terraria: Internal.Cryptography.Pal.X509Pal.DecodeECPublicKey< TAlgorithm >
DecodeECPublicKey< TAlgorithm >()
static TAlgorithm Internal.Cryptography.Pal.X509Pal.DecodeECPublicKey< TAlgorithm > (CertificatePal certificatePal, Func< CngKey, TAlgorithm > factory, Action< TAlgorithm, ECParameters > import, CryptImportPublicKeyInfoFlags importFlags = CryptImportPublicKeyInfoFlags::NONE) inline static private
Type Constraints
TAlgorithm : AsymmetricAlgorithm
TAlgorithm : new()
Definition at line 252 of file X509Pal.cs.
                                                                                                                                                                                                                                                                       : AsymmetricAlgorithm, new()
    {
        TAlgorithm val;
        using (Microsoft.Win32.SafeHandles.SafeBCryptKeyHandle safeBCryptKeyHandle = ImportPublicKeyInfo(certificatePal.CertContext, importFlags))
        {
            string curveName = GetCurveName(safeBCryptKeyHandle);
            if (curveName == null)
            {
                CngKeyBlobFormat cngKeyBlobFormat = ((!HasExplicitParameters(safeBCryptKeyHandle)) ? CngKeyBlobFormat.EccPublicBlob : CngKeyBlobFormat.EccFullPublicBlob);
                byte[] keyBlob = ExportKeyBlob(safeBCryptKeyHandle, cngKeyBlobFormat);
                using CngKey arg = CngKey.Import(keyBlob, cngKeyBlobFormat);
                val = factory(arg);
            }
            else
            {
                CngKeyBlobFormat cngKeyBlobFormat = CngKeyBlobFormat.EccPublicBlob;
                byte[] keyBlob = ExportKeyBlob(safeBCryptKeyHandle, cngKeyBlobFormat);
                ECParameters ecParams = default(ECParameters);
                ExportNamedCurveParameters(ref ecParams, keyBlob, includePrivateParameters: false);
                ecParams.Curve = ECCurve.CreateFromFriendlyName(curveName);
                val = new TAlgorithm();
                import(val, ecParams);
            }
        }
        return val;
    }
References Internal.Cryptography.Pal.CertificatePal.CertContext, System.Security.Cryptography.ECCurve.CreateFromFriendlyName(), System.Security.Cryptography.CngKeyBlobFormat.EccFullPublicBlob, System.Security.Cryptography.CngKeyBlobFormat.EccPublicBlob, Internal.Cryptography.Pal.X509Pal.ExportKeyBlob(), Internal.Cryptography.Pal.X509Pal.ExportNamedCurveParameters(), Internal.Cryptography.Pal.X509Pal.GetCurveName(), Internal.Cryptography.Pal.X509Pal.HasExplicitParameters(), System.Security.Cryptography.CngKey.Import(), and Internal.Cryptography.Pal.X509Pal.ImportPublicKeyInfo().