Terraria: Terraria.UI.IngameFancyUI.Draw
Draw()
static bool Terraria.UI.IngameFancyUI.Draw (SpriteBatch spriteBatch, GameTime gameTime) inline static
Definition at line 180 of file IngameFancyUI.cs.
    {
        bool result = false;
        if (Main.InGameUI.CurrentState is UIVirtualKeyboard && UIVirtualKeyboard.KeyboardContext > 0)
        {
            if (!Main.inFancyUI)
            {
                Main.InGameUI.SetState(null);
            }
            if (Main.screenWidth >= 1705 || !PlayerInput.UsingGamepad)
            {
                result = true;
            }
        }
        if (!Main.gameMenu)
        {
            Main.mouseText = false;
            if (Main.InGameUI != null && Main.InGameUI.IsElementUnderMouse())
            {
                Main.player[Main.myPlayer].mouseInterface = true;
            }
            Main.instance.GUIBarsDraw();
            if (Main.InGameUI.CurrentState is UIVirtualKeyboard && UIVirtualKeyboard.KeyboardContext > 0)
            {
                Main.instance.GUIChatDraw();
            }
            if (!Main.inFancyUI)
            {
                Main.InGameUI.SetState(null);
            }
            Main.instance.DrawMouseOver();
            Main.DrawCursor(Main.DrawThickCursor());
        }
        return result;
    }
References Terraria.Main.DrawCursor(), Terraria.Main.DrawThickCursor(), Terraria.Main.gameMenu, Terraria.Main.inFancyUI, Terraria.Main.InGameUI, Terraria.Main.instance, Terraria.GameContent.UI.States.UIVirtualKeyboard.KeyboardContext, Terraria.Main.myPlayer, Terraria.Main.player, Terraria.Main.screenWidth, and Terraria.GameInput.PlayerInput.UsingGamepad.
Referenced by Terraria.Main.DrawInterface_12_IngameFancyUI().