Terraria: Terraria.UI.IngameFancyUI.Close
Close()
static void Terraria.UI.IngameFancyUI.Close () inline static
    {
        Main.inFancyUI = false;
        SoundEngine.PlaySound(11);
        bool flag = !Main.gameMenu;
        bool flag2 = !(Main.InGameUI.CurrentState is UIVirtualKeyboard);
        bool flag3 = false;
        int keyboardContext = UIVirtualKeyboard.KeyboardContext;
        if ((uint)(keyboardContext - 2) <= 1u)
        {
            flag3 = true;
        }
        if (flag && !(flag2 || flag3))
        {
            flag = false;
        }
        if (flag)
        {
            Main.playerInventory = true;
        }
        if (!Main.gameMenu && Main.InGameUI.CurrentState is UIEmotesMenu)
        {
            Main.playerInventory = false;
        }
        Main.LocalPlayer.releaseInventory = false;
        Main.InGameUI.SetState(null);
        UILinkPointNavigator.Shortcuts.FANCYUI_SPECIAL_INSTRUCTIONS = 0;
    }
References Terraria.Main.gameMenu, Terraria.Main.InGameUI, Terraria.GameContent.UI.States.UIVirtualKeyboard.KeyboardContext, and Terraria.Audio.SoundEngine.PlaySound().
Referenced by Terraria.GameContent.UI.States.UIBestiaryTest.Click_GoBack(), Terraria.GameContent.UI.States.UIVirtualKeyboard.DrawSelf(), Terraria.GameContent.UI.Elements.UICreativeInfiniteItemsDisplay.EscapeVirtualKeyboard(), Terraria.Initializers.UILinksInitializer.FancyExit(), Terraria.GameContent.UI.States.UIAchievementsMenu.GoBackClick(), Terraria.GameContent.UI.States.UIEmotesMenu.GoBackClick(), Terraria.GameContent.UI.States.UIManageControls.GoBackClick(), Terraria.GameContent.UI.Elements.UICreativeInfiniteItemsDisplay.GoBackHere(), Terraria.GameContent.UI.States.UIResourcePackSelectionMenu.HandleBackButtonUsage(), Terraria.GameContent.UI.Elements.EmoteButton.LeftClick(), Terraria.Player.ToggleCreativeMenu(), Terraria.Player.ToggleInv(), and Terraria.GameContent.UI.States.UIVirtualKeyboard.TryEscapingMenu().