Terraria: System.Security.Cryptography.CngKeyLite.GenerateNewExportableKey
GenerateNewExportableKey() [2/3]
static SafeNCryptKeyHandle System.Security.Cryptography.CngKeyLite.GenerateNewExportableKey (string algorithm, ref ECCurve explicitCurve) inline static package
Definition at line 204 of file CngKeyLite.cs.
    {
        global::Interop.NCrypt.ErrorCode errorCode = global::Interop.NCrypt.NCryptCreatePersistedKey(s_microsoftSoftwareProviderHandle, out var phKey, algorithm, null, 0, CngKeyCreationOptions.None);
        if (errorCode != 0)
        {
            throw errorCode.ToCryptographicException();
        }
        SetExportable(phKey);
        byte[] primeCurveParameterBlob = ECCng.GetPrimeCurveParameterBlob(ref explicitCurve);
        SetProperty(phKey, "ECCParameters", primeCurveParameterBlob);
        errorCode = global::Interop.NCrypt.NCryptFinalizeKey(phKey, 0);
        if (errorCode != 0)
        {
            throw errorCode.ToCryptographicException();
        }
        return phKey;
    }
References System.Security.Cryptography.ECCng.GetPrimeCurveParameterBlob(), System.Security.Cryptography.CngKeyLite.s_microsoftSoftwareProviderHandle, System.Security.Cryptography.CngKeyLite.SetExportable(), and System.Security.Cryptography.CngKeyLite.SetProperty().