Terraria: System.Security.Cryptography.CngKeyLite.GenerateNewExportableKey
GenerateNewExportableKey() [1/3]
static SafeNCryptKeyHandle System.Security.Cryptography.CngKeyLite.GenerateNewExportableKey (string algorithm, int keySize) inline static package
Definition at line 170 of file CngKeyLite.cs.
    {
        global::Interop.NCrypt.ErrorCode errorCode = global::Interop.NCrypt.NCryptCreatePersistedKey(s_microsoftSoftwareProviderHandle, out var phKey, algorithm, null, 0, CngKeyCreationOptions.None);
        if (errorCode != 0)
        {
            throw errorCode.ToCryptographicException();
        }
        SetExportable(phKey);
        SetKeyLength(phKey, keySize);
        errorCode = global::Interop.NCrypt.NCryptFinalizeKey(phKey, 0);
        if (errorCode != 0)
        {
            throw errorCode.ToCryptographicException();
        }
        return phKey;
    }
References System.Security.Cryptography.CngKeyLite.s_microsoftSoftwareProviderHandle, System.Security.Cryptography.CngKeyLite.SetExportable(), and System.Security.Cryptography.CngKeyLite.SetKeyLength().
Referenced by System.Security.Cryptography.ECCngKey.GenerateKey(), System.Security.Cryptography.DSAImplementation.DSACng.GetDuplicatedKeyHandle(), System.Security.Cryptography.RSAImplementation.RSACng.GetDuplicatedKeyHandle(), and System.Security.Cryptography.ECCngKey.GetDuplicatedKeyHandle().