Terraria: System.Security.Cryptography.CngKeyLite.GetPropertyAsString
GetPropertyAsString()
static unsafe string System.Security.Cryptography.CngKeyLite.GetPropertyAsString (SafeNCryptHandle ncryptHandle, string propertyName, CngPropertyOptions options) inline static package
Definition at line 297 of file CngKeyLite.cs.
    {
        byte[] property = GetProperty(ncryptHandle, propertyName, options);
        if (property == null)
        {
            return null;
        }
        if (property.Length == 0)
        {
            return string.Empty;
        }
        fixed (byte* ptr = &property[0])
        {
            return Marshal.PtrToStringUni((IntPtr)ptr);
        }
    }
References System.Security.Cryptography.CngKeyLite.GetProperty(), System.options, and System.Runtime.InteropServices.Marshal.PtrToStringUni().
Referenced by System.Security.Cryptography.ECDiffieHellmanImplementation.ECDiffieHellmanCng.AcceptImport(), System.Security.Cryptography.ECDsaImplementation.ECDsaCng.AcceptImport(), System.Security.Cryptography.ECDiffieHellmanImplementation.ECDiffieHellmanCng.DeriveSecretAgreementHandle(), System.Security.Cryptography.CngPkcs8.Pkcs8Response.GetAlgorithmGroup(), and System.Security.Cryptography.CngKeyLite.GetCurveName().