Terraria: System.Security.Cryptography.CngKeyLite.ImportKeyBlob
ImportKeyBlob() [2/2]
static unsafe SafeNCryptKeyHandle System.Security.Cryptography.CngKeyLite.ImportKeyBlob (string blobType, ReadOnlySpan< byte > keyBlob, bool encrypted = false, ReadOnlySpan< char > password = default(ReadOnlySpan<char>)) inline static package
Definition at line 14 of file CngKeyLite.cs.
    {
        global::Interop.NCrypt.ErrorCode errorCode;
        SafeNCryptKeyHandle phKey;
        if (encrypted)
        {
            using SafeUnicodeStringHandle safeUnicodeStringHandle = new SafeUnicodeStringHandle(password);
            global::Interop.NCrypt.NCryptBuffer* ptr = stackalloc global::Interop.NCrypt.NCryptBuffer[1];
            *ptr = new global::Interop.NCrypt.NCryptBuffer
            {
                BufferType = global::Interop.NCrypt.BufferType.PkcsSecret,
                cbBuffer = checked(2 * (password.Length + 1)),
                pvBuffer = safeUnicodeStringHandle.DangerousGetHandle()
            };
            if (ptr->pvBuffer == IntPtr.Zero)
            {
                ptr->cbBuffer = 0;
            }
            global::Interop.NCrypt.NCryptBufferDesc nCryptBufferDesc = default(global::Interop.NCrypt.NCryptBufferDesc);
            nCryptBufferDesc.cBuffers = 1;
            nCryptBufferDesc.pBuffers = (IntPtr)ptr;
            nCryptBufferDesc.ulVersion = 0;
            global::Interop.NCrypt.NCryptBufferDesc pParameterList = nCryptBufferDesc;
            errorCode = global::Interop.NCrypt.NCryptImportKey(s_microsoftSoftwareProviderHandle, IntPtr.Zero, blobType, ref pParameterList, out phKey, ref MemoryMarshal.GetReference(keyBlob), keyBlob.Length, 0);
        }
        else
        {
            errorCode = global::Interop.NCrypt.NCryptImportKey(s_microsoftSoftwareProviderHandle, IntPtr.Zero, blobType, IntPtr.Zero, out phKey, ref MemoryMarshal.GetReference(keyBlob), keyBlob.Length, 0);
        }
        if (errorCode != 0)
        {
            throw errorCode.ToCryptographicException();
        }
        SetExportable(phKey);
        return phKey;
    }
References System.ReadOnlySpan< T >.Length, System.Security.Cryptography.CngKeyLite.s_microsoftSoftwareProviderHandle, System.Security.Cryptography.CngKeyLite.SetExportable(), and System.IntPtr.Zero.
Referenced by System.Security.Cryptography.ECDiffieHellmanImplementation.ECDiffieHellmanCng.ImportFullKeyBlob(), System.Security.Cryptography.ECDsaImplementation.ECDsaCng.ImportFullKeyBlob(), System.Security.Cryptography.DSAImplementation.DSACng.ImportKeyBlob(), System.Security.Cryptography.ECDiffieHellmanImplementation.ECDiffieHellmanCng.ImportKeyBlob(), System.Security.Cryptography.ECDsaImplementation.ECDsaCng.ImportKeyBlob(), System.Security.Cryptography.RSAImplementation.RSACng.ImportKeyBlob(), System.Security.Cryptography.CngPkcs8.ImportPkcs8(), and System.Security.Cryptography.CngPkcs8.ImportPkcs8().