Terraria: System.Security.Cryptography.CngKeyLite.GetKeyLength
GetKeyLength()
static int System.Security.Cryptography.CngKeyLite.GetKeyLength (SafeNCryptKeyHandle keyHandle) inline static package
Definition at line 241 of file CngKeyLite.cs.
    {
        int result = 0;
        global::Interop.NCrypt.ErrorCode errorCode = global::Interop.NCrypt.NCryptGetIntProperty(keyHandle, "PublicKeyLength", ref result);
        if (errorCode != 0)
        {
            errorCode = global::Interop.NCrypt.NCryptGetIntProperty(keyHandle, "Length", ref result);
        }
        if (errorCode != 0)
        {
            throw errorCode.ToCryptographicException();
        }
        return result;
    }
Referenced by System.Security.Cryptography.ECDiffieHellmanImplementation.ECDiffieHellmanCng.DeriveSecretAgreementHandle(), System.Security.Cryptography.ECCngKey.GenerateKey(), System.Security.Cryptography.ECCngKey.SetHandle(), System.Security.Cryptography.DSAImplementation.DSACng.SetKeyHandle(), and System.Security.Cryptography.RSAImplementation.RSACng.SetKeyHandle().