Terraria: System.IO.Strategies.Net5CompatFileStreamStrategy.CopyToAsync
CopyToAsync() [4/4]
override Task System.IO.Strategies.Net5CompatFileStreamStrategy.CopyToAsync (Stream destination, int bufferSize, CancellationToken cancellationToken) inline virtual
Reimplemented from System.IO.Stream.
Definition at line 1171 of file Net5CompatFileStreamStrategy.cs.
    {
        if (!_useAsyncIO)
        {
            return base.CopyToAsync(destination, bufferSize, cancellationToken);
        }
        if (_fileHandle.IsClosed)
        {
            ThrowHelper.ThrowObjectDisposedException_FileClosed();
        }
        if (!CanRead)
        {
            ThrowHelper.ThrowNotSupportedException_UnreadableStream();
        }
        if (cancellationToken.IsCancellationRequested)
        {
            return Task.FromCanceled<int>(cancellationToken);
        }
        return AsyncModeCopyToAsync(destination, bufferSize, cancellationToken);
    }
References System.IO.Strategies.Net5CompatFileStreamStrategy._fileHandle, System.IO.Strategies.Net5CompatFileStreamStrategy._useAsyncIO, System.IO.Strategies.Net5CompatFileStreamStrategy.AsyncModeCopyToAsync(), System.cancellationToken, System.IO.Strategies.Net5CompatFileStreamStrategy.CanRead, System.destination, System.Threading.Tasks.Task< TResult >.FromCanceled(), System.Runtime.InteropServices.SafeHandle.IsClosed, System.ThrowHelper.ThrowNotSupportedException_UnreadableStream(), and System.ThrowHelper.ThrowObjectDisposedException_FileClosed().