Terraria: UIItemIcon.DrawSelf
DrawSelf()
override void UIItemIcon.DrawSelf (SpriteBatch spriteBatch) inline protected virtual
Reimplemented from UIElement.
     {
         CalculatedStyle dimensions = GetDimensions();
         ItemSlot.DrawItemIcon(_item, 31, spriteBatch, dimensions.Center(), _item.scale, 32f, _blackedOut ? Color.Black : Color.White);
     }
References _blackedOut, _item, CalculatedStyle.Center(), Color, ItemSlot.DrawItemIcon(), UIElement.GetDimensions(), and Item.scale.