Terraria: System.IO.Strategies.Net5CompatFileStreamStrategy.ReadSpan
ReadSpan()
int System.IO.Strategies.Net5CompatFileStreamStrategy.ReadSpan (Span< byte > destination) inline private
Definition at line 743 of file Net5CompatFileStreamStrategy.cs.
    {
        bool flag = false;
        int num = _readLength - _readPos;
        if (num == 0)
        {
            if (!CanRead)
            {
                ThrowHelper.ThrowNotSupportedException_UnreadableStream();
            }
            if (_writePos > 0)
            {
                FlushWriteBuffer();
            }
            if (!CanSeek || destination.Length >= _bufferLength)
            {
                num = ReadNative(destination);
                _readPos = 0;
                _readLength = 0;
                return num;
            }
            num = ReadNative(GetBuffer());
            if (num == 0)
            {
                return 0;
            }
            flag = num < _bufferLength;
            _readPos = 0;
            _readLength = num;
        }
        if (num > destination.Length)
        {
            num = destination.Length;
        }
        new ReadOnlySpan<byte>(GetBuffer(), _readPos, num).CopyTo(destination);
        _readPos += num;
        if (_fileHandle.CanSeek && num < destination.Length && !flag)
        {
            int num2 = ReadNative(destination.Slice(num));
            num += num2;
            _readPos = 0;
            _readLength = 0;
        }
        return num;
    }
References System.IO.Strategies.Net5CompatFileStreamStrategy._bufferLength, System.IO.Strategies.Net5CompatFileStreamStrategy._fileHandle, System.IO.Strategies.Net5CompatFileStreamStrategy._readLength, System.IO.Strategies.Net5CompatFileStreamStrategy._readPos, System.IO.Strategies.Net5CompatFileStreamStrategy._writePos, System.IO.Strategies.Net5CompatFileStreamStrategy.CanRead, Microsoft.Win32.SafeHandles.SafeFileHandle.CanSeek, System.IO.Strategies.Net5CompatFileStreamStrategy.CanSeek, System.ReadOnlySpan< T >.CopyTo(), System.destination, System.IO.Strategies.Net5CompatFileStreamStrategy.FlushWriteBuffer(), System.IO.Strategies.Net5CompatFileStreamStrategy.GetBuffer(), System.IO.Strategies.Net5CompatFileStreamStrategy.ReadNative(), and System.ThrowHelper.ThrowNotSupportedException_UnreadableStream().
Referenced by System.IO.Strategies.Net5CompatFileStreamStrategy.Read(), and System.IO.Strategies.Net5CompatFileStreamStrategy.Read().