Terraria: System.IO.Strategies.Net5CompatFileStreamStrategy.WriteAsyncInternal
WriteAsyncInternal()
ValueTask System.IO.Strategies.Net5CompatFileStreamStrategy.WriteAsyncInternal (ReadOnlyMemory< byte > source, CancellationToken cancellationToken) inline private
Definition at line 1058 of file Net5CompatFileStreamStrategy.cs.
    {
        if (!CanWrite)
        {
            ThrowHelper.ThrowNotSupportedException_UnwritableStream();
        }
        bool flag = false;
        if (_fileHandle.CanSeek)
        {
            if (_writePos == 0)
            {
                if (_readPos < _readLength)
                {
                    FlushReadBuffer();
                }
                _readPos = 0;
                _readLength = 0;
            }
            int num = _bufferLength - _writePos;
            if (source.Length < _bufferLength && !HasActiveBufferOperation && source.Length <= num)
            {
                source.Span.CopyTo(new Span<byte>(GetBuffer(), _writePos, source.Length));
                _writePos += source.Length;
                flag = true;
                if (source.Length != num)
                {
                    return default(ValueTask);
                }
            }
        }
        Task task = null;
        if (_writePos > 0)
        {
            task = FlushWriteAsync(cancellationToken);
            if (flag || task.IsFaulted || task.IsCanceled)
            {
                return new ValueTask(task);
            }
        }
        Task task2 = WriteAsyncInternalCore(source, cancellationToken);
        return new ValueTask((task == null || task.Status == TaskStatus.RanToCompletion) ? task2 : ((task2.Status == TaskStatus.RanToCompletion) ? task : Task.WhenAll(task, task2)));
    }
References System.IO.Strategies.Net5CompatFileStreamStrategy._bufferLength, System.IO.Strategies.Net5CompatFileStreamStrategy._fileHandle, System.IO.Strategies.Net5CompatFileStreamStrategy._readLength, System.IO.Strategies.Net5CompatFileStreamStrategy._readPos, System.IO.Strategies.Net5CompatFileStreamStrategy._writePos, System.cancellationToken, Microsoft.Win32.SafeHandles.SafeFileHandle.CanSeek, System.IO.Strategies.Net5CompatFileStreamStrategy.CanWrite, System.IO.Strategies.Net5CompatFileStreamStrategy.FlushReadBuffer(), System.IO.Strategies.Net5CompatFileStreamStrategy.FlushWriteAsync(), System.IO.Strategies.Net5CompatFileStreamStrategy.GetBuffer(), System.IO.Strategies.Net5CompatFileStreamStrategy.HasActiveBufferOperation, System.source, System.task, System.ThrowHelper.ThrowNotSupportedException_UnwritableStream(), System.Threading.Tasks.Task< TResult >.WhenAll(), and System.IO.Strategies.Net5CompatFileStreamStrategy.WriteAsyncInternalCore().
Referenced by System.IO.Strategies.Net5CompatFileStreamStrategy.BeginWrite(), System.IO.Strategies.Net5CompatFileStreamStrategy.Write(), System.IO.Strategies.Net5CompatFileStreamStrategy.WriteAsync(), and System.IO.Strategies.Net5CompatFileStreamStrategy.WriteAsync().