Terraria: System.IO.Strategies.Net5CompatFileStreamStrategy.FlushInternalBuffer
FlushInternalBuffer()
void System.IO.Strategies.Net5CompatFileStreamStrategy.FlushInternalBuffer () inline private
Definition at line 485 of file Net5CompatFileStreamStrategy.cs.
    {
        if (_writePos > 0)
        {
            FlushWriteBuffer();
        }
        else if (_readPos < _readLength && CanSeek)
        {
            FlushReadBuffer();
        }
    }
References System.IO.Strategies.Net5CompatFileStreamStrategy._readLength, System.IO.Strategies.Net5CompatFileStreamStrategy._readPos, System.IO.Strategies.Net5CompatFileStreamStrategy._writePos, System.IO.Strategies.Net5CompatFileStreamStrategy.CanSeek, System.IO.Strategies.Net5CompatFileStreamStrategy.FlushReadBuffer(), and System.IO.Strategies.Net5CompatFileStreamStrategy.FlushWriteBuffer().
Referenced by System.IO.Strategies.Net5CompatFileStreamStrategy.Flush(), and System.IO.Strategies.Net5CompatFileStreamStrategy.FlushAsync().