Terraria: System.IO.Strategies.Net5CompatFileStreamStrategy.Net5CompatFileStreamStrategy
Net5CompatFileStreamStrategy() [2/2]
System.IO.Strategies.Net5CompatFileStreamStrategy.Net5CompatFileStreamStrategy (string path, FileMode mode, FileAccess access, FileShare share, int bufferSize, FileOptions options, long preallocationSize) inline package
Definition at line 265 of file Net5CompatFileStreamStrategy.cs.
    {
        string fullPath = Path.GetFullPath(path);
        _access = access;
        _bufferLength = bufferSize;
        if ((options & FileOptions.Asynchronous) != 0)
        {
            _useAsyncIO = true;
        }
        _fileHandle = SafeFileHandle.Open(fullPath, mode, access, share, options, preallocationSize);
        try
        {
            Init(mode, path, options);
        }
        catch
        {
            _fileHandle.Dispose();
            _fileHandle = null;
            throw;
        }
    }
References System.IO.Strategies.Net5CompatFileStreamStrategy._access, System.IO.Strategies.Net5CompatFileStreamStrategy._bufferLength, System.IO.Strategies.Net5CompatFileStreamStrategy._fileHandle, System.IO.Strategies.Net5CompatFileStreamStrategy._useAsyncIO, System.Runtime.InteropServices.SafeHandle.Dispose(), System.IO.Path.GetFullPath(), System.IO.Strategies.Net5CompatFileStreamStrategy.Init(), Microsoft.Win32.SafeHandles.SafeFileHandle.Open(), and System.options.