Terraria: System.IO.Strategies.Net5CompatFileStreamStrategy.DisposeAsync
DisposeAsync()
override async ValueTask System.IO.Strategies.Net5CompatFileStreamStrategy.DisposeAsync () inline virtual
Reimplemented from System.IO.Stream.
Definition at line 655 of file Net5CompatFileStreamStrategy.cs.
    {
        try
        {
            if (_fileHandle != null && !_fileHandle.IsClosed && _writePos > 0)
            {
                await FlushAsync(default(CancellationToken)).ConfigureAwait(continueOnCapturedContext: false);
            }
        }
        finally
        {
            if (_fileHandle != null && !_fileHandle.IsClosed)
            {
                _fileHandle.ThreadPoolBinding?.Dispose();
                _fileHandle.Dispose();
            }
            _preallocatedOverlapped?.Dispose();
            GC.SuppressFinalize(this);
        }
    }
References System.IO.Strategies.Net5CompatFileStreamStrategy._fileHandle, System.IO.Strategies.Net5CompatFileStreamStrategy._preallocatedOverlapped, System.IO.Strategies.Net5CompatFileStreamStrategy._writePos, System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.Runtime.InteropServices.SafeHandle.Dispose(), System.Threading.PreAllocatedOverlapped.Dispose(), System.Threading.ThreadPoolBoundHandle.Dispose(), System.IO.Stream.FlushAsync(), System.Runtime.InteropServices.SafeHandle.IsClosed, System.GC.SuppressFinalize(), and Microsoft.Win32.SafeHandles.SafeFileHandle.ThreadPoolBinding.