Terraria: System.IO.Strategies.Net5CompatFileStreamStrategy.VerifyOSHandlePosition
VerifyOSHandlePosition()
void System.IO.Strategies.Net5CompatFileStreamStrategy.VerifyOSHandlePosition () inline private
Definition at line 439 of file Net5CompatFileStreamStrategy.cs.
    {
        if (!_exposedHandle || !CanSeek)
        {
            return;
        }
        long filePosition = _filePosition;
        long num = SeekCore(_fileHandle, 0L, SeekOrigin.Current);
        if (filePosition != num)
        {
            _readPos = (_readLength = 0);
            if (_writePos > 0)
            {
                _writePos = 0;
                throw new IOException(SR.IO_FileStreamHandlePosition);
            }
        }
    }
References System.IO.Strategies.Net5CompatFileStreamStrategy._exposedHandle, System.IO.Strategies.Net5CompatFileStreamStrategy._fileHandle, System.IO.Strategies.Net5CompatFileStreamStrategy._filePosition, System.IO.Strategies.Net5CompatFileStreamStrategy._readLength, System.IO.Strategies.Net5CompatFileStreamStrategy._readPos, System.IO.Strategies.Net5CompatFileStreamStrategy._writePos, System.IO.Strategies.Net5CompatFileStreamStrategy.CanSeek, System.SR.IO_FileStreamHandlePosition, System.L, and System.IO.Strategies.Net5CompatFileStreamStrategy.SeekCore().
Referenced by System.IO.Strategies.Net5CompatFileStreamStrategy.AsyncModeCopyToAsync(), System.IO.Strategies.Net5CompatFileStreamStrategy.ReadNative(), System.IO.Strategies.Net5CompatFileStreamStrategy.ReadNativeAsync(), System.IO.Strategies.Net5CompatFileStreamStrategy.Seek(), System.IO.Strategies.Net5CompatFileStreamStrategy.SetLengthCore(), System.IO.Strategies.Net5CompatFileStreamStrategy.WriteAsyncInternalCore(), and System.IO.Strategies.Net5CompatFileStreamStrategy.WriteCore().