Terraria: System.IO.Strategies.Net5CompatFileStreamStrategy.WriteAsync
WriteAsync() [2/3]
override Task System.IO.Strategies.Net5CompatFileStreamStrategy.WriteAsync (byte[] buffer, int offset, int count, CancellationToken cancellationToken) inline virtual
Reimplemented from System.IO.Stream.
Definition at line 403 of file Net5CompatFileStreamStrategy.cs.
    {
        if (!_useAsyncIO)
        {
            return BeginWriteInternal(buffer, offset, count, null, null, serializeAsynchronously: true, apm: false);
        }
        return WriteAsyncInternal(new ReadOnlyMemory<byte>(buffer, offset, count), cancellationToken).AsTask();
    }
References System.IO.Strategies.Net5CompatFileStreamStrategy._useAsyncIO, System.Threading.Tasks.ValueTask< TResult >.AsTask(), System.IO.Stream.BeginWriteInternal(), System.buffer, System.cancellationToken, System.count, System.offset, and System.IO.Strategies.Net5CompatFileStreamStrategy.WriteAsyncInternal().