Terraria: System.IO.Strategies.Net5CompatFileStreamStrategy.WriteByte
WriteByte()
override void System.IO.Strategies.Net5CompatFileStreamStrategy.WriteByte (byte value) inline virtual
Reimplemented from System.IO.Stream.
Definition at line 524 of file Net5CompatFileStreamStrategy.cs.
    {
        PrepareForWriting();
        if (_writePos == _bufferLength)
        {
            FlushWriteBufferForWriteByte();
        }
        GetBuffer()[_writePos++] = value;
    }
References System.IO.Strategies.Net5CompatFileStreamStrategy._bufferLength, System.IO.Strategies.Net5CompatFileStreamStrategy._writePos, System.IO.Strategies.Net5CompatFileStreamStrategy.FlushWriteBufferForWriteByte(), System.IO.Strategies.Net5CompatFileStreamStrategy.GetBuffer(), System.IO.Strategies.Net5CompatFileStreamStrategy.PrepareForWriting(), and System.value.