Terraria: System.IO.Strategies.Net5CompatFileStreamStrategy.FlushWriteBuffer
FlushWriteBuffer()
void System.IO.Strategies.Net5CompatFileStreamStrategy.FlushWriteBuffer (bool calledFromFinalizer = false) inline private
Definition at line 693 of file Net5CompatFileStreamStrategy.cs.
    {
        if (_writePos == 0)
        {
            return;
        }
        if (_useAsyncIO)
        {
            Task task = FlushWriteAsync(CancellationToken.None);
            if (!calledFromFinalizer)
            {
                task.GetAwaiter().GetResult();
            }
        }
        else
        {
            WriteCore(new ReadOnlySpan<byte>(GetBuffer(), 0, _writePos));
        }
        _writePos = 0;
    }
References System.IO.Strategies.Net5CompatFileStreamStrategy._useAsyncIO, System.IO.Strategies.Net5CompatFileStreamStrategy._writePos, System.IO.Strategies.Net5CompatFileStreamStrategy.FlushWriteAsync(), System.IO.Strategies.Net5CompatFileStreamStrategy.GetBuffer(), System.Threading.CancellationToken.None, System.task, and System.IO.Strategies.Net5CompatFileStreamStrategy.WriteCore().
Referenced by System.IO.Strategies.Net5CompatFileStreamStrategy.Dispose(), System.IO.Strategies.Net5CompatFileStreamStrategy.FlushInternalBuffer(), System.IO.Strategies.Net5CompatFileStreamStrategy.FlushWriteBufferForWriteByte(), System.IO.Strategies.Net5CompatFileStreamStrategy.ReadAsyncInternal(), System.IO.Strategies.Net5CompatFileStreamStrategy.ReadByte(), System.IO.Strategies.Net5CompatFileStreamStrategy.ReadSpan(), System.IO.Strategies.Net5CompatFileStreamStrategy.Seek(), and System.IO.Strategies.Net5CompatFileStreamStrategy.SetLength().