Terraria: System.IO.Strategies.Net5CompatFileStreamStrategy.WriteFileNative
WriteFileNative()
unsafe int System.IO.Strategies.Net5CompatFileStreamStrategy.WriteFileNative (SafeFileHandle handle, ReadOnlySpan< byte > buffer, NativeOverlapped * overlapped, out int errorCode) inline private
Definition at line 1154 of file Net5CompatFileStreamStrategy.cs.
    {
        int numBytesWritten = 0;
        int num;
        fixed (byte* bytes = &MemoryMarshal.GetReference(buffer))
        {
            num = ((overlapped == null) ? Interop.Kernel32.WriteFile(handle, bytes, buffer.Length, out numBytesWritten, overlapped) : Interop.Kernel32.WriteFile(handle, bytes, buffer.Length, IntPtr.Zero, overlapped));
        }
        if (num == 0)
        {
            errorCode = FileStreamHelpers.GetLastWin32ErrorAndDisposeHandleIfInvalid(handle);
            return -1;
        }
        errorCode = 0;
        return numBytesWritten;
    }
References System.buffer, System.bytes, System.IO.Strategies.FileStreamHelpers.GetLastWin32ErrorAndDisposeHandleIfInvalid(), System.handle, Interop.Kernel32.WriteFile(), and System.IntPtr.Zero.
Referenced by System.IO.Strategies.Net5CompatFileStreamStrategy.WriteAsyncInternalCore(), and System.IO.Strategies.Net5CompatFileStreamStrategy.WriteCore().