Terraria: System.IO.Strategies.Net5CompatFileStreamStrategy.ReadAsyncInternal
ReadAsyncInternal()
Task< int > System.IO.Strategies.Net5CompatFileStreamStrategy.ReadAsyncInternal (Memory< byte > destination, CancellationToken cancellationToken, out int synchronousResult) inline private
Definition at line 955 of file Net5CompatFileStreamStrategy.cs.
    {
        if (!CanRead)
        {
            ThrowHelper.ThrowNotSupportedException_UnreadableStream();
        }
        if (!_fileHandle.CanSeek)
        {
            if (_readPos < _readLength)
            {
                int num = Math.Min(_readLength - _readPos, destination.Length);
                new Span<byte>(GetBuffer(), _readPos, num).CopyTo(destination.Span);
                _readPos += num;
                synchronousResult = num;
                return null;
            }
            synchronousResult = 0;
            return ReadNativeAsync(destination, 0, cancellationToken);
        }
        if (_writePos > 0)
        {
            FlushWriteBuffer();
        }
        if (_readPos == _readLength)
        {
            if (destination.Length < _bufferLength)
            {
                Task<int> task = ReadNativeAsync(new Memory<byte>(GetBuffer()), 0, cancellationToken);
                _readLength = task.GetAwaiter().GetResult();
                int num2 = Math.Min(_readLength, destination.Length);
                new Span<byte>(GetBuffer(), 0, num2).CopyTo(destination.Span);
                _readPos = num2;
                synchronousResult = num2;
                return null;
            }
            _readPos = 0;
            _readLength = 0;
            synchronousResult = 0;
            return ReadNativeAsync(destination, 0, cancellationToken);
        }
        int num3 = Math.Min(_readLength - _readPos, destination.Length);
        new Span<byte>(GetBuffer(), _readPos, num3).CopyTo(destination.Span);
        _readPos += num3;
        if (num3 == destination.Length)
        {
            synchronousResult = num3;
            return null;
        }
        _readPos = 0;
        _readLength = 0;
        synchronousResult = 0;
        return ReadNativeAsync(destination.Slice(num3), num3, cancellationToken);
    }
References System.IO.Strategies.Net5CompatFileStreamStrategy._bufferLength, System.IO.Strategies.Net5CompatFileStreamStrategy._fileHandle, System.IO.Strategies.Net5CompatFileStreamStrategy._readLength, System.IO.Strategies.Net5CompatFileStreamStrategy._readPos, System.IO.Strategies.Net5CompatFileStreamStrategy._writePos, System.cancellationToken, System.IO.Strategies.Net5CompatFileStreamStrategy.CanRead, Microsoft.Win32.SafeHandles.SafeFileHandle.CanSeek, System.Span< T >.CopyTo(), System.destination, System.IO.Strategies.Net5CompatFileStreamStrategy.FlushWriteBuffer(), System.IO.Strategies.Net5CompatFileStreamStrategy.GetBuffer(), System.Math.Min(), System.IO.Strategies.Net5CompatFileStreamStrategy.ReadNativeAsync(), System.task, and System.ThrowHelper.ThrowNotSupportedException_UnreadableStream().
Referenced by System.IO.Strategies.Net5CompatFileStreamStrategy.ReadAsync(), and System.IO.Strategies.Net5CompatFileStreamStrategy.ReadAsyncTask().