Terraria: System.IO.Strategies.Net5CompatFileStreamStrategy.WriteAsyncInternalCore
WriteAsyncInternalCore()
unsafe Task System.IO.Strategies.Net5CompatFileStreamStrategy.WriteAsyncInternalCore (ReadOnlyMemory< byte > source, CancellationToken cancellationToken) inline private
Definition at line 1101 of file Net5CompatFileStreamStrategy.cs.
    {
        CompletionSource completionSource = CompletionSource.Create(this, _preallocatedOverlapped, 0, source);
        NativeOverlapped* overlapped = completionSource.Overlapped;
        if (CanSeek)
        {
            long length = Length;
            VerifyOSHandlePosition();
            if (_filePosition + source.Length > length)
            {
                SetLengthCore(_filePosition + source.Length);
            }
            overlapped->OffsetLow = (int)_filePosition;
            overlapped->OffsetHigh = (int)(_filePosition >> 32);
            SeekCore(_fileHandle, source.Length, SeekOrigin.Current);
        }
        int errorCode;
        int num = WriteFileNative(_fileHandle, source.Span, overlapped, out errorCode);
        if (num == -1)
        {
            switch (errorCode)
            {
            case 232:
                completionSource.SetCompletedSynchronously(0);
                return Task.CompletedTask;
            default:
                if (!_fileHandle.IsClosed && CanSeek)
                {
                    SeekCore(_fileHandle, 0L, SeekOrigin.Current);
                }
                completionSource.ReleaseNativeResource();
                if (errorCode == 38)
                {
                    ThrowHelper.ThrowEndOfFileException();
                    break;
                }
                throw Win32Marshal.GetExceptionForWin32Error(errorCode, _fileHandle.Path);
            case 997:
                if (cancellationToken.CanBeCanceled)
                {
                    completionSource.RegisterForCancellation(cancellationToken);
                }
                break;
            }
        }
        return completionSource.Task;
    }
References System.IO.Strategies.Net5CompatFileStreamStrategy._fileHandle, System.IO.Strategies.Net5CompatFileStreamStrategy._filePosition, System.IO.Strategies.Net5CompatFileStreamStrategy._preallocatedOverlapped, System.cancellationToken, System.IO.Strategies.Net5CompatFileStreamStrategy.CanSeek, System.Threading.Tasks.Task< TResult >.CompletedTask, System.IO.Strategies.Net5CompatFileStreamStrategy.CompletionSource.Create(), System.IO.Win32Marshal.GetExceptionForWin32Error(), System.Runtime.InteropServices.SafeHandle.IsClosed, System.L, System.length, System.IO.Strategies.Net5CompatFileStreamStrategy.Length, System.Threading.NativeOverlapped.OffsetHigh, System.Threading.NativeOverlapped.OffsetLow, System.IO.Strategies.Net5CompatFileStreamStrategy.CompletionSource.Overlapped, Microsoft.Win32.SafeHandles.SafeFileHandle.Path, System.IO.Strategies.Net5CompatFileStreamStrategy.CompletionSource.RegisterForCancellation(), System.IO.Strategies.Net5CompatFileStreamStrategy.CompletionSource.ReleaseNativeResource(), System.IO.Strategies.Net5CompatFileStreamStrategy.SeekCore(), System.IO.Strategies.Net5CompatFileStreamStrategy.CompletionSource.SetCompletedSynchronously(), System.IO.Strategies.Net5CompatFileStreamStrategy.SetLengthCore(), System.source, System.Threading.Tasks.TaskCompletionSource< TResult >.Task, System.ThrowHelper.ThrowEndOfFileException(), System.IO.Strategies.Net5CompatFileStreamStrategy.VerifyOSHandlePosition(), and System.IO.Strategies.Net5CompatFileStreamStrategy.WriteFileNative().
Referenced by System.IO.Strategies.Net5CompatFileStreamStrategy.FlushWriteAsync(), and System.IO.Strategies.Net5CompatFileStreamStrategy.WriteAsyncInternal().