Terraria: System.IO.Strategies.Net5CompatFileStreamStrategy.Dispose
Dispose() [2/2]
override void System.IO.Strategies.Net5CompatFileStreamStrategy.Dispose (bool disposing) inline protected virtual
Reimplemented from System.IO.Stream.
Definition at line 627 of file Net5CompatFileStreamStrategy.cs.
    {
        try
        {
            if (_fileHandle != null && !_fileHandle.IsClosed && _writePos > 0)
            {
                try
                {
                    FlushWriteBuffer(!disposing);
                    return;
                }
                catch (Exception e) when (!disposing && FileStreamHelpers.IsIoRelatedException(e))
                {
                    return;
                }
            }
        }
        finally
        {
            if (_fileHandle != null && !_fileHandle.IsClosed)
            {
                _fileHandle.ThreadPoolBinding?.Dispose();
                _fileHandle.Dispose();
            }
            _preallocatedOverlapped?.Dispose();
        }
    }
References System.IO.Strategies.Net5CompatFileStreamStrategy._fileHandle, System.IO.Strategies.Net5CompatFileStreamStrategy._preallocatedOverlapped, System.IO.Strategies.Net5CompatFileStreamStrategy._writePos, System.Runtime.InteropServices.SafeHandle.Dispose(), System.Threading.PreAllocatedOverlapped.Dispose(), System.Threading.ThreadPoolBoundHandle.Dispose(), System.IO.Strategies.Net5CompatFileStreamStrategy.FlushWriteBuffer(), System.Runtime.InteropServices.SafeHandle.IsClosed, System.IO.Strategies.FileStreamHelpers.IsIoRelatedException(), and Microsoft.Win32.SafeHandles.SafeFileHandle.ThreadPoolBinding.