Terraria: System.IO.Strategies.Net5CompatFileStreamStrategy.WriteSpan
WriteSpan()
void System.IO.Strategies.Net5CompatFileStreamStrategy.WriteSpan (ReadOnlySpan< byte > source) inline private
Definition at line 890 of file Net5CompatFileStreamStrategy.cs.
    {
        if (_writePos == 0)
        {
            if (!CanWrite)
            {
                ThrowHelper.ThrowNotSupportedException_UnwritableStream();
            }
            if (_readPos < _readLength)
            {
                FlushReadBuffer();
            }
            _readPos = 0;
            _readLength = 0;
        }
        if (_writePos > 0)
        {
            int num = _bufferLength - _writePos;
            if (num > 0)
            {
                if (num >= source.Length)
                {
                    source.CopyTo(GetBuffer().AsSpan(_writePos));
                    _writePos += source.Length;
                    return;
                }
                source.Slice(0, num).CopyTo(GetBuffer().AsSpan(_writePos));
                _writePos += num;
                source = source.Slice(num);
            }
            WriteCore(new ReadOnlySpan<byte>(GetBuffer(), 0, _writePos));
            _writePos = 0;
        }
        if (source.Length >= _bufferLength)
        {
            WriteCore(source);
        }
        else if (source.Length != 0)
        {
            source.CopyTo(GetBuffer().AsSpan(_writePos));
            _writePos = source.Length;
        }
    }
References System.IO.Strategies.Net5CompatFileStreamStrategy._bufferLength, System.IO.Strategies.Net5CompatFileStreamStrategy._readLength, System.IO.Strategies.Net5CompatFileStreamStrategy._readPos, System.IO.Strategies.Net5CompatFileStreamStrategy._writePos, System.IO.Strategies.Net5CompatFileStreamStrategy.CanWrite, System.IO.Strategies.Net5CompatFileStreamStrategy.FlushReadBuffer(), System.IO.Strategies.Net5CompatFileStreamStrategy.GetBuffer(), System.source, System.ThrowHelper.ThrowNotSupportedException_UnwritableStream(), and System.IO.Strategies.Net5CompatFileStreamStrategy.WriteCore().
Referenced by System.IO.Strategies.Net5CompatFileStreamStrategy.Write(), and System.IO.Strategies.Net5CompatFileStreamStrategy.Write().