Terraria: System.IO.Strategies.Net5CompatFileStreamStrategy.GetBuffer
GetBuffer()
byte[] System.IO.Strategies.Net5CompatFileStreamStrategy.GetBuffer () inline private
Definition at line 475 of file Net5CompatFileStreamStrategy.cs.
    {
        if (_buffer == null)
        {
            _buffer = new byte[_bufferLength];
            OnBufferAllocated();
        }
        return _buffer;
    }
References System.IO.Strategies.Net5CompatFileStreamStrategy._buffer, System.IO.Strategies.Net5CompatFileStreamStrategy._bufferLength, and System.IO.Strategies.Net5CompatFileStreamStrategy.OnBufferAllocated().
Referenced by System.IO.Strategies.Net5CompatFileStreamStrategy.AsyncModeCopyToAsync(), System.IO.Strategies.Net5CompatFileStreamStrategy.FlushWriteAsync(), System.IO.Strategies.Net5CompatFileStreamStrategy.FlushWriteBuffer(), System.IO.Strategies.Net5CompatFileStreamStrategy.ReadAsyncInternal(), System.IO.Strategies.Net5CompatFileStreamStrategy.ReadByte(), System.IO.Strategies.Net5CompatFileStreamStrategy.ReadSpan(), System.IO.Strategies.Net5CompatFileStreamStrategy.Seek(), System.IO.Strategies.Net5CompatFileStreamStrategy.WriteAsyncInternal(), System.IO.Strategies.Net5CompatFileStreamStrategy.WriteByte(), and System.IO.Strategies.Net5CompatFileStreamStrategy.WriteSpan().