Terraria: System.IO.Strategies.Net5CompatFileStreamStrategy.ReadByte
ReadByte()
override int System.IO.Strategies.Net5CompatFileStreamStrategy.ReadByte () inline virtual
Reimplemented from System.IO.Stream.
Definition at line 507 of file Net5CompatFileStreamStrategy.cs.
    {
        PrepareForReading();
        byte[] buffer = GetBuffer();
        if (_readPos == _readLength)
        {
            FlushWriteBuffer();
            _readLength = FillReadBufferForReadByte();
            _readPos = 0;
            if (_readLength == 0)
            {
                return -1;
            }
        }
        return buffer[_readPos++];
    }
References System.IO.Strategies.Net5CompatFileStreamStrategy._readLength, System.IO.Strategies.Net5CompatFileStreamStrategy._readPos, System.buffer, System.IO.Strategies.Net5CompatFileStreamStrategy.FillReadBufferForReadByte(), System.IO.Strategies.Net5CompatFileStreamStrategy.FlushWriteBuffer(), System.IO.Strategies.Net5CompatFileStreamStrategy.GetBuffer(), and System.IO.Strategies.Net5CompatFileStreamStrategy.PrepareForReading().