Terraria: System.IO.Strategies.Net5CompatFileStreamStrategy.Seek
Seek()
override long System.IO.Strategies.Net5CompatFileStreamStrategy.Seek (long offset, SeekOrigin origin) inline
Definition at line 819 of file Net5CompatFileStreamStrategy.cs.
    {
        if (origin < SeekOrigin.Begin || origin > SeekOrigin.End)
        {
            throw new ArgumentException(SR.Argument_InvalidSeekOrigin, "origin");
        }
        if (_fileHandle.IsClosed)
        {
            ThrowHelper.ThrowObjectDisposedException_FileClosed();
        }
        if (!CanSeek)
        {
            ThrowHelper.ThrowNotSupportedException_UnseekableStream();
        }
        if (_writePos > 0)
        {
            FlushWriteBuffer();
        }
        else if (origin == SeekOrigin.Current)
        {
            offset -= _readLength - _readPos;
        }
        _readPos = (_readLength = 0);
        VerifyOSHandlePosition();
        long num = _filePosition + (_readPos - _readLength);
        long num2 = SeekCore(_fileHandle, offset, origin);
        if (_appendStart != -1 && num2 < _appendStart)
        {
            SeekCore(_fileHandle, num, SeekOrigin.Begin);
            throw new IOException(SR.IO_SeekAppendOverwrite);
        }
        if (_readLength > 0)
        {
            if (num == num2)
            {
                if (_readPos > 0)
                {
                    Buffer.BlockCopy(GetBuffer(), _readPos, GetBuffer(), 0, _readLength - _readPos);
                    _readLength -= _readPos;
                    _readPos = 0;
                }
                if (_readLength > 0)
                {
                    SeekCore(_fileHandle, _readLength, SeekOrigin.Current);
                }
            }
            else if (num - _readPos < num2 && num2 < num + _readLength - _readPos)
            {
                int num3 = (int)(num2 - num);
                Buffer.BlockCopy(GetBuffer(), _readPos + num3, GetBuffer(), 0, _readLength - (_readPos + num3));
                _readLength -= _readPos + num3;
                _readPos = 0;
                if (_readLength > 0)
                {
                    SeekCore(_fileHandle, _readLength, SeekOrigin.Current);
                }
            }
            else
            {
                _readPos = 0;
                _readLength = 0;
            }
        }
        return num2;
    }
References System.IO.Strategies.Net5CompatFileStreamStrategy._appendStart, System.IO.Strategies.Net5CompatFileStreamStrategy._fileHandle, System.IO.Strategies.Net5CompatFileStreamStrategy._filePosition, System.IO.Strategies.Net5CompatFileStreamStrategy._readLength, System.IO.Strategies.Net5CompatFileStreamStrategy._readPos, System.IO.Strategies.Net5CompatFileStreamStrategy._writePos, System.SR.Argument_InvalidSeekOrigin, System.Buffer.BlockCopy(), System.IO.Strategies.Net5CompatFileStreamStrategy.CanSeek, System.IO.Strategies.Net5CompatFileStreamStrategy.FlushWriteBuffer(), System.IO.Strategies.Net5CompatFileStreamStrategy.GetBuffer(), System.SR.IO_SeekAppendOverwrite, System.Runtime.InteropServices.SafeHandle.IsClosed, System.offset, System.IO.Strategies.Net5CompatFileStreamStrategy.SeekCore(), System.ThrowHelper.ThrowNotSupportedException_UnseekableStream(), System.ThrowHelper.ThrowObjectDisposedException_FileClosed(), and System.IO.Strategies.Net5CompatFileStreamStrategy.VerifyOSHandlePosition().