Terraria: System.IO.Strategies.Net5CompatFileStreamStrategy.WriteCore
WriteCore()
unsafe void System.IO.Strategies.Net5CompatFileStreamStrategy.WriteCore (ReadOnlySpan< byte > source) inline private
Definition at line 934 of file Net5CompatFileStreamStrategy.cs.
    {
        VerifyOSHandlePosition();
        int errorCode;
        int num = WriteFileNative(_fileHandle, source, null, out errorCode);
        if (num == -1)
        {
            switch (errorCode)
            {
            case 232:
                break;
            case 87:
                throw new IOException(SR.IO_FileTooLongOrHandleNotSync);
            default:
                throw Win32Marshal.GetExceptionForWin32Error(errorCode, _fileHandle.Path);
            }
            num = 0;
        }
        _filePosition += num;
    }
References System.IO.Strategies.Net5CompatFileStreamStrategy._fileHandle, System.IO.Strategies.Net5CompatFileStreamStrategy._filePosition, System.IO.Win32Marshal.GetExceptionForWin32Error(), System.SR.IO_FileTooLongOrHandleNotSync, Microsoft.Win32.SafeHandles.SafeFileHandle.Path, System.source, System.IO.Strategies.Net5CompatFileStreamStrategy.VerifyOSHandlePosition(), and System.IO.Strategies.Net5CompatFileStreamStrategy.WriteFileNative().
Referenced by System.IO.Strategies.Net5CompatFileStreamStrategy.FlushWriteBuffer(), and System.IO.Strategies.Net5CompatFileStreamStrategy.WriteSpan().