Terraria: System.Transactions.TransactionStatePromoted.PromoteEnlistmentsAndOutcome
PromoteEnlistmentsAndOutcome()
virtual void System.Transactions.TransactionStatePromoted.PromoteEnlistmentsAndOutcome (InternalTransaction tx) inline package virtual
Definition at line 100 of file TransactionStatePromoted.cs.
    {
        bool flag = false;
        tx.PromotedTransaction.RealTransaction.InternalTransaction = tx;
        try
        {
            flag = PromotePhaseVolatiles(tx, ref tx._phase0Volatiles, phase0: true);
        }
        catch (TransactionException innerException)
        {
            TransactionException exception = (TransactionException)(tx._innerException = innerException);
            TransactionsEtwProvider log = TransactionsEtwProvider.Log;
            if (log.IsEnabled())
            {
                log.ExceptionConsumed(exception);
            }
            return;
        }
        finally
        {
            if (!flag)
            {
                tx.PromotedTransaction.Rollback();
                tx.State.ChangeStateAbortedDuringPromotion(tx);
            }
        }
        flag = false;
        try
        {
            flag = PromotePhaseVolatiles(tx, ref tx._phase1Volatiles, phase0: false);
        }
        catch (TransactionException innerException2)
        {
            TransactionException exception2 = (TransactionException)(tx._innerException = innerException2);
            TransactionsEtwProvider log2 = TransactionsEtwProvider.Log;
            if (log2.IsEnabled())
            {
                log2.ExceptionConsumed(exception2);
            }
            return;
        }
        finally
        {
            if (!flag)
            {
                tx.PromotedTransaction.Rollback();
                tx.State.ChangeStateAbortedDuringPromotion(tx);
            }
        }
        flag = false;
        try
        {
            flag = PromoteDurable(tx);
        }
        catch (TransactionException innerException3)
        {
            TransactionException exception3 = (TransactionException)(tx._innerException = innerException3);
            TransactionsEtwProvider log3 = TransactionsEtwProvider.Log;
            if (log3.IsEnabled())
            {
                log3.ExceptionConsumed(exception3);
            }
        }
        finally
        {
            if (!flag)
            {
                tx.PromotedTransaction.Rollback();
                tx.State.ChangeStateAbortedDuringPromotion(tx);
            }
        }
    }
References System.Transactions.InternalTransaction._innerException, System.Transactions.InternalTransaction._phase0Volatiles, System.Transactions.InternalTransaction._phase1Volatiles, System.Transactions.TransactionState.ChangeStateAbortedDuringPromotion(), System.exception, System.Transactions.TransactionsEtwProvider.ExceptionConsumed(), System.Diagnostics.Tracing.EventSource.IsEnabled(), System.Transactions.TransactionsEtwProvider.Log, System.Transactions.InternalTransaction.PromotedTransaction, System.Transactions.TransactionStatePromoted.PromoteDurable(), System.Transactions.TransactionStatePromoted.PromotePhaseVolatiles(), System.Transactions.Distributed.DistributedTransaction.Rollback(), System.Transactions.InternalTransaction.State, and System.Transactions.TransactionException.
Referenced by System.Transactions.TransactionStateDelegatedBase.EnterState(), and System.Transactions.TransactionStatePromoted.EnterState().