Terraria: System.Transactions.TransactionStatePromoted.EnterState
EnterState()
override void System.Transactions.TransactionStatePromoted.EnterState (InternalTransaction tx) inline package
Definition at line 8 of file TransactionStatePromoted.cs.
    {
        tx.SetPromoterTypeToMSDTC();
        if (tx._outcomeSource._isoLevel == IsolationLevel.Snapshot)
        {
            throw TransactionException.CreateInvalidOperationException(TraceSourceType.TraceSourceLtm, System.SR.CannotPromoteSnapshot, null);
        }
        CommonEnterState(tx);
        DistributedCommittableTransaction distributedCommittableTransaction = null;
        try
        {
            TimeSpan timeSpan;
            if (tx.AbsoluteTimeout == long.MaxValue)
            {
                timeSpan = TimeSpan.Zero;
            }
            else
            {
                timeSpan = TransactionManager.TransactionTable.RecalcTimeout(tx);
                if (timeSpan <= TimeSpan.Zero)
                {
                    return;
                }
            }
            TransactionOptions options = default(TransactionOptions);
            options.IsolationLevel = tx._outcomeSource._isoLevel;
            options.Timeout = timeSpan;
            distributedCommittableTransaction = TransactionManager.DistributedTransactionManager.CreateTransaction(options);
            distributedCommittableTransaction.SavedLtmPromotedTransaction = tx._outcomeSource;
            TransactionsEtwProvider log = TransactionsEtwProvider.Log;
            if (log.IsEnabled())
            {
                log.TransactionPromoted(tx.TransactionTraceId, distributedCommittableTransaction.TransactionTraceId);
            }
        }
        catch (TransactionException innerException)
        {
            TransactionException exception = (TransactionException)(tx._innerException = innerException);
            TransactionsEtwProvider log2 = TransactionsEtwProvider.Log;
            if (log2.IsEnabled())
            {
                log2.ExceptionConsumed(exception);
            }
            return;
        }
        finally
        {
            if (distributedCommittableTransaction == null)
            {
                tx.State.ChangeStateAbortedDuringPromotion(tx);
            }
        }
        tx.PromotedTransaction = distributedCommittableTransaction;
        Hashtable promotedTransactionTable = TransactionManager.PromotedTransactionTable;
        lock (promotedTransactionTable)
        {
            tx._finalizedObject = new FinalizedObject(tx, distributedCommittableTransaction.Identifier);
            WeakReference value = new WeakReference(tx._outcomeSource, trackResurrection: false);
            promotedTransactionTable[distributedCommittableTransaction.Identifier] = value;
        }
        TransactionManager.FireDistributedTransactionStarted(tx._outcomeSource);
        PromoteEnlistmentsAndOutcome(tx);
    }
References System.Transactions.InternalTransaction._innerException, System.Transactions.Transaction._isoLevel, System.Transactions.InternalTransaction._outcomeSource, System.Transactions.InternalTransaction.AbsoluteTimeout, System.SR.CannotPromoteSnapshot, System.Transactions.TransactionState.ChangeStateAbortedDuringPromotion(), System.Transactions.TransactionState.CommonEnterState(), System.Transactions.TransactionException.CreateInvalidOperationException(), System.Transactions.TransactionManager.DistributedTransactionManager, System.exception, System.Transactions.TransactionsEtwProvider.ExceptionConsumed(), System.Transactions.TransactionManager.FireDistributedTransactionStarted(), System.Transactions.Distributed.DistributedTransaction.Identifier, System.Diagnostics.Tracing.EventSource.IsEnabled(), System.Transactions.TransactionsEtwProvider.Log, System.options, System.Transactions.TransactionManager.PromotedTransactionTable, System.Transactions.TransactionStatePromoted.PromoteEnlistmentsAndOutcome(), System.Transactions.InternalTransaction.SetPromoterTypeToMSDTC(), System.Transactions.InternalTransaction.State, System.Transactions.TransactionException, System.Transactions.TransactionsEtwProvider.TransactionPromoted(), System.Transactions.TransactionManager.TransactionTable, System.Transactions.Distributed.DistributedTransaction.TransactionTraceId, System.Transactions.InternalTransaction.TransactionTraceId, System.value, and System.TimeSpan.Zero.