Terraria: System.Transactions.InternalTransaction.Dispose
Dispose()
void System.Transactions.InternalTransaction.Dispose () inline
Implements System.IDisposable.
Definition at line 234 of file InternalTransaction.cs.
    {
        if (_promotedTransaction != null)
        {
            _promotedTransaction.Dispose();
        }
    }
References System.Transactions.InternalTransaction._promotedTransaction, and System.Transactions.Distributed.DistributedTransaction.Dispose().
Referenced by System.Transactions.CommittableTransaction.InternalDispose(), and System.Transactions.Transaction.InternalDispose().