Terraria: System.Transactions.InternalTransaction.ThrowIfPromoterTypeIsNotMSDTC
ThrowIfPromoterTypeIsNotMSDTC()
void System.Transactions.InternalTransaction.ThrowIfPromoterTypeIsNotMSDTC () inline package
Definition at line 165 of file InternalTransaction.cs.
    {
        if (_promoterType != Guid.Empty && _promoterType != TransactionInterop.PromoterTypeDtc)
        {
            throw new TransactionPromotionException(System.SR.Format(System.SR.PromoterTypeUnrecognized, _promoterType.ToString()), _innerException);
        }
    }
References System.Transactions.InternalTransaction._innerException, System.Transactions.InternalTransaction._promoterType, System.Guid.Empty, System.SR.Format(), System.Transactions.TransactionInterop.PromoterTypeDtc, System.SR.PromoterTypeUnrecognized, and System.Guid.ToString().
Referenced by System.Transactions.EnlistableStates.EnlistDurable(), System.Transactions.TransactionStatePhase0.EnlistDurable(), System.Transactions.TransactionStatePromotedBase.EnlistDurable(), System.Transactions.EnlistableStates.EnlistDurable(), System.Transactions.TransactionStatePhase0.EnlistDurable(), System.Transactions.TransactionStatePromotedBase.EnlistDurable(), and System.Transactions.Transaction.Promote().