Terraria: System.Transactions.InternalTransaction.SignalAsyncCompletion
SignalAsyncCompletion()
void System.Transactions.InternalTransaction.SignalAsyncCompletion () inline package
Definition at line 203 of file InternalTransaction.cs.
    {
        if (_asyncResultEvent != null)
        {
            _asyncResultEvent.Set();
        }
        if (_asyncCallback != null)
        {
            Monitor.Exit(this);
            try
            {
                _asyncCallback(_committableTransaction);
            }
            finally
            {
                Monitor.Enter(this);
            }
        }
    }
References System.Transactions.InternalTransaction._asyncCallback, System.Transactions.InternalTransaction._asyncResultEvent, System.Transactions.InternalTransaction._committableTransaction, System.Threading.Monitor.Enter(), System.Threading.Monitor.Exit(), and System.Threading.EventWaitHandle.Set().
Referenced by System.Transactions.TransactionStateAborted.EnterState(), System.Transactions.TransactionStateCommitted.EnterState(), System.Transactions.TransactionStateInDoubt.EnterState(), System.Transactions.TransactionStatePromotedEnded.SignalCallback(), and System.Transactions.TransactionStatePromotedNonMSDTCEnded.SignalCallback().