Terraria: UIScrollbar.DrawSelf
DrawSelf()
override void UIScrollbar.DrawSelf (SpriteBatch spriteBatch) inline protected virtual
Reimplemented from UIElement.
     {
         CalculatedStyle dimensions = GetDimensions();
         CalculatedStyle innerDimensions = GetInnerDimensions();
         if (_isDragging)
         {
             float num = UserInterface.ActiveInstance.MousePosition.Y - innerDimensions.Y - _dragYOffset;
             _viewPosition = MathHelper.Clamp(num / innerDimensions.Height * _maxViewSize, 0f, _maxViewSize - _viewSize);
         }
         Rectangle handleRectangle = GetHandleRectangle();
         Vector2 mousePosition = UserInterface.ActiveInstance.MousePosition;
         bool isHoveringOverHandle = _isHoveringOverHandle;
         _isHoveringOverHandle = handleRectangle.Contains(new Point((int)mousePosition.X, (int)mousePosition.Y));
         if (!isHoveringOverHandle && _isHoveringOverHandle && Main.hasFocus)
         {
             SoundEngine.PlaySound(12);
         }
         DrawBar(spriteBatch, _texture.Value, dimensions.ToRectangle(), Color.White);
         DrawBar(spriteBatch, _innerTexture.Value, handleRectangle, Color.White * ((_isDragging || _isHoveringOverHandle) ? 1f : 0.85f));
     }
References _dragYOffset, _innerTexture, _isDragging, _isHoveringOverHandle, _maxViewSize, _texture, _viewPosition, _viewSize, UserInterface.ActiveInstance, Color, DrawBar(), UIElement.GetDimensions(), GetHandleRectangle(), UIElement.GetInnerDimensions(), Main.hasFocus, CalculatedStyle.Height, UserInterface.MousePosition, SoundEngine.PlaySound(), CalculatedStyle.ToRectangle(), Asset< T >.Value, and CalculatedStyle.Y.