Terraria: UIScrollbar.SetView
SetView()
void UIScrollbar.SetView (float viewSize, float maxViewSize) inline
     {
         viewSize = MathHelper.Clamp(viewSize, 0f, maxViewSize);
         _viewPosition = MathHelper.Clamp(_viewPosition, 0f, maxViewSize - viewSize);
         _viewSize = viewSize;
         _maxViewSize = maxViewSize;
     }
References _maxViewSize, _viewPosition, and _viewSize.
Referenced by UIBestiaryEntryInfoPage.UIBestiaryEntryInfoPage(), AWorkshopPublishInfoState< TPublishedObjectType >.AddUIList(), UIReportsPage.BuildPage(), UIResourcePackInfoMenu.BuildPage(), UIAchievementsMenu.InitializePage(), UIEmotesMenu.InitializePage(), UICharacterCreation.MakeHairsylesMenu(), UICharacterSelect.OnInitialize(), UIManageControls.OnInitialize(), UIWorkshopSelectResourcePackToPublish.OnInitialize(), UIWorkshopSelectWorldToPublish.OnInitialize(), UIWorkshopWorldImport.OnInitialize(), UIWorldSelect.OnInitialize(), and UIList.UpdateScrollbar().