Terraria: Terraria.Graphics.Renderers.RandomizedFrameParticle.SetTypeInfo
SetTypeInfo()
void Terraria.Graphics.Renderers.RandomizedFrameParticle.SetTypeInfo (int animationFramesAmount, int gameFramesPerAnimationFrame, float timeToLive) inline
Definition at line 37 of file RandomizedFrameParticle.cs.
    {
        _timeTolive = timeToLive;
        GameFramesPerAnimationFrame = gameFramesPerAnimationFrame;
        AnimationFramesAmount = animationFramesAmount;
        RandomizeFrame();
    }
References Terraria.Graphics.Renderers.RandomizedFrameParticle._timeTolive, Terraria.Graphics.Renderers.RandomizedFrameParticle.AnimationFramesAmount, Terraria.Graphics.Renderers.RandomizedFrameParticle.GameFramesPerAnimationFrame, and Terraria.Graphics.Renderers.RandomizedFrameParticle.RandomizeFrame().
Referenced by Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_BlackLightningHit(), and Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_BlackLightningSmall().