Terraria: System.Xml.Xsl.Xslt.LoopFocus.ConstructLoop
ConstructLoop()
QilLoop System.Xml.Xsl.Xslt.LoopFocus.ConstructLoop (QilNode body) inline
Definition at line 67 of file LoopFocus.cs.
    {
        if (_last != null)
        {
            EnsureCache();
            _last.Binding = _f.XsltConvert(_f.Length(_cached), XmlQueryTypeFactory.DoubleX);
        }
        QilLoop qilLoop = _f.BaseFactory.Loop(_current, body);
        if (_last != null)
        {
            qilLoop = _f.BaseFactory.Loop(_last, qilLoop);
        }
        if (_cached != null)
        {
            qilLoop = _f.BaseFactory.Loop(_cached, qilLoop);
        }
        return qilLoop;
    }
References System.Xml.Xsl.Xslt.LoopFocus._cached, System.Xml.Xsl.Xslt.LoopFocus._current, System.Xml.Xsl.Xslt.LoopFocus._f, System.Xml.Xsl.Xslt.LoopFocus._last, System.Xml.Xsl.Qil.QilPatternFactory.BaseFactory, System.Xml.Dictionary, System.Xml.Xsl.XmlQueryTypeFactory.DoubleX, System.Xml.Xsl.Xslt.LoopFocus.EnsureCache(), System.Xml.Xsl.Qil.QilPatternFactory.Length(), System.Xml.Xsl.Qil.QilFactory.Loop(), and System.Xml.Xsl.Qil.QilPatternFactory.XsltConvert().
Referenced by System.Xml.Xsl.Xslt.QilGenerator.CompileApplyTemplates(), System.Xml.Xsl.Xslt.QilGenerator.CompileForEach(), and System.Xml.Xsl.Xslt.QilGenerator.InvokeApplyFunction().