Terraria: System.Xml.Xsl.Xslt.LoopFocus.Sort
Sort()
void System.Xml.Xsl.Xslt.LoopFocus.Sort (QilNode sortKeys) inline
Definition at line 58 of file LoopFocus.cs.
    {
        if (sortKeys != null)
        {
            EnsureCache();
            _current = _f.For(_f.Sort(_current, sortKeys));
        }
    }
References System.Xml.Xsl.Xslt.LoopFocus._current, System.Xml.Xsl.Xslt.LoopFocus._f, System.Xml.Dictionary, System.Xml.Xsl.Xslt.LoopFocus.EnsureCache(), System.Xml.Xsl.Qil.QilPatternFactory.For(), and System.Xml.Xsl.Qil.QilPatternFactory.Sort().
Referenced by System.Xml.Xsl.Xslt.QilGenerator.CompileApplyTemplates(), and System.Xml.Xsl.Xslt.QilGenerator.CompileForEach().