Terraria: System.Xml.Xsl.Xslt.LoopFocus.SetFocus
SetFocus()
void System.Xml.Xsl.Xslt.LoopFocus.SetFocus (QilIterator current) inline
Definition at line 24 of file LoopFocus.cs.
    {
        _current = current;
        _cached = (_last = null);
    }
References System.Xml.Xsl.Xslt.LoopFocus._cached, System.Xml.Xsl.Xslt.LoopFocus._current, and System.Xml.Xsl.Xslt.LoopFocus._last.
Referenced by System.Xml.Xsl.Xslt.QilGenerator.CompileApplyTemplates(), System.Xml.Xsl.Xslt.QilGenerator.CompileForEach(), and System.Xml.Xsl.Xslt.QilGenerator.InvokeApplyFunction().