Terraria: System.Xml.Xsl.Xslt.LoopFocus.EnsureCache
EnsureCache()
void System.Xml.Xsl.Xslt.LoopFocus.EnsureCache () inline
Definition at line 49 of file LoopFocus.cs.
    {
        if (_cached == null)
        {
            _cached = _f.Let(_current.Binding);
            _current.Binding = _cached;
        }
    }
References System.Xml.Xsl.Xslt.LoopFocus._cached, System.Xml.Xsl.Xslt.LoopFocus._current, System.Xml.Xsl.Xslt.LoopFocus._f, System.Xml.Xsl.Qil.QilIterator.Binding, System.Xml.Dictionary, and System.Xml.Xsl.Qil.QilPatternFactory.Let().
Referenced by System.Xml.Xsl.Xslt.LoopFocus.ConstructLoop(), and System.Xml.Xsl.Xslt.LoopFocus.Sort().