Terraria: System.Xml.Xsl.Xslt.LoopFocus.GetLast
GetLast()
QilNode System.Xml.Xsl.Xslt.LoopFocus.GetLast () inline
Implements System.Xml.Xsl.XPath.IFocus.
Definition at line 40 of file LoopFocus.cs.
    {
        if (_last == null)
        {
            _last = _f.Let(_f.Double(0.0));
        }
        return _last;
    }
References System.Xml.Xsl.Xslt.LoopFocus._f, System.Xml.Xsl.Xslt.LoopFocus._last, System.Xml.Xsl.Qil.QilPatternFactory.Double(), and System.Xml.Xsl.Qil.QilPatternFactory.Let().
Referenced by System.Xml.Xsl.Xslt.QilGenerator.GetLastPosition().