Terraria: Terraria.GameContent.TilePaintSystemV2.WallRenderTargetHolder.PrepareShader
PrepareShader() [1/2]
override void Terraria.GameContent.TilePaintSystemV2.WallRenderTargetHolder.PrepareShader () inline
Definition at line 140 of file TilePaintSystemV2.cs.
        {
            PrepareShader(Key.PaintColor, TreePaintSystemData.GetWallSettings(Key.WallType));
        }
References Terraria.GameContent.TreePaintSystemData.GetWallSettings(), Terraria.GameContent.TilePaintSystemV2.WallRenderTargetHolder.Key, Terraria.GameContent.TilePaintSystemV2.WallVariationKey.PaintColor, Terraria.GameContent.TilePaintSystemV2.WallRenderTargetHolder.PrepareShader(), and Terraria.GameContent.TilePaintSystemV2.WallVariationKey.WallType.
Referenced by Terraria.GameContent.TilePaintSystemV2.WallRenderTargetHolder.PrepareShader().