Terraria: System.Net.Http.IHttpTrace.Trace
Trace()
void System.Net.Http.IHttpTrace.Trace (string message, [CallerMemberName] string memberName = null)
Implemented in System.Net.Http.Http2Connection.Http2Stream, System.Net.Http.Http2Connection, System.Net.Http.Http3Connection, System.Net.Http.HttpConnection, and System.Net.Http.HttpConnectionBase.
Referenced by System.Net.Http.CreditManager.CreditManager(), System.Net.Http.CreditManager.AdjustCredit(), System.Net.Http.CreditManager.RequestCreditAsync(), and System.Net.Http.CreditManager.TryRequestCreditNoLock().