Terraria: System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.InvokeFactoryMethod
InvokeFactoryMethod()
bool System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.InvokeFactoryMethod (ClassDataContract classContract, LocalBuilder objectId) inline private
Definition at line 264 of file XmlFormatReaderGenerator.cs.
        {
            if (HasFactoryMethod(classContract))
            {
                _ilg.Load(_contextArg);
                _ilg.LoadAddress(_objectLocal);
                _ilg.ConvertAddress(_objectLocal.LocalType, Globals.TypeOfIObjectReference);
                _ilg.Load(objectId);
                _ilg.Call(XmlFormatGeneratorStatics.GetRealObjectMethod);
                _ilg.ConvertValue(Globals.TypeOfObject, _ilg.CurrentMethod.ReturnType);
                return true;
            }
            return false;
        }
References System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper._contextArg, System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper._ilg, System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper._objectLocal, System.Runtime.Serialization.CodeGenerator.Call(), System.Runtime.Serialization.CodeGenerator.ConvertAddress(), System.Runtime.Serialization.CodeGenerator.ConvertValue(), System.Runtime.Serialization.CodeGenerator.CurrentMethod, System.Runtime.Serialization.XmlFormatGeneratorStatics.GetRealObjectMethod, System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.HasFactoryMethod(), System.Runtime.Serialization.CodeGenerator.Load(), System.Runtime.Serialization.CodeGenerator.LoadAddress(), System.Reflection.Emit.LocalBuilder.LocalType, System.Reflection.MethodInfo.ReturnType, System.Runtime.Serialization.Globals.TypeOfIObjectReference, and System.Runtime.Serialization.Globals.TypeOfObject.
Referenced by System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.GenerateClassReader().