Terraria: System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.InternalDeserialize
InternalDeserialize()
void System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.InternalDeserialize (LocalBuilder value, Type type, string name, string ns) inline private
Definition at line 508 of file XmlFormatReaderGenerator.cs.
        {
            _ilg.Load(_contextArg);
            _ilg.Load(_xmlReaderArg);
            _ilg.Load(DataContract.GetId(type.TypeHandle));
            _ilg.Ldtoken(type);
            _ilg.Load(name);
            _ilg.Load(ns);
            _ilg.Call(XmlFormatGeneratorStatics.InternalDeserializeMethod);
            _ilg.ConvertValue(Globals.TypeOfObject, type);
            _ilg.Stloc(value);
        }
References System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper._contextArg, System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper._ilg, System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper._xmlReaderArg, System.Runtime.Serialization.CodeGenerator.Call(), System.Runtime.Serialization.CodeGenerator.ConvertValue(), System.Runtime.Serialization.DataContract.GetId(), System.Runtime.Serialization.XmlFormatGeneratorStatics.InternalDeserializeMethod, System.Runtime.Serialization.CodeGenerator.Ldtoken(), System.Runtime.Serialization.CodeGenerator.Load(), System.Runtime.Serialization.CodeGenerator.Stloc(), System.type, System.Runtime.Serialization.Globals.TypeOfObject, and System.value.
Referenced by System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.ReadValue().