Terraria: System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.ReadMembers
ReadMembers() [1/2]
int System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.ReadMembers (ClassDataContract classContract, bool[] requiredMembers, Label[] memberLabels, LocalBuilder memberIndexLocal, LocalBuilder requiredIndexLocal) inline private
Definition at line 337 of file XmlFormatReaderGenerator.cs.
        {
            int num = ((classContract.BaseContract != null) ? ReadMembers(classContract.BaseContract, requiredMembers, memberLabels, memberIndexLocal, requiredIndexLocal) : 0);
            int num2 = 0;
            while (num2 < classContract.Members.Count)
            {
                DataMember dataMember = classContract.Members[num2];
                Type memberType = dataMember.MemberType;
                _ilg.Case(memberLabels[num], dataMember.Name);
                if (dataMember.IsRequired)
                {
                    int i;
                    for (i = num + 1; i < requiredMembers.Length && !requiredMembers[i]; i++)
                    {
                    }
                    _ilg.Set(requiredIndexLocal, i);
                }
                LocalBuilder localBuilder = null;
                if (dataMember.IsGetOnlyCollection)
                {
                    _ilg.LoadAddress(_objectLocal);
                    _ilg.LoadMember(dataMember.MemberInfo);
                    localBuilder = _ilg.DeclareLocal(memberType, dataMember.Name + "Value");
                    _ilg.Stloc(localBuilder);
                    _ilg.Call(_contextArg, XmlFormatGeneratorStatics.StoreCollectionMemberInfoMethod, localBuilder);
                    ReadValue(memberType, dataMember.Name, classContract.StableName.Namespace);
                }
                else
                {
                    _ilg.Call(_contextArg, XmlFormatGeneratorStatics.ResetCollectionMemberInfoMethod);
                    localBuilder = ReadValue(memberType, dataMember.Name, classContract.StableName.Namespace);
                    _ilg.LoadAddress(_objectLocal);
                    _ilg.ConvertAddress(_objectLocal.LocalType, _objectType);
                    _ilg.Ldloc(localBuilder);
                    _ilg.StoreMember(dataMember.MemberInfo);
                }
                _ilg.Set(memberIndexLocal, num);
                _ilg.EndCase();
                num2++;
                num++;
            }
            return num;
        }
References System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper._contextArg, System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper._ilg, System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper._objectLocal, System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper._objectType, System.Runtime.Serialization.CodeGenerator.Call(), System.Runtime.Serialization.CodeGenerator.Case(), System.Runtime.Serialization.CodeGenerator.ConvertAddress(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Runtime.Serialization.CodeGenerator.DeclareLocal(), System.Runtime.Serialization.Dictionary, System.Runtime.Serialization.CodeGenerator.EndCase(), System.Runtime.Serialization.CodeGenerator.Ldloc(), System.Runtime.Serialization.CodeGenerator.LoadAddress(), System.Runtime.Serialization.CodeGenerator.LoadMember(), System.Reflection.Emit.LocalBuilder.LocalType, System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.ReadMembers(), System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.ReadValue(), System.Runtime.Serialization.XmlFormatGeneratorStatics.ResetCollectionMemberInfoMethod, System.Runtime.Serialization.CodeGenerator.Set(), System.Runtime.Serialization.CodeGenerator.Stloc(), System.Runtime.Serialization.XmlFormatGeneratorStatics.StoreCollectionMemberInfoMethod, and System.Runtime.Serialization.CodeGenerator.StoreMember().