Terraria: System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.GenerateCollectionReaderHelper
GenerateCollectionReaderHelper()
CodeGenerator System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.GenerateCollectionReaderHelper (CollectionDataContract collectionContract, bool isGetOnlyCollection) inline private
Definition at line 149 of file XmlFormatReaderGenerator.cs.
        {
            _ilg = new CodeGenerator();
            bool flag = collectionContract.RequiresMemberAccessForRead(null);
            try
            {
                if (isGetOnlyCollection)
                {
                    _ilg.BeginMethod("Read" + collectionContract.StableName.Name + "FromXmlIsGetOnly", Globals.TypeOfXmlFormatGetOnlyCollectionReaderDelegate, flag);
                }
                else
                {
                    _ilg.BeginMethod("Read" + collectionContract.StableName.Name + "FromXml" + string.Empty, Globals.TypeOfXmlFormatCollectionReaderDelegate, flag);
                }
            }
            catch (SecurityException securityException)
            {
                if (!flag)
                {
                    throw;
                }
                collectionContract.RequiresMemberAccessForRead(securityException);
            }
            InitArgs();
            _collectionContractArg = _ilg.GetArg(4);
            return _ilg;
        }
References System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper._collectionContractArg, System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper._ilg, System.Runtime.Serialization.CodeGenerator.BeginMethod(), System.Runtime.Serialization.CodeGenerator.GetArg(), System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.InitArgs(), System.Runtime.Serialization.Globals.TypeOfXmlFormatCollectionReaderDelegate, and System.Runtime.Serialization.Globals.TypeOfXmlFormatGetOnlyCollectionReaderDelegate.
Referenced by System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.GenerateCollectionReader(), and System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.GenerateGetOnlyCollectionReader().