Terraria: System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.CreateObject
CreateObject()
void System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.CreateObject (ClassDataContract classContract) inline private
Definition at line 188 of file XmlFormatReaderGenerator.cs.
        {
            Type type = (_objectType = classContract.UnderlyingType);
            if (type.IsValueType && !classContract.IsNonAttributedType)
            {
                type = Globals.TypeOfValueType;
            }
            _objectLocal = _ilg.DeclareLocal(type, "objectDeserialized");
            if (classContract.UnderlyingType == Globals.TypeOfDBNull)
            {
                _ilg.LoadMember(GetDBNullValueField());
                _ilg.Stloc(_objectLocal);
            }
            else if (classContract.IsNonAttributedType)
            {
                if (type.IsValueType)
                {
                    _ilg.Ldloca(_objectLocal);
                    _ilg.InitObj(type);
                }
                else
                {
                    _ilg.New(classContract.GetNonAttributedTypeConstructor());
                    _ilg.Stloc(_objectLocal);
                }
            }
            else
            {
                _ilg.Call(null, XmlFormatGeneratorStatics.GetUninitializedObjectMethod, DataContract.GetIdForInitialization(classContract));
                _ilg.ConvertValue(Globals.TypeOfObject, type);
                _ilg.Stloc(_objectLocal);
            }
        }
References System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper._ilg, System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper._objectLocal, System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper._objectType, System.Runtime.Serialization.CodeGenerator.Call(), System.Runtime.Serialization.CodeGenerator.ConvertValue(), System.Runtime.Serialization.CodeGenerator.DeclareLocal(), System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.GetDBNullValueField(), System.Runtime.Serialization.DataContract.GetIdForInitialization(), System.Runtime.Serialization.XmlFormatGeneratorStatics.GetUninitializedObjectMethod, System.Runtime.Serialization.CodeGenerator.InitObj(), System.Runtime.Serialization.CodeGenerator.Ldloca(), System.Runtime.Serialization.CodeGenerator.LoadMember(), System.Runtime.Serialization.CodeGenerator.New(), System.Runtime.Serialization.CodeGenerator.Stloc(), System.type, System.Runtime.Serialization.Globals.TypeOfDBNull, System.Runtime.Serialization.Globals.TypeOfObject, and System.Runtime.Serialization.Globals.TypeOfValueType.
Referenced by System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.GenerateClassReader().