Terraria: System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.InitArgs
InitArgs()
void System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.InitArgs () inline private
Definition at line 177 of file XmlFormatReaderGenerator.cs.
        {
            _xmlReaderArg = _ilg.GetArg(0);
            _contextArg = _ilg.GetArg(1);
            _memberNamesArg = _ilg.GetArg(2);
            _memberNamespacesArg = _ilg.GetArg(3);
        }
References System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper._contextArg, System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper._ilg, System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper._memberNamesArg, System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper._memberNamespacesArg, System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper._xmlReaderArg, and System.Runtime.Serialization.CodeGenerator.GetArg().
Referenced by System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.GenerateClassReader(), and System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.GenerateCollectionReaderHelper().