Terraria: System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.GenerateClassReader
GenerateClassReader()
XmlFormatClassReaderDelegate System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.GenerateClassReader (ClassDataContract classContract) inline
Definition at line 38 of file XmlFormatReaderGenerator.cs.
        {
            if (DataContractSerializer.Option == SerializationOption.ReflectionOnly)
            {
                return CreateReflectionXmlClassReader(classContract);
            }
            _ilg = new CodeGenerator();
            bool flag = classContract.RequiresMemberAccessForRead(null);
            try
            {
                _ilg.BeginMethod("Read" + classContract.StableName.Name + "FromXml", Globals.TypeOfXmlFormatClassReaderDelegate, flag);
            }
            catch (SecurityException securityException)
            {
                if (!flag)
                {
                    throw;
                }
                classContract.RequiresMemberAccessForRead(securityException);
            }
            InitArgs();
            CreateObject(classContract);
            _ilg.Call(_contextArg, XmlFormatGeneratorStatics.AddNewObjectMethod, _objectLocal);
            InvokeOnDeserializing(classContract);
            LocalBuilder localBuilder = null;
            if (HasFactoryMethod(classContract))
            {
                localBuilder = _ilg.DeclareLocal(Globals.TypeOfString, "objectIdRead");
                _ilg.Call(_contextArg, XmlFormatGeneratorStatics.GetObjectIdMethod);
                _ilg.Stloc(localBuilder);
            }
            if (classContract.IsISerializable)
            {
                ReadISerializable(classContract);
            }
            else
            {
                ReadClass(classContract);
            }
            InvokeFactoryMethod(classContract, localBuilder);
            if (Globals.TypeOfIDeserializationCallback.IsAssignableFrom(classContract.UnderlyingType))
            {
                _ilg.Call(_objectLocal, XmlFormatGeneratorStatics.OnDeserializationMethod, null);
            }
            InvokeOnDeserialized(classContract);
            if (localBuilder == null)
            {
                _ilg.Load(_objectLocal);
                if (classContract.UnderlyingType == Globals.TypeOfDateTimeOffsetAdapter)
                {
                    _ilg.ConvertValue(_objectLocal.LocalType, Globals.TypeOfDateTimeOffsetAdapter);
                    _ilg.Call(XmlFormatGeneratorStatics.GetDateTimeOffsetMethod);
                    _ilg.ConvertValue(Globals.TypeOfDateTimeOffset, _ilg.CurrentMethod.ReturnType);
                }
                else if (classContract.UnderlyingType == Globals.TypeOfMemoryStreamAdapter)
                {
                    _ilg.ConvertValue(_objectLocal.LocalType, Globals.TypeOfMemoryStreamAdapter);
                    _ilg.Call(XmlFormatGeneratorStatics.GetMemoryStreamMethod);
                    _ilg.ConvertValue(Globals.TypeOfMemoryStream, _ilg.CurrentMethod.ReturnType);
                }
                else if (classContract.IsKeyValuePairAdapter)
                {
                    _ilg.Call(classContract.GetKeyValuePairMethodInfo);
                    _ilg.ConvertValue(Globals.TypeOfKeyValuePair.MakeGenericType(classContract.KeyValuePairGenericArguments), _ilg.CurrentMethod.ReturnType);
                }
                else
                {
                    _ilg.ConvertValue(_objectLocal.LocalType, _ilg.CurrentMethod.ReturnType);
                }
            }
            return (XmlFormatClassReaderDelegate)_ilg.EndMethod();
        }
References System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper._contextArg, System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper._ilg, System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper._objectLocal, System.Runtime.Serialization.XmlFormatGeneratorStatics.AddNewObjectMethod, System.Runtime.Serialization.CodeGenerator.BeginMethod(), System.Runtime.Serialization.CodeGenerator.Call(), System.Runtime.Serialization.CodeGenerator.ConvertValue(), System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.CreateObject(), System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.CreateReflectionXmlClassReader(), System.Runtime.Serialization.CodeGenerator.CurrentMethod, System.Runtime.Serialization.CodeGenerator.DeclareLocal(), System.Runtime.Serialization.CodeGenerator.EndMethod(), System.Runtime.Serialization.XmlFormatGeneratorStatics.GetDateTimeOffsetMethod, System.Runtime.Serialization.XmlFormatGeneratorStatics.GetMemoryStreamMethod, System.Runtime.Serialization.XmlFormatGeneratorStatics.GetObjectIdMethod, System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.HasFactoryMethod(), System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.InitArgs(), System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.InvokeFactoryMethod(), System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.InvokeOnDeserialized(), System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.InvokeOnDeserializing(), System.Runtime.Serialization.CodeGenerator.Load(), System.Reflection.Emit.LocalBuilder.LocalType, System.Runtime.Serialization.XmlFormatGeneratorStatics.OnDeserializationMethod, System.Runtime.Serialization.DataContractSerializer.Option, System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.ReadClass(), System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.ReadISerializable(), System.Reflection.MethodInfo.ReturnType, System.Runtime.Serialization.CodeGenerator.Stloc(), System.Runtime.Serialization.Globals.TypeOfDateTimeOffset, System.Runtime.Serialization.Globals.TypeOfDateTimeOffsetAdapter, System.Runtime.Serialization.Globals.TypeOfIDeserializationCallback, System.Runtime.Serialization.Globals.TypeOfKeyValuePair, System.Runtime.Serialization.Globals.TypeOfMemoryStream, System.Runtime.Serialization.Globals.TypeOfMemoryStreamAdapter, System.Runtime.Serialization.Globals.TypeOfString, and System.Runtime.Serialization.Globals.TypeOfXmlFormatClassReaderDelegate.
Referenced by System.Runtime.Serialization.XmlFormatReaderGenerator.GenerateClassReader().