Terraria: System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.GenerateGetOnlyCollectionReader
GenerateGetOnlyCollectionReader()
XmlFormatGetOnlyCollectionReaderDelegate System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.GenerateGetOnlyCollectionReader (CollectionDataContract collectionContract) inline
Definition at line 138 of file XmlFormatReaderGenerator.cs.
        {
            if (DataContractSerializer.Option == SerializationOption.ReflectionOnly)
            {
                return CreateReflectionReadGetOnlyCollectionReader();
            }
            _ilg = GenerateCollectionReaderHelper(collectionContract, isGetOnlyCollection: true);
            ReadGetOnlyCollection(collectionContract);
            return (XmlFormatGetOnlyCollectionReaderDelegate)_ilg.EndMethod();
        }
References System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper._ilg, System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.CreateReflectionReadGetOnlyCollectionReader(), System.Runtime.Serialization.CodeGenerator.EndMethod(), System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.GenerateCollectionReaderHelper(), System.Runtime.Serialization.DataContractSerializer.Option, and System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.ReadGetOnlyCollection().
Referenced by System.Runtime.Serialization.XmlFormatReaderGenerator.GenerateGetOnlyCollectionReader().