Terraria: System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.ThrowValidationException
ThrowValidationException() [1/2]
void System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.ThrowValidationException () inline private
Definition at line 870 of file XmlFormatReaderGenerator.cs.
        {
            _ilg.Call(XmlFormatGeneratorStatics.CreateSerializationExceptionMethod);
            _ilg.Throw();
        }
References System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper._ilg, System.Runtime.Serialization.CodeGenerator.Call(), System.Runtime.Serialization.XmlFormatGeneratorStatics.CreateSerializationExceptionMethod, and System.Runtime.Serialization.CodeGenerator.Throw().
Referenced by System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.ReadValue(), and System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.ThrowValidationException().