Terraria: System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.ReadCollection
ReadCollection()
void System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.ReadCollection (CollectionDataContract collectionContract) inline private
Definition at line 539 of file XmlFormatReaderGenerator.cs.
        {
            Type type = collectionContract.UnderlyingType;
            Type itemType = collectionContract.ItemType;
            bool flag = collectionContract.Kind == CollectionKind.Array;
            ConstructorInfo constructorInfo = collectionContract.Constructor;
            if (type.IsInterface)
            {
                switch (collectionContract.Kind)
                {
                case CollectionKind.GenericDictionary:
                    type = Globals.TypeOfDictionaryGeneric.MakeGenericType(itemType.GetGenericArguments());
                    constructorInfo = type.GetConstructor(BindingFlags.Instance | BindingFlags.Public, Type.EmptyTypes);
                    break;
                case CollectionKind.Dictionary:
                    type = Globals.TypeOfHashtable;
                    constructorInfo = XmlFormatGeneratorStatics.HashtableCtor;
                    break;
                case CollectionKind.GenericList:
                case CollectionKind.GenericCollection:
                case CollectionKind.List:
                case CollectionKind.GenericEnumerable:
                case CollectionKind.Collection:
                case CollectionKind.Enumerable:
                    type = itemType.MakeArrayType();
                    flag = true;
                    break;
                }
            }
            string itemName = collectionContract.ItemName;
            string @namespace = collectionContract.StableName.Namespace;
            _objectLocal = _ilg.DeclareLocal(type, "objectDeserialized");
            if (!flag)
            {
                if (type.IsValueType)
                {
                    _ilg.Ldloca(_objectLocal);
                    _ilg.InitObj(type);
                }
                else
                {
                    _ilg.New(constructorInfo);
                    _ilg.Stloc(_objectLocal);
                    _ilg.Call(_contextArg, XmlFormatGeneratorStatics.AddNewObjectMethod, _objectLocal);
                }
            }
            LocalBuilder localBuilder = _ilg.DeclareLocal(Globals.TypeOfInt, "arraySize");
            _ilg.Call(_contextArg, XmlFormatGeneratorStatics.GetArraySizeMethod);
            _ilg.Stloc(localBuilder);
            LocalBuilder localBuilder2 = _ilg.DeclareLocal(Globals.TypeOfString, "objectIdRead");
            _ilg.Call(_contextArg, XmlFormatGeneratorStatics.GetObjectIdMethod);
            _ilg.Stloc(localBuilder2);
            bool flag2 = false;
            if (flag && TryReadPrimitiveArray(type, itemType, localBuilder))
            {
                flag2 = true;
                _ilg.IfNot();
            }
            _ilg.If(localBuilder, Cmp.EqualTo, -1);
            LocalBuilder localBuilder3 = null;
            if (flag)
            {
                localBuilder3 = _ilg.DeclareLocal(type, "growingCollection");
                _ilg.NewArray(itemType, 32);
                _ilg.Stloc(localBuilder3);
            }
            LocalBuilder localBuilder4 = _ilg.DeclareLocal(Globals.TypeOfInt, "i");
            object forState = _ilg.For(localBuilder4, 0, int.MaxValue);
            IsStartElement(_memberNamesArg, _memberNamespacesArg);
            _ilg.If();
            _ilg.Call(_contextArg, XmlFormatGeneratorStatics.IncrementItemCountMethod, 1);
            LocalBuilder value = ReadCollectionItem(collectionContract, itemType, itemName, @namespace);
            if (flag)
            {
                MethodInfo methodInfo = XmlFormatGeneratorStatics.EnsureArraySizeMethod.MakeGenericMethod(itemType);
                _ilg.Call(null, methodInfo, localBuilder3, localBuilder4);
                _ilg.Stloc(localBuilder3);
                _ilg.StoreArrayElement(localBuilder3, localBuilder4, value);
            }
            else
            {
                StoreCollectionValue(_objectLocal, value, collectionContract);
            }
            _ilg.Else();
            IsEndElement();
            _ilg.If();
            _ilg.Break(forState);
            _ilg.Else();
            HandleUnexpectedItemInCollection(localBuilder4);
            _ilg.EndIf();
            _ilg.EndIf();
            _ilg.EndFor();
            if (flag)
            {
                MethodInfo methodInfo2 = XmlFormatGeneratorStatics.TrimArraySizeMethod.MakeGenericMethod(itemType);
                _ilg.Call(null, methodInfo2, localBuilder3, localBuilder4);
                _ilg.Stloc(_objectLocal);
                _ilg.Call(_contextArg, XmlFormatGeneratorStatics.AddNewObjectWithIdMethod, localBuilder2, _objectLocal);
            }
            _ilg.Else();
            _ilg.Call(_contextArg, XmlFormatGeneratorStatics.IncrementItemCountMethod, localBuilder);
            if (flag)
            {
                _ilg.NewArray(itemType, localBuilder);
                _ilg.Stloc(_objectLocal);
                _ilg.Call(_contextArg, XmlFormatGeneratorStatics.AddNewObjectMethod, _objectLocal);
            }
            LocalBuilder localBuilder5 = _ilg.DeclareLocal(Globals.TypeOfInt, "j");
            _ilg.For(localBuilder5, 0, localBuilder);
            IsStartElement(_memberNamesArg, _memberNamespacesArg);
            _ilg.If();
            LocalBuilder value2 = ReadCollectionItem(collectionContract, itemType, itemName, @namespace);
            if (flag)
            {
                _ilg.StoreArrayElement(_objectLocal, localBuilder5, value2);
            }
            else
            {
                StoreCollectionValue(_objectLocal, value2, collectionContract);
            }
            _ilg.Else();
            HandleUnexpectedItemInCollection(localBuilder5);
            _ilg.EndIf();
            _ilg.EndFor();
            _ilg.Call(_contextArg, XmlFormatGeneratorStatics.CheckEndOfArrayMethod, _xmlReaderArg, localBuilder, _memberNamesArg, _memberNamespacesArg);
            _ilg.EndIf();
            if (flag2)
            {
                _ilg.Else();
                _ilg.Call(_contextArg, XmlFormatGeneratorStatics.AddNewObjectWithIdMethod, localBuilder2, _objectLocal);
                _ilg.EndIf();
            }
        }
References System.Collections.Generic.Dictionary< TKey, TValue >.Dictionary(), System.Runtime.Serialization.XmlFormatGeneratorStatics.AddNewObjectMethod, System.Runtime.Serialization.XmlFormatGeneratorStatics.AddNewObjectWithIdMethod, System.Runtime.Serialization.CodeGenerator.Break(), System.Runtime.Serialization.CodeGenerator.Call(), System.Runtime.Serialization.XmlFormatGeneratorStatics.CheckEndOfArrayMethod, System.Runtime.Serialization.CodeGenerator.DeclareLocal(), System.Runtime.Serialization.Dictionary, System.Runtime.Serialization.CodeGenerator.Else(), System.Type.EmptyTypes, System.Runtime.Serialization.CodeGenerator.EndFor(), System.Runtime.Serialization.CodeGenerator.EndIf(), System.Runtime.Serialization.XmlFormatGeneratorStatics.EnsureArraySizeMethod, System.Runtime.Serialization.CodeGenerator.For(), System.Runtime.Serialization.XmlFormatGeneratorStatics.GetArraySizeMethod, System.Runtime.Serialization.XmlFormatGeneratorStatics.GetObjectIdMethod, System.Runtime.Serialization.XmlFormatGeneratorStatics.HashtableCtor, System.Runtime.Serialization.CodeGenerator.If(), System.Runtime.Serialization.CodeGenerator.IfNot(), System.Runtime.Serialization.XmlFormatGeneratorStatics.IncrementItemCountMethod, System.Runtime.Serialization.CodeGenerator.InitObj(), System.Runtime.Serialization.CodeGenerator.Ldloca(), System.Reflection.MaxValue, System.Runtime.Serialization.CodeGenerator.New(), System.Runtime.Serialization.CodeGenerator.NewArray(), System.Runtime.Serialization.CodeGenerator.Stloc(), System.Runtime.Serialization.CodeGenerator.StoreArrayElement(), System.Runtime.Serialization.XmlFormatGeneratorStatics.TrimArraySizeMethod, System.type, System.Runtime.Serialization.Globals.TypeOfDictionaryGeneric, System.Runtime.Serialization.Globals.TypeOfHashtable, System.Runtime.Serialization.Globals.TypeOfInt, System.Runtime.Serialization.Globals.TypeOfString, and System.value.
Referenced by System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.GenerateCollectionReader().