Terraria: System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.HandleUnexpectedItemInCollection
HandleUnexpectedItemInCollection()
void System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.HandleUnexpectedItemInCollection (LocalBuilder iterator) inline private
Definition at line 829 of file XmlFormatReaderGenerator.cs.
        {
            IsStartElement();
            _ilg.If();
            _ilg.Call(_contextArg, XmlFormatGeneratorStatics.SkipUnknownElementMethod, _xmlReaderArg);
            _ilg.Dec(iterator);
            _ilg.Else();
            ThrowUnexpectedStateException(XmlNodeType.Element);
            _ilg.EndIf();
        }
References System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper._contextArg, System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper._ilg, System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper._xmlReaderArg, System.Runtime.Serialization.CodeGenerator.Call(), System.Runtime.Serialization.CodeGenerator.Dec(), System.Runtime.Serialization.CodeGenerator.Else(), System.Runtime.Serialization.CodeGenerator.EndIf(), System.Runtime.Serialization.CodeGenerator.If(), System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.IsStartElement(), System.Runtime.Serialization.XmlFormatGeneratorStatics.SkipUnknownElementMethod, and System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.ThrowUnexpectedStateException().