Terraria: System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.InvokeOnDeserializing
InvokeOnDeserializing()
void System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.InvokeOnDeserializing (ClassDataContract classContract) inline private
Definition at line 227 of file XmlFormatReaderGenerator.cs.
        {
            if (classContract.BaseContract != null)
            {
                InvokeOnDeserializing(classContract.BaseContract);
            }
            if (classContract.OnDeserializing != null)
            {
                _ilg.LoadAddress(_objectLocal);
                _ilg.ConvertAddress(_objectLocal.LocalType, _objectType);
                _ilg.Load(_contextArg);
                _ilg.LoadMember(XmlFormatGeneratorStatics.GetStreamingContextMethod);
                _ilg.Call(classContract.OnDeserializing);
            }
        }
References System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper._contextArg, System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper._ilg, System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper._objectLocal, System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper._objectType, System.Runtime.Serialization.CodeGenerator.Call(), System.Runtime.Serialization.CodeGenerator.ConvertAddress(), System.Runtime.Serialization.XmlFormatGeneratorStatics.GetStreamingContextMethod, System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.InvokeOnDeserializing(), System.Runtime.Serialization.CodeGenerator.Load(), System.Runtime.Serialization.CodeGenerator.LoadAddress(), System.Runtime.Serialization.CodeGenerator.LoadMember(), and System.Reflection.Emit.LocalBuilder.LocalType.
Referenced by System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.GenerateClassReader(), and System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.InvokeOnDeserializing().