Terraria: System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.TryReadPrimitiveArray
TryReadPrimitiveArray()
bool System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.TryReadPrimitiveArray (Type type, Type itemType, LocalBuilder size) inline private
Definition at line 732 of file XmlFormatReaderGenerator.cs.
        {
            PrimitiveDataContract primitiveDataContract = PrimitiveDataContract.GetPrimitiveDataContract(itemType);
            if (primitiveDataContract == null)
            {
                return false;
            }
            string text = null;
            switch (itemType.GetTypeCode())
            {
            case TypeCode.Boolean:
                text = "TryReadBooleanArray";
                break;
            case TypeCode.DateTime:
                text = "TryReadDateTimeArray";
                break;
            case TypeCode.Decimal:
                text = "TryReadDecimalArray";
                break;
            case TypeCode.Int32:
                text = "TryReadInt32Array";
                break;
            case TypeCode.Int64:
                text = "TryReadInt64Array";
                break;
            case TypeCode.Single:
                text = "TryReadSingleArray";
                break;
            case TypeCode.Double:
                text = "TryReadDoubleArray";
                break;
            }
            if (text != null)
            {
                _ilg.Load(_xmlReaderArg);
                _ilg.Load(_contextArg);
                _ilg.Load(_memberNamesArg);
                _ilg.Load(_memberNamespacesArg);
                _ilg.Load(size);
                _ilg.Ldloca(_objectLocal);
                _ilg.Call(typeof(XmlReaderDelegator).GetMethod(text, BindingFlags.Instance | BindingFlags.Static | BindingFlags.Public | BindingFlags.NonPublic));
                return true;
            }
            return false;
        }
References System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper._contextArg, System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper._ilg, System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper._memberNamesArg, System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper._memberNamespacesArg, System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper._objectLocal, System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper._xmlReaderArg, System.Runtime.Serialization.CodeGenerator.Call(), System.Runtime.Serialization.Dictionary, System.Runtime.Serialization.PrimitiveDataContract.GetPrimitiveDataContract(), System.Runtime.Serialization.CodeGenerator.Ldloca(), System.Runtime.Serialization.CodeGenerator.Load(), and System.text.