Terraria: System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.GenerateCollectionReader
GenerateCollectionReader()
XmlFormatCollectionReaderDelegate System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.GenerateCollectionReader (CollectionDataContract collectionContract) inline
Definition at line 118 of file XmlFormatReaderGenerator.cs.
        {
            if (DataContractSerializer.Option == SerializationOption.ReflectionOnly)
            {
                return CreateReflectionXmlCollectionReader();
            }
            _ilg = GenerateCollectionReaderHelper(collectionContract, isGetOnlyCollection: false);
            ReadCollection(collectionContract);
            _ilg.Load(_objectLocal);
            _ilg.ConvertValue(_objectLocal.LocalType, _ilg.CurrentMethod.ReturnType);
            return (XmlFormatCollectionReaderDelegate)_ilg.EndMethod();
        }
References System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper._ilg, System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper._objectLocal, System.Runtime.Serialization.CodeGenerator.ConvertValue(), System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.CreateReflectionXmlCollectionReader(), System.Runtime.Serialization.CodeGenerator.CurrentMethod, System.Runtime.Serialization.CodeGenerator.EndMethod(), System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.GenerateCollectionReaderHelper(), System.Runtime.Serialization.CodeGenerator.Load(), System.Reflection.Emit.LocalBuilder.LocalType, System.Runtime.Serialization.DataContractSerializer.Option, System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.ReadCollection(), and System.Reflection.MethodInfo.ReturnType.
Referenced by System.Runtime.Serialization.XmlFormatReaderGenerator.GenerateCollectionReader().