Terraria: System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.ReadMembers
ReadMembers() [2/2]
void System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.ReadMembers (ClassDataContract classContract, LocalBuilder extensionDataLocal) inline private
Definition at line 304 of file XmlFormatReaderGenerator.cs.
        {
            int num = classContract.MemberNames.Length;
            _ilg.Call(_contextArg, XmlFormatGeneratorStatics.IncrementItemCountMethod, num);
            LocalBuilder localBuilder = _ilg.DeclareLocal(Globals.TypeOfInt, "memberIndex", -1);
            int firstRequiredMember;
            bool[] requiredMembers = GetRequiredMembers(classContract, out firstRequiredMember);
            bool flag = firstRequiredMember < num;
            LocalBuilder localBuilder2 = (flag ? _ilg.DeclareLocal(Globals.TypeOfInt, "requiredIndex", firstRequiredMember) : null);
            object forState = _ilg.For(null, null, null);
            _ilg.Call(null, XmlFormatGeneratorStatics.MoveToNextElementMethod, _xmlReaderArg);
            _ilg.IfFalseBreak(forState);
            if (flag)
            {
                _ilg.Call(_contextArg, XmlFormatGeneratorStatics.GetMemberIndexWithRequiredMembersMethod, _xmlReaderArg, _memberNamesArg, _memberNamespacesArg, localBuilder, localBuilder2, extensionDataLocal);
            }
            else
            {
                _ilg.Call(_contextArg, XmlFormatGeneratorStatics.GetMemberIndexMethod, _xmlReaderArg, _memberNamesArg, _memberNamespacesArg, localBuilder, extensionDataLocal);
            }
            Label[] memberLabels = _ilg.Switch(num);
            ReadMembers(classContract, requiredMembers, memberLabels, localBuilder, localBuilder2);
            _ilg.EndSwitch();
            _ilg.EndFor();
            if (flag)
            {
                _ilg.If(localBuilder2, Cmp.LessThan, num);
                _ilg.Call(null, XmlFormatGeneratorStatics.ThrowRequiredMemberMissingExceptionMethod, _xmlReaderArg, localBuilder, localBuilder2, _memberNamesArg);
                _ilg.EndIf();
            }
        }
References System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper._contextArg, System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper._ilg, System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper._memberNamesArg, System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper._memberNamespacesArg, System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper._xmlReaderArg, System.Runtime.Serialization.CodeGenerator.Call(), System.Runtime.Serialization.CodeGenerator.DeclareLocal(), System.Runtime.Serialization.Dictionary, System.Runtime.Serialization.CodeGenerator.EndFor(), System.Runtime.Serialization.CodeGenerator.EndIf(), System.Runtime.Serialization.CodeGenerator.EndSwitch(), System.Runtime.Serialization.CodeGenerator.For(), System.Runtime.Serialization.XmlFormatGeneratorStatics.GetMemberIndexMethod, System.Runtime.Serialization.XmlFormatGeneratorStatics.GetMemberIndexWithRequiredMembersMethod, System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.GetRequiredMembers(), System.Runtime.Serialization.CodeGenerator.If(), System.Runtime.Serialization.CodeGenerator.IfFalseBreak(), System.Runtime.Serialization.XmlFormatGeneratorStatics.IncrementItemCountMethod, System.Runtime.Serialization.XmlFormatGeneratorStatics.MoveToNextElementMethod, System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.ReadMembers(), System.Runtime.Serialization.CodeGenerator.Switch(), System.Runtime.Serialization.XmlFormatGeneratorStatics.ThrowRequiredMemberMissingExceptionMethod, and System.Runtime.Serialization.Globals.TypeOfInt.
Referenced by System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.ReadClass(), System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.ReadMembers(), and System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.ReadMembers().