Terraria: ChatManager.DrawColorCodedString
DrawColorCodedString() [2/2]
static Vector2 ChatManager.DrawColorCodedString (SpriteBatch spriteBatch, DynamicSpriteFont font, TextSnippet[] snippets, Vector2 position, Color baseColor, float rotation, Vector2 origin, Vector2 baseScale, out int hoveredSnippet, float maxWidth, bool ignoreColors = false) inline static
     {
         int num = -1;
         Vector2 vec = new Vector2(Main.mouseX, Main.mouseY);
         Vector2 vector = position;
         Vector2 result = vector;
         float x = font.MeasureString(" ").X;
         Color color = baseColor;
         float num2 = 1f;
         float num3 = 0f;
         for (int i = 0; i < snippets.Length; i++)
         {
             TextSnippet textSnippet = snippets[i];
             textSnippet.Update();
             if (!ignoreColors)
             {
                 color = textSnippet.GetVisibleColor();
             }
             num2 = textSnippet.Scale;
             if (textSnippet.UniqueDraw(justCheckingString: false, out var size, spriteBatch, vector, color, num2))
             {
                 if (vec.Between(vector, vector + size))
                 {
                     num = i;
                 }
                 vector.X += size.X * baseScale.X * num2;
                 result.X = Math.Max(result.X, vector.X);
                 continue;
             }
             string[] array = textSnippet.Text.Split('\n');
             array = Regex.Split(textSnippet.Text, "(\n)");
             bool flag = true;
             foreach (string text in array)
             {
                 string[] array2 = Regex.Split(text, "( )");
                 array2 = text.Split(' ');
                 if (text == "\n")
                 {
                     vector.Y += (float)font.LineSpacing * num3 * baseScale.Y;
                     vector.X = position.X;
                     result.Y = Math.Max(result.Y, vector.Y);
                     num3 = 0f;
                     flag = false;
                     continue;
                 }
                 for (int k = 0; k < array2.Length; k++)
                 {
                     if (k != 0)
                     {
                         vector.X += x * baseScale.X * num2;
                     }
                     if (maxWidth > 0f)
                     {
                         float num4 = font.MeasureString(array2[k]).X * baseScale.X * num2;
                         if (vector.X - position.X + num4 > maxWidth)
{
                             vector.X = position.X;
                             vector.Y += (float)font.LineSpacing * num3 * baseScale.Y;
                             result.Y = Math.Max(result.Y, vector.Y);
                             num3 = 0f;
                         }
                     }
                     if (num3 < num2)
                     {
                         num3 = num2;
                     }
                     DynamicSpriteFontExtensionMethods.DrawString(spriteBatch, font, array2[k], vector, color, rotation, origin, baseScale * textSnippet.Scale * num2, SpriteEffects.None, 0f);
                     Vector2 vector2 = font.MeasureString(array2[k]);
                     if (vec.Between(vector, vector + vector2))
                     {
                         num = i;
                     }
                     vector.X += vector2.X * baseScale.X * num2;
                     result.X = Math.Max(result.X, vector.X);
                 }
                 if (array.Length > 1 && flag)
                 {
                     vector.Y += (float)font.LineSpacing * num3 * baseScale.Y;
                     vector.X = position.X;
                     result.Y = Math.Max(result.Y, vector.Y);
                     num3 = 0f;
                 }
                 flag = true;
             }
         }
         hoveredSnippet = num;
         return result;
     }
References Color, DynamicSpriteFontExtensionMethods.DrawString(), TextSnippet.GetVisibleColor(), DynamicSpriteFont.LineSpacing, DynamicSpriteFont.MeasureString(), Main.mouseX, Main.mouseY, TextSnippet.Scale, TextSnippet.Text, TextSnippet.UniqueDraw(), and TextSnippet.Update().
Referenced by Segments.LocalizedTextSegment.Draw(), DrawColorCodedStringShadow(), DrawColorCodedStringWithShadow(), Main.DrawInterface_14_EntityHealthBars(), Main.DrawNetplayStatusText(), Main.DrawNPCChatButtons(), and UIText.DrawSelf().