Terraria: System.Xml.Xsl.XsltOld.InputScopeManager.ResolveXmlNamespace
ResolveXmlNamespace()
string System.Xml.Xsl.XsltOld.InputScopeManager.ResolveXmlNamespace (string prefix) inline
Definition at line 83 of file InputScopeManager.cs.
    {
        if (prefix.Length == 0)
        {
            return _defaultNS;
        }
        return ResolveNonEmptyPrefix(prefix);
    }
References System.Xml.Xsl.XsltOld.InputScopeManager._defaultNS, System.prefix, and System.Xml.Xsl.XsltOld.InputScopeManager.ResolveNonEmptyPrefix().
Referenced by System.Xml.Xsl.XsltOld.Compiler.CreateXmlQName(), System.Xml.Xsl.XsltOld.XsltCompileContext.ElementAvailable(), System.Xml.Xsl.XsltOld.Compiler.ResolvePrefixes(), and System.Xml.Xsl.XsltOld.Compiler.ResolveXmlNamespace().