Terraria: StyleDimension.FromPixels
FromPixels()
static StyleDimension StyleDimension.FromPixels (float pixels) inline static
     {
         return new StyleDimension(pixels, 0f);
     }
References StyleDimension().
Referenced by EmotesGroupListItem.EmotesGroupListItem(), GroupOptionButton< T >.GroupOptionButton(), UICharacterNameButton.UICharacterNameButton(), UIClothStyleButton.UIClothStyleButton(), UIDifficultyButton.UIDifficultyButton(), UIHairStyleButton.UIHairStyleButton(), UIIconTextButton.UIIconTextButton(), UIResourcePack.UIResourcePack(), UIWorkshopHub.AddDescriptionPanel(), UIWorldCreation.AddDescriptionPanel(), AWorkshopPublishInfoState< TPublishedObjectType >.AddDescriptionPanel(), UIWorkshopHub.AddHorizontalSeparator(), UIWorldCreation.AddHorizontalSeparator(), AWorkshopPublishInfoState< TPublishedObjectType >.AddHorizontalSeparator(), AWorkshopPublishInfoState< TPublishedObjectType >.AddUIList(), UIResourcePack.BuildChildren(), UICharacterCreation.BuildPage(), UIReportsPage.BuildPage(), UIResourcePackInfoMenu.BuildPage(), UIWorldCreation.BuildPage(), AWorkshopPublishInfoState< TPublishedObjectType >.CreateInsturctionsPanel(), AWorkshopPublishInfoState< TPublishedObjectType >.CreateSteamDisclaimer(), AWorkshopPublishInfoState< TPublishedObjectType >.CreateStylizedCategoryPanel(), UIEmotesMenu.InitializePage(), UICharacterCreation.MakeBackAndCreatebuttons(), UIWorldCreation.MakeBackAndCreatebuttons(), UICharacterCreation.MakeCategoriesBar(), UICharacterCreation.MakeCharPreview(), UICharacterCreation.MakeClothStylesMenu(), UIBestiaryTest.MakeExitButton(), UIWorkshopHub.MakeFancyButton(), UICharacterCreation.MakeHairsylesMenu(), UICharacterCreation.MakeInfoMenu(), UIWorldCreation.MakeInfoMenu(), UIReportsPage.PopulateLogs(), UICharacterNameButton.SetContents(), GroupOptionButton< T >.SetText(), and UIIconTextButton.SetText().