Terraria: System.Globalization.CharUnicodeInfo.GetCategoryCasingTableOffsetNoBoundsChecks
GetCategoryCasingTableOffsetNoBoundsChecks()
static nuint System.Globalization.CharUnicodeInfo.GetCategoryCasingTableOffsetNoBoundsChecks (uint codePoint) inline static private
Definition at line 3954 of file CharUnicodeInfo.cs.
    {
        uint num = Unsafe.AddByteOffset(ref MemoryMarshal.GetReference(CategoryCasingLevel1Index), codePoint >> 9);
        ref byte source = ref Unsafe.AddByteOffset(ref MemoryMarshal.GetReference(CategoryCasingLevel2Index), (num << 6) + ((codePoint >> 3) & 0x3E));
        _ = BitConverter.IsLittleEndian;
        num = Unsafe.ReadUnaligned<ushort>(ref source);
        return Unsafe.AddByteOffset(ref MemoryMarshal.GetReference(CategoryCasingLevel3Index), (num << 4) + (codePoint & 0xF));
    }
References System.Globalization.CharUnicodeInfo.CategoryCasingLevel1Index, System.Globalization.CharUnicodeInfo.CategoryCasingLevel2Index, System.Globalization.CharUnicodeInfo.CategoryCasingLevel3Index, System.codePoint, System.BitConverter.IsLittleEndian, and System.source.
Referenced by System.Globalization.CharUnicodeInfo.GetBidiCategoryNoBoundsChecks(), System.Globalization.CharUnicodeInfo.GetIsWhiteSpace(), System.Globalization.CharUnicodeInfo.GetUnicodeCategoryNoBoundsChecks(), System.Globalization.CharUnicodeInfo.ToLower(), System.Globalization.CharUnicodeInfo.ToLower(), System.Globalization.CharUnicodeInfo.ToUpper(), and System.Globalization.CharUnicodeInfo.ToUpper().