Terraria: System.Globalization.CharUnicodeInfo.ToLower
ToLower() [1/2]
static char System.Globalization.CharUnicodeInfo.ToLower (char codePoint) inline static package
Definition at line 3859 of file CharUnicodeInfo.cs.
    {
        nuint categoryCasingTableOffsetNoBoundsChecks = GetCategoryCasingTableOffsetNoBoundsChecks(codePoint);
        ref short reference = ref Unsafe.Add(ref Unsafe.As<byte, short>(ref MemoryMarshal.GetReference(LowercaseValues)), (nint)categoryCasingTableOffsetNoBoundsChecks);
        if (!BitConverter.IsLittleEndian)
        {
        }
        int num = reference;
        return (char)(num + codePoint);
    }
References System.codePoint, System.Globalization.CharUnicodeInfo.GetCategoryCasingTableOffsetNoBoundsChecks(), System.BitConverter.IsLittleEndian, and System.Globalization.CharUnicodeInfo.LowercaseValues.
Referenced by System.Globalization.InvariantModeCasing.ToLower(), System.Globalization.SurrogateCasing.ToLower(), and System.Text.Rune.ToLowerInvariant().