Terraria: System.Globalization.CharUnicodeInfo.ToUpper
ToUpper() [1/2]
static char System.Globalization.CharUnicodeInfo.ToUpper (char codePoint) inline static package
Definition at line 3831 of file CharUnicodeInfo.cs.
    {
        nuint categoryCasingTableOffsetNoBoundsChecks = GetCategoryCasingTableOffsetNoBoundsChecks(codePoint);
        ref short reference = ref Unsafe.Add(ref Unsafe.As<byte, short>(ref MemoryMarshal.GetReference(UppercaseValues)), (nint)categoryCasingTableOffsetNoBoundsChecks);
        if (!BitConverter.IsLittleEndian)
        {
        }
        int num = reference;
        return (char)(num + codePoint);
    }
References System.codePoint, System.Globalization.CharUnicodeInfo.GetCategoryCasingTableOffsetNoBoundsChecks(), System.BitConverter.IsLittleEndian, and System.Globalization.CharUnicodeInfo.UppercaseValues.
Referenced by System.Globalization.InvariantModeCasing.CompareStringIgnoreCase(), System.Globalization.OrdinalCasing.CompareStringIgnoreCase(), System.Globalization.InvariantModeCasing.ToUpper(), System.Globalization.SurrogateCasing.ToUpper(), and System.Text.Rune.ToUpperInvariant().