Terraria: System.Globalization.CharUnicodeInfo.GetUnicodeCategoryInternal
GetUnicodeCategoryInternal() [2/2]
static UnicodeCategory System.Globalization.CharUnicodeInfo.GetUnicodeCategoryInternal (string value, int index) inline static package
Definition at line 3913 of file CharUnicodeInfo.cs.
    {
        return GetUnicodeCategoryNoBoundsChecks((uint)GetCodePointFromString(value, index));
    }
References System.Globalization.CharUnicodeInfo.GetCodePointFromString(), System.Globalization.CharUnicodeInfo.GetUnicodeCategoryNoBoundsChecks(), System.index, and System.value.
Referenced by System.Globalization.CharUnicodeInfo.GetUnicodeCategory(), System.Char.GetUnicodeCategory(), System.Char.IsDigit(), System.Char.IsLetter(), System.Char.IsLetterOrDigit(), System.Char.IsLower(), System.Char.IsNumber(), System.Char.IsPunctuation(), System.Char.IsSeparator(), System.Char.IsSymbol(), System.Char.IsUpper(), and System.Globalization.TextInfo.ToTitleCase().