Terraria: System.Globalization.CharUnicodeInfo.GetNumericGraphemeTableOffsetNoBoundsChecks
GetNumericGraphemeTableOffsetNoBoundsChecks()
static nuint System.Globalization.CharUnicodeInfo.GetNumericGraphemeTableOffsetNoBoundsChecks (uint codePoint) inline static private
Definition at line 3963 of file CharUnicodeInfo.cs.
    {
        uint num = Unsafe.AddByteOffset(ref MemoryMarshal.GetReference(NumericGraphemeLevel1Index), codePoint >> 9);
        ref byte source = ref Unsafe.AddByteOffset(ref MemoryMarshal.GetReference(NumericGraphemeLevel2Index), (num << 6) + ((codePoint >> 3) & 0x3E));
        _ = BitConverter.IsLittleEndian;
        num = Unsafe.ReadUnaligned<ushort>(ref source);
        return Unsafe.AddByteOffset(ref MemoryMarshal.GetReference(NumericGraphemeLevel3Index), (num << 4) + (codePoint & 0xF));
    }
References System.codePoint, System.BitConverter.IsLittleEndian, System.Globalization.CharUnicodeInfo.NumericGraphemeLevel1Index, System.Globalization.CharUnicodeInfo.NumericGraphemeLevel2Index, System.Globalization.CharUnicodeInfo.NumericGraphemeLevel3Index, and System.source.
Referenced by System.Globalization.CharUnicodeInfo.GetDecimalDigitValueInternalNoBoundsCheck(), System.Globalization.CharUnicodeInfo.GetDigitValueInternalNoBoundsCheck(), System.Globalization.CharUnicodeInfo.GetGraphemeClusterBreakType(), and System.Globalization.CharUnicodeInfo.GetNumericValueNoBoundsCheck().