Terraria: System.Globalization.CharUnicodeInfo.ToLower
ToLower() [2/2]
static uint System.Globalization.CharUnicodeInfo.ToLower (uint codePoint) inline static package
Definition at line 3871 of file CharUnicodeInfo.cs.
    {
        if (!UnicodeUtility.IsValidCodePoint(codePoint))
        {
            ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument.codePoint);
        }
        nuint categoryCasingTableOffsetNoBoundsChecks = GetCategoryCasingTableOffsetNoBoundsChecks(codePoint);
        ref short reference = ref Unsafe.Add(ref Unsafe.As<byte, short>(ref MemoryMarshal.GetReference(LowercaseValues)), (nint)categoryCasingTableOffsetNoBoundsChecks);
        if (!BitConverter.IsLittleEndian)
        {
        }
        int num = reference;
        return (uint)num + codePoint;
    }
References System.codePoint, System.Globalization.CharUnicodeInfo.GetCategoryCasingTableOffsetNoBoundsChecks(), System.BitConverter.IsLittleEndian, System.Text.UnicodeUtility.IsValidCodePoint(), System.Globalization.CharUnicodeInfo.LowercaseValues, and System.ThrowHelper.ThrowArgumentOutOfRangeException().