Terraria: System.Globalization.CharUnicodeInfo.GetCodePointFromString
GetCodePointFromString()
static int System.Globalization.CharUnicodeInfo.GetCodePointFromString (string s, int index) inline static private
Definition at line 3931 of file CharUnicodeInfo.cs.
    {
        int num = 0;
        if ((uint)index < (uint)s.Length)
        {
            num = s[index];
            int num2 = num - 55296;
            if ((uint)num2 <= 1023u)
            {
                index++;
                if ((uint)index < (uint)s.Length)
                {
                    int num3 = s[index] - 56320;
                    if ((uint)num3 <= 1023u)
                    {
                        num = (num2 << 10) + num3 + 65536;
                    }
                }
            }
        }
        return num;
    }
References System.index, and System.s.
Referenced by System.Globalization.CharUnicodeInfo.GetBidiCategory(), System.Globalization.CharUnicodeInfo.GetDecimalDigitValue(), System.Globalization.CharUnicodeInfo.GetDigitValue(), System.Globalization.CharUnicodeInfo.GetNumericValueInternal(), System.Globalization.CharUnicodeInfo.GetUnicodeCategoryInternal(), and System.Globalization.CharUnicodeInfo.GetUnicodeCategoryInternal().