Terraria: MS.Internal.Xml.Cache.XPathDocumentNavigator.MoveToNext
MoveToNext() [1/3]
override bool MS.Internal.Xml.Cache.XPathDocumentNavigator.MoveToNext () inline
Definition at line 280 of file XPathDocumentNavigator.cs.
    {
        return XPathNodeHelper.GetContentSibling(ref _pageCurrent, ref _idxCurrent);
    }
References MS.Internal.Xml.Cache.XPathDocumentNavigator._idxCurrent, MS.Internal.Xml.Cache.XPathDocumentNavigator._pageCurrent, System.Xml.Dictionary, and MS.Internal.Xml.Cache.XPathNodeHelper.GetContentSibling().
Referenced by MS.Internal.Xml.Cache.XPathDocumentElementChildIterator.MoveNext(), and MS.Internal.Xml.Cache.XPathDocumentKindChildIterator.MoveNext().