Terraria: MS.Internal.Xml.Cache.XPathDocumentNavigator.MoveToFollowing
MoveToFollowing() [5/6]
override bool MS.Internal.Xml.Cache.XPathDocumentNavigator.MoveToFollowing (XPathNodeType type, XPathNavigator end) inline
Definition at line 432 of file XPathDocumentNavigator.cs.
    {
        XPathDocumentNavigator xPathDocumentNavigator = end as XPathDocumentNavigator;
        XPathNode[] pageEnd;
        int followingEnd;
        if (type == XPathNodeType.Text || type == XPathNodeType.All)
        {
            if (_pageCurrent[_idxCurrent].HasCollapsedText)
            {
                if (xPathDocumentNavigator != null && _idxCurrent == xPathDocumentNavigator._idxParent && _pageCurrent == xPathDocumentNavigator._pageParent)
                {
                    return false;
                }
                _pageParent = _pageCurrent;
                _idxParent = _idxCurrent;
                _idxCurrent = _pageCurrent[_idxCurrent].Document.GetCollapsedTextNode(out _pageCurrent);
                return true;
            }
            if (type == XPathNodeType.Text)
            {
                followingEnd = GetFollowingEnd(xPathDocumentNavigator, useParentOfVirtual: true, out pageEnd);
                XPathNode[] pageCurrent;
                int idxCurrent;
                if (_idxParent != 0)
                {
                    pageCurrent = _pageParent;
                    idxCurrent = _idxParent;
                }
                else
                {
                    pageCurrent = _pageCurrent;
                    idxCurrent = _idxCurrent;
                }
                if (xPathDocumentNavigator != null && xPathDocumentNavigator._idxParent != 0 && idxCurrent == followingEnd && pageCurrent == pageEnd)
                {
                    return false;
                }
                if (!XPathNodeHelper.GetTextFollowing(ref pageCurrent, ref idxCurrent, pageEnd, followingEnd))
                {
                    return false;
                }
                if (pageCurrent[idxCurrent].NodeType == XPathNodeType.Element)
                {
                    _idxCurrent = pageCurrent[idxCurrent].Document.GetCollapsedTextNode(out _pageCurrent);
                    _pageParent = pageCurrent;
                    _idxParent = idxCurrent;
                }
                else
                {
                    _pageCurrent = pageCurrent;
                    _idxCurrent = idxCurrent;
                    _pageParent = null;
                    _idxParent = 0;
                }
                return true;
            }
        }
        followingEnd = GetFollowingEnd(xPathDocumentNavigator, useParentOfVirtual: false, out pageEnd);
        if (_idxParent != 0)
        {
            if (!XPathNodeHelper.GetContentFollowing(ref _pageParent, ref _idxParent, pageEnd, followingEnd, type))
            {
                return false;
            }
            _pageCurrent = _pageParent;
            _idxCurrent = _idxParent;
            _pageParent = null;
            _idxParent = 0;
            return true;
        }
        return XPathNodeHelper.GetContentFollowing(ref _pageCurrent, ref _idxCurrent, pageEnd, followingEnd, type);
    }
References MS.Internal.Xml.Cache.XPathDocumentNavigator.XPathDocumentNavigator(), MS.Internal.Xml.Cache.XPathDocumentNavigator._idxCurrent, MS.Internal.Xml.Cache.XPathDocumentNavigator._idxParent, MS.Internal.Xml.Cache.XPathDocumentNavigator._pageCurrent, MS.Internal.Xml.Cache.XPathDocumentNavigator._pageParent, System.Xml.Dictionary, MS.Internal.Xml.Cache.XPathNode.Document, System.Xml.XPath.XPathDocument.GetCollapsedTextNode(), MS.Internal.Xml.Cache.XPathNodeHelper.GetContentFollowing(), MS.Internal.Xml.Cache.XPathDocumentNavigator.GetFollowingEnd(), MS.Internal.Xml.Cache.XPathNodeHelper.GetTextFollowing(), and MS.Internal.Xml.Cache.XPathDocumentNavigator.NodeType.