Terraria: System.Globalization.CharUnicodeInfo.GetUnicodeCategory
GetUnicodeCategory() [1/3]
static UnicodeCategory System.Globalization.CharUnicodeInfo.GetUnicodeCategory (char ch) inline static
Definition at line 3886 of file CharUnicodeInfo.cs.
    {
        return GetUnicodeCategoryNoBoundsChecks(ch);
    }
References System.ch, and System.Globalization.CharUnicodeInfo.GetUnicodeCategoryNoBoundsChecks().
Referenced by System.Char.GetUnicodeCategory(), System.Text.Rune.GetUnicodeCategoryNonAscii(), System.Xml.Xsl.Runtime.CharUtil.IsAlphaNumeric(), System.Xml.Xsl.Runtime.CharUtil.IsDecimalDigitOne(), System.Char.IsDigit(), System.Char.IsLetter(), System.Char.IsLetterOrDigit(), System.Char.IsLower(), System.Char.IsNumber(), System.Char.IsPunctuation(), System.Char.IsSeparator(), System.Char.IsSymbol(), System.Char.IsUpper(), System.Xml.Serialization.CodeIdentifier.IsValid(), System.Xml.Serialization.CodeIdentifier.IsValidStart(), System.CSharpHelpers.IsValidTypeNameOrIdentifier(), System.Text.RegularExpressions.RegexCharClass.IsWordChar(), and System.Globalization.NumberFormatInfo.VerifyNativeDigits().