Terraria: Rain.Update
Update()
void Rain.Update () inline
     {
         if (Main.gamePaused)
         {
             return;
         }
         position += velocity;
         if (Main.gameMenu)
         {
             if (position.Y > Main.screenPosition.Y + (float)Main.screenHeight + 2000f)
             {
                 active = false;
             }
         }
         else if (Main.remixWorld)
         {
             if (position.Y > Main.screenPosition.Y + (float)Main.screenHeight + 100f)
             {
                 active = false;
             }
         }
         else if (Collision.SolidCollision(position, 2, 2) || position.Y > Main.screenPosition.Y + (float)Main.screenHeight + 100f || Collision.WetCollision(position, 2, 2))
         {
             active = false;
             if ((float)Main.rand.Next(100) < Main.gfxQuality * 100f)
             {
                 int num = Dust.NewDust(position - velocity, 2, 2, Dust.dustWater());
                 Main.dust[num].position.X -= 2f;
                 Main.dust[num].position.Y += 2f;
                 Main.dust[num].alpha = 38;
                 Main.dust[num].velocity *= 0.1f;
                 Main.dust[num].velocity += -velocity * 0.025f;
                 Main.dust[num].velocity.Y -= 2f;
                 Main.dust[num].scale = 0.6f;
                 Main.dust[num].noGravity = true;
             }
         }
     }
References active, Dust.alpha, Main.dust, Dust.dustWater(), Main.gameMenu, Main.gamePaused, Main.gfxQuality, Dust.NewDust(), UnifiedRandom.Next(), Dust.noGravity, Dust.position, position, Main.rand, Main.remixWorld, Dust.scale, Main.screenHeight, Main.screenPosition, Collision.SolidCollision(), Dust.velocity, velocity, and Collision.WetCollision().
Referenced by Main.DrawRain(), and Main.DrawRainInMenu().