Terraria: System.IO.Strategies.BufferedFileStreamStrategy._003CReadAsyncSlowPath_003Ed__39.MoveNext
MoveNext() [1/2]
void System.IO.Strategies.BufferedFileStreamStrategy._003CReadAsyncSlowPath_003Ed__39.MoveNext () inline private
Implements System.Runtime.CompilerServices.IAsyncStateMachine.
Definition at line 37 of file BufferedFileStreamStrategy.cs.
        {
            int num = _003C_003E1__state;
            BufferedFileStreamStrategy bufferedFileStreamStrategy = _003C_003E4__this;
            int result;
            try
            {
                ConfiguredTaskAwaitable.ConfiguredTaskAwaiter awaiter;
                if (num != 0)
                {
                    if ((uint)(num - 1) <= 2u)
                    {
                        goto IL_007d;
                    }
                    awaiter = semaphoreLockTask.ConfigureAwait(continueOnCapturedContext: false).GetAwaiter();
                    if (!awaiter.IsCompleted)
                    {
                        num = (_003C_003E1__state = 0);
                        _003C_003Eu__1 = awaiter;
                        _003C_003Et__builder.AwaitUnsafeOnCompleted(ref awaiter, ref this);
                        return;
                    }
                }
                else
                {
                    awaiter = _003C_003Eu__1;
                    _003C_003Eu__1 = default(ConfiguredTaskAwaitable.ConfiguredTaskAwaiter);
                    num = (_003C_003E1__state = -1);
                }
                awaiter.GetResult();
                goto IL_007d;
                IL_007d:
                try
                {
                    ConfiguredValueTaskAwaitable.ConfiguredValueTaskAwaiter awaiter4;
                    ConfiguredValueTaskAwaitable<int>.ConfiguredValueTaskAwaiter awaiter3;
                    ConfiguredValueTaskAwaitable<int>.ConfiguredValueTaskAwaiter awaiter2;
                    int result2;
                    int num2;
                    switch (num)
                    {
                    default:
                        num2 = 0;
                        _003CbytesAlreadySatisfied_003E5__2 = 0;
                        if (bufferedFileStreamStrategy._readLen - bufferedFileStreamStrategy._readPos <= 0)
{
                            goto IL_0146;
                        }
                        num2 = Math.Min(buffer.Length, bufferedFileStreamStrategy._readLen - bufferedFileStreamStrategy._readPos);
                        if (num2 > 0)
{
                            bufferedFileStreamStrategy._buffer.AsSpan(bufferedFileStreamStrategy._readPos, num2).CopyTo(buffer.Span);
                            bufferedFileStreamStrategy._readPos += num2;
                        }
                        if (num2 != buffer.Length)
{
                            if (num2 > 0)
{
                                buffer = buffer.Slice(num2);
                                _003CbytesAlreadySatisfied_003E5__2 += num2;
                            }
                            goto IL_0146;
                        }
                        result = num2;
                        goto end_IL_007d;
                    case 1:
                        awaiter4 = _003C_003Eu__2;
                        _003C_003Eu__2 = default(ConfiguredValueTaskAwaitable.ConfiguredValueTaskAwaiter);
                        num = (_003C_003E1__state = -1);
                        goto IL_01e6;
                    case 2:
                        awaiter3 = _003C_003Eu__3;
                        _003C_003Eu__3 = default(ConfiguredValueTaskAwaitable<int>.ConfiguredValueTaskAwaiter);
                        num = (_003C_003E1__state = -1);
                        goto IL_0280;
                    case 3:
{
                            awaiter2 = _003C_003Eu__3;
                            _003C_003Eu__3 = default(ConfiguredValueTaskAwaitable<int>.ConfiguredValueTaskAwaiter);
                            num = (_003C_003E1__state = -1);
                            break;
                        }
                        IL_0280:
                        result2 = awaiter3.GetResult();
                        result = result2 + _003CbytesAlreadySatisfied_003E5__2;
                        goto end_IL_007d;
                        IL_0146:
                        bufferedFileStreamStrategy._readPos = (bufferedFileStreamStrategy._readLen = 0);
                        if (bufferedFileStreamStrategy._writePos > 0)
{
                            awaiter4 = bufferedFileStreamStrategy._strategy.WriteAsync(new ReadOnlyMemory<byte>(bufferedFileStreamStrategy._buffer, 0, bufferedFileStreamStrategy._writePos), cancellationToken).ConfigureAwait(continueOnCapturedContext: false).GetAwaiter();
                            if (!awaiter4.IsCompleted)
{
                                num = (_003C_003E1__state = 1);
                                _003C_003Eu__2 = awaiter4;
                                _003C_003Et__builder.AwaitUnsafeOnCompleted(ref awaiter4, ref this);
                                return;
                            }
                            goto IL_01e6;
                        }
                        goto IL_01f4;
                        IL_01e6:
                        awaiter4.GetResult();
                        bufferedFileStreamStrategy._writePos = 0;
                        goto IL_01f4;
                        IL_01f4:
                        if (buffer.Length >= bufferedFileStreamStrategy._bufferSize)
{
                            awaiter3 = bufferedFileStreamStrategy._strategy.ReadAsync(buffer, cancellationToken).ConfigureAwait(continueOnCapturedContext: false).GetAwaiter();
                            if (!awaiter3.IsCompleted)
{
                                num = (_003C_003E1__state = 2);
                                _003C_003Eu__3 = awaiter3;
                                _003C_003Et__builder.AwaitUnsafeOnCompleted(ref awaiter3, ref this);
                                return;
                            }
                            goto IL_0280;
                        }
                        bufferedFileStreamStrategy.EnsureBufferAllocated();
                        awaiter2 = bufferedFileStreamStrategy._strategy.ReadAsync(new Memory<byte>(bufferedFileStreamStrategy._buffer, 0, bufferedFileStreamStrategy._bufferSize), cancellationToken).ConfigureAwait(continueOnCapturedContext: false).GetAwaiter();
                        if (!awaiter2.IsCompleted)
{
                            num = (_003C_003E1__state = 3);
                            _003C_003Eu__3 = awaiter2;
                            _003C_003Et__builder.AwaitUnsafeOnCompleted(ref awaiter2, ref this);
                            return;
                        }
                        break;
                    }
                    int result3 = awaiter2.GetResult();
                    bufferedFileStreamStrategy._readLen = result3;
                    num2 = Math.Min(bufferedFileStreamStrategy._readLen, buffer.Length);
                    bufferedFileStreamStrategy._buffer.AsSpan(0, num2).CopyTo(buffer.Span);
                    bufferedFileStreamStrategy._readPos += num2;
                    result = _003CbytesAlreadySatisfied_003E5__2 + num2;
                    end_IL_007d:;
                }
                finally
                {
                    if (num < 0)
                    {
                        bufferedFileStreamStrategy._asyncActiveSemaphore.Release();
                    }
                }
            }
            catch (Exception exception)
            {
                _003C_003E1__state = -2;
                _003C_003Et__builder.SetException(exception);
                return;
            }
            _003C_003E1__state = -2;
            _003C_003Et__builder.SetResult(result);
        }
References System.IO.Strategies.BufferedFileStreamStrategy._003CReadAsyncSlowPath_003Ed__39._003C_003E1__state, System.IO.Strategies.BufferedFileStreamStrategy._003CReadAsyncSlowPath_003Ed__39._003C_003E4__this, System.IO.Strategies.BufferedFileStreamStrategy._003CReadAsyncSlowPath_003Ed__39._003C_003Et__builder, System.IO.Strategies.BufferedFileStreamStrategy._003CReadAsyncSlowPath_003Ed__39._003C_003Eu__1, System.IO.Strategies.BufferedFileStreamStrategy._003CReadAsyncSlowPath_003Ed__39._003C_003Eu__2, System.IO.Strategies.BufferedFileStreamStrategy._003CReadAsyncSlowPath_003Ed__39._003C_003Eu__3, System.IO.Strategies.BufferedFileStreamStrategy._003CReadAsyncSlowPath_003Ed__39._003CbytesAlreadySatisfied_003E5__2, System.IO.Stream._asyncActiveSemaphore, System.IO.Strategies.BufferedFileStreamStrategy._buffer, System.IO.Strategies.BufferedFileStreamStrategy._bufferSize, System.IO.Strategies.BufferedFileStreamStrategy._readLen, System.IO.Strategies.BufferedFileStreamStrategy._readPos, System.IO.Strategies.BufferedFileStreamStrategy._strategy, System.IO.Strategies.BufferedFileStreamStrategy._writePos, System.IO.Strategies.BufferedFileStreamStrategy._003CReadAsyncSlowPath_003Ed__39.buffer, System.IO.Strategies.BufferedFileStreamStrategy._003CReadAsyncSlowPath_003Ed__39.cancellationToken, System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.IO.Strategies.BufferedFileStreamStrategy.EnsureBufferAllocated(), System.exception, System.Runtime.CompilerServices.ConfiguredTaskAwaitable< TResult >.ConfiguredTaskAwaiter.GetResult(), System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable< TResult >.ConfiguredValueTaskAwaiter.GetResult(), System.Runtime.CompilerServices.ConfiguredTaskAwaitable< TResult >.ConfiguredTaskAwaiter.IsCompleted, System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable< TResult >.ConfiguredValueTaskAwaiter.IsCompleted, System.Memory< T >.Length, System.Math.Min(), System.IO.Stream.ReadAsync(), System.Threading.SemaphoreSlim.Release(), System.IO.Strategies.BufferedFileStreamStrategy._003CReadAsyncSlowPath_003Ed__39.semaphoreLockTask, System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder< TResult >.SetException(), System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder< TResult >.SetResult(), System.Memory< T >.Slice(), System.Memory< T >.Span, and System.IO.Stream.WriteAsync().
Referenced by System.IO.Strategies.BufferedFileStreamStrategy._003CReadAsyncSlowPath_003Ed__39.MoveNext().