Terraria: System.Net.Http.HttpRequestMessage.ToString
ToString()
override string System.Net.Http.HttpRequestMessage.ToString () inline
Definition at line 143 of file HttpRequestMessage.cs.
    {
        StringBuilder stringBuilder = new StringBuilder();
        stringBuilder.Append("Method: ");
        stringBuilder.Append(_method);
        stringBuilder.Append(", RequestUri: '");
        stringBuilder.Append((_requestUri == null) ? "<null>" : _requestUri.ToString());
        stringBuilder.Append("', Version: ");
        stringBuilder.Append(_version);
        stringBuilder.Append(", Content: ");
        stringBuilder.Append((_content == null) ? "<null>" : _content.GetType().ToString());
        stringBuilder.AppendLine(", Headers:");
        HeaderUtilities.DumpHeaders(stringBuilder, _headers, _content?.Headers);
        return stringBuilder.ToString();
    }
References System.Net.Http.HttpRequestMessage._content, System.Net.Http.HttpRequestMessage._headers, System.Net.Http.HttpRequestMessage._method, System.Net.Http.HttpRequestMessage._requestUri, System.Net.Http.HttpRequestMessage._version, System.Net.Http.Headers.HeaderUtilities.DumpHeaders(), and System.Uri.ToString().
Referenced by System.Net.Http.HttpRequestMessage.CheckDisposed().