Terraria: System.Net.Mail.AlternateView.Dispose
Dispose() [2/2]
override void System.Net.Mail.AlternateView.Dispose (bool disposing) inline protected virtual
Reimplemented from System.Net.Mail.AttachmentBase.
Definition at line 90 of file AlternateView.cs.
    {
        if (!disposed)
        {
            if (disposing && _linkedResources != null)
            {
                _linkedResources.Dispose();
            }
            base.Dispose(disposing);
        }
    }
References System.Net.Mail.AlternateView._linkedResources, System.Net.Mail.LinkedResourceCollection.Dispose(), and System.Net.Mail.AttachmentBase.disposed.
Referenced by System.Net.Mail.AlternateViewCollection.Dispose(), System.Net.Mail.MailMessage.Dispose(), and System.Net.Mail.MailMessage.SetContent().