Terraria: System.Threading.Tasks.TaskSchedulerAwaitTaskContinuation.Run
Run()
override void System.Threading.Tasks.TaskSchedulerAwaitTaskContinuation.Run (Task ignored, bool canInlineContinuationTask) inline sealed package
Definition at line 13 of file TaskSchedulerAwaitTaskContinuation.cs.
    {
        if (m_scheduler == TaskScheduler.Default)
        {
            base.Run(ignored, canInlineContinuationTask);
            return;
        }
        bool flag = canInlineContinuationTask && (TaskScheduler.InternalCurrent == m_scheduler || Thread.CurrentThread.IsThreadPoolThread);
        Task task = CreateTask(delegate(object state)
        {
            try
            {
                ((Action)state)();
            }
            catch (Exception exception)
            {
                Task.ThrowAsync(exception, null);
            }
        }, m_action, m_scheduler);
        if (flag)
        {
            TaskContinuation.InlineIfPossibleOrElseQueue(task, needsProtection: false);
            return;
        }
        try
        {
            task.ScheduleAndStart(needsProtection: false);
        }
        catch (TaskSchedulerException)
        {
        }
    }
References System.Action(), System.Threading.Tasks.AwaitTaskContinuation.CreateTask(), System.Threading.Thread.CurrentThread, System.Threading.Tasks.TaskScheduler.Default, System.exception, System.Threading.Tasks.TaskContinuation.InlineIfPossibleOrElseQueue(), System.Threading.Tasks.AwaitTaskContinuation.m_action, System.Threading.Tasks.TaskSchedulerAwaitTaskContinuation.m_scheduler, System.state, System.task, and System.Threading.Tasks.Task< TResult >.ThrowAsync().