Terraria: System.Runtime.Versioning.VersioningHelper.MakeVersionSafeName
MakeVersionSafeName() [2/2]
static string System.Runtime.Versioning.VersioningHelper.MakeVersionSafeName (string? name, ResourceScope from, ResourceScope to, Type? type) inline static
Definition at line 12 of file VersioningHelper.cs.
    {
        ResourceScope resourceScope = from & (ResourceScope.Machine | ResourceScope.Process | ResourceScope.AppDomain | ResourceScope.Library);
        ResourceScope resourceScope2 = to & (ResourceScope.Machine | ResourceScope.Process | ResourceScope.AppDomain | ResourceScope.Library);
        if (resourceScope > resourceScope2)
        {
            throw new ArgumentException(SR.Format(SR.Argument_ResourceScopeWrongDirection, resourceScope, resourceScope2), "from");
        }
        SxSRequirements requirements = GetRequirements(to, from);
        if ((requirements & (SxSRequirements.AssemblyName | SxSRequirements.TypeName)) != 0 && type == null)
        {
            throw new ArgumentNullException("type", SR.ArgumentNull_TypeRequiredByResourceScope);
        }
        StringBuilder stringBuilder = new StringBuilder(name);
        char value = '_';
        if ((requirements & SxSRequirements.ProcessID) != 0)
        {
            stringBuilder.Append(value);
            stringBuilder.Append('p');
            stringBuilder.Append(Environment.ProcessId);
        }
        if ((requirements & SxSRequirements.CLRInstanceID) != 0)
        {
            string cLRInstanceString = GetCLRInstanceString();
            stringBuilder.Append(value);
            stringBuilder.Append('r');
            stringBuilder.Append(cLRInstanceString);
        }
        if ((requirements & SxSRequirements.AppDomainID) != 0)
        {
            stringBuilder.Append(value);
            stringBuilder.Append("ad");
            stringBuilder.Append(AppDomain.CurrentDomain.Id);
        }
        if ((requirements & SxSRequirements.TypeName) != 0)
        {
            stringBuilder.Append(value);
            stringBuilder.Append(type.Name);
        }
        if ((requirements & SxSRequirements.AssemblyName) != 0)
        {
            stringBuilder.Append(value);
            stringBuilder.Append(type.Assembly.FullName);
        }
        return stringBuilder.ToString();
    }
References System.Text.StringBuilder.Append(), System.SR.Argument_ResourceScopeWrongDirection, System.SR.ArgumentNull_TypeRequiredByResourceScope, System.AppDomain.CurrentDomain, System.SR.Format(), System.Runtime.Versioning.VersioningHelper.GetCLRInstanceString(), System.Runtime.Versioning.VersioningHelper.GetRequirements(), System.Environment.ProcessId, System.Text.StringBuilder.ToString(), System.type, and System.value.