Terraria: System.Net.RequestContextBase.SetBuffer
SetBuffer()
unsafe void System.Net.RequestContextBase.SetBuffer (int size) inline protected inherited
Definition at line 90 of file RequestContextBase.cs.
    {
        if (_backingBuffer != IntPtr.Zero)
        {
            Marshal.FreeHGlobal(_backingBuffer);
        }
        _backingBuffer = ((size == 0) ? IntPtr.Zero : Marshal.AllocHGlobal(size));
        _backingBufferLength = size;
        new Span<byte>(_backingBuffer.ToPointer(), size).Clear();
    }
References System.Net.RequestContextBase._backingBuffer, System.Net.RequestContextBase._backingBufferLength, System.Runtime.InteropServices.Marshal.AllocHGlobal(), System.Span< T >.Clear(), System.Runtime.InteropServices.Marshal.FreeHGlobal(), System.IntPtr.ToPointer(), and System.IntPtr.Zero.
Referenced by System.Net.SyncRequestContext.Allocate(), and System.Net.AsyncRequestContext.Allocate().