Terraria: System.Net.RequestContextBase.SetBlob
SetBlob()
unsafe void System.Net.RequestContextBase.SetBlob (global::Interop::HttpApi::HTTP_REQUEST * requestBlob) inline protected inherited
Definition at line 73 of file RequestContextBase.cs.
    {
        if (requestBlob == null)
        {
            UnsetBlob();
        }
        else
        {
            _memoryBlob = requestBlob;
        }
    }
References System.Net.RequestContextBase._memoryBlob, and System.Net.RequestContextBase.UnsetBlob().
Referenced by System.Net.SyncRequestContext.Reset(), and System.Net.AsyncRequestContext.Reset().