Terraria: PressurePlateHelper.UpdatePlayerPosition
UpdatePlayerPosition()
static void PressurePlateHelper.UpdatePlayerPosition (Player player) inline static
     {
         Point p = new Point(1, 1);
         Vector2 vector = p.ToVector2();
         List<Point> tilesIn = Collision.GetTilesIn(PlayerLastPosition[player.whoAmI] + vector, PlayerLastPosition[player.whoAmI] + player.Size - vector * 2f);
         List<Point> tilesIn2 = Collision.GetTilesIn(player.TopLeft + vector, player.BottomRight - vector * 2f);
         Rectangle hitbox = player.Hitbox;
         Rectangle hitbox2 = player.Hitbox;
         hitbox.Inflate(-p.X, -p.Y);
         hitbox2.Inflate(-p.X, -p.Y);
         hitbox2.X = (int)PlayerLastPosition[player.whoAmI].X;
         hitbox2.Y = (int)PlayerLastPosition[player.whoAmI].Y;
         for (int i = 0; i < tilesIn.Count; i++)
         {
             Point point = tilesIn[i];
             Tile tile = Main.tile[point.X, point.Y];
             if (tile.active() && tile.type == 428)
             {
                 pressurePlateBounds.X = point.X * 16;
                 pressurePlateBounds.Y = point.Y * 16 + 16 - pressurePlateBounds.Height;
                 if (!hitbox.Intersects(pressurePlateBounds) && !tilesIn2.Contains(point))
                 {
                     MoveAwayFrom(point, player.whoAmI);
                 }
             }
         }
         for (int j = 0; j < tilesIn2.Count; j++)
         {
             Point point2 = tilesIn2[j];
             Tile tile2 = Main.tile[point2.X, point2.Y];
             if (tile2.active() && tile2.type == 428)
             {
                 pressurePlateBounds.X = point2.X * 16;
                 pressurePlateBounds.Y = point2.Y * 16 + 16 - pressurePlateBounds.Height;
                 if (hitbox.Intersects(pressurePlateBounds) && (!tilesIn.Contains(point2) || !hitbox2.Intersects(pressurePlateBounds)))
                 {
                     MoveInto(point2, player.whoAmI);
                 }
             }
         }
         PlayerLastPosition[player.whoAmI] = player.position;
     }
References Tile.active(), Entity.BottomRight, Collision.GetTilesIn(), Entity.Hitbox, MoveAwayFrom(), MoveInto(), PlayerLastPosition, Entity.position, pressurePlateBounds, Entity.Size, Main.tile, Entity.TopLeft, Tile.type, and Entity.whoAmI.
Referenced by Player.Teleport(), and Player.Update().