Terraria: System.Data.DataTableReader.ValidateState
ValidateState()
void System.Data.DataTableReader.ValidateState (string caller) inline private
Definition at line 838 of file DataTableReader.cs.
    {
        ValidateOpen(caller);
        if (_tableCleared)
        {
            throw ExceptionBuilder.EmptyDataTableReader(_currentDataTable.TableName);
        }
        if (_currentDataRow == null || _currentDataTable == null)
        {
            ReaderIsInvalid = true;
            throw ExceptionBuilder.InvalidDataTableReader(_currentDataTable.TableName);
        }
        if (_currentDataRow.RowState == DataRowState.Deleted || _currentDataRow.RowState == DataRowState.Detached || _currentRowRemoved)
        {
            throw ExceptionBuilder.InvalidCurrentRowInDataTableReader();
        }
        if (0 > _rowCounter || _currentDataTable.Rows.Count <= _rowCounter)
        {
            ReaderIsInvalid = true;
            throw ExceptionBuilder.InvalidDataTableReader(_currentDataTable.TableName);
        }
    }
References System.Data.DataTableReader._currentDataRow, System.Data.DataTableReader._currentDataTable, System.Data.DataTableReader._currentRowRemoved, System.Data.DataTableReader._rowCounter, System.Data.DataTableReader._tableCleared, System.Data.DataRowCollection.Count, System.Data.ExceptionBuilder.EmptyDataTableReader(), System.Data.ExceptionBuilder.InvalidCurrentRowInDataTableReader(), System.Data.ExceptionBuilder.InvalidDataTableReader(), System.Data.DataTableReader.ReaderIsInvalid, System.Data.DataTable.Rows, System.Data.DataRow.RowState, System.Data.DataTable.TableName, and System.Data.DataTableReader.ValidateOpen().
Referenced by System.Data.DataTableReader.GetBoolean(), System.Data.DataTableReader.GetByte(), System.Data.DataTableReader.GetBytes(), System.Data.DataTableReader.GetChar(), System.Data.DataTableReader.GetChars(), System.Data.DataTableReader.GetDateTime(), System.Data.DataTableReader.GetDecimal(), System.Data.DataTableReader.GetDouble(), System.Data.DataTableReader.GetFloat(), System.Data.DataTableReader.GetGuid(), System.Data.DataTableReader.GetInt16(), System.Data.DataTableReader.GetInt32(), System.Data.DataTableReader.GetInt64(), System.Data.DataTableReader.GetString(), System.Data.DataTableReader.GetValue(), System.Data.DataTableReader.GetValues(), and System.Data.DataTableReader.IsDBNull().