Terraria: System.Data.DataTableReader.GetSchemaTable
GetSchemaTable()
override DataTable System.Data.DataTableReader.GetSchemaTable () inline virtual
Reimplemented from System.Data.Common.DbDataReader.
Definition at line 216 of file DataTableReader.cs.
    {
        ValidateOpen("GetSchemaTable");
        ValidateReader();
        if (_schemaTable == null)
        {
            _schemaTable = GetSchemaTableFromDataTable(_currentDataTable);
        }
        return _schemaTable;
    }
References System.Data.DataTableReader._currentDataTable, System.Data.DataTableReader._schemaTable, System.Data.DataTableReader.GetSchemaTableFromDataTable(), System.Data.DataTableReader.ValidateOpen(), and System.Data.DataTableReader.ValidateReader().