Terraria: System.Data.DataTableReader.ValidateOpen
ValidateOpen()
void System.Data.DataTableReader.ValidateOpen (string caller) inline private
Definition at line 818 of file DataTableReader.cs.
    {
        if (!_isOpen)
        {
            throw ADP.DataReaderClosed(caller);
        }
    }
References System.Data.DataTableReader._isOpen, and System.Data.Common.ADP.DataReaderClosed().
Referenced by System.Data.DataTableReader.GetDataTypeName(), System.Data.DataTableReader.GetEnumerator(), System.Data.DataTableReader.GetFieldType(), System.Data.DataTableReader.GetName(), System.Data.DataTableReader.GetOrdinal(), System.Data.DataTableReader.GetProviderSpecificFieldType(), System.Data.DataTableReader.GetProviderSpecificValue(), System.Data.DataTableReader.GetProviderSpecificValues(), System.Data.DataTableReader.GetSchemaTable(), System.Data.DataTableReader.NextResult(), System.Data.DataTableReader.Read(), and System.Data.DataTableReader.ValidateState().