Terraria: System.Data.DataTableReader.GetSchemaTableFromDataTable
GetSchemaTableFromDataTable()
static DataTable System.Data.DataTableReader.GetSchemaTableFromDataTable (DataTable table) inline static package
Definition at line 687 of file DataTableReader.cs.
    {
        if (table == null)
        {
            throw ExceptionBuilder.ArgumentNull("DataTable");
        }
        DataTable dataTable = new DataTable("SchemaTable");
        dataTable.Locale = CultureInfo.InvariantCulture;
        DataColumn column = new DataColumn(SchemaTableColumn.ColumnName, typeof(string));
        DataColumn column2 = new DataColumn(SchemaTableColumn.ColumnOrdinal, typeof(int));
        DataColumn dataColumn = new DataColumn(SchemaTableColumn.ColumnSize, typeof(int));
        DataColumn column3 = new DataColumn(SchemaTableColumn.NumericPrecision, typeof(short));
        DataColumn column4 = new DataColumn(SchemaTableColumn.NumericScale, typeof(short));
        DataColumn column5 = GetSystemTypeDataColumn();
        DataColumn column6 = new DataColumn(SchemaTableColumn.ProviderType, typeof(int));
        DataColumn dataColumn2 = new DataColumn(SchemaTableColumn.IsLong, typeof(bool));
        DataColumn column7 = new DataColumn(SchemaTableColumn.AllowDBNull, typeof(bool));
        DataColumn dataColumn3 = new DataColumn(SchemaTableOptionalColumn.IsReadOnly, typeof(bool));
        DataColumn dataColumn4 = new DataColumn(SchemaTableOptionalColumn.IsRowVersion, typeof(bool));
        DataColumn column8 = new DataColumn(SchemaTableColumn.IsUnique, typeof(bool));
        DataColumn dataColumn5 = new DataColumn(SchemaTableColumn.IsKey, typeof(bool));
        DataColumn dataColumn6 = new DataColumn(SchemaTableOptionalColumn.IsAutoIncrement, typeof(bool));
        DataColumn column9 = new DataColumn(SchemaTableColumn.BaseSchemaName, typeof(string));
        DataColumn dataColumn7 = new DataColumn(SchemaTableOptionalColumn.BaseCatalogName, typeof(string));
        DataColumn dataColumn8 = new DataColumn(SchemaTableColumn.BaseTableName, typeof(string));
        DataColumn column10 = new DataColumn(SchemaTableColumn.BaseColumnName, typeof(string));
        DataColumn dataColumn9 = new DataColumn(SchemaTableOptionalColumn.AutoIncrementSeed, typeof(long));
        DataColumn dataColumn10 = new DataColumn(SchemaTableOptionalColumn.AutoIncrementStep, typeof(long));
        DataColumn column11 = new DataColumn(SchemaTableOptionalColumn.DefaultValue, typeof(object));
        DataColumn column12 = new DataColumn(SchemaTableOptionalColumn.Expression, typeof(string));
        DataColumn column13 = new DataColumn(SchemaTableOptionalColumn.ColumnMapping, typeof(MappingType));
        DataColumn dataColumn11 = new DataColumn(SchemaTableOptionalColumn.BaseTableNamespace, typeof(string));
        DataColumn column14 = new DataColumn(SchemaTableOptionalColumn.BaseColumnNamespace, typeof(string));
        dataColumn.DefaultValue = -1;
        if (table.DataSet != null)
        {
            dataColumn7.DefaultValue = table.DataSet.DataSetName;
        }
        dataColumn8.DefaultValue = table.TableName;
        dataColumn11.DefaultValue = table.Namespace;
        dataColumn4.DefaultValue = false;
        dataColumn2.DefaultValue = false;
        dataColumn3.DefaultValue = false;
        dataColumn5.DefaultValue = false;
        dataColumn6.DefaultValue = false;
        dataColumn9.DefaultValue = 0;
        dataColumn10.DefaultValue = 1;
        dataTable.Columns.Add(column);
        dataTable.Columns.Add(column2);
        dataTable.Columns.Add(dataColumn);
        dataTable.Columns.Add(column3);
        dataTable.Columns.Add(column4);
        dataTable.Columns.Add(column5);
        dataTable.Columns.Add(column6);
        dataTable.Columns.Add(dataColumn2);
        dataTable.Columns.Add(column7);
        dataTable.Columns.Add(dataColumn3);
        dataTable.Columns.Add(dataColumn4);
        dataTable.Columns.Add(column8);
        dataTable.Columns.Add(dataColumn5);
        dataTable.Columns.Add(dataColumn6);
        dataTable.Columns.Add(dataColumn7);
        dataTable.Columns.Add(column9);
        dataTable.Columns.Add(dataColumn8);
        dataTable.Columns.Add(column10);
        dataTable.Columns.Add(dataColumn9);
        dataTable.Columns.Add(dataColumn10);
        dataTable.Columns.Add(column11);
        dataTable.Columns.Add(column12);
        dataTable.Columns.Add(column13);
        dataTable.Columns.Add(dataColumn11);
        dataTable.Columns.Add(column14);
        foreach (DataColumn column15 in table.Columns)
        {
            DataRow dataRow = dataTable.NewRow();
            dataRow[column] = column15.ColumnName;
            dataRow[column2] = column15.Ordinal;
            dataRow[column5] = column15.DataType;
            if (column15.DataType == typeof(string))
            {
                dataRow[dataColumn] = column15.MaxLength;
            }
            dataRow[column7] = column15.AllowDBNull;
            dataRow[dataColumn3] = column15.ReadOnly;
            dataRow[column8] = column15.Unique;
            if (column15.AutoIncrement)
            {
                dataRow[dataColumn6] = true;
                dataRow[dataColumn9] = column15.AutoIncrementSeed;
                dataRow[dataColumn10] = column15.AutoIncrementStep;
            }
            if (column15.DefaultValue != DBNull.Value)
            {
                dataRow[column11] = column15.DefaultValue;
            }
            if (column15.Expression.Length != 0)
            {
                bool flag = false;
                DataColumn[] dependency = column15.DataExpression.GetDependency();
                for (int i = 0; i < dependency.Length; i++)
                {
                    if (dependency[i].Table != table)
                    {
                        flag = true;
                        break;
                    }
                }
                if (!flag)
                {
                    dataRow[column12] = column15.Expression;
                }
            }
            dataRow[column13] = column15.ColumnMapping;
            dataRow[column10] = column15.ColumnName;
            dataRow[column14] = column15.Namespace;
            dataTable.Rows.Add(dataRow);
        }
        DataColumn[] primaryKey = table.PrimaryKey;
        foreach (DataColumn dataColumn13 in primaryKey)
        {
            dataTable.Rows[dataColumn13.Ordinal][dataColumn5] = true;
        }
        dataTable.AcceptChanges();
        return dataTable;
        [UnconditionalSuppressMessage("ReflectionAnalysis", "IL2111:ReflectionToDynamicallyAccessedMembers", Justification = "The problem is Type.TypeInitializer which requires constructors on the Type instance.In this case the TypeInitializer property is not accessed dynamically.")]
        static DataColumn GetSystemTypeDataColumn()
        {
            return new DataColumn(SchemaTableColumn.DataType, typeof(Type));
        }
    }
References System.Data.DataColumnCollection.Add(), System.Data.Common.SchemaTableColumn.AllowDBNull, System.Data.DataColumn.AllowDBNull, System.Data.ExceptionBuilder.ArgumentNull(), System.Data.DataColumn.AutoIncrement, System.Data.Common.SchemaTableOptionalColumn.AutoIncrementSeed, System.Data.DataColumn.AutoIncrementSeed, System.Data.Common.SchemaTableOptionalColumn.AutoIncrementStep, System.Data.DataColumn.AutoIncrementStep, System.Data.Common.SchemaTableOptionalColumn.BaseCatalogName, System.Data.Common.SchemaTableColumn.BaseColumnName, System.Data.Common.SchemaTableOptionalColumn.BaseColumnNamespace, System.Data.Common.SchemaTableColumn.BaseSchemaName, System.Data.Common.SchemaTableColumn.BaseTableName, System.Data.Common.SchemaTableOptionalColumn.BaseTableNamespace, System.Data.Common.SchemaTableOptionalColumn.ColumnMapping, System.Data.DataColumn.ColumnMapping, System.Data.Common.SchemaTableColumn.ColumnName, System.Data.DataColumn.ColumnName, System.Data.Common.SchemaTableColumn.ColumnOrdinal, System.Data.DataTable.Columns, System.Data.Common.SchemaTableColumn.ColumnSize, System.Data.DataColumn.DataExpression, System.Data.DataTable.DataSet, System.Data.DataSet.DataSetName, System.Data.Common.SchemaTableColumn.DataType, System.Data.DataColumn.DataType, System.Data.Common.SchemaTableOptionalColumn.DefaultValue, System.Data.DataColumn.DefaultValue, System.Data.Common.SchemaTableOptionalColumn.Expression, System.Data.DataColumn.Expression, System.Data.DataExpression.GetDependency(), System.Globalization.CultureInfo.InvariantCulture, System.Data.Common.SchemaTableOptionalColumn.IsAutoIncrement, System.Data.Common.SchemaTableColumn.IsKey, System.Data.Common.SchemaTableColumn.IsLong, System.Data.Common.SchemaTableOptionalColumn.IsReadOnly, System.Data.Common.SchemaTableOptionalColumn.IsRowVersion, System.Data.Common.SchemaTableColumn.IsUnique, System.Data.DataColumn.MaxLength, System.Data.DataColumn.Namespace, System.Data.DataTable.Namespace, System.Data.Common.SchemaTableColumn.NumericPrecision, System.Data.Common.SchemaTableColumn.NumericScale, System.Data.DataColumn.Ordinal, System.Data.Common.SchemaTableColumn.ProviderType, System.Data.DataColumn.ReadOnly, System.Data.DataTable.TableName, System.Data.DataColumn.Unique, and System.DBNull.Value.
Referenced by System.Data.DataTableReader.GetSchemaTable().