Terraria: System.Data.DataTableReader.GetBytes
GetBytes()
override long System.Data.DataTableReader.GetBytes (int ordinal, long dataIndex, byte?[] buffer, int bufferIndex, int length) inline
Implements System.Data.IDataRecord.
Definition at line 349 of file DataTableReader.cs.
    {
        ValidateState("GetBytes");
        ValidateReader();
        byte[] array;
        try
        {
            array = (byte[])_currentDataRow[ordinal];
        }
        catch (IndexOutOfRangeException e)
        {
            ExceptionBuilder.TraceExceptionWithoutRethrow(e);
            throw ExceptionBuilder.ArgumentOutOfRange("ordinal");
        }
        if (buffer == null)
        {
            return array.Length;
        }
        int num = (int)dataIndex;
        int num2 = Math.Min(array.Length - num, length);
        if (num < 0)
        {
            throw ADP.InvalidSourceBufferIndex(array.Length, num, "dataIndex");
        }
        if (bufferIndex < 0 || (bufferIndex > 0 && bufferIndex >= buffer.Length))
        {
            throw ADP.InvalidDestinationBufferIndex(buffer.Length, bufferIndex, "bufferIndex");
        }
        if (0 < num2)
        {
            Array.Copy(array, dataIndex, buffer, bufferIndex, num2);
        }
        else
        {
            if (length < 0)
            {
                throw ADP.InvalidDataLength(length);
            }
            num2 = 0;
        }
        return num2;
    }
References System.Data.DataTableReader._currentDataRow, System.Data.ExceptionBuilder.ArgumentOutOfRange(), System.array, System.buffer, System.Array.Copy(), System.Data.Common.ADP.InvalidDataLength(), System.Data.Common.ADP.InvalidDestinationBufferIndex(), System.Data.Common.ADP.InvalidSourceBufferIndex(), System.length, System.Math.Min(), System.Data.ExceptionBuilder.TraceExceptionWithoutRethrow(), System.Data.DataTableReader.ValidateReader(), and System.Data.DataTableReader.ValidateState().