Terraria: System.Data.DataTableReader.GetFieldType
GetFieldType()
override Type System.Data.DataTableReader.GetFieldType (int ordinal) inline
Implements System.Data.IDataRecord.
Definition at line 503 of file DataTableReader.cs.
    {
        ValidateOpen("GetFieldType");
        ValidateReader();
        try
        {
            return _currentDataTable.Columns[ordinal].DataType;
        }
        catch (IndexOutOfRangeException e)
        {
            ExceptionBuilder.TraceExceptionWithoutRethrow(e);
            throw ExceptionBuilder.ArgumentOutOfRange("ordinal");
        }
    }
References System.Data.DataTableReader._currentDataTable, System.Data.ExceptionBuilder.ArgumentOutOfRange(), System.Data.DataTable.Columns, System.Data.ExceptionBuilder.TraceExceptionWithoutRethrow(), System.Data.DataTableReader.ValidateOpen(), and System.Data.DataTableReader.ValidateReader().
Referenced by System.Data.DataTableReader.GetDataTypeName(), and System.Data.DataTableReader.GetProviderSpecificFieldType().