Terraria: System.Data.DataTableReader.GetValues
GetValues()
override int System.Data.DataTableReader.GetValues (object[] values) inline
Implements System.Data.IDataRecord.
Definition at line 650 of file DataTableReader.cs.
    {
        ValidateState("GetValues");
        ValidateReader();
        if (values == null)
        {
            throw ExceptionBuilder.ArgumentNull("values");
        }
        Array.Copy(_currentDataRow.ItemArray, values, (_currentDataRow.ItemArray.Length > values.Length) ? values.Length : _currentDataRow.ItemArray.Length);
        if (_currentDataRow.ItemArray.Length <= values.Length)
        {
            return _currentDataRow.ItemArray.Length;
        }
        return values.Length;
    }
References System.Data.DataTableReader._currentDataRow, System.Data.ExceptionBuilder.ArgumentNull(), System.Array.Copy(), System.Data.DataRow.ItemArray, System.Data.DataTableReader.ValidateReader(), System.Data.DataTableReader.ValidateState(), and System.values.
Referenced by System.Data.DataTableReader.GetProviderSpecificValues().