Terraria: System.Data.DataTableReader.Read
Read()
override bool System.Data.DataTableReader.Read () inline
Implements System.Data.IDataReader.
Definition at line 251 of file DataTableReader.cs.
    {
        if (!_started)
        {
            _started = true;
        }
        ValidateOpen("Read");
        ValidateReader();
        if (_reachEORows)
        {
            return false;
        }
        if (_rowCounter >= _currentDataTable.Rows.Count - 1)
        {
            _reachEORows = true;
            if (_listener != null)
            {
                _listener.CleanUp();
            }
            return false;
        }
        _rowCounter++;
        ValidateRow(_rowCounter);
        _currentDataRow = _currentDataTable.Rows[_rowCounter];
        while (_currentDataRow.RowState == DataRowState.Deleted)
        {
            _rowCounter++;
            if (_rowCounter == _currentDataTable.Rows.Count)
            {
                _reachEORows = true;
                if (_listener != null)
                {
                    _listener.CleanUp();
                }
                return false;
            }
            ValidateRow(_rowCounter);
            _currentDataRow = _currentDataTable.Rows[_rowCounter];
        }
        if (_currentRowRemoved)
        {
            _currentRowRemoved = false;
        }
        return true;
    }
References System.Data.DataTableReader._currentDataRow, System.Data.DataTableReader._currentDataTable, System.Data.DataTableReader._currentRowRemoved, System.Data.DataTableReader._listener, System.Data.DataTableReader._reachEORows, System.Data.DataTableReader._rowCounter, System.Data.DataTableReader._started, System.Data.DataTableReaderListener.CleanUp(), System.Data.DataRowCollection.Count, System.Data.DataTable.Rows, System.Data.DataRow.RowState, System.Data.DataTableReader.ValidateOpen(), System.Data.DataTableReader.ValidateReader(), and System.Data.DataTableReader.ValidateRow().