Terraria: System.Data.DataTableReader.ValidateRow
ValidateRow()
void System.Data.DataTableReader.ValidateRow (int rowPosition) inline private
Definition at line 861 of file DataTableReader.cs.
    {
        if (ReaderIsInvalid)
        {
            throw ExceptionBuilder.InvalidDataTableReader(_currentDataTable.TableName);
        }
        if (0 > rowPosition || _currentDataTable.Rows.Count <= rowPosition)
        {
            ReaderIsInvalid = true;
            throw ExceptionBuilder.InvalidDataTableReader(_currentDataTable.TableName);
        }
    }
References System.Data.DataTableReader._currentDataTable, System.Data.DataRowCollection.Count, System.Data.ExceptionBuilder.InvalidDataTableReader(), System.Data.DataTableReader.ReaderIsInvalid, System.Data.DataTable.Rows, and System.Data.DataTable.TableName.
Referenced by System.Data.DataTableReader.DataChanged(), and System.Data.DataTableReader.Read().