Terraria: System.Data.DataTableReader.ValidateReader
ValidateReader()
void System.Data.DataTableReader.ValidateReader () inline private
Definition at line 826 of file DataTableReader.cs.
    {
        if (ReaderIsInvalid)
        {
            throw ExceptionBuilder.InvalidDataTableReader(_currentDataTable.TableName);
        }
        if (IsSchemaChanged)
        {
            throw ExceptionBuilder.DataTableReaderSchemaIsInvalid(_currentDataTable.TableName);
        }
    }
References System.Data.DataTableReader._currentDataTable, System.Data.ExceptionBuilder.DataTableReaderSchemaIsInvalid(), System.Data.ExceptionBuilder.InvalidDataTableReader(), System.Data.DataTableReader.IsSchemaChanged, System.Data.DataTableReader.ReaderIsInvalid, and System.Data.DataTable.TableName.
Referenced by System.Data.DataTableReader.GetBoolean(), System.Data.DataTableReader.GetByte(), System.Data.DataTableReader.GetBytes(), System.Data.DataTableReader.GetChar(), System.Data.DataTableReader.GetChars(), System.Data.DataTableReader.GetDataTypeName(), System.Data.DataTableReader.GetDateTime(), System.Data.DataTableReader.GetDecimal(), System.Data.DataTableReader.GetDouble(), System.Data.DataTableReader.GetFieldType(), System.Data.DataTableReader.GetFloat(), System.Data.DataTableReader.GetGuid(), System.Data.DataTableReader.GetInt16(), System.Data.DataTableReader.GetInt32(), System.Data.DataTableReader.GetInt64(), System.Data.DataTableReader.GetName(), System.Data.DataTableReader.GetOrdinal(), System.Data.DataTableReader.GetProviderSpecificFieldType(), System.Data.DataTableReader.GetProviderSpecificValue(), System.Data.DataTableReader.GetProviderSpecificValues(), System.Data.DataTableReader.GetSchemaTable(), System.Data.DataTableReader.GetString(), System.Data.DataTableReader.GetValue(), System.Data.DataTableReader.GetValues(), System.Data.DataTableReader.IsDBNull(), and System.Data.DataTableReader.Read().