Terraria: System.Threading.Tasks.Dataflow.BufferBlock.CompleteCore
CompleteCore()
void System.Threading.Tasks.Dataflow.BufferBlock< T >.CompleteCore (Exception exception, bool storeExceptionEvenIfAlreadyCompleting, bool revertProcessingState = false) inline private
Definition at line 183 of file BufferBlock.cs.
    {
        lock (IncomingLock)
        {
            if (exception != null && (!_targetDecliningPermanently || storeExceptionEvenIfAlreadyCompleting))
            {
                _source.AddException(exception);
            }
            if (revertProcessingState)
            {
                _boundingState.TaskForInputProcessing = null;
            }
            _targetDecliningPermanently = true;
            CompleteTargetIfPossible();
        }
    }
References System.Threading.Tasks.Dataflow.BufferBlock< T >._source, System.Threading.Tasks.Dataflow.BufferBlock< T >._targetDecliningPermanently, System.Threading.Tasks.Dataflow.Internal.SourceCore< TOutput >.AddException(), System.Threading.Tasks.Dataflow.BufferBlock< T >.CompleteTargetIfPossible(), System.exception, and System.Threading.Tasks.Dataflow.BufferBlock< T >.IncomingLock.
Referenced by System.Threading.Tasks.Dataflow.BufferBlock< T >.Complete(), System.Threading.Tasks.Dataflow.BufferBlock< T >.ConsumeAsyncIfNecessary(), System.Threading.Tasks.Dataflow.BufferBlock< T >.ConsumeMessagesLoopCore(), and System.Threading.Tasks.Dataflow.BufferBlock< T >.Fault().