Terraria: System.Threading.Tasks.Dataflow.BufferBlock.CompleteTargetIfPossible
CompleteTargetIfPossible()
void System.Threading.Tasks.Dataflow.BufferBlock< T >.CompleteTargetIfPossible () inline private
Definition at line 340 of file BufferBlock.cs.
    {
        if (!_targetDecliningPermanently || _targetCompletionReserved || (_boundingState != null && _boundingState.TaskForInputProcessing != null))
        {
            return;
        }
        _targetCompletionReserved = true;
        if (_boundingState != null && _boundingState.PostponedMessages.Count > 0)
        {
            Task.Factory.StartNew(delegate(object state)
            {
                BufferBlock<T> bufferBlock = (BufferBlock<T>)state;
                List<Exception> exceptions = null;
                if (bufferBlock._boundingState != null)
                {
                    Common.ReleaseAllPostponedMessages(bufferBlock, bufferBlock._boundingState.PostponedMessages, ref exceptions);
                }
                if (exceptions != null)
                {
                    bufferBlock._source.AddExceptions(exceptions);
                }
                bufferBlock._source.Complete();
            }, this, CancellationToken.None, Common.GetCreationOptionsForTask(), TaskScheduler.Default);
        }
        else
        {
            _source.Complete();
        }
    }
References System.Threading.Tasks.Dataflow.BufferBlock< T >._boundingState, System.Threading.Tasks.Dataflow.BufferBlock< T >._source, System.Threading.Tasks.Dataflow.BufferBlock< T >._targetCompletionReserved, System.Threading.Tasks.Dataflow.BufferBlock< T >._targetDecliningPermanently, System.Threading.Tasks.Dataflow.Internal.SourceCore< TOutput >.Complete(), System.Threading.Tasks.TaskScheduler.Default, System.exceptions, System.Threading.Tasks.Task< TResult >.Factory, System.Threading.Tasks.Dataflow.Internal.Common.GetCreationOptionsForTask(), System.Threading.CancellationToken.None, System.state, and System.Threading.Tasks.Dataflow.Internal.BoundingStateWithPostponedAndTask< TInput >.TaskForInputProcessing.
Referenced by System.Threading.Tasks.Dataflow.BufferBlock< T >.CompleteCore(), System.Threading.Tasks.Dataflow.BufferBlock< T >.ConsumeMessagesLoopCore(), System.Threading.Tasks.Dataflow.BufferBlock< T >.OfferMessage(), and System.Threading.Tasks.Dataflow.BufferBlock< T >.OnItemsRemoved().