Terraria: ReLogic.Peripherals.RGB.Logitech.LogitechKeyboard.Present
Present()
override void ReLogic.Peripherals.RGB.Logitech.LogitechKeyboard.Present () inline
Definition at line 432 of file LogitechKeyboard.cs.
    {
        //IL_000e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0013: Unknown result type (might be due to invalid IL or missing references)
        //IL_001f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0038: Unknown result type (might be due to invalid IL or missing references)
        //IL_004f: Unknown result type (might be due to invalid IL or missing references)
        if (NativeMethods.LogiLedSetTargetDevice(4))
        {
            for (int i = 0; i < base.LedCount; i++)
            {
                Vector4 processedLedColor = GetProcessedLedColor(i);
                _colors[i * 4 + 2] = (byte)(processedLedColor.X * 255f);
                _colors[i * 4 + 1] = (byte)(processedLedColor.Y * 255f);
                _colors[i * 4] = (byte)(processedLedColor.Z * 255f);
                _colors[i * 4 + 3] = byte.MaxValue;
            }
            NativeMethods.LogiLedSetLightingFromBitmap(_colors);
        }
    }
References ReLogic.Peripherals.RGB.Logitech.LogitechKeyboard._colors, ReLogic.Peripherals.RGB.RgbDevice.GetProcessedLedColor(), ReLogic.Peripherals.RGB.Logitech.NativeMethods.LogiLedSetLightingFromBitmap(), and ReLogic.Peripherals.RGB.Logitech.NativeMethods.LogiLedSetTargetDevice().