Terraria: ReLogic.Peripherals.RGB.Logitech.LogitechKeyboard.Render
Render() [2/2]
override void ReLogic.Peripherals.RGB.Logitech.LogitechKeyboard.Render (IEnumerable< RgbKey > keys) inline
    {
        //IL_0018: Unknown result type (might be due to invalid IL or missing references)
        //IL_0028: Unknown result type (might be due to invalid IL or missing references)
        //IL_002d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0032: Unknown result type (might be due to invalid IL or missing references)
        int listCount = 0;
        foreach (RgbKey key in keys)
        {
            if (XnaToLogitechKeys.TryGetValue(key.Key, out var value))
            {
                Color color = ProcessLedColor(key.CurrentColor);
                _excludedKeys[listCount++] = value;
                NativeMethods.LogiLedSetLightingForKeyWithKeyName(value, ((Color)(ref color)).R * 100 / 255, ((Color)(ref color)).G * 100 / 255, ((Color)(ref color)).B * 100 / 255);
            }
        }
        NativeMethods.LogiLedExcludeKeysFromBitmap(_excludedKeys, listCount);
    }
References ReLogic.Peripherals.RGB.Logitech.LogitechKeyboard._excludedKeys, ReLogic.Peripherals.RGB.Logitech.B, ReLogic.Peripherals.RGB.RgbKey.CurrentColor, ReLogic.Peripherals.RGB.Logitech.G, ReLogic.Peripherals.RGB.RgbKey.Key, ReLogic.Peripherals.RGB.Logitech.NativeMethods.LogiLedExcludeKeysFromBitmap(), ReLogic.Peripherals.RGB.Logitech.NativeMethods.LogiLedSetLightingForKeyWithKeyName(), ReLogic.Peripherals.RGB.RgbDevice.ProcessLedColor(), ReLogic.Peripherals.RGB.Logitech.R, and ReLogic.Peripherals.RGB.Logitech.LogitechKeyboard.XnaToLogitechKeys.