Terraria: System.IO.Compression.Zip64ExtraField.GetJustZip64Block
GetJustZip64Block()
static Zip64ExtraField System.IO.Compression.Zip64ExtraField.GetJustZip64Block (Stream extraFieldStream, bool readUncompressedSize, bool readCompressedSize, bool readLocalHeaderOffset, bool readStartDiskNumber) inline static
Definition at line 81 of file Zip64ExtraField.cs.
    {
        Zip64ExtraField zip64Block;
        using (BinaryReader reader = new BinaryReader(extraFieldStream))
        {
            ZipGenericExtraField field;
            while (ZipGenericExtraField.TryReadBlock(reader, extraFieldStream.Length, out field))
            {
                if (TryGetZip64BlockFromGenericExtraField(field, readUncompressedSize, readCompressedSize, readLocalHeaderOffset, readStartDiskNumber, out zip64Block))
                {
                    return zip64Block;
                }
            }
        }
        zip64Block = default(Zip64ExtraField);
        zip64Block._compressedSize = null;
        zip64Block._uncompressedSize = null;
        zip64Block._localHeaderOffset = null;
        zip64Block._startDiskNumber = null;
        return zip64Block;
    }
References System.IO.Compression.Zip64ExtraField.TryGetZip64BlockFromGenericExtraField(), and System.IO.Compression.ZipGenericExtraField.TryReadBlock().
Referenced by System.IO.Compression.ZipCentralDirectoryFileHeader.TryReadBlock().