Terraria: System.Xml.XmlTextEncoder.WriteRaw
WriteRaw()
void System.Xml.XmlTextEncoder.WriteRaw (char[] array, int offset, int count) inline package
Definition at line 389 of file XmlTextEncoder.cs.
    {
        if (array == null)
        {
            throw new ArgumentNullException("array");
        }
        if (0 > count)
        {
            throw new ArgumentOutOfRangeException("count");
        }
        if (0 > offset)
        {
            throw new ArgumentOutOfRangeException("offset");
        }
        if (count > array.Length - offset)
        {
            throw new ArgumentOutOfRangeException("count");
        }
        if (_cacheAttrValue)
        {
            _attrValue.Append(array, offset, count);
        }
        _textWriter.Write(array, offset, count);
    }
References System.Xml.XmlTextEncoder._attrValue, System.Xml.XmlTextEncoder._cacheAttrValue, System.Xml.XmlTextEncoder._textWriter, System.Text.StringBuilder.Append(), System.array, System.count, System.offset, and System.IO.TextWriter.Write().
Referenced by System.Xml.XmlTextWriterBase64Encoder.WriteChars().