Terraria: System.Xml.XmlTextEncoder.WriteCharEntity
WriteCharEntity()
void System.Xml.XmlTextEncoder.WriteCharEntity (char ch) inline package
Definition at line 414 of file XmlTextEncoder.cs.
    {
        if (XmlCharType.IsSurrogate(ch))
        {
            throw new ArgumentException(System.SR.Xml_InvalidSurrogateMissingLowChar);
        }
        int num = ch;
        string text = num.ToString("X", NumberFormatInfo.InvariantInfo);
        if (_cacheAttrValue)
        {
            _attrValue.Append("&#x");
            _attrValue.Append(text);
            _attrValue.Append(';');
        }
        WriteCharEntityImpl(text);
    }
References System.Xml.XmlTextEncoder._attrValue, System.Xml.XmlTextEncoder._cacheAttrValue, System.Text.StringBuilder.Append(), System.Xml.ArgumentException, System.ch, System.Globalization.NumberFormatInfo.InvariantInfo, System.Xml.XmlCharType.IsSurrogate(), System.text, System.Xml.XmlTextEncoder.WriteCharEntityImpl(), and System.SR.Xml_InvalidSurrogateMissingLowChar.