Terraria: System.Xml.XmlTextEncoder.WriteSurrogateCharEntity
WriteSurrogateCharEntity()
void System.Xml.XmlTextEncoder.WriteSurrogateCharEntity (char lowChar, char highChar) inline package
Definition at line 193 of file XmlTextEncoder.cs.
    {
        if (!XmlCharType.IsLowSurrogate(lowChar) || !XmlCharType.IsHighSurrogate(highChar))
        {
            throw XmlConvert.CreateInvalidSurrogatePairException(lowChar, highChar);
        }
        int num = XmlCharType.CombineSurrogateChar(lowChar, highChar);
        if (_cacheAttrValue)
        {
            _attrValue.Append(highChar);
            _attrValue.Append(lowChar);
        }
        _textWriter.Write("&#x");
        _textWriter.Write(num.ToString("X", NumberFormatInfo.InvariantInfo));
        _textWriter.Write(';');
    }
References System.Xml.XmlTextEncoder._attrValue, System.Xml.XmlTextEncoder._cacheAttrValue, System.Xml.XmlTextEncoder._textWriter, System.Text.StringBuilder.Append(), System.Xml.XmlCharType.CombineSurrogateChar(), System.Xml.XmlConvert.CreateInvalidSurrogatePairException(), System.Xml.Dictionary, System.Globalization.NumberFormatInfo.InvariantInfo, System.Xml.XmlCharType.IsHighSurrogate(), System.Xml.XmlCharType.IsLowSurrogate(), and System.IO.TextWriter.Write().