Terraria: System.Xml.XmlTextEncoder.WriteSurrogateChar
WriteSurrogateChar()
void System.Xml.XmlTextEncoder.WriteSurrogateChar (char lowChar, char highChar) inline package
Definition at line 72 of file XmlTextEncoder.cs.
    {
        if (!XmlCharType.IsLowSurrogate(lowChar) || !XmlCharType.IsHighSurrogate(highChar))
        {
            throw XmlConvert.CreateInvalidSurrogatePairException(lowChar, highChar);
        }
        _textWriter.Write(highChar);
        _textWriter.Write(lowChar);
    }
References System.Xml.XmlTextEncoder._textWriter, System.Xml.XmlConvert.CreateInvalidSurrogatePairException(), System.Xml.Dictionary, System.Xml.XmlCharType.IsHighSurrogate(), System.Xml.XmlCharType.IsLowSurrogate(), and System.IO.TextWriter.Write().
Referenced by System.Xml.XmlTextEncoder.Write(), and System.Xml.XmlTextEncoder.Write().