Terraria: System.Xml.XmlTextEncoder.Write
Write() [1/2]
void System.Xml.XmlTextEncoder.Write (char[] array, int offset, int count) inline package
Definition at line 82 of file XmlTextEncoder.cs.
    {
        if (array == null)
        {
            throw new ArgumentNullException("array");
        }
        if (0 > offset)
        {
            throw new ArgumentOutOfRangeException("offset");
        }
        if (0 > count)
        {
            throw new ArgumentOutOfRangeException("count");
        }
        if (count > array.Length - offset)
        {
            throw new ArgumentOutOfRangeException("count");
        }
        if (_cacheAttrValue)
        {
            _attrValue.Append(array, offset, count);
        }
        int num = offset + count;
        int i = offset;
        char c = '\0';
        while (true)
        {
            int num2 = i;
            for (; i < num; i++)
            {
                if (!XmlCharType.IsAttributeValueChar(c = array[i]))
                {
                    break;
                }
            }
            if (num2 < i)
            {
                _textWriter.Write(array, num2, i - num2);
            }
            if (i == num)
            {
                break;
            }
            switch (c)
            {
            case '\t':
                _textWriter.Write(c);
                break;
            case '\n':
            case '\r':
                if (_inAttribute)
                {
                    WriteCharEntityImpl(c);
                }
                else
                {
                    _textWriter.Write(c);
                }
                break;
            case '<':
                WriteEntityRefImpl("lt");
                break;
            case '>':
                WriteEntityRefImpl("gt");
                break;
            case '&':
                WriteEntityRefImpl("amp");
                break;
            case '\'':
                if (_inAttribute && _quoteChar == c)
                {
                    WriteEntityRefImpl("apos");
                }
                else
                {
                    _textWriter.Write('\'');
                }
                break;
            case '"':
                if (_inAttribute && _quoteChar == c)
                {
                    WriteEntityRefImpl("quot");
                }
                else
                {
                    _textWriter.Write('"');
                }
                break;
            default:
                if (XmlCharType.IsHighSurrogate(c))
                {
                    if (i + 1 >= num)
                    {
                        throw new ArgumentException(System.SR.Xml_SurrogatePairSplit);
                    }
                    WriteSurrogateChar(array[++i], c);
                }
                else
                {
                    if (XmlCharType.IsLowSurrogate(c))
                    {
                        throw XmlConvert.CreateInvalidHighSurrogateCharException(c);
                    }
                    WriteCharEntityImpl(c);
                }
                break;
            }
            i++;
        }
    }
References System.Xml.XmlTextEncoder._attrValue, System.Xml.XmlTextEncoder._cacheAttrValue, System.Xml.XmlTextEncoder._inAttribute, System.Xml.XmlTextEncoder._quoteChar, System.Xml.XmlTextEncoder._textWriter, System.Text.StringBuilder.Append(), System.Xml.ArgumentException, System.array, System.count, System.Xml.XmlConvert.CreateInvalidHighSurrogateCharException(), System.Xml.Dictionary, System.Xml.XmlCharType.IsAttributeValueChar(), System.Xml.XmlCharType.IsHighSurrogate(), System.Xml.XmlCharType.IsLowSurrogate(), System.offset, System.IO.TextWriter.Write(), System.Xml.XmlTextEncoder.WriteCharEntityImpl(), System.Xml.XmlTextEncoder.WriteEntityRefImpl(), System.Xml.XmlTextEncoder.WriteSurrogateChar(), and System.SR.Xml_SurrogatePairSplit.
Referenced by System.Xml.Xsl.XsltOld.ReaderOutput.XmlEncoder.AttributeInnerXml(), and System.Xml.Xsl.XsltOld.ReaderOutput.XmlEncoder.AttributeOuterXml().