Terraria: System.Xml.XmlTextEncoder.WriteRawWithSurrogateChecking
WriteRawWithSurrogateChecking()
void System.Xml.XmlTextEncoder.WriteRawWithSurrogateChecking (string text) inline package
Definition at line 340 of file XmlTextEncoder.cs.
    {
        if (text == null)
        {
            return;
        }
        if (_cacheAttrValue)
        {
            _attrValue.Append(text);
        }
        int length = text.Length;
        int num = 0;
        char c = '\0';
        while (true)
        {
            if (num < length && (XmlCharType.IsCharData(c = text[num]) || c < ' '))
            {
                num++;
                continue;
            }
            if (num == length)
            {
                break;
            }
            if (XmlCharType.IsHighSurrogate(c))
            {
                if (num + 1 >= length)
                {
                    throw new ArgumentException(System.SR.Xml_InvalidSurrogateMissingLowChar);
                }
                char c2 = text[num + 1];
                if (!XmlCharType.IsLowSurrogate(c2))
                {
                    throw XmlConvert.CreateInvalidSurrogatePairException(c2, c);
                }
                num += 2;
            }
            else
            {
                if (XmlCharType.IsLowSurrogate(c))
                {
                    throw XmlConvert.CreateInvalidHighSurrogateCharException(c);
                }
                num++;
            }
        }
        _textWriter.Write(text);
    }
References System.Xml.XmlTextEncoder._attrValue, System.Xml.XmlTextEncoder._cacheAttrValue, System.Xml.XmlTextEncoder._textWriter, System.Text.StringBuilder.Append(), System.Xml.ArgumentException, System.Xml.XmlConvert.CreateInvalidHighSurrogateCharException(), System.Xml.XmlConvert.CreateInvalidSurrogatePairException(), System.Xml.Dictionary, System.Xml.XmlCharType.IsCharData(), System.Xml.XmlCharType.IsHighSurrogate(), System.Xml.XmlCharType.IsLowSurrogate(), System.length, System.Text.StringBuilder.Length, System.text, System.IO.TextWriter.Write(), and System.SR.Xml_InvalidSurrogateMissingLowChar.