Terraria: System.Xml.XmlTextEncoder.Write
Write() [2/2]
void System.Xml.XmlTextEncoder.Write (string text) inline package
Definition at line 210 of file XmlTextEncoder.cs.
    {
        if (text == null)
        {
            return;
        }
        if (_cacheAttrValue)
        {
            _attrValue.Append(text);
        }
        int length = text.Length;
        int i = 0;
        int num = 0;
        char c = '\0';
        while (true)
        {
            if (i < length && XmlCharType.IsAttributeValueChar(c = text[i]))
            {
                i++;
                continue;
            }
            if (i == length)
            {
                _textWriter.Write(text);
                return;
            }
            if (_inAttribute)
            {
                if (c != '\t')
                {
                    break;
                }
                i++;
            }
            else
            {
                if (c != '\t' && c != '\n' && c != '\r' && c != '"' && c != '\'')
                {
                    break;
                }
                i++;
            }
        }
        char[] helperBuffer = new char[256];
        while (true)
        {
            if (num < i)
            {
                WriteStringFragment(text, num, i - num, helperBuffer);
            }
            if (i == length)
            {
                break;
            }
            switch (c)
            {
            case '\t':
                _textWriter.Write(c);
                break;
            case '\n':
            case '\r':
                if (_inAttribute)
                {
                    WriteCharEntityImpl(c);
                }
                else
                {
                    _textWriter.Write(c);
                }
                break;
            case '<':
                WriteEntityRefImpl("lt");
                break;
            case '>':
                WriteEntityRefImpl("gt");
                break;
            case '&':
                WriteEntityRefImpl("amp");
                break;
            case '\'':
                if (_inAttribute && _quoteChar == c)
                {
                    WriteEntityRefImpl("apos");
                }
                else
                {
                    _textWriter.Write('\'');
                }
                break;
            case '"':
                if (_inAttribute && _quoteChar == c)
                {
                    WriteEntityRefImpl("quot");
                }
                else
                {
                    _textWriter.Write('"');
                }
                break;
            default:
                if (XmlCharType.IsHighSurrogate(c))
                {
                    if (i + 1 >= length)
                    {
                        throw XmlConvert.CreateInvalidSurrogatePairException(text[i], c);
                    }
                    WriteSurrogateChar(text[++i], c);
                }
                else
                {
                    if (XmlCharType.IsLowSurrogate(c))
                    {
                        throw XmlConvert.CreateInvalidHighSurrogateCharException(c);
                    }
                    WriteCharEntityImpl(c);
                }
                break;
            }
            i++;
            num = i;
            for (; i < length; i++)
            {
                if (!XmlCharType.IsAttributeValueChar(c = text[i]))
                {
                    break;
                }
            }
        }
    }
References System.Xml.XmlTextEncoder._attrValue, System.Xml.XmlTextEncoder._cacheAttrValue, System.Xml.XmlTextEncoder._inAttribute, System.Xml.XmlTextEncoder._quoteChar, System.Xml.XmlTextEncoder._textWriter, System.Text.StringBuilder.Append(), System.Xml.XmlConvert.CreateInvalidHighSurrogateCharException(), System.Xml.XmlConvert.CreateInvalidSurrogatePairException(), System.Xml.Dictionary, System.Xml.XmlCharType.IsAttributeValueChar(), System.Xml.XmlCharType.IsHighSurrogate(), System.Xml.XmlCharType.IsLowSurrogate(), System.length, System.Text.StringBuilder.Length, System.text, System.IO.TextWriter.Write(), System.Xml.XmlTextEncoder.WriteCharEntityImpl(), System.Xml.XmlTextEncoder.WriteEntityRefImpl(), System.Xml.XmlTextEncoder.WriteStringFragment(), and System.Xml.XmlTextEncoder.WriteSurrogateChar().