Terraria: System.Xml.XmlTextEncoder.WriteEntityRefImpl
WriteEntityRefImpl()
void System.Xml.XmlTextEncoder.WriteEntityRefImpl (string name) inline private
Definition at line 472 of file XmlTextEncoder.cs.
    {
        _textWriter.Write('&');
        _textWriter.Write(name);
        _textWriter.Write(';');
    }
References System.Xml.XmlTextEncoder._textWriter, and System.IO.TextWriter.Write().
Referenced by System.Xml.XmlTextEncoder.Write(), System.Xml.XmlTextEncoder.Write(), and System.Xml.XmlTextEncoder.WriteEntityRef().