Terraria: System.Xml.XmlTextEncoder.WriteCharEntityImpl
WriteCharEntityImpl() [1/2]
void System.Xml.XmlTextEncoder.WriteCharEntityImpl (char ch) inline private
Definition at line 459 of file XmlTextEncoder.cs.
    {
        int num = ch;
        WriteCharEntityImpl(num.ToString("X", NumberFormatInfo.InvariantInfo));
    }
References System.ch, System.Globalization.NumberFormatInfo.InvariantInfo, and System.Xml.XmlTextEncoder.WriteCharEntityImpl().
Referenced by System.Xml.XmlTextEncoder.Write(), System.Xml.XmlTextEncoder.Write(), System.Xml.XmlTextEncoder.WriteCharEntity(), and System.Xml.XmlTextEncoder.WriteCharEntityImpl().