Terraria: Terraria.GameContent.PlayerQueenSlimeMountTextureContent.HandleUseReqest
HandleUseReqest()
override void Terraria.GameContent.PlayerQueenSlimeMountTextureContent.HandleUseReqest (GraphicsDevice device, SpriteBatch spriteBatch) inline protected
Definition at line 11 of file PlayerQueenSlimeMountTextureContent.cs.
    {
        Asset<Texture2D> val = TextureAssets.Extra[204];
        PrepareARenderTarget_AndListenToEvents(ref _target, device, val.Width(), val.Height(), RenderTargetUsage.PreserveContents);
        device.SetRenderTarget(_target);
        device.Clear(Color.Transparent);
        DrawData value = new DrawData(val.Value, Vector2.Zero, Color.White);
        spriteBatch.Begin(SpriteSortMode.Immediate, BlendState.AlphaBlend);
        GameShaders.Misc["QueenSlime"].Apply(value);
        value.Draw(spriteBatch);
        spriteBatch.End();
        device.SetRenderTarget(null);
        _wasPrepared = true;
    }
References Terraria.GameContent.ARenderTargetContentByRequest._target, Terraria.GameContent.ARenderTargetContentByRequest._wasPrepared, Microsoft.Xna.Framework.Graphics.BlendState.AlphaBlend, Microsoft.Xna.Framework.Graphics.SpriteBatch.Begin(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.Clear(), Microsoft.Xna.Framework.Graphics.SpriteBatch.End(), Terraria.GameContent.TextureAssets.Extra, Terraria.Graphics.Shaders.GameShaders.Misc, Terraria.GameContent.ARenderTargetContentByRequest.PrepareARenderTarget_AndListenToEvents(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.SetRenderTarget(), Microsoft.Xna.Framework.Color.Transparent, ReLogic.Content.Asset< T >.Value, Microsoft.Xna.Framework.Color.White, and Microsoft.Xna.Framework.Vector2.Zero.