Terraria: MS.Internal.Xml.XPath.IDQuery.Evaluate
Evaluate()
override object MS.Internal.Xml.XPath.IDQuery.Evaluate (XPathNodeIterator context) inline
Definition at line 18 of file IDQuery.cs.
    {
        object obj = base.Evaluate(context);
        XPathNavigator contextNode = context.Current.Clone();
        switch (GetXPathType(obj))
        {
        case XPathResultType.NodeSet:
        {
            XPathNavigator xPathNavigator;
            while ((xPathNavigator = input.Advance()) != null)
            {
                ProcessIds(contextNode, xPathNavigator.Value);
            }
            break;
        }
        case XPathResultType.String:
            ProcessIds(contextNode, (string)obj);
            break;
        case XPathResultType.Number:
            ProcessIds(contextNode, StringFunctions.toString((double)obj));
            break;
        case XPathResultType.Boolean:
            ProcessIds(contextNode, StringFunctions.toString((bool)obj));
            break;
        case (XPathResultType)4:
            ProcessIds(contextNode, ((XPathNavigator)obj).Value);
            break;
        }
        return this;
    }
References MS.Internal.Xml.XPath.Query.Advance(), System.Xml.XPath.XPathNavigator.Clone(), System.Xml.XPath.XPathNodeIterator.Current, System.Xml.Dictionary, MS.Internal.Xml.XPath.Query.GetXPathType(), MS.Internal.Xml.XPath.CacheOutputQuery.input, MS.Internal.Xml.XPath.IDQuery.ProcessIds(), MS.Internal.Xml.XPath.StringFunctions.toString(), and System.Xml.XPath.XPathItem.Value.
Referenced by MS.Internal.Xml.XPath.IDQuery.MatchNode().