Terraria: System.StubHelpers.AnsiCharMarshaler.DoAnsiConversion
DoAnsiConversion()
static unsafe byte[] System.StubHelpers.AnsiCharMarshaler.DoAnsiConversion (string str, bool fBestFit, bool fThrowOnUnmappableChar, out int cbLength) inline static package
Definition at line 8 of file AnsiCharMarshaler.cs.
    {
        byte[] array = new byte[checked((str.Length + 1) * Marshal.SystemMaxDBCSCharSize)];
        fixed (byte* buffer = &array[0])
        {
            cbLength = Marshal.StringToAnsiString(str, buffer, array.Length, fBestFit, fThrowOnUnmappableChar);
        }
        return array;
    }
References System.array, System.buffer, System.str, System.Runtime.InteropServices.Marshal.StringToAnsiString(), and System.Runtime.InteropServices.Marshal.SystemMaxDBCSCharSize.
Referenced by System.StubHelpers.AnsiBSTRMarshaler.ConvertToNative(), System.StubHelpers.CSTRMarshaler.ConvertToNative(), and System.StubHelpers.VBByValStrMarshaler.ConvertToNative().