Terraria: Terraria.GameContent.UI.Elements.UICharacterNameButton.SetContents
SetContents()
void Terraria.GameContent.UI.Elements.UICharacterNameButton.SetContents (string name) inline
Definition at line 85 of file UICharacterNameButton.cs.
    {
        actualContents = name;
        if (string.IsNullOrEmpty(actualContents))
        {
            _text.TextColor = Color.Gray;
            _text.SetText(_textToShowWhenEmpty);
        }
        else
        {
            _text.TextColor = Color.White;
            _text.SetText(actualContents);
        }
        _text.Left = StyleDimension.FromPixels(_title.GetInnerDimensions().Width + DistanceFromTitleToOption);
    }
References Terraria.GameContent.UI.Elements.UICharacterNameButton._text, Terraria.GameContent.UI.Elements.UICharacterNameButton._textToShowWhenEmpty, Terraria.GameContent.UI.Elements.UICharacterNameButton._title, Terraria.GameContent.UI.Elements.UICharacterNameButton.actualContents, Terraria.GameContent.UI.Elements.UICharacterNameButton.DistanceFromTitleToOption, Terraria.UI.StyleDimension.FromPixels(), Terraria.UI.UIElement.GetInnerDimensions(), Microsoft.Xna.Framework.Color.Gray, Terraria.GameContent.UI.Elements.UIText.SetText(), Microsoft.Xna.Framework.Color.White, and Terraria.UI.CalculatedStyle.Width.
Referenced by Terraria.GameContent.UI.Elements.UICharacterNameButton.UICharacterNameButton(), Terraria.GameContent.UI.States.UICharacterCreation.OnFinishedNaming(), Terraria.GameContent.UI.States.UICharacterCreation.OnFinishedNamingAndCreating(), Terraria.GameContent.UI.States.AWorkshopPublishInfoState< TPublishedObjectType >.UpdateImagePreview(), and Terraria.GameContent.UI.States.UIWorldCreation.UpdateInputFields().