Terraria: Terraria.GameContent.UI.Elements.UICharacterNameButton.DrawSelf
DrawSelf()
override void Terraria.GameContent.UI.Elements.UICharacterNameButton.DrawSelf (SpriteBatch spriteBatch) inline protected virtual
Reimplemented from Terraria.UI.UIElement.
    {
        if (_hovered)
        {
            if (!_soundedHover)
            {
                SoundEngine.PlaySound(12);
            }
            _soundedHover = true;
        }
        else
        {
            _soundedHover = false;
        }
        CalculatedStyle dimensions = GetDimensions();
        Utils.DrawSplicedPanel(spriteBatch, _BasePanelTexture.Value, (int)dimensions.X, (int)dimensions.Y, (int)dimensions.Width, (int)dimensions.Height, 10, 10, 10, 10, Color.White * 0.5f);
        if (_hovered)
        {
            Utils.DrawSplicedPanel(spriteBatch, _hoveredBorderTexture.Value, (int)dimensions.X, (int)dimensions.Y, (int)dimensions.Width, (int)dimensions.Height, 10, 10, 10, 10, Color.White);
        }
    }
References Terraria.GameContent.UI.Elements.UICharacterNameButton._BasePanelTexture, Terraria.GameContent.UI.Elements.UICharacterNameButton._hovered, Terraria.GameContent.UI.Elements.UICharacterNameButton._hoveredBorderTexture, Terraria.GameContent.UI.Elements.UICharacterNameButton._soundedHover, Terraria.Utils.DrawSplicedPanel(), Terraria.UI.UIElement.GetDimensions(), Terraria.Audio.SoundEngine.PlaySound(), and ReLogic.Content.Asset< T >.Value.