Terraria: System.Data.Common.DataRecordInternal.GetChars
GetChars() [1/2]
override long System.Data.Common.DataRecordInternal.GetChars (int i, long dataIndex, char[] buffer, int bufferIndex, int length) inline
Definition at line 131 of file DataRecordInternal.cs.
    {
        string text = (string)_values[i];
        char[] array = text.ToCharArray();
        int num = array.Length;
        if (dataIndex > int.MaxValue)
        {
            throw ADP.InvalidSourceBufferIndex(num, dataIndex, "dataIndex");
        }
        int num2 = (int)dataIndex;
        if (buffer == null)
        {
            return num;
        }
        try
        {
            if (num2 < num)
            {
                num = ((num2 + length <= num) ? length : (num - num2));
            }
            Array.Copy(array, num2, buffer, bufferIndex, num);
        }
        catch (Exception e) when (ADP.IsCatchableExceptionType(e))
        {
            num = array.Length;
            if (length < 0)
            {
                throw ADP.InvalidDataLength(length);
            }
            if (bufferIndex < 0 || bufferIndex >= buffer.Length)
            {
                throw ADP.InvalidDestinationBufferIndex(buffer.Length, bufferIndex, "bufferIndex");
            }
            if (num2 < 0 || num2 >= num)
            {
                throw ADP.InvalidSourceBufferIndex(num, dataIndex, "dataIndex");
            }
            if (num + bufferIndex > buffer.Length)
            {
                throw ADP.InvalidBufferSizeOrIndex(num, bufferIndex);
            }
        }
        return num;
    }
References System.Data.Common.DataRecordInternal._values, System.array, System.buffer, System.Array.Copy(), System.Data.Common.ADP.InvalidBufferSizeOrIndex(), System.Data.Common.ADP.InvalidDataLength(), System.Data.Common.ADP.InvalidDestinationBufferIndex(), System.Data.Common.ADP.InvalidSourceBufferIndex(), System.Data.Common.ADP.IsCatchableExceptionType(), System.length, and System.text.