Terraria: System.Linq.Expressions.UnaryExpression.ReduceIndex
ReduceIndex()
Expression System.Linq.Expressions.UnaryExpression.ReduceIndex () inline private
Definition at line 143 of file UnaryExpression.cs.
    {
        bool isPrefix = IsPrefix;
        IndexExpression indexExpression = (IndexExpression)Operand;
        int argumentCount = indexExpression.ArgumentCount;
        Expression[] array = new Expression[argumentCount + (isPrefix ? 2 : 4)];
        ParameterExpression[] array2 = new ParameterExpression[argumentCount + (isPrefix ? 1 : 2)];
        ParameterExpression[] array3 = new ParameterExpression[argumentCount];
        int num = 0;
        array2[num] = Expression.Parameter(indexExpression.Object.Type, null);
        array[num] = Expression.Assign(array2[num], indexExpression.Object);
        for (num++; num <= argumentCount; num++)
        {
            Expression argument = indexExpression.GetArgument(num - 1);
            array3[num - 1] = (array2[num] = Expression.Parameter(argument.Type, null));
            array[num] = Expression.Assign(array2[num], argument);
        }
        ParameterExpression instance = array2[0];
        PropertyInfo? indexer = indexExpression.Indexer;
        Expression[] list = array3;
        indexExpression = Expression.MakeIndex(instance, indexer, new TrueReadOnlyCollection<Expression>(list));
        if (!isPrefix)
        {
            ParameterExpression parameterExpression = (array2[num] = Expression.Parameter(indexExpression.Type, null));
            array[num] = Expression.Assign(array2[num], indexExpression);
            num++;
            array[num++] = Expression.Assign(indexExpression, FunctionalOp(parameterExpression));
            array[num++] = parameterExpression;
        }
        else
        {
            array[num++] = Expression.Assign(indexExpression, FunctionalOp(indexExpression));
        }
        return Expression.Block(new TrueReadOnlyCollection<ParameterExpression>(array2), new TrueReadOnlyCollection<Expression>(array));
    }
References System.Linq.Expressions.IndexExpression.ArgumentCount, System.array, System.Linq.Expressions.Expression< TDelegate >.Assign(), System.Linq.Expressions.Expression< TDelegate >.Block(), System.Linq.Expressions.UnaryExpression.FunctionalOp(), System.Linq.Expressions.IndexExpression.GetArgument(), System.Linq.Expressions.IndexExpression.Indexer, System.Linq.Expressions.UnaryExpression.IsPrefix, System.list, System.Linq.Expressions.Expression< TDelegate >.MakeIndex(), System.Linq.Expressions.IndexExpression.Object, System.Linq.Expressions.UnaryExpression.Operand, System.Linq.Expressions.Expression< TDelegate >.Parameter(), System.Linq.Expressions.Expression< TDelegate >.Type, and System.Linq.Expressions.IndexExpression.Type.
Referenced by System.Linq.Expressions.UnaryExpression.Reduce().