Terraria: System.Linq.Expressions.UnaryExpression.ReduceVariable
ReduceVariable()
Expression System.Linq.Expressions.UnaryExpression.ReduceVariable () inline private
Definition at line 115 of file UnaryExpression.cs.
    {
        if (IsPrefix)
        {
            return Expression.Assign(Operand, FunctionalOp(Operand));
        }
        ParameterExpression parameterExpression = Expression.Parameter(Operand.Type, null);
        return Expression.Block(new TrueReadOnlyCollection<ParameterExpression>(parameterExpression), new TrueReadOnlyCollection<Expression>(Expression.Assign(parameterExpression, Operand), Expression.Assign(Operand, FunctionalOp(parameterExpression)), parameterExpression));
    }
References System.Linq.Expressions.Expression< TDelegate >.Assign(), System.Linq.Expressions.Expression< TDelegate >.Block(), System.Linq.Expressions.UnaryExpression.FunctionalOp(), System.Linq.Expressions.UnaryExpression.IsPrefix, System.Linq.Expressions.UnaryExpression.Operand, System.Linq.Expressions.Expression< TDelegate >.Parameter(), and System.Linq.Expressions.Expression< TDelegate >.Type.
Referenced by System.Linq.Expressions.UnaryExpression.Reduce(), and System.Linq.Expressions.UnaryExpression.ReduceMember().