Terraria: System.Linq.Expressions.UnaryExpression.ReduceMember
ReduceMember()
Expression System.Linq.Expressions.UnaryExpression.ReduceMember () inline private
Definition at line 125 of file UnaryExpression.cs.
    {
        MemberExpression memberExpression = (MemberExpression)Operand;
        if (memberExpression.Expression == null)
        {
            return ReduceVariable();
        }
        ParameterExpression parameterExpression = Expression.Parameter(memberExpression.Expression.Type, null);
        BinaryExpression binaryExpression = Expression.Assign(parameterExpression, memberExpression.Expression);
        memberExpression = Expression.MakeMemberAccess(parameterExpression, memberExpression.Member);
        if (IsPrefix)
        {
            return Expression.Block(new TrueReadOnlyCollection<ParameterExpression>(parameterExpression), new TrueReadOnlyCollection<Expression>(binaryExpression, Expression.Assign(memberExpression, FunctionalOp(memberExpression))));
        }
        ParameterExpression parameterExpression2 = Expression.Parameter(memberExpression.Type, null);
        return Expression.Block(new TrueReadOnlyCollection<ParameterExpression>(parameterExpression, parameterExpression2), new TrueReadOnlyCollection<Expression>(binaryExpression, Expression.Assign(parameterExpression2, memberExpression), Expression.Assign(memberExpression, FunctionalOp(parameterExpression2)), parameterExpression2));
    }
References System.Linq.Expressions.Expression< TDelegate >.Assign(), System.Linq.Expressions.Expression< TDelegate >.Block(), System.Linq.Expressions.MemberExpression.Expression, System.Linq.Expressions.UnaryExpression.FunctionalOp(), System.Linq.Expressions.UnaryExpression.IsPrefix, System.Linq.Expressions.Expression< TDelegate >.MakeMemberAccess(), System.Linq.Expressions.MemberExpression.Member, System.Linq.Expressions.UnaryExpression.Operand, System.Linq.Expressions.Expression< TDelegate >.Parameter(), System.Linq.Expressions.UnaryExpression.ReduceVariable(), and System.Linq.Expressions.Expression< TDelegate >.Type.
Referenced by System.Linq.Expressions.UnaryExpression.Reduce().