Terraria: CreativePowers.ASharedButtonPower.ProvidePowerButtons
ProvidePowerButtons()
void CreativePowers.ASharedButtonPower.ProvidePowerButtons (CreativePowerUIElementRequestInfo info, List< UIElement > elements) inline inherited
Implements ICreativePower.
         {
             GroupOptionButton<bool> groupOptionButton = CreativePowersHelper.CreateSimpleButton(info);
             CreativePowersHelper.UpdateUnlockStateByPower(this, groupOptionButton, CreativePowersHelper.CommonSelectedColor);
             groupOptionButton.Append(CreativePowersHelper.GetIconImage(_iconLocation));
             groupOptionButton.OnLeftClick += button_OnClick;
             groupOptionButton.OnUpdate += button_OnUpdate;
             elements.Add(groupOptionButton);
         }
References CreativePowers.ASharedButtonPower._iconLocation, UIElement.Append(), CreativePowers.ASharedButtonPower.button_OnClick(), CreativePowers.ASharedButtonPower.button_OnUpdate(), CreativePowersHelper.CommonSelectedColor, CreativePowersHelper.CreateSimpleButton(), CreativePowersHelper.GetIconImage(), UIElement.OnLeftClick, UIElement.OnUpdate, and CreativePowersHelper.UpdateUnlockStateByPower().