Terraria: System.Xml.DataSetMapper.IsRegionRadical
IsRegionRadical()
bool System.Xml.DataSetMapper.IsRegionRadical (XmlBoundElement rowElem) inline package
Definition at line 150 of file DataSetMapper.cs.
    {
        if (rowElem.ElementState == ElementState.Defoliated)
        {
            return true;
        }
        DataTable tableSchemaForElement = GetTableSchemaForElement(rowElem);
        DataColumnCollection columns = tableSchemaForElement.Columns;
        int iColumn = 0;
        int count = rowElem.Attributes.Count;
        for (int i = 0; i < count; i++)
        {
            XmlAttribute xmlAttribute = rowElem.Attributes[i];
            if (!xmlAttribute.Specified)
            {
                return false;
            }
            DataColumn columnSchemaForNode = GetColumnSchemaForNode(rowElem, xmlAttribute);
            if (columnSchemaForNode == null)
            {
                return false;
            }
            if (!IsNextColumn(columns, ref iColumn, columnSchemaForNode))
            {
                return false;
            }
            XmlNode firstChild = xmlAttribute.FirstChild;
            if (firstChild == null || firstChild.NodeType != XmlNodeType.Text || firstChild.NextSibling != null)
            {
                return false;
            }
        }
        iColumn = 0;
        XmlNode xmlNode;
        for (xmlNode = rowElem.FirstChild; xmlNode != null; xmlNode = xmlNode.NextSibling)
        {
            if (xmlNode.NodeType != XmlNodeType.Element)
            {
                return false;
            }
            XmlElement xmlElement = xmlNode as XmlElement;
            if (GetRowFromElement(xmlElement) != null)
            {
                break;
            }
            DataColumn columnSchemaForNode2 = GetColumnSchemaForNode(rowElem, xmlElement);
            if (columnSchemaForNode2 == null)
            {
                return false;
            }
            if (!IsNextColumn(columns, ref iColumn, columnSchemaForNode2))
            {
                return false;
            }
            if (xmlElement.HasAttributes)
            {
                return false;
            }
            XmlNode firstChild2 = xmlElement.FirstChild;
            if (firstChild2 == null || firstChild2.NodeType != XmlNodeType.Text || firstChild2.NextSibling != null)
            {
                return false;
            }
        }
        while (xmlNode != null)
        {
            if (xmlNode.NodeType != XmlNodeType.Element)
            {
                return false;
            }
            DataRow rowFromElement = GetRowFromElement((XmlElement)xmlNode);
            if (rowFromElement == null)
            {
                return false;
            }
            xmlNode = xmlNode.NextSibling;
        }
        return true;
    }
References System.Xml.XmlNode.Attributes, System.Data.InternalDataCollectionBase.Count, System.count, System.Xml.Dictionary, System.Xml.XmlNode.FirstChild, System.Xml.DataSetMapper.GetColumnSchemaForNode(), System.Xml.DataSetMapper.GetRowFromElement(), System.Xml.DataSetMapper.GetTableSchemaForElement(), and System.Xml.DataSetMapper.IsNextColumn().
Referenced by System.Xml.XmlDataDocument.DefoliateRegion().