Terraria: System.Xml.DataSetMapper.SetupMapping
SetupMapping()
void System.Xml.DataSetMapper.SetupMapping (XmlDataDocument xd, DataSet ds) inline package
Definition at line 23 of file DataSetMapper.cs.
    {
        if (IsMapped())
        {
            _tableSchemaMap = new Hashtable();
            _columnSchemaMap = new Hashtable();
        }
        _doc = xd;
        _dataSet = ds;
        foreach (DataTable table in _dataSet.Tables)
        {
            AddTableSchema(table);
            foreach (DataColumn column in table.Columns)
            {
                if (!IsNotMapped(column))
                {
                    AddColumnSchema(column);
                }
            }
        }
    }
References System.Xml.DataSetMapper._columnSchemaMap, System.Xml.DataSetMapper._dataSet, System.Xml.DataSetMapper._doc, System.Xml.DataSetMapper._tableSchemaMap, System.Xml.DataSetMapper.AddColumnSchema(), System.Xml.DataSetMapper.AddTableSchema(), System.Data.DataTable.Columns, System.Xml.Dictionary, System.Xml.DataSetMapper.IsMapped(), System.Xml.DataSetMapper.IsNotMapped(), and System.Data.DataSet.Tables.
Referenced by System.Xml.XmlDataDocument.Bind(), System.Xml.XmlDataDocument.BindForLoad(), and System.Xml.XmlDataDocument.EnsurePopulatedMode().