Terraria: Terraria.GameContent.ChromaHotkeyPainter.PaintKey.SetClear
SetClear()
void Terraria.GameContent.ChromaHotkeyPainter.PaintKey.SetClear () inline
Definition at line 117 of file ChromaHotkeyPainter.cs.
        {
            foreach (RgbKey rgbKey in _rgbKeys)
            {
                rgbKey.Clear();
            }
        }
References Terraria.GameContent.ChromaHotkeyPainter.PaintKey._rgbKeys, and ReLogic.Peripherals.RGB.RgbKey.Clear().
Referenced by Terraria.GameContent.ChromaHotkeyPainter.Step_Grapple(), Terraria.GameContent.ChromaHotkeyPainter.Step_Jump(), Terraria.GameContent.ChromaHotkeyPainter.Step_Mount(), Terraria.GameContent.ChromaHotkeyPainter.Step_QuickHeal(), Terraria.GameContent.ChromaHotkeyPainter.Step_QuickMana(), Terraria.GameContent.ChromaHotkeyPainter.Step_SmartKeys(), and Terraria.GameContent.ChromaHotkeyPainter.Step_Throw().