Terraria: System.HexConverter.EncodeToUtf16_Ssse3
EncodeToUtf16_Ssse3()
static void System.HexConverter.EncodeToUtf16_Ssse3 (ReadOnlySpan< byte > bytes, Span< char > chars, Casing casing) inline static private
Definition at line 65 of file HexConverter.cs.
    {
        nint num = 0;
        Vector128<byte> mask = Vector128.Create(byte.MaxValue, byte.MaxValue, 0, byte.MaxValue, byte.MaxValue, byte.MaxValue, 1, byte.MaxValue, byte.MaxValue, byte.MaxValue, 2, byte.MaxValue, byte.MaxValue, byte.MaxValue, 3, byte.MaxValue);
        Vector128<byte> value = ((casing == Casing.Upper) ? Vector128.Create((byte)48, (byte)49, (byte)50, (byte)51, (byte)52, (byte)53, (byte)54, (byte)55, (byte)56, (byte)57, (byte)65, (byte)66, (byte)67, (byte)68, (byte)69, (byte)70) : Vector128.Create((byte)48, (byte)49, (byte)50, (byte)51, (byte)52, (byte)53, (byte)54, (byte)55, (byte)56, (byte)57, (byte)97, (byte)98, (byte)99, (byte)100, (byte)101, (byte)102));
        do
        {
            uint value2 = Unsafe.ReadUnaligned<uint>(ref Unsafe.Add(ref MemoryMarshal.GetReference(bytes), num));
            Vector128<byte> vector = Ssse3.Shuffle(Vector128.CreateScalarUnsafe(value2).AsByte(), mask);
            Vector128<byte> right = Sse2.ShiftRightLogical(Sse2.ShiftRightLogical128BitLane(vector, 2).AsInt32(), 4).AsByte();
            Vector128<byte> mask2 = Sse2.And(Sse2.Or(vector, right), Vector128.Create((byte)15));
            Vector128<byte> left = Ssse3.Shuffle(value, mask2);
            left = Sse2.And(left, Vector128.Create((ushort)255).AsByte());
            Unsafe.WriteUnaligned(ref Unsafe.As<char, byte>(ref Unsafe.Add(ref MemoryMarshal.GetReference(chars), num * 2)), left);
            num += 4;
        }
        while (num < bytes.Length - 3);
        for (; num < bytes.Length; num++)
        {
            ToCharsBuffer(Unsafe.Add(ref MemoryMarshal.GetReference(bytes), num), chars, (int)num * 2, casing);
        }
    }
References System.Runtime.Intrinsics.X86.Sse2.And(), System.bytes, System.chars, System.Runtime.Intrinsics.Vector128< T >.Create(), System.Runtime.Intrinsics.Vector128< T >.CreateScalarUnsafe(), System.Runtime.Intrinsics.X86.Sse2.Or(), System.Runtime.Intrinsics.X86.Sse2.ShiftRightLogical(), System.Runtime.Intrinsics.X86.Sse2.ShiftRightLogical128BitLane(), System.Runtime.Intrinsics.X86.Ssse3.Shuffle(), System.HexConverter.ToCharsBuffer(), and System.value.
Referenced by System.HexConverter.EncodeToUtf16().