Terraria: DrippingShader.ProcessHighDetail
ProcessHighDetail()
void DrippingShader.ProcessHighDetail (RgbDevice device, Fragment fragment, EffectDetailLevel quality, float time) inline private
     {
         for (int i = 0; i < fragment.Count; i++)
         {
             fragment.GetGridPositionOfIndex(i);
             Vector2 canvasPositionOfIndex = fragment.GetCanvasPositionOfIndex(i);
             float staticNoise = NoiseHelper.GetStaticNoise(canvasPositionOfIndex * new Vector2(0.7f * _viscosity, 0.075f) + new Vector2(0f, time * -0.1f * _viscosity));
             staticNoise = Math.Max(0f, 1f - (canvasPositionOfIndex.Y * 4.5f + 0.5f) * staticNoise);
             Vector4 baseColor = _baseColor;
             baseColor = Vector4.Lerp(baseColor, _liquidColor, staticNoise);
             fragment.SetColor(i, baseColor);
         }
     }
References _baseColor, _liquidColor, _viscosity, Fragment.Count, Fragment.GetCanvasPositionOfIndex(), Fragment.GetGridPositionOfIndex(), NoiseHelper.GetStaticNoise(), and Fragment.SetColor().