Terraria: WeGameP2PReader.ReadTick
ReadTick()
void WeGameP2PReader.ReadTick () inline
     {
         //IL_0072: Unknown result type (might be due to invalid IL or missing references)
         //IL_0079: Expected O, but got Unknown
         //IL_00a1: Unknown result type (might be due to invalid IL or missing references)
         //IL_00a7: Invalid comparison between Unknown and I4
         if (!IsValid())
         {
             return;
         }
         lock (_pendingReadBuffers)
         {
             while (_deletionQueue.Count > 0)
             {
                 _pendingReadBuffers.Remove(_deletionQueue.Dequeue());
             }
             uint size;
             while (IsPacketAvailable(out size))
             {
                 byte[] array = ((_bufferPool.Count != 0) ? _bufferPool.Dequeue() : new byte[Math.Max(size, 4096u)]);
                 RailID val = new RailID();
                 bool flag;
                 lock (RailLock)
                 {
                     flag = (int)rail_api.RailFactory().RailNetworkHelper().ReadData(GetLocalPeer(), val, array, size) == 0;
                 }
                 if (!flag)
                 {
                     continue;
                 }
                 if (_readEvent == null || _readEvent(array, (int)size, val))
                 {
                     if (!_pendingReadBuffers.ContainsKey(val))
                     {
                         _pendingReadBuffers[val] = new Queue<ReadResult>();
                     }
                     _pendingReadBuffers[val].Enqueue(new ReadResult(array, size));
                 }
                 else
                 {
                     _bufferPool.Enqueue(array);
                 }
             }
         }
     }
References _bufferPool, _deletionQueue, _pendingReadBuffers, _readEvent, GetLocalPeer(), IsPacketAvailable(), IsValid(), and RailLock.