Terraria: System.Runtime.Serialization.XPathQueryGenerator.ExportContext.SetNamespace
SetNamespace()
string System.Runtime.Serialization.XPathQueryGenerator.ExportContext.SetNamespace (string ns) inline
Definition at line 42 of file XPathQueryGenerator.cs.
        {
            string text = _namespaces.LookupPrefix(ns);
            if (text == null || text.Length == 0)
            {
                text = "xg" + _nextPrefix++.ToString(NumberFormatInfo.InvariantInfo);
                Namespaces.AddNamespace(text, ns);
            }
            return text;
        }
References System.Runtime.Serialization.XPathQueryGenerator.ExportContext._namespaces, System.Runtime.Serialization.XPathQueryGenerator.ExportContext._nextPrefix, System.Xml.XmlNamespaceManager.AddNamespace(), System.Globalization.NumberFormatInfo.InvariantInfo, System.Xml.XmlNamespaceManager.LookupPrefix(), System.Runtime.Serialization.XPathQueryGenerator.ExportContext.Namespaces, and System.text.
Referenced by System.Runtime.Serialization.XPathQueryGenerator.ExportContext.ExportContext(), and System.Runtime.Serialization.XPathQueryGenerator.ProcessClassDataContract().