Terraria: Terraria.GameContent.UI.Elements.UIWorkshopPublishWorldListItem.UIWorkshopPublishWorldListItem
UIWorkshopPublishWorldListItem()
Terraria.GameContent.UI.Elements.UIWorkshopPublishWorldListItem.UIWorkshopPublishWorldListItem (UIState ownerState, WorldFileData data, int orderInList) inline
Definition at line 25 of file UIWorkshopPublishWorldListItem.cs.
    {
        _ownerState = ownerState;
        _orderInList = orderInList;
        _data = data;
        LoadTextures();
        InitializeAppearance();
        _worldIcon = GetIconElement();
        _worldIcon.Left.Set(4f, 0f);
        _worldIcon.VAlign = 0.5f;
        _worldIcon.OnLeftDoubleClick += PublishButtonClick_ImportWorldToLocalFiles;
        Append(_worldIcon);
        _ = 4f;
        _publishButton = new UIIconTextButton(Language.GetText("Workshop.Publish"), Color.White, "Images/UI/Workshop/Publish");
        _publishButton.HAlign = 1f;
        _publishButton.VAlign = 1f;
        _publishButton.OnLeftClick += PublishButtonClick_ImportWorldToLocalFiles;
        base.OnLeftDoubleClick += PublishButtonClick_ImportWorldToLocalFiles;
        Append(_publishButton);
        _publishButton.SetSnapPoint("Publish", orderInList);
    }
References Terraria.GameContent.UI.Elements.AWorldListItem._data, Terraria.GameContent.UI.Elements.UIWorkshopPublishWorldListItem._orderInList, Terraria.GameContent.UI.Elements.UIWorkshopPublishWorldListItem._ownerState, Terraria.GameContent.UI.Elements.UIWorkshopPublishWorldListItem._publishButton, Terraria.GameContent.UI.Elements.UIWorkshopPublishWorldListItem._worldIcon, Terraria.UI.UIElement.Append(), Terraria.GameContent.UI.Elements.AWorldListItem.GetIconElement(), Terraria.Localization.Language.GetText(), Terraria.GameContent.UI.Elements.UIWorkshopPublishWorldListItem.InitializeAppearance(), Terraria.UI.UIElement.Left, Terraria.GameContent.UI.Elements.UIWorkshopPublishWorldListItem.LoadTextures(), Terraria.GameContent.UI.Elements.UIWorkshopPublishWorldListItem.PublishButtonClick_ImportWorldToLocalFiles(), Terraria.UI.StyleDimension.Set(), and Terraria.UI.UIElement.SetSnapPoint().