Terraria: Terraria.GameContent.UI.Elements.UIWorkshopPublishWorldListItem.DrawSelf
DrawSelf()
override void Terraria.GameContent.UI.Elements.UIWorkshopPublishWorldListItem.DrawSelf (SpriteBatch spriteBatch) inline protected virtual
Reimplemented from Terraria.GameContent.UI.Elements.UIPanel.
Definition at line 107 of file UIWorkshopPublishWorldListItem.cs.
    {
        base.DrawSelf(spriteBatch);
        CalculatedStyle innerDimensions = GetInnerDimensions();
        CalculatedStyle dimensions = _worldIcon.GetDimensions();
        float num = dimensions.X + dimensions.Width;
        Color color = (_data.IsValid ? Color.White : Color.Gray);
        string worldName = _data.GetWorldName(allowCropping: true);
        Utils.DrawBorderString(spriteBatch, worldName, new Vector2(num + 6f, innerDimensions.Y + 3f), color);
        float num2 = (innerDimensions.Width - 22f - dimensions.Width - _publishButton.GetDimensions().Width) / 2f;
        float height = _publishButton.GetDimensions().Height;
        Vector2 vector = new Vector2(num + 6f, innerDimensions.Y + innerDimensions.Height - height);
        float num3 = num2;
        DrawPanel(spriteBatch, vector, num3, height);
        string expertText = "";
        Color gameModeColor = Color.White;
        GetDifficulty(out expertText, out gameModeColor);
        Vector2 vector2 = FontAssets.MouseText.Value.MeasureString(expertText);
        float x = vector2.X;
        float y = vector2.Y;
        float x2 = num3 * 0.5f - x * 0.5f;
        float num4 = height * 0.5f - y * 0.5f;
        Utils.DrawBorderString(spriteBatch, expertText, vector + new Vector2(x2, num4 + 3f), gameModeColor);
        vector.X += num3 + 5f;
        float num5 = num2;
        if (!GameCulture.FromCultureName(GameCulture.CultureName.English).IsActive)
        {
            num5 += 40f;
        }
        DrawPanel(spriteBatch, vector, num5, height);
        string textValue = Language.GetTextValue("UI.WorldSizeFormat", _data.WorldSizeName);
        Vector2 vector3 = FontAssets.MouseText.Value.MeasureString(textValue);
        float x3 = vector3.X;
        float y2 = vector3.Y;
        float x4 = num5 * 0.5f - x3 * 0.5f;
        float num6 = height * 0.5f - y2 * 0.5f;
        Utils.DrawBorderString(spriteBatch, textValue, vector + new Vector2(x4, num6 + 3f), Color.White);
        vector.X += num5 + 5f;
    }
References Terraria.GameContent.UI.Elements.AWorldListItem._data, Terraria.GameContent.UI.Elements.UIWorkshopPublishWorldListItem._publishButton, Terraria.GameContent.UI.Elements.UIWorkshopPublishWorldListItem._worldIcon, Terraria.Utils.DrawBorderString(), Terraria.GameContent.UI.Elements.UIWorkshopPublishWorldListItem.DrawPanel(), Terraria.Localization.GameCulture.FromCultureName(), Terraria.GameContent.UI.Elements.AWorldListItem.GetDifficulty(), Terraria.UI.UIElement.GetDimensions(), Terraria.UI.UIElement.GetInnerDimensions(), Terraria.Localization.Language.GetTextValue(), Terraria.IO.WorldFileData.GetWorldName(), Terraria.UI.CalculatedStyle.Height, Terraria.GameContent.FontAssets.MouseText, ReLogic.Content.Asset< T >.Value, Terraria.UI.CalculatedStyle.Width, and Terraria.IO.WorldFileData.WorldSizeName.