Terraria: System.IO.Compression.Zip64EndOfCentralDirectoryRecord.TryReadBlock
TryReadBlock()
static bool System.IO.Compression.Zip64EndOfCentralDirectoryRecord.TryReadBlock (BinaryReader reader, out Zip64EndOfCentralDirectoryRecord zip64EOCDRecord) inline static
Definition at line 23 of file Zip64EndOfCentralDirectoryRecord.cs.
    {
        zip64EOCDRecord = default(Zip64EndOfCentralDirectoryRecord);
        if (reader.ReadUInt32() != 101075792)
        {
            return false;
        }
        zip64EOCDRecord.SizeOfThisRecord = reader.ReadUInt64();
        zip64EOCDRecord.VersionMadeBy = reader.ReadUInt16();
        zip64EOCDRecord.VersionNeededToExtract = reader.ReadUInt16();
        zip64EOCDRecord.NumberOfThisDisk = reader.ReadUInt32();
        zip64EOCDRecord.NumberOfDiskWithStartOfCD = reader.ReadUInt32();
        zip64EOCDRecord.NumberOfEntriesOnThisDisk = reader.ReadUInt64();
        zip64EOCDRecord.NumberOfEntriesTotal = reader.ReadUInt64();
        zip64EOCDRecord.SizeOfCentralDirectory = reader.ReadUInt64();
        zip64EOCDRecord.OffsetOfCentralDirectory = reader.ReadUInt64();
        return true;
    }
References System.IO.BinaryReader.ReadUInt16(), System.IO.BinaryReader.ReadUInt32(), and System.IO.BinaryReader.ReadUInt64().
Referenced by System.IO.Compression.ZipArchive.TryReadZip64EndOfCentralDirectory().