Terraria: System.IO.BufferedStream.BufferedStream
BufferedStream() [2/2]
System.IO.BufferedStream.BufferedStream (Stream stream, int bufferSize) inline
Definition at line 98 of file BufferedStream.cs.
    {
        if (stream == null)
        {
            ThrowHelper.ThrowArgumentNullException(ExceptionArgument.stream);
        }
        if (bufferSize <= 0)
        {
            throw new ArgumentOutOfRangeException("bufferSize", SR.Format(SR.ArgumentOutOfRange_MustBePositive, "bufferSize"));
        }
        _stream = stream;
        _bufferSize = bufferSize;
        if (!_stream.CanRead && !_stream.CanWrite)
        {
            ThrowHelper.ThrowObjectDisposedException_StreamClosed(null);
        }
    }
References System.IO.BufferedStream._bufferSize, System.IO.BufferedStream._stream, System.SR.ArgumentOutOfRange_MustBePositive, System.IO.Stream.CanRead, System.IO.Stream.CanWrite, System.SR.Format(), System.stream, System.ThrowHelper.ThrowArgumentNullException(), and System.ThrowHelper.ThrowObjectDisposedException_StreamClosed().