Terraria: System.IO.BufferedStream.WriteToUnderlyingStreamAsync
WriteToUnderlyingStreamAsync()
async ValueTask System.IO.BufferedStream.WriteToUnderlyingStreamAsync (ReadOnlyMemory< byte > buffer, CancellationToken cancellationToken, Task semaphoreLockTask) inline private
Definition at line 724 of file BufferedStream.cs.
    {
        await semaphoreLockTask.ConfigureAwait(continueOnCapturedContext: false);
        try
        {
            if (_writePos == 0)
            {
                ClearReadBufferBeforeWrite();
            }
            int num;
            checked
            {
                num = _writePos + buffer.Length;
                if (num + buffer.Length < _bufferSize + _bufferSize)
                {
                    buffer = buffer.Slice(WriteToBuffer(buffer.Span));
                    if (_writePos >= _bufferSize)
                    {
                        await _stream.WriteAsync(new ReadOnlyMemory<byte>(_buffer, 0, _writePos), cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
                        _writePos = 0;
                        WriteToBuffer(buffer.Span);
                    }
                    return;
                }
            }
            if (_writePos > 0)
            {
                if (num <= _bufferSize + _bufferSize && num <= 81920)
                {
                    EnsureShadowBufferAllocated();
                    buffer.Span.CopyTo(new Span<byte>(_buffer, _writePos, buffer.Length));
                    await _stream.WriteAsync(new ReadOnlyMemory<byte>(_buffer, 0, num), cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
                    _writePos = 0;
                    return;
                }
                await _stream.WriteAsync(new ReadOnlyMemory<byte>(_buffer, 0, _writePos), cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
                _writePos = 0;
            }
            await _stream.WriteAsync(buffer, cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
        }
        finally
        {
            _asyncActiveSemaphore.Release();
        }
    }
References System.IO.Stream._asyncActiveSemaphore, System.IO.BufferedStream._buffer, System.IO.BufferedStream._bufferSize, System.IO.BufferedStream._stream, System.IO.BufferedStream._writePos, System.buffer, System.cancellationToken, System.IO.BufferedStream.ClearReadBufferBeforeWrite(), System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.IO.BufferedStream.EnsureShadowBufferAllocated(), System.Threading.SemaphoreSlim.Release(), System.IO.Stream.WriteAsync(), and System.IO.BufferedStream.WriteToBuffer().
Referenced by System.IO.BufferedStream.WriteAsync().