Terraria: System.IO.BufferedStream.Read
Read() [2/2]
override int System.IO.BufferedStream.Read (Span< byte > destination) inline virtual
Reimplemented from System.IO.Stream.
Definition at line 396 of file BufferedStream.cs.
    {
        EnsureNotClosed();
        EnsureCanRead();
        int num = ReadFromBuffer(destination);
        if (num == destination.Length)
        {
            return num;
        }
        if (num > 0)
        {
            destination = destination.Slice(num);
        }
        _readPos = (_readLen = 0);
        if (_writePos > 0)
        {
            FlushWrite();
        }
        if (destination.Length >= _bufferSize)
        {
            return _stream.Read(destination) + num;
        }
        EnsureBufferAllocated();
        _readLen = _stream.Read(_buffer, 0, _bufferSize);
        return ReadFromBuffer(destination) + num;
    }
References System.IO.BufferedStream._buffer, System.IO.BufferedStream._bufferSize, System.IO.BufferedStream._readLen, System.IO.BufferedStream._readPos, System.IO.BufferedStream._stream, System.IO.BufferedStream._writePos, System.destination, System.IO.BufferedStream.EnsureBufferAllocated(), System.IO.BufferedStream.EnsureCanRead(), System.IO.BufferedStream.EnsureNotClosed(), System.IO.BufferedStream.FlushWrite(), System.IO.Stream.Read(), and System.IO.BufferedStream.ReadFromBuffer().