Terraria: System.IO.BufferedStream.ReadFromBuffer
ReadFromBuffer() [1/3]
int System.IO.BufferedStream.ReadFromBuffer (byte[] buffer, int offset, int count) inline private
Definition at line 324 of file BufferedStream.cs.
    {
        int num = _readLen - _readPos;
        if (num == 0)
        {
            return 0;
        }
        if (num > count)
        {
            num = count;
        }
        Buffer.BlockCopy(_buffer, _readPos, buffer, offset, num);
        _readPos += num;
        return num;
    }
References System.IO.BufferedStream._buffer, System.IO.BufferedStream._readLen, System.IO.BufferedStream._readPos, System.Buffer.BlockCopy(), System.buffer, System.count, and System.offset.
Referenced by System.IO.BufferedStream.Read(), System.IO.BufferedStream.Read(), System.IO.BufferedStream.ReadAsync(), System.IO.BufferedStream.ReadAsync(), System.IO.BufferedStream.ReadFromBuffer(), and System.IO.BufferedStream.ReadFromUnderlyingStreamAsync().