Terraria: nativefiledialog.Utf8EncodeNullable
Utf8EncodeNullable()
static unsafe byte* nativefiledialog.Utf8EncodeNullable (string str) inline static private
     {
         if (str == null)
         {
             return null;
         }
         int num = Utf8Size(str);
         byte* ptr = (byte*)(void*)Marshal.AllocHGlobal(num);
         fixed (char* chars = str)
         {
             Encoding.UTF8.GetBytes(chars, (str != null) ? (str.Length + 1) : 0, ptr, num);
         }
         return ptr;
     }
References Utf8Size().
Referenced by NFD_OpenDialog(), NFD_OpenDialogMultiple(), NFD_PickFolder(), and NFD_SaveDialog().