Terraria: System.Collections.Immutable.ImmutableSortedSet.Intersect
Intersect() [1/2]
ImmutableSortedSet< T > System.Collections.Immutable.ImmutableSortedSet< T >.Intersect (IEnumerable< T > other) inline
Implements System.Collections.Immutable.IImmutableSet< T >.
Definition at line 1045 of file ImmutableSortedSet.cs.
    {
        Requires.NotNull(other, "other");
        ImmutableSortedSet<T> immutableSortedSet = Clear();
        foreach (T item in other.GetEnumerableDisposable<T, Enumerator>())
        {
            if (Contains(item))
            {
                immutableSortedSet = immutableSortedSet.Add(item);
            }
        }
        return immutableSortedSet;
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Collections.Immutable.ImmutableSortedSet< T >.Clear(), System.Collections.Immutable.ImmutableSortedSet< T >.Contains(), System.item, and System.other.
Referenced by System.Collections.Immutable.ImmutableSortedSet< T >.Intersect().