Terraria: System.Collections.Immutable.ImmutableSortedSet.Union
Union() [1/2]
ImmutableSortedSet< T > System.Collections.Immutable.ImmutableSortedSet< T >.Union (IEnumerable< T > other) inline
Implements System.Collections.Immutable.IImmutableSet< T >.
Definition at line 1096 of file ImmutableSortedSet.cs.
    {
        Requires.NotNull(other, "other");
        if (TryCastToImmutableSortedSet(other, out var other2) && other2.KeyComparer == KeyComparer)
        {
            if (other2.IsEmpty)
            {
                return this;
            }
            if (IsEmpty)
            {
                return other2;
            }
            if (other2.Count > Count)
            {
                return other2.Union(this);
            }
        }
        if (IsEmpty || (other.TryGetCount(out var count) && (float)(Count + count) * 0.15f > (float)Count))
        {
            return LeafToRootRefill(other);
        }
        return UnionIncremental(other);
    }
References System.Collections.Immutable.ImmutableSortedSet< T >.Count, System.count, System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Collections.Immutable.ImmutableSortedSet< T >.IsEmpty, System.Collections.Immutable.ImmutableSortedSet< T >.KeyComparer, System.Collections.Immutable.ImmutableSortedSet< T >.LeafToRootRefill(), System.other, System.Collections.Immutable.ImmutableSortedSet< T >.TryCastToImmutableSortedSet(), and System.Collections.Immutable.ImmutableSortedSet< T >.UnionIncremental().
Referenced by System.Collections.Immutable.ImmutableSortedSet< T >.Union().