Terraria: System.Collections.Immutable.ImmutableSortedSet.Wrap
Wrap() [2/2]
static ImmutableSortedSet< T > System.Collections.Immutable.ImmutableSortedSet< T >.Wrap (Node root, IComparer< T > comparer) inline static private
Definition at line 1438 of file ImmutableSortedSet.cs.
    {
        if (!root.IsEmpty)
        {
            return new ImmutableSortedSet<T>(root, comparer);
        }
        return Empty.WithComparer(comparer);
    }
References System.comparer, and System.Collections.Immutable.ImmutableSortedSet< T >.Node.IsEmpty.
Referenced by System.Collections.Immutable.ImmutableSortedSet< T >.Add(), System.Collections.Immutable.ImmutableSortedSet< T >.Except(), System.Collections.Immutable.ImmutableSortedSet< T >.LeafToRootRefill(), System.Collections.Immutable.ImmutableSortedSet< T >.Remove(), and System.Collections.Immutable.ImmutableSortedSet< T >.UnionIncremental().