Terraria: System.Collections.Immutable.ImmutableSortedSet.LeafToRootRefill
LeafToRootRefill()
ImmutableSortedSet< T > System.Collections.Immutable.ImmutableSortedSet< T >.LeafToRootRefill (IEnumerable< T > addedItems) inline private
Definition at line 1471 of file ImmutableSortedSet.cs.
    {
        Requires.NotNull(addedItems, "addedItems");
        List<T> list;
        if (IsEmpty)
        {
            if (addedItems.TryGetCount(out var count) && count == 0)
            {
                return this;
            }
            list = new List<T>(addedItems);
            if (list.Count == 0)
            {
                return this;
            }
        }
        else
        {
            list = new List<T>(this);
            list.AddRange(addedItems);
        }
        IComparer<T> keyComparer = KeyComparer;
        list.Sort(keyComparer);
        int num = 1;
        for (int i = 1; i < list.Count; i++)
        {
            if (keyComparer.Compare(list[i], list[i - 1]) != 0)
            {
                list[num++] = list[i];
            }
        }
        list.RemoveRange(num, list.Count - num);
        Node root = Node.NodeTreeFromList(list.AsOrderedCollection(), 0, list.Count);
        return Wrap(root);
    }
References System.count, System.Collections.Immutable.ImmutableSortedSet< T >.IsEmpty, System.Collections.Immutable.ImmutableSortedSet< T >.KeyComparer, System.list, System.Collections.Immutable.ImmutableSortedSet< T >.Node.NodeTreeFromList(), and System.Collections.Immutable.ImmutableSortedSet< T >.Wrap().
Referenced by System.Collections.Immutable.ImmutableSortedSet< T >.Union().