Terraria: System.CodeDom.Compiler.IndentedTextWriter.WriteAsync
WriteAsync() [4/6]
override async Task System.CodeDom.Compiler.IndentedTextWriter.WriteAsync (ReadOnlyMemory< char > buffer, CancellationToken cancellationToken = default(CancellationToken)) inline virtual
Reimplemented from System.IO.TextWriter.
Definition at line 207 of file IndentedTextWriter.cs.
    {
        await OutputTabsAsync().ConfigureAwait(continueOnCapturedContext: false);
        await _writer.WriteAsync(buffer, cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
    }
References System.CodeDom.Compiler.IndentedTextWriter._writer, System.buffer, System.cancellationToken, System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.CodeDom.Compiler.IndentedTextWriter.OutputTabsAsync(), and System.IO.TextWriter.WriteAsync().