Terraria: System.CodeDom.Compiler.IndentedTextWriter.OutputTabsAsync
OutputTabsAsync()
virtual async Task System.CodeDom.Compiler.IndentedTextWriter.OutputTabsAsync () inline protected virtual
Definition at line 99 of file IndentedTextWriter.cs.
    {
        if (_tabsPending)
        {
            for (int i = 0; i < _indentLevel; i++)
            {
                await _writer.WriteAsync(_tabString).ConfigureAwait(continueOnCapturedContext: false);
            }
            _tabsPending = false;
        }
    }
References System.CodeDom.Compiler.IndentedTextWriter._indentLevel, System.CodeDom.Compiler.IndentedTextWriter._tabsPending, System.CodeDom.Compiler.IndentedTextWriter._tabString, System.CodeDom.Compiler.IndentedTextWriter._writer, System.Threading.Tasks.Task< TResult >.ConfigureAwait(), and System.IO.TextWriter.WriteAsync().
Referenced by System.CodeDom.Compiler.IndentedTextWriter.WriteAsync(), System.CodeDom.Compiler.IndentedTextWriter.WriteAsync(), System.CodeDom.Compiler.IndentedTextWriter.WriteAsync(), System.CodeDom.Compiler.IndentedTextWriter.WriteAsync(), System.CodeDom.Compiler.IndentedTextWriter.WriteAsync(), System.CodeDom.Compiler.IndentedTextWriter.WriteLineAsync(), System.CodeDom.Compiler.IndentedTextWriter.WriteLineAsync(), System.CodeDom.Compiler.IndentedTextWriter.WriteLineAsync(), System.CodeDom.Compiler.IndentedTextWriter.WriteLineAsync(), System.CodeDom.Compiler.IndentedTextWriter.WriteLineAsync(), and System.CodeDom.Compiler.IndentedTextWriter.WriteLineAsync().