Terraria: System.CodeDom.Compiler.IndentedTextWriter.OutputTabs
OutputTabs()
virtual void System.CodeDom.Compiler.IndentedTextWriter.OutputTabs () inline protected virtual
Definition at line 87 of file IndentedTextWriter.cs.
    {
        if (_tabsPending)
        {
            for (int i = 0; i < _indentLevel; i++)
            {
                _writer.Write(_tabString);
            }
            _tabsPending = false;
        }
    }
References System.CodeDom.Compiler.IndentedTextWriter._indentLevel, System.CodeDom.Compiler.IndentedTextWriter._tabsPending, System.CodeDom.Compiler.IndentedTextWriter._tabString, System.CodeDom.Compiler.IndentedTextWriter._writer, and System.IO.TextWriter.Write().
Referenced by System.CodeDom.Compiler.IndentedTextWriter.Write(), System.CodeDom.Compiler.IndentedTextWriter.Write(), System.CodeDom.Compiler.IndentedTextWriter.Write(), System.CodeDom.Compiler.IndentedTextWriter.Write(), System.CodeDom.Compiler.IndentedTextWriter.Write(), System.CodeDom.Compiler.IndentedTextWriter.Write(), System.CodeDom.Compiler.IndentedTextWriter.Write(), System.CodeDom.Compiler.IndentedTextWriter.Write(), System.CodeDom.Compiler.IndentedTextWriter.Write(), System.CodeDom.Compiler.IndentedTextWriter.Write(), System.CodeDom.Compiler.IndentedTextWriter.Write(), System.CodeDom.Compiler.IndentedTextWriter.Write(), System.CodeDom.Compiler.IndentedTextWriter.Write(), System.CodeDom.Compiler.IndentedTextWriter.WriteLine(), System.CodeDom.Compiler.IndentedTextWriter.WriteLine(), System.CodeDom.Compiler.IndentedTextWriter.WriteLine(), System.CodeDom.Compiler.IndentedTextWriter.WriteLine(), System.CodeDom.Compiler.IndentedTextWriter.WriteLine(), System.CodeDom.Compiler.IndentedTextWriter.WriteLine(), System.CodeDom.Compiler.IndentedTextWriter.WriteLine(), System.CodeDom.Compiler.IndentedTextWriter.WriteLine(), System.CodeDom.Compiler.IndentedTextWriter.WriteLine(), System.CodeDom.Compiler.IndentedTextWriter.WriteLine(), System.CodeDom.Compiler.IndentedTextWriter.WriteLine(), System.CodeDom.Compiler.IndentedTextWriter.WriteLine(), System.CodeDom.Compiler.IndentedTextWriter.WriteLine(), System.CodeDom.Compiler.IndentedTextWriter.WriteLine(), and System.CodeDom.Compiler.IndentedTextWriter.WriteLine().