Terraria: Terraria.GameContent.Biomes.CaveHouseBiome.Place
Place()
override bool Terraria.GameContent.Biomes.CaveHouseBiome.Place (Point origin, StructureMap structures) inline
Definition at line 34 of file CaveHouseBiome.cs.
    {
        if (!WorldGen.InWorld(origin.X, origin.Y, 10))
        {
            return false;
        }
        int num = 25;
        for (int i = origin.X - num; i <= origin.X + num; i++)
        {
            for (int j = origin.Y - num; j <= origin.Y + num; j++)
            {
                if (Main.tile[i, j].wire())
                {
                    return false;
                }
                if (TileID.Sets.BasicChest[Main.tile[i, j].type])
                {
                    return false;
                }
            }
        }
        HouseBuilder houseBuilder = HouseUtils.CreateBuilder(origin, structures);
        if (!houseBuilder.IsValid)
        {
            return false;
        }
        ApplyConfigurationToBuilder(houseBuilder);
        houseBuilder.Place(_builderContext, structures);
        return true;
    }
References Terraria.GameContent.Biomes.CaveHouseBiome._builderContext, Terraria.GameContent.Biomes.CaveHouseBiome.ApplyConfigurationToBuilder(), Terraria.ID.TileID.Sets.BasicChest, Terraria.GameContent.Biomes.CaveHouse.HouseUtils.CreateBuilder(), Terraria.WorldGen.InWorld(), Terraria.GameContent.Biomes.CaveHouse.HouseBuilder.IsValid, Terraria.GameContent.Biomes.CaveHouse.HouseBuilder.Place(), Terraria.Main.tile, Microsoft.Xna.Framework.Point.X, and Microsoft.Xna.Framework.Point.Y.