Terraria: System.Security.AccessControl.Privilege.TlsContents.TlsContents
TlsContents()
System.Security.AccessControl.Privilege.TlsContents.TlsContents () inline
Definition at line 32 of file Privilege.cs.
        {
            int num = 0;
            int num2 = 0;
            bool flag = true;
            if (processHandle.IsInvalid)
            {
                lock (syncRoot)
                {
                    if (processHandle.IsInvalid)
                    {
                        if (!global::Interop.Advapi32.OpenProcessToken(global::Interop.Kernel32.GetCurrentProcess(), TokenAccessLevels.Duplicate, out var TokenHandle))
{
                            num2 = Marshal.GetLastWin32Error();
                            flag = false;
                        }
                        processHandle = TokenHandle;
                    }
                }
            }
            try
            {
                SafeTokenHandle safeTokenHandle = threadHandle;
                num = System.Security.Principal.Win32.OpenThreadToken(TokenAccessLevels.Query | TokenAccessLevels.AdjustPrivileges, System.Security.Principal.WinSecurityContext.Process, out threadHandle);
                num &= 0x7FF8FFFF;
                if (num != 0)
                {
                    if (flag)
                    {
                        threadHandle = safeTokenHandle;
                        if (num != 1008)
{
                            flag = false;
                        }
                        if (flag)
{
                            num = 0;
                            if (!global::Interop.Advapi32.DuplicateTokenEx(processHandle, TokenAccessLevels.Impersonate | TokenAccessLevels.Query | TokenAccessLevels.AdjustPrivileges, IntPtr.Zero, global::Interop.Advapi32.SECURITY_IMPERSONATION_LEVEL.SecurityImpersonation, System.Security.Principal.TokenType.TokenImpersonation, ref threadHandle))
{
                                num = Marshal.GetLastWin32Error();
                                flag = false;
                            }
                        }
                        if (flag)
{
                            num = System.Security.Principal.Win32.SetThreadToken(threadHandle);
                            num &= 0x7FF8FFFF;
                            if (num != 0)
{
                                flag = false;
                            }
                        }
                        if (flag)
{
                            isImpersonating = true;
                        }
                    }
                    else
                    {
                        num = num2;
                    }
                }
                else
                {
                    flag = true;
                }
            }
            finally
            {
                if (!flag)
                {
                    Dispose();
                }
            }
            switch (num)
            {
            case 8:
                throw new OutOfMemoryException();
            case 5:
            case 1347:
                throw new UnauthorizedAccessException();
            default:
                throw new InvalidOperationException();
            case 0:
                break;
            }
        }
References System.Security.AccessControl.Privilege.TlsContents.Dispose(), System.Runtime.InteropServices.Marshal.GetLastWin32Error(), System.Security.AccessControl.Privilege.TlsContents.isImpersonating, System.Security.Principal.Win32.OpenThreadToken(), System.Security.AccessControl.Privilege.TlsContents.processHandle, System.Security.Principal.Win32.SetThreadToken(), System.Security.AccessControl.Privilege.TlsContents.syncRoot, System.Security.AccessControl.Privilege.TlsContents.threadHandle, and System.IntPtr.Zero.