Terraria: System.ComponentModel.TypeDescriptor.TypeDescriptionNode.DefaultTypeDescriptor.GetEvents
GetEvents() [1/3]
EventDescriptorCollection ICustomTypeDescriptor. System.ComponentModel.TypeDescriptor.TypeDescriptionNode.DefaultTypeDescriptor.GetEvents () inline
Implements System.ComponentModel.ICustomTypeDescriptor.
Definition at line 747 of file TypeDescriptor.cs.
            {
                TypeDescriptionProvider provider = _node.Provider;
                EventDescriptorCollection events;
                if (provider is ReflectTypeDescriptionProvider reflectTypeDescriptionProvider)
                {
                    events = reflectTypeDescriptionProvider.GetEvents(_objectType);
                }
                else
                {
                    ICustomTypeDescriptor typeDescriptor = provider.GetTypeDescriptor(_objectType, _instance);
                    if (typeDescriptor == null)
                    {
                        throw new InvalidOperationException(System.SR.Format(System.SR.TypeDescriptorProviderError, _node.Provider.GetType().FullName, "GetTypeDescriptor"));
                    }
                    events = typeDescriptor.GetEvents();
                    if (events == null)
                    {
                        throw new InvalidOperationException(System.SR.Format(System.SR.TypeDescriptorProviderError, _node.Provider.GetType().FullName, "GetEvents"));
                    }
                }
                return events;
            }
References System.ComponentModel.TypeDescriptor.TypeDescriptionNode.DefaultTypeDescriptor._instance, System.ComponentModel.TypeDescriptor.TypeDescriptionNode.DefaultTypeDescriptor._node, System.ComponentModel.TypeDescriptor.TypeDescriptionNode.DefaultTypeDescriptor._objectType, System.SR.Format(), System.ComponentModel.ICustomTypeDescriptor.GetEvents(), System.ComponentModel.TypeDescriptionProvider.GetTypeDescriptor(), System.ComponentModel.TypeDescriptor.TypeDescriptionNode.Provider, and System.SR.TypeDescriptorProviderError.