Terraria: System.Reflection.Metadata.Ecma335.ImplMapTableReader.GetImport
GetImport()
MethodImport System.Reflection.Metadata.Ecma335.ImplMapTableReader.GetImport (int rowId) inline package
Definition at line 45 of file ImplMapTableReader.cs.
    {
        int num = (rowId - 1) * RowSize;
        MethodImportAttributes attributes = (MethodImportAttributes)Block.PeekUInt16(num + _FlagsOffset);
        StringHandle name = StringHandle.FromOffset(Block.PeekHeapReference(num + _ImportNameOffset, _IsStringHeapRefSizeSmall));
        ModuleReferenceHandle module = ModuleReferenceHandle.FromRowId(Block.PeekReference(num + _ImportScopeOffset, _IsModuleRefTableRowRefSizeSmall));
        return new MethodImport(attributes, name, module);
    }
References System.Reflection.Metadata.Ecma335.ImplMapTableReader._FlagsOffset, System.Reflection.Metadata.Ecma335.ImplMapTableReader._ImportNameOffset, System.Reflection.Metadata.Ecma335.ImplMapTableReader._ImportScopeOffset, System.Reflection.Metadata.Ecma335.ImplMapTableReader._IsModuleRefTableRowRefSizeSmall, System.Reflection.Metadata.Ecma335.ImplMapTableReader._IsStringHeapRefSizeSmall, System.Reflection.Metadata.Ecma335.ImplMapTableReader.Block, System.Reflection.Metadata.StringHandle.FromOffset(), System.Reflection.Metadata.ModuleReferenceHandle.FromRowId(), System.Reflection.Internal.MemoryBlock.PeekHeapReference(), System.Reflection.Internal.MemoryBlock.PeekReference(), System.Reflection.Internal.MemoryBlock.PeekUInt16(), and System.Reflection.Metadata.Ecma335.ImplMapTableReader.RowSize.
Referenced by System.Reflection.Metadata.MethodDefinition.GetImport().