Terraria: System.ValueType.Equals
Equals()
override bool System.ValueType.Equals ([NotNullWhen(true)] object? obj) inline
Definition at line 12 of file ValueType.cs.
    {
        if (obj == null)
        {
            return false;
        }
        Type type = GetType();
        Type type2 = obj.GetType();
        if (type2 != type)
        {
            return false;
        }
        if (CanCompareBits(this))
        {
            return FastEqualsCheck(this, obj);
        }
        FieldInfo[] fields = type.GetFields(BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic);
        for (int i = 0; i < fields.Length; i++)
        {
            object value = fields[i].GetValue(this);
            object value2 = fields[i].GetValue(obj);
            if (value == null)
            {
                if (value2 != null)
                {
                    return false;
                }
            }
            else if (!value.Equals(value2))
            {
                return false;
            }
        }
        return true;
    }
References System.ValueType.CanCompareBits(), System.ValueType.FastEqualsCheck(), System.Type.GetType(), System.Reflection.FieldInfo.GetValue(), System.obj, System.type, and System.value.