Terraria: System.Dynamic.Utils.DelegateHelpers.CreateObjectArrayDelegateRefEmit
CreateObjectArrayDelegateRefEmit()
static Delegate System.Dynamic.Utils.DelegateHelpers.CreateObjectArrayDelegateRefEmit (Type delegateType, Func< object[], object > handler) inline static private
Definition at line 134 of file DelegateHelpers.cs.
    {
        if (!s_thunks.TryGetValue(delegateType, out var value))
        {
            MethodInfo invokeMethod = delegateType.GetInvokeMethod();
            Type returnType = invokeMethod.ReturnType;
            bool flag = returnType != typeof(void);
            ParameterInfo[] parametersCached = invokeMethod.GetParametersCached();
            value = GetCSharpThunk(returnType, flag, parametersCached);
            if (value == null)
            {
                int value2 = Interlocked.Increment(ref s_ThunksCreated);
                Type[] array = new Type[parametersCached.Length + 1];
                array[0] = typeof(Func<object[], object>);
                StringBuilder stringBuilder = new StringBuilder();
                stringBuilder.Append("Thunk");
                stringBuilder.Append(value2);
                if (flag)
                {
                    stringBuilder.Append("ret_");
                    stringBuilder.Append(returnType.Name);
                }
                for (int i = 0; i < parametersCached.Length; i++)
                {
                    stringBuilder.Append('_');
                    stringBuilder.Append(parametersCached[i].ParameterType.Name);
                    array[i + 1] = parametersCached[i].ParameterType;
                }
                DynamicMethod dynamicMethod = new DynamicMethod(stringBuilder.ToString(), returnType, array);
                value = dynamicMethod;
                ILGenerator iLGenerator = dynamicMethod.GetILGenerator();
                LocalBuilder local = iLGenerator.DeclareLocal(typeof(object[]));
                LocalBuilder local2 = iLGenerator.DeclareLocal(typeof(object));
                if (parametersCached.Length == 0)
                {
                    iLGenerator.Emit(OpCodes.Call, s_ArrayEmpty);
                }
                else
                {
                    iLGenerator.Emit(OpCodes.Ldc_I4, parametersCached.Length);
                    iLGenerator.Emit(OpCodes.Newarr, typeof(object));
                }
                iLGenerator.Emit(OpCodes.Stloc, local);
                bool flag2 = false;
                for (int j = 0; j < parametersCached.Length; j++)
                {
                    bool isByRef = parametersCached[j].ParameterType.IsByRef;
                    Type type = parametersCached[j].ParameterType;
                    if (isByRef)
                    {
                        type = type.GetElementType();
                    }
                    flag2 = flag2 || isByRef;
                    iLGenerator.Emit(OpCodes.Ldloc, local);
                    iLGenerator.Emit(OpCodes.Ldc_I4, j);
                    iLGenerator.Emit(OpCodes.Ldarg, j + 1);
                    if (isByRef)
                    {
                        iLGenerator.Emit(OpCodes.Ldobj, type);
                    }
                    Type cls = ConvertToBoxableType(type);
                    iLGenerator.Emit(OpCodes.Box, cls);
                    iLGenerator.Emit(OpCodes.Stelem_Ref);
                }
                if (flag2)
                {
                    iLGenerator.BeginExceptionBlock();
                }
                iLGenerator.Emit(OpCodes.Ldarg_0);
                iLGenerator.Emit(OpCodes.Ldloc, local);
                iLGenerator.Emit(OpCodes.Callvirt, s_FuncInvoke);
                iLGenerator.Emit(OpCodes.Stloc, local2);
                if (flag2)
                {
                    iLGenerator.BeginFinallyBlock();
                    for (int k = 0; k < parametersCached.Length; k++)
                    {
                        if (parametersCached[k].ParameterType.IsByRef)
{
                            Type elementType = parametersCached[k].ParameterType.GetElementType();
                            iLGenerator.Emit(OpCodes.Ldarg, k + 1);
                            iLGenerator.Emit(OpCodes.Ldloc, local);
                            iLGenerator.Emit(OpCodes.Ldc_I4, k);
                            iLGenerator.Emit(OpCodes.Ldelem_Ref);
                            iLGenerator.Emit(OpCodes.Unbox_Any, elementType);
                            iLGenerator.Emit(OpCodes.Stobj, elementType);
                        }
                    }
                    iLGenerator.EndExceptionBlock();
                }
                if (flag)
                {
                    iLGenerator.Emit(OpCodes.Ldloc, local2);
                    iLGenerator.Emit(OpCodes.Unbox_Any, ConvertToBoxableType(returnType));
                }
                iLGenerator.Emit(OpCodes.Ret);
            }
            s_thunks[delegateType] = value;
        }
        return value.CreateDelegate(delegateType, handler);
    }
References System.Text.StringBuilder.Append(), System.array, System.Reflection.Emit.ILGenerator.BeginExceptionBlock(), System.Reflection.Emit.ILGenerator.BeginFinallyBlock(), System.Reflection.Emit.OpCodes.Box, System.Reflection.Emit.OpCodes.Call, System.Reflection.Emit.OpCodes.Callvirt, System.Dynamic.Utils.DelegateHelpers.ConvertToBoxableType(), System.Reflection.Emit.ILGenerator.DeclareLocal(), System.elementType, System.Reflection.Emit.ILGenerator.Emit(), System.Reflection.Emit.ILGenerator.EndExceptionBlock(), System.Dynamic.Utils.DelegateHelpers.GetCSharpThunk(), System.Type.GetElementType(), System.Reflection.Emit.DynamicMethod.GetILGenerator(), System.Threading.Interlocked.Increment(), System.Type.IsByRef, System.Reflection.Emit.OpCodes.Ldarg, System.Reflection.Emit.OpCodes.Ldarg_0, System.Reflection.Emit.OpCodes.Ldc_I4, System.Reflection.Emit.OpCodes.Ldelem_Ref, System.Reflection.Emit.OpCodes.Ldloc, System.Reflection.Emit.OpCodes.Ldobj, System.Reflection.MemberInfo.Name, System.Reflection.ParameterInfo.Name, System.Reflection.Emit.OpCodes.Newarr, System.Reflection.ParameterInfo.ParameterType, System.Reflection.Emit.OpCodes.Ret, System.Reflection.MethodInfo.ReturnType, System.Dynamic.Utils.DelegateHelpers.s_ArrayEmpty, System.Dynamic.Utils.DelegateHelpers.s_FuncInvoke, System.Dynamic.Utils.DelegateHelpers.s_thunks, System.Dynamic.Utils.DelegateHelpers.s_ThunksCreated, System.Reflection.Emit.OpCodes.Stelem_Ref, System.Reflection.Emit.OpCodes.Stloc, System.Reflection.Emit.OpCodes.Stobj, System.Text.StringBuilder.ToString(), System.type, System.Reflection.Emit.OpCodes.Unbox_Any, and System.value.
Referenced by System.Dynamic.Utils.DelegateHelpers.CreateObjectArrayDelegate().