Terraria: System.Net.Http.QPack.QPackEncoder.EncodeLiteralHeaderFieldWithoutNameReferenceToArray
EncodeLiteralHeaderFieldWithoutNameReferenceToArray() [1/2]
static byte[] System.Net.Http.QPack.QPackEncoder.EncodeLiteralHeaderFieldWithoutNameReferenceToArray (string name) inline static
Definition at line 96 of file QPackEncoder.cs.
    {
        Span<byte> span = ((name.Length >= 256) ? ((Span<byte>)new byte[name.Length + 6]) : stackalloc byte[262]);
        Span<byte> buffer = span;
        int length;
        bool flag = EncodeNameString(name, buffer, out length);
        return buffer.Slice(0, length).ToArray();
    }
References System.buffer, System.Net.Http.QPack.QPackEncoder.EncodeNameString(), and System.length.
Referenced by System.Net.Http.Http3Connection.Http3Connection(), and System.Net.Http.Headers.KnownHeader.Initialize().