Terraria: System.Net.Http.QPack.QPackEncoder.EncodeValueString
EncodeValueString() [1/2]
static bool System.Net.Http.QPack.QPackEncoder.EncodeValueString (ReadOnlySpan< string > values, string separator, Encoding valueEncoding, Span< byte > buffer, out int length) inline static
Definition at line 142 of file QPackEncoder.cs.
    {
        if (values.Length == 1)
        {
            return EncodeValueString(values[0], valueEncoding, buffer, out length);
        }
        if (values.Length == 0)
        {
            return EncodeValueString(string.Empty, null, buffer, out length);
        }
        if (buffer.Length > 0)
        {
            int num;
            if (valueEncoding == null || valueEncoding == Encoding.Latin1)
            {
                num = separator.Length * (values.Length - 1);
                ReadOnlySpan<string> readOnlySpan = values;
                for (int i = 0; i < readOnlySpan.Length; i++)
                {
                    string text = readOnlySpan[i];
                    num += text.Length;
                }
            }
            else
            {
                num = valueEncoding.GetByteCount(separator) * (values.Length - 1);
                ReadOnlySpan<string> readOnlySpan2 = values;
                for (int j = 0; j < readOnlySpan2.Length; j++)
                {
                    string s = readOnlySpan2[j];
                    num += valueEncoding.GetByteCount(s);
                }
            }
            buffer[0] = 0;
            if (IntegerEncoder.Encode(num, 7, buffer, out var bytesWritten))
            {
                buffer = buffer.Slice(bytesWritten);
                if (buffer.Length >= num)
                {
                    if (valueEncoding == null)
                    {
                        string text2 = values[0];
                        EncodeValueStringPart(text2, buffer);
                        buffer = buffer.Slice(text2.Length);
                        for (int k = 1; k < values.Length; k++)
{
                            EncodeValueStringPart(separator, buffer);
                            buffer = buffer.Slice(separator.Length);
                            text2 = values[k];
                            EncodeValueStringPart(text2, buffer);
                            buffer = buffer.Slice(text2.Length);
                        }
                    }
                    else
                    {
                        int bytes = valueEncoding.GetBytes(values[0], buffer);
                        buffer = buffer.Slice(bytes);
                        for (int l = 1; l < values.Length; l++)
{
                            bytes = valueEncoding.GetBytes(separator, buffer);
                            buffer = buffer.Slice(bytes);
                            bytes = valueEncoding.GetBytes(values[l], buffer);
                            buffer = buffer.Slice(bytes);
                        }
                    }
                    length = bytesWritten + num;
                    return true;
                }
            }
        }
        length = 0;
        return false;
    }
References System.buffer, System.bytes, System.Net.Http.HPack.IntegerEncoder.Encode(), System.Net.Http.QPack.QPackEncoder.EncodeValueString(), System.Net.Http.QPack.QPackEncoder.EncodeValueStringPart(), System.Text.Encoding.GetByteCount(), System.Text.Encoding.GetBytes(), System.Text.Encoding.Latin1, System.length, System.ReadOnlySpan< T >.Length, System.s, System.text, and System.values.