Terraria: System.Net.Http.QPack.QPackEncoder.EncodeLiteralHeaderFieldWithStaticNameReferenceToArray
EncodeLiteralHeaderFieldWithStaticNameReferenceToArray() [1/2]
static byte[] System.Net.Http.QPack.QPackEncoder.EncodeLiteralHeaderFieldWithStaticNameReferenceToArray (int index) inline static
Definition at line 51 of file QPackEncoder.cs.
    {
        Span<byte> destination = stackalloc byte[6];
        destination[0] = 112;
        int bytesWritten;
        bool flag = IntegerEncoder.Encode(index, 4, destination, out bytesWritten);
        return destination.Slice(0, bytesWritten).ToArray();
    }
References System.destination, System.Net.Http.HPack.IntegerEncoder.Encode(), and System.index.
Referenced by System.Net.Http.HttpConnectionPool.HttpConnectionPool(), and System.Net.Http.Headers.KnownHeader.Initialize().