Terraria: System.Net.Http.QPack.QPackEncoder.EncodeValueString
EncodeValueString() [2/2]
static bool System.Net.Http.QPack.QPackEncoder.EncodeValueString (string s, Encoding valueEncoding, Span< byte > buffer, out int length) inline static private
Definition at line 114 of file QPackEncoder.cs.
    {
        if (buffer.Length != 0)
        {
            buffer[0] = 0;
            int num = ((valueEncoding == null || valueEncoding == Encoding.Latin1) ? s.Length : valueEncoding.GetByteCount(s));
            if (IntegerEncoder.Encode(num, 7, buffer, out var bytesWritten))
            {
                buffer = buffer.Slice(bytesWritten);
                if (buffer.Length >= num)
                {
                    if (valueEncoding == null)
                    {
                        EncodeValueStringPart(s, buffer);
                    }
                    else
                    {
                        int bytes = valueEncoding.GetBytes(s, buffer);
                    }
                    length = bytesWritten + num;
                    return true;
                }
            }
        }
        length = 0;
        return false;
    }
References System.buffer, System.bytes, System.Net.Http.HPack.IntegerEncoder.Encode(), System.Net.Http.QPack.QPackEncoder.EncodeValueStringPart(), System.Text.Encoding.GetByteCount(), System.Text.Encoding.GetBytes(), System.Text.Encoding.Latin1, System.length, and System.s.
Referenced by System.Net.Http.Http3RequestStream.BufferLiteralHeaderValues(), System.Net.Http.QPack.QPackEncoder.EncodeLiteralHeaderFieldWithoutNameReference(), System.Net.Http.QPack.QPackEncoder.EncodeLiteralHeaderFieldWithoutNameReference(), System.Net.Http.QPack.QPackEncoder.EncodeLiteralHeaderFieldWithStaticNameReference(), and System.Net.Http.QPack.QPackEncoder.EncodeValueString().