Terraria: System.Net.Http.QPack.QPackEncoder.EncodeNameString
EncodeNameString()
static bool System.Net.Http.QPack.QPackEncoder.EncodeNameString (string s, Span< byte > buffer, out int length) inline static private
Definition at line 229 of file QPackEncoder.cs.
    {
        if (buffer.Length != 0)
        {
            buffer[0] = 48;
            if (IntegerEncoder.Encode(s.Length, 3, buffer, out var bytesWritten))
            {
                buffer = buffer.Slice(bytesWritten);
                if (buffer.Length >= s.Length)
                {
                    for (int i = 0; i < s.Length; i++)
                    {
                        int num = s[i];
                        if ((uint)(num - 65) <= 25u)
{
                            num |= 0x20;
                        }
                        buffer[i] = (byte)num;
                    }
                    length = bytesWritten + s.Length;
                    return true;
                }
            }
        }
        length = 0;
        return false;
    }
References System.buffer, System.Net.Http.HPack.IntegerEncoder.Encode(), System.length, and System.s.
Referenced by System.Net.Http.QPack.QPackEncoder.EncodeLiteralHeaderFieldWithoutNameReference(), System.Net.Http.QPack.QPackEncoder.EncodeLiteralHeaderFieldWithoutNameReference(), and System.Net.Http.QPack.QPackEncoder.EncodeLiteralHeaderFieldWithoutNameReferenceToArray().