Terraria: ZipContentSource.ZipContentSource
ZipContentSource() [2/3]
ZipContentSource.ZipContentSource (string path, string contentDir) inline
     {
         _zipFile = ZipFile.Read(path);
         if (ZipPathContainsInvalidCharacters(contentDir))
         {
             throw new ArgumentException("Content directory cannot contain \"..\"", "contentDir");
         }
         _basePath = CleanZipPath(contentDir);
         BuildEntryList();
     }
References _basePath, _zipFile, BuildEntryList(), CleanZipPath(), and ZipPathContainsInvalidCharacters().