Terraria: System.Xml.Xsl.Runtime.DecimalFormatter.DecimalFormatter
DecimalFormatter()
System.Xml.Xsl.Runtime.DecimalFormatter.DecimalFormatter (string formatPicture, DecimalFormat decimalFormat) inline
Definition at line 18 of file DecimalFormatter.cs.
    {
        if (formatPicture.Length == 0)
        {
            throw XsltException.Create(System.SR.Xslt_InvalidFormat);
        }
        _zeroDigit = decimalFormat.zeroDigit;
        _posFormatInfo = (NumberFormatInfo)decimalFormat.info.Clone();
        StringBuilder stringBuilder = new StringBuilder();
        bool flag = true;
        bool flag2 = false;
        bool flag3 = false;
        bool flag4 = false;
        bool flag5 = false;
        bool flag6 = false;
        char c = _posFormatInfo.NumberDecimalSeparator[0];
        char c2 = _posFormatInfo.NumberGroupSeparator[0];
        char c3 = _posFormatInfo.PercentSymbol[0];
        char c4 = _posFormatInfo.PerMilleSymbol[0];
        int num = 0;
        int num2 = 0;
        int num3 = -1;
        int num4 = -1;
        for (int i = 0; i < formatPicture.Length; i++)
        {
            char c5 = formatPicture[i];
            if (c5 == decimalFormat.digit)
            {
                if (flag3 && flag)
                {
                    throw XsltException.Create(System.SR.Xslt_InvalidFormat1, formatPicture);
                }
                num4 = stringBuilder.Length;
                flag4 = (flag6 = true);
                stringBuilder.Append('#');
            }
            else if (c5 == decimalFormat.zeroDigit)
            {
                if (flag4 && !flag)
                {
                    throw XsltException.Create(System.SR.Xslt_InvalidFormat2, formatPicture);
                }
                num4 = stringBuilder.Length;
                flag3 = (flag6 = true);
                stringBuilder.Append('0');
            }
            else if (c5 == decimalFormat.patternSeparator)
            {
                if (!flag6)
                {
                    throw XsltException.Create(System.SR.Xslt_InvalidFormat8);
                }
                if (flag2)
                {
                    throw XsltException.Create(System.SR.Xslt_InvalidFormat3, formatPicture);
                }
                flag2 = true;
                if (num3 < 0)
                {
                    num3 = num4 + 1;
                }
                num2 = RemoveTrailingComma(stringBuilder, num, num3);
                if (num2 > 9)
                {
                    num2 = 0;
                }
                _posFormatInfo.NumberGroupSizes = new int[1] { num2 };
                if (!flag5)
                {
                    _posFormatInfo.NumberDecimalDigits = 0;
                }
                _posFormat = stringBuilder.ToString();
                stringBuilder.Length = 0;
                num3 = -1;
                num4 = -1;
                num = 0;
                flag4 = (flag3 = (flag6 = false));
                flag5 = false;
                flag = true;
                _negFormatInfo = (NumberFormatInfo)decimalFormat.info.Clone();
                _negFormatInfo.NegativeSign = string.Empty;
            }
            else if (c5 == c)
            {
                if (flag5)
                {
                    throw XsltException.Create(System.SR.Xslt_InvalidFormat5, formatPicture);
                }
                num3 = stringBuilder.Length;
                flag5 = true;
                flag4 = (flag3 = (flag = false));
                stringBuilder.Append('.');
            }
            else if (c5 == c2)
            {
                num = stringBuilder.Length;
                num4 = num;
                stringBuilder.Append(',');
            }
            else if (c5 == c3)
            {
                stringBuilder.Append('%');
            }
            else if (c5 == c4)
            {
                stringBuilder.Append('‰');
            }
            else if (c5 == '\'')
            {
                int num5 = formatPicture.IndexOf('\'', i + 1);
                if (num5 < 0)
                {
                    num5 = formatPicture.Length - 1;
                }
                stringBuilder.Append(formatPicture, i, num5 - i + 1);
                i = num5;
            }
            else
            {
                if ((('0' <= c5 && c5 <= '9') || c5 == '\a') && decimalFormat.zeroDigit != '0')
                {
                    stringBuilder.Append('\a');
                }
                if ("0#.,%‰Ee\\'\";".Contains(c5))
                {
                    stringBuilder.Append('\\');
                }
                stringBuilder.Append(c5);
            }
        }
        if (!flag6)
        {
            throw XsltException.Create(System.SR.Xslt_InvalidFormat8);
        }
        NumberFormatInfo numberFormatInfo = (flag2 ? _negFormatInfo : _posFormatInfo);
        if (num3 < 0)
        {
            num3 = num4 + 1;
        }
        num2 = RemoveTrailingComma(stringBuilder, num, num3);
        if (num2 > 9)
        {
            num2 = 0;
        }
        numberFormatInfo.NumberGroupSizes = new int[1] { num2 };
        if (!flag5)
        {
            numberFormatInfo.NumberDecimalDigits = 0;
        }
        if (flag2)
        {
            _negFormat = stringBuilder.ToString();
        }
        else
        {
            _posFormat = stringBuilder.ToString();
        }
    }
References System.Xml.Xsl.Runtime.DecimalFormatter._negFormat, System.Xml.Xsl.Runtime.DecimalFormatter._negFormatInfo, System.Xml.Xsl.Runtime.DecimalFormatter._posFormat, System.Xml.Xsl.Runtime.DecimalFormatter._posFormatInfo, System.Xml.Xsl.Runtime.DecimalFormatter._zeroDigit, System.Globalization.NumberFormatInfo.Clone(), System.Xml.Xsl.XsltException.Create(), System.Xml.Dictionary, System.Globalization.NumberFormatInfo.NumberDecimalSeparator, System.Globalization.NumberFormatInfo.NumberGroupSeparator, System.Globalization.NumberFormatInfo.PercentSymbol, System.Globalization.NumberFormatInfo.PerMilleSymbol, System.Xml.Xsl.Runtime.DecimalFormatter.RemoveTrailingComma(), System.SR.Xslt_InvalidFormat, System.SR.Xslt_InvalidFormat1, System.SR.Xslt_InvalidFormat2, System.SR.Xslt_InvalidFormat3, System.SR.Xslt_InvalidFormat5, and System.SR.Xslt_InvalidFormat8.
Referenced by System.Xml.Xsl.Runtime.DecimalFormatter.Format().