Terraria: System.Transactions.TransactionStateDelegatedNonMSDTC.EnterState
EnterState()
override void System.Transactions.TransactionStateDelegatedNonMSDTC.EnterState (InternalTransaction tx) inline package
Definition at line 7 of file TransactionStateDelegatedNonMSDTC.cs.
    {
        CommonEnterState(tx);
        DistributedTransaction distributedTransaction = null;
        try
        {
            if (tx._durableEnlistment != null)
            {
                TransactionsEtwProvider log = TransactionsEtwProvider.Log;
                if (log.IsEnabled())
                {
                    log.EnlistmentStatus(tx._durableEnlistment, NotificationCall.Promote);
                }
            }
            distributedTransaction = TransactionState.TransactionStatePSPEOperation.PSPEPromote(tx);
        }
        catch (TransactionPromotionException innerException)
        {
            TransactionPromotionException exception = (TransactionPromotionException)(tx._innerException = innerException);
            TransactionsEtwProvider log2 = TransactionsEtwProvider.Log;
            if (log2.IsEnabled())
            {
                log2.ExceptionConsumed(exception);
            }
        }
        finally
        {
            if (tx.promotedToken == null)
            {
                tx.State.ChangeStateAbortedDuringPromotion(tx);
            }
        }
    }
References System.Transactions.InternalTransaction._durableEnlistment, System.Transactions.InternalTransaction._innerException, System.Transactions.TransactionState.ChangeStateAbortedDuringPromotion(), System.Transactions.TransactionState.CommonEnterState(), System.Transactions.TransactionsEtwProvider.EnlistmentStatus(), System.exception, System.Transactions.TransactionsEtwProvider.ExceptionConsumed(), System.Diagnostics.Tracing.EventSource.IsEnabled(), System.Transactions.TransactionsEtwProvider.Log, System.Transactions.InternalTransaction.promotedToken, System.Transactions.InternalTransaction.State, and System.Transactions.TransactionState.TransactionStatePSPEOperation.