Terraria: CalculatedStyle.Center
Center()
Vector2 CalculatedStyle.Center () inline
     {
         return new Vector2(X + Width * 0.5f, Y + Height * 0.5f);
     }
References Height, Width, X, and Y.
Referenced by UIBestiaryEntryIcon.DrawSelf(), UIIconTextButton.DrawSelf(), UIItemIcon.DrawSelf(), UIItemSlot.DrawSelf(), and UIVirtualKeyboard.SetupGamepadPoints().