Terraria: System.Security.Cryptography.Asn1.X509ExtensionAsn.Encode
Encode() [2/2]
void System.Security.Cryptography.Asn1.X509ExtensionAsn.Encode (AsnWriter writer, Asn1Tag tag) inline package
Definition at line 21 of file X509ExtensionAsn.cs.
    {
        writer.PushSequence(tag);
        try
        {
            writer.WriteObjectIdentifier(ExtnId);
        }
        catch (ArgumentException inner)
        {
            throw new CryptographicException(System.SR.Cryptography_Der_Invalid_Encoding, inner);
        }
        AsnWriter asnWriter = new AsnWriter(AsnEncodingRules.DER);
        asnWriter.WriteBoolean(Critical);
        if (!asnWriter.EncodedValueEquals(DefaultCritical))
        {
            asnWriter.CopyTo(writer);
        }
        writer.WriteOctetString(ExtnValue.Span);
        writer.PopSequence(tag);
    }
References System.Formats.Asn1.AsnWriter.CopyTo(), System.Security.Cryptography.Asn1.X509ExtensionAsn.Critical, System.SR.Cryptography_Der_Invalid_Encoding, System.Security.Cryptography.Asn1.X509ExtensionAsn.DefaultCritical, System.Formats.Asn1.AsnWriter.EncodedValueEquals(), System.Security.Cryptography.Asn1.X509ExtensionAsn.ExtnId, System.Security.Cryptography.Asn1.X509ExtensionAsn.ExtnValue, System.ReadOnlyMemory< T >.Span, System.Formats.Asn1.AsnWriter.WriteBoolean(), and System.writer.