Terraria: System.Text.EncodingExtensions.GetBytes
GetBytes() [1/4]
static byte[] System.Text.EncodingExtensions.GetBytes (this Encoding encoding, in ReadOnlySequence< char > chars) inline static
Definition at line 74 of file EncodingExtensions.cs.
    {
        if (encoding == null)
        {
            throw new ArgumentNullException("encoding");
        }
        if (chars.IsSingleSegment)
        {
            ReadOnlySpan<char> firstSpan = chars.FirstSpan;
            byte[] array = new byte[encoding.GetByteCount(firstSpan)];
            encoding.GetBytes(firstSpan, array);
            return array;
        }
        Encoder encoder = encoding.GetEncoder();
        List<(byte[], int)> list = new List<(byte[], int)>();
        int num = 0;
        ReadOnlySequence<char> readOnlySequence = chars;
        bool isSingleSegment;
        do
        {
            readOnlySequence.GetFirstSpan(out var first, out var next);
            isSingleSegment = readOnlySequence.IsSingleSegment;
            int byteCount = encoder.GetByteCount(first, isSingleSegment);
            byte[] array2 = ArrayPool<byte>.Shared.Rent(byteCount);
            int bytes = encoder.GetBytes(first, array2, isSingleSegment);
            list.Add((array2, bytes));
            num += bytes;
            if (num < 0)
            {
                num = int.MaxValue;
                break;
            }
            readOnlySequence = readOnlySequence.Slice(next);
        }
        while (!isSingleSegment);
        byte[] array3 = new byte[num];
        Span<byte> destination = array3;
        foreach (var (array4, num2) in list)
        {
            array4.AsSpan(0, num2).CopyTo(destination);
            ArrayPool<byte>.Shared.Return(array4);
            destination = destination.Slice(num2);
        }
        return array3;
    }
References System.array, System.byteCount, System.bytes, System.chars, System.Collections.Generic.Dictionary< TKey, TValue >.CopyTo(), System.destination, System.Text.Encoding.GetByteCount(), System.Text.Encoder.GetByteCount(), System.Text.Encoding.GetBytes(), System.Text.Encoder.GetBytes(), System.Text.Encoding.GetEncoder(), and System.list.