Terraria: System.Text.EncodingExtensions.GetString
GetString()
static string System.Text.EncodingExtensions.GetString (this Encoding encoding, in ReadOnlySequence< byte > bytes) inline static
Definition at line 186 of file EncodingExtensions.cs.
    {
        if (encoding == null)
        {
            throw new ArgumentNullException("encoding");
        }
        if (bytes.IsSingleSegment)
        {
            return encoding.GetString(bytes.FirstSpan);
        }
        Decoder decoder = encoding.GetDecoder();
        List<(char[], int)> list = new List<(char[], int)>();
        int num = 0;
        ReadOnlySequence<byte> readOnlySequence = bytes;
        bool isSingleSegment;
        do
        {
            readOnlySequence.GetFirstSpan(out var first, out var next);
            isSingleSegment = readOnlySequence.IsSingleSegment;
            int charCount = decoder.GetCharCount(first, isSingleSegment);
            char[] array = ArrayPool<char>.Shared.Rent(charCount);
            int chars = decoder.GetChars(first, array, isSingleSegment);
            list.Add((array, chars));
            num += chars;
            if (num < 0)
            {
                num = int.MaxValue;
                break;
            }
            readOnlySequence = readOnlySequence.Slice(next);
        }
        while (!isSingleSegment);
        return string.Create(num, list, delegate(Span<char> span, List<(char[], int)> listOfSegments)
        {
            foreach (var (array2, num2) in listOfSegments)
            {
                array2.AsSpan(0, num2).CopyTo(span);
                ArrayPool<char>.Shared.Return(array2);
                span = span.Slice(num2);
            }
        });
    }
References System.array, System.bytes, System.charCount, System.chars, System.Collections.Generic.Dictionary< TKey, TValue >.CopyTo(), System.Text.Decoder.GetCharCount(), System.Text.Decoder.GetChars(), System.Text.Encoding.GetDecoder(), System.Text.Encoding.GetString(), and System.list.