Terraria: System.Net.Http.Headers.HeaderUtilities.TryParseInt64
TryParseInt64()
static bool System.Net.Http.Headers.HeaderUtilities.TryParseInt64 (string value, int offset, int length, out long result) inline static package
Definition at line 255 of file HeaderUtilities.cs.
    {
        if (offset < 0 || length < 0 || offset > value.Length - length)
        {
            result = 0L;
            return false;
        }
        return long.TryParse(value.AsSpan(offset, length), NumberStyles.None, CultureInfo.InvariantCulture, out result);
    }
References System.Globalization.CultureInfo.InvariantCulture, System.L, System.length, System.offset, and System.value.
Referenced by System.Net.Http.Headers.Int64NumberHeaderParser.GetParsedValueLength(), System.Net.Http.Headers.RangeItemHeaderValue.GetRangeItemLength(), and System.Net.Http.Headers.ContentRangeHeaderValue.TryCreateContentRange().