Terraria: System.Net.Http.Headers.HeaderUtilities.CheckValidToken
CheckValidToken()
static void System.Net.Http.Headers.HeaderUtilities.CheckValidToken (string value, string parameterName) inline static package
Definition at line 105 of file HeaderUtilities.cs.
    {
        if (string.IsNullOrEmpty(value))
        {
            throw new ArgumentException(System.SR.net_http_argument_empty_string, parameterName);
        }
        if (HttpRuleParser.GetTokenLength(value, 0) != value.Length)
        {
            throw new FormatException(System.SR.Format(CultureInfo.InvariantCulture, System.SR.net_http_headers_invalid_value, value));
        }
    }
References System.SR.Format(), System.Net.Http.HttpRuleParser.GetTokenLength(), System.Globalization.CultureInfo.InvariantCulture, System.SR.net_http_argument_empty_string, System.SR.net_http_headers_invalid_value, and System.value.
Referenced by System.Net.Http.Headers.AuthenticationHeaderValue.AuthenticationHeaderValue(), System.Net.Http.Headers.ProductHeaderValue.ProductHeaderValue(), System.Net.Http.Headers.StringWithQualityHeaderValue.StringWithQualityHeaderValue(), System.Net.Http.Headers.StringWithQualityHeaderValue.StringWithQualityHeaderValue(), System.Net.Http.Headers.TransferCodingHeaderValue.TransferCodingHeaderValue(), System.Net.Http.Headers.ViaHeaderValue.ViaHeaderValue(), System.Net.Http.Headers.CacheControlHeaderValue.CheckIsValidToken(), System.Net.Http.Headers.NameValueHeaderValue.CheckNameValueFormat(), and System.Net.Http.Headers.HeaderUtilities.ValidateToken().