Terraria: System.Net.Http.Headers.HeaderUtilities.DumpHeaders
DumpHeaders()
static void System.Net.Http.Headers.HeaderUtilities.DumpHeaders (StringBuilder sb, params HttpHeaders[] headers) inline static package
Definition at line 265 of file HeaderUtilities.cs.
    {
        sb.AppendLine("{");
        foreach (HttpHeaders httpHeaders in headers)
        {
            if (httpHeaders == null)
            {
                continue;
            }
            foreach (KeyValuePair<string, HeaderStringValues> item in httpHeaders.NonValidated)
            {
                foreach (string item2 in item.Value)
                {
                    sb.Append("  ");
                    sb.Append(item.Key);
                    sb.Append(": ");
                    sb.AppendLine(item2);
                }
            }
        }
        sb.Append('}');
    }
References System.Text.StringBuilder.Append(), System.Text.StringBuilder.AppendLine(), and System.item.
Referenced by System.Net.Http.HttpRequestMessage.ToString(), and System.Net.Http.HttpResponseMessage.ToString().