Terraria: System.Net.Http.Headers.HeaderUtilities.GetQuality
GetQuality()
static ? double System.Net.Http.Headers.HeaderUtilities.GetQuality (ObjectCollection< NameValueHeaderValue > parameters) inline static package
Definition at line 87 of file HeaderUtilities.cs.
    {
        NameValueHeaderValue nameValueHeaderValue = NameValueHeaderValue.Find(parameters, "q");
        if (nameValueHeaderValue != null)
        {
            double result = 0.0;
            if (double.TryParse(nameValueHeaderValue.Value, NumberStyles.AllowDecimalPoint, NumberFormatInfo.InvariantInfo, out result))
            {
                return result;
            }
            if (System.Net.NetEventSource.Log.IsEnabled())
            {
                System.Net.NetEventSource.Error(null, System.SR.Format(System.SR.net_http_log_headers_invalid_quality, nameValueHeaderValue.Value), "GetQuality");
            }
        }
        return null;
    }
References System.Net.NetEventSource.Error(), System.Net.Http.Headers.NameValueHeaderValue.Find(), System.SR.Format(), System.Globalization.NumberFormatInfo.InvariantInfo, System.Net.NetEventSource.Log, and System.SR.net_http_log_headers_invalid_quality.