Terraria: System.Net.Http.Headers.HeaderUtilities.Encode5987
Encode5987()
static string System.Net.Http.Headers.HeaderUtilities.Encode5987 (string input) inline static package
Definition at line 53 of file HeaderUtilities.cs.
    {
        StringBuilder stringBuilder = System.Text.StringBuilderCache.Acquire();
        byte[] array = ArrayPool<byte>.Shared.Rent(Encoding.UTF8.GetMaxByteCount(input.Length));
        int bytes = Encoding.UTF8.GetBytes(input, 0, input.Length, array, 0);
        stringBuilder.Append("utf-8''");
        for (int i = 0; i < bytes; i++)
        {
            byte b = array[i];
            if (b > 127)
            {
                AddHexEscaped(b, stringBuilder);
            }
            else if (!HttpRuleParser.IsTokenChar((char)b) || b == 42 || b == 39 || b == 37)
            {
                AddHexEscaped(b, stringBuilder);
            }
            else
            {
                stringBuilder.Append((char)b);
            }
        }
        Array.Clear(array, 0, bytes);
        ArrayPool<byte>.Shared.Return(array);
        return System.Text.StringBuilderCache.GetStringAndRelease(stringBuilder);
    }
References System.Text.StringBuilderCache.Acquire(), System.Net.Http.Headers.HeaderUtilities.AddHexEscaped(), System.array, System.bytes, System.Array.Clear(), System.Text.StringBuilderCache.GetStringAndRelease(), System.input, System.Net.Http.HttpRuleParser.IsTokenChar(), and System.Text.Encoding.UTF8.
Referenced by System.Net.Http.AuthenticationHelper.GetDigestTokenForCredential(), and System.Net.Http.Headers.ContentDispositionHeaderValue.SetName().