Terraria: System.Net.Http.Headers.HeaderUtilities.SetQuality
SetQuality()
static void System.Net.Http.Headers.HeaderUtilities.SetQuality (ObjectCollection< NameValueHeaderValue > parameters, double? value) inline static package
Definition at line 16 of file HeaderUtilities.cs.
    {
        NameValueHeaderValue nameValueHeaderValue = NameValueHeaderValue.Find(parameters, "q");
        if (value.HasValue)
        {
            if (value < 0.0 || value > 1.0)
            {
                throw new ArgumentOutOfRangeException("value");
            }
            string value2 = value.Value.ToString("0.0##", NumberFormatInfo.InvariantInfo);
            if (nameValueHeaderValue != null)
            {
                nameValueHeaderValue.Value = value2;
            }
            else
            {
                parameters.Add(new NameValueHeaderValue("q", value2));
            }
        }
        else if (nameValueHeaderValue != null)
        {
            parameters.Remove(nameValueHeaderValue);
        }
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Net.Http.Headers.NameValueHeaderValue.Find(), System.Globalization.NumberFormatInfo.InvariantInfo, System.Collections.Generic.Dictionary< TKey, TValue >.Remove(), and System.value.