Terraria: System.Security.Cryptography.DSACng.ThrowIfDisposed
ThrowIfDisposed()
void System.Security.Cryptography.DSACng.ThrowIfDisposed () inline private
Definition at line 62 of file DSACng.cs.
    {
        _core.ThrowIfDisposed();
    }
References System.Security.Cryptography.DSACng._core, and Internal.Cryptography.CngAlgorithmCore.ThrowIfDisposed().
Referenced by System.Security.Cryptography.DSACng.ImportEncryptedPkcs8PrivateKey(), and System.Security.Cryptography.DSACng.ImportEncryptedPkcs8PrivateKey().