Terraria: System.Data.Common.SqlStringStorage.Aggregate
Aggregate()
override object System.Data.Common.SqlStringStorage.Aggregate (int[] recordNos, AggregateType kind) inline virtual
Reimplemented from System.Data.Common.DataStorage.
Definition at line 19 of file SqlStringStorage.cs.
    {
        try
        {
            switch (kind)
            {
            case AggregateType.Min:
            {
                int num3 = -1;
                int i;
                for (i = 0; i < recordNos.Length; i++)
                {
                    if (!IsNull(recordNos[i]))
                    {
                        num3 = recordNos[i];
                        break;
                    }
                }
                if (num3 >= 0)
                {
                    for (i++; i < recordNos.Length; i++)
                    {
                        if (!IsNull(recordNos[i]) && Compare(num3, recordNos[i]) > 0)
{
                            num3 = recordNos[i];
                        }
                    }
                    return Get(num3);
                }
                return _nullValue;
            }
            case AggregateType.Max:
            {
                int num2 = -1;
                int i;
                for (i = 0; i < recordNos.Length; i++)
                {
                    if (!IsNull(recordNos[i]))
                    {
                        num2 = recordNos[i];
                        break;
                    }
                }
                if (num2 >= 0)
                {
                    for (i++; i < recordNos.Length; i++)
                    {
                        if (Compare(num2, recordNos[i]) < 0)
{
                            num2 = recordNos[i];
                        }
                    }
                    return Get(num2);
                }
                return _nullValue;
            }
            case AggregateType.Count:
            {
                int num = 0;
                for (int i = 0; i < recordNos.Length; i++)
                {
                    if (!IsNull(recordNos[i]))
                    {
                        num++;
                    }
                }
                return num;
            }
            case AggregateType.First:
                break;
            }
        }
        catch (OverflowException)
        {
            throw ExprException.Overflow(typeof(SqlString));
        }
        throw ExceptionBuilder.AggregateException(kind, _dataType);
    }
References System.Data.Common.DataStorage._dataType, System.Data.Common.DataStorage._nullValue, System.Data.ExceptionBuilder.AggregateException(), System.Data.Common.SqlStringStorage.Compare(), System.Xml.Dictionary, System.Data.Common.SqlStringStorage.Get(), System.Data.IsNull, and System.Data.ExprException.Overflow().