Terraria: System.Dynamic.Utils.ListProvider.CopyTo
CopyTo() [2/2]
void System.Dynamic.Utils.ListProvider< T >.CopyTo (T[] array, int index) inline
Definition at line 84 of file ListProvider.cs.
    {
        ContractUtils.RequiresNotNull(array, "array");
        if (index < 0)
        {
            throw Error.ArgumentOutOfRange("index");
        }
        int elementCount = ElementCount;
        if (index + elementCount > array.Length)
        {
            throw new ArgumentException();
        }
        array[index++] = First;
        for (int i = 1; i < elementCount; i++)
        {
            array[index++] = GetElement(i);
        }
    }
References System.Linq.Expressions.Error.ArgumentOutOfRange(), System.array, System.Dynamic.Utils.ListProvider< T >.ElementCount, System.Dynamic.Utils.ListProvider< T >.First, System.Dynamic.Utils.ListProvider< T >.GetElement(), System.index, and System.Dynamic.Utils.ContractUtils.RequiresNotNull().