Terraria: System.Data.Common.SqlStringStorage.Compare
Compare() [1/2]
override int System.Data.Common.SqlStringStorage.Compare (int recordNo1, int recordNo2) inline
Definition at line 98 of file SqlStringStorage.cs.
    {
        return Compare(_values[recordNo1], _values[recordNo2]);
    }
References System.Data.Common.SqlStringStorage._values, System.Data.Common.SqlStringStorage.Compare(), and System.Xml.Dictionary.
Referenced by System.Data.Common.SqlStringStorage.Aggregate(), System.Data.Common.SqlStringStorage.Compare(), and System.Data.Common.SqlStringStorage.CompareValueTo().