Terraria: System.Collections.Concurrent.Partitioner.DynamicPartitionerForIEnumerable.InternalPartitionEnumerable.GrabChunk
GrabChunk()
bool System.Collections.Concurrent.Partitioner< TSource >.DynamicPartitionerForIEnumerable< TSource >.InternalPartitionEnumerable.GrabChunk (KeyValuePair< long, TSource >[] destArray, int requestedChunkSize, ref int actualNumElementsGrabbed) inline package
Definition at line 182 of file Partitioner.cs.
            {
                actualNumElementsGrabbed = 0;
                if (_hasNoElementsLeft.Value)
                {
                    return false;
                }
                if (_useSingleChunking)
                {
                    return GrabChunk_Single(destArray, requestedChunkSize, ref actualNumElementsGrabbed);
                }
                return GrabChunk_Buffered(destArray, requestedChunkSize, ref actualNumElementsGrabbed);
            }
References System.Collections.Concurrent.Partitioner< TSource >.DynamicPartitionerForIEnumerable< TSource >.InternalPartitionEnumerable._hasNoElementsLeft, System.Collections.Concurrent.Partitioner< TSource >.DynamicPartitionerForIEnumerable< TSource >.InternalPartitionEnumerable._useSingleChunking, System.Collections.Concurrent.Partitioner< TSource >.DynamicPartitionerForIEnumerable< TSource >.InternalPartitionEnumerable.GrabChunk_Buffered(), System.Collections.Concurrent.Partitioner< TSource >.DynamicPartitionerForIEnumerable< TSource >.InternalPartitionEnumerable.GrabChunk_Single(), and System.Collections.Concurrent.Partitioner< TSource >.SharedBool.Value.
Referenced by System.Collections.Concurrent.Partitioner< TSource >.DynamicPartitionerForIEnumerable< TSource >.InternalPartitionEnumerator.GrabNextChunk().