Terraria: System.Collections.Concurrent.Partitioner.DynamicPartitionerForIEnumerable.InternalPartitionEnumerable.GrabChunk_Buffered
GrabChunk_Buffered()
bool System.Collections.Concurrent.Partitioner< TSource >.DynamicPartitionerForIEnumerable< TSource >.InternalPartitionEnumerable.GrabChunk_Buffered (KeyValuePair< long, TSource >[] destArray, int requestedChunkSize, ref int actualNumElementsGrabbed) inline package
Definition at line 226 of file Partitioner.cs.
            {
                TryCopyFromFillBuffer(destArray, requestedChunkSize, ref actualNumElementsGrabbed);
                if (actualNumElementsGrabbed == requestedChunkSize)
                {
                    return true;
                }
                if (_sourceDepleted.Value)
                {
                    _hasNoElementsLeft.Value = true;
                    _fillBuffer = null;
                    return actualNumElementsGrabbed > 0;
                }
                lock (_sharedLock)
                {
                    if (_sourceDepleted.Value)
                    {
                        return actualNumElementsGrabbed > 0;
                    }
                    try
                    {
                        if (_activeCopiers > 0)
{
                            SpinWait spinWait = default(SpinWait);
                            while (_activeCopiers > 0)
{
                                spinWait.SpinOnce();
                            }
                        }
                        while (actualNumElementsGrabbed < requestedChunkSize)
{
                            if (_sharedReader.MoveNext())
{
                                _sharedIndex.Value = checked(_sharedIndex.Value + 1);
                                destArray[actualNumElementsGrabbed] = new KeyValuePair<long, TSource>(_sharedIndex.Value, _sharedReader.Current);
                                actualNumElementsGrabbed++;
                                continue;
                            }
                            _sourceDepleted.Value = true;
                            break;
                        }
                        KeyValuePair<long, TSource>[] fillBuffer = _fillBuffer;
                        if (!_sourceDepleted.Value && fillBuffer != null && _fillBufferCurrentPosition >= fillBuffer.Length)
{
                            for (int i = 0; i < fillBuffer.Length; i++)
{
                                if (_sharedReader.MoveNext())
{
                                    _sharedIndex.Value = checked(_sharedIndex.Value + 1);
                                    fillBuffer[i] = new KeyValuePair<long, TSource>(_sharedIndex.Value, _sharedReader.Current);
                                    continue;
                                }
                                _sourceDepleted.Value = true;
                                _fillBufferSize = i;
                                break;
                            }
                            _fillBufferCurrentPosition = 0;
                        }
                    }
                    catch
                    {
                        _sourceDepleted.Value = true;
                        _hasNoElementsLeft.Value = true;
                        throw;
                    }
                }
                return actualNumElementsGrabbed > 0;
            }
References System.Collections.Concurrent.Partitioner< TSource >.DynamicPartitionerForIEnumerable< TSource >.InternalPartitionEnumerable._activeCopiers, System.Collections.Concurrent.Partitioner< TSource >.DynamicPartitionerForIEnumerable< TSource >.InternalPartitionEnumerable._fillBuffer, System.Collections.Concurrent.Partitioner< TSource >.DynamicPartitionerForIEnumerable< TSource >.InternalPartitionEnumerable._fillBufferCurrentPosition, System.Collections.Concurrent.Partitioner< TSource >.DynamicPartitionerForIEnumerable< TSource >.InternalPartitionEnumerable._fillBufferSize, System.Collections.Concurrent.Partitioner< TSource >.DynamicPartitionerForIEnumerable< TSource >.InternalPartitionEnumerable._sharedIndex, System.Collections.Concurrent.Partitioner< TSource >.DynamicPartitionerForIEnumerable< TSource >.InternalPartitionEnumerable._sharedLock, System.Collections.Concurrent.Partitioner< TSource >.DynamicPartitionerForIEnumerable< TSource >.InternalPartitionEnumerable._sharedReader, System.Collections.Concurrent.Partitioner< TSource >.DynamicPartitionerForIEnumerable< TSource >.InternalPartitionEnumerable._sourceDepleted, System.Collections.IEnumerator.Current, System.Collections.IEnumerator.MoveNext(), System.Collections.Concurrent.Partitioner< TSource >.DynamicPartitionerForIEnumerable< TSource >.InternalPartitionEnumerable.TryCopyFromFillBuffer(), System.Collections.Concurrent.Partitioner< TSource >.SharedBool.Value, and System.Collections.Concurrent.Partitioner< TSource >.SharedLong.Value.
Referenced by System.Collections.Concurrent.Partitioner< TSource >.DynamicPartitionerForIEnumerable< TSource >.InternalPartitionEnumerable.GrabChunk().