Terraria: System.Formats.Asn1.T61Encoding.s_utf8Encoding
s_utf8Encoding
readonly Encoding System.Formats.Asn1.T61Encoding.s_utf8Encoding = new UTF8Encoding(encoderShouldEmitUTF8Identifier: false, throwOnInvalidBytes: true) static private
Definition at line 7 of file T61Encoding.cs.
Referenced by System.Formats.Asn1.T61Encoding.GetByteCount(), System.Formats.Asn1.T61Encoding.GetByteCount(), System.Formats.Asn1.T61Encoding.GetByteCount(), System.Formats.Asn1.T61Encoding.GetByteCount(), System.Formats.Asn1.T61Encoding.GetBytes(), System.Formats.Asn1.T61Encoding.GetBytes(), System.Formats.Asn1.T61Encoding.GetCharCount(), System.Formats.Asn1.T61Encoding.GetCharCount(), System.Formats.Asn1.T61Encoding.GetCharCount(), System.Formats.Asn1.T61Encoding.GetChars(), System.Formats.Asn1.T61Encoding.GetChars(), and System.Formats.Asn1.T61Encoding.GetMaxByteCount().