Terraria: PlayerSittingHelper.UpdateSitting
UpdateSitting()
void PlayerSittingHelper.UpdateSitting (Player player) inline
     {
         if (!isSitting)
         {
             return;
         }
         Point coords = (player.Bottom + new Vector2(0f, -2f)).ToTileCoordinates();
         if (!GetSittingTargetInfo(player, coords.X, coords.Y, out var targetDirection, out var _, out var seatDownOffset, out var extraInfo))
         {
             SitUp(player);
             return;
         }
         if (player.controlLeft || player.controlRight || player.controlUp || player.controlDown || player.controlJump || player.pulley || player.mount.Active || targetDirection != player.direction)
         {
             SitUp(player);
         }
         if (Main.sittingManager.GetNextPlayerStackIndexInCoords(coords) >= 2)
         {
             SitUp(player);
         }
         if (isSitting)
         {
             offsetForSeat = seatDownOffset;
             details = extraInfo;
             Main.sittingManager.AddPlayerAndGetItsStackedIndexInCoords(player.whoAmI, coords, out sittingIndex);
         }
     }
References Mount.Active, AnchoredEntitiesCollection.AddPlayerAndGetItsStackedIndexInCoords(), Entity.Bottom, Player.controlDown, Player.controlJump, Player.controlLeft, Player.controlRight, Player.controlUp, details, Entity.direction, AnchoredEntitiesCollection.GetNextPlayerStackIndexInCoords(), GetSittingTargetInfo(), isSitting, Player.mount, offsetForSeat, Player.pulley, sittingIndex, Main.sittingManager, SitUp(), and Entity.whoAmI.