Terraria: PlayerSittingHelper.SitDown
SitDown()
void PlayerSittingHelper.SitDown (Player player, int x, int y) inline
     {
         if (!GetSittingTargetInfo(player, x, y, out var targetDirection, out var playerSittingPosition, out var seatDownOffset, out var extraInfo))
         {
             return;
         }
         Vector2 offset = playerSittingPosition - player.Bottom;
         bool flag = player.CanSnapToPosition(offset);
         if (flag)
         {
             flag &= Main.sittingManager.GetNextPlayerStackIndexInCoords((playerSittingPosition + new Vector2(0f, -2f)).ToTileCoordinates()) < 2;
         }
         if (!flag)
         {
             return;
         }
         if (isSitting && player.Bottom == playerSittingPosition)
         {
             SitUp(player);
             return;
         }
         player.StopVanityActions();
         player.RemoveAllGrapplingHooks();
         if (player.mount.Active)
         {
             player.mount.Dismount(player);
         }
         player.Bottom = playerSittingPosition;
         player.ChangeDir(targetDirection);
         isSitting = true;
         details = extraInfo;
         offsetForSeat = seatDownOffset;
         Main.sittingManager.AddPlayerAndGetItsStackedIndexInCoords(player.whoAmI, new Point(x, y), out sittingIndex);
         player.velocity = Vector2.Zero;
         player.gravDir = 1f;
         if (Main.myPlayer == player.whoAmI)
         {
             NetMessage.SendData(13, -1, -1, null, player.whoAmI);
         }
     }
References Mount.Active, AnchoredEntitiesCollection.AddPlayerAndGetItsStackedIndexInCoords(), Entity.Bottom, Player.CanSnapToPosition(), Player.ChangeDir(), details, Mount.Dismount(), AnchoredEntitiesCollection.GetNextPlayerStackIndexInCoords(), GetSittingTargetInfo(), Player.gravDir, isSitting, Player.mount, Main.myPlayer, offsetForSeat, Player.RemoveAllGrapplingHooks(), NetMessage.SendData(), sittingIndex, Main.sittingManager, SitUp(), Player.StopVanityActions(), Entity.velocity, and Entity.whoAmI.