Terraria: PlayerSittingHelper.SitUp
SitUp()
void PlayerSittingHelper.SitUp (Player player, bool multiplayerBroadcast = true) inline
     {
         if (isSitting)
         {
             isSitting = false;
             offsetForSeat = Vector2.Zero;
             sittingIndex = -1;
             details = default(ExtraSeatInfo);
             if (multiplayerBroadcast && Main.myPlayer == player.whoAmI)
             {
                 NetMessage.SendData(13, -1, -1, null, player.whoAmI);
             }
         }
     }
References details, isSitting, Main.myPlayer, offsetForSeat, NetMessage.SendData(), sittingIndex, and Entity.whoAmI.
Referenced by SitDown(), and UpdateSitting().