Terraria: System.Xml.Serialization.IXmlSerializable.ReadXml
ReadXml()
void System.Xml.Serialization.IXmlSerializable.ReadXml (XmlReader reader)
Implemented in System.Data.SqlTypes.SqlBytes, System.Data.SqlTypes.SqlChars, System.Data.SqlTypes.SqlXml, System.Data.SqlTypes.SqlBinary, System.Data.SqlTypes.SqlBoolean, System.Data.SqlTypes.SqlByte, System.Data.SqlTypes.SqlDateTime, System.Data.SqlTypes.SqlDecimal, System.Data.SqlTypes.SqlDouble, System.Data.SqlTypes.SqlGuid, System.Data.SqlTypes.SqlInt16, System.Data.SqlTypes.SqlInt32, System.Data.SqlTypes.SqlInt64, System.Data.SqlTypes.SqlMoney, System.Data.SqlTypes.SqlSingle, System.Data.SqlTypes.SqlString, System.Data.DataSet, System.Data.DataTable, and System.Xml.Linq.XElement.
Referenced by System.Data.Common.SqlBinaryStorage.ConvertXmlToObject(), System.Data.Common.SqlBooleanStorage.ConvertXmlToObject(), System.Data.Common.SqlBytesStorage.ConvertXmlToObject(), System.Data.Common.SqlByteStorage.ConvertXmlToObject(), System.Data.Common.SqlCharsStorage.ConvertXmlToObject(), System.Data.Common.SqlDateTimeStorage.ConvertXmlToObject(), System.Data.Common.SqlDecimalStorage.ConvertXmlToObject(), System.Data.Common.SqlDoubleStorage.ConvertXmlToObject(), System.Data.Common.SqlGuidStorage.ConvertXmlToObject(), System.Data.Common.SqlInt16Storage.ConvertXmlToObject(), System.Data.Common.SqlInt32Storage.ConvertXmlToObject(), System.Data.Common.SqlInt64Storage.ConvertXmlToObject(), System.Data.Common.SqlMoneyStorage.ConvertXmlToObject(), System.Data.Common.SqlSingleStorage.ConvertXmlToObject(), and System.Data.Common.SqlStringStorage.ConvertXmlToObject().