Terraria: System.Text.Json.JsonEncodedText.TranscodeAndEncode
TranscodeAndEncode()
static JsonEncodedText System.Text.Json.JsonEncodedText.TranscodeAndEncode (ReadOnlySpan< char > value, JavaScriptEncoder encoder) inline static private
Definition at line 39 of file JsonEncodedText.cs.
    {
        JsonWriterHelper.ValidateValue(value);
        int utf8ByteCount = JsonReaderHelper.GetUtf8ByteCount(value);
        byte[] array = ArrayPool<byte>.Shared.Rent(utf8ByteCount);
        int utf8FromText = JsonReaderHelper.GetUtf8FromText(value, array);
        JsonEncodedText result = EncodeHelper(array.AsSpan(0, utf8FromText), encoder);
        array.AsSpan(0, utf8ByteCount).Clear();
        ArrayPool<byte>.Shared.Return(array);
        return result;
    }
References System.array, System.Text.Json.Dictionary, System.Text.Json.JsonEncodedText.EncodeHelper(), System.Text.Json.JsonReaderHelper.GetUtf8ByteCount(), System.Text.Json.JsonReaderHelper.GetUtf8FromText(), System.Buffers.ArrayPool< T >.Shared, System.Text.Json.JsonWriterHelper.ValidateValue(), and System.value.
Referenced by System.Text.Json.JsonEncodedText.Encode().