Terraria: System.Convert.TryFromBase64Chars
TryFromBase64Chars()
static bool System.Convert.TryFromBase64Chars (ReadOnlySpan< char > chars, Span< byte > bytes, out int bytesWritten) inline static
Definition at line 2925 of file Convert.cs.
    {
        Span<char> span = stackalloc char[4];
        bytesWritten = 0;
        while (chars.Length != 0)
        {
            int consumed;
            int written;
            bool flag = TryDecodeFromUtf16(chars, bytes, out consumed, out written);
            bytesWritten += written;
            if (flag)
            {
                return true;
            }
            chars = chars.Slice(consumed);
            bytes = bytes.Slice(written);
            if (chars[0].IsSpace())
            {
                int i;
                for (i = 1; i != chars.Length && chars[i].IsSpace(); i++)
                {
                }
                chars = chars.Slice(i);
                if (written % 3 != 0 && chars.Length != 0)
                {
                    bytesWritten = 0;
                    return false;
                }
                continue;
            }
            CopyToTempBufferWithoutWhiteSpace(chars, span, out var consumed2, out var charsWritten);
            if (((uint)charsWritten & 3u) != 0)
            {
                bytesWritten = 0;
                return false;
            }
            span = span.Slice(0, charsWritten);
            if (!TryDecodeFromUtf16(span, bytes, out var _, out var written2))
            {
                bytesWritten = 0;
                return false;
            }
            bytesWritten += written2;
            chars = chars.Slice(consumed2);
            bytes = bytes.Slice(written2);
            if (written2 % 3 == 0)
            {
                continue;
            }
            for (int j = 0; j < chars.Length; j++)
            {
                if (!chars[j].IsSpace())
                {
                    bytesWritten = 0;
                    return false;
                }
            }
            return true;
        }
        return true;
    }
References System.bytes, System.chars, System.Convert.CopyToTempBufferWithoutWhiteSpace(), System.Convert.IsSpace(), System.Span< T >.Slice(), and System.Convert.TryDecodeFromUtf16().
Referenced by System.Security.Cryptography.X509Certificates.X509Certificate2.CreateFromPem(), System.Convert.FromBase64CharPtr(), Internal.Cryptography.PemKeyImportHelpers.ImportEncryptedPem< TPass >(), System.Security.Cryptography.X509Certificates.X509Certificate2Collection.ImportFromPem(), Internal.Cryptography.PemKeyImportHelpers.ImportPem(), System.Security.Cryptography.XmlKeyHelper.ReadCryptoBinary(), and System.Convert.TryFromBase64String().