Terraria: System.Convert.ToInt32
ToInt32() [10/19]
static int System.Convert.ToInt32 (object? value) inline static
Definition at line 1320 of file Convert.cs.
    {
        if (value != null)
        {
            return ((IConvertible)value).ToInt32(null);
        }
        return 0;
    }
References System.value.
Referenced by System.Data.BinaryNode.BinaryCompare(), ReLogic.Reflection.IdDictionary.Create(), Terraria.Main.DedServ(), Terraria.Main.DrawMenu(), System.Data.FunctionNode.Eval(), System.Data.BinaryNode.EvalBinaryOp(), System.Data.FunctionNode.EvalFunction(), System.Xml.Xsl.XsltOld.NumberAction.Format(), System.Drawing.ColorTranslator.FromHtml(), System.ComponentModel.Int32Converter.FromString(), System.AppContextConfigHelper.GetInt32Config(), System.Net.FtpControlStream.GetLastModifiedFrom213Response(), System.Net.FtpControlStream.GetPortV6(), System.Data.XDRSchema.HandleTable(), System.Drawing.ColorConverterCommon.IntFromString(), System.Runtime.Serialization.CodeGenerator.Ldc(), System.Xml.Serialization.CodeGenerator.Ldc(), Terraria.Main.LoadDedConfig(), Terraria.Initializers.LaunchInitializer.LoadServerParameters(), System.Data.SimpleType.LoadTypeValues(), MS.Internal.Xml.XPath.XPathScanner.NextLex(), Terraria.Main.setServerWorldRollbacks(), System.ComponentModel.DataAnnotations.RangeAttribute.SetupConversion(), System.Diagnostics.Tracing.NativeRuntimeEventSource.ThreadPoolIOEnqueue(), System.Convert.ToByte(), System.Convert.ToInt16(), System.Convert.ToInt32(), System.Boolean.ToInt32(), System.Byte.ToInt32(), System.Char.ToInt32(), System.Decimal.ToInt32(), System.Double.ToInt32(), System.Enum.ToInt32(), System.Int16.ToInt32(), System.Int64.ToInt32(), System.Single.ToInt32(), System.String.ToInt32(), System.UInt16.ToInt32(), System.UInt32.ToInt32(), System.UInt64.ToInt32(), System.Runtime.Serialization.FormatterConverter.ToInt32(), System.Linq.Expressions.Interpreter.ConvertHelper.ToInt32NoNull(), System.Convert.ToSByte(), System.Convert.ToUInt16(), System.Runtime.Serialization.Formatter.WriteMember(), and System.Runtime.Serialization.Formatters.Binary.BinaryFormatterWriter.WriteValue().