Terraria: System.Convert.ToInt16
ToInt16() [10/19]
static short System.Convert.ToInt16 (object? value) inline static
Definition at line 1038 of file Convert.cs.
    {
        if (value != null)
        {
            return ((IConvertible)value).ToInt16(null);
        }
        return 0;
    }
References System.value.
Referenced by System.Net.FtpControlStream.CheckValid(), System.Data.BinaryNode.EvalBinaryOp(), System.ComponentModel.Int16Converter.FromString(), System.AppContextConfigHelper.GetInt16Config(), System.Net.FtpControlStream.GetLastModifiedFrom213Response(), System.Convert.ToInt16(), System.Convert.ToInt16(), System.Boolean.ToInt16(), System.Byte.ToInt16(), System.Char.ToInt16(), System.Decimal.ToInt16(), System.Double.ToInt16(), System.Enum.ToInt16(), System.Int32.ToInt16(), System.Int64.ToInt16(), System.SByte.ToInt16(), System.Single.ToInt16(), System.String.ToInt16(), System.UInt16.ToInt16(), System.UInt32.ToInt16(), System.UInt64.ToInt16(), System.Runtime.Serialization.FormatterConverter.ToInt16(), System.Runtime.Serialization.Formatter.WriteMember(), and System.Runtime.Serialization.Formatters.Binary.BinaryFormatterWriter.WriteValue().