Terraria: System.Convert.TryToBase64Chars
TryToBase64Chars()
static unsafe bool System.Convert.TryToBase64Chars (ReadOnlySpan< byte > bytes, Span< char > chars, out int charsWritten, Base64FormattingOptions options = Base64FormattingOptions::None) inline static
Definition at line 2799 of file Convert.cs.
    {
        if (options < Base64FormattingOptions.None || options > Base64FormattingOptions.InsertLineBreaks)
        {
            throw new ArgumentException(SR.Format(SR.Arg_EnumIllegalVal, (int)options), "options");
        }
        if (bytes.Length == 0)
        {
            charsWritten = 0;
            return true;
        }
        bool insertLineBreaks = options == Base64FormattingOptions.InsertLineBreaks;
        int num = ToBase64_CalculateAndValidateOutputLength(bytes.Length, insertLineBreaks);
        if (num > chars.Length)
        {
            charsWritten = 0;
            return false;
        }
        fixed (char* outChars = &MemoryMarshal.GetReference(chars))
        {
            fixed (byte* inData = &MemoryMarshal.GetReference(bytes))
            {
                charsWritten = ConvertToBase64Array(outChars, inData, 0, bytes.Length, insertLineBreaks);
                return true;
            }
        }
    }
References System.SR.Arg_EnumIllegalVal, System.bytes, System.chars, System.Convert.ConvertToBase64Array(), System.SR.Format(), System.options, and System.Convert.ToBase64_CalculateAndValidateOutputLength().
Referenced by System.Security.Cryptography.PemEncoding.TryWrite(), and System.Security.Cryptography.XmlKeyHelper.WriteCryptoBinary().