Terraria: System.Convert.ToUInt32
ToUInt32() [10/19]
static uint System.Convert.ToUInt32 (object? value) inline static
Definition at line 1470 of file Convert.cs.
    {
        if (value != null)
        {
            return ((IConvertible)value).ToUInt32(null);
        }
        return 0u;
    }
References System.value.
Referenced by ReLogic.OS.Windows.NativeMethods.FlashInfo.CreateStart(), ReLogic.OS.Windows.NativeMethods.FlashInfo.CreateStop(), System.Data.BinaryNode.EvalBinaryOp(), System.ComponentModel.UInt32Converter.FromString(), System.Convert.ToUInt32(), System.Boolean.ToUInt32(), System.Byte.ToUInt32(), System.Char.ToUInt32(), System.Decimal.ToUInt32(), System.Double.ToUInt32(), System.Enum.ToUInt32(), System.Int16.ToUInt32(), System.Int32.ToUInt32(), System.Int64.ToUInt32(), System.SByte.ToUInt32(), System.Single.ToUInt32(), System.String.ToUInt32(), System.UInt16.ToUInt32(), System.UInt64.ToUInt32(), System.Convert.ToUInt32(), System.Runtime.Serialization.FormatterConverter.ToUInt32(), System.Runtime.Serialization.Formatter.WriteMember(), and System.Runtime.Serialization.Formatters.Binary.BinaryFormatterWriter.WriteValue().