Terraria: System.Text.StringBuilder.Insert
Insert() [17/20]
unsafe StringBuilder System.Text.StringBuilder.Insert (int index, string? value, int count) inline
Definition at line 1017 of file StringBuilder.cs.
    {
        if (count < 0)
        {
            throw new ArgumentOutOfRangeException("count", SR.ArgumentOutOfRange_NeedNonNegNum);
        }
        int length = Length;
        if ((uint)index > (uint)length)
        {
            throw new ArgumentOutOfRangeException("index", SR.ArgumentOutOfRange_Index);
        }
        if (string.IsNullOrEmpty(value) || count == 0)
        {
            return this;
        }
        long num = (long)value.Length * (long)count;
        if (num > MaxCapacity - Length)
        {
            throw new OutOfMemoryException();
        }
        MakeRoom(index, (int)num, out var chunk, out var indexInChunk, doNotMoveFollowingChars: false);
        fixed (char* value2 = value)
        {
            while (count > 0)
            {
                ReplaceInPlaceAtChunk(ref chunk, ref indexInChunk, value2, value.Length);
                count--;
            }
            return this;
        }
    }
References System.SR.ArgumentOutOfRange_Index, System.SR.ArgumentOutOfRange_NeedNonNegNum, System.count, System.Runtime.Serialization.Dictionary, System.index, System.length, System.Text.StringBuilder.Length, System.Text.StringBuilder.MakeRoom(), System.Text.StringBuilder.MaxCapacity, System.Text.StringBuilder.ReplaceInPlaceAtChunk(), and System.value.
Referenced by System.Globalization.HebrewNumber.Append(), System.Xml.Schema.FacetsChecker.FacetsCompiler.FinishFacetCompile(), System.Xml.XmlCharacterData.InsertData(), System.Globalization.IdnMapping.PunycodeDecode(), and System.Xml.XmlCharacterData.ReplaceData().