Terraria: System.Convert.TryDecodeFromUtf16
TryDecodeFromUtf16()
static bool System.Convert.TryDecodeFromUtf16 (ReadOnlySpan< char > utf16, Span< byte > bytes, out int consumed, out int written) inline static private
Definition at line 79 of file Convert.cs.
    {
        ref char reference = ref MemoryMarshal.GetReference(utf16);
        ref byte reference2 = ref MemoryMarshal.GetReference(bytes);
        int num = utf16.Length & -4;
        int length = bytes.Length;
        int num2 = 0;
        int num3 = 0;
        if (utf16.Length != 0)
        {
            ref sbyte reference3 = ref MemoryMarshal.GetReference(DecodingMap);
            int num4 = ((length < (num >> 2) * 3) ? (length / 3 * 4) : (num - 4));
            while (true)
            {
                if (num2 < num4)
                {
                    int num5 = Decode(ref Unsafe.Add(ref reference, num2), ref reference3);
                    if (num5 >= 0)
                    {
                        WriteThreeLowOrderBytes(ref Unsafe.Add(ref reference2, num3), num5);
                        num3 += 3;
                        num2 += 4;
                        continue;
                    }
                }
                else if (num4 == num - 4 && num2 != num)
                {
                    int num6 = Unsafe.Add(ref reference, num - 4);
                    int num7 = Unsafe.Add(ref reference, num - 3);
                    int num8 = Unsafe.Add(ref reference, num - 2);
                    int num9 = Unsafe.Add(ref reference, num - 1);
                    if (((num6 | num7 | num8 | num9) & 0xFFFFFF00u) == 0L)
                    {
                        num6 = Unsafe.Add(ref reference3, num6);
                        num7 = Unsafe.Add(ref reference3, num7);
                        num6 <<= 18;
                        num7 <<= 12;
                        num6 |= num7;
                        if (num9 != 61)
{
                            num8 = Unsafe.Add(ref reference3, num8);
                            num9 = Unsafe.Add(ref reference3, num9);
                            num8 <<= 6;
                            num6 |= num9;
                            num6 |= num8;
                            if (num6 >= 0 && num3 <= length - 3)
{
                                WriteThreeLowOrderBytes(ref Unsafe.Add(ref reference2, num3), num6);
                                num3 += 3;
                                goto IL_01e6;
                            }
                        }
                        else if (num8 != 61)
{
                            num8 = Unsafe.Add(ref reference3, num8);
                            num8 <<= 6;
                            num6 |= num8;
                            if (num6 >= 0 && num3 <= length - 2)
{
                                Unsafe.Add(ref reference2, num3) = (byte)(num6 >> 16);
                                Unsafe.Add(ref reference2, num3 + 1) = (byte)(num6 >> 8);
                                num3 += 2;
                                goto IL_01e6;
                            }
                        }
                        else if (num6 >= 0 && num3 <= length - 1)
{
                            Unsafe.Add(ref reference2, num3) = (byte)(num6 >> 16);
                            num3++;
                            goto IL_01e6;
                        }
                    }
                }
                goto IL_0200;
                IL_0200:
                consumed = num2;
                written = num3;
                return false;
                IL_01e6:
                num2 += 4;
                if (num == utf16.Length)
                {
                    break;
                }
                goto IL_0200;
            }
        }
        consumed = num2;
        written = num3;
        return true;
    }
References System.bytes, System.Convert.Decode(), System.Convert.DecodingMap, System.L, System.length, System.ReadOnlySpan< T >.Length, and System.Convert.WriteThreeLowOrderBytes().
Referenced by System.Convert.TryFromBase64Chars().