Terraria: System.Text.StringBuilder.CopyTo
CopyTo() [1/2]
void System.Text.StringBuilder.CopyTo (int sourceIndex, char[] destination, int destinationIndex, int count) inline
Definition at line 962 of file StringBuilder.cs.
    {
        if (destination == null)
        {
            throw new ArgumentNullException("destination");
        }
        if (destinationIndex < 0)
        {
            throw new ArgumentOutOfRangeException("destinationIndex", SR.Format(SR.ArgumentOutOfRange_MustBeNonNegNum, "destinationIndex"));
        }
        if (destinationIndex > destination.Length - count)
        {
            throw new ArgumentException(SR.ArgumentOutOfRange_OffsetOut);
        }
        CopyTo(sourceIndex, new Span<char>(destination).Slice(destinationIndex), count);
    }
References System.SR.ArgumentOutOfRange_MustBeNonNegNum, System.SR.ArgumentOutOfRange_OffsetOut, System.Text.StringBuilder.CopyTo(), System.count, System.destination, System.destinationIndex, System.SR.Format(), and System.sourceIndex.
Referenced by System.Text.StringBuilder.CopyTo(), System.Text.StringBuilder.InternalCopy(), System.Net.IPAddressParser.IPv6AddressToString(), System.Text.StringBuilder.ToString(), and System.Globalization.TimeSpanFormat.TryFormat().