Terraria: System.Convert.ToBase64CharArray
ToBase64CharArray() [2/2]
static unsafe int System.Convert.ToBase64CharArray (byte[] inArray, int offsetIn, int length, char[] outArray, int offsetOut, Base64FormattingOptions options) inline static
Definition at line 2746 of file Convert.cs.
    {
        if (inArray == null)
        {
            throw new ArgumentNullException("inArray");
        }
        if (outArray == null)
        {
            throw new ArgumentNullException("outArray");
        }
        if (length < 0)
        {
            throw new ArgumentOutOfRangeException("length", SR.ArgumentOutOfRange_Index);
        }
        if (offsetIn < 0)
        {
            throw new ArgumentOutOfRangeException("offsetIn", SR.ArgumentOutOfRange_GenericPositive);
        }
        if (offsetOut < 0)
        {
            throw new ArgumentOutOfRangeException("offsetOut", SR.ArgumentOutOfRange_GenericPositive);
        }
        if (options < Base64FormattingOptions.None || options > Base64FormattingOptions.InsertLineBreaks)
        {
            throw new ArgumentException(SR.Format(SR.Arg_EnumIllegalVal, (int)options), "options");
        }
        int num = inArray.Length;
        if (offsetIn > num - length)
        {
            throw new ArgumentOutOfRangeException("offsetIn", SR.ArgumentOutOfRange_OffsetLength);
        }
        if (num == 0)
        {
            return 0;
        }
        bool insertLineBreaks = options == Base64FormattingOptions.InsertLineBreaks;
        int num2 = outArray.Length;
        int num3 = ToBase64_CalculateAndValidateOutputLength(length, insertLineBreaks);
        if (offsetOut > num2 - num3)
        {
            throw new ArgumentOutOfRangeException("offsetOut", SR.ArgumentOutOfRange_OffsetOut);
        }
        int result;
        fixed (char* outChars = &outArray[offsetOut])
        {
            fixed (byte* inData = &inArray[0])
            {
                result = ConvertToBase64Array(outChars, inData, offsetIn, length, insertLineBreaks);
            }
        }
        return result;
    }
References System.SR.Arg_EnumIllegalVal, System.SR.ArgumentOutOfRange_GenericPositive, System.SR.ArgumentOutOfRange_Index, System.SR.ArgumentOutOfRange_OffsetLength, System.SR.ArgumentOutOfRange_OffsetOut, System.Convert.ConvertToBase64Array(), System.SR.Format(), System.length, System.options, and System.Convert.ToBase64_CalculateAndValidateOutputLength().