Terraria: System.Convert.ToChar
ToChar() [10/18]
static char System.Convert.ToChar (object? value) inline static
Definition at line 618 of file Convert.cs.
    {
        if (value != null)
        {
            return ((IConvertible)value).ToChar(null);
        }
        return '\0';
    }
References System.value.
Referenced by System.Data.Select.Eval(), System.Runtime.Serialization.Json.XmlJsonReader.ParseChar(), System.Byte.ToChar(), System.Enum.ToChar(), System.Int16.ToChar(), System.Int32.ToChar(), System.Int64.ToChar(), System.SByte.ToChar(), System.String.ToChar(), System.UInt16.ToChar(), System.UInt32.ToChar(), System.UInt64.ToChar(), System.Convert.ToChar(), System.Convert.ToChar(), System.Runtime.Serialization.FormatterConverter.ToChar(), System.Convert.ToChar(), System.Runtime.Serialization.Formatter.WriteMember(), and System.Runtime.Serialization.Formatters.Binary.BinaryFormatterWriter.WriteValue().