Terraria: System.Convert.ToBoolean
ToBoolean() [1/18]
static bool System.Convert.ToBoolean ([NotNullWhen(true)] object? value) inline static
Definition at line 508 of file Convert.cs.
    {
        if (value != null)
        {
            return ((IConvertible)value).ToBoolean(null);
        }
        return false;
    }
References System.value.
Referenced by System.Data.ConstNode.ConstNode(), System.Data.DataTable.DataTable(), System.Data.Common.ObjectStorage.CompareWithFamilies(), System.Xml.Xsl.XsltOld.Processor.EvaluateBoolean(), System.Data.DataTable.GetObjectData(), System.Byte.ToBoolean(), System.Decimal.ToBoolean(), System.Double.ToBoolean(), System.Enum.ToBoolean(), System.Int16.ToBoolean(), System.Int32.ToBoolean(), System.Int64.ToBoolean(), System.SByte.ToBoolean(), System.Single.ToBoolean(), System.String.ToBoolean(), System.UInt16.ToBoolean(), System.UInt32.ToBoolean(), System.UInt64.ToBoolean(), System.Xml.Xsl.XsltOld.XsltCompileContext.XsltFunctionImpl.ToBoolean(), System.Runtime.Serialization.FormatterConverter.ToBoolean(), System.Runtime.Serialization.Formatter.WriteMember(), and System.Runtime.Serialization.Formatters.Binary.BinaryFormatterWriter.WriteValue().