Terraria: System.Convert.FromBase64String
FromBase64String()
static unsafe byte[] System.Convert.FromBase64String (string s) inline static
Definition at line 2904 of file Convert.cs.
    {
        if (s == null)
        {
            ThrowHelper.ThrowArgumentNullException(ExceptionArgument.s);
        }
        fixed (char* inputPtr = s)
        {
            return FromBase64CharPtr(inputPtr, s.Length);
        }
    }
References System.Convert.FromBase64CharPtr(), System.s, and System.ThrowHelper.ThrowArgumentNullException().
Referenced by System.Net.Mail.SmtpNegotiateAuthenticationModule.Authenticate(), System.Data.Common.SqlConvert.ChangeTypeForXML(), System.Data.Common.ObjectStorage.ConvertXmlToObject(), System.Data.Common.ObjectStorage.ConvertXmlToObject(), System.Net.NTAuthentication.GetOutgoingBlob(), System.Net.Mail.SmtpNegotiateAuthenticationModule.GetSecurityLayerOutgoingBlob(), System.Net.HttpListener.HandleAuthentication(), System.Runtime.Serialization.Formatters.Binary.ObjectReader.ParseArray(), System.Runtime.Serialization.Formatters.Binary.ObjectReader.ParseMember(), System.Runtime.Serialization.XmlReaderDelegator.ReadContentAsBase64(), System.Security.Cryptography.XmlKeyHelper.ReadCryptoBinary(), System.Data.SqlTypes.SqlBytes.ReadXml(), System.Data.SqlTypes.SqlBinary.ReadXml(), System.Xml.Schema.XmlBaseConverter.StringToBase64Binary(), System.Xml.Schema.XmlUntypedStringConverter.StringToBase64Binary(), System.Xml.Serialization.XmlCustomFormatter.ToByteArrayBase64(), System.Net.Http.Headers.ContentDispositionHeaderValue.TryDecodeMime(), System.Net.Http.Headers.ByteArrayHeaderParser.TryParseValue(), System.Xml.Schema.Datatype_base64Binary.TryParseValue(), and System.Net.WebSockets.HttpWebSocket.ValidateWebSocketHeaders().