Terraria: System.Text.StringBuilder.Replace
Replace() [3/4]
StringBuilder System.Text.StringBuilder.Replace (string oldValue, string? newValue) inline
Definition at line 1774 of file StringBuilder.cs.
    {
        return Replace(oldValue, newValue, 0, Length);
    }
References System.Text.StringBuilder.Length, and System.Text.StringBuilder.Replace().
Referenced by System.Linq.Expressions.Compiler.AssemblyGen.DefineType(), System.Text.StringBuilder.Replace(), and System.Text.StringBuilder.Replace().