Terraria: System.Text.StringBuilder.ExpandByABlock
ExpandByABlock()
void System.Text.StringBuilder.ExpandByABlock (int minBlockCharCount) inline private
Definition at line 2128 of file StringBuilder.cs.
    {
        if (minBlockCharCount + Length > m_MaxCapacity || minBlockCharCount + Length < minBlockCharCount)
        {
            throw new ArgumentOutOfRangeException("requiredLength", SR.ArgumentOutOfRange_SmallCapacity);
        }
        int num = Math.Max(minBlockCharCount, Math.Min(Length, 8000));
        if (m_ChunkOffset + m_ChunkLength + num < num)
        {
            throw new OutOfMemoryException();
        }
        char[] chunkChars = GC.AllocateUninitializedArray<char>(num);
        m_ChunkPrevious = new StringBuilder(this);
        m_ChunkOffset += m_ChunkLength;
        m_ChunkLength = 0;
        m_ChunkChars = chunkChars;
    }
References System.Text.StringBuilder.StringBuilder(), System.SR.ArgumentOutOfRange_SmallCapacity, System.Runtime.Serialization.Dictionary, System.Text.StringBuilder.Length, System.Text.StringBuilder.m_ChunkChars, System.Text.StringBuilder.m_ChunkLength, System.Text.StringBuilder.m_ChunkOffset, System.Text.StringBuilder.m_ChunkPrevious, System.Text.StringBuilder.m_MaxCapacity, System.Math.Max(), and System.Math.Min().
Referenced by System.Text.StringBuilder.Append(), System.Text.StringBuilder.Append(), and System.Text.StringBuilder.AppendCore().