Terraria: System.Text.StringBuilder.Append
Append() [20/26]
StringBuilder System.Text.StringBuilder.Append (string? value) inline
Definition at line 811 of file StringBuilder.cs.
    {
        if (value != null)
        {
            char[] chunkChars = m_ChunkChars;
            int chunkLength = m_ChunkLength;
            int length = value.Length;
            if ((uint)(chunkLength + length) < (uint)chunkChars.Length)
            {
                if (length <= 2)
                {
                    if (length > 0)
                    {
                        chunkChars[chunkLength] = value[0];
                    }
                    if (length > 1)
                    {
                        chunkChars[chunkLength + 1] = value[1];
                    }
                }
                else
                {
                    Buffer.Memmove(ref Unsafe.Add(ref MemoryMarshal.GetArrayDataReference(chunkChars), chunkLength), ref value.GetRawStringData(), (nuint)length);
                }
                m_ChunkLength = chunkLength + length;
            }
            else
            {
                AppendHelper(value);
            }
        }
        return this;
    }
References System.Text.StringBuilder.AppendHelper(), System.Runtime.Serialization.Dictionary, System.Runtime.InteropServices.MemoryMarshal.GetArrayDataReference(), System.length, System.Text.StringBuilder.m_ChunkChars, System.Text.StringBuilder.m_ChunkLength, System.Buffer.Memmove(), and System.value.