Terraria: System.Convert.ToDouble
ToDouble() [10/18]
static double System.Convert.ToDouble (object? value) inline static
Definition at line 1991 of file Convert.cs.
    {
        if (value != null)
        {
            return ((IConvertible)value).ToDouble(null);
        }
        return 0.0;
    }
References System.value.
Referenced by System.Data.ConstNode.ConstNode(), System.Data.BinaryNode.BinaryCompare(), System.Data.Common.ObjectStorage.CompareWithFamilies(), System.Data.BinaryNode.EvalBinaryOp(), System.Data.FunctionNode.EvalFunction(), System.ComponentModel.DoubleConverter.FromString(), System.ComponentModel.DataAnnotations.RangeAttribute.SetupConversion(), System.Boolean.ToDouble(), System.Byte.ToDouble(), System.Enum.ToDouble(), System.Int16.ToDouble(), System.Int32.ToDouble(), System.Int64.ToDouble(), System.SByte.ToDouble(), System.Single.ToDouble(), System.String.ToDouble(), System.UInt16.ToDouble(), System.UInt32.ToDouble(), System.UInt64.ToDouble(), System.Runtime.Serialization.FormatterConverter.ToDouble(), System.Xml.XmlConvert.ToXPathDouble(), System.Runtime.Serialization.Formatter.WriteMember(), and System.Runtime.Serialization.Formatters.Binary.BinaryFormatterWriter.WriteValue().