Terraria: System.Text.StringBuilder.AppendLine
AppendLine() [1/4]
StringBuilder System.Text.StringBuilder.AppendLine () inline
Definition at line 951 of file StringBuilder.cs.
    {
        return Append(Environment.NewLine);
    }
References System.Text.StringBuilder.Append(), and System.Environment.NewLine.
Referenced by System.Diagnostics.Tracing.ManifestBuilder.ManifestBuilder(), System.Diagnostics.Tracing.ManifestBuilder.AddEventParameter(), System.Text.StringBuilder.AppendLine(), Internal.Cryptography.Pal.CertificatePal.AppendPrivateKeyInfo(), System.Diagnostics.Tracing.ManifestBuilder.CreateManifestString(), System.Net.Http.Headers.HeaderUtilities.DumpHeaders(), System.Linq.Expressions.Interpreter.LightLambda.DebugViewPrinter.EmitExits(), System.Diagnostics.Tracing.ManifestBuilder.EndEvent(), System.Runtime.CompilerServices.AsyncMethodBuilderCore.GetAsyncStateMachineDescription(), System.Diagnostics.FileVersionInfo.ToString(), System.Net.Http.HttpResponseMessage.ToString(), System.Diagnostics.StackFrame.ToString(), System.Reflection.Emit.MethodBuilder.ToString(), System.Reflection.Emit.SignatureHelper.ToString(), and System.Diagnostics.StackTrace.ToString().