Terraria: System.Text.StringBuilder.ToString
ToString() [1/2]
override string System.Text.StringBuilder.ToString () inline
Definition at line 679 of file StringBuilder.cs.
    {
        if (Length == 0)
        {
            return string.Empty;
        }
        string text = string.FastAllocateString(Length);
        StringBuilder stringBuilder = this;
        do
        {
            if (stringBuilder.m_ChunkLength > 0)
            {
                char[] chunkChars = stringBuilder.m_ChunkChars;
                int chunkOffset = stringBuilder.m_ChunkOffset;
                int chunkLength = stringBuilder.m_ChunkLength;
                if ((uint)(chunkLength + chunkOffset) > (uint)text.Length || (uint)chunkLength > (uint)chunkChars.Length)
                {
                    throw new ArgumentOutOfRangeException("chunkLength", SR.ArgumentOutOfRange_Index);
                }
                Buffer.Memmove(ref Unsafe.Add(ref text.GetRawStringData(), chunkOffset), ref MemoryMarshal.GetArrayDataReference(chunkChars), (nuint)chunkLength);
            }
            stringBuilder = stringBuilder.m_ChunkPrevious;
        }
        while (stringBuilder != null);
        return text;
    }
References System.SR.ArgumentOutOfRange_Index, System.Runtime.InteropServices.MemoryMarshal.GetArrayDataReference(), System.Text.StringBuilder.Length, System.Buffer.Memmove(), and System.text.
Referenced by System.IO.IsolatedStorage.IsolatedStorageFile.IsolatedStorageFile(), System.Xml.XmlTextReaderImpl._ParseTextAsync(), System.Xml.XmlCharacterData.AppendData(), System.Text.StringBuilder.AppendInterpolatedStringHandler.AppendFormatted< T >(), System.Text.StringBuilder.AppendInterpolatedStringHandler.AppendFormatted< T >(), System.Text.StringBuilder.AppendJoinCore< T >(), System.Xml.Xsl.XsltOld.ReaderOutput.XmlEncoder.AttributeInnerXml(), System.Xml.Xsl.XsltOld.ReaderOutput.XmlEncoder.AttributeOuterXml(), System.Data.Common.DbCommandBuilder.BuildDeleteCommand(), System.Net.Mail.MailMessage.BuildDeliveryStatusNotificationString(), System.Data.Common.DbCommandBuilder.BuildInformation(), System.Data.Common.DbCommandBuilder.BuildInsertCommand(), System.Net.HttpListenerRequestUriBuilder.BuildRequestUriUsingRawPath(), System.Data.Common.DbCommandBuilder.BuildUpdateCommand(), System.Xml.Xsl.XsltOld.StringOutput.Close(), System.Xml.Xsl.XsltOld.Compiler.CompileAvt(), System.Reflection.AssemblyNameFormatter.ComputeDisplayName(), System.StubHelpers.AsAnyMarshaler.ConvertStringBuilderToNative(), System.StubHelpers.UTF8BufferMarshaler.ConvertToNative(), System.Diagnostics.Tracing.ManifestBuilder.CreateManifestString(), System.Dynamic.Utils.DelegateHelpers.CreateObjectArrayDelegateRefEmit(), System.Linq.Expressions.Compiler.AssemblyGen.DefineType(), System.Xml.XmlCharacterData.DeleteData(), Terraria.Testing.PacketHistory.Dump(), System.Xml.Schema.XsdValidator.EndElementIdentityConstraints(), System.Security.SecurityElement.Escape(), System.Xml.Xsl.XsltOld.Avt.Evaluate(), System.Xml.Xsl.Xslt.QilGenerator.ExtractText(), System.Xml.Schema.FacetsChecker.FacetsCompiler.FinishFacetCompile(), System.Xml.XmlTextReaderImpl.FinishPartialValue(), System.Xml.XmlTextReaderImpl.FinishPartialValueAsync(), System.Xml.Xsl.Xslt.QilStrConcatenator.FlushBuilder(), ReLogic.Text.WrappedTextBuilder.NonBreakingText.GetAsWrappedText(), System.Xml.Schema.XmlSchemaValidator.GetConcatenatedValue(), System.Xml.Serialization.CodeIdentifier.GetCSharpName(), System.Net.Mime.MailBnfHelper.GetDateTimeString(), Internal.NativeCrypto.CapiHelper.GetDefaultProvider(), System.Text.StringBuilder.GetObjectData(), System.Xml.XmlTextReaderImpl.GetRemainder(), System.Xml.Serialization.SchemaObjectWriter.GetString(), System.Text.StringBuilderCache.GetStringAndRelease(), System.Net.WebClient.GetUri(), System.Xml.DtdParser.GetValue(), System.Xml.DtdParser.GetValueWithStrippedSpaces(), System.Globalization.TimeSpanFormat.FormatLiterals.Init(), System.Xml.XmlCharacterData.InsertData(), System.IO.File.InternalReadAllTextAsync(), System.Xml.XmlReader.InternalReadContentAsStringAsync(), System.Xml.Schema.XmlSchemaValidator.InternalValidateEndElement(), System.Web.Util.HttpEncoder.JavaScriptStringEncode(), System.Runtime.Versioning.VersioningHelper.MakeVersionSafeName(), System.Diagnostics.AsyncStreamReader.MoveLinesFromStringBuilderToMessageQueue(), System.Xml.XmlTextReaderImpl.ParseAttributeValueChunk(), System.Xml.XmlTextReaderImpl.ParseAttributeValueSlow(), System.Xml.XmlTextReaderImpl.ParseAttributeValueSlowAsync(), System.Xml.XmlTextReaderImpl.ParseCDataOrComment(), System.Xml.XmlTextReaderImpl.ParseCDataOrCommentAsync(), System.Xml.XmlTextReaderImpl.ParsePI(), System.Xml.XmlTextReaderImpl.ParsePIAsync(), System.Xml.XmlTextReaderImpl.ParseRootLevelWhitespace(), System.Xml.XmlTextReaderImpl.ParseRootLevelWhitespaceAsync(), System.Xml.DtdParser.ParseSubset(), System.Xml.DtdParser.ParseSubsetAsync(), System.Xml.XmlTextReaderImpl.ParseText(), System.Xml.XmlTextReaderImpl.ParseXmlDeclarationAsync(), System.Net.Mail.SmtpReplyReaderFactory.ReadLinesAsyncResult.ProcessRead(), System.Globalization.IdnMapping.PunycodeDecode(), System.Globalization.IdnMapping.PunycodeEncode(), System.Diagnostics.AsyncStreamReader.ReadBufferAsync(), System.IO.StreamReader.ReadLine(), System.IO.TextReader.ReadLine(), System.IO.StreamReader.ReadLineAsyncInternal(), System.Net.Mime.MailBnfHelper.ReadQuotedString(), System.IO.StreamReader.ReadToEnd(), System.IO.TextReader.ReadToEnd(), System.IO.TextReader.ReadToEndAsync(), System.IO.StreamReader.ReadToEndAsyncInternal(), System.Xml.XmlCharacterData.ReplaceData(), ReLogic.OS.Base.Clipboard.SanitizeClipboardText(), System.Text.DecoderFallbackBuffer.ThrowLastBytesRecursive(), System.Xml.XmlTextReaderImpl.ThrowUnclosedElements(), System.Security.IdentityHelper.ToBase32StringSuitableForDirName(), System.ComponentModel.MaskedTextProvider.ToDisplayString(), System.Xml.Xsl.Xslt.QilStrConcatenator.ToQil(), ReLogic.Text.WrappedTextBuilder.ToString(), System.Diagnostics.Activity.TagsLinkedList.ToString(), System.Diagnostics.FileVersionInfo.ToString(), System.Linq.Expressions.ExpressionStringBuilder.ToString(), System.Net.Http.HttpResponseMessage.ToString(), System.Diagnostics.StackFrame.ToString(), System.IO.StringWriter.ToString(), System.Reflection.Emit.MethodBuilder.ToString(), System.Reflection.Emit.SignatureHelper.ToString(), System.Reflection.Emit.TypeNameBuilder.ToString(), System.Reflection.SignatureConstructedGenericType.ToString(), System.Security.SecurityElement.ToString(), System.Number.NumberBuffer.ToString(), MS.Internal.Xml.Cache.XPathNodeInfoAtom.ToString(), MS.Internal.Xml.Cache.XPathNodeInfoTable.ToString(), System.Reflection.Metadata.SignatureHeader.ToString(), System.Web.HttpUtility.HttpQSCollection.ToString(), Terraria.Utilities.Vertical64BitStrips.ToString(), System.ComponentModel.MaskedTextProvider.ToString(), System.Numerics.Vector2.ToString(), System.Numerics.Vector3.ToString(), System.Numerics.Vector4.ToString(), System.Tuple< T1, T2, T3, T4, T5, T6, T7, TRest >.ToString(), System.Diagnostics.Debug.AssertInterpolatedStringHandler.ToStringAndClear(), System.Reflection.Internal.PooledStringBuilder.ToStringAndFree(), System.Globalization.TextInfo.ToTitleCase(), System.Security.Cryptography.DSA.ToXmlString(), System.Security.Cryptography.RSA.ToXmlString(), System.Xml.XmlWellFormedWriter.AttributeValueCache.Trim(), System.Security.SecurityElement.Unescape(), System.Web.Util.HttpEncoder.UrlEncodeUnicode(), System.Xml.Schema.DtdValidator.ValidateEndElement(), System.Xml.Schema.XdrValidator.ValidateEndElement(), System.Xml.Schema.XsdValidator.ValidateEndElement(), System.Diagnostics.XmlWriterTraceListener.WriteData(), and System.Diagnostics.DelimitedListTraceListener.WriteEscaped().