Terraria: System.Text.StringBuilder.Append
Append() [6/26]
StringBuilder System.Text.StringBuilder.Append (char value, int repeatCount) inline
Definition at line 744 of file StringBuilder.cs.
    {
        if (repeatCount < 0)
        {
            throw new ArgumentOutOfRangeException("repeatCount", SR.ArgumentOutOfRange_NegativeCount);
        }
        if (repeatCount == 0)
        {
            return this;
        }
        int num = Length + repeatCount;
        if (num > m_MaxCapacity || num < repeatCount)
        {
            throw new ArgumentOutOfRangeException("repeatCount", SR.ArgumentOutOfRange_LengthGreaterThanCapacity);
        }
        int num2 = m_ChunkLength;
        while (repeatCount > 0)
        {
            if (num2 < m_ChunkChars.Length)
            {
                m_ChunkChars[num2++] = value;
                repeatCount--;
            }
            else
            {
                m_ChunkLength = num2;
                ExpandByABlock(repeatCount);
                num2 = 0;
            }
        }
        m_ChunkLength = num2;
        return this;
    }
References System.SR.ArgumentOutOfRange_LengthGreaterThanCapacity, System.SR.ArgumentOutOfRange_NegativeCount, System.Runtime.Serialization.Dictionary, System.Text.StringBuilder.ExpandByABlock(), System.Text.StringBuilder.Length, System.Text.StringBuilder.m_ChunkChars, System.Text.StringBuilder.m_ChunkLength, System.Text.StringBuilder.m_MaxCapacity, and System.value.
Referenced by System.IO.IsolatedStorage.IsolatedStorageFile.IsolatedStorageFile(), System.Xml.XmlTextReaderImpl._ParseTextAsync(), System.Reflection.Emit.TypeNameBuilder.AddArray(), System.Text.RegularExpressions.RegexCharClass.AddCategory(), System.Text.RegularExpressions.RegexCharClass.AddCharClass(), System.Diagnostics.Tracing.ManifestBuilder.AddEventParameter(), System.Net.Http.Headers.NameValueHeaderValue.AddToStringBuilder(), System.Text.StringBuilder.Append(), System.Reflection.Emit.TypeNameBuilder.Append(), System.Text.StringBuilder.Append(), System.Xml.Xsl.Xslt.QilStrConcatenator.Append(), System.Text.StringBuilder.Append(), System.Text.StringBuilder.Append(), ReLogic.Text.WrappedTextBuilder.Append(), System.Text.StringBuilder.Append(), System.Xml.Xsl.Xslt.QilStrConcatenator.Append(), System.Text.StringBuilder.Append(), System.Text.StringBuilder.Append(), System.Reflection.Emit.TypeNameBuilder.Append(), System.Xml.Xsl.Xslt.QilStrConcatenator.Append(), System.Text.StringBuilder.Append(), System.Globalization.HebrewNumber.Append(), System.DateTimeFormat.Append2DigitNumber(), System.Web.Util.HttpEncoder.AppendCharAsUnicodeJavaScript(), System.Text.StringBuilder.AppendCore(), System.Text.StringBuilder.AppendInterpolatedStringHandler.AppendCustomFormatter< T >(), System.Xml.XmlCharacterData.AppendData(), System.Text.StringBuilder.AppendFormatHelper(), System.Text.StringBuilder.AppendInterpolatedStringHandler.AppendFormatted(), System.Text.StringBuilder.AppendInterpolatedStringHandler.AppendFormatted(), System.Text.StringBuilder.AppendInterpolatedStringHandler.AppendFormatted(), System.Text.StringBuilder.AppendInterpolatedStringHandler.AppendFormatted< T >(), System.Text.StringBuilder.AppendInterpolatedStringHandler.AppendFormatted< T >(), System.Text.StringBuilder.AppendInterpolatedStringHandler.AppendFormatted< T >(), System.Text.StringBuilder.AppendHelper(), System.Text.StringBuilder.AppendJoinCore< T >(), System.Text.StringBuilder.AppendJoinCore< T >(), System.Net.Http.StringBuilderExtensions.AppendKeyValue(), System.Diagnostics.Tracing.ManifestBuilder.AppendKeywords(), System.Diagnostics.Tracing.ManifestBuilder.AppendLevelName(), System.Text.StringBuilder.AppendLine(), System.Text.StringBuilder.AppendLine(), System.Text.StringBuilder.AppendInterpolatedStringHandler.AppendLiteral(), Internal.Cryptography.Pal.CertificatePal.AppendPrivateKeyInfo(), System.Reflection.AssemblyNameFormatter.AppendQuoted(), System.Text.StringBuilder.AppendSpanFormattable< T >(), System.Text.StringBuilder.AppendSpanFormattable< T >(), System.Xml.Linq.XContainer.AppendText(), System.Xml.Linq.XText.AppendText(), System.Xml.Xsl.XPath.XPathCompileException.AppendTrimmed(), System.Net.Http.Headers.CacheControlHeaderValue.AppendValueWithSeparatorIfRequired(), System.Xml.Xsl.XsltOld.ReaderOutput.XmlEncoder.AttributeOuterXml(), System.Data.Common.DbCommandBuilder.BuildDeleteCommand(), System.Net.Mail.MailMessage.BuildDeliveryStatusNotificationString(), System.Data.Common.DbCommandBuilder.BuildInformation(), System.Data.Common.DbCommandBuilder.BuildInsertCommand(), System.Net.HttpListenerRequestUriBuilder.BuildRequestUriUsingRawPath(), System.Data.Common.DbCommandBuilder.BuildUpdateCommand(), System.Data.Common.DbCommandBuilder.BuildWhereClause(), ReLogic.Text.WrappedTextBuilder.CommitWorkingLine(), System.Xml.Schema.FacetsChecker.FacetsCompiler.CompilePatternFacet(), System.Reflection.AssemblyNameFormatter.ComputeDisplayName(), System.Xml.Xsl.Runtime.NumberFormatterBase.ConvertToAlphabetic(), System.Xml.Xsl.Runtime.NumberFormatterBase.ConvertToRoman(), System.Xml.XmlTextReaderImpl.NodeData.CopyTo(), System.Diagnostics.Tracing.ManifestBuilder.CreateManifestString(), System.Dynamic.Utils.DelegateHelpers.CreateObjectArrayDelegateRefEmit(), System.Linq.Expressions.Compiler.AssemblyGen.DefineType(), Terraria.Testing.PacketHistory.Dump(), System.Net.Http.Headers.HeaderUtilities.DumpHeaders(), System.Xml.XmlTextReaderImpl.EatWhitespaces(), System.Xml.XmlTextReaderImpl.EatWhitespacesAsync(), System.Linq.Expressions.Interpreter.LightLambda.DebugViewPrinter.EmitExits(), System.Net.Mime.ContentType.Encode(), System.Net.Mime.ContentType.EncodeToBuffer(), System.Diagnostics.Tracing.ManifestBuilder.EndEvent(), System.Security.SecurityElement.Escape(), System.Xml.Serialization.CodeIdentifier.EscapeKeywords(), System.Diagnostics.DelimitedListTraceListener.EscapeMessage(), System.Reflection.Emit.TypeNameBuilder.EscapeName(), System.Xml.Xsl.XsltOld.Avt.Evaluate(), System.Xml.Xsl.Xslt.QilGenerator.ExtractText(), System.Xml.Schema.FacetsChecker.FacetsCompiler.FinishFacetCompile(), System.Xml.XmlTextReaderImpl.FinishPartialValue(), System.Xml.XmlTextReaderImpl.FinishPartialValueAsync(), System.DateTimeFormat.FormatCustomized(), System.DateTimeFormat.FormatCustomizedRoundripTimeZone(), System.DateTimeFormat.FormatCustomizedTimeZone(), System.DateTimeFormat.FormatDigits(), System.Xml.Xsl.Runtime.NumberFormatter.FormatItem(), ReLogic.Text.WrappedTextBuilder.NonBreakingText.GetAsWrappedText(), System.Runtime.Serialization.FormatterServices.GetClrTypeFullNameForNonArrayTypes(), System.Xml.Serialization.CodeIdentifier.GetCSharpName(), System.Xml.Serialization.CodeIdentifier.GetCSharpName(), System.Runtime.Serialization.DataContract.GetDataContractNameForGenericName(), System.Net.Mime.MailBnfHelper.GetDateTimeString(), System.Reflection.Metadata.Ecma335.BlobHeap.GetDocumentName(), System.Diagnostics.Tracing.DiagnosticCounter.GetMetadataString(), System.Xml.XmlTextReaderImpl.GetRemainder(), System.Net.Mime.MailBnfHelper.GetTokenOrQuotedString(), System.Net.WebClient.GetUri(), System.Globalization.TimeSpanFormat.FormatLiterals.Init(), System.ComponentModel.MaskedTextProvider.Initialize(), System.Xml.XmlCharacterData.InsertData(), System.IO.File.InternalReadAllTextAsync(), System.Xml.XmlReader.InternalReadContentAsStringAsync(), System.Net.IPAddressParser.IPv6AddressToStringHelper(), System.Web.Util.HttpEncoder.JavaScriptStringEncode(), System.Text.Json.ReadStack.JsonPath(), System.Runtime.Versioning.VersioningHelper.MakeVersionSafeName(), System.Xml.Serialization.SchemaObjectWriter.NewLine(), System.Linq.Expressions.ExpressionStringBuilder.Out(), System.Linq.Expressions.ExpressionStringBuilder.Out(), System.Xml.XmlTextReaderImpl.ParseAttributeValueChunk(), System.Xml.XmlTextReaderImpl.ParseAttributeValueSlow(), System.Xml.XmlTextReaderImpl.ParseAttributeValueSlowAsync(), System.Xml.XmlTextReaderImpl.ParseCDataOrComment(), System.Xml.XmlTextReaderImpl.ParseCDataOrCommentAsync(), System.Xml.DtdParser.ParseComment(), System.Xml.DtdParser.ParseCommentAsync(), System.Globalization.FormatProvider.Number.ParseNumber(), System.Xml.DtdParser.ParsePI(), System.Xml.DtdParser.ParsePIAsync(), System.Xml.XmlTextReaderImpl.ParsePIAsync(), System.DateTimeFormat.ParseQuoteString(), System.Net.HttpListenerRequestUriBuilder.ParseRawPath(), System.Text.RegularExpressions.RegexCharClass.ParseRecursive(), System.Xml.XmlTextReaderImpl.ParseText(), System.Xml.XmlTextReaderImpl.ParseXmlDeclarationAsync(), System.Net.FtpControlStream.PipelineCallback(), System.Xml.Schema.XsdDateTime.PrintDate(), System.Xml.Schema.XsdDateTime.PrintTime(), System.Xml.Schema.XsdDateTime.PrintZone(), System.Net.Mail.SmtpReplyReaderFactory.ReadLinesAsyncResult.ProcessRead(), System.Text.Json.WriteStack.PropertyPath(), System.Globalization.IdnMapping.PunycodeDecode(), System.Globalization.IdnMapping.PunycodeEncode(), System.Diagnostics.AsyncStreamReader.ReadBufferAsync(), System.IO.StreamReader.ReadLine(), System.IO.TextReader.ReadLine(), System.IO.StreamReader.ReadLineAsyncInternal(), System.Net.Mime.MailBnfHelper.ReadQuotedString(), System.IO.BinaryReader.ReadString(), System.IO.StreamReader.ReadToEnd(), System.IO.TextReader.ReadToEnd(), System.IO.TextReader.ReadToEndAsync(), System.IO.StreamReader.ReadToEndAsyncInternal(), ReLogic.OS.Base.Clipboard.SanitizeClipboardText(), System.Xml.DtdParser.SaveParsingBuffer(), System.Xml.Schema.XmlSchemaValidator.SaveTextValue(), System.Xml.Schema.BaseValidator.SaveTextValue(), System.Xml.DtdParser.ScanLiteral(), System.Xml.DtdParser.ScanLiteralAsync(), System.Xml.XmlWellFormedWriter.AttributeValueCache.StartComplexValue(), System.Diagnostics.Tracing.ManifestBuilder.StartEvent(), System.Text.DecoderExceptionFallbackBuffer.Throw(), System.Text.DecoderFallbackBuffer.ThrowLastBytesRecursive(), System.Xml.XmlTextReaderImpl.ThrowUnclosedElements(), System.Security.IdentityHelper.ToBase32StringSuitableForDirName(), System.Diagnostics.Activity.TagsLinkedList.ToString(), System.Diagnostics.FileVersionInfo.ToString(), System.Net.Http.Headers.AltSvcHeaderValue.ToString(), System.Net.Http.Headers.ContentRangeHeaderValue.ToString(), System.Net.Http.Headers.ViaHeaderValue.ToString(), System.Net.Http.Headers.WarningHeaderValue.ToString(), System.Net.Http.HttpResponseMessage.ToString(), System.Diagnostics.StackFrame.ToString(), System.Reflection.Emit.MethodBuilder.ToString(), System.Reflection.Emit.SignatureHelper.ToString(), System.Reflection.SignatureConstructedGenericType.ToString(), System.Security.SecurityElement.ToString(), System.Number.NumberBuffer.ToString(), MS.Internal.Xml.Cache.XPathNodeInfoAtom.ToString(), MS.Internal.Xml.Cache.XPathNodeInfoTable.ToString(), System.Reflection.Metadata.SignatureHeader.ToString(), System.Web.HttpUtility.HttpQSCollection.ToString(), Terraria.Utilities.Vertical64BitStrips.ToString(), System.Numerics.Vector2.ToString(), System.Numerics.Vector3.ToString(), System.Numerics.Vector4.ToString(), System.Net.Cookie.ToString(), System.Tuple< T1, T2, T3, T4, T5, T6, T7, TRest >.ToString(), System.Diagnostics.StackTrace.ToString(), System.Globalization.TextInfo.ToTitleCase(), System.Security.Cryptography.DSA.ToXmlString(), System.Security.Cryptography.RSA.ToXmlString(), System.DateTimeParse.TryParseQuoteString(), System.Security.SecurityElement.Unescape(), System.Web.Util.HttpEncoder.UrlEncodeUnicode(), System.Xml.Xsl.XsltOld.StringOutput.Write(), System.IO.StringWriter.Write(), System.Xml.XmlTextEncoder.Write(), System.IO.StringWriter.Write(), System.IO.StringWriter.Write(), System.Xml.Xsl.XsltOld.StringOutput.Write(), System.Xml.XmlTextEncoder.Write(), System.IO.StringWriter.Write(), System.IO.StringWriter.Write(), System.Xml.Serialization.SchemaObjectWriter.Write12_XmlSchemaSimpleTypeUnion(), System.Xml.BinXmlDateTime.Write2Dig(), System.Xml.BinXmlDateTime.Write3Dec(), System.Xml.BinXmlDateTime.Write4DigNeg(), System.IO.StringWriter.WriteAsync(), System.Xml.Serialization.SchemaObjectWriter.WriteAttribute(), System.Xml.XmlTextEncoder.WriteCharEntity(), System.Xml.XmlWellFormedWriter.AttributeValueCache.WriteCharEntity(), System.Xml.XmlWellFormedWriter.AttributeValueCache.WriteChars(), System.Runtime.Serialization.XPathQueryGenerator.ExportContext.WriteChildToContext(), System.Security.Cryptography.XmlKeyHelper.WriteCryptoBinary(), System.Xml.BinXmlDateTime.WriteDate(), System.Xml.Serialization.SchemaObjectWriter.WriteEndElement(), System.Xml.XmlTextEncoder.WriteEntityRef(), System.Xml.XmlWellFormedWriter.AttributeValueCache.WriteEntityRef(), System.Diagnostics.DelimitedListTraceListener.WriteEscaped(), System.Xml.Serialization.SchemaObjectWriter.WriteIndent(), System.IO.StringWriter.WriteLine(), System.IO.StringWriter.WriteLine(), System.IO.StringWriter.WriteLineAsync(), System.Xml.XmlTextEncoder.WriteRaw(), System.Xml.XmlWellFormedWriter.AttributeValueCache.WriteRaw(), System.Xml.XmlWellFormedWriter.AttributeValueCache.WriteRaw(), System.Xml.XmlTextEncoder.WriteRawWithSurrogateChecking(), System.Xml.Serialization.SchemaObjectWriter.WriteStartElement(), System.Xml.XmlWellFormedWriter.AttributeValueCache.WriteString(), System.Xml.XmlTextEncoder.WriteSurrogateCharEntity(), System.Xml.XmlWellFormedWriter.AttributeValueCache.WriteSurrogateCharEntity(), System.Xml.BinXmlDateTime.WriteTime(), System.Xml.BinXmlDateTime.WriteTimeFullPrecision(), System.Xml.BinXmlDateTime.WriteTimeZone(), System.Xml.XmlWellFormedWriter.AttributeValueCache.WriteValue(), and System.Xml.XmlWellFormedWriter.AttributeValueCache.WriteWhitespace().