Terraria: System.Text.StringBuilder.Replace
Replace() [4/4]
StringBuilder System.Text.StringBuilder.Replace (string oldValue, string? newValue, int startIndex, int count) inline
Definition at line 1855 of file StringBuilder.cs.
    {
        int length = Length;
        if ((uint)startIndex > (uint)length)
        {
            throw new ArgumentOutOfRangeException("startIndex", SR.ArgumentOutOfRange_Index);
        }
        if (count < 0 || startIndex > length - count)
        {
            throw new ArgumentOutOfRangeException("count", SR.ArgumentOutOfRange_Index);
        }
        if (oldValue == null)
        {
            throw new ArgumentNullException("oldValue");
        }
        if (oldValue.Length == 0)
        {
            throw new ArgumentException(SR.Argument_EmptyName, "oldValue");
        }
        if (newValue == null)
        {
            newValue = string.Empty;
        }
        int[] array = null;
        int num = 0;
        StringBuilder stringBuilder = FindChunkForIndex(startIndex);
        int num2 = startIndex - stringBuilder.m_ChunkOffset;
        while (count > 0)
        {
            if (StartsWith(stringBuilder, num2, count, oldValue))
            {
                if (array == null)
                {
                    array = new int[5];
                }
                else if (num >= array.Length)
                {
                    Array.Resize(ref array, array.Length * 3 / 2 + 4);
                }
                array[num++] = num2;
                num2 += oldValue.Length;
                count -= oldValue.Length;
            }
            else
            {
                num2++;
                count--;
            }
            if (num2 >= stringBuilder.m_ChunkLength || count == 0)
            {
                int num3 = num2 + stringBuilder.m_ChunkOffset;
                ReplaceAllInChunk(array, num, stringBuilder, oldValue.Length, newValue);
                num3 += (newValue.Length - oldValue.Length) * num;
                num = 0;
                stringBuilder = FindChunkForIndex(num3);
                num2 = num3 - stringBuilder.m_ChunkOffset;
            }
        }
        return this;
    }
References System.SR.Argument_EmptyName, System.SR.ArgumentOutOfRange_Index, System.array, System.count, System.Runtime.Serialization.Dictionary, System.Text.StringBuilder.FindChunkForIndex(), System.length, System.Text.StringBuilder.Length, System.Text.StringBuilder.ReplaceAllInChunk(), System.startIndex, and System.Text.StringBuilder.StartsWith().