Terraria: System.Convert.ToDecimal
ToDecimal() [10/18]
static decimal System.Convert.ToDecimal (object? value) inline static
Definition at line 2101 of file Convert.cs.
    {
        if (value != null)
        {
            return ((IConvertible)value).ToDecimal(null);
        }
        return 0m;
    }
References System.value.
Referenced by System.Data.BinaryNode.BinaryCompare(), System.Linq.Expressions.Compiler.LambdaCompiler.ConvertSwitchValue(), System.Data.BinaryNode.EvalBinaryOp(), System.ComponentModel.DecimalConverter.FromString(), System.Xml.Schema.TypedObject.SetDecimal(), System.Boolean.ToDecimal(), System.Byte.ToDecimal(), System.Double.ToDecimal(), System.Enum.ToDecimal(), System.Int16.ToDecimal(), System.Int32.ToDecimal(), System.Int64.ToDecimal(), System.SByte.ToDecimal(), System.Single.ToDecimal(), System.String.ToDecimal(), System.UInt16.ToDecimal(), System.UInt32.ToDecimal(), System.UInt64.ToDecimal(), System.Runtime.Serialization.FormatterConverter.ToDecimal(), System.Runtime.Serialization.Formatter.WriteMember(), and System.Runtime.Serialization.Formatters.Binary.BinaryFormatterWriter.WriteValue().