Terraria: System.Convert.ToSingle
ToSingle() [10/18]
static float System.Convert.ToSingle (object? value) inline static
Definition at line 1881 of file Convert.cs.
    {
        if (value != null)
        {
            return ((IConvertible)value).ToSingle(null);
        }
        return 0f;
    }
References System.value.
Referenced by System.Data.BinaryNode.BinaryCompare(), System.Data.BinaryNode.EvalBinaryOp(), System.ComponentModel.SingleConverter.FromString(), System.Boolean.ToSingle(), System.Byte.ToSingle(), System.Double.ToSingle(), System.Enum.ToSingle(), System.Int16.ToSingle(), System.Int32.ToSingle(), System.Int64.ToSingle(), System.SByte.ToSingle(), System.String.ToSingle(), System.UInt16.ToSingle(), System.UInt32.ToSingle(), System.UInt64.ToSingle(), System.Runtime.Serialization.FormatterConverter.ToSingle(), System.Runtime.Serialization.Formatter.WriteMember(), and System.Runtime.Serialization.Formatters.Binary.BinaryFormatterWriter.WriteValue().