Terraria: System.Convert.ToString
ToString() [22/36]
static ? string System.Convert.ToString (object? value) inline static
Definition at line 2321 of file Convert.cs.
    {
        return ToString(value, null);
    }
References System.ToString, and System.value.
Referenced by System.Data.XmlTreeGen.AddExtendedProperties(), System.Data.BinaryNode.BinaryCompare(), MS.Internal.Xml.XPath.XPathComparerHelper.Compare(), System.Data.Common.DbConnectionStringBuilder.ConvertValueToString(), System.Data.BinaryNode.EvalBinaryOp(), System.Data.FunctionNode.EvalFunction(), System.Data.XmlTreeGen.GetSchema(), System.Web.HttpUtility.HtmlEncode(), System.ComponentModel.DataAnnotations.RegularExpressionAttribute.IsValid(), System.Data.ExceptionBuilder.KeysToString(), System.Xml.Serialization.XmlReflectionImporter.ReconcileAccessor(), System.Data.ExceptionBuilder.RelationOutOfRange(), System.Runtime.Serialization.FormatterConverter.ToString(), System.Xml.XmlConvert.ToXPathString(), System.Data.ExceptionBuilder.UniqueConstraintViolationText(), and System.Xml.Serialization.XmlSerializationWriterCodeGen.WriteValue().