Terraria: System.Convert.ThrowInt16OverflowException
ThrowInt16OverflowException()
static void System.Convert.ThrowInt16OverflowException () inline static private
Definition at line 473 of file Convert.cs.
    {
        throw new OverflowException(SR.Overflow_Int16);
    }
References System.SR.Overflow_Int16.
Referenced by System.Convert.ToInt16(), System.Convert.ToInt16(), System.Convert.ToInt16(), System.Convert.ToInt16(), System.Convert.ToInt16(), System.Convert.ToInt16(), and System.Convert.ToInt16().