Terraria: System.Convert.ChangeType
ChangeType() [3/4]
static ? object System.Convert.ChangeType (object? value, TypeCode typeCode) inline static
Definition at line 229 of file Convert.cs.
    {
        return ChangeType(value, typeCode, CultureInfo.CurrentCulture);
    }
References System.Convert.ChangeType(), System.Globalization.CultureInfo.CurrentCulture, and System.value.
Referenced by System.ComponentModel.DefaultValueAttribute.DefaultValueAttribute(), System.Convert.ChangeType(), System.Convert.ChangeType(), System.Data.Common.SqlConvert.ChangeType2(), System.Xml.Xsl.Runtime.XmlQueryRuntime.ChangeTypeXsltArgument(), System.Runtime.Serialization.FormatterConverter.Convert(), System.Runtime.Serialization.FormatterConverter.Convert(), System.ComponentModel.BaseNumberConverter.ConvertTo(), Terraria.ID.SetFactory.CreateCustomSet< T >(), System.Data.BinaryNode.EvalBinaryOp(), System.Runtime.Serialization.Formatters.Binary.Converter.FromString(), Terraria.IO.Preferences.Get< T >(), System.ComponentModel.DataAnnotations.EnumDataTypeAttribute.GetUnderlyingTypeValueString(), System.Data.XSDSchema.HandleElementColumn(), System.Data.XSDSchema.HandleSimpleContentColumn(), System.Data.XSDSchema.HandleSimpleTypeSimpleContentColumn(), System.Runtime.Serialization.CodeGenerator.Ldc(), System.Xml.Serialization.CodeGenerator.Ldc(), System.Data.XmlDataLoader.LoadTable(), System.Data.XMLDiffLoader.ReadOldRowData(), System.Xml.Xsl.XsltOld.XsltCompileContext.XsltFunctionImpl.ToNumeric(), System.ComponentModel.DataAnnotations.CustomValidationAttribute.TryConvertValue(), Terraria.Social.Base.AWorkshopEntry.TryGet< T >(), System.Enum.TryParseRareEnum(), System.Xml.Serialization.XmlSerializationWriterILGen.WriteCheckDefault(), and System.Xml.Serialization.XmlSerializationWriterCodeGen.WriteCheckDefault().