Terraria: System.Convert.ToInt64
ToInt64() [10/19]
static long System.Convert.ToInt64 (object? value) inline static
Definition at line 1623 of file Convert.cs.
    {
        if (value != null)
        {
            return ((IConvertible)value).ToInt64(null);
        }
        return 0L;
    }
References System.L, and System.value.
Referenced by Extensions.EnumerationExtensions._Value._Value(), System.DateTime.DateTime(), System.Diagnostics.Tracing.ManifestBuilder.CreateManifestString(), System.Diagnostics.Tracing.EventProvider.EncodeObject(), System.Data.BinaryNode.EvalBinaryOp(), Terraria.Lang.FillNameCacheArray< IdClass, IdType >(), System.ComponentModel.Int64Converter.FromString(), System.Net.FtpControlStream.GetContentLengthFrom213Response(), System.ComponentModel.EnumConverter.GetEnumValue(), Extensions.EnumerationExtensions.Has< T >(), System.Runtime.Serialization.EnumDataContract.EnumDataContractCriticalHelper.ImportDataMembers(), Extensions.EnumerationExtensions.Include< T >(), Extensions.EnumerationExtensions.Remove< T >(), System.Data.AutoIncrementInt64.SetCurrent(), System.Net.HttpListenerTimeoutManager.SetTimespanTimeout(), System.Convert.ToInt64(), System.Boolean.ToInt64(), System.Byte.ToInt64(), System.Char.ToInt64(), System.Decimal.ToInt64(), System.Double.ToInt64(), System.Enum.ToInt64(), System.Int16.ToInt64(), System.Int32.ToInt64(), System.SByte.ToInt64(), System.Single.ToInt64(), System.String.ToInt64(), System.UInt16.ToInt64(), System.UInt32.ToInt64(), System.UInt64.ToInt64(), System.Runtime.Serialization.FormatterConverter.ToInt64(), System.Formats.Asn1.AsnWriter.WriteEnumeratedValue(), System.Xml.Serialization.ReflectionXmlSerializationWriter.WriteEnumMethod(), System.Runtime.Serialization.EnumDataContract.WriteEnumValue(), System.Runtime.Serialization.Json.JsonEnumDataContract.WriteJsonValueCore(), System.Runtime.Serialization.Formatter.WriteMember(), System.Formats.Asn1.AsnWriter.WriteNamedBitList(), and System.Runtime.Serialization.Formatters.Binary.BinaryFormatterWriter.WriteValue().