Terraria: System.Text.StringBuilder.Remove
Remove() [2/2]
StringBuilder System.Text.StringBuilder.Remove (int startIndex, int length) inline
Definition at line 1049 of file StringBuilder.cs.
    {
        if (length < 0)
        {
            throw new ArgumentOutOfRangeException("length", SR.ArgumentOutOfRange_NegativeLength);
        }
        if (startIndex < 0)
        {
            throw new ArgumentOutOfRangeException("startIndex", SR.ArgumentOutOfRange_StartIndex);
        }
        if (length > Length - startIndex)
        {
            throw new ArgumentOutOfRangeException("length", SR.ArgumentOutOfRange_Index);
        }
        if (Length == length && startIndex == 0)
        {
            Length = 0;
            return this;
        }
        if (length > 0)
        {
            Remove(startIndex, length, out var _, out var _);
        }
        return this;
    }
References System.SR.ArgumentOutOfRange_Index, System.SR.ArgumentOutOfRange_NegativeLength, System.SR.ArgumentOutOfRange_StartIndex, System.length, System.Text.StringBuilder.Length, System.ComponentModel.Remove, and System.startIndex.
Referenced by System.Reflection.Emit.TypeNameBuilder.CloseGenericArguments(), System.Xml.XmlCharacterData.DeleteData(), System.DateTimeFormat.FormatCustomized(), System.Diagnostics.AsyncStreamReader.MoveLinesFromStringBuilderToMessageQueue(), System.Reflection.Emit.TypeNameBuilder.PopOpenGenericArgument(), System.Globalization.IdnMapping.PunycodeEncode(), and System.Xml.XmlCharacterData.ReplaceData().