Terraria: System.Convert.ThrowUInt16OverflowException
ThrowUInt16OverflowException()
static void System.Convert.ThrowUInt16OverflowException () inline static private
Definition at line 479 of file Convert.cs.
    {
        throw new OverflowException(SR.Overflow_UInt16);
    }
References System.SR.Overflow_UInt16.
Referenced by System.Convert.ToUInt16(), System.Convert.ToUInt16(), System.Convert.ToUInt16(), System.Convert.ToUInt16(), and System.Convert.ToUInt16().