Terraria: System.Convert.ThrowByteOverflowException
ThrowByteOverflowException()
static void System.Convert.ThrowByteOverflowException () inline static private
Definition at line 461 of file Convert.cs.
    {
        throw new OverflowException(SR.Overflow_Byte);
    }
References System.SR.Overflow_Byte.
Referenced by System.Convert.ToByte(), System.Convert.ToByte(), System.Convert.ToByte(), System.Convert.ToByte(), System.Convert.ToByte(), System.Convert.ToByte(), and System.Convert.ToByte().