Terraria: System.Convert.ToBase64String
ToBase64String() [1/5]
static string System.Convert.ToBase64String (byte[] inArray) inline static
Definition at line 2675 of file Convert.cs.
    {
        if (inArray == null)
        {
            throw new ArgumentNullException("inArray");
        }
        return ToBase64String(new ReadOnlySpan<byte>(inArray));
    }
References System.Convert.ToBase64String().
Referenced by System.Net.WebSockets.WebSocketProtocolComponent.WebSocketProtocolComponent(), System.Net.Mail.SmtpLoginAuthenticationModule.Authenticate(), System.Net.Mail.SmtpNegotiateAuthenticationModule.Authenticate(), System.Xml.Schema.XmlBaseConverter.Base64BinaryToString(), System.Data.Common.SqlConvert.ChangeTypeForXML(), System.Data.Common.ObjectStorage.ConvertObjectToXml(), System.Net.WebSockets.WebSocketHandle.CreateSecKeyAndSecWebSocketAccept(), System.Net.Http.Headers.ContentDispositionHeaderValue.EncodeMime(), System.Net.NTAuthentication.GetOutgoingBlob(), System.Net.Mail.SmtpNegotiateAuthenticationModule.GetSecurityLayerOutgoingBlob(), System.Net.WebSockets.HttpWebSocket.GetSecWebSocketAcceptString(), System.Net.HttpListener.HandleAuthentication(), System.Net.Http.AuthenticationHelper.SetBasicAuthToken(), System.Convert.ToBase64String(), System.Convert.ToBase64String(), System.Convert.ToBase64String(), System.Convert.ToBase64String(), System.Net.Http.Headers.ByteArrayHeaderParser.ToString(), System.Xml.XmlSqlBinaryReader.ValueAsString(), System.Data.SqlTypes.SqlBinary.WriteXml(), and System.Data.SqlTypes.SqlBytes.WriteXml().