Terraria: System.Convert.ToUInt64
ToUInt64() [10/19]
static ulong System.Convert.ToUInt64 (object? value) inline static
Definition at line 1738 of file Convert.cs.
    {
        if (value != null)
        {
            return ((IConvertible)value).ToUInt64(null);
        }
        return 0uL;
    }
References System.value.
Referenced by Extensions.EnumerationExtensions._Value._Value(), System.DateTime.DateTime(), System.Data.BinaryNode.EvalBinaryOp(), System.ComponentModel.UInt64Converter.FromString(), System.ComponentModel.EnumConverter.GetEnumValue(), Extensions.EnumerationExtensions.Has< T >(), System.Runtime.Serialization.EnumDataContract.EnumDataContractCriticalHelper.ImportDataMembers(), Extensions.EnumerationExtensions.Include< T >(), Extensions.EnumerationExtensions.Remove< T >(), System.Convert.ToUInt64(), System.Boolean.ToUInt64(), System.Byte.ToUInt64(), System.Char.ToUInt64(), System.Decimal.ToUInt64(), System.Double.ToUInt64(), System.Enum.ToUInt64(), System.Int16.ToUInt64(), System.Int32.ToUInt64(), System.Int64.ToUInt64(), System.SByte.ToUInt64(), System.Single.ToUInt64(), System.String.ToUInt64(), System.UInt16.ToUInt64(), System.UInt32.ToUInt64(), System.Runtime.Serialization.FormatterConverter.ToUInt64(), System.Formats.Asn1.AsnWriter.WriteEnumeratedValue(), System.Runtime.Serialization.EnumDataContract.WriteEnumValue(), System.Runtime.Serialization.Json.JsonEnumDataContract.WriteJsonValueCore(), System.Runtime.Serialization.Formatter.WriteMember(), System.Formats.Asn1.AsnWriter.WriteNamedBitList(), and System.Runtime.Serialization.Formatters.Binary.BinaryFormatterWriter.WriteValue().