Terraria: System.Convert.ThrowSByteOverflowException
ThrowSByteOverflowException()
static void System.Convert.ThrowSByteOverflowException () inline static private
Definition at line 467 of file Convert.cs.
    {
        throw new OverflowException(SR.Overflow_SByte);
    }
References System.SR.Overflow_SByte.
Referenced by System.Convert.ToSByte(), System.Convert.ToSByte(), System.Convert.ToSByte(), System.Convert.ToSByte(), System.Convert.ToSByte(), System.Convert.ToSByte(), System.Convert.ToSByte(), System.Convert.ToSByte(), and System.Convert.ToSByte().