Terraria: System.Collections.ArrayList.FixedSizeArrayList.Clone
Clone()
override object System.Collections.ArrayList.FixedSizeArrayList.Clone () inline virtual
Reimplemented from System.Collections.ArrayList.
Definition at line 1131 of file ArrayList.cs.
        {
            FixedSizeArrayList fixedSizeArrayList = new FixedSizeArrayList(_list);
            fixedSizeArrayList._list = (ArrayList)_list.Clone();
            return fixedSizeArrayList;
        }
References System.Collections.ArrayList.ArrayList(), System.Collections.ArrayList.FixedSizeArrayList.FixedSizeArrayList(), System.Collections.ArrayList.FixedSizeArrayList._list, and System.Collections.ArrayList.Clone().