Terraria: Microsoft.Xna.Framework.Graphics.TextureCollection.ResetState
ResetState()
unsafe void Microsoft.Xna.Framework.Graphics.TextureCollection.ResetState () inline package
Definition at line 151 of file TextureCollection.cs.
    {
        int num = 0;
        if (0 >= _maxTextures)
        {
            return;
        }
        while (true)
        {
            IntPtr pComPtr = (IntPtr)_parent.pComPtr;
            Helpers.CheckDisposed(_parent, pComPtr);
            if (num < 0 || num >= _maxTextures)
            {
                break;
            }
            int num2 = _textureOffset + num;
            int num3 = ((num2 < 257) ? num2 : (num2 - 241));
            uint num4 = (uint)(1 << num3);
            EffectPass activePass = _parent.activePass;
            if (activePass != null && (activePass._textureFlags & num4) != 0)
            {
                activePass.EndPass();
                _parent.activePass = null;
            }
            IDirect3DDevice9* pComPtr2 = _parent.pComPtr;
            int num5 = ((delegate* unmanaged[Stdcall, Stdcall]<IntPtr, uint, IDirect3DBaseTexture9*, int>)(int)(*(uint*)(*(int*)pComPtr2 + 260)))((nint)pComPtr2, (uint)num2, null);
            if (num5 >= 0)
            {
                StateTrackerDevice* pStateTracker = _parent.pStateTracker;
                uint num6 = ~num4;
                *(int*)((byte*)pStateTracker + 136) &= (int)num6;
                *(int*)((byte*)pStateTracker + 140) &= (int)num6;
                num++;
                if (num >= _maxTextures)
                {
                    return;
                }
                continue;
            }
            throw GraphicsHelpers.GetExceptionFromResult((uint)num5);
        }
        throw new ArgumentOutOfRangeException("index");
    }
References Microsoft.Xna.Framework.Graphics.TextureCollection._maxTextures, Microsoft.Xna.Framework.Graphics.TextureCollection._parent, Microsoft.Xna.Framework.Graphics.EffectPass._textureFlags, Microsoft.Xna.Framework.Graphics.TextureCollection._textureOffset, Microsoft.Xna.Framework.Graphics.GraphicsDevice.activePass, Microsoft.Xna.Framework.Helpers.CheckDisposed(), Microsoft.Xna.Framework.Graphics.EffectPass.EndPass(), Microsoft.Xna.Framework.Graphics.GraphicsHelpers.GetExceptionFromResult(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.pComPtr, and Microsoft.Xna.Framework.Graphics.GraphicsDevice.pStateTracker.
Referenced by Microsoft.Xna.Framework.Graphics.GraphicsDevice.Reset().