Terraria: System.Xml.Xsl.IlGen.StorageDescriptor.None
None()
static StorageDescriptor System.Xml.Xsl.IlGen.StorageDescriptor.None () inline static
Definition at line 30 of file StorageDescriptor.cs.
    {
        return default(StorageDescriptor);
    }
Referenced by System.Xml.Xsl.IlGen.XmlILVisitor.ClrCompare(), System.Xml.Xsl.IlGen.IteratorDescriptor.DiscardStack(), System.Xml.Xsl.IlGen.XmlILVisitor.EndConjunctiveTests(), System.Xml.Xsl.IlGen.XmlILVisitor.EndNestedIterator(), System.Xml.Xsl.IlGen.XmlILVisitor.EndWriterLoop(), System.Xml.Xsl.IlGen.IteratorDescriptor.LoopToEnd(), System.Xml.Xsl.IlGen.XmlILVisitor.NestedVisit(), System.Xml.Xsl.IlGen.XmlILVisitor.NestedVisitWithBranch(), System.Xml.Xsl.IlGen.XmlILVisitor.StartNestedIterator(), System.Xml.Xsl.IlGen.XmlILVisitor.StartWriterLoop(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitAttributeCtor(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitChoice(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitCommentCtor(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitConditional(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitDocumentCtor(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitElementCtor(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitError(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitFalse(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitInvoke(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitIsEmpty(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitNamespaceDecl(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitNot(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitOr(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitPICtor(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitTextCtor(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitTrue(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitWarning(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitXsltCopy(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitXsltCopyOf(), and System.Xml.Xsl.IlGen.XmlILVisitor.ZeroCompare().