Terraria: System.Xml.Xsl.IlGen.StorageDescriptor.Stack
Stack()
static StorageDescriptor System.Xml.Xsl.IlGen.StorageDescriptor.Stack (Type itemStorageType, bool isCached) inline static
Definition at line 35 of file StorageDescriptor.cs.
    {
        StorageDescriptor result = default(StorageDescriptor);
        result._location = ItemLocation.Stack;
        result._itemStorageType = itemStorageType;
        result._isCached = isCached;
        return result;
    }
References System.Xml.Dictionary, and System.Xml.Xsl.IlGen.StorageDescriptor.Stack().
Referenced by System.Xml.Xsl.IlGen.XmlILVisitor.ArithmeticOp(), System.Xml.Xsl.IlGen.XmlILVisitor.ClrCompare(), System.Xml.Xsl.IlGen.XmlILVisitor.CreateAggregator(), System.Xml.Xsl.IlGen.XmlILVisitor.EndConjunctiveTests(), System.Xml.Xsl.IlGen.IteratorDescriptor.EnsureNoCache(), System.Xml.Xsl.IlGen.XmlILVisitor.HandleDodPatterns(), System.Xml.Xsl.IlGen.XmlILVisitor.HandleFilterPatterns(), System.Xml.Xsl.IlGen.XmlILVisitor.NestedConstruction(), System.Xml.Xsl.IlGen.XmlILVisitor.Sequence(), System.Xml.Xsl.IlGen.StorageDescriptor.Stack(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitEmpty(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitError(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitFalse(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitInvoke(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitIsEmpty(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitLength(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitLiteralDecimal(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitLiteralDouble(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitLiteralInt32(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitLiteralInt64(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitLiteralQName(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitLiteralString(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitNegate(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitNodeProperty(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitNot(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitOr(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitRtfCtor(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitStrConcat(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitStrLength(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitStrParseQName(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitTrue(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitXmlContext(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitXPathNodeValue(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitXsltConvert(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitXsltGenerateId(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitXsltInvokeEarlyBound(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitXsltInvokeLateBound(), and System.Xml.Xsl.IlGen.XmlILVisitor.ZeroCompare().