Terraria: System.Linq.Expressions.ScopeWithType.Rewrite
Rewrite() [2/2]
override BlockExpression System.Linq.Expressions.ScopeWithType.Rewrite (ReadOnlyCollection< ParameterExpression > variables, Expression[] args) inline package virtual
Reimplemented from System.Linq.Expressions.ScopeN.
Definition at line 16 of file ScopeWithType.cs.
    {
        if (args == null)
        {
            Expression.ValidateVariables(variables, "variables");
            return new ScopeWithType(variables, base.Body, Type);
        }
        return new ScopeWithType(ReuseOrValidateVariables(variables), args, Type);
    }
References System.Linq.Expressions.ScopeWithType.ScopeWithType(), System.Linq.Expressions.ScopeExpression.ReuseOrValidateVariables(), and System.Linq.Expressions.Expression< TDelegate >.ValidateVariables().