Terraria: System.Runtime.Intrinsics.X86.Sse.Store
Store() [3/10]
static unsafe void System.Runtime.Intrinsics.X86.Sse.Store (float * address, Vector128< float > source) inline static inherited
Definition at line 417 of file Sse.cs.
    {
        Store(address, source);
    }
References System.source, and System.Runtime.Intrinsics.X86.Sse.Store().
Referenced by System.Numerics.Matrix4x4.Lerp(), System.Numerics.Matrix4x4.operator*(), System.Numerics.Matrix4x4.operator*(), System.Numerics.Matrix4x4.operator+(), System.Numerics.Matrix4x4.operator-(), System.Numerics.Matrix4x4.operator-(), System.Runtime.Intrinsics.X86.Sse.Store(), and System.Numerics.Matrix4x4.Transpose().