Terraria: System.Runtime.Intrinsics.X86.Sse.Multiply
Multiply() [2/4]
static Vector128< float > System.Runtime.Intrinsics.X86.Sse.Multiply (Vector128< float > left, Vector128< float > right) inline static inherited
Definition at line 322 of file Sse.cs.
    {
        return Multiply(left, right);
    }
References System.Multiply.
Referenced by System.Numerics.Matrix4x4.Invert(), System.Numerics.VectorMath.Lerp(), System.Numerics.Matrix4x4.operator*(), and System.Numerics.Matrix4x4.operator*().