Terraria: Terraria.Wiring.ToggleFirePlace
ToggleFirePlace()
static void Terraria.Wiring.ToggleFirePlace (int i, int j, Tile theBlock, bool? forcedStateWhereTrueIsOn, bool doSkipWires) inline static
Definition at line 2714 of file Wiring.cs.
    {
        int num = theBlock.frameX % 54 / 18;
        int num2 = theBlock.frameY % 36 / 18;
        int num3 = i - num;
        int num4 = j - num2;
        bool flag = Main.tile[num3, num4].frameX >= 54;
        if (forcedStateWhereTrueIsOn.HasValue && !forcedStateWhereTrueIsOn.Value == flag)
        {
            return;
        }
        int num5 = 54;
        if (Main.tile[num3, num4].frameX >= 54)
        {
            num5 = -54;
        }
        for (int k = num3; k < num3 + 3; k++)
        {
            for (int l = num4; l < num4 + 2; l++)
            {
                if (doSkipWires)
                {
                    SkipWire(k, l);
                }
                Main.tile[k, l].frameX = (short)(Main.tile[k, l].frameX + num5);
            }
        }
        NetMessage.SendTileSquare(-1, num3, num4, 3, 2);
    }
References Terraria.Tile.frameX, Terraria.NetMessage.SendTileSquare(), and Terraria.Main.tile.
Referenced by Terraria.Wiring.HitWireSingle(), and Terraria.WorldGen.TryToggleLight().