Terraria: System.Xml.Xsl.XsltOld.PrefixQName.ParseQualifiedName
ParseQualifiedName()
static void System.Xml.Xsl.XsltOld.PrefixQName.ParseQualifiedName (string qname, out string prefix, out string local) inline static
Definition at line 26 of file PrefixQName.cs.
    {
        prefix = string.Empty;
        local = string.Empty;
        int num = ValidateNames.ParseNCName(qname);
        if (num == 0)
        {
            throw XsltException.Create(System.SR.Xslt_InvalidQName, qname);
        }
        local = qname.Substring(0, num);
        if (num >= qname.Length)
        {
            return;
        }
        if (qname[num] == ':')
        {
            int startIndex = ++num;
            prefix = local;
            int num2 = ValidateNames.ParseNCName(qname, num);
            num += num2;
            if (num2 == 0)
            {
                throw XsltException.Create(System.SR.Xslt_InvalidQName, qname);
            }
            local = qname.Substring(startIndex, num2);
        }
        if (num < qname.Length)
        {
            throw XsltException.Create(System.SR.Xslt_InvalidQName, qname);
        }
    }
References System.Xml.Xsl.XsltException.Create(), System.Xml.Dictionary, System.Xml.ValidateNames.ParseNCName(), System.prefix, System.startIndex, and System.SR.Xslt_InvalidQName.
Referenced by System.Xml.Xsl.XsltOld.Compiler.CreateXmlQName(), System.Xml.Xsl.XsltOld.Compiler.CreateXPathQName(), System.Xml.Xsl.XsltOld.XsltCompileContext.ElementAvailable(), System.Xml.Xsl.XsltOld.XsltCompileContext.FunctionAvailable(), System.Xml.Xsl.XsltOld.XsltCompileContext.FuncKey.Invoke(), System.Xml.Xsl.XsltOld.ContainerAction.NameTest(), System.Xml.Xsl.XsltOld.SortAction.ParseDataType(), System.Xml.Xsl.XsltOld.XsltCompileContext.ResolveFormatName(), System.Xml.Xsl.XsltOld.PrefixQName.SetQName(), and System.Xml.Xsl.XsltOld.XsltCompileContext.SystemProperty().