Terraria: System.Xml.XmlExceptionHelper.ThrowDuplicateAttribute
ThrowDuplicateAttribute()
static void System.Xml.XmlExceptionHelper.ThrowDuplicateAttribute (XmlDictionaryReader reader, string prefix1, string prefix2, string localName, string ns) inline static
Definition at line 230 of file XmlExceptionHelper.cs.
    {
        ThrowXmlException(reader, System.SR.XmlDuplicateAttribute, GetName(prefix1, localName), GetName(prefix2, localName), ns);
    }
References System.Xml.Dictionary, System.Xml.XmlExceptionHelper.GetName(), System.Xml.XmlExceptionHelper.ThrowXmlException(), and System.SR.XmlDuplicateAttribute.
Referenced by System.Xml.XmlBaseReader.CheckAttributes(), and System.Xml.XmlBaseReader.ProcessAttributes().