Terraria: System.Xml.XmlExceptionHelper.GetWhatWasFound
GetWhatWasFound()
static string System.Xml.XmlExceptionHelper.GetWhatWasFound (XmlDictionaryReader reader) inline static private
Definition at line 59 of file XmlExceptionHelper.cs.
    {
        if (reader.EOF)
        {
            return System.SR.XmlFoundEndOfFile;
        }
        switch (reader.NodeType)
        {
        case XmlNodeType.Element:
            return System.SR.Format(System.SR.XmlFoundElement, GetName(reader.Prefix, reader.LocalName), reader.NamespaceURI);
        case XmlNodeType.EndElement:
            return System.SR.Format(System.SR.XmlFoundEndElement, GetName(reader.Prefix, reader.LocalName), reader.NamespaceURI);
        case XmlNodeType.Text:
        case XmlNodeType.Whitespace:
        case XmlNodeType.SignificantWhitespace:
            return System.SR.Format(System.SR.XmlFoundText, reader.Value);
        case XmlNodeType.Comment:
            return System.SR.Format(System.SR.XmlFoundComment, reader.Value);
        case XmlNodeType.CDATA:
            return System.SR.Format(System.SR.XmlFoundCData, reader.Value);
        default:
            return System.SR.Format(System.SR.XmlFoundNodeType, reader.NodeType);
        }
    }
References System.Xml.XmlReader.EOF, System.SR.Format(), System.Xml.XmlExceptionHelper.GetName(), System.Xml.XmlReader.LocalName, System.Xml.XmlReader.NamespaceURI, System.Xml.XmlReader.NodeType, System.Xml.XmlReader.Prefix, System.Xml.XmlReader.Value, System.SR.XmlFoundCData, System.SR.XmlFoundComment, System.SR.XmlFoundElement, System.SR.XmlFoundEndElement, System.SR.XmlFoundEndOfFile, System.SR.XmlFoundNodeType, and System.SR.XmlFoundText.
Referenced by System.Xml.XmlExceptionHelper.ThrowBase64DataExpected(), System.Xml.XmlExceptionHelper.ThrowEndElementExpected(), System.Xml.XmlExceptionHelper.ThrowFullStartElementExpected(), System.Xml.XmlExceptionHelper.ThrowFullStartElementExpected(), System.Xml.XmlExceptionHelper.ThrowFullStartElementExpected(), System.Xml.XmlExceptionHelper.ThrowStartElementExpected(), System.Xml.XmlExceptionHelper.ThrowStartElementExpected(), and System.Xml.XmlExceptionHelper.ThrowStartElementExpected().