Terraria: System.Xml.XmlExceptionHelper.CreateConversionException
CreateConversionException() [1/2]
static XmlException System.Xml.XmlExceptionHelper.CreateConversionException (string type, Exception exception) inline static
Definition at line 289 of file XmlExceptionHelper.cs.
    {
        return new XmlException(System.SR.Format(System.SR.XmlInvalidConversionWithoutValue, type), exception);
    }
References System.exception, System.SR.Format(), System.type, System.Xml.XmlException, and System.SR.XmlInvalidConversionWithoutValue.
Referenced by System.Runtime.Serialization.DateTimeOffsetAdapter.GetDateTimeOffset(), System.Runtime.Serialization.Json.XmlJsonReader.ParseChar(), System.Runtime.Serialization.Json.XmlJsonReader.ParseInt(), System.Runtime.Serialization.Json.JsonReaderDelegator.ParseJsonDateInDefaultFormat(), System.Runtime.Serialization.XmlReaderDelegator.ReadContentAsBase64(), System.Xml.XmlDictionaryReader.XmlWrappedReader.ReadContentAsBoolean(), System.Runtime.Serialization.Json.XmlJsonReader.ReadContentAsDecimal(), System.Xml.XmlDictionaryReader.XmlWrappedReader.ReadContentAsDecimal(), System.Xml.XmlDictionaryReader.XmlWrappedReader.ReadContentAsDouble(), System.Xml.XmlDictionaryReader.XmlWrappedReader.ReadContentAsFloat(), System.Runtime.Serialization.XmlReaderDelegator.ReadContentAsGuid(), System.Xml.XmlDictionaryReader.XmlWrappedReader.ReadContentAsInt(), System.Runtime.Serialization.Json.XmlJsonReader.ReadContentAsLong(), System.Xml.XmlDictionaryReader.XmlWrappedReader.ReadContentAsLong(), System.Xml.XmlDictionaryReader.XmlWrappedReader.ReadContentAsString(), System.Runtime.Serialization.Json.JsonReaderDelegator.ReadContentAsUnsignedLong(), System.Runtime.Serialization.XmlReaderDelegator.ReadContentAsUri(), System.Xml.XmlBufferReader.ReadDateTime(), System.Xml.XmlDictionaryReader.ReadElementContentAsDateTime(), System.Runtime.Serialization.XmlReaderDelegator.ReadElementContentAsGuid(), System.Xml.XmlDictionaryReader.ReadElementContentAsGuid(), System.Xml.XmlDictionaryReader.ReadElementContentAsUniqueId(), System.Runtime.Serialization.Json.JsonReaderDelegator.ReadElementContentAsUnsignedLong(), System.Runtime.Serialization.XmlReaderDelegator.ReadElementContentAsUri(), System.Xml.XmlBufferReader.ReadTimeSpan(), System.Xml.XmlConverter.ToBoolean(), System.Xml.XmlConverter.ToDateTime(), System.Xml.XmlConverter.ToDateTime(), System.Xml.XmlConverter.ToDecimal(), System.Xml.XmlConverter.ToDouble(), System.Xml.XmlConverter.ToGuid(), System.Xml.XmlConverter.ToInt32(), System.Xml.XmlConverter.ToInt64(), System.Xml.XmlConverter.ToSingle(), System.Xml.XmlConverter.ToTimeSpan(), System.Xml.XmlConverter.ToUInt64(), and System.Xml.XmlConverter.ToUniqueId().