Terraria: System.Xml.XmlExceptionHelper.ThrowMaxStringContentLengthExceeded
ThrowMaxStringContentLengthExceeded()
static void System.Xml.XmlExceptionHelper.ThrowMaxStringContentLengthExceeded (XmlDictionaryReader reader, int maxStringContentLength) inline static
Definition at line 157 of file XmlExceptionHelper.cs.
    {
        ThrowXmlException(reader, System.SR.XmlMaxStringContentLengthExceeded, maxStringContentLength.ToString(NumberFormatInfo.CurrentInfo));
    }
References System.Globalization.NumberFormatInfo.CurrentInfo, System.Xml.Dictionary, System.Xml.XmlExceptionHelper.ThrowXmlException(), and System.SR.XmlMaxStringContentLengthExceeded.
Referenced by System.Xml.XmlBaseReader.ReadContentAsString(), System.Xml.XmlDictionaryReader.ReadContentAsString(), System.Xml.XmlBinaryReader.ReadElementContentAsString(), and System.Xml.XmlDictionaryReader.ReadString().