Terraria: System.Xml.XmlExceptionHelper.GetName
GetName()
static string System.Xml.XmlExceptionHelper.GetName (string prefix, string localName) inline static private
Definition at line 50 of file XmlExceptionHelper.cs.
    {
        if (prefix.Length == 0)
        {
            return localName;
        }
        return prefix + ":" + localName;
    }
References System.prefix.
Referenced by System.Xml.XmlExceptionHelper.GetWhatWasFound(), System.Xml.XmlExceptionHelper.ThrowDuplicateAttribute(), and System.Xml.XmlExceptionHelper.ThrowTagMismatch().