Terraria: System.Xml.XmlExceptionHelper.CreateEncodingException
CreateEncodingException() [1/2]
static XmlException System.Xml.XmlExceptionHelper.CreateEncodingException (byte[] buffer, int offset, int count, Exception exception) inline static
Definition at line 299 of file XmlExceptionHelper.cs.
    {
        return CreateEncodingException(new UTF8Encoding(encoderShouldEmitUTF8Identifier: false, throwOnInvalidBytes: false).GetString(buffer, offset, count), exception);
    }
References System.buffer, System.count, System.Xml.XmlExceptionHelper.CreateEncodingException(), System.Xml.Dictionary, System.exception, and System.offset.
Referenced by System.Xml.XmlExceptionHelper.CreateEncodingException(), System.Xml.XmlConverter.ToBytes(), System.Xml.XmlConverter.ToChars(), System.Xml.XmlConverter.ToString(), System.Xml.XmlConverter.ToStringUnicode(), and System.Xml.ValueHandle.TryReadChars().