Terraria: Terraria.WorldBuilding.StructureMap.CanPlace
CanPlace() [2/2]
bool Terraria.WorldBuilding.StructureMap.CanPlace (Rectangle area, int padding = 0) inline
    {
        return CanPlace(area, TileID.Sets.GeneralPlacementTiles, padding);
    }
References Terraria.WorldBuilding.StructureMap.CanPlace(), and Terraria.ID.TileID.Sets.GeneralPlacementTiles.
Referenced by Terraria.WorldBuilding.StructureMap.CanPlace(), Terraria.GameContent.Biomes.DeadMansChestBiome.GetPossibleChestsToTrapify(), Terraria.GameContent.Biomes.CampsiteBiome.Place(), Terraria.GameContent.Biomes.CorruptionPitBiome.Place(), Terraria.GameContent.Biomes.EnchantedSwordBiome.Place(), Terraria.GameContent.Biomes.HiveBiome.Place(), Terraria.GameContent.Biomes.HoneyPatchBiome.Place(), Terraria.GameContent.Biomes.MahoganyTreeBiome.Place(), Terraria.GameContent.Biomes.MiningExplosivesBiome.Place(), and Terraria.WorldBuilding.SimpleStructure.Place().