Terraria: Terraria.WorldBuilding.StructureMap.AddProtectedStructure
AddProtectedStructure()
void Terraria.WorldBuilding.StructureMap.AddProtectedStructure (Rectangle area, int padding = 0) inline
Definition at line 78 of file StructureMap.cs.
    {
        lock (_lock)
        {
            area.Inflate(padding, padding);
            _structures.Add(area);
            _protectedStructures.Add(area);
        }
    }
References Terraria.WorldBuilding.StructureMap._lock, Terraria.WorldBuilding.StructureMap._protectedStructures, and Terraria.WorldBuilding.StructureMap._structures.
Referenced by Terraria.GameContent.Biomes.CampsiteBiome.Place(), Terraria.GameContent.Biomes.CorruptionPitBiome.Place(), Terraria.GameContent.Biomes.EnchantedSwordBiome.Place(), Terraria.GameContent.Biomes.HiveBiome.Place(), Terraria.GameContent.Biomes.HoneyPatchBiome.Place(), Terraria.GameContent.Biomes.MiningExplosivesBiome.Place(), and Terraria.WorldBuilding.SimpleStructure.Place().