Terraria: System.Xml.XmlExceptionHelper.ThrowTagMismatch
ThrowTagMismatch()
static void System.Xml.XmlExceptionHelper.ThrowTagMismatch (XmlDictionaryReader reader, string expectedPrefix, string expectedLocalName, string foundPrefix, string foundLocalName) inline static
Definition at line 217 of file XmlExceptionHelper.cs.
    {
        ThrowXmlException(reader, System.SR.XmlTagMismatch, GetName(expectedPrefix, expectedLocalName), GetName(foundPrefix, foundLocalName));
    }
References System.Xml.Dictionary, System.Xml.XmlExceptionHelper.GetName(), System.Xml.XmlExceptionHelper.ThrowXmlException(), and System.SR.XmlTagMismatch.
Referenced by System.Xml.XmlUTF8TextReader.ReadEndElement().