Terraria: System.Xml.XmlExceptionHelper.ThrowXmlException
ThrowXmlException() [1/5]
static void System.Xml.XmlExceptionHelper.ThrowXmlException (XmlDictionaryReader reader, string res) inline static private
Definition at line 11 of file XmlExceptionHelper.cs.
    {
        ThrowXmlException(reader, res, null);
    }
References System.Xml.Dictionary, and System.Xml.XmlExceptionHelper.ThrowXmlException().
Referenced by System.Xml.XmlBaseReader.AddXmlnsAttribute(), System.Xml.XmlBaseReader.CheckDeclAttribute(), System.Xml.XmlBaseReader.CheckStandalone(), System.Xml.XmlBaseReader.MoveToDeclaration(), System.Runtime.Serialization.Json.XmlJsonReader.Read(), System.Xml.XmlUTF8TextReader.Read(), System.Runtime.Serialization.Json.XmlJsonReader.ReadAttributes(), System.Xml.XmlUTF8TextReader.ReadAttributes(), System.Xml.XmlUTF8TextReader.ReadComment(), System.Runtime.Serialization.Json.XmlJsonReader.ReadEscapedCharacter(), System.Runtime.Serialization.Json.XmlJsonReader.ReadNonFFFE(), System.Xml.XmlUTF8TextReader.ReadNonFFFE(), System.Xml.XmlUTF8TextReader.ReadTextAndWatchForInvalidCharacters(), System.Xml.XmlExceptionHelper.ThrowBase64DataExpected(), System.Xml.XmlExceptionHelper.ThrowConversionOverflow(), System.Xml.XmlExceptionHelper.ThrowDeclarationNotFirst(), System.Xml.XmlExceptionHelper.ThrowDuplicateAttribute(), System.Xml.XmlExceptionHelper.ThrowDuplicateXmlnsAttribute(), System.Xml.XmlExceptionHelper.ThrowEmptyNamespace(), System.Xml.XmlExceptionHelper.ThrowEndElementExpected(), System.Xml.XmlExceptionHelper.ThrowFullStartElementExpected(), System.Xml.XmlExceptionHelper.ThrowFullStartElementExpected(), System.Xml.XmlExceptionHelper.ThrowFullStartElementExpected(), System.Xml.XmlExceptionHelper.ThrowInvalidBinaryFormat(), System.Xml.XmlExceptionHelper.ThrowInvalidCharRef(), System.Xml.XmlExceptionHelper.ThrowInvalidRootData(), System.Xml.XmlExceptionHelper.ThrowInvalidXml(), System.Xml.XmlExceptionHelper.ThrowMaxArrayLengthExceeded(), System.Xml.XmlExceptionHelper.ThrowMaxBytesPerReadExceeded(), System.Xml.XmlExceptionHelper.ThrowMaxDepthExceeded(), System.Xml.XmlExceptionHelper.ThrowMaxStringContentLengthExceeded(), System.Xml.XmlExceptionHelper.ThrowMultipleRootElements(), System.Xml.XmlExceptionHelper.ThrowProcessingInstructionNotSupported(), System.Xml.XmlExceptionHelper.ThrowStartElementExpected(), System.Xml.XmlExceptionHelper.ThrowStartElementExpected(), System.Xml.XmlExceptionHelper.ThrowStartElementExpected(), System.Xml.XmlExceptionHelper.ThrowTagMismatch(), System.Xml.XmlExceptionHelper.ThrowTokenExpected(), System.Xml.XmlExceptionHelper.ThrowTokenExpected(), System.Xml.XmlExceptionHelper.ThrowUndefinedPrefix(), System.Xml.XmlExceptionHelper.ThrowUnexpectedEndElement(), System.Xml.XmlExceptionHelper.ThrowUnexpectedEndOfFile(), System.Xml.XmlExceptionHelper.ThrowXmlDictionaryStringIDOutOfRange(), System.Xml.XmlExceptionHelper.ThrowXmlDictionaryStringIDUndefinedSession(), System.Xml.XmlExceptionHelper.ThrowXmlDictionaryStringIDUndefinedStatic(), System.Xml.XmlExceptionHelper.ThrowXmlException(), System.Xml.XmlExceptionHelper.ThrowXmlException(), System.Xml.XmlExceptionHelper.ThrowXmlException(), System.Runtime.Serialization.Json.XmlJsonReader.UnescapeJsonString(), and System.Xml.XmlUTF8TextReader.VerifyNCName().