Terraria: System.Text.RegularExpressions.RegexNode.ReverseLeft
ReverseLeft()
RegexNode System.Text.RegularExpressions.RegexNode.ReverseLeft () inline
Definition at line 63 of file RegexNode.cs.
    {
        if (UseOptionR() && Type == 25 && ChildCount() > 1)
        {
            ((List<RegexNode>)Children).Reverse();
        }
        return this;
    }
References System.Text.RegularExpressions.RegexNode.ChildCount(), System.Text.RegularExpressions.RegexNode.Children, and System.Text.RegularExpressions.RegexNode.UseOptionR().
Referenced by System.Text.RegularExpressions.RegexParser.AddAlternate(), and System.Text.RegularExpressions.RegexParser.AddGroup().