Terraria: System.Text.RegularExpressions.RegexNode.MakeQuantifier
MakeQuantifier()
RegexNode System.Text.RegularExpressions.RegexNode.MakeQuantifier (bool lazy, int min, int max) inline
Definition at line 1406 of file RegexNode.cs.
    {
        if (min == 0 && max == 0)
        {
            return new RegexNode(23, Options);
        }
        if (min == 1 && max == 1)
        {
            return this;
        }
        int type = Type;
        if ((uint)(type - 9) <= 2u)
        {
            MakeRep(lazy ? 6 : 3, min, max);
            return this;
        }
        RegexNode regexNode = new RegexNode(lazy ? 27 : 26, Options, min, max);
        regexNode.AddChild(this);
        return regexNode;
    }
References System.Text.RegularExpressions.RegexNode.RegexNode(), System.Text.RegularExpressions.RegexNode.MakeRep(), System.Text.RegularExpressions.RegexNode.Options, System.type, and System.Text.RegularExpressions.RegexNode.Type.
Referenced by System.Text.RegularExpressions.RegexParser.AddConcatenate().