Terraria: System.Text.RegularExpressions.RegexNode.ReduceConcatenationWithAutoAtomic
ReduceConcatenationWithAutoAtomic()
void System.Text.RegularExpressions.RegexNode.ReduceConcatenationWithAutoAtomic () inline private
Definition at line 946 of file RegexNode.cs.
    {
        List<RegexNode> list = (List<RegexNode>)Children;
        for (int i = 0; i < list.Count - 1; i++)
        {
            ProcessNode(list[i], list[i + 1], 20u);
        }
        static void ProcessNode(RegexNode node, RegexNode subsequent, uint maxDepth)
        {
            while (true)
            {
                if (node.Type == 28 || node.Type == 25)
                {
                    node = node.Child(node.ChildCount() - 1);
                }
                else
                {
                    if (node.Type != 26)
                    {
                        break;
                    }
                    RegexNode regexNode = FindLastExpressionInLoopForAutoAtomic(node, maxDepth - 1);
                    if (regexNode == null)
                    {
                        break;
                    }
                    node = regexNode;
                }
            }
            switch (node.Type)
            {
            case 3:
                if (!CanBeMadeAtomic(node, subsequent, maxDepth - 1))
                {
                    break;
                }
                goto IL_0089;
            case 4:
                if (!CanBeMadeAtomic(node, subsequent, maxDepth - 1))
                {
                    break;
                }
                goto IL_0089;
            case 5:
                if (!CanBeMadeAtomic(node, subsequent, maxDepth - 1))
                {
                    break;
                }
                goto IL_0089;
            case 24:
                {
                    int num = node.ChildCount();
                    for (int j = 0; j < num; j++)
                    {
                        ProcessNode(node.Child(j), subsequent, maxDepth - 1);
                    }
                    break;
                }
                IL_0089:
                node.MakeLoopAtomic();
                break;
            }
        }
    }
References System.Text.RegularExpressions.RegexNode.CanBeMadeAtomic(), System.Text.RegularExpressions.RegexNode.Children, System.Text.RegularExpressions.RegexNode.FindLastExpressionInLoopForAutoAtomic(), System.Text.RegularExpressions.i, and System.list.
Referenced by System.Text.RegularExpressions.RegexNode.ReduceConcatenation().