Terraria: System.Text.RegularExpressions.RegexNode.AddChild
AddChild()
void System.Text.RegularExpressions.RegexNode.AddChild (RegexNode newChild) inline
Definition at line 1427 of file RegexNode.cs.
    {
        newChild.Next = this;
        newChild = newChild.Reduce();
        newChild.Next = this;
        if (Children == null)
        {
            Children = newChild;
        }
        else if (Children is RegexNode item)
        {
            Children = new List<RegexNode> { item, newChild };
        }
        else
        {
            ((List<RegexNode>)Children).Add(newChild);
        }
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Text.RegularExpressions.RegexNode.Children, and System.item.
Referenced by System.Text.RegularExpressions.RegexParser.AddAlternate(), System.Text.RegularExpressions.RegexParser.AddConcatenate(), System.Text.RegularExpressions.RegexParser.AddConcatenate(), System.Text.RegularExpressions.RegexParser.AddConcatenate(), System.Text.RegularExpressions.RegexParser.AddGroup(), and System.Text.RegularExpressions.RegexParser.PopGroup().