Terraria: System.Text.RegularExpressions.RegexNode.ReduceConcatenation
ReduceConcatenation()
RegexNode System.Text.RegularExpressions.RegexNode.ReduceConcatenation () inline private
Definition at line 654 of file RegexNode.cs.
    {
        switch (ChildCount())
        {
        case 0:
            return new RegexNode(23, Options);
        case 1:
            return Child(0);
        default:
            ReduceConcatenationWithAdjacentStrings();
            ReduceConcatenationWithAdjacentLoops();
            if ((Options & RegexOptions.RightToLeft) == 0)
            {
                ReduceConcatenationWithAutoAtomic();
            }
            return ReplaceNodeIfUnnecessary(23);
        }
    }
References System.Text.RegularExpressions.RegexNode.RegexNode(), System.Text.RegularExpressions.RegexNode.Child(), System.Text.RegularExpressions.RegexNode.ChildCount(), System.Text.RegularExpressions.RegexNode.Options, System.Text.RegularExpressions.RegexNode.ReduceConcatenationWithAdjacentLoops(), System.Text.RegularExpressions.RegexNode.ReduceConcatenationWithAdjacentStrings(), System.Text.RegularExpressions.RegexNode.ReduceConcatenationWithAutoAtomic(), and System.Text.RegularExpressions.RegexNode.ReplaceNodeIfUnnecessary().
Referenced by System.Text.RegularExpressions.RegexNode.Reduce().