Terraria: System.Text.RegularExpressions.RegexNode.CanBeMadeAtomic
CanBeMadeAtomic()
static bool System.Text.RegularExpressions.RegexNode.CanBeMadeAtomic (RegexNode node, RegexNode subsequent, uint maxDepth) inline static private
Definition at line 1030 of file RegexNode.cs.
    {
        if (maxDepth == 0)
        {
            return false;
        }
        for (; subsequent.ChildCount() > 0; subsequent = subsequent.Child(0))
        {
            switch (subsequent.Type)
            {
            case 30:
                if ((subsequent.Options & RegexOptions.RightToLeft) == 0)
                {
                    continue;
                }
                break;
            case 26:
                if (subsequent.M > 0)
                {
                    continue;
                }
                break;
            case 27:
                if (subsequent.M > 0)
                {
                    continue;
                }
                break;
            case 25:
            case 28:
            case 32:
                continue;
            }
            break;
        }
        if (node.Options != subsequent.Options)
        {
            return false;
        }
        if (subsequent.Type == 24)
        {
            int num = subsequent.ChildCount();
            for (int i = 0; i < num; i++)
            {
                if (!CanBeMadeAtomic(node, subsequent.Child(i), maxDepth - 1))
                {
                    return false;
                }
            }
            return true;
        }
        switch (node.Type)
        {
        case 3:
            switch (subsequent.Type)
            {
            case 9:
                if (node.Ch == subsequent.Ch)
                {
                    break;
                }
                goto case 21;
            case 6:
                if (subsequent.M <= 0 || node.Ch == subsequent.Ch)
                {
                    break;
                }
                goto case 21;
            case 3:
                if (subsequent.M <= 0 || node.Ch == subsequent.Ch)
                {
                    break;
                }
                goto case 21;
            case 43:
                if (subsequent.M <= 0 || node.Ch == subsequent.Ch)
                {
                    break;
                }
                goto case 21;
            case 10:
                if (node.Ch != subsequent.Ch)
                {
                    break;
                }
                goto case 21;
            case 7:
                if (subsequent.M <= 0 || node.Ch != subsequent.Ch)
                {
                    break;
                }
                goto case 21;
            case 4:
                if (subsequent.M <= 0 || node.Ch != subsequent.Ch)
                {
                    break;
                }
                goto case 21;
            case 44:
                if (subsequent.M <= 0 || node.Ch != subsequent.Ch)
                {
                    break;
                }
                goto case 21;
            case 12:
                if (node.Ch == subsequent.Str[0])
                {
                    break;
                }
                goto case 21;
            case 11:
                if (RegexCharClass.CharInClass(node.Ch, subsequent.Str))
                {
                    break;
                }
                goto case 21;
            case 8:
                if (subsequent.M <= 0 || RegexCharClass.CharInClass(node.Ch, subsequent.Str))
                {
                    break;
                }
                goto case 21;
            case 5:
                if (subsequent.M <= 0 || RegexCharClass.CharInClass(node.Ch, subsequent.Str))
                {
                    break;
                }
                goto case 21;
            case 45:
                if (subsequent.M <= 0 || RegexCharClass.CharInClass(node.Ch, subsequent.Str))
                {
                    break;
                }
                goto case 21;
            case 20:
                if (node.Ch == '\n')
                {
                    break;
                }
                goto case 21;
            case 15:
                if (node.Ch == '\n')
                {
                    break;
                }
                goto case 21;
            case 16:
                if (!RegexCharClass.IsWordChar(node.Ch))
                {
                    break;
                }
                goto case 21;
            case 17:
                if (RegexCharClass.IsWordChar(node.Ch))
                {
                    break;
                }
                goto case 21;
            case 41:
                if (!RegexCharClass.IsECMAWordChar(node.Ch))
                {
                    break;
                }
                goto case 21;
            case 42:
                if (RegexCharClass.IsECMAWordChar(node.Ch))
                {
                    break;
                }
                goto case 21;
            case 21:
                return true;
            }
            break;
        case 4:
        {
            int type = subsequent.Type;
            if (type <= 9)
            {
                if (type != 3)
                {
                    if (type != 6)
                    {
                        if (type != 9 || node.Ch != subsequent.Ch)
{
                            break;
                        }
                    }
                    else if (subsequent.M <= 0 || node.Ch != subsequent.Ch)
                    {
                        break;
                    }
                }
                else if (subsequent.M <= 0 || node.Ch != subsequent.Ch)
                {
                    break;
                }
            }
            else if (type != 12)
            {
                if (type != 21 && (type != 43 || subsequent.M <= 0 || node.Ch != subsequent.Ch))
                {
                    break;
                }
            }
            else if (node.Ch != subsequent.Str[0])
            {
                break;
            }
            return true;
        }
        case 5:
            switch (subsequent.Type)
            {
            case 9:
                if (RegexCharClass.CharInClass(subsequent.Ch, node.Str))
                {
                    break;
                }
                goto case 21;
            case 6:
                if (subsequent.M <= 0 || RegexCharClass.CharInClass(subsequent.Ch, node.Str))
                {
                    break;
                }
                goto case 21;
            case 3:
                if (subsequent.M <= 0 || RegexCharClass.CharInClass(subsequent.Ch, node.Str))
                {
                    break;
                }
                goto case 21;
            case 43:
                if (subsequent.M <= 0 || RegexCharClass.CharInClass(subsequent.Ch, node.Str))
                {
                    break;
                }
                goto case 21;
            case 12:
                if (RegexCharClass.CharInClass(subsequent.Str[0], node.Str))
                {
                    break;
                }
                goto case 21;
            case 11:
                if (RegexCharClass.MayOverlap(node.Str, subsequent.Str))
                {
                    break;
                }
                goto case 21;
            case 8:
                if (subsequent.M <= 0 || RegexCharClass.MayOverlap(node.Str, subsequent.Str))
                {
                    break;
                }
                goto case 21;
            case 5:
                if (subsequent.M <= 0 || RegexCharClass.MayOverlap(node.Str, subsequent.Str))
                {
                    break;
                }
                goto case 21;
            case 45:
                if (subsequent.M <= 0 || RegexCharClass.MayOverlap(node.Str, subsequent.Str))
                {
                    break;
                }
                goto case 21;
            case 20:
                if (RegexCharClass.CharInClass('\n', node.Str))
                {
                    break;
                }
                goto case 21;
            case 15:
                if (RegexCharClass.CharInClass('\n', node.Str))
                {
                    break;
                }
                goto case 21;
            case 16:
                if (!(node.Str == "\0\0\n\0\u0002\u0004\u0005\u0003\u0001\u0006\t\u0013\0") && !(node.Str == "\0\0\u0001\t"))
                {
                    break;
                }
                goto case 21;
            case 17:
                if (!(node.Str == "\u0001\0\n\0\u0002\u0004\u0005\u0003\u0001\u0006\t\u0013\0") && !(node.Str == "\0\0\u0001\ufff7"))
                {
                    break;
                }
                goto case 21;
            case 41:
                if (!(node.Str == "\0\n\00:A[_`a{") && !(node.Str == "\0\u0002\00:"))
                {
                    break;
                }
                goto case 21;
            case 42:
                if (!(node.Str == "\u0001\n\00:A[_`a{") && !(node.Str == "\0\0\u0001\ufff7"))
                {
                    break;
                }
                goto case 21;
            case 21:
                return true;
            }
            break;
        }
        return false;
    }
References System.Text.RegularExpressions.RegexNode.CanBeMadeAtomic(), System.Text.RegularExpressions.RegexCharClass.CharInClass(), System.Text.RegularExpressions.i, System.Text.RegularExpressions.RegexCharClass.IsECMAWordChar(), System.Text.RegularExpressions.RegexCharClass.IsWordChar(), System.Text.RegularExpressions.RegexCharClass.MayOverlap(), and System.type.
Referenced by System.Text.RegularExpressions.RegexNode.CanBeMadeAtomic(), System.Text.RegularExpressions.RegexNode.FindLastExpressionInLoopForAutoAtomic(), and System.Text.RegularExpressions.RegexNode.ReduceConcatenationWithAutoAtomic().