Terraria: System.Text.RegularExpressions.RegexNode.FinalOptimize
FinalOptimize()
RegexNode System.Text.RegularExpressions.RegexNode.FinalOptimize () inline package
Definition at line 95 of file RegexNode.cs.
    {
        if ((Options & RegexOptions.RightToLeft) == 0)
        {
            EliminateEndingBacktracking(Child(0), 20u);
            RegexNode regexNode = Child(0);
            while (true)
            {
                RegexNode next;
                switch (regexNode.Type)
                {
                case 25:
                case 32:
                    goto IL_006f;
                case 3:
                    if (regexNode.N != int.MaxValue)
                    {
                        break;
                    }
                    goto IL_00d4;
                case 43:
                    if (regexNode.N != int.MaxValue)
                    {
                        break;
                    }
                    goto IL_00d4;
                case 4:
                    if (regexNode.N != int.MaxValue)
                    {
                        break;
                    }
                    goto IL_00d4;
                case 44:
                    if (regexNode.N != int.MaxValue)
                    {
                        break;
                    }
                    goto IL_00d4;
                case 5:
                    if (regexNode.N != int.MaxValue)
                    {
                        break;
                    }
                    goto IL_00d4;
                case 45:
                    {
                        if (regexNode.N != int.MaxValue)
{
                            break;
                        }
                        goto IL_00d4;
                    }
                    IL_00d4:
                    next = regexNode.Next;
                    if (next != null && next.Type == 25)
                    {
                        next.InsertChild(1, new RegexNode(46, regexNode.Options));
                    }
                    break;
                }
                break;
                IL_006f:
                regexNode = regexNode.Child(0);
            }
        }
        while (Child(0).Type == 32)
        {
            ReplaceChild(0, Child(0).Child(0));
        }
        return this;
    }
References System.Text.RegularExpressions.RegexNode.RegexNode(), System.Text.RegularExpressions.RegexNode.Child(), System.Text.RegularExpressions.RegexNode.EliminateEndingBacktracking(), System.Text.RegularExpressions.RegexNode.InsertChild(), System.Text.RegularExpressions.RegexNode.Options, System.Text.RegularExpressions.RegexNode.ReplaceChild(), and System.Text.RegularExpressions.RegexNode.Type.
Referenced by System.Text.RegularExpressions.RegexParser.ScanRegex().