Terraria: System.Text.RegularExpressions.RegexNode.ComputeMinLength
ComputeMinLength()
int System.Text.RegularExpressions.RegexNode.ComputeMinLength () inline
Definition at line 1342 of file RegexNode.cs.
    {
        return ComputeMinLength(this, 20u);
        static int ComputeMinLength(RegexNode node, uint maxDepth)
        {
            if (maxDepth == 0)
            {
                return 0;
            }
            switch (node.Type)
            {
            case 9:
            case 10:
            case 11:
                return 1;
            case 12:
                return node.Str.Length;
            case 3:
            case 4:
            case 5:
            case 6:
            case 7:
            case 8:
            case 43:
            case 44:
            case 45:
                return node.M;
            case 26:
            case 27:
                return (int)Math.Min(2147483647L, (long)node.M * (long)ComputeMinLength(node.Child(0), maxDepth - 1));
            case 24:
            {
                int num3 = node.ChildCount();
                int num4 = ComputeMinLength(node.Child(0), maxDepth - 1);
                for (int j = 1; j < num3; j++)
                {
                    if (num4 <= 0)
                    {
                        break;
                    }
                    num4 = Math.Min(num4, ComputeMinLength(node.Child(j), maxDepth - 1));
                }
                return num4;
            }
            case 25:
            {
                long num = 0L;
                int num2 = node.ChildCount();
                for (int i = 0; i < num2; i++)
                {
                    num += ComputeMinLength(node.Child(i), maxDepth - 1);
                }
                return (int)Math.Min(2147483647L, num);
            }
            case 28:
            case 29:
            case 32:
                return ComputeMinLength(node.Child(0), maxDepth - 1);
            default:
                return 0;
            }
        }
    }
References System.Text.RegularExpressions.RegexNode.ComputeMinLength(), System.Text.RegularExpressions.i, System.L, and System.Math.Min().
Referenced by System.Text.RegularExpressions.RegexNode.ComputeMinLength().