Terraria: System.Text.RegularExpressions.RegexNode.EliminateEndingBacktracking
EliminateEndingBacktracking()
static void System.Text.RegularExpressions.RegexNode.EliminateEndingBacktracking (RegexNode node, uint maxDepth) inline static private
Definition at line 167 of file RegexNode.cs.
    {
        if (maxDepth == 0)
        {
            return;
        }
        while (true)
        {
            switch (node.Type)
            {
            case 3:
            case 4:
            case 5:
                node.MakeLoopAtomic();
                return;
            case 25:
            case 28:
            {
                RegexNode regexNode2 = node.Child(node.ChildCount() - 1);
                if ((regexNode2.Type == 24 || regexNode2.Type == 26 || regexNode2.Type == 27) && (node.Next == null || node.Next.Type != 32))
                {
                    RegexNode regexNode3 = new RegexNode(32, regexNode2.Options);
                    regexNode3.AddChild(regexNode2);
                    node.ReplaceChild(node.ChildCount() - 1, regexNode3);
                }
                node = regexNode2;
                break;
            }
            case 24:
            {
                int num = node.ChildCount();
                for (int i = 1; i < num; i++)
                {
                    EliminateEndingBacktracking(node.Child(i), maxDepth - 1);
                }
                node = node.Child(0);
                break;
            }
            case 26:
            {
                RegexNode regexNode = FindLastExpressionInLoopForAutoAtomic(node, maxDepth - 1);
                if (regexNode != null)
                {
                    node = regexNode;
                    break;
                }
                return;
            }
            default:
                return;
            }
        }
    }
References System.Text.RegularExpressions.RegexNode.RegexNode(), System.Text.RegularExpressions.RegexNode.EliminateEndingBacktracking(), System.Text.RegularExpressions.RegexNode.FindLastExpressionInLoopForAutoAtomic(), and System.Text.RegularExpressions.i.
Referenced by System.Text.RegularExpressions.RegexNode.EliminateEndingBacktracking(), System.Text.RegularExpressions.RegexNode.FinalOptimize(), and System.Text.RegularExpressions.RegexNode.ReduceAtomic().