Terraria: MS.Internal.Xml.XPath.CompiledXpathExpr.AddSort
AddSort() [1/2]
override void MS.Internal.Xml.XPath.CompiledXpathExpr.AddSort (object expr, IComparer comparer) inline inherited
Definition at line 93 of file CompiledXpathExpr.cs.
    {
        Query evalQuery;
        if (expr is string query)
        {
            evalQuery = new QueryBuilder().Build(query, out _needContext);
        }
        else
        {
            if (!(expr is CompiledXpathExpr compiledXpathExpr))
            {
                throw XPathException.Create(System.SR.Xp_BadQueryObject);
            }
            evalQuery = compiledXpathExpr.QueryTree;
        }
        SortQuery sortQuery = _query as SortQuery;
        if (sortQuery == null)
        {
            sortQuery = (SortQuery)(_query = new SortQuery(_query));
        }
        sortQuery.AddSort(evalQuery, comparer);
    }
References MS.Internal.Xml.XPath.CompiledXpathExpr._needContext, MS.Internal.Xml.XPath.CompiledXpathExpr._query, MS.Internal.Xml.XPath.SortQuery.AddSort(), MS.Internal.Xml.XPath.QueryBuilder.Build(), System.comparer, System.Xml.XPath.XPathException.Create(), System.Xml.Dictionary, and System.SR.Xp_BadQueryObject.
Referenced by MS.Internal.Xml.XPath.CompiledXpathExpr.AddSort().