Terraria: System.Text.RegularExpressions.RegexNode.FindLastExpressionInLoopForAutoAtomic
FindLastExpressionInLoopForAutoAtomic()
static RegexNode System.Text.RegularExpressions.RegexNode.FindLastExpressionInLoopForAutoAtomic (RegexNode node, uint maxDepth) inline static private
Definition at line 1011 of file RegexNode.cs.
    {
        node = node.Child(0);
        while (node.Type == 28)
        {
            node = node.Child(0);
        }
        if (node.Type == 25)
        {
            int num = node.ChildCount();
            RegexNode regexNode = node.Child(num - 1);
            if (CanBeMadeAtomic(regexNode, node.Child(0), maxDepth - 1))
            {
                return regexNode;
            }
        }
        return null;
    }
References System.Text.RegularExpressions.RegexNode.CanBeMadeAtomic().
Referenced by System.Text.RegularExpressions.RegexNode.EliminateEndingBacktracking(), and System.Text.RegularExpressions.RegexNode.ReduceConcatenationWithAutoAtomic().