Terraria: System.Text.RegularExpressions.RegexNode.ChildCount
ChildCount()
int System.Text.RegularExpressions.RegexNode.ChildCount () inline
Definition at line 1476 of file RegexNode.cs.
    {
        if (Children == null)
        {
            return 0;
        }
        if (Children is List<RegexNode> list)
        {
            return list.Count;
        }
        return 1;
    }
References System.Text.RegularExpressions.RegexNode.Children, and System.list.
Referenced by System.Text.RegularExpressions.RegexParser.AddGroup(), System.Text.RegularExpressions.RegexNode.IsAtomicByParent(), System.Text.RegularExpressions.RegexParser.PopGroup(), System.Text.RegularExpressions.RegexNode.ReduceAlternation(), System.Text.RegularExpressions.RegexNode.ReduceConcatenation(), System.Text.RegularExpressions.RegexNode.ReplaceNodeIfUnnecessary(), and System.Text.RegularExpressions.RegexNode.ReverseLeft().