Terraria: System.Text.RegularExpressions.RegexNode.Reduce
Reduce()
RegexNode System.Text.RegularExpressions.RegexNode.Reduce () inline private
Definition at line 244 of file RegexNode.cs.
    {
        switch (Type)
        {
        case 24:
            return ReduceAlternation();
        case 25:
            return ReduceConcatenation();
        case 26:
        case 27:
            return ReduceLoops();
        case 32:
            return ReduceAtomic();
        case 29:
            return ReduceGroup();
        case 5:
        case 8:
        case 11:
        case 45:
            return ReduceSet();
        default:
            return this;
        }
    }
References System.Text.RegularExpressions.RegexNode.ReduceAlternation(), System.Text.RegularExpressions.RegexNode.ReduceAtomic(), System.Text.RegularExpressions.RegexNode.ReduceConcatenation(), System.Text.RegularExpressions.RegexNode.ReduceGroup(), System.Text.RegularExpressions.RegexNode.ReduceLoops(), and System.Text.RegularExpressions.RegexNode.ReduceSet().