Terraria: System.Net.WebSockets.HttpWebSocket.ValidateWebSocketHeaders
ValidateWebSocketHeaders()
static void System.Net.WebSockets.HttpWebSocket.ValidateWebSocketHeaders (HttpListenerContext context) inline static private
Definition at line 82 of file HttpWebSocket.cs.
    {
        if (!WebSocketsSupported)
        {
            throw new PlatformNotSupportedException(System.SR.net_WebSockets_UnsupportedPlatform);
        }
        if (!context.Request.IsWebSocketRequest)
        {
            throw new WebSocketException(WebSocketError.NotAWebSocket, System.SR.Format(System.SR.net_WebSockets_AcceptNotAWebSocket, "ValidateWebSocketHeaders", "Connection", "Upgrade", "websocket", context.Request.Headers["Upgrade"]));
        }
        string text = context.Request.Headers["Sec-WebSocket-Version"];
        if (string.IsNullOrEmpty(text))
        {
            throw new WebSocketException(WebSocketError.HeaderError, System.SR.Format(System.SR.net_WebSockets_AcceptHeaderNotFound, "ValidateWebSocketHeaders", "Sec-WebSocket-Version"));
        }
        if (!string.Equals(text, SupportedVersion, StringComparison.OrdinalIgnoreCase))
        {
            throw new WebSocketException(WebSocketError.UnsupportedVersion, System.SR.Format(System.SR.net_WebSockets_AcceptUnsupportedWebSocketVersion, "ValidateWebSocketHeaders", text, SupportedVersion));
        }
        string text2 = context.Request.Headers["Sec-WebSocket-Key"];
        bool flag = string.IsNullOrWhiteSpace(text2);
        if (!flag)
        {
            try
            {
                flag = Convert.FromBase64String(text2).Length != 16;
            }
            catch
            {
                flag = true;
            }
        }
        if (flag)
        {
            throw new WebSocketException(WebSocketError.HeaderError, System.SR.Format(System.SR.net_WebSockets_AcceptHeaderNotFound, "ValidateWebSocketHeaders", "Sec-WebSocket-Key"));
        }
    }
References System.Net.Equals, System.SR.Format(), System.Convert.FromBase64String(), System.Net.HttpListenerRequest.Headers, System.Net.HttpListenerRequest.IsWebSocketRequest, System.SR.net_WebSockets_AcceptHeaderNotFound, System.SR.net_WebSockets_AcceptNotAWebSocket, System.SR.net_WebSockets_AcceptUnsupportedWebSocketVersion, System.SR.net_WebSockets_UnsupportedPlatform, System.Net.HttpListenerContext.Request, System.Net.WebSockets.HttpWebSocket.SupportedVersion, System.text, and System.Net.WebSockets.HttpWebSocket.WebSocketsSupported.
Referenced by System.Net.WebSockets.HttpWebSocket.AcceptWebSocketAsyncCore().