Terraria: System.Net.WebSockets.HttpWebSocket.AcceptWebSocketAsync
AcceptWebSocketAsync()
static Task< HttpListenerWebSocketContext > System.Net.WebSockets.HttpWebSocket.AcceptWebSocketAsync (HttpListenerContext context, string subProtocol, int receiveBufferSize, TimeSpan keepAliveInterval, ArraySegment< byte > internalBuffer) inline static package
Definition at line 120 of file HttpWebSocket.cs.
    {
        ValidateOptions(subProtocol, receiveBufferSize, 16, keepAliveInterval);
        System.Net.WebSockets.WebSocketValidate.ValidateArraySegment(internalBuffer, "internalBuffer");
        WebSocketBuffer.Validate(internalBuffer.Count, receiveBufferSize, 16, isServerBuffer: true);
        return AcceptWebSocketAsyncCore(context, subProtocol, receiveBufferSize, keepAliveInterval, internalBuffer);
    }
References System.Net.WebSockets.HttpWebSocket.AcceptWebSocketAsyncCore(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Net.WebSockets.WebSocketBuffer.Validate(), System.Net.WebSockets.WebSocketValidate.ValidateArraySegment(), and System.Net.WebSockets.HttpWebSocket.ValidateOptions().
Referenced by System.Net.HttpListenerContext.AcceptWebSocketAsync().