Terraria: System.Net.WebSockets.HttpWebSocket.AcceptWebSocketAsyncCore
AcceptWebSocketAsyncCore()
static async Task< HttpListenerWebSocketContext > System.Net.WebSockets.HttpWebSocket.AcceptWebSocketAsyncCore (HttpListenerContext context, string subProtocol, int receiveBufferSize, TimeSpan keepAliveInterval, ArraySegment< byte > internalBuffer) inline static private
Definition at line 128 of file HttpWebSocket.cs.
    {
        try
        {
            HttpListenerResponse response = context.Response;
            HttpListenerRequest request = context.Request;
            ValidateWebSocketHeaders(context);
            string secWebSocketVersion = request.Headers["Sec-WebSocket-Version"];
            string origin = request.Headers["Origin"];
            List<string> secWebSocketProtocols = new List<string>();
            if (ProcessWebSocketProtocolHeader(request.Headers["Sec-WebSocket-Protocol"], subProtocol, out var acceptProtocol))
            {
                secWebSocketProtocols.Add(acceptProtocol);
                response.Headers.Add("Sec-WebSocket-Protocol", acceptProtocol);
            }
            string secWebSocketKey = request.Headers["Sec-WebSocket-Key"];
            string secWebSocketAcceptString = GetSecWebSocketAcceptString(secWebSocketKey);
            response.Headers.Add("Connection", "Upgrade");
            response.Headers.Add("Upgrade", "websocket");
            response.Headers.Add("Sec-WebSocket-Accept", secWebSocketAcceptString);
            response.StatusCode = 101;
            response.ComputeCoreHeaders();
            ulong num = SendWebSocketHeaders(response);
            if (num != 0L)
            {
                throw new WebSocketException((int)num, System.SR.Format(System.SR.net_WebSockets_NativeSendResponseHeaders, "AcceptWebSocketAsync", num));
            }
            if (System.Net.NetEventSource.Log.IsEnabled())
            {
                System.Net.NetEventSource.Info(null, FormattableStringFactory.Create("{0} = {1}", "Origin", origin), "AcceptWebSocketAsyncCore");
                System.Net.NetEventSource.Info(null, FormattableStringFactory.Create("{0} = {1}", "Sec-WebSocket-Version", secWebSocketVersion), "AcceptWebSocketAsyncCore");
                System.Net.NetEventSource.Info(null, FormattableStringFactory.Create("{0} = {1}", "Sec-WebSocket-Key", secWebSocketKey), "AcceptWebSocketAsyncCore");
                System.Net.NetEventSource.Info(null, FormattableStringFactory.Create("{0} = {1}", "Sec-WebSocket-Accept", secWebSocketAcceptString), "AcceptWebSocketAsyncCore");
                System.Net.NetEventSource.Info(null, FormattableStringFactory.Create("{0} = {1}", "Sec-WebSocket-Protocol", request.Headers["Sec-WebSocket-Protocol"]), "AcceptWebSocketAsyncCore");
                System.Net.NetEventSource.Info(null, FormattableStringFactory.Create("{0} = {1}", "Sec-WebSocket-Protocol", acceptProtocol), "AcceptWebSocketAsyncCore");
            }
            await response.OutputStream.FlushAsync().SuppressContextFlow();
            HttpResponseStream outputStream = response.OutputStream as HttpResponseStream;
            ((HttpResponseStream)response.OutputStream).SwitchToOpaqueMode();
            HttpRequestStream httpRequestStream = new HttpRequestStream(context);
            httpRequestStream.SwitchToOpaqueMode();
            WebSocketHttpListenerDuplexStream innerStream = new WebSocketHttpListenerDuplexStream(httpRequestStream, outputStream, context);
            WebSocket webSocket = ServerWebSocket.Create(innerStream, subProtocol, receiveBufferSize, keepAliveInterval, internalBuffer);
            HttpListenerWebSocketContext httpListenerWebSocketContext = new HttpListenerWebSocketContext(request.Url, request.Headers, request.Cookies, context.User, request.IsAuthenticated, request.IsLocal, request.IsSecureConnection, origin, secWebSocketProtocols.AsReadOnly(), secWebSocketVersion, secWebSocketKey, webSocket);
            if (System.Net.NetEventSource.Log.IsEnabled())
            {
                System.Net.NetEventSource.Associate(context, httpListenerWebSocketContext, "AcceptWebSocketAsyncCore");
                System.Net.NetEventSource.Associate(httpListenerWebSocketContext, webSocket, "AcceptWebSocketAsyncCore");
            }
            return httpListenerWebSocketContext;
        }
        catch (Exception message)
        {
            if (System.Net.NetEventSource.Log.IsEnabled())
            {
                System.Net.NetEventSource.Error(context, message, "AcceptWebSocketAsyncCore");
            }
            throw;
        }
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Net.NetEventSource.Associate(), System.Net.WebSockets.ServerWebSocket.Create(), System.Runtime.CompilerServices.FormattableStringFactory.Create(), System.Net.NetEventSource.Error(), System.SR.Format(), System.Net.WebSockets.HttpWebSocket.GetSecWebSocketAcceptString(), System.Net.NetEventSource.Info(), System.L, System.Net.NetEventSource.Log, System.SR.net_WebSockets_NativeSendResponseHeaders, System.Net.WebSockets.HttpWebSocket.ProcessWebSocketProtocolHeader(), System.Net.HttpListenerContext.Request, System.Net.HttpListenerContext.Response, System.Net.WebSockets.HttpWebSocket.SendWebSocketHeaders(), System.Net.HttpResponseStream.SwitchToOpaqueMode(), System.Net.HttpListenerContext.User, and System.Net.WebSockets.HttpWebSocket.ValidateWebSocketHeaders().
Referenced by System.Net.WebSockets.HttpWebSocket.AcceptWebSocketAsync().