Terraria: System.Net.Http.Headers.WarningHeaderValue.WarningHeaderValue
WarningHeaderValue() [1/3]
System.Net.Http.Headers.WarningHeaderValue.WarningHeaderValue (int code, string agent, string text) inline
Definition at line 25 of file WarningHeaderValue.cs.
    {
        CheckCode(code);
        CheckAgent(agent);
        HeaderUtilities.CheckValidQuotedString(text, "text");
        _code = code;
        _agent = agent;
        _text = text;
    }
References System.Net.Http.Headers.WarningHeaderValue._agent, System.Net.Http.Headers.WarningHeaderValue._code, System.Net.Http.Headers.WarningHeaderValue._text, System.Net.Http.Headers.WarningHeaderValue.CheckAgent(), System.Net.Http.Headers.WarningHeaderValue.CheckCode(), System.Net.Http.Headers.HeaderUtilities.CheckValidQuotedString(), and System.text.
Referenced by System.Net.Http.Headers.WarningHeaderValue.Clone(), System.Net.Http.Headers.WarningHeaderValue.GetWarningLength(), and System.Net.Http.Headers.WarningHeaderValue.TryParse().