Terraria: System.Net.Http.Headers.WarningHeaderValue.ToString
ToString()
override string System.Net.Http.Headers.WarningHeaderValue.ToString () inline
Definition at line 54 of file WarningHeaderValue.cs.
    {
        StringBuilder stringBuilder = System.Text.StringBuilderCache.Acquire();
        StringBuilder stringBuilder2 = stringBuilder;
        IFormatProvider invariantInfo = NumberFormatInfo.InvariantInfo;
        StringBuilder.AppendInterpolatedStringHandler handler = new StringBuilder.AppendInterpolatedStringHandler(0, 1, stringBuilder2, invariantInfo);
        handler.AppendFormatted(_code, "000");
        stringBuilder2.Append(invariantInfo, ref handler);
        stringBuilder.Append(' ');
        stringBuilder.Append(_agent);
        stringBuilder.Append(' ');
        stringBuilder.Append(_text);
        if (_date.HasValue)
        {
            stringBuilder.Append(" \"");
            stringBuilder.Append(HttpDateParser.DateToString(_date.Value));
            stringBuilder.Append('"');
        }
        return System.Text.StringBuilderCache.GetStringAndRelease(stringBuilder);
    }
References System.Net.Http.Headers.WarningHeaderValue._agent, System.Net.Http.Headers.WarningHeaderValue._code, System.Net.Http.Headers.WarningHeaderValue._date, System.Net.Http.Headers.WarningHeaderValue._text, System.Text.StringBuilderCache.Acquire(), System.Text.StringBuilder.Append(), System.Text.StringBuilder.AppendInterpolatedStringHandler.AppendFormatted(), System.Net.HttpDateParser.DateToString(), System.Text.StringBuilderCache.GetStringAndRelease(), and System.Globalization.NumberFormatInfo.InvariantInfo.