Terraria: System.Net.Http.Headers.WarningHeaderValue.GetWarningLength
GetWarningLength()
static int System.Net.Http.Headers.WarningHeaderValue.GetWarningLength (string input, int startIndex, out object parsedValue) inline static package
Definition at line 124 of file WarningHeaderValue.cs.
    {
        parsedValue = null;
        if (string.IsNullOrEmpty(input) || startIndex >= input.Length)
        {
            return 0;
        }
        int current = startIndex;
        if (!TryReadCode(input, ref current, out var code))
        {
            return 0;
        }
        if (!TryReadAgent(input, current, ref current, out var agent))
        {
            return 0;
        }
        int length = 0;
        int startIndex2 = current;
        if (HttpRuleParser.GetQuotedStringLength(input, current, out length) != 0)
        {
            return 0;
        }
        string text = input.Substring(startIndex2, length);
        current += length;
        DateTimeOffset? date = null;
        if (!TryReadDate(input, ref current, out date))
        {
            return 0;
        }
        parsedValue = ((!date.HasValue) ? new WarningHeaderValue(code, agent, text) : new WarningHeaderValue(code, agent, text, date.Value));
        return current - startIndex;
    }
References System.Net.Http.Headers.WarningHeaderValue.WarningHeaderValue(), System.Net.Http.HttpRuleParser.GetQuotedStringLength(), System.input, System.length, System.startIndex, System.text, System.Net.Http.Headers.WarningHeaderValue.TryReadAgent(), System.Net.Http.Headers.WarningHeaderValue.TryReadCode(), and System.Net.Http.Headers.WarningHeaderValue.TryReadDate().