Terraria: System.Net.Mail.SmtpReplyReaderFactory.ReadLinesAsyncResult.ProcessRead
ProcessRead()
bool System.Net.Mail.SmtpReplyReaderFactory.ReadLinesAsyncResult.ProcessRead () inline private
Definition at line 114 of file SmtpReplyReaderFactory.cs.
        {
            if (_read == 0)
            {
                throw new IOException(System.SR.Format(System.SR.net_io_readfailure, System.SR.net_io_connectionclosed));
            }
            int num = 0;
            while (num != _read)
            {
                int num2 = _parent.ProcessRead(_parent._byteBuffer, num, _read - num, readLine: true);
                if (_statusRead < 4)
                {
                    int num3 = Math.Min(4 - _statusRead, num2);
                    _statusRead += num3;
                    num += num3;
                    num2 -= num3;
                    if (num2 == 0)
                    {
                        continue;
                    }
                }
                _builder.Append(Encoding.UTF8.GetString(_parent._byteBuffer, num, num2));
                num += num2;
                if (_parent._readState == ReadState.Status0)
                {
                    _lines.Add(new LineInfo(_parent._statusCode, _builder.ToString(0, _builder.Length - 2)));
                    _builder = new StringBuilder();
                    _statusRead = 0;
                    if (_oneLine)
                    {
                        _parent._bufferedStream.Push(_parent._byteBuffer, num, _read - num);
                        InvokeCallback();
                        return false;
                    }
                }
                else if (_parent._readState == ReadState.Done)
                {
                    _lines.Add(new LineInfo(_parent._statusCode, _builder.ToString(0, _builder.Length - 2)));
                    _parent._bufferedStream.Push(_parent._byteBuffer, num, _read - num);
                    InvokeCallback();
                    return false;
                }
            }
            return true;
        }
References System.Net.Mail.SmtpReplyReaderFactory._bufferedStream, System.Net.Mail.SmtpReplyReaderFactory.ReadLinesAsyncResult._builder, System.Net.Mail.SmtpReplyReaderFactory._byteBuffer, System.Net.Mail.SmtpReplyReaderFactory.ReadLinesAsyncResult._lines, System.Net.Mail.SmtpReplyReaderFactory.ReadLinesAsyncResult._oneLine, System.Net.Mail.SmtpReplyReaderFactory.ReadLinesAsyncResult._parent, System.Net.Mail.SmtpReplyReaderFactory.ReadLinesAsyncResult._read, System.Net.Mail.SmtpReplyReaderFactory._readState, System.Net.Mail.SmtpReplyReaderFactory._statusCode, System.Net.Mail.SmtpReplyReaderFactory.ReadLinesAsyncResult._statusRead, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Text.StringBuilder.Append(), System.SR.Format(), System.Net.LazyAsyncResult.InvokeCallback(), System.Text.StringBuilder.Length, System.Math.Min(), System.SR.net_io_connectionclosed, System.SR.net_io_readfailure, System.Net.Mail.SmtpReplyReaderFactory.ProcessRead(), System.Net.BufferedReadStream.Push(), System.Text.StringBuilder.ToString(), and System.Text.Encoding.UTF8.
Referenced by System.Net.Mail.SmtpReplyReaderFactory.ReadLinesAsyncResult.Read().