Terraria: System.Text.Encodings.Web.TextEncoderSettings.GetAllowedCodePointsBitmap
GetAllowedCodePointsBitmap()
ref readonly AllowedBmpCodePointsBitmap System.Text.Encodings.Web.TextEncoderSettings.GetAllowedCodePointsBitmap () inline package
Definition at line 152 of file TextEncoderSettings.cs.
    {
        if (GetType() == typeof(TextEncoderSettings))
        {
            return ref _allowedCodePointsBitmap;
        }
        StrongBox<AllowedBmpCodePointsBitmap> strongBox = new StrongBox<AllowedBmpCodePointsBitmap>();
        foreach (int allowedCodePoint in GetAllowedCodePoints())
        {
            if ((uint)allowedCodePoint <= 65535u)
            {
                strongBox.Value.AllowChar((char)allowedCodePoint);
            }
        }
        return ref strongBox.Value;
    }
References System.Text.Encodings.Web.TextEncoderSettings._allowedCodePointsBitmap, and System.Text.Encodings.Web.TextEncoderSettings.GetAllowedCodePoints().
Referenced by System.Text.Encodings.Web.DefaultHtmlEncoder.DefaultHtmlEncoder(), System.Text.Encodings.Web.DefaultJavaScriptEncoder.DefaultJavaScriptEncoder(), and System.Text.Encodings.Web.DefaultUrlEncoder.DefaultUrlEncoder().