Terraria: ParticleOrchestrator.Spawn_RainbowRodHit
Spawn_RainbowRodHit()
static void ParticleOrchestrator.Spawn_RainbowRodHit (ParticleOrchestraSettings settings) inline static private
     {
         float num = Main.rand.NextFloat() * ((float)Math.PI * 2f);
         float num2 = 6f;
         float num3 = Main.rand.NextFloat();
         for (float num4 = 0f; num4 < 1f; num4 += 1f / num2)
         {
             Vector2 vector = settings.MovementVector * Main.rand.NextFloatDirection() * 0.15f;
             Vector2 vector2 = new Vector2(Main.rand.NextFloat() * 0.4f + 0.4f);
             float f = num + Main.rand.NextFloat() * ((float)Math.PI * 2f);
             float rotation = (float)Math.PI / 2f;
             Vector2 vector3 = 1.5f * vector2;
             float num5 = 60f;
             Vector2 vector4 = Main.rand.NextVector2Circular(8f, 8f) * vector2;
             PrettySparkleParticle prettySparkleParticle = _poolPrettySparkle.RequestParticle();
             prettySparkleParticle.Velocity = f.ToRotationVector2() * vector3 + vector;
             prettySparkleParticle.AccelerationPerFrame = f.ToRotationVector2() * -(vector3 / num5) - vector * 1f / 60f;
             prettySparkleParticle.ColorTint = Main.hslToRgb((num3 + Main.rand.NextFloat() * 0.33f) % 1f, 1f, 0.4f + Main.rand.NextFloat() * 0.25f);
             prettySparkleParticle.ColorTint.A = 0;
             prettySparkleParticle.LocalPosition = settings.PositionInWorld + vector4;
             prettySparkleParticle.Rotation = rotation;
             prettySparkleParticle.Scale = vector2;
             Main.ParticleSystem_World_OverPlayers.Add(prettySparkleParticle);
             prettySparkleParticle = _poolPrettySparkle.RequestParticle();
             prettySparkleParticle.Velocity = f.ToRotationVector2() * vector3 + vector;
             prettySparkleParticle.AccelerationPerFrame = f.ToRotationVector2() * -(vector3 / num5) - vector * 1f / 60f;
             prettySparkleParticle.ColorTint = new Color(255, 255, 255, 0);
             prettySparkleParticle.LocalPosition = settings.PositionInWorld + vector4;
             prettySparkleParticle.Rotation = rotation;
             prettySparkleParticle.Scale = vector2 * 0.6f;
             Main.ParticleSystem_World_OverPlayers.Add(prettySparkleParticle);
         }
         for (int i = 0; i < 12; i++)
         {
             Color newColor = Main.hslToRgb((num3 + Main.rand.NextFloat() * 0.12f) % 1f, 1f, 0.4f + Main.rand.NextFloat() * 0.25f);
             int num6 = Dust.NewDust(settings.PositionInWorld, 0, 0, 267, 0f, 0f, 0, newColor);
             Main.dust[num6].velocity = Main.rand.NextVector2Circular(1f, 1f);
             Main.dust[num6].velocity += settings.MovementVector * Main.rand.NextFloatDirection() * 0.5f;
             Main.dust[num6].noGravity = true;
             Main.dust[num6].scale = 0.6f + Main.rand.NextFloat() * 0.9f;
             Main.dust[num6].fadeIn = 0.7f + Main.rand.NextFloat() * 0.8f;
             if (num6 != 6000)
             {
                 Dust dust = Dust.CloneDust(num6);
                 dust.scale /= 2f;
                 dust.fadeIn *= 0.75f;
                 dust.color = new Color(255, 255, 255, 255);
             }
         }
     }
References _poolPrettySparkle, ABasicParticle.AccelerationPerFrame, ParticleRenderer.Add(), Dust.CloneDust(), Color, Dust.color, PrettySparkleParticle.ColorTint, Main.dust, Dust.fadeIn, Main.hslToRgb(), ABasicParticle.LocalPosition, ParticleOrchestraSettings.MovementVector, Dust.NewDust(), Dust.noGravity, Main.ParticleSystem_World_OverPlayers, ParticleOrchestraSettings.PositionInWorld, Main.rand, ParticlePool< T >.RequestParticle(), ABasicParticle.Rotation, ABasicParticle.Scale, Dust.scale, ABasicParticle.Velocity, and Dust.velocity.
Referenced by SpawnParticlesDirect().