Terraria: ParticleOrchestrator.Spawn_TrueExcalibur
Spawn_TrueExcalibur()
static void ParticleOrchestrator.Spawn_TrueExcalibur (ParticleOrchestraSettings settings) inline static private
     {
         float num = 36f;
         float num2 = (float)Math.PI / 4f;
         for (float num3 = 0f; num3 < 2f; num3 += 1f)
         {
             PrettySparkleParticle prettySparkleParticle = _poolPrettySparkle.RequestParticle();
             Vector2 v = ((float)Math.PI / 2f * num3 + num2).ToRotationVector2() * 4f;
             prettySparkleParticle.ColorTint = new Color(1f, 0f, 0.3f, 1f);
             prettySparkleParticle.LocalPosition = settings.PositionInWorld;
             prettySparkleParticle.Rotation = v.ToRotation();
             prettySparkleParticle.Scale = new Vector2(5f, 0.5f) * 1.1f;
             prettySparkleParticle.FadeInNormalizedTime = 5E-06f;
             prettySparkleParticle.FadeOutNormalizedTime = 0.95f;
             prettySparkleParticle.TimeToLive = num;
             prettySparkleParticle.FadeOutEnd = num;
             prettySparkleParticle.FadeInEnd = num / 2f;
             prettySparkleParticle.FadeOutStart = num / 2f;
             prettySparkleParticle.AdditiveAmount = 0.35f;
             prettySparkleParticle.DrawVerticalAxis = false;
             Main.ParticleSystem_World_OverPlayers.Add(prettySparkleParticle);
         }
         for (float num4 = 0f; num4 < 2f; num4 += 1f)
         {
             PrettySparkleParticle prettySparkleParticle2 = _poolPrettySparkle.RequestParticle();
             Vector2 vector = ((float)Math.PI / 2f * num4 + num2).ToRotationVector2() * 4f;
             prettySparkleParticle2.ColorTint = new Color(1f, 0.5f, 0.8f, 1f);
             prettySparkleParticle2.LocalPosition = settings.PositionInWorld;
             prettySparkleParticle2.Rotation = vector.ToRotation();
             prettySparkleParticle2.Scale = new Vector2(3f, 0.5f) * 0.7f;
             prettySparkleParticle2.FadeInNormalizedTime = 5E-06f;
             prettySparkleParticle2.FadeOutNormalizedTime = 0.95f;
             prettySparkleParticle2.TimeToLive = num;
             prettySparkleParticle2.FadeOutEnd = num;
             prettySparkleParticle2.FadeInEnd = num / 2f;
             prettySparkleParticle2.FadeOutStart = num / 2f;
             prettySparkleParticle2.DrawVerticalAxis = false;
             Main.ParticleSystem_World_OverPlayers.Add(prettySparkleParticle2);
             for (int i = 0; i < 1; i++)
             {
                 if (Main.rand.Next(2) != 0)
                 {
                     Dust dust = Dust.NewDustPerfect(settings.PositionInWorld, 242, vector.RotatedBy(Main.rand.NextFloatDirection() * ((float)Math.PI * 2f) * 0.025f) * Main.rand.NextFloat());
                     dust.noGravity = true;
                     dust.scale = 1.4f;
                     Dust dust2 = Dust.NewDustPerfect(settings.PositionInWorld, 242, -vector.RotatedBy(Main.rand.NextFloatDirection() * ((float)Math.PI * 2f) * 0.025f) * Main.rand.NextFloat());
                     dust2.noGravity = true;
                     dust2.scale = 1.4f;
                 }
             }
         }
         num = 30f;
         num2 = 0f;
         for (float num5 = 0f; num5 < 4f; num5 += 1f)
         {
             PrettySparkleParticle prettySparkleParticle3 = _poolPrettySparkle.RequestParticle();
             Vector2 vector2 = ((float)Math.PI / 2f * num5 + num2).ToRotationVector2() * 4f;
             prettySparkleParticle3.ColorTint = new Color(0.9f, 0.85f, 0.4f, 0.5f);
             prettySparkleParticle3.LocalPosition = settings.PositionInWorld;
             prettySparkleParticle3.Rotation = vector2.ToRotation();
             prettySparkleParticle3.Scale = new Vector2((num5 % 2f == 0f) ? 2f : 4f, 0.5f) * 1.1f;
             prettySparkleParticle3.FadeInNormalizedTime = 5E-06f;
             prettySparkleParticle3.FadeOutNormalizedTime = 0.95f;
             prettySparkleParticle3.TimeToLive = num;
             prettySparkleParticle3.FadeOutEnd = num;
             prettySparkleParticle3.FadeInEnd = num / 2f;
             prettySparkleParticle3.FadeOutStart = num / 2f;
             prettySparkleParticle3.AdditiveAmount = 0.35f;
             prettySparkleParticle3.Velocity = -vector2 * 0.2f;
             prettySparkleParticle3.DrawVerticalAxis = false;
             if (num5 % 2f == 1f)
             {
                 prettySparkleParticle3.Scale *= 1.5f;
                 prettySparkleParticle3.Velocity *= 1.5f;
             }
             Main.ParticleSystem_World_OverPlayers.Add(prettySparkleParticle3);
         }
         for (float num6 = 0f; num6 < 4f; num6 += 1f)
         {
             PrettySparkleParticle prettySparkleParticle4 = _poolPrettySparkle.RequestParticle();
             Vector2 vector3 = ((float)Math.PI / 2f * num6 + num2).ToRotationVector2() * 4f;
             prettySparkleParticle4.ColorTint = new Color(1f, 1f, 0.2f, 1f);
             prettySparkleParticle4.LocalPosition = settings.PositionInWorld;
             prettySparkleParticle4.Rotation = vector3.ToRotation();
             prettySparkleParticle4.Scale = new Vector2((num6 % 2f == 0f) ? 2f : 4f, 0.5f) * 0.7f;
             prettySparkleParticle4.FadeInNormalizedTime = 5E-06f;
             prettySparkleParticle4.FadeOutNormalizedTime = 0.95f;
             prettySparkleParticle4.TimeToLive = num;
             prettySparkleParticle4.FadeOutEnd = num;
             prettySparkleParticle4.FadeInEnd = num / 2f;
             prettySparkleParticle4.FadeOutStart = num / 2f;
             prettySparkleParticle4.Velocity = vector3 * 0.2f;
             prettySparkleParticle4.DrawVerticalAxis = false;
             if (num6 % 2f == 1f)
             {
                 prettySparkleParticle4.Scale *= 1.5f;
                 prettySparkleParticle4.Velocity *= 1.5f;
             }
             Main.ParticleSystem_World_OverPlayers.Add(prettySparkleParticle4);
             for (int j = 0; j < 1; j++)
             {
                 if (Main.rand.Next(2) != 0)
                 {
                     Dust dust3 = Dust.NewDustPerfect(settings.PositionInWorld, 169, vector3.RotatedBy(Main.rand.NextFloatDirection() * ((float)Math.PI * 2f) * 0.025f) * Main.rand.NextFloat());
                     dust3.noGravity = true;
                     dust3.scale = 1.4f;
                     Dust dust4 = Dust.NewDustPerfect(settings.PositionInWorld, 169, -vector3.RotatedBy(Main.rand.NextFloatDirection() * ((float)Math.PI * 2f) * 0.025f) * Main.rand.NextFloat());
                     dust4.noGravity = true;
                     dust4.scale = 1.4f;
                 }
             }
         }
     }
References _poolPrettySparkle, ParticleRenderer.Add(), PrettySparkleParticle.AdditiveAmount, Color, PrettySparkleParticle.ColorTint, PrettySparkleParticle.DrawVerticalAxis, E, PrettySparkleParticle.FadeInEnd, PrettySparkleParticle.FadeInNormalizedTime, PrettySparkleParticle.FadeOutEnd, PrettySparkleParticle.FadeOutNormalizedTime, PrettySparkleParticle.FadeOutStart, ABasicParticle.LocalPosition, Dust.NewDustPerfect(), UnifiedRandom.Next(), Dust.noGravity, Main.ParticleSystem_World_OverPlayers, ParticleOrchestraSettings.PositionInWorld, Main.rand, ParticlePool< T >.RequestParticle(), ABasicParticle.Rotation, ABasicParticle.Scale, Dust.scale, PrettySparkleParticle.TimeToLive, and ABasicParticle.Velocity.
Referenced by SpawnParticlesDirect().