Terraria: ParticleOrchestrator.Spawn_Keybrand
Spawn_Keybrand()
static void ParticleOrchestrator.Spawn_Keybrand (ParticleOrchestraSettings settings) inline static private
     {
         float num = Main.rand.NextFloat() * ((float)Math.PI * 2f);
         float num2 = 3f;
         Vector2 vector = new Vector2(0.7f);
         for (float num3 = 0f; num3 < 1f; num3 += 1f / num2)
         {
             float num4 = (float)Math.PI * 2f * num3 + num + Main.rand.NextFloatDirection() * 0.1f;
             Vector2 vector2 = 1.5f * vector;
             float num5 = 60f;
             Vector2 vector3 = Main.rand.NextVector2Circular(4f, 4f) * vector;
             PrettySparkleParticle prettySparkleParticle = _poolPrettySparkle.RequestParticle();
             prettySparkleParticle.Velocity = num4.ToRotationVector2() * vector2;
             prettySparkleParticle.AccelerationPerFrame = num4.ToRotationVector2() * -(vector2 / num5);
             prettySparkleParticle.ColorTint = Color.Lerp(Color.Gold, Color.OrangeRed, Main.rand.NextFloat());
             prettySparkleParticle.LocalPosition = settings.PositionInWorld + vector3;
             prettySparkleParticle.Rotation = num4;
             prettySparkleParticle.Scale = vector * 0.8f;
             Main.ParticleSystem_World_OverPlayers.Add(prettySparkleParticle);
         }
         num += 1f / num2 / 2f * ((float)Math.PI * 2f);
         num = Main.rand.NextFloat() * ((float)Math.PI * 2f);
         for (float num6 = 0f; num6 < 1f; num6 += 1f / num2)
         {
             float num7 = (float)Math.PI * 2f * num6 + num + Main.rand.NextFloatDirection() * 0.1f;
             Vector2 vector4 = 1f * vector;
             float num8 = 30f;
             Color value = Color.Lerp(Color.Gold, Color.OrangeRed, Main.rand.NextFloat());
             value = Color.Lerp(Color.White, value, 0.5f);
             value.A = 0;
             Vector2 vector5 = Main.rand.NextVector2Circular(4f, 4f) * vector;
             FadingParticle fadingParticle = _poolFading.RequestParticle();
             fadingParticle.SetBasicInfo(TextureAssets.Extra[98], null, Vector2.Zero, Vector2.Zero);
             fadingParticle.SetTypeInfo(num8);
             fadingParticle.Velocity = num7.ToRotationVector2() * vector4;
             fadingParticle.AccelerationPerFrame = num7.ToRotationVector2() * -(vector4 / num8);
             fadingParticle.ColorTint = value;
             fadingParticle.LocalPosition = settings.PositionInWorld + num7.ToRotationVector2() * vector4 * vector * num8 * 0.2f + vector5;
             fadingParticle.Rotation = num7 + (float)Math.PI / 2f;
             fadingParticle.FadeInNormalizedTime = 0.3f;
             fadingParticle.FadeOutNormalizedTime = 0.4f;
             fadingParticle.Scale = new Vector2(0.5f, 1.2f) * 0.8f * vector;
             Main.ParticleSystem_World_OverPlayers.Add(fadingParticle);
         }
         num2 = 1f;
         num = Main.rand.NextFloat() * ((float)Math.PI * 2f);
         for (float num9 = 0f; num9 < 1f; num9 += 1f / num2)
         {
             float num10 = (float)Math.PI * 2f * num9 + num;
             float typeInfo = 30f;
             Color colorTint = Color.Lerp(Color.CornflowerBlue, Color.White, Main.rand.NextFloat());
             colorTint.A = 127;
             Vector2 vector6 = Main.rand.NextVector2Circular(4f, 4f) * vector;
             Vector2 vector7 = Main.rand.NextVector2Square(0.7f, 1.3f);
             FadingParticle fadingParticle2 = _poolFading.RequestParticle();
             fadingParticle2.SetBasicInfo(TextureAssets.Extra[174], null, Vector2.Zero, Vector2.Zero);
             fadingParticle2.SetTypeInfo(typeInfo);
             fadingParticle2.ColorTint = colorTint;
             fadingParticle2.LocalPosition = settings.PositionInWorld + vector6;
             fadingParticle2.Rotation = num10 + (float)Math.PI / 2f;
             fadingParticle2.FadeInNormalizedTime = 0.1f;
             fadingParticle2.FadeOutNormalizedTime = 0.4f;
             fadingParticle2.Scale = new Vector2(0.1f, 0.1f) * vector;
             fadingParticle2.ScaleVelocity = vector7 * 1f / 60f;
             fadingParticle2.ScaleAcceleration = vector7 * (-1f / 60f) / 60f;
             Main.ParticleSystem_World_OverPlayers.Add(fadingParticle2);
         }
     }
References _poolFading, _poolPrettySparkle, ABasicParticle.AccelerationPerFrame, ParticleRenderer.Add(), Color, FadingParticle.ColorTint, PrettySparkleParticle.ColorTint, TextureAssets.Extra, FadingParticle.FadeInNormalizedTime, FadingParticle.FadeOutNormalizedTime, ABasicParticle.LocalPosition, Main.ParticleSystem_World_OverPlayers, ParticleOrchestraSettings.PositionInWorld, Main.rand, ParticlePool< T >.RequestParticle(), ABasicParticle.Rotation, ABasicParticle.Scale, ABasicParticle.ScaleAcceleration, ABasicParticle.ScaleVelocity, ABasicParticle.SetBasicInfo(), FadingParticle.SetTypeInfo(), and ABasicParticle.Velocity.
Referenced by SpawnParticlesDirect().