Terraria: ParticleOrchestrator.Spawn_ItemTransfer
Spawn_ItemTransfer()
static void ParticleOrchestrator.Spawn_ItemTransfer (ParticleOrchestraSettings settings) inline static private
     {
         Vector2 vector = settings.PositionInWorld + settings.MovementVector;
         Vector2 vector2 = Main.rand.NextVector2Circular(32f, 32f);
         Vector2 vector3 = settings.PositionInWorld + vector2;
         Vector2 vector4 = vector - vector3;
         int uniqueInfoPiece = settings.UniqueInfoPiece;
         if (ContentSamples.ItemsByType.TryGetValue(uniqueInfoPiece, out var value) && !value.IsAir)
         {
             uniqueInfoPiece = value.type;
             int num = Main.rand.Next(60, 80);
             Chest.AskForChestToEatItem(vector3 + vector4 + new Vector2(-8f, -8f), num + 10);
             ItemTransferParticle itemTransferParticle = _poolItemTransfer.RequestParticle();
             itemTransferParticle.Prepare(uniqueInfoPiece, num, vector3, vector3 + vector4);
             Main.ParticleSystem_World_OverPlayers.Add(itemTransferParticle);
         }
     }
References _poolItemTransfer, ParticleRenderer.Add(), Chest.AskForChestToEatItem(), ContentSamples.ItemsByType, ParticleOrchestraSettings.MovementVector, UnifiedRandom.Next(), Main.ParticleSystem_World_OverPlayers, ParticleOrchestraSettings.PositionInWorld, ItemTransferParticle.Prepare(), Main.rand, ParticlePool< T >.RequestParticle(), and ParticleOrchestraSettings.UniqueInfoPiece.
Referenced by SpawnParticlesDirect().