Terraria: ParticleOrchestrator.Spawn_StardustPunch
Spawn_StardustPunch()
static void ParticleOrchestrator.Spawn_StardustPunch (ParticleOrchestraSettings settings) inline static private
     {
         float num = Main.rand.NextFloat() * ((float)Math.PI * 2f);
         float num2 = 1f;
         for (float num3 = 0f; num3 < 1f; num3 += 1f / num2)
         {
             Vector2 vector = settings.MovementVector * (0.3f + Main.rand.NextFloat() * 0.35f);
             Vector2 vector2 = new Vector2(Main.rand.NextFloat() * 0.4f + 0.4f);
             float f = num + Main.rand.NextFloat() * ((float)Math.PI * 2f);
             float rotation = (float)Math.PI / 2f;
             Vector2 vector3 = 0.1f * vector2;
             float num4 = 60f;
             Vector2 vector4 = Main.rand.NextVector2Circular(8f, 8f) * vector2;
             PrettySparkleParticle prettySparkleParticle = _poolPrettySparkle.RequestParticle();
             prettySparkleParticle.Velocity = f.ToRotationVector2() * vector3 + vector;
             prettySparkleParticle.AccelerationPerFrame = f.ToRotationVector2() * -(vector3 / num4) - vector * 1f / 60f;
             prettySparkleParticle.ColorTint = Main.hslToRgb((0.6f + Main.rand.NextFloat() * 0.05f) % 1f, 1f, 0.4f + Main.rand.NextFloat() * 0.25f);
             prettySparkleParticle.ColorTint.A = 0;
             prettySparkleParticle.LocalPosition = settings.PositionInWorld + vector4;
             prettySparkleParticle.Rotation = rotation;
             prettySparkleParticle.Scale = vector2;
             Main.ParticleSystem_World_OverPlayers.Add(prettySparkleParticle);
             prettySparkleParticle = _poolPrettySparkle.RequestParticle();
             prettySparkleParticle.Velocity = f.ToRotationVector2() * vector3 + vector;
             prettySparkleParticle.AccelerationPerFrame = f.ToRotationVector2() * -(vector3 / num4) - vector * 1f / 30f;
             prettySparkleParticle.ColorTint = new Color(255, 255, 255, 0);
             prettySparkleParticle.LocalPosition = settings.PositionInWorld + vector4;
             prettySparkleParticle.Rotation = rotation;
             prettySparkleParticle.Scale = vector2 * 0.6f;
             Main.ParticleSystem_World_OverPlayers.Add(prettySparkleParticle);
         }
         for (int i = 0; i < 2; i++)
         {
             Color newColor = Main.hslToRgb((0.59f + Main.rand.NextFloat() * 0.05f) % 1f, 1f, 0.4f + Main.rand.NextFloat() * 0.25f);
             int num5 = Dust.NewDust(settings.PositionInWorld, 0, 0, 267, 0f, 0f, 0, newColor);
             Main.dust[num5].velocity = Main.rand.NextVector2Circular(2f, 2f);
             Main.dust[num5].velocity += settings.MovementVector * (0.5f + 0.5f * Main.rand.NextFloat()) * 1.4f;
             Main.dust[num5].noGravity = true;
             Main.dust[num5].scale = 0.6f + Main.rand.NextFloat() * 2f;
             Main.dust[num5].position += Main.rand.NextVector2Circular(16f, 16f);
             if (num5 != 6000)
             {
                 Dust dust = Dust.CloneDust(num5);
                 dust.scale /= 2f;
                 dust.fadeIn *= 0.75f;
                 dust.color = new Color(255, 255, 255, 255);
             }
         }
     }
References _poolPrettySparkle, ABasicParticle.AccelerationPerFrame, ParticleRenderer.Add(), Dust.CloneDust(), Color, Dust.color, PrettySparkleParticle.ColorTint, Main.dust, Dust.fadeIn, Main.hslToRgb(), ABasicParticle.LocalPosition, ParticleOrchestraSettings.MovementVector, Dust.NewDust(), Dust.noGravity, Main.ParticleSystem_World_OverPlayers, Dust.position, ParticleOrchestraSettings.PositionInWorld, Main.rand, ParticlePool< T >.RequestParticle(), ABasicParticle.Rotation, ABasicParticle.Scale, Dust.scale, ABasicParticle.Velocity, and Dust.velocity.
Referenced by SpawnParticlesDirect().