Terraria: System.Diagnostics.DistributedContextPropagator.InjectBaggage
InjectBaggage()
static void System.Diagnostics.DistributedContextPropagator.InjectBaggage (object carrier, IEnumerable< KeyValuePair< string, string > > baggage, PropagatorSetterCallback setter) inline static package inherited
Definition at line 52 of file DistributedContextPropagator.cs.
    {
        using IEnumerator<KeyValuePair<string, string>> enumerator = baggage.GetEnumerator();
        if (enumerator.MoveNext())
        {
            StringBuilder stringBuilder = new StringBuilder();
            do
            {
                KeyValuePair<string, string> current = enumerator.Current;
                stringBuilder.Append(WebUtility.UrlEncode(current.Key)).Append('=').Append(WebUtility.UrlEncode(current.Value))
                    .Append(", ");
            }
            while (enumerator.MoveNext());
            setter(carrier, "Correlation-Context", stringBuilder.ToString(0, stringBuilder.Length - 2));
        }
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.GetEnumerator(), and System.Net.WebUtility.UrlEncode().
Referenced by System.Diagnostics.LegacyPropagator.Inject(), and System.Diagnostics.PassThroughPropagator.Inject().