Terraria: System.RuntimeTypeHandle.GetModule
GetModule()
static RuntimeModule System.RuntimeTypeHandle.GetModule (RuntimeType type) package
Referenced by System.RuntimeType.RuntimeTypeCache.RuntimeTypeCache(), System.Reflection.Associates.AssignAssociates(), System.Reflection.RuntimeEventInfo.CacheEquals(), System.Reflection.RuntimePropertyInfo.CacheEquals(), System.RuntimeTypeHandle.GetModuleHandle(), System.Reflection.RtFieldInfo.GetRuntimeModule(), System.Reflection.RuntimeConstructorInfo.GetRuntimeModule(), System.RuntimeType.GetRuntimeModule(), System.RuntimeType.RuntimeTypeCache.MemberInfoCache< T >.PopulateNestedClasses(), and System.RuntimeType.RuntimeTypeCache.MemberInfoCache< T >.PopulateProperties().