Terraria: System.RuntimeTypeHandle.GetMetadataImport
GetMetadataImport()
static MetadataImport System.RuntimeTypeHandle.GetMetadataImport (RuntimeType type) inline static package
Definition at line 659 of file RuntimeTypeHandle.cs.
    {
        return new MetadataImport(_GetMetadataImport(type), type);
    }
References System.RuntimeTypeHandle._GetMetadataImport(), and System.type.
Referenced by System.RuntimeType.RuntimeTypeCache.GetNameSpace(), System.Reflection.RuntimeParameterInfo.GetParameters(), System.RuntimeType.RuntimeTypeCache.MemberInfoCache< T >.PopulateEvents(), System.RuntimeType.RuntimeTypeCache.MemberInfoCache< T >.PopulateLiteralFields(), and System.RuntimeType.RuntimeTypeCache.MemberInfoCache< T >.PopulateProperties().