Terraria: System.RuntimeTypeHandle.IsTypeDefinition
IsTypeDefinition()
static bool System.RuntimeTypeHandle.IsTypeDefinition (RuntimeType type) inline static package
Definition at line 156 of file RuntimeTypeHandle.cs.
    {
        CorElementType corElementType = GetCorElementType(type);
        if (((int)corElementType < 1 || (int)corElementType >= 15) && corElementType != CorElementType.ELEMENT_TYPE_VALUETYPE && corElementType != CorElementType.ELEMENT_TYPE_CLASS && corElementType != CorElementType.ELEMENT_TYPE_TYPEDBYREF && corElementType != CorElementType.ELEMENT_TYPE_I && corElementType != CorElementType.ELEMENT_TYPE_U && corElementType != CorElementType.ELEMENT_TYPE_OBJECT)
        {
            return false;
        }
        if (HasInstantiation(type) && !IsGenericTypeDefinition(type))
        {
            return false;
        }
        return true;
    }
References System.Runtime.Serialization.Dictionary, System.RuntimeTypeHandle.GetCorElementType(), System.RuntimeTypeHandle.HasInstantiation(), System.RuntimeTypeHandle.IsGenericTypeDefinition(), and System.type.