Terraria: System.RuntimeTypeHandle.Equals
Equals() [1/2]
override bool System.RuntimeTypeHandle.Equals (object? obj) inline
Definition at line 133 of file RuntimeTypeHandle.cs.
    {
        if (!(obj is RuntimeTypeHandle runtimeTypeHandle))
        {
            return false;
        }
        return runtimeTypeHandle.m_type == m_type;
    }
References System.Runtime.Serialization.Dictionary, System.RuntimeTypeHandle.m_type, and System.obj.
Referenced by System.Runtime.Serialization.TypeHandleRefEqualityComparer.Equals(), System.Runtime.InteropServices.DynamicInterfaceCastableHelpers.GetInterfaceImplementation(), System.RuntimeTypeHandle.operator!=(), System.RuntimeTypeHandle.operator!=(), System.RuntimeTypeHandle.operator==(), and System.RuntimeTypeHandle.operator==().