Terraria: System.RuntimeTypeHandle.GetTypeByNameUsingCARules
GetTypeByNameUsingCARules() [1/2]
static void System.RuntimeTypeHandle.GetTypeByNameUsingCARules (string name, QCallModule scope, ObjectHandleOnStack type) private
Referenced by System.Reflection.PseudoCustomAttribute.GetMarshalAsCustomAttribute(), System.RuntimeTypeHandle.GetTypeByNameUsingCARules(), and System.Reflection.CustomAttributeTypedArgument.ResolveType().