Terraria: System.RuntimeTypeHandle.GetNativeHandle
GetNativeHandle()
RuntimeTypeHandle System.RuntimeTypeHandle.GetNativeHandle () inline package
Definition at line 62 of file RuntimeTypeHandle.cs.
    {
        RuntimeType type = m_type;
        if (type == null)
        {
            throw new ArgumentNullException(null, SR.Arg_InvalidHandle);
        }
        return new RuntimeTypeHandle(type);
    }
References System.RuntimeTypeHandle.RuntimeTypeHandle(), System.SR.Arg_InvalidHandle, System.RuntimeTypeHandle.m_type, and System.type.
Referenced by System.RuntimeTypeHandle.ConstructName(), System.RuntimeTypeHandle.FreeGCHandle(), System.RuntimeTypeHandle.GetConstraints(), System.RuntimeTypeHandle.GetGCHandle(), System.RuntimeTypeHandle.GetInstantiationInternal(), System.RuntimeTypeHandle.GetInstantiationPublic(), System.RuntimeTypeHandle.GetInterfaceMethodImplementation(), System.RuntimeTypeHandle.Instantiate(), System.RuntimeTypeHandle.Instantiate(), System.RuntimeTypeHandle.MakeArray(), System.RuntimeTypeHandle.MakeByRef(), System.RuntimeTypeHandle.MakePointer(), System.RuntimeTypeHandle.MakeSZArray(), and System.RuntimeTypeHandle.VerifyInterfaceIsImplemented().