Terraria: System.RuntimeTypeHandle.CreateInstanceForAnotherGenericParameter
CreateInstanceForAnotherGenericParameter() [1/3]
static unsafe object System.RuntimeTypeHandle.CreateInstanceForAnotherGenericParameter ([DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicParameterlessConstructor)] RuntimeType type, RuntimeType genericParameter) inline static package
Definition at line 245 of file RuntimeTypeHandle.cs.
    {
        object o = null;
        IntPtr value = genericParameter.GetTypeHandleInternal().Value;
        CreateInstanceForAnotherGenericParameter(new QCallTypeHandle(ref type), &value, 1, ObjectHandleOnStack.Create(ref o));
        GC.KeepAlive(genericParameter);
        return o;
    }
References System.RuntimeTypeHandle.CreateInstanceForAnotherGenericParameter(), System.Runtime.Serialization.Dictionary, System.GC.KeepAlive(), System.type, and System.value.
Referenced by System.Collections.Generic.ArraySortHelper< TKey, TValue >.CreateArraySortHelper(), System.Collections.Generic.ComparerHelpers.CreateDefaultComparer(), System.Collections.Generic.ComparerHelpers.CreateDefaultEqualityComparer(), System.RuntimeTypeHandle.CreateInstanceForAnotherGenericParameter(), System.RuntimeTypeHandle.CreateInstanceForAnotherGenericParameter(), System.Collections.Generic.ComparerHelpers.TryCreateEnumComparer(), System.Collections.Generic.ComparerHelpers.TryCreateEnumEqualityComparer(), System.Collections.Generic.ComparerHelpers.TryCreateNullableComparer(), and System.Collections.Generic.ComparerHelpers.TryCreateNullableEqualityComparer().