Terraria: System.UInt16.Parse
Parse() [5/13]
static ushort System.UInt16.Parse (ReadOnlySpan< char > s, NumberStyles style, NumberFormatInfo info) inline static private
Definition at line 145 of file UInt16.cs.
    {
        uint result;
        Number.ParsingStatus parsingStatus = Number.TryParseUInt32(s, style, info, out result);
        if (parsingStatus != 0)
        {
            Number.ThrowOverflowOrFormatException(parsingStatus, TypeCode.UInt16);
        }
        if (result > 65535)
        {
            Number.ThrowOverflowException(TypeCode.UInt16);
        }
        return (ushort)result;
    }
References System.info, System.s, System.Number.ThrowOverflowException(), System.Number.ThrowOverflowOrFormatException(), and System.Number.TryParseUInt32().