Terraria: System.UInt16.Parse
Parse() [7/13]
static ushort System.UInt16.Parse (string s) inline static
Definition at line 101 of file UInt16.cs.
    {
        if (s == null)
        {
            ThrowHelper.ThrowArgumentNullException(ExceptionArgument.s);
        }
        return Parse((ReadOnlySpan<char>)s, NumberStyles.Integer, NumberFormatInfo.CurrentInfo);
    }
References System.Globalization.NumberFormatInfo.CurrentInfo, System.UInt16.Parse(), System.s, and System.ThrowHelper.ThrowArgumentNullException().
Referenced by System.UInt16.Parse(), System.UInt16.Parse(), System.UInt16.Parse(), System.UInt16.Parse(), System.UInt16.Parse(), System.UInt16.Parse(), System.UInt16.Parse(), System.UInt16.Parse(), and System.UInt16.Parse().