Terraria: System.Globalization.CalendricalCalculationsHelper.CenturiesFrom1900
CenturiesFrom1900()
static double System.Globalization.CalendricalCalculationsHelper.CenturiesFrom1900 (int gregorianYear) inline static private
Definition at line 146 of file CalendricalCalculationsHelper.cs.
    {
        long numberOfDays = GetNumberOfDays(new DateTime(gregorianYear, 7, 1));
        return (double)(numberOfDays - s_startOf1900Century) / 36525.0;
    }
References System.DateTime, System.Globalization.CalendricalCalculationsHelper.GetNumberOfDays(), and System.Globalization.CalendricalCalculationsHelper.s_startOf1900Century.
Referenced by System.Globalization.CalendricalCalculationsHelper.EphemerisCorrection1800to1899(), and System.Globalization.CalendricalCalculationsHelper.EphemerisCorrection1900to1987().