Terraria: System.Globalization.CalendricalCalculationsHelper.Nutation
Nutation()
static double System.Globalization.CalendricalCalculationsHelper.Nutation (double julianCenturies) inline static private
Definition at line 338 of file CalendricalCalculationsHelper.cs.
    {
        double degree = PolynomialSum(s_coefficientsA, julianCenturies);
        double degree2 = PolynomialSum(s_coefficientsB, julianCenturies);
        return -0.004778 * SinOfDegree(degree) - 0.0003667 * SinOfDegree(degree2);
    }
References System.Globalization.CalendricalCalculationsHelper.PolynomialSum(), System.Globalization.CalendricalCalculationsHelper.s_coefficientsA, System.Globalization.CalendricalCalculationsHelper.s_coefficientsB, and System.Globalization.CalendricalCalculationsHelper.SinOfDegree().
Referenced by System.Globalization.CalendricalCalculationsHelper.Compute().