Terraria: Internal.Cryptography.PinAndClear.Track
Track()
static PinAndClear Internal.Cryptography.PinAndClear.Track (byte[] data) inline static package
Definition at line 12 of file PinAndClear.cs.
    {
        PinAndClear result = default(PinAndClear);
        result._gcHandle = GCHandle.Alloc(data, GCHandleType.Pinned);
        result._data = data;
        return result;
    }
References System.Runtime.InteropServices.GCHandle.Alloc().
Referenced by Internal.Cryptography.Pal.CertificatePal.CopyWithPrivateKey(), Internal.Cryptography.Pal.CertificatePal.CopyWithPrivateKey(), Internal.Cryptography.Pal.CertificatePal.CopyWithPrivateKey(), and Internal.Cryptography.Pal.CertificatePal.CopyWithPrivateKey().