Terraria: PlayerInput.GenerateInputTag_ForCurrentGamemode_WithHacks
GenerateInputTag_ForCurrentGamemode_WithHacks()
static string PlayerInput.GenerateInputTag_ForCurrentGamemode_WithHacks (bool tagForGameplay, string triggerName) inline static
     {
         InputMode inputMode = CurrentInputMode;
         if (inputMode == InputMode.Mouse || inputMode == InputMode.KeyboardUI)
         {
             inputMode = InputMode.Keyboard;
         }
         if (!(triggerName == "SmartSelect"))
         {
             if (triggerName == "SmartCursor" && inputMode == InputMode.Keyboard)
             {
                 return GenerateRawInputList(new List<string> { Keys.LeftAlt.ToString() });
             }
         }
         else if (inputMode == InputMode.Keyboard)
         {
             return GenerateRawInputList(new List<string> { Keys.LeftControl.ToString() });
         }
         return GenerateInputTag_ForCurrentGamemode(tagForGameplay, triggerName);
     }
References CurrentInputMode, GenerateInputTag_ForCurrentGamemode(), and GenerateRawInputList().
Referenced by Lang.CreateDialogSubstitutionObject().