Terraria: PlayerInput.SetZoom_UI
SetZoom_UI()
static void PlayerInput.SetZoom_UI () inline static
     {
         float uIScale = Main.UIScale;
         SetZoom_Scaled(1f / uIScale);
     }
References SetZoom_Scaled(), and Main.UIScale.
Referenced by Main.DoDraw(), Main.DoUpdate(), Main.DoUpdate_WhilePaused(), LegacyMultiplayerClosePlayersOverlay.Draw(), NewMultiplayerClosePlayersOverlay.Draw(), GameInterfaceLayer.Draw(), CaptureInterface.ModeEdgeSelection.Draw(), CaptureInterface.ModeDragBounds.Draw(), CaptureInterface.ModeChangeSettings.Draw(), CaptureInterface.Draw(), Main.DrawInterface(), Main.DrawInterface_10_CheckCaptureManager(), Main.DrawInterface_11_IngameOptionsMenu(), Main.DrawInterface_16_MapOrMinimap(), Main.DrawMap(), AchievementAdvisor.DrawMouseHover(), Main.DrawMouseOver(), Main.DrawNPCChatBubble(), Main.PreDrawMenu(), SetZoom_Context(), CaptureInterface.ModeChangeSettings.Update(), CaptureInterface.Update(), and Player.Update().