Terraria: PlayerInput.UpdateInput
UpdateInput()
static void PlayerInput.UpdateInput () inline static
     {
         SettingsForUI.UpdateCounters();
         Triggers.Reset();
         ScrollWheelValueOld = ScrollWheelValue;
         ScrollWheelValue = 0;
         GamepadThumbstickLeft = Vector2.Zero;
         GamepadThumbstickRight = Vector2.Zero;
         GrappleAndInteractAreShared = (UsingGamepad || SteamDeckIsUsed) && CurrentProfile.InputModes[InputMode.XBoxGamepad].DoGrappleAndInteractShareTheSameKey;
         if (InBuildingMode && !UsingGamepad)
         {
             ExitBuildingMode();
         }
         if (_canReleaseRebindingLock && NavigatorRebindingLock > 0)
         {
             NavigatorRebindingLock--;
             Triggers.Current.UsedMovementKey = false;
             if (NavigatorRebindingLock == 0 && _memoOfLastPoint != -1)
             {
                 UIManageControls.ForceMoveTo = _memoOfLastPoint;
                 _memoOfLastPoint = -1;
             }
         }
         _canReleaseRebindingLock = true;
         VerifyBuildingMode();
         MouseInput();
         int num = 0 | (KeyboardInput() ? 1 : 0) | (GamePadInput() ? 1 : 0);
         Triggers.Update();
         PostInput();
         ScrollWheelDelta = ScrollWheelValue - ScrollWheelValueOld;
         ScrollWheelDeltaForUI = ScrollWheelDelta;
         WritingText = false;
         UpdateMainMouse();
         Main.mouseLeft = Triggers.Current.MouseLeft;
         Main.mouseRight = Triggers.Current.MouseRight;
         CacheZoomableValues();
         if (num != 0 && PlayerInput.OnActionableInput != null)
         {
             PlayerInput.OnActionableInput();
         }
     }
References _canReleaseRebindingLock, _memoOfLastPoint, CacheZoomableValues(), TriggersPack.Current, CurrentProfile, ExitBuildingMode(), UIManageControls.ForceMoveTo, GamePadInput(), GamepadThumbstickLeft, GamepadThumbstickRight, GrappleAndInteractAreShared, InBuildingMode, PlayerInputProfile.InputModes, KeyboardInput(), MouseInput(), TriggersSet.MouseLeft, Main.mouseLeft, TriggersSet.MouseRight, Main.mouseRight, NavigatorRebindingLock, OnActionableInput, PostInput(), TriggersPack.Reset(), ScrollWheelDelta, ScrollWheelDeltaForUI, ScrollWheelValue, ScrollWheelValueOld, SteamDeckIsUsed, Triggers, TriggersPack.Update(), PlayerInput.SettingsForUI.UpdateCounters(), UpdateMainMouse(), TriggersSet.UsedMovementKey, UsingGamepad, VerifyBuildingMode(), and WritingText.
Referenced by Main.DoUpdate_HandleInput().