Terraria: PlayerInput.SetSelectedProfile
SetSelectedProfile()
static void PlayerInput.SetSelectedProfile (string name) inline static
     {
         if (Profiles.ContainsKey(name))
         {
             _selectedProfile = name;
             _currentProfile = Profiles[_selectedProfile];
         }
     }
References _currentProfile, and _selectedProfile.
Referenced by Initialize(), Load(), and UIManageControls.profileButtonClick().