Terraria: PlayerInput.GenerateInputTag_ForCurrentGamemode
GenerateInputTag_ForCurrentGamemode()
static string PlayerInput.GenerateInputTag_ForCurrentGamemode (bool tagForGameplay, string triggerName) inline static
     {
         InputMode inputMode = CurrentInputMode;
         if (inputMode == InputMode.Mouse || inputMode == InputMode.KeyboardUI)
         {
             inputMode = InputMode.Keyboard;
         }
         if (tagForGameplay)
         {
             if ((uint)(inputMode - 3) > 1u)
             {
                 return GenerateRawInputList(CurrentProfile.InputModes[inputMode].KeyStatus[triggerName]);
             }
             return GenerateGlyphList(CurrentProfile.InputModes[InputMode.XBoxGamepad].KeyStatus[triggerName]);
         }
         if ((uint)(inputMode - 3) > 1u)
         {
             return GenerateRawInputList(CurrentProfile.InputModes[inputMode].KeyStatus[triggerName]);
         }
         return GenerateGlyphList(CurrentProfile.InputModes[InputMode.XBoxGamepadUI].KeyStatus[triggerName]);
     }
References CurrentInputMode, CurrentProfile, GenerateGlyphList(), GenerateRawInputList(), and PlayerInputProfile.InputModes.
Referenced by Lang.CreateDialogSubstitutionObject(), GenerateInputTag_ForCurrentGamemode_WithHacks(), UICharacterCreation.MakeCategoriesBar(), and UICharacterCreation.UpdateHelpGlyphs().