Terraria: PlayerInput.CheckRebindingProcessKeyboard
CheckRebindingProcessKeyboard()
static bool PlayerInput.CheckRebindingProcessKeyboard (string newKey) inline static private
     {
         _canReleaseRebindingLock = false;
         if (CurrentlyRebinding && _listeningInputMode == InputMode.Keyboard)
         {
             NavigatorRebindingLock = 3;
             _memoOfLastPoint = UILinkPointNavigator.CurrentPoint;
             SoundEngine.PlaySound(12);
             if (CurrentProfile.InputModes[InputMode.Keyboard].KeyStatus[ListeningTrigger].Contains(newKey))
             {
                 CurrentProfile.InputModes[InputMode.Keyboard].KeyStatus[ListeningTrigger].Remove(newKey);
             }
             else
             {
                 CurrentProfile.InputModes[InputMode.Keyboard].KeyStatus[ListeningTrigger] = new List<string> { newKey };
             }
             ListenFor(null, InputMode.Keyboard);
             Main.blockKey = newKey;
             Main.blockInput = false;
             Main.ChromaPainter.CollectBoundKeys();
         }
         if (CurrentlyRebinding && _listeningInputMode == InputMode.KeyboardUI)
         {
             NavigatorRebindingLock = 3;
             _memoOfLastPoint = UILinkPointNavigator.CurrentPoint;
             SoundEngine.PlaySound(12);
             if (CurrentProfile.InputModes[InputMode.KeyboardUI].KeyStatus[ListeningTrigger].Contains(newKey))
             {
                 CurrentProfile.InputModes[InputMode.KeyboardUI].KeyStatus[ListeningTrigger].Remove(newKey);
             }
             else
             {
                 CurrentProfile.InputModes[InputMode.KeyboardUI].KeyStatus[ListeningTrigger] = new List<string> { newKey };
             }
             ListenFor(null, InputMode.KeyboardUI);
             Main.blockKey = newKey;
             Main.blockInput = false;
             Main.ChromaPainter.CollectBoundKeys();
         }
         FixDerpedRebinds();
         if (PlayerInput.OnBindingChange != null)
         {
             PlayerInput.OnBindingChange();
         }
         return NavigatorRebindingLock > 0;
     }
References _canReleaseRebindingLock, _listeningInputMode, _memoOfLastPoint, Main.blockInput, Main.blockKey, Main.ChromaPainter, ChromaHotkeyPainter.CollectBoundKeys(), CurrentlyRebinding, UILinkPointNavigator.CurrentPoint, CurrentProfile, FixDerpedRebinds(), PlayerInputProfile.InputModes, ListenFor(), ListeningTrigger, NavigatorRebindingLock, OnBindingChange, and SoundEngine.PlaySound().
Referenced by KeyboardInput().