Terraria: PlayerInput.Load
Load()
static void PlayerInput.Load () inline static
     {
         Main.InputProfiles.Load();
         Dictionary<string, PlayerInputProfile> dictionary = new Dictionary<string, PlayerInputProfile>();
         string currentValue = null;
         Main.InputProfiles.Get("Selected Profile", ref currentValue);
         List<string> allKeys = Main.InputProfiles.GetAllKeys();
         for (int i = 0; i < allKeys.Count; i++)
         {
             string text = allKeys[i];
             if (text == "Selected Profile" || string.IsNullOrEmpty(text))
             {
                 continue;
             }
             Dictionary<string, object> currentValue2 = new Dictionary<string, object>();
             Main.InputProfiles.Get(text, ref currentValue2);
             if (currentValue2.Count > 0)
             {
                 PlayerInputProfile playerInputProfile = new PlayerInputProfile(text);
                 playerInputProfile.Initialize(PresetProfiles.None);
                 if (playerInputProfile.Load(currentValue2))
                 {
                     dictionary.Add(text, playerInputProfile);
                 }
             }
         }
         if (dictionary.Count > 0)
         {
             Profiles = dictionary;
             if (!string.IsNullOrEmpty(currentValue) && Profiles.ContainsKey(currentValue))
             {
                 SetSelectedProfile(currentValue);
             }
             else
             {
                 SetSelectedProfile(Profiles.Keys.First());
             }
         }
     }
References Preferences.GetAllKeys(), PlayerInputProfile.Initialize(), Main.InputProfiles, Preferences.Load(), PlayerInputProfile.Load(), and SetSelectedProfile().
Referenced by Main.LoadSettings().