Terraria: PlayerInput.ExitBuildingMode
ExitBuildingMode()
static void PlayerInput.ExitBuildingMode () inline static
     {
         SoundEngine.PlaySound(11);
         _InBuildingMode = false;
         UILinkPointNavigator.ChangePoint(_UIPointForBuildingMode);
         if (Main.mouseItem.stack > 0 && Main.player[Main.myPlayer].itemAnimation == 0)
         {
             int uIPointForBuildingMode = _UIPointForBuildingMode;
             if (uIPointForBuildingMode < 50 && uIPointForBuildingMode >= 0 && Main.player[Main.myPlayer].inventory[uIPointForBuildingMode].stack <= 0)
             {
                 Utils.Swap(ref Main.mouseItem, ref Main.player[Main.myPlayer].inventory[uIPointForBuildingMode]);
             }
         }
         _UIPointForBuildingMode = -1;
     }
References _InBuildingMode, _UIPointForBuildingMode, UILinkPointNavigator.ChangePoint(), Player.inventory, Player.itemAnimation, Main.mouseItem, Main.myPlayer, Main.player, SoundEngine.PlaySound(), and Item.stack.
Referenced by Player.ToggleCreativeMenu(), Player.ToggleInv(), UpdateInput(), and VerifyBuildingMode().