Terraria: PlayerInput.ResetInputsOnActiveStateChange
ResetInputsOnActiveStateChange()
static void PlayerInput.ResetInputsOnActiveStateChange () inline static
     {
         bool isActive = Main.instance.IsActive;
         if (_lastActivityState != isActive)
         {
             MouseInfo = default(MouseState);
             MouseInfoOld = default(MouseState);
             Main.keyState = Keyboard.GetState();
             Main.inputText = Keyboard.GetState();
             Main.oldInputText = Keyboard.GetState();
             Main.keyCount = 0;
             Triggers.Reset();
             Triggers.Reset();
             string text = "";
             List<Keys> pressedKeys = GetPressedKeys();
             for (int i = 0; i < pressedKeys.Count; i++)
             {
                 text = string.Concat(text, pressedKeys[i], ", ");
             }
             _invalidatorCheck = text;
         }
         _lastActivityState = isActive;
     }
References _invalidatorCheck, _lastActivityState, GetPressedKeys(), Main.inputText, Main.instance, Game.IsActive, Keyboard, Main.keyCount, Main.keyState, MouseInfo, MouseInfoOld, Main.oldInputText, TriggersPack.Reset(), and Triggers.
Referenced by Main.DoUpdate().