Terraria: System.Threading.WaitHandle.ObtainSafeWaitHandles
ObtainSafeWaitHandles()
static void System.Threading.WaitHandle.ObtainSafeWaitHandles (ReadOnlySpan< WaitHandle > waitHandles, Span< SafeWaitHandle > safeWaitHandles, Span< IntPtr > unsafeWaitHandles) inline static private
Definition at line 173 of file WaitHandle.cs.
    {
        bool success = true;
        SafeWaitHandle safeWaitHandle = null;
        try
        {
            for (int i = 0; i < waitHandles.Length; i++)
            {
                WaitHandle waitHandle = waitHandles[i];
                if (waitHandle == null)
                {
                    throw new ArgumentNullException("waitHandles[" + i + "]", SR.ArgumentNull_ArrayElement);
                }
                SafeWaitHandle safeWaitHandle2 = waitHandle._waitHandle ?? throw new ObjectDisposedException(null, SR.ObjectDisposed_Generic);
                safeWaitHandle = safeWaitHandle2;
                success = false;
                safeWaitHandle2.DangerousAddRef(ref success);
                safeWaitHandles[i] = safeWaitHandle2;
                unsafeWaitHandles[i] = safeWaitHandle2.DangerousGetHandle();
            }
        }
        catch
        {
            for (int j = 0; j < waitHandles.Length; j++)
            {
                SafeWaitHandle safeWaitHandle3 = safeWaitHandles[j];
                if (safeWaitHandle3 == null)
                {
                    break;
                }
                safeWaitHandle3.DangerousRelease();
                safeWaitHandles[j] = null;
                if (safeWaitHandle3 == safeWaitHandle)
                {
                    safeWaitHandle = null;
                    success = true;
                }
            }
            if (!success)
            {
                safeWaitHandle.DangerousRelease();
            }
            throw;
        }
    }
References System.SR.ArgumentNull_ArrayElement, System.Runtime.InteropServices.SafeHandle.DangerousAddRef(), System.Runtime.InteropServices.SafeHandle.DangerousGetHandle(), System.Runtime.InteropServices.SafeHandle.DangerousRelease(), System.ReadOnlySpan< T >.Length, and System.SR.ObjectDisposed_Generic.
Referenced by System.Threading.WaitHandle.WaitMultiple().