Terraria: System.Threading.WaitHandle.Dispose
Dispose() [2/2]
virtual void System.Threading.WaitHandle.Dispose (bool explicitDisposing) inline protected virtual
Definition at line 112 of file WaitHandle.cs.
    {
        _waitHandle?.Close();
    }
References System.Threading.WaitHandle._waitHandle, and System.Runtime.InteropServices.SafeHandle.Close().
Referenced by System.Threading.ManualResetEventSlim.Dispose(), System.Threading.ReaderWriterLockSlim.Dispose(), System.Threading.SemaphoreSlim.Dispose(), System.Net.NetworkInformation.Ping.InternalDisposeCore(), System.Threading.ReaderWriterLockSlim.LazyCreateEvent(), System.Threading.ManualResetEventSlim.LazyInitializeEvent(), System.Threading.RegisteredWaitHandle.ReturnEvent(), and System.Net.LazyAsyncResult.WaitForCompletion().