Terraria: System.Threading.WaitHandle.RentSafeWaitHandleArray
RentSafeWaitHandleArray()
static SafeWaitHandle[] System.Threading.WaitHandle.RentSafeWaitHandleArray (int capacity) inline static private
Definition at line 156 of file WaitHandle.cs.
    {
        SafeWaitHandle[] array = t_safeWaitHandlesForRent;
        t_safeWaitHandlesForRent = null;
        int num = ((array != null) ? array.Length : 0);
        if (num < capacity)
        {
            array = new SafeWaitHandle[Math.Max(capacity, Math.Min(64, 2 * num))];
        }
        return array;
    }
References System.array, System.capacity, System.Math.Max(), System.Math.Min(), and System.Threading.WaitHandle.t_safeWaitHandlesForRent.
Referenced by System.Threading.WaitHandle.WaitMultiple().