Terraria: System.Threading.WaitHandle.WaitOneNoCheck
WaitOneNoCheck()
bool System.Threading.WaitHandle.WaitOneNoCheck (int millisecondsTimeout) inline private
Definition at line 132 of file WaitHandle.cs.
    {
        SafeWaitHandle safeWaitHandle = _waitHandle ?? throw new ObjectDisposedException(null, SR.ObjectDisposed_Generic);
        bool success = false;
        try
        {
            safeWaitHandle.DangerousAddRef(ref success);
            SynchronizationContext current = SynchronizationContext.Current;
            int num = ((current == null || !current.IsWaitNotificationRequired()) ? WaitOneCore(safeWaitHandle.DangerousGetHandle(), millisecondsTimeout) : current.Wait(new IntPtr[1] { safeWaitHandle.DangerousGetHandle() }, waitAll: false, millisecondsTimeout));
            if (num == 128)
            {
                throw new AbandonedMutexException();
            }
            return num != 258;
        }
        finally
        {
            if (success)
            {
                safeWaitHandle.DangerousRelease();
            }
        }
    }
References System.Threading.WaitHandle._waitHandle, System.Threading.SynchronizationContext.Current, System.Runtime.InteropServices.SafeHandle.DangerousAddRef(), System.Runtime.InteropServices.SafeHandle.DangerousGetHandle(), System.Runtime.InteropServices.SafeHandle.DangerousRelease(), System.Threading.SynchronizationContext.IsWaitNotificationRequired(), System.millisecondsTimeout, System.SR.ObjectDisposed_Generic, System.Threading.SynchronizationContext.Wait(), and System.Threading.WaitHandle.WaitOneCore().
Referenced by System.Threading.WaitHandle.WaitOne(), System.Threading.WaitHandle.WaitOne(), System.Threading.WaitHandle.WaitOne(), and System.Threading.WaitHandle.WaitOne().