Terraria: System.Threading.WaitHandle.WaitAnyMultiple
WaitAnyMultiple()
static int System.Threading.WaitHandle.WaitAnyMultiple (ReadOnlySpan< SafeWaitHandle > safeWaitHandles, int millisecondsTimeout) inline static private
Definition at line 286 of file WaitHandle.cs.
    {
        SynchronizationContext current = SynchronizationContext.Current;
        if (current != null && current.IsWaitNotificationRequired())
        {
            IntPtr[] array = new IntPtr[safeWaitHandles.Length];
            for (int i = 0; i < safeWaitHandles.Length; i++)
            {
                array[i] = safeWaitHandles[i].DangerousGetHandle();
            }
            return current.Wait(array, waitAll: false, millisecondsTimeout);
        }
        Span<IntPtr> waitHandles = stackalloc IntPtr[safeWaitHandles.Length];
        for (int j = 0; j < safeWaitHandles.Length; j++)
        {
            waitHandles[j] = safeWaitHandles[j].DangerousGetHandle();
        }
        return WaitMultipleIgnoringSyncContext(waitHandles, waitAll: false, millisecondsTimeout);
    }
References System.array, System.Threading.SynchronizationContext.Current, System.Threading.SynchronizationContext.IsWaitNotificationRequired(), System.ReadOnlySpan< T >.Length, System.millisecondsTimeout, System.Threading.SynchronizationContext.Wait(), and System.Threading.WaitHandle.WaitMultipleIgnoringSyncContext().
Referenced by System.Threading.WaitHandle.WaitAny().