Terraria: System.Linq.Enumerable.WhereSelectEnumerableIterator.MoveNext
MoveNext()
override bool System.Linq.Enumerable.WhereSelectEnumerableIterator< TSource, TResult >.MoveNext () inline
Definition at line 3338 of file Enumerable.cs.
        {
            int state = _state;
            if (state != 1)
            {
                if (state != 2)
                {
                    goto IL_006c;
                }
            }
            else
            {
                _enumerator = _source.GetEnumerator();
                _state = 2;
            }
            while (_enumerator.MoveNext())
            {
                TSource current = _enumerator.Current;
                if (_predicate(current))
                {
                    _current = _selector(current);
                    return true;
                }
            }
            Dispose();
            goto IL_006c;
            IL_006c:
            return false;
        }
References System.Linq.Enumerable.Iterator< TResult >._current, System.Linq.Enumerable.WhereSelectEnumerableIterator< TSource, TResult >._enumerator, System.Linq.Enumerable.WhereSelectEnumerableIterator< TSource, TResult >._predicate, System.Linq.Enumerable.WhereSelectEnumerableIterator< TSource, TResult >._selector, System.Linq.Enumerable.WhereSelectEnumerableIterator< TSource, TResult >._source, System.Linq.Enumerable.Iterator< TResult >._state, System.Collections.IEnumerator.Current, System.Linq.Enumerable.WhereSelectEnumerableIterator< TSource, TResult >.Dispose(), System.Collections.IEnumerable.GetEnumerator(), System.Collections.IEnumerator.MoveNext(), and System.state.