Terraria: WorldUtils.Find
Find()
static bool WorldUtils.Find (Point origin, GenSearch search, out Point result) inline static
     {
         result = search.Find(origin);
         if (result == GenSearch.NOT_FOUND)
         {
             return false;
         }
         return true;
     }
References GenSearch.Find(), and GenSearch.NOT_FOUND.
Referenced by NPC.AI(), NPC.AI_109_DarkMage(), Projectile.AI_137_LightningAura(), Projectile.AI_140_MonkStaffT1(), HouseUtils.AreRoomsValid(), Projectile.CanHitWithOwnBody(), HouseUtils.CreateRooms(), HouseBuilder.CreateSupportBeamList(), Projectile.Damage(), HouseUtils.FindRoom(), HouseBuilder.FindSideExit(), HouseBuilder.FindVerticalExit(), Player.ItemCheck_Shoot(), CampsiteBiome.Place(), CorruptionPitBiome.Place(), EnchantedSwordBiome.Place(), HoneyPatchBiome.Place(), MahoganyTreeBiome.Place(), MiningExplosivesBiome.Place(), and DD2Event.RaiseGoblins().