Terraria: System.Xml.Serialization.CodeIdentifier.CheckValidIdentifier
CheckValidIdentifier()
static void System.Xml.Serialization.CodeIdentifier.CheckValidIdentifier ([NotNull] string ident) inline static package
Definition at line 135 of file CodeIdentifier.cs.
    {
        if (!CSharpHelpers.IsValidLanguageIndependentIdentifier(ident))
        {
            throw new ArgumentException(System.SR.Format(System.SR.XmlInvalidIdentifier, ident), "ident");
        }
    }
References System.Xml.ArgumentException, System.Xml.Dictionary, System.SR.Format(), System.CSharpHelpers.IsValidLanguageIndependentIdentifier(), and System.SR.XmlInvalidIdentifier.
Referenced by System.Xml.Serialization.CodeIdentifier.EscapeKeywords(), System.Xml.Serialization.XmlSerializationWriterCodeGen.FindChoiceEnumValue(), System.Xml.Serialization.XmlSerializationWriterILGen.FindChoiceEnumValue(), System.Xml.Serialization.XmlSerializationReaderCodeGen.GetChoiceIdentifierSource(), System.Xml.Serialization.XmlSerializationReaderILGen.GetChoiceIdentifierSource(), System.Xml.Serialization.ReflectionAwareCodeGen.GetStringForEnumCompare(), System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteElement(), System.Xml.Serialization.XmlSerializationReaderILGen.WriteElement(), System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteEncodedStructMethod(), System.Xml.Serialization.ReflectionAwareCodeGen.WriteEnumCase(), System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteEnumMethod(), System.Xml.Serialization.XmlSerializationReaderILGen.WriteEnumMethod(), System.Xml.Serialization.XmlSerializationWriterCodeGen.WriteEnumMethod(), System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteHashtable(), System.Xml.Serialization.XmlSerializationReaderILGen.WriteHashtable(), System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteLiteralStructMethod(), System.Xml.Serialization.XmlSerializationReaderILGen.WriteLiteralStructMethod(), System.Xml.Serialization.XmlSerializationWriterCodeGen.WriteStructMethod(), and System.Xml.Serialization.XmlSerializationWriterILGen.WriteStructMethod().