Terraria: System.Xml.Serialization.CodeIdentifier.MakeValid
MakeValid()
static string System.Xml.Serialization.CodeIdentifier.MakeValid (string identifier) inline static
Definition at line 50 of file CodeIdentifier.cs.
    {
        StringBuilder stringBuilder = new StringBuilder();
        for (int i = 0; i < identifier.Length; i++)
        {
            if (stringBuilder.Length >= 511)
            {
                break;
            }
            char c = identifier[i];
            if (IsValid(c))
            {
                if (stringBuilder.Length == 0 && !IsValidStart(c))
                {
                    stringBuilder.Append("Item");
                }
                stringBuilder.Append(c);
            }
        }
        if (stringBuilder.Length == 0)
        {
            return "Item";
        }
        return stringBuilder.ToString();
    }
References System.Xml.Dictionary, System.Xml.Serialization.CodeIdentifier.IsValid(), and System.Xml.Serialization.CodeIdentifier.IsValidStart().
Referenced by System.Xml.Serialization.XmlSerializationCodeGen.GenerateBaseSerializer(), System.Xml.Serialization.XmlSerializationILGen.GenerateBaseSerializer(), System.Xml.Serialization.TempAssembly.GenerateRefEmitAssembly(), System.Xml.Serialization.TempAssembly.GenerateSerializerToStream(), System.Xml.Serialization.XmlSerializationCodeGen.GenerateTypedSerializer(), System.Xml.Serialization.XmlSerializationILGen.GenerateTypedSerializer(), System.Xml.Serialization.XmlSchemaImporter.GenerateUniqueTypeName(), System.Xml.Serialization.SchemaImporter.GenerateUniqueTypeName(), System.Xml.Serialization.XmlSchemaImporter.ImportAttribute(), System.Xml.Serialization.XmlSchemaImporter.ImportAttributeMember(), System.Xml.Serialization.XmlSchemaImporter.ImportElement(), System.Xml.Serialization.XmlSchemaImporter.ImportElementMember(), System.Xml.Serialization.XmlSchemaImporter.ImportEnumeratedChoice(), System.Xml.Serialization.XmlSchemaImporter.ImportEnumeratedDataType(), System.Xml.Serialization.XmlSchemaImporter.ImportMembersMapping(), System.Xml.Serialization.XmlSchemaImporter.ImportSubstitutionGroupMember(), System.Xml.Serialization.TypeScope.ImportTypeDesc(), System.Xml.Serialization.XmlSchemaImporter.ImportXmlnsDeclarationsMember(), System.Xml.Serialization.XmlSchemaImporter.IsCyclicReferencedType(), System.Xml.Serialization.CodeIdentifier.MakeCamel(), System.Xml.Serialization.CodeIdentifier.MakePascal(), and System.Xml.Serialization.CodeIdentifier.MakeValidInternal().