Terraria: System.Xml.Serialization.CodeIdentifier.GetCSharpName
GetCSharpName() [1/3]
static string System.Xml.Serialization.CodeIdentifier.GetCSharpName (string name) inline static package
Definition at line 143 of file CodeIdentifier.cs.
    {
        return EscapeKeywords(name.Replace('+', '.'));
    }
References System.Xml.Serialization.CodeIdentifier.EscapeKeywords().
Referenced by System.Xml.Serialization.XmlSerializationCodeGen.GenerateBaseSerializer(), System.Xml.Serialization.XmlSerializationILGen.GenerateBaseSerializer(), System.Xml.Serialization.XmlSerializationCodeGen.GenerateGetSerializer(), System.Xml.Serialization.XmlSerializationCodeGen.GenerateSupportedTypes(), System.Xml.Serialization.XmlSerializationCodeGen.GenerateTypedSerializer(), System.Xml.Serialization.XmlSerializationILGen.GenerateTypedSerializer(), System.Xml.Serialization.CodeIdentifier.GetCSharpName(), System.Xml.Serialization.ReflectionAwareCodeGen.WriteCollectionInfo(), System.Xml.Serialization.ReflectionAwareCodeGen.WriteDefaultIndexerInit(), System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteHashtable(), and System.Xml.Serialization.XmlSerializationReaderILGen.WriteHashtable().