Terraria: System.Xml.Serialization.CodeIdentifier.EscapeKeywords
EscapeKeywords() [2/2]
static void System.Xml.Serialization.CodeIdentifier.EscapeKeywords (string identifier, StringBuilder sb) inline static private
Definition at line 213 of file CodeIdentifier.cs.
    {
        if (identifier != null && identifier.Length != 0)
        {
            int num = 0;
            while (identifier.EndsWith("[]", StringComparison.Ordinal))
            {
                num++;
                identifier = identifier.Substring(0, identifier.Length - 2);
            }
            if (identifier.Length > 0)
            {
                CheckValidIdentifier(identifier);
                identifier = CSharpHelpers.CreateEscapedIdentifier(identifier);
                sb.Append(identifier);
            }
            for (int i = 0; i < num; i++)
            {
                sb.Append("[]");
            }
        }
    }
References System.Text.StringBuilder.Append(), System.Xml.Serialization.CodeIdentifier.CheckValidIdentifier(), System.CSharpHelpers.CreateEscapedIdentifier(), and System.Xml.Dictionary.
Referenced by System.Xml.Serialization.CodeIdentifier.EscapeKeywords(), System.Xml.Serialization.CodeIdentifier.GetCSharpName(), and System.Xml.Serialization.CodeIdentifier.GetCSharpName().