Terraria: System.Xml.Serialization.CodeIdentifier.GetCSharpName
GetCSharpName() [3/3]
static int System.Xml.Serialization.CodeIdentifier.GetCSharpName (Type t, Type[] parameters, int index, StringBuilder sb) inline static private
Definition at line 148 of file CodeIdentifier.cs.
    {
        if (t.DeclaringType != null && t.DeclaringType != t)
        {
            index = GetCSharpName(t.DeclaringType, parameters, index, sb);
            sb.Append('.');
        }
        string name = t.Name;
        int num = name.IndexOf('`');
        if (num < 0)
        {
            num = name.IndexOf('!');
        }
        if (num > 0)
        {
            EscapeKeywords(name.Substring(0, num), sb);
            sb.Append('<');
            int num2 = int.Parse(name.AsSpan(num + 1), NumberStyles.Integer, CultureInfo.InvariantCulture) + index;
            while (index < num2)
            {
                sb.Append(GetCSharpName(parameters[index]));
                if (index < num2 - 1)
                {
                    sb.Append(',');
                }
                index++;
            }
            sb.Append('>');
        }
        else
        {
            EscapeKeywords(name, sb);
        }
        return index;
    }
References System.Text.StringBuilder.Append(), System.Type.DeclaringType, System.Xml.Dictionary, System.Xml.Serialization.CodeIdentifier.EscapeKeywords(), System.Xml.Serialization.CodeIdentifier.GetCSharpName(), System.index, System.Globalization.CultureInfo.InvariantCulture, and System.Reflection.MemberInfo.Name.