Terraria: System.Reflection.Metadata.Ecma335.MetadataBuilder.SerializeHandle
SerializeHandle() [3/4]
int System.Reflection.Metadata.Ecma335.MetadataBuilder.SerializeHandle (ImmutableArray< int > map, StringHandle handle) inline package
Definition at line 2453 of file MetadataBuilder.cs.
    {
        return map[handle.GetWriterVirtualIndex()];
    }
References System.handle.
Referenced by System.Reflection.Metadata.Ecma335.MetadataBuilder.SerializeAssemblyRefTable(), System.Reflection.Metadata.Ecma335.MetadataBuilder.SerializeAssemblyTable(), System.Reflection.Metadata.Ecma335.MetadataBuilder.SerializeConstantTable(), System.Reflection.Metadata.Ecma335.MetadataBuilder.SerializeCustomAttributeTable(), System.Reflection.Metadata.Ecma335.MetadataBuilder.SerializeCustomDebugInformationTable(), System.Reflection.Metadata.Ecma335.MetadataBuilder.SerializeDeclSecurityTable(), System.Reflection.Metadata.Ecma335.MetadataBuilder.SerializeDocumentTable(), System.Reflection.Metadata.Ecma335.MetadataBuilder.SerializeEventTable(), System.Reflection.Metadata.Ecma335.MetadataBuilder.SerializeExportedTypeTable(), System.Reflection.Metadata.Ecma335.MetadataBuilder.SerializeFieldMarshalTable(), System.Reflection.Metadata.Ecma335.MetadataBuilder.SerializeFieldTable(), System.Reflection.Metadata.Ecma335.MetadataBuilder.SerializeFileTable(), System.Reflection.Metadata.Ecma335.MetadataBuilder.SerializeGenericParamTable(), System.Reflection.Metadata.Ecma335.MetadataBuilder.SerializeImplMapTable(), System.Reflection.Metadata.Ecma335.MetadataBuilder.SerializeImportScopeTable(), System.Reflection.Metadata.Ecma335.MetadataBuilder.SerializeLocalConstantTable(), System.Reflection.Metadata.Ecma335.MetadataBuilder.SerializeLocalVariableTable(), System.Reflection.Metadata.Ecma335.MetadataBuilder.SerializeManifestResourceTable(), System.Reflection.Metadata.Ecma335.MetadataBuilder.SerializeMemberRefTable(), System.Reflection.Metadata.Ecma335.MetadataBuilder.SerializeMethodDebugInformationTable(), System.Reflection.Metadata.Ecma335.MetadataBuilder.SerializeMethodDefTable(), System.Reflection.Metadata.Ecma335.MetadataBuilder.SerializeMethodSpecTable(), System.Reflection.Metadata.Ecma335.MetadataBuilder.SerializeModuleRefTable(), System.Reflection.Metadata.Ecma335.MetadataBuilder.SerializeModuleTable(), System.Reflection.Metadata.Ecma335.MetadataBuilder.SerializeParamTable(), System.Reflection.Metadata.Ecma335.MetadataBuilder.SerializePropertyTable(), System.Reflection.Metadata.Ecma335.MetadataBuilder.SerializeStandAloneSigTable(), System.Reflection.Metadata.Ecma335.MetadataBuilder.SerializeTypeDefTable(), System.Reflection.Metadata.Ecma335.MetadataBuilder.SerializeTypeRefTable(), and System.Reflection.Metadata.Ecma335.MetadataBuilder.SerializeTypeSpecTable().