Terraria: System.Reflection.Metadata.Ecma335.MetadataBuilder.SerializeMetadataHeader
SerializeMetadataHeader()
static void System.Reflection.Metadata.Ecma335.MetadataBuilder.SerializeMetadataHeader (BlobBuilder builder, string metadataVersion, MetadataSizes sizes) inline static package
Definition at line 593 of file MetadataBuilder.cs.
    {
        int count = builder.Count;
        builder.WriteUInt32(1112167234u);
        builder.WriteUInt16(1);
        builder.WriteUInt16(1);
        builder.WriteUInt32(0u);
        builder.WriteInt32(sizes.MetadataVersionPaddedLength);
        int count2 = builder.Count;
        builder.WriteUTF8(metadataVersion);
        builder.WriteByte(0);
        int count3 = builder.Count;
        for (int i = 0; i < sizes.MetadataVersionPaddedLength - (count3 - count2); i++)
        {
            builder.WriteByte(0);
        }
        builder.WriteUInt16(0);
        builder.WriteUInt16((ushort)(5 + (sizes.IsEncDelta ? 1 : 0) + (sizes.IsStandaloneDebugMetadata ? 1 : 0)));
        int offsetFromStartOfMetadata = sizes.MetadataHeaderSize;
        if (sizes.IsStandaloneDebugMetadata)
        {
            SerializeStreamHeader(ref offsetFromStartOfMetadata, sizes.StandalonePdbStreamSize, "#Pdb", builder);
        }
        SerializeStreamHeader(ref offsetFromStartOfMetadata, sizes.MetadataTableStreamSize, sizes.IsCompressed ? "#~" : "#-", builder);
        SerializeStreamHeader(ref offsetFromStartOfMetadata, sizes.GetAlignedHeapSize(HeapIndex.String), "#Strings", builder);
        SerializeStreamHeader(ref offsetFromStartOfMetadata, sizes.GetAlignedHeapSize(HeapIndex.UserString), "#US", builder);
        SerializeStreamHeader(ref offsetFromStartOfMetadata, sizes.GetAlignedHeapSize(HeapIndex.Guid), "#GUID", builder);
        SerializeStreamHeader(ref offsetFromStartOfMetadata, sizes.GetAlignedHeapSize(HeapIndex.Blob), "#Blob", builder);
        if (sizes.IsEncDelta)
        {
            SerializeStreamHeader(ref offsetFromStartOfMetadata, 0, "#JTD", builder);
        }
        int count4 = builder.Count;
    }
References System.count, System.Collections.Generic.Dictionary< TKey, TValue >.Count, and System.Reflection.Metadata.Ecma335.MetadataBuilder.SerializeStreamHeader().
Referenced by System.Reflection.Metadata.Ecma335.PortablePdbBuilder.Serialize(), and System.Reflection.Metadata.Ecma335.MetadataRootBuilder.Serialize().