Terraria: System.Reflection.Metadata.Ecma335.MetadataBuilder.AddMethodDefinition
AddMethodDefinition()
MethodDefinitionHandle System.Reflection.Metadata.Ecma335.MetadataBuilder.AddMethodDefinition (MethodAttributes attributes, MethodImplAttributes implAttributes, StringHandle name, BlobHandle signature, int bodyOffset, ParameterHandle parameterList) inline
Definition at line 1288 of file MetadataBuilder.cs.
    {
        if (bodyOffset < -1)
        {
            Throw.ArgumentOutOfRange("bodyOffset");
        }
        _methodDefTable.Add(new MethodRow
        {
            Flags = (ushort)attributes,
            ImplFlags = (ushort)implAttributes,
            Name = name,
            Signature = signature,
            BodyOffset = bodyOffset,
            ParamList = parameterList.RowId
        });
        return MethodDefinitionHandle.FromRowId(_methodDefTable.Count);
    }
References System.Reflection.Metadata.Ecma335.MetadataBuilder._methodDefTable, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Reflection.Throw.ArgumentOutOfRange(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Reflection.Metadata.MethodDefinitionHandle.FromRowId(), and System.Reflection.Name.