Terraria: System.Reflection.Metadata.Ecma335.MetadataBuilder.SerializeMetadataTables
SerializeMetadataTables()
void System.Reflection.Metadata.Ecma335.MetadataBuilder.SerializeMetadataTables (BlobBuilder writer, MetadataSizes metadataSizes, ImmutableArray< int > stringMap, int methodBodyStreamRva, int mappedFieldDataStreamRva) inline package
Definition at line 1660 of file MetadataBuilder.cs.
    {
        int count = writer.Count;
        SerializeTablesHeader(writer, metadataSizes);
        if (metadataSizes.IsPresent(TableIndex.Module))
        {
            SerializeModuleTable(writer, stringMap, metadataSizes);
        }
        if (metadataSizes.IsPresent(TableIndex.TypeRef))
        {
            SerializeTypeRefTable(writer, stringMap, metadataSizes);
        }
        if (metadataSizes.IsPresent(TableIndex.TypeDef))
        {
            SerializeTypeDefTable(writer, stringMap, metadataSizes);
        }
        if (metadataSizes.IsPresent(TableIndex.Field))
        {
            SerializeFieldTable(writer, stringMap, metadataSizes);
        }
        if (metadataSizes.IsPresent(TableIndex.MethodDef))
        {
            SerializeMethodDefTable(writer, stringMap, metadataSizes, methodBodyStreamRva);
        }
        if (metadataSizes.IsPresent(TableIndex.Param))
        {
            SerializeParamTable(writer, stringMap, metadataSizes);
        }
        if (metadataSizes.IsPresent(TableIndex.InterfaceImpl))
        {
            SerializeInterfaceImplTable(writer, metadataSizes);
        }
        if (metadataSizes.IsPresent(TableIndex.MemberRef))
        {
            SerializeMemberRefTable(writer, stringMap, metadataSizes);
        }
        if (metadataSizes.IsPresent(TableIndex.Constant))
        {
            SerializeConstantTable(writer, metadataSizes);
        }
        if (metadataSizes.IsPresent(TableIndex.CustomAttribute))
        {
            SerializeCustomAttributeTable(writer, metadataSizes);
        }
        if (metadataSizes.IsPresent(TableIndex.FieldMarshal))
        {
            SerializeFieldMarshalTable(writer, metadataSizes);
        }
        if (metadataSizes.IsPresent(TableIndex.DeclSecurity))
        {
            SerializeDeclSecurityTable(writer, metadataSizes);
        }
        if (metadataSizes.IsPresent(TableIndex.ClassLayout))
        {
            SerializeClassLayoutTable(writer, metadataSizes);
        }
        if (metadataSizes.IsPresent(TableIndex.FieldLayout))
        {
            SerializeFieldLayoutTable(writer, metadataSizes);
        }
        if (metadataSizes.IsPresent(TableIndex.StandAloneSig))
        {
            SerializeStandAloneSigTable(writer, metadataSizes);
        }
        if (metadataSizes.IsPresent(TableIndex.EventMap))
        {
            SerializeEventMapTable(writer, metadataSizes);
        }
        if (metadataSizes.IsPresent(TableIndex.Event))
        {
            SerializeEventTable(writer, stringMap, metadataSizes);
        }
        if (metadataSizes.IsPresent(TableIndex.PropertyMap))
        {
            SerializePropertyMapTable(writer, metadataSizes);
        }
        if (metadataSizes.IsPresent(TableIndex.Property))
        {
            SerializePropertyTable(writer, stringMap, metadataSizes);
        }
        if (metadataSizes.IsPresent(TableIndex.MethodSemantics))
        {
            SerializeMethodSemanticsTable(writer, metadataSizes);
        }
        if (metadataSizes.IsPresent(TableIndex.MethodImpl))
        {
            SerializeMethodImplTable(writer, metadataSizes);
        }
        if (metadataSizes.IsPresent(TableIndex.ModuleRef))
        {
            SerializeModuleRefTable(writer, stringMap, metadataSizes);
        }
        if (metadataSizes.IsPresent(TableIndex.TypeSpec))
        {
            SerializeTypeSpecTable(writer, metadataSizes);
        }
        if (metadataSizes.IsPresent(TableIndex.ImplMap))
        {
            SerializeImplMapTable(writer, stringMap, metadataSizes);
        }
        if (metadataSizes.IsPresent(TableIndex.FieldRva))
        {
            SerializeFieldRvaTable(writer, metadataSizes, mappedFieldDataStreamRva);
        }
        if (metadataSizes.IsPresent(TableIndex.EncLog))
        {
            SerializeEncLogTable(writer);
        }
        if (metadataSizes.IsPresent(TableIndex.EncMap))
        {
            SerializeEncMapTable(writer);
        }
        if (metadataSizes.IsPresent(TableIndex.Assembly))
        {
            SerializeAssemblyTable(writer, stringMap, metadataSizes);
        }
        if (metadataSizes.IsPresent(TableIndex.AssemblyRef))
        {
            SerializeAssemblyRefTable(writer, stringMap, metadataSizes);
        }
        if (metadataSizes.IsPresent(TableIndex.File))
        {
            SerializeFileTable(writer, stringMap, metadataSizes);
        }
        if (metadataSizes.IsPresent(TableIndex.ExportedType))
        {
            SerializeExportedTypeTable(writer, stringMap, metadataSizes);
        }
        if (metadataSizes.IsPresent(TableIndex.ManifestResource))
        {
            SerializeManifestResourceTable(writer, stringMap, metadataSizes);
        }
        if (metadataSizes.IsPresent(TableIndex.NestedClass))
        {
            SerializeNestedClassTable(writer, metadataSizes);
        }
        if (metadataSizes.IsPresent(TableIndex.GenericParam))
        {
            SerializeGenericParamTable(writer, stringMap, metadataSizes);
        }
        if (metadataSizes.IsPresent(TableIndex.MethodSpec))
        {
            SerializeMethodSpecTable(writer, metadataSizes);
        }
        if (metadataSizes.IsPresent(TableIndex.GenericParamConstraint))
        {
            SerializeGenericParamConstraintTable(writer, metadataSizes);
        }
        if (metadataSizes.IsPresent(TableIndex.Document))
        {
            SerializeDocumentTable(writer, metadataSizes);
        }
        if (metadataSizes.IsPresent(TableIndex.MethodDebugInformation))
        {
            SerializeMethodDebugInformationTable(writer, metadataSizes);
        }
        if (metadataSizes.IsPresent(TableIndex.LocalScope))
        {
            SerializeLocalScopeTable(writer, metadataSizes);
        }
        if (metadataSizes.IsPresent(TableIndex.LocalVariable))
        {
            SerializeLocalVariableTable(writer, stringMap, metadataSizes);
        }
        if (metadataSizes.IsPresent(TableIndex.LocalConstant))
        {
            SerializeLocalConstantTable(writer, stringMap, metadataSizes);
        }
        if (metadataSizes.IsPresent(TableIndex.ImportScope))
        {
            SerializeImportScopeTable(writer, metadataSizes);
        }
        if (metadataSizes.IsPresent(TableIndex.StateMachineMethod))
        {
            SerializeStateMachineMethodTable(writer, metadataSizes);
        }
        if (metadataSizes.IsPresent(TableIndex.CustomDebugInformation))
        {
            SerializeCustomDebugInformationTable(writer, metadataSizes);
        }
        writer.WriteByte(0);
        writer.Align(4);
        int count2 = writer.Count;
    }
References System.count, System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Reflection.Metadata.Ecma335.MetadataBuilder.SerializeAssemblyRefTable(), System.Reflection.Metadata.Ecma335.MetadataBuilder.SerializeAssemblyTable(), System.Reflection.Metadata.Ecma335.MetadataBuilder.SerializeClassLayoutTable(), System.Reflection.Metadata.Ecma335.MetadataBuilder.SerializeConstantTable(), System.Reflection.Metadata.Ecma335.MetadataBuilder.SerializeCustomAttributeTable(), System.Reflection.Metadata.Ecma335.MetadataBuilder.SerializeCustomDebugInformationTable(), System.Reflection.Metadata.Ecma335.MetadataBuilder.SerializeDeclSecurityTable(), System.Reflection.Metadata.Ecma335.MetadataBuilder.SerializeDocumentTable(), System.Reflection.Metadata.Ecma335.MetadataBuilder.SerializeEncLogTable(), System.Reflection.Metadata.Ecma335.MetadataBuilder.SerializeEncMapTable(), System.Reflection.Metadata.Ecma335.MetadataBuilder.SerializeEventMapTable(), System.Reflection.Metadata.Ecma335.MetadataBuilder.SerializeEventTable(), System.Reflection.Metadata.Ecma335.MetadataBuilder.SerializeExportedTypeTable(), System.Reflection.Metadata.Ecma335.MetadataBuilder.SerializeFieldLayoutTable(), System.Reflection.Metadata.Ecma335.MetadataBuilder.SerializeFieldMarshalTable(), System.Reflection.Metadata.Ecma335.MetadataBuilder.SerializeFieldRvaTable(), System.Reflection.Metadata.Ecma335.MetadataBuilder.SerializeFieldTable(), System.Reflection.Metadata.Ecma335.MetadataBuilder.SerializeFileTable(), System.Reflection.Metadata.Ecma335.MetadataBuilder.SerializeGenericParamConstraintTable(), System.Reflection.Metadata.Ecma335.MetadataBuilder.SerializeGenericParamTable(), System.Reflection.Metadata.Ecma335.MetadataBuilder.SerializeImplMapTable(), System.Reflection.Metadata.Ecma335.MetadataBuilder.SerializeImportScopeTable(), System.Reflection.Metadata.Ecma335.MetadataBuilder.SerializeInterfaceImplTable(), System.Reflection.Metadata.Ecma335.MetadataBuilder.SerializeLocalConstantTable(), System.Reflection.Metadata.Ecma335.MetadataBuilder.SerializeLocalScopeTable(), System.Reflection.Metadata.Ecma335.MetadataBuilder.SerializeLocalVariableTable(), System.Reflection.Metadata.Ecma335.MetadataBuilder.SerializeManifestResourceTable(), System.Reflection.Metadata.Ecma335.MetadataBuilder.SerializeMemberRefTable(), System.Reflection.Metadata.Ecma335.MetadataBuilder.SerializeMethodDebugInformationTable(), System.Reflection.Metadata.Ecma335.MetadataBuilder.SerializeMethodDefTable(), System.Reflection.Metadata.Ecma335.MetadataBuilder.SerializeMethodImplTable(), System.Reflection.Metadata.Ecma335.MetadataBuilder.SerializeMethodSemanticsTable(), System.Reflection.Metadata.Ecma335.MetadataBuilder.SerializeMethodSpecTable(), System.Reflection.Metadata.Ecma335.MetadataBuilder.SerializeModuleRefTable(), System.Reflection.Metadata.Ecma335.MetadataBuilder.SerializeModuleTable(), System.Reflection.Metadata.Ecma335.MetadataBuilder.SerializeNestedClassTable(), System.Reflection.Metadata.Ecma335.MetadataBuilder.SerializeParamTable(), System.Reflection.Metadata.Ecma335.MetadataBuilder.SerializePropertyMapTable(), System.Reflection.Metadata.Ecma335.MetadataBuilder.SerializePropertyTable(), System.Reflection.Metadata.Ecma335.MetadataBuilder.SerializeStandAloneSigTable(), System.Reflection.Metadata.Ecma335.MetadataBuilder.SerializeStateMachineMethodTable(), System.Reflection.Metadata.Ecma335.MetadataBuilder.SerializeTablesHeader(), System.Reflection.Metadata.Ecma335.MetadataBuilder.SerializeTypeDefTable(), System.Reflection.Metadata.Ecma335.MetadataBuilder.SerializeTypeRefTable(), System.Reflection.Metadata.Ecma335.MetadataBuilder.SerializeTypeSpecTable(), and System.writer.
Referenced by System.Reflection.Metadata.Ecma335.PortablePdbBuilder.Serialize(), and System.Reflection.Metadata.Ecma335.MetadataRootBuilder.Serialize().