Terraria: System.Reflection.Metadata.Ecma335.MetadataBuilder.AddManifestResource
AddManifestResource()
ManifestResourceHandle System.Reflection.Metadata.Ecma335.MetadataBuilder.AddManifestResource (ManifestResourceAttributes attributes, StringHandle name, EntityHandle implementation, uint offset) inline
Definition at line 1339 of file MetadataBuilder.cs.
    {
        _manifestResourceTable.Add(new ManifestResourceRow
        {
            Flags = (uint)attributes,
            Name = name,
            Implementation = ((!implementation.IsNil) ? CodedIndex.Implementation(implementation) : 0),
            Offset = offset
        });
        return ManifestResourceHandle.FromRowId(_manifestResourceTable.Count);
    }
References System.Reflection.Metadata.Ecma335.MetadataBuilder._manifestResourceTable, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Reflection.Metadata.ManifestResourceHandle.FromRowId(), System.Reflection.Metadata.Ecma335.CodedIndex.Implementation(), System.Reflection.Metadata.Ecma335.Implementation, System.Reflection.Name, and System.offset.