Terraria: System.Reflection.Metadata.Ecma335.MetadataBuilder.AddConstant
AddConstant()
ConstantHandle System.Reflection.Metadata.Ecma335.MetadataBuilder.AddConstant (EntityHandle parent, object? value) inline
Definition at line 1142 of file MetadataBuilder.cs.
    {
        int num = CodedIndex.HasConstant(parent);
        _constantTableNeedsSorting |= num < _constantTableLastParent;
        _constantTableLastParent = num;
        _constantTable.Add(new ConstantRow
        {
            Type = (byte)MetadataWriterUtilities.GetConstantTypeCode(value),
            Parent = num,
            Value = GetOrAddConstantBlob(value)
        });
        return ConstantHandle.FromRowId(_constantTable.Count);
    }
References System.Reflection.Metadata.Ecma335.MetadataBuilder._constantTable, System.Reflection.Metadata.Ecma335.MetadataBuilder._constantTableLastParent, System.Reflection.Metadata.Ecma335.MetadataBuilder._constantTableNeedsSorting, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Reflection.Metadata.ConstantHandle.FromRowId(), System.Reflection.Metadata.Ecma335.MetadataWriterUtilities.GetConstantTypeCode(), System.Reflection.Metadata.Ecma335.MetadataBuilder.GetOrAddConstantBlob(), System.Reflection.Metadata.Ecma335.CodedIndex.HasConstant(), and System.value.