Terraria: System.Reflection.Metadata.Ecma335.MetadataBuilder.GetOrAddBlobUTF8
GetOrAddBlobUTF8()
BlobHandle System.Reflection.Metadata.Ecma335.MetadataBuilder.GetOrAddBlobUTF8 (string value, bool allowUnpairedSurrogates = true) inline
Definition at line 2528 of file MetadataBuilder.cs.
    {
        PooledBlobBuilder instance = PooledBlobBuilder.GetInstance();
        instance.WriteUTF8(value, allowUnpairedSurrogates);
        BlobHandle orAddBlob = GetOrAddBlob(instance);
        instance.Free();
        return orAddBlob;
    }
References System.Reflection.Metadata.PooledBlobBuilder.Free(), System.Reflection.Metadata.PooledBlobBuilder.GetInstance(), System.Reflection.Metadata.Ecma335.MetadataBuilder.GetOrAddBlob(), System.value, and System.Reflection.Metadata.BlobBuilder.WriteUTF8().