Terraria: System.Reflection.Metadata.Ecma335.MetadataBuilder.GetOrAddString
GetOrAddString()
StringHandle System.Reflection.Metadata.Ecma335.MetadataBuilder.GetOrAddString (string value) inline
Definition at line 2622 of file MetadataBuilder.cs.
    {
        if (value == null)
        {
            Throw.ArgumentNull("value");
        }
        StringHandle value2;
        if (value.Length == 0)
        {
            value2 = default(StringHandle);
        }
        else if (!_strings.TryGetValue(value, out value2))
        {
            value2 = StringHandle.FromWriterVirtualIndex(_strings.Count + 1);
            _strings.Add(value, value2);
        }
        return value2;
    }
References System.Reflection.Metadata.Ecma335.MetadataBuilder._strings, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Reflection.Throw.ArgumentNull(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Reflection.Metadata.StringHandle.FromWriterVirtualIndex(), System.Collections.Generic.Dictionary< TKey, TValue >.TryGetValue(), and System.value.