Terraria: System.Reflection.Metadata.Ecma335.MetadataBuilder._paramTable
_paramTable
readonly List<ParamRow> System.Reflection.Metadata.Ecma335.MetadataBuilder._paramTable = new List<ParamRow>() private
Definition at line 530 of file MetadataBuilder.cs.
Referenced by System.Reflection.Metadata.Ecma335.MetadataBuilder.AddParameter(), System.Reflection.Metadata.Ecma335.MetadataBuilder.GetRowCount(), System.Reflection.Metadata.Ecma335.MetadataBuilder.GetRowCounts(), System.Reflection.Metadata.Ecma335.MetadataBuilder.SerializeParamTable(), and System.Reflection.Metadata.Ecma335.MetadataBuilder.SetCapacity().