Terraria: System.Reflection.Metadata.Ecma335.MetadataBuilder.AddExportedType
AddExportedType()
ExportedTypeHandle System.Reflection.Metadata.Ecma335.MetadataBuilder.AddExportedType (TypeAttributes attributes, StringHandle @ namespace, StringHandle name, EntityHandle implementation, int typeDefinitionId) inline
Definition at line 1362 of file MetadataBuilder.cs.
    {
        _exportedTypeTable.Add(new ExportedTypeRow
        {
            Flags = (uint)attributes,
            Implementation = CodedIndex.Implementation(implementation),
            TypeNamespace = @namespace,
            TypeName = name,
            TypeDefId = typeDefinitionId
        });
        return ExportedTypeHandle.FromRowId(_exportedTypeTable.Count);
    }
References System.Reflection.Metadata.Ecma335.MetadataBuilder._exportedTypeTable, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Reflection.Metadata.ExportedTypeHandle.FromRowId(), System.Reflection.Metadata.Ecma335.CodedIndex.Implementation(), and System.Reflection.Metadata.Ecma335.Implementation.