Terraria: System.Reflection.Metadata.Ecma335.MetadataBuilder.MetadataBuilder
MetadataBuilder()
System.Reflection.Metadata.Ecma335.MetadataBuilder.MetadataBuilder (int userStringHeapStartOffset = 0, int stringHeapStartOffset = 0, int blobHeapStartOffset = 0, int guidHeapStartOffset = 0) inline
Definition at line 2393 of file MetadataBuilder.cs.
    {
        if (userStringHeapStartOffset >= 16777215)
        {
            Throw.HeapSizeLimitExceeded(HeapIndex.UserString);
        }
        if (userStringHeapStartOffset < 0)
        {
            Throw.ArgumentOutOfRange("userStringHeapStartOffset");
        }
        if (stringHeapStartOffset < 0)
        {
            Throw.ArgumentOutOfRange("stringHeapStartOffset");
        }
        if (blobHeapStartOffset < 0)
        {
            Throw.ArgumentOutOfRange("blobHeapStartOffset");
        }
        if (guidHeapStartOffset < 0)
        {
            Throw.ArgumentOutOfRange("guidHeapStartOffset");
        }
        if (guidHeapStartOffset % 16 != 0)
        {
            throw new ArgumentException(System.SR.Format(System.SR.ValueMustBeMultiple, 16), "guidHeapStartOffset");
        }
        _userStringBuilder.WriteByte(0);
        _blobs.Add(ImmutableArray<byte>.Empty, default(BlobHandle));
        _blobHeapSize = 1;
        _userStringHeapStartOffset = userStringHeapStartOffset;
        _stringHeapStartOffset = stringHeapStartOffset;
        _blobHeapStartOffset = blobHeapStartOffset;
        _guidBuilder.WriteBytes(0, guidHeapStartOffset);
    }
References System.Reflection.Metadata.Ecma335.MetadataBuilder._blobHeapSize, System.Reflection.Metadata.Ecma335.MetadataBuilder._blobHeapStartOffset, System.Reflection.Metadata.Ecma335.MetadataBuilder._blobs, System.Reflection.Metadata.Ecma335.MetadataBuilder._guidBuilder, System.Reflection.Metadata.Ecma335.MetadataBuilder._stringHeapStartOffset, System.Reflection.Metadata.Ecma335.MetadataBuilder._userStringBuilder, System.Reflection.Metadata.Ecma335.MetadataBuilder._userStringHeapStartOffset, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Reflection.Throw.ArgumentOutOfRange(), System.SR.Format(), System.Reflection.Throw.HeapSizeLimitExceeded(), System.SR.ValueMustBeMultiple, System.Reflection.Metadata.BlobBuilder.WriteByte(), and System.Reflection.Metadata.BlobBuilder.WriteBytes().