Terraria: System.Reflection.Metadata.Ecma335.MetadataBuilder.GetSerializedMetadata
GetSerializedMetadata()
SerializedMetadata System.Reflection.Metadata.Ecma335.MetadataBuilder.GetSerializedMetadata (ImmutableArray< int > externalRowCounts, int metadataVersionByteCount, bool isStandaloneDebugMetadata) inline package
Definition at line 584 of file MetadataBuilder.cs.
    {
        HeapBlobBuilder heapBlobBuilder = new HeapBlobBuilder(_stringHeapCapacity);
        ImmutableArray<int> stringMap = SerializeStringHeap(heapBlobBuilder, _strings, _stringHeapStartOffset);
        ImmutableArray<int> heapSizes = ImmutableArray.Create(_userStringBuilder.Count, heapBlobBuilder.Count, _blobHeapSize, _guidBuilder.Count);
        MetadataSizes sizes = new MetadataSizes(GetRowCounts(), externalRowCounts, heapSizes, metadataVersionByteCount, isStandaloneDebugMetadata);
        return new SerializedMetadata(sizes, heapBlobBuilder, stringMap);
    }
References System.Reflection.Metadata.Ecma335.MetadataBuilder._blobHeapSize, System.Reflection.Metadata.Ecma335.MetadataBuilder._guidBuilder, System.Reflection.Metadata.Ecma335.MetadataBuilder._stringHeapCapacity, System.Reflection.Metadata.Ecma335.MetadataBuilder._stringHeapStartOffset, System.Reflection.Metadata.Ecma335.MetadataBuilder._strings, System.Reflection.Metadata.Ecma335.MetadataBuilder._userStringBuilder, System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Reflection.Metadata.BlobBuilder.Count, System.Reflection.Metadata.Ecma335.MetadataBuilder.GetRowCounts(), and System.Reflection.Metadata.Ecma335.MetadataBuilder.SerializeStringHeap().
Referenced by System.Reflection.Metadata.Ecma335.MetadataRootBuilder.MetadataRootBuilder().