Terraria: System.Reflection.Metadata.Ecma335.MetadataBuilder.WriteHeapsTo
WriteHeapsTo()
void System.Reflection.Metadata.Ecma335.MetadataBuilder.WriteHeapsTo (BlobBuilder builder, BlobBuilder stringHeap) inline package
Definition at line 2706 of file MetadataBuilder.cs.
    {
        WriteAligned(stringHeap, builder);
        WriteAligned(_userStringBuilder, builder);
        WriteAligned(_guidBuilder, builder);
        WriteAlignedBlobHeap(builder);
    }
References System.Reflection.Metadata.Ecma335.MetadataBuilder._guidBuilder, System.Reflection.Metadata.Ecma335.MetadataBuilder._userStringBuilder, System.Reflection.Metadata.Ecma335.MetadataBuilder.WriteAligned(), and System.Reflection.Metadata.Ecma335.MetadataBuilder.WriteAlignedBlobHeap().
Referenced by System.Reflection.Metadata.Ecma335.PortablePdbBuilder.Serialize(), and System.Reflection.Metadata.Ecma335.MetadataRootBuilder.Serialize().