Terraria: System.Reflection.Metadata.Ecma335.MetadataBuilder.AddCustomAttribute
AddCustomAttribute()
CustomAttributeHandle System.Reflection.Metadata.Ecma335.MetadataBuilder.AddCustomAttribute (EntityHandle parent, EntityHandle constructor, BlobHandle value) inline
Definition at line 1169 of file MetadataBuilder.cs.
    {
        int num = CodedIndex.HasCustomAttribute(parent);
        _customAttributeTableNeedsSorting |= num < _customAttributeTableLastParent;
        _customAttributeTableLastParent = num;
        _customAttributeTable.Add(new CustomAttributeRow
        {
            Parent = num,
            Type = CodedIndex.CustomAttributeType(constructor),
            Value = value
        });
        return CustomAttributeHandle.FromRowId(_customAttributeTable.Count);
    }
References System.Reflection.Metadata.Ecma335.MetadataBuilder._customAttributeTable, System.Reflection.Metadata.Ecma335.MetadataBuilder._customAttributeTableLastParent, System.Reflection.Metadata.Ecma335.MetadataBuilder._customAttributeTableNeedsSorting, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Reflection.Metadata.Ecma335.CodedIndex.CustomAttributeType(), System.Reflection.Metadata.CustomAttributeHandle.FromRowId(), System.Reflection.Metadata.Ecma335.CodedIndex.HasCustomAttribute(), and System.value.