Terraria: System.Reflection.Metadata.Ecma335.MetadataBuilder.AddTypeDefinition
AddTypeDefinition()
TypeDefinitionHandle System.Reflection.Metadata.Ecma335.MetadataBuilder.AddTypeDefinition (TypeAttributes attributes, StringHandle @ namespace, StringHandle name, EntityHandle baseType, FieldDefinitionHandle fieldList, MethodDefinitionHandle methodList) inline
Definition at line 1030 of file MetadataBuilder.cs.
    {
        _typeDefTable.Add(new TypeDefRow
        {
            Flags = (uint)attributes,
            Name = name,
            Namespace = @namespace,
            Extends = ((!baseType.IsNil) ? CodedIndex.TypeDefOrRefOrSpec(baseType) : 0),
            FieldList = fieldList.RowId,
            MethodList = methodList.RowId
        });
        return TypeDefinitionHandle.FromRowId(_typeDefTable.Count);
    }
References System.Reflection.Metadata.Ecma335.MetadataBuilder._typeDefTable, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Reflection.Metadata.TypeDefinitionHandle.FromRowId(), System.Reflection.Name, and System.Reflection.Metadata.Ecma335.CodedIndex.TypeDefOrRefOrSpec().