Terraria: System.Reflection.Metadata.Ecma335.MetadataBuilder.SerializeStringHeap
SerializeStringHeap()
static ImmutableArray< int > System.Reflection.Metadata.Ecma335.MetadataBuilder.SerializeStringHeap (BlobBuilder heapBuilder, Dictionary< string, StringHandle > strings, int stringHeapStartOffset) inline static private
Definition at line 2678 of file MetadataBuilder.cs.
    {
        List<KeyValuePair<string, StringHandle>> list = new List<KeyValuePair<string, StringHandle>>(strings);
        list.Sort(SuffixSort.Instance);
        int num = list.Count + 1;
        ImmutableArray<int>.Builder builder = ImmutableArray.CreateBuilder<int>(num);
        builder.Count = num;
        builder[0] = 0;
        heapBuilder.WriteByte(0);
        string text = string.Empty;
        foreach (KeyValuePair<string, StringHandle> item in list)
        {
            int num2 = stringHeapStartOffset + heapBuilder.Count;
            if (text.EndsWith(item.Key, StringComparison.Ordinal) && !BlobUtilities.IsLowSurrogateChar(item.Key[0]))
            {
                builder[item.Value.GetWriterVirtualIndex()] = num2 - (BlobUtilities.GetUTF8ByteCount(item.Key) + 1);
            }
            else
            {
                builder[item.Value.GetWriterVirtualIndex()] = num2;
                heapBuilder.WriteUTF8(item.Key, allowUnpairedSurrogates: false);
                heapBuilder.WriteByte(0);
            }
            text = item.Key;
        }
        return builder.MoveToImmutable();
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Reflection.BlobUtilities.GetUTF8ByteCount(), System.Reflection.Metadata.Ecma335.MetadataBuilder.SuffixSort.Instance, System.Reflection.BlobUtilities.IsLowSurrogateChar(), System.item, System.list, and System.text.
Referenced by System.Reflection.Metadata.Ecma335.MetadataBuilder.GetSerializedMetadata().