Terraria: System.Reflection.Metadata.Ecma335.MetadataBuilder.AddAssemblyReference
AddAssemblyReference()
AssemblyReferenceHandle System.Reflection.Metadata.Ecma335.MetadataBuilder.AddAssemblyReference (StringHandle name, Version version, StringHandle culture, BlobHandle publicKeyOrToken, AssemblyFlags flags, BlobHandle hashValue) inline
Definition at line 1012 of file MetadataBuilder.cs.
    {
        if (version == null)
        {
            Throw.ArgumentNull("version");
        }
        _assemblyRefTable.Add(new AssemblyRefTableRow
        {
            Name = name,
            Version = version,
            Culture = culture,
            PublicKeyToken = publicKeyOrToken,
            Flags = (uint)flags,
            HashValue = hashValue
        });
        return AssemblyReferenceHandle.FromRowId(_assemblyRefTable.Count);
    }
References System.Reflection.Metadata.Ecma335.MetadataBuilder._assemblyRefTable, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Reflection.Throw.ArgumentNull(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.culture, System.Reflection.Metadata.AssemblyReferenceHandle.FromRowId(), and System.Reflection.Name.