Terraria: System.Reflection.Metadata.Ecma335.MetadataBuilder.GetNewUserStringHandle
GetNewUserStringHandle()
UserStringHandle System.Reflection.Metadata.Ecma335.MetadataBuilder.GetNewUserStringHandle () inline private
Definition at line 2668 of file MetadataBuilder.cs.
    {
        int num = _userStringHeapStartOffset + _userStringBuilder.Count;
        if (num >= 16777216)
        {
            Throw.HeapSizeLimitExceeded(HeapIndex.UserString);
        }
        return UserStringHandle.FromOffset(num);
    }
References System.Reflection.Metadata.Ecma335.MetadataBuilder._userStringBuilder, System.Reflection.Metadata.Ecma335.MetadataBuilder._userStringHeapStartOffset, System.Reflection.Metadata.BlobBuilder.Count, System.Reflection.Metadata.UserStringHandle.FromOffset(), and System.Reflection.Throw.HeapSizeLimitExceeded().
Referenced by System.Reflection.Metadata.Ecma335.MetadataBuilder.GetOrAddUserString(), and System.Reflection.Metadata.Ecma335.MetadataBuilder.ReserveUserString().