Terraria: System.Reflection.Metadata.Ecma335.MetadataBuilder.GetOrAddDocumentName
GetOrAddDocumentName()
BlobHandle System.Reflection.Metadata.Ecma335.MetadataBuilder.GetOrAddDocumentName (string value) inline
Definition at line 2537 of file MetadataBuilder.cs.
    {
        if (value == null)
        {
            Throw.ArgumentNull("value");
        }
        char c = ChooseSeparator(value);
        PooledBlobBuilder instance = PooledBlobBuilder.GetInstance();
        instance.WriteByte((byte)c);
        PooledBlobBuilder instance2 = PooledBlobBuilder.GetInstance();
        int num = 0;
        while (true)
        {
            int num2 = value.IndexOf(c, num);
            instance2.WriteUTF8(value, num, ((num2 >= 0) ? num2 : value.Length) - num, allowUnpairedSurrogates: true, prependSize: false);
            instance.WriteCompressedInteger(GetOrAddBlob(instance2).GetHeapOffset());
            if (num2 == -1)
            {
                break;
            }
            if (num2 == value.Length - 1)
            {
                instance.WriteByte(0);
                break;
            }
            instance2.Clear();
            num = num2 + 1;
        }
        instance2.Free();
        BlobHandle orAddBlob = GetOrAddBlob(instance);
        instance.Free();
        return orAddBlob;
    }
References System.Reflection.Throw.ArgumentNull(), System.Reflection.Metadata.Ecma335.MetadataBuilder.ChooseSeparator(), System.Collections.Generic.Dictionary< TKey, TValue >.Clear(), System.Reflection.Metadata.PooledBlobBuilder.Free(), System.Reflection.Metadata.BlobHandle.GetHeapOffset(), System.Reflection.Metadata.PooledBlobBuilder.GetInstance(), System.Reflection.Metadata.Ecma335.MetadataBuilder.GetOrAddBlob(), System.value, System.Reflection.Metadata.BlobBuilder.WriteByte(), and System.Reflection.Metadata.BlobBuilder.WriteCompressedInteger().