Terraria: System.Reflection.Metadata.Ecma335.MetadataBuilder.GetOrAddUserString
GetOrAddUserString()
UserStringHandle System.Reflection.Metadata.Ecma335.MetadataBuilder.GetOrAddUserString (string value) inline
Definition at line 2653 of file MetadataBuilder.cs.
    {
        if (value == null)
        {
            Throw.ArgumentNull("value");
        }
        if (!_userStrings.TryGetValue(value, out var value2))
        {
            value2 = GetNewUserStringHandle();
            _userStrings.Add(value, value2);
            _userStringBuilder.WriteUserString(value);
        }
        return value2;
    }
References System.Reflection.Metadata.Ecma335.MetadataBuilder._userStringBuilder, System.Reflection.Metadata.Ecma335.MetadataBuilder._userStrings, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Reflection.Throw.ArgumentNull(), System.Reflection.Metadata.Ecma335.MetadataBuilder.GetNewUserStringHandle(), System.Collections.Generic.Dictionary< TKey, TValue >.TryGetValue(), System.value, and System.Reflection.Metadata.BlobBuilder.WriteUserString().