Terraria: System.Reflection.Metadata.Ecma335.MetadataBuilder.ValidateOrder
ValidateOrder()
void System.Reflection.Metadata.Ecma335.MetadataBuilder.ValidateOrder () inline package
Definition at line 1497 of file MetadataBuilder.cs.
    {
        ValidateClassLayoutTable();
        ValidateFieldLayoutTable();
        ValidateFieldRvaTable();
        ValidateGenericParamTable();
        ValidateGenericParamConstaintTable();
        ValidateImplMapTable();
        ValidateInterfaceImplTable();
        ValidateMethodImplTable();
        ValidateNestedClassTable();
        ValidateLocalScopeTable();
        ValidateStateMachineMethodTable();
    }
References System.Reflection.Metadata.Ecma335.MetadataBuilder.ValidateClassLayoutTable(), System.Reflection.Metadata.Ecma335.MetadataBuilder.ValidateFieldLayoutTable(), System.Reflection.Metadata.Ecma335.MetadataBuilder.ValidateFieldRvaTable(), System.Reflection.Metadata.Ecma335.MetadataBuilder.ValidateGenericParamConstaintTable(), System.Reflection.Metadata.Ecma335.MetadataBuilder.ValidateGenericParamTable(), System.Reflection.Metadata.Ecma335.MetadataBuilder.ValidateImplMapTable(), System.Reflection.Metadata.Ecma335.MetadataBuilder.ValidateInterfaceImplTable(), System.Reflection.Metadata.Ecma335.MetadataBuilder.ValidateLocalScopeTable(), System.Reflection.Metadata.Ecma335.MetadataBuilder.ValidateMethodImplTable(), System.Reflection.Metadata.Ecma335.MetadataBuilder.ValidateNestedClassTable(), and System.Reflection.Metadata.Ecma335.MetadataBuilder.ValidateStateMachineMethodTable().
Referenced by System.Reflection.Metadata.Ecma335.MetadataRootBuilder.Serialize().