Terraria: System.Reflection.Metadata.Ecma335.MetadataBuilder.AddParameter
AddParameter()
ParameterHandle System.Reflection.Metadata.Ecma335.MetadataBuilder.AddParameter (ParameterAttributes attributes, StringHandle name, int sequenceNumber) inline
Definition at line 1202 of file MetadataBuilder.cs.
    {
        if ((uint)sequenceNumber > 65535u)
        {
            Throw.ArgumentOutOfRange("sequenceNumber");
        }
        _paramTable.Add(new ParamRow
        {
            Flags = (ushort)attributes,
            Name = name,
            Sequence = (ushort)sequenceNumber
        });
        return ParameterHandle.FromRowId(_paramTable.Count);
    }
References System.Reflection.Metadata.Ecma335.MetadataBuilder._paramTable, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Reflection.Throw.ArgumentOutOfRange(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Reflection.Metadata.ParameterHandle.FromRowId(), and System.Reflection.Name.