Terraria: System.Reflection.Metadata.Ecma335.MetadataBuilder.ReserveUserString
ReserveUserString()
ReservedBlob< UserStringHandle > System.Reflection.Metadata.Ecma335.MetadataBuilder.ReserveUserString (int length) inline
Definition at line 2641 of file MetadataBuilder.cs.
    {
        if (length < 0)
        {
            Throw.ArgumentOutOfRange("length");
        }
        UserStringHandle newUserStringHandle = GetNewUserStringHandle();
        int userStringByteLength = BlobUtilities.GetUserStringByteLength(length);
        Blob content = _userStringBuilder.ReserveBytes(BlobWriterImpl.GetCompressedIntegerSize(userStringByteLength) + userStringByteLength);
        return new ReservedBlob<UserStringHandle>(newUserStringHandle, content);
    }
References System.Reflection.Metadata.Ecma335.MetadataBuilder._userStringBuilder, System.Reflection.Throw.ArgumentOutOfRange(), System.Reflection.Metadata.BlobWriterImpl.GetCompressedIntegerSize(), System.Reflection.Metadata.Ecma335.MetadataBuilder.GetNewUserStringHandle(), System.Reflection.BlobUtilities.GetUserStringByteLength(), System.length, and System.Reflection.Metadata.BlobBuilder.ReserveBytes().