Terraria: System.Runtime.Serialization.ClassDataContract.RequiresMemberAccessForWrite
RequiresMemberAccessForWrite()
bool System.Runtime.Serialization.ClassDataContract.RequiresMemberAccessForWrite (SecurityException securityException) inline package
Definition at line 1474 of file ClassDataContract.cs.
    {
        EnsureMethodsImported();
        if (!DataContract.IsTypeVisible(base.UnderlyingType))
        {
            if (securityException != null)
            {
                throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new SecurityException(System.SR.Format(System.SR.PartialTrustDataContractTypeNotPublic, DataContract.GetClrTypeFullName(base.UnderlyingType)), securityException));
            }
            return true;
        }
        if (BaseContract != null && BaseContract.RequiresMemberAccessForWrite(securityException))
        {
            return true;
        }
        if (DataContract.MethodRequiresMemberAccess(OnSerializing))
        {
            if (securityException != null)
            {
                throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new SecurityException(System.SR.Format(System.SR.PartialTrustDataContractOnSerializingNotPublic, DataContract.GetClrTypeFullName(base.UnderlyingType), OnSerializing.Name), securityException));
            }
            return true;
        }
        if (DataContract.MethodRequiresMemberAccess(OnSerialized))
        {
            if (securityException != null)
            {
                throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new SecurityException(System.SR.Format(System.SR.PartialTrustDataContractOnSerializedNotPublic, DataContract.GetClrTypeFullName(base.UnderlyingType), OnSerialized.Name), securityException));
            }
            return true;
        }
        if (Members != null)
        {
            for (int i = 0; i < Members.Count; i++)
            {
                if (!Members[i].RequiresMemberAccessForGet())
                {
                    continue;
                }
                if (securityException != null)
                {
                    if (Members[i].MemberInfo is FieldInfo)
                    {
                        throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new SecurityException(System.SR.Format(System.SR.PartialTrustDataContractFieldGetNotPublic, DataContract.GetClrTypeFullName(base.UnderlyingType), Members[i].MemberInfo.Name), securityException));
                    }
                    throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new SecurityException(System.SR.Format(System.SR.PartialTrustDataContractPropertyGetNotPublic, DataContract.GetClrTypeFullName(base.UnderlyingType), Members[i].MemberInfo.Name), securityException));
                }
                return true;
            }
        }
        return false;
    }
References System.Runtime.Serialization.ClassDataContract.BaseContract, System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Runtime.Serialization.ClassDataContract.EnsureMethodsImported(), System.SR.Format(), System.Runtime.Serialization.DataContract.GetClrTypeFullName(), System.Runtime.Serialization.DataContract.IsTypeVisible(), System.Runtime.Serialization.ClassDataContract.Members, System.Runtime.Serialization.DataContract.MethodRequiresMemberAccess(), System.Reflection.MemberInfo.Name, System.Runtime.Serialization.ClassDataContract.OnSerialized, System.Runtime.Serialization.ClassDataContract.OnSerializing, System.SR.PartialTrustDataContractFieldGetNotPublic, System.SR.PartialTrustDataContractOnSerializedNotPublic, System.SR.PartialTrustDataContractOnSerializingNotPublic, System.SR.PartialTrustDataContractPropertyGetNotPublic, System.SR.PartialTrustDataContractTypeNotPublic, System.Runtime.Serialization.ClassDataContract.RequiresMemberAccessForWrite(), and System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperError().
Referenced by System.Runtime.Serialization.ClassDataContract.RequiresMemberAccessForWrite().