Terraria: System.Runtime.Serialization.ClassDataContract.IsNonAttributedTypeValidForSerialization
IsNonAttributedTypeValidForSerialization()
static bool System.Runtime.Serialization.ClassDataContract.IsNonAttributedTypeValidForSerialization ([DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicConstructors | DynamicallyAccessedMemberTypes.NonPublicConstructors | DynamicallyAccessedMemberTypes.Interfaces)] Type type) inline static package
Definition at line 1269 of file ClassDataContract.cs.
    {
        if (type.IsArray)
        {
            return false;
        }
        if (type.IsEnum)
        {
            return false;
        }
        if (type.IsGenericParameter)
        {
            return false;
        }
        if (Globals.TypeOfIXmlSerializable.IsAssignableFrom(type))
        {
            return false;
        }
        if (type.IsPointer)
        {
            return false;
        }
        if (type.IsDefined(Globals.TypeOfCollectionDataContractAttribute, inherit: false))
        {
            return false;
        }
        Type[] interfaces = type.GetInterfaces();
        if (!IsArraySegment(type))
        {
            Type[] array = interfaces;
            foreach (Type type2 in array)
            {
                if (CollectionDataContract.IsCollectionInterface(type2))
                {
                    return false;
                }
            }
        }
        if (type.IsSerializable)
        {
            return false;
        }
        if (Globals.TypeOfISerializable.IsAssignableFrom(type))
        {
            return false;
        }
        if (type.IsDefined(Globals.TypeOfDataContractAttribute, inherit: false))
        {
            return false;
        }
        if (type.IsValueType)
        {
            return type.IsVisible;
        }
        if (type.IsVisible)
        {
            return type.GetConstructor(BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, Type.EmptyTypes) != null;
        }
        return false;
    }
References System.array, System.Type.EmptyTypes, System.Type.GetInterfaces(), System.Runtime.Serialization.ClassDataContract.IsArraySegment(), System.Runtime.Serialization.CollectionDataContract.IsCollectionInterface(), System.Type.IsVisible, System.type, System.Runtime.Serialization.Globals.TypeOfCollectionDataContractAttribute, System.Runtime.Serialization.Globals.TypeOfDataContractAttribute, System.Runtime.Serialization.Globals.TypeOfISerializable, and System.Runtime.Serialization.Globals.TypeOfIXmlSerializable.
Referenced by System.Runtime.Serialization.DataContract.DataContractCriticalHelper.CreateDataContract(), System.Runtime.Serialization.DataContract.GetNonDCTypeStableName(), System.Runtime.Serialization.DataContract.IsTypeSerializable(), and System.Runtime.Serialization.ClassDataContract.ClassDataContractCriticalHelper.SetIsNonAttributedType().