Terraria: System.Runtime.Serialization.ClassDataContract.GetChildNamespaceToDeclare
GetChildNamespaceToDeclare()
static XmlDictionaryString System.Runtime.Serialization.ClassDataContract.GetChildNamespaceToDeclare (DataContract dataContract, Type childType, XmlDictionary dictionary) inline static package
Definition at line 1246 of file ClassDataContract.cs.
    {
        childType = DataContract.UnwrapNullableType(childType);
        if (!childType.IsEnum && !Globals.TypeOfIXmlSerializable.IsAssignableFrom(childType) && DataContract.GetBuiltInDataContract(childType) == null && childType != Globals.TypeOfDBNull)
        {
            string @namespace = DataContract.GetStableName(childType).Namespace;
            if (@namespace.Length > 0 && @namespace != dataContract.Namespace.Value)
            {
                return dictionary.Add(@namespace);
            }
        }
        return null;
    }
References System.dictionary, System.Runtime.Serialization.Dictionary, System.Runtime.Serialization.DataContract.GetBuiltInDataContract(), System.Runtime.Serialization.DataContract.Namespace, System.Runtime.Serialization.Globals.TypeOfDBNull, System.Runtime.Serialization.Globals.TypeOfIXmlSerializable, and System.Runtime.Serialization.DataContract.UnwrapNullableType().
Referenced by System.Runtime.Serialization.ClassDataContract.CreateChildElementNamespaces().