Terraria: System.Runtime.Serialization.ClassDataContract.CheckAndAddMember
CheckAndAddMember()
static void System.Runtime.Serialization.ClassDataContract.CheckAndAddMember (List< DataMember > members, DataMember memberContract, Dictionary< string, DataMember > memberNamesTable) inline static package
Definition at line 1234 of file ClassDataContract.cs.
    {
        if (memberNamesTable.TryGetValue(memberContract.Name, out var value))
        {
            Type declaringType = memberContract.MemberInfo.DeclaringType;
            DataContract.ThrowInvalidDataContractException(System.SR.Format(declaringType.IsEnum ? System.SR.DupEnumMemberValue : System.SR.DupMemberName, value.MemberInfo.Name, memberContract.MemberInfo.Name, DataContract.GetClrTypeFullName(declaringType), memberContract.Name), declaringType);
        }
        memberNamesTable.Add(memberContract.Name, memberContract);
        members.Add(memberContract);
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.SR.DupEnumMemberValue, System.SR.DupMemberName, System.SR.Format(), System.Runtime.Serialization.DataContract.GetClrTypeFullName(), System.Runtime.Serialization.DataContract.ThrowInvalidDataContractException(), System.Collections.Generic.Dictionary< TKey, TValue >.TryGetValue(), and System.value.
Referenced by System.Runtime.Serialization.ClassDataContract.ClassDataContractCriticalHelper.ImportDataMembers(), and System.Runtime.Serialization.EnumDataContract.EnumDataContractCriticalHelper.ImportDataMembers().