Terraria: System.Runtime.Serialization.ClassDataContract.RequiresMemberAccessForRead
RequiresMemberAccessForRead()
bool System.Runtime.Serialization.ClassDataContract.RequiresMemberAccessForRead (SecurityException securityException) inline package
Definition at line 1409 of file ClassDataContract.cs.
    {
        EnsureMethodsImported();
        if (!DataContract.IsTypeVisible(base.UnderlyingType))
        {
            if (securityException != null)
            {
                throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new SecurityException(System.SR.Format(System.SR.PartialTrustDataContractTypeNotPublic, DataContract.GetClrTypeFullName(base.UnderlyingType)), securityException));
            }
            return true;
        }
        if (BaseContract != null && BaseContract.RequiresMemberAccessForRead(securityException))
        {
            return true;
        }
        if (DataContract.ConstructorRequiresMemberAccess(GetNonAttributedTypeConstructor()))
        {
            if (Globals.TypeOfScriptObject_IsAssignableFrom(base.UnderlyingType))
            {
                return true;
            }
            if (securityException != null)
            {
                throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new SecurityException(System.SR.Format(System.SR.PartialTrustNonAttributedSerializableTypeNoPublicConstructor, DataContract.GetClrTypeFullName(base.UnderlyingType)), securityException));
            }
            return true;
        }
        if (DataContract.MethodRequiresMemberAccess(OnDeserializing))
        {
            if (securityException != null)
            {
                throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new SecurityException(System.SR.Format(System.SR.PartialTrustDataContractOnDeserializingNotPublic, DataContract.GetClrTypeFullName(base.UnderlyingType), OnDeserializing.Name), securityException));
            }
            return true;
        }
        if (DataContract.MethodRequiresMemberAccess(OnDeserialized))
        {
            if (securityException != null)
            {
                throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new SecurityException(System.SR.Format(System.SR.PartialTrustDataContractOnDeserializedNotPublic, DataContract.GetClrTypeFullName(base.UnderlyingType), OnDeserialized.Name), securityException));
            }
            return true;
        }
        if (Members != null)
        {
            for (int i = 0; i < Members.Count; i++)
            {
                if (!Members[i].RequiresMemberAccessForSet())
                {
                    continue;
                }
                if (securityException != null)
                {
                    if (Members[i].MemberInfo is FieldInfo)
                    {
                        throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new SecurityException(System.SR.Format(System.SR.PartialTrustDataContractFieldSetNotPublic, DataContract.GetClrTypeFullName(base.UnderlyingType), Members[i].MemberInfo.Name), securityException));
                    }
                    throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new SecurityException(System.SR.Format(System.SR.PartialTrustDataContractPropertySetNotPublic, DataContract.GetClrTypeFullName(base.UnderlyingType), Members[i].MemberInfo.Name), securityException));
                }
                return true;
            }
        }
        return false;
    }
References System.Runtime.Serialization.ClassDataContract.BaseContract, System.Runtime.Serialization.DataContract.ConstructorRequiresMemberAccess(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Runtime.Serialization.ClassDataContract.EnsureMethodsImported(), System.SR.Format(), System.Runtime.Serialization.DataContract.GetClrTypeFullName(), System.Runtime.Serialization.ClassDataContract.GetNonAttributedTypeConstructor(), System.Runtime.Serialization.DataContract.IsTypeVisible(), System.Runtime.Serialization.ClassDataContract.Members, System.Runtime.Serialization.DataContract.MethodRequiresMemberAccess(), System.Reflection.MemberInfo.Name, System.Runtime.Serialization.ClassDataContract.OnDeserialized, System.Runtime.Serialization.ClassDataContract.OnDeserializing, System.SR.PartialTrustDataContractFieldSetNotPublic, System.SR.PartialTrustDataContractOnDeserializedNotPublic, System.SR.PartialTrustDataContractOnDeserializingNotPublic, System.SR.PartialTrustDataContractPropertySetNotPublic, System.SR.PartialTrustDataContractTypeNotPublic, System.SR.PartialTrustNonAttributedSerializableTypeNoPublicConstructor, System.Runtime.Serialization.ClassDataContract.RequiresMemberAccessForRead(), System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperError(), and System.Runtime.Serialization.Globals.TypeOfScriptObject_IsAssignableFrom().
Referenced by System.Runtime.Serialization.ClassDataContract.RequiresMemberAccessForRead().