Terraria: System.Tuple.CombineHashCodes
CombineHashCodes() [1/7]
static int System.Tuple< T1, T2, T3, T4, T5, T6, T7, TRest >.CombineHashCodes (int h1, int h2) inline static package
Definition at line 51 of file Tuple.cs.
    {
        return ((h1 << 5) + h1) ^ h2;
    }
Referenced by System.Tuple< T1, T2, T3, T4, T5, T6, T7, TRest >.CombineHashCodes(), System.Tuple< T1, T2, T3, T4, T5, T6, T7, TRest >.CombineHashCodes(), System.Tuple< T1, T2, T3, T4, T5, T6, T7, TRest >.CombineHashCodes(), System.Tuple< T1, T2, T3, T4, T5, T6, T7, TRest >.CombineHashCodes(), System.Tuple< T1, T2, T3, T4, T5, T6, T7, TRest >.CombineHashCodes(), System.Tuple< T1, T2, T3, T4, T5, T6, T7, TRest >.CombineHashCodes(), and System.Tuple< T1, T2, T3, T4, T5, T6, T7, TRest >.GetHashCode().