Terraria: System.Xml.Xsl.XmlQueryTypeFactory.BooleanX
BooleanX
readonly XmlQueryType System.Xml.Xsl.XmlQueryTypeFactory.BooleanX = Type(XmlTypeCode.Boolean, isStrict: true) static
Definition at line 588 of file XmlQueryTypeFactory.cs.
Referenced by System.Xml.Xsl.Qil.QilTypeChecker.CheckAnd(), System.Xml.Xsl.Qil.QilTypeChecker.CheckFalse(), System.Xml.Xsl.Qil.QilTypeChecker.CheckIs(), System.Xml.Xsl.Qil.QilTypeChecker.CheckIsEmpty(), System.Xml.Xsl.Qil.QilTypeChecker.CheckIsType(), System.Xml.Xsl.Qil.QilTypeChecker.CheckNe(), System.Xml.Xsl.Qil.QilTypeChecker.CheckNot(), System.Xml.Xsl.Qil.QilTypeChecker.CheckTrue(), System.Xml.Xsl.Xslt.QilGenerator.ChooseBestType(), System.Xml.Xsl.XPath.XPathQilFactory.ConvertToBoolean(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.FoldXsltConvert(), System.Xml.Xsl.Xslt.XslAstAnalyzer.XPathAnalyzer.Function(), System.Xml.Xsl.IlGen.XmlILVisitor.GetXsltConvertMethod(), System.Xml.Xsl.Runtime.XsltConvert.InferXsltType(), System.Xml.Xsl.XPath.XPathQilFactory.InvokeContains(), System.Xml.Xsl.Xslt.XsltQilFactory.InvokeElementAvailable(), System.Xml.Xsl.XPath.XPathQilFactory.InvokeEqualityOperator(), System.Xml.Xsl.Xslt.XsltQilFactory.InvokeFunctionAvailable(), System.Xml.Xsl.Xslt.XsltQilFactory.InvokeIsSameNodeSort(), System.Xml.Xsl.XPath.XPathQilFactory.InvokeLang(), System.Xml.Xsl.XPath.XPathQilFactory.InvokeRelationalOperator(), and System.Xml.Xsl.XPath.XPathQilFactory.InvokeStartsWith().