Terraria: System.Xml.Xsl.XmlQueryTypeFactory.StringX
StringX
readonly XmlQueryType System.Xml.Xsl.XmlQueryTypeFactory.StringX = Type(XmlTypeCode.String, isStrict: true) static
Definition at line 582 of file XmlQueryTypeFactory.cs.
Referenced by System.Xml.Xsl.Qil.QilTypeChecker.CheckLiteralString(), System.Xml.Xsl.Qil.QilTypeChecker.CheckLocalNameOf(), System.Xml.Xsl.Qil.QilTypeChecker.CheckNamespaceUriOf(), System.Xml.Xsl.Qil.QilTypeChecker.CheckPrefixOf(), System.Xml.Xsl.Qil.QilTypeChecker.CheckStrConcat(), System.Xml.Xsl.Qil.QilTypeChecker.CheckXPathNodeValue(), System.Xml.Xsl.Qil.QilTypeChecker.CheckXsltGenerateId(), System.Xml.Xsl.Xslt.QilGenerator.ChooseBestType(), System.Xml.Xsl.Xslt.QilGenerator.CompileCopyOf(), System.Xml.Xsl.Xslt.QilGenerator.CompileFnDocument(), System.Xml.Xsl.Xslt.QilGenerator.CompileFnKey(), System.Xml.Xsl.Xslt.QilGenerator.CompileKeys(), System.Xml.Xsl.XPath.XPathQilFactory.ConvertToString(), System.Xml.Xsl.Xslt.QilGenerator.CreateGeneralKeyFunction(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.FoldXsltConvert(), System.Xml.Xsl.Xslt.XslAstAnalyzer.XPathAnalyzer.Function(), System.Xml.Xsl.IlGen.XmlILVisitor.GetXsltConvertMethod(), System.Xml.Xsl.Runtime.XsltConvert.InferXsltType(), System.Xml.Xsl.Xslt.XsltQilFactory.InvokeBaseUri(), System.Xml.Xsl.Xslt.XsltQilFactory.InvokeEXslObjectType(), System.Xml.Xsl.XPath.XPathQilFactory.InvokeFormatMessage(), System.Xml.Xsl.Xslt.XsltQilFactory.InvokeFormatNumberDynamic(), System.Xml.Xsl.Xslt.XsltQilFactory.InvokeFormatNumberStatic(), System.Xml.Xsl.Xslt.XsltQilFactory.InvokeMsFormatDateTime(), System.Xml.Xsl.Xslt.XsltQilFactory.InvokeMsLocalName(), System.Xml.Xsl.Xslt.XsltQilFactory.InvokeMsNamespaceUri(), System.Xml.Xsl.Xslt.XsltQilFactory.InvokeMsUtc(), System.Xml.Xsl.XPath.XPathQilFactory.InvokeNormalizeSpace(), System.Xml.Xsl.Xslt.XsltQilFactory.InvokeNumberFormat(), System.Xml.Xsl.Xslt.XsltQilFactory.InvokeOuterXml(), System.Xml.Xsl.XPath.XPathQilFactory.InvokeSubstring(), System.Xml.Xsl.XPath.XPathQilFactory.InvokeSubstring(), System.Xml.Xsl.XPath.XPathQilFactory.InvokeSubstringAfter(), System.Xml.Xsl.XPath.XPathQilFactory.InvokeSubstringBefore(), System.Xml.Xsl.Xslt.XsltQilFactory.InvokeSystemProperty(), System.Xml.Xsl.XPath.XPathQilFactory.InvokeTranslate(), and System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitFunction().