Terraria: System.Xml.Xsl.XmlQueryTypeFactory.DoubleX
DoubleX
readonly XmlQueryType System.Xml.Xsl.XmlQueryTypeFactory.DoubleX = Type(XmlTypeCode.Double, isStrict: true) static
Definition at line 606 of file XmlQueryTypeFactory.cs.
Referenced by System.Xml.Xsl.XPath.XPathBuilder.XPathBuilder(), System.Xml.Xsl.Xslt.XPathPatternBuilder.XPathPredicateEnvironment.XPathPredicateEnvironment(), System.Xml.Xsl.XPath.XPathBuilder.BuildOnePredicate(), System.Xml.Xsl.Qil.QilTypeChecker.CheckLiteralDouble(), System.Xml.Xsl.Xslt.QilGenerator.ChooseBestType(), System.Xml.Xsl.Xslt.QilGenerator.CompileLangToLcid(), System.Xml.Xsl.Xslt.LoopFocus.ConstructLoop(), System.Xml.Xsl.XPath.XPathQilFactory.ConvertToNumber(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.FoldXsltConvert(), System.Xml.Xsl.XPath.XPathBuilder.Function(), System.Xml.Xsl.Xslt.XslAstAnalyzer.XPathAnalyzer.Function(), System.Xml.Xsl.Xslt.LoopFocus.GetPosition(), System.Xml.Xsl.IlGen.XmlILVisitor.GetXsltConvertMethod(), System.Xml.Xsl.Runtime.XsltConvert.InferXsltType(), System.Xml.Xsl.XPath.XPathQilFactory.InvokeCeiling(), System.Xml.Xsl.XPath.XPathQilFactory.InvokeFloor(), System.Xml.Xsl.Xslt.XsltQilFactory.InvokeMsNumber(), System.Xml.Xsl.Xslt.XsltQilFactory.InvokeMsStringCompare(), System.Xml.Xsl.Xslt.XsltQilFactory.InvokeRegisterDecimalFormatter(), System.Xml.Xsl.XPath.XPathQilFactory.InvokeRound(), System.Xml.Xsl.Xslt.XsltQilFactory.InvokeSystemProperty(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.IsPrimitiveNumeric(), System.Xml.Xsl.Xslt.QilGenerator.PrecompileProtoTemplatesHeaders(), System.Xml.Xsl.XPath.XPathBuilder.PredicateToBoolean(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitSortKey(), and System.Xml.Xsl.XPath.XPathBuilder.FixupVisitor.VisitUnknown().