Terraria: System.Xml.Xsl.XmlQueryTypeFactory.Type
Type() [1/3]
static XmlQueryType System.Xml.Xsl.XmlQueryTypeFactory.Type (XmlSchemaSimpleType schemaType, bool isStrict) inline static
Definition at line 649 of file XmlQueryTypeFactory.cs.
    {
        if (schemaType.Datatype.Variety == XmlSchemaDatatypeVariety.Atomic)
        {
            if (schemaType == DatatypeImplementation.AnySimpleType)
            {
                return AnyAtomicTypeS;
            }
            return ItemType.Create(schemaType, isStrict);
        }
        while (schemaType.DerivedBy == XmlSchemaDerivationMethod.Restriction)
        {
            schemaType = (XmlSchemaSimpleType)schemaType.BaseXmlSchemaType;
        }
        if (schemaType.DerivedBy == XmlSchemaDerivationMethod.List)
        {
            return PrimeProduct(Type(((XmlSchemaSimpleTypeList)schemaType.Content).BaseItemType, isStrict), XmlQueryCardinality.ZeroOrMore);
        }
        XmlSchemaSimpleType[] baseMemberTypes = ((XmlSchemaSimpleTypeUnion)schemaType.Content).BaseMemberTypes;
        XmlQueryType[] array = new XmlQueryType[baseMemberTypes.Length];
        for (int i = 0; i < baseMemberTypes.Length; i++)
        {
            array[i] = Type(baseMemberTypes[i], isStrict);
        }
        return Choice(array);
    }
References System.Xml.Xsl.XmlQueryTypeFactory.AnyAtomicTypeS, System.Xml.Schema.DatatypeImplementation.AnySimpleType, System.array, System.Xml.Schema.XmlSchemaType.BaseXmlSchemaType, System.Xml.Xsl.XmlQueryTypeFactory.Choice(), System.Xml.Schema.XmlSchemaSimpleType.Content, System.Xml.Xsl.XmlQueryTypeFactory.ItemType.Create(), System.Xml.Schema.XmlSchemaType.Datatype, System.Xml.Schema.XmlSchemaType.DerivedBy, System.Xml.Xsl.XmlQueryTypeFactory.PrimeProduct(), System.Xml.Type, System.Xml.Schema.XmlSchemaDatatype.Variety, and System.Xml.Xsl.XmlQueryCardinality.ZeroOrMore.