Terraria: System.Xml.Xsl.XmlQueryTypeFactory.Choice
Choice() [1/2]
static XmlQueryType System.Xml.Xsl.XmlQueryTypeFactory.Choice (params XmlQueryType[] types) inline static
Definition at line 681 of file XmlQueryTypeFactory.cs.
    {
        if (types.Length == 0)
        {
            return None;
        }
        if (types.Length == 1)
        {
            return types[0];
        }
        List<XmlQueryType> list = new List<XmlQueryType>(types[0]);
        XmlQueryCardinality cardinality = types[0].Cardinality;
        for (int i = 1; i < types.Length; i++)
        {
            PrimeChoice(list, types[i]);
            cardinality |= types[i].Cardinality;
        }
        return SequenceType.Create(ChoiceType.Create(list), cardinality);
    }
References System.Xml.Xsl.XmlQueryTypeFactory.ChoiceType.Create(), System.Xml.Xsl.XmlQueryTypeFactory.SequenceType.Create(), System.Xml.Dictionary, System.list, System.Xml.Xsl.XmlQueryTypeFactory.None, and System.Xml.Xsl.XmlQueryTypeFactory.PrimeChoice().