Terraria: System.Xml.Xsl.XmlQueryTypeFactory.Deserialize
Deserialize()
static XmlQueryType System.Xml.Xsl.XmlQueryTypeFactory.Deserialize (BinaryReader reader) inline static
Definition at line 775 of file XmlQueryTypeFactory.cs.
    {
        return reader.ReadByte() switch
        {
            0 => ItemType.Create(reader),
            1 => ChoiceType.Create(reader),
            2 => SequenceType.Create(reader),
            _ => null,
        };
    }
References System.Xml.Xsl.XmlQueryTypeFactory.ChoiceType.Create(), System.Xml.Xsl.XmlQueryTypeFactory.SequenceType.Create(), System.Xml.Xsl.XmlQueryTypeFactory.ItemType.Create(), and System.IO.BinaryReader.ReadByte().
Referenced by System.Xml.Xsl.Runtime.XmlQueryStaticData.XmlQueryStaticData(), System.Xml.Xsl.XmlQueryTypeFactory.ChoiceType.Create(), and System.Xml.Xsl.XmlQueryTypeFactory.SequenceType.Create().