Terraria: System.Xml.Xsl.XmlQueryTypeFactory.PrimeProduct
PrimeProduct()
static XmlQueryType System.Xml.Xsl.XmlQueryTypeFactory.PrimeProduct (XmlQueryType t, XmlQueryCardinality c) inline static
Definition at line 711 of file XmlQueryTypeFactory.cs.
    {
        if (t.Cardinality == c && !t.IsDod)
        {
            return t;
        }
        return SequenceType.Create(t.Prime, c);
    }
References System.Xml.Xsl.XmlQueryType.Cardinality, System.Xml.Xsl.XmlQueryTypeFactory.SequenceType.Create(), System.Xml.Xsl.XmlQueryType.IsDod, and System.Xml.Xsl.XmlQueryType.Prime.
Referenced by System.Xml.Xsl.XmlQueryTypeFactory.AtMost(), System.Xml.Xsl.XPath.XPathBuilder.BuildAxisFilter(), System.Xml.Xsl.Xslt.XPathPatternBuilder.BuildAxisFilter(), System.Xml.Xsl.Qil.QilTypeChecker.CheckAverage(), System.Xml.Xsl.Qil.QilTypeChecker.CheckLoop(), System.Xml.Xsl.Qil.QilTypeChecker.CheckSort(), System.Xml.Xsl.Qil.QilTypeChecker.DistinctType(), and System.Xml.Xsl.XmlQueryTypeFactory.Type().