Terraria: System.Xml.Xsl.XmlQueryTypeFactory.ItemS
ItemS
readonly XmlQueryType System.Xml.Xsl.XmlQueryTypeFactory.ItemS = PrimeProduct(Item, XmlQueryCardinality.ZeroOrMore) static
Definition at line 522 of file XmlQueryTypeFactory.cs.
Referenced by System.Xml.Xsl.Qil.QilTypeChecker.CheckLiteralObject(), System.Xml.Xsl.Qil.QilTypeChecker.CheckQilExpression(), System.Xml.Xsl.Qil.QilTypeChecker.CheckXsltInvokeLateBound(), System.Xml.Xsl.Xslt.QilGenerator.ChooseBestType(), System.Xml.Xsl.Xslt.QilGenerator.CompileInitializationCode(), System.Xml.Xsl.Xslt.QilGenerator.CompileVarParValue(), System.Xml.Xsl.Xslt.XslAstAnalyzer.XPathAnalyzer.Function(), System.Xml.Xsl.IlGen.XmlILVisitor.GetXsltConvertMethod(), System.Xml.Xsl.Runtime.XsltConvert.InferXsltType(), System.Xml.Xsl.XPath.XPathQilFactory.InvokeEqualityOperator(), System.Xml.Xsl.XPath.XPathQilFactory.InvokeRelationalOperator(), System.Xml.Xsl.Runtime.XmlQueryContext.InvokeXsltLateBoundFunction(), System.Xml.Xsl.Xslt.QilGenerator.PhantomXPathExpression(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitGlobalValues(), and System.Xml.Xsl.IlGen.XmlILVisitor.VisitXsltConvert().