Terraria: System.Xml.Xsl.XmlQueryTypeFactory.IntX
IntX
readonly XmlQueryType System.Xml.Xsl.XmlQueryTypeFactory.IntX = Type(XmlTypeCode.Int, isStrict: true) static
Definition at line 592 of file XmlQueryTypeFactory.cs.
Referenced by System.Xml.Xsl.Qil.QilTypeChecker.CheckLength(), System.Xml.Xsl.Qil.QilTypeChecker.CheckLiteralInt32(), System.Xml.Xsl.Qil.QilTypeChecker.CheckPositionOf(), System.Xml.Xsl.Qil.QilTypeChecker.CheckStrLength(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.FoldXsltConvert(), System.Xml.Xsl.IlGen.XmlILVisitor.GetXsltConvertMethod(), System.Xml.Xsl.Xslt.XsltQilFactory.InvokeCheckScriptNamespace(), System.Xml.Xsl.Xslt.XsltQilFactory.InvokeLangToLcid(), System.Xml.Xsl.Xslt.XsltQilFactory.InvokeOnCurrentNodeChanged(), System.Xml.Xsl.Xslt.XsltQilFactory.InvokeRegisterDecimalFormat(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.IsPrimitiveNumeric(), and System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitSortKey().