Terraria: System.ThrowHelper.ThrowKeyNullException
ThrowKeyNullException()
static void System.ThrowHelper.ThrowKeyNullException () inline static package
Definition at line 8 of file ThrowHelper.cs.
    {
        ThrowArgumentNullException("key");
    }
References System.ThrowHelper.ThrowArgumentNullException().
Referenced by System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >.Add(), System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >.AddOrUpdate(), System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >.AddOrUpdate(), System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >.AddOrUpdate< TArg >(), System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >.Contains(), System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >.ContainsKey(), System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >.GetOrAdd(), System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >.GetOrAdd(), System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >.GetOrAdd< TArg >(), System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >.InitializeFromCollection(), System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >.Remove(), System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >.TryAdd(), System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >.TryGetValue(), System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >.TryRemove(), and System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >.TryUpdate().