Terraria: System.ThrowHelper.ThrowArgumentException_DestinationTooShort
ThrowArgumentException_DestinationTooShort()
static void System.ThrowHelper.ThrowArgumentException_DestinationTooShort () inline static package
Definition at line 38 of file ThrowHelper.cs.
    {
        throw new ArgumentException(SR.Argument_DestinationTooShort, "destination");
    }
References System.SR.Argument_DestinationTooShort.
Referenced by System.ArraySegment< T >.CopyTo(), System.Numerics.Vector< T >.CopyTo(), System.String.CopyTo(), System.Numerics.Vector2.CopyTo(), System.Numerics.Vector3.CopyTo(), System.Numerics.Vector4.CopyTo(), System.Numerics.Vector< T >.CopyTo(), System.ReadOnlySpan< T >.CopyTo(), System.Span< T >.CopyTo(), System.Text.Rune.EncodeToUtf16(), System.Text.Rune.EncodeToUtf8(), System.Decimal.GetBits(), System.Globalization.CompareInfo.IcuGetSortKey(), System.Globalization.CompareInfo.InvariantGetSortKey(), and System.Globalization.CompareInfo.NlsGetSortKey().