Terraria: System.ThrowHelper.ThrowObjectDisposedException_StreamClosed
ThrowObjectDisposedException_StreamClosed()
static void System.ThrowHelper.ThrowObjectDisposedException_StreamClosed (string objectName) inline static package
Definition at line 288 of file ThrowHelper.cs.
    {
        throw new ObjectDisposedException(objectName, SR.ObjectDisposed_StreamClosed);
    }
References System.SR.ObjectDisposed_StreamClosed.
Referenced by System.IO.BufferedStream.BufferedStream(), System.IO.Stream.CopyTo(), System.IO.Stream.CopyToAsync(), System.IO.UnmanagedMemoryStreamWrapper.CopyToAsync(), System.IO.Strategies.BufferedFileStreamStrategy.EnsureNotClosed(), System.IO.BufferedStream.EnsureNotClosed(), System.IO.MemoryStream.EnsureNotClosed(), System.IO.UnmanagedMemoryStream.EnsureNotClosed(), System.Text.TranscodingStream.ThrowObjectDisposedException(), and System.IO.Stream.ValidateCopyToArguments().