Terraria: System.ThrowHelper.ThrowIndexArgumentOutOfRange_NeedNonNegNumException
ThrowIndexArgumentOutOfRange_NeedNonNegNumException()
static void System.ThrowHelper.ThrowIndexArgumentOutOfRange_NeedNonNegNumException () inline static package
Definition at line 74 of file ThrowHelper.cs.
    {
        throw GetArgumentOutOfRangeException(ExceptionArgument.index, ExceptionResource.ArgumentOutOfRange_NeedNonNegNum);
    }
References System.ThrowHelper.GetArgumentOutOfRangeException().
Referenced by System.Array.BinarySearch(), System.Collections.Generic.List< T >.BinarySearch(), System.Array.BinarySearch< T >(), System.Collections.Generic.Dictionary< TKey, TValue >.KeyCollection.CopyTo(), System.Collections.Generic.Dictionary< TKey, TValue >.ValueCollection.CopyTo(), System.Collections.Generic.Dictionary< TKey, TValue >.CopyTo(), System.Collections.ObjectModel.Collection< T >.CopyTo(), System.Collections.ObjectModel.ReadOnlyCollection< T >.CopyTo(), System.Collections.Generic.Dictionary< TKey, TValue >.CopyTo(), System.Collections.Generic.Dictionary< TKey, TValue >.KeyCollection.CopyTo(), System.Collections.Generic.Dictionary< TKey, TValue >.ValueCollection.CopyTo(), System.Collections.Generic.List< T >.GetRange(), System.Collections.Generic.List< T >.LastIndexOf(), System.Collections.Generic.List< T >.RemoveRange(), System.Array.Reverse(), System.Collections.Generic.List< T >.Reverse(), System.Array.Reverse< T >(), System.Array.Sort(), System.Collections.Generic.List< T >.Sort(), System.Array.Sort< T >(), and System.Array.Sort< TKey, TValue >().