Terraria: System.ThrowHelper.ThrowValueArgumentOutOfRange_NeedNonNegNumException
ThrowValueArgumentOutOfRange_NeedNonNegNumException()
static void System.ThrowHelper.ThrowValueArgumentOutOfRange_NeedNonNegNumException () inline static package
Definition at line 80 of file ThrowHelper.cs.
    {
        throw GetArgumentOutOfRangeException(ExceptionArgument.value, ExceptionResource.ArgumentOutOfRange_NeedNonNegNum);
    }
References System.ThrowHelper.GetArgumentOutOfRangeException().
Referenced by System.Index.Index(), System.Index.FromEnd(), System.Index.FromStart(), System.Int32.Log2(), System.Int64.Log2(), System.IntPtr.Log2(), System.SByte.Log2(), and System.Int16.Log2().