Terraria: System.ThrowHelper.ThrowArgumentException
ThrowArgumentException() [1/2]
static void System.ThrowHelper.ThrowArgumentException (ExceptionResource resource) inline static package
Definition at line 169 of file ThrowHelper.cs.
    {
        throw GetArgumentException(resource);
    }
References System.ThrowHelper.GetArgumentException().
Referenced by System.Runtime.CompilerServices.ConditionalWeakTable< TKey, TValue >.Add(), System.Runtime.InteropServices.NativeMemory.AlignedAlloc(), System.Runtime.InteropServices.NativeMemory.AlignedRealloc(), System.Array.BinarySearch(), System.Collections.Generic.List< T >.BinarySearch(), System.Array.BinarySearch< T >(), System.String.CheckStringComparison(), System.String.CheckStringSplitOptions(), System.Collections.Generic.Comparer< T >.Compare(), System.Array.CompareTo(), System.Threading.Tasks.TaskFactory< TResult >.FromAsyncTrimPromise< TInstance >.CompleteFromAsyncResult(), System.Threading.Tasks.TaskFactory< TResult >.ContinueWhenAnyImpl(), System.Threading.Tasks.TaskFactory< TResult >.ContinueWhenAnyImpl< TAntecedentResult >(), System.Collections.Generic.List< T >.CopyTo(), System.Collections.Generic.Dictionary< TKey, TValue >.KeyCollection.CopyTo(), System.Collections.Generic.Dictionary< TKey, TValue >.ValueCollection.CopyTo(), System.Collections.Generic.Dictionary< TKey, TValue >.CopyTo(), System.Collections.ObjectModel.Collection< T >.CopyTo(), System.Collections.ObjectModel.ReadOnlyCollection< T >.CopyTo(), System.Array.CopyTo(), System.Collections.Generic.List< T >.CopyTo(), System.Collections.Generic.Dictionary< TKey, TValue >.CopyTo(), System.Collections.Generic.HashSet< T >.CopyTo(), System.Collections.Concurrent.ConcurrentQueue< T >.CopyTo(), System.Collections.Generic.Dictionary< TKey, TValue >.KeyCollection.CopyTo(), System.Collections.Generic.Dictionary< TKey, TValue >.ValueCollection.CopyTo(), System.Array.CreateInstance(), System.Array.CreateInstance(), System.Array.CreateInstance(), System.Array.CreateInstance(), System.Array.CreateInstance(), System.Array.CreateInstance(), System.IO.Stream.EndRead(), System.IO.Stream.EndWrite(), System.Collections.Generic.EqualityComparer< T >.Equals(), System.Collections.Generic.EqualityComparer< T >.GetHashCode(), System.String.GetHashCode(), System.Collections.Generic.List< T >.GetRange(), System.Globalization.CompareInfo.GetSortKey(), System.Globalization.CompareInfo.GetSortKeyLength(), System.Array.GetValue(), System.Array.GetValue(), System.Array.GetValue(), System.Array.GetValue(), System.Array.GetValue(), System.Globalization.CompareInfo.IndexOf(), System.Globalization.CompareInfo.IndexOf(), System.Collections.Generic.List< T >.RemoveRange(), System.Array.Reverse(), System.Collections.Generic.List< T >.Reverse(), System.Array.Reverse< T >(), System.Array.SetValue(), System.Array.SetValue(), System.Array.SetValue(), System.Array.SetValue(), System.Array.SetValue(), System.Array.Sort(), System.Collections.Generic.List< T >.Sort(), System.Array.Sort< T >(), System.MemoryExtensions.Sort< TKey, TValue >(), System.Array.Sort< TKey, TValue >(), System.MemoryExtensions.Sort< TKey, TValue, TComparer >(), System.BitConverter.ToInt16(), System.BitConverter.ToInt32(), System.BitConverter.ToInt64(), System.BitConverter.ToString(), System.Threading.Tasks.TaskCompletionSource< TResult >.TrySetException(), System.Threading.Tasks.Task< TResult >.WaitAllCore(), System.Threading.Tasks.Task< TResult >.WaitAnyCore(), System.Threading.Tasks.Task< TResult >.WhenAll(), System.Threading.Tasks.Task< TResult >.WhenAll(), System.Threading.Tasks.Task< TResult >.WhenAll< TResult >(), System.Threading.Tasks.Task< TResult >.WhenAll< TResult >(), System.Threading.Tasks.Task< TResult >.WhenAny(), and System.Threading.Tasks.Task< TResult >.WhenAny().