Terraria: Terraria.GameContent.RGB.QueenSlimeShader.ProcessHighDetail
ProcessHighDetail()
void Terraria.GameContent.RGB.QueenSlimeShader.ProcessHighDetail (RgbDevice device, Fragment fragment, EffectDetailLevel quality, float time) inline private
Definition at line 32 of file QueenSlimeShader.cs.
    {
        new Vector2(1.6f, 0.5f);
        for (int i = 0; i < fragment.Count; i++)
        {
            Vector2 canvasPositionOfIndex = fragment.GetCanvasPositionOfIndex(i);
            Vector4 slimeColor = _slimeColor;
            float staticNoise = NoiseHelper.GetStaticNoise(canvasPositionOfIndex * 0.3f + new Vector2(0f, time * 0.1f));
            staticNoise = Math.Max(0f, 1f - staticNoise * 3f);
            staticNoise = (float)Math.Sqrt(staticNoise);
            slimeColor = Vector4.Lerp(slimeColor, _debrisColor, staticNoise);
            fragment.SetColor(i, slimeColor);
        }
    }
References Terraria.GameContent.RGB.QueenSlimeShader._debrisColor, Terraria.GameContent.RGB.QueenSlimeShader._slimeColor, ReLogic.Peripherals.RGB.Fragment.Count, ReLogic.Peripherals.RGB.Fragment.GetCanvasPositionOfIndex(), Terraria.GameContent.RGB.NoiseHelper.GetStaticNoise(), and ReLogic.Peripherals.RGB.Fragment.SetColor().