Terraria: System.ThrowHelper.ThrowInvalidTypeWithPointersNotSupported
ThrowInvalidTypeWithPointersNotSupported()
static void System.ThrowHelper.ThrowInvalidTypeWithPointersNotSupported (Type targetType) inline static package
Definition at line 20 of file ThrowHelper.cs.
    {
        throw new ArgumentException(SR.Format(SR.Argument_InvalidTypeWithPointersNotSupported, targetType));
    }
References System.SR.Argument_InvalidTypeWithPointersNotSupported, and System.SR.Format().
Referenced by System.ReadOnlySpan< T >.ReadOnlySpan(), System.Span< T >.Span(), System.GC.AllocateArray< T >(), System.GC.AllocateUninitializedArray< T >(), System.Runtime.InteropServices.MemoryMarshal.AsBytes< T >(), System.Runtime.InteropServices.MemoryMarshal.AsBytes< T >(), System.Runtime.InteropServices.MemoryMarshal.AsRef< T >(), System.Runtime.InteropServices.MemoryMarshal.AsRef< T >(), System.Runtime.InteropServices.MemoryMarshal.Cast< TFrom, TTo >(), System.Runtime.InteropServices.MemoryMarshal.Cast< TFrom, TTo >(), System.Runtime.InteropServices.MemoryMarshal.Read< T >(), System.Runtime.InteropServices.MemoryMarshal.TryRead< T >(), System.Runtime.InteropServices.MemoryMarshal.TryWrite< T >(), and System.Runtime.InteropServices.MemoryMarshal.Write< T >().