Terraria: System.ThrowHelper.ThrowNotSupportedException
ThrowNotSupportedException() [2/2]
static void System.ThrowHelper.ThrowNotSupportedException (ExceptionResource resource) inline static package
Definition at line 264 of file ThrowHelper.cs.
    {
        throw new NotSupportedException(GetResourceString(resource));
    }
References System.ThrowHelper.GetResourceString().
Referenced by System.Collections.ObjectModel.Collection< T >.Add(), System.Collections.ObjectModel.ReadOnlyCollection< T >.Add(), System.Array.Add(), System.Collections.ObjectModel.Collection< T >.Add(), System.ArraySegment< T >.Add(), System.Collections.ObjectModel.ReadOnlyCollection< T >.Add(), System.Collections.Generic.Dictionary< TKey, TValue >.KeyCollection.Add(), System.Collections.Generic.Dictionary< TKey, TValue >.ValueCollection.Add(), System.SZArrayHelper.Add< T >(), System.Collections.Generic.Dictionary< TKey, TValue >.KeyCollection.Clear(), System.Collections.Generic.Dictionary< TKey, TValue >.ValueCollection.Clear(), System.Collections.ObjectModel.Collection< T >.Clear(), System.Collections.ObjectModel.ReadOnlyCollection< T >.Clear(), System.ArraySegment< T >.Clear(), System.SZArrayHelper.Clear< T >(), System.Byte.Create< TOther >(), System.Char.Create< TOther >(), System.Decimal.Create< TOther >(), System.Double.Create< TOther >(), System.Half.Create< TOther >(), System.Int16.Create< TOther >(), System.Int32.Create< TOther >(), System.Int64.Create< TOther >(), System.IntPtr.Create< TOther >(), System.SByte.Create< TOther >(), System.Single.Create< TOther >(), System.UInt16.Create< TOther >(), System.UInt32.Create< TOther >(), System.UInt64.Create< TOther >(), System.UIntPtr.Create< TOther >(), System.Byte.CreateSaturating< TOther >(), System.Char.CreateSaturating< TOther >(), System.Decimal.CreateSaturating< TOther >(), System.Double.CreateSaturating< TOther >(), System.Half.CreateSaturating< TOther >(), System.Int16.CreateSaturating< TOther >(), System.Int32.CreateSaturating< TOther >(), System.Int64.CreateSaturating< TOther >(), System.IntPtr.CreateSaturating< TOther >(), System.SByte.CreateSaturating< TOther >(), System.Single.CreateSaturating< TOther >(), System.UInt16.CreateSaturating< TOther >(), System.UInt32.CreateSaturating< TOther >(), System.UInt64.CreateSaturating< TOther >(), System.UIntPtr.CreateSaturating< TOther >(), System.Byte.CreateTruncating< TOther >(), System.Char.CreateTruncating< TOther >(), System.Decimal.CreateTruncating< TOther >(), System.Double.CreateTruncating< TOther >(), System.Half.CreateTruncating< TOther >(), System.Int16.CreateTruncating< TOther >(), System.Int32.CreateTruncating< TOther >(), System.Int64.CreateTruncating< TOther >(), System.IntPtr.CreateTruncating< TOther >(), System.SByte.CreateTruncating< TOther >(), System.Single.CreateTruncating< TOther >(), System.UInt16.CreateTruncating< TOther >(), System.UInt32.CreateTruncating< TOther >(), System.UInt64.CreateTruncating< TOther >(), System.UIntPtr.CreateTruncating< TOther >(), System.Collections.ObjectModel.Collection< T >.Insert(), System.Collections.ObjectModel.ReadOnlyCollection< T >.Insert(), System.Array.Insert(), System.Collections.ObjectModel.Collection< T >.Insert(), System.ArraySegment< T >.Insert(), System.Collections.ObjectModel.ReadOnlyCollection< T >.Insert(), System.SZArrayHelper.Insert< T >(), System.Collections.ObjectModel.Collection< T >.Remove(), System.Collections.ObjectModel.ReadOnlyCollection< T >.Remove(), System.Array.Remove(), System.Collections.ObjectModel.Collection< T >.Remove(), System.ArraySegment< T >.Remove(), System.Collections.ObjectModel.ReadOnlyCollection< T >.Remove(), System.Collections.Generic.Dictionary< TKey, TValue >.KeyCollection.Remove(), System.Collections.Generic.Dictionary< TKey, TValue >.ValueCollection.Remove(), System.SZArrayHelper.Remove< T >(), System.Collections.ObjectModel.Collection< T >.RemoveAt(), System.Collections.ObjectModel.ReadOnlyCollection< T >.RemoveAt(), System.Array.RemoveAt(), System.ArraySegment< T >.RemoveAt(), System.SZArrayHelper.RemoveAt< T >(), System.Byte.TryCreate< TOther >(), System.Char.TryCreate< TOther >(), System.Decimal.TryCreate< TOther >(), System.Double.TryCreate< TOther >(), System.Single.TryCreate< TOther >(), System.Half.TryCreate< TOther >(), System.Int32.TryCreate< TOther >(), System.Int64.TryCreate< TOther >(), System.IntPtr.TryCreate< TOther >(), System.UIntPtr.TryCreate< TOther >(), System.SByte.TryCreate< TOther >(), System.Int16.TryCreate< TOther >(), System.UInt32.TryCreate< TOther >(), System.UInt64.TryCreate< TOther >(), and System.UInt16.TryCreate< TOther >().