Terraria: System.ThrowHelper.ThrowArgumentOutOfRange_Month
ThrowArgumentOutOfRange_Month()
static void System.ThrowHelper.ThrowArgumentOutOfRange_Month (int month) inline static package
Definition at line 110 of file ThrowHelper.cs.
    {
        throw new ArgumentOutOfRangeException("month", month, SR.ArgumentOutOfRange_Month);
    }
References System.SR.ArgumentOutOfRange_Month.
Referenced by System.Globalization.JulianCalendar.CheckMonthRange(), System.Globalization.EastAsianLunisolarCalendar.CheckYearMonthRange(), System.Globalization.HijriCalendar.CheckYearMonthRange(), System.Globalization.PersianCalendar.CheckYearMonthRange(), System.Globalization.UmAlQuraCalendar.CheckYearMonthRange(), System.DateTime.DaysInMonth(), System.Globalization.GregorianCalendarHelper.GetDaysInMonth(), and System.Globalization.HebrewCalendar.GetDaysInMonth().