Terraria: System.ThrowHelper.ThrowArgumentException_BadComparer
ThrowArgumentException_BadComparer()
static void System.ThrowHelper.ThrowArgumentException_BadComparer (object comparer) inline static package
Definition at line 68 of file ThrowHelper.cs.
    {
        throw new ArgumentException(SR.Format(SR.Arg_BogusIComparer, comparer));
    }
References System.SR.Arg_BogusIComparer, System.comparer, and System.SR.Format().
Referenced by System.Array.SorterObjectArray.IntrospectiveSort(), System.Array.SorterGenericArray.IntrospectiveSort(), System.Collections.Generic.ArraySortHelper< TKey, TValue >.Sort(), System.Collections.Generic.ArraySortHelper< TKey, TValue >.Sort(), System.Collections.Generic.GenericArraySortHelper< TKey, TValue >.Sort(), System.Collections.Generic.ArraySortHelper< TKey, TValue >.Sort(), and System.Collections.Generic.GenericArraySortHelper< TKey, TValue >.Sort().