Terraria: System.ThrowHelper.ThrowLengthArgumentOutOfRange_ArgumentOutOfRange_NeedNonNegNum
ThrowLengthArgumentOutOfRange_ArgumentOutOfRange_NeedNonNegNum()
static void System.ThrowHelper.ThrowLengthArgumentOutOfRange_ArgumentOutOfRange_NeedNonNegNum () inline static package
Definition at line 86 of file ThrowHelper.cs.
    {
        throw GetArgumentOutOfRangeException(ExceptionArgument.length, ExceptionResource.ArgumentOutOfRange_NeedNonNegNum);
    }
References System.ThrowHelper.GetArgumentOutOfRangeException().
Referenced by System.Array.BinarySearch(), System.Array.BinarySearch< T >(), System.Array.CreateInstance(), System.Array.Reverse(), System.Array.Reverse< T >(), System.Array.Sort(), System.Array.Sort< T >(), and System.Array.Sort< TKey, TValue >().