Terraria: System.ThrowHelper.ThrowArgumentOutOfRangeException_PositionOutOfRange
ThrowArgumentOutOfRangeException_PositionOutOfRange()
static void System.ThrowHelper.ThrowArgumentOutOfRangeException_PositionOutOfRange () inline static package
Definition at line 58 of file ThrowHelper.cs.
    {
        throw CreateArgumentOutOfRangeException_PositionOutOfRange();
    }
References System.ThrowHelper.CreateArgumentOutOfRangeException_PositionOutOfRange().
Referenced by System.Buffers.ReadOnlySequence< T >.BoundsCheck(), System.Buffers.ReadOnlySequence< T >.BoundsCheck(), System.Buffers.ReadOnlySequence< T >.GetEndPosition(), System.Buffers.ReadOnlySequence< T >.GetOffset(), System.Buffers.ReadOnlySequence< T >.Seek(), System.Buffers.ReadOnlySequence< T >.Seek(), System.Buffers.ReadOnlySequence< T >.Slice(), System.Buffers.ReadOnlySequence< T >.Slice(), and System.Buffers.ReadOnlySequence< T >.Slice().