Terraria: System.ThrowHelper.GetResourceString
GetResourceString()
static string System.ThrowHelper.GetResourceString (ExceptionResource resource) inline static private
Definition at line 618 of file ThrowHelper.cs.
    {
        return resource switch
        {
            ExceptionResource.ArgumentOutOfRange_Index => SR.ArgumentOutOfRange_Index,
            ExceptionResource.ArgumentOutOfRange_IndexCount => SR.ArgumentOutOfRange_IndexCount,
            ExceptionResource.ArgumentOutOfRange_IndexCountBuffer => SR.ArgumentOutOfRange_IndexCountBuffer,
            ExceptionResource.ArgumentOutOfRange_Count => SR.ArgumentOutOfRange_Count,
            ExceptionResource.ArgumentOutOfRange_Year => SR.ArgumentOutOfRange_Year,
            ExceptionResource.Arg_ArrayPlusOffTooSmall => SR.Arg_ArrayPlusOffTooSmall,
            ExceptionResource.NotSupported_ReadOnlyCollection => SR.NotSupported_ReadOnlyCollection,
            ExceptionResource.Arg_RankMultiDimNotSupported => SR.Arg_RankMultiDimNotSupported,
            ExceptionResource.Arg_NonZeroLowerBound => SR.Arg_NonZeroLowerBound,
            ExceptionResource.ArgumentOutOfRange_GetCharCountOverflow => SR.ArgumentOutOfRange_GetCharCountOverflow,
            ExceptionResource.ArgumentOutOfRange_ListInsert => SR.ArgumentOutOfRange_ListInsert,
            ExceptionResource.ArgumentOutOfRange_NeedNonNegNum => SR.ArgumentOutOfRange_NeedNonNegNum,
            ExceptionResource.ArgumentOutOfRange_SmallCapacity => SR.ArgumentOutOfRange_SmallCapacity,
            ExceptionResource.Argument_InvalidOffLen => SR.Argument_InvalidOffLen,
            ExceptionResource.Argument_CannotExtractScalar => SR.Argument_CannotExtractScalar,
            ExceptionResource.ArgumentOutOfRange_BiggerThanCollection => SR.ArgumentOutOfRange_BiggerThanCollection,
            ExceptionResource.Serialization_MissingKeys => SR.Serialization_MissingKeys,
            ExceptionResource.Serialization_NullKey => SR.Serialization_NullKey,
            ExceptionResource.NotSupported_KeyCollectionSet => SR.NotSupported_KeyCollectionSet,
            ExceptionResource.NotSupported_ValueCollectionSet => SR.NotSupported_ValueCollectionSet,
            ExceptionResource.InvalidOperation_NullArray => SR.InvalidOperation_NullArray,
            ExceptionResource.TaskT_TransitionToFinal_AlreadyCompleted => SR.TaskT_TransitionToFinal_AlreadyCompleted,
            ExceptionResource.TaskCompletionSourceT_TrySetException_NullException => SR.TaskCompletionSourceT_TrySetException_NullException,
            ExceptionResource.TaskCompletionSourceT_TrySetException_NoExceptions => SR.TaskCompletionSourceT_TrySetException_NoExceptions,
            ExceptionResource.NotSupported_StringComparison => SR.NotSupported_StringComparison,
            ExceptionResource.ConcurrentCollection_SyncRoot_NotSupported => SR.ConcurrentCollection_SyncRoot_NotSupported,
            ExceptionResource.Task_MultiTaskContinuation_NullTask => SR.Task_MultiTaskContinuation_NullTask,
            ExceptionResource.InvalidOperation_WrongAsyncResultOrEndCalledMultiple => SR.InvalidOperation_WrongAsyncResultOrEndCalledMultiple,
            ExceptionResource.Task_MultiTaskContinuation_EmptyTaskList => SR.Task_MultiTaskContinuation_EmptyTaskList,
            ExceptionResource.Task_Start_TaskCompleted => SR.Task_Start_TaskCompleted,
            ExceptionResource.Task_Start_Promise => SR.Task_Start_Promise,
            ExceptionResource.Task_Start_ContinuationTask => SR.Task_Start_ContinuationTask,
            ExceptionResource.Task_Start_AlreadyStarted => SR.Task_Start_AlreadyStarted,
            ExceptionResource.Task_RunSynchronously_Continuation => SR.Task_RunSynchronously_Continuation,
            ExceptionResource.Task_RunSynchronously_Promise => SR.Task_RunSynchronously_Promise,
            ExceptionResource.Task_RunSynchronously_TaskCompleted => SR.Task_RunSynchronously_TaskCompleted,
            ExceptionResource.Task_RunSynchronously_AlreadyStarted => SR.Task_RunSynchronously_AlreadyStarted,
            ExceptionResource.AsyncMethodBuilder_InstanceNotInitialized => SR.AsyncMethodBuilder_InstanceNotInitialized,
            ExceptionResource.Task_ContinueWith_ESandLR => SR.Task_ContinueWith_ESandLR,
            ExceptionResource.Task_ContinueWith_NotOnAnything => SR.Task_ContinueWith_NotOnAnything,
            ExceptionResource.Task_InvalidTimerTimeSpan => SR.Task_InvalidTimerTimeSpan,
            ExceptionResource.Task_Delay_InvalidMillisecondsDelay => SR.Task_Delay_InvalidMillisecondsDelay,
            ExceptionResource.Task_Dispose_NotCompleted => SR.Task_Dispose_NotCompleted,
            ExceptionResource.Task_ThrowIfDisposed => SR.Task_ThrowIfDisposed,
            ExceptionResource.Task_WaitMulti_NullTask => SR.Task_WaitMulti_NullTask,
            ExceptionResource.ArgumentException_OtherNotArrayOfCorrectLength => SR.ArgumentException_OtherNotArrayOfCorrectLength,
            ExceptionResource.ArgumentNull_Array => SR.ArgumentNull_Array,
            ExceptionResource.ArgumentNull_SafeHandle => SR.ArgumentNull_SafeHandle,
            ExceptionResource.ArgumentOutOfRange_EndIndexStartIndex => SR.ArgumentOutOfRange_EndIndexStartIndex,
            ExceptionResource.ArgumentOutOfRange_Enum => SR.ArgumentOutOfRange_Enum,
            ExceptionResource.ArgumentOutOfRange_HugeArrayNotSupported => SR.ArgumentOutOfRange_HugeArrayNotSupported,
            ExceptionResource.Argument_AddingDuplicate => SR.Argument_AddingDuplicate,
            ExceptionResource.Argument_InvalidArgumentForComparison => SR.Argument_InvalidArgumentForComparison,
            ExceptionResource.Arg_LowerBoundsMustMatch => SR.Arg_LowerBoundsMustMatch,
            ExceptionResource.Arg_MustBeType => SR.Arg_MustBeType,
            ExceptionResource.Arg_Need1DArray => SR.Arg_Need1DArray,
            ExceptionResource.Arg_Need2DArray => SR.Arg_Need2DArray,
            ExceptionResource.Arg_Need3DArray => SR.Arg_Need3DArray,
            ExceptionResource.Arg_NeedAtLeast1Rank => SR.Arg_NeedAtLeast1Rank,
            ExceptionResource.Arg_RankIndices => SR.Arg_RankIndices,
            ExceptionResource.Arg_RanksAndBounds => SR.Arg_RanksAndBounds,
            ExceptionResource.InvalidOperation_IComparerFailed => SR.InvalidOperation_IComparerFailed,
            ExceptionResource.NotSupported_FixedSizeCollection => SR.NotSupported_FixedSizeCollection,
            ExceptionResource.Rank_MultiDimNotSupported => SR.Rank_MultiDimNotSupported,
            ExceptionResource.Arg_TypeNotSupported => SR.Arg_TypeNotSupported,
            ExceptionResource.Argument_SpansMustHaveSameLength => SR.Argument_SpansMustHaveSameLength,
            ExceptionResource.Argument_InvalidFlag => SR.Argument_InvalidFlag,
            ExceptionResource.CancellationTokenSource_Disposed => SR.CancellationTokenSource_Disposed,
            ExceptionResource.Argument_AlignmentMustBePow2 => SR.Argument_AlignmentMustBePow2,
            _ => "",
        };
    }
References System.SR.Arg_ArrayPlusOffTooSmall, System.SR.Arg_LowerBoundsMustMatch, System.SR.Arg_MustBeType, System.SR.Arg_Need1DArray, System.SR.Arg_Need2DArray, System.SR.Arg_Need3DArray, System.SR.Arg_NeedAtLeast1Rank, System.SR.Arg_NonZeroLowerBound, System.SR.Arg_RankIndices, System.SR.Arg_RankMultiDimNotSupported, System.SR.Arg_RanksAndBounds, System.SR.Arg_TypeNotSupported, System.SR.Argument_AddingDuplicate, System.SR.Argument_AlignmentMustBePow2, System.SR.Argument_CannotExtractScalar, System.SR.Argument_InvalidArgumentForComparison, System.SR.Argument_InvalidFlag, System.SR.Argument_InvalidOffLen, System.SR.Argument_SpansMustHaveSameLength, System.SR.ArgumentException_OtherNotArrayOfCorrectLength, System.SR.ArgumentNull_Array, System.SR.ArgumentNull_SafeHandle, System.SR.ArgumentOutOfRange_BiggerThanCollection, System.SR.ArgumentOutOfRange_Count, System.SR.ArgumentOutOfRange_EndIndexStartIndex, System.SR.ArgumentOutOfRange_Enum, System.SR.ArgumentOutOfRange_GetCharCountOverflow, System.SR.ArgumentOutOfRange_HugeArrayNotSupported, System.SR.ArgumentOutOfRange_Index, System.SR.ArgumentOutOfRange_IndexCount, System.SR.ArgumentOutOfRange_IndexCountBuffer, System.SR.ArgumentOutOfRange_ListInsert, System.SR.ArgumentOutOfRange_NeedNonNegNum, System.SR.ArgumentOutOfRange_SmallCapacity, System.SR.ArgumentOutOfRange_Year, System.SR.AsyncMethodBuilder_InstanceNotInitialized, System.SR.CancellationTokenSource_Disposed, System.SR.ConcurrentCollection_SyncRoot_NotSupported, System.Runtime.Serialization.Dictionary, System.SR.InvalidOperation_IComparerFailed, System.SR.InvalidOperation_NullArray, System.SR.InvalidOperation_WrongAsyncResultOrEndCalledMultiple, System.SR.NotSupported_FixedSizeCollection, System.SR.NotSupported_KeyCollectionSet, System.SR.NotSupported_ReadOnlyCollection, System.SR.NotSupported_StringComparison, System.SR.NotSupported_ValueCollectionSet, System.SR.Rank_MultiDimNotSupported, System.SR.Serialization_MissingKeys, System.SR.Serialization_NullKey, System.SR.Task_ContinueWith_ESandLR, System.SR.Task_ContinueWith_NotOnAnything, System.SR.Task_Delay_InvalidMillisecondsDelay, System.SR.Task_Dispose_NotCompleted, System.SR.Task_InvalidTimerTimeSpan, System.SR.Task_MultiTaskContinuation_EmptyTaskList, System.SR.Task_MultiTaskContinuation_NullTask, System.SR.Task_RunSynchronously_AlreadyStarted, System.SR.Task_RunSynchronously_Continuation, System.SR.Task_RunSynchronously_Promise, System.SR.Task_RunSynchronously_TaskCompleted, System.SR.Task_Start_AlreadyStarted, System.SR.Task_Start_ContinuationTask, System.SR.Task_Start_Promise, System.SR.Task_Start_TaskCompleted, System.SR.Task_ThrowIfDisposed, System.SR.Task_WaitMulti_NullTask, System.SR.TaskCompletionSourceT_TrySetException_NoExceptions, System.SR.TaskCompletionSourceT_TrySetException_NullException, and System.SR.TaskT_TransitionToFinal_AlreadyCompleted.
Referenced by System.ThrowHelper.GetArgumentException(), System.ThrowHelper.GetArgumentException(), System.ThrowHelper.GetArgumentOutOfRangeException(), System.ThrowHelper.GetArgumentOutOfRangeException(), System.ThrowHelper.GetInvalidOperationException(), System.ThrowHelper.ThrowArgumentNullException(), System.ThrowHelper.ThrowInvalidOperationException(), System.ThrowHelper.ThrowNotSupportedException(), System.ThrowHelper.ThrowObjectDisposedException(), System.ThrowHelper.ThrowRankException(), and System.ThrowHelper.ThrowSerializationException().