Terraria: System.ThrowHelper.ThrowNotSupportedException_UnwritableStream
ThrowNotSupportedException_UnwritableStream()
static void System.ThrowHelper.ThrowNotSupportedException_UnwritableStream () inline static package
Definition at line 282 of file ThrowHelper.cs.
    {
        throw new NotSupportedException(SR.NotSupported_UnwritableStream);
    }
References System.SR.NotSupported_UnwritableStream.
Referenced by System.IO.FileStream.BeginWrite(), System.IO.Stream.BeginWriteInternal(), System.IO.UnmanagedMemoryStreamWrapper.CopyToAsync(), System.IO.Strategies.BufferedFileStreamStrategy.EnsureCanWrite(), System.IO.BufferedStream.EnsureCanWrite(), System.Text.TranscodingStream.EnsurePreWriteConditions(), System.IO.MemoryStream.EnsureWriteable(), System.IO.UnmanagedMemoryStream.EnsureWriteable(), System.IO.Strategies.Net5CompatFileStreamStrategy.PrepareForWriting(), System.IO.FileStream.SetLength(), System.IO.Stream.ValidateCopyToArguments(), System.IO.Strategies.OSFileStreamStrategy.Write(), System.IO.FileStream.WriteAsync(), System.IO.FileStream.WriteAsync(), System.IO.Strategies.Net5CompatFileStreamStrategy.WriteAsyncInternal(), and System.IO.Strategies.Net5CompatFileStreamStrategy.WriteSpan().