Terraria: System.ThrowHelper.GetArgumentName
GetArgumentName()
static string System.ThrowHelper.GetArgumentName (ExceptionArgument argument) inline static private
Definition at line 514 of file ThrowHelper.cs.
    {
        return argument switch
        {
            ExceptionArgument.obj => "obj",
            ExceptionArgument.dictionary => "dictionary",
            ExceptionArgument.array => "array",
            ExceptionArgument.info => "info",
            ExceptionArgument.key => "key",
            ExceptionArgument.text => "text",
            ExceptionArgument.values => "values",
            ExceptionArgument.value => "value",
            ExceptionArgument.startIndex => "startIndex",
            ExceptionArgument.task => "task",
            ExceptionArgument.bytes => "bytes",
            ExceptionArgument.byteIndex => "byteIndex",
            ExceptionArgument.byteCount => "byteCount",
            ExceptionArgument.ch => "ch",
            ExceptionArgument.chars => "chars",
            ExceptionArgument.charIndex => "charIndex",
            ExceptionArgument.charCount => "charCount",
            ExceptionArgument.s => "s",
            ExceptionArgument.input => "input",
            ExceptionArgument.ownedMemory => "ownedMemory",
            ExceptionArgument.list => "list",
            ExceptionArgument.index => "index",
            ExceptionArgument.capacity => "capacity",
            ExceptionArgument.collection => "collection",
            ExceptionArgument.item => "item",
            ExceptionArgument.converter => "converter",
            ExceptionArgument.match => "match",
            ExceptionArgument.count => "count",
            ExceptionArgument.action => "action",
            ExceptionArgument.comparison => "comparison",
            ExceptionArgument.exceptions => "exceptions",
            ExceptionArgument.exception => "exception",
            ExceptionArgument.pointer => "pointer",
            ExceptionArgument.start => "start",
            ExceptionArgument.format => "format",
            ExceptionArgument.formats => "formats",
            ExceptionArgument.culture => "culture",
            ExceptionArgument.comparer => "comparer",
            ExceptionArgument.comparable => "comparable",
            ExceptionArgument.source => "source",
            ExceptionArgument.state => "state",
            ExceptionArgument.length => "length",
            ExceptionArgument.comparisonType => "comparisonType",
            ExceptionArgument.manager => "manager",
            ExceptionArgument.sourceBytesToCopy => "sourceBytesToCopy",
            ExceptionArgument.callBack => "callBack",
            ExceptionArgument.creationOptions => "creationOptions",
            ExceptionArgument.function => "function",
            ExceptionArgument.scheduler => "scheduler",
            ExceptionArgument.continuationAction => "continuationAction",
            ExceptionArgument.continuationFunction => "continuationFunction",
            ExceptionArgument.tasks => "tasks",
            ExceptionArgument.asyncResult => "asyncResult",
            ExceptionArgument.beginMethod => "beginMethod",
            ExceptionArgument.endMethod => "endMethod",
            ExceptionArgument.endFunction => "endFunction",
            ExceptionArgument.cancellationToken => "cancellationToken",
            ExceptionArgument.continuationOptions => "continuationOptions",
            ExceptionArgument.delay => "delay",
            ExceptionArgument.millisecondsDelay => "millisecondsDelay",
            ExceptionArgument.millisecondsTimeout => "millisecondsTimeout",
            ExceptionArgument.stateMachine => "stateMachine",
            ExceptionArgument.timeout => "timeout",
            ExceptionArgument.type => "type",
            ExceptionArgument.sourceIndex => "sourceIndex",
            ExceptionArgument.sourceArray => "sourceArray",
            ExceptionArgument.destinationIndex => "destinationIndex",
            ExceptionArgument.destinationArray => "destinationArray",
            ExceptionArgument.pHandle => "pHandle",
            ExceptionArgument.handle => "handle",
            ExceptionArgument.other => "other",
            ExceptionArgument.newSize => "newSize",
            ExceptionArgument.lowerBounds => "lowerBounds",
            ExceptionArgument.lengths => "lengths",
            ExceptionArgument.len => "len",
            ExceptionArgument.keys => "keys",
            ExceptionArgument.indices => "indices",
            ExceptionArgument.index1 => "index1",
            ExceptionArgument.index2 => "index2",
            ExceptionArgument.index3 => "index3",
            ExceptionArgument.length1 => "length1",
            ExceptionArgument.length2 => "length2",
            ExceptionArgument.length3 => "length3",
            ExceptionArgument.endIndex => "endIndex",
            ExceptionArgument.elementType => "elementType",
            ExceptionArgument.arrayIndex => "arrayIndex",
            ExceptionArgument.year => "year",
            ExceptionArgument.codePoint => "codePoint",
            ExceptionArgument.str => "str",
            ExceptionArgument.options => "options",
            ExceptionArgument.prefix => "prefix",
            ExceptionArgument.suffix => "suffix",
            ExceptionArgument.buffer => "buffer",
            ExceptionArgument.buffers => "buffers",
            ExceptionArgument.offset => "offset",
            ExceptionArgument.stream => "stream",
            _ => "",
        };
    }
References System.Runtime.Serialization.Dictionary.
Referenced by System.ThrowHelper.GetArgumentException(), System.ThrowHelper.GetArgumentOutOfRangeException(), System.ThrowHelper.GetArgumentOutOfRangeException(), System.ThrowHelper.ThrowArgumentNullException(), System.ThrowHelper.ThrowArgumentNullException(), and System.ThrowHelper.ThrowArgumentOutOfRangeException().