Terraria: System.ThrowHelper.ThrowArgumentOutOfRangeException
ThrowArgumentOutOfRangeException() [5/5]
static void System.ThrowHelper.ThrowArgumentOutOfRangeException (System::ExceptionArgument argument) inline static package
Definition at line 22 of file ThrowHelper.cs.
    {
        throw CreateArgumentOutOfRangeException(argument);
    }
References System.ThrowHelper.CreateArgumentOutOfRangeException().
Referenced by System.Threading.CancellationTokenSource.CancellationTokenSource(), System.Threading.CancellationTokenSource.CancellationTokenSource(), System.Collections.Generic.Dictionary< TKey, TValue >.Dictionary(), System.Collections.Generic.HashSet< T >.HashSet(), System.Collections.Generic.List< T >.List(), System.Memory< T >.Memory(), System.Memory< T >.Memory(), System.Memory< T >.Memory(), System.Memory< T >.Memory(), System.ReadOnlyMemory< T >.ReadOnlyMemory(), System.ReadOnlySpan< T >.ReadOnlySpan(), System.ReadOnlySpan< T >.ReadOnlySpan(), System.Text.Rune.Rune(), System.Text.Rune.Rune(), System.Span< T >.Span(), System.Span< T >.Span(), System.Threading.Tasks.Task< TResult >.Task(), System.Buffers.SequenceReader< T >.AdvanceToNextSpan(), System.MemoryExtensions.AsMemory(), System.MemoryExtensions.AsMemory(), System.MemoryExtensions.AsMemory(), System.MemoryExtensions.AsMemory< T >(), System.MemoryExtensions.AsMemory< T >(), System.Runtime.InteropServices.MemoryMarshal.AsRef< T >(), System.Runtime.InteropServices.MemoryMarshal.AsRef< T >(), System.MemoryExtensions.AsSpan(), System.MemoryExtensions.AsSpan(), System.MemoryExtensions.AsSpan< T >(), System.MemoryExtensions.AsSpan< T >(), System.MemoryExtensions.AsSpan< T >(), System.MemoryExtensions.AsSpan< T >(), System.Collections.Generic.List< T >.BinarySearch(), System.Threading.CancellationTokenSource.CancelAfter(), System.Threading.CancellationTokenSource.CancelAfter(), System.Threading.Tasks.TaskFactory< TResult >.CheckCreationOptions(), System.Threading.Tasks.TaskFactory< TResult >.CheckFromAsyncOptions(), System.Array.Copy(), System.Array.Copy(), System.Array.CopyTo(), System.Collections.Concurrent.ConcurrentQueue< T >.CopyTo(), System.Buffers.BuffersExtensions.CopyTo< T >(), System.Buffers.BuffersExtensions.CopyToMultiSegment< T >(), System.Runtime.InteropServices.MemoryMarshal.CreateFromPinnedArray< T >(), System.Array.CreateInstance(), System.Array.CreateInstance(), System.Array.CreateInstance(), System.Array.CreateInstance(), System.Array.CreateInstance(), System.Threading.Tasks.Task< TResult >.CreationOptionsFromContinuationOptions(), System.Threading.Tasks.Task< TResult >.Delay(), System.Collections.Generic.Dictionary< TKey, TValue >.EnsureCapacity(), System.Collections.Generic.HashSet< T >.EnsureCapacity(), System.Collections.Generic.List< T >.EnsureCapacity(), System.Threading.Tasks.Task< TResult >.FromCanceled(), System.Threading.Tasks.Task< TResult >.FromCanceled< TResult >(), System.Globalization.CharUnicodeInfo.GetBidiCategory(), System.Buffer.GetByte(), System.Text.ASCIIEncoding.GetByteCount(), System.Text.Latin1Encoding.GetByteCount(), System.Text.UTF8Encoding.GetByteCount(), System.Text.ASCIIEncoding.GetByteCount(), System.Text.Latin1Encoding.GetByteCount(), System.Text.UTF8Encoding.GetByteCount(), System.Text.ASCIIEncoding.GetBytes(), System.Text.Latin1Encoding.GetBytes(), System.Text.UTF8Encoding.GetBytes(), System.Text.ASCIIEncoding.GetBytes(), System.Text.Latin1Encoding.GetBytes(), System.Text.UTF8Encoding.GetBytes(), System.Text.ASCIIEncoding.GetBytes(), System.Text.Latin1Encoding.GetBytes(), System.Text.UTF8Encoding.GetBytes(), System.Text.ASCIIEncoding.GetCharCount(), System.Text.Latin1Encoding.GetCharCount(), System.Text.UTF8Encoding.GetCharCount(), System.Text.ASCIIEncoding.GetCharCount(), System.Text.Latin1Encoding.GetCharCount(), System.Text.UTF8Encoding.GetCharCount(), System.Text.ASCIIEncoding.GetChars(), System.Text.Latin1Encoding.GetChars(), System.Text.UTF8Encoding.GetChars(), System.Text.ASCIIEncoding.GetChars(), System.Text.Latin1Encoding.GetChars(), System.Text.UTF8Encoding.GetChars(), System.Text.Latin1Encoding.GetChars(), System.Globalization.CharUnicodeInfo.GetDecimalDigitValue(), System.Globalization.CharUnicodeInfo.GetDigitValue(), System.Runtime.Intrinsics.Vector128< T >.GetElement< T >(), System.Runtime.Intrinsics.Vector256< T >.GetElement< T >(), System.Runtime.Intrinsics.Vector64< T >.GetElement< T >(), System.Text.Latin1Encoding.GetMaxCharCount(), System.Buffers.Text.Base64.GetMaxDecodedFromUtf8Length(), System.Buffers.Text.Base64.GetMaxEncodedToUtf8Length(), System.Globalization.CharUnicodeInfo.GetNumericValue(), System.Globalization.CharUnicodeInfo.GetNumericValue(), System.Char.GetNumericValue(), System.Range.GetOffsetAndLength(), System.Collections.Generic.List< T >.GetRange(), System.Text.ASCIIEncoding.GetString(), System.Text.Latin1Encoding.GetString(), System.Text.UTF8Encoding.GetString(), System.Globalization.CharUnicodeInfo.GetUnicodeCategory(), System.Globalization.CharUnicodeInfo.GetUnicodeCategory(), System.Char.GetUnicodeCategory(), System.Array.GetValue(), System.Array.GetValue(), System.Array.GetValue(), System.Array.GetValue(), System.Globalization.CompareInfo.IndexOf(), System.Globalization.Ordinal.IndexOf(), System.Globalization.CompareInfo.IndexOf(), System.Collections.Generic.List< T >.Insert(), System.Char.IsControl(), System.Char.IsDigit(), System.Char.IsHighSurrogate(), System.Char.IsLetter(), System.Char.IsLetterOrDigit(), System.Char.IsLower(), System.Char.IsLowSurrogate(), System.Char.IsNumber(), System.Char.IsPunctuation(), System.Char.IsSeparator(), System.Char.IsSurrogate(), System.Char.IsSurrogatePair(), System.Char.IsSymbol(), System.Char.IsUpper(), System.Char.IsWhiteSpace(), System.Array.LastIndexOf(), System.Globalization.CompareInfo.LastIndexOf(), System.Globalization.CompareInfo.LastIndexOf(), System.Collections.Generic.List< T >.LastIndexOf(), System.Buffer.MemoryCopy(), System.Buffer.MemoryCopy(), System.Runtime.InteropServices.MemoryMarshal.Read< T >(), System.Collections.Generic.List< T >.RemoveRange(), System.Buffers.ArrayMemoryPool< T >.Rent(), System.Array.Resize< T >(), System.Collections.Generic.List< T >.Reverse(), System.Buffers.SequenceReader< T >.Rewind(), System.Buffers.ReadOnlySequence< T >.Seek(), System.Buffers.ReadOnlySequence< T >.Seek(), System.Buffers.ReadOnlySequence< T >.SeekMultiSegment(), System.Buffer.SetByte(), System.IO.BufferedStream.SetLength(), System.IO.FileStream.SetLength(), System.Array.SetValue(), System.Array.SetValue(), System.Array.SetValue(), System.Array.SetValue(), System.Memory< T >.Slice(), System.ReadOnlyMemory< T >.Slice(), System.ReadOnlySpan< T >.Slice(), System.Span< T >.Slice(), System.Memory< T >.Slice(), System.ReadOnlyMemory< T >.Slice(), System.ReadOnlySpan< T >.Slice(), System.Span< T >.Slice(), System.Buffers.ReadOnlySequence< T >.Slice(), System.Buffers.ReadOnlySequence< T >.Slice(), System.Collections.Generic.List< T >.Sort(), System.Runtime.InteropServices.Marshal.StringToCoTaskMemAnsi(), System.Runtime.InteropServices.Marshal.StringToCoTaskMemUni(), System.Runtime.InteropServices.Marshal.StringToHGlobalAnsi(), System.Runtime.InteropServices.Marshal.StringToHGlobalUni(), System.Threading.Tasks.Task< TResult >.TaskConstructorCore(), System.BitConverter.ToBoolean(), System.BitConverter.ToBoolean(), System.BitConverter.ToChar(), System.BitConverter.ToDouble(), System.BitConverter.ToHalf(), System.BitConverter.ToInt16(), System.BitConverter.ToInt16(), System.BitConverter.ToInt32(), System.BitConverter.ToInt32(), System.BitConverter.ToInt64(), System.BitConverter.ToInt64(), System.Globalization.CharUnicodeInfo.ToLower(), System.BitConverter.ToSingle(), System.BitConverter.ToString(), System.BitConverter.ToUInt16(), System.BitConverter.ToUInt32(), System.BitConverter.ToUInt64(), System.Globalization.CharUnicodeInfo.ToUpper(), System.Collections.Generic.Dictionary< TKey, TValue >.TrimExcess(), System.Threading.ThreadPool.UnsafeQueueUserWorkItem(), System.Threading.ThreadPool.UnsafeQueueUserWorkItem< TState >(), System.IO.Stream.ValidateBufferArguments(), System.Threading.Tasks.Task< TResult >.ValidateTimeout(), System.Threading.Tasks.Task< TResult >.Wait(), System.Threading.Tasks.Task< TResult >.Wait(), System.Threading.Tasks.Task< TResult >.WaitAll(), System.Threading.Tasks.Task< TResult >.WaitAllCore(), System.Threading.Tasks.Task< TResult >.WaitAny(), System.Threading.Tasks.Task< TResult >.WaitAnyCore(), System.Runtime.Intrinsics.Vector128< T >.WithElement< T >(), System.Runtime.Intrinsics.Vector256< T >.WithElement< T >(), System.Runtime.Intrinsics.Vector64< T >.WithElement< T >(), System.Runtime.InteropServices.MemoryMarshal.Write< T >(), and System.Buffers.BuffersExtensions.WriteMultiSegment< T >().