Terraria: System.ThrowHelper.ThrowObjectDisposedException_FileClosed
ThrowObjectDisposedException_FileClosed()
static void System.ThrowHelper.ThrowObjectDisposedException_FileClosed () inline static package
Definition at line 294 of file ThrowHelper.cs.
    {
        throw new ObjectDisposedException(null, SR.ObjectDisposed_FileClosed);
    }
References System.SR.ObjectDisposed_FileClosed.
Referenced by System.IO.FileStream.BeginRead(), System.IO.FileStream.BeginWrite(), System.IO.Strategies.AsyncWindowsFileStreamStrategy.CopyToAsync(), System.IO.Strategies.Net5CompatFileStreamStrategy.CopyToAsync(), System.IO.FileStream.Flush(), System.IO.FileStream.FlushAsync(), System.IO.FileStream.Lock(), System.IO.Strategies.Net5CompatFileStreamStrategy.PrepareForReading(), System.IO.Strategies.Net5CompatFileStreamStrategy.PrepareForWriting(), System.IO.Strategies.Net5CompatFileStreamStrategy.Read(), System.IO.Strategies.OSFileStreamStrategy.Read(), System.IO.FileStream.ReadAsync(), System.IO.FileStream.ReadAsync(), System.IO.Strategies.Net5CompatFileStreamStrategy.Seek(), System.IO.Strategies.OSFileStreamStrategy.Seek(), System.IO.FileStream.SetLength(), System.IO.BinaryReader.ThrowIfDisposed(), System.IO.FileStream.Unlock(), System.IO.FileStream.ValidateHandle(), System.IO.RandomAccess.ValidateInput(), System.IO.FileStream.ValidateReadWriteArgs(), System.IO.Strategies.Net5CompatFileStreamStrategy.Write(), System.IO.Strategies.OSFileStreamStrategy.Write(), System.IO.FileStream.WriteAsync(), and System.IO.FileStream.WriteAsync().