Terraria: System.ThrowHelper.ThrowCountArgumentOutOfRange_ArgumentOutOfRange_Count
ThrowCountArgumentOutOfRange_ArgumentOutOfRange_Count()
static void System.ThrowHelper.ThrowCountArgumentOutOfRange_ArgumentOutOfRange_Count () inline static package
Definition at line 98 of file ThrowHelper.cs.
    {
        throw GetArgumentOutOfRangeException(ExceptionArgument.count, ExceptionResource.ArgumentOutOfRange_Count);
    }
References System.ThrowHelper.GetArgumentOutOfRangeException().
Referenced by System.Array.Fill< T >(), System.Collections.Generic.List< T >.FindIndex(), System.Array.FindIndex< T >(), System.Collections.Generic.List< T >.FindLastIndex(), System.Array.FindLastIndex< T >(), System.Array.IndexOf(), System.Collections.Generic.List< T >.IndexOf(), System.Array.IndexOf< T >(), System.Array.LastIndexOf(), System.Globalization.CompareInfo.LastIndexOf(), System.Globalization.CompareInfo.LastIndexOf(), and System.Array.LastIndexOf< T >().