Terraria: System.ThrowHelper.ThrowArgumentNullException
ThrowArgumentNullException() [3/5]
static void System.ThrowHelper.ThrowArgumentNullException (string name) inline static package
Definition at line 14 of file ThrowHelper.cs.
    {
        throw new ArgumentNullException(name);
    }
Referenced by System.ArraySegment< T >.ArraySegment(), System.IO.BufferedStream.BufferedStream(), System.Collections.ObjectModel.Collection< T >.Collection(), System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >.ConcurrentDictionary(), System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >.ConcurrentDictionary(), System.Collections.Concurrent.ConcurrentQueue< T >.ConcurrentQueue(), System.DateTime.DateTime(), System.Collections.Generic.Dictionary< TKey, TValue >.Dictionary(), System.Collections.Generic.Dictionary< TKey, TValue >.Dictionary(), System.Collections.Generic.HashSet< T >.HashSet(), System.Collections.Concurrent.IDictionaryDebugView< TKey, TValue >.IDictionaryDebugView(), System.Collections.Generic.Dictionary< TKey, TValue >.KeyCollection.KeyCollection(), System.Collections.Generic.List< T >.List(), System.Collections.ObjectModel.ReadOnlyCollection< T >.ReadOnlyCollection(), System.Buffers.ReadOnlySequence< T >.ReadOnlySequence(), System.IO.StreamReader.StreamReader(), System.IO.StreamWriter.StreamWriter(), System.IO.StringReader.StringReader(), System.Threading.Tasks.Task< TResult >.Task(), System.Collections.Generic.Dictionary< TKey, TValue >.ValueCollection.ValueCollection(), System.Threading.Tasks.ValueTask< TResult >.ValueTask(), System.Threading.Tasks.ValueTask< TResult >.ValueTask(), System.Threading.Tasks.ValueTask< TResult >.ValueTask(), System.Threading.Tasks.ValueTask< TResult >.ValueTask(), System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Runtime.CompilerServices.ConditionalWeakTable< TKey, TValue >.Add(), System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >.AddOrUpdate(), System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >.AddOrUpdate(), System.Runtime.CompilerServices.ConditionalWeakTable< TKey, TValue >.AddOrUpdate(), System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >.AddOrUpdate< TArg >(), System.Text.StringBuilder.AppendJoinCore< T >(), System.Text.StringBuilder.AppendJoinCore< T >(), System.MemoryExtensions.AsMemory(), System.MemoryExtensions.AsMemory(), System.MemoryExtensions.AsMemory< T >(), System.MemoryExtensions.AsMemory< T >(), System.Array.AsReadOnly< T >(), System.MemoryExtensions.AsSpan< T >(), System.MemoryExtensions.AsSpan< T >(), System.Array.BinarySearch(), System.Array.BinarySearch(), System.Array.BinarySearch(), System.Array.BinarySearch< T >(), System.Array.BinarySearch< T >(), System.Array.BinarySearch< T >(), System.SpanHelpers.BinarySearch< T, TComparable >(), System.MemoryExtensions.BinarySearch< T, TComparer >(), System.Array.Clear(), System.Array.Clear(), System.Threading.Tasks.TaskFactory< TResult >.FromAsyncTrimPromise< TInstance >.CompleteFromAsyncResult(), System.String.Contains(), System.Threading.Tasks.TaskFactory< TResult >.ContinueWhenAll(), System.Threading.Tasks.TaskFactory< TResult >.ContinueWhenAll(), System.Threading.Tasks.TaskFactory< TResult >.ContinueWhenAll(), System.Threading.Tasks.TaskFactory< TResult >.ContinueWhenAll(), System.Threading.Tasks.TaskFactory< TResult >.ContinueWhenAll< TAntecedentResult >(), System.Threading.Tasks.TaskFactory< TResult >.ContinueWhenAll< TAntecedentResult >(), System.Threading.Tasks.TaskFactory< TResult >.ContinueWhenAll< TAntecedentResult >(), System.Threading.Tasks.TaskFactory< TResult >.ContinueWhenAll< TAntecedentResult >(), System.Threading.Tasks.TaskFactory< TResult >.ContinueWhenAllImpl(), System.Threading.Tasks.TaskFactory< TResult >.ContinueWhenAllImpl< TAntecedentResult >(), System.Threading.Tasks.TaskFactory< TResult >.ContinueWhenAny(), System.Threading.Tasks.TaskFactory< TResult >.ContinueWhenAny(), System.Threading.Tasks.TaskFactory< TResult >.ContinueWhenAny(), System.Threading.Tasks.TaskFactory< TResult >.ContinueWhenAny(), System.Threading.Tasks.TaskFactory< TResult >.ContinueWhenAny< TAntecedentResult >(), System.Threading.Tasks.TaskFactory< TResult >.ContinueWhenAny< TAntecedentResult >(), System.Threading.Tasks.TaskFactory< TResult >.ContinueWhenAny< TAntecedentResult >(), System.Threading.Tasks.TaskFactory< TResult >.ContinueWhenAny< TAntecedentResult >(), System.Threading.Tasks.TaskFactory< TResult >.ContinueWhenAnyImpl(), System.Threading.Tasks.TaskFactory< TResult >.ContinueWhenAnyImpl< TAntecedentResult >(), System.Threading.Tasks.Task< TResult >.ContinueWith(), System.Threading.Tasks.Task< TResult >.ContinueWith(), System.Threading.Tasks.Task< TResult >.ContinueWith(), System.Threading.Tasks.Task< TResult >.ContinueWith(), System.Threading.Tasks.Task< TResult >.ContinueWith< TNewResult >(), System.Threading.Tasks.Task< TResult >.ContinueWith< TNewResult >(), System.Threading.Tasks.Task< TResult >.ContinueWith< TResult >(), System.Threading.Tasks.Task< TResult >.ContinueWith< TResult >(), System.Array.ConvertAll< TInput, TOutput >(), System.Collections.Generic.List< T >.ConvertAll< TOutput >(), System.Char.ConvertToUtf32(), System.Array.Copy(), System.Array.Copy(), System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >.CopyTo(), System.Collections.Concurrent.ConcurrentQueue< T >.CopyTo(), System.Collections.Generic.Dictionary< TKey, TValue >.KeyCollection.CopyTo(), System.Collections.Generic.Dictionary< TKey, TValue >.ValueCollection.CopyTo(), System.Collections.Generic.Dictionary< TKey, TValue >.CopyTo(), System.Collections.ObjectModel.Collection< T >.CopyTo(), System.Collections.ObjectModel.ReadOnlyCollection< T >.CopyTo(), System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >.CopyTo(), System.Collections.Generic.Dictionary< TKey, TValue >.CopyTo(), System.Collections.Generic.HashSet< T >.CopyTo(), System.Collections.Concurrent.ConcurrentQueue< T >.CopyTo(), System.Collections.Generic.Dictionary< TKey, TValue >.KeyCollection.CopyTo(), System.Collections.Generic.Dictionary< TKey, TValue >.ValueCollection.CopyTo(), System.Array.CreateInstance(), System.Array.CreateInstance(), System.Array.CreateInstance(), System.Array.CreateInstance(), System.Array.CreateInstance(), System.Array.CreateInstance(), System.IO.Stream.SyncStream.EndRead(), System.IO.Stream.EndRead(), System.IO.Stream.SyncStream.EndWrite(), System.IO.Stream.EndWrite(), System.Collections.Generic.HashSet< T >.ExceptWith(), System.Array.Fill< T >(), System.Array.Fill< T >(), System.Collections.Generic.List< T >.Find(), System.Array.Find< T >(), System.Collections.Generic.List< T >.FindAll(), System.Array.FindAll< T >(), System.Collections.Generic.List< T >.FindIndex(), System.Array.FindIndex< T >(), System.Array.FindIndex< T >(), System.Array.FindIndex< T >(), System.Collections.Generic.List< T >.FindLast(), System.Array.FindLast< T >(), System.Collections.Generic.List< T >.FindLastIndex(), System.Array.FindLastIndex< T >(), System.Array.FindLastIndex< T >(), System.Array.FindLastIndex< T >(), System.Collections.Generic.Dictionary< TKey, TValue >.FindValue(), System.Collections.Generic.List< T >.ForEach(), System.Array.ForEach< T >(), System.Threading.Tasks.TaskFactory< TResult >.FromAsyncImpl(), System.Threading.Tasks.TaskFactory< TResult >.FromAsyncImpl(), System.Threading.Tasks.TaskFactory< TResult >.FromAsyncImpl< TArg1 >(), System.Threading.Tasks.TaskFactory< TResult >.FromAsyncImpl< TArg1, TArg2 >(), System.Threading.Tasks.TaskFactory< TResult >.FromAsyncImpl< TArg1, TArg2, TArg3 >(), System.Convert.FromBase64String(), System.Threading.Tasks.Task< TResult >.FromException(), System.Threading.Tasks.Task< TResult >.FromException< TResult >(), System.Convert.FromHexString(), System.Globalization.CharUnicodeInfo.GetBidiCategory(), System.Text.ASCIIEncoding.GetByteCount(), System.Text.Latin1Encoding.GetByteCount(), System.Text.UTF8Encoding.GetByteCount(), System.Text.ASCIIEncoding.GetByteCount(), System.Text.Latin1Encoding.GetByteCount(), System.Text.UTF8Encoding.GetByteCount(), System.Text.ASCIIEncoding.GetByteCount(), System.Text.UTF8Encoding.GetByteCount(), System.Text.Encoding.GetByteCount(), System.Text.Latin1Encoding.GetByteCount(), System.Text.UnicodeEncoding.GetByteCount(), System.Text.UTF32Encoding.GetByteCount(), System.Text.UTF7Encoding.GetByteCount(), System.Text.ASCIIEncoding.GetBytes(), System.Text.Latin1Encoding.GetBytes(), System.Text.UTF8Encoding.GetBytes(), System.Text.ASCIIEncoding.GetBytes(), System.Text.Latin1Encoding.GetBytes(), System.Text.UTF8Encoding.GetBytes(), System.Text.ASCIIEncoding.GetBytes(), System.Text.Encoding.GetBytes(), System.Text.Latin1Encoding.GetBytes(), System.Text.UTF8Encoding.GetBytes(), System.Text.ASCIIEncoding.GetCharCount(), System.Text.Latin1Encoding.GetCharCount(), System.Text.UTF8Encoding.GetCharCount(), System.Text.Latin1Encoding.GetCharCount(), System.Text.ASCIIEncoding.GetCharCount(), System.Text.Latin1Encoding.GetCharCount(), System.Text.UTF8Encoding.GetCharCount(), System.Text.ASCIIEncoding.GetChars(), System.Text.Latin1Encoding.GetChars(), System.Text.UTF8Encoding.GetChars(), System.Text.Latin1Encoding.GetChars(), System.Text.ASCIIEncoding.GetChars(), System.Text.Latin1Encoding.GetChars(), System.Text.UTF8Encoding.GetChars(), System.Text.Latin1Encoding.GetChars(), System.Globalization.CharUnicodeInfo.GetDecimalDigitValue(), System.Globalization.CharUnicodeInfo.GetDigitValue(), System.Array.GetHashCode(), System.OrdinalCaseSensitiveComparer.GetHashCode(), System.OrdinalComparer.GetHashCode(), System.OrdinalIgnoreCaseComparer.GetHashCode(), System.Globalization.CompareInfo.GetHashCode(), System.Globalization.StringInfo.GetNextTextElementLength(), System.Globalization.CharUnicodeInfo.GetNumericValue(), System.Char.GetNumericValue(), System.Collections.Generic.Dictionary< TKey, TValue >.GetObjectData(), System.Collections.Generic.HashSet< T >.GetObjectData(), System.DateTime.GetObjectData(), System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >.GetOrAdd(), System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >.GetOrAdd< TArg >(), System.Text.Latin1Encoding.GetString(), System.Text.ASCIIEncoding.GetString(), System.Text.Latin1Encoding.GetString(), System.Text.UTF8Encoding.GetString(), System.Runtime.CompilerServices.RuntimeHelpers.GetSubArray< T >(), System.Globalization.StringInfo.GetTextElementEnumerator(), System.Globalization.CharUnicodeInfo.GetUnicodeCategory(), System.Char.GetUnicodeCategory(), System.Array.GetValue(), System.Array.GetValue(), System.Collections.Generic.Dictionary< TKey, TValue >.CollectionsMarshalHelper.GetValueRefOrAddDefault(), System.ThrowHelper.IfNullAndNullsAreIllegalThenThrow< T >(), System.Array.IndexOf(), System.Array.IndexOf(), System.Array.IndexOf(), System.Globalization.CompareInfo.IndexOf(), System.Globalization.CompareInfo.IndexOf(), System.Globalization.CompareInfo.IndexOf(), System.Globalization.CompareInfo.IndexOf(), System.Globalization.CompareInfo.IndexOf(), System.Globalization.Ordinal.IndexOf(), System.Globalization.CompareInfo.IndexOf(), System.Array.IndexOf< T >(), System.Array.IndexOf< T >(), System.Array.IndexOf< T >(), System.Collections.Generic.List< T >.InsertRange(), System.Threading.Tasks.Task< TResult >.InternalStartNew(), System.Collections.Generic.HashSet< T >.IntersectWith(), System.Collections.Generic.Dictionary< TKey, TValue >.IsCompatibleKey(), System.Char.IsControl(), System.Char.IsDigit(), System.Char.IsHighSurrogate(), System.Char.IsLetter(), System.Char.IsLetterOrDigit(), System.Char.IsLower(), System.Char.IsLowSurrogate(), System.Char.IsNumber(), System.Globalization.CompareInfo.IsPrefix(), System.Collections.Generic.HashSet< T >.IsProperSubsetOf(), System.Collections.Generic.HashSet< T >.IsProperSupersetOf(), System.Char.IsPunctuation(), System.Char.IsSeparator(), System.Collections.Generic.HashSet< T >.IsSubsetOf(), System.Globalization.CompareInfo.IsSuffix(), System.Collections.Generic.HashSet< T >.IsSupersetOf(), System.Char.IsSurrogate(), System.Char.IsSurrogatePair(), System.Char.IsSymbol(), System.Char.IsUpper(), System.Char.IsWhiteSpace(), System.String.Join(), System.String.Join(), System.String.Join(), System.String.JoinCore(), System.String.JoinCore< T >(), System.Array.LastIndexOf(), System.Array.LastIndexOf(), System.Array.LastIndexOf(), System.Globalization.CompareInfo.LastIndexOf(), System.Globalization.CompareInfo.LastIndexOf(), System.Globalization.CompareInfo.LastIndexOf(), System.Globalization.CompareInfo.LastIndexOf(), System.Array.LastIndexOf< T >(), System.Array.LastIndexOf< T >(), System.Array.LastIndexOf< T >(), System.Random.ThreadSafeRandom.NextBytes(), System.Random.NextBytes(), System.Collections.Generic.HashSet< T >.Overlaps(), System.DateTimeOffset.Parse(), System.DateTimeOffset.Parse(), System.TimeSpan.Parse(), System.DateTimeOffset.Parse(), System.Byte.Parse(), System.Char.Parse(), System.DateTime.Parse(), System.Decimal.Parse(), System.Double.Parse(), System.Half.Parse(), System.Int16.Parse(), System.Int32.Parse(), System.Int64.Parse(), System.SByte.Parse(), System.Single.Parse(), System.TimeSpan.Parse(), System.UInt16.Parse(), System.UInt32.Parse(), System.UInt64.Parse(), System.Byte.Parse(), System.DateTime.Parse(), System.Decimal.Parse(), System.Double.Parse(), System.Half.Parse(), System.Int16.Parse(), System.Int32.Parse(), System.Int64.Parse(), System.SByte.Parse(), System.Single.Parse(), System.UInt16.Parse(), System.UInt32.Parse(), System.UInt64.Parse(), System.DateOnly.Parse(), System.TimeOnly.Parse(), System.DateTime.Parse(), System.Byte.Parse(), System.Decimal.Parse(), System.Double.Parse(), System.Half.Parse(), System.Int16.Parse(), System.Int32.Parse(), System.Int64.Parse(), System.SByte.Parse(), System.Single.Parse(), System.UInt16.Parse(), System.UInt32.Parse(), System.UInt64.Parse(), System.Byte.Parse(), System.Decimal.Parse(), System.Double.Parse(), System.Int16.Parse(), System.Int32.Parse(), System.Int64.Parse(), System.SByte.Parse(), System.Single.Parse(), System.UInt16.Parse(), System.UInt32.Parse(), System.UInt64.Parse(), System.Half.Parse(), System.Globalization.StringInfo.ParseCombiningCharacters(), System.DateTimeOffset.ParseExact(), System.TimeSpan.ParseExact(), System.DateTimeOffset.ParseExact(), System.TimeSpan.ParseExact(), System.TimeSpan.ParseExact(), System.DateTimeOffset.ParseExact(), System.TimeSpan.ParseExact(), System.DateTime.ParseExact(), System.DateTime.ParseExact(), System.DateOnly.ParseExact(), System.TimeOnly.ParseExact(), System.DateTime.ParseExact(), System.DateOnly.ParseExact(), System.TimeOnly.ParseExact(), System.Threading.ThreadPool.QueueUserWorkItem(), System.Threading.ThreadPool.QueueUserWorkItem< TState >(), System.Text.Rune.ReadRuneFromString(), System.Collections.Generic.Dictionary< TKey, TValue >.Remove(), System.Runtime.CompilerServices.ConditionalWeakTable< TKey, TValue >.Remove(), System.Collections.Generic.Dictionary< TKey, TValue >.Remove(), System.Collections.Generic.List< T >.RemoveAll(), System.Collections.Generic.HashSet< T >.RemoveWhere(), System.Buffers.TlsOverPerCoreLockedStacksArrayPool< T >.Return(), System.Array.Reverse(), System.Array.Reverse(), System.Array.Reverse< T >(), System.Array.Reverse< T >(), System.Threading.Tasks.Task< TResult >.Run(), System.Threading.Tasks.Task< TResult >.Run< TResult >(), System.Threading.Tasks.Task< TResult >.RunSynchronously(), System.StubHelpers.StubHelpers.SafeHandleAddRef(), System.StubHelpers.StubHelpers.SafeHandleRelease(), System.Runtime.InteropServices.Marshal.SecureStringToBSTR(), System.Runtime.InteropServices.Marshal.SecureStringToCoTaskMemAnsi(), System.Runtime.InteropServices.Marshal.SecureStringToCoTaskMemUnicode(), System.Runtime.InteropServices.Marshal.SecureStringToGlobalAllocAnsi(), System.Runtime.InteropServices.Marshal.SecureStringToGlobalAllocUnicode(), System.Collections.Generic.HashSet< T >.SetEquals(), System.Runtime.CompilerServices.AsyncVoidMethodBuilder.SetException(), System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder< TResult >.SetException(), System.Runtime.CompilerServices.AsyncTaskMethodBuilder< TResult >.SetException(), System.Runtime.CompilerServices.AsyncMethodBuilderCore.SetStateMachine(), System.Array.SetValue(), System.Array.SetValue(), System.Array.Sort(), System.Array.Sort(), System.Array.Sort(), System.Array.Sort(), System.Array.Sort(), System.Collections.Generic.List< T >.Sort(), System.Array.Sort< T >(), System.Array.Sort< T >(), System.Array.Sort< T >(), System.Array.Sort< T >(), System.MemoryExtensions.Sort< T >(), System.MemoryExtensions.Sort< TKey, TValue >(), System.Array.Sort< TKey, TValue >(), System.Array.Sort< TKey, TValue >(), System.Array.Sort< TKey, TValue >(), System.Threading.Tasks.Task< TResult >.Start(), System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start< TStateMachine >(), System.Threading.Tasks.Task< TResult >.StartNew(), System.Threading.Tasks.Task< TResult >.StartNew(), System.Collections.Generic.HashSet< T >.SymmetricExceptWith(), System.ThrowHelper.ThrowKeyNullException(), System.BitConverter.ToBoolean(), System.BitConverter.ToInt16(), System.BitConverter.ToInt32(), System.BitConverter.ToInt64(), System.Char.ToLower(), System.Text.Rune.ToLower(), System.BitConverter.ToString(), System.BitConverter.ToString(), System.BitConverter.ToString(), System.Char.ToUpper(), System.Text.Rune.ToUpper(), System.Collections.Generic.List< T >.TrueForAll(), System.Array.TrueForAll< T >(), System.Convert.TryFromBase64String(), System.Runtime.CompilerServices.ConditionalWeakTable< TKey, TValue >.TryGetValue(), System.Collections.Generic.Dictionary< TKey, TValue >.TryInsert(), System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >.TryRemove(), System.Threading.Tasks.TaskCompletionSource< TResult >.TrySetException(), System.Threading.Tasks.TaskCompletionSource< TResult >.TrySetException(), System.Collections.Generic.HashSet< T >.UnionWith(), System.Threading.ThreadPool.UnsafeQueueUserWorkItem(), System.Threading.ThreadPool.UnsafeQueueUserWorkItem(), System.Threading.ThreadPool.UnsafeQueueUserWorkItem< TState >(), System.IO.Stream.ValidateBufferArguments(), System.IO.RandomAccess.ValidateBuffers< T >(), System.IO.RandomAccess.ValidateInput(), System.Threading.Tasks.Task< TResult >.WaitAllCore(), System.Threading.Tasks.Task< TResult >.WaitAnyCore(), System.Threading.Tasks.Task< TResult >.WhenAll(), System.Threading.Tasks.Task< TResult >.WhenAll(), System.Threading.Tasks.Task< TResult >.WhenAll< TResult >(), System.Threading.Tasks.Task< TResult >.WhenAll< TResult >(), System.Threading.Tasks.Task< TResult >.WhenAny(), and System.Threading.Tasks.Task< TResult >.WhenAny().