Terraria: ReLogic.Text.WrappedTextBuilder.NonBreakingText.GetAsWrappedText
GetAsWrappedText()
string ReLogic.Text.WrappedTextBuilder.NonBreakingText.GetAsWrappedText (float maxWidth) inline
Definition at line 49 of file WrappedTextBuilder.cs.
        {
            float num = 0f;
            StringBuilder stringBuilder = new StringBuilder(Text.Length);
            for (int i = 0; i < Text.Length; i++)
            {
                GlyphMetrics characterMetrics = _font.GetCharacterMetrics(Text[i]);
                num = ((i != 0) ? (num + (_font.CharacterSpacing + characterMetrics.KernedWidth)) : (num + characterMetrics.KernedWidthOnNewLine));
                if (num > maxWidth)
                {
                    num = characterMetrics.KernedWidthOnNewLine;
                    stringBuilder.Append('\n');
                }
                stringBuilder.Append(Text[i]);
            }
            return stringBuilder.ToString();
        }
References ReLogic.Text.WrappedTextBuilder.NonBreakingText._font, System.Text.StringBuilder.Append(), ReLogic.Text.IFontMetrics.CharacterSpacing, ReLogic.Text.IFontMetrics.GetCharacterMetrics(), ReLogic.Text.GlyphMetrics.KernedWidth, ReLogic.Text.GlyphMetrics.KernedWidthOnNewLine, and System.Text.StringBuilder.ToString().
Referenced by ReLogic.Text.WrappedTextBuilder.Append().