Terraria: ItemID.FromLegacyName
FromLegacyName()
static short ItemID.FromLegacyName (string name, int release) inline static
     {
         if (_legacyItemLookup == null)
         {
             _legacyItemLookup = GenerateLegacyItemDictionary();
         }
         if (release <= 4)
         {
             switch (name)
             {
             case "Cobalt Helmet":
                 name = "Jungle Hat";
                 break;
             case "Cobalt Breastplate":
                 name = "Jungle Shirt";
                 break;
             case "Cobalt Greaves":
                 name = "Jungle Pants";
                 break;
             }
         }
         if (release <= 13 && name == "Jungle Rose")
         {
             name = "Jungle Spores";
         }
         if (release <= 20)
         {
             switch (name)
             {
             case "Gills potion":
                 name = "Gills Potion";
                 break;
             case "Thorn Chakrum":
                 name = "Thorn Chakram";
                 break;
             case "Ball 'O Hurt":
                 name = "Ball O' Hurt";
                 break;
             }
         }
         if (release <= 41 && name == "Iron Chain")
         {
             name = "Chain";
         }
         if (release <= 44 && name == "Orb of Light")
         {
             name = "Shadow Orb";
         }
         if (release <= 46)
         {
             if (name == "Black Dye")
             {
                 name = "Black Thread";
             }
             if (name == "Green Dye")
             {
                 name = "Green Thread";
             }
         }
         if (_legacyItemLookup.TryGetValue(name, out var value))
         {
             return value;
         }
         return 0;
     }
References _legacyItemLookup, and GenerateLegacyItemDictionary().
Referenced by Player.Deserialize(), and WorldFile.LoadWorld_Version1_Old_BeforeRelease88().