Terraria: System.Collections.Generic.HashSet.Remove
Remove()
bool System.Collections.Generic.HashSet< T >.Remove (T item) inline
Implements System.Collections.Generic.ICollection< T >.
Definition at line 327 of file HashSet.cs.
    {
        if (_buckets != null)
        {
            Entry[] entries = _entries;
            uint num = 0u;
            int num2 = -1;
            int num3 = ((item != null) ? (_comparer?.GetHashCode(item) ?? item.GetHashCode()) : 0);
            ref int bucketRef = ref GetBucketRef(num3);
            int num4 = bucketRef - 1;
            while (num4 >= 0)
            {
                ref Entry reference = ref entries[num4];
                if (reference.HashCode == num3 && (_comparer?.Equals(reference.Value, item) ?? EqualityComparer<T>.Default.Equals(reference.Value, item)))
                {
                    if (num2 < 0)
                    {
                        bucketRef = reference.Next + 1;
                    }
                    else
                    {
                        entries[num2].Next = reference.Next;
                    }
                    reference.Next = -3 - _freeList;
                    if (RuntimeHelpers.IsReferenceOrContainsReferences<T>())
                    {
                        reference.Value = default(T);
                    }
                    _freeList = num4;
                    _freeCount++;
                    return true;
                }
                num2 = num4;
                num4 = reference.Next;
                num++;
                if (num > (uint)entries.Length)
                {
                    ThrowHelper.ThrowInvalidOperationException_ConcurrentOperationsNotSupported();
                }
            }
        }
        return false;
    }
References System.Collections.Generic.HashSet< T >._buckets, System.Collections.Generic.HashSet< T >._comparer, System.Collections.Generic.HashSet< T >._entries, System.Collections.Generic.HashSet< T >._freeCount, System.Collections.Generic.HashSet< T >._freeList, System.Runtime.Serialization.Dictionary, System.Collections.Generic.IEqualityComparer< in T >.Equals(), System.Collections.Generic.HashSet< T >.GetBucketRef(), System.Collections.Generic.IEqualityComparer< in T >.GetHashCode(), System.item, and System.ThrowHelper.ThrowInvalidOperationException_ConcurrentOperationsNotSupported().
Referenced by System.Collections.Generic.HashSet< T >.ExceptWith(), System.Collections.Generic.HashSet< T >.IntersectWithEnumerable(), System.Collections.Generic.HashSet< T >.IntersectWithHashSetWithSameComparer(), System.Linq.Parallel.IntersectQueryOperator< TInputOutput >.IntersectQueryOperatorEnumerator< TLeftKey >.MoveNext(), Terraria.WorldBuilding.ShapeData.Remove(), System.Collections.Generic.HashSet< T >.RemoveWhere(), System.Collections.Generic.HashSet< T >.SymmetricExceptWithEnumerable(), and System.Collections.Generic.HashSet< T >.SymmetricExceptWithUniqueHashSet().