Terraria: System.Collections.Generic.HashSet.IsProperSupersetOf
IsProperSupersetOf()
bool System.Collections.Generic.HashSet< T >.IsProperSupersetOf (IEnumerable< T > other) inline
Implements System.Collections.Generic.ISet< T >.
Definition at line 628 of file HashSet.cs.
    {
        if (other == null)
        {
            ThrowHelper.ThrowArgumentNullException(ExceptionArgument.other);
        }
        if (Count == 0 || other == this)
        {
            return false;
        }
        if (other is ICollection<T> collection)
        {
            if (collection.Count == 0)
            {
                return true;
            }
            if (other is HashSet<T> hashSet && EqualityComparersAreEqual(this, hashSet))
            {
                if (hashSet.Count >= Count)
                {
                    return false;
                }
                return ContainsAllElements(hashSet);
            }
        }
        var (num, num2) = CheckUniqueAndUnfoundElements(other, returnIfUnfound: true);
        if (num < Count)
        {
            return num2 == 0;
        }
        return false;
    }
References System.Collections.Generic.HashSet< T >.CheckUniqueAndUnfoundElements(), System.collection, System.Collections.Generic.HashSet< T >.ContainsAllElements(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Collections.Generic.HashSet< T >.Count, System.Runtime.Serialization.Dictionary, System.Collections.Generic.HashSet< T >.EqualityComparersAreEqual(), System.other, and System.ThrowHelper.ThrowArgumentNullException().