Terraria: System.Collections.Generic.HashSet.Resize
Resize() [2/2]
void System.Collections.Generic.HashSet< T >.Resize (int newSize, bool forceNewHashCodes) inline private
Definition at line 807 of file HashSet.cs.
    {
        Entry[] array = new Entry[newSize];
        int count = _count;
        Array.Copy(_entries, array, count);
        if (!typeof(T).IsValueType && forceNewHashCodes)
        {
            _comparer = (IEqualityComparer<T>)((NonRandomizedStringEqualityComparer)_comparer).GetRandomizedEqualityComparer();
            for (int i = 0; i < count; i++)
            {
                ref Entry reference = ref array[i];
                if (reference.Next >= -1)
                {
                    reference.HashCode = ((reference.Value != null) ? _comparer.GetHashCode(reference.Value) : 0);
                }
            }
            if (_comparer == EqualityComparer<T>.Default)
            {
                _comparer = null;
            }
        }
        _buckets = new int[newSize];
        _fastModMultiplier = HashHelpers.GetFastModMultiplier((uint)newSize);
        for (int j = 0; j < count; j++)
        {
            ref Entry reference2 = ref array[j];
            if (reference2.Next >= -1)
            {
                ref int bucketRef = ref GetBucketRef(reference2.HashCode);
                reference2.Next = bucketRef - 1;
                bucketRef = j + 1;
            }
        }
        _entries = array;
    }
References System.Collections.Generic.HashSet< T >._buckets, System.Collections.Generic.HashSet< T >._comparer, System.Collections.Generic.HashSet< T >._count, System.Collections.Generic.HashSet< T >._entries, System.Collections.Generic.HashSet< T >._fastModMultiplier, System.array, System.Array.Copy(), System.count, System.Default, System.Runtime.Serialization.Dictionary, System.Collections.Generic.HashSet< T >.GetBucketRef(), System.Collections.HashHelpers.GetFastModMultiplier(), System.Collections.Generic.IEqualityComparer< in T >.GetHashCode(), and System.newSize.