Terraria: System.Collections.Generic.HashSet.EqualityComparersAreEqual
EqualityComparersAreEqual()
static bool System.Collections.Generic.HashSet< T >.EqualityComparersAreEqual (HashSet< T > set1, HashSet< T > set2) inline static package
Definition at line 1153 of file HashSet.cs.
    {
        return set1.Comparer.Equals(set2.Comparer);
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Comparer, and System.Collections.IEqualityComparer.Equals().
Referenced by System.Collections.Generic.HashSet< T >.HashSet(), System.Collections.Generic.HashSet< T >.IntersectWith(), System.Collections.Generic.HashSet< T >.IsProperSubsetOf(), System.Collections.Generic.HashSet< T >.IsProperSupersetOf(), System.Collections.Generic.HashSet< T >.IsSubsetOf(), System.Collections.Generic.HashSet< T >.IsSupersetOf(), System.Collections.Generic.HashSet< T >.SetEquals(), and System.Collections.Generic.HashSet< T >.SymmetricExceptWith().