Terraria: System.Collections.Generic.HashSet.HashSet
HashSet() [5/7]
System.Collections.Generic.HashSet< T >.HashSet (IEnumerable< T > collection, IEqualityComparer< T >? comparer) inline
Definition at line 154 of file HashSet.cs.
        : this(comparer)
    {
        if (collection == null)
        {
            ThrowHelper.ThrowArgumentNullException(ExceptionArgument.collection);
        }
        if (collection is HashSet<T> hashSet && EqualityComparersAreEqual(this, hashSet))
        {
            ConstructFrom(hashSet);
            return;
        }
        if (collection is ICollection<T> { Count: var count } && count > 0)
        {
            Initialize(count);
        }
        UnionWith(collection);
        if (_count > 0 && _entries.Length / _count > 3)
        {
            TrimExcess();
        }
    }
References System.Collections.Generic.HashSet< T >._count, System.Collections.Generic.HashSet< T >._entries, System.collection, System.Collections.Generic.HashSet< T >.ConstructFrom(), System.count, System.Collections.Generic.HashSet< T >.Count, System.Collections.Generic.HashSet< T >.EqualityComparersAreEqual(), System.Collections.Generic.HashSet< T >.Initialize(), System.ThrowHelper.ThrowArgumentNullException(), System.Collections.Generic.HashSet< T >.TrimExcess(), and System.Collections.Generic.HashSet< T >.UnionWith().