Terraria: System.Collections.Generic.HashSet.ExceptWith
ExceptWith()
void System.Collections.Generic.HashSet< T >.ExceptWith (IEnumerable< T > other) inline
Implements System.Collections.Generic.ISet< T >.
Definition at line 496 of file HashSet.cs.
    {
        if (other == null)
        {
            ThrowHelper.ThrowArgumentNullException(ExceptionArgument.other);
        }
        if (Count == 0)
        {
            return;
        }
        if (other == this)
        {
            Clear();
            return;
        }
        foreach (T item in other)
        {
            Remove(item);
        }
    }
References System.Collections.Generic.HashSet< T >.Clear(), System.Collections.Generic.HashSet< T >.Count, System.item, System.other, System.Collections.Generic.HashSet< T >.Remove(), and System.ThrowHelper.ThrowArgumentNullException().