Terraria: System.Collections.Generic.HashSet.Initialize
Initialize()
int System.Collections.Generic.HashSet< T >.Initialize (int capacity) inline private
Definition at line 880 of file HashSet.cs.
    {
        int prime = HashHelpers.GetPrime(capacity);
        int[] buckets = new int[prime];
        Entry[] entries = new Entry[prime];
        _freeList = -1;
        _buckets = buckets;
        _entries = entries;
        _fastModMultiplier = HashHelpers.GetFastModMultiplier((uint)prime);
        return prime;
    }
References System.Collections.Generic.HashSet< T >._buckets, System.Collections.Generic.HashSet< T >._entries, System.Collections.Generic.HashSet< T >._fastModMultiplier, System.Collections.Generic.HashSet< T >._freeList, System.capacity, System.Runtime.Serialization.Dictionary, System.Collections.HashHelpers.GetFastModMultiplier(), and System.Collections.HashHelpers.GetPrime().
Referenced by System.Collections.Generic.HashSet< T >.HashSet(), System.Collections.Generic.HashSet< T >.HashSet(), System.Collections.Generic.HashSet< T >.AddIfNotPresent(), System.Collections.Generic.HashSet< T >.ConstructFrom(), System.Collections.Generic.HashSet< T >.EnsureCapacity(), and System.Collections.Generic.HashSet< T >.TrimExcess().