Terraria: System.Collections.Generic.HashSet.FindItemIndex
FindItemIndex()
int System.Collections.Generic.HashSet< T >.FindItemIndex (T item) inline private
Definition at line 248 of file HashSet.cs.
    {
        int[] buckets = _buckets;
        if (buckets != null)
        {
            Entry[] entries = _entries;
            uint num = 0u;
            IEqualityComparer<T> comparer = _comparer;
            if (comparer == null)
            {
                int num2 = item?.GetHashCode() ?? 0;
                if (typeof(T).IsValueType)
                {
                    int num3 = GetBucketRef(num2) - 1;
                    while (num3 >= 0)
                    {
                        ref Entry reference = ref entries[num3];
                        if (reference.HashCode == num2 && EqualityComparer<T>.Default.Equals(reference.Value, item))
{
                            return num3;
                        }
                        num3 = reference.Next;
                        num++;
                        if (num > (uint)entries.Length)
{
                            ThrowHelper.ThrowInvalidOperationException_ConcurrentOperationsNotSupported();
                        }
                    }
                }
                else
                {
                    EqualityComparer<T> @default = EqualityComparer<T>.Default;
                    int num4 = GetBucketRef(num2) - 1;
                    while (num4 >= 0)
                    {
                        ref Entry reference2 = ref entries[num4];
                        if (reference2.HashCode == num2 && @default.Equals(reference2.Value, item))
{
                            return num4;
                        }
                        num4 = reference2.Next;
                        num++;
                        if (num > (uint)entries.Length)
{
                            ThrowHelper.ThrowInvalidOperationException_ConcurrentOperationsNotSupported();
                        }
                    }
                }
            }
            else
            {
                int num5 = ((item != null) ? comparer.GetHashCode(item) : 0);
                int num6 = GetBucketRef(num5) - 1;
                while (num6 >= 0)
                {
                    ref Entry reference3 = ref entries[num6];
                    if (reference3.HashCode == num5 && comparer.Equals(reference3.Value, item))
                    {
                        return num6;
                    }
                    num6 = reference3.Next;
                    num++;
                    if (num > (uint)entries.Length)
                    {
                        ThrowHelper.ThrowInvalidOperationException_ConcurrentOperationsNotSupported();
                    }
                }
            }
        }
        return -1;
    }
References System.Collections.Generic.HashSet< T >._buckets, System.Collections.Generic.HashSet< T >._comparer, System.Collections.Generic.HashSet< T >._entries, System.comparer, System.Runtime.Serialization.Dictionary, System.Collections.Generic.HashSet< T >.GetBucketRef(), System.item, and System.ThrowHelper.ThrowInvalidOperationException_ConcurrentOperationsNotSupported().
Referenced by System.Collections.Generic.HashSet< T >.AddIfNotPresent(), System.Collections.Generic.HashSet< T >.CheckUniqueAndUnfoundElements(), System.Collections.Generic.HashSet< T >.Contains(), System.Collections.Generic.HashSet< T >.IntersectWithEnumerable(), and System.Collections.Generic.HashSet< T >.TryGetValue().