Terraria: System.Collections.Generic.HashSet.OnDeserialization
OnDeserialization()
virtual void System.Collections.Generic.HashSet< T >.OnDeserialization (object? sender) inline virtual
Implements System.Runtime.Serialization.IDeserializationCallback.
Definition at line 403 of file HashSet.cs.
    {
        HashHelpers.SerializationInfoTable.TryGetValue(this, out var value);
        if (value == null)
        {
            return;
        }
        int @int = value.GetInt32("Capacity");
        _comparer = (IEqualityComparer<T>)value.GetValue("Comparer", typeof(IEqualityComparer<T>));
        _freeList = -1;
        _freeCount = 0;
        if (@int != 0)
        {
            _buckets = new int[@int];
            _entries = new Entry[@int];
            _fastModMultiplier = HashHelpers.GetFastModMultiplier((uint)@int);
            T[] array = (T[])value.GetValue("Elements", typeof(T[]));
            if (array == null)
            {
                ThrowHelper.ThrowSerializationException(ExceptionResource.Serialization_MissingKeys);
            }
            for (int i = 0; i < array.Length; i++)
            {
                AddIfNotPresent(array[i], out var _);
            }
        }
        else
        {
            _buckets = null;
        }
        _version = value.GetInt32("Version");
        HashHelpers.SerializationInfoTable.Remove(this);
    }
References System.Collections.Generic.HashSet< T >._buckets, System.Collections.Generic.HashSet< T >._comparer, System.Collections.Generic.HashSet< T >._entries, System.Collections.Generic.HashSet< T >._fastModMultiplier, System.Collections.Generic.HashSet< T >._freeCount, System.Collections.Generic.HashSet< T >._freeList, System.Collections.Generic.HashSet< T >._version, System.Collections.Generic.HashSet< T >.AddIfNotPresent(), System.array, System.Collections.HashHelpers.GetFastModMultiplier(), System.Collections.HashHelpers.SerializationInfoTable, System.ThrowHelper.ThrowSerializationException(), and System.value.