Terraria: System.Collections.Generic.HashSet.Add
Add() [1/2]
void ICollection< T >. System.Collections.Generic.HashSet< T >.Add (T item) inline private
Implements System.Collections.Generic.ICollection< T >.
Definition at line 225 of file HashSet.cs.
    {
        AddIfNotPresent(item, out var _);
    }
References System.Collections.Generic.HashSet< T >.AddIfNotPresent(), and System.item.
Referenced by Terraria.WorldBuilding.ShapeData.Add(), Terraria.GameContent.SpelunkerProjectileHelper.AddSpotToCheck(), Terraria.GameContent.SpelunkerProjectileHelper.CheckSpot(), System.Reflection.DispatchProxyGenerator.ProxyAssembly.EnsureTypeIsVisible(), Terraria.GameContent.Bestiary.NPCWasChatWithTracker.Load(), Terraria.GameContent.Bestiary.NPCWasNearPlayerTracker.Load(), System.Linq.Enumerable.DistinctIterator< TSource >.MoveNext(), System.Linq.Parallel.DistinctQueryOperator< TInputOutput >.DistinctQueryOperatorEnumerator< TKey >.MoveNext(), System.Linq.Parallel.ExceptQueryOperator< TInputOutput >.ExceptQueryOperatorEnumerator< TLeftKey >.MoveNext(), System.Linq.Parallel.IntersectQueryOperator< TInputOutput >.IntersectQueryOperatorEnumerator< TLeftKey >.MoveNext(), System.Linq.Parallel.UnionQueryOperator< TInputOutput >.UnionQueryOperatorEnumerator< TLeftKey, TRightKey >.MoveNext(), Terraria.GameContent.Bestiary.NPCWasChatWithTracker.RegisterChatStartWith(), Terraria.GameContent.Bestiary.NPCWasNearPlayerTracker.RegisterWasNearby(), Terraria.Social.Steam.Lobby.SetPlayedWith(), Terraria.GameContent.Bestiary.NPCWasChatWithTracker.SetWasChatWithDirectly(), Terraria.GameContent.Bestiary.NPCWasNearPlayerTracker.SetWasSeenDirectly(), and Terraria.Player.UpdateBlacklistedTilesForGrappling().