Terraria: System.Collections.Generic.HashSet.UnionWith
UnionWith()
void System.Collections.Generic.HashSet< T >.UnionWith (IEnumerable< T > other) inline
Implements System.Collections.Generic.ISet< T >.
Definition at line 458 of file HashSet.cs.
    {
        if (other == null)
        {
            ThrowHelper.ThrowArgumentNullException(ExceptionArgument.other);
        }
        foreach (T item in other)
        {
            AddIfNotPresent(item, out var _);
        }
    }
References System.Collections.Generic.HashSet< T >.AddIfNotPresent(), System.item, System.other, and System.ThrowHelper.ThrowArgumentNullException().
Referenced by System.Collections.Generic.HashSet< T >.HashSet(), and System.Collections.Generic.HashSet< T >.SymmetricExceptWith().