Terraria: System.Collections.Generic.HashSet.AddIfNotPresent
AddIfNotPresent()
bool System.Collections.Generic.HashSet< T >.AddIfNotPresent (T value, out int location) inline private
Definition at line 892 of file HashSet.cs.
    {
        if (_buckets == null)
        {
            Initialize(0);
        }
        Entry[] entries = _entries;
        IEqualityComparer<T> comparer = _comparer;
        uint num = 0u;
        ref int reference = ref Unsafe.NullRef<int>();
        int num2;
        if (comparer == null)
        {
            num2 = value?.GetHashCode() ?? 0;
            reference = ref GetBucketRef(num2);
            int num3 = reference - 1;
            if (typeof(T).IsValueType)
            {
                while (num3 >= 0)
                {
                    ref Entry reference2 = ref entries[num3];
                    if (reference2.HashCode == num2 && EqualityComparer<T>.Default.Equals(reference2.Value, value))
                    {
                        location = num3;
                        return false;
                    }
                    num3 = reference2.Next;
                    num++;
                    if (num > (uint)entries.Length)
                    {
                        ThrowHelper.ThrowInvalidOperationException_ConcurrentOperationsNotSupported();
                    }
                }
            }
            else
            {
                EqualityComparer<T> @default = EqualityComparer<T>.Default;
                while (num3 >= 0)
                {
                    ref Entry reference3 = ref entries[num3];
                    if (reference3.HashCode == num2 && @default.Equals(reference3.Value, value))
                    {
                        location = num3;
                        return false;
                    }
                    num3 = reference3.Next;
                    num++;
                    if (num > (uint)entries.Length)
                    {
                        ThrowHelper.ThrowInvalidOperationException_ConcurrentOperationsNotSupported();
                    }
                }
            }
        }
        else
        {
            num2 = ((value != null) ? comparer.GetHashCode(value) : 0);
            reference = ref GetBucketRef(num2);
            int num4 = reference - 1;
            while (num4 >= 0)
            {
                ref Entry reference4 = ref entries[num4];
                if (reference4.HashCode == num2 && comparer.Equals(reference4.Value, value))
                {
                    location = num4;
                    return false;
                }
                num4 = reference4.Next;
                num++;
                if (num > (uint)entries.Length)
                {
                    ThrowHelper.ThrowInvalidOperationException_ConcurrentOperationsNotSupported();
                }
            }
        }
        int num5;
        if (_freeCount > 0)
        {
            num5 = _freeList;
            _freeCount--;
            _freeList = -3 - entries[_freeList].Next;
        }
        else
        {
            int count = _count;
            if (count == entries.Length)
            {
                Resize();
                reference = ref GetBucketRef(num2);
            }
            num5 = count;
            _count = count + 1;
            entries = _entries;
        }
        ref Entry reference5 = ref entries[num5];
        reference5.HashCode = num2;
        reference5.Next = reference - 1;
        reference5.Value = value;
        reference = num5 + 1;
        _version++;
        location = num5;
        if (!typeof(T).IsValueType && num > 100 && comparer is NonRandomizedStringEqualityComparer)
        {
            Resize(entries.Length, forceNewHashCodes: true);
            location = FindItemIndex(value);
        }
        return true;
    }
References System.Collections.Generic.HashSet< T >._buckets, System.Collections.Generic.HashSet< T >._comparer, System.Collections.Generic.HashSet< T >._count, System.Collections.Generic.HashSet< T >._entries, System.Collections.Generic.HashSet< T >._freeCount, System.Collections.Generic.HashSet< T >._freeList, System.Collections.Generic.HashSet< T >._version, System.comparer, System.count, System.Runtime.Serialization.Dictionary, System.Collections.Generic.HashSet< T >.FindItemIndex(), System.Collections.Generic.HashSet< T >.GetBucketRef(), System.Collections.Generic.HashSet< T >.Initialize(), System.Collections.Generic.HashSet< T >.Resize(), System.ThrowHelper.ThrowInvalidOperationException_ConcurrentOperationsNotSupported(), and System.value.
Referenced by System.Collections.Generic.HashSet< T >.Add(), System.Collections.Generic.HashSet< T >.ConstructFrom(), System.Collections.Generic.HashSet< T >.OnDeserialization(), System.Collections.Generic.HashSet< T >.SymmetricExceptWithEnumerable(), System.Collections.Generic.HashSet< T >.SymmetricExceptWithUniqueHashSet(), and System.Collections.Generic.HashSet< T >.UnionWith().