Terraria: System.Collections.Generic.HashSet.GetBucketRef
GetBucketRef()
ref int System.Collections.Generic.HashSet< T >.GetBucketRef (int hashCode) inline private
Definition at line 321 of file HashSet.cs.
    {
        int[] buckets = _buckets;
        return ref buckets[HashHelpers.FastMod((uint)hashCode, (uint)buckets.Length, _fastModMultiplier)];
    }
References System.Collections.Generic.HashSet< T >._buckets, System.Collections.Generic.HashSet< T >._fastModMultiplier, and System.Collections.HashHelpers.FastMod().
Referenced by System.Collections.Generic.HashSet< T >.AddIfNotPresent(), System.Collections.Generic.HashSet< T >.FindItemIndex(), System.Collections.Generic.HashSet< T >.Remove(), System.Collections.Generic.HashSet< T >.Resize(), and System.Collections.Generic.HashSet< T >.TrimExcess().