Terraria: System.Collections.Generic.HashSet.ConstructFrom
ConstructFrom()
void System.Collections.Generic.HashSet< T >.ConstructFrom (HashSet< T > source) inline private
Definition at line 195 of file HashSet.cs.
    {
        if (source.Count == 0)
        {
            return;
        }
        int num = source._buckets.Length;
        int num2 = HashHelpers.ExpandPrime(source.Count + 1);
        if (num2 >= num)
        {
            _buckets = (int[])source._buckets.Clone();
            _entries = (Entry[])source._entries.Clone();
            _freeList = source._freeList;
            _freeCount = source._freeCount;
            _count = source._count;
            _fastModMultiplier = source._fastModMultiplier;
            return;
        }
        Initialize(source.Count);
        Entry[] entries = source._entries;
        for (int i = 0; i < source._count; i++)
        {
            ref Entry reference = ref entries[i];
            if (reference.Next >= -1)
            {
                AddIfNotPresent(reference.Value, out var _);
            }
        }
    }
References System.Collections.Generic.Dictionary< TKey, TValue >._buckets, System.Collections.Generic.HashSet< T >._buckets, System.Collections.Generic.HashSet< T >._count, System.Collections.Generic.Dictionary< TKey, TValue >._entries, System.Collections.Generic.HashSet< T >._entries, System.Collections.Generic.HashSet< T >._fastModMultiplier, System.Collections.Generic.HashSet< T >._freeCount, System.Collections.Generic.HashSet< T >._freeList, System.Collections.Generic.HashSet< T >.AddIfNotPresent(), System.Collections.HashHelpers.ExpandPrime(), System.Collections.Generic.HashSet< T >.Initialize(), and System.source.
Referenced by System.Collections.Generic.HashSet< T >.HashSet().