Terraria: System.Collections.Generic.HashSet.CheckUniqueAndUnfoundElements
CheckUniqueAndUnfoundElements()
int int UnfoundCount System.Collections.Generic.HashSet< T >.CheckUniqueAndUnfoundElements (IEnumerable< T > other, bool returnIfUnfound) inline private
Definition at line 1109 of file HashSet.cs.
    {
        if (_count == 0)
        {
            int num = 0;
            using (IEnumerator<T> enumerator = other.GetEnumerator())
            {
                if (enumerator.MoveNext())
                {
                    T current = enumerator.Current;
                    num++;
                }
            }
            return (UniqueCount: 0, UnfoundCount: num);
        }
        int count = _count;
        int num2 = BitHelper.ToIntArrayLength(count);
        Span<int> span = stackalloc int[100];
        BitHelper bitHelper = ((num2 <= 100) ? new BitHelper(span.Slice(0, num2), clear: true) : new BitHelper(new int[num2], clear: false));
        int num3 = 0;
        int num4 = 0;
        foreach (T item in other)
        {
            int num5 = FindItemIndex(item);
            if (num5 >= 0)
            {
                if (!bitHelper.IsMarked(num5))
                {
                    bitHelper.MarkBit(num5);
                    num4++;
                }
            }
            else
            {
                num3++;
                if (returnIfUnfound)
                {
                    break;
                }
            }
        }
        return (UniqueCount: num4, UnfoundCount: num3);
    }
References System.Collections.Generic.HashSet< T >._count, System.count, System.Runtime.Serialization.Dictionary, System.Collections.Generic.HashSet< T >.FindItemIndex(), System.Collections.Generic.Dictionary< TKey, TValue >.GetEnumerator(), System.item, System.other, System.Collections.Generic.BitHelper.ToIntArrayLength(), and System.Collections.Generic.HashSet< T >.UniqueCount.
Referenced by System.Collections.Generic.HashSet< T >.IsProperSubsetOf(), System.Collections.Generic.HashSet< T >.IsProperSupersetOf(), System.Collections.Generic.HashSet< T >.IsSubsetOf(), and System.Collections.Generic.HashSet< T >.SetEquals().