Terraria: System.Collections.Generic.HashSet.EnsureCapacity
EnsureCapacity()
int System.Collections.Generic.HashSet< T >.EnsureCapacity (int capacity) inline
Definition at line 782 of file HashSet.cs.
    {
        if (capacity < 0)
        {
            ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument.capacity);
        }
        int num = ((_entries != null) ? _entries.Length : 0);
        if (num >= capacity)
        {
            return num;
        }
        if (_buckets == null)
        {
            return Initialize(capacity);
        }
        int prime = HashHelpers.GetPrime(capacity);
        Resize(prime, forceNewHashCodes: false);
        return prime;
    }
References System.Collections.Generic.HashSet< T >._buckets, System.Collections.Generic.HashSet< T >._entries, System.capacity, System.Runtime.Serialization.Dictionary, System.Collections.HashHelpers.GetPrime(), System.Collections.Generic.HashSet< T >.Initialize(), System.Collections.Generic.HashSet< T >.Resize(), and System.ThrowHelper.ThrowArgumentOutOfRangeException().