Terraria: System.Collections.Generic.HashSet.IntersectWithEnumerable
IntersectWithEnumerable()
void System.Collections.Generic.HashSet< T >.IntersectWithEnumerable (IEnumerable< T > other) inline private
Definition at line 1046 of file HashSet.cs.
    {
        int count = _count;
        int num = BitHelper.ToIntArrayLength(count);
        Span<int> span = stackalloc int[100];
        BitHelper bitHelper = ((num <= 100) ? new BitHelper(span.Slice(0, num), clear: true) : new BitHelper(new int[num], clear: false));
        foreach (T item in other)
        {
            int num2 = FindItemIndex(item);
            if (num2 >= 0)
            {
                bitHelper.MarkBit(num2);
            }
        }
        for (int i = 0; i < count; i++)
        {
            ref Entry reference = ref _entries[i];
            if (reference.Next >= -1 && !bitHelper.IsMarked(i))
            {
                Remove(reference.Value);
            }
        }
    }
References System.Collections.Generic.HashSet< T >._count, System.Collections.Generic.HashSet< T >._entries, System.count, System.Runtime.Serialization.Dictionary, System.Collections.Generic.HashSet< T >.FindItemIndex(), System.item, System.other, System.Collections.Generic.HashSet< T >.Remove(), and System.Collections.Generic.BitHelper.ToIntArrayLength().
Referenced by System.Collections.Generic.HashSet< T >.IntersectWith().