Terraria: System.Collections.Generic.HashSet.TrimExcess
TrimExcess()
void System.Collections.Generic.HashSet< T >.TrimExcess () inline
Definition at line 843 of file HashSet.cs.
    {
        int count = Count;
        int prime = HashHelpers.GetPrime(count);
        Entry[] entries = _entries;
        int num = ((entries != null) ? entries.Length : 0);
        if (prime >= num)
        {
            return;
        }
        int count2 = _count;
        _version++;
        Initialize(prime);
        Entry[] entries2 = _entries;
        int num2 = 0;
        for (int i = 0; i < count2; i++)
        {
            int hashCode = entries[i].HashCode;
            if (entries[i].Next >= -1)
            {
                ref Entry reference = ref entries2[num2];
                reference = entries[i];
                ref int bucketRef = ref GetBucketRef(hashCode);
                reference.Next = bucketRef - 1;
                bucketRef = num2 + 1;
                num2++;
            }
        }
        _count = count;
        _freeCount = 0;
    }
References System.Collections.Generic.HashSet< T >._count, System.Collections.Generic.HashSet< T >._entries, System.Collections.Generic.HashSet< T >._freeCount, System.Collections.Generic.HashSet< T >._version, System.count, System.Collections.Generic.HashSet< T >.Count, System.Runtime.Serialization.Dictionary, System.Collections.Generic.HashSet< T >.GetBucketRef(), System.Collections.HashHelpers.GetPrime(), and System.Collections.Generic.HashSet< T >.Initialize().
Referenced by System.Collections.Generic.HashSet< T >.HashSet().