Terraria: System.Collections.Generic.HashSet.Contains
Contains()
bool System.Collections.Generic.HashSet< T >.Contains (T item) inline
Implements System.Collections.Generic.ICollection< T >.
Definition at line 243 of file HashSet.cs.
    {
        return FindItemIndex(item) >= 0;
    }
References System.Collections.Generic.HashSet< T >.FindItemIndex(), and System.item.
Referenced by Terraria.WorldBuilding.ShapeData.Contains(), System.Collections.Generic.HashSet< T >.ContainsAllElements(), System.Reflection.DispatchProxyGenerator.ProxyAssembly.EnsureTypeIsVisible(), Terraria.GameContent.Creative.ItemFilters.Tools.FitsFilter(), Terraria.GameContent.Bestiary.NPCWasChatWithTracker.GetWasChatWith(), Terraria.GameContent.Bestiary.NPCWasChatWithTracker.GetWasChatWith(), Terraria.GameContent.Bestiary.NPCWasNearPlayerTracker.GetWasNearbyBefore(), Terraria.Player.IsBlacklistedForGrappling(), System.Xml.Serialization.XmlSerializationWriter.NextPrefix(), System.Collections.Generic.HashSet< T >.Overlaps(), Terraria.GameContent.Bestiary.NPCWasChatWithTracker.RegisterChatStartWith(), Terraria.GameContent.Bestiary.NPCWasNearPlayerTracker.RegisterWasNearby(), Terraria.Social.Steam.Lobby.SetPlayedWith(), Terraria.GameContent.UI.BigProgressBar.GolemHeadProgressBar.TryFindingAnotherGolemPiece(), Terraria.GameContent.UI.BigProgressBar.MartianSaucerBigProgressBar.TryFindingAnotherMartianSaucerPiece(), Terraria.GameContent.UI.BigProgressBar.MoonLordProgressBar.TryFindingAnotherMoonLordPiece(), Terraria.GameContent.UI.BigProgressBar.PirateShipBigProgressBar.TryFindingAnotherPirateShipPiece(), Terraria.GameContent.UI.BigProgressBar.GolemHeadProgressBar.ValidateAndCollectNecessaryInfo(), Terraria.GameContent.UI.BigProgressBar.MartianSaucerBigProgressBar.ValidateAndCollectNecessaryInfo(), and Terraria.GameContent.UI.BigProgressBar.MoonLordProgressBar.ValidateAndCollectNecessaryInfo().