Terraria: Terraria.GameContent.Tile_Entities.TEFoodPlatter.Place
Place()
static int Terraria.GameContent.Tile_Entities.TEFoodPlatter.Place (int x, int y) inline static
Definition at line 39 of file TEFoodPlatter.cs.
    {
        TEFoodPlatter tEFoodPlatter = new TEFoodPlatter();
        tEFoodPlatter.Position = new Point16(x, y);
        tEFoodPlatter.ID = TileEntity.AssignNewID();
        tEFoodPlatter.type = _myEntityID;
        lock (TileEntity.EntityCreationLock)
        {
            TileEntity.ByID[tEFoodPlatter.ID] = tEFoodPlatter;
            TileEntity.ByPosition[tEFoodPlatter.Position] = tEFoodPlatter;
        }
        return tEFoodPlatter.ID;
    }
References Terraria.GameContent.Tile_Entities.TEFoodPlatter.TEFoodPlatter(), Terraria.GameContent.Tile_Entities.TEFoodPlatter._myEntityID, Terraria.DataStructures.TileEntity.AssignNewID(), Terraria.DataStructures.TileEntity.ByID, Terraria.DataStructures.TileEntity.ByPosition, Terraria.DataStructures.TileEntity.EntityCreationLock, Terraria.DataStructures.TileEntity.ID, and Terraria.DataStructures.TileEntity.Position.
Referenced by Terraria.GameContent.Tile_Entities.TEFoodPlatter.Hook_AfterPlacement(), and Terraria.GameContent.Tile_Entities.TEFoodPlatter.NetPlaceEntity().