Terraria: Terraria.GameContent.Tile_Entities.TEFoodPlatter.TryPlacing
TryPlacing()
static void Terraria.GameContent.Tile_Entities.TEFoodPlatter.TryPlacing (int x, int y, int netid, int prefix, int stack) inline static
Definition at line 128 of file TEFoodPlatter.cs.
    {
        WorldGen.RangeFrame(x, y, x + 1, y + 1);
        int num = Find(x, y);
        if (num == -1)
        {
            int num2 = Item.NewItem(new EntitySource_TileBreak(x, y), x * 16, y * 16, 16, 16, 1);
            Main.item[num2].netDefaults(netid);
            Main.item[num2].Prefix(prefix);
            Main.item[num2].stack = stack;
            NetMessage.SendData(21, -1, -1, null, num2);
            return;
        }
        TEFoodPlatter tEFoodPlatter = (TEFoodPlatter)TileEntity.ByID[num];
        if (tEFoodPlatter.item.stack > 0)
        {
            tEFoodPlatter.DropItem();
        }
        tEFoodPlatter.item = new Item();
        tEFoodPlatter.item.netDefaults(netid);
        tEFoodPlatter.item.Prefix(prefix);
        tEFoodPlatter.item.stack = stack;
        NetMessage.SendData(86, -1, -1, null, tEFoodPlatter.ID, x, y);
    }
References Terraria.GameContent.Tile_Entities.TEFoodPlatter.TEFoodPlatter(), Terraria.DataStructures.TileEntity.ByID, Terraria.GameContent.Tile_Entities.TEFoodPlatter.DropItem(), Terraria.GameContent.Tile_Entities.TEFoodPlatter.Find(), Terraria.DataStructures.TileEntity.ID, Terraria.GameContent.Tile_Entities.TEFoodPlatter.item, Terraria.Main.item, Terraria.Item.netDefaults(), Terraria.Item.NewItem(), Terraria.Item.Prefix(), Terraria.WorldGen.RangeFrame(), Terraria.NetMessage.SendData(), and Terraria.Item.stack.
Referenced by Terraria.MessageBuffer.GetData(), and Terraria.GameContent.Tile_Entities.TEFoodPlatter.PlaceItemInFrame().