Terraria: System.Collections.Immutable.ImmutableDictionary.RemoveRange
RemoveRange() [1/2]
ImmutableDictionary< TKey, TValue > System.Collections.Immutable.ImmutableDictionary< TKey, TValue >.RemoveRange (IEnumerable< TKey > keys) inline
Implements System.Collections.Immutable.IImmutableDictionary< TKey, TValue >.
Definition at line 1140 of file ImmutableDictionary.cs.
    {
        Requires.NotNull(keys, "keys");
        int num = _count;
        SortedInt32KeyNode<HashBucket> sortedInt32KeyNode = _root;
        foreach (TKey key in keys)
        {
            int hashCode = KeyComparer.GetHashCode(key);
            if (sortedInt32KeyNode.TryGetValue(hashCode, out var value))
            {
                OperationResult result;
                HashBucket newBucket = value.Remove(key, _comparers.KeyOnlyComparer, out result);
                sortedInt32KeyNode = UpdateRoot(sortedInt32KeyNode, hashCode, newBucket, _comparers.HashBucketEqualityComparer);
                if (result == OperationResult.SizeChanged)
                {
                    num--;
                }
            }
        }
        return Wrap(sortedInt32KeyNode, num);
    }
References System.Collections.Immutable.ImmutableDictionary< TKey, TValue >._comparers, System.Collections.Immutable.ImmutableDictionary< TKey, TValue >._count, System.Collections.Immutable.ImmutableDictionary< TKey, TValue >._root, System.Collections.IEqualityComparer.GetHashCode(), System.Collections.Immutable.ImmutableDictionary< TKey, TValue >.Comparers.HashBucketEqualityComparer, System.key, System.Collections.Immutable.ImmutableDictionary< TKey, TValue >.KeyComparer, System.Collections.Immutable.ImmutableDictionary< TKey, TValue >.Comparers.KeyOnlyComparer, System.keys, System.Collections.Generic.Dictionary< TKey, TValue >.Remove(), System.Collections.Generic.Dictionary< TKey, TValue >.TryGetValue(), System.Collections.Immutable.ImmutableDictionary< TKey, TValue >.UpdateRoot(), System.value, and System.Collections.Immutable.ImmutableDictionary< TKey, TValue >.Wrap().
Referenced by System.Collections.Immutable.ImmutableDictionary< TKey, TValue >.RemoveRange().