Terraria: System.Collections.Immutable.ImmutableDictionary.Contains
Contains() [1/3]
static bool System.Collections.Immutable.ImmutableDictionary< TKey, TValue >.Contains (KeyValuePair< TKey, TValue > keyValuePair, MutationInput origin) inline static private
Definition at line 1391 of file ImmutableDictionary.cs.
    {
        int hashCode = origin.KeyComparer.GetHashCode(keyValuePair.Key);
        if (origin.Root.TryGetValue(hashCode, out var value))
        {
            if (value.TryGetValue(keyValuePair.Key, origin.Comparers, out var value2))
            {
                return origin.ValueComparer.Equals(value2, keyValuePair.Value);
            }
            return false;
        }
        return false;
    }
References System.Collections.Immutable.ImmutableDictionary< TKey, TValue >.MutationInput.Comparers, System.Collections.IEqualityComparer.Equals(), System.Collections.IEqualityComparer.GetHashCode(), System.Collections.Immutable.ImmutableDictionary< TKey, TValue >.MutationInput.KeyComparer, System.Collections.Immutable.ImmutableDictionary< TKey, TValue >.MutationInput.Root, System.Collections.Generic.Dictionary< TKey, TValue >.TryGetValue(), System.value, and System.Collections.Immutable.ImmutableDictionary< TKey, TValue >.MutationInput.ValueComparer.