Terraria: SocialAPI.Initialize
Initialize()
static void SocialAPI.Initialize (SocialMode? mode = null) inline static
     {
         if (!mode.HasValue)
         {
             mode = SocialMode.None;
             _ = Main.dedServ;
         }
         _mode = mode.Value;
         _modules = new List<ISocialModule>();
         JoinRequests = new ServerJoinRequestsManager();
         Main.OnTickForInternalCodeOnly += JoinRequests.Update;
         switch (Mode)
         {
         case SocialMode.Steam:
             LoadSteam();
             break;
         case SocialMode.WeGame:
             LoadWeGame();
             break;
         }
         foreach (ISocialModule module in _modules)
         {
             module.Initialize();
         }
     }
References _mode, _modules, Main.dedServ, ISocialModule.Initialize(), JoinRequests, LoadSteam(), LoadWeGame(), Mode, Main.OnTickForInternalCodeOnly, and ServerJoinRequestsManager.Update().
Referenced by Program.RunGame().