Terraria: System.Buffers.Text.Utf8Parser.TryParseDateTimeOffsetO
TryParseDateTimeOffsetO()
static bool System.Buffers.Text.Utf8Parser.TryParseDateTimeOffsetO (ReadOnlySpan< byte > source, out DateTimeOffset value, out int bytesConsumed, out DateTimeKind kind) inline static private
Definition at line 569 of file Utf8Parser.cs.
    {
        if (source.Length < 27)
        {
            value = default(DateTimeOffset);
            bytesConsumed = 0;
            kind = DateTimeKind.Unspecified;
            return false;
        }
        uint num = (uint)(source[0] - 48);
        uint num2 = (uint)(source[1] - 48);
        uint num3 = (uint)(source[2] - 48);
        uint num4 = (uint)(source[3] - 48);
        if (num > 9 || num2 > 9 || num3 > 9 || num4 > 9)
        {
            value = default(DateTimeOffset);
            bytesConsumed = 0;
            kind = DateTimeKind.Unspecified;
            return false;
        }
        int year = (int)(num * 1000 + num2 * 100 + num3 * 10 + num4);
        if (source[4] != 45)
        {
            value = default(DateTimeOffset);
            bytesConsumed = 0;
            kind = DateTimeKind.Unspecified;
            return false;
        }
        uint num5 = (uint)(source[5] - 48);
        uint num6 = (uint)(source[6] - 48);
        if (num5 > 9 || num6 > 9)
        {
            value = default(DateTimeOffset);
            bytesConsumed = 0;
            kind = DateTimeKind.Unspecified;
            return false;
        }
        int month = (int)(num5 * 10 + num6);
        if (source[7] != 45)
        {
            value = default(DateTimeOffset);
            bytesConsumed = 0;
            kind = DateTimeKind.Unspecified;
            return false;
        }
        uint num7 = (uint)(source[8] - 48);
        uint num8 = (uint)(source[9] - 48);
        if (num7 > 9 || num8 > 9)
        {
            value = default(DateTimeOffset);
            bytesConsumed = 0;
            kind = DateTimeKind.Unspecified;
            return false;
        }
        int day = (int)(num7 * 10 + num8);
        if (source[10] != 84)
        {
            value = default(DateTimeOffset);
            bytesConsumed = 0;
            kind = DateTimeKind.Unspecified;
            return false;
        }
        uint num9 = (uint)(source[11] - 48);
        uint num10 = (uint)(source[12] - 48);
        if (num9 > 9 || num10 > 9)
        {
            value = default(DateTimeOffset);
            bytesConsumed = 0;
            kind = DateTimeKind.Unspecified;
            return false;
        }
        int hour = (int)(num9 * 10 + num10);
        if (source[13] != 58)
        {
            value = default(DateTimeOffset);
            bytesConsumed = 0;
            kind = DateTimeKind.Unspecified;
            return false;
        }
        uint num11 = (uint)(source[14] - 48);
        uint num12 = (uint)(source[15] - 48);
        if (num11 > 9 || num12 > 9)
        {
            value = default(DateTimeOffset);
            bytesConsumed = 0;
            kind = DateTimeKind.Unspecified;
            return false;
        }
        int minute = (int)(num11 * 10 + num12);
        if (source[16] != 58)
        {
            value = default(DateTimeOffset);
            bytesConsumed = 0;
            kind = DateTimeKind.Unspecified;
            return false;
        }
        uint num13 = (uint)(source[17] - 48);
        uint num14 = (uint)(source[18] - 48);
        if (num13 > 9 || num14 > 9)
        {
            value = default(DateTimeOffset);
            bytesConsumed = 0;
            kind = DateTimeKind.Unspecified;
            return false;
        }
        int second = (int)(num13 * 10 + num14);
        if (source[19] != 46)
        {
            value = default(DateTimeOffset);
            bytesConsumed = 0;
            kind = DateTimeKind.Unspecified;
            return false;
        }
        uint num15 = (uint)(source[20] - 48);
        uint num16 = (uint)(source[21] - 48);
        uint num17 = (uint)(source[22] - 48);
        uint num18 = (uint)(source[23] - 48);
        uint num19 = (uint)(source[24] - 48);
        uint num20 = (uint)(source[25] - 48);
        uint num21 = (uint)(source[26] - 48);
        if (num15 > 9 || num16 > 9 || num17 > 9 || num18 > 9 || num19 > 9 || num20 > 9 || num21 > 9)
        {
            value = default(DateTimeOffset);
            bytesConsumed = 0;
            kind = DateTimeKind.Unspecified;
            return false;
        }
        int fraction = (int)(num15 * 1000000 + num16 * 100000 + num17 * 10000 + num18 * 1000 + num19 * 100 + num20 * 10 + num21);
        byte b = (byte)((source.Length > 27) ? source[27] : 0);
        if (b != 90 && b != 43 && b != 45)
        {
            if (!TryCreateDateTimeOffsetInterpretingDataAsLocalTime(year, month, day, hour, minute, second, fraction, out value))
            {
                value = default(DateTimeOffset);
                bytesConsumed = 0;
                kind = DateTimeKind.Unspecified;
                return false;
            }
            bytesConsumed = 27;
            kind = DateTimeKind.Unspecified;
            return true;
        }
        if (b == 90)
        {
            if (!TryCreateDateTimeOffset(year, month, day, hour, minute, second, fraction, offsetNegative: false, 0, 0, out value))
            {
                value = default(DateTimeOffset);
                bytesConsumed = 0;
                kind = DateTimeKind.Unspecified;
                return false;
            }
            bytesConsumed = 28;
            kind = DateTimeKind.Utc;
            return true;
        }
        if (source.Length < 33)
        {
            value = default(DateTimeOffset);
            bytesConsumed = 0;
            kind = DateTimeKind.Unspecified;
            return false;
        }
        uint num22 = (uint)(source[28] - 48);
        uint num23 = (uint)(source[29] - 48);
        if (num22 > 9 || num23 > 9)
        {
            value = default(DateTimeOffset);
            bytesConsumed = 0;
            kind = DateTimeKind.Unspecified;
            return false;
        }
        int offsetHours = (int)(num22 * 10 + num23);
        if (source[30] != 58)
        {
            value = default(DateTimeOffset);
            bytesConsumed = 0;
            kind = DateTimeKind.Unspecified;
            return false;
        }
        uint num24 = (uint)(source[31] - 48);
        uint num25 = (uint)(source[32] - 48);
        if (num24 > 9 || num25 > 9)
        {
            value = default(DateTimeOffset);
            bytesConsumed = 0;
            kind = DateTimeKind.Unspecified;
            return false;
        }
        int offsetMinutes = (int)(num24 * 10 + num25);
        if (!TryCreateDateTimeOffset(year, month, day, hour, minute, second, fraction, b == 45, offsetHours, offsetMinutes, out value))
        {
            value = default(DateTimeOffset);
            bytesConsumed = 0;
            kind = DateTimeKind.Unspecified;
            return false;
        }
        bytesConsumed = 33;
        kind = DateTimeKind.Local;
        return true;
    }
References System.source, System.Buffers.Text.Utf8Parser.TryCreateDateTimeOffset(), System.Buffers.Text.Utf8Parser.TryCreateDateTimeOffsetInterpretingDataAsLocalTime(), System.value, and System.year.
Referenced by System.Buffers.Text.Utf8Parser.TryParse(), and System.Buffers.Text.Utf8Parser.TryParse().