Terraria: System.Buffers.Text.Utf8Parser.TryParseDateTimeOffsetR
TryParseDateTimeOffsetR()
static bool System.Buffers.Text.Utf8Parser.TryParseDateTimeOffsetR (ReadOnlySpan< byte > source, uint caseFlipXorMask, out DateTimeOffset dateTimeOffset, out int bytesConsumed) inline static private
Definition at line 770 of file Utf8Parser.cs.
    {
        if (source.Length < 29)
        {
            bytesConsumed = 0;
            dateTimeOffset = default(DateTimeOffset);
            return false;
        }
        uint num = source[0] ^ caseFlipXorMask;
        uint num2 = source[1];
        uint num3 = source[2];
        uint num4 = source[3];
        DayOfWeek dayOfWeek;
        switch ((num << 24) | (num2 << 16) | (num3 << 8) | num4)
        {
        case 1400204844u:
            dayOfWeek = DayOfWeek.Sunday;
            break;
        case 1299148332u:
            dayOfWeek = DayOfWeek.Monday;
            break;
        case 1416979756u:
            dayOfWeek = DayOfWeek.Tuesday;
            break;
        case 1466262572u:
            dayOfWeek = DayOfWeek.Wednesday;
            break;
        case 1416131884u:
            dayOfWeek = DayOfWeek.Thursday;
            break;
        case 1181903148u:
            dayOfWeek = DayOfWeek.Friday;
            break;
        case 1398895660u:
            dayOfWeek = DayOfWeek.Saturday;
            break;
        default:
            bytesConsumed = 0;
            dateTimeOffset = default(DateTimeOffset);
            return false;
        }
        if (source[4] != 32)
        {
            bytesConsumed = 0;
            dateTimeOffset = default(DateTimeOffset);
            return false;
        }
        uint num5 = (uint)(source[5] - 48);
        uint num6 = (uint)(source[6] - 48);
        if (num5 > 9 || num6 > 9)
        {
            bytesConsumed = 0;
            dateTimeOffset = default(DateTimeOffset);
            return false;
        }
        int day = (int)(num5 * 10 + num6);
        if (source[7] != 32)
        {
            bytesConsumed = 0;
            dateTimeOffset = default(DateTimeOffset);
            return false;
        }
        uint num7 = source[8] ^ caseFlipXorMask;
        uint num8 = source[9];
        uint num9 = source[10];
        uint num10 = source[11];
        int month;
        switch ((num7 << 24) | (num8 << 16) | (num9 << 8) | num10)
        {
        case 1247899168u:
            month = 1;
            break;
        case 1181049376u:
            month = 2;
            break;
        case 1298231840u:
            month = 3;
            break;
        case 1097888288u:
            month = 4;
            break;
        case 1298233632u:
            month = 5;
            break;
        case 1249209888u:
            month = 6;
            break;
        case 1249209376u:
            month = 7;
            break;
        case 1098213152u:
            month = 8;
            break;
        case 1399156768u:
            month = 9;
            break;
        case 1331917856u:
            month = 10;
            break;
        case 1315927584u:
            month = 11;
            break;
        case 1147495200u:
            month = 12;
            break;
        default:
            bytesConsumed = 0;
            dateTimeOffset = default(DateTimeOffset);
            return false;
        }
        uint num11 = (uint)(source[12] - 48);
        uint num12 = (uint)(source[13] - 48);
        uint num13 = (uint)(source[14] - 48);
        uint num14 = (uint)(source[15] - 48);
        if (num11 > 9 || num12 > 9 || num13 > 9 || num14 > 9)
        {
            bytesConsumed = 0;
            dateTimeOffset = default(DateTimeOffset);
            return false;
        }
        int year = (int)(num11 * 1000 + num12 * 100 + num13 * 10 + num14);
        if (source[16] != 32)
        {
            bytesConsumed = 0;
            dateTimeOffset = default(DateTimeOffset);
            return false;
        }
        uint num15 = (uint)(source[17] - 48);
        uint num16 = (uint)(source[18] - 48);
        if (num15 > 9 || num16 > 9)
        {
            bytesConsumed = 0;
            dateTimeOffset = default(DateTimeOffset);
            return false;
        }
        int hour = (int)(num15 * 10 + num16);
        if (source[19] != 58)
        {
            bytesConsumed = 0;
            dateTimeOffset = default(DateTimeOffset);
            return false;
        }
        uint num17 = (uint)(source[20] - 48);
        uint num18 = (uint)(source[21] - 48);
        if (num17 > 9 || num18 > 9)
        {
            bytesConsumed = 0;
            dateTimeOffset = default(DateTimeOffset);
            return false;
        }
        int minute = (int)(num17 * 10 + num18);
        if (source[22] != 58)
        {
            bytesConsumed = 0;
            dateTimeOffset = default(DateTimeOffset);
            return false;
        }
        uint num19 = (uint)(source[23] - 48);
        uint num20 = (uint)(source[24] - 48);
        if (num19 > 9 || num20 > 9)
        {
            bytesConsumed = 0;
            dateTimeOffset = default(DateTimeOffset);
            return false;
        }
        int second = (int)(num19 * 10 + num20);
        uint num21 = source[25];
        uint num22 = source[26] ^ caseFlipXorMask;
        uint num23 = source[27] ^ caseFlipXorMask;
        uint num24 = source[28] ^ caseFlipXorMask;
        uint num25 = (num21 << 24) | (num22 << 16) | (num23 << 8) | num24;
        if (num25 != 541543764)
        {
            bytesConsumed = 0;
            dateTimeOffset = default(DateTimeOffset);
            return false;
        }
        if (!TryCreateDateTimeOffset(year, month, day, hour, minute, second, 0, offsetNegative: false, 0, 0, out dateTimeOffset))
        {
            bytesConsumed = 0;
            dateTimeOffset = default(DateTimeOffset);
            return false;
        }
        if (dayOfWeek != dateTimeOffset.DayOfWeek)
        {
            bytesConsumed = 0;
            dateTimeOffset = default(DateTimeOffset);
            return false;
        }
        bytesConsumed = 29;
        return true;
    }
References System.source, System.Buffers.Text.Utf8Parser.TryCreateDateTimeOffset(), and System.year.
Referenced by System.Buffers.Text.Utf8Parser.TryParse(), and System.Buffers.Text.Utf8Parser.TryParse().