Terraria: System.Buffers.Text.Utf8Parser.TryParse
TryParse() [12/16]
static bool System.Buffers.Text.Utf8Parser.TryParse (ReadOnlySpan< byte > source, out short value, out int bytesConsumed, char standardFormat = '\0') inline static
Definition at line 1317 of file Utf8Parser.cs.
    {
        while (standardFormat != 0)
        {
            switch (standardFormat | 0x20)
            {
            case 100:
            case 103:
                break;
            case 110:
                return TryParseInt16N(source, out value, out bytesConsumed);
            case 120:
                Unsafe.SkipInit<short>(out value);
                return TryParseUInt16X(source, out Unsafe.As<short, ushort>(ref value), out bytesConsumed);
            default:
                return ParserHelpers.TryParseThrowFormatException<short>(source, out value, out bytesConsumed);
            }
            standardFormat = '\0';
        }
        return TryParseInt16D(source, out value, out bytesConsumed);
    }
References System.source, System.Buffers.Text.Utf8Parser.TryParseInt16D(), System.Buffers.Text.Utf8Parser.TryParseInt16N(), System.Buffers.Text.ParserHelpers.TryParseThrowFormatException(), System.Buffers.Text.Utf8Parser.TryParseUInt16X(), and System.value.