Terraria: System.Buffers.Text.Utf8Parser.TryParseDateTimeG
TryParseDateTimeG()
static bool System.Buffers.Text.Utf8Parser.TryParseDateTimeG (ReadOnlySpan< byte > source, out DateTime value, out DateTimeOffset valueAsOffset, out int bytesConsumed) inline static private
Definition at line 339 of file Utf8Parser.cs.
    {
        if (source.Length < 19)
        {
            bytesConsumed = 0;
            value = default(DateTime);
            valueAsOffset = default(DateTimeOffset);
            return false;
        }
        uint num = (uint)(source[0] - 48);
        uint num2 = (uint)(source[1] - 48);
        if (num > 9 || num2 > 9)
        {
            bytesConsumed = 0;
            value = default(DateTime);
            valueAsOffset = default(DateTimeOffset);
            return false;
        }
        int month = (int)(num * 10 + num2);
        if (source[2] != 47)
        {
            bytesConsumed = 0;
            value = default(DateTime);
            valueAsOffset = default(DateTimeOffset);
            return false;
        }
        uint num3 = (uint)(source[3] - 48);
        uint num4 = (uint)(source[4] - 48);
        if (num3 > 9 || num4 > 9)
        {
            bytesConsumed = 0;
            value = default(DateTime);
            valueAsOffset = default(DateTimeOffset);
            return false;
        }
        int day = (int)(num3 * 10 + num4);
        if (source[5] != 47)
        {
            bytesConsumed = 0;
            value = default(DateTime);
            valueAsOffset = default(DateTimeOffset);
            return false;
        }
        uint num5 = (uint)(source[6] - 48);
        uint num6 = (uint)(source[7] - 48);
        uint num7 = (uint)(source[8] - 48);
        uint num8 = (uint)(source[9] - 48);
        if (num5 > 9 || num6 > 9 || num7 > 9 || num8 > 9)
        {
            bytesConsumed = 0;
            value = default(DateTime);
            valueAsOffset = default(DateTimeOffset);
            return false;
        }
        int year = (int)(num5 * 1000 + num6 * 100 + num7 * 10 + num8);
        if (source[10] != 32)
        {
            bytesConsumed = 0;
            value = default(DateTime);
            valueAsOffset = default(DateTimeOffset);
            return false;
        }
        uint num9 = (uint)(source[11] - 48);
        uint num10 = (uint)(source[12] - 48);
        if (num9 > 9 || num10 > 9)
        {
            bytesConsumed = 0;
            value = default(DateTime);
            valueAsOffset = default(DateTimeOffset);
            return false;
        }
        int hour = (int)(num9 * 10 + num10);
        if (source[13] != 58)
        {
            bytesConsumed = 0;
            value = default(DateTime);
            valueAsOffset = default(DateTimeOffset);
            return false;
        }
        uint num11 = (uint)(source[14] - 48);
        uint num12 = (uint)(source[15] - 48);
        if (num11 > 9 || num12 > 9)
        {
            bytesConsumed = 0;
            value = default(DateTime);
            valueAsOffset = default(DateTimeOffset);
            return false;
        }
        int minute = (int)(num11 * 10 + num12);
        if (source[16] != 58)
        {
            bytesConsumed = 0;
            value = default(DateTime);
            valueAsOffset = default(DateTimeOffset);
            return false;
        }
        uint num13 = (uint)(source[17] - 48);
        uint num14 = (uint)(source[18] - 48);
        if (num13 > 9 || num14 > 9)
        {
            bytesConsumed = 0;
            value = default(DateTime);
            valueAsOffset = default(DateTimeOffset);
            return false;
        }
        int second = (int)(num13 * 10 + num14);
        if (!TryCreateDateTimeOffsetInterpretingDataAsLocalTime(year, month, day, hour, minute, second, 0, out valueAsOffset))
        {
            bytesConsumed = 0;
            value = default(DateTime);
            valueAsOffset = default(DateTimeOffset);
            return false;
        }
        bytesConsumed = 19;
        value = valueAsOffset.DateTime;
        return true;
    }
References System.source, System.Buffers.Text.Utf8Parser.TryCreateDateTimeOffsetInterpretingDataAsLocalTime(), System.value, and System.year.
Referenced by System.Buffers.Text.Utf8Parser.TryParse(), System.Buffers.Text.Utf8Parser.TryParse(), and System.Buffers.Text.Utf8Parser.TryParseDateTimeOffsetDefault().