Terraria: System.Buffers.Text.Utf8Parser.TryParseUInt64X
TryParseUInt64X()
static bool System.Buffers.Text.Utf8Parser.TryParseUInt64X (ReadOnlySpan< byte > source, out ulong value, out int bytesConsumed) inline static private
Definition at line 3323 of file Utf8Parser.cs.
    {
        if (source.Length < 1)
        {
            bytesConsumed = 0;
            value = 0uL;
            return false;
        }
        ReadOnlySpan<byte> charToHexLookup = HexConverter.CharToHexLookup;
        byte index = source[0];
        byte b = charToHexLookup[index];
        if (b == byte.MaxValue)
        {
            bytesConsumed = 0;
            value = 0uL;
            return false;
        }
        ulong num = b;
        if (source.Length <= 16)
        {
            for (int i = 1; i < source.Length; i++)
            {
                index = source[i];
                b = charToHexLookup[index];
                if (b == byte.MaxValue)
                {
                    bytesConsumed = i;
                    value = num;
                    return true;
                }
                num = (num << 4) + b;
            }
        }
        else
        {
            for (int j = 1; j < 16; j++)
            {
                index = source[j];
                b = charToHexLookup[index];
                if (b == byte.MaxValue)
                {
                    bytesConsumed = j;
                    value = num;
                    return true;
                }
                num = (num << 4) + b;
            }
            for (int k = 16; k < source.Length; k++)
            {
                index = source[k];
                b = charToHexLookup[index];
                if (b == byte.MaxValue)
                {
                    bytesConsumed = k;
                    value = num;
                    return true;
                }
                if (num > 1152921504606846975L)
                {
                    bytesConsumed = 0;
                    value = 0uL;
                    return false;
                }
                num = (num << 4) + b;
            }
        }
        bytesConsumed = source.Length;
        value = num;
        return true;
    }
References System.HexConverter.CharToHexLookup, System.index, System.L, System.source, and System.value.
Referenced by System.Buffers.Text.Utf8Parser.TryParse(), System.Buffers.Text.Utf8Parser.TryParse(), System.Buffers.Text.Utf8Parser.TryParseGuidCore(), and System.Buffers.Text.Utf8Parser.TryParseGuidN().