Terraria: System.Buffers.Text.Utf8Parser.TryParseGuidCore
TryParseGuidCore()
static bool System.Buffers.Text.Utf8Parser.TryParseGuidCore (ReadOnlySpan< byte > source, out Guid value, out int bytesConsumed, int ends) inline static private
Definition at line 1175 of file Utf8Parser.cs.
    {
        int num = 36 + ((ends != 0) ? 2 : 0);
        if (source.Length < num)
        {
            value = default(Guid);
            bytesConsumed = 0;
            return false;
        }
        if (ends != 0)
        {
            if (source[0] != (byte)ends)
            {
                value = default(Guid);
                bytesConsumed = 0;
                return false;
            }
            source = source.Slice(1);
            ends >>= 8;
        }
        if (!TryParseUInt32X(source, out var value2, out var bytesConsumed2))
        {
            value = default(Guid);
            bytesConsumed = 0;
            return false;
        }
        if (bytesConsumed2 != 8)
        {
            value = default(Guid);
            bytesConsumed = 0;
            return false;
        }
        if (source[bytesConsumed2] != 45)
        {
            value = default(Guid);
            bytesConsumed = 0;
            return false;
        }
        source = source.Slice(9);
        if (!TryParseUInt16X(source, out var value3, out bytesConsumed2))
        {
            value = default(Guid);
            bytesConsumed = 0;
            return false;
        }
        if (bytesConsumed2 != 4)
        {
            value = default(Guid);
            bytesConsumed = 0;
            return false;
        }
        if (source[bytesConsumed2] != 45)
        {
            value = default(Guid);
            bytesConsumed = 0;
            return false;
        }
        source = source.Slice(5);
        if (!TryParseUInt16X(source, out var value4, out bytesConsumed2))
        {
            value = default(Guid);
            bytesConsumed = 0;
            return false;
        }
        if (bytesConsumed2 != 4)
        {
            value = default(Guid);
            bytesConsumed = 0;
            return false;
        }
        if (source[bytesConsumed2] != 45)
        {
            value = default(Guid);
            bytesConsumed = 0;
            return false;
        }
        source = source.Slice(5);
        if (!TryParseUInt16X(source, out var value5, out bytesConsumed2))
        {
            value = default(Guid);
            bytesConsumed = 0;
            return false;
        }
        if (bytesConsumed2 != 4)
        {
            value = default(Guid);
            bytesConsumed = 0;
            return false;
        }
        if (source[bytesConsumed2] != 45)
        {
            value = default(Guid);
            bytesConsumed = 0;
            return false;
        }
        source = source.Slice(5);
        if (!TryParseUInt64X(source, out var value6, out bytesConsumed2))
        {
            value = default(Guid);
            bytesConsumed = 0;
            return false;
        }
        if (bytesConsumed2 != 12)
        {
            value = default(Guid);
            bytesConsumed = 0;
            return false;
        }
        if (ends != 0 && source[bytesConsumed2] != (byte)ends)
        {
            value = default(Guid);
            bytesConsumed = 0;
            return false;
        }
        bytesConsumed = num;
        value = new Guid((int)value2, (short)value3, (short)value4, (byte)(value5 >> 8), (byte)value5, (byte)(value6 >> 40), (byte)(value6 >> 32), (byte)(value6 >> 24), (byte)(value6 >> 16), (byte)(value6 >> 8), (byte)value6);
        return true;
    }
References System.source, System.Buffers.Text.Utf8Parser.TryParseUInt16X(), System.Buffers.Text.Utf8Parser.TryParseUInt32X(), System.Buffers.Text.Utf8Parser.TryParseUInt64X(), and System.value.
Referenced by System.Buffers.Text.Utf8Parser.TryParse().