Terraria: System.Buffers.Text.Utf8Parser.TryParse
TryParse() [5/16]
static unsafe bool System.Buffers.Text.Utf8Parser.TryParse (ReadOnlySpan< byte > source, out decimal value, out int bytesConsumed, char standardFormat = '\0') inline static
Definition at line 963 of file Utf8Parser.cs.
    {
        ParseNumberOptions options;
        switch (standardFormat)
        {
        case '\0':
        case 'E':
        case 'G':
        case 'e':
        case 'g':
            options = ParseNumberOptions.AllowExponent;
            break;
        case 'F':
        case 'f':
            options = (ParseNumberOptions)0;
            break;
        default:
            return ParserHelpers.TryParseThrowFormatException<decimal>(out value, out bytesConsumed);
        }
        byte* digits = stackalloc byte[31];
        Number.NumberBuffer number = new Number.NumberBuffer(Number.NumberBufferKind.Decimal, digits, 31);
        if (!TryParseNumber(source, ref number, out bytesConsumed, options, out var textUsedExponentNotation))
        {
            value = default(decimal);
            return false;
        }
        if (!textUsedExponentNotation && (standardFormat == 'E' || standardFormat == 'e'))
        {
            value = default(decimal);
            bytesConsumed = 0;
            return false;
        }
        value = default(decimal);
        if (!Number.TryNumberToDecimal(ref number, ref value))
        {
            value = default(decimal);
            bytesConsumed = 0;
            return false;
        }
        return true;
    }
References System.options, System.source, System.Number.TryNumberToDecimal(), System.Buffers.Text.Utf8Parser.TryParseNumber(), System.Buffers.Text.ParserHelpers.TryParseThrowFormatException(), and System.value.