Terraria: System.Buffers.Text.Utf8Parser.TryParseNumber
TryParseNumber()
static bool System.Buffers.Text.Utf8Parser.TryParseNumber (ReadOnlySpan< byte > source, ref Number::NumberBuffer number, out int bytesConsumed, ParseNumberOptions options, out bool textUsedExponentNotation) inline static private
Definition at line 3394 of file Utf8Parser.cs.
    {
        textUsedExponentNotation = false;
        if (source.Length == 0)
        {
            bytesConsumed = 0;
            return false;
        }
        Span<byte> digits = number.Digits;
        int i = 0;
        int num = 0;
        byte b = source[i];
        if (b != 43)
        {
            if (b != 45)
            {
                goto IL_0055;
            }
            number.IsNegative = true;
        }
        i++;
        if (i == source.Length)
        {
            bytesConsumed = 0;
            return false;
        }
        b = source[i];
        goto IL_0055;
        IL_02a0:
        if ((byte)(b - 48) > 9)
        {
            bytesConsumed = 0;
            return false;
        }
        if (!TryParseUInt32D(source.Slice(i), out var value, out var bytesConsumed2))
        {
            value = uint.MaxValue;
            for (i += 10; i != source.Length; i++)
            {
                b = source[i];
                int num2 = (byte)(b - 48);
                if (num2 > 9)
                {
                    break;
                }
            }
        }
        i += bytesConsumed2;
        bool flag;
        if (flag)
        {
            if (number.Scale < int.MinValue + value)
            {
                number.Scale = int.MinValue;
            }
            else
            {
                number.Scale -= (int)value;
            }
        }
        else if (number.Scale > 2147483647L - (long)value)
        {
            number.Scale = int.MaxValue;
        }
        else
        {
            number.Scale += (int)value;
        }
        digits[num] = 0;
        number.DigitsCount = num;
        bytesConsumed = i;
        return true;
        IL_0055:
        int num3 = i;
        int num4 = 0;
        int num5 = digits.Length - 1;
        for (; i != source.Length; i++)
        {
            b = source[i];
            if (b != 48)
            {
                break;
            }
        }
        if (i == source.Length)
        {
            bytesConsumed = i;
            return true;
        }
        int num6 = i;
        int num7 = 0;
        while (i != source.Length)
        {
            b = source[i];
            int num8 = (byte)(b - 48);
            if (num8 > 9)
            {
                break;
            }
            i++;
            num4++;
            if (num4 >= num5)
            {
                num7 |= num8;
            }
        }
        number.HasNonZeroTail = num7 != 0;
        int num9 = i - num3;
        int num10 = i - num6;
        int num11 = Math.Min(num10, num5);
        source.Slice(num6, num11).CopyTo(digits);
        num = num11;
        number.Scale = num10;
        if (i == source.Length)
        {
            digits[num] = 0;
            number.DigitsCount = num;
            bytesConsumed = i;
            return true;
        }
        int num12 = 0;
        if (b == 46)
        {
            i++;
            int num13 = i;
            while (i != source.Length)
            {
                b = source[i];
                int num14 = (byte)(b - 48);
                if (num14 > 9)
                {
                    break;
                }
                i++;
                num4++;
                if (num4 >= num5)
                {
                    num7 |= num14;
                }
            }
            number.HasNonZeroTail = num7 != 0;
            num12 = i - num13;
            int j = num13;
            if (num == 0)
            {
                for (; j < i && source[j] == 48; j++)
                {
                    number.Scale--;
                }
            }
            int num15 = Math.Min(i - j, num5 - num);
            source.Slice(j, num15).CopyTo(digits.Slice(num));
            num += num15;
            if (i == source.Length)
            {
                if (num9 == 0 && num12 == 0)
                {
                    bytesConsumed = 0;
                    return false;
                }
                digits[num] = 0;
                number.DigitsCount = num;
                bytesConsumed = i;
                return true;
            }
        }
        if (num9 == 0 && num12 == 0)
        {
            bytesConsumed = 0;
            return false;
        }
        if ((b & -33) != 69)
        {
            digits[num] = 0;
            number.DigitsCount = num;
            bytesConsumed = i;
            return true;
        }
        textUsedExponentNotation = true;
        i++;
        if ((options & ParseNumberOptions.AllowExponent) == 0)
        {
            bytesConsumed = 0;
            return false;
        }
        if (i == source.Length)
        {
            bytesConsumed = 0;
            return false;
        }
        flag = false;
        b = source[i];
        if (b != 43)
        {
            if (b != 45)
            {
                goto IL_02a0;
            }
            flag = true;
        }
        i++;
        if (i == source.Length)
        {
            bytesConsumed = 0;
            return false;
        }
        b = source[i];
        goto IL_02a0;
    }
References System.L, System.Math.Min(), System.options, System.Span< T >.Slice(), System.source, System.Buffers.Text.Utf8Parser.TryParseUInt32D(), and System.value.
Referenced by System.Buffers.Text.Utf8Parser.TryParse(), and System.Buffers.Text.Utf8Parser.TryParseNormalAsFloatingPoint().