Terraria: System.Buffers.Text.Utf8Parser.TryParseUInt32X
TryParseUInt32X()
static bool System.Buffers.Text.Utf8Parser.TryParseUInt32X (ReadOnlySpan< byte > source, out uint value, out int bytesConsumed) inline static private
Definition at line 3252 of file Utf8Parser.cs.
    {
        if (source.Length < 1)
        {
            bytesConsumed = 0;
            value = 0u;
            return false;
        }
        ReadOnlySpan<byte> charToHexLookup = HexConverter.CharToHexLookup;
        byte index = source[0];
        byte b = charToHexLookup[index];
        if (b == byte.MaxValue)
        {
            bytesConsumed = 0;
            value = 0u;
            return false;
        }
        uint num = b;
        if (source.Length <= 8)
        {
            for (int i = 1; i < source.Length; i++)
            {
                index = source[i];
                b = charToHexLookup[index];
                if (b == byte.MaxValue)
                {
                    bytesConsumed = i;
                    value = num;
                    return true;
                }
                num = (num << 4) + b;
            }
        }
        else
        {
            for (int j = 1; j < 8; j++)
            {
                index = source[j];
                b = charToHexLookup[index];
                if (b == byte.MaxValue)
                {
                    bytesConsumed = j;
                    value = num;
                    return true;
                }
                num = (num << 4) + b;
            }
            for (int k = 8; k < source.Length; k++)
            {
                index = source[k];
                b = charToHexLookup[index];
                if (b == byte.MaxValue)
                {
                    bytesConsumed = k;
                    value = num;
                    return true;
                }
                if (num > 268435455)
                {
                    bytesConsumed = 0;
                    value = 0u;
                    return false;
                }
                num = (num << 4) + b;
            }
        }
        bytesConsumed = source.Length;
        value = num;
        return true;
    }
References System.HexConverter.CharToHexLookup, System.index, System.source, and System.value.
Referenced by System.Buffers.Text.Utf8Parser.TryParse(), System.Buffers.Text.Utf8Parser.TryParse(), System.Buffers.Text.Utf8Parser.TryParseGuidCore(), and System.Buffers.Text.Utf8Parser.TryParseGuidN().