Terraria: System.Buffers.Text.Utf8Parser.TryParse
TryParse() [11/16]
static bool System.Buffers.Text.Utf8Parser.TryParse (ReadOnlySpan< byte > source, out sbyte value, out int bytesConsumed, char standardFormat = '\0') inline static
Definition at line 1295 of file Utf8Parser.cs.
    {
        while (standardFormat != 0)
        {
            switch (standardFormat | 0x20)
            {
            case 100:
            case 103:
                break;
            case 110:
                return TryParseSByteN(source, out value, out bytesConsumed);
            case 120:
                Unsafe.SkipInit<sbyte>(out value);
                return TryParseByteX(source, out Unsafe.As<sbyte, byte>(ref value), out bytesConsumed);
            default:
                return ParserHelpers.TryParseThrowFormatException<sbyte>(source, out value, out bytesConsumed);
            }
            standardFormat = '\0';
        }
        return TryParseSByteD(source, out value, out bytesConsumed);
    }
References System.source, System.Buffers.Text.Utf8Parser.TryParseByteX(), System.Buffers.Text.Utf8Parser.TryParseSByteD(), System.Buffers.Text.Utf8Parser.TryParseSByteN(), System.Buffers.Text.ParserHelpers.TryParseThrowFormatException(), and System.value.