Terraria: System.Buffers.Text.Utf8Parser.TryParse
TryParse() [15/16]
static bool System.Buffers.Text.Utf8Parser.TryParse (ReadOnlySpan< byte > source, out ulong value, out int bytesConsumed, char standardFormat = '\0') inline static
Definition at line 2336 of file Utf8Parser.cs.
    {
        while (standardFormat != 0)
        {
            switch (standardFormat | 0x20)
            {
            case 100:
            case 103:
                break;
            case 110:
                return TryParseUInt64N(source, out value, out bytesConsumed);
            case 120:
                return TryParseUInt64X(source, out value, out bytesConsumed);
            default:
                return ParserHelpers.TryParseThrowFormatException<ulong>(source, out value, out bytesConsumed);
            }
            standardFormat = '\0';
        }
        return TryParseUInt64D(source, out value, out bytesConsumed);
    }
References System.source, System.Buffers.Text.ParserHelpers.TryParseThrowFormatException(), System.Buffers.Text.Utf8Parser.TryParseUInt64D(), System.Buffers.Text.Utf8Parser.TryParseUInt64N(), System.Buffers.Text.Utf8Parser.TryParseUInt64X(), and System.value.