Terraria: System.Buffers.Text.Utf8Parser.TryParseUInt32D
TryParseUInt32D()
static bool System.Buffers.Text.Utf8Parser.TryParseUInt32D (ReadOnlySpan< byte > source, out uint value, out int bytesConsumed) inline static private
Definition at line 2527 of file Utf8Parser.cs.
    {
        int num;
        int num3;
        int num2;
        if (source.Length >= 1)
        {
            num = 0;
            num2 = source[num];
            num3 = 0;
            if (ParserHelpers.IsDigit(num2))
            {
                if (num2 != 48)
                {
                    goto IL_0056;
                }
                while (true)
                {
                    num++;
                    if ((uint)num >= (uint)source.Length)
                    {
                        break;
                    }
                    num2 = source[num];
                    if (num2 == 48)
                    {
                        continue;
                    }
                    goto IL_004b;
                }
                goto IL_023d;
            }
        }
        goto IL_0235;
        IL_004b:
        if (ParserHelpers.IsDigit(num2))
        {
            goto IL_0056;
        }
        goto IL_023d;
        IL_0056:
        num3 = num2 - 48;
        num++;
        if ((uint)num < (uint)source.Length)
        {
            num2 = source[num];
            if (ParserHelpers.IsDigit(num2))
            {
                num++;
                num3 = 10 * num3 + num2 - 48;
                if ((uint)num < (uint)source.Length)
                {
                    num2 = source[num];
                    if (ParserHelpers.IsDigit(num2))
                    {
                        num++;
                        num3 = 10 * num3 + num2 - 48;
                        if ((uint)num < (uint)source.Length)
{
                            num2 = source[num];
                            if (ParserHelpers.IsDigit(num2))
{
                                num++;
                                num3 = 10 * num3 + num2 - 48;
                                if ((uint)num < (uint)source.Length)
{
                                    num2 = source[num];
                                    if (ParserHelpers.IsDigit(num2))
{
                                        num++;
                                        num3 = 10 * num3 + num2 - 48;
                                        if ((uint)num < (uint)source.Length)
{
                                            num2 = source[num];
                                            if (ParserHelpers.IsDigit(num2))
{
                                                num++;
                                                num3 = 10 * num3 + num2 - 48;
                                                if ((uint)num < (uint)source.Length)
{
                                                    num2 = source[num];
                                                    if (ParserHelpers.IsDigit(num2))
{
                                                        num++;
                                                        num3 = 10 * num3 + num2 - 48;
                                                        if ((uint)num < (uint)source.Length)
{
                                                            num2 = source[num];
                                                            if (ParserHelpers.IsDigit(num2))
{
                                                                num++;
                                                                num3 = 10 * num3 + num2 - 48;
                                                                if ((uint)num < (uint)source.Length)
{
                                                                    num2 = source[num];
                                                                    if (ParserHelpers.IsDigit(num2))
{
                                                                        num++;
                                                                        num3 = 10 * num3 + num2 - 48;
                                                                        if ((uint)num < (uint)source.Length)
{
                                                                            num2 = source[num];
                                                                            if (ParserHelpers.IsDigit(num2))
{
                                                                                num++;
                                                                                if ((uint)num3 <= 429496729u && (num3 != 429496729 || num2 <= 53))
{
                                                                                    num3 = num3 * 10 + num2 - 48;
                                                                                    if ((uint)num >= (uint)source.Length || !ParserHelpers.IsDigit(source[num]))
{
                                                                                        goto IL_023d;
                                                                                    }
                                                                                }
                                                                                goto IL_0235;
                                                                            }
                                                                        }
                                                                    }
                                                                }
                                                            }
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
        goto IL_023d;
        IL_023d:
        bytesConsumed = num;
        value = (uint)num3;
        return true;
        IL_0235:
        bytesConsumed = 0;
        value = 0u;
        return false;
    }
References System.Buffers.Text.ParserHelpers.IsDigit(), System.source, and System.value.
Referenced by System.Buffers.Text.Utf8Parser.TimeSpanSplitter.ParseComponent(), System.Buffers.Text.Utf8Parser.TryParse(), System.Buffers.Text.Utf8Parser.TryParseNumber(), System.Buffers.Text.Utf8Parser.TryParseTimeSpanBigG(), and System.Buffers.Text.Utf8Parser.TimeSpanSplitter.TrySplitTimeSpan().