Terraria: System.Buffers.Text.Utf8Parser.TryParse
TryParse() [8/16]
static bool System.Buffers.Text.Utf8Parser.TryParse (ReadOnlySpan< byte > source, out Guid value, out int bytesConsumed, char standardFormat = '\0') inline static
Definition at line 1109 of file Utf8Parser.cs.
    {
        while (true)
        {
            switch (standardFormat)
            {
            case '\0':
                return TryParseGuidCore(source, out value, out bytesConsumed, 0);
            case 'D':
                break;
            case 'B':
                return TryParseGuidCore(source, out value, out bytesConsumed, 32123);
            case 'P':
                return TryParseGuidCore(source, out value, out bytesConsumed, 10536);
            case 'N':
                return TryParseGuidN(source, out value, out bytesConsumed);
            default:
                return ParserHelpers.TryParseThrowFormatException<Guid>(source, out value, out bytesConsumed);
            }
            standardFormat = '\0';
        }
    }
References System.source, System.Buffers.Text.Utf8Parser.TryParseGuidCore(), System.Buffers.Text.Utf8Parser.TryParseGuidN(), System.Buffers.Text.ParserHelpers.TryParseThrowFormatException(), and System.value.