Terraria: System.Buffers.Text.Utf8Parser.TryParse
TryParse() [16/16]
static bool System.Buffers.Text.Utf8Parser.TryParse (ReadOnlySpan< byte > source, out ushort value, out int bytesConsumed, char standardFormat = '\0') inline static
Definition at line 2292 of file Utf8Parser.cs.
    {
        while (standardFormat != 0)
        {
            switch (standardFormat | 0x20)
            {
            case 100:
            case 103:
                break;
            case 110:
                return TryParseUInt16N(source, out value, out bytesConsumed);
            case 120:
                return TryParseUInt16X(source, out value, out bytesConsumed);
            default:
                return ParserHelpers.TryParseThrowFormatException<ushort>(source, out value, out bytesConsumed);
            }
            standardFormat = '\0';
        }
        return TryParseUInt16D(source, out value, out bytesConsumed);
    }
References System.source, System.Buffers.Text.ParserHelpers.TryParseThrowFormatException(), System.Buffers.Text.Utf8Parser.TryParseUInt16D(), System.Buffers.Text.Utf8Parser.TryParseUInt16N(), System.Buffers.Text.Utf8Parser.TryParseUInt16X(), and System.value.