Terraria: System.Buffers.Text.Utf8Parser.TryParseDateTimeOffsetDefault
TryParseDateTimeOffsetDefault()
static bool System.Buffers.Text.Utf8Parser.TryParseDateTimeOffsetDefault (ReadOnlySpan< byte > source, out DateTimeOffset value, out int bytesConsumed) inline static private
Definition at line 278 of file Utf8Parser.cs.
    {
        if (source.Length < 26)
        {
            bytesConsumed = 0;
            value = default(DateTimeOffset);
            return false;
        }
        if (!TryParseDateTimeG(source, out var value2, out var _, out var _))
        {
            bytesConsumed = 0;
            value = default(DateTimeOffset);
            return false;
        }
        if (source[19] != 32)
        {
            bytesConsumed = 0;
            value = default(DateTimeOffset);
            return false;
        }
        byte b = source[20];
        if (b != 43 && b != 45)
        {
            bytesConsumed = 0;
            value = default(DateTimeOffset);
            return false;
        }
        uint num = (uint)(source[21] - 48);
        uint num2 = (uint)(source[22] - 48);
        if (num > 9 || num2 > 9)
        {
            bytesConsumed = 0;
            value = default(DateTimeOffset);
            return false;
        }
        int offsetHours = (int)(num * 10 + num2);
        if (source[23] != 58)
        {
            bytesConsumed = 0;
            value = default(DateTimeOffset);
            return false;
        }
        uint num3 = (uint)(source[24] - 48);
        uint num4 = (uint)(source[25] - 48);
        if (num3 > 9 || num4 > 9)
        {
            bytesConsumed = 0;
            value = default(DateTimeOffset);
            return false;
        }
        int offsetMinutes = (int)(num3 * 10 + num4);
        if (!TryCreateDateTimeOffset(value2, b == 45, offsetHours, offsetMinutes, out value))
        {
            bytesConsumed = 0;
            value = default(DateTimeOffset);
            return false;
        }
        bytesConsumed = 26;
        return true;
    }
References System.source, System.Buffers.Text.Utf8Parser.TryCreateDateTimeOffset(), System.Buffers.Text.Utf8Parser.TryParseDateTimeG(), and System.value.
Referenced by System.Buffers.Text.Utf8Parser.TryParse().