Terraria: System.Buffers.Text.Utf8Parser.TryCreateDateTimeOffset
TryCreateDateTimeOffset() [1/2]
static bool System.Buffers.Text.Utf8Parser.TryCreateDateTimeOffset (DateTime dateTime, bool offsetNegative, int offsetHours, int offsetMinutes, out DateTimeOffset value) inline static private
Definition at line 457 of file Utf8Parser.cs.
    {
        if ((uint)offsetHours > 14u)
        {
            value = default(DateTimeOffset);
            return false;
        }
        if ((uint)offsetMinutes > 59u)
        {
            value = default(DateTimeOffset);
            return false;
        }
        if (offsetHours == 14 && offsetMinutes != 0)
        {
            value = default(DateTimeOffset);
            return false;
        }
        long num = ((long)offsetHours * 3600L + (long)offsetMinutes * 60L) * 10000000;
        if (offsetNegative)
        {
            num = -num;
        }
        try
        {
            value = new DateTimeOffset(dateTime.Ticks, new TimeSpan(num));
        }
        catch (ArgumentOutOfRangeException)
        {
            value = default(DateTimeOffset);
            return false;
        }
        return true;
    }
References System.L, System.DateTime.Ticks, and System.value.
Referenced by System.Buffers.Text.Utf8Parser.TryCreateDateTimeOffset(), System.Buffers.Text.Utf8Parser.TryParseDateTimeOffsetDefault(), System.Buffers.Text.Utf8Parser.TryParseDateTimeOffsetO(), and System.Buffers.Text.Utf8Parser.TryParseDateTimeOffsetR().