Terraria: System.Xml.Xsl.Xslt.OutputScopeManager.PushScope
PushScope()
void System.Xml.Xsl.Xslt.OutputScopeManager.PushScope () inline
Definition at line 32 of file OutputScopeManager.cs.
    {
        _lastScopes++;
    }
References System.Xml.Xsl.Xslt.OutputScopeManager._lastScopes.
Referenced by System.Xml.Xsl.Xslt.QilGenerator.CompileCopy(), System.Xml.Xsl.Xslt.QilGenerator.CompileElement(), System.Xml.Xsl.Xslt.QilGenerator.CompileLiteralElement(), System.Xml.Xsl.Xslt.QilGenerator.CompileVarParValue(), and System.Xml.Xsl.Xslt.OutputScopeManager.Reset().