Terraria: System.Xml.Xsl.Xslt.OutputScopeManager.InvalidateNonDefaultPrefixes
InvalidateNonDefaultPrefixes()
void System.Xml.Xsl.Xslt.OutputScopeManager.InvalidateNonDefaultPrefixes () inline
Definition at line 79 of file OutputScopeManager.cs.
    {
        string text = LookupNamespace(string.Empty);
        if (text == null)
        {
            InvalidateAllPrefixes();
        }
        else if (_records[_lastRecord].prefix.Length != 0 || _records[_lastRecord - 1].prefix != null)
        {
            AddRecord(null, null);
            AddRecord(string.Empty, text);
        }
    }
References System.Xml.Xsl.Xslt.OutputScopeManager._lastRecord, System.Xml.Xsl.Xslt.OutputScopeManager._records, System.Xml.Xsl.Xslt.OutputScopeManager.AddRecord(), System.Xml.Xsl.Xslt.OutputScopeManager.InvalidateAllPrefixes(), System.Xml.Xsl.Xslt.OutputScopeManager.LookupNamespace(), System.prefix, System.Xml.Xsl.Xslt.OutputScopeManager.ScopeReord.prefix, and System.text.
Referenced by System.Xml.Xsl.Xslt.QilGenerator.CompileAttribute().