Terraria: System.Buffers.Text.Utf8Parser.TryParseTimeSpanBigG
TryParseTimeSpanBigG()
static bool System.Buffers.Text.Utf8Parser.TryParseTimeSpanBigG (ReadOnlySpan< byte > source, out TimeSpan value, out int bytesConsumed) inline static private
Definition at line 3604 of file Utf8Parser.cs.
    {
        int i = 0;
        byte b = 0;
        for (; i != source.Length; i++)
        {
            b = source[i];
            if (b != 32 && b != 9)
            {
                break;
            }
        }
        if (i == source.Length)
        {
            value = default(TimeSpan);
            bytesConsumed = 0;
            return false;
        }
        bool isNegative = false;
        if (b == 45)
        {
            isNegative = true;
            i++;
            if (i == source.Length)
            {
                value = default(TimeSpan);
                bytesConsumed = 0;
                return false;
            }
        }
        if (!TryParseUInt32D(source.Slice(i), out var value2, out var bytesConsumed2))
        {
            value = default(TimeSpan);
            bytesConsumed = 0;
            return false;
        }
        i += bytesConsumed2;
        if (i == source.Length || source[i++] != 58)
        {
            value = default(TimeSpan);
            bytesConsumed = 0;
            return false;
        }
        if (!TryParseUInt32D(source.Slice(i), out var value3, out bytesConsumed2))
        {
            value = default(TimeSpan);
            bytesConsumed = 0;
            return false;
        }
        i += bytesConsumed2;
        if (i == source.Length || source[i++] != 58)
        {
            value = default(TimeSpan);
            bytesConsumed = 0;
            return false;
        }
        if (!TryParseUInt32D(source.Slice(i), out var value4, out bytesConsumed2))
        {
            value = default(TimeSpan);
            bytesConsumed = 0;
            return false;
        }
        i += bytesConsumed2;
        if (i == source.Length || source[i++] != 58)
        {
            value = default(TimeSpan);
            bytesConsumed = 0;
            return false;
        }
        if (!TryParseUInt32D(source.Slice(i), out var value5, out bytesConsumed2))
        {
            value = default(TimeSpan);
            bytesConsumed = 0;
            return false;
        }
        i += bytesConsumed2;
        if (i == source.Length || source[i++] != 46)
        {
            value = default(TimeSpan);
            bytesConsumed = 0;
            return false;
        }
        if (!TryParseTimeSpanFraction(source.Slice(i), out var value6, out bytesConsumed2))
        {
            value = default(TimeSpan);
            bytesConsumed = 0;
            return false;
        }
        i += bytesConsumed2;
        if (!TryCreateTimeSpan(isNegative, value2, value3, value4, value5, value6, out value))
        {
            value = default(TimeSpan);
            bytesConsumed = 0;
            return false;
        }
        if (i != source.Length && (source[i] == 46 || source[i] == 58))
        {
            value = default(TimeSpan);
            bytesConsumed = 0;
            return false;
        }
        bytesConsumed = i;
        return true;
    }
References System.source, System.Buffers.Text.Utf8Parser.TryCreateTimeSpan(), System.Buffers.Text.Utf8Parser.TryParseTimeSpanFraction(), System.Buffers.Text.Utf8Parser.TryParseUInt32D(), and System.value.
Referenced by System.Buffers.Text.Utf8Parser.TryParse().