Terraria: System.Xml.Ref.Equal
Equal()
static bool System.Xml.Ref.Equal (string strA, string strB) inline static
Definition at line 5 of file Ref.cs.
    {
        return (object)strA == strB;
    }
References System.Xml.Dictionary.
Referenced by System.Xml.XmlTextReaderImpl.AddAttribute(), System.Xml.XmlTextReaderImpl.AddDefaultAttributeInternal(), System.Xml.XmlNamespaceManager.AddNamespace(), System.Xml.XmlTextReaderImpl.AddNamespace(), System.Xml.Schema.BaseProcessor.AddToTable(), System.Xml.Xsl.XsltOld.RecordBuilder.AnalyzeSpaceLang(), System.Xml.XmlTextReaderImpl.AttributeDuplCheck(), System.Xml.Xsl.XsltOld.RecordBuilder.BeginNamespace(), System.Xml.Schema.XmlSchemaValidator.CheckIsXmlAttribute(), System.Xml.XmlTextReaderImpl.NodeData.CompareTo(), System.Xml.Xsl.XsltOld.ApplyTemplatesAction.CompileAttribute(), System.Xml.Xsl.XsltOld.AttributeAction.CompileAttribute(), System.Xml.Xsl.XsltOld.AttributeSetAction.CompileAttribute(), System.Xml.Xsl.XsltOld.CallTemplateAction.CompileAttribute(), System.Xml.Xsl.XsltOld.CopyAction.CompileAttribute(), System.Xml.Xsl.XsltOld.CopyOfAction.CompileAttribute(), System.Xml.Xsl.XsltOld.ElementAction.CompileAttribute(), System.Xml.Xsl.XsltOld.ForEachAction.CompileAttribute(), System.Xml.Xsl.XsltOld.IfAction.CompileAttribute(), System.Xml.Xsl.XsltOld.MessageAction.CompileAttribute(), System.Xml.Xsl.XsltOld.NumberAction.CompileAttribute(), System.Xml.Xsl.XsltOld.ProcessingInstructionAction.CompileAttribute(), System.Xml.Xsl.XsltOld.SortAction.CompileAttribute(), System.Xml.Xsl.XsltOld.TemplateAction.CompileAttribute(), System.Xml.Xsl.XsltOld.TextAction.CompileAttribute(), System.Xml.Xsl.XsltOld.ValueOfAction.CompileAttribute(), System.Xml.Xsl.XsltOld.VariableAction.CompileAttribute(), System.Xml.Xsl.XsltOld.XsltOutput.CompileAttribute(), System.Xml.Xsl.XsltOld.ChooseAction.CompileConditions(), System.Xml.Xsl.XsltOld.ApplyTemplatesAction.CompileContent(), System.Xml.Xsl.XsltOld.AttributeSetAction.CompileContent(), System.Xml.Xsl.XsltOld.CallTemplateAction.CompileContent(), System.Xml.Xsl.XsltOld.ContainerAction.CompileDecimalFormat(), System.Xml.Xsl.XsltOld.ContainerAction.CompileDocument(), System.Xml.Xsl.XsltOld.ContainerAction.CompileInstruction(), System.Xml.Xsl.XsltOld.ContainerAction.CompileKey(), System.Xml.Xsl.XsltOld.ContainerAction.CompileLiteralAttributesAndNamespaces(), System.Xml.Xsl.XsltOld.ContainerAction.CompileNamespaceAlias(), System.Xml.Xsl.XsltOld.ContainerAction.CompileOnceTemplate(), System.Xml.Xsl.XsltOld.TemplateAction.CompileParameters(), System.Xml.Xsl.XsltOld.NewInstructionAction.CompileSelectiveTemplate(), System.Xml.Xsl.XsltOld.ContainerAction.CompileSingleTemplate(), System.Xml.Xsl.XsltOld.ForEachAction.CompileSortElements(), System.Xml.Xsl.XsltOld.ContainerAction.CompileStylesheetAttributes(), System.Xml.Xsl.XsltOld.ContainerAction.CompileTopLevelElements(), System.Xml.Schema.AutoValidator.DetectValidationType(), System.Xml.XmlLoader.ExpandEntityReference(), System.Xml.Xsl.XsltOld.RecordBuilder.FindAttribute(), System.Xml.Xsl.XsltOld.OutputScopeManager.FindPrefix(), System.Xml.Xsl.XsltOld.OutputScope.FindPrefix(), System.Xml.Xsl.XsltOld.RecordBuilder.FixupAttributes(), System.Xml.Xsl.XsltOld.RecordBuilder.FixupElement(), System.Xml.XmlTextReaderImpl.GetAttribute(), System.Xml.XsdCachingReader.GetAttribute(), System.Xml.XsdCachingReader.GetAttributeIndexWithoutPrefix(), System.Xml.XsdCachingReader.GetAttributeIndexWithPrefix(), System.Xml.XsdValidatingReader.GetAttributePSVI(), System.Xml.Xsl.Xslt.XsltInput.GetAttributes(), System.Xml.XsdValidatingReader.GetDefaultAttribute(), System.Xml.Schema.XmlSchemaValidator.GetDefaultAttributePrefix(), System.Xml.XmlTextReaderImpl.GetIndexOfAttributeWithoutPrefix(), System.Xml.XmlTextReaderImpl.GetIndexOfAttributeWithPrefix(), System.Xml.Xsl.Xslt.XsltInput.GetLiteralAttributes(), System.Xml.XmlNode.GetNamespaceOfPrefixStrict(), System.Xml.DocumentSchemaValidator.GetNamespacesInScope(), System.Xml.XmlNode.GetPrefixOfNamespaceStrict(), System.Xml.Xsl.XsltOld.Compiler.GetSingleAttribute(), System.Xml.Xsl.Xslt.XsltInput.IsKeyword(), System.Xml.XmlElementList.IsMatch(), System.Xml.Xsl.Xslt.XsltInput.IsNs(), System.Xml.Xsl.Runtime.XsltLibrary.IsSameNodeSort(), System.Xml.Schema.XdrBuilder.IsSkipableAttribute(), System.Xml.Schema.XdrBuilder.IsSkipableElement(), System.Xml.Schema.SchemaNames.IsXDRRoot(), System.Xml.Schema.SchemaNames.IsXSDRoot(), System.Xml.Schema.XsdValidator.IsXSDRoot(), System.Xml.XsdValidatingReader.IsXSDRoot(), System.Xml.Schema.Parser.LoadElementNode(), System.Xml.Xsl.Xslt.XsltLoader.LoadInstructions(), System.Xml.DocumentXPathNodeIterator_ElemChildren.Match(), System.Xml.DocumentXPathNodeIterator_ElemChildren_NoLocalName.Match(), System.Xml.Xsl.Xslt.XsltLoader.MergeNamespaces(), System.Xml.XmlTextReaderImpl.MoveToAttribute(), System.Xml.XsdCachingReader.MoveToAttribute(), System.Xml.DocumentXPathNavigator.MoveToFirstNamespace(), System.Xml.DocumentXPathNavigator.MoveToNextNamespace(), System.Xml.XmlTextReaderImpl.ParseAttributes(), System.Xml.XmlTextReaderImpl.ParseAttributesAsync(), System.Xml.Schema.Parser.ParseReaderNode(), System.Xml.Schema.Preprocessor.PreprocessAttributeContent(), System.Xml.XsdValidatingReader.ProcessElementEvent(), System.Xml.XsdValidatingReader.ProcessElementEventAsync(), System.Xml.XmlSubtreeReader.ProcessNamespaces(), System.Xml.Schema.XsdValidator.ProcessXsiAttributes(), System.Xml.Xsl.Xslt.XsltInput.ReadAttribute(), System.Xml.XmlReader.ReadToDescendant(), System.Xml.XmlReader.ReadToDescendant(), System.Xml.XmlReader.ReadToFollowing(), System.Xml.XmlReader.ReadToFollowing(), System.Xml.XmlReader.ReadToNextSibling(), System.Xml.XmlReader.ReadToNextSibling(), System.Xml.XmlSubtreeReader.RemoveNamespace(), System.Xml.Xsl.XsltOld.DocumentScope.ResolveAtom(), System.Xml.Xsl.XsltOld.OutputScopeManager.ResolveNamespace(), System.Xml.XmlSqlBinaryReader.ScanAttributes(), System.Xml.Schema.XdrValidator.ThoroughGetElementDecl(), System.Xml.Schema.XmlSchemaValidator.ValidateAttribute(), System.Xml.DocumentSchemaValidator.ValidateAttributes(), System.Xml.DocumentSchemaValidator.ValidateElement(), System.Xml.DocumentSchemaValidator.ValidateSingleElement(), System.Xml.Schema.XmlSchemaDatatype.XdrCanonizeUri(), System.Xml.Xsl.Xslt.XsltLoader.XslChoose(), and System.Xml.Xsl.Xslt.XsltLoader.XslVarPar().