Terraria: System.Transactions.TransactionStateActive.EnlistVolatile
EnlistVolatile() [1/2]
override Enlistment System.Transactions.TransactionStateActive.EnlistVolatile (InternalTransaction tx, IEnlistmentNotification enlistmentNotification, EnlistmentOptions enlistmentOptions, Transaction atomicTransaction) inline package virtual
Reimplemented from System.Transactions.TransactionState.
Reimplemented in System.Transactions.TransactionStateSubordinateActive.
Definition at line 27 of file TransactionStateActive.cs.
    {
        Enlistment enlistment = new Enlistment(tx, enlistmentNotification, null, atomicTransaction, enlistmentOptions);
        if ((enlistmentOptions & EnlistmentOptions.EnlistDuringPrepareRequired) != 0)
        {
            AddVolatileEnlistment(ref tx._phase0Volatiles, enlistment);
        }
        else
        {
            AddVolatileEnlistment(ref tx._phase1Volatiles, enlistment);
        }
        TransactionsEtwProvider log = TransactionsEtwProvider.Log;
        if (log.IsEnabled())
        {
            log.TransactionstateEnlist(enlistment.InternalEnlistment.EnlistmentTraceId, EnlistmentType.Volatile, enlistmentOptions);
        }
        return enlistment;
    }
References System.Transactions.InternalTransaction._phase0Volatiles, System.Transactions.InternalTransaction._phase1Volatiles, System.Transactions.TransactionState.AddVolatileEnlistment(), System.Transactions.InternalEnlistment.EnlistmentTraceId, System.Transactions.Enlistment.InternalEnlistment, System.Diagnostics.Tracing.EventSource.IsEnabled(), System.Transactions.TransactionsEtwProvider.Log, and System.Transactions.TransactionsEtwProvider.TransactionstateEnlist().