Terraria: System.Diagnostics.Tracing.EventCounter.WritePayload
WritePayload()
override void System.Diagnostics.Tracing.EventCounter.WritePayload (float intervalSec, int pollingIntervalMillisec) inline package
Definition at line 75 of file EventCounter.cs.
    {
        lock (this)
        {
            Flush();
            CounterPayload counterPayload = new CounterPayload();
            counterPayload.Count = _count;
            counterPayload.IntervalSec = intervalSec;
            if (0 < _count)
            {
                counterPayload.Mean = _sum / (double)_count;
                counterPayload.StandardDeviation = Math.Sqrt(_sumSquared / (double)_count - _sum * _sum / (double)_count / (double)_count);
            }
            else
            {
                counterPayload.Mean = 0.0;
                counterPayload.StandardDeviation = 0.0;
            }
            counterPayload.Min = _min;
            counterPayload.Max = _max;
            counterPayload.Series = $"Interval={pollingIntervalMillisec}";
            counterPayload.CounterType = "Mean";
            counterPayload.Metadata = GetMetadataString();
            counterPayload.DisplayName = base.DisplayName ?? "";
            counterPayload.DisplayUnits = base.DisplayUnits ?? "";
            counterPayload.Name = base.Name;
            ResetStatistics();
            base.EventSource.Write("EventCounters", new EventSourceOptions
            {
                Level = EventLevel.LogAlways
            }, new CounterPayloadType(counterPayload));
        }
    }
References System.Diagnostics.Tracing.EventCounter._count, System.Diagnostics.Tracing.EventCounter._max, System.Diagnostics.Tracing.EventCounter._min, System.Diagnostics.Tracing.EventCounter._sum, System.Diagnostics.Tracing.EventCounter._sumSquared, System.Diagnostics.Tracing.EventCounter.Flush(), System.Diagnostics.Tracing.DiagnosticCounter.GetMetadataString(), System.Diagnostics.Tracing.EventCounter.ResetStatistics(), and System.Math.Sqrt().