Terraria: System.Diagnostics.Tracing.EventCounter.Flush
Flush()
void System.Diagnostics.Tracing.EventCounter.Flush () inline protected
Definition at line 142 of file EventCounter.cs.
    {
        for (int i = 0; i < _bufferedValues.Length; i++)
        {
            double num = Interlocked.Exchange(ref _bufferedValues[i], double.NegativeInfinity);
            if (num != double.NegativeInfinity)
            {
                OnMetricWritten(num);
            }
        }
        _bufferedValuesIndex = 0;
    }
References System.Diagnostics.Tracing.EventCounter._bufferedValues, System.Diagnostics.Tracing.EventCounter._bufferedValuesIndex, System.Threading.Interlocked.Exchange(), and System.Diagnostics.Tracing.EventCounter.OnMetricWritten().
Referenced by System.Diagnostics.Tracing.EventCounter.Enqueue(), and System.Diagnostics.Tracing.EventCounter.WritePayload().