Terraria: System.Text.RegularExpressions.RegexCharClass.MayOverlap
MayOverlap()
static bool System.Text.RegularExpressions.RegexCharClass.MayOverlap (string set1, string set2) inline static
Definition at line 721 of file RegexCharClass.cs.
    {
        if (set1 == set2)
        {
            return true;
        }
        if (set1 == "\0\u0001\0\0" || set2 == "\0\u0001\0\0")
        {
            return true;
        }
        bool flag = IsNegated(set1);
        bool flag2 = IsNegated(set2);
        if (flag != flag2)
        {
            return !set1.AsSpan(1).SequenceEqual(set2.AsSpan(1));
        }
        if (flag)
        {
            return true;
        }
        if (KnownDistinctSets(set1, set2) || KnownDistinctSets(set2, set1))
        {
            return false;
        }
        if (CanEasilyEnumerateSetContents(set2))
        {
            return MayOverlapByEnumeration(set1, set2);
        }
        if (CanEasilyEnumerateSetContents(set1))
        {
            return MayOverlapByEnumeration(set2, set1);
        }
        return true;
        static bool KnownDistinctSets(string set1, string set2)
        {
            if (set1 == "\0\0\u0001d" || set1 == "\0\u0004\0\t\u000e !")
            {
                switch (set2)
                {
                default:
                    return set2 == "\0\n\00:A[_`a{İı";
                case "\0\0\u0001\t":
                case "\0\0\n\0\u0002\u0004\u0005\u0003\u0001\u0006\t\u0013\0":
                case "\0\u0002\00:":
                    return true;
                }
            }
            return false;
        }
        static bool MayOverlapByEnumeration(string set1, string set2)
        {
            for (int i = 3; i < 3 + set2[1]; i += 2)
            {
                int num = set2[i + 1];
                for (int j = set2[i]; j < num; j++)
                {
                    if (CharInClass((char)j, set1))
                    {
                        return true;
                    }
                }
            }
            return false;
        }
    }
References System.Text.RegularExpressions.RegexCharClass.CanEasilyEnumerateSetContents(), System.Text.RegularExpressions.RegexCharClass.CharInClass(), System.Text.RegularExpressions.i, and System.Text.RegularExpressions.RegexCharClass.IsNegated().
Referenced by System.Text.RegularExpressions.RegexNode.CanBeMadeAtomic().