Terraria: System.IO.Compression.WrappedStream.ThrowIfCantRead
ThrowIfCantRead()
void System.IO.Compression.WrappedStream.ThrowIfCantRead () inline private
Definition at line 105 of file WrappedStream.cs.
    {
        if (!CanRead)
        {
            throw new NotSupportedException(System.SR.ReadingNotSupported);
        }
    }
References System.IO.Compression.WrappedStream.CanRead, and System.SR.ReadingNotSupported.
Referenced by System.IO.Compression.WrappedStream.Read(), System.IO.Compression.WrappedStream.Read(), System.IO.Compression.WrappedStream.ReadAsync(), System.IO.Compression.WrappedStream.ReadAsync(), and System.IO.Compression.WrappedStream.ReadByte().