Terraria: System.IO.Compression.WrappedStream.Seek
Seek()
override long System.IO.Compression.WrappedStream.Seek (long offset, SeekOrigin origin) inline
Definition at line 164 of file WrappedStream.cs.
    {
        ThrowIfDisposed();
        ThrowIfCantSeek();
        return _baseStream.Seek(offset, origin);
    }
References System.IO.Compression.WrappedStream._baseStream, System.offset, System.IO.Stream.Seek(), System.IO.Compression.WrappedStream.ThrowIfCantSeek(), and System.IO.Compression.WrappedStream.ThrowIfDisposed().