Terraria: System.Text.RegularExpressions.RegexCharClass.ToStringClass
ToStringClass() [2/2]
void System.Text.RegularExpressions.RegexCharClass.ToStringClass (ref System::Text::ValueStringBuilder vsb) inline private
Definition at line 1073 of file RegexCharClass.cs.
    {
        Canonicalize();
        int length = vsb.Length;
        int num = _categories?.Length ?? 0;
        Span<char> span = vsb.AppendSpan(3);
        span[0] = (char)(_negate ? 1u : 0u);
        span[1] = '\0';
        span[2] = (char)num;
        List<SingleRange> rangelist = _rangelist;
        if (rangelist != null)
        {
            for (int i = 0; i < rangelist.Count; i++)
            {
                SingleRange singleRange = rangelist[i];
                vsb.Append(singleRange.First);
                if (singleRange.Last != '\uffff')
                {
                    vsb.Append((char)(singleRange.Last + 1));
                }
            }
        }
        vsb[length + 1] = (char)(vsb.Length - length - 3);
        if (num != 0)
        {
            StringBuilder.ChunkEnumerator enumerator = _categories.GetChunks().GetEnumerator();
            while (enumerator.MoveNext())
            {
                vsb.Append(enumerator.Current.Span);
            }
        }
        _subtractor?.ToStringClass(ref vsb);
    }
References System.Text.RegularExpressions.RegexCharClass._categories, System.Text.RegularExpressions.RegexCharClass._negate, System.Text.RegularExpressions.RegexCharClass._rangelist, System.Text.RegularExpressions.RegexCharClass._subtractor, System.Text.RegularExpressions.RegexCharClass.Canonicalize(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Text.StringBuilder.GetChunks(), System.Text.StringBuilder.ChunkEnumerator.GetEnumerator(), System.Text.RegularExpressions.i, System.Text.StringBuilder.Length, System.Text.RegularExpressions.length, and System.Text.RegularExpressions.RegexCharClass.ToStringClass().