Terraria: System.IO.Compression.WrappedStream.SetLength
SetLength()
override void System.IO.Compression.WrappedStream.SetLength (long value) inline
Definition at line 171 of file WrappedStream.cs.
    {
        ThrowIfDisposed();
        ThrowIfCantSeek();
        ThrowIfCantWrite();
        _baseStream.SetLength(value);
    }
References System.IO.Compression.WrappedStream._baseStream, System.IO.Stream.SetLength(), System.IO.Compression.WrappedStream.ThrowIfCantSeek(), System.IO.Compression.WrappedStream.ThrowIfCantWrite(), System.IO.Compression.WrappedStream.ThrowIfDisposed(), and System.value.