Terraria: System.Text.RegularExpressions.RegexCharClass.AddSet
AddSet()
void System.Text.RegularExpressions.RegexCharClass.AddSet (ReadOnlySpan< char > set) inline private
Definition at line 388 of file RegexCharClass.cs.
    {
        if (set.Length != 0)
        {
            List<SingleRange> list = EnsureRangeList();
            int i;
            for (i = 0; i < set.Length - 1; i += 2)
            {
                list.Add(new SingleRange(set[i], (char)(set[i + 1] - 1)));
            }
            if (i < set.Length)
            {
                list.Add(new SingleRange(set[i], '\uffff'));
            }
        }
    }
References System.Text.RegularExpressions.RegexCharClass.EnsureRangeList(), System.Text.RegularExpressions.i, and System.list.
Referenced by System.Text.RegularExpressions.RegexCharClass.AddCategoryFromName(), System.Text.RegularExpressions.RegexCharClass.AddDigit(), System.Text.RegularExpressions.RegexCharClass.AddSpace(), and System.Text.RegularExpressions.RegexCharClass.AddWord().