Terraria: System.IO.Compression.WrappedStream.ThrowIfDisposed
ThrowIfDisposed()
void System.IO.Compression.WrappedStream.ThrowIfDisposed () inline private
Definition at line 97 of file WrappedStream.cs.
    {
        if (_isDisposed)
        {
            throw new ObjectDisposedException(GetType().ToString(), System.SR.HiddenStreamName);
        }
    }
References System.IO.Compression.WrappedStream._isDisposed, System.SR.HiddenStreamName, and System.ToString.
Referenced by System.IO.Compression.WrappedStream.Flush(), System.IO.Compression.WrappedStream.FlushAsync(), System.IO.Compression.WrappedStream.Read(), System.IO.Compression.WrappedStream.Read(), System.IO.Compression.WrappedStream.ReadAsync(), System.IO.Compression.WrappedStream.ReadAsync(), System.IO.Compression.WrappedStream.ReadByte(), System.IO.Compression.WrappedStream.Seek(), System.IO.Compression.WrappedStream.SetLength(), System.IO.Compression.WrappedStream.Write(), System.IO.Compression.WrappedStream.Write(), System.IO.Compression.WrappedStream.WriteAsync(), System.IO.Compression.WrappedStream.WriteAsync(), and System.IO.Compression.WrappedStream.WriteByte().