Terraria: System.IO.Compression.WrappedStream.ThrowIfCantWrite
ThrowIfCantWrite()
void System.IO.Compression.WrappedStream.ThrowIfCantWrite () inline private
Definition at line 113 of file WrappedStream.cs.
    {
        if (!CanWrite)
        {
            throw new NotSupportedException(System.SR.WritingNotSupported);
        }
    }
References System.IO.Compression.WrappedStream.CanWrite, and System.SR.WritingNotSupported.
Referenced by System.IO.Compression.WrappedStream.Flush(), System.IO.Compression.WrappedStream.FlushAsync(), System.IO.Compression.WrappedStream.SetLength(), System.IO.Compression.WrappedStream.Write(), System.IO.Compression.WrappedStream.Write(), System.IO.Compression.WrappedStream.WriteAsync(), System.IO.Compression.WrappedStream.WriteAsync(), and System.IO.Compression.WrappedStream.WriteByte().