Terraria: System.Text.RegularExpressions.RegexCharClass.ParseRecursive
ParseRecursive()
static RegexCharClass System.Text.RegularExpressions.RegexCharClass.ParseRecursive (string charClass, int start) inline static private
Definition at line 1032 of file RegexCharClass.cs.
    {
        int num = charClass[start + 1];
        int num2 = charClass[start + 2];
        int num3 = start + 3 + num + num2;
        int num4 = start + 3;
        int num5 = num4 + num;
        List<SingleRange> list = null;
        if (num > 0)
        {
            list = new List<SingleRange>(num);
            while (num4 < num5)
            {
                char first = charClass[num4];
                num4++;
                char last = ((num4 < num5) ? ((char)(charClass[num4] - 1)) : '\uffff');
                num4++;
                list.Add(new SingleRange(first, last));
            }
        }
        RegexCharClass subtraction = null;
        if (charClass.Length > num3)
        {
            subtraction = ParseRecursive(charClass, num3);
        }
        StringBuilder categories = null;
        if (num2 > 0)
        {
            categories = new StringBuilder().Append(charClass.AsSpan(num5, num2));
        }
        return new RegexCharClass(IsNegated(charClass, start), list, categories, subtraction);
    }
References System.Text.RegularExpressions.RegexCharClass.RegexCharClass(), System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Text.StringBuilder.Append(), System.Text.RegularExpressions.RegexCharClass.IsNegated(), System.list, System.Text.RegularExpressions.RegexCharClass.ParseRecursive(), and System.start.
Referenced by System.Text.RegularExpressions.RegexCharClass.Parse(), and System.Text.RegularExpressions.RegexCharClass.ParseRecursive().