Terraria: System.IO.Compression.WrappedStream.WriteAsync
WriteAsync() [3/3]
override ValueTask System.IO.Compression.WrappedStream.WriteAsync (ReadOnlyMemory< byte > buffer, CancellationToken cancellationToken = default(CancellationToken)) inline virtual
Reimplemented from System.IO.Stream.
Definition at line 207 of file WrappedStream.cs.
    {
        ThrowIfDisposed();
        ThrowIfCantWrite();
        return _baseStream.WriteAsync(buffer, cancellationToken);
    }
References System.IO.Compression.WrappedStream._baseStream, System.buffer, System.cancellationToken, System.IO.Compression.WrappedStream.ThrowIfCantWrite(), System.IO.Compression.WrappedStream.ThrowIfDisposed(), and System.IO.Stream.WriteAsync().