Terraria: System.Text.RegularExpressions.RegexCharClass.IsWordChar
IsWordChar()
static bool System.Text.RegularExpressions.RegexCharClass.IsWordChar (char ch) inline static
Definition at line 844 of file RegexCharClass.cs.
    {
        ReadOnlySpan<byte> readOnlySpan = AsciiLookup();
        int num = (int)ch >> 3;
        if ((uint)num < readOnlySpan.Length)
        {
            return (readOnlySpan[num] & (1 << (ch & 7))) != 0;
        }
        UnicodeCategory unicodeCategory = CharUnicodeInfo.GetUnicodeCategory(ch);
        if ((uint)unicodeCategory <= 5u || unicodeCategory == UnicodeCategory.DecimalDigitNumber || unicodeCategory == UnicodeCategory.ConnectorPunctuation)
        {
            return true;
        }
        if (ch != '\u200d')
        {
            return ch == '\u200c';
        }
        return true;
        static ReadOnlySpan<byte> AsciiLookup()
        {
            return new byte[16]
            {
                0, 0, 0, 0, 0, 0, 255, 3, 254, 255,
                255, 135, 254, 255, 255, 7
            };
        }
    }
References System.ch, and System.Globalization.CharUnicodeInfo.GetUnicodeCategory().
Referenced by System.Text.RegularExpressions.RegexNode.CanBeMadeAtomic(), System.Text.RegularExpressions.RegexParser.CountCaptures(), System.Text.RegularExpressions.RegexRunner.IsBoundary(), System.Text.RegularExpressions.RegexParser.ParseProperty(), System.Text.RegularExpressions.RegexParser.ScanBasicBackslash(), System.Text.RegularExpressions.RegexParser.ScanCapname(), System.Text.RegularExpressions.RegexParser.ScanCharEscape(), System.Text.RegularExpressions.RegexParser.ScanDollar(), and System.Text.RegularExpressions.RegexParser.ScanGroupOpen().