Terraria: System.Text.RegularExpressions.RegexCharClass.CharInClass
CharInClass() [2/2]
static bool System.Text.RegularExpressions.RegexCharClass.CharInClass (char ch, string set, ref int[] asciiResultCache) inline static
Definition at line 872 of file RegexCharClass.cs.
    {
        if (ch < '\u0080')
        {
            if (asciiResultCache == null)
            {
                Interlocked.CompareExchange(ref asciiResultCache, new int[8], null);
            }
            ref int reference = ref asciiResultCache[(int)ch >> 4];
            int num = 1 << ((ch & 0xF) << 1);
            int num2 = num << 1;
            int num3 = reference;
            if ((num3 & num) != 0)
            {
                return (num3 & num2) != 0;
            }
            bool flag = CharInClass(ch, set);
            int num4 = num;
            if (flag)
            {
                num4 |= num2;
            }
            Interlocked.Or(ref reference, num4);
            return flag;
        }
        return CharInClassRecursive(ch, set, 0);
    }
References System.ch, System.Text.RegularExpressions.RegexCharClass.CharInClass(), System.Text.RegularExpressions.RegexCharClass.CharInClassRecursive(), System.Threading.Interlocked.CompareExchange(), and System.Threading.Interlocked.Or().
Referenced by System.Text.RegularExpressions.RegexNode.CanBeMadeAtomic(), System.Text.RegularExpressions.RegexRunner.CharInClass(), System.Text.RegularExpressions.RegexCharClass.CharInClass(), System.Text.RegularExpressions.RegexRunner.CharInSet(), System.Text.RegularExpressions.RegexCompiler.EmitMatchCharacterClass(), System.Text.RegularExpressions.RegexInterpreter.FindFirstChar(), System.Text.RegularExpressions.RegexInterpreter.Go(), and System.Text.RegularExpressions.RegexCharClass.MayOverlap().