Terraria: System.IO.Compression.WrappedStream.ReadAsync
ReadAsync() [3/3]
override ValueTask< int > System.IO.Compression.WrappedStream.ReadAsync (Memory< byte > buffer, CancellationToken cancellationToken = default(CancellationToken)) inline virtual
Reimplemented from System.IO.Stream.
Definition at line 157 of file WrappedStream.cs.
    {
        ThrowIfDisposed();
        ThrowIfCantRead();
        return _baseStream.ReadAsync(buffer, cancellationToken);
    }
References System.IO.Compression.WrappedStream._baseStream, System.buffer, System.cancellationToken, System.IO.Stream.ReadAsync(), System.IO.Compression.WrappedStream.ThrowIfCantRead(), and System.IO.Compression.WrappedStream.ThrowIfDisposed().