Terraria: Microsoft.Xna.Framework.Graphics.OcclusionQuery.OcclusionQuery
OcclusionQuery() [2/2]
unsafe Microsoft.Xna.Framework.Graphics.OcclusionQuery.OcclusionQuery (GraphicsDevice graphicsDevice) inline
Definition at line 77 of file OcclusionQuery.cs.
    {
        try
        {
            if (graphicsDevice == null)
            {
                throw new ArgumentNullException("graphicsDevice", FrameworkResources.DeviceCannotBeNullOnResourceCreate);
            }
            if (!graphicsDevice._profileCapabilities.OcclusionQuery)
            {
                graphicsDevice._profileCapabilities.ThrowNotSupportedException(FrameworkResources.ProfileFeatureNotSupported, typeof(OcclusionQuery).Name);
            }
            _hasIsCompleteBeenQueried = true;
            fixed (IDirect3DQuery9** ptr = &pComPtr)
            {
                int num = *(int*)graphicsDevice.pComPtr + 472;
                int num2 = ((delegate* unmanaged[Stdcall, Stdcall]<IntPtr, _D3DQUERYTYPE, IDirect3DQuery9**, int>)(int)(*(uint*)num))((nint)graphicsDevice.pComPtr, (_D3DQUERYTYPE)9, ptr);
                if (num2 < 0)
                {
                    throw GraphicsHelpers.GetExceptionFromResult((uint)num2);
                }
                _parent = graphicsDevice;
                graphicsDevice.Resources.AddTrackedObject(this, pComPtr, 0u, _internalHandle, ref _internalHandle);
                return;
            }
        }
        catch
        {
            //try-fault
            base.Dispose(true);
            throw;
        }
    }
References Microsoft.Xna.Framework.Graphics.OcclusionQuery._hasIsCompleteBeenQueried, Microsoft.Xna.Framework.Graphics.GraphicsResource._internalHandle, Microsoft.Xna.Framework.Graphics.GraphicsResource._parent, Microsoft.Xna.Framework.Graphics.GraphicsDevice._profileCapabilities, Microsoft.Xna.Framework.Graphics.DeviceResourceManager.AddTrackedObject(), Microsoft.Xna.Framework.FrameworkResources.DeviceCannotBeNullOnResourceCreate, Microsoft.Xna.Framework.Graphics.GraphicsHelpers.GetExceptionFromResult(), Microsoft.Xna.Framework.Graphics.GraphicsResource.Name, Microsoft.Xna.Framework.Graphics.ProfileCapabilities.OcclusionQuery, Microsoft.Xna.Framework.Graphics.GraphicsDevice.pComPtr, Microsoft.Xna.Framework.Graphics.OcclusionQuery.pComPtr, Microsoft.Xna.Framework.FrameworkResources.ProfileFeatureNotSupported, Microsoft.Xna.Framework.Graphics.GraphicsDevice.Resources, and Microsoft.Xna.Framework.Graphics.ProfileCapabilities.ThrowNotSupportedException().