Terraria: Microsoft.Xna.Framework.Graphics.OcclusionQuery.ReleaseNativeObject
ReleaseNativeObject() [1/2]
virtual unsafe void Microsoft.Xna.Framework.Graphics.OcclusionQuery.ReleaseNativeObject ([MarshalAs(UnmanagedType.U1)] bool disposeManagedResource) inline package virtual
Implements Microsoft.Xna.Framework.Graphics.IGraphicsResource.
Definition at line 183 of file OcclusionQuery.cs.
    {
        GraphicsDevice parent = _parent;
        if (parent != null && pComPtr != null)
        {
            parent.Resources.ReleaseAllReferences(_internalHandle, disposeManagedResource);
        }
        _isAvailable = false;
        pComPtr = null;
    }
References Microsoft.Xna.Framework.Graphics.GraphicsResource._internalHandle, Microsoft.Xna.Framework.Graphics.OcclusionQuery._isAvailable, Microsoft.Xna.Framework.Graphics.GraphicsResource._parent, Microsoft.Xna.Framework.Graphics.OcclusionQuery.pComPtr, Microsoft.Xna.Framework.Graphics.DeviceResourceManager.ReleaseAllReferences(), and Microsoft.Xna.Framework.Graphics.GraphicsDevice.Resources.
Referenced by Microsoft.Xna.Framework.Graphics.OcclusionQuery._0021OcclusionQuery(), Microsoft.Xna.Framework.Graphics.OcclusionQuery._007EOcclusionQuery(), and Microsoft.Xna.Framework.Graphics.OcclusionQuery.ReleaseNativeObject().