Terraria: System.Net.WebFileStream.CheckAborted
CheckAborted()
void System.Net.WebFileStream.CheckAborted () inline private
Definition at line 167 of file WebFileStream.cs.
    {
        if (_request.Aborted)
        {
            throw new WebException(System.SR.Format(System.SR.net_requestaborted, WebExceptionStatus.RequestCanceled), WebExceptionStatus.RequestCanceled);
        }
    }
References System.Net.WebFileStream._request, System.Net.FileWebRequest.Aborted, System.SR.Format(), and System.SR.net_requestaborted.
Referenced by System.Net.WebFileStream.BeginRead(), System.Net.WebFileStream.BeginWrite(), System.Net.WebFileStream.CopyToAsync(), System.Net.WebFileStream.EndRead(), System.Net.WebFileStream.EndWrite(), System.Net.WebFileStream.Read(), System.Net.WebFileStream.ReadAsync(), System.Net.WebFileStream.Write(), and System.Net.WebFileStream.WriteAsync().