Terraria: System.ReadOnlyMemory.Slice
Slice() [1/2]
ReadOnlyMemory< T > System.ReadOnlyMemory< T >.Slice (int start) inline
Definition at line 134 of file ReadOnlyMemory.cs.
    {
        if ((uint)start > (uint)_length)
        {
            ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument.start);
        }
        return new ReadOnlyMemory<T>(_object, _index + start, _length - start);
    }
References System.ReadOnlyMemory< T >._index, System.ReadOnlyMemory< T >._length, System.ReadOnlyMemory< T >._object, System.start, and System.ThrowHelper.ThrowArgumentOutOfRangeException().
Referenced by System.Formats.Asn1.AsnReader.CloneAtSlice(), System.IO.ReadOnlyMemoryStream.CopyToAsync(), System.Security.Cryptography.Asn1.AlgorithmIdentifierAsn.DecodeCore(), System.Security.Cryptography.Asn1.CurveAsn.DecodeCore(), System.Security.Cryptography.Asn1.ECPrivateKey.DecodeCore(), System.Security.Cryptography.Asn1.EncryptedPrivateKeyInfoAsn.DecodeCore(), System.Security.Cryptography.Asn1.FieldID.DecodeCore(), System.Security.Cryptography.Asn1.PBEParameter.DecodeCore(), System.Security.Cryptography.Asn1.Rc2CbcParameters.DecodeCore(), System.Security.Cryptography.Asn1.SpecifiedECDomain.DecodeCore(), System.Security.Cryptography.Asn1.SubjectPublicKeyInfoAsn.DecodeCore(), System.Security.Cryptography.Asn1.Pbkdf2SaltChoice.DecodeCore(), System.Security.Cryptography.X509Certificates.Asn1.CertificateAsn.DecodeCore(), System.Security.Cryptography.Asn1.AlgorithmIdentifierAsn.DecodeCore(), System.Security.Cryptography.Asn1.CurveAsn.DecodeCore(), System.Security.Cryptography.Asn1.ECPrivateKey.DecodeCore(), System.Security.Cryptography.Asn1.EncryptedPrivateKeyInfoAsn.DecodeCore(), System.Security.Cryptography.Asn1.FieldID.DecodeCore(), System.Security.Cryptography.Asn1.PBEParameter.DecodeCore(), System.Security.Cryptography.Asn1.Rc2CbcParameters.DecodeCore(), System.Security.Cryptography.Asn1.SpecifiedECDomain.DecodeCore(), System.Security.Cryptography.Asn1.SubjectPublicKeyInfoAsn.DecodeCore(), System.Security.Cryptography.Asn1.X509ExtensionAsn.DecodeCore(), System.Security.Cryptography.Asn1.Pbkdf2SaltChoice.DecodeCore(), System.Buffers.ReadOnlySequence< T >.GetFirstBuffer(), System.Text.Json.JsonDocument.GetPropertyRawValue(), System.Text.Json.JsonDocument.GetRawValue(), System.IO.Strategies.BufferedFileStreamStrategy._003CWriteAsyncSlowPath_003Ed__50.MoveNext(), System.Formats.Asn1.AsnReader.PeekContentBytes(), System.Formats.Asn1.AsnReader.PeekEncodedValue(), System.Formats.Asn1.AsnReader.ReadBitString(), System.Formats.Asn1.AsnReader.ReadBoolean(), System.Formats.Asn1.AsnReader.ReadCharacterString(), System.Formats.Asn1.AsnReader.ReadEncodedValue(), System.Formats.Asn1.AsnReader.ReadEnumeratedBytes(), System.Formats.Asn1.AsnReader.ReadEnumeratedValue(), System.Formats.Asn1.AsnReader.ReadEnumeratedValue< TEnum >(), System.Formats.Asn1.AsnReader.ReadGeneralizedTime(), System.Formats.Asn1.AsnReader.ReadInteger(), System.Formats.Asn1.AsnReader.ReadIntegerBytes(), System.Formats.Asn1.AsnReader.ReadNamedBitList(), System.Formats.Asn1.AsnReader.ReadNamedBitListValue(), System.Formats.Asn1.AsnReader.ReadNamedBitListValue< TFlagsEnum >(), System.Formats.Asn1.AsnReader.ReadNull(), System.Formats.Asn1.AsnReader.ReadObjectIdentifier(), System.Formats.Asn1.AsnReader.ReadOctetString(), System.Formats.Asn1.AsnReader.ReadSequence(), System.Formats.Asn1.AsnReader.ReadSetOf(), System.Formats.Asn1.AsnReader.ReadUtcTime(), System.Formats.Asn1.AsnReader.ReadUtcTime(), System.Formats.Asn1.AsnReader.TryReadBitString(), System.Formats.Asn1.AsnReader.TryReadCharacterString(), System.Formats.Asn1.AsnReader.TryReadCharacterStringBytes(), System.Formats.Asn1.AsnReader.TryReadInt32(), System.Formats.Asn1.AsnReader.TryReadInt64(), System.Formats.Asn1.AsnReader.TryReadOctetString(), System.Formats.Asn1.AsnReader.TryReadPrimitiveBitString(), System.Formats.Asn1.AsnReader.TryReadPrimitiveCharacterStringBytes(), System.Formats.Asn1.AsnReader.TryReadPrimitiveOctetString(), System.Formats.Asn1.AsnReader.TryReadUInt32(), System.Formats.Asn1.AsnReader.TryReadUInt64(), System.Text.Json.JsonDocument.UnescapeString(), System.Text.TranscodingStream.WriteAsync(), System.Text.Json.JsonDocument.WriteComplexElement(), and System.Text.Json.JsonDocument.WriteElementTo().