Terraria: System.ReadOnlyMemory.Pin
Pin()
unsafe MemoryHandle System.ReadOnlyMemory< T >.Pin () inline
Definition at line 163 of file ReadOnlyMemory.cs.
    {
        object @object = _object;
        if (@object != null)
        {
            if (typeof(T) == typeof(char) && @object is string text)
            {
                GCHandle handle = GCHandle.Alloc(@object, GCHandleType.Pinned);
                return new MemoryHandle(Unsafe.AsPointer(ref Unsafe.Add(ref text.GetRawStringData(), _index)), handle);
            }
            if (RuntimeHelpers.ObjectHasComponentSize(@object))
            {
                if (_index < 0)
                {
                    void* pointer = Unsafe.Add<T>(Unsafe.AsPointer(ref MemoryMarshal.GetArrayDataReference(Unsafe.As<T[]>(@object))), _index & 0x7FFFFFFF);
                    return new MemoryHandle(pointer);
                }
                GCHandle handle2 = GCHandle.Alloc(@object, GCHandleType.Pinned);
                void* pointer2 = Unsafe.Add<T>(Unsafe.AsPointer(ref MemoryMarshal.GetArrayDataReference(Unsafe.As<T[]>(@object))), _index);
                return new MemoryHandle(pointer2, handle2);
            }
            return Unsafe.As<MemoryManager<T>>(@object).Pin(_index);
        }
        return default(MemoryHandle);
    }
References System.ReadOnlyMemory< T >._index, System.ReadOnlyMemory< T >._object, System.Runtime.InteropServices.GCHandle.Alloc(), System.Runtime.InteropServices.MemoryMarshal.GetArrayDataReference(), System.handle, System.Runtime.CompilerServices.RuntimeHelpers.ObjectHasComponentSize(), System.ReadOnlyMemory< T >.Pin(), System.pointer, and System.text.
Referenced by System.IO.Strategies.Net5CompatFileStreamStrategy.MemoryFileStreamCompletionSource.MemoryFileStreamCompletionSource(), System.ReadOnlyMemory< T >.Pin(), System.Net.Quic.Implementations.MsQuic.MsQuicStream.SendReadOnlyMemoryListAsync(), System.Net.Quic.Implementations.MsQuic.MsQuicStream.SendReadOnlySequenceAsync(), System.IO.Compression.Deflater.SetInput(), and System.IO.Compression.Inflater.SetInput().