Terraria: System.Runtime.Serialization.ExtensionDataReader.MoveToAttribute
MoveToAttribute() [1/4]
override void System.Runtime.Serialization.ExtensionDataReader.MoveToAttribute (int index) inline virtual
Reimplemented from System.Xml.XmlReader.
Definition at line 373 of file ExtensionDataReader.cs.
    {
        if (IsXmlDataNode)
        {
            _xmlNodeReader.MoveToAttribute(index);
            return;
        }
        if (index < 0 || index >= _attributeCount)
        {
            throw new XmlException(System.SR.InvalidXmlDeserializingExtensionData);
        }
        _nodeType = XmlNodeType.Attribute;
        AttributeData attributeData = _element.attributes[index];
        _localName = attributeData.localName;
        _ns = attributeData.ns;
        _prefix = attributeData.prefix;
        _value = attributeData.value;
        _attributeIndex = index;
    }
References System.Runtime.Serialization.ExtensionDataReader._attributeCount, System.Runtime.Serialization.ExtensionDataReader._attributeIndex, System.Runtime.Serialization.ExtensionDataReader._element, System.Runtime.Serialization.ExtensionDataReader._localName, System.Runtime.Serialization.ExtensionDataReader._nodeType, System.Runtime.Serialization.ExtensionDataReader._ns, System.Runtime.Serialization.ExtensionDataReader._prefix, System.Runtime.Serialization.ExtensionDataReader._value, System.Runtime.Serialization.ExtensionDataReader._xmlNodeReader, System.Runtime.Serialization.ElementData.attributes, System.Runtime.Serialization.Dictionary, System.index, System.SR.InvalidXmlDeserializingExtensionData, System.Runtime.Serialization.ExtensionDataReader.IsXmlDataNode, System.Xml.XmlNodeReader.MoveToAttribute(), and System.Xml.XmlException.
Referenced by System.Runtime.Serialization.ExtensionDataReader.MoveToAttribute(), System.Runtime.Serialization.ExtensionDataReader.MoveToFirstAttribute(), and System.Runtime.Serialization.ExtensionDataReader.MoveToNextAttribute().