Terraria: System.Runtime.Serialization.ExtensionDataReader.Read
Read()
override bool System.Runtime.Serialization.ExtensionDataReader.Read () inline
Definition at line 525 of file ExtensionDataReader.cs.
    {
        if (_nodeType == XmlNodeType.Attribute && MoveToNextAttribute())
        {
            return true;
        }
        MoveNext(_element.dataNode);
        switch (_internalNodeType)
        {
        case ExtensionDataNodeType.Element:
        case ExtensionDataNodeType.ReferencedElement:
        case ExtensionDataNodeType.NullElement:
            PushElement();
            SetElement();
            break;
        case ExtensionDataNodeType.Text:
            _nodeType = XmlNodeType.Text;
            _prefix = string.Empty;
            _ns = string.Empty;
            _localName = string.Empty;
            _attributeCount = 0;
            _attributeIndex = -1;
            break;
        case ExtensionDataNodeType.EndElement:
            _nodeType = XmlNodeType.EndElement;
            _prefix = string.Empty;
            _ns = string.Empty;
            _localName = string.Empty;
            _value = string.Empty;
            _attributeCount = 0;
            _attributeIndex = -1;
            PopElement();
            break;
        case ExtensionDataNodeType.None:
            if (_depth != 0)
            {
                throw new XmlException(System.SR.InvalidXmlDeserializingExtensionData);
            }
            _nodeType = XmlNodeType.None;
            _prefix = string.Empty;
            _ns = string.Empty;
            _localName = string.Empty;
            _value = string.Empty;
            _attributeCount = 0;
            _readState = ReadState.EndOfFile;
            return false;
        default:
            throw new SerializationException(System.SR.InvalidStateInExtensionDataReader);
        case ExtensionDataNodeType.Xml:
            break;
        }
        _readState = ReadState.Interactive;
        return true;
    }
References System.Runtime.Serialization.ExtensionDataReader._attributeCount, System.Runtime.Serialization.ExtensionDataReader._attributeIndex, System.Runtime.Serialization.ExtensionDataReader._depth, System.Runtime.Serialization.ExtensionDataReader._element, System.Runtime.Serialization.ExtensionDataReader._internalNodeType, System.Runtime.Serialization.ExtensionDataReader._localName, System.Runtime.Serialization.ExtensionDataReader._nodeType, System.Runtime.Serialization.ExtensionDataReader._ns, System.Runtime.Serialization.ExtensionDataReader._prefix, System.Runtime.Serialization.ExtensionDataReader._readState, System.Runtime.Serialization.ExtensionDataReader._value, System.Runtime.Serialization.ElementData.dataNode, System.SR.InvalidStateInExtensionDataReader, System.SR.InvalidXmlDeserializingExtensionData, System.Runtime.Serialization.ExtensionDataReader.MoveNext(), System.Runtime.Serialization.ExtensionDataReader.MoveToNextAttribute(), System.Runtime.Serialization.ExtensionDataReader.PopElement(), System.Runtime.Serialization.ExtensionDataReader.PushElement(), System.Runtime.Serialization.ExtensionDataReader.SetElement(), and System.Xml.XmlException.
Referenced by System.Runtime.Serialization.ExtensionDataReader.Skip().