Terraria: System.Security.Cryptography.X509Certificates.ECDsaCertificateExtensions.CopyWithPrivateKey
CopyWithPrivateKey()
static X509Certificate2 System.Security.Cryptography.X509Certificates.ECDsaCertificateExtensions.CopyWithPrivateKey (this X509Certificate2 certificate, ECDsa privateKey) inline static
Definition at line 18 of file ECDsaCertificateExtensions.cs.
    {
        if (certificate == null)
        {
            throw new ArgumentNullException("certificate");
        }
        if (privateKey == null)
        {
            throw new ArgumentNullException("privateKey");
        }
        if (certificate.HasPrivateKey)
        {
            throw new InvalidOperationException(System.SR.Cryptography_Cert_AlreadyHasPrivateKey);
        }
        using (ECDsa eCDsa = certificate.GetECDsaPublicKey())
        {
            if (eCDsa == null)
            {
                throw new ArgumentException(System.SR.Cryptography_PrivateKey_WrongAlgorithm);
            }
            if (!Internal.Cryptography.Helpers.AreSamePublicECParameters(eCDsa.ExportParameters(includePrivateParameters: false), privateKey.ExportParameters(includePrivateParameters: false)))
            {
                throw new ArgumentException(System.SR.Cryptography_PrivateKey_DoesNotMatch, "privateKey");
            }
        }
        ICertificatePal pal = certificate.Pal.CopyWithPrivateKey(privateKey);
        return new X509Certificate2(pal);
    }
References Internal.Cryptography.Helpers.AreSamePublicECParameters(), Internal.Cryptography.ICertificatePal.CopyWithPrivateKey(), System.SR.Cryptography_Cert_AlreadyHasPrivateKey, System.SR.Cryptography_PrivateKey_DoesNotMatch, System.SR.Cryptography_PrivateKey_WrongAlgorithm, System.Security.Cryptography.ECDsa.ExportParameters(), System.Security.Cryptography.X509Certificates.X509Certificate2.HasPrivateKey, and System.Security.Cryptography.X509Certificates.X509Certificate2.Pal.