Terraria: System.Runtime.Serialization.ExtensionDataReader.Skip
Skip()
override void System.Runtime.Serialization.ExtensionDataReader.Skip () inline virtual
Reimplemented from System.Xml.XmlReader.
Definition at line 462 of file ExtensionDataReader.cs.
    {
        if (IsXmlDataNode)
        {
            _xmlNodeReader.Skip();
        }
        else
        {
            if (ReadState != ReadState.Interactive)
            {
                return;
            }
            MoveToElement();
            if (IsElementNode(_internalNodeType))
            {
                int num = 1;
                while (num != 0)
                {
                    if (!Read())
                    {
                        throw new XmlException(System.SR.InvalidXmlDeserializingExtensionData);
                    }
                    if (IsElementNode(_internalNodeType))
                    {
                        num++;
                    }
                    else if (_internalNodeType == ExtensionDataNodeType.EndElement)
                    {
                        ReadEndElement();
                        num--;
                    }
                }
            }
            else
            {
                Read();
            }
        }
    }
References System.Runtime.Serialization.ExtensionDataReader._internalNodeType, System.Runtime.Serialization.ExtensionDataReader._xmlNodeReader, System.SR.InvalidXmlDeserializingExtensionData, System.Runtime.Serialization.ExtensionDataReader.IsElementNode(), System.Runtime.Serialization.ExtensionDataReader.IsXmlDataNode, System.Runtime.Serialization.ExtensionDataReader.MoveToElement(), System.Runtime.Serialization.ExtensionDataReader.Read(), System.Xml.XmlReader.ReadEndElement(), System.Xml.XmlNodeReader.Skip(), and System.Xml.XmlException.
Referenced by System.Runtime.Serialization.ExtensionDataReader.GetCurrentNode().