Terraria: FlameLashDrawer.Draw
Draw()
void FlameLashDrawer.Draw (Projectile proj) inline
     {
         transitToDark = Utils.GetLerpValue(0f, 6f, proj.localAI[0], clamped: true);
         MiscShaderData miscShaderData = GameShaders.Misc["FlameLash"];
         miscShaderData.UseSaturation(-2f);
         miscShaderData.UseOpacity(MathHelper.Lerp(4f, 8f, transitToDark));
         miscShaderData.Apply();
         _vertexStrip.PrepareStripWithProceduralPadding(proj.oldPos, proj.oldRot, StripColors, StripWidth, -Main.screenPosition + proj.Size / 2f);
         _vertexStrip.DrawTrail();
         Main.pixelShader.CurrentTechnique.Passes[0].Apply();
     }
References _vertexStrip, MiscShaderData.Apply(), VertexStrip.DrawTrail(), Utils.GetLerpValue(), Projectile.localAI, GameShaders.Misc, Projectile.oldPos, Projectile.oldRot, Main.pixelShader, VertexStrip.PrepareStripWithProceduralPadding(), Main.screenPosition, Entity.Size, StripColors(), StripWidth(), transitToDark, MiscShaderData.UseOpacity(), and MiscShaderData.UseSaturation().