Terraria: Terraria.IngameOptions.Close
Close()
static void Terraria.IngameOptions.Close () inline static
Definition at line 94 of file IngameOptions.cs.
    {
        if (Main.setKey == -1)
        {
            Main.ingameOptionsWindow = false;
            SoundEngine.PlaySound(11);
            Recipe.FindRecipes();
            Main.playerInventory = true;
            Main.SaveSettings();
        }
    }
References Terraria.Recipe.FindRecipes(), Terraria.Audio.SoundEngine.PlaySound(), Terraria.Main.SaveSettings(), and Terraria.Main.setKey.
Referenced by Terraria.IngameOptions.Draw(), Terraria.Main.DrawInterface_29_SettingsButton(), Terraria.GameContent.UI.Chat.AchievementTagHandler.AchievementSnippet.OnClick(), Terraria.Player.ToggleCreativeMenu(), Terraria.Player.ToggleInv(), and Terraria.Player.TryOpeningInGameOptionsBasedOnInput().