Terraria: PlayerTitaniumStormBuffTextureContent.HandleUseReqest
HandleUseReqest()
override void PlayerTitaniumStormBuffTextureContent.HandleUseReqest (GraphicsDevice device, SpriteBatch spriteBatch) inline protected virtual
Implements ARenderTargetContentByRequest.
     {
         Main.instance.LoadProjectile(908);
         Asset<Texture2D> val = TextureAssets.Projectile[908];
         UpdateSettingsForRendering(0.6f, 0f, Main.GlobalTimeWrappedHourly, 0.3f);
         PrepareARenderTarget_AndListenToEvents(ref _target, device, val.Width(), val.Height(), RenderTargetUsage.PreserveContents);
         device.SetRenderTarget(_target);
         device.Clear(Color.Transparent);
         DrawData value = new DrawData(val.Value, Vector2.Zero, Color.White);
         spriteBatch.Begin(SpriteSortMode.Immediate, BlendState.AlphaBlend);
         _shaderData.Apply(value);
         value.Draw(spriteBatch);
         spriteBatch.End();
         device.SetRenderTarget(null);
         _wasPrepared = true;
     }
References _shaderData, ARenderTargetContentByRequest._target, ARenderTargetContentByRequest._wasPrepared, MiscShaderData.Apply(), Color, DrawData.Draw(), Main.GlobalTimeWrappedHourly, Main.instance, Main.LoadProjectile(), ARenderTargetContentByRequest.PrepareARenderTarget_AndListenToEvents(), TextureAssets.Projectile, UpdateSettingsForRendering(), and Asset< T >.Value.