Terraria: System.Threading.PortableThreadPool.GateThread.EnsureRunningSlow
EnsureRunningSlow()
static void System.Threading.PortableThreadPool.GateThread.EnsureRunningSlow (PortableThreadPool threadPoolInstance) inline static package
Definition at line 280 of file PortableThreadPool.cs.
        {
            int num = Interlocked.Exchange(ref threadPoolInstance._separated.gateThreadRunningState, GetRunningStateForNumRuns(2));
            if (num == GetRunningStateForNumRuns(0))
            {
                RunGateThreadEvent.Set();
            }
            else if ((num & 4) == 0)
            {
                CreateGateThread(threadPoolInstance);
            }
        }
References System.Threading.PortableThreadPool._separated, System.Threading.PortableThreadPool.GateThread.CreateGateThread(), System.Threading.Interlocked.Exchange(), System.Threading.PortableThreadPool.CacheLineSeparated.gateThreadRunningState, System.Threading.PortableThreadPool.GateThread.GetRunningStateForNumRuns(), and System.Threading.PortableThreadPool.GateThread.RunGateThreadEvent.
Referenced by System.Threading.PortableThreadPool.GateThread.EnsureRunning().