Terraria: System.Threading.PortableThreadPool.GateThread.GateThreadStart
GateThreadStart()
static void System.Threading.PortableThreadPool.GateThread.GateThreadStart () inline static private
Definition at line 156 of file PortableThreadPool.cs.
        {
            bool booleanConfig = AppContextConfigHelper.GetBooleanConfig("System.Threading.ThreadPool.DisableStarvationDetection", defaultValue: false);
            bool booleanConfig2 = AppContextConfigHelper.GetBooleanConfig("System.Threading.ThreadPool.DebugBreakOnWorkerStarvation", defaultValue: false);
            CpuUtilizationReader cpuUtilizationReader = default(CpuUtilizationReader);
            _ = cpuUtilizationReader.CurrentUtilization;
            PortableThreadPool threadPoolInstance = ThreadPoolInstance;
            LowLevelLock threadAdjustmentLock = threadPoolInstance._threadAdjustmentLock;
            DelayHelper delayHelper = default(DelayHelper);
            if (BlockingConfig.IsCooperativeBlockingEnabled)
            {
                threadPoolInstance.OnGen2GCCallback();
                Gen2GcCallback.Register(threadPoolInstance.OnGen2GCCallback);
            }
            while (true)
            {
                RunGateThreadEvent.WaitOne();
                int tickCount = Environment.TickCount;
                delayHelper.SetGateActivitiesTime(tickCount);
                while (true)
                {
                    bool wasSignaledToWake = DelayEvent.WaitOne((int)delayHelper.GetNextDelay(tickCount));
                    tickCount = Environment.TickCount;
                    PendingBlockingAdjustment pendingBlockingAdjustment = threadPoolInstance._pendingBlockingAdjustment;
                    if (pendingBlockingAdjustment == PendingBlockingAdjustment.None)
                    {
                        delayHelper.ClearBlockingAdjustmentDelay();
                    }
                    else
                    {
                        bool flag = false;
                        if (delayHelper.HasBlockingAdjustmentDelay)
{
                            flag = delayHelper.HasBlockingAdjustmentDelayElapsed(tickCount, wasSignaledToWake);
                            if (pendingBlockingAdjustment == PendingBlockingAdjustment.WithDelayIfNecessary && !flag)
{
                                goto IL_00ee;
                            }
                        }
                        uint num = threadPoolInstance.PerformBlockingAdjustment(flag);
                        if (num == 0)
{
                            delayHelper.ClearBlockingAdjustmentDelay();
                        }
                        else
{
                            delayHelper.SetBlockingAdjustmentTimeAndDelay(tickCount, num);
                        }
                    }
                    goto IL_00ee;
                    IL_00ee:
                    if (!delayHelper.ShouldPerformGateActivities(tickCount, wasSignaledToWake))
                    {
                        continue;
                    }
                    if (ThreadPool.EnableWorkerTracking && NativeRuntimeEventSource.Log.IsEnabled())
                    {
                        NativeRuntimeEventSource.Log.ThreadPoolWorkingThreadCount((uint)threadPoolInstance.GetAndResetHighWatermarkCountOfThreadsProcessingUserCallbacks(), 0);
                    }
                    bool flag2 = ThreadPool.PerformRuntimeSpecificGateActivities(threadPoolInstance._cpuUtilization = cpuUtilizationReader.CurrentUtilization);
                    if (!booleanConfig && threadPoolInstance._pendingBlockingAdjustment == PendingBlockingAdjustment.None && threadPoolInstance._separated.numRequestedWorkers > 0 && SufficientDelaySinceLastDequeue(threadPoolInstance))
                    {
                        bool flag3 = false;
                        threadAdjustmentLock.Acquire();
                        try
{
                            ThreadCounts threadCounts = threadPoolInstance._separated.counts;
                            while (threadCounts.NumProcessingWork < threadPoolInstance._maxThreads && threadCounts.NumProcessingWork >= threadCounts.NumThreadsGoal)
{
                                if (booleanConfig2)
{
                                    Debugger.Break();
                                }
                                ThreadCounts newCounts = threadCounts;
                                short newThreadCount = (newCounts.NumThreadsGoal = (short)(threadCounts.NumProcessingWork + 1));
                                ThreadCounts threadCounts2 = threadPoolInstance._separated.counts.InterlockedCompareExchange(newCounts, threadCounts);
                                if (threadCounts2 == threadCounts)
{
                                    HillClimbing.ThreadPoolHillClimber.ForceChange(newThreadCount, HillClimbing.StateOrTransition.Starvation);
                                    flag3 = true;
                                    break;
                                }
                                threadCounts = threadCounts2;
                            }
                        }
                        finally
{
                            threadAdjustmentLock.Release();
                        }
                        if (flag3)
{
                            WorkerThread.MaybeAddWorkingWorker(threadPoolInstance);
                        }
                    }
                    if (!flag2 && threadPoolInstance._separated.numRequestedWorkers <= 0 && threadPoolInstance._pendingBlockingAdjustment == PendingBlockingAdjustment.None && Interlocked.Decrement(ref threadPoolInstance._separated.gateThreadRunningState) <= GetRunningStateForNumRuns(0))
                    {
                        break;
                    }
                }
            }
        }
References System.Threading.PortableThreadPool._cpuUtilization, System.Threading.PortableThreadPool._maxThreads, System.Threading.PortableThreadPool._pendingBlockingAdjustment, System.Threading.PortableThreadPool._separated, System.Threading.PortableThreadPool._threadAdjustmentLock, System.Threading.LowLevelLock.Acquire(), System.Diagnostics.Debugger.Break(), System.Threading.PortableThreadPool.GateThread.DelayHelper.ClearBlockingAdjustmentDelay(), System.Threading.PortableThreadPool.CacheLineSeparated.counts, System.Threading.PortableThreadPool.CpuUtilizationReader.CurrentUtilization, System.Threading.Interlocked.Decrement(), System.Threading.PortableThreadPool.GateThread.DelayEvent, System.Threading.ThreadPool.EnableWorkerTracking, System.Threading.PortableThreadPool.CacheLineSeparated.gateThreadRunningState, System.Threading.PortableThreadPool.GetAndResetHighWatermarkCountOfThreadsProcessingUserCallbacks(), System.AppContextConfigHelper.GetBooleanConfig(), System.Threading.PortableThreadPool.GateThread.DelayHelper.GetNextDelay(), System.Threading.PortableThreadPool.GateThread.GetRunningStateForNumRuns(), System.Threading.PortableThreadPool.GateThread.DelayHelper.HasBlockingAdjustmentDelay, System.Threading.PortableThreadPool.GateThread.DelayHelper.HasBlockingAdjustmentDelayElapsed(), System.Threading.PortableThreadPool.ThreadCounts.InterlockedCompareExchange(), System.Threading.PortableThreadPool.BlockingConfig.IsCooperativeBlockingEnabled, System.Diagnostics.Tracing.NativeRuntimeEventSource.Log, System.Threading.PortableThreadPool.WorkerThread.MaybeAddWorkingWorker(), System.Threading.PortableThreadPool.ThreadCounts.NumProcessingWork, System.Threading.PortableThreadPool.CacheLineSeparated.numRequestedWorkers, System.Threading.PortableThreadPool.ThreadCounts.NumThreadsGoal, System.Threading.PortableThreadPool.OnGen2GCCallback(), System.Threading.PortableThreadPool.PerformBlockingAdjustment(), System.Threading.ThreadPool.PerformRuntimeSpecificGateActivities(), System.Gen2GcCallback.Register(), System.Threading.LowLevelLock.Release(), System.Threading.PortableThreadPool.GateThread.RunGateThreadEvent, System.Threading.PortableThreadPool.GateThread.DelayHelper.SetBlockingAdjustmentTimeAndDelay(), System.Threading.PortableThreadPool.GateThread.DelayHelper.SetGateActivitiesTime(), System.Threading.PortableThreadPool.GateThread.DelayHelper.ShouldPerformGateActivities(), System.Threading.PortableThreadPool.GateThread.SufficientDelaySinceLastDequeue(), System.Threading.PortableThreadPool.HillClimbing.ThreadPoolHillClimber, System.Threading.PortableThreadPool.ThreadPoolInstance, and System.Environment.TickCount.
Referenced by System.Threading.PortableThreadPool.GateThread.CreateGateThread().