Terraria: System.Threading.PortableThreadPool.GateThread.CreateGateThread
CreateGateThread()
static void System.Threading.PortableThreadPool.GateThread.CreateGateThread (PortableThreadPool threadPoolInstance) inline static private
Definition at line 299 of file PortableThreadPool.cs.
        {
            bool flag = false;
            try
            {
                Thread thread = new Thread(GateThreadStart, 262144)
                {
                    IsThreadPoolThread = true,
                    IsBackground = true,
                    Name = ".NET ThreadPool Gate"
                };
                thread.UnsafeStart();
                flag = true;
            }
            finally
            {
                if (!flag)
                {
                    Interlocked.Exchange(ref threadPoolInstance._separated.gateThreadRunningState, 0);
                }
            }
        }
References System.Threading.PortableThreadPool._separated, System.Threading.Interlocked.Exchange(), System.Threading.PortableThreadPool.CacheLineSeparated.gateThreadRunningState, System.Threading.PortableThreadPool.GateThread.GateThreadStart(), System.Name, and System.Threading.Thread.UnsafeStart().
Referenced by System.Threading.PortableThreadPool.GateThread.EnsureRunningSlow().