Terraria: Terraria.Localization.LanguageManager.Instance
Instance
LanguageManager Terraria.Localization.LanguageManager.Instance = new LanguageManager() static
Referenced by Terraria.Main.DrawMenu(), Terraria.Localization.Language.Exists(), Terraria.Localization.Language.FindAll(), Terraria.Localization.Language.FindAll(), Terraria.Localization.Language.GetCategorySize(), Terraria.Localization.Language.GetText(), Terraria.GameContent.LucyAxeMessage.GetTextForVariation(), Terraria.Localization.Language.GetTextValue(), Terraria.Localization.Language.GetTextValue(), Terraria.Localization.Language.GetTextValue(), Terraria.Localization.Language.GetTextValue(), Terraria.Localization.Language.GetTextValue(), Terraria.Localization.Language.GetTextValueWith(), Terraria.Main.LoadDedConfig(), Terraria.Initializers.LaunchInitializer.LoadServerParameters(), Terraria.Main.LoadSettings(), Terraria.Main.OpenLegacySettings(), Terraria.Localization.Language.RandomFromCategory(), Terraria.Program.RunGame(), Terraria.Localization.Language.SelectRandom(), and Terraria.GameContent.AssetSourceController.UseResourcePacks().