Terraria: Terraria.Localization.LanguageManager.UseSources
UseSources()
void Terraria.Localization.LanguageManager.UseSources (List< IContentSource > sourcesFromLowestToHighest) inline
    {
        string name = ActiveCulture.Name;
        string text = ("Localization" + Path.DirectorySeparatorChar + name).ToLower();
        LoadLanguage(ActiveCulture, processCopyCommands: false);
        foreach (IContentSource item in sourcesFromLowestToHighest)
        {
            foreach (string item2 in item.GetAllAssetsStartingWith(text))
            {
                string extension = item.GetExtension(item2);
                if (!(extension == ".json") && !(extension == ".csv"))
                {
                    continue;
                }
                using Stream stream = item.OpenStream(item2);
                using StreamReader streamReader = new StreamReader(stream);
                string fileText = streamReader.ReadToEnd();
                if (extension == ".json")
                {
                    LoadLanguageFromFileTextJson(fileText, canCreateCategories: false);
                }
                if (extension == ".csv")
                {
                    LoadLanguageFromFileTextCsv(fileText);
                }
            }
        }
        ProcessCopyCommandsInTexts();
        ChatInitializer.PrepareAliases();
    }
References Terraria.Localization.LanguageManager.ActiveCulture, ReLogic.Content.Sources.IContentSource.GetAllAssetsStartingWith(), ReLogic.Content.Sources.IContentSource.GetExtension(), Terraria.Localization.LanguageManager.LoadLanguage(), Terraria.Localization.LanguageManager.LoadLanguageFromFileTextCsv(), Terraria.Localization.LanguageManager.LoadLanguageFromFileTextJson(), Terraria.Localization.GameCulture.Name, ReLogic.Content.Sources.IContentSource.OpenStream(), Terraria.Initializers.ChatInitializer.PrepareAliases(), and Terraria.Localization.LanguageManager.ProcessCopyCommandsInTexts().