Terraria: Terraria.UI.StyleDimension.FromPixelsAndPercent
FromPixelsAndPercent()
static StyleDimension Terraria.UI.StyleDimension.FromPixelsAndPercent (float pixels, float percent) inline static
Definition at line 40 of file StyleDimension.cs.
    {
        return new StyleDimension(pixels, percent);
    }
References Terraria.UI.StyleDimension.StyleDimension().
Referenced by Terraria.GameContent.UI.Elements.EmotesGroupListItem.EmotesGroupListItem(), Terraria.GameContent.UI.Elements.GroupOptionButton< T >.GroupOptionButton(), Terraria.GameContent.UI.Elements.UIBestiaryEntryInfoPage.UIBestiaryEntryInfoPage(), Terraria.GameContent.UI.Elements.UIDifficultyButton.UIDifficultyButton(), Terraria.GameContent.UI.States.UIWorkshopHub.AddDescriptionPanel(), Terraria.GameContent.UI.States.UIWorldCreation.AddDescriptionPanel(), Terraria.GameContent.UI.States.AWorkshopPublishInfoState< TPublishedObjectType >.AddDescriptionPanel(), Terraria.GameContent.UI.States.AWorkshopPublishInfoState< TPublishedObjectType >.AddHorizontalSeparator(), Terraria.GameContent.UI.Elements.UIBestiaryEntryInfoPage.AddInfoToList(), Terraria.GameContent.UI.States.AWorkshopPublishInfoState< TPublishedObjectType >.AddUIList(), Terraria.GameContent.UI.States.UIWorldCreation.AddWorldDifficultyOptions(), Terraria.GameContent.UI.States.UIWorldCreation.AddWorldEvilOptions(), Terraria.GameContent.UI.States.UIWorldCreation.AddWorldSizeOptions(), Terraria.GameContent.UI.Elements.UIResourcePack.BuildChildren(), Terraria.GameContent.UI.States.UICharacterCreation.BuildPage(), Terraria.GameContent.UI.States.UIReportsPage.BuildPage(), Terraria.GameContent.UI.States.UIResourcePackInfoMenu.BuildPage(), Terraria.GameContent.UI.States.UIResourcePackSelectionMenu.BuildPage(), Terraria.GameContent.UI.States.UIWorldCreation.BuildPage(), Terraria.GameContent.UI.States.UICharacterCreation.CreateHSLSlider(), Terraria.GameContent.UI.States.AWorkshopPublishInfoState< TPublishedObjectType >.CreateInsturctionsPanel(), Terraria.GameContent.UI.States.UIResourcePackSelectionMenu.CreateOffsetButton(), Terraria.GameContent.UI.States.UIResourcePackSelectionMenu.CreatePackInfoButton(), Terraria.GameContent.UI.States.UIResourcePackSelectionMenu.CreatePackToggleButton(), Terraria.GameContent.UI.States.AWorkshopPublishInfoState< TPublishedObjectType >.CreatePreviewImageSelectionPanel(), Terraria.GameContent.UI.States.AWorkshopPublishInfoState< TPublishedObjectType >.CreatePublicSettingsRow(), Terraria.GameContent.UI.States.AWorkshopPublishInfoState< TPublishedObjectType >.CreateSteamDisclaimer(), Terraria.GameContent.UI.States.AWorkshopPublishInfoState< TPublishedObjectType >.CreateStylizedCategoryPanel(), Terraria.GameContent.UI.States.AWorkshopPublishInfoState< TPublishedObjectType >.CreateTagOptionsPanel(), Terraria.GameContent.UI.States.UICharacterCreation.MakeBackAndCreatebuttons(), Terraria.GameContent.UI.States.UIWorldCreation.MakeBackAndCreatebuttons(), Terraria.GameContent.UI.States.UICharacterCreation.MakeCategoriesBar(), Terraria.GameContent.UI.States.UICharacterCreation.MakeCharPreview(), Terraria.GameContent.UI.States.UICharacterCreation.MakeClothStylesMenu(), Terraria.GameContent.UI.States.UIBestiaryTest.MakeExitButton(), Terraria.GameContent.UI.States.UIWorkshopHub.MakeFancyButton(), Terraria.GameContent.UI.States.UICharacterCreation.MakeHairsylesMenu(), Terraria.GameContent.UI.States.UICharacterCreation.MakeHSLMenu(), Terraria.GameContent.UI.States.UICharacterCreation.MakeInfoMenu(), Terraria.GameContent.UI.States.UIWorldCreation.MakeInfoMenu(), Terraria.GameContent.UI.States.UIReportsPage.PopulateLogs(), Terraria.GameContent.UI.States.UIResourcePackSelectionMenu.PopulatePackList(), Terraria.GameContent.Bestiary.FlavorTextBestiaryInfoElement.ProvideUIElement(), Terraria.GameContent.Bestiary.NPCStatsReportInfoElement.ProvideUIElement(), Terraria.GameContent.Bestiary.UnlockProgressDisplayBestiaryInfoElement.ProvideUIElement(), Terraria.GameContent.UI.Elements.GroupOptionButton< T >.SetText(), and Terraria.GameContent.UI.Elements.UIIconTextButton.SetText().