Terraria: Terraria.UI.StyleDimension.StyleDimension
StyleDimension()
Terraria.UI.StyleDimension.StyleDimension (float pixels, float precent) inline
Definition at line 13 of file StyleDimension.cs.
    {
        Pixels = pixels;
        Precent = precent;
    }
References Terraria.UI.StyleDimension.Pixels, and Terraria.UI.StyleDimension.Precent.
Referenced by Terraria.UI.StyleDimension.FromPercent(), Terraria.UI.StyleDimension.FromPixels(), and Terraria.UI.StyleDimension.FromPixelsAndPercent().