Terraria: Terraria.UI.StyleDimension.FromPixels
FromPixels()
static StyleDimension Terraria.UI.StyleDimension.FromPixels (float pixels) inline static
References Terraria.UI.StyleDimension.StyleDimension().
Referenced by Terraria.GameContent.UI.Elements.EmotesGroupListItem.EmotesGroupListItem(), Terraria.GameContent.UI.Elements.GroupOptionButton< T >.GroupOptionButton(), Terraria.GameContent.UI.Elements.UICharacterNameButton.UICharacterNameButton(), Terraria.GameContent.UI.Elements.UIClothStyleButton.UIClothStyleButton(), Terraria.GameContent.UI.Elements.UIDifficultyButton.UIDifficultyButton(), Terraria.GameContent.UI.Elements.UIHairStyleButton.UIHairStyleButton(), Terraria.GameContent.UI.Elements.UIIconTextButton.UIIconTextButton(), Terraria.GameContent.UI.Elements.UIResourcePack.UIResourcePack(), Terraria.GameContent.UI.States.UIWorkshopHub.AddDescriptionPanel(), Terraria.GameContent.UI.States.UIWorldCreation.AddDescriptionPanel(), Terraria.GameContent.UI.States.AWorkshopPublishInfoState< TPublishedObjectType >.AddDescriptionPanel(), Terraria.GameContent.UI.States.UIWorkshopHub.AddHorizontalSeparator(), Terraria.GameContent.UI.States.UIWorldCreation.AddHorizontalSeparator(), Terraria.GameContent.UI.States.AWorkshopPublishInfoState< TPublishedObjectType >.AddHorizontalSeparator(), Terraria.GameContent.UI.States.AWorkshopPublishInfoState< TPublishedObjectType >.AddUIList(), Terraria.GameContent.UI.Elements.UIResourcePack.BuildChildren(), Terraria.GameContent.UI.States.UICharacterCreation.BuildPage(), Terraria.GameContent.UI.States.UIReportsPage.BuildPage(), Terraria.GameContent.UI.States.UIResourcePackInfoMenu.BuildPage(), Terraria.GameContent.UI.States.UIWorldCreation.BuildPage(), Terraria.GameContent.UI.States.AWorkshopPublishInfoState< TPublishedObjectType >.CreateInsturctionsPanel(), Terraria.GameContent.UI.States.AWorkshopPublishInfoState< TPublishedObjectType >.CreateSteamDisclaimer(), Terraria.GameContent.UI.States.AWorkshopPublishInfoState< TPublishedObjectType >.CreateStylizedCategoryPanel(), Terraria.GameContent.UI.States.UIEmotesMenu.InitializePage(), Terraria.GameContent.UI.States.UICharacterCreation.MakeBackAndCreatebuttons(), Terraria.GameContent.UI.States.UIWorldCreation.MakeBackAndCreatebuttons(), Terraria.GameContent.UI.States.UICharacterCreation.MakeCategoriesBar(), Terraria.GameContent.UI.States.UICharacterCreation.MakeCharPreview(), Terraria.GameContent.UI.States.UICharacterCreation.MakeClothStylesMenu(), Terraria.GameContent.UI.States.UIBestiaryTest.MakeExitButton(), Terraria.GameContent.UI.States.UIWorkshopHub.MakeFancyButton(), Terraria.GameContent.UI.States.UICharacterCreation.MakeHairsylesMenu(), Terraria.GameContent.UI.States.UICharacterCreation.MakeInfoMenu(), Terraria.GameContent.UI.States.UIWorldCreation.MakeInfoMenu(), Terraria.GameContent.UI.States.UIReportsPage.PopulateLogs(), Terraria.GameContent.UI.Elements.UICharacterNameButton.SetContents(), Terraria.GameContent.UI.Elements.GroupOptionButton< T >.SetText(), and Terraria.GameContent.UI.Elements.UIIconTextButton.SetText().