Terraria: Terraria.UI.StyleDimension.FromPercent
FromPercent()
static StyleDimension Terraria.UI.StyleDimension.FromPercent (float percent) inline static
    {
        return new StyleDimension(0f, percent);
    }
References Terraria.UI.StyleDimension.StyleDimension().
Referenced by Terraria.GameContent.UI.Elements.UIResourcePack.UIResourcePack(), Terraria.GameContent.UI.States.UIWorkshopHub.AddHorizontalSeparator(), Terraria.GameContent.UI.States.UIWorldCreation.AddHorizontalSeparator(), Terraria.GameContent.UI.States.UIWorldCreation.AddWorldDifficultyOptions(), Terraria.GameContent.UI.States.UIWorldCreation.AddWorldEvilOptions(), Terraria.GameContent.UI.States.UIWorldCreation.AddWorldSizeOptions(), Terraria.GameContent.UI.States.UICharacterCreation.BuildPage(), Terraria.GameContent.UI.States.UIWorldCreation.BuildPage(), Terraria.GameContent.UI.States.UIResourcePackSelectionMenu.CreateOffsetButton(), Terraria.GameContent.UI.States.UIResourcePackSelectionMenu.CreatePackToggleButton(), Terraria.GameContent.UI.States.AWorkshopPublishInfoState< TPublishedObjectType >.CreatePublicSettingsRow(), and Terraria.GameContent.UI.States.AWorkshopPublishInfoState< TPublishedObjectType >.CreateTagOptionsPanel().