Terraria: FinalFractalHelper.FinalFractalProfile.FinalFractalProfile
FinalFractalProfile()
FinalFractalHelper.FinalFractalProfile.FinalFractalProfile (float fullBladeLength, Color color) inline
         {
             trailWidth = fullBladeLength / 2f;
             trailColor = color;
             widthMethod = null;
             colorMethod = null;
             dustMethod = null;
             widthMethod = StripWidth;
             colorMethod = StripColors;
             dustMethod = StripDust;
         }
References FinalFractalHelper.FinalFractalProfile.colorMethod, FinalFractalHelper.FinalFractalProfile.dustMethod, FinalFractalHelper.FinalFractalProfile.StripColors(), FinalFractalHelper.FinalFractalProfile.StripDust(), FinalFractalHelper.FinalFractalProfile.StripWidth(), FinalFractalHelper.FinalFractalProfile.trailColor, FinalFractalHelper.FinalFractalProfile.trailWidth, and FinalFractalHelper.FinalFractalProfile.widthMethod.