Terraria: UICharacter.DrawPets
DrawPets()
void UICharacter.DrawPets (SpriteBatch spriteBatch) inline
     {
         CalculatedStyle dimensions = GetDimensions();
         Vector2 playerPosition = GetPlayerPosition(ref dimensions);
         for (int i = 0; i < _petProjectiles.Length; i++)
         {
             Projectile projectile = _petProjectiles[i];
             Vector2 vector = playerPosition + new Vector2(0f, _player.height) + new Vector2(20f, 0f) + new Vector2(0f, -projectile.height);
             projectile.position = vector + Main.screenPosition;
             projectile.velocity = new Vector2(0.1f, 0f);
             projectile.direction = 1;
             projectile.owner = Main.myPlayer;
             ProjectileID.Sets.CharacterPreviewAnimations[projectile.type].ApplyTo(projectile, _animated);
             Player player = Main.player[Main.myPlayer];
             Main.player[Main.myPlayer] = _player;
             Main.instance.DrawProjDirect(projectile);
             Main.player[Main.myPlayer] = player;
         }
         spriteBatch.End();
         spriteBatch.Begin(SpriteSortMode.Immediate, spriteBatch.GraphicsDevice.BlendState, spriteBatch.GraphicsDevice.SamplerStates[0], spriteBatch.GraphicsDevice.DepthStencilState, spriteBatch.GraphicsDevice.RasterizerState, null, Main.UIScaleMatrix);
     }
References _animated, _petProjectiles, _player, SettingsForCharacterPreview.ApplyTo(), ProjectileID.Sets.CharacterPreviewAnimations, Entity.direction, Main.DrawProjDirect(), UIElement.GetDimensions(), GetPlayerPosition(), Entity.height, Main.instance, Main.myPlayer, Projectile.owner, Main.player, Entity.position, Main.screenPosition, Projectile.type, Main.UIScaleMatrix, and Entity.velocity.
Referenced by DrawSelf().