Terraria: UICharacter.UICharacter
UICharacter()
UICharacter.UICharacter (Player player, bool animated = false, bool hasBackPanel = true, float characterScale = 1f, bool useAClone = false) inline
     {
         _player = player;
         if (useAClone)
         {
             _player = player.SerializedClone();
             _player.dead = false;
             _player.PlayerFrame();
         }
         Width.Set(59f, 0f);
         Height.Set(58f, 0f);
         _texture = Main.Assets.Request<Texture2D>("Images/UI/PlayerBackground", (AssetRequestMode)1);
         UseImmediateMode = true;
         _animated = animated;
         _drawsBackPanel = hasBackPanel;
         _characterScale = characterScale;
         OverrideSamplerState = SamplerState.PointClamp;
         _petProjectiles = NoPets;
         PreparePetProjectiles();
     }
References _animated, _characterScale, _drawsBackPanel, _petProjectiles, _player, _texture, Main.Assets, Player.dead, UIElement.Height, NoPets, UIElement.OverrideSamplerState, Player.PlayerFrame(), PreparePetProjectiles(), Player.SerializedClone(), StyleDimension.Set(), UIElement.UseImmediateMode, and UIElement.Width.