Terraria: System.Linq.Expressions.Interpreter.EnterTryCatchFinallyInstruction.Run
Run()
override int System.Linq.Expressions.Interpreter.EnterTryCatchFinallyInstruction.Run (InterpretedFrame frame) inline
Definition at line 56 of file EnterTryCatchFinallyInstruction.cs.
    {
        if (_hasFinally)
        {
            frame.PushContinuation(_labelIndex);
        }
        int instructionIndex = frame.InstructionIndex;
        frame.InstructionIndex++;
        Instruction[] instructions = frame.Interpreter.Instructions.Instructions;
        ExceptionHandler handler;
        object unwrappedException;
        try
        {
            int num = frame.InstructionIndex;
            while (num >= _tryHandler.TryStartIndex && num < _tryHandler.TryEndIndex)
            {
                num = (frame.InstructionIndex = num + instructions[num].Run(frame));
            }
            if (num == _tryHandler.GotoEndTargetIndex)
            {
                frame.InstructionIndex += instructions[num].Run(frame);
            }
        }
        catch (Exception exception) when (_tryHandler.HasHandler(frame, exception, out handler, out unwrappedException))
        {
            frame.InstructionIndex += frame.Goto(handler.LabelIndex, unwrappedException, gotoExceptionHandler: true);
            bool flag = false;
            try
            {
                int num2 = frame.InstructionIndex;
                while (num2 >= handler.HandlerStartIndex && num2 < handler.HandlerEndIndex)
                {
                    num2 = (frame.InstructionIndex = num2 + instructions[num2].Run(frame));
                }
                if (num2 == _tryHandler.GotoEndTargetIndex)
                {
                    frame.InstructionIndex += instructions[num2].Run(frame);
                }
            }
            catch (RethrowException)
            {
                flag = true;
            }
            if (flag)
            {
                throw;
            }
        }
        finally
        {
            if (_tryHandler.IsFinallyBlockExist)
            {
                int num3 = (frame.InstructionIndex = _tryHandler.FinallyStartIndex);
                while (num3 >= _tryHandler.FinallyStartIndex && num3 < _tryHandler.FinallyEndIndex)
                {
                    num3 = (frame.InstructionIndex = num3 + instructions[num3].Run(frame));
                }
            }
        }
        return frame.InstructionIndex - instructionIndex;
    }
References System.Linq.Expressions.Interpreter.EnterTryCatchFinallyInstruction._hasFinally, System.Linq.Expressions.Interpreter.IndexedBranchInstruction._labelIndex, System.Linq.Expressions.Interpreter.EnterTryCatchFinallyInstruction._tryHandler, System.exception, System.Linq.Expressions.Interpreter.TryCatchFinallyHandler.FinallyEndIndex, System.Linq.Expressions.Interpreter.TryCatchFinallyHandler.FinallyStartIndex, System.Linq.Expressions.Interpreter.InterpretedFrame.Goto(), System.Linq.Expressions.Interpreter.TryCatchFinallyHandler.GotoEndTargetIndex, System.Linq.Expressions.Interpreter.ExceptionHandler.HandlerEndIndex, System.Linq.Expressions.Interpreter.ExceptionHandler.HandlerStartIndex, System.Linq.Expressions.Interpreter.TryCatchFinallyHandler.HasHandler(), System.Linq.Expressions.Interpreter.InterpretedFrame.InstructionIndex, System.Linq.Expressions.Interpreter.InstructionArray.Instructions, System.Linq.Expressions.Interpreter.Interpreter.Instructions, System.Linq.Expressions.Interpreter.InterpretedFrame.Interpreter, System.Linq.Expressions.Interpreter.TryCatchFinallyHandler.IsFinallyBlockExist, System.Linq.Expressions.Interpreter.ExceptionHandler.LabelIndex, System.Linq.Expressions.Interpreter.InterpretedFrame.PushContinuation(), System.Linq.Expressions.Interpreter.Instruction.Run(), System.Linq.Expressions.Interpreter.TryCatchFinallyHandler.TryEndIndex, and System.Linq.Expressions.Interpreter.TryCatchFinallyHandler.TryStartIndex.