Terraria: Terraria.Graphics.SpriteRenderTargetHelper.GetHighsAndLowsOf
GetHighsAndLowsOf() [2/2]
static void Terraria.Graphics.SpriteRenderTargetHelper.GetHighsAndLowsOf (ref Vector2 lowest, ref Vector2 highest, ref DrawData cdd, ref Vector2 pos, ref Vector2 origin, Vector2 corner) inline static
Definition at line 51 of file SpriteRenderTargetHelper.cs.
    {
        Vector2 corner2 = GetCorner(ref cdd, ref pos, ref origin, corner);
        lowest = Vector2.Min(lowest, corner2);
        highest = Vector2.Max(highest, corner2);
    }
References Terraria.Graphics.SpriteRenderTargetHelper.GetCorner(), Microsoft.Xna.Framework.Vector2.Max(), and Microsoft.Xna.Framework.Vector2.Min().