Terraria: System.Threading.ThreadPoolWorkQueue.Enqueue
Enqueue()
void System.Threading.ThreadPoolWorkQueue.Enqueue (object callback, bool forceGlobal) inline
Definition at line 430 of file ThreadPoolWorkQueue.cs.
    {
        if (loggingEnabled && FrameworkEventSource.Log.IsEnabled())
        {
            FrameworkEventSource.Log.ThreadPoolEnqueueWorkObject(callback);
        }
        ThreadPoolWorkQueueThreadLocals threadPoolWorkQueueThreadLocals = null;
        if (!forceGlobal)
        {
            threadPoolWorkQueueThreadLocals = ThreadPoolWorkQueueThreadLocals.threadLocals;
        }
        if (threadPoolWorkQueueThreadLocals != null)
        {
            threadPoolWorkQueueThreadLocals.workStealingQueue.LocalPush(callback);
        }
        else
        {
            workItems.Enqueue(callback);
        }
        EnsureThreadRequested();
    }
References System.Collections.Concurrent.ConcurrentQueue< T >.Enqueue(), System.Threading.ThreadPoolWorkQueue.EnsureThreadRequested(), System.Diagnostics.Tracing.FrameworkEventSource.Log, System.Threading.ThreadPoolWorkQueue.loggingEnabled, System.Threading.ThreadPoolWorkQueueThreadLocals.threadLocals, System.Threading.ThreadPoolWorkQueue.workItems, and System.Threading.ThreadPoolWorkQueueThreadLocals.workStealingQueue.
Referenced by System.Threading.ThreadPoolWorkQueueThreadLocals.TransferLocalWork().