Terraria: System.Threading.ThreadPoolWorkQueue.Dequeue
Dequeue()
object System.Threading.ThreadPoolWorkQueue.Dequeue (ThreadPoolWorkQueueThreadLocals tl, ref bool missedSteal) inline
Definition at line 457 of file ThreadPoolWorkQueue.cs.
    {
        WorkStealingQueue workStealingQueue = tl.workStealingQueue;
        object result;
        if ((result = workStealingQueue.LocalPop()) == null && !workItems.TryDequeue(out result))
        {
            WorkStealingQueue[] queues = WorkStealingQueueList.Queues;
            int num = queues.Length;
            int num2 = num - 1;
            uint num3 = tl.random.NextUInt32() % (uint)num;
            while (num > 0)
            {
                num3 = ((num3 < num2) ? (num3 + 1) : 0u);
                WorkStealingQueue workStealingQueue2 = queues[num3];
                if (workStealingQueue2 != workStealingQueue && workStealingQueue2.CanSteal)
                {
                    result = workStealingQueue2.TrySteal(ref missedSteal);
                    if (result != null)
                    {
                        return result;
                    }
                }
                num--;
            }
            if (ThreadPool.SupportsTimeSensitiveWorkItems)
            {
                result = TryDequeueTimeSensitiveWorkItem();
            }
        }
        return result;
    }
References System.Threading.ThreadPoolWorkQueue.WorkStealingQueue.CanSteal, System.Threading.ThreadPoolWorkQueue.WorkStealingQueue.LocalPop(), System.Threading.ThreadPoolWorkQueue.WorkStealingQueueList.Queues, System.Threading.ThreadPoolWorkQueueThreadLocals.random, System.Threading.ThreadPool.SupportsTimeSensitiveWorkItems, System.Collections.Concurrent.ConcurrentQueue< T >.TryDequeue(), System.Threading.ThreadPoolWorkQueue.TryDequeueTimeSensitiveWorkItem(), System.Threading.ThreadPoolWorkQueue.WorkStealingQueue.TrySteal(), System.Threading.ThreadPoolWorkQueue.workItems, and System.Threading.ThreadPoolWorkQueueThreadLocals.workStealingQueue.
Referenced by System.Threading.ThreadPoolWorkQueue.Dispatch().