Terraria: System.Threading.ThreadPoolWorkQueue.Dispatch
Dispatch()
static bool System.Threading.ThreadPoolWorkQueue.Dispatch () inline static package
Definition at line 489 of file ThreadPoolWorkQueue.cs.
    {
        ThreadPoolWorkQueue s_workQueue = ThreadPool.s_workQueue;
        s_workQueue.MarkThreadRequestSatisfied();
        s_workQueue.RefreshLoggingEnabled();
        bool flag = true;
        try
        {
            ThreadPoolWorkQueue threadPoolWorkQueue = s_workQueue;
            ThreadPoolWorkQueueThreadLocals orCreateThreadLocals = threadPoolWorkQueue.GetOrCreateThreadLocals();
            object threadLocalCompletionCountObject = orCreateThreadLocals.threadLocalCompletionCountObject;
            Thread currentThread = orCreateThreadLocals.currentThread;
            currentThread._executionContext = null;
            currentThread._synchronizationContext = null;
            int num = Environment.TickCount;
            object obj = null;
            while (true)
            {
                if (obj == null)
                {
                    bool missedSteal = false;
                    obj = threadPoolWorkQueue.Dequeue(orCreateThreadLocals, ref missedSteal);
                    if (obj == null)
                    {
                        flag = missedSteal;
                        return true;
                    }
                }
                if (threadPoolWorkQueue.loggingEnabled && FrameworkEventSource.Log.IsEnabled())
                {
                    FrameworkEventSource.Log.ThreadPoolDequeueWorkObject(obj);
                }
                threadPoolWorkQueue.EnsureThreadRequested();
                if (ThreadPool.EnableWorkerTracking)
                {
                    DispatchWorkItemWithWorkerTracking(obj, currentThread);
                }
                else
                {
                    DispatchWorkItem(obj, currentThread);
                }
                obj = null;
                ExecutionContext.ResetThreadPoolThread(currentThread);
                currentThread.ResetThreadPoolThread();
                int tickCount = Environment.TickCount;
                if (!ThreadPool.NotifyWorkItemComplete(threadLocalCompletionCountObject, tickCount))
                {
                    orCreateThreadLocals.TransferLocalWork();
                    return false;
                }
                if ((uint)(tickCount - num) >= 30u)
                {
                    if (!ThreadPool.SupportsTimeSensitiveWorkItems)
                    {
                        break;
                    }
                    num = tickCount;
                    threadPoolWorkQueue.RefreshLoggingEnabled();
                    obj = threadPoolWorkQueue.TryDequeueTimeSensitiveWorkItem();
                }
            }
            return true;
        }
        finally
        {
            if (flag)
            {
                s_workQueue.EnsureThreadRequested();
            }
        }
    }
References System.Threading.ThreadPoolWorkQueueThreadLocals.currentThread, System.Threading.ThreadPoolWorkQueue.Dequeue(), System.Threading.ThreadPoolWorkQueue.DispatchWorkItem(), System.Threading.ThreadPoolWorkQueue.DispatchWorkItemWithWorkerTracking(), System.Threading.ThreadPool.EnableWorkerTracking, System.Threading.ThreadPoolWorkQueue.EnsureThreadRequested(), System.Threading.ThreadPoolWorkQueue.GetOrCreateThreadLocals(), System.Diagnostics.Tracing.FrameworkEventSource.Log, System.Threading.ThreadPoolWorkQueue.loggingEnabled, System.Threading.ThreadPoolWorkQueue.MarkThreadRequestSatisfied(), System.Threading.ThreadPool.NotifyWorkItemComplete(), System.obj, System.Threading.ThreadPoolWorkQueue.RefreshLoggingEnabled(), System.Threading.Thread.ResetThreadPoolThread(), System.Threading.ExecutionContext.ResetThreadPoolThread(), System.Threading.ThreadPool.s_workQueue, System.Threading.ThreadPool.SupportsTimeSensitiveWorkItems, System.Threading.ThreadPoolWorkQueueThreadLocals.threadLocalCompletionCountObject, System.Environment.TickCount, System.Threading.ThreadPoolWorkQueueThreadLocals.TransferLocalWork(), and System.Threading.ThreadPoolWorkQueue.TryDequeueTimeSensitiveWorkItem().
Referenced by System.Threading._ThreadPoolWaitCallback.PerformWaitCallback(), and System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart().