Terraria: System.Threading.ThreadPoolWorkQueue.RefreshLoggingEnabled
RefreshLoggingEnabled()
void System.Threading.ThreadPoolWorkQueue.RefreshLoggingEnabled () inline
Definition at line 361 of file ThreadPoolWorkQueue.cs.
    {
        if (!FrameworkEventSource.Log.IsEnabled())
        {
            if (loggingEnabled)
            {
                loggingEnabled = false;
            }
        }
        else
        {
            RefreshLoggingEnabledFull();
        }
    }
References System.Diagnostics.Tracing.FrameworkEventSource.Log, System.Threading.ThreadPoolWorkQueue.loggingEnabled, and System.Threading.ThreadPoolWorkQueue.RefreshLoggingEnabledFull().
Referenced by System.Threading.ThreadPoolWorkQueue.ThreadPoolWorkQueue(), and System.Threading.ThreadPoolWorkQueue.Dispatch().