Terraria: System.Globalization.TextInfo.ToUpper
ToUpper() [1/2]
char System.Globalization.TextInfo.ToUpper (char c) inline
Definition at line 414 of file TextInfo.cs.
    {
        if (GlobalizationMode.Invariant)
        {
            return InvariantModeCasing.ToUpper(c);
        }
        if (UnicodeUtility.IsAsciiCodePoint(c) && IsAsciiCasingSameAsInvariant)
        {
            return ToUpperAsciiInvariant(c);
        }
        return ChangeCase(c, toUpper: true);
    }
References System.Globalization.TextInfo.ChangeCase(), System.Runtime.Serialization.Dictionary, System.Globalization.GlobalizationMode.Invariant, System.Globalization.TextInfo.IsAsciiCasingSameAsInvariant, System.Text.UnicodeUtility.IsAsciiCodePoint(), System.Globalization.InvariantModeCasing.ToUpper(), and System.Globalization.TextInfo.ToUpperAsciiInvariant().
Referenced by System.Globalization.TextInfo.AddTitlecaseLetter().