Terraria: System.Globalization.TextInfo.ChangeCaseCommon< TConversion >
ChangeCaseCommon< TConversion >() [3/3]
unsafe string System.Globalization.TextInfo.ChangeCaseCommon< TConversion > (string source) inline private
Type Constraints
TConversion : struct
Definition at line 299 of file TextInfo.cs.
                                                                                         : struct
    {
        bool flag = typeof(TConversion) == typeof(ToUpperConversion);
        if (source.Length == 0)
        {
            return string.Empty;
        }
        fixed (char* ptr = source)
        {
            nuint num = 0u;
            if (IsAsciiCasingSameAsInvariant)
            {
                if (source.Length < 2)
                {
                    goto IL_0095;
                }
                nuint num2 = (uint)(source.Length - 2);
                while (true)
                {
                    uint value = Unsafe.ReadUnaligned<uint>(ptr + num);
                    if (!Utf16Utility.AllCharsInUInt32AreAscii(value))
                    {
                        break;
                    }
                    if (!(flag ? Utf16Utility.UInt32ContainsAnyLowercaseAsciiChar(value) : Utf16Utility.UInt32ContainsAnyUppercaseAsciiChar(value)))
                    {
                        num += 2;
                        if (num <= num2)
{
                            continue;
                        }
                        goto IL_0095;
                    }
                    goto IL_00d1;
                }
            }
            goto IL_0121;
            IL_0121:
            string text = string.FastAllocateString(source.Length);
            if (num != 0)
            {
                Span<char> destination = new Span<char>(ref text.GetRawStringData(), text.Length);
                source.AsSpan(0, (int)num).CopyTo(destination);
            }
            fixed (char* ptr2 = text)
            {
                ChangeCaseCore(ptr + num, source.Length - (int)num, ptr2 + num, text.Length - (int)num, flag);
            }
            return text;
            IL_0095:
            if (((uint)source.Length & (true ? 1u : 0u)) != 0)
            {
                uint num3 = ptr[num];
                if (num3 > 127)
                {
                    goto IL_0121;
                }
                if (flag ? (num3 - 97 <= 25) : (num3 - 65 <= 25))
                {
                    goto IL_00d1;
                }
            }
            return source;
            IL_00d1:
            string text2 = string.FastAllocateString(source.Length);
            Span<char> destination2 = new Span<char>(ref text2.GetRawStringData(), text2.Length);
            source.AsSpan(0, (int)num).CopyTo(destination2);
            ChangeCaseCommon<TConversion>(source.AsSpan((int)num), destination2.Slice((int)num));
            return text2;
        }
    }
References System.Text.Unicode.Utf16Utility.AllCharsInUInt32AreAscii(), System.Globalization.TextInfo.ChangeCaseCommon< TConversion >(), System.Globalization.TextInfo.ChangeCaseCore(), System.destination, System.Runtime.Serialization.Dictionary, System.Globalization.TextInfo.IsAsciiCasingSameAsInvariant, System.source, System.text, System.Text.Unicode.Utf16Utility.UInt32ContainsAnyLowercaseAsciiChar(), System.Text.Unicode.Utf16Utility.UInt32ContainsAnyUppercaseAsciiChar(), and System.value.