Terraria: System.Globalization.TextInfo.ToUpperInvariant
ToUpperInvariant()
static char System.Globalization.TextInfo.ToUpperInvariant (char c) inline static package
Definition at line 427 of file TextInfo.cs.
    {
        if (GlobalizationMode.Invariant)
        {
            return InvariantModeCasing.ToUpper(c);
        }
        if (UnicodeUtility.IsAsciiCodePoint(c))
        {
            return ToUpperAsciiInvariant(c);
        }
        return Invariant.ChangeCase(c, toUpper: true);
    }
References System.Runtime.Serialization.Dictionary, System.Globalization.GlobalizationMode.Invariant, System.Globalization.TextInfo.Invariant, System.Text.UnicodeUtility.IsAsciiCodePoint(), System.Globalization.InvariantModeCasing.ToUpper(), and System.Globalization.TextInfo.ToUpperAsciiInvariant().
Referenced by System.Char.ToUpperInvariant().