Terraria: System.Globalization.TextInfo.TextInfo
TextInfo() [1/2]
System.Globalization.TextInfo.TextInfo (CultureData cultureData) inline package
Definition at line 99 of file TextInfo.cs.
    {
        _cultureData = cultureData;
        _cultureName = _cultureData.CultureName;
        _textInfoName = _cultureData.TextInfoName;
        if (GlobalizationMode.UseNls)
        {
            _sortHandle = CompareInfo.NlsGetSortHandle(_textInfoName);
        }
    }
References System.Globalization.TextInfo._cultureData, System.Globalization.TextInfo._cultureName, System.Globalization.TextInfo._sortHandle, System.Globalization.TextInfo._textInfoName, System.Globalization.CultureData.CultureName, System.Runtime.Serialization.Dictionary, System.Globalization.CompareInfo.NlsGetSortHandle(), System.Globalization.CultureData.TextInfoName, and System.Globalization.GlobalizationMode.UseNls.
Referenced by System.Text.RegularExpressions.RegexInterpreter.RegexInterpreter(), System.Globalization.TextInfo.Clone(), and System.Globalization.TextInfo.ReadOnly().