Terraria: System.Globalization.TextInfo.ToLower
ToLower() [1/2]
char System.Globalization.TextInfo.ToLower (char c) inline
Definition at line 156 of file TextInfo.cs.
    {
        if (GlobalizationMode.Invariant)
        {
            return InvariantModeCasing.ToLower(c);
        }
        if (UnicodeUtility.IsAsciiCodePoint(c) && IsAsciiCasingSameAsInvariant)
        {
            return ToLowerAsciiInvariant(c);
        }
        return ChangeCase(c, toUpper: false);
    }
References System.Globalization.TextInfo.ChangeCase(), System.Runtime.Serialization.Dictionary, System.Globalization.GlobalizationMode.Invariant, System.Globalization.TextInfo.IsAsciiCasingSameAsInvariant, System.Text.UnicodeUtility.IsAsciiCodePoint(), System.Globalization.InvariantModeCasing.ToLower(), and System.Globalization.TextInfo.ToLowerAsciiInvariant().
Referenced by System.Text.RegularExpressions.RegexInterpreter.FindFirstChar(), System.Text.RegularExpressions.RegexInterpreter.Forwardcharnext(), System.Text.RegularExpressions.RegexBoyerMoore.IsMatch(), System.Text.RegularExpressions.RegexInterpreter.MatchRef(), System.Text.RegularExpressions.RegexInterpreter.MatchString(), System.Text.RegularExpressions.RegexBoyerMoore.Scan(), and System.Globalization.TextInfo.ToTitleCase().