Terraria: System.Globalization.TextInfo.ChangeCaseCommon< TConversion >
ChangeCaseCommon< TConversion >() [2/3]
unsafe void System.Globalization.TextInfo.ChangeCaseCommon< TConversion > (ref char source, ref char destination, int charCount) inline private
Type Constraints
TConversion : struct
Definition at line 220 of file TextInfo.cs.
                                                                                                                              : struct
    {
        bool flag = typeof(TConversion) == typeof(ToUpperConversion);
        if (charCount == 0)
        {
            return;
        }
        fixed (char* ptr = &source)
        {
            fixed (char* ptr2 = &destination)
            {
                nuint num = 0u;
                if (IsAsciiCasingSameAsInvariant)
                {
                    if (charCount < 4)
                    {
                        goto IL_00e5;
                    }
                    nuint num2 = (uint)(charCount - 4);
                    while (true)
                    {
                        uint value = Unsafe.ReadUnaligned<uint>(ptr + num);
                        if (!Utf16Utility.AllCharsInUInt32AreAscii(value))
{
                            break;
                        }
                        value = (flag ? Utf16Utility.ConvertAllAsciiCharsInUInt32ToUppercase(value) : Utf16Utility.ConvertAllAsciiCharsInUInt32ToLowercase(value));
                        Unsafe.WriteUnaligned(ptr2 + num, value);
                        value = Unsafe.ReadUnaligned<uint>(ptr + num + 2);
                        if (Utf16Utility.AllCharsInUInt32AreAscii(value))
{
                            value = (flag ? Utf16Utility.ConvertAllAsciiCharsInUInt32ToUppercase(value) : Utf16Utility.ConvertAllAsciiCharsInUInt32ToLowercase(value));
                            Unsafe.WriteUnaligned(ptr2 + num + 2, value);
                            num += 4;
                            if (num <= num2)
{
                                continue;
                            }
                            goto IL_00e5;
                        }
                        num += 2;
                        break;
                    }
                    goto IL_0171;
                }
                goto IL_0178;
                IL_0178:
                ChangeCaseCore(ptr + num, charCount, ptr2 + num, charCount, flag);
                return;
                IL_0171:
                charCount -= (int)num;
                goto IL_0178;
                IL_00e5:
                if (((uint)charCount & 2u) != 0)
                {
                    uint value2 = Unsafe.ReadUnaligned<uint>(ptr + num);
                    if (!Utf16Utility.AllCharsInUInt32AreAscii(value2))
                    {
                        goto IL_0171;
                    }
                    value2 = (flag ? Utf16Utility.ConvertAllAsciiCharsInUInt32ToUppercase(value2) : Utf16Utility.ConvertAllAsciiCharsInUInt32ToLowercase(value2));
                    Unsafe.WriteUnaligned(ptr2 + num, value2);
                    num += 2;
                }
                if (((uint)charCount & (true ? 1u : 0u)) != 0)
                {
                    uint num3 = ptr[num];
                    if (num3 <= 127)
                    {
                        num3 = (flag ? Utf16Utility.ConvertAllAsciiCharsInUInt32ToUppercase(num3) : Utf16Utility.ConvertAllAsciiCharsInUInt32ToLowercase(num3));
                        ptr2[num] = (char)num3;
                        return;
                    }
                    goto IL_0171;
                }
            }
        }
    }
References System.Text.Unicode.Utf16Utility.AllCharsInUInt32AreAscii(), System.Globalization.TextInfo.ChangeCaseCore(), System.charCount, System.Text.Unicode.Utf16Utility.ConvertAllAsciiCharsInUInt32ToLowercase(), System.Text.Unicode.Utf16Utility.ConvertAllAsciiCharsInUInt32ToUppercase(), System.destination, System.Runtime.Serialization.Dictionary, System.Globalization.TextInfo.IsAsciiCasingSameAsInvariant, System.source, and System.value.