Terraria: System.Globalization.TextInfo.ToTitleCase
ToTitleCase()
string System.Globalization.TextInfo.ToTitleCase (string str) inline
Definition at line 489 of file TextInfo.cs.
    {
        if (str == null)
        {
            throw new ArgumentNullException("str");
        }
        if (str.Length == 0)
        {
            return str;
        }
        StringBuilder result = new StringBuilder();
        string text = null;
        bool flag = CultureName.StartsWith("nl-", StringComparison.OrdinalIgnoreCase);
        int num;
        for (num = 0; num < str.Length; num++)
        {
            UnicodeCategory unicodeCategoryInternal = CharUnicodeInfo.GetUnicodeCategoryInternal(str, num, out var charLength);
            if (char.CheckLetter(unicodeCategoryInternal))
            {
                if (flag && num < str.Length - 1 && (str[num] == 'i' || str[num] == 'I') && (str[num + 1] == 'j' || str[num + 1] == 'J'))
                {
                    result.Append("IJ");
                    num += 2;
                }
                else
                {
                    num = AddTitlecaseLetter(ref result, ref str, num, charLength) + 1;
                }
                int num2 = num;
                bool flag2 = unicodeCategoryInternal == UnicodeCategory.LowercaseLetter;
                while (num < str.Length)
                {
                    unicodeCategoryInternal = CharUnicodeInfo.GetUnicodeCategoryInternal(str, num, out charLength);
                    if (IsLetterCategory(unicodeCategoryInternal))
                    {
                        if (unicodeCategoryInternal == UnicodeCategory.LowercaseLetter)
{
                            flag2 = true;
                        }
                        num += charLength;
                    }
                    else if (str[num] == '\'')
                    {
                        num++;
                        if (flag2)
{
                            if (text == null)
{
                                text = ToLower(str);
                            }
                            result.Append(text, num2, num - num2);
                        }
                        else
{
                            result.Append(str, num2, num - num2);
                        }
                        num2 = num;
                        flag2 = true;
                    }
                    else
                    {
                        if (IsWordSeparator(unicodeCategoryInternal))
{
                            break;
                        }
                        num += charLength;
                    }
                }
                int num3 = num - num2;
                if (num3 > 0)
                {
                    if (flag2)
                    {
                        if (text == null)
{
                            text = ToLower(str);
                        }
                        result.Append(text, num2, num3);
                    }
                    else
                    {
                        result.Append(str, num2, num3);
                    }
                }
                if (num < str.Length)
                {
                    num = AddNonLetter(ref result, ref str, num, charLength);
                }
            }
            else
            {
                num = AddNonLetter(ref result, ref str, num, charLength);
            }
        }
        return result.ToString();
    }
References System.Globalization.TextInfo.AddNonLetter(), System.Globalization.TextInfo.AddTitlecaseLetter(), System.Text.StringBuilder.Append(), System.Globalization.TextInfo.CultureName, System.Runtime.Serialization.Dictionary, System.Globalization.CharUnicodeInfo.GetUnicodeCategoryInternal(), System.Globalization.TextInfo.IsLetterCategory(), System.Globalization.TextInfo.IsWordSeparator(), System.str, System.text, System.Globalization.TextInfo.ToLower(), and System.Text.StringBuilder.ToString().