Terraria: System.Globalization.TextInfo.IcuChangeCase
IcuChangeCase()
unsafe void System.Globalization.TextInfo.IcuChangeCase (char * src, int srcLen, char * dstBuffer, int dstBufferCapacity, bool bToUpper) inline package
Definition at line 682 of file TextInfo.cs.
    {
        if (IsInvariant)
        {
            Interop.Globalization.ChangeCaseInvariant(src, srcLen, dstBuffer, dstBufferCapacity, bToUpper);
            return;
        }
        if (_needsTurkishCasing == Tristate.NotInitialized)
        {
            _needsTurkishCasing = ((!NeedsTurkishCasing(_textInfoName)) ? Tristate.False : Tristate.True);
        }
        if (_needsTurkishCasing == Tristate.True)
        {
            Interop.Globalization.ChangeCaseTurkish(src, srcLen, dstBuffer, dstBufferCapacity, bToUpper);
        }
        else
        {
            Interop.Globalization.ChangeCase(src, srcLen, dstBuffer, dstBufferCapacity, bToUpper);
        }
    }
References System.Globalization.TextInfo._needsTurkishCasing, System.Globalization.TextInfo._textInfoName, Interop.Globalization.ChangeCase(), Interop.Globalization.ChangeCaseInvariant(), Interop.Globalization.ChangeCaseTurkish(), System.Runtime.Serialization.Dictionary, System.Globalization.TextInfo.IsInvariant, and System.Globalization.TextInfo.NeedsTurkishCasing().
Referenced by System.Globalization.TextInfo.ChangeCaseCore().