Terraria: System.Globalization.TextInfo.AddTitlecaseLetter
AddTitlecaseLetter()
int System.Globalization.TextInfo.AddTitlecaseLetter (ref StringBuilder result, ref string input, int inputIndex, int charLen) inline private
Definition at line 600 of file TextInfo.cs.
    {
        if (charLen == 2)
        {
            ReadOnlySpan<char> source = input.AsSpan(inputIndex, 2);
            if (GlobalizationMode.Invariant)
            {
                SurrogateCasing.ToUpper(source[0], source[1], out var hr, out var lr);
                result.Append(hr);
                result.Append(lr);
            }
            else
            {
                Span<char> span = stackalloc char[2];
                ChangeCaseToUpper(source, span);
                result.Append(span);
            }
            inputIndex++;
        }
        else
        {
            switch (input[inputIndex])
            {
            case 'Ǆ':
            case 'ǅ':
            case 'ǆ':
                result.Append('ǅ');
                break;
            case 'Ǉ':
            case 'ǈ':
            case 'ǉ':
                result.Append('ǈ');
                break;
            case 'Ǌ':
            case 'ǋ':
            case 'ǌ':
                result.Append('ǋ');
                break;
            case 'Ǳ':
            case 'ǲ':
            case 'ǳ':
                result.Append('ǲ');
                break;
            default:
                result.Append(GlobalizationMode.Invariant ? InvariantModeCasing.ToUpper(input[inputIndex]) : ToUpper(input[inputIndex]));
                break;
            }
        }
        return inputIndex;
    }
References System.Globalization.TextInfo.ChangeCaseToUpper(), System.Runtime.Serialization.Dictionary, System.input, System.Globalization.GlobalizationMode.Invariant, System.source, System.Globalization.InvariantModeCasing.ToUpper(), System.Globalization.TextInfo.ToUpper(), and System.Globalization.SurrogateCasing.ToUpper().
Referenced by System.Globalization.TextInfo.ToTitleCase().