Terraria: System.Globalization.TextInfo.ToLowerAsciiInvariant
ToLowerAsciiInvariant() [2/2]
static unsafe string System.Globalization.TextInfo.ToLowerAsciiInvariant (string s) inline static package
Definition at line 371 of file TextInfo.cs.
    {
        if (s.Length == 0)
        {
            return string.Empty;
        }
        fixed (char* ptr = s)
        {
            int i;
            for (i = 0; i < s.Length && (uint)(ptr[i] - 65) > 25u; i++)
            {
            }
            if (i >= s.Length)
            {
                return s;
            }
            string text = string.FastAllocateString(s.Length);
            fixed (char* ptr2 = text)
            {
                for (int j = 0; j < i; j++)
                {
                    ptr2[j] = ptr[j];
                }
                ptr2[i] = (char)(ptr[i] | 0x20u);
                for (i++; i < s.Length; i++)
                {
                    ptr2[i] = ToLowerAsciiInvariant(ptr[i]);
                }
            }
            return text;
        }
    }
References System.Runtime.Serialization.Dictionary, System.s, System.text, and System.Globalization.TextInfo.ToLowerAsciiInvariant().
Referenced by System.Globalization.CultureData.AnsiToLower(), System.Globalization.TextInfo.ToLower(), System.Globalization.TextInfo.ToLowerAsciiInvariant(), and System.Globalization.TextInfo.ToLowerInvariant().