Terraria: System.Globalization.TextInfo.NlsChangeCase
NlsChangeCase()
unsafe void System.Globalization.TextInfo.NlsChangeCase (char * pSource, int pSourceLen, char * pResult, int pResultLen, bool toUpper) inline private
Definition at line 703 of file TextInfo.cs.
    {
        uint num = ((!IsInvariantLocale(_textInfoName)) ? 16777216u : 0u);
        if (Interop.Kernel32.LCMapStringEx((_sortHandle != IntPtr.Zero) ? null : _textInfoName, num | (toUpper ? 512u : 256u), pSource, pSourceLen, pResult, pSourceLen, null, null, _sortHandle) == 0)
        {
            throw new InvalidOperationException(SR.InvalidOperation_ReadOnly);
        }
    }
References System.Globalization.TextInfo._sortHandle, System.Globalization.TextInfo._textInfoName, System.Runtime.Serialization.Dictionary, System.SR.InvalidOperation_ReadOnly, System.Globalization.TextInfo.IsInvariantLocale(), Interop.Kernel32.LCMapStringEx(), and System.IntPtr.Zero.
Referenced by System.Globalization.TextInfo.ChangeCaseCore().