Terraria: System.Linq.Expressions.Interpreter.LightLambda.MakeDelegate
MakeDelegate()
Delegate System.Linq.Expressions.Interpreter.LightLambda.MakeDelegate (Type delegateType) inline package
Definition at line 175 of file LightLambda.cs.
    {
        MethodInfo invokeMethod = delegateType.GetInvokeMethod();
        if (invokeMethod.ReturnType == typeof(void))
        {
            return DelegateHelpers.CreateObjectArrayDelegate(delegateType, RunVoid);
        }
        return DelegateHelpers.CreateObjectArrayDelegate(delegateType, Run);
    }
References System.Dynamic.Utils.DelegateHelpers.CreateObjectArrayDelegate(), System.Linq.Expressions.Interpreter.LightLambda.Run(), and System.Linq.Expressions.Interpreter.LightLambda.RunVoid().
Referenced by System.Linq.Expressions.Interpreter.LightDelegateCreator.CreateDelegate().