Terraria: System.Diagnostics.Contracts.Contract.ReportFailure
ReportFailure()
static void System.Diagnostics.Contracts.Contract.ReportFailure (ContractFailureKind failureKind, string userMessage, string conditionText, Exception innerException) inline static private
Definition at line 244 of file Contract.cs.
    {
        if (failureKind < ContractFailureKind.Precondition || failureKind > ContractFailureKind.Assume)
        {
            throw new ArgumentException(SR.Format(SR.Arg_EnumIllegalVal, failureKind), "failureKind");
        }
        string text = ContractHelper.RaiseContractFailedEvent(failureKind, userMessage, conditionText, innerException);
        if (text != null)
        {
            ContractHelper.TriggerFailure(failureKind, text, userMessage, conditionText, innerException);
        }
    }
References System.SR.Arg_EnumIllegalVal, System.SR.Format(), System.Runtime.CompilerServices.ContractHelper.RaiseContractFailedEvent(), System.text, and System.Runtime.CompilerServices.ContractHelper.TriggerFailure().
Referenced by System.Diagnostics.Contracts.Contract.Assert(), System.Diagnostics.Contracts.Contract.Assert(), System.Diagnostics.Contracts.Contract.Assume(), and System.Diagnostics.Contracts.Contract.Assume().