Terraria: System.Linq.Expressions.Interpreter.LightLambda.Run
Run()
object? System.Linq.Expressions.Interpreter.LightLambda.Run (params object?[] arguments) inline
Definition at line 190 of file LightLambda.cs.
    {
        InterpretedFrame interpretedFrame = MakeFrame();
        for (int i = 0; i < arguments.Length; i++)
        {
            interpretedFrame.Data[i] = arguments[i];
        }
        InterpretedFrame prevFrame = interpretedFrame.Enter();
        try
        {
            _interpreter.Run(interpretedFrame);
        }
        finally
        {
            for (int j = 0; j < arguments.Length; j++)
            {
                arguments[j] = interpretedFrame.Data[j];
            }
            interpretedFrame.Leave(prevFrame);
        }
        return interpretedFrame.Pop();
    }
References System.Linq.Expressions.Interpreter.LightLambda._interpreter, System.Linq.Expressions.Interpreter.LightLambda.MakeFrame(), and System.Linq.Expressions.Interpreter.Interpreter.Run().
Referenced by System.Linq.Expressions.Interpreter.LightLambda.MakeDelegate().