Terraria: System.Xml.Xsl.IlGen.XmlILModule.DefineMethod
DefineMethod()
MethodInfo System.Xml.Xsl.IlGen.XmlILModule.DefineMethod (string name, Type returnType, Type[] paramTypes, string[] paramNames, XmlILMethodAttributes xmlAttrs) inline
Definition at line 62 of file XmlILModule.cs.
    {
        int num = 1;
        string text = name;
        bool flag = (xmlAttrs & XmlILMethodAttributes.Raw) != 0;
        while (_methods[name] != null)
        {
            num++;
            name = text + " (" + num + ")";
        }
        if (!flag)
        {
            Type[] array = new Type[paramTypes.Length + 1];
            array[0] = typeof(XmlQueryRuntime);
            Array.Copy(paramTypes, 0, array, 1, paramTypes.Length);
            paramTypes = array;
        }
        MethodInfo methodInfo;
        if (!_useLRE)
        {
            MethodBuilder methodBuilder = _typeBldr.DefineMethod(name, MethodAttributes.Private | MethodAttributes.Static, returnType, paramTypes);
            if (_emitSymbols && (xmlAttrs & XmlILMethodAttributes.NonUser) != 0)
            {
                methodBuilder.SetCustomAttribute(new CustomAttributeBuilder(XmlILConstructors.StepThrough, Array.Empty<object>()));
                methodBuilder.SetCustomAttribute(new CustomAttributeBuilder(XmlILConstructors.NonUserCode, Array.Empty<object>()));
            }
            if (!flag)
            {
                methodBuilder.DefineParameter(1, ParameterAttributes.None, "{urn:schemas-microsoft-com:xslt-debug}runtime");
            }
            for (int i = 0; i < paramNames.Length; i++)
            {
                if (paramNames[i] != null && paramNames[i].Length != 0)
                {
                    methodBuilder.DefineParameter(i + (flag ? 1 : 2), ParameterAttributes.None, paramNames[i]);
                }
            }
            methodInfo = methodBuilder;
        }
        else
        {
            DynamicMethod dynamicMethod = new DynamicMethod(name, returnType, paramTypes, s_LREModule);
            dynamicMethod.InitLocals = true;
            methodInfo = dynamicMethod;
        }
        _methods[name] = methodInfo;
        return methodInfo;
    }
References System.Xml.Xsl.IlGen.XmlILModule._emitSymbols, System.Xml.Xsl.IlGen.XmlILModule._methods, System.Xml.Xsl.IlGen.XmlILModule._typeBldr, System.Xml.Xsl.IlGen.XmlILModule._useLRE, System.array, System.Array.Copy(), System.Reflection.Emit.TypeBuilder.DefineMethod(), System.Xml.Dictionary, System.Xml.Xsl.IlGen.XmlILConstructors.NonUserCode, System.Xml.Xsl.IlGen.XmlILModule.s_LREModule, System.Xml.Xsl.IlGen.XmlILConstructors.StepThrough, and System.text.
Referenced by System.Xml.Xsl.XmlILGenerator.CreateFunctionMetadata(), System.Xml.Xsl.XmlILGenerator.CreateGlobalValueMetadata(), System.Xml.Xsl.XmlILGenerator.CreateHelperFunctions(), and System.Xml.Xsl.XmlILGenerator.Generate().