Terraria: System.Xml.Xsl.IlGen.XmlILModule.XmlILModule
XmlILModule() [2/2]
System.Xml.Xsl.IlGen.XmlILModule.XmlILModule (bool useLRE, bool emitSymbols) inline
Definition at line 42 of file XmlILModule.cs.
    {
        _useLRE = useLRE;
        _emitSymbols = emitSymbols;
        _methods = new Hashtable();
        if (!useLRE)
        {
            AssemblyName name = CreateAssemblyName();
            AssemblyBuilder assemblyBuilder = AssemblyBuilder.DefineDynamicAssembly(name, AssemblyBuilderAccess.Run);
            assemblyBuilder.SetCustomAttribute(new CustomAttributeBuilder(XmlILConstructors.Transparent, Array.Empty<object>()));
            if (emitSymbols)
            {
                DebuggableAttribute.DebuggingModes debuggingModes = DebuggableAttribute.DebuggingModes.Default | DebuggableAttribute.DebuggingModes.DisableOptimizations | DebuggableAttribute.DebuggingModes.IgnoreSymbolStoreSequencePoints;
                assemblyBuilder.SetCustomAttribute(new CustomAttributeBuilder(XmlILConstructors.Debuggable, new object[1] { debuggingModes }));
            }
            ModuleBuilder moduleBuilder = assemblyBuilder.DefineDynamicModule("System.Xml.Xsl.CompiledQuery");
            _typeBldr = moduleBuilder.DefineType("System.Xml.Xsl.CompiledQuery.Query", TypeAttributes.Public);
        }
    }
References System.Xml.Xsl.IlGen.XmlILModule._emitSymbols, System.Xml.Xsl.IlGen.XmlILModule._methods, System.Xml.Xsl.IlGen.XmlILModule._typeBldr, System.Xml.Xsl.IlGen.XmlILModule._useLRE, System.Xml.Xsl.IlGen.XmlILModule.CreateAssemblyName(), System.Xml.Xsl.IlGen.XmlILConstructors.Debuggable, System.Reflection.Emit.AssemblyBuilder.DefineDynamicAssembly(), System.Reflection.Emit.TypeBuilder.DefineType(), System.Xml.Dictionary, and System.Xml.Xsl.IlGen.XmlILConstructors.Transparent.