Terraria: System.Xml.Xsl.IlGen.XmlILModule.BakeMethods
BakeMethods()
void System.Xml.Xsl.IlGen.XmlILModule.BakeMethods () inline
Definition at line 146 of file XmlILModule.cs.
    {
        if (_useLRE)
        {
            return;
        }
        Type type = _typeBldr.CreateTypeInfo().AsType();
        Hashtable hashtable = new Hashtable(_methods.Count);
        foreach (string key in _methods.Keys)
        {
            hashtable[key] = type.GetMethod(key, BindingFlags.Static | BindingFlags.NonPublic);
        }
        _methods = hashtable;
        _typeBldr = null;
    }
References System.Xml.Xsl.IlGen.XmlILModule._methods, System.Xml.Xsl.IlGen.XmlILModule._typeBldr, System.Xml.Xsl.IlGen.XmlILModule._useLRE, System.Reflection.TypeInfo.AsType(), System.Collections.Hashtable.Count, System.Reflection.Emit.TypeBuilder.CreateTypeInfo(), System.key, System.Collections.Hashtable.Keys, and System.type.
Referenced by System.Xml.Xsl.XmlILGenerator.Generate().