Terraria: System.Security.AccessControl.GenericAce.CreateFromBinaryForm
CreateFromBinaryForm()
static GenericAce System.Security.AccessControl.GenericAce.CreateFromBinaryForm (byte[] binaryForm, int offset) inline static inherited
Definition at line 176 of file GenericAce.cs.
    {
        VerifyHeader(binaryForm, offset);
        AceType aceType = (AceType)binaryForm[offset];
        GenericAce genericAce;
        if (aceType == AceType.AccessAllowed || aceType == AceType.AccessDenied || aceType == AceType.SystemAudit || aceType == AceType.SystemAlarm || aceType == AceType.AccessAllowedCallback || aceType == AceType.AccessDeniedCallback || aceType == AceType.SystemAuditCallback || aceType == AceType.SystemAlarmCallback)
        {
            if (CommonAce.ParseBinaryForm(binaryForm, offset, out var qualifier, out var accessMask, out var sid, out var isCallback, out var opaque))
            {
                AceFlags flags = (AceFlags)binaryForm[offset + 1];
                genericAce = new CommonAce(flags, qualifier, accessMask, sid, isCallback, opaque);
                goto IL_0154;
            }
        }
        else if (aceType == AceType.AccessAllowedObject || aceType == AceType.AccessDeniedObject || aceType == AceType.SystemAuditObject || aceType == AceType.SystemAlarmObject || aceType == AceType.AccessAllowedCallbackObject || aceType == AceType.AccessDeniedCallbackObject || aceType == AceType.SystemAuditCallbackObject || aceType == AceType.SystemAlarmCallbackObject)
        {
            if (ObjectAce.ParseBinaryForm(binaryForm, offset, out var qualifier2, out var accessMask2, out var sid2, out var objectFlags, out var objectAceType, out var inheritedObjectAceType, out var isCallback2, out var opaque2))
            {
                AceFlags aceFlags = (AceFlags)binaryForm[offset + 1];
                genericAce = new ObjectAce(aceFlags, qualifier2, accessMask2, sid2, objectFlags, objectAceType, inheritedObjectAceType, isCallback2, opaque2);
                goto IL_0154;
            }
        }
        else if (aceType == AceType.AccessAllowedCompound)
        {
            if (CompoundAce.ParseBinaryForm(binaryForm, offset, out var accessMask3, out var compoundAceType, out var sid3))
            {
                AceFlags flags2 = (AceFlags)binaryForm[offset + 1];
                genericAce = new CompoundAce(flags2, accessMask3, compoundAceType, sid3);
                goto IL_0154;
            }
        }
        else
        {
            AceFlags flags3 = (AceFlags)binaryForm[offset + 1];
            byte[] array = null;
            int num = binaryForm[offset + 2] + (binaryForm[offset + 3] << 8);
            if (num % 4 == 0)
            {
                int num2 = num - 4;
                if (num2 > 0)
                {
                    array = new byte[num2];
                    for (int i = 0; i < num2; i++)
                    {
                        array[i] = binaryForm[offset + num - num2 + i];
                    }
                }
                genericAce = new CustomAce(aceType, flags3, array);
                goto IL_0154;
            }
        }
        goto IL_01a8;
        IL_01a8:
        throw new ArgumentException(System.SR.ArgumentException_InvalidAceBinaryForm, "binaryForm");
        IL_0154:
        if ((genericAce is ObjectAce || binaryForm[offset + 2] + (binaryForm[offset + 3] << 8) == genericAce.BinaryLength) && (!(genericAce is ObjectAce) || binaryForm[offset + 2] + (binaryForm[offset + 3] << 8) == genericAce.BinaryLength || binaryForm[offset + 2] + (binaryForm[offset + 3] << 8) - 32 == genericAce.BinaryLength))
        {
            return genericAce;
        }
        goto IL_01a8;
    }
References System.Security.AccessControl.GenericAce.AceFlags, System.Security.AccessControl.GenericAce.AceType, System.SR.ArgumentException_InvalidAceBinaryForm, System.array, System.Security.AccessControl.GenericAce.BinaryLength, System.offset, System.Security.AccessControl.CommonAce.ParseBinaryForm(), System.Security.AccessControl.ObjectAce.ParseBinaryForm(), System.Security.AccessControl.CompoundAce.ParseBinaryForm(), and System.Security.AccessControl.GenericAce.VerifyHeader().
Referenced by System.Security.AccessControl.GenericAce.Copy(), and System.Security.AccessControl.RawAcl.SetBinaryForm().