Terraria: System.Security.AccessControl.GenericAce.VerifyHeader
VerifyHeader()
static void System.Security.AccessControl.GenericAce.VerifyHeader (byte[] binaryForm, int offset) inline static package inherited
Definition at line 156 of file GenericAce.cs.
    {
        if (binaryForm == null)
        {
            throw new ArgumentNullException("binaryForm");
        }
        if (offset < 0)
        {
            throw new ArgumentOutOfRangeException("offset", System.SR.ArgumentOutOfRange_NeedNonNegNum);
        }
        if (binaryForm.Length - offset < 4)
        {
            throw new ArgumentOutOfRangeException("binaryForm", System.SR.ArgumentOutOfRange_ArrayTooSmall);
        }
        if ((binaryForm[offset + 3] << 8) + binaryForm[offset + 2] > binaryForm.Length - offset)
        {
            throw new ArgumentOutOfRangeException("binaryForm", System.SR.ArgumentOutOfRange_ArrayTooSmall);
        }
    }
References System.SR.ArgumentOutOfRange_ArrayTooSmall, System.SR.ArgumentOutOfRange_NeedNonNegNum, and System.offset.
Referenced by System.Security.AccessControl.GenericAce.CreateFromBinaryForm(), System.Security.AccessControl.CommonAce.ParseBinaryForm(), System.Security.AccessControl.ObjectAce.ParseBinaryForm(), and System.Security.AccessControl.CompoundAce.ParseBinaryForm().