Terraria: System.Security.AccessControl.GenericAce.AceFlagsFromInheritanceFlags
AceFlagsFromInheritanceFlags()
static AceFlags System.Security.AccessControl.GenericAce.AceFlagsFromInheritanceFlags (InheritanceFlags inheritanceFlags, PropagationFlags propagationFlags) inline static package inherited
Definition at line 131 of file GenericAce.cs.
    {
        AceFlags aceFlags = AceFlags.None;
        if ((inheritanceFlags & InheritanceFlags.ContainerInherit) != 0)
        {
            aceFlags |= AceFlags.ContainerInherit;
        }
        if ((inheritanceFlags & InheritanceFlags.ObjectInherit) != 0)
        {
            aceFlags |= AceFlags.ObjectInherit;
        }
        if (aceFlags != 0)
        {
            if ((propagationFlags & PropagationFlags.NoPropagateInherit) != 0)
            {
                aceFlags |= AceFlags.NoPropagateInherit;
            }
            if ((propagationFlags & PropagationFlags.InheritOnly) != 0)
            {
                aceFlags |= AceFlags.InheritOnly;
            }
        }
        return aceFlags;
    }
Referenced by System.Security.AccessControl.DiscretionaryAcl.AddAccess(), System.Security.AccessControl.DiscretionaryAcl.AddAccess(), System.Security.AccessControl.SystemAcl.AddAudit(), System.Security.AccessControl.SystemAcl.AddAudit(), System.Security.AccessControl.DiscretionaryAcl.RemoveAccess(), System.Security.AccessControl.DiscretionaryAcl.RemoveAccess(), System.Security.AccessControl.DiscretionaryAcl.RemoveAccessSpecific(), System.Security.AccessControl.DiscretionaryAcl.RemoveAccessSpecific(), System.Security.AccessControl.SystemAcl.RemoveAudit(), System.Security.AccessControl.SystemAcl.RemoveAudit(), System.Security.AccessControl.SystemAcl.RemoveAuditSpecific(), System.Security.AccessControl.SystemAcl.RemoveAuditSpecific(), System.Security.AccessControl.DiscretionaryAcl.SetAccess(), System.Security.AccessControl.DiscretionaryAcl.SetAccess(), System.Security.AccessControl.SystemAcl.SetAudit(), and System.Security.AccessControl.SystemAcl.SetAudit().