Terraria: System.Security.AccessControl.GenericAce.Equals
Equals()
override bool System.Security.AccessControl.GenericAce.Equals ([NotNullWhen(true)] object? o) inline sealed inherited
Definition at line 248 of file GenericAce.cs.
    {
        GenericAce genericAce = o as GenericAce;
        if (genericAce == null)
        {
            return false;
        }
        if (AceType != genericAce.AceType || AceFlags != genericAce.AceFlags)
        {
            return false;
        }
        int binaryLength = BinaryLength;
        int binaryLength2 = genericAce.BinaryLength;
        if (binaryLength != binaryLength2)
        {
            return false;
        }
        byte[] array = new byte[binaryLength];
        byte[] array2 = new byte[binaryLength2];
        GetBinaryForm(array, 0);
        genericAce.GetBinaryForm(array2, 0);
        for (int i = 0; i < array.Length; i++)
        {
            if (array[i] != array2[i])
            {
                return false;
            }
        }
        return true;
    }
References System.Security.AccessControl.GenericAce.GenericAce(), System.Security.AccessControl.GenericAce.AceFlags, System.Security.AccessControl.GenericAce.AceType, System.array, System.Security.AccessControl.GenericAce.BinaryLength, and System.Security.AccessControl.GenericAce.GetBinaryForm().
Referenced by System.Security.AccessControl.GenericAce.operator==().