Terraria: System.Security.AccessControl.GenericAce.AceFlagsFromAuditFlags
AceFlagsFromAuditFlags()
static AceFlags System.Security.AccessControl.GenericAce.AceFlagsFromAuditFlags (AuditFlags auditFlags) inline static package inherited
Definition at line 113 of file GenericAce.cs.
    {
        AceFlags aceFlags = AceFlags.None;
        if ((auditFlags & AuditFlags.Success) != 0)
        {
            aceFlags |= AceFlags.SuccessfulAccess;
        }
        if ((auditFlags & AuditFlags.Failure) != 0)
        {
            aceFlags |= AceFlags.FailedAccess;
        }
        if (aceFlags == AceFlags.None)
        {
            throw new ArgumentException(System.SR.Arg_EnumAtLeastOneFlag, "auditFlags");
        }
        return aceFlags;
    }
References System.SR.Arg_EnumAtLeastOneFlag.
Referenced by System.Security.AccessControl.SystemAcl.AddAudit(), System.Security.AccessControl.SystemAcl.AddAudit(), System.Security.AccessControl.SystemAcl.RemoveAudit(), System.Security.AccessControl.SystemAcl.RemoveAudit(), System.Security.AccessControl.SystemAcl.RemoveAuditSpecific(), System.Security.AccessControl.SystemAcl.RemoveAuditSpecific(), System.Security.AccessControl.SystemAcl.SetAudit(), and System.Security.AccessControl.SystemAcl.SetAudit().