Terraria: System.Security.AccessControl.GenericAce.MarshalHeader
MarshalHeader()
void System.Security.AccessControl.GenericAce.MarshalHeader (byte[] binaryForm, int offset) inline package inherited
Definition at line 82 of file GenericAce.cs.
    {
        int binaryLength = BinaryLength;
        if (binaryForm == null)
        {
            throw new ArgumentNullException("binaryForm");
        }
        if (offset < 0)
        {
            throw new ArgumentOutOfRangeException("offset", System.SR.ArgumentOutOfRange_NeedNonNegNum);
        }
        if (binaryForm.Length - offset < BinaryLength)
        {
            throw new ArgumentOutOfRangeException("binaryForm", System.SR.ArgumentOutOfRange_ArrayTooSmall);
        }
        if (binaryLength > 65535)
        {
            throw new InvalidOperationException();
        }
        binaryForm[offset] = (byte)AceType;
        binaryForm[offset + 1] = (byte)AceFlags;
        binaryForm[offset + 2] = (byte)binaryLength;
        binaryForm[offset + 3] = (byte)(binaryLength >> 8);
    }
References System.SR.ArgumentOutOfRange_ArrayTooSmall, System.SR.ArgumentOutOfRange_NeedNonNegNum, System.Security.AccessControl.GenericAce.BinaryLength, and System.offset.
Referenced by System.Security.AccessControl.CommonAce.GetBinaryForm(), System.Security.AccessControl.CompoundAce.GetBinaryForm(), System.Security.AccessControl.CustomAce.GetBinaryForm(), and System.Security.AccessControl.ObjectAce.GetBinaryForm().