Terraria: System.Xml.Xsl.XslLoadException.CreateMessage
CreateMessage() [1/2]
static string System.Xml.Xsl.XslLoadException.CreateMessage (ISourceLineInfo lineInfo, string res, params string[] args) inline static package inherited
Definition at line 126 of file XslLoadException.cs.
    {
        return AppendLineInfoMessage(XslTransformException.CreateMessage(res, args), lineInfo);
    }
References System.Xml.Xsl.XslLoadException.AppendLineInfoMessage(), System.Xml.Xsl.XslTransformException.CreateMessage(), and System.Xml.Dictionary.
Referenced by System.Xml.Xsl.Xslt.QilGenerator.CompileKeyUse(), System.Xml.Xsl.XPath.XPathQilFactory.Error(), System.Xml.Xsl.Xslt.XsltLoader.LoadFallbacks(), System.Xml.Xsl.Xslt.XsltLoader.XslApplyImports(), and System.Xml.Xsl.Xslt.XsltLoader.XslValueOf().