Terraria: System.Xml.Xsl.XslLoadException.AppendLineInfoMessage
AppendLineInfoMessage()
static string System.Xml.Xsl.XslLoadException.AppendLineInfoMessage (string message, ISourceLineInfo lineInfo) inline static private inherited
Definition at line 108 of file XslLoadException.cs.
    {
        if (lineInfo != null)
        {
            string fileName = SourceLineInfo.GetFileName(lineInfo.Uri);
            string text = XslTransformException.CreateMessage(System.SR.Xml_ErrorFilePosition, fileName, lineInfo.Start.Line.ToString(CultureInfo.InvariantCulture), lineInfo.Start.Pos.ToString(CultureInfo.InvariantCulture));
            if (text != null && text.Length > 0)
            {
                if (message.Length > 0 && !XmlCharType.IsWhiteSpace(message[message.Length - 1]))
                {
                    message += " ";
                }
                message += text;
            }
        }
        return message;
    }
References System.Xml.Xsl.XslTransformException.CreateMessage(), System.Xml.Dictionary, System.Xml.Xsl.SourceLineInfo.GetFileName(), System.Globalization.CultureInfo.InvariantCulture, System.Xml.XmlCharType.IsWhiteSpace(), System.Xml.Xsl.Location.Line, System.Xml.Xsl.Location.Pos, System.Xml.Xsl.ISourceLineInfo.Start, System.text, System.Xml.Xsl.ISourceLineInfo.Uri, and System.SR.Xml_ErrorFilePosition.
Referenced by System.Xml.Xsl.XslLoadException.CreateMessage(), and System.Xml.Xsl.XslLoadException.FormatDetailedMessage().