Terraria: System.Threading.Tasks.Dataflow.BroadcastBlock.BroadcastBlock
BroadcastBlock() [2/2]
System.Threading.Tasks.Dataflow.BroadcastBlock< T >.BroadcastBlock (Func< T, T >? cloningFunction, DataflowBlockOptions dataflowBlockOptions) inline
Definition at line 625 of file BroadcastBlock.cs.
    {
        if (dataflowBlockOptions == null)
        {
            throw new ArgumentNullException("dataflowBlockOptions");
        }
        dataflowBlockOptions = dataflowBlockOptions.DefaultOrClone();
        Action<int> itemsRemovedAction = null;
        if (dataflowBlockOptions.BoundedCapacity > 0)
        {
            itemsRemovedAction = OnItemsRemoved;
            _boundingState = new BoundingStateWithPostponedAndTask<T>(dataflowBlockOptions.BoundedCapacity);
        }
        _source = new BroadcastingSourceCore<T>(this, cloningFunction, dataflowBlockOptions, itemsRemovedAction);
        _source.Completion.ContinueWith(delegate(Task completed, object state)
        {
            IDataflowBlock dataflowBlock = (BroadcastBlock<T>)state;
            dataflowBlock.Fault(completed.Exception);
        }, this, CancellationToken.None, Common.GetContinuationOptions() | TaskContinuationOptions.OnlyOnFaulted, TaskScheduler.Default);
        Common.WireCancellationToComplete(dataflowBlockOptions.CancellationToken, _source.Completion, delegate(object state)
        {
            ((BroadcastBlock<T>)state).Complete();
        }, this);
        DataflowEtwProvider log = DataflowEtwProvider.Log;
        if (log.IsEnabled())
        {
            log.DataflowBlockCreated(this, dataflowBlockOptions);
        }
    }
References System.Threading.Tasks.Dataflow.BroadcastBlock< T >._boundingState, System.Threading.Tasks.Dataflow.BroadcastBlock< T >._source, System.Threading.Tasks.Dataflow.BroadcastBlock< T >.BroadcastingSourceCore< TOutput >.Completion, System.Threading.Tasks.Task< TResult >.ContinueWith(), System.Threading.Tasks.TaskScheduler.Default, System.Threading.Tasks.Dataflow.Internal.Common.GetContinuationOptions(), System.Threading.Tasks.Dataflow.Internal.DataflowEtwProvider.Log, System.Threading.CancellationToken.None, System.Threading.Tasks.Dataflow.BroadcastBlock< T >.OnItemsRemoved(), System.state, and System.Threading.Tasks.Dataflow.Internal.Common.WireCancellationToComplete().