Terraria: System.Data.XMLDiffLoader.GetTable
GetTable()
DataTable System.Data.XMLDiffLoader.GetTable (string tableName, string ns) inline private
Definition at line 237 of file XMLDiffLoader.cs.
    {
        if (_tables == null)
        {
            return _dataSet.Tables.GetTable(tableName, ns);
        }
        if (_tables.Count == 0)
        {
            return (DataTable)_tables[0];
        }
        for (int i = 0; i < _tables.Count; i++)
        {
            DataTable dataTable = (DataTable)_tables[i];
            if (string.Equals(dataTable.TableName, tableName, StringComparison.Ordinal) && string.Equals(dataTable.Namespace, ns, StringComparison.Ordinal))
            {
                return dataTable;
            }
        }
        return null;
    }
References System.Data.XMLDiffLoader._dataSet, System.Data.XMLDiffLoader._tables, System.Collections.ArrayList.Count, System.Xml.Dictionary, System.Data.DataTableCollection.GetTable(), and System.Data.DataSet.Tables.
Referenced by System.Data.XMLDiffLoader.ProcessErrors(), and System.Data.XMLDiffLoader.ReadOldRowData().