Terraria: System.Data.XMLDiffLoader.ProcessErrors
ProcessErrors() [1/2]
void System.Data.XMLDiffLoader.ProcessErrors (ArrayList dt, XmlReader ssync) inline package
Definition at line 188 of file XMLDiffLoader.cs.
    {
        int depth = ssync.Depth;
        ssync.Read();
        while (depth < ssync.Depth)
        {
            DataTable table = GetTable(XmlConvert.DecodeName(ssync.LocalName), ssync.NamespaceURI);
            if (table == null)
            {
                throw ExceptionBuilder.DiffgramMissingSQL();
            }
            string attribute = ssync.GetAttribute("id", "urn:schemas-microsoft-com:xml-diffgram-v1");
            DataRow dataRow = (DataRow)table.RowDiffId[attribute];
            if (dataRow == null)
            {
                for (int i = 0; i < dt.Count; i++)
                {
                    dataRow = (DataRow)((DataTable)dt[i]).RowDiffId[attribute];
                    if (dataRow != null)
                    {
                        table = dataRow.Table;
                        break;
                    }
                }
            }
            string attribute2 = ssync.GetAttribute("Error", "urn:schemas-microsoft-com:xml-diffgram-v1");
            if (attribute2 != null)
            {
                dataRow.RowError = attribute2;
            }
            int depth2 = ssync.Depth;
            ssync.Read();
            while (depth2 < ssync.Depth)
            {
                if (XmlNodeType.Element == ssync.NodeType)
                {
                    DataColumn column = table.Columns[XmlConvert.DecodeName(ssync.LocalName), ssync.NamespaceURI];
                    string attribute3 = ssync.GetAttribute("Error", "urn:schemas-microsoft-com:xml-diffgram-v1");
                    dataRow.SetColumnError(column, attribute3);
                }
                ssync.Read();
            }
            while (ssync.NodeType == XmlNodeType.EndElement && depth < ssync.Depth)
            {
                ssync.Read();
            }
        }
    }
References System.Data.DataTable.Columns, System.Xml.XmlConvert.DecodeName(), System.Xml.Dictionary, System.Data.ExceptionBuilder.DiffgramMissingSQL(), System.Data.XMLDiffLoader.GetTable(), and System.Data.DataTable.RowDiffId.