Terraria: System.Data.XMLDiffLoader.ProcessDiffs
ProcessDiffs() [2/2]
void System.Data.XMLDiffLoader.ProcessDiffs (DataSet ds, XmlReader ssync) inline package
Definition at line 66 of file XMLDiffLoader.cs.
    {
        int pos = -1;
        int depth = ssync.Depth;
        ssync.Read();
        SkipWhitespaces(ssync);
        while (depth < ssync.Depth)
        {
            DataTable table = null;
            string text = null;
            int num = -1;
            text = ssync.GetAttribute("id", "urn:schemas-microsoft-com:xml-diffgram-v1");
            bool flag = ssync.GetAttribute("hasErrors", "urn:schemas-microsoft-com:xml-diffgram-v1") == "true";
            num = ReadOldRowData(ds, ref table, ref pos, ssync);
            if (num == -1)
            {
                continue;
            }
            if (table == null)
            {
                throw ExceptionBuilder.DiffgramMissingSQL();
            }
            DataRow dataRow = (DataRow)table.RowDiffId[text];
            if (dataRow != null)
            {
                dataRow._oldRecord = num;
                table._recordManager[num] = dataRow;
                continue;
            }
            dataRow = table.NewEmptyRow();
            table._recordManager[num] = dataRow;
            dataRow._oldRecord = num;
            dataRow._newRecord = num;
            table.Rows.DiffInsertAt(dataRow, pos);
            dataRow.Delete();
            if (flag)
            {
                table.RowDiffId[text] = dataRow;
            }
        }
    }
References System.Data.DataTable._recordManager, System.Xml.Dictionary, System.Data.ExceptionBuilder.DiffgramMissingSQL(), System.Data.DataRowCollection.DiffInsertAt(), System.Data.DataTable.NewEmptyRow(), System.Data.XMLDiffLoader.ReadOldRowData(), System.Data.DataTable.RowDiffId, System.Data.DataTable.Rows, System.Data.XMLDiffLoader.SkipWhitespaces(), and System.text.
Referenced by System.Data.XMLDiffLoader.LoadDiffGram(), and System.Data.XMLDiffLoader.LoadDiffGram().