Terraria: LegacyChatMonitor.NewTextInternal
NewTextInternal()
void LegacyChatMonitor.NewTextInternal (string newText, byte R = byte.MaxValue, byte G = byte.MaxValue, byte B = byte.MaxValue, bool force = false) inline
     {
         int num = 80;
         if (!force && newText.Length > num)
         {
             string oldText = newText;
             oldText = TrimIntoMultipleLines(R, G, B, num, oldText);
             if (oldText.Length > 0)
             {
                 NewTextInternal(oldText, R, G, B, force: true);
             }
             return;
         }
         for (int num2 = numChatLines - 1; num2 > 0; num2--)
         {
             chatLine[num2].Copy(chatLine[num2 - 1]);
         }
         chatLine[0].color = new Color(R, G, B);
         chatLine[0].originalText = newText;
         chatLine[0].parsedText = ChatManager.ParseMessage(chatLine[0].originalText, chatLine[0].color).ToArray();
         chatLine[0].showTime = chatLength;
         SoundEngine.PlaySound(12);
     }
References B, chatLength, chatLine, Color, ChatLine.color, ChatLine.Copy(), G, numChatLines, ChatLine.originalText, ChatLine.parsedText, ChatManager.ParseMessage(), SoundEngine.PlaySound(), R, ChatLine.showTime, and TrimIntoMultipleLines().
Referenced by TrimIntoMultipleLines().