Terraria: System.Data.XMLDiffLoader.ProcessErrors
ProcessErrors() [2/2]
void System.Data.XMLDiffLoader.ProcessErrors (DataSet ds, XmlReader ssync) inline package
Definition at line 150 of file XMLDiffLoader.cs.
    {
        int depth = ssync.Depth;
        ssync.Read();
        while (depth < ssync.Depth)
        {
            DataTable table = ds.Tables.GetTable(XmlConvert.DecodeName(ssync.LocalName), ssync.NamespaceURI);
            if (table == null)
            {
                throw ExceptionBuilder.DiffgramMissingSQL();
            }
            string attribute = ssync.GetAttribute("id", "urn:schemas-microsoft-com:xml-diffgram-v1");
            DataRow dataRow = (DataRow)table.RowDiffId[attribute];
            string attribute2 = ssync.GetAttribute("Error", "urn:schemas-microsoft-com:xml-diffgram-v1");
            if (attribute2 != null)
            {
                dataRow.RowError = attribute2;
            }
            int depth2 = ssync.Depth;
            ssync.Read();
            while (depth2 < ssync.Depth)
            {
                if (XmlNodeType.Element == ssync.NodeType)
                {
                    DataColumn column = table.Columns[XmlConvert.DecodeName(ssync.LocalName), ssync.NamespaceURI];
                    string attribute3 = ssync.GetAttribute("Error", "urn:schemas-microsoft-com:xml-diffgram-v1");
                    dataRow.SetColumnError(column, attribute3);
                }
                ssync.Read();
            }
            while (ssync.NodeType == XmlNodeType.EndElement && depth < ssync.Depth)
            {
                ssync.Read();
            }
        }
    }
References System.Data.DataTable.Columns, System.Xml.XmlConvert.DecodeName(), System.Xml.Dictionary, System.Data.ExceptionBuilder.DiffgramMissingSQL(), and System.Data.DataTable.RowDiffId.
Referenced by System.Data.XMLDiffLoader.LoadDiffGram(), and System.Data.XMLDiffLoader.LoadDiffGram().