Terraria: System.Data.XMLDiffLoader.ReadOldRowData
ReadOldRowData()
int System.Data.XMLDiffLoader.ReadOldRowData (DataSet ds, ref DataTable table, ref int pos, XmlReader row) inline private
Definition at line 259 of file XMLDiffLoader.cs.
    {
        if (ds != null)
        {
            table = ds.Tables.GetTable(XmlConvert.DecodeName(row.LocalName), row.NamespaceURI);
        }
        else
        {
            table = GetTable(XmlConvert.DecodeName(row.LocalName), row.NamespaceURI);
        }
        if (table == null)
        {
            row.Skip();
            return -1;
        }
        int depth = row.Depth;
        string text = null;
        text = row.GetAttribute("rowOrder", "urn:schemas-microsoft-com:xml-msdata");
        if (!string.IsNullOrEmpty(text))
        {
            pos = (int)Convert.ChangeType(text, typeof(int), null);
        }
        int num = table.NewRecord();
        foreach (DataColumn column in table.Columns)
        {
            column[num] = DBNull.Value;
        }
        foreach (DataColumn column2 in table.Columns)
        {
            if (column2.ColumnMapping != MappingType.Element && column2.ColumnMapping != MappingType.SimpleContent)
            {
                text = ((column2.ColumnMapping != MappingType.Hidden) ? row.GetAttribute(column2.EncodedColumnName, column2.Namespace) : row.GetAttribute("hidden" + column2.EncodedColumnName, "urn:schemas-microsoft-com:xml-msdata"));
                if (text != null)
                {
                    column2[num] = column2.ConvertXmlToObject(text);
                }
            }
        }
        row.Read();
        SkipWhitespaces(row);
        int depth2 = row.Depth;
        if (depth2 <= depth)
        {
            if (depth2 == depth && row.NodeType == XmlNodeType.EndElement)
            {
                row.Read();
                SkipWhitespaces(row);
            }
            return num;
        }
        if (table.XmlText != null)
        {
            DataColumn xmlText = table.XmlText;
            xmlText[num] = xmlText.ConvertXmlToObject(row.ReadString());
        }
        else
        {
            while (row.Depth > depth)
            {
                string text2 = XmlConvert.DecodeName(row.LocalName);
                string namespaceURI = row.NamespaceURI;
                DataColumn dataColumn3 = table.Columns[text2, namespaceURI];
                if (dataColumn3 == null)
                {
                    while (row.NodeType != XmlNodeType.EndElement && row.LocalName != text2 && row.NamespaceURI != namespaceURI)
                    {
                        row.Read();
                    }
                    row.Read();
                    continue;
                }
                if (dataColumn3.IsCustomType)
                {
                    bool flag = dataColumn3.DataType == typeof(object) || row.GetAttribute("InstanceType", "urn:schemas-microsoft-com:xml-msdata") != null || row.GetAttribute("type", "http://www.w3.org/2001/XMLSchema-instance") != null;
                    bool flag2 = false;
                    if (dataColumn3.Table.DataSet != null && dataColumn3.Table.DataSet._udtIsWrapped)
                    {
                        row.Read();
                        flag2 = true;
                    }
                    XmlRootAttribute xmlRootAttribute = null;
                    if (!flag && !dataColumn3.ImplementsIXMLSerializable)
                    {
                        if (flag2)
{
                            xmlRootAttribute = new XmlRootAttribute(row.LocalName);
                            xmlRootAttribute.Namespace = row.NamespaceURI;
                        }
                        else
{
                            xmlRootAttribute = new XmlRootAttribute(dataColumn3.EncodedColumnName);
                            xmlRootAttribute.Namespace = dataColumn3.Namespace;
                        }
                    }
                    dataColumn3[num] = dataColumn3.ConvertXmlToObject(row, xmlRootAttribute);
                    if (flag2)
                    {
                        row.Read();
                    }
                    continue;
                }
                int depth3 = row.Depth;
                row.Read();
                if (row.Depth > depth3)
                {
                    if (row.NodeType == XmlNodeType.Text || row.NodeType == XmlNodeType.Whitespace || row.NodeType == XmlNodeType.SignificantWhitespace)
                    {
                        string s = row.ReadString();
                        dataColumn3[num] = dataColumn3.ConvertXmlToObject(s);
                        row.Read();
                    }
                }
                else if (dataColumn3.DataType == typeof(string))
                {
                    dataColumn3[num] = string.Empty;
                }
            }
        }
        row.Read();
        SkipWhitespaces(row);
        return num;
    }
References System.Convert.ChangeType(), System.Data.DataColumn.ConvertXmlToObject(), System.Xml.XmlConvert.DecodeName(), System.Xml.Dictionary, System.Data.XMLDiffLoader.GetTable(), System.s, System.Data.XMLDiffLoader.SkipWhitespaces(), System.text, and System.DBNull.Value.
Referenced by System.Data.XMLDiffLoader.ProcessDiffs(), and System.Data.XMLDiffLoader.ProcessDiffs().