Terraria: NPCWasNearPlayerTracker.RegisterWasNearby
RegisterWasNearby()
void NPCWasNearPlayerTracker.RegisterWasNearby (NPC npc) inline
     {
         string bestiaryCreditId = npc.GetBestiaryCreditId();
         bool flag = !_wasNearPlayer.Contains(bestiaryCreditId);
         lock (_entryCreationLock)
         {
             _wasNearPlayer.Add(bestiaryCreditId);
         }
         if (Main.netMode == 2 && flag)
         {
             NetManager.Instance.Broadcast(NetBestiaryModule.SerializeSight(npc.netID));
         }
     }
References _entryCreationLock, _wasNearPlayer, NetManager.Broadcast(), NPC.GetBestiaryCreditId(), NetManager.Instance, NPC.netID, Main.netMode, and NetBestiaryModule.SerializeSight().
Referenced by ScanWorldForFinds().