Terraria: PlayerHeadDrawRenderTargetContent.DrawTheContent
DrawTheContent()
override void PlayerHeadDrawRenderTargetContent.DrawTheContent (SpriteBatch spriteBatch) inline package virtual
Implements AnOutlinedDrawRenderTargetContent.
     {
         if (_player != null && !_player.ShouldNotDraw)
         {
             _drawData.Clear();
             _dust.Clear();
             _gore.Clear();
             PlayerDrawHeadSet drawinfo = default(PlayerDrawHeadSet);
             drawinfo.BoringSetup(_player, _drawData, _dust, _gore, width / 2, height / 2, 1f, 1f);
             PlayerDrawHeadLayers.DrawPlayer_00_BackHelmet(ref drawinfo);
             PlayerDrawHeadLayers.DrawPlayer_01_FaceSkin(ref drawinfo);
             PlayerDrawHeadLayers.DrawPlayer_02_DrawArmorWithFullHair(ref drawinfo);
             PlayerDrawHeadLayers.DrawPlayer_03_HelmetHair(ref drawinfo);
             PlayerDrawHeadLayers.DrawPlayer_04_HatsWithFullHair(ref drawinfo);
             PlayerDrawHeadLayers.DrawPlayer_05_TallHats(ref drawinfo);
             PlayerDrawHeadLayers.DrawPlayer_06_NormalHats(ref drawinfo);
             PlayerDrawHeadLayers.DrawPlayer_07_JustHair(ref drawinfo);
             PlayerDrawHeadLayers.DrawPlayer_08_FaceAcc(ref drawinfo);
             PlayerDrawHeadLayers.DrawPlayer_RenderAllLayers(ref drawinfo);
         }
     }
References _drawData, _dust, _gore, _player, PlayerDrawHeadSet.BoringSetup(), PlayerDrawHeadLayers.DrawPlayer_00_BackHelmet(), PlayerDrawHeadLayers.DrawPlayer_01_FaceSkin(), PlayerDrawHeadLayers.DrawPlayer_02_DrawArmorWithFullHair(), PlayerDrawHeadLayers.DrawPlayer_03_HelmetHair(), PlayerDrawHeadLayers.DrawPlayer_04_HatsWithFullHair(), PlayerDrawHeadLayers.DrawPlayer_05_TallHats(), PlayerDrawHeadLayers.DrawPlayer_06_NormalHats(), PlayerDrawHeadLayers.DrawPlayer_07_JustHair(), PlayerDrawHeadLayers.DrawPlayer_08_FaceAcc(), PlayerDrawHeadLayers.DrawPlayer_RenderAllLayers(), AnOutlinedDrawRenderTargetContent.height, Player.ShouldNotDraw, and AnOutlinedDrawRenderTargetContent.width.