Terraria: MarbleBiome.Place
Place()
override bool MarbleBiome.Place (Point origin, StructureMap structures) inline virtual
Implements GenStructure.
     {
         if (WorldGen.BiomeTileCheck(origin.X, origin.Y))
         {
             return false;
         }
         if (_slabs == null)
         {
             _slabs = new Slab[56, 26];
         }
         int num = GenBase._random.Next(80, 150) / 3;
         int num2 = GenBase._random.Next(40, 60) / 3;
         int num3 = (num2 * 3 - GenBase._random.Next(20, 30)) / 3;
         origin.X -= num * 3 / 2;
         origin.Y -= num2 * 3 / 2;
         for (int i = -1; i < num + 1; i++)
         {
             double num4 = (double)(i - num / 2) / (double)num + 0.5;
             int num5 = (int)((0.5 - Math.Abs(num4 - 0.5)) * 5.0) - 2;
             for (int j = -1; j < num2 + 1; j++)
             {
                 bool hasWall = true;
                 bool flag = false;
                 bool flag2 = IsGroupSolid(i * 3 + origin.X, j * 3 + origin.Y, 3);
                 int num6 = Math.Abs(j - num2 / 2) - num3 / 4 + num5;
                 if (num6 > 3)
                 {
                     flag = flag2;
                     hasWall = false;
                 }
                 else if (num6 > 0)
                 {
                     flag = j - num2 / 2 > 0 || flag2;
                     hasWall = j - num2 / 2 < 0 || num6 <= 2;
                 }
                 else if (num6 == 0)
                 {
                     flag = GenBase._random.Next(2) == 0 && (j - num2 / 2 > 0 || flag2);
                 }
                 if (Math.Abs(num4 - 0.5) > 0.35 + GenBase._random.NextDouble() * 0.1 && !flag2)
                 {
                     hasWall = false;
                     flag = false;
                 }
                 _slabs[i + 1, j + 1] = Slab.Create(flag ? new SlabState(SlabStates.Solid) : new SlabState(SlabStates.Empty), hasWall);
             }
         }
         for (int k = 0; k < num; k++)
         {
             for (int l = 0; l < num2; l++)
             {
                 SmoothSlope(k + 1, l + 1);
             }
         }
         int num7 = num / 2;
         int num8 = num2 / 2;
         int num9 = (num8 + 1) * (num8 + 1);
         double value = GenBase._random.NextDouble() * 2.0 - 1.0;
         double num10 = GenBase._random.NextDouble() * 2.0 - 1.0;
         double value2 = GenBase._random.NextDouble() * 2.0 - 1.0;
         double num11 = 0.0;
         for (int m = 0; m <= num; m++)
         {
             double num12 = (double)num8 / (double)num7 * (double)(m - num7);
             int num13 = Math.Min(num8, (int)Math.Sqrt(Math.Max(0.0, (double)num9 - num12 * num12)));
             num11 = ((m >= num / 2) ? (num11 + Utils.Lerp(num10, value2, (double)m / (double)(num / 2) - 1.0)) : (num11 + Utils.Lerp(value, num10, (double)m / (double)(num / 2))));
             for (int n = num8 - num13; n <= num8 + num13; n++)
             {
                 PlaceSlab(_slabs[m + 1, n + 1], m * 3 + origin.X, n * 3 + origin.Y + (int)num11, 3);
             }
         }
         structures.AddStructure(new Rectangle(origin.X, origin.Y, num * 3, num2 * 3), 8);
         return true;
     }
References GenBase._random, _slabs, StructureMap.AddStructure(), WorldGen.BiomeTileCheck(), MarbleBiome.Slab.Create(), MarbleBiome.SlabStates.Empty(), IsGroupSolid(), Utils.Lerp(), UnifiedRandom.Next(), UnifiedRandom.NextDouble(), PlaceSlab(), SlabState(), SmoothSlope(), and MarbleBiome.SlabStates.Solid().