Terraria: MarbleBiome.SmoothSlope
SmoothSlope()
void MarbleBiome.SmoothSlope (int x, int y) inline private
     {
         Slab slab = _slabs[x, y];
         if (slab.IsSolid)
         {
             bool isSolid = _slabs[x, y - 1].IsSolid;
             bool isSolid2 = _slabs[x, y + 1].IsSolid;
             bool isSolid3 = _slabs[x - 1, y].IsSolid;
             bool isSolid4 = _slabs[x + 1, y].IsSolid;
             switch (((isSolid ? 1 : 0) << 3) | ((isSolid2 ? 1 : 0) << 2) | ((isSolid3 ? 1 : 0) << 1) | (isSolid4 ? 1 : 0))
             {
             case 10:
                 _slabs[x, y] = slab.WithState(SlabStates.TopLeftFilled);
                 break;
             case 9:
                 _slabs[x, y] = slab.WithState(SlabStates.TopRightFilled);
                 break;
             case 6:
                 _slabs[x, y] = slab.WithState(SlabStates.BottomLeftFilled);
                 break;
             case 5:
                 _slabs[x, y] = slab.WithState(SlabStates.BottomRightFilled);
                 break;
             case 4:
                 _slabs[x, y] = slab.WithState(SlabStates.HalfBrick);
                 break;
             default:
                 _slabs[x, y] = slab.WithState(SlabStates.Solid);
                 break;
             }
         }
     }
References _slabs, MarbleBiome.SlabStates.BottomLeftFilled(), MarbleBiome.SlabStates.BottomRightFilled(), MarbleBiome.SlabStates.HalfBrick(), MarbleBiome.Slab.IsSolid, MarbleBiome.SlabStates.Solid(), MarbleBiome.SlabStates.TopLeftFilled(), MarbleBiome.SlabStates.TopRightFilled(), and MarbleBiome.Slab.WithState().
Referenced by Place().