Terraria: System.Xml.Linq.XContainer.RemoveNode
RemoveNode()
void System.Xml.Linq.XContainer.RemoveNode (XNode n) inline package inherited
Definition at line 1274 of file XContainer.cs.
    {
        bool flag = NotifyChanging(n, XObjectChangeEventArgs.Remove);
        if (n.parent != this)
        {
            throw new InvalidOperationException(System.SR.InvalidOperation_ExternalCode);
        }
        XNode xNode = (XNode)content;
        while (xNode.next != n)
        {
            xNode = xNode.next;
        }
        if (xNode == n)
        {
            content = null;
        }
        else
        {
            if (content == n)
            {
                content = xNode;
            }
            xNode.next = n.next;
        }
        n.parent = null;
        n.next = null;
        if (flag)
        {
            NotifyChanged(n, XObjectChangeEventArgs.Remove);
        }
    }
References System.Xml.Linq.XNode.XNode(), System.Xml.Linq.XContainer.content, System.Xml.Dictionary, System.SR.InvalidOperation_ExternalCode, System.Xml.Linq.XObject.NotifyChanged(), System.Xml.Linq.XObject.NotifyChanging(), and System.Xml.Linq.XObjectChangeEventArgs.Remove.
Referenced by System.Xml.Linq.XNode.Remove(), System.Xml.Linq.XNode.ReplaceWith(), and System.Xml.Linq.XElement.SetElementValue().