Terraria: System.Xml.Linq.XContainer.AddContentToList
AddContentToList()
static void System.Xml.Linq.XContainer.AddContentToList (List< object > list, object content) inline static private inherited
Definition at line 1380 of file XContainer.cs.
    {
        IEnumerable enumerable = ((content is string) ? null : (content as IEnumerable));
        if (enumerable == null)
        {
            list.Add(content);
            return;
        }
        foreach (object item in enumerable)
        {
            if (item != null)
            {
                AddContentToList(list, item);
            }
        }
    }
References System.Xml.Linq.XContainer.AddContentToList(), System.Xml.Linq.XContainer.content, System.item, and System.list.
Referenced by System.Xml.Linq.XContainer.AddContentToList(), and System.Xml.Linq.XContainer.GetContentSnapshot().