Terraria: System.Xml.Linq.XContainer.Add
Add() [1/2]
void System.Xml.Linq.XContainer.Add (object? content) inline inherited
Definition at line 483 of file XContainer.cs.
    {
        if (SkipNotify())
        {
            AddContentSkipNotify(content);
        }
        else
        {
            if (content == null)
            {
                return;
            }
            if (content is XNode n)
            {
                AddNode(n);
                return;
            }
            if (content is string s)
            {
                AddString(s);
                return;
            }
            if (content is XAttribute a)
            {
                AddAttribute(a);
                return;
            }
            if (content is XStreamingElement other)
            {
                AddNode(new XElement(other));
                return;
            }
            if (content is object[] array)
            {
                object[] array2 = array;
                foreach (object obj in array2)
                {
                    Add(obj);
                }
                return;
            }
            if (content is IEnumerable enumerable)
            {
                {
                    foreach (object item in enumerable)
                    {
                        Add(item);
                    }
                    return;
                }
            }
            AddString(GetStringValue(content));
        }
    }
References System.Xml.Linq.Add, System.Xml.Linq.XContainer.AddAttribute(), System.Xml.Linq.XContainer.AddContentSkipNotify(), System.Xml.Linq.XContainer.AddNode(), System.Xml.Linq.XContainer.AddString(), System.array, System.Xml.Linq.XContainer.content, System.Xml.Linq.XContainer.GetStringValue(), System.item, System.obj, System.other, System.s, and System.Xml.Linq.XObject.SkipNotify().
Referenced by System.Xml.Linq.XNodeBuilder.AddNode(), System.Xml.Linq.XNodeBuilder.AddString(), System.Xml.Linq.XNodeBuilder.Close(), System.Xml.Schema.XNodeValidator.ValidateAttributes(), and System.Xml.Linq.XNodeBuilder.WriteEndAttribute().