Terraria: System.Xml.Linq.XContainer.AddString
AddString()
void System.Xml.Linq.XContainer.AddString (string s) inline package inherited
Definition at line 791 of file XContainer.cs.
    {
        ValidateString(s);
        if (content == null)
        {
            if (s.Length > 0)
            {
                AppendNode(new XText(s));
            }
            else if (this is XElement)
            {
                NotifyChanging(this, XObjectChangeEventArgs.Value);
                if (content != null)
                {
                    throw new InvalidOperationException(System.SR.InvalidOperation_ExternalCode);
                }
                content = s;
                NotifyChanged(this, XObjectChangeEventArgs.Value);
            }
            else
            {
                content = s;
            }
        }
        else if (s.Length > 0)
        {
            ConvertTextToNode();
            if (content is XText xText && !(xText is XCData))
            {
                xText.Value += s;
            }
            else
            {
                AppendNode(new XText(s));
            }
        }
    }
References System.Xml.Linq.XContainer.AppendNode(), System.Xml.Linq.XContainer.content, System.Xml.Linq.XContainer.ConvertTextToNode(), System.Xml.Dictionary, System.SR.InvalidOperation_ExternalCode, System.Xml.Linq.XObject.NotifyChanged(), System.Xml.Linq.XObject.NotifyChanging(), System.s, System.Xml.Linq.XContainer.ValidateString(), and System.Xml.Linq.XObjectChangeEventArgs.Value.
Referenced by System.Xml.Linq.XContainer.Add().