Terraria: System.Xml.Linq.XContainer.RemoveNodes
RemoveNodes()
void System.Xml.Linq.XContainer.RemoveNodes () inline inherited
Definition at line 625 of file XContainer.cs.
    {
        if (SkipNotify())
        {
            RemoveNodesSkipNotify();
            return;
        }
        while (content != null)
        {
            if (content is string text)
            {
                if (text.Length > 0)
                {
                    ConvertTextToNode();
                }
                else if (this is XElement)
                {
                    NotifyChanging(this, XObjectChangeEventArgs.Value);
                    if (text != content)
                    {
                        throw new InvalidOperationException(System.SR.InvalidOperation_ExternalCode);
                    }
                    content = null;
                    NotifyChanged(this, XObjectChangeEventArgs.Value);
                }
                else
                {
                    content = null;
                }
            }
            if (content is XNode { next: var xNode2 } xNode)
            {
                NotifyChanging(xNode2, XObjectChangeEventArgs.Remove);
                if (xNode != content || xNode2 != xNode.next)
                {
                    throw new InvalidOperationException(System.SR.InvalidOperation_ExternalCode);
                }
                if (xNode2 != xNode)
                {
                    xNode.next = xNode2.next;
                }
                else
                {
                    content = null;
                }
                xNode2.parent = null;
                xNode2.next = null;
                NotifyChanged(xNode2, XObjectChangeEventArgs.Remove);
            }
        }
    }
References System.Xml.Linq.XContainer.content, System.Xml.Linq.XContainer.ConvertTextToNode(), System.Xml.Dictionary, System.SR.InvalidOperation_ExternalCode, System.Xml.Linq.XNode.next, System.Xml.Linq.XObject.NotifyChanged(), System.Xml.Linq.XObject.NotifyChanging(), System.Xml.Linq.XObjectChangeEventArgs.Remove, System.Xml.Linq.XContainer.RemoveNodesSkipNotify(), System.Xml.Linq.XObject.SkipNotify(), System.text, and System.Xml.Linq.XObjectChangeEventArgs.Value.
Referenced by System.Xml.Linq.XElement.RemoveAll(), and System.Xml.Linq.XContainer.ReplaceNodes().