Terraria: System.Xml.Linq.XContainer.GetStringValue
GetStringValue()
static string System.Xml.Linq.XContainer.GetStringValue (object value) inline static package inherited
Definition at line 1100 of file XContainer.cs.
    {
        string text2;
        if (!(value is string text))
        {
            if (!(value is int num))
            {
                if (!(value is double num2))
                {
                    if (!(value is long num3))
                    {
                        if (!(value is float num4))
{
                            if (!(value is decimal num5))
{
                                if (!(value is short num6))
{
                                    if (!(value is sbyte b))
{
                                        if (!(value is bool flag))
{
                                            if (!(value is DateTime dateTime))
{
                                                if (!(value is DateTimeOffset dateTimeOffset))
{
                                                    if (!(value is TimeSpan timeSpan))
{
                                                        if (value is XObject)
{
                                                            throw new ArgumentException(System.SR.Argument_XObjectValue);
                                                        }
                                                        text2 = value.ToString();
                                                    }
                                                    else
{
                                                        text2 = XmlConvert.ToString(timeSpan);
                                                    }
                                                }
                                                else
{
                                                    text2 = XmlConvert.ToString(dateTimeOffset);
                                                }
                                            }
                                            else
{
                                                text2 = XmlConvert.ToString(dateTime, XmlDateTimeSerializationMode.RoundtripKind);
                                            }
                                        }
                                        else
{
                                            text2 = XmlConvert.ToString(flag);
                                        }
                                    }
                                    else
{
                                        text2 = XmlConvert.ToString(b);
                                    }
                                }
                                else
{
                                    text2 = XmlConvert.ToString(num6);
                                }
                            }
                            else
{
                                text2 = XmlConvert.ToString(num5);
                            }
                        }
                        else
{
                            text2 = XmlConvert.ToString(num4);
                        }
                    }
                    else
                    {
                        text2 = XmlConvert.ToString(num3);
                    }
                }
                else
                {
                    text2 = XmlConvert.ToString(num2);
                }
            }
            else
            {
                text2 = XmlConvert.ToString(num);
            }
        }
        else
        {
            text2 = text;
        }
        string text3 = text2;
        if (text3 == null)
        {
            throw new ArgumentException(System.SR.Argument_ConvertToString);
        }
        return text3;
    }
References System.SR.Argument_ConvertToString, System.SR.Argument_XObjectValue, System.Xml.ArgumentException, System.Xml.Dictionary, System.text, System.Xml.XmlConvert.ToString(), and System.value.
Referenced by System.Xml.Linq.XAttribute.XAttribute(), System.Xml.Linq.XContainer.Add(), System.Xml.Linq.Inserter.AddContent(), System.Xml.Linq.XContainer.AddContentSkipNotify(), System.Xml.Linq.XElement.SetAttributeValue(), System.Xml.Linq.XElement.SetElementValue(), System.Xml.Linq.XAttribute.SetValue(), System.Xml.Linq.XElement.SetValue(), and System.Xml.Linq.StreamingElementWriter.Write().