Terraria: System.Xml.Linq.XContainer.AddNodeSkipNotify
AddNodeSkipNotify()
void System.Xml.Linq.XContainer.AddNodeSkipNotify (XNode n) inline package inherited
Definition at line 768 of file XContainer.cs.
    {
        ValidateNode(n, this);
        if (n.parent != null)
        {
            n = n.CloneNode();
        }
        else
        {
            XNode xNode = this;
            while (xNode.parent != null)
            {
                xNode = xNode.parent;
            }
            if (n == xNode)
            {
                n = n.CloneNode();
            }
        }
        ConvertTextToNode();
        AppendNodeSkipNotify(n);
    }
References System.Xml.Linq.XContainer.AppendNodeSkipNotify(), System.Xml.Linq.XContainer.ConvertTextToNode(), and System.Xml.Linq.XContainer.ValidateNode().
Referenced by System.Xml.Linq.XContainer.AddContentSkipNotify(), System.Xml.Linq.XContainer.ContentReader.ReadContentFrom(), System.Xml.Linq.XContainer.ContentReader.ReadContentFrom(), System.Xml.Linq.XContainer.ContentReader.ReadContentFromAsync(), and System.Xml.Linq.XContainer.ContentReader.ReadContentFromAsync().