Terraria: System.Xml.Linq.XContainer.AddContentSkipNotify
AddContentSkipNotify()
void System.Xml.Linq.XContainer.AddContentSkipNotify (object content) inline package inherited
Definition at line 697 of file XContainer.cs.
    {
        if (content == null)
        {
            return;
        }
        if (content is XNode n)
        {
            AddNodeSkipNotify(n);
            return;
        }
        if (content is string s)
        {
            AddStringSkipNotify(s);
            return;
        }
        if (content is XAttribute a)
        {
            AddAttributeSkipNotify(a);
            return;
        }
        if (content is XStreamingElement other)
        {
            AddNodeSkipNotify(new XElement(other));
            return;
        }
        if (content is object[] array)
        {
            object[] array2 = array;
            foreach (object obj in array2)
            {
                AddContentSkipNotify(obj);
            }
            return;
        }
        if (content is IEnumerable enumerable)
        {
            {
                foreach (object item in enumerable)
                {
                    AddContentSkipNotify(item);
                }
                return;
            }
        }
        AddStringSkipNotify(GetStringValue(content));
    }
References System.Xml.Linq.XContainer.AddAttributeSkipNotify(), System.Xml.Linq.XContainer.AddContentSkipNotify(), System.Xml.Linq.XContainer.AddNodeSkipNotify(), System.Xml.Linq.XContainer.AddStringSkipNotify(), System.array, System.Xml.Linq.XContainer.content, System.Xml.Linq.XContainer.GetStringValue(), System.item, System.obj, System.other, and System.s.
Referenced by System.Xml.Linq.XDocument.XDocument(), System.Xml.Linq.XElement.XElement(), System.Xml.Linq.XElement.XElement(), System.Xml.Linq.XContainer.Add(), and System.Xml.Linq.XContainer.AddContentSkipNotify().