Terraria: System.Xml.Linq.XContainer.AddNode
AddNode()
void System.Xml.Linq.XContainer.AddNode (XNode n) inline package inherited
Definition at line 745 of file XContainer.cs.
    {
        ValidateNode(n, this);
        if (n.parent != null)
        {
            n = n.CloneNode();
        }
        else
        {
            XNode xNode = this;
            while (xNode.parent != null)
            {
                xNode = xNode.parent;
            }
            if (n == xNode)
            {
                n = n.CloneNode();
            }
        }
        ConvertTextToNode();
        AppendNode(n);
    }
References System.Xml.Linq.XContainer.AppendNode(), System.Xml.Linq.XContainer.ConvertTextToNode(), and System.Xml.Linq.XContainer.ValidateNode().
Referenced by System.Xml.Linq.XContainer.Add(), and System.Xml.Linq.XElement.SetElementValue().