Terraria: PortalHelper.TryPlacingPortal
TryPlacingPortal()
static int PortalHelper.TryPlacingPortal (Projectile theBolt, Vector2 velocity, Vector2 theCrashVelocity) inline static
     {
         Vector2 vector = velocity / velocity.Length();
         Point position = FindCollision(theBolt.position, theBolt.position + velocity + vector * 32f).ToTileCoordinates();
         Tile tile = Main.tile[position.X, position.Y];
         Vector2 vector2 = new Vector2(position.X * 16 + 8, position.Y * 16 + 8);
         if (!WorldGen.SolidOrSlopedTile(tile))
         {
             return -1;
         }
         int num = tile.slope();
         bool flag = tile.halfBrick();
         for (int i = 0; i < (flag ? 2 : EDGES.Length); i++)
         {
             if (Vector2.Dot(EDGES[i], vector) > 0f && FindValidLine(position, (int)EDGES[i].Y, (int)(0f - EDGES[i].X), out var bestPosition))
             {
                 vector2 = new Vector2(bestPosition.X * 16 + 8, bestPosition.Y * 16 + 8);
                 return AddPortal(theBolt, vector2 - EDGES[i] * (flag ? 0f : 8f), (float)Math.Atan2(EDGES[i].Y, EDGES[i].X) + (float)Math.PI / 2f, (int)theBolt.ai[0], theBolt.direction);
             }
         }
         if (num != 0)
         {
             Vector2 value = SLOPE_EDGES[num - 1];
             if (Vector2.Dot(value, -vector) > 0f && FindValidLine(position, -SLOPE_OFFSETS[num - 1].Y, SLOPE_OFFSETS[num - 1].X, out var bestPosition2))
             {
                 vector2 = new Vector2(bestPosition2.X * 16 + 8, bestPosition2.Y * 16 + 8);
                 return AddPortal(theBolt, vector2, (float)Math.Atan2(value.Y, value.X) - (float)Math.PI / 2f, (int)theBolt.ai[0], theBolt.direction);
             }
         }
         return -1;
     }
References AddPortal(), Projectile.ai, Entity.direction, EDGES, FindCollision(), FindValidLine(), Tile.halfBrick(), Entity.position, Tile.slope(), SLOPE_EDGES, SLOPE_OFFSETS, WorldGen.SolidOrSlopedTile(), Main.tile, X, and Y.
Referenced by Projectile.HandleMovement().