Terraria: PortalHelper.TryGoingThroughPortals
TryGoingThroughPortals()
static void PortalHelper.TryGoingThroughPortals (Entity ent) inline static
     {
         if (!anyPortalAtAll)
         {
             return;
         }
         float collisionPoint = 0f;
         _ = ent.velocity;
         int width = ent.width;
         int height = ent.height;
         int num = 1;
         if (ent is Player)
         {
             num = (int)((Player)ent).gravDir;
         }
         for (int i = 0; i < FoundPortals.GetLength(0); i++)
         {
             if (FoundPortals[i, 0] == -1 || FoundPortals[i, 1] == -1 || (ent is Player && (i >= PortalCooldownForPlayers.Length || PortalCooldownForPlayers[i] > 0)) || (ent is NPC && (i >= PortalCooldownForNPCs.Length || PortalCooldownForNPCs[i] > 0)))
             {
                 continue;
             }
             for (int j = 0; j < 2; j++)
             {
                 Projectile projectile = Main.projectile[FoundPortals[i, j]];
                 GetPortalEdges(projectile.Center, projectile.ai[0], out var start, out var end);
                 if (!Collision.CheckAABBvLineCollision(ent.position + ent.velocity, ent.Size, start, end, 2f, ref collisionPoint))
                 {
                     continue;
                 }
                 Projectile projectile2 = Main.projectile[FoundPortals[i, 1 - j]];
                 float num2 = ent.Hitbox.Distance(projectile.Center);
                 int bonusX;
                 int bonusY;
                 Vector2 vector = GetPortalOutingPoint(ent.Size, projectile2.Center, projectile2.ai[0], out bonusX, out bonusY) + Vector2.Normalize(new Vector2(bonusX, bonusY)) * num2;
                 Vector2 vector2 = Vector2.UnitX * 16f;
                 if (Collision.TileCollision(vector - vector2, vector2, width, height, fallThrough: true, fall2: true, num) != vector2)
                 {
                     continue;
                 }
                 vector2 = -Vector2.UnitX * 16f;
                 if (Collision.TileCollision(vector - vector2, vector2, width, height, fallThrough: true, fall2: true, num) != vector2)
                 {
                     continue;
                 }
                 vector2 = Vector2.UnitY * 16f;
                 if (Collision.TileCollision(vector - vector2, vector2, width, height, fallThrough: true, fall2: true, num) != vector2)
                 {
                     continue;
                 }
                 vector2 = -Vector2.UnitY * 16f;
                 if (Collision.TileCollision(vector - vector2, vector2, width, height, fallThrough: true, fall2: true, num) != vector2)
                 {
                     continue;
                 }
                 float num3 = 0.1f;
                 if (bonusY == -num)
                 {
                     num3 = 0.1f;
                 }
                 if (ent.velocity == Vector2.Zero)
                 {
                     ent.velocity = (projectile.ai[0] - (float)Math.PI / 2f).ToRotationVector2() * num3;
                 }
                 if (ent.velocity.Length() < num3)
                 {
                     ent.velocity.Normalize();
                     ent.velocity *= num3;
                 }
                 Vector2 vector3 = Vector2.Normalize(new Vector2(bonusX, bonusY));
                 if (vector3.HasNaNs() || vector3 == Vector2.Zero)
                 {
                     vector3 = Vector2.UnitX * ent.direction;
                 }
                 ent.velocity = vector3 * ent.velocity.Length();
                 if ((bonusY == -num && Math.Sign(ent.velocity.Y) != -num) || Math.Abs(ent.velocity.Y) < 0.1f)
                 {
                     ent.velocity.Y = (float)(-num) * 0.1f;
                 }
                 int num4 = (int)((float)(projectile2.owner * 2) + projectile2.ai[1]);
                 int lastPortalColorIndex = num4 + ((num4 % 2 == 0) ? 1 : (-1));
                 if (ent is Player)
                 {
                     Player player = (Player)ent;
                     player.lastPortalColorIndex = lastPortalColorIndex;
                     player.Teleport(vector, 4, num4);
                     if (Main.netMode == 1)
                     {
                         NetMessage.SendData(96, -1, -1, null, player.whoAmI, vector.X, vector.Y, num4);
                         NetMessage.SendData(13, -1, -1, null, player.whoAmI);
                     }
                     PortalCooldownForPlayers[i] = 10;
                 }
                 else if (ent is NPC)
                 {
                     NPC nPC = (NPC)ent;
                     nPC.lastPortalColorIndex = lastPortalColorIndex;
                     nPC.Teleport(vector, 4, num4);
                     if (Main.netMode == 2)
                     {
                         NetMessage.SendData(100, -1, -1, null, nPC.whoAmI, vector.X, vector.Y, num4);
                         NetMessage.SendData(23, -1, -1, null, nPC.whoAmI);
                     }
                     PortalCooldownForPlayers[i] = 10;
                     if (bonusY == -1 && ent.velocity.Y > -3f)
                     {
                         ent.velocity.Y = -3f;
                     }
                 }
                 return;
             }
         }
     }
References Projectile.ai, anyPortalAtAll, Entity.Center, Collision.CheckAABBvLineCollision(), Entity.direction, FoundPortals, GetPortalEdges(), GetPortalOutingPoint(), Entity.height, Entity.Hitbox, NPC.lastPortalColorIndex, Player.lastPortalColorIndex, Main.netMode, NPC, Projectile.owner, Player, PortalCooldownForNPCs, PortalCooldownForPlayers, Entity.position, Main.projectile, NetMessage.SendData(), Entity.Size, NPC.Teleport(), Player.Teleport(), Collision.TileCollision(), Entity.velocity, Entity.whoAmI, and Entity.width.
Referenced by NPC.TryPortalJumping(), and Player.TryPortalJumping().