Terraria: AchievementCondition.Complete
Complete()
virtual void AchievementCondition.Complete () inline virtual inherited
Reimplemented in CustomIntCondition, and CustomFloatCondition.
     {
         if (!_isCompleted)
         {
             _isCompleted = true;
             if (this.OnComplete != null)
             {
                 this.OnComplete(this);
             }
         }
     }
References AchievementCondition._isCompleted, and AchievementCondition.OnComplete.
Referenced by AchievementsHelper.HandleAnglerService(), AchievementsHelper.HandleOnEquip(), AchievementsHelper.HandleSpecialEvent(), ItemCraftCondition.ItemCraftListener(), ItemPickupCondition.ItemPickupListener(), Projectile.Kill(), NPCKilledCondition.NPCKilledListener(), AchievementsHelper.OnPlayerEnteredWorld(), ProgressionEventCondition.ProgressionEventListener(), and TileDestroyedListener().