Terraria: PortalHelper.SupportedTilesAreFine
SupportedTilesAreFine()
static bool PortalHelper.SupportedTilesAreFine (Vector2 portalCenter, float portalAngle) inline static
     {
         Point point = portalCenter.ToTileCoordinates();
         int num = (int)Math.Round(MathHelper.WrapAngle(portalAngle) / ((float)Math.PI / 4f));
         int num2;
         int num3;
         switch (num)
         {
         case -2:
         case 2:
             num2 = ((num != 2) ? 1 : (-1));
             num3 = 0;
             break;
         case 0:
         case 4:
             num2 = 0;
             num3 = ((num == 0) ? 1 : (-1));
             break;
         case -3:
         case 3:
             num2 = ((num == -3) ? 1 : (-1));
             num3 = -1;
             break;
         case -1:
         case 1:
             num2 = ((num == -1) ? 1 : (-1));
             num3 = 1;
             break;
         default:
             Main.NewText("Broken portal! (over4s = " + num + " , " + portalAngle + ")");
             return false;
         }
         if (num2 != 0 && num3 != 0)
         {
             int num4 = 3;
             if (num2 == -1 && num3 == 1)
             {
                 num4 = 5;
             }
             if (num2 == 1 && num3 == -1)
             {
                 num4 = 2;
             }
             if (num2 == 1 && num3 == 1)
             {
                 num4 = 4;
             }
             num4--;
             if (SupportedSlope(point.X, point.Y, num4) && SupportedSlope(point.X + num2, point.Y - num3, num4))
             {
                 return SupportedSlope(point.X - num2, point.Y + num3, num4);
             }
             return false;
         }
         if (num2 != 0)
         {
             if (num2 == 1)
             {
                 point.X--;
             }
             if (SupportedNormal(point.X, point.Y) && SupportedNormal(point.X, point.Y - 1))
             {
                 return SupportedNormal(point.X, point.Y + 1);
             }
             return false;
         }
         if (num3 != 0)
         {
             if (num3 == 1)
             {
                 point.Y--;
             }
             if (!SupportedNormal(point.X, point.Y) || !SupportedNormal(point.X + 1, point.Y) || !SupportedNormal(point.X - 1, point.Y))
             {
                 if (SupportedHalfbrick(point.X, point.Y) && SupportedHalfbrick(point.X + 1, point.Y))
                 {
                     return SupportedHalfbrick(point.X - 1, point.Y);
                 }
                 return false;
             }
             return true;
         }
         return true;
     }
References Main.NewText(), SupportedHalfbrick(), SupportedNormal(), and SupportedSlope().
Referenced by AddPortal().