Terraria: IPCServer.StartListen
StartListen()
void IPCServer.StartListen () inline
     {
         LazyCreatePipe();
         WeGameHelper.WriteDebugString("begin listen");
         GetPipeStream().BeginWaitForConnection(ConnectionCallback, _cancelTokenSrc.Token);
     }
References IPCBase._cancelTokenSrc, ConnectionCallback(), GetPipeStream(), LazyCreatePipe(), and WeGameHelper.WriteDebugString().
Referenced by RestartListen(), and MessageDispatcherServer.Start().