Terraria: System.Web.HttpUtility.HttpQSCollection.ToString
ToString()
override string System.Web.HttpUtility.HttpQSCollection.ToString () inline
Definition at line 19 of file HttpUtility.cs.
        {
            int count = Count;
            if (count == 0)
            {
                return "";
            }
            StringBuilder stringBuilder = new StringBuilder();
            string[] allKeys = AllKeys;
            for (int i = 0; i < count; i++)
            {
                string text = allKeys[i];
                string[] values = GetValues(text);
                if (values == null)
                {
                    continue;
                }
                string[] array = values;
                foreach (string str in array)
                {
                    if (!string.IsNullOrEmpty(text))
                    {
                        stringBuilder.Append(text).Append('=');
                    }
                    stringBuilder.Append(UrlEncode(str)).Append('&');
                }
            }
            return stringBuilder.ToString(0, stringBuilder.Length - 1);
        }
References System.Collections.Specialized.NameValueCollection.AllKeys, System.Text.StringBuilder.Append(), System.array, System.Collections.Specialized.NameObjectCollectionBase.Count, System.count, System.Collections.Specialized.NameValueCollection.GetValues(), System.Text.StringBuilder.Length, System.str, System.text, System.Text.StringBuilder.ToString(), System.Web.HttpUtility.UrlEncode(), and System.values.