Terraria: Segments.SpriteSegment.Draw
Draw()
override void Segments.SpriteSegment.Draw (ref GameAnimationSegment info) inline virtual
Implements Segments.AnimationSegmentWithActions< LooseSprite >.
         {
             if (!((float)info.TimeInAnimation > (float)_targetTime + base.DedicatedTimeNeeded) && info.TimeInAnimation >= _targetTime)
             {
                 ResetSpriteAnimation(ref info);
                 float localTimeForObject = info.TimeInAnimation - _targetTime;
                 ProcessActions(_sprite, localTimeForObject);
                 DrawData drawData = _sprite.CurrentDrawData;
                 drawData.position += info.AnchorPositionOnScreen + _anchorOffset;
                 drawData.color *= _sprite.CurrentOpacity * info.DisplayOpacity;
                 if (_shaderEffect != null)
                 {
                     _shaderEffect.BeforeDrawing(ref info, ref drawData);
                 }
                 drawData.Draw(info.SpriteBatch);
                 if (_shaderEffect != null)
                 {
                     _shaderEffect.AfterDrawing(ref info, ref drawData);
                 }
             }
         }
References Segments.SpriteSegment._anchorOffset, Segments.SpriteSegment._shaderEffect, Segments.SpriteSegment._sprite, Segments.AnimationSegmentWithActions< LooseSprite >._targetTime, Segments.SpriteSegment.IShaderEffect.AfterDrawing(), Segments.SpriteSegment.IShaderEffect.BeforeDrawing(), DrawData.color, Segments.LooseSprite.CurrentDrawData, Segments.LooseSprite.CurrentOpacity, DrawData.Draw(), DrawData.position, Segments.AnimationSegmentWithActions< LooseSprite >.ProcessActions(), and Segments.SpriteSegment.ResetSpriteAnimation().