Terraria: System.Runtime.Serialization.Formatters.Binary.BinaryArray.Write
Write()
void System.Runtime.Serialization.Formatters.Binary.BinaryArray.Write (BinaryFormatterWriter output) inline
Definition at line 60 of file BinaryArray.cs.
    {
        switch (_binaryHeaderEnum)
        {
        case BinaryHeaderEnum.ArraySinglePrimitive:
            output.WriteByte((byte)_binaryHeaderEnum);
            output.WriteInt32(_objectId);
            output.WriteInt32(_lengthA[0]);
            output.WriteByte((byte)(InternalPrimitiveTypeE)_typeInformation);
            return;
        case BinaryHeaderEnum.ArraySingleString:
            output.WriteByte((byte)_binaryHeaderEnum);
            output.WriteInt32(_objectId);
            output.WriteInt32(_lengthA[0]);
            return;
        case BinaryHeaderEnum.ArraySingleObject:
            output.WriteByte((byte)_binaryHeaderEnum);
            output.WriteInt32(_objectId);
            output.WriteInt32(_lengthA[0]);
            return;
        }
        output.WriteByte((byte)_binaryHeaderEnum);
        output.WriteInt32(_objectId);
        output.WriteByte((byte)_binaryArrayTypeEnum);
        output.WriteInt32(_rank);
        for (int i = 0; i < _rank; i++)
        {
            output.WriteInt32(_lengthA[i]);
        }
        if (_binaryArrayTypeEnum == BinaryArrayTypeEnum.SingleOffset || _binaryArrayTypeEnum == BinaryArrayTypeEnum.JaggedOffset || _binaryArrayTypeEnum == BinaryArrayTypeEnum.RectangularOffset)
        {
            for (int j = 0; j < _rank; j++)
            {
                output.WriteInt32(_lowerBoundA[j]);
            }
        }
        output.WriteByte((byte)_binaryTypeEnum);
        BinaryTypeConverter.WriteTypeInfo(_binaryTypeEnum, _typeInformation, _assemId, output);
    }
References System.Runtime.Serialization.Formatters.Binary.BinaryArray._assemId, System.Runtime.Serialization.Formatters.Binary.BinaryArray._binaryArrayTypeEnum, System.Runtime.Serialization.Formatters.Binary.BinaryArray._binaryHeaderEnum, System.Runtime.Serialization.Formatters.Binary.BinaryArray._binaryTypeEnum, System.Runtime.Serialization.Formatters.Binary.BinaryArray._lengthA, System.Runtime.Serialization.Formatters.Binary.BinaryArray._lowerBoundA, System.Runtime.Serialization.Formatters.Binary.BinaryArray._objectId, System.Runtime.Serialization.Formatters.Binary.BinaryArray._rank, System.Runtime.Serialization.Formatters.Binary.BinaryArray._typeInformation, System.Runtime.Serialization.Dictionary, and System.Runtime.Serialization.Formatters.Binary.BinaryTypeConverter.WriteTypeInfo().
Referenced by System.Runtime.Serialization.Formatters.Binary.BinaryFormatterWriter.WriteJaggedArray(), System.Runtime.Serialization.Formatters.Binary.BinaryFormatterWriter.WriteRectangleArray(), and System.Runtime.Serialization.Formatters.Binary.BinaryFormatterWriter.WriteSingleArray().