Terraria: System.Runtime.Serialization.Formatters.Binary.BinaryArray.Set
Set()
void System.Runtime.Serialization.Formatters.Binary.BinaryArray.Set (int objectId, int rank, int[] lengthA, int[] lowerBoundA, BinaryTypeEnum binaryTypeEnum, object typeInformation, BinaryArrayTypeEnum binaryArrayTypeEnum, int assemId) inline package
Definition at line 32 of file BinaryArray.cs.
    {
        _objectId = objectId;
        _binaryArrayTypeEnum = binaryArrayTypeEnum;
        _rank = rank;
        _lengthA = lengthA;
        _lowerBoundA = lowerBoundA;
        _binaryTypeEnum = binaryTypeEnum;
        _typeInformation = typeInformation;
        _assemId = assemId;
        _binaryHeaderEnum = BinaryHeaderEnum.Array;
        if (binaryArrayTypeEnum == BinaryArrayTypeEnum.Single)
        {
            switch (binaryTypeEnum)
            {
            case BinaryTypeEnum.Primitive:
                _binaryHeaderEnum = BinaryHeaderEnum.ArraySinglePrimitive;
                break;
            case BinaryTypeEnum.String:
                _binaryHeaderEnum = BinaryHeaderEnum.ArraySingleString;
                break;
            case BinaryTypeEnum.Object:
                _binaryHeaderEnum = BinaryHeaderEnum.ArraySingleObject;
                break;
            }
        }
    }
References System.Runtime.Serialization.Formatters.Binary.BinaryArray._assemId, System.Runtime.Serialization.Formatters.Binary.BinaryArray._binaryArrayTypeEnum, System.Runtime.Serialization.Formatters.Binary.BinaryArray._binaryHeaderEnum, System.Runtime.Serialization.Formatters.Binary.BinaryArray._binaryTypeEnum, System.Runtime.Serialization.Formatters.Binary.BinaryArray._lengthA, System.Runtime.Serialization.Formatters.Binary.BinaryArray._lowerBoundA, System.Runtime.Serialization.Formatters.Binary.BinaryArray._objectId, System.Runtime.Serialization.Formatters.Binary.BinaryArray._rank, System.Runtime.Serialization.Formatters.Binary.BinaryArray._typeInformation, and System.Runtime.Serialization.Dictionary.
Referenced by System.Runtime.Serialization.Formatters.Binary.BinaryFormatterWriter.WriteJaggedArray(), System.Runtime.Serialization.Formatters.Binary.BinaryFormatterWriter.WriteRectangleArray(), and System.Runtime.Serialization.Formatters.Binary.BinaryFormatterWriter.WriteSingleArray().