Terraria: Microsoft.Xna.Framework.Rectangle.Intersect
Intersect() [1/2]
static Rectangle Microsoft.Xna.Framework.Rectangle.Intersect (Rectangle value1, Rectangle value2) inline static
Definition at line 143 of file Rectangle.cs.
    {
        int num = value1.X + value1.Width;
        int num2 = value2.X + value2.Width;
        int num3 = value1.Y + value1.Height;
        int num4 = value2.Y + value2.Height;
        int num5 = ((value1.X > value2.X) ? value1.X : value2.X);
        int num6 = ((value1.Y > value2.Y) ? value1.Y : value2.Y);
        int num7 = ((num < num2) ? num : num2);
        int num8 = ((num3 < num4) ? num3 : num4);
        Rectangle result = default(Rectangle);
        if (num7 > num5 && num8 > num6)
        {
            result.X = num5;
            result.Y = num6;
            result.Width = num7 - num5;
            result.Height = num8 - num6;
        }
        else
        {
            result.X = 0;
            result.Y = 0;
            result.Width = 0;
            result.Height = 0;
        }
        return result;
    }
References Microsoft.Xna.Framework.Rectangle.Height, Microsoft.Xna.Framework.Rectangle.Width, Microsoft.Xna.Framework.Rectangle.X, and Microsoft.Xna.Framework.Rectangle.Y.
Referenced by Terraria.Graphics.Capture.CaptureInterface.ModeDragBounds.DragBounds(), Terraria.Graphics.Capture.CaptureInterface.ModeEdgeSelection.DrawMarkedArea(), Terraria.Graphics.Capture.CaptureInterface.ModeDragBounds.DrawMarkedArea(), Terraria.Graphics.Light.LightingEngine.ExportToMiniMap(), Terraria.Player.FindSharpTearsSpot(), Terraria.NPC.GetFairyTreasureCoords(), Terraria.GameContent.DoorOpeningHelper.CommonDoorOpeningInfoProvider.TryCloseDoor(), and Terraria.GameContent.DoorOpeningHelper.TallGateOpeningInfoProvider.TryCloseDoor().