Terraria: Microsoft.Xna.Framework.Rectangle.Union
Union() [1/2]
static Rectangle Microsoft.Xna.Framework.Rectangle.Union (Rectangle value1, Rectangle value2) inline static
Definition at line 197 of file Rectangle.cs.
    {
        int num = value1.X + value1.Width;
        int num2 = value2.X + value2.Width;
        int num3 = value1.Y + value1.Height;
        int num4 = value2.Y + value2.Height;
        int num5 = ((value1.X < value2.X) ? value1.X : value2.X);
        int num6 = ((value1.Y < value2.Y) ? value1.Y : value2.Y);
        int num7 = ((num > num2) ? num : num2);
        int num8 = ((num3 > num4) ? num3 : num4);
        Rectangle result = default(Rectangle);
        result.X = num5;
        result.Y = num6;
        result.Width = num7 - num5;
        result.Height = num8 - num6;
        return result;
    }
References Microsoft.Xna.Framework.Rectangle.Height, Microsoft.Xna.Framework.Rectangle.Width, Microsoft.Xna.Framework.Rectangle.X, and Microsoft.Xna.Framework.Rectangle.Y.
Referenced by Terraria.NPC.AI_AttemptToFindTeleportSpot(), Terraria.GameContent.Events.ScreenObstruction.Draw(), Terraria.GameContent.DoorOpeningHelper.GetPlayerInfoForOpeningDoor(), and Terraria.Wiring.TeleporterHitboxIntersects().