Terraria: Microsoft.Xna.Framework.Rectangle.Inflate
Inflate()
void Microsoft.Xna.Framework.Rectangle.Inflate (int horizontalAmount, int verticalAmount) inline
Definition at line 84 of file Rectangle.cs.
    {
        X -= horizontalAmount;
        Y -= verticalAmount;
        Width += horizontalAmount * 2;
        Height += verticalAmount * 2;
    }
References Microsoft.Xna.Framework.Rectangle.Height, Microsoft.Xna.Framework.Rectangle.Width, Microsoft.Xna.Framework.Rectangle.X, and Microsoft.Xna.Framework.Rectangle.Y.
Referenced by Terraria.Projectile.Colliding(), Terraria.Projectile.Damage_GetHitbox(), Terraria.GameContent.Events.ScreenObstruction.Draw(), Terraria.GameContent.UI.BigProgressBar.BigProgressBarHelper.DrawBareBonesBar(), Terraria.GameContent.UI.Elements.UIVerticalSlider.DrawValueBarDynamicWidth(), Terraria.Collision.StepConveyorBelt(), and Terraria.GameContent.Bestiary.CustomEntryIcon.UpdateUnlockState().