Terraria: System.Reflection.Internal.AbstractMemoryBlock.GetReader
GetReader()
unsafe BlobReader System.Reflection.Internal.AbstractMemoryBlock.GetReader () inline inherited
Definition at line 12 of file AbstractMemoryBlock.cs.
    {
        return new BlobReader(Pointer, Size);
    }
References System.Reflection.Internal.AbstractMemoryBlock.Size.
Referenced by System.Reflection.PortableExecutable.PEReader.DecodeCodeViewDebugDirectoryData(), System.Reflection.PortableExecutable.PEReader.DecodeEmbeddedPortablePdbDebugDirectoryData(), and System.Reflection.PortableExecutable.PEReader.DecodePdbChecksumDebugDirectoryData().