Terraria: System.Reflection.Internal.AbstractMemoryBlock.GetContentUnchecked
GetContentUnchecked()
virtual unsafe ImmutableArray< byte > System.Reflection.Internal.AbstractMemoryBlock.GetContentUnchecked (int start, int length) inline virtual inherited
Reimplemented in System.Reflection.Internal.ByteArrayMemoryBlock.
Definition at line 17 of file AbstractMemoryBlock.cs.
    {
        ImmutableArray<byte> result = BlobUtilities.ReadImmutableBytes(Pointer + start, length);
        GC.KeepAlive(this);
        return result;
    }
References System.GC.KeepAlive(), System.length, System.Reflection.BlobUtilities.ReadImmutableBytes(), and System.start.
Referenced by System.Reflection.PortableExecutable.PEMemoryBlock.GetContent(), and System.Reflection.PortableExecutable.PEMemoryBlock.GetContent().