Terraria: System.Xml.Xsl.Runtime.StringConcat.GetResult
GetResult()
string System.Xml.Xsl.Runtime.StringConcat.GetResult () inline
Definition at line 52 of file StringConcat.cs.
    {
        return _idxStr switch
        {
            0 => string.Empty,
            1 => _s1 ?? string.Empty,
            2 => _s1 + _s2,
            3 => _s1 + _s2 + _s3,
            4 => _s1 + _s2 + _s3 + _s4,
            _ => string.Concat(_strList.ToArray()),
        };
    }
References System.Xml.Xsl.Runtime.StringConcat._idxStr, System.Xml.Xsl.Runtime.StringConcat._s1, System.Xml.Xsl.Runtime.StringConcat._s2, System.Xml.Xsl.Runtime.StringConcat._s3, System.Xml.Xsl.Runtime.StringConcat._s4, System.Xml.Xsl.Runtime.StringConcat._strList, and System.Collections.Generic.List< T >.ToArray().
Referenced by System.Xml.XmlEventCache.EventsToString(), System.Xml.XmlEventCache.EventsToWriter(), System.Xml.XmlEventCache.NewEvent(), System.Xml.Xsl.Xslt.XsltInput.ReadAttribute(), System.Xml.Xsl.Runtime.XmlQueryOutput.WriteEndComment(), System.Xml.Xsl.Runtime.XmlQueryOutput.WriteEndNamespace(), and System.Xml.Xsl.Runtime.XmlQueryOutput.WriteEndProcessingInstruction().