Terraria: System.Xml.Xsl.Runtime.StringConcat.ConcatNoDelimiter
ConcatNoDelimiter()
void System.Xml.Xsl.Runtime.StringConcat.ConcatNoDelimiter (string s) inline package
Definition at line 65 of file StringConcat.cs.
    {
        switch (_idxStr)
        {
        case 0:
            _s1 = s;
            break;
        case 1:
            _s2 = s;
            break;
        case 2:
            _s3 = s;
            break;
        case 3:
            _s4 = s;
            break;
        case 4:
        {
            int capacity = ((_strList == null) ? 8 : _strList.Count);
            List<string> list = (_strList = new List<string>(capacity));
            list.Add(_s1);
            list.Add(_s2);
            list.Add(_s3);
            list.Add(_s4);
            goto default;
        }
        default:
            _strList.Add(s);
            break;
        }
        _idxStr++;
    }
References System.Xml.Xsl.Runtime.StringConcat._idxStr, System.Xml.Xsl.Runtime.StringConcat._s1, System.Xml.Xsl.Runtime.StringConcat._s2, System.Xml.Xsl.Runtime.StringConcat._s3, System.Xml.Xsl.Runtime.StringConcat._s4, System.Xml.Xsl.Runtime.StringConcat._strList, System.Collections.Generic.List< T >.Add(), System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.capacity, System.Collections.Generic.List< T >.Count, System.list, and System.s.
Referenced by System.Xml.Xsl.Runtime.StringConcat.Concat(), System.Xml.Xsl.Runtime.XmlQueryOutput.WriteCommentString(), System.Xml.Xsl.Runtime.XmlQueryOutput.WriteNamespaceString(), System.Xml.Xsl.Runtime.XmlQueryOutput.WriteProcessingInstructionString(), and System.Xml.XmlEventCache.WriteString().