Terraria: System.Xml.Xsl.Runtime.StringConcat.Clear
Clear()
void System.Xml.Xsl.Runtime.StringConcat.Clear () inline
Definition at line 37 of file StringConcat.cs.
    {
        _idxStr = 0;
        _delimiter = null;
    }
References System.Xml.Xsl.Runtime.StringConcat._delimiter, and System.Xml.Xsl.Runtime.StringConcat._idxStr.
Referenced by System.Xml.XmlEventCache.NewEvent(), System.Xml.Xsl.Xslt.XsltInput.ReadAttribute(), System.Xml.Xsl.Runtime.XmlQueryOutput.WriteStartComment(), System.Xml.Xsl.Runtime.XmlQueryOutput.WriteStartNamespace(), and System.Xml.Xsl.Runtime.XmlQueryOutput.WriteStartProcessingInstruction().