Terraria: System.Data.DataTable.AddUniqueKey
AddUniqueKey() [2/2]
DataColumn System.Data.DataTable.AddUniqueKey (int position) inline package inherited
Definition at line 4254 of file DataTable.cs.
    {
        if (_colUnique != null)
        {
            return _colUnique;
        }
        DataColumn[] primaryKey = PrimaryKey;
        if (primaryKey.Length == 1)
        {
            return primaryKey[0];
        }
        string columnName = XMLSchema.GenUniqueColumnName(TableName + "_Id", this);
        DataColumn dataColumn = new DataColumn(columnName, typeof(int), null, MappingType.Hidden);
        dataColumn.Prefix = _tablePrefix;
        dataColumn.AutoIncrement = true;
        dataColumn.AllowDBNull = false;
        dataColumn.Unique = true;
        if (position == -1)
        {
            Columns.Add(dataColumn);
        }
        else
        {
            for (int num = Columns.Count - 1; num >= position; num--)
            {
                Columns[num].SetOrdinalInternal(num + 1);
            }
            Columns.AddAt(position, dataColumn);
            dataColumn.SetOrdinalInternal(position);
        }
        if (primaryKey.Length == 0)
        {
            PrimaryKey = new DataColumn[1] { dataColumn };
        }
        _colUnique = dataColumn;
        return _colUnique;
    }
References System.Data.DataTable._colUnique, System.Data.DataTable._tablePrefix, System.Data.DataColumnCollection.Add(), System.Data.DataColumnCollection.AddAt(), System.Data.DataTable.Columns, System.Data.InternalDataCollectionBase.Count, System.Runtime.Serialization.Dictionary, System.Data.XMLSchema.GenUniqueColumnName(), System.Data.DataTable.PrimaryKey, and System.Data.DataTable.TableName.