Terraria: System.Data.DataTable.FindByPrimaryKey
FindByPrimaryKey() [2/2]
DataRow System.Data.DataTable.FindByPrimaryKey (object[] values) inline package inherited
Definition at line 2728 of file DataTable.cs.
    {
        CheckPrimaryKey();
        return FindRow(_primaryKey.Key, values);
    }
References System.Data.DataTable._primaryKey, System.Data.DataTable.CheckPrimaryKey(), System.Data.DataTable.FindRow(), System.Data.UniqueConstraint.Key, and System.values.
Referenced by System.Data.DataRowCollection.Contains(), System.Data.DataRowCollection.Contains(), System.Data.DataRowCollection.Find(), and System.Data.DataRowCollection.Find().