Terraria: System.Data.DataTable.SerializeTableData
SerializeTableData()
void System.Data.DataTable.SerializeTableData (SerializationInfo info, StreamingContext context, int serIndex) inline package inherited
Definition at line 1508 of file DataTable.cs.
    {
        int count = Columns.Count;
        int count2 = Rows.Count;
        int num = 0;
        int num2 = 0;
        BitArray bitArray = new BitArray(count2 * 3, defaultValue: false);
        for (int i = 0; i < count2; i++)
        {
            int num3 = i * 3;
            DataRow dataRow = Rows[i];
            DataRowState rowState = dataRow.RowState;
            switch (rowState)
            {
            case DataRowState.Added:
                bitArray[num3 + 1] = true;
                break;
            case DataRowState.Modified:
                bitArray[num3] = true;
                num++;
                break;
            case DataRowState.Deleted:
                bitArray[num3] = true;
                bitArray[num3 + 1] = true;
                break;
            default:
                throw ExceptionBuilder.InvalidRowState(rowState);
            case DataRowState.Unchanged:
                break;
            }
            if (-1 != dataRow._tempRecord)
            {
                bitArray[num3 + 2] = true;
                num2++;
            }
        }
        int num4 = count2 + num + num2;
        ArrayList arrayList = new ArrayList();
        ArrayList arrayList2 = new ArrayList();
        if (num4 > 0)
        {
            for (int j = 0; j < count; j++)
            {
                object emptyColumnStore = Columns[j].GetEmptyColumnStore(num4);
                arrayList.Add(emptyColumnStore);
                BitArray value = new BitArray(num4);
                arrayList2.Add(value);
            }
        }
        int num5 = 0;
        Hashtable hashtable = new Hashtable();
        Hashtable hashtable2 = new Hashtable();
        for (int k = 0; k < count2; k++)
        {
            int num6 = Rows[k].CopyValuesIntoStore(arrayList, arrayList2, num5);
            GetRowAndColumnErrors(k, hashtable, hashtable2);
            num5 += num6;
        }
        IFormatProvider invariantCulture = CultureInfo.InvariantCulture;
        info.AddValue(string.Format(invariantCulture, "DataTable_{0}.Rows.Count", serIndex), count2);
        info.AddValue(string.Format(invariantCulture, "DataTable_{0}.Records.Count", serIndex), num4);
        info.AddValue(string.Format(invariantCulture, "DataTable_{0}.RowStates", serIndex), bitArray);
        info.AddValue(string.Format(invariantCulture, "DataTable_{0}.Records", serIndex), arrayList);
        info.AddValue(string.Format(invariantCulture, "DataTable_{0}.NullBits", serIndex), arrayList2);
        info.AddValue(string.Format(invariantCulture, "DataTable_{0}.RowErrors", serIndex), hashtable);
        info.AddValue(string.Format(invariantCulture, "DataTable_{0}.ColumnErrors", serIndex), hashtable2);
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Data.DataTable.Columns, System.Data.DataRowCollection.Count, System.Data.InternalDataCollectionBase.Count, System.count, System.Runtime.Serialization.Dictionary, System.Format, System.Data.DataTable.GetRowAndColumnErrors(), System.info, System.Data.ExceptionBuilder.InvalidRowState(), System.Globalization.CultureInfo.InvariantCulture, System.Data.DataTable.Rows, and System.value.
Referenced by System.Data.DataTable.SerializeDataTable().