Terraria: System.Data.DataTable.ReadXml
ReadXml() [6/7]
XmlReadMode System.Data.DataTable.ReadXml (XmlReader reader, XmlReadMode mode, bool denyResolving) inline package inherited
Definition at line 5266 of file DataTable.cs.
    {
        IDisposable disposable = null;
        RowDiffIdUsageSection rowDiffIdUsageSection = default(RowDiffIdUsageSection);
        try
        {
            disposable = TypeLimiter.EnterRestrictedScope(this);
            bool flag = false;
            bool flag2 = false;
            bool isXdr = false;
            int depth = -1;
            XmlReadMode result = mode;
            rowDiffIdUsageSection.Prepare(this);
            if (reader == null)
            {
                return result;
            }
            bool flag3 = false;
            if (DataSet != null)
            {
                flag3 = DataSet.EnforceConstraints;
                DataSet.EnforceConstraints = false;
            }
            else
            {
                flag3 = EnforceConstraints;
                EnforceConstraints = false;
            }
            if (reader is XmlTextReader)
            {
                ((XmlTextReader)reader).WhitespaceHandling = WhitespaceHandling.Significant;
            }
            XmlDocument xmlDocument = new XmlDocument();
            if (mode != XmlReadMode.Fragment && reader.NodeType == XmlNodeType.Element)
            {
                depth = reader.Depth;
            }
            reader.MoveToContent();
            if (Columns.Count == 0 && IsEmptyXml(reader))
            {
                reader.Read();
                return result;
            }
            XmlDataLoader xmlDataLoader = null;
            if (reader.NodeType == XmlNodeType.Element)
            {
                XmlElement xmlElement = null;
                if (mode == XmlReadMode.Fragment)
                {
                    xmlDocument.AppendChild(xmlDocument.CreateElement("ds_sqlXmlWraPPeR"));
                    xmlElement = xmlDocument.DocumentElement;
                }
                else
                {
                    if (reader.LocalName == "diffgram" && reader.NamespaceURI == "urn:schemas-microsoft-com:xml-diffgram-v1")
                    {
                        if (mode == XmlReadMode.DiffGram || mode == XmlReadMode.IgnoreSchema)
{
                            if (Columns.Count == 0)
{
                                if (reader.IsEmptyElement)
{
                                    reader.Read();
                                    return XmlReadMode.DiffGram;
                                }
                                throw ExceptionBuilder.DataTableInferenceNotSupported();
                            }
                            ReadXmlDiffgram(reader);
                            ReadEndElement(reader);
                        }
                        else
{
                            reader.Skip();
                        }
                        RestoreConstraint(flag3);
                        return result;
                    }
                    if (reader.LocalName == "Schema" && reader.NamespaceURI == "urn:schemas-microsoft-com:xml-data")
                    {
                        if (mode != XmlReadMode.IgnoreSchema && mode != XmlReadMode.InferSchema)
{
                            ReadXDRSchema(reader);
                        }
                        else
{
                            reader.Skip();
                        }
                        RestoreConstraint(flag3);
                        return result;
                    }
                    if (reader.LocalName == "schema" && reader.NamespaceURI == "http://www.w3.org/2001/XMLSchema")
                    {
                        if (mode != XmlReadMode.IgnoreSchema && mode != XmlReadMode.InferSchema)
{
                            ReadXmlSchema(reader, denyResolving);
                        }
                        else
{
                            reader.Skip();
                        }
                        RestoreConstraint(flag3);
                        return result;
                    }
                    if (reader.LocalName == "schema" && reader.NamespaceURI.StartsWith("http://www.w3.org/", StringComparison.Ordinal))
                    {
                        if (DataSet != null)
{
                            DataSet.RestoreEnforceConstraints(flag3);
                        }
                        else
{
                            _enforceConstraints = flag3;
                        }
                        throw ExceptionBuilder.DataSetUnsupportedSchema("http://www.w3.org/2001/XMLSchema");
                    }
                    xmlElement = xmlDocument.CreateElement(reader.Prefix, reader.LocalName, reader.NamespaceURI);
                    if (reader.HasAttributes)
                    {
                        int attributeCount = reader.AttributeCount;
                        for (int i = 0; i < attributeCount; i++)
{
                            reader.MoveToAttribute(i);
                            if (reader.NamespaceURI.Equals("http://www.w3.org/2000/xmlns/"))
{
                                xmlElement.SetAttribute(reader.Name, reader.GetAttribute(i));
                                continue;
                            }
                            XmlAttribute xmlAttribute = xmlElement.SetAttributeNode(reader.LocalName, reader.NamespaceURI);
                            xmlAttribute.Prefix = reader.Prefix;
                            xmlAttribute.Value = reader.GetAttribute(i);
                        }
                    }
                    reader.Read();
                }
                while (MoveToElement(reader, depth))
                {
                    if (reader.LocalName == "Schema" && reader.NamespaceURI == "urn:schemas-microsoft-com:xml-data")
                    {
                        if (!flag && !flag2 && mode != XmlReadMode.IgnoreSchema && mode != XmlReadMode.InferSchema)
{
                            ReadXDRSchema(reader);
                            flag = true;
                            isXdr = true;
                        }
                        else
{
                            reader.Skip();
                        }
                        continue;
                    }
                    if (reader.LocalName == "schema" && reader.NamespaceURI == "http://www.w3.org/2001/XMLSchema")
                    {
                        if (mode != XmlReadMode.IgnoreSchema && mode != XmlReadMode.InferSchema)
{
                            ReadXmlSchema(reader, denyResolving);
                            flag = true;
                        }
                        else
{
                            reader.Skip();
                        }
                        continue;
                    }
                    if (reader.LocalName == "diffgram" && reader.NamespaceURI == "urn:schemas-microsoft-com:xml-diffgram-v1")
                    {
                        if (mode == XmlReadMode.DiffGram || mode == XmlReadMode.IgnoreSchema)
{
                            if (Columns.Count == 0)
{
                                if (reader.IsEmptyElement)
{
                                    reader.Read();
                                    return XmlReadMode.DiffGram;
                                }
                                throw ExceptionBuilder.DataTableInferenceNotSupported();
                            }
                            ReadXmlDiffgram(reader);
                            result = XmlReadMode.DiffGram;
                        }
                        else
{
                            reader.Skip();
                        }
                        continue;
                    }
                    if (reader.LocalName == "schema" && reader.NamespaceURI.StartsWith("http://www.w3.org/", StringComparison.Ordinal))
                    {
                        if (DataSet != null)
{
                            DataSet.RestoreEnforceConstraints(flag3);
                        }
                        else
{
                            _enforceConstraints = flag3;
                        }
                        throw ExceptionBuilder.DataSetUnsupportedSchema("http://www.w3.org/2001/XMLSchema");
                    }
                    if (mode == XmlReadMode.DiffGram)
                    {
                        reader.Skip();
                        continue;
                    }
                    flag2 = true;
                    if (mode == XmlReadMode.InferSchema)
                    {
                        XmlNode newChild = xmlDocument.ReadNode(reader);
                        xmlElement.AppendChild(newChild);
                        continue;
                    }
                    if (Columns.Count == 0)
                    {
                        throw ExceptionBuilder.DataTableInferenceNotSupported();
                    }
                    if (xmlDataLoader == null)
                    {
                        xmlDataLoader = new XmlDataLoader(this, isXdr, xmlElement, mode == XmlReadMode.IgnoreSchema);
                    }
                    xmlDataLoader.LoadData(reader);
                }
                ReadEndElement(reader);
                xmlDocument.AppendChild(xmlElement);
                if (xmlDataLoader == null)
                {
                    xmlDataLoader = new XmlDataLoader(this, isXdr, mode == XmlReadMode.IgnoreSchema);
                }
                switch (mode)
                {
                case XmlReadMode.DiffGram:
                    RestoreConstraint(flag3);
                    return result;
                case XmlReadMode.InferSchema:
                    if (Columns.Count == 0)
                    {
                        throw ExceptionBuilder.DataTableInferenceNotSupported();
                    }
                    break;
                }
            }
            RestoreConstraint(flag3);
            return result;
        }
        finally
        {
            disposable?.Dispose();
        }
    }
References System.Data.DataTable._enforceConstraints, System.Xml.XmlReader.AttributeCount, System.Data.DataTable.Columns, System.Data.InternalDataCollectionBase.Count, System.Data.ExceptionBuilder.DataSetUnsupportedSchema(), System.Data.ExceptionBuilder.DataTableInferenceNotSupported(), System.Xml.XmlReader.Depth, System.Runtime.Serialization.Dictionary, System.Data.DataSet.EnforceConstraints, System.Data.DataTable.EnforceConstraints, System.Data.TypeLimiter.EnterRestrictedScope(), System.Xml.XmlReader.GetAttribute(), System.Xml.XmlReader.HasAttributes, System.Xml.XmlReader.IsEmptyElement, System.Data.DataTable.IsEmptyXml(), System.Xml.XmlReader.LocalName, System.Xml.XmlReader.MoveToAttribute(), System.Xml.XmlReader.MoveToContent(), System.Data.DataTable.MoveToElement(), System.Xml.XmlReader.Name, System.Xml.XmlReader.NamespaceURI, System.Xml.XmlReader.NodeType, System.Xml.XmlReader.Prefix, System.Xml.XmlReader.Read(), System.Data.DataTable.ReadEndElement(), System.Data.DataTable.ReadXDRSchema(), System.Data.DataTable.ReadXmlDiffgram(), System.Data.DataTable.ReadXmlSchema(), System.Data.DataTable.RestoreConstraint(), System.Data.DataSet.RestoreEnforceConstraints(), and System.Xml.XmlReader.Skip().