Terraria: System.Data.DataTable.SetShadowIndexes
SetShadowIndexes()
void System.Data.DataTable.SetShadowIndexes () inline private inherited
Definition at line 4010 of file DataTable.cs.
    {
        if (_shadowIndexes == null)
        {
            _shadowIndexes = LiveIndexes;
            _shadowCount = 1;
        }
        else
        {
            _shadowCount++;
        }
    }
References System.Data.DataTable._shadowCount, System.Data.DataTable._shadowIndexes, and System.Data.DataTable.LiveIndexes.
Referenced by System.Data.DataTable.RecordChanged(), System.Data.DataTable.RecordChanged(), System.Data.DataTable.RecordStateChanged(), System.Data.DataTable.RecordStateChanged(), System.Data.DataTable.ResetInternalIndexes(), and System.Data.DataTable.RestoreIndexEvents().