Terraria: System.Data.DataTable.CommitRow
CommitRow()
void System.Data.DataTable.CommitRow (DataRow row) inline package inherited
Definition at line 2621 of file DataTable.cs.
    {
        DataRowChangeEventArgs args = OnRowChanging(null, row, DataRowAction.Commit);
        if (!_inDataLoad)
        {
            CascadeAll(row, DataRowAction.Commit);
        }
        SetOldRecord(row, row._newRecord);
        OnRowChanged(args, row, DataRowAction.Commit);
    }
References System.Data.DataTable._inDataLoad, System.Data.DataTable.CascadeAll(), System.Data.DataTable.OnRowChanged(), System.Data.DataTable.OnRowChanging(), and System.Data.DataTable.SetOldRecord().
Referenced by System.Data.DataRow.AcceptChanges().