Terraria: System.Data.DataTable.DeserializeDataTable
DeserializeDataTable()
void System.Data.DataTable.DeserializeDataTable (SerializationInfo info, StreamingContext context, bool isSingleTable, SerializationFormat remotingFormat) inline package inherited
Definition at line 1228 of file DataTable.cs.
    {
        if (remotingFormat != 0)
        {
            DeserializeTableSchema(info, context, isSingleTable);
            if (isSingleTable)
            {
                DeserializeTableData(info, context, 0);
                ResetIndexes();
            }
            return;
        }
        string text = (string)info.GetValue("XmlSchema", typeof(string));
        string text2 = (string)info.GetValue("XmlDiffGram", typeof(string));
        if (text != null)
        {
            DataSet dataSet = new DataSet();
            dataSet.ReadXmlSchema(new XmlTextReader(new StringReader(text)));
            DataTable dataTable = dataSet.Tables[0];
            dataTable.CloneTo(this, null, skipExpressionColumns: false);
            Namespace = dataTable.Namespace;
            if (text2 != null)
            {
                dataSet.Tables.Remove(dataSet.Tables[0]);
                dataSet.Tables.Add(this);
                dataSet.ReadXml(new XmlTextReader(new StringReader(text2)), XmlReadMode.DiffGram);
                dataSet.Tables.Remove(this);
            }
        }
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Data.DataTable.DataSet, System.Data.DataTable.DeserializeTableData(), System.Data.DataTable.DeserializeTableSchema(), System.info, System.Data.DataTable.Namespace, System.Collections.Generic.Dictionary< TKey, TValue >.Remove(), System.Data.DataTable.ResetIndexes(), and System.text.
Referenced by System.Data.DataTable.DataTable().