Terraria: System.GC.KeepAlive
KeepAlive()
static void System.GC.KeepAlive (object? obj) inline static
Definition at line 180 of file GC.cs.
    {
    }
Referenced by System.Diagnostics.ActivitySource.ActivitySource(), System.Runtime.Loader.AssemblyDependencyResolver.AssemblyDependencyResolver(), Internal.Cryptography.Pal.CertificatePal.CertificatePal(), System.Diagnostics.DiagnosticListener.DiagnosticListener(), System.Diagnostics.Tracing.EventListener.EventListener(), System.Diagnostics.Metrics.Meter.Meter(), System.Signature.Signature(), System.RuntimeMethodHandle.ConstructInstantiation(), System.Reflection.Emit.DynamicMethod.CreateDelegate(), System.Reflection.Emit.DynamicMethod.CreateDelegate(), System.RuntimeTypeHandle.CreateInstanceForAnotherGenericParameter(), System.RuntimeTypeHandle.CreateInstanceForAnotherGenericParameter(), System.RuntimeType.ActivatorCache.CreateUninitializedObject(), System.StubHelpers.KeepAliveCleanupWorkListElement.DestroyCore(), Internal.Cryptography.Pal.StorePal.Export(), System.Reflection.CustomAttribute.FilterCustomAttributeRecord(), Internal.Cryptography.Pal.FindPal.FindByCertificatePolicy(), Internal.Cryptography.Pal.FindPal.FindByExtension(), Internal.Cryptography.Pal.FindPal.FindByKeyUsage(), Internal.Cryptography.Pal.FindPal.FindBySerialNumber(), Internal.Cryptography.Pal.FindPal.FindByTemplateName(), Internal.Cryptography.Pal.FindPal.FindByTime(), System.Runtime.CompilerServices.ConditionalWeakTable< TKey, TValue >.Container.FindEntry(), System.RuntimeFieldHandle.GetApproxDeclaringType(), System.RuntimeMethodHandle.GetAttributes(), System.Reflection.Internal.AbstractMemoryBlock.GetContentUnchecked(), System.RuntimeMethodHandle.GetDeclaringType(), System.RuntimeType.GetFieldInfo(), System.RuntimeMethodHandle.GetFunctionPointer(), System.GC.GetGeneration(), System.Reflection.Emit.ModuleBuilder.GetMemberRefOfMethodInfo(), System.Reflection.Emit.ModuleBuilder.GetMemberRefOfMethodInfo(), System.RuntimeType.GetMethodBase(), System.RuntimeType.GetMethodBase(), System.RuntimeMethodHandle.GetMethodInstantiationInternal(), System.RuntimeMethodHandle.GetMethodInstantiationPublic(), System.Runtime.CompilerServices.RuntimeHelpers.GetMultiDimensionalArrayRank(), System.RuntimeMethodHandle.GetName(), System.Runtime.CompilerServices.RuntimeHelpers.GetRawObjectDataSize(), System.RuntimeMethodHandle.GetSlot(), System.Reflection.RuntimeModule.GetType(), System.Reflection.RuntimeAssembly.GetType(), System.RuntimeTypeHandle.GetTypeByName(), System.RuntimeMethodHandle.GetTypicalMethodDefinition(), System.RuntimeMethodHandle.HasMethodInstantiation(), System.RuntimeTypeHandle.Instantiate(), System.RuntimeTypeHandle.Instantiate(), System.Reflection.Emit.DynamicMethod.Invoke(), System.RuntimeMethodHandle.IsGenericMethodDefinition(), System.Runtime.InteropServices.Marshal.PrelinkCore(), System.Runtime.CompilerServices.RuntimeHelpers.PrepareMethod(), Internal.Cryptography.Pal.StorePal.Remove(), System.Runtime.CompilerServices.ConditionalWeakTable< TKey, TValue >.Container.Resize(), System.ModuleHandle.ResolveFieldHandle(), System.ModuleHandle.ResolveMethodHandle(), System.ModuleHandle.ResolveTypeHandle(), System.RuntimeTypeHandle.SatisfiesConstraints(), System.RuntimeMethodHandle.StripMethodInstantiation(), System.Runtime.CompilerServices.ConditionalWeakTable< TKey, TValue >.Container.TryGetEntry(), System.Threading.Tasks.Task< TResult >.WaitAllCore(), and System.Threading.Tasks.Task< TResult >.WaitAnyCore().