Terraria: System.Data.DataTable.InsertRow
InsertRow() [2/3]
void System.Data.DataTable.InsertRow (DataRow row, long proposedID) inline package inherited
Definition at line 2957 of file DataTable.cs.
    {
        long scopeId = DataCommonEventSource.Log.EnterScope("<ds.DataTable.InsertRow|INFO> {0}, row={1}", ObjectID, row._objectID);
        try
        {
            if (row.Table != this)
            {
                throw ExceptionBuilder.RowAlreadyInOtherCollection();
            }
            if (row.rowID != -1)
            {
                throw ExceptionBuilder.RowAlreadyInTheCollection();
            }
            if (row._oldRecord == -1 && row._newRecord == -1)
            {
                throw ExceptionBuilder.RowEmpty();
            }
            if (proposedID == -1)
            {
                proposedID = _nextRowID;
            }
            row.rowID = proposedID;
            if (_nextRowID <= proposedID)
            {
                _nextRowID = checked(proposedID + 1);
            }
            DataRowChangeEventArgs args = null;
            if (row._newRecord != -1)
            {
                row._tempRecord = row._newRecord;
                row._newRecord = -1;
                try
                {
                    args = RaiseRowChanging(null, row, DataRowAction.Add, fireEvent: true);
                }
                catch
                {
                    row._tempRecord = -1;
                    throw;
                }
                row._newRecord = row._tempRecord;
                row._tempRecord = -1;
            }
            if (row._oldRecord != -1)
            {
                _recordManager[row._oldRecord] = row;
            }
            if (row._newRecord != -1)
            {
                _recordManager[row._newRecord] = row;
            }
            Rows.ArrayAdd(row);
            if (row.RowState == DataRowState.Unchanged)
            {
                RecordStateChanged(row._oldRecord, DataViewRowState.None, DataViewRowState.Unchanged);
            }
            else
            {
                RecordStateChanged(row._oldRecord, DataViewRowState.None, row.GetRecordState(row._oldRecord), row._newRecord, DataViewRowState.None, row.GetRecordState(row._newRecord));
            }
            if (_dependentColumns != null && _dependentColumns.Count > 0)
            {
                EvaluateExpressions(row, DataRowAction.Add, null);
            }
            RaiseRowChanged(args, row, DataRowAction.Add);
        }
        finally
        {
            DataCommonEventSource.Log.ExitScope(scopeId);
        }
    }
References System.Data.DataTable._dependentColumns, System.Data.DataTable._nextRowID, System.Data.DataTable._recordManager, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Data.DataRowCollection.ArrayAdd(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Runtime.Serialization.Dictionary, System.Data.DataTable.EvaluateExpressions(), System.Data.DataCommonEventSource.Log, System.Data.DataTable.ObjectID, System.Data.DataTable.RaiseRowChanged(), System.Data.DataTable.RaiseRowChanging(), System.Data.DataTable.RecordStateChanged(), System.Data.ExceptionBuilder.RowAlreadyInOtherCollection(), System.Data.ExceptionBuilder.RowAlreadyInTheCollection(), System.Data.ExceptionBuilder.RowEmpty(), and System.Data.DataTable.Rows.