Terraria: System.Data.DataTable.DeserializeTableData
DeserializeTableData()
void System.Data.DataTable.DeserializeTableData (SerializationInfo info, StreamingContext context, int serIndex) inline package inherited
Definition at line 1577 of file DataTable.cs.
    {
        bool enforceConstraints = _enforceConstraints;
        bool inDataLoad = _inDataLoad;
        try
        {
            _enforceConstraints = false;
            _inDataLoad = true;
            IFormatProvider invariantCulture = CultureInfo.InvariantCulture;
            int @int = info.GetInt32(string.Format(invariantCulture, "DataTable_{0}.Rows.Count", serIndex));
            int int2 = info.GetInt32(string.Format(invariantCulture, "DataTable_{0}.Records.Count", serIndex));
            BitArray bitArray = (BitArray)info.GetValue(string.Format(invariantCulture, "DataTable_{0}.RowStates", serIndex), typeof(BitArray));
            ArrayList arrayList = (ArrayList)info.GetValue(string.Format(invariantCulture, "DataTable_{0}.Records", serIndex), typeof(ArrayList));
            ArrayList arrayList2 = (ArrayList)info.GetValue(string.Format(invariantCulture, "DataTable_{0}.NullBits", serIndex), typeof(ArrayList));
            Hashtable hashtable = (Hashtable)info.GetValue(string.Format(invariantCulture, "DataTable_{0}.RowErrors", serIndex), typeof(Hashtable));
            hashtable.OnDeserialization(this);
            Hashtable hashtable2 = (Hashtable)info.GetValue(string.Format(invariantCulture, "DataTable_{0}.ColumnErrors", serIndex), typeof(Hashtable));
            hashtable2.OnDeserialization(this);
            if (int2 <= 0)
            {
                return;
            }
            for (int i = 0; i < Columns.Count; i++)
            {
                Columns[i].SetStorage(arrayList[i], (BitArray)arrayList2[i]);
            }
            int num = 0;
            DataRow[] array = new DataRow[int2];
            for (int j = 0; j < @int; j++)
            {
                DataRow dataRow = (array[num] = NewEmptyRow());
                int num2 = j * 3;
                switch (ConvertToRowState(bitArray, num2))
                {
                case DataRowState.Unchanged:
                    dataRow._oldRecord = num;
                    dataRow._newRecord = num;
                    num++;
                    break;
                case DataRowState.Added:
                    dataRow._oldRecord = -1;
                    dataRow._newRecord = num;
                    num++;
                    break;
                case DataRowState.Modified:
                    dataRow._oldRecord = num;
                    dataRow._newRecord = num + 1;
                    array[num + 1] = dataRow;
                    num += 2;
                    break;
                case DataRowState.Deleted:
                    dataRow._oldRecord = num;
                    dataRow._newRecord = -1;
                    num++;
                    break;
                }
                if (bitArray[num2 + 2])
                {
                    dataRow._tempRecord = num;
                    array[num] = dataRow;
                    num++;
                }
                else
                {
                    dataRow._tempRecord = -1;
                }
                Rows.ArrayAdd(dataRow);
                dataRow.rowID = _nextRowID;
                _nextRowID++;
                ConvertToRowError(j, hashtable, hashtable2);
            }
            _recordManager.SetRowCache(array);
            ResetIndexes();
        }
        finally
        {
            _enforceConstraints = enforceConstraints;
            _inDataLoad = inDataLoad;
        }
    }
References System.Data.DataTable._enforceConstraints, System.Data.DataTable._inDataLoad, System.Data.DataTable._nextRowID, System.Data.DataTable._recordManager, System.array, System.Data.DataRowCollection.ArrayAdd(), System.Data.DataTable.Columns, System.Data.DataTable.ConvertToRowError(), System.Data.DataTable.ConvertToRowState(), System.Data.InternalDataCollectionBase.Count, System.Runtime.Serialization.Dictionary, System.Format, System.info, System.Globalization.CultureInfo.InvariantCulture, System.Data.DataTable.NewEmptyRow(), System.Collections.Generic.Dictionary< TKey, TValue >.OnDeserialization(), System.Collections.Hashtable.OnDeserialization(), System.Data.DataTable.ResetIndexes(), System.Data.DataTable.Rows, and System.Data.RecordManager.SetRowCache().
Referenced by System.Data.DataTable.DeserializeDataTable().