Terraria: System.Data.DataTable.RestoreIndexEvents
RestoreIndexEvents()
void System.Data.DataTable.RestoreIndexEvents (bool forceReset) inline package inherited
Definition at line 1726 of file DataTable.cs.
    {
        DataCommonEventSource.Log.Trace("<ds.DataTable.RestoreIndexEvents|Info> {0}, {1}", ObjectID, _suspendIndexEvents);
        if (0 >= _suspendIndexEvents)
        {
            return;
        }
        _suspendIndexEvents--;
        if (_suspendIndexEvents != 0)
        {
            return;
        }
        Exception ex = null;
        SetShadowIndexes();
        try
        {
            int count = _shadowIndexes.Count;
            for (int i = 0; i < count; i++)
            {
                Index index = _shadowIndexes[i];
                try
                {
                    if (forceReset || index.HasRemoteAggregate)
                    {
                        index.Reset();
                    }
                    else
                    {
                        index.FireResetEvent();
                    }
                }
                catch (Exception ex2) when (ADP.IsCatchableExceptionType(ex2))
                {
                    ExceptionBuilder.TraceExceptionWithoutRethrow(ex2);
                    if (ex2 == null)
                    {
                        ex = ex2;
                    }
                }
            }
            if (ex != null)
            {
                throw ex;
            }
        }
        finally
        {
            RestoreShadowIndexes();
        }
    }
References System.Data.DataTable._shadowIndexes, System.Data.DataTable._suspendIndexEvents, System.count, System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Runtime.Serialization.Dictionary, System.index, System.Data.Common.ADP.IsCatchableExceptionType(), System.Data.DataCommonEventSource.Log, System.Data.DataTable.ObjectID, System.Data.DataTable.RestoreShadowIndexes(), System.Data.DataTable.SetShadowIndexes(), and System.Data.ExceptionBuilder.TraceExceptionWithoutRethrow().
Referenced by System.Data.DataTable.AcceptChanges(), and System.Data.DataTable.EndLoadData().