Terraria: System.Data.DataTable.CreateTableList
CreateTableList()
void System.Data.DataTable.CreateTableList (DataTable currentTable, List< DataTable > tableList) inline private inherited
Definition at line 5829 of file DataTable.cs.
    {
        foreach (DataRelation childRelation in currentTable.ChildRelations)
        {
            if (!tableList.Contains(childRelation.ChildTable))
            {
                tableList.Add(childRelation.ChildTable);
                CreateTableList(childRelation.ChildTable, tableList);
            }
        }
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Collections.Generic.Dictionary< TKey, TValue >.Contains(), and System.Data.DataTable.CreateTableList().
Referenced by System.Data.DataTable.CheckForClosureOnExpressions(), System.Data.DataTable.CreateTableList(), System.Data.DataTable.ReadXmlDiffgram(), and System.Data.DataTable.ReadXmlSchema().