Terraria: System.Data.DataTable.ResetIndexes
ResetIndexes()
void System.Data.DataTable.ResetIndexes () inline package inherited
Definition at line 3634 of file DataTable.cs.
    {
        ResetInternalIndexes(null);
    }
References System.Data.DataTable.ResetInternalIndexes().
Referenced by System.Data.DataTableCollection.Add(), System.Data.DataTable.Clear(), System.Data.DataTable.DeserializeDataTable(), System.Data.DataTable.DeserializeTableData(), System.Data.DataTable.SetCaseSensitiveValue(), and System.Data.DataTable.SetLocaleValue().