Terraria: System.Data.DataTable.AddRow
AddRow() [1/2]
void System.Data.DataTable.AddRow (DataRow row) inline package inherited
Definition at line 2461 of file DataTable.cs.
    {
        AddRow(row, -1);
    }
References System.Data.DataTable.AddRow().
Referenced by System.Data.DataRowCollection.Add(), System.Data.DataRowCollection.Add(), System.Data.DataTable.AddRecords(), System.Data.DataTable.AddRow(), System.Data.DataRowCollection.AddWithColumnEvents(), System.Data.DataRowCollection.DiffInsertAt(), System.Data.DataRowCollection.InsertAt(), and System.Data.DataTable.LoadDataRow().