Terraria: System.Data.DataTable.SetLocaleValue
SetLocaleValue()
bool System.Data.DataTable.SetLocaleValue (CultureInfo culture, bool userSet, bool resetIndexes) inline package inherited
Definition at line 1868 of file DataTable.cs.
    {
        if (userSet || resetIndexes || (!_cultureUserSet && !_culture.Equals(culture)))
        {
            _culture = culture;
            _compareInfo = null;
            _formatProvider = null;
            _hashCodeProvider = null;
            foreach (DataColumn column in Columns)
            {
                column._hashCode = GetSpecialHashCode(column.ColumnName);
            }
            if (resetIndexes)
            {
                ResetIndexes();
                foreach (Constraint constraint in Constraints)
                {
                    constraint.CheckConstraint();
                }
            }
            return true;
        }
        return false;
    }
References System.Data.DataTable._compareInfo, System.Data.DataTable._culture, System.Data.DataTable._cultureUserSet, System.Data.DataTable._formatProvider, System.Data.DataTable._hashCodeProvider, System.Data.Constraint.CheckConstraint(), System.Data.DataTable.Columns, System.Data.DataTable.Constraints, System.culture, System.Runtime.Serialization.Dictionary, System.Globalization.CultureInfo.Equals(), System.Data.DataTable.GetSpecialHashCode(), and System.Data.DataTable.ResetIndexes().
Referenced by System.Data.DataTableCollection.Add(), System.Data.DataTable.DeserializeTableSchema(), and System.Data.DataSet.SetLocaleValue().