Terraria: System.Data.DataTable.AddRecords
AddRecords()
DataRow System.Data.DataTable.AddRecords (int oldRecord, int newRecord) inline package inherited
Definition at line 2443 of file DataTable.cs.
    {
        DataRow dataRow;
        if (oldRecord == -1 && newRecord == -1)
        {
            dataRow = NewRow(-1);
            AddRow(dataRow);
        }
        else
        {
            dataRow = NewEmptyRow();
            dataRow._oldRecord = oldRecord;
            dataRow._newRecord = newRecord;
            InsertRow(dataRow, -1L);
        }
        return dataRow;
    }
References System.Data.DataTable.AddRow(), System.Runtime.Serialization.Dictionary, System.Data.DataTable.InsertRow(), System.L, System.Data.DataTable.NewEmptyRow(), and System.Data.DataTable.NewRow().
Referenced by System.Data.DataTable.CopyRow(), and System.Data.DataTable.ImportRow().