Terraria: System.Data.DataTable.AcceptChanges
AcceptChanges()
void System.Data.DataTable.AcceptChanges () inline inherited
Definition at line 2205 of file DataTable.cs.
    {
        long scopeId = DataCommonEventSource.Log.EnterScope("<ds.DataTable.AcceptChanges|API> {0}", ObjectID);
        try
        {
            DataRow[] array = new DataRow[Rows.Count];
            Rows.CopyTo(array, 0);
            SuspendIndexEvents();
            try
            {
                for (int i = 0; i < array.Length; i++)
                {
                    if (array[i].rowID != -1)
                    {
                        array[i].AcceptChanges();
                    }
                }
            }
            finally
            {
                RestoreIndexEvents(forceReset: false);
            }
        }
        finally
        {
            DataCommonEventSource.Log.ExitScope(scopeId);
        }
    }
References System.array, System.Data.DataRowCollection.CopyTo(), System.Data.DataRowCollection.Count, System.Data.DataCommonEventSource.Log, System.Data.DataTable.ObjectID, System.Data.DataTable.RestoreIndexEvents(), System.Data.DataTable.Rows, and System.Data.DataTable.SuspendIndexEvents().