Terraria: System.Data.DataTable.WriteXml
WriteXml() [1/17]
void System.Data.DataTable.WriteXml (Stream? stream) inline inherited
Definition at line 4689 of file DataTable.cs.
    {
        WriteXml(stream, XmlWriteMode.IgnoreSchema, writeHierarchy: false);
    }
References System.stream, and System.Data.DataTable.WriteXml().
Referenced by System.Data.DataTable.WriteXml(), System.Data.DataTable.WriteXml(), System.Data.DataTable.WriteXml(), System.Data.DataTable.WriteXml(), System.Data.DataTable.WriteXml(), System.Data.DataTable.WriteXml(), System.Data.DataTable.WriteXml(), System.Data.DataTable.WriteXml(), System.Data.DataTable.WriteXml(), System.Data.DataTable.WriteXml(), System.Data.DataTable.WriteXml(), System.Data.DataTable.WriteXml(), System.Data.DataTable.WriteXml(), System.Data.DataTable.WriteXml(), System.Data.DataTable.WriteXml(), and System.Data.DataTable.WriteXmlInternal().