Terraria: System.Data.DataTable.WriteXmlSchema
WriteXmlSchema() [1/8]
void System.Data.DataTable.WriteXmlSchema (Stream? stream) inline inherited
Definition at line 4859 of file DataTable.cs.
    {
        WriteXmlSchema(stream, writeHierarchy: false);
    }
References System.stream, and System.Data.DataTable.WriteXmlSchema().
Referenced by System.Data.DataTable.WriteXmlInternal(), System.Data.DataTable.WriteXmlSchema(), System.Data.DataTable.WriteXmlSchema(), System.Data.DataTable.WriteXmlSchema(), System.Data.DataTable.WriteXmlSchema(), System.Data.DataTable.WriteXmlSchema(), System.Data.DataTable.WriteXmlSchema(), and System.Data.DataTable.WriteXmlSchema().