Terraria: System.Data.DataTable.SerializeDataTable
SerializeDataTable()
void System.Data.DataTable.SerializeDataTable (SerializationInfo info, StreamingContext context, bool isSingleTable, SerializationFormat remotingFormat) inline private inherited
Definition at line 1183 of file DataTable.cs.
    {
        info.AddValue("DataTable.RemotingVersion", new Version(2, 0));
        if (remotingFormat != 0)
        {
            info.AddValue("DataTable.RemotingFormat", remotingFormat);
        }
        if (remotingFormat != 0)
        {
            SerializeTableSchema(info, context, isSingleTable);
            if (isSingleTable)
            {
                SerializeTableData(info, context, 0);
            }
            return;
        }
        string namespaceURI = string.Empty;
        bool flag = false;
        if (_dataSet == null)
        {
            DataSet dataSet = new DataSet("tmpDataSet");
            dataSet.SetLocaleValue(_culture, _cultureUserSet);
            dataSet.CaseSensitive = CaseSensitive;
            dataSet._namespaceURI = Namespace;
            dataSet.Tables.Add(this);
            flag = true;
        }
        else
        {
            namespaceURI = _dataSet.Namespace;
            _dataSet._namespaceURI = Namespace;
        }
        info.AddValue("XmlSchema", _dataSet.GetXmlSchemaForRemoting(this));
        info.AddValue("XmlDiffGram", _dataSet.GetRemotingDiffGram(this));
        if (flag)
        {
            _dataSet.Tables.Remove(this);
        }
        else
        {
            _dataSet._namespaceURI = namespaceURI;
        }
    }
References System.Data.DataTable._culture, System.Data.DataTable._cultureUserSet, System.Data.DataTable._dataSet, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Data.DataTable.CaseSensitive, System.Data.DataTable.DataSet, System.Runtime.Serialization.Dictionary, System.Data.DataSet.GetRemotingDiffGram(), System.Data.DataSet.GetXmlSchemaForRemoting(), System.info, System.Data.DataSet.Namespace, System.Data.DataTable.Namespace, System.Data.DataTableCollection.Remove(), System.Data.DataTable.SerializeTableData(), System.Data.DataTable.SerializeTableSchema(), and System.Data.DataSet.Tables.
Referenced by System.Data.DataTable.GetObjectData().