Terraria: System.Data.DataTable.Clear
Clear() [2/2]
void System.Data.DataTable.Clear (bool clearAll) inline package inherited
Definition at line 2557 of file DataTable.cs.
    {
        long scopeId = DataCommonEventSource.Log.EnterScope("<ds.DataTable.Clear|INFO> {0}, clearAll={1}", ObjectID, clearAll);
        try
        {
            _rowDiffId = null;
            if (_dataSet != null)
            {
                _dataSet.OnClearFunctionCalled(this);
            }
            bool flag = Rows.Count != 0;
            DataTableClearEventArgs e = null;
            if (flag)
            {
                e = new DataTableClearEventArgs(this);
                OnTableClearing(e);
            }
            if (_dataSet != null && _dataSet.EnforceConstraints)
            {
                ParentForeignKeyConstraintEnumerator parentForeignKeyConstraintEnumerator = new ParentForeignKeyConstraintEnumerator(_dataSet, this);
                while (parentForeignKeyConstraintEnumerator.GetNext())
                {
                    ForeignKeyConstraint foreignKeyConstraint = parentForeignKeyConstraintEnumerator.GetForeignKeyConstraint();
                    foreignKeyConstraint.CheckCanClearParentTable(this);
                }
            }
            _recordManager.Clear(clearAll);
            foreach (DataRow row in Rows)
            {
                row._oldRecord = -1;
                row._newRecord = -1;
                row._tempRecord = -1;
                row.rowID = -1L;
                row.RBTreeNodeId = 0;
            }
            Rows.ArrayClear();
            ResetIndexes();
            if (flag)
            {
                OnTableCleared(e);
            }
            foreach (DataColumn column in Columns)
            {
                EvaluateDependentExpressions(column);
            }
        }
        finally
        {
            DataCommonEventSource.Log.ExitScope(scopeId);
        }
    }
References System.Data.DataTable._dataSet, System.Data.DataTable._recordManager, System.Data.DataTable._rowDiffId, System.Data.DataRowCollection.ArrayClear(), System.Data.RecordManager.Clear(), System.Data.DataTable.Columns, System.Runtime.Serialization.Dictionary, System.Data.DataSet.EnforceConstraints, System.Data.DataTable.EvaluateDependentExpressions(), System.L, System.Data.DataCommonEventSource.Log, System.Data.DataTable.ObjectID, System.Data.DataSet.OnClearFunctionCalled(), System.Data.DataTable.OnTableCleared(), System.Data.DataTable.OnTableClearing(), System.Data.DataTable.ResetIndexes(), and System.Data.DataTable.Rows.