Terraria: System.Data.DataTable.Clone
Clone() [1/2]
virtual DataTable System.Data.DataTable.Clone () inline virtual inherited
Definition at line 2240 of file DataTable.cs.
    {
        return Clone(null);
    }
References System.Data.DataTable.Clone().
Referenced by System.Data.DataTable.Clone(), System.Data.DataTable.CloneTo(), System.Data.DataTable.Copy(), System.Data.DataTable.GetChanges(), System.Data.DataTable.GetChanges(), System.Data.Merger.MergeSchema(), and System.Data.DataTable.ReadXmlDiffgram().