Terraria: System.Data.DataTable.SetOldRecord
SetOldRecord()
void System.Data.DataTable.SetOldRecord (DataRow row, int proposedRecord) inline package inherited
Definition at line 3948 of file DataTable.cs.
    {
        if (!_inDataLoad)
        {
            row.CheckInTable();
            CheckNotModifying(row);
        }
        if (proposedRecord == row._oldRecord)
        {
            return;
        }
        int record = row._oldRecord;
        try
        {
            if (LiveIndexes.Count != 0)
            {
                if (-1 == record && -1 != proposedRecord && -1 != row._newRecord && proposedRecord != row._newRecord)
                {
                    record = row._newRecord;
                }
                DataViewRowState recordState = row.GetRecordState(record);
                DataViewRowState recordState2 = row.GetRecordState(proposedRecord);
                row._oldRecord = proposedRecord;
                if (proposedRecord != -1)
                {
                    _recordManager[proposedRecord] = row;
                }
                DataViewRowState recordState3 = row.GetRecordState(record);
                DataViewRowState recordState4 = row.GetRecordState(proposedRecord);
                RecordStateChanged(record, recordState, recordState3, proposedRecord, recordState2, recordState4);
            }
            else
            {
                row._oldRecord = proposedRecord;
                if (proposedRecord != -1)
                {
                    _recordManager[proposedRecord] = row;
                }
            }
        }
        finally
        {
            if (record != -1 && record != row._tempRecord && record != row._oldRecord && record != row._newRecord)
            {
                FreeRecord(ref record);
            }
            if (row.RowState == DataRowState.Detached && row.rowID != -1)
            {
                RemoveRow(row, check: false);
            }
        }
    }
References System.Data.DataTable._inDataLoad, System.Data.DataTable._recordManager, System.Data.DataTable.CheckNotModifying(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Runtime.Serialization.Dictionary, System.Data.DataTable.FreeRecord(), System.Data.DataTable.LiveIndexes, System.Data.DataTable.RecordStateChanged(), and System.Data.DataTable.RemoveRow().
Referenced by System.Data.DataTable.CommitRow(), System.Data.DataTable.LoadRow(), System.Data.DataRow.SetAdded(), System.Data.DataTable.SetDataRowWithLoadOption(), and System.Data.DataTable.SetMergeRecords().