Terraria: System.Data.DataTable.InsertRow
InsertRow() [1/3]
void System.Data.DataTable.InsertRow (DataRow row, int proposedID, int pos) inline package inherited
Definition at line 2471 of file DataTable.cs.
    {
        InsertRow(row, proposedID, pos, fireEvent: true);
    }
References System.Data.DataTable.InsertRow().
Referenced by System.Data.DataTable.AddRecords(), System.Data.DataTable.AddRow(), System.Data.DataRowCollection.DiffInsertAt(), System.Data.DataRowCollection.InsertAt(), System.Data.DataTable.InsertRow(), System.Data.DataTable.LoadRow(), and System.Data.DataTable.MergeRow().