Terraria: System.Data.DataTable.LoadDataRow
LoadDataRow() [2/2]
DataRow System.Data.DataTable.LoadDataRow (object?[] values, LoadOption loadOption) inline inherited
Definition at line 4173 of file DataTable.cs.
    {
        long scopeId = DataCommonEventSource.Log.EnterScope("<ds.DataTable.LoadDataRow|API> {0}, loadOption={1}", ObjectID, loadOption);
        try
        {
            Index searchIndex = null;
            if (_primaryKey != null)
            {
                if (loadOption == LoadOption.Upsert)
                {
                    if (_loadIndexwithCurrentDeleted == null)
                    {
                        _loadIndexwithCurrentDeleted = _primaryKey.Key.GetSortIndex(DataViewRowState.CurrentRows | DataViewRowState.Deleted);
                        if (_loadIndexwithCurrentDeleted != null)
{
                            _loadIndexwithCurrentDeleted.AddRef();
                        }
                    }
                    searchIndex = _loadIndexwithCurrentDeleted;
                }
                else
                {
                    if (_loadIndexwithOriginalAdded == null)
                    {
                        _loadIndexwithOriginalAdded = _primaryKey.Key.GetSortIndex(DataViewRowState.OriginalRows | DataViewRowState.Added);
                        if (_loadIndexwithOriginalAdded != null)
{
                            _loadIndexwithOriginalAdded.AddRef();
                        }
                    }
                    searchIndex = _loadIndexwithOriginalAdded;
                }
            }
            if (_inDataLoad && !AreIndexEventsSuspended)
            {
                SuspendIndexEvents();
            }
            return LoadRow(values, loadOption, searchIndex);
        }
        finally
        {
            DataCommonEventSource.Log.ExitScope(scopeId);
        }
    }
References System.Data.DataTable._inDataLoad, System.Data.DataTable._loadIndexwithCurrentDeleted, System.Data.DataTable._loadIndexwithOriginalAdded, System.Data.DataTable._primaryKey, System.Data.Index.AddRef(), System.Data.DataTable.AreIndexEventsSuspended, System.Data.DataKey.GetSortIndex(), System.Data.UniqueConstraint.Key, System.Data.DataTable.LoadRow(), System.Data.DataCommonEventSource.Log, System.Data.DataTable.ObjectID, System.Data.DataTable.SuspendIndexEvents(), and System.values.