Terraria: System.Data.DataTable.GetPropertyDescriptorCollection
GetPropertyDescriptorCollection()
PropertyDescriptorCollection System.Data.DataTable.GetPropertyDescriptorCollection (Attribute[] attributes) inline package inherited
Definition at line 4311 of file DataTable.cs.
    {
        if (_propertyDescriptorCollectionCache == null)
        {
            int count = Columns.Count;
            int count2 = ChildRelations.Count;
            PropertyDescriptor[] array = new PropertyDescriptor[count + count2];
            for (int i = 0; i < count; i++)
            {
                array[i] = new DataColumnPropertyDescriptor(Columns[i]);
            }
            for (int j = 0; j < count2; j++)
            {
                array[count + j] = new DataRelationPropertyDescriptor(ChildRelations[j]);
            }
            _propertyDescriptorCollectionCache = new PropertyDescriptorCollection(array);
        }
        return _propertyDescriptorCollectionCache;
    }
References System.Data.DataTable._propertyDescriptorCollectionCache, System.array, System.Data.DataTable.ChildRelations, System.Data.DataTable.Columns, System.Data.InternalDataCollectionBase.Count, System.count, and System.Runtime.Serialization.Dictionary.
Referenced by System.Data.DataView.GetItemProperties(), System.Data.DataViewManager.GetItemProperties(), and System.Data.DataRowView.GetProperties().