Terraria: System.Data.DataTable.SetMergeRecords
SetMergeRecords()
void System.Data.DataTable.SetMergeRecords (DataRow row, int newRecord, int oldRecord, DataRowAction action) inline private inherited
Definition at line 2096 of file DataTable.cs.
    {
        if (newRecord != -1)
        {
            SetNewRecord(row, newRecord, action, isInMerge: true);
            SetOldRecord(row, oldRecord);
            return;
        }
        SetOldRecord(row, oldRecord);
        if (row._newRecord != -1)
        {
            SetNewRecord(row, newRecord, action, isInMerge: true);
        }
    }
References System.action, System.Data.DataTable.SetNewRecord(), and System.Data.DataTable.SetOldRecord().
Referenced by System.Data.DataTable.MergeRow().