Terraria: System.Data.DataTable.InsertRow
InsertRow() [3/3]
void System.Data.DataTable.InsertRow (DataRow row, long proposedID, int pos, bool fireEvent) inline package inherited
Definition at line 2476 of file DataTable.cs.
    {
        Exception deferredException = null;
        if (row == null)
        {
            throw ExceptionBuilder.ArgumentNull("row");
        }
        if (row.Table != this)
        {
            throw ExceptionBuilder.RowAlreadyInOtherCollection();
        }
        if (row.rowID != -1)
        {
            throw ExceptionBuilder.RowAlreadyInTheCollection();
        }
        row.BeginEdit();
        int tempRecord = row._tempRecord;
        row._tempRecord = -1;
        if (proposedID == -1)
        {
            proposedID = _nextRowID;
        }
        bool flag;
        if (flag = _nextRowID <= proposedID)
        {
            _nextRowID = checked(proposedID + 1);
        }
        try
        {
            try
            {
                row.rowID = proposedID;
                SetNewRecordWorker(row, tempRecord, DataRowAction.Add, isInMerge: false, suppressEnsurePropertyChanged: false, pos, fireEvent, out deferredException);
            }
            catch
            {
                if (flag && _nextRowID == proposedID + 1)
                {
                    _nextRowID = proposedID;
                }
                row.rowID = -1L;
                row._tempRecord = tempRecord;
                throw;
            }
            if (deferredException != null)
            {
                throw deferredException;
            }
            if (!EnforceConstraints)
            {
                return;
            }
            int count = _columnCollection.Count;
            for (int i = 0; i < count; i++)
            {
                DataColumn dataColumn = _columnCollection[i];
                if (dataColumn.Computed)
                {
                    dataColumn.CheckColumnConstraint(row, DataRowAction.Add);
                }
            }
        }
        finally
        {
            row.ResetLastChangedColumn();
        }
    }
References System.Data.DataTable._columnCollection, System.Data.DataTable._nextRowID, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Data.ExceptionBuilder.ArgumentNull(), System.Data.InternalDataCollectionBase.Count, System.count, System.Runtime.Serialization.Dictionary, System.Data.DataTable.EnforceConstraints, System.L, System.Data.ExceptionBuilder.RowAlreadyInOtherCollection(), System.Data.ExceptionBuilder.RowAlreadyInTheCollection(), and System.Data.DataTable.SetNewRecordWorker().