Terraria: System.Data.DataTable.RaiseRowChanging
RaiseRowChanging() [2/2]
DataRowChangeEventArgs System.Data.DataTable.RaiseRowChanging (DataRowChangeEventArgs args, DataRow eRow, DataRowAction eAction, bool fireEvent) inline private inherited
Definition at line 3743 of file DataTable.cs.
    {
        if (EnforceConstraints)
        {
            int count = _columnCollection.Count;
            for (int i = 0; i < count; i++)
            {
                DataColumn dataColumn = _columnCollection[i];
                if (!dataColumn.Computed || eAction != DataRowAction.Add)
                {
                    dataColumn.CheckColumnConstraint(eRow, eAction);
                }
            }
            int count2 = _constraintCollection.Count;
            for (int j = 0; j < count2; j++)
            {
                _constraintCollection[j].CheckConstraint(eRow, eAction);
            }
        }
        if (fireEvent)
        {
            args = RaiseRowChanging(args, eRow, eAction);
        }
        if (!_inDataLoad && !MergingData && eAction != 0 && eAction != DataRowAction.ChangeOriginal)
        {
            CascadeAll(eRow, eAction);
        }
        return args;
    }
References System.Data.DataTable._columnCollection, System.Data.DataTable._constraintCollection, System.Data.DataTable._inDataLoad, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Data.DataTable.CascadeAll(), System.Data.InternalDataCollectionBase.Count, System.count, System.Runtime.Serialization.Dictionary, System.Data.DataTable.EnforceConstraints, System.Data.DataTable.MergingData, and System.Data.DataTable.RaiseRowChanging().