Terraria: System.Data.DataTable.DeserializeTableSchema
DeserializeTableSchema()
void System.Data.DataTable.DeserializeTableSchema (SerializationInfo info, StreamingContext context, bool isSingleTable) inline package inherited
Definition at line 1316 of file DataTable.cs.
    {
        _tableName = info.GetString("DataTable.TableName");
        _tableNamespace = info.GetString("DataTable.Namespace");
        _tablePrefix = info.GetString("DataTable.Prefix");
        bool boolean = info.GetBoolean("DataTable.CaseSensitive");
        SetCaseSensitiveValue(boolean, userSet: true, resetIndexes: false);
        _caseSensitiveUserSet = !info.GetBoolean("DataTable.caseSensitiveAmbient");
        int culture = (int)info.GetValue("DataTable.LocaleLCID", typeof(int));
        CultureInfo culture2 = new CultureInfo(culture);
        SetLocaleValue(culture2, userSet: true, resetIndexes: false);
        _cultureUserSet = true;
        MinimumCapacity = info.GetInt32("DataTable.MinimumCapacity");
        _fNestedInDataset = info.GetBoolean("DataTable.NestedInDataSet");
        string @string = info.GetString("DataTable.TypeName");
        _typeName = new XmlQualifiedName(@string);
        _repeatableElement = info.GetBoolean("DataTable.RepeatableElement");
        _extendedProperties = (PropertyCollection)info.GetValue("DataTable.ExtendedProperties", typeof(PropertyCollection));
        int @int = info.GetInt32("DataTable.Columns.Count");
        string[] array = new string[@int];
        IFormatProvider invariantCulture = CultureInfo.InvariantCulture;
        for (int i = 0; i < @int; i++)
        {
            DataColumn dataColumn = new DataColumn();
            dataColumn.ColumnName = info.GetString(string.Format(invariantCulture, "DataTable.DataColumn_{0}.ColumnName", i));
            dataColumn._columnUri = info.GetString(string.Format(invariantCulture, "DataTable.DataColumn_{0}.Namespace", i));
            dataColumn.Prefix = info.GetString(string.Format(invariantCulture, "DataTable.DataColumn_{0}.Prefix", i));
            string typeName = (string)info.GetValue(string.Format(invariantCulture, "DataTable.DataColumn_{0}.DataType_AssemblyQualifiedName", i), typeof(string));
            dataColumn.DataType = Type.GetType(typeName, throwOnError: true);
            dataColumn.XmlDataType = (string)info.GetValue(string.Format(invariantCulture, "DataTable.DataColumn_{0}.XmlDataType", i), typeof(string));
            dataColumn.SimpleType = (SimpleType)info.GetValue(string.Format(invariantCulture, "DataTable.DataColumn_{0}.SimpleType", i), typeof(SimpleType));
            dataColumn.ColumnMapping = (MappingType)info.GetValue(string.Format(invariantCulture, "DataTable.DataColumn_{0}.ColumnMapping", i), typeof(MappingType));
            dataColumn.DateTimeMode = (DataSetDateTime)info.GetValue(string.Format(invariantCulture, "DataTable.DataColumn_{0}.DateTimeMode", i), typeof(DataSetDateTime));
            dataColumn.AllowDBNull = info.GetBoolean(string.Format(invariantCulture, "DataTable.DataColumn_{0}.AllowDBNull", i));
            dataColumn.AutoIncrement = info.GetBoolean(string.Format(invariantCulture, "DataTable.DataColumn_{0}.AutoIncrement", i));
            dataColumn.AutoIncrementStep = info.GetInt64(string.Format(invariantCulture, "DataTable.DataColumn_{0}.AutoIncrementStep", i));
            dataColumn.AutoIncrementSeed = info.GetInt64(string.Format(invariantCulture, "DataTable.DataColumn_{0}.AutoIncrementSeed", i));
            dataColumn.Caption = info.GetString(string.Format(invariantCulture, "DataTable.DataColumn_{0}.Caption", i));
            dataColumn.DefaultValue = info.GetValue(string.Format(invariantCulture, "DataTable.DataColumn_{0}.DefaultValue", i), typeof(object));
            dataColumn.ReadOnly = info.GetBoolean(string.Format(invariantCulture, "DataTable.DataColumn_{0}.ReadOnly", i));
            dataColumn.MaxLength = info.GetInt32(string.Format(invariantCulture, "DataTable.DataColumn_{0}.MaxLength", i));
            dataColumn.AutoIncrementCurrent = info.GetValue(string.Format(invariantCulture, "DataTable.DataColumn_{0}.AutoIncrementCurrent", i), typeof(object));
            if (isSingleTable)
            {
                array[i] = info.GetString(string.Format(invariantCulture, "DataTable.DataColumn_{0}.Expression", i));
            }
            dataColumn._extendedProperties = (PropertyCollection)info.GetValue(string.Format(invariantCulture, "DataTable.DataColumn_{0}.ExtendedProperties", i), typeof(PropertyCollection));
            Columns.Add(dataColumn);
        }
        if (isSingleTable)
        {
            for (int j = 0; j < @int; j++)
            {
                if (array[j] != null)
                {
                    Columns[j].Expression = array[j];
                }
            }
        }
        if (isSingleTable)
        {
            DeserializeConstraints(info, context, 0, allConstraints: false);
        }
    }
References System.Data.DataTable._caseSensitiveUserSet, System.Data.DataTable._cultureUserSet, System.Data.DataTable._extendedProperties, System.Data.DataTable._fNestedInDataset, System.Data.DataTable._repeatableElement, System.Data.DataTable._tableName, System.Data.DataTable._tableNamespace, System.Data.DataTable._tablePrefix, System.Data.DataTable._typeName, System.Data.DataColumnCollection.Add(), System.array, System.Data.DataTable.Columns, System.culture, System.Data.DataTable.DeserializeConstraints(), System.Runtime.Serialization.Dictionary, System.Format, System.Type.GetType(), System.info, System.Globalization.CultureInfo.InvariantCulture, System.Data.DataTable.MinimumCapacity, System.Data.DataTable.SetCaseSensitiveValue(), and System.Data.DataTable.SetLocaleValue().
Referenced by System.Data.DataTable.DeserializeDataTable().