Terraria: System.Data.DataTable.EndLoadData
EndLoadData()
void System.Data.DataTable.EndLoadData () inline inherited
Definition at line 4083 of file DataTable.cs.
    {
        long scopeId = DataCommonEventSource.Log.EnterScope("<ds.DataTable.EndLoadData|API> {0}", ObjectID);
        try
        {
            if (_inDataLoad)
            {
                if (_loadIndex != null)
                {
                    _loadIndex.RemoveRef();
                }
                if (_loadIndexwithOriginalAdded != null)
                {
                    _loadIndexwithOriginalAdded.RemoveRef();
                }
                if (_loadIndexwithCurrentDeleted != null)
                {
                    _loadIndexwithCurrentDeleted.RemoveRef();
                }
                _loadIndex = null;
                _loadIndexwithOriginalAdded = null;
                _loadIndexwithCurrentDeleted = null;
                _inDataLoad = false;
                RestoreIndexEvents(forceReset: false);
                if (DataSet != null)
                {
                    DataSet.EnforceConstraints = _savedEnforceConstraints;
                }
                else
                {
                    EnforceConstraints = true;
                }
            }
        }
        finally
        {
            DataCommonEventSource.Log.ExitScope(scopeId);
        }
    }
References System.Data.DataTable._inDataLoad, System.Data.DataTable._loadIndex, System.Data.DataTable._loadIndexwithCurrentDeleted, System.Data.DataTable._loadIndexwithOriginalAdded, System.Data.DataTable._savedEnforceConstraints, System.Runtime.Serialization.Dictionary, System.Data.DataTable.EnforceConstraints, System.Data.DataCommonEventSource.Log, System.Data.DataTable.ObjectID, System.Data.Index.RemoveRef(), and System.Data.DataTable.RestoreIndexEvents().
Referenced by System.Data.Common.DataAdapter.FillFromReader().