Terraria: System.Data.DataTable.SerializeConstraints
SerializeConstraints()
void System.Data.DataTable.SerializeConstraints (SerializationInfo info, StreamingContext context, int serIndex, bool allConstraints) inline package inherited
Definition at line 1381 of file DataTable.cs.
    {
        ArrayList arrayList = new ArrayList();
        for (int i = 0; i < Constraints.Count; i++)
        {
            Constraint constraint = Constraints[i];
            if (constraint is UniqueConstraint uniqueConstraint)
            {
                int[] array = new int[uniqueConstraint.Columns.Length];
                for (int j = 0; j < array.Length; j++)
                {
                    array[j] = uniqueConstraint.Columns[j].Ordinal;
                }
                ArrayList arrayList2 = new ArrayList();
                arrayList2.Add("U");
                arrayList2.Add(uniqueConstraint.ConstraintName);
                arrayList2.Add(array);
                arrayList2.Add(uniqueConstraint.IsPrimaryKey);
                arrayList2.Add(uniqueConstraint.ExtendedProperties);
                arrayList.Add(arrayList2);
                continue;
            }
            ForeignKeyConstraint foreignKeyConstraint = constraint as ForeignKeyConstraint;
            if (allConstraints || (foreignKeyConstraint.Table == this && foreignKeyConstraint.RelatedTable == this))
            {
                int[] array2 = new int[foreignKeyConstraint.RelatedColumns.Length + 1];
                array2[0] = (allConstraints ? DataSet.Tables.IndexOf(foreignKeyConstraint.RelatedTable) : 0);
                for (int k = 1; k < array2.Length; k++)
                {
                    array2[k] = foreignKeyConstraint.RelatedColumns[k - 1].Ordinal;
                }
                int[] array3 = new int[foreignKeyConstraint.Columns.Length + 1];
                array3[0] = (allConstraints ? DataSet.Tables.IndexOf(foreignKeyConstraint.Table) : 0);
                for (int l = 1; l < array3.Length; l++)
                {
                    array3[l] = foreignKeyConstraint.Columns[l - 1].Ordinal;
                }
                ArrayList arrayList3 = new ArrayList();
                arrayList3.Add("F");
                arrayList3.Add(foreignKeyConstraint.ConstraintName);
                arrayList3.Add(array2);
                arrayList3.Add(array3);
                arrayList3.Add(new int[3]
                {
                    (int)foreignKeyConstraint.AcceptRejectRule,
                    (int)foreignKeyConstraint.UpdateRule,
                    (int)foreignKeyConstraint.DeleteRule
                });
                arrayList3.Add(foreignKeyConstraint.ExtendedProperties);
                arrayList.Add(arrayList3);
            }
        }
        info.AddValue(string.Format(CultureInfo.InvariantCulture, "DataTable_{0}.Constraints", serIndex), arrayList);
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.array, System.Data.DataTable.Constraints, System.Data.InternalDataCollectionBase.Count, System.Runtime.Serialization.Dictionary, System.Format, System.Data.DataTableCollection.IndexOf(), System.info, System.Globalization.CultureInfo.InvariantCulture, and System.Data.DataSet.Tables.
Referenced by System.Data.DataTable.SerializeTableSchema().