Terraria: System.Data.DataTable.GetSpecialHashCode
GetSpecialHashCode()
int System.Data.DataTable.GetSpecialHashCode (string name) inline package inherited
Definition at line 2899 of file DataTable.cs.
    {
        int i;
        for (i = 0; i < name.Length && '\u3000' > name[i]; i++)
        {
        }
        if (name.Length == i)
        {
            if (_hashCodeProvider == null)
            {
                _hashCodeProvider = StringComparer.Create(Locale, ignoreCase: true);
            }
            return _hashCodeProvider.GetHashCode(name);
        }
        return 0;
    }
References System.Data.DataTable._hashCodeProvider, System.StringComparer.Create(), System.Runtime.Serialization.Dictionary, System.StringComparer.GetHashCode(), and System.Data.DataTable.Locale.
Referenced by System.Data.DataColumnCollection.IndexOfCaseInsensitive(), System.Data.DataColumnCollection.RegisterColumnName(), and System.Data.DataTable.SetLocaleValue().