Terraria: System.Data.DataTable.BeginLoadData
BeginLoadData()
void System.Data.DataTable.BeginLoadData () inline inherited
Definition at line 4040 of file DataTable.cs.
    {
        long scopeId = DataCommonEventSource.Log.EnterScope("<ds.DataTable.BeginLoadData|API> {0}", ObjectID);
        try
        {
            if (_inDataLoad)
            {
                return;
            }
            _inDataLoad = true;
            _loadIndex = null;
            _initialLoad = Rows.Count == 0;
            if (_initialLoad)
            {
                SuspendIndexEvents();
            }
            else
            {
                if (_primaryKey != null)
                {
                    _loadIndex = _primaryKey.Key.GetSortIndex(DataViewRowState.OriginalRows);
                }
                if (_loadIndex != null)
                {
                    _loadIndex.AddRef();
                }
            }
            if (DataSet != null)
            {
                _savedEnforceConstraints = DataSet.EnforceConstraints;
                DataSet.EnforceConstraints = false;
            }
            else
            {
                EnforceConstraints = false;
            }
        }
        finally
        {
            DataCommonEventSource.Log.ExitScope(scopeId);
        }
    }
References System.Data.DataTable._inDataLoad, System.Data.DataTable._initialLoad, System.Data.DataTable._loadIndex, System.Data.DataTable._primaryKey, System.Data.DataTable._savedEnforceConstraints, System.Data.Index.AddRef(), System.Runtime.Serialization.Dictionary, System.Data.DataSet.EnforceConstraints, System.Data.DataTable.EnforceConstraints, System.Data.DataKey.GetSortIndex(), System.Data.UniqueConstraint.Key, System.Data.DataCommonEventSource.Log, System.Data.DataTable.ObjectID, and System.Data.DataTable.SuspendIndexEvents().
Referenced by System.Data.Common.DataAdapter.FillFromReader().