Terraria: System.Data.DataTable.RaiseRowChanged
RaiseRowChanged()
DataRowChangeEventArgs System.Data.DataTable.RaiseRowChanged (DataRowChangeEventArgs args, DataRow eRow, DataRowAction eAction) inline private inherited
Definition at line 3686 of file DataTable.cs.
    {
        try
        {
            if (UpdatingCurrent(eRow, eAction) && (IsTypedDataTable || _onRowChangedDelegate != null))
            {
                args = OnRowChanged(args, eRow, eAction);
            }
            else if (DataRowAction.Delete == eAction && eRow._newRecord == -1 && (IsTypedDataTable || _onRowDeletedDelegate != null))
            {
                if (args == null)
                {
                    args = new DataRowChangeEventArgs(eRow, eAction);
                }
                OnRowDeleted(args);
            }
        }
        catch (Exception e) when (ADP.IsCatchableExceptionType(e))
        {
            ExceptionBuilder.TraceExceptionWithoutRethrow(e);
        }
        return args;
    }
References System.Data.DataTable._onRowChangedDelegate, System.Data.DataTable._onRowDeletedDelegate, System.Runtime.Serialization.Dictionary, System.Data.Common.ADP.IsCatchableExceptionType(), System.Data.DataTable.IsTypedDataTable, System.Data.DataTable.OnRowChanged(), System.Data.DataTable.OnRowDeleted(), System.Data.ExceptionBuilder.TraceExceptionWithoutRethrow(), and System.Data.DataTable.UpdatingCurrent().
Referenced by System.Data.DataTable.InsertRow(), System.Data.DataTable.LoadRow(), System.Data.DataTable.SetDataRowWithLoadOption(), and System.Data.DataTable.SetNewRecordWorker().