Terraria: System.Data.DataTable.RestoreShadowIndexes
RestoreShadowIndexes()
void System.Data.DataTable.RestoreShadowIndexes () inline private inherited
Definition at line 4001 of file DataTable.cs.
    {
        _shadowCount--;
        if (_shadowCount == 0)
        {
            _shadowIndexes = null;
        }
    }
References System.Data.DataTable._shadowCount, and System.Data.DataTable._shadowIndexes.
Referenced by System.Data.DataTable.RecordChanged(), System.Data.DataTable.RecordChanged(), System.Data.DataTable.RecordStateChanged(), System.Data.DataTable.RecordStateChanged(), System.Data.DataTable.ResetInternalIndexes(), and System.Data.DataTable.RestoreIndexEvents().