Terraria: System.Data.DataTable.IsEmptyXml
IsEmptyXml()
bool System.Data.DataTable.IsEmptyXml (XmlReader reader) inline private inherited
Definition at line 5054 of file DataTable.cs.
    {
        if (reader.IsEmptyElement)
        {
            if (reader.AttributeCount == 0 || (reader.LocalName == "diffgram" && reader.NamespaceURI == "urn:schemas-microsoft-com:xml-diffgram-v1"))
            {
                return true;
            }
            if (reader.AttributeCount == 1)
            {
                reader.MoveToAttribute(0);
                if (Namespace == reader.Value && Prefix == reader.LocalName && reader.Prefix == "xmlns" && reader.NamespaceURI == "http://www.w3.org/2000/xmlns/")
                {
                    return true;
                }
            }
        }
        return false;
    }
References System.Xml.XmlReader.AttributeCount, System.Xml.XmlReader.IsEmptyElement, System.Xml.XmlReader.LocalName, System.Xml.XmlReader.MoveToAttribute(), System.Data.DataTable.Namespace, System.Xml.XmlReader.NamespaceURI, System.Data.DataTable.Prefix, System.Xml.XmlReader.Prefix, and System.Xml.XmlReader.Value.
Referenced by System.Data.DataTable.ReadXml(), and System.Data.DataTable.ReadXml().