Terraria: System.Data.DataTable.ParseSortString
ParseSortString()
IndexField[] System.Data.DataTable.ParseSortString (string sortString) inline package inherited
Definition at line 3339 of file DataTable.cs.
    {
        IndexField[] array = Array.Empty<IndexField>();
        if (sortString != null && 0 < sortString.Length)
        {
            string[] array2 = sortString.Split(',', StringSplitOptions.TrimEntries);
            array = new IndexField[array2.Length];
            for (int i = 0; i < array2.Length; i++)
            {
                string text = array2[i];
                int length = text.Length;
                bool isDescending = false;
                if (length >= 5 && string.Compare(text, length - 4, " ASC", 0, 4, StringComparison.OrdinalIgnoreCase) == 0)
                {
                    text = text.AsSpan(0, length - 4).Trim().ToString();
                }
                else if (length >= 6 && string.Compare(text, length - 5, " DESC", 0, 5, StringComparison.OrdinalIgnoreCase) == 0)
                {
                    isDescending = true;
                    text = text.AsSpan(0, length - 5).Trim().ToString();
                }
                if (text.StartsWith('['))
                {
                    if (!text.EndsWith(']'))
                    {
                        throw ExceptionBuilder.InvalidSortString(array2[i]);
                    }
                    text = text.Substring(1, text.Length - 2);
                }
                DataColumn dataColumn = Columns[text];
                if (dataColumn == null)
                {
                    throw ExceptionBuilder.ColumnOutOfRange(text);
                }
                array[i] = new IndexField(dataColumn, isDescending);
            }
        }
        return array;
    }
References System.array, System.Data.ExceptionBuilder.ColumnOutOfRange(), System.Data.DataTable.Columns, System.Data.DataTable.Compare(), System.Data.ExceptionBuilder.InvalidSortString(), System.length, and System.text.
Referenced by System.Data.Select.Select(), System.Data.DataView.CheckSort(), and System.Data.DataTable.GetIndex().