Terraria: System.Data.DataTable.EndInit
EndInit()
virtual void System.Data.DataTable.EndInit () inline virtual inherited
Implements System.ComponentModel.ISupportInitialize.
Definition at line 2035 of file DataTable.cs.
    {
        if (_dataSet == null || !_dataSet._fInitInProgress)
        {
            Columns.FinishInitCollection();
            Constraints.FinishInitConstraints();
            foreach (DataColumn column in Columns)
            {
                if (column.Computed)
                {
                    column.CopyExpressionFrom(column);
                }
            }
        }
        fInitInProgress = false;
        if (_delayedSetPrimaryKey != null)
        {
            PrimaryKey = _delayedSetPrimaryKey;
            _delayedSetPrimaryKey = null;
        }
        if (_delayedViews.Count > 0)
        {
            foreach (DataView delayedView in _delayedViews)
            {
                delayedView.EndInit();
            }
            _delayedViews.Clear();
        }
        OnInitialized();
    }
References System.Data.DataTable._dataSet, System.Data.DataTable._delayedSetPrimaryKey, System.Data.DataTable._delayedViews, System.Data.DataSet._fInitInProgress, System.Collections.Generic.Dictionary< TKey, TValue >.Clear(), System.Data.DataTable.Columns, System.Data.DataTable.Constraints, System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Data.DataColumnCollection.FinishInitCollection(), System.Data.ConstraintCollection.FinishInitConstraints(), System.Data.DataTable.fInitInProgress, System.Data.DataTable.OnInitialized(), and System.Data.DataTable.PrimaryKey.