Terraria: System.Data.DataTable.SerializeTableSchema
SerializeTableSchema()
void System.Data.DataTable.SerializeTableSchema (SerializationInfo info, StreamingContext context, bool isSingleTable) inline package inherited
Definition at line 1260 of file DataTable.cs.
    {
        info.AddValue("DataTable.TableName", TableName);
        info.AddValue("DataTable.Namespace", Namespace);
        info.AddValue("DataTable.Prefix", Prefix);
        info.AddValue("DataTable.CaseSensitive", _caseSensitive);
        info.AddValue("DataTable.caseSensitiveAmbient", !_caseSensitiveUserSet);
        info.AddValue("DataTable.LocaleLCID", Locale.LCID);
        info.AddValue("DataTable.MinimumCapacity", _recordManager.MinimumCapacity);
        info.AddValue("DataTable.NestedInDataSet", _fNestedInDataset);
        info.AddValue("DataTable.TypeName", TypeName.ToString());
        info.AddValue("DataTable.RepeatableElement", _repeatableElement);
        info.AddValue("DataTable.ExtendedProperties", ExtendedProperties);
        info.AddValue("DataTable.Columns.Count", Columns.Count);
        if (isSingleTable)
        {
            List<DataTable> list = new List<DataTable>();
            list.Add(this);
            if (!CheckForClosureOnExpressionTables(list))
            {
                throw ExceptionBuilder.CanNotRemoteDataTable();
            }
        }
        IFormatProvider invariantCulture = CultureInfo.InvariantCulture;
        for (int i = 0; i < Columns.Count; i++)
        {
            info.AddValue(string.Format(invariantCulture, "DataTable.DataColumn_{0}.ColumnName", i), Columns[i].ColumnName);
            info.AddValue(string.Format(invariantCulture, "DataTable.DataColumn_{0}.Namespace", i), Columns[i]._columnUri);
            info.AddValue(string.Format(invariantCulture, "DataTable.DataColumn_{0}.Prefix", i), Columns[i].Prefix);
            info.AddValue(string.Format(invariantCulture, "DataTable.DataColumn_{0}.ColumnMapping", i), Columns[i].ColumnMapping);
            info.AddValue(string.Format(invariantCulture, "DataTable.DataColumn_{0}.AllowDBNull", i), Columns[i].AllowDBNull);
            info.AddValue(string.Format(invariantCulture, "DataTable.DataColumn_{0}.AutoIncrement", i), Columns[i].AutoIncrement);
            info.AddValue(string.Format(invariantCulture, "DataTable.DataColumn_{0}.AutoIncrementStep", i), Columns[i].AutoIncrementStep);
            info.AddValue(string.Format(invariantCulture, "DataTable.DataColumn_{0}.AutoIncrementSeed", i), Columns[i].AutoIncrementSeed);
            info.AddValue(string.Format(invariantCulture, "DataTable.DataColumn_{0}.Caption", i), Columns[i].Caption);
            info.AddValue(string.Format(invariantCulture, "DataTable.DataColumn_{0}.DefaultValue", i), Columns[i].DefaultValue);
            info.AddValue(string.Format(invariantCulture, "DataTable.DataColumn_{0}.ReadOnly", i), Columns[i].ReadOnly);
            info.AddValue(string.Format(invariantCulture, "DataTable.DataColumn_{0}.MaxLength", i), Columns[i].MaxLength);
            info.AddValue(string.Format(invariantCulture, "DataTable.DataColumn_{0}.DataType_AssemblyQualifiedName", i), Columns[i].DataType.AssemblyQualifiedName);
            info.AddValue(string.Format(invariantCulture, "DataTable.DataColumn_{0}.XmlDataType", i), Columns[i].XmlDataType);
            info.AddValue(string.Format(invariantCulture, "DataTable.DataColumn_{0}.SimpleType", i), Columns[i].SimpleType);
            info.AddValue(string.Format(invariantCulture, "DataTable.DataColumn_{0}.DateTimeMode", i), Columns[i].DateTimeMode);
            info.AddValue(string.Format(invariantCulture, "DataTable.DataColumn_{0}.AutoIncrementCurrent", i), Columns[i].AutoIncrementCurrent);
            if (isSingleTable)
            {
                info.AddValue(string.Format(invariantCulture, "DataTable.DataColumn_{0}.Expression", i), Columns[i].Expression);
            }
            info.AddValue(string.Format(invariantCulture, "DataTable.DataColumn_{0}.ExtendedProperties", i), Columns[i]._extendedProperties);
        }
        if (isSingleTable)
        {
            SerializeConstraints(info, context, 0, allConstraints: false);
        }
    }
References System.Data.DataTable._caseSensitive, System.Data.DataTable._caseSensitiveUserSet, System.Data.DataTable._extendedProperties, System.Data.DataTable._fNestedInDataset, System.Data.DataTable._recordManager, System.Data.DataTable._repeatableElement, System.Data.ExceptionBuilder.CanNotRemoteDataTable(), System.Data.DataTable.CheckForClosureOnExpressionTables(), System.Data.DataTable.Columns, System.Data.InternalDataCollectionBase.Count, System.Runtime.Serialization.Dictionary, System.Data.DataTable.ExtendedProperties, System.Format, System.info, System.Globalization.CultureInfo.InvariantCulture, System.Globalization.CultureInfo.LCID, System.list, System.Data.DataTable.Locale, System.Xml.Schema.MaxLength, System.Data.RecordManager.MinimumCapacity, System.Data.DataTable.Namespace, System.Data.DataTable.Prefix, System.IO.ReadOnly, System.Data.DataTable.SerializeConstraints(), System.Data.DataTable.TableName, System.Xml.XmlQualifiedName.ToString(), and System.Data.DataTable.TypeName.
Referenced by System.Data.DataTable.SerializeDataTable().