Terraria: System.Data.DataTable.MergeRow
MergeRow()
DataRow System.Data.DataTable.MergeRow (DataRow row, DataRow targetRow, bool preserveChanges, Index idxSearch) inline package inherited
Definition at line 2111 of file DataTable.cs.
    {
        if (targetRow == null)
        {
            targetRow = NewEmptyRow();
            targetRow._oldRecord = _recordManager.ImportRecord(row.Table, row._oldRecord);
            targetRow._newRecord = targetRow._oldRecord;
            if (row._oldRecord != row._newRecord)
            {
                targetRow._newRecord = _recordManager.ImportRecord(row.Table, row._newRecord);
            }
            InsertRow(targetRow, -1L);
        }
        else
        {
            int tempRecord = targetRow._tempRecord;
            targetRow._tempRecord = -1;
            try
            {
                DataRowState rowState = targetRow.RowState;
                int oldRecord = ((rowState == DataRowState.Added) ? targetRow._newRecord : (oldRecord = targetRow._oldRecord));
                if (targetRow.RowState == DataRowState.Unchanged && row.RowState == DataRowState.Unchanged)
                {
                    int oldRecord2 = targetRow._oldRecord;
                    int newRecord = (preserveChanges ? _recordManager.CopyRecord(this, oldRecord2, -1) : targetRow._newRecord);
                    oldRecord2 = _recordManager.CopyRecord(row.Table, row._oldRecord, targetRow._oldRecord);
                    SetMergeRecords(targetRow, newRecord, oldRecord2, DataRowAction.Change);
                }
                else if (row._newRecord == -1)
                {
                    int oldRecord2 = targetRow._oldRecord;
                    int newRecord = ((!preserveChanges) ? (-1) : ((targetRow.RowState == DataRowState.Unchanged) ? _recordManager.CopyRecord(this, oldRecord2, -1) : targetRow._newRecord));
                    oldRecord2 = _recordManager.CopyRecord(row.Table, row._oldRecord, oldRecord2);
                    if (oldRecord != ((rowState == DataRowState.Added) ? newRecord : oldRecord2))
                    {
                        SetMergeRecords(targetRow, newRecord, oldRecord2, (newRecord == -1) ? DataRowAction.Delete : DataRowAction.Change);
                        idxSearch.Reset();
                        oldRecord = ((rowState == DataRowState.Added) ? newRecord : oldRecord2);
                    }
                    else
                    {
                        SetMergeRecords(targetRow, newRecord, oldRecord2, (newRecord == -1) ? DataRowAction.Delete : DataRowAction.Change);
                    }
                }
                else
                {
                    int oldRecord2 = targetRow._oldRecord;
                    int newRecord = targetRow._newRecord;
                    if (targetRow.RowState == DataRowState.Unchanged)
                    {
                        newRecord = _recordManager.CopyRecord(this, oldRecord2, -1);
                    }
                    oldRecord2 = _recordManager.CopyRecord(row.Table, row._oldRecord, oldRecord2);
                    if (!preserveChanges)
                    {
                        newRecord = _recordManager.CopyRecord(row.Table, row._newRecord, newRecord);
                    }
                    SetMergeRecords(targetRow, newRecord, oldRecord2, DataRowAction.Change);
                }
                if (rowState == DataRowState.Added && targetRow._oldRecord != -1)
                {
                    idxSearch.Reset();
                }
            }
            finally
            {
                targetRow._tempRecord = tempRecord;
            }
        }
        if (row.HasErrors)
        {
            if (targetRow.RowError.Length == 0)
            {
                targetRow.RowError = row.RowError;
            }
            else
            {
                DataRow dataRow = targetRow;
                dataRow.RowError = dataRow.RowError + " ]:[ " + row.RowError;
            }
            DataColumn[] columnsInError = row.GetColumnsInError();
            for (int i = 0; i < columnsInError.Length; i++)
            {
                DataColumn column = targetRow.Table.Columns[columnsInError[i].ColumnName];
                targetRow.SetColumnError(column, row.GetColumnError(columnsInError[i]));
            }
        }
        else if (!preserveChanges)
        {
            targetRow.ClearErrors();
        }
        return targetRow;
    }
References System.Data.DataTable._recordManager, System.Data.RecordManager.CopyRecord(), System.Runtime.Serialization.Dictionary, System.Data.RecordManager.ImportRecord(), System.Data.DataTable.InsertRow(), System.L, System.Data.DataTable.NewEmptyRow(), and System.Data.DataTable.SetMergeRecords().