Terraria: System.Data.DataTable.FindRow
FindRow() [2/2]
DataRow System.Data.DataTable.FindRow (DataKey key, object[] values) inline private inherited
Definition at line 2740 of file DataTable.cs.
    {
        Index index = GetIndex(NewIndexDesc(key));
        Range range = index.FindRecords(values);
        if (range.IsNull)
        {
            return null;
        }
        return _recordManager[index.GetRecord(range.Min)];
    }
References System.Data.DataTable._recordManager, System.Data.DataTable.GetIndex(), System.index, System.key, System.Data.DataTable.NewIndexDesc(), and System.values.
Referenced by System.Data.DataTable.FindByPrimaryKey(), and System.Data.DataTable.FindByPrimaryKey().