Terraria: System.Data.DataTable.ReadXml
ReadXml() [5/7]
XmlReadMode System.Data.DataTable.ReadXml (XmlReader reader, bool denyResolving) inline package inherited
Definition at line 5075 of file DataTable.cs.
    {
        IDisposable disposable = null;
        long scopeId = DataCommonEventSource.Log.EnterScope("<ds.DataTable.ReadXml|INFO> {0}, denyResolving={1}", ObjectID, denyResolving);
        try
        {
            disposable = TypeLimiter.EnterRestrictedScope(this);
            RowDiffIdUsageSection rowDiffIdUsageSection = default(RowDiffIdUsageSection);
            try
            {
                bool flag = false;
                bool flag2 = false;
                bool flag3 = false;
                bool isXdr = false;
                int num = -1;
                XmlReadMode result = XmlReadMode.Auto;
                rowDiffIdUsageSection.Prepare(this);
                if (reader == null)
                {
                    return result;
                }
                bool flag4 = false;
                if (DataSet != null)
                {
                    flag4 = DataSet.EnforceConstraints;
                    DataSet.EnforceConstraints = false;
                }
                else
                {
                    flag4 = EnforceConstraints;
                    EnforceConstraints = false;
                }
                if (reader is XmlTextReader)
                {
                    ((XmlTextReader)reader).WhitespaceHandling = WhitespaceHandling.Significant;
                }
                XmlDocument xmlDocument = new XmlDocument();
                XmlDataLoader xmlDataLoader = null;
                reader.MoveToContent();
                if (Columns.Count == 0 && IsEmptyXml(reader))
                {
                    reader.Read();
                    return result;
                }
                if (reader.NodeType == XmlNodeType.Element)
                {
                    num = reader.Depth;
                    if (reader.LocalName == "diffgram" && reader.NamespaceURI == "urn:schemas-microsoft-com:xml-diffgram-v1")
                    {
                        if (Columns.Count == 0)
{
                            if (reader.IsEmptyElement)
{
                                reader.Read();
                                return XmlReadMode.DiffGram;
                            }
                            throw ExceptionBuilder.DataTableInferenceNotSupported();
                        }
                        ReadXmlDiffgram(reader);
                        ReadEndElement(reader);
                        RestoreConstraint(flag4);
                        return XmlReadMode.DiffGram;
                    }
                    if (reader.LocalName == "Schema" && reader.NamespaceURI == "urn:schemas-microsoft-com:xml-data")
                    {
                        ReadXDRSchema(reader);
                        RestoreConstraint(flag4);
                        return XmlReadMode.ReadSchema;
                    }
                    if (reader.LocalName == "schema" && reader.NamespaceURI == "http://www.w3.org/2001/XMLSchema")
                    {
                        ReadXmlSchema(reader, denyResolving);
                        RestoreConstraint(flag4);
                        return XmlReadMode.ReadSchema;
                    }
                    if (reader.LocalName == "schema" && reader.NamespaceURI.StartsWith("http://www.w3.org/", StringComparison.Ordinal))
                    {
                        if (DataSet != null)
{
                            DataSet.RestoreEnforceConstraints(flag4);
                        }
                        else
{
                            _enforceConstraints = flag4;
                        }
                        throw ExceptionBuilder.DataSetUnsupportedSchema("http://www.w3.org/2001/XMLSchema");
                    }
                    XmlElement xmlElement = xmlDocument.CreateElement(reader.Prefix, reader.LocalName, reader.NamespaceURI);
                    if (reader.HasAttributes)
                    {
                        int attributeCount = reader.AttributeCount;
                        for (int i = 0; i < attributeCount; i++)
{
                            reader.MoveToAttribute(i);
                            if (reader.NamespaceURI.Equals("http://www.w3.org/2000/xmlns/"))
{
                                xmlElement.SetAttribute(reader.Name, reader.GetAttribute(i));
                                continue;
                            }
                            XmlAttribute xmlAttribute = xmlElement.SetAttributeNode(reader.LocalName, reader.NamespaceURI);
                            xmlAttribute.Prefix = reader.Prefix;
                            xmlAttribute.Value = reader.GetAttribute(i);
                        }
                    }
                    reader.Read();
                    while (MoveToElement(reader, num))
                    {
                        if (reader.LocalName == "diffgram" && reader.NamespaceURI == "urn:schemas-microsoft-com:xml-diffgram-v1")
{
                            ReadXmlDiffgram(reader);
                            ReadEndElement(reader);
                            RestoreConstraint(flag4);
                            return XmlReadMode.DiffGram;
                        }
                        if (!flag2 && !flag && reader.LocalName == "Schema" && reader.NamespaceURI == "urn:schemas-microsoft-com:xml-data")
{
                            ReadXDRSchema(reader);
                            flag2 = true;
                            isXdr = true;
                            continue;
                        }
                        if (reader.LocalName == "schema" && reader.NamespaceURI == "http://www.w3.org/2001/XMLSchema")
{
                            ReadXmlSchema(reader, denyResolving);
                            flag2 = true;
                            continue;
                        }
                        if (reader.LocalName == "schema" && reader.NamespaceURI.StartsWith("http://www.w3.org/", StringComparison.Ordinal))
{
                            if (DataSet != null)
{
                                DataSet.RestoreEnforceConstraints(flag4);
                            }
                            else
{
                                _enforceConstraints = flag4;
                            }
                            throw ExceptionBuilder.DataSetUnsupportedSchema("http://www.w3.org/2001/XMLSchema");
                        }
                        if (reader.LocalName == "diffgram" && reader.NamespaceURI == "urn:schemas-microsoft-com:xml-diffgram-v1")
{
                            ReadXmlDiffgram(reader);
                            flag3 = true;
                            result = XmlReadMode.DiffGram;
                            continue;
                        }
                        flag = true;
                        if (!flag2 && Columns.Count == 0)
{
                            XmlNode newChild = xmlDocument.ReadNode(reader);
                            xmlElement.AppendChild(newChild);
                            continue;
                        }
                        if (xmlDataLoader == null)
{
                            xmlDataLoader = new XmlDataLoader(this, isXdr, xmlElement, ignoreSchema: false);
                        }
                        xmlDataLoader.LoadData(reader);
                        result = (flag2 ? XmlReadMode.ReadSchema : XmlReadMode.IgnoreSchema);
                    }
                    ReadEndElement(reader);
                    xmlDocument.AppendChild(xmlElement);
                    if (!flag2 && Columns.Count == 0)
                    {
                        if (IsEmptyXml(reader))
{
                            reader.Read();
                            return result;
                        }
                        throw ExceptionBuilder.DataTableInferenceNotSupported();
                    }
                    if (xmlDataLoader == null)
                    {
                        xmlDataLoader = new XmlDataLoader(this, isXdr, ignoreSchema: false);
                    }
                }
                RestoreConstraint(flag4);
                return result;
            }
            finally
            {
            }
        }
        finally
        {
            disposable?.Dispose();
            DataCommonEventSource.Log.ExitScope(scopeId);
        }
    }
References System.Data.DataTable._enforceConstraints, System.Xml.XmlReader.AttributeCount, System.Data.DataTable.Columns, System.Data.InternalDataCollectionBase.Count, System.Data.ExceptionBuilder.DataSetUnsupportedSchema(), System.Data.ExceptionBuilder.DataTableInferenceNotSupported(), System.Xml.XmlReader.Depth, System.Runtime.Serialization.Dictionary, System.Data.DataSet.EnforceConstraints, System.Data.DataTable.EnforceConstraints, System.Data.TypeLimiter.EnterRestrictedScope(), System.Xml.XmlReader.GetAttribute(), System.Xml.XmlReader.HasAttributes, System.Xml.XmlReader.IsEmptyElement, System.Data.DataTable.IsEmptyXml(), System.Xml.XmlReader.LocalName, System.Data.DataCommonEventSource.Log, System.Xml.XmlReader.MoveToAttribute(), System.Xml.XmlReader.MoveToContent(), System.Data.DataTable.MoveToElement(), System.Xml.XmlReader.Name, System.Xml.XmlReader.NamespaceURI, System.Xml.XmlReader.NodeType, System.Data.DataTable.ObjectID, System.Xml.XmlReader.Prefix, System.Xml.XmlReader.Read(), System.Data.DataTable.ReadEndElement(), System.Data.DataTable.ReadXDRSchema(), System.Data.DataTable.ReadXmlDiffgram(), System.Data.DataTable.ReadXmlSchema(), System.Data.DataTable.RestoreConstraint(), and System.Data.DataSet.RestoreEnforceConstraints().