Terraria: System.Data.DataTable.CheckForClosureOnExpressionTables
CheckForClosureOnExpressionTables()
bool System.Data.DataTable.CheckForClosureOnExpressionTables (List< DataTable > tableList) inline private inherited
Definition at line 4903 of file DataTable.cs.
    {
        foreach (DataTable table in tableList)
        {
            foreach (DataColumn column in table.Columns)
            {
                if (column.Expression.Length == 0)
                {
                    continue;
                }
                DataColumn[] dependency = column.DataExpression.GetDependency();
                for (int i = 0; i < dependency.Length; i++)
                {
                    if (!tableList.Contains(dependency[i].Table))
                    {
                        return false;
                    }
                }
            }
        }
        return true;
    }
References System.Data.DataTable.Columns, and System.Collections.Generic.Dictionary< TKey, TValue >.Contains().
Referenced by System.Data.DataTable.CheckForClosureOnExpressions(), and System.Data.DataTable.SerializeTableSchema().