Terraria: System.Data.DataTable.Reset
Reset()
virtual void System.Data.DataTable.Reset () inline virtual inherited
Definition at line 3604 of file DataTable.cs.
    {
        long scopeId = DataCommonEventSource.Log.EnterScope("<ds.DataTable.Reset|API> {0}", ObjectID);
        try
        {
            Clear();
            ResetConstraints();
            DataRelationCollection parentRelations = ParentRelations;
            int num = parentRelations.Count;
            while (num > 0)
            {
                num--;
                parentRelations.RemoveAt(num);
            }
            parentRelations = ChildRelations;
            num = parentRelations.Count;
            while (num > 0)
            {
                num--;
                parentRelations.RemoveAt(num);
            }
            Columns.Clear();
            _indexes.Clear();
        }
        finally
        {
            DataCommonEventSource.Log.ExitScope(scopeId);
        }
    }
References System.Data.DataTable._indexes, System.Data.DataTable.ChildRelations, System.Data.DataColumnCollection.Clear(), System.Data.DataTable.Clear(), System.Collections.Generic.Dictionary< TKey, TValue >.Clear(), System.Data.DataTable.Columns, System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Data.DataCommonEventSource.Log, System.Data.DataTable.ObjectID, System.Data.DataTable.ParentRelations, and System.Data.DataTable.ResetConstraints().