Terraria: System.Data.DataTable.SetNewRecordWorker
SetNewRecordWorker()
void System.Data.DataTable.SetNewRecordWorker (DataRow row, int proposedRecord, DataRowAction action, bool isInMerge, bool suppressEnsurePropertyChanged, int position, bool fireEvent, out Exception deferredException) inline private inherited
Definition at line 3811 of file DataTable.cs.
    {
        deferredException = null;
        if (row._tempRecord != proposedRecord)
        {
            if (!_inDataLoad)
            {
                row.CheckInTable();
                CheckNotModifying(row);
            }
            if (proposedRecord == row._newRecord)
            {
                if (isInMerge)
                {
                    RaiseRowChanged(null, row, action);
                }
                return;
            }
            row._tempRecord = proposedRecord;
        }
        DataRowChangeEventArgs args = null;
        try
        {
            row._action = action;
            args = RaiseRowChanging(null, row, action, fireEvent);
        }
        catch
        {
            row._tempRecord = -1;
            throw;
        }
        finally
        {
            row._action = DataRowAction.Nothing;
        }
        row._tempRecord = -1;
        int record = row._newRecord;
        int num = ((proposedRecord != -1) ? proposedRecord : ((row.RowState != DataRowState.Unchanged) ? row._oldRecord : (-1)));
        if (action == DataRowAction.Add)
        {
            if (position == -1)
            {
                Rows.ArrayAdd(row);
            }
            else
            {
                Rows.ArrayInsert(row, position);
            }
        }
        List<DataRow> list = null;
        if ((action == DataRowAction.Delete || action == DataRowAction.Change) && _dependentColumns != null && _dependentColumns.Count > 0)
        {
            list = new List<DataRow>();
            for (int i = 0; i < ParentRelations.Count; i++)
            {
                DataRelation dataRelation = ParentRelations[i];
                if (dataRelation.ChildTable == row.Table)
                {
                    list.InsertRange(list.Count, row.GetParentRows(dataRelation));
                }
            }
            for (int j = 0; j < ChildRelations.Count; j++)
            {
                DataRelation dataRelation2 = ChildRelations[j];
                if (dataRelation2.ParentTable == row.Table)
                {
                    list.InsertRange(list.Count, row.GetChildRows(dataRelation2));
                }
            }
        }
        if (!suppressEnsurePropertyChanged && !row.HasPropertyChanged && row._newRecord != proposedRecord && -1 != proposedRecord && -1 != row._newRecord)
        {
            row.LastChangedColumn = null;
            row.LastChangedColumn = null;
        }
        if (LiveIndexes.Count != 0)
        {
            if (-1 == record && -1 != proposedRecord && -1 != row._oldRecord && proposedRecord != row._oldRecord)
            {
                record = row._oldRecord;
            }
            DataViewRowState recordState = row.GetRecordState(record);
            DataViewRowState recordState2 = row.GetRecordState(num);
            row._newRecord = proposedRecord;
            if (proposedRecord != -1)
            {
                _recordManager[proposedRecord] = row;
            }
            DataViewRowState recordState3 = row.GetRecordState(record);
            DataViewRowState recordState4 = row.GetRecordState(num);
            RecordStateChanged(record, recordState, recordState3, num, recordState2, recordState4);
        }
        else
        {
            row._newRecord = proposedRecord;
            if (proposedRecord != -1)
            {
                _recordManager[proposedRecord] = row;
            }
        }
        row.ResetLastChangedColumn();
        if (-1 != record && record != row._oldRecord && record != row._tempRecord && record != row._newRecord && row == _recordManager[record])
        {
            FreeRecord(ref record);
        }
        if (row.RowState == DataRowState.Detached && row.rowID != -1)
        {
            RemoveRow(row, check: false);
        }
        if (_dependentColumns != null && _dependentColumns.Count > 0)
        {
            try
            {
                EvaluateExpressions(row, action, list);
            }
            catch (Exception ex)
            {
                if (action != DataRowAction.Add)
                {
                    throw;
                }
                deferredException = ex;
            }
        }
        try
        {
            if (fireEvent)
            {
                RaiseRowChanged(args, row, action);
            }
        }
        catch (Exception e) when (ADP.IsCatchableExceptionType(e))
        {
            ExceptionBuilder.TraceExceptionWithoutRethrow(e);
        }
    }
References System.Data.DataTable._dependentColumns, System.Data.DataTable._inDataLoad, System.Data.DataTable._recordManager, System.action, System.Data.DataRowCollection.ArrayAdd(), System.Data.DataRowCollection.ArrayInsert(), System.Data.DataTable.CheckNotModifying(), System.Data.DataTable.ChildRelations, System.Data.InternalDataCollectionBase.Count, System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Runtime.Serialization.Dictionary, System.Data.DataTable.EvaluateExpressions(), System.Data.DataTable.FreeRecord(), System.Data.Common.ADP.IsCatchableExceptionType(), System.list, System.Data.DataTable.LiveIndexes, System.Data.DataTable.ParentRelations, System.Data.DataTable.RaiseRowChanged(), System.Data.DataTable.RaiseRowChanging(), System.Data.DataTable.RecordStateChanged(), System.Data.DataTable.RemoveRow(), System.Data.DataTable.Rows, and System.Data.ExceptionBuilder.TraceExceptionWithoutRethrow().
Referenced by System.Data.DataTable.InsertRow(), and System.Data.DataTable.SetNewRecord().