Terraria: System.Data.DataTable.NewRecordFromArray
NewRecordFromArray()
int System.Data.DataTable.NewRecordFromArray (object[] value) inline package inherited
Definition at line 3047 of file DataTable.cs.
    {
        int count = _columnCollection.Count;
        if (count < value.Length)
        {
            throw ExceptionBuilder.ValueArrayLength();
        }
        int record = _recordManager.NewRecordBase();
        try
        {
            for (int i = 0; i < value.Length; i++)
            {
                object obj = value[i];
                if (obj != null)
                {
                    _columnCollection[i][record] = obj;
                }
                else
                {
                    _columnCollection[i].Init(record);
                }
            }
            for (int j = value.Length; j < count; j++)
            {
                _columnCollection[j].Init(record);
            }
            return record;
        }
        catch (Exception e) when (ADP.IsCatchableOrSecurityExceptionType(e))
        {
            FreeRecord(ref record);
            throw;
        }
    }
References System.Data.DataTable._columnCollection, System.Data.DataTable._recordManager, System.Data.InternalDataCollectionBase.Count, System.count, System.Runtime.Serialization.Dictionary, System.Data.DataTable.FreeRecord(), System.Data.Common.ADP.IsCatchableOrSecurityExceptionType(), System.Data.RecordManager.NewRecordBase(), System.obj, System.value, and System.Data.ExceptionBuilder.ValueArrayLength().
Referenced by System.Data.DataRowCollection.Add(), System.Data.DataTable.LoadDataRow(), System.Data.DataTable.LoadRow(), and System.Data.DataTable.UpdatingAdd().