Terraria: System.Data.DataTable.SetCaseSensitiveValue
SetCaseSensitiveValue()
bool System.Data.DataTable.SetCaseSensitiveValue (bool isCaseSensitive, bool userSet, bool resetIndexes) inline package inherited
Definition at line 1783 of file DataTable.cs.
    {
        if (userSet || (!_caseSensitiveUserSet && _caseSensitive != isCaseSensitive))
        {
            _caseSensitive = isCaseSensitive;
            if (isCaseSensitive)
            {
                _compareFlags = CompareOptions.None;
            }
            else
            {
                _compareFlags = CompareOptions.IgnoreCase | CompareOptions.IgnoreKanaType | CompareOptions.IgnoreWidth;
            }
            if (resetIndexes)
            {
                ResetIndexes();
                foreach (Constraint constraint in Constraints)
                {
                    constraint.CheckConstraint();
                }
            }
            return true;
        }
        return false;
    }
References System.Data.DataTable._caseSensitive, System.Data.DataTable._caseSensitiveUserSet, System.Data.DataTable._compareFlags, System.Data.Constraint.CheckConstraint(), System.Data.DataTable.Constraints, System.Runtime.Serialization.Dictionary, and System.Data.DataTable.ResetIndexes().
Referenced by System.Data.DataTableCollection.Add(), and System.Data.DataTable.DeserializeTableSchema().