Terraria: System.Data.DataTable.ReadEndElement
ReadEndElement()
void System.Data.DataTable.ReadEndElement (XmlReader reader) inline package inherited
Definition at line 5513 of file DataTable.cs.
    {
        while (reader.NodeType == XmlNodeType.Whitespace)
        {
            reader.Skip();
        }
        if (reader.NodeType == XmlNodeType.None)
        {
            reader.Skip();
        }
        else if (reader.NodeType == XmlNodeType.EndElement)
        {
            reader.ReadEndElement();
        }
    }
References System.Xml.XmlReader.NodeType, System.Xml.XmlReader.ReadEndElement(), and System.Xml.XmlReader.Skip().
Referenced by System.Data.DataTable.ReadXml(), System.Data.DataTable.ReadXml(), System.Data.DataTable.ReadXmlDiffgram(), and System.Data.DataTable.ReadXSDSchema().