Terraria: System.Data.DataTable.LoadRow
LoadRow()
DataRow System.Data.DataTable.LoadRow (object[] values, LoadOption loadOption, Index searchIndex) inline private inherited
Definition at line 4404 of file DataTable.cs.
    {
        DataRow dataRow = null;
        int num2;
        if (searchIndex != null)
        {
            int[] array = Array.Empty<int>();
            if (_primaryKey != null)
            {
                array = new int[_primaryKey.ColumnsReference.Length];
                for (int i = 0; i < _primaryKey.ColumnsReference.Length; i++)
                {
                    array[i] = _primaryKey.ColumnsReference[i].Ordinal;
                }
            }
            object[] array2 = new object[array.Length];
            for (int j = 0; j < array.Length; j++)
            {
                array2[j] = values[array[j]];
            }
            Range range = searchIndex.FindRecords(array2);
            if (!range.IsNull)
            {
                int num = 0;
                for (int k = range.Min; k <= range.Max; k++)
                {
                    int record = searchIndex.GetRecord(k);
                    dataRow = _recordManager[record];
                    num2 = NewRecordFromArray(values);
                    for (int l = 0; l < values.Length; l++)
                    {
                        if (values[l] == null)
{
                            _columnCollection[l].Copy(record, num2);
                        }
                    }
                    for (int m = values.Length; m < _columnCollection.Count; m++)
                    {
                        _columnCollection[m].Copy(record, num2);
                    }
                    if (loadOption != LoadOption.Upsert || dataRow.RowState != DataRowState.Deleted)
                    {
                        SetDataRowWithLoadOption(dataRow, num2, loadOption, checkReadOnly: true);
                    }
                    else
                    {
                        num++;
                    }
                }
                if (num == 0)
                {
                    return dataRow;
                }
            }
        }
        num2 = NewRecordFromArray(values);
        dataRow = NewRow(num2);
        DataRowChangeEventArgs dataRowChangeEventArgs = null;
        DataRowAction eAction;
        switch (loadOption)
        {
        case LoadOption.OverwriteChanges:
        case LoadOption.PreserveChanges:
            eAction = DataRowAction.ChangeCurrentAndOriginal;
            break;
        case LoadOption.Upsert:
            eAction = DataRowAction.Add;
            break;
        default:
            throw ExceptionBuilder.ArgumentOutOfRange("LoadOption");
        }
        dataRowChangeEventArgs = RaiseRowChanging(null, dataRow, eAction);
        InsertRow(dataRow, -1L, -1, fireEvent: false);
        switch (loadOption)
        {
        case LoadOption.OverwriteChanges:
        case LoadOption.PreserveChanges:
            SetOldRecord(dataRow, num2);
            break;
        default:
            throw ExceptionBuilder.ArgumentOutOfRange("LoadOption");
        case LoadOption.Upsert:
            break;
        }
        RaiseRowChanged(dataRowChangeEventArgs, dataRow, eAction);
        return dataRow;
    }
References System.Data.DataTable._columnCollection, System.Data.DataTable._primaryKey, System.Data.DataTable._recordManager, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Data.ExceptionBuilder.ArgumentOutOfRange(), System.array, System.Data.UniqueConstraint.ColumnsReference, System.Data.InternalDataCollectionBase.Count, System.Runtime.Serialization.Dictionary, System.Data.DataTable.InsertRow(), System.L, System.Data.DataTable.NewRecordFromArray(), System.Data.DataTable.NewRow(), System.Data.DataColumn.Ordinal, System.Data.DataTable.RaiseRowChanged(), System.Data.DataTable.RaiseRowChanging(), System.Data.DataTable.SetDataRowWithLoadOption(), System.Data.DataTable.SetOldRecord(), and System.values.
Referenced by System.Data.DataTable.LoadDataRow().