Terraria: System.GC.SuppressFinalize
SuppressFinalize()
static void System.GC.SuppressFinalize (object obj) inline static
Definition at line 202 of file GC.cs.
    {
        if (obj == null)
        {
            throw new ArgumentNullException("obj");
        }
        _SuppressFinalize(obj);
    }
References System.GC._SuppressFinalize(), and System.obj.
Referenced by System.Runtime.Loader.AssemblyLoadContext.AssemblyLoadContext(), System.Data.Common.DataAdapter.DataAdapter(), System.Data.DataColumn.DataColumn(), System.Data.DataSet.DataSet(), System.Data.DataTable.DataTable(), System.Data.DataView.DataView(), System.Data.DataView.DataView(), System.Data.DataView.DataView(), System.Data.DataViewManager.DataViewManager(), System.IO.FileStream.FileStream(), System.LocalDataStoreSlot.LocalDataStoreSlot(), System.Threading.PeriodicTimer.PeriodicTimer(), System.Net.NetworkInformation.Ping.Ping(), System.Diagnostics.Process.Process(), System.Diagnostics.Process.Process(), System.Runtime.InteropServices.SafeHandle.SafeHandle(), System.Threading.Tasks.Dataflow.DataflowBlock.SendAsyncSource< TOutput >.SendAsyncSource(), System.Net.Sockets.Socket.Socket(), System.Net.WebClient.WebClient(), System.ComponentModel.Design.DesignerTransaction.Cancel(), System.Net.ListenerClientCertAsyncResult.Cleanup(), System.Runtime.InteropServices.CriticalHandle.Cleanup(), System.Security.Cryptography.ToBase64Transform.Clear(), System.Security.Cryptography.AsymmetricAlgorithm.Clear(), System.Runtime.CompilerServices.AsyncTaskMethodBuilder< TResult >.AsyncStateMachineBox< TStateMachine >.ClearStateUponCompletion(), System.IO.IsolatedStorage.IsolatedStorageFile.Close(), System.Net.Security.SecureChannel.Close(), System.IO.Stream.Close(), System.IO.StreamWriter.Close(), System.IO.TextReader.Close(), System.IO.TextWriter.Close(), System.Threading.TimerHolder.Close(), System.Threading.TimerHolder.Close(), System.Threading.TimerHolder.CloseAsync(), System.Net.Security.SslStream.CloseInternal(), System.ComponentModel.Design.DesignerTransaction.Commit(), Microsoft.Xna.Framework.Graphics.GraphicsAdapter.CleanupHelper.Dispose(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.Dispose(), Microsoft.Xna.Framework.Graphics.GraphicsResource.Dispose(), Microsoft.Xna.Framework.Graphics.GuideRenderer.Dispose(), Microsoft.Xna.Framework.Graphics.RenderTargetHelper.Dispose(), Microsoft.Xna.Framework.WindowsManagedCallbackHandler.Dispose(), ReLogic.Localization.IME.PlatformIme.Dispose(), ReLogic.OS.Windows.WindowsMessageHook.Dispose(), ReLogic.Peripherals.RGB.RgbDeviceGroup.Dispose(), System.Collections.Concurrent.BlockingCollection< T >.Dispose(), System.ComponentModel.Component.Dispose(), System.ComponentModel.Design.DesignerTransaction.Dispose(), System.ComponentModel.Container.Dispose(), System.ComponentModel.LicFileLicenseProvider.LicFileLicense.Dispose(), System.ComponentModel.MarshalByValueComponent.Dispose(), System.Diagnostics.Activity.Dispose(), System.Diagnostics.TraceListener.Dispose(), System.IO.Compression.Deflater.Dispose(), System.IO.Compression.Inflater.Dispose(), System.IO.Compression.ZipArchive.Dispose(), System.IO.MemoryMappedFiles.MemoryMappedFile.Dispose(), System.IO.MemoryMappedFiles.MemoryMappedView.Dispose(), System.Buffers.MemoryPool< T >.Dispose(), System.Net.Http.HttpConnectionPoolManager.NetworkChangeCleanup.Dispose(), System.Net.Http.HttpContent.Dispose(), System.Net.Http.HttpMessageHandler.Dispose(), System.Net.Http.HttpMessageInvoker.Dispose(), System.Net.Http.HttpRequestMessage.Dispose(), System.Net.Http.HttpResponseMessage.Dispose(), System.Net.Security.SafeCredentialReference.Dispose(), System.Net.WebSockets.WebSocketHttpListenerDuplexStream.HttpListenerAsyncEventArgs.Dispose(), System.Net.RequestContextBase.Dispose(), System.Net.Mail.SmtpClient.Dispose(), System.Net.Quic.Implementations.Mock.MockConnection.Dispose(), System.Net.Quic.Implementations.Mock.MockListener.Dispose(), System.Net.Quic.Implementations.MsQuic.MsQuicConnection.Dispose(), System.Net.Quic.Implementations.MsQuic.MsQuicListener.Dispose(), System.Net.Quic.Implementations.MsQuic.MsQuicStream.Dispose(), System.Net.WebResponse.Dispose(), System.Net.Sockets.Socket.Dispose(), System.Net.Sockets.SocketAsyncEventArgs.Dispose(), System.Buffers.MemoryManager< T >.Dispose(), System.Diagnostics.Tracing.EventProvider.Dispose(), System.Diagnostics.Tracing.EventSource.Dispose(), System.IO.Enumeration.FileSystemEnumerator< TResult >.Dispose(), System.IO.Iterator< TSource >.Dispose(), System.IO.TextReader.Dispose(), System.IO.TextWriter.Dispose(), System.IO.UnmanagedMemoryAccessor.Dispose(), System.Runtime.CompilerServices.ConditionalWeakTable< TKey, TValue >.Enumerator.Dispose(), System.Runtime.InteropServices.PosixSignalRegistration.Dispose(), System.Runtime.InteropServices.SafeHandle.Dispose(), System.Runtime.MemoryFailPoint.Dispose(), System.Threading.Tasks.Task< TResult >.Dispose(), System.Threading.CancellationTokenSource.Dispose(), System.Threading.LowLevelLifoSemaphore.Dispose(), System.Threading.LowLevelLock.Dispose(), System.Threading.ManualResetEventSlim.Dispose(), System.Threading.PeriodicTimer.Dispose(), System.Threading.PreAllocatedOverlapped.Dispose(), System.Threading.SemaphoreSlim.Dispose(), System.Threading.ThreadLocal< T >.Dispose(), System.Threading.WaitHandle.Dispose(), System.Runtime.Serialization.CollectionDataContract.DictionaryEnumerator.Dispose(), System.Runtime.Serialization.CollectionDataContract.GenericDictionaryEnumerator< K, V >.Dispose(), System.Reflection.Internal.CriticalDisposableObject.Dispose(), System.Reflection.Internal.MemoryBlockProvider.Dispose(), System.Security.AccessControl.Privilege.TlsContents.Dispose(), Internal.Cryptography.BasicSymmetricCipher.Dispose(), Internal.Cryptography.HashProvider.Dispose(), Internal.Cryptography.UniversalCryptoTransform.Dispose(), System.Security.Cryptography.DeriveBytes.Dispose(), System.Security.Cryptography.RandomNumberGenerator.Dispose(), System.Security.Cryptography.FromBase64Transform.Dispose(), System.Security.Cryptography.HashAlgorithm.Dispose(), System.Security.Cryptography.SymmetricAlgorithm.Dispose(), System.Security.Cryptography.X509Certificates.X509Chain.Dispose(), System.Threading.Barrier.Dispose(), System.Threading.CountdownEvent.Dispose(), System.Net.Http.HttpConnection.Dispose(), System.Net.Sockets.TcpClient.Dispose(), System.Net.Sockets.UdpClient.Dispose(), System.Transactions.FinalizedObject.Dispose(), System.Net.Security.AuthenticatedStream.DisposeAsync(), System.IO.Strategies.Net5CompatFileStreamStrategy.DisposeAsync(), System.Xml.XmlWriter.DisposeAsync(), System.IO.StreamWriter.DisposeAsyncCore(), System.IO.Strategies.DerivedFileStreamStrategy.DisposeInternal(), Microsoft.Win32.SafeHandles.SafeNCryptHandle.DuplicateOwnerHandle< T >(), System.Net.Http.Http2Connection.FinalTeardown(), System.IO.Pipes.AnonymousPipeServerStream.GetClientHandleAsString(), Microsoft.Win32.SafeHandles.SafeHandleCache< T >.GetInvalidHandle(), System.Threading.Tasks.TaskExceptionHolder.MarkAsHandled(), System.Threading.RegisteredWaitHandle.OnBeforeRegister(), System.ComponentModel.AsyncOperation.OperationCompletedCore(), Microsoft.Xna.Framework.XOverlappedAsyncResult.PrepareForEndFunction(), System.Xml.XmlElementList.PrivateDisposeNodeList(), System.Runtime.InteropServices.ComEventsHelper.Remove(), System.Runtime.CompilerServices.ConditionalWeakTable< TKey, TValue >.Container.Resize(), System.Threading.Tasks.Dataflow.DataflowBlock.SendAsyncSource< TOutput >.RunCompletionAction(), System.Runtime.InteropServices.CriticalHandle.SetHandleAsInvalid(), System.Runtime.InteropServices.SafeHandle.SetHandleAsInvalid(), System.Net.Http.HttpConnectionPoolManager.StartMonitoringNetworkChanges(), System.Runtime.Loader.AssemblyLoadContext.Unload(), and System.Threading.RegisteredWaitHandle.Unregister().