Terraria: System.Data.DataTable.WriteXml
WriteXml() [17/17]
void System.Data.DataTable.WriteXml (XmlWriter? writer, XmlWriteMode mode, bool writeHierarchy) inline inherited
Definition at line 4777 of file DataTable.cs.
    {
        long scopeId = DataCommonEventSource.Log.EnterScope("<ds.DataTable.WriteXml|API> {0}, mode={1}", ObjectID, mode);
        try
        {
            if (_tableName.Length == 0)
            {
                throw ExceptionBuilder.CanNotSerializeDataTableWithEmptyName();
            }
            if (writer == null)
            {
                return;
            }
            switch (mode)
            {
            case XmlWriteMode.DiffGram:
                new NewDiffgramGen(this, writeHierarchy).Save(writer, this);
                break;
            case XmlWriteMode.WriteSchema:
            {
                DataSet dataSet = null;
                string tableNamespace = _tableNamespace;
                if (DataSet == null)
                {
                    dataSet = new DataSet();
                    dataSet.SetLocaleValue(_culture, _cultureUserSet);
                    dataSet.CaseSensitive = CaseSensitive;
                    dataSet.Namespace = Namespace;
                    dataSet.RemotingFormat = RemotingFormat;
                    dataSet.Tables.Add(this);
                }
                if (writer != null)
                {
                    XmlDataTreeWriter xmlDataTreeWriter2 = new XmlDataTreeWriter(this, writeHierarchy);
                    xmlDataTreeWriter2.Save(writer, writeSchema: true);
                }
                if (dataSet != null)
                {
                    dataSet.Tables.Remove(this);
                    _tableNamespace = tableNamespace;
                }
                break;
            }
            default:
            {
                XmlDataTreeWriter xmlDataTreeWriter = new XmlDataTreeWriter(this, writeHierarchy);
                xmlDataTreeWriter.Save(writer, writeSchema: false);
                break;
            }
            }
        }
        finally
        {
            DataCommonEventSource.Log.ExitScope(scopeId);
        }
    }
References System.Data.DataTable._culture, System.Data.DataTable._cultureUserSet, System.Data.DataTable._tableName, System.Data.DataTable._tableNamespace, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Data.ExceptionBuilder.CanNotSerializeDataTableWithEmptyName(), System.Data.DataTable.CaseSensitive, System.Data.DataTable.DataSet, System.Runtime.Serialization.Dictionary, System.Data.DataCommonEventSource.Log, System.Data.DataTable.Namespace, System.Data.DataTable.ObjectID, System.Data.DataTable.RemotingFormat, System.Collections.Generic.Dictionary< TKey, TValue >.Remove(), System.Data.NewDiffgramGen.Save(), and System.writer.