Terraria: System.Data.DataTable.CloneTo
CloneTo()
DataTable System.Data.DataTable.CloneTo (DataTable clone, DataSet cloneDS, bool skipExpressionColumns) inline private inherited
Definition at line 2307 of file DataTable.cs.
    {
        clone._tableName = _tableName;
        clone._tableNamespace = _tableNamespace;
        clone._tablePrefix = _tablePrefix;
        clone._fNestedInDataset = _fNestedInDataset;
        clone._culture = _culture;
        clone._cultureUserSet = _cultureUserSet;
        clone._compareInfo = _compareInfo;
        clone._compareFlags = _compareFlags;
        clone._formatProvider = _formatProvider;
        clone._hashCodeProvider = _hashCodeProvider;
        clone._caseSensitive = _caseSensitive;
        clone._caseSensitiveUserSet = _caseSensitiveUserSet;
        clone._displayExpression = _displayExpression;
        clone._typeName = _typeName;
        clone._repeatableElement = _repeatableElement;
        clone.MinimumCapacity = MinimumCapacity;
        clone.RemotingFormat = RemotingFormat;
        DataColumnCollection columns = Columns;
        for (int i = 0; i < columns.Count; i++)
        {
            clone.Columns.Add(columns[i].Clone());
        }
        if (!skipExpressionColumns && cloneDS == null)
        {
            for (int j = 0; j < columns.Count; j++)
            {
                clone.Columns[columns[j].ColumnName].CopyExpressionFrom(columns[j]);
            }
        }
        DataColumn[] primaryKey = PrimaryKey;
        if (primaryKey.Length != 0)
        {
            DataColumn[] array = new DataColumn[primaryKey.Length];
            for (int k = 0; k < primaryKey.Length; k++)
            {
                array[k] = clone.Columns[primaryKey[k].Ordinal];
            }
            clone.PrimaryKey = array;
        }
        for (int l = 0; l < Constraints.Count; l++)
        {
            ForeignKeyConstraint foreignKeyConstraint = Constraints[l] as ForeignKeyConstraint;
            UniqueConstraint uniqueConstraint = Constraints[l] as UniqueConstraint;
            if (foreignKeyConstraint != null)
            {
                if (foreignKeyConstraint.Table != foreignKeyConstraint.RelatedTable)
                {
                    continue;
                }
                ForeignKeyConstraint foreignKeyConstraint2 = foreignKeyConstraint.Clone(clone);
                if (foreignKeyConstraint2 != null)
                {
                    Constraint constraint = clone.Constraints.FindConstraint(foreignKeyConstraint2);
                    if (constraint != null)
                    {
                        constraint.ConstraintName = Constraints[l].ConstraintName;
                    }
                }
            }
            else
            {
                if (uniqueConstraint == null)
                {
                    continue;
                }
                UniqueConstraint uniqueConstraint2 = uniqueConstraint.Clone(clone);
                if (uniqueConstraint2 == null)
                {
                    continue;
                }
                Constraint constraint2 = clone.Constraints.FindConstraint(uniqueConstraint2);
                if (constraint2 == null)
                {
                    continue;
                }
                constraint2.ConstraintName = Constraints[l].ConstraintName;
                foreach (object key in uniqueConstraint2.ExtendedProperties.Keys)
                {
                    constraint2.ExtendedProperties[key] = uniqueConstraint2.ExtendedProperties[key];
                }
            }
        }
        for (int m = 0; m < Constraints.Count; m++)
        {
            if (clone.Constraints.Contains(Constraints[m].ConstraintName, caseSensitive: true))
            {
                continue;
            }
            ForeignKeyConstraint foreignKeyConstraint3 = Constraints[m] as ForeignKeyConstraint;
            UniqueConstraint uniqueConstraint3 = Constraints[m] as UniqueConstraint;
            if (foreignKeyConstraint3 != null)
            {
                if (foreignKeyConstraint3.Table == foreignKeyConstraint3.RelatedTable)
                {
                    ForeignKeyConstraint foreignKeyConstraint4 = foreignKeyConstraint3.Clone(clone);
                    if (foreignKeyConstraint4 != null)
                    {
                        clone.Constraints.Add(foreignKeyConstraint4);
                    }
                }
            }
            else if (uniqueConstraint3 != null)
            {
                clone.Constraints.Add(uniqueConstraint3.Clone(clone));
            }
        }
        if (_extendedProperties != null)
        {
            foreach (object key2 in _extendedProperties.Keys)
            {
                clone.ExtendedProperties[key2] = _extendedProperties[key2];
            }
        }
        return clone;
    }
References System.Data.DataTable._caseSensitive, System.Data.DataTable._caseSensitiveUserSet, System.Data.DataTable._compareFlags, System.Data.DataTable._compareInfo, System.Data.DataTable._culture, System.Data.DataTable._cultureUserSet, System.Data.DataTable._displayExpression, System.Data.DataTable._extendedProperties, System.Data.DataTable._fNestedInDataset, System.Data.DataTable._formatProvider, System.Data.DataTable._hashCodeProvider, System.Data.DataTable._repeatableElement, System.Data.DataTable._tableName, System.Data.DataTable._tableNamespace, System.Data.DataTable._tablePrefix, System.Data.DataTable._typeName, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.array, System.Data.DataTable.Clone(), System.Data.DataTable.Columns, System.Data.DataTable.Constraints, System.Collections.Generic.Dictionary< TKey, TValue >.Contains(), System.Data.InternalDataCollectionBase.Count, System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Runtime.Serialization.Dictionary, System.key, System.Collections.Generic.Dictionary< TKey, TValue >.Keys, System.Collections.Hashtable.Keys, System.Data.DataTable.MinimumCapacity, System.Data.DataTable.PrimaryKey, and System.Data.DataTable.RemotingFormat.
Referenced by System.Data.DataTable.Clone().