Terraria: System.Data.DataTable.AddDependentColumn
AddDependentColumn()
void System.Data.DataTable.AddDependentColumn (DataColumn expressionColumn) inline package inherited
Definition at line 5943 of file DataTable.cs.
    {
        if (_dependentColumns == null)
        {
            _dependentColumns = new List<DataColumn>();
        }
        if (!_dependentColumns.Contains(expressionColumn))
        {
            _dependentColumns.Add(expressionColumn);
        }
    }
References System.Data.DataTable._dependentColumns, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Collections.Generic.Dictionary< TKey, TValue >.Contains(), and System.Runtime.Serialization.Dictionary.
Referenced by System.Data.DataColumn.AddDependentColumn(), and System.Data.DataColumn.HandleDependentColumnList().