Terraria: System.Data.DataTable.NewRow
NewRow() [2/2]
DataRow System.Data.DataTable.NewRow (int record) inline package inherited
Definition at line 3160 of file DataTable.cs.
    {
        if (-1 == record)
        {
            record = NewRecord(-1);
        }
        _rowBuilder._record = record;
        DataRow dataRow = NewRowFromBuilder(_rowBuilder);
        _recordManager[record] = dataRow;
        _dataSet?.OnDataRowCreated(dataRow);
        return dataRow;
    }
References System.Data.DataTable._dataSet, System.Data.DataTable._recordManager, System.Data.DataTable._rowBuilder, System.Runtime.Serialization.Dictionary, System.Data.DataTable.NewRecord(), System.Data.DataTable.NewRowFromBuilder(), and System.Data.DataSet.OnDataRowCreated().