Terraria: System.Data.DataTable.CloneHierarchy
CloneHierarchy()
DataTable System.Data.DataTable.CloneHierarchy (DataTable sourceTable, DataSet ds, Hashtable visitedMap) inline private inherited
Definition at line 2275 of file DataTable.cs.
    {
        if (visitedMap == null)
        {
            visitedMap = new Hashtable();
        }
        if (visitedMap.Contains(sourceTable))
        {
            return (DataTable)visitedMap[sourceTable];
        }
        DataTable dataTable = ds.Tables[sourceTable.TableName, sourceTable.Namespace];
        if (dataTable != null && dataTable.Columns.Count > 0)
        {
            dataTable = IncrementalCloneTo(sourceTable, dataTable);
        }
        else
        {
            if (dataTable == null)
            {
                dataTable = new DataTable();
                ds.Tables.Add(dataTable);
            }
            dataTable = sourceTable.CloneTo(dataTable, ds, skipExpressionColumns: true);
        }
        visitedMap[sourceTable] = dataTable;
        foreach (DataRelation childRelation in sourceTable.ChildRelations)
        {
            CloneHierarchy(childRelation.ChildTable, ds, visitedMap);
        }
        return dataTable;
    }
References System.Data.DataTable.DataTable(), System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Data.DataTable.CloneHierarchy(), System.Collections.Generic.Dictionary< TKey, TValue >.Contains(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Runtime.Serialization.Dictionary, and System.Data.DataTable.IncrementalCloneTo().
Referenced by System.Data.DataTable.CloneHierarchy(), and System.Data.DataTable.ReadXmlSchema().