Terraria: System.GC.StartNoGCRegionWorker
StartNoGCRegionWorker()
static bool System.GC.StartNoGCRegionWorker (long totalSize, bool hasLohSize, long lohSize, bool disallowFullBlockingGC) inline static private
Definition at line 321 of file GC.cs.
    {
        if (totalSize <= 0)
        {
            throw new ArgumentOutOfRangeException("totalSize", "totalSize can't be zero or negative");
        }
        if (hasLohSize)
        {
            if (lohSize <= 0)
            {
                throw new ArgumentOutOfRangeException("lohSize", "lohSize can't be zero or negative");
            }
            if (lohSize > totalSize)
            {
                throw new ArgumentOutOfRangeException("lohSize", "lohSize can't be greater than totalSize");
            }
        }
        return (StartNoGCRegionStatus)_StartNoGCRegion(totalSize, hasLohSize, lohSize, disallowFullBlockingGC) switch
        {
            StartNoGCRegionStatus.NotEnoughMemory => false,
            StartNoGCRegionStatus.AlreadyInProgress => throw new InvalidOperationException("The NoGCRegion mode was already in progress"),
            StartNoGCRegionStatus.AmountTooLarge => throw new ArgumentOutOfRangeException("totalSize", "totalSize is too large. For more information about setting the maximum size, see \"Latency Modes\" in https://go.microsoft.com/fwlink/?LinkId=522706"),
            _ => true,
        };
    }
References System.GC._StartNoGCRegion().
Referenced by System.GC.TryStartNoGCRegion(), System.GC.TryStartNoGCRegion(), System.GC.TryStartNoGCRegion(), and System.GC.TryStartNoGCRegion().