Terraria: System.GC.CollectionCount
CollectionCount()
static int System.GC.CollectionCount (int generation) inline static
Definition at line 169 of file GC.cs.
    {
        if (generation < 0)
        {
            throw new ArgumentOutOfRangeException("generation", SR.ArgumentOutOfRange_GenericPositive);
        }
        return _CollectionCount(generation, 0);
    }
References System.GC._CollectionCount(), and System.SR.ArgumentOutOfRange_GenericPositive.
Referenced by System.Diagnostics.Switch._pruneCachedSwitches(), System.Diagnostics.TraceSource._pruneCachedTraceSources(), System.Runtime.InteropServices.HandleCollector.Add(), System.Diagnostics.Tracing.RuntimeEventSource.OnEventCommand(), and System.Runtime.InteropServices.HandleCollector.Remove().