Terraria: System.Data.DataTable.RemoveRow
RemoveRow()
void System.Data.DataTable.RemoveRow (DataRow row, bool check) inline package inherited
Definition at line 3573 of file DataTable.cs.
    {
        if (row.rowID == -1)
        {
            throw ExceptionBuilder.RowAlreadyRemoved();
        }
        if (check && _dataSet != null)
        {
            ParentForeignKeyConstraintEnumerator parentForeignKeyConstraintEnumerator = new ParentForeignKeyConstraintEnumerator(_dataSet, this);
            while (parentForeignKeyConstraintEnumerator.GetNext())
            {
                parentForeignKeyConstraintEnumerator.GetForeignKeyConstraint().CheckCanRemoveParentRow(row);
            }
        }
        int record = row._oldRecord;
        int record2 = row._newRecord;
        DataViewRowState recordState = row.GetRecordState(record);
        DataViewRowState recordState2 = row.GetRecordState(record2);
        row._oldRecord = -1;
        row._newRecord = -1;
        if (record == record2)
        {
            record = -1;
        }
        RecordStateChanged(record, recordState, DataViewRowState.None, record2, recordState2, DataViewRowState.None);
        FreeRecord(ref record);
        FreeRecord(ref record2);
        row.rowID = -1L;
        Rows.ArrayRemove(row);
    }
References System.Data.DataTable._dataSet, System.Data.DataRowCollection.ArrayRemove(), System.Runtime.Serialization.Dictionary, System.Data.DataTable.FreeRecord(), System.L, System.Data.DataTable.RecordStateChanged(), System.Data.ExceptionBuilder.RowAlreadyRemoved(), and System.Data.DataTable.Rows.
Referenced by System.Data.DataTable.SetNewRecordWorker(), and System.Data.DataTable.SetOldRecord().