Terraria: System.Data.DataTable.NewRowArray
NewRowArray()
DataRow[] System.Data.DataTable.NewRowArray (int size) inline package inherited
Definition at line 3184 of file DataTable.cs.
    {
        if (IsTypedDataTable)
        {
            if (size == 0)
            {
                if (_emptyDataRowArray == null)
                {
                    _emptyDataRowArray = (DataRow[])Array.CreateInstance(GetRowType(), 0);
                }
                return _emptyDataRowArray;
            }
            return (DataRow[])Array.CreateInstance(GetRowType(), size);
        }
        if (size != 0)
        {
            return new DataRow[size];
        }
        return Array.Empty<DataRow>();
    }
References System.Data.DataTable._emptyDataRowArray, System.Array.CreateInstance(), System.Data.DataTable.GetRowType(), and System.Data.DataTable.IsTypedDataTable.
Referenced by System.Data.DataRow.GetChildRows(), System.Data.DataTable.GetErrors(), System.Data.Select.GetLinearFilteredRows(), System.Data.DataRow.GetParentRows(), System.Data.Select.GetRows(), System.Data.Index.GetRows(), System.Data.RecordManager.GrowRecordCapacity(), and System.Data.Select.SelectRows().