Terraria: System.Data.DataTable.ReadXmlDiffgram
ReadXmlDiffgram()
void System.Data.DataTable.ReadXmlDiffgram (XmlReader reader) inline private inherited
Definition at line 5545 of file DataTable.cs.
    {
        int depth = reader.Depth;
        bool enforceConstraints = EnforceConstraints;
        EnforceConstraints = false;
        bool flag;
        DataTable dataTable;
        if (Rows.Count == 0)
        {
            flag = true;
            dataTable = this;
        }
        else
        {
            flag = false;
            dataTable = Clone();
            dataTable.EnforceConstraints = false;
        }
        dataTable.Rows._nullInList = 0;
        reader.MoveToContent();
        if (reader.LocalName != "diffgram" && reader.NamespaceURI != "urn:schemas-microsoft-com:xml-diffgram-v1")
        {
            return;
        }
        reader.Read();
        if (reader.NodeType == XmlNodeType.Whitespace)
        {
            MoveToElement(reader, reader.Depth - 1);
        }
        dataTable._fInLoadDiffgram = true;
        if (reader.Depth > depth)
        {
            if (reader.NamespaceURI != "urn:schemas-microsoft-com:xml-diffgram-v1" && reader.NamespaceURI != "urn:schemas-microsoft-com:xml-msdata")
            {
                XmlDocument xmlDocument = new XmlDocument();
                XmlElement topNode = xmlDocument.CreateElement(reader.Prefix, reader.LocalName, reader.NamespaceURI);
                reader.Read();
                if (reader.Depth - 1 > depth)
                {
                    XmlDataLoader xmlDataLoader = new XmlDataLoader(dataTable, IsXdr: false, topNode, ignoreSchema: false);
                    xmlDataLoader._isDiffgram = true;
                    xmlDataLoader.LoadData(reader);
                }
                ReadEndElement(reader);
            }
            if ((reader.LocalName == "before" && reader.NamespaceURI == "urn:schemas-microsoft-com:xml-diffgram-v1") || (reader.LocalName == "errors" && reader.NamespaceURI == "urn:schemas-microsoft-com:xml-diffgram-v1"))
            {
                XMLDiffLoader xMLDiffLoader = new XMLDiffLoader();
                xMLDiffLoader.LoadDiffGram(dataTable, reader);
            }
            while (reader.Depth > depth)
            {
                reader.Read();
            }
            ReadEndElement(reader);
        }
        if (dataTable.Rows._nullInList > 0)
        {
            throw ExceptionBuilder.RowInsertMissing(dataTable.TableName);
        }
        dataTable._fInLoadDiffgram = false;
        List<DataTable> list = new List<DataTable>();
        list.Add(this);
        CreateTableList(this, list);
        for (int i = 0; i < list.Count; i++)
        {
            DataRelation[] nestedParentRelations = list[i].NestedParentRelations;
            DataRelation[] array = nestedParentRelations;
            foreach (DataRelation dataRelation in array)
            {
                if (dataRelation == null || dataRelation.ParentTable != list[i])
                {
                    continue;
                }
                foreach (DataRow row in list[i].Rows)
                {
                    DataRelation[] array2 = nestedParentRelations;
                    foreach (DataRelation rel in array2)
                    {
                        row.CheckForLoops(rel);
                    }
                }
            }
        }
        if (!flag)
        {
            Merge(dataTable);
        }
        EnforceConstraints = enforceConstraints;
    }
References System.array, System.Data.DataTable.Clone(), System.Data.DataRowCollection.Count, System.Data.DataTable.CreateTableList(), System.Xml.XmlReader.Depth, System.Runtime.Serialization.Dictionary, System.Data.DataTable.EnforceConstraints, System.list, System.Xml.XmlReader.LocalName, System.Data.DataTable.Merge(), System.Xml.XmlReader.MoveToContent(), System.Data.DataTable.MoveToElement(), System.Xml.XmlReader.NamespaceURI, System.Xml.XmlReader.NodeType, System.Xml.XmlReader.Prefix, System.Xml.XmlReader.Read(), System.Data.DataTable.ReadEndElement(), System.Data.ExceptionBuilder.RowInsertMissing(), and System.Data.DataTable.Rows.
Referenced by System.Data.DataTable.ReadXml(), and System.Data.DataTable.ReadXml().