Terraria: Terraria.Audio.MusicCueHolder.SetVolume
SetVolume()
void Terraria.Audio.MusicCueHolder.SetVolume (float volume) inline
Definition at line 126 of file MusicCueHolder.cs.
    {
        _lastSetVolume = volume;
        if (_loadedCue != null)
        {
            _loadedCue.SetVariable("Volume", _lastSetVolume);
        }
    }
References Terraria.Audio.MusicCueHolder._lastSetVolume, and Terraria.Audio.MusicCueHolder._loadedCue.
Referenced by Terraria.Audio.MusicCueHolder.Play(), Terraria.Audio.MusicCueHolder.Stop(), and Terraria.Audio.MusicCueHolder.TryPlaying().