Terraria: System.Text.Json.Nodes.JsonNode.AssignParent
AssignParent()
void System.Text.Json.Nodes.JsonNode.AssignParent (JsonNode parent) inline package inherited
Definition at line 133 of file JsonNode.cs.
    {
        if (Parent != null)
        {
            ThrowHelper.ThrowInvalidOperationException_NodeAlreadyHasParent();
        }
        for (JsonNode jsonNode = parent; jsonNode != null; jsonNode = jsonNode.Parent)
        {
            if (jsonNode == this)
            {
                ThrowHelper.ThrowInvalidOperationException_NodeCycleDetected();
            }
        }
        Parent = parent;
    }
References System.Text.Json.Nodes.JsonNode.Parent, System.Text.Json.ThrowHelper.ThrowInvalidOperationException_NodeAlreadyHasParent(), and System.Text.Json.ThrowHelper.ThrowInvalidOperationException_NodeCycleDetected().
Referenced by System.Text.Json.Nodes.JsonArray.InitializeFromArray().