Terraria: System.Runtime.Serialization.Formatters.Binary.BinaryTypeConverter.ReadTypeInfo
ReadTypeInfo()
static object System.Runtime.Serialization.Formatters.Binary.BinaryTypeConverter.ReadTypeInfo (BinaryTypeEnum binaryTypeEnum, BinaryParser input, out int assemId) inline static package
Definition at line 138 of file BinaryTypeConverter.cs.
    {
        object result = null;
        int num = 0;
        switch (binaryTypeEnum)
        {
        case BinaryTypeEnum.Primitive:
        case BinaryTypeEnum.PrimitiveArray:
            result = (InternalPrimitiveTypeE)input.ReadByte();
            break;
        case BinaryTypeEnum.ObjectUrt:
            result = input.ReadString();
            break;
        case BinaryTypeEnum.ObjectUser:
            result = input.ReadString();
            num = input.ReadInt32();
            break;
        default:
            throw new SerializationException(System.SR.Format(System.SR.Serialization_TypeRead, binaryTypeEnum.ToString()));
        case BinaryTypeEnum.String:
        case BinaryTypeEnum.Object:
        case BinaryTypeEnum.ObjectArray:
        case BinaryTypeEnum.StringArray:
            break;
        }
        assemId = num;
        return result;
    }
References System.Runtime.Serialization.Dictionary, System.SR.Format(), System.input, and System.SR.Serialization_TypeRead.
Referenced by System.Runtime.Serialization.Formatters.Binary.BinaryArray.Read(), and System.Runtime.Serialization.Formatters.Binary.BinaryObjectWithMapTyped.Read().