Terraria: System.Xml.XmlBaseWriter.NamespaceManager.AddNamespaceIfNotDeclared
AddNamespaceIfNotDeclared()
void System.Xml.XmlBaseWriter.NamespaceManager.AddNamespaceIfNotDeclared (string prefix, string uri, XmlDictionaryString uriDictionaryString) inline
Definition at line 402 of file XmlBaseWriter.cs.
        {
            if (LookupNamespace(prefix) != uri)
            {
                AddNamespace(prefix, uri, uriDictionaryString);
            }
        }
References System.Xml.XmlBaseWriter.NamespaceManager.AddNamespace(), System.Xml.Dictionary, System.Xml.XmlBaseWriter.NamespaceManager.LookupNamespace(), and System.prefix.
Referenced by System.Xml.XmlBaseWriter.NamespaceManager.AddNamespace(), System.Xml.XmlBaseWriter.StartAttribute(), System.Xml.XmlBaseWriter.StartElement(), System.Xml.XmlBaseWriter.StartElementAsync(), System.Xml.XmlBaseWriter.WriteEndAttribute(), System.Xml.XmlBaseWriter.WriteEndAttributeAsyncImpl(), System.Xml.XmlBaseWriter.WriteXmlnsAttribute(), and System.Xml.XmlBaseWriter.WriteXmlnsAttribute().