Terraria: System.Runtime.Serialization.Formatters.Binary.BinaryTypeConverter.WriteTypeInfo
WriteTypeInfo()
static void System.Runtime.Serialization.Formatters.Binary.BinaryTypeConverter.WriteTypeInfo (BinaryTypeEnum binaryTypeEnum, object typeInformation, int assemId, BinaryFormatterWriter output) inline static package
Definition at line 113 of file BinaryTypeConverter.cs.
    {
        switch (binaryTypeEnum)
        {
        case BinaryTypeEnum.Primitive:
        case BinaryTypeEnum.PrimitiveArray:
            output.WriteByte((byte)(InternalPrimitiveTypeE)typeInformation);
            break;
        case BinaryTypeEnum.ObjectUrt:
            output.WriteString(typeInformation.ToString());
            break;
        case BinaryTypeEnum.ObjectUser:
            output.WriteString(typeInformation.ToString());
            output.WriteInt32(assemId);
            break;
        default:
            throw new SerializationException(System.SR.Format(System.SR.Serialization_TypeWrite, binaryTypeEnum.ToString()));
        case BinaryTypeEnum.String:
        case BinaryTypeEnum.Object:
        case BinaryTypeEnum.ObjectArray:
        case BinaryTypeEnum.StringArray:
            break;
        }
    }
References System.Runtime.Serialization.Dictionary, System.SR.Format(), and System.SR.Serialization_TypeWrite.
Referenced by System.Runtime.Serialization.Formatters.Binary.BinaryArray.Write(), and System.Runtime.Serialization.Formatters.Binary.BinaryObjectWithMapTyped.Write().