Terraria: System.Runtime.Serialization.Formatters.Binary.BinaryTypeConverter.GetParserBinaryTypeInfo
GetParserBinaryTypeInfo()
static BinaryTypeEnum System.Runtime.Serialization.Formatters.Binary.BinaryTypeConverter.GetParserBinaryTypeInfo (Type type, out object typeInformation) inline static package
Definition at line 72 of file BinaryTypeConverter.cs.
    {
        typeInformation = null;
        BinaryTypeEnum result;
        if ((object)type == Converter.s_typeofString)
        {
            result = BinaryTypeEnum.String;
        }
        else if ((object)type == Converter.s_typeofObject)
        {
            result = BinaryTypeEnum.Object;
        }
        else if ((object)type == Converter.s_typeofObjectArray)
        {
            result = BinaryTypeEnum.ObjectArray;
        }
        else if ((object)type == Converter.s_typeofStringArray)
        {
            result = BinaryTypeEnum.StringArray;
        }
        else if (Converter.IsPrimitiveArray(type, out typeInformation))
        {
            result = BinaryTypeEnum.PrimitiveArray;
        }
        else
        {
            InternalPrimitiveTypeE internalPrimitiveTypeE = Converter.ToCode(type);
            if (internalPrimitiveTypeE == InternalPrimitiveTypeE.Invalid)
            {
                result = ((type.Assembly == Converter.s_urtAssembly) ? BinaryTypeEnum.ObjectUrt : BinaryTypeEnum.ObjectUser);
                typeInformation = type.FullName;
            }
            else
            {
                result = BinaryTypeEnum.Primitive;
                typeInformation = internalPrimitiveTypeE;
            }
        }
        return result;
    }
References System.Runtime.Serialization.Dictionary, System.Runtime.Serialization.Formatters.Binary.Converter.IsPrimitiveArray(), System.Runtime.Serialization.Formatters.Binary.Converter.s_typeofObject, System.Runtime.Serialization.Formatters.Binary.Converter.s_typeofObjectArray, System.Runtime.Serialization.Formatters.Binary.Converter.s_typeofString, System.Runtime.Serialization.Formatters.Binary.Converter.s_typeofStringArray, System.Runtime.Serialization.Formatters.Binary.Converter.s_urtAssembly, System.Runtime.Serialization.Formatters.Binary.Converter.ToCode(), and System.type.
Referenced by System.Runtime.Serialization.Formatters.Binary.ObjectMap.ObjectMap().