Terraria: System.Xml.XmlBaseWriter.NamespaceManager.AddNamespace
AddNamespace() [1/2]
void System.Xml.XmlBaseWriter.NamespaceManager.AddNamespace (string prefix, string uri, XmlDictionaryString uriDictionaryString) inline
Definition at line 410 of file XmlBaseWriter.cs.
        {
            if (prefix.Length >= 3 && (prefix[0] & -33) == 88 && (prefix[1] & -33) == 77 && (prefix[2] & -33) == 76)
            {
                if ((!(prefix == "xml") || !(uri == "http://www.w3.org/XML/1998/namespace")) && (!(prefix == "xmlns") || !(uri == "http://www.w3.org/2000/xmlns/")))
                {
                    throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new ArgumentException(System.SR.XmlReservedPrefix, "prefix"));
                }
                return;
            }
            Namespace @namespace;
            for (int num = _nsCount - 1; num >= 0; num--)
            {
                @namespace = _namespaces[num];
                if (@namespace.Depth != _depth)
                {
                    break;
                }
                if (@namespace.Prefix == prefix)
                {
                    if (@namespace.Uri == uri)
                    {
                        return;
                    }
                    throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new ArgumentException(System.SR.Format(System.SR.XmlPrefixBoundToNamespace, prefix, @namespace.Uri, uri), "prefix"));
                }
            }
            if (prefix.Length != 0 && uri.Length == 0)
            {
                throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new ArgumentException(System.SR.XmlEmptyNamespaceRequiresNullPrefix, "prefix"));
            }
            if (uri.Length == "http://www.w3.org/2000/xmlns/".Length && uri == "http://www.w3.org/2000/xmlns/")
            {
                throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new ArgumentException(System.SR.Format(System.SR.XmlSpecificBindingNamespace, "xmlns", uri)));
            }
            if (uri.Length == "http://www.w3.org/XML/1998/namespace".Length && uri[18] == 'X' && uri == "http://www.w3.org/XML/1998/namespace")
            {
                throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new ArgumentException(System.SR.Format(System.SR.XmlSpecificBindingNamespace, "xml", uri)));
            }
            if (_namespaces.Length == _nsCount)
            {
                Namespace[] array = new Namespace[_nsCount * 2];
                Array.Copy(_namespaces, array, _nsCount);
                _namespaces = array;
            }
            @namespace = _namespaces[_nsCount];
            if (@namespace == null)
            {
                @namespace = new Namespace();
                _namespaces[_nsCount] = @namespace;
            }
            @namespace.Depth = _depth;
            @namespace.Prefix = prefix;
            @namespace.Uri = uri;
            @namespace.UriDictionaryString = uriDictionaryString;
            _nsCount++;
            _lastNameSpace = null;
        }
References System.Xml.XmlBaseWriter.NamespaceManager._depth, System.Xml.XmlBaseWriter.NamespaceManager._lastNameSpace, System.Xml.XmlBaseWriter.NamespaceManager._namespaces, System.Xml.XmlBaseWriter.NamespaceManager._nsCount, System.Xml.ArgumentException, System.array, System.Array.Copy(), System.Xml.Dictionary, System.SR.Format(), System.prefix, System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperError(), System.SR.XmlEmptyNamespaceRequiresNullPrefix, System.SR.XmlPrefixBoundToNamespace, System.SR.XmlReservedPrefix, and System.SR.XmlSpecificBindingNamespace.