Terraria: System.Runtime.Serialization.Formatters.Binary.BinaryTypeConverter.GetBinaryTypeInfo
GetBinaryTypeInfo()
static BinaryTypeEnum System.Runtime.Serialization.Formatters.Binary.BinaryTypeConverter.GetBinaryTypeInfo (Type type, WriteObjectInfo objectInfo, string typeName, ObjectWriter objectWriter, out object typeInformation, out int assemId) inline static package
Definition at line 7 of file BinaryTypeConverter.cs.
    {
        assemId = 0;
        typeInformation = null;
        BinaryTypeEnum result;
        if ((object)type == Converter.s_typeofString)
        {
            result = BinaryTypeEnum.String;
        }
        else if ((objectInfo == null || (objectInfo != null && !objectInfo._isSi)) && (object)type == Converter.s_typeofObject)
        {
            result = BinaryTypeEnum.Object;
        }
        else if ((object)type == Converter.s_typeofStringArray)
        {
            result = BinaryTypeEnum.StringArray;
        }
        else if ((object)type == Converter.s_typeofObjectArray)
        {
            result = BinaryTypeEnum.ObjectArray;
        }
        else if (Converter.IsPrimitiveArray(type, out typeInformation))
        {
            result = BinaryTypeEnum.PrimitiveArray;
        }
        else
        {
            InternalPrimitiveTypeE internalPrimitiveTypeE = objectWriter.ToCode(type);
            if (internalPrimitiveTypeE == InternalPrimitiveTypeE.Invalid)
            {
                string text = null;
                if (objectInfo == null)
                {
                    text = type.Assembly.FullName;
                    typeInformation = type.FullName;
                }
                else
                {
                    text = objectInfo.GetAssemblyString();
                    typeInformation = objectInfo.GetTypeFullName();
                }
                if (text.Equals(Converter.s_urtAssemblyString) || text.Equals(Converter.s_urtAlternativeAssemblyString))
                {
                    result = BinaryTypeEnum.ObjectUrt;
                    assemId = 0;
                }
                else
                {
                    result = BinaryTypeEnum.ObjectUser;
                    assemId = (int)objectInfo._assemId;
                    if (assemId == 0)
                    {
                        throw new SerializationException(System.SR.Format(System.SR.Serialization_AssemblyId, typeInformation));
                    }
                }
            }
            else
            {
                result = BinaryTypeEnum.Primitive;
                typeInformation = internalPrimitiveTypeE;
            }
        }
        return result;
    }
References System.Runtime.Serialization.Dictionary, System.SR.Format(), System.Runtime.Serialization.Formatters.Binary.Converter.IsPrimitiveArray(), System.Runtime.Serialization.Formatters.Binary.Converter.s_typeofObject, System.Runtime.Serialization.Formatters.Binary.Converter.s_typeofObjectArray, System.Runtime.Serialization.Formatters.Binary.Converter.s_typeofString, System.Runtime.Serialization.Formatters.Binary.Converter.s_typeofStringArray, System.Runtime.Serialization.Formatters.Binary.Converter.s_urtAlternativeAssemblyString, System.Runtime.Serialization.Formatters.Binary.Converter.s_urtAssemblyString, System.SR.Serialization_AssemblyId, System.text, and System.type.
Referenced by System.Runtime.Serialization.Formatters.Binary.BinaryFormatterWriter.WriteJaggedArray(), System.Runtime.Serialization.Formatters.Binary.BinaryFormatterWriter.WriteObject(), System.Runtime.Serialization.Formatters.Binary.BinaryFormatterWriter.WriteRectangleArray(), and System.Runtime.Serialization.Formatters.Binary.BinaryFormatterWriter.WriteSingleArray().