Terraria: System.Xml.XmlBaseWriter.NamespaceManager.DeclareNamespaces
DeclareNamespaces()
void System.Xml.XmlBaseWriter.NamespaceManager.DeclareNamespaces (XmlNodeWriter writer) inline
Definition at line 276 of file XmlBaseWriter.cs.
        {
            int i;
            for (i = _nsCount; i > 0; i--)
            {
                Namespace @namespace = _namespaces[i - 1];
                if (@namespace.Depth != _depth)
                {
                    break;
                }
            }
            for (; i < _nsCount; i++)
            {
                Namespace namespace2 = _namespaces[i];
                if (namespace2.UriDictionaryString != null)
                {
                    writer.WriteXmlnsAttribute(namespace2.Prefix, namespace2.UriDictionaryString);
                }
                else
                {
                    writer.WriteXmlnsAttribute(namespace2.Prefix, namespace2.Uri);
                }
            }
        }
References System.Xml.XmlBaseWriter.NamespaceManager._depth, System.Xml.XmlBaseWriter.NamespaceManager._namespaces, System.Xml.XmlBaseWriter.NamespaceManager._nsCount, System.Xml.Dictionary, and System.writer.
Referenced by System.Xml.XmlBaseWriter.EndStartElement(), System.Xml.XmlBaseWriter.EndStartElementAsync(), System.Xml.XmlBaseWriter.WriteEndElement(), and System.Xml.XmlBaseWriter.WriteEndElementAsyncImpl().