Terraria: System.Xml.XmlBaseWriter.NamespaceManager.AddNamespace
AddNamespace() [2/2]
string System.Xml.XmlBaseWriter.NamespaceManager.AddNamespace (string uri, XmlDictionaryString uriDictionaryString) inline
Definition at line 373 of file XmlBaseWriter.cs.
        {
            if (uri.Length == 0)
            {
                AddNamespaceIfNotDeclared(string.Empty, uri, uriDictionaryString);
                return string.Empty;
            }
            for (int i = 0; i < s_prefixes.Length; i++)
            {
                string text = s_prefixes[i];
                bool flag = false;
                for (int num = _nsCount - 1; num >= _nsTop; num--)
                {
                    Namespace @namespace = _namespaces[num];
                    if (@namespace.Prefix == text)
                    {
                        flag = true;
                        break;
                    }
                }
                if (!flag)
                {
                    AddNamespace(text, uri, uriDictionaryString);
                    return text;
                }
            }
            return null;
        }
References System.Xml.XmlBaseWriter.NamespaceManager._namespaces, System.Xml.XmlBaseWriter.NamespaceManager._nsCount, System.Xml.XmlBaseWriter.NamespaceManager._nsTop, System.Xml.XmlBaseWriter.NamespaceManager.AddNamespace(), System.Xml.XmlBaseWriter.NamespaceManager.AddNamespaceIfNotDeclared(), System.Xml.Dictionary, System.Xml.XmlBaseWriter.s_prefixes, and System.text.
Referenced by System.Xml.XmlBaseWriter.NamespaceManager.AddNamespace(), System.Xml.XmlBaseWriter.NamespaceManager.AddNamespaceIfNotDeclared(), System.Xml.XmlBaseWriter.GeneratePrefix(), System.Xml.XmlBaseWriter.StartElement(), and System.Xml.XmlBaseWriter.StartElementAsync().