Terraria: System.Runtime.Serialization.Formatters.Binary.BinaryTypeConverter.TypeFromInfo
TypeFromInfo()
static void System.Runtime.Serialization.Formatters.Binary.BinaryTypeConverter.TypeFromInfo (BinaryTypeEnum binaryTypeEnum, object typeInformation, ObjectReader objectReader, BinaryAssemblyInfo assemblyInfo, out InternalPrimitiveTypeE primitiveTypeEnum, out string typeString, out Type type, out bool isVariant) inline static package
Definition at line 168 of file BinaryTypeConverter.cs.
    {
        isVariant = false;
        primitiveTypeEnum = InternalPrimitiveTypeE.Invalid;
        typeString = null;
        type = null;
        switch (binaryTypeEnum)
        {
        case BinaryTypeEnum.Primitive:
            primitiveTypeEnum = (InternalPrimitiveTypeE)typeInformation;
            typeString = Converter.ToComType(primitiveTypeEnum);
            type = Converter.ToType(primitiveTypeEnum);
            break;
        case BinaryTypeEnum.String:
            type = Converter.s_typeofString;
            break;
        case BinaryTypeEnum.Object:
            type = Converter.s_typeofObject;
            isVariant = true;
            break;
        case BinaryTypeEnum.ObjectArray:
            type = Converter.s_typeofObjectArray;
            break;
        case BinaryTypeEnum.StringArray:
            type = Converter.s_typeofStringArray;
            break;
        case BinaryTypeEnum.PrimitiveArray:
            primitiveTypeEnum = (InternalPrimitiveTypeE)typeInformation;
            type = Converter.ToArrayType(primitiveTypeEnum);
            break;
        case BinaryTypeEnum.ObjectUrt:
        case BinaryTypeEnum.ObjectUser:
            if (typeInformation != null)
            {
                typeString = typeInformation.ToString();
                type = objectReader.GetType(assemblyInfo, typeString);
                if ((object)type == Converter.s_typeofObject)
                {
                    isVariant = true;
                }
            }
            break;
        default:
            throw new SerializationException(System.SR.Format(System.SR.Serialization_TypeRead, binaryTypeEnum.ToString()));
        }
    }
References System.Runtime.Serialization.Dictionary, System.SR.Format(), System.Runtime.Serialization.Formatters.Binary.Converter.s_typeofObject, System.Runtime.Serialization.Formatters.Binary.Converter.s_typeofObjectArray, System.Runtime.Serialization.Formatters.Binary.Converter.s_typeofString, System.Runtime.Serialization.Formatters.Binary.Converter.s_typeofStringArray, System.SR.Serialization_TypeRead, System.Runtime.Serialization.Formatters.Binary.Converter.ToArrayType(), System.Runtime.Serialization.Formatters.Binary.Converter.ToComType(), System.Runtime.Serialization.Formatters.Binary.Converter.ToType(), and System.type.
Referenced by System.Runtime.Serialization.Formatters.Binary.ObjectMap.ObjectMap(), and System.Runtime.Serialization.Formatters.Binary.BinaryParser.ReadArray().