Terraria: AmbientSky.EOCSkyEntity.EOCSkyEntity
EOCSkyEntity()
AmbientSky.EOCSkyEntity.EOCSkyEntity (Player player, FastRandom random) inline
         {
             VirtualCamera camera = new VirtualCamera(player);
             Texture = Main.Assets.Request<Texture2D>("Images/Backgrounds/Ambience/EOC", (AssetRequestMode)1);
             Frame = new SpriteFrame(1, 3);
             Depth = random.NextFloat() * 3f + 4.5f;
             if (random.Next(4) != 0)
             {
                 BeginZigZag(ref random, camera, (random.Next(2) == 1) ? 1 : (-1));
             }
             else
             {
                 BeginChasingPlayer(ref random, camera);
             }
             SetPositionInWorldBasedOnScreenSpace(Position);
             OpacityNormalizedTimeToFadeIn = 0.1f;
             OpacityNormalizedTimeToFadeOut = 0.9f;
             BrightnessLerper = 0.2f;
             FinalOpacityMultiplier = 1f;
             FramingSpeed = 5;
         }
References Main.Assets, AmbientSky.EOCSkyEntity.BeginChasingPlayer(), AmbientSky.EOCSkyEntity.BeginZigZag(), AmbientSky.FadingSkyEntity.BrightnessLerper, AmbientSky.SkyEntity.Depth, AmbientSky.FadingSkyEntity.FinalOpacityMultiplier, AmbientSky.SkyEntity.Frame, AmbientSky.FadingSkyEntity.FramingSpeed, FastRandom.Next(), FastRandom.NextFloat(), AmbientSky.FadingSkyEntity.OpacityNormalizedTimeToFadeIn, AmbientSky.FadingSkyEntity.OpacityNormalizedTimeToFadeOut, AmbientSky.SkyEntity.Position, AmbientSky.SkyEntity.SetPositionInWorldBasedOnScreenSpace(), and AmbientSky.SkyEntity.Texture.