Terraria: System.Xml.Xsl.Xslt.Compiler.AddModule
AddModule()
void System.Xml.Xsl.Xslt.Compiler.AddModule (string baseUri) inline
Definition at line 153 of file Compiler.cs.
    {
        if (!_moduleOrder.ContainsKey(baseUri))
        {
            _moduleOrder[baseUri] = _moduleOrder.Count;
        }
    }
References System.Xml.Xsl.Xslt.Compiler._moduleOrder, System.Collections.Generic.Dictionary< TKey, TValue >.ContainsKey(), and System.Collections.Generic.Dictionary< TKey, TValue >.Count.
Referenced by System.Xml.Xsl.Xslt.Compiler.CreateError(), and System.Xml.Xsl.Xslt.XsltLoader.LoadStylesheet().