Terraria: System.Xml.Xsl.Xslt.Compiler.CreateError
CreateError()
CompilerError System.Xml.Xsl.Xslt.Compiler.CreateError (ISourceLineInfo lineInfo, string res, params string[] args) inline
Definition at line 325 of file Compiler.cs.
    {
        AddModule(lineInfo.Uri);
        return new CompilerError(lineInfo.Uri, lineInfo.Start.Line, lineInfo.Start.Pos, string.Empty, XslTransformException.CreateMessage(res, args));
    }
References System.Xml.Xsl.Xslt.Compiler.AddModule(), System.Xml.Xsl.XslTransformException.CreateMessage(), System.Xml.Xsl.Location.Line, System.Xml.Xsl.Location.Pos, System.Xml.Xsl.ISourceLineInfo.Start, and System.Xml.Xsl.ISourceLineInfo.Uri.
Referenced by System.Xml.Xsl.Xslt.Compiler.ReportError(), and System.Xml.Xsl.Xslt.Compiler.ReportWarning().