Terraria: System.Xml.Xsl.Xslt.Compiler.ReportError
ReportError()
void System.Xml.Xsl.Xslt.Compiler.ReportError (ISourceLineInfo lineInfo, string res, params string[] args) inline
Definition at line 331 of file Compiler.cs.
    {
        CompilerError value = CreateError(lineInfo, res, args);
        CompilerErrorColl.Add(value);
    }
References System.Xml.Xsl.Xslt.CompilerErrorCollection.Add(), System.Xml.Xsl.Xslt.Compiler.CompilerErrorColl, System.Xml.Xsl.Xslt.Compiler.CreateError(), and System.value.
Referenced by System.Xml.Xsl.Xslt.XsltLoader.CheckAttributeSetsDfs(), System.Xml.Xsl.Xslt.XsltLoader.CheckError(), System.Xml.Xsl.Xslt.XsltLoader.CheckNoContent(), System.Xml.Xsl.Xslt.QilGenerator.CompileCallTemplate(), System.Xml.Xsl.Xslt.QilGenerator.CompileUseAttributeSet(), System.Xml.Xsl.Xslt.QilGenerator.ReportError(), System.Xml.Xsl.Xslt.XsltInput.ReportError(), System.Xml.Xsl.Xslt.XsltLoader.ReportError(), System.Xml.Xsl.Xslt.XsltInput.ReportErrorFC(), System.Xml.Xsl.Xslt.QilGenerator.ReportErrorInXPath(), and System.Xml.Xsl.Xslt.XsltLoader.XslApplyImports().