Terraria: System.Xml.Xsl.Xslt.Compiler.SortErrors
SortErrors()
void System.Xml.Xsl.Xslt.Compiler.SortErrors () inline private
Definition at line 356 of file Compiler.cs.
    {
        CompilerErrorCollection compilerErrorColl = CompilerErrorColl;
        if (compilerErrorColl.Count > 1)
        {
            CompilerError[] array = new CompilerError[compilerErrorColl.Count];
            compilerErrorColl.CopyTo(array, 0);
            Array.Sort(array, new CompilerErrorComparer(_moduleOrder));
            compilerErrorColl.Clear();
            compilerErrorColl.AddRange(array);
        }
    }
References System.Xml.Xsl.Xslt.Compiler._moduleOrder, System.Collections.Generic.Dictionary< TKey, TValue >.AddRange(), System.array, System.Collections.Generic.Dictionary< TKey, TValue >.Clear(), System.Xml.Xsl.Xslt.Compiler.CompilerErrorColl, System.Collections.Generic.Dictionary< TKey, TValue >.CopyTo(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, and System.Array.Sort().
Referenced by System.Xml.Xsl.Xslt.Compiler.Compile().