Terraria: System.Reflection.Metadata.Ecma335.MetadataTokens.Handle
Handle() [1/2]
static Handle System.Reflection.Metadata.Ecma335.MetadataTokens.Handle (int token) inline static
Definition at line 174 of file MetadataTokens.cs.
    {
        if (!TokenTypeIds.IsEntityOrUserStringToken((uint)token))
        {
            Throw.InvalidToken();
        }
        return System.Reflection.Metadata.Handle.FromVToken((uint)token);
    }
References System.Reflection.Metadata.Handle.FromVToken(), System.Reflection.Throw.InvalidToken(), and System.Reflection.Metadata.Ecma335.TokenTypeIds.IsEntityOrUserStringToken().
Referenced by System.Reflection.Metadata.Ecma335.MetadataTokens.EntityHandle(), and System.Diagnostics.StackTraceSymbols.GetSourceLineInfo().