Terraria: System.Reflection.Metadata.Ecma335.MetadataTokens.ToRowId
ToRowId()
static int System.Reflection.Metadata.Ecma335.MetadataTokens.ToRowId (int rowNumber) inline static private
Definition at line 207 of file MetadataTokens.cs.
    {
        return rowNumber & 0xFFFFFF;
    }
Referenced by System.Reflection.Metadata.Ecma335.MetadataTokens.AssemblyFileHandle(), System.Reflection.Metadata.Ecma335.MetadataTokens.AssemblyReferenceHandle(), System.Reflection.Metadata.Ecma335.MetadataTokens.ConstantHandle(), System.Reflection.Metadata.Ecma335.MetadataTokens.CustomAttributeHandle(), System.Reflection.Metadata.Ecma335.MetadataTokens.CustomDebugInformationHandle(), System.Reflection.Metadata.Ecma335.MetadataTokens.DeclarativeSecurityAttributeHandle(), System.Reflection.Metadata.Ecma335.MetadataTokens.DocumentHandle(), System.Reflection.Metadata.Ecma335.MetadataTokens.EventDefinitionHandle(), System.Reflection.Metadata.Ecma335.MetadataTokens.ExportedTypeHandle(), System.Reflection.Metadata.Ecma335.MetadataTokens.FieldDefinitionHandle(), System.Reflection.Metadata.Ecma335.MetadataTokens.GenericParameterConstraintHandle(), System.Reflection.Metadata.Ecma335.MetadataTokens.GenericParameterHandle(), System.Reflection.Metadata.Ecma335.MetadataTokens.ImportScopeHandle(), System.Reflection.Metadata.Ecma335.MetadataTokens.InterfaceImplementationHandle(), System.Reflection.Metadata.Ecma335.MetadataTokens.LocalConstantHandle(), System.Reflection.Metadata.Ecma335.MetadataTokens.LocalScopeHandle(), System.Reflection.Metadata.Ecma335.MetadataTokens.LocalVariableHandle(), System.Reflection.Metadata.Ecma335.MetadataTokens.ManifestResourceHandle(), System.Reflection.Metadata.Ecma335.MetadataTokens.MemberReferenceHandle(), System.Reflection.Metadata.Ecma335.MetadataTokens.MethodDebugInformationHandle(), System.Reflection.Metadata.Ecma335.MetadataTokens.MethodDefinitionHandle(), System.Reflection.Metadata.Ecma335.MetadataTokens.MethodImplementationHandle(), System.Reflection.Metadata.Ecma335.MetadataTokens.MethodSpecificationHandle(), System.Reflection.Metadata.Ecma335.MetadataTokens.ModuleReferenceHandle(), System.Reflection.Metadata.Ecma335.MetadataTokens.ParameterHandle(), System.Reflection.Metadata.Ecma335.MetadataTokens.PropertyDefinitionHandle(), System.Reflection.Metadata.Ecma335.MetadataTokens.StandaloneSignatureHandle(), System.Reflection.Metadata.Ecma335.MetadataTokens.TypeDefinitionHandle(), System.Reflection.Metadata.Ecma335.MetadataTokens.TypeReferenceHandle(), and System.Reflection.Metadata.Ecma335.MetadataTokens.TypeSpecificationHandle().