Terraria: System.Reflection.Metadata.Ecma335.MetadataTokens.GetToken
GetToken() [3/4]
static int System.Reflection.Metadata.Ecma335.MetadataTokens.GetToken (this MetadataReader reader, EntityHandle handle) inline static
Definition at line 31 of file MetadataTokens.cs.
    {
        if (handle.IsVirtual)
        {
            return (int)handle.Type | MapVirtualHandleRowId(reader, handle);
        }
        return handle.Token;
    }
References System.handle, and System.Reflection.Metadata.Ecma335.MetadataTokens.MapVirtualHandleRowId().
Referenced by System.Reflection.Metadata.Ecma335.ExceptionRegionEncoder.Add(), System.Reflection.Metadata.Ecma335.InstructionEncoder.LoadString(), System.Reflection.Metadata.Ecma335.ControlFlowBuilder.SerializeExceptionTable(), System.Reflection.Metadata.Ecma335.MethodBodyStreamEncoder.SerializeHeader(), System.Reflection.Metadata.Ecma335.PortablePdbBuilder.SerializeStandalonePdbStream(), System.Reflection.PortableExecutable.ManagedPEBuilder.SerializeTextSection(), and System.Reflection.Metadata.Ecma335.InstructionEncoder.Token().