Terraria: System.Reflection.Metadata.Ecma335.MetadataTokens.MapVirtualHandleRowId
MapVirtualHandleRowId()
static int System.Reflection.Metadata.Ecma335.MetadataTokens.MapVirtualHandleRowId (MetadataReader reader, Handle handle) inline static private
Definition at line 53 of file MetadataTokens.cs.
    {
        switch (handle.Kind)
        {
        case HandleKind.AssemblyReference:
            return reader.AssemblyRefTable.NumberOfNonVirtualRows + 1 + handle.RowId;
        case HandleKind.Blob:
        case HandleKind.String:
            throw new NotSupportedException(System.SR.CantGetOffsetForVirtualHeapHandle);
        default:
            Throw.InvalidArgument_UnexpectedHandleKind(handle.Kind);
            return 0;
        }
    }
References System.SR.CantGetOffsetForVirtualHeapHandle, System.handle, and System.Reflection.Throw.InvalidArgument_UnexpectedHandleKind().
Referenced by System.Reflection.Metadata.Ecma335.MetadataTokens.GetHeapOffset(), System.Reflection.Metadata.Ecma335.MetadataTokens.GetRowNumber(), System.Reflection.Metadata.Ecma335.MetadataTokens.GetToken(), and System.Reflection.Metadata.Ecma335.MetadataTokens.GetToken().