Terraria: System.Xml.XmlBinaryReader.ReadPartialUnicodeText
ReadPartialUnicodeText()
void System.Xml.XmlBinaryReader.ReadPartialUnicodeText (bool withEndElement, int length) inline private
Definition at line 1054 of file XmlBinaryReader.cs.
    {
        int num = Math.Max(_maxBytesPerRead - 5, 0);
        if (length <= num)
        {
            if (withEndElement)
            {
                ReadText(MoveToAtomicTextWithEndElement(), ValueHandleType.Unicode, length);
            }
            else
            {
                ReadText(MoveToComplexText(), ValueHandleType.Unicode, length);
            }
            return;
        }
        int num2 = Math.Max(num - 5, 0);
        if (((uint)num2 & (true ? 1u : 0u)) != 0)
        {
            num2--;
        }
        int num3 = base.BufferReader.ReadBytes(num2);
        int num4 = 0;
        char c = (char)base.BufferReader.GetInt16(num3 + num2 - 2);
        if (c >= '\ud800' && c < '\udc00')
        {
            num4 = 2;
        }
        base.BufferReader.Offset = base.BufferReader.Offset - num4;
        num2 -= num4;
        MoveToComplexText().Value.SetValue(ValueHandleType.Unicode, num3, num2);
        if (base.OutsideRootElement)
        {
            VerifyWhitespace();
        }
        XmlBinaryNodeType nodeType = (withEndElement ? XmlBinaryNodeType.UnicodeChars32TextWithEndElement : XmlBinaryNodeType.UnicodeChars32Text);
        InsertNode(nodeType, length - num2);
    }
References System.Xml.XmlBinaryReader._maxBytesPerRead, System.Xml.Dictionary, System.Xml.XmlBinaryReader.InsertNode(), System.length, System.Math.Max(), System.Xml.XmlBinaryReader.MoveToAtomicTextWithEndElement(), System.Xml.XmlBaseReader.MoveToComplexText(), System.Xml.XmlBinaryReader.ReadText(), System.Xml.ValueHandle.SetValue(), System.Xml.XmlBaseReader.XmlNode.Value, and System.Xml.XmlBinaryReader.VerifyWhitespace().
Referenced by System.Xml.XmlBinaryReader.ReadUnicodeText().