Terraria: System.Xml.XmlBinaryReader.ReadArray
ReadArray() [1/31]
void System.Xml.XmlBinaryReader.ReadArray () inline private
Definition at line 1225 of file XmlBinaryReader.cs.
    {
        if (GetNodeType() == XmlBinaryNodeType.Array)
        {
            XmlExceptionHelper.ThrowInvalidBinaryFormat(this);
        }
        ReadNode();
        if (base.Node.NodeType != XmlNodeType.Element)
        {
            XmlExceptionHelper.ThrowInvalidBinaryFormat(this);
        }
        if (GetNodeType() == XmlBinaryNodeType.Array)
        {
            XmlExceptionHelper.ThrowInvalidBinaryFormat(this);
        }
        ReadNode();
        if (base.Node.NodeType != XmlNodeType.EndElement)
        {
            XmlExceptionHelper.ThrowInvalidBinaryFormat(this);
        }
        _arrayState = ArrayState.Element;
        _arrayNodeType = GetNodeType();
        if (!IsValidArrayType(_arrayNodeType))
        {
            XmlExceptionHelper.ThrowInvalidBinaryFormat(this);
        }
        SkipNodeType();
        _arrayCount = ReadMultiByteUInt31();
        if (_arrayCount == 0)
        {
            XmlExceptionHelper.ThrowInvalidBinaryFormat(this);
        }
        MoveToArrayElement();
    }
References System.Xml.XmlBinaryReader._arrayCount, System.Xml.XmlBinaryReader._arrayNodeType, System.Xml.XmlBinaryReader._arrayState, System.Xml.Dictionary, System.Xml.XmlBinaryReader.GetNodeType(), System.Xml.XmlBinaryReader.IsValidArrayType(), System.Xml.XmlBinaryReader.MoveToArrayElement(), System.Xml.XmlBinaryReader.ReadMultiByteUInt31(), System.Xml.XmlBinaryReader.ReadNode(), System.Xml.XmlBinaryReader.SkipNodeType(), and System.Xml.XmlExceptionHelper.ThrowInvalidBinaryFormat().
Referenced by System.Xml.XmlBinaryReader.ReadArray(), System.Xml.XmlBinaryReader.ReadArray(), System.Xml.XmlBinaryReader.ReadArray(), System.Xml.XmlBinaryReader.ReadArray(), System.Xml.XmlBinaryReader.ReadArray(), System.Xml.XmlBinaryReader.ReadArray(), System.Xml.XmlBinaryReader.ReadArray(), System.Xml.XmlBinaryReader.ReadArray(), System.Xml.XmlBinaryReader.ReadArray(), System.Xml.XmlBinaryReader.ReadArray(), System.Xml.XmlBinaryReader.ReadArray(), System.Xml.XmlBinaryReader.ReadArray(), System.Xml.XmlBinaryReader.ReadArray(), System.Xml.XmlBinaryReader.ReadArray(), System.Xml.XmlBinaryReader.ReadArray(), System.Xml.XmlBinaryReader.ReadArray(), System.Xml.XmlBinaryReader.ReadArray(), System.Xml.XmlBinaryReader.ReadArray(), System.Xml.XmlBinaryReader.ReadArray(), System.Xml.XmlBinaryReader.ReadArray(), and System.Xml.XmlBinaryReader.ReadNode().