Terraria: System.Xml.XmlBinaryReader.ReadAttributes2
ReadAttributes2()
void System.Xml.XmlBinaryReader.ReadAttributes2 () inline private
Definition at line 816 of file XmlBinaryReader.cs.
    {
        int num = 0;
        if (_buffered)
        {
            num = base.BufferReader.Offset;
        }
        while (true)
        {
            XmlBinaryNodeType nodeType = GetNodeType();
            switch (nodeType)
            {
            case XmlBinaryNodeType.MinAttribute:
            {
                SkipNodeType();
                XmlAttributeNode xmlAttributeNode = AddAttribute();
                xmlAttributeNode.Prefix.SetValue(PrefixHandleType.Empty);
                ReadName(xmlAttributeNode.LocalName);
                ReadAttributeText(xmlAttributeNode.AttributeText);
                break;
            }
            case XmlBinaryNodeType.Attribute:
            {
                SkipNodeType();
                XmlAttributeNode xmlAttributeNode = AddAttribute();
                ReadName(xmlAttributeNode.Prefix);
                ReadName(xmlAttributeNode.LocalName);
                ReadAttributeText(xmlAttributeNode.AttributeText);
                FixXmlAttribute(xmlAttributeNode);
                break;
            }
            case XmlBinaryNodeType.ShortDictionaryAttribute:
            {
                SkipNodeType();
                XmlAttributeNode xmlAttributeNode = AddAttribute();
                xmlAttributeNode.Prefix.SetValue(PrefixHandleType.Empty);
                ReadDictionaryName(xmlAttributeNode.LocalName);
                ReadAttributeText(xmlAttributeNode.AttributeText);
                break;
            }
            case XmlBinaryNodeType.DictionaryAttribute:
            {
                SkipNodeType();
                XmlAttributeNode xmlAttributeNode = AddAttribute();
                ReadName(xmlAttributeNode.Prefix);
                ReadDictionaryName(xmlAttributeNode.LocalName);
                ReadAttributeText(xmlAttributeNode.AttributeText);
                break;
            }
            case XmlBinaryNodeType.XmlnsAttribute:
            {
                SkipNodeType();
                Namespace @namespace = AddNamespace();
                ReadName(@namespace.Prefix);
                ReadName(@namespace.Uri);
                XmlAttributeNode xmlAttributeNode = AddXmlnsAttribute(@namespace);
                break;
            }
            case XmlBinaryNodeType.ShortXmlnsAttribute:
            {
                SkipNodeType();
                Namespace @namespace = AddNamespace();
                @namespace.Prefix.SetValue(PrefixHandleType.Empty);
                ReadName(@namespace.Uri);
                XmlAttributeNode xmlAttributeNode = AddXmlnsAttribute(@namespace);
                break;
            }
            case XmlBinaryNodeType.ShortDictionaryXmlnsAttribute:
            {
                SkipNodeType();
                Namespace @namespace = AddNamespace();
                @namespace.Prefix.SetValue(PrefixHandleType.Empty);
                ReadDictionaryName(@namespace.Uri);
                XmlAttributeNode xmlAttributeNode = AddXmlnsAttribute(@namespace);
                break;
            }
            case XmlBinaryNodeType.DictionaryXmlnsAttribute:
            {
                SkipNodeType();
                Namespace @namespace = AddNamespace();
                ReadName(@namespace.Prefix);
                ReadDictionaryName(@namespace.Uri);
                XmlAttributeNode xmlAttributeNode = AddXmlnsAttribute(@namespace);
                break;
            }
            case XmlBinaryNodeType.PrefixDictionaryAttributeA:
            case XmlBinaryNodeType.PrefixDictionaryAttributeB:
            case XmlBinaryNodeType.PrefixDictionaryAttributeC:
            case XmlBinaryNodeType.PrefixDictionaryAttributeD:
            case XmlBinaryNodeType.PrefixDictionaryAttributeE:
            case XmlBinaryNodeType.PrefixDictionaryAttributeF:
            case XmlBinaryNodeType.PrefixDictionaryAttributeG:
            case XmlBinaryNodeType.PrefixDictionaryAttributeH:
            case XmlBinaryNodeType.PrefixDictionaryAttributeI:
            case XmlBinaryNodeType.PrefixDictionaryAttributeJ:
            case XmlBinaryNodeType.PrefixDictionaryAttributeK:
            case XmlBinaryNodeType.PrefixDictionaryAttributeL:
            case XmlBinaryNodeType.PrefixDictionaryAttributeM:
            case XmlBinaryNodeType.PrefixDictionaryAttributeN:
            case XmlBinaryNodeType.PrefixDictionaryAttributeO:
            case XmlBinaryNodeType.PrefixDictionaryAttributeP:
            case XmlBinaryNodeType.PrefixDictionaryAttributeQ:
            case XmlBinaryNodeType.PrefixDictionaryAttributeR:
            case XmlBinaryNodeType.PrefixDictionaryAttributeS:
            case XmlBinaryNodeType.PrefixDictionaryAttributeT:
            case XmlBinaryNodeType.PrefixDictionaryAttributeU:
            case XmlBinaryNodeType.PrefixDictionaryAttributeV:
            case XmlBinaryNodeType.PrefixDictionaryAttributeW:
            case XmlBinaryNodeType.PrefixDictionaryAttributeX:
            case XmlBinaryNodeType.PrefixDictionaryAttributeY:
            case XmlBinaryNodeType.PrefixDictionaryAttributeZ:
            {
                SkipNodeType();
                XmlAttributeNode xmlAttributeNode = AddAttribute();
                PrefixHandleType alphaPrefix = PrefixHandle.GetAlphaPrefix((int)(nodeType - 12));
                xmlAttributeNode.Prefix.SetValue(alphaPrefix);
                ReadDictionaryName(xmlAttributeNode.LocalName);
                ReadAttributeText(xmlAttributeNode.AttributeText);
                break;
            }
            case XmlBinaryNodeType.PrefixAttributeA:
            case XmlBinaryNodeType.PrefixAttributeB:
            case XmlBinaryNodeType.PrefixAttributeC:
            case XmlBinaryNodeType.PrefixAttributeD:
            case XmlBinaryNodeType.PrefixAttributeE:
            case XmlBinaryNodeType.PrefixAttributeF:
            case XmlBinaryNodeType.PrefixAttributeG:
            case XmlBinaryNodeType.PrefixAttributeH:
            case XmlBinaryNodeType.PrefixAttributeI:
            case XmlBinaryNodeType.PrefixAttributeJ:
            case XmlBinaryNodeType.PrefixAttributeK:
            case XmlBinaryNodeType.PrefixAttributeL:
            case XmlBinaryNodeType.PrefixAttributeM:
            case XmlBinaryNodeType.PrefixAttributeN:
            case XmlBinaryNodeType.PrefixAttributeO:
            case XmlBinaryNodeType.PrefixAttributeP:
            case XmlBinaryNodeType.PrefixAttributeQ:
            case XmlBinaryNodeType.PrefixAttributeR:
            case XmlBinaryNodeType.PrefixAttributeS:
            case XmlBinaryNodeType.PrefixAttributeT:
            case XmlBinaryNodeType.PrefixAttributeU:
            case XmlBinaryNodeType.PrefixAttributeV:
            case XmlBinaryNodeType.PrefixAttributeW:
            case XmlBinaryNodeType.PrefixAttributeX:
            case XmlBinaryNodeType.PrefixAttributeY:
            case XmlBinaryNodeType.PrefixAttributeZ:
            {
                SkipNodeType();
                XmlAttributeNode xmlAttributeNode = AddAttribute();
                PrefixHandleType alphaPrefix = PrefixHandle.GetAlphaPrefix((int)(nodeType - 38));
                xmlAttributeNode.Prefix.SetValue(alphaPrefix);
                ReadName(xmlAttributeNode.LocalName);
                ReadAttributeText(xmlAttributeNode.AttributeText);
                break;
            }
            default:
                ProcessAttributes();
                return;
            }
        }
    }
References System.Xml.XmlBinaryReader._buffered, System.Xml.XmlBaseReader.AddAttribute(), System.Xml.XmlBaseReader.AddNamespace(), System.Xml.XmlBaseReader.AddXmlnsAttribute(), System.Xml.Dictionary, System.Xml.XmlBaseReader.FixXmlAttribute(), System.Xml.PrefixHandle.GetAlphaPrefix(), System.Xml.XmlBinaryReader.GetNodeType(), System.Xml.XmlBaseReader.Namespace.Prefix, System.Xml.XmlBaseReader.Prefix, System.Xml.XmlBaseReader.ProcessAttributes(), System.Xml.XmlBinaryReader.ReadAttributeText(), System.Xml.XmlBinaryReader.ReadDictionaryName(), System.Xml.XmlBinaryReader.ReadName(), System.Xml.PrefixHandle.SetValue(), and System.Xml.XmlBinaryReader.SkipNodeType().
Referenced by System.Xml.XmlBinaryReader.ReadAttributes().