Terraria: System.Xml.XmlBinaryReader.Read
Read()
override bool System.Xml.XmlBinaryReader.Read () inline
Definition at line 396 of file XmlBinaryReader.cs.
    {
        if (base.Node.ReadState == ReadState.Closed)
        {
            return false;
        }
        SignNode();
        if (_isTextWithEndElement)
        {
            _isTextWithEndElement = false;
            MoveToEndElement();
            return true;
        }
        if (_arrayState == ArrayState.Content)
        {
            if (_arrayCount != 0)
            {
                MoveToArrayElement();
                return true;
            }
            _arrayState = ArrayState.None;
        }
        if (base.Node.ExitScope)
        {
            ExitScope();
        }
        return ReadNode();
    }
References System.Xml.XmlBinaryReader._arrayCount, System.Xml.XmlBinaryReader._arrayState, System.Xml.XmlBinaryReader._isTextWithEndElement, System.Xml.Dictionary, System.Xml.XmlBaseReader.ExitScope(), System.Xml.XmlBinaryReader.MoveToArrayElement(), System.Xml.XmlBaseReader.MoveToEndElement(), System.Xml.XmlBinaryReader.ReadNode(), and System.Xml.XmlBaseReader.SignNode().