Terraria: System.Xml.XmlBinaryReader.ReadPartialBinaryText
ReadPartialBinaryText()
void System.Xml.XmlBinaryReader.ReadPartialBinaryText (bool withEndElement, int length) inline private
Definition at line 1092 of file XmlBinaryReader.cs.
    {
        int num = Math.Max(_maxBytesPerRead - 5, 0);
        if (length <= num)
        {
            if (withEndElement)
            {
                ReadText(MoveToAtomicTextWithEndElement(), ValueHandleType.Base64, length);
            }
            else
            {
                ReadText(MoveToComplexText(), ValueHandleType.Base64, length);
            }
            return;
        }
        int num2 = num;
        if (num2 > 3)
        {
            num2 -= num2 % 3;
        }
        ReadText(MoveToComplexText(), ValueHandleType.Base64, num2);
        XmlBinaryNodeType nodeType = (withEndElement ? XmlBinaryNodeType.Bytes32TextWithEndElement : XmlBinaryNodeType.Bytes32Text);
        InsertNode(nodeType, length - num2);
    }
References System.Xml.XmlBinaryReader._maxBytesPerRead, System.Xml.Dictionary, System.Xml.XmlBinaryReader.InsertNode(), System.length, System.Math.Max(), System.Xml.XmlBinaryReader.MoveToAtomicTextWithEndElement(), System.Xml.XmlBaseReader.MoveToComplexText(), and System.Xml.XmlBinaryReader.ReadText().
Referenced by System.Xml.XmlBinaryReader.ReadNode().