Terraria: System.Xml.XmlBinaryReader.SkipArrayElements
SkipArrayElements()
void System.Xml.XmlBinaryReader.SkipArrayElements (int count) inline private
Definition at line 1266 of file XmlBinaryReader.cs.
    {
        _arrayCount -= count;
        if (_arrayCount == 0)
        {
            _arrayState = ArrayState.None;
            ExitScope();
            ReadNode();
        }
    }
References System.Xml.XmlBinaryReader._arrayCount, System.Xml.XmlBinaryReader._arrayState, System.count, System.Xml.XmlBaseReader.ExitScope(), and System.Xml.XmlBinaryReader.ReadNode().
Referenced by System.Xml.XmlBinaryReader.ReadArray(), System.Xml.XmlBinaryReader.ReadArray(), System.Xml.XmlBinaryReader.ReadArray(), System.Xml.XmlBinaryReader.ReadArray(), System.Xml.XmlBinaryReader.ReadArray(), System.Xml.XmlBinaryReader.ReadArray(), System.Xml.XmlBinaryReader.ReadArray(), System.Xml.XmlBinaryReader.ReadArray(), System.Xml.XmlBinaryReader.ReadArray(), and System.Xml.XmlBinaryReader.ReadArray().