Terraria: System.Xml.XmlBinaryReader.MoveToInitial
MoveToInitial() [2/2]
void System.Xml.XmlBinaryReader.MoveToInitial (XmlDictionaryReaderQuotas quotas, XmlBinaryReaderSession session, OnXmlDictionaryReaderClose onClose) inline private
Definition at line 66 of file XmlBinaryReader.cs.
    {
        MoveToInitial(quotas);
        _maxBytesPerRead = quotas.MaxBytesPerRead;
        _arrayState = ArrayState.None;
        _isTextWithEndElement = false;
    }
References System.Xml.XmlBinaryReader._arrayState, System.Xml.XmlBinaryReader._isTextWithEndElement, System.Xml.XmlBinaryReader._maxBytesPerRead, System.Xml.Dictionary, and System.Xml.XmlBinaryReader.MoveToInitial().
Referenced by System.Xml.XmlBinaryReader.MoveToInitial(), System.Xml.XmlBinaryReader.SetInput(), and System.Xml.XmlBinaryReader.SetInput().