Terraria: System.Xml.XmlBinaryReader.ReadPartialUTF8Text
ReadPartialUTF8Text()
void System.Xml.XmlBinaryReader.ReadPartialUTF8Text (bool withEndElement, int length) inline private
Definition at line 993 of file XmlBinaryReader.cs.
    {
        int num = Math.Max(_maxBytesPerRead - 5, 0);
        if (length <= num)
        {
            if (withEndElement)
            {
                ReadText(MoveToAtomicTextWithEndElement(), ValueHandleType.UTF8, length);
            }
            else
            {
                ReadText(MoveToComplexText(), ValueHandleType.UTF8, length);
            }
            return;
        }
        int num2 = Math.Max(num - 5, 0);
        int num3 = base.BufferReader.ReadBytes(num2);
        int num4;
        for (num4 = num3 + num2 - 1; num4 >= num3; num4--)
        {
            byte @byte = base.BufferReader.GetByte(num4);
            if ((@byte & 0x80) == 0 || (@byte & 0xC0) == 192)
            {
                break;
            }
        }
        int num5 = num3 + num2 - num4;
        base.BufferReader.Offset = base.BufferReader.Offset - num5;
        num2 -= num5;
        MoveToComplexText().Value.SetValue(ValueHandleType.UTF8, num3, num2);
        if (base.OutsideRootElement)
        {
            VerifyWhitespace();
        }
        XmlBinaryNodeType nodeType = (withEndElement ? XmlBinaryNodeType.Chars32TextWithEndElement : XmlBinaryNodeType.Chars32Text);
        InsertNode(nodeType, length - num2);
    }
References System.Xml.XmlBinaryReader._maxBytesPerRead, System.Xml.Dictionary, System.Xml.XmlBinaryReader.InsertNode(), System.length, System.Math.Max(), System.Xml.XmlBinaryReader.MoveToAtomicTextWithEndElement(), System.Xml.XmlBaseReader.MoveToComplexText(), System.Xml.XmlBinaryReader.ReadText(), System.Xml.ValueHandle.SetValue(), System.Xml.XmlBaseReader.XmlNode.Value, and System.Xml.XmlBinaryReader.VerifyWhitespace().
Referenced by System.Xml.XmlBinaryReader.ReadNode().