Terraria: System.Xml.XmlBinaryReader.GetNodeType
GetNodeType()
XmlBinaryNodeType System.Xml.XmlBinaryReader.GetNodeType () inline private
Definition at line 1170 of file XmlBinaryReader.cs.
    {
        return base.BufferReader.GetNodeType();
    }
References System.Xml.Dictionary.
Referenced by System.Xml.XmlBinaryReader.ReadArray(), System.Xml.XmlBinaryReader.ReadAttributes(), System.Xml.XmlBinaryReader.ReadAttributes2(), System.Xml.XmlBinaryReader.ReadAttributeText(), System.Xml.XmlBinaryReader.ReadElementContentAsBoolean(), System.Xml.XmlBinaryReader.ReadElementContentAsDateTime(), System.Xml.XmlBinaryReader.ReadElementContentAsDecimal(), System.Xml.XmlBinaryReader.ReadElementContentAsDouble(), System.Xml.XmlBinaryReader.ReadElementContentAsFloat(), System.Xml.XmlBinaryReader.ReadElementContentAsGuid(), System.Xml.XmlBinaryReader.ReadElementContentAsInt(), System.Xml.XmlBinaryReader.ReadElementContentAsString(), System.Xml.XmlBinaryReader.ReadElementContentAsTimeSpan(), System.Xml.XmlBinaryReader.ReadElementContentAsUniqueId(), System.Xml.XmlBinaryReader.ReadNode(), and System.Xml.XmlBinaryReader.TryGetBase64ContentLength().