Terraria: System.Xml.XmlBinaryReader.CanOptimizeReadElementContent
CanOptimizeReadElementContent()
bool System.Xml.XmlBinaryReader.CanOptimizeReadElementContent () inline private
Definition at line 193 of file XmlBinaryReader.cs.
    {
        if (_arrayState == ArrayState.None)
        {
            return !base.Signing;
        }
        return false;
    }
References System.Xml.XmlBinaryReader._arrayState, and System.Xml.Dictionary.
Referenced by System.Xml.XmlBinaryReader.ReadElementContentAsBoolean(), System.Xml.XmlBinaryReader.ReadElementContentAsDateTime(), System.Xml.XmlBinaryReader.ReadElementContentAsDecimal(), System.Xml.XmlBinaryReader.ReadElementContentAsDouble(), System.Xml.XmlBinaryReader.ReadElementContentAsFloat(), System.Xml.XmlBinaryReader.ReadElementContentAsGuid(), System.Xml.XmlBinaryReader.ReadElementContentAsInt(), System.Xml.XmlBinaryReader.ReadElementContentAsString(), System.Xml.XmlBinaryReader.ReadElementContentAsTimeSpan(), and System.Xml.XmlBinaryReader.ReadElementContentAsUniqueId().