Terraria: System.Xml.XmlBinaryReader.ReadAttributes
ReadAttributes()
void System.Xml.XmlBinaryReader.ReadAttributes () inline private
Definition at line 807 of file XmlBinaryReader.cs.
    {
        XmlBinaryNodeType nodeType = GetNodeType();
        if (nodeType >= XmlBinaryNodeType.MinAttribute && nodeType <= XmlBinaryNodeType.PrefixAttributeZ)
        {
            ReadAttributes2();
        }
    }
References System.Xml.XmlBinaryReader.GetNodeType(), and System.Xml.XmlBinaryReader.ReadAttributes2().
Referenced by System.Xml.XmlBinaryReader.ReadNode().