Terraria: System.Xml.XmlBinaryReader.MoveToAtomicTextWithEndElement
MoveToAtomicTextWithEndElement()
XmlAtomicTextNode System.Xml.XmlBinaryReader.MoveToAtomicTextWithEndElement () inline private
Definition at line 390 of file XmlBinaryReader.cs.
    {
        _isTextWithEndElement = true;
        return MoveToAtomicText();
    }
References System.Xml.XmlBinaryReader._isTextWithEndElement, and System.Xml.XmlBaseReader.MoveToAtomicText().
Referenced by System.Xml.XmlBinaryReader.ReadNode(), System.Xml.XmlBinaryReader.ReadPartialBinaryText(), System.Xml.XmlBinaryReader.ReadPartialUnicodeText(), System.Xml.XmlBinaryReader.ReadPartialUTF8Text(), and System.Xml.XmlBinaryReader.ReadUnicodeText().