Terraria: System.Xml.XmlBinaryReader.ReadElementContentAsTimeSpan
ReadElementContentAsTimeSpan()
override TimeSpan System.Xml.XmlBinaryReader.ReadElementContentAsTimeSpan () inline virtual
Reimplemented from System.Xml.XmlDictionaryReader.
Definition at line 266 of file XmlBinaryReader.cs.
    {
        if (base.Node.NodeType != XmlNodeType.Element)
        {
            MoveToStartElement();
        }
        if (CanOptimizeReadElementContent() && GetNodeType() == XmlBinaryNodeType.TimeSpanTextWithEndElement)
        {
            SkipNodeType();
            TimeSpan result = base.BufferReader.ReadTimeSpan();
            ReadTextWithEndElement();
            return result;
        }
        return base.ReadElementContentAsTimeSpan();
    }
References System.Xml.XmlBinaryReader.CanOptimizeReadElementContent(), System.Xml.Dictionary, System.Xml.XmlBinaryReader.GetNodeType(), System.Xml.XmlDictionaryReader.MoveToStartElement(), System.Xml.XmlBinaryReader.ReadTextWithEndElement(), and System.Xml.XmlBinaryReader.SkipNodeType().