Terraria: Terraria.UI.Chat.ChatMessageContainer.SetContents
SetContents()
void Terraria.UI.Chat.ChatMessageContainer.SetContents (string text, Color color, int widthLimitInPixels) inline
Definition at line 27 of file ChatMessageContainer.cs.
    {
        OriginalText = text;
        _color = color;
        _widthLimitInPixels = widthLimitInPixels;
        MarkToNeedRefresh();
        _parsedText = new List<TextSnippet[]>();
        _timeLeft = 600;
        Refresh();
    }
References Terraria.UI.Chat.ChatMessageContainer._color, Terraria.UI.Chat.ChatMessageContainer._parsedText, Terraria.UI.Chat.ChatMessageContainer._timeLeft, Terraria.UI.Chat.ChatMessageContainer._widthLimitInPixels, Terraria.UI.Chat.ChatMessageContainer.MarkToNeedRefresh(), Terraria.UI.Chat.ChatMessageContainer.OriginalText, and Terraria.UI.Chat.ChatMessageContainer.Refresh().
Referenced by Terraria.GameContent.UI.Chat.RemadeChatMonitor.AddNewMessage().