Terraria: System.Xml.XmlBinaryReader.ReadNode
ReadNode()
bool System.Xml.XmlBinaryReader.ReadNode () inline private
Definition at line 425 of file XmlBinaryReader.cs.
    {
        if (!_buffered)
        {
            base.BufferReader.SetWindow(base.ElementNode.BufferOffset, _maxBytesPerRead);
        }
        if (base.BufferReader.EndOfFile)
        {
            MoveToEndOfFile();
            return false;
        }
        XmlBinaryNodeType xmlBinaryNodeType;
        if (_arrayState == ArrayState.None)
        {
            xmlBinaryNodeType = GetNodeType();
            SkipNodeType();
        }
        else
        {
            xmlBinaryNodeType = _arrayNodeType;
            _arrayCount--;
            _arrayState = ArrayState.Content;
        }
        switch (xmlBinaryNodeType)
        {
        case XmlBinaryNodeType.MinElement:
        {
            XmlElementNode xmlElementNode = EnterScope();
            xmlElementNode.Prefix.SetValue(PrefixHandleType.Empty);
            ReadName(xmlElementNode.LocalName);
            ReadAttributes();
            xmlElementNode.Namespace = LookupNamespace(PrefixHandleType.Empty);
            xmlElementNode.BufferOffset = base.BufferReader.Offset;
            return true;
        }
        case XmlBinaryNodeType.Element:
        {
            XmlElementNode xmlElementNode = EnterScope();
            ReadName(xmlElementNode.Prefix);
            ReadName(xmlElementNode.LocalName);
            ReadAttributes();
            xmlElementNode.Namespace = LookupNamespace(xmlElementNode.Prefix);
            xmlElementNode.BufferOffset = base.BufferReader.Offset;
            return true;
        }
        case XmlBinaryNodeType.ShortDictionaryElement:
        {
            XmlElementNode xmlElementNode = EnterScope();
            xmlElementNode.Prefix.SetValue(PrefixHandleType.Empty);
            ReadDictionaryName(xmlElementNode.LocalName);
            ReadAttributes();
            xmlElementNode.Namespace = LookupNamespace(PrefixHandleType.Empty);
            xmlElementNode.BufferOffset = base.BufferReader.Offset;
            return true;
        }
        case XmlBinaryNodeType.DictionaryElement:
        {
            XmlElementNode xmlElementNode = EnterScope();
            ReadName(xmlElementNode.Prefix);
            ReadDictionaryName(xmlElementNode.LocalName);
            ReadAttributes();
            xmlElementNode.Namespace = LookupNamespace(xmlElementNode.Prefix);
            xmlElementNode.BufferOffset = base.BufferReader.Offset;
            return true;
        }
        case XmlBinaryNodeType.PrefixElementA:
        case XmlBinaryNodeType.PrefixElementB:
        case XmlBinaryNodeType.PrefixElementC:
        case XmlBinaryNodeType.PrefixElementD:
        case XmlBinaryNodeType.PrefixElementE:
        case XmlBinaryNodeType.PrefixElementF:
        case XmlBinaryNodeType.PrefixElementG:
        case XmlBinaryNodeType.PrefixElementH:
        case XmlBinaryNodeType.PrefixElementI:
        case XmlBinaryNodeType.PrefixElementJ:
        case XmlBinaryNodeType.PrefixElementK:
        case XmlBinaryNodeType.PrefixElementL:
        case XmlBinaryNodeType.PrefixElementM:
        case XmlBinaryNodeType.PrefixElementN:
        case XmlBinaryNodeType.PrefixElementO:
        case XmlBinaryNodeType.PrefixElementP:
        case XmlBinaryNodeType.PrefixElementQ:
        case XmlBinaryNodeType.PrefixElementR:
        case XmlBinaryNodeType.PrefixElementS:
        case XmlBinaryNodeType.PrefixElementT:
        case XmlBinaryNodeType.PrefixElementU:
        case XmlBinaryNodeType.PrefixElementV:
        case XmlBinaryNodeType.PrefixElementW:
        case XmlBinaryNodeType.PrefixElementX:
        case XmlBinaryNodeType.PrefixElementY:
        case XmlBinaryNodeType.PrefixElementZ:
        {
            XmlElementNode xmlElementNode = EnterScope();
            PrefixHandleType alphaPrefix = PrefixHandle.GetAlphaPrefix((int)(xmlBinaryNodeType - 94));
            xmlElementNode.Prefix.SetValue(alphaPrefix);
            ReadName(xmlElementNode.LocalName);
            ReadAttributes();
            xmlElementNode.Namespace = LookupNamespace(alphaPrefix);
            xmlElementNode.BufferOffset = base.BufferReader.Offset;
            return true;
        }
        case XmlBinaryNodeType.PrefixDictionaryElementA:
        case XmlBinaryNodeType.PrefixDictionaryElementB:
        case XmlBinaryNodeType.PrefixDictionaryElementC:
        case XmlBinaryNodeType.PrefixDictionaryElementD:
        case XmlBinaryNodeType.PrefixDictionaryElementE:
        case XmlBinaryNodeType.PrefixDictionaryElementF:
        case XmlBinaryNodeType.PrefixDictionaryElementG:
        case XmlBinaryNodeType.PrefixDictionaryElementH:
        case XmlBinaryNodeType.PrefixDictionaryElementI:
        case XmlBinaryNodeType.PrefixDictionaryElementJ:
        case XmlBinaryNodeType.PrefixDictionaryElementK:
        case XmlBinaryNodeType.PrefixDictionaryElementL:
        case XmlBinaryNodeType.PrefixDictionaryElementM:
        case XmlBinaryNodeType.PrefixDictionaryElementN:
        case XmlBinaryNodeType.PrefixDictionaryElementO:
        case XmlBinaryNodeType.PrefixDictionaryElementP:
        case XmlBinaryNodeType.PrefixDictionaryElementQ:
        case XmlBinaryNodeType.PrefixDictionaryElementR:
        case XmlBinaryNodeType.PrefixDictionaryElementS:
        case XmlBinaryNodeType.PrefixDictionaryElementT:
        case XmlBinaryNodeType.PrefixDictionaryElementU:
        case XmlBinaryNodeType.PrefixDictionaryElementV:
        case XmlBinaryNodeType.PrefixDictionaryElementW:
        case XmlBinaryNodeType.PrefixDictionaryElementX:
        case XmlBinaryNodeType.PrefixDictionaryElementY:
        case XmlBinaryNodeType.PrefixDictionaryElementZ:
        {
            XmlElementNode xmlElementNode = EnterScope();
            PrefixHandleType alphaPrefix = PrefixHandle.GetAlphaPrefix((int)(xmlBinaryNodeType - 68));
            xmlElementNode.Prefix.SetValue(alphaPrefix);
            ReadDictionaryName(xmlElementNode.LocalName);
            ReadAttributes();
            xmlElementNode.Namespace = LookupNamespace(alphaPrefix);
            xmlElementNode.BufferOffset = base.BufferReader.Offset;
            return true;
        }
        case XmlBinaryNodeType.EndElement:
            MoveToEndElement();
            return true;
        case XmlBinaryNodeType.Comment:
            ReadName(MoveToComment().Value);
            return true;
        case XmlBinaryNodeType.EmptyTextWithEndElement:
            MoveToAtomicTextWithEndElement().Value.SetValue(ValueHandleType.Empty);
            if (base.OutsideRootElement)
            {
                VerifyWhitespace();
            }
            return true;
        case XmlBinaryNodeType.ZeroTextWithEndElement:
            MoveToAtomicTextWithEndElement().Value.SetValue(ValueHandleType.Zero);
            if (base.OutsideRootElement)
            {
                VerifyWhitespace();
            }
            return true;
        case XmlBinaryNodeType.OneTextWithEndElement:
            MoveToAtomicTextWithEndElement().Value.SetValue(ValueHandleType.One);
            if (base.OutsideRootElement)
            {
                VerifyWhitespace();
            }
            return true;
        case XmlBinaryNodeType.TrueTextWithEndElement:
            MoveToAtomicTextWithEndElement().Value.SetValue(ValueHandleType.True);
            if (base.OutsideRootElement)
            {
                VerifyWhitespace();
            }
            return true;
        case XmlBinaryNodeType.FalseTextWithEndElement:
            MoveToAtomicTextWithEndElement().Value.SetValue(ValueHandleType.False);
            if (base.OutsideRootElement)
            {
                VerifyWhitespace();
            }
            return true;
        case XmlBinaryNodeType.BoolTextWithEndElement:
            MoveToAtomicTextWithEndElement().Value.SetValue((ReadUInt8() != 0) ? ValueHandleType.True : ValueHandleType.False);
            if (base.OutsideRootElement)
            {
                VerifyWhitespace();
            }
            return true;
        case XmlBinaryNodeType.Chars8TextWithEndElement:
            if (_buffered)
            {
                ReadText(MoveToAtomicTextWithEndElement(), ValueHandleType.UTF8, ReadUInt8());
            }
            else
            {
                ReadPartialUTF8Text(withEndElement: true, ReadUInt8());
            }
            return true;
        case XmlBinaryNodeType.Chars8Text:
            if (_buffered)
            {
                ReadText(MoveToComplexText(), ValueHandleType.UTF8, ReadUInt8());
            }
            else
            {
                ReadPartialUTF8Text(withEndElement: false, ReadUInt8());
            }
            return true;
        case XmlBinaryNodeType.Chars16TextWithEndElement:
            if (_buffered)
            {
                ReadText(MoveToAtomicTextWithEndElement(), ValueHandleType.UTF8, ReadUInt16());
            }
            else
            {
                ReadPartialUTF8Text(withEndElement: true, ReadUInt16());
            }
            return true;
        case XmlBinaryNodeType.Chars16Text:
            if (_buffered)
            {
                ReadText(MoveToComplexText(), ValueHandleType.UTF8, ReadUInt16());
            }
            else
            {
                ReadPartialUTF8Text(withEndElement: false, ReadUInt16());
            }
            return true;
        case XmlBinaryNodeType.Chars32TextWithEndElement:
            if (_buffered)
            {
                ReadText(MoveToAtomicTextWithEndElement(), ValueHandleType.UTF8, ReadUInt31());
            }
            else
            {
                ReadPartialUTF8Text(withEndElement: true, ReadUInt31());
            }
            return true;
        case XmlBinaryNodeType.Chars32Text:
            if (_buffered)
            {
                ReadText(MoveToComplexText(), ValueHandleType.UTF8, ReadUInt31());
            }
            else
            {
                ReadPartialUTF8Text(withEndElement: false, ReadUInt31());
            }
            return true;
        case XmlBinaryNodeType.UnicodeChars8TextWithEndElement:
            ReadUnicodeText(withEndElement: true, ReadUInt8());
            return true;
        case XmlBinaryNodeType.UnicodeChars8Text:
            ReadUnicodeText(withEndElement: false, ReadUInt8());
            return true;
        case XmlBinaryNodeType.UnicodeChars16TextWithEndElement:
            ReadUnicodeText(withEndElement: true, ReadUInt16());
            return true;
        case XmlBinaryNodeType.UnicodeChars16Text:
            ReadUnicodeText(withEndElement: false, ReadUInt16());
            return true;
        case XmlBinaryNodeType.UnicodeChars32TextWithEndElement:
            ReadUnicodeText(withEndElement: true, ReadUInt31());
            return true;
        case XmlBinaryNodeType.UnicodeChars32Text:
            ReadUnicodeText(withEndElement: false, ReadUInt31());
            return true;
        case XmlBinaryNodeType.Bytes8TextWithEndElement:
            if (_buffered)
            {
                ReadBinaryText(MoveToAtomicTextWithEndElement(), ReadUInt8());
            }
            else
            {
                ReadPartialBinaryText(withEndElement: true, ReadUInt8());
            }
            return true;
        case XmlBinaryNodeType.Bytes8Text:
            if (_buffered)
            {
                ReadBinaryText(MoveToComplexText(), ReadUInt8());
            }
            else
            {
                ReadPartialBinaryText(withEndElement: false, ReadUInt8());
            }
            return true;
        case XmlBinaryNodeType.Bytes16TextWithEndElement:
            if (_buffered)
            {
                ReadBinaryText(MoveToAtomicTextWithEndElement(), ReadUInt16());
            }
            else
            {
                ReadPartialBinaryText(withEndElement: true, ReadUInt16());
            }
            return true;
        case XmlBinaryNodeType.Bytes16Text:
            if (_buffered)
            {
                ReadBinaryText(MoveToComplexText(), ReadUInt16());
            }
            else
            {
                ReadPartialBinaryText(withEndElement: false, ReadUInt16());
            }
            return true;
        case XmlBinaryNodeType.Bytes32TextWithEndElement:
            if (_buffered)
            {
                ReadBinaryText(MoveToAtomicTextWithEndElement(), ReadUInt31());
            }
            else
            {
                ReadPartialBinaryText(withEndElement: true, ReadUInt31());
            }
            return true;
        case XmlBinaryNodeType.Bytes32Text:
            if (_buffered)
            {
                ReadBinaryText(MoveToComplexText(), ReadUInt31());
            }
            else
            {
                ReadPartialBinaryText(withEndElement: false, ReadUInt31());
            }
            return true;
        case XmlBinaryNodeType.DictionaryTextWithEndElement:
            MoveToAtomicTextWithEndElement().Value.SetDictionaryValue(ReadDictionaryKey());
            return true;
        case XmlBinaryNodeType.UniqueIdTextWithEndElement:
            ReadText(MoveToAtomicTextWithEndElement(), ValueHandleType.UniqueId, 16);
            return true;
        case XmlBinaryNodeType.GuidTextWithEndElement:
            ReadText(MoveToAtomicTextWithEndElement(), ValueHandleType.Guid, 16);
            return true;
        case XmlBinaryNodeType.DecimalTextWithEndElement:
            ReadText(MoveToAtomicTextWithEndElement(), ValueHandleType.Decimal, 16);
            return true;
        case XmlBinaryNodeType.Int8TextWithEndElement:
            ReadText(MoveToAtomicTextWithEndElement(), ValueHandleType.Int8, 1);
            return true;
        case XmlBinaryNodeType.Int16TextWithEndElement:
            ReadText(MoveToAtomicTextWithEndElement(), ValueHandleType.Int16, 2);
            return true;
        case XmlBinaryNodeType.Int32TextWithEndElement:
            ReadText(MoveToAtomicTextWithEndElement(), ValueHandleType.Int32, 4);
            return true;
        case XmlBinaryNodeType.Int64TextWithEndElement:
            ReadText(MoveToAtomicTextWithEndElement(), ValueHandleType.Int64, 8);
            return true;
        case XmlBinaryNodeType.UInt64TextWithEndElement:
            ReadText(MoveToAtomicTextWithEndElement(), ValueHandleType.UInt64, 8);
            return true;
        case XmlBinaryNodeType.FloatTextWithEndElement:
            ReadText(MoveToAtomicTextWithEndElement(), ValueHandleType.Single, 4);
            return true;
        case XmlBinaryNodeType.DoubleTextWithEndElement:
            ReadText(MoveToAtomicTextWithEndElement(), ValueHandleType.Double, 8);
            return true;
        case XmlBinaryNodeType.TimeSpanTextWithEndElement:
            ReadText(MoveToAtomicTextWithEndElement(), ValueHandleType.TimeSpan, 8);
            return true;
        case XmlBinaryNodeType.DateTimeTextWithEndElement:
            ReadText(MoveToAtomicTextWithEndElement(), ValueHandleType.DateTime, 8);
            return true;
        case XmlBinaryNodeType.QNameDictionaryTextWithEndElement:
            base.BufferReader.ReadQName(MoveToAtomicTextWithEndElement().Value);
            return true;
        case XmlBinaryNodeType.Array:
            ReadArray();
            return true;
        default:
            base.BufferReader.ReadValue(xmlBinaryNodeType, MoveToComplexText().Value);
            return true;
        }
    }
References System.Xml.XmlBinaryReader._arrayCount, System.Xml.XmlBinaryReader._arrayNodeType, System.Xml.XmlBinaryReader._arrayState, System.Xml.XmlBinaryReader._buffered, System.Xml.XmlBinaryReader._maxBytesPerRead, System.Xml.Dictionary, System.Xml.XmlBaseReader.EnterScope(), System.Xml.PrefixHandle.GetAlphaPrefix(), System.Xml.XmlBinaryReader.GetNodeType(), System.Xml.XmlBaseReader.LookupNamespace(), System.Xml.XmlBinaryReader.MoveToAtomicTextWithEndElement(), System.Xml.XmlBaseReader.MoveToComment(), System.Xml.XmlBaseReader.MoveToComplexText(), System.Xml.XmlBaseReader.MoveToEndElement(), System.Xml.XmlBaseReader.MoveToEndOfFile(), System.Xml.XmlBinaryReader.ReadArray(), System.Xml.XmlBinaryReader.ReadAttributes(), System.Xml.XmlBinaryReader.ReadBinaryText(), System.Xml.XmlBinaryReader.ReadDictionaryKey(), System.Xml.XmlBinaryReader.ReadDictionaryName(), System.Xml.XmlBinaryReader.ReadName(), System.Xml.XmlBinaryReader.ReadPartialBinaryText(), System.Xml.XmlBinaryReader.ReadPartialUTF8Text(), System.Xml.XmlBinaryReader.ReadText(), System.Xml.XmlBinaryReader.ReadUInt16(), System.Xml.XmlBinaryReader.ReadUInt31(), System.Xml.XmlBinaryReader.ReadUInt8(), System.Xml.XmlBinaryReader.ReadUnicodeText(), System.Xml.ValueHandle.SetDictionaryValue(), System.Xml.ValueHandle.SetValue(), System.Xml.XmlBinaryReader.SkipNodeType(), System.Xml.XmlBaseReader.XmlNode.Value, System.Xml.XmlBaseReader.Value, and System.Xml.XmlBinaryReader.VerifyWhitespace().
Referenced by System.Xml.XmlBinaryReader.Read(), System.Xml.XmlBinaryReader.ReadArray(), System.Xml.XmlBinaryReader.ReadTextWithEndElement(), and System.Xml.XmlBinaryReader.SkipArrayElements().