Terraria: Terraria.UI.Chat.ChatMessageContainer.Refresh
Refresh()
void Terraria.UI.Chat.ChatMessageContainer.Refresh () inline
Definition at line 58 of file ChatMessageContainer.cs.
    {
        if (!_prepared)
        {
            _prepared = true;
            int num = _widthLimitInPixels;
            if (num == -1)
            {
                num = Main.screenWidth - 320;
            }
            List<List<TextSnippet>> list = Utils.WordwrapStringSmart(OriginalText, _color, FontAssets.MouseText.Value, num, 10);
            _parsedText.Clear();
            for (int i = 0; i < list.Count; i++)
            {
                _parsedText.Add(list[i].ToArray());
            }
        }
    }
References Terraria.UI.Chat.ChatMessageContainer._color, Terraria.UI.Chat.ChatMessageContainer._parsedText, Terraria.UI.Chat.ChatMessageContainer._prepared, Terraria.UI.Chat.ChatMessageContainer._widthLimitInPixels, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Collections.Generic.Dictionary< TKey, TValue >.Clear(), Terraria.GameContent.FontAssets.MouseText, Terraria.UI.Chat.ChatMessageContainer.OriginalText, and Terraria.Utils.WordwrapStringSmart().
Referenced by Terraria.UI.Chat.ChatMessageContainer.SetContents(), and Terraria.UI.Chat.ChatMessageContainer.Update().