Terraria: System.Xml.XmlBinaryReader.ReadText
ReadText()
void System.Xml.XmlBinaryReader.ReadText (XmlTextNode textNode, ValueHandleType type, int length) inline private
Definition at line 978 of file XmlBinaryReader.cs.
    {
        int offset = base.BufferReader.ReadBytes(length);
        textNode.Value.SetValue(type, offset, length);
        if (base.OutsideRootElement)
        {
            VerifyWhitespace();
        }
    }
References System.Xml.Dictionary, System.length, System.offset, System.type, and System.Xml.XmlBinaryReader.VerifyWhitespace().
Referenced by System.Xml.XmlBinaryReader.ReadBinaryText(), System.Xml.XmlBinaryReader.ReadNode(), System.Xml.XmlBinaryReader.ReadPartialBinaryText(), System.Xml.XmlBinaryReader.ReadPartialUnicodeText(), System.Xml.XmlBinaryReader.ReadPartialUTF8Text(), and System.Xml.XmlBinaryReader.ReadUnicodeText().