Terraria: System.Xml.XmlBinaryReader.InsertNode
InsertNode()
void System.Xml.XmlBinaryReader.InsertNode (XmlBinaryNodeType nodeType, int length) inline private
Definition at line 1117 of file XmlBinaryReader.cs.
    {
        byte[] array = new byte[5]
        {
            (byte)nodeType,
            (byte)length,
            0,
            0,
            0
        };
        length >>= 8;
        array[2] = (byte)length;
        length >>= 8;
        array[3] = (byte)length;
        length >>= 8;
        array[4] = (byte)length;
        base.BufferReader.InsertBytes(array, 0, array.Length);
    }
References System.array, System.Xml.Dictionary, and System.length.
Referenced by System.Xml.XmlBinaryReader.ReadPartialBinaryText(), System.Xml.XmlBinaryReader.ReadPartialUnicodeText(), and System.Xml.XmlBinaryReader.ReadPartialUTF8Text().