Terraria: System.Xml.XmlBinaryReader.IsStartArray
IsStartArray() [1/4]
override bool System.Xml.XmlBinaryReader.IsStartArray ([NotNullWhen(true)] out Type type) inline
Definition at line 1277 of file XmlBinaryReader.cs.
    {
        type = null;
        if (_arrayState != ArrayState.Element)
        {
            return false;
        }
        switch (_arrayNodeType)
        {
        case XmlBinaryNodeType.BoolTextWithEndElement:
            type = typeof(bool);
            break;
        case XmlBinaryNodeType.Int16TextWithEndElement:
            type = typeof(short);
            break;
        case XmlBinaryNodeType.Int32TextWithEndElement:
            type = typeof(int);
            break;
        case XmlBinaryNodeType.Int64TextWithEndElement:
            type = typeof(long);
            break;
        case XmlBinaryNodeType.FloatTextWithEndElement:
            type = typeof(float);
            break;
        case XmlBinaryNodeType.DoubleTextWithEndElement:
            type = typeof(double);
            break;
        case XmlBinaryNodeType.DecimalTextWithEndElement:
            type = typeof(decimal);
            break;
        case XmlBinaryNodeType.DateTimeTextWithEndElement:
            type = typeof(DateTime);
            break;
        case XmlBinaryNodeType.GuidTextWithEndElement:
            type = typeof(Guid);
            break;
        case XmlBinaryNodeType.TimeSpanTextWithEndElement:
            type = typeof(TimeSpan);
            break;
        case XmlBinaryNodeType.UniqueIdTextWithEndElement:
            type = typeof(UniqueId);
            break;
        default:
            return false;
        }
        return true;
    }
References System.Xml.XmlBinaryReader._arrayNodeType, System.Xml.XmlBinaryReader._arrayState, System.Xml.Dictionary, and System.type.
Referenced by System.Xml.XmlBinaryReader.ReadArray(), System.Xml.XmlBinaryReader.ReadArray(), System.Xml.XmlBinaryReader.ReadArray(), System.Xml.XmlBinaryReader.ReadArray(), System.Xml.XmlBinaryReader.ReadArray(), System.Xml.XmlBinaryReader.ReadArray(), System.Xml.XmlBinaryReader.ReadArray(), System.Xml.XmlBinaryReader.ReadArray(), System.Xml.XmlBinaryReader.ReadArray(), System.Xml.XmlBinaryReader.ReadArray(), System.Xml.XmlBinaryReader.ReadArray(), System.Xml.XmlBinaryReader.ReadArray(), System.Xml.XmlBinaryReader.ReadArray(), System.Xml.XmlBinaryReader.ReadArray(), System.Xml.XmlBinaryReader.ReadArray(), System.Xml.XmlBinaryReader.ReadArray(), System.Xml.XmlBinaryReader.ReadArray(), System.Xml.XmlBinaryReader.ReadArray(), System.Xml.XmlBinaryReader.ReadArray(), and System.Xml.XmlBinaryReader.ReadArray().