Terraria: System.Xml.XmlBinaryReader.ReadUnicodeText
ReadUnicodeText()
void System.Xml.XmlBinaryReader.ReadUnicodeText (bool withEndElement, int length) inline private
Definition at line 1031 of file XmlBinaryReader.cs.
    {
        if (((uint)length & (true ? 1u : 0u)) != 0)
        {
            XmlExceptionHelper.ThrowInvalidBinaryFormat(this);
        }
        if (_buffered)
        {
            if (withEndElement)
            {
                ReadText(MoveToAtomicTextWithEndElement(), ValueHandleType.Unicode, length);
            }
            else
            {
                ReadText(MoveToComplexText(), ValueHandleType.Unicode, length);
            }
        }
        else
        {
            ReadPartialUnicodeText(withEndElement, length);
        }
    }
References System.Xml.XmlBinaryReader._buffered, System.Xml.Dictionary, System.length, System.Xml.XmlBinaryReader.MoveToAtomicTextWithEndElement(), System.Xml.XmlBaseReader.MoveToComplexText(), System.Xml.XmlBinaryReader.ReadPartialUnicodeText(), System.Xml.XmlBinaryReader.ReadText(), and System.Xml.XmlExceptionHelper.ThrowInvalidBinaryFormat().
Referenced by System.Xml.XmlBinaryReader.ReadNode().