Terraria: System.Xml.XmlBinaryReader.ReadElementContentAsGuid
ReadElementContentAsGuid()
override Guid System.Xml.XmlBinaryReader.ReadElementContentAsGuid () inline virtual
Reimplemented from System.Xml.XmlDictionaryReader.
Definition at line 282 of file XmlBinaryReader.cs.
    {
        if (base.Node.NodeType != XmlNodeType.Element)
        {
            MoveToStartElement();
        }
        if (CanOptimizeReadElementContent() && GetNodeType() == XmlBinaryNodeType.GuidTextWithEndElement)
        {
            SkipNodeType();
            Guid result = base.BufferReader.ReadGuid();
            ReadTextWithEndElement();
            return result;
        }
        return base.ReadElementContentAsGuid();
    }
References System.Xml.XmlBinaryReader.CanOptimizeReadElementContent(), System.Xml.Dictionary, System.Xml.XmlBinaryReader.GetNodeType(), System.Xml.XmlDictionaryReader.MoveToStartElement(), System.Xml.XmlBinaryReader.ReadTextWithEndElement(), and System.Xml.XmlBinaryReader.SkipNodeType().