Terraria: System.Runtime.Serialization.Json.JsonReaderDelegator.TryReadJsonDateTimeArray
TryReadJsonDateTimeArray()
bool System.Runtime.Serialization.Json.JsonReaderDelegator.TryReadJsonDateTimeArray (XmlObjectSerializerReadContext context, XmlDictionaryString itemName, XmlDictionaryString itemNamespace, int arrayLength, [NotNullWhen(true)] out DateTime[] array) inline package
Definition at line 231 of file JsonReaderDelegator.cs.
    {
        if (dictionaryReader == null || arrayLength != -1)
        {
            array = null;
            return false;
        }
        array = DateTimeArrayHelper.ReadArray(dictionaryReader, XmlDictionaryString.GetString(itemName), XmlDictionaryString.GetString(itemNamespace), GetArrayLengthQuota(context));
        context.IncrementItemCount(array.Length);
        return true;
    }
References System.array, System.Runtime.Serialization.Json.JsonReaderDelegator.DateTimeArrayHelper, System.Runtime.Serialization.Dictionary, System.Runtime.Serialization.XmlReaderDelegator.dictionaryReader, System.Runtime.Serialization.XmlReaderDelegator.GetArrayLengthQuota(), System.Xml.XmlDictionaryString.GetString(), System.Runtime.Serialization.XmlObjectSerializerContext.IncrementItemCount(), and System.Runtime.Serialization.Json.JsonReaderDelegator.DateTimeArrayJsonHelperWithString.ReadArray().
Referenced by System.Runtime.Serialization.Json.JsonReaderDelegator.TryReadDateTimeArray().