Terraria: System.Runtime.Serialization.Json.JsonReaderDelegator.ParseJsonDateInDefaultFormat
ParseJsonDateInDefaultFormat()
static DateTime System.Runtime.Serialization.Json.JsonReaderDelegator.ParseJsonDateInDefaultFormat (string originalDateTimeValue) inline static package
Definition at line 168 of file JsonReaderDelegator.cs.
    {
        string text = (string.IsNullOrEmpty(originalDateTimeValue) ? originalDateTimeValue : originalDateTimeValue.Trim());
        if (string.IsNullOrEmpty(text) || !text.StartsWith("/Date(", StringComparison.Ordinal) || !text.EndsWith(")/", StringComparison.Ordinal))
        {
            throw new FormatException(System.SR.Format(System.SR.JsonInvalidDateTimeString, originalDateTimeValue, "\\/Date(", ")\\/"));
        }
        string text2 = text.Substring(6, text.Length - 8);
        DateTimeKind dateTimeKind = DateTimeKind.Utc;
        int num = text2.IndexOf('+', 1);
        if (num == -1)
        {
            num = text2.IndexOf('-', 1);
        }
        if (num != -1)
        {
            dateTimeKind = DateTimeKind.Local;
            text2 = text2.Substring(0, num);
        }
        long num2;
        try
        {
            num2 = long.Parse(text2, CultureInfo.InvariantCulture);
        }
        catch (ArgumentException exception)
        {
            throw XmlExceptionHelper.CreateConversionException(text2, "Int64", exception);
        }
        catch (FormatException exception2)
        {
            throw XmlExceptionHelper.CreateConversionException(text2, "Int64", exception2);
        }
        catch (OverflowException exception3)
        {
            throw XmlExceptionHelper.CreateConversionException(text2, "Int64", exception3);
        }
        long ticks = num2 * 10000 + JsonGlobals.unixEpochTicks;
        try
        {
            DateTime dateTime = new DateTime(ticks, DateTimeKind.Utc);
            return dateTimeKind switch
            {
                DateTimeKind.Local => dateTime.ToLocalTime(),
                DateTimeKind.Unspecified => DateTime.SpecifyKind(dateTime.ToLocalTime(), DateTimeKind.Unspecified),
                _ => dateTime,
            };
        }
        catch (ArgumentException exception4)
        {
            throw XmlExceptionHelper.CreateConversionException(text2, "DateTime", exception4);
        }
    }
References System.Xml.XmlExceptionHelper.CreateConversionException(), System.DateTime, System.Runtime.Serialization.Dictionary, System.exception, System.SR.Format(), System.Globalization.CultureInfo.InvariantCulture, System.SR.JsonInvalidDateTimeString, System.DateTime.SpecifyKind(), System.text, and System.Runtime.Serialization.Json.JsonGlobals.unixEpochTicks.
Referenced by System.Runtime.Serialization.Json.JsonReaderDelegator.ParseJsonDate().