Terraria: Terraria.Social.WeGame.IPCMessage.BuildFrom
BuildFrom()
void Terraria.Social.WeGame.IPCMessage.BuildFrom (byte[] data) inline
Definition at line 20 of file IPCMessage.cs.
    {
        byte[] value = data.Take(4).ToArray();
        byte[] bytes = data.Skip(4).ToArray();
        _cmd = (IPCMessageType)BitConverter.ToInt32(value, 0);
        _jsonData = Encoding.UTF8.GetString(bytes);
    }
References Terraria.Social.WeGame.IPCMessage._cmd, Terraria.Social.WeGame.IPCMessage._jsonData, System.bytes, System.BitConverter.ToInt32(), System.Text.Encoding.UTF8, and System.value.
Referenced by Terraria.Social.WeGame.MessageDispatcherClient.OnDataArrive(), and Terraria.Social.WeGame.MessageDispatcherServer.OnDataArrive().