Terraria: System.Runtime.Serialization.Json.JsonReaderDelegator.ParseJsonDate
ParseJsonDate()
static DateTime System.Runtime.Serialization.Json.JsonReaderDelegator.ParseJsonDate (string originalDateTimeValue, DateTimeFormat dateTimeFormat) inline static package
Definition at line 159 of file JsonReaderDelegator.cs.
    {
        if (dateTimeFormat == null)
        {
            return ParseJsonDateInDefaultFormat(originalDateTimeValue);
        }
        return DateTime.ParseExact(originalDateTimeValue, dateTimeFormat.FormatString, dateTimeFormat.FormatProvider, dateTimeFormat.DateTimeStyles);
    }
References System.Runtime.Serialization.Dictionary, System.DateTime.ParseExact(), and System.Runtime.Serialization.Json.JsonReaderDelegator.ParseJsonDateInDefaultFormat().
Referenced by System.Runtime.Serialization.Json.JsonReaderDelegator.DateTimeArrayJsonHelperWithString.ReadArray(), System.Runtime.Serialization.Json.JsonReaderDelegator.ReadContentAsDateTime(), and System.Runtime.Serialization.Json.JsonReaderDelegator.ReadElementContentAsDateTime().