Terraria: System.Runtime.Serialization.Json.JsonReaderDelegator.ReadElementContentAsBase64
ReadElementContentAsBase64()
override byte[] System.Runtime.Serialization.Json.JsonReaderDelegator.ReadElementContentAsBase64 () inline package virtual
Reimplemented from System.Runtime.Serialization.XmlReaderDelegator.
Definition at line 133 of file JsonReaderDelegator.cs.
    {
        if (isEndOfEmptyElement)
        {
            throw new XmlException(System.SR.Format(System.SR.XmlStartElementExpected, "EndElement"));
        }
        byte[] result;
        if (reader.IsStartElement() && reader.IsEmptyElement)
        {
            reader.Read();
            result = Array.Empty<byte>();
        }
        else
        {
            reader.ReadStartElement();
            result = ReadContentAsBase64();
            reader.ReadEndElement();
        }
        return result;
    }
References System.SR.Format(), System.Xml.XmlReader.IsEmptyElement, System.Runtime.Serialization.XmlReaderDelegator.isEndOfEmptyElement, System.Xml.XmlReader.IsStartElement(), System.Xml.XmlReader.Read(), System.Runtime.Serialization.Json.JsonReaderDelegator.ReadContentAsBase64(), System.Xml.XmlReader.ReadEndElement(), System.Runtime.Serialization.XmlReaderDelegator.reader, System.Xml.XmlReader.ReadStartElement(), System.Xml.XmlException, and System.SR.XmlStartElementExpected.