Terraria: System.Runtime.Serialization.Json.JsonReaderDelegator.ReadContentAsUnsignedLong
ReadContentAsUnsignedLong()
override ulong System.Runtime.Serialization.Json.JsonReaderDelegator.ReadContentAsUnsignedLong () inline package virtual
Reimplemented from System.Runtime.Serialization.XmlReaderDelegator.
Definition at line 243 of file JsonReaderDelegator.cs.
    {
        string text = reader.ReadContentAsString();
        if (text == null || text.Length == 0)
        {
            throw new XmlException(XmlObjectSerializer.TryAddLineInfo(this, System.SR.Format(System.SR.XmlInvalidConversion, text, "UInt64")));
        }
        try
        {
            return ulong.Parse(text, NumberStyles.Float, NumberFormatInfo.InvariantInfo);
        }
        catch (ArgumentException exception)
        {
            throw XmlExceptionHelper.CreateConversionException(text, "UInt64", exception);
        }
        catch (FormatException exception2)
        {
            throw XmlExceptionHelper.CreateConversionException(text, "UInt64", exception2);
        }
        catch (OverflowException exception3)
        {
            throw XmlExceptionHelper.CreateConversionException(text, "UInt64", exception3);
        }
    }
References System.Xml.XmlExceptionHelper.CreateConversionException(), System.Runtime.Serialization.Dictionary, System.exception, System.SR.Format(), System.Globalization.NumberFormatInfo.InvariantInfo, System.Xml.XmlReader.ReadContentAsString(), System.Runtime.Serialization.XmlReaderDelegator.reader, System.text, System.Runtime.Serialization.XmlObjectSerializer.TryAddLineInfo(), System.Xml.XmlException, and System.SR.XmlInvalidConversion.