Terraria: System.Runtime.Intrinsics.Vector256.Equals
Equals() [3/3]
bool System.Runtime.Intrinsics.Vector256< T >.Equals (Vector256< T > other) inline
Definition at line 1063 of file Vector256.cs.
    {
        if (Avx.IsSupported)
        {
            if (typeof(T) == typeof(float))
            {
                Vector256<float> value = Avx.Compare(this.AsSingle(), other.AsSingle(), FloatComparisonMode.OrderedEqualNonSignaling);
                return Avx.MoveMask(value) == 255;
            }
            if (typeof(T) == typeof(double))
            {
                Vector256<double> value2 = Avx.Compare(this.AsDouble(), other.AsDouble(), FloatComparisonMode.OrderedEqualNonSignaling);
                return Avx.MoveMask(value2) == 15;
            }
        }
        if (Avx2.IsSupported)
        {
            Vector256<byte> value3 = Avx2.CompareEqual(this.AsByte(), other.AsByte());
            return Avx2.MoveMask(value3) == -1;
        }
        return SoftwareFallback(in this, other);
        static bool SoftwareFallback(in Vector256<T> vector, Vector256<T> other)
        {
            for (int i = 0; i < Count; i++)
            {
                if (!((IEquatable<T>)(object)vector.GetElement(i)).Equals(other.GetElement(i)))
                {
                    return false;
                }
            }
            return true;
        }
    }
References System.Runtime.Intrinsics.X86.Avx.Compare(), System.Runtime.Intrinsics.X86.Avx2.CompareEqual(), System.Runtime.Intrinsics.Vector256< T >.Count, System.Runtime.Intrinsics.X86.Avx.IsSupported, System.Runtime.Intrinsics.X86.Avx2.IsSupported, System.Runtime.Intrinsics.X86.Avx.MoveMask(), System.Runtime.Intrinsics.X86.Avx2.MoveMask(), System.other, and System.value.
Referenced by System.Runtime.Intrinsics.Vector256< T >.Equals().