Terraria: System.Runtime.Intrinsics.Vector256.ToString
ToString()
override string System.Runtime.Intrinsics.Vector256< T >.ToString () inline
Definition at line 1117 of file Vector256.cs.
    {
        ThrowHelper.ThrowForUnsupportedIntrinsicsVectorBaseType<T>();
        int num = Count - 1;
        Span<char> initialBuffer = stackalloc char[64];
        ValueStringBuilder valueStringBuilder = new ValueStringBuilder(initialBuffer);
        CultureInfo invariantCulture = CultureInfo.InvariantCulture;
        valueStringBuilder.Append('<');
        for (int i = 0; i < num; i++)
        {
            valueStringBuilder.Append(((IFormattable)(object)this.GetElement(i)).ToString("G", invariantCulture));
            valueStringBuilder.Append(',');
            valueStringBuilder.Append(' ');
        }
        valueStringBuilder.Append(((IFormattable)(object)this.GetElement(num)).ToString("G", invariantCulture));
        valueStringBuilder.Append('>');
        return valueStringBuilder.ToString();
    }
References System.Text.ValueStringBuilder.Append(), System.Runtime.Intrinsics.Vector256< T >.Count, System.Globalization.CultureInfo.InvariantCulture, System.Text.ValueStringBuilder.ToString(), and System.Runtime.Intrinsics.Vector256< T >.ToString().
Referenced by System.Runtime.Intrinsics.Vector256< T >.ToString().