Terraria: System.ComponentModel.TypeDescriptionProvider.GetFullComponentName
GetFullComponentName()
virtual ? string System.ComponentModel.TypeDescriptionProvider.GetFullComponentName (object component) inline virtual inherited
Reimplemented in System.ComponentModel.DelegatingTypeDescriptionProvider, System.ComponentModel.ReflectTypeDescriptionProvider, and System.ComponentModel.TypeDescriptor.TypeDescriptionNode.
Definition at line 67 of file TypeDescriptionProvider.cs.
    {
        if (_parent != null)
        {
            return _parent.GetFullComponentName(component);
        }
        return GetTypeDescriptor(component)?.GetComponentName();
    }
References System.ComponentModel.TypeDescriptionProvider._parent, System.ComponentModel.ICustomTypeDescriptor.GetComponentName(), System.ComponentModel.TypeDescriptionProvider.GetFullComponentName(), and System.ComponentModel.TypeDescriptionProvider.GetTypeDescriptor().
Referenced by System.ComponentModel.TypeDescriptionProvider.GetFullComponentName().