Terraria: System.ComponentModel.TypeDescriptionProvider.GetRuntimeType
GetRuntimeType()
virtual Type System.ComponentModel.TypeDescriptionProvider.GetRuntimeType (Type reflectionType) inline virtual inherited
Reimplemented in System.ComponentModel.DelegatingTypeDescriptionProvider, and System.ComponentModel.TypeDescriptor.TypeDescriptionNode.
Definition at line 102 of file TypeDescriptionProvider.cs.
    {
        if (_parent != null)
        {
            return _parent.GetRuntimeType(reflectionType);
        }
        if (reflectionType == null)
        {
            throw new ArgumentNullException("reflectionType");
        }
        if (reflectionType.GetType().Assembly == typeof(object).Assembly)
        {
            return reflectionType;
        }
        return reflectionType.UnderlyingSystemType;
    }
References System.ComponentModel.TypeDescriptionProvider._parent, System.Assembly, System.ComponentModel.TypeDescriptionProvider.GetRuntimeType(), System.Type.GetType(), and System.Type.UnderlyingSystemType.
Referenced by System.ComponentModel.TypeDescriptionProvider.GetRuntimeType().