Terraria: System.Data.DataViewSettingCollection.CopyTo
CopyTo() [1/2]
void System.Data.DataViewSettingCollection.CopyTo (Array ar, int index) inline
Implements System.Collections.ICollection.
Definition at line 153 of file DataViewSettingCollection.cs.
    {
        IEnumerator enumerator = GetEnumerator();
        while (enumerator.MoveNext())
        {
            ar.SetValue(enumerator.Current, index++);
        }
    }
References System.Collections.IEnumerator.Current, System.Data.DataViewSettingCollection.GetEnumerator(), System.index, System.Collections.IEnumerator.MoveNext(), and System.Array.SetValue().