Terraria: System.Xml.Xsl.XsltOld.XsltCompileContext.FuncFormatNumber.Invoke
Invoke()
override object System.Xml.Xsl.XsltOld.XsltCompileContext.FuncFormatNumber.Invoke (XsltContext xsltContext, object[] args, XPathNavigator docContext) inline
Implements System.Xml.Xsl.IXsltContextFunction.
Definition at line 355 of file XsltCompileContext.cs.
        {
            DecimalFormat decimalFormat = ((XsltCompileContext)xsltContext).ResolveFormatName((args.Length == 3) ? XsltFunctionImpl.ToString(args[2]) : null);
            return DecimalFormatter.Format(XsltFunctionImpl.ToNumber(args[0]), XsltFunctionImpl.ToString(args[1]), decimalFormat);
        }
References System.Xml.Xsl.XsltOld.XsltCompileContext.XsltCompileContext(), System.Xml.Dictionary, System.Xml.Xsl.Runtime.DecimalFormatter.Format(), System.Xml.Xsl.XsltOld.XsltCompileContext.XsltFunctionImpl.ToNumber(), and System.Xml.Xsl.XsltOld.XsltCompileContext.XsltFunctionImpl.ToString().