Terraria: System.Linq.Expressions.Interpreter.ByRefMethodInfoCallInstruction.Run
Run()
override int System.Linq.Expressions.Interpreter.ByRefMethodInfoCallInstruction.Run (InterpretedFrame frame) inline sealed
Definition at line 28 of file ByRefMethodInfoCallInstruction.cs.
    {
        int num = frame.StackIndex - _argumentCount;
        object[] array = null;
        object obj = null;
        try
        {
            object obj2;
            if (_target.IsStatic)
            {
                array = GetArgs(frame, num, 0);
                try
                {
                    obj2 = _target.Invoke(null, array);
                }
                catch (TargetInvocationException exception)
                {
                    ExceptionHelpers.UnwrapAndRethrow(exception);
                    throw ContractUtils.Unreachable;
                }
            }
            else
            {
                obj = frame.Data[num];
                Instruction.NullCheck(obj);
                array = GetArgs(frame, num, 1);
                if (CallInstruction.TryGetLightLambdaTarget(obj, out var lightLambda))
                {
                    obj2 = InterpretLambdaInvoke(lightLambda, array);
                }
                else
                {
                    try
                    {
                        obj2 = _target.Invoke(obj, array);
                    }
                    catch (TargetInvocationException exception2)
                    {
                        ExceptionHelpers.UnwrapAndRethrow(exception2);
                        throw ContractUtils.Unreachable;
                    }
                }
            }
            if (_target.ReturnType != typeof(void))
            {
                frame.Data[num] = obj2;
                frame.StackIndex = num + 1;
            }
            else
            {
                frame.StackIndex = num;
            }
        }
        finally
        {
            if (array != null)
            {
                ByRefUpdater[] byrefArgs = _byrefArgs;
                foreach (ByRefUpdater byRefUpdater in byrefArgs)
                {
                    byRefUpdater.Update(frame, (byRefUpdater.ArgumentIndex == -1) ? obj : array[byRefUpdater.ArgumentIndex]);
                }
            }
        }
        return 1;
    }
References System.Linq.Expressions.Interpreter.MethodInfoCallInstruction._argumentCount, System.Linq.Expressions.Interpreter.ByRefMethodInfoCallInstruction._byrefArgs, System.Linq.Expressions.Interpreter.MethodInfoCallInstruction._target, System.Linq.Expressions.Interpreter.ByRefUpdater.ArgumentIndex, System.array, System.Linq.Expressions.Interpreter.InterpretedFrame.Data, System.exception, System.Linq.Expressions.Interpreter.MethodInfoCallInstruction.GetArgs(), System.Linq.Expressions.Interpreter.CallInstruction.InterpretLambdaInvoke(), System.Reflection.MethodBase.Invoke(), System.Reflection.MethodBase.IsStatic, System.Linq.Expressions.Interpreter.Instruction.NullCheck(), System.obj, System.Reflection.MethodInfo.ReturnType, System.Linq.Expressions.Interpreter.CallInstruction.TryGetLightLambdaTarget(), System.Dynamic.Utils.ContractUtils.Unreachable, System.Linq.Expressions.Interpreter.ExceptionHelpers.UnwrapAndRethrow(), and System.Linq.Expressions.Interpreter.ByRefUpdater.Update().