Terraria: Terraria.GameContent.UI.Elements.UIAchievementListItem.DrawProgressBar
DrawProgressBar()
void Terraria.GameContent.UI.Elements.UIAchievementListItem.DrawProgressBar (SpriteBatch spriteBatch, float progress, Vector2 spot, float Width = 169f, Color BackColor = default(Color), Color FillingColor = default(Color), Color BlipColor = default(Color)) inline private
Definition at line 227 of file UIAchievementListItem.cs.
    {
        if (BlipColor == Color.Transparent)
        {
            BlipColor = new Color(255, 165, 0, 127);
        }
        if (FillingColor == Color.Transparent)
        {
            FillingColor = new Color(255, 241, 51);
        }
        if (BackColor == Color.Transparent)
        {
            FillingColor = new Color(255, 255, 255);
        }
        Texture2D value = TextureAssets.ColorBar.Value;
        _ = TextureAssets.ColorBlip.Value;
        Texture2D value2 = TextureAssets.MagicPixel.Value;
        float num = MathHelper.Clamp(progress, 0f, 1f);
        float num2 = Width * 1f;
        float num3 = 8f;
        float num4 = num2 / 169f;
        Vector2 position = spot + Vector2.UnitY * num3 + Vector2.UnitX * 1f;
        spriteBatch.Draw(value, spot, new Rectangle(5, 0, value.Width - 9, value.Height), BackColor, 0f, new Vector2(84.5f, 0f), new Vector2(num4, 1f), SpriteEffects.None, 0f);
        spriteBatch.Draw(value, spot + new Vector2((0f - num4) * 84.5f - 5f, 0f), new Rectangle(0, 0, 5, value.Height), BackColor, 0f, Vector2.Zero, Vector2.One, SpriteEffects.None, 0f);
        spriteBatch.Draw(value, spot + new Vector2(num4 * 84.5f, 0f), new Rectangle(value.Width - 4, 0, 4, value.Height), BackColor, 0f, Vector2.Zero, Vector2.One, SpriteEffects.None, 0f);
        position += Vector2.UnitX * (num - 0.5f) * num2;
        position.X -= 1f;
        spriteBatch.Draw(value2, position, new Rectangle(0, 0, 1, 1), FillingColor, 0f, new Vector2(1f, 0.5f), new Vector2(num2 * num, num3), SpriteEffects.None, 0f);
        if (progress != 0f)
        {
            spriteBatch.Draw(value2, position, new Rectangle(0, 0, 1, 1), BlipColor, 0f, new Vector2(1f, 0.5f), new Vector2(2f, num3), SpriteEffects.None, 0f);
        }
        spriteBatch.Draw(value2, position, new Rectangle(0, 0, 1, 1), Color.Black, 0f, new Vector2(0f, 0.5f), new Vector2(num2 * (1f - num), num3), SpriteEffects.None, 0f);
    }
References Microsoft.Xna.Framework.Color.Black, Microsoft.Xna.Framework.MathHelper.Clamp(), Microsoft.Xna.Framework.Graphics.Color, Terraria.GameContent.TextureAssets.ColorBar, Terraria.GameContent.TextureAssets.ColorBlip, Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(), Terraria.GameContent.TextureAssets.MagicPixel, Microsoft.Xna.Framework.Vector2.One, Microsoft.Xna.Framework.Color.Transparent, System.value, Microsoft.Xna.Framework.Graphics.Vector2, Terraria.UI.UIElement.Width, and Microsoft.Xna.Framework.Vector2.Zero.
Referenced by Terraria.GameContent.UI.Elements.UIAchievementListItem.DrawSelf().