Terraria: System.Collections.BitArray.Set
Set()
void System.Collections.BitArray.Set (int index, bool value) inline
Definition at line 326 of file BitArray.cs.
    {
        if ((uint)index >= (uint)m_length)
        {
            ThrowArgumentOutOfRangeException(index);
        }
        int num = 1 << index;
        ref int reference = ref m_array[index >> 5];
        if (value)
        {
            reference |= num;
        }
        else
        {
            reference &= ~num;
        }
        _version++;
    }
References System.Collections.BitArray._version, System.index, System.Collections.BitArray.m_array, System.Collections.BitArray.m_length, System.Collections.BitArray.ThrowArgumentOutOfRangeException(), and System.value.
Referenced by System.Xml.Xsl.Qil.QilPatternVisitor.QilPatterns.Add(), System.Data.Common.DataStorage.CopyBits(), System.Data.Common.BigIntegerStorage.CopyValue(), System.Data.Common.StringStorage.CopyValue(), System.Security.Cryptography.EccKeyFormatHelper.GetSpecifiedECCurveCore(), System.Security.Cryptography.EccKeyFormatHelper.GetSpecifiedECCurveCore(), and System.Data.Common.DataStorage.SetNullBit().