Terraria: Terraria.GameContent.UI.Elements.UIAchievementListItem.GetTrackerValues
GetTrackerValues()
Tuple< decimal, decimal > Terraria.GameContent.UI.Elements.UIAchievementListItem.GetTrackerValues () inline private
Definition at line 207 of file UIAchievementListItem.cs.
    {
        if (!_achievement.HasTracker)
        {
            return Tuple.Create(0m, 0m);
        }
        IAchievementTracker tracker = _achievement.GetTracker();
        if (tracker.GetTrackerType() == TrackerType.Int)
        {
            AchievementTracker<int> achievementTracker = (AchievementTracker<int>)tracker;
            return Tuple.Create((decimal)achievementTracker.Value, (decimal)achievementTracker.MaxValue);
        }
        if (tracker.GetTrackerType() == TrackerType.Float)
        {
            AchievementTracker<float> achievementTracker2 = (AchievementTracker<float>)tracker;
            return Tuple.Create((decimal)achievementTracker2.Value, (decimal)achievementTracker2.MaxValue);
        }
        return Tuple.Create(0m, 0m);
    }
References Terraria.GameContent.UI.Elements.UIAchievementListItem._achievement, Terraria.Achievements.Achievement.GetTracker(), Terraria.Achievements.IAchievementTracker.GetTrackerType(), Terraria.Achievements.Achievement.HasTracker, Terraria.Achievements.AchievementTracker< T >.MaxValue, and Terraria.Achievements.AchievementTracker< T >.Value.
Referenced by Terraria.GameContent.UI.Elements.UIAchievementListItem.DrawSelf().