Terraria: System.Collections.BitArray.SetAll
SetAll()
void System.Collections.BitArray.SetAll (bool value) inline
Definition at line 345 of file BitArray.cs.
    {
        int int32ArrayLengthFromBitLength = GetInt32ArrayLengthFromBitLength(Length);
        Span<int> span = m_array.AsSpan(0, int32ArrayLengthFromBitLength);
        if (value)
        {
            span.Fill(-1);
            Div32Rem(m_length, out var remainder);
            if (remainder > 0)
            {
                span[span.Length - 1] &= (1 << remainder) - 1;
            }
        }
        else
        {
            span.Clear();
        }
        _version++;
    }
References System.Collections.BitArray._version, System.Span< T >.Clear(), System.Collections.BitArray.Div32Rem(), System.Span< T >.Fill(), System.Collections.BitArray.GetInt32ArrayLengthFromBitLength(), System.Collections.BitArray.Length, System.Collections.BitArray.m_array, System.Collections.BitArray.m_length, and System.value.