Terraria: System.Collections.BitArray.Div32Rem
Div32Rem()
static int System.Collections.BitArray.Div32Rem (int number, out int remainder) inline static private
Definition at line 1003 of file BitArray.cs.
    {
        uint result = (uint)number / 32u;
        remainder = number & 0x1F;
        return (int)result;
    }
Referenced by System.Collections.BitArray.BitArray(), System.Collections.BitArray.BitArray(), System.Collections.BitArray.CopyTo(), System.Collections.BitArray.LeftShift(), System.Collections.BitArray.RightShift(), and System.Collections.BitArray.SetAll().