Terraria: System.Xml.Serialization.XmlSerializationPrimitiveWriter.Write_dateTimeOffset
Write_dateTimeOffset()
void System.Xml.Serialization.XmlSerializationPrimitiveWriter.Write_dateTimeOffset (object o) inline package
Definition at line 122 of file XmlSerializationPrimitiveWriter.cs.
    {
        WriteStartDocument();
        if (o == null)
        {
            WriteEmptyTag("dateTimeOffset", "");
            return;
        }
        DateTimeOffset dateTimeOffset = (DateTimeOffset)o;
        WriteElementStringRaw("dateTimeOffset", "", XmlConvert.ToString(dateTimeOffset));
    }
References System.Xml.Dictionary, System.Xml.XmlConvert.ToString(), System.Xml.Serialization.XmlSerializationWriter.WriteElementStringRaw(), System.Xml.Serialization.XmlSerializationWriter.WriteEmptyTag(), and System.Xml.Serialization.XmlSerializationWriter.WriteStartDocument().