Terraria: System.Collections.BitArray.Xor
Xor()
unsafe BitArray System.Collections.BitArray.Xor (BitArray value) inline
Definition at line 559 of file BitArray.cs.
    {
        if (value == null)
        {
            throw new ArgumentNullException("value");
        }
        int[] array = m_array;
        int[] array2 = value.m_array;
        int int32ArrayLengthFromBitLength = GetInt32ArrayLengthFromBitLength(Length);
        if (Length != value.Length || (uint)int32ArrayLengthFromBitLength > (uint)array.Length || (uint)int32ArrayLengthFromBitLength > (uint)array2.Length)
        {
            throw new ArgumentException(System.SR.Arg_ArrayLengthsDiffer);
        }
        switch (int32ArrayLengthFromBitLength)
        {
        case 7:
            array[6] ^= array2[6];
            goto case 6;
        case 6:
            array[5] ^= array2[5];
            goto case 5;
        case 5:
            array[4] ^= array2[4];
            goto case 4;
        case 4:
            array[3] ^= array2[3];
            goto case 3;
        case 3:
            array[2] ^= array2[2];
            goto case 2;
        case 2:
            array[1] ^= array2[1];
            goto case 1;
        case 1:
            array[0] ^= array2[0];
            break;
        default:
        {
            uint num = 0u;
            if (Avx2.IsSupported)
            {
                fixed (int* ptr = m_array)
                {
                    fixed (int* ptr2 = value.m_array)
                    {
                        for (; num < (uint)(int32ArrayLengthFromBitLength - 7); num += 8)
{
                            Vector256<int> left = Avx.LoadVector256(ptr + num);
                            Vector256<int> right = Avx.LoadVector256(ptr2 + num);
                            Avx.Store(ptr + num, Avx2.Xor(left, right));
                        }
                    }
                }
            }
            else if (Sse2.IsSupported)
            {
                fixed (int* ptr3 = array)
                {
                    fixed (int* ptr4 = array2)
                    {
                        for (; num < (uint)(int32ArrayLengthFromBitLength - 3); num += 4)
{
                            Vector128<int> left2 = Sse2.LoadVector128(ptr3 + num);
                            Vector128<int> right2 = Sse2.LoadVector128(ptr4 + num);
                            Sse2.Store(ptr3 + num, Sse2.Xor(left2, right2));
                        }
                    }
                }
            }
            else if (AdvSimd.IsSupported)
            {
                fixed (int* ptr5 = array)
                {
                    fixed (int* ptr6 = array2)
                    {
                        for (; num < (uint)(int32ArrayLengthFromBitLength - 3); num += 4)
{
                            Vector128<int> left3 = AdvSimd.LoadVector128(ptr5 + num);
                            Vector128<int> right3 = AdvSimd.LoadVector128(ptr6 + num);
                            AdvSimd.Store(ptr5 + num, AdvSimd.Xor(left3, right3));
                        }
                    }
                }
            }
            for (; num < (uint)int32ArrayLengthFromBitLength; num++)
            {
                array[num] ^= array2[num];
            }
            break;
        }
        case 0:
            break;
        }
        _version++;
        return this;
    }
References System.Collections.BitArray._version, System.SR.Arg_ArrayLengthsDiffer, System.array, System.Collections.BitArray.GetInt32ArrayLengthFromBitLength(), System.Runtime.Intrinsics.Arm.AdvSimd.IsSupported, System.Runtime.Intrinsics.X86.Avx2.IsSupported, System.Runtime.Intrinsics.X86.Sse2.IsSupported, System.Collections.BitArray.Length, System.Runtime.Intrinsics.Arm.AdvSimd.LoadVector128(), System.Runtime.Intrinsics.X86.Sse2.LoadVector128(), System.Runtime.Intrinsics.X86.Avx.LoadVector256(), System.Collections.BitArray.m_array, System.Runtime.Intrinsics.Arm.AdvSimd.Store(), System.Runtime.Intrinsics.X86.Sse2.Store(), System.Runtime.Intrinsics.X86.Avx.Store(), System.value, System.Runtime.Intrinsics.X86.Sse2.Xor(), System.Runtime.Intrinsics.X86.Avx2.Xor(), and System.Runtime.Intrinsics.Arm.AdvSimd.Xor().