Terraria: System.Collections.BitArray.LeftShift
LeftShift()
BitArray System.Collections.BitArray.LeftShift (int count) inline
Definition at line 778 of file BitArray.cs.
    {
        if (count <= 0)
        {
            if (count < 0)
            {
                throw new ArgumentOutOfRangeException("count", count, System.SR.ArgumentOutOfRange_NeedNonNegNum);
            }
            _version++;
            return this;
        }
        int num2;
        if (count < m_length)
        {
            int num = m_length - 1 >> 5;
            num2 = Div32Rem(count, out var remainder);
            if (remainder == 0)
            {
                Array.Copy(m_array, 0, m_array, num2, num + 1 - num2);
            }
            else
            {
                int num3 = num - num2;
                while (num3 > 0)
                {
                    int num4 = m_array[num3] << remainder;
                    uint num5 = (uint)m_array[--num3] >> 32 - remainder;
                    m_array[num] = num4 | (int)num5;
                    num--;
                }
                m_array[num] = m_array[num3] << remainder;
            }
        }
        else
        {
            num2 = GetInt32ArrayLengthFromBitLength(m_length);
        }
        m_array.AsSpan(0, num2).Clear();
        _version++;
        return this;
    }
References System.Collections.BitArray._version, System.SR.ArgumentOutOfRange_NeedNonNegNum, System.Array.Copy(), System.count, System.Collections.BitArray.Div32Rem(), System.Collections.BitArray.GetInt32ArrayLengthFromBitLength(), System.Collections.BitArray.m_array, and System.Collections.BitArray.m_length.