Terraria: System.Collections.BitArray.BitArray
BitArray() [4/6]
unsafe System.Collections.BitArray.BitArray (bool[] values) inline
Definition at line 200 of file BitArray.cs.
    {
        if (values == null)
        {
            throw new ArgumentNullException("values");
        }
        m_array = new int[GetInt32ArrayLengthFromBitLength(values.Length)];
        m_length = values.Length;
        uint num = 0u;
        if (values.Length >= Vector256<byte>.Count)
        {
            if (Avx2.IsSupported)
            {
                Vector256<byte> zero = Vector256<byte>.Zero;
                fixed (bool* ptr = values)
                {
                    for (; num + 32 <= (uint)values.Length; num += 32)
                    {
                        Vector256<byte> left = Avx.LoadVector256((byte*)(ptr + num));
                        Vector256<byte> value = Avx2.CompareEqual(left, zero);
                        int num2 = Avx2.MoveMask(value);
                        m_array[num / 32] = ~num2;
                    }
                }
            }
            else if (Sse2.IsSupported)
            {
                Vector128<byte> zero2 = Vector128<byte>.Zero;
                fixed (bool* ptr2 = values)
                {
                    for (; num + 32 <= (uint)values.Length; num += 32)
                    {
                        Vector128<byte> left2 = Sse2.LoadVector128((byte*)(ptr2 + num));
                        Vector128<byte> value2 = Sse2.CompareEqual(left2, zero2);
                        int num3 = Sse2.MoveMask(value2);
                        Vector128<byte> left3 = Sse2.LoadVector128((byte*)(ptr2 + num + Vector128<byte>.Count));
                        Vector128<byte> value3 = Sse2.CompareEqual(left3, zero2);
                        int num4 = Sse2.MoveMask(value3);
                        m_array[num / 32] = ~((num4 << 16) | num3);
                    }
                }
            }
            else if (AdvSimd.Arm64.IsSupported)
            {
                Vector128<byte> zero3 = Vector128<byte>.Zero;
                Vector128<byte> right = (BitConverter.IsLittleEndian ? Vector128.Create(9241421688590303745uL).AsByte() : Vector128.Create(72624976668147840L).AsByte());
                fixed (bool* ptr3 = values)
                {
                    for (; num + 32 <= (uint)values.Length; num += 32)
                    {
                        Vector128<byte> left4 = AdvSimd.LoadVector128((byte*)(ptr3 + num));
                        Vector128<byte> left5 = AdvSimd.CompareEqual(left4, zero3);
                        Vector128<byte> vector = AdvSimd.And(left5, right);
                        vector = AdvSimd.Arm64.AddPairwise(vector, vector);
                        vector = AdvSimd.Arm64.AddPairwise(vector, vector);
                        vector = AdvSimd.Arm64.AddPairwise(vector, vector);
                        Vector128<short> left6 = vector.AsInt16();
                        Vector128<byte> left7 = AdvSimd.LoadVector128((byte*)(ptr3 + num + Vector128<byte>.Count));
                        Vector128<byte> left8 = AdvSimd.CompareEqual(left7, zero3);
                        Vector128<byte> vector2 = AdvSimd.And(left8, right);
                        vector2 = AdvSimd.Arm64.AddPairwise(vector2, vector2);
                        vector2 = AdvSimd.Arm64.AddPairwise(vector2, vector2);
                        vector2 = AdvSimd.Arm64.AddPairwise(vector2, vector2);
                        Vector128<short> right2 = vector2.AsInt16();
                        int num5 = AdvSimd.Arm64.ZipLow(left6, right2).AsInt32().ToScalar();
                        if (!BitConverter.IsLittleEndian)
{
                            num5 = BinaryPrimitives.ReverseEndianness(num5);
                        }
                        m_array[num / 32] = ~num5;
                    }
                }
            }
        }
        for (; num < (uint)values.Length; num++)
        {
            if (values[num])
            {
                int remainder;
                int num6 = Div32Rem((int)num, out remainder);
                m_array[num6] |= 1 << remainder;
            }
        }
        _version = 0;
    }
References System.Collections.BitArray._version, System.Runtime.Intrinsics.Arm.AdvSimd.Arm64.AddPairwise(), System.Runtime.Intrinsics.Arm.AdvSimd.And(), System.Runtime.Intrinsics.X86.Sse2.CompareEqual(), System.Runtime.Intrinsics.X86.Avx2.CompareEqual(), System.Runtime.Intrinsics.Arm.AdvSimd.CompareEqual(), System.Runtime.Intrinsics.Vector128< T >.Count, System.Runtime.Intrinsics.Vector256< T >.Count, System.Runtime.Intrinsics.Vector128< T >.Create(), System.Collections.BitArray.Div32Rem(), System.Collections.BitArray.GetInt32ArrayLengthFromBitLength(), System.BitConverter.IsLittleEndian, System.Runtime.Intrinsics.Arm.AdvSimd.Arm64.IsSupported, System.Runtime.Intrinsics.X86.Avx2.IsSupported, System.Runtime.Intrinsics.X86.Sse2.IsSupported, System.L, System.Runtime.Intrinsics.Arm.AdvSimd.LoadVector128(), System.Runtime.Intrinsics.X86.Sse2.LoadVector128(), System.Runtime.Intrinsics.X86.Avx.LoadVector256(), System.Collections.BitArray.m_array, System.Collections.BitArray.m_length, System.Runtime.Intrinsics.X86.Sse2.MoveMask(), System.Runtime.Intrinsics.X86.Avx2.MoveMask(), System.Buffers.Binary.BinaryPrimitives.ReverseEndianness(), System.value, System.values, System.Runtime.Intrinsics.Vector128< T >.Zero, System.Runtime.Intrinsics.Vector256< T >.Zero, and System.Runtime.Intrinsics.Arm.AdvSimd.Arm64.ZipLow().