Terraria: System.Collections.BitArray.Get
Get()
bool System.Collections.BitArray.Get (int index) inline
Definition at line 316 of file BitArray.cs.
    {
        if ((uint)index >= (uint)m_length)
        {
            ThrowArgumentOutOfRangeException(index);
        }
        return (m_array[index >> 5] & (1 << index)) != 0;
    }
References System.index, System.Collections.BitArray.m_array, System.Collections.BitArray.m_length, and System.Collections.BitArray.ThrowArgumentOutOfRangeException().
Referenced by System.Data.Common.DataStorage.AggregateCount(), System.Data.Common.DataStorage.CompareBits(), System.Data.Common.DataStorage.CopyBits(), System.Data.Common.DataStorage.GetBits(), System.Data.Common.DataStorage.HasValue(), System.Data.Common.DataStorage.IsNull(), and System.Collections.BitArray.BitArrayEnumeratorSimple.MoveNext().