Terraria: Terraria.GameContent.UI.Elements.UIAchievementListItem.UIAchievementListItem
UIAchievementListItem()
Terraria.GameContent.UI.Elements.UIAchievementListItem.UIAchievementListItem (Achievement achievement, bool largeForOtherLanguages) inline
    {
        _large = largeForOtherLanguages;
        BackgroundColor = new Color(26, 40, 89) * 0.8f;
        BorderColor = new Color(13, 20, 44) * 0.8f;
        float num = 16 + _large.ToInt() * 20;
        float num2 = _large.ToInt() * 6;
        float num3 = _large.ToInt() * 12;
        _achievement = achievement;
        Height.Set(66f + num, 0f);
        Width.Set(0f, 1f);
        PaddingTop = 8f;
        PaddingLeft = 9f;
        int num4 = (_iconIndex = Main.Achievements.GetIconIndex(achievement.Name));
        _iconFrameUnlocked = new Rectangle(num4 % 8 * 66, num4 / 8 * 66, 64, 64);
        _iconFrameLocked = _iconFrameUnlocked;
        _iconFrameLocked.X += 528;
        _iconFrame = _iconFrameLocked;
        UpdateIconFrame();
        _achievementIcon = new UIImageFramed(Main.Assets.Request<Texture2D>("Images/UI/Achievements", (AssetRequestMode)1), _iconFrame);
        _achievementIcon.Left.Set(num2, 0f);
        _achievementIcon.Top.Set(num3, 0f);
        Append(_achievementIcon);
        _achievementIconBorders = new UIImage(Main.Assets.Request<Texture2D>("Images/UI/Achievement_Borders", (AssetRequestMode)1));
        _achievementIconBorders.Left.Set(-4f + num2, 0f);
        _achievementIconBorders.Top.Set(-4f + num3, 0f);
        Append(_achievementIconBorders);
        _innerPanelTopTexture = Main.Assets.Request<Texture2D>("Images/UI/Achievement_InnerPanelTop", (AssetRequestMode)1);
        if (_large)
        {
            _innerPanelBottomTexture = Main.Assets.Request<Texture2D>("Images/UI/Achievement_InnerPanelBottom_Large", (AssetRequestMode)1);
        }
        else
        {
            _innerPanelBottomTexture = Main.Assets.Request<Texture2D>("Images/UI/Achievement_InnerPanelBottom", (AssetRequestMode)1);
        }
        _categoryTexture = Main.Assets.Request<Texture2D>("Images/UI/Achievement_Categories", (AssetRequestMode)1);
    }
References Terraria.GameContent.UI.Elements.UIAchievementListItem._achievement, Terraria.GameContent.UI.Elements.UIAchievementListItem._achievementIcon, Terraria.GameContent.UI.Elements.UIAchievementListItem._achievementIconBorders, Terraria.GameContent.UI.Elements.UIAchievementListItem._categoryTexture, Terraria.GameContent.UI.Elements.UIAchievementListItem._iconFrame, Terraria.GameContent.UI.Elements.UIAchievementListItem._iconFrameLocked, Terraria.GameContent.UI.Elements.UIAchievementListItem._iconFrameUnlocked, Terraria.GameContent.UI.Elements.UIAchievementListItem._iconIndex, Terraria.GameContent.UI.Elements.UIAchievementListItem._innerPanelBottomTexture, Terraria.GameContent.UI.Elements.UIAchievementListItem._innerPanelTopTexture, Terraria.GameContent.UI.Elements.UIAchievementListItem._large, Terraria.Main.Achievements, Terraria.UI.UIElement.Append(), Terraria.Main.Assets, Terraria.GameContent.UI.Elements.UIPanel.BackgroundColor, Terraria.GameContent.UI.Elements.UIPanel.BorderColor, Terraria.UI.UIElement.Height, Terraria.UI.UIElement.Left, Terraria.Achievements.Achievement.Name, Terraria.UI.UIElement.PaddingLeft, Terraria.UI.UIElement.PaddingTop, Terraria.UI.StyleDimension.Set(), Terraria.UI.UIElement.Top, Terraria.GameContent.UI.Elements.UIAchievementListItem.UpdateIconFrame(), and Terraria.UI.UIElement.Width.