Terraria: System.Collections.BitArray.BitArray
BitArray() [3/6]
System.Collections.BitArray.BitArray (byte[] bytes) inline
Definition at line 165 of file BitArray.cs.
    {
        if (bytes == null)
        {
            throw new ArgumentNullException("bytes");
        }
        if (bytes.Length > 268435455)
        {
            throw new ArgumentException(System.SR.Format(System.SR.Argument_ArrayTooLarge, 8), "bytes");
        }
        m_array = new int[GetInt32ArrayLengthFromByteLength(bytes.Length)];
        m_length = bytes.Length * 8;
        uint num = (uint)bytes.Length / 4u;
        ReadOnlySpan<byte> source = bytes;
        for (int i = 0; i < num; i++)
        {
            m_array[i] = BinaryPrimitives.ReadInt32LittleEndian(source);
            source = source.Slice(4);
        }
        int num2 = 0;
        switch (source.Length)
        {
        case 3:
            num2 = source[2] << 16;
            goto case 2;
        case 2:
            num2 |= source[1] << 8;
            goto case 1;
        case 1:
            m_array[num] = num2 | source[0];
            break;
        }
        _version = 0;
    }
References System.Collections.BitArray._version, System.SR.Argument_ArrayTooLarge, System.bytes, System.SR.Format(), System.Collections.BitArray.GetInt32ArrayLengthFromByteLength(), System.Collections.BitArray.m_array, System.Collections.BitArray.m_length, System.Buffers.Binary.BinaryPrimitives.ReadInt32LittleEndian(), and System.source.