Terraria: System.Collections.BitArray.Not
Not()
unsafe BitArray System.Collections.BitArray.Not () inline
Definition at line 656 of file BitArray.cs.
    {
        int[] array = m_array;
        int int32ArrayLengthFromBitLength = GetInt32ArrayLengthFromBitLength(Length);
        switch (int32ArrayLengthFromBitLength)
        {
        case 7:
            array[6] = ~array[6];
            goto case 6;
        case 6:
            array[5] = ~array[5];
            goto case 5;
        case 5:
            array[4] = ~array[4];
            goto case 4;
        case 4:
            array[3] = ~array[3];
            goto case 3;
        case 3:
            array[2] = ~array[2];
            goto case 2;
        case 2:
            array[1] = ~array[1];
            goto case 1;
        case 1:
            array[0] = ~array[0];
            break;
        default:
        {
            uint num = 0u;
            if (Avx2.IsSupported)
            {
                Vector256<int> right = Vector256.Create(-1);
                fixed (int* ptr = array)
                {
                    for (; num < (uint)(int32ArrayLengthFromBitLength - 7); num += 8)
                    {
                        Vector256<int> left = Avx.LoadVector256(ptr + num);
                        Avx.Store(ptr + num, Avx2.Xor(left, right));
                    }
                }
            }
            else if (Sse2.IsSupported)
            {
                Vector128<int> right2 = Vector128.Create(-1);
                fixed (int* ptr2 = array)
                {
                    for (; num < (uint)(int32ArrayLengthFromBitLength - 3); num += 4)
                    {
                        Vector128<int> left2 = Sse2.LoadVector128(ptr2 + num);
                        Sse2.Store(ptr2 + num, Sse2.Xor(left2, right2));
                    }
                }
            }
            else if (AdvSimd.IsSupported)
            {
                fixed (int* ptr3 = array)
                {
                    for (; num < (uint)(int32ArrayLengthFromBitLength - 3); num += 4)
                    {
                        Vector128<int> value = AdvSimd.LoadVector128(ptr3 + num);
                        AdvSimd.Store(ptr3 + num, AdvSimd.Not(value));
                    }
                }
            }
            for (; num < (uint)int32ArrayLengthFromBitLength; num++)
            {
                array[num] = ~array[num];
            }
            break;
        }
        case 0:
            break;
        }
        _version++;
        return this;
    }
References System.Collections.BitArray._version, System.array, System.Runtime.Intrinsics.Vector128< T >.Create(), System.Runtime.Intrinsics.Vector256< T >.Create(), System.Collections.BitArray.GetInt32ArrayLengthFromBitLength(), System.Runtime.Intrinsics.Arm.AdvSimd.IsSupported, System.Runtime.Intrinsics.X86.Avx2.IsSupported, System.Runtime.Intrinsics.X86.Sse2.IsSupported, System.Collections.BitArray.Length, System.Runtime.Intrinsics.Arm.AdvSimd.LoadVector128(), System.Runtime.Intrinsics.X86.Sse2.LoadVector128(), System.Runtime.Intrinsics.X86.Avx.LoadVector256(), System.Collections.BitArray.m_array, System.Runtime.Intrinsics.Arm.AdvSimd.Not(), System.Runtime.Intrinsics.Arm.AdvSimd.Store(), System.Runtime.Intrinsics.X86.Sse2.Store(), System.Runtime.Intrinsics.X86.Avx.Store(), System.value, System.Runtime.Intrinsics.X86.Sse2.Xor(), and System.Runtime.Intrinsics.X86.Avx2.Xor().