Terraria: TileEntitiesManager.Register
Register()
void TileEntitiesManager.Register (TileEntity entity) inline
     {
         int num = AssignNewID();
         _types[num] = entity;
         entity.RegisterTileEntityID(num);
     }
References _types, AssignNewID(), and TileEntity.RegisterTileEntityID().
Referenced by RegisterAll().