Terraria: System.Attribute.InternalIsDefined
InternalIsDefined() [1/2]
static bool System.Attribute.InternalIsDefined (EventInfo element, Type attributeType, bool inherit) inline static private inherited
Definition at line 129 of file Attribute.cs.
    {
        if (element.IsDefined(attributeType, inherit))
        {
            return true;
        }
        if (inherit)
        {
            AttributeUsageAttribute attributeUsageAttribute = InternalGetAttributeUsage(attributeType);
            if (!attributeUsageAttribute.Inherited)
            {
                return false;
            }
            EventInfo parentDefinition = GetParentDefinition(element);
            while (parentDefinition != null)
            {
                if (parentDefinition.IsDefined(attributeType, inherit: false))
                {
                    return true;
                }
                parentDefinition = GetParentDefinition(parentDefinition);
            }
        }
        return false;
    }
References System.Attribute.GetParentDefinition(), System.Attribute.InternalGetAttributeUsage(), and System.Reflection.MemberInfo.IsDefined().