Terraria: System.Attribute.Equals
Equals()
override bool System.Attribute.Equals ([NotNullWhen(true)] object? obj) inline inherited
Definition at line 691 of file Attribute.cs.
    {
        if (obj == null)
        {
            return false;
        }
        if (GetType() != obj.GetType())
        {
            return false;
        }
        Type type = GetType();
        while (type != typeof(Attribute))
        {
            FieldInfo[] fields = type.GetFields(BindingFlags.DeclaredOnly | BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic);
            for (int i = 0; i < fields.Length; i++)
            {
                object value = fields[i].GetValue(this);
                object value2 = fields[i].GetValue(obj);
                if (!AreFieldValuesEqual(value, value2))
                {
                    return false;
                }
            }
            type = type.BaseType;
        }
        return true;
    }
References System.Attribute.AreFieldValuesEqual(), System.Reflection.FieldInfo.GetValue(), System.obj, System.type, and System.value.
Referenced by System.ComponentModel.TypeDescriptor.AttributeProvider.AttributeTypeDescriptor.GetAttributes(), System.ComponentModel.DataAnnotations.CompareAttribute.IsValid(), System.Attribute.Match(), and System.ComponentModel.DataAnnotations.CustomValidationAttribute.ValidateMethodParameter().