Terraria: System.Attribute.CopyToAttributeList
CopyToAttributeList()
static void System.Attribute.CopyToAttributeList (List< Attribute > attributeList, Attribute[] attributes, Dictionary< Type, AttributeUsageAttribute > types) inline static private inherited
Definition at line 270 of file Attribute.cs.
    {
        for (int i = 0; i < attributes.Length; i++)
        {
            attributeList.Add(attributes[i]);
            Type type = attributes[i].GetType();
            if (!types.ContainsKey(type))
            {
                types[type] = InternalGetAttributeUsage(type);
            }
        }
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Collections.Generic.Dictionary< TKey, TValue >.ContainsKey(), System.Attribute.InternalGetAttributeUsage(), and System.type.
Referenced by System.Attribute.InternalGetCustomAttributes(), and System.Attribute.InternalGetCustomAttributes().