Terraria: System.Attribute.InternalParamGetCustomAttributes
InternalParamGetCustomAttributes()
static Attribute[] System.Attribute.InternalParamGetCustomAttributes (ParameterInfo param, Type type, bool inherit) inline static private inherited
Definition at line 175 of file Attribute.cs.
    {
        List<Type> list = new List<Type>();
        if ((object)type == null)
        {
            type = typeof(Attribute);
        }
        object[] customAttributes = param.GetCustomAttributes(type, inherit: false);
        for (int i = 0; i < customAttributes.Length; i++)
        {
            Type type2 = customAttributes[i].GetType();
            AttributeUsageAttribute attributeUsageAttribute = InternalGetAttributeUsage(type2);
            if (!attributeUsageAttribute.AllowMultiple)
            {
                list.Add(type2);
            }
        }
        Attribute[] array = ((customAttributes.Length != 0) ? ((Attribute[])customAttributes) : CreateAttributeArrayHelper(type, 0));
        if ((object)param.Member.DeclaringType == null)
        {
            return array;
        }
        if (!inherit)
        {
            return array;
        }
        for (ParameterInfo parentDefinition = GetParentDefinition(param); parentDefinition != null; parentDefinition = GetParentDefinition(parentDefinition))
        {
            customAttributes = parentDefinition.GetCustomAttributes(type, inherit: false);
            int num = 0;
            for (int j = 0; j < customAttributes.Length; j++)
            {
                Type type3 = customAttributes[j].GetType();
                AttributeUsageAttribute attributeUsageAttribute2 = InternalGetAttributeUsage(type3);
                if (attributeUsageAttribute2.Inherited && !list.Contains(type3))
                {
                    if (!attributeUsageAttribute2.AllowMultiple)
                    {
                        list.Add(type3);
                    }
                    num++;
                }
                else
                {
                    customAttributes[j] = null;
                }
            }
            Attribute[] array2 = CreateAttributeArrayHelper(type, num);
            num = 0;
            foreach (object obj in customAttributes)
            {
                if (obj != null)
                {
                    array2[num] = (Attribute)obj;
                    num++;
                }
            }
            Attribute[] array3 = array;
            array = CreateAttributeArrayHelper(type, array3.Length + num);
            Array.Copy(array3, array, array3.Length);
            int num2 = array3.Length;
            for (int l = 0; l < array2.Length; l++)
            {
                array[num2 + l] = array2[l];
            }
        }
        return array;
    }
References System.array, System.Collections.Generic.Dictionary< TKey, TValue >.Contains(), System.Array.Copy(), System.Attribute.CreateAttributeArrayHelper(), System.Attribute.GetParentDefinition(), System.Attribute.InternalGetAttributeUsage(), System.list, System.obj, and System.type.
Referenced by System.Attribute.GetCustomAttributes(), and System.Attribute.GetCustomAttributes().