Terraria: System.Attribute.GetCustomAttributes
GetCustomAttributes() [7/16]
static Attribute[] System.Attribute.GetCustomAttributes (MemberInfo element, Type attributeType) inline static inherited
Definition at line 338 of file Attribute.cs.
    {
        return GetCustomAttributes(element, attributeType, inherit: true);
    }
References System.Attribute.GetCustomAttributes().
Referenced by System.ComponentModel.DataAnnotations.AssociatedMetadataTypeTypeDescriptor.TypeDescriptorCache.GetAssociatedMetadata(), ReLogic.Utilities.AttributeUtilities.GetAttribute< T >(), ReLogic.Utilities.AttributeUtilities.GetAttribute< T >(), System.Attribute.GetCustomAttribute(), System.Attribute.GetCustomAttribute(), System.Attribute.GetCustomAttribute(), System.Attribute.GetCustomAttribute(), System.Attribute.GetCustomAttributes(), System.Attribute.GetCustomAttributes(), System.Attribute.GetCustomAttributes(), System.Attribute.GetCustomAttributes(), System.Attribute.GetCustomAttributes(), System.Attribute.GetCustomAttributes(), System.Attribute.GetCustomAttributes(), System.Attribute.GetCustomAttributes(), System.Reflection.CustomAttributeExtensions.GetCustomAttributes(), System.Reflection.CustomAttributeExtensions.GetCustomAttributes(), System.Reflection.CustomAttributeExtensions.GetCustomAttributes(), System.Reflection.CustomAttributeExtensions.GetCustomAttributes(), System.Reflection.CustomAttributeExtensions.GetCustomAttributes(), System.Reflection.CustomAttributeExtensions.GetCustomAttributes(), System.Reflection.CustomAttributeExtensions.GetCustomAttributes(), System.Reflection.CustomAttributeExtensions.GetCustomAttributes(), System.Reflection.CustomAttributeExtensions.GetCustomAttributes(), System.Reflection.CustomAttributeExtensions.GetCustomAttributes(), System.Reflection.CustomAttributeExtensions.GetCustomAttributes(), System.Reflection.CustomAttributeExtensions.GetCustomAttributes(), System.Reflection.CustomAttributeExtensions.GetCustomAttributes< T >(), System.Reflection.CustomAttributeExtensions.GetCustomAttributes< T >(), System.Reflection.CustomAttributeExtensions.GetCustomAttributes< T >(), System.Reflection.CustomAttributeExtensions.GetCustomAttributes< T >(), System.Attribute.InternalGetCustomAttributes(), and System.Attribute.InternalGetCustomAttributes().