Terraria: System.Attribute.GetCustomAttributes
GetCustomAttributes() [8/16]
static Attribute[] System.Attribute.GetCustomAttributes (MemberInfo element, Type attributeType, bool inherit) inline static inherited
Definition at line 343 of file Attribute.cs.
    {
        if (element == null)
        {
            throw new ArgumentNullException("element");
        }
        if (attributeType == null)
        {
            throw new ArgumentNullException("attributeType");
        }
        if (!attributeType.IsSubclassOf(typeof(Attribute)) && attributeType != typeof(Attribute))
        {
            throw new ArgumentException(SR.Argument_MustHaveAttributeBaseClass);
        }
        return element.MemberType switch
        {
            MemberTypes.Property => InternalGetCustomAttributes((PropertyInfo)element, attributeType, inherit),
            MemberTypes.Event => InternalGetCustomAttributes((EventInfo)element, attributeType, inherit),
            _ => element.GetCustomAttributes(attributeType, inherit) as Attribute[],
        };
    }
References System.SR.Argument_MustHaveAttributeBaseClass, System.Reflection.MemberInfo.GetCustomAttributes(), System.Attribute.InternalGetCustomAttributes(), and System.Type.IsSubclassOf().