Terraria: System.Attribute.GetCustomAttributes
GetCustomAttributes() [16/16]
static Attribute[] System.Attribute.GetCustomAttributes (ParameterInfo element, Type attributeType, bool inherit) inline static inherited
Definition at line 440 of file Attribute.cs.
    {
        if (element == null)
        {
            throw new ArgumentNullException("element");
        }
        if (attributeType == null)
        {
            throw new ArgumentNullException("attributeType");
        }
        if (!attributeType.IsSubclassOf(typeof(Attribute)) && attributeType != typeof(Attribute))
        {
            throw new ArgumentException(SR.Argument_MustHaveAttributeBaseClass);
        }
        if (element.Member == null)
        {
            throw new ArgumentException(SR.Argument_InvalidParameterInfo, "element");
        }
        MemberInfo member = element.Member;
        if (member.MemberType == MemberTypes.Method && inherit)
        {
            return InternalParamGetCustomAttributes(element, attributeType, inherit);
        }
        return element.GetCustomAttributes(attributeType, inherit) as Attribute[];
    }
References System.SR.Argument_InvalidParameterInfo, System.SR.Argument_MustHaveAttributeBaseClass, System.Reflection.ParameterInfo.GetCustomAttributes(), System.Attribute.InternalParamGetCustomAttributes(), System.Type.IsSubclassOf(), System.Reflection.ParameterInfo.Member, and System.Reflection.MemberInfo.MemberType.