Terraria: System.Attribute.InternalGetCustomAttributes
InternalGetCustomAttributes() [1/2]
static Attribute[] System.Attribute.InternalGetCustomAttributes (EventInfo element, Type type, bool inherit) inline static private inherited
Definition at line 86 of file Attribute.cs.
    {
        Attribute[] array = (Attribute[])element.GetCustomAttributes(type, inherit);
        if (!inherit)
        {
            return array;
        }
        EventInfo parentDefinition = GetParentDefinition(element);
        if (parentDefinition == null)
        {
            return array;
        }
        Dictionary<Type, AttributeUsageAttribute> types = new Dictionary<Type, AttributeUsageAttribute>(11);
        List<Attribute> list = new List<Attribute>();
        CopyToAttributeList(list, array, types);
        do
        {
            array = GetCustomAttributes(parentDefinition, type, inherit: false);
            AddAttributesToList(list, array, types);
            parentDefinition = GetParentDefinition(parentDefinition);
        }
        while (parentDefinition != null);
        Attribute[] array2 = CreateAttributeArrayHelper(type, list.Count);
        list.CopyTo(array2, 0);
        return array2;
    }
References System.Attribute.AddAttributesToList(), System.array, System.Attribute.CopyToAttributeList(), System.Attribute.CreateAttributeArrayHelper(), System.Reflection.MemberInfo.GetCustomAttributes(), System.Attribute.GetCustomAttributes(), System.Attribute.GetParentDefinition(), System.list, and System.type.