Terraria: System.Attribute.GetCustomAttribute
GetCustomAttribute() [3/8]
static ? Attribute System.Attribute.GetCustomAttribute (MemberInfo element, Type attributeType) inline static inherited
Definition at line 411 of file Attribute.cs.
    {
        return GetCustomAttribute(element, attributeType, inherit: true);
    }
References System.Attribute.GetCustomAttribute().
Referenced by ReLogic.Peripherals.RGB.ChromaShader.BindProcessors(), System.Runtime.InteropServices.Marshal.GenerateProgIdForType(), System.ComponentModel.DataAnnotations.AssociatedMetadataTypeTypeDescriptor.TypeDescriptorCache.GetAssociatedMetadataType(), System.Attribute.GetCustomAttribute(), System.Attribute.GetCustomAttribute(), System.Attribute.GetCustomAttribute(), System.Attribute.GetCustomAttribute(), System.Reflection.CustomAttributeExtensions.GetCustomAttribute(), System.Reflection.CustomAttributeExtensions.GetCustomAttribute(), System.Reflection.CustomAttributeExtensions.GetCustomAttribute(), System.Reflection.CustomAttributeExtensions.GetCustomAttribute(), System.Reflection.CustomAttributeExtensions.GetCustomAttribute(), System.Reflection.CustomAttributeExtensions.GetCustomAttribute(), System.Reflection.CustomAttributeExtensions.GetCustomAttribute< T >(), System.Reflection.CustomAttributeExtensions.GetCustomAttribute< T >(), System.Reflection.CustomAttributeExtensions.GetCustomAttribute< T >(), System.Reflection.CustomAttributeExtensions.GetCustomAttribute< T >(), System.Reflection.CustomAttributeExtensions.GetCustomAttribute< T >(), System.Reflection.CustomAttributeExtensions.GetCustomAttribute< T >(), System.Runtime.InteropServices.ComAwareEventInfo.GetDataForComInvocation(), System.Text.Json.Serialization.Metadata.FSharpCoreReflectionProxy.GetFSharpCompilationMappingAttribute(), and System.ComponentModel.LicenseManager.ValidateInternalRecursive().