Terraria: System.Attribute.InternalGetAttributeUsage
InternalGetAttributeUsage()
static AttributeUsageAttribute System.Attribute.InternalGetAttributeUsage (Type type) inline static private inherited
Definition at line 319 of file Attribute.cs.
    {
        object[] customAttributes = type.GetCustomAttributes(typeof(AttributeUsageAttribute), inherit: false);
        if (customAttributes.Length == 1)
        {
            return (AttributeUsageAttribute)customAttributes[0];
        }
        if (customAttributes.Length == 0)
        {
            return AttributeUsageAttribute.Default;
        }
        throw new FormatException(SR.Format(SR.Format_AttributeUsage, type));
    }
References System.AttributeUsageAttribute.Default, System.SR.Format(), System.SR.Format_AttributeUsage, and System.type.
Referenced by System.Attribute.AddAttributesToList(), System.Attribute.CopyToAttributeList(), System.Attribute.InternalIsDefined(), System.Attribute.InternalIsDefined(), System.Attribute.InternalParamGetCustomAttributes(), and System.Attribute.InternalParamIsDefined().