Terraria: System.Threading.Tasks.Task.WhenAllPromise.Invoke
Invoke() [2/2]
void System.Threading.Tasks.Task< TResult >.WhenAllPromise< T >.Invoke (Task ignored) inline
Implements System.Threading.Tasks.ITaskCompletionAction.
Definition at line 818 of file Task.cs.
        {
            if (TplEventSource.Log.IsEnabled())
            {
                TplEventSource.Log.TraceOperationRelation(base.Id, CausalityRelation.Join);
            }
            if (Interlocked.Decrement(ref m_count) != 0)
            {
                return;
            }
            T[] array = new T[m_tasks.Length];
            List<ExceptionDispatchInfo> list = null;
            Task task = null;
            for (int i = 0; i < m_tasks.Length; i++)
            {
                Task<T> task2 = m_tasks[i];
                if (task2.IsFaulted)
                {
                    if (list == null)
                    {
                        list = new List<ExceptionDispatchInfo>();
                    }
                    list.AddRange(task2.GetExceptionDispatchInfos());
                }
                else if (task2.IsCanceled)
                {
                    if (task == null)
                    {
                        task = task2;
                    }
                }
                else
                {
                    array[i] = task2.GetResultCore(waitCompletionNotification: false);
                }
                if (task2.IsWaitNotificationEnabled)
                {
                    SetNotificationForWaitCompletion(enabled: true);
                }
                else
                {
                    m_tasks[i] = null;
                }
            }
            if (list != null)
            {
                TrySetException(list);
                return;
            }
            if (task != null)
            {
                TrySetCanceled(task.CancellationToken, task.GetCancellationExceptionDispatchInfo());
                return;
            }
            if (TplEventSource.Log.IsEnabled())
            {
                TplEventSource.Log.TraceOperationEnd(base.Id, AsyncCausalityStatus.Completed);
            }
            if (s_asyncDebuggingEnabled)
            {
                RemoveFromActiveTasks(this);
            }
            TrySetResult(array);
        }
References System.array, System.Threading.Interlocked.Decrement(), System.list, System.Threading.Tasks.TplEventSource.Log, System.Threading.Tasks.Task< TResult >.WhenAllPromise< T >.m_count, System.Threading.Tasks.Task< TResult >.WhenAllPromise< T >.m_tasks, System.Threading.Tasks.Task< TResult >.RemoveFromActiveTasks(), System.Threading.Tasks.Task< TResult >.s_asyncDebuggingEnabled, System.Threading.Tasks.Task< TResult >.SetNotificationForWaitCompletion(), System.task, System.Threading.Tasks.Task< TResult >.TrySetCanceled(), System.Threading.Tasks.Task< TResult >.TrySetException(), and System.Threading.Tasks.Task< TResult >.TrySetResult().