Terraria: Terraria.GameContent.RGB.GolemShader.ProcessHighDetail
ProcessHighDetail()
void Terraria.GameContent.RGB.GolemShader.ProcessHighDetail (RgbDevice device, Fragment fragment, EffectDetailLevel quality, float time) inline private
    {
        float num = 0.5f + (float)Math.Sin(time * 3f) * 0.1f;
        Vector2 vector = new Vector2(1.6f, 0.5f);
        for (int i = 0; i < fragment.Count; i++)
        {
            Vector2 canvasPositionOfIndex = fragment.GetCanvasPositionOfIndex(i);
            Point gridPositionOfIndex = fragment.GetGridPositionOfIndex(i);
            Vector4 vector2 = _backgroundColor;
            float num2 = (NoiseHelper.GetStaticNoise(gridPositionOfIndex.Y) * 10f + time * 2f) % 10f - Math.Abs(canvasPositionOfIndex.X - vector.X);
            if (num2 > 0f)
            {
                float amount = Math.Max(0f, 1.2f - num2);
                if (num2 < 0.2f)
                {
                    amount = num2 * 5f;
                }
                vector2 = Vector4.Lerp(vector2, _glowColor, amount);
            }
            float num3 = (canvasPositionOfIndex - vector).Length();
            if (num3 < num)
            {
                float amount2 = 1f - MathHelper.Clamp((num3 - num + 0.1f) / 0.1f, 0f, 1f);
                vector2 = Vector4.Lerp(vector2, _coreColor, amount2);
            }
            fragment.SetColor(i, vector2);
        }
    }
References Terraria.GameContent.RGB.GolemShader._backgroundColor, Terraria.GameContent.RGB.GolemShader._coreColor, Terraria.GameContent.RGB.GolemShader._glowColor, ReLogic.Peripherals.RGB.Fragment.Count, ReLogic.Peripherals.RGB.Fragment.GetCanvasPositionOfIndex(), ReLogic.Peripherals.RGB.Fragment.GetGridPositionOfIndex(), Terraria.GameContent.RGB.NoiseHelper.GetStaticNoise(), and ReLogic.Peripherals.RGB.Fragment.SetColor().