Terraria: System.IDisposable.Dispose
Dispose()
void System.IDisposable.Dispose () inherited
Implemented in Microsoft.Xna.Framework.Graphics.GraphicsAdapter.CleanupHelper, Microsoft.Xna.Framework.Graphics.GraphicsDevice, Microsoft.Xna.Framework.Graphics.GraphicsResource, Microsoft.Xna.Framework.Graphics.GuideRenderer, Microsoft.Xna.Framework.Graphics.ModelBoneCollection.Enumerator, Microsoft.Xna.Framework.Graphics.ModelEffectCollection.Enumerator, Microsoft.Xna.Framework.Graphics.ModelMeshCollection.Enumerator, Microsoft.Xna.Framework.Graphics.ModelMeshPartCollection.Enumerator, Microsoft.Xna.Framework.Graphics.RenderTargetHelper, Microsoft.Xna.Framework.WindowsManagedCallbackHandler, ReLogic.Content.Readers.PngReader, ReLogic.Content.Readers.XnbReader, ReLogic.Content.Sources.ZipContentSource, ReLogic.Content.Asset< T >, ReLogic.Content.AssetRepository, ReLogic.Graphics.BasicDebugDrawer, ReLogic.IO.ConsoleOutputMirror, ReLogic.Localization.IME.PlatformIme, ReLogic.OS.Windows.STATaskInvoker, ReLogic.OS.Windows.WindowsMessageHook, ReLogic.OS.Platform, ReLogic.Peripherals.RGB.RgbDeviceGroup, ReLogic.Threading.AsyncActionDispatcher, ReLogic.Utilities.SlotVector< T >.Enumerator, ReLogic.Utilities.TypeInstanceCollection< BaseType >, System.Collections.Concurrent.BlockingCollection< T >, System.Collections.Concurrent.ConcurrentBag< T >.Enumerator, System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >.Enumerator, System.Collections.Concurrent.OrderablePartitioner< TSource >.EnumerableDropIndices, System.Collections.Concurrent.OrderablePartitioner< TSource >.EnumeratorDropIndices, System.Collections.Concurrent.Partitioner< TSource >.DynamicPartitionEnumerator_Abstract< TSource, TSourceReader >, System.Collections.Concurrent.Partitioner< TSource >.DynamicPartitionerForIEnumerable< TSource >.InternalPartitionEnumerable, System.Collections.Concurrent.Partitioner< TSource >.DynamicPartitionEnumeratorForIndexRange_Abstract< TSource, TSourceReader >, System.Collections.Concurrent.Partitioner< TSource >.StaticIndexRangePartition< TSource >, System.Collections.Immutable.DisposableEnumeratorAdapter< T, TEnumerator >, System.Collections.Immutable.ImmutableArray< T >.EnumeratorObject, System.Collections.Immutable.ImmutableDictionary< TKey, TValue >.Enumerator, System.Collections.Immutable.ImmutableDictionary< TKey, TValue >.HashBucket.Enumerator, System.Collections.Immutable.ImmutableHashSet< T >.Enumerator, System.Collections.Immutable.ImmutableHashSet< T >.HashBucket.Enumerator, System.Collections.Immutable.ImmutableList< T >.Enumerator, System.Collections.Immutable.ImmutableQueue< T >.EnumeratorObject, System.Collections.Immutable.ImmutableSortedDictionary< TKey, TValue >.Enumerator, System.Collections.Immutable.ImmutableSortedSet< T >.Enumerator, System.Collections.Immutable.ImmutableStack< T >.EnumeratorObject, System.Collections.Immutable.SortedInt32KeyNode< TValue >.Enumerator, System.Collections.Generic.LinkedList< T >.Enumerator, System.Collections.Generic.PriorityQueue< TElement, TPriority >.UnorderedItemsCollection.Enumerator, System.Collections.Generic.SortedDictionary< TKey, TValue >.Enumerator, System.Collections.Generic.SortedDictionary< TKey, TValue >.KeyCollection.Enumerator, System.Collections.Generic.SortedDictionary< TKey, TValue >.ValueCollection.Enumerator, System.Collections.Generic.SortedList< TKey, TValue >.Enumerator, System.Collections.Generic.SortedList< TKey, TValue >.SortedListKeyEnumerator, System.Collections.Generic.SortedList< TKey, TValue >.SortedListValueEnumerator, System.Collections.Generic.SortedSet< T >.Enumerator, System.Collections.Generic.Stack< T >.Enumerator, System.ComponentModel.Component, System.ComponentModel.EventHandlerList, System.ComponentModel.Design.Serialization.SerializationStore, System.ComponentModel.Design.DesignerTransaction, System.ComponentModel.Design.ServiceContainer, System.ComponentModel.Container, System.ComponentModel.License, System.ComponentModel.LicFileLicenseProvider.LicFileLicense, System.ComponentModel.MarshalByValueComponent, System.Data.Common.DbBatch, System.Data.Common.DbDataReader, System.Data.Common.DbTransaction, System.Data.RBTree< K >.RBTreeEnumerator, System.Data.TypeLimiter.Scope, System.Diagnostics.Metrics.Meter, System.Diagnostics.Metrics.MeterListener, System.Diagnostics.Activity, System.Diagnostics.ActivityListener, System.Diagnostics.ActivitySource, System.Diagnostics.ActivityTagsCollection.Enumerator, System.Diagnostics.DiagnosticListener.DiagnosticSubscription, System.Diagnostics.DiagnosticListener.AllListenerObservable.AllListenerSubscription, System.Diagnostics.DiagnosticListener, System.Diagnostics.Enumerator< T >, System.Diagnostics.TagList.Enumerator, System.Diagnostics.AsyncStreamReader, System.Diagnostics.StackTraceSymbols, System.Diagnostics.TraceListener, System.Formats.Asn1.AsnWriter.Scope, System.IO.Compression.BrotliDecoder, System.IO.Compression.BrotliEncoder, System.IO.Compression.Deflater, System.IO.Compression.Inflater, System.IO.Compression.ZipArchive, System.IO.DisableMediaInsertionPrompt, System.IO.DisableMediaInsertionPrompt, System.IO.IsolatedStorage.IsolatedStorageFile, System.IO.MemoryMappedFiles.MemoryMappedFile, System.IO.MemoryMappedFiles.MemoryMappedView, System.Runtime.CompilerServices.ReadOnlyCollectionBuilder< T >.Enumerator, System.Linq.Parallel.AsynchronousChannel< T >, System.Linq.Parallel.EnumerableWrapperWeakToStrong.WrapperEnumeratorWeakToStrong, System.Linq.Parallel.MergeEnumerator< TInputOutput >, System.Linq.Parallel.QueryOpeningEnumerator< TOutput >, System.Linq.Parallel.QueryOperatorEnumerator< TElement, TKey >.QueryOperatorClassicEnumerator, System.Linq.Parallel.SortHelper< TInputOutput, TKey >, System.Linq.EmptyPartition< TElement >, System.Linq.Enumerable.AppendPrependIterator< TSource >, System.Linq.Enumerable.ConcatIterator< TSource >, System.Linq.Enumerable.DefaultIfEmptyIterator< TSource >, System.Linq.Enumerable.DistinctIterator< TSource >, System.Linq.Enumerable.EnumerablePartition< TSource >, System.Linq.Enumerable.ReverseIterator< TSource >, System.Linq.Enumerable.UnionIterator< TSource >, System.Linq.Enumerable.WhereEnumerableIterator< TSource >, System.Linq.Enumerable.Iterator< TSource >, System.Buffers.ArrayMemoryPool< T >.ArrayMemoryPoolBuffer, System.Buffers.MemoryPool< T >, System.Net.Http.Headers.HeaderStringValues.Enumerator, System.Net.Http.Headers.HttpHeadersNonValidated.Enumerator, System.Net.Http.Headers.ObjectCollection< T >.Enumerator, System.Net.Http.QPack.QPackDecoder, System.Net.Http.Http2Connection, System.Net.Http.Http3Connection, System.Net.Http.Http3RequestStream, System.Net.Http.HttpConnection, System.Net.Http.HttpConnectionBase, System.Net.Http.HttpConnectionPool, System.Net.Http.HttpConnectionPoolManager.NetworkChangeCleanup, System.Net.Http.HttpConnectionPoolManager, System.Net.Http.HttpContent, System.Net.Http.HttpMessageHandler, System.Net.Http.HttpMessageInvoker, System.Net.Http.HttpRequestMessage, System.Net.Http.HttpResponseMessage, System.Net.Http.HttpWindowsProxy, System.Net.Security.SafeCredentialReference, System.Net.ArrayBuffer, System.Net.MultiArrayBuffer, System.Net.Security.SafeCredentialReference, System.Net.WebSockets.WebSocketBase.KeepAliveTracker.DisabledKeepAliveTracker, System.Net.WebSockets.WebSocketBase.KeepAliveTracker.DefaultKeepAliveTracker, System.Net.WebSockets.WebSocketBase.KeepAliveTracker, System.Net.WebSockets.WebSocketBase.OutstandingOperationHelper, System.Net.WebSockets.WebSocketBase, System.Net.WebSockets.WebSocketBuffer, System.Net.WebSockets.WebSocketHttpListenerDuplexStream.HttpListenerAsyncEventArgs, System.Net.HttpListener, System.Net.HttpListener, System.Net.HttpListenerResponse, System.Net.HttpListenerResponse, System.Net.ListenerPrefixEnumerator, System.Net.RequestContextBase, System.Net.Mail.AlternateViewCollection, System.Net.Mail.AttachmentBase, System.Net.Mail.AttachmentCollection, System.Net.Mail.LinkedResourceCollection, System.Net.Mail.MailMessage, System.Net.Mail.SmtpClient, System.Net.Mime.MimePart, System.Net.Security.SafeCredentialReference, System.IO.StreamBuffer, System.Net.Quic.Implementations.Mock.MockConnection, System.Net.Quic.Implementations.Mock.MockListener, System.Net.Quic.Implementations.Mock.MockStream, System.Net.Quic.Implementations.MsQuic.MsQuicConnection, System.Net.Quic.Implementations.MsQuic.MsQuicListener, System.Net.Quic.Implementations.MsQuic.MsQuicStream, System.Net.Quic.Implementations.QuicConnectionProvider, System.Net.Quic.Implementations.QuicListenerProvider, System.Net.Quic.Implementations.QuicStreamProvider, System.Net.Quic.QuicConnection, System.Net.Quic.QuicListener, System.Net.MultiArrayBuffer, System.Net.TimerThread.Timer, System.Net.WebResponse, System.Net.Security.SafeCredentialReference, System.Net.ArrayBuffer, System.Net.Sockets.Socket, System.Net.Sockets.SocketAsyncEventArgs, System.Net.Sockets.TcpClient, System.Net.Sockets.UdpClient, System.Net.WebSockets.ClientWebSocket, System.Net.WebSockets.Compression.WebSocketDeflater, System.Net.WebSockets.Compression.WebSocketInflater, System.Net.WebSockets.ManagedWebSocket, System.Net.WebSockets.WebSocket, System.Collections.ObjectModel.ObservableCollection< T >.SimpleMonitor, Internal.Win32.RegistryKey, System.Buffers.MemoryHandle, System.Buffers.MemoryManager< T >, System.Collections.Generic.Dictionary< TKey, TValue >.Enumerator, System.Collections.Generic.Dictionary< TKey, TValue >.KeyCollection.Enumerator, System.Collections.Generic.Dictionary< TKey, TValue >.ValueCollection.Enumerator, System.Collections.Generic.HashSet< T >.Enumerator, System.Collections.Generic.List< T >.Enumerator, System.Collections.Generic.Queue< T >.Enumerator, System.Diagnostics.Tracing.DiagnosticCounter, System.Diagnostics.Tracing.EventListener, System.Diagnostics.Tracing.EventProvider, System.Diagnostics.Tracing.EventSource, System.IO.Enumeration.FileSystemEnumerator< TResult >, System.IO.BinaryReader, System.IO.BinaryWriter, System.IO.DisableMediaInsertionPrompt, System.IO.Iterator< TSource >, System.IO.Stream, System.IO.TextReader, System.IO.TextWriter, System.IO.UnmanagedMemoryAccessor, System.Resources.ResourceReader, System.Resources.ResourceSet, System.Runtime.CompilerServices.ConditionalWeakTable< TKey, TValue >.Enumerator, System.Runtime.InteropServices.CriticalHandle, System.Runtime.InteropServices.PosixSignalRegistration, System.Runtime.InteropServices.SafeHandle, System.Runtime.Loader.AssemblyLoadContext.ContextualReflectionScope, System.Runtime.Serialization.DeserializationToken, System.Runtime.DependentHandle, System.Runtime.MemoryFailPoint, System.Security.SecureString, System.Text.StringRuneEnumerator, System.Threading.Tasks.Task< TResult >, System.Threading.Tasks.Task< bool >, System.Threading.Tasks.Task< HttpResponseMessage >, System.Threading.Tasks.Task< int >, System.Threading.Tasks.Task< T >, System.Threading.Tasks.Task< T[]>, System.Threading.Tasks.Task< TAntecedentResult >, System.Threading.Tasks.Task< Task >, System.Threading.Tasks.Task< Task< T >[]>, System.Threading.Tasks.Task< Task[]>, System.Threading.Tasks.Task< TTask >, System.Threading.Tasks.Task< VoidTaskResult >, System.Threading.Tasks.Task<(int, int, int, bool)>, System.Threading.AsyncFlowControl, System.Threading.CancellationTokenRegistration, System.Threading.CancellationTokenSource, System.Threading.ExecutionContext, System.Threading.LowLevelLifoSemaphore, System.Threading.LowLevelLock, System.Threading.ManualResetEventSlim, System.Threading.PeriodicTimer, System.Threading.PreAllocatedOverlapped, System.Threading.ReaderWriterLockSlim, System.Threading.SemaphoreSlim, System.Threading.ThreadLocal< T >, System.Threading.ThreadPoolBoundHandle, System.Threading.Timer, System.Threading.WaitHandle, System.ArraySegment< T >.Enumerator, System.CharEnumerator, System.SZGenericArrayEnumerator< T >, System.TypeNameParser, System.Runtime.Serialization.CollectionDataContract.DictionaryEnumerator, System.Runtime.Serialization.CollectionDataContract.GenericDictionaryEnumerator< K, V >, System.Xml.Serialization.XmlSchemaEnumerator, System.Xml.Xsl.IListEnumerator< T >, System.Xml.XmlNodeList, System.Xml.XmlReader, System.Xml.XmlWriter, System.Reflection.Internal.AbstractMemoryBlock, System.Reflection.Internal.ByteArrayMemoryBlock, System.Reflection.Internal.CriticalDisposableObject, System.Reflection.Internal.ExternalMemoryBlock, System.Reflection.Internal.MemoryBlockProvider, System.Reflection.Internal.MemoryMappedFileBlock, System.Reflection.Internal.NativeHeapMemoryBlock, System.Reflection.Metadata.AssemblyFileHandleCollection.Enumerator, System.Reflection.Metadata.AssemblyReferenceHandleCollection.Enumerator, System.Reflection.Metadata.BlobBuilder.Chunks, System.Reflection.Metadata.BlobBuilder.Blobs, System.Reflection.Metadata.CustomAttributeHandleCollection.Enumerator, System.Reflection.Metadata.CustomDebugInformationHandleCollection.Enumerator, System.Reflection.Metadata.DeclarativeSecurityAttributeHandleCollection.Enumerator, System.Reflection.Metadata.DocumentHandleCollection.Enumerator, System.Reflection.Metadata.EventDefinitionHandleCollection.Enumerator, System.Reflection.Metadata.ExportedTypeHandleCollection.Enumerator, System.Reflection.Metadata.FieldDefinitionHandleCollection.Enumerator, System.Reflection.Metadata.GenericParameterConstraintHandleCollection.Enumerator, System.Reflection.Metadata.GenericParameterHandleCollection.Enumerator, System.Reflection.Metadata.ImportDefinitionCollection.Enumerator, System.Reflection.Metadata.ImportScopeCollection.Enumerator, System.Reflection.Metadata.InterfaceImplementationHandleCollection.Enumerator, System.Reflection.Metadata.LocalConstantHandleCollection.Enumerator, System.Reflection.Metadata.LocalScopeHandleCollection.Enumerator, System.Reflection.Metadata.LocalScopeHandleCollection.ChildrenEnumerator, System.Reflection.Metadata.LocalVariableHandleCollection.Enumerator, System.Reflection.Metadata.ManifestResourceHandleCollection.Enumerator, System.Reflection.Metadata.MemberReferenceHandleCollection.Enumerator, System.Reflection.Metadata.MetadataReaderProvider, System.Reflection.Metadata.MethodDebugInformationHandleCollection.Enumerator, System.Reflection.Metadata.MethodDefinitionHandleCollection.Enumerator, System.Reflection.Metadata.MethodImplementationHandleCollection.Enumerator, System.Reflection.Metadata.ParameterHandleCollection.Enumerator, System.Reflection.Metadata.PropertyDefinitionHandleCollection.Enumerator, System.Reflection.Metadata.SequencePointCollection.Enumerator, System.Reflection.Metadata.TypeDefinitionHandleCollection.Enumerator, System.Reflection.Metadata.TypeReferenceHandleCollection.Enumerator, System.Reflection.PortableExecutable.PEReader, System.Resources.ResourceWriter, System.Security.AccessControl.Privilege.TlsContents, Internal.Cryptography.BasicSymmetricCipher, Internal.Cryptography.HashProvider, Internal.Cryptography.UniversalCryptoTransform, System.Security.Cryptography.AesCcm, System.Security.Cryptography.AesGcm, System.Security.Cryptography.ChaCha20Poly1305, System.Security.Cryptography.DeriveBytes, System.Security.Cryptography.ECDiffieHellmanPublicKey, System.Security.Cryptography.IncrementalHash, System.Security.Cryptography.RandomNumberGenerator, Internal.Cryptography.BasicSymmetricCipher, Internal.Cryptography.HashProvider, Internal.Cryptography.UniversalCryptoTransform, System.Security.Cryptography.CngKey, Internal.Cryptography.BasicSymmetricCipher, Internal.Cryptography.UniversalCryptoTransform, System.Security.Cryptography.FromBase64Transform, System.Security.Cryptography.ToBase64Transform, System.Security.Cryptography.AsymmetricAlgorithm, System.Security.Cryptography.HashAlgorithm, System.Security.Cryptography.SymmetricAlgorithm, Internal.Cryptography.Pal.CertificatePal, Internal.Cryptography.Pal.ChainPal, Internal.Cryptography.Pal.FindPal, Internal.Cryptography.Pal.StorePal, Internal.Cryptography.PinAndClear, System.Security.Cryptography.X509Certificates.X509Certificate, System.Security.Cryptography.X509Certificates.X509Certificate2Enumerator, System.Security.Cryptography.X509Certificates.X509Chain, System.Security.Cryptography.X509Certificates.X509ChainElementEnumerator, System.Security.Cryptography.X509Certificates.X509ExtensionEnumerator, System.Security.Cryptography.X509Certificates.X509Store, System.Security.Principal.IdentityReferenceEnumerator, System.Security.Principal.WindowsIdentity, System.Text.Json.Serialization.ReadBufferState, System.Text.Json.JsonDocument.MetadataDb, System.Text.Json.JsonDocument.StackRowStack, System.Text.Json.JsonDocument, System.Text.Json.JsonElement.ArrayEnumerator, System.Text.Json.JsonElement.ObjectEnumerator, System.Text.Json.PooledByteBufferWriter, System.Text.Json.Utf8JsonWriter, System.Text.RegularExpressions.CaptureCollection.Enumerator, System.Text.RegularExpressions.GroupCollection.Enumerator, System.Text.RegularExpressions.MatchCollection.Enumerator, System.Text.RegularExpressions.RegexCompiler.RentedLocalBuilder, System.Threading.Tasks.Dataflow.Internal.Disposables.NopDisposable, System.Threading.Tasks.Dataflow.Internal.Disposables.Disposable< T1, T2, T3 >, System.Threading.Tasks.Dataflow.Internal.Disposables.Disposable< T1, T2, T3 >, System.Threading.Tasks.Parallel.SyncForEachAsyncState< TSource >, System.Threading.Barrier, System.Threading.CountdownEvent, System.Threading.HostExecutionContext, System.Transactions.FinalizedObject, System.Transactions.InternalTransaction, System.Transactions.Transaction, System.Transactions.TransactionScope, Terraria.Audio.ASoundEffectBasedAudioTrack, Terraria.Audio.CueAudioTrack, Terraria.Audio.DisabledAudioSystem, Terraria.Audio.LegacyAudioSystem, Terraria.Audio.MP3AudioTrack, Terraria.Audio.OGGAudioTrack, Terraria.Audio.WAVAudioTrack, Terraria.Graphics.Capture.CaptureCamera, Terraria.Graphics.Capture.CaptureManager, and Terraria.Server.Game.
Referenced by System.Data.PropertyCollection.Clone(), System.Net.HttpListenerContext.Close(), System.Security.Cryptography.X509Certificates.X509Store.Close(), System.Diagnostics.ProcessModuleCollection.Dispose(), System.Diagnostics.ProcessThreadCollection.Dispose(), ReLogic.Content.Asset< T >.Dispose(), System.ComponentModel.Container.Dispose(), System.Net.Sockets.TcpClient.Dispose(), Internal.Runtime.InteropServices.LicenseInteropProxy.GetLicInfo(), Terraria.Audio.LegacyAudioSystem.LoadFromSources(), System.Security.Cryptography.X509Certificates.X509Certificate.Reset(), System.Security.Cryptography.X509Certificates.X509Chain.Reset(), System.Reflection.Internal.StreamMemoryBlockProvider.TryCreateMemoryMappedFileBlock(), System.Xml.XmlDocumentFragment.WriteContentTo(), and System.Xml.XmlEntityReference.WriteContentTo().