Terraria: System.Runtime.Serialization.FastInvokerBuilder.CreateGetter
CreateGetter()
static Getter System.Runtime.Serialization.FastInvokerBuilder.CreateGetter (MemberInfo memberInfo) inline static
Definition at line 29 of file FastInvokerBuilder.cs.
    {
        if (memberInfo is PropertyInfo propertyInfo)
        {
            Func<PropertyInfo, Getter> func = s_createGetterInternal.MakeGenericMethod(propertyInfo.DeclaringType, propertyInfo.PropertyType).CreateDelegate<Func<PropertyInfo, Getter>>();
            return func(propertyInfo);
        }
        FieldInfo fieldInfo = memberInfo as FieldInfo;
        if ((object)fieldInfo != null)
        {
            return (object obj) => fieldInfo.GetValue(obj);
        }
        throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new InvalidOperationException(System.SR.Format(System.SR.InvalidMember, DataContract.GetClrTypeFullName(memberInfo.DeclaringType), memberInfo.Name)));
    }
References System.Runtime.Serialization.Dictionary, System.SR.Format(), System.Runtime.Serialization.DataContract.GetClrTypeFullName(), System.Reflection.FieldInfo.GetValue(), System.SR.InvalidMember, System.obj, System.Runtime.Serialization.FastInvokerBuilder.s_createGetterInternal, and System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperError().