Terraria: System.Runtime.Serialization.FastInvokerBuilder.CreateSetter
CreateSetter()
static Setter System.Runtime.Serialization.FastInvokerBuilder.CreateSetter (MemberInfo memberInfo) inline static
Definition at line 45 of file FastInvokerBuilder.cs.
    {
        if (memberInfo is PropertyInfo)
        {
            PropertyInfo propertyInfo = (PropertyInfo)memberInfo;
            if (propertyInfo.CanWrite)
            {
                Func<PropertyInfo, Setter> func = s_createSetterInternal.MakeGenericMethod(propertyInfo.DeclaringType, propertyInfo.PropertyType).CreateDelegate<Func<PropertyInfo, Setter>>();
                return func(propertyInfo);
            }
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new InvalidOperationException(System.SR.Format(System.SR.NoSetMethodForProperty, propertyInfo.DeclaringType, propertyInfo.Name)));
        }
        if (memberInfo is FieldInfo)
        {
            FieldInfo fieldInfo = (FieldInfo)memberInfo;
            return delegate(ref object obj, object val)
            {
                fieldInfo.SetValue(obj, val);
            };
        }
        throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new InvalidOperationException(System.SR.Format(System.SR.InvalidMember, DataContract.GetClrTypeFullName(memberInfo.DeclaringType), memberInfo.Name)));
    }
References System.Reflection.PropertyInfo.CanWrite, System.Reflection.MemberInfo.DeclaringType, System.Runtime.Serialization.Dictionary, System.SR.Format(), System.Runtime.Serialization.DataContract.GetClrTypeFullName(), System.SR.InvalidMember, System.Reflection.MemberInfo.Name, System.SR.NoSetMethodForProperty, System.obj, System.Reflection.PropertyInfo.PropertyType, System.Runtime.Serialization.FastInvokerBuilder.s_createSetterInternal, System.Reflection.FieldInfo.SetValue(), and System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperError().