Terraria: System.Net.Quic.Implementations.MsQuic.MsQuicStream._state
_state
readonly State System.Net.Quic.Implementations.MsQuic.MsQuicStream._state = new State() private
Definition at line 127 of file MsQuicStream.cs.
Referenced by System.Net.Quic.Implementations.MsQuic.MsQuicStream.MsQuicStream(), System.Net.Quic.Implementations.MsQuic.MsQuicStream.MsQuicStream(), System.Net.Quic.Implementations.MsQuic.MsQuicStream.AbortRead(), System.Net.Quic.Implementations.MsQuic.MsQuicStream.AbortWrite(), System.Net.Quic.Implementations.MsQuic.MsQuicStream.Dispose(), System.Net.Quic.Implementations.MsQuic.MsQuicStream.EnableReceive(), System.Net.Quic.Implementations.MsQuic.MsQuicStream.GetStreamId(), System.Net.Quic.Implementations.MsQuic.MsQuicStream.HandleWriteCompletedState(), System.Net.Quic.Implementations.MsQuic.MsQuicStream.HandleWriteFailedState(), System.Net.Quic.Implementations.MsQuic.MsQuicStream.HandleWriteStartState(), System.Net.Quic.Implementations.MsQuic.MsQuicStream.ReadAsync(), System.Net.Quic.Implementations.MsQuic.MsQuicStream.ReceiveComplete(), System.Net.Quic.Implementations.MsQuic.MsQuicStream.SendReadOnlyMemoryAsync(), System.Net.Quic.Implementations.MsQuic.MsQuicStream.SendReadOnlyMemoryListAsync(), System.Net.Quic.Implementations.MsQuic.MsQuicStream.SendReadOnlySequenceAsync(), System.Net.Quic.Implementations.MsQuic.MsQuicStream.Shutdown(), System.Net.Quic.Implementations.MsQuic.MsQuicStream.ShutdownCompleted(), System.Net.Quic.Implementations.MsQuic.MsQuicStream.StartShutdown(), System.Net.Quic.Implementations.MsQuic.MsQuicStream.TraceId(), and System.Net.Quic.Implementations.MsQuic.MsQuicStream.WaitForWriteCompletionAsync().