Terraria: System.Net.Quic.Implementations.MsQuic.MsQuicStream.WriteAsync
WriteAsync() [1/6]
override async ValueTask System.Net.Quic.Implementations.MsQuic.MsQuicStream.WriteAsync (ReadOnlyMemory< byte > buffer, bool endStream, CancellationToken cancellationToken = default(CancellationToken)) inline package
Definition at line 323 of file MsQuicStream.cs.
    {
        ThrowIfDisposed();
        using (HandleWriteStartState(buffer.IsEmpty, cancellationToken))
        {
            await SendReadOnlyMemoryAsync(buffer, endStream ? QUIC_SEND_FLAGS.FIN : QUIC_SEND_FLAGS.NONE).ConfigureAwait(continueOnCapturedContext: false);
            HandleWriteCompletedState();
        }
    }
References System.buffer, System.cancellationToken, System.Net.Quic.Implementations.MsQuic.MsQuicStream.HandleWriteCompletedState(), System.Net.Quic.Implementations.MsQuic.MsQuicStream.HandleWriteStartState(), System.Net.Quic.Implementations.MsQuic.MsQuicStream.SendReadOnlyMemoryAsync(), and System.Net.Quic.Implementations.MsQuic.MsQuicStream.ThrowIfDisposed().