Terraria: System.Net.Quic.Implementations.MsQuic.MsQuicStream.HandleEventRecv
HandleEventRecv()
static unsafe uint System.Net.Quic.Implementations.MsQuic.MsQuicStream.HandleEventRecv (State state, ref MsQuicNativeMethods::StreamEvent evt) inline static private
Definition at line 811 of file MsQuicStream.cs.
    {
        ref MsQuicNativeMethods.StreamEventDataReceive receive = ref evt.Data.Receive;
        if (System.Net.NetEventSource.Log.IsEnabled())
        {
            System.Net.NetEventSource.Info(state, FormattableStringFactory.Create("{0} Stream received {1} bytes{2}", state.TraceId, receive.TotalBufferLength, receive.Flags.HasFlag(QUIC_RECEIVE_FLAGS.FIN) ? " with FIN flag" : ""), "HandleEventRecv");
        }
        bool flag = false;
        int num;
        lock (state)
        {
            switch (state.ReadState)
            {
            case ReadState.None:
            {
                if ((uint)state.ReceiveQuicBuffers.Length < receive.BufferCount)
                {
                    MsQuicNativeMethods.QuicBuffer[] receiveQuicBuffers = state.ReceiveQuicBuffers;
                    state.ReceiveQuicBuffers = ArrayPool<MsQuicNativeMethods.QuicBuffer>.Shared.Rent((int)receive.BufferCount);
                    if (receiveQuicBuffers.Length != 0)
                    {
                        ArrayPool<MsQuicNativeMethods.QuicBuffer>.Shared.Return(receiveQuicBuffers);
                    }
                }
                for (uint num2 = 0u; num2 < receive.BufferCount; num2++)
                {
                    state.ReceiveQuicBuffers[num2] = receive.Buffers[num2];
                }
                state.ReceiveQuicBuffersCount = (int)receive.BufferCount;
                state.ReceiveQuicBuffersTotalBytes = checked((int)receive.TotalBufferLength);
                state.ReceiveIsFinal = receive.Flags.HasFlag(QUIC_RECEIVE_FLAGS.FIN);
                if (state.ReceiveQuicBuffersTotalBytes == 0)
                {
                    if (state.ReceiveIsFinal)
                    {
                        state.ReadState = ReadState.ReadsCompleted;
                    }
                    return 0u;
                }
                state.ReadState = ReadState.IndividualReadComplete;
                return 459749u;
            }
            case ReadState.PendingRead:
                state.ReceiveCancellationRegistration.Unregister();
                flag = true;
                state.Stream = null;
                state.ReadState = ReadState.None;
                num = CopyMsQuicBuffersToUserBuffer(new ReadOnlySpan<MsQuicNativeMethods.QuicBuffer>(receive.Buffers, (int)receive.BufferCount), state.ReceiveUserBuffer.Span);
                if (receive.Flags.HasFlag(QUIC_RECEIVE_FLAGS.FIN) && (uint)num == receive.TotalBufferLength)
                {
                    state.ReadState = ReadState.ReadsCompleted;
                }
                state.ReceiveUserBuffer = null;
                break;
            default:
                return 0u;
            }
        }
        if (flag)
        {
            state.ReceiveResettableCompletionSource.Complete(num);
        }
        uint result = (((uint)num != receive.TotalBufferLength) ? 459998u : 0u);
        receive.TotalBufferLength = (uint)num;
        return result;
    }
References System.Net.Quic.Implementations.MsQuic.MsQuicStream.CopyMsQuicBuffersToUserBuffer(), System.Runtime.CompilerServices.FormattableStringFactory.Create(), System.Net.NetEventSource.Info(), System.Net.NetEventSource.Log, and System.state.
Referenced by System.Net.Quic.Implementations.MsQuic.MsQuicStream.HandleEvent().