Terraria: System.Net.Quic.Implementations.MsQuic.MsQuicStream.AbortRead
AbortRead()
override void System.Net.Quic.Implementations.MsQuic.MsQuicStream.AbortRead (long errorCode) inline package
Definition at line 516 of file MsQuicStream.cs.
    {
        if (_disposed != 1)
        {
            bool flag = false;
            lock (_state)
            {
                flag = CleanupReadStateAndCheckPending(_state, ReadState.Aborted);
            }
            if (flag)
            {
                _state.ReceiveResettableCompletionSource.CompleteException(ExceptionDispatchInfo.SetCurrentStackTrace(new QuicOperationAbortedException("Read was aborted")));
            }
            StartShutdown(QUIC_STREAM_SHUTDOWN_FLAGS.ABORT_RECEIVE, errorCode);
        }
    }
References System.Net.Quic.Implementations.MsQuic.MsQuicStream._disposed, System.Net.Quic.Implementations.MsQuic.MsQuicStream._state, System.Net.Quic.Implementations.MsQuic.MsQuicStream.CleanupReadStateAndCheckPending(), System.Net.Quic.Implementations.MsQuic.Internal.ResettableCompletionSource< T >.CompleteException(), System.Net.Quic.Implementations.MsQuic.MsQuicStream.State.ReceiveResettableCompletionSource, System.Runtime.ExceptionServices.ExceptionDispatchInfo.SetCurrentStackTrace(), and System.Net.Quic.Implementations.MsQuic.MsQuicStream.StartShutdown().