Terraria: System.Net.Quic.Implementations.MsQuic.MsQuicStream.ReadAsync
ReadAsync()
override ValueTask< int > System.Net.Quic.Implementations.MsQuic.MsQuicStream.ReadAsync (Memory< byte > destination, CancellationToken cancellationToken = default(CancellationToken)) inline package
Definition at line 417 of file MsQuicStream.cs.
    {
        ThrowIfDisposed();
        if (_state.ReadState == ReadState.Closed)
        {
            throw new InvalidOperationException(System.SR.net_quic_reading_notallowed);
        }
        if (System.Net.NetEventSource.Log.IsEnabled())
        {
            System.Net.NetEventSource.Info(_state, $"{TraceId()} Stream reading into Memory of '{destination.Length}' bytes.", "ReadAsync");
        }
        bool flag = false;
        ReadState readState;
        long readErrorCode;
        lock (_state)
        {
            readState = _state.ReadState;
            readErrorCode = _state.ReadErrorCode;
            if (readState != ReadState.PendingRead && cancellationToken.IsCancellationRequested)
            {
                readState = ReadState.Aborted;
                CleanupReadStateAndCheckPending(_state, ReadState.Aborted);
                flag = true;
            }
            switch (readState)
            {
            case ReadState.ReadsCompleted:
                return new ValueTask<int>(0);
            case ReadState.None:
                _state.ReceiveUserBuffer = destination;
                _state.Stream = this;
                _state.ReadState = ReadState.PendingRead;
                if (cancellationToken.CanBeCanceled)
                {
                    _state.ReceiveCancellationRegistration = cancellationToken.UnsafeRegister(delegate(object obj, CancellationToken token)
                    {
                        State state = (State)obj;
                        bool flag2;
                        lock (state)
{
                            flag2 = CleanupReadStateAndCheckPending(state, ReadState.Aborted);
                        }
                        if (flag2)
{
                            state.ReceiveResettableCompletionSource.CompleteException(ExceptionDispatchInfo.SetCurrentStackTrace(new OperationCanceledException(token)));
                        }
                    }, _state);
                }
                else
                {
                    _state.ReceiveCancellationRegistration = default(CancellationTokenRegistration);
                }
                return _state.ReceiveResettableCompletionSource.GetValueTask();
            case ReadState.IndividualReadComplete:
            {
                _state.ReadState = ReadState.None;
                int num = CopyMsQuicBuffersToUserBuffer(_state.ReceiveQuicBuffers.AsSpan(0, _state.ReceiveQuicBuffersCount), destination.Span);
                ReceiveComplete(num);
                if (num != _state.ReceiveQuicBuffersTotalBytes)
                {
                    EnableReceive();
                }
                else if (_state.ReceiveIsFinal)
                {
                    _state.ReadState = ReadState.ReadsCompleted;
                }
                return new ValueTask<int>(num);
            }
            }
        }
        Exception ex = null;
        return ValueTask.FromException<int>(ExceptionDispatchInfo.SetCurrentStackTrace(readState switch
        {
            ReadState.PendingRead => new InvalidOperationException("Only one read is supported at a time."),
            ReadState.Aborted => flag ? new OperationCanceledException(cancellationToken) : ThrowHelper.GetStreamAbortedException(readErrorCode),
            _ => GetConnectionAbortedException(_state),
        }));
    }
References System.Net.Quic.Implementations.MsQuic.MsQuicStream._state, System.cancellationToken, System.Net.Quic.Implementations.MsQuic.MsQuicStream.CleanupReadStateAndCheckPending(), System.Net.Quic.Implementations.MsQuic.MsQuicStream.CopyMsQuicBuffersToUserBuffer(), System.destination, System.Net.Quic.Implementations.MsQuic.MsQuicStream.EnableReceive(), System.Threading.Tasks.ValueTask< TResult >.FromException(), System.Net.Quic.Implementations.MsQuic.MsQuicStream.GetConnectionAbortedException(), System.Net.Quic.Implementations.MsQuic.ThrowHelper.GetStreamAbortedException(), System.Net.Quic.Implementations.MsQuic.Internal.ResettableCompletionSource< T >.GetValueTask(), System.Net.NetEventSource.Info(), System.Net.NetEventSource.Log, System.SR.net_quic_reading_notallowed, System.obj, System.Net.Quic.Implementations.MsQuic.MsQuicStream.State.ReadErrorCode, System.Net.Quic.Implementations.MsQuic.MsQuicStream.State.ReadState, System.Net.Quic.Implementations.MsQuic.MsQuicStream.ReceiveComplete(), System.Net.Quic.Implementations.MsQuic.MsQuicStream.State.ReceiveIsFinal, System.Net.Quic.Implementations.MsQuic.MsQuicStream.State.ReceiveQuicBuffers, System.Net.Quic.Implementations.MsQuic.MsQuicStream.State.ReceiveQuicBuffersCount, System.Net.Quic.Implementations.MsQuic.MsQuicStream.State.ReceiveQuicBuffersTotalBytes, System.Net.Quic.Implementations.MsQuic.MsQuicStream.State.ReceiveResettableCompletionSource, System.Runtime.ExceptionServices.ExceptionDispatchInfo.SetCurrentStackTrace(), System.state, and System.Net.Quic.Implementations.MsQuic.MsQuicStream.ThrowIfDisposed().
Referenced by System.Net.Quic.Implementations.MsQuic.MsQuicStream.Read().