Terraria: System.Net.Quic.Implementations.MsQuic.MsQuicStream.ThrowIfDisposed
ThrowIfDisposed()
void System.Net.Quic.Implementations.MsQuic.MsQuicStream.ThrowIfDisposed () inline private
Definition at line 1186 of file MsQuicStream.cs.
    {
        if (_disposed == 1)
        {
            throw new ObjectDisposedException("MsQuicStream");
        }
    }
References System.Net.Quic.Implementations.MsQuic.MsQuicStream._disposed.
Referenced by System.Net.Quic.Implementations.MsQuic.MsQuicStream.Flush(), System.Net.Quic.Implementations.MsQuic.MsQuicStream.FlushAsync(), System.Net.Quic.Implementations.MsQuic.MsQuicStream.Read(), System.Net.Quic.Implementations.MsQuic.MsQuicStream.ReadAsync(), System.Net.Quic.Implementations.MsQuic.MsQuicStream.Shutdown(), System.Net.Quic.Implementations.MsQuic.MsQuicStream.ShutdownCompleted(), System.Net.Quic.Implementations.MsQuic.MsQuicStream.WaitForWriteCompletionAsync(), System.Net.Quic.Implementations.MsQuic.MsQuicStream.Write(), System.Net.Quic.Implementations.MsQuic.MsQuicStream.WriteAsync(), System.Net.Quic.Implementations.MsQuic.MsQuicStream.WriteAsync(), and System.Net.Quic.Implementations.MsQuic.MsQuicStream.WriteAsync().