Terraria: System.Net.Quic.Implementations.MsQuic.MsQuicStream.SendReadOnlySequenceAsync
SendReadOnlySequenceAsync()
unsafe ValueTask System.Net.Quic.Implementations.MsQuic.MsQuicStream.SendReadOnlySequenceAsync (ReadOnlySequence< byte > buffers, QUIC_SEND_FLAGS flags) inline private
Definition at line 1087 of file MsQuicStream.cs.
    {
        if (buffers.IsEmpty)
        {
            if ((flags & QUIC_SEND_FLAGS.FIN) == QUIC_SEND_FLAGS.FIN)
            {
                StartShutdown(QUIC_STREAM_SHUTDOWN_FLAGS.GRACEFUL, 0L);
            }
            return default(ValueTask);
        }
        int num = 0;
        ReadOnlySequence<byte>.Enumerator enumerator = buffers.GetEnumerator();
        while (enumerator.MoveNext())
        {
            ReadOnlyMemory<byte> current = enumerator.Current;
            num++;
        }
        if (_state.SendBufferMaxCount < num)
        {
            Marshal.FreeHGlobal(_state.SendQuicBuffers);
            _state.SendQuicBuffers = IntPtr.Zero;
            _state.SendQuicBuffers = Marshal.AllocHGlobal(sizeof(MsQuicNativeMethods.QuicBuffer) * num);
            _state.SendBufferMaxCount = num;
            _state.BufferArrays = new MemoryHandle[num];
        }
        _state.SendBufferCount = num;
        num = 0;
        MsQuicNativeMethods.QuicBuffer* ptr = (MsQuicNativeMethods.QuicBuffer*)(void*)_state.SendQuicBuffers;
        ReadOnlySequence<byte>.Enumerator enumerator2 = buffers.GetEnumerator();
        while (enumerator2.MoveNext())
        {
            ReadOnlyMemory<byte> current2 = enumerator2.Current;
            MemoryHandle memoryHandle = current2.Pin();
            ptr[num].Length = (uint)current2.Length;
            ptr[num].Buffer = (byte*)memoryHandle.Pointer;
            _state.BufferArrays[num] = memoryHandle;
            num++;
        }
        uint status = MsQuicApi.Api.StreamSendDelegate(_state.Handle, ptr, (uint)num, flags, IntPtr.Zero);
        if (!MsQuicStatusHelper.SuccessfulStatusCode(status))
        {
            HandleWriteFailedState();
            CleanupSendState(_state);
            QuicExceptionHelpers.ThrowIfFailed(status, "Could not send data to peer.");
        }
        return _state.SendResettableCompletionSource.GetTypelessValueTask();
    }
References System.Net.Quic.Implementations.MsQuic.MsQuicStream._state, System.Runtime.InteropServices.Marshal.AllocHGlobal(), System.Net.Quic.Implementations.MsQuic.Internal.MsQuicApi.Api, System.Net.Quic.Implementations.MsQuic.MsQuicStream.State.BufferArrays, System.buffers, System.Net.Quic.Implementations.MsQuic.MsQuicStream.CleanupSendState(), System.Runtime.InteropServices.Marshal.FreeHGlobal(), System.Net.Quic.Implementations.MsQuic.Internal.ResettableCompletionSource< T >.GetTypelessValueTask(), System.Net.Quic.Implementations.MsQuic.MsQuicStream.State.Handle, System.Net.Quic.Implementations.MsQuic.MsQuicStream.HandleWriteFailedState(), System.L, System.ReadOnlyMemory< T >.Length, System.ReadOnlyMemory< T >.Pin(), System.Buffers.MemoryHandle.Pointer, System.Net.Quic.Implementations.MsQuic.MsQuicStream.State.SendBufferMaxCount, System.Net.Quic.Implementations.MsQuic.MsQuicStream.State.SendQuicBuffers, System.Net.Quic.Implementations.MsQuic.MsQuicStream.State.SendResettableCompletionSource, System.Net.Quic.Implementations.MsQuic.MsQuicStream.StartShutdown(), System.Net.Quic.Implementations.MsQuic.Internal.MsQuicStatusHelper.SuccessfulStatusCode(), System.Net.Quic.Implementations.MsQuic.Internal.QuicExceptionHelpers.ThrowIfFailed(), and System.IntPtr.Zero.
Referenced by System.Net.Quic.Implementations.MsQuic.MsQuicStream.WriteAsync().