Terraria: System.Net.Quic.Implementations.MsQuic.MsQuicStream.Dispose
Dispose() [2/2]
void System.Net.Quic.Implementations.MsQuic.MsQuicStream.Dispose (bool disposing) inline private
Definition at line 699 of file MsQuicStream.cs.
    {
        if (Interlocked.Exchange(ref _disposed, 1) != 0)
        {
            return;
        }
        if (System.Net.NetEventSource.Log.IsEnabled())
        {
            System.Net.NetEventSource.Info(_state, $"{TraceId()} Stream disposing {disposing}", "Dispose");
        }
        bool flag = false;
        bool flag2 = false;
        bool flag3 = false;
        bool flag4 = false;
        lock (_state)
        {
            if (_state.SendState < SendState.Aborted)
            {
                flag = true;
            }
            if (_state.ReadState < ReadState.ReadsCompleted || _state.ReadState == ReadState.Aborted)
            {
                flag2 = true;
                flag3 = CleanupReadStateAndCheckPending(_state, ReadState.Aborted);
            }
            if (_state.ShutdownState == ShutdownState.None)
            {
                _state.ShutdownState = ShutdownState.Pending;
            }
            flag4 = Interlocked.Exchange(ref _state.ShutdownDone, 1) == 2;
            if (flag4)
            {
                _state.ShutdownState = ShutdownState.Finished;
            }
        }
        if (flag)
        {
            try
            {
                StartShutdown(QUIC_STREAM_SHUTDOWN_FLAGS.GRACEFUL, 0L);
            }
            catch (ObjectDisposedException)
            {
            }
        }
        if (flag2)
        {
            try
            {
                StartShutdown(QUIC_STREAM_SHUTDOWN_FLAGS.ABORT_RECEIVE, 4294967295L);
            }
            catch (ObjectDisposedException)
            {
            }
        }
        if (flag3)
        {
            _state.ReceiveResettableCompletionSource.CompleteException(ExceptionDispatchInfo.SetCurrentStackTrace(new QuicOperationAbortedException("Read was canceled")));
        }
        if (flag4)
        {
            _state.Cleanup();
        }
        if (System.Net.NetEventSource.Log.IsEnabled())
        {
            System.Net.NetEventSource.Info(_state, $"{TraceId()} Stream disposed", "Dispose");
        }
    }
References System.Net.Quic.Implementations.MsQuic.MsQuicStream._disposed, System.Net.Quic.Implementations.MsQuic.MsQuicStream._state, System.Net.Quic.Implementations.MsQuic.MsQuicStream.State.Cleanup(), System.Net.Quic.Implementations.MsQuic.MsQuicStream.CleanupReadStateAndCheckPending(), System.Net.Quic.Implementations.MsQuic.Internal.ResettableCompletionSource< T >.CompleteException(), System.Threading.Interlocked.Exchange(), System.Net.NetEventSource.Info(), System.L, System.Net.NetEventSource.Log, System.Net.Quic.Implementations.MsQuic.MsQuicStream.State.ReadState, System.Net.Quic.Implementations.MsQuic.MsQuicStream.State.ReceiveResettableCompletionSource, System.Net.Quic.Implementations.MsQuic.MsQuicStream.State.SendState, System.Runtime.ExceptionServices.ExceptionDispatchInfo.SetCurrentStackTrace(), System.Net.Quic.Implementations.MsQuic.MsQuicStream.State.ShutdownDone, System.Net.Quic.Implementations.MsQuic.MsQuicStream.State.ShutdownState, and System.Net.Quic.Implementations.MsQuic.MsQuicStream.StartShutdown().