Terraria: System.Net.Quic.Implementations.MsQuic.MsQuicStream.HandleEvent
HandleEvent()
static uint System.Net.Quic.Implementations.MsQuic.MsQuicStream.HandleEvent (State state, ref MsQuicNativeMethods::StreamEvent evt) inline static private
Definition at line 780 of file MsQuicStream.cs.
    {
        if (System.Net.NetEventSource.Log.IsEnabled())
        {
            System.Net.NetEventSource.Info(state, $"{state.TraceId} Stream received event {evt.Type}", "HandleEvent");
        }
        try
        {
            return evt.Type switch
            {
                QUIC_STREAM_EVENT_TYPE.START_COMPLETE => HandleEventStartComplete(state, ref evt),
                QUIC_STREAM_EVENT_TYPE.RECEIVE => HandleEventRecv(state, ref evt),
                QUIC_STREAM_EVENT_TYPE.SEND_COMPLETE => HandleEventSendComplete(state, ref evt),
                QUIC_STREAM_EVENT_TYPE.PEER_SEND_SHUTDOWN => HandleEventPeerSendShutdown(state),
                QUIC_STREAM_EVENT_TYPE.PEER_SEND_ABORTED => HandleEventPeerSendAborted(state, ref evt),
                QUIC_STREAM_EVENT_TYPE.PEER_RECEIVE_ABORTED => HandleEventPeerRecvAborted(state, ref evt),
                QUIC_STREAM_EVENT_TYPE.SEND_SHUTDOWN_COMPLETE => HandleEventSendShutdownComplete(state, ref evt),
                QUIC_STREAM_EVENT_TYPE.SHUTDOWN_COMPLETE => HandleEventShutdownComplete(state, ref evt),
                _ => 0u,
            };
        }
        catch (Exception ex)
        {
            if (System.Net.NetEventSource.Log.IsEnabled())
            {
                System.Net.NetEventSource.Error(state, $"{state.TraceId} Exception occurred during handling Stream {evt.Type} event: {ex}", "HandleEvent");
            }
            return 2151743491u;
        }
    }
References System.Net.NetEventSource.Error(), System.Net.Quic.Implementations.MsQuic.MsQuicStream.HandleEventPeerRecvAborted(), System.Net.Quic.Implementations.MsQuic.MsQuicStream.HandleEventPeerSendAborted(), System.Net.Quic.Implementations.MsQuic.MsQuicStream.HandleEventPeerSendShutdown(), System.Net.Quic.Implementations.MsQuic.MsQuicStream.HandleEventRecv(), System.Net.Quic.Implementations.MsQuic.MsQuicStream.HandleEventSendComplete(), System.Net.Quic.Implementations.MsQuic.MsQuicStream.HandleEventSendShutdownComplete(), System.Net.Quic.Implementations.MsQuic.MsQuicStream.HandleEventShutdownComplete(), System.Net.Quic.Implementations.MsQuic.MsQuicStream.HandleEventStartComplete(), System.Net.NetEventSource.Info(), System.Net.NetEventSource.Log, and System.state.
Referenced by System.Net.Quic.Implementations.MsQuic.MsQuicStream.NativeCallbackHandler().