Terraria: System.Net.Quic.Implementations.MsQuic.MsQuicStream.ShutdownCompleted
ShutdownCompleted()
override async ValueTask System.Net.Quic.Implementations.MsQuic.MsQuicStream.ShutdownCompleted (CancellationToken cancellationToken = default(CancellationToken)) inline package
Definition at line 565 of file MsQuicStream.cs.
    {
        ThrowIfDisposed();
        lock (_state)
        {
            if (_state.ShutdownState == ShutdownState.ConnectionClosed)
            {
                throw GetConnectionAbortedException(_state);
            }
        }
        using (cancellationToken.UnsafeRegister(delegate(object s, CancellationToken token)
        {
            State state = (State)s;
            bool flag = false;
            lock (state)
            {
                if (state.ShutdownState == ShutdownState.None)
                {
                    state.ShutdownState = ShutdownState.Canceled;
                    flag = true;
                }
            }
            if (flag)
            {
                state.ShutdownCompletionSource.SetException(ExceptionDispatchInfo.SetCurrentStackTrace(new OperationCanceledException("Wait for shutdown was canceled", token)));
            }
        }, _state))
        {
            await _state.ShutdownCompletionSource.Task.ConfigureAwait(continueOnCapturedContext: false);
        }
    }
References System.Net.Quic.Implementations.MsQuic.MsQuicStream._state, System.cancellationToken, System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.Net.Quic.Implementations.MsQuic.MsQuicStream.GetConnectionAbortedException(), System.s, System.Runtime.ExceptionServices.ExceptionDispatchInfo.SetCurrentStackTrace(), System.Net.Quic.Implementations.MsQuic.MsQuicStream.State.ShutdownCompletionSource, System.Net.Quic.Implementations.MsQuic.MsQuicStream.State.ShutdownState, System.state, System.Threading.Tasks.TaskCompletionSource< TResult >.Task, and System.Net.Quic.Implementations.MsQuic.MsQuicStream.ThrowIfDisposed().