Terraria: System.Net.Quic.Implementations.MsQuic.MsQuicStream.Read
Read()
override int System.Net.Quic.Implementations.MsQuic.MsQuicStream.Read (Span< byte > buffer) inline package
Definition at line 623 of file MsQuicStream.cs.
    {
        ThrowIfDisposed();
        byte[] array = ArrayPool<byte>.Shared.Rent(buffer.Length);
        CancellationTokenSource cancellationTokenSource = null;
        try
        {
            if (_readTimeout > 0)
            {
                cancellationTokenSource = new CancellationTokenSource(_readTimeout);
            }
            int result = ReadAsync(new Memory<byte>(array, 0, buffer.Length), cancellationTokenSource?.Token ?? default(CancellationToken)).AsTask().GetAwaiter().GetResult();
            array.AsSpan(0, result).CopyTo(buffer);
            return result;
        }
        catch (OperationCanceledException) when (cancellationTokenSource?.IsCancellationRequested ?? false)
        {
            throw new IOException(System.SR.net_quic_timeout);
        }
        finally
        {
            ArrayPool<byte>.Shared.Return(array);
            cancellationTokenSource?.Dispose();
        }
    }
References System.Net.Quic.Implementations.MsQuic.MsQuicStream._readTimeout, System.array, System.Threading.Tasks.ValueTask< TResult >.AsTask(), System.buffer, System.Threading.CancellationTokenSource.Dispose(), System.Threading.Tasks.Task< TResult >.GetAwaiter(), System.SR.net_quic_timeout, System.Net.Quic.Implementations.MsQuic.MsQuicStream.ReadAsync(), System.Buffers.ArrayPool< T >.Shared, System.Net.Quic.Implementations.MsQuic.MsQuicStream.ThrowIfDisposed(), and System.Threading.CancellationTokenSource.Token.