Terraria: System.Net.Quic.Implementations.MsQuic.MsQuicStream.MsQuicStream
MsQuicStream() [2/2]
System.Net.Quic.Implementations.MsQuic.MsQuicStream.MsQuicStream (MsQuicConnection::State connectionState, QUIC_STREAM_OPEN_FLAGS flags) inline package
Definition at line 254 of file MsQuicStream.cs.
    {
        if (!connectionState.TryAddStream(this))
        {
            throw new ObjectDisposedException("QuicConnection");
        }
        _state.ConnectionState = connectionState;
        _canRead = !flags.HasFlag(QUIC_STREAM_OPEN_FLAGS.UNIDIRECTIONAL);
        _canWrite = true;
        _state.StateGCHandle = GCHandle.Alloc(_state);
        if (!_canRead)
        {
            _state.ReadState = ReadState.Closed;
        }
        try
        {
            uint status = MsQuicApi.Api.StreamOpenDelegate(connectionState.Handle, flags, s_streamDelegate, GCHandle.ToIntPtr(_state.StateGCHandle), out _state.Handle);
            QuicExceptionHelpers.ThrowIfFailed(status, "Failed to open stream to peer.");
            status = MsQuicApi.Api.StreamStartDelegate(_state.Handle, QUIC_STREAM_START_FLAGS.FAIL_BLOCKED);
            QuicExceptionHelpers.ThrowIfFailed(status, "Could not start stream.");
        }
        catch
        {
            _state.Handle?.Dispose();
            _state.StateGCHandle.Free();
            throw;
        }
        _state.TraceId = MsQuicTraceHelper.GetTraceId(_state.Handle);
        if (System.Net.NetEventSource.Log.IsEnabled())
        {
            System.Net.NetEventSource.Info(_state, $"{_state.TraceId} Outbound {(flags.HasFlag(QUIC_STREAM_OPEN_FLAGS.UNIDIRECTIONAL) ? "uni" : "bi")}directional stream created in connection {_state.ConnectionState.TraceId}.", ".ctor");
        }
    }
References System.Net.Quic.Implementations.MsQuic.MsQuicStream._canRead, System.Net.Quic.Implementations.MsQuic.MsQuicStream._canWrite, System.Net.Quic.Implementations.MsQuic.MsQuicStream._state, System.Runtime.InteropServices.GCHandle.Alloc(), System.Net.Quic.Implementations.MsQuic.Internal.MsQuicApi.Api, System.Runtime.InteropServices.SafeHandle.Dispose(), System.Runtime.InteropServices.GCHandle.Free(), System.Net.Quic.Implementations.MsQuic.Internal.MsQuicTraceHelper.GetTraceId(), System.Net.Quic.Implementations.MsQuic.MsQuicStream.State.Handle, System.Net.NetEventSource.Info(), System.Net.NetEventSource.Log, System.Net.Quic.Implementations.MsQuic.MsQuicStream.s_streamDelegate, System.Net.Quic.Implementations.MsQuic.MsQuicStream.State.StateGCHandle, System.Net.Quic.Implementations.MsQuic.Internal.QuicExceptionHelpers.ThrowIfFailed(), and System.Runtime.InteropServices.GCHandle.ToIntPtr().