Terraria: System.Net.Quic.Implementations.MsQuic.MsQuicStream.Write
Write()
override void System.Net.Quic.Implementations.MsQuic.MsQuicStream.Write (ReadOnlySpan< byte > buffer) inline package
Definition at line 649 of file MsQuicStream.cs.
    {
        ThrowIfDisposed();
        CancellationTokenSource cancellationTokenSource = null;
        if (_writeTimeout > 0)
        {
            cancellationTokenSource = new CancellationTokenSource(_writeTimeout);
        }
        try
        {
            WriteAsync(buffer.ToArray()).AsTask().GetAwaiter().GetResult();
        }
        catch (OperationCanceledException) when (cancellationTokenSource?.IsCancellationRequested ?? false)
        {
            throw new IOException(System.SR.net_quic_timeout);
        }
        finally
        {
            cancellationTokenSource?.Dispose();
        }
    }
References System.Net.Quic.Implementations.MsQuic.MsQuicStream._writeTimeout, System.Threading.Tasks.ValueTask< TResult >.AsTask(), System.buffer, System.Threading.CancellationTokenSource.Dispose(), System.Threading.Tasks.Task< TResult >.GetAwaiter(), System.SR.net_quic_timeout, System.Net.Quic.Implementations.MsQuic.MsQuicStream.ThrowIfDisposed(), and System.Net.Quic.Implementations.MsQuic.MsQuicStream.WriteAsync().