Terraria: System.Net.Quic.Implementations.MsQuic.MsQuicStream.MsQuicStream
MsQuicStream() [1/2]
System.Net.Quic.Implementations.MsQuic.MsQuicStream.MsQuicStream (MsQuicConnection::State connectionState, SafeMsQuicStreamHandle streamHandle, QUIC_STREAM_OPEN_FLAGS flags) inline package
Definition at line 223 of file MsQuicStream.cs.
    {
        if (!connectionState.TryAddStream(this))
        {
            throw new ObjectDisposedException("QuicConnection");
        }
        _state.ConnectionState = connectionState;
        _state.Handle = streamHandle;
        _canRead = true;
        _canWrite = !flags.HasFlag(QUIC_STREAM_OPEN_FLAGS.UNIDIRECTIONAL);
        if (!_canWrite)
        {
            _state.SendState = SendState.Closed;
        }
        _state.StateGCHandle = GCHandle.Alloc(_state);
        try
        {
            MsQuicApi.Api.SetCallbackHandlerDelegate(_state.Handle, s_streamDelegate, GCHandle.ToIntPtr(_state.StateGCHandle));
        }
        catch
        {
            _state.StateGCHandle.Free();
            throw;
        }
        _state.TraceId = MsQuicTraceHelper.GetTraceId(_state.Handle);
        if (System.Net.NetEventSource.Log.IsEnabled())
        {
            System.Net.NetEventSource.Info(_state, $"{TraceId()} Inbound {(flags.HasFlag(QUIC_STREAM_OPEN_FLAGS.UNIDIRECTIONAL) ? "uni" : "bi")}directional stream created in connection {_state.ConnectionState.TraceId}.", ".ctor");
        }
    }
References System.Net.Quic.Implementations.MsQuic.MsQuicStream._canRead, System.Net.Quic.Implementations.MsQuic.MsQuicStream._canWrite, System.Net.Quic.Implementations.MsQuic.MsQuicStream._state, System.Runtime.InteropServices.GCHandle.Alloc(), System.Net.Quic.Implementations.MsQuic.Internal.MsQuicApi.Api, System.Runtime.InteropServices.GCHandle.Free(), System.Net.Quic.Implementations.MsQuic.Internal.MsQuicTraceHelper.GetTraceId(), System.Net.Quic.Implementations.MsQuic.MsQuicStream.State.Handle, System.Net.NetEventSource.Info(), System.Net.NetEventSource.Log, System.Net.Quic.Implementations.MsQuic.MsQuicStream.s_streamDelegate, System.Net.Quic.Implementations.MsQuic.MsQuicStream.State.StateGCHandle, and System.Runtime.InteropServices.GCHandle.ToIntPtr().