Terraria: System.Net.Quic.Implementations.MsQuic.MsQuicStream.HandleWriteStartState
HandleWriteStartState()
CancellationTokenRegistration System.Net.Quic.Implementations.MsQuic.MsQuicStream.HandleWriteStartState (bool emptyBuffer, CancellationToken cancellationToken) inline private
Definition at line 333 of file MsQuicStream.cs.
    {
        if (_state.SendState == SendState.Closed)
        {
            throw new InvalidOperationException(System.SR.net_quic_writing_notallowed);
        }
        if (_state.SendState == SendState.Aborted)
        {
            if (_state.SendErrorCode != -1)
            {
                throw new QuicStreamAbortedException(_state.SendErrorCode);
            }
            throw new OperationCanceledException(cancellationToken);
        }
        if (cancellationToken.IsCancellationRequested)
        {
            lock (_state)
            {
                if (_state.SendState == SendState.None || _state.SendState == SendState.Pending)
                {
                    _state.SendState = SendState.Aborted;
                }
            }
            throw new OperationCanceledException(cancellationToken);
        }
        CancellationTokenRegistration result = cancellationToken.UnsafeRegister(delegate(object s, CancellationToken token)
        {
            State state = (State)s;
            bool flag = false;
            lock (state)
            {
                if (state.SendState == SendState.None || state.SendState == SendState.Pending)
                {
                    state.SendState = SendState.Aborted;
                    flag = true;
                }
            }
            if (flag)
            {
                state.SendResettableCompletionSource.CompleteException(ExceptionDispatchInfo.SetCurrentStackTrace(new OperationCanceledException("Write was canceled", token)));
            }
        }, _state);
        lock (_state)
        {
            if (_state.SendState == SendState.Aborted)
            {
                cancellationToken.ThrowIfCancellationRequested();
                if (_state.SendErrorCode != -1)
                {
                    throw new QuicStreamAbortedException(_state.SendErrorCode);
                }
                throw new OperationCanceledException(System.SR.net_quic_sending_aborted);
            }
            if (_state.SendState == SendState.ConnectionClosed)
            {
                throw GetConnectionAbortedException(_state);
            }
            _state.SendState = ((!emptyBuffer) ? SendState.Pending : SendState.Finished);
            return result;
        }
    }
References System.Net.Quic.Implementations.MsQuic.MsQuicStream._state, System.cancellationToken, System.Net.Quic.Implementations.MsQuic.MsQuicStream.GetConnectionAbortedException(), System.SR.net_quic_sending_aborted, System.SR.net_quic_writing_notallowed, System.s, System.Net.Quic.Implementations.MsQuic.MsQuicStream.State.SendErrorCode, System.Net.Quic.Implementations.MsQuic.MsQuicStream.State.SendState, System.Runtime.ExceptionServices.ExceptionDispatchInfo.SetCurrentStackTrace(), and System.state.
Referenced by System.Net.Quic.Implementations.MsQuic.MsQuicStream.WriteAsync(), System.Net.Quic.Implementations.MsQuic.MsQuicStream.WriteAsync(), and System.Net.Quic.Implementations.MsQuic.MsQuicStream.WriteAsync().