Terraria: System.Net.Quic.Implementations.MsQuic.MsQuicStream.AbortWrite
AbortWrite()
override void System.Net.Quic.Implementations.MsQuic.MsQuicStream.AbortWrite (long errorCode) inline package
Definition at line 533 of file MsQuicStream.cs.
    {
        if (_disposed == 1)
        {
            return;
        }
        bool flag = false;
        lock (_state)
        {
            if (_state.SendState < SendState.Aborted)
            {
                _state.SendState = SendState.Aborted;
            }
            if (_state.ShutdownWriteState == ShutdownWriteState.None)
            {
                _state.ShutdownWriteState = ShutdownWriteState.Canceled;
                flag = true;
            }
        }
        if (flag)
        {
            _state.ShutdownWriteCompletionSource.SetException(ExceptionDispatchInfo.SetCurrentStackTrace(new QuicOperationAbortedException("Write was aborted.")));
        }
        StartShutdown(QUIC_STREAM_SHUTDOWN_FLAGS.ABORT_SEND, errorCode);
    }
References System.Net.Quic.Implementations.MsQuic.MsQuicStream._disposed, System.Net.Quic.Implementations.MsQuic.MsQuicStream._state, System.Net.Quic.Implementations.MsQuic.MsQuicStream.State.SendState, System.Runtime.ExceptionServices.ExceptionDispatchInfo.SetCurrentStackTrace(), System.Threading.Tasks.TaskCompletionSource< TResult >.SetException(), System.Net.Quic.Implementations.MsQuic.MsQuicStream.State.ShutdownWriteCompletionSource, System.Net.Quic.Implementations.MsQuic.MsQuicStream.State.ShutdownWriteState, and System.Net.Quic.Implementations.MsQuic.MsQuicStream.StartShutdown().