Terraria: System.Net.Quic.Implementations.MsQuic.MsQuicStream.HandleEventShutdownComplete
HandleEventShutdownComplete()
static uint System.Net.Quic.Implementations.MsQuic.MsQuicStream.HandleEventShutdownComplete (State state, ref MsQuicNativeMethods::StreamEvent evt) inline static private
Definition at line 933 of file MsQuicStream.cs.
    {
        MsQuicNativeMethods.StreamEventDataShutdownComplete shutdownComplete = evt.Data.ShutdownComplete;
        if (shutdownComplete.ConnectionShutdown != 0)
        {
            return HandleEventConnectionClose(state);
        }
        bool flag = false;
        bool flag2 = false;
        bool flag3 = false;
        lock (state)
        {
            if (System.Net.NetEventSource.Log.IsEnabled())
            {
                System.Net.NetEventSource.Info(state, $"{state.TraceId} Stream completing resettable event source.", "HandleEventShutdownComplete");
            }
            flag = CleanupReadStateAndCheckPending(state, ReadState.ReadsCompleted);
            if (state.ShutdownWriteState == ShutdownWriteState.None)
            {
                state.ShutdownWriteState = ShutdownWriteState.Finished;
                flag2 = true;
            }
            if (state.ShutdownState == ShutdownState.None)
            {
                state.ShutdownState = ShutdownState.Finished;
                flag3 = true;
            }
        }
        if (flag)
        {
            state.ReceiveResettableCompletionSource.Complete(0);
        }
        if (flag2)
        {
            state.ShutdownWriteCompletionSource.SetResult();
        }
        if (flag3)
        {
            state.ShutdownCompletionSource.SetResult();
        }
        if (Interlocked.Exchange(ref state.ShutdownDone, 2) == 1)
        {
            state.Cleanup();
        }
        return 0u;
    }
References System.Net.Quic.Implementations.MsQuic.MsQuicStream.CleanupReadStateAndCheckPending(), System.Net.Quic.Implementations.MsQuic.Internal.MsQuicNativeMethods.StreamEventDataShutdownComplete.ConnectionShutdown, System.Threading.Interlocked.Exchange(), System.Net.Quic.Implementations.MsQuic.MsQuicStream.HandleEventConnectionClose(), System.Net.NetEventSource.Info(), System.Net.NetEventSource.Log, and System.state.
Referenced by System.Net.Quic.Implementations.MsQuic.MsQuicStream.HandleEvent().