Terraria: System.Net.Quic.Implementations.MsQuic.MsQuicStream.HandleEventSendComplete
HandleEventSendComplete()
static uint System.Net.Quic.Implementations.MsQuic.MsQuicStream.HandleEventSendComplete (State state, ref MsQuicNativeMethods::StreamEvent evt) inline static private
Definition at line 1013 of file MsQuicStream.cs.
    {
        MsQuicNativeMethods.StreamEventDataSendComplete sendComplete = evt.Data.SendComplete;
        bool flag = sendComplete.Canceled != 0;
        bool flag2 = false;
        lock (state)
        {
            if (state.SendState == SendState.Pending)
            {
                state.SendState = SendState.Finished;
                flag2 = true;
            }
            if (flag)
            {
                state.SendState = SendState.Aborted;
            }
        }
        if (flag2)
        {
            CleanupSendState(state);
            if (!flag)
            {
                state.SendResettableCompletionSource.Complete(0u);
            }
            else
            {
                state.SendResettableCompletionSource.CompleteException(ExceptionDispatchInfo.SetCurrentStackTrace(new OperationCanceledException("Write was canceled")));
            }
        }
        return 0u;
    }
References System.Net.Quic.Implementations.MsQuic.MsQuicStream.CleanupSendState(), System.Runtime.ExceptionServices.ExceptionDispatchInfo.SetCurrentStackTrace(), and System.state.
Referenced by System.Net.Quic.Implementations.MsQuic.MsQuicStream.HandleEvent().