Terraria: System.Net.Quic.Implementations.MsQuic.MsQuicStream.WaitForWriteCompletionAsync
WaitForWriteCompletionAsync()
override ValueTask System.Net.Quic.Implementations.MsQuic.MsQuicStream.WaitForWriteCompletionAsync (CancellationToken cancellationToken = default(CancellationToken)) inline package
Definition at line 597 of file MsQuicStream.cs.
    {
        ThrowIfDisposed();
        lock (_state)
        {
            if (_state.ShutdownWriteState == ShutdownWriteState.ConnectionClosed)
            {
                throw GetConnectionAbortedException(_state);
            }
        }
        return new ValueTask(_state.ShutdownWriteCompletionSource.Task.WaitAsync(cancellationToken));
    }
References System.Net.Quic.Implementations.MsQuic.MsQuicStream._state, System.cancellationToken, System.Net.Quic.Implementations.MsQuic.MsQuicStream.GetConnectionAbortedException(), System.Net.Quic.Implementations.MsQuic.MsQuicStream.State.ShutdownWriteCompletionSource, System.Net.Quic.Implementations.MsQuic.MsQuicStream.State.ShutdownWriteState, System.Threading.Tasks.TaskCompletionSource< TResult >.Task, System.Net.Quic.Implementations.MsQuic.MsQuicStream.ThrowIfDisposed(), and System.Threading.Tasks.Task< TResult >.WaitAsync().