Terraria: System.Threading._ThreadPoolWaitOrTimerCallback.PerformWaitOrTimerCallback
PerformWaitOrTimerCallback()
static void System.Threading._ThreadPoolWaitOrTimerCallback.PerformWaitOrTimerCallback (_ThreadPoolWaitOrTimerCallback helper, bool timedOut) inline static package
Definition at line 41 of file _ThreadPoolWaitOrTimerCallback.cs.
    {
        ExecutionContext executionContext = helper._executionContext;
        if (executionContext == null)
        {
            WaitOrTimerCallback waitOrTimerCallback = helper._waitOrTimerCallback;
            waitOrTimerCallback(helper._state, timedOut);
        }
        else
        {
            ExecutionContext.Run(executionContext, timedOut ? _ccbt : _ccbf, helper);
        }
    }
References System.Threading._ThreadPoolWaitOrTimerCallback._ccbf, System.Threading._ThreadPoolWaitOrTimerCallback._ccbt, System.Threading._ThreadPoolWaitOrTimerCallback._executionContext, System.Threading._ThreadPoolWaitOrTimerCallback._state, System.Threading._ThreadPoolWaitOrTimerCallback._waitOrTimerCallback, System.Threading.ExecutionContext.Run(), and System.Threading.WaitOrTimerCallback().
Referenced by System.Threading.RegisteredWaitHandle.PerformCallback().