Terraria: System.Net.Quic.Implementations.MsQuic.MsQuicStream.CopyMsQuicBuffersToUserBuffer
CopyMsQuicBuffersToUserBuffer()
static unsafe int System.Net.Quic.Implementations.MsQuic.MsQuicStream.CopyMsQuicBuffersToUserBuffer (ReadOnlySpan< MsQuicNativeMethods::QuicBuffer > sourceBuffers, Span< byte > destinationBuffer) inline static private
Definition at line 496 of file MsQuicStream.cs.
    {
        if (sourceBuffers.Length == 0)
        {
            return 0;
        }
        int length = destinationBuffer.Length;
        int num = 0;
        int num2 = 0;
        do
        {
            MsQuicNativeMethods.QuicBuffer quicBuffer = sourceBuffers[num2];
            num = Math.Min((int)quicBuffer.Length, destinationBuffer.Length);
            new Span<byte>(quicBuffer.Buffer, num).CopyTo(destinationBuffer);
            destinationBuffer = destinationBuffer.Slice(num);
        }
        while (destinationBuffer.Length != 0 && ++num2 < sourceBuffers.Length);
        return length - destinationBuffer.Length;
    }
References System.Net.Quic.Implementations.MsQuic.Internal.MsQuicNativeMethods.QuicBuffer.Buffer, System.Span< T >.CopyTo(), System.length, System.Net.Quic.Implementations.MsQuic.Internal.MsQuicNativeMethods.QuicBuffer.Length, System.ReadOnlySpan< T >.Length, System.Span< T >.Length, System.Math.Min(), and System.Span< T >.Slice().
Referenced by System.Net.Quic.Implementations.MsQuic.MsQuicStream.HandleEventRecv(), and System.Net.Quic.Implementations.MsQuic.MsQuicStream.ReadAsync().