Terraria: System.Net.Quic.Implementations.MsQuic.MsQuicStream.HandleEventConnectionClose
HandleEventConnectionClose()
static uint System.Net.Quic.Implementations.MsQuic.MsQuicStream.HandleEventConnectionClose (State state) inline static private
Definition at line 1194 of file MsQuicStream.cs.
    {
        long abortErrorCode = state.ConnectionState.AbortErrorCode;
        if (System.Net.NetEventSource.Log.IsEnabled())
        {
            System.Net.NetEventSource.Info(state, state.TraceId + " Stream handling connection " + state.ConnectionState.TraceId + " close" + ((abortErrorCode != -1) ? $" with code {abortErrorCode}" : ""), "HandleEventConnectionClose");
        }
        bool flag = false;
        bool flag2 = false;
        bool flag3 = false;
        bool flag4 = false;
        lock (state)
        {
            flag = CleanupReadStateAndCheckPending(state, ReadState.ConnectionClosed);
            if (state.SendState == SendState.None || state.SendState == SendState.Pending)
            {
                flag2 = true;
            }
            state.SendState = SendState.ConnectionClosed;
            if (state.ShutdownWriteState == ShutdownWriteState.None)
            {
                flag3 = true;
            }
            state.ShutdownWriteState = ShutdownWriteState.ConnectionClosed;
            if (state.ShutdownState == ShutdownState.None)
            {
                flag4 = true;
            }
            state.ShutdownState = ShutdownState.ConnectionClosed;
        }
        if (flag)
        {
            state.ReceiveResettableCompletionSource.CompleteException(ExceptionDispatchInfo.SetCurrentStackTrace(GetConnectionAbortedException(state)));
        }
        if (flag2)
        {
            state.SendResettableCompletionSource.CompleteException(ExceptionDispatchInfo.SetCurrentStackTrace(GetConnectionAbortedException(state)));
        }
        if (flag3)
        {
            state.ShutdownWriteCompletionSource.SetException(ExceptionDispatchInfo.SetCurrentStackTrace(GetConnectionAbortedException(state)));
        }
        if (flag4)
        {
            state.ShutdownCompletionSource.SetException(ExceptionDispatchInfo.SetCurrentStackTrace(GetConnectionAbortedException(state)));
        }
        if (Interlocked.Exchange(ref state.ShutdownDone, 2) == 1)
        {
            state.Cleanup();
        }
        return 0u;
    }
References System.Net.Quic.Implementations.MsQuic.MsQuicStream.CleanupReadStateAndCheckPending(), System.Threading.Interlocked.Exchange(), System.Net.Quic.Implementations.MsQuic.MsQuicStream.GetConnectionAbortedException(), System.Net.NetEventSource.Info(), System.Net.NetEventSource.Log, System.Runtime.ExceptionServices.ExceptionDispatchInfo.SetCurrentStackTrace(), and System.state.
Referenced by System.Net.Quic.Implementations.MsQuic.MsQuicStream.HandleEventShutdownComplete().