Terraria: System.Net.Quic.Implementations.MsQuic.MsQuicStream.StartShutdown
StartShutdown()
void System.Net.Quic.Implementations.MsQuic.MsQuicStream.StartShutdown (QUIC_STREAM_SHUTDOWN_FLAGS flags, long errorCode) inline private
Definition at line 559 of file MsQuicStream.cs.
    {
        uint status = MsQuicApi.Api.StreamShutdownDelegate(_state.Handle, flags, errorCode);
        QuicExceptionHelpers.ThrowIfFailed(status, "StreamShutdown failed.");
    }
References System.Net.Quic.Implementations.MsQuic.MsQuicStream._state, System.Net.Quic.Implementations.MsQuic.Internal.MsQuicApi.Api, System.Net.Quic.Implementations.MsQuic.MsQuicStream.State.Handle, and System.Net.Quic.Implementations.MsQuic.Internal.QuicExceptionHelpers.ThrowIfFailed().
Referenced by System.Net.Quic.Implementations.MsQuic.MsQuicStream.AbortRead(), System.Net.Quic.Implementations.MsQuic.MsQuicStream.AbortWrite(), System.Net.Quic.Implementations.MsQuic.MsQuicStream.Dispose(), System.Net.Quic.Implementations.MsQuic.MsQuicStream.SendReadOnlyMemoryAsync(), System.Net.Quic.Implementations.MsQuic.MsQuicStream.SendReadOnlyMemoryListAsync(), System.Net.Quic.Implementations.MsQuic.MsQuicStream.SendReadOnlySequenceAsync(), and System.Net.Quic.Implementations.MsQuic.MsQuicStream.Shutdown().