Terraria: Terraria.GameContent.UI.Elements.UIResourcePack.DrawSelf
DrawSelf()
override void Terraria.GameContent.UI.Elements.UIResourcePack.DrawSelf (SpriteBatch spriteBatch) inline protected virtual
Reimplemented from Terraria.GameContent.UI.Elements.UIPanel.
Definition at line 98 of file UIResourcePack.cs.
    {
        base.DrawSelf(spriteBatch);
        DrawIcon(spriteBatch);
        if (ResourcePack.Branding == ResourcePack.BrandingType.SteamWorkshop)
        {
            Asset<Texture2D> val = TextureAssets.Extra[243];
            spriteBatch.Draw(val.Value, new Vector2(GetDimensions().X + GetDimensions().Width - (float)val.Width() - 3f, GetDimensions().Y + 2f), val.Frame(), Color.White);
        }
    }
References Terraria.IO.ResourcePack.Branding, Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(), Terraria.GameContent.UI.Elements.UIResourcePack.DrawIcon(), Terraria.GameContent.TextureAssets.Extra, Terraria.UI.UIElement.GetDimensions(), ReLogic.Content.Asset< T >.Value, Microsoft.Xna.Framework.Color.White, and Terraria.UI.UIElement.Width.