Terraria: Terraria.GameContent.UI.Elements.UIResourcePack.UIResourcePack
UIResourcePack()
Terraria.GameContent.UI.Elements.UIResourcePack.UIResourcePack (ResourcePack pack, int order) inline
Definition at line 40 of file UIResourcePack.cs.
    {
        ResourcePack = pack;
        Order = order;
        BackgroundColor = DefaultBackgroundColor;
        BorderColor = DefaultBorderColor;
        Height = StyleDimension.FromPixels(102f);
        MinHeight = Height;
        MaxHeight = Height;
        MinWidth = StyleDimension.FromPixels(102f);
        Width = StyleDimension.FromPercent(1f);
        SetPadding(5f);
        _iconBorderTexture = Main.Assets.Request<Texture2D>("Images/UI/Achievement_Borders", (AssetRequestMode)1);
        OverflowHidden = true;
        BuildChildren();
    }
References Terraria.GameContent.UI.Elements.UIResourcePack._iconBorderTexture, Terraria.Main.Assets, Terraria.GameContent.UI.Elements.UIPanel.BackgroundColor, Terraria.GameContent.UI.Elements.UIPanel.BorderColor, Terraria.GameContent.UI.Elements.UIResourcePack.BuildChildren(), Terraria.GameContent.UI.Elements.UIResourcePack.DefaultBackgroundColor, Terraria.GameContent.UI.Elements.UIResourcePack.DefaultBorderColor, Terraria.UI.StyleDimension.FromPercent(), Terraria.UI.StyleDimension.FromPixels(), Terraria.UI.UIElement.Height, Terraria.UI.UIElement.MaxHeight, Terraria.UI.UIElement.MinHeight, Terraria.UI.UIElement.MinWidth, Terraria.GameContent.UI.Elements.UIResourcePack.Order, Terraria.UI.UIElement.OverflowHidden, Terraria.UI.UIElement.SetPadding(), and Terraria.UI.UIElement.Width.