Terraria: Terraria.GameContent.UI.Elements.UIResourcePack.DrawIcon
DrawIcon()
void Terraria.GameContent.UI.Elements.UIResourcePack.DrawIcon (SpriteBatch spriteBatch) inline private
Definition at line 109 of file UIResourcePack.cs.
    {
        CalculatedStyle innerDimensions = GetInnerDimensions();
        spriteBatch.Draw(ResourcePack.Icon, new Rectangle((int)innerDimensions.X + 4, (int)innerDimensions.Y + 4 + 10, 64, 64), Color.White);
        spriteBatch.Draw(_iconBorderTexture.Value, new Rectangle((int)innerDimensions.X, (int)innerDimensions.Y + 10, 72, 72), Color.White);
    }
References Terraria.GameContent.UI.Elements.UIResourcePack._iconBorderTexture, Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(), Terraria.UI.UIElement.GetInnerDimensions(), Terraria.IO.ResourcePack.Icon, ReLogic.Content.Asset< T >.Value, Microsoft.Xna.Framework.Color.White, Terraria.UI.CalculatedStyle.X, and Terraria.UI.CalculatedStyle.Y.
Referenced by Terraria.GameContent.UI.Elements.UIResourcePack.DrawSelf().