Terraria: BestiaryUnlocksTracker.Load
Load()
void BestiaryUnlocksTracker.Load (BinaryReader reader, int gameVersionSaveWasMadeOn) inline
Implements IPersistentPerWorldContent.
     {
         Kills.Load(reader, gameVersionSaveWasMadeOn);
         Sights.Load(reader, gameVersionSaveWasMadeOn);
         Chats.Load(reader, gameVersionSaveWasMadeOn);
     }
References Chats, Kills, NPCKillsTracker.Load(), NPCWasChatWithTracker.Load(), NPCWasNearPlayerTracker.Load(), and Sights.
Referenced by WorldFile.LoadBestiary().