Terraria: System.Reflection.PortableExecutable.PEHeaders.PEHeaders
PEHeaders() [3/3]
System.Reflection.PortableExecutable.PEHeaders.PEHeaders (Stream peStream, int size, bool isLoadedImage) inline
Definition at line 83 of file PEHeaders.cs.
    {
        if (peStream == null)
        {
            throw new ArgumentNullException("peStream");
        }
        if (!peStream.CanRead || !peStream.CanSeek)
        {
            throw new ArgumentException(System.SR.StreamMustSupportReadAndSeek, "peStream");
        }
        _isLoadedImage = isLoadedImage;
        int andValidateSize = StreamExtensions.GetAndValidateSize(peStream, size, "peStream");
        PEBinaryReader reader = new PEBinaryReader(peStream, andValidateSize);
        SkipDosHeader(ref reader, out var isCOFFOnly);
        _coffHeaderStartOffset = reader.CurrentOffset;
        _coffHeader = new CoffHeader(ref reader);
        if (!isCOFFOnly)
        {
            _peHeaderStartOffset = reader.CurrentOffset;
            _peHeader = new PEHeader(ref reader);
        }
        _sectionHeaders = ReadSectionHeaders(ref reader);
        if (!isCOFFOnly && TryCalculateCorHeaderOffset(andValidateSize, out var startOffset))
        {
            _corHeaderStartOffset = startOffset;
            reader.Seek(startOffset);
            _corHeader = new CorHeader(ref reader);
        }
        CalculateMetadataLocation(andValidateSize, out _metadataStartOffset, out _metadataSize);
    }
References System.Reflection.PortableExecutable.PEHeaders._coffHeader, System.Reflection.PortableExecutable.PEHeaders._coffHeaderStartOffset, System.Reflection.PortableExecutable.PEHeaders._corHeader, System.Reflection.PortableExecutable.PEHeaders._corHeaderStartOffset, System.Reflection.PortableExecutable.PEHeaders._isLoadedImage, System.Reflection.PortableExecutable.PEHeaders._metadataSize, System.Reflection.PortableExecutable.PEHeaders._metadataStartOffset, System.Reflection.PortableExecutable.PEHeaders._peHeader, System.Reflection.PortableExecutable.PEHeaders._peHeaderStartOffset, System.Reflection.PortableExecutable.PEHeaders._sectionHeaders, System.Reflection.PortableExecutable.PEHeaders.CalculateMetadataLocation(), System.IO.Stream.CanRead, System.IO.Stream.CanSeek, System.Reflection.PortableExecutable.PEHeaders.CoffHeader, System.Reflection.PortableExecutable.PEHeaders.CorHeader, System.Reflection.PortableExecutable.PEBinaryReader.CurrentOffset, System.Reflection.Internal.StreamExtensions.GetAndValidateSize(), System.Reflection.PortableExecutable.PEHeaders.PEHeader, System.Reflection.PortableExecutable.PEHeaders.ReadSectionHeaders(), System.Reflection.PortableExecutable.PEBinaryReader.Seek(), System.Reflection.PortableExecutable.PEHeaders.SkipDosHeader(), System.SR.StreamMustSupportReadAndSeek, and System.Reflection.PortableExecutable.PEHeaders.TryCalculateCorHeaderOffset().