Terraria: System.Reflection.PortableExecutable.PEHeaders.CalculateMetadataLocation
CalculateMetadataLocation()
void System.Reflection.PortableExecutable.PEHeaders.CalculateMetadataLocation (long peImageSize, out int start, out int size) inline private
Definition at line 219 of file PEHeaders.cs.
    {
        if (IsCoffOnly)
        {
            int num = IndexOfSection(".cormeta");
            if (num == -1)
            {
                start = -1;
                size = 0;
                return;
            }
            if (_isLoadedImage)
            {
                start = SectionHeaders[num].VirtualAddress;
                size = SectionHeaders[num].VirtualSize;
            }
            else
            {
                start = SectionHeaders[num].PointerToRawData;
                size = SectionHeaders[num].SizeOfRawData;
            }
        }
        else
        {
            if (_corHeader == null)
            {
                start = 0;
                size = 0;
                return;
            }
            if (!TryGetDirectoryOffset(_corHeader.MetadataDirectory, out start, canCrossSectionBoundary: false))
            {
                throw new BadImageFormatException(System.SR.MissingDataDirectory);
            }
            size = _corHeader.MetadataDirectory.Size;
        }
        if (start < 0 || start >= peImageSize || size <= 0 || start > peImageSize - size)
        {
            throw new BadImageFormatException(System.SR.InvalidMetadataSectionSpan);
        }
    }
References System.Reflection.PortableExecutable.PEHeaders._corHeader, System.Reflection.PortableExecutable.PEHeaders._isLoadedImage, System.Reflection.PortableExecutable.PEHeaders.IndexOfSection(), System.SR.InvalidMetadataSectionSpan, System.Reflection.PortableExecutable.PEHeaders.IsCoffOnly, System.Reflection.PortableExecutable.CorHeader.MetadataDirectory, System.SR.MissingDataDirectory, System.Reflection.PortableExecutable.PEHeaders.SectionHeaders, System.Reflection.PortableExecutable.DirectoryEntry.Size, System.start, and System.Reflection.PortableExecutable.PEHeaders.TryGetDirectoryOffset().
Referenced by System.Reflection.PortableExecutable.PEHeaders.PEHeaders().