Terraria: System.Runtime.Serialization.XmlDataContract.GenerateCreateXmlSerializableDelegate
GenerateCreateXmlSerializableDelegate()
CreateXmlSerializableDelegate System.Runtime.Serialization.XmlDataContract.GenerateCreateXmlSerializableDelegate () inline package
Definition at line 315 of file XmlDataContract.cs.
    {
        Type underlyingType = base.UnderlyingType;
        CodeGenerator codeGenerator = new CodeGenerator();
        bool flag = RequiresMemberAccessForCreate(null) && !(underlyingType.FullName == "System.Xml.Linq.XElement");
        try
        {
            codeGenerator.BeginMethod("Create" + DataContract.GetClrTypeFullName(underlyingType), typeof(CreateXmlSerializableDelegate), flag);
        }
        catch (SecurityException securityException)
        {
            if (!flag)
            {
                throw;
            }
            RequiresMemberAccessForCreate(securityException);
        }
        if (underlyingType.IsValueType)
        {
            LocalBuilder localBuilder = codeGenerator.DeclareLocal(underlyingType, underlyingType.Name + "Value");
            codeGenerator.Ldloca(localBuilder);
            codeGenerator.InitObj(underlyingType);
            codeGenerator.Ldloc(localBuilder);
        }
        else
        {
            ConstructorInfo constructorInfo = GetConstructor();
            if (!constructorInfo.IsPublic && underlyingType.FullName == "System.Xml.Linq.XElement")
            {
                Type type = underlyingType.Assembly.GetType("System.Xml.Linq.XName");
                if (type != null)
                {
                    MethodInfo method = type.GetMethod("op_Implicit", BindingFlags.Static | BindingFlags.Public | BindingFlags.NonPublic, new Type[1] { typeof(string) });
                    ConstructorInfo constructor = underlyingType.GetConstructor(BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, new Type[1] { type });
                    if (method != null && constructor != null)
                    {
                        codeGenerator.Ldstr("default");
                        codeGenerator.Call(method);
                        constructorInfo = constructor;
                    }
                }
            }
            codeGenerator.New(constructorInfo);
        }
        codeGenerator.ConvertValue(base.UnderlyingType, Globals.TypeOfIXmlSerializable);
        codeGenerator.Ret();
        return (CreateXmlSerializableDelegate)codeGenerator.EndMethod();
    }
References System.Runtime.Serialization.Dictionary, System.Runtime.Serialization.DataContract.GetClrTypeFullName(), System.Runtime.Serialization.XmlDataContract.GetConstructor(), System.Runtime.Serialization.XmlDataContract.RequiresMemberAccessForCreate(), System.type, and System.Runtime.Serialization.Globals.TypeOfIXmlSerializable.