Terraria: System.Runtime.Serialization.XmlDataContract.RequiresMemberAccessForCreate
RequiresMemberAccessForCreate()
bool System.Runtime.Serialization.XmlDataContract.RequiresMemberAccessForCreate (SecurityException securityException) inline private
Definition at line 364 of file XmlDataContract.cs.
    {
        if (!DataContract.IsTypeVisible(base.UnderlyingType))
        {
            if (securityException != null)
            {
                throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new SecurityException(System.SR.Format(System.SR.PartialTrustIXmlSerializableTypeNotPublic, DataContract.GetClrTypeFullName(base.UnderlyingType)), securityException));
            }
            return true;
        }
        if (DataContract.ConstructorRequiresMemberAccess(GetConstructor()))
        {
            if (securityException != null)
            {
                throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new SecurityException(System.SR.Format(System.SR.PartialTrustIXmlSerialzableNoPublicConstructor, DataContract.GetClrTypeFullName(base.UnderlyingType)), securityException));
            }
            return true;
        }
        return false;
    }
References System.Runtime.Serialization.DataContract.ConstructorRequiresMemberAccess(), System.SR.Format(), System.Runtime.Serialization.DataContract.GetClrTypeFullName(), System.Runtime.Serialization.XmlDataContract.GetConstructor(), System.Runtime.Serialization.DataContract.IsTypeVisible(), System.SR.PartialTrustIXmlSerializableTypeNotPublic, System.SR.PartialTrustIXmlSerialzableNoPublicConstructor, and System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperError().
Referenced by System.Runtime.Serialization.XmlDataContract.GenerateCreateXmlSerializableDelegate().