Terraria: Terraria.Player.RabbitOrderFrameHelper.Update
Update()
void Terraria.Player.RabbitOrderFrameHelper.Update () inline
        {
            switch (_aiState)
            {
            case 0:
                UpdateFrame(0, 0, Main.rand.Next(1, 4), Main.rand.Next(180, 3600));
                break;
            case 1:
                UpdateFrame(7, 9, 0, 20);
                break;
            case 2:
            {
                int gameFramesPerDisplayFrame = 8;
                if (DisplayFrame == 13)
                {
                    gameFramesPerDisplayFrame = 120;
                }
                UpdateFrame(10, 16, 0, gameFramesPerDisplayFrame);
                break;
            }
            case 3:
                UpdateFrame(17, 26, 0, 4);
                break;
            }
        }
References Terraria.Player.RabbitOrderFrameHelper._aiState, Terraria.Player.RabbitOrderFrameHelper.DisplayFrame, Terraria.Utilities.UnifiedRandom.Next(), Terraria.Main.rand, and Terraria.Player.RabbitOrderFrameHelper.UpdateFrame().
Referenced by Terraria.Player.RabbitOrderFrameHelper.ChangeToAIState().