Terraria: UIManageControls.CreateElementGroup
CreateElementGroup()
void UIManageControls.CreateElementGroup (UIList parent, List< string > bindings, InputMode currentInputMode, Color color) inline private
     {
         for (int i = 0; i < bindings.Count; i++)
         {
             _ = bindings[i];
             UISortableElement uISortableElement = new UISortableElement(i);
             uISortableElement.Width.Set(0f, 1f);
             uISortableElement.Height.Set(30f, 0f);
             uISortableElement.HAlign = 0.5f;
             parent.Add(uISortableElement);
             if (_BindingsHalfSingleLine.Contains(bindings[i]))
             {
                 UIElement uIElement = CreatePanel(bindings[i], currentInputMode, color);
                 uIElement.Width.Set(0f, 0.5f);
                 uIElement.HAlign = 0.5f;
                 uIElement.Height.Set(0f, 1f);
                 uIElement.SetSnapPoint("Wide", SnapPointIndex++);
                 uISortableElement.Append(uIElement);
                 continue;
             }
             if (_BindingsFullLine.Contains(bindings[i]))
             {
                 UIElement uIElement2 = CreatePanel(bindings[i], currentInputMode, color);
                 uIElement2.Width.Set(0f, 1f);
                 uIElement2.Height.Set(0f, 1f);
                 uIElement2.SetSnapPoint("Wide", SnapPointIndex++);
                 uISortableElement.Append(uIElement2);
                 continue;
             }
             UIElement uIElement3 = CreatePanel(bindings[i], currentInputMode, color);
             uIElement3.Width.Set(-5f, 0.5f);
             uIElement3.Height.Set(0f, 1f);
             uIElement3.SetSnapPoint("Thin", SnapPointIndex++);
             uISortableElement.Append(uIElement3);
             i++;
             if (i < bindings.Count)
             {
                 uIElement3 = CreatePanel(bindings[i], currentInputMode, color);
                 uIElement3.Width.Set(-5f, 0.5f);
                 uIElement3.Height.Set(0f, 1f);
                 uIElement3.HAlign = 1f;
                 uIElement3.SetSnapPoint("Thin", SnapPointIndex++);
                 uISortableElement.Append(uIElement3);
             }
         }
     }
References _BindingsFullLine, _BindingsHalfSingleLine, UIList.Add(), UIElement.Append(), CreatePanel(), UIElement.HAlign, UIElement.Height, StyleDimension.Set(), UIElement.SetSnapPoint(), SnapPointIndex, and UIElement.Width.
Referenced by CreateBindingGroup().