Terraria: UIManageControls.CreateBindingGroup
CreateBindingGroup()
UISortableElement UIManageControls.CreateBindingGroup (int elementIndex, List< string > bindings, InputMode currentInputMode) inline private
     {
         UISortableElement uISortableElement = new UISortableElement(elementIndex);
         uISortableElement.HAlign = 0.5f;
         uISortableElement.Width.Set(0f, 1f);
         uISortableElement.Height.Set(2000f, 0f);
         UIPanel uIPanel = new UIPanel();
         uIPanel.Width.Set(0f, 1f);
         uIPanel.Height.Set(-16f, 1f);
         uIPanel.VAlign = 1f;
         uIPanel.BackgroundColor = new Color(33, 43, 79) * 0.8f;
         uISortableElement.Append(uIPanel);
         UIList uIList = new UIList();
         uIList.OverflowHidden = false;
         uIList.Width.Set(0f, 1f);
         uIList.Height.Set(-8f, 1f);
         uIList.VAlign = 1f;
         uIList.ListPadding = 5f;
         uIPanel.Append(uIList);
         _ = uIPanel.BackgroundColor;
         switch (elementIndex)
         {
         case 0:
             uIPanel.BackgroundColor = Color.Lerp(uIPanel.BackgroundColor, Color.Green, 0.18f);
             break;
         case 1:
             uIPanel.BackgroundColor = Color.Lerp(uIPanel.BackgroundColor, Color.Goldenrod, 0.18f);
             break;
         case 2:
             uIPanel.BackgroundColor = Color.Lerp(uIPanel.BackgroundColor, Color.HotPink, 0.18f);
             break;
         case 3:
             uIPanel.BackgroundColor = Color.Lerp(uIPanel.BackgroundColor, Color.Indigo, 0.18f);
             break;
         case 4:
             uIPanel.BackgroundColor = Color.Lerp(uIPanel.BackgroundColor, Color.Turquoise, 0.18f);
             break;
         }
         CreateElementGroup(uIList, bindings, currentInputMode, uIPanel.BackgroundColor);
         uIPanel.BackgroundColor = uIPanel.BackgroundColor.MultiplyRGBA(new Color(111, 111, 111));
         LocalizedText text = LocalizedText.Empty;
         switch (elementIndex)
         {
         case 0:
             text = ((currentInputMode == InputMode.Keyboard || currentInputMode == InputMode.XBoxGamepad) ? Lang.menu[164] : Lang.menu[243]);
             break;
         case 1:
             text = Lang.menu[165];
             break;
         case 2:
             text = Lang.menu[166];
             break;
         case 3:
             text = Lang.menu[167];
             break;
         case 4:
             text = Lang.menu[198];
             break;
         }
         UITextPanel<LocalizedText> element = new UITextPanel<LocalizedText>(text, 0.7f)
         {
             VAlign = 0f,
             HAlign = 0.5f
         };
         uISortableElement.Append(element);
         uISortableElement.Recalculate();
         float totalHeight = uIList.GetTotalHeight();
         uISortableElement.Width.Set(0f, 1f);
         uISortableElement.Height.Set(totalHeight + 30f + 16f, 0f);
         return uISortableElement;
     }
References UIElement.Append(), UIPanel.BackgroundColor, Color, CreateElementGroup(), LocalizedText.Empty, UIList.GetTotalHeight(), UIElement.HAlign, UIElement.Height, UIList.ListPadding, Lang.menu, UIElement.OverflowHidden, UIElement.Recalculate(), StyleDimension.Set(), UIElement.VAlign, and UIElement.Width.
Referenced by AssembleBindPanels().