Terraria: System.Net.Sockets.NetworkStream.Read
Read() [2/2]
override int System.Net.Sockets.NetworkStream.Read (Span< byte > buffer) inline virtual
Reimplemented from System.IO.Stream.
Definition at line 204 of file NetworkStream.cs.
    {
        if (GetType() != typeof(NetworkStream))
        {
            return base.Read(buffer);
        }
        ThrowIfDisposed();
        if (!CanRead)
        {
            throw new InvalidOperationException(System.SR.net_writeonlystream);
        }
        try
        {
            return _streamSocket.Receive(buffer, SocketFlags.None);
        }
        catch (Exception ex) when (!(ex is OutOfMemoryException))
        {
            throw WrapException(System.SR.net_io_readfailure, ex);
        }
    }
References System.Net.Sockets.NetworkStream._streamSocket, System.buffer, System.Net.Sockets.NetworkStream.CanRead, System.SR.net_io_readfailure, System.SR.net_writeonlystream, System.Net.Sockets.Socket.Receive(), System.Net.Sockets.NetworkStream.ThrowIfDisposed(), and System.Net.Sockets.NetworkStream.WrapException().