Terraria: System.Net.Sockets.NetworkStream.WrapException
WrapException()
static IOException System.Net.Sockets.NetworkStream.WrapException (string resourceFormatString, Exception innerException) inline static private
Definition at line 500 of file NetworkStream.cs.
    {
        return new IOException(System.SR.Format(resourceFormatString, innerException.Message), innerException);
    }
References System.SR.Format(), and System.Exception.Message.
Referenced by System.Net.Sockets.NetworkStream.BeginRead(), System.Net.Sockets.NetworkStream.BeginWrite(), System.Net.Sockets.NetworkStream.EndRead(), System.Net.Sockets.NetworkStream.EndWrite(), System.Net.Sockets.NetworkStream.Read(), System.Net.Sockets.NetworkStream.Read(), System.Net.Sockets.NetworkStream.ReadAsync(), System.Net.Sockets.NetworkStream.ReadAsync(), System.Net.Sockets.NetworkStream.Write(), System.Net.Sockets.NetworkStream.Write(), System.Net.Sockets.NetworkStream.WriteAsync(), and System.Net.Sockets.NetworkStream.WriteAsync().