Terraria: System.Net.Sockets.NetworkStream.Read
Read() [1/2]
override int System.Net.Sockets.NetworkStream.Read (byte[] buffer, int offset, int count) inline
Definition at line 186 of file NetworkStream.cs.
    {
        Stream.ValidateBufferArguments(buffer, offset, count);
        ThrowIfDisposed();
        if (!CanRead)
        {
            throw new InvalidOperationException(System.SR.net_writeonlystream);
        }
        try
        {
            return _streamSocket.Receive(buffer, offset, count, SocketFlags.None);
        }
        catch (Exception ex) when (!(ex is OutOfMemoryException))
        {
            throw WrapException(System.SR.net_io_readfailure, ex);
        }
    }
References System.Net.Sockets.NetworkStream._streamSocket, System.buffer, System.Net.Sockets.NetworkStream.CanRead, System.count, System.SR.net_io_readfailure, System.SR.net_writeonlystream, System.offset, System.Net.Sockets.Socket.Receive(), System.Net.Sockets.NetworkStream.ThrowIfDisposed(), System.IO.Stream.ValidateBufferArguments(), and System.Net.Sockets.NetworkStream.WrapException().
Referenced by System.Net.FtpDataStream.Read(), and System.Net.NetworkStreamWrapper.Read().