Terraria: System.Net.Sockets.NetworkStream.BeginRead
BeginRead()
override IAsyncResult System.Net.Sockets.NetworkStream.BeginRead (byte[] buffer, int offset, int count, AsyncCallback? callback, object? state) inline virtual
Reimplemented from System.IO.Stream.
Definition at line 314 of file NetworkStream.cs.
    {
        Stream.ValidateBufferArguments(buffer, offset, count);
        ThrowIfDisposed();
        if (!CanRead)
        {
            throw new InvalidOperationException(System.SR.net_writeonlystream);
        }
        try
        {
            return _streamSocket.BeginReceive(buffer, offset, count, SocketFlags.None, callback, state);
        }
        catch (Exception ex) when (!(ex is OutOfMemoryException))
        {
            throw WrapException(System.SR.net_io_readfailure, ex);
        }
    }
References System.Net.Sockets.NetworkStream._streamSocket, System.Net.Sockets.Socket.BeginReceive(), System.buffer, System.Net.Sockets.NetworkStream.CanRead, System.count, System.SR.net_io_readfailure, System.SR.net_writeonlystream, System.offset, System.state, System.Net.Sockets.NetworkStream.ThrowIfDisposed(), System.IO.Stream.ValidateBufferArguments(), and System.Net.Sockets.NetworkStream.WrapException().
Referenced by Terraria.Net.Sockets.TcpSocket.AsyncReceive(), System.Net.FtpDataStream.BeginRead(), and System.Net.NetworkStreamWrapper.BeginRead().