Terraria: System.Net.Sockets.NetworkStream.Dispose
Dispose() [2/2]
override void System.Net.Sockets.NetworkStream.Dispose (bool disposing) inline protected virtual
Reimplemented from System.IO.Stream.
Definition at line 290 of file NetworkStream.cs.
    {
        if (Interlocked.Exchange(ref _disposed, 1) != 0)
        {
            return;
        }
        if (disposing)
        {
            _readable = false;
            _writeable = false;
            if (_ownsSocket)
            {
                _streamSocket.InternalShutdown(SocketShutdown.Both);
                _streamSocket.Close(_closeTimeout);
            }
        }
        base.Dispose(disposing);
    }
References System.Net.Sockets.NetworkStream._closeTimeout, System.Net.Sockets.NetworkStream._disposed, System.Net.Sockets.NetworkStream._ownsSocket, System.Net.Sockets.NetworkStream._readable, System.Net.Sockets.NetworkStream._streamSocket, System.Net.Sockets.NetworkStream._writeable, System.Net.Sockets.Socket.Close(), System.Threading.Interlocked.Exchange(), and System.Net.Sockets.Socket.InternalShutdown().
Referenced by System.Net.HttpWebRequest.CreateHttpClient().