Terraria: System.Net.Sockets.NetworkStream.EndWrite
EndWrite()
override void System.Net.Sockets.NetworkStream.EndWrite (IAsyncResult asyncResult) inline virtual
Reimplemented from System.IO.Stream.
Reimplemented in System.Net.TlsStream, and System.Net.TlsStream.
Definition at line 367 of file NetworkStream.cs.
    {
        ThrowIfDisposed();
        if (asyncResult == null)
        {
            throw new ArgumentNullException("asyncResult");
        }
        try
        {
            _streamSocket.EndSend(asyncResult);
        }
        catch (Exception ex) when (!(ex is OutOfMemoryException))
        {
            throw WrapException(System.SR.net_io_writefailure, ex);
        }
    }
References System.Net.Sockets.NetworkStream._streamSocket, System.asyncResult, System.Net.Sockets.Socket.EndSend(), System.SR.net_io_writefailure, System.Net.Sockets.NetworkStream.ThrowIfDisposed(), and System.Net.Sockets.NetworkStream.WrapException().
Referenced by System.Net.Mail.SmtpConnection.EndFlush(), System.Net.FtpDataStream.EndWrite(), System.Net.NetworkStreamWrapper.EndWrite(), and Terraria.Net.Sockets.TcpSocket.SendCallback().