Terraria: System.Net.Sockets.NetworkStream.Write
Write() [2/2]
override void System.Net.Sockets.NetworkStream.Write (ReadOnlySpan< byte > buffer) inline virtual
Reimplemented from System.IO.Stream.
Definition at line 253 of file NetworkStream.cs.
    {
        if (GetType() != typeof(NetworkStream))
        {
            base.Write(buffer);
            return;
        }
        ThrowIfDisposed();
        if (!CanWrite)
        {
            throw new InvalidOperationException(System.SR.net_readonlystream);
        }
        try
        {
            _streamSocket.Send(buffer, SocketFlags.None);
        }
        catch (Exception ex) when (!(ex is OutOfMemoryException))
        {
            throw WrapException(System.SR.net_io_writefailure, ex);
        }
    }
References System.Net.Sockets.NetworkStream._streamSocket, System.buffer, System.Net.Sockets.NetworkStream.CanWrite, System.SR.net_io_writefailure, System.SR.net_readonlystream, System.Net.Sockets.Socket.Send(), System.Net.Sockets.NetworkStream.ThrowIfDisposed(), and System.Net.Sockets.NetworkStream.WrapException().