Terraria: System.Net.Sockets.NetworkStream.WriteAsync
WriteAsync() [3/3]
override ValueTask System.Net.Sockets.NetworkStream.WriteAsync (ReadOnlyMemory< byte > buffer, CancellationToken cancellationToken) inline virtual
Reimplemented from System.IO.Stream.
Definition at line 438 of file NetworkStream.cs.
    {
        bool canWrite = CanWrite;
        ThrowIfDisposed();
        if (!canWrite)
        {
            throw new InvalidOperationException(System.SR.net_readonlystream);
        }
        try
        {
            return _streamSocket.SendAsyncForNetworkStream(buffer, SocketFlags.None, cancellationToken);
        }
        catch (Exception ex) when (!(ex is OutOfMemoryException))
        {
            throw WrapException(System.SR.net_io_writefailure, ex);
        }
    }
References System.Net.Sockets.NetworkStream._streamSocket, System.buffer, System.cancellationToken, System.Net.Sockets.NetworkStream.CanWrite, System.SR.net_io_writefailure, System.SR.net_readonlystream, System.Net.Sockets.Socket.SendAsyncForNetworkStream(), System.Net.Sockets.NetworkStream.ThrowIfDisposed(), and System.Net.Sockets.NetworkStream.WrapException().