Terraria: System.Security.Cryptography.ECCngKey.FullDispose
FullDispose()
void System.Security.Cryptography.ECCngKey.FullDispose () inline package
Definition at line 139 of file ECCngKey.cs.
    {
        DisposeKey();
        _disposed = true;
    }
References System.Security.Cryptography.ECCngKey._disposed, and System.Security.Cryptography.ECCngKey.DisposeKey().
Referenced by System.Security.Cryptography.ECDiffieHellmanImplementation.ECDiffieHellmanCng.Dispose(), and System.Security.Cryptography.ECDsaImplementation.ECDsaCng.Dispose().