Terraria: System.Security.Cryptography.ECCngKey.GetCurveName
GetCurveName()
string System.Security.Cryptography.ECCngKey.GetCurveName (int callerKeySizeProperty, out string oidValue) inline package
Definition at line 27 of file ECCngKey.cs.
    {
        using SafeNCryptKeyHandle ncryptHandle = GetDuplicatedKeyHandle(callerKeySizeProperty);
        string lastAlgorithm = _lastAlgorithm;
        if (ECCng.IsECNamedCurve(lastAlgorithm))
        {
            oidValue = null;
            return CngKeyLite.GetCurveName(ncryptHandle);
        }
        return ECCng.SpecialNistAlgorithmToCurveName(lastAlgorithm, out oidValue);
    }
References System.Security.Cryptography.ECCngKey._lastAlgorithm, System.Security.Cryptography.CngKeyLite.GetCurveName(), System.Security.Cryptography.ECCngKey.GetDuplicatedKeyHandle(), System.Security.Cryptography.ECCng.IsECNamedCurve(), and System.Security.Cryptography.ECCng.SpecialNistAlgorithmToCurveName().
Referenced by System.Security.Cryptography.ECDiffieHellmanImplementation.ECDiffieHellmanCng.GetCurveName(), and System.Security.Cryptography.ECDsaImplementation.ECDsaCng.GetCurveName().