Terraria: System.Security.Cryptography.ECCngKey.GenerateKey
GenerateKey()
void System.Security.Cryptography.ECCngKey.GenerateKey (ECCurve curve) inline package
Definition at line 68 of file ECCngKey.cs.
    {
        curve.Validate();
        ThrowIfDisposed();
        if (_keyHandle != null)
        {
            DisposeKey();
        }
        int num = 0;
        string text;
        if (curve.IsNamed)
        {
            if (string.IsNullOrEmpty(curve.Oid.FriendlyName))
            {
                throw new PlatformNotSupportedException(System.SR.Format(System.SR.Cryptography_InvalidCurveOid, curve.Oid.Value));
            }
            text = ((!(_algorithmGroup == "ECDSA")) ? ECCng.EcdhCurveNameToAlgorithm(curve.Oid.FriendlyName) : ECCng.EcdsaCurveNameToAlgorithm(curve.Oid.FriendlyName));
            if (ECCng.IsECNamedCurve(text))
            {
                try
                {
                    _keyHandle = CngKeyLite.GenerateNewExportableKey(text, curve.Oid.FriendlyName);
                    num = CngKeyLite.GetKeyLength(_keyHandle);
                }
                catch (CryptographicException ex)
                {
                    global::Interop.NCrypt.ErrorCode hResult = (global::Interop.NCrypt.ErrorCode)ex.HResult;
                    if ((curve.IsNamed && hResult == global::Interop.NCrypt.ErrorCode.NTE_INVALID_PARAMETER) || hResult == global::Interop.NCrypt.ErrorCode.NTE_NOT_SUPPORTED)
                    {
                        throw new PlatformNotSupportedException(System.SR.Format(System.SR.Cryptography_CurveNotSupported, curve.Oid.FriendlyName), ex);
                    }
                    throw;
                }
            }
            else
            {
                switch (text)
                {
                case "ECDSA_P256":
                case "ECDH_P256":
                    num = 256;
                    break;
                case "ECDSA_P384":
                case "ECDH_P384":
                    num = 384;
                    break;
                case "ECDSA_P521":
                case "ECDH_P521":
                    num = 521;
                    break;
                default:
                    throw new ArgumentException(System.SR.Cryptography_InvalidKeySize);
                }
                _keyHandle = CngKeyLite.GenerateNewExportableKey(text, num);
            }
        }
        else
        {
            if (!curve.IsExplicit)
            {
                throw new PlatformNotSupportedException(System.SR.Format(System.SR.Cryptography_CurveNotSupported, curve.CurveType.ToString()));
            }
            text = _algorithmGroup;
            _keyHandle = CngKeyLite.GenerateNewExportableKey(text, ref curve);
            num = CngKeyLite.GetKeyLength(_keyHandle);
        }
        _lastAlgorithm = text;
        _lastKeySize = num;
        KeySize = num;
    }
References System.Security.Cryptography.ECCngKey._algorithmGroup, System.Security.Cryptography.ECCngKey._keyHandle, System.Security.Cryptography.ECCngKey._lastAlgorithm, System.Security.Cryptography.ECCngKey._lastKeySize, System.SR.Cryptography_CurveNotSupported, System.SR.Cryptography_InvalidCurveOid, System.SR.Cryptography_InvalidKeySize, System.Security.Cryptography.ECCurve.CurveType, System.Security.Cryptography.ECCngKey.DisposeKey(), System.Security.Cryptography.ECCng.EcdhCurveNameToAlgorithm(), System.Security.Cryptography.ECCng.EcdsaCurveNameToAlgorithm(), System.SR.Format(), System.Security.Cryptography.Oid.FriendlyName, System.Security.Cryptography.CngKeyLite.GenerateNewExportableKey(), System.Security.Cryptography.CngKeyLite.GetKeyLength(), System.Exception.HResult, System.Security.Cryptography.ECCng.IsECNamedCurve(), System.Security.Cryptography.ECCurve.IsExplicit, System.Security.Cryptography.ECCurve.IsNamed, System.Security.Cryptography.ECCngKey.KeySize, System.Security.Cryptography.ECCurve.Oid, System.text, System.Security.Cryptography.ECCngKey.ThrowIfDisposed(), System.Security.Cryptography.ECCurve.Validate(), and System.Security.Cryptography.Oid.Value.
Referenced by System.Security.Cryptography.ECDiffieHellmanImplementation.ECDiffieHellmanCng.GenerateKey(), and System.Security.Cryptography.ECDsaImplementation.ECDsaCng.GenerateKey().