Terraria: System.Security.Cryptography.ECCngKey.DisposeKey
DisposeKey()
void System.Security.Cryptography.ECCngKey.DisposeKey () inline package
Definition at line 145 of file ECCngKey.cs.
    {
        if (_keyHandle != null)
        {
            _keyHandle.Dispose();
            _keyHandle = null;
        }
        _lastAlgorithm = null;
        _lastKeySize = 0;
    }
References System.Security.Cryptography.ECCngKey._keyHandle, System.Security.Cryptography.ECCngKey._lastAlgorithm, System.Security.Cryptography.ECCngKey._lastKeySize, and System.Runtime.InteropServices.SafeHandle.Dispose().
Referenced by System.Security.Cryptography.ECDiffieHellmanImplementation.ECDiffieHellmanCng.DisposeKey(), System.Security.Cryptography.ECDsaImplementation.ECDsaCng.DisposeKey(), System.Security.Cryptography.ECCngKey.FullDispose(), System.Security.Cryptography.ECCngKey.GenerateKey(), and System.Security.Cryptography.ECCngKey.GetDuplicatedKeyHandle().