Terraria: System.Security.Cryptography.ECCngKey.SetHandle
SetHandle()
void System.Security.Cryptography.ECCngKey.SetHandle (SafeNCryptKeyHandle keyHandle, string algorithmName) inline package
Definition at line 156 of file ECCngKey.cs.
    {
        ThrowIfDisposed();
        _keyHandle?.Dispose();
        _keyHandle = keyHandle;
        _lastAlgorithm = algorithmName;
        KeySize = CngKeyLite.GetKeyLength(keyHandle);
        _lastKeySize = KeySize;
    }
References System.Security.Cryptography.ECCngKey._keyHandle, System.Security.Cryptography.ECCngKey._lastAlgorithm, System.Security.Cryptography.ECCngKey._lastKeySize, System.Runtime.InteropServices.SafeHandle.Dispose(), System.Security.Cryptography.CngKeyLite.GetKeyLength(), System.Security.Cryptography.ECCngKey.KeySize, and System.Security.Cryptography.ECCngKey.ThrowIfDisposed().
Referenced by System.Security.Cryptography.ECDiffieHellmanImplementation.ECDiffieHellmanCng.AcceptImport(), System.Security.Cryptography.ECDsaImplementation.ECDsaCng.AcceptImport(), System.Security.Cryptography.ECDiffieHellmanImplementation.ECDiffieHellmanCng.ImportFullKeyBlob(), System.Security.Cryptography.ECDsaImplementation.ECDsaCng.ImportFullKeyBlob(), System.Security.Cryptography.ECDiffieHellmanImplementation.ECDiffieHellmanCng.ImportKeyBlob(), and System.Security.Cryptography.ECDsaImplementation.ECDsaCng.ImportKeyBlob().