Terraria: System.Security.Cryptography.ECCngKey.GetDuplicatedKeyHandle
GetDuplicatedKeyHandle()
SafeNCryptKeyHandle System.Security.Cryptography.ECCngKey.GetDuplicatedKeyHandle (int callerKeySizeProperty) inline package
Definition at line 39 of file ECCngKey.cs.
    {
        ThrowIfDisposed();
        if (ECCng.IsECNamedCurve(_lastAlgorithm))
        {
            return new DuplicateSafeNCryptKeyHandle(_keyHandle);
        }
        if (_lastKeySize != callerKeySizeProperty)
        {
            bool flag = _algorithmGroup == "ECDSA";
            string text = callerKeySizeProperty switch
            {
                256 => flag ? "ECDSA_P256" : "ECDH_P256",
                384 => flag ? "ECDSA_P384" : "ECDH_P384",
                521 => flag ? "ECDSA_P521" : "ECDH_P521",
                _ => throw new ArgumentException(System.SR.Cryptography_InvalidKeySize),
            };
            if (_keyHandle != null)
            {
                DisposeKey();
            }
            _keyHandle = CngKeyLite.GenerateNewExportableKey(text, callerKeySizeProperty);
            _lastKeySize = callerKeySizeProperty;
            _lastAlgorithm = text;
            KeySize = callerKeySizeProperty;
        }
        return new DuplicateSafeNCryptKeyHandle(_keyHandle);
    }
References System.Security.Cryptography.ECCngKey._algorithmGroup, System.Security.Cryptography.ECCngKey._keyHandle, System.Security.Cryptography.ECCngKey._lastAlgorithm, System.Security.Cryptography.ECCngKey._lastKeySize, System.SR.Cryptography_InvalidKeySize, System.Security.Cryptography.ECCngKey.DisposeKey(), System.Security.Cryptography.CngKeyLite.GenerateNewExportableKey(), System.Security.Cryptography.ECCng.IsECNamedCurve(), System.Security.Cryptography.ECCngKey.KeySize, System.text, and System.Security.Cryptography.ECCngKey.ThrowIfDisposed().
Referenced by System.Security.Cryptography.ECCngKey.GetCurveName(), System.Security.Cryptography.ECDiffieHellmanImplementation.ECDiffieHellmanCng.GetDuplicatedKeyHandle(), and System.Security.Cryptography.ECDsaImplementation.ECDsaCng.GetDuplicatedKeyHandle().