Terraria: System.Security.Cryptography.ECCngKey.ThrowIfDisposed
ThrowIfDisposed()
void System.Security.Cryptography.ECCngKey.ThrowIfDisposed () inline package
Definition at line 166 of file ECCngKey.cs.
    {
        if (_disposed)
        {
            throw new ObjectDisposedException(_disposedName);
        }
    }
References System.Security.Cryptography.ECCngKey._disposed, and System.Security.Cryptography.ECCngKey._disposedName.
Referenced by System.Security.Cryptography.ECCngKey.GenerateKey(), System.Security.Cryptography.ECCngKey.GetDuplicatedKeyHandle(), System.Security.Cryptography.ECCngKey.SetHandle(), System.Security.Cryptography.ECDiffieHellmanImplementation.ECDiffieHellmanCng.ThrowIfDisposed(), and System.Security.Cryptography.ECDsaImplementation.ECDsaCng.ThrowIfDisposed().