Terraria: Internal.Cryptography.PemKeyImportHelpers.ImportPem
ImportPem()
static void Internal.Cryptography.PemKeyImportHelpers.ImportPem (ReadOnlySpan< char > input, FindImportActionFunc callback) inline static
Definition at line 68 of file PemKeyImportHelpers.cs.
    {
        ImportKeyAction importKeyAction = null;
        PemFields pemFields = default(PemFields);
        ReadOnlySpan<char> readOnlySpan = default(ReadOnlySpan<char>);
        bool flag = false;
        ReadOnlySpan<char> readOnlySpan2 = input;
        PemFields fields;
        ReadOnlySpan<char> readOnlySpan3;
        while (PemEncoding.TryFind(readOnlySpan2, out fields))
        {
            readOnlySpan3 = readOnlySpan2;
            ReadOnlySpan<char> readOnlySpan4 = readOnlySpan3[fields.Label];
            ImportKeyAction importKeyAction2 = callback(readOnlySpan4);
            if (importKeyAction2 != null)
            {
                if (importKeyAction != null || flag)
                {
                    throw new ArgumentException(System.SR.Argument_PemImport_AmbiguousPem, "input");
                }
                importKeyAction = importKeyAction2;
                pemFields = fields;
                readOnlySpan = readOnlySpan2;
            }
            else if (readOnlySpan4.SequenceEqual("ENCRYPTED PRIVATE KEY"))
            {
                if (importKeyAction != null || flag)
                {
                    throw new ArgumentException(System.SR.Argument_PemImport_AmbiguousPem, "input");
                }
                flag = true;
            }
            Index end = fields.Location.End;
            readOnlySpan3 = readOnlySpan2;
            readOnlySpan2 = readOnlySpan3[end..];
        }
        if (flag)
        {
            throw new ArgumentException(System.SR.Argument_PemImport_EncryptedPem, "input");
        }
        if (importKeyAction == null)
        {
            throw new ArgumentException(System.SR.Argument_PemImport_NoPemFound, "input");
        }
        readOnlySpan3 = readOnlySpan;
        int length = readOnlySpan3.Length;
        Range base64Data = pemFields.Base64Data;
        int offset = base64Data.Start.GetOffset(length);
        int bytesRead = base64Data.End.GetOffset(length) - offset;
        ReadOnlySpan<char> chars = readOnlySpan3.Slice(offset, bytesRead);
        int decodedDataLength = pemFields.DecodedDataLength;
        byte[] array = System.Security.Cryptography.CryptoPool.Rent(decodedDataLength);
        int bytesWritten = 0;
        try
        {
            if (!Convert.TryFromBase64Chars(chars, array, out bytesWritten))
            {
                throw new ArgumentException();
            }
            Span<byte> span = array.AsSpan(0, bytesWritten);
            importKeyAction(span, out bytesRead);
        }
        finally
        {
            System.Security.Cryptography.CryptoPool.Return(array, bytesWritten);
        }
    }
References System.SR.Argument_PemImport_AmbiguousPem, System.SR.Argument_PemImport_EncryptedPem, System.SR.Argument_PemImport_NoPemFound, System.array, System.Security.Cryptography.PemFields.Base64Data, System.chars, System.Security.Cryptography.PemFields.DecodedDataLength, System.Range.End, System.Index.GetOffset(), Internal.Cryptography.PemKeyImportHelpers.ImportKeyAction(), System.input, System.Security.Cryptography.PemFields.Label, System.length, System.ReadOnlySpan< T >.Length, System.Security.Cryptography.PemFields.Location, System.offset, System.Security.Cryptography.CryptoPool.Rent(), System.Security.Cryptography.CryptoPool.Return(), System.ReadOnlySpan< T >.Slice(), System.Range.Start, System.Security.Cryptography.PemEncoding.TryFind(), and System.Convert.TryFromBase64Chars().
Referenced by System.Security.Cryptography.DSA.ImportFromPem(), System.Security.Cryptography.ECDiffieHellman.ImportFromPem(), System.Security.Cryptography.ECDsa.ImportFromPem(), and System.Security.Cryptography.RSA.ImportFromPem().