Terraria: System.Xml.Serialization.XmlSchemaObjectComparer.NameOf
NameOf() [1/2]
static XmlQualifiedName System.Xml.Serialization.XmlSchemaObjectComparer.NameOf (XmlSchemaObject o) inline static package
Definition at line 15 of file XmlSchemaObjectComparer.cs.
    {
        if (o is XmlSchemaAttribute)
        {
            return ((XmlSchemaAttribute)o).QualifiedName;
        }
        if (o is XmlSchemaAttributeGroup)
        {
            return ((XmlSchemaAttributeGroup)o).QualifiedName;
        }
        if (o is XmlSchemaComplexType)
        {
            return ((XmlSchemaComplexType)o).QualifiedName;
        }
        if (o is XmlSchemaSimpleType)
        {
            return ((XmlSchemaSimpleType)o).QualifiedName;
        }
        if (o is XmlSchemaElement)
        {
            return ((XmlSchemaElement)o).QualifiedName;
        }
        if (o is XmlSchemaGroup)
        {
            return ((XmlSchemaGroup)o).QualifiedName;
        }
        if (o is XmlSchemaGroupRef)
        {
            return ((XmlSchemaGroupRef)o).RefName;
        }
        if (o is XmlSchemaNotation)
        {
            return ((XmlSchemaNotation)o).QualifiedName;
        }
        if (o is XmlSchemaSequence)
        {
            XmlSchemaSequence xmlSchemaSequence = (XmlSchemaSequence)o;
            if (xmlSchemaSequence.Items.Count == 0)
            {
                return new XmlQualifiedName(".sequence", Namespace(o));
            }
            return NameOf(xmlSchemaSequence.Items[0]);
        }
        if (o is XmlSchemaAll)
        {
            XmlSchemaAll xmlSchemaAll = (XmlSchemaAll)o;
            if (xmlSchemaAll.Items.Count == 0)
            {
                return new XmlQualifiedName(".all", Namespace(o));
            }
            return NameOf(xmlSchemaAll.Items);
        }
        if (o is XmlSchemaChoice)
        {
            XmlSchemaChoice xmlSchemaChoice = (XmlSchemaChoice)o;
            if (xmlSchemaChoice.Items.Count == 0)
            {
                return new XmlQualifiedName(".choice", Namespace(o));
            }
            return NameOf(xmlSchemaChoice.Items);
        }
        if (o is XmlSchemaAny)
        {
            return new XmlQualifiedName("*", SchemaObjectWriter.ToString(((XmlSchemaAny)o).NamespaceList));
        }
        if (o is XmlSchemaIdentityConstraint)
        {
            return ((XmlSchemaIdentityConstraint)o).QualifiedName;
        }
        return new XmlQualifiedName("?", Namespace(o));
    }
References System.Xml.Dictionary, System.Xml.Serialization.XmlSchemaObjectComparer.NameOf(), System.Xml.Schema.Namespace, and System.Xml.Serialization.SchemaObjectWriter.ToString().
Referenced by System.Xml.Serialization.XmlSchemaObjectComparer.Compare(), System.Xml.Serialization.XmlSchemaObjectComparer.NameOf(), and System.Xml.Serialization.XmlSchemaObjectComparer.NameOf().