Terraria: System.Buffers.TlsOverPerCoreLockedStacksArrayPool.Trim
Trim()
bool System.Buffers.TlsOverPerCoreLockedStacksArrayPool< T >.Trim () inline
Definition at line 311 of file TlsOverPerCoreLockedStacksArrayPool.cs.
    {
        int tickCount = Environment.TickCount;
        Utilities.MemoryPressure memoryPressure = Utilities.GetMemoryPressure();
        ArrayPoolEventSource log = ArrayPoolEventSource.Log;
        if (log.IsEnabled())
        {
            log.BufferTrimPoll(tickCount, (int)memoryPressure);
        }
        PerCoreLockedStacks[] buckets = _buckets;
        for (int i = 0; i < buckets.Length; i++)
        {
            buckets[i]?.Trim(tickCount, Id, memoryPressure, Utilities.GetMaxSizeForBucket(i));
        }
        if (memoryPressure == Utilities.MemoryPressure.High)
        {
            if (log.IsEnabled())
            {
                foreach (KeyValuePair<ThreadLocalArray[], object> item in (IEnumerable<KeyValuePair<ThreadLocalArray[], object>>)_allTlsBuckets)
                {
                    ThreadLocalArray[] key = item.Key;
                    for (int j = 0; j < key.Length; j++)
                    {
                        T[] array = Interlocked.Exchange(ref key[j].Array, null);
                        if (array != null)
{
                            log.BufferTrimmed(array.GetHashCode(), array.Length, Id);
                        }
                    }
                }
            }
            else
            {
                foreach (KeyValuePair<ThreadLocalArray[], object> item2 in (IEnumerable<KeyValuePair<ThreadLocalArray[], object>>)_allTlsBuckets)
                {
                    Array.Clear(item2.Key);
                }
            }
        }
        else
        {
            uint num = ((memoryPressure != Utilities.MemoryPressure.Medium) ? 30000u : 15000u);
            uint num2 = num;
            foreach (KeyValuePair<ThreadLocalArray[], object> item3 in (IEnumerable<KeyValuePair<ThreadLocalArray[], object>>)_allTlsBuckets)
            {
                ThreadLocalArray[] key2 = item3.Key;
                for (int k = 0; k < key2.Length; k++)
                {
                    if (key2[k].Array == null)
                    {
                        continue;
                    }
                    int millisecondsTimeStamp = key2[k].MillisecondsTimeStamp;
                    if (millisecondsTimeStamp == 0)
                    {
                        key2[k].MillisecondsTimeStamp = tickCount;
                    }
                    else if (tickCount - millisecondsTimeStamp >= num2)
                    {
                        T[] array2 = Interlocked.Exchange(ref key2[k].Array, null);
                        if (array2 != null && log.IsEnabled())
{
                            log.BufferTrimmed(array2.GetHashCode(), array2.Length, Id);
                        }
                    }
                }
            }
        }
        return true;
    }
References System.Buffers.TlsOverPerCoreLockedStacksArrayPool< T >._allTlsBuckets, System.Buffers.TlsOverPerCoreLockedStacksArrayPool< T >._buckets, System.array, System.Array.Clear(), System.Threading.Interlocked.Exchange(), System.Buffers.Utilities.GetMaxSizeForBucket(), System.Buffers.Utilities.GetMemoryPressure(), System.Buffers.TlsOverPerCoreLockedStacksArrayPool< T >.Id, System.item, System.key, System.Buffers.ArrayPoolEventSource.Log, System.Environment.TickCount, and System.Buffers.TlsOverPerCoreLockedStacksArrayPool< T >.PerCoreLockedStacks.Trim().