Terraria: DelegateMethods.Minecart.SpawnFartCloud
SpawnFartCloud()
static void DelegateMethods.Minecart.SpawnFartCloud (Player Player, Vector2 Position, int Width, int Height, bool useDelay = true) inline static
         {
             if (useDelay)
             {
                 if (Player.fartKartCloudDelay > 0)
                 {
                     return;
                 }
                 Player.fartKartCloudDelay = 20;
             }
             float num = 10f;
             float y = -4f;
             Vector2 vector = Position + new Vector2(Width / 2 - 18, Height - 16);
             Vector2 vector2 = Player.velocity * 0.1f;
             if (vector2.Length() > 2f)
             {
                 vector2 = vector2.SafeNormalize(Vector2.Zero) * 2f;
             }
             int num2 = Gore.NewGore(vector + new Vector2(0f, y), Vector2.Zero, Main.rand.Next(435, 438));
             Main.gore[num2].velocity *= 0.2f;
             Main.gore[num2].velocity += vector2;
             Main.gore[num2].velocity.Y *= 0.75f;
             num2 = Gore.NewGore(vector + new Vector2(0f - num, y), Vector2.Zero, Main.rand.Next(435, 438));
             Main.gore[num2].velocity *= 0.2f;
             Main.gore[num2].velocity += vector2;
             Main.gore[num2].velocity.Y *= 0.75f;
             num2 = Gore.NewGore(vector + new Vector2(num, y), Vector2.Zero, Main.rand.Next(435, 438));
             Main.gore[num2].velocity *= 0.2f;
             Main.gore[num2].velocity += vector2;
             Main.gore[num2].velocity.Y *= 0.75f;
             if (Player.mount.Active && Player.mount.Type == 53)
             {
                 Vector2 vector3 = Position + new Vector2(Width / 2, Height + 10);
                 float num3 = 30f;
                 float num4 = -16f;
                 for (int i = 0; i < 15; i++)
                 {
                     Dust dust = Dust.NewDustPerfect(vector3 + new Vector2(0f - num3 + num3 * 2f * Main.rand.NextFloat(), num4 * Main.rand.NextFloat()), 107, Vector2.Zero, 100, Color.Lerp(new Color(64, 220, 96), Color.White, Main.rand.NextFloat() * 0.3f), 0.6f);
                     dust.velocity *= (float)Main.rand.Next(15, 51) * 0.01f;
                     dust.velocity.X *= (float)Main.rand.Next(25, 101) * 0.01f;
                     dust.velocity.Y -= (float)Main.rand.Next(15, 31) * 0.1f;
                     dust.velocity += vector2;
                     dust.velocity.Y *= 0.75f;
                     dust.fadeIn = 0.2f + Main.rand.NextFloat() * 0.1f;
                     dust.noGravity = Main.rand.Next(3) == 0;
                     dust.noLightEmittence = true;
                 }
             }
         }
References Mount.Active, Color, Dust.fadeIn, Player.fartKartCloudDelay, Main.gore, Player.mount, Dust.NewDustPerfect(), Gore.NewGore(), UnifiedRandom.Next(), Dust.noGravity, Dust.noLightEmittence, Main.rand, Mount.Type, Dust.velocity, Entity.velocity, and Gore.velocity.
Referenced by DelegateMethods.Minecart.BumperSoundFart(), DelegateMethods.Minecart.JumpingSoundFart(), and DelegateMethods.Minecart.LandingSoundFart().