Terraria: DelegateMethods.Minecart.JumpingSoundFart
JumpingSoundFart()
static void DelegateMethods.Minecart.JumpingSoundFart (Player Player, Vector2 Position, int Width, int Height) inline static
         {
             SoundEngine.PlaySound(SoundID.Item16, (int)Position.X + Width / 2, (int)Position.Y + Height / 2);
             SpawnFartCloud(Player, Position, Width, Height, useDelay: false);
         }
References SoundID.Item16, SoundEngine.PlaySound(), and DelegateMethods.Minecart.SpawnFartCloud().
Referenced by Mount.Initialize().