Terraria: DelegateMethods.Minecart.SparksFart
SparksFart()
static void DelegateMethods.Minecart.SparksFart (Vector2 dustPosition) inline static
         {
             dustPosition += new Vector2((Main.rand.Next(2) == 0) ? 13 : (-13), 0f).RotatedBy(rotation);
             int num = Dust.NewDust(dustPosition, 1, 1, 211, Main.rand.Next(-2, 3), Main.rand.Next(-2, 3), 50, default(Color), 0.8f);
             if (Main.rand.Next(2) == 0)
             {
                 Main.dust[num].alpha += 25;
             }
             if (Main.rand.Next(2) == 0)
             {
                 Main.dust[num].alpha += 25;
             }
             Main.dust[num].noLight = true;
             Main.dust[num].noGravity = Main.rand.Next(3) == 0;
             Main.dust[num].velocity *= (float)Main.rand.Next(15, 51) * 0.01f;
             Main.dust[num].velocity.X *= (float)Main.rand.Next(25, 101) * 0.01f;
             Main.dust[num].velocity.Y -= (float)Main.rand.Next(15, 31) * 0.1f;
             Main.dust[num].position.Y -= 4f;
         }
References Dust.alpha, Color, Main.dust, Dust.NewDust(), UnifiedRandom.Next(), Dust.noGravity, Dust.noLight, Dust.position, Main.rand, DelegateMethods.Minecart.rotation, and Dust.velocity.
Referenced by Mount.Initialize(), and DelegateMethods.Minecart.SparksTerraFart().