Terraria: System.Buffers.TlsOverPerCoreLockedStacksArrayPool.InitializeTlsBucketsAndTrimming
InitializeTlsBucketsAndTrimming()
ThreadLocalArray[] System.Buffers.TlsOverPerCoreLockedStacksArrayPool< T >.InitializeTlsBucketsAndTrimming () inline private
Definition at line 382 of file TlsOverPerCoreLockedStacksArrayPool.cs.
    {
        ThreadLocalArray[] array = (t_tlsBuckets = new ThreadLocalArray[27]);
        _allTlsBuckets.Add(array, null);
        if (Interlocked.Exchange(ref _trimCallbackCreated, 1) == 0)
        {
            Gen2GcCallback.Register((object s) => ((TlsOverPerCoreLockedStacksArrayPool<T>)s).Trim(), this);
        }
        return array;
    }
References System.Buffers.TlsOverPerCoreLockedStacksArrayPool< T >._allTlsBuckets, System.Buffers.TlsOverPerCoreLockedStacksArrayPool< T >._trimCallbackCreated, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.array, System.Threading.Interlocked.Exchange(), System.Gen2GcCallback.Register(), System.s, and System.Buffers.TlsOverPerCoreLockedStacksArrayPool< T >.t_tlsBuckets.
Referenced by System.Buffers.TlsOverPerCoreLockedStacksArrayPool< T >.Return().