Terraria: Terraria.WorldBuilding.ModShapes.OuterOutline.Perform
Perform()
override bool Terraria.WorldBuilding.ModShapes.OuterOutline.Perform (Point origin, GenAction action) inline
Definition at line 47 of file ModShapes.cs.
        {
            int num = (_useDiagonals ? 16 : 8);
            foreach (Point16 datum in _data.GetData())
            {
                if (_useInterior && !UnitApply(action, origin, datum.X + origin.X, datum.Y + origin.Y) && _quitOnFail)
                {
                    return false;
                }
                for (int i = 0; i < num; i += 2)
                {
                    if (!_data.Contains(datum.X + POINT_OFFSETS[i], datum.Y + POINT_OFFSETS[i + 1]) && !UnitApply(action, origin, origin.X + datum.X + POINT_OFFSETS[i], origin.Y + datum.Y + POINT_OFFSETS[i + 1]) && _quitOnFail)
                    {
                        return false;
                    }
                }
            }
            return true;
        }
References Terraria.WorldBuilding.GenModShape._data, Terraria.WorldBuilding.GenShape._quitOnFail, Terraria.WorldBuilding.ModShapes.OuterOutline._useDiagonals, Terraria.WorldBuilding.ModShapes.OuterOutline._useInterior, Terraria.WorldBuilding.ShapeData.Contains(), Terraria.WorldBuilding.ShapeData.GetData(), Terraria.WorldBuilding.ModShapes.OuterOutline.POINT_OFFSETS, Terraria.WorldBuilding.GenShape.UnitApply(), Terraria.DataStructures.Point16.X, and Terraria.DataStructures.Point16.Y.