Terraria: System.Text.DecoderDBCS.GetChars
GetChars() [2/7]
unsafe override int System.Text.DecoderDBCS.GetChars (byte * bytes, int byteCount, char * chars, int charCount, bool flush) inline virtual
Reimplemented from System.Text.Decoder.
Definition at line 164 of file DecoderDBCS.cs.
    {
        if (chars == null || bytes == null)
        {
            throw new ArgumentNullException((chars == null) ? "chars" : "bytes", System.SR.ArgumentNull_Array);
        }
        if (byteCount < 0 || charCount < 0)
        {
            throw new ArgumentOutOfRangeException((byteCount < 0) ? "byteCount" : "charCount", System.SR.ArgumentOutOfRange_NeedNonNegNum);
        }
        if (charCount == 0)
        {
            return 0;
        }
        byte b = (byte)((byteCount > 0 && !flush && IsLastByteALeadByte(bytes, byteCount)) ? bytes[byteCount - 1] : 0);
        if (b != 0)
        {
            byteCount--;
        }
        if (_leftOverLeadByte == 0)
        {
            if (byteCount <= 0)
            {
                _leftOverLeadByte = b;
                return 0;
            }
            int result = OSEncoding.MultiByteToWideChar(_encoding.CodePage, bytes, byteCount, chars, charCount);
            _leftOverLeadByte = b;
            return result;
        }
        if (byteCount == 0 && b == 0 && !flush)
        {
            return 0;
        }
        int result2 = ConvertWithLeftOverByte(bytes, byteCount, chars, charCount);
        _leftOverLeadByte = b;
        return result2;
    }
References System.Text.DecoderDBCS._encoding, System.Text.DecoderDBCS._leftOverLeadByte, System.SR.ArgumentNull_Array, System.SR.ArgumentOutOfRange_NeedNonNegNum, System.byteCount, System.bytes, System.charCount, System.chars, System.Text.Encoding.CodePage, System.Text.DecoderDBCS.ConvertWithLeftOverByte(), System.Text.DecoderDBCS.IsLastByteALeadByte(), and System.Text.OSEncoding.MultiByteToWideChar().