Terraria: System.Text.DecoderDBCS.GetCharCount
GetCharCount() [2/7]
unsafe override int System.Text.DecoderDBCS.GetCharCount (byte * bytes, int count, bool flush) inline virtual
Reimplemented from System.Text.Decoder.
Definition at line 92 of file DecoderDBCS.cs.
    {
        if (bytes == null)
        {
            throw new ArgumentNullException("bytes", System.SR.ArgumentNull_Array);
        }
        if (count < 0)
        {
            throw new ArgumentOutOfRangeException("count", System.SR.ArgumentOutOfRange_NeedNonNegNum);
        }
        bool flag = count > 0 && !flush && IsLastByteALeadByte(bytes, count);
        if (flag)
        {
            count--;
        }
        if (_leftOverLeadByte == 0)
        {
            if (count <= 0)
            {
                return 0;
            }
            return OSEncoding.MultiByteToWideChar(_encoding.CodePage, bytes, count, null, 0);
        }
        if (count == 0 && !flag && !flush)
        {
            return 0;
        }
        return ConvertWithLeftOverByte(bytes, count, null, 0);
    }
References System.Text.DecoderDBCS._encoding, System.Text.DecoderDBCS._leftOverLeadByte, System.SR.ArgumentNull_Array, System.SR.ArgumentOutOfRange_NeedNonNegNum, System.bytes, System.Text.Encoding.CodePage, System.Text.DecoderDBCS.ConvertWithLeftOverByte(), System.count, System.Text.DecoderDBCS.IsLastByteALeadByte(), and System.Text.OSEncoding.MultiByteToWideChar().