Terraria: Terraria.GameContent.Bestiary.NPCKillsTracker.RegisterKill
RegisterKill()
void Terraria.GameContent.Bestiary.NPCKillsTracker.RegisterKill (NPC npc) inline
    {
        string bestiaryCreditId = npc.GetBestiaryCreditId();
        _killCountsByNpcId.TryGetValue(bestiaryCreditId, out var value);
        value++;
        lock (_entryCreationLock)
        {
            _killCountsByNpcId[bestiaryCreditId] = Utils.Clamp(value, 0, 999999999);
        }
        if (Main.netMode == 2)
        {
            NetManager.Instance.Broadcast(NetBestiaryModule.SerializeKillCount(npc.netID, value));
        }
    }
References Terraria.GameContent.Bestiary.NPCKillsTracker._entryCreationLock, Terraria.GameContent.Bestiary.NPCKillsTracker._killCountsByNpcId, Terraria.Net.NetManager.Broadcast(), Terraria.NPC.GetBestiaryCreditId(), Terraria.Net.NetManager.Instance, Terraria.NPC.netID, Terraria.Main.netMode, and Terraria.GameContent.NetModules.NetBestiaryModule.SerializeKillCount().