Terraria: Terraria.DataStructures.TitleLinkButton.Draw
Draw()
void Terraria.DataStructures.TitleLinkButton.Draw (SpriteBatch spriteBatch, Vector2 anchorPosition) inline
Definition at line 26 of file TitleLinkButton.cs.
    {
        Rectangle r = Image.Frame();
        if (FrameWhenNotSelected.HasValue)
        {
            r = FrameWhenNotSelected.Value;
        }
        Vector2 vector = r.Size();
        Vector2 vector2 = anchorPosition - vector / 2f;
        bool flag = false;
        if (Main.MouseScreen.Between(vector2, vector2 + vector))
        {
            Main.LocalPlayer.mouseInterface = true;
            flag = true;
            DrawTooltip();
            TryClicking();
        }
        Rectangle? rectangle = (flag ? FrameWehnSelected : FrameWhenNotSelected);
        Rectangle rectangle2 = Image.Frame();
        if (rectangle.HasValue)
        {
            rectangle2 = rectangle.Value;
        }
        Texture2D value = Image.Value;
        spriteBatch.Draw(value, anchorPosition, rectangle2, Color.White, 0f, rectangle2.Size() / 2f, 1f, SpriteEffects.None, 0f);
    }
References Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(), Terraria.DataStructures.TitleLinkButton.DrawTooltip(), Terraria.DataStructures.TitleLinkButton.FrameWehnSelected, Terraria.DataStructures.TitleLinkButton.FrameWhenNotSelected, Terraria.DataStructures.TitleLinkButton.Image, Terraria.Main.MouseScreen, Terraria.DataStructures.TitleLinkButton.TryClicking(), ReLogic.Content.Asset< T >.Value, System.value, and Microsoft.Xna.Framework.Color.White.