Terraria: Terraria.DataStructures.TitleLinkButton.TryClicking
TryClicking()
void Terraria.DataStructures.TitleLinkButton.TryClicking () inline private
    {
        if (!PlayerInput.IgnoreMouseInterface && Main.mouseLeft && Main.mouseLeftRelease)
        {
            SoundEngine.PlaySound(10);
            Main.mouseLeftRelease = false;
            OpenLink();
        }
    }
References Terraria.GameInput.PlayerInput.IgnoreMouseInterface, Terraria.Main.mouseLeft, Terraria.Main.mouseLeftRelease, Terraria.DataStructures.TitleLinkButton.OpenLink(), and Terraria.Audio.SoundEngine.PlaySound().
Referenced by Terraria.DataStructures.TitleLinkButton.Draw().