Terraria: System.TypeNameParser.GetType
GetType()
static Type System.TypeNameParser.GetType (string typeName, Func< AssemblyName, Assembly > assemblyResolver, Func< Assembly, string, bool, Type > typeResolver, bool throwOnError, bool ignoreCase, ref StackCrawlMark stackMark) inline static package
Definition at line 34 of file TypeNameParser.cs.
    {
        if (typeName == null)
        {
            throw new ArgumentNullException("typeName");
        }
        if (typeName.Length > 0 && typeName[0] == '\0')
        {
            throw new ArgumentException(SR.Format_StringZeroLength);
        }
        Type result = null;
        SafeTypeNameParserHandle safeTypeNameParserHandle = CreateTypeNameParser(typeName, throwOnError);
        if (safeTypeNameParserHandle != null)
        {
            using TypeNameParser typeNameParser = new TypeNameParser(safeTypeNameParserHandle);
            result = typeNameParser.ConstructType(assemblyResolver, typeResolver, throwOnError, ignoreCase, ref stackMark);
        }
        return result;
    }
References System.TypeNameParser.TypeNameParser(), System.TypeNameParser.CreateTypeNameParser(), and System.SR.Format_StringZeroLength.
Referenced by System.Type.GetType(), System.Type.GetType(), and System.Type.GetType().