Terraria: System.TypeNameParser.ResolveAssembly
ResolveAssembly()
static Assembly System.TypeNameParser.ResolveAssembly (string asmName, Func< AssemblyName, Assembly > assemblyResolver, bool throwOnError, ref StackCrawlMark stackMark) inline static private
Definition at line 116 of file TypeNameParser.cs.
    {
        Assembly assembly;
        if (assemblyResolver == null)
        {
            if (throwOnError)
            {
                assembly = RuntimeAssembly.InternalLoad(asmName, ref stackMark, AssemblyLoadContext.CurrentContextualReflectionContext);
            }
            else
            {
                try
                {
                    assembly = RuntimeAssembly.InternalLoad(asmName, ref stackMark, AssemblyLoadContext.CurrentContextualReflectionContext);
                }
                catch (FileNotFoundException)
                {
                    return null;
                }
            }
        }
        else
        {
            assembly = assemblyResolver(new AssemblyName(asmName));
            if (assembly == null && throwOnError)
            {
                throw new FileNotFoundException(SR.Format(SR.FileNotFound_ResolveAssembly, asmName));
            }
        }
        return assembly;
    }
References System.Runtime.Loader.AssemblyLoadContext.CurrentContextualReflectionContext, System.SR.FileNotFound_ResolveAssembly, System.SR.Format(), and System.Reflection.RuntimeAssembly.InternalLoad().
Referenced by System.TypeNameParser.ConstructType().