Terraria: System.TypeNameParser.ResolveType
ResolveType()
static Type System.TypeNameParser.ResolveType (Assembly assembly, string[] names, Func< Assembly, string, bool, Type > typeResolver, bool throwOnError, bool ignoreCase, ref StackCrawlMark stackMark) inline static private
Definition at line 149 of file TypeNameParser.cs.
    {
        string text = EscapeTypeName(names[0]);
        Type type;
        if (typeResolver == null)
        {
            type = ((!(assembly == null)) ? assembly.GetType(text, throwOnError, ignoreCase) : RuntimeType.GetType(text, throwOnError, ignoreCase, ref stackMark));
        }
        else
        {
            type = typeResolver(assembly, text, ignoreCase);
            if (type == null && throwOnError)
            {
                string message = ((assembly == null) ? SR.Format(SR.TypeLoad_ResolveType, text) : SR.Format(SR.TypeLoad_ResolveTypeFromAssembly, text, assembly.FullName));
                throw new TypeLoadException(message);
            }
        }
        if (type != null)
        {
            BindingFlags bindingFlags = BindingFlags.Public | BindingFlags.NonPublic;
            if (ignoreCase)
            {
                bindingFlags |= BindingFlags.IgnoreCase;
            }
            for (int i = 1; i < names.Length; i++)
            {
                type = type.GetNestedType(names[i], bindingFlags);
                if (type == null)
                {
                    if (!throwOnError)
                    {
                        break;
                    }
                    throw new TypeLoadException(SR.Format(SR.TypeLoad_ResolveNestedType, names[i], names[i - 1]));
                }
            }
        }
        return type;
    }
References System.TypeNameParser.EscapeTypeName(), System.SR.Format(), System.Reflection.Assembly.FullName, System.Reflection.Assembly.GetType(), System.RuntimeType.GetType(), System.text, System.type, System.SR.TypeLoad_ResolveNestedType, System.SR.TypeLoad_ResolveType, and System.SR.TypeLoad_ResolveTypeFromAssembly.
Referenced by System.TypeNameParser.ConstructType().