Terraria: System.TypeNameParser.ConstructType
ConstructType()
unsafe Type System.TypeNameParser.ConstructType (Func< AssemblyName, Assembly > assemblyResolver, Func< Assembly, string, bool, Type > typeResolver, bool throwOnError, bool ignoreCase, ref StackCrawlMark stackMark) inline private
Definition at line 65 of file TypeNameParser.cs.
    {
        Assembly assembly = null;
        string assemblyName = GetAssemblyName();
        if (assemblyName.Length > 0)
        {
            assembly = ResolveAssembly(assemblyName, assemblyResolver, throwOnError, ref stackMark);
            if (assembly == null)
            {
                return null;
            }
        }
        string[] names = GetNames();
        if (names == null)
        {
            if (throwOnError)
            {
                throw new TypeLoadException(SR.Arg_TypeLoadNullStr);
            }
            return null;
        }
        Type type = ResolveType(assembly, names, typeResolver, throwOnError, ignoreCase, ref stackMark);
        if (type == null)
        {
            return null;
        }
        SafeTypeNameParserHandle[] typeArguments = GetTypeArguments();
        Type[] array = null;
        if (typeArguments != null)
        {
            array = new Type[typeArguments.Length];
            for (int i = 0; i < typeArguments.Length; i++)
            {
                using (TypeNameParser typeNameParser = new TypeNameParser(typeArguments[i]))
                {
                    array[i] = typeNameParser.ConstructType(assemblyResolver, typeResolver, throwOnError, ignoreCase, ref stackMark);
                }
                if (array[i] == null)
                {
                    return null;
                }
            }
        }
        int[] modifiers = GetModifiers();
        fixed (int* value = modifiers)
        {
            IntPtr pModifiers = new IntPtr(value);
            return RuntimeTypeHandle.GetTypeHelper(type, array, pModifiers, (modifiers != null) ? modifiers.Length : 0);
        }
    }
References System.TypeNameParser.TypeNameParser(), System.SR.Arg_TypeLoadNullStr, System.array, System.TypeNameParser.ConstructType(), System.TypeNameParser.GetAssemblyName(), System.TypeNameParser.GetModifiers(), System.TypeNameParser.GetNames(), System.TypeNameParser.GetTypeArguments(), System.RuntimeTypeHandle.GetTypeHelper(), System.TypeNameParser.ResolveAssembly(), System.TypeNameParser.ResolveType(), System.type, and System.value.
Referenced by System.TypeNameParser.ConstructType().