Terraria: System.Runtime.Serialization.SurrogateDataContract.ReadXmlValue
ReadXmlValue()
override object System.Runtime.Serialization.SurrogateDataContract.ReadXmlValue (XmlReaderDelegator xmlReader, XmlObjectSerializerReadContext context) inline virtual
Reimplemented from System.Runtime.Serialization.DataContract.
Definition at line 68 of file SurrogateDataContract.cs.
    {
        xmlReader.Read();
        Type underlyingType = base.UnderlyingType;
        object obj = (underlyingType.IsArray ? Array.CreateInstance(underlyingType.GetElementType(), 0) : GetUninitializedObject(underlyingType));
        context.AddNewObject(obj);
        string objectId = context.GetObjectId();
        SerializationInfo serInfo = context.ReadSerializationInfo(xmlReader, underlyingType);
        object obj2 = SerializationSurrogateSetObjectData(obj, serInfo, context.GetStreamingContext());
        if (obj2 == null)
        {
            obj2 = obj;
        }
        if (obj2 is IDeserializationCallback)
        {
            ((IDeserializationCallback)obj2).OnDeserialization(null);
        }
        if (obj2 is IObjectReference)
        {
            obj2 = GetRealObject((IObjectReference)obj2, context.GetStreamingContext());
        }
        context.ReplaceDeserializedObject(objectId, obj, obj2);
        xmlReader.ReadEndElement();
        return obj2;
    }
References System.Runtime.Serialization.XmlObjectSerializerReadContext.AddNewObject(), System.Array.CreateInstance(), System.Runtime.Serialization.Dictionary, System.Runtime.Serialization.XmlObjectSerializerReadContext.GetObjectId(), System.Runtime.Serialization.SurrogateDataContract.GetRealObject(), System.Runtime.Serialization.XmlObjectSerializerContext.GetStreamingContext(), System.Runtime.Serialization.SurrogateDataContract.GetUninitializedObject(), System.obj, System.Runtime.Serialization.XmlObjectSerializerReadContext.ReadSerializationInfo(), System.Runtime.Serialization.XmlObjectSerializerReadContext.ReplaceDeserializedObject(), and System.Runtime.Serialization.SurrogateDataContract.SerializationSurrogateSetObjectData().