Terraria: System.Xml.XmlNode.GetPrefixOfNamespaceStrict
GetPrefixOfNamespaceStrict()
string System.Xml.XmlNode.GetPrefixOfNamespaceStrict (string namespaceURI) inline package inherited
Definition at line 1134 of file XmlNode.cs.
    {
        XmlDocument document = Document;
        if (document != null)
        {
            namespaceURI = document.NameTable.Add(namespaceURI);
            XmlNode xmlNode = this;
            while (xmlNode != null)
            {
                if (xmlNode.NodeType == XmlNodeType.Element)
                {
                    XmlElement xmlElement = (XmlElement)xmlNode;
                    if (xmlElement.HasAttributes)
                    {
                        XmlAttributeCollection attributes = xmlElement.Attributes;
                        for (int i = 0; i < attributes.Count; i++)
{
                            XmlAttribute xmlAttribute = attributes[i];
                            if (xmlAttribute.Prefix.Length == 0)
{
                                if (Ref.Equal(xmlAttribute.LocalName, document.strXmlns) && xmlAttribute.Value == namespaceURI)
{
                                    return string.Empty;
                                }
                            }
                            else if (Ref.Equal(xmlAttribute.Prefix, document.strXmlns))
{
                                if (xmlAttribute.Value == namespaceURI)
{
                                    return xmlAttribute.LocalName;
                                }
                            }
                            else if (Ref.Equal(xmlAttribute.NamespaceURI, namespaceURI))
{
                                return xmlAttribute.Prefix;
                            }
                        }
                    }
                    if (Ref.Equal(xmlNode.NamespaceURI, namespaceURI))
                    {
                        return xmlNode.Prefix;
                    }
                    xmlNode = xmlNode.ParentNode;
                }
                else
                {
                    xmlNode = ((xmlNode.NodeType != XmlNodeType.Attribute) ? xmlNode.ParentNode : ((XmlAttribute)xmlNode).OwnerElement);
                }
            }
            if (Ref.Equal(document.strReservedXml, namespaceURI))
            {
                return document.strXml;
            }
            if (Ref.Equal(document.strReservedXmlns, namespaceURI))
            {
                return document.strXmlns;
            }
        }
        return null;
    }
References System.Xml.XmlNameTable.Add(), System.Xml.XmlAttributeCollection.Count, System.Xml.Dictionary, System.Xml.XmlNode.Document, System.Xml.Ref.Equal(), and System.Xml.XmlDocument.NameTable.
Referenced by System.Xml.XmlNode.GetPrefixOfNamespace(), and System.Xml.DocumentSchemaValidator.LookupPrefix().