Terraria: System.Xml.XmlNode.AppendChildForLoad
AppendChildForLoad()
virtual XmlNode System.Xml.XmlNode.AppendChildForLoad (XmlNode newChild, XmlDocument doc) inline package virtual inherited
Reimplemented in System.Xml.XmlAttribute, System.Xml.XmlDocument, and System.Xml.XmlElement.
Definition at line 816 of file XmlNode.cs.
    {
        XmlNodeChangedEventArgs insertEventArgsForLoad = doc.GetInsertEventArgsForLoad(newChild, this);
        if (insertEventArgsForLoad != null)
        {
            doc.BeforeEvent(insertEventArgsForLoad);
        }
        XmlLinkedNode lastNode = LastNode;
        XmlLinkedNode xmlLinkedNode = (XmlLinkedNode)newChild;
        if (lastNode == null)
        {
            xmlLinkedNode.next = xmlLinkedNode;
            LastNode = xmlLinkedNode;
            xmlLinkedNode.SetParentForLoad(this);
        }
        else
        {
            xmlLinkedNode.next = lastNode.next;
            lastNode.next = xmlLinkedNode;
            LastNode = xmlLinkedNode;
            if (lastNode.IsText && xmlLinkedNode.IsText)
            {
                NestTextNodes(lastNode, xmlLinkedNode);
            }
            else
            {
                xmlLinkedNode.SetParentForLoad(this);
            }
        }
        if (insertEventArgsForLoad != null)
        {
            doc.AfterEvent(insertEventArgsForLoad);
        }
        return xmlLinkedNode;
    }
References System.Xml.Dictionary, System.Xml.XmlNode.LastNode, System.Xml.XmlNode.NestTextNodes(), and System.Xml.XmlNode.SetParentForLoad().
Referenced by System.Xml.XmlNode.CopyChildren(), System.Xml.XmlLoader.LoadAttributeValue(), and System.Xml.XmlLoader.ParsePartialContent().