Terraria: System.Xml.XmlNode.CopyChildren
CopyChildren()
virtual void System.Xml.XmlNode.CopyChildren (XmlDocument doc, XmlNode container, bool deep) inline package virtual inherited
Definition at line 869 of file XmlNode.cs.
    {
        for (XmlNode xmlNode = container.FirstChild; xmlNode != null; xmlNode = xmlNode.NextSibling)
        {
            AppendChildForLoad(xmlNode.CloneNode(deep), doc);
        }
    }
References System.Xml.XmlNode.AppendChildForLoad(), System.Xml.Dictionary, and System.Xml.XmlNode.FirstChild.
Referenced by System.Xml.XmlAttribute.CloneNode(), System.Xml.XmlDocumentFragment.CloneNode(), System.Xml.XmlElement.CloneNode(), and System.Xml.XmlUnspecifiedAttribute.CloneNode().