Terraria: System.Xml.XmlNode.AncestorNode
AncestorNode()
bool System.Xml.XmlNode.AncestorNode (XmlNode node) inline package inherited
Definition at line 421 of file XmlNode.cs.
    {
        XmlNode xmlNode = ParentNode;
        while (xmlNode != null && xmlNode != this)
        {
            if (xmlNode == node)
            {
                return true;
            }
            xmlNode = xmlNode.ParentNode;
        }
        return false;
    }
References System.Xml.Dictionary, and System.Xml.XmlNode.ParentNode.
Referenced by System.Xml.XmlNode.AppendChild(), System.Xml.XmlNode.InsertAfter(), and System.Xml.XmlNode.InsertBefore().