Terraria: System.Xml.XmlNode.ReplaceChild
ReplaceChild()
virtual XmlNode System.Xml.XmlNode.ReplaceChild (XmlNode newChild, XmlNode oldChild) inline virtual inherited
Reimplemented in System.Xml.XmlBoundElement, System.Xml.XmlAttribute, and System.Xml.XmlUnspecifiedAttribute.
Definition at line 654 of file XmlNode.cs.
    {
        XmlNode nextSibling = oldChild.NextSibling;
        RemoveChild(oldChild);
        InsertBefore(newChild, nextSibling);
        return oldChild;
    }
References System.Xml.Dictionary, System.Xml.XmlNode.InsertBefore(), System.Xml.XmlNode.NextSibling, and System.Xml.XmlNode.RemoveChild().
Referenced by System.Xml.DocumentXmlWriter.CloseWithReplaceToFollowingSibling(), System.Xml.XmlAttribute.ReplaceChild(), and System.Xml.XmlUnspecifiedAttribute.ReplaceChild().