Terraria: System.Xml.XmlNode.GetEventArgs
GetEventArgs()
virtual XmlNodeChangedEventArgs System.Xml.XmlNode.GetEventArgs (XmlNode node, XmlNode oldParent, XmlNode newParent, string oldValue, string newValue, XmlNodeChangedAction action) inline package virtual inherited
Reimplemented in System.Xml.XmlDocument.
Definition at line 1239 of file XmlNode.cs.
    {
        XmlDocument ownerDocument = OwnerDocument;
        if (ownerDocument != null)
        {
            if (!ownerDocument.IsLoading && ((newParent != null && newParent.IsReadOnly) || (oldParent != null && oldParent.IsReadOnly)))
            {
                throw new InvalidOperationException(System.SR.Xdom_Node_Modify_ReadOnly);
            }
            return ownerDocument.GetEventArgs(node, oldParent, newParent, oldValue, newValue, action);
        }
        return null;
    }
References System.action, System.Xml.Dictionary, System.Xml.XmlNode.OwnerDocument, and System.SR.Xdom_Node_Modify_ReadOnly.
Referenced by System.Xml.XmlNamedNodeMap.AddNode(), System.Xml.XmlNode.AppendChild(), System.Xml.XmlCharacterData.AppendData(), System.Xml.XmlCharacterData.DeleteData(), System.Xml.XmlNode.InsertAfter(), System.Xml.XmlNode.InsertBefore(), System.Xml.XmlCharacterData.InsertData(), System.Xml.XmlNamedNodeMap.InsertNodeAt(), System.Xml.XmlNode.RemoveChild(), System.Xml.XmlNamedNodeMap.RemoveNodeAt(), and System.Xml.XmlCharacterData.ReplaceData().