Terraria: System.ComponentModel.ComponentResourceManager.FillResources
FillResources()
SortedList< string, object > System.ComponentModel.ComponentResourceManager.FillResources (CultureInfo culture, out ResourceSet resourceSet) inline private
Definition at line 139 of file ComponentResourceManager.cs.
    {
        ResourceSet resourceSet2 = null;
        SortedList<string, object> sortedList = ((!culture.Equals(CultureInfo.InvariantCulture) && !culture.Equals(NeutralResourcesCulture)) ? FillResources(culture.Parent, out resourceSet2) : ((!IgnoreCase) ? new SortedList<string, object>(StringComparer.Ordinal) : new SortedList<string, object>(StringComparer.OrdinalIgnoreCase)));
        resourceSet = GetResourceSet(culture, createIfNotExists: true, tryParents: true);
        if (resourceSet != null && resourceSet != resourceSet2)
        {
            foreach (DictionaryEntry item in resourceSet)
            {
                sortedList[(string)item.Key] = item.Value;
            }
        }
        return sortedList;
    }
References System.culture, System.ComponentModel.ComponentResourceManager.FillResources(), System.Resources.ResourceManager.GetResourceSet(), System.Resources.ResourceManager.IgnoreCase, System.Globalization.CultureInfo.InvariantCulture, System.item, System.ComponentModel.ComponentResourceManager.NeutralResourcesCulture, System.StringComparer.Ordinal, and System.StringComparer.OrdinalIgnoreCase.
Referenced by System.ComponentModel.ComponentResourceManager.ApplyResources(), and System.ComponentModel.ComponentResourceManager.FillResources().