Terraria: System.ComponentModel.ComponentResourceManager.ApplyResources
ApplyResources() [2/2]
virtual void System.ComponentModel.ComponentResourceManager.ApplyResources (object value, string objectName, CultureInfo? culture) inline virtual
Definition at line 44 of file ComponentResourceManager.cs.
    {
        if (value == null)
        {
            throw new ArgumentNullException("value");
        }
        if (objectName == null)
        {
            throw new ArgumentNullException("objectName");
        }
        if (culture == null)
        {
            culture = CultureInfo.CurrentUICulture;
        }
        SortedList<string, object> sortedList;
        if (_resourceSets == null)
        {
            _resourceSets = new Hashtable();
            sortedList = FillResources(culture, out var _);
            _resourceSets[culture] = sortedList;
        }
        else
        {
            sortedList = (SortedList<string, object>)_resourceSets[culture];
            if (sortedList == null || sortedList.Comparer.Equals(StringComparer.OrdinalIgnoreCase) != IgnoreCase)
            {
                sortedList = FillResources(culture, out var _);
                _resourceSets[culture] = sortedList;
            }
        }
        BindingFlags bindingFlags = BindingFlags.Instance | BindingFlags.Public | BindingFlags.GetProperty;
        if (IgnoreCase)
        {
            bindingFlags |= BindingFlags.IgnoreCase;
        }
        bool flag = false;
        if (value is IComponent)
        {
            ISite site = ((IComponent)value).Site;
            if (site != null && site.DesignMode)
            {
                flag = true;
            }
        }
        foreach (KeyValuePair<string, object> item in sortedList)
        {
            string key = item.Key;
            if (IgnoreCase)
            {
                if (string.Compare(key, 0, objectName, 0, objectName.Length, StringComparison.OrdinalIgnoreCase) != 0)
                {
                    continue;
                }
            }
            else if (string.CompareOrdinal(key, 0, objectName, 0, objectName.Length) != 0)
            {
                continue;
            }
            int length = objectName.Length;
            if (key.Length <= length || (key[length] != '.' && key[length] != '-'))
            {
                continue;
            }
            string name = key.Substring(length + 1);
            if (flag)
            {
                PropertyDescriptor propertyDescriptor = TypeDescriptor.GetProperties(value).Find(name, IgnoreCase);
                if (propertyDescriptor != null && !propertyDescriptor.IsReadOnly && (item.Value == null || propertyDescriptor.PropertyType.IsInstanceOfType(item.Value)))
                {
                    propertyDescriptor.SetValue(value, item.Value);
                }
                continue;
            }
            PropertyInfo propertyInfo = null;
            try
            {
                propertyInfo = value.GetType().GetProperty(name, bindingFlags);
            }
            catch (AmbiguousMatchException)
            {
                Type type = value.GetType();
                do
                {
                    propertyInfo = type.GetProperty(name, bindingFlags | BindingFlags.DeclaredOnly);
                    type = type.BaseType;
                }
                while (propertyInfo == null && type != null && type != typeof(object));
            }
            if (propertyInfo != null && propertyInfo.CanWrite && (item.Value == null || propertyInfo.PropertyType.IsInstanceOfType(item.Value)))
            {
                propertyInfo.SetValue(value, item.Value, null);
            }
        }
    }
References System.ComponentModel.ComponentResourceManager._resourceSets, System.Reflection.PropertyInfo.CanWrite, System.Collections.Generic.Dictionary< TKey, TValue >.Comparer, System.culture, System.Globalization.CultureInfo.CurrentUICulture, System.Collections.IEqualityComparer.Equals(), System.ComponentModel.ComponentResourceManager.FillResources(), System.ComponentModel.TypeDescriptor.GetProperties(), System.Type.GetType(), System.Resources.ResourceManager.IgnoreCase, System.Type.IsInstanceOfType(), System.Collections.Generic.Dictionary< TKey, TValue >.IsReadOnly, System.item, System.key, System.length, System.StringComparer.OrdinalIgnoreCase, System.Reflection.PropertyInfo.PropertyType, System.Reflection.PropertyInfo.SetValue(), System.type, and System.value.