Terraria: System.Xml.XmlNode.InsertBefore
InsertBefore()
virtual ? XmlNode System.Xml.XmlNode.InsertBefore (XmlNode newChild, XmlNode? refChild) inline virtual inherited
Reimplemented in System.Xml.XmlAttribute.
Definition at line 445 of file XmlNode.cs.
    {
        if (this == newChild || AncestorNode(newChild))
        {
            throw new ArgumentException(System.SR.Xdom_Node_Insert_Child);
        }
        if (refChild == null)
        {
            return AppendChild(newChild);
        }
        if (!IsContainer)
        {
            throw new InvalidOperationException(System.SR.Xdom_Node_Insert_Contain);
        }
        if (refChild.ParentNode != this)
        {
            throw new ArgumentException(System.SR.Xdom_Node_Insert_Path);
        }
        if (newChild == refChild)
        {
            return newChild;
        }
        XmlDocument ownerDocument = newChild.OwnerDocument;
        XmlDocument ownerDocument2 = OwnerDocument;
        if (ownerDocument != null && ownerDocument != ownerDocument2 && ownerDocument != this)
        {
            throw new ArgumentException(System.SR.Xdom_Node_Insert_Context);
        }
        if (!CanInsertBefore(newChild, refChild))
        {
            throw new InvalidOperationException(System.SR.Xdom_Node_Insert_Location);
        }
        if (newChild.ParentNode != null)
        {
            newChild.ParentNode.RemoveChild(newChild);
        }
        if (newChild.NodeType == XmlNodeType.DocumentFragment)
        {
            XmlNode firstChild = newChild.FirstChild;
            XmlNode xmlNode = firstChild;
            if (xmlNode != null)
            {
                newChild.RemoveChild(xmlNode);
                InsertBefore(xmlNode, refChild);
                InsertAfter(newChild, xmlNode);
            }
            return firstChild;
        }
        if (!(newChild is XmlLinkedNode) || !IsValidChildType(newChild.NodeType))
        {
            throw new InvalidOperationException(System.SR.Xdom_Node_Insert_TypeConflict);
        }
        XmlLinkedNode xmlLinkedNode = (XmlLinkedNode)newChild;
        XmlLinkedNode xmlLinkedNode2 = (XmlLinkedNode)refChild;
        string value = newChild.Value;
        XmlNodeChangedEventArgs eventArgs = GetEventArgs(newChild, newChild.ParentNode, this, value, value, XmlNodeChangedAction.Insert);
        if (eventArgs != null)
        {
            BeforeEvent(eventArgs);
        }
        if (xmlLinkedNode2 == FirstChild)
        {
            xmlLinkedNode.next = xmlLinkedNode2;
            LastNode.next = xmlLinkedNode;
            xmlLinkedNode.SetParent(this);
            if (xmlLinkedNode.IsText && xmlLinkedNode2.IsText)
            {
                NestTextNodes(xmlLinkedNode, xmlLinkedNode2);
            }
        }
        else
        {
            XmlLinkedNode xmlLinkedNode3 = (XmlLinkedNode)xmlLinkedNode2.PreviousSibling;
            xmlLinkedNode.next = xmlLinkedNode2;
            xmlLinkedNode3.next = xmlLinkedNode;
            xmlLinkedNode.SetParent(this);
            if (xmlLinkedNode3.IsText)
            {
                if (xmlLinkedNode.IsText)
                {
                    NestTextNodes(xmlLinkedNode3, xmlLinkedNode);
                    if (xmlLinkedNode2.IsText)
                    {
                        NestTextNodes(xmlLinkedNode, xmlLinkedNode2);
                    }
                }
                else if (xmlLinkedNode2.IsText)
                {
                    UnnestTextNodes(xmlLinkedNode3, xmlLinkedNode2);
                }
            }
            else if (xmlLinkedNode.IsText && xmlLinkedNode2.IsText)
            {
                NestTextNodes(xmlLinkedNode, xmlLinkedNode2);
            }
        }
        if (eventArgs != null)
        {
            AfterEvent(eventArgs);
        }
        return xmlLinkedNode;
    }
References System.Xml.XmlNode.AfterEvent(), System.Xml.XmlNode.AncestorNode(), System.Xml.AppendChild, System.Xml.ArgumentException, System.Xml.XmlNode.BeforeEvent(), System.Xml.XmlNode.CanInsertBefore(), System.Xml.Dictionary, System.Xml.XmlNode.FirstChild, System.Xml.XmlNode.GetEventArgs(), System.Xml.XmlNode.InsertAfter(), System.Xml.XmlNode.InsertBefore(), System.Xml.XmlNode.IsContainer, System.Xml.XmlNode.IsValidChildType(), System.Xml.XmlNode.NestTextNodes(), System.Xml.XmlDocument.OwnerDocument, System.Xml.XmlNode.OwnerDocument, System.Xml.XmlLinkedNode.PreviousSibling, System.Xml.XmlNode.RemoveChild(), System.Xml.XmlNode.UnnestTextNodes(), System.value, System.Xml.XmlNode.Value, System.SR.Xdom_Node_Insert_Child, System.SR.Xdom_Node_Insert_Contain, System.SR.Xdom_Node_Insert_Context, System.SR.Xdom_Node_Insert_Location, System.SR.Xdom_Node_Insert_Path, and System.SR.Xdom_Node_Insert_TypeConflict.
Referenced by System.Xml.Serialization.XmlSchemaExporter.AddXmlnsAnnotation(), System.Xml.DocumentXmlWriter.Close(), System.Data.XmlTreeGen.HandleTable(), System.Xml.XmlUnspecifiedAttribute.InsertBefore(), System.Xml.XmlAttribute.InsertBefore(), System.Xml.XmlNode.InsertBefore(), System.Xml.XmlNode.PrependChild(), System.Xml.XmlNode.ReplaceChild(), and System.Xml.XmlDataDocument.ReplaceInitialChildText().