Terraria: System.Xml.XmlNode.InsertAfter
InsertAfter()
virtual ? XmlNode System.Xml.XmlNode.InsertAfter (XmlNode newChild, XmlNode? refChild) inline virtual inherited
Reimplemented in System.Xml.XmlAttribute.
Definition at line 548 of file XmlNode.cs.
    {
        if (this == newChild || AncestorNode(newChild))
        {
            throw new ArgumentException(System.SR.Xdom_Node_Insert_Child);
        }
        if (refChild == null)
        {
            return PrependChild(newChild);
        }
        if (!IsContainer)
        {
            throw new InvalidOperationException(System.SR.Xdom_Node_Insert_Contain);
        }
        if (refChild.ParentNode != this)
        {
            throw new ArgumentException(System.SR.Xdom_Node_Insert_Path);
        }
        if (newChild == refChild)
        {
            return newChild;
        }
        XmlDocument ownerDocument = newChild.OwnerDocument;
        XmlDocument ownerDocument2 = OwnerDocument;
        if (ownerDocument != null && ownerDocument != ownerDocument2 && ownerDocument != this)
        {
            throw new ArgumentException(System.SR.Xdom_Node_Insert_Context);
        }
        if (!CanInsertAfter(newChild, refChild))
        {
            throw new InvalidOperationException(System.SR.Xdom_Node_Insert_Location);
        }
        if (newChild.ParentNode != null)
        {
            newChild.ParentNode.RemoveChild(newChild);
        }
        if (newChild.NodeType == XmlNodeType.DocumentFragment)
        {
            XmlNode refChild2 = refChild;
            XmlNode firstChild = newChild.FirstChild;
            XmlNode xmlNode = firstChild;
            while (xmlNode != null)
            {
                XmlNode nextSibling = xmlNode.NextSibling;
                newChild.RemoveChild(xmlNode);
                InsertAfter(xmlNode, refChild2);
                refChild2 = xmlNode;
                xmlNode = nextSibling;
            }
            return firstChild;
        }
        if (!(newChild is XmlLinkedNode) || !IsValidChildType(newChild.NodeType))
        {
            throw new InvalidOperationException(System.SR.Xdom_Node_Insert_TypeConflict);
        }
        XmlLinkedNode xmlLinkedNode = (XmlLinkedNode)newChild;
        XmlLinkedNode xmlLinkedNode2 = (XmlLinkedNode)refChild;
        string value = newChild.Value;
        XmlNodeChangedEventArgs eventArgs = GetEventArgs(newChild, newChild.ParentNode, this, value, value, XmlNodeChangedAction.Insert);
        if (eventArgs != null)
        {
            BeforeEvent(eventArgs);
        }
        if (xmlLinkedNode2 == LastNode)
        {
            xmlLinkedNode.next = xmlLinkedNode2.next;
            xmlLinkedNode2.next = xmlLinkedNode;
            LastNode = xmlLinkedNode;
            xmlLinkedNode.SetParent(this);
            if (xmlLinkedNode2.IsText && xmlLinkedNode.IsText)
            {
                NestTextNodes(xmlLinkedNode2, xmlLinkedNode);
            }
        }
        else
        {
            XmlLinkedNode xmlLinkedNode3 = (xmlLinkedNode.next = xmlLinkedNode2.next);
            xmlLinkedNode2.next = xmlLinkedNode;
            xmlLinkedNode.SetParent(this);
            if (xmlLinkedNode2.IsText)
            {
                if (xmlLinkedNode.IsText)
                {
                    NestTextNodes(xmlLinkedNode2, xmlLinkedNode);
                    if (xmlLinkedNode3.IsText)
                    {
                        NestTextNodes(xmlLinkedNode, xmlLinkedNode3);
                    }
                }
                else if (xmlLinkedNode3.IsText)
                {
                    UnnestTextNodes(xmlLinkedNode2, xmlLinkedNode3);
                }
            }
            else if (xmlLinkedNode.IsText && xmlLinkedNode3.IsText)
            {
                NestTextNodes(xmlLinkedNode, xmlLinkedNode3);
            }
        }
        if (eventArgs != null)
        {
            AfterEvent(eventArgs);
        }
        return xmlLinkedNode;
    }
References System.Xml.XmlNode.AfterEvent(), System.Xml.XmlNode.AncestorNode(), System.Xml.ArgumentException, System.Xml.XmlNode.BeforeEvent(), System.Xml.XmlNode.CanInsertAfter(), System.Xml.Dictionary, System.Xml.XmlNode.FirstChild, System.Xml.XmlNode.GetEventArgs(), System.Xml.XmlNode.InsertAfter(), System.Xml.XmlNode.IsContainer, System.Xml.XmlNode.IsValidChildType(), System.Xml.XmlNode.LastNode, System.Xml.XmlNode.NestTextNodes(), System.Xml.XmlNode.NextSibling, System.Xml.XmlDocument.OwnerDocument, System.Xml.XmlNode.OwnerDocument, System.Xml.PrependChild, System.Xml.XmlNode.RemoveChild(), System.Xml.XmlNode.SetParent(), System.Xml.XmlNode.UnnestTextNodes(), System.value, System.Xml.XmlNode.Value, System.SR.Xdom_Node_Insert_Child, System.SR.Xdom_Node_Insert_Contain, System.SR.Xdom_Node_Insert_Context, System.SR.Xdom_Node_Insert_Location, System.SR.Xdom_Node_Insert_Path, and System.SR.Xdom_Node_Insert_TypeConflict.
Referenced by System.Xml.DocumentXmlWriter.Close(), System.Xml.DocumentXmlWriter.CloseWithReplaceToFollowingSibling(), System.Data.XmlTreeGen.HandleTable(), System.Xml.XmlUnspecifiedAttribute.InsertAfter(), System.Xml.XmlAttribute.InsertAfter(), System.Xml.XmlNode.InsertAfter(), System.Xml.XmlNode.InsertBefore(), and System.Xml.XmlText.SplitText().