Terraria: System.Xml.XmlNode.RemoveChild
RemoveChild()
virtual XmlNode System.Xml.XmlNode.RemoveChild (XmlNode oldChild) inline virtual inherited
Reimplemented in System.Xml.XmlAttribute, and System.Xml.XmlUnspecifiedAttribute.
Definition at line 662 of file XmlNode.cs.
    {
        if (!IsContainer)
        {
            throw new InvalidOperationException(System.SR.Xdom_Node_Remove_Contain);
        }
        if (oldChild.ParentNode != this)
        {
            throw new ArgumentException(System.SR.Xdom_Node_Remove_Child);
        }
        XmlLinkedNode xmlLinkedNode = (XmlLinkedNode)oldChild;
        string value = xmlLinkedNode.Value;
        XmlNodeChangedEventArgs eventArgs = GetEventArgs(xmlLinkedNode, this, null, value, value, XmlNodeChangedAction.Remove);
        if (eventArgs != null)
        {
            BeforeEvent(eventArgs);
        }
        XmlLinkedNode lastNode = LastNode;
        if (xmlLinkedNode == FirstChild)
        {
            if (xmlLinkedNode == lastNode)
            {
                LastNode = null;
                xmlLinkedNode.next = null;
                xmlLinkedNode.SetParent(null);
            }
            else
            {
                XmlLinkedNode next = xmlLinkedNode.next;
                if (next.IsText && xmlLinkedNode.IsText)
                {
                    UnnestTextNodes(xmlLinkedNode, next);
                }
                lastNode.next = next;
                xmlLinkedNode.next = null;
                xmlLinkedNode.SetParent(null);
            }
        }
        else if (xmlLinkedNode == lastNode)
        {
            XmlLinkedNode xmlLinkedNode2 = (XmlLinkedNode)xmlLinkedNode.PreviousSibling;
            xmlLinkedNode2.next = xmlLinkedNode.next;
            LastNode = xmlLinkedNode2;
            xmlLinkedNode.next = null;
            xmlLinkedNode.SetParent(null);
        }
        else
        {
            XmlLinkedNode xmlLinkedNode3 = (XmlLinkedNode)xmlLinkedNode.PreviousSibling;
            XmlLinkedNode next2 = xmlLinkedNode.next;
            if (next2.IsText)
            {
                if (xmlLinkedNode3.IsText)
                {
                    NestTextNodes(xmlLinkedNode3, next2);
                }
                else if (xmlLinkedNode.IsText)
                {
                    UnnestTextNodes(xmlLinkedNode, next2);
                }
            }
            xmlLinkedNode3.next = next2;
            xmlLinkedNode.next = null;
            xmlLinkedNode.SetParent(null);
        }
        if (eventArgs != null)
        {
            AfterEvent(eventArgs);
        }
        return oldChild;
    }
References System.Xml.XmlNode.AfterEvent(), System.Xml.ArgumentException, System.Xml.XmlNode.BeforeEvent(), System.Xml.Dictionary, System.Xml.XmlNode.FirstChild, System.Xml.XmlNode.GetEventArgs(), System.Xml.XmlNode.IsContainer, System.Xml.XmlNode.IsText, System.Xml.XmlNode.LastNode, System.Xml.XmlNode.NestTextNodes(), System.Xml.XmlLinkedNode.next, System.Xml.XmlLinkedNode.PreviousSibling, System.Xml.XmlNode.SetParent(), System.Xml.XmlNode.UnnestTextNodes(), System.value, System.Xml.XmlNode.Value, System.SR.Xdom_Node_Remove_Child, and System.SR.Xdom_Node_Remove_Contain.
Referenced by System.Xml.XmlNode.AppendChild(), System.Xml.DocumentXPathNavigator.DeleteToFollowingSibling(), System.Xml.XmlDataDocument.DemoteDocumentElement(), System.Data.XmlTreeGen.HandleTable(), System.Xml.XmlNode.InsertAfter(), System.Xml.XmlNode.InsertBefore(), System.Xml.XmlNode.Normalize(), System.Xml.XmlNode.RemoveAll(), System.Xml.XmlBoundElement.RemoveAllChildren(), System.Xml.XmlAttribute.RemoveChild(), System.Xml.XmlUnspecifiedAttribute.RemoveChild(), System.Xml.XmlNode.ReplaceChild(), System.Data.XmlTreeGen.SchemaTree(), and System.Data.XmlTreeGen.SchemaTree().