Terraria: System.Xml.XmlNode.AppendChild
AppendChild()
virtual ? XmlNode System.Xml.XmlNode.AppendChild (XmlNode newChild) inline virtual inherited
Reimplemented in System.Xml.XmlBoundElement, System.Xml.XmlAttribute, and System.Xml.XmlUnspecifiedAttribute.
Definition at line 739 of file XmlNode.cs.
    {
        XmlDocument xmlDocument = OwnerDocument;
        if (xmlDocument == null)
        {
            xmlDocument = this as XmlDocument;
        }
        if (!IsContainer)
        {
            throw new InvalidOperationException(System.SR.Xdom_Node_Insert_Contain);
        }
        if (this == newChild || AncestorNode(newChild))
        {
            throw new ArgumentException(System.SR.Xdom_Node_Insert_Child);
        }
        if (newChild.ParentNode != null)
        {
            newChild.ParentNode.RemoveChild(newChild);
        }
        XmlDocument ownerDocument = newChild.OwnerDocument;
        if (ownerDocument != null && ownerDocument != xmlDocument && ownerDocument != this)
        {
            throw new ArgumentException(System.SR.Xdom_Node_Insert_Context);
        }
        if (newChild.NodeType == XmlNodeType.DocumentFragment)
        {
            XmlNode firstChild = newChild.FirstChild;
            XmlNode xmlNode = firstChild;
            while (xmlNode != null)
            {
                XmlNode nextSibling = xmlNode.NextSibling;
                newChild.RemoveChild(xmlNode);
                AppendChild(xmlNode);
                xmlNode = nextSibling;
            }
            return firstChild;
        }
        if (!(newChild is XmlLinkedNode) || !IsValidChildType(newChild.NodeType))
        {
            throw new InvalidOperationException(System.SR.Xdom_Node_Insert_TypeConflict);
        }
        if (!CanInsertAfter(newChild, LastChild))
        {
            throw new InvalidOperationException(System.SR.Xdom_Node_Insert_Location);
        }
        string value = newChild.Value;
        XmlNodeChangedEventArgs eventArgs = GetEventArgs(newChild, newChild.ParentNode, this, value, value, XmlNodeChangedAction.Insert);
        if (eventArgs != null)
        {
            BeforeEvent(eventArgs);
        }
        XmlLinkedNode lastNode = LastNode;
        XmlLinkedNode xmlLinkedNode = (XmlLinkedNode)newChild;
        if (lastNode == null)
        {
            xmlLinkedNode.next = xmlLinkedNode;
            LastNode = xmlLinkedNode;
            xmlLinkedNode.SetParent(this);
        }
        else
        {
            xmlLinkedNode.next = lastNode.next;
            lastNode.next = xmlLinkedNode;
            LastNode = xmlLinkedNode;
            xmlLinkedNode.SetParent(this);
            if (lastNode.IsText && xmlLinkedNode.IsText)
            {
                NestTextNodes(lastNode, xmlLinkedNode);
            }
        }
        if (eventArgs != null)
        {
            AfterEvent(eventArgs);
        }
        return xmlLinkedNode;
    }
References System.Xml.XmlNode.AfterEvent(), System.Xml.XmlNode.AncestorNode(), System.Xml.AppendChild, System.Xml.ArgumentException, System.Xml.XmlNode.BeforeEvent(), System.Xml.XmlNode.CanInsertAfter(), System.Xml.Dictionary, System.Xml.XmlNode.FirstChild, System.Xml.XmlNode.GetEventArgs(), System.Xml.XmlNode.IsContainer, System.Xml.XmlNode.IsValidChildType(), System.Xml.XmlNode.LastChild, System.Xml.XmlNode.LastNode, System.Xml.XmlNode.NestTextNodes(), System.Xml.XmlNode.NextSibling, System.Xml.XmlDocument.OwnerDocument, System.Xml.XmlNode.OwnerDocument, System.Xml.XmlNode.RemoveChild(), System.Xml.XmlNode.SetParent(), System.value, System.SR.Xdom_Node_Insert_Child, System.SR.Xdom_Node_Insert_Contain, System.SR.Xdom_Node_Insert_Context, System.SR.Xdom_Node_Insert_Location, and System.SR.Xdom_Node_Insert_TypeConflict.
Referenced by System.Xml.DocumentXmlWriter.AddChild(), System.Xml.XmlAttribute.AppendChild(), System.Xml.XmlUnspecifiedAttribute.AppendChild(), System.Xml.DocumentXmlWriter.Close(), System.Data.XmlTreeGen.FillDataSetElement(), System.Data.XmlTreeGen.HandleColumnType(), System.Data.XmlTreeGen.HandleTable(), System.Xml.Schema.Parser.LoadAttributeNode(), System.Xml.Schema.Parser.LoadElementNode(), System.Xml.XmlDataDocument.OnAddRow(), System.Xml.XmlDataDocument.OnNestedParentChange(), System.Xml.Schema.Parser.ProcessAppInfoDocMarkup(), System.Xml.XmlDataDocument.ReplaceInitialChildText(), System.Data.XmlTreeGen.SchemaTree(), and System.Data.XmlTreeGen.SchemaTree().