Terraria: System.Xml.XmlNode.GetNamespaceOfPrefixStrict
GetNamespaceOfPrefixStrict()
string System.Xml.XmlNode.GetNamespaceOfPrefixStrict (string prefix) inline package inherited
Definition at line 1051 of file XmlNode.cs.
    {
        XmlDocument document = Document;
        string array = prefix;
        if (document != null)
        {
            array = document.NameTable.Get(array);
            if (array == null)
            {
                return null;
            }
            XmlNode xmlNode = this;
            while (xmlNode != null)
            {
                if (xmlNode.NodeType == XmlNodeType.Element)
                {
                    XmlElement xmlElement = (XmlElement)xmlNode;
                    if (xmlElement.HasAttributes)
                    {
                        XmlAttributeCollection attributes = xmlElement.Attributes;
                        if (array.Length == 0)
{
                            for (int i = 0; i < attributes.Count; i++)
{
                                XmlAttribute xmlAttribute = attributes[i];
                                if (xmlAttribute.Prefix.Length == 0 && Ref.Equal(xmlAttribute.LocalName, document.strXmlns))
{
                                    return xmlAttribute.Value;
                                }
                            }
                        }
                        else
{
                            for (int j = 0; j < attributes.Count; j++)
{
                                XmlAttribute xmlAttribute2 = attributes[j];
                                if (Ref.Equal(xmlAttribute2.Prefix, document.strXmlns))
{
                                    if (Ref.Equal(xmlAttribute2.LocalName, array))
{
                                        return xmlAttribute2.Value;
                                    }
                                }
                                else if (Ref.Equal(xmlAttribute2.Prefix, array))
{
                                    return xmlAttribute2.NamespaceURI;
                                }
                            }
                        }
                    }
                    if (Ref.Equal(xmlNode.Prefix, array))
                    {
                        return xmlNode.NamespaceURI;
                    }
                    xmlNode = xmlNode.ParentNode;
                }
                else
                {
                    xmlNode = ((xmlNode.NodeType != XmlNodeType.Attribute) ? xmlNode.ParentNode : ((XmlAttribute)xmlNode).OwnerElement);
                }
            }
            if (Ref.Equal(document.strXml, array))
            {
                return document.strReservedXml;
            }
            if (Ref.Equal(document.strXmlns, array))
            {
                return document.strReservedXmlns;
            }
        }
        return null;
    }
References System.array, System.Xml.XmlAttributeCollection.Count, System.Xml.Dictionary, System.Xml.XmlNode.Document, System.Xml.Ref.Equal(), System.Xml.XmlNameTable.Get(), System.Xml.XmlDocument.NameTable, and System.prefix.
Referenced by System.Xml.XmlNode.GetNamespaceOfPrefix(), and System.Xml.DocumentSchemaValidator.LookupNamespace().