Terraria: System.Xml.XmlNode.Normalize
Normalize()
virtual void System.Xml.XmlNode.Normalize () inline virtual inherited
Definition at line 877 of file XmlNode.cs.
    {
        XmlNode xmlNode = null;
        StringBuilder stringBuilder = System.Text.StringBuilderCache.Acquire();
        XmlNode nextSibling;
        for (XmlNode xmlNode2 = FirstChild; xmlNode2 != null; xmlNode2 = nextSibling)
        {
            nextSibling = xmlNode2.NextSibling;
            switch (xmlNode2.NodeType)
            {
            case XmlNodeType.Text:
            case XmlNodeType.Whitespace:
            case XmlNodeType.SignificantWhitespace:
            {
                stringBuilder.Append(xmlNode2.Value);
                XmlNode xmlNode3 = NormalizeWinner(xmlNode, xmlNode2);
                if (xmlNode3 == xmlNode)
                {
                    RemoveChild(xmlNode2);
                    continue;
                }
                if (xmlNode != null)
                {
                    RemoveChild(xmlNode);
                }
                xmlNode = xmlNode2;
                continue;
            }
            case XmlNodeType.Element:
                xmlNode2.Normalize();
                break;
            }
            if (xmlNode != null)
            {
                xmlNode.Value = stringBuilder.ToString();
                xmlNode = null;
            }
            stringBuilder.Remove(0, stringBuilder.Length);
        }
        if (xmlNode != null && stringBuilder.Length > 0)
        {
            xmlNode.Value = stringBuilder.ToString();
        }
        System.Text.StringBuilderCache.Release(stringBuilder);
    }
References System.Text.StringBuilderCache.Acquire(), System.Xml.Dictionary, System.Xml.XmlNode.FirstChild, System.Xml.XmlNode.NextSibling, System.Xml.XmlNode.NormalizeWinner(), System.Text.StringBuilderCache.Release(), and System.Xml.XmlNode.RemoveChild().