Terraria: CoreSocialModule.Initialize
Initialize() [2/2]
void CoreSocialModule.Initialize () inline
Implements ISocialModule.
     {
         //IL_0000: Unknown result type (might be due to invalid IL or missing references)
         //IL_0006: Expected O, but got Unknown
         //IL_005d: Unknown result type (might be due to invalid IL or missing references)
         //IL_0067: Expected O, but got Unknown
         RailGameID val = new RailGameID();
         ((RailComparableID)val).id_ = 2000328uL;
         string[] array = ((!Main.dedServ) ? new string[1] { " " } : Environment.GetCommandLineArgs());
         if (rail_api.RailNeedRestartAppForCheckingEnvironment(val, array.Length, array))
         {
             Environment.Exit(1);
         }
         if (!rail_api.RailInitialize())
         {
             Environment.Exit(1);
         }
         _callbackHelper.RegisterCallback((RAILEventID)2, new RailEventCallBackHandler(RailEventCallBack));
         isRailValid = true;
         ThreadPool.QueueUserWorkItem(TickThread, null);
         Main.OnTickForThirdPartySoftwareOnly += RailEventTick;
     }
References _callbackHelper, Main.dedServ, isRailValid, Main.OnTickForThirdPartySoftwareOnly, RailEventCallBack(), RailEventTick(), and TickThread().