Terraria: UIAchievementListItem.DrawSelf
DrawSelf()
override void UIAchievementListItem.DrawSelf (SpriteBatch spriteBatch) inline protected virtual
Reimplemented from UIElement.
     {
         base.DrawSelf(spriteBatch);
         int num = _large.ToInt() * 6;
         Vector2 vector = new Vector2(num, 0f);
         _locked = !_achievement.IsCompleted;
         UpdateIconFrame();
         CalculatedStyle innerDimensions = GetInnerDimensions();
         CalculatedStyle dimensions = _achievementIconBorders.GetDimensions();
         float num2 = dimensions.X + dimensions.Width;
         Vector2 vector2 = new Vector2(num2 + 7f, innerDimensions.Y);
         Tuple<decimal, decimal> trackerValues = GetTrackerValues();
         bool flag = false;
         if ((!(trackerValues.Item1 == 0m) || !(trackerValues.Item2 == 0m)) && _locked)
         {
             flag = true;
         }
         float num3 = innerDimensions.Width - dimensions.Width + 1f - (float)(num * 2);
         Vector2 baseScale = new Vector2(0.85f);
         Vector2 baseScale2 = new Vector2(0.92f);
         string text = FontAssets.ItemStack.Value.CreateWrappedText(_achievement.Description.Value, (num3 - 20f) * (1f / baseScale2.X), Language.ActiveCulture.CultureInfo);
         Vector2 stringSize = ChatManager.GetStringSize(FontAssets.ItemStack.Value, text, baseScale2, num3);
         if (!_large)
         {
             stringSize = ChatManager.GetStringSize(FontAssets.ItemStack.Value, _achievement.Description.Value, baseScale2, num3);
         }
         float num4 = 38f + (float)(_large ? 20 : 0);
         if (stringSize.Y > num4)
         {
             baseScale2.Y *= num4 / stringSize.Y;
         }
         Color value = (_locked ? Color.Silver : Color.Gold);
         value = Color.Lerp(value, Color.White, base.IsMouseHovering ? 0.5f : 0f);
         Color value2 = (_locked ? Color.DarkGray : Color.Silver);
         value2 = Color.Lerp(value2, Color.White, base.IsMouseHovering ? 1f : 0f);
         Color color = (base.IsMouseHovering ? Color.White : Color.Gray);
         Vector2 vector3 = vector2 - Vector2.UnitY * 2f + vector;
         DrawPanelTop(spriteBatch, vector3, num3, color);
         AchievementCategory category = _achievement.Category;
         vector3.Y += 2f;
         vector3.X += 4f;
         spriteBatch.Draw(_categoryTexture.Value, vector3, _categoryTexture.Frame(4, 2, (int)category), base.IsMouseHovering ? Color.White : Color.Silver, 0f, Vector2.Zero, 0.5f, SpriteEffects.None, 0f);
         vector3.X += 4f;
         vector3.X += 17f;
         ChatManager.DrawColorCodedStringWithShadow(spriteBatch, FontAssets.ItemStack.Value, _achievement.FriendlyName.Value, vector3, value, 0f, Vector2.Zero, baseScale, num3);
         vector3.X -= 17f;
         Vector2 position = vector2 + Vector2.UnitY * 27f + vector;
         DrawPanelBottom(spriteBatch, position, num3, color);
         position.X += 8f;
         position.Y += 4f;
         ChatManager.DrawColorCodedStringWithShadow(spriteBatch, FontAssets.ItemStack.Value, text, position, value2, 0f, Vector2.Zero, baseScale2);
         if (flag)
         {
             Vector2 vector4 = vector3 + Vector2.UnitX * num3 + Vector2.UnitY;
             string text2 = (int)trackerValues.Item1 + "/" + (int)trackerValues.Item2;
             Vector2 baseScale3 = new Vector2(0.75f);
             Vector2 stringSize2 = ChatManager.GetStringSize(FontAssets.ItemStack.Value, text2, baseScale3);
             float progress = (float)(trackerValues.Item1 / trackerValues.Item2);
             float num5 = 80f;
             Color color2 = new Color(100, 255, 100);
             if (!base.IsMouseHovering)
             {
                 color2 = Color.Lerp(color2, Color.Black, 0.25f);
             }
             Color color3 = new Color(255, 255, 255);
             if (!base.IsMouseHovering)
             {
                 color3 = Color.Lerp(color3, Color.Black, 0.25f);
             }
             DrawProgressBar(spriteBatch, progress, vector4 - Vector2.UnitX * num5 * 0.7f, num5, color3, color2, color2.MultiplyRGBA(new Color(new Vector4(1f, 1f, 1f, 0.5f))));
             vector4.X -= num5 * 1.4f + stringSize2.X;
             ChatManager.DrawColorCodedStringWithShadow(spriteBatch, FontAssets.ItemStack.Value, text2, vector4, value, 0f, new Vector2(0f, 0f), baseScale3, 90f);
         }
     }
References _achievement, _achievementIconBorders, _categoryTexture, _large, _locked, Language.ActiveCulture, Achievement.Category, Color, GameCulture.CultureInfo, Achievement.Description, ChatManager.DrawColorCodedStringWithShadow(), DrawPanelBottom(), DrawPanelTop(), DrawProgressBar(), Achievement.FriendlyName, UIElement.GetDimensions(), UIElement.GetInnerDimensions(), ChatManager.GetStringSize(), GetTrackerValues(), Achievement.IsCompleted, FontAssets.ItemStack, UpdateIconFrame(), Asset< T >.Value, LocalizedText.Value, CalculatedStyle.Width, CalculatedStyle.X, and CalculatedStyle.Y.