Terraria: System.Xml.Xsl.IlGen.XmlILNamespaceAnalyzer.AnalyzeContent
AnalyzeContent()
void System.Xml.Xsl.IlGen.XmlILNamespaceAnalyzer.AnalyzeContent (QilNode nd) inline private
Definition at line 31 of file XmlILNamespaceAnalyzer.cs.
    {
        switch (nd.NodeType)
        {
        case QilNodeType.Loop:
            _addInScopeNmsp = false;
            AnalyzeContent((nd as QilLoop).Body);
            break;
        case QilNodeType.Sequence:
        {
            foreach (QilNode item in nd)
            {
                AnalyzeContent(item);
            }
            break;
        }
        case QilNodeType.Conditional:
            _addInScopeNmsp = false;
            AnalyzeContent((nd as QilTernary).Center);
            AnalyzeContent((nd as QilTernary).Right);
            break;
        case QilNodeType.Choice:
        {
            _addInScopeNmsp = false;
            QilList branches = (nd as QilChoice).Branches;
            for (int i = 0; i < branches.Count; i++)
            {
                AnalyzeContent(branches[i]);
            }
            break;
        }
        case QilNodeType.ElementCtor:
        {
            _addInScopeNmsp = true;
            _nsmgr.PushScope();
            int cntNmsp = _cntNmsp;
            if (CheckNamespaceInScope(nd as QilBinary))
            {
                AnalyzeContent((nd as QilBinary).Right);
            }
            _nsmgr.PopScope();
            _addInScopeNmsp = false;
            _cntNmsp = cntNmsp;
            break;
        }
        case QilNodeType.AttributeCtor:
            _addInScopeNmsp = false;
            CheckNamespaceInScope(nd as QilBinary);
            break;
        case QilNodeType.NamespaceDecl:
            CheckNamespaceInScope(nd as QilBinary);
            break;
        case QilNodeType.Nop:
            AnalyzeContent((nd as QilUnary).Child);
            break;
        default:
            _addInScopeNmsp = false;
            break;
        }
    }
References System.Xml.Xsl.IlGen.XmlILNamespaceAnalyzer._addInScopeNmsp, System.Xml.Xsl.IlGen.XmlILNamespaceAnalyzer._cntNmsp, System.Xml.Xsl.IlGen.XmlILNamespaceAnalyzer._nsmgr, System.Xml.Xsl.IlGen.XmlILNamespaceAnalyzer.AnalyzeContent(), System.Xml.Xsl.IlGen.XmlILNamespaceAnalyzer.CheckNamespaceInScope(), System.Xml.Dictionary, System.item, System.Xml.XmlNamespaceManager.PopScope(), and System.Xml.XmlNamespaceManager.PushScope().
Referenced by System.Xml.Xsl.IlGen.XmlILNamespaceAnalyzer.Analyze(), and System.Xml.Xsl.IlGen.XmlILNamespaceAnalyzer.AnalyzeContent().