Terraria: System.Reflection.Internal.StreamExtensions.GetAndValidateSize
GetAndValidateSize()
static int System.Reflection.Internal.StreamExtensions.GetAndValidateSize (Stream stream, int size, string streamParameterName) inline static package
Definition at line 57 of file StreamExtensions.cs.
    {
        long num = stream.Length - stream.Position;
        if (size < 0 || size > num)
        {
            throw new ArgumentOutOfRangeException("size");
        }
        if (size != 0)
        {
            return size;
        }
        if (num > int.MaxValue)
        {
            throw new ArgumentException(System.SR.StreamTooLarge, streamParameterName);
        }
        return (int)num;
    }
References System.Reflection.MaxValue, System.stream, and System.SR.StreamTooLarge.
Referenced by System.Reflection.PortableExecutable.PEHeaders.PEHeaders(), System.Reflection.PortableExecutable.PEReader.PEReader(), and System.Reflection.Metadata.MetadataReaderProvider.FromMetadataStream().