Terraria: System.Xml.Xsl.Xslt.TemplateMatch.TemplateMatch
TemplateMatch()
System.Xml.Xsl.Xslt.TemplateMatch.TemplateMatch (Template template, QilLoop filter) inline
Definition at line 48 of file TemplateMatch.cs.
    {
        _template = template;
        _priority = (double.IsNaN(template.Priority) ? XPathPatternBuilder.GetPriority(filter) : template.Priority);
        _iterator = filter.Variable;
        _condition = filter.Body;
        XPathPatternBuilder.CleanAnnotation(filter);
        NipOffTypeNameCheck();
    }
References System.Xml.Xsl.Xslt.TemplateMatch._condition, System.Xml.Xsl.Xslt.TemplateMatch._iterator, System.Xml.Xsl.Xslt.TemplateMatch._priority, System.Xml.Xsl.Xslt.TemplateMatch._template, System.Xml.Xsl.Xslt.XPathPatternBuilder.CleanAnnotation(), System.Xml.Xsl.Xslt.XPathPatternBuilder.GetPriority(), and System.Xml.Xsl.Xslt.TemplateMatch.NipOffTypeNameCheck().