Terraria: Minecart.TrackCollision
TrackCollision()
static BitsByte Minecart.TrackCollision (Player Player, ref Vector2 Position, ref Vector2 Velocity, ref Vector2 lastBoost, int Width, int Height, bool followDown, bool followUp, int fallStart, bool trackOnly, Mount.MountDelegatesData delegatesData) inline static
     {
         if (followDown && followUp)
         {
             followDown = false;
             followUp = false;
         }
         Vector2 vector = new Vector2((float)(Width / 2) - 25f, Height / 2);
         Vector2 vector2 = Position + new Vector2((float)(Width / 2) - 25f, Height / 2) + _trackMagnetOffset;
         Vector2 vector3 = Velocity;
         float num = vector3.Length();
         vector3.Normalize();
         Vector2 vector4 = vector2;
         Tile tile = null;
         bool flag = false;
         bool flag2 = true;
         int num2 = -1;
         int num3 = -1;
         int num4 = -1;
         TrackState trackState = TrackState.NoTrack;
         bool flag3 = false;
         bool flag4 = false;
         bool flag5 = false;
         bool flag6 = false;
         Vector2 vector5 = Vector2.Zero;
         Vector2 vector6 = Vector2.Zero;
         BitsByte result = default(BitsByte);
         while (true)
         {
             int num5 = (int)(vector4.X / 16f);
             int num6 = (int)(vector4.Y / 16f);
             int num7 = (int)vector4.X % 16 / 2;
             if (flag2)
             {
                 num4 = num7;
             }
             bool flag7 = num7 != num4;
             if ((trackState == TrackState.OnBack || trackState == TrackState.OnTrack || trackState == TrackState.OnFront) && num5 != num2)
             {
                 int num8 = ((trackState != TrackState.OnBack) ? tile.FrontTrack() : tile.BackTrack());
                 switch ((!(vector3.X < 0f)) ? _rightSideConnection[num8] : _leftSideConnection[num8])
                 {
                 case 0:
                     num6--;
                     vector4.Y -= 2f;
                     break;
                 case 2:
                     num6++;
                     vector4.Y += 2f;
                     break;
                 }
             }
             TrackState trackState2 = TrackState.NoTrack;
             bool flag8 = false;
             if (num5 != num2 || num6 != num3)
             {
                 if (flag2)
                 {
                     flag2 = false;
                 }
                 else
                 {
                     flag8 = true;
                 }
                 tile = Main.tile[num5, num6];
                 if (tile == null)
                 {
                     tile = new Tile();
                     Main.tile[num5, num6] = tile;
                 }
                 flag = ((tile.nactive() && tile.type == 314) ? true : false);
             }
             if (flag)
             {
                 TrackState trackState3 = TrackState.NoTrack;
                 int num9 = tile.FrontTrack();
                 int num10 = tile.BackTrack();
                 int num11 = _tileHeight[num9][num7];
                 switch (num11)
                 {
                 case -4:
                     if (trackState == TrackState.OnFront)
                     {
                         if (trackOnly)
{
                             vector4 -= vector6;
                             num = 0f;
                             trackState2 = TrackState.OnFront;
                             flag6 = true;
                         }
                         else
{
                             trackState2 = TrackState.NoTrack;
                             flag5 = true;
                         }
                     }
                     break;
                 case -1:
                     if (trackState == TrackState.OnFront)
                     {
                         vector4 -= vector6;
                         num = 0f;
                         trackState2 = TrackState.OnFront;
                         flag6 = true;
                     }
                     break;
                 case -2:
                     if (trackState != TrackState.OnFront)
                     {
                         break;
                     }
                     if (trackOnly)
                     {
                         vector4 -= vector6;
                         num = 0f;
                         trackState2 = TrackState.OnFront;
                         flag6 = true;
                         break;
                     }
                     if (vector3.X < 0f)
                     {
                         float num14 = (float)(num5 * 16 + (num7 + 1) * 2) - vector4.X;
                         vector4.X += num14;
                         num += num14 / vector3.X;
                     }
                     vector3.X = 0f - vector3.X;
                     result[1] = true;
                     trackState2 = TrackState.OnFront;
                     break;
                 case -3:
                     if (trackState == TrackState.OnFront)
                     {
                         trackState = TrackState.NoTrack;
                         vector5 = Vector2.Transform(matrix: (Velocity.X > 0f) ? ((_leftSideConnection[num9] != 2) ? Matrix.CreateRotationZ((float)Math.PI / 4f) : Matrix.CreateRotationZ(-(float)Math.PI / 4f)) : ((_rightSideConnection[num9] != 2) ? Matrix.CreateRotationZ(-(float)Math.PI / 4f) : Matrix.CreateRotationZ((float)Math.PI / 4f)), position: new Vector2(Velocity.X, 0f));
                         vector5.X = Velocity.X;
                         flag4 = true;
                         num = 0f;
                     }
                     break;
                 default:
                 {
                     float num12 = num6 * 16 + num11;
                     if (num5 != num2 && trackState == TrackState.NoTrack && vector4.Y > num12 && vector4.Y - num12 < 2f)
                     {
                         flag8 = false;
                         trackState = TrackState.AboveFront;
                     }
                     TrackState trackState4 = ((!(vector4.Y < num12)) ? ((!(vector4.Y > num12)) ? TrackState.OnTrack : TrackState.BelowTrack) : TrackState.AboveTrack);
                     if (num10 != -1)
                     {
                         float num13 = num6 * 16 + _tileHeight[num10][num7];
                         trackState3 = ((!(vector4.Y < num13)) ? ((!(vector4.Y > num13)) ? TrackState.OnTrack : TrackState.BelowTrack) : TrackState.AboveTrack);
                     }
                     switch (trackState4)
                     {
                     case TrackState.OnTrack:
                         trackState2 = ((trackState3 == TrackState.OnTrack) ? TrackState.OnTrack : TrackState.OnFront);
                         break;
                     case TrackState.AboveTrack:
                         trackState2 = trackState3 switch
{
                             TrackState.OnTrack => TrackState.OnBack,
                             TrackState.BelowTrack => TrackState.AboveFront,
                             TrackState.AboveTrack => TrackState.AboveTrack,
                             _ => TrackState.AboveFront,
                         };
                         break;
                     case TrackState.BelowTrack:
                         trackState2 = trackState3 switch
{
                             TrackState.OnTrack => TrackState.OnBack,
                             TrackState.AboveTrack => TrackState.AboveBack,
                             TrackState.BelowTrack => TrackState.BelowTrack,
                             _ => TrackState.BelowTrack,
                         };
                         break;
                     }
                     break;
                 }
                 }
             }
             if (!flag8)
             {
                 if (trackState != trackState2)
                 {
                     bool flag9 = false;
                     if (flag7 || vector3.Y > 0f)
                     {
                         switch (trackState)
{
                         case TrackState.AboveTrack:
                             switch (trackState2)
{
                             case TrackState.AboveFront:
                                 trackState2 = TrackState.OnBack;
                                 break;
                             case TrackState.AboveBack:
                                 trackState2 = TrackState.OnFront;
                                 break;
                             case TrackState.AboveTrack:
                                 trackState2 = TrackState.OnTrack;
                                 break;
                             }
                             break;
                         case TrackState.AboveFront:
                             if (trackState2 == TrackState.BelowTrack)
{
                                 trackState2 = TrackState.OnFront;
                             }
                             break;
                         case TrackState.AboveBack:
                             if (trackState2 == TrackState.BelowTrack)
{
                                 trackState2 = TrackState.OnBack;
                             }
                             break;
                         case TrackState.OnFront:
                             trackState2 = TrackState.OnFront;
                             flag9 = true;
                             break;
                         case TrackState.OnBack:
                             trackState2 = TrackState.OnBack;
                             flag9 = true;
                             break;
                         case TrackState.OnTrack:
{
                             int num15 = _tileHeight[tile.FrontTrack()][num7];
                             int num16 = _tileHeight[tile.BackTrack()][num7];
                             trackState2 = (followDown ? ((num15 >= num16) ? TrackState.OnFront : TrackState.OnBack) : ((!followUp) ? TrackState.OnFront : ((num15 >= num16) ? TrackState.OnBack : TrackState.OnFront)));
                             flag9 = true;
                             break;
                         }
                         }
                         int num17 = -1;
                         switch (trackState2)
{
                         case TrackState.OnTrack:
                         case TrackState.OnFront:
                             num17 = tile.FrontTrack();
                             break;
                         case TrackState.OnBack:
                             num17 = tile.BackTrack();
                             break;
                         }
                         if (num17 != -1)
{
                             if (!flag9 && Velocity.Y > Player.defaultGravity)
{
                                 int num18 = (int)(Position.Y / 16f);
                                 if (fallStart < num18 - 1)
{
                                     delegatesData.MinecartLandingSound(Player, Position, Width, Height);
                                     WheelSparks(delegatesData.MinecartDust, Position, Width, Height, 10);
                                 }
                             }
                             if (trackState == TrackState.AboveFront && _trackType[num17] == 1)
{
                                 flag3 = true;
                             }
                             vector3.Y = 0f;
                             vector4.Y = num6 * 16 + _tileHeight[num17][num7];
                         }
                     }
                 }
             }
             else if (trackState2 == TrackState.OnFront || trackState2 == TrackState.OnBack || trackState2 == TrackState.OnTrack)
             {
                 if (flag && _trackType[tile.FrontTrack()] == 1)
                 {
                     flag3 = true;
                 }
                 vector3.Y = 0f;
             }
             if (trackState2 == TrackState.OnFront)
             {
                 int num19 = tile.FrontTrack();
                 if (_trackType[num19] == 2 && lastBoost.X == 0f && lastBoost.Y == 0f)
                 {
                     lastBoost = new Vector2(num5, num6);
                     if (_boostLeft[num19])
                     {
                         result[4] = true;
                     }
                     else
                     {
                         result[5] = true;
                     }
                 }
             }
             num4 = num7;
             trackState = trackState2;
             num2 = num5;
             num3 = num6;
             if (num > 0f)
             {
                 float num20 = vector4.X % 2f;
                 float num21 = vector4.Y % 2f;
                 float num22 = 3f;
                 float num23 = 3f;
                 if (vector3.X < 0f)
                 {
                     num22 = num20 + 0.125f;
                 }
                 else if (vector3.X > 0f)
                 {
                     num22 = 2f - num20;
                 }
                 if (vector3.Y < 0f)
                 {
                     num23 = num21 + 0.125f;
                 }
                 else if (vector3.Y > 0f)
                 {
                     num23 = 2f - num21;
                 }
                 if (num22 == 3f && num23 == 3f)
                 {
                     break;
                 }
                 float num24 = Math.Abs(num22 / vector3.X);
                 float num25 = Math.Abs(num23 / vector3.Y);
                 float num26 = ((num24 < num25) ? num24 : num25);
                 if (num26 > num)
                 {
                     vector6 = vector3 * num;
                     num = 0f;
                 }
                 else
                 {
                     vector6 = vector3 * num26;
                     num -= num26;
                 }
                 vector4 += vector6;
                 continue;
             }
             if (lastBoost.X != (float)num2 || lastBoost.Y != (float)num3)
             {
                 lastBoost = Vector2.Zero;
             }
             break;
         }
         if (flag3)
         {
             result[3] = true;
         }
         if (flag5)
         {
             Velocity.X = vector4.X - vector2.X;
             Velocity.Y = Player.defaultGravity;
         }
         else if (flag4)
         {
             result[2] = true;
             Velocity = vector5;
         }
         else if (result[1])
         {
             Velocity.X = 0f - Velocity.X;
             Position.X = vector4.X - _trackMagnetOffset.X - vector.X - Velocity.X;
             if (vector3.Y == 0f)
             {
                 Velocity.Y = 0f;
             }
         }
         else
         {
             if (flag6)
             {
                 Velocity.X = vector4.X - vector2.X;
             }
             if (vector3.Y == 0f)
             {
                 Velocity.Y = 0f;
             }
         }
         Position.Y += vector4.Y - vector2.Y - Velocity.Y;
         Position.Y = (float)Math.Round(Position.Y, 2);
         if (trackState == TrackState.OnTrack || (uint)(trackState - 5) <= 1u)
         {
             result[0] = true;
         }
         return result;
     }
References _boostLeft, _leftSideConnection, _rightSideConnection, _tileHeight, _trackMagnetOffset, _trackType, Player.defaultGravity, Tile.nactive(), Tile, Main.tile, Tile.type, and WheelSparks().
Referenced by GetWheelsPositions(), and Player.Update().