Terraria: IssueReportsIndicator.Draw
Draw()
void IssueReportsIndicator.Draw (SpriteBatch spriteBatch) inline
     {
         bool shouldBeShowing = _shouldBeShowing;
         _displayUpPercent = MathHelper.Clamp(_displayUpPercent + (float)shouldBeShowing.ToDirectionInt(), 0f, 1f);
         if (_displayUpPercent == 0f)
         {
             return;
         }
         Texture2D value = _buttonTexture.Value;
         Vector2 vector = Main.ScreenSize.ToVector2() + new Vector2(40f, -80f);
         Vector2 value2 = vector + new Vector2(-80f, 0f);
         Vector2 vector2 = Vector2.Lerp(vector, value2, _displayUpPercent);
         Rectangle rectangle = value.Frame();
         Vector2 origin = rectangle.Size() / 2f;
         bool flag = false;
         if (Utils.CenteredRectangle(vector2, rectangle.Size()).Contains(Main.MouseScreen.ToPoint()))
         {
             flag = true;
             string textValue = Language.GetTextValue("UI.IssueReporterHasThingsToShow");
             Main.instance.MouseText(textValue, 0, 0);
             if (Main.mouseLeft)
             {
                 OpenUI();
                 Hide();
                 return;
             }
         }
         float scale = 1f;
         spriteBatch.Draw(value, vector2, rectangle, Color.White, 0f, origin, scale, SpriteEffects.None, 0f);
         if (flag)
         {
             Texture2D value3 = _buttonOutlineTexture.Value;
             Rectangle rectangle2 = value3.Frame();
             spriteBatch.Draw(value3, vector2, rectangle2, Color.White, 0f, rectangle2.Size() / 2f, scale, SpriteEffects.None, 0f);
         }
     }
References _buttonOutlineTexture, _buttonTexture, _displayUpPercent, _shouldBeShowing, Utils.CenteredRectangle(), Color, Language.GetTextValue(), Hide(), Main.instance, Main.mouseLeft, Main.MouseScreen, Main.MouseText(), OpenUI(), Main.ScreenSize, and Asset< T >.Value.
Referenced by Main.DrawMenu().