Terraria: System.Xml.Schema.XmlUntypedConverter.ToSingle
ToSingle() [2/3]
override float System.Xml.Schema.XmlUntypedConverter.ToSingle (object value) inline
Definition at line 192 of file XmlUntypedConverter.cs.
    {
        if (value == null)
        {
            throw new ArgumentNullException("value");
        }
        Type type = value.GetType();
        if (type == XmlBaseConverter.StringType)
        {
            return XmlConvert.ToSingle((string)value);
        }
        return (float)ChangeTypeWildcardDestination(value, XmlBaseConverter.SingleType, null);
    }
References System.Xml.Schema.XmlUntypedConverter.ChangeTypeWildcardDestination(), System.Type.GetType(), System.Xml.Schema.XmlBaseConverter.SingleType, System.Xml.Schema.XmlBaseConverter.StringType, System.Xml.XmlConvert.ToSingle(), System.type, and System.value.