Terraria: System.Xml.Schema.XmlUntypedConverter.ToString
ToString() [10/10]
override string System.Xml.Schema.XmlUntypedConverter.ToString (object value, IXmlNamespaceResolver nsResolver) inline
Definition at line 246 of file XmlUntypedConverter.cs.
    {
        if (value == null)
        {
            throw new ArgumentNullException("value");
        }
        Type type = value.GetType();
        if (type == XmlBaseConverter.BooleanType)
        {
            return XmlConvert.ToString((bool)value);
        }
        if (type == XmlBaseConverter.ByteType)
        {
            return XmlConvert.ToString((byte)value);
        }
        if (type == XmlBaseConverter.ByteArrayType)
        {
            return XmlBaseConverter.Base64BinaryToString((byte[])value);
        }
        if (type == XmlBaseConverter.DateTimeType)
        {
            return XmlBaseConverter.DateTimeToString((DateTime)value);
        }
        if (type == XmlBaseConverter.DateTimeOffsetType)
        {
            return XmlBaseConverter.DateTimeOffsetToString((DateTimeOffset)value);
        }
        if (type == XmlBaseConverter.DecimalType)
        {
            return XmlConvert.ToString((decimal)value);
        }
        if (type == XmlBaseConverter.DoubleType)
        {
            return XmlConvert.ToString((double)value);
        }
        if (type == XmlBaseConverter.Int16Type)
        {
            return XmlConvert.ToString((short)value);
        }
        if (type == XmlBaseConverter.Int32Type)
        {
            return XmlConvert.ToString((int)value);
        }
        if (type == XmlBaseConverter.Int64Type)
        {
            return XmlConvert.ToString((long)value);
        }
        if (type == XmlBaseConverter.SByteType)
        {
            return XmlConvert.ToString((sbyte)value);
        }
        if (type == XmlBaseConverter.SingleType)
        {
            return XmlConvert.ToString((float)value);
        }
        if (type == XmlBaseConverter.StringType)
        {
            return (string)value;
        }
        if (type == XmlBaseConverter.TimeSpanType)
        {
            return XmlBaseConverter.DurationToString((TimeSpan)value);
        }
        if (type == XmlBaseConverter.UInt16Type)
        {
            return XmlConvert.ToString((ushort)value);
        }
        if (type == XmlBaseConverter.UInt32Type)
        {
            return XmlConvert.ToString((uint)value);
        }
        if (type == XmlBaseConverter.UInt64Type)
        {
            return XmlConvert.ToString((ulong)value);
        }
        if (XmlBaseConverter.IsDerivedFrom(type, XmlBaseConverter.UriType))
        {
            return XmlBaseConverter.AnyUriToString((Uri)value);
        }
        if (type == XmlBaseConverter.XmlAtomicValueType)
        {
            return (string)((XmlAtomicValue)value).ValueAs(XmlBaseConverter.StringType, nsResolver);
        }
        if (XmlBaseConverter.IsDerivedFrom(type, XmlBaseConverter.XmlQualifiedNameType))
        {
            return XmlBaseConverter.QNameToString((XmlQualifiedName)value, nsResolver);
        }
        return (string)ChangeTypeWildcardDestination(value, XmlBaseConverter.StringType, nsResolver);
    }
References System.Xml.Schema.XmlBaseConverter.AnyUriToString(), System.Xml.Schema.XmlBaseConverter.Base64BinaryToString(), System.Xml.Schema.XmlBaseConverter.BooleanType, System.Xml.Schema.XmlBaseConverter.ByteArrayType, System.Xml.Schema.XmlBaseConverter.ByteType, System.Xml.Schema.XmlUntypedConverter.ChangeTypeWildcardDestination(), System.Xml.Schema.XmlBaseConverter.DateTimeOffsetToString(), System.Xml.Schema.XmlBaseConverter.DateTimeOffsetType, System.Xml.Schema.XmlBaseConverter.DateTimeToString(), System.Xml.Schema.XmlBaseConverter.DateTimeType, System.Xml.Schema.XmlBaseConverter.DecimalType, System.Xml.Dictionary, System.Xml.Schema.XmlBaseConverter.DoubleType, System.Xml.Schema.XmlBaseConverter.DurationToString(), System.Type.GetType(), System.Xml.Schema.XmlBaseConverter.Int16Type, System.Xml.Schema.XmlBaseConverter.Int32Type, System.Xml.Schema.XmlBaseConverter.Int64Type, System.Xml.Schema.XmlBaseConverter.IsDerivedFrom(), System.Xml.Schema.XmlBaseConverter.QNameToString(), System.Xml.Schema.XmlBaseConverter.SByteType, System.Xml.Schema.XmlBaseConverter.SingleType, System.Xml.Schema.XmlBaseConverter.StringType, System.Xml.Schema.XmlBaseConverter.TimeSpanType, System.Xml.XmlConvert.ToString(), System.type, System.Xml.Schema.XmlBaseConverter.UInt16Type, System.Xml.Schema.XmlBaseConverter.UInt32Type, System.Xml.Schema.XmlBaseConverter.UInt64Type, System.Xml.Schema.XmlBaseConverter.UriType, System.value, System.Xml.Schema.XmlBaseConverter.XmlAtomicValueType, and System.Xml.Schema.XmlBaseConverter.XmlQualifiedNameType.