Terraria: System.Xml.Schema.XmlUntypedConverter.Untyped
Untyped
readonly XmlValueConverter System.Xml.Schema.XmlUntypedConverter.Untyped = new XmlUntypedConverter(new XmlUntypedConverter(), allowListToList: false) static
Definition at line 7 of file XmlUntypedConverter.cs.
Referenced by System.Xml.Schema.XmlListConverter.Create(), System.Xml.Schema.Datatype_anySimpleType.CreateValueConverter(), System.Xml.Schema.Datatype_untypedAtomicType.CreateValueConverter(), System.Xml.XsdValidatingReader.ReadContentAs(), System.Xml.XsdValidatingReader.ReadContentAsAsync(), System.Xml.XmlReader.ReadContentAsAsync(), System.Xml.XsdValidatingReader.ReadContentAsBoolean(), System.Xml.XsdValidatingReader.ReadContentAsDateTime(), System.Xml.XsdValidatingReader.ReadContentAsDecimal(), System.Xml.XsdValidatingReader.ReadContentAsDouble(), System.Xml.XsdValidatingReader.ReadContentAsFloat(), System.Xml.XsdValidatingReader.ReadContentAsInt(), System.Xml.XsdValidatingReader.ReadContentAsLong(), System.Xml.XsdValidatingReader.ReadElementContentAs(), System.Xml.XmlReader.ReadElementContentAsAsync(), System.Xml.XsdValidatingReader.ReadElementContentAsAsync(), System.Xml.XsdValidatingReader.ReadElementContentAsBoolean(), System.Xml.XsdValidatingReader.ReadElementContentAsDateTime(), System.Xml.XsdValidatingReader.ReadElementContentAsDecimal(), System.Xml.XsdValidatingReader.ReadElementContentAsDouble(), System.Xml.XsdValidatingReader.ReadElementContentAsFloat(), System.Xml.XsdValidatingReader.ReadElementContentAsInt(), System.Xml.XsdValidatingReader.ReadElementContentAsLong(), System.Xml.XPath.XPathNavigator.SetTypedValue(), System.Xml.XPath.XPathNavigator.ValueAs(), System.Xml.XmlEventCache.WriteValue(), System.Xml.XmlRawWriter.WriteValue(), and System.Xml.XmlWriter.WriteValue().