Terraria: System.Net.IPAddress.Any
Any
readonly IPAddress System.Net.IPAddress.Any = new ReadOnlyIPAddress(new byte[4] { 0, 0, 0, 0 }) static inherited
Definition at line 19 of file IPAddress.cs.
Referenced by System.Net.Sockets.MulticastOption.MulticastOption(), System.Net.Sockets.Socket.Socket(), System.Net.Sockets.TcpListener.TcpListener(), System.Net.Sockets.UdpClient.UdpClient(), Terraria.Netplay.BroadcastThread(), System.Net.NetworkInformation.Ping.CheckArgs(), System.Net.Sockets.TcpListener.Create(), System.Net.Dns.GetHostAddresses(), System.Net.Dns.GetHostEntry(), System.Net.Dns.GetHostEntry(), System.Net.Dns.GetHostEntryAsync(), System.Net.Dns.GetHostEntryOrAddressesCoreAsync(), Interop.HttpApi.GetRemoteEndPoint(), Terraria.Netplay.InitializeServer(), System.Net.Quic.Implementations.MsQuic.Internal.MsQuicAddressHelpers.IPEndPointToINet(), System.Net.Sockets.Socket.IsWildcardEndPoint(), Terraria.Net.Sockets.TcpSocket.StartListening(), and System.Net.Sockets.Socket.WildcardBindForConnectIfNecessary().