Terraria: System.Xml.Schema.XmlUntypedConverter.ToDateTimeOffset
ToDateTimeOffset() [2/3]
override DateTimeOffset System.Xml.Schema.XmlUntypedConverter.ToDateTimeOffset (object value) inline
Definition at line 77 of file XmlUntypedConverter.cs.
    {
        if (value == null)
        {
            throw new ArgumentNullException("value");
        }
        Type type = value.GetType();
        if (type == XmlBaseConverter.StringType)
        {
            return XmlBaseConverter.UntypedAtomicToDateTimeOffset((string)value);
        }
        return (DateTimeOffset)ChangeTypeWildcardDestination(value, XmlBaseConverter.DateTimeOffsetType, null);
    }
References System.Xml.Schema.XmlUntypedConverter.ChangeTypeWildcardDestination(), System.Xml.Schema.XmlBaseConverter.DateTimeOffsetType, System.Type.GetType(), System.Xml.Schema.XmlBaseConverter.StringType, System.type, System.Xml.Schema.XmlBaseConverter.UntypedAtomicToDateTimeOffset(), and System.value.