Terraria: System.Net.IPAddress.HostToNetworkOrder
HostToNetworkOrder() [2/3]
static long System.Net.IPAddress.HostToNetworkOrder (long host) inline static inherited
Definition at line 408 of file IPAddress.cs.
    {
        if (!BitConverter.IsLittleEndian)
        {
            return host;
        }
        return BinaryPrimitives.ReverseEndianness(host);
    }
References System.BitConverter.IsLittleEndian, and System.Buffers.Binary.BinaryPrimitives.ReverseEndianness().
Referenced by System.Net.IPAddressParser.ExtractIPv4Address(), System.Net.IPAddressParser.Ipv4StringToAddress(), System.Net.IPAddress.IsLoopback(), System.Net.IPAddress.MapToIPv4(), System.Net.IPAddress.NetworkToHostOrder(), System.Net.IPAddress.NetworkToHostOrder(), System.Net.IPAddress.NetworkToHostOrder(), System.Net.Sockets.SocketPal.SetMulticastOption(), and System.Net.Quic.Implementations.MsQuic.Internal.MsQuicAddressHelpers.SetPort().