Terraria: System.Xml.Schema.XmlUntypedConverter.ChangeListType
ChangeListType()
override object System.Xml.Schema.XmlUntypedConverter.ChangeListType (object value, Type destinationType, IXmlNamespaceResolver nsResolver) inline protected virtual
Reimplemented from System.Xml.Schema.XmlListConverter.
Definition at line 690 of file XmlUntypedConverter.cs.
    {
        Type type = value.GetType();
        if (atomicConverter == null || (!_allowListToList && type != XmlBaseConverter.StringType && destinationType != XmlBaseConverter.StringType))
        {
            if (SupportsType(type))
            {
                throw new InvalidCastException(System.SR.Format(System.SR.XmlConvert_TypeToString, base.XmlTypeName, type.Name));
            }
            if (SupportsType(destinationType))
            {
                throw new InvalidCastException(System.SR.Format(System.SR.XmlConvert_TypeFromString, base.XmlTypeName, destinationType.Name));
            }
            throw CreateInvalidClrMappingException(type, destinationType);
        }
        return base.ChangeListType(value, destinationType, nsResolver);
    }
References System.Xml.Schema.XmlUntypedConverter._allowListToList, System.Xml.Schema.XmlListConverter.atomicConverter, System.Xml.Schema.XmlListConverter.CreateInvalidClrMappingException(), System.Xml.Dictionary, System.SR.Format(), System.Type.GetType(), System.Xml.Schema.XmlBaseConverter.StringType, System.Xml.Schema.XmlUntypedConverter.SupportsType(), System.type, System.value, System.SR.XmlConvert_TypeFromString, and System.SR.XmlConvert_TypeToString.
Referenced by System.Xml.Schema.XmlUntypedConverter.ChangeType(), System.Xml.Schema.XmlUntypedConverter.ChangeTypeWildcardDestination(), and System.Xml.Schema.XmlUntypedConverter.ChangeTypeWildcardSource().