Terraria: System.Xml.Schema.XmlUntypedConverter.ChangeType
ChangeType() [8/9]
override object System.Xml.Schema.XmlUntypedConverter.ChangeType (object value, Type destinationType, IXmlNamespaceResolver nsResolver) inline
Definition at line 539 of file XmlUntypedConverter.cs.
    {
        if (value == null)
        {
            throw new ArgumentNullException("value");
        }
        if (destinationType == null)
        {
            throw new ArgumentNullException("destinationType");
        }
        Type type = value.GetType();
        if (destinationType == XmlBaseConverter.ObjectType)
        {
            destinationType = base.DefaultClrType;
        }
        if (destinationType == XmlBaseConverter.BooleanType && type == XmlBaseConverter.StringType)
        {
            return XmlConvert.ToBoolean((string)value);
        }
        if (destinationType == XmlBaseConverter.ByteType && type == XmlBaseConverter.StringType)
        {
            return XmlBaseConverter.Int32ToByte(XmlConvert.ToInt32((string)value));
        }
        if (destinationType == XmlBaseConverter.ByteArrayType && type == XmlBaseConverter.StringType)
        {
            return XmlBaseConverter.StringToBase64Binary((string)value);
        }
        if (destinationType == XmlBaseConverter.DateTimeType && type == XmlBaseConverter.StringType)
        {
            return XmlBaseConverter.UntypedAtomicToDateTime((string)value);
        }
        if (destinationType == XmlBaseConverter.DateTimeOffsetType && type == XmlBaseConverter.StringType)
        {
            return XmlBaseConverter.UntypedAtomicToDateTimeOffset((string)value);
        }
        if (destinationType == XmlBaseConverter.DecimalType && type == XmlBaseConverter.StringType)
        {
            return XmlConvert.ToDecimal((string)value);
        }
        if (destinationType == XmlBaseConverter.DoubleType && type == XmlBaseConverter.StringType)
        {
            return XmlConvert.ToDouble((string)value);
        }
        if (destinationType == XmlBaseConverter.Int16Type && type == XmlBaseConverter.StringType)
        {
            return XmlBaseConverter.Int32ToInt16(XmlConvert.ToInt32((string)value));
        }
        if (destinationType == XmlBaseConverter.Int32Type && type == XmlBaseConverter.StringType)
        {
            return XmlConvert.ToInt32((string)value);
        }
        if (destinationType == XmlBaseConverter.Int64Type && type == XmlBaseConverter.StringType)
        {
            return XmlConvert.ToInt64((string)value);
        }
        if (destinationType == XmlBaseConverter.SByteType && type == XmlBaseConverter.StringType)
        {
            return XmlBaseConverter.Int32ToSByte(XmlConvert.ToInt32((string)value));
        }
        if (destinationType == XmlBaseConverter.SingleType && type == XmlBaseConverter.StringType)
        {
            return XmlConvert.ToSingle((string)value);
        }
        if (destinationType == XmlBaseConverter.TimeSpanType && type == XmlBaseConverter.StringType)
        {
            return XmlBaseConverter.StringToDuration((string)value);
        }
        if (destinationType == XmlBaseConverter.UInt16Type && type == XmlBaseConverter.StringType)
        {
            return XmlBaseConverter.Int32ToUInt16(XmlConvert.ToInt32((string)value));
        }
        if (destinationType == XmlBaseConverter.UInt32Type && type == XmlBaseConverter.StringType)
        {
            return XmlBaseConverter.Int64ToUInt32(XmlConvert.ToInt64((string)value));
        }
        if (destinationType == XmlBaseConverter.UInt64Type && type == XmlBaseConverter.StringType)
        {
            return XmlBaseConverter.DecimalToUInt64(XmlConvert.ToDecimal((string)value));
        }
        if (destinationType == XmlBaseConverter.UriType && type == XmlBaseConverter.StringType)
        {
            return XmlConvert.ToUri((string)value);
        }
        if (destinationType == XmlBaseConverter.XmlAtomicValueType)
        {
            if (type == XmlBaseConverter.StringType)
            {
                return new XmlAtomicValue(base.SchemaType, (string)value);
            }
            if (type == XmlBaseConverter.XmlAtomicValueType)
            {
                return (XmlAtomicValue)value;
            }
        }
        if (destinationType == XmlBaseConverter.XmlQualifiedNameType && type == XmlBaseConverter.StringType)
        {
            return XmlBaseConverter.StringToQName((string)value, nsResolver);
        }
        if (destinationType == XmlBaseConverter.XPathItemType)
        {
            if (type == XmlBaseConverter.StringType)
            {
                return new XmlAtomicValue(base.SchemaType, (string)value);
            }
            if (type == XmlBaseConverter.XmlAtomicValueType)
            {
                return (XmlAtomicValue)value;
            }
        }
        if (destinationType == XmlBaseConverter.StringType)
        {
            return ToString(value, nsResolver);
        }
        if (destinationType == XmlBaseConverter.XmlAtomicValueType)
        {
            return new XmlAtomicValue(base.SchemaType, ToString(value, nsResolver));
        }
        if (destinationType == XmlBaseConverter.XPathItemType)
        {
            return new XmlAtomicValue(base.SchemaType, ToString(value, nsResolver));
        }
        if (type == XmlBaseConverter.XmlAtomicValueType)
        {
            return ((XmlAtomicValue)value).ValueAs(destinationType, nsResolver);
        }
        return ChangeListType(value, destinationType, nsResolver);
    }
References System.Xml.Schema.XmlBaseConverter.BooleanType, System.Xml.Schema.XmlBaseConverter.ByteArrayType, System.Xml.Schema.XmlBaseConverter.ByteType, System.Xml.Schema.XmlUntypedConverter.ChangeListType(), System.Xml.Schema.XmlBaseConverter.DateTimeOffsetType, System.Xml.Schema.XmlBaseConverter.DateTimeType, System.Xml.Schema.XmlBaseConverter.DecimalToUInt64(), System.Xml.Schema.XmlBaseConverter.DecimalType, System.Xml.Dictionary, System.Xml.Schema.XmlBaseConverter.DoubleType, System.Type.GetType(), System.Xml.Schema.XmlBaseConverter.Int16Type, System.Xml.Schema.XmlBaseConverter.Int32ToByte(), System.Xml.Schema.XmlBaseConverter.Int32ToInt16(), System.Xml.Schema.XmlBaseConverter.Int32ToSByte(), System.Xml.Schema.XmlBaseConverter.Int32ToUInt16(), System.Xml.Schema.XmlBaseConverter.Int32Type, System.Xml.Schema.XmlBaseConverter.Int64ToUInt32(), System.Xml.Schema.XmlBaseConverter.Int64Type, System.Xml.Schema.XmlBaseConverter.ObjectType, System.Xml.Schema.XmlBaseConverter.SByteType, System.Xml.Schema.XmlBaseConverter.SingleType, System.Xml.Schema.XmlBaseConverter.StringToBase64Binary(), System.Xml.Schema.XmlBaseConverter.StringToDuration(), System.Xml.Schema.XmlBaseConverter.StringToQName(), System.Xml.Schema.XmlBaseConverter.StringType, System.Xml.Schema.XmlBaseConverter.TimeSpanType, System.Xml.XmlConvert.ToBoolean(), System.Xml.XmlConvert.ToDecimal(), System.Xml.XmlConvert.ToDouble(), System.Xml.XmlConvert.ToInt32(), System.Xml.XmlConvert.ToInt64(), System.Xml.XmlConvert.ToSingle(), System.ToString, System.Xml.XmlConvert.ToUri(), System.type, System.Xml.Schema.XmlBaseConverter.UInt16Type, System.Xml.Schema.XmlBaseConverter.UInt32Type, System.Xml.Schema.XmlBaseConverter.UInt64Type, System.Xml.Schema.XmlBaseConverter.UntypedAtomicToDateTime(), System.Xml.Schema.XmlBaseConverter.UntypedAtomicToDateTimeOffset(), System.Xml.Schema.XmlBaseConverter.UriType, System.value, System.Xml.Schema.XmlBaseConverter.XmlAtomicValueType, System.Xml.Schema.XmlBaseConverter.XmlQualifiedNameType, and System.Xml.Schema.XmlBaseConverter.XPathItemType.