Terraria: System.Net.IPAddress.Equals
Equals() [1/2]
override bool System.Net.IPAddress.Equals ([NotNullWhen(true)] object? comparand) inline inherited
Definition at line 468 of file IPAddress.cs.
    {
        if (comparand is IPAddress comparand2)
        {
            return Equals(comparand2);
        }
        return false;
    }
References System.Net.Equals.
Referenced by System.Net.NetworkInformation.Ping.CheckArgs(), System.Net.IPEndPoint.Equals(), System.Net.Dns.GetHostEntry(), System.Net.Dns.GetHostEntryAsync(), System.Net.Quic.Implementations.MsQuic.Internal.MsQuicAddressHelpers.IPEndPointToINet(), System.Net.Sockets.UdpClient.IsBroadcast(), Terraria.Net.TcpAddress.IsLocalHost(), System.Net.IPAddress.IsLoopback(), and System.Net.Sockets.IPPacketInformation.operator==().