Terraria: System.Net.IPAddress.IsLoopback
IsLoopback()
static bool System.Net.IPAddress.IsLoopback (IPAddress address) inline static inherited
Definition at line 450 of file IPAddress.cs.
    {
        if (address == null)
        {
            ThrowAddressNullException();
        }
        if (address.IsIPv6)
        {
            if (!address.Equals(IPv6Loopback))
            {
                return address.Equals(s_loopbackMappedToIPv6);
            }
            return true;
        }
        long num = (uint)HostToNetworkOrder(-16777216);
        return (address.PrivateAddress & num) == (Loopback.PrivateAddress & num);
    }
References System.Net.IPAddress.Equals(), System.Net.IPAddress.HostToNetworkOrder(), System.Net.IPAddress.IPv6Loopback, System.Net.IPAddress.IsIPv6, System.Net.IPAddress.PrivateAddress, System.Net.IPAddress.s_loopbackMappedToIPv6, and System.Net.IPAddress.ThrowAddressNullException().