Terraria: System.Xml.Schema.XmlUntypedConverter.ChangeTypeWildcardSource
ChangeTypeWildcardSource()
object System.Xml.Schema.XmlUntypedConverter.ChangeTypeWildcardSource (object value, Type destinationType, IXmlNamespaceResolver nsResolver) inline private
Definition at line 677 of file XmlUntypedConverter.cs.
    {
        if (destinationType == XmlBaseConverter.XmlAtomicValueType)
        {
            return new XmlAtomicValue(base.SchemaType, ToString(value, nsResolver));
        }
        if (destinationType == XmlBaseConverter.XPathItemType)
        {
            return new XmlAtomicValue(base.SchemaType, ToString(value, nsResolver));
        }
        return ChangeListType(value, destinationType, nsResolver);
    }
References System.Xml.Schema.XmlUntypedConverter.ChangeListType(), System.Xml.Dictionary, System.ToString, System.value, System.Xml.Schema.XmlBaseConverter.XmlAtomicValueType, and System.Xml.Schema.XmlBaseConverter.XPathItemType.
Referenced by System.Xml.Schema.XmlUntypedConverter.ChangeType(), System.Xml.Schema.XmlUntypedConverter.ChangeType(), System.Xml.Schema.XmlUntypedConverter.ChangeType(), System.Xml.Schema.XmlUntypedConverter.ChangeType(), System.Xml.Schema.XmlUntypedConverter.ChangeType(), System.Xml.Schema.XmlUntypedConverter.ChangeType(), and System.Xml.Schema.XmlUntypedConverter.ChangeType().