Terraria: System.Xml.Schema.XmlUntypedConverter.ChangeTypeWildcardDestination
ChangeTypeWildcardDestination()
object System.Xml.Schema.XmlUntypedConverter.ChangeTypeWildcardDestination (object value, Type destinationType, IXmlNamespaceResolver nsResolver) inline private
Definition at line 667 of file XmlUntypedConverter.cs.
    {
        Type type = value.GetType();
        if (type == XmlBaseConverter.XmlAtomicValueType)
        {
            return ((XmlAtomicValue)value).ValueAs(destinationType, nsResolver);
        }
        return ChangeListType(value, destinationType, nsResolver);
    }
References System.Xml.Schema.XmlUntypedConverter.ChangeListType(), System.Xml.Dictionary, System.Type.GetType(), System.type, System.value, and System.Xml.Schema.XmlBaseConverter.XmlAtomicValueType.
Referenced by System.Xml.Schema.XmlUntypedConverter.ToBoolean(), System.Xml.Schema.XmlUntypedConverter.ToDateTime(), System.Xml.Schema.XmlUntypedConverter.ToDateTimeOffset(), System.Xml.Schema.XmlUntypedConverter.ToDecimal(), System.Xml.Schema.XmlUntypedConverter.ToDouble(), System.Xml.Schema.XmlUntypedConverter.ToInt32(), System.Xml.Schema.XmlUntypedConverter.ToInt64(), System.Xml.Schema.XmlUntypedConverter.ToSingle(), and System.Xml.Schema.XmlUntypedConverter.ToString().