Terraria: System.Net.IPAddress.TryParse
TryParse() [1/2]
static bool System.Net.IPAddress.TryParse ([NotNullWhen(true)] string? ipString, [NotNullWhen(true)] out IPAddress? address) inline static inherited
Definition at line 303 of file IPAddress.cs.
    {
        if (ipString == null)
        {
            address = null;
            return false;
        }
        address = IPAddressParser.Parse(ipString.AsSpan(), tryParse: true);
        return address != null;
    }
References System.Net.IPAddressParser.Parse().
Referenced by System.Net.ServiceNameStore.BuildServiceNames(), System.Net.Sockets.Socket.Connect(), System.Net.Quic.Implementations.MsQuic.MsQuicConnection.ConnectAsync(), System.Net.Sockets.Socket.ConnectAsync(), System.Net.Http.SocksHelper.EstablishSocks4TunnelAsync(), System.Net.Http.SocksHelper.EstablishSocks5TunnelAsync(), System.Net.Dns.GetHostAddresses(), System.Net.Dns.GetHostByName(), System.Net.Dns.GetHostEntry(), System.Net.Dns.GetHostEntryOrAddressesCoreAsync(), System.Net.Http.HttpWindowsProxy.GetMultiProxy(), System.Net.WebProxy.IsLocal(), System.Net.Dns.Resolve(), System.Net.NetworkInformation.Ping.Send(), System.Net.NetworkInformation.Ping.SendPingAsync(), Terraria.Netplay.SetRemoteIPAsync(), Terraria.Netplay.SetRemoteIPOld(), Terraria.Net.Sockets.TcpSocket.StartListening(), and System.Net.IPEndPoint.TryParse().