Terraria: System.Net.IPAddress.MapToIPv6
MapToIPv6()
IPAddress System.Net.IPAddress.MapToIPv6 () inline inherited
Definition at line 513 of file IPAddress.cs.
    {
        if (IsIPv6)
        {
            return this;
        }
        uint num = (uint)NetworkToHostOrder((int)PrivateAddress);
        return new IPAddress(new ushort[8]
        {
            0,
            0,
            0,
            0,
            0,
            65535,
            (ushort)(num >> 16),
            (ushort)num
        }, 0u);
    }
References System.Net.IPAddress.IPAddress(), System.Net.IPAddress.IsIPv6, System.Net.IPAddress.NetworkToHostOrder(), and System.Net.IPAddress.PrivateAddress.
Referenced by System.Net.Sockets.Socket.Serialize().