Terraria: System.Net.IPAddress.GetAddressBytes
GetAddressBytes()
byte[] System.Net.IPAddress.GetAddressBytes () inline inherited
Definition at line 377 of file IPAddress.cs.
    {
        if (IsIPv6)
        {
            byte[] array = new byte[16];
            WriteIPv6Bytes(array);
            return array;
        }
        byte[] array2 = new byte[4];
        WriteIPv4Bytes(array2);
        return array2;
    }
References System.array, System.Net.IPAddress.IsIPv6, System.Net.IPAddress.WriteIPv4Bytes(), and System.Net.IPAddress.WriteIPv6Bytes().
Referenced by System.Net.FtpControlStream.FormatAddress(), and System.Net.NetworkInformation.Ping.GetAddressSnapshot().