Terraria: System.Threading.EventWaitHandle.Set
Set() [1/2]
bool System.Threading.EventWaitHandle.Set () inline inherited
Definition at line 118 of file EventWaitHandle.cs.
    {
        bool flag = Interop.Kernel32.SetEvent(base.SafeWaitHandle);
        if (!flag)
        {
            throw Win32Marshal.GetExceptionForLastWin32Error();
        }
        return flag;
    }
References System.IO.Win32Marshal.GetExceptionForLastWin32Error(), and Interop.Kernel32.SetEvent().
Referenced by System.Threading.ReaderWriterLockSlim.ExitAndWakeUpAppropriateReadWaiters(), System.Threading.ReaderWriterLockSlim.ExitAndWakeUpAppropriateWaitersPreferringWriters(), System.Transactions.CheapUnfairReaderWriterLock.ExitWriteLock(), System.Net.LazyAsyncResult.LazilyCreateEvent(), System.Threading.ManualResetEventSlim.LazyInitializeEvent(), System.Threading.RegisteredWaitHandle.OnRemoveWait(), System.Net.LazyAsyncResult.ProtectedInvokeCallback(), System.Threading.PortableThreadPool.WaitThread.RegisterWaitHandle(), System.Threading.SemaphoreSlim.Release(), System.Threading.ManualResetEventSlim.Set(), System.Transactions.InternalTransaction.SignalAsyncCompletion(), System.Threading.TimerQueueTimer.SignalNoCallbacksRunning(), System.Threading.RegisteredWaitHandle.SignalUserWaitHandle(), System.Diagnostics.Tracing.EventPipeEventDispatcher.StopDispatchTask(), and System.Threading.PortableThreadPool.WaitThread.UnregisterWait().