Terraria: System.Threading.EventWaitHandle.CreateEventCore
CreateEventCore()
void System.Threading.EventWaitHandle.CreateEventCore (bool initialState, EventResetMode mode, string name, out bool createdNew) inline private inherited
Definition at line 54 of file EventWaitHandle.cs.
    {
        uint num = (initialState ? 2u : 0u);
        if (mode == EventResetMode.ManualReset)
        {
            num |= 1u;
        }
        SafeWaitHandle safeWaitHandle = Interop.Kernel32.CreateEventEx(IntPtr.Zero, name, num, 34603010u);
        int lastPInvokeError = Marshal.GetLastPInvokeError();
        if (safeWaitHandle.IsInvalid)
        {
            safeWaitHandle.SetHandleAsInvalid();
            if (!string.IsNullOrEmpty(name) && lastPInvokeError == 6)
            {
                throw new WaitHandleCannotBeOpenedException(SR.Format(SR.Threading_WaitHandleCannotBeOpenedException_InvalidHandle, name));
            }
            throw Win32Marshal.GetExceptionForWin32Error(lastPInvokeError, name);
        }
        createdNew = lastPInvokeError != 183;
        base.SafeWaitHandle = safeWaitHandle;
    }
References Interop.Kernel32.CreateEventEx(), System.SR.Format(), System.IO.Win32Marshal.GetExceptionForWin32Error(), System.Runtime.InteropServices.Marshal.GetLastPInvokeError(), Microsoft.Win32.SafeHandles.SafeHandleZeroOrMinusOneIsInvalid.IsInvalid, System.Runtime.InteropServices.SafeHandle.SetHandleAsInvalid(), System.SR.Threading_WaitHandleCannotBeOpenedException_InvalidHandle, and System.IntPtr.Zero.
Referenced by System.Threading.EventWaitHandle.EventWaitHandle().