Terraria: System.Numerics.Matrix3x2.CreateRotation
CreateRotation() [1/2]
static Matrix3x2 System.Numerics.Matrix3x2.CreateRotation (float radians) inline static
Definition at line 130 of file Matrix3x2.cs.
    {
        radians = MathF.IEEERemainder(radians, (float)Math.PI * 2f);
        float num;
        float num2;
        if (radians > -1.7453294E-05f && radians < 1.7453294E-05f)
        {
            num = 1f;
            num2 = 0f;
        }
        else if (radians > 1.570779f && radians < 1.5708138f)
        {
            num = 0f;
            num2 = 1f;
        }
        else if (radians < -3.1415753f || radians > 3.1415753f)
        {
            num = -1f;
            num2 = 0f;
        }
        else if (radians > -1.5708138f && radians < -1.570779f)
        {
            num = 0f;
            num2 = -1f;
        }
        else
        {
            num = MathF.Cos(radians);
            num2 = MathF.Sin(radians);
        }
        Matrix3x2 identity = Identity;
        identity.M11 = num;
        identity.M12 = num2;
        identity.M21 = 0f - num2;
        identity.M22 = num;
        return identity;
    }
References System.MathF.Cos(), System.E, System.Numerics.Matrix3x2.Identity, System.MathF.IEEERemainder(), System.Math.PI, and System.MathF.Sin().