Terraria: CreativePowersHelper.GetIconImage
GetIconImage()
static UIImageFramed CreativePowersHelper.GetIconImage (Point iconLocation) inline static
     {
         Asset<Texture2D> powerIconAsset = GetPowerIconAsset("Images/UI/Creative/Infinite_Powers");
         return new UIImageFramed(powerIconAsset, powerIconAsset.Frame(21, 1, iconLocation.X, iconLocation.Y))
         {
             MarginLeft = 4f,
             MarginTop = 4f,
             VAlign = 0.5f,
             HAlign = 1f,
             IgnoresMouseInteraction = true
         };
     }
References GetPowerIconAsset().
Referenced by UICreativePowersMenu.CreateMainPowerStrip(), CreativePowers.FreezeTime.CustomizeButton(), CreativePowers.FreezeWindDirectionAndStrength.CustomizeButton(), CreativePowers.FreezeRainPower.CustomizeButton(), CreativePowers.StopBiomeSpreadPower.CustomizeButton(), CreativePowers.APerPlayerSliderPower.GetOptionButton(), CreativePowers.ASharedSliderPower.GetOptionButton(), CreativePowers.APerPlayerTogglePower.ProvidePowerButtons(), and CreativePowers.ASharedButtonPower.ProvidePowerButtons().