Terraria: System.Text.Encodings.Web.SpanUtility.TryWriteUInt64LittleEndian
TryWriteUInt64LittleEndian()
static bool System.Text.Encodings.Web.SpanUtility.TryWriteUInt64LittleEndian (Span< byte > span, int offset, ulong value) inline static
Definition at line 130 of file SpanUtility.cs.
    {
        if (AreValidIndexAndLength(span.Length, offset, 8))
        {
            if (!BitConverter.IsLittleEndian)
            {
                value = BinaryPrimitives.ReverseEndianness(value);
            }
            Unsafe.WriteUnaligned(ref Unsafe.Add(ref MemoryMarshal.GetReference(span), (nint)(uint)offset), value);
            return true;
        }
        return false;
    }
References System.Text.Encodings.Web.SpanUtility.AreValidIndexAndLength(), System.BitConverter.IsLittleEndian, System.Span< T >.Length, System.offset, System.Buffers.Binary.BinaryPrimitives.ReverseEndianness(), and System.Text.Encodings.Web.value.
Referenced by System.Text.Encodings.Web.OptimizedInboxTextEncoder.EncodeUtf8().