Terraria: Terraria.Social.Steam.WorkshopHelper.UGCBased.APublisherInstance.PublishContent
PublishContent()
void Terraria.Social.Steam.WorkshopHelper.UGCBased.APublisherInstance.PublishContent (PublishedItemsFinder finder, WorkshopIssueReporter issueReporter, FinishedPublishingAction endAction, string itemTitle, string itemDescription, string contentFolderPath, string previewImagePath, WorkshopItemPublicSettingId publicity, string[] tags) inline inherited
Definition at line 222 of file WorkshopHelper.cs.
            {
                //IL_003f: Unknown result type (might be due to invalid IL or missing references)
                //IL_0044: Unknown result type (might be due to invalid IL or missing references)
                //IL_007d: Unknown result type (might be due to invalid IL or missing references)
                //IL_00e9: Unknown result type (might be due to invalid IL or missing references)
                //IL_00ee: Unknown result type (might be due to invalid IL or missing references)
                _issueReporter = issueReporter;
                _endAction = endAction;
                _createItemHook = CallResult<CreateItemResult_t>.Create((APIDispatchDelegate<CreateItemResult_t>)CreateItemResult);
                _updateItemHook = CallResult<SubmitItemUpdateResult_t>.Create((APIDispatchDelegate<SubmitItemUpdateResult_t>)UpdateItemResult);
                ERemoteStoragePublishedFileVisibility visibility = GetVisibility(publicity);
                _entryData = new SteamWorkshopItem
                {
                    Title = itemTitle,
                    Description = itemDescription,
                    ContentFolderPath = contentFolderPath,
                    Tags = tags,
                    PreviewImagePath = previewImagePath,
                    Visibility = visibility
                };
                ulong? num = null;
                if (AWorkshopEntry.TryReadingManifest(contentFolderPath + Path.DirectorySeparatorChar + "workshop.json", out var info))
                {
                    num = info.workshopEntryId;
                }
                if (num.HasValue && finder.HasItemOfId(num.Value))
                {
                    _publishedFileID = new PublishedFileId_t(num.Value);
                    PreventUpdatingCertainThings();
                    UpdateItem();
                }
                else
                {
                    CreateItem();
                }
            }
References Terraria.Social.Steam.WorkshopHelper.UGCBased.APublisherInstance._createItemHook, Terraria.Social.Steam.WorkshopHelper.UGCBased.APublisherInstance._endAction, Terraria.Social.Steam.WorkshopHelper.UGCBased.APublisherInstance._entryData, Terraria.Social.Steam.WorkshopHelper.UGCBased.APublisherInstance._issueReporter, Terraria.Social.Steam.WorkshopHelper.UGCBased.APublisherInstance._publishedFileID, Terraria.Social.Steam.WorkshopHelper.UGCBased.APublisherInstance._updateItemHook, Terraria.Social.Steam.WorkshopHelper.UGCBased.APublisherInstance.CreateItem(), Terraria.Social.Steam.WorkshopHelper.UGCBased.APublisherInstance.CreateItemResult(), Terraria.Social.Steam.WorkshopHelper.UGCBased.APublisherInstance.GetVisibility(), Terraria.Social.Steam.WorkshopHelper.UGCBased.PublishedItemsFinder.HasItemOfId(), Terraria.Social.Steam.WorkshopHelper.UGCBased.APublisherInstance.PreventUpdatingCertainThings(), Terraria.Social.Base.AWorkshopEntry.TryReadingManifest(), Terraria.Social.Steam.WorkshopHelper.UGCBased.APublisherInstance.UpdateItem(), and Terraria.Social.Steam.WorkshopHelper.UGCBased.APublisherInstance.UpdateItemResult().
Referenced by Terraria.Social.Steam.WorkshopSocialModule.PublishResourcePack(), and Terraria.Social.Steam.WorkshopSocialModule.PublishWorld().