Terraria: Terraria.Social.Steam.WorkshopHelper.UGCBased.APublisherInstance.CreateItemResult
CreateItemResult()
void Terraria.Social.Steam.WorkshopHelper.UGCBased.APublisherInstance.CreateItemResult (CreateItemResult_t param, bool bIOFailure) inline private inherited
Definition at line 288 of file WorkshopHelper.cs.
            {
                //IL_0000: Unknown result type (might be due to invalid IL or missing references)
                //IL_0025: Unknown result type (might be due to invalid IL or missing references)
                //IL_0026: Unknown result type (might be due to invalid IL or missing references)
                //IL_002c: Invalid comparison between Unknown and I4
                //IL_002f: Unknown result type (might be due to invalid IL or missing references)
                //IL_0030: Unknown result type (might be due to invalid IL or missing references)
                //IL_0035: Unknown result type (might be due to invalid IL or missing references)
                if (param.m_bUserNeedsToAcceptWorkshopLegalAgreement)
                {
                    _issueReporter.ReportDelayedUploadProblem("Workshop.ReportIssue_FailedToPublish_UserDidNotAcceptWorkshopTermsOfService");
                    _endAction(this);
                }
                else if ((int)param.m_eResult == 1)
                {
                    _publishedFileID = param.m_nPublishedFileId;
                    UpdateItem();
                }
                else
                {
                    _issueReporter.ReportDelayedUploadProblemWithoutKnownReason("Workshop.ReportIssue_FailedToPublish_WithoutKnownReason", ((object)(EResult)(ref param.m_eResult)).ToString());
                    _endAction(this);
                }
            }
References Terraria.Social.Steam.WorkshopHelper.UGCBased.APublisherInstance._endAction, Terraria.Social.Steam.WorkshopHelper.UGCBased.APublisherInstance._issueReporter, Terraria.Social.Steam.WorkshopHelper.UGCBased.APublisherInstance._publishedFileID, Terraria.Social.Base.WorkshopIssueReporter.ReportDelayedUploadProblem(), Terraria.Social.Base.WorkshopIssueReporter.ReportDelayedUploadProblemWithoutKnownReason(), and Terraria.Social.Steam.WorkshopHelper.UGCBased.APublisherInstance.UpdateItem().
Referenced by Terraria.Social.Steam.WorkshopHelper.UGCBased.APublisherInstance.CreateItem(), and Terraria.Social.Steam.WorkshopHelper.UGCBased.APublisherInstance.PublishContent().