Terraria: Terraria.Social.Steam.WorkshopHelper.UGCBased.APublisherInstance.UpdateItem
UpdateItem()
void Terraria.Social.Steam.WorkshopHelper.UGCBased.APublisherInstance.UpdateItem () inline private inherited
Definition at line 318 of file WorkshopHelper.cs.
            {
                //IL_002e: Unknown result type (might be due to invalid IL or missing references)
                //IL_0034: Unknown result type (might be due to invalid IL or missing references)
                //IL_0039: Unknown result type (might be due to invalid IL or missing references)
                //IL_003e: Unknown result type (might be due to invalid IL or missing references)
                //IL_004c: Unknown result type (might be due to invalid IL or missing references)
                //IL_007d: Unknown result type (might be due to invalid IL or missing references)
                //IL_008f: Unknown result type (might be due to invalid IL or missing references)
                //IL_006b: Unknown result type (might be due to invalid IL or missing references)
                //IL_00ae: Unknown result type (might be due to invalid IL or missing references)
                //IL_00ef: Unknown result type (might be due to invalid IL or missing references)
                //IL_00f5: Unknown result type (might be due to invalid IL or missing references)
                //IL_00fa: Unknown result type (might be due to invalid IL or missing references)
                //IL_00fc: Unknown result type (might be due to invalid IL or missing references)
                //IL_00fd: Unknown result type (might be due to invalid IL or missing references)
                //IL_0108: Unknown result type (might be due to invalid IL or missing references)
                //IL_00d2: Unknown result type (might be due to invalid IL or missing references)
                //IL_00de: Unknown result type (might be due to invalid IL or missing references)
                string headerText = GetHeaderText();
                if (!TryWritingManifestToFolder(_entryData.ContentFolderPath, headerText))
                {
                    _endAction(this);
                    return;
                }
                PrepareContentForUpdate();
                UGCUpdateHandle_t val = SteamUGC.StartItemUpdate(SteamUtils.GetAppID(), _publishedFileID);
                if (_entryData.Title != null)
                {
                    SteamUGC.SetItemTitle(val, _entryData.Title);
                }
                if (_entryData.Description != null)
                {
                    SteamUGC.SetItemDescription(val, _entryData.Description);
                }
                SteamUGC.SetItemContent(val, _entryData.ContentFolderPath);
                SteamUGC.SetItemTags(val, (IList<string>)_entryData.Tags);
                if (_entryData.PreviewImagePath != null)
                {
                    SteamUGC.SetItemPreview(val, _entryData.PreviewImagePath);
                }
                if (_entryData.Visibility.HasValue)
                {
                    SteamUGC.SetItemVisibility(val, _entryData.Visibility.Value);
                }
                CoreSocialModule.SetSkipPulsing(shouldSkipPausing: true);
                SteamAPICall_t val2 = SteamUGC.SubmitItemUpdate(val, "");
                _updateHandle = val;
                _updateItemHook.Set(val2, (APIDispatchDelegate<SubmitItemUpdateResult_t>)UpdateItemResult);
                CoreSocialModule.SetSkipPulsing(shouldSkipPausing: false);
            }
References Terraria.Social.Steam.WorkshopHelper.UGCBased.APublisherInstance._endAction, Terraria.Social.Steam.WorkshopHelper.UGCBased.APublisherInstance._entryData, Terraria.Social.Steam.WorkshopHelper.UGCBased.APublisherInstance._publishedFileID, Terraria.Social.Steam.WorkshopHelper.UGCBased.APublisherInstance._updateHandle, Terraria.Social.Steam.WorkshopHelper.UGCBased.APublisherInstance._updateItemHook, Terraria.Social.Steam.WorkshopHelper.UGCBased.SteamWorkshopItem.ContentFolderPath, Terraria.Social.Steam.WorkshopHelper.UGCBased.SteamWorkshopItem.Description, Terraria.Social.Steam.WorkshopHelper.UGCBased.APublisherInstance.GetHeaderText(), Terraria.Social.Steam.WorkshopHelper.UGCBased.APublisherInstance.PrepareContentForUpdate(), Terraria.Social.Steam.WorkshopHelper.UGCBased.SteamWorkshopItem.PreviewImagePath, Terraria.Social.Steam.CoreSocialModule.SetSkipPulsing(), Terraria.Social.Steam.WorkshopHelper.UGCBased.SteamWorkshopItem.Tags, Terraria.Social.Steam.WorkshopHelper.UGCBased.SteamWorkshopItem.Title, Terraria.Social.Steam.WorkshopHelper.UGCBased.APublisherInstance.TryWritingManifestToFolder(), Terraria.Social.Steam.WorkshopHelper.UGCBased.APublisherInstance.UpdateItemResult(), and Terraria.Social.Steam.WorkshopHelper.UGCBased.SteamWorkshopItem.Visibility.
Referenced by Terraria.Social.Steam.WorkshopHelper.UGCBased.APublisherInstance.CreateItemResult(), and Terraria.Social.Steam.WorkshopHelper.UGCBased.APublisherInstance.PublishContent().