Terraria: System.Net.WebSockets.ServerWebSocket.ServerWebSocket
ServerWebSocket()
System.Net.WebSockets.ServerWebSocket.ServerWebSocket (Stream innerStream, string subProtocol, int receiveBufferSize, TimeSpan keepAliveInterval, ArraySegment< byte > internalBuffer) inline
Definition at line 27 of file ServerWebSocket.cs.
        : base(innerStream, subProtocol, keepAliveInterval, WebSocketBuffer.CreateServerBuffer(internalBuffer, receiveBufferSize))
    {
        _properties = base.InternalBuffer.CreateProperties(useZeroMaskingKey: false);
        _sessionHandle = CreateWebSocketHandle();
        if (_sessionHandle == null || _sessionHandle.IsInvalid)
        {
            HttpWebSocket.ThrowPlatformNotSupportedException_WSPC();
        }
        StartKeepAliveTimer();
    }
References System.Net.WebSockets.ServerWebSocket._properties, System.Net.WebSockets.ServerWebSocket._sessionHandle, System.Net.WebSockets.ServerWebSocket.CreateWebSocketHandle(), System.Runtime.InteropServices.SafeHandle.IsInvalid, System.Net.WebSockets.WebSocketBase.StartKeepAliveTimer(), and System.Net.WebSockets.HttpWebSocket.ThrowPlatformNotSupportedException_WSPC().
Referenced by System.Net.WebSockets.ServerWebSocket.Create().