Terraria: Terraria.WorldBuilding.Actions.TileScanner.Output
Output() [1/2]
TileScanner Terraria.WorldBuilding.Actions.TileScanner.Output (Dictionary< ushort, int > resultsOutput) inline
Definition at line 86 of file Actions.cs.
        {
            _tileCounts = resultsOutput;
            for (int i = 0; i < _tileIds.Length; i++)
            {
                if (!_tileCounts.ContainsKey(_tileIds[i]))
                {
                    _tileCounts[_tileIds[i]] = 0;
                }
            }
            return this;
        }
References Terraria.WorldBuilding.Actions.TileScanner._tileCounts, Terraria.WorldBuilding.Actions.TileScanner._tileIds, and System.Collections.Generic.Dictionary< TKey, TValue >.ContainsKey().
Referenced by Terraria.GameContent.Biomes.CaveHouse.HouseUtils.GetHouseType(), Terraria.GameContent.Biomes.EnchantedSwordBiome.Place(), Terraria.GameContent.Biomes.MahoganyTreeBiome.Place(), Terraria.GameContent.Biomes.ThinIceBiome.Place(), and Terraria.Player.PlaceThing_Tiles_PlaceIt_StaffOfRegrowthCheck().