Terraria: System.Net.WebSockets.ServerWebSocket.Create
Create()
static WebSocket System.Net.WebSockets.ServerWebSocket.Create (Stream innerStream, string subProtocol, int receiveBufferSize, TimeSpan keepAliveInterval, ArraySegment< byte > internalBuffer) inline static package
Definition at line 14 of file ServerWebSocket.cs.
    {
        if (!WebSocketProtocolComponent.IsSupported)
        {
            HttpWebSocket.ThrowPlatformNotSupportedException_WSPC();
        }
        HttpWebSocket.ValidateInnerStream(innerStream);
        HttpWebSocket.ValidateOptions(subProtocol, receiveBufferSize, 16, keepAliveInterval);
        System.Net.WebSockets.WebSocketValidate.ValidateArraySegment(internalBuffer, "internalBuffer");
        WebSocketBuffer.Validate(internalBuffer.Count, receiveBufferSize, 16, isServerBuffer: true);
        return new ServerWebSocket(innerStream, subProtocol, receiveBufferSize, keepAliveInterval, internalBuffer);
    }
References System.Net.WebSockets.ServerWebSocket.ServerWebSocket(), System.ArraySegment< T >.Count, System.Net.WebSockets.WebSocketProtocolComponent.IsSupported, System.Net.WebSockets.HttpWebSocket.ThrowPlatformNotSupportedException_WSPC(), System.Net.WebSockets.WebSocketBuffer.Validate(), System.Net.WebSockets.WebSocketValidate.ValidateArraySegment(), System.Net.WebSockets.HttpWebSocket.ValidateInnerStream(), and System.Net.WebSockets.HttpWebSocket.ValidateOptions().
Referenced by System.Net.WebSockets.HttpWebSocket.AcceptWebSocketAsyncCore().