Terraria: StrayMethods.CheckArenaScore
CheckArenaScore()
static void StrayMethods.CheckArenaScore (Vector2 arenaCenter, out Point xLeftEnd, out Point xRightEnd, int walkerWidthInTiles = 5, int walkerHeightInTiles = 10) inline static
     {
         bool flag = false;
         Point point = arenaCenter.ToTileCoordinates();
         xLeftEnd = (xRightEnd = point);
         Collision.ExpandVertically(point.X, point.Y, out var _, out var bottomY, 0, 4);
         point.Y = bottomY;
         if (flag)
         {
             Dust.QuickDust(point, Color.Blue).scale = 5f;
         }
         SendWalker(point, walkerHeightInTiles, -1, out var _, out var lastIteratedFloorSpot, 120, flag);
         SendWalker(point, walkerHeightInTiles, 1, out var _, out var lastIteratedFloorSpot2, 120, flag);
         lastIteratedFloorSpot.X++;
         lastIteratedFloorSpot2.X--;
         if (flag)
         {
             Dust.QuickDustLine(lastIteratedFloorSpot.ToWorldCoordinates(), lastIteratedFloorSpot2.ToWorldCoordinates(), 50f, Color.Pink);
         }
         xLeftEnd = lastIteratedFloorSpot;
         xRightEnd = lastIteratedFloorSpot2;
     }
References Color, Collision.ExpandVertically(), Dust.QuickDust(), Dust.QuickDustLine(), Dust.scale, and SendWalker().
Referenced by NPC.AI(), and DD2Event.WouldFailSpawningHere().