Terraria: System.Runtime.CompilerServices.ReadOnlyCollectionBuilder.Remove
Remove() [3/3]
bool System.Runtime.CompilerServices.ReadOnlyCollectionBuilder< T >.Remove (T item) inline
Implements System.Collections.Generic.ICollection< T >.
Definition at line 287 of file ReadOnlyCollectionBuilder.cs.
    {
        int num = IndexOf(item);
        if (num >= 0)
        {
            RemoveAt(num);
            return true;
        }
        return false;
    }
References System.Runtime.CompilerServices.ReadOnlyCollectionBuilder< T >.IndexOf(), System.item, and System.Runtime.CompilerServices.ReadOnlyCollectionBuilder< T >.RemoveAt().
Referenced by System.Runtime.CompilerServices.ReadOnlyCollectionBuilder< T >.Remove().