Terraria: Microsoft.Xna.Framework.Graphics.GuideRenderer.GraphicsDeviceReset
GraphicsDeviceReset()
unsafe void Microsoft.Xna.Framework.Graphics.GuideRenderer.GraphicsDeviceReset (object sender, EventArgs e) inline private
Definition at line 111 of file GuideRenderer.cs.
    {
        deviceResetCount++;
        IDirect3DDevice9* pComPtr = graphicsDevice.pComPtr;
        System.Runtime.CompilerServices.Unsafe.SkipInit(out IDirect3DStateBlock9* ptr);
        int num = ((delegate* unmanaged[Stdcall, Stdcall]<IntPtr, _D3DSTATEBLOCKTYPE, IDirect3DStateBlock9**, int>)(int)(*(uint*)(*(int*)pComPtr + 236)))((nint)pComPtr, (_D3DSTATEBLOCKTYPE)1, &ptr);
        if (num < 0)
        {
            throw GraphicsHelpers.GetExceptionFromResult((uint)num);
        }
        pStateBlock = ptr;
    }
References Microsoft.Xna.Framework.Graphics.GuideRenderer.deviceResetCount, Microsoft.Xna.Framework.Graphics.GraphicsHelpers.GetExceptionFromResult(), Microsoft.Xna.Framework.Graphics.GuideRenderer.graphicsDevice, Microsoft.Xna.Framework.Graphics.GraphicsDevice.pComPtr, and Microsoft.Xna.Framework.Graphics.GuideRenderer.pStateBlock.
Referenced by Microsoft.Xna.Framework.Graphics.GuideRenderer.GuideRenderer(), Microsoft.Xna.Framework.Graphics.GuideRenderer._007EGuideRenderer(), and Microsoft.Xna.Framework.Graphics.GuideRenderer.GraphicsDeviceCreated().