Terraria: Microsoft.Xna.Framework.Graphics.GuideRenderer.DrawGuide
DrawGuide()
unsafe void Microsoft.Xna.Framework.Graphics.GuideRenderer.DrawGuide (object sender, EventArgs e) inline private
Definition at line 134 of file GuideRenderer.cs.
    {
        if (!object.ReferenceEquals(sender, graphicsDevice))
        {
            return;
        }
        IntPtr commandData = default(IntPtr);
        PresentationParameters presentationParameters = graphicsDevice.PresentationParameters;
        if (proxySource.GetDrawingCommandsFromProxy(deviceResetCount, presentationParameters.BackBufferWidth, presentationParameters.BackBufferHeight, out commandData, out var commandDataSize))
        {
            IDirect3DStateBlock9* intPtr = pStateBlock;
            ((delegate* unmanaged[Stdcall, Stdcall]<IntPtr, int>)(int)(*(uint*)(*(int*)intPtr + 16)))((nint)intPtr);
            try
            {
                SetStandardRenderStates();
                ReplayDrawingCommands(commandData, commandDataSize);
            }
            finally
            {
                IDirect3DStateBlock9* intPtr2 = pStateBlock;
                ((delegate* unmanaged[Stdcall, Stdcall]<IntPtr, int>)(int)(*(uint*)(*(int*)intPtr2 + 20)))((nint)intPtr2);
            }
        }
    }
References Microsoft.Xna.Framework.Graphics.GuideRenderer.deviceResetCount, Microsoft.Xna.Framework.Graphics.GuideRenderer.graphicsDevice, Microsoft.Xna.Framework.Graphics.GraphicsDevice.PresentationParameters, Microsoft.Xna.Framework.Graphics.GuideRenderer.proxySource, Microsoft.Xna.Framework.Graphics.GuideRenderer.pStateBlock, Microsoft.Xna.Framework.Graphics.GuideRenderer.ReplayDrawingCommands(), and Microsoft.Xna.Framework.Graphics.GuideRenderer.SetStandardRenderStates().
Referenced by Microsoft.Xna.Framework.Graphics.GuideRenderer._007EGuideRenderer(), Microsoft.Xna.Framework.Graphics.GuideRenderer.GraphicsDeviceCreated(), and Microsoft.Xna.Framework.Graphics.GuideRenderer.GraphicsDeviceDisposing().