Terraria: Microsoft.Xna.Framework.Graphics.GuideRenderer.DestroyResources
DestroyResources()
unsafe void Microsoft.Xna.Framework.Graphics.GuideRenderer.DestroyResources () inline private
Definition at line 67 of file GuideRenderer.cs.
    {
        IDirect3DStateBlock9* ptr = pStateBlock;
        if (ptr != null)
        {
            ((delegate* unmanaged[Stdcall, Stdcall]<IntPtr, uint>)(int)(*(uint*)(*(int*)ptr + 8)))((nint)ptr);
            pStateBlock = null;
        }
        Dictionary<int, IntPtr> dictionary = resourceTable;
        if (dictionary == null)
        {
            return;
        }
        Dictionary<int, IntPtr>.ValueCollection.Enumerator enumerator = dictionary.Values.GetEnumerator();
        if (enumerator.MoveNext())
        {
            do
            {
                IUnknown* ptr2 = (IUnknown*)enumerator.Current.ToPointer();
                if (ptr2 != null)
                {
                    ((delegate* unmanaged[Stdcall, Stdcall]<IntPtr, uint>)(int)(*(uint*)(*(int*)ptr2 + 8)))((nint)ptr2);
                }
            }
            while (enumerator.MoveNext());
        }
        resourceTable.Clear();
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Clear(), System.dictionary, System.Collections.Generic.Dictionary< TKey, TValue >.ValueCollection.GetEnumerator(), System.Runtime.InteropServices.IUnknown, Microsoft.Xna.Framework.Graphics.GuideRenderer.pStateBlock, Microsoft.Xna.Framework.Graphics.GuideRenderer.resourceTable, and System.Collections.Generic.Dictionary< TKey, TValue >.Values.
Referenced by Microsoft.Xna.Framework.Graphics.GuideRenderer._0021GuideRenderer(), Microsoft.Xna.Framework.Graphics.GuideRenderer._007EGuideRenderer(), Microsoft.Xna.Framework.Graphics.GuideRenderer.GraphicsDeviceDisposing(), and Microsoft.Xna.Framework.Graphics.GuideRenderer.GraphicsDeviceResetting().