Terraria: Microsoft.Xna.Framework.Graphics.GuideRenderer.GuideRenderer
GuideRenderer()
Microsoft.Xna.Framework.Graphics.GuideRenderer.GuideRenderer (IGuideRendererProxySource proxySource) inline
Definition at line 25 of file GuideRenderer.cs.
    {
        this.proxySource = proxySource;
        resourceTable = new Dictionary<int, IntPtr>();
        deviceResetCount = -1;
        if ((graphicsDeviceService = proxySource.ServiceProvider.GetService(typeof(IGraphicsDeviceService)) as IGraphicsDeviceService) == null)
        {
            throw new InvalidOperationException(FrameworkResources.NoGraphicsDevice);
        }
        graphicsDeviceService.DeviceCreated += GraphicsDeviceCreated;
        graphicsDeviceService.DeviceResetting += GraphicsDeviceResetting;
        graphicsDeviceService.DeviceReset += GraphicsDeviceReset;
        graphicsDeviceService.DeviceDisposing += GraphicsDeviceDisposing;
        if (graphicsDeviceService.GraphicsDevice != null)
        {
            GraphicsDeviceCreated(graphicsDeviceService, EventArgs.Empty);
        }
    }
References Microsoft.Xna.Framework.Graphics.GuideRenderer.deviceResetCount, System.EventArgs.Empty, Microsoft.Xna.Framework.Graphics.IGraphicsDeviceService.GraphicsDevice, Microsoft.Xna.Framework.Graphics.GuideRenderer.GraphicsDeviceCreated(), Microsoft.Xna.Framework.Graphics.GuideRenderer.GraphicsDeviceDisposing(), Microsoft.Xna.Framework.Graphics.GuideRenderer.GraphicsDeviceReset(), Microsoft.Xna.Framework.Graphics.GuideRenderer.GraphicsDeviceResetting(), Microsoft.Xna.Framework.Graphics.GuideRenderer.graphicsDeviceService, Microsoft.Xna.Framework.FrameworkResources.NoGraphicsDevice, Microsoft.Xna.Framework.Graphics.GuideRenderer.proxySource, and Microsoft.Xna.Framework.Graphics.GuideRenderer.resourceTable.