Terraria: Microsoft.Xna.Framework.Graphics.GuideRenderer._007EGuideRenderer
_007EGuideRenderer()
void Microsoft.Xna.Framework.Graphics.GuideRenderer._007EGuideRenderer () inline private
Definition at line 44 of file GuideRenderer.cs.
    {
        if (graphicsDeviceService != null)
        {
            graphicsDeviceService.DeviceCreated -= GraphicsDeviceCreated;
            graphicsDeviceService.DeviceResetting -= GraphicsDeviceResetting;
            graphicsDeviceService.DeviceReset -= GraphicsDeviceReset;
            graphicsDeviceService.DeviceDisposing -= GraphicsDeviceDisposing;
        }
        _ = EventArgs.Empty;
        if (graphicsDevice != null)
        {
            graphicsDevice.DrawGuide -= DrawGuide;
            graphicsDevice = null;
        }
        DestroyResources();
    }
References Microsoft.Xna.Framework.Graphics.GuideRenderer.DestroyResources(), Microsoft.Xna.Framework.Graphics.GuideRenderer.DrawGuide(), System.EventArgs.Empty, Microsoft.Xna.Framework.Graphics.GuideRenderer.graphicsDevice, Microsoft.Xna.Framework.Graphics.GuideRenderer.GraphicsDeviceCreated(), Microsoft.Xna.Framework.Graphics.GuideRenderer.GraphicsDeviceDisposing(), Microsoft.Xna.Framework.Graphics.GuideRenderer.GraphicsDeviceReset(), Microsoft.Xna.Framework.Graphics.GuideRenderer.GraphicsDeviceResetting(), and Microsoft.Xna.Framework.Graphics.GuideRenderer.graphicsDeviceService.
Referenced by Microsoft.Xna.Framework.Graphics.GuideRenderer.Dispose().