Terraria: Gore.UpdateLightningBunnySparks
UpdateLightningBunnySparks()
void Gore.UpdateLightningBunnySparks () inline private
     {
         if (frameCounter == 0)
         {
             frameCounter = 1;
             Frame.CurrentRow = (byte)Main.rand.Next(3);
         }
         timeLeft -= GoreID.Sets.DisappearSpeed[type];
         if (timeLeft <= 0)
         {
             active = false;
             return;
         }
         alpha = (int)MathHelper.Lerp(255f, 0f, (float)timeLeft / 15f);
         float num = (255f - (float)alpha) / 255f;
         num *= scale;
         Lighting.AddLight(position + new Vector2(Width / 2f, Height / 2f), num * 0.4f, num, num);
         position += velocity;
     }
References active, Lighting.AddLight(), alpha, SpriteFrame.CurrentRow, GoreID.Sets.DisappearSpeed, Frame, frameCounter, Height, UnifiedRandom.Next(), position, Main.rand, scale, timeLeft, type, velocity, and Width.
Referenced by Update().