Terraria: Gore.NewGore
NewGore()
static int Gore.NewGore (Vector2 Position, Vector2 Velocity, int Type, float Scale = 1f) inline static
     {
         if (Main.netMode == 2)
         {
             return 600;
         }
         if (Main.gamePaused)
         {
             return 600;
         }
         if (WorldGen.gen)
         {
             return 600;
         }
         if (Main.rand == null)
         {
             Main.rand = new UnifiedRandom();
         }
         if (Type == -1)
         {
             return 600;
         }
         int num = 600;
         for (int i = 0; i < 600; i++)
         {
             if (!Main.gore[i].active)
             {
                 num = i;
                 break;
             }
         }
         if (num == 600)
         {
             return num;
         }
         Main.gore[num].Frame = new SpriteFrame(1, 1);
         Main.gore[num].frameCounter = 0;
         Main.gore[num].behindTiles = false;
         Main.gore[num].light = 0f;
         Main.gore[num].position = Position;
         Main.gore[num].velocity = Velocity;
         Main.gore[num].velocity.Y -= (float)Main.rand.Next(10, 31) * 0.1f;
         Main.gore[num].velocity.X += (float)Main.rand.Next(-20, 21) * 0.1f;
         Main.gore[num].type = Type;
         Main.gore[num].active = true;
         Main.gore[num].alpha = 0;
         Main.gore[num].rotation = 0f;
         Main.gore[num].scale = Scale;
         if (!ChildSafety.Disabled && ChildSafety.DangerousGore(Type))
         {
             Main.gore[num].type = Main.rand.Next(11, 14);
             Main.gore[num].scale = Main.rand.NextFloat() * 0.5f + 0.5f;
             Main.gore[num].velocity /= 2f;
         }
         if (goreTime == 0 || Type == 11 || Type == 12 || Type == 13 || Type == 16 || Type == 17 || Type == 61 || Type == 62 || Type == 63 || Type == 99 || Type == 220 || Type == 221 || Type == 222 || Type == 435 || Type == 436 || Type == 437 || (Type >= 861 && Type <= 862))
         {
             Main.gore[num].sticky = false;
         }
         else if (Type >= 375 && Type <= 377)
         {
             Main.gore[num].sticky = false;
             Main.gore[num].alpha = 100;
         }
         else
         {
             Main.gore[num].sticky = true;
             Main.gore[num].timeLeft = goreTime;
         }
         if ((Type >= 706 && Type <= 717) || Type == 943 || Type == 1147 || (Type >= 1160 && Type <= 1162))
         {
             Main.gore[num].numFrames = 15;
             Main.gore[num].behindTiles = true;
             Main.gore[num].timeLeft = goreTime * 3;
         }
         if (Type == 16 || Type == 17)
         {
             Main.gore[num].alpha = 100;
             Main.gore[num].scale = 0.7f;
             Main.gore[num].light = 1f;
         }
         if (Type >= 570 && Type <= 572)
         {
             Main.gore[num].velocity = Velocity;
         }
         if (Type == 1201 || Type == 1208)
         {
             Main.gore[num].Frame = new SpriteFrame(1, 4);
         }
         if (Type == 1217 || Type == 1218)
         {
             Main.gore[num].Frame = new SpriteFrame(1, 3);
         }
         if (Type == 1225)
         {
             Main.gore[num].Frame = new SpriteFrame(1, 3);
             Main.gore[num].timeLeft = 10 + Main.rand.Next(6);
             Main.gore[num].sticky = false;
             if (TextureAssets.Gore[Type].IsLoaded)
             {
                 Main.gore[num].position.X = Position.X - (float)(TextureAssets.Gore[Type].Width() / 2) * Scale;
                 Main.gore[num].position.Y = Position.Y - (float)TextureAssets.Gore[Type].Height() * Scale / 2f;
             }
         }
         int num2 = GoreID.Sets.SpecialAI[Type];
         if (num2 == 3)
         {
             Main.gore[num].velocity = new Vector2((Main.rand.NextFloat() - 0.5f) * 1f, Main.rand.NextFloat() * ((float)Math.PI * 2f));
             bool flag = (Type >= 910 && Type <= 925) || (Type >= 1113 && Type <= 1121) || (Type >= 1248 && Type <= 1255) || Type == 1257 || Type == 1278;
             Gore obj = Main.gore[num];
             SpriteFrame spriteFrame = new SpriteFrame((byte)((!flag) ? 1u : 32u), 8)
             {
                 CurrentRow = (byte)Main.rand.Next(8)
             };
             obj.Frame = spriteFrame;
             Main.gore[num].frameCounter = (byte)Main.rand.Next(8);
         }
         if (num2 == 1)
         {
             Main.gore[num].velocity = new Vector2((Main.rand.NextFloat() - 0.5f) * 3f, Main.rand.NextFloat() * ((float)Math.PI * 2f));
         }
         if (Type >= 411 && Type <= 430 && TextureAssets.Gore[Type].IsLoaded)
         {
             Main.gore[num].position.X = Position.X - (float)(TextureAssets.Gore[Type].Width() / 2) * Scale;
             Main.gore[num].position.Y = Position.Y - (float)TextureAssets.Gore[Type].Height() * Scale;
             Main.gore[num].velocity.Y *= (float)Main.rand.Next(90, 150) * 0.01f;
             Main.gore[num].velocity.X *= (float)Main.rand.Next(40, 90) * 0.01f;
             int num3 = Main.rand.Next(4) * 5;
             Main.gore[num].type += num3;
             Main.gore[num].timeLeft = Main.rand.Next(goreTime / 2, goreTime * 2);
             Main.gore[num].sticky = true;
             if (goreTime == 0)
             {
                 Main.gore[num].timeLeft = Main.rand.Next(150, 600);
             }
         }
         if (Type >= 907 && Type <= 909)
         {
             Main.gore[num].sticky = true;
             Main.gore[num].numFrames = 3;
             Main.gore[num].frame = (byte)Main.rand.Next(3);
             Main.gore[num].frameCounter = (byte)Main.rand.Next(5);
             Main.gore[num].rotation = 0f;
         }
         if (num2 == 2)
         {
             Main.gore[num].sticky = false;
             if (TextureAssets.Gore[Type].IsLoaded)
             {
                 Main.gore[num].alpha = 150;
                 Main.gore[num].velocity = Velocity;
                 Main.gore[num].position.X = Position.X - (float)(TextureAssets.Gore[Type].Width() / 2) * Scale;
                 Main.gore[num].position.Y = Position.Y - (float)TextureAssets.Gore[Type].Height() * Scale / 2f;
                 Main.gore[num].timeLeft = Main.rand.Next(goreTime / 2, goreTime + 1);
             }
         }
         if (num2 == 4)
         {
             Main.gore[num].alpha = 254;
             Main.gore[num].timeLeft = 300;
         }
         if (num2 == 5)
         {
             Main.gore[num].alpha = 254;
             Main.gore[num].timeLeft = 240;
         }
         if (num2 == 6)
         {
             Main.gore[num].alpha = 254;
             Main.gore[num].timeLeft = 480;
         }
         if (Main.gore[num].DeactivateIfOutsideOfWorld())
         {
             return 600;
         }
         return num;
     }
References active, alpha, behindTiles, ChildSafety.DangerousGore(), DeactivateIfOutsideOfWorld(), ChildSafety.Disabled, Frame, frame, frameCounter, Main.gamePaused, WorldGen.gen, TextureAssets.Gore, Main.gore, goreTime, Asset< T >.IsLoaded, light, Main.netMode, UnifiedRandom.Next(), numFrames, position, Main.rand, rotation, scale, GoreID.Sets.SpecialAI, sticky, timeLeft, type, and velocity.
Referenced by NPC.AI(), Projectile.AI(), Projectile.AI_026(), NPC.AI_045_Golem(), Projectile.AI_067_FreakingPirates(), NPC.AI_107_ImprovedWalkers(), NPC.AI_108_DivingFlyer(), NPC.AI_121_QueenSlime(), Projectile.AI_147_Explosion(), Projectile.AI_151_SuperStar(), Projectile.AI_178_FireExplosion(), NPC.BigMimicSpawnSmoke(), PlayerDrawSet.BoringSetup(), WorldGen.Check3x3(), WorldGen.CheckPot(), Player.DashMovement(), Item.DespawnIfMeetingConditions(), Mount.DoSpawnDust(), Player.DoubleJumpVisuals(), TileDrawing.DrawTiles_EmitParticles(), Projectile.EmitEnchantmentVisualsAt(), TileDrawing.EmitLiquidDrops(), NPC.FindFrame(), NPC.HitEffect(), Player.ItemCheck_ApplyUseStyle(), Player.ItemCheck_EmitUseVisuals(), Player.ItemCheck_GetMeleeHitbox(), Player.JumpMovement(), Projectile.Kill(), Player.KillMe(), NewGoreDirect(), Player.NinjaDodge(), Utils.PoofOfSmoke(), ParticleOrchestrator.Spawn_Digestion(), DelegateMethods.Minecart.SpawnFartCloud(), NPC.StrikeNPC(), NPC.TransformVisuals(), WorldGen.TreeGrowFX(), Update(), Player.UpdateHairDyeDust(), and NPC.UpdateNPC_BuffApplyVFX().