Terraria: System.Runtime.Serialization.XmlObjectSerializerWriteContext.WriteExtensionData
WriteExtensionData()
void System.Runtime.Serialization.XmlObjectSerializerWriteContext.WriteExtensionData (XmlWriterDelegator xmlWriter, ExtensionDataObject extensionData, int memberIndex) inline inherited
Definition at line 639 of file XmlObjectSerializerWriteContext.cs.
    {
        if (base.IgnoreExtensionDataObject || extensionData == null)
        {
            return;
        }
        IList<ExtensionDataMember> members = extensionData.Members;
        if (members == null)
        {
            return;
        }
        for (int i = 0; i < members.Count; i++)
        {
            ExtensionDataMember extensionDataMember = members[i];
            if (extensionDataMember.MemberIndex == memberIndex)
            {
                WriteExtensionDataMember(xmlWriter, extensionDataMember);
            }
        }
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Count, and System.Runtime.Serialization.XmlObjectSerializerWriteContext.WriteExtensionDataMember().
Referenced by System.Runtime.Serialization.ReflectionClassWriter.ReflectionWriteClass(), System.Runtime.Serialization.ReflectionXmlClassWriter.ReflectionWriteMembers(), and System.Runtime.Serialization.Json.ReflectionJsonClassWriter.ReflectionWriteMembers().