Terraria: System.Runtime.Serialization.XmlObjectSerializerWriteContext.WriteExtensionClassData
WriteExtensionClassData()
void System.Runtime.Serialization.XmlObjectSerializerWriteContext.WriteExtensionClassData (XmlWriterDelegator xmlWriter, ClassDataNode dataNode) inline private inherited
Definition at line 747 of file XmlObjectSerializerWriteContext.cs.
    {
        if (TryWriteDeserializedExtensionData(xmlWriter, dataNode))
        {
            return;
        }
        WriteExtensionDataTypeInfo(xmlWriter, dataNode);
        IList<ExtensionDataMember> members = dataNode.Members;
        if (members != null)
        {
            for (int i = 0; i < members.Count; i++)
            {
                WriteExtensionDataMember(xmlWriter, members[i]);
            }
        }
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Runtime.Serialization.ClassDataNode.Members, System.Runtime.Serialization.XmlObjectSerializerWriteContext.TryWriteDeserializedExtensionData(), System.Runtime.Serialization.XmlObjectSerializerWriteContext.WriteExtensionDataMember(), and System.Runtime.Serialization.XmlObjectSerializerWriteContext.WriteExtensionDataTypeInfo().
Referenced by System.Runtime.Serialization.XmlObjectSerializerWriteContext.WriteExtensionDataValue().