Terraria: System.Runtime.Serialization.XmlObjectSerializerWriteContext.WriteExtensionDataValue
WriteExtensionDataValue()
void System.Runtime.Serialization.XmlObjectSerializerWriteContext.WriteExtensionDataValue (XmlWriterDelegator xmlWriter, IDataNode dataNode) inline package inherited
Definition at line 680 of file XmlObjectSerializerWriteContext.cs.
    {
        IncrementItemCount(1);
        if (dataNode == null)
        {
            WriteNull(xmlWriter);
        }
        else
        {
            if (dataNode.PreservesReferences && OnHandleReference(xmlWriter, (dataNode.Value == null) ? dataNode : dataNode.Value, canContainCyclicReference: true))
            {
                return;
            }
            Type dataType = dataNode.DataType;
            if (dataType == Globals.TypeOfClassDataNode)
            {
                WriteExtensionClassData(xmlWriter, (ClassDataNode)dataNode);
            }
            else if (dataType == Globals.TypeOfCollectionDataNode)
            {
                WriteExtensionCollectionData(xmlWriter, (CollectionDataNode)dataNode);
            }
            else if (dataType == Globals.TypeOfXmlDataNode)
            {
                WriteExtensionXmlData(xmlWriter, (XmlDataNode)dataNode);
            }
            else if (dataType == Globals.TypeOfISerializableDataNode)
            {
                WriteExtensionISerializableData(xmlWriter, (ISerializableDataNode)dataNode);
            }
            else
            {
                WriteExtensionDataTypeInfo(xmlWriter, dataNode);
                if (dataType == Globals.TypeOfObject)
                {
                    object value = dataNode.Value;
                    if (value != null)
                    {
                        InternalSerialize(xmlWriter, value, isDeclaredType: false, writeXsiType: false, -1, value.GetType().TypeHandle);
                    }
                }
                else
                {
                    xmlWriter.WriteExtensionData(dataNode);
                }
            }
            if (dataNode.PreservesReferences)
            {
                OnEndHandleReference(xmlWriter, (dataNode.Value == null) ? dataNode : dataNode.Value, canContainCyclicReference: true);
            }
        }
    }
References System.Runtime.Serialization.IDataNode.DataType, System.Runtime.Serialization.Dictionary, System.Runtime.Serialization.XmlObjectSerializerContext.IncrementItemCount(), System.Runtime.Serialization.XmlObjectSerializerWriteContext.InternalSerialize(), System.Runtime.Serialization.XmlObjectSerializerWriteContext.OnEndHandleReference(), System.Runtime.Serialization.XmlObjectSerializerWriteContext.OnHandleReference(), System.Runtime.Serialization.IDataNode.PreservesReferences, System.Runtime.Serialization.Globals.TypeOfClassDataNode, System.Runtime.Serialization.Globals.TypeOfCollectionDataNode, System.Runtime.Serialization.Globals.TypeOfISerializableDataNode, System.Runtime.Serialization.Globals.TypeOfObject, System.Runtime.Serialization.Globals.TypeOfXmlDataNode, System.value, System.Runtime.Serialization.IDataNode.Value, System.Runtime.Serialization.XmlObjectSerializerWriteContext.WriteExtensionClassData(), System.Runtime.Serialization.XmlObjectSerializerWriteContext.WriteExtensionCollectionData(), System.Runtime.Serialization.XmlObjectSerializerWriteContext.WriteExtensionDataTypeInfo(), System.Runtime.Serialization.XmlObjectSerializerWriteContext.WriteExtensionISerializableData(), System.Runtime.Serialization.XmlObjectSerializerWriteContext.WriteExtensionXmlData(), and System.Runtime.Serialization.XmlObjectSerializerWriteContext.WriteNull().
Referenced by System.Runtime.Serialization.XmlObjectSerializerWriteContext.WriteExtensionCollectionData(), System.Runtime.Serialization.XmlObjectSerializerWriteContext.WriteExtensionDataMember(), and System.Runtime.Serialization.XmlObjectSerializerWriteContext.WriteExtensionISerializableData().