Terraria: System.Runtime.Serialization.XmlObjectSerializerWriteContext.WriteNull
WriteNull() [2/3]
void System.Runtime.Serialization.XmlObjectSerializerWriteContext.WriteNull (XmlWriterDelegator xmlWriter, Type memberType, bool isMemberTypeSerializable) inline package inherited
Definition at line 404 of file XmlObjectSerializerWriteContext.cs.
    {
        CheckIfTypeSerializable(memberType, isMemberTypeSerializable);
        WriteNull(xmlWriter);
    }
References System.Runtime.Serialization.XmlObjectSerializerContext.CheckIfTypeSerializable(), and System.Runtime.Serialization.XmlObjectSerializerWriteContext.WriteNull().
Referenced by System.Runtime.Serialization.ReflectionClassWriter.ReflectionWriteValue(), System.Runtime.Serialization.XmlObjectSerializerWriteContext.WriteBase64(), System.Runtime.Serialization.XmlObjectSerializerWriteContextComplex.WriteBase64(), System.Runtime.Serialization.XmlObjectSerializerWriteContext.WriteExtensionDataValue(), System.Runtime.Serialization.XmlObjectSerializerWriteContext.WriteNull(), System.Runtime.Serialization.XmlObjectSerializerWriteContext.WriteNull(), System.Runtime.Serialization.XmlObjectSerializerWriteContext.WriteQName(), System.Runtime.Serialization.XmlObjectSerializerWriteContextComplex.WriteQName(), System.Runtime.Serialization.XmlObjectSerializerWriteContext.WriteSerializationInfo(), System.Runtime.Serialization.XmlObjectSerializerWriteContext.WriteString(), System.Runtime.Serialization.XmlObjectSerializerWriteContextComplex.WriteString(), System.Runtime.Serialization.XmlObjectSerializerWriteContext.WriteUri(), and System.Runtime.Serialization.XmlObjectSerializerWriteContextComplex.WriteUri().