Terraria: System.Runtime.Serialization.XmlObjectSerializerWriteContext.TryWriteDeserializedExtensionData
TryWriteDeserializedExtensionData()
bool System.Runtime.Serialization.XmlObjectSerializerWriteContext.TryWriteDeserializedExtensionData (XmlWriterDelegator xmlWriter, IDataNode dataNode) inline package inherited
Definition at line 734 of file XmlObjectSerializerWriteContext.cs.
    {
        object value = dataNode.Value;
        if (value == null)
        {
            return false;
        }
        Type type = ((dataNode.DataContractName == null) ? value.GetType() : Globals.TypeOfObject);
        InternalSerialize(xmlWriter, value, isDeclaredType: false, writeXsiType: false, -1, type.TypeHandle);
        return true;
    }
References System.Runtime.Serialization.Dictionary, System.Runtime.Serialization.XmlObjectSerializerWriteContext.InternalSerialize(), System.type, System.Runtime.Serialization.Globals.TypeOfObject, System.value, and System.Runtime.Serialization.IDataNode.Value.
Referenced by System.Runtime.Serialization.XmlObjectSerializerWriteContext.WriteExtensionClassData(), System.Runtime.Serialization.XmlObjectSerializerWriteContext.WriteExtensionCollectionData(), System.Runtime.Serialization.XmlObjectSerializerWriteContext.WriteExtensionISerializableData(), and System.Runtime.Serialization.XmlObjectSerializerWriteContext.WriteExtensionXmlData().