Terraria: System.Runtime.Serialization.XmlObjectSerializerWriteContext.WriteExtensionCollectionData
WriteExtensionCollectionData()
void System.Runtime.Serialization.XmlObjectSerializerWriteContext.WriteExtensionCollectionData (XmlWriterDelegator xmlWriter, CollectionDataNode dataNode) inline private inherited
Definition at line 765 of file XmlObjectSerializerWriteContext.cs.
    {
        if (TryWriteDeserializedExtensionData(xmlWriter, dataNode))
        {
            return;
        }
        WriteExtensionDataTypeInfo(xmlWriter, dataNode);
        WriteArraySize(xmlWriter, dataNode.Size);
        IList<IDataNode> items = dataNode.Items;
        if (items != null)
        {
            for (int i = 0; i < items.Count; i++)
            {
                xmlWriter.WriteStartElement(dataNode.ItemName, dataNode.ItemNamespace);
                WriteExtensionDataValue(xmlWriter, items[i]);
                xmlWriter.WriteEndElement();
            }
        }
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Runtime.Serialization.CollectionDataNode.ItemName, System.Runtime.Serialization.CollectionDataNode.ItemNamespace, System.Runtime.Serialization.CollectionDataNode.Items, System.Runtime.Serialization.CollectionDataNode.Size, System.Runtime.Serialization.XmlObjectSerializerWriteContext.TryWriteDeserializedExtensionData(), System.Runtime.Serialization.XmlObjectSerializerWriteContext.WriteArraySize(), System.Runtime.Serialization.XmlObjectSerializerWriteContext.WriteExtensionDataTypeInfo(), and System.Runtime.Serialization.XmlObjectSerializerWriteContext.WriteExtensionDataValue().
Referenced by System.Runtime.Serialization.XmlObjectSerializerWriteContext.WriteExtensionDataValue().