Terraria: System.Runtime.Serialization.XmlObjectSerializerWriteContext.WriteSerializationInfo
WriteSerializationInfo()
void System.Runtime.Serialization.XmlObjectSerializerWriteContext.WriteSerializationInfo (XmlWriterDelegator xmlWriter, Type objType, SerializationInfo serInfo) inline package inherited
Definition at line 532 of file XmlObjectSerializerWriteContext.cs.
    {
        if (DataContract.GetClrTypeFullName(objType) != serInfo.FullTypeName)
        {
            if (base.DataContractResolver != null)
            {
                if (ResolveType(serInfo.ObjectType, objType, out var typeName, out var typeNamespace))
                {
                    xmlWriter.WriteAttributeQualifiedName("z", DictionaryGlobals.ISerializableFactoryTypeLocalName, DictionaryGlobals.SerializationNamespace, typeName, typeNamespace);
                }
            }
            else
            {
                DataContract.GetDefaultStableName(serInfo.FullTypeName, out var localName, out var ns);
                xmlWriter.WriteAttributeQualifiedName("z", DictionaryGlobals.ISerializableFactoryTypeLocalName, DictionaryGlobals.SerializationNamespace, DataContract.GetClrTypeString(localName), DataContract.GetClrTypeString(ns));
            }
        }
        WriteClrTypeInfo(xmlWriter, objType, serInfo);
        IncrementItemCount(serInfo.MemberCount);
        SerializationInfoEnumerator enumerator = serInfo.GetEnumerator();
        while (enumerator.MoveNext())
        {
            SerializationEntry current = enumerator.Current;
            XmlDictionaryString clrTypeString = DataContract.GetClrTypeString(DataContract.EncodeLocalName(current.Name));
            xmlWriter.WriteStartElement(clrTypeString, DictionaryGlobals.EmptyString);
            object value = current.Value;
            if (value == null)
            {
                WriteNull(xmlWriter);
            }
            else
            {
                InternalSerializeReference(xmlWriter, value, isDeclaredType: false, writeXsiType: false, -1, Globals.TypeOfObject.TypeHandle);
            }
            xmlWriter.WriteEndElement();
        }
    }
References System.Runtime.Serialization.Dictionary, System.Runtime.Serialization.DictionaryGlobals.EmptyString, System.Runtime.Serialization.DataContract.EncodeLocalName(), System.Runtime.Serialization.DataContract.GetClrTypeFullName(), System.Runtime.Serialization.DataContract.GetClrTypeString(), System.Runtime.Serialization.DataContract.GetDefaultStableName(), System.Collections.Generic.Dictionary< TKey, TValue >.GetEnumerator(), System.Runtime.Serialization.XmlObjectSerializerContext.IncrementItemCount(), System.Runtime.Serialization.XmlObjectSerializerWriteContext.InternalSerializeReference(), System.Runtime.Serialization.DictionaryGlobals.ISerializableFactoryTypeLocalName, System.Runtime.Serialization.SerializationEntry.Name, System.Runtime.Serialization.XmlObjectSerializerWriteContext.ResolveType(), System.Runtime.Serialization.DictionaryGlobals.SerializationNamespace, System.Runtime.Serialization.Globals.TypeOfObject, System.Runtime.Serialization.SerializationEntry.Value, System.value, System.Runtime.Serialization.XmlObjectSerializerWriteContext.WriteClrTypeInfo(), and System.Runtime.Serialization.XmlObjectSerializerWriteContext.WriteNull().
Referenced by System.Runtime.Serialization.XmlObjectSerializerWriteContext.WriteISerializable(), System.Runtime.Serialization.Json.XmlObjectSerializerWriteContextComplexJson.WriteJsonISerializable(), and System.Runtime.Serialization.SurrogateDataContract.WriteXmlValue().