Terraria: System.Runtime.Serialization.XmlObjectSerializerWriteContext.WriteISerializable
WriteISerializable()
void System.Runtime.Serialization.XmlObjectSerializerWriteContext.WriteISerializable (XmlWriterDelegator xmlWriter, ISerializable obj) inline inherited
Definition at line 519 of file XmlObjectSerializerWriteContext.cs.
    {
        Type type = obj.GetType();
        SerializationInfo serializationInfo = new SerializationInfo(type, XmlObjectSerializer.FormatterConverter);
        GetObjectData(obj, serializationInfo, GetStreamingContext());
        if (!UnsafeTypeForwardingEnabled && serializationInfo.AssemblyName == "0")
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(XmlObjectSerializer.CreateSerializationException(System.SR.Format(System.SR.ISerializableAssemblyNameSetToZero, DataContract.GetClrTypeFullName(obj.GetType()))));
        }
        WriteSerializationInfo(xmlWriter, type, serializationInfo);
    }
References System.Runtime.Serialization.XmlObjectSerializer.CreateSerializationException(), System.SR.Format(), System.Runtime.Serialization.XmlObjectSerializer.FormatterConverter, System.Runtime.Serialization.DataContract.GetClrTypeFullName(), System.Runtime.Serialization.XmlObjectSerializerWriteContext.GetObjectData(), System.Runtime.Serialization.XmlObjectSerializerContext.GetStreamingContext(), System.Type.GetType(), System.SR.ISerializableAssemblyNameSetToZero, System.obj, System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperError(), System.type, System.Runtime.Serialization.XmlObjectSerializerWriteContext.UnsafeTypeForwardingEnabled, and System.Runtime.Serialization.XmlObjectSerializerWriteContext.WriteSerializationInfo().
Referenced by System.Runtime.Serialization.ReflectionClassWriter.ReflectionWriteClass().