Terraria: System.Runtime.Serialization.XmlObjectSerializerWriteContext.OnHandleIsReference
OnHandleIsReference()
bool System.Runtime.Serialization.XmlObjectSerializerWriteContext.OnHandleIsReference (XmlWriterDelegator xmlWriter, DataContract contract, object obj) inline package inherited
Definition at line 207 of file XmlObjectSerializerWriteContext.cs.
    {
        if (preserveObjectReferences || !contract.IsReference || _isGetOnlyCollection)
        {
            return false;
        }
        bool newId = true;
        int id = SerializedObjects.GetId(obj, ref newId);
        _byValObjectsInScope.EnsureSetAsIsReference(obj);
        IFormatProvider invariantCulture;
        if (newId)
        {
            XmlDictionaryString idLocalName = DictionaryGlobals.IdLocalName;
            XmlDictionaryString serializationNamespace = DictionaryGlobals.SerializationNamespace;
            invariantCulture = CultureInfo.InvariantCulture;
            IFormatProvider provider = invariantCulture;
            DefaultInterpolatedStringHandler handler = new DefaultInterpolatedStringHandler(1, 1, invariantCulture);
            handler.AppendLiteral("i");
            handler.AppendFormatted(id);
            xmlWriter.WriteAttributeString("z", idLocalName, serializationNamespace, string.Create(provider, ref handler));
            return false;
        }
        XmlDictionaryString refLocalName = DictionaryGlobals.RefLocalName;
        XmlDictionaryString serializationNamespace2 = DictionaryGlobals.SerializationNamespace;
        invariantCulture = CultureInfo.InvariantCulture;
        IFormatProvider provider2 = invariantCulture;
        DefaultInterpolatedStringHandler handler2 = new DefaultInterpolatedStringHandler(1, 1, invariantCulture);
        handler2.AppendLiteral("i");
        handler2.AppendFormatted(id);
        xmlWriter.WriteAttributeString("z", refLocalName, serializationNamespace2, string.Create(provider2, ref handler2));
        return true;
    }
References System.Runtime.Serialization.XmlObjectSerializerWriteContext._byValObjectsInScope, System.Runtime.Serialization.XmlObjectSerializerWriteContext._isGetOnlyCollection, System.Runtime.CompilerServices.DefaultInterpolatedStringHandler.AppendFormatted(), System.Runtime.CompilerServices.DefaultInterpolatedStringHandler.AppendLiteral(), System.Runtime.Serialization.Dictionary, System.Runtime.Serialization.ObjectReferenceStack.EnsureSetAsIsReference(), System.Runtime.Serialization.ObjectToIdCache.GetId(), System.Runtime.Serialization.DictionaryGlobals.IdLocalName, System.Globalization.CultureInfo.InvariantCulture, System.obj, System.Runtime.Serialization.XmlObjectSerializerWriteContext.preserveObjectReferences, System.Runtime.Serialization.DictionaryGlobals.RefLocalName, System.Runtime.Serialization.DictionaryGlobals.SerializationNamespace, and System.Runtime.Serialization.XmlObjectSerializerWriteContext.SerializedObjects.
Referenced by System.Runtime.Serialization.XmlObjectSerializerWriteContext.SerializeWithoutXsiType(), and System.Runtime.Serialization.XmlObjectSerializerWriteContext.SerializeWithXsiType().