Terraria: System.Runtime.Serialization.XmlObjectSerializerWriteContext.WriteExtensionISerializableData
WriteExtensionISerializableData()
void System.Runtime.Serialization.XmlObjectSerializerWriteContext.WriteExtensionISerializableData (XmlWriterDelegator xmlWriter, ISerializableDataNode dataNode) inline private inherited
Definition at line 786 of file XmlObjectSerializerWriteContext.cs.
    {
        if (TryWriteDeserializedExtensionData(xmlWriter, dataNode))
        {
            return;
        }
        WriteExtensionDataTypeInfo(xmlWriter, dataNode);
        if (dataNode.FactoryTypeName != null)
        {
            xmlWriter.WriteAttributeQualifiedName("z", DictionaryGlobals.ISerializableFactoryTypeLocalName, DictionaryGlobals.SerializationNamespace, dataNode.FactoryTypeName, dataNode.FactoryTypeNamespace);
        }
        IList<ISerializableDataMember> members = dataNode.Members;
        if (members != null)
        {
            for (int i = 0; i < members.Count; i++)
            {
                ISerializableDataMember serializableDataMember = members[i];
                xmlWriter.WriteStartElement(serializableDataMember.Name, string.Empty);
                WriteExtensionDataValue(xmlWriter, serializableDataMember.Value);
                xmlWriter.WriteEndElement();
            }
        }
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Runtime.Serialization.ISerializableDataNode.FactoryTypeName, System.Runtime.Serialization.ISerializableDataNode.FactoryTypeNamespace, System.Runtime.Serialization.DictionaryGlobals.ISerializableFactoryTypeLocalName, System.Runtime.Serialization.ISerializableDataNode.Members, System.Runtime.Serialization.DictionaryGlobals.SerializationNamespace, System.Runtime.Serialization.XmlObjectSerializerWriteContext.TryWriteDeserializedExtensionData(), System.Runtime.Serialization.XmlObjectSerializerWriteContext.WriteExtensionDataTypeInfo(), and System.Runtime.Serialization.XmlObjectSerializerWriteContext.WriteExtensionDataValue().
Referenced by System.Runtime.Serialization.XmlObjectSerializerWriteContext.WriteExtensionDataValue().