Terraria: System.Runtime.Serialization.XmlObjectSerializerWriteContext.ThrowRequiredMemberMustBeEmitted
ThrowRequiredMemberMustBeEmitted()
static void System.Runtime.Serialization.XmlObjectSerializerWriteContext.ThrowRequiredMemberMustBeEmitted (string memberName, Type type) inline static package inherited
Definition at line 462 of file XmlObjectSerializerWriteContext.cs.
    {
        throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new SerializationException(System.SR.Format(System.SR.RequiredMemberMustBeEmitted, memberName, type.FullName)));
    }
References System.SR.Format(), System.SR.RequiredMemberMustBeEmitted, System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperError(), and System.type.
Referenced by System.Runtime.Serialization.ReflectionXmlClassWriter.ReflectionWriteMembers(), and System.Runtime.Serialization.Json.ReflectionJsonClassWriter.ReflectionWriteMembers().