Terraria: System.Runtime.Serialization.XmlObjectSerializerWriteContext.WriteExtensionDataMember
WriteExtensionDataMember()
void System.Runtime.Serialization.XmlObjectSerializerWriteContext.WriteExtensionDataMember (XmlWriterDelegator xmlWriter, ExtensionDataMember member) inline private inherited
Definition at line 661 of file XmlObjectSerializerWriteContext.cs.
    {
        xmlWriter.WriteStartElement(member.Name, member.Namespace);
        IDataNode value = member.Value;
        WriteExtensionDataValue(xmlWriter, value);
        xmlWriter.WriteEndElement();
    }
References System.Runtime.Serialization.ExtensionDataMember.Name, System.Runtime.Serialization.ExtensionDataMember.Namespace, System.value, System.Runtime.Serialization.ExtensionDataMember.Value, and System.Runtime.Serialization.XmlObjectSerializerWriteContext.WriteExtensionDataValue().
Referenced by System.Runtime.Serialization.XmlObjectSerializerWriteContext.WriteExtensionClassData(), and System.Runtime.Serialization.XmlObjectSerializerWriteContext.WriteExtensionData().