Terraria: System.Runtime.Serialization.XmlObjectSerializerWriteContext.InternalSerialize
InternalSerialize()
virtual void System.Runtime.Serialization.XmlObjectSerializerWriteContext.InternalSerialize (XmlWriterDelegator xmlWriter, object obj, bool isDeclaredType, bool writeXsiType, int declaredTypeID, RuntimeTypeHandle declaredTypeHandle) inline package virtual
Reimplemented in System.Runtime.Serialization.XmlObjectSerializerWriteContextComplex.
Definition at line 100 of file XmlObjectSerializerWriteContext.cs.
    {
        if (writeXsiType)
        {
            Type typeOfObject = Globals.TypeOfObject;
            SerializeWithXsiType(xmlWriter, obj, obj.GetType().TypeHandle, null, -1, typeOfObject.TypeHandle, typeOfObject);
            return;
        }
        if (isDeclaredType)
        {
            DataContract dataContract = GetDataContract(declaredTypeID, declaredTypeHandle);
            SerializeWithoutXsiType(dataContract, xmlWriter, obj, declaredTypeHandle);
            return;
        }
        RuntimeTypeHandle typeHandle = obj.GetType().TypeHandle;
        if (declaredTypeHandle.GetHashCode() == typeHandle.GetHashCode())
        {
            DataContract dataContract2 = ((declaredTypeID >= 0) ? GetDataContract(declaredTypeID, declaredTypeHandle) : GetDataContract(declaredTypeHandle, null));
            SerializeWithoutXsiType(dataContract2, xmlWriter, obj, declaredTypeHandle);
        }
        else
        {
            SerializeWithXsiType(xmlWriter, obj, typeHandle, null, declaredTypeID, declaredTypeHandle, Type.GetTypeFromHandle(declaredTypeHandle));
        }
    }
References System.Runtime.Serialization.XmlObjectSerializerContext.GetDataContract(), System.Type.GetTypeFromHandle(), System.obj, System.Runtime.Serialization.XmlObjectSerializerWriteContext.SerializeWithoutXsiType(), System.Runtime.Serialization.XmlObjectSerializerWriteContext.SerializeWithXsiType(), and System.Runtime.Serialization.Globals.TypeOfObject.
Referenced by System.Runtime.Serialization.XmlObjectSerializerWriteContext.InternalSerializeReference(), System.Runtime.Serialization.ReflectionClassWriter.ReflectionInternalSerialize(), System.Runtime.Serialization.XmlObjectSerializerWriteContext.TryWriteDeserializedExtensionData(), and System.Runtime.Serialization.XmlObjectSerializerWriteContext.WriteExtensionDataValue().