Terraria: System.Runtime.Serialization.XmlObjectSerializerWriteContext.ResolveType
ResolveType()
bool System.Runtime.Serialization.XmlObjectSerializerWriteContext.ResolveType (Type objectType, Type declaredType, [NotNullWhen(true)] out XmlDictionaryString typeName, [NotNullWhen(true)] out XmlDictionaryString typeNamespace) inline private inherited
Definition at line 591 of file XmlObjectSerializerWriteContext.cs.
    {
        if (!base.DataContractResolver.TryResolveType(objectType, declaredType, base.KnownTypeResolver, out typeName, out typeNamespace))
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(XmlObjectSerializer.CreateSerializationException(System.SR.Format(System.SR.ResolveTypeReturnedFalse, DataContract.GetClrTypeFullName(base.DataContractResolver.GetType()), DataContract.GetClrTypeFullName(objectType))));
        }
        if (typeName == null)
        {
            if (typeNamespace == null)
            {
                return false;
            }
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(XmlObjectSerializer.CreateSerializationException(System.SR.Format(System.SR.ResolveTypeReturnedNull, DataContract.GetClrTypeFullName(base.DataContractResolver.GetType()), DataContract.GetClrTypeFullName(objectType))));
        }
        if (typeNamespace == null)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(XmlObjectSerializer.CreateSerializationException(System.SR.Format(System.SR.ResolveTypeReturnedNull, DataContract.GetClrTypeFullName(base.DataContractResolver.GetType()), DataContract.GetClrTypeFullName(objectType))));
        }
        return true;
    }
References System.Runtime.Serialization.XmlObjectSerializer.CreateSerializationException(), System.SR.Format(), System.Runtime.Serialization.DataContract.GetClrTypeFullName(), System.SR.ResolveTypeReturnedFalse, System.SR.ResolveTypeReturnedNull, and System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperError().
Referenced by System.Runtime.Serialization.XmlObjectSerializerWriteContext.WriteResolvedTypeInfo(), and System.Runtime.Serialization.XmlObjectSerializerWriteContext.WriteSerializationInfo().