Terraria: System.Runtime.Serialization.XmlObjectSerializerWriteContext.OnHandleReference
OnHandleReference()
virtual bool System.Runtime.Serialization.XmlObjectSerializerWriteContext.OnHandleReference (XmlWriterDelegator xmlWriter, object obj, bool canContainCyclicReference) inline package virtual
Reimplemented in System.Runtime.Serialization.XmlObjectSerializerWriteContextComplex.
Definition at line 378 of file XmlObjectSerializerWriteContext.cs.
    {
        if (xmlWriter.depth < 512)
        {
            return false;
        }
        if (canContainCyclicReference)
        {
            if (_byValObjectsInScope.Contains(obj))
            {
                throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(XmlObjectSerializer.CreateSerializationException(System.SR.Format(System.SR.CannotSerializeObjectWithCycles, DataContract.GetClrTypeFullName(obj.GetType()))));
            }
            _byValObjectsInScope.Push(obj);
        }
        return false;
    }
References System.Runtime.Serialization.XmlObjectSerializerWriteContext._byValObjectsInScope, System.SR.CannotSerializeObjectWithCycles, System.Runtime.Serialization.ObjectReferenceStack.Contains(), System.Runtime.Serialization.XmlObjectSerializer.CreateSerializationException(), System.SR.Format(), System.Runtime.Serialization.DataContract.GetClrTypeFullName(), System.obj, System.Runtime.Serialization.ObjectReferenceStack.Push(), and System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperError().
Referenced by System.Runtime.Serialization.XmlObjectSerializerWriteContext.HandleGraphAtTopLevel(), System.Runtime.Serialization.XmlObjectSerializerWriteContext.InternalSerializeReference(), and System.Runtime.Serialization.XmlObjectSerializerWriteContext.WriteExtensionDataValue().