Terraria: System.Runtime.Serialization.XmlObjectSerializerWriteContext.WriteExtensionDataTypeInfo
WriteExtensionDataTypeInfo()
virtual void System.Runtime.Serialization.XmlObjectSerializerWriteContext.WriteExtensionDataTypeInfo (XmlWriterDelegator xmlWriter, IDataNode dataNode) inline package virtual inherited
Reimplemented in System.Runtime.Serialization.Json.XmlObjectSerializerWriteContextComplexJson.
Definition at line 670 of file XmlObjectSerializerWriteContext.cs.
    {
        if (dataNode.DataContractName != null)
        {
            WriteTypeInfo(xmlWriter, dataNode.DataContractName, dataNode.DataContractNamespace);
        }
        WriteClrTypeInfo(xmlWriter, dataNode.DataType, dataNode.ClrTypeName, dataNode.ClrAssemblyName);
    }
References System.Runtime.Serialization.IDataNode.ClrAssemblyName, System.Runtime.Serialization.IDataNode.ClrTypeName, System.Runtime.Serialization.IDataNode.DataContractName, System.Runtime.Serialization.IDataNode.DataContractNamespace, System.Runtime.Serialization.IDataNode.DataType, System.Runtime.Serialization.XmlObjectSerializerWriteContext.WriteClrTypeInfo(), and System.Runtime.Serialization.XmlObjectSerializerWriteContext.WriteTypeInfo().
Referenced by System.Runtime.Serialization.XmlObjectSerializerWriteContext.WriteExtensionClassData(), System.Runtime.Serialization.XmlObjectSerializerWriteContext.WriteExtensionCollectionData(), System.Runtime.Serialization.XmlObjectSerializerWriteContext.WriteExtensionDataValue(), System.Runtime.Serialization.XmlObjectSerializerWriteContext.WriteExtensionISerializableData(), and System.Runtime.Serialization.XmlObjectSerializerWriteContext.WriteExtensionXmlData().