Terraria: System.Runtime.Serialization.XmlObjectSerializerWriteContext.SerializeWithXsiTypeAtTopLevel
SerializeWithXsiTypeAtTopLevel()
virtual void System.Runtime.Serialization.XmlObjectSerializerWriteContext.SerializeWithXsiTypeAtTopLevel (DataContract dataContract, XmlWriterDelegator xmlWriter, object obj, RuntimeTypeHandle originalDeclaredTypeHandle, Type graphType) inline package virtual inherited
Reimplemented in System.Runtime.Serialization.Json.XmlObjectSerializerWriteContextComplexJson.
Definition at line 145 of file XmlObjectSerializerWriteContext.cs.
    {
        bool verifyKnownType = false;
        Type underlyingType = rootTypeDataContract.UnderlyingType;
        if (underlyingType.IsInterface && CollectionDataContract.IsCollectionInterface(underlyingType))
        {
            if (base.DataContractResolver != null)
            {
                WriteResolvedTypeInfo(xmlWriter, graphType, underlyingType);
            }
        }
        else if (!underlyingType.IsArray)
        {
            verifyKnownType = WriteTypeInfo(xmlWriter, dataContract, rootTypeDataContract);
        }
        SerializeAndVerifyType(dataContract, xmlWriter, obj, verifyKnownType, originalDeclaredTypeHandle, underlyingType);
    }
References System.Runtime.Serialization.CollectionDataContract.IsCollectionInterface(), System.obj, System.Runtime.Serialization.XmlObjectSerializerContext.rootTypeDataContract, System.Runtime.Serialization.XmlObjectSerializerWriteContext.SerializeAndVerifyType(), System.Runtime.Serialization.DataContract.UnderlyingType, System.Runtime.Serialization.XmlObjectSerializerWriteContext.WriteResolvedTypeInfo(), and System.Runtime.Serialization.XmlObjectSerializerWriteContext.WriteTypeInfo().