Terraria: System.Runtime.Serialization.XmlObjectSerializerWriteContext.WriteExtensionXmlData
WriteExtensionXmlData()
void System.Runtime.Serialization.XmlObjectSerializerWriteContext.WriteExtensionXmlData (XmlWriterDelegator xmlWriter, XmlDataNode dataNode) inline private inherited
Definition at line 811 of file XmlObjectSerializerWriteContext.cs.
    {
        if (TryWriteDeserializedExtensionData(xmlWriter, dataNode))
        {
            return;
        }
        IList<XmlAttribute> xmlAttributes = dataNode.XmlAttributes;
        if (xmlAttributes != null)
        {
            foreach (XmlAttribute item in xmlAttributes)
            {
                item.WriteTo(xmlWriter.Writer);
            }
        }
        WriteExtensionDataTypeInfo(xmlWriter, dataNode);
        IList<XmlNode> xmlChildNodes = dataNode.XmlChildNodes;
        if (xmlChildNodes == null)
        {
            return;
        }
        foreach (XmlNode item2 in xmlChildNodes)
        {
            item2.WriteTo(xmlWriter.Writer);
        }
    }
References System.item, System.Runtime.Serialization.XmlObjectSerializerWriteContext.TryWriteDeserializedExtensionData(), System.Runtime.Serialization.XmlObjectSerializerWriteContext.WriteExtensionDataTypeInfo(), System.Runtime.Serialization.XmlDataNode.XmlAttributes, and System.Runtime.Serialization.XmlDataNode.XmlChildNodes.
Referenced by System.Runtime.Serialization.XmlObjectSerializerWriteContext.WriteExtensionDataValue().