Terraria: System.Runtime.Serialization.XmlObjectSerializerWriteContext.SerializeWithXsiType
SerializeWithXsiType()
virtual void System.Runtime.Serialization.XmlObjectSerializerWriteContext.SerializeWithXsiType (XmlWriterDelegator xmlWriter, object obj, RuntimeTypeHandle objectTypeHandle, Type objectType, int declaredTypeID, RuntimeTypeHandle declaredTypeHandle, Type declaredType) inline protected virtual inherited
Reimplemented in System.Runtime.Serialization.Json.XmlObjectSerializerWriteContextComplexJson.
Definition at line 164 of file XmlObjectSerializerWriteContext.cs.
    {
        bool verifyKnownType = false;
        DataContract dataContractSkipValidation;
        if (declaredType.IsInterface && CollectionDataContract.IsCollectionInterface(declaredType))
        {
            dataContractSkipValidation = GetDataContractSkipValidation(DataContract.GetId(objectTypeHandle), objectTypeHandle, objectType);
            if (OnHandleIsReference(xmlWriter, dataContractSkipValidation, obj))
            {
                return;
            }
            dataContractSkipValidation = GetDataContract(declaredTypeHandle, declaredType);
            if (!WriteClrTypeInfo(xmlWriter, dataContractSkipValidation) && base.DataContractResolver != null)
            {
                if (objectType == null)
                {
                    objectType = Type.GetTypeFromHandle(objectTypeHandle);
                }
                WriteResolvedTypeInfo(xmlWriter, objectType, declaredType);
            }
        }
        else if (declaredType.IsArray)
        {
            dataContractSkipValidation = GetDataContract(objectTypeHandle, objectType);
            WriteClrTypeInfo(xmlWriter, dataContractSkipValidation);
            dataContractSkipValidation = GetDataContract(declaredTypeHandle, declaredType);
        }
        else
        {
            dataContractSkipValidation = GetDataContract(objectTypeHandle, objectType);
            if (OnHandleIsReference(xmlWriter, dataContractSkipValidation, obj))
            {
                return;
            }
            if (!WriteClrTypeInfo(xmlWriter, dataContractSkipValidation))
            {
                DataContract declaredContract = ((declaredTypeID >= 0) ? GetDataContract(declaredTypeID, declaredTypeHandle) : GetDataContract(declaredTypeHandle, declaredType));
                verifyKnownType = WriteTypeInfo(xmlWriter, dataContractSkipValidation, declaredContract);
            }
        }
        SerializeAndVerifyType(dataContractSkipValidation, xmlWriter, obj, verifyKnownType, declaredTypeHandle, declaredType);
    }
References System.Runtime.Serialization.Dictionary, System.Runtime.Serialization.XmlObjectSerializerContext.GetDataContract(), System.Runtime.Serialization.XmlObjectSerializerContext.GetDataContractSkipValidation(), System.Runtime.Serialization.DataContract.GetId(), System.Type.GetTypeFromHandle(), System.Runtime.Serialization.CollectionDataContract.IsCollectionInterface(), System.obj, System.Runtime.Serialization.XmlObjectSerializerWriteContext.OnHandleIsReference(), System.Runtime.Serialization.XmlObjectSerializerWriteContext.SerializeAndVerifyType(), System.Runtime.Serialization.XmlObjectSerializerWriteContext.WriteClrTypeInfo(), System.Runtime.Serialization.XmlObjectSerializerWriteContext.WriteResolvedTypeInfo(), and System.Runtime.Serialization.XmlObjectSerializerWriteContext.WriteTypeInfo().
Referenced by System.Runtime.Serialization.XmlObjectSerializerWriteContext.InternalSerialize(), and System.Runtime.Serialization.XmlObjectSerializerWriteContextComplex.InternalSerializeWithSurrogate().