Terraria: System.Runtime.Serialization.XmlObjectSerializerWriteContext.SerializeAndVerifyType
SerializeAndVerifyType()
void System.Runtime.Serialization.XmlObjectSerializerWriteContext.SerializeAndVerifyType (DataContract dataContract, XmlWriterDelegator xmlWriter, object obj, bool verifyKnownType, RuntimeTypeHandle declaredTypeHandle, Type declaredType) inline protected inherited
Definition at line 241 of file XmlObjectSerializerWriteContext.cs.
    {
        bool flag = false;
        if (dataContract.KnownDataContracts != null)
        {
            scopedKnownTypes.Push(dataContract.KnownDataContracts);
            flag = true;
        }
        if (verifyKnownType && !IsKnownType(dataContract, declaredType))
        {
            DataContract dataContract2 = ResolveDataContractFromKnownTypes(dataContract.StableName.Name, dataContract.StableName.Namespace, null, declaredType);
            if (dataContract2 == null || dataContract2.UnderlyingType != dataContract.UnderlyingType)
            {
                throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(XmlObjectSerializer.CreateSerializationException(System.SR.Format(System.SR.DcTypeNotFoundOnSerialize, DataContract.GetClrTypeFullName(dataContract.UnderlyingType), dataContract.StableName.Name, dataContract.StableName.Namespace)));
            }
        }
        WriteDataContractValue(dataContract, xmlWriter, obj, declaredTypeHandle);
        if (flag)
        {
            scopedKnownTypes.Pop();
        }
    }
References System.Runtime.Serialization.XmlObjectSerializer.CreateSerializationException(), System.SR.DcTypeNotFoundOnSerialize, System.SR.Format(), System.Runtime.Serialization.DataContract.GetClrTypeFullName(), System.Runtime.Serialization.XmlObjectSerializerContext.IsKnownType(), System.obj, System.Runtime.Serialization.ScopedKnownTypes.Pop(), System.Runtime.Serialization.ScopedKnownTypes.Push(), System.Runtime.Serialization.XmlObjectSerializerContext.ResolveDataContractFromKnownTypes(), System.Runtime.Serialization.XmlObjectSerializerContext.scopedKnownTypes, System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperError(), and System.Runtime.Serialization.XmlObjectSerializerWriteContext.WriteDataContractValue().
Referenced by System.Runtime.Serialization.Json.XmlObjectSerializerWriteContextComplexJson.SerializeWithXsiType(), System.Runtime.Serialization.XmlObjectSerializerWriteContext.SerializeWithXsiType(), System.Runtime.Serialization.Json.XmlObjectSerializerWriteContextComplexJson.SerializeWithXsiTypeAtTopLevel(), and System.Runtime.Serialization.XmlObjectSerializerWriteContext.SerializeWithXsiTypeAtTopLevel().