Terraria: Terraria.GameContent.UI.Chat.LegacyChatMonitor.NewTextInternal
NewTextInternal()
void Terraria.GameContent.UI.Chat.LegacyChatMonitor.NewTextInternal (string newText, byte R = byte::MaxValue, byte G = byte::MaxValue, byte B = byte::MaxValue, bool force = false) inline
    {
        int num = 80;
        if (!force && newText.Length > num)
        {
            string oldText = newText;
            oldText = TrimIntoMultipleLines(R, G, B, num, oldText);
            if (oldText.Length > 0)
            {
                NewTextInternal(oldText, R, G, B, force: true);
            }
            return;
        }
        for (int num2 = numChatLines - 1; num2 > 0; num2--)
        {
            chatLine[num2].Copy(chatLine[num2 - 1]);
        }
        chatLine[0].color = new Color(R, G, B);
        chatLine[0].originalText = newText;
        chatLine[0].parsedText = ChatManager.ParseMessage(chatLine[0].originalText, chatLine[0].color).ToArray();
        chatLine[0].showTime = chatLength;
        SoundEngine.PlaySound(12);
    }
References Terraria.GameContent.UI.Chat.LegacyChatMonitor.chatLength, Terraria.GameContent.UI.Chat.LegacyChatMonitor.chatLine, Terraria.UI.Chat.ChatLine.color, Terraria.UI.Chat.ChatLine.Copy(), Terraria.GameContent.UI.Chat.LegacyChatMonitor.NewTextInternal(), Terraria.GameContent.UI.Chat.LegacyChatMonitor.numChatLines, Terraria.UI.Chat.ChatLine.originalText, Terraria.UI.Chat.ChatLine.parsedText, Terraria.UI.Chat.ChatManager.ParseMessage(), Terraria.Audio.SoundEngine.PlaySound(), Terraria.UI.Chat.ChatLine.showTime, and Terraria.GameContent.UI.Chat.LegacyChatMonitor.TrimIntoMultipleLines().
Referenced by Terraria.GameContent.UI.Chat.LegacyChatMonitor.NewTextInternal(), and Terraria.GameContent.UI.Chat.LegacyChatMonitor.TrimIntoMultipleLines().