Terraria: UICreativeInfiniteItemsDisplay.UpdateVisualFrame
UpdateVisualFrame()
void UICreativeInfiniteItemsDisplay.UpdateVisualFrame () inline private
     {
         float num = 0.05f;
         float sacrificeAnimationProgress = GetSacrificeAnimationProgress();
         float lerpValue = Utils.GetLerpValue(1f, 0.7f, sacrificeAnimationProgress, clamped: true);
         float num2 = lerpValue * lerpValue;
         num2 *= 2f;
         float num3 = 1f + num2;
         num *= num3;
         float num4 = 1.1428572f;
         float num5 = 1f;
         OffsetRotationsForCogs(2f * num, _sacrificeCogsSmall);
         OffsetRotationsForCogs(num4 * num, _sacrificeCogsMedium);
         OffsetRotationsForCogs((0f - num5) * num, _sacrificeCogsBig);
         int frameY = 0;
         if (_sacrificeAnimationTimeLeft != 0)
         {
             float num6 = 0.1f;
             float num7 = 1f / 15f;
             frameY = ((sacrificeAnimationProgress >= 1f - num6) ? 8 : ((sacrificeAnimationProgress >= 1f - num6 * 2f) ? 7 : ((sacrificeAnimationProgress >= 1f - num6 * 3f) ? 6 : ((sacrificeAnimationProgress >= num7 * 4f) ? 5 : ((sacrificeAnimationProgress >= num7 * 3f) ? 4 : ((sacrificeAnimationProgress >= num7 * 2f) ? 3 : ((!(sacrificeAnimationProgress >= num7)) ? 1 : 2)))))));
             if (_sacrificeAnimationTimeLeft == 56)
             {
                 SoundEngine.PlaySound(63);
                 Vector2 accelerationPerFrame = new Vector2(0f, 0.16350001f);
                 for (int i = 0; i < 15; i++)
                 {
                     Vector2 initialVelocity = Main.rand.NextVector2Circular(4f, 3f);
                     if (initialVelocity.Y > 0f)
                     {
                         initialVelocity.Y = 0f - initialVelocity.Y;
                     }
                     initialVelocity.Y -= 2f;
                     _pistonParticleSystem.AddParticle(new CreativeSacrificeParticle(_pistonParticleAsset, null, initialVelocity, Vector2.Zero)
                     {
                         AccelerationPerFrame = accelerationPerFrame,
                         ScaleOffsetPerFrame = -1f / 60f
                     });
                 }
             }
             if (_sacrificeAnimationTimeLeft == 40 && _researchComplete)
             {
                 _researchComplete = false;
                 SoundEngine.PlaySound(64);
             }
         }
         _sacrificePistons.SetFrame(1, 9, 0, frameY, 0, 0);
     }
References _pistonParticleAsset, _pistonParticleSystem, _researchComplete, _sacrificeAnimationTimeLeft, _sacrificeCogsBig, _sacrificeCogsMedium, _sacrificeCogsSmall, _sacrificePistons, UIParticleLayer.AddParticle(), Utils.GetLerpValue(), GetSacrificeAnimationProgress(), OffsetRotationsForCogs(), SoundEngine.PlaySound(), Main.rand, and UIImageFramed.SetFrame().
Referenced by sacrificeWindow_OnUpdate(), and StopPlayingAnimation().