Terraria: UICreativeInfiniteItemsDisplay.EscapeVirtualKeyboard
EscapeVirtualKeyboard()
bool UICreativeInfiniteItemsDisplay.EscapeVirtualKeyboard () inline private
     {
         IngameFancyUI.Close();
         Main.playerInventory = true;
         if (_searchBar.IsWritingText)
         {
             _searchBar.ToggleTakingText();
         }
         Main.CreativeMenu.ToggleMenu();
         return true;
     }
References _searchBar, IngameFancyUI.Close(), Main.CreativeMenu, UISearchBar.IsWritingText, Main.playerInventory, CreativeUI.ToggleMenu(), and UISearchBar.ToggleTakingText().
Referenced by OpenVirtualKeyboardWhenNeeded().