Terraria: UICreativeInfiniteItemsDisplay.OpenVirtualKeyboardWhenNeeded
OpenVirtualKeyboardWhenNeeded()
void UICreativeInfiniteItemsDisplay.OpenVirtualKeyboardWhenNeeded () inline private
     {
         int maxInputLength = 40;
         UIVirtualKeyboard uIVirtualKeyboard = new UIVirtualKeyboard(Language.GetText("UI.PlayerNameSlot").Value, _searchString, OnFinishedSettingName, GoBackHere, 3, allowEmpty: true);
         uIVirtualKeyboard.SetMaxInputLength(maxInputLength);
         uIVirtualKeyboard.CustomEscapeAttempt = EscapeVirtualKeyboard;
         IngameFancyUI.OpenUIState(uIVirtualKeyboard);
     }
References _searchString, UIVirtualKeyboard.CustomEscapeAttempt, EscapeVirtualKeyboard(), Language.GetText(), GoBackHere(), OnFinishedSettingName(), IngameFancyUI.OpenUIState(), UIVirtualKeyboard.SetMaxInputLength(), and LocalizedText.Value.
Referenced by AddSearchBar().