Terraria: UICreativeInfiniteItemsDisplay.UICreativeInfiniteItemsDisplay_OnUpdate
UICreativeInfiniteItemsDisplay_OnUpdate()
void UICreativeInfiniteItemsDisplay.UICreativeInfiniteItemsDisplay_OnUpdate (UIElement affectedElement) inline private
     {
         RemoveAllChildren();
         CreativeUnlocksTracker localPlayerCreativeTracker = Main.LocalPlayerCreativeTracker;
         if (_lastTrackerCheckedForEdits != localPlayerCreativeTracker)
         {
             _lastTrackerCheckedForEdits = localPlayerCreativeTracker;
             _lastCheckedVersionForEdits = -1;
         }
         int lastEditId = localPlayerCreativeTracker.ItemSacrifices.LastEditId;
         if (_lastCheckedVersionForEdits != lastEditId)
         {
             _lastCheckedVersionForEdits = lastEditId;
             UpdateContents();
         }
         if (_showSacrificesInsteadOfInfinites)
         {
             Append(_containerSacrifice);
         }
         else
         {
             Append(_containerInfinites);
         }
         UpdateSacrificeAnimation();
     }
References _containerInfinites, _containerSacrifice, _lastCheckedVersionForEdits, _lastTrackerCheckedForEdits, _showSacrificesInsteadOfInfinites, UIElement.Append(), CreativeUnlocksTracker.ItemSacrifices, ItemsSacrificedUnlocksTracker.LastEditId, Main.LocalPlayerCreativeTracker, UIElement.RemoveAllChildren(), UpdateContents(), and UpdateSacrificeAnimation().
Referenced by BuildPage().