Terraria: UICreativeInfiniteItemsDisplay.BuildSacrificeMenuContents
BuildSacrificeMenuContents()
void UICreativeInfiniteItemsDisplay.BuildSacrificeMenuContents (UIElement totalContainer) inline private
     {
         UIPanel uIPanel = CreateBasicPanel();
         uIPanel.VAlign = 0.5f;
         uIPanel.Height = new StyleDimension(170f, 0f);
         uIPanel.Width = new StyleDimension(170f, 0f);
         uIPanel.Top = default(StyleDimension);
         totalContainer.Append(uIPanel);
         uIPanel.OnUpdate += Hover_OnUpdate;
         uIPanel.OnMouseOver += Hover_OnMouseOver;
         uIPanel.OnMouseOut += Hover_OnMouseOut;
         AddCogsForSacrificeMenu(uIPanel);
         _pistonParticleAsset = Main.Assets.Request<Texture2D>("Images/UI/Creative/Research_Spark", (AssetRequestMode)1);
         float pixels = 0f;
         UIImage uIImage = new UIImage(Main.Assets.Request<Texture2D>("Images/UI/Creative/Research_Slots", (AssetRequestMode)1))
         {
             HAlign = 0.5f,
             VAlign = 0.5f,
             Top = new StyleDimension(-20f, 0f),
             Left = new StyleDimension(pixels, 0f)
         };
         uIPanel.Append(uIImage);
         Asset<Texture2D> obj = Main.Assets.Request<Texture2D>("Images/UI/Creative/Research_FramedPistons", (AssetRequestMode)1);
         UIImageFramed uIImageFramed = new UIImageFramed(obj, obj.Frame(1, 9))
         {
             HAlign = 0.5f,
             VAlign = 0.5f,
             Top = new StyleDimension(-20f, 0f),
             Left = new StyleDimension(pixels, 0f),
             IgnoresMouseInteraction = true
         };
         uIPanel.Append(uIImageFramed);
         _sacrificePistons = uIImageFramed;
         UIParticleLayer pistonParticleSystem = new UIParticleLayer
         {
             Width = new StyleDimension(0f, 1f),
             Height = new StyleDimension(0f, 1f),
             AnchorPositionOffsetByPercents = Vector2.One / 2f,
             AnchorPositionOffsetByPixels = Vector2.Zero
         };
         _pistonParticleSystem = pistonParticleSystem;
         uIImageFramed.Append(_pistonParticleSystem);
         UIElement uIElement = Main.CreativeMenu.ProvideItemSlotElement(0);
         uIElement.HAlign = 0.5f;
         uIElement.VAlign = 0.5f;
         uIElement.Top = new StyleDimension(-15f, 0f);
         uIElement.Left = new StyleDimension(pixels, 0f);
         uIElement.SetSnapPoint("CreativeSacrificeSlot", 0);
         uIImage.Append(uIElement);
         UIText uIText = new UIText("(0/50)", 0.8f)
         {
             Top = new StyleDimension(10f, 0f),
             Left = new StyleDimension(pixels, 0f),
             HAlign = 0.5f,
             VAlign = 0.5f,
             IgnoresMouseInteraction = true
         };
         uIText.OnUpdate += descriptionText_OnUpdate;
         uIPanel.Append(uIText);
         UIPanel uIPanel2 = new UIPanel
         {
             Top = new StyleDimension(0f, 0f),
             Left = new StyleDimension(pixels, 0f),
             HAlign = 0.5f,
             VAlign = 1f,
             Width = new StyleDimension(124f, 0f),
             Height = new StyleDimension(30f, 0f)
         };
         UIText element = new UIText(Language.GetText("CreativePowers.ConfirmInfiniteItemSacrifice"), 0.8f)
         {
             IgnoresMouseInteraction = true,
             HAlign = 0.5f,
             VAlign = 0.5f
         };
         uIPanel2.Append(element);
         uIPanel2.SetSnapPoint("CreativeSacrificeConfirm", 0);
         uIPanel2.OnLeftClick += sacrificeButton_OnClick;
         uIPanel2.OnMouseOver += FadedMouseOver;
         uIPanel2.OnMouseOut += FadedMouseOut;
         uIPanel2.OnUpdate += research_OnUpdate;
         uIPanel.Append(uIPanel2);
         uIPanel.OnUpdate += sacrificeWindow_OnUpdate;
     }
References _pistonParticleAsset, _pistonParticleSystem, _sacrificePistons, AddCogsForSacrificeMenu(), UIElement.Append(), Main.Assets, CreateBasicPanel(), Main.CreativeMenu, descriptionText_OnUpdate(), FadedMouseOut(), FadedMouseOver(), Language.GetText(), UIElement.HAlign, UIElement.Height, Hover_OnMouseOut(), Hover_OnMouseOver(), Hover_OnUpdate(), UIElement.IgnoresMouseInteraction, UIElement.Left, UIElement.OnLeftClick, UIElement.OnMouseOut, UIElement.OnMouseOver, UIElement.OnUpdate, CreativeUI.ProvideItemSlotElement(), research_OnUpdate(), sacrificeButton_OnClick(), sacrificeWindow_OnUpdate(), UIElement.SetSnapPoint(), UIElement.Top, UIElement.VAlign, and UIElement.Width.
Referenced by BuildPage().