Terraria: UICreativeInfiniteItemsDisplay.BuildPage
BuildPage()
void UICreativeInfiniteItemsDisplay.BuildPage () inline private
     {
         _lastCheckedVersionForEdits = -1;
         RemoveAllChildren();
         SetPadding(0f);
         UIElement uIElement = new UIElement
         {
             Width = StyleDimension.Fill,
             Height = StyleDimension.Fill
         };
         uIElement.SetPadding(0f);
         _containerInfinites = uIElement;
         UIElement uIElement2 = new UIElement
         {
             Width = StyleDimension.Fill,
             Height = StyleDimension.Fill
         };
         uIElement2.SetPadding(0f);
         _containerSacrifice = uIElement2;
         BuildInfinitesMenuContents(uIElement);
         BuildSacrificeMenuContents(uIElement2);
         UpdateContents();
         base.OnUpdate += UICreativeInfiniteItemsDisplay_OnUpdate;
     }
References _containerInfinites, _containerSacrifice, _lastCheckedVersionForEdits, BuildInfinitesMenuContents(), BuildSacrificeMenuContents(), StyleDimension.Fill, UIElement.Height, UIElement.RemoveAllChildren(), UIElement.SetPadding(), UICreativeInfiniteItemsDisplay_OnUpdate(), UpdateContents(), and UIElement.Width.
Referenced by UICreativeInfiniteItemsDisplay().