Terraria: Terraria.GameContent.UI.Chat.LegacyChatMonitor.NewTextMultiline
NewTextMultiline()
void Terraria.GameContent.UI.Chat.LegacyChatMonitor.NewTextMultiline (string text, bool force = false, Color c = default(Color), int WidthLimit = -1) inline
Implements Terraria.GameContent.UI.Chat.IChatMonitor.
Definition at line 161 of file LegacyChatMonitor.cs.
    {
        if (c == default(Color))
        {
            c = Color.White;
        }
        List<List<TextSnippet>> list = ((WidthLimit == -1) ? Utils.WordwrapStringSmart(text, c, FontAssets.MouseText.Value, TextMaxLengthForScreen, 10) : Utils.WordwrapStringSmart(text, c, FontAssets.MouseText.Value, WidthLimit, 10));
        for (int i = 0; i < list.Count; i++)
        {
            NewText(list[i]);
        }
    }
References Terraria.GameContent.FontAssets.MouseText, Terraria.GameContent.UI.Chat.LegacyChatMonitor.NewText(), Terraria.GameContent.UI.Chat.LegacyChatMonitor.TextMaxLengthForScreen, Microsoft.Xna.Framework.Color.White, and Terraria.Utils.WordwrapStringSmart().
Referenced by Terraria.GameContent.UI.Chat.LegacyChatMonitor.NewText().