Terraria: UICreativeInfiniteItemsDisplay.descriptionText_OnUpdate
descriptionText_OnUpdate()
void UICreativeInfiniteItemsDisplay.descriptionText_OnUpdate (UIElement affectedElement) inline private
     {
         UIText uIText = affectedElement as UIText;
         int itemIdChecked;
         int amountWeHave;
         int amountNeededTotal;
         bool sacrificeNumbers = Main.CreativeMenu.GetSacrificeNumbers(out itemIdChecked, out amountWeHave, out amountNeededTotal);
         Main.CreativeMenu.ShouldDrawSacrificeArea();
         if (!Main.mouseItem.IsAir)
         {
             ForgetItemSacrifice();
         }
         if (itemIdChecked == 0)
         {
             if (_lastItemIdSacrificed != 0 && _lastItemAmountWeNeededTotal != _lastItemAmountWeHad)
             {
                 uIText.SetText($"({_lastItemAmountWeHad}/{_lastItemAmountWeNeededTotal})");
             }
             else
             {
                 uIText.SetText("???");
             }
             return;
         }
         ForgetItemSacrifice();
         if (!sacrificeNumbers)
         {
             uIText.SetText("X");
         }
         else
         {
             uIText.SetText($"({amountWeHave}/{amountNeededTotal})");
         }
     }
References _lastItemAmountWeHad, _lastItemAmountWeNeededTotal, _lastItemIdSacrificed, Main.CreativeMenu, ForgetItemSacrifice(), CreativeUI.GetSacrificeNumbers(), Item.IsAir, Main.mouseItem, UIText.SetText(), and CreativeUI.ShouldDrawSacrificeArea().
Referenced by BuildSacrificeMenuContents().