Terraria: UICreativeInfiniteItemsDisplay.UpdateContents
UpdateContents()
void UICreativeInfiniteItemsDisplay.UpdateContents () inline private
     {
         _itemIdsAvailableTotal.Clear();
         Main.LocalPlayerCreativeTracker.ItemSacrifices.FillListOfItemsThatCanBeObtainedInfinitely(_itemIdsAvailableTotal);
         _itemIdsAvailableToShow.Clear();
         _itemIdsAvailableToShow.AddRange(_itemIdsAvailableTotal.Where((int x) => _filterer.FitsFilter(ContentSamples.ItemsByType[x])));
         _itemIdsAvailableToShow.Sort(_sorter);
         _itemGrid.SetContentsToShow(_itemIdsAvailableToShow);
     }
References _filterer, _itemGrid, _itemIdsAvailableToShow, _itemIdsAvailableTotal, _sorter, ItemsSacrificedUnlocksTracker.FillListOfItemsThatCanBeObtainedInfinitely(), EntryFilterer< T, U >.FitsFilter(), CreativeUnlocksTracker.ItemSacrifices, ContentSamples.ItemsByType, Main.LocalPlayerCreativeTracker, and UIDynamicItemCollection.SetContentsToShow().
Referenced by BuildPage(), filtersHelper_OnClickingOption(), OnSearchContentsChanged(), and UICreativeInfiniteItemsDisplay_OnUpdate().