Terraria: UICreativeInfiniteItemsDisplay.GoBackHere
GoBackHere()
void UICreativeInfiniteItemsDisplay.GoBackHere () inline private
     {
         IngameFancyUI.Close();
         Main.CreativeMenu.ToggleMenu();
         _searchBar.ToggleTakingText();
         Main.CreativeMenu.GamepadMoveToSearchButtonHack = true;
     }
References _searchBar, IngameFancyUI.Close(), Main.CreativeMenu, CreativeUI.GamepadMoveToSearchButtonHack, CreativeUI.ToggleMenu(), and UISearchBar.ToggleTakingText().
Referenced by OnFinishedSettingName(), and OpenVirtualKeyboardWhenNeeded().