Terraria: UICreativeInfiniteItemsDisplay.AddSearchBar
AddSearchBar()
void UICreativeInfiniteItemsDisplay.AddSearchBar (UIElement searchArea) inline private
     {
         UIImageButton uIImageButton = new UIImageButton(Main.Assets.Request<Texture2D>("Images/UI/Bestiary/Button_Search", (AssetRequestMode)1))
         {
             VAlign = 0.5f,
             HAlign = 0f
         };
         uIImageButton.OnLeftClick += Click_SearchArea;
         uIImageButton.SetHoverImage(Main.Assets.Request<Texture2D>("Images/UI/Bestiary/Button_Search_Border", (AssetRequestMode)1));
         uIImageButton.SetVisibility(1f, 1f);
         uIImageButton.SetSnapPoint("CreativeInfinitesSearch", 0);
         searchArea.Append(uIImageButton);
         UIPanel uIPanel = (_searchBoxPanel = new UIPanel
         {
             Width = new StyleDimension(0f - uIImageButton.Width.Pixels - 3f, 1f),
             Height = new StyleDimension(0f, 1f),
             VAlign = 0.5f,
             HAlign = 1f
         });
         uIPanel.BackgroundColor = new Color(35, 40, 83);
         uIPanel.BorderColor = new Color(35, 40, 83);
         uIPanel.SetPadding(0f);
         searchArea.Append(uIPanel);
         UISearchBar uISearchBar = (_searchBar = new UISearchBar(Language.GetText("UI.PlayerNameSlot"), 0.8f)
         {
             Width = new StyleDimension(0f, 1f),
             Height = new StyleDimension(0f, 1f),
             HAlign = 0f,
             VAlign = 0.5f,
             Left = new StyleDimension(0f, 0f),
             IgnoresMouseInteraction = true
         });
         uIPanel.OnLeftClick += Click_SearchArea;
         uISearchBar.OnContentsChanged += OnSearchContentsChanged;
         uIPanel.Append(uISearchBar);
         uISearchBar.OnStartTakingInput += OnStartTakingInput;
         uISearchBar.OnEndTakingInput += OnEndTakingInput;
         uISearchBar.OnNeedingVirtualKeyboard += OpenVirtualKeyboardWhenNeeded;
         uISearchBar.OnCanceledTakingInput += OnCanceledInput;
         UIImageButton uIImageButton2 = new UIImageButton(Main.Assets.Request<Texture2D>("Images/UI/SearchCancel", (AssetRequestMode)1))
         {
             HAlign = 1f,
             VAlign = 0.5f,
             Left = new StyleDimension(-2f, 0f)
         };
         uIImageButton2.OnMouseOver += searchCancelButton_OnMouseOver;
         uIImageButton2.OnLeftClick += searchCancelButton_OnClick;
         uIPanel.Append(uIImageButton2);
     }
References _searchBar, _searchBoxPanel, UIElement.Append(), Main.Assets, UIPanel.BackgroundColor, UIPanel.BorderColor, Click_SearchArea(), Color, Language.GetText(), UIElement.HAlign, UIElement.Height, UIElement.IgnoresMouseInteraction, UIElement.Left, OnCanceledInput(), UISearchBar.OnCanceledTakingInput, UISearchBar.OnContentsChanged, OnEndTakingInput(), UISearchBar.OnEndTakingInput, UIElement.OnLeftClick, UIElement.OnMouseOver, UISearchBar.OnNeedingVirtualKeyboard, OnSearchContentsChanged(), OnStartTakingInput(), UISearchBar.OnStartTakingInput, OpenVirtualKeyboardWhenNeeded(), StyleDimension.Pixels, searchCancelButton_OnClick(), searchCancelButton_OnMouseOver(), UIImageButton.SetHoverImage(), UIElement.SetPadding(), UIElement.SetSnapPoint(), UIImageButton.SetVisibility(), UIElement.VAlign, and UIElement.Width.
Referenced by BuildInfinitesMenuContents().