Terraria: System.Net.Http.Http2Connection.RttEstimator.OnDataOrHeadersReceived
OnDataOrHeadersReceived()
void System.Net.Http.Http2Connection.RttEstimator.OnDataOrHeadersReceived (Http2Connection connection) inline package
Definition at line 1615 of file Http2Connection.cs.
        {
            if (_state != State.Waiting)
            {
                return;
            }
            long timestamp = Stopwatch.GetTimestamp();
            bool flag = _initialBurst > 0;
            if (flag || timestamp - _pingSentTimestamp > PingIntervalInTicks)
            {
                if (flag)
                {
                    _initialBurst--;
                }
                _pingCounter--;
                if (System.Net.NetEventSource.Log.IsEnabled())
                {
                    connection.Trace($"[FlowControl] Sending RTT PING with payload {_pingCounter}", "OnDataOrHeadersReceived");
                }
                connection.LogExceptions(connection.SendPingAsync(_pingCounter));
                _pingSentTimestamp = timestamp;
                _state = State.PingSent;
            }
        }
References System.Net.Http.Http2Connection.RttEstimator._initialBurst, System.Net.Http.Http2Connection.RttEstimator._pingCounter, System.Net.Http.Http2Connection.RttEstimator._pingSentTimestamp, System.Net.Http.Http2Connection.RttEstimator._state, System.Diagnostics.Stopwatch.GetTimestamp(), System.Net.NetEventSource.Log, System.Net.Http.HttpConnectionBase.LogExceptions(), System.Net.Http.Http2Connection.RttEstimator.PingIntervalInTicks, System.Net.Http.Http2Connection.SendPingAsync(), and System.Net.Http.Http2Connection.Trace().
Referenced by System.Net.Http.Http2Connection.ProcessDataFrame(), and System.Net.Http.Http2Connection.ProcessHeadersFrame().