Terraria: System.Net.Http.Http2Connection.RttEstimator.RefreshRtt
RefreshRtt()
void System.Net.Http.Http2Connection.RttEstimator.RefreshRtt (Http2Connection connection) inline private
Definition at line 1679 of file Http2Connection.cs.
        {
            long num = Stopwatch.GetTimestamp() - _pingSentTimestamp;
            long val = ((_minRtt == 0L) ? long.MaxValue : _minRtt);
            long value = Math.Min(val, TimeSpan.FromSeconds((double)num / (double)Stopwatch.Frequency).Ticks);
            Interlocked.Exchange(ref _minRtt, value);
            if (System.Net.NetEventSource.Log.IsEnabled())
            {
                connection.Trace($"[FlowControl] Updated MinRtt: {MinRtt.TotalMilliseconds} ms", "RefreshRtt");
            }
        }
References System.Net.Http.Http2Connection.RttEstimator._minRtt, System.Net.Http.Http2Connection.RttEstimator._pingSentTimestamp, System.Threading.Interlocked.Exchange(), System.Diagnostics.Stopwatch.Frequency, System.TimeSpan.FromSeconds(), System.Diagnostics.Stopwatch.GetTimestamp(), System.L, System.Net.NetEventSource.Log, System.Math.Min(), System.Net.Http.Http2Connection.Trace(), and System.value.
Referenced by System.Net.Http.Http2Connection.RttEstimator.OnInitialSettingsAckReceived(), and System.Net.Http.Http2Connection.RttEstimator.OnPingAckReceived().