Terraria: Terraria.WorldBuilding.GenShape.UnitApply
UnitApply()
bool Terraria.WorldBuilding.GenShape.UnitApply (GenAction action, Point origin, int x, int y, params object[] args) inline protected inherited
    {
        if (_outputData != null)
        {
            _outputData.Add(x - origin.X, y - origin.Y);
        }
        return action.Apply(origin, x, y, args);
    }
References Terraria.WorldBuilding.GenShape._outputData, Terraria.WorldBuilding.ShapeData.Add(), and Terraria.WorldBuilding.GenAction.Apply().
Referenced by Terraria.GameContent.Generation.ShapeRoot.DoRoot(), Terraria.GameContent.Generation.ShapeFloodFill.Perform(), Terraria.GameContent.Generation.ShapeRunner.Perform(), Terraria.WorldBuilding.ModShapes.All.Perform(), Terraria.WorldBuilding.ModShapes.OuterOutline.Perform(), Terraria.WorldBuilding.ModShapes.InnerOutline.Perform(), Terraria.WorldBuilding.Shapes.Circle.Perform(), Terraria.WorldBuilding.Shapes.HalfCircle.Perform(), Terraria.WorldBuilding.Shapes.Slime.Perform(), Terraria.WorldBuilding.Shapes.Rectangle.Perform(), Terraria.WorldBuilding.Shapes.Tail.Perform(), Terraria.WorldBuilding.Shapes.Mound.Perform(), and Terraria.GameContent.Generation.ShapeBranch.PerformSegment().