using System;
using System.Diagnostics;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.Versioning;
using System.Xml.Serialization;

[assembly: CLSCompliant(true)]
[assembly: AssemblyDefaultAlias("System.Xml.XmlSerializer")]
[assembly: AssemblyMetadata(".NETFrameworkAssembly", "")]
[assembly: AssemblyMetadata("Serviceable", "True")]
[assembly: AssemblyMetadata("PreferInbox", "True")]
[assembly: AssemblyMetadata("IsTrimmable", "True")]
[assembly: AssemblyCompany("Microsoft Corporation")]
[assembly: AssemblyCopyright("© Microsoft Corporation. All rights reserved.")]
[assembly: AssemblyDescription("System.Xml.XmlSerializer")]
[assembly: AssemblyFileVersion("6.0.21.52210")]
[assembly: AssemblyInformationalVersion("6.0.0+4822e3c3aa77eb82b2fb33c9321f923cf11ddde6")]
[assembly: AssemblyProduct("Microsoft® .NET")]
[assembly: AssemblyTitle("System.Xml.XmlSerializer")]
[assembly: AssemblyMetadata("RepositoryUrl", "https://github.com/dotnet/runtime")]
[assembly: AssemblyVersion("6.0.0.0")]
[assembly: TypeForwardedTo(typeof(CodeGenerationOptions))]
[assembly: TypeForwardedTo(typeof(CodeIdentifier))]
[assembly: TypeForwardedTo(typeof(CodeIdentifiers))]
[assembly: TypeForwardedTo(typeof(ImportContext))]
[assembly: TypeForwardedTo(typeof(IXmlSerializable))]
[assembly: TypeForwardedTo(typeof(IXmlTextParser))]
[assembly: TypeForwardedTo(typeof(SchemaImporter))]
[assembly: TypeForwardedTo(typeof(SoapAttributeAttribute))]
[assembly: TypeForwardedTo(typeof(SoapAttributeOverrides))]
[assembly: TypeForwardedTo(typeof(SoapAttributes))]
[assembly: TypeForwardedTo(typeof(SoapElementAttribute))]
[assembly: TypeForwardedTo(typeof(SoapEnumAttribute))]
[assembly: TypeForwardedTo(typeof(SoapIgnoreAttribute))]
[assembly: TypeForwardedTo(typeof(SoapIncludeAttribute))]
[assembly: TypeForwardedTo(typeof(SoapReflectionImporter))]
[assembly: TypeForwardedTo(typeof(SoapSchemaMember))]
[assembly: TypeForwardedTo(typeof(SoapTypeAttribute))]
[assembly: TypeForwardedTo(typeof(UnreferencedObjectEventArgs))]
[assembly: TypeForwardedTo(typeof(UnreferencedObjectEventHandler))]
[assembly: TypeForwardedTo(typeof(XmlAnyAttributeAttribute))]
[assembly: TypeForwardedTo(typeof(XmlAnyElementAttribute))]
[assembly: TypeForwardedTo(typeof(XmlAnyElementAttributes))]
[assembly: TypeForwardedTo(typeof(XmlArrayAttribute))]
[assembly: TypeForwardedTo(typeof(XmlArrayItemAttribute))]
[assembly: TypeForwardedTo(typeof(XmlArrayItemAttributes))]
[assembly: TypeForwardedTo(typeof(XmlAttributeAttribute))]
[assembly: TypeForwardedTo(typeof(XmlAttributeEventArgs))]
[assembly: TypeForwardedTo(typeof(XmlAttributeEventHandler))]
[assembly: TypeForwardedTo(typeof(XmlAttributeOverrides))]
[assembly: TypeForwardedTo(typeof(XmlAttributes))]
[assembly: TypeForwardedTo(typeof(XmlChoiceIdentifierAttribute))]
[assembly: TypeForwardedTo(typeof(XmlDeserializationEvents))]
[assembly: TypeForwardedTo(typeof(XmlElementAttribute))]
[assembly: TypeForwardedTo(typeof(XmlElementAttributes))]
[assembly: TypeForwardedTo(typeof(XmlElementEventArgs))]
[assembly: TypeForwardedTo(typeof(XmlElementEventHandler))]
[assembly: TypeForwardedTo(typeof(XmlEnumAttribute))]
[assembly: TypeForwardedTo(typeof(XmlIgnoreAttribute))]
[assembly: TypeForwardedTo(typeof(XmlIncludeAttribute))]
[assembly: TypeForwardedTo(typeof(XmlMapping))]
[assembly: TypeForwardedTo(typeof(XmlMappingAccess))]
[assembly: TypeForwardedTo(typeof(XmlMemberMapping))]
[assembly: TypeForwardedTo(typeof(XmlMembersMapping))]
[assembly: TypeForwardedTo(typeof(XmlNamespaceDeclarationsAttribute))]
[assembly: TypeForwardedTo(typeof(XmlNodeEventArgs))]
[assembly: TypeForwardedTo(typeof(XmlNodeEventHandler))]
[assembly: TypeForwardedTo(typeof(XmlReflectionImporter))]
[assembly: TypeForwardedTo(typeof(XmlReflectionMember))]
[assembly: TypeForwardedTo(typeof(XmlRootAttribute))]
[assembly: TypeForwardedTo(typeof(XmlSchemaEnumerator))]
[assembly: TypeForwardedTo(typeof(XmlSchemaExporter))]
[assembly: TypeForwardedTo(typeof(XmlSchemaImporter))]
[assembly: TypeForwardedTo(typeof(XmlSchemaProviderAttribute))]
[assembly: TypeForwardedTo(typeof(XmlSchemas))]
[assembly: TypeForwardedTo(typeof(XmlSerializationCollectionFixupCallback))]
[assembly: TypeForwardedTo(typeof(XmlSerializationFixupCallback))]
[assembly: TypeForwardedTo(typeof(XmlSerializationGeneratedCode))]
[assembly: TypeForwardedTo(typeof(XmlSerializationReadCallback))]
[assembly: TypeForwardedTo(typeof(XmlSerializationReader))]
[assembly: TypeForwardedTo(typeof(XmlSerializationWriteCallback))]
[assembly: TypeForwardedTo(typeof(XmlSerializationWriter))]
[assembly: TypeForwardedTo(typeof(XmlSerializer))]
[assembly: TypeForwardedTo(typeof(XmlSerializerAssemblyAttribute))]
[assembly: TypeForwardedTo(typeof(XmlSerializerFactory))]
[assembly: TypeForwardedTo(typeof(XmlSerializerImplementation))]
[assembly: TypeForwardedTo(typeof(XmlSerializerNamespaces))]
[assembly: TypeForwardedTo(typeof(XmlSerializerVersionAttribute))]
[assembly: TypeForwardedTo(typeof(XmlTextAttribute))]
[assembly: TypeForwardedTo(typeof(XmlTypeAttribute))]
[assembly: TypeForwardedTo(typeof(XmlTypeMapping))]
[module: SkipLocalsInit]
