Terraria: System.Text.Unicode.Utf8Utility.TranscodeToUtf16
TranscodeToUtf16()
static unsafe OperationStatus System.Text.Unicode.Utf8Utility.TranscodeToUtf16 (byte * pInputBuffer, int inputLength, char * pOutputBuffer, int outputCharsRemaining, out byte * pInputBufferRemaining, out char * pOutputBufferRemaining) inline static
Definition at line 387 of file Utf8Utility.cs.
    {
        nuint num = ASCIIUtility.WidenAsciiToUtf16(pInputBuffer, pOutputBuffer, (uint)Math.Min(inputLength, outputCharsRemaining));
        pInputBuffer += num;
        pOutputBuffer += num;
        if ((int)num == inputLength)
        {
            pInputBufferRemaining = pInputBuffer;
            pOutputBufferRemaining = pOutputBuffer;
            return OperationStatus.Done;
        }
        inputLength -= (int)num;
        outputCharsRemaining -= (int)num;
        if (inputLength < 4)
        {
            goto IL_0690;
        }
        byte* ptr = pInputBuffer + (uint)inputLength - 4;
        while (true)
        {
            IL_004a:
            uint num2 = Unsafe.ReadUnaligned<uint>(pInputBuffer);
            while (true)
            {
                IL_0051:
                if (!ASCIIUtility.AllBytesInUInt32AreAscii(num2))
                {
                    goto IL_0120;
                }
                int num4;
                uint num5;
                if (outputCharsRemaining >= 4)
                {
                    ASCIIUtility.WidenFourAsciiBytesToUtf16AndWriteToBuffer(ref *pOutputBuffer, num2);
                    pInputBuffer += 4;
                    pOutputBuffer += 4;
                    outputCharsRemaining -= 4;
                    uint val = (uint)((int)(void*)Unsafe.ByteOffset(ref *pInputBuffer, ref *ptr) + 4);
                    uint num3 = Math.Min(val, (uint)outputCharsRemaining) / 8;
                    num4 = 0;
                    while ((uint)num4 < num3)
                    {
                        num2 = Unsafe.ReadUnaligned<uint>(pInputBuffer);
                        num5 = Unsafe.ReadUnaligned<uint>(pInputBuffer + 4);
                        if (ASCIIUtility.AllBytesInUInt32AreAscii(num2 | num5))
{
                            pInputBuffer += 8;
                            ASCIIUtility.WidenFourAsciiBytesToUtf16AndWriteToBuffer(ref *pOutputBuffer, num2);
                            ASCIIUtility.WidenFourAsciiBytesToUtf16AndWriteToBuffer(ref pOutputBuffer[4], num5);
                            pOutputBuffer += 8;
                            num4++;
                            continue;
                        }
                        goto IL_00f4;
                    }
                    outputCharsRemaining -= 8 * num4;
                    goto IL_04aa;
                }
                goto IL_04b1;
                IL_04b1:
                inputLength = (int)(void*)Unsafe.ByteOffset(ref *pInputBuffer, ref *ptr) + 4;
                goto IL_0690;
                IL_04aa:
                if (pInputBuffer <= ptr)
                {
                    goto IL_004a;
                }
                goto IL_04b1;
                IL_0120:
                if (UInt32FirstByteIsAscii(num2))
                {
                    if (outputCharsRemaining >= 3)
                    {
                        uint num6 = ToLittleEndian(num2);
                        nuint num7 = 1u;
                        *pOutputBuffer = (char)(byte)num6;
                        if (UInt32SecondByteIsAscii(num2))
{
                            num7++;
                            num6 >>= 8;
                            pOutputBuffer[1] = (char)(byte)num6;
                            if (UInt32ThirdByteIsAscii(num2))
{
                                num7++;
                                num6 >>= 8;
                                pOutputBuffer[2] = (char)(byte)num6;
                            }
                        }
                        pInputBuffer += num7;
                        pOutputBuffer += num7;
                        outputCharsRemaining -= (int)num7;
                    }
                    else
                    {
                        if (outputCharsRemaining == 0)
{
                            break;
                        }
                        uint num8 = ToLittleEndian(num2);
                        pInputBuffer++;
                        *(pOutputBuffer++) = (char)(byte)num8;
                        outputCharsRemaining--;
                        if (UInt32SecondByteIsAscii(num2))
{
                            if (outputCharsRemaining == 0)
{
                                break;
                            }
                            pInputBuffer++;
                            num8 >>= 8;
                            *(pOutputBuffer++) = (char)(byte)num8;
                            if (UInt32ThirdByteIsAscii(num2))
{
                                break;
                            }
                            outputCharsRemaining = 0;
                        }
                    }
                    if (pInputBuffer > ptr)
                    {
                        goto IL_04b1;
                    }
                    num2 = Unsafe.ReadUnaligned<uint>(pInputBuffer);
                }
                uint num9;
                while (UInt32BeginsWithUtf8TwoByteMask(num2))
                {
                    if (!UInt32BeginsWithOverlongUtf8TwoByteSequence(num2))
                    {
                        while (true)
{
                            _ = BitConverter.IsLittleEndian;
                            if (!UInt32EndsWithValidUtf8TwoByteSequenceLittleEndian(num2) && BitConverter.IsLittleEndian)
{
                                break;
                            }
                            if (outputCharsRemaining >= 2)
{
                                Unsafe.WriteUnaligned(pOutputBuffer, ExtractTwoCharsPackedFromTwoAdjacentTwoByteSequences(num2));
                                pInputBuffer += 4;
                                pOutputBuffer += 2;
                                outputCharsRemaining -= 2;
                                if (pInputBuffer <= ptr)
{
                                    num2 = Unsafe.ReadUnaligned<uint>(pInputBuffer);
                                    _ = BitConverter.IsLittleEndian;
                                    if (!UInt32BeginsWithValidUtf8TwoByteSequenceLittleEndian(num2))
{
                                        goto IL_0051;
                                    }
                                    continue;
                                }
                            }
                            goto IL_04b1;
                        }
                        num9 = ExtractCharFromFirstTwoByteSequence(num2);
                        if (UInt32ThirdByteIsAscii(num2))
{
                            if (UInt32FourthByteIsAscii(num2))
{
                                goto IL_0282;
                            }
                            if (outputCharsRemaining >= 2)
{
                                *pOutputBuffer = (char)num9;
                                char* num10 = pOutputBuffer + 1;
                                uint num11 = num2;
                                if (!BitConverter.IsLittleEndian)
{
                                }
                                *num10 = (char)(byte)(num11 >> 16);
                                pInputBuffer += 3;
                                pOutputBuffer += 2;
                                outputCharsRemaining -= 2;
                                if (ptr >= pInputBuffer)
{
                                    num2 = Unsafe.ReadUnaligned<uint>(pInputBuffer);
                                    continue;
                                }
                            }
                        }
                        else if (outputCharsRemaining != 0)
{
                            *pOutputBuffer = (char)num9;
                            pInputBuffer += 2;
                            pOutputBuffer++;
                            outputCharsRemaining--;
                            if (ptr >= pInputBuffer)
{
                                num2 = Unsafe.ReadUnaligned<uint>(pInputBuffer);
                                break;
                            }
                        }
                        goto IL_04b1;
                    }
                    goto IL_06a3;
                }
                if (UInt32BeginsWithUtf8ThreeByteMask(num2))
                {
                    while (true)
                    {
                        _ = BitConverter.IsLittleEndian;
                        if ((num2 & 0x200F) == 0 || ((num2 - 8205) & 0x200F) == 0)
{
                            break;
                        }
                        if (outputCharsRemaining == 0)
{
                            goto end_IL_0051;
                        }
                        _ = BitConverter.IsLittleEndian;
                        if ((((int)num2 - -536870912) & -268435456) == 0 && outputCharsRemaining > 1 && (nint)(void*)Unsafe.ByteOffset(ref *pInputBuffer, ref *ptr) >= (nint)3)
{
                            uint num12 = Unsafe.ReadUnaligned<uint>(pInputBuffer + 3);
                            if (UInt32BeginsWithUtf8ThreeByteMask(num12) && (num12 & 0x200Fu) != 0 && ((num12 - 8205) & 0x200Fu) != 0)
{
                                *pOutputBuffer = (char)ExtractCharFromFirstThreeByteSequence(num2);
                                pOutputBuffer[1] = (char)ExtractCharFromFirstThreeByteSequence(num12);
                                pInputBuffer += 6;
                                pOutputBuffer += 2;
                                outputCharsRemaining -= 2;
                                goto IL_03ff;
                            }
                        }
                        *pOutputBuffer = (char)ExtractCharFromFirstThreeByteSequence(num2);
                        pInputBuffer += 3;
                        pOutputBuffer++;
                        outputCharsRemaining--;
                        goto IL_03ff;
                        IL_03ff:
                        if (UInt32FourthByteIsAscii(num2))
{
                            if (outputCharsRemaining == 0)
{
                                goto end_IL_0051;
                            }
                            _ = BitConverter.IsLittleEndian;
                            *pOutputBuffer = (char)(num2 >> 24);
                            pInputBuffer++;
                            pOutputBuffer++;
                            outputCharsRemaining--;
                        }
                        if (pInputBuffer <= ptr)
{
                            num2 = Unsafe.ReadUnaligned<uint>(pInputBuffer);
                            if (!UInt32BeginsWithUtf8ThreeByteMask(num2))
{
                                goto IL_0051;
                            }
                            continue;
                        }
                        goto IL_04b1;
                    }
                }
                else if (UInt32BeginsWithUtf8FourByteMask(num2))
                {
                    _ = BitConverter.IsLittleEndian;
                    uint value = num2 & 0xFFFFu;
                    value = BitOperations.RotateRight(value, 8);
                    if (UnicodeUtility.IsInRangeInclusive(value, 4026531984u, 4093640847u))
                    {
                        if (outputCharsRemaining < 2)
{
                            break;
                        }
                        Unsafe.WriteUnaligned(pOutputBuffer, ExtractCharsFromFourByteSequence(num2));
                        pInputBuffer += 4;
                        pOutputBuffer += 2;
                        outputCharsRemaining -= 2;
                        goto IL_04aa;
                    }
                }
                goto IL_06a3;
                IL_0282:
                if (outputCharsRemaining >= 3)
                {
                    *pOutputBuffer = (char)num9;
                    _ = BitConverter.IsLittleEndian;
                    num2 >>= 16;
                    pOutputBuffer[1] = (char)(byte)num2;
                    num2 >>= 8;
                    pOutputBuffer[2] = (char)num2;
                    pInputBuffer += 4;
                    pOutputBuffer += 3;
                    outputCharsRemaining -= 3;
                    goto IL_04aa;
                }
                goto IL_04b1;
                IL_00f4:
                if (ASCIIUtility.AllBytesInUInt32AreAscii(num2))
                {
                    ASCIIUtility.WidenFourAsciiBytesToUtf16AndWriteToBuffer(ref *pOutputBuffer, num2);
                    num2 = num5;
                    pInputBuffer += 4;
                    pOutputBuffer += 4;
                    outputCharsRemaining -= 4;
                }
                outputCharsRemaining -= 8 * num4;
                goto IL_0120;
                continue;
                end_IL_0051:
                break;
            }
            break;
        }
        goto IL_069f;
        IL_06a3:
        OperationStatus result = OperationStatus.InvalidData;
        goto IL_06a5;
        IL_069f:
        result = OperationStatus.DestinationTooSmall;
        goto IL_06a5;
        IL_06a5:
        pInputBufferRemaining = pInputBuffer;
        pOutputBufferRemaining = pOutputBuffer;
        return result;
        IL_0690:
        while (true)
        {
            if (inputLength > 0)
            {
                uint num13 = *pInputBuffer;
                if (num13 <= 127)
                {
                    if (outputCharsRemaining != 0)
                    {
                        *pOutputBuffer = (char)num13;
                        pInputBuffer++;
                        pOutputBuffer++;
                        inputLength--;
                        outputCharsRemaining--;
                        continue;
                    }
                    goto IL_069f;
                }
                num13 -= 194;
                if ((uint)(byte)num13 <= 29u)
                {
                    if (inputLength < 2)
                    {
                        goto IL_069b;
                    }
                    uint num14 = pInputBuffer[1];
                    if (IsLowByteUtf8ContinuationByte(num14))
                    {
                        if (outputCharsRemaining != 0)
{
                            uint num15 = (num13 << 6) + num14 + 128 - 128;
                            *pOutputBuffer = (char)num15;
                            pInputBuffer += 2;
                            pOutputBuffer++;
                            inputLength -= 2;
                            outputCharsRemaining--;
                            continue;
                        }
                        goto IL_069f;
                    }
                }
                else if ((uint)(byte)num13 <= 45u)
                {
                    if (inputLength >= 3)
                    {
                        uint num16 = pInputBuffer[1];
                        uint num17 = pInputBuffer[2];
                        if (IsLowByteUtf8ContinuationByte(num16) && IsLowByteUtf8ContinuationByte(num17))
{
                            uint num18 = (num13 << 12) + (num16 << 6);
                            if (num18 >= 133120)
{
                                num18 -= 186368;
                                if (num18 >= 2048)
{
                                    if (outputCharsRemaining != 0)
{
                                        num18 += num17;
                                        num18 += 55296;
                                        num18 -= 128;
                                        *pOutputBuffer = (char)num18;
                                        pInputBuffer += 3;
                                        pOutputBuffer++;
                                        inputLength -= 3;
                                        outputCharsRemaining--;
                                        continue;
                                    }
                                    goto IL_069f;
                                }
                            }
                        }
                    }
                    else
                    {
                        if (inputLength < 2)
{
                            goto IL_069b;
                        }
                        uint num19 = pInputBuffer[1];
                        if (IsLowByteUtf8ContinuationByte(num19))
{
                            uint num20 = (num13 << 6) + num19;
                            if (num20 >= 2080 && !UnicodeUtility.IsInRangeInclusive(num20, 2912u, 2943u))
{
                                goto IL_069b;
                            }
                        }
                    }
                }
                else if ((uint)(byte)num13 <= 50u)
                {
                    if (inputLength < 2)
                    {
                        goto IL_069b;
                    }
                    uint num21 = pInputBuffer[1];
                    if (IsLowByteUtf8ContinuationByte(num21))
                    {
                        uint value2 = (num13 << 6) + num21;
                        if (UnicodeUtility.IsInRangeInclusive(value2, 3088u, 3343u))
{
                            if (inputLength < 3)
{
                                goto IL_069b;
                            }
                            if (IsLowByteUtf8ContinuationByte(pInputBuffer[2]))
{
                                if (inputLength < 4)
{
                                    goto IL_069b;
                                }
                                if (IsLowByteUtf8ContinuationByte(pInputBuffer[3]))
{
                                    goto IL_069f;
                                }
                            }
                        }
                    }
                }
                goto IL_06a3;
            }
            result = OperationStatus.Done;
            break;
            IL_069b:
            result = OperationStatus.NeedMoreData;
            break;
        }
        goto IL_06a5;
    }
References System.Text.ASCIIUtility.AllBytesInUInt32AreAscii(), System.Text.Unicode.Utf8Utility.ExtractCharFromFirstThreeByteSequence(), System.Text.Unicode.Utf8Utility.ExtractCharFromFirstTwoByteSequence(), System.Text.Unicode.Utf8Utility.ExtractCharsFromFourByteSequence(), System.Text.Unicode.Utf8Utility.ExtractTwoCharsPackedFromTwoAdjacentTwoByteSequences(), System.Text.UnicodeUtility.IsInRangeInclusive(), System.BitConverter.IsLittleEndian, System.Text.Unicode.Utf8Utility.IsLowByteUtf8ContinuationByte(), System.Math.Min(), System.Numerics.BitOperations.RotateRight(), System.Text.Unicode.Utf8Utility.ToLittleEndian(), System.Text.Unicode.Utf8Utility.UInt32BeginsWithOverlongUtf8TwoByteSequence(), System.Text.Unicode.Utf8Utility.UInt32BeginsWithUtf8FourByteMask(), System.Text.Unicode.Utf8Utility.UInt32BeginsWithUtf8ThreeByteMask(), System.Text.Unicode.Utf8Utility.UInt32BeginsWithUtf8TwoByteMask(), System.Text.Unicode.Utf8Utility.UInt32BeginsWithValidUtf8TwoByteSequenceLittleEndian(), System.Text.Unicode.Utf8Utility.UInt32EndsWithValidUtf8TwoByteSequenceLittleEndian(), System.Text.Unicode.Utf8Utility.UInt32FirstByteIsAscii(), System.Text.Unicode.Utf8Utility.UInt32FourthByteIsAscii(), System.Text.Unicode.Utf8Utility.UInt32SecondByteIsAscii(), System.Text.Unicode.Utf8Utility.UInt32ThirdByteIsAscii(), System.value, System.Text.ASCIIUtility.WidenAsciiToUtf16(), and System.Text.ASCIIUtility.WidenFourAsciiBytesToUtf16AndWriteToBuffer().
Referenced by System.Text.UTF8Encoding.GetCharsFast(), and System.Text.Unicode.Utf8.ToUtf16().