Terraria: System.Text.Unicode.Utf8Utility.ExtractFourUtf8BytesFromSurrogatePair
ExtractFourUtf8BytesFromSurrogatePair()
static uint System.Text.Unicode.Utf8Utility.ExtractFourUtf8BytesFromSurrogatePair (uint value) inline static private
Definition at line 45 of file Utf8Utility.cs.
    {
        _ = BitConverter.IsLittleEndian;
        value += 64;
        uint value2 = BinaryPrimitives.ReverseEndianness(value & 0x3F0700u);
        value2 = BitOperations.RotateLeft(value2, 16);
        uint num = (value & 0xFC) << 6;
        uint num2 = (value >> 6) & 0xF0000u;
        num2 |= num;
        uint num3 = (value & 3) << 20;
        num3 |= 0x808080F0u;
        return num3 | value2 | num2;
    }
References System.BitConverter.IsLittleEndian, System.Buffers.Binary.BinaryPrimitives.ReverseEndianness(), System.Numerics.BitOperations.RotateLeft(), and System.value.
Referenced by System.Text.Unicode.Utf8Utility.TranscodeToUtf8().