Terraria: System.Linq.EnumerableSorter.CompareKeys
CompareKeys()
int System.Linq.EnumerableSorter< TElement, TKey >.CompareKeys (int index1, int index2) inline private
Definition at line 102 of file EnumerableSorter.cs.
    {
        if (index1 != index2)
        {
            return CompareAnyKeys(index1, index2);
        }
        return 0;
    }
References System.Linq.EnumerableSorter< TElement, TKey >.CompareAnyKeys(), System.index1, and System.index2.
Referenced by System.Linq.EnumerableSorter< TElement, TKey >.Min(), System.Linq.EnumerableSorter< TElement, TKey >.PartialQuickSort(), and System.Linq.EnumerableSorter< TElement, TKey >.QuickSelect().