Terraria: System.Text.EncoderFallbackBuffer.Reset
Reset()
virtual void System.Text.EncoderFallbackBuffer.Reset () inline virtual
Reimplemented in System.Text.EncoderLatin1BestFitFallbackBuffer, System.Text.EncoderReplacementFallbackBuffer, System.Xml.CharEntityEncoderFallbackBuffer, and System.Text.InternalEncoderBestFitFallbackBuffer.
Definition at line 36 of file EncoderFallbackBuffer.cs.
    {
        while (GetNextChar() != 0)
        {
        }
    }
References System.Text.EncoderFallbackBuffer.GetNextChar().
Referenced by System.Text.EncoderFallbackBuffer.InternalReset(), System.Text.EncoderFallbackBufferHelper.InternalReset(), System.Text.Encoder.Reset(), System.Text.EncoderNLS.Reset(), System.Text.UTF7Encoding.Encoder.Reset(), System.Text.ISCIIEncoding.ISCIIEncoder.Reset(), and System.Text.ISO2022Encoding.ISO2022Encoder.Reset().