Terraria: System.Text.EncoderFallbackBuffer.CreateAndInitialize
CreateAndInitialize()
static EncoderFallbackBuffer System.Text.EncoderFallbackBuffer.CreateAndInitialize (Encoding encoding, EncoderNLS encoder, int originalCharCount) inline static package inherited
Definition at line 62 of file EncoderFallbackBuffer.cs.
    {
        EncoderFallbackBuffer encoderFallbackBuffer = ((encoder == null) ? encoding.EncoderFallback.CreateFallbackBuffer() : encoder.FallbackBuffer);
        encoderFallbackBuffer.encoding = encoding;
        encoderFallbackBuffer.encoder = encoder;
        encoderFallbackBuffer.originalCharCount = originalCharCount;
        return encoderFallbackBuffer;
    }
References System.Text.EncoderFallback.CreateFallbackBuffer(), System.Text.EncoderFallbackBuffer.encoder, System.Text.Encoding.EncoderFallback, System.Text.EncoderFallbackBuffer.encoding, System.Text.EncoderNLS.FallbackBuffer, and System.Text.EncoderFallbackBuffer.originalCharCount.
Referenced by System.Text.Encoding.GetByteCountWithFallback(), and System.Text.Encoding.GetBytesWithFallback().