Terraria: System.Security.Cryptography.ECDiffieHellmanCngPublicKey.ExportParameters
ExportParameters()
override ECParameters System.Security.Cryptography.ECDiffieHellmanCngPublicKey.ExportParameters () inline virtual
Reimplemented from System.Security.Cryptography.ECDiffieHellmanPublicKey.
Definition at line 83 of file ECDiffieHellmanCngPublicKey.cs.
    {
        using CngKey cngKey = Import();
        ECParameters ecParams = default(ECParameters);
        string oidValue;
        string curveName = cngKey.GetCurveName(out oidValue);
        if (string.IsNullOrEmpty(curveName))
        {
            byte[] ecBlob = System.Security.Cryptography.ECCng.ExportFullKeyBlob(cngKey, includePrivateParameters: false);
            System.Security.Cryptography.ECCng.ExportPrimeCurveParameters(ref ecParams, ecBlob, includePrivateParameters: false);
        }
        else
        {
            byte[] ecBlob2 = System.Security.Cryptography.ECCng.ExportKeyBlob(cngKey, includePrivateParameters: false);
            System.Security.Cryptography.ECCng.ExportNamedCurveParameters(ref ecParams, ecBlob2, includePrivateParameters: false);
            ecParams.Curve = ECCurve.CreateFromFriendlyName(curveName);
        }
        return ecParams;
    }
References System.Security.Cryptography.ECCurve.CreateFromFriendlyName(), System.Security.Cryptography.ECCng.ExportFullKeyBlob(), System.Security.Cryptography.ECCng.ExportKeyBlob(), System.Security.Cryptography.ECCng.ExportNamedCurveParameters(), System.Security.Cryptography.ECCng.ExportPrimeCurveParameters(), and System.Security.Cryptography.ECDiffieHellmanCngPublicKey.Import().