Terraria: System.Security.Cryptography.ECDiffieHellmanCngPublicKey.Import
Import()
CngKey System.Security.Cryptography.ECDiffieHellmanCngPublicKey.Import () inline
Definition at line 65 of file ECDiffieHellmanCngPublicKey.cs.
    {
        if (_disposed)
        {
            throw new ObjectDisposedException("ECDiffieHellmanCngPublicKey");
        }
        return CngKey.Import(ToByteArray(), _curveName, BlobFormat);
    }
References System.Security.Cryptography.ECDiffieHellmanCngPublicKey._curveName, System.Security.Cryptography.ECDiffieHellmanCngPublicKey._disposed, System.Security.Cryptography.ECDiffieHellmanCngPublicKey.BlobFormat, System.Security.Cryptography.CngKey.Import(), and System.Security.Cryptography.ECDiffieHellmanPublicKey.ToByteArray().
Referenced by System.Security.Cryptography.ECDiffieHellmanCng.DeriveKeyMaterial(), System.Security.Cryptography.ECDiffieHellmanCng.DeriveSecretAgreementHandle(), System.Security.Cryptography.ECDiffieHellmanCngPublicKey.ExportExplicitParameters(), and System.Security.Cryptography.ECDiffieHellmanCngPublicKey.ExportParameters().