Terraria: System.Data.DataExpression.Bind
Bind()
void System.Data.DataExpression.Bind (DataTable table) inline package
Definition at line 76 of file DataExpression.cs.
    {
        _table = table;
        if (table != null && _expr != null)
        {
            List<DataColumn> list = new List<DataColumn>();
            _expr.Bind(table, list);
            _expr = _expr.Optimize();
            _table = table;
            _bound = true;
            _dependency = list.ToArray();
        }
    }
References System.Data.DataExpression._bound, System.Data.DataExpression._dependency, System.Data.DataExpression._expr, System.Data.DataExpression._table, System.Data.ExpressionNode.Bind(), System.list, and System.Data.ExpressionNode.Optimize().
Referenced by System.Data.DataExpression.DataExpression(), System.Data.DataColumn.BindExpression(), System.Data.DataExpression.Evaluate(), System.Data.DataExpression.Evaluate(), and System.Data.DataColumn.SetTable().