Terraria: System.Data.DataExpression.Evaluate
Evaluate() [2/4]
object System.Data.DataExpression.Evaluate (DataRow row, DataRowVersion version) inline package
Definition at line 105 of file DataExpression.cs.
    {
        if (!_bound)
        {
            Bind(_table);
        }
        object obj;
        if (_expr != null)
        {
            obj = _expr.Eval(row, version);
            if (obj != DBNull.Value || StorageType.Uri < _storageType)
            {
                try
                {
                    if (StorageType.Object != _storageType)
                    {
                        obj = SqlConvert.ChangeType2(obj, _storageType, _dataType, _table.FormatProvider);
                    }
                }
                catch (Exception ex) when (ADP.IsCatchableExceptionType(ex))
                {
                    ExceptionBuilder.TraceExceptionForCapture(ex);
                    throw ExprException.DatavalueConvertion(obj, _dataType, ex);
                }
            }
        }
        else
        {
            obj = null;
        }
        return obj;
    }
References System.Data.DataExpression._bound, System.Data.DataExpression._dataType, System.Data.DataExpression._expr, System.Data.DataExpression._storageType, System.Data.DataExpression._table, System.Data.DataExpression.Bind(), System.Data.Common.SqlConvert.ChangeType2(), System.Data.ExprException.DatavalueConvertion(), System.Data.ExpressionNode.Eval(), System.Data.DataTable.FormatProvider, System.Data.Common.ADP.IsCatchableExceptionType(), System.obj, System.Data.ExceptionBuilder.TraceExceptionForCapture(), and System.DBNull.Value.