Terraria: System.Data.DataExpression.Invoke
Invoke()
bool System.Data.DataExpression.Invoke (DataRow row, DataRowVersion version) inline
Implements System.Data.IFilter.
Definition at line 167 of file DataExpression.cs.
    {
        if (_expr == null)
        {
            return true;
        }
        if (row == null)
        {
            throw ExprException.InvokeArgument();
        }
        object value = _expr.Eval(row, version);
        try
        {
            return ToBoolean(value);
        }
        catch (EvaluateException)
        {
            throw ExprException.FilterConvertion(Expression);
        }
    }
References System.Data.DataExpression._expr, System.Data.ExpressionNode.Eval(), System.Data.DataExpression.Expression, System.Data.ExprException.FilterConvertion(), System.Data.ExprException.InvokeArgument(), System.Data.DataExpression.ToBoolean(), and System.value.