Terraria: System.Data.DataExpression.ToBoolean
ToBoolean()
static bool System.Data.DataExpression.ToBoolean (object value) inline static package
Definition at line 225 of file DataExpression.cs.
    {
        if (IsUnknown(value))
        {
            return false;
        }
        if (value is bool)
        {
            return (bool)value;
        }
        if (value is SqlBoolean sqlBoolean)
        {
            return sqlBoolean.IsTrue;
        }
        if (value is string)
        {
            try
            {
                return bool.Parse((string)value);
            }
            catch (Exception ex) when (ADP.IsCatchableExceptionType(ex))
            {
                ExceptionBuilder.TraceExceptionForCapture(ex);
                throw ExprException.DatavalueConvertion(value, typeof(bool), ex);
            }
        }
        throw ExprException.DatavalueConvertion(value, typeof(bool), null);
    }
References System.Data.ExprException.DatavalueConvertion(), System.Data.Common.ADP.IsCatchableExceptionType(), System.Data.DataExpression.IsUnknown(), System.Data.ExceptionBuilder.TraceExceptionForCapture(), and System.value.
Referenced by System.Data.Select.AcceptRecord(), System.Data.BinaryNode.BinaryCompare(), System.Data.FunctionNode.EvalFunction(), System.Data.UnaryNode.EvalUnaryOp(), and System.Data.DataExpression.Invoke().