Terraria: System.Linq.Expressions.Error.CollectionReadOnly
CollectionReadOnly()
static Exception System.Linq.Expressions.Error.CollectionReadOnly () inline static package
Definition at line 43 of file Error.cs.
    {
        return new NotSupportedException(Strings.CollectionReadOnly);
    }
References System.Linq.Expressions.Strings.CollectionReadOnly.
Referenced by System.Dynamic.ExpandoObject.ValueCollection.Add(), System.Dynamic.ExpandoObject.KeyCollection.Add(), System.Dynamic.ExpandoObject.KeyCollection.Clear(), System.Dynamic.ExpandoObject.ValueCollection.Clear(), System.Dynamic.ExpandoObject.ValueCollection.Remove(), and System.Dynamic.ExpandoObject.KeyCollection.Remove().