Terraria: System.Linq.Expressions.Error.BinaryOperatorNotDefined
BinaryOperatorNotDefined()
static Exception System.Linq.Expressions.Error.BinaryOperatorNotDefined (object p0, object p1, object p2) inline static package
Definition at line 303 of file Error.cs.
    {
        return new InvalidOperationException(Strings.BinaryOperatorNotDefined(p0, p1, p2));
    }
References System.Linq.Expressions.Strings.BinaryOperatorNotDefined().
Referenced by System.Linq.Expressions.Expression< TDelegate >.AndAlso(), System.Linq.Expressions.Expression< TDelegate >.GetEqualityComparisonOperator(), System.Linq.Expressions.Expression< TDelegate >.GetUserDefinedBinaryOperatorOrThrow(), System.Linq.Expressions.Expression< TDelegate >.OrElse(), System.Linq.Expressions.Expression< TDelegate >.Power(), and System.Linq.Expressions.Expression< TDelegate >.PowerAssign().