Terraria: System.Linq.Expressions.Error.MustRewriteWithoutMethod
MustRewriteWithoutMethod()
static Exception System.Linq.Expressions.Error.MustRewriteWithoutMethod (object p0, object p1) inline static package
Definition at line 793 of file Error.cs.
    {
        return new InvalidOperationException(Strings.MustRewriteWithoutMethod(p0, p1));
    }
References System.Linq.Expressions.Strings.MustRewriteWithoutMethod().
Referenced by System.Linq.Expressions.ExpressionVisitor.ValidateBinary(), System.Linq.Expressions.ExpressionVisitor.ValidateSwitch(), and System.Linq.Expressions.ExpressionVisitor.ValidateUnary().