Terraria: System.Linq.Expressions.Error.GetParamName
GetParamName()
static string System.Linq.Expressions.Error.GetParamName (string paramName, int index) inline static private
Definition at line 943 of file Error.cs.
    {
        if (index >= 0)
        {
            return $"{paramName}[{index}]";
        }
        return paramName;
    }
References System.Linq.index.
Referenced by System.Linq.Expressions.Error.AccessorsCannotHaveByRefArgs(), System.Linq.Expressions.Error.ArgumentMemberNotDeclOnType(), System.Linq.Expressions.Error.ArgumentMustBeArrayIndexType(), System.Linq.Expressions.Error.ArgumentMustBeFieldInfoOrPropertyInfoOrMethod(), System.Linq.Expressions.Error.ArgumentMustBeInstanceMember(), System.Linq.Expressions.Error.ArgumentMustBeInteger(), System.Linq.Expressions.Error.ArgumentTypeDoesNotMatchMember(), System.Linq.Expressions.Error.DuplicateVariable(), System.Linq.Expressions.Error.ExpressionMustBeReadable(), System.Linq.Expressions.Error.ExpressionTypeDoesNotMatchConstructorParameter(), System.Linq.Expressions.Error.ExpressionTypeDoesNotMatchMethodParameter(), System.Linq.Expressions.Error.ExpressionTypeDoesNotMatchParameter(), System.Linq.Expressions.Error.MethodNotPropertyAccessor(), System.Linq.Expressions.Error.NotAMemberOfType(), System.Linq.Expressions.Error.PropertyDoesNotHaveGetter(), System.Linq.Expressions.Error.TypeContainsGenericParameters(), System.Linq.Expressions.Error.TypeIsGeneric(), and System.Linq.Expressions.Error.VariableMustNotBeByRef().