Terraria: System.Linq.Expressions.Error.ArgumentTypesMustMatch
ArgumentTypesMustMatch() [1/2]
static Exception System.Linq.Expressions.Error.ArgumentTypesMustMatch () inline static package
Definition at line 398 of file Error.cs.
    {
        return new ArgumentException(Strings.ArgumentTypesMustMatch);
    }
References System.Linq.Expressions.Strings.ArgumentTypesMustMatch.
Referenced by System.Linq.Expressions.Expression< TDelegate >.Bind(), System.Linq.Expressions.Expression< TDelegate >.BlockCore(), System.Linq.Expressions.Expression< TDelegate >.Condition(), System.Linq.Expressions.Expression< TDelegate >.Condition(), System.Linq.Expressions.Expression< TDelegate >.Constant(), System.Linq.Expressions.Expression< TDelegate >.ValidateCoalesceArgTypes(), System.Linq.Expressions.Expression< TDelegate >.ValidateSwitchCaseType(), and System.Linq.Expressions.Expression< TDelegate >.ValidateTryAndCatchHaveSameType().