Terraria: DSTFilm.CreateChester
CreateChester()
void DSTFilm.CreateChester (FrameEventData evt) inline private
     {
         FindFloorAt(_startPoint + new Vector2(110f, 0f), out var x, out var y);
         y -= 240;
         int num = Projectile.NewProjectile(null, x, y, 0f, 0f, 960, 0, 0f, Main.myPlayer, -1f);
         _chester = Main.projectile[num];
         _chester.velocity.Y = 4f;
         _chester.velocity.X = 6f;
     }
References _chester, _startPoint, FindFloorAt(), Main.myPlayer, Projectile.NewProjectile(), Main.projectile, and Entity.velocity.
Referenced by BuildSequence().