Terraria: DSTFilm.BuildSequence
BuildSequence()
void DSTFilm.BuildSequence () inline private
     {
         AppendKeyFrames(EquipDSTShaderItem);
         AppendEmptySequence(60);
         AppendKeyFrames(CreateDeerclops, CreateChester, ControlPlayer);
         AppendEmptySequence(60);
         AppendEmptySequence(187);
         AppendKeyFrames(StopBeforeCliff);
         AppendEmptySequence(20);
         AppendKeyFrames(TurnPlayerToTheLeft);
         AppendEmptySequence(20);
         AppendKeyFrames(DeerclopsAttack);
         AppendEmptySequence(60);
         AppendKeyFrames(RemoveDSTShaderItem);
     }
References Film.AppendEmptySequence(), Film.AppendKeyFrames(), ControlPlayer(), CreateChester(), CreateDeerclops(), DeerclopsAttack(), EquipDSTShaderItem(), RemoveDSTShaderItem(), StopBeforeCliff(), and TurnPlayerToTheLeft().
Referenced by DSTFilm().