Terraria: DSTFilm.PlaceNPCOnGround
PlaceNPCOnGround()
NPC DSTFilm.PlaceNPCOnGround (int type, Vector2 position) inline private
     {
         FindFloorAt(position, out var x, out var y);
         if (type == 668)
         {
             y -= 240;
         }
         int start = 100;
         int num = NPC.NewNPC(new EntitySource_Film(), x, y, type, start);
         return Main.npc[num];
     }
References FindFloorAt(), NPC.NewNPC(), and Main.npc.
Referenced by CreateDeerclops().