Terraria: Main.OnSubmitServerIP
OnSubmitServerIP()
static void Main.OnSubmitServerIP (string inputText) inline static
     {
         getIP = inputText;
         SoundEngine.PlaySound(12);
         menuMode = 131;
         clrInput();
     }
References clrInput(), getIP, inputText, menuMode, and SoundEngine.PlaySound().
Referenced by DrawMenu().