Terraria: Main.FixUIScale
FixUIScale()
static void Main.FixUIScale () inline static
     {
         UIScale = UIScaleWanted;
     }
References UIScale, and UIScaleWanted.
Referenced by MessageBuffer.GetData(), WorldGen.Hooks.Initialize(), SetDisplayMode(), and UpdateWorldPreparationState().