Terraria: Main.DrawInvasionProgress
DrawInvasionProgress()
static void Main.DrawInvasionProgress () inline static
     {
         if (invasionProgress == -1)
         {
             return;
         }
         if (invasionProgressMode == 2 && invasionProgressNearInvasion && invasionProgressDisplayLeft < 160)
         {
             invasionProgressDisplayLeft = 160;
         }
         if (!gamePaused && invasionProgressDisplayLeft > 0)
         {
             invasionProgressDisplayLeft--;
         }
         if (invasionProgressDisplayLeft > 0)
         {
             invasionProgressAlpha += 0.05f;
         }
         else
         {
             invasionProgressAlpha -= 0.05f;
         }
         if (invasionProgressMode == 0)
         {
             invasionProgressDisplayLeft = 0;
             invasionProgressAlpha = 0f;
         }
         if (invasionProgressAlpha < 0f)
         {
             invasionProgressAlpha = 0f;
         }
         if (invasionProgressAlpha > 1f)
         {
             invasionProgressAlpha = 1f;
         }
         if (invasionProgressAlpha <= 0f)
         {
             return;
         }
         float num = 0.5f + invasionProgressAlpha * 0.5f;
         Texture2D value = TextureAssets.Extra[9].Value;
         string text = "";
         Microsoft.Xna.Framework.Color c = Microsoft.Xna.Framework.Color.White;
         if (invasionProgressIcon == 1)
         {
             value = TextureAssets.Extra[8].Value;
             text = Lang.inter[83].Value;
             c = new Microsoft.Xna.Framework.Color(64, 109, 164) * 0.5f;
         }
         else if (invasionProgressIcon == 2)
         {
             value = TextureAssets.Extra[12].Value;
             text = Lang.inter[84].Value;
             c = new Microsoft.Xna.Framework.Color(112, 86, 114) * 0.5f;
         }
         else if (invasionProgressIcon == 3)
         {
             value = TextureAssets.Extra[79].Value;
             text = Language.GetTextValue("DungeonDefenders2.InvasionProgressTitle");
             c = new Microsoft.Xna.Framework.Color(88, 0, 160) * 0.5f;
         }
         else if (invasionProgressIcon == 7)
         {
             value = TextureAssets.Extra[10].Value;
             text = Lang.inter[85].Value;
             c = new Microsoft.Xna.Framework.Color(165, 160, 155) * 0.5f;
         }
         else if (invasionProgressIcon == 6)
         {
             value = TextureAssets.Extra[11].Value;
             text = Lang.inter[86].Value;
             c = new Microsoft.Xna.Framework.Color(148, 122, 72) * 0.5f;
         }
         else if (invasionProgressIcon == 5)
         {
             value = TextureAssets.Extra[7].Value;
             text = Lang.inter[87].Value;
             c = new Microsoft.Xna.Framework.Color(173, 135, 140) * 0.5f;
         }
         else if (invasionProgressIcon == 4)
         {
             value = TextureAssets.Extra[9].Value;
             text = Lang.inter[88].Value;
             c = new Microsoft.Xna.Framework.Color(94, 72, 131) * 0.5f;
         }
         if (invasionProgressWave > 0)
         {
             int num2 = (int)(200f * num);
             int num3 = (int)(45f * num);
             Vector2 vector = new Vector2(screenWidth - 120, screenHeight - 40);
             Utils.DrawInvBG(R: new Microsoft.Xna.Framework.Rectangle((int)vector.X - num2 / 2, (int)vector.Y - num3 / 2, num2, num3), sb: spriteBatch, c: new Microsoft.Xna.Framework.Color(63, 65, 151, 255) * 0.785f);
             string text2 = "";
             text2 = Language.GetTextValue(arg1: (invasionProgressMax != 0) ? ((int)((float)invasionProgress * 100f / (float)invasionProgressMax) + "%") : Language.GetTextValue("Game.InvasionPoints", invasionProgress), key: "Game.WaveMessage", arg0: invasionProgressWave);
             Texture2D value2 = TextureAssets.ColorBar.Value;
             _ = TextureAssets.ColorBlip.Value;
             float num4 = MathHelper.Clamp((float)invasionProgress / (float)invasionProgressMax, 0f, 1f);
             if (invasionProgressMax == 0)
             {
                 num4 = 1f;
             }
             float num5 = 169f * num;
             float num6 = 8f * num;
             Vector2 vector2 = vector + Vector2.UnitY * num6 + Vector2.UnitX * 1f;
             Utils.DrawBorderString(spriteBatch, text2, vector2, Microsoft.Xna.Framework.Color.White * invasionProgressAlpha, num, 0.5f, 1f);
             spriteBatch.Draw(value2, vector, null, Microsoft.Xna.Framework.Color.White * invasionProgressAlpha, 0f, new Vector2(value2.Width / 2, 0f), num, SpriteEffects.None, 0f);
             vector2 += Vector2.UnitX * (num4 - 0.5f) * num5;
             spriteBatch.Draw(TextureAssets.MagicPixel.Value, vector2, new Microsoft.Xna.Framework.Rectangle(0, 0, 1, 1), new Microsoft.Xna.Framework.Color(255, 241, 51) * invasionProgressAlpha, 0f, new Vector2(1f, 0.5f), new Vector2(num5 * num4, num6), SpriteEffects.None, 0f);
             spriteBatch.Draw(TextureAssets.MagicPixel.Value, vector2, new Microsoft.Xna.Framework.Rectangle(0, 0, 1, 1), new Microsoft.Xna.Framework.Color(255, 165, 0, 127) * invasionProgressAlpha, 0f, new Vector2(1f, 0.5f), new Vector2(2f, num6), SpriteEffects.None, 0f);
             spriteBatch.Draw(TextureAssets.MagicPixel.Value, vector2, new Microsoft.Xna.Framework.Rectangle(0, 0, 1, 1), Microsoft.Xna.Framework.Color.Black * invasionProgressAlpha, 0f, new Vector2(0f, 0.5f), new Vector2(num5 * (1f - num4), num6), SpriteEffects.None, 0f);
         }
         else
         {
             int num7 = (int)(200f * num);
             int num8 = (int)(45f * num);
             Vector2 vector3 = new Vector2(screenWidth - 120, screenHeight - 40);
             Utils.DrawInvBG(R: new Microsoft.Xna.Framework.Rectangle((int)vector3.X - num7 / 2, (int)vector3.Y - num8 / 2, num7, num8), sb: spriteBatch, c: new Microsoft.Xna.Framework.Color(63, 65, 151, 255) * 0.785f);
             string text3 = "";
             text3 = ((invasionProgressMax != 0) ? ((int)((float)invasionProgress * 100f / (float)invasionProgressMax) + "%") : invasionProgress.ToString());
             text3 = Language.GetTextValue("Game.WaveCleared", text3);
             Texture2D value3 = TextureAssets.ColorBar.Value;
             _ = TextureAssets.ColorBlip.Value;
             if (invasionProgressMax != 0)
             {
                 spriteBatch.Draw(value3, vector3, null, Microsoft.Xna.Framework.Color.White * invasionProgressAlpha, 0f, new Vector2(value3.Width / 2, 0f), num, SpriteEffects.None, 0f);
                 float num9 = MathHelper.Clamp((float)invasionProgress / (float)invasionProgressMax, 0f, 1f);
                 Vector2 vector4 = FontAssets.MouseText.Value.MeasureString(text3);
                 float num10 = num;
                 if (vector4.Y > 22f)
                 {
                     num10 *= 22f / vector4.Y;
                 }
                 float num11 = 169f * num;
                 float num12 = 8f * num;
                 Vector2 vector5 = vector3 + Vector2.UnitY * num12 + Vector2.UnitX * 1f;
                 Utils.DrawBorderString(spriteBatch, text3, vector5 + new Vector2(0f, -4f), Microsoft.Xna.Framework.Color.White * invasionProgressAlpha, num10, 0.5f, 1f);
                 vector5 += Vector2.UnitX * (num9 - 0.5f) * num11;
                 spriteBatch.Draw(TextureAssets.MagicPixel.Value, vector5, new Microsoft.Xna.Framework.Rectangle(0, 0, 1, 1), new Microsoft.Xna.Framework.Color(255, 241, 51) * invasionProgressAlpha, 0f, new Vector2(1f, 0.5f), new Vector2(num11 * num9, num12), SpriteEffects.None, 0f);
                 spriteBatch.Draw(TextureAssets.MagicPixel.Value, vector5, new Microsoft.Xna.Framework.Rectangle(0, 0, 1, 1), new Microsoft.Xna.Framework.Color(255, 165, 0, 127) * invasionProgressAlpha, 0f, new Vector2(1f, 0.5f), new Vector2(2f, num12), SpriteEffects.None, 0f);
                 spriteBatch.Draw(TextureAssets.MagicPixel.Value, vector5, new Microsoft.Xna.Framework.Rectangle(0, 0, 1, 1), Microsoft.Xna.Framework.Color.Black * invasionProgressAlpha, 0f, new Vector2(0f, 0.5f), new Vector2(num11 * (1f - num9), num12), SpriteEffects.None, 0f);
             }
         }
         Vector2 vector6 = FontAssets.MouseText.Value.MeasureString(text);
         float num13 = 120f;
         if (vector6.X > 200f)
         {
             num13 += vector6.X - 200f;
         }
         Microsoft.Xna.Framework.Rectangle r3 = Utils.CenteredRectangle(new Vector2((float)screenWidth - num13, screenHeight - 80), (vector6 + new Vector2(value.Width + 12, 6f)) * num);
         Utils.DrawInvBG(spriteBatch, r3, c);
         spriteBatch.Draw(value, r3.Left() + Vector2.UnitX * num * 8f, null, Microsoft.Xna.Framework.Color.White * invasionProgressAlpha, 0f, new Vector2(0f, value.Height / 2), num * 0.8f, SpriteEffects.None, 0f);
         Utils.DrawBorderString(spriteBatch, text, r3.Right() + Vector2.UnitX * num * -22f, Microsoft.Xna.Framework.Color.White * invasionProgressAlpha, num * 0.9f, 1f, 0.4f);
     }
References Utils.CenteredRectangle(), TextureAssets.ColorBar, TextureAssets.ColorBlip, Utils.DrawBorderString(), Utils.DrawInvBG(), TextureAssets.Extra, gamePaused, Language.GetTextValue(), Lang.inter, invasionProgress, invasionProgressAlpha, invasionProgressDisplayLeft, invasionProgressIcon, invasionProgressMax, invasionProgressMode, invasionProgressNearInvasion, invasionProgressWave, TextureAssets.MagicPixel, FontAssets.MouseText, R, screenHeight, screenWidth, spriteBatch, Asset< T >.Value, and LocalizedText.Value.
Referenced by DrawInterface_15_InvasionProgressBars().