Terraria: Main.DoUpdate_F9_ToggleLighting
DoUpdate_F9_ToggleLighting()
static void Main.DoUpdate_F9_ToggleLighting () inline static private
     {
         if (keyState.PressingShift() && keyState.IsKeyDown(Microsoft.Xna.Framework.Input.Keys.F9) && !drawingPlayerChat && !editSign && !editChest)
         {
             if (RGBRelease)
             {
                 SoundEngine.PlaySound(12);
                 Lighting.NextLightMode();
             }
             RGBRelease = false;
         }
         else
         {
             RGBRelease = true;
         }
     }
References drawingPlayerChat, editChest, editSign, keyState, Lighting.NextLightMode(), SoundEngine.PlaySound(), and RGBRelease.
Referenced by DoUpdate().