Terraria: Main.TryRemovingBuff
TryRemovingBuff()
static void Main.TryRemovingBuff (int i, int b) inline static
     {
         bool flag = false;
         if (!debuff[b] && b != 60 && b != 151)
         {
             if (player[myPlayer].mount.Active && player[myPlayer].mount.CheckBuff(b))
             {
                 player[myPlayer].mount.Dismount(player[myPlayer]);
                 flag = true;
             }
             TryRemovingBuff_CheckBuffHideMisc(0, b);
             TryRemovingBuff_CheckBuffHideMisc(1, b);
             SoundEngine.PlaySound(12);
             if (!flag)
             {
                 player[myPlayer].DelBuff(i);
             }
         }
     }
References Mount.CheckBuff(), debuff, Player.DelBuff(), Mount.Dismount(), Player.mount, myPlayer, player, SoundEngine.PlaySound(), and TryRemovingBuff_CheckBuffHideMisc().
Referenced by DrawBuffIcon().