Terraria: Main.DrawGamepadInstructions
DrawGamepadInstructions()
static void Main.DrawGamepadInstructions () inline static
     {
         if (drawingPlayerChat || !PlayerInput.SettingsForUI.ShowGamepadHints)
         {
             return;
         }
         string text = PlayerInput.ComposeInstructionsForGamepad();
         PlayerInput.AllowExecutionOfGamepadInstructions = false;
         if (!GamepadDisableInstructionsDisplay && text.Length > 0 && (!player[myPlayer].dead || gameMenu))
         {
             float num = 35f;
             float num2 = 1f;
             Vector2 baseScale = new Vector2(num2);
             if (gameMenu)
             {
                 num = 55f;
             }
             if (menuMode == 0)
             {
                 num += 32f;
             }
             Vector2 stringSize = ChatManager.GetStringSize(FontAssets.MouseText.Value, text, new Vector2(1f));
             float t = num2;
             Utils.Swap(ref GlyphTagHandler.GlyphsScale, ref t);
             ChatManager.DrawColorCodedStringWithShadow(spriteBatch, FontAssets.MouseText.Value, text, new Vector2(12f, (float)screenHeight - num) - stringSize * new Vector2(0f, 0f), Microsoft.Xna.Framework.Color.White, 0f, Vector2.Zero, baseScale, -1f, num2 * 2f);
             Utils.Swap(ref GlyphTagHandler.GlyphsScale, ref t);
         }
     }
References PlayerInput.AllowExecutionOfGamepadInstructions, PlayerInput.ComposeInstructionsForGamepad(), Player.dead, ChatManager.DrawColorCodedStringWithShadow(), drawingPlayerChat, gameMenu, GamepadDisableInstructionsDisplay, ChatManager.GetStringSize(), GlyphTagHandler.GlyphsScale, menuMode, FontAssets.MouseText, myPlayer, player, screenHeight, PlayerInput.SettingsForUI.ShowGamepadHints, spriteBatch, and Asset< T >.Value.
Referenced by DrawPendingMouseText().