Terraria: Main.DrawPlayerItemPos
DrawPlayerItemPos()
static Vector2 Main.DrawPlayerItemPos (float gravdir, int itemtype) inline static
     {
         float num = 10f;
         GetItemDrawFrame(itemtype, out var _, out var r);
         Vector2 result = r.Size() / 2f;
         switch (itemtype)
         {
         case 95:
             num = 6f;
             result.Y += 2f * gravdir;
             break;
         case 1295:
             num = 4f;
             break;
         case 3611:
             num = 2f;
             break;
         case 3350:
             num = 2f;
             break;
         case 2624:
             num = 4f;
             break;
         case 3018:
             num = 2f;
             break;
         case 3007:
             num = 4f;
             result.Y -= 1f * gravdir;
             break;
         case 3107:
             num = 4f;
             result.Y += 2f * gravdir;
             break;
         case 3008:
             num = -7f;
             result.Y += 2f * gravdir;
             break;
         case 1255:
             num = 6f;
             result.Y += 0f * gravdir;
             break;
         case 2269:
             num = 2f;
             result.Y += 2f * gravdir;
             break;
         case 1265:
             num = -8f;
             result.Y += 4f * gravdir;
             break;
         case 2272:
             num = 0f;
             result.Y += 4f * gravdir;
             break;
         case 3029:
             num = 4f;
             break;
         case 4381:
             num = 4f;
             break;
         case 2796:
             num = -28f;
             result.Y += 2f * gravdir;
             break;
         case 2797:
             num = 0f;
             break;
         case 2610:
             num = 0f;
             break;
         case 2623:
             num = -30f;
             result.Y -= 4f * gravdir;
             break;
         case 3546:
             num = -14f;
             result.Y -= 6f * gravdir;
             break;
         case 1835:
             num = -2f;
             result.Y += 2f * gravdir;
             break;
         default:
             switch (itemtype)
             {
             case 2624:
                 num = -4f;
                 break;
             case 3859:
                 num = -2f;
                 break;
             case 2888:
                 num = 6f;
                 break;
             case 2223:
                 num = 2f;
                 result.Y -= 2f * gravdir;
                 break;
             case 1782:
                 num = 0f;
                 result.Y += 4f * gravdir;
                 break;
             case 1929:
                 num = 0f;
                 result.Y += 2f * gravdir;
                 break;
             case 2270:
                 num = -4f;
                 break;
             case 1784:
                 num = 0f;
                 result.Y += 4f * gravdir;
                 break;
             case 1000:
                 num = 6f;
                 result.Y += 0f * gravdir;
                 break;
             case 1178:
                 num = 4f;
                 result.Y += 0f * gravdir;
                 break;
             case 1319:
                 num = 0f;
                 result.Y += 0f * gravdir;
                 break;
             case 1297:
                 num = -8f;
                 result.Y += 0f * gravdir;
                 break;
             case 1121:
                 num = 6f;
                 result.Y -= 2f * gravdir;
                 break;
             case 1314:
                 num = 2f;
                 break;
             case 1258:
                 num = 2f;
                 result.Y -= 2f * gravdir;
                 break;
             case 1155:
                 num = -10f;
                 result.Y -= 2f * gravdir;
                 break;
             case 1156:
                 num = -2f;
                 break;
             case 4703:
                 num = -3f;
                 result.Y -= 2f * gravdir;
                 break;
             case 5117:
                 num = -1f;
                 break;
             case 96:
                 num = -8f;
                 result.Y += 2f * gravdir;
                 break;
             case 1870:
                 num = -8f;
                 result.Y += 2f * gravdir;
                 break;
             case 1260:
                 num = -8f;
                 result.Y += 2f * gravdir;
                 break;
             case 1254:
                 num = -6f;
                 result.Y += 2f * gravdir;
                 break;
             case 98:
                 num = -5f;
                 result.Y -= 2f * gravdir;
                 break;
             case 534:
                 num = -2f;
                 result.Y += 1f * gravdir;
                 break;
             case 679:
                 num = 0f;
                 result.Y += 2f * gravdir;
                 break;
             case 964:
                 num = 0f;
                 result.Y += 0f * gravdir;
                 break;
             case 533:
                 num = -7f;
                 result.Y -= 2f * gravdir;
                 break;
             case 1553:
                 num = -10f;
                 result.Y -= 2f * gravdir;
                 break;
             case 506:
                 num = 0f;
                 result.Y -= 2f * gravdir;
                 break;
             case 1910:
                 num = 0f;
                 result.Y -= 2f * gravdir;
                 break;
             case 494:
             case 508:
                 num = -2f;
                 break;
             case 434:
                 num = 0f;
                 result.Y -= 2f * gravdir;
                 break;
             case 514:
                 num = 0f;
                 result.Y += 3f * gravdir;
                 break;
             case 435:
             case 436:
             case 481:
             case 578:
             case 1187:
             case 1194:
             case 1201:
             case 1229:
                 num = -2f;
                 result.Y -= 2f * gravdir;
                 break;
             case 197:
                 num = -5f;
                 result.Y += 4f * gravdir;
                 break;
             case 4060:
                 num = -2f;
                 result.Y += 4f * gravdir;
                 break;
             case 126:
                 num = 4f;
                 result.Y += 4f * gravdir;
                 break;
             case 800:
                 num = 4f;
                 result.Y += 2f * gravdir;
                 break;
             case 127:
                 num = 4f;
                 result.Y += 2f * gravdir;
                 break;
             case 157:
                 num = 6f;
                 result.Y += 2f * gravdir;
                 break;
             case 160:
                 num = -8f;
                 break;
             case 164:
             case 219:
                 num = 0f;
                 result.Y += 2f * gravdir;
                 break;
             case 165:
             case 272:
                 num = 4f;
                 result.Y += 4f * gravdir;
                 break;
             case 3870:
                 num = 4f;
                 result.Y += 4f * gravdir;
                 break;
             case 266:
                 num = 0f;
                 result.Y += 2f * gravdir;
                 break;
             case 281:
                 num = 6f;
                 result.Y -= 6f * gravdir;
                 break;
             case 986:
                 num = 6f;
                 result.Y -= 10f * gravdir;
                 break;
             case 682:
                 num = 4f;
                 break;
             case 4953:
                 num = -4f;
                 break;
             case 758:
                 num -= 20f;
                 result.Y += 0f * gravdir;
                 break;
             case 759:
                 num -= 18f;
                 result.Y += 2f * gravdir;
                 break;
             case 760:
                 num -= 12f;
                 result.Y += 2f * gravdir;
                 break;
             case 1946:
                 num -= 12f;
                 result.Y += 2f * gravdir;
                 break;
             case 779:
                 num = 0f;
                 result.Y += 2f * gravdir;
                 break;
             case 5134:
                 num = 0f;
                 result.Y += 2f * gravdir;
                 break;
             case 905:
                 num = -5f;
                 result.Y += 0f * gravdir;
                 break;
             case 930:
                 num = 4f;
                 result.Y += 2f * gravdir;
                 break;
             case 3788:
                 num = 2f;
                 result.Y += 2f * gravdir;
                 break;
             }
             break;
         }
         result.X = num;
         return result;
     }
References GetItemDrawFrame().
Referenced by DrawNPCExtras(), and PlayerDrawLayers.DrawPlayer_27_HeldItem().