Terraria: Main.GetPlayerHeadBordersColor
GetPlayerHeadBordersColor()
static Microsoft.Xna.Framework.Color Main.GetPlayerHeadBordersColor (Player plr) inline static
     {
         if (plr.ghost || plr.dead)
         {
             return Microsoft.Xna.Framework.Color.Transparent;
         }
         if (plr.whoAmI == myPlayer)
         {
             return teamColor[plr.team];
         }
         if (plr.hostile && (plr.team != LocalPlayer.team || plr.team == 0))
         {
             return Microsoft.Xna.Framework.Color.Transparent;
         }
         return teamColor[plr.team];
     }
References Player.dead, Player.ghost, Player.hostile, LocalPlayer, myPlayer, Player.team, teamColor, and Entity.whoAmI.
Referenced by LegacyMultiplayerClosePlayersOverlay.Draw(), DrawMap(), and NewMultiplayerClosePlayersOverlay.PlayerOffScreenCache.DrawPlayerHead().