Terraria: Main.DrawProj_EmpressBlade
DrawProj_EmpressBlade()
void Main.DrawProj_EmpressBlade (Projectile proj, float hueOverride) inline private
     {
         CurrentDrawnEntityShader = -1;
         PrepareDrawnProjectileDrawing(proj);
         Vector2 vector = proj.Center - screenPosition;
         proj.GetFairyQueenWeaponsColor(0f, 0f, hueOverride);
         Microsoft.Xna.Framework.Color fairyQueenWeaponsColor = proj.GetFairyQueenWeaponsColor(0.5f, 0f, hueOverride);
         Texture2D value = TextureAssets.Projectile[proj.type].Value;
         Vector2 origin = value.Frame().Size() / 2f;
         Microsoft.Xna.Framework.Color color = Microsoft.Xna.Framework.Color.White * proj.Opacity;
         color.A = (byte)((float)(int)color.A * 0.7f);
         fairyQueenWeaponsColor.A /= 2;
         float scale = proj.scale;
         float num = proj.rotation - (float)Math.PI / 2f;
         float num2 = proj.Opacity * 0.3f;
         if (num2 > 0f)
         {
             float lerpValue = Utils.GetLerpValue(60f, 50f, proj.ai[0], clamped: true);
             float num3 = Utils.GetLerpValue(70f, 50f, proj.ai[0], clamped: true) * Utils.GetLerpValue(40f, 45f, proj.ai[0], clamped: true);
             for (float num4 = 0f; num4 < 1f; num4 += 1f / 6f)
             {
                 Vector2 vector2 = num.ToRotationVector2() * -120f * num4 * lerpValue;
                 EntitySpriteDraw(value, vector + vector2, null, fairyQueenWeaponsColor * num2 * (1f - num4) * num3, num, origin, scale * 1.5f, SpriteEffects.None);
             }
             for (float num5 = 0f; num5 < 1f; num5 += 0.25f)
             {
                 Vector2 vector3 = (num5 * ((float)Math.PI * 2f) + num).ToRotationVector2() * 4f * scale;
                 EntitySpriteDraw(value, vector + vector3, null, fairyQueenWeaponsColor * num2, num, origin, scale, SpriteEffects.None);
             }
         }
         EntitySpriteDraw(value, vector, null, color, num, origin, scale, SpriteEffects.None);
         EntitySpriteDraw(value, vector, null, fairyQueenWeaponsColor * num2 * 0.5f, num, origin, scale, SpriteEffects.None);
     }
References Projectile.ai, Entity.Center, CurrentDrawnEntityShader, EntitySpriteDraw(), Projectile.GetFairyQueenWeaponsColor(), Utils.GetLerpValue(), Projectile.Opacity, PrepareDrawnProjectileDrawing(), TextureAssets.Projectile, Projectile.rotation, Projectile.scale, screenPosition, Projectile.type, and Asset< T >.Value.
Referenced by DrawProjDirect().