Terraria: Main.rgbToHsl
rgbToHsl()
static Vector3 Main.rgbToHsl (Microsoft.Xna.Framework.Color newColor) inline static
     {
         float num = (int)newColor.R;
         float num2 = (int)newColor.G;
         float num3 = (int)newColor.B;
         num /= 255f;
         num2 /= 255f;
         num3 /= 255f;
         float val = Math.Max(num, num2);
         val = Math.Max(val, num3);
         float val2 = Math.Min(num, num2);
         val2 = Math.Min(val2, num3);
         float num4 = 0f;
         float num5 = (val + val2) / 2f;
         float y;
         if (val == val2)
         {
             num4 = (y = 0f);
         }
         else
         {
             float num6 = val - val2;
             y = (((double)num5 > 0.5) ? (num6 / (2f - val - val2)) : (num6 / (val + val2)));
             if (val == num)
             {
                 num4 = (num2 - num3) / num6 + (float)((num2 < num3) ? 6 : 0);
             }
             if (val == num2)
             {
                 num4 = (num3 - num) / num6 + 2f;
             }
             if (val == num3)
             {
                 num4 = (num - num2) / num6 + 4f;
             }
             num4 /= 6f;
         }
         return new Vector3(num4, y, num5);
     }
Referenced by DrawClothesWindow(), CaptureInterface.ModeEdgeSelection.DrawCursors(), DrawHairWindow(), DrawMenu(), PlayerDrawLayers.DrawPlayer_07_LeinforsHairShampoo(), DrawProjDirect(), Projectile.GetLastPrismHue(), UICharacterCreation.RgbToScaledHsl(), ColorSlidersSet.SetHSL(), Player.WingFrame(), and Player.Yoraiz0rEye().