Terraria: Main.DrawInterface_27_Inventory
DrawInterface_27_Inventory()
void Main.DrawInterface_27_Inventory () inline private
     {
         HackForGamepadInputHell();
         if (playerInventory)
         {
             if (player[myPlayer].chest != -1)
             {
                 CreativeMenu.CloseMenu();
             }
             if (ignoreErrors)
             {
                 try
                 {
                     DrawInventory();
                     return;
                 }
                 catch (Exception e)
                 {
                     TimeLogger.DrawException(e);
                     return;
                 }
             }
             DrawInventory();
         }
         else
         {
             CreativeMenu.CloseMenu();
             recFastScroll = true;
             SetMouseNPC(-1, -1);
             EquipPage = 0;
         }
     }
References chest, CreativeUI.CloseMenu(), CreativeMenu, TimeLogger.DrawException(), DrawInventory(), EquipPage, HackForGamepadInputHell(), ignoreErrors, myPlayer, player, playerInventory, recFastScroll, and SetMouseNPC().
Referenced by SetupDrawInterfaceLayers().