Terraria: Main.LoadBackground
LoadBackground()
void Main.LoadBackground (int i) inline
     {
         //IL_000e: Unknown result type (might be due to invalid IL or missing references)
         if (i >= 0 && (int)TextureAssets.Background[i].State == 0)
         {
             Assets.Request<Texture2D>(TextureAssets.Background[i].Name, (AssetRequestMode)1);
             backgroundWidth[i] = TextureAssets.Background[i].Width();
             backgroundHeight[i] = TextureAssets.Background[i].Height();
             switch (i)
             {
             case 219:
             case 220:
             case 221:
             case 235:
             case 271:
             case 272:
             case 273:
             case 281:
                 backgroundWidth[i] /= 2;
                 backgroundHeight[i] /= 2;
                 break;
             }
         }
     }
References Assets, TextureAssets.Background, backgroundHeight, backgroundWidth, Asset< T >.Name, and Asset< T >.State.
Referenced by DrawBackground(), DrawSurfaceBG(), DrawSurfaceBG_Corrupt(), DrawSurfaceBG_Crimson(), DrawSurfaceBG_Desert(), DrawSurfaceBG_DrawBackMountainsLayer(), DrawSurfaceBG_Forest(), DrawSurfaceBG_GoodEvilDesert(), DrawSurfaceBG_Hallow(), DrawSurfaceBG_Jungle(), DrawSurfaceBG_Mushroom(), DrawSurfaceBG_Snow(), AssetInitializer.LoadTextures(), and OldDrawBackground().