Terraria: Main.CancelClothesWindow
CancelClothesWindow()
static void Main.CancelClothesWindow (bool quiet = false) inline static
     {
         if (clothesWindow)
         {
             clothesWindow = false;
             if (!quiet)
             {
                 SoundEngine.PlaySound(11);
             }
             player[myPlayer].shirtColor = oldClothesColor[0];
             player[myPlayer].underShirtColor = oldClothesColor[1];
             player[myPlayer].pantsColor = oldClothesColor[2];
             player[myPlayer].shoeColor = oldClothesColor[3];
             player[myPlayer].eyeColor = oldClothesColor[4];
             player[myPlayer].skinColor = oldClothesColor[5];
             dresserInterfaceDummy.skinVariant = oldClothesStyle;
             dresserInterfaceDummy.Male = player[myPlayer].Male;
             player[myPlayer].skinVariant = dresserInterfaceDummy.skinVariant;
         }
     }
References clothesWindow, dresserInterfaceDummy, Player.eyeColor, Player.Male, myPlayer, oldClothesColor, oldClothesStyle, Player.pantsColor, player, SoundEngine.PlaySound(), Player.shirtColor, Player.shoeColor, Player.skinColor, Player.skinVariant, and Player.underShirtColor.
Referenced by DrawClothesWindow(), OpenClothesWindow(), Player.TileInteractionsUse(), Player.ToggleCreativeMenu(), and Player.ToggleInv().