Terraria: Main.GetWorldPathFromName
GetWorldPathFromName()
static string Main.GetWorldPathFromName (string worldName, bool cloudSave) inline static
     {
         char[] invalidFileNameChars = Path.GetInvalidFileNameChars();
         string text = "";
         foreach (char c in worldName)
         {
             text += ((!invalidFileNameChars.Contains(c)) ? ((c != ' ') ? c : '_') : '-');
         }
         text = text.Replace(".", "_");
         text = text.Replace("*", "_");
         string text2 = (cloudSave ? CloudWorldPath : WorldPath);
         if (FileUtilities.GetFullPath(text2 + Path.DirectorySeparatorChar + text + ".wld", cloudSave).StartsWith("\\\\.\\", StringComparison.Ordinal))
         {
             text += "_";
         }
         if (FileUtilities.Exists(text2 + Path.DirectorySeparatorChar + text + ".wld", cloudSave))
         {
             int num = 2;
             while (FileUtilities.Exists(text2 + Path.DirectorySeparatorChar.ToString() + text + num + ".wld", cloudSave))
             {
                 num++;
             }
             text += num;
         }
         return text2 + Path.DirectorySeparatorChar + text + ".wld";
     }
References CloudWorldPath, FileUtilities.Exists(), FileUtilities.GetFullPath(), worldName, and WorldPath.
Referenced by WorldFileData.CopyToLocal(), WorldFile.CreateMetadata(), WorldFileData.MoveToCloud(), and WorldFileData.MoveToLocal().