Terraria: Main.DoUpdate_HandleInput
DoUpdate_HandleInput()
void Main.DoUpdate_HandleInput () inline private
     {
         PlayerInput.UpdateInput();
         UpdateViewZoomKeys();
         PlayerInput.SetZoom_Unscaled();
         UILinkPointNavigator.Update();
         PlayerInput.CacheMousePositionForZoom();
         PlayerInput.SetZoom_MouseInWorld();
         oldKeyState = keyState;
         keyState = Keyboard.GetState();
     }
References PlayerInput.CacheMousePositionForZoom(), Keyboard, keyState, oldKeyState, PlayerInput.SetZoom_MouseInWorld(), PlayerInput.SetZoom_Unscaled(), UILinkPointNavigator.Update(), PlayerInput.UpdateInput(), and UpdateViewZoomKeys().
Referenced by DoUpdate().