Terraria: Main.InputTextSignCancel
InputTextSignCancel()
static void Main.InputTextSignCancel () inline static
     {
         SoundEngine.PlaySound(12);
         editSign = false;
         blockKey = Microsoft.Xna.Framework.Input.Keys.Escape.ToString();
         UIVirtualKeyboard.CacheCanceledInput(1);
         if (player[myPlayer].sign >= 0)
         {
             npcChatText = sign[player[myPlayer].sign].text;
         }
     }
References blockKey, UIVirtualKeyboard.CacheCanceledInput(), editSign, myPlayer, npcChatText, player, SoundEngine.PlaySound(), sign, Player.sign, and Sign.text.
Referenced by InputTextSign(), and UIVirtualKeyboard.TryEscapingMenu().