Terraria: Main.DoDraw
DoDraw()
void Main.DoDraw (GameTime gameTime) inline private
     {
         Stopwatch stopwatch = new Stopwatch();
         stopwatch.Start();
         if (showSplash)
         {
             DrawSplash(gameTime);
             TimeLogger.SplashDrawTime(stopwatch.Elapsed.TotalMilliseconds);
             TimeLogger.EndDrawFrame();
             return;
         }
         if (_drawCycleCounter == 0L)
         {
             TileFrameSeed = Utils.RandomNextSeed(TileFrameSeed);
         }
         _drawCycleCounter = (_drawCycleCounter + 1) % 5;
         MenuUI.IsVisible = gameMenu && menuMode == 888;
         InGameUI.IsVisible = !gameMenu && InGameUI.CurrentState != null;
         PlayerInput.UpdateMainMouse();
         RefreshPlayerDrawOrder();
         CaptureManager.Instance.DrawTick();
         TimeLogger.NewDrawFrame();
         if (!gameMenu)
         {
             TilesRenderer.PreparePaintForTilesOnScreen();
         }
         for (int i = 0; i < ContentThatNeedsRenderTargets.Count; i++)
         {
             ContentThatNeedsRenderTargets[i].PrepareRenderTarget(base.GraphicsDevice, spriteBatch);
         }
         TilePaintSystem.PrepareAllRequests();
         TimeLogger.DetailedDrawTime(0);
         if (loadMap)
         {
             refreshMap = false;
             DrawToMap();
             TimeLogger.DetailedDrawTime(1);
         }
         if (Lighting.UpdateEveryFrame)
         {
             drawToScreen = true;
         }
         else
         {
             drawToScreen = false;
         }
         if (drawToScreen && targetSet)
         {
             ReleaseTargets();
         }
         if (!drawToScreen && !targetSet)
         {
             InitTargets();
         }
         fpsCount++;
         if (!base.IsActive)
         {
             maxQ = true;
         }
         if (!dedServ)
         {
             UpdateDisplaySettings();
             if (Main.OnPreDraw != null)
             {
                 Main.OnPreDraw(gameTime);
             }
         }
         drawsCountedForFPS++;
         screenLastPosition = screenPosition;
         if (stackSplit == 0)
         {
             timesTriedToFastStack = 0;
             stackCounter = 0;
             stackDelay = 7;
             superFastStack = 0;
         }
         else
         {
             stackCounter++;
             int num = 30;
             num = ((stackDelay == 7) ? 30 : ((stackDelay == 6) ? 25 : ((stackDelay == 5) ? 20 : ((stackDelay == 4) ? 15 : ((stackDelay != 3) ? 5 : 10)))));
             if (stackCounter >= num)
             {
                 stackDelay--;
                 if (stackDelay < 2)
                 {
                     stackDelay = 2;
                     superFastStack++;
                 }
                 if (timesTriedToFastStack < 10)
                 {
                     superFastStack = 0;
                 }
                 timesTriedToFastStack++;
                 stackCounter = 0;
             }
         }
         if (myPlayer >= 0)
         {
             player[myPlayer].lastMouseInterface = player[myPlayer].mouseInterface;
             player[myPlayer].mouseInterface = false;
         }
         if (mapTime > 0)
         {
             mapTime--;
         }
         if (gameMenu)
         {
             mapTime = mapTimeMax;
         }
         HoverItem = new Item();
         DoDraw_UpdateCameraPosition();
         CheckMonoliths();
         sunCircle += 0.01f;
         if ((double)sunCircle > 6.285)
         {
             sunCircle -= 6.285f;
         }
         TimeLogger.DetailedDrawReset();
         if (!gameMenu)
         {
             waterfallManager.FindWaterfalls();
             TimeLogger.DetailedDrawTime(2);
             if (renderNow)
             {
                 screenLastPosition = screenPosition;
                 renderNow = false;
                 renderCount = 99;
                 Draw(gameTime);
                 Lighting.LightTiles(firstTileX, lastTileX, firstTileY, lastTileY);
                 Lighting.LightTiles(firstTileX, lastTileX, firstTileY, lastTileY);
                 RenderTiles();
                 sceneTilePos.X = screenPosition.X - (float)offScreenRange;
                 sceneTilePos.Y = screenPosition.Y - (float)offScreenRange;
                 RenderBackground();
                 sceneBackgroundPos.X = screenPosition.X - (float)offScreenRange;
                 sceneBackgroundPos.Y = screenPosition.Y - (float)offScreenRange;
                 RenderWalls();
                 sceneWallPos.X = screenPosition.X - (float)offScreenRange;
                 sceneWallPos.Y = screenPosition.Y - (float)offScreenRange;
                 RenderTiles2();
                 sceneTile2Pos.X = screenPosition.X - (float)offScreenRange;
                 sceneTile2Pos.Y = screenPosition.Y - (float)offScreenRange;
                 RenderWater();
                 sceneWaterPos.X = screenPosition.X - (float)offScreenRange;
                 sceneWaterPos.Y = screenPosition.Y - (float)offScreenRange;
                 renderCount = 99;
             }
             else
             {
                 if (renderCount == 3)
                 {
                     RenderTiles();
                     sceneTilePos.X = screenPosition.X - (float)offScreenRange;
                     sceneTilePos.Y = screenPosition.Y - (float)offScreenRange;
                 }
                 if (renderCount == 3)
                 {
                     RenderTiles2();
                     sceneTile2Pos.X = screenPosition.X - (float)offScreenRange;
                     sceneTile2Pos.Y = screenPosition.Y - (float)offScreenRange;
                 }
                 if (renderCount == 3)
                 {
                     RenderWalls();
                     sceneWallPos.X = screenPosition.X - (float)offScreenRange;
                     sceneWallPos.Y = screenPosition.Y - (float)offScreenRange;
                 }
                 if (renderCount == 2)
                 {
                     RenderBackground();
                     sceneBackgroundPos.X = screenPosition.X - (float)offScreenRange;
                     sceneBackgroundPos.Y = screenPosition.Y - (float)offScreenRange;
                 }
                 if (renderCount == 1)
                 {
                     RenderWater();
                     sceneWaterPos.X = screenPosition.X - (float)offScreenRange;
                     sceneWaterPos.Y = screenPosition.Y - (float)offScreenRange;
                 }
             }
             if (render && !gameMenu)
             {
                 if (Math.Abs(sceneTilePos.X - (screenPosition.X - (float)offScreenRange)) > (float)offScreenRange || Math.Abs(sceneTilePos.Y - (screenPosition.Y - (float)offScreenRange)) > (float)offScreenRange)
                 {
                     RenderTiles();
                     sceneTilePos.X = screenPosition.X - (float)offScreenRange;
                     sceneTilePos.Y = screenPosition.Y - (float)offScreenRange;
                 }
                 if (Math.Abs(sceneTile2Pos.X - (screenPosition.X - (float)offScreenRange)) > (float)offScreenRange || Math.Abs(sceneTile2Pos.Y - (screenPosition.Y - (float)offScreenRange)) > (float)offScreenRange)
                 {
                     RenderTiles2();
                     sceneTile2Pos.X = screenPosition.X - (float)offScreenRange;
                     sceneTile2Pos.Y = screenPosition.Y - (float)offScreenRange;
                 }
                 if (Math.Abs(sceneBackgroundPos.X - (screenPosition.X - (float)offScreenRange)) > (float)offScreenRange || Math.Abs(sceneBackgroundPos.Y - (screenPosition.Y - (float)offScreenRange)) > (float)offScreenRange)
                 {
                     RenderBackground();
                     sceneBackgroundPos.X = screenPosition.X - (float)offScreenRange;
                     sceneBackgroundPos.Y = screenPosition.Y - (float)offScreenRange;
                 }
                 if (Math.Abs(sceneWallPos.X - (screenPosition.X - (float)offScreenRange)) > (float)offScreenRange || Math.Abs(sceneWallPos.Y - (screenPosition.Y - (float)offScreenRange)) > (float)offScreenRange)
                 {
                     RenderWalls();
                     sceneWallPos.X = screenPosition.X - (float)offScreenRange;
                     sceneWallPos.Y = screenPosition.Y - (float)offScreenRange;
                 }
                 if (Math.Abs(sceneWaterPos.X - (screenPosition.X - (float)offScreenRange)) > (float)offScreenRange || Math.Abs(sceneWaterPos.Y - (screenPosition.Y - (float)offScreenRange)) > (float)offScreenRange)
                 {
                     RenderWater();
                     sceneWaterPos.X = screenPosition.X - (float)offScreenRange;
                     sceneWaterPos.Y = screenPosition.Y - (float)offScreenRange;
                 }
             }
         }
         if (!loadMap)
         {
             if (!gameMenu)
             {
                 TimeLogger.DetailedDrawReset();
                 Stopwatch stopwatch2 = new Stopwatch();
                 stopwatch2.Start();
                 int num2 = 0;
                 int x;
                 int y;
                 while (stopwatch2.ElapsedMilliseconds < 5 && sectionManager.GetNextMapDraw(player[myPlayer].position, out x, out y))
                 {
                     DrawToMap_Section(x, y);
                     num2++;
                 }
                 TimeLogger.DetailedDrawTime(3);
             }
             if (updateMap)
             {
                 if (base.IsActive || netMode == 1)
                 {
                     if (refreshMap)
                     {
                         refreshMap = false;
                         sectionManager.ClearMapDraw();
                     }
                     DrawToMap();
                     updateMap = false;
                 }
                 else if (MapHelper.numUpdateTile > 0)
                 {
                     DrawToMap();
                 }
                 TimeLogger.DetailedDrawTime(4);
             }
         }
         bgParallax = 0.1;
         bgStartX = (int)(0.0 - Math.IEEERemainder((double)screenPosition.X * bgParallax, backgroundWidth[background]) - (double)(backgroundWidth[background] / 2));
         bgLoops = screenWidth / backgroundWidth[background] + 2;
         bgStartY = 0;
         bgLoopsY = 0;
         bgTopY = (int)((double)(0f - screenPosition.Y) / (worldSurface * 16.0 - 600.0) * 200.0);
         if (gameMenu || netMode == 2)
         {
             bgTopY = -200;
         }
         int num3 = dayRate;
         if (num3 < 1)
         {
             num3 = 1;
         }
         float num4 = 0.0005f * (float)num3;
         if (gameMenu)
         {
             num4 *= 20f;
         }
         if (raining)
         {
             if (cloudAlpha > maxRaining)
             {
                 cloudAlpha -= num4;
                 if (cloudAlpha < maxRaining)
                 {
                     cloudAlpha = maxRaining;
                 }
             }
             else if (cloudAlpha < maxRaining)
             {
                 cloudAlpha += num4;
                 if (cloudAlpha > maxRaining)
                 {
                     cloudAlpha = maxRaining;
                 }
             }
         }
         else
         {
             cloudAlpha -= num4;
             if (cloudAlpha < 0f)
             {
                 cloudAlpha = 0f;
             }
         }
         if (gameMenu || netMode == 2)
         {
             bgDelay = 1000;
             SceneMetrics.EvilTileCount = (int)(bgAlphaFrontLayer[1] * (float)SceneMetrics.CorruptionTileMax);
         }
         Microsoft.Xna.Framework.Color moonColor = Microsoft.Xna.Framework.Color.White;
         Microsoft.Xna.Framework.Color sunColor = Microsoft.Xna.Framework.Color.White;
         float num5 = SceneMetrics.MushroomTileCount / SceneMetrics.MushroomTileMax;
         float num6 = SmoothedMushroomLightInfluence;
         if (num5 > 0f)
         {
             if (num5 > num6)
             {
                 num6 += 0.01f;
             }
             if (num5 < num6)
             {
                 num6 -= 0.01f;
             }
         }
         else
         {
             num6 -= 0.02f;
         }
         if (num6 < 0f)
         {
             num6 = 0f;
         }
         if (num6 > 1f)
         {
             num6 = 1f;
         }
         SmoothedMushroomLightInfluence = num6;
         InfoToSetBackColor info = default(InfoToSetBackColor);
         info.isInGameMenuOrIsServer = gameMenu || netMode == 2;
         info.CorruptionBiomeInfluence = (float)SceneMetrics.EvilTileCount / (float)SceneMetrics.CorruptionTileMax;
         info.CrimsonBiomeInfluence = (float)SceneMetrics.BloodTileCount / (float)SceneMetrics.CrimsonTileMax;
         info.JungleBiomeInfluence = (float)SceneMetrics.JungleTileCount / (float)SceneMetrics.JungleTileMax;
         info.MushroomBiomeInfluence = SmoothedMushroomLightInfluence;
         info.GraveyardInfluence = GraveyardVisualIntensity;
         info.BloodMoonActive = bloodMoon || SceneMetrics.BloodMoonMonolith;
         info.LanternNightActive = LanternNight.LanternsUp;
         SetBackColor(info, out sunColor, out moonColor);
         if (gameMenu || netMode == 2)
         {
             bgTopY = 0;
         }
         ApplyColorOfTheSkiesToTiles();
         UpdateAtmosphereTransparencyToSkyColor();
         base.GraphicsDevice.Clear(Microsoft.Xna.Framework.Color.Black);
         base.Draw(gameTime);
         float val = (float)screenWidth / MinimumZoomComparerX;
         float val2 = (float)screenHeight / MinimumZoomComparerY;
         ForcedMinimumZoom = Math.Max(Math.Max(1f, val), val2);
         GameViewMatrix.Effects = ((!gameMenu && player[myPlayer].gravDir != 1f) ? SpriteEffects.FlipVertically : SpriteEffects.None);
         BackgroundViewMatrix.Effects = GameViewMatrix.Effects;
         BackgroundViewMatrix.Zoom = new Vector2(ForcedMinimumZoom);
         GameViewMatrix.Zoom = new Vector2(ForcedMinimumZoom * MathHelper.Clamp(GameZoomTarget, 1f, 2f));
         if (gameMenu || player[myPlayer].gravDir == 1f)
         {
             Rasterizer = RasterizerState.CullCounterClockwise;
         }
         else
         {
             Rasterizer = RasterizerState.CullClockwise;
         }
         bool flag = gameMenu;
         if (dontStarveWorld && WorldGen.generatingWorld)
         {
             if (!Terraria.Graphics.Effects.Filters.Scene["Sepia"].IsActive())
             {
                 Terraria.Graphics.Effects.Filters.Scene.Activate("Sepia", default(Vector2));
             }
             flag = false;
         }
         else if (flag && Terraria.Graphics.Effects.Filters.Scene["Sepia"].IsActive())
         {
             Terraria.Graphics.Effects.Filters.Scene.Deactivate("Sepia");
         }
         if (Terraria.Graphics.Effects.Filters.Scene["Sepia"].IsInUse())
         {
             flag = false;
         }
         bool flag2 = !(drawToScreen || netMode == 2 || flag) && !mapFullscreen && Lighting.NotRetro && Terraria.Graphics.Effects.Filters.Scene.CanCapture();
         if (flag2)
         {
             Terraria.Graphics.Effects.Filters.Scene.BeginCapture(screenTarget, Microsoft.Xna.Framework.Color.Black);
         }
         spriteBatch.Begin(SpriteSortMode.Deferred, BlendState.AlphaBlend, DefaultSamplerState, DepthStencilState.None, Rasterizer, null, BackgroundViewMatrix.TransformationMatrix);
         TimeLogger.DetailedDrawReset();
         SceneArea sceneArea = default(SceneArea);
         sceneArea.bgTopY = bgTopY;
         sceneArea.totalHeight = screenHeight;
         sceneArea.totalWidth = screenWidth;
         sceneArea.SceneLocalScreenPositionOffset = Vector2.Zero;
         SceneArea sceneArea2 = sceneArea;
         if (!mapFullscreen)
         {
             unityMouseOver = false;
             if ((double)screenPosition.Y < worldSurface * 16.0 + 16.0)
             {
                 Asset<Texture2D> val3 = TextureAssets.Background[background];
                 Microsoft.Xna.Framework.Rectangle destinationRectangle = new Microsoft.Xna.Framework.Rectangle(bgStartX, bgTopY, val3.Width(), Math.Max(screenHeight, val3.Height()));
                 if (destinationRectangle.Bottom < val3.Height())
                 {
                     int num7 = val3.Height() - destinationRectangle.Bottom;
                     destinationRectangle.Height += num7;
                 }
                 if (false)
                 {
                     for (int j = 0; j < bgLoops; j++)
                     {
                         destinationRectangle.X = bgStartX + val3.Width() * j;
                         spriteBatch.Draw(val3.Value, destinationRectangle, null, ColorOfTheSkies, 0f, Vector2.Zero, SpriteEffects.FlipVertically, 0f);
                     }
                 }
                 else
                 {
                     for (int k = 0; k < bgLoops; k++)
                     {
                         destinationRectangle.X = bgStartX + val3.Width() * k;
                         spriteBatch.Draw(val3.Value, destinationRectangle, ColorOfTheSkies);
                     }
                 }
                 TimeLogger.DetailedDrawTime(6);
             }
             spriteBatch.End();
             spriteBatch.Begin(SpriteSortMode.Deferred, BlendState.AlphaBlend, DefaultSamplerState, DepthStencilState.None, Rasterizer, null, BackgroundViewMatrix.EffectMatrix);
             if (shimmerAlpha != 1f)
             {
                 DrawStarsInBackground(sceneArea2, artificial: false);
             }
             if ((double)(screenPosition.Y / 16f) < worldSurface + 2.0)
             {
                 DrawSunAndMoon(sceneArea2, moonColor, sunColor, num6);
             }
             TimeLogger.DetailedDrawTime(7);
         }
         Overlays.Scene.Draw(spriteBatch, RenderLayers.Sky);
         spriteBatch.End();
         Vector2 vector = screenPosition;
         int num8 = screenWidth;
         int num9 = screenHeight;
         screenWidth = (int)((float)screenWidth / BackgroundViewMatrix.Zoom.X);
         screenHeight = (int)((float)screenHeight / BackgroundViewMatrix.Zoom.Y);
         screenPosition += BackgroundViewMatrix.Translation;
         Matrix transformationMatrix = BackgroundViewMatrix.TransformationMatrix;
         transformationMatrix.Translation -= BackgroundViewMatrix.ZoomMatrix.Translation * new Vector3(1f, BackgroundViewMatrix.Effects.HasFlag(SpriteEffects.FlipVertically) ? (-1f) : 1f, 1f);
         spriteBatch.Begin(SpriteSortMode.Deferred, BlendState.AlphaBlend, SamplerState.LinearClamp, DepthStencilState.None, Rasterizer, null, transformationMatrix);
         CurrentFrameFlags.Hacks.CurrentBackgroundMatrixForCreditsRoll = transformationMatrix;
         DrawBG();
         screenWidth = num8;
         screenHeight = num9;
         screenPosition = vector;
         spriteBatch.End();
         spriteBatch.Begin(SpriteSortMode.Deferred, BlendState.AlphaBlend, SamplerState.LinearClamp, DepthStencilState.None, Rasterizer, null, GameViewMatrix.TransformationMatrix);
         DrawBackgroundBlackFill();
         spriteBatch.End();
         Overlays.Scene.Draw(spriteBatch, RenderLayers.Landscape);
         spriteBatch.Begin(SpriteSortMode.Deferred, BlendState.AlphaBlend, SamplerState.LinearClamp, DepthStencilState.None, Rasterizer, null, UIScaleMatrix);
         if (gameMenu || netMode == 2)
         {
             spriteBatch.End();
             PreDrawMenu(out var screenSizeCache, out var screenSizeCacheAfterScaling);
             spriteBatch.Begin(SpriteSortMode.Deferred, BlendState.AlphaBlend, SamplerState.LinearClamp, DepthStencilState.None, Rasterizer, null, UIScaleMatrix);
             DrawMenu(gameTime);
             PostDrawMenu(screenSizeCache, screenSizeCacheAfterScaling);
             TimeLogger.MenuDrawTime(stopwatch.Elapsed.TotalMilliseconds);
             TimeLogger.EndDrawFrame();
             if (flag2)
             {
                 Terraria.Graphics.Effects.Filters.Scene.EndCapture(null, screenTarget, screenTargetSwap, Microsoft.Xna.Framework.Color.Black);
             }
             return;
         }
         spriteBatch.End();
         spriteBatch.Begin(SpriteSortMode.Deferred, BlendState.AlphaBlend, DefaultSamplerState, DepthStencilState.None, Rasterizer, null, Transform);
         DoLightTiles();
         TimeLogger.DetailedDrawReset();
         if (mapFullscreen)
         {
             if (player[myPlayer].talkNPC >= 0 || player[myPlayer].sign >= 0 || (playerInventory && !CaptureManager.Instance.Active))
             {
                 player[myPlayer].ToggleInv();
             }
             DrawMap(gameTime);
             spriteBatch.End();
             spriteBatch.Begin(SpriteSortMode.Deferred, BlendState.AlphaBlend, SamplerStateForCursor, null, null, null, UIScaleMatrix);
             PlayerInput.SetZoom_UI();
             DrawFPS();
             DrawPlayerChat();
             DrawPendingMouseText();
             DrawCursor(DrawThickCursor());
             PlayerInput.SetZoom_Unscaled();
             spriteBatch.End();
             spriteBatch.Begin(SpriteSortMode.Deferred, BlendState.AlphaBlend, DefaultSamplerState, null, null, null);
             TimeLogger.MapDrawTime(stopwatch.Elapsed.TotalMilliseconds);
             TimeLogger.EndDrawFrame();
             PlayerInput.SetDesiredZoomContext(ZoomContext.Unscaled);
             CaptureManager.Instance.Update();
             if (CaptureManager.Instance.Active)
             {
                 CaptureManager.Instance.Draw(spriteBatch);
             }
             spriteBatch.End();
             if (mouseLeft)
             {
                 mouseLeftRelease = false;
             }
             else
             {
                 mouseLeftRelease = true;
             }
             return;
         }
         if (shimmerAlpha > 0f)
         {
             spriteBatch.Draw(TextureAssets.MagicPixel.Value, Vector2.Zero, null, Microsoft.Xna.Framework.Color.Black * shimmerAlpha, 0f, Vector2.Zero, new Vector2(Camera.UnscaledSize.X + (float)(offScreenRange * 2), Camera.UnscaledSize.Y + (float)(offScreenRange * 2)), SpriteEffects.None, 0f);
         }
         Overlays.Scene.Draw(spriteBatch, RenderLayers.InWorldUI);
         _ = Microsoft.Xna.Framework.Color.White;
         if (drawToScreen)
         {
             DrawWaters(isBackground: true);
         }
         else
         {
             spriteBatch.Draw(backWaterTarget, sceneBackgroundPos - screenPosition, Microsoft.Xna.Framework.Color.White);
             TimeLogger.DetailedDrawTime(11);
         }
         Overlays.Scene.Draw(spriteBatch, RenderLayers.BackgroundWater);
         float x2 = (sceneBackgroundPos.X - screenPosition.X + (float)offScreenRange) * caveParallax - (float)offScreenRange;
         if (shimmerAlpha > 0f)
         {
             spriteBatch.End();
             spriteBatch.Begin(SpriteSortMode.Deferred, BlendState.AlphaBlend, DefaultSamplerState, null, null, null);
             PlayerInput.SetZoom_Unscaled();
             DrawStarsInBackground(sceneArea2, artificial: true);
             spriteBatch.End();
             PlayerInput.SetDesiredZoomContext(ZoomContext.World);
             spriteBatch.Begin(SpriteSortMode.Deferred, BlendState.AlphaBlend, DefaultSamplerState, DepthStencilState.None, Rasterizer, null, Transform);
         }
         if (drawToScreen)
         {
             tileBatch.Begin();
             DrawBackground();
             tileBatch.End();
         }
         else
         {
             spriteBatch.Draw(backgroundTarget, new Vector2(x2, sceneBackgroundPos.Y - screenPosition.Y), Microsoft.Xna.Framework.Color.White);
             TimeLogger.DetailedDrawTime(12);
         }
         Overlays.Scene.Draw(spriteBatch, RenderLayers.Background);
         ScreenDarkness.DrawBack(spriteBatch);
         magmaBGFrameCounter++;
         if (magmaBGFrameCounter >= 8)
         {
             magmaBGFrameCounter = 0;
             magmaBGFrame++;
             if (magmaBGFrame >= 3)
             {
                 magmaBGFrame = 0;
             }
         }
         DoDraw_WallsTilesNPCs();
         Overlays.Scene.Draw(spriteBatch, RenderLayers.TilesAndNPCs);
         if (!mapFullscreen && mapStyle == 2)
         {
             try
             {
                 DrawMap(gameTime);
             }
             catch (Exception e)
             {
                 if (!ignoreErrors)
                 {
                     throw;
                 }
                 TimeLogger.DrawException(e);
             }
         }
         TimeLogger.DetailedDrawReset();
         spriteBatch.End();
         TimeLogger.DetailedDrawTime(35);
         HasInteractibleObjectThatIsNotATile = false;
         SortDrawCacheWorms();
         DrawSuperSpecialProjectiles(DrawCacheFirstFractals);
         DrawCachedProjs(DrawCacheProjsBehindProjectiles);
         DrawProjectiles();
         spriteBatch.Begin(SpriteSortMode.Immediate, BlendState.AlphaBlend, DefaultSamplerState, DepthStencilState.None, Rasterizer, null, Transform);
         ParticleSystem_World_BehindPlayers.Settings.AnchorPosition = -screenPosition;
         ParticleSystem_World_BehindPlayers.Draw(spriteBatch);
         spriteBatch.End();
         DrawPlayers_AfterProjectiles();
         DrawCachedProjs(DrawCacheProjsOverPlayers);
         spriteBatch.Begin(SpriteSortMode.Immediate, BlendState.AlphaBlend, DefaultSamplerState, DepthStencilState.None, Rasterizer, null, Transform);
         ParticleSystem_World_OverPlayers.Settings.AnchorPosition = -screenPosition;
         ParticleSystem_World_OverPlayers.Draw(spriteBatch);
         spriteBatch.End();
         spriteBatch.Begin(SpriteSortMode.Deferred, BlendState.AlphaBlend, DefaultSamplerState, DepthStencilState.None, Rasterizer, null, Transform);
         DrawCachedNPCs(DrawCacheNPCsOverPlayers, behindTiles: false);
         if (!gamePaused)
         {
             essScale += (float)essDir * 0.01f;
             if (essScale > 1f)
             {
                 essDir = -1;
                 essScale = 1f;
             }
             if ((double)essScale < 0.7)
             {
                 essDir = 1;
                 essScale = 0.7f;
             }
         }
         DrawItems();
         TimeLogger.DetailedDrawTime(22);
         DrawRain();
         if (ignoreErrors)
         {
             try
             {
                 DrawGore();
             }
             catch (Exception e2)
             {
                 TimeLogger.DrawException(e2);
             }
         }
         else
         {
             DrawGore();
         }
         spriteBatch.End();
         DrawDust();
         spriteBatch.Begin(SpriteSortMode.Deferred, BlendState.AlphaBlend, DefaultSamplerState, DepthStencilState.None, Rasterizer, null, Transform);
         Overlays.Scene.Draw(spriteBatch, RenderLayers.Entities);
         if (drawToScreen)
         {
             DrawWaters();
             if (WiresUI.Settings.DrawWires)
             {
                 DrawWires();
             }
         }
         else
         {
             spriteBatch.Draw(waterTarget, sceneWaterPos - screenPosition, Microsoft.Xna.Framework.Color.White);
             if (WiresUI.Settings.DrawWires)
             {
                 DrawWires();
             }
             TimeLogger.DetailedDrawTime(26);
         }
         if (shimmerAlpha > 0f)
         {
             spriteBatch.End();
             spriteBatch.Begin(SpriteSortMode.Deferred, BlendState.AlphaBlend, DefaultSamplerState, null, null, null, BackgroundViewMatrix.EffectMatrix);
             PlayerInput.SetZoom_Unscaled();
             DrawStarsInForeground(sceneArea2);
             spriteBatch.End();
             PlayerInput.SetDesiredZoomContext(ZoomContext.World);
             spriteBatch.Begin(SpriteSortMode.Deferred, BlendState.AlphaBlend, DefaultSamplerState, DepthStencilState.None, Rasterizer, null, Transform);
         }
         Overlays.Scene.Draw(spriteBatch, RenderLayers.ForegroundWater);
         DrawCachedProjs(DrawCacheProjsOverWiresUI, startSpriteBatch: false);
         DrawInfernoRings();
         ScreenDarkness.DrawFront(spriteBatch);
         MoonlordDeathDrama.DrawWhite(spriteBatch);
         ScreenObstruction.Draw(spriteBatch);
         TimeLogger.DetailedDrawReset();
         spriteBatch.End();
         Overlays.Scene.Draw(spriteBatch, RenderLayers.All);
         if (flag2)
         {
             Terraria.Graphics.Effects.Filters.Scene.EndCapture(null, screenTarget, screenTargetSwap, Microsoft.Xna.Framework.Color.Black);
         }
         TimeLogger.DetailedDrawTime(36);
         if (!hideUI)
         {
             spriteBatch.Begin(SpriteSortMode.Deferred, BlendState.AlphaBlend, DefaultSamplerState, null, null, null, UIScaleMatrix);
             TimeLogger.DetailedDrawReset();
             DrawPlayerChatBubbles();
             spriteBatch.End();
             spriteBatch.Begin(SpriteSortMode.Deferred, BlendState.AlphaBlend, DefaultSamplerState, null, null, null, GameViewMatrix.ZoomMatrix);
             float targetScale = CombatText.TargetScale;
             for (int l = 0; l < 100; l++)
             {
                 if (!combatText[l].active)
                 {
                     continue;
                 }
                 int num10 = 0;
                 if (combatText[l].crit)
                 {
                     num10 = 1;
                 }
                 Vector2 vector2 = FontAssets.CombatText[num10].Value.MeasureString(combatText[l].text);
                 Vector2 vector3 = new Vector2(vector2.X * 0.5f, vector2.Y * 0.5f);
                 float num11 = combatText[l].scale / targetScale;
                 float num12 = (int)combatText[l].color.R;
                 float num13 = (int)combatText[l].color.G;
                 float num14 = (int)combatText[l].color.B;
                 float num15 = (int)combatText[l].color.A;
                 num12 *= num11 * combatText[l].alpha * 0.3f;
                 num14 *= num11 * combatText[l].alpha * 0.3f;
                 num13 *= num11 * combatText[l].alpha * 0.3f;
                 num15 *= num11 * combatText[l].alpha;
                 Microsoft.Xna.Framework.Color color = new Microsoft.Xna.Framework.Color((int)num12, (int)num13, (int)num14, (int)num15);
                 for (int m = 0; m < 5; m++)
                 {
                     float num16 = 0f;
                     float num17 = 0f;
                     switch (m)
                     {
                     case 0:
                         num16 -= targetScale;
                         break;
                     case 1:
                         num16 += targetScale;
                         break;
                     case 2:
                         num17 -= targetScale;
                         break;
                     case 3:
                         num17 += targetScale;
                         break;
                     default:
                         num12 = (float)(int)combatText[l].color.R * num11 * combatText[l].alpha;
                         num14 = (float)(int)combatText[l].color.B * num11 * combatText[l].alpha;
                         num13 = (float)(int)combatText[l].color.G * num11 * combatText[l].alpha;
                         num15 = (float)(int)combatText[l].color.A * num11 * combatText[l].alpha;
                         color = new Microsoft.Xna.Framework.Color((int)num12, (int)num13, (int)num14, (int)num15);
                         break;
                     }
                     if (player[myPlayer].gravDir == -1f)
                     {
                         float num18 = combatText[l].position.Y - screenPosition.Y;
                         num18 = (float)screenHeight - num18;
                         DynamicSpriteFontExtensionMethods.DrawString(spriteBatch, FontAssets.CombatText[num10].Value, combatText[l].text, new Vector2(combatText[l].position.X - screenPosition.X + num16 + vector3.X, num18 + num17 + vector3.Y), color, combatText[l].rotation, vector3, combatText[l].scale, SpriteEffects.None, 0f);
                     }
                     else
                     {
                         DynamicSpriteFontExtensionMethods.DrawString(spriteBatch, FontAssets.CombatText[num10].Value, combatText[l].text, new Vector2(combatText[l].position.X - screenPosition.X + num16 + vector3.X, combatText[l].position.Y - screenPosition.Y + num17 + vector3.Y), color, combatText[l].rotation, vector3, combatText[l].scale, SpriteEffects.None, 0f);
                     }
                 }
             }
             targetScale = PopupText.TargetScale;
             if (targetScale == 0f)
             {
                 targetScale = 1f;
             }
             DrawItemTextPopups(targetScale);
             PlayerInput.SetZoom_UI();
             spriteBatch.End();
             spriteBatch.Begin(SpriteSortMode.Deferred, BlendState.AlphaBlend, DefaultSamplerState, null, null, null, UIScaleMatrix);
             DrawNetplayStatusText();
             DrawFPS();
             spriteBatch.End();
             spriteBatch.Begin(SpriteSortMode.Deferred, BlendState.AlphaBlend, DefaultSamplerState, null, null, null, GameViewMatrix.ZoomMatrix);
             PlayerInput.SetZoom_World();
             if (BlackFadeIn > 0)
             {
                 if (BlackFadeIn < 0)
                 {
                     BlackFadeIn = 0;
                 }
                 int num19 = BlackFadeIn;
                 if (num19 > 255)
                 {
                     num19 = 255;
                 }
                 BlackFadeIn -= 25;
                 spriteBatch.Draw(TextureAssets.SplashTexture16x9.Value, new Microsoft.Xna.Framework.Rectangle(0, 0, screenWidth, screenHeight), new Microsoft.Xna.Framework.Color(0, 0, 0, num19));
             }
             spriteBatch.End();
             if (!mapFullscreen)
             {
                 if (ignoreErrors)
                 {
                     try
                     {
                         DrawInterface(gameTime);
                     }
                     catch (Exception e3)
                     {
                         TimeLogger.DrawException(e3);
                     }
                 }
                 else
                 {
                     DrawInterface(gameTime);
                 }
             }
             TimeLogger.DetailedDrawTime(27);
         }
         else
         {
             maxQ = true;
         }
         TimeLogger.DetailedDrawTime(37);
         if (mouseLeft)
         {
             mouseLeftRelease = false;
         }
         else
         {
             mouseLeftRelease = true;
         }
         if (mouseRight)
         {
             mouseRightRelease = false;
         }
         else
         {
             mouseRightRelease = true;
         }
         if (!PlayerInput.Triggers.Current.MouseRight && !PlayerInput.Triggers.Current.MouseLeft && !preventStackSplitReset)
         {
             stackSplit = 0;
         }
         if (stackSplit > 0)
         {
             stackSplit--;
             if (stackSplit == 0)
             {
                 preventStackSplitReset = false;
             }
         }
         TimeLogger.RenderTime(renderCount, stopwatch.Elapsed.TotalMilliseconds);
         TimeLogger.EndDrawFrame();
     }
References _drawCycleCounter, CaptureManager.Active, CombatText.alpha, ParticleRendererSettings.AnchorPosition, ApplyColorOfTheSkiesToTiles(), TextureAssets.Background, background, backgroundTarget, BackgroundViewMatrix, backgroundWidth, backWaterTarget, TileBatch.Begin(), bgAlphaFrontLayer, bgDelay, bgLoops, bgLoopsY, bgParallax, bgStartX, bgStartY, Main.SceneArea.bgTopY, bgTopY, BlackFadeIn, bloodMoon, Main.InfoToSetBackColor.BloodMoonActive, SceneMetrics.BloodMoonMonolith, SceneMetrics.BloodTileCount, caveParallax, CheckMonoliths(), WorldSections.ClearMapDraw(), cloudAlpha, CombatText.color, ColorOfTheSkies, FontAssets.CombatText, combatText, ContentThatNeedsRenderTargets, Main.InfoToSetBackColor.CorruptionBiomeInfluence, SceneMetrics.CorruptionTileMax, Main.InfoToSetBackColor.CrimsonBiomeInfluence, SceneMetrics.CrimsonTileMax, TriggersPack.Current, Main.CurrentFrameFlags.Hacks.CurrentBackgroundMatrixForCreditsRoll, UserInterface.CurrentState, dayRate, dedServ, DefaultSamplerState, TimeLogger.DetailedDrawReset(), TimeLogger.DetailedDrawTime(), DoDraw_UpdateCameraPosition(), DoDraw_WallsTilesNPCs(), DoLightTiles(), dontStarveWorld, Draw(), CaptureManager.Draw(), ScreenObstruction.Draw(), ParticleRenderer.Draw(), OverlayManager.Draw(), ScreenDarkness.DrawBack(), DrawBackground(), DrawBackgroundBlackFill(), DrawBG(), DrawCachedNPCs(), DrawCachedProjs(), DrawCacheFirstFractals, DrawCacheNPCsOverPlayers, DrawCacheProjsBehindProjectiles, DrawCacheProjsOverPlayers, DrawCacheProjsOverWiresUI, DrawCursor(), DrawDust(), TimeLogger.DrawException(), DrawFPS(), ScreenDarkness.DrawFront(), DrawGore(), DrawInfernoRings(), DrawInterface(), DrawItems(), DrawItemTextPopups(), DrawMap(), DrawMenu(), DrawNetplayStatusText(), DrawPendingMouseText(), DrawPlayerChat(), DrawPlayerChatBubbles(), DrawPlayers_AfterProjectiles(), DrawProjectiles(), DrawRain(), drawsCountedForFPS, DrawSplash(), DrawStarsInBackground(), DrawStarsInForeground(), DynamicSpriteFontExtensionMethods.DrawString(), DrawSunAndMoon(), DrawSuperSpecialProjectiles(), DrawThickCursor(), CaptureManager.DrawTick(), DrawToMap(), DrawToMap_Section(), drawToScreen, DrawWaters(), MoonlordDeathDrama.DrawWhite(), WiresUI.Settings.DrawWires, DrawWires(), SpriteViewMatrix.EffectMatrix, SpriteViewMatrix.Effects, TileBatch.End(), TimeLogger.EndDrawFrame(), essDir, essScale, SceneMetrics.EvilTileCount, WaterfallManager.FindWaterfalls(), firstTileX, firstTileY, ForcedMinimumZoom, fpsCount, gameMenu, gamePaused, GameViewMatrix, GameZoomTarget, WorldGen.generatingWorld, WorldSections.GetNextMapDraw(), Player.gravDir, Main.InfoToSetBackColor.GraveyardInfluence, GraveyardVisualIntensity, HasInteractibleObjectThatIsNotATile, hideUI, HoverItem, ignoreErrors, InGameUI, InitTargets(), CaptureManager.Instance, Main.InfoToSetBackColor.isInGameMenuOrIsServer, UserInterface.IsVisible, Main.InfoToSetBackColor.JungleBiomeInfluence, SceneMetrics.JungleTileCount, SceneMetrics.JungleTileMax, L, Main.InfoToSetBackColor.LanternNightActive, LanternNight.LanternsUp, Player.lastMouseInterface, lastTileX, lastTileY, Lighting.LightTiles(), loadMap, TextureAssets.MagicPixel, magmaBGFrame, magmaBGFrameCounter, TimeLogger.MapDrawTime(), mapFullscreen, mapStyle, mapTime, mapTimeMax, maxQ, maxRaining, TimeLogger.MenuDrawTime(), menuMode, MenuUI, MinimumZoomComparerX, MinimumZoomComparerY, Player.mouseInterface, TriggersSet.MouseLeft, mouseLeft, mouseLeftRelease, TriggersSet.MouseRight, mouseRight, mouseRightRelease, Main.InfoToSetBackColor.MushroomBiomeInfluence, SceneMetrics.MushroomTileCount, SceneMetrics.MushroomTileMax, myPlayer, netMode, TimeLogger.NewDrawFrame(), Lighting.NotRetro, MapHelper.numUpdateTile, offScreenRange, OnPreDraw, ParticleSystem_World_BehindPlayers, ParticleSystem_World_OverPlayers, player, playerInventory, CombatText.position, Entity.position, PostDrawMenu(), PreDrawMenu(), TilePaintSystemV2.PrepareAllRequests(), TileDrawing.PreparePaintForTilesOnScreen(), preventStackSplitReset, raining, Utils.RandomNextSeed(), Rasterizer, refreshMap, RefreshPlayerDrawOrder(), ReleaseTargets(), render, RenderBackground(), renderCount, renderNow, RenderTiles(), RenderTiles2(), TimeLogger.RenderTime(), RenderWalls(), RenderWater(), CombatText.rotation, SamplerStateForCursor, CombatText.scale, Overlays.Scene, sceneBackgroundPos, Main.SceneArea.SceneLocalScreenPositionOffset, sceneTile2Pos, sceneTilePos, sceneWallPos, sceneWaterPos, screenHeight, screenLastPosition, screenPosition, screenTarget, screenTargetSwap, screenWidth, sectionManager, SetBackColor(), PlayerInput.SetDesiredZoomContext(), ParticleRenderer.Settings, PlayerInput.SetZoom_UI(), PlayerInput.SetZoom_Unscaled(), PlayerInput.SetZoom_World(), shimmerAlpha, showSplash, sign, SmoothedMushroomLightInfluence, SortDrawCacheWorms(), TimeLogger.SplashDrawTime(), TextureAssets.SplashTexture16x9, spriteBatch, stackCounter, stackDelay, stackSplit, sunCircle, superFastStack, CombatText.TargetScale, PopupText.TargetScale, targetSet, CombatText.text, tileBatch, TileFrameSeed, TilePaintSystem, TilesRenderer, timesTriedToFastStack, Player.ToggleInv(), Main.SceneArea.totalHeight, Main.SceneArea.totalWidth, Transform, SpriteViewMatrix.TransformationMatrix, SpriteViewMatrix.Translation, PlayerInput.Triggers, UIScaleMatrix, unityMouseOver, Camera.UnscaledSize, CaptureManager.Update(), UpdateAtmosphereTransparencyToSkyColor(), UpdateDisplaySettings(), Lighting.UpdateEveryFrame, PlayerInput.UpdateMainMouse(), updateMap, Asset< T >.Value, waterfallManager, waterTarget, worldSurface, SpriteViewMatrix.Zoom, and SpriteViewMatrix.ZoomMatrix.
Referenced by Draw().