Terraria: Main.DoDraw_Tiles_NonSolid
DoDraw_Tiles_NonSolid()
void Main.DoDraw_Tiles_NonSolid () inline private
     {
         TilesRenderer.PreDrawTiles(solidLayer: false, !drawToScreen, intoRenderTargets: false);
         if (drawToScreen)
         {
             DrawTiles(solidLayer: false, !drawToScreen, intoRenderTargets: false);
             TimeLogger.DetailedDrawReset();
         }
         else
         {
             spriteBatch.Draw(tile2Target, sceneTile2Pos - screenPosition, Microsoft.Xna.Framework.Color.White);
             TimeLogger.DetailedDrawTime(15);
         }
         spriteBatch.End();
         try
         {
             DrawTileEntities(solidLayer: false, !drawToScreen, intoRenderTargets: false);
         }
         catch (Exception e)
         {
             TimeLogger.DrawException(e);
         }
         spriteBatch.Begin(SpriteSortMode.Deferred, BlendState.AlphaBlend, DefaultSamplerState, DepthStencilState.None, Rasterizer, null, Transform);
     }
References DefaultSamplerState, TimeLogger.DetailedDrawReset(), TimeLogger.DetailedDrawTime(), TimeLogger.DrawException(), DrawTileEntities(), DrawTiles(), drawToScreen, TileDrawing.PreDrawTiles(), Rasterizer, sceneTile2Pos, screenPosition, spriteBatch, tile2Target, TilesRenderer, and Transform.
Referenced by DoDraw_WallsTilesNPCs().