Terraria: Main.OpenResourcePacksMenu
OpenResourcePacksMenu()
static void Main.OpenResourcePacksMenu (UIState uiStateToGoBackTo) inline static
     {
         menuMode = 888;
         MenuUI.SetState(new UIResourcePackSelectionMenu(uiStateToGoBackTo, AssetSourceController, AssetInitializer.CreateResourcePackList(instance.Services)));
     }
References AssetInitializer.CreateResourcePackList(), instance, menuMode, MenuUI, Game.Services, and UserInterface.SetState().
Referenced by UIWorkshopHub.Click_OpenResourcePacksMenu(), and DrawMenu().