Terraria: Main.DrawSuperSpecialProjectiles
DrawSuperSpecialProjectiles()
void Main.DrawSuperSpecialProjectiles (List< int > projCache, bool startSpriteBatch = true) inline protected
     {
         if (startSpriteBatch)
         {
             spriteBatch.Begin(SpriteSortMode.Deferred, BlendState.AlphaBlend, DefaultSamplerState, DepthStencilState.None, Rasterizer, null, Transform);
         }
         for (int i = 0; i < projCache.Count; i++)
         {
             try
             {
                 int num = projCache[i];
                 Projectile projectile = Main.projectile[num];
                 int owner = projectile.owner;
                 Player other = Main.player[owner];
                 if (playerVisualClone[owner] == null)
                 {
                     playerVisualClone[owner] = new Player();
                 }
                 Player player = playerVisualClone[owner];
                 player.CopyVisuals(other);
                 player.isFirstFractalAfterImage = true;
                 player.firstFractalAfterImageOpacity = projectile.Opacity * 1f;
                 player.ResetEffects();
                 player.ResetVisibleAccessories();
                 player.UpdateDyes();
                 player.DisplayDollUpdate();
                 player.UpdateSocialShadow();
                 player.itemAnimationMax = 60;
                 player.itemAnimation = (int)projectile.localAI[0];
                 player.itemRotation = projectile.velocity.ToRotation();
                 player.heldProj = num;
                 player.Center = projectile.Center - projectile.velocity.SafeNormalize(Vector2.Zero) * 42f;
                 player.direction = ((projectile.velocity.X > 0f) ? 1 : (-1));
                 player.itemRotation = (float)Math.Atan2(projectile.velocity.Y * (float)player.direction, projectile.velocity.X * (float)player.direction);
                 player.velocity.Y = 0.01f;
                 player.wingFrame = 2;
                 player.PlayerFrame();
                 player.socialIgnoreLight = true;
                 PlayerRenderer.DrawPlayer(Camera, player, player.position, 0f, player.fullRotationOrigin);
             }
             catch (Exception e)
             {
                 TimeLogger.DrawException(e);
                 Main.projectile[projCache[i]].active = false;
             }
         }
         if (startSpriteBatch)
         {
             spriteBatch.End();
         }
     }
References Entity.active, Entity.Center, Player.CopyVisuals(), DefaultSamplerState, Entity.direction, Player.DisplayDollUpdate(), TimeLogger.DrawException(), IPlayerRenderer.DrawPlayer(), Player.firstFractalAfterImageOpacity, Player.fullRotationOrigin, Player.heldProj, Player.isFirstFractalAfterImage, Player.itemAnimation, Player.itemAnimationMax, Player.itemRotation, Projectile.localAI, Projectile.Opacity, Projectile.owner, Player, player, Player.PlayerFrame(), PlayerRenderer, playerVisualClone, Entity.position, projectile, Rasterizer, Player.ResetEffects(), Player.ResetVisibleAccessories(), Player.socialIgnoreLight, spriteBatch, Transform, Player.UpdateDyes(), Player.UpdateSocialShadow(), Entity.velocity, and Player.wingFrame.
Referenced by DoDraw(), and DrawCapture().