Terraria: Main.DoDraw_Tiles_Solid
DoDraw_Tiles_Solid()
void Main.DoDraw_Tiles_Solid () inline private
     {
         TilesRenderer.PreDrawTiles(solidLayer: true, !drawToScreen, intoRenderTargets: false);
         tileBatch.Begin(Rasterizer, Transform);
         spriteBatch.Begin(SpriteSortMode.Deferred, BlendState.AlphaBlend, DefaultSamplerState, DepthStencilState.None, Rasterizer, null, Transform);
         try
         {
             if (drawToScreen)
             {
                 DrawTiles(solidLayer: true, !drawToScreen, intoRenderTargets: false);
             }
             else
             {
                 spriteBatch.Draw(tileTarget, sceneTilePos - screenPosition, Microsoft.Xna.Framework.Color.White);
                 TimeLogger.DetailedDrawTime(17);
             }
         }
         catch (Exception e)
         {
             TimeLogger.DrawException(e);
         }
         tileBatch.End();
         spriteBatch.End();
         DrawTileEntities(solidLayer: true, !drawToScreen, intoRenderTargets: false);
         spriteBatch.Begin(SpriteSortMode.Deferred, BlendState.AlphaBlend, DefaultSamplerState, DepthStencilState.None, Rasterizer, null, Transform);
         try
         {
             player[myPlayer].hitReplace.DrawFreshAnimations(spriteBatch);
             player[myPlayer].hitTile.DrawFreshAnimations(spriteBatch);
         }
         catch (Exception e2)
         {
             TimeLogger.DrawException(e2);
         }
         spriteBatch.End();
     }
References TileBatch.Begin(), DefaultSamplerState, TimeLogger.DetailedDrawTime(), TimeLogger.DrawException(), HitTile.DrawFreshAnimations(), DrawTileEntities(), DrawTiles(), drawToScreen, TileBatch.End(), Player.hitReplace, Player.hitTile, myPlayer, player, TileDrawing.PreDrawTiles(), Rasterizer, sceneTilePos, screenPosition, spriteBatch, tileBatch, TilesRenderer, tileTarget, and Transform.
Referenced by DoDraw_WallsTilesNPCs().