Terraria: Main.ReportInvasionProgress
ReportInvasionProgress()
static void Main.ReportInvasionProgress (int progress, int progressMax, int icon, int progressWave) inline static
     {
         invasionProgress = progress;
         invasionProgressMax = progressMax;
         invasionProgressIcon = icon;
         invasionProgressWave = progressWave;
         invasionProgressDisplayLeft = 160;
     }
References invasionProgress, invasionProgressDisplayLeft, invasionProgressIcon, invasionProgressMax, and invasionProgressWave.
Referenced by NPC.checkDead(), CheckInvasionProgressDisplay(), DD2Event.CheckProgress(), NPC.CheckProgressFrostMoon(), NPC.CheckProgressPumpkinMoon(), MessageBuffer.GetData(), DD2Event.ReportEventProgress(), DD2Event.StartInvasion(), and DD2Event.UpdateTime().