Terraria: Main.UpdateInvasion
UpdateInvasion()
static void Main.UpdateInvasion () inline static private
     {
         if (invasionType <= 0)
         {
             return;
         }
         if (invasionSize <= 0)
         {
             if (invasionType == 1)
             {
                 NPC.SetEventFlagCleared(ref NPC.downedGoblins, 0);
                 if (netMode == 2)
                 {
                     NetMessage.SendData(7);
                 }
                 AchievementsHelper.NotifyProgressionEvent(10);
             }
             else if (invasionType == 2)
             {
                 NPC.SetEventFlagCleared(ref NPC.downedFrost, 1);
                 AchievementsHelper.NotifyProgressionEvent(12);
             }
             else if (invasionType == 3)
             {
                 NPC.SetEventFlagCleared(ref NPC.downedPirates, 2);
                 AchievementsHelper.NotifyProgressionEvent(11);
             }
             else if (invasionType == 4)
             {
                 NPC.SetEventFlagCleared(ref NPC.downedMartians, 3);
                 AchievementsHelper.NotifyProgressionEvent(13);
             }
             InvasionWarning();
             invasionType = 0;
             invasionDelay = 0;
         }
         if (invasionX == (double)spawnTileX)
         {
             return;
         }
         float num = dayRate;
         if (num < 1f)
         {
             num = 1f;
         }
         if (invasionX > (double)spawnTileX)
         {
             invasionX -= num;
             if (invasionX <= (double)spawnTileX)
             {
                 invasionX = spawnTileX;
                 InvasionWarning();
             }
             else if (num > 0f)
             {
                 invasionWarn--;
             }
         }
         else if (invasionX < (double)spawnTileX)
         {
             invasionX += num;
             if (invasionX >= (double)spawnTileX)
             {
                 invasionX = spawnTileX;
                 InvasionWarning();
             }
             else if (num > 0f)
             {
                 invasionWarn--;
             }
         }
         if (invasionWarn <= 0)
         {
             invasionWarn = 3600;
             InvasionWarning();
         }
     }
References dayRate, NPC.downedFrost, NPC.downedGoblins, NPC.downedMartians, NPC.downedPirates, invasionDelay, invasionSize, invasionType, invasionWarn, InvasionWarning(), invasionX, netMode, AchievementsHelper.NotifyProgressionEvent(), NetMessage.SendData(), NPC.SetEventFlagCleared(), and spawnTileX.
Referenced by DoUpdateInWorld().