Terraria: Main.DrawInterface_36_Cursor
DrawInterface_36_Cursor()
static void Main.DrawInterface_36_Cursor () inline static private
     {
         spriteBatch.End();
         spriteBatch.Begin(SpriteSortMode.Deferred, BlendState.AlphaBlend, SamplerStateForCursor, DepthStencilState.None, RasterizerState.CullCounterClockwise, null, UIScaleMatrix);
         if (cursorOverride != -1)
         {
             Microsoft.Xna.Framework.Color color = new Microsoft.Xna.Framework.Color((int)((float)(int)cursorColor.R * 0.2f), (int)((float)(int)cursorColor.G * 0.2f), (int)((float)(int)cursorColor.B * 0.2f), (int)((float)(int)cursorColor.A * 0.5f));
             Microsoft.Xna.Framework.Color white = cursorColor;
             bool flag = true;
             bool flag2 = true;
             float rotation = 0f;
             Vector2 vector = default(Vector2);
             float num = 1f;
             if (cursorOverride == 2)
             {
                 flag = false;
                 white = Microsoft.Xna.Framework.Color.White;
                 num = 0.7f;
                 vector = new Vector2(0.1f);
             }
             switch (cursorOverride)
             {
             case 2:
                 flag = false;
                 white = Microsoft.Xna.Framework.Color.White;
                 num = 0.7f;
                 vector = new Vector2(0.1f);
                 break;
             case 3:
             case 6:
             case 7:
             case 8:
             case 9:
             case 10:
                 flag = false;
                 white = Microsoft.Xna.Framework.Color.White;
                 break;
             }
             if (flag)
             {
                 spriteBatch.Draw(TextureAssets.Cursors[cursorOverride].Value, new Vector2(mouseX + 1, mouseY + 1), null, color, rotation, vector * TextureAssets.Cursors[cursorOverride].Value.Size(), cursorScale * 1.1f * num, SpriteEffects.None, 0f);
             }
             if (flag2)
             {
                 spriteBatch.Draw(TextureAssets.Cursors[cursorOverride].Value, new Vector2(mouseX, mouseY), null, white, rotation, vector * TextureAssets.Cursors[cursorOverride].Value.Size(), cursorScale * num, SpriteEffects.None, 0f);
             }
         }
         else if (SmartCursorIsUsed)
         {
             DrawCursor(DrawThickCursor(smart: true), smart: true);
         }
         else
         {
             DrawCursor(DrawThickCursor());
         }
     }
References cursorColor, cursorOverride, TextureAssets.Cursors, cursorScale, DrawCursor(), DrawThickCursor(), mouseX, mouseY, SamplerStateForCursor, SmartCursorIsUsed, spriteBatch, UIScaleMatrix, and Asset< T >.Value.
Referenced by DrawPendingMouseText(), and SetupDrawInterfaceLayers().