Terraria: Main.DoUpdate_Enter_ToggleChat
DoUpdate_Enter_ToggleChat()
static void Main.DoUpdate_Enter_ToggleChat () inline static private
     {
         if (keyState.IsKeyDown(Microsoft.Xna.Framework.Input.Keys.Enter) && !keyState.IsKeyDown(Microsoft.Xna.Framework.Input.Keys.LeftAlt) && !keyState.IsKeyDown(Microsoft.Xna.Framework.Input.Keys.RightAlt) && hasFocus)
         {
             if (chatRelease && !drawingPlayerChat && !editSign && !editChest && !gameMenu && !keyState.IsKeyDown(Microsoft.Xna.Framework.Input.Keys.Escape))
             {
                 SoundEngine.PlaySound(10);
                 OpenPlayerChat();
                 chatText = "";
             }
             chatRelease = false;
         }
         else
         {
             chatRelease = true;
         }
     }
References chatRelease, chatText, drawingPlayerChat, editChest, editSign, gameMenu, hasFocus, keyState, OpenPlayerChat(), and SoundEngine.PlaySound().
Referenced by DoUpdate().