Terraria: Main.InputTextChest
InputTextChest()
static void Main.InputTextChest () inline static
     {
         if (!IngameFancyUI.CanShowVirtualKeyboard(2) || UIVirtualKeyboard.KeyboardContext != 2)
         {
             npcChatText = GetInputText(npcChatText);
             if (inputTextEnter)
             {
                 ChestUI.RenameChestSubmit(player[myPlayer]);
             }
             else if (inputTextEscape)
             {
                 ChestUI.RenameChestCancel();
             }
         }
     }
References IngameFancyUI.CanShowVirtualKeyboard(), GetInputText(), inputTextEnter, inputTextEscape, UIVirtualKeyboard.KeyboardContext, myPlayer, npcChatText, player, ChestUI.RenameChestCancel(), and ChestUI.RenameChestSubmit().
Referenced by Player.Update().