Terraria: Main.DrawFPS
DrawFPS()
void Main.DrawFPS () inline protected
     {
         if (showFrameRate)
         {
             string text = string.Concat(frameRate);
             text = text + " (" + (Liquid.numLiquid + LiquidBuffer.numLiquidBuffer) + ")";
             text = text + " (" + (int)(gfxQuality * 100f) + "%)";
             string text2 = text + " " + debugWords;
             int num = 4;
             if (!gameMenu)
             {
                 num = screenHeight - 24;
             }
             Vector2 vector = new Vector2(4f, num);
             Vector2 vector2 = new Vector2(0f, 0f);
             Vector2 vector3 = FontAssets.MouseText.Value.MeasureString(text2);
             if (PlayerInput.SettingsForUI.ShowGamepadHints && !gameMenu)
             {
                 vector.X = (float)(screenWidth - 4) - vector3.X;
             }
             DynamicSpriteFontExtensionMethods.DrawString(spriteBatch, FontAssets.MouseText.Value, text2, vector, new Microsoft.Xna.Framework.Color(mouseTextColor, mouseTextColor, mouseTextColor, mouseTextColor), 0f, vector2, 1f, SpriteEffects.None, 0f);
         }
     }
References debugWords, DynamicSpriteFontExtensionMethods.DrawString(), frameRate, gameMenu, gfxQuality, Liquid, FontAssets.MouseText, mouseTextColor, LiquidBuffer.numLiquidBuffer, screenHeight, screenWidth, showFrameRate, PlayerInput.SettingsForUI.ShowGamepadHints, spriteBatch, and Asset< T >.Value.
Referenced by DoDraw(), and DrawMenu().