Terraria: Main.DrawInterface_12_IngameFancyUI
DrawInterface_12_IngameFancyUI()
static bool Main.DrawInterface_12_IngameFancyUI () inline static private
     {
         spriteBatch.End();
         spriteBatch.Begin(SpriteSortMode.Deferred, BlendState.AlphaBlend, SamplerStateForCursor, DepthStencilState.None, RasterizerState.CullCounterClockwise, null, UIScaleMatrix);
         InGameUI.Draw(spriteBatch, _drawInterfaceGameTime);
         bool result = true;
         if (inFancyUI && !IngameFancyUI.Draw(spriteBatch, _drawInterfaceGameTime))
         {
             result = false;
             DrawPendingMouseText();
         }
         return result;
     }
References _drawInterfaceGameTime, IngameFancyUI.Draw(), UserInterface.Draw(), DrawPendingMouseText(), inFancyUI, InGameUI, SamplerStateForCursor, spriteBatch, and UIScaleMatrix.
Referenced by SetupDrawInterfaceLayers().