Terraria: Main.OpenClothesWindow
OpenClothesWindow()
static void Main.OpenClothesWindow () inline static
     {
         if (clothesWindow)
         {
             CancelClothesWindow();
             return;
         }
         hBar = -1f;
         lBar = -1f;
         sBar = -1f;
         playerInventory = false;
         npcChatText = "";
         clothesWindow = true;
         SoundEngine.PlaySound(10);
         selClothes = 0;
         oldClothesColor[0] = player[myPlayer].shirtColor;
         oldClothesColor[1] = player[myPlayer].underShirtColor;
         oldClothesColor[2] = player[myPlayer].pantsColor;
         oldClothesColor[3] = player[myPlayer].shoeColor;
         oldClothesColor[4] = player[myPlayer].eyeColor;
         oldClothesColor[5] = player[myPlayer].skinColor;
         if (dresserInterfaceDummy == null)
         {
             dresserInterfaceDummy = new Player();
         }
         oldClothesStyle = player[myPlayer].skinVariant;
     }
References CancelClothesWindow(), clothesWindow, dresserInterfaceDummy, Player.eyeColor, hBar, lBar, myPlayer, npcChatText, oldClothesColor, oldClothesStyle, Player.pantsColor, Player, player, playerInventory, SoundEngine.PlaySound(), sBar, selClothes, Player.shirtColor, Player.shoeColor, Player.skinColor, Player.skinVariant, and Player.underShirtColor.
Referenced by Player.TileInteractionsUse().