Terraria: Main.DoDraw_DrawNPCsBehindTiles
DoDraw_DrawNPCsBehindTiles()
void Main.DoDraw_DrawNPCsBehindTiles () inline private
     {
         DrawCachedProjs(DrawCacheProjsBehindNPCsAndTiles);
         spriteBatch.Begin(SpriteSortMode.Deferred, BlendState.AlphaBlend, DefaultSamplerState, DepthStencilState.None, Rasterizer, null, Transform);
         try
         {
             DrawNPCs(behindTiles: true);
             TimeLogger.DetailedDrawTime(18);
         }
         catch (Exception e)
         {
             TimeLogger.DrawException(e);
         }
         spriteBatch.End();
     }
References DefaultSamplerState, TimeLogger.DetailedDrawTime(), DrawCachedProjs(), DrawCacheProjsBehindNPCsAndTiles, TimeLogger.DrawException(), DrawNPCs(), Rasterizer, spriteBatch, and Transform.
Referenced by DoDraw_WallsTilesNPCs().