Terraria: Main.AnimateTiles_CritterCages
AnimateTiles_CritterCages()
static void Main.AnimateTiles_CritterCages () inline static
References birdCageFrame, birdCageFrameCounter, blueBirdCageFrame, blueBirdCageFrameCounter, bunnyCageFrame, bunnyCageFrameCounter, butterflyCageFrame, butterflyCageFrameCounter, butterflyCageMode, cageFrames, critterCage, duckCageFrame, duckCageFrameCounter, fairyJarFrame, fairyJarFrameCounter, fishBowlFrame, fishBowlFrameCounter, fishBowlFrameMode, frogCageFrame, frogCageFrameCounter, grasshopperCageFrame, grasshopperCageFrameCounter, grebeCageFrame, grebeCageFrameCounter, jellyfishCageFrame, jellyfishCageFrameCounter, jellyfishCageMode, ladybugCageFrame, ladybugCageFrameCounter, lavaFishBowlFrame, lavaFishBowlFrameCounter, macawCageFrame, macawCageFrameCounter, maggotCageFrame, maggotCageFrameCounter, mallardCageFrame, mallardCageFrameCounter, mouseCageFrame, mouseCageFrameCounter, UnifiedRandom.Next(), penguinCageFrame, penguinCageFrameCounter, rand, ratCageFrame, ratCageFrameCounter, redBirdCageFrame, redBirdCageFrameCounter, scorpionCageFrame, scorpionCageFrameCounter, seagullCageFrame, seagullCageFrameCounter, seahorseCageFrame, seahorseCageFrameCounter, slugCageFrame, slugCageFrameCounter, snail2CageFrame, snail2CageFrameCounter, snailCageFrame, snailCageFrameCounter, squirrelCageFrame, squirrelCageFrameCounter, squirrelCageFrameCounterOrange, squirrelCageFrameOrange, turtleCageFrame, turtleCageFrameCounter, UpdateDragonflyJarFrames(), UpdateOwlCageFrames(), waterStriderCageFrame, waterStriderCageFrameCounter, wormCageFrame, and wormCageFrameCounter.
Referenced by AnimateTiles(), and Initialize_TileAndNPCData2().