Terraria: Main.TeleportEffect
TeleportEffect()
static void Main.TeleportEffect (Microsoft.Xna.Framework.Rectangle effectRect, int Style, int extraInfo = 0, float dustCountMult = 1f, TeleportationSide side = TeleportationSide.Entry, Vector2 otherPosition = default(Vector2)) inline static
     {
         switch (Style)
         {
         case 0:
         {
             SoundEngine.PlaySound(SoundID.Item6, effectRect.X + effectRect.Width / 2, effectRect.Y + effectRect.Height / 2);
             int num2 = effectRect.Width * effectRect.Height / 5;
             num2 = (int)((float)num2 * dustCountMult);
             for (int j = 0; j < num2; j++)
             {
                 int num3 = Dust.NewDust(new Vector2(effectRect.X, effectRect.Y), effectRect.Width, effectRect.Height, 159);
                 Main.dust[num3].scale = (float)rand.Next(20, 70) * 0.01f;
                 if (j < 10)
                 {
                     Main.dust[num3].scale += 0.25f;
                 }
                 if (j < 5)
                 {
                     Main.dust[num3].scale += 0.25f;
                 }
             }
             break;
         }
         case 1:
         {
             SoundEngine.PlaySound(SoundID.Item8, effectRect.X + effectRect.Width / 2, effectRect.Y + effectRect.Height / 2);
             int num10 = effectRect.Width * effectRect.Height / 5;
             num10 = (int)((float)num10 * dustCountMult);
             for (int num11 = 0; num11 < num10; num11++)
             {
                 int num12 = Dust.NewDust(new Vector2(effectRect.X, effectRect.Y), effectRect.Width, effectRect.Height, 164);
                 Main.dust[num12].scale = (float)rand.Next(20, 70) * 0.01f;
                 if (num11 < 10)
                 {
                     Main.dust[num12].scale += 0.25f;
                 }
                 if (num11 < 5)
                 {
                     Main.dust[num12].scale += 0.25f;
                 }
             }
             break;
         }
         case 2:
         {
             int num15 = (int)(50f * dustCountMult);
             for (int num16 = 0; num16 < num15; num16++)
             {
                 Main.dust[Dust.NewDust(new Vector2(effectRect.X, effectRect.Y), effectRect.Width, effectRect.Height, 58, 0f, 0f, 150, Microsoft.Xna.Framework.Color.GhostWhite, 1.2f)].velocity *= 0.5f;
             }
             break;
         }
         case 3:
         {
             SoundEngine.PlaySound(SoundID.Item6, effectRect.X + effectRect.Width / 2, effectRect.Y + effectRect.Height / 2);
             int num5 = (int)(50f * dustCountMult);
             for (int l = 0; l < num5; l++)
             {
                 int num6 = Dust.NewDust(new Vector2(effectRect.X, effectRect.Y), effectRect.Width, effectRect.Height, 180);
                 Main.dust[num6].noGravity = true;
                 for (int m = 0; m < 5; m++)
                 {
                     if (rand.Next(3) == 0)
                     {
                         Main.dust[num6].velocity *= 0.75f;
                     }
                 }
                 if (rand.Next(3) == 0)
                 {
                     Main.dust[num6].velocity *= 2f;
                     Main.dust[num6].scale *= 1.2f;
                 }
                 if (rand.Next(3) == 0)
                 {
                     Main.dust[num6].velocity *= 2f;
                     Main.dust[num6].scale *= 1.2f;
                 }
                 if (rand.Next(2) == 0)
                 {
                     Main.dust[num6].fadeIn = (float)rand.Next(75, 100) * 0.01f;
                     Main.dust[num6].scale = (float)rand.Next(25, 75) * 0.01f;
                 }
                 Main.dust[num6].scale *= 0.8f;
             }
             break;
         }
         case 4:
         {
             SoundEngine.PlaySound(SoundID.Item8, effectRect.X + effectRect.Width / 2, effectRect.Y + effectRect.Height / 2);
             int num17 = effectRect.Width * effectRect.Height / 5;
             num17 = (int)((float)num17 * dustCountMult);
             for (int num18 = 0; num18 < num17; num18++)
             {
                 Dust obj4 = Main.dust[Dust.NewDust(effectRect.TopLeft(), effectRect.Width, effectRect.Height, 263)];
                 obj4.color = PortalHelper.GetPortalColor(extraInfo);
                 obj4.noLight = true;
                 obj4.noGravity = true;
                 obj4.scale = 1.2f;
                 obj4.fadeIn = 0.4f;
                 obj4.color.A = byte.MaxValue;
             }
             break;
         }
         case 5:
         {
             Vector2 position = effectRect.TopLeft();
             int num8 = (int)(100f * dustCountMult);
             for (int num9 = 0; num9 < num8; num9++)
             {
                 Dust obj3 = Dust.NewDustDirect(position, effectRect.Width, effectRect.Height + 24, Dust.dustWater());
                 obj3.velocity.Y *= 0f;
                 obj3.velocity.Y -= 3.5f;
                 obj3.velocity.X *= 1.5f;
                 obj3.scale = 0.8f;
                 obj3.alpha = 130;
                 obj3.noGravity = true;
                 obj3.fadeIn = 1.2f;
             }
             SoundEngine.PlaySound(19, effectRect.Center.ToVector2(), 0);
             break;
         }
         case 7:
         {
             Vector2 position2 = effectRect.TopLeft();
             int num19 = (int)(50f * dustCountMult);
             for (int num20 = 0; num20 < num19; num20++)
             {
                 Dust obj5 = Dust.NewDustDirect(position2, effectRect.Width, effectRect.Height + 24, 35);
                 obj5.velocity.Y *= 0f;
                 obj5.velocity.Y -= 3.5f;
                 obj5.velocity.X *= 1.5f;
                 obj5.scale = 0.8f;
                 obj5.alpha = 130;
                 obj5.noGravity = true;
                 obj5.fadeIn = 1.2f;
             }
             SoundEngine.PlaySound(SoundID.Item8, effectRect.Center.ToVector2());
             break;
         }
         case 9:
         {
             effectRect.Inflate(15, 15);
             int num13 = (int)(100f * dustCountMult);
             for (int num14 = 0; num14 < num13; num14++)
             {
                 TeleportPylonsSystem.SpawnInWorldDust(extraInfo, effectRect);
             }
             SoundEngine.PlaySound(SoundID.Item6, effectRect.Center.X, effectRect.Center.Y);
             break;
         }
         case 10:
         {
             effectRect.Inflate(15, 15);
             int num7 = (int)(60f * dustCountMult);
             Vector2 vector = otherPosition - effectRect.TopLeft();
             for (int n = 0; n < num7; n++)
             {
                 float fadeIn = 0.4f + rand.NextFloat();
                 float scale = 0.4f + rand.NextFloat();
                 Microsoft.Xna.Framework.Color newColor = hslToRgb(0.66f + rand.NextFloat() * 0.24f, 1f, 0.5f);
                 Dust dust = Dust.NewDustDirect(effectRect.TopLeft(), effectRect.Width, effectRect.Height, 267, 0f, 0f, 127, newColor);
                 dust.scale = (float)rand.Next(20, 70) * 0.01f;
                 if (n < 10)
                 {
                     dust.scale += 0.25f;
                 }
                 if (n < 5)
                 {
                     dust.scale += 0.25f;
                 }
                 if ((float)n < (float)num7 * 0.8f)
                 {
                     dust.velocity += vector * 0.1f * rand.NextFloat();
                 }
                 dust.noGravity = true;
                 dust.noLight = true;
                 dust.scale = scale;
                 dust.fadeIn = fadeIn;
                 if (dust.dustIndex != 6000)
                 {
                     Dust obj2 = Dust.CloneDust(dust);
                     obj2.scale *= 0.65f;
                     obj2.fadeIn *= 0.65f;
                     obj2.color = new Microsoft.Xna.Framework.Color(255, 255, 255, 255);
                 }
             }
             SoundEngine.PlaySound(SoundID.Item8, effectRect.Center.X, effectRect.Center.Y);
             break;
         }
         case 11:
         {
             for (int k = 0; k < 50; k++)
             {
                 int num4 = rand.Next(4);
                 Microsoft.Xna.Framework.Color color = Microsoft.Xna.Framework.Color.Green;
                 switch (num4)
                 {
                 case 0:
                 case 1:
                     color = new Microsoft.Xna.Framework.Color(100, 255, 100);
                     break;
                 case 2:
                     color = Microsoft.Xna.Framework.Color.Yellow;
                     break;
                 case 3:
                     color = Microsoft.Xna.Framework.Color.White;
                     break;
                 }
                 Dust obj = Dust.NewDustPerfect(rand.NextVector2FromRectangle(effectRect), 267);
                 obj.noGravity = true;
                 obj.color = color;
                 obj.velocity *= 2f;
                 obj.scale = 0.8f + rand.NextFloat() * 0.6f;
                 obj.fadeIn = 0.5f;
             }
             break;
         }
         case 13:
         {
             SoundEngine.PlaySound(SoundID.Item8, effectRect.Center.ToVector2());
             for (int i = 0; i < 21; i++)
             {
                 int num = Dust.NewDust(rand.NextVector2FromRectangle(effectRect), 2, 2, 27, 0f, 0f, 100, default(Microsoft.Xna.Framework.Color), rand.Next(1, 3));
                 Main.dust[num].velocity *= 1.75f;
                 if (i % 3 == 0)
                 {
                     Main.dust[num].velocity *= 1.5f;
                 }
                 Main.dust[num].noLightEmittence = true;
                 Main.dust[num].noGravity = true;
             }
             break;
         }
         }
     }
References Dust.alpha, Dust.CloneDust(), Dust.color, dust, Dust.dustIndex, Dust.dustWater(), Dust.fadeIn, PortalHelper.GetPortalColor(), hslToRgb(), SoundID.Item6, SoundID.Item8, Dust.NewDust(), Dust.NewDustDirect(), Dust.NewDustPerfect(), UnifiedRandom.Next(), Dust.noGravity, Dust.noLight, Dust.noLightEmittence, SoundEngine.PlaySound(), rand, Dust.scale, TeleportPylonsSystem.SpawnInWorldDust(), and Dust.velocity.
Referenced by NPC.Teleport(), and Player.Teleport().