Terraria: Main.StartRain
StartRain()
static void Main.StartRain () inline static
     {
         int num = 86400;
         int num2 = num / 24;
         int num3 = rand.Next(num2 * 8, num);
         if (rand.Next(3) == 0)
         {
             num3 += rand.Next(0, num2);
         }
         if (rand.Next(4) == 0)
         {
             num3 += rand.Next(0, num2 * 2);
         }
         if (rand.Next(5) == 0)
         {
             num3 += rand.Next(0, num2 * 2);
         }
         if (rand.Next(6) == 0)
         {
             num3 += rand.Next(0, num2 * 3);
         }
         if (rand.Next(7) == 0)
         {
             num3 += rand.Next(0, num2 * 4);
         }
         if (rand.Next(8) == 0)
         {
             num3 += rand.Next(0, num2 * 5);
         }
         float num4 = 1f;
         if (rand.Next(2) == 0)
         {
             num4 += 0.05f;
         }
         if (rand.Next(3) == 0)
         {
             num4 += 0.1f;
         }
         if (rand.Next(4) == 0)
         {
             num4 += 0.15f;
         }
         if (rand.Next(5) == 0)
         {
             num4 += 0.2f;
         }
         rainTime = (int)((float)num3 * num4);
         ChangeRain();
         raining = true;
     }
References ChangeRain(), UnifiedRandom.Next(), raining, rainTime, and rand.
Referenced by CreativePowers.ModifyRainPower.UpdateInfoFromSliderValueCache(), and UpdateTime().