Terraria: Main.UpdateWorldPreparationState
UpdateWorldPreparationState()
static void Main.UpdateWorldPreparationState () inline static
     {
         if (netMode != 1)
         {
             _worldPreparationState = WorldPreparationState.Ready;
             return;
         }
         if (netMode == 1 && gameMenu && _worldPreparationState == WorldPreparationState.Ready)
         {
             _worldPreparationState = WorldPreparationState.AwaitingData;
         }
         if (netMode == 1 && _worldPreparationState == WorldPreparationState.ProcessingData)
         {
             _worldPreparationState = WorldPreparationState.Ready;
             gameMenu = false;
             FixUIScale();
             ChatHelper.ShowCachedMessages();
             ChatHelper.ClearDelayedMessagesCache();
         }
     }
References _worldPreparationState, ChatHelper.ClearDelayedMessagesCache(), FixUIScale(), gameMenu, netMode, and ChatHelper.ShowCachedMessages().
Referenced by DoUpdate().