Terraria: Main.DoDraw_WallsAndBlacks
DoDraw_WallsAndBlacks()
void Main.DoDraw_WallsAndBlacks () inline private
     {
         if (drawToScreen)
         {
             DrawBlack();
             tileBatch.Begin();
             DrawWalls();
             tileBatch.End();
         }
         else
         {
             spriteBatch.Draw(blackTarget, sceneTilePos - screenPosition, Microsoft.Xna.Framework.Color.White);
             TimeLogger.DetailedDrawTime(13);
             spriteBatch.Draw(wallTarget, sceneWallPos - screenPosition, Microsoft.Xna.Framework.Color.White);
             TimeLogger.DetailedDrawTime(14);
         }
         Overlays.Scene.Draw(spriteBatch, RenderLayers.Walls);
     }
References TileBatch.Begin(), blackTarget, TimeLogger.DetailedDrawTime(), OverlayManager.Draw(), DrawBlack(), drawToScreen, DrawWalls(), TileBatch.End(), Overlays.Scene, sceneTilePos, sceneWallPos, screenPosition, spriteBatch, tileBatch, and wallTarget.
Referenced by DoDraw_WallsTilesNPCs().