Terraria: Main.DrawDust
DrawDust()
void Main.DrawDust () inline protected
     {
         Microsoft.Xna.Framework.Rectangle rectangle = new Microsoft.Xna.Framework.Rectangle((int)screenPosition.X - 500, (int)screenPosition.Y - 50, screenWidth + 1000, screenHeight + 100);
         rectangle = new Microsoft.Xna.Framework.Rectangle((int)screenPosition.X - 1000, (int)screenPosition.Y - 1050, screenWidth + 2000, screenHeight + 2100);
         Microsoft.Xna.Framework.Rectangle rectangle2 = rectangle;
         ArmorShaderData armorShaderData = null;
         spriteBatch.Begin(SpriteSortMode.Deferred, BlendState.AlphaBlend, SamplerState.PointClamp, DepthStencilState.None, RasterizerState.CullNone, null, Transform);
         for (int i = 0; i < maxDustToDraw; i++)
         {
             Dust dust = Main.dust[i];
             if (!dust.active)
             {
                 continue;
             }
             if ((dust.type >= 130 && dust.type <= 134) || (dust.type >= 219 && dust.type <= 223) || dust.type == 226 || dust.type == 278)
             {
                 rectangle = rectangle2;
             }
             if (new Microsoft.Xna.Framework.Rectangle((int)dust.position.X, (int)dust.position.Y, 4, 4).Intersects(rectangle))
             {
                 float scale = dust.GetVisualScale();
                 if (dust.shader != armorShaderData)
                 {
                     spriteBatch.End();
                     armorShaderData = dust.shader;
                     if (armorShaderData == null)
                     {
                         spriteBatch.Begin(SpriteSortMode.Deferred, BlendState.AlphaBlend, SamplerState.PointClamp, DepthStencilState.None, RasterizerState.CullNone, null, Transform);
                     }
                     else
                     {
                         spriteBatch.Begin(SpriteSortMode.Immediate, BlendState.AlphaBlend, SamplerState.PointClamp, DepthStencilState.None, RasterizerState.CullNone, null, Transform);
                         dust.shader.Apply(null);
                     }
                 }
                 if (dust.type >= 130 && dust.type <= 134)
                 {
                     float num = Math.Abs(dust.velocity.X) + Math.Abs(dust.velocity.Y);
                     num *= 0.3f;
                     num *= 10f;
                     if (num > 10f)
                     {
                         num = 10f;
                     }
                     for (int j = 0; (float)j < num; j++)
                     {
                         Vector2 velocity = dust.velocity;
                         Vector2 vector = dust.position - velocity * j;
                         float scale2 = dust.scale * (1f - (float)j / 10f);
                         Microsoft.Xna.Framework.Color color = Lighting.GetColor((int)((double)dust.position.X + 4.0) / 16, (int)((double)dust.position.Y + 4.0) / 16);
                         color = dust.GetAlpha(color);
                         spriteBatch.Draw(TextureAssets.Dust.Value, vector - screenPosition, dust.frame, color, dust.rotation, new Vector2(4f, 4f), scale2, SpriteEffects.None, 0f);
                     }
                 }
                 else if (dust.type == 278)
                 {
                     float num2 = Math.Abs(dust.velocity.X) + Math.Abs(dust.velocity.Y);
                     num2 *= 0.3f;
                     num2 *= 10f;
                     if (num2 > 10f)
                     {
                         num2 = 10f;
                     }
                     Vector2 origin = new Vector2(4f, 4f);
                     for (int k = 0; (float)k < num2; k++)
                     {
                         Vector2 velocity2 = dust.velocity;
                         Vector2 vector2 = dust.position - velocity2 * k;
                         float scale3 = dust.scale * (1f - (float)k / 10f);
                         Microsoft.Xna.Framework.Color color2 = Lighting.GetColor((int)(dust.position.X + 4f) / 16, (int)(dust.position.Y + 4f) / 16);
                         color2 = dust.GetAlpha(color2);
                         spriteBatch.Draw(TextureAssets.Dust.Value, vector2 - screenPosition, dust.frame, color2, dust.rotation, origin, scale3, SpriteEffects.None, 0f);
                     }
                 }
                 else if (dust.type >= 219 && dust.type <= 223 && dust.fadeIn == 0f)
                 {
                     float num3 = Math.Abs(dust.velocity.X) + Math.Abs(dust.velocity.Y);
                     num3 *= 0.3f;
                     num3 *= 10f;
                     if (num3 > 10f)
                     {
                         num3 = 10f;
                     }
                     for (int l = 0; (float)l < num3; l++)
                     {
                         Vector2 velocity3 = dust.velocity;
                         Vector2 vector3 = dust.position - velocity3 * l;
                         float scale4 = dust.scale * (1f - (float)l / 10f);
                         Microsoft.Xna.Framework.Color color3 = Lighting.GetColor((int)((double)dust.position.X + 4.0) / 16, (int)((double)dust.position.Y + 4.0) / 16);
                         color3 = dust.GetAlpha(color3);
                         spriteBatch.Draw(TextureAssets.Dust.Value, vector3 - screenPosition, dust.frame, color3, dust.rotation, new Vector2(4f, 4f), scale4, SpriteEffects.None, 0f);
                     }
                 }
                 else if (dust.type == 264 && dust.fadeIn == 0f)
                 {
                     float num4 = Math.Abs(dust.velocity.X) + Math.Abs(dust.velocity.Y);
                     num4 *= 10f;
                     if (num4 > 10f)
                     {
                         num4 = 10f;
                     }
                     for (int m = 0; (float)m < num4; m++)
                     {
                         Vector2 velocity4 = dust.velocity;
                         Vector2 vector4 = dust.position - velocity4 * m;
                         float scale5 = dust.scale * (1f - (float)m / 10f);
                         Microsoft.Xna.Framework.Color color4 = Lighting.GetColor((int)((double)dust.position.X + 4.0) / 16, (int)((double)dust.position.Y + 4.0) / 16);
                         color4 = dust.GetAlpha(color4) * 0.3f;
                         spriteBatch.Draw(TextureAssets.Dust.Value, vector4 - screenPosition, dust.frame, color4, dust.rotation, new Vector2(5f), scale5, SpriteEffects.None, 0f);
                         color4 = dust.GetColor(color4);
                         spriteBatch.Draw(TextureAssets.Dust.Value, vector4 - screenPosition, dust.frame, color4, dust.rotation, new Vector2(5f), scale5, SpriteEffects.None, 0f);
                     }
                 }
                 else if ((dust.type == 226 || dust.type == 272) && dust.fadeIn == 0f)
                 {
                     float num5 = Math.Abs(dust.velocity.X) + Math.Abs(dust.velocity.Y);
                     num5 *= 0.3f;
                     num5 *= 10f;
                     if (num5 > 10f)
                     {
                         num5 = 10f;
                     }
                     for (int n = 0; (float)n < num5; n++)
                     {
                         Vector2 velocity5 = dust.velocity;
                         Vector2 vector5 = dust.position - velocity5 * n;
                         float scale6 = dust.scale * (1f - (float)n / 10f);
                         Microsoft.Xna.Framework.Color color5 = Lighting.GetColor((int)((double)dust.position.X + 4.0) / 16, (int)((double)dust.position.Y + 4.0) / 16);
                         color5 = dust.GetAlpha(color5);
                         spriteBatch.Draw(TextureAssets.Dust.Value, vector5 - screenPosition, dust.frame, color5, dust.rotation, new Vector2(4f, 4f), scale6, SpriteEffects.None, 0f);
                     }
                 }
                 Microsoft.Xna.Framework.Color newColor = Lighting.GetColor((int)((double)dust.position.X + 4.0) / 16, (int)((double)dust.position.Y + 4.0) / 16);
                 if (dust.type == 6 || dust.type == 15 || (dust.type >= 59 && dust.type <= 64))
                 {
                     newColor = Microsoft.Xna.Framework.Color.White;
                 }
                 newColor = dust.GetAlpha(newColor);
                 if (dust.type == 213)
                 {
                     scale = 1f;
                 }
                 spriteBatch.Draw(TextureAssets.Dust.Value, dust.position - screenPosition, dust.frame, newColor, dust.GetVisualRotation(), new Vector2(4f, 4f), scale, SpriteEffects.None, 0f);
                 if (dust.color.PackedValue != 0)
                 {
                     Microsoft.Xna.Framework.Color color6 = dust.GetColor(newColor);
                     if (color6.PackedValue != 0)
                     {
                         spriteBatch.Draw(TextureAssets.Dust.Value, dust.position - screenPosition, dust.frame, color6, dust.GetVisualRotation(), new Vector2(4f, 4f), scale, SpriteEffects.None, 0f);
                     }
                 }
                 if (newColor == Microsoft.Xna.Framework.Color.Black)
                 {
                     dust.active = false;
                 }
             }
             else
             {
                 dust.active = false;
             }
         }
         spriteBatch.End();
         pixelShader.CurrentTechnique.Passes[0].Apply();
         TimeLogger.DetailedDrawTime(25);
     }
References Dust.active, ArmorShaderData.Apply(), Dust.color, TimeLogger.DetailedDrawTime(), TextureAssets.Dust, dust, Dust.fadeIn, Dust.frame, Dust.GetAlpha(), Dust.GetColor(), Lighting.GetColor(), Dust.GetVisualRotation(), Dust.GetVisualScale(), maxDustToDraw, pixelShader, Dust.position, Dust.rotation, Dust.scale, screenHeight, screenPosition, screenWidth, Dust.shader, spriteBatch, Transform, Dust.type, Asset< T >.Value, and Dust.velocity.
Referenced by DoDraw(), and DrawCapture().