Terraria: Main.DrawItems
DrawItems()
void Main.DrawItems () inline
     {
         for (int i = 0; i < 400; i++)
         {
             DrawItem(item[i], i);
         }
     }
References DrawItem(), and item.
Referenced by DoDraw(), and DrawCapture().