Terraria: Main.DrawHotbarLockIcon
DrawHotbarLockIcon()
void Main.DrawHotbarLockIcon (int pivotTopLeftX, int pivotTopLeftY, bool pushSideToolsUp) inline private
     {
         int num = 21 + pivotTopLeftY;
         _ = player[myPlayer];
         if (pushSideToolsUp)
         {
             num = pivotTopLeftY;
         }
         float num2 = 0.9f;
         Texture2D value = TextureAssets.HbLock[(!player[myPlayer].hbLocked) ? 1u : 0u].Value;
         Microsoft.Xna.Framework.Rectangle value2 = value.Frame(2);
         bool flag = false;
         if (mouseX > pivotTopLeftX && (float)mouseX < (float)pivotTopLeftX + (float)value2.Width * num2 && mouseY > num && (float)mouseY < (float)num + (float)value2.Height * num2)
         {
             flag = true;
             player[myPlayer].mouseInterface = true;
             if (!player[myPlayer].hbLocked)
             {
                 MouseText(Lang.inter[5].Value, 0, 0);
             }
             else
             {
                 MouseText(Lang.inter[6].Value, 0, 0);
             }
             mouseText = true;
             if (mouseLeft && mouseLeftRelease)
             {
                 SoundEngine.PlaySound(22);
                 player[myPlayer].hbLocked = !player[myPlayer].hbLocked;
             }
         }
         spriteBatch.Draw(value, new Vector2(pivotTopLeftX, num), value2, Microsoft.Xna.Framework.Color.White, 0f, default(Vector2), num2, SpriteEffects.None, 0f);
         if (flag)
         {
             spriteBatch.Draw(value, new Vector2(pivotTopLeftX, num), value.Frame(2, 1, 1), OurFavoriteColor, 0f, default(Vector2), num2, SpriteEffects.None, 0f);
         }
     }
References TextureAssets.HbLock, Player.hbLocked, Lang.inter, Player.mouseInterface, mouseLeft, mouseLeftRelease, mouseText, MouseText(), mouseX, mouseY, myPlayer, OurFavoriteColor, player, SoundEngine.PlaySound(), spriteBatch, and LocalizedText.Value.
Referenced by DrawInventory().