Terraria: Main.TrySyncingMyPlayer
TrySyncingMyPlayer()
static void Main.TrySyncingMyPlayer () inline static private
     {
         Player player = clientPlayer;
         bool syncedAnyInventoryContents = false;
         for (int i = 0; i < 59; i++)
         {
             if (Main.player[myPlayer].inventory[i].IsNotTheSameAs(player.inventory[i]))
             {
                 syncedAnyInventoryContents = true;
                 NetMessage.SendData(5, -1, -1, null, myPlayer, PlayerItemSlotID.Inventory0 + i, (int)Main.player[myPlayer].inventory[i].prefix);
             }
         }
         TrySyncingItemArray(ref syncedAnyInventoryContents, Main.player[myPlayer].armor, player.armor, PlayerItemSlotID.Armor0);
         TrySyncingItemArray(ref syncedAnyInventoryContents, Main.player[myPlayer].dye, player.dye, PlayerItemSlotID.Dye0);
         TrySyncingItemArray(ref syncedAnyInventoryContents, Main.player[myPlayer].miscEquips, player.miscEquips, PlayerItemSlotID.Misc0);
         TrySyncingItemArray(ref syncedAnyInventoryContents, Main.player[myPlayer].miscDyes, player.miscDyes, PlayerItemSlotID.MiscDye0);
         TrySyncingItemArray(ref syncedAnyInventoryContents, Main.player[myPlayer].bank.item, player.bank.item, PlayerItemSlotID.Bank1_0);
         TrySyncingItemArray(ref syncedAnyInventoryContents, Main.player[myPlayer].bank2.item, player.bank2.item, PlayerItemSlotID.Bank2_0);
         if (Main.player[myPlayer].trashItem.IsNotTheSameAs(player.trashItem))
         {
             syncedAnyInventoryContents = true;
             NetMessage.SendData(5, -1, -1, null, myPlayer, PlayerItemSlotID.TrashItem, (int)Main.player[myPlayer].trashItem.prefix);
         }
         TrySyncingItemArray(ref syncedAnyInventoryContents, Main.player[myPlayer].bank3.item, player.bank3.item, PlayerItemSlotID.Bank3_0);
         TrySyncingItemArray(ref syncedAnyInventoryContents, Main.player[myPlayer].bank4.item, player.bank4.item, PlayerItemSlotID.Bank4_0);
         TrySyncingItemArray(ref syncedAnyInventoryContents, Main.player[myPlayer].Loadouts[0].Armor, player.Loadouts[0].Armor, PlayerItemSlotID.Loadout1_Armor_0);
         TrySyncingItemArray(ref syncedAnyInventoryContents, Main.player[myPlayer].Loadouts[0].Dye, player.Loadouts[0].Dye, PlayerItemSlotID.Loadout1_Dye_0);
         TrySyncingItemArray(ref syncedAnyInventoryContents, Main.player[myPlayer].Loadouts[1].Armor, player.Loadouts[1].Armor, PlayerItemSlotID.Loadout2_Armor_0);
         TrySyncingItemArray(ref syncedAnyInventoryContents, Main.player[myPlayer].Loadouts[1].Dye, player.Loadouts[1].Dye, PlayerItemSlotID.Loadout2_Dye_0);
         TrySyncingItemArray(ref syncedAnyInventoryContents, Main.player[myPlayer].Loadouts[2].Armor, player.Loadouts[2].Armor, PlayerItemSlotID.Loadout3_Armor_0);
         TrySyncingItemArray(ref syncedAnyInventoryContents, Main.player[myPlayer].Loadouts[2].Dye, player.Loadouts[2].Dye, PlayerItemSlotID.Loadout3_Dye_0);
         if (Main.player[myPlayer].chest != player.chest && Main.player[myPlayer].chest < 0 && player.chest >= 0)
         {
             if (Main.player[myPlayer].editedChestName)
             {
                 if (chest[player.chest] != null)
                 {
                     NetMessage.SendData(33, -1, -1, NetworkText.FromLiteral(chest[player.chest].name), Main.player[myPlayer].chest, 1f);
                 }
                 else
                 {
                     NetMessage.SendData(33, -1, -1, null, Main.player[myPlayer].chest);
                 }
                 Main.player[myPlayer].editedChestName = false;
             }
             else
             {
                 NetMessage.SendData(33, -1, -1, null, Main.player[myPlayer].chest);
             }
         }
         if (Main.player[myPlayer].talkNPC != player.talkNPC)
         {
             NetMessage.SendData(40, -1, -1, null, myPlayer);
         }
         if (false | (Main.player[myPlayer].voidLensChest != player.voidLensChest) | (Main.player[myPlayer].piggyBankProjTracker != player.piggyBankProjTracker))
         {
             NetMessage.SendData(142, -1, -1, null, myPlayer);
         }
         if (LocalPlayer.tileEntityAnchor.interactEntityID != player.tileEntityAnchor.interactEntityID && LocalPlayer.tileEntityAnchor.interactEntityID < 0)
         {
             NetMessage.SendData(122, -1, -1, null, -1, myPlayer);
         }
         bool flag = false;
         if ((byte)Main.player[myPlayer].zone1 != (byte)player.zone1)
         {
             flag = true;
         }
         if ((byte)Main.player[myPlayer].zone2 != (byte)player.zone2)
         {
             flag = true;
         }
         if ((byte)Main.player[myPlayer].zone3 != (byte)player.zone3)
         {
             flag = true;
         }
         if ((byte)Main.player[myPlayer].zone4 != (byte)player.zone4)
         {
             flag = true;
         }
         if ((byte)Main.player[myPlayer].zone5 != (byte)player.zone5)
         {
             flag = true;
         }
         if (flag)
         {
             NetMessage.SendData(36, -1, -1, null, myPlayer);
         }
         if (Main.player[myPlayer].statLife != player.statLife || Main.player[myPlayer].statLifeMax != player.statLifeMax)
         {
             Main.player[myPlayer].netLife = true;
         }
         if (Main.player[myPlayer].netLifeTime > 0)
         {
             Main.player[myPlayer].netLifeTime--;
         }
         else if (Main.player[myPlayer].netLife)
         {
             Main.player[myPlayer].netLife = false;
             Main.player[myPlayer].netLifeTime = 60;
             NetMessage.SendData(16, -1, -1, null, myPlayer);
         }
         if (Main.player[myPlayer].statMana != player.statMana || Main.player[myPlayer].statManaMax != player.statManaMax)
         {
             Main.player[myPlayer].netMana = true;
         }
         if (Main.player[myPlayer].netManaTime > 0)
         {
             Main.player[myPlayer].netManaTime--;
         }
         else if (Main.player[myPlayer].netMana)
         {
             Main.player[myPlayer].netMana = false;
             Main.player[myPlayer].netManaTime = 60;
             NetMessage.SendData(42, -1, -1, null, myPlayer);
         }
         bool flag2 = false;
         for (int j = 0; j < Player.maxBuffs; j++)
         {
             if (Main.player[myPlayer].buffType[j] != player.buffType[j])
             {
                 flag2 = true;
                 break;
             }
         }
         if (flag2)
         {
             NetMessage.SendData(50, -1, -1, null, myPlayer);
             NetMessage.SendData(13, -1, -1, null, myPlayer);
         }
         bool flag3 = false;
         if (Main.player[myPlayer].MinionRestTargetPoint != player.MinionRestTargetPoint)
         {
             flag3 = true;
         }
         if (flag3)
         {
             NetMessage.SendData(99, -1, -1, null, myPlayer);
         }
         bool flag4 = false;
         if (Main.player[myPlayer].MinionAttackTargetNPC != player.MinionAttackTargetNPC)
         {
             flag4 = true;
         }
         if (flag4)
         {
             NetMessage.SendData(115, -1, -1, null, myPlayer);
         }
         if (player.shieldRaised != Main.player[myPlayer].shieldRaised)
         {
             NetMessage.SendData(13, -1, -1, null, myPlayer);
         }
         if (syncedAnyInventoryContents)
         {
             NetMessage.SendData(138);
         }
         clientPlayer = Main.player[myPlayer].clientClone();
     }
References EquipmentLoadout.Armor, Player.armor, PlayerItemSlotID.Armor0, Player.bank, PlayerItemSlotID.Bank1_0, Player.bank2, PlayerItemSlotID.Bank2_0, Player.bank3, PlayerItemSlotID.Bank3_0, Player.bank4, PlayerItemSlotID.Bank4_0, Player.buffType, chest, Player.chest, Player.clientClone(), clientPlayer, EquipmentLoadout.Dye, Player.dye, PlayerItemSlotID.Dye0, Player.editedChestName, NetworkText.FromLiteral(), PlayerInteractionAnchor.interactEntityID, Player.inventory, PlayerItemSlotID.Inventory0, Item.IsNotTheSameAs(), Chest.item, PlayerItemSlotID.Loadout1_Armor_0, PlayerItemSlotID.Loadout1_Dye_0, PlayerItemSlotID.Loadout2_Armor_0, PlayerItemSlotID.Loadout2_Dye_0, PlayerItemSlotID.Loadout3_Armor_0, PlayerItemSlotID.Loadout3_Dye_0, Player.Loadouts, LocalPlayer, Player.maxBuffs, Player.MinionAttackTargetNPC, Player.MinionRestTargetPoint, PlayerItemSlotID.Misc0, PlayerItemSlotID.MiscDye0, Player.miscDyes, Player.miscEquips, myPlayer, Chest.name, Player.netLife, Player.netLifeTime, Player.netMana, Player.netManaTime, Player.piggyBankProjTracker, player, Item.prefix, NetMessage.SendData(), Player.shieldRaised, Player.statLife, Player.statLifeMax, Player.statMana, Player.statManaMax, Player.talkNPC, Player.tileEntityAnchor, PlayerItemSlotID.TrashItem, Player.trashItem, TrySyncingItemArray(), Player.voidLensChest, Player.zone1, Player.zone2, Player.zone3, Player.zone4, and Player.zone5.
Referenced by DoUpdate().