Terraria: Main.UpdateWeather
UpdateWeather()
void Main.UpdateWeather (GameTime gameTime, int currentDayRateIteration) inline
     {
         if (netMode != 2 && currentDayRateIteration == 0)
         {
             bool flag = base.IsActive;
             if (thunderDelay > 0)
             {
                 thunderDelay--;
                 if (thunderDelay == 0)
                 {
                     Vector2 center = player[myPlayer].Center;
                     float num = thunderDistance * 15;
                     if (rand.Next(2) == 0)
                     {
                         num *= -1f;
                     }
                     center.X += num;
                     int num2 = (int)(worldSurface * 16.0) - 500;
                     if (center.Y > (float)num2)
                     {
                         center.Y = num2;
                     }
                     if (flag)
                     {
                         SoundEngine.PlaySound(43, center);
                     }
                 }
             }
             if (lightningSpeed > 0f)
             {
                 lightning += lightningSpeed;
                 if (lightning >= 1f)
                 {
                     lightning = 1f;
                     lightningSpeed = 0f;
                 }
                 Lighting.LightTiles(firstTileX, lastTileX, firstTileY, lastTileY);
                 Lighting.LightTiles(firstTileX, lastTileX, firstTileY, lastTileY);
             }
             else if (lightning > 0f)
             {
                 lightning -= lightningDecay;
                 Lighting.LightTiles(firstTileX, lastTileX, firstTileY, lastTileY);
                 Lighting.LightTiles(firstTileX, lastTileX, firstTileY, lastTileY);
             }
             else if (thunderDelay <= 0 && (double)player[myPlayer].position.Y < rockLayer * 16.0 && atmo == 1f && !remixWorld)
             {
                 if (IsItStorming)
                 {
                     float num3 = 600f;
                     float num4 = 1600f;
                     if ((double)maxRaining > 0.8)
                     {
                         num3 *= 0.6f;
                         num4 *= 0.8f;
                     }
                     if ((double)maxRaining > 0.7)
                     {
                         num3 *= 0.7f;
                         num4 *= 0.9f;
                     }
                     if ((double)maxRaining > 0.6)
                     {
                         num3 *= 0.8f;
                         num4 *= 0.95f;
                     }
                     if ((double)Math.Abs(windSpeedTarget) > 0.7)
                     {
                         num3 *= 0.6f;
                         num4 *= 0.8f;
                     }
                     if ((double)Math.Abs(windSpeedTarget) > 0.6)
                     {
                         num3 *= 0.7f;
                         num4 *= 0.9f;
                     }
                     if ((double)Math.Abs(windSpeedTarget) > 0.5)
                     {
                         num3 *= 0.8f;
                         num4 *= 0.95f;
                     }
                     float num5 = rand.Next((int)num3, (int)num4);
                     num5 *= (1f - maxRaining + 1f) / 2f;
                     num5 *= (1f - windSpeedTarget + 1f) / 2f;
                     if (rand.Next((int)num5) == 0)
                     {
                         NewLightning();
                     }
                 }
                 else if ((double)GraveyardVisualIntensity >= 0.9)
                 {
                     int maxValue = 120;
                     if (rand.Next(maxValue) == 0)
                     {
                         NewLightning();
                     }
                 }
             }
         }
         float num6 = 0.8f;
         float num7 = 0.0003f;
         float num8 = windSpeedTarget * (1f + 5f / 9f * maxRaining);
         num7 += Math.Abs(num8 - windSpeedCurrent) * 0.0015f;
         if (windSpeedCurrent < num8)
         {
             windSpeedCurrent += num7;
             if (windSpeedCurrent > num8)
             {
                 windSpeedCurrent = num8;
             }
         }
         else if (windSpeedCurrent > num8)
         {
             windSpeedCurrent -= num7;
             if (windSpeedCurrent < num8)
             {
                 windSpeedCurrent = num8;
             }
         }
         if (netMode == 1 || (netMode != 2 && gameMenu))
         {
             return;
         }
         if (!CreativePowerManager.Instance.GetPower<CreativePowers.FreezeWindDirectionAndStrength>().Enabled)
         {
             if (LanternNight.LanternsUp)
             {
                 return;
             }
             windCounter--;
             if (windCounter <= 0)
             {
                 float num9 = 1f;
                 if (windSpeedTarget < 0f)
                 {
                     num9 = -1f;
                 }
                 if (rand.Next(4) == 0)
                 {
                     windSpeedTarget += (float)rand.Next(-25, 26) * 0.001f;
                 }
                 else if (rand.Next(2) == 0)
                 {
                     windSpeedTarget += (float)rand.Next(-50, 51) * 0.001f;
                 }
                 else
                 {
                     windSpeedTarget += (float)rand.Next(-100, 101) * 0.001f;
                 }
                 extremeWindCounter--;
                 if (extremeWindCounter <= 0)
                 {
                     ResetWindCounter(resetExtreme: true);
                     if (rand.Next(30) < 13)
                     {
                         if (rand.Next(2) == 0)
{
                             windSpeedTarget = 0f;
                             windCounter = rand.Next(7200, 28801);
                         }
                         else
{
                             windSpeedTarget = (float)rand.Next(-200, 201) * 0.001f;
                         }
                     }
                     else if (rand.Next(20) < 13)
                     {
                         windSpeedTarget = (float)rand.Next(-400, 401) * 0.001f;
                     }
                     else
                     {
                         windSpeedTarget = (float)rand.Next(-850, 851) * 0.001f;
                     }
                     if ((double)Math.Abs(windSpeedTarget) > 0.3)
                     {
                         extremeWindCounter += rand.Next(5, 11);
                     }
                     if ((double)Math.Abs(windSpeedTarget) > 0.5)
                     {
                         extremeWindCounter += rand.Next(10, 21);
                     }
                     if ((double)Math.Abs(windSpeedTarget) > 0.7)
                     {
                         extremeWindCounter += rand.Next(15, 31);
                     }
                 }
                 else
                 {
                     ResetWindCounter();
                 }
                 if (rand.Next(3) != 0 && ((num9 < 0f && windSpeedTarget > 0f) || (num9 > 0f && windSpeedTarget < 0f)))
                 {
                     windSpeedTarget *= -1f;
                 }
             }
             if (windSpeedTarget > num6)
             {
                 windSpeedTarget = num6;
             }
             if (windSpeedTarget < 0f - num6)
             {
                 windSpeedTarget = 0f - num6;
             }
         }
         if (rand.Next(60) == 0)
         {
             numCloudsTemp += rand.Next(-1, 2);
         }
         if ((float)rand.Next(1000) < 50f * cloudBGAlpha)
         {
             numCloudsTemp++;
         }
         if ((float)rand.Next(1300) < 25f * (1f - cloudBGAlpha))
         {
             numCloudsTemp--;
         }
         if ((float)rand.Next(1000) < 200f * cloudAlpha && numCloudsTemp < 100)
         {
             numCloudsTemp++;
         }
         if ((float)rand.Next(1000) < 50f * cloudAlpha)
         {
             numCloudsTemp++;
         }
         if (numCloudsTemp > 66 && rand.Next(100) == 0)
         {
             numCloudsTemp -= rand.Next(1, 3);
         }
         if (numCloudsTemp < 50 && rand.Next(100) == 0)
         {
             numCloudsTemp += rand.Next(1, 3);
         }
         if (cloudBGActive <= 0f && numCloudsTemp > 100 && cloudAlpha == 0f)
         {
             numCloudsTemp = 100;
         }
         if (numCloudsTemp < -20)
         {
             numCloudsTemp = -20;
         }
         if (cloudAlpha > 0f && (float)numClouds < 200f * cloudAlpha)
         {
             while ((float)numClouds < 200f * cloudAlpha)
             {
                 numClouds += rand.Next(30);
                 if (numClouds > 200)
                 {
                     numClouds = 200;
                 }
                 if (numCloudsTemp < numClouds)
                 {
                     numCloudsTemp = numClouds;
                 }
             }
             if (netMode == 2)
             {
                 NetMessage.SendData(7);
             }
         }
         weatherCounter--;
         if (weatherCounter > 0)
         {
             return;
         }
         if (rand.Next(2) == 0)
         {
             if (rand.Next(2) == 0)
             {
                 numCloudsTemp += rand.Next(250);
             }
             else
             {
                 numCloudsTemp += rand.Next(100);
             }
         }
         if (numCloudsTemp < 0)
         {
             numCloudsTemp = 0;
         }
         if (numCloudsTemp > 200)
         {
             numCloudsTemp = 200;
         }
         numClouds = numCloudsTemp;
         weatherCounter = rand.Next(3600, 10800);
         if (netMode == 2)
         {
             NetMessage.SendData(7);
         }
     }
References atmo, Entity.Center, cloudAlpha, cloudBGAlpha, CreativePowers.ASharedTogglePower.Enabled, extremeWindCounter, firstTileX, firstTileY, gameMenu, GraveyardVisualIntensity, CreativePowerManager.Instance, IsItStorming, LanternNight.LanternsUp, lastTileX, lastTileY, lightning, lightningDecay, lightningSpeed, Lighting.LightTiles(), maxRaining, myPlayer, netMode, NewLightning(), UnifiedRandom.Next(), numClouds, numCloudsTemp, player, SoundEngine.PlaySound(), Entity.position, rand, remixWorld, ResetWindCounter(), rockLayer, NetMessage.SendData(), thunderDelay, thunderDistance, weatherCounter, windCounter, windSpeedCurrent, windSpeedTarget, and worldSurface.
Referenced by DoUpdate().