Terraria: Main.TryPlayingCreditsRoll
TryPlayingCreditsRoll()
static void Main.TryPlayingCreditsRoll () inline static private
     {
         if (!gameMenu && CanPlayCreditsRoll() && !SkyManager.Instance["CreditsRoll"].IsActive())
         {
             SkyManager.Instance.Activate("CreditsRoll", Vector2.Zero);
         }
     }
References EffectManager< T >.Activate(), CanPlayCreditsRoll(), gameMenu, and SkyManager.Instance.
Referenced by DoUpdate().