Terraria: Main.MouseTextInner
MouseTextInner()
void Main.MouseTextInner (MouseTextCache info) inline private
     {
         string cursorText = info.cursorText;
         int num = info.rare;
         byte diff = info.diff;
         int x = info.X;
         int y = info.Y;
         int hackedScreenWidth = info.hackedScreenWidth;
         int hackedScreenHeight = info.hackedScreenHeight;
         if (mouseNPCType > -1 || cursorText == null)
         {
             return;
         }
         int X = mouseX + 14;
         int Y = mouseY + 14;
         if (x != -1 && y != -1)
         {
             X = x + 10;
             Y = y + 10;
         }
         if (ThickMouse)
         {
             X += 6;
             Y += 6;
         }
         if (!mouseItem.IsAir)
         {
             X += 34;
         }
         new Microsoft.Xna.Framework.Color(mouseTextColor, mouseTextColor, mouseTextColor, mouseTextColor);
         if (HoverItem.type > 0)
         {
             MouseText_DrawItemTooltip(info, num, diff, X, Y);
             return;
         }
         if (info.buffTooltip != null && info.buffTooltip != "")
         {
             MouseText_DrawBuffTooltip(info.buffTooltip, ref X, ref Y);
         }
         Vector2 vector = FontAssets.MouseText.Value.MeasureString(cursorText);
         if (hackedScreenHeight != -1 && hackedScreenWidth != -1)
         {
             if ((float)X + vector.X + 4f > (float)hackedScreenWidth)
             {
                 X = (int)((float)hackedScreenWidth - vector.X - 4f);
             }
             if ((float)Y + vector.Y + 4f > (float)hackedScreenHeight)
             {
                 Y = (int)((float)hackedScreenHeight - vector.Y - 4f);
             }
         }
         else
         {
             if ((float)X + vector.X + 4f > (float)screenWidth)
             {
                 X = (int)((float)screenWidth - vector.X - 4f);
             }
             if ((float)Y + vector.Y + 4f > (float)screenHeight)
             {
                 Y = (int)((float)screenHeight - vector.Y - 4f);
             }
         }
         float num2 = (float)(int)mouseTextColor / 255f;
         Microsoft.Xna.Framework.Color baseColor = new Microsoft.Xna.Framework.Color(mouseTextColor, mouseTextColor, mouseTextColor, mouseTextColor);
         if (num == -13)
         {
             baseColor = new Microsoft.Xna.Framework.Color((byte)(255f * num2), (byte)(masterColor * 200f * num2), 0, mouseTextColor);
         }
         if (num == -11)
         {
             baseColor = new Microsoft.Xna.Framework.Color((byte)(255f * num2), (byte)(175f * num2), (byte)(0f * num2), mouseTextColor);
         }
         if (num == -10)
         {
             baseColor = new Microsoft.Xna.Framework.Color((byte)(65f * num2), (byte)(255f * num2), (byte)(110f * num2), mouseTextColor);
         }
         if (num == -1)
         {
             baseColor = new Microsoft.Xna.Framework.Color((byte)(130f * num2), (byte)(130f * num2), (byte)(130f * num2), mouseTextColor);
         }
         if (num == 1)
         {
             baseColor = new Microsoft.Xna.Framework.Color((byte)(150f * num2), (byte)(150f * num2), (byte)(255f * num2), mouseTextColor);
         }
         if (num == 2)
         {
             baseColor = new Microsoft.Xna.Framework.Color((byte)(150f * num2), (byte)(255f * num2), (byte)(150f * num2), mouseTextColor);
         }
         if (num == 3)
         {
             baseColor = new Microsoft.Xna.Framework.Color((byte)(255f * num2), (byte)(200f * num2), (byte)(150f * num2), mouseTextColor);
         }
         if (num == 4)
         {
             baseColor = new Microsoft.Xna.Framework.Color((byte)(255f * num2), (byte)(150f * num2), (byte)(150f * num2), mouseTextColor);
         }
         if (num == 5)
         {
             baseColor = new Microsoft.Xna.Framework.Color((byte)(255f * num2), (byte)(150f * num2), (byte)(255f * num2), mouseTextColor);
         }
         if (num == 6)
         {
             baseColor = new Microsoft.Xna.Framework.Color((byte)(210f * num2), (byte)(160f * num2), (byte)(255f * num2), mouseTextColor);
         }
         if (num == 7)
         {
             baseColor = new Microsoft.Xna.Framework.Color((byte)(150f * num2), (byte)(255f * num2), (byte)(10f * num2), mouseTextColor);
         }
         if (num == 8)
         {
             baseColor = new Microsoft.Xna.Framework.Color((byte)(255f * num2), (byte)(255f * num2), (byte)(10f * num2), mouseTextColor);
         }
         if (num == 9)
         {
             baseColor = new Microsoft.Xna.Framework.Color((byte)(5f * num2), (byte)(200f * num2), (byte)(255f * num2), mouseTextColor);
         }
         if (num == 10)
         {
             baseColor = new Microsoft.Xna.Framework.Color((byte)(255f * num2), (byte)(40f * num2), (byte)(100f * num2), mouseTextColor);
         }
         if (num >= 11)
         {
             baseColor = new Microsoft.Xna.Framework.Color((byte)(180f * num2), (byte)(40f * num2), (byte)(255f * num2), mouseTextColor);
         }
         if (HoverItem.expert || num == -12)
         {
             baseColor = new Microsoft.Xna.Framework.Color((byte)((float)DiscoR * num2), (byte)((float)DiscoG * num2), (byte)((float)DiscoB * num2), mouseTextColor);
         }
         if (diff == 1)
         {
             baseColor = new Microsoft.Xna.Framework.Color((byte)((float)(int)mcColor.R * num2), (byte)((float)(int)mcColor.G * num2), (byte)((float)(int)mcColor.B * num2), mouseTextColor);
         }
         if (diff == 2)
         {
             baseColor = new Microsoft.Xna.Framework.Color((byte)((float)(int)hcColor.R * num2), (byte)((float)(int)hcColor.G * num2), (byte)((float)(int)hcColor.B * num2), mouseTextColor);
         }
         ChatManager.DrawColorCodedStringWithShadow(spriteBatch, FontAssets.MouseText.Value, cursorText, new Vector2(X, Y), baseColor, 0f, Vector2.Zero, Vector2.One);
     }
References Main.MouseTextCache.buffTooltip, Main.MouseTextCache.cursorText, Main.MouseTextCache.diff, DiscoB, DiscoG, DiscoR, ChatManager.DrawColorCodedStringWithShadow(), Item.expert, Main.MouseTextCache.hackedScreenHeight, Main.MouseTextCache.hackedScreenWidth, hcColor, HoverItem, Item.IsAir, masterColor, mcColor, mouseItem, mouseNPCType, FontAssets.MouseText, MouseText_DrawBuffTooltip(), MouseText_DrawItemTooltip(), mouseTextColor, mouseX, mouseY, Main.MouseTextCache.rare, screenHeight, screenWidth, spriteBatch, ThickMouse, Item.type, Asset< T >.Value, X, Main.MouseTextCache.X, Y, and Main.MouseTextCache.Y.
Referenced by DrawPendingMouseText().