Terraria: Main.GetInputText
GetInputText()
static string Main.GetInputText (string oldString, bool allowMultiLine = false) inline static
     {
         if (dedServ)
         {
             return "";
         }
         if (!hasFocus)
         {
             return oldString;
         }
         inputTextEnter = false;
         inputTextEscape = false;
         string text = oldString;
         string text2 = "";
         if (text == null)
         {
             text = "";
         }
         bool flag = false;
         if (inputText.IsKeyDown(Microsoft.Xna.Framework.Input.Keys.LeftControl) || inputText.IsKeyDown(Microsoft.Xna.Framework.Input.Keys.RightControl))
         {
             if (inputText.IsKeyDown(Microsoft.Xna.Framework.Input.Keys.Z) && !oldInputText.IsKeyDown(Microsoft.Xna.Framework.Input.Keys.Z))
             {
                 text = "";
             }
             else if (inputText.IsKeyDown(Microsoft.Xna.Framework.Input.Keys.X) && !oldInputText.IsKeyDown(Microsoft.Xna.Framework.Input.Keys.X))
             {
                 Platform.Get<IClipboard>().Value = oldString;
                 text = "";
             }
             else if ((inputText.IsKeyDown(Microsoft.Xna.Framework.Input.Keys.C) && !oldInputText.IsKeyDown(Microsoft.Xna.Framework.Input.Keys.C)) || (inputText.IsKeyDown(Microsoft.Xna.Framework.Input.Keys.Insert) && !oldInputText.IsKeyDown(Microsoft.Xna.Framework.Input.Keys.Insert)))
             {
                 Platform.Get<IClipboard>().Value = oldString;
             }
             else if (inputText.IsKeyDown(Microsoft.Xna.Framework.Input.Keys.V) && !oldInputText.IsKeyDown(Microsoft.Xna.Framework.Input.Keys.V))
             {
                 text2 = PasteTextIn(allowMultiLine, text2);
             }
         }
         else
         {
             if (inputText.PressingShift())
             {
                 if (inputText.IsKeyDown(Microsoft.Xna.Framework.Input.Keys.Delete) && !oldInputText.IsKeyDown(Microsoft.Xna.Framework.Input.Keys.Delete))
                 {
                     Platform.Get<IClipboard>().Value = oldString;
                     text = "";
                 }
                 if (inputText.IsKeyDown(Microsoft.Xna.Framework.Input.Keys.Insert) && !oldInputText.IsKeyDown(Microsoft.Xna.Framework.Input.Keys.Insert))
                 {
                     text2 = PasteTextIn(allowMultiLine, text2);
                 }
             }
             for (int i = 0; i < keyCount; i++)
             {
                 int num = keyInt[i];
                 string text3 = keyString[i];
                 if (num == 13)
                 {
                     inputTextEnter = true;
                 }
                 else if (num == 27)
                 {
                     inputTextEscape = true;
                 }
                 else if (num >= 32 && num != 127)
                 {
                     text2 += text3;
                 }
             }
         }
         keyCount = 0;
         text += text2;
         oldInputText = inputText;
         inputText = Keyboard.GetState();
         Microsoft.Xna.Framework.Input.Keys[] pressedKeys = inputText.GetPressedKeys();
         Microsoft.Xna.Framework.Input.Keys[] pressedKeys2 = oldInputText.GetPressedKeys();
         if (inputText.IsKeyDown(Microsoft.Xna.Framework.Input.Keys.Back) && oldInputText.IsKeyDown(Microsoft.Xna.Framework.Input.Keys.Back))
         {
             backSpaceRate -= 0.05f;
             if (backSpaceRate < 0f)
             {
                 backSpaceRate = 0f;
             }
             if (backSpaceCount <= 0)
             {
                 backSpaceCount = (int)Math.Round(backSpaceRate);
                 flag = true;
             }
             backSpaceCount--;
         }
         else
         {
             backSpaceRate = 7f;
             backSpaceCount = 15;
         }
         for (int j = 0; j < pressedKeys.Length; j++)
         {
             bool flag2 = true;
             for (int k = 0; k < pressedKeys2.Length; k++)
             {
                 if (pressedKeys[j] == pressedKeys2[k])
                 {
                     flag2 = false;
                 }
             }
             if (string.Concat(pressedKeys[j]) == "Back" && (flag2 || flag) && text.Length > 0)
             {
                 TextSnippet[] array = ChatManager.ParseMessage(text, Microsoft.Xna.Framework.Color.White).ToArray();
                 text = ((!array[array.Length - 1].DeleteWhole) ? text.Substring(0, text.Length - 1) : text.Substring(0, text.Length - array[array.Length - 1].TextOriginal.Length));
             }
         }
         return text;
     }
References backSpaceCount, backSpaceRate, dedServ, TextSnippet.DeleteWhole, hasFocus, inputText, inputTextEnter, inputTextEscape, Keyboard, keyCount, keyInt, keyString, oldInputText, ChatManager.ParseMessage(), PasteTextIn(), and TextSnippet.TextOriginal.
Referenced by DoUpdate_HandleChat(), DrawMenu(), UISearchBar.DrawSelf(), UIVirtualKeyboard.DrawSelf(), InputTextChest(), InputTextSign(), NetClientSocialModule.OnAuthSuccess(), NetClientSocialModule.OnLobbyEntered(), and UIWorldListItem.PlayGame().