Terraria: Main.DrawSurfaceBG_BackMountainsStep2
DrawSurfaceBG_BackMountainsStep2()
void Main.DrawSurfaceBG_BackMountainsStep2 (int pushBGTopHack) inline private
     {
         if (gameMenu)
         {
             bgTopY = 230 + pushBGTopHack;
             bgStartX -= 500;
         }
         Microsoft.Xna.Framework.Color colorOfSurfaceBackgroundsBase = ColorOfSurfaceBackgroundsBase;
         UpdateOceanWaterLineForAmbience();
         SkyManager.Instance.DrawToDepth(spriteBatch, 1f / (float)bgParallax);
         if (!((double)screenPosition.Y < worldSurface * 16.0 + 16.0))
         {
             return;
         }
         if (bgAlphaFarBackLayer[0] > 0f)
         {
             ColorOfSurfaceBackgroundsModified = colorOfSurfaceBackgroundsBase * bgAlphaFarBackLayer[0];
             if (treeMntBGSet1[1] > -1)
             {
                 DrawSurfaceBG_DrawBackMountainsLayer(treeMntBGSet1[1]);
             }
         }
         if (bgAlphaFarBackLayer[1] > 0f)
         {
             ColorOfSurfaceBackgroundsModified = colorOfSurfaceBackgroundsBase * bgAlphaFarBackLayer[1];
             if (WorldGen.desertBG != 4)
             {
                 DrawSurfaceBG_DrawBackMountainsLayer(22);
             }
         }
         if (bgAlphaFarBackLayer[2] > 0f)
         {
             ColorOfSurfaceBackgroundsModified = colorOfSurfaceBackgroundsBase * bgAlphaFarBackLayer[2];
             DrawSurfaceBG_DrawBackMountainsLayer(25);
         }
         if (bgAlphaFarBackLayer[3] > 0f)
         {
             ColorOfSurfaceBackgroundsModified = colorOfSurfaceBackgroundsBase * bgAlphaFarBackLayer[3];
             DrawSurfaceBG_DrawBackMountainsLayer(oceanBG);
         }
         if (bgAlphaFarBackLayer[4] > 0f)
         {
             ColorOfSurfaceBackgroundsModified = colorOfSurfaceBackgroundsBase * bgAlphaFarBackLayer[4];
             DrawSurfaceBG_DrawBackMountainsLayer(snowMntBG[1]);
         }
         if (bgAlphaFarBackLayer[5] > 0f)
         {
             ColorOfSurfaceBackgroundsModified = colorOfSurfaceBackgroundsBase * bgAlphaFarBackLayer[5];
             if (WorldGen.crimsonBG != 5)
             {
                 DrawSurfaceBG_DrawBackMountainsLayer(42);
             }
         }
         if (bgAlphaFarBackLayer[6] > 0f && WorldGen.hallowBG == 3)
         {
             ColorOfSurfaceBackgroundsModified = colorOfSurfaceBackgroundsBase * bgAlphaFarBackLayer[6];
             DrawSurfaceBG_DrawBackMountainsLayer(247);
         }
         if (bgAlphaFarBackLayer[10] > 0f)
         {
             ColorOfSurfaceBackgroundsModified = colorOfSurfaceBackgroundsBase * bgAlphaFarBackLayer[10];
             if (treeMntBGSet2[1] > -1)
             {
                 DrawSurfaceBG_DrawBackMountainsLayer(treeMntBGSet2[1]);
             }
         }
         if (bgAlphaFarBackLayer[11] > 0f)
         {
             ColorOfSurfaceBackgroundsModified = colorOfSurfaceBackgroundsBase * bgAlphaFarBackLayer[11];
             if (treeMntBGSet3[1] > -1)
             {
                 DrawSurfaceBG_DrawBackMountainsLayer(treeMntBGSet3[1]);
             }
         }
         if (bgAlphaFarBackLayer[12] > 0f)
         {
             ColorOfSurfaceBackgroundsModified = colorOfSurfaceBackgroundsBase * bgAlphaFarBackLayer[12];
             if (treeMntBGSet4[1] > -1)
             {
                 DrawSurfaceBG_DrawBackMountainsLayer(treeMntBGSet4[1]);
             }
         }
     }
References bgAlphaFarBackLayer, bgParallax, bgStartX, bgTopY, ColorOfSurfaceBackgroundsBase, ColorOfSurfaceBackgroundsModified, WorldGen.crimsonBG, WorldGen.desertBG, DrawSurfaceBG_DrawBackMountainsLayer(), SkyManager.DrawToDepth(), gameMenu, WorldGen.hallowBG, SkyManager.Instance, oceanBG, screenPosition, snowMntBG, spriteBatch, treeMntBGSet1, treeMntBGSet2, treeMntBGSet3, treeMntBGSet4, UpdateOceanWaterLineForAmbience(), and worldSurface.
Referenced by DrawSurfaceBG().