Terraria: Main.DrawSurfaceBG_DrawChangeOverlay
DrawSurfaceBG_DrawChangeOverlay()
void Main.DrawSurfaceBG_DrawChangeOverlay (int backgroundAreaId) inline private
     {
         Texture2D value = TextureAssets.MagicPixel.Value;
         float flashPower = WorldGen.BackgroundsCache.GetFlashPower(backgroundAreaId);
         Microsoft.Xna.Framework.Color color = Microsoft.Xna.Framework.Color.Black * flashPower;
         spriteBatch.Draw(value, new Microsoft.Xna.Framework.Rectangle(0, 0, screenWidth, screenHeight), color);
     }
References WorldGen.BackgroundsCache, BackgroundChangeFlashInfo.GetFlashPower(), TextureAssets.MagicPixel, screenHeight, screenWidth, spriteBatch, and Asset< T >.Value.
Referenced by DrawSurfaceBG(), and DrawUnderworldBackground().