Terraria: Main.DrawInterface_GolfBallIndicator
DrawInterface_GolfBallIndicator()
static void Main.DrawInterface_GolfBallIndicator () inline static private
     {
         if (!Item.IsAGolfingItem(LocalPlayer.HeldItem))
         {
             return;
         }
         Projectile lastHitBall = LocalGolfState.GetLastHitBall();
         if (lastHitBall != null && GolfHelper.IsGolfBallResting(lastHitBall))
         {
             Vector2 vector = lastHitBall.Top - Camera.ScaledPosition;
             vector *= GameViewMatrix.Zoom;
             vector /= UIScale;
             float num = MathHelper.Clamp(((LocalPlayer.position - lastHitBall.position).Length() - 150f) / 50f, 0f, 1f);
             Vector2 vector2 = Vector2.Clamp(vector, new Vector2(20f), Camera.UnscaledSize - new Vector2(20f));
             float num2 = 0f;
             if (vector2 != vector)
             {
                 num2 = (vector2 - vector).ToRotation() + (float)Math.PI / 2f;
             }
             vector2 -= (num2 + (float)Math.PI / 2f).ToRotationVector2() * (((float)Math.Sin(GlobalTimeWrappedHourly * 4f) * 0.5f + 0.5f) * 5f + 14f);
             Texture2D value = TextureAssets.GolfBallArrow.Value;
             Microsoft.Xna.Framework.Rectangle rectangle = value.Frame(2);
             Vector2 origin = rectangle.Size() * new Vector2(0.5f, 1f);
             Microsoft.Xna.Framework.Rectangle value2 = value.Frame(2, 1, 1);
             spriteBatch.Draw(TextureAssets.GolfBallArrowShadow.Value, vector2 + new Vector2(-4f, 4f) * 1.5f, rectangle, Microsoft.Xna.Framework.Color.White * num, num2, origin, 1.5f, SpriteEffects.None, 0f);
             float amount = (float)Math.Sin(GlobalTimeWrappedHourly * 4f) * 0.5f + 0.5f;
             for (float num3 = 0f; num3 < 1f; num3 += 0.25f)
             {
                 spriteBatch.Draw(value, vector2 + ((float)Math.PI * 2f * num3 + num2).ToRotationVector2() * MathHelper.Lerp(2f, 2f, amount), value2, Microsoft.Xna.Framework.Color.Black * num * MathHelper.Lerp(1f, 1f, amount), num2, origin, 1.5f, SpriteEffects.None, 0f);
             }
             for (float num4 = 0f; num4 < 1f; num4 += 0.25f)
             {
                 spriteBatch.Draw(value, vector2 + ((float)Math.PI * 2f * num4 + num2).ToRotationVector2() * MathHelper.Lerp(0f, 0f, amount), value2, Microsoft.Xna.Framework.Color.White * num * MathHelper.Lerp(0.8f, 0.8f, amount), num2, origin, 1.5f, SpriteEffects.None, 0f);
             }
             spriteBatch.Draw(value, vector2, rectangle, mouseColor * num, num2, origin, 1.5f, SpriteEffects.None, 0f);
         }
     }
References GameViewMatrix, GolfState.GetLastHitBall(), GlobalTimeWrappedHourly, TextureAssets.GolfBallArrow, TextureAssets.GolfBallArrowShadow, Player.HeldItem, Item.IsAGolfingItem(), GolfHelper.IsGolfBallResting(), LocalGolfState, LocalPlayer, mouseColor, Entity.position, Camera.ScaledPosition, spriteBatch, Entity.Top, UIScale, Camera.UnscaledSize, Asset< T >.Value, and SpriteViewMatrix.Zoom.
Referenced by DrawInterface_9_WireSelection().