Terraria: Main.DrawWhip_CoolWhip
DrawWhip_CoolWhip()
static Vector2 Main.DrawWhip_CoolWhip (Projectile proj, List< Vector2 > controlPoints) inline static
     {
         Texture2D value = TextureAssets.Projectile[proj.type].Value;
         Microsoft.Xna.Framework.Rectangle rectangle = value.Frame(1, 5);
         int height = rectangle.Height;
         rectangle.Height -= 2;
         Vector2 vector = rectangle.Size() / 2f;
         Vector2 vector2 = controlPoints[0];
         for (int i = 0; i < controlPoints.Count - 1; i++)
         {
             bool flag = true;
             Vector2 origin = vector;
             switch (i)
             {
             case 0:
                 origin.Y -= 4f;
                 break;
             case 3:
             case 5:
             case 7:
                 rectangle.Y = height;
                 break;
             case 9:
             case 11:
             case 13:
                 rectangle.Y = height * 2;
                 break;
             case 15:
             case 17:
                 rectangle.Y = height * 3;
                 break;
             case 19:
                 rectangle.Y = height * 4;
                 break;
             default:
                 flag = false;
                 break;
             }
             Vector2 vector3 = controlPoints[i];
             Vector2 vector4 = controlPoints[i + 1] - vector3;
             if (flag)
             {
                 float rotation = vector4.ToRotation() - (float)Math.PI / 2f;
                 Microsoft.Xna.Framework.Color alpha = proj.GetAlpha(Lighting.GetColor(vector3.ToTileCoordinates()));
                 spriteBatch.Draw(value, vector2 - screenPosition, rectangle, alpha, rotation, origin, 1f, SpriteEffects.None, 0f);
             }
             vector2 += vector4;
         }
         return vector2;
     }
References Projectile.GetAlpha(), Lighting.GetColor(), TextureAssets.Projectile, screenPosition, spriteBatch, Projectile.type, and Asset< T >.Value.
Referenced by DrawWhip().