Terraria: Main.maxTilesY
maxTilesY
int Main.maxTilesY = (int)bottomWorld / 16 + 1 static
Referenced by Main(), WorldGen.AddBuriedChest(), WorldGen.AddHellHouses(), WorldGen.AddLifeCrystal(), WorldGen.AddShadowOrb(), WorldGen.AddTrees(), Liquid.AddWater(), Collision.AdvancedTileCollision(), NPC.AI(), NPC.AI_003_Gnomes_ShouldTurnToStone(), NPC.AI_006_Worms(), NPC.AI_007_FindGoodRestingSpot(), Projectile.AI_007_GrapplingHooks(), Projectile.AI_009_MagicMissiles(), Projectile.AI_016(), NPC.AI_037_Destroyer(), NPC.AI_107_ImprovedWalkers(), NPC.AI_121_QueenSlime(), Projectile.AI_121_StardustDragon(), NPC.AI_123_Deerclops_FindSpotToSpawnSpike(), NPC.AI_123_Deerclops_TryMakingSpike_FindBestY(), Projectile.AI_174_MultisegmentPet(), Collision.AnyCollision(), Collision.AnyCollisionWithSpecificTiles(), TerrainPass.ApplyPass(), JunglePass.ApplyRandomMovement(), HouseUtils.AreRoomLocationsValid(), autoCreate(), WorldGen.BlockBelowMakesSandConvertIntoHardenedSand(), WorldGen.BlockBelowMakesSandFall(), Conditions.YoyoCascade.CanDrop(), Conditions.YoyosHelFire.CanDrop(), Collision.CanHit(), Collision.CanHitLine(), Collision.CanHitWithCheck(), WorldGen.CanKillTile(), TileObject.CanPlace(), StructureMap.CanPlace(), WorldGen.CanPlaceSink(), Player.CanSeeShimmerEffects(), DelegateMethods.CastLight(), DelegateMethods.CastLightOpen(), DelegateMethods.CastLightOpen_StopForSolids(), DelegateMethods.CastLightOpen_StopForSolids_ScaleWithDistance(), WorldGen.CaveOpenater(), WorldGen.Cavinator(), WorldGen.ChasmRunner(), WorldGen.ChasmRunnerSideways(), WorldGen.CheckCatTail(), NPC.checkDead(), Player.CheckForGoodTeleportationSpot(), WorldGen.CheckLilyPad(), Wiring.CheckLogicGate(), WorldGen.CheckSign(), DelegateMethods.CheckStopForSolids(), WorldGen.CheckTileBreakability(), WorldUtils.ClampToWorld(), Utils.ClampWithinWorld(), DesertBiome.CleanupArea(), WorldGen.ClearAllBrokenTraps(), WorldFile.ClearTempTiles(), WorldGen.clearWorld(), WorldGen.CloudIsland(), WorldGen.CloudLake(), WorldGen.Convert(), WorldFile.ConvertIlluminantPaintToNewField(), WorldFile.ConvertOldTileEntities(), WorldGen.CountNearBlocksTypes(), WorldGen.CountTiles(), WorldGen.CountTileTypesInWorld(), TileDrawing.CrawlToBottomOfReverseVineAndAddSpecialPoint(), HiveBiome.CreateHiveTunnel(), MapHelper.CreateMapTile(), HiveBiome.CreateStandForLarva(), JunglePass.CreateStartPoint(), Projectile.CutTilesAt(), WorldUtils.DebugRotate(), DedServ(), WorldGen.DesertCloudIsland(), WorldGen.DestroyHeart(), WorldGen.digTunnel(), WorldGen.DirtyRockRunner(), TeleportPylonsSystem.DoesPylonAcceptTeleportation(), DrawBackground(), DrawBackgroundBlackFill(), DrawBG(), DrawBlack(), DrawCapture(), DrawInfoAccs(), DrawMap(), DrawMapFullscreenBackground(), DrawMenu(), DrawToMap(), DrawUnderworldBackground(), TileDrawing.DrawVineStrip(), WallDrawing.DrawWalls(), DrawWaters(), DrawWires(), WorldGen.dropMeteor(), Collision.DrownCollision(), WorldGen.DungeonEnt(), WorldGen.DungeonHalls(), WorldGen.DungeonPitTrap(), WorldGen.DungeonRoom(), WorldGen.DungeonStairs(), DelegateMethods.EmitGolfCartDust_StopForSolids(), WorldGen.EmptyTileCheck(), WorldGen.EveryTileFrame(), Collision.ExpandVertically(), LightingEngine.ExportToMiniMap(), TerrainPass.FillColumn(), WorldGen.FillWallHolesInColumn(), Searches.Down.Find(), Player.FindSentryRestingSpot(), Player.FindSharpTearsSpot(), WaterfallManager.FindWaterfalls(), UIWorldCreation.FinishCreatingWorld(), WorldGen.FinishDrunkGen(), WorldGen.FinishGetGoodWorld(), WorldGen.FinishNoTraps(), WorldGen.FinishNotTheBees(), WorldGen.FinishRemixWorld(), WorldGen.FinishTenthAnniversaryWorld(), Projectile.FishingCheck(), WorldGen.FixChands(), WorldFile.FixDresserChests(), WorldGen.FixHeart(), WorldGen.FixHearts(), WorldGen.FloatingIsland(), HiveBiome.FrameOutAllHiveContents(), SurfaceMap.FromArea(), PartySky.GenerateBalloons(), JunglePass.GenerateFinishingTouches(), LanternSky.GenerateLanterns(), SlimeSky.GenerateSlimes(), JunglePass.GenerateTunnelToSurface(), WorldGen.GenerateWorld(), WorldGen.GERunner(), MessageBuffer.GetData(), NPC.GetFairyTreasureCoords(), Projectile.GetFishingPondState(), CaptureInterface.GetMapCoords(), TileDrawing.GetScreenDrawArea(), WorldGen.GetSectionBounds(), Collision.GetTilesIn(), WorldGen.GetTreeBottom(), WorldGen.GetWaterDepth(), WorldGen.GrowAlch(), WorldGen.GrowCatTail(), WorldGen.GrowCheckSeaweed(), WorldGen.GrowGlowTulips(), WorldGen.GrowLivingTreePassageRoom(), Projectile.HandleMovement(), WorldGen.HasAnyWireNearby(), NPC.HaveDryadDoStardewAnimation(), WorldGen.HellFort(), WorldGen.HellHouse(), WorldGen.HellRoom(), Collision.HitTiles(), Wiring.HitWire(), WorldGen.Housing_GetTestedRoomBounds(), Collision.HurtTiles(), MapHelper.InternalSaveMap(), WorldGen.InWorld(), BallCollision.IsBallInWorld(), WorldGen.IsFitToPlaceFlowerIn(), WorldGen.IslandHouse(), Player.IsTileTypeInInteractionRange(), Player.ItemCheck_Shoot(), Player.ItemCheck_UseTeleportRod(), Projectile.Kill(), WorldGen.KillTile(), WorldGen.KillWall(), WorldGen.Lakinater(), Collision.LavaCollision(), WorldFile.LoadHeader(), DyeInitializer.LoadLegacyHairdyes(), MapHelper.LoadMapVersion1(), MapHelper.LoadMapVersion2(), WorldFile.LoadWorld(), WorldFile.LoadWorld_Version1_Old_BeforeRelease88(), WorldFile.LoadWorldTiles(), Player.MagicConch(), WorldGen.MakeDungeon(), WorldGen.MakeDungeon_Lights(), Rain.MakeRain(), WorldGen.makeTemple(), WorldGen.MakeWateryIceThing(), WorldGen.MarblePileWithStatues(), WorldGen.MatureTheHerbPlants(), WorldGen.mayanTrap(), WorldGen.meteor(), WorldGen.MineHouse(), Player.MinionRestTargetAim(), WorldGen.Mountinater(), WorldGen.MudWallRunner(), WorldGen.nearbyChlorophyte(), WorldGen.NearFriendlyWall(), WorldGen.neonMossBiome(), Animation.NewTemporaryAnimation(), WorldGen.nextCount(), WorldGen.nextDirtCount(), WorldGen.NoNearbyAbigailsFlower(), WorldGen.NoNearbyGlowTulips(), Collision.noSlopeCollision(), WorldGen.NotTheBees(), WorldGen.oceanCave(), OldDrawBackground(), oldDrawWater(), SpelunkerProjectileHelper.OnPreUpdateAllProjectiles(), WorldGen.OreRunner(), WorldGen.PaintTheClouds(), WorldGen.PaintTheDungeon(), WorldGen.PaintTheLivingTrees(), WorldGen.PaintTheMushrooms(), WorldGen.PaintThePurityGrass(), WorldGen.PaintThePyramids(), WorldGen.PaintTheSand(), WorldGen.PaintTheTemple(), WorldGen.PaintTheTrees(), ShapeFloodFill.Perform(), WorldGen.Place2x2(), WorldGen.Place2x2Horizontal(), WorldGen.Place2x2Style(), WorldGen.Place3x1(), WorldGen.Place3x2(), WorldGen.Place3x4(), WorldGen.Place4x2(), WorldGen.Place5x4(), WorldGen.Place6x3(), WorldGen.PlaceCannon(), WorldGen.PlaceCatTail(), WorldGen.PlaceJunglePlant(), WorldGen.placeLavaTrap(), WorldGen.PlaceLilyPad(), WorldGen.PlaceMB(), WorldGen.PlaceOasis(), WorldGen.PlaceOasisPlant(), WorldGen.PlacePot(), WorldGen.PlacePumpkin(), WorldGen.PlaceSign(), Player.PlaceThing_Tiles_CheckRopeUsability(), WorldGen.PlaceTile(), WorldGen.placeTNTBarrel(), WorldGen.placeTrap(), WorldGen.PlaceWall(), WorldGen.PlantAlch(), WorldGen.PlantCheck(), WorldGen.plantDye(), CaptureInterface.PointWorldClamp(), LegacyLighting.PreRenderPhase(), EmoteBubble.ProbeBiomes(), EmoteBubble.ProbeDebuffs(), WorldGen.QuickFindHome(), Player.QuickMinecart(), Player.QuickStackAllChests(), Liquid.QuickWater(), WorldGen.RandomWorldPoint(), Projectile.ReduceRemainingChumsInPool(), TerrainPass.RetargetColumn(), WorldFile.SaveChests(), WorldFile.SaveWorldHeader(), WorldFile.SaveWorldTiles(), WorldGenRange.ScaleValue(), WorldGen.ScanTileColumnAndRemoveClumps(), MysticLogFairiesEvent.ScanWholeOverworldForLogs(), NetMessage.SendData(), Liquid.SettleWaterAt(), Chest.SetupShop(), WorldGen.setWorldSize(), WorldGen.ShimmeratorNext(), WorldGen.ShimmerCleanUp(), WorldGen.ShroomPatch(), Collision.SlopeCollision(), SmartCursorHelper.SmartCursorLookup(), Player.SmartInteractLookup_PrepareCommonlyUsedInfo(), WorldGen.SmashAltar(), WorldGen.smCallBack(), WorldGen.SnowCloudIsland(), Collision.SolidCollision(), Collision.SolidTiles(), WorldGen.SonOfLakinater(), NPC.SpawnFaelings(), NPC.SpawnNPC(), NPC.SpawnNPC_CheckToSpawnUndergroundFairy(), NPC.SpawnOnPlayer(), WorldGen.SpawnThingsFromPot(), Projectile.SpawnWebs(), NPC.SpawnWOF(), WorldGen.SpreadGrass(), Liquid.StartPanic(), WorldGen.Statue(), SmartCursorHelper.Step_Hammers(), SmartCursorHelper.Step_Pickaxe_MineSolids(), Collision.StickyTiles(), Collision.SwitchTiles(), Collision.SwitchTilesNew(), DelegateMethods.TestDust(), Collision.TileCollision(), WorldGen.tileCountAndDestroy(), WorldGen.tileCounterNext(), WorldGen.TileFrame(), WorldGen.TileRunner(), HiveBiome.TooCloseToImportantLocations(), Player.TorchAttack(), WorldGen.TriggerLunarApocalypse(), WorldGen.TryGrowingAbigailsFlower(), WorldGen.TryGrowingGlowTulip(), Player.TryPlacingAGolfBallNearANearbyTee(), Player.TryRecalculatingTorchLuck(), LegacyLighting.TryUpdatingMapWithLight(), Collision.TupleHitLine(), Collision.TupleHitLineWall(), Player.Update(), UpdateAudio(), UpdateAudio_DecideOnNewMusic(), Player.UpdateBiomes(), Item.UpdateItem(), LegacyLighting.UpdateLightToSkyColor(), NPC.UpdateNPC(), WorldGen.UpdateWorld(), WorldGen.UpdateWorld_GrassGrowth(), WorldGen.UpdateWorld_OvergroundTile(), WorldGen.UpdateWorld_UndergroundTile(), Collision.WalkDownSlope(), Framing.WallFrame(), WorldGen.WaterCheck(), Collision.WaterCollision(), Collision.WetCollision(), and Player.WOFTongue().