Terraria: Main.DrawWoF
DrawWoF()
void Main.DrawWoF () inline protected
     {
         if (wofNPCIndex < 0 || !npc[wofNPCIndex].active || npc[wofNPCIndex].life <= 0)
         {
             return;
         }
         for (int i = 0; i < 255; i++)
         {
             if (player[i].active && player[i].tongued && !player[i].dead)
             {
                 DrawWOFTongueToPlayer(i);
             }
         }
         for (int j = 0; j < 200; j++)
         {
             if (npc[j].active && npc[j].aiStyle == 29)
             {
                 DrawWOFRopeToTheHungry(j);
             }
         }
         DrawWOFBody();
     }
References DrawWOFBody(), DrawWOFRopeToTheHungry(), DrawWOFTongueToPlayer(), npc, player, and wofNPCIndex.
Referenced by DoDraw_WallsTilesNPCs(), and DrawCapture().