Terraria: Main.RenderTiles
RenderTiles()
void Main.RenderTiles () inline protected
     {
         if (drawToScreen)
         {
             return;
         }
         RenderBlack();
         base.GraphicsDevice.SetRenderTarget(tileTarget);
         base.GraphicsDevice.Clear(Microsoft.Xna.Framework.Color.Transparent);
         spriteBatch.Begin();
         tileBatch.Begin();
         try
         {
             TilesRenderer.PreDrawTiles(solidLayer: true, forRenderTargets: false, intoRenderTargets: true);
             DrawTiles(solidLayer: true, forRenderTargets: false, intoRenderTargets: true);
         }
         catch (Exception e)
         {
             if (!ignoreErrors)
             {
                 throw;
             }
             TimeLogger.DrawException(e);
         }
         TimeLogger.DetailedDrawReset();
         tileBatch.End();
         spriteBatch.End();
         DrawTileEntities(solidLayer: true, overRenderTargets: false, intoRenderTargets: true);
         TimeLogger.DetailedDrawTime(28);
         base.GraphicsDevice.SetRenderTarget(null);
     }
References TileBatch.Begin(), TimeLogger.DetailedDrawReset(), TimeLogger.DetailedDrawTime(), TimeLogger.DrawException(), DrawTileEntities(), DrawTiles(), drawToScreen, TileBatch.End(), ignoreErrors, TileDrawing.PreDrawTiles(), RenderBlack(), spriteBatch, tileBatch, TilesRenderer, and tileTarget.
Referenced by DoDraw().