Terraria: Main.GetPlayerArmPosition
GetPlayerArmPosition()
static Vector2 Main.GetPlayerArmPosition (Projectile proj) inline static
     {
         Player player = Main.player[proj.owner];
         Vector2 vector = OffsetsPlayerOnhand[player.bodyFrame.Y / 56] * 2f;
         if (player.direction != 1)
         {
             vector.X = (float)player.bodyFrame.Width - vector.X;
         }
         if (player.gravDir != 1f)
         {
             vector.Y = (float)player.bodyFrame.Height - vector.Y;
         }
         vector -= new Vector2(player.bodyFrame.Width - player.width, player.bodyFrame.Height - 42) / 2f;
         Vector2 pos = player.MountedCenter - new Vector2(20f, 42f) / 2f + vector + Vector2.UnitY * player.gfxOffY;
         if (player.mount.Active && player.mount.Type == 52)
         {
             pos.Y -= player.mount.PlayerOffsetHitbox;
             pos += new Vector2(12 * player.direction, -12f);
         }
         return player.RotatedRelativePoint(pos);
     }
References Mount.Active, Player.bodyFrame, Entity.direction, Player.gfxOffY, Player.gravDir, Player.mount, Player.MountedCenter, OffsetsPlayerOnhand, Projectile.owner, player, Mount.PlayerOffsetHitbox, Player.RotatedRelativePoint(), Mount.Type, and Entity.width.
Referenced by Projectile.AI_165_Whip(), DrawKite(), DrawProj_FlailChains(), and Projectile.FillWhipControlPoints().