Terraria: Main.DrawInterface_Healthbar_Worm
DrawInterface_Healthbar_Worm()
void Main.DrawInterface_Healthbar_Worm (NPC head, int tailID, float scale) inline private
     {
         NPC nPC = head;
         for (int i = head.whoAmI + 1; i < 200; i++)
         {
             if (npc[i].active && npc[i].type == tailID)
             {
                 nPC = npc[i];
                 break;
             }
         }
         Vector2 vector = (head.position + nPC.position) / 2f;
         DrawHealthBar(vector.X + (float)(head.width / 2), vector.Y + (float)(head.height / 2), head.life, head.lifeMax, Lighting.Brightness((int)((head.position.X + (float)(head.width / 2)) / 16f), (int)((head.position.Y + (float)(head.height / 2) + head.gfxOffY) / 16f)), scale);
     }
References Lighting.Brightness(), DrawHealthBar(), NPC.gfxOffY, Entity.height, NPC.life, NPC.lifeMax, npc, Entity.position, Entity.whoAmI, and Entity.width.
Referenced by DrawInterface_14_EntityHealthBars().