Terraria: Main.SkipToTime
SkipToTime()
static void Main.SkipToTime (int timeToSet, bool setIsDayTime) inline static
     {
         _ = time;
         _ = dayTime;
         while (setIsDayTime != dayTime)
         {
             bool stopEvents = ShouldNormalEventsBeAbleToStart();
             if (dayTime)
             {
                 UpdateTime_StartNight(ref stopEvents);
             }
             else
             {
                 UpdateTime_StartDay(ref stopEvents);
             }
         }
         time = timeToSet;
         if (netMode == 2)
         {
             NetMessage.TrySendData(7);
         }
     }
References dayTime, netMode, ShouldNormalEventsBeAbleToStart(), time, NetMessage.TrySendData(), UpdateTime_StartDay(), and UpdateTime_StartNight().
Referenced by CreativePowers.StartDayImmediately.UsePower(), CreativePowers.StartNightImmediately.UsePower(), CreativePowers.StartNoonImmediately.UsePower(), and CreativePowers.StartMidnightImmediately.UsePower().