Terraria: Main.TryInteractingWithMoneyTrough
TryInteractingWithMoneyTrough()
static int Main.TryInteractingWithMoneyTrough (Projectile proj) inline static private
     {
         if (gamePaused || gameMenu)
         {
             return 0;
         }
         bool flag = !SmartCursorIsUsed && !PlayerInput.UsingGamepad;
         Player localPlayer = LocalPlayer;
         Microsoft.Xna.Framework.Point point = proj.Center.ToTileCoordinates();
         Vector2 compareSpot = localPlayer.Center;
         if (!localPlayer.IsProjectileInteractibleAndInInteractionRange(proj, ref compareSpot))
         {
             return 0;
         }
         Matrix matrix = Matrix.Invert(GameViewMatrix.ZoomMatrix);
         Vector2 position = ReverseGravitySupport(MouseScreen);
         Vector2.Transform(screenPosition, matrix);
         Vector2 v = Vector2.Transform(position, matrix) + screenPosition;
         bool flag2 = proj.Hitbox.Contains(v.ToPoint());
         if (!((flag2 || SmartInteractProj == proj.whoAmI) & !localPlayer.lastMouseInterface))
         {
             if (!flag)
             {
                 return 1;
             }
             return 0;
         }
         HasInteractibleObjectThatIsNotATile = true;
         if (flag2)
         {
             localPlayer.noThrow = 2;
             localPlayer.cursorItemIconEnabled = true;
             localPlayer.cursorItemIconID = 3213;
             if (proj.type == 960)
             {
                 localPlayer.cursorItemIconID = 5098;
             }
         }
         if (PlayerInput.UsingGamepad)
         {
             localPlayer.GamepadEnableGrappleCooldown();
         }
         if (mouseRight && mouseRightRelease && Player.BlockInteractionWithProjectiles == 0)
         {
             mouseRightRelease = false;
             localPlayer.tileInteractAttempted = true;
             localPlayer.tileInteractionHappened = true;
             localPlayer.releaseUseTile = false;
             if (localPlayer.chest == -2)
             {
                 localPlayer.chest = -1;
                 PlayInteractiveProjectileOpenCloseSound(proj.type, open: false);
                 Recipe.FindRecipes();
             }
             else
             {
                 localPlayer.chest = -2;
                 for (int i = 0; i < 40; i++)
                 {
                     ItemSlot.SetGlow(i, -1f, chest: true);
                 }
                 localPlayer.piggyBankProjTracker.Set(proj);
                 localPlayer.chestX = point.X;
                 localPlayer.chestY = point.Y;
                 localPlayer.SetTalkNPC(-1);
                 SetNPCShopIndex(0);
                 playerInventory = true;
                 PlayInteractiveProjectileOpenCloseSound(proj.type, open: true);
                 Recipe.FindRecipes();
             }
         }
         if (!SmartCursorIsUsed && !PlayerInput.UsingGamepad)
         {
             return 0;
         }
         if (!flag)
         {
             return 2;
         }
         return 0;
     }
References Player.BlockInteractionWithProjectiles, Entity.Center, chest, Player.chest, Player.chestX, Player.chestY, Player.cursorItemIconEnabled, Player.cursorItemIconID, Recipe.FindRecipes(), gameMenu, Player.GamepadEnableGrappleCooldown(), gamePaused, GameViewMatrix, HasInteractibleObjectThatIsNotATile, Entity.Hitbox, Player.IsProjectileInteractibleAndInInteractionRange(), Player.lastMouseInterface, LocalPlayer, mouseRight, mouseRightRelease, MouseScreen, Player.noThrow, Player.piggyBankProjTracker, playerInventory, PlayInteractiveProjectileOpenCloseSound(), Player.releaseUseTile, ReverseGravitySupport(), screenPosition, TrackedProjectileReference.Set(), ItemSlot.SetGlow(), SetNPCShopIndex(), Player.SetTalkNPC(), SmartCursorIsUsed, SmartInteractProj, Player.tileInteractAttempted, Player.tileInteractionHappened, Projectile.type, PlayerInput.UsingGamepad, Entity.whoAmI, and SpriteViewMatrix.ZoomMatrix.
Referenced by DrawProjDirect().