Terraria: Main.DrawMurderAurora
DrawMurderAurora()
void Main.DrawMurderAurora (Projectile proj) inline private
     {
         Texture2D value = TextureAssets.Projectile[proj.type].Value;
         Vector2 origin = value.Size() / 2f;
         float num = GlobalTimeWrappedHourly % 10f / 10f;
         Vector2 vector = proj.Center - screenPosition;
         float[] array = new float[15];
         float[] array2 = new float[15];
         float[] array3 = new float[15];
         float[] array4 = new float[15];
         float[] array5 = new float[15];
         float num2 = 0.5f;
         int num3 = 210;
         num2 = Utils.GetLerpValue(0f, 60f, proj.timeLeft, clamped: true) * Utils.GetLerpValue(num3, num3 - 60, proj.timeLeft, clamped: true);
         float amount = Utils.GetLerpValue(0f, 60f, proj.timeLeft, clamped: true) * Utils.GetLerpValue(num3, 90f, proj.timeLeft, clamped: true);
         amount = MathHelper.Lerp(0.2f, 0.5f, amount);
         float num4 = 800f / (float)value.Width;
         float num5 = num4 * 0.8f;
         float num6 = (num4 - num5) / 15f;
         float num7 = 30f;
         float num8 = 300f;
         Vector2 vector2 = new Vector2(3f, 6f);
         for (int i = 0; i < 15; i++)
         {
             _ = (float)(i + 1) / 50f;
             float num9 = (float)Math.Sin(num * ((float)Math.PI * 2f) + (float)Math.PI / 2f + (float)i / 2f);
             array[i] = num9 * (num8 - (float)i * 3f);
             array2[i] = (float)Math.Sin(num * ((float)Math.PI * 2f) * 2f + (float)Math.PI / 3f + (float)i) * num7;
             array2[i] -= (float)i * 3f;
             array3[i] = (float)i / 15f * 2f + num;
             array3[i] = (num9 * 0.5f + 0.5f) * 0.6f + num;
             array4[i] = (float)(1.0 - Math.Pow(1f * (float)i / 15f, 2.0));
             array5[i] = num5 + (float)(i + 1) * num6;
             array5[i] *= 0.3f;
             Microsoft.Xna.Framework.Color color = hslToRgb(array3[i] % 1f, 1f, 0.5f) * num2 * amount;
             color.A /= 4;
             float rotation = (float)Math.PI / 2f + num9 * ((float)Math.PI / 4f) * -0.3f + (float)Math.PI * (float)i;
             EntitySpriteDraw(value, vector + new Vector2(array[i], array2[i]), null, color, rotation, origin, new Vector2(array5[i], array5[i]) * vector2, SpriteEffects.None);
         }
     }
References Entity.Center, EntitySpriteDraw(), Utils.GetLerpValue(), GlobalTimeWrappedHourly, hslToRgb(), TextureAssets.Projectile, screenPosition, Projectile.timeLeft, Projectile.type, and Asset< T >.Value.
Referenced by DrawProjDirect().