Terraria: Main.DrawMouseOver
DrawMouseOver()
void Main.DrawMouseOver () inline
     {
         PlayerInput.SetZoom_Unscaled();
         PlayerInput.SetZoom_MouseInWorld();
         Microsoft.Xna.Framework.Rectangle mouseRectangle = new Microsoft.Xna.Framework.Rectangle((int)((float)mouseX + screenPosition.X), (int)((float)mouseY + screenPosition.Y), 1, 1);
         if (player[myPlayer].gravDir == -1f)
         {
             mouseRectangle.Y = (int)screenPosition.Y + screenHeight - mouseY;
         }
         PlayerInput.SetZoom_UI();
         if (!LocalPlayer.ghost)
         {
             ResourceSetsManager.TryToHoverOverResources();
         }
         AchievementAdvisor.DrawMouseHover();
         IngameOptions.MouseOver();
         IngameFancyUI.MouseOver();
         if (!mouseText)
         {
             for (int i = 0; i < 400; i++)
             {
                 if (!item[i].active)
                 {
                     continue;
                 }
                 Microsoft.Xna.Framework.Rectangle drawHitbox = Item.GetDrawHitbox(item[i].type, null);
                 Vector2 bottom = item[i].Bottom;
                 Microsoft.Xna.Framework.Rectangle value = new Microsoft.Xna.Framework.Rectangle((int)(bottom.X - (float)drawHitbox.Width * 0.5f), (int)(bottom.Y - (float)drawHitbox.Height), drawHitbox.Width, drawHitbox.Height);
                 if (mouseRectangle.Intersects(value))
                 {
                     player[myPlayer].cursorItemIconEnabled = false;
                     string text = item[i].AffixName();
                     if (item[i].stack > 1)
                     {
                         text = text + " (" + item[i].stack + ")";
                     }
                     if (item[i].playerIndexTheItemIsReservedFor < 255 && showItemOwner)
                     {
                         text = text + " <" + player[item[i].playerIndexTheItemIsReservedFor].name + ">";
                     }
                     rare = item[i].rare;
                     if (item[i].expert)
                     {
                         rare = -12;
                     }
                     MouseTextHackZoom(text, rare, 0);
                     mouseText = true;
                     break;
                 }
             }
         }
         for (int j = 0; j < 255; j++)
         {
             if (!player[j].active || myPlayer == j || player[j].dead || player[j].ShouldNotDraw || !((double)player[j].stealth > 0.5))
             {
                 continue;
             }
             Microsoft.Xna.Framework.Rectangle value2 = new Microsoft.Xna.Framework.Rectangle((int)((double)player[j].position.X + (double)player[j].width * 0.5 - 16.0), (int)(player[j].position.Y + (float)player[j].height - 48f), 32, 48);
             if (!mouseText && mouseRectangle.Intersects(value2))
             {
                 player[myPlayer].cursorItemIconEnabled = false;
                 int num = player[j].statLife;
                 if (num < 0)
                 {
                     num = 0;
                 }
                 string text2 = player[j].name + ": " + num + "/" + player[j].statLifeMax2;
                 if (player[j].hostile)
                 {
                     text2 = text2 + " " + Language.GetTextValue("Game.PvPFlag");
                 }
                 MouseTextHackZoom(text2, 0, player[j].difficulty);
                 mouseText = true;
             }
         }
         HoveringOverAnNPC = false;
         if (!mouseText)
         {
             HoverOverNPCs(mouseRectangle);
         }
         if (!mouseText && signHover != -1 && sign[signHover] != null && !player[myPlayer].mouseInterface && !string.IsNullOrWhiteSpace(sign[signHover].text))
         {
             int lineAmount;
             string[] array = Utils.WordwrapString(sign[signHover].text, FontAssets.MouseText.Value, 460, 10, out lineAmount);
             lineAmount++;
             spriteBatch.End();
             spriteBatch.Begin(SpriteSortMode.Deferred, null, null, null, null, null, _uiScaleMatrix);
             PlayerInput.SetZoom_UI();
             int num2 = screenWidth;
             int num3 = screenHeight;
             int num4 = mouseX;
             int num5 = mouseY;
             PlayerInput.SetZoom_UI();
             PlayerInput.SetZoom_Test();
             float num6 = 0f;
             for (int k = 0; k < lineAmount; k++)
             {
                 float x = FontAssets.MouseText.Value.MeasureString(array[k]).X;
                 if (num6 < x)
                 {
                     num6 = x;
                 }
             }
             if (num6 > 460f)
             {
                 num6 = 460f;
             }
             bool settingsEnabled_OpaqueBoxBehindTooltips = SettingsEnabled_OpaqueBoxBehindTooltips;
             Vector2 vector = new Vector2(num4, num5) + new Vector2(16f);
             if (settingsEnabled_OpaqueBoxBehindTooltips)
             {
                 vector += new Vector2(8f, 2f);
             }
             if (vector.Y > (float)(num3 - 30 * lineAmount))
             {
                 vector.Y = num3 - 30 * lineAmount;
             }
             if (vector.X > (float)num2 - num6)
             {
                 vector.X = (float)num2 - num6;
             }
             Microsoft.Xna.Framework.Color color = new Microsoft.Xna.Framework.Color(mouseTextColor, mouseTextColor, mouseTextColor, mouseTextColor);
             if (settingsEnabled_OpaqueBoxBehindTooltips)
             {
                 color = Microsoft.Xna.Framework.Color.Lerp(color, Microsoft.Xna.Framework.Color.White, 1f);
                 int num7 = 10;
                 int num8 = 5;
                 Utils.DrawInvBG(spriteBatch, new Microsoft.Xna.Framework.Rectangle((int)vector.X - num7, (int)vector.Y - num8, (int)num6 + num7 * 2, 30 * lineAmount + num8 + num8 / 2), new Microsoft.Xna.Framework.Color(23, 25, 81, 255) * 0.925f * 0.85f);
             }
             for (int l = 0; l < lineAmount; l++)
             {
                 Utils.DrawBorderStringFourWay(spriteBatch, FontAssets.MouseText.Value, array[l], vector.X, vector.Y + (float)(l * 30), color, Microsoft.Xna.Framework.Color.Black, Vector2.Zero);
             }
             mouseText = true;
         }
         PlayerInput.SetZoom_UI();
     }
References _uiScaleMatrix, Item.AffixName(), Entity.Bottom, Player.cursorItemIconEnabled, Utils.DrawBorderStringFourWay(), Utils.DrawInvBG(), AchievementAdvisor.DrawMouseHover(), Item.GetDrawHitbox(), Language.GetTextValue(), Player.ghost, Entity.height, HoveringOverAnNPC, HoverOverNPCs(), item, LocalPlayer, IngameFancyUI.MouseOver(), IngameOptions.MouseOver(), FontAssets.MouseText, mouseText, mouseTextColor, MouseTextHackZoom(), mouseX, mouseY, myPlayer, Player.name, player, Item.playerIndexTheItemIsReservedFor, Entity.position, Item.rare, rare, ResourceSetsManager, screenHeight, screenPosition, screenWidth, SettingsEnabled_OpaqueBoxBehindTooltips, PlayerInput.SetZoom_MouseInWorld(), PlayerInput.SetZoom_Test(), PlayerInput.SetZoom_UI(), PlayerInput.SetZoom_Unscaled(), showItemOwner, sign, signHover, spriteBatch, Item.stack, Player.statLife, Player.statLifeMax2, PlayerResourceSetsManager.TryToHoverOverResources(), Asset< T >.Value, Entity.width, and Utils.WordwrapString().
Referenced by CaptureInterface.Draw(), IngameFancyUI.Draw(), and DrawInterface_39_MouseOver().