Terraria: Main.DrawInterface_32_GamepadRadialHotbars
DrawInterface_32_GamepadRadialHotbars()
static void Main.DrawInterface_32_GamepadRadialHotbars () inline static private
     {
         ItemSlot.DrawRadialCircular(spriteBatch, new Vector2(screenWidth, screenHeight) / 2f, LocalPlayer.CircularRadial, LocalPlayer.inventory);
         ItemSlot.DrawRadialQuicks(spriteBatch, new Vector2(screenWidth, screenHeight) / 2f);
     }
References Player.CircularRadial, ItemSlot.DrawRadialCircular(), ItemSlot.DrawRadialQuicks(), Player.inventory, LocalPlayer, screenHeight, screenWidth, and spriteBatch.
Referenced by SetupDrawInterfaceLayers().