Terraria: Main.InitTargets
InitTargets() [1/2]
void Main.InitTargets () inline protected
     {
         if (!PreventUpdatingTargets)
         {
             UpdateDisplaySettings();
         }
         InitTargets(base.GraphicsDevice.PresentationParameters.BackBufferWidth, base.GraphicsDevice.PresentationParameters.BackBufferHeight);
     }
References PreventUpdatingTargets, and UpdateDisplaySettings().
Referenced by DoDraw(), EnsureRenderTargetContent(), and SetDisplayMode().