Terraria: Main.DrawInterface_18_DiagnoseVideo
DrawInterface_18_DiagnoseVideo()
static void Main.DrawInterface_18_DiagnoseVideo () inline static private
     {
         if (!drawDiag)
         {
             return;
         }
         if (PlayerInput.UsingGamepad)
         {
             for (int i = 0; i < 2; i++)
             {
                 string text = "";
                 int num = 20;
                 int num2 = 160;
                 num2 += i * 16;
                 if (i == 0)
                 {
                     text = "Gamepad Left Thumbstick  : " + string.Format("{0,-10} ,   {1,-10}", PlayerInput.GamepadThumbstickLeft.X.ToString("P2"), PlayerInput.GamepadThumbstickLeft.Y.ToString("P2"));
                 }
                 if (i == 1)
                 {
                     text = "Gamepad Right Thumbstick: " + string.Format("{0,-10} ,   {1,-10}", PlayerInput.GamepadThumbstickRight.X.ToString("P2"), PlayerInput.GamepadThumbstickRight.Y.ToString("P2"));
                 }
                 DynamicSpriteFontExtensionMethods.DrawString(spriteBatch, FontAssets.MouseText.Value, text, new Vector2(num, num2), Microsoft.Xna.Framework.Color.White, 0f, default(Vector2), 1f, SpriteEffects.None, 0f);
             }
         }
         for (int j = 0; j < 7; j++)
         {
             string text2 = "";
             int num3 = 20;
             int num4 = 220;
             num4 += j * 16;
             if (j == 0)
             {
                 text2 = "Solid Tiles:";
             }
             if (j == 1)
             {
                 text2 = "Misc. Tiles:";
             }
             if (j == 2)
             {
                 text2 = "Walls Tiles:";
             }
             if (j == 3)
             {
                 text2 = "Background Tiles:";
             }
             if (j == 4)
             {
                 text2 = "Water Tiles:";
             }
             if (j == 5)
             {
                 text2 = "Black Tiles:";
             }
             if (j == 6)
             {
                 text2 = "Total Render:";
             }
             DynamicSpriteFontExtensionMethods.DrawString(spriteBatch, FontAssets.MouseText.Value, text2, new Vector2(num3, num4), Microsoft.Xna.Framework.Color.White, 0f, default(Vector2), 1f, SpriteEffects.None, 0f);
         }
         for (int k = 0; k < 7; k++)
         {
             string text3 = "";
             int num5 = 180;
             int num6 = 220;
             num6 += k * 16;
             float num7 = ((k != 6) ? TimeLogger.GetDrawTime(k) : TimeLogger.GetDrawTotal());
             text3 = $"{num7:F2}ms";
             DynamicSpriteFontExtensionMethods.DrawString(spriteBatch, FontAssets.MouseText.Value, text3, new Vector2(num5, num6), Microsoft.Xna.Framework.Color.White, 0f, default(Vector2), 1f, SpriteEffects.None, 0f);
         }
         for (int l = 0; l < 6; l++)
         {
             string text4 = "";
             int num8 = 20;
             int num9 = 346;
             num9 += l * 16;
             if (l == 0)
             {
                 text4 = "Lighting Init:";
             }
             if (l == 1)
             {
                 text4 = "Lighting Phase #1:";
             }
             if (l == 2)
             {
                 text4 = "Lighting Phase #2:";
             }
             if (l == 3)
             {
                 text4 = "Lighting Phase #3";
             }
             if (l == 4)
             {
                 text4 = "Lighting Phase #4";
             }
             if (l == 5)
             {
                 text4 = "Total Lighting:";
             }
             DynamicSpriteFontExtensionMethods.DrawString(spriteBatch, FontAssets.MouseText.Value, text4, new Vector2(num8, num9), Microsoft.Xna.Framework.Color.White, 0f, default(Vector2), 1f, SpriteEffects.None, 0f);
         }
         for (int m = 0; m < 6; m++)
         {
             string text5 = "";
             int num10 = 180;
             int num11 = 346;
             num11 += m * 16;
             float num12 = ((m != 5) ? TimeLogger.GetLightingTime(m) : TimeLogger.GetLightingTotal());
             text5 = $"{num12:F2}ms";
             DynamicSpriteFontExtensionMethods.DrawString(spriteBatch, FontAssets.MouseText.Value, text5, new Vector2(num10, num11), Microsoft.Xna.Framework.Color.White, 0f, default(Vector2), 1f, SpriteEffects.None, 0f);
         }
         int num13 = 5;
         for (int n = 0; n < num13; n++)
         {
             string text6 = "";
             int num14 = 20;
             int num15 = 456;
             num15 += n * 16;
             text6 = "Render #" + n + ":";
             DynamicSpriteFontExtensionMethods.DrawString(spriteBatch, FontAssets.MouseText.Value, text6, new Vector2(num14, num15), Microsoft.Xna.Framework.Color.White, 0f, default(Vector2), 1f, SpriteEffects.None, 0f);
         }
         for (int num16 = 0; num16 < num13; num16++)
         {
             string text7 = "";
             int num17 = 180;
             int num18 = 456;
             num18 += num16 * 16;
             text7 = $"{TimeLogger.GetRenderTime(num16):F2}ms";
             DynamicSpriteFontExtensionMethods.DrawString(spriteBatch, FontAssets.MouseText.Value, text7, new Vector2(num17, num18), Microsoft.Xna.Framework.Color.White, 0f, default(Vector2), 1f, SpriteEffects.None, 0f);
         }
         for (int num19 = 0; num19 < num13; num19++)
         {
             string text8 = "";
             int num20 = 230;
             int num21 = 456;
             num21 += num19 * 16;
             num20 += 10;
             text8 = $"{TimeLogger.GetRenderMax(num19):F2}ms";
             DynamicSpriteFontExtensionMethods.DrawString(spriteBatch, FontAssets.MouseText.Value, text8, new Vector2(num20, num21), Microsoft.Xna.Framework.Color.White, 0f, default(Vector2), 1f, SpriteEffects.None, 0f);
         }
         string text9 = "";
         int num22 = 20;
         int num23 = 456 + 16 * num13 + 16;
         text9 = "Update:";
         DynamicSpriteFontExtensionMethods.DrawString(spriteBatch, FontAssets.MouseText.Value, text9, new Vector2(num22, num23), Microsoft.Xna.Framework.Color.White, 0f, default(Vector2), 1f, SpriteEffects.None, 0f);
         text9 = "";
         num22 = 180;
         text9 = $"{upTimer:F2}ms";
         DynamicSpriteFontExtensionMethods.DrawString(spriteBatch, FontAssets.MouseText.Value, text9, new Vector2(num22, num23), Microsoft.Xna.Framework.Color.White, 0f, default(Vector2), 1f, SpriteEffects.None, 0f);
         text9 = "";
         num22 = 240;
         text9 = $"{upTimerMax:F2}ms";
         DynamicSpriteFontExtensionMethods.DrawString(spriteBatch, FontAssets.MouseText.Value, text9, new Vector2(num22, num23), Microsoft.Xna.Framework.Color.White, 0f, default(Vector2), 1f, SpriteEffects.None, 0f);
     }
References drawDiag, DynamicSpriteFontExtensionMethods.DrawString(), PlayerInput.GamepadThumbstickLeft, PlayerInput.GamepadThumbstickRight, TimeLogger.GetDrawTime(), TimeLogger.GetDrawTotal(), TimeLogger.GetLightingTime(), TimeLogger.GetLightingTotal(), FontAssets.MouseText, spriteBatch, PlayerInput.UsingGamepad, and Asset< T >.Value.
Referenced by SetupDrawInterfaceLayers().