Terraria: Main.DrawNPCChatButtons
DrawNPCChatButtons()
static void Main.DrawNPCChatButtons (int superColor, Microsoft.Xna.Framework.Color chatColor, int numLines, string focusText, string focusText3) inline static private
     {
         float y = 130 + numLines * 30;
         int num = 180 + (screenWidth - 800) / 2;
         Vector2 vec = new Vector2(mouseX, mouseY);
         Player player = Main.player[myPlayer];
         Vector2 vector = new Vector2(num, y);
         string text = focusText;
         DynamicSpriteFont value = FontAssets.MouseText.Value;
         Vector2 vector2 = vector;
         Vector2 vector3 = new Vector2(0.9f);
         Vector2 stringSize = ChatManager.GetStringSize(value, text, vector3);
         Microsoft.Xna.Framework.Color baseColor = chatColor;
         Microsoft.Xna.Framework.Color black = Microsoft.Xna.Framework.Color.Black;
         Vector2 vector4 = new Vector2(1f);
         Microsoft.Xna.Framework.Color brown = Microsoft.Xna.Framework.Color.Brown;
         float num2 = 1.2f;
         if (stringSize.X > 260f)
         {
             vector4.X *= 260f / stringSize.X;
         }
         if (vec.Between(vector2, vector2 + stringSize * vector3 * vector4.X) && !PlayerInput.IgnoreMouseInterface)
         {
             player.mouseInterface = true;
             player.releaseUseItem = false;
             vector3 *= num2;
             if (!npcChatFocus2)
             {
                 SoundEngine.PlaySound(12);
             }
             npcChatFocus2 = true;
         }
         else
         {
             if (npcChatFocus2)
             {
                 SoundEngine.PlaySound(12);
             }
             npcChatFocus2 = false;
         }
         ChatManager.DrawColorCodedStringShadow(baseColor: (!npcChatFocus2) ? Microsoft.Xna.Framework.Color.Black : brown, spriteBatch: spriteBatch, font: value, text: text, position: vector2 + stringSize * vector4 * 0.5f, rotation: 0f, origin: stringSize * 0.5f, baseScale: vector3 * vector4);
         ChatManager.DrawColorCodedString(spriteBatch, value, text, vector2 + stringSize * vector4 * 0.5f, baseColor, 0f, stringSize * 0.5f, vector3 * vector4);
         if (text.Length > 0)
         {
             UILinkPointNavigator.SetPosition(2500, vector2 + stringSize * 0.5f);
             UILinkPointNavigator.Shortcuts.NPCCHAT_ButtonsLeft = true;
         }
         Vector2 vector5 = new Vector2((float)num + stringSize.X * vector4.X + 30f, y);
         text = Lang.inter[52].Value;
         value = FontAssets.MouseText.Value;
         vector2 = vector5;
         vector3 = new Vector2(0.9f);
         stringSize = ChatManager.GetStringSize(value, text, vector3);
         baseColor = new Microsoft.Xna.Framework.Color(superColor, (int)((double)superColor / 1.1), superColor / 2, superColor);
         vector4 = new Vector2(1f);
         if (vec.Between(vector2, vector2 + stringSize * vector3 * vector4.X) && !PlayerInput.IgnoreMouseInterface)
         {
             player.mouseInterface = true;
             player.releaseUseItem = false;
             vector3 *= num2;
             if (!npcChatFocus1)
             {
                 SoundEngine.PlaySound(12);
             }
             npcChatFocus1 = true;
         }
         else
         {
             if (npcChatFocus1)
             {
                 SoundEngine.PlaySound(12);
             }
             npcChatFocus1 = false;
         }
         ChatManager.DrawColorCodedStringShadow(baseColor: (!npcChatFocus1) ? Microsoft.Xna.Framework.Color.Black : brown, spriteBatch: spriteBatch, font: value, text: text, position: vector2 + stringSize * vector4 * 0.5f, rotation: 0f, origin: stringSize * 0.5f, baseScale: vector3 * vector4);
         ChatManager.DrawColorCodedString(spriteBatch, value, text, vector2 + stringSize * vector4 * 0.5f, baseColor, 0f, stringSize * 0.5f, vector3 * vector4);
         if (text.Length > 0)
         {
             UILinkPointNavigator.SetPosition(2501, vector2 + stringSize * 0.5f);
             UILinkPointNavigator.Shortcuts.NPCCHAT_ButtonsMiddle = true;
         }
         if (string.IsNullOrWhiteSpace(focusText3))
         {
             npcChatFocus3 = false;
             UILinkPointNavigator.Shortcuts.NPCCHAT_ButtonsRight = false;
         }
         else
         {
             Vector2 vector6 = new Vector2(vector5.X + stringSize.X * vector4.X + 30f, y);
             text = focusText3;
             value = FontAssets.MouseText.Value;
             vector2 = vector6;
             vector3 = new Vector2(0.9f);
             stringSize = ChatManager.GetStringSize(value, text, vector3);
             baseColor = chatColor;
             vector4 = new Vector2(1f);
             vector5.X = vector6.X;
             if (vec.Between(vector2, vector2 + stringSize * vector3 * vector4.X) && !PlayerInput.IgnoreMouseInterface)
             {
                 player.mouseInterface = true;
                 player.releaseUseItem = false;
                 vector3 *= num2;
                 if (!npcChatFocus3)
                 {
                     SoundEngine.PlaySound(12);
                 }
                 npcChatFocus3 = true;
             }
             else
             {
                 if (npcChatFocus3)
                 {
                     SoundEngine.PlaySound(12);
                 }
                 npcChatFocus3 = false;
             }
             ChatManager.DrawColorCodedStringShadow(baseColor: (!npcChatFocus3) ? Microsoft.Xna.Framework.Color.Black : brown, spriteBatch: spriteBatch, font: value, text: text, position: vector2 + stringSize * vector4 * 0.5f, rotation: 0f, origin: stringSize * 0.5f, baseScale: vector3 * vector4);
             ChatManager.DrawColorCodedString(spriteBatch, value, text, vector2 + stringSize * vector4 * 0.5f, baseColor, 0f, stringSize * 0.5f, vector3 * vector4);
             UILinkPointNavigator.SetPosition(2502, vector2 + stringSize * 0.5f);
             UILinkPointNavigator.Shortcuts.NPCCHAT_ButtonsRight = true;
         }
         if (remixWorld)
         {
             return;
         }
         if (Main.player[myPlayer].currentShoppingSettings.HappinessReport == "")
         {
             npcChatFocus4 = false;
             UILinkPointNavigator.Shortcuts.NPCCHAT_ButtonsRight2 = false;
             return;
         }
         string textValue = Language.GetTextValue("UI.NPCCheckHappiness");
         Vector2 vector7 = new Vector2(vector5.X + stringSize.X * vector4.X + 30f, y);
         text = textValue;
         value = FontAssets.MouseText.Value;
         vector2 = vector7;
         vector3 = new Vector2(0.9f);
         stringSize = ChatManager.GetStringSize(value, text, vector3);
         baseColor = new Microsoft.Xna.Framework.Color(superColor, (int)((double)superColor / 1.1), superColor / 2, superColor);
         vector4 = new Vector2(1f);
         if (vec.Between(vector2, vector2 + stringSize * vector3 * vector4.X) && !PlayerInput.IgnoreMouseInterface)
         {
             player.mouseInterface = true;
             player.releaseUseItem = false;
             vector3 *= num2;
             if (!npcChatFocus4)
             {
                 SoundEngine.PlaySound(12);
             }
             npcChatFocus4 = true;
         }
         else
         {
             if (npcChatFocus4)
             {
                 SoundEngine.PlaySound(12);
             }
             npcChatFocus4 = false;
         }
         ChatManager.DrawColorCodedStringShadow(baseColor: (!npcChatFocus4) ? Microsoft.Xna.Framework.Color.Black : brown, spriteBatch: spriteBatch, font: value, text: text, position: vector2 + stringSize * vector4 * 0.5f, rotation: 0f, origin: stringSize * 0.5f, baseScale: vector3 * vector4);
         ChatManager.DrawColorCodedString(spriteBatch, value, text, vector2 + stringSize * vector4 * 0.5f, baseColor, 0f, stringSize * 0.5f, vector3 * vector4);
         UILinkPointNavigator.SetPosition(2503, vector2 + stringSize * 0.5f);
         UILinkPointNavigator.Shortcuts.NPCCHAT_ButtonsRight2 = true;
     }
References Player.currentShoppingSettings, ChatManager.DrawColorCodedString(), ChatManager.DrawColorCodedStringShadow(), ChatManager.GetStringSize(), Language.GetTextValue(), ShoppingSettings.HappinessReport, PlayerInput.IgnoreMouseInterface, Lang.inter, Player.mouseInterface, FontAssets.MouseText, mouseX, mouseY, myPlayer, UILinkPointNavigator.Shortcuts.NPCCHAT_ButtonsLeft, UILinkPointNavigator.Shortcuts.NPCCHAT_ButtonsMiddle, UILinkPointNavigator.Shortcuts.NPCCHAT_ButtonsRight, UILinkPointNavigator.Shortcuts.NPCCHAT_ButtonsRight2, npcChatFocus1, npcChatFocus2, npcChatFocus3, npcChatFocus4, player, SoundEngine.PlaySound(), Player.releaseUseItem, remixWorld, screenWidth, UILinkPointNavigator.SetPosition(), spriteBatch, Asset< T >.Value, and LocalizedText.Value.
Referenced by GUIChatDrawInner().