Terraria: Main.DrawWires
DrawWires()
void Main.DrawWires () inline protected
     {
         Microsoft.Xna.Framework.Rectangle value = new Microsoft.Xna.Framework.Rectangle(0, 0, 16, 16);
         Vector2 zero = Vector2.Zero;
         DrawWiresSpecialTiles.Clear();
         bool flag = !WiresUI.Settings.HideWires;
         float num = 1f;
         if (WiresUI.Settings.HideWires)
         {
             num = 0.5f;
         }
         int num2 = 1;
         int num3 = 1;
         int num4 = 1;
         int num5 = 1;
         int num6 = 1;
         if (player[myPlayer].InfoAccMechShowWires)
         {
             int[] builderAccStatus = player[myPlayer].builderAccStatus;
             num2 = builderAccStatus[4];
             num3 = builderAccStatus[5];
             num4 = builderAccStatus[6];
             num5 = builderAccStatus[7];
             num6 = builderAccStatus[9];
         }
         _ = gfxQuality;
         _ = gfxQuality;
         Vector2 zero2 = Vector2.Zero;
         if (drawToScreen)
         {
             zero2 = Vector2.Zero;
         }
         int num7 = (int)((screenPosition.X - zero2.X) / 16f - 1f);
         int num8 = (int)((screenPosition.X + (float)screenWidth + zero2.X) / 16f) + 2;
         int num9 = (int)((screenPosition.Y - zero2.Y) / 16f - 1f);
         int num10 = (int)((screenPosition.Y + (float)screenHeight + zero2.Y) / 16f) + 5;
         if (num7 < 0)
         {
             num7 = 0;
         }
         if (num8 > maxTilesX)
         {
             num8 = maxTilesX;
         }
         if (num9 < 0)
         {
             num9 = 0;
         }
         if (num10 > maxTilesY)
         {
             num10 = maxTilesY;
         }
         Microsoft.Xna.Framework.Point screenOverdrawOffset = GetScreenOverdrawOffset();
         for (int i = num9 + screenOverdrawOffset.Y; i < num10 - screenOverdrawOffset.Y; i++)
         {
             for (int j = num7 + screenOverdrawOffset.X; j < num8 - screenOverdrawOffset.X; j++)
             {
                 bool flag2 = false;
                 bool flag3 = false;
                 bool flag4 = false;
                 bool flag5 = false;
                 bool flag6 = false;
                 bool flag7 = false;
                 bool flag8 = false;
                 bool flag9 = false;
                 bool flag10 = false;
                 float num11 = 0f;
                 Tile tile = Main.tile[j, i];
                 if (flag && player[myPlayer].CanDoWireStuffHere(j, i))
                 {
                     int num12 = 0;
                     if (tile.active())
                     {
                         if (tile.type == 424)
{
                             switch (tile.frameX / 18)
{
                             case 0:
                                 num12 += 72;
                                 break;
                             case 1:
                                 num12 += 144;
                                 break;
                             case 2:
                                 num12 += 216;
                                 break;
                             }
                         }
                         else if (tile.type == 445)
{
                             num12 += 72;
                         }
                     }
                     if (tile.wire())
                     {
                         num11 += 1f;
                         int num13 = 0;
                         if (Main.tile[j, i - 1].wire())
{
                             num13 += 18;
                             flag4 = true;
                         }
                         if (Main.tile[j + 1, i].wire())
{
                             num13 += 36;
                             flag3 = true;
                         }
                         if (Main.tile[j, i + 1].wire())
{
                             num13 += 72;
                             flag5 = true;
                         }
                         if (Main.tile[j - 1, i].wire())
{
                             num13 += 144;
                             flag2 = true;
                         }
                         value.Y = num12;
                         value.X = num13;
                         Microsoft.Xna.Framework.Color color = Lighting.GetColor(j, i);
                         switch (num2)
{
                         case 0:
                             color = Microsoft.Xna.Framework.Color.White;
                             break;
                         case 2:
                             color *= 0.5f;
                             break;
                         case 3:
                             color = Microsoft.Xna.Framework.Color.Transparent;
                             break;
                         }
                         if (color == Microsoft.Xna.Framework.Color.Transparent)
{
                             num11 -= 1f;
                         }
                         else
{
                             spriteBatch.Draw(TextureAssets.WireNew.Value, new Vector2(j * 16 - (int)screenPosition.X, i * 16 - (int)screenPosition.Y) + zero2, value, color, 0f, zero, 1f, SpriteEffects.None, 0f);
                         }
                     }
                     if (tile.wire2())
                     {
                         flag6 = (flag7 = (flag8 = (flag9 = (flag10 = false))));
                         num11 += 1f;
                         int num14 = 0;
                         if (Main.tile[j, i - 1].wire2())
{
                             num14 += 18;
                             flag8 = true;
                             if (flag4)
{
                                 flag10 = true;
                             }
                         }
                         if (Main.tile[j + 1, i].wire2())
{
                             num14 += 36;
                             flag7 = true;
                             if (flag3)
{
                                 flag10 = true;
                             }
                         }
                         if (Main.tile[j, i + 1].wire2())
{
                             num14 += 72;
                             flag9 = true;
                             if (flag5)
{
                                 flag10 = true;
                             }
                         }
                         if (Main.tile[j - 1, i].wire2())
{
                             num14 += 144;
                             flag6 = true;
                             if (flag2)
{
                                 flag10 = true;
                             }
                         }
                         if (num11 > 1f)
{
                             flag10 = true;
                         }
                         value.Y = num12 + 18;
                         value.X = num14;
                         Microsoft.Xna.Framework.Color color2 = Lighting.GetColor(j, i);
                         switch (num3)
{
                         case 0:
                             color2 = Microsoft.Xna.Framework.Color.White;
                             break;
                         case 2:
                             color2 *= 0.5f;
                             break;
                         case 3:
                             color2 = Microsoft.Xna.Framework.Color.Transparent;
                             break;
                         }
                         if (color2 == Microsoft.Xna.Framework.Color.Transparent)
{
                             num11 -= 1f;
                         }
                         else
{
                             spriteBatch.Draw(TextureAssets.WireNew.Value, new Vector2(j * 16 - (int)screenPosition.X, i * 16 - (int)screenPosition.Y) + zero2, value, color2 * (1f / num11), 0f, zero, 1f, SpriteEffects.None, 0f);
                             if (flag8)
{
                                 if (flag10 && !flag4)
{
                                     spriteBatch.Draw(TextureAssets.WireNew.Value, new Vector2(j * 16 - (int)screenPosition.X, i * 16 - (int)screenPosition.Y) + zero2, new Microsoft.Xna.Framework.Rectangle(18, value.Y, 16, 6), color2, 0f, zero, 1f, SpriteEffects.None, 0f);
                                 }
                                 flag4 = true;
                             }
                             if (flag9)
{
                                 if (flag10 && !flag5)
{
                                     spriteBatch.Draw(TextureAssets.WireNew.Value, new Vector2(j * 16 - (int)screenPosition.X, i * 16 - (int)screenPosition.Y) + zero2 + new Vector2(0f, 10f), new Microsoft.Xna.Framework.Rectangle(72, value.Y + 10, 16, 6), color2, 0f, zero, 1f, SpriteEffects.None, 0f);
                                 }
                                 flag5 = true;
                             }
                             if (flag7)
{
                                 if (flag10 && !flag3)
{
                                     spriteBatch.Draw(TextureAssets.WireNew.Value, new Vector2(j * 16 - (int)screenPosition.X, i * 16 - (int)screenPosition.Y) + zero2 + new Vector2(10f, 0f), new Microsoft.Xna.Framework.Rectangle(46, value.Y, 6, 16), color2, 0f, zero, 1f, SpriteEffects.None, 0f);
                                 }
                                 flag3 = true;
                             }
                             if (flag6)
{
                                 if (flag10 && !flag2)
{
                                     spriteBatch.Draw(TextureAssets.WireNew.Value, new Vector2(j * 16 - (int)screenPosition.X, i * 16 - (int)screenPosition.Y) + zero2, new Microsoft.Xna.Framework.Rectangle(144, value.Y, 6, 16), color2, 0f, zero, 1f, SpriteEffects.None, 0f);
                                 }
                                 flag2 = true;
                             }
                         }
                     }
                     if (tile.wire3())
                     {
                         flag6 = (flag7 = (flag8 = (flag9 = (flag10 = false))));
                         num11 += 1f;
                         int num15 = 0;
                         if (Main.tile[j, i - 1].wire3())
{
                             num15 += 18;
                             flag8 = true;
                             if (flag4)
{
                                 flag10 = true;
                             }
                         }
                         if (Main.tile[j + 1, i].wire3())
{
                             num15 += 36;
                             flag7 = true;
                             if (flag3)
{
                                 flag10 = true;
                             }
                         }
                         if (Main.tile[j, i + 1].wire3())
{
                             num15 += 72;
                             flag9 = true;
                             if (flag5)
{
                                 flag10 = true;
                             }
                         }
                         if (Main.tile[j - 1, i].wire3())
{
                             num15 += 144;
                             flag6 = true;
                             if (flag2)
{
                                 flag10 = true;
                             }
                         }
                         if (num11 > 1f)
{
                             flag10 = true;
                         }
                         value.Y = num12 + 36;
                         value.X = num15;
                         Microsoft.Xna.Framework.Color color3 = Lighting.GetColor(j, i);
                         switch (num4)
{
                         case 0:
                             color3 = Microsoft.Xna.Framework.Color.White;
                             break;
                         case 2:
                             color3 *= 0.5f;
                             break;
                         case 3:
                             color3 = Microsoft.Xna.Framework.Color.Transparent;
                             break;
                         }
                         if (color3 == Microsoft.Xna.Framework.Color.Transparent)
{
                             num11 -= 1f;
                         }
                         else
{
                             spriteBatch.Draw(TextureAssets.WireNew.Value, new Vector2(j * 16 - (int)screenPosition.X, i * 16 - (int)screenPosition.Y) + zero2, value, color3 * (1f / num11), 0f, zero, 1f, SpriteEffects.None, 0f);
                             if (flag8)
{
                                 if (flag10 && !flag4)
{
                                     spriteBatch.Draw(TextureAssets.WireNew.Value, new Vector2(j * 16 - (int)screenPosition.X, i * 16 - (int)screenPosition.Y) + zero2, new Microsoft.Xna.Framework.Rectangle(18, value.Y, 16, 6), color3, 0f, zero, 1f, SpriteEffects.None, 0f);
                                 }
                                 flag4 = true;
                             }
                             if (flag9)
{
                                 if (flag10 && !flag5)
{
                                     spriteBatch.Draw(TextureAssets.WireNew.Value, new Vector2(j * 16 - (int)screenPosition.X, i * 16 - (int)screenPosition.Y) + zero2 + new Vector2(0f, 10f), new Microsoft.Xna.Framework.Rectangle(72, value.Y + 10, 16, 6), color3, 0f, zero, 1f, SpriteEffects.None, 0f);
                                 }
                                 flag5 = true;
                             }
                             if (flag7)
{
                                 if (flag10 && !flag3)
{
                                     spriteBatch.Draw(TextureAssets.WireNew.Value, new Vector2(j * 16 - (int)screenPosition.X, i * 16 - (int)screenPosition.Y) + zero2 + new Vector2(10f, 0f), new Microsoft.Xna.Framework.Rectangle(46, value.Y, 6, 16), color3, 0f, zero, 1f, SpriteEffects.None, 0f);
                                 }
                                 flag3 = true;
                             }
                             if (flag6)
{
                                 if (flag10 && !flag2)
{
                                     spriteBatch.Draw(TextureAssets.WireNew.Value, new Vector2(j * 16 - (int)screenPosition.X, i * 16 - (int)screenPosition.Y) + zero2, new Microsoft.Xna.Framework.Rectangle(144, value.Y, 6, 16), color3, 0f, zero, 1f, SpriteEffects.None, 0f);
                                 }
                                 flag2 = true;
                             }
                         }
                     }
                     if (tile.wire4())
                     {
                         flag6 = (flag7 = (flag8 = (flag9 = (flag10 = false))));
                         num11 += 1f;
                         int num16 = 0;
                         if (Main.tile[j, i - 1].wire4())
{
                             num16 += 18;
                             flag8 = true;
                             if (flag4)
{
                                 flag10 = true;
                             }
                         }
                         if (Main.tile[j + 1, i].wire4())
{
                             num16 += 36;
                             flag7 = true;
                             if (flag3)
{
                                 flag10 = true;
                             }
                         }
                         if (Main.tile[j, i + 1].wire4())
{
                             num16 += 72;
                             flag9 = true;
                             if (flag5)
{
                                 flag10 = true;
                             }
                         }
                         if (Main.tile[j - 1, i].wire4())
{
                             num16 += 144;
                             flag6 = true;
                             if (flag2)
{
                                 flag10 = true;
                             }
                         }
                         if (num11 > 1f)
{
                             flag10 = true;
                         }
                         value.Y = num12 + 54;
                         value.X = num16;
                         Microsoft.Xna.Framework.Color color4 = Lighting.GetColor(j, i);
                         switch (num5)
{
                         case 0:
                             color4 = Microsoft.Xna.Framework.Color.White;
                             break;
                         case 2:
                             color4 *= 0.5f;
                             break;
                         case 3:
                             color4 = Microsoft.Xna.Framework.Color.Transparent;
                             break;
                         }
                         if (color4 == Microsoft.Xna.Framework.Color.Transparent)
{
                             num11 -= 1f;
                         }
                         else
{
                             spriteBatch.Draw(TextureAssets.WireNew.Value, new Vector2(j * 16 - (int)screenPosition.X, i * 16 - (int)screenPosition.Y) + zero2, value, color4 * (1f / num11), 0f, zero, 1f, SpriteEffects.None, 0f);
                             if (flag8)
{
                                 if (flag10 && !flag4)
{
                                     spriteBatch.Draw(TextureAssets.WireNew.Value, new Vector2(j * 16 - (int)screenPosition.X, i * 16 - (int)screenPosition.Y) + zero2, new Microsoft.Xna.Framework.Rectangle(18, value.Y, 16, 6), color4, 0f, zero, 1f, SpriteEffects.None, 0f);
                                 }
                                 flag4 = true;
                             }
                             if (flag9)
{
                                 if (flag10 && !flag5)
{
                                     spriteBatch.Draw(TextureAssets.WireNew.Value, new Vector2(j * 16 - (int)screenPosition.X, i * 16 - (int)screenPosition.Y) + zero2 + new Vector2(0f, 10f), new Microsoft.Xna.Framework.Rectangle(72, value.Y + 10, 16, 6), color4, 0f, zero, 1f, SpriteEffects.None, 0f);
                                 }
                                 flag5 = true;
                             }
                             if (flag7)
{
                                 if (flag10 && !flag3)
{
                                     spriteBatch.Draw(TextureAssets.WireNew.Value, new Vector2(j * 16 - (int)screenPosition.X, i * 16 - (int)screenPosition.Y) + zero2 + new Vector2(10f, 0f), new Microsoft.Xna.Framework.Rectangle(46, value.Y, 6, 16), color4, 0f, zero, 1f, SpriteEffects.None, 0f);
                                 }
                                 flag3 = true;
                             }
                             if (flag6)
{
                                 if (flag10 && !flag2)
{
                                     spriteBatch.Draw(TextureAssets.WireNew.Value, new Vector2(j * 16 - (int)screenPosition.X, i * 16 - (int)screenPosition.Y) + zero2, new Microsoft.Xna.Framework.Rectangle(144, value.Y, 6, 16), color4, 0f, zero, 1f, SpriteEffects.None, 0f);
                                 }
                                 flag2 = true;
                             }
                         }
                     }
                 }
                 if (Main.tile[j, i].actuator() && (Lighting.Brightness(j, i) > 0f || num6 == 0))
                 {
                     Microsoft.Xna.Framework.Color color5 = Lighting.GetColor(j, i);
                     switch (num6)
                     {
                     case 0:
                         color5 = Microsoft.Xna.Framework.Color.White;
                         break;
                     case 2:
                         color5 *= 0.5f;
                         break;
                     case 3:
                         color5 = Microsoft.Xna.Framework.Color.Transparent;
                         break;
                     }
                     spriteBatch.Draw(TextureAssets.Actuator.Value, new Vector2(j * 16 - (int)screenPosition.X, i * 16 - (int)screenPosition.Y) + zero2, new Microsoft.Xna.Framework.Rectangle(0, 0, TextureAssets.Actuator.Width(), TextureAssets.Actuator.Height()), color5 * num, 0f, default(Vector2), 1f, SpriteEffects.None, 0f);
                 }
                 if (tile.active())
                 {
                     ushort type = tile.type;
                     if (type == 423 && tile.frameY == 36)
                     {
                         DrawWiresSpecialTiles.Add(Tuple.Create(j, i, tile.type));
                     }
                 }
             }
         }
         for (int k = 0; k < DrawWiresSpecialTiles.Count; k++)
         {
             Tuple<int, int, ushort> tuple = DrawWiresSpecialTiles[k];
             ushort type = tuple.Item3;
             if (type == 423)
             {
                 Vector2 start = new Vector2(tuple.Item1 * 16 - 32 - 1, tuple.Item2 * 16 - 160 - 1) + zero2;
                 Vector2 end = new Vector2(tuple.Item1 * 16 + 48 + 1, tuple.Item2 * 16 + 1) + zero2;
                 Utils.DrawRectangle(spriteBatch, start, end, Microsoft.Xna.Framework.Color.LightSeaGreen, Microsoft.Xna.Framework.Color.LightSeaGreen, 2f);
             }
         }
         TimeLogger.DetailedDrawTime(34);
     }
References Tile.active(), TextureAssets.Actuator, Tile.actuator(), Lighting.Brightness(), Player.builderAccStatus, TimeLogger.DetailedDrawTime(), Utils.DrawRectangle(), drawToScreen, DrawWiresSpecialTiles, Tile.frameX, Tile.frameY, Lighting.GetColor(), GetScreenOverdrawOffset(), gfxQuality, WiresUI.Settings.HideWires, maxTilesX, maxTilesY, myPlayer, player, screenHeight, screenPosition, screenWidth, spriteBatch, tile, Tile.type, Asset< T >.Value, Tile.wire(), Tile.wire2(), Tile.wire3(), Tile.wire4(), and TextureAssets.WireNew.
Referenced by DoDraw(), and DrawCapture().