Terraria: Main.DrawSplash
DrawSplash()
void Main.DrawSplash (GameTime gameTime) inline protected
     {
         int num = 10000;
         base.GraphicsDevice.Clear(Microsoft.Xna.Framework.Color.Black);
         base.Draw(gameTime);
         TickLoadProcess();
         long num2 = splashTimer.ElapsedMilliseconds;
         if (musicVolume == 0f)
         {
             quickSplash = true;
             num2 = 999999L;
             num = 0;
         }
         if (Assets.PendingAssets == 0 && _musicLoaded && _artLoaded && Program.LoadedEverything)
         {
             _isAsyncLoadComplete = true;
         }
         spriteBatch.Begin();
         splashCounter++;
         Microsoft.Xna.Framework.Color white = Microsoft.Xna.Framework.Color.White;
         byte b = 0;
         if (quickSplash)
         {
             if (splashCounter <= 75)
             {
                 b = (byte)((float)splashCounter / 75f * 255f);
             }
             else if (splashCounter <= 125)
             {
                 b = byte.MaxValue;
             }
             else if (splashCounter <= 200)
             {
                 if (!_isAsyncLoadComplete)
                 {
                     splashCounter = 125;
                 }
                 b = (byte)((float)(75 - (splashCounter - 125)) / 75f * 255f);
             }
             else
             {
                 Initialize_AlmostEverything();
                 PostContentLoadInitialize();
                 showSplash = false;
                 fadeCounter = 75;
                 splashTimer.Stop();
             }
         }
         else
         {
             int num3 = 90;
             int num4 = 410;
             int num5 = 620;
             int num6 = 60;
             if (splashCounter >= num3)
             {
                 if (splashCounter <= num4)
                 {
                     float num7 = (float)(splashCounter - num3) / (float)(num4 - num3);
                     num7 *= num7 * num7 * num7;
                     num7 *= 255f;
                     b = (byte)num7;
                 }
                 else if (splashCounter <= num5)
                 {
                     b = byte.MaxValue;
                     if (splashCounter >= num5 - num6)
                     {
                         b = (byte)((float)(num6 - (splashCounter - (num5 - num6))) / (float)num6 * 255f);
                     }
                 }
                 else if (!_isAsyncLoadComplete)
                 {
                     b = 0;
                     num = 1;
                 }
                 else
                 {
                     Initialize_AlmostEverything();
                     PostContentLoadInitialize();
                     showSplash = false;
                     fadeCounter = 120;
                     splashTimer.Stop();
                 }
             }
         }
         white = new Microsoft.Xna.Framework.Color(b, b, b, b);
         Asset<Texture2D> splashTextureLegoBack = TextureAssets.SplashTextureLegoBack;
         if (splashTextureLegoBack.Width() > 0 && splashTextureLegoBack.Height() > 0)
         {
             Vector2 vector = new Vector2((float)screenWidth / (float)splashTextureLegoBack.Width(), (float)screenHeight / (float)splashTextureLegoBack.Height());
             _ = splashTextureLegoBack.Size() / 2f;
             Vector2 position = new Vector2(screenWidth, screenHeight) / 2f;
             Vector2 scale = vector;
             if (scale.X > scale.Y)
             {
                 scale.X = scale.Y;
             }
             else
             {
                 scale.Y = scale.X;
             }
             Vector2 scale2 = vector;
             if (scale2.X < scale2.Y)
             {
                 scale2.X = scale2.Y;
             }
             else
             {
                 scale2.Y = scale2.X;
             }
             spriteBatch.Draw(splashTextureLegoBack.Value, position, null, white, 0f, splashTextureLegoBack.Size() / 2f, scale2, SpriteEffects.None, 0f);
             spriteBatch.Draw(TextureAssets.SplashTextureLegoTree.Value, ScreenSize.ToVector2(), null, white, 0f, TextureAssets.SplashTextureLegoTree.Size(), scale, SpriteEffects.None, 0f);
             spriteBatch.Draw(TextureAssets.SplashTextureLegoFront.Value, position, null, white, 0f, TextureAssets.SplashTextureLegoFront.Size() / 2f, scale, SpriteEffects.None, 0f);
         }
         int num8 = 70;
         if (num == 1)
         {
             DrawSplash_LoadingFlower(Microsoft.Xna.Framework.Color.White);
         }
         else if (num2 > num)
         {
             DrawSplash_LoadingFlower(white);
         }
         _splashFrameCount += 1f;
         if (_splashFrameCount >= (float)num8)
         {
             _splashFrameCount = 0f;
         }
         spriteBatch.End();
     }
References _artLoaded, _isAsyncLoadComplete, _musicLoaded, _splashFrameCount, Assets, DrawSplash_LoadingFlower(), fadeCounter, Initialize_AlmostEverything(), L, Program.LoadedEverything, musicVolume, IAssetRepository.PendingAssets, PostContentLoadInitialize(), quickSplash, screenHeight, ScreenSize, screenWidth, showSplash, splashCounter, TextureAssets.SplashTextureLegoBack, TextureAssets.SplashTextureLegoFront, TextureAssets.SplashTextureLegoTree, splashTimer, spriteBatch, TickLoadProcess(), and Asset< T >.Value.
Referenced by DoDraw().