Terraria: Main.updateCloudLayer
updateCloudLayer()
void Main.updateCloudLayer () inline
     {
         if (netMode == 1 || (netMode == 0 && gameMenu))
         {
             return;
         }
         int num = 86400;
         int num2 = num / 24;
         float num3 = Math.Max(1f, 1f + 4f * cloudAlpha);
         if (cloudBGActive > 0f)
         {
             if (cloudBGActive > 1f)
             {
                 cloudBGActive -= (float)dayRate / num3;
             }
             if (cloudBGActive < 1f)
             {
                 cloudBGActive = 1f;
             }
             if (cloudBGActive == 1f && rand.Next((int)((float)(num2 * 2 / Math.Max(dayRate, 1)) * num3)) == 0)
             {
                 cloudBGActive = -rand.Next(num2 * 4, num * 4);
                 if (netMode == 2)
                 {
                     NetMessage.SendData(7);
                 }
             }
             return;
         }
         if (cloudBGActive < 0f)
         {
             cloudBGActive += (float)dayRate * num3;
             if (raining)
             {
                 cloudBGActive += (float)(2 * dayRate) * num3;
             }
         }
         if (cloudBGActive > 0f)
         {
             cloudBGActive = 0f;
         }
         if (cloudBGActive == 0f && rand.Next((int)((float)(num2 * 12 / ((dayRate == 0) ? 1 : dayRate)) / num3)) == 0)
         {
             cloudBGActive = rand.Next(num2 * 3, num * 2);
             if (netMode == 2)
             {
                 NetMessage.SendData(7);
             }
         }
         else if (IsItStorming)
         {
             cloudBGActive = rand.Next(num2, num2 * 4);
             if (netMode == 2)
             {
                 NetMessage.SendData(7);
             }
         }
     }
References cloudAlpha, cloudBGActive, dayRate, gameMenu, IsItStorming, netMode, UnifiedRandom.Next(), raining, rand, and NetMessage.SendData().
Referenced by DoUpdate().