Terraria: Main.DrawBlockReplacementIcon
DrawBlockReplacementIcon()
void Main.DrawBlockReplacementIcon (int pivotTopLeftX, int pivotTopLeftY, bool pushSideToolsUp, int gamepadPointOffset) inline private
     {
         if (!playerInventory)
         {
             return;
         }
         int num = 44 + pivotTopLeftY;
         _ = player[myPlayer];
         if (pushSideToolsUp)
         {
             num = 23 + pivotTopLeftY;
         }
         float num2 = 0.9f;
         int num3 = 10;
         bool flag = player[myPlayer].builderAccStatus[num3] == 0;
         Texture2D value = TextureAssets.blockReplaceIcon[0].Value;
         Microsoft.Xna.Framework.Rectangle rectangle = value.Frame(3, 1, (!flag) ? 1 : 0);
         bool flag2 = false;
         if (mouseX > pivotTopLeftX && (float)mouseX < (float)pivotTopLeftX + (float)rectangle.Width * num2 && mouseY > num && (float)mouseY < (float)num + (float)rectangle.Height * num2)
         {
             flag2 = true;
             player[myPlayer].mouseInterface = true;
             MouseText(flag ? Language.GetTextValue("GameUI.BlockReplacerOn") : Language.GetTextValue("GameUI.BlockReplacerOff"), 0, 0);
             mouseText = true;
             if (mouseLeft && mouseLeftRelease)
             {
                 SoundEngine.PlaySound(22);
                 player[myPlayer].builderAccStatus[num3] = (flag ? 1 : 0);
             }
         }
         Vector2 vector = new Vector2(pivotTopLeftX, num);
         spriteBatch.Draw(value, vector, rectangle, Microsoft.Xna.Framework.Color.White, 0f, default(Vector2), num2, SpriteEffects.None, 0f);
         if (flag2)
         {
             spriteBatch.Draw(value, vector, value.Frame(3, 1, 2), OurFavoriteColor, 0f, default(Vector2), num2, SpriteEffects.None, 0f);
         }
         UILinkPointNavigator.SetPosition(6000 + gamepadPointOffset, vector + rectangle.Size() * 0.65f);
     }
References TextureAssets.blockReplaceIcon, Player.builderAccStatus, Language.GetTextValue(), Player.mouseInterface, mouseLeft, mouseLeftRelease, mouseText, MouseText(), mouseX, mouseY, myPlayer, OurFavoriteColor, player, playerInventory, SoundEngine.PlaySound(), UILinkPointNavigator.SetPosition(), spriteBatch, and Asset< T >.Value.
Referenced by DrawBuilderAccToggles().