Terraria: Main.DoUpdateInWorld
DoUpdateInWorld()
void Main.DoUpdateInWorld (Stopwatch sw) inline private
     {
         UpdateParticleSystems();
         tileSolid[379] = false;
         int num = 0;
         int num2 = 0;
         sittingManager.ClearPlayerAnchors();
         sleepingManager.ClearPlayerAnchors();
         for (int i = 0; i < 255; i++)
         {
             if (!player[i].active)
             {
                 continue;
             }
             try
             {
                 player[i].Update(i);
                 if (player[i].active)
                 {
                     num++;
                     if (player[i].sleeping.FullyFallenAsleep)
                     {
                         num2++;
                     }
                 }
             }
             catch
             {
                 if (!ignoreErrors)
                 {
                     throw;
                 }
             }
         }
         CurrentFrameFlags.ActivePlayersCount = num;
         CurrentFrameFlags.SleepingPlayersCount = num2;
         if (netMode != 2)
         {
             int num3 = myPlayer;
             if (player[num3].creativeGodMode)
             {
                 player[num3].statLife = player[num3].statLifeMax2;
                 player[num3].statMana = player[num3].statManaMax2;
                 player[num3].breath = player[num3].breathMax;
             }
         }
         _gameUpdateCount++;
         NPC.RevengeManager.Update();
         if (netMode != 1)
         {
             if (remixWorld)
             {
                 NPC.SetRemixHax();
             }
             try
             {
                 NPC.SpawnNPC();
             }
             catch
             {
             }
             if (remixWorld)
             {
                 NPC.ResetRemixHax();
             }
         }
         if (netMode != 1)
         {
             PressurePlateHelper.Update();
         }
         for (int j = 0; j < 255; j++)
         {
             player[j].nearbyActiveNPCs = 0f;
             player[j].townNPCs = 0f;
         }
         CheckBossIndexes();
         sittingManager.ClearNPCAnchors();
         sleepingManager.ClearNPCAnchors();
         NPC.taxCollector = false;
         NPC.ClearFoundActiveNPCs();
         NPC.UpdateFoundActiveNPCs();
         FixExploitManEaters.Update();
         if (netMode != 1)
         {
             BestiaryTracker.Sights.ScanWorldForFinds();
         }
         bool anyActiveBossNPC = false;
         if (NPC.offSetDelayTime > 0)
         {
             NPC.offSetDelayTime--;
         }
         if (remixWorld && NPC.empressRageMode && !NPC.AnyNPCs(636))
         {
             NPC.empressRageMode = false;
         }
         if (netMode != 1 && afterPartyOfDoom && !BirthdayParty.PartyIsUp)
         {
             for (int k = 0; k < 200; k++)
             {
                 NPC nPC = npc[k];
                 if (nPC.active && nPC.townNPC && nPC.type != 37 && nPC.type != 453 && nPC.type != 368)
                 {
                     nPC.StrikeNPCNoInteraction(9999, 10f, -nPC.direction);
                     if (netMode == 2)
                     {
                         NetMessage.SendData(28, -1, -1, null, k, 9999f, 10f, -nPC.direction);
                     }
                 }
             }
             NPC.unlockedPartyGirlSpawn = false;
             NPC.unlockedPrincessSpawn = false;
             NPC.unlockedSlimeRainbowSpawn = false;
             NPC.unlockedSlimeGreenSpawn = false;
             afterPartyOfDoom = false;
         }
         if (NPC.brainOfGravity >= 0 && NPC.brainOfGravity < 200 && (!npc[NPC.brainOfGravity].active || npc[NPC.brainOfGravity].type != 266))
         {
             NPC.brainOfGravity = -1;
         }
         for (int l = 0; l < 200; l++)
         {
             if (ignoreErrors)
             {
                 try
                 {
                     npc[l].UpdateNPC(l);
                     if (npc[l].active && (npc[l].boss || NPCID.Sets.DangerThatPreventsOtherDangers[npc[l].type]))
                     {
                         anyActiveBossNPC = true;
                     }
                 }
                 catch (Exception)
                 {
                     npc[l] = new NPC();
                 }
             }
             else
             {
                 npc[l].UpdateNPC(l);
             }
         }
         CurrentFrameFlags.AnyActiveBossNPC = anyActiveBossNPC;
         for (int m = 0; m < 600; m++)
         {
             if (ignoreErrors)
             {
                 try
                 {
                     gore[m].Update();
                 }
                 catch
                 {
                     gore[m] = new Gore();
                 }
             }
             else
             {
                 gore[m].Update();
             }
         }
         LockOnHelper.SetUP();
         CurrentFrameFlags.HadAnActiveInteractibleProjectile = false;
         PreUpdateAllProjectiles();
         for (int n = 0; n < 1000; n++)
         {
             ProjectileUpdateLoopIndex = n;
             if (ignoreErrors)
             {
                 try
                 {
                     projectile[n].Update(n);
                 }
                 catch
                 {
                     projectile[n] = new Projectile();
                 }
             }
             else
             {
                 projectile[n].Update(n);
             }
         }
         ProjectileUpdateLoopIndex = -1;
         PostUpdateAllProjectiles();
         LockOnHelper.SetDOWN();
         Item.numberOfNewItems = 0;
         for (int num4 = 0; num4 < 400; num4++)
         {
             if (ignoreErrors)
             {
                 try
                 {
                     item[num4].UpdateItem(num4);
                 }
                 catch
                 {
                     item[num4] = new Item();
                 }
             }
             else
             {
                 item[num4].UpdateItem(num4);
             }
         }
         if (ignoreErrors)
         {
             try
             {
                 Dust.UpdateDust();
             }
             catch
             {
                 for (int num5 = 0; num5 < 6000; num5++)
                 {
                     dust[num5] = new Dust();
                     dust[num5].dustIndex = num5;
                 }
             }
         }
         else
         {
             Dust.UpdateDust();
         }
         if (netMode != 2)
         {
             CombatText.UpdateCombatText();
             PopupText.UpdateItemText();
         }
         if (ignoreErrors)
         {
             try
             {
                 UpdateTime();
             }
             catch
             {
                 checkForSpawns = 0;
             }
         }
         else
         {
             UpdateTime();
         }
         tileSolid[379] = true;
         if (gameMenu && netMode != 2)
         {
             return;
         }
         if (netMode != 1)
         {
             if (ignoreErrors)
             {
                 try
                 {
                     WorldGen.UpdateWorld();
                     UpdateInvasion();
                 }
                 catch
                 {
                 }
             }
             else
             {
                 WorldGen.UpdateWorld();
                 UpdateInvasion();
             }
         }
         if (ignoreErrors)
         {
             try
             {
                 if (netMode == 2)
                 {
                     UpdateServer();
                 }
                 if (netMode == 1)
                 {
                     UpdateClient();
                 }
             }
             catch
             {
                 _ = netMode;
                 _ = 2;
             }
         }
         else
         {
             if (netMode == 2)
             {
                 UpdateServer();
             }
             if (netMode == 1)
             {
                 UpdateClient();
             }
         }
         chatMonitor.Update();
         upTimer = (float)sw.Elapsed.TotalMilliseconds;
         if (upTimerMaxDelay > 0f)
         {
             upTimerMaxDelay -= 1f;
         }
         else
         {
             upTimerMax = 0f;
         }
         if (upTimer > upTimerMax)
         {
             upTimerMax = upTimer;
             upTimerMaxDelay = 400f;
         }
         Chest.UpdateChestFrames();
         _ambientWindSys.Update();
         TilesRenderer.Update();
         WallsRenderer.Update();
         if (cameraLerp > 0f)
         {
             cameraLerpTimer++;
             if (cameraLerpTimer >= cameraLerpTimeToggle)
             {
                 cameraLerp += (float)((cameraLerpTimer - cameraLerpTimeToggle) / 3 + 1) * 0.001f;
             }
             if (cameraLerp > 1f)
             {
                 cameraLerp = 1f;
             }
         }
     }
References _ambientWindSys, _gameUpdateCount, Entity.active, Main.CurrentFrameFlags.ActivePlayersCount, afterPartyOfDoom, Main.CurrentFrameFlags.AnyActiveBossNPC, NPC.AnyNPCs(), BestiaryTracker, NPC.brainOfGravity, Player.breath, Player.breathMax, cameraLerp, cameraLerpTimer, cameraLerpTimeToggle, chatMonitor, CheckBossIndexes(), checkForSpawns, NPC.ClearFoundActiveNPCs(), AnchoredEntitiesCollection.ClearNPCAnchors(), AnchoredEntitiesCollection.ClearPlayerAnchors(), NPCID.Sets.DangerThatPreventsOtherDangers, Entity.direction, dust, Dust.dustIndex, NPC.empressRageMode, gameMenu, gore, Main.CurrentFrameFlags.HadAnActiveInteractibleProjectile, ignoreErrors, item, myPlayer, Player.nearbyActiveNPCs, netMode, NPC, npc, Item.numberOfNewItems, NPC.offSetDelayTime, BirthdayParty.PartyIsUp, player, PostUpdateAllProjectiles(), PreUpdateAllProjectiles(), projectile, ProjectileUpdateLoopIndex, remixWorld, NPC.ResetRemixHax(), NPC.RevengeManager, NPCWasNearPlayerTracker.ScanWorldForFinds(), NetMessage.SendData(), LockOnHelper.SetDOWN(), NPC.SetRemixHax(), LockOnHelper.SetUP(), BestiaryUnlocksTracker.Sights, sittingManager, sleepingManager, Main.CurrentFrameFlags.SleepingPlayersCount, NPC.SpawnNPC(), Player.statLife, Player.statLifeMax2, Player.statMana, Player.statManaMax2, NPC.StrikeNPCNoInteraction(), NPC.taxCollector, tileSolid, TilesRenderer, NPC.townNPC, Player.townNPCs, NPC.type, NPC.unlockedPartyGirlSpawn, NPC.unlockedPrincessSpawn, NPC.unlockedSlimeGreenSpawn, NPC.unlockedSlimeRainbowSpawn, TileDrawing.Update(), WallDrawing.Update(), IChatMonitor.Update(), AmbientWindSystem.Update(), CoinLossRevengeSystem.Update(), FixExploitManEaters.Update(), PressurePlateHelper.Update(), Gore.Update(), Player.Update(), Projectile.Update(), Chest.UpdateChestFrames(), UpdateClient(), CombatText.UpdateCombatText(), Dust.UpdateDust(), NPC.UpdateFoundActiveNPCs(), UpdateInvasion(), Item.UpdateItem(), PopupText.UpdateItemText(), NPC.UpdateNPC(), UpdateParticleSystems(), UpdateServer(), UpdateTime(), WorldGen.UpdateWorld(), upTimer, upTimerMax, upTimerMaxDelay, and WallsRenderer.
Referenced by DoUpdate().