Terraria: Main.DrawLiquid
DrawLiquid()
void Main.DrawLiquid (bool bg = false, int waterStyle = 0, float Alpha = 1f, bool drawSinglePassLiquids = true) inline protected
     {
         if (!Lighting.NotRetro)
         {
             oldDrawWater(bg, waterStyle, Alpha);
             return;
         }
         Stopwatch stopwatch = new Stopwatch();
         stopwatch.Start();
         Vector2 drawOffset = (drawToScreen ? Vector2.Zero : new Vector2(offScreenRange, offScreenRange)) - screenPosition;
         if (bg)
         {
             TilesRenderer.DrawLiquidBehindTiles(waterStyle);
         }
         LiquidRenderer.Instance.DrawNormalLiquids(spriteBatch, drawOffset, waterStyle, Alpha, bg);
         if (drawSinglePassLiquids)
         {
             LiquidRenderer.Instance.DrawShimmer(spriteBatch, drawOffset, bg);
         }
         if (!bg)
         {
             TimeLogger.DrawTime(4, stopwatch.Elapsed.TotalMilliseconds);
         }
     }
References TileDrawing.DrawLiquidBehindTiles(), LiquidRenderer.DrawNormalLiquids(), LiquidRenderer.DrawShimmer(), TimeLogger.DrawTime(), drawToScreen, LiquidRenderer.Instance, Lighting.NotRetro, offScreenRange, oldDrawWater(), screenPosition, spriteBatch, TilesRenderer, and waterStyle.
Referenced by DrawCapture(), and DrawWaters().