Terraria: Main.LoadSettings
LoadSettings()
void Main.LoadSettings () inline protected
     {
         if (File.Exists(SavePath + Path.DirectorySeparatorChar + "config.dat"))
         {
             OpenLegacySettings();
             if (SaveSettings())
             {
                 File.Delete(SavePath + Path.DirectorySeparatorChar + "config.dat");
             }
             return;
         }
         IsInTheMiddleOfLoadingSettings = true;
         Preferences configuration = Configuration;
         configuration.Load();
         int currentValue = 0;
         configuration.Get("LastLaunchedVersion", ref currentValue);
         bool flag = false;
         if (currentValue < 219)
         {
             flag = true;
         }
         if (!flag)
         {
             configuration.Get("ResetDefaultUIScale", ref shouldSetDefaultUIScale);
             configuration.Get("Fullscreen", ref startFullscreen);
             configuration.Get("WindowMaximized", ref screenMaximized);
             configuration.Get("WindowBorderless", ref screenBorderless);
         }
         PendingBorderlessState = screenBorderless;
         screenBorderlessPendingResizes = (screenBorderless ? 6 : 0);
         if (Platform.IsWindows && !dedServ)
         {
             Form form = (Form)Control.FromHandle(instance.Window.Handle);
             if (screenBorderless)
             {
                 SetBorderlessFormStyle(form);
             }
             else if (screenMaximized)
             {
                 form.FormBorderStyle = FormBorderStyle.Sizable;
                 form.WindowState = FormWindowState.Maximized;
             }
             else
             {
                 form.FormBorderStyle = FormBorderStyle.Sizable;
             }
             form.BringToFront();
         }
         int currentValue2 = graphics.PreferredBackBufferWidth;
         int currentValue3 = graphics.PreferredBackBufferHeight;
         configuration.Get("DisplayWidth", ref currentValue2);
         configuration.Get("DisplayHeight", ref currentValue3);
         LastLoadedResolution = new Microsoft.Xna.Framework.Point(currentValue2, currentValue3);
         if (!startFullscreen)
         {
             if (PendingBorderlessState)
             {
                 screenBorderlessPendingResizes = 1;
             }
             SetDisplayMode(currentValue2, currentValue3, fullscreen: false);
             TryPickingDefaultUIScale(currentValue3);
         }
         configuration.Get("SmartCursorToggle", ref cSmartCursorModeIsToggleAndNotHold);
         configuration.Get("MapEnabled", ref mapEnabled);
         configuration.Get("InvasionBarMode", ref invasionProgressMode);
         configuration.Get("AutoSave", ref autoSave);
         configuration.Get("AutoPause", ref autoPause);
         _needsLanguageSelect = !configuration.Contains("Language");
         string text = configuration.Get("Language", "en-US");
         int result = 0;
         if (int.TryParse(text, out result))
         {
             LanguageManager.Instance.SetLanguage(result);
             SetTitle();
         }
         else
         {
             LanguageManager.Instance.SetLanguage(text);
             SetTitle();
         }
         configuration.Get("PlacementPreview", ref placementPreview);
         configuration.Get("GoreVisualsAllowed", ref ChildSafety.Disabled);
         configuration.Get("DisableIntenseVisualEffects", ref DisableIntenseVisualEffects);
         if (!flag)
         {
             configuration.Get("VolumeSound", ref soundVolume);
             configuration.Get("VolumeAmbient", ref ambientVolume);
             configuration.Get("VolumeMusic", ref musicVolume);
         }
         configuration.Get("KeyFavoriteModifier", ref cFavoriteKey);
         if (Enum.TryParse<Microsoft.Xna.Framework.Input.Keys>(cFavoriteKey, out var result2))
         {
             FavoriteKey = result2;
         }
         if (!flag)
         {
             configuration.Get("GraphicsQuality", ref qaStyle);
             configuration.Get("BackgroundEnabled", ref BackgroundEnabled);
         }
         if (configuration.GetAllKeys().Contains("FrameSkip"))
         {
             bool currentValue4 = false;
             configuration.Get("FrameSkip", ref currentValue4);
             terrariasFixedTiming = !currentValue4;
             if (terrariasFixedTiming)
             {
                 FrameSkipMode = FrameSkipMode.Subtle;
             }
             else
             {
                 FrameSkipMode = FrameSkipMode.On;
             }
         }
         int currentValue5 = (int)FrameSkipMode;
         configuration.Get("FrameSkipMode", ref currentValue5);
         if (currentValue5 < 0)
         {
             currentValue5 = 0;
         }
         if (currentValue5 > 2)
         {
             currentValue5 = 2;
         }
         FrameSkipMode = (FrameSkipMode)currentValue5;
         int currentValue6 = (int)Lighting.Mode;
         if (!flag)
         {
             configuration.Get("LightingMode", ref currentValue6);
         }
         Lighting.Mode = (LightMode)currentValue6;
         configuration.Get("UnlockMusicSwap", ref TOWMusicUnlocked);
         configuration.Get("Parallax", ref caveParallax);
         bgScroll = (int)((1f - caveParallax) * 500f);
         configuration.Get("BackgroundParallax", ref bgScroll);
         caveParallax = 1f - (float)bgScroll / 500f;
         configuration.Get("ShowItemText", ref showItemText);
         configuration.Get("ClientUUID", ref clientUUID);
         configuration.Get("UseSmartCursorForCommonBlocks", ref Player.SmartCursorSettings.SmartBlocksEnabled);
         configuration.Get("UseSmartAxeAfterSmartPickaxe", ref Player.SmartCursorSettings.SmartAxeAfterPickaxe);
         configuration.Get("SmartCursorHoldCanReleaseMidUse", ref Player.SmartCursorSettings.SmartCursorHoldCanReleaseMidUse);
         if (!flag)
         {
             configuration.Get("DisableLeftShiftTrashCan", ref ItemSlot.Options.DisableLeftShiftTrashCan);
         }
         if (!flag)
         {
             configuration.Get("DisableQuickTrash", ref ItemSlot.Options.DisableQuickTrash);
         }
         configuration.Get("HidePasswords", ref HidePassword);
         configuration.Get("HighlightNewItems", ref ItemSlot.Options.HighlightNewItems);
         configuration.Get("ReverseUpDownForArmorSetBonuses", ref ReversedUpDownArmorSetBonuses);
         configuration.Get("MouseShowBuildingGrid", ref MouseShowBuildingGrid);
         configuration.Get("AllowUnfocusedInputOnGamepad", ref AllowUnfocusedInputOnGamepad);
         configuration.Get("GamepadDisableInstructionsDisplay", ref GamepadDisableInstructionsDisplay);
         configuration.Get("SettingDontScaleMainMenuUp", ref SettingDontScaleMainMenuUp);
         configuration.Get("WorldRollbacksToKeep", ref WorldRollingBackupsCountToKeep);
         configuration.Get("TeamNameplateDistance", ref teamNamePlateDistance);
         if (currentValue < 230)
         {
             configuration.Get("MultiplayerNPCSmoothingRange", ref multiplayerNPCSmoothingRange);
         }
         configuration.Get("UseStormEffect", ref UseStormEffects);
         configuration.Get("UseHeatDistortion", ref UseHeatDistortion);
         configuration.Get("WaveQuality", ref WaveQuality);
         if (WaveQuality > 3)
         {
             WaveQuality = 3;
         }
         if (WaveQuality < 0)
         {
             WaveQuality = 0;
         }
         Dictionary<string, byte> currentValue7 = new Dictionary<string, byte>();
         configuration.Get("MouseColor", ref currentValue7);
         if (currentValue7.TryGetValue("R", out var value))
         {
             mouseColor.R = value;
         }
         if (currentValue7.TryGetValue("G", out value))
         {
             mouseColor.G = value;
         }
         if (currentValue7.TryGetValue("B", out value))
         {
             mouseColor.B = value;
         }
         currentValue7.Clear();
         configuration.Get("MouseBorderColor", ref currentValue7);
         if (currentValue7.TryGetValue("R", out value))
         {
             MouseBorderColor.R = value;
         }
         if (currentValue7.TryGetValue("G", out value))
         {
             MouseBorderColor.G = value;
         }
         if (currentValue7.TryGetValue("B", out value))
         {
             MouseBorderColor.B = value;
         }
         if (currentValue7.TryGetValue("A", out value))
         {
             MouseBorderColor.A = value;
         }
         configuration.Get("QuickLaunch", ref SkipAssemblyLoad);
         if (!flag)
         {
             GameZoomTarget = configuration.Get("Zoom", 1f);
         }
         if (!flag)
         {
             UIScale = configuration.Get("UIScale", Platform.Get<IWindowService>().GetScaling());
         }
         if (newDefaultUIScale > 0f)
         {
             UIScale = newDefaultUIScale;
             newDefaultUIScale = 0f;
         }
         MapScale = MathHelper.Clamp(configuration.Get("MapScale", InitialMapScale), 0.5f, 1f);
         int currentValue8 = -1;
         configuration.Get("LockOnPriority", ref currentValue8);
         if (currentValue8 < 0)
         {
             currentValue8 = 0;
         }
         if (currentValue8 > 2)
         {
             currentValue8 = 2;
         }
         LockOnHelper.UseMode = (LockOnHelper.LockOnMode)currentValue8;
         if (LockOnHelper.UseMode == LockOnHelper.LockOnMode.FocusTarget)
         {
             LockOnHelper.UseMode = LockOnHelper.LockOnMode.ThreeDS;
         }
         configuration.Get("InvisibleCursorForGamepad", ref InvisibleCursorForGamepad);
         if (Enum.TryParse<GameNotificationType>(configuration.Get("FlashIconForEvents", "All"), out var result3))
         {
             _flashNotificationType = result3;
         }
         if (!flag)
         {
             string screenDeviceName = configuration.Get("DisplayScreen", "");
             _windowMover.TryMovingToScreen(screenDeviceName);
             bool flag2 = configuration.Get("ThrottleWhenInactive", defaultValue: true);
             base.InactiveSleepTime = TimeSpan.FromMilliseconds(flag2 ? 20 : 0);
         }
         if (!flag)
         {
             configuration.Get("Support4K", ref Support4K);
         }
         configuration.Get("UseExperimentalFeatures", ref UseExperimentalFeatures);
         configuration.Get("SettingsUnlock_WorldEvil", ref SettingsUnlock_WorldEvil);
         configuration.Get("SettingsEnabled_MinersWobble", ref SettingsEnabled_MinersWobble);
         configuration.Get("SettingBlockGamepadsEntirely", ref SettingBlockGamepadsEntirely);
         configuration.Get("SettingsEnabled_OpaqueBoxBehindTooltips", ref SettingsEnabled_OpaqueBoxBehindTooltips);
         configuration.Get("SettingsEnabled_TilesSwayInWind", ref SettingsEnabled_TilesSwayInWind);
         configuration.Get("SettingsEnabled_AutoReuseAllItems", ref SettingsEnabled_AutoReuseAllItems);
         int currentValue9 = (int)DoorOpeningHelper.PreferenceSettings;
         configuration.Get("DoorAutoOpeningMode", ref currentValue9);
         DoorOpeningHelper.PreferenceSettings = (DoorOpeningHelper.DoorAutoOpeningPreference)currentValue9;
         int currentValue10 = (int)Player.Settings.HoverControl;
         configuration.Get("HoverControlMode", ref currentValue10);
         Player.Settings.HoverControl = (Player.Settings.HoverControlMode)currentValue10;
         if (currentValue <= 147)
         {
             terrariasFixedTiming = !terrariasFixedTiming;
         }
         if (currentValue <= 162)
         {
             bool currentValue11 = false;
             uint currentValue12 = 0u;
             configuration.Get("ThickMouseEdges", ref currentValue11);
             if (currentValue11)
             {
                 configuration.Get("ThickMouseEdgesPackedColor", ref currentValue12);
                 MouseBorderColor.PackedValue = currentValue12;
                 mouseColor.R = configuration.Get("MouseColorR", mouseColor.R);
                 mouseColor.G = configuration.Get("MouseColorG", mouseColor.G);
                 mouseColor.B = configuration.Get("MouseColorB", mouseColor.B);
             }
         }
         if (currentValue <= 162)
         {
             configuration.Get("KeyUp", ref cUp);
             configuration.Get("KeyDown", ref cDown);
             configuration.Get("KeyLeft", ref cLeft);
             configuration.Get("KeyRight", ref cRight);
             configuration.Get("KeyJump", ref cJump);
             configuration.Get("KeyThrowItem", ref cThrowItem);
             configuration.Get("KeyInventory", ref cInv);
             configuration.Get("KeyQuickHeal", ref cHeal);
             configuration.Get("KeyQuickMana", ref cMana);
             configuration.Get("KeyQuickBuff", ref cBuff);
             configuration.Get("KeyUseHook", ref cHook);
             configuration.Get("KeyAutoSelect", ref cTorch);
             configuration.Get("KeySmartCursor", ref cSmart);
             configuration.Get("KeyMount", ref cMount);
             configuration.Get("KeyMapStyle", ref cMapStyle);
             configuration.Get("KeyFullscreenMap", ref cMapFull);
             configuration.Get("KeyMapZoomIn", ref cMapZoomIn);
             configuration.Get("KeyMapZoomOut", ref cMapZoomOut);
             configuration.Get("KeyMapAlphaUp", ref cMapAlphaUp);
             configuration.Get("KeyMapAlphaDown", ref cMapAlphaDown);
             PlayerInput.CurrentProfile.InputModes[InputMode.Keyboard].KeyStatus["Up"] = new List<string> { cUp };
             PlayerInput.CurrentProfile.InputModes[InputMode.Keyboard].KeyStatus["Down"] = new List<string> { cDown };
             PlayerInput.CurrentProfile.InputModes[InputMode.Keyboard].KeyStatus["Left"] = new List<string> { cLeft };
             PlayerInput.CurrentProfile.InputModes[InputMode.Keyboard].KeyStatus["Right"] = new List<string> { cRight };
             PlayerInput.CurrentProfile.InputModes[InputMode.Keyboard].KeyStatus["Jump"] = new List<string> { cJump };
             PlayerInput.CurrentProfile.InputModes[InputMode.Keyboard].KeyStatus["Throw"] = new List<string> { cThrowItem };
             PlayerInput.CurrentProfile.InputModes[InputMode.Keyboard].KeyStatus["Inventory"] = new List<string> { cInv };
             PlayerInput.CurrentProfile.InputModes[InputMode.Keyboard].KeyStatus["QuickHeal"] = new List<string> { cHeal };
             PlayerInput.CurrentProfile.InputModes[InputMode.Keyboard].KeyStatus["QuickMana"] = new List<string> { cMana };
             PlayerInput.CurrentProfile.InputModes[InputMode.Keyboard].KeyStatus["QuickBuff"] = new List<string> { cBuff };
             PlayerInput.CurrentProfile.InputModes[InputMode.Keyboard].KeyStatus["Grapple"] = new List<string> { cHook };
             PlayerInput.CurrentProfile.InputModes[InputMode.Keyboard].KeyStatus["SmartSelect"] = new List<string> { cTorch };
             PlayerInput.CurrentProfile.InputModes[InputMode.Keyboard].KeyStatus["SmartCursor"] = new List<string> { cSmart };
             PlayerInput.CurrentProfile.InputModes[InputMode.Keyboard].KeyStatus["QuickMount"] = new List<string> { cMount };
             PlayerInput.CurrentProfile.InputModes[InputMode.Keyboard].KeyStatus["MapStyle"] = new List<string> { cMapStyle };
             PlayerInput.CurrentProfile.InputModes[InputMode.Keyboard].KeyStatus["MapFull"] = new List<string> { cMapFull };
             PlayerInput.CurrentProfile.InputModes[InputMode.Keyboard].KeyStatus["MapZoomIn"] = new List<string> { cMapZoomIn };
             PlayerInput.CurrentProfile.InputModes[InputMode.Keyboard].KeyStatus["MapZoomOut"] = new List<string> { cMapZoomOut };
             PlayerInput.CurrentProfile.InputModes[InputMode.Keyboard].KeyStatus["MapAlphaUp"] = new List<string> { cMapAlphaUp };
             PlayerInput.CurrentProfile.InputModes[InputMode.Keyboard].KeyStatus["MapAlphaDown"] = new List<string> { cMapAlphaDown };
         }
         PlayerInput.Load();
         if (currentValue < 165)
         {
             try
             {
                 PlayerInput.ManageVersion_1_3();
             }
             catch (Exception)
             {
             }
         }
         mouseColorSlider.SetHSL(mouseColor);
         mouseBorderColorSlider.SetHSL(MouseBorderColor);
         mouseBorderColorSlider.Alpha = (float)(int)MouseBorderColor.A / 255f;
         if (currentValue != 279)
         {
             SaveSettings();
         }
         IsInTheMiddleOfLoadingSettings = false;
     }
References _flashNotificationType, _needsLanguageSelect, _windowMover, AllowUnfocusedInputOnGamepad, ColorSlidersSet.Alpha, ambientVolume, autoPause, autoSave, BackgroundEnabled, bgScroll, caveParallax, cBuff, cDown, cFavoriteKey, cHeal, cHook, cInv, cJump, cLeft, clientUUID, cMana, cMapAlphaDown, cMapAlphaUp, cMapFull, cMapStyle, cMapZoomIn, cMapZoomOut, cMount, Configuration, Preferences.Contains(), cRight, cSmart, cSmartCursorModeIsToggleAndNotHold, cThrowItem, cTorch, cUp, PlayerInput.CurrentProfile, dedServ, ChildSafety.Disabled, DisableIntenseVisualEffects, ItemSlot.Options.DisableLeftShiftTrashCan, ItemSlot.Options.DisableQuickTrash, FavoriteKey, FrameSkipMode, GamepadDisableInstructionsDisplay, GameZoomTarget, Preferences.GetAllKeys(), IWindowService.GetScaling(), graphics, HidePassword, ItemSlot.Options.HighlightNewItems, Player.Settings.HoverControl, InitialMapScale, PlayerInputProfile.InputModes, LanguageManager.Instance, instance, invasionProgressMode, InvisibleCursorForGamepad, IsInTheMiddleOfLoadingSettings, Platform.IsWindows, LastLoadedResolution, PlayerInput.Load(), Preferences.Load(), PlayerInput.ManageVersion_1_3(), mapEnabled, MapScale, Lighting.Mode, MouseBorderColor, mouseBorderColorSlider, mouseColor, mouseColorSlider, MouseShowBuildingGrid, multiplayerNPCSmoothingRange, musicVolume, newDefaultUIScale, OpenLegacySettings(), PendingBorderlessState, placementPreview, DoorOpeningHelper.PreferenceSettings, qaStyle, ReversedUpDownArmorSetBonuses, SavePath, SaveSettings(), screenBorderless, screenBorderlessPendingResizes, screenMaximized, SetBorderlessFormStyle(), SetDisplayMode(), ColorSlidersSet.SetHSL(), LanguageManager.SetLanguage(), SettingBlockGamepadsEntirely, SettingDontScaleMainMenuUp, SettingsEnabled_AutoReuseAllItems, SettingsEnabled_MinersWobble, SettingsEnabled_OpaqueBoxBehindTooltips, SettingsEnabled_TilesSwayInWind, SettingsUnlock_WorldEvil, SetTitle(), shouldSetDefaultUIScale, showItemText, SkipAssemblyLoad, Player.SmartCursorSettings.SmartAxeAfterPickaxe, Player.SmartCursorSettings.SmartBlocksEnabled, Player.SmartCursorSettings.SmartCursorHoldCanReleaseMidUse, soundVolume, startFullscreen, Support4K, teamNamePlateDistance, terrariasFixedTiming, TOWMusicUnlocked, WindowStateController.TryMovingToScreen(), TryPickingDefaultUIScale(), UIScale, UseExperimentalFeatures, UseHeatDistortion, LockOnHelper.UseMode, UseStormEffects, WaveQuality, Game.Window, and WorldRollingBackupsCountToKeep.
Referenced by ClientInitialize().