Terraria: Main.PreDrawMenu
PreDrawMenu()
void Main.PreDrawMenu (out Microsoft.Xna.Framework.Point screenSizeCache, out Microsoft.Xna.Framework.Point screenSizeCacheAfterScaling) inline private
     {
         float uiScaleWanted = _uiScaleWanted;
         float num = (float)screenHeight / 900f;
         if (num < 1f)
         {
             num = 1f;
         }
         if (SettingDontScaleMainMenuUp)
         {
             num = 1f;
         }
         screenSizeCache = ScreenSize;
         UIScale = num;
         PlayerInput.SetZoom_UI();
         screenSizeCacheAfterScaling = ScreenSize;
         if (_needsMenuUIRecalculation)
         {
             _needsMenuUIRecalculation = false;
             MenuUI.Recalculate();
         }
         _uiScaleWanted = uiScaleWanted;
     }
References _needsMenuUIRecalculation, _uiScaleWanted, MenuUI, UserInterface.Recalculate(), screenHeight, ScreenSize, SettingDontScaleMainMenuUp, PlayerInput.SetZoom_UI(), and UIScale.
Referenced by DoDraw().