Terraria: Main.DrawNPCDirect_Faeling
DrawNPCDirect_Faeling()
static void Main.DrawNPCDirect_Faeling (SpriteBatch mySpriteBatch, NPC rCurrentNPC, ref Vector2 screenPos, int typeCache, ref Microsoft.Xna.Framework.Color npcColor, ref Vector2 halfSize, SpriteEffects npcSpriteEffect) inline static private
     {
         Texture2D value = TextureAssets.Npc[typeCache].Value;
         Vector2 vector = rCurrentNPC.Center - screenPos;
         int num = 5;
         int horizontalFrames = 4;
         float num2 = ((float)rCurrentNPC.whoAmI * 0.11f + (float)timeForVisualEffects / 360f) % 1f;
         Microsoft.Xna.Framework.Color color = hslToRgb(num2, 1f, 0.65f);
         color.A /= 2;
         float rotation = rCurrentNPC.rotation;
         Microsoft.Xna.Framework.Rectangle rectangle = value.Frame(horizontalFrames, num, 0, rCurrentNPC.frame.Y);
         Vector2 origin = rectangle.Size() / 2f;
         float scale = rCurrentNPC.scale;
         Microsoft.Xna.Framework.Rectangle value2 = value.Frame(horizontalFrames, num, 2);
         Microsoft.Xna.Framework.Color color2 = new Microsoft.Xna.Framework.Color(255, 255, 255, 0) * 1f;
         int num3 = rCurrentNPC.oldPos.Length;
         int num4 = num3 - 1 - 5;
         int num5 = 5;
         int num6 = 3;
         float num7 = 32f;
         float num8 = 16f;
         float fromMax = new Vector2(num7, num8).Length();
         float num9 = Utils.Remap(Vector2.Distance(rCurrentNPC.oldPos[num4], rCurrentNPC.position), 0f, fromMax, 0f, 100f);
         num9 = (int)num9 / 5;
         num9 *= 5f;
         num9 /= 100f;
         num8 *= num9;
         num7 *= num9;
         float num10 = 9f;
         float num11 = 0.5f;
         float num12 = (float)Math.PI;
         for (int num13 = num4; num13 >= num5; num13 -= num6)
         {
             Vector2 vector2 = rCurrentNPC.oldPos[num13] - rCurrentNPC.position;
             float num14 = Utils.Remap(num13, 0f, num3, 1f, 0f);
             float num15 = 1f - num14;
             Vector2 spinningpoint = new Vector2((float)Math.Sin((double)((float)rCurrentNPC.whoAmI / 17f) + timeForVisualEffects / (double)num10 + (double)(num14 * 2f * ((float)Math.PI * 2f))) * num8, 0f - num7) * num15;
             vector2 += spinningpoint.RotatedBy(num12);
             Microsoft.Xna.Framework.Color color3 = hslToRgb((num2 + num15 * num11) % 1f, 1f, 0.5f);
             color3.A = 0;
             mySpriteBatch.Draw(value, vector + vector2, value2, color3 * num14 * 0.16f, rotation, origin, scale * Utils.Remap(num14 * num14, 0f, 1f, 0f, 2.5f), npcSpriteEffect, 0f);
         }
         mySpriteBatch.Draw(value, vector, value2, color2, rotation, origin, scale, npcSpriteEffect, 0f);
         Microsoft.Xna.Framework.Rectangle value3 = value.Frame(horizontalFrames, num, 1, rCurrentNPC.frame.Y);
         Microsoft.Xna.Framework.Color white = Microsoft.Xna.Framework.Color.White;
         white.A /= 2;
         mySpriteBatch.Draw(value, vector, value3, white, rotation, origin, scale, npcSpriteEffect, 0f);
         mySpriteBatch.Draw(value, vector, rectangle, color, rotation, origin, scale, npcSpriteEffect, 0f);
         float num16 = MathHelper.Clamp((float)Math.Sin(timeForVisualEffects / 60.0) * 0.3f + 0.3f, 0f, 1f);
         float num17 = 0.8f + (float)Math.Sin(timeForVisualEffects / 15.0 * 6.2831854820251465) * 0.3f;
         Microsoft.Xna.Framework.Rectangle value4 = value.Frame(horizontalFrames, num, 3, rCurrentNPC.whoAmI % num);
         Microsoft.Xna.Framework.Color color4 = Microsoft.Xna.Framework.Color.Lerp(color, new Microsoft.Xna.Framework.Color(255, 255, 255, 0), 0.5f) * num16;
         mySpriteBatch.Draw(value, vector, value4, color4, rotation, origin, scale * num17, SpriteEffects.None, 0f);
         Microsoft.Xna.Framework.Rectangle value5 = value.Frame(horizontalFrames, num, 3, 1);
         Microsoft.Xna.Framework.Color color5 = Microsoft.Xna.Framework.Color.Lerp(color, new Microsoft.Xna.Framework.Color(255, 255, 255, 0), 0.5f) * num16;
         mySpriteBatch.Draw(value, vector, value5, color5, rotation, origin, scale * num17, SpriteEffects.None, 0f);
     }
References Entity.Center, NPC.frame, hslToRgb(), TextureAssets.Npc, NPC.oldPos, Entity.position, Utils.Remap(), NPC.rotation, NPC.scale, timeForVisualEffects, Asset< T >.Value, and Entity.whoAmI.
Referenced by DrawNPCDirect().