Terraria: Main.GetBackgroundRect
GetBackgroundRect()
Microsoft.Xna.Framework.? Rectangle Main.GetBackgroundRect (int backgroundTextureIndex) inline private
     {
         int num = 0;
         Microsoft.Xna.Framework.Rectangle rectangle = new Microsoft.Xna.Framework.Rectangle(0, 0, 1, 1);
         switch (backgroundTextureIndex)
         {
         case 235:
             num = (int)(GetBackgroundCounter() / 20) % 4;
             rectangle = TextureAssets.Background[backgroundTextureIndex].Frame(2, 2, num % 2, num / 2);
             rectangle.Inflate(0, -2);
             return rectangle;
         case 219:
         case 220:
         case 221:
         case 271:
         case 272:
         case 273:
             num = (int)(GetBackgroundCounter() / 15) % 4;
             rectangle = TextureAssets.Background[backgroundTextureIndex].Frame(2, 2, num % 2, num / 2);
             rectangle.Inflate(0, -2);
             return rectangle;
         case 281:
             num = (int)(GetBackgroundCounter() / 5) % 4;
             rectangle = TextureAssets.Background[backgroundTextureIndex].Frame(2, 2, num % 2, num / 2);
             rectangle.Inflate(0, -2);
             return rectangle;
         default:
             return null;
         }
     }
References TextureAssets.Background, and GetBackgroundCounter().
Referenced by DrawSurfaceBG_DrawBackMountainsLayer(), DrawSurfaceBG_Forest(), DrawSurfaceBG_Hallow(), DrawSurfaceBG_Jungle(), and DrawSurfaceBG_Mushroom().