Terraria: Main.DrawInterface_34_PlayerChat
DrawInterface_34_PlayerChat()
void Main.DrawInterface_34_PlayerChat () inline private
     {
         if (ignoreErrors)
         {
             try
             {
                 DrawPlayerChat();
                 return;
             }
             catch (Exception e)
             {
                 TimeLogger.DrawException(e);
                 return;
             }
         }
         DrawPlayerChat();
     }
References TimeLogger.DrawException(), DrawPlayerChat(), and ignoreErrors.
Referenced by SetupDrawInterfaceLayers().