Terraria: Main.DrawRain
DrawRain()
void Main.DrawRain () inline protected
     {
         bool flag = base.IsActive || netMode == 1;
         Microsoft.Xna.Framework.Rectangle value = new Microsoft.Xna.Framework.Rectangle(0, 0, 2, 40);
         Texture2D value2 = TextureAssets.Rain.Value;
         Vector2 zero = Vector2.Zero;
         for (int i = 0; i < maxRain; i++)
         {
             Rain rain = Main.rain[i];
             if (rain.active)
             {
                 value.X = rain.type * 4;
                 Microsoft.Xna.Framework.Color color = Lighting.GetColor((int)(rain.position.X + 4f) >> 4, (int)(rain.position.Y + 4f) >> 4) * 0.85f;
                 if (shimmerAlpha > 0f)
                 {
                     color *= 1f - shimmerAlpha;
                 }
                 spriteBatch.Draw(value2, rain.position - screenPosition, value, color, rain.rotation, zero, rain.scale, SpriteEffects.None, 0f);
                 if (flag)
                 {
                     rain.Update();
                 }
             }
         }
         TimeLogger.DetailedDrawTime(23);
     }
References Rain.active, TimeLogger.DetailedDrawTime(), Lighting.GetColor(), maxRain, netMode, Rain.position, TextureAssets.Rain, rain, Rain.rotation, Rain.scale, screenPosition, shimmerAlpha, spriteBatch, Rain.type, Rain.Update(), and Asset< T >.Value.
Referenced by DoDraw(), and DrawCapture().