Terraria: Main.UpdateClient
UpdateClient()
static void Main.UpdateClient () inline static private
     {
         if (myPlayer == 255)
         {
             Netplay.Disconnect = true;
         }
         netPlayCounter++;
         if (netPlayCounter > 3600)
         {
             netPlayCounter = 0;
         }
         if (netPlayCounter % 420 == 0)
         {
             NetMessage.SendData(13, -1, -1, null, myPlayer);
         }
         if (netPlayCounter % 900 == 0)
         {
             NetMessage.SendData(36, -1, -1, null, myPlayer);
             NetMessage.SendData(16, -1, -1, null, myPlayer);
             NetMessage.SendData(40, -1, -1, null, myPlayer);
         }
         if (Netplay.Connection.IsActive)
         {
             Netplay.Connection.TimeOutTimer++;
             if (!stopTimeOuts && Netplay.Connection.TimeOutTimer > 7200)
             {
                 statusText = Lang.inter[43].Value;
                 Netplay.Disconnect = true;
             }
         }
         for (int i = 0; i < 400; i++)
         {
             if (item[i].active && item[i].playerIndexTheItemIsReservedFor == myPlayer)
             {
                 item[i].FindOwner(i);
             }
         }
     }
References Netplay.Connection, Netplay.Disconnect, Item.FindOwner(), Lang.inter, RemoteServer.IsActive, item, myPlayer, netPlayCounter, NetMessage.SendData(), statusText, stopTimeOuts, RemoteServer.TimeOutTimer, and LocalizedText.Value.
Referenced by DoUpdateInWorld().