Terraria: Main.DrawMapIcons_LastGolfballHit
DrawMapIcons_LastGolfballHit()
void Main.DrawMapIcons_LastGolfballHit (SpriteBatch spriteBatch, Vector2 mapTopLeft, Vector2 mapX2Y2AndOff, Microsoft.Xna.Framework.Rectangle? mapRect, float mapScale, float drawScale, ref string mouseTextString) inline private
     {
         Projectile lastHitBall = LocalGolfState.GetLastHitBall();
         if (lastHitBall == null)
         {
             return;
         }
         Vector2 vec = lastHitBall.Center / 16f - mapTopLeft;
         vec *= mapScale;
         vec += mapX2Y2AndOff;
         vec = vec.Floor();
         if (!mapRect.HasValue || mapRect.Value.Contains(vec.ToPoint()))
         {
             Texture2D value = TextureAssets.Extra[176].Value;
             Microsoft.Xna.Framework.Rectangle rectangle = value.Frame();
             spriteBatch.Draw(value, vec, rectangle, Microsoft.Xna.Framework.Color.White, 0f, rectangle.Size() / 2f, drawScale, SpriteEffects.None, 0f);
             Microsoft.Xna.Framework.Rectangle rectangle2 = Utils.CenteredRectangle(vec, rectangle.Size() * drawScale);
             LoadProjectile(lastHitBall.type);
             value = TextureAssets.Projectile[lastHitBall.type].Value;
             rectangle = value.Frame();
             spriteBatch.Draw(value, vec, rectangle, Microsoft.Xna.Framework.Color.White, 0f, rectangle.Size() / 2f, drawScale, SpriteEffects.None, 0f);
             if (rectangle2.Contains(MouseScreen.ToPoint()))
             {
                 mouseTextString = lastHitBall.Name;
                 _ = MouseScreen + new Vector2(-28f) + new Vector2(4f, 0f);
             }
         }
     }
References Entity.Center, Utils.CenteredRectangle(), TextureAssets.Extra, GolfState.GetLastHitBall(), LoadProjectile(), LocalGolfState, MouseScreen, Projectile.Name, TextureAssets.Projectile, spriteBatch, Projectile.type, and Asset< T >.Value.
Referenced by DrawMiscMapIcons().