Terraria: Main.DrawInterface_29_SettingsButton
DrawInterface_29_SettingsButton()
static void Main.DrawInterface_29_SettingsButton () inline static
     {
         _settingsButtonIsPushedToSide = false;
         if (playerInventory || ingameOptionsWindow || player[myPlayer].ghost || player[myPlayer].dead)
         {
             string value = Lang.inter[62].Value;
             string textSizeMatcher = "Settings";
             int num = screenWidth - 110;
             int num2 = screenHeight - 20;
             int num3 = 620;
             int num4 = 870;
             int amountOfExtraAccessorySlotsToShow = player[myPlayer].GetAmountOfExtraAccessorySlotsToShow();
             if (amountOfExtraAccessorySlotsToShow > 1)
             {
                 int num5 = (int)(56f * inventoryScale * (float)(amountOfExtraAccessorySlotsToShow - 1));
                 num3 += num5;
                 num4 += num5;
             }
             if (amountOfExtraAccessorySlotsToShow >= 1 && (screenHeight < num3 || (screenHeight < num4 && mapStyle == 1)))
             {
                 num -= 140;
                 num2 -= PlayerInput.SettingsForUI.PushEquipmentAreaUp.ToInt() * 30;
                 _settingsButtonIsPushedToSide = true;
             }
             Action clickAction = IngameOptions.Open;
             if (ingameOptionsWindow)
             {
                 clickAction = IngameOptions.Close;
             }
             DrawSettingButton(ref mouseExit, ref exitScale, num, num2, value, textSizeMatcher, clickAction);
         }
     }
References _settingsButtonIsPushedToSide, IngameOptions.Close(), DrawSettingButton(), exitScale, Player.GetAmountOfExtraAccessorySlotsToShow(), ingameOptionsWindow, Lang.inter, inventoryScale, mapStyle, mouseExit, myPlayer, IngameOptions.Open(), player, playerInventory, PlayerInput.SettingsForUI.PushEquipmentAreaUp, screenHeight, screenWidth, and LocalizedText.Value.
Referenced by SetupDrawInterfaceLayers().