Terraria: Main.DrawNPCDirect_Deerclops
DrawNPCDirect_Deerclops()
static void Main.DrawNPCDirect_Deerclops (SpriteBatch mySpriteBatch, NPC rCurrentNPC, ref Vector2 screenPos, int typeCache, ref Microsoft.Xna.Framework.Color npcColor, ref Vector2 halfSize, SpriteEffects npcSpriteEffect) inline static private
     {
         Texture2D value = TextureAssets.Npc[typeCache].Value;
         Vector2 vector = rCurrentNPC.Bottom - screenPos;
         Microsoft.Xna.Framework.Rectangle rectangle = value.Frame(5, 5, rCurrentNPC.frame.Y / 5, rCurrentNPC.frame.Y % 5, 2, 2);
         Vector2 origin = rectangle.Size() * new Vector2(0.5f, 1f);
         origin.Y -= 4f;
         int num = 106;
         if (rCurrentNPC.spriteDirection == 1)
         {
             origin.X = num;
         }
         else
         {
             origin.X = rectangle.Width - num;
         }
         Microsoft.Xna.Framework.Color value2 = Microsoft.Xna.Framework.Color.White;
         float amount = 0f;
         float amount2 = 0f;
         int num2 = 0;
         float num3 = 0f;
         float num4 = 0f;
         float num5 = 10f;
         Microsoft.Xna.Framework.Color color = npcColor;
         if (rCurrentNPC.localAI[3] > 0f)
         {
             float num6 = rCurrentNPC.localAI[3] / 36f;
             num2 = 2;
             num3 = num6 * num6;
             num4 = 20f;
             value2 = new Microsoft.Xna.Framework.Color(80, 0, 0, 255) * 0.5f;
             amount2 = 1f;
             color = Microsoft.Xna.Framework.Color.Lerp(Microsoft.Xna.Framework.Color.Transparent, color, 1f - num6 * num6);
         }
         for (int i = 0; i < num2; i++)
         {
             Microsoft.Xna.Framework.Color value3 = npcColor;
             value3 = Microsoft.Xna.Framework.Color.Lerp(value3, value2, amount);
             value3 = rCurrentNPC.GetAlpha(value3);
             value3 = Microsoft.Xna.Framework.Color.Lerp(value3, value2, amount2);
             value3 *= 1f - num3 * 0.5f;
             Vector2 vector2 = vector;
             mySpriteBatch.Draw(value, vector2 + new Vector2(0f, 1f).RotatedBy((float)i * ((float)Math.PI * 2f) / (float)num2 + GlobalTimeWrappedHourly * num5) * num3 * num4, rectangle, value3, rCurrentNPC.rotation, origin, rCurrentNPC.scale, npcSpriteEffect ^ SpriteEffects.FlipHorizontally, 0f);
         }
         Microsoft.Xna.Framework.Color color2 = rCurrentNPC.GetAlpha(color);
         Microsoft.Xna.Framework.Color value4 = new Microsoft.Xna.Framework.Color(50, 0, 160);
         float num7 = 0f;
         if (rCurrentNPC.localAI[3] > 0f)
         {
             float amount3 = Utils.Remap(rCurrentNPC.localAI[3], 0f, 20f, 0f, 1f);
             color2 = Microsoft.Xna.Framework.Color.Lerp(color2, value4, amount3);
         }
         if (rCurrentNPC.ai[0] == 7f || rCurrentNPC.ai[0] == 8f)
         {
             num7 = Utils.Remap(rCurrentNPC.ai[1], 20f, 60f, 0f, 2f);
             if (num7 > 1f)
             {
                 num7 = 2f - num7;
             }
             color2 = Microsoft.Xna.Framework.Color.Lerp(color2, value4, num7);
             color2 *= 1f - num7;
             float num8 = 5f;
             for (int j = 0; (float)j < num8; j++)
             {
                 Vector2 vector3 = vector;
                 float num9 = num7 * num7;
                 float num10 = 80f * num9;
                 float num11 = 80f * num9 + (float)(30 * j) * num9;
                 Vector2 vector4 = Vector2.UnitX.RotatedBy((float)j * ((float)Math.PI * 2f) / num8 + GlobalTimeWrappedHourly * 6f) * num10;
                 Vector2 vector5 = Vector2.UnitX.RotatedBy((float)j * ((float)Math.PI * 2f) / num8 + GlobalTimeWrappedHourly * 3f * ((float)j * 0.5f)) * num11;
                 mySpriteBatch.Draw(value, vector3 + vector4 + vector5, rectangle, color2 * 0.5f, rCurrentNPC.rotation, origin, rCurrentNPC.scale, npcSpriteEffect ^ SpriteEffects.FlipHorizontally, 0f);
             }
         }
         mySpriteBatch.Draw(value, vector, rectangle, color2, rCurrentNPC.rotation, origin, rCurrentNPC.scale, npcSpriteEffect ^ SpriteEffects.FlipHorizontally, 0f);
         if (rCurrentNPC.localAI[3] > 0f)
         {
             Texture2D value5 = TextureAssets.Extra[245].Value;
             float num12 = Utils.Remap(rCurrentNPC.localAI[3], 0f, 20f, 0f, 1f);
             Microsoft.Xna.Framework.Color color3 = new Microsoft.Xna.Framework.Color(255, 30, 30, 66) * rCurrentNPC.Opacity * num12 * 0.25f * (1f - num7);
             for (int k = 0; k < num2; k++)
             {
                 Vector2 vector6 = vector;
                 mySpriteBatch.Draw(value5, vector6 + new Vector2(0f, 1f).RotatedBy((float)k * ((float)Math.PI * 2f) / (float)num2 + GlobalTimeWrappedHourly * num5) * num3 * 4f, rectangle, color3, rCurrentNPC.rotation, origin, rCurrentNPC.scale, npcSpriteEffect ^ SpriteEffects.FlipHorizontally, 0f);
             }
         }
     }
References NPC.ai, Entity.Bottom, TextureAssets.Extra, NPC.frame, NPC.GetAlpha(), GlobalTimeWrappedHourly, NPC.localAI, TextureAssets.Npc, NPC.Opacity, Utils.Remap(), NPC.rotation, NPC.scale, NPC.spriteDirection, and Asset< T >.Value.
Referenced by DrawNPCDirect().