Terraria: Main.Update
Update()
override void Main.Update (GameTime gameTime) inline protected virtual
Reimplemented from Game.
     {
         if (!IsEnginePreloaded)
         {
             IsEnginePreloaded = true;
             if (Main.OnEnginePreload != null)
             {
                 Main.OnEnginePreload();
             }
         }
         if (!_isDrawingOrUpdating)
         {
             _isDrawingOrUpdating = true;
             DoUpdate(ref gameTime);
             CinematicManager.Instance.Update(gameTime);
             if (netMode == 2)
             {
                 for (int i = 0; i < 256; i++)
                 {
                     if (Netplay.Clients[i].Socket != null)
                     {
                         Netplay.Clients[i].Socket.SendQueuedPackets();
                     }
                 }
             }
             else if (netMode == 1)
             {
                 Netplay.Connection.Socket.SendQueuedPackets();
             }
             _isDrawingOrUpdating = false;
         }
         base.Update(gameTime);
         ConsumeAllMainThreadActions();
         if (GameAskedToQuit)
         {
             QuitGame();
         }
     }
References _isDrawingOrUpdating, Netplay.Clients, Netplay.Connection, ConsumeAllMainThreadActions(), DoUpdate(), GameAskedToQuit, CinematicManager.Instance, IsEnginePreloaded, netMode, OnEnginePreload, QuitGame(), ISocket.SendQueuedPackets(), RemoteClient.Socket, RemoteServer.Socket, and CinematicManager.Update().
Referenced by DedServ().