Terraria: Main.NotifyOfEvent
NotifyOfEvent()
static void Main.NotifyOfEvent (GameNotificationType type) inline static
     {
         if (!dedServ && !instance.IsActive && _flashNotificationType.HasFlag(type))
         {
             QueueMainThreadAction(delegate
             {
                 Platform.Get<IWindowService>().StartFlashingIcon(instance.Window);
             });
         }
     }
References _flashNotificationType, dedServ, instance, Game.IsActive, QueueMainThreadAction(), and Game.Window.
Referenced by Player.Hurt(), Player.KillMe(), and Player.Spawn().