Terraria: Main.DrawPrettyStarSparkle
DrawPrettyStarSparkle()
static void Main.DrawPrettyStarSparkle (float opacity, SpriteEffects dir, Vector2 drawpos, Microsoft.Xna.Framework.Color drawColor, Microsoft.Xna.Framework.Color shineColor, float flareCounter, float fadeInStart, float fadeInEnd, float fadeOutStart, float fadeOutEnd, float rotation, Vector2 scale, Vector2 fatness) inline static private
     {
         Texture2D value = TextureAssets.Extra[98].Value;
         Microsoft.Xna.Framework.Color color = shineColor * opacity * 0.5f;
         color.A = 0;
         Vector2 origin = value.Size() / 2f;
         Microsoft.Xna.Framework.Color color2 = drawColor * 0.5f;
         float num = Utils.GetLerpValue(fadeInStart, fadeInEnd, flareCounter, clamped: true) * Utils.GetLerpValue(fadeOutEnd, fadeOutStart, flareCounter, clamped: true);
         Vector2 vector = new Vector2(fatness.X * 0.5f, scale.X) * num;
         Vector2 vector2 = new Vector2(fatness.Y * 0.5f, scale.Y) * num;
         color *= num;
         color2 *= num;
         EntitySpriteDraw(value, drawpos, null, color, (float)Math.PI / 2f + rotation, origin, vector, dir);
         EntitySpriteDraw(value, drawpos, null, color, 0f + rotation, origin, vector2, dir);
         EntitySpriteDraw(value, drawpos, null, color2, (float)Math.PI / 2f + rotation, origin, vector * 0.6f, dir);
         EntitySpriteDraw(value, drawpos, null, color2, 0f + rotation, origin, vector2 * 0.6f, dir);
     }
References EntitySpriteDraw(), TextureAssets.Extra, Utils.GetLerpValue(), and Asset< T >.Value.
Referenced by DrawNPCDirect(), DrawProj_Excalibur(), DrawProj_NightsEdge(), DrawProj_TerraBlade2(), DrawProj_TerraBlade2Shot(), DrawProj_TheHorsemansBlade(), DrawProj_TrueExcalibur(), DrawProj_TrueNightsEdge(), and DrawProjDirect().