Terraria: Main.ReleaseTargets
ReleaseTargets()
void Main.ReleaseTargets () inline protected
     {
         try
         {
             if (!dedServ)
             {
                 offScreenRange = 0;
                 targetSet = false;
                 if (waterTarget != null)
                 {
                     waterTarget.Dispose();
                 }
                 if (backWaterTarget != null)
                 {
                     backWaterTarget.Dispose();
                 }
                 if (blackTarget != null)
                 {
                     blackTarget.Dispose();
                 }
                 if (tileTarget != null)
                 {
                     tileTarget.Dispose();
                 }
                 if (tile2Target != null)
                 {
                     tile2Target.Dispose();
                 }
                 if (wallTarget != null)
                 {
                     wallTarget.Dispose();
                 }
                 if (screenTarget != null)
                 {
                     screenTarget.Dispose();
                 }
                 if (screenTargetSwap != null)
                 {
                     screenTargetSwap.Dispose();
                 }
                 if (backgroundTarget != null)
                 {
                     backgroundTarget.Dispose();
                 }
                 if (Main.OnRenderTargetsReleased != null)
                 {
                     Main.OnRenderTargetsReleased();
                 }
             }
         }
         catch
         {
         }
     }
References backgroundTarget, backWaterTarget, blackTarget, dedServ, offScreenRange, OnRenderTargetsReleased, screenTarget, screenTargetSwap, targetSet, tile2Target, tileTarget, wallTarget, and waterTarget.
Referenced by DoDraw(), InitTargets(), and TrySupporting8K().