Terraria: Main.DrawProj_TheHorsemansBlade
DrawProj_TheHorsemansBlade()
void Main.DrawProj_TheHorsemansBlade (Projectile proj) inline private
     {
         Vector2 vector = proj.Center - screenPosition;
         Asset<Texture2D> val = TextureAssets.Projectile[proj.type];
         Microsoft.Xna.Framework.Rectangle rectangle = val.Frame(1, 4);
         Vector2 origin = rectangle.Size() / 2f;
         float num = proj.scale * 1.1f;
         SpriteEffects effects = ((!(proj.ai[0] >= 0f)) ? SpriteEffects.FlipVertically : SpriteEffects.None);
         float num2 = proj.localAI[0] / proj.ai[1];
         float num3 = Utils.Remap(num2, 0f, 0.6f, 0f, 1f) * Utils.Remap(num2, 0.6f, 1f, 1f, 0f);
         float num4 = 0.975f;
         float fromValue = Lighting.GetColor(proj.Center.ToTileCoordinates()).ToVector3().Length() / (float)Math.Sqrt(3.0);
         fromValue = Utils.Remap(fromValue, 0.2f, 1f, 0f, 1f);
         Microsoft.Xna.Framework.Color color = new Microsoft.Xna.Framework.Color(193, 43, 43);
         spriteBatch.Draw(val.Value, vector, rectangle, color * fromValue * num3, proj.rotation + proj.ai[0] * ((float)Math.PI / 4f) * -1f * (1f - num2), origin, num, effects, 0f);
         Microsoft.Xna.Framework.Color color2 = new Microsoft.Xna.Framework.Color(247, 115, 0);
         Microsoft.Xna.Framework.Color color3 = new Microsoft.Xna.Framework.Color(255, 202, 130);
         Microsoft.Xna.Framework.Color color4 = Microsoft.Xna.Framework.Color.White * num3 * 0.5f;
         color4.A = (byte)((float)(int)color4.A * (1f - fromValue));
         Microsoft.Xna.Framework.Color color5 = color4 * fromValue * 0.5f;
         color5.G = (byte)((float)(int)color5.G * fromValue);
         color5.B = (byte)((float)(int)color5.R * (0.25f + fromValue * 0.75f));
         spriteBatch.Draw(val.Value, vector, rectangle, color5 * 0.15f, proj.rotation + proj.ai[0] * 0.01f, origin, num, effects, 0f);
         spriteBatch.Draw(val.Value, vector, rectangle, color3 * fromValue * num3 * 0.3f, proj.rotation, origin, num, effects, 0f);
         spriteBatch.Draw(val.Value, vector, rectangle, color2 * fromValue * num3 * 0.5f, proj.rotation, origin, num * num4, effects, 0f);
         spriteBatch.Draw(val.Value, vector, val.Frame(1, 4, 0, 3), Microsoft.Xna.Framework.Color.White * 0.6f * num3, proj.rotation + proj.ai[0] * 0.01f, origin, num, effects, 0f);
         spriteBatch.Draw(val.Value, vector, val.Frame(1, 4, 0, 3), Microsoft.Xna.Framework.Color.White * 0.5f * num3, proj.rotation + proj.ai[0] * -0.05f, origin, num * 0.8f, effects, 0f);
         spriteBatch.Draw(val.Value, vector, val.Frame(1, 4, 0, 3), Microsoft.Xna.Framework.Color.White * 0.4f * num3, proj.rotation + proj.ai[0] * -0.1f, origin, num * 0.6f, effects, 0f);
         for (float num5 = 0f; num5 < 8f; num5 += 1f)
         {
             float num6 = proj.rotation + proj.ai[0] * num5 * ((float)Math.PI * -2f) * 0.025f + Utils.Remap(num2, 0f, 1f, 0f, (float)Math.PI / 4f) * proj.ai[0];
             Vector2 drawpos = vector + num6.ToRotationVector2() * ((float)val.Width() * 0.5f - 6f) * num;
             float num7 = num5 / 9f;
             DrawPrettyStarSparkle(proj.Opacity, SpriteEffects.None, drawpos, new Microsoft.Xna.Framework.Color(255, 255, 255, 0) * num3 * num7, color3, num2, 0f, 0.5f, 0.5f, 1f, num6, new Vector2(0f, Utils.Remap(num2, 0f, 1f, 3f, 0f)) * num, Vector2.One * num);
         }
         Vector2 drawpos2 = vector + (proj.rotation + Utils.Remap(num2, 0f, 1f, 0f, (float)Math.PI / 4f) * proj.ai[0]).ToRotationVector2() * ((float)val.Width() * 0.5f - 4f) * num;
         DrawPrettyStarSparkle(proj.Opacity, SpriteEffects.None, drawpos2, new Microsoft.Xna.Framework.Color(255, 255, 255, 0) * num3 * 0.5f, color3, num2, 0f, 0.5f, 0.5f, 1f, (float)Math.PI / 4f, new Vector2(Utils.Remap(num2, 0f, 1f, 4f, 1f)) * num, Vector2.One * num);
     }
References Projectile.ai, Entity.Center, DrawPrettyStarSparkle(), Lighting.GetColor(), Projectile.localAI, Projectile.Opacity, TextureAssets.Projectile, Utils.Remap(), Projectile.rotation, Projectile.scale, screenPosition, spriteBatch, Projectile.type, and Asset< T >.Value.
Referenced by DrawProjDirect().