Terraria: Main.CraftItem
CraftItem()
static void Main.CraftItem (Recipe r) inline static
     {
         int stack = mouseItem.stack;
         mouseItem = r.createItem.Clone();
         mouseItem.stack += stack;
         mouseItem.OnCreated(new RecipeItemCreationContext(r));
         if (stack <= 0)
         {
             mouseItem.Prefix(-1);
         }
         mouseItem.position.X = player[myPlayer].position.X + (float)(player[myPlayer].width / 2) - (float)(mouseItem.width / 2);
         mouseItem.position.Y = player[myPlayer].position.Y + (float)(player[myPlayer].height / 2) - (float)(mouseItem.height / 2);
         PopupText.NewText(PopupTextContext.ItemCraft, mouseItem, r.createItem.stack);
         r.Create();
         if (mouseItem.type > 0 || r.createItem.type > 0)
         {
             SoundEngine.PlaySound(7);
         }
     }
References Item.Clone(), Recipe.Create(), Recipe.createItem, Entity.height, mouseItem, myPlayer, PopupText.NewText(), Item.OnCreated(), player, SoundEngine.PlaySound(), Entity.position, Item.Prefix(), Item.stack, Item.type, and Entity.width.
Referenced by HoverOverCraftingItemButton().