Terraria: Main.RenderWalls
RenderWalls()
void Main.RenderWalls () inline protected
     {
         if (drawToScreen)
         {
             return;
         }
         base.GraphicsDevice.SetRenderTarget(wallTarget);
         base.GraphicsDevice.DepthStencilState = new DepthStencilState
         {
             DepthBufferEnable = true
         };
         base.GraphicsDevice.Clear(Microsoft.Xna.Framework.Color.Transparent);
         spriteBatch.Begin(SpriteSortMode.Deferred, BlendState.AlphaBlend);
         tileBatch.Begin();
         if (ignoreErrors)
         {
             try
             {
                 DrawWalls();
             }
             catch (Exception e)
             {
                 TimeLogger.DrawException(e);
             }
         }
         else
         {
             DrawWalls();
         }
         TimeLogger.DetailedDrawReset();
         tileBatch.End();
         spriteBatch.End();
         TimeLogger.DetailedDrawTime(32);
         base.GraphicsDevice.SetRenderTarget(null);
     }
References TileBatch.Begin(), TimeLogger.DetailedDrawReset(), TimeLogger.DetailedDrawTime(), TimeLogger.DrawException(), drawToScreen, DrawWalls(), TileBatch.End(), ignoreErrors, spriteBatch, tileBatch, and wallTarget.
Referenced by DoDraw().