Terraria: Main.DrawUnderworldBackground
DrawUnderworldBackground()
void Main.DrawUnderworldBackground (bool flat) inline protected
     {
         if (!(screenPosition.Y + (float)screenHeight < (float)(maxTilesY - 220) * 16f))
         {
             Vector2 screenOffset = screenPosition + new Vector2(screenWidth >> 1, screenHeight >> 1);
             float pushUp = (GameViewMatrix.Zoom.Y - 1f) * 0.5f * 200f;
             SkyManager.Instance.ResetDepthTracker();
             for (int num = 4; num >= 0; num--)
             {
                 DrawUnderworldBackgroudLayer(flat, screenOffset, pushUp, num);
             }
             if (!mapFullscreen)
             {
                 SkyManager.Instance.DrawRemainingDepth(spriteBatch);
             }
             DrawSurfaceBG_DrawChangeOverlay(12);
         }
     }
References SkyManager.DrawRemainingDepth(), DrawSurfaceBG_DrawChangeOverlay(), DrawUnderworldBackgroudLayer(), GameViewMatrix, SkyManager.Instance, mapFullscreen, maxTilesY, SkyManager.ResetDepthTracker(), screenHeight, screenPosition, screenWidth, spriteBatch, and SpriteViewMatrix.Zoom.
Referenced by DrawBG(), and DrawCapture().