Terraria: Main.TryDisposingEverything
TryDisposingEverything()
static void Main.TryDisposingEverything () inline static private
     {
         ChromaInitializer.DisableAllDeviceGroups();
         CaptureManager.Instance.Dispose();
         audioSystem.Dispose();
     }
References audioSystem, ChromaInitializer.DisableAllDeviceGroups(), CaptureManager.Dispose(), and CaptureManager.Instance.
Referenced by Main_Exiting().