Terraria: Main.DrawDefenseCounter
DrawDefenseCounter()
static void Main.DrawDefenseCounter (int inventoryX, int inventoryY) inline static private
     {
         Vector2 vector = new Vector2(inventoryX - 10 - 47 - 47 - 14, (float)inventoryY + (float)TextureAssets.InventoryBack.Height() * 0.5f);
         spriteBatch.Draw(TextureAssets.Extra[58].Value, vector, null, Microsoft.Xna.Framework.Color.White, 0f, TextureAssets.Extra[58].Value.Size() / 2f, inventoryScale, SpriteEffects.None, 0f);
         Vector2 vector2 = FontAssets.MouseText.Value.MeasureString(player[myPlayer].statDefense.ToString());
         ChatManager.DrawColorCodedStringWithShadow(spriteBatch, FontAssets.MouseText.Value, player[myPlayer].statDefense.ToString(), vector - vector2 * 0.5f * inventoryScale, Microsoft.Xna.Framework.Color.White, 0f, Vector2.Zero, new Vector2(inventoryScale));
         if (Utils.CenteredRectangle(vector, TextureAssets.Extra[58].Value.Size()).Contains(new Microsoft.Xna.Framework.Point(mouseX, mouseY)) && !PlayerInput.IgnoreMouseInterface)
         {
             player[myPlayer].mouseInterface = true;
             string value = player[myPlayer].statDefense + " " + Lang.inter[10].Value;
             if (!string.IsNullOrEmpty(value))
             {
                 hoverItemName = value;
             }
         }
         UILinkPointNavigator.SetPosition(1557, vector + TextureAssets.Extra[58].Value.Size() * inventoryScale / 4f);
     }
References Utils.CenteredRectangle(), ChatManager.DrawColorCodedStringWithShadow(), TextureAssets.Extra, hoverItemName, PlayerInput.IgnoreMouseInterface, Lang.inter, TextureAssets.InventoryBack, inventoryScale, Player.mouseInterface, FontAssets.MouseText, mouseX, mouseY, myPlayer, player, UILinkPointNavigator.SetPosition(), spriteBatch, Player.statDefense, Asset< T >.Value, and LocalizedText.Value.
Referenced by DrawInventory().