Terraria: Main.DoDraw_UpdateCameraPosition
DoDraw_UpdateCameraPosition()
static void Main.DoDraw_UpdateCameraPosition () inline static private
     {
         Vector3 vector = new Vector3(1f, 1f, 1f);
         Vector3 vector2 = Vector3.One / vector;
         if (gameMenu || netMode == 2)
         {
             return;
         }
         int num = 21;
         if (cameraX != 0f && !Main.player[myPlayer].pulley)
         {
             cameraX = 0f;
         }
         if (cameraX > 0f)
         {
             cameraX -= 1f;
             if (cameraX < 0f)
             {
                 cameraX = 0f;
             }
         }
         if (cameraX < 0f)
         {
             cameraX += 1f;
             if (cameraX > 0f)
             {
                 cameraX = 0f;
             }
         }
         Vector2 value = screenPosition;
         screenPosition.X = Main.player[myPlayer].position.X + (float)Main.player[myPlayer].width * 0.5f - (float)screenWidth * 0.5f * vector2.X + cameraX;
         screenPosition.Y = Main.player[myPlayer].position.Y + (float)Main.player[myPlayer].height - (float)num - (float)screenHeight * 0.5f * vector2.Y + Main.player[myPlayer].gfxOffY;
         Vector2 vector3 = Vector2.Zero;
         float num2 = 0f;
         float num3 = 0f;
         float num4 = 36f;
         bool flag = false;
         Vector2 vector4 = Vector2.Zero;
         if (!Main.player[myPlayer].dead)
         {
             if (DroneCameraTracker.TryTracking(out var cameraPosition))
             {
                 vector3 = cameraPosition - LocalPlayer.Center;
                 if (LocalPlayer.gravDir == -1f)
                 {
                     vector3.Y *= -1f;
                 }
                 vector4 = vector3;
                 vector3 = CurrentPan * 0.87f + vector3 * 0.13f;
                 flag = true;
                 _cameraPanHasBlackTransition = true;
             }
             else if (LocalGolfState != null && (LocalGolfState.ShouldCameraTrackBallLastKnownLocation || LocalGolfState.IsTrackingBall))
             {
                 if (LocalGolfState.IsTrackingBall)
                 {
                     Projectile lastHitBall = LocalGolfState.GetLastHitBall();
                     vector3 = lastHitBall.Center - LocalPlayer.Center;
                     vector4 = vector3;
                     _cameraPanHasBlackTransition = true;
                     if (lastHitBall.velocity.Length() > 20f)
                     {
                         num4 *= 2f;
                     }
                     vector3 = CurrentPan * 0.87f + vector3 * 0.13f;
                     flag = true;
                 }
                 else if (LocalGolfState.ShouldCameraTrackBallLastKnownLocation)
                 {
                     Vector2? lastBallLocation = LocalGolfState.GetLastBallLocation();
                     if (lastBallLocation.HasValue)
                     {
                         vector3 = lastBallLocation.Value - LocalPlayer.Center;
                         vector4 = vector3;
                         _cameraPanHasBlackTransition = true;
                         vector3 = CurrentPan * 0.87f + vector3 * 0.13f;
                         flag = true;
                     }
                 }
             }
             else if ((Main.player[myPlayer].noThrow <= 0 && !Main.player[myPlayer].lastMouseInterface) || !(CurrentPan == Vector2.Zero))
             {
                 if (PlayerInput.UsingGamepad)
                 {
                     Player player = Main.player[myPlayer];
                     if (PlayerInput.GamepadThumbstickRight.Length() != 0f || !SmartCursorIsUsed)
                     {
                         float num5 = -1f;
                         if (player.inventory[player.selectedItem].type == 1254 && player.scope)
{
                             num5 = 0.8f;
                         }
                         else if (player.inventory[player.selectedItem].type == 1254)
{
                             num5 = 2f / 3f;
                         }
                         else if (player.inventory[player.selectedItem].type == 1299)
{
                             num5 = 2f / 3f;
                         }
                         else if (player.scope)
{
                             num5 = 0.5f;
                         }
                         Vector2 vector5 = (MouseScreen - new Vector2(screenWidth, screenHeight) / 2f) / (new Vector2(screenWidth, screenHeight) / 2f);
                         num4 = 48f;
                         if (vector5 != Vector2.Zero && num5 != -1f)
{
                             Vector2 vector6 = new Vector2(screenWidth, screenHeight) * 0.5f * vector5 * num5;
                             vector3.X = vector6.X;
                             vector3.Y = vector6.Y;
                             flag = true;
                         }
                     }
                 }
                 else if (Main.player[myPlayer].inventory[Main.player[myPlayer].selectedItem].type == 1254 && Main.player[myPlayer].scope && mouseRight)
                 {
                     int num6 = mouseX;
                     int num7 = mouseY;
                     if (num6 > screenWidth)
                     {
                         num6 = screenWidth;
                     }
                     if (num6 < 0)
                     {
                         num6 = 0;
                     }
                     if (num7 > screenHeight)
                     {
                         num7 = screenHeight;
                     }
                     if (num7 < 0)
                     {
                         num7 = 0;
                     }
                     vector3.X = (float)(num6 - screenWidth / 2) / 1.25f;
                     vector3.Y = (float)(num7 - screenHeight / 2) / 1.25f;
                     flag = true;
                 }
                 else if (Main.player[myPlayer].inventory[Main.player[myPlayer].selectedItem].type == 1254 && mouseRight)
                 {
                     int num8 = mouseX;
                     int num9 = mouseY;
                     if (num8 > screenWidth)
                     {
                         num8 = screenWidth;
                     }
                     if (num8 < 0)
                     {
                         num8 = 0;
                     }
                     if (num9 > screenHeight)
                     {
                         num9 = screenHeight;
                     }
                     if (num9 < 0)
                     {
                         num9 = 0;
                     }
                     vector3.X = (float)(num8 - screenWidth / 2) / 1.5f;
                     vector3.Y = (float)(num9 - screenHeight / 2) / 1.5f;
                     flag = true;
                 }
                 else if (Main.player[myPlayer].inventory[Main.player[myPlayer].selectedItem].type == 1299 && Main.player[myPlayer].selectedItem != 58)
                 {
                     int num10 = mouseX;
                     int num11 = mouseY;
                     if (num10 > screenWidth)
                     {
                         num10 = screenWidth;
                     }
                     if (num10 < 0)
                     {
                         num10 = 0;
                     }
                     if (num11 > screenHeight)
                     {
                         num11 = screenHeight;
                     }
                     if (num11 < 0)
                     {
                         num11 = 0;
                     }
                     vector3.X = (float)(num10 - screenWidth / 2) / 1.5f;
                     vector3.Y = (float)(num11 - screenHeight / 2) / 1.5f;
                     flag = true;
                 }
                 else if (Main.player[myPlayer].scope && mouseRight)
                 {
                     int num12 = mouseX;
                     int num13 = mouseY;
                     if (num12 > screenWidth)
                     {
                         num12 = screenWidth;
                     }
                     if (num12 < 0)
                     {
                         num12 = 0;
                     }
                     if (num13 > screenHeight)
                     {
                         num13 = screenHeight;
                     }
                     if (num13 < 0)
                     {
                         num13 = 0;
                     }
                     vector3.X = (float)(num12 - screenWidth / 2) / 2f;
                     vector3.Y = (float)(num13 - screenHeight / 2) / 2f;
                     flag = true;
                 }
             }
         }
         if (float.IsNaN(CurrentPan.X))
         {
             CurrentPan.X = 0f;
         }
         if (float.IsNaN(CurrentPan.Y))
         {
             CurrentPan.Y = 0f;
         }
         Vector2 value2 = vector3 - CurrentPan;
         float num14 = value2.Length();
         float amount = 1f;
         if (num3 > num2 + 0.0001f)
         {
             amount = MathHelper.Clamp((num14 - num2) / (num3 - num2), 0f, 1f);
         }
         float value3 = MathHelper.SmoothStep(0f, num14, amount);
         value3 = MathHelper.Clamp(value3, 0f, num4);
         if (CurrentPan == Vector2.Zero && _cameraPanHasBlackTransition && vector4 != Vector2.Zero)
         {
             Vector2 vector7 = vector4 - CurrentPan;
             float num15 = Math.Abs(vector7.X);
             float num16 = Math.Abs(vector7.Y);
             float num17 = vector7.Length();
             if ((num15 >= (float)(screenWidth / 2) || num16 >= (float)(screenHeight / 2)) && num17 >= new Vector2(screenWidth, screenHeight).Length() / 2f + 100f)
             {
                 renderNow = true;
                 CurrentPan = vector4;
                 _cameraPanHasBlackTransition = false;
                 NPC.ResetNetOffsets();
                 BlackFadeIn = 255;
                 if (mapTime < 5)
                 {
                     mapTime = 5;
                 }
                 maxQ = true;
                 Lighting.Clear();
                 instantBGTransitionCounter = 10;
                 LocalPlayer.ForceUpdateBiomes();
             }
         }
         if (vector3 == Vector2.Zero && !flag)
         {
             float num18 = Math.Abs(value2.X);
             float num19 = Math.Abs(value2.Y);
             float num20 = value2.Length();
             if (num18 >= (float)(screenWidth / 2) || num19 >= (float)(screenHeight / 2))
             {
                 renderNow = true;
                 CurrentPan *= 0.9f;
                 if (_cameraPanHasBlackTransition && num20 >= new Vector2(screenWidth, screenHeight).Length() / 2f + 100f)
                 {
                     _cameraPanHasBlackTransition = false;
                     NPC.ResetNetOffsets();
                     BlackFadeIn = 255;
                     if (mapTime < 5)
                     {
                         mapTime = 5;
                     }
                     maxQ = true;
                     Lighting.Clear();
                     CurrentPan = Vector2.Zero;
                     instantBGTransitionCounter = 10;
                     LocalPlayer.ForceUpdateBiomes();
                 }
             }
             else if (value3 > 0.0001f)
             {
                 CurrentPan += Vector2.Normalize(value2) * value3;
             }
         }
         else if (value3 > 0.0001f)
         {
             CurrentPan += Vector2.Normalize(value2) * value3;
         }
         screenPosition.X += CurrentPan.X;
         screenPosition.Y += CurrentPan.Y * Main.player[myPlayer].gravDir;
         if (cameraLerp > 0f)
         {
             if (Vector2.Distance(value, screenPosition) - Main.player[myPlayer].velocity.Length() < 0.25f || (cameraGamePadLerp && !PlayerInput.UsingGamepad))
             {
                 cameraLerp = 0f;
                 cameraGamePadLerp = false;
             }
             else
             {
                 screenPosition = Vector2.Lerp(value, screenPosition, cameraLerp);
             }
         }
         instance.CameraModifiers.ApplyTo(ref screenPosition);
         screenPosition.X = (int)screenPosition.X;
         screenPosition.Y = (int)screenPosition.Y;
         ClampScreenPositionToWorld();
     }
References _cameraPanHasBlackTransition, CameraModifierStack.ApplyTo(), BlackFadeIn, cameraGamePadLerp, cameraLerp, CameraModifiers, cameraX, Entity.Center, ClampScreenPositionToWorld(), Lighting.Clear(), CurrentPan, Player.dead, Player.ForceUpdateBiomes(), gameMenu, PlayerInput.GamepadThumbstickRight, GolfState.GetLastBallLocation(), GolfState.GetLastHitBall(), Player.gfxOffY, Player.gravDir, Entity.height, instance, instantBGTransitionCounter, Player.inventory, GolfState.IsTrackingBall, Player.lastMouseInterface, LocalGolfState, LocalPlayer, mapTime, maxQ, mouseRight, MouseScreen, mouseX, mouseY, myPlayer, netMode, Player.noThrow, player, Entity.position, Player.pulley, renderNow, NPC.ResetNetOffsets(), Player.scope, screenHeight, screenPosition, screenWidth, Player.selectedItem, GolfState.ShouldCameraTrackBallLastKnownLocation, SmartCursorIsUsed, DroneCameraTracker.TryTracking(), Item.type, PlayerInput.UsingGamepad, Entity.velocity, and Entity.width.
Referenced by DoDraw().