Terraria: Main.DoUpdate_F7_ToggleGraphicsDiagnostics
DoUpdate_F7_ToggleGraphicsDiagnostics()
static void Main.DoUpdate_F7_ToggleGraphicsDiagnostics () inline static private
     {
         if (keyState.IsKeyDown(Microsoft.Xna.Framework.Input.Keys.F7) && !drawingPlayerChat && !editSign && !editChest)
         {
             if (drawRelease)
             {
                 SoundEngine.PlaySound(12);
                 if (keyState.IsKeyDown(Microsoft.Xna.Framework.Input.Keys.LeftAlt) || keyState.IsKeyDown(Microsoft.Xna.Framework.Input.Keys.RightAlt))
                 {
                     TimeLogger.Start();
                 }
                 else if (drawDiag)
                 {
                     drawDiag = false;
                 }
                 else
                 {
                     drawDiag = true;
                 }
             }
             drawRelease = false;
         }
         else
         {
             drawRelease = true;
         }
     }
References drawDiag, drawingPlayerChat, drawRelease, editChest, editSign, keyState, SoundEngine.PlaySound(), and TimeLogger.Start().
Referenced by DoUpdate().