Terraria: Main.AnglerQuestSwap
AnglerQuestSwap()
static void Main.AnglerQuestSwap () inline static
     {
         if (netMode == 1)
         {
             return;
         }
         anglerWhoFinishedToday.Clear();
         anglerQuestFinished = false;
         bool flag = NPC.downedBoss1 || NPC.downedBoss2 || NPC.downedBoss3 || hardMode || NPC.downedSlimeKing || NPC.downedQueenBee;
         bool flag2 = true;
         while (flag2)
         {
             flag2 = false;
             anglerQuest = rand.Next(anglerQuestItemNetIDs.Length);
             int num = anglerQuestItemNetIDs[anglerQuest];
             if (num == 2454 && (!hardMode || WorldGen.crimson))
             {
                 flag2 = true;
             }
             if (num == 2457 && WorldGen.crimson)
             {
                 flag2 = true;
             }
             if (num == 2462 && !hardMode)
             {
                 flag2 = true;
             }
             if (num == 2463 && (!hardMode || !WorldGen.crimson))
             {
                 flag2 = true;
             }
             if (num == 2465 && !hardMode)
             {
                 flag2 = true;
             }
             if (num == 2468 && !hardMode)
             {
                 flag2 = true;
             }
             if (num == 2471 && !hardMode)
             {
                 flag2 = true;
             }
             if (num == 2473 && !hardMode)
             {
                 flag2 = true;
             }
             if (num == 2477 && !WorldGen.crimson)
             {
                 flag2 = true;
             }
             if (num == 2480 && !hardMode)
             {
                 flag2 = true;
             }
             if (num == 2483 && !hardMode)
             {
                 flag2 = true;
             }
             if (num == 2484 && !hardMode)
             {
                 flag2 = true;
             }
             if (num == 2485 && WorldGen.crimson)
             {
                 flag2 = true;
             }
             if ((num == 2476 || num == 2453 || num == 2473) && !flag)
             {
                 flag2 = true;
             }
         }
         NetMessage.SendAnglerQuest(-1);
     }
References anglerQuest, anglerQuestFinished, anglerQuestItemNetIDs, anglerWhoFinishedToday, WorldGen.crimson, NPC.downedBoss1, NPC.downedBoss2, NPC.downedBoss3, NPC.downedQueenBee, NPC.downedSlimeKing, hardMode, netMode, UnifiedRandom.Next(), rand, and NetMessage.SendAnglerQuest().
Referenced by UpdateTime_StartDay().