Terraria: Main.LoadHair
LoadHair()
void Main.LoadHair (int i) inline
     {
         //IL_0007: Unknown result type (might be due to invalid IL or missing references)
         if ((int)TextureAssets.PlayerHair[i].State == 0)
         {
             Assets.Request<Texture2D>(TextureAssets.PlayerHair[i].Name, (AssetRequestMode)1);
             Assets.Request<Texture2D>(TextureAssets.PlayerHairAlt[i].Name, (AssetRequestMode)1);
         }
     }
References Assets, Asset< T >.Name, TextureAssets.PlayerHair, TextureAssets.PlayerHairAlt, and Asset< T >.State.
Referenced by PlayerDrawHeadSet.BoringSetup(), PlayerDrawSet.BoringSetup(), and DrawHairWindow().