Terraria: Main.DrawNPCExtras
DrawNPCExtras()
void Main.DrawNPCExtras (NPC n, bool beforeDraw, float addHeight, float addY, Microsoft.Xna.Framework.Color npcColor, Vector2 halfSize, SpriteEffects npcSpriteEffect, Vector2 screenPosition) inline protected
     {
         if (!beforeDraw && n.UsesPartyHat())
         {
             int num = n.frame.Y / n.frame.Height;
             int[] array = NPCID.Sets.TownNPCsFramingGroups[NPCID.Sets.NPCFramingGroup[n.type]];
             if (num >= array.Length)
             {
                 num = 0;
             }
             Texture2D value = TextureAssets.Extra[72].Value;
             int num2 = 0;
             switch (n.GetPartyHatColor())
             {
             case PartyHatColor.Pink:
                 num2 = 16;
                 break;
             case PartyHatColor.Cyan:
                 num2 = 17;
                 break;
             case PartyHatColor.Purple:
                 num2 = 18;
                 break;
             case PartyHatColor.White:
                 num2 = 19;
                 break;
             }
             Microsoft.Xna.Framework.Rectangle rectangle = value.Frame(20, 1, num2 % 20);
             rectangle.Width -= 2;
             rectangle.Height -= 2;
             int num3 = 0;
             int num4 = 0;
             int num5 = n.spriteDirection;
             if (n.type == 663)
             {
                 num3 = 1;
             }
             if (n.type == 637)
             {
                 num3 = 6;
                 switch (num)
                 {
                 case 19:
                 case 22:
                 case 23:
                 case 24:
                 case 25:
                 case 26:
                 case 27:
                     num3 -= 2;
                     break;
                 case 11:
                 case 12:
                 case 13:
                 case 14:
                 case 15:
                     num3 += 2;
                     break;
                 }
             }
             if (n.type == 638)
             {
                 num3 = 12;
             }
             if (n.type == 656)
             {
                 num3 = 6;
                 switch (num)
                 {
                 case 1:
                 case 2:
                 case 3:
                     num3 -= 2;
                     break;
                 case 18:
                 case 19:
                 case 20:
                 case 21:
                 case 22:
                 case 23:
                 case 24:
                 case 25:
                     num3 -= 4;
                     break;
                 case 8:
                     num3 -= 2;
                     break;
                 }
             }
             if (NPCID.Sets.IsTownSlime[n.type])
             {
                 num5 *= -1;
                 switch (n.type)
                 {
                 default:
                     num3 = 1;
                     break;
                 case 670:
                     num3 = -1;
                     break;
                 case 681:
                     num3 = -2;
                     break;
                 case 682:
                     num3 = -1;
                     num4 = 2;
                     break;
                 case 683:
                     num3 = -1;
                     num4 = -2;
                     break;
                 case 684:
                     num3 = -4;
                     break;
                 case 679:
                     break;
                 }
             }
             if (n.IsShimmerVariant)
             {
                 switch (n.type)
                 {
                 case 38:
                     num3 += 2;
                     num4 = -2;
                     break;
                 case 178:
                 case 228:
                     num3 = -4;
                     num4 = -4;
                     break;
                 case 107:
                     num3 = 2;
                     num4 = -6;
                     break;
                 case 54:
                     num4 = -6;
                     break;
                 case 160:
                     num4 = -2;
                     break;
                 case 108:
                 case 124:
                 case 208:
                 case 209:
                 case 227:
                     num4 = -4;
                     break;
                 }
             }
             Vector2 vector = n.Top + new Vector2(-2 * num5, n.gfxOffY);
             vector.X += num3 * num5;
             vector.Y += array[num];
             vector.Y += num4;
             vector.Y += NPCID.Sets.HatOffsetY[n.type];
             int num6 = 0;
             if (n.ai[0] == 5f)
             {
                 num6 = -4;
                 if (n.type == 38)
                 {
                     num6 = -8;
                 }
                 if (n.type == 124)
                 {
                     num6 = -2;
                 }
                 if (n.type == 550)
                 {
                     num6 = -4;
                 }
                 if (n.type == 588)
                 {
                     num6 = -4;
                 }
                 if (n.type == 108 || n.type == 178)
                 {
                     num6 = -6;
                 }
                 if (n.type == 637)
                 {
                     num6 = -12;
                 }
                 if (n.type == 663)
                 {
                     num6 = -8;
                 }
             }
             vector.Y += num6;
             if (n.type == 229 && n.ai[0] == 12f)
             {
                 vector.X -= num5 * 4;
             }
             if (n.type == 550 && n.ai[0] == 5f)
             {
                 vector.X += num5 * 7;
             }
             Vector2 origin = rectangle.Size() - new Vector2(rectangle.Width / 2, 12f);
             int num7 = 0;
             switch (n.type)
             {
             case 550:
                 num7 = -4;
                 break;
             case 588:
                 num7 = 0;
                 break;
             case 227:
                 num7 = -4;
                 break;
             case 228:
                 num7 = -2;
                 break;
             case 17:
             case 18:
             case 19:
             case 20:
             case 22:
             case 124:
             case 229:
             case 353:
             case 633:
             case 637:
             case 638:
             case 656:
             case 670:
             case 678:
             case 679:
             case 680:
             case 681:
             case 682:
             case 683:
             case 684:
                 num7 = -1;
                 break;
             case 37:
             case 38:
             case 54:
             case 107:
             case 108:
             case 160:
             case 207:
             case 209:
                 num7 = -3;
                 break;
             case 178:
             case 208:
             case 369:
                 num7 = 1;
                 break;
             }
             vector.X += num7 * num5;
             vector.X += 4 * num5;
             SpriteEffects spriteEffects = npcSpriteEffect;
             if (NPCID.Sets.IsTownSlime[n.type])
             {
                 spriteEffects ^= SpriteEffects.FlipHorizontally;
             }
             float num8 = 1f;
             if (n.shimmerTransparency > 0f)
             {
                 num8 *= 1f - n.shimmerTransparency;
             }
             spriteBatch.Draw(value, new Vector2(vector.X - screenPosition.X, vector.Y - screenPosition.Y), rectangle, npcColor * n.Opacity * num8, 0f, origin, n.scale, spriteEffects, 0f);
         }
         if (!beforeDraw && n.type == 681)
         {
             spriteBatch.Draw(TextureAssets.Extra[250].Value, new Vector2(n.position.X - screenPosition.X + (float)(n.width / 2) - (float)TextureAssets.Npc[n.type].Width() * n.scale / 2f + halfSize.X * n.scale, n.position.Y - screenPosition.Y + (float)n.height - (float)TextureAssets.Npc[n.type].Height() * n.scale / (float)npcFrameCount[n.type] + 4f + halfSize.Y * n.scale + addHeight + addY + n.gfxOffY), n.frame, n.GetAlpha(npcColor), n.rotation, halfSize, n.scale, npcSpriteEffect, 0f);
         }
         if (NPCID.Sets.AttackType[n.type] == 1 && n.ai[0] == 12f && !beforeDraw)
         {
             if (n.type == 228 || n.type == 229 || n.type == 209)
             {
                 return;
             }
             float num9 = n.ai[2];
             Vector2 vector2 = OffsetsNPCOffhand[2];
             if (n.spriteDirection == 1)
             {
                 vector2.X *= -1f;
             }
             Vector2 vector3 = n.Bottom - vector2;
             if (n.type == 22 && n.ai[2] > -0.1f)
             {
                 vector3.Y += 4f;
             }
             if (n.type == 368 && hardMode && n.ai[2] > -0.1f)
             {
                 vector3.Y += 4f;
             }
             if (n.type == 368 && !hardMode && n.ai[2] < -0.1f)
             {
                 vector3.Y -= 8f;
             }
             float rotation = num9 * ((float)Math.PI / 2f) * (float)n.spriteDirection;
             float num10 = 1f;
             int itemtype = 0;
             int num11 = 4;
             if (n.type == 19)
             {
                 itemtype = (hardMode ? 98 : 95);
                 if (hardMode)
                 {
                     vector3.X -= 10 * n.direction;
                     vector3.Y += 4f;
                 }
             }
             else if (n.type == 22)
             {
                 itemtype = 39;
                 num11 = 18;
             }
             else if (n.type == 178)
             {
                 itemtype = 434;
             }
             else if (n.type == 227)
             {
                 itemtype = 3350;
                 num11 = 16;
                 num10 = 0.85f;
             }
             else if (n.type == 368)
             {
                 itemtype = (hardMode ? 2223 : 2269);
                 if (hardMode)
                 {
                     num11 = 18;
                 }
                 else
                 {
                     if (n.ai[2] < -0.1f)
                     {
                         num11 = 28;
                     }
                     num10 = 0.75f;
                 }
             }
             Vector2 vector4 = DrawPlayerItemPos(1f, itemtype);
             GetItemDrawFrame(itemtype, out var itemTexture, out var value2);
             int num12 = (int)vector4.X - num11;
             Vector2 origin2 = new Vector2(-num12, value2.Height / 2);
             if (n.spriteDirection == -1)
             {
                 origin2 = new Vector2(value2.Width + num12, value2.Height / 2);
             }
             spriteBatch.Draw(itemTexture, new Vector2((int)(vector3.X - screenPosition.X), (int)(vector3.Y - screenPosition.Y)), value2, npcColor, rotation, origin2, n.scale * num10, npcSpriteEffect ^ SpriteEffects.FlipHorizontally, 0f);
             if (n.type == 22 && n.frame.Y / (TextureAssets.Npc[n.type].Height() / npcFrameCount[n.type]) >= 21)
             {
                 Texture2D value3 = TextureAssets.Extra[52].Value;
                 if (n.IsShimmerVariant)
                 {
                     value3 = TextureAssets.Extra[264].Value;
                 }
                 Microsoft.Xna.Framework.Rectangle value4 = value3.Frame(1, 5, 0, n.frame.Y / (TextureAssets.Npc[n.type].Height() / npcFrameCount[n.type]) - 21);
                 spriteBatch.Draw(value3, new Vector2(n.position.X - screenPosition.X + (float)(n.width / 2) - (float)TextureAssets.Npc[n.type].Width() * n.scale / 2f + halfSize.X * n.scale, n.position.Y - screenPosition.Y + (float)n.height - (float)TextureAssets.Npc[n.type].Height() * n.scale / (float)npcFrameCount[n.type] + 4f + halfSize.Y * n.scale + addHeight + addY + n.gfxOffY), value4, n.GetAlpha(npcColor), n.rotation, halfSize, n.scale, npcSpriteEffect, 0f);
             }
             else if (n.type == 368 && n.frame.Y / (TextureAssets.Npc[n.type].Height() / npcFrameCount[n.type]) >= 21)
             {
                 Texture2D value5 = TextureAssets.Extra[53].Value;
                 if (n.IsShimmerVariant)
                 {
                     value5 = TextureAssets.Extra[265].Value;
                 }
                 Microsoft.Xna.Framework.Rectangle value6 = value5.Frame(1, 5, 0, n.frame.Y / (TextureAssets.Npc[n.type].Height() / npcFrameCount[n.type]) - 21);
                 spriteBatch.Draw(value5, new Vector2(n.position.X - screenPosition.X + (float)(n.width / 2) - (float)TextureAssets.Npc[n.type].Width() * n.scale / 2f + halfSize.X * n.scale, n.position.Y - screenPosition.Y + (float)n.height - (float)TextureAssets.Npc[n.type].Height() * n.scale / (float)npcFrameCount[n.type] + 4f + halfSize.Y * n.scale + addHeight + addY + n.gfxOffY), value6, n.GetAlpha(npcColor), n.rotation, halfSize, n.scale, npcSpriteEffect, 0f);
             }
         }
         if (NPCID.Sets.AttackType[n.type] == 2 && (n.ai[0] == 14f || (n.ai[0] == 24f && n.frameCounter < 240.0)) && !beforeDraw)
         {
             Texture2D value7 = TextureAssets.Extra[51].Value;
             Vector2 vector5 = n.Bottom + new Vector2(0f, n.gfxOffY + 4f);
             Microsoft.Xna.Framework.Rectangle rectangle2 = value7.Frame(1, 4, 0, (int)n.frameCounter % 48 / 12);
             Vector2 origin3 = rectangle2.Size() * new Vector2(0.5f, 1f);
             spriteBatch.Draw(value7, new Vector2((int)(vector5.X - screenPosition.X), (int)(vector5.Y - screenPosition.Y)), rectangle2, n.GetMagicAuraColor(), 0f, origin3, n.scale, npcSpriteEffect ^ SpriteEffects.FlipHorizontally, 0f);
         }
         if (NPCID.Sets.AttackType[n.type] == 3 && n.ai[0] == 15f)
         {
             int num13 = 32;
             float num14 = 0f;
             Vector2 zero = Vector2.Zero;
             short num15 = 4;
             if (n.type == 207)
             {
                 num15 = 3349;
                 num14 = 0.15f;
                 if (beforeDraw)
                 {
                     return;
                 }
                 if (n.ai[1] > (float)NPCID.Sets.AttackTime[n.type] * 0.66f)
                 {
                     zero.Y = 12f;
                 }
             }
             else if (n.type == 353)
             {
                 num15 = 3352;
                 num14 = 0.15f;
                 if (!beforeDraw)
                 {
                     return;
                 }
                 if (n.ai[1] > (float)NPCID.Sets.AttackTime[n.type] * 0.66f)
                 {
                     zero.Y = 12f;
                 }
             }
             else if (n.type == 441)
             {
                 num15 = 3351;
                 num13 = 28;
                 num14 = 0.1f;
                 if (!beforeDraw)
                 {
                     return;
                 }
                 if (n.ai[1] > (float)NPCID.Sets.AttackTime[n.type] * 0.66f)
                 {
                     zero.Y = 12f;
                 }
             }
             GetItemDrawFrame(num15, out var itemTexture2, out var rectangle3);
             Tuple<Vector2, float> swingStats = n.GetSwingStats(NPCID.Sets.AttackTime[n.type] * 2, (int)n.ai[1], n.spriteDirection, num13, num13);
             Vector2 vector6 = swingStats.Item1 + (swingStats.Item1 - n.Center) * num14 + zero;
             Vector2 origin4 = rectangle3.Size() * new Vector2((n.spriteDirection != 1) ? 1 : 0, 1f);
             spriteBatch.Draw(itemTexture2, new Vector2((int)(vector6.X - screenPosition.X), (int)(vector6.Y - screenPosition.Y)), rectangle3, n.GetAlpha(npcColor), swingStats.Item2, origin4, n.scale, npcSpriteEffect ^ SpriteEffects.FlipHorizontally, 0f);
         }
         if (n.type == 550 && n.ai[0] == 18f)
         {
             if (beforeDraw)
             {
                 return;
             }
             instance.LoadItem(353);
             Texture2D value8 = TextureAssets.Item[353].Value;
             int num16 = 32;
             float num17 = 0.15f;
             Vector2 zero2 = Vector2.Zero;
             Microsoft.Xna.Framework.Rectangle rectangle4 = value8.Frame(1, 3, 0, 1);
             int num18 = (int)n.ai[2];
             if (num18 >= 0 && num18 < 255)
             {
                 Player player = Main.player[num18];
                 bool flag = player.HeldItem.type == 353 && player.direction == Math.Sign(n.Center.X - player.Center.X);
                 float num19 = player.Hitbox.Distance(n.Center);
                 float num20 = n.localAI[3];
                 if (num19 < 46f && flag)
                 {
                     n.localAI[3] = 1f;
                     if (n.localAI[3] != num20)
                     {
                         Vector2 vector7 = n.Center + new Vector2(n.spriteDirection * 30, -6f);
                         Vector2 vector8 = new Vector2(10f, 10f);
                         for (int i = 0; i < 30; i++)
{
                             Dust obj = Dust.NewDustDirect(vector7 - vector8 / 2f, (int)vector8.X, (int)vector8.Y, 4, 0f, 0f, 50, new Microsoft.Xna.Framework.Color(245, 200, 30, 155), 0.7f);
                             obj.noGravity = true;
                             obj.velocity *= 1f;
                             Dust.NewDustDirect(vector7 - vector8 / 2f, (int)vector8.X, (int)vector8.Y, 4, 0f, 0f, 50, new Microsoft.Xna.Framework.Color(245, 200, 30, 155), 0.6f).velocity *= 2f;
                         }
                     }
                 }
                 else if (n.localAI[3] == 1f)
                 {
                     n.localAI[3] = 2f;
                 }
             }
             Tuple<Vector2, float> swingStats2 = n.GetSwingStats(40, 12, n.spriteDirection, num16, num16);
             Vector2 vector9 = swingStats2.Item1 + (swingStats2.Item1 - n.Center) * num17 + zero2;
             Vector2 origin5 = rectangle4.Size() * new Vector2((n.spriteDirection != 1) ? 1 : 0, 1f);
             spriteBatch.Draw(value8, new Vector2((int)(vector9.X - screenPosition.X), (int)(vector9.Y - screenPosition.Y)), rectangle4, n.GetAlpha(npcColor), swingStats2.Item2, origin5, n.scale, npcSpriteEffect ^ SpriteEffects.FlipHorizontally, 0f);
         }
         if (beforeDraw || n.ai[0] != 23f)
         {
             return;
         }
         int num21 = (int)n.ai[2];
         if (num21 <= 0 || num21 > ItemID.Count)
         {
             return;
         }
         GetItemDrawFrame(num21, out var itemTexture3, out var rectangle5);
         int num22 = 0;
         num22 = (((int)n.frameCounter < 6) ? 1 : 2);
         if (n.ai[1] < 6f)
         {
             num22 = 1;
         }
         if (num22 == 0)
         {
             return;
         }
         Vector2 vector10 = Vector2.Zero;
         if (num22 == 1)
         {
             vector10 = new Vector2(10f, 6f);
         }
         if (num22 == 2)
         {
             vector10 = new Vector2(16f, 0f);
         }
         if (!npcSpriteEffect.HasFlag(SpriteEffects.FlipHorizontally))
         {
             vector10.X *= -1f;
         }
         if (n.type == 369)
         {
             vector10.X *= 0.5f;
             vector10.Y += 4f;
         }
         if (n.type == 453)
         {
             vector10.Y += 8f;
         }
         if (n.type == 550)
         {
             if (num21 == 353)
             {
                 rectangle5 = itemTexture3.Frame(1, 3, 0, 1);
             }
             vector10.Y += 6f;
         }
         Vector2 vector11 = n.Center + vector10;
         Vector2 origin6 = rectangle5.Size() * new Vector2((n.spriteDirection != 1) ? 1 : 0, 1f);
         Vector2 position = new Vector2((int)(vector11.X - screenPosition.X), (int)(vector11.Y - screenPosition.Y));
         Microsoft.Xna.Framework.Color alpha = n.GetAlpha(npcColor);
         spriteBatch.Draw(itemTexture3, position, rectangle5, alpha, 0f, origin6, n.scale, npcSpriteEffect ^ SpriteEffects.FlipHorizontally, 0f);
     }
References NPC.ai, NPCID.Sets.AttackTime, NPCID.Sets.AttackType, Entity.Bottom, Entity.Center, ItemID.Count, Entity.direction, DrawPlayerItemPos(), TextureAssets.Extra, NPC.frame, NPC.frameCounter, NPC.GetAlpha(), GetItemDrawFrame(), NPC.GetMagicAuraColor(), NPC.GetPartyHatColor(), NPC.GetSwingStats(), NPC.gfxOffY, hardMode, NPCID.Sets.HatOffsetY, Entity.height, Player.HeldItem, Entity.Hitbox, instance, NPC.IsShimmerVariant, NPCID.Sets.IsTownSlime, TextureAssets.Item, LoadItem(), NPC.localAI, Dust.NewDustDirect(), Dust.noGravity, TextureAssets.Npc, npcFrameCount, NPCID.Sets.NPCFramingGroup, OffsetsNPCOffhand, NPC.Opacity, player, Entity.position, NPC.rotation, NPC.scale, screenPosition, NPC.shimmerTransparency, spriteBatch, NPC.spriteDirection, Entity.Top, NPCID.Sets.TownNPCsFramingGroups, Item.type, NPC.type, NPC.UsesPartyHat(), Asset< T >.Value, Dust.velocity, and Entity.width.
Referenced by DrawNPCDirect().