Terraria: Main.OnSubmitServerPassword
OnSubmitServerPassword() [1/2]
void Main.OnSubmitServerPassword () inline private
     {
         string text = "-autoshutdown -password \"" + ConvertToSafeArgument(Netplay.ServerPassword) + "\" -lang " + Language.ActiveCulture.LegacyId;
         if (Platform.IsLinux)
         {
             text = ((IntPtr.Size != 8) ? (text + " -x86") : (text + " -x64"));
         }
         text = ((!ActiveWorldFileData.IsCloudSave) ? (text + SanitizePathArgument("world", worldPathName)) : (text + SanitizePathArgument("cloudworld", worldPathName)));
         text = text + " -worldrollbackstokeep " + WorldRollingBackupsCountToKeep;
         tServer = new Process();
         if (Platform.IsLinux)
         {
             tServer.StartInfo.FileName = "TerrariaServer";
         }
         else if (Platform.IsOSX)
         {
             tServer.StartInfo.FileName = "../MacOS/TerrariaServer";
         }
         else
         {
             tServer.StartInfo.FileName = "TerrariaServer.exe";
         }
         tServer.StartInfo.Arguments = text;
         if (libPath != "")
         {
             ProcessStartInfo startInfo = tServer.StartInfo;
             startInfo.Arguments = startInfo.Arguments + " -loadlib " + libPath;
         }
         tServer.StartInfo.UseShellExecute = false;
         tServer.StartInfo.CreateNoWindow = true;
         if (SocialAPI.Network != null)
         {
             SocialAPI.Network.LaunchLocalServer(tServer, MenuServerMode);
         }
         else
         {
             tServer.Start();
         }
         Netplay.SetRemoteIP("127.0.0.1");
         autoPass = true;
         statusText = Lang.menu[8].Value;
         Netplay.StartTcpClient();
         menuMode = 10;
     }
References Language.ActiveCulture, ActiveWorldFileData, autoPass, ConvertToSafeArgument(), FileData.IsCloudSave, Platform.IsLinux, Platform.IsOSX, NetSocialModule.LaunchLocalServer(), GameCulture.LegacyId, libPath, Lang.menu, menuMode, MenuServerMode, SocialAPI.Network, SanitizePathArgument(), Netplay.ServerPassword, Netplay.SetRemoteIP(), Netplay.StartTcpClient(), statusText, tServer, LocalizedText.Value, worldPathName, and WorldRollingBackupsCountToKeep.
Referenced by DrawMenu(), and OnSubmitServerPassword().