Terraria: Main.TriggerPing
TriggerPing()
static void Main.TriggerPing (Vector2 position) inline static
     {
         if (!dedServ)
         {
             Pings.Add(position);
             if (netMode == 1)
             {
                 NetManager.Instance.SendToServer(NetPingModule.Serialize(position));
             }
         }
     }
References PingMapLayer.Add(), dedServ, NetManager.Instance, netMode, Pings, NetManager.SendToServer(), and NetPingModule.Serialize().
Referenced by DrawMap().