Terraria: Main.DoUpdate_HandleChat
DoUpdate_HandleChat()
static void Main.DoUpdate_HandleChat () inline static private
     {
         if (CurrentInputTextTakerOverride != null)
         {
             drawingPlayerChat = false;
             return;
         }
         if (editSign)
         {
             drawingPlayerChat = false;
         }
         if (PlayerInput.UsingGamepad)
         {
             drawingPlayerChat = false;
         }
         if (!drawingPlayerChat)
         {
             chatMonitor.ResetOffset();
             return;
         }
         int linesOffset = 0;
         if (keyState.IsKeyDown(Microsoft.Xna.Framework.Input.Keys.Up))
         {
             linesOffset = 1;
         }
         else if (keyState.IsKeyDown(Microsoft.Xna.Framework.Input.Keys.Down))
         {
             linesOffset = -1;
         }
         chatMonitor.Offset(linesOffset);
         if (keyState.IsKeyDown(Microsoft.Xna.Framework.Input.Keys.Escape))
         {
             drawingPlayerChat = false;
         }
         string text = chatText;
         chatText = GetInputText(chatText);
         int num = 470;
         num = (int)((float)screenWidth * (1f / UIScale)) - 330;
         if (text != chatText)
         {
             for (float x = ChatManager.GetStringSize(FontAssets.MouseText.Value, chatText, Vector2.One).X; x > (float)num; x = ChatManager.GetStringSize(FontAssets.MouseText.Value, chatText, Vector2.One).X)
             {
                 int num2 = Math.Max(0, (int)(x - (float)num) / 100);
                 chatText = chatText.Substring(0, chatText.Length - 1 - num2);
             }
         }
         if (text != chatText)
         {
             SoundEngine.PlaySound(12);
         }
         if (!inputTextEnter || !chatRelease)
         {
             return;
         }
         if (chatText != "")
         {
             ChatMessage message = ChatManager.Commands.CreateOutgoingMessage(chatText);
             if (netMode == 1)
             {
                 ChatHelper.SendChatMessageFromClient(message);
             }
             else if (netMode == 0)
             {
                 ChatManager.Commands.ProcessIncomingMessage(message, myPlayer);
             }
         }
         chatText = "";
         ClosePlayerChat();
         chatRelease = false;
         SoundEngine.PlaySound(11);
     }
References chatMonitor, chatRelease, chatText, ClosePlayerChat(), ChatManager.Commands, ChatCommandProcessor.CreateOutgoingMessage(), CurrentInputTextTakerOverride, drawingPlayerChat, editSign, GetInputText(), ChatManager.GetStringSize(), inputTextEnter, keyState, FontAssets.MouseText, myPlayer, netMode, IChatMonitor.Offset(), SoundEngine.PlaySound(), ChatCommandProcessor.ProcessIncomingMessage(), IChatMonitor.ResetOffset(), screenWidth, ChatHelper.SendChatMessageFromClient(), UIScale, PlayerInput.UsingGamepad, and Asset< T >.Value.
Referenced by DoUpdate().