Terraria: Main.MouseText
MouseText() [1/2]
void Main.MouseText (string cursorText, int rare = 0, byte diff = 0, int hackedMouseX = -1, int hackedMouseY = -1, int hackedScreenWidth = -1, int hackedScreenHeight = -1, int pushWidthX = 0) inline
     {
         MouseText(cursorText, null, rare, diff, hackedMouseX, hackedMouseY, hackedScreenWidth, hackedScreenHeight, pushWidthX);
     }
References rare.
Referenced by UIResourcePackSelectionMenu.DisplayMouseTextIfHovered(), IssueReportsIndicator.Draw(), DrawBestiaryIcon(), DrawBlockReplacementIcon(), DrawBuilderAccToggles(), CaptureInterface.DrawButtons(), DrawEmoteBubblesButton(), DrawHotbarLockIcon(), DrawInfoAccs(), DrawInterface_33_MouseText(), DrawInterface_40_InteractItemIcon(), DrawInterface_InstrumentMouseText(), DrawInventory(), DrawLoadoutButtons(), DrawMap(), AchievementAdvisor.DrawMouseHover(), UIBestiaryInfoItemLine.DrawMouseOver(), DrawNPCHousesInUI(), DrawNPCHousesInWorld(), EmoteButton.DrawSelf(), UIBestiaryEntryButton.DrawSelf(), CreativeUI.DrawToggleButton(), TitleLinkButton.DrawTooltip(), DrawTorchBiomeSwapIcon(), CaptureInterface.ModeChangeSettings.DrawWaterChoices(), GUIChatDrawInner(), IngameOptions.MouseOver(), MouseTextHackZoom(), MouseTextNoOverride(), ItemTagHandler.ItemSnippet.OnHover(), UICreativeInfiniteItemsDisplay.research_OnUpdate(), FilterProviderInfoElement.ShowButtonName(), UIBestiaryFilteringOptionsGrid.ShowButtonName(), UICreativeItemsInfiniteFilteringOptions.ShowButtonName(), NPCKillCounterInfoElement.ShowDescription(), NPCStatsReportInfoElement.ShowStats_Attack(), UIBestiaryTest.ShowStats_Completion(), NPCStatsReportInfoElement.ShowStats_Defense(), NPCStatsReportInfoElement.ShowStats_Knockback(), and NPCStatsReportInfoElement.ShowStats_Life().