Terraria: Main.ErasePlayer
ErasePlayer()
static void Main.ErasePlayer (int i) inline static private
     {
         try
         {
             FileUtilities.Delete(PlayerList[i].Path, PlayerList[i].IsCloudSave);
             FileUtilities.Delete(PlayerList[i].Path + ".bak", PlayerList[i].IsCloudSave);
         }
         catch
         {
         }
         try
         {
             string text = PlayerList[i].Path.Substring(0, PlayerList[i].Path.Length - 4);
             if (text.Substring(text.Length - 1) != "." && text.Substring(text.Length - 1) != "\\" && Directory.Exists(text))
             {
                 Directory.Delete(text, recursive: true);
             }
             LoadPlayers();
         }
         catch
         {
         }
     }
References FileUtilities.Delete(), LoadPlayers(), and PlayerList.
Referenced by DrawMenu().