Terraria: Main.DrawProj_FairyQueenLance
DrawProj_FairyQueenLance()
void Main.DrawProj_FairyQueenLance (Projectile proj) inline private
     {
         Vector2 vector = proj.Center - screenPosition;
         int num = 40;
         int num2 = 180 * num;
         num2 /= 2;
         Microsoft.Xna.Framework.Color color = proj.AI_171_GetColor();
         Microsoft.Xna.Framework.Color color2 = color;
         color.A = 0;
         color2.A /= 2;
         Texture2D value = TextureAssets.Extra[178].Value;
         Vector2 origin = value.Frame().Size() * new Vector2(0f, 0.5f);
         Vector2 scale = new Vector2(num2 / value.Width, 2f);
         Vector2 scale2 = new Vector2((float)(num2 / value.Width) * 0.5f, 2f);
         Microsoft.Xna.Framework.Color color3 = color * Utils.GetLerpValue(60f, 55f, proj.localAI[0], clamped: true) * Utils.GetLerpValue(0f, 10f, proj.localAI[0], clamped: true);
         spriteBatch.Draw(value, vector, null, color3, proj.rotation, origin, scale2, SpriteEffects.None, 0f);
         spriteBatch.Draw(value, vector, null, color3 * 0.3f, proj.rotation, origin, scale, SpriteEffects.None, 0f);
         Texture2D value2 = TextureAssets.Projectile[proj.type].Value;
         Vector2 origin2 = value2.Frame().Size() / 2f;
         Microsoft.Xna.Framework.Color color4 = Microsoft.Xna.Framework.Color.White * Utils.GetLerpValue(0f, 20f, proj.localAI[0], clamped: true);
         color4.A /= 2;
         float num3 = MathHelper.Lerp(0.7f, 1f, Utils.GetLerpValue(55f, 60f, proj.localAI[0], clamped: true));
         float lerpValue = Utils.GetLerpValue(10f, 60f, proj.localAI[0]);
         if (lerpValue > 0f)
         {
             float lerpValue2 = Utils.GetLerpValue(0f, 1f, proj.velocity.Length(), clamped: true);
             for (float num4 = 1f; num4 > 0f; num4 -= 1f / 6f)
             {
                 Vector2 vector2 = proj.rotation.ToRotationVector2() * -120f * num4 * lerpValue2;
                 spriteBatch.Draw(value2, vector + vector2, null, color * lerpValue * (1f - num4), proj.rotation, origin2, num3, SpriteEffects.None, 0f);
                 spriteBatch.Draw(value2, vector + vector2, null, new Microsoft.Xna.Framework.Color(255, 255, 255, 0) * 0.15f * lerpValue * (1f - num4), proj.rotation, origin2, num3 * 0.85f, SpriteEffects.None, 0f);
             }
             for (float num5 = 0f; num5 < 1f; num5 += 0.25f)
             {
                 Vector2 vector3 = (num5 * ((float)Math.PI * 2f) + proj.rotation).ToRotationVector2() * 2f * num3;
                 spriteBatch.Draw(value2, vector + vector3, null, color2 * lerpValue, proj.rotation, origin2, num3, SpriteEffects.None, 0f);
             }
             spriteBatch.Draw(value2, vector, null, color2 * lerpValue, proj.rotation, origin2, num3 * 1.1f, SpriteEffects.None, 0f);
         }
         spriteBatch.Draw(value2, vector, null, color4, proj.rotation, origin2, num3, SpriteEffects.None, 0f);
     }
References Projectile.AI_171_GetColor(), Entity.Center, TextureAssets.Extra, Utils.GetLerpValue(), Projectile.localAI, TextureAssets.Projectile, Projectile.rotation, screenPosition, spriteBatch, Projectile.type, Asset< T >.Value, and Entity.velocity.
Referenced by DrawProjDirect().