Terraria: Main.StartInvasion
StartInvasion()
static void Main.StartInvasion (int type = 1) inline static
     {
         if (invasionType != 0 && invasionSize == 0)
         {
             invasionType = 0;
         }
         if (invasionType != 0)
         {
             return;
         }
         int num = 0;
         for (int i = 0; i < 255; i++)
         {
             if (player[i].active && player[i].statLifeMax >= 200)
             {
                 num++;
             }
         }
         if (num > 0)
         {
             invasionType = type;
             invasionSize = 80 + 40 * num;
             if (type == 3)
             {
                 invasionSize += 40 + 20 * num;
             }
             if (type == 4)
             {
                 invasionSize = 160 + 40 * num;
             }
             invasionSizeStart = invasionSize;
             invasionProgress = 0;
             invasionProgressIcon = type + 3;
             invasionProgressWave = 0;
             invasionProgressMax = invasionSizeStart;
             invasionWarn = 0;
             if (type == 4)
             {
                 invasionX = spawnTileX - 1;
                 invasionWarn = 2;
             }
             else if (rand.Next(2) == 0)
             {
                 invasionX = 0.0;
             }
             else
             {
                 invasionX = maxTilesX;
             }
         }
     }
References invasionProgress, invasionProgressIcon, invasionProgressMax, invasionProgressWave, invasionSize, invasionSizeStart, invasionType, invasionWarn, invasionX, maxTilesX, UnifiedRandom.Next(), player, rand, and spawnTileX.
Referenced by NPC.AI(), MessageBuffer.GetData(), Player.ItemCheck_UseEventItems(), and UpdateTime_StartDay().