Terraria: Main.DrawTileInWater
DrawTileInWater()
static void Main.DrawTileInWater (Vector2 drawOffset, int x, int y) inline static
     {
         if (Main.tile[x, y] != null && Main.tile[x, y].active() && Main.tile[x, y].type == 518)
         {
             instance.LoadTiles(Main.tile[x, y].type);
             Tile tile = Main.tile[x, y];
             int num = tile.liquid / 16;
             num -= 3;
             if (WorldGen.SolidTile(x, y - 1) && num > 8)
             {
                 num = 8;
             }
             Microsoft.Xna.Framework.Rectangle value = new Microsoft.Xna.Framework.Rectangle(tile.frameX, tile.frameY, 16, 16);
             spriteBatch.Draw(TextureAssets.Tile[tile.type].Value, new Vector2(x * 16, y * 16 - num) + drawOffset, value, Lighting.GetColor(x, y), 0f, default(Vector2), 1f, SpriteEffects.None, 0f);
         }
     }
References Tile.active(), Tile.frameX, Tile.frameY, Lighting.GetColor(), instance, Tile.liquid, LoadTiles(), WorldGen.SolidTile(), spriteBatch, TextureAssets.Tile, tile, Tile.type, and Asset< T >.Value.
Referenced by LiquidRenderer.DrawNormalLiquids(), LiquidRenderer.DrawShimmer(), and oldDrawWater().