Terraria: Main.OpenCharacterSelectUI
OpenCharacterSelectUI()
static void Main.OpenCharacterSelectUI () inline static
     {
         menuMode = 888;
         MenuUI.SetState(_characterSelectMenu);
     }
References _characterSelectMenu, menuMode, MenuUI, and UserInterface.SetState().
Referenced by UICharacterCreation.Click_GoBack(), DrawMenu(), UICharacterListItem.GoBackHere(), and UICharacterListItem.OnFinishedSettingName().