Terraria: Main.CloseNPCChatOrSign
CloseNPCChatOrSign()
static void Main.CloseNPCChatOrSign () inline static
     {
         player[myPlayer].sign = -1;
         editSign = false;
         player[myPlayer].SetTalkNPC(-1);
         npcChatCornerItem = 0;
         npcChatText = "";
         SoundEngine.PlaySound(11);
         player[myPlayer].releaseMount = false;
     }
References editSign, myPlayer, npcChatCornerItem, npcChatText, player, SoundEngine.PlaySound(), Player.releaseMount, Player.SetTalkNPC(), and Player.sign.
Referenced by GUIChatDrawInner().