Terraria: Main.UpdateUIStates
UpdateUIStates()
static void Main.UpdateUIStates (GameTime gameTime) inline static private
     {
         if (MenuUI != null)
         {
             MenuUI.Update(gameTime);
         }
         if (InGameUI != null)
         {
             InGameUI.Update(gameTime);
         }
         CreativeMenu.Update(gameTime);
         BigBossProgressBar.Update();
     }
References BigBossProgressBar, CreativeMenu, InGameUI, MenuUI, BigProgressBarSystem.Update(), CreativeUI.Update(), and UserInterface.Update().
Referenced by DoUpdate().