Terraria: Main.DrawSmartCursor
DrawSmartCursor()
static void Main.DrawSmartCursor () inline static private
     {
         if (SmartCursorShowing && !player[myPlayer].dead)
         {
             Vector2 vector = new Vector2(SmartCursorX, SmartCursorY) * 16f;
             new Vector2(offScreenRange, offScreenRange);
             _ = drawToScreen;
             vector -= screenPosition;
             if (player[myPlayer].gravDir == -1f)
             {
                 vector.Y = (float)screenHeight - vector.Y - 16f;
             }
             Microsoft.Xna.Framework.Color newColor = Lighting.GetColor(SmartCursorX, SmartCursorY) * 1f;
             Microsoft.Xna.Framework.Rectangle value = new Microsoft.Xna.Framework.Rectangle(0, 0, 1, 1);
             float r = 1f;
             float g = 0.9f;
             float b = 0.1f;
             float a = 1f;
             float num = 0.6f;
             spriteBatch.Draw(TextureAssets.MagicPixel.Value, vector, value, buffColor(newColor, r, g, b, a) * num, 0f, Vector2.Zero, 8f, SpriteEffects.None, 0f);
             spriteBatch.Draw(TextureAssets.MagicPixel.Value, vector + Vector2.UnitX * 8f, value, buffColor(newColor, r, g, b, a) * num, 0f, Vector2.Zero, 8f, SpriteEffects.None, 0f);
             spriteBatch.Draw(TextureAssets.MagicPixel.Value, vector + Vector2.UnitY * 8f, value, buffColor(newColor, r, g, b, a) * num, 0f, Vector2.Zero, 8f, SpriteEffects.None, 0f);
             spriteBatch.Draw(TextureAssets.MagicPixel.Value, vector + Vector2.One * 8f, value, buffColor(newColor, r, g, b, a) * num, 0f, Vector2.Zero, 8f, SpriteEffects.None, 0f);
             b = 0.3f;
             g = 0.95f;
             a = (num = 1f);
             spriteBatch.Draw(TextureAssets.MagicPixel.Value, vector + Vector2.UnitX * -2f, value, buffColor(newColor, r, g, b, a) * num, 0f, Vector2.Zero, new Vector2(2f, 16f), SpriteEffects.None, 0f);
             spriteBatch.Draw(TextureAssets.MagicPixel.Value, vector + Vector2.UnitX * 16f, value, buffColor(newColor, r, g, b, a) * num, 0f, Vector2.Zero, new Vector2(2f, 16f), SpriteEffects.None, 0f);
             spriteBatch.Draw(TextureAssets.MagicPixel.Value, vector + Vector2.UnitY * -2f, value, buffColor(newColor, r, g, b, a) * num, 0f, Vector2.Zero, new Vector2(16f, 2f), SpriteEffects.None, 0f);
             spriteBatch.Draw(TextureAssets.MagicPixel.Value, vector + Vector2.UnitY * 16f, value, buffColor(newColor, r, g, b, a) * num, 0f, Vector2.Zero, new Vector2(16f, 2f), SpriteEffects.None, 0f);
         }
     }
References buffColor(), drawToScreen, Lighting.GetColor(), TextureAssets.MagicPixel, myPlayer, offScreenRange, player, screenHeight, screenPosition, SmartCursorShowing, SmartCursorX, SmartCursorY, spriteBatch, and Asset< T >.Value.
Referenced by DrawInterface_2_SmartCursorTargets().