Terraria: Main.DrawSurfaceBG_DrawBackMountainsLayer
DrawSurfaceBG_DrawBackMountainsLayer()
void Main.DrawSurfaceBG_DrawBackMountainsLayer (int bgTextureIndex) inline private
     {
         if (bgTextureIndex >= 0)
         {
             LoadBackground(bgTextureIndex);
             int num = DrawSurfaceBG_GetLayerYOffset(bgTextureIndex);
             bgTopY += num;
             for (int i = 0; i < bgLoops; i++)
             {
                 spriteBatch.Draw(TextureAssets.Background[bgTextureIndex].Value, new Vector2(bgStartX + bgWidthScaled * i, bgTopY), GetBackgroundRect(bgTextureIndex), ColorOfSurfaceBackgroundsModified, 0f, default(Vector2), bgScale, SpriteEffects.None, 0f);
             }
             bgTopY -= num;
         }
     }
References TextureAssets.Background, bgLoops, bgScale, bgStartX, bgTopY, bgWidthScaled, ColorOfSurfaceBackgroundsModified, DrawSurfaceBG_GetLayerYOffset(), GetBackgroundRect(), LoadBackground(), spriteBatch, and Asset< T >.Value.
Referenced by DrawSurfaceBG_BackMountainsStep1(), and DrawSurfaceBG_BackMountainsStep2().