Terraria: Main.ShouldDrawBackgroundTileAt
ShouldDrawBackgroundTileAt()
static bool Main.ShouldDrawBackgroundTileAt (int i, int j) inline static private
     {
         if (tile[i, j] == null)
         {
             tile[i, j] = new Tile();
         }
         if (caveParallax != 0f)
         {
             if (tile[i - 1, j] == null)
             {
                 tile[i - 1, j] = new Tile();
             }
             if (tile[i + 1, j] == null)
             {
                 tile[i + 1, j] = new Tile();
             }
             if (WallLightAt(i, j) || WallLightAt(i - 1, j) || WallLightAt(i + 1, j))
             {
                 return true;
             }
         }
         else if (WallLightAt(i, j))
         {
             return true;
         }
         return false;
     }
References caveParallax, Tile, tile, and WallLightAt().
Referenced by DrawBackground(), and OldDrawBackground().