Terraria: Main.InvasionWarning
InvasionWarning()
static void Main.InvasionWarning () inline static private
     {
         LocalizedText empty = LocalizedText.Empty;
         empty = ((invasionSize <= 0) ? ((invasionType == 2) ? Lang.misc[4] : ((invasionType == 3) ? Lang.misc[24] : ((invasionType != 4) ? (empty = Lang.misc[0]) : Lang.misc[42]))) : ((invasionX < (double)spawnTileX) ? ((invasionType == 2) ? Lang.misc[5] : ((invasionType == 3) ? Lang.misc[25] : ((invasionType != 4) ? (empty = Lang.misc[1]) : LocalizedText.Empty))) : ((invasionX > (double)spawnTileX) ? ((invasionType == 2) ? Lang.misc[6] : ((invasionType == 3) ? Lang.misc[26] : ((invasionType != 4) ? (empty = Lang.misc[2]) : LocalizedText.Empty))) : ((invasionType == 2) ? Lang.misc[7] : ((invasionType == 3) ? Lang.misc[27] : ((invasionType != 4) ? (empty = Lang.misc[3]) : Lang.misc[41]))))));
         if (netMode == 0)
         {
             NewText(empty.ToString(), 175, 75);
         }
         else if (netMode == 2 && empty.Value != "")
         {
             ChatHelper.BroadcastChatMessage(NetworkText.FromKey(empty.Key), new Microsoft.Xna.Framework.Color(175, 75, 255));
         }
     }
References ChatHelper.BroadcastChatMessage(), LocalizedText.Empty, NetworkText.FromKey(), invasionSize, invasionType, invasionX, LocalizedText.Key, Lang.misc, netMode, NewText(), spawnTileX, LocalizedText.ToString(), and LocalizedText.Value.
Referenced by UpdateInvasion().