Terraria: Main.UpdateSlimeRainWarning
UpdateSlimeRainWarning()
static void Main.UpdateSlimeRainWarning () inline static private
     {
         if (slimeWarningTime <= 0)
         {
             return;
         }
         slimeWarningTime--;
         if (slimeWarningTime > 0)
         {
             return;
         }
         if (netMode == 0)
         {
             if (slimeRainTime > 0.0)
             {
                 NewText(Lang.gen[74].Value, 50, byte.MaxValue, 130);
             }
             else
             {
                 NewText(Lang.gen[75].Value, 50, byte.MaxValue, 130);
             }
         }
         else if (slimeRainTime > 0.0)
         {
             ChatHelper.BroadcastChatMessage(NetworkText.FromKey(Lang.gen[74].Key), new Microsoft.Xna.Framework.Color(50, 255, 130));
         }
         else
         {
             ChatHelper.BroadcastChatMessage(NetworkText.FromKey(Lang.gen[75].Key), new Microsoft.Xna.Framework.Color(50, 255, 130));
         }
     }
References ChatHelper.BroadcastChatMessage(), NetworkText.FromKey(), Lang.gen, LocalizedText.Key, netMode, NewText(), slimeRainTime, slimeWarningTime, and LocalizedText.Value.
Referenced by UpdateTime().