Terraria: Main.MenuUI
MenuUI
UserInterface Main.MenuUI = new UserInterface() static
Referenced by UIResourcePackSelectionMenu.Click_Info(), UICharacterCreation.Click_Naming(), UICharacterCreation.Click_NamingAndCreating(), UIWorldCreation.Click_NamingAndCreating(), UIWorkshopHub.Click_OpenResourcePackPublishMenu(), UIWorkshopHub.Click_OpenWorldImportMenu(), UIWorkshopHub.Click_OpenWorldPublishMenu(), UIWorldCreation.Click_SetName(), UIWorldCreation.Click_SetSeed(), WorldGen.CreateNewWorld(), DoDraw(), DoUpdate(), UICharacterSelect.Draw(), UIWorldSelect.Draw(), DrawMenu(), UILinksInitializer.FancyExit(), UICreativeInfiniteItemsDisplay.GetCurrentInterface(), RichPresenceState.GetCurrentState(), UIReportsPage.GoBackClick(), UIResourcePackInfoMenu.GoBackClick(), UIWorldCreation.GoBackHere(), UILinkPointNavigator.GoToDefaultPage(), WorkshopPublishInfoStateForResourcePack.GoToPublishConfirmation(), WorkshopPublishInfoStateForWorld.GoToPublishConfirmation(), GoToWorldSelect(), AWorkshopPublishInfoState< TPublishedObjectType >.HandleBackButtonUsage(), UIResourcePackSelectionMenu.HandleBackButtonUsage(), UIWorkshopHub.HandleBackButtonUsage(), UIWorkshopSelectResourcePackToPublish.HandleBackButtonUsage(), UIWorkshopSelectWorldToPublish.HandleBackButtonUsage(), UIWorkshopWorldImport.HandleBackButtonUsage(), UIWorkshopImportWorldListItem.ImportButtonClick_ImportWorldToLocalFiles(), UILinksInitializer.Load(), UICharacterSelect.NewCharacterClick(), UIWorldSelect.NewWorldClick(), UICharacterCreation.OnCanceledNaming(), UILinksInitializer.OnFancyUIPageMoveAttempt(), UICharacterCreation.OnFinishedNaming(), UICharacterCreation.OnFinishedNamingAndCreating(), OpenCharacterSelectUI(), OpenPlayerSelect(), OpenReportsMenu(), OpenResourcePacksMenu(), OpenWorldSelectUI(), PreDrawMenu(), UIWorkshopPublishResourcePackListItem.PublishButtonClick_ImportResourcePackToLocalFiles(), UIWorkshopPublishWorldListItem.PublishButtonClick_ImportWorldToLocalFiles(), UIWorkshopPublishResourcePackListItem.RejectionMenuExitAction(), UICharacterListItem.RenameButtonClick(), UIWorldListItem.RenameButtonClick(), GamepadMainMenuHandler.Update(), and UpdateUIStates().