Terraria: Main.HandleMeteorFall
HandleMeteorFall()
static void Main.HandleMeteorFall () inline static private
     {
         if (netMode != 1 && WorldGen.spawnMeteor)
         {
             if (time < 15000.0)
             {
                 _canShowMeteorFall = true;
             }
             else
             {
                 if (_canShowMeteorFall && time <= 16200.0)
                 {
                     AmbienceServer.ForceEntitySpawn(new AmbienceServer.AmbienceSpawnInfo
                     {
                         skyEntityType = SkyEntityType.Meteor,
                         targetPlayer = -1
                     });
                 }
                 _canShowMeteorFall = false;
             }
         }
         if (time > 16200.0 && WorldGen.spawnMeteor)
         {
             WorldGen.spawnMeteor = false;
             WorldGen.dropMeteor();
         }
     }
References _canShowMeteorFall, WorldGen.dropMeteor(), AmbienceServer.ForceEntitySpawn(), netMode, WorldGen.spawnMeteor, and time.
Referenced by UpdateTime().