Terraria: Main.DrawSurfaceBG
DrawSurfaceBG()
void Main.DrawSurfaceBG () inline protected
     {
         bool flag = false;
         if ((!remixWorld || (gameMenu && !WorldGen.remixWorldGen)) && (!WorldGen.remixWorldGen || !WorldGen.drunkWorldGen))
         {
             flag = true;
         }
         if (mapFullscreen)
         {
             flag = false;
         }
         Microsoft.Xna.Framework.Color colorOfSurfaceBackgroundsBase = ColorOfSurfaceBackgroundsBase;
         int num = 30;
         if (gameMenu)
         {
             num = 0;
         }
         if (WorldGen.drunkWorldGen)
         {
             num = -180;
         }
         float num2 = (float)worldSurface;
         if (num2 == 0f)
         {
             num2 = 1f;
         }
         _ = screenPosition;
         float num3 = screenPosition.Y + (float)(screenHeight / 2) - 600f;
         double num4 = (num3 - screenOff / 2f) / (num2 * 16f);
         num4 = 0f - MathHelper.Lerp((float)num4, 1f, 0f);
         num4 = (0f - num3 + screenOff / 2f) / (num2 * 16f);
         float num5 = 2f;
         int num6 = 0;
         float num7 = SkyManager.Instance.ProcessCloudAlpha() * atmo;
         if (flag && (double)screenPosition.Y < worldSurface * 16.0 + 16.0)
         {
             for (int i = 0; i < 200; i++)
             {
                 if (cloud[i].active && cloud[i].scale < 1f)
                 {
                     Microsoft.Xna.Framework.Color color = cloud[i].cloudColor(ColorOfTheSkies);
                     float num8 = cloud[i].scale * 0.8f;
                     float num9 = (cloud[i].scale + 1f) / 2f * 0.9f;
                     color.R = (byte)((float)(int)color.R * num8);
                     color.G = (byte)((float)(int)color.G * num9);
                     float num10 = cloud[i].position.Y * ((float)screenHeight / 600f);
                     num10 = cloud[i].position.Y + (float)(int)(num4 * 750.0 + 830.0) + (float)(int)scAdj + (float)num6;
                     spriteBatch.Draw(TextureAssets.Cloud[cloud[i].type].Value, new Vector2(cloud[i].position.X + (float)TextureAssets.Cloud[cloud[i].type].Width() * 0.5f, num10 + (float)TextureAssets.Cloud[cloud[i].type].Height() * 0.5f), new Microsoft.Xna.Framework.Rectangle(0, 0, TextureAssets.Cloud[cloud[i].type].Width(), TextureAssets.Cloud[cloud[i].type].Height()), color * num7, cloud[i].rotation, new Vector2((float)TextureAssets.Cloud[cloud[i].type].Width() * 0.5f, (float)TextureAssets.Cloud[cloud[i].type].Height() * 0.5f), cloud[i].scale, cloud[i].spriteDir, 0f);
                 }
             }
         }
         if (invasionType == 4 && !SkyManager.Instance["Martian"].IsActive())
         {
             SkyManager.Instance.Activate("Martian", default(Vector2));
         }
         else if (invasionType != 4 && SkyManager.Instance["Martian"].IsActive())
         {
             SkyManager.Instance.Deactivate("Martian");
         }
         SkyManager.Instance.ResetDepthTracker();
         bgParallax = 0.15;
         int num11 = -180;
         bool flag2 = true;
         int num12 = 0;
         if (gameMenu)
         {
             num12 -= num11;
         }
         num6 = num12;
         num6 += num;
         if (!WorldGen.drunkWorldGen && flag && (double)(screenPosition.Y / 16f) <= worldSurface + 10.0)
         {
             if (BackgroundEnabled)
             {
                 if (cloudBGActive > 0f)
                 {
                     cloudBGAlpha += 0.0005f * (float)dayRate;
                     if (cloudBGAlpha > 1f)
                     {
                         cloudBGAlpha = 1f;
                     }
                 }
                 else
                 {
                     cloudBGAlpha -= 0.0005f * (float)dayRate;
                     if (cloudBGAlpha < 0f)
                     {
                         cloudBGAlpha = 0f;
                     }
                 }
                 if (cloudBGAlpha > 0f)
                 {
                     LoadBackground(cloudBG[0]);
                     LoadBackground(cloudBG[1]);
                     float num13 = cloudBGAlpha;
                     if (num13 > 1f)
                     {
                         num13 = 1f;
                     }
                     bgScale = 1.65f;
                     bgParallax = 0.09000000357627869;
                     if (base.IsActive && !gamePaused)
                     {
                         cloudBGX[0] += windSpeedCurrent * (float)bgParallax * 9f * (float)dayRate;
                     }
                     if (cloudBGX[0] > (float)backgroundWidth[cloudBG[0]] * bgScale)
                     {
                         cloudBGX[0] -= (float)backgroundWidth[cloudBG[0]] * bgScale;
                     }
                     if (cloudBGX[0] < (float)(-backgroundWidth[cloudBG[0]]) * bgScale)
                     {
                         cloudBGX[0] += (float)backgroundWidth[cloudBG[0]] * bgScale;
                     }
                     float num14 = (float)backgroundWidth[cloudBG[0]] * bgScale;
                     bgTopY = (int)(num4 * 900.0 + 600.0) + (int)scAdj + num6;
                     if (gameMenu)
                     {
                         bgTopY = -150 + num6;
                     }
                     bgStartX = (int)(0.0 - Math.IEEERemainder((double)screenPosition.X * bgParallax, num14) - (double)(num14 / 2f) - (double)num14);
                     bgStartX += (int)cloudBGX[0];
                     bgLoops = screenWidth / (int)num14 + 2 + 2;
                     ColorOfSurfaceBackgroundsModified = colorOfSurfaceBackgroundsBase * num13;
                     SkyManager.Instance.DrawToDepth(spriteBatch, 1f / (float)bgParallax);
                     for (int j = 0; j < bgLoops; j++)
                     {
                         spriteBatch.Draw(TextureAssets.Background[cloudBG[0]].Value, new Vector2((float)bgStartX + num14 * (float)j, bgTopY), new Microsoft.Xna.Framework.Rectangle(0, 0, backgroundWidth[cloudBG[0]], backgroundHeight[cloudBG[0]]), ColorOfSurfaceBackgroundsModified * num7, 0f, default(Vector2), bgScale, SpriteEffects.None, 0f);
                     }
                     num13 = cloudBGAlpha * 1.5f;
                     if (num13 > 1f)
                     {
                         num13 = 1f;
                     }
                     ColorOfSurfaceBackgroundsModified = colorOfSurfaceBackgroundsBase * num13;
                     bgScale = 1.85f;
                     bgParallax = 0.12;
                     if (base.IsActive && !gamePaused)
                     {
                         cloudBGX[1] += windSpeedCurrent * (float)bgParallax * 9f * (float)dayRate;
                     }
                     if (cloudBGX[1] > (float)backgroundWidth[cloudBG[1]] * bgScale)
                     {
                         cloudBGX[1] -= (float)backgroundWidth[cloudBG[1]] * bgScale;
                     }
                     if (cloudBGX[1] < (float)(-backgroundWidth[cloudBG[1]]) * bgScale)
                     {
                         cloudBGX[1] += (float)backgroundWidth[cloudBG[1]] * bgScale;
                     }
                     num14 = (float)backgroundWidth[cloudBG[1]] * bgScale;
                     bgTopY = (int)(num4 * 1100.0 + 750.0) + (int)scAdj + num6;
                     if (gameMenu)
                     {
                         bgTopY = -50 + num6;
                     }
                     bgStartX = (int)(0.0 - Math.IEEERemainder((double)screenPosition.X * bgParallax, num14) - (double)(num14 / 2f) - (double)num14);
                     bgStartX += (int)cloudBGX[1];
                     bgLoops = screenWidth / (int)num14 + 2 + 2;
                     SkyManager.Instance.DrawToDepth(spriteBatch, 1f / (float)bgParallax);
                     for (int k = 0; k < bgLoops; k++)
                     {
                         spriteBatch.Draw(TextureAssets.Background[cloudBG[1]].Value, new Vector2((float)bgStartX + num14 * (float)k, bgTopY), new Microsoft.Xna.Framework.Rectangle(0, 0, backgroundWidth[cloudBG[1]], backgroundHeight[cloudBG[1]]), ColorOfSurfaceBackgroundsModified * num7, 0f, default(Vector2), bgScale, SpriteEffects.None, 0f);
                     }
                 }
                 DrawSurfaceBG_BackMountainsStep1(num4, num5, num6);
             }
             cTop = bgTopY - 50;
             if ((double)screenPosition.Y < worldSurface * 16.0 + 16.0)
             {
                 for (int l = 0; l < 200; l++)
                 {
                     if (cloud[l].active && (double)cloud[l].scale < 1.15 && cloud[l].scale >= 1f)
                     {
                         Microsoft.Xna.Framework.Color color2 = cloud[l].cloudColor(ColorOfTheSkies);
                         if (atmo < 1f)
{
                             color2 *= atmo;
                         }
                         float num15 = cloud[l].position.Y * ((float)screenHeight / 600f);
                         float num16 = (float)((double)(screenPosition.Y / 16f - 24f) / worldSurface);
                         if (num16 < 0f)
{
                             num16 = 0f;
                         }
                         if (num16 > 1f)
{
                             num16 = 1f;
                         }
                         if (gameMenu)
{
                             num16 = 1f;
                         }
                         spriteBatch.Draw(TextureAssets.Cloud[cloud[l].type].Value, new Vector2(cloud[l].position.X + (float)TextureAssets.Cloud[cloud[l].type].Width() * 0.5f, num15 + (float)TextureAssets.Cloud[cloud[l].type].Height() * 0.5f + cTop + 200f), new Microsoft.Xna.Framework.Rectangle(0, 0, TextureAssets.Cloud[cloud[l].type].Width(), TextureAssets.Cloud[cloud[l].type].Height()), color2 * num7, cloud[l].rotation, new Vector2((float)TextureAssets.Cloud[cloud[l].type].Width() * 0.5f, (float)TextureAssets.Cloud[cloud[l].type].Height() * 0.5f), cloud[l].scale, cloud[l].spriteDir, 0f);
                     }
                 }
             }
             if (SceneMetrics.HolyTileCount > 0 && BackgroundEnabled)
             {
                 bgParallax = 0.17;
                 bgScale = 1.1f;
                 bgTopY = (int)(num4 * 1400.0 + 900.0) + (int)scAdj + num6;
                 SetBackgroundOffsets(18, num4, num6);
                 bgScale *= num5;
                 bgWidthScaled = (int)((double)(2100f * bgScale) * 1.05);
                 bgStartX = (int)(0.0 - Math.IEEERemainder((double)screenPosition.X * bgParallax, bgWidthScaled) - (double)(bgWidthScaled / 2));
                 bgLoops = screenWidth / bgWidthScaled + 2;
                 if (gameMenu)
                 {
                     bgTopY = 230 + num6;
                     bgStartX -= 500;
                 }
                 SkyManager.Instance.DrawToDepth(spriteBatch, 1f / (float)bgParallax);
                 Microsoft.Xna.Framework.Color color3 = colorOfSurfaceBackgroundsBase;
                 float num17 = (float)(SceneMetrics.HolyTileCount - SceneMetrics.HallowTileThreshold) / (float)(SceneMetrics.HallowTileMax - SceneMetrics.HallowTileThreshold);
                 if (num17 > 0.5f)
                 {
                     num17 = 0.5f;
                 }
                 else if (num17 < 0f)
                 {
                     num17 = 0f;
                 }
                 color3.R = (byte)((float)(int)color3.R * num17);
                 color3.G = (byte)((float)(int)color3.G * num17);
                 color3.B = (byte)((float)(int)color3.B * num17);
                 color3.A = (byte)((float)(int)color3.A * num17 * 0.8f);
                 if ((double)screenPosition.Y < worldSurface * 16.0 + 16.0)
                 {
                     LoadBackground(18);
                     LoadBackground(19);
                     for (int m = 0; m < bgLoops; m++)
                     {
                         spriteBatch.Draw(TextureAssets.Background[18].Value, new Vector2(bgStartX + bgWidthScaled * m, bgTopY), new Microsoft.Xna.Framework.Rectangle(0, 0, backgroundWidth[18], backgroundHeight[18]), color3, 0f, default(Vector2), bgScale, SpriteEffects.None, 0f);
                         spriteBatch.Draw(TextureAssets.Background[19].Value, new Vector2(bgStartX + bgWidthScaled * m + 1900, bgTopY + 100), new Microsoft.Xna.Framework.Rectangle(0, 0, backgroundWidth[19], backgroundHeight[19]), color3, 0f, default(Vector2), bgScale * 0.9f, SpriteEffects.None, 0f);
                     }
                 }
             }
             if (treeMntBGSet1[1] > -1)
             {
                 LoadBackground(treeMntBGSet1[1]);
                 bgParallax = 0.2;
                 bgScale = 1.15f;
                 bgScale *= num5;
                 int num18 = backgroundWidth[treeMntBGSet1[1]];
                 if (num18 == 0)
                 {
                     num18 = 1;
                 }
                 bgWidthScaled = (int)((float)num18 * bgScale);
                 bgStartX = (int)(0.0 - Math.IEEERemainder((double)screenPosition.X * bgParallax, bgWidthScaled) - (double)(bgWidthScaled / 2));
                 bgLoops = screenWidth / bgWidthScaled + 2;
                 if (treeMntBGSet1[1] == 172)
                 {
                     bgLoops++;
                 }
                 bgTopY = (int)(num4 * 1400.0 + 1260.0) + (int)scAdj + num6;
             }
             if (BackgroundEnabled)
             {
                 DrawSurfaceBG_BackMountainsStep2(num6);
             }
             cTop = (float)bgTopY * 1.01f - 150f;
             if ((double)screenPosition.Y < worldSurface * 16.0 + 16.0)
             {
                 for (int n = 0; n < 200; n++)
                 {
                     if (cloud[n].active && cloud[n].scale >= 1.15f)
                     {
                         Microsoft.Xna.Framework.Color color4 = cloud[n].cloudColor(ColorOfTheSkies);
                         if (atmo < 1f)
{
                             color4 *= atmo;
                         }
                         float num19 = cloud[n].position.Y * ((float)screenHeight / 600f) - 100f;
                         float num20 = (float)((double)(screenPosition.Y / 16f - 24f) / worldSurface);
                         if (num20 < 0f)
{
                             num20 = 0f;
                         }
                         if (num20 > 1f)
{
                             num20 = 1f;
                         }
                         if (gameMenu)
{
                             num20 = 1f;
                         }
                         spriteBatch.Draw(TextureAssets.Cloud[cloud[n].type].Value, new Vector2(cloud[n].position.X + (float)TextureAssets.Cloud[cloud[n].type].Width() * 0.5f, num19 + (float)TextureAssets.Cloud[cloud[n].type].Height() * 0.5f + cTop), new Microsoft.Xna.Framework.Rectangle(0, 0, TextureAssets.Cloud[cloud[n].type].Width(), TextureAssets.Cloud[cloud[n].type].Height()), color4 * num7, cloud[n].rotation, new Vector2((float)TextureAssets.Cloud[cloud[n].type].Width() * 0.5f, (float)TextureAssets.Cloud[cloud[n].type].Height() * 0.5f), cloud[n].scale, cloud[n].spriteDir, 0f);
                     }
                 }
             }
         }
         if (flag2)
         {
             num6 += num11;
         }
         if (flag)
         {
             for (int num21 = 0; num21 < bgAlphaFrontLayer.Length; num21++)
             {
                 if (BackgroundEnabled)
                 {
                     ColorOfSurfaceBackgroundsModified = colorOfSurfaceBackgroundsBase * bgAlphaFrontLayer[num21];
                     if (bgAlphaFrontLayer[num21] > 0f && num21 == 0)
                     {
                         DrawSurfaceBG_Forest(num4, num5, num6, treeBGSet1);
                         DrawSurfaceBG_DrawChangeOverlay(0);
                     }
                     if (bgAlphaFrontLayer[num21] > 0f && num21 == 10)
                     {
                         DrawSurfaceBG_Forest(num4, num5, num6, treeBGSet2);
                         DrawSurfaceBG_DrawChangeOverlay(1);
                     }
                     if (bgAlphaFrontLayer[num21] > 0f && num21 == 11)
                     {
                         DrawSurfaceBG_Forest(num4, num5, num6, treeBGSet3);
                         DrawSurfaceBG_DrawChangeOverlay(2);
                     }
                     if (bgAlphaFrontLayer[num21] > 0f && num21 == 12)
                     {
                         DrawSurfaceBG_Forest(num4, num5, num6, treeBGSet4);
                         DrawSurfaceBG_DrawChangeOverlay(3);
                     }
                     if (bgAlphaFrontLayer[num21] > 0f && num21 == 1)
                     {
                         int[] bgTexIndexes = corruptBG;
                         DrawSurfaceBG_Corrupt(num4, num5, num6, bgTexIndexes);
                         DrawSurfaceBG_DrawChangeOverlay(4);
                     }
                     if (bgAlphaFrontLayer[num21] > 0f && num21 == 2)
                     {
                         int[] bgTexIndexes2 = desertBG;
                         DrawSurfaceBG_Desert(num4, num5, num6, bgTexIndexes2);
                         DrawSurfaceBG_DrawChangeOverlay(9);
                     }
                     if (bgAlphaFrontLayer[num21] > 0f && num21 == 3)
                     {
                         int[] bgTexIndexes3 = jungleBG;
                         DrawSurfaceBG_Jungle(num4, num5, num6, bgTexIndexes3);
                         DrawSurfaceBG_DrawChangeOverlay(5);
                     }
                     if (bgAlphaFrontLayer[num21] > 0f && num21 == 4)
                     {
                         DrawSurfaceBG_DrawChangeOverlay(10);
                     }
                     if (bgAlphaFrontLayer[num21] > 0f && num21 == 5)
                     {
                         DrawSurfaceBG_GoodEvilDesert(num4, num5, num6);
                         DrawSurfaceBG_DrawChangeOverlay(9);
                     }
                     if (bgAlphaFrontLayer[num21] > 0f && num21 == 6)
                     {
                         int[] bgTexIndexes4 = hallowBG;
                         DrawSurfaceBG_Hallow(num4, num5, num6, bgTexIndexes4);
                         DrawSurfaceBG_DrawChangeOverlay(7);
                     }
                     if (bgAlphaFrontLayer[num21] > 0f && num21 == 7)
                     {
                         int[] bgTexIndexes5 = snowBG;
                         DrawSurfaceBG_Snow(num4, num5, num6, bgTexIndexes5);
                         DrawSurfaceBG_DrawChangeOverlay(6);
                     }
                     if (bgAlphaFrontLayer[num21] > 0f && num21 == 8)
                     {
                         int[] bgTexIndexes6 = crimsonBG;
                         DrawSurfaceBG_Crimson(num4, num5, num6, bgTexIndexes6);
                         DrawSurfaceBG_DrawChangeOverlay(8);
                     }
                     if (bgAlphaFrontLayer[num21] > 0f && num21 == 9)
                     {
                         int[] bgTexIndexes7 = mushroomBG;
                         DrawSurfaceBG_Mushroom(num4, num5, num6, bgTexIndexes7);
                         DrawSurfaceBG_DrawChangeOverlay(11);
                     }
                 }
             }
         }
         if (flag2)
         {
             num6 -= num11;
         }
         float num22 = DrawSurfaceBG_GetFogPower();
         if (flag && num22 > 0f && !gameMenu && (double)screenPosition.Y < worldSurface * 16.0 + 16.0)
         {
             bgParallax = 0.1;
             bgStartX = (int)(0.0 - Math.IEEERemainder((double)screenPosition.X * bgParallax, backgroundWidth[background]) - (double)(backgroundWidth[background] / 2));
             bgLoops = screenWidth / backgroundWidth[background] + 2;
             bgStartY = 0;
             bgLoopsY = 0;
             bgTopY = (int)((double)(0f - screenPosition.Y) / (worldSurface * 16.0 - 600.0) * 200.0);
             Texture2D value = TextureAssets.Background[49].Value;
             for (int num23 = 0; num23 < bgLoops; num23++)
             {
                 bgStartX = 0;
                 Microsoft.Xna.Framework.Color color5 = ColorOfTheSkies * num22 * atmo;
                 int height = Math.Max(screenHeight + 210, value.Height);
                 spriteBatch.Draw(value, new Microsoft.Xna.Framework.Rectangle(bgStartX + value.Width * num23, bgTopY, value.Width, height), color5);
             }
         }
         if (!mapFullscreen)
         {
             SkyManager.Instance.DrawRemainingDepth(spriteBatch);
         }
     }
References EffectManager< T >.Activate(), atmo, TextureAssets.Background, background, BackgroundEnabled, backgroundHeight, backgroundWidth, bgAlphaFrontLayer, bgLoops, bgLoopsY, bgParallax, bgScale, bgStartX, bgStartY, bgTopY, bgWidthScaled, TextureAssets.Cloud, cloud, cloudBG, cloudBGActive, cloudBGAlpha, cloudBGX, Cloud.cloudColor(), ColorOfSurfaceBackgroundsBase, ColorOfSurfaceBackgroundsModified, ColorOfTheSkies, corruptBG, crimsonBG, cTop, dayRate, EffectManager< T >.Deactivate(), desertBG, SkyManager.DrawRemainingDepth(), DrawSurfaceBG_BackMountainsStep1(), DrawSurfaceBG_BackMountainsStep2(), DrawSurfaceBG_Corrupt(), DrawSurfaceBG_Crimson(), DrawSurfaceBG_Desert(), DrawSurfaceBG_DrawChangeOverlay(), DrawSurfaceBG_Forest(), DrawSurfaceBG_GetFogPower(), DrawSurfaceBG_GoodEvilDesert(), DrawSurfaceBG_Hallow(), DrawSurfaceBG_Jungle(), DrawSurfaceBG_Mushroom(), DrawSurfaceBG_Snow(), SkyManager.DrawToDepth(), WorldGen.drunkWorldGen, gameMenu, gamePaused, hallowBG, SceneMetrics.HallowTileMax, SceneMetrics.HallowTileThreshold, SceneMetrics.HolyTileCount, SkyManager.Instance, invasionType, jungleBG, LoadBackground(), mapFullscreen, mushroomBG, Cloud.position, SkyManager.ProcessCloudAlpha(), remixWorld, WorldGen.remixWorldGen, SkyManager.ResetDepthTracker(), scAdj, Cloud.scale, screenHeight, screenOff, screenPosition, screenWidth, SetBackgroundOffsets(), snowBG, spriteBatch, treeBGSet1, treeBGSet2, treeBGSet3, treeBGSet4, treeMntBGSet1, Cloud.type, Asset< T >.Value, windSpeedCurrent, and worldSurface.
Referenced by DrawBG(), and DrawCapture().