Terraria: Main.LoadContent_Deferred
LoadContent_Deferred()
IEnumerator Main.LoadContent_Deferred () inline protected
     {
         yield return null;
         IssueReporter = new GeneralIssueReporter();
         AssetInitializer.LoadAssetsWhileInInitialBlackScreen();
         yield return null;
         bool doneLoadingMusic = false;
         IEnumerator musicLoadProcedure = LoadMusic_InSteps();
         while (!doneLoadingMusic)
         {
             try
             {
                 if (!musicLoadProcedure.MoveNext())
                 {
                     doneLoadingMusic = true;
                 }
             }
             catch
             {
                 doneLoadingMusic = true;
                 musicVolume = 0f;
                 soundVolume = 0f;
             }
             yield return null;
         }
         _musicLoaded = true;
         splashTimer.Start();
         yield return null;
         _begunMainAsyncLoad = true;
         AssetInitializer.Load(asyncLoad: true);
         _artLoaded = true;
         TownNPCHeadRenderer = new NPCHeadRenderer(TextureAssets.NpcHead);
         ContentThatNeedsRenderTargets.Add(TownNPCHeadRenderer);
         BossNPCHeadRenderer = new NPCHeadRenderer(TextureAssets.NpcHeadBoss);
         ContentThatNeedsRenderTargets.Add(BossNPCHeadRenderer);
     }
References _artLoaded, _begunMainAsyncLoad, _musicLoaded, BossNPCHeadRenderer, ContentThatNeedsRenderTargets, IssueReporter, AssetInitializer.Load(), AssetInitializer.LoadAssetsWhileInInitialBlackScreen(), LoadMusic_InSteps(), musicVolume, TextureAssets.NpcHead, TextureAssets.NpcHeadBoss, soundVolume, splashTimer, and TownNPCHeadRenderer.
Referenced by LoadContent().