Terraria: Main.DrawTwinsPet
DrawTwinsPet()
void Main.DrawTwinsPet (Projectile proj) inline private
     {
         Texture2D value = TextureAssets.Projectile[proj.type].Value;
         SpriteEffects effects = ((proj.spriteDirection != 1) ? SpriteEffects.FlipHorizontally : SpriteEffects.None);
         Microsoft.Xna.Framework.Rectangle rectangle = value.Frame(1, projFrames[proj.type], 0, proj.frame);
         Vector2 origin = rectangle.Size() / 2f;
         Vector2 vector = proj.Center - screenPosition;
         Microsoft.Xna.Framework.Color alpha = proj.GetAlpha(Lighting.GetColor(proj.Center.ToTileCoordinates()));
         float num = 18f;
         if (proj.isAPreviewDummy)
         {
             num = 8f;
         }
         Vector2 position = vector + (GlobalTimeWrappedHourly * 2f).ToRotationVector2() * num;
         EntitySpriteDraw(value, position, rectangle, alpha, proj.rotation, origin, proj.scale, effects);
         position = vector - (GlobalTimeWrappedHourly * 2f).ToRotationVector2() * num;
         rectangle = value.Frame(1, projFrames[proj.type], 0, proj.frame + 18);
         EntitySpriteDraw(value, position, rectangle, alpha, proj.rotation, origin, proj.scale, effects);
     }
References Entity.Center, EntitySpriteDraw(), Projectile.frame, Projectile.GetAlpha(), Lighting.GetColor(), GlobalTimeWrappedHourly, Projectile.isAPreviewDummy, TextureAssets.Projectile, projFrames, Projectile.rotation, Projectile.scale, screenPosition, Projectile.spriteDirection, Projectile.type, and Asset< T >.Value.
Referenced by DrawProjDirect().