Terraria: Main.DrawProj_FlailChains
DrawProj_FlailChains()
static void Main.DrawProj_FlailChains (Projectile proj, Vector2 mountedCenter) inline static private
     {
         Player player = Main.player[proj.owner];
         Vector2 playerArmPosition = GetPlayerArmPosition(proj);
         playerArmPosition -= Vector2.UnitY * player.gfxOffY;
         Asset<Texture2D> val = null;
         Microsoft.Xna.Framework.Rectangle? sourceRectangle = null;
         float num = 0f;
         switch (proj.type)
         {
         default:
             val = TextureAssets.Chain3;
             break;
         case 25:
             val = TextureAssets.Chain2;
             break;
         case 35:
             val = TextureAssets.Chain6;
             break;
         case 63:
             val = TextureAssets.Chain7;
             break;
         case 154:
             val = TextureAssets.Chain13;
             break;
         case 247:
             val = TextureAssets.Chain19;
             break;
         case 757:
             val = TextureAssets.Extra[99];
             sourceRectangle = val.Frame(1, 6);
             num = -2f;
             break;
         case 947:
             val = TextureAssets.Chain41;
             break;
         case 948:
             val = TextureAssets.Chain43;
             break;
         }
         Vector2 origin = (sourceRectangle.HasValue ? (sourceRectangle.Value.Size() / 2f) : (val.Size() / 2f));
         Vector2 center = proj.Center;
         Vector2 v = playerArmPosition.MoveTowards(center, 4f) - center;
         Vector2 vector = v.SafeNormalize(Vector2.Zero);
         float num2 = (float)(sourceRectangle.HasValue ? sourceRectangle.Value.Height : val.Height()) + num;
         float rotation = vector.ToRotation() + (float)Math.PI / 2f;
         int num3 = 0;
         float num4 = v.Length() + num2 / 2f;
         int num5 = 0;
         while (num4 > 0f)
         {
             Microsoft.Xna.Framework.Color color = Lighting.GetColor((int)center.X / 16, (int)(center.Y / 16f));
             switch (proj.type)
             {
             case 757:
                 sourceRectangle = val.Frame(1, 6, 0, num3 % 6);
                 break;
             case 948:
                 if (num5 >= 6)
                 {
                     val = (val = TextureAssets.Chain41);
                 }
                 else if (num5 >= 4)
                 {
                     val = (val = TextureAssets.Chain42);
                     byte b = 140;
                     if (color.R < b)
                     {
                         color.R = b;
                     }
                     if (color.G < b)
                     {
                         color.G = b;
                     }
                     if (color.B < b)
                     {
                         color.B = b;
                     }
                 }
                 else
                 {
                     color = Microsoft.Xna.Framework.Color.White;
                 }
                 num5++;
                 break;
             }
             spriteBatch.Draw(val.Value, center - screenPosition, sourceRectangle, color, rotation, origin, 1f, SpriteEffects.None, 0f);
             center += vector * num2;
             num3++;
             num4 -= num2;
         }
     }
References Entity.Center, TextureAssets.Chain13, TextureAssets.Chain19, TextureAssets.Chain2, TextureAssets.Chain3, TextureAssets.Chain41, TextureAssets.Chain42, TextureAssets.Chain43, TextureAssets.Chain6, TextureAssets.Chain7, TextureAssets.Extra, Lighting.GetColor(), GetPlayerArmPosition(), Player.gfxOffY, Projectile.owner, player, screenPosition, spriteBatch, Projectile.type, and Asset< T >.Value.
Referenced by DrawProjDirect().