Terraria: Main.TryGetAmmo
TryGetAmmo()
bool Main.TryGetAmmo (Item sourceItem, out Item ammoItem, out Microsoft.Xna.Framework.Color ammoColor, out float ammoScale, out Vector2 ammoOffset) inline private
     {
         ammoItem = null;
         ammoColor = Microsoft.Xna.Framework.Color.White;
         ammoScale = 0.8f;
         ammoOffset = Vector2.Zero;
         int type = sourceItem.type;
         if (type == 1071 || type == 1543 || type == 1072 || type == 1544)
         {
             int num = 22;
             int num2 = 22;
             if (type == 1072 || type == 1544)
             {
                 num = 28;
                 num2 = 28;
             }
             ammoOffset = new Vector2(num, num2);
             ammoItem = player[myPlayer].FindPaintOrCoating();
             return ammoItem != null;
         }
         FlexibleTileWand flexibleTileWand = sourceItem.GetFlexibleTileWand();
         if (flexibleTileWand != null && flexibleTileWand.TryGetPlacementOption(LocalPlayer, Player.FlexibleWandRandomSeed, Player.FlexibleWandCycleOffset, out var _, out ammoItem))
         {
             ammoOffset = new Vector2(28f, 28f);
             return true;
         }
         return false;
     }
References Player.FindPaintOrCoating(), Player.FlexibleWandCycleOffset, Player.FlexibleWandRandomSeed, Item.GetFlexibleTileWand(), LocalPlayer, myPlayer, player, FlexibleTileWand.TryGetPlacementOption(), and Item.type.
Referenced by DrawInterface_40_InteractItemIcon().