Terraria: Main.DrawNPC_SlimeItem
DrawNPC_SlimeItem()
static void Main.DrawNPC_SlimeItem (NPC rCurrentNPC, int typeCache, Microsoft.Xna.Framework.Color npcColor, float addedRotation) inline static private
     {
         int num = (int)rCurrentNPC.ai[1];
         float num2 = 1f;
         float num3 = 22f * rCurrentNPC.scale;
         float num4 = 18f * rCurrentNPC.scale;
         GetItemDrawFrame(num, out var itemTexture, out var rectangle);
         float num5 = rectangle.Width;
         float num6 = rectangle.Height;
         bool num7 = (int)rCurrentNPC.ai[0] == -999;
         if (num7)
         {
             num3 = 14f * rCurrentNPC.scale;
             num4 = 14f * rCurrentNPC.scale;
         }
         if (num5 > num3)
         {
             num2 *= num3 / num5;
             num5 *= num2;
             num6 *= num2;
         }
         if (num6 > num4)
         {
             num2 *= num4 / num6;
             num5 *= num2;
             num6 *= num2;
         }
         float num8 = -1f;
         float num9 = 1f;
         int num10 = rCurrentNPC.frame.Y / (TextureAssets.Npc[typeCache].Height() / npcFrameCount[typeCache]);
         num9 -= (float)num10;
         num8 += (float)(num10 * 2);
         float num11 = 0.2f;
         num11 -= 0.3f * (float)num10;
         if (num7)
         {
             num11 = 0f;
             num9 -= 6f;
             num8 -= num5 * addedRotation;
         }
         if (num == 75)
         {
             npcColor = new Microsoft.Xna.Framework.Color(255, 255, 255, 0);
             num11 *= 0.3f;
             num9 -= 2f;
         }
         npcColor = rCurrentNPC.GetShimmerColor(npcColor);
         spriteBatch.Draw(itemTexture, new Vector2(rCurrentNPC.Center.X - screenPosition.X + num8, rCurrentNPC.Center.Y - screenPosition.Y + rCurrentNPC.gfxOffY + num9), rectangle, npcColor, num11, rectangle.Size() / 2f, num2, SpriteEffects.None, 0f);
     }
References NPC.ai, Entity.Center, NPC.frame, GetItemDrawFrame(), NPC.GetShimmerColor(), NPC.gfxOffY, TextureAssets.Npc, npcFrameCount, NPC.scale, screenPosition, and spriteBatch.
Referenced by DrawNPCDirect().