Terraria: Main.GUIBarsDrawInner
GUIBarsDrawInner()
void Main.GUIBarsDrawInner () inline protected
     {
         ResourceSetsManager.Draw();
         spriteBatch.End();
         spriteBatch.Begin(SpriteSortMode.Deferred, BlendState.AlphaBlend, SamplerState.PointClamp, DepthStencilState.None, RasterizerState.CullCounterClockwise, null, UIScaleMatrix);
         DrawInterface_Resources_Breath();
         DrawInterface_Resources_ClearBuffs();
         if (!ingameOptionsWindow && !playerInventory && !inFancyUI)
         {
             DrawInterface_Resources_Buffs();
         }
     }
References PlayerResourceSetsManager.Draw(), DrawInterface_Resources_Breath(), DrawInterface_Resources_Buffs(), DrawInterface_Resources_ClearBuffs(), inFancyUI, ingameOptionsWindow, playerInventory, ResourceSetsManager, spriteBatch, and UIScaleMatrix.
Referenced by GUIBarsDraw().