Terraria: Main.StopSlimeRain
StopSlimeRain()
static void Main.StopSlimeRain (bool announce = true) inline static
     {
         if (!slimeRain)
         {
             return;
         }
         if (netMode == 1)
         {
             slimeRainTime = 0.0;
             slimeRain = false;
             SkyManager.Instance.Deactivate("Slime");
             return;
         }
         int num = 86400 * 7;
         if (hardMode)
         {
             num *= 2;
         }
         slimeRainTime = -rand.Next(3024, 6048) * 100;
         slimeRain = false;
         if (netMode == 0)
         {
             if (announce)
             {
                 slimeWarningTime = slimeWarningDelay;
             }
             SkyManager.Instance.Deactivate("Slime");
         }
         else if (announce)
         {
             slimeWarningTime = slimeWarningDelay;
             NetMessage.SendData(7);
         }
     }
References EffectManager< T >.Deactivate(), hardMode, SkyManager.Instance, netMode, UnifiedRandom.Next(), rand, NetMessage.SendData(), slimeRain, slimeRainTime, slimeWarningDelay, and slimeWarningTime.
Referenced by NPC.DoDeathEvents(), DrawMenu(), MessageBuffer.GetData(), and UpdateTime().