Terraria: Main.DrawInterface_38_MouseCarriedObject
DrawInterface_38_MouseCarriedObject()
void Main.DrawInterface_38_MouseCarriedObject () inline private
     {
         if (mouseItem.type > 0 && mouseItem.stack > 0)
         {
             SetMouseNPC(-1, -1);
             player[myPlayer].cursorItemIconEnabled = false;
             player[myPlayer].cursorItemIconID = 0;
             mouseText = true;
             float num = inventoryScale;
             inventoryScale = cursorScale;
             ItemSlot.Draw(spriteBatch, ref mouseItem, 21, new Vector2(mouseX, mouseY));
             inventoryScale = num;
         }
         else
         {
             if (mouseNPCType <= -1)
             {
                 return;
             }
             float num2 = 1f;
             num2 *= cursorScale;
             if (mouseNPCIndex >= 0)
             {
                 NPC nPC = npc[mouseNPCIndex];
                 if (!nPC.active || nPC.type != mouseNPCType)
                 {
                     SetMouseNPC_ToHousingQuery();
                 }
             }
             int type = mouseNPCType;
             int num3 = ((mouseNPCIndex >= 0) ? TownNPCProfiles.GetHeadIndexSafe(npc[mouseNPCIndex]) : NPC.TypeToDefaultHeadIndex(type));
             Texture2D value = TextureAssets.NpcHead[num3].Value;
             spriteBatch.Draw(value, new Vector2((float)mouseX + 26f * num2 - (float)value.Width * 0.5f * num2, (float)mouseY + 26f * num2 - (float)value.Height * 0.5f * num2), null, Microsoft.Xna.Framework.Color.White, 0f, default(Vector2), num2, SpriteEffects.None, 0f);
             if (PlayerInput.IgnoreMouseInterface)
             {
                 return;
             }
             player[myPlayer].mouseInterface = true;
             mouseText = false;
             if (mouseRight && mouseRightRelease)
             {
                 SoundEngine.PlaySound(12);
                 SetMouseNPC(-1, -1);
             }
             if (!mouseLeft || !mouseLeftRelease)
             {
                 return;
             }
             if (mouseNPCType == 0)
             {
                 PlayerInput.SetZoom_Unscaled();
                 PlayerInput.SetZoom_MouseInWorld();
                 int x = (int)(((float)mouseX + screenPosition.X) / 16f);
                 int y = (int)(((float)mouseY + screenPosition.Y) / 16f);
                 if (player[myPlayer].gravDir == -1f)
                 {
                     y = (int)((screenPosition.Y + (float)screenHeight - (float)mouseY) / 16f);
                 }
                 PlayerInput.SetZoom_Unscaled();
                 int n = -1;
                 if (WorldGen.MoveTownNPC(x, y, n))
                 {
                     NewText(Lang.inter[39].Value, byte.MaxValue, 240, 20);
                 }
                 return;
             }
             int num4 = mouseNPCIndex;
             if (num4 >= 0)
             {
                 PlayerInput.SetZoom_Unscaled();
                 PlayerInput.SetZoom_MouseInWorld();
                 int x2 = (int)(((float)mouseX + screenPosition.X) / 16f);
                 int y2 = (int)(((float)mouseY + screenPosition.Y) / 16f);
                 PlayerInput.SetZoom_Unscaled();
                 if (WorldGen.MoveTownNPC(x2, y2, num4))
                 {
                     SetMouseNPC(-1, -1);
                     WorldGen.moveRoom(x2, y2, num4);
                     SoundEngine.PlaySound(12);
                 }
             }
         }
     }
References Entity.active, Player.cursorItemIconEnabled, Player.cursorItemIconID, cursorScale, ItemSlot.Draw(), TownNPCProfiles.GetHeadIndexSafe(), PlayerInput.IgnoreMouseInterface, Lang.inter, inventoryScale, Player.mouseInterface, mouseItem, mouseLeft, mouseLeftRelease, mouseNPCIndex, mouseNPCType, mouseRight, mouseRightRelease, mouseText, mouseX, mouseY, WorldGen.moveRoom(), WorldGen.MoveTownNPC(), myPlayer, NewText(), npc, TextureAssets.NpcHead, player, SoundEngine.PlaySound(), screenHeight, screenPosition, SetMouseNPC(), SetMouseNPC_ToHousingQuery(), PlayerInput.SetZoom_MouseInWorld(), PlayerInput.SetZoom_Unscaled(), spriteBatch, Item.stack, Item.type, NPC.type, NPC.TypeToDefaultHeadIndex(), Asset< T >.Value, and LocalizedText.Value.
Referenced by SetupDrawInterfaceLayers().