Terraria: Main.DoDraw_DrawNPCsOverTiles
DoDraw_DrawNPCsOverTiles()
void Main.DoDraw_DrawNPCsOverTiles () inline private
     {
         DrawCachedProjs(DrawCacheProjsBehindNPCs);
         spriteBatch.Begin(SpriteSortMode.Deferred, BlendState.AlphaBlend, DefaultSamplerState, DepthStencilState.None, Rasterizer, null, Transform);
         try
         {
             DrawNPCs();
             DrawCachedNPCs(DrawCacheNPCProjectiles, behindTiles: false);
             TimeLogger.DetailedDrawTime(19);
         }
         catch (Exception e)
         {
             TimeLogger.DrawException(e);
         }
         spriteBatch.End();
     }
References DefaultSamplerState, TimeLogger.DetailedDrawTime(), DrawCachedNPCs(), DrawCachedProjs(), DrawCacheNPCProjectiles, DrawCacheProjsBehindNPCs, TimeLogger.DrawException(), DrawNPCs(), Rasterizer, spriteBatch, and Transform.
Referenced by DoDraw_WallsTilesNPCs().