Terraria: Main.oldDrawWater
oldDrawWater()
void Main.oldDrawWater (bool bg = false, int Style = 0, float Alpha = 1f) inline
     {
         float num = 0f;
         float num2 = 99999f;
         float num3 = 99999f;
         int num4 = -1;
         int num5 = -1;
         Vector2 vector = new Vector2(offScreenRange, offScreenRange);
         if (drawToScreen)
         {
             vector = Vector2.Zero;
         }
         _ = new Microsoft.Xna.Framework.Color[4];
         int num6 = (int)(255f * (1f - gfxQuality) + 40f * gfxQuality);
         _ = gfxQuality;
         _ = gfxQuality;
         int num7 = (int)((screenPosition.X - vector.X) / 16f - 1f);
         int num8 = (int)((screenPosition.X + (float)screenWidth + vector.X) / 16f) + 2;
         int num9 = (int)((screenPosition.Y - vector.Y) / 16f - 1f);
         int num10 = (int)((screenPosition.Y + (float)screenHeight + vector.Y) / 16f) + 5;
         if (num7 < 5)
         {
             num7 = 5;
         }
         if (num8 > maxTilesX - 5)
         {
             num8 = maxTilesX - 5;
         }
         if (num9 < 5)
         {
             num9 = 5;
         }
         if (num10 > maxTilesY - 5)
         {
             num10 = maxTilesY - 5;
         }
         for (int i = num9; i < num10 + 4; i++)
         {
             for (int j = num7 - 2; j < num8 + 2; j++)
             {
                 if (tile[j, i] == null)
                 {
                     tile[j, i] = new Tile();
                 }
                 if (tile[j, i].liquid <= 0 || (tile[j, i].nactive() && tileSolid[tile[j, i].type] && !tileSolidTop[tile[j, i].type]) || !(Lighting.Brightness(j, i) > 0f || bg))
                 {
                     continue;
                 }
                 Microsoft.Xna.Framework.Color color = Lighting.GetColor(j, i);
                 float num11 = 256 - tile[j, i].liquid;
                 num11 /= 32f;
                 bool flag = false;
                 int num12 = 0;
                 if (tile[j, i].lava())
                 {
                     if (drewLava)
                     {
                         continue;
                     }
                     float num13 = Math.Abs((float)(j * 16 + 8) - (screenPosition.X + (float)(screenWidth / 2)));
                     float num14 = Math.Abs((float)(i * 16 + 8) - (screenPosition.Y + (float)(screenHeight / 2)));
                     if (num13 < (float)(screenWidth * 2) && num14 < (float)(screenHeight * 2))
                     {
                         float num15 = (float)Math.Sqrt(num13 * num13 + num14 * num14);
                         float num16 = 1f - num15 / ((float)screenWidth * 0.75f);
                         if (num16 > 0f)
{
                             num += num16;
                         }
                     }
                     if (num13 < num2)
                     {
                         num2 = num13;
                         num4 = j * 16 + 8;
                     }
                     if (num14 < num3)
                     {
                         num3 = num13;
                         num5 = i * 16 + 8;
                     }
                     num12 = 1;
                 }
                 else if (tile[j, i].honey())
                 {
                     num12 = 11;
                 }
                 else if (tile[j, i].shimmer())
                 {
                     num12 = 14;
                     flag = true;
                 }
                 if (num12 == 0)
                 {
                     num12 = Style;
                 }
                 if ((num12 == 1 || num12 == 11) && drewLava)
                 {
                     continue;
                 }
                 float num17 = 0.5f;
                 if (bg)
                 {
                     num17 = 1f;
                 }
                 if (num12 != 1 && num12 != 11)
                 {
                     num17 *= Alpha;
                 }
                 DrawTileInWater(-screenPosition + vector, j, i);
                 Vector2 vector2 = new Vector2(j * 16, i * 16 + (int)num11 * 2);
                 Microsoft.Xna.Framework.Rectangle value = new Microsoft.Xna.Framework.Rectangle(0, 0, 16, 16 - (int)num11 * 2);
                 bool flag2 = true;
                 if (tile[j, i + 1].liquid < 245 && (!tile[j, i + 1].nactive() || !tileSolid[tile[j, i + 1].type] || tileSolidTop[tile[j, i + 1].type]))
                 {
                     float num18 = 256 - tile[j, i + 1].liquid;
                     num18 /= 32f;
                     num17 = 0.5f * (8f - num11) / 4f;
                     if ((double)num17 > 0.55)
                     {
                         num17 = 0.55f;
                     }
                     if ((double)num17 < 0.35)
                     {
                         num17 = 0.35f;
                     }
                     float num19 = num11 / 2f;
                     if (tile[j, i + 1].liquid < 200)
                     {
                         if (bg)
{
                             continue;
                         }
                         if (tile[j, i - 1].liquid > 0 && tile[j, i - 1].liquid > 0)
{
                             value = new Microsoft.Xna.Framework.Rectangle(0, 4, 16, 16);
                             num17 = 0.5f;
                         }
                         else if (tile[j, i - 1].liquid > 0)
{
                             vector2 = new Vector2(j * 16, i * 16 + 4);
                             value = new Microsoft.Xna.Framework.Rectangle(0, 4, 16, 12);
                             num17 = 0.5f;
                         }
                         else if (tile[j, i + 1].liquid > 0)
{
                             vector2 = new Vector2(j * 16, i * 16 + (int)num11 * 2 + (int)num18 * 2);
                             value = new Microsoft.Xna.Framework.Rectangle(0, 4, 16, 16 - (int)num11 * 2);
                         }
                         else
{
                             vector2 = new Vector2(j * 16 + (int)num19, i * 16 + (int)num19 * 2 + (int)num18 * 2);
                             value = new Microsoft.Xna.Framework.Rectangle(0, 4, 16 - (int)num19 * 2, 16 - (int)num19 * 2);
                         }
                     }
                     else
                     {
                         num17 = 0.5f;
                         value = new Microsoft.Xna.Framework.Rectangle(0, 4, 16, 16 - (int)num11 * 2 + (int)num18 * 2);
                     }
                 }
                 else if (tile[j, i - 1].liquid > 32)
                 {
                     value = new Microsoft.Xna.Framework.Rectangle(0, 4, value.Width, value.Height);
                 }
                 else if (num11 < 1f && tile[j, i - 1].nactive() && tileSolid[tile[j, i - 1].type] && !tileSolidTop[tile[j, i - 1].type])
                 {
                     vector2 = new Vector2(j * 16, i * 16);
                     value = new Microsoft.Xna.Framework.Rectangle(0, 4, 16, 16);
                 }
                 else
                 {
                     for (int k = i + 1; k < i + 6 && (!tile[j, k].nactive() || !tileSolid[tile[j, k].type] || tileSolidTop[tile[j, k].type]); k++)
                     {
                         if (tile[j, k].liquid < 200)
{
                             flag2 = false;
                             break;
                         }
                     }
                     if (!flag2)
                     {
                         num17 = 0.5f;
                         value = new Microsoft.Xna.Framework.Rectangle(0, 4, 16, 16);
                     }
                     else if (tile[j, i - 1].liquid > 0)
                     {
                         value = new Microsoft.Xna.Framework.Rectangle(0, 2, value.Width, value.Height);
                     }
                 }
                 if ((color.R > 20 || color.B > 20 || color.G > 20) && value.Y < 4)
                 {
                     int num20 = color.R;
                     if (color.G > num20)
                     {
                         num20 = color.G;
                     }
                     if (color.B > num20)
                     {
                         num20 = color.B;
                     }
                     num20 /= 30;
                     if (rand.Next(20000) < num20)
                     {
                         Microsoft.Xna.Framework.Color newColor = new Microsoft.Xna.Framework.Color(255, 255, 255);
                         if (tile[j, i].honey())
{
                             newColor = new Microsoft.Xna.Framework.Color(255, 255, 50);
                         }
                         int num21 = Dust.NewDust(new Vector2(j * 16, vector2.Y - 2f), 16, 8, 43, 0f, 0f, 254, newColor, 0.75f);
                         dust[num21].velocity *= 0f;
                     }
                 }
                 if (tile[j, i].honey())
                 {
                     num17 *= 1.6f;
                     if (num17 > 1f)
                     {
                         num17 = 1f;
                     }
                 }
                 if (tile[j, i].lava())
                 {
                     num17 *= 1.8f;
                     if (num17 > 1f)
                     {
                         num17 = 1f;
                     }
                     if (base.IsActive && !gamePaused && Dust.lavaBubbles < 200)
                     {
                         if (tile[j, i].liquid > 200 && rand.Next(700) == 0)
{
                             Dust.NewDust(new Vector2(j * 16, i * 16), 16, 16, 35);
                         }
                         if (value.Y == 0 && rand.Next(350) == 0)
{
                             int num22 = Dust.NewDust(new Vector2(j * 16, (float)(i * 16) + num11 * 2f - 8f), 16, 8, 35, 0f, 0f, 50, default(Microsoft.Xna.Framework.Color), 1.5f);
                             dust[num22].velocity *= 0.8f;
                             dust[num22].velocity.X *= 2f;
                             dust[num22].velocity.Y -= (float)rand.Next(1, 7) * 0.1f;
                             if (rand.Next(10) == 0)
{
                                 dust[num22].velocity.Y *= rand.Next(2, 5);
                             }
                             dust[num22].noGravity = true;
                         }
                     }
                 }
                 float num23 = (float)(int)color.R * num17;
                 float num24 = (float)(int)color.G * num17;
                 float num25 = (float)(int)color.B * num17;
                 float num26 = (float)(int)color.A * num17;
                 color = new Microsoft.Xna.Framework.Color((byte)num23, (byte)num24, (byte)num25, (byte)num26);
                 if (flag)
                 {
                     color = new Microsoft.Xna.Framework.Color(color.ToVector4() * LiquidRenderer.GetShimmerBaseColor(j, i));
                 }
                 if (Lighting.NotRetro && !bg)
                 {
                     Microsoft.Xna.Framework.Color color2 = color;
                     if (num12 != 1 && ((double)(int)color2.R > (double)num6 * 0.6 || (double)(int)color2.G > (double)num6 * 0.65 || (double)(int)color2.B > (double)num6 * 0.7))
                     {
                         for (int l = 0; l < 4; l++)
{
                             int num27 = 0;
                             int num28 = 0;
                             int width = 8;
                             int height = 8;
                             Microsoft.Xna.Framework.Color color3 = color2;
                             Microsoft.Xna.Framework.Color color4 = Lighting.GetColor(j, i);
                             if (l == 0)
{
                                 color4 = Lighting.GetColor(j - 1, i - 1);
                                 if (value.Height < 8)
{
                                     height = value.Height;
                                 }
                             }
                             if (l == 1)
{
                                 color4 = Lighting.GetColor(j + 1, i - 1);
                                 num27 = 8;
                                 if (value.Height < 8)
{
                                     height = value.Height;
                                 }
                             }
                             if (l == 2)
{
                                 color4 = Lighting.GetColor(j - 1, i + 1);
                                 num28 = 8;
                                 height = 8 - (16 - value.Height);
                             }
                             if (l == 3)
{
                                 color4 = Lighting.GetColor(j + 1, i + 1);
                                 num27 = 8;
                                 num28 = 8;
                                 height = 8 - (16 - value.Height);
                             }
                             num23 = (float)(int)color4.R * num17;
                             num24 = (float)(int)color4.G * num17;
                             num25 = (float)(int)color4.B * num17;
                             num26 = (float)(int)color4.A * num17;
                             color4 = new Microsoft.Xna.Framework.Color((byte)num23, (byte)num24, (byte)num25, (byte)num26);
                             color3.R = (byte)((color2.R * 3 + color4.R * 2) / 5);
                             color3.G = (byte)((color2.G * 3 + color4.G * 2) / 5);
                             color3.B = (byte)((color2.B * 3 + color4.B * 2) / 5);
                             color3.A = (byte)((color2.A * 3 + color4.A * 2) / 5);
                             if (flag)
{
                                 color3 = new Microsoft.Xna.Framework.Color(color3.ToVector4() * LiquidRenderer.GetShimmerBaseColor(j, i));
                             }
                             spriteBatch.Draw(TextureAssets.Liquid[num12].Value, vector2 - screenPosition + new Vector2(num27, num28) + vector, new Microsoft.Xna.Framework.Rectangle(value.X + num27, value.Y + num28, width, height), color3, 0f, default(Vector2), 1f, SpriteEffects.None, 0f);
                             if (flag)
{
                                 spriteBatch.Draw(TextureAssets.Liquid[num12].Value, vector2 - screenPosition + new Vector2(num27, num28) + vector, new Microsoft.Xna.Framework.Rectangle(value.X + num27, value.Y + num28 + 36, width, height), LiquidRenderer.GetShimmerGlitterColor(flag2, j, i), 0f, default(Vector2), 1f, SpriteEffects.None, 0f);
                             }
                         }
                     }
                     else
                     {
                         spriteBatch.Draw(TextureAssets.Liquid[num12].Value, vector2 - screenPosition + vector, value, color, 0f, default(Vector2), 1f, SpriteEffects.None, 0f);
                         if (flag)
{
                             value.Y += 36;
                             spriteBatch.Draw(TextureAssets.Liquid[num12].Value, vector2 - screenPosition + vector, value, LiquidRenderer.GetShimmerGlitterColor(flag2, j, i), 0f, default(Vector2), 1f, SpriteEffects.None, 0f);
                         }
                     }
                 }
                 else
                 {
                     if (value.Y < 4)
                     {
                         value.X += (int)(wFrame * 18f);
                     }
                     spriteBatch.Draw(TextureAssets.Liquid[num12].Value, vector2 - screenPosition + vector, value, color, 0f, default(Vector2), 1f, SpriteEffects.None, 0f);
                     if (flag)
                     {
                         value.Y += 36;
                         spriteBatch.Draw(TextureAssets.Liquid[num12].Value, vector2 - screenPosition + vector, value, LiquidRenderer.GetShimmerGlitterColor(flag2, j, i), 0f, default(Vector2), 1f, SpriteEffects.None, 0f);
                     }
                 }
                 if (!tile[j, i + 1].halfBrick())
                 {
                     continue;
                 }
                 color = Lighting.GetColor(j, i + 1);
                 num23 = (float)(int)color.R * num17;
                 num24 = (float)(int)color.G * num17;
                 num25 = (float)(int)color.B * num17;
                 num26 = (float)(int)color.A * num17;
                 color = new Microsoft.Xna.Framework.Color((byte)num23, (byte)num24, (byte)num25, (byte)num26);
                 if (flag)
                 {
                     color = new Microsoft.Xna.Framework.Color(color.ToVector4() * LiquidRenderer.GetShimmerBaseColor(j, i));
                 }
                 vector2 = new Vector2(j * 16, i * 16 + 16);
                 spriteBatch.Draw(TextureAssets.Liquid[num12].Value, vector2 - screenPosition + vector, new Microsoft.Xna.Framework.Rectangle(0, 4, 16, 8), color, 0f, default(Vector2), 1f, SpriteEffects.None, 0f);
                 if (flag)
                 {
                     spriteBatch.Draw(TextureAssets.Liquid[num12].Value, vector2 - screenPosition + vector, new Microsoft.Xna.Framework.Rectangle(0, 40, 16, 8), LiquidRenderer.GetShimmerGlitterColor(flag2, j, i), 0f, default(Vector2), 1f, SpriteEffects.None, 0f);
                 }
                 float num29 = 6f;
                 float num30 = 0.75f;
                 if (num12 == 1 || num12 == 11)
                 {
                     num29 = 4f;
                     num30 = 0.5f;
                 }
                 for (int m = 0; (float)m < num29; m++)
                 {
                     int num31 = i + 2 + m;
                     if (WorldGen.SolidTile(j, num31))
                     {
                         break;
                     }
                     float num32 = 1f - (float)m / num29;
                     num32 *= num30;
                     vector2 = new Vector2(j * 16, num31 * 16 - 2);
                     spriteBatch.Draw(TextureAssets.Liquid[num12].Value, vector2 - screenPosition + vector, new Microsoft.Xna.Framework.Rectangle(0, 18, 16, 16), color * num32, 0f, default(Vector2), 1f, SpriteEffects.None, 0f);
                     if (flag)
                     {
                         spriteBatch.Draw(TextureAssets.Liquid[num12].Value, vector2 - screenPosition + vector, new Microsoft.Xna.Framework.Rectangle(0, 54, 16, 16), LiquidRenderer.GetShimmerGlitterColor(flag2, j, i) * num32, 0f, default(Vector2), 1f, SpriteEffects.None, 0f);
                     }
                 }
             }
         }
         if (!drewLava)
         {
             ambientLavaX = num4;
             ambientLavaY = num5;
             ambientLavaStrength = num;
         }
         drewLava = true;
     }
References ambientLavaStrength, ambientLavaX, ambientLavaY, Lighting.Brightness(), DrawTileInWater(), drawToScreen, drewLava, dust, gamePaused, Lighting.GetColor(), LiquidRenderer.GetShimmerBaseColor(), LiquidRenderer.GetShimmerGlitterColor(), gfxQuality, Dust.lavaBubbles, TextureAssets.Liquid, liquid, Tile.liquid, maxTilesX, maxTilesY, Tile.nactive(), Dust.NewDust(), UnifiedRandom.Next(), Dust.noGravity, Lighting.NotRetro, offScreenRange, rand, screenHeight, screenPosition, screenWidth, WorldGen.SolidTile(), spriteBatch, Tile, tile, tileSolid, tileSolidTop, Asset< T >.Value, Dust.velocity, and wFrame.
Referenced by DrawLiquid().