Terraria: FileUtilities.Delete
Delete()
static void FileUtilities.Delete (string path, bool cloud, bool forceDeleteFile = false) inline static
     {
         if (cloud && SocialAPI.Cloud != null)
         {
             SocialAPI.Cloud.Delete(path);
         }
         else if (forceDeleteFile)
         {
             File.Delete(path);
         }
         else
         {
             Platform.Get<IPathService>().MoveToRecycleBin(path);
         }
     }
References SocialAPI.Cloud, and CloudSocialModule.Delete().
Referenced by Main.ErasePlayer(), Player.KillMeForGood(), AchievementManager.Load(), Move(), MoveToCloud(), MoveToLocal(), WorldGen.playWorldCallBack(), and WorldGen.serverLoadWorldCallBack().