Terraria: FileUtilities.Write
Write()
static void FileUtilities.Write (string path, byte[] data, int length, bool cloud) inline static
     {
         if (cloud && SocialAPI.Cloud != null)
         {
             SocialAPI.Cloud.Write(path, data, length);
             return;
         }
         string parentFolderPath = GetParentFolderPath(path);
         if (parentFolderPath != "")
         {
             Utils.TryCreatingDirectory(parentFolderPath);
         }
         RemoveReadOnlyAttribute(path);
         using FileStream fileStream = File.Open(path, FileMode.Create);
         while (fileStream.Position < length)
         {
             fileStream.Write(data, (int)fileStream.Position, Math.Min(length - (int)fileStream.Position, 2048));
         }
     }
References SocialAPI.Cloud, GetParentFolderPath(), RemoveReadOnlyAttribute(), Utils.TryCreatingDirectory(), and CloudSocialModule.Write().
Referenced by WorldFile.InternalSaveWorld(), and WriteAllBytes().