Terraria: System.Diagnostics.DiagnosticSourceEventSource.OnEventCommand
OnEventCommand()
override void System.Diagnostics.DiagnosticSourceEventSource.OnEventCommand (EventCommandEventArgs command) inline protected virtual
Reimplemented from System.Diagnostics.Tracing.EventSource.
Definition at line 987 of file DiagnosticSourceEventSource.cs.
    {
        BreakPointWithDebuggerFuncEval();
        lock (this)
        {
            if ((command.Command == EventCommand.Update || command.Command == EventCommand.Enable) && IsEnabled(EventLevel.Informational, (EventKeywords)2L))
            {
                string value = null;
                command.Arguments.TryGetValue("FilterAndPayloadSpecs", out value);
                if (!IsEnabled(EventLevel.Informational, (EventKeywords)2048L))
                {
                    if (IsEnabled(EventLevel.Informational, (EventKeywords)4096L))
                    {
                        value = NewLineSeparate(value, AspNetCoreHostingKeywordValue);
                    }
                    if (IsEnabled(EventLevel.Informational, (EventKeywords)8192L))
                    {
                        value = NewLineSeparate(value, EntityFrameworkCoreCommandsKeywordValue);
                    }
                }
                FilterAndTransform.CreateFilterAndTransformList(ref _specs, value, this);
            }
            else if (command.Command == EventCommand.Update || command.Command == EventCommand.Disable)
            {
                FilterAndTransform.DestroyFilterAndTransformList(ref _specs, this);
            }
        }
    }
References System.Diagnostics.DiagnosticSourceEventSource.FilterAndTransform.CreateFilterAndTransformList(), System.Diagnostics.DiagnosticSourceEventSource.FilterAndTransform.DestroyFilterAndTransformList(), System.L, System.Collections.Generic.Dictionary< TKey, TValue >.TryGetValue(), and System.value.