Terraria: ReturnGatePlayerRenderer.DrawReturnGateInWorld
DrawReturnGateInWorld()
void ReturnGatePlayerRenderer.DrawReturnGateInWorld (Camera camera, Player player) inline private
     {
         Rectangle homeHitbox = Rectangle.Empty;
         if (!PotionOfReturnHelper.TryGetGateHitbox(player, out homeHitbox))
         {
             return;
         }
         int num = 0;
         AHoverInteractionChecker.HoverStatus hoverStatus = AHoverInteractionChecker.HoverStatus.NotSelectable;
         if (player == Main.LocalPlayer)
         {
             _interactionChecker.AttemptInteraction(player, homeHitbox);
         }
         if (Main.SmartInteractPotionOfReturn)
         {
             hoverStatus = AHoverInteractionChecker.HoverStatus.Selected;
         }
         num = (int)hoverStatus;
         if (!player.PotionOfReturnOriginalUsePosition.HasValue)
         {
             return;
         }
         SpriteBatch spriteBatch = camera.SpriteBatch;
         SamplerState sampler = camera.Sampler;
         spriteBatch.Begin(SpriteSortMode.Immediate, BlendState.AlphaBlend, sampler, DepthStencilState.None, camera.Rasterizer, null, camera.GameViewMatrix.TransformationMatrix);
         float opacity = ((player.whoAmI == Main.myPlayer) ? 1f : 0.1f);
         Vector2 value = player.PotionOfReturnOriginalUsePosition.Value;
         Vector2 vector = new Vector2(0f, -21f);
         Vector2 worldPosition = value + vector;
         Vector2 worldPosition2 = homeHitbox.Center.ToVector2();
         PotionOfReturnGateHelper potionOfReturnGateHelper = new PotionOfReturnGateHelper(PotionOfReturnGateHelper.GateType.ExitPoint, worldPosition, opacity);
         PotionOfReturnGateHelper potionOfReturnGateHelper2 = new PotionOfReturnGateHelper(PotionOfReturnGateHelper.GateType.EntryPoint, worldPosition2, opacity);
         if (!Main.gamePaused)
         {
             potionOfReturnGateHelper.Update();
             potionOfReturnGateHelper2.Update();
         }
         _voidLensData.Clear();
         potionOfReturnGateHelper.DrawToDrawData(_voidLensData, 0);
         potionOfReturnGateHelper2.DrawToDrawData(_voidLensData, num);
         foreach (DrawData voidLensDatum in _voidLensData)
         {
             voidLensDatum.Draw(spriteBatch);
         }
         spriteBatch.End();
     }
References _interactionChecker, _voidLensData, AHoverInteractionChecker.AttemptInteraction(), DrawData.Draw(), PotionOfReturnGateHelper.DrawToDrawData(), Main.gamePaused, Camera.GameViewMatrix, Main.LocalPlayer, Main.myPlayer, Player.PotionOfReturnOriginalUsePosition, Camera.Rasterizer, Camera.Sampler, Main.SmartInteractPotionOfReturn, Camera.SpriteBatch, SpriteViewMatrix.TransformationMatrix, PotionOfReturnHelper.TryGetGateHitbox(), PotionOfReturnGateHelper.Update(), and Entity.whoAmI.
Referenced by DrawPlayer(), and DrawPlayers().