Terraria: System.Threading.Tasks.RangeWorker.FindNewWork
FindNewWork()
unsafe bool System.Threading.Tasks.RangeWorker.FindNewWork (out long nFromInclusiveLocal, out long nToExclusiveLocal) inline package
Definition at line 33 of file RangeWorker.cs.
    {
        int num = _indexRanges.Length;
        do
        {
            IndexRange indexRange = _indexRanges[_nCurrentIndexRange];
            if (indexRange._bRangeFinished == 0)
            {
                StrongBox<long> nSharedCurrentIndexOffset = _indexRanges[_nCurrentIndexRange]._nSharedCurrentIndexOffset;
                if (nSharedCurrentIndexOffset == null)
                {
                    Interlocked.CompareExchange(ref _indexRanges[_nCurrentIndexRange]._nSharedCurrentIndexOffset, new StrongBox<long>(0L), null);
                    nSharedCurrentIndexOffset = _indexRanges[_nCurrentIndexRange]._nSharedCurrentIndexOffset;
                }
                long num2;
                if (IntPtr.Size == 4 && _use32BitCurrentIndex)
                {
                    fixed (long* ptr = &nSharedCurrentIndexOffset.Value)
                    {
                        num2 = Interlocked.Add(ref *(int*)ptr, (int)_nIncrementValue) - _nIncrementValue;
                    }
                }
                else
                {
                    num2 = Interlocked.Add(ref nSharedCurrentIndexOffset.Value, _nIncrementValue) - _nIncrementValue;
                }
                if (indexRange._nToExclusive - indexRange._nFromInclusive > num2)
                {
                    nFromInclusiveLocal = indexRange._nFromInclusive + num2;
                    nToExclusiveLocal = nFromInclusiveLocal + _nIncrementValue;
                    if (nToExclusiveLocal > indexRange._nToExclusive || nToExclusiveLocal < indexRange._nFromInclusive)
                    {
                        nToExclusiveLocal = indexRange._nToExclusive;
                    }
                    if (_nIncrementValue < _nMaxIncrementValue)
                    {
                        _nIncrementValue *= 2L;
                        if (_nIncrementValue > _nMaxIncrementValue)
{
                            _nIncrementValue = _nMaxIncrementValue;
                        }
                    }
                    return true;
                }
                Interlocked.Exchange(ref _indexRanges[_nCurrentIndexRange]._bRangeFinished, 1);
            }
            _nCurrentIndexRange = (_nCurrentIndexRange + 1) % _indexRanges.Length;
            num--;
        }
        while (num > 0);
        nFromInclusiveLocal = 0L;
        nToExclusiveLocal = 0L;
        return false;
    }
References System.Threading.Tasks.IndexRange._bRangeFinished, System.Threading.Tasks.RangeWorker._indexRanges, System.Threading.Tasks.RangeWorker._nCurrentIndexRange, System.Threading.Tasks.IndexRange._nFromInclusive, System.Threading.Tasks.RangeWorker._nIncrementValue, System.Threading.Tasks.RangeWorker._nMaxIncrementValue, System.Threading.Tasks.IndexRange._nSharedCurrentIndexOffset, System.Threading.Tasks.IndexRange._nToExclusive, System.Threading.Tasks.RangeWorker._use32BitCurrentIndex, System.Threading.Interlocked.Add(), System.Threading.Interlocked.CompareExchange(), System.Threading.Interlocked.Exchange(), System.L, System.IntPtr.Size, and System.Runtime.CompilerServices.StrongBox< T >.Value.
Referenced by System.Threading.Tasks.RangeWorker.FindNewWork32().