Terraria: LogitechKeyboard.Render
Render() [2/2]
override void LogitechKeyboard.Render (IEnumerable< RgbKey > keys) inline virtual
Implements RgbKeyboard.
     {
         //IL_0018: Unknown result type (might be due to invalid IL or missing references)
         //IL_0028: Unknown result type (might be due to invalid IL or missing references)
         //IL_002d: Unknown result type (might be due to invalid IL or missing references)
         //IL_0032: Unknown result type (might be due to invalid IL or missing references)
         int listCount = 0;
         foreach (RgbKey key in keys)
         {
             if (XnaToLogitechKeys.TryGetValue(key.Key, out var value))
             {
                 Color color = ProcessLedColor(key.CurrentColor);
                 _excludedKeys[listCount++] = value;
                 NativeMethods.LogiLedSetLightingForKeyWithKeyName(value, ((Color)(ref color)).R * 100 / 255, ((Color)(ref color)).G * 100 / 255, ((Color)(ref color)).B * 100 / 255);
             }
         }
         NativeMethods.LogiLedExcludeKeysFromBitmap(_excludedKeys, listCount);
     }
References _excludedKeys, B, Color, RgbKey.CurrentColor, G, RgbKey.Key, NativeMethods.LogiLedExcludeKeysFromBitmap(), NativeMethods.LogiLedSetLightingForKeyWithKeyName(), RgbDevice.ProcessLedColor(), R, and XnaToLogitechKeys.