Terraria: System.Diagnostics.ActivitySpanId.ActivitySpanId
ActivitySpanId() [2/2]
unsafe System.Diagnostics.ActivitySpanId.ActivitySpanId (ReadOnlySpan< byte > idData) inline private
Definition at line 86 of file ActivitySpanId.cs.
    {
        if (idData.Length != 16)
        {
            throw new ArgumentOutOfRangeException("idData");
        }
        if (!Utf8Parser.TryParse(idData, out ulong value, out int _, 'x'))
        {
            _hexString = CreateRandom()._hexString;
            return;
        }
        if (BitConverter.IsLittleEndian)
        {
            value = BinaryPrimitives.ReverseEndianness(value);
        }
        _hexString = System.HexConverter.ToString(new ReadOnlySpan<byte>(&value, 8), System.HexConverter.Casing.Lower);
    }
References System.Diagnostics.ActivitySpanId._hexString, System.Diagnostics.ActivitySpanId.CreateRandom(), System.BitConverter.IsLittleEndian, System.ReadOnlySpan< T >.Length, System.Buffers.Binary.BinaryPrimitives.ReverseEndianness(), System.HexConverter.ToString(), System.Buffers.Text.Utf8Parser.TryParse(), and System.value.