Terraria: System.Linq.Enumerable.ConcatIterator.MoveNext
MoveNext()
override bool System.Linq.Enumerable.ConcatIterator< TSource >.MoveNext () inline inherited
Implements System.Collections.IEnumerator.
Definition at line 646 of file Enumerable.cs.
        {
            if (_state == 1)
            {
                _enumerator = GetEnumerable(0).GetEnumerator();
                _state = 2;
            }
            if (_state > 1)
            {
                while (true)
                {
                    if (_enumerator.MoveNext())
                    {
                        _current = _enumerator.Current;
                        return true;
                    }
                    IEnumerable<TSource> enumerable = GetEnumerable(_state++ - 1);
                    if (enumerable == null)
                    {
                        break;
                    }
                    _enumerator.Dispose();
                    _enumerator = enumerable.GetEnumerator();
                }
                Dispose();
            }
            return false;
        }
References System.Linq.Enumerable.Iterator< TSource >._current, System.Linq.Enumerable.ConcatIterator< TSource >._enumerator, System.Linq.Enumerable.Iterator< TSource >._state, System.Collections.IEnumerator.Current, System.Linq.Enumerable.ConcatIterator< TSource >.Dispose(), System.Linq.enumerable, System.Linq.Enumerable.ConcatIterator< TSource >.GetEnumerable(), System.Collections.IEnumerable.GetEnumerator(), and System.Collections.IEnumerator.MoveNext().