Terraria: System.Runtime.CompilerServices.CallSite.CreateCustomNoMatchDelegate
CreateCustomNoMatchDelegate()
T System.Runtime.CompilerServices.CallSite< T >.CreateCustomNoMatchDelegate (MethodInfo invoke) inline private
Definition at line 300 of file CallSite.cs.
    {
        ParameterExpression[] array = Array.ConvertAll(invoke.GetParametersCached(), (ParameterInfo p) => Expression.Parameter(p.ParameterType, p.Name));
        return Expression.Lambda<T>(Expression.Block(Expression.Call(typeof(CallSiteOps).GetMethod("SetNotMatched"), array[0]), Expression.Default(invoke.GetReturnType())), new TrueReadOnlyCollection<ParameterExpression>(array)).Compile();
    }
References System.array, System.Linq.Expressions.Expression< TDelegate >.Block(), System.Linq.Expressions.Expression< TDelegate >.Call(), System.Linq.Expressions.Expression< TDelegate >.Default(), System.Linq.Expressions.Expression< TDelegate >.Lambda(), System.Reflection.ParameterInfo.Name, System.Linq.Expressions.Expression< TDelegate >.Parameter(), and System.Reflection.ParameterInfo.ParameterType.
Referenced by System.Runtime.CompilerServices.CallSite< T >.MakeUpdateDelegate().