Terraria: System.Runtime.CompilerServices.CallSite.CreateCustomUpdateDelegate
CreateCustomUpdateDelegate()
T System.Runtime.CompilerServices.CallSite< T >.CreateCustomUpdateDelegate (MethodInfo invoke) inline private
Definition at line 232 of file CallSite.cs.
    {
        Type returnType = invoke.GetReturnType();
        bool flag = returnType == typeof(void);
        System.Collections.Generic.ArrayBuilder<Expression> builder = new System.Collections.Generic.ArrayBuilder<Expression>(13);
        System.Collections.Generic.ArrayBuilder<ParameterExpression> builder2 = new System.Collections.Generic.ArrayBuilder<ParameterExpression>(8 + ((!flag) ? 1 : 0));
        ParameterExpression[] array = Array.ConvertAll(invoke.GetParametersCached(), (ParameterInfo p) => Expression.Parameter(p.ParameterType, p.Name));
        LabelTarget labelTarget = Expression.Label(returnType);
        Type[] typeArguments = new Type[1] { typeof(T) };
        ParameterExpression parameterExpression = array[0];
        ParameterExpression[] array2 = array.RemoveFirst();
        ParameterExpression parameterExpression2 = Expression.Variable(typeof(CallSite<T>), "this");
        builder2.UncheckedAdd(parameterExpression2);
        builder.UncheckedAdd(Expression.Assign(parameterExpression2, Expression.Convert(parameterExpression, parameterExpression2.Type)));
        ParameterExpression parameterExpression3 = Expression.Variable(typeof(T[]), "applicable");
        builder2.UncheckedAdd(parameterExpression3);
        ParameterExpression parameterExpression4 = Expression.Variable(typeof(T), "rule");
        builder2.UncheckedAdd(parameterExpression4);
        ParameterExpression parameterExpression5 = Expression.Variable(typeof(T), "originalRule");
        builder2.UncheckedAdd(parameterExpression5);
        Expression expression = Expression.Field(parameterExpression2, typeof(CallSite<T>).GetField("Target"));
        builder.UncheckedAdd(Expression.Assign(parameterExpression5, expression));
        ParameterExpression parameterExpression6 = null;
        if (!flag)
        {
            builder2.UncheckedAdd(parameterExpression6 = Expression.Variable(labelTarget.Type, "result"));
        }
        ParameterExpression parameterExpression7 = Expression.Variable(typeof(int), "count");
        builder2.UncheckedAdd(parameterExpression7);
        ParameterExpression parameterExpression8 = Expression.Variable(typeof(int), "index");
        builder2.UncheckedAdd(parameterExpression8);
        builder.UncheckedAdd(Expression.Assign(parameterExpression, Expression.Call(CachedReflectionInfo.CallSiteOps_CreateMatchmaker.MakeGenericMethod(typeArguments), parameterExpression2)));
        Expression test = Expression.Call(CachedReflectionInfo.CallSiteOps_GetMatch, parameterExpression);
        Expression expression2 = Expression.Call(CachedReflectionInfo.CallSiteOps_ClearMatch, parameterExpression);
        Expression[] list = array;
        Expression expression3 = Expression.Invoke(parameterExpression4, new TrueReadOnlyCollection<Expression>(list));
        Expression arg = Expression.Call(CachedReflectionInfo.CallSiteOps_UpdateRules.MakeGenericMethod(typeArguments), parameterExpression2, parameterExpression8);
        Expression arg2 = ((!flag) ? Expression.Block(Expression.Assign(parameterExpression6, expression3), Expression.IfThen(test, Expression.Block(arg, Expression.Return(labelTarget, parameterExpression6)))) : Expression.Block(expression3, Expression.IfThen(test, Expression.Block(arg, Expression.Return(labelTarget)))));
        Expression expression4 = Expression.Assign(parameterExpression4, Expression.ArrayAccess(parameterExpression3, new TrueReadOnlyCollection<Expression>(parameterExpression8)));
        Expression arg3 = expression4;
        LabelTarget labelTarget2 = Expression.Label();
        Expression arg4 = Expression.IfThen(Expression.Equal(parameterExpression8, parameterExpression7), Expression.Break(labelTarget2));
        Expression expression5 = Expression.PreIncrementAssign(parameterExpression8);
        builder.UncheckedAdd(Expression.IfThen(Expression.NotEqual(Expression.Assign(parameterExpression3, Expression.Call(CachedReflectionInfo.CallSiteOps_GetRules.MakeGenericMethod(typeArguments), parameterExpression2)), Expression.Constant(null, parameterExpression3.Type)), Expression.Block(Expression.Assign(parameterExpression7, Expression.ArrayLength(parameterExpression3)), Expression.Assign(parameterExpression8, Utils.Constant(0)), Expression.Loop(Expression.Block(arg4, arg3, Expression.IfThen(Expression.NotEqual(Expression.Convert(parameterExpression4, typeof(object)), Expression.Convert(parameterExpression5, typeof(object))), Expression.Block(Expression.Assign(expression, parameterExpression4), arg2, expression2)), expression5), labelTarget2, null))));
        ParameterExpression parameterExpression9 = Expression.Variable(typeof(RuleCache<T>), "cache");
        builder2.UncheckedAdd(parameterExpression9);
        builder.UncheckedAdd(Expression.Assign(parameterExpression9, Expression.Call(CachedReflectionInfo.CallSiteOps_GetRuleCache.MakeGenericMethod(typeArguments), parameterExpression2)));
        builder.UncheckedAdd(Expression.Assign(parameterExpression3, Expression.Call(CachedReflectionInfo.CallSiteOps_GetCachedRules.MakeGenericMethod(typeArguments), parameterExpression9)));
        arg2 = ((!flag) ? Expression.Block(Expression.Assign(parameterExpression6, expression3), Expression.IfThen(test, Expression.Return(labelTarget, parameterExpression6))) : Expression.Block(expression3, Expression.IfThen(test, Expression.Return(labelTarget))));
        Expression arg5 = Expression.TryFinally(arg2, Expression.IfThen(test, Expression.Block(Expression.Call(CachedReflectionInfo.CallSiteOps_AddRule.MakeGenericMethod(typeArguments), parameterExpression2, parameterExpression4), Expression.Call(CachedReflectionInfo.CallSiteOps_MoveRule.MakeGenericMethod(typeArguments), parameterExpression9, parameterExpression4, parameterExpression8))));
        arg3 = Expression.Assign(expression, expression4);
        builder.UncheckedAdd(Expression.Assign(parameterExpression8, Utils.Constant(0)));
        builder.UncheckedAdd(Expression.Assign(parameterExpression7, Expression.ArrayLength(parameterExpression3)));
        builder.UncheckedAdd(Expression.Loop(Expression.Block(arg4, arg3, arg5, expression2, expression5), labelTarget2, null));
        builder.UncheckedAdd(Expression.Assign(parameterExpression4, Expression.Constant(null, parameterExpression4.Type)));
        ParameterExpression parameterExpression10 = Expression.Variable(typeof(object[]), "args");
        Expression[] list2 = Array.ConvertAll(array2, (ParameterExpression p) => Convert(p, typeof(object)));
        builder2.UncheckedAdd(parameterExpression10);
        builder.UncheckedAdd(Expression.Assign(parameterExpression10, Expression.NewArrayInit(typeof(object), new TrueReadOnlyCollection<Expression>(list2))));
        Expression arg6 = Expression.Assign(expression, parameterExpression5);
        arg3 = Expression.Assign(expression, Expression.Assign(parameterExpression4, Expression.Call(CachedReflectionInfo.CallSiteOps_Bind.MakeGenericMethod(typeArguments), Expression.Property(parameterExpression2, typeof(CallSite).GetProperty("Binder")), parameterExpression2, parameterExpression10)));
        arg5 = Expression.TryFinally(arg2, Expression.IfThen(test, Expression.Call(CachedReflectionInfo.CallSiteOps_AddRule.MakeGenericMethod(typeArguments), parameterExpression2, parameterExpression4)));
        builder.UncheckedAdd(Expression.Loop(Expression.Block(arg6, arg3, arg5, expression2), null, null));
        builder.UncheckedAdd(Expression.Default(labelTarget.Type));
        Expression<T> expression6 = Expression.Lambda<T>(Expression.Label(labelTarget, Expression.Block(builder2.ToReadOnly(), builder.ToReadOnly())), "CallSite.Target", tailCall: true, new TrueReadOnlyCollection<ParameterExpression>(array));
        return expression6.Compile();
    }
References System.array, System.Linq.Expressions.Expression< TDelegate >.ArrayAccess(), System.Linq.Expressions.Expression< TDelegate >.ArrayLength(), System.Linq.Expressions.Expression< TDelegate >.Assign(), System.Linq.Expressions.Expression< TDelegate >.Block(), System.Linq.Expressions.Expression< TDelegate >.Break(), System.Linq.Expressions.Expression< TDelegate >.Call(), System.Linq.Expressions.CachedReflectionInfo.CallSiteOps_AddRule, System.Linq.Expressions.CachedReflectionInfo.CallSiteOps_Bind, System.Linq.Expressions.CachedReflectionInfo.CallSiteOps_ClearMatch, System.Linq.Expressions.CachedReflectionInfo.CallSiteOps_CreateMatchmaker, System.Linq.Expressions.CachedReflectionInfo.CallSiteOps_GetCachedRules, System.Linq.Expressions.CachedReflectionInfo.CallSiteOps_GetMatch, System.Linq.Expressions.CachedReflectionInfo.CallSiteOps_GetRuleCache, System.Linq.Expressions.CachedReflectionInfo.CallSiteOps_GetRules, System.Linq.Expressions.CachedReflectionInfo.CallSiteOps_MoveRule, System.Linq.Expressions.CachedReflectionInfo.CallSiteOps_UpdateRules, System.Linq.Expressions.Utils.Constant(), System.Linq.Expressions.Expression< TDelegate >.Constant(), System.Linq.Expressions.Expression< TDelegate >.Convert(), System.Linq.Expressions.Convert, System.Linq.Expressions.Expression< TDelegate >.Default(), System.Linq.Expressions.Expression< TDelegate >.Equal(), System.Linq.Expressions.Expression< TDelegate >.Field(), System.Reflection.GetField, System.Reflection.GetProperty, System.Linq.Expressions.Expression< TDelegate >.IfThen(), System.Linq.Expressions.Expression< TDelegate >.Invoke(), System.Linq.Expressions.Expression< TDelegate >.Label(), System.Linq.Expressions.Expression< TDelegate >.Lambda(), System.list, System.Linq.Expressions.Expression< TDelegate >.Loop(), System.Reflection.ParameterInfo.Name, System.Linq.Expressions.Expression< TDelegate >.NewArrayInit(), System.Linq.Expressions.Expression< TDelegate >.NotEqual(), System.Linq.Expressions.Expression< TDelegate >.Parameter(), System.Reflection.ParameterInfo.ParameterType, System.Linq.Expressions.Expression< TDelegate >.PreIncrementAssign(), System.Linq.Expressions.Expression< TDelegate >.Property(), System.Linq.Expressions.Expression< TDelegate >.Return(), System.Linq.Expressions.Expression< TDelegate >.TryFinally(), and System.Linq.Expressions.Expression< TDelegate >.Variable().
Referenced by System.Runtime.CompilerServices.CallSite< T >.MakeUpdateDelegate().