Terraria: System.Runtime.CompilerServices.CallSite.MakeUpdateDelegate
MakeUpdateDelegate()
T System.Runtime.CompilerServices.CallSite< T >.MakeUpdateDelegate () inline package
Definition at line 177 of file CallSite.cs.
    {
        Type typeFromHandle = typeof(T);
        MethodInfo invokeMethod = typeFromHandle.GetInvokeMethod();
        if (typeFromHandle.IsGenericType && IsSimpleSignature(invokeMethod, out var sig))
        {
            MethodInfo methodInfo = null;
            MethodInfo methodInfo2 = null;
            if (invokeMethod.ReturnType == typeof(void))
            {
                if (typeFromHandle == System.Linq.Expressions.Compiler.DelegateHelpers.GetActionType(sig.AddFirst<Type>(typeof(CallSite))))
                {
                    methodInfo = typeof(UpdateDelegates).GetMethod("UpdateAndExecuteVoid" + sig.Length, BindingFlags.Static | BindingFlags.NonPublic);
                    methodInfo2 = typeof(UpdateDelegates).GetMethod("NoMatchVoid" + sig.Length, BindingFlags.Static | BindingFlags.NonPublic);
                }
            }
            else if (typeFromHandle == System.Linq.Expressions.Compiler.DelegateHelpers.GetFuncType(sig.AddFirst<Type>(typeof(CallSite))))
            {
                methodInfo = typeof(UpdateDelegates).GetMethod("UpdateAndExecute" + (sig.Length - 1), BindingFlags.Static | BindingFlags.NonPublic);
                methodInfo2 = typeof(UpdateDelegates).GetMethod("NoMatch" + (sig.Length - 1), BindingFlags.Static | BindingFlags.NonPublic);
            }
            if (methodInfo != null)
            {
                s_cachedNoMatch = (T)(object)methodInfo2.MakeGenericMethod(sig).CreateDelegate(typeFromHandle);
                return (T)(object)methodInfo.MakeGenericMethod(sig).CreateDelegate(typeFromHandle);
            }
        }
        s_cachedNoMatch = CreateCustomNoMatchDelegate(invokeMethod);
        return CreateCustomUpdateDelegate(invokeMethod);
    }
References System.Runtime.CompilerServices.CallSite< T >.CreateCustomNoMatchDelegate(), System.Runtime.CompilerServices.CallSite< T >.CreateCustomUpdateDelegate(), System.Linq.Expressions.Compiler.DelegateHelpers.GetActionType(), System.Linq.Expressions.Compiler.DelegateHelpers.GetFuncType(), System.Runtime.CompilerServices.CallSite< T >.IsSimpleSignature(), System.Runtime.CompilerServices.CallSite< T >.s_cachedNoMatch, and System.T.
Referenced by System.Runtime.CompilerServices.CallSite< T >.GetUpdateDelegate().