Terraria: System.Runtime.CompilerServices.CallSite.GetMatchmaker
GetMatchmaker()
CallSite System.Runtime.CompilerServices.CallSite< T >.GetMatchmaker () inline package
Definition at line 93 of file CallSite.cs.
    {
        CallSite callSite = _cachedMatchmaker;
        if (callSite != null)
        {
            callSite = Interlocked.Exchange(ref _cachedMatchmaker, null);
        }
        return callSite ?? new CallSite<T>
        {
            _match = true
        };
    }
References System.Runtime.CompilerServices.CallSite< T >._cachedMatchmaker, System.Runtime.CompilerServices.CallSite< T >._match, and System.Threading.Interlocked.Exchange().
Referenced by System.Dynamic.UpdateDelegates.UpdateAndExecute10< T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, TRet >(), System.Dynamic.UpdateDelegates.UpdateAndExecute1< T0, TRet >(), System.Dynamic.UpdateDelegates.UpdateAndExecute2< T0, T1, TRet >(), System.Dynamic.UpdateDelegates.UpdateAndExecute3< T0, T1, T2, TRet >(), System.Dynamic.UpdateDelegates.UpdateAndExecute4< T0, T1, T2, T3, TRet >(), System.Dynamic.UpdateDelegates.UpdateAndExecute5< T0, T1, T2, T3, T4, TRet >(), System.Dynamic.UpdateDelegates.UpdateAndExecute6< T0, T1, T2, T3, T4, T5, TRet >(), System.Dynamic.UpdateDelegates.UpdateAndExecute7< T0, T1, T2, T3, T4, T5, T6, TRet >(), System.Dynamic.UpdateDelegates.UpdateAndExecute8< T0, T1, T2, T3, T4, T5, T6, T7, TRet >(), System.Dynamic.UpdateDelegates.UpdateAndExecute9< T0, T1, T2, T3, T4, T5, T6, T7, T8, TRet >(), System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid10< T0, T1, T2, T3, T4, T5, T6, T7, T8, T9 >(), System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid1< T0 >(), System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid2< T0, T1 >(), System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3< T0, T1, T2 >(), System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid4< T0, T1, T2, T3 >(), System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid5< T0, T1, T2, T3, T4 >(), System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid6< T0, T1, T2, T3, T4, T5 >(), System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid7< T0, T1, T2, T3, T4, T5, T6 >(), System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid8< T0, T1, T2, T3, T4, T5, T6, T7 >(), and System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid9< T0, T1, T2, T3, T4, T5, T6, T7, T8 >().