Terraria: System.Data.SqlTypes.SqlDecimal.ReadXml
ReadXml()
void IXmlSerializable. System.Data.SqlTypes.SqlDecimal.ReadXml (XmlReader reader) inline
Implements System.Xml.Serialization.IXmlSerializable.
Definition at line 2189 of file SqlDecimal.cs.
    {
        string attribute = reader.GetAttribute("nil", "http://www.w3.org/2001/XMLSchema-instance");
        if (attribute != null && XmlConvert.ToBoolean(attribute))
        {
            reader.ReadElementString();
            _bStatus = (byte)(0xFEu & _bStatus);
            return;
        }
        SqlDecimal sqlDecimal = Parse(reader.ReadElementString());
        _bStatus = sqlDecimal._bStatus;
        _bLen = sqlDecimal._bLen;
        _bPrec = sqlDecimal._bPrec;
        _bScale = sqlDecimal._bScale;
        _data1 = sqlDecimal._data1;
        _data2 = sqlDecimal._data2;
        _data3 = sqlDecimal._data3;
        _data4 = sqlDecimal._data4;
    }
References System.Data.SqlTypes.SqlDecimal._bLen, System.Data.SqlTypes.SqlDecimal._bPrec, System.Data.SqlTypes.SqlDecimal._bScale, System.Data.SqlTypes.SqlDecimal._bStatus, System.Data.SqlTypes.SqlDecimal._data1, System.Data.SqlTypes.SqlDecimal._data2, System.Data.SqlTypes.SqlDecimal._data3, System.Data.SqlTypes.SqlDecimal._data4, System.Xml.Dictionary, System.Xml.XmlReader.GetAttribute(), System.Xml.Parse, System.Xml.XmlReader.ReadElementString(), and System.Xml.XmlConvert.ToBoolean().