Terraria: System.Data.SqlTypes.SqlDecimal.operator/
operator/()
static SqlDecimal System.Data.SqlTypes.SqlDecimal.operator/ (SqlDecimal x, SqlDecimal y) inline static
Definition at line 1056 of file SqlDecimal.cs.
    {
        if (x.IsNull || y.IsNull)
        {
            return Null;
        }
        if (y.FZero())
        {
            throw new DivideByZeroException(SQLResource.DivideByZeroMessage);
        }
        bool fPositive = x.IsPositive == y.IsPositive;
        int bScale = x._bScale;
        int bPrec = x._bPrec;
        int num = Math.Max(x._bScale + y._bPrec + 1, 6);
        int val = x._bPrec - x._bScale + y._bScale;
        int num2 = num + x._bPrec + y._bPrec + 1;
        int val2 = Math.Min(num, 6);
        val = Math.Min(val, 38);
        num2 = val + num;
        if (num2 > 38)
        {
            num2 = 38;
        }
        num = Math.Min(num2 - val, num);
        num = Math.Max(num, val2);
        int digits = num - x._bScale + y._bScale;
        x.AdjustScale(digits, fRound: true);
        Span<uint> span = stackalloc uint[4] { x._data1, x._data2, x._data3, x._data4 };
        Span<uint> rgulD = stackalloc uint[4] { y._data1, y._data2, y._data3, y._data4 };
        Span<uint> rgulR = stackalloc uint[5];
        Span<uint> span2 = stackalloc uint[4];
        rgulR.Clear();
        span2.Clear();
        MpDiv(span, x._bLen, rgulD, y._bLen, span2, out var ciulQ, rgulR, out var _);
        ZeroToMaxLen(span2, ciulQ);
        SqlDecimal result = new SqlDecimal(span2, (byte)ciulQ, (byte)num2, (byte)num, fPositive);
        if (result.FZero())
        {
            result.SetPositive();
        }
        return result;
    }
References System.Data.SqlTypes.SqlDecimal._bLen, System.Data.SqlTypes.SqlDecimal._bPrec, System.Data.SqlTypes.SqlDecimal._bScale, System.Data.SqlTypes.SqlDecimal._data1, System.Data.SqlTypes.SqlDecimal._data2, System.Data.SqlTypes.SqlDecimal._data3, System.Data.SqlTypes.SqlDecimal.AdjustScale(), System.Span< T >.Clear(), System.Xml.Dictionary, System.Data.SqlTypes.SQLResource.DivideByZeroMessage, System.Data.SqlTypes.SqlDecimal.FZero(), System.Data.SqlTypes.SqlDecimal.IsNull, System.Data.SqlTypes.SqlDecimal.IsPositive, System.Math.Max(), System.Math.Min(), System.Data.SqlTypes.SqlDecimal.MpDiv(), System.Data.SqlTypes.SqlDecimal.Null, System.Data.SqlTypes.SqlDecimal.SetPositive(), System.Data.Common.SqlDecimal, and System.Data.SqlTypes.SqlDecimal.ZeroToMaxLen().