Terraria: System.Data.SqlTypes.SqlDecimal.Round
Round() [1/2]
static SqlDecimal System.Data.SqlTypes.SqlDecimal.Round (SqlDecimal n, int lPosition, bool fTruncate) inline static private
Definition at line 2026 of file SqlDecimal.cs.
    {
        if (n.IsNull)
        {
            return Null;
        }
        if (lPosition >= 0)
        {
            lPosition = Math.Min(38, lPosition);
            if (lPosition >= n._bScale)
            {
                return n;
            }
        }
        else
        {
            lPosition = Math.Max(-38, lPosition);
            if (lPosition < n._bScale - n._bPrec)
            {
                n.SetToZero();
                return n;
            }
        }
        uint num = 0u;
        int num2 = Math.Abs(lPosition - n._bScale);
        uint num3 = 1u;
        while (num2 > 0)
        {
            if (num2 >= 9)
            {
                num = n.DivByULong(s_rgulShiftBase[8]);
                num3 = s_rgulShiftBase[8];
                num2 -= 9;
            }
            else
            {
                num = n.DivByULong(s_rgulShiftBase[num2 - 1]);
                num3 = s_rgulShiftBase[num2 - 1];
                num2 = 0;
            }
        }
        if (num3 > 1)
        {
            num /= num3 / 10;
        }
        if (n.FZero() && (fTruncate || num < 5))
        {
            n.SetPositive();
            return n;
        }
        if (num >= 5 && !fTruncate)
        {
            n.AddULong(1u);
        }
        num2 = Math.Abs(lPosition - n._bScale);
        while (num2-- > 0)
        {
            n.MultByULong(10u);
        }
        return n;
    }
References System.Math.Abs(), System.Xml.Dictionary, System.Math.Max(), System.Math.Min(), System.Data.SqlTypes.SqlDecimal.Null, and System.Data.SqlTypes.SqlDecimal.s_rgulShiftBase.
Referenced by System.Data.SqlTypes.SqlDecimal.Round(), and System.Data.SqlTypes.SqlDecimal.Truncate().