Terraria: System.Data.SqlTypes.SqlDecimal.SqlDecimal
SqlDecimal() [5/8]
System.Data.SqlTypes.SqlDecimal.SqlDecimal (byte bPrecision, byte bScale, bool fPositive, int[] bits) inline
Definition at line 365 of file SqlDecimal.cs.
    {
        CheckValidPrecScale(bPrecision, bScale);
        if (bits == null)
        {
            throw new ArgumentNullException("bits");
        }
        if (bits.Length != 4)
        {
            throw new ArgumentException(SQLResource.InvalidArraySizeMessage, "bits");
        }
        _bPrec = bPrecision;
        _bScale = bScale;
        _data1 = (uint)bits[0];
        _data2 = (uint)bits[1];
        _data3 = (uint)bits[2];
        _data4 = (uint)bits[3];
        _bLen = 1;
        for (int num = 3; num >= 0; num--)
        {
            if (bits[num] != 0)
            {
                _bLen = (byte)(num + 1);
                break;
            }
        }
        _bStatus = 1;
        if (!fPositive)
        {
            _bStatus |= 2;
        }
        if (FZero())
        {
            SetPositive();
        }
        if (bPrecision < CalculatePrecision())
        {
            throw new OverflowException(SQLResource.ArithOverflowMessage);
        }
    }
References System.Data.SqlTypes.SqlDecimal._bLen, System.Data.SqlTypes.SqlDecimal._bPrec, System.Data.SqlTypes.SqlDecimal._bScale, System.Data.SqlTypes.SqlDecimal._bStatus, System.Data.SqlTypes.SqlDecimal._data1, System.Data.SqlTypes.SqlDecimal._data2, System.Data.SqlTypes.SqlDecimal._data3, System.Data.SqlTypes.SqlDecimal._data4, System.Xml.ArgumentException, System.Data.SqlTypes.SQLResource.ArithOverflowMessage, System.Data.SqlTypes.SqlDecimal.CalculatePrecision(), System.Data.SqlTypes.SqlDecimal.CheckValidPrecScale(), System.Xml.Dictionary, System.Data.SqlTypes.SqlDecimal.FZero(), System.Data.SqlTypes.SQLResource.InvalidArraySizeMessage, and System.Data.SqlTypes.SqlDecimal.SetPositive().