Terraria: System.Data.SqlTypes.SqlDecimal.FGt10_38
FGt10_38() [1/2]
bool System.Data.SqlTypes.SqlDecimal.FGt10_38 () inline private
Definition at line 1210 of file SqlDecimal.cs.
    {
        if ((long)_data4 >= 1262177448L && _bLen == 4)
        {
            if ((long)_data4 <= 1262177448L && (long)_data3 <= 1518781562L)
            {
                if ((ulong)_data3 == 1518781562)
                {
                    return (long)_data2 >= 160047680L;
                }
                return false;
            }
            return true;
        }
        return false;
    }
References System.Data.SqlTypes.SqlDecimal._bLen, System.Data.SqlTypes.SqlDecimal._data2, System.Data.SqlTypes.SqlDecimal._data3, System.Data.SqlTypes.SqlDecimal._data4, and System.L.
Referenced by System.Data.SqlTypes.SqlDecimal.AddULong(), System.Data.SqlTypes.SqlDecimal.MultByULong(), System.Data.SqlTypes.SqlDecimal.operator*(), and System.Data.SqlTypes.SqlDecimal.operator+().