Terraria: System.Data.SqlTypes.SqlDecimal.FZero
FZero()
bool System.Data.SqlTypes.SqlDecimal.FZero () inline private
Definition at line 1201 of file SqlDecimal.cs.
    {
        if (_data1 == 0)
        {
            return _bLen <= 1;
        }
        return false;
    }
References System.Data.SqlTypes.SqlDecimal._bLen, and System.Data.SqlTypes.SqlDecimal._data1.
Referenced by System.Data.SqlTypes.SqlDecimal.SqlDecimal(), System.Data.SqlTypes.SqlDecimal.SqlDecimal(), System.Data.SqlTypes.SqlDecimal.SqlDecimal(), System.Data.SqlTypes.SqlDecimal.SqlDecimal(), System.Data.SqlTypes.SqlDecimal.AdjustScale(), System.Data.SqlTypes.SqlDecimal.operator*(), System.Data.SqlTypes.SqlDecimal.operator+(), System.Data.SqlTypes.SqlDecimal.operator-(), System.Data.SqlTypes.SqlDecimal.operator/(), and System.Data.SqlTypes.SqlDecimal.Parse().