Terraria: System.Data.SqlTypes.SqlDecimal.ConvertToPrecScale
ConvertToPrecScale()
static SqlDecimal System.Data.SqlTypes.SqlDecimal.ConvertToPrecScale (SqlDecimal n, int precision, int scale) inline static
Definition at line 1440 of file SqlDecimal.cs.
    {
        CheckValidPrecScale(precision, scale);
        if (n.IsNull)
        {
            return Null;
        }
        SqlDecimal result = n;
        int digits = scale - result._bScale;
        result.AdjustScale(digits, fRound: true);
        byte b = CLenFromPrec((byte)precision);
        if (b < result._bLen)
        {
            throw new SqlTruncateException();
        }
        if (b == result._bLen && precision < result.CalculatePrecision())
        {
            throw new SqlTruncateException();
        }
        result._bPrec = (byte)precision;
        return result;
    }
References System.Data.SqlTypes.SqlDecimal._bLen, System.Data.SqlTypes.SqlDecimal._bScale, System.Data.SqlTypes.SqlDecimal.AdjustScale(), System.Data.SqlTypes.SqlDecimal.CalculatePrecision(), System.Data.SqlTypes.SqlDecimal.CheckValidPrecScale(), System.Data.SqlTypes.SqlDecimal.CLenFromPrec(), System.Xml.Dictionary, and System.Data.SqlTypes.SqlDecimal.Null.