Terraria: System.Data.SqlTypes.SqlDecimal.CheckValidPrecScale
CheckValidPrecScale() [1/2]
static void System.Data.SqlTypes.SqlDecimal.CheckValidPrecScale (byte bPrec, byte bScale) inline static private
Definition at line 1743 of file SqlDecimal.cs.
    {
        if (bPrec < 1 || bPrec > MaxPrecision || bScale < 0 || bScale > MaxScale || bScale > bPrec)
        {
            throw new SqlTypeException(SQLResource.InvalidPrecScaleMessage);
        }
    }
References System.Xml.Dictionary, System.Data.SqlTypes.SQLResource.InvalidPrecScaleMessage, System.Data.SqlTypes.SqlDecimal.MaxPrecision, and System.Data.SqlTypes.SqlDecimal.MaxScale.
Referenced by System.Data.SqlTypes.SqlDecimal.SqlDecimal(), System.Data.SqlTypes.SqlDecimal.SqlDecimal(), System.Data.SqlTypes.SqlDecimal.SqlDecimal(), and System.Data.SqlTypes.SqlDecimal.ConvertToPrecScale().