Terraria: System.Data.SqlTypes.SqlDecimal.operator*
operator*()
static SqlDecimal System.Data.SqlTypes.SqlDecimal.operator* (SqlDecimal x, SqlDecimal y) inline static
Definition at line 920 of file SqlDecimal.cs.
    {
        if (x.IsNull || y.IsNull)
        {
            return Null;
        }
        int bLen = y._bLen;
        int num = x._bScale + y._bScale;
        int num2 = num;
        int num3 = x._bPrec - x._bScale + (y._bPrec - y._bScale) + 1;
        int num4 = num2 + num3;
        if (num4 > 38)
        {
            num4 = 38;
        }
        if (num2 > 38)
        {
            num2 = 38;
        }
        num2 = Math.Min(num4 - num3, num2);
        num2 = Math.Max(num2, Math.Min(num, 6));
        int num5 = num2 - num;
        bool fPositive = x.IsPositive == y.IsPositive;
        Span<uint> span = stackalloc uint[4] { x._data1, x._data2, x._data3, x._data4 };
        ReadOnlySpan<uint> readOnlySpan = span;
        span = stackalloc uint[4] { y._data1, y._data2, y._data3, y._data4 };
        ReadOnlySpan<uint> readOnlySpan2 = span;
        Span<uint> span2 = stackalloc uint[9];
        span2.Clear();
        int num6 = 0;
        for (int i = 0; i < x._bLen; i++)
        {
            uint num7 = readOnlySpan[i];
            ulong num8 = 0uL;
            num6 = i;
            for (int j = 0; j < bLen; j++)
            {
                ulong num9 = num8 + span2[num6];
                ulong num10 = readOnlySpan2[j];
                num8 = num7 * num10;
                num8 += num9;
                num9 = ((num8 >= num9) ? 0 : 4294967296uL);
                span2[num6++] = (uint)num8;
                num8 = (num8 >> 32) + num9;
            }
            if (num8 != 0L)
            {
                span2[num6++] = (uint)num8;
            }
        }
        while (span2[num6] == 0 && num6 > 0)
        {
            num6--;
        }
        int ciulU = num6 + 1;
        SqlDecimal result;
        if (num5 != 0)
        {
            if (num5 < 0)
            {
                uint num11;
                uint iulR;
                do
                {
                    if (num5 <= -9)
                    {
                        num11 = s_rgulShiftBase[8];
                        num5 += 9;
                    }
                    else
                    {
                        num11 = s_rgulShiftBase[-num5 - 1];
                        num5 = 0;
                    }
                    MpDiv1(span2, ref ciulU, num11, out iulR);
                }
                while (num5 != 0);
                if (ciulU > 4)
                {
                    throw new OverflowException(SQLResource.ArithOverflowMessage);
                }
                for (num6 = ciulU; num6 < 4; num6++)
                {
                    span2[num6] = 0u;
                }
                result = new SqlDecimal(span2, (byte)ciulU, (byte)num4, (byte)num2, fPositive);
                if (result.FGt10_38())
                {
                    throw new OverflowException(SQLResource.ArithOverflowMessage);
                }
                if (iulR >= num11 / 2)
                {
                    result.AddULong(1u);
                }
                if (result.FZero())
                {
                    result.SetPositive();
                }
                return result;
            }
            if (ciulU > 4)
            {
                throw new OverflowException(SQLResource.ArithOverflowMessage);
            }
            for (num6 = ciulU; num6 < 4; num6++)
            {
                span2[num6] = 0u;
            }
            result = new SqlDecimal(span2, (byte)ciulU, (byte)num4, (byte)num, fPositive);
            if (result.FZero())
            {
                result.SetPositive();
            }
            result.AdjustScale(num5, fRound: true);
            return result;
        }
        if (ciulU > 4)
        {
            throw new OverflowException(SQLResource.ArithOverflowMessage);
        }
        for (num6 = ciulU; num6 < 4; num6++)
        {
            span2[num6] = 0u;
        }
        result = new SqlDecimal(span2, (byte)ciulU, (byte)num4, (byte)num2, fPositive);
        if (result.FGt10_38())
        {
            throw new OverflowException(SQLResource.ArithOverflowMessage);
        }
        if (result.FZero())
        {
            result.SetPositive();
        }
        return result;
    }
References System.Data.SqlTypes.SqlDecimal._bLen, System.Data.SqlTypes.SqlDecimal._bScale, System.Data.SqlTypes.SqlDecimal._data1, System.Data.SqlTypes.SqlDecimal._data2, System.Data.SqlTypes.SqlDecimal._data3, System.Data.SqlTypes.SqlDecimal.AddULong(), System.Data.SqlTypes.SqlDecimal.AdjustScale(), System.Data.SqlTypes.SQLResource.ArithOverflowMessage, System.Span< T >.Clear(), System.Xml.Dictionary, System.Data.SqlTypes.SqlDecimal.FGt10_38(), System.Data.SqlTypes.SqlDecimal.FZero(), System.Data.SqlTypes.SqlDecimal.IsNull, System.Data.SqlTypes.SqlDecimal.IsPositive, System.L, System.Math.Max(), System.Math.Min(), System.Data.SqlTypes.SqlDecimal.MpDiv1(), System.Data.SqlTypes.SqlDecimal.Null, System.Data.SqlTypes.SqlDecimal.s_rgulShiftBase, System.Data.SqlTypes.SqlDecimal.SetPositive(), and System.Data.Common.SqlDecimal.