Terraria: System.Data.SqlTypes.SqlDecimal.operator+
operator+()
static SqlDecimal System.Data.SqlTypes.SqlDecimal.operator+ (SqlDecimal x, SqlDecimal y) inline static
Definition at line 804 of file SqlDecimal.cs.
    {
        if (x.IsNull || y.IsNull)
        {
            return Null;
        }
        bool flag = true;
        bool isPositive = x.IsPositive;
        bool flag2 = y.IsPositive;
        int bScale = x._bScale;
        int bScale2 = y._bScale;
        int num = Math.Max(x._bPrec - bScale, y._bPrec - bScale2);
        int num2 = Math.Max(bScale, bScale2);
        int val = num + num2 + 1;
        val = Math.Min(MaxPrecision, val);
        if (val - num < num2)
        {
            num2 = val - num;
        }
        if (bScale != num2)
        {
            x.AdjustScale(num2 - bScale, fRound: true);
        }
        if (bScale2 != num2)
        {
            y.AdjustScale(num2 - bScale2, fRound: true);
        }
        if (!isPositive)
        {
            isPositive = !isPositive;
            flag2 = !flag2;
            flag = !flag;
        }
        int num3 = x._bLen;
        int bLen = y._bLen;
        Span<uint> span = stackalloc uint[4] { x._data1, x._data2, x._data3, x._data4 };
        Span<uint> span2 = stackalloc uint[4] { y._data1, y._data2, y._data3, y._data4 };
        byte bLen2;
        if (flag2)
        {
            ulong num4 = 0uL;
            int i;
            for (i = 0; i < num3 || i < bLen; i++)
            {
                if (i < num3)
                {
                    num4 += span[i];
                }
                if (i < bLen)
                {
                    num4 += span2[i];
                }
                span[i] = (uint)num4;
                num4 >>= 32;
            }
            if (num4 != 0L)
            {
                if (i == 4)
                {
                    throw new OverflowException(SQLResource.ArithOverflowMessage);
                }
                span[i] = (uint)num4;
                i++;
            }
            bLen2 = (byte)i;
        }
        else
        {
            int num5 = 0;
            if (x.LAbsCmp(y) < 0)
            {
                flag = !flag;
                Span<uint> span3 = span2;
                span2 = span;
                span = span3;
                num3 = bLen;
                bLen = x._bLen;
            }
            ulong num4 = 4294967296uL;
            for (int i = 0; i < num3 || i < bLen; i++)
            {
                if (i < num3)
                {
                    num4 += span[i];
                }
                if (i < bLen)
                {
                    num4 -= span2[i];
                }
                span[i] = (uint)num4;
                if (span[i] != 0)
                {
                    num5 = i;
                }
                num4 >>= 32;
                num4 += uint.MaxValue;
            }
            bLen2 = (byte)(num5 + 1);
        }
        SqlDecimal result = new SqlDecimal(span, bLen2, (byte)val, (byte)num2, flag);
        if (result.FGt10_38() || result.CalculatePrecision() > 38)
        {
            throw new OverflowException(SQLResource.ArithOverflowMessage);
        }
        if (result.FZero())
        {
            result.SetPositive();
        }
        return result;
    }
References System.Data.SqlTypes.SqlDecimal._bLen, System.Data.SqlTypes.SqlDecimal._bPrec, System.Data.SqlTypes.SqlDecimal._bScale, System.Data.SqlTypes.SqlDecimal._data1, System.Data.SqlTypes.SqlDecimal._data2, System.Data.SqlTypes.SqlDecimal._data3, System.Data.SqlTypes.SqlDecimal.AdjustScale(), System.Data.SqlTypes.SQLResource.ArithOverflowMessage, System.Data.SqlTypes.SqlDecimal.CalculatePrecision(), System.Xml.Dictionary, System.Data.SqlTypes.SqlDecimal.FGt10_38(), System.Data.SqlTypes.SqlDecimal.FZero(), System.Data.SqlTypes.SqlDecimal.IsNull, System.Data.SqlTypes.SqlDecimal.IsPositive, System.L, System.Data.SqlTypes.SqlDecimal.LAbsCmp(), System.Math.Max(), System.Data.SqlTypes.SqlDecimal.MaxPrecision, System.Math.Min(), System.Data.SqlTypes.SqlDecimal.Null, System.Data.SqlTypes.SqlDecimal.SetPositive(), and System.Data.Common.SqlDecimal.