Terraria: System.Data.SqlTypes.SqlDecimal.AdjustScale
AdjustScale() [1/2]
void System.Data.SqlTypes.SqlDecimal.AdjustScale (int digits, bool fRound) inline package
Definition at line 1362 of file SqlDecimal.cs.
    {
        bool flag = false;
        int num = digits;
        if (num + _bScale < 0)
        {
            throw new SqlTruncateException();
        }
        if (num + _bScale > 38)
        {
            throw new OverflowException(SQLResource.ArithOverflowMessage);
        }
        byte bScale = (byte)(num + _bScale);
        byte bPrec = (byte)Math.Min(38, Math.Max(1, num + _bPrec));
        if (num > 0)
        {
            _bScale = bScale;
            _bPrec = bPrec;
            while (num > 0)
            {
                uint uiMultiplier;
                if (num >= 9)
                {
                    uiMultiplier = s_rgulShiftBase[8];
                    num -= 9;
                }
                else
                {
                    uiMultiplier = s_rgulShiftBase[num - 1];
                    num = 0;
                }
                MultByULong(uiMultiplier);
            }
        }
        else if (num < 0)
        {
            uint uiMultiplier;
            uint num2;
            do
            {
                if (num <= -9)
                {
                    uiMultiplier = s_rgulShiftBase[8];
                    num += 9;
                }
                else
                {
                    uiMultiplier = s_rgulShiftBase[-num - 1];
                    num = 0;
                }
                num2 = DivByULong(uiMultiplier);
            }
            while (num < 0);
            flag = num2 >= uiMultiplier / 2;
            _bScale = bScale;
            _bPrec = bPrec;
        }
        if (flag && fRound)
        {
            AddULong(1u);
        }
        else if (FZero())
        {
            SetPositive();
        }
    }
References System.Data.SqlTypes.SqlDecimal._bPrec, System.Data.SqlTypes.SqlDecimal._bScale, System.Data.SqlTypes.SqlDecimal.AddULong(), System.Data.SqlTypes.SQLResource.ArithOverflowMessage, System.Xml.Dictionary, System.Data.SqlTypes.SqlDecimal.DivByULong(), System.Data.SqlTypes.SqlDecimal.FZero(), System.Math.Max(), System.Math.Min(), System.Data.SqlTypes.SqlDecimal.MultByULong(), System.Data.SqlTypes.SqlDecimal.s_rgulShiftBase, and System.Data.SqlTypes.SqlDecimal.SetPositive().
Referenced by System.Data.SqlTypes.SqlDecimal.AdjustScale(), System.Data.SqlTypes.SqlDecimal.ConvertToPrecScale(), System.Data.SqlTypes.SqlInt32.operator SqlInt32(), System.Data.SqlTypes.SqlInt64.operator SqlInt64(), System.Data.SqlTypes.SqlDecimal.operator*(), System.Data.SqlTypes.SqlDecimal.operator+(), and System.Data.SqlTypes.SqlDecimal.operator/().