Terraria: System.Data.SqlTypes.SqlDecimal.SqlDecimal
SqlDecimal() [7/8]
System.Data.SqlTypes.SqlDecimal.SqlDecimal (double dVal) inline
Definition at line 453 of file SqlDecimal.cs.
        : this(fNull: false)
    {
        _bStatus = 1;
        if (dVal < 0.0)
        {
            dVal = 0.0 - dVal;
            _bStatus |= 2;
        }
        if (dVal >= 1E+38)
        {
            throw new OverflowException(SQLResource.ArithOverflowMessage);
        }
        double num = Math.Floor(dVal);
        double num2 = dVal - num;
        _bPrec = 38;
        _bLen = 1;
        if (num > 0.0)
        {
            dVal = Math.Floor(num / 4294967296.0);
            _data1 = (uint)(num - dVal * 4294967296.0);
            num = dVal;
            if (num > 0.0)
            {
                dVal = Math.Floor(num / 4294967296.0);
                _data2 = (uint)(num - dVal * 4294967296.0);
                num = dVal;
                _bLen++;
                if (num > 0.0)
                {
                    dVal = Math.Floor(num / 4294967296.0);
                    _data3 = (uint)(num - dVal * 4294967296.0);
                    num = dVal;
                    _bLen++;
                    if (num > 0.0)
                    {
                        dVal = Math.Floor(num / 4294967296.0);
                        _data4 = (uint)(num - dVal * 4294967296.0);
                        num = dVal;
                        _bLen++;
                    }
                }
            }
        }
        uint num3 = (uint)((!FZero()) ? CalculatePrecision() : 0);
        if (num3 > 17)
        {
            uint num4 = num3 - 17;
            uint num5;
            do
            {
                num5 = DivByULong(10u);
                num4--;
            }
            while (num4 != 0);
            num4 = num3 - 17;
            if (num5 >= 5)
            {
                AddULong(1u);
                num3 = CalculatePrecision() + num4;
            }
            do
            {
                MultByULong(10u);
                num4--;
            }
            while (num4 != 0);
        }
        _bScale = (byte)((num3 < 17) ? (17 - num3) : 0u);
        _bPrec = (byte)(num3 + _bScale);
        if (_bScale > 0)
        {
            num3 = _bScale;
            do
            {
                uint num6 = ((num3 >= 9) ? 9u : num3);
                num2 *= (double)s_rgulShiftBase[num6 - 1];
                num3 -= num6;
                MultByULong(s_rgulShiftBase[num6 - 1]);
                AddULong((uint)num2);
                num2 -= Math.Floor(num2);
            }
            while (num3 != 0);
        }
        if (num2 >= 0.5)
        {
            AddULong(1u);
        }
        if (FZero())
        {
            SetPositive();
        }
    }
References System.Data.SqlTypes.SqlDecimal._bLen, System.Data.SqlTypes.SqlDecimal._bPrec, System.Data.SqlTypes.SqlDecimal._bScale, System.Data.SqlTypes.SqlDecimal._bStatus, System.Data.SqlTypes.SqlDecimal._data1, System.Data.SqlTypes.SqlDecimal._data2, System.Data.SqlTypes.SqlDecimal._data3, System.Data.SqlTypes.SqlDecimal._data4, System.Data.SqlTypes.SqlDecimal.AddULong(), System.Data.SqlTypes.SQLResource.ArithOverflowMessage, System.Data.SqlTypes.SqlDecimal.CalculatePrecision(), System.Xml.Dictionary, System.Data.SqlTypes.SqlDecimal.DivByULong(), System.E, System.Math.Floor(), System.Data.SqlTypes.SqlDecimal.FZero(), System.Data.SqlTypes.SqlDecimal.MultByULong(), System.Data.SqlTypes.SqlDecimal.s_rgulShiftBase, and System.Data.SqlTypes.SqlDecimal.SetPositive().