Terraria: System.Data.SqlTypes.SqlDecimal.Null
Null
readonly SqlDecimal System.Data.SqlTypes.SqlDecimal.Null = new SqlDecimal(fNull: true) static
Definition at line 66 of file SqlDecimal.cs.
Referenced by System.Data.SqlTypes.SqlDecimal.Abs(), System.Data.SqlTypes.SqlDecimal.AdjustScale(), System.Data.SqlTypes.SqlDecimal.Ceiling(), System.Data.SqlTypes.SqlDecimal.ConvertToPrecScale(), System.Data.Common.SqlConvert.ConvertToSqlDecimal(), System.Data.SqlTypes.SqlDecimal.Floor(), System.Data.SqlTypes.SqlDecimal.operator SqlDecimal(), System.Data.SqlTypes.SqlDecimal.operator SqlDecimal(), System.Data.SqlTypes.SqlDecimal.operator SqlDecimal(), System.Data.SqlTypes.SqlDecimal.operator SqlDecimal(), System.Data.SqlTypes.SqlDecimal.operator SqlDecimal(), System.Data.SqlTypes.SqlDecimal.operator SqlDecimal(), System.Data.SqlTypes.SqlDecimal.operator SqlDecimal(), System.Data.SqlTypes.SqlDecimal.operator SqlDecimal(), System.Data.SqlTypes.SqlDecimal.operator SqlDecimal(), System.Data.SqlTypes.SqlDecimal.operator*(), System.Data.SqlTypes.SqlDecimal.operator+(), System.Data.SqlTypes.SqlDecimal.operator-(), System.Data.SqlTypes.SqlDecimal.operator/(), System.Data.SqlTypes.SqlDecimal.Parse(), System.Data.SqlTypes.SqlDecimal.Power(), and System.Data.SqlTypes.SqlDecimal.Round().