Terraria: System.Data.SqlTypes.SqlDecimal.ToDouble
ToDouble()
double System.Data.SqlTypes.SqlDecimal.ToDouble () inline
Definition at line 734 of file SqlDecimal.cs.
    {
        if (IsNull)
        {
            throw new SqlNullValueException();
        }
        double num = 0.0;
        num = _data4;
        num = num * 4294967296.0 + (double)_data3;
        num = num * 4294967296.0 + (double)_data2;
        num = num * 4294967296.0 + (double)_data1;
        num /= Math.Pow(10.0, (int)_bScale);
        if (!IsPositive)
        {
            return 0.0 - num;
        }
        return num;
    }
References System.Data.SqlTypes.SqlDecimal._bScale, System.Data.SqlTypes.SqlDecimal._data1, System.Data.SqlTypes.SqlDecimal._data2, System.Data.SqlTypes.SqlDecimal._data3, System.Data.SqlTypes.SqlDecimal._data4, System.Data.SqlTypes.SqlDecimal.IsNull, System.Data.SqlTypes.SqlDecimal.IsPositive, and System.Math.Pow().
Referenced by System.Data.SqlTypes.SqlDouble.operator SqlDouble(), and System.Data.SqlTypes.SqlSingle.operator SqlSingle().