Terraria: System.Data.SqlTypes.SqlDecimal.MpDiv
MpDiv()
static void System.Data.SqlTypes.SqlDecimal.MpDiv (ReadOnlySpan< uint > rgulU, int ciulU, Span< uint > rgulD, int ciulD, Span< uint > rgulQ, out int ciulQ, Span< uint > rgulR, out int ciulR) inline static private
Definition at line 1568 of file SqlDecimal.cs.
    {
        if (ciulD == 1 && rgulD[0] == 0)
        {
            ciulQ = (ciulR = 0);
            return;
        }
        if (ciulU == 1 && ciulD == 1)
        {
            MpSet(rgulQ, out ciulQ, rgulU[0] / rgulD[0]);
            MpSet(rgulR, out ciulR, rgulU[0] % rgulD[0]);
            return;
        }
        if (ciulD > ciulU)
        {
            MpMove(rgulU, ciulU, rgulR, out ciulR);
            MpSet(rgulQ, out ciulQ, 0u);
            return;
        }
        if (ciulU <= 2)
        {
            ulong num = DWL(rgulU[0], rgulU[1]);
            ulong num2 = rgulD[0];
            if (ciulD > 1)
            {
                num2 += (ulong)rgulD[1] << 32;
            }
            ulong x = num / num2;
            rgulQ[0] = LO(x);
            rgulQ[1] = HI(x);
            ciulQ = ((HI(x) == 0) ? 1 : 2);
            x = num % num2;
            rgulR[0] = LO(x);
            rgulR[1] = HI(x);
            ciulR = ((HI(x) == 0) ? 1 : 2);
            return;
        }
        if (ciulD == 1)
        {
            MpMove(rgulU, ciulU, rgulQ, out ciulQ);
            MpDiv1(rgulQ, ref ciulQ, rgulD[0], out var iulR);
            rgulR[0] = iulR;
            ciulR = 1;
            return;
        }
        ciulQ = (ciulR = 0);
        if (rgulU != rgulR)
        {
            MpMove(rgulU, ciulU, rgulR, out ciulR);
        }
        ciulQ = ciulU - ciulD + 1;
        uint num3 = rgulD[ciulD - 1];
        rgulR[ciulU] = 0u;
        int num4 = ciulU;
        uint num5 = (uint)(4294967296uL / (ulong)((long)num3 + 1L));
        if (num5 > 1)
        {
            MpMul1(rgulD, ref ciulD, num5);
            num3 = rgulD[ciulD - 1];
            MpMul1(rgulR, ref ciulR, num5);
        }
        uint num6 = rgulD[ciulD - 2];
        do
        {
            ulong num7 = DWL(rgulR[num4 - 1], rgulR[num4]);
            uint num8 = (uint)((num3 != rgulR[num4]) ? (num7 / num3) : uint.MaxValue);
            ulong num9 = num8;
            uint num10 = (uint)(num7 - num9 * num3);
            while (num6 * num9 > DWL(rgulR[num4 - 2], num10))
            {
                num8--;
                if (num10 >= 0 - num3)
                {
                    break;
                }
                num10 += num3;
                num9 = num8;
            }
            num7 = 4294967296uL;
            ulong num11 = 0uL;
            int num12 = 0;
            int num13 = num4 - ciulD;
            while (num12 < ciulD)
            {
                ulong num14 = rgulD[num12];
                num11 += num8 * num14;
                num7 += (ulong)((long)rgulR[num13] - (long)LO(num11));
                num11 = HI(num11);
                rgulR[num13] = LO(num7);
                num7 = (ulong)((long)HI(num7) + 4294967296L - 1);
                num12++;
                num13++;
            }
            num7 += rgulR[num13] - num11;
            rgulR[num13] = LO(num7);
            rgulQ[num4 - ciulD] = num8;
            if (HI(num7) == 0)
            {
                rgulQ[num4 - ciulD] = num8 - 1;
                uint num15 = 0u;
                num12 = 0;
                num13 = num4 - ciulD;
                while (num12 < ciulD)
                {
                    num7 = (ulong)((long)rgulD[num12] + (long)rgulR[num13] + num15);
                    num15 = HI(num7);
                    rgulR[num13] = LO(num7);
                    num12++;
                    num13++;
                }
                rgulR[num13] += num15;
            }
            num4--;
        }
        while (num4 >= ciulD);
        MpNormalize(rgulQ, ref ciulQ);
        ciulR = ciulD;
        MpNormalize(rgulR, ref ciulR);
        if (num5 > 1)
        {
            MpDiv1(rgulD, ref ciulD, num5, out var iulR2);
            MpDiv1(rgulR, ref ciulR, num5, out iulR2);
        }
    }
References System.Xml.Dictionary, System.Data.SqlTypes.SqlDecimal.DWL(), System.Data.SqlTypes.SqlDecimal.HI(), System.L, System.Data.SqlTypes.SqlDecimal.LO(), System.Data.SqlTypes.SqlDecimal.MpDiv1(), System.Data.SqlTypes.SqlDecimal.MpMove(), System.Data.SqlTypes.SqlDecimal.MpMul1(), System.Data.SqlTypes.SqlDecimal.MpNormalize(), and System.Data.SqlTypes.SqlDecimal.MpSet().
Referenced by System.Data.SqlTypes.SqlDecimal.operator/().