Terraria: System.Data.SqlTypes.SqlDecimal.MpDiv1
MpDiv1()
static void System.Data.SqlTypes.SqlDecimal.MpDiv1 (Span< uint > rgulU, ref int ciulU, uint iulD, out uint iulR) inline static private
Definition at line 1537 of file SqlDecimal.cs.
    {
        uint num = 0u;
        ulong num2 = iulD;
        int num3 = ciulU;
        while (num3 > 0)
        {
            num3--;
            ulong num4 = ((ulong)num << 32) + rgulU[num3];
            rgulU[num3] = (uint)(num4 / num2);
            num = (uint)(num4 - rgulU[num3] * num2);
        }
        iulR = num;
        MpNormalize(rgulU, ref ciulU);
    }
References System.Xml.Dictionary, and System.Data.SqlTypes.SqlDecimal.MpNormalize().
Referenced by System.Data.SqlTypes.SqlDecimal.MpDiv(), System.Data.SqlTypes.SqlDecimal.operator*(), and System.Data.SqlTypes.SqlDecimal.ToString().