Terraria: System.Data.SqlTypes.SqlDecimal.CompareNm
CompareNm()
EComparison System.Data.SqlTypes.SqlDecimal.CompareNm (SqlDecimal snumOp) inline private
Definition at line 1693 of file SqlDecimal.cs.
    {
        int num = (IsPositive ? 1 : (-1));
        int num2 = (snumOp.IsPositive ? 1 : (-1));
        if (num != num2)
        {
            if (num != 1)
            {
                return EComparison.LT;
            }
            return EComparison.GT;
        }
        SqlDecimal sqlDecimal = this;
        SqlDecimal snumOp2 = snumOp;
        int num3 = _bScale - snumOp._bScale;
        if (num3 < 0)
        {
            try
            {
                sqlDecimal.AdjustScale(-num3, fRound: true);
            }
            catch (OverflowException)
            {
                return (num > 0) ? EComparison.GT : EComparison.LT;
            }
        }
        else if (num3 > 0)
        {
            try
            {
                snumOp2.AdjustScale(num3, fRound: true);
            }
            catch (OverflowException)
            {
                return (num <= 0) ? EComparison.GT : EComparison.LT;
            }
        }
        int num4 = sqlDecimal.LAbsCmp(snumOp2);
        if (num4 == 0)
        {
            return EComparison.EQ;
        }
        int num5 = num * num4;
        if (num5 < 0)
        {
            return EComparison.LT;
        }
        return EComparison.GT;
    }
References System.Data.SqlTypes.SqlDecimal._bScale, System.Xml.Dictionary, and System.Data.SqlTypes.SqlDecimal.IsPositive.
Referenced by System.Data.SqlTypes.SqlDecimal.operator<(), System.Data.SqlTypes.SqlDecimal.operator<=(), System.Data.SqlTypes.SqlDecimal.operator==(), System.Data.SqlTypes.SqlDecimal.operator>(), and System.Data.SqlTypes.SqlDecimal.operator>=().