Terraria: System.Data.SqlTypes.SqlDecimal.CalculatePrecision
CalculatePrecision()
byte System.Data.SqlTypes.SqlDecimal.CalculatePrecision () inline private
Definition at line 200 of file SqlDecimal.cs.
    {
        uint[] array;
        uint num2;
        int num;
        if (_data4 != 0)
        {
            num = 33;
            array = s_decimalHelpersHiHi;
            num2 = _data4;
        }
        else if (_data3 != 0)
        {
            num = 24;
            array = s_decimalHelpersHi;
            num2 = _data3;
        }
        else if (_data2 != 0)
        {
            num = 15;
            array = s_decimalHelpersMid;
            num2 = _data2;
        }
        else
        {
            num = 5;
            array = s_decimalHelpersLo;
            num2 = _data1;
        }
        if (num2 < array[num])
        {
            num -= 2;
            if (num2 < array[num])
            {
                num -= 2;
                num = ((num2 >= array[num]) ? (num + 1) : (num - 1));
            }
            else
            {
                num++;
            }
        }
        else
        {
            num += 2;
            num = ((num2 >= array[num]) ? (num + 1) : (num - 1));
        }
        if (num2 >= array[num])
        {
            num++;
            if (num == 37 && num2 >= array[num])
            {
                num++;
            }
        }
        byte b = (byte)(num + 1);
        if (b > 1 && VerifyPrecision((byte)(b - 1)))
        {
            b--;
        }
        return Math.Max(b, _bScale);
    }
References System.Data.SqlTypes.SqlDecimal._bScale, System.Data.SqlTypes.SqlDecimal._data1, System.Data.SqlTypes.SqlDecimal._data2, System.Data.SqlTypes.SqlDecimal._data3, System.Data.SqlTypes.SqlDecimal._data4, System.array, System.Xml.Dictionary, System.Math.Max(), System.Data.SqlTypes.SqlDecimal.s_decimalHelpersHi, System.Data.SqlTypes.SqlDecimal.s_decimalHelpersHiHi, System.Data.SqlTypes.SqlDecimal.s_decimalHelpersLo, System.Data.SqlTypes.SqlDecimal.s_decimalHelpersMid, and System.Data.SqlTypes.SqlDecimal.VerifyPrecision().
Referenced by System.Data.SqlTypes.SqlDecimal.SqlDecimal(), System.Data.SqlTypes.SqlDecimal.SqlDecimal(), System.Data.SqlTypes.SqlDecimal.SqlDecimal(), System.Data.SqlTypes.SqlDecimal.SqlDecimal(), System.Data.SqlTypes.SqlDecimal.ConvertToPrecScale(), System.Data.SqlTypes.SqlDecimal.GetHashCode(), and System.Data.SqlTypes.SqlDecimal.operator+().