Terraria: System.Data.SqlTypes.SqlDecimal.CompareTo
CompareTo() [1/3]
int System.Data.SqlTypes.SqlDecimal.CompareTo (object? value) inline
Implements System.IComparable< in T >.
Definition at line 2112 of file SqlDecimal.cs.
    {
        if (value is SqlDecimal value2)
        {
            return CompareTo(value2);
        }
        throw ADP.WrongType(value.GetType(), typeof(SqlDecimal));
    }
References System.Data.SqlTypes.SqlDecimal.CompareTo(), System.Xml.Dictionary, System.value, and System.Data.Common.ADP.WrongType().
Referenced by System.Data.Common.SqlDecimalStorage.Compare(), System.Data.SqlTypes.SqlDecimal.CompareTo(), and System.Data.Common.SqlDecimalStorage.CompareValueTo().