Terraria: System.Data.SqlTypes.SqlDecimal.AddULong
AddULong()
void System.Data.SqlTypes.SqlDecimal.AddULong (uint ulAdd) inline private
Definition at line 1265 of file SqlDecimal.cs.
    {
        ulong num = ulAdd;
        int bLen = _bLen;
        Span<uint> span = stackalloc uint[4] { _data1, _data2, _data3, _data4 };
        int num2 = 0;
        do
        {
            num += span[num2];
            span[num2] = (uint)num;
            num >>= 32;
            if (num == 0L)
            {
                StoreFromWorkingArray(span);
                return;
            }
            num2++;
        }
        while (num2 < bLen);
        if (num2 == 4)
        {
            throw new OverflowException(SQLResource.ArithOverflowMessage);
        }
        span[num2] = (uint)num;
        _bLen++;
        if (FGt10_38(span))
        {
            throw new OverflowException(SQLResource.ArithOverflowMessage);
        }
        StoreFromWorkingArray(span);
    }
References System.Data.SqlTypes.SqlDecimal._bLen, System.Data.SqlTypes.SqlDecimal._data1, System.Data.SqlTypes.SqlDecimal._data2, System.Data.SqlTypes.SqlDecimal._data3, System.Data.SqlTypes.SqlDecimal._data4, System.Data.SqlTypes.SQLResource.ArithOverflowMessage, System.Xml.Dictionary, System.Data.SqlTypes.SqlDecimal.FGt10_38(), System.L, and System.Data.SqlTypes.SqlDecimal.StoreFromWorkingArray().
Referenced by System.Data.SqlTypes.SqlDecimal.SqlDecimal(), System.Data.SqlTypes.SqlDecimal.AdjustScale(), and System.Data.SqlTypes.SqlDecimal.operator*().