Terraria: System.Data.SqlTypes.SqlDecimal.ToString
ToString()
override string System.Data.SqlTypes.SqlDecimal.ToString () inline
Definition at line 578 of file SqlDecimal.cs.
    {
        if (IsNull)
        {
            return SQLResource.NullString;
        }
        Span<uint> rgulU = stackalloc uint[4] { _data1, _data2, _data3, _data4 };
        int ciulU = _bLen;
        Span<char> span = stackalloc char[39];
        span.Clear();
        int num = 0;
        while (ciulU > 1 || rgulU[0] != 0)
        {
            MpDiv1(rgulU, ref ciulU, 10u, out var iulR);
            span[num++] = ChFromDigit(iulR);
        }
        while (num <= _bScale)
        {
            span[num++] = ChFromDigit(0u);
        }
        int num2 = 0;
        int num3 = 0;
        if (_bScale > 0)
        {
            num2 = 1;
        }
        char[] array;
        if (IsPositive)
        {
            array = new char[num2 + num];
        }
        else
        {
            array = new char[num2 + num + 1];
            array[num3++] = '-';
        }
        while (num > 0)
        {
            if (num-- == _bScale)
            {
                array[num3++] = '.';
            }
            array[num3++] = span[num];
        }
        return new string(array);
    }
References System.Data.SqlTypes.SqlDecimal._bLen, System.Data.SqlTypes.SqlDecimal._bScale, System.Data.SqlTypes.SqlDecimal._data1, System.Data.SqlTypes.SqlDecimal._data2, System.Data.SqlTypes.SqlDecimal._data3, System.Data.SqlTypes.SqlDecimal._data4, System.array, System.Data.SqlTypes.SqlDecimal.ChFromDigit(), System.Span< T >.Clear(), System.Xml.Dictionary, System.Data.SqlTypes.SqlDecimal.IsNull, System.Data.SqlTypes.SqlDecimal.IsPositive, System.Data.SqlTypes.SqlDecimal.MpDiv1(), and System.Data.SqlTypes.SQLResource.NullString.
Referenced by System.Data.SqlTypes.SqlString.operator SqlString(), and System.Data.SqlTypes.SqlDecimal.WriteXml().