Terraria: System.Threading.PortableThreadPool.WaitThread.UnregisterWait
UnregisterWait() [2/2]
void System.Threading.PortableThreadPool.WaitThread.UnregisterWait (RegisteredWaitHandle handle, bool blocking) inline private
Definition at line 958 of file PortableThreadPool.cs.
        {
            bool flag = false;
            PortableThreadPool threadPoolInstance = ThreadPoolInstance;
            threadPoolInstance._waitThreadLock.Acquire();
            try
            {
                if (Array.IndexOf(_registeredWaits, handle) != -1)
                {
                    if (Array.IndexOf(_pendingRemoves, handle) == -1)
                    {
                        _pendingRemoves[_numPendingRemoves++] = handle;
                        _changeHandlesEvent.Set();
                    }
                    flag = true;
                }
            }
            finally
            {
                threadPoolInstance._waitThreadLock.Release();
            }
            if (blocking)
            {
                if (handle.IsBlocking)
                {
                    handle.WaitForCallbacks();
                }
                else if (flag)
                {
                    handle.WaitForRemoval();
                }
            }
        }
References System.Threading.PortableThreadPool.WaitThread._changeHandlesEvent, System.Threading.PortableThreadPool.WaitThread._numPendingRemoves, System.Threading.PortableThreadPool.WaitThread._pendingRemoves, System.Threading.PortableThreadPool.WaitThread._registeredWaits, System.Threading.PortableThreadPool._waitThreadLock, System.Threading.LowLevelLock.Acquire(), System.handle, System.Array.IndexOf(), System.Threading.LowLevelLock.Release(), System.Threading.EventWaitHandle.Set(), and System.Threading.PortableThreadPool.ThreadPoolInstance.