Terraria: System.Threading.PortableThreadPool.WaitThread.ProcessRemovals
ProcessRemovals()
int System.Threading.PortableThreadPool.WaitThread.ProcessRemovals () inline private
Definition at line 873 of file PortableThreadPool.cs.
        {
            PortableThreadPool threadPoolInstance = ThreadPoolInstance;
            threadPoolInstance._waitThreadLock.Acquire();
            try
            {
                if (_numPendingRemoves == 0 || _numUserWaits == 0)
                {
                    return _numUserWaits;
                }
                int numUserWaits = _numUserWaits;
                int numPendingRemoves = _numPendingRemoves;
                for (int i = 0; i < _numPendingRemoves; i++)
                {
                    RegisteredWaitHandle registeredWaitHandle = _pendingRemoves[i];
                    int numUserWaits2 = _numUserWaits;
                    int j;
                    for (j = 0; j < numUserWaits2 && registeredWaitHandle != _registeredWaits[j]; j++)
                    {
                    }
                    registeredWaitHandle.OnRemoveWait();
                    if (j + 1 < numUserWaits2)
                    {
                        int num = j;
                        int num2 = numUserWaits2;
                        Array.Copy(_registeredWaits, num + 1, _registeredWaits, num, num2 - (num + 1));
                        _registeredWaits[num2 - 1] = null;
                        num++;
                        num2++;
                        Array.Copy(_waitHandles, num + 1, _waitHandles, num, num2 - (num + 1));
                        _waitHandles[num2 - 1] = null;
                    }
                    else
                    {
                        _registeredWaits[j] = null;
                        _waitHandles[j + 1] = null;
                    }
                    _numUserWaits = numUserWaits2 - 1;
                    _pendingRemoves[i] = null;
                    registeredWaitHandle.Handle.DangerousRelease();
                }
                _numPendingRemoves = 0;
                return _numUserWaits;
            }
            finally
            {
                threadPoolInstance._waitThreadLock.Release();
            }
        }
References System.Threading.PortableThreadPool.WaitThread._numPendingRemoves, System.Threading.PortableThreadPool.WaitThread._numUserWaits, System.Threading.PortableThreadPool.WaitThread._pendingRemoves, System.Threading.PortableThreadPool.WaitThread._registeredWaits, System.Threading.PortableThreadPool.WaitThread._waitHandles, System.Threading.PortableThreadPool._waitThreadLock, System.Threading.LowLevelLock.Acquire(), System.Array.Copy(), System.Runtime.InteropServices.SafeHandle.DangerousRelease(), System.Threading.RegisteredWaitHandle.Handle, System.Threading.RegisteredWaitHandle.OnRemoveWait(), System.Threading.LowLevelLock.Release(), and System.Threading.PortableThreadPool.ThreadPoolInstance.
Referenced by System.Threading.PortableThreadPool.WaitThread.WaitThreadStart().