Terraria: System.Threading.PortableThreadPool.WaitThread.WaitThreadStart
WaitThreadStart()
void System.Threading.PortableThreadPool.WaitThread.WaitThreadStart () inline private
Definition at line 810 of file PortableThreadPool.cs.
        {
            while (true)
            {
                int num = ProcessRemovals();
                int tickCount = Environment.TickCount;
                int num2 = -1;
                if (num == 0)
                {
                    num2 = 20000;
                }
                else
                {
                    for (int i = 0; i < num; i++)
                    {
                        RegisteredWaitHandle registeredWaitHandle = _registeredWaits[i];
                        if (!registeredWaitHandle.IsInfiniteTimeout)
{
                            int num3 = Math.Max(0, registeredWaitHandle.TimeoutTimeMs - tickCount);
                            num2 = ((num2 != -1) ? Math.Min(num3, num2) : num3);
                            if (num2 == 0)
{
                                break;
                            }
                        }
                    }
                }
                int num4 = WaitHandle.WaitAny(new ReadOnlySpan<SafeWaitHandle>(_waitHandles, 0, num + 1), num2);
                if (num4 >= 128 && num4 < 129 + num)
                {
                    num4 += -128;
                }
                switch (num4)
                {
                case 0:
                    break;
                default:
                {
                    RegisteredWaitHandle registeredHandle = _registeredWaits[num4 - 1];
                    QueueWaitCompletion(registeredHandle, timedOut: false);
                    break;
                }
                case 258:
                {
                    if (num == 0 && ThreadPoolInstance.TryRemoveWaitThread(this))
                    {
                        return;
                    }
                    tickCount = Environment.TickCount;
                    for (int j = 0; j < num; j++)
                    {
                        RegisteredWaitHandle registeredWaitHandle2 = _registeredWaits[j];
                        if (!registeredWaitHandle2.IsInfiniteTimeout && tickCount - registeredWaitHandle2.TimeoutTimeMs >= 0)
{
                            QueueWaitCompletion(registeredWaitHandle2, timedOut: true);
                        }
                    }
                    break;
                }
                }
            }
        }
References System.Threading.PortableThreadPool.WaitThread._registeredWaits, System.Threading.PortableThreadPool.WaitThread._waitHandles, System.Threading.RegisteredWaitHandle.IsInfiniteTimeout, System.Math.Max(), System.Math.Min(), System.Threading.PortableThreadPool.WaitThread.ProcessRemovals(), System.Threading.PortableThreadPool.WaitThread.QueueWaitCompletion(), System.Threading.PortableThreadPool.ThreadPoolInstance, System.Environment.TickCount, System.Threading.RegisteredWaitHandle.TimeoutTimeMs, and System.Threading.WaitHandle.WaitAny().
Referenced by System.Threading.PortableThreadPool.WaitThread.WaitThread().