Terraria: System.Threading.PortableThreadPool.WaitThread.QueueWaitCompletion
QueueWaitCompletion()
void System.Threading.PortableThreadPool.WaitThread.QueueWaitCompletion (RegisteredWaitHandle registeredHandle, bool timedOut) inline private
Definition at line 923 of file PortableThreadPool.cs.
        {
            registeredHandle.RequestCallback();
            if (registeredHandle.Repeating)
            {
                registeredHandle.RestartTimeout();
            }
            else
            {
                UnregisterWait(registeredHandle, blocking: false);
            }
            ThreadPool.UnsafeQueueWaitCompletion(new CompleteWaitThreadPoolWorkItem(registeredHandle, timedOut));
        }
References System.Threading.RegisteredWaitHandle.Repeating, System.Threading.RegisteredWaitHandle.RequestCallback(), System.Threading.RegisteredWaitHandle.RestartTimeout(), System.Threading.PortableThreadPool.WaitThread.UnregisterWait(), and System.Threading.ThreadPool.UnsafeQueueWaitCompletion().
Referenced by System.Threading.PortableThreadPool.WaitThread.WaitThreadStart().