Terraria: System.Net.Sockets.SendPacketsElement.Initialize
Initialize()
void System.Net.Sockets.SendPacketsElement.Initialize (string filePath, FileStream fileStream, byte[] buffer, ReadOnlyMemory< byte >? memoryBuffer, long offset, int count, bool endOfPacket) inline private
Definition at line 128 of file SendPacketsElement.cs.
    {
        FilePath = filePath;
        FileStream = fileStream;
        Buffer = buffer;
        MemoryBuffer = memoryBuffer;
        OffsetLong = offset;
        Count = count;
        EndOfPacket = endOfPacket;
    }
References System.buffer, System.count, System.Net.Sockets.SendPacketsElement.Count, System.Net.Sockets.SendPacketsElement.EndOfPacket, System.Net.Sockets.SendPacketsElement.FilePath, System.Net.Sockets.SendPacketsElement.MemoryBuffer, System.offset, and System.Net.Sockets.SendPacketsElement.OffsetLong.
Referenced by System.Net.Sockets.SendPacketsElement.SendPacketsElement(), System.Net.Sockets.SendPacketsElement.SendPacketsElement(), System.Net.Sockets.SendPacketsElement.SendPacketsElement(), and System.Net.Sockets.SendPacketsElement.SendPacketsElement().