Terraria: System.Net.Http.HttpResponseMessage.ToString
ToString()
override string System.Net.Http.HttpResponseMessage.ToString () inline
Definition at line 192 of file HttpResponseMessage.cs.
    {
        StringBuilder stringBuilder = new StringBuilder();
        stringBuilder.Append("StatusCode: ");
        stringBuilder.Append((int)_statusCode);
        stringBuilder.Append(", ReasonPhrase: '");
        stringBuilder.Append(ReasonPhrase ?? "<null>");
        stringBuilder.Append("', Version: ");
        stringBuilder.Append(_version);
        stringBuilder.Append(", Content: ");
        stringBuilder.Append((_content == null) ? "<null>" : _content.GetType().ToString());
        stringBuilder.AppendLine(", Headers:");
        HeaderUtilities.DumpHeaders(stringBuilder, _headers, _content?.Headers);
        if (_trailingHeaders != null)
        {
            stringBuilder.AppendLine(", Trailing Headers:");
            HeaderUtilities.DumpHeaders(stringBuilder, _trailingHeaders);
        }
        return stringBuilder.ToString();
    }
References System.Net.Http.HttpResponseMessage._content, System.Net.Http.HttpResponseMessage._headers, System.Net.Http.HttpResponseMessage._statusCode, System.Net.Http.HttpResponseMessage._trailingHeaders, System.Net.Http.HttpResponseMessage._version, System.Text.StringBuilder.Append(), System.Text.StringBuilder.AppendLine(), System.Net.Http.Headers.HeaderUtilities.DumpHeaders(), System.Net.Http.HttpResponseMessage.ReasonPhrase, and System.Text.StringBuilder.ToString().
Referenced by System.Net.Http.HttpResponseMessage.CheckDisposed().