Terraria: System.Data.Common.DbCommandBuilder.ParameterNames.GetAdjustedParameterNameMaxLength
GetAdjustedParameterNameMaxLength()
int System.Data.Common.DbCommandBuilder.ParameterNames.GetAdjustedParameterNameMaxLength () inline private
Definition at line 184 of file DbCommandBuilder.cs.
        {
            int num = Math.Max((_isNullPrefix != null) ? _isNullPrefix.Length : 0, (_originalPrefix != null) ? _originalPrefix.Length : 0) + _dbCommandBuilder.GetParameterName("").Length;
            return _dbCommandBuilder.ParameterNameMaxLength - num;
        }
References System.Data.Common.DbCommandBuilder.ParameterNames._dbCommandBuilder, System.Data.Common.DbCommandBuilder.ParameterNames._isNullPrefix, System.Data.Common.DbCommandBuilder.ParameterNames._originalPrefix, System.Data.Common.DbCommandBuilder.GetParameterName(), and System.Math.Max().
Referenced by System.Data.Common.DbCommandBuilder.ParameterNames.ParameterNames().