Terraria: System.Data.Common.DbCommandBuilder.ParameterNames.ParameterNames
ParameterNames()
System.Data.Common.DbCommandBuilder.ParameterNames.ParameterNames (DbCommandBuilder dbCommandBuilder, DbSchemaRow[] schemaRows) inline package
Definition at line 35 of file DbCommandBuilder.cs.
        {
            _dbCommandBuilder = dbCommandBuilder;
            _baseParameterNames = new string[schemaRows.Length];
            _originalParameterNames = new string[schemaRows.Length];
            _nullParameterNames = new string[schemaRows.Length];
            _isMutatedName = new bool[schemaRows.Length];
            _count = schemaRows.Length;
            _parameterNameParser = new Regex(_dbCommandBuilder.ParameterNamePattern, RegexOptions.ExplicitCapture | RegexOptions.Singleline);
            SetAndValidateNamePrefixes();
            _adjustedParameterNameMaxLength = GetAdjustedParameterNameMaxLength();
            for (int i = 0; i < schemaRows.Length; i++)
            {
                DbSchemaRow dbSchemaRow = schemaRows[i];
                if (dbSchemaRow == null)
                {
                    continue;
                }
                bool flag = false;
                string text = dbSchemaRow.ColumnName;
                if ((_originalPrefix == null || !text.StartsWith(_originalPrefix, StringComparison.OrdinalIgnoreCase)) && (_isNullPrefix == null || !text.StartsWith(_isNullPrefix, StringComparison.OrdinalIgnoreCase)))
                {
                    if (text.Contains(' '))
                    {
                        text = text.Replace(' ', '_');
                        flag = true;
                    }
                    if (_parameterNameParser.IsMatch(text) && text.Length <= _adjustedParameterNameMaxLength)
                    {
                        _baseParameterNames[i] = text;
                        _isMutatedName[i] = flag;
                    }
                }
            }
            EliminateConflictingNames();
            for (int j = 0; j < schemaRows.Length; j++)
            {
                if (_baseParameterNames[j] != null)
                {
                    if (_originalPrefix != null)
                    {
                        _originalParameterNames[j] = _originalPrefix + _baseParameterNames[j];
                    }
                    if (_isNullPrefix != null && schemaRows[j].AllowDBNull)
                    {
                        _nullParameterNames[j] = _isNullPrefix + _baseParameterNames[j];
                    }
                }
            }
            ApplyProviderSpecificFormat();
            GenerateMissingNames(schemaRows);
        }
References System.Data.Common.DbCommandBuilder.ParameterNames._adjustedParameterNameMaxLength, System.Data.Common.DbCommandBuilder.ParameterNames._baseParameterNames, System.Data.Common.DbCommandBuilder.ParameterNames._count, System.Data.Common.DbCommandBuilder.ParameterNames._dbCommandBuilder, System.Data.Common.DbCommandBuilder.ParameterNames._isMutatedName, System.Data.Common.DbCommandBuilder.ParameterNames._isNullPrefix, System.Data.Common.DbCommandBuilder.ParameterNames._nullParameterNames, System.Data.Common.DbCommandBuilder.ParameterNames._originalParameterNames, System.Data.Common.DbCommandBuilder.ParameterNames._originalPrefix, System.Data.Common.DbCommandBuilder.ParameterNames._parameterNameParser, System.Data.Common.DbCommandBuilder.ParameterNames.ApplyProviderSpecificFormat(), System.Data.Common.DbSchemaRow.ColumnName, System.Data.Common.DbCommandBuilder.ParameterNames.EliminateConflictingNames(), System.Data.Common.DbCommandBuilder.ParameterNames.GenerateMissingNames(), System.Data.Common.DbCommandBuilder.ParameterNames.GetAdjustedParameterNameMaxLength(), System.Text.RegularExpressions.i, System.Text.RegularExpressions.Regex.IsMatch(), System.Data.Common.DbCommandBuilder.ParameterNamePattern, System.Data.Common.DbCommandBuilder.ParameterNames.SetAndValidateNamePrefixes(), and System.text.