Terraria: System.Reflection.Metadata.AssemblyReferenceHandle.FromVirtualIndex
FromVirtualIndex()
static AssemblyReferenceHandle System.Reflection.Metadata.AssemblyReferenceHandle.FromVirtualIndex (VirtualIndex virtualIndex) inline static package
Definition at line 38 of file AssemblyReferenceHandle.cs.
    {
        return new AssemblyReferenceHandle(0x80000000u | (uint)virtualIndex);
    }
References System.Reflection.Metadata.AssemblyReferenceHandle.AssemblyReferenceHandle().
Referenced by System.Reflection.Metadata.MetadataReader.GetProjectedAssemblyRef(), and System.Reflection.Metadata.TypeReference.GetProjectedResolutionScope().