Terraria: Microsoft.Xna.Framework.Graphics.ProfileChecker.IsProfileSupported
IsProfileSupported()
static unsafe bool Microsoft.Xna.Framework.Graphics.ProfileChecker.IsProfileSupported (IDirect3D9 * pD3D, uint adapter, _D3DDEVTYPE deviceType, GraphicsProfile graphicsProfile) inline static
Definition at line 13 of file ProfileChecker.cs.
    {
        ProfileCapabilities instance = ProfileCapabilities.GetInstance(graphicsProfile);
        System.Runtime.CompilerServices.Unsafe.SkipInit(out _D3DCAPS9 d3DCAPS);
        if (((delegate* unmanaged[Stdcall, Stdcall]<IntPtr, uint, _D3DDEVTYPE, _D3DCAPS9*, int>)(int)(*(uint*)(*(int*)pD3D + 56)))((nint)pD3D, adapter, deviceType, &d3DCAPS) < 0)
        {
            return false;
        }
        if (deviceType == (_D3DDEVTYPE)1 && (System.Runtime.CompilerServices.Unsafe.As<_D3DCAPS9, int>(ref System.Runtime.CompilerServices.Unsafe.AddByteOffset(ref d3DCAPS, 28)) & 0x10000) == 0)
        {
            System.Runtime.CompilerServices.Unsafe.As<_D3DCAPS9, int>(ref System.Runtime.CompilerServices.Unsafe.AddByteOffset(ref d3DCAPS, 196)) = -130560;
            System.Runtime.CompilerServices.Unsafe.As<_D3DCAPS9, int>(ref System.Runtime.CompilerServices.Unsafe.AddByteOffset(ref d3DCAPS, 236)) = 15;
        }
        if ((uint)(System.Runtime.CompilerServices.Unsafe.As<_D3DCAPS9, int>(ref System.Runtime.CompilerServices.Unsafe.AddByteOffset(ref d3DCAPS, 196)) & 0xFFFF) < instance.VertexShaderVersion)
        {
            return false;
        }
        if ((uint)(System.Runtime.CompilerServices.Unsafe.As<_D3DCAPS9, int>(ref System.Runtime.CompilerServices.Unsafe.AddByteOffset(ref d3DCAPS, 204)) & 0xFFFF) < instance.PixelShaderVersion)
        {
            return false;
        }
        if ((uint)System.Runtime.CompilerServices.Unsafe.As<_D3DCAPS9, int>(ref System.Runtime.CompilerServices.Unsafe.AddByteOffset(ref d3DCAPS, 180)) < (uint)instance.MaxPrimitiveCount)
        {
            return false;
        }
        if ((uint)System.Runtime.CompilerServices.Unsafe.As<_D3DCAPS9, int>(ref System.Runtime.CompilerServices.Unsafe.AddByteOffset(ref d3DCAPS, 188)) < (uint)instance.MaxVertexStreams)
        {
            return false;
        }
        if ((uint)System.Runtime.CompilerServices.Unsafe.As<_D3DCAPS9, int>(ref System.Runtime.CompilerServices.Unsafe.AddByteOffset(ref d3DCAPS, 192)) < (uint)instance.MaxStreamStride)
        {
            return false;
        }
        int num = (instance.IndexElementSize32 ? 16777214 : 65534);
        if ((uint)System.Runtime.CompilerServices.Unsafe.As<_D3DCAPS9, int>(ref System.Runtime.CompilerServices.Unsafe.AddByteOffset(ref d3DCAPS, 184)) < (uint)num)
        {
            return false;
        }
        if ((System.Runtime.CompilerServices.Unsafe.As<_D3DCAPS9, int>(ref System.Runtime.CompilerServices.Unsafe.AddByteOffset(ref d3DCAPS, 212)) & 0x10) == 0)
        {
            return false;
        }
        if ((System.Runtime.CompilerServices.Unsafe.As<_D3DCAPS9, int>(ref System.Runtime.CompilerServices.Unsafe.AddByteOffset(ref d3DCAPS, 212)) & 1) == 0)
        {
            return false;
        }
        if ((System.Runtime.CompilerServices.Unsafe.As<_D3DCAPS9, int>(ref System.Runtime.CompilerServices.Unsafe.AddByteOffset(ref d3DCAPS, 36)) & 0x4000000) == 0)
        {
            return false;
        }
        if ((System.Runtime.CompilerServices.Unsafe.As<_D3DCAPS9, int>(ref System.Runtime.CompilerServices.Unsafe.AddByteOffset(ref d3DCAPS, 36)) & 0x2000) == 0)
        {
            return false;
        }
        if ((System.Runtime.CompilerServices.Unsafe.As<_D3DCAPS9, int>(ref System.Runtime.CompilerServices.Unsafe.AddByteOffset(ref d3DCAPS, 36)) & 0x1000000) == 0)
        {
            return false;
        }
        if ((System.Runtime.CompilerServices.Unsafe.As<_D3DCAPS9, int>(ref System.Runtime.CompilerServices.Unsafe.AddByteOffset(ref d3DCAPS, 36)) & 0x2000000) == 0)
        {
            return false;
        }
        if ((System.Runtime.CompilerServices.Unsafe.As<_D3DCAPS9, int>(ref System.Runtime.CompilerServices.Unsafe.AddByteOffset(ref d3DCAPS, 56)) & 8) == 0)
        {
            return false;
        }
        if ((System.Runtime.CompilerServices.Unsafe.As<_D3DCAPS9, int>(ref System.Runtime.CompilerServices.Unsafe.AddByteOffset(ref d3DCAPS, 56)) & 0x4000) == 0)
        {
            return false;
        }
        if ((System.Runtime.CompilerServices.Unsafe.As<_D3DCAPS9, int>(ref System.Runtime.CompilerServices.Unsafe.AddByteOffset(ref d3DCAPS, 32)) & 2) == 0)
        {
            return false;
        }
        if ((System.Runtime.CompilerServices.Unsafe.As<_D3DCAPS9, int>(ref System.Runtime.CompilerServices.Unsafe.AddByteOffset(ref d3DCAPS, 32)) & 0x10) == 0)
        {
            return false;
        }
        if ((System.Runtime.CompilerServices.Unsafe.As<_D3DCAPS9, int>(ref System.Runtime.CompilerServices.Unsafe.AddByteOffset(ref d3DCAPS, 32)) & 0x20) == 0)
        {
            return false;
        }
        if ((System.Runtime.CompilerServices.Unsafe.As<_D3DCAPS9, int>(ref System.Runtime.CompilerServices.Unsafe.AddByteOffset(ref d3DCAPS, 32)) & 0x40) == 0)
        {
            return false;
        }
        if ((System.Runtime.CompilerServices.Unsafe.As<_D3DCAPS9, int>(ref System.Runtime.CompilerServices.Unsafe.AddByteOffset(ref d3DCAPS, 32)) & 0x80) == 0)
        {
            return false;
        }
        if ((System.Runtime.CompilerServices.Unsafe.As<_D3DCAPS9, int>(ref System.Runtime.CompilerServices.Unsafe.AddByteOffset(ref d3DCAPS, 32)) & 0x800) == 0)
        {
            return false;
        }
        if ((System.Runtime.CompilerServices.Unsafe.As<_D3DCAPS9, int>(ref System.Runtime.CompilerServices.Unsafe.AddByteOffset(ref d3DCAPS, 84)) & 4) == 0)
        {
            return false;
        }
        if ((System.Runtime.CompilerServices.Unsafe.As<_D3DCAPS9, int>(ref System.Runtime.CompilerServices.Unsafe.AddByteOffset(ref d3DCAPS, 84)) & 1) == 0)
        {
            return false;
        }
        if ((System.Runtime.CompilerServices.Unsafe.As<_D3DCAPS9, int>(ref System.Runtime.CompilerServices.Unsafe.AddByteOffset(ref d3DCAPS, 84)) & 2) == 0)
        {
            return false;
        }
        if ((System.Runtime.CompilerServices.Unsafe.As<_D3DCAPS9, int>(ref System.Runtime.CompilerServices.Unsafe.AddByteOffset(ref d3DCAPS, 40)) & 0x80) == 0)
        {
            return false;
        }
        if ((System.Runtime.CompilerServices.Unsafe.As<_D3DCAPS9, int>(ref System.Runtime.CompilerServices.Unsafe.AddByteOffset(ref d3DCAPS, 40)) & 4) == 0)
        {
            return false;
        }
        if ((System.Runtime.CompilerServices.Unsafe.As<_D3DCAPS9, int>(ref System.Runtime.CompilerServices.Unsafe.AddByteOffset(ref d3DCAPS, 40)) & 0x10) == 0)
        {
            return false;
        }
        if ((System.Runtime.CompilerServices.Unsafe.As<_D3DCAPS9, int>(ref System.Runtime.CompilerServices.Unsafe.AddByteOffset(ref d3DCAPS, 40)) & 0x40) == 0)
        {
            return false;
        }
        if ((System.Runtime.CompilerServices.Unsafe.As<_D3DCAPS9, int>(ref System.Runtime.CompilerServices.Unsafe.AddByteOffset(ref d3DCAPS, 40)) & 2) == 0)
        {
            return false;
        }
        if ((System.Runtime.CompilerServices.Unsafe.As<_D3DCAPS9, int>(ref System.Runtime.CompilerServices.Unsafe.AddByteOffset(ref d3DCAPS, 40)) & 8) == 0)
        {
            return false;
        }
        if ((System.Runtime.CompilerServices.Unsafe.As<_D3DCAPS9, int>(ref System.Runtime.CompilerServices.Unsafe.AddByteOffset(ref d3DCAPS, 40)) & 1) == 0)
        {
            return false;
        }
        if ((System.Runtime.CompilerServices.Unsafe.As<_D3DCAPS9, int>(ref System.Runtime.CompilerServices.Unsafe.AddByteOffset(ref d3DCAPS, 40)) & 0x20) == 0)
        {
            return false;
        }
        if ((System.Runtime.CompilerServices.Unsafe.As<_D3DCAPS9, int>(ref System.Runtime.CompilerServices.Unsafe.AddByteOffset(ref d3DCAPS, 136)) & 1) == 0)
        {
            return false;
        }
        if ((System.Runtime.CompilerServices.Unsafe.As<_D3DCAPS9, int>(ref System.Runtime.CompilerServices.Unsafe.AddByteOffset(ref d3DCAPS, 136)) & 2) == 0)
        {
            return false;
        }
        if ((System.Runtime.CompilerServices.Unsafe.As<_D3DCAPS9, int>(ref System.Runtime.CompilerServices.Unsafe.AddByteOffset(ref d3DCAPS, 136)) & 4) == 0)
        {
            return false;
        }
        if ((System.Runtime.CompilerServices.Unsafe.As<_D3DCAPS9, int>(ref System.Runtime.CompilerServices.Unsafe.AddByteOffset(ref d3DCAPS, 136)) & 8) == 0)
        {
            return false;
        }
        if ((System.Runtime.CompilerServices.Unsafe.As<_D3DCAPS9, int>(ref System.Runtime.CompilerServices.Unsafe.AddByteOffset(ref d3DCAPS, 136)) & 0x10) == 0)
        {
            return false;
        }
        if ((System.Runtime.CompilerServices.Unsafe.As<_D3DCAPS9, int>(ref System.Runtime.CompilerServices.Unsafe.AddByteOffset(ref d3DCAPS, 136)) & 0x20) == 0)
        {
            return false;
        }
        if ((System.Runtime.CompilerServices.Unsafe.As<_D3DCAPS9, int>(ref System.Runtime.CompilerServices.Unsafe.AddByteOffset(ref d3DCAPS, 136)) & 0x40) == 0)
        {
            return false;
        }
        if ((System.Runtime.CompilerServices.Unsafe.As<_D3DCAPS9, int>(ref System.Runtime.CompilerServices.Unsafe.AddByteOffset(ref d3DCAPS, 136)) & 0x80) == 0)
        {
            return false;
        }
        if ((System.Runtime.CompilerServices.Unsafe.As<_D3DCAPS9, int>(ref System.Runtime.CompilerServices.Unsafe.AddByteOffset(ref d3DCAPS, 136)) & 0x100) == 0)
        {
            return false;
        }
        if ((System.Runtime.CompilerServices.Unsafe.As<_D3DCAPS9, int>(ref System.Runtime.CompilerServices.Unsafe.AddByteOffset(ref d3DCAPS, 44)) & 0x2000) == 0)
        {
            return false;
        }
        if ((System.Runtime.CompilerServices.Unsafe.As<_D3DCAPS9, int>(ref System.Runtime.CompilerServices.Unsafe.AddByteOffset(ref d3DCAPS, 44)) & 0x40) == 0)
        {
            return false;
        }
        if ((System.Runtime.CompilerServices.Unsafe.As<_D3DCAPS9, int>(ref System.Runtime.CompilerServices.Unsafe.AddByteOffset(ref d3DCAPS, 44)) & 0x100) == 0)
        {
            return false;
        }
        if ((System.Runtime.CompilerServices.Unsafe.As<_D3DCAPS9, int>(ref System.Runtime.CompilerServices.Unsafe.AddByteOffset(ref d3DCAPS, 44)) & 0x80) == 0)
        {
            return false;
        }
        if ((System.Runtime.CompilerServices.Unsafe.As<_D3DCAPS9, int>(ref System.Runtime.CompilerServices.Unsafe.AddByteOffset(ref d3DCAPS, 44)) & 0x200) == 0)
        {
            return false;
        }
        if ((System.Runtime.CompilerServices.Unsafe.As<_D3DCAPS9, int>(ref System.Runtime.CompilerServices.Unsafe.AddByteOffset(ref d3DCAPS, 44)) & 0x20) == 0)
        {
            return false;
        }
        if ((System.Runtime.CompilerServices.Unsafe.As<_D3DCAPS9, int>(ref System.Runtime.CompilerServices.Unsafe.AddByteOffset(ref d3DCAPS, 44)) & 8) == 0)
        {
            return false;
        }
        if ((System.Runtime.CompilerServices.Unsafe.As<_D3DCAPS9, int>(ref System.Runtime.CompilerServices.Unsafe.AddByteOffset(ref d3DCAPS, 44)) & 2) == 0)
        {
            return false;
        }
        if ((System.Runtime.CompilerServices.Unsafe.As<_D3DCAPS9, int>(ref System.Runtime.CompilerServices.Unsafe.AddByteOffset(ref d3DCAPS, 44)) & 0x10) == 0)
        {
            return false;
        }
        if ((System.Runtime.CompilerServices.Unsafe.As<_D3DCAPS9, int>(ref System.Runtime.CompilerServices.Unsafe.AddByteOffset(ref d3DCAPS, 44)) & 0x400) == 0)
        {
            return false;
        }
        if ((System.Runtime.CompilerServices.Unsafe.As<_D3DCAPS9, int>(ref System.Runtime.CompilerServices.Unsafe.AddByteOffset(ref d3DCAPS, 44)) & 4) == 0)
        {
            return false;
        }
        if ((System.Runtime.CompilerServices.Unsafe.As<_D3DCAPS9, int>(ref System.Runtime.CompilerServices.Unsafe.AddByteOffset(ref d3DCAPS, 44)) & 1) == 0)
        {
            return false;
        }
        if ((System.Runtime.CompilerServices.Unsafe.As<_D3DCAPS9, int>(ref System.Runtime.CompilerServices.Unsafe.AddByteOffset(ref d3DCAPS, 48)) & 0x2000) == 0)
        {
            return false;
        }
        if ((System.Runtime.CompilerServices.Unsafe.As<_D3DCAPS9, int>(ref System.Runtime.CompilerServices.Unsafe.AddByteOffset(ref d3DCAPS, 48)) & 0x40) == 0)
        {
            return false;
        }
        if ((System.Runtime.CompilerServices.Unsafe.As<_D3DCAPS9, int>(ref System.Runtime.CompilerServices.Unsafe.AddByteOffset(ref d3DCAPS, 48)) & 0x100) == 0)
        {
            return false;
        }
        if ((System.Runtime.CompilerServices.Unsafe.As<_D3DCAPS9, int>(ref System.Runtime.CompilerServices.Unsafe.AddByteOffset(ref d3DCAPS, 48)) & 0x80) == 0)
        {
            return false;
        }
        if ((System.Runtime.CompilerServices.Unsafe.As<_D3DCAPS9, int>(ref System.Runtime.CompilerServices.Unsafe.AddByteOffset(ref d3DCAPS, 48)) & 0x200) == 0)
        {
            return false;
        }
        if ((System.Runtime.CompilerServices.Unsafe.As<_D3DCAPS9, int>(ref System.Runtime.CompilerServices.Unsafe.AddByteOffset(ref d3DCAPS, 48)) & 0x20) == 0)
        {
            return false;
        }
        if ((System.Runtime.CompilerServices.Unsafe.As<_D3DCAPS9, int>(ref System.Runtime.CompilerServices.Unsafe.AddByteOffset(ref d3DCAPS, 48)) & 8) == 0)
        {
            return false;
        }
        if ((System.Runtime.CompilerServices.Unsafe.As<_D3DCAPS9, int>(ref System.Runtime.CompilerServices.Unsafe.AddByteOffset(ref d3DCAPS, 48)) & 2) == 0)
        {
            return false;
        }
        if ((System.Runtime.CompilerServices.Unsafe.As<_D3DCAPS9, int>(ref System.Runtime.CompilerServices.Unsafe.AddByteOffset(ref d3DCAPS, 48)) & 0x10) == 0)
        {
            return false;
        }
        if ((System.Runtime.CompilerServices.Unsafe.As<_D3DCAPS9, int>(ref System.Runtime.CompilerServices.Unsafe.AddByteOffset(ref d3DCAPS, 48)) & 4) == 0)
        {
            return false;
        }
        if ((System.Runtime.CompilerServices.Unsafe.As<_D3DCAPS9, int>(ref System.Runtime.CompilerServices.Unsafe.AddByteOffset(ref d3DCAPS, 48)) & 1) == 0)
        {
            return false;
        }
        if (instance.DestBlendSrcAlphaSat && (System.Runtime.CompilerServices.Unsafe.As<_D3DCAPS9, int>(ref System.Runtime.CompilerServices.Unsafe.AddByteOffset(ref d3DCAPS, 48)) & 0x400) == 0)
        {
            return false;
        }
        if (instance.SeparateAlphaBlend && (System.Runtime.CompilerServices.Unsafe.As<_D3DCAPS9, int>(ref System.Runtime.CompilerServices.Unsafe.AddByteOffset(ref d3DCAPS, 32)) & 0x20000) == 0)
        {
            return false;
        }
        int maxRenderTargets = instance.MaxRenderTargets;
        if ((uint)System.Runtime.CompilerServices.Unsafe.As<_D3DCAPS9, int>(ref System.Runtime.CompilerServices.Unsafe.AddByteOffset(ref d3DCAPS, 240)) < (uint)maxRenderTargets)
        {
            return false;
        }
        if (maxRenderTargets > 1)
        {
            if ((System.Runtime.CompilerServices.Unsafe.As<_D3DCAPS9, int>(ref System.Runtime.CompilerServices.Unsafe.AddByteOffset(ref d3DCAPS, 32)) & 0x4000) == 0)
            {
                return false;
            }
            if ((System.Runtime.CompilerServices.Unsafe.As<_D3DCAPS9, int>(ref System.Runtime.CompilerServices.Unsafe.AddByteOffset(ref d3DCAPS, 32)) & 0x80000) == 0)
            {
                return false;
            }
        }
        int maxTextureSize = instance.MaxTextureSize;
        if ((uint)System.Runtime.CompilerServices.Unsafe.As<_D3DCAPS9, int>(ref System.Runtime.CompilerServices.Unsafe.AddByteOffset(ref d3DCAPS, 88)) < (uint)maxTextureSize)
        {
            return false;
        }
        if ((uint)System.Runtime.CompilerServices.Unsafe.As<_D3DCAPS9, int>(ref System.Runtime.CompilerServices.Unsafe.AddByteOffset(ref d3DCAPS, 92)) < (uint)maxTextureSize)
        {
            return false;
        }
        if (System.Runtime.CompilerServices.Unsafe.As<_D3DCAPS9, int>(ref System.Runtime.CompilerServices.Unsafe.AddByteOffset(ref d3DCAPS, 104)) != 0 && (uint)System.Runtime.CompilerServices.Unsafe.As<_D3DCAPS9, int>(ref System.Runtime.CompilerServices.Unsafe.AddByteOffset(ref d3DCAPS, 104)) < (uint)instance.MaxTextureAspectRatio)
        {
            return false;
        }
        if ((System.Runtime.CompilerServices.Unsafe.As<_D3DCAPS9, int>(ref System.Runtime.CompilerServices.Unsafe.AddByteOffset(ref d3DCAPS, 60)) & 4) == 0)
        {
            return false;
        }
        if ((System.Runtime.CompilerServices.Unsafe.As<_D3DCAPS9, int>(ref System.Runtime.CompilerServices.Unsafe.AddByteOffset(ref d3DCAPS, 60)) & 0x4000) == 0)
        {
            return false;
        }
        if ((System.Runtime.CompilerServices.Unsafe.As<_D3DCAPS9, int>(ref System.Runtime.CompilerServices.Unsafe.AddByteOffset(ref d3DCAPS, 60)) & 0x800) == 0)
        {
            return false;
        }
        if ((System.Runtime.CompilerServices.Unsafe.As<_D3DCAPS9, int>(ref System.Runtime.CompilerServices.Unsafe.AddByteOffset(ref d3DCAPS, 60)) & 0x10000) == 0)
        {
            return false;
        }
        if ((System.Runtime.CompilerServices.Unsafe.As<_D3DCAPS9, int>(ref System.Runtime.CompilerServices.Unsafe.AddByteOffset(ref d3DCAPS, 60)) & 1) == 0)
        {
            return false;
        }
        if (((uint)System.Runtime.CompilerServices.Unsafe.As<_D3DCAPS9, int>(ref System.Runtime.CompilerServices.Unsafe.AddByteOffset(ref d3DCAPS, 60)) & 0x20u) != 0)
        {
            return false;
        }
        if ((System.Runtime.CompilerServices.Unsafe.As<_D3DCAPS9, int>(ref System.Runtime.CompilerServices.Unsafe.AddByteOffset(ref d3DCAPS, 76)) & 4) == 0)
        {
            return false;
        }
        if ((System.Runtime.CompilerServices.Unsafe.As<_D3DCAPS9, int>(ref System.Runtime.CompilerServices.Unsafe.AddByteOffset(ref d3DCAPS, 76)) & 1) == 0)
        {
            return false;
        }
        if ((System.Runtime.CompilerServices.Unsafe.As<_D3DCAPS9, int>(ref System.Runtime.CompilerServices.Unsafe.AddByteOffset(ref d3DCAPS, 76)) & 2) == 0)
        {
            return false;
        }
        if ((System.Runtime.CompilerServices.Unsafe.As<_D3DCAPS9, int>(ref System.Runtime.CompilerServices.Unsafe.AddByteOffset(ref d3DCAPS, 76)) & 0x10) == 0)
        {
            return false;
        }
        if ((System.Runtime.CompilerServices.Unsafe.As<_D3DCAPS9, int>(ref System.Runtime.CompilerServices.Unsafe.AddByteOffset(ref d3DCAPS, 64)) & 0x1000000) == 0)
        {
            return false;
        }
        if ((System.Runtime.CompilerServices.Unsafe.As<_D3DCAPS9, int>(ref System.Runtime.CompilerServices.Unsafe.AddByteOffset(ref d3DCAPS, 64)) & 0x2000000) == 0)
        {
            return false;
        }
        if ((System.Runtime.CompilerServices.Unsafe.As<_D3DCAPS9, int>(ref System.Runtime.CompilerServices.Unsafe.AddByteOffset(ref d3DCAPS, 64)) & 0x100) == 0)
        {
            return false;
        }
        if ((System.Runtime.CompilerServices.Unsafe.As<_D3DCAPS9, int>(ref System.Runtime.CompilerServices.Unsafe.AddByteOffset(ref d3DCAPS, 64)) & 0x200) == 0)
        {
            return false;
        }
        if ((System.Runtime.CompilerServices.Unsafe.As<_D3DCAPS9, int>(ref System.Runtime.CompilerServices.Unsafe.AddByteOffset(ref d3DCAPS, 64)) & 0x10000) == 0)
        {
            return false;
        }
        if ((System.Runtime.CompilerServices.Unsafe.As<_D3DCAPS9, int>(ref System.Runtime.CompilerServices.Unsafe.AddByteOffset(ref d3DCAPS, 64)) & 0x20000) == 0)
        {
            return false;
        }
        if ((System.Runtime.CompilerServices.Unsafe.As<_D3DCAPS9, int>(ref System.Runtime.CompilerServices.Unsafe.AddByteOffset(ref d3DCAPS, 68)) & 0x1000000) == 0)
        {
            return false;
        }
        if ((System.Runtime.CompilerServices.Unsafe.As<_D3DCAPS9, int>(ref System.Runtime.CompilerServices.Unsafe.AddByteOffset(ref d3DCAPS, 68)) & 0x2000000) == 0)
        {
            return false;
        }
        if ((System.Runtime.CompilerServices.Unsafe.As<_D3DCAPS9, int>(ref System.Runtime.CompilerServices.Unsafe.AddByteOffset(ref d3DCAPS, 68)) & 0x100) == 0)
        {
            return false;
        }
        if ((System.Runtime.CompilerServices.Unsafe.As<_D3DCAPS9, int>(ref System.Runtime.CompilerServices.Unsafe.AddByteOffset(ref d3DCAPS, 68)) & 0x200) == 0)
        {
            return false;
        }
        if ((System.Runtime.CompilerServices.Unsafe.As<_D3DCAPS9, int>(ref System.Runtime.CompilerServices.Unsafe.AddByteOffset(ref d3DCAPS, 68)) & 0x10000) == 0)
        {
            return false;
        }
        if ((System.Runtime.CompilerServices.Unsafe.As<_D3DCAPS9, int>(ref System.Runtime.CompilerServices.Unsafe.AddByteOffset(ref d3DCAPS, 68)) & 0x20000) == 0)
        {
            return false;
        }
        int maxVolumeExtent = instance.MaxVolumeExtent;
        if (maxVolumeExtent > 0)
        {
            if ((uint)System.Runtime.CompilerServices.Unsafe.As<_D3DCAPS9, int>(ref System.Runtime.CompilerServices.Unsafe.AddByteOffset(ref d3DCAPS, 96)) < (uint)maxVolumeExtent)
            {
                return false;
            }
            if ((System.Runtime.CompilerServices.Unsafe.As<_D3DCAPS9, int>(ref System.Runtime.CompilerServices.Unsafe.AddByteOffset(ref d3DCAPS, 60)) & 0x2000) == 0)
            {
                return false;
            }
            if ((System.Runtime.CompilerServices.Unsafe.As<_D3DCAPS9, int>(ref System.Runtime.CompilerServices.Unsafe.AddByteOffset(ref d3DCAPS, 60)) & 0x8000) == 0)
            {
                return false;
            }
            if ((System.Runtime.CompilerServices.Unsafe.As<_D3DCAPS9, int>(ref System.Runtime.CompilerServices.Unsafe.AddByteOffset(ref d3DCAPS, 80)) & 4) == 0)
            {
                return false;
            }
            if ((System.Runtime.CompilerServices.Unsafe.As<_D3DCAPS9, int>(ref System.Runtime.CompilerServices.Unsafe.AddByteOffset(ref d3DCAPS, 80)) & 1) == 0)
            {
                return false;
            }
            if ((System.Runtime.CompilerServices.Unsafe.As<_D3DCAPS9, int>(ref System.Runtime.CompilerServices.Unsafe.AddByteOffset(ref d3DCAPS, 80)) & 2) == 0)
            {
                return false;
            }
            if ((System.Runtime.CompilerServices.Unsafe.As<_D3DCAPS9, int>(ref System.Runtime.CompilerServices.Unsafe.AddByteOffset(ref d3DCAPS, 80)) & 0x10) == 0)
            {
                return false;
            }
            if ((System.Runtime.CompilerServices.Unsafe.As<_D3DCAPS9, int>(ref System.Runtime.CompilerServices.Unsafe.AddByteOffset(ref d3DCAPS, 72)) & 0x1000000) == 0)
            {
                return false;
            }
            if ((System.Runtime.CompilerServices.Unsafe.As<_D3DCAPS9, int>(ref System.Runtime.CompilerServices.Unsafe.AddByteOffset(ref d3DCAPS, 72)) & 0x2000000) == 0)
            {
                return false;
            }
            if ((System.Runtime.CompilerServices.Unsafe.As<_D3DCAPS9, int>(ref System.Runtime.CompilerServices.Unsafe.AddByteOffset(ref d3DCAPS, 72)) & 0x100) == 0)
            {
                return false;
            }
            if ((System.Runtime.CompilerServices.Unsafe.As<_D3DCAPS9, int>(ref System.Runtime.CompilerServices.Unsafe.AddByteOffset(ref d3DCAPS, 72)) & 0x200) == 0)
            {
                return false;
            }
            if ((System.Runtime.CompilerServices.Unsafe.As<_D3DCAPS9, int>(ref System.Runtime.CompilerServices.Unsafe.AddByteOffset(ref d3DCAPS, 72)) & 0x10000) == 0)
            {
                return false;
            }
            if ((System.Runtime.CompilerServices.Unsafe.As<_D3DCAPS9, int>(ref System.Runtime.CompilerServices.Unsafe.AddByteOffset(ref d3DCAPS, 72)) & 0x20000) == 0)
            {
                return false;
            }
        }
        if (instance.NonPow2Unconditional)
        {
            if (((uint)System.Runtime.CompilerServices.Unsafe.As<_D3DCAPS9, int>(ref System.Runtime.CompilerServices.Unsafe.AddByteOffset(ref d3DCAPS, 60)) & 2u) != 0)
            {
                return false;
            }
        }
        else if (((uint)System.Runtime.CompilerServices.Unsafe.As<_D3DCAPS9, int>(ref System.Runtime.CompilerServices.Unsafe.AddByteOffset(ref d3DCAPS, 60)) & 2u) != 0 && (System.Runtime.CompilerServices.Unsafe.As<_D3DCAPS9, int>(ref System.Runtime.CompilerServices.Unsafe.AddByteOffset(ref d3DCAPS, 60)) & 0x100) == 0)
        {
            return false;
        }
        if (instance.NonPow2Cube && ((uint)System.Runtime.CompilerServices.Unsafe.As<_D3DCAPS9, int>(ref System.Runtime.CompilerServices.Unsafe.AddByteOffset(ref d3DCAPS, 60)) & 0x20000u) != 0)
        {
            return false;
        }
        if (instance.NonPow2Volume && ((uint)System.Runtime.CompilerServices.Unsafe.As<_D3DCAPS9, int>(ref System.Runtime.CompilerServices.Unsafe.AddByteOffset(ref d3DCAPS, 60)) & 0x40000u) != 0)
        {
            return false;
        }
        if (instance.MaxVertexSamplers > 0)
        {
            if ((System.Runtime.CompilerServices.Unsafe.As<_D3DCAPS9, int>(ref System.Runtime.CompilerServices.Unsafe.AddByteOffset(ref d3DCAPS, 284)) & 0x1000000) == 0)
            {
                return false;
            }
            if ((System.Runtime.CompilerServices.Unsafe.As<_D3DCAPS9, int>(ref System.Runtime.CompilerServices.Unsafe.AddByteOffset(ref d3DCAPS, 284)) & 0x100) == 0)
            {
                return false;
            }
        }
        List<VertexElementFormat>.Enumerator enumerator = instance.ValidVertexFormats.GetEnumerator();
        if (enumerator.MoveNext())
        {
            do
            {
                switch (enumerator.Current)
                {
                case VertexElementFormat.Color:
                    if (((uint)System.Runtime.CompilerServices.Unsafe.As<_D3DCAPS9, int>(ref System.Runtime.CompilerServices.Unsafe.AddByteOffset(ref d3DCAPS, 236)) & 2u) != 0)
                    {
                        break;
                    }
                    return false;
                case VertexElementFormat.Byte4:
                    if (((uint)System.Runtime.CompilerServices.Unsafe.As<_D3DCAPS9, int>(ref System.Runtime.CompilerServices.Unsafe.AddByteOffset(ref d3DCAPS, 236)) & (true ? 1u : 0u)) != 0)
                    {
                        break;
                    }
                    return false;
                case VertexElementFormat.NormalizedShort2:
                    if (((uint)System.Runtime.CompilerServices.Unsafe.As<_D3DCAPS9, int>(ref System.Runtime.CompilerServices.Unsafe.AddByteOffset(ref d3DCAPS, 236)) & 4u) != 0)
                    {
                        break;
                    }
                    return false;
                case VertexElementFormat.NormalizedShort4:
                    if (((uint)System.Runtime.CompilerServices.Unsafe.As<_D3DCAPS9, int>(ref System.Runtime.CompilerServices.Unsafe.AddByteOffset(ref d3DCAPS, 236)) & 8u) != 0)
                    {
                        break;
                    }
                    return false;
                case VertexElementFormat.HalfVector2:
                    if (((uint)System.Runtime.CompilerServices.Unsafe.As<_D3DCAPS9, int>(ref System.Runtime.CompilerServices.Unsafe.AddByteOffset(ref d3DCAPS, 236)) & 0x100u) != 0)
                    {
                        break;
                    }
                    return false;
                case VertexElementFormat.HalfVector4:
                    if ((System.Runtime.CompilerServices.Unsafe.As<_D3DCAPS9, int>(ref System.Runtime.CompilerServices.Unsafe.AddByteOffset(ref d3DCAPS, 236)) & 0x200) == 0)
                    {
                        return false;
                    }
                    break;
                }
            }
            while (enumerator.MoveNext());
        }
        List<SurfaceFormat>.Enumerator enumerator2 = instance.ValidTextureFormats.GetEnumerator();
        if (enumerator2.MoveNext())
        {
            do
            {
                SurfaceFormat current = enumerator2.Current;
                if (!CheckTextureFormat(instance, pD3D, adapter, deviceType, (_D3DRESOURCETYPE)3, current))
                {
                    return false;
                }
            }
            while (enumerator2.MoveNext());
        }
        List<SurfaceFormat>.Enumerator enumerator3 = instance.ValidCubeFormats.GetEnumerator();
        if (enumerator3.MoveNext())
        {
            do
            {
                SurfaceFormat current2 = enumerator3.Current;
                if (!CheckTextureFormat(instance, pD3D, adapter, deviceType, (_D3DRESOURCETYPE)5, current2))
                {
                    return false;
                }
            }
            while (enumerator3.MoveNext());
        }
        List<SurfaceFormat>.Enumerator enumerator4 = instance.ValidVolumeFormats.GetEnumerator();
        if (enumerator4.MoveNext())
        {
            do
            {
                SurfaceFormat current3 = enumerator4.Current;
                if (!CheckTextureFormat(instance, pD3D, adapter, deviceType, (_D3DRESOURCETYPE)4, current3))
                {
                    return false;
                }
            }
            while (enumerator4.MoveNext());
        }
        List<SurfaceFormat>.Enumerator enumerator5 = instance.ValidVertexTextureFormats.GetEnumerator();
        if (enumerator5.MoveNext())
        {
            do
            {
                SurfaceFormat current4 = enumerator5.Current;
                if (!CheckVertexTextureFormat(instance, pD3D, adapter, deviceType, current4))
                {
                    return false;
                }
            }
            while (enumerator5.MoveNext());
        }
        if (!CheckRenderTargetFormat(instance, pD3D, adapter, deviceType, SurfaceFormat.Color))
        {
            return false;
        }
        if (instance.ValidTextureFormats.Contains(SurfaceFormat.HdrBlendable) && !CheckRenderTargetFormat(instance, pD3D, adapter, deviceType, SurfaceFormat.HdrBlendable))
        {
            return false;
        }
        return true;
    }
References Microsoft.Xna.Framework.Graphics.ProfileChecker.CheckRenderTargetFormat(), Microsoft.Xna.Framework.Graphics.ProfileChecker.CheckTextureFormat(), Microsoft.Xna.Framework.Graphics.ProfileChecker.CheckVertexTextureFormat(), System.Collections.Generic.List< T >.Contains(), Microsoft.Xna.Framework.Graphics.ProfileCapabilities.DestBlendSrcAlphaSat, System.Collections.Generic.List< T >.GetEnumerator(), Microsoft.Xna.Framework.Graphics.ProfileCapabilities.GetInstance(), Microsoft.Xna.Framework.Graphics.ProfileCapabilities.MaxPrimitiveCount, Microsoft.Xna.Framework.Graphics.ProfileCapabilities.MaxRenderTargets, Microsoft.Xna.Framework.Graphics.ProfileCapabilities.MaxStreamStride, Microsoft.Xna.Framework.Graphics.ProfileCapabilities.MaxTextureAspectRatio, Microsoft.Xna.Framework.Graphics.ProfileCapabilities.MaxTextureSize, Microsoft.Xna.Framework.Graphics.ProfileCapabilities.MaxVertexSamplers, Microsoft.Xna.Framework.Graphics.ProfileCapabilities.MaxVertexStreams, Microsoft.Xna.Framework.Graphics.ProfileCapabilities.MaxVolumeExtent, Microsoft.Xna.Framework.Graphics.ProfileCapabilities.NonPow2Cube, Microsoft.Xna.Framework.Graphics.ProfileCapabilities.NonPow2Unconditional, Microsoft.Xna.Framework.Graphics.ProfileCapabilities.NonPow2Volume, Microsoft.Xna.Framework.Graphics.ProfileCapabilities.PixelShaderVersion, Microsoft.Xna.Framework.Graphics.ProfileCapabilities.SeparateAlphaBlend, Microsoft.Xna.Framework.Graphics.ProfileCapabilities.ValidCubeFormats, Microsoft.Xna.Framework.Graphics.ProfileCapabilities.ValidTextureFormats, Microsoft.Xna.Framework.Graphics.ProfileCapabilities.ValidVertexFormats, Microsoft.Xna.Framework.Graphics.ProfileCapabilities.ValidVertexTextureFormats, Microsoft.Xna.Framework.Graphics.ProfileCapabilities.ValidVolumeFormats, and Microsoft.Xna.Framework.Graphics.ProfileCapabilities.VertexShaderVersion.
Referenced by Microsoft.Xna.Framework.Graphics.GraphicsAdapter.IsProfileSupported(), and Microsoft.Xna.Framework.Graphics.GraphicsAdapter.IsProfileSupported().