Terraria: System.Reflection.Metadata.NamespaceDefinitionHandle.FromVirtualIndex
FromVirtualIndex()
static NamespaceDefinitionHandle System.Reflection.Metadata.NamespaceDefinitionHandle.FromVirtualIndex (uint virtualIndex) inline static package
Definition at line 26 of file NamespaceDefinitionHandle.cs.
    {
        if (!HeapHandleType.IsValidHeapOffset(virtualIndex))
        {
            Throw.TooManySubnamespaces();
        }
        return new NamespaceDefinitionHandle(0x80000000u | virtualIndex);
    }
References System.Reflection.Metadata.NamespaceDefinitionHandle.NamespaceDefinitionHandle(), System.Reflection.Metadata.Ecma335.HeapHandleType.IsValidHeapOffset(), and System.Reflection.Throw.TooManySubnamespaces().
Referenced by System.Reflection.Metadata.Ecma335.NamespaceCache.SynthesizeNamespaceData().