Terraria: Terraria.Localization.Language.RandomFromCategory
RandomFromCategory()
static LocalizedText Terraria.Localization.Language.RandomFromCategory (string categoryName, UnifiedRandom random = null) inline static
    {
        return LanguageManager.Instance.RandomFromCategory(categoryName, random);
    }
References Terraria.Localization.LanguageManager.Instance, and Terraria.Localization.LanguageManager.RandomFromCategory().
Referenced by Terraria.Lang.CreateDeathMessage(), Terraria.GameContent.Profiles.VariantNPCProfile.GetNameForVariant(), Terraria.NPC.getNewNPCNameInner(), and Terraria.Lang.GetRandomGameTitle().