Terraria: System.IO.Pipes.PipeStream.PipeValueTaskSource.IOCallback
IOCallback()
static unsafe void System.IO.Pipes.PipeStream.PipeValueTaskSource.IOCallback (uint errorCode, uint numBytes, NativeOverlapped * pOverlapped) inline static private inherited
Definition at line 130 of file PipeStream.cs.
        {
            PipeValueTaskSource pipeValueTaskSource = (PipeValueTaskSource)ThreadPoolBoundHandle.GetNativeOverlappedState(pOverlapped);
            if (Interlocked.Exchange(ref pipeValueTaskSource._result, 0x8000000000000000uL | ((ulong)numBytes << 32) | errorCode) != 0L)
            {
                pipeValueTaskSource.Complete(errorCode, numBytes);
            }
        }
References System.IO.Pipes.PipeStream.PipeValueTaskSource.PipeValueTaskSource(), System.IO.Pipes.PipeStream.PipeValueTaskSource._result, System.IO.Pipes.PipeStream.PipeValueTaskSource.Complete(), System.Threading.Interlocked.Exchange(), System.Threading.ThreadPoolBoundHandle.GetNativeOverlappedState(), and System.L.