Terraria: Terraria.Localization.Language.GetTextValueWith
GetTextValueWith()
static string Terraria.Localization.Language.GetTextValueWith (string key, object obj) inline static
Definition at line 40 of file Language.cs.
    {
        return LanguageManager.Instance.GetText(key).FormatWith(obj);
    }
References Terraria.Localization.LocalizedText.FormatWith(), Terraria.Localization.LanguageManager.GetText(), and Terraria.Localization.LanguageManager.Instance.
Referenced by Terraria.GameContent.ShopHelper.AddHappinessReportText(), Terraria.Lang.AnglerQuestChat(), Terraria.Lang.BartenderChat(), Terraria.Lang.BartenderHelpText(), Terraria.Lang.dialog(), Terraria.NPC.GetChat(), Terraria.GameContent.UI.States.UIBestiaryTest.GetCompletionPercentText(), Terraria.DataStructures.EntryFilterer< T, U >.GetDisplayName(), Terraria.GameContent.ContentRejectionFromSize.GetReason(), Terraria.Main.HelpText(), Terraria.Social.Base.WorkshopIssueReporter.ReportDelayedUploadProblemWithoutKnownReason(), Terraria.Social.Base.WorkshopIssueReporter.ReportDownloadProblem(), Terraria.Social.Base.WorkshopIssueReporter.ReportManifestCreationProblem(), and Terraria.GameContent.UI.States.AWorkshopPublishInfoState< TPublishedObjectType >.UpdateImagePreview().