Terraria: System.IO.Pipes.PipeStream.PipeValueTaskSource.ReleaseResources
ReleaseResources()
unsafe void System.IO.Pipes.PipeStream.PipeValueTaskSource.ReleaseResources () inline package inherited
Definition at line 110 of file PipeStream.cs.
        {
            _cancellationRegistration.Dispose();
            _memoryHandle.Dispose();
            if (_overlapped != null)
            {
                _pipeStream._threadPoolBinding.FreeNativeOverlapped(_overlapped);
                _overlapped = null;
            }
        }
References System.IO.Pipes.PipeStream.PipeValueTaskSource._cancellationRegistration, System.IO.Pipes.PipeStream.PipeValueTaskSource._memoryHandle, System.IO.Pipes.PipeStream.PipeValueTaskSource._overlapped, System.IO.Pipes.PipeStream.PipeValueTaskSource._pipeStream, System.IO.Pipes.PipeStream._threadPoolBinding, System.Buffers.MemoryHandle.Dispose(), System.Threading.CancellationTokenRegistration.Dispose(), and System.Threading.ThreadPoolBoundHandle.FreeNativeOverlapped().
Referenced by System.IO.Pipes.PipeStream.PipeValueTaskSource.Complete(), and System.IO.Pipes.PipeStream.PipeValueTaskSource.Dispose().