Terraria: Terraria.Localization.Language.Exists
Exists()
static bool Terraria.Localization.Language.Exists (string key) inline static
    {
        return LanguageManager.Instance.Exists(key);
    }
References Terraria.Localization.LanguageManager.Exists(), and Terraria.Localization.LanguageManager.Instance.
Referenced by Terraria.Chat.ChatCommandProcessor.AddCommand< T >(), Terraria.GameContent.UI.GameTipsDisplay.AddNewTip(), Terraria.GameContent.Bestiary.BestiaryEntry.Critter(), Terraria.GameContent.Bestiary.BestiaryEntry.Enemy(), Terraria.Lang.FillNameCacheArray< IdClass, IdType >(), Terraria.UI.ItemTooltip.FromLanguageKey(), Terraria.Main.HelpText(), Terraria.Main.startDedInputCallBack(), and Terraria.GameContent.Bestiary.BestiaryEntry.TownNPC().