Terraria: System.IO.Pipes.PipeStream.PipeValueTaskSource.FinishedScheduling
FinishedScheduling()
void System.IO.Pipes.PipeStream.PipeValueTaskSource.FinishedScheduling () inline package inherited
Definition at line 121 of file PipeStream.cs.
        {
            ulong num = Interlocked.Exchange(ref _result, 1uL);
            if (num != 0L)
            {
                Complete((uint)num, (uint)(int)(num >> 32) & 0x7FFFFFFFu);
            }
        }
References System.IO.Pipes.PipeStream.PipeValueTaskSource._result, System.IO.Pipes.PipeStream.PipeValueTaskSource.Complete(), System.Threading.Interlocked.Exchange(), and System.L.
Referenced by System.IO.Pipes.PipeStream.ReadAsyncCore(), System.IO.Pipes.NamedPipeServerStream.WaitForConnectionCoreAsync(), and System.IO.Pipes.PipeStream.WriteAsyncCore().