Terraria: System.IO.Pipes.PipeStream.PipeValueTaskSource.PrepareForOperation
PrepareForOperation()
unsafe void System.IO.Pipes.PipeStream.PipeValueTaskSource.PrepareForOperation (ReadOnlyMemory< byte > memory = default(ReadOnlyMemory<byte>)) inline package inherited
Definition at line 48 of file PipeStream.cs.
        {
            _result = 0uL;
            _memoryHandle = memory.Pin();
            _overlapped = _pipeStream._threadPoolBinding.AllocateNativeOverlapped(_preallocatedOverlapped);
        }
References System.IO.Pipes.PipeStream.PipeValueTaskSource._memoryHandle, System.IO.Pipes.PipeStream.PipeValueTaskSource._overlapped, System.IO.Pipes.PipeStream.PipeValueTaskSource._pipeStream, System.IO.Pipes.PipeStream.PipeValueTaskSource._preallocatedOverlapped, System.IO.Pipes.PipeStream.PipeValueTaskSource._result, System.IO.Pipes.PipeStream._threadPoolBinding, and System.Threading.ThreadPoolBoundHandle.AllocateNativeOverlapped().
Referenced by System.IO.Pipes.PipeStream.ReadAsyncCore(), System.IO.Pipes.NamedPipeServerStream.WaitForConnectionCoreAsync(), and System.IO.Pipes.PipeStream.WriteAsyncCore().