Terraria: System.Threading.Timer.Dispose
Dispose() [2/2]
bool System.Threading.Timer.Dispose (WaitHandle notifyObject) inline
Definition at line 176 of file Timer.cs.
    {
        if (notifyObject == null)
        {
            throw new ArgumentNullException("notifyObject");
        }
        return _timer.Close(notifyObject);
    }
References System.Threading.Timer._timer, and System.Threading.TimerHolder.Close().
Referenced by System.Threading.Tasks.Dataflow.DataflowBlock.ReceiveTarget< T >.CleanupAndComplete(), System.Net.Http.HttpConnectionPool.Dispose(), System.Net.Http.HttpConnectionPoolManager.Dispose(), System.Net.WebSockets.WebSocketBase.KeepAliveTracker.DefaultKeepAliveTracker.Dispose(), System.Net.Mail.SmtpClient.Dispose(), System.Net.WebSockets.ManagedWebSocket.DisposeCore(), System.Transactions.TransactionScope.InternalDispose(), and System.Net.Mail.SmtpClient.Send().