Terraria: System.Threading.Timer.TimerSetup
TimerSetup()
void System.Threading.Timer.TimerSetup (TimerCallback callback, object state, uint dueTime, uint period, bool flowExecutionContext = true) inline private
Definition at line 122 of file Timer.cs.
    {
        if (callback == null)
        {
            throw new ArgumentNullException("callback");
        }
        _timer = new TimerHolder(new TimerQueueTimer(callback, state, dueTime, period, flowExecutionContext));
    }
References System.Threading.Timer._timer, and System.state.
Referenced by System.Threading.Timer.Timer(), System.Threading.Timer.Timer(), System.Threading.Timer.Timer(), System.Threading.Timer.Timer(), and System.Threading.Timer.Timer().