Terraria: Terraria.DataStructures.PlayerInteractionAnchor.Clear
Clear()
void Terraria.DataStructures.PlayerInteractionAnchor.Clear () inline
Definition at line 20 of file PlayerInteractionAnchor.cs.
    {
        interactEntityID = -1;
        X = -1;
        Y = -1;
    }
References Terraria.DataStructures.PlayerInteractionAnchor.interactEntityID, Terraria.DataStructures.PlayerInteractionAnchor.X, and Terraria.DataStructures.PlayerInteractionAnchor.Y.
Referenced by Terraria.GameContent.Tile_Entities.TEDisplayDoll.OnInventoryDraw(), Terraria.GameContent.Tile_Entities.TEHatRack.OnInventoryDraw(), Terraria.GameContent.Tile_Entities.TEDisplayDoll.OnPlayerUpdate(), Terraria.GameContent.Tile_Entities.TEHatRack.OnPlayerUpdate(), Terraria.Player.ToggleCreativeMenu(), and Terraria.Player.ToggleInv().