Terraria: Terraria.GameContent.CoinLossRevengeSystem.RemoveExpiredOrInvalidMarkers
RemoveExpiredOrInvalidMarkers()
void Terraria.GameContent.CoinLossRevengeSystem.RemoveExpiredOrInvalidMarkers () inline private
    {
        lock (_markersLock)
        {
            IEnumerable<RevengeMarker> enumerable = _markers.Where((RevengeMarker x) => x.IsExpired(_gameTime));
            IEnumerable<RevengeMarker> enumerable2 = _markers.Where((RevengeMarker x) => x.IsInvalid());
            _markers.RemoveAll((RevengeMarker x) => x.IsInvalid());
            _markers.RemoveAll((RevengeMarker x) => x.IsExpired(_gameTime));
            if (!Main.dedServ)
            {
                return;
            }
            foreach (RevengeMarker item in enumerable)
            {
                NetMessage.SendData(127, -1, -1, null, item.UniqueID);
            }
            foreach (RevengeMarker item2 in enumerable2)
            {
                NetMessage.SendData(127, -1, -1, null, item2.UniqueID);
            }
        }
    }
References Terraria.GameContent.CoinLossRevengeSystem._gameTime, Terraria.GameContent.CoinLossRevengeSystem._markers, Terraria.GameContent.CoinLossRevengeSystem._markersLock, Terraria.Main.dedServ, Terraria.GameContent.CoinLossRevengeSystem.RevengeMarker.IsExpired(), Terraria.GameContent.CoinLossRevengeSystem.RevengeMarker.IsInvalid(), Terraria.NetMessage.SendData(), and Terraria.GameContent.CoinLossRevengeSystem.RevengeMarker.UniqueID.
Referenced by Terraria.GameContent.CoinLossRevengeSystem.CheckRespawns(), and Terraria.GameContent.CoinLossRevengeSystem.Update().