Terraria: System.Reflection.Metadata.StringHandle.FromOffset
FromOffset()
static StringHandle System.Reflection.Metadata.StringHandle.FromOffset (int heapOffset) inline static package
Definition at line 98 of file StringHandle.cs.
    {
        return new StringHandle(0u | (uint)heapOffset);
    }
References System.Reflection.Metadata.StringHandle.StringHandle().
Referenced by System.Reflection.Metadata.Ecma335.AssemblyTableReader.GetCulture(), System.Reflection.Metadata.Ecma335.AssemblyRefTableReader.GetCulture(), System.Reflection.Metadata.NamespaceDefinitionHandle.GetFullName(), System.Reflection.Metadata.Ecma335.ImplMapTableReader.GetImport(), System.Reflection.Metadata.Ecma335.AssemblyTableReader.GetName(), System.Reflection.Metadata.Ecma335.ModuleTableReader.GetName(), System.Reflection.Metadata.Ecma335.FileTableReader.GetName(), System.Reflection.Metadata.Ecma335.EventTableReader.GetName(), System.Reflection.Metadata.Ecma335.FieldTableReader.GetName(), System.Reflection.Metadata.Ecma335.GenericParamTableReader.GetName(), System.Reflection.Metadata.Ecma335.AssemblyRefTableReader.GetName(), System.Reflection.Metadata.Ecma335.LocalConstantTableReader.GetName(), System.Reflection.Metadata.Ecma335.LocalVariableTableReader.GetName(), System.Reflection.Metadata.Ecma335.ManifestResourceTableReader.GetName(), System.Reflection.Metadata.Ecma335.MemberRefTableReader.GetName(), System.Reflection.Metadata.Ecma335.MethodTableReader.GetName(), System.Reflection.Metadata.Ecma335.ModuleRefTableReader.GetName(), System.Reflection.Metadata.Ecma335.ParamTableReader.GetName(), System.Reflection.Metadata.Ecma335.PropertyTableReader.GetName(), System.Reflection.Metadata.Ecma335.TypeDefTableReader.GetName(), System.Reflection.Metadata.Ecma335.TypeRefTableReader.GetName(), System.Reflection.Metadata.Ecma335.TypeDefTableReader.GetNamespace(), System.Reflection.Metadata.Ecma335.TypeRefTableReader.GetNamespace(), System.Reflection.Metadata.Ecma335.StringHeap.GetNextHandle(), System.Reflection.Metadata.Ecma335.NamespaceCache.GetSimpleName(), System.Reflection.Metadata.Ecma335.ExportedTypeTableReader.GetTypeName(), System.Reflection.Metadata.Ecma335.ExportedTypeTableReader.GetTypeNamespaceString(), and System.Reflection.Metadata.Ecma335.MetadataTokens.StringHandle().