Terraria: AssetSourceController.UseResourcePacks
UseResourcePacks()
void AssetSourceController.UseResourcePacks (ResourcePackList resourcePacks) inline
     {
         if (this.OnResourcePackChange != null)
         {
             this.OnResourcePackChange(resourcePacks);
         }
         ActiveResourcePackList = resourcePacks;
         List<IContentSource> list = new List<IContentSource>(from pack in resourcePacks.EnabledPacks
             orderby pack.SortingOrder
             select pack.GetContentSource());
         list.AddRange(_staticSources);
         foreach (IContentSource item in list)
         {
             item.ClearRejections();
         }
         List<IContentSource> list2 = new List<IContentSource>();
         for (int num = list.Count - 1; num >= 0; num--)
         {
             list2.Add(list[num]);
         }
         _assetRepository.SetSources((IEnumerable<IContentSource>)list, (AssetRequestMode)1);
         LanguageManager.Instance.UseSources(list2);
         Main.audioSystem.UseSources(list2);
         SoundEngine.Reload();
         Main.changeTheTitle = true;
     }
References _assetRepository, _staticSources, ActiveResourcePackList, Main.audioSystem, Main.changeTheTitle, ResourcePackList.EnabledPacks, LanguageManager.Instance, OnResourcePackChange, SoundEngine.Reload(), IAssetRepository.SetSources(), IAudioSystem.UseSources(), and LanguageManager.UseSources().
Referenced by AssetSourceController(), UIResourcePackSelectionMenu.ApplyListChanges(), Main.LoadContent(), and Refresh().