Terraria: Internal.Cryptography.BasicSymmetricCipherNCrypt.Reset
Reset()
void Internal.Cryptography.BasicSymmetricCipherNCrypt.Reset () inline private
Definition at line 76 of file BasicSymmetricCipherNCrypt.cs.
    {
        if (base.IV != null)
        {
            CngProperty property = new CngProperty("IV", base.IV, CngPropertyOptions.None);
            _cngKey.SetProperty(property);
        }
    }
References Internal.Cryptography.BasicSymmetricCipherNCrypt._cngKey, and System.Security.Cryptography.CngKey.SetProperty().
Referenced by Internal.Cryptography.BasicSymmetricCipherNCrypt.BasicSymmetricCipherNCrypt(), and Internal.Cryptography.BasicSymmetricCipherNCrypt.TransformFinal().