Terraria: System.Linq.Parallel.ExceptQueryOperator.OrderedExceptQueryOperatorEnumerator.MoveNext
MoveNext() [2/2]
override bool System.Linq.Parallel.ExceptQueryOperator< TInputOutput >.OrderedExceptQueryOperatorEnumerator< TLeftKey >.MoveNext ([AllowNull] ref TInputOutput currentElement, [AllowNull] ref TLeftKey currentKey) inline package
Definition at line 96 of file ExceptQueryOperator.cs.
        {
            if (_outputEnumerator == null)
            {
                HashSet<TInputOutput> hashSet = new HashSet<TInputOutput>(_comparer);
                Pair<TInputOutput, NoKeyMemoizationRequired> currentElement2 = default(Pair<TInputOutput, NoKeyMemoizationRequired>);
                int currentKey2 = 0;
                int num = 0;
                while (_rightSource.MoveNext(ref currentElement2, ref currentKey2))
                {
                    if ((num++ & 0x3F) == 0)
                    {
                        _cancellationToken.ThrowIfCancellationRequested();
                    }
                    hashSet.Add(currentElement2.First);
                }
                Dictionary<Wrapper<TInputOutput>, Pair<TInputOutput, TLeftKey>> dictionary = new Dictionary<Wrapper<TInputOutput>, Pair<TInputOutput, TLeftKey>>(new WrapperEqualityComparer<TInputOutput>(_comparer));
                Pair<TInputOutput, NoKeyMemoizationRequired> currentElement3 = default(Pair<TInputOutput, NoKeyMemoizationRequired>);
                TLeftKey currentKey3 = default(TLeftKey);
                while (_leftSource.MoveNext(ref currentElement3, ref currentKey3))
                {
                    if ((num++ & 0x3F) == 0)
                    {
                        _cancellationToken.ThrowIfCancellationRequested();
                    }
                    if (!hashSet.Contains(currentElement3.First))
                    {
                        Wrapper<TInputOutput> key = new Wrapper<TInputOutput>(currentElement3.First);
                        if (!dictionary.TryGetValue(key, out var value) || _leftKeyComparer.Compare(currentKey3, value.Second) < 0)
{
                            dictionary[key] = new Pair<TInputOutput, TLeftKey>(currentElement3.First, currentKey3);
                        }
                    }
                }
                _outputEnumerator = dictionary.GetEnumerator();
            }
            if (_outputEnumerator.MoveNext())
            {
                Pair<TInputOutput, TLeftKey> value2 = _outputEnumerator.Current.Value;
                currentElement = value2.First;
                currentKey = value2.Second;
                return true;
            }
            return false;
        }
References System.Linq.Parallel.ExceptQueryOperator< TInputOutput >.OrderedExceptQueryOperatorEnumerator< TLeftKey >._cancellationToken, System.Linq.Parallel.ExceptQueryOperator< TInputOutput >.OrderedExceptQueryOperatorEnumerator< TLeftKey >._comparer, System.Linq.Parallel.ExceptQueryOperator< TInputOutput >.OrderedExceptQueryOperatorEnumerator< TLeftKey >._leftKeyComparer, System.Linq.Parallel.ExceptQueryOperator< TInputOutput >.OrderedExceptQueryOperatorEnumerator< TLeftKey >._leftSource, System.Linq.Parallel.ExceptQueryOperator< TInputOutput >.OrderedExceptQueryOperatorEnumerator< TLeftKey >._outputEnumerator, System.Linq.Parallel.ExceptQueryOperator< TInputOutput >.OrderedExceptQueryOperatorEnumerator< TLeftKey >._rightSource, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Collections.Generic.IComparer< in T >.Compare(), System.Collections.Generic.Dictionary< TKey, TValue >.Contains(), System.dictionary, System.Collections.Generic.Dictionary< TKey, TValue >.GetEnumerator(), System.key, System.Threading.CancellationToken.ThrowIfCancellationRequested(), and System.value.