Terraria: CoinLossRevengeSystem.CacheEnemy
CacheEnemy()
void CoinLossRevengeSystem.CacheEnemy (NPC npc) inline
     {
         if (npc.boss || npc.realLife != -1 || npc.rarity > 0 || npc.extraValue < MinimumCoinsForCaching || npc.position.X < Main.leftWorld + 640f + 16f || npc.position.X + (float)npc.width > Main.rightWorld - 640f - 32f || npc.position.Y < Main.topWorld + 640f + 16f || npc.position.Y > Main.bottomWorld - 640f - 32f - (float)npc.height)
         {
             return;
         }
         int num = npc.netID;
         if (NPCID.Sets.RespawnEnemyID.TryGetValue(num, out var value))
         {
             num = value;
         }
         if (num != 0)
         {
             RevengeMarker marker = new RevengeMarker(npc.Center, num, npc.GetLifePercent(), npc.type, npc.aiStyle, npc.extraValue, npc.value, npc.SpawnedFromStatue, _gameTime);
             AddMarker(marker);
             if (Main.netMode == 2)
             {
                 NetMessage.SendCoinLossRevengeMarker(marker);
             }
             if (DisplayCaching)
             {
                 Main.NewText("Cached " + npc.GivenOrTypeName);
             }
         }
     }
References _gameTime, AddMarker(), NPC.aiStyle, NPC.boss, Main.bottomWorld, Entity.Center, DisplayCaching, NPC.extraValue, NPC.GetLifePercent(), NPC.GivenOrTypeName, Entity.height, Main.leftWorld, MinimumCoinsForCaching, NPC.netID, Main.netMode, Main.NewText(), Entity.position, NPC.rarity, NPC.realLife, NPCID.Sets.RespawnEnemyID, Main.rightWorld, NetMessage.SendCoinLossRevengeMarker(), NPC.SpawnedFromStatue, Main.topWorld, NPC.type, NPC.value, and Entity.width.
Referenced by NPC.CheckActive().