Terraria: System.Security.Cryptography.RandomNumberGenerator.Fill
Fill()
static void System.Security.Cryptography.RandomNumberGenerator.Fill (Span< byte > data) inline static inherited
Definition at line 85 of file RandomNumberGenerator.cs.
    {
        RandomNumberGeneratorImplementation.FillSpan(data);
    }
References System.Security.Cryptography.RandomNumberGeneratorImplementation.FillSpan().
Referenced by System.Security.Cryptography.Rfc2898DeriveBytes.Rfc2898DeriveBytes(), System.Security.Cryptography.X509Certificates.CertificateRequest.CreateSelfSigned(), System.Security.Cryptography.CngKeyLite.ExportPkcs8KeyBlob(), System.Security.Cryptography.CngKey.ExportPkcs8KeyBlob(), System.Security.Cryptography.RsaPaddingProcessor.FillNonZeroBytes(), System.Security.Cryptography.CngPkcs8.FillRandomAsciiString(), Internal.Cryptography.DesImplementation.GenerateKey(), System.Security.Cryptography.DESCryptoServiceProvider.GenerateKey(), Internal.Cryptography.Helpers.GenerateRandom(), System.Net.Http.AuthenticationHelper.GetRandomAlphaNumericString(), Internal.Cryptography.UniversalCryptoEncryptor.PadBlock(), System.Security.Cryptography.RsaPaddingProcessor.PadOaep(), and System.Security.Cryptography.KeyFormatHelper.WriteEncryptedPkcs8().