Terraria: System.Security.Cryptography.RandomNumberGenerator.GetNonZeroBytes
GetNonZeroBytes() [2/2]
virtual void System.Security.Cryptography.RandomNumberGenerator.GetNonZeroBytes (Span< byte > data) inline virtual
Reimplemented in System.Security.Cryptography.RandomNumberGeneratorImplementation, and System.Security.Cryptography.RNGCryptoServiceProvider.
Definition at line 70 of file RandomNumberGenerator.cs.
    {
        byte[] array = ArrayPool<byte>.Shared.Rent(data.Length);
        try
        {
            GetNonZeroBytes(array);
            new ReadOnlySpan<byte>(array, 0, data.Length).CopyTo(data);
        }
        finally
        {
            Array.Clear(array, 0, data.Length);
            ArrayPool<byte>.Shared.Return(array);
        }
    }
References System.array, System.Array.Clear(), System.ReadOnlySpan< T >.CopyTo(), System.Security.Cryptography.RandomNumberGenerator.GetNonZeroBytes(), System.Span< T >.Length, and System.Buffers.ArrayPool< T >.Shared.