Terraria: System.Security.Cryptography.RandomNumberGenerator.GetBytes
GetBytes() [2/4]
virtual void System.Security.Cryptography.RandomNumberGenerator.GetBytes (byte[] data, int offset, int count) inline virtual
Reimplemented in System.Security.Cryptography.RandomNumberGeneratorImplementation, and System.Security.Cryptography.RNGCryptoServiceProvider.
Definition at line 34 of file RandomNumberGenerator.cs.
    {
        VerifyGetBytes(data, offset, count);
        if (count > 0)
        {
            if (offset == 0 && count == data.Length)
            {
                GetBytes(data);
                return;
            }
            byte[] array = new byte[count];
            GetBytes(array);
            Buffer.BlockCopy(array, 0, data, offset, count);
        }
    }
References System.array, System.Buffer.BlockCopy(), System.count, System.Security.Cryptography.RandomNumberGenerator.GetBytes(), System.offset, and System.Security.Cryptography.RandomNumberGenerator.VerifyGetBytes().