Terraria: System.Security.Cryptography.RandomNumberGenerator.GetBytes
GetBytes() [1/4]
void System.Security.Cryptography.RandomNumberGenerator.GetBytes (byte[] data) abstract
Referenced by System.Security.Cryptography.DESCryptoServiceProvider.CreateTransform(), System.Security.Cryptography.RC2CryptoServiceProvider.CreateTransform(), Internal.Cryptography.AesImplementation.GenerateIV(), Internal.Cryptography.DesImplementation.GenerateIV(), Internal.Cryptography.RC2Implementation.GenerateIV(), Internal.Cryptography.TripleDesImplementation.GenerateIV(), System.Security.Cryptography.DESCryptoServiceProvider.GenerateIV(), System.Security.Cryptography.RC2CryptoServiceProvider.GenerateIV(), Internal.Cryptography.AesImplementation.GenerateKey(), Internal.Cryptography.RC2Implementation.GenerateKey(), Internal.Cryptography.TripleDesImplementation.GenerateKey(), System.Security.Cryptography.RC2CryptoServiceProvider.GenerateKey(), System.Security.Cryptography.RNGCryptoServiceProvider.GetBytes(), System.Security.Cryptography.RandomNumberGenerator.GetBytes(), System.Security.Cryptography.RNGCryptoServiceProvider.GetBytes(), System.Security.Cryptography.RandomNumberGenerator.GetBytes(), and System.Security.Cryptography.RNGCryptoServiceProvider.GetBytes().