Terraria: Terraria.GameContent.UI.ResourceSets.HorizontalBarsPlayerResourcesDisplaySet.Draw
Draw()
void Terraria.GameContent.UI.ResourceSets.HorizontalBarsPlayerResourcesDisplaySet.Draw () inline
Implements Terraria.GameContent.UI.ResourceSets.IPlayerResourcesDisplaySet.
    {
        PrepareFields(Main.LocalPlayer);
        SpriteBatch spriteBatch = Main.spriteBatch;
        int num = 16;
        int num2 = 18;
        int num3 = Main.screenWidth - 300 - 22 + num;
        if (_drawTextStyle == 2)
        {
            num2 += 2;
            DrawLifeBarText(spriteBatch, new Vector2(num3, num2));
            DrawManaText(spriteBatch);
        }
        else if (_drawTextStyle == 1)
        {
            num2 += 4;
            DrawLifeBarText(spriteBatch, new Vector2(num3, num2));
        }
        Vector2 vector = new Vector2(num3, num2);
        vector.X += (_maxSegmentCount - _hpSegmentsCount) * _panelMiddleHP.Width();
        bool isHovered = false;
        ResourceDrawSettings resourceDrawSettings = default(ResourceDrawSettings);
        resourceDrawSettings.ElementCount = _hpSegmentsCount + 2;
        resourceDrawSettings.ElementIndexOffset = 0;
        resourceDrawSettings.TopLeftAnchor = vector;
        resourceDrawSettings.GetTextureMethod = LifePanelDrawer;
        resourceDrawSettings.OffsetPerDraw = Vector2.Zero;
        resourceDrawSettings.OffsetPerDrawByTexturePercentile = Vector2.UnitX;
        resourceDrawSettings.OffsetSpriteAnchor = Vector2.Zero;
        resourceDrawSettings.OffsetSpriteAnchorByTexturePercentile = Vector2.Zero;
        resourceDrawSettings.Draw(spriteBatch, ref isHovered);
        resourceDrawSettings = default(ResourceDrawSettings);
        resourceDrawSettings.ElementCount = _hpSegmentsCount;
        resourceDrawSettings.ElementIndexOffset = 0;
        resourceDrawSettings.TopLeftAnchor = vector + new Vector2(6f, 6f);
        resourceDrawSettings.GetTextureMethod = LifeFillingDrawer;
        resourceDrawSettings.OffsetPerDraw = new Vector2(_hpFill.Width(), 0f);
        resourceDrawSettings.OffsetPerDrawByTexturePercentile = Vector2.Zero;
        resourceDrawSettings.OffsetSpriteAnchor = Vector2.Zero;
        resourceDrawSettings.OffsetSpriteAnchorByTexturePercentile = Vector2.Zero;
        resourceDrawSettings.Draw(spriteBatch, ref isHovered);
        _hpHovered = isHovered;
        isHovered = false;
        Vector2 vector2 = new Vector2(num3 - 10, num2 + 24);
        vector2.X += (_maxSegmentCount - _mpSegmentsCount) * _panelMiddleMP.Width();
        resourceDrawSettings = default(ResourceDrawSettings);
        resourceDrawSettings.ElementCount = _mpSegmentsCount + 2;
        resourceDrawSettings.ElementIndexOffset = 0;
        resourceDrawSettings.TopLeftAnchor = vector2;
        resourceDrawSettings.GetTextureMethod = ManaPanelDrawer;
        resourceDrawSettings.OffsetPerDraw = Vector2.Zero;
        resourceDrawSettings.OffsetPerDrawByTexturePercentile = Vector2.UnitX;
        resourceDrawSettings.OffsetSpriteAnchor = Vector2.Zero;
        resourceDrawSettings.OffsetSpriteAnchorByTexturePercentile = Vector2.Zero;
        resourceDrawSettings.Draw(spriteBatch, ref isHovered);
        resourceDrawSettings = default(ResourceDrawSettings);
        resourceDrawSettings.ElementCount = _mpSegmentsCount;
        resourceDrawSettings.ElementIndexOffset = 0;
        resourceDrawSettings.TopLeftAnchor = vector2 + new Vector2(6f, 6f);
        resourceDrawSettings.GetTextureMethod = ManaFillingDrawer;
        resourceDrawSettings.OffsetPerDraw = new Vector2(_mpFill.Width(), 0f);
        resourceDrawSettings.OffsetPerDrawByTexturePercentile = Vector2.Zero;
        resourceDrawSettings.OffsetSpriteAnchor = Vector2.Zero;
        resourceDrawSettings.OffsetSpriteAnchorByTexturePercentile = Vector2.Zero;
        resourceDrawSettings.Draw(spriteBatch, ref isHovered);
        _mpHovered = isHovered;
    }
References Terraria.GameContent.UI.ResourceSets.HorizontalBarsPlayerResourcesDisplaySet._drawTextStyle, Terraria.GameContent.UI.ResourceSets.HorizontalBarsPlayerResourcesDisplaySet._hpFill, Terraria.GameContent.UI.ResourceSets.HorizontalBarsPlayerResourcesDisplaySet._hpHovered, Terraria.GameContent.UI.ResourceSets.HorizontalBarsPlayerResourcesDisplaySet._hpSegmentsCount, Terraria.GameContent.UI.ResourceSets.HorizontalBarsPlayerResourcesDisplaySet._maxSegmentCount, Terraria.GameContent.UI.ResourceSets.HorizontalBarsPlayerResourcesDisplaySet._mpFill, Terraria.GameContent.UI.ResourceSets.HorizontalBarsPlayerResourcesDisplaySet._mpHovered, Terraria.GameContent.UI.ResourceSets.HorizontalBarsPlayerResourcesDisplaySet._mpSegmentsCount, Terraria.GameContent.UI.ResourceSets.HorizontalBarsPlayerResourcesDisplaySet._panelMiddleHP, Terraria.GameContent.UI.ResourceSets.HorizontalBarsPlayerResourcesDisplaySet._panelMiddleMP, Terraria.GameContent.UI.ResourceSets.HorizontalBarsPlayerResourcesDisplaySet.DrawLifeBarText(), Terraria.GameContent.UI.ResourceSets.HorizontalBarsPlayerResourcesDisplaySet.DrawManaText(), Terraria.GameContent.UI.ResourceSets.HorizontalBarsPlayerResourcesDisplaySet.LifeFillingDrawer(), Terraria.GameContent.UI.ResourceSets.HorizontalBarsPlayerResourcesDisplaySet.LifePanelDrawer(), Terraria.Main.LocalPlayer, Terraria.GameContent.UI.ResourceSets.HorizontalBarsPlayerResourcesDisplaySet.ManaFillingDrawer(), Terraria.GameContent.UI.ResourceSets.HorizontalBarsPlayerResourcesDisplaySet.ManaPanelDrawer(), Terraria.GameContent.UI.ResourceSets.HorizontalBarsPlayerResourcesDisplaySet.PrepareFields(), and Terraria.Main.spriteBatch.