Terraria: Terraria.GameContent.UI.ResourceSets.HorizontalBarsPlayerResourcesDisplaySet.FillBarByValues
FillBarByValues()
static void Terraria.GameContent.UI.ResourceSets.HorizontalBarsPlayerResourcesDisplaySet.FillBarByValues (int elementIndex, Asset< Texture2D > sprite, int segmentsCount, float fillPercent, out Vector2 offset, out float drawScale, out Rectangle? sourceRect) inline static private
Definition at line 232 of file HorizontalBarsPlayerResourcesDisplaySet.cs.
    {
        sourceRect = null;
        offset = Vector2.Zero;
        float num = 1f;
        float num2 = 1f / (float)segmentsCount;
        float t = 1f - fillPercent;
        float lerpValue = Utils.GetLerpValue(num2 * (float)elementIndex, num2 * (float)(elementIndex + 1), t, clamped: true);
        num = 1f - lerpValue;
        drawScale = 1f;
        Rectangle value = sprite.Frame();
        int num3 = (int)((float)value.Width * (1f - num));
        offset.X += num3;
        value.X += num3;
        value.Width -= num3;
        sourceRect = value;
    }
References Terraria.Utils.GetLerpValue(), and Microsoft.Xna.Framework.Vector2.Zero.
Referenced by Terraria.GameContent.UI.ResourceSets.HorizontalBarsPlayerResourcesDisplaySet.LifeFillingDrawer(), and Terraria.GameContent.UI.ResourceSets.HorizontalBarsPlayerResourcesDisplaySet.ManaFillingDrawer().