Terraria: System.Reflection.FieldInfo.GetValue
GetValue() [2/2]
object? System.Reflection.FieldInfo.GetValue (object? obj) abstract inherited
Referenced by System.Runtime.Serialization.FastInvokerBuilder.CreateGetter(), System.Attribute.Equals(), System.ValueType.Equals(), Terraria.Lang.FillNameCacheArray< IdClass, IdType >(), System.Runtime.CompilerServices.AsyncMethodBuilderCore.GetAsyncStateMachineDescription(), System.ComponentModel.AttributeCollection.GetDefaultAttribute(), System.Attribute.GetHashCode(), System.Data.Common.SqlUdtStorage.GetStaticNullForUdtTypeCore(), System.Runtime.Serialization.SerializationFieldInfo.GetValue(), Terraria.Lang.InitializeLegacyLocalization(), System.Linq.Expressions.Interpreter.LoadFieldInstruction.Run(), and System.Linq.Expressions.Interpreter.LoadStaticFieldInstruction.Run().