Terraria: System.Reflection.FieldInfo.SetValue
SetValue() [2/3]
void System.Reflection.FieldInfo.SetValue (object? obj, object? value) inline inherited
Definition at line 108 of file FieldInfo.cs.
    {
        SetValue(obj, value, BindingFlags.Default, Type.DefaultBinder, null);
    }
References System.Type.DefaultBinder, System.obj, System.Reflection.FieldInfo.SetValue(), and System.value.
Referenced by System.Reflection.CustomAttribute.AddCustomAttributes(), System.Runtime.Serialization.FastInvokerBuilder.CreateSetter(), System.Xml.Serialization.ReflectionXmlSerializationReaderHelper.GetSetMemberValueDelegateWithType< TObj, TParam >(), System.Linq.Expressions.Interpreter.StoreFieldInstruction.Run(), System.Linq.Expressions.Interpreter.StoreStaticFieldInstruction.Run(), System.Runtime.Serialization.SerializationFieldInfo.SetValue(), System.Reflection.FieldInfo.SetValue(), and System.Linq.Expressions.Interpreter.FieldByRefUpdater.Update().