Terraria: System.Transactions.TransactionException.Create
Create() [3/4]
static TransactionException System.Transactions.TransactionException.Create (string message, Guid distributedTxId) inline static package inherited
Definition at line 84 of file TransactionException.cs.
    {
        if (IncludeDistributedTxId(distributedTxId))
        {
            return new TransactionException(System.SR.Format(System.SR.DistributedTxIDInTransactionException, message, distributedTxId));
        }
        return new TransactionException(message);
    }
References System.Transactions.TransactionException.TransactionException(), System.Runtime.Serialization.Dictionary, System.SR.DistributedTxIDInTransactionException, System.SR.Format(), and System.Transactions.TransactionException.IncludeDistributedTxId().