Terraria: Microsoft.Xna.Framework.Graphics.BlendState.SetDefaults
SetDefaults()
void Microsoft.Xna.Framework.Graphics.BlendState.SetDefaults () inline private
Definition at line 220 of file BlendState.cs.
    {
        ThrowIfBound();
        cachedColorSourceBlend = Blend.One;
        ThrowIfBound();
        cachedColorDestinationBlend = Blend.Zero;
        ThrowIfBound();
        cachedColorBlendFunction = BlendFunction.Add;
        ThrowIfBound();
        cachedAlphaSourceBlend = Blend.One;
        ThrowIfBound();
        cachedAlphaDestinationBlend = Blend.Zero;
        ThrowIfBound();
        cachedAlphaBlendFunction = BlendFunction.Add;
        ThrowIfBound();
        cachedColorWriteChannels = ColorWriteChannels.All;
        ThrowIfBound();
        cachedColorWriteChannels1 = ColorWriteChannels.All;
        ThrowIfBound();
        cachedColorWriteChannels2 = ColorWriteChannels.All;
        ThrowIfBound();
        cachedColorWriteChannels3 = ColorWriteChannels.All;
        Color white = Color.White;
        ThrowIfBound();
        cachedBlendFactor = white;
        ThrowIfBound();
        cachedMultiSampleMask = -1;
    }
References Microsoft.Xna.Framework.Graphics.BlendState.cachedAlphaBlendFunction, Microsoft.Xna.Framework.Graphics.BlendState.cachedAlphaDestinationBlend, Microsoft.Xna.Framework.Graphics.BlendState.cachedAlphaSourceBlend, Microsoft.Xna.Framework.Graphics.BlendState.cachedBlendFactor, Microsoft.Xna.Framework.Graphics.BlendState.cachedColorBlendFunction, Microsoft.Xna.Framework.Graphics.BlendState.cachedColorDestinationBlend, Microsoft.Xna.Framework.Graphics.BlendState.cachedColorSourceBlend, Microsoft.Xna.Framework.Graphics.BlendState.cachedColorWriteChannels, Microsoft.Xna.Framework.Graphics.BlendState.cachedColorWriteChannels1, Microsoft.Xna.Framework.Graphics.BlendState.cachedColorWriteChannels2, Microsoft.Xna.Framework.Graphics.BlendState.cachedColorWriteChannels3, Microsoft.Xna.Framework.Graphics.BlendState.cachedMultiSampleMask, Microsoft.Xna.Framework.Graphics.BlendState.ThrowIfBound(), and Microsoft.Xna.Framework.Color.White.
Referenced by Microsoft.Xna.Framework.Graphics.BlendState.BlendState(), and Microsoft.Xna.Framework.Graphics.BlendState.BlendState().