Terraria: System.Transactions.TransactionException.Create
Create() [1/4]
static TransactionException System.Transactions.TransactionException.Create (string message, Exception innerException) inline static package inherited
Definition at line 20 of file TransactionException.cs.
    {
        TransactionsEtwProvider log = TransactionsEtwProvider.Log;
        if (log.IsEnabled())
        {
            log.TransactionExceptionTrace(TransactionExceptionType.TransactionException, message, (innerException == null) ? string.Empty : innerException.ToString());
        }
        return new TransactionException(message, innerException);
    }
References System.Transactions.TransactionException.TransactionException(), System.Runtime.Serialization.Dictionary, and System.Transactions.TransactionsEtwProvider.Log.
Referenced by System.Transactions.TransactionException.Create(), System.Transactions.TransactionStatePromotedNonMSDTCIndoubt.CreateAbortingClone(), System.Transactions.TransactionStatePromotedNonMSDTCSinglePhaseCommit.CreateAbortingClone(), System.Transactions.TransactionStatePromotedNonMSDTCVolatilePhase1.CreateAbortingClone(), System.Transactions.TransactionStatePromotedNonMSDTCIndoubt.CreateBlockingClone(), System.Transactions.TransactionStatePromotedNonMSDTCSinglePhaseCommit.CreateBlockingClone(), System.Transactions.TransactionStatePromotedNonMSDTCVolatilePhase1.CreateBlockingClone(), System.Transactions.TransactionException.CreateTransactionStateException(), System.Transactions.TransactionStatePromotedNonMSDTCSinglePhaseCommit.EnlistPromotableSinglePhase(), System.Transactions.TransactionStatePromotedNonMSDTCVolatilePhase1.EnlistPromotableSinglePhase(), System.Transactions.TransactionStatePromotedNonMSDTCSinglePhaseCommit.EnlistVolatile(), System.Transactions.TransactionStatePromotedNonMSDTCVolatilePhase1.EnlistVolatile(), System.Transactions.TransactionStatePromotedNonMSDTCSinglePhaseCommit.EnlistVolatile(), System.Transactions.TransactionStatePromotedNonMSDTCVolatilePhase1.EnlistVolatile(), and System.Transactions.TransactionScope.TimerCallback().