Terraria: System.Transactions.TransactionException.CreateEnlistmentStateException
CreateEnlistmentStateException()
static Exception System.Transactions.TransactionException.CreateEnlistmentStateException (Exception innerException, Guid distributedTxId) inline static package inherited
Definition at line 40 of file TransactionException.cs.
    {
        string text = System.SR.EnlistmentStateException;
        if (IncludeDistributedTxId(distributedTxId))
        {
            text = System.SR.Format(System.SR.DistributedTxIDInTransactionException, text, distributedTxId);
        }
        TransactionsEtwProvider log = TransactionsEtwProvider.Log;
        if (log.IsEnabled())
        {
            log.TransactionExceptionTrace(TransactionExceptionType.InvalidOperationException, text, (innerException == null) ? string.Empty : innerException.ToString());
        }
        return new InvalidOperationException(text, innerException);
    }
References System.Runtime.Serialization.Dictionary, System.SR.DistributedTxIDInTransactionException, System.SR.EnlistmentStateException, System.SR.Format(), System.Transactions.TransactionException.IncludeDistributedTxId(), System.Transactions.InvalidOperationException, System.Transactions.TransactionsEtwProvider.Log, and System.text.
Referenced by System.Transactions.EnlistmentState.Aborted(), System.Transactions.EnlistmentState.ChangeStateCommitting(), System.Transactions.EnlistmentState.ChangeStateDelegated(), System.Transactions.EnlistmentState.ChangeStatePreparing(), System.Transactions.EnlistmentState.ChangeStatePromoted(), System.Transactions.EnlistmentState.ChangeStateSinglePhaseCommit(), System.Transactions.EnlistmentState.Committed(), System.Transactions.EnlistmentState.EnlistmentDone(), System.Transactions.EnlistmentState.ForceRollback(), System.Transactions.EnlistmentState.InDoubt(), System.Transactions.EnlistmentState.InternalAborted(), System.Transactions.EnlistmentState.InternalCommitted(), System.Transactions.EnlistmentState.InternalIndoubt(), System.Transactions.EnlistmentState.Prepared(), and System.Transactions.EnlistmentState.RecoveryInformation().