Terraria: Microsoft.Xna.Framework.Graphics.BlendState.Apply
Apply()
unsafe void Microsoft.Xna.Framework.Graphics.BlendState.Apply (GraphicsDevice device) inline package
Definition at line 294 of file BlendState.cs.
    {
        if (isDisposed)
        {
            throw new ObjectDisposedException(typeof(BlendState).Name);
        }
        if (_parent != device)
        {
            ProfileCapabilities profileCapabilities = device._profileCapabilities;
            if (!profileCapabilities.SeparateAlphaBlend)
            {
                Blend alphaBlend = cachedAlphaSourceBlend;
                Blend colorBlend = cachedColorSourceBlend;
                if (GraphicsHelpers.IsSeparateBlend(colorBlend, alphaBlend))
                {
                    profileCapabilities.ThrowNotSupportedException(FrameworkResources.ProfileNoSeparateAlphaBlend, "ColorSourceBlend", "AlphaSourceBlend");
                }
                Blend alphaBlend2 = cachedAlphaDestinationBlend;
                Blend colorBlend2 = cachedColorDestinationBlend;
                if (GraphicsHelpers.IsSeparateBlend(colorBlend2, alphaBlend2))
                {
                    profileCapabilities.ThrowNotSupportedException(FrameworkResources.ProfileNoSeparateAlphaBlend, "ColorDestinationBlend", "AlphaDestinationBlend");
                }
                if (cachedColorBlendFunction != cachedAlphaBlendFunction)
                {
                    profileCapabilities.ThrowNotSupportedException(FrameworkResources.ProfileNoSeparateAlphaBlend, "ColorBlendFunction", "AlphaBlendFunction");
                }
            }
            if (!profileCapabilities.DestBlendSrcAlphaSat)
            {
                if (cachedColorDestinationBlend == Blend.SourceAlphaSaturation)
                {
                    profileCapabilities.ThrowNotSupportedException(FrameworkResources.ProfileFeatureNotSupported, "ColorDestinationBlend = Blend.SourceAlphaSaturation");
                }
                if (cachedAlphaDestinationBlend == Blend.SourceAlphaSaturation)
                {
                    profileCapabilities.ThrowNotSupportedException(FrameworkResources.ProfileFeatureNotSupported, "AlphaDestinationBlend = Blend.SourceAlphaSaturation");
                }
            }
            if (!profileCapabilities.MinMaxSrcDestBlend)
            {
                BlendFunction blendFunction = cachedColorBlendFunction;
                if ((blendFunction == BlendFunction.Min || blendFunction == BlendFunction.Max) && (cachedColorSourceBlend != 0 || cachedColorDestinationBlend != 0))
                {
                    profileCapabilities.ThrowNotSupportedException(FrameworkResources.ProfileNoMinMaxSrcDestBlend, "Color");
                }
                BlendFunction blendFunction2 = cachedAlphaBlendFunction;
                if ((blendFunction2 == BlendFunction.Min || blendFunction2 == BlendFunction.Max) && (cachedAlphaSourceBlend != 0 || cachedAlphaDestinationBlend != 0))
                {
                    profileCapabilities.ThrowNotSupportedException(FrameworkResources.ProfileNoMinMaxSrcDestBlend, "Alpha");
                }
            }
            _parent = device;
            isBound = true;
            Blend blend = cachedColorSourceBlend;
            int num = ((blend != 0 || cachedColorDestinationBlend != Blend.Zero || cachedColorBlendFunction != 0 || cachedAlphaSourceBlend != 0 || cachedAlphaDestinationBlend != Blend.Zero || cachedAlphaBlendFunction != 0) ? 1 : 0);
            blendEnable = (byte)num != 0;
            int num2 = ((GraphicsHelpers.IsSeparateBlend(blend, cachedAlphaSourceBlend) || GraphicsHelpers.IsSeparateBlend(cachedColorDestinationBlend, cachedAlphaDestinationBlend) || cachedColorBlendFunction != cachedAlphaBlendFunction) ? 1 : 0);
            separateAlphaBlend = (byte)num2 != 0;
            d3dColorSourceBlend = _003CModule_003E.ConvertXnaBlendToDx(cachedColorSourceBlend);
            d3dColorDestinationBlend = _003CModule_003E.ConvertXnaBlendToDx(cachedColorDestinationBlend);
            d3dColorBlendFunction = _003CModule_003E.ConvertXnaBlendOpToDx(cachedColorBlendFunction);
            d3dAlphaSourceBlend = _003CModule_003E.ConvertXnaBlendToDx(GraphicsHelpers.AdjustAlphaBlend(cachedAlphaSourceBlend));
            d3dAlphaDestinationBlend = _003CModule_003E.ConvertXnaBlendToDx(GraphicsHelpers.AdjustAlphaBlend(cachedAlphaDestinationBlend));
            d3dAlphaBlendFunction = _003CModule_003E.ConvertXnaBlendOpToDx(cachedAlphaBlendFunction);
            uint num3 = (uint)(cachedBlendFactor.A << 8);
            uint num4 = (cachedBlendFactor.R | num3) << 8;
            uint num5 = (cachedBlendFactor.G | num4) << 8;
            d3dBlendFactor = cachedBlendFactor.B | num5;
            stateTrackerFlags = 0u;
            if (blendEnable)
            {
                stateTrackerFlags = 1u;
            }
            if (cachedColorWriteChannels != ColorWriteChannels.All)
            {
                stateTrackerFlags |= 2u;
            }
            if (cachedColorWriteChannels1 != ColorWriteChannels.All)
            {
                stateTrackerFlags |= 4u;
            }
            if (cachedColorWriteChannels2 != ColorWriteChannels.All)
            {
                stateTrackerFlags |= 8u;
            }
            if (cachedColorWriteChannels3 != ColorWriteChannels.All)
            {
                stateTrackerFlags |= 16u;
            }
        }
        IntPtr pComPtr = (IntPtr)device.pComPtr;
        Helpers.CheckDisposed(device, pComPtr);
        IDirect3DDevice9* pComPtr2 = device.pComPtr;
        ((delegate* unmanaged[Stdcall, Stdcall]<IntPtr, _D3DRENDERSTATETYPE, uint, int>)(int)(*(uint*)(*(int*)pComPtr2 + 228)))((nint)pComPtr2, (_D3DRENDERSTATETYPE)27, blendEnable ? 1u : 0u);
        if (blendEnable)
        {
            ((delegate* unmanaged[Stdcall, Stdcall]<IntPtr, _D3DRENDERSTATETYPE, uint, int>)(int)(*(uint*)(*(int*)pComPtr2 + 228)))((nint)pComPtr2, (_D3DRENDERSTATETYPE)19, (uint)d3dColorSourceBlend);
            ((delegate* unmanaged[Stdcall, Stdcall]<IntPtr, _D3DRENDERSTATETYPE, uint, int>)(int)(*(uint*)(*(int*)pComPtr2 + 228)))((nint)pComPtr2, (_D3DRENDERSTATETYPE)20, (uint)d3dColorDestinationBlend);
            ((delegate* unmanaged[Stdcall, Stdcall]<IntPtr, _D3DRENDERSTATETYPE, uint, int>)(int)(*(uint*)(*(int*)pComPtr2 + 228)))((nint)pComPtr2, (_D3DRENDERSTATETYPE)171, (uint)d3dColorBlendFunction);
            ((delegate* unmanaged[Stdcall, Stdcall]<IntPtr, _D3DRENDERSTATETYPE, uint, int>)(int)(*(uint*)(*(int*)pComPtr2 + 228)))((nint)pComPtr2, (_D3DRENDERSTATETYPE)206, separateAlphaBlend ? 1u : 0u);
            if (separateAlphaBlend)
            {
                ((delegate* unmanaged[Stdcall, Stdcall]<IntPtr, _D3DRENDERSTATETYPE, uint, int>)(int)(*(uint*)(*(int*)pComPtr2 + 228)))((nint)pComPtr2, (_D3DRENDERSTATETYPE)207, (uint)d3dAlphaSourceBlend);
                ((delegate* unmanaged[Stdcall, Stdcall]<IntPtr, _D3DRENDERSTATETYPE, uint, int>)(int)(*(uint*)(*(int*)pComPtr2 + 228)))((nint)pComPtr2, (_D3DRENDERSTATETYPE)208, (uint)d3dAlphaDestinationBlend);
                ((delegate* unmanaged[Stdcall, Stdcall]<IntPtr, _D3DRENDERSTATETYPE, uint, int>)(int)(*(uint*)(*(int*)pComPtr2 + 228)))((nint)pComPtr2, (_D3DRENDERSTATETYPE)209, (uint)d3dAlphaBlendFunction);
            }
        }
        ((delegate* unmanaged[Stdcall, Stdcall]<IntPtr, _D3DRENDERSTATETYPE, uint, int>)(int)(*(uint*)(*(int*)pComPtr2 + 228)))((nint)pComPtr2, (_D3DRENDERSTATETYPE)168, (uint)cachedColorWriteChannels);
        ((delegate* unmanaged[Stdcall, Stdcall]<IntPtr, _D3DRENDERSTATETYPE, uint, int>)(int)(*(uint*)(*(int*)pComPtr2 + 228)))((nint)pComPtr2, (_D3DRENDERSTATETYPE)190, (uint)cachedColorWriteChannels1);
        ((delegate* unmanaged[Stdcall, Stdcall]<IntPtr, _D3DRENDERSTATETYPE, uint, int>)(int)(*(uint*)(*(int*)pComPtr2 + 228)))((nint)pComPtr2, (_D3DRENDERSTATETYPE)191, (uint)cachedColorWriteChannels2);
        ((delegate* unmanaged[Stdcall, Stdcall]<IntPtr, _D3DRENDERSTATETYPE, uint, int>)(int)(*(uint*)(*(int*)pComPtr2 + 228)))((nint)pComPtr2, (_D3DRENDERSTATETYPE)192, (uint)cachedColorWriteChannels3);
        ((delegate* unmanaged[Stdcall, Stdcall]<IntPtr, _D3DRENDERSTATETYPE, uint, int>)(int)(*(uint*)(*(int*)pComPtr2 + 228)))((nint)pComPtr2, (_D3DRENDERSTATETYPE)193, d3dBlendFactor);
        ((delegate* unmanaged[Stdcall, Stdcall]<IntPtr, _D3DRENDERSTATETYPE, uint, int>)(int)(*(uint*)(*(int*)pComPtr2 + 228)))((nint)pComPtr2, (_D3DRENDERSTATETYPE)162, (uint)cachedMultiSampleMask);
        *(uint*)((byte*)device.pStateTracker + 112) = stateTrackerFlags;
    }
References Microsoft.Xna.Framework.Graphics.GraphicsResource._parent, Microsoft.Xna.Framework.Graphics.GraphicsDevice._profileCapabilities, Microsoft.Xna.Framework.Color.A, Microsoft.Xna.Framework.Graphics.GraphicsHelpers.AdjustAlphaBlend(), Microsoft.Xna.Framework.Graphics.BlendState.blendEnable, Microsoft.Xna.Framework.Graphics.BlendState.cachedAlphaBlendFunction, Microsoft.Xna.Framework.Graphics.BlendState.cachedAlphaDestinationBlend, Microsoft.Xna.Framework.Graphics.BlendState.cachedAlphaSourceBlend, Microsoft.Xna.Framework.Graphics.BlendState.cachedBlendFactor, Microsoft.Xna.Framework.Graphics.BlendState.cachedColorBlendFunction, Microsoft.Xna.Framework.Graphics.BlendState.cachedColorDestinationBlend, Microsoft.Xna.Framework.Graphics.BlendState.cachedColorSourceBlend, Microsoft.Xna.Framework.Graphics.BlendState.cachedColorWriteChannels, Microsoft.Xna.Framework.Graphics.BlendState.cachedColorWriteChannels1, Microsoft.Xna.Framework.Graphics.BlendState.cachedColorWriteChannels2, Microsoft.Xna.Framework.Graphics.BlendState.cachedColorWriteChannels3, Microsoft.Xna.Framework.Graphics.BlendState.cachedMultiSampleMask, Microsoft.Xna.Framework.Helpers.CheckDisposed(), Microsoft.Xna.Framework.Graphics.BlendState.d3dAlphaBlendFunction, Microsoft.Xna.Framework.Graphics.BlendState.d3dAlphaDestinationBlend, Microsoft.Xna.Framework.Graphics.BlendState.d3dAlphaSourceBlend, Microsoft.Xna.Framework.Graphics.BlendState.d3dBlendFactor, Microsoft.Xna.Framework.Graphics.BlendState.d3dColorBlendFunction, Microsoft.Xna.Framework.Graphics.BlendState.d3dColorDestinationBlend, Microsoft.Xna.Framework.Graphics.BlendState.d3dColorSourceBlend, Microsoft.Xna.Framework.Graphics.ProfileCapabilities.DestBlendSrcAlphaSat, Microsoft.Xna.Framework.Graphics.BlendState.isBound, Microsoft.Xna.Framework.Graphics.GraphicsResource.isDisposed, Microsoft.Xna.Framework.Graphics.GraphicsHelpers.IsSeparateBlend(), Microsoft.Xna.Framework.Graphics.ProfileCapabilities.MinMaxSrcDestBlend, Microsoft.Xna.Framework.Graphics.GraphicsResource.Name, Microsoft.Xna.Framework.Graphics.GraphicsDevice.pComPtr, Microsoft.Xna.Framework.FrameworkResources.ProfileFeatureNotSupported, Microsoft.Xna.Framework.FrameworkResources.ProfileNoMinMaxSrcDestBlend, Microsoft.Xna.Framework.FrameworkResources.ProfileNoSeparateAlphaBlend, Microsoft.Xna.Framework.Graphics.BlendState.separateAlphaBlend, Microsoft.Xna.Framework.Graphics.ProfileCapabilities.SeparateAlphaBlend, Microsoft.Xna.Framework.Graphics.BlendState.stateTrackerFlags, and Microsoft.Xna.Framework.Graphics.ProfileCapabilities.ThrowNotSupportedException().