Terraria: System.Transactions.TransactionException.IncludeDistributedTxId
IncludeDistributedTxId()
static bool System.Transactions.TransactionException.IncludeDistributedTxId (Guid distributedTxId) inline static package inherited
Definition at line 11 of file TransactionException.cs.
    {
        if (distributedTxId != Guid.Empty)
        {
            return AppSettings.IncludeDistributedTxIdInExceptionMessage;
        }
        return false;
    }
References System.Runtime.Serialization.Dictionary, System.Guid.Empty, and System.Transactions.Configuration.AppSettings.IncludeDistributedTxIdInExceptionMessage.
Referenced by System.Transactions.TransactionAbortedException.Create(), System.Transactions.TransactionException.Create(), System.Transactions.TransactionException.Create(), System.Transactions.TransactionInDoubtException.Create(), System.Transactions.TransactionException.CreateEnlistmentStateException(), System.Transactions.TransactionException.CreateInvalidOperationException(), and System.Transactions.TransactionException.CreateTransactionCompletedException().