Terraria: System.Transactions.TransactionException.CreateTransactionCompletedException
CreateTransactionCompletedException()
static Exception System.Transactions.TransactionException.CreateTransactionCompletedException (Guid distributedTxId) inline static package inherited
Definition at line 108 of file TransactionException.cs.
    {
        string text = System.SR.TransactionAlreadyCompleted;
        if (IncludeDistributedTxId(distributedTxId))
        {
            text = System.SR.Format(System.SR.DistributedTxIDInTransactionException, text, distributedTxId);
        }
        TransactionsEtwProvider log = TransactionsEtwProvider.Log;
        if (log.IsEnabled())
        {
            log.TransactionExceptionTrace(TransactionExceptionType.InvalidOperationException, text, string.Empty);
        }
        return new InvalidOperationException(text);
    }
References System.Runtime.Serialization.Dictionary, System.SR.DistributedTxIDInTransactionException, System.SR.Format(), System.Transactions.TransactionException.IncludeDistributedTxId(), System.Transactions.InvalidOperationException, System.Transactions.TransactionsEtwProvider.Log, System.text, and System.SR.TransactionAlreadyCompleted.
Referenced by System.Transactions.CommittableTransaction.BeginCommit(), System.Transactions.Transaction.Clone(), System.Transactions.CommittableTransaction.Commit(), System.Transactions.DependentTransaction.Complete(), System.Transactions.TransactionInterop.ConvertToDistributedTransaction(), System.Transactions.Transaction.DependentClone(), System.Transactions.Transaction.EnlistDurable(), System.Transactions.Transaction.EnlistDurable(), System.Transactions.Transaction.EnlistPromotableSinglePhase(), System.Transactions.Transaction.EnlistVolatile(), System.Transactions.Transaction.EnlistVolatile(), System.Transactions.Transaction.PromoteAndEnlistDurable(), and System.Transactions.Transaction.SetDistributedTransactionIdentifier().