Terraria: System.Transactions.TransactionException.CreateTransactionStateException
CreateTransactionStateException()
static TransactionException System.Transactions.TransactionException.CreateTransactionStateException (Exception innerException, Guid distributedTxId) inline static package inherited
Definition at line 103 of file TransactionException.cs.
    {
        return Create(System.SR.TransactionStateException, innerException, distributedTxId);
    }
References System.Transactions.TransactionException.Create(), System.Runtime.Serialization.Dictionary, and System.SR.TransactionStateException.
Referenced by System.Transactions.TransactionState.AddOutcomeRegistrant(), System.Transactions.TransactionState.BeginCommit(), System.Transactions.TransactionStateDelegatedAborting.BeginCommit(), System.Transactions.TransactionStatePromotedAborting.BeginCommit(), System.Transactions.TransactionStatePromotedCommitting.BeginCommit(), System.Transactions.TransactionStatePromotedNonMSDTCPhase0.BeginCommit(), System.Transactions.TransactionStatePromotedNonMSDTCSinglePhaseCommit.BeginCommit(), System.Transactions.TransactionStatePromotedNonMSDTCVolatilePhase1.BeginCommit(), System.Transactions.TransactionStatePromotedP0Wave.BeginCommit(), System.Transactions.TransactionState.CreateAbortingClone(), System.Transactions.TransactionStatePromotedAborting.CreateAbortingClone(), System.Transactions.TransactionStatePromotedEnded.CreateAbortingClone(), System.Transactions.TransactionStatePromotedNonMSDTCEnded.CreateAbortingClone(), System.Transactions.TransactionState.CreateBlockingClone(), System.Transactions.TransactionStatePromotedAborting.CreateBlockingClone(), System.Transactions.TransactionStatePromotedEnded.CreateBlockingClone(), System.Transactions.TransactionStatePromotedNonMSDTCEnded.CreateBlockingClone(), System.Transactions.TransactionState.EndCommit(), System.Transactions.TransactionState.EnlistDurable(), System.Transactions.TransactionState.EnlistDurable(), System.Transactions.TransactionState.EnlistPromotableSinglePhase(), System.Transactions.TransactionState.EnlistVolatile(), System.Transactions.TransactionState.EnlistVolatile(), System.Transactions.TransactionStatePSPEOperation.get_Status(), System.Transactions.TransactionState.Phase0VolatilePrepareDone(), System.Transactions.TransactionState.Phase1VolatilePrepareDone(), System.Transactions.TransactionState.Promote(), System.Transactions.TransactionState.PromoteAndEnlistDurable(), System.Transactions.TransactionStatePSPEOperation.PromoteAndEnlistDurable(), System.Transactions.TransactionState.PromotedToken(), System.Transactions.TransactionState.Rollback(), System.Transactions.TransactionStateCommitted.Rollback(), System.Transactions.TransactionStateInDoubt.Rollback(), System.Transactions.TransactionStatePromotedNonMSDTCSinglePhaseCommit.Rollback(), System.Transactions.TransactionState.SetDistributedTransactionId(), and System.Transactions.TransactionStatePSPEOperation.SetDistributedTransactionId().