Terraria: System.Drawing.Rectangle.Rectangle
Rectangle() [1/2]
System.Drawing.Rectangle.Rectangle (int x, int y, int width, int height) inline
Definition at line 123 of file Rectangle.cs.
    {
        this.x = x;
        this.y = y;
        this.width = width;
        this.height = height;
    }
References System.Drawing.Rectangle.height, System.Drawing.Rectangle.width, System.Drawing.Rectangle.x, and System.Drawing.Rectangle.y.
Referenced by System.Drawing.Rectangle.Ceiling(), System.Drawing.Rectangle.FromLTRB(), System.Drawing.Rectangle.Intersect(), System.Drawing.Rectangle.Round(), System.Drawing.Rectangle.Truncate(), and System.Drawing.Rectangle.Union().