Terraria: System.Drawing.Rectangle.Union
Union()
static Rectangle System.Drawing.Rectangle.Union (Rectangle a, Rectangle b) inline static
Definition at line 266 of file Rectangle.cs.
    {
        int num = Math.Min(a.X, b.X);
        int num2 = Math.Max(a.X + a.Width, b.X + b.Width);
        int num3 = Math.Min(a.Y, b.Y);
        int num4 = Math.Max(a.Y + a.Height, b.Y + b.Height);
        return new Rectangle(num, num3, num2 - num, num4 - num3);
    }
References System.Drawing.Rectangle.Rectangle(), System.Drawing.Rectangle.Height, System.Math.Max(), System.Math.Min(), System.Drawing.Rectangle.Width, System.Drawing.Rectangle.X, and System.Drawing.Rectangle.Y.