Terraria: System.Net.TimerThread.ThreadProc
ThreadProc()
static void System.Net.TimerThread.ThreadProc () inline static private
Definition at line 398 of file TimerThread.cs.
    {
        lock (s_queues)
        {
            if (Interlocked.CompareExchange(ref s_threadState, 1, 1) != 1)
            {
                return;
            }
            bool flag = true;
            while (flag)
            {
                try
                {
                    s_threadReadyEvent.Reset();
                    while (true)
                    {
                        if (s_newQueues.Count > 0)
{
                            lock (s_newQueues)
{
                                for (LinkedListNode<WeakReference> first = s_newQueues.First; first != null; first = s_newQueues.First)
{
                                    s_newQueues.Remove(first);
                                    s_queues.AddLast(first);
                                }
                            }
                        }
                        int tickCount = Environment.TickCount;
                        int num = 0;
                        bool flag2 = false;
                        LinkedListNode<WeakReference> linkedListNode = s_queues.First;
                        while (linkedListNode != null)
{
                            TimerQueue timerQueue = (TimerQueue)linkedListNode.Value.Target;
                            if (timerQueue == null)
{
                                LinkedListNode<WeakReference> next = linkedListNode.Next;
                                s_queues.Remove(linkedListNode);
                                linkedListNode = next;
                                continue;
                            }
                            if (timerQueue.Fire(out var nextExpiration) && (!flag2 || IsTickBetween(tickCount, num, nextExpiration)))
{
                                num = nextExpiration;
                                flag2 = true;
                            }
                            linkedListNode = linkedListNode.Next;
                        }
                        int tickCount2 = Environment.TickCount;
                        int num2 = (int)((!flag2) ? 30000 : (IsTickBetween(tickCount, num, tickCount2) ? (Math.Min((uint)(num - tickCount2), 2147483632u) + 15) : 0));
                        if (System.Net.NetEventSource.Log.IsEnabled())
{
                            System.Net.NetEventSource.Info(null, $"Waiting for {num2}ms", "ThreadProc");
                        }
                        int num3 = WaitHandle.WaitAny(s_threadEvents, num2, exitContext: false);
                        if (num3 == 0)
{
                            if (System.Net.NetEventSource.Log.IsEnabled())
{
                                System.Net.NetEventSource.Info(null, "Awoke, cause: Shutdown", "ThreadProc");
                            }
                            flag = false;
                            break;
                        }
                        if (System.Net.NetEventSource.Log.IsEnabled())
{
                            System.Net.NetEventSource.Info(null, FormattableStringFactory.Create("Awoke, cause {0}", (num3 == 258) ? "Timeout" : "Prod"), "ThreadProc");
                        }
                        if (num3 == 258 && !flag2)
{
                            Interlocked.CompareExchange(ref s_threadState, 0, 1);
                            if (!s_threadReadyEvent.WaitOne(0, exitContext: false) || Interlocked.CompareExchange(ref s_threadState, 1, 0) != 0)
{
                                flag = false;
                                break;
                            }
                        }
                    }
                }
                catch (Exception ex)
                {
                    if (System.Net.ExceptionCheck.IsFatal(ex))
                    {
                        throw;
                    }
                    if (System.Net.NetEventSource.Log.IsEnabled())
                    {
                        System.Net.NetEventSource.Error(null, ex, "ThreadProc");
                    }
                    Thread.Sleep(1000);
                }
            }
        }
        if (System.Net.NetEventSource.Log.IsEnabled())
        {
            System.Net.NetEventSource.Info(null, "Stop", "ThreadProc");
        }
    }
References System.Threading.Interlocked.CompareExchange(), System.Runtime.CompilerServices.FormattableStringFactory.Create(), System.Net.NetEventSource.Error(), System.Net.NetEventSource.Info(), System.Net.ExceptionCheck.IsFatal(), System.Net.TimerThread.IsTickBetween(), System.Net.NetEventSource.Log, System.Math.Min(), System.Net.TimerThread.s_newQueues, System.Net.TimerThread.s_queues, System.Net.TimerThread.s_threadEvents, System.Net.TimerThread.s_threadReadyEvent, System.Net.TimerThread.s_threadState, System.Threading.Thread.Sleep(), System.Environment.TickCount, and System.Threading.WaitHandle.WaitAny().
Referenced by System.Net.TimerThread.Prod().