Terraria: System.Int32.Parse
Parse() [11/12]
static int System.Int32.Parse (string s, NumberStyles style, IFormatProvider? provider) inline static
Definition at line 147 of file Int32.cs.
    {
        NumberFormatInfo.ValidateParseStyleInteger(style);
        if (s == null)
        {
            ThrowHelper.ThrowArgumentNullException(ExceptionArgument.s);
        }
        return Number.ParseInt32(s, style, NumberFormatInfo.GetInstance(provider));
    }
References System.Globalization.NumberFormatInfo.GetInstance(), System.Number.ParseInt32(), System.s, System.ThrowHelper.ThrowArgumentNullException(), and System.Globalization.NumberFormatInfo.ValidateParseStyleInteger().