Terraria: System.Xml.Xsl.XsltOld.CallTemplateAction.Execute
Execute()
override void System.Xml.Xsl.XsltOld.CallTemplateAction.Execute (Processor processor, ActionFrame frame) inline package
Definition at line 67 of file CallTemplateAction.cs.
    {
        switch (frame.State)
        {
        case 0:
            processor.ResetParams();
            if (containedActions != null && containedActions.Count > 0)
            {
                processor.PushActionFrame(frame);
                frame.State = 2;
                break;
            }
            goto case 2;
        case 2:
        {
            TemplateAction templateAction = processor.Stylesheet.FindTemplate(_name);
            if (templateAction != null)
            {
                frame.State = 3;
                processor.PushActionFrame(templateAction, frame.NodeSet);
                break;
            }
            throw XsltException.Create(System.SR.Xslt_InvalidCallTemplate, _name.ToString());
        }
        case 3:
            frame.Finished();
            break;
        case 1:
            break;
        }
    }
References System.Xml.Xsl.XsltOld.CallTemplateAction._name, System.Xml.Xsl.XsltOld.ContainerAction.containedActions, System.Xml.Xsl.XsltException.Create(), System.Xml.Dictionary, System.Xml.Xsl.XsltOld.ActionFrame.Finished(), System.Xml.Xsl.XsltOld.ActionFrame.NodeSet, System.Xml.Xsl.XsltOld.ActionFrame.State, System.Xml.XmlQualifiedName.ToString(), and System.SR.Xslt_InvalidCallTemplate.