Terraria: System.Xml.Xsl.XsltOld.CallTemplateAction.Compile
Compile()
override void System.Xml.Xsl.XsltOld.CallTemplateAction.Compile (Compiler compiler) inline package
Definition at line 9 of file CallTemplateAction.cs.
    {
        CompileAttributes(compiler);
        CheckRequiredAttribute(compiler, _name, "name");
        CompileContent(compiler);
    }
References System.Xml.Xsl.XsltOld.CallTemplateAction._name, System.Xml.Xsl.XsltOld.CompiledAction.CheckRequiredAttribute(), System.Xml.Xsl.XsltOld.CompiledAction.CompileAttributes(), System.Xml.Xsl.XsltOld.CallTemplateAction.CompileContent(), and System.Xml.Dictionary.