Terraria: System.Xml.Xsl.XsltOld.CallTemplateAction.CompileContent
CompileContent()
void System.Xml.Xsl.XsltOld.CallTemplateAction.CompileContent (Compiler compiler) inline private
Definition at line 28 of file CallTemplateAction.cs.
    {
        NavigatorInput input = compiler.Input;
        if (!compiler.Recurse())
        {
            return;
        }
        do
        {
            switch (input.NodeType)
            {
            case XPathNodeType.Element:
            {
                compiler.PushNamespaceScope();
                string namespaceURI = input.NamespaceURI;
                string localName = input.LocalName;
                if (Ref.Equal(namespaceURI, input.Atoms.UriXsl) && Ref.Equal(localName, input.Atoms.WithParam))
                {
                    WithParamAction withParamAction = compiler.CreateWithParamAction();
                    CheckDuplicateParams(withParamAction.Name);
                    AddAction(withParamAction);
                    compiler.PopScope();
                    break;
                }
                throw compiler.UnexpectedKeyword();
            }
            default:
                throw XsltException.Create(System.SR.Xslt_InvalidContents, "call-template");
            case XPathNodeType.SignificantWhitespace:
            case XPathNodeType.Whitespace:
            case XPathNodeType.ProcessingInstruction:
            case XPathNodeType.Comment:
                break;
            }
        }
        while (compiler.Advance());
        compiler.ToParent();
    }
References System.Xml.Xsl.XsltOld.ContainerAction.AddAction(), System.Xml.Xsl.XsltOld.ContainerAction.CheckDuplicateParams(), System.Xml.Xsl.XsltException.Create(), System.Xml.Dictionary, System.Xml.Ref.Equal(), System.input, System.Xml.Xsl.XsltOld.NavigatorInput.NamespaceURI, and System.SR.Xslt_InvalidContents.
Referenced by System.Xml.Xsl.XsltOld.CallTemplateAction.Compile().