Terraria: System.Xml.Schema.AutoValidator.DetectValidationType
DetectValidationType()
ValidationType System.Xml.Schema.AutoValidator.DetectValidationType () inline private
Definition at line 40 of file AutoValidator.cs.
    {
        if (reader.Schemas != null && reader.Schemas.Count > 0)
        {
            XmlSchemaCollectionEnumerator enumerator = reader.Schemas.GetEnumerator();
            while (enumerator.MoveNext())
            {
                XmlSchemaCollectionNode currentNode = enumerator.CurrentNode;
                SchemaInfo schemaInfo = currentNode.SchemaInfo;
                if (schemaInfo.SchemaType == SchemaType.XSD)
                {
                    return ValidationType.Schema;
                }
                if (schemaInfo.SchemaType == SchemaType.XDR)
                {
                    return ValidationType.XDR;
                }
            }
        }
        if (reader.NodeType == XmlNodeType.Element)
        {
            switch (base.SchemaNames.SchemaTypeFromRoot(reader.LocalName, reader.NamespaceURI))
            {
            case SchemaType.XSD:
                return ValidationType.Schema;
            case SchemaType.XDR:
                return ValidationType.XDR;
            }
            int attributeCount = reader.AttributeCount;
            for (int i = 0; i < attributeCount; i++)
            {
                reader.MoveToAttribute(i);
                string namespaceURI = reader.NamespaceURI;
                string localName = reader.LocalName;
                if (Ref.Equal(namespaceURI, base.SchemaNames.NsXmlNs))
                {
                    if (XdrBuilder.IsXdrSchema(reader.Value))
                    {
                        reader.MoveToElement();
                        return ValidationType.XDR;
                    }
                    continue;
                }
                if (Ref.Equal(namespaceURI, base.SchemaNames.NsXsi))
                {
                    reader.MoveToElement();
                    return ValidationType.Schema;
                }
                if (Ref.Equal(namespaceURI, base.SchemaNames.QnDtDt.Namespace) && Ref.Equal(localName, base.SchemaNames.QnDtDt.Name))
                {
                    reader.SchemaTypeObject = XmlSchemaDatatype.FromXdrName(reader.Value);
                    reader.MoveToElement();
                    return ValidationType.XDR;
                }
            }
            if (attributeCount > 0)
            {
                reader.MoveToElement();
            }
        }
        return ValidationType.Auto;
    }
References System.Xml.XmlValidatingReaderImpl.AttributeCount, System.Xml.Dictionary, System.Xml.Ref.Equal(), System.Xml.Schema.XmlSchemaDatatype.FromXdrName(), System.Xml.Schema.XdrBuilder.IsXdrSchema(), System.Xml.XmlValidatingReaderImpl.LocalName, System.Xml.XmlValidatingReaderImpl.MoveToAttribute(), System.Xml.XmlValidatingReaderImpl.MoveToElement(), System.Xml.XmlValidatingReaderImpl.NamespaceURI, System.Xml.XmlValidatingReaderImpl.NodeType, System.Xml.Schema.BaseValidator.reader, System.Xml.Schema.BaseValidator.schemaInfo, System.Xml.Schema.XmlSchemaCollectionNode.SchemaInfo, System.Xml.XmlValidatingReaderImpl.Schemas, System.Xml.Schema.SchemaInfo.SchemaType, and System.Xml.XmlValidatingReaderImpl.Value.
Referenced by System.Xml.Schema.AutoValidator.Validate().