Terraria: System.Linq.Parallel.UnionQueryOperator.OrderedUnionQueryOperatorEnumerator.MoveNext
MoveNext() [2/2]
override bool System.Linq.Parallel.UnionQueryOperator< TInputOutput >.OrderedUnionQueryOperatorEnumerator< TLeftKey, TRightKey >.MoveNext ([AllowNull] ref TInputOutput currentElement, ref ConcatKey< TLeftKey, TRightKey > currentKey) inline package
Definition at line 126 of file UnionQueryOperator.cs.
        {
            if (_outputEnumerator == null)
            {
                IEqualityComparer<Wrapper<TInputOutput>> comparer = new WrapperEqualityComparer<TInputOutput>(_comparer);
                Dictionary<Wrapper<TInputOutput>, Pair<TInputOutput, ConcatKey<TLeftKey, TRightKey>>> dictionary = new Dictionary<Wrapper<TInputOutput>, Pair<TInputOutput, ConcatKey<TLeftKey, TRightKey>>>(comparer);
                Pair<TInputOutput, NoKeyMemoizationRequired> currentElement2 = default(Pair<TInputOutput, NoKeyMemoizationRequired>);
                TLeftKey currentKey2 = default(TLeftKey);
                int num = 0;
                while (_leftSource.MoveNext(ref currentElement2, ref currentKey2))
                {
                    if ((num++ & 0x3F) == 0)
                    {
                        _cancellationToken.ThrowIfCancellationRequested();
                    }
                    ConcatKey<TLeftKey, TRightKey> concatKey = ConcatKey<TLeftKey, TRightKey>.MakeLeft(_leftOrdered ? currentKey2 : default(TLeftKey));
                    Wrapper<TInputOutput> key = new Wrapper<TInputOutput>(currentElement2.First);
                    if (!dictionary.TryGetValue(key, out var value) || _keyComparer.Compare(concatKey, value.Second) < 0)
                    {
                        dictionary[key] = new Pair<TInputOutput, ConcatKey<TLeftKey, TRightKey>>(currentElement2.First, concatKey);
                    }
                }
                TRightKey currentKey3 = default(TRightKey);
                while (_rightSource.MoveNext(ref currentElement2, ref currentKey3))
                {
                    if ((num++ & 0x3F) == 0)
                    {
                        _cancellationToken.ThrowIfCancellationRequested();
                    }
                    ConcatKey<TLeftKey, TRightKey> concatKey2 = ConcatKey<TLeftKey, TRightKey>.MakeRight(_rightOrdered ? currentKey3 : default(TRightKey));
                    Wrapper<TInputOutput> key2 = new Wrapper<TInputOutput>(currentElement2.First);
                    if (!dictionary.TryGetValue(key2, out var value2) || _keyComparer.Compare(concatKey2, value2.Second) < 0)
                    {
                        dictionary[key2] = new Pair<TInputOutput, ConcatKey<TLeftKey, TRightKey>>(currentElement2.First, concatKey2);
                    }
                }
                _outputEnumerator = dictionary.GetEnumerator();
            }
            if (_outputEnumerator.MoveNext())
            {
                Pair<TInputOutput, ConcatKey<TLeftKey, TRightKey>> value3 = _outputEnumerator.Current.Value;
                currentElement = value3.First;
                currentKey = value3.Second;
                return true;
            }
            return false;
        }
References System.Linq.Parallel.UnionQueryOperator< TInputOutput >.OrderedUnionQueryOperatorEnumerator< TLeftKey, TRightKey >._cancellationToken, System.Linq.Parallel.UnionQueryOperator< TInputOutput >.OrderedUnionQueryOperatorEnumerator< TLeftKey, TRightKey >._comparer, System.Linq.Parallel.UnionQueryOperator< TInputOutput >.OrderedUnionQueryOperatorEnumerator< TLeftKey, TRightKey >._keyComparer, System.Linq.Parallel.UnionQueryOperator< TInputOutput >.OrderedUnionQueryOperatorEnumerator< TLeftKey, TRightKey >._leftOrdered, System.Linq.Parallel.UnionQueryOperator< TInputOutput >.OrderedUnionQueryOperatorEnumerator< TLeftKey, TRightKey >._leftSource, System.Linq.Parallel.UnionQueryOperator< TInputOutput >.OrderedUnionQueryOperatorEnumerator< TLeftKey, TRightKey >._outputEnumerator, System.Linq.Parallel.UnionQueryOperator< TInputOutput >.OrderedUnionQueryOperatorEnumerator< TLeftKey, TRightKey >._rightOrdered, System.Linq.Parallel.UnionQueryOperator< TInputOutput >.OrderedUnionQueryOperatorEnumerator< TLeftKey, TRightKey >._rightSource, System.Collections.Generic.IComparer< in T >.Compare(), System.comparer, System.dictionary, System.Collections.Generic.Dictionary< TKey, TValue >.GetEnumerator(), System.key, System.Threading.CancellationToken.ThrowIfCancellationRequested(), and System.value.