Terraria: System.Linq.Enumerable.Min
Min() [3/10]
static double System.Linq.Enumerable.Min (this IEnumerable< double > source) inline static
Definition at line 6498 of file Enumerable.cs.
    {
        if (source == null)
        {
            ThrowHelper.ThrowArgumentNullException(ExceptionArgument.source);
        }
        using IEnumerator<double> enumerator = source.GetEnumerator();
        if (!enumerator.MoveNext())
        {
            ThrowHelper.ThrowNoElementsException();
        }
        double num = enumerator.Current;
        if (double.IsNaN(num))
        {
            return num;
        }
        while (enumerator.MoveNext())
        {
            double current = enumerator.Current;
            if (current < num)
            {
                num = current;
            }
            else if (double.IsNaN(current))
            {
                return current;
            }
        }
        return num;
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.GetEnumerator(), System.Linq.source, System.Linq.ThrowHelper.ThrowArgumentNullException(), and System.Linq.ThrowHelper.ThrowNoElementsException().