Terraria: System.Linq.Enumerable.MaxBy< TSource, TKey >
MaxBy< TSource, TKey >() [2/2]
static ? TSource System.Linq.Enumerable.MaxBy< TSource, TKey > (this IEnumerable< TSource > source, Func< TSource, TKey > keySelector, IComparer< TKey >? comparer) inline static
Definition at line 5799 of file Enumerable.cs.
    {
        if (source == null)
        {
            ThrowHelper.ThrowArgumentNullException(ExceptionArgument.source);
        }
        if (keySelector == null)
        {
            ThrowHelper.ThrowArgumentNullException(ExceptionArgument.keySelector);
        }
        if (comparer == null)
        {
            comparer = Comparer<TKey>.Default;
        }
        using IEnumerator<TSource> enumerator = source.GetEnumerator();
        if (!enumerator.MoveNext())
        {
            if (default(TSource) == null)
            {
                return default(TSource);
            }
            ThrowHelper.ThrowNoElementsException();
        }
        TSource val = enumerator.Current;
        TKey val2 = keySelector(val);
        if (default(TKey) == null)
        {
            while (val2 == null)
            {
                if (!enumerator.MoveNext())
                {
                    return val;
                }
                val = enumerator.Current;
                val2 = keySelector(val);
            }
            while (enumerator.MoveNext())
            {
                TSource current = enumerator.Current;
                TKey val3 = keySelector(current);
                if (val3 != null && comparer.Compare(val3, val2) > 0)
                {
                    val2 = val3;
                    val = current;
                }
            }
        }
        else if (comparer == Comparer<TKey>.Default)
        {
            while (enumerator.MoveNext())
            {
                TSource current2 = enumerator.Current;
                TKey val4 = keySelector(current2);
                if (Comparer<TKey>.Default.Compare(val4, val2) > 0)
                {
                    val2 = val4;
                    val = current2;
                }
            }
        }
        else
        {
            while (enumerator.MoveNext())
            {
                TSource current3 = enumerator.Current;
                TKey val5 = keySelector(current3);
                if (comparer.Compare(val5, val2) > 0)
                {
                    val2 = val5;
                    val = current3;
                }
            }
        }
        return val;
    }
References System.comparer, System.Linq.Default, System.Collections.Generic.Dictionary< TKey, TValue >.GetEnumerator(), System.Linq.keySelector, System.Linq.source, System.Linq.ThrowHelper.ThrowArgumentNullException(), and System.Linq.ThrowHelper.ThrowNoElementsException().