Terraria: System.Xml.Schema.XmlNumeric2Converter.ToDouble
ToDouble() [6/6]
override double System.Xml.Schema.XmlNumeric2Converter.ToDouble (string value) inline
Definition at line 15 of file XmlNumeric2Converter.cs.
    {
        if (value == null)
        {
            throw new ArgumentNullException("value");
        }
        if (base.TypeCode == XmlTypeCode.Float)
        {
            return XmlConvert.ToSingle(value);
        }
        return XmlConvert.ToDouble(value);
    }
References System.Xml.Dictionary, System.Xml.XmlConvert.ToDouble(), System.Xml.XmlConvert.ToSingle(), and System.value.
Referenced by System.Xml.Schema.XmlNumeric2Converter.ChangeType(), System.Xml.Schema.XmlNumeric2Converter.ChangeType(), and System.Xml.Schema.XmlNumeric2Converter.ToDouble().