Terraria: PlayerResourceSetsManager.CycleResourceSet
CycleResourceSet()
void PlayerResourceSetsManager.CycleResourceSet () inline
     {
         IPlayerResourcesDisplaySet lastFrame = null;
         _sets.Values.FirstOrDefault(delegate(IPlayerResourcesDisplaySet frame)
         {
             if (frame == _activeSet)
             {
                 return true;
             }
             lastFrame = frame;
             return false;
         });
         if (lastFrame == null)
         {
             lastFrame = _sets.Values.Last();
         }
         SetActiveFrame(lastFrame);
     }
References _activeSet, _sets, and SetActiveFrame().
Referenced by IngameOptions.Draw(), and Main.DrawMenu().