Terraria: System.Threading.Tasks.TaskFactory.ContinueWhenAllImpl
ContinueWhenAllImpl()
static Task< TResult > System.Threading.Tasks.TaskFactory< TResult >.ContinueWhenAllImpl (Task[] tasks, Func< Task[], TResult > continuationFunction, Action< Task[]> continuationAction, TaskContinuationOptions continuationOptions, CancellationToken cancellationToken, TaskScheduler scheduler) inline static package
Definition at line 665 of file TaskFactory.cs.
    {
        TaskFactory.CheckMultiTaskContinuationOptions(continuationOptions);
        if (tasks == null)
        {
            ThrowHelper.ThrowArgumentNullException(ExceptionArgument.tasks);
        }
        if (scheduler == null)
        {
            ThrowHelper.ThrowArgumentNullException(ExceptionArgument.scheduler);
        }
        Task[] tasksCopy = TaskFactory.CheckMultiContinuationTasksAndCopy(tasks);
        if (cancellationToken.IsCancellationRequested && (continuationOptions & TaskContinuationOptions.LazyCancellation) == 0)
        {
            return CreateCanceledTask(continuationOptions, cancellationToken);
        }
        Task<Task[]> task = TaskFactory.CommonCWAllLogic(tasksCopy);
        if (continuationFunction != null)
        {
            return task.ContinueWith(delegate(Task<Task[]> completedTasks, object state)
            {
                completedTasks.NotifyDebuggerOfWaitCompletionIfNecessary();
                return ((Func<Task[], TResult>)state)(completedTasks.Result);
            }, continuationFunction, scheduler, cancellationToken, continuationOptions);
        }
        return task.ContinueWith(delegate(Task<Task[]> completedTasks, object state)
        {
            completedTasks.NotifyDebuggerOfWaitCompletionIfNecessary();
            ((Action<Task[]>)state)(completedTasks.Result);
            return default(TResult);
        }, continuationAction, scheduler, cancellationToken, continuationOptions);
    }
References System.cancellationToken, System.Threading.Tasks.TaskFactory< TResult >.CheckMultiContinuationTasksAndCopy(), System.Threading.Tasks.TaskFactory< TResult >.CheckMultiTaskContinuationOptions(), System.Threading.Tasks.TaskFactory< TResult >.CommonCWAllLogic(), System.continuationAction, System.continuationFunction, System.continuationOptions, System.scheduler, System.state, System.task, System.tasks, and System.ThrowHelper.ThrowArgumentNullException().