Terraria: System.Threading.Tasks.TaskFactory.CommonCWAnyLogic
CommonCWAnyLogic()
static Task< Task > System.Threading.Tasks.TaskFactory< TResult >.CommonCWAnyLogic (IList< Task > tasks, bool isSyncBlocking = false) inline static package
Definition at line 1474 of file TaskFactory.cs.
    {
        CompleteOnInvokePromise completeOnInvokePromise = new CompleteOnInvokePromise(tasks, isSyncBlocking);
        bool flag = false;
        int count = tasks.Count;
        for (int i = 0; i < count; i++)
        {
            Task task = tasks[i];
            if (task == null)
            {
                throw new ArgumentException(SR.Task_MultiTaskContinuation_NullTask, "tasks");
            }
            if (flag)
            {
                continue;
            }
            if (completeOnInvokePromise.IsCompleted)
            {
                flag = true;
                continue;
            }
            if (task.IsCompleted)
            {
                completeOnInvokePromise.Invoke(task);
                flag = true;
                continue;
            }
            task.AddCompletionAction(completeOnInvokePromise, isSyncBlocking);
            if (completeOnInvokePromise.IsCompleted)
            {
                task.RemoveContinuation(completeOnInvokePromise);
            }
        }
        return completeOnInvokePromise;
    }
References System.task, System.SR.Task_MultiTaskContinuation_NullTask, and System.tasks.
Referenced by System.Threading.Tasks.TaskFactory< TResult >.ContinueWhenAnyImpl(), System.Threading.Tasks.TaskFactory< TResult >.ContinueWhenAnyImpl< TAntecedentResult >(), System.Threading.Tasks.Task< TResult >.WaitAnyCore(), System.Threading.Tasks.Task< TResult >.WhenAny(), and System.Threading.Tasks.Task< TResult >.WhenAny().