Terraria: System.Threading.Tasks.TaskFactory.FromAsyncImpl
FromAsyncImpl() [2/2]
static Task< TResult > System.Threading.Tasks.TaskFactory< TResult >.FromAsyncImpl (IAsyncResult asyncResult, Func< IAsyncResult, TResult > endFunction, Action< IAsyncResult > endAction, TaskCreationOptions creationOptions, TaskScheduler scheduler) inline static package
Definition at line 248 of file TaskFactory.cs.
    {
        if (asyncResult == null)
        {
            ThrowHelper.ThrowArgumentNullException(ExceptionArgument.asyncResult);
        }
        if (endFunction == null && endAction == null)
        {
            ThrowHelper.ThrowArgumentNullException(ExceptionArgument.endMethod);
        }
        if (scheduler == null)
        {
            ThrowHelper.ThrowArgumentNullException(ExceptionArgument.scheduler);
        }
        TaskFactory.CheckFromAsyncOptions(creationOptions, hasBeginMethod: false);
        Task<TResult> promise = new Task<TResult>((object)null, creationOptions);
        if (TplEventSource.Log.IsEnabled())
        {
            TplEventSource.Log.TraceOperationBegin(promise.Id, "TaskFactory.FromAsync", 0L);
        }
        if (Task.s_asyncDebuggingEnabled)
        {
            Task.AddToActiveTasks(promise);
        }
        Task t = new Task((Action<object>)delegate
        {
            FromAsyncCoreLogic(asyncResult, endFunction, endAction, promise, requiresSynchronization: true);
        }, null, null, default(CancellationToken), TaskCreationOptions.None, InternalTaskOptions.None, null);
        if (TplEventSource.Log.IsEnabled())
        {
            TplEventSource.Log.TraceOperationBegin(t.Id, "TaskFactory.FromAsync Callback", 0L);
        }
        if (Task.s_asyncDebuggingEnabled)
        {
            Task.AddToActiveTasks(t);
        }
        if (asyncResult.IsCompleted)
        {
            try
            {
                t.InternalRunSynchronously(scheduler, waitForCompletion: false);
            }
            catch (Exception exceptionObject)
            {
                promise.TrySetException(exceptionObject);
            }
        }
        else
        {
            ThreadPool.RegisterWaitForSingleObject(asyncResult.AsyncWaitHandle, delegate
            {
                try
                {
                    t.InternalRunSynchronously(scheduler, waitForCompletion: false);
                }
                catch (Exception exceptionObject2)
                {
                    promise.TrySetException(exceptionObject2);
                }
            }, null, -1, executeOnlyOnce: true);
        }
        return promise;
    }
References System.Threading.Tasks.Task< TResult >.AddToActiveTasks(), System.asyncResult, System.Threading.Tasks.TaskFactory< TResult >.CheckFromAsyncOptions(), System.creationOptions, System.endFunction, System.Threading.Tasks.TaskFactory< TResult >.FromAsyncCoreLogic(), System.Threading.Tasks.Task< TResult >.Id, System.Threading.Tasks.Task< TResult >.InternalRunSynchronously(), System.L, System.Threading.Tasks.TplEventSource.Log, System.Threading.ThreadPool.RegisterWaitForSingleObject(), System.Threading.Tasks.Task< TResult >.s_asyncDebuggingEnabled, System.scheduler, and System.ThrowHelper.ThrowArgumentNullException().
Referenced by System.Threading.Tasks.TaskFactory< TResult >.FromAsync(), System.Threading.Tasks.TaskFactory< TResult >.FromAsync(), and System.Threading.Tasks.TaskFactory< TResult >.FromAsync().