Terraria: System.Threading.Tasks.TaskFactory.ContinueWhenAnyImpl< TAntecedentResult >
ContinueWhenAnyImpl< TAntecedentResult >()
static Task< TResult > System.Threading.Tasks.TaskFactory< TResult >.ContinueWhenAnyImpl< TAntecedentResult > (Task< TAntecedentResult >[] tasks, Func< Task< TAntecedentResult >, TResult > continuationFunction, Action< Task< TAntecedentResult > > continuationAction, TaskContinuationOptions continuationOptions, CancellationToken cancellationToken, TaskScheduler scheduler) inline static package
Definition at line 801 of file TaskFactory.cs.
    {
        TaskFactory.CheckMultiTaskContinuationOptions(continuationOptions);
        if (tasks == null)
        {
            ThrowHelper.ThrowArgumentNullException(ExceptionArgument.tasks);
        }
        if (tasks.Length == 0)
        {
            ThrowHelper.ThrowArgumentException(ExceptionResource.Task_MultiTaskContinuation_EmptyTaskList, ExceptionArgument.tasks);
        }
        if (scheduler == null)
        {
            ThrowHelper.ThrowArgumentNullException(ExceptionArgument.scheduler);
        }
        Task<Task> task = TaskFactory.CommonCWAnyLogic(tasks);
        if (cancellationToken.IsCancellationRequested && (continuationOptions & TaskContinuationOptions.LazyCancellation) == 0)
        {
            return CreateCanceledTask(continuationOptions, cancellationToken);
        }
        if (continuationFunction != null)
        {
            return task.ContinueWith(GenericDelegateCache<TAntecedentResult, TResult>.CWAnyFuncDelegate, continuationFunction, scheduler, cancellationToken, continuationOptions);
        }
        return task.ContinueWith(GenericDelegateCache<TAntecedentResult, TResult>.CWAnyActionDelegate, continuationAction, scheduler, cancellationToken, continuationOptions);
    }
References System.cancellationToken, System.Threading.Tasks.TaskFactory< TResult >.CheckMultiTaskContinuationOptions(), System.Threading.Tasks.TaskFactory< TResult >.CommonCWAnyLogic(), System.continuationAction, System.continuationFunction, System.continuationOptions, System.scheduler, System.task, System.tasks, System.ThrowHelper.ThrowArgumentException(), and System.ThrowHelper.ThrowArgumentNullException().