Terraria: System.Globalization.HijriCalendar.AddMonths
AddMonths()
override DateTime System.Globalization.HijriCalendar.AddMonths (DateTime time, int months) inline
Definition at line 180 of file HijriCalendar.cs.
    {
        if (months < -120000 || months > 120000)
        {
            throw new ArgumentOutOfRangeException("months", months, SR.Format(SR.ArgumentOutOfRange_Range, -120000, 120000));
        }
        int datePart = GetDatePart(time.Ticks, 0);
        int datePart2 = GetDatePart(time.Ticks, 2);
        int num = GetDatePart(time.Ticks, 3);
        int num2 = datePart2 - 1 + months;
        if (num2 >= 0)
        {
            datePart2 = num2 % 12 + 1;
            datePart += num2 / 12;
        }
        else
        {
            datePart2 = 12 + (num2 + 1) % 12;
            datePart += (num2 - 11) / 12;
        }
        int daysInMonth = GetDaysInMonth(datePart, datePart2);
        if (num > daysInMonth)
        {
            num = daysInMonth;
        }
        long ticks = GetAbsoluteDateHijri(datePart, datePart2, num) * 864000000000L + time.Ticks % 864000000000L;
        Calendar.CheckAddResult(ticks, MinSupportedDateTime, MaxSupportedDateTime);
        return new DateTime(ticks);
    }
References System.SR.ArgumentOutOfRange_Range, System.Globalization.Calendar.CheckAddResult(), System.DateTime, System.SR.Format(), System.Globalization.HijriCalendar.GetAbsoluteDateHijri(), System.Globalization.HijriCalendar.GetDatePart(), System.Globalization.HijriCalendar.GetDaysInMonth(), System.L, System.Globalization.HijriCalendar.MaxSupportedDateTime, System.Globalization.HijriCalendar.MinSupportedDateTime, and System.DateTime.Ticks.
Referenced by System.Globalization.HijriCalendar.AddYears().