Terraria: System.Globalization.HijriCalendar.DaysUpToHijriYear
DaysUpToHijriYear()
long System.Globalization.HijriCalendar.DaysUpToHijriYear (int HijriYear) inline private
Definition at line 80 of file HijriCalendar.cs.
    {
        int num = (HijriYear - 1) / 30 * 30;
        int num2 = HijriYear - num - 1;
        long num3 = (long)num * 10631L / 30 + 227013;
        while (num2 > 0)
        {
            num3 += 354 + (IsLeapYear(num2, 0) ? 1 : 0);
            num2--;
        }
        return num3;
    }
References System.Globalization.HijriCalendar.IsLeapYear(), and System.L.
Referenced by System.Globalization.HijriCalendar.GetAbsoluteDateHijri(), and System.Globalization.HijriCalendar.GetDatePart().