Terraria: System.Globalization.HijriCalendar.IsLeapDay
IsLeapDay() [2/2]
override bool System.Globalization.HijriCalendar.IsLeapDay (int year, int month, int day, int era) inline
Definition at line 280 of file HijriCalendar.cs.
    {
        int daysInMonth = GetDaysInMonth(year, month, era);
        if (day < 1 || day > daysInMonth)
        {
            throw new ArgumentOutOfRangeException("day", day, SR.Format(SR.ArgumentOutOfRange_Day, daysInMonth, month));
        }
        if (IsLeapYear(year, era) && month == 12)
        {
            return day == 30;
        }
        return false;
    }
References System.SR.ArgumentOutOfRange_Day, System.SR.Format(), System.Globalization.HijriCalendar.GetDaysInMonth(), System.Globalization.HijriCalendar.IsLeapYear(), and System.year.