Terraria: System.Globalization.HijriCalendar.ToDateTime
ToDateTime() [2/2]
override DateTime System.Globalization.HijriCalendar.ToDateTime (int year, int month, int day, int hour, int minute, int second, int millisecond, int era) inline
Definition at line 312 of file HijriCalendar.cs.
    {
        int daysInMonth = GetDaysInMonth(year, month, era);
        if (day < 1 || day > daysInMonth)
        {
            throw new ArgumentOutOfRangeException("day", day, SR.Format(SR.ArgumentOutOfRange_Day, daysInMonth, month));
        }
        long absoluteDateHijri = GetAbsoluteDateHijri(year, month, day);
        if (absoluteDateHijri < 0)
        {
            throw new ArgumentOutOfRangeException(null, SR.ArgumentOutOfRange_BadYearMonthDay);
        }
        return new DateTime(absoluteDateHijri * 864000000000L + Calendar.TimeToTicks(hour, minute, second, millisecond));
    }
References System.SR.ArgumentOutOfRange_BadYearMonthDay, System.SR.ArgumentOutOfRange_Day, System.DateTime, System.SR.Format(), System.Globalization.HijriCalendar.GetAbsoluteDateHijri(), System.Globalization.HijriCalendar.GetDaysInMonth(), System.L, System.Globalization.Calendar.TimeToTicks(), and System.year.