Terraria: System.Globalization.HijriCalendar.CheckTicksRange
CheckTicksRange()
static void System.Globalization.HijriCalendar.CheckTicksRange (long ticks) inline static package
Definition at line 93 of file HijriCalendar.cs.
    {
        if (ticks < s_calendarMinValue.Ticks || ticks > s_calendarMaxValue.Ticks)
        {
            throw new ArgumentOutOfRangeException("time", ticks, SR.Format(CultureInfo.InvariantCulture, SR.ArgumentOutOfRange_CalendarRange, s_calendarMinValue, s_calendarMaxValue));
        }
    }
References System.SR.ArgumentOutOfRange_CalendarRange, System.SR.Format(), System.Globalization.CultureInfo.InvariantCulture, System.Globalization.HijriCalendar.s_calendarMaxValue, and System.Globalization.HijriCalendar.s_calendarMinValue.
Referenced by System.Globalization.HijriCalendar.GetDatePart(), and System.Globalization.HijriCalendar.GetEra().