Terraria: System.Xml.Xsl.Qil.SubstitutionList.AddSubstitutionPair
AddSubstitutionPair()
void System.Xml.Xsl.Qil.SubstitutionList.AddSubstitutionPair (QilNode find, QilNode replace) inline
Definition at line 14 of file SubstitutionList.cs.
    {
        _s.Add(find);
        _s.Add(replace);
    }
References System.Xml.Xsl.Qil.SubstitutionList._s, System.Collections.ArrayList.Add(), and System.Xml.Dictionary.
Referenced by System.Xml.Xsl.Qil.QilCloneVisitor.BeginScope(), and System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.Subs().