Terraria: MS.Internal.Xml.XPath.XPathSortComparer.Clone
Clone()
XPathSortComparer MS.Internal.Xml.XPath.XPathSortComparer.Clone () inline package
Definition at line 74 of file XPathSortComparer.cs.
    {
        XPathSortComparer xPathSortComparer = new XPathSortComparer(_numSorts);
        for (int i = 0; i < _numSorts; i++)
        {
            xPathSortComparer._comparers[i] = _comparers[i];
            xPathSortComparer._expressions[i] = (Query)_expressions[i].Clone();
        }
        xPathSortComparer._numSorts = _numSorts;
        return xPathSortComparer;
    }
References MS.Internal.Xml.XPath.XPathSortComparer.XPathSortComparer(), MS.Internal.Xml.XPath.XPathSortComparer._comparers, MS.Internal.Xml.XPath.XPathSortComparer._expressions, MS.Internal.Xml.XPath.XPathSortComparer._numSorts, and MS.Internal.Xml.XPath.XPathSortComparer.Clone().
Referenced by MS.Internal.Xml.XPath.SortQuery.SortQuery(), and MS.Internal.Xml.XPath.XPathSortComparer.Clone().