Terraria: MS.Internal.Xml.Cache.XPathDocumentBuilder.NodePageFactory.AllocateSlot
AllocateSlot()
void MS.Internal.Xml.Cache.XPathDocumentBuilder.NodePageFactory.AllocateSlot (out XPathNode[] page, out int idx) inline
Definition at line 32 of file XPathDocumentBuilder.cs.
        {
            page = _page;
            idx = _pageInfo.NodeCount;
            if (++_pageInfo.NodeCount >= _page.Length)
            {
                if (_pageSize < 65536)
                {
                    _pageSize *= 2;
                }
                _page = new XPathNode[_pageSize];
                _pageInfo.NextPage = _page;
                _pageInfo = new XPathNodePageInfo(page, _pageInfo.PageNumber + 1);
                _page[0].Create(_pageInfo);
            }
        }
References MS.Internal.Xml.Cache.XPathDocumentBuilder.NodePageFactory._page, MS.Internal.Xml.Cache.XPathDocumentBuilder.NodePageFactory._pageInfo, MS.Internal.Xml.Cache.XPathDocumentBuilder.NodePageFactory._pageSize, MS.Internal.Xml.Cache.XPathNode.Create(), System.Xml.Dictionary, MS.Internal.Xml.Cache.XPathNodePageInfo.NodeCount, and MS.Internal.Xml.Cache.XPathNodePageInfo.PageNumber.
Referenced by MS.Internal.Xml.Cache.XPathDocumentBuilder.NewNamespaceNode(), and MS.Internal.Xml.Cache.XPathDocumentBuilder.NewNode().