Terraria: System.Linq.Expressions.BlockExpressionList.CopyTo
CopyTo() [1/2]
void System.Linq.Expressions.BlockExpressionList.CopyTo (Expression[] array, int index) inline
Definition at line 93 of file BlockExpressionList.cs.
    {
        ContractUtils.RequiresNotNull(array, "array");
        if (index < 0)
        {
            throw Error.ArgumentOutOfRange("index");
        }
        int expressionCount = _block.ExpressionCount;
        if (index + expressionCount > array.Length)
        {
            throw new ArgumentException();
        }
        array[index++] = _arg0;
        for (int i = 1; i < expressionCount; i++)
        {
            array[index++] = _block.GetExpression(i);
        }
    }
References System.Linq.Expressions.BlockExpressionList._arg0, System.Linq.Expressions.BlockExpressionList._block, System.Linq.Expressions.Error.ArgumentOutOfRange(), System.array, System.Linq.Expressions.BlockExpression.ExpressionCount, System.Linq.Expressions.BlockExpression.GetExpression(), System.Linq.index, and System.Dynamic.Utils.ContractUtils.RequiresNotNull().