Terraria: System.Xml.HtmlUtf8RawTextWriter.WriteProcessingInstruction
WriteProcessingInstruction() [2/2]
override void System.Xml.HtmlUtf8RawTextWriter.WriteProcessingInstruction (string target, string text) inline
Definition at line 197 of file HtmlUtf8RawTextWriter.cs.
    {
        _bufBytes[_bufPos++] = 60;
        _bufBytes[_bufPos++] = 63;
        RawText(target);
        _bufBytes[_bufPos++] = 32;
        WriteCommentOrPi(text, 63);
        _bufBytes[_bufPos++] = 62;
        if (_bufPos > _bufLen)
        {
            FlushBuffer();
        }
    }
References System.Xml.XmlUtf8RawTextWriter._bufBytes, System.Xml.XmlUtf8RawTextWriter._bufLen, System.Xml.XmlUtf8RawTextWriter._bufPos, System.Xml.XmlUtf8RawTextWriter.FlushBuffer(), System.Xml.XmlUtf8RawTextWriter.RawText(), System.text, and System.Xml.XmlUtf8RawTextWriter.WriteCommentOrPi().