Terraria: System.Xml.HtmlUtf8RawTextWriter.WriteUriAttributeText
WriteUriAttributeText()
unsafe void System.Xml.HtmlUtf8RawTextWriter.WriteUriAttributeText (char * pSrc, char * pSrcEnd) inline private
Definition at line 399 of file HtmlUtf8RawTextWriter.cs.
    {
        if (_endsWithAmpersand)
        {
            if (pSrcEnd - pSrc > 0 && *pSrc != '{')
            {
                OutputRestAmps();
            }
            _endsWithAmpersand = false;
        }
        fixed (byte* ptr = _bufBytes)
        {
            byte* ptr2 = ptr + _bufPos;
            char c = '\0';
            while (true)
            {
                byte* ptr3 = ptr2 + (pSrcEnd - pSrc);
                if (ptr3 > ptr + _bufLen)
                {
                    ptr3 = ptr + _bufLen;
                }
                while (ptr2 < ptr3 && XmlCharType.IsAttributeValueChar(c = *pSrc) && c < '\u0080')
                {
                    *(ptr2++) = (byte)c;
                    pSrc++;
                }
                if (pSrc >= pSrcEnd)
                {
                    break;
                }
                if (ptr2 >= ptr3)
                {
                    _bufPos = (int)(ptr2 - ptr);
                    FlushBuffer();
                    ptr2 = ptr + 1;
                    continue;
                }
                switch (c)
                {
                case '&':
                    if (pSrc + 1 == pSrcEnd)
                    {
                        _endsWithAmpersand = true;
                    }
                    else if (pSrc[1] != '{')
                    {
                        ptr2 = XmlUtf8RawTextWriter.AmpEntity(ptr2);
                        break;
                    }
                    *(ptr2++) = (byte)c;
                    break;
                case '"':
                    ptr2 = XmlUtf8RawTextWriter.QuoteEntity(ptr2);
                    break;
                case '\t':
                case '\'':
                case '<':
                case '>':
                    *(ptr2++) = (byte)c;
                    break;
                case '\r':
                    ptr2 = XmlUtf8RawTextWriter.CarriageReturnEntity(ptr2);
                    break;
                case '\n':
                    ptr2 = XmlUtf8RawTextWriter.LineFeedEntity(ptr2);
                    break;
                default:
                    fixed (byte* ptr4 = _uriEscapingBuffer)
                    {
                        byte* ptr5 = ptr4;
                        byte* pDst = ptr5;
                        XmlUtf8RawTextWriter.CharToUTF8(ref pSrc, pSrcEnd, ref pDst);
                        for (; ptr5 < pDst; ptr5++)
{
                            *(ptr2++) = 37;
                            *(ptr2++) = (byte)System.HexConverter.ToCharUpper(*ptr5 >> 4);
                            *(ptr2++) = (byte)System.HexConverter.ToCharUpper(*ptr5);
                        }
                    }
                    continue;
                }
                pSrc++;
            }
            _bufPos = (int)(ptr2 - ptr);
        }
    }
References System.Xml.XmlUtf8RawTextWriter._bufBytes, System.Xml.XmlUtf8RawTextWriter._bufLen, System.Xml.XmlUtf8RawTextWriter._bufPos, System.Xml.HtmlUtf8RawTextWriter._endsWithAmpersand, System.Xml.HtmlUtf8RawTextWriter._uriEscapingBuffer, System.Xml.XmlUtf8RawTextWriter.AmpEntity(), System.Xml.XmlUtf8RawTextWriter.CarriageReturnEntity(), System.Xml.XmlUtf8RawTextWriter.CharToUTF8(), System.Xml.Dictionary, System.Xml.XmlUtf8RawTextWriter.FlushBuffer(), System.Xml.XmlCharType.IsAttributeValueChar(), System.Xml.XmlUtf8RawTextWriter.LineFeedEntity(), System.Xml.HtmlUtf8RawTextWriter.OutputRestAmps(), System.Xml.XmlUtf8RawTextWriter.QuoteEntity(), and System.HexConverter.ToCharUpper().
Referenced by System.Xml.HtmlUtf8RawTextWriter.WriteHtmlAttributeTextBlock().