Terraria: System.Xml.HtmlUtf8RawTextWriter.WriteHtmlAttributeTextBlock
WriteHtmlAttributeTextBlock()
unsafe void System.Xml.HtmlUtf8RawTextWriter.WriteHtmlAttributeTextBlock (char * pSrc, char * pSrcEnd) inline protected
Definition at line 297 of file HtmlUtf8RawTextWriter.cs.
    {
        if ((_currentAttributeProperties & (AttributeProperties)7u) != 0)
        {
            if ((_currentAttributeProperties & AttributeProperties.BOOLEAN) == 0)
            {
                if ((_currentAttributeProperties & (AttributeProperties)5u) != 0 && !_doNotEscapeUriAttributes)
                {
                    WriteUriAttributeText(pSrc, pSrcEnd);
                }
                else
                {
                    WriteHtmlAttributeText(pSrc, pSrcEnd);
                }
            }
        }
        else if ((_currentElementProperties & ElementProperties.HAS_NS) != 0)
        {
            WriteAttributeTextBlock(pSrc, pSrcEnd);
        }
        else
        {
            WriteHtmlAttributeText(pSrc, pSrcEnd);
        }
    }
References System.Xml.HtmlUtf8RawTextWriter._currentAttributeProperties, System.Xml.HtmlUtf8RawTextWriter._currentElementProperties, System.Xml.HtmlUtf8RawTextWriter._doNotEscapeUriAttributes, System.Xml.Dictionary, System.Xml.XmlUtf8RawTextWriter.WriteAttributeTextBlock(), System.Xml.HtmlUtf8RawTextWriter.WriteHtmlAttributeText(), and System.Xml.HtmlUtf8RawTextWriter.WriteUriAttributeText().
Referenced by System.Xml.HtmlUtf8RawTextWriter.WriteString().