Terraria: System.Xml.HtmlUtf8RawTextWriter.WriteHtmlElementTextBlock
WriteHtmlElementTextBlock()
unsafe void System.Xml.HtmlUtf8RawTextWriter.WriteHtmlElementTextBlock (char * pSrc, char * pSrcEnd) inline protected
Definition at line 285 of file HtmlUtf8RawTextWriter.cs.
    {
        if ((_currentElementProperties & ElementProperties.NO_ENTITIES) != 0)
        {
            RawText(pSrc, pSrcEnd);
        }
        else
        {
            WriteElementTextBlock(pSrc, pSrcEnd);
        }
    }
References System.Xml.HtmlUtf8RawTextWriter._currentElementProperties, System.Xml.Dictionary, System.Xml.XmlUtf8RawTextWriter.RawText(), and System.Xml.XmlUtf8RawTextWriter.WriteElementTextBlock().
Referenced by System.Xml.HtmlUtf8RawTextWriter.WriteString().