Terraria: Terraria.GameContent.UI.States.UIEmotesMenu.Recalculate
Recalculate()
override void Terraria.GameContent.UI.States.UIEmotesMenu.Recalculate () inline virtual
Reimplemented from Terraria.UI.UIElement.
Definition at line 285 of file UIEmotesMenu.cs.
    {
        if (_scrollBar != null)
        {
            if (_isScrollbarAttached && !_scrollBar.CanScroll)
            {
                _container.RemoveChild(_scrollBar);
                _isScrollbarAttached = false;
                _list.Width.Set(0f, 1f);
            }
            else if (!_isScrollbarAttached && _scrollBar.CanScroll)
            {
                _container.Append(_scrollBar);
                _isScrollbarAttached = true;
                _list.Width.Set(-25f, 1f);
            }
        }
        base.Recalculate();
    }
References Terraria.GameContent.UI.States.UIEmotesMenu._container, Terraria.GameContent.UI.States.UIEmotesMenu._isScrollbarAttached, Terraria.GameContent.UI.States.UIEmotesMenu._list, Terraria.GameContent.UI.States.UIEmotesMenu._scrollBar, Terraria.UI.UIElement.Append(), Terraria.GameContent.UI.Elements.UIScrollbar.CanScroll, Terraria.UI.UIElement.RemoveChild(), Terraria.UI.StyleDimension.Set(), and Terraria.UI.UIElement.Width.