Terraria: System.Xml.HtmlUtf8RawTextWriter.WriteHtmlAttributeText
WriteHtmlAttributeText()
unsafe void System.Xml.HtmlUtf8RawTextWriter.WriteHtmlAttributeText (char * pSrc, char * pSrcEnd) inline private
Definition at line 323 of file HtmlUtf8RawTextWriter.cs.
    {
        if (_endsWithAmpersand)
        {
            if (pSrcEnd - pSrc > 0 && *pSrc != '{')
            {
                OutputRestAmps();
            }
            _endsWithAmpersand = false;
        }
        fixed (byte* ptr = _bufBytes)
        {
            byte* pDst = ptr + _bufPos;
            char c = '\0';
            while (true)
            {
                byte* ptr2 = pDst + (pSrcEnd - pSrc);
                if (ptr2 > ptr + _bufLen)
                {
                    ptr2 = ptr + _bufLen;
                }
                while (pDst < ptr2 && XmlCharType.IsAttributeValueChar(c = *pSrc) && c <= '\u007f')
                {
                    *(pDst++) = (byte)c;
                    pSrc++;
                }
                if (pSrc >= pSrcEnd)
                {
                    break;
                }
                if (pDst >= ptr2)
                {
                    _bufPos = (int)(pDst - ptr);
                    FlushBuffer();
                    pDst = ptr + 1;
                    continue;
                }
                switch (c)
                {
                case '&':
                    if (pSrc + 1 == pSrcEnd)
                    {
                        _endsWithAmpersand = true;
                    }
                    else if (pSrc[1] != '{')
                    {
                        pDst = XmlUtf8RawTextWriter.AmpEntity(pDst);
                        break;
                    }
                    *(pDst++) = (byte)c;
                    break;
                case '"':
                    pDst = XmlUtf8RawTextWriter.QuoteEntity(pDst);
                    break;
                case '\t':
                case '\'':
                case '<':
                case '>':
                    *(pDst++) = (byte)c;
                    break;
                case '\r':
                    pDst = XmlUtf8RawTextWriter.CarriageReturnEntity(pDst);
                    break;
                case '\n':
                    pDst = XmlUtf8RawTextWriter.LineFeedEntity(pDst);
                    break;
                default:
                    EncodeChar(ref pSrc, pSrcEnd, ref pDst);
                    continue;
                }
                pSrc++;
            }
            _bufPos = (int)(pDst - ptr);
        }
    }
References System.Xml.XmlUtf8RawTextWriter._bufBytes, System.Xml.XmlUtf8RawTextWriter._bufLen, System.Xml.XmlUtf8RawTextWriter._bufPos, System.Xml.HtmlUtf8RawTextWriter._endsWithAmpersand, System.Xml.XmlUtf8RawTextWriter.AmpEntity(), System.Xml.XmlUtf8RawTextWriter.CarriageReturnEntity(), System.Xml.Dictionary, System.Xml.XmlUtf8RawTextWriter.EncodeChar(), System.Xml.XmlUtf8RawTextWriter.FlushBuffer(), System.Xml.XmlCharType.IsAttributeValueChar(), System.Xml.XmlUtf8RawTextWriter.LineFeedEntity(), System.Xml.HtmlUtf8RawTextWriter.OutputRestAmps(), and System.Xml.XmlUtf8RawTextWriter.QuoteEntity().
Referenced by System.Xml.HtmlUtf8RawTextWriter.WriteHtmlAttributeTextBlock().