Terraria: System.Xml.HtmlUtf8RawTextWriter.WriteMetaElement
WriteMetaElement()
void System.Xml.HtmlUtf8RawTextWriter.WriteMetaElement () inline protected
Definition at line 271 of file HtmlUtf8RawTextWriter.cs.
    {
        RawText("<META http-equiv=\"Content-Type\"");
        if (_mediaType == null)
        {
            _mediaType = "text/html";
        }
        RawText(" content=\"");
        RawText(_mediaType);
        RawText("; charset=");
        RawText(_encoding.WebName);
        RawText("\">");
    }
References System.Xml.XmlUtf8RawTextWriter._encoding, System.Xml.HtmlUtf8RawTextWriter._mediaType, and System.Xml.XmlUtf8RawTextWriter.RawText().
Referenced by System.Xml.HtmlUtf8RawTextWriter.StartElementContent(), and System.Xml.HtmlUtf8RawTextWriterIndent.StartElementContent().