Terraria: UIWorkshopPublishResourcePackListItem.UIWorkshopPublishResourcePackListItem
UIWorkshopPublishResourcePackListItem()
UIWorkshopPublishResourcePackListItem.UIWorkshopPublishResourcePackListItem (UIState ownerState, ResourcePack data, int orderInList, bool canBePublished) inline
     {
         _ownerState = ownerState;
         _orderInList = orderInList;
         _data = data;
         _canPublish = canBePublished;
         LoadTextures();
         InitializeAppearance();
         UIElement uIElement = new UIElement
         {
             Width = new StyleDimension(72f, 0f),
             Height = new StyleDimension(72f, 0f),
             Left = new StyleDimension(4f, 0f),
             VAlign = 0.5f
         };
         uIElement.OnLeftDoubleClick += PublishButtonClick_ImportResourcePackToLocalFiles;
         UIImage element = new UIImage(data.Icon)
         {
             Width = new StyleDimension(-6f, 1f),
             Height = new StyleDimension(-6f, 1f),
             HAlign = 0.5f,
             VAlign = 0.5f,
             ScaleToFit = true,
             AllowResizingDimensions = false,
             IgnoresMouseInteraction = true
         };
         UIImage element2 = new UIImage(Main.Assets.Request<Texture2D>("Images/UI/Achievement_Borders", (AssetRequestMode)1))
         {
             HAlign = 0.5f,
             VAlign = 0.5f,
             IgnoresMouseInteraction = true
         };
         uIElement.Append(element);
         uIElement.Append(element2);
         Append(uIElement);
         _iconArea = uIElement;
         _ = 4f;
         _publishButton = new UIIconTextButton(Language.GetText("Workshop.Publish"), Color.White, "Images/UI/Workshop/Publish");
         _publishButton.HAlign = 1f;
         _publishButton.VAlign = 1f;
         _publishButton.OnLeftClick += PublishButtonClick_ImportResourcePackToLocalFiles;
         base.OnLeftDoubleClick += PublishButtonClick_ImportResourcePackToLocalFiles;
         Append(_publishButton);
         _publishButton.SetSnapPoint("Publish", orderInList);
     }
References _canPublish, _data, _iconArea, _orderInList, _ownerState, _publishButton, UIElement.Append(), Main.Assets, Color, Language.GetText(), UIElement.HAlign, UIElement.Height, ResourcePack.Icon, UIElement.IgnoresMouseInteraction, InitializeAppearance(), UIElement.Left, LoadTextures(), UIElement.OnLeftClick, UIElement.OnLeftDoubleClick, PublishButtonClick_ImportResourcePackToLocalFiles(), UIElement.SetSnapPoint(), UIElement.VAlign, and UIElement.Width.