Terraria: System.Environment.SetEnvironmentVariableCore
SetEnvironmentVariableCore()
static void System.Environment.SetEnvironmentVariableCore (string variable, string value) inline static private
Definition at line 888 of file Environment.cs.
    {
        if (!Interop.Kernel32.SetEnvironmentVariable(variable, value))
        {
            int lastPInvokeError = Marshal.GetLastPInvokeError();
            switch (lastPInvokeError)
            {
            case 203:
                break;
            case 206:
                throw new ArgumentException(SR.Argument_LongEnvVarValue);
            case 8:
            case 1450:
                throw new OutOfMemoryException(Interop.Kernel32.GetMessage(lastPInvokeError));
            default:
                throw new ArgumentException(Interop.Kernel32.GetMessage(lastPInvokeError));
            }
        }
    }
References System.SR.Argument_LongEnvVarValue, System.Runtime.InteropServices.Marshal.GetLastPInvokeError(), Interop.Kernel32.GetMessage(), Interop.Kernel32.SetEnvironmentVariable(), and System.value.
Referenced by System.Environment.SetEnvironmentVariable().