Terraria: System.Environment.OpenEnvironmentKeyIfExists
OpenEnvironmentKeyIfExists()
static RegistryKey System.Environment.OpenEnvironmentKeyIfExists (bool fromMachine, bool writable) inline static private
Definition at line 619 of file Environment.cs.
    {
        RegistryKey registryKey;
        string name;
        if (fromMachine)
        {
            registryKey = Registry.LocalMachine;
            name = "System\\CurrentControlSet\\Control\\Session Manager\\Environment";
        }
        else
        {
            registryKey = Registry.CurrentUser;
            name = "Environment";
        }
        return registryKey.OpenSubKey(name, writable);
    }
References Internal.Win32.Registry.CurrentUser, Internal.Win32.Registry.LocalMachine, and Internal.Win32.RegistryKey.OpenSubKey().
Referenced by System.Environment.GetEnvironmentVariableFromRegistry(), System.Environment.GetEnvironmentVariablesFromRegistry(), and System.Environment.SetEnvironmentVariableFromRegistry().