Terraria: System.Environment.SetEnvironmentVariable
SetEnvironmentVariable() [2/2]
static void System.Environment.SetEnvironmentVariable (string variable, string? value, EnvironmentVariableTarget target) inline static
Definition at line 480 of file Environment.cs.
    {
        if (target == EnvironmentVariableTarget.Process)
        {
            SetEnvironmentVariable(variable, value);
            return;
        }
        ValidateVariableAndValue(variable, ref value);
        bool fromMachine = ValidateAndConvertRegistryTarget(target);
        SetEnvironmentVariableFromRegistry(variable, value, fromMachine);
    }
References System.Environment.SetEnvironmentVariable(), System.Environment.SetEnvironmentVariableFromRegistry(), System.Environment.ValidateAndConvertRegistryTarget(), System.Environment.ValidateVariableAndValue(), and System.value.