Terraria: System.Environment.GetEnvironmentVariables
GetEnvironmentVariables() [2/2]
static IDictionary System.Environment.GetEnvironmentVariables (EnvironmentVariableTarget target) inline static
Definition at line 464 of file Environment.cs.
    {
        if (target == EnvironmentVariableTarget.Process)
        {
            return GetEnvironmentVariables();
        }
        bool fromMachine = ValidateAndConvertRegistryTarget(target);
        return GetEnvironmentVariablesFromRegistry(fromMachine);
    }
References System.Environment.GetEnvironmentVariables(), System.Environment.GetEnvironmentVariablesFromRegistry(), and System.Environment.ValidateAndConvertRegistryTarget().