Terraria: System.Environment.GetProcessPath
GetProcessPath()
static string System.Environment.GetProcessPath () inline static private
Definition at line 839 of file Environment.cs.
    {
        Span<char> initialBuffer = stackalloc char[260];
        ValueStringBuilder valueStringBuilder = new ValueStringBuilder(initialBuffer);
        uint moduleFileName;
        while ((moduleFileName = Interop.Kernel32.GetModuleFileName(IntPtr.Zero, ref valueStringBuilder.GetPinnableReference(), (uint)valueStringBuilder.Capacity)) >= valueStringBuilder.Capacity)
        {
            valueStringBuilder.EnsureCapacity((int)moduleFileName);
        }
        if (moduleFileName == 0)
        {
            throw Win32Marshal.GetExceptionForLastWin32Error();
        }
        valueStringBuilder.Length = (int)moduleFileName;
        return valueStringBuilder.ToString();
    }
References System.Text.ValueStringBuilder.Capacity, System.Text.ValueStringBuilder.EnsureCapacity(), System.IO.Win32Marshal.GetExceptionForLastWin32Error(), Interop.Kernel32.GetModuleFileName(), System.Text.ValueStringBuilder.GetPinnableReference(), System.Text.ValueStringBuilder.ToString(), and System.IntPtr.Zero.