Terraria: System.Environment.GetEnvironmentVariablesFromRegistry
GetEnvironmentVariablesFromRegistry()
static IDictionary System.Environment.GetEnvironmentVariablesFromRegistry (bool fromMachine) inline static private
Definition at line 595 of file Environment.cs.
    {
        Hashtable hashtable = new Hashtable();
        using (RegistryKey registryKey = OpenEnvironmentKeyIfExists(fromMachine, writable: false))
        {
            if (registryKey != null)
            {
                string[] valueNames = registryKey.GetValueNames();
                foreach (string text in valueNames)
                {
                    string value = registryKey.GetValue(text, "").ToString();
                    try
                    {
                        hashtable.Add(text, value);
                    }
                    catch (ArgumentException)
                    {
                    }
                }
            }
        }
        return hashtable;
    }
References System.Collections.Hashtable.Add(), Internal.Win32.RegistryKey.GetValue(), Internal.Win32.RegistryKey.GetValueNames(), System.Environment.OpenEnvironmentKeyIfExists(), System.text, and System.value.
Referenced by System.Environment.GetEnvironmentVariables().