Terraria: System.Environment.GetFolderPath
GetFolderPath() [1/2]
static string System.Environment.GetFolderPath (SpecialFolder folder) inline static
Definition at line 510 of file Environment.cs.
    {
        return GetFolderPath(folder, SpecialFolderOption.None);
    }
References System.Environment.GetFolderPath().
Referenced by System.IO.IsolatedStorage.Helper.GetDataDirectory(), System.Environment.GetFolderPath(), and ReLogic.OS.Windows.PathService.GetStoragePath().