Terraria: System.Environment.GetEnvironmentVariable
GetEnvironmentVariable() [2/2]
static ? string System.Environment.GetEnvironmentVariable (string variable, EnvironmentVariableTarget target) inline static
Definition at line 450 of file Environment.cs.
    {
        if (target == EnvironmentVariableTarget.Process)
        {
            return GetEnvironmentVariable(variable);
        }
        if (variable == null)
        {
            throw new ArgumentNullException("variable");
        }
        bool fromMachine = ValidateAndConvertRegistryTarget(target);
        return GetEnvironmentVariableFromRegistry(variable, fromMachine);
    }
References System.Environment.GetEnvironmentVariable(), System.Environment.GetEnvironmentVariableFromRegistry(), and System.Environment.ValidateAndConvertRegistryTarget().