Terraria: System.Environment.GetEnvironmentVariables
GetEnvironmentVariables() [1/2]
static unsafe IDictionary System.Environment.GetEnvironmentVariables () inline static
Definition at line 908 of file Environment.cs.
    {
        char* environmentStringsW = Interop.Kernel32.GetEnvironmentStringsW();
        if (environmentStringsW == null)
        {
            throw new OutOfMemoryException();
        }
        try
        {
            Hashtable hashtable = new Hashtable();
            char* ptr = environmentStringsW;
            while (true)
            {
                ReadOnlySpan<char> span = MemoryMarshal.CreateReadOnlySpanFromNullTerminated(ptr);
                if (span.IsEmpty)
                {
                    break;
                }
                int num = span.IndexOf('=');
                if (num > 0)
                {
                    string key = new string(span.Slice(0, num));
                    string value = new string(span.Slice(num + 1));
                    try
                    {
                        hashtable.Add(key, value);
                    }
                    catch (ArgumentException)
                    {
                    }
                }
                ptr += span.Length + 1;
            }
            return hashtable;
        }
        finally
        {
            Interop.BOOL bOOL = Interop.Kernel32.FreeEnvironmentStringsW(environmentStringsW);
        }
    }
References System.Collections.Hashtable.Add(), System.Runtime.InteropServices.MemoryMarshal.CreateReadOnlySpanFromNullTerminated(), Interop.Kernel32.FreeEnvironmentStringsW(), Interop.Kernel32.GetEnvironmentStringsW(), System.ReadOnlySpan< T >.IsEmpty, System.key, System.ReadOnlySpan< T >.Slice(), and System.value.
Referenced by System.Environment.GetEnvironmentVariables().