Terraria: System.Environment.ExpandEnvironmentVariablesCore
ExpandEnvironmentVariablesCore()
static string System.Environment.ExpandEnvironmentVariablesCore (string name) inline static private
Definition at line 816 of file Environment.cs.
    {
        Span<char> initialBuffer = stackalloc char[128];
        ValueStringBuilder valueStringBuilder = new ValueStringBuilder(initialBuffer);
        uint num;
        while ((num = Interop.Kernel32.ExpandEnvironmentStrings(name, ref valueStringBuilder.GetPinnableReference(), (uint)valueStringBuilder.Capacity)) > valueStringBuilder.Capacity)
        {
            valueStringBuilder.EnsureCapacity((int)num);
        }
        if (num == 0)
        {
            throw Win32Marshal.GetExceptionForLastWin32Error();
        }
        valueStringBuilder.Length = (int)(num - 1);
        return valueStringBuilder.ToString();
    }
References System.Text.ValueStringBuilder.Capacity, System.Text.ValueStringBuilder.EnsureCapacity(), Interop.Kernel32.ExpandEnvironmentStrings(), System.IO.Win32Marshal.GetExceptionForLastWin32Error(), System.Text.ValueStringBuilder.GetPinnableReference(), and System.Text.ValueStringBuilder.ToString().
Referenced by System.Environment.ExpandEnvironmentVariables().