Terraria: ActionPlaceStatue.Apply
Apply()
override bool ActionPlaceStatue.Apply (Point origin, int x, int y, params object[] args) inline virtual
Implements GenAction.
     {
         Point16 point = ((_statueIndex != -1) ? GenVars.statueList[_statueIndex] : GenVars.statueList[GenBase._random.Next(2, GenVars.statueList.Length)]);
         WorldGen.PlaceTile(x, y, point.X, mute: true, forced: false, -1, point.Y);
         return UnitApply(origin, x, y, args);
     }
References GenBase._random, _statueIndex, UnifiedRandom.Next(), WorldGen.PlaceTile(), GenVars.statueList, GenAction.UnitApply(), Point16.X, and Point16.Y.