Terraria: NetworkText.ToDebugInfoString
ToDebugInfoString()
string NetworkText.ToDebugInfoString (string linePrefix = "") inline private
     {
         string text = string.Format("{0}Mode: {1}\n{0}Text: {2}\n", linePrefix, _mode, _text);
         if (_mode == Mode.LocalizationKey)
         {
             text += $"{linePrefix}Localized Text: {Language.GetTextValue(_text)}\n";
         }
         if (_mode != 0)
         {
             for (int i = 0; i < _substitutions.Length; i++)
             {
                 text += $"{linePrefix}Substitution {i}:\n";
                 text += _substitutions[i].ToDebugInfoString(linePrefix + "\t");
             }
         }
         return text;
     }
References _mode, _substitutions, _text, and ToDebugInfoString().
Referenced by ToDebugInfoString(), and ToString().