Terraria: NetworkText.FromKey
FromKey()
static NetworkText NetworkText.FromKey (string key, params object[] substitutions) inline static
     {
         return new NetworkText(key, Mode.LocalizationKey)
         {
             _substitutions = ConvertSubstitutionsToNetworkText(substitutions)
         };
     }
References NetworkText(), _substitutions, and ConvertSubstitutionsToNetworkText().
Referenced by ItemVariants.ItemVariants(), NPC.checkDead(), Main.CheckForMoonEventsScoreDisplay(), Main.CheckForMoonEventsStartingTemporarySeasons(), BirthdayParty.CheckNight(), WorldGen.CheckOrb(), DD2Event.CheckProgress(), NPC.CountKillForBannersAndDropThem(), Lang.CreateDeathMessage(), NPC.DoDeathEvents(), NPC.DoDeathEvents_CelebrateBossDeath(), DD2Event.FailureMessage(), MessageBuffer.GetData(), NPC.GetFullNetName(), Lang.GetInvasionWaveText(), NPC.GetTypeNetName(), NetMessage.greetPlayer(), Projectile.HandleMovement(), TeleportPylonsSystem.HandleTeleportRequest(), Main.InvasionWarning(), DD2Event.LoseInvasionMessage(), WorldGen.MessageLunarApocalypse(), WorldGen.meteor(), BirthdayParty.NaturalAttempt(), NPC.NewNPC(), NPC.NPCLoot(), Netplay.OnConnectionAccepted(), AllDeathCommand.ProcessIncomingMessage(), AllPVPDeathCommand.ProcessIncomingMessage(), DeathCommand.ProcessIncomingMessage(), PVPDeathCommand.ProcessIncomingMessage(), GolfHelper.ContactListener.PutBallInCup_TextAndEffects(), WorldGen.SmashAltar(), WorldGen.smCallBack(), RemoteClient.SpamUpdate(), NPC.SpawnBoss(), NPC.SpawnOnPlayer(), NPC.SpawnSkeletron(), WorldGen.SpawnTownNPC(), WorldGen.SpawnTravelNPC(), NPC.SpawnWOF(), Main.startDedInputCallBack(), WorldGen.StartImpendingDoom(), DD2Event.StartInvasion(), NetMessage.SyncOnePlayer(), LocalizedText.ToNetworkText(), NPC.UnlockOrExchangePet(), WorldGen.UnspawnTravelNPC(), Main.UpdateSlimeRainWarning(), BirthdayParty.UpdateTime(), and DD2Event.WinInvasionInternal().