Terraria: NetworkText.ToString
ToString()
override string NetworkText.ToString () inline
     {
         try
         {
             switch (_mode)
             {
             case Mode.Literal:
                 return _text;
             case Mode.Formattable:
             {
                 string text2 = _text;
                 object[] substitutions = _substitutions;
                 return string.Format(text2, substitutions);
             }
             case Mode.LocalizationKey:
             {
                 string text = _text;
                 object[] substitutions = _substitutions;
                 return Language.GetTextValue(text, substitutions);
             }
             default:
                 return _text;
             }
         }
         catch (Exception ex)
         {
             string.Concat(string.Concat("NetworkText.ToString() threw an exception.\n" + ToDebugInfoString(), "\n"), "Exception: ", ex);
             SetToEmptyLiteral();
         }
         return _text;
     }
References _mode, _substitutions, _text, Language.GetTextValue(), SetToEmptyLiteral(), and ToDebugInfoString().
Referenced by WorldGen.BroadcastText(), NPC.checkDead(), NPC.CheckProgressFrostMoon(), NPC.CheckProgressPumpkinMoon(), ConvertSubstitutionsToNetworkText(), NPC.CountKillForBannersAndDropThem(), ChatHelper.DisplayMessage(), Player.DropTombstone(), NPC.DropTombstoneTownNPC(), MessageBuffer.GetData(), Projectile.HandleMovement(), Player.KillMe(), GolfHelper.ContactListener.PutBallInCup_TextAndEffects(), Main.startPumpkinMoon(), Main.startSnowMoon(), ItemVariant.ToString(), and ItemVariantCondition.ToString().