Terraria: NetworkText.DeserializeLiteral
DeserializeLiteral()
static NetworkText NetworkText.DeserializeLiteral (BinaryReader reader) inline static
     {
         Mode mode = (Mode)reader.ReadByte();
         NetworkText networkText = new NetworkText(reader.ReadString(), mode);
         networkText.DeserializeSubstitutionList(reader);
         if (mode != 0)
         {
             networkText.SetToEmptyLiteral();
         }
         return networkText;
     }
References NetworkText(), DeserializeSubstitutionList(), and SetToEmptyLiteral().