Terraria: NetworkText.FromFormattable
FromFormattable()
static NetworkText NetworkText.FromFormattable (string text, params object[] substitutions) inline static
     {
         return new NetworkText(text, Mode.Formattable)
         {
             _substitutions = ConvertSubstitutionsToNetworkText(substitutions)
         };
     }
References NetworkText(), _substitutions, and ConvertSubstitutionsToNetworkText().
Referenced by HelpCommand.ComposeMessage(), NetMessage.greetPlayer(), ChatInitializer.PrepareAliases(), and RollCommand.ProcessIncomingMessage().