Terraria: System.Xml.Xsl.Qil.QilVisitor.VisitAssumeReference
VisitAssumeReference()
virtual QilNode System.Xml.Xsl.Qil.QilVisitor.VisitAssumeReference (QilNode expr) inline protected virtual inherited
Definition at line 5 of file QilVisitor.cs.
    {
        if (expr is QilReference)
        {
            return VisitReference(expr);
        }
        return Visit(expr);
    }
References System.Xml.Dictionary, System.Xml.Xsl.Qil.QilVisitor.Visit(), and System.Xml.Xsl.Qil.QilVisitor.VisitReference().
Referenced by System.Xml.Xsl.Qil.QilCloneVisitor.Clone(), System.Xml.Xsl.XPath.XPathBuilder.FixupVisitor.CountUnfixedLast(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.NodeFinder.Find(), System.Xml.Xsl.XPath.XPathBuilder.FixupVisitor.Fixup(), System.Xml.Xsl.XPath.XPathBuilder.FixupVisitor.Fixup(), and System.Xml.Xsl.Xslt.ReferenceReplacer.Replace().