Terraria: System.Xml.Xsl.Qil.QilVisitor.VisitReference
VisitReference()
virtual QilNode System.Xml.Xsl.Qil.QilVisitor.VisitReference (QilNode n) inline protected virtual inherited
Reimplemented in System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.NodeFinder, System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.EqualityIndexVisitor, System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.NodeCounter, System.Xml.Xsl.Xslt.InvokeGenerator, System.Xml.Xsl.Xslt.ReferenceReplacer, System.Xml.Xsl.IlGen.XmlILOptimizerVisitor, and System.Xml.Xsl.Qil.QilCloneVisitor.
Definition at line 179 of file QilVisitor.cs.
    {
        if (n == null)
        {
            return VisitNull();
        }
        return n.NodeType switch
        {
            QilNodeType.For => VisitForReference((QilIterator)n),
            QilNodeType.Let => VisitLetReference((QilIterator)n),
            QilNodeType.Parameter => VisitParameterReference((QilParameter)n),
            QilNodeType.Function => VisitFunctionReference((QilFunction)n),
            _ => VisitUnknown(n),
        };
    }
References System.Xml.Dictionary, System.Xml.Xsl.Qil.QilVisitor.VisitForReference(), System.Xml.Xsl.Qil.QilVisitor.VisitFunctionReference(), System.Xml.Xsl.Qil.QilVisitor.VisitLetReference(), System.Xml.Xsl.Qil.QilVisitor.VisitNull(), System.Xml.Xsl.Qil.QilVisitor.VisitParameterReference(), and System.Xml.Xsl.Qil.QilVisitor.VisitUnknown().
Referenced by System.Xml.Xsl.Qil.QilVisitor.VisitAssumeReference(), System.Xml.Xsl.Qil.QilReplaceVisitor.VisitChildren(), and System.Xml.Xsl.Qil.QilVisitor.VisitChildren().