Terraria: System.Xml.Xsl.Qil.QilVisitor.Visit
Visit()
virtual QilNode System.Xml.Xsl.Qil.QilVisitor.Visit (QilNode n) inline protected virtual inherited
Reimplemented in System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.NodeFinder, System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.NodeCounter, System.Xml.Xsl.Qil.QilScopedVisitor, System.Xml.Xsl.Xslt.KeyMatchBuilder.PathConvertor, System.Xml.Xsl.IlGen.XmlILOptimizerVisitor, System.Xml.Xsl.IlGen.XmlILVisitor, System.Xml.Xsl.Qil.QilPatternVisitor, and System.Xml.Xsl.Qil.QilCloneVisitor.
Definition at line 60 of file QilVisitor.cs.
    {
        if (n == null)
        {
            return VisitNull();
        }
        return n.NodeType switch
        {
            QilNodeType.QilExpression => VisitQilExpression((QilExpression)n),
            QilNodeType.FunctionList => VisitFunctionList((QilList)n),
            QilNodeType.GlobalVariableList => VisitGlobalVariableList((QilList)n),
            QilNodeType.GlobalParameterList => VisitGlobalParameterList((QilList)n),
            QilNodeType.ActualParameterList => VisitActualParameterList((QilList)n),
            QilNodeType.FormalParameterList => VisitFormalParameterList((QilList)n),
            QilNodeType.SortKeyList => VisitSortKeyList((QilList)n),
            QilNodeType.BranchList => VisitBranchList((QilList)n),
            QilNodeType.OptimizeBarrier => VisitOptimizeBarrier((QilUnary)n),
            QilNodeType.Unknown => VisitUnknown(n),
            QilNodeType.DataSource => VisitDataSource((QilDataSource)n),
            QilNodeType.Nop => VisitNop((QilUnary)n),
            QilNodeType.Error => VisitError((QilUnary)n),
            QilNodeType.Warning => VisitWarning((QilUnary)n),
            QilNodeType.For => VisitFor((QilIterator)n),
            QilNodeType.Let => VisitLet((QilIterator)n),
            QilNodeType.Parameter => VisitParameter((QilParameter)n),
            QilNodeType.PositionOf => VisitPositionOf((QilUnary)n),
            QilNodeType.True => VisitTrue(n),
            QilNodeType.False => VisitFalse(n),
            QilNodeType.LiteralString => VisitLiteralString((QilLiteral)n),
            QilNodeType.LiteralInt32 => VisitLiteralInt32((QilLiteral)n),
            QilNodeType.LiteralInt64 => VisitLiteralInt64((QilLiteral)n),
            QilNodeType.LiteralDouble => VisitLiteralDouble((QilLiteral)n),
            QilNodeType.LiteralDecimal => VisitLiteralDecimal((QilLiteral)n),
            QilNodeType.LiteralQName => VisitLiteralQName((QilName)n),
            QilNodeType.LiteralType => VisitLiteralType((QilLiteral)n),
            QilNodeType.LiteralObject => VisitLiteralObject((QilLiteral)n),
            QilNodeType.And => VisitAnd((QilBinary)n),
            QilNodeType.Or => VisitOr((QilBinary)n),
            QilNodeType.Not => VisitNot((QilUnary)n),
            QilNodeType.Conditional => VisitConditional((QilTernary)n),
            QilNodeType.Choice => VisitChoice((QilChoice)n),
            QilNodeType.Length => VisitLength((QilUnary)n),
            QilNodeType.Sequence => VisitSequence((QilList)n),
            QilNodeType.Union => VisitUnion((QilBinary)n),
            QilNodeType.Intersection => VisitIntersection((QilBinary)n),
            QilNodeType.Difference => VisitDifference((QilBinary)n),
            QilNodeType.Average => VisitAverage((QilUnary)n),
            QilNodeType.Sum => VisitSum((QilUnary)n),
            QilNodeType.Minimum => VisitMinimum((QilUnary)n),
            QilNodeType.Maximum => VisitMaximum((QilUnary)n),
            QilNodeType.Negate => VisitNegate((QilUnary)n),
            QilNodeType.Add => VisitAdd((QilBinary)n),
            QilNodeType.Subtract => VisitSubtract((QilBinary)n),
            QilNodeType.Multiply => VisitMultiply((QilBinary)n),
            QilNodeType.Divide => VisitDivide((QilBinary)n),
            QilNodeType.Modulo => VisitModulo((QilBinary)n),
            QilNodeType.StrLength => VisitStrLength((QilUnary)n),
            QilNodeType.StrConcat => VisitStrConcat((QilStrConcat)n),
            QilNodeType.StrParseQName => VisitStrParseQName((QilBinary)n),
            QilNodeType.Ne => VisitNe((QilBinary)n),
            QilNodeType.Eq => VisitEq((QilBinary)n),
            QilNodeType.Gt => VisitGt((QilBinary)n),
            QilNodeType.Ge => VisitGe((QilBinary)n),
            QilNodeType.Lt => VisitLt((QilBinary)n),
            QilNodeType.Le => VisitLe((QilBinary)n),
            QilNodeType.Is => VisitIs((QilBinary)n),
            QilNodeType.After => VisitAfter((QilBinary)n),
            QilNodeType.Before => VisitBefore((QilBinary)n),
            QilNodeType.Loop => VisitLoop((QilLoop)n),
            QilNodeType.Filter => VisitFilter((QilLoop)n),
            QilNodeType.Sort => VisitSort((QilLoop)n),
            QilNodeType.SortKey => VisitSortKey((QilSortKey)n),
            QilNodeType.DocOrderDistinct => VisitDocOrderDistinct((QilUnary)n),
            QilNodeType.Function => VisitFunction((QilFunction)n),
            QilNodeType.Invoke => VisitInvoke((QilInvoke)n),
            QilNodeType.Content => VisitContent((QilUnary)n),
            QilNodeType.Attribute => VisitAttribute((QilBinary)n),
            QilNodeType.Parent => VisitParent((QilUnary)n),
            QilNodeType.Root => VisitRoot((QilUnary)n),
            QilNodeType.XmlContext => VisitXmlContext(n),
            QilNodeType.Descendant => VisitDescendant((QilUnary)n),
            QilNodeType.DescendantOrSelf => VisitDescendantOrSelf((QilUnary)n),
            QilNodeType.Ancestor => VisitAncestor((QilUnary)n),
            QilNodeType.AncestorOrSelf => VisitAncestorOrSelf((QilUnary)n),
            QilNodeType.Preceding => VisitPreceding((QilUnary)n),
            QilNodeType.FollowingSibling => VisitFollowingSibling((QilUnary)n),
            QilNodeType.PrecedingSibling => VisitPrecedingSibling((QilUnary)n),
            QilNodeType.NodeRange => VisitNodeRange((QilBinary)n),
            QilNodeType.Deref => VisitDeref((QilBinary)n),
            QilNodeType.ElementCtor => VisitElementCtor((QilBinary)n),
            QilNodeType.AttributeCtor => VisitAttributeCtor((QilBinary)n),
            QilNodeType.CommentCtor => VisitCommentCtor((QilUnary)n),
            QilNodeType.PICtor => VisitPICtor((QilBinary)n),
            QilNodeType.TextCtor => VisitTextCtor((QilUnary)n),
            QilNodeType.RawTextCtor => VisitRawTextCtor((QilUnary)n),
            QilNodeType.DocumentCtor => VisitDocumentCtor((QilUnary)n),
            QilNodeType.NamespaceDecl => VisitNamespaceDecl((QilBinary)n),
            QilNodeType.RtfCtor => VisitRtfCtor((QilBinary)n),
            QilNodeType.NameOf => VisitNameOf((QilUnary)n),
            QilNodeType.LocalNameOf => VisitLocalNameOf((QilUnary)n),
            QilNodeType.NamespaceUriOf => VisitNamespaceUriOf((QilUnary)n),
            QilNodeType.PrefixOf => VisitPrefixOf((QilUnary)n),
            QilNodeType.TypeAssert => VisitTypeAssert((QilTargetType)n),
            QilNodeType.IsType => VisitIsType((QilTargetType)n),
            QilNodeType.IsEmpty => VisitIsEmpty((QilUnary)n),
            QilNodeType.XPathNodeValue => VisitXPathNodeValue((QilUnary)n),
            QilNodeType.XPathFollowing => VisitXPathFollowing((QilUnary)n),
            QilNodeType.XPathPreceding => VisitXPathPreceding((QilUnary)n),
            QilNodeType.XPathNamespace => VisitXPathNamespace((QilUnary)n),
            QilNodeType.XsltGenerateId => VisitXsltGenerateId((QilUnary)n),
            QilNodeType.XsltInvokeLateBound => VisitXsltInvokeLateBound((QilInvokeLateBound)n),
            QilNodeType.XsltInvokeEarlyBound => VisitXsltInvokeEarlyBound((QilInvokeEarlyBound)n),
            QilNodeType.XsltCopy => VisitXsltCopy((QilBinary)n),
            QilNodeType.XsltCopyOf => VisitXsltCopyOf((QilUnary)n),
            QilNodeType.XsltConvert => VisitXsltConvert((QilTargetType)n),
            _ => VisitUnknown(n),
        };
    }
References System.Xml.Dictionary, System.Xml.Xsl.Qil.QilVisitor.VisitActualParameterList(), System.Xml.Xsl.Qil.QilVisitor.VisitAdd(), System.Xml.Xsl.Qil.QilVisitor.VisitAfter(), System.Xml.Xsl.Qil.QilVisitor.VisitAncestor(), System.Xml.Xsl.Qil.QilVisitor.VisitAncestorOrSelf(), System.Xml.Xsl.Qil.QilVisitor.VisitAnd(), System.Xml.Xsl.Qil.QilVisitor.VisitAttribute(), System.Xml.Xsl.Qil.QilVisitor.VisitAttributeCtor(), System.Xml.Xsl.Qil.QilVisitor.VisitAverage(), System.Xml.Xsl.Qil.QilVisitor.VisitBefore(), System.Xml.Xsl.Qil.QilVisitor.VisitBranchList(), System.Xml.Xsl.Qil.QilVisitor.VisitChoice(), System.Xml.Xsl.Qil.QilVisitor.VisitCommentCtor(), System.Xml.Xsl.Qil.QilVisitor.VisitConditional(), System.Xml.Xsl.Qil.QilVisitor.VisitContent(), System.Xml.Xsl.Qil.QilVisitor.VisitDataSource(), System.Xml.Xsl.Qil.QilVisitor.VisitDeref(), System.Xml.Xsl.Qil.QilVisitor.VisitDescendant(), System.Xml.Xsl.Qil.QilVisitor.VisitDescendantOrSelf(), System.Xml.Xsl.Qil.QilVisitor.VisitDifference(), System.Xml.Xsl.Qil.QilVisitor.VisitDivide(), System.Xml.Xsl.Qil.QilVisitor.VisitDocOrderDistinct(), System.Xml.Xsl.Qil.QilVisitor.VisitDocumentCtor(), System.Xml.Xsl.Qil.QilVisitor.VisitElementCtor(), System.Xml.Xsl.Qil.QilVisitor.VisitEq(), System.Xml.Xsl.Qil.QilVisitor.VisitError(), System.Xml.Xsl.Qil.QilVisitor.VisitFalse(), System.Xml.Xsl.Qil.QilVisitor.VisitFilter(), System.Xml.Xsl.Qil.QilVisitor.VisitFollowingSibling(), System.Xml.Xsl.Qil.QilVisitor.VisitFor(), System.Xml.Xsl.Qil.QilVisitor.VisitFormalParameterList(), System.Xml.Xsl.Qil.QilVisitor.VisitFunction(), System.Xml.Xsl.Qil.QilVisitor.VisitFunctionList(), System.Xml.Xsl.Qil.QilVisitor.VisitGe(), System.Xml.Xsl.Qil.QilVisitor.VisitGlobalParameterList(), System.Xml.Xsl.Qil.QilVisitor.VisitGlobalVariableList(), System.Xml.Xsl.Qil.QilVisitor.VisitGt(), System.Xml.Xsl.Qil.QilVisitor.VisitIntersection(), System.Xml.Xsl.Qil.QilVisitor.VisitInvoke(), System.Xml.Xsl.Qil.QilVisitor.VisitIs(), System.Xml.Xsl.Qil.QilVisitor.VisitIsEmpty(), System.Xml.Xsl.Qil.QilVisitor.VisitIsType(), System.Xml.Xsl.Qil.QilVisitor.VisitLe(), System.Xml.Xsl.Qil.QilVisitor.VisitLength(), System.Xml.Xsl.Qil.QilVisitor.VisitLet(), System.Xml.Xsl.Qil.QilVisitor.VisitLiteralDecimal(), System.Xml.Xsl.Qil.QilVisitor.VisitLiteralDouble(), System.Xml.Xsl.Qil.QilVisitor.VisitLiteralInt32(), System.Xml.Xsl.Qil.QilVisitor.VisitLiteralInt64(), System.Xml.Xsl.Qil.QilVisitor.VisitLiteralObject(), System.Xml.Xsl.Qil.QilVisitor.VisitLiteralQName(), System.Xml.Xsl.Qil.QilVisitor.VisitLiteralString(), System.Xml.Xsl.Qil.QilVisitor.VisitLiteralType(), System.Xml.Xsl.Qil.QilVisitor.VisitLocalNameOf(), System.Xml.Xsl.Qil.QilVisitor.VisitLoop(), System.Xml.Xsl.Qil.QilVisitor.VisitLt(), System.Xml.Xsl.Qil.QilVisitor.VisitMaximum(), System.Xml.Xsl.Qil.QilVisitor.VisitMinimum(), System.Xml.Xsl.Qil.QilVisitor.VisitModulo(), System.Xml.Xsl.Qil.QilVisitor.VisitMultiply(), System.Xml.Xsl.Qil.QilVisitor.VisitNameOf(), System.Xml.Xsl.Qil.QilVisitor.VisitNamespaceDecl(), System.Xml.Xsl.Qil.QilVisitor.VisitNamespaceUriOf(), System.Xml.Xsl.Qil.QilVisitor.VisitNe(), System.Xml.Xsl.Qil.QilVisitor.VisitNegate(), System.Xml.Xsl.Qil.QilVisitor.VisitNodeRange(), System.Xml.Xsl.Qil.QilVisitor.VisitNop(), System.Xml.Xsl.Qil.QilVisitor.VisitNot(), System.Xml.Xsl.Qil.QilVisitor.VisitNull(), System.Xml.Xsl.Qil.QilVisitor.VisitOptimizeBarrier(), System.Xml.Xsl.Qil.QilVisitor.VisitOr(), System.Xml.Xsl.Qil.QilVisitor.VisitParameter(), System.Xml.Xsl.Qil.QilVisitor.VisitParent(), System.Xml.Xsl.Qil.QilVisitor.VisitPICtor(), System.Xml.Xsl.Qil.QilVisitor.VisitPositionOf(), System.Xml.Xsl.Qil.QilVisitor.VisitPreceding(), System.Xml.Xsl.Qil.QilVisitor.VisitPrecedingSibling(), System.Xml.Xsl.Qil.QilVisitor.VisitPrefixOf(), System.Xml.Xsl.Qil.QilVisitor.VisitQilExpression(), System.Xml.Xsl.Qil.QilVisitor.VisitRawTextCtor(), System.Xml.Xsl.Qil.QilVisitor.VisitRoot(), System.Xml.Xsl.Qil.QilVisitor.VisitRtfCtor(), System.Xml.Xsl.Qil.QilVisitor.VisitSequence(), System.Xml.Xsl.Qil.QilVisitor.VisitSort(), System.Xml.Xsl.Qil.QilVisitor.VisitSortKey(), System.Xml.Xsl.Qil.QilVisitor.VisitSortKeyList(), System.Xml.Xsl.Qil.QilVisitor.VisitStrConcat(), System.Xml.Xsl.Qil.QilVisitor.VisitStrLength(), System.Xml.Xsl.Qil.QilVisitor.VisitStrParseQName(), System.Xml.Xsl.Qil.QilVisitor.VisitSubtract(), System.Xml.Xsl.Qil.QilVisitor.VisitSum(), System.Xml.Xsl.Qil.QilVisitor.VisitTextCtor(), System.Xml.Xsl.Qil.QilVisitor.VisitTrue(), System.Xml.Xsl.Qil.QilVisitor.VisitTypeAssert(), System.Xml.Xsl.Qil.QilVisitor.VisitUnion(), System.Xml.Xsl.Qil.QilVisitor.VisitUnknown(), System.Xml.Xsl.Qil.QilVisitor.VisitWarning(), System.Xml.Xsl.Qil.QilVisitor.VisitXmlContext(), System.Xml.Xsl.Qil.QilVisitor.VisitXPathFollowing(), System.Xml.Xsl.Qil.QilVisitor.VisitXPathNamespace(), System.Xml.Xsl.Qil.QilVisitor.VisitXPathNodeValue(), System.Xml.Xsl.Qil.QilVisitor.VisitXPathPreceding(), System.Xml.Xsl.Qil.QilVisitor.VisitXsltConvert(), System.Xml.Xsl.Qil.QilVisitor.VisitXsltCopy(), System.Xml.Xsl.Qil.QilVisitor.VisitXsltCopyOf(), System.Xml.Xsl.Qil.QilVisitor.VisitXsltGenerateId(), System.Xml.Xsl.Qil.QilVisitor.VisitXsltInvokeEarlyBound(), and System.Xml.Xsl.Qil.QilVisitor.VisitXsltInvokeLateBound().
Referenced by System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.EqualityIndexVisitor.Scan(), System.Xml.Xsl.Qil.QilVisitor.VisitAssumeReference(), System.Xml.Xsl.Qil.QilReplaceVisitor.VisitChildren(), and System.Xml.Xsl.Qil.QilVisitor.VisitChildren().