Terraria: System.Xml.Xsl.Qil.QilVisitor.VisitChildren
VisitChildren()
virtual QilNode System.Xml.Xsl.Qil.QilVisitor.VisitChildren (QilNode parent) inline protected virtual
Reimplemented in System.Xml.Xsl.IlGen.XmlILVisitor, System.Xml.Xsl.Qil.QilCloneVisitor, and System.Xml.Xsl.Qil.QilReplaceVisitor.
Definition at line 14 of file QilVisitor.cs.
    {
        for (int i = 0; i < parent.Count; i++)
        {
            if (IsReference(parent, i))
            {
                VisitReference(parent[i]);
            }
            else
            {
                Visit(parent[i]);
            }
        }
        return parent;
    }
References System.Xml.Xsl.Qil.QilNode.Count, System.Xml.Xsl.Qil.QilVisitor.IsReference(), System.Xml.Xsl.Qil.QilVisitor.Visit(), and System.Xml.Xsl.Qil.QilVisitor.VisitReference().
Referenced by System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.NodeFinder.Visit(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.NodeCounter.Visit(), System.Xml.Xsl.Qil.QilVisitor.VisitActualParameterList(), System.Xml.Xsl.Qil.QilVisitor.VisitAdd(), System.Xml.Xsl.Qil.QilVisitor.VisitAfter(), System.Xml.Xsl.Qil.QilVisitor.VisitAncestor(), System.Xml.Xsl.Qil.QilVisitor.VisitAncestorOrSelf(), System.Xml.Xsl.Qil.QilVisitor.VisitAnd(), System.Xml.Xsl.Qil.QilVisitor.VisitAttribute(), System.Xml.Xsl.Qil.QilVisitor.VisitAttributeCtor(), System.Xml.Xsl.Qil.QilVisitor.VisitAverage(), System.Xml.Xsl.Qil.QilVisitor.VisitBefore(), System.Xml.Xsl.Qil.QilVisitor.VisitBranchList(), System.Xml.Xsl.Qil.QilVisitor.VisitChoice(), System.Xml.Xsl.Qil.QilVisitor.VisitCommentCtor(), System.Xml.Xsl.Qil.QilVisitor.VisitConditional(), System.Xml.Xsl.Qil.QilVisitor.VisitContent(), System.Xml.Xsl.Qil.QilVisitor.VisitDataSource(), System.Xml.Xsl.Qil.QilVisitor.VisitDeref(), System.Xml.Xsl.Qil.QilVisitor.VisitDescendant(), System.Xml.Xsl.Qil.QilVisitor.VisitDescendantOrSelf(), System.Xml.Xsl.Qil.QilVisitor.VisitDifference(), System.Xml.Xsl.Qil.QilVisitor.VisitDivide(), System.Xml.Xsl.Qil.QilVisitor.VisitDocOrderDistinct(), System.Xml.Xsl.Qil.QilVisitor.VisitDocumentCtor(), System.Xml.Xsl.Qil.QilVisitor.VisitElementCtor(), System.Xml.Xsl.Qil.QilVisitor.VisitEq(), System.Xml.Xsl.Qil.QilVisitor.VisitError(), System.Xml.Xsl.Qil.QilVisitor.VisitFalse(), System.Xml.Xsl.Qil.QilVisitor.VisitFilter(), System.Xml.Xsl.Qil.QilVisitor.VisitFollowingSibling(), System.Xml.Xsl.Qil.QilVisitor.VisitFor(), System.Xml.Xsl.Qil.QilVisitor.VisitFormalParameterList(), System.Xml.Xsl.Qil.QilVisitor.VisitFunction(), System.Xml.Xsl.Qil.QilVisitor.VisitFunctionList(), System.Xml.Xsl.Qil.QilVisitor.VisitGe(), System.Xml.Xsl.Qil.QilVisitor.VisitGlobalParameterList(), System.Xml.Xsl.Qil.QilVisitor.VisitGlobalVariableList(), System.Xml.Xsl.Qil.QilVisitor.VisitGt(), System.Xml.Xsl.Qil.QilVisitor.VisitIntersection(), System.Xml.Xsl.Qil.QilVisitor.VisitInvoke(), System.Xml.Xsl.Qil.QilVisitor.VisitIs(), System.Xml.Xsl.Qil.QilVisitor.VisitIsEmpty(), System.Xml.Xsl.Qil.QilVisitor.VisitIsType(), System.Xml.Xsl.Qil.QilVisitor.VisitLe(), System.Xml.Xsl.Qil.QilVisitor.VisitLength(), System.Xml.Xsl.Qil.QilVisitor.VisitLet(), System.Xml.Xsl.Qil.QilVisitor.VisitLiteralDecimal(), System.Xml.Xsl.Qil.QilVisitor.VisitLiteralDouble(), System.Xml.Xsl.Qil.QilVisitor.VisitLiteralInt32(), System.Xml.Xsl.Qil.QilVisitor.VisitLiteralInt64(), System.Xml.Xsl.Qil.QilVisitor.VisitLiteralObject(), System.Xml.Xsl.Qil.QilVisitor.VisitLiteralQName(), System.Xml.Xsl.Qil.QilVisitor.VisitLiteralString(), System.Xml.Xsl.Qil.QilVisitor.VisitLiteralType(), System.Xml.Xsl.Qil.QilVisitor.VisitLocalNameOf(), System.Xml.Xsl.Qil.QilVisitor.VisitLoop(), System.Xml.Xsl.Qil.QilVisitor.VisitLt(), System.Xml.Xsl.Qil.QilVisitor.VisitMaximum(), System.Xml.Xsl.Qil.QilVisitor.VisitMinimum(), System.Xml.Xsl.Qil.QilVisitor.VisitModulo(), System.Xml.Xsl.Qil.QilVisitor.VisitMultiply(), System.Xml.Xsl.Qil.QilVisitor.VisitNameOf(), System.Xml.Xsl.Qil.QilVisitor.VisitNamespaceDecl(), System.Xml.Xsl.Qil.QilVisitor.VisitNamespaceUriOf(), System.Xml.Xsl.Qil.QilVisitor.VisitNe(), System.Xml.Xsl.Qil.QilVisitor.VisitNegate(), System.Xml.Xsl.Qil.QilVisitor.VisitNodeRange(), System.Xml.Xsl.Qil.QilVisitor.VisitNop(), System.Xml.Xsl.Qil.QilVisitor.VisitNot(), System.Xml.Xsl.Qil.QilVisitor.VisitOptimizeBarrier(), System.Xml.Xsl.Qil.QilVisitor.VisitOr(), System.Xml.Xsl.Qil.QilVisitor.VisitParameter(), System.Xml.Xsl.Qil.QilVisitor.VisitParent(), System.Xml.Xsl.Qil.QilVisitor.VisitPICtor(), System.Xml.Xsl.Qil.QilVisitor.VisitPositionOf(), System.Xml.Xsl.Qil.QilVisitor.VisitPreceding(), System.Xml.Xsl.Qil.QilVisitor.VisitPrecedingSibling(), System.Xml.Xsl.Qil.QilVisitor.VisitPrefixOf(), System.Xml.Xsl.Qil.QilVisitor.VisitQilExpression(), System.Xml.Xsl.Qil.QilVisitor.VisitRawTextCtor(), System.Xml.Xsl.Qil.QilVisitor.VisitRoot(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.EqualityIndexVisitor.VisitRoot(), System.Xml.Xsl.Qil.QilVisitor.VisitRtfCtor(), System.Xml.Xsl.Qil.QilVisitor.VisitSequence(), System.Xml.Xsl.Qil.QilVisitor.VisitSort(), System.Xml.Xsl.Qil.QilVisitor.VisitSortKey(), System.Xml.Xsl.Qil.QilVisitor.VisitSortKeyList(), System.Xml.Xsl.Qil.QilVisitor.VisitStrConcat(), System.Xml.Xsl.Qil.QilVisitor.VisitStrLength(), System.Xml.Xsl.Qil.QilVisitor.VisitStrParseQName(), System.Xml.Xsl.Qil.QilVisitor.VisitSubtract(), System.Xml.Xsl.Qil.QilVisitor.VisitSum(), System.Xml.Xsl.Qil.QilVisitor.VisitTextCtor(), System.Xml.Xsl.Qil.QilVisitor.VisitTrue(), System.Xml.Xsl.Qil.QilVisitor.VisitTypeAssert(), System.Xml.Xsl.Qil.QilVisitor.VisitUnion(), System.Xml.Xsl.Qil.QilVisitor.VisitUnknown(), System.Xml.Xsl.Qil.QilVisitor.VisitWarning(), System.Xml.Xsl.Qil.QilVisitor.VisitXmlContext(), System.Xml.Xsl.Qil.QilVisitor.VisitXPathFollowing(), System.Xml.Xsl.Qil.QilVisitor.VisitXPathNamespace(), System.Xml.Xsl.Qil.QilVisitor.VisitXPathNodeValue(), System.Xml.Xsl.Qil.QilVisitor.VisitXPathPreceding(), System.Xml.Xsl.Qil.QilVisitor.VisitXsltConvert(), System.Xml.Xsl.Qil.QilVisitor.VisitXsltCopy(), System.Xml.Xsl.Qil.QilVisitor.VisitXsltCopyOf(), System.Xml.Xsl.Qil.QilVisitor.VisitXsltGenerateId(), System.Xml.Xsl.Qil.QilVisitor.VisitXsltInvokeEarlyBound(), and System.Xml.Xsl.Qil.QilVisitor.VisitXsltInvokeLateBound().