Terraria: System.IO.Compression.ZipEndOfCentralDirectoryBlock.TryReadBlock
TryReadBlock()
static bool System.IO.Compression.ZipEndOfCentralDirectoryBlock.TryReadBlock (BinaryReader reader, out ZipEndOfCentralDirectoryBlock eocdBlock) inline static
Definition at line 41 of file ZipEndOfCentralDirectoryBlock.cs.
    {
        eocdBlock = default(ZipEndOfCentralDirectoryBlock);
        if (reader.ReadUInt32() != 101010256)
        {
            return false;
        }
        eocdBlock.Signature = 101010256u;
        eocdBlock.NumberOfThisDisk = reader.ReadUInt16();
        eocdBlock.NumberOfTheDiskWithTheStartOfTheCentralDirectory = reader.ReadUInt16();
        eocdBlock.NumberOfEntriesInTheCentralDirectoryOnThisDisk = reader.ReadUInt16();
        eocdBlock.NumberOfEntriesInTheCentralDirectory = reader.ReadUInt16();
        eocdBlock.SizeOfCentralDirectory = reader.ReadUInt32();
        eocdBlock.OffsetOfStartOfCentralDirectoryWithRespectToTheStartingDiskNumber = reader.ReadUInt32();
        ushort count = reader.ReadUInt16();
        eocdBlock.ArchiveComment = reader.ReadBytes(count);
        return true;
    }
References System.count, System.IO.BinaryReader.ReadBytes(), System.IO.BinaryReader.ReadUInt16(), and System.IO.BinaryReader.ReadUInt32().
Referenced by System.IO.Compression.ZipArchive.ReadEndOfCentralDirectory().