Terraria: System.Runtime.Serialization.Json.JsonXmlDataContract.WriteJsonValueCore
WriteJsonValueCore()
override void System.Runtime.Serialization.Json.JsonXmlDataContract.WriteJsonValueCore (XmlWriterDelegator jsonWriter, object obj, XmlObjectSerializerWriteContextComplexJson context, RuntimeTypeHandle declaredTypeHandle) inline virtual
Reimplemented from System.Runtime.Serialization.Json.JsonDataContract.
Definition at line 30 of file JsonXmlDataContract.cs.
    {
        DataContractSerializer dataContractSerializer = new DataContractSerializer(Type.GetTypeFromHandle(declaredTypeHandle), GetKnownTypesFromContext(context, context?.SerializerKnownTypeList), 1, ignoreExtensionDataObject: false, preserveObjectReferences: false);
        MemoryStream memoryStream = new MemoryStream();
        dataContractSerializer.WriteObject(memoryStream, obj);
        memoryStream.Position = 0L;
        string value = new StreamReader(memoryStream).ReadToEnd();
        jsonWriter.WriteString(value);
    }
References System.Runtime.Serialization.Dictionary, System.Runtime.Serialization.Json.JsonXmlDataContract.GetKnownTypesFromContext(), System.Type.GetTypeFromHandle(), System.L, System.obj, System.IO.StreamReader.ReadToEnd(), and System.value.