Terraria: System.Runtime.Serialization.Json.JsonXmlDataContract.ReadJsonValueCore
ReadJsonValueCore()
override object System.Runtime.Serialization.Json.JsonXmlDataContract.ReadJsonValueCore (XmlReaderDelegator jsonReader, XmlObjectSerializerReadContextComplexJson context) inline virtual
Reimplemented from System.Runtime.Serialization.Json.JsonDataContract.
Definition at line 18 of file JsonXmlDataContract.cs.
    {
        string s = jsonReader.ReadElementContentAsString();
        DataContractSerializer dataContractSerializer = new DataContractSerializer(base.TraditionalDataContract.UnderlyingType, GetKnownTypesFromContext(context, context?.SerializerKnownTypeList), 1, ignoreExtensionDataObject: false, preserveObjectReferences: false);
        MemoryStream stream = new MemoryStream(Encoding.UTF8.GetBytes(s));
        XmlDictionaryReaderQuotas readerQuotas = ((JsonReaderDelegator)jsonReader).ReaderQuotas;
        object obj = ((readerQuotas != null) ? dataContractSerializer.ReadObject(XmlDictionaryReader.CreateTextReader(stream, readerQuotas)) : dataContractSerializer.ReadObject(stream));
        context?.AddNewObject(obj);
        return obj;
    }
References System.Runtime.Serialization.XmlObjectSerializerReadContext.AddNewObject(), System.Xml.XmlDictionaryReader.CreateTextReader(), System.Runtime.Serialization.Json.JsonXmlDataContract.GetKnownTypesFromContext(), System.obj, System.s, System.stream, and System.Text.Encoding.UTF8.