Terraria: Terraria.GameContent.RGB.UnderworldShader.ProcessLowDetail
ProcessLowDetail()
void Terraria.GameContent.RGB.UnderworldShader.ProcessLowDetail (RgbDevice device, Fragment fragment, EffectDetailLevel quality, float time) inline private
Definition at line 23 of file UnderworldShader.cs.
    {
        for (int i = 0; i < fragment.Count; i++)
        {
            Vector2 canvasPositionOfIndex = fragment.GetCanvasPositionOfIndex(i);
            Vector4 vector = Vector4.Lerp(_backColor, _frontColor, (float)Math.Sin(time * _speed + canvasPositionOfIndex.X) * 0.5f + 0.5f);
            fragment.SetColor(i, vector);
        }
    }
References Terraria.GameContent.RGB.UnderworldShader._backColor, Terraria.GameContent.RGB.UnderworldShader._frontColor, Terraria.GameContent.RGB.UnderworldShader._speed, ReLogic.Peripherals.RGB.Fragment.Count, ReLogic.Peripherals.RGB.Fragment.GetCanvasPositionOfIndex(), Microsoft.Xna.Framework.Vector4.Lerp(), ReLogic.Peripherals.RGB.Fragment.SetColor(), System.Math.Sin(), and Microsoft.Xna.Framework.Vector2.X.