Terraria: System.Runtime.Serialization.PrimitiveDataContract.TryReadNullAtTopLevel
TryReadNullAtTopLevel()
bool System.Runtime.Serialization.PrimitiveDataContract.TryReadNullAtTopLevel (XmlReaderDelegator reader) inline protected inherited
Definition at line 182 of file PrimitiveDataContract.cs.
    {
        Attributes attributes = new Attributes();
        attributes.Read(reader);
        if (attributes.Ref != Globals.NewObjectId)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(XmlObjectSerializer.CreateSerializationException(System.SR.Format(System.SR.CannotDeserializeRefAtTopLevel, attributes.Ref)));
        }
        if (attributes.XsiNil)
        {
            reader.Skip();
            return true;
        }
        return false;
    }
References System.SR.CannotDeserializeRefAtTopLevel, System.Runtime.Serialization.XmlObjectSerializer.CreateSerializationException(), System.SR.Format(), System.Runtime.Serialization.Globals.NewObjectId, System.Runtime.Serialization.Attributes.Read(), System.Runtime.Serialization.Attributes.Ref, System.Runtime.Serialization.XmlReaderDelegator.Skip(), System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperError(), and System.Runtime.Serialization.Attributes.XsiNil.
Referenced by System.Runtime.Serialization.ByteArrayDataContract.ReadXmlValue(), System.Runtime.Serialization.QNameDataContract.ReadXmlValue(), System.Runtime.Serialization.StringDataContract.ReadXmlValue(), and System.Runtime.Serialization.UriDataContract.ReadXmlValue().