Terraria: System.Runtime.Serialization.PrimitiveDataContract.GetPrimitiveDataContract
GetPrimitiveDataContract() [2/2]
static PrimitiveDataContract System.Runtime.Serialization.PrimitiveDataContract.GetPrimitiveDataContract (Type type) inline static package inherited
Definition at line 159 of file PrimitiveDataContract.cs.
    {
        return DataContract.GetBuiltInDataContract(type) as PrimitiveDataContract;
    }
References System.Runtime.Serialization.PrimitiveDataContract.PrimitiveDataContract(), System.Runtime.Serialization.Dictionary, System.Runtime.Serialization.DataContract.GetBuiltInDataContract(), and System.type.
Referenced by System.Runtime.Serialization.ReflectionReader.GetReflectionReadValueDelegate(), System.Runtime.Serialization.XmlObjectSerializer.IsRootElement(), System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.ReadValue(), System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.ReadValue(), System.Runtime.Serialization.ReflectionReader.ReflectionReadValue(), System.Runtime.Serialization.ReflectionReader.ReflectionTryReadPrimitiveArray(), System.Runtime.Serialization.Json.ReflectionJsonFormatWriter.ReflectionTryWritePrimitiveArray(), System.Runtime.Serialization.ReflectionXmlFormatWriter.ReflectionTryWritePrimitiveArray(), System.Runtime.Serialization.ReflectionXmlFormatWriter.ReflectionWriteCollection(), System.Runtime.Serialization.Json.ReflectionJsonFormatWriter.ReflectionWriteCollection(), System.Runtime.Serialization.ReflectionClassWriter.ReflectionWriteValue(), System.Runtime.Serialization.XmlObjectSerializerContext.ResolveDataContractFromKnownTypes(), System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.TryReadPrimitiveArray(), System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.TryReadPrimitiveArray(), System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper.TryWritePrimitive(), System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper.TryWritePrimitive(), System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper.TryWritePrimitiveArray(), System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper.TryWritePrimitiveArray(), System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper.WriteValue(), and System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper.WriteValue().