Terraria: System.Formats.Asn1.AsnValueReader.ReadSequence
ReadSequence() [1/3]
AsnValueReader System.Formats.Asn1.AsnValueReader.ReadSequence (Asn1Tag? expectedTag = null) inline package
Definition at line 112 of file AsnValueReader.cs.
    {
        AsnDecoder.ReadSequence(_span, _ruleSet, out var contentOffset, out var contentLength, out var bytesConsumed, expectedTag);
        ReadOnlySpan<byte> span = _span.Slice(contentOffset, contentLength);
        _span = _span.Slice(bytesConsumed);
        return new AsnValueReader(span, _ruleSet);
    }
References System.Formats.Asn1.AsnValueReader.AsnValueReader(), System.Formats.Asn1.AsnValueReader._ruleSet, System.Formats.Asn1.AsnValueReader._span, System.Formats.Asn1.AsnDecoder.ReadSequence(), and System.ReadOnlySpan< T >.Slice().
Referenced by Internal.Cryptography.AsymmetricAlgorithmHelpers.ConvertDerToIeee1363(), System.Security.Cryptography.Asn1.AlgorithmIdentifierAsn.DecodeCore(), System.Security.Cryptography.Asn1.CurveAsn.DecodeCore(), System.Security.Cryptography.Asn1.DssParms.DecodeCore(), System.Security.Cryptography.Asn1.ECPrivateKey.DecodeCore(), System.Security.Cryptography.Asn1.EncryptedPrivateKeyInfoAsn.DecodeCore(), System.Security.Cryptography.Asn1.FieldID.DecodeCore(), System.Security.Cryptography.Asn1.PBEParameter.DecodeCore(), System.Security.Cryptography.Asn1.PBES2Params.DecodeCore(), System.Security.Cryptography.Asn1.Pbkdf2Params.DecodeCore(), System.Security.Cryptography.Asn1.Rc2CbcParameters.DecodeCore(), System.Security.Cryptography.Asn1.RSAPrivateKeyAsn.DecodeCore(), System.Security.Cryptography.Asn1.RSAPublicKeyAsn.DecodeCore(), System.Security.Cryptography.Asn1.SpecifiedECDomain.DecodeCore(), System.Security.Cryptography.Asn1.SubjectPublicKeyInfoAsn.DecodeCore(), System.Security.Cryptography.X509Certificates.Asn1.CertificateAsn.DecodeCore(), System.Security.Cryptography.Asn1.AlgorithmIdentifierAsn.DecodeCore(), System.Security.Cryptography.Asn1.CurveAsn.DecodeCore(), System.Security.Cryptography.Asn1.ECPrivateKey.DecodeCore(), System.Security.Cryptography.Asn1.EncryptedPrivateKeyInfoAsn.DecodeCore(), System.Security.Cryptography.Asn1.FieldID.DecodeCore(), System.Security.Cryptography.Asn1.PBEParameter.DecodeCore(), System.Security.Cryptography.Asn1.PBES2Params.DecodeCore(), System.Security.Cryptography.Asn1.Pbkdf2Params.DecodeCore(), System.Security.Cryptography.Asn1.Rc2CbcParameters.DecodeCore(), System.Security.Cryptography.Asn1.SpecifiedECDomain.DecodeCore(), System.Security.Cryptography.Asn1.SubjectPublicKeyInfoAsn.DecodeCore(), System.Security.Cryptography.X509Certificates.Asn1.ValidityAsn.DecodeCore(), and System.Security.Cryptography.Asn1.X509ExtensionAsn.DecodeCore().