Terraria: System.Net.WebRequest.GetRequestStream
GetRequestStream()
virtual Stream System.Net.WebRequest.GetRequestStream () inline virtual
Reimplemented in System.Net.FileWebRequest, System.Net.FtpWebRequest, and System.Net.HttpWebRequest.
Definition at line 369 of file WebRequest.cs.
    {
        throw System.NotImplemented.ByDesignWithMessage(System.SR.net_MethodNotImplementedException);
    }
References System.NotImplemented.ByDesignWithMessage(), and System.SR.net_MethodNotImplementedException.
Referenced by System.Net.WebClient.OpenWrite(), and System.Net.WebClient.UploadBits().