Terraria: System.Threading.LowLevelSpinWaiter.SpinWaitForCondition
SpinWaitForCondition()
bool System.Threading.LowLevelSpinWaiter.SpinWaitForCondition (Func< bool > condition, int spinCount, int sleep0Threshold) inline
Definition at line 7 of file LowLevelSpinWaiter.cs.
    {
        int processorCount = Environment.ProcessorCount;
        int num = Interlocked.Increment(ref _spinningThreadCount);
        try
        {
            if (num <= processorCount)
            {
                for (int i = ((processorCount <= 1) ? sleep0Threshold : 0); i < spinCount; i++)
                {
                    Wait(i, sleep0Threshold, processorCount);
                    if (condition())
                    {
                        return true;
                    }
                }
            }
        }
        finally
        {
            Interlocked.Decrement(ref _spinningThreadCount);
        }
        return false;
    }
References System.Threading.LowLevelSpinWaiter._spinningThreadCount, System.Threading.Interlocked.Decrement(), System.Threading.Interlocked.Increment(), System.Environment.ProcessorCount, and System.Threading.LowLevelSpinWaiter.Wait().
Referenced by System.Threading.LowLevelLock.WaitAndAcquire().