Terraria: System.Threading.LowLevelSpinWaiter.Wait
Wait()
static void System.Threading.LowLevelSpinWaiter.Wait (int spinIndex, int sleep0Threshold, int processorCount) inline static
Definition at line 32 of file LowLevelSpinWaiter.cs.
    {
        if (processorCount > 1 && (spinIndex < sleep0Threshold || (spinIndex - sleep0Threshold) % 2 != 0))
        {
            int num = Thread.OptimalMaxSpinWaitsPerSpinIteration;
            if (spinIndex <= 30 && 1 << spinIndex < num)
            {
                num = 1 << spinIndex;
            }
            Thread.SpinWait(num);
        }
        else
        {
            Thread.UninterruptibleSleep0();
        }
    }
References System.Threading.Thread.OptimalMaxSpinWaitsPerSpinIteration, System.Threading.Thread.SpinWait(), and System.Threading.Thread.UninterruptibleSleep0().
Referenced by System.Threading.LowLevelSpinWaiter.SpinWaitForCondition(), and System.Threading.LowLevelLifoSemaphore.Wait().