Terraria: System.Xml.Schema.XmlSchemaObject.Clone
Clone()
virtual XmlSchemaObject System.Xml.Schema.XmlSchemaObject.Clone () inline package virtual inherited
Reimplemented in System.Xml.Schema.XmlSchema, System.Xml.Schema.XmlSchemaAttribute, System.Xml.Schema.XmlSchemaAttributeGroup, System.Xml.Schema.XmlSchemaComplexType, System.Xml.Schema.XmlSchemaElement, System.Xml.Schema.XmlSchemaGroup, System.Xml.Schema.XmlSchemaSimpleType, System.Xml.Schema.XmlSchemaSimpleTypeList, System.Xml.Schema.XmlSchemaSimpleTypeRestriction, and System.Xml.Schema.XmlSchemaSimpleTypeUnion.
Definition at line 145 of file XmlSchemaObject.cs.
    {
        return (XmlSchemaObject)MemberwiseClone();
    }
Referenced by System.Xml.Schema.XmlSchemaSimpleType.Clone(), System.Xml.Schema.XmlSchemaComplexType.Clone(), System.Xml.Schema.XmlSchemaComplexType.CloneAttributes(), and System.Xml.Schema.XmlSchemaComplexType.CloneParticle().