Terraria: System.Data.SqlTypes.SqlXml.CreateMemoryStreamFromXmlReader
CreateMemoryStreamFromXmlReader()
Stream System.Data.SqlTypes.SqlXml.CreateMemoryStreamFromXmlReader (XmlReader reader) inline private
Definition at line 163 of file SqlXml.cs.
    {
        XmlWriterSettings xmlWriterSettings = new XmlWriterSettings();
        xmlWriterSettings.CloseOutput = false;
        xmlWriterSettings.ConformanceLevel = ConformanceLevel.Fragment;
        xmlWriterSettings.Encoding = Encoding.GetEncoding("utf-16");
        xmlWriterSettings.OmitXmlDeclaration = true;
        MemoryStream memoryStream = new MemoryStream();
        XmlWriter xmlWriter = XmlWriter.Create(memoryStream, xmlWriterSettings);
        if (reader.ReadState == ReadState.Closed)
        {
            throw new InvalidOperationException(SQLResource.ClosedXmlReaderMessage);
        }
        if (reader.ReadState == ReadState.Initial)
        {
            reader.Read();
        }
        while (!reader.EOF)
        {
            xmlWriter.WriteNode(reader, defattr: true);
        }
        xmlWriter.Flush();
        memoryStream.Seek(0L, SeekOrigin.Begin);
        return memoryStream;
    }
References System.Data.SqlTypes.SQLResource.ClosedXmlReaderMessage, System.Xml.XmlWriter.Create(), System.Xml.Dictionary, System.Xml.XmlReader.EOF, System.Text.Encoding.GetEncoding(), System.L, System.Xml.XmlReader.Read(), and System.Xml.XmlReader.ReadState.
Referenced by System.Data.SqlTypes.SqlXml.SqlXml().