Terraria: System.Data.SqlTypes.SqlXml.ReadXml
ReadXml()
void IXmlSerializable. System.Data.SqlTypes.SqlXml.ReadXml (XmlReader r) inline private
Implements System.Xml.Serialization.IXmlSerializable.
Definition at line 194 of file SqlXml.cs.
    {
        string attribute = r.GetAttribute("nil", "http://www.w3.org/2001/XMLSchema-instance");
        if (attribute != null && XmlConvert.ToBoolean(attribute))
        {
            r.ReadInnerXml();
            SetNull();
            return;
        }
        _fNotNull = true;
        _firstCreateReader = true;
        _stream = new MemoryStream();
        StreamWriter streamWriter = new StreamWriter(_stream);
        streamWriter.Write(r.ReadInnerXml());
        streamWriter.Flush();
        if (_stream.CanSeek)
        {
            _stream.Seek(0L, SeekOrigin.Begin);
        }
    }
References System.Data.SqlTypes.SqlXml._firstCreateReader, System.Data.SqlTypes.SqlXml._fNotNull, System.Data.SqlTypes.SqlXml._stream, System.IO.Stream.CanSeek, System.Xml.Dictionary, System.L, System.IO.Stream.Seek(), System.Data.SqlTypes.SqlXml.SetNull(), and System.Xml.XmlConvert.ToBoolean().