Terraria: Terraria.GameContent.Biomes.GraniteBiome.SimulatePressure
SimulatePressure()
void Terraria.GameContent.Biomes.GraniteBiome.SimulatePressure (out Rectangle effectedMapArea) inline private
    {
        //IL_0072: Unknown result type (might be due to invalid IL or missing references)
        //IL_0077: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a4: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a9: Unknown result type (might be due to invalid IL or missing references)
        //IL_0157: Unknown result type (might be due to invalid IL or missing references)
        //IL_015b: Unknown result type (might be due to invalid IL or missing references)
        //IL_015d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0162: Unknown result type (might be due to invalid IL or missing references)
        //IL_0167: Unknown result type (might be due to invalid IL or missing references)
        int length = _sourceMagmaMap.GetLength(0);
        int length2 = _sourceMagmaMap.GetLength(1);
        int num = length / 2;
        int num2 = length2 / 2;
        int num3 = num;
        int num4 = num3;
        int num5 = num2;
        int num6 = num5;
        for (int i = 0; i < 300; i++)
        {
            for (int j = num3; j <= num4; j++)
            {
                for (int k = num5; k <= num6; k++)
                {
                    Magma magma = _sourceMagmaMap[j, k];
                    if (!magma.IsActive)
                    {
                        continue;
                    }
                    double num7 = 0.0;
                    Vector2D val = Vector2D.Zero;
                    for (int l = -1; l <= 1; l++)
                    {
                        for (int m = -1; m <= 1; m++)
{
                            if (l == 0 && m == 0)
{
                                continue;
                            }
                            Vector2D val2 = _normalisedVectors[(l + 1) * 3 + (m + 1)];
                            Magma magma2 = _sourceMagmaMap[j + l, k + m];
                            if (magma.Pressure > 0.01 && !magma2.IsActive)
{
                                if (l == -1)
{
                                    num3 = Utils.Clamp(j + l, 1, num3);
                                }
                                else
{
                                    num4 = Utils.Clamp(j + l, num4, length - 2);
                                }
                                if (m == -1)
{
                                    num5 = Utils.Clamp(k + m, 1, num5);
                                }
                                else
{
                                    num6 = Utils.Clamp(k + m, num6, length2 - 2);
                                }
                                _targetMagmaMap[j + l, k + m] = magma2.ToFlow();
                            }
                            double pressure = magma2.Pressure;
                            num7 += pressure;
                            val += pressure * val2;
                        }
                    }
                    num7 /= 8.0;
                    if (num7 > magma.Resistance)
                    {
                        double num8 = ((Vector2D)(ref val)).Length() / 8.0;
                        double val3 = Math.Max(num7 - num8 - magma.Pressure, 0.0) + num8 + magma.Pressure * 0.875 - magma.Resistance;
                        val3 = Math.Max(0.0, val3);
                        _targetMagmaMap[j, k] = Magma.CreateFlow(val3, Math.Max(0.0, magma.Resistance - val3 * 0.02));
                    }
                }
            }
            if (i < 2)
            {
                _targetMagmaMap[num, num2] = Magma.CreateFlow(25.0);
            }
            Utils.Swap(ref _sourceMagmaMap, ref _targetMagmaMap);
        }
        effectedMapArea = new Rectangle(num3, num5, num4 - num3 + 1, num6 - num5 + 1);
    }
References Terraria.GameContent.Biomes.GraniteBiome._normalisedVectors, Terraria.GameContent.Biomes.GraniteBiome._sourceMagmaMap, Terraria.GameContent.Biomes.GraniteBiome._targetMagmaMap, Terraria.GameContent.Biomes.GraniteBiome.Magma.CreateFlow(), Terraria.GameContent.Biomes.GraniteBiome.Magma.IsActive, Terraria.GameContent.Biomes.GraniteBiome.Magma.Pressure, Terraria.GameContent.Biomes.GraniteBiome.Magma.Resistance, Terraria.GameContent.Biomes.GraniteBiome.Magma.ToFlow(), and ReLogic.Utilities.Vector2D.Zero.
Referenced by Terraria.GameContent.Biomes.GraniteBiome.Place().