Terraria: Terraria.GameContent.Biomes.GraniteBiome.Place
Place()
override bool Terraria.GameContent.Biomes.GraniteBiome.Place (Point origin, StructureMap structures) inline
    {
        if (GenBase._tiles[origin.X, origin.Y].active())
        {
            return false;
        }
        origin.X -= _sourceMagmaMap.GetLength(0) / 2;
        origin.Y -= _sourceMagmaMap.GetLength(1) / 2;
        BuildMagmaMap(origin);
        SimulatePressure(out var effectedMapArea);
        PlaceGranite(origin, effectedMapArea);
        CleanupTiles(origin, effectedMapArea);
        PlaceDecorations(origin, effectedMapArea);
        structures.AddStructure(effectedMapArea, 8);
        return true;
    }
References Terraria.GameContent.Biomes.GraniteBiome._sourceMagmaMap, Terraria.WorldBuilding.GenBase._tiles, Terraria.Tile.active(), Terraria.WorldBuilding.StructureMap.AddStructure(), Terraria.GameContent.Biomes.GraniteBiome.BuildMagmaMap(), Terraria.GameContent.Biomes.GraniteBiome.CleanupTiles(), Terraria.GameContent.Biomes.GraniteBiome.PlaceDecorations(), Terraria.GameContent.Biomes.GraniteBiome.PlaceGranite(), and Terraria.GameContent.Biomes.GraniteBiome.SimulatePressure().
Referenced by Terraria.WorldGen.GenerateWorld().