Terraria: MS.Internal.Xml.Cache.XPathDocumentBuilder.WriteNamespaceDeclaration
WriteNamespaceDeclaration()
override void MS.Internal.Xml.Cache.XPathDocumentBuilder.WriteNamespaceDeclaration (string prefix, string namespaceName) inline package
Definition at line 421 of file XPathDocumentBuilder.cs.
    {
        if (_atomizeNames)
        {
            prefix = _nameTable.Add(prefix);
        }
        namespaceName = _nameTable.Add(namespaceName);
        XPathNode[] pageNode = _pageNmsp;
        int num = _idxNmsp;
        while (num != 0 && (object)pageNode[num].LocalName != prefix)
        {
            num = pageNode[num].GetSibling(out pageNode);
        }
        XPathNode[] page;
        int num2 = NewNamespaceNode(out page, prefix, namespaceName, _pageParent, _idxParent);
        if (num != 0)
        {
            XPathNode[] pageNode2 = _pageNmsp;
            int num3 = _idxNmsp;
            XPathNode[] array = page;
            int num4 = num2;
            while (num3 != num || pageNode2 != pageNode)
            {
                int parent = pageNode2[num3].GetParent(out var pageNode3);
                parent = NewNamespaceNode(out pageNode3, pageNode2[num3].LocalName, pageNode2[num3].Value, pageNode3, parent);
                array[num4].SetSibling(_infoTable, pageNode3, parent);
                array = pageNode3;
                num4 = parent;
                num3 = pageNode2[num3].GetSibling(out pageNode2);
            }
            num = pageNode[num].GetSibling(out pageNode);
            if (num != 0)
            {
                array[num4].SetSibling(_infoTable, pageNode, num);
            }
        }
        else if (_idxParent != 0)
        {
            page[num2].SetSibling(_infoTable, _pageNmsp, _idxNmsp);
        }
        else
        {
            _doc.SetRootNode(page, num2);
        }
        if (_idxParent != 0)
        {
            if (!_pageParent[_idxParent].HasNamespaceDecls)
            {
                _stkNmsp.Push(new XPathNodeRef(_pageNmsp, _idxNmsp));
                _pageParent[_idxParent].HasNamespaceDecls = true;
            }
            _pageNmsp = page;
            _idxNmsp = num2;
        }
    }
References MS.Internal.Xml.Cache.XPathDocumentBuilder._atomizeNames, MS.Internal.Xml.Cache.XPathDocumentBuilder._doc, MS.Internal.Xml.Cache.XPathDocumentBuilder._idxNmsp, MS.Internal.Xml.Cache.XPathDocumentBuilder._idxParent, MS.Internal.Xml.Cache.XPathDocumentBuilder._infoTable, MS.Internal.Xml.Cache.XPathDocumentBuilder._nameTable, MS.Internal.Xml.Cache.XPathDocumentBuilder._pageNmsp, MS.Internal.Xml.Cache.XPathDocumentBuilder._pageParent, MS.Internal.Xml.Cache.XPathDocumentBuilder._stkNmsp, System.Xml.XmlNameTable.Add(), System.array, System.Xml.Dictionary, MS.Internal.Xml.Cache.XPathNode.HasNamespaceDecls, MS.Internal.Xml.Cache.XPathDocumentBuilder.NewNamespaceNode(), System.prefix, and System.Xml.XPath.XPathDocument.SetRootNode().