Terraria: MS.Internal.Xml.Cache.XPathDocumentBuilder.NewNode
NewNode()
int MS.Internal.Xml.Cache.XPathDocumentBuilder.NewNode (out XPathNode[] page, XPathNodeType xptyp, string localName, string namespaceUri, string prefix, string baseUri) inline private
Definition at line 511 of file XPathDocumentBuilder.cs.
    {
        _nodePageFact.AllocateSlot(out var page2, out var idx);
        ComputeLineInfo(XPathNavigator.IsText(xptyp), out var lineNumOffset, out var linePosOffset);
        XPathNodeInfoAtom info = _infoTable.Create(localName, namespaceUri, prefix, baseUri, _pageParent, page2, page2, _doc, _lineNumBase, _linePosBase);
        page2[idx].Create(info, xptyp, _idxParent);
        page2[idx].SetLineInfoOffsets(lineNumOffset, linePosOffset);
        page = page2;
        return idx;
    }
References MS.Internal.Xml.Cache.XPathDocumentBuilder._doc, MS.Internal.Xml.Cache.XPathDocumentBuilder._idxParent, MS.Internal.Xml.Cache.XPathDocumentBuilder._infoTable, MS.Internal.Xml.Cache.XPathDocumentBuilder._lineNumBase, MS.Internal.Xml.Cache.XPathDocumentBuilder._linePosBase, MS.Internal.Xml.Cache.XPathDocumentBuilder._nodePageFact, MS.Internal.Xml.Cache.XPathDocumentBuilder._pageParent, MS.Internal.Xml.Cache.XPathDocumentBuilder.NodePageFactory.AllocateSlot(), MS.Internal.Xml.Cache.XPathDocumentBuilder.ComputeLineInfo(), MS.Internal.Xml.Cache.XPathNodeInfoTable.Create(), System.Xml.Dictionary, System.info, System.Xml.XPath.XPathNavigator.IsText(), and System.prefix.
Referenced by MS.Internal.Xml.Cache.XPathDocumentBuilder.AddSibling(), and MS.Internal.Xml.Cache.XPathDocumentBuilder.Initialize().