Terraria: MS.Internal.Xml.Cache.XPathDocumentBuilder.Initialize
Initialize()
void MS.Internal.Xml.Cache.XPathDocumentBuilder.Initialize (XPathDocument doc, IXmlLineInfo lineInfo, string baseUri, XPathDocument::LoadFlags flags) inline
Definition at line 166 of file XPathDocumentBuilder.cs.
    {
        _doc = doc;
        _nameTable = doc.NameTable;
        _atomizeNames = (flags & XPathDocument.LoadFlags.AtomizeNames) != 0;
        _idxParent = (_idxSibling = 0);
        _elemNameIndex = new XPathNodeRef[64];
        _textBldr.Initialize(lineInfo);
        _lineInfo = lineInfo;
        _lineNumBase = 0;
        _linePosBase = 0;
        _infoTable = new XPathNodeInfoTable();
        XPathNode[] page;
        int idxText = NewNode(out page, XPathNodeType.Text, string.Empty, string.Empty, string.Empty, string.Empty);
        _doc.SetCollapsedTextNode(page, idxText);
        _idxNmsp = NewNamespaceNode(out _pageNmsp, _nameTable.Add("xml"), _nameTable.Add("http://www.w3.org/XML/1998/namespace"), null, 0);
        _doc.SetXmlNamespaceNode(_pageNmsp, _idxNmsp);
        if ((flags & XPathDocument.LoadFlags.Fragment) == 0)
        {
            _idxParent = NewNode(out _pageParent, XPathNodeType.Root, string.Empty, string.Empty, string.Empty, baseUri);
            _doc.SetRootNode(_pageParent, _idxParent);
        }
        else
        {
            _doc.SetRootNode(_nodePageFact.NextNodePage, _nodePageFact.NextNodeIndex);
        }
    }
References MS.Internal.Xml.Cache.XPathDocumentBuilder._atomizeNames, MS.Internal.Xml.Cache.XPathDocumentBuilder._doc, MS.Internal.Xml.Cache.XPathDocumentBuilder._elemNameIndex, MS.Internal.Xml.Cache.XPathDocumentBuilder._idxNmsp, MS.Internal.Xml.Cache.XPathDocumentBuilder._idxParent, MS.Internal.Xml.Cache.XPathDocumentBuilder._idxSibling, MS.Internal.Xml.Cache.XPathDocumentBuilder._infoTable, MS.Internal.Xml.Cache.XPathDocumentBuilder._lineInfo, MS.Internal.Xml.Cache.XPathDocumentBuilder._lineNumBase, MS.Internal.Xml.Cache.XPathDocumentBuilder._linePosBase, MS.Internal.Xml.Cache.XPathDocumentBuilder._nameTable, MS.Internal.Xml.Cache.XPathDocumentBuilder._nodePageFact, MS.Internal.Xml.Cache.XPathDocumentBuilder._pageNmsp, MS.Internal.Xml.Cache.XPathDocumentBuilder._pageParent, MS.Internal.Xml.Cache.XPathDocumentBuilder._textBldr, System.Xml.XmlNameTable.Add(), System.Xml.Dictionary, MS.Internal.Xml.Cache.XPathDocumentBuilder.TextBlockBuilder.Initialize(), MS.Internal.Xml.Cache.XPathDocumentBuilder.NewNamespaceNode(), MS.Internal.Xml.Cache.XPathDocumentBuilder.NewNode(), MS.Internal.Xml.Cache.XPathDocumentBuilder.NodePageFactory.NextNodeIndex, MS.Internal.Xml.Cache.XPathDocumentBuilder.NodePageFactory.NextNodePage, System.Xml.XPath.XPathDocument.SetCollapsedTextNode(), System.Xml.XPath.XPathDocument.SetRootNode(), and System.Xml.XPath.XPathDocument.SetXmlNamespaceNode().
Referenced by MS.Internal.Xml.Cache.XPathDocumentBuilder.XPathDocumentBuilder().