Terraria: MS.Internal.Xml.Cache.XPathDocumentBuilder.WriteEndElement
WriteEndElement() [2/3]
void MS.Internal.Xml.Cache.XPathDocumentBuilder.WriteEndElement (bool allowShortcutTag) inline
Definition at line 243 of file XPathDocumentBuilder.cs.
    {
        if (!_pageParent[_idxParent].HasContentChild)
        {
            TextBlockType textType = _textBldr.TextType;
            if (textType != TextBlockType.Text)
            {
                if ((uint)(textType - 5) > 1u)
                {
                    _pageParent[_idxParent].SetEmptyValue(allowShortcutTag);
                    goto IL_012d;
                }
            }
            else
            {
                if (_lineInfo == null)
                {
                    goto IL_00aa;
                }
                if (_textBldr.LineNumber == _pageParent[_idxParent].LineNumber)
                {
                    int num = _textBldr.LinePosition - _pageParent[_idxParent].LinePosition;
                    if (num >= 0 && num <= 255)
                    {
                        _pageParent[_idxParent].SetCollapsedLineInfoOffset(num);
                        goto IL_00aa;
                    }
                }
            }
            CachedTextNode();
            _pageParent[_idxParent].SetValue(_pageSibling[_idxSibling].Value);
        }
        else if (_textBldr.HasText)
        {
            CachedTextNode();
        }
        goto IL_012d;
        IL_00aa:
        _pageParent[_idxParent].SetCollapsedValue(_textBldr.ReadText());
        goto IL_012d;
        IL_012d:
        if (_pageParent[_idxParent].HasNamespaceDecls)
        {
            _doc.AddNamespace(_pageParent, _idxParent, _pageNmsp, _idxNmsp);
            XPathNodeRef xPathNodeRef = _stkNmsp.Pop();
            _pageNmsp = xPathNodeRef.Page;
            _idxNmsp = xPathNodeRef.Index;
        }
        _pageSibling = _pageParent;
        _idxSibling = _idxParent;
        _idxParent = _pageParent[_idxParent].GetParent(out _pageParent);
    }
References MS.Internal.Xml.Cache.XPathDocumentBuilder._doc, MS.Internal.Xml.Cache.XPathDocumentBuilder._idxNmsp, MS.Internal.Xml.Cache.XPathDocumentBuilder._idxParent, MS.Internal.Xml.Cache.XPathDocumentBuilder._idxSibling, MS.Internal.Xml.Cache.XPathDocumentBuilder._lineInfo, MS.Internal.Xml.Cache.XPathDocumentBuilder._pageNmsp, MS.Internal.Xml.Cache.XPathDocumentBuilder._pageParent, MS.Internal.Xml.Cache.XPathDocumentBuilder._pageSibling, MS.Internal.Xml.Cache.XPathDocumentBuilder._stkNmsp, MS.Internal.Xml.Cache.XPathDocumentBuilder._textBldr, System.Xml.XPath.XPathDocument.AddNamespace(), MS.Internal.Xml.Cache.XPathDocumentBuilder.CachedTextNode(), System.Xml.Dictionary, MS.Internal.Xml.Cache.XPathNode.GetParent(), MS.Internal.Xml.Cache.XPathDocumentBuilder.TextBlockBuilder.HasText, MS.Internal.Xml.Cache.XPathDocumentBuilder.TextBlockBuilder.LineNumber, MS.Internal.Xml.Cache.XPathNode.LineNumber, MS.Internal.Xml.Cache.XPathNode.LinePosition, MS.Internal.Xml.Cache.XPathDocumentBuilder.TextBlockBuilder.ReadText(), MS.Internal.Xml.Cache.XPathNode.SetCollapsedLineInfoOffset(), MS.Internal.Xml.Cache.XPathNode.SetCollapsedValue(), MS.Internal.Xml.Cache.XPathNode.SetEmptyValue(), MS.Internal.Xml.Cache.XPathNode.SetValue(), and MS.Internal.Xml.Cache.XPathDocumentBuilder.TextBlockBuilder.TextType.