Terraria: MS.Internal.Xml.Cache.XPathDocumentBuilder.WriteStartElement
WriteStartElement() [4/5]
void MS.Internal.Xml.Cache.XPathDocumentBuilder.WriteStartElement (string prefix, string localName, string ns, string baseUri) inline
Definition at line 203 of file XPathDocumentBuilder.cs.
    {
        if (_atomizeNames)
        {
            prefix = _nameTable.Add(prefix);
            localName = _nameTable.Add(localName);
            ns = _nameTable.Add(ns);
        }
        AddSibling(XPathNodeType.Element, localName, ns, prefix, baseUri);
        _pageParent = _pageSibling;
        _idxParent = _idxSibling;
        _idxSibling = 0;
        int num = _pageParent[_idxParent].LocalNameHashCode & 0x3F;
        _elemNameIndex[num] = LinkSimilarElements(_elemNameIndex[num].Page, _elemNameIndex[num].Index, _pageParent, _idxParent);
        if (_elemIdMap != null)
        {
            _idAttrName = (XmlQualifiedName)_elemIdMap[new XmlQualifiedName(localName, prefix)];
        }
    }
References MS.Internal.Xml.Cache.XPathDocumentBuilder._atomizeNames, MS.Internal.Xml.Cache.XPathDocumentBuilder._elemIdMap, MS.Internal.Xml.Cache.XPathDocumentBuilder._elemNameIndex, MS.Internal.Xml.Cache.XPathDocumentBuilder._idAttrName, MS.Internal.Xml.Cache.XPathDocumentBuilder._idxParent, MS.Internal.Xml.Cache.XPathDocumentBuilder._idxSibling, MS.Internal.Xml.Cache.XPathDocumentBuilder._nameTable, MS.Internal.Xml.Cache.XPathDocumentBuilder._pageParent, MS.Internal.Xml.Cache.XPathDocumentBuilder._pageSibling, System.Xml.XmlNameTable.Add(), MS.Internal.Xml.Cache.XPathDocumentBuilder.AddSibling(), MS.Internal.Xml.Cache.XPathDocumentBuilder.LinkSimilarElements(), MS.Internal.Xml.Cache.XPathNode.LocalNameHashCode, and System.prefix.