Terraria: MS.Internal.Xml.Cache.XPathDocumentBuilder.WriteEndAttribute
WriteEndAttribute()
override void MS.Internal.Xml.Cache.XPathDocumentBuilder.WriteEndAttribute () inline
Definition at line 307 of file XPathDocumentBuilder.cs.
    {
        _pageSibling[_idxSibling].SetValue(_textBldr.ReadText());
        if (_idAttrName != null && _pageSibling[_idxSibling].LocalName == _idAttrName.Name && _pageSibling[_idxSibling].Prefix == _idAttrName.Namespace)
        {
            string value = _pageSibling[_idxSibling].Value;
            _doc.AddIdElement(value, _pageParent, _idxParent);
        }
    }
References MS.Internal.Xml.Cache.XPathDocumentBuilder._doc, MS.Internal.Xml.Cache.XPathDocumentBuilder._idAttrName, MS.Internal.Xml.Cache.XPathDocumentBuilder._idxParent, MS.Internal.Xml.Cache.XPathDocumentBuilder._idxSibling, MS.Internal.Xml.Cache.XPathDocumentBuilder._pageParent, MS.Internal.Xml.Cache.XPathDocumentBuilder._pageSibling, MS.Internal.Xml.Cache.XPathDocumentBuilder._textBldr, System.Xml.XPath.XPathDocument.AddIdElement(), System.Xml.XmlQualifiedName.Name, System.Xml.XmlQualifiedName.Namespace, MS.Internal.Xml.Cache.XPathNode.Prefix, MS.Internal.Xml.Cache.XPathDocumentBuilder.TextBlockBuilder.ReadText(), MS.Internal.Xml.Cache.XPathNode.SetValue(), System.value, and MS.Internal.Xml.Cache.XPathNode.Value.