Terraria: MS.Internal.Xml.Cache.XPathDocumentBuilder.CachedTextNode
CachedTextNode()
void MS.Internal.Xml.Cache.XPathDocumentBuilder.CachedTextNode () inline private
Definition at line 578 of file XPathDocumentBuilder.cs.
    {
        TextBlockType textType = _textBldr.TextType;
        string value = _textBldr.ReadText();
        AddSibling((XPathNodeType)textType, string.Empty, string.Empty, string.Empty, string.Empty);
        _pageSibling[_idxSibling].SetValue(value);
    }
References MS.Internal.Xml.Cache.XPathDocumentBuilder._idxSibling, MS.Internal.Xml.Cache.XPathDocumentBuilder._pageSibling, MS.Internal.Xml.Cache.XPathDocumentBuilder._textBldr, MS.Internal.Xml.Cache.XPathDocumentBuilder.AddSibling(), MS.Internal.Xml.Cache.XPathDocumentBuilder.TextBlockBuilder.ReadText(), MS.Internal.Xml.Cache.XPathNode.SetValue(), MS.Internal.Xml.Cache.XPathDocumentBuilder.TextBlockBuilder.TextType, and System.value.
Referenced by MS.Internal.Xml.Cache.XPathDocumentBuilder.AddSibling(), MS.Internal.Xml.Cache.XPathDocumentBuilder.Close(), and MS.Internal.Xml.Cache.XPathDocumentBuilder.WriteEndElement().