Terraria: MS.Internal.Xml.Cache.XPathDocumentBuilder.AddSibling
AddSibling()
void MS.Internal.Xml.Cache.XPathDocumentBuilder.AddSibling (XPathNodeType xptyp, string localName, string namespaceUri, string prefix, string baseUri) inline private
Definition at line 557 of file XPathDocumentBuilder.cs.
    {
        if (_textBldr.HasText)
        {
            CachedTextNode();
        }
        XPathNode[] page;
        int idxSibling = NewNode(out page, xptyp, localName, namespaceUri, prefix, baseUri);
        if (_idxParent != 0)
        {
            _pageParent[_idxParent].SetParentProperties(xptyp);
            if (_idxSibling != 0)
            {
                _pageSibling[_idxSibling].SetSibling(_infoTable, page, idxSibling);
            }
        }
        _pageSibling = page;
        _idxSibling = idxSibling;
    }
References MS.Internal.Xml.Cache.XPathDocumentBuilder._idxParent, MS.Internal.Xml.Cache.XPathDocumentBuilder._idxSibling, MS.Internal.Xml.Cache.XPathDocumentBuilder._infoTable, MS.Internal.Xml.Cache.XPathDocumentBuilder._pageParent, MS.Internal.Xml.Cache.XPathDocumentBuilder._pageSibling, MS.Internal.Xml.Cache.XPathDocumentBuilder._textBldr, MS.Internal.Xml.Cache.XPathDocumentBuilder.CachedTextNode(), System.Xml.Dictionary, MS.Internal.Xml.Cache.XPathDocumentBuilder.TextBlockBuilder.HasText, MS.Internal.Xml.Cache.XPathDocumentBuilder.NewNode(), System.prefix, MS.Internal.Xml.Cache.XPathNode.SetParentProperties(), and MS.Internal.Xml.Cache.XPathNode.SetSibling().
Referenced by MS.Internal.Xml.Cache.XPathDocumentBuilder.CachedTextNode(), MS.Internal.Xml.Cache.XPathDocumentBuilder.Close(), MS.Internal.Xml.Cache.XPathDocumentBuilder.WriteComment(), MS.Internal.Xml.Cache.XPathDocumentBuilder.WriteProcessingInstruction(), MS.Internal.Xml.Cache.XPathDocumentBuilder.WriteStartAttribute(), and MS.Internal.Xml.Cache.XPathDocumentBuilder.WriteStartElement().