Terraria: MS.Internal.Xml.Cache.XPathDocumentBuilder.Close
Close() [1/2]
override void MS.Internal.Xml.Cache.XPathDocumentBuilder.Close () inline virtual
Reimplemented from System.Xml.XmlWriter.
Definition at line 390 of file XPathDocumentBuilder.cs.
    {
        if (_textBldr.HasText)
        {
            CachedTextNode();
        }
        XPathNode[] pageRoot;
        int rootNode = _doc.GetRootNode(out pageRoot);
        if (rootNode == _nodePageFact.NextNodeIndex && pageRoot == _nodePageFact.NextNodePage)
        {
            AddSibling(XPathNodeType.Text, string.Empty, string.Empty, string.Empty, string.Empty);
            _pageSibling[_idxSibling].SetValue(string.Empty);
        }
    }
References MS.Internal.Xml.Cache.XPathDocumentBuilder._doc, MS.Internal.Xml.Cache.XPathDocumentBuilder._idxSibling, MS.Internal.Xml.Cache.XPathDocumentBuilder._nodePageFact, MS.Internal.Xml.Cache.XPathDocumentBuilder._pageSibling, MS.Internal.Xml.Cache.XPathDocumentBuilder._textBldr, MS.Internal.Xml.Cache.XPathDocumentBuilder.AddSibling(), MS.Internal.Xml.Cache.XPathDocumentBuilder.CachedTextNode(), System.Xml.Dictionary, System.Xml.XPath.XPathDocument.GetRootNode(), MS.Internal.Xml.Cache.XPathDocumentBuilder.TextBlockBuilder.HasText, MS.Internal.Xml.Cache.XPathDocumentBuilder.NodePageFactory.NextNodeIndex, MS.Internal.Xml.Cache.XPathDocumentBuilder.NodePageFactory.NextNodePage, and MS.Internal.Xml.Cache.XPathNode.SetValue().