Terraria: EmoteButton.DrawSelf
DrawSelf()
override void EmoteButton.DrawSelf (SpriteBatch spriteBatch) inline protected virtual
Reimplemented from UIElement.
     {
         CalculatedStyle dimensions = GetDimensions();
         Vector2 vector = dimensions.Position() + new Vector2(dimensions.Width, dimensions.Height) / 2f;
         Rectangle frame = GetFrame();
         Rectangle value = frame;
         value.X = _texture.Width() / 8;
         value.Y = 0;
         Vector2 origin = frame.Size() / 2f;
         Color white = Color.White;
         Color color = Color.Black;
         if (_hovered)
         {
             color = Main.OurFavoriteColor;
         }
         spriteBatch.Draw(_texture.Value, vector, value, white, 0f, origin, 1f, SpriteEffects.None, 0f);
         spriteBatch.Draw(_texture.Value, vector, frame, white, 0f, origin, 1f, SpriteEffects.None, 0f);
         spriteBatch.Draw(_textureBorder.Value, vector - Vector2.One * 2f, null, color, 0f, origin, 1f, SpriteEffects.None, 0f);
         if (_hovered)
         {
             string name = EmoteID.Search.GetName(_emoteIndex);
             string cursorText = "/" + Language.GetTextValue("EmojiName." + name);
             Main.instance.MouseText(cursorText, 0, 0);
         }
     }
References _emoteIndex, _hovered, _texture, _textureBorder, Color, UIElement.GetDimensions(), GetFrame(), IdDictionary.GetName(), Language.GetTextValue(), CalculatedStyle.Height, Main.instance, Main.MouseText(), Main.OurFavoriteColor, CalculatedStyle.Position(), EmoteID.Search, Asset< T >.Value, and CalculatedStyle.Width.