Terraria: System.Security.Cryptography.PasswordBasedEncryption.Decrypt
Decrypt() [2/4]
static unsafe int System.Security.Cryptography.PasswordBasedEncryption.Decrypt (in System::Security::Cryptography::Asn1::AlgorithmIdentifierAsn algorithmIdentifier, ReadOnlySpan< char > password, ReadOnlySpan< byte > passwordBytes, ReadOnlySpan< byte > encryptedData, Span< byte > destination) inline static package
Definition at line 41 of file PasswordBasedEncryption.cs.
    {
        SymmetricAlgorithm symmetricAlgorithm = null;
        bool flag = false;
        HashAlgorithmName hashAlgorithm;
        switch (algorithmIdentifier.Algorithm)
        {
        case "1.2.840.113549.1.5.3":
            hashAlgorithm = HashAlgorithmName.MD5;
            symmetricAlgorithm = DES.Create();
            break;
        case "1.2.840.113549.1.5.6":
            hashAlgorithm = HashAlgorithmName.MD5;
            symmetricAlgorithm = CreateRC2();
            break;
        case "1.2.840.113549.1.5.10":
            hashAlgorithm = HashAlgorithmName.SHA1;
            symmetricAlgorithm = DES.Create();
            break;
        case "1.2.840.113549.1.5.11":
            hashAlgorithm = HashAlgorithmName.SHA1;
            symmetricAlgorithm = CreateRC2();
            break;
        case "1.2.840.113549.1.12.1.3":
            hashAlgorithm = HashAlgorithmName.SHA1;
            symmetricAlgorithm = TripleDES.Create();
            flag = true;
            break;
        case "1.2.840.113549.1.12.1.4":
            hashAlgorithm = HashAlgorithmName.SHA1;
            symmetricAlgorithm = TripleDES.Create();
            symmetricAlgorithm.KeySize = 128;
            flag = true;
            break;
        case "1.2.840.113549.1.12.1.5":
            hashAlgorithm = HashAlgorithmName.SHA1;
            symmetricAlgorithm = CreateRC2();
            symmetricAlgorithm.KeySize = 128;
            flag = true;
            break;
        case "1.2.840.113549.1.12.1.6":
            hashAlgorithm = HashAlgorithmName.SHA1;
            symmetricAlgorithm = CreateRC2();
            symmetricAlgorithm.KeySize = 40;
            flag = true;
            break;
        case "1.2.840.113549.1.5.13":
            return Pbes2Decrypt(algorithmIdentifier.Parameters, password, passwordBytes, encryptedData, destination);
        default:
            throw new CryptographicException(System.SR.Format(System.SR.Cryptography_UnknownAlgorithmIdentifier, algorithmIdentifier.Algorithm));
        }
        using (symmetricAlgorithm)
        {
            if (flag)
            {
                if (password.IsEmpty && passwordBytes.Length > 0)
                {
                    throw AlgorithmKdfRequiresChars(algorithmIdentifier.Algorithm);
                }
                return Pkcs12PbeDecrypt(algorithmIdentifier, password, hashAlgorithm, symmetricAlgorithm, encryptedData, destination);
            }
            using IncrementalHash hasher = IncrementalHash.CreateHash(hashAlgorithm);
            Span<byte> span = stackalloc byte[128];
            ReadOnlySpan<byte> password2 = default(Span<byte>);
            byte[] array = null;
            Encoding encoding = null;
            if (passwordBytes.Length > 0 || password.Length == 0)
            {
                password2 = passwordBytes;
            }
            else
            {
                encoding = Encoding.UTF8;
                int byteCount = encoding.GetByteCount(password);
                if (byteCount > span.Length)
                {
                    array = System.Security.Cryptography.CryptoPool.Rent(byteCount);
                    span = array.AsSpan(0, byteCount);
                }
                else
                {
                    span = span.Slice(0, byteCount);
                }
            }
            fixed (byte* ptr = &MemoryMarshal.GetReference(span))
            {
                if (encoding != null)
                {
                    span = span[..encoding.GetBytes(password, span)];
                    password2 = span;
                }
                try
                {
                    return Pbes1Decrypt(algorithmIdentifier.Parameters, password2, hasher, symmetricAlgorithm, encryptedData, destination);
                }
                finally
                {
                    CryptographicOperations.ZeroMemory(span);
                    if (array != null)
                    {
                        System.Security.Cryptography.CryptoPool.Return(array, 0);
                    }
                }
            }
        }
    }
References System.Security.Cryptography.PasswordBasedEncryption.AlgorithmKdfRequiresChars(), System.array, System.byteCount, System.Security.Cryptography.DES.Create(), System.Security.Cryptography.TripleDES.Create(), System.Security.Cryptography.IncrementalHash.CreateHash(), System.Security.Cryptography.PasswordBasedEncryption.CreateRC2(), System.SR.Cryptography_UnknownAlgorithmIdentifier, System.destination, System.SR.Format(), System.Text.Encoding.GetByteCount(), System.Text.Encoding.GetBytes(), System.ReadOnlySpan< T >.IsEmpty, System.ReadOnlySpan< T >.Length, System.Span< T >.Length, System.Security.Cryptography.HashAlgorithmName.MD5, System.Security.Cryptography.PasswordBasedEncryption.Pbes1Decrypt(), System.Security.Cryptography.PasswordBasedEncryption.Pbes2Decrypt(), System.Security.Cryptography.PasswordBasedEncryption.Pkcs12PbeDecrypt(), System.Security.Cryptography.CryptoPool.Rent(), System.Security.Cryptography.CryptoPool.Return(), System.Security.Cryptography.HashAlgorithmName.SHA1, System.Span< T >.Slice(), System.Text.Encoding.UTF8, and System.Security.Cryptography.CryptographicOperations.ZeroMemory().