Terraria: System.Security.Cryptography.PasswordBasedEncryption.InitiateEncryption
InitiateEncryption() [2/2]
static void System.Security.Cryptography.PasswordBasedEncryption.InitiateEncryption (PbeParameters pbeParameters, out SymmetricAlgorithm cipher, out string hmacOid, out string encryptionAlgorithmOid, out bool isPkcs12) inline static package
Definition at line 148 of file PasswordBasedEncryption.cs.
    {
        isPkcs12 = false;
        switch (pbeParameters.EncryptionAlgorithm)
        {
        case PbeEncryptionAlgorithm.Aes128Cbc:
            cipher = Aes.Create();
            cipher.KeySize = 128;
            encryptionAlgorithmOid = "2.16.840.1.101.3.4.1.2";
            break;
        case PbeEncryptionAlgorithm.Aes192Cbc:
            cipher = Aes.Create();
            cipher.KeySize = 192;
            encryptionAlgorithmOid = "2.16.840.1.101.3.4.1.22";
            break;
        case PbeEncryptionAlgorithm.Aes256Cbc:
            cipher = Aes.Create();
            cipher.KeySize = 256;
            encryptionAlgorithmOid = "2.16.840.1.101.3.4.1.42";
            break;
        case PbeEncryptionAlgorithm.TripleDes3KeyPkcs12:
            cipher = TripleDES.Create();
            cipher.KeySize = 192;
            encryptionAlgorithmOid = "1.2.840.113549.1.12.1.3";
            isPkcs12 = true;
            break;
        default:
            throw new CryptographicException(System.SR.Format(System.SR.Cryptography_UnknownAlgorithmIdentifier, pbeParameters.HashAlgorithm.Name));
        }
        HashAlgorithmName hashAlgorithm = pbeParameters.HashAlgorithm;
        if (hashAlgorithm == HashAlgorithmName.SHA256)
        {
            hmacOid = "1.2.840.113549.2.9";
            return;
        }
        if (hashAlgorithm == HashAlgorithmName.SHA384)
        {
            hmacOid = "1.2.840.113549.2.10";
            return;
        }
        if (hashAlgorithm == HashAlgorithmName.SHA512)
        {
            hmacOid = "1.2.840.113549.2.11";
            return;
        }
        if (hashAlgorithm == HashAlgorithmName.SHA1)
        {
            hmacOid = "1.2.840.113549.2.7";
            return;
        }
        cipher.Dispose();
        throw new CryptographicException(System.SR.Cryptography_UnknownHashAlgorithm, hashAlgorithm.Name);
    }
References System.Security.Cryptography.Aes.Create(), System.Security.Cryptography.TripleDES.Create(), System.SR.Cryptography_UnknownAlgorithmIdentifier, System.SR.Cryptography_UnknownHashAlgorithm, System.Security.Cryptography.PbeParameters.EncryptionAlgorithm, System.SR.Format(), System.Security.Cryptography.PbeParameters.HashAlgorithm, System.Security.Cryptography.HashAlgorithmName.Name, System.Security.Cryptography.HashAlgorithmName.SHA1, System.Security.Cryptography.HashAlgorithmName.SHA256, System.Security.Cryptography.HashAlgorithmName.SHA384, and System.Security.Cryptography.HashAlgorithmName.SHA512.