Terraria: System.Security.Cryptography.PasswordBasedEncryption.Pbes2Decrypt
Pbes2Decrypt() [4/4]
static unsafe int System.Security.Cryptography.PasswordBasedEncryption.Pbes2Decrypt (ReadOnlyMemory< byte >? algorithmParameters, ReadOnlySpan< char > password, ReadOnlySpan< byte > passwordBytes, ReadOnlySpan< byte > encryptedData, Span< byte > destination) inline static private
Definition at line 279 of file PasswordBasedEncryption.cs.
    {
        Span<byte> span = stackalloc byte[128];
        ReadOnlySpan<byte> password2 = default(Span<byte>);
        byte[] array = null;
        Encoding encoding = null;
        if (passwordBytes.Length > 0 || password.Length == 0)
        {
            password2 = passwordBytes;
        }
        else
        {
            encoding = Encoding.UTF8;
            int byteCount = encoding.GetByteCount(password);
            if (byteCount > span.Length)
            {
                array = System.Security.Cryptography.CryptoPool.Rent(byteCount);
                span = array.AsSpan(0, byteCount);
            }
            else
            {
                span = span.Slice(0, byteCount);
            }
        }
        fixed (byte* ptr = &MemoryMarshal.GetReference(span))
        {
            if (encoding != null)
            {
                span = span[..encoding.GetBytes(password, span)];
                password2 = span;
            }
            try
            {
                return Pbes2Decrypt(algorithmParameters, password2, encryptedData, destination);
            }
            finally
            {
                if (array != null)
                {
                    System.Security.Cryptography.CryptoPool.Return(array, span.Length);
                }
            }
        }
    }
References System.array, System.byteCount, System.destination, System.Text.Encoding.GetByteCount(), System.Text.Encoding.GetBytes(), System.ReadOnlySpan< T >.Length, System.Span< T >.Length, System.Security.Cryptography.PasswordBasedEncryption.Pbes2Decrypt(), System.Security.Cryptography.CryptoPool.Rent(), System.Security.Cryptography.CryptoPool.Return(), System.Span< T >.Slice(), and System.Text.Encoding.UTF8.