Terraria: System.Security.Cryptography.PasswordBasedEncryption.Pbkdf1
Pbkdf1() [2/2]
static void System.Security.Cryptography.PasswordBasedEncryption.Pbkdf1 (IncrementalHash hasher, ReadOnlySpan< byte > password, ReadOnlySpan< byte > salt, int iterationCount, Span< byte > dk) inline static private
Definition at line 603 of file PasswordBasedEncryption.cs.
    {
        Span<byte> span = stackalloc byte[20];
        hasher.AppendData(password);
        hasher.AppendData(salt);
        if (!hasher.TryGetHashAndReset(span, out var bytesWritten))
        {
            throw new CryptographicException();
        }
        span = span.Slice(0, bytesWritten);
        for (int i = 1; i < iterationCount; i++)
        {
            hasher.AppendData(span);
            if (!hasher.TryGetHashAndReset(span, out bytesWritten) || bytesWritten != span.Length)
            {
                throw new CryptographicException();
            }
        }
        span.Slice(0, dk.Length).CopyTo(dk);
        CryptographicOperations.ZeroMemory(span);
    }
References System.Security.Cryptography.IncrementalHash.AppendData(), System.Span< T >.Length, System.Span< T >.Slice(), System.Security.Cryptography.IncrementalHash.TryGetHashAndReset(), and System.Security.Cryptography.CryptographicOperations.ZeroMemory().