Terraria: System.Security.Cryptography.PasswordBasedEncryption.Pkcs12PbeDecrypt
Pkcs12PbeDecrypt() [1/2]
static int System.Security.Cryptography.PasswordBasedEncryption.Pkcs12PbeDecrypt (AlgorithmIdentifierAsn algorithmIdentifier, ReadOnlySpan< char > password, HashAlgorithmName hashAlgorithm, SymmetricAlgorithm cipher, ReadOnlySpan< byte > encryptedData, Span< byte > destination) inline static private
Definition at line 531 of file PasswordBasedEncryption.cs.
    {
        if (!algorithmIdentifier.Parameters.HasValue)
        {
            throw new CryptographicException(System.SR.Cryptography_Der_Invalid_Encoding);
        }
        if (cipher.KeySize > 256 || cipher.BlockSize > 256)
        {
            throw new CryptographicException();
        }
        PBEParameter pBEParameter = PBEParameter.Decode(algorithmIdentifier.Parameters.Value, AsnEncodingRules.BER);
        int iterationCount = NormalizeIterationCount(pBEParameter.IterationCount, 600000);
        Span<byte> span = stackalloc byte[cipher.BlockSize / 8];
        Span<byte> span2 = stackalloc byte[cipher.KeySize / 8];
        ReadOnlySpan<byte> span3 = pBEParameter.Salt.Span;
        try
        {
            Pkcs12Kdf.DeriveIV(password, hashAlgorithm, iterationCount, span3, span);
            Pkcs12Kdf.DeriveCipherKey(password, hashAlgorithm, iterationCount, span3, span2);
            return Decrypt(cipher, span2, span, encryptedData, destination);
        }
        finally
        {
            CryptographicOperations.ZeroMemory(span2);
            CryptographicOperations.ZeroMemory(span);
        }
    }
References System.Security.Cryptography.SymmetricAlgorithm.BlockSize, System.SR.Cryptography_Der_Invalid_Encoding, System.Security.Cryptography.Asn1.PBEParameter.Decode(), System.Security.Cryptography.PasswordBasedEncryption.Decrypt(), System.Security.Cryptography.Pkcs.Pkcs12Kdf.DeriveCipherKey(), System.Security.Cryptography.Pkcs.Pkcs12Kdf.DeriveIV(), System.destination, System.Security.Cryptography.Asn1.PBEParameter.IterationCount, System.Security.Cryptography.SymmetricAlgorithm.KeySize, System.Security.Cryptography.PasswordBasedEncryption.NormalizeIterationCount(), System.Security.Cryptography.Asn1.AlgorithmIdentifierAsn.Parameters, System.Security.Cryptography.Asn1.PBEParameter.Salt, System.ReadOnlyMemory< T >.Span, and System.Security.Cryptography.CryptographicOperations.ZeroMemory().
Referenced by System.Security.Cryptography.PasswordBasedEncryption.Decrypt(), and System.Security.Cryptography.PasswordBasedEncryption.Decrypt().