Terraria: System.Security.Cryptography.PasswordBasedEncryption.Encrypt
Encrypt() [2/2]
static unsafe int System.Security.Cryptography.PasswordBasedEncryption.Encrypt (ReadOnlySpan< char > password, ReadOnlySpan< byte > passwordBytes, SymmetricAlgorithm cipher, bool isPkcs12, AsnWriter source, PbeParameters pbeParameters, ReadOnlySpan< byte > salt, byte[] destination, Span< byte > ivDest) inline static package
Definition at line 202 of file PasswordBasedEncryption.cs.
    {
        byte[] array = null;
        byte[] iV = cipher.IV;
        int encodedLength = source.GetEncodedLength();
        byte[] array2 = System.Security.Cryptography.CryptoPool.Rent(encodedLength);
        int num = cipher.KeySize / 8;
        int iterationCount = pbeParameters.IterationCount;
        HashAlgorithmName hashAlgorithm = pbeParameters.HashAlgorithm;
        Encoding uTF = Encoding.UTF8;
        if (!isPkcs12)
        {
            array = ((passwordBytes.Length == 0 && password.Length > 0) ? new byte[uTF.GetByteCount(password)] : ((passwordBytes.Length != 0) ? new byte[passwordBytes.Length] : Array.Empty<byte>()));
        }
        fixed (byte* ptr3 = array2)
        {
            fixed (byte* ptr2 = array)
            {
                byte[] array3;
                if (isPkcs12)
                {
                    array3 = new byte[num];
                    System.Security.Cryptography.Pkcs.Pkcs12Kdf.DeriveCipherKey(password, hashAlgorithm, iterationCount, salt, array3);
                    System.Security.Cryptography.Pkcs.Pkcs12Kdf.DeriveIV(password, hashAlgorithm, iterationCount, salt, iV);
                    ivDest.Clear();
                }
                else
                {
                    if (passwordBytes.Length > 0)
                    {
                        passwordBytes.CopyTo(array);
                    }
                    else if (password.Length > 0)
                    {
                        int bytes = uTF.GetBytes(password, array);
                        if (bytes != array.Length)
{
                            throw new CryptographicException();
                        }
                    }
                    using (Rfc2898DeriveBytes rfc2898DeriveBytes = new Rfc2898DeriveBytes(array, salt.ToArray(), iterationCount, hashAlgorithm))
                    {
                        array3 = rfc2898DeriveBytes.GetBytes(num);
                    }
                    iV.CopyTo(ivDest);
                }
                fixed (byte* ptr = array3)
                {
                    CryptographicOperations.ZeroMemory(array);
                    using ICryptoTransform cryptoTransform = cipher.CreateEncryptor(array3, iV);
                    int num2 = cipher.BlockSize / 8;
                    int num3 = encodedLength % num2;
                    int num4 = encodedLength - num3;
                    try
                    {
                        if (!source.TryEncode(array2, out var _))
{
                            throw new CryptographicException();
                        }
                        int num5 = 0;
                        if (num4 != 0)
{
                            num5 = cryptoTransform.TransformBlock(array2, 0, num4, destination, 0);
                        }
                        byte[] array4 = cryptoTransform.TransformFinalBlock(array2, num5, num3);
                        array4.AsSpan().CopyTo(destination.AsSpan(num5));
                        return num5 + array4.Length;
                    }
                    finally
                    {
                        System.Security.Cryptography.CryptoPool.Return(array2, encodedLength);
                    }
                }
            }
        }
    }
References System.array, System.bytes, System.Span< T >.Clear(), System.ReadOnlySpan< T >.CopyTo(), System.Security.Cryptography.SymmetricAlgorithm.CreateEncryptor(), System.Security.Cryptography.Pkcs.Pkcs12Kdf.DeriveCipherKey(), System.Security.Cryptography.Pkcs.Pkcs12Kdf.DeriveIV(), System.destination, System.Text.Encoding.GetByteCount(), System.Text.Encoding.GetBytes(), System.Security.Cryptography.Rfc2898DeriveBytes.GetBytes(), System.Security.Cryptography.PbeParameters.HashAlgorithm, System.Security.Cryptography.PbeParameters.IterationCount, System.Security.Cryptography.SymmetricAlgorithm.IV, System.ReadOnlySpan< T >.Length, System.Security.Cryptography.CryptoPool.Rent(), System.Security.Cryptography.CryptoPool.Return(), System.source, System.ReadOnlySpan< T >.ToArray(), System.Text.Encoding.UTF8, and System.Security.Cryptography.CryptographicOperations.ZeroMemory().