Terraria: System.Security.Cryptography.PasswordBasedEncryption.Pbes1Decrypt
Pbes1Decrypt() [2/2]
static int System.Security.Cryptography.PasswordBasedEncryption.Pbes1Decrypt (ReadOnlyMemory< byte >? algorithmParameters, ReadOnlySpan< byte > password, IncrementalHash hasher, SymmetricAlgorithm cipher, ReadOnlySpan< byte > encryptedData, Span< byte > destination) inline static private
Definition at line 501 of file PasswordBasedEncryption.cs.
    {
        if (!algorithmParameters.HasValue)
        {
            throw new CryptographicException(System.SR.Cryptography_Der_Invalid_Encoding);
        }
        System.Security.Cryptography.Asn1.PBEParameter pBEParameter = System.Security.Cryptography.Asn1.PBEParameter.Decode(algorithmParameters.Value, AsnEncodingRules.BER);
        if (pBEParameter.Salt.Length != 8)
        {
            throw new CryptographicException(System.SR.Cryptography_Der_Invalid_Encoding);
        }
        if (pBEParameter.IterationCount < 1)
        {
            throw new CryptographicException(System.SR.Cryptography_Der_Invalid_Encoding);
        }
        int iterationCount = NormalizeIterationCount(pBEParameter.IterationCount);
        Span<byte> span = stackalloc byte[16];
        try
        {
            Pbkdf1(hasher, password, pBEParameter.Salt.Span, iterationCount, span);
            Span<byte> span2 = span.Slice(0, 8);
            Span<byte> span3 = span.Slice(8, 8);
            return Decrypt(cipher, span2, span3, encryptedData, destination);
        }
        finally
        {
            CryptographicOperations.ZeroMemory(span);
        }
    }
References System.SR.Cryptography_Der_Invalid_Encoding, System.Security.Cryptography.Asn1.PBEParameter.Decode(), System.Security.Cryptography.PasswordBasedEncryption.Decrypt(), System.destination, System.Security.Cryptography.Asn1.PBEParameter.IterationCount, System.ReadOnlyMemory< T >.Length, System.Security.Cryptography.PasswordBasedEncryption.NormalizeIterationCount(), System.Security.Cryptography.PasswordBasedEncryption.Pbkdf1(), System.Security.Cryptography.Asn1.PBEParameter.Salt, System.Span< T >.Slice(), System.ReadOnlyMemory< T >.Span, and System.Security.Cryptography.CryptographicOperations.ZeroMemory().