Terraria: System.Security.Cryptography.PasswordBasedEncryption.Decrypt
Decrypt() [4/4]
static unsafe int System.Security.Cryptography.PasswordBasedEncryption.Decrypt (SymmetricAlgorithm cipher, ReadOnlySpan< byte > key, ReadOnlySpan< byte > iv, ReadOnlySpan< byte > encryptedData, Span< byte > destination) inline static private
Definition at line 559 of file PasswordBasedEncryption.cs.
    {
        byte[] array = new byte[key.Length];
        byte[] array2 = new byte[iv.Length];
        byte[] array3 = System.Security.Cryptography.CryptoPool.Rent(encryptedData.Length);
        byte[] array4 = System.Security.Cryptography.CryptoPool.Rent(destination.Length);
        fixed (byte* ptr5 = array)
        {
            fixed (byte* ptr4 = array2)
            {
                fixed (byte* ptr3 = array3)
                {
                    fixed (byte* ptr2 = array4)
                    {
                        try
{
                            key.CopyTo(array);
                            iv.CopyTo(array2);
                            using ICryptoTransform cryptoTransform = cipher.CreateDecryptor(array, array2);
                            encryptedData.CopyTo(array3);
                            int num = cryptoTransform.TransformBlock(array3, 0, encryptedData.Length, array4, 0);
                            array4.AsSpan(0, num).CopyTo(destination);
                            byte[] array5 = cryptoTransform.TransformFinalBlock(Array.Empty<byte>(), 0, 0);
                            fixed (byte* ptr = array5)
{
                                Span<byte> buffer = array5.AsSpan();
                                buffer.CopyTo(destination.Slice(num));
                                CryptographicOperations.ZeroMemory(buffer);
                            }
                            return num + array5.Length;
                        }
                        finally
{
                            CryptographicOperations.ZeroMemory(array);
                            CryptographicOperations.ZeroMemory(array2);
                            System.Security.Cryptography.CryptoPool.Return(array3, encryptedData.Length);
                            System.Security.Cryptography.CryptoPool.Return(array4, destination.Length);
                        }
                    }
                }
            }
        }
    }
References System.array, System.buffer, System.ReadOnlySpan< T >.CopyTo(), System.Security.Cryptography.SymmetricAlgorithm.CreateDecryptor(), System.destination, System.key, System.ReadOnlySpan< T >.Length, System.Security.Cryptography.CryptoPool.Rent(), System.Security.Cryptography.CryptoPool.Return(), and System.Security.Cryptography.CryptographicOperations.ZeroMemory().