Terraria: System.Security.Cryptography.PasswordBasedEncryption.OpenPbkdf2
OpenPbkdf2() [2/2]
static unsafe Rfc2898DeriveBytes System.Security.Cryptography.PasswordBasedEncryption.OpenPbkdf2 (ReadOnlySpan< byte > password, ReadOnlyMemory< byte >? parameters, out int? requestedKeyLength) inline static private
Definition at line 446 of file PasswordBasedEncryption.cs.
    {
        if (!parameters.HasValue)
        {
            throw new CryptographicException(System.SR.Cryptography_Der_Invalid_Encoding);
        }
        System.Security.Cryptography.Asn1.Pbkdf2Params pbkdf2Params = System.Security.Cryptography.Asn1.Pbkdf2Params.Decode(parameters.Value, AsnEncodingRules.BER);
        if (pbkdf2Params.Salt.OtherSource.HasValue)
        {
            throw new CryptographicException(System.SR.Format(System.SR.Cryptography_UnknownAlgorithmIdentifier, pbkdf2Params.Salt.OtherSource.Value.Algorithm));
        }
        if (!pbkdf2Params.Salt.Specified.HasValue)
        {
            throw new CryptographicException(System.SR.Cryptography_Der_Invalid_Encoding);
        }
        HashAlgorithmName hashAlgorithm = pbkdf2Params.Prf.Algorithm switch
        {
            "1.2.840.113549.2.7" => HashAlgorithmName.SHA1,
            "1.2.840.113549.2.9" => HashAlgorithmName.SHA256,
            "1.2.840.113549.2.10" => HashAlgorithmName.SHA384,
            "1.2.840.113549.2.11" => HashAlgorithmName.SHA512,
            _ => throw new CryptographicException(System.SR.Format(System.SR.Cryptography_UnknownAlgorithmIdentifier, pbkdf2Params.Prf.Algorithm)),
        };
        if (!pbkdf2Params.Prf.HasNullEquivalentParameters())
        {
            throw new CryptographicException(System.SR.Cryptography_Der_Invalid_Encoding);
        }
        int iterations = NormalizeIterationCount(pbkdf2Params.IterationCount);
        ReadOnlyMemory<byte> value = pbkdf2Params.Salt.Specified.Value;
        byte[] array = new byte[password.Length];
        byte[] array2 = new byte[value.Length];
        fixed (byte* ptr2 = array)
        {
            fixed (byte* ptr = array2)
            {
                password.CopyTo(array);
                value.CopyTo(array2);
                try
                {
                    requestedKeyLength = pbkdf2Params.KeyLength;
                    return new Rfc2898DeriveBytes(array, array2, iterations, hashAlgorithm);
                }
                catch (ArgumentException inner)
                {
                    throw new CryptographicException(System.SR.Argument_InvalidValue, inner);
                }
                finally
                {
                    CryptographicOperations.ZeroMemory(array);
                    CryptographicOperations.ZeroMemory(array2);
                }
            }
        }
    }
References System.Security.Cryptography.Asn1.AlgorithmIdentifierAsn.Algorithm, System.SR.Argument_InvalidValue, System.array, System.ReadOnlySpan< T >.CopyTo(), System.SR.Cryptography_Der_Invalid_Encoding, System.SR.Cryptography_UnknownAlgorithmIdentifier, System.Security.Cryptography.Asn1.Pbkdf2Params.Decode(), System.SR.Format(), System.Security.Cryptography.Asn1.AlgorithmIdentifierAsn.HasNullEquivalentParameters(), System.Security.Cryptography.Asn1.Pbkdf2Params.IterationCount, System.Security.Cryptography.Asn1.Pbkdf2Params.KeyLength, System.ReadOnlySpan< T >.Length, System.Security.Cryptography.PasswordBasedEncryption.NormalizeIterationCount(), System.Security.Cryptography.Asn1.Pbkdf2SaltChoice.OtherSource, System.Security.Cryptography.Asn1.Pbkdf2Params.Prf, System.Security.Cryptography.Asn1.Pbkdf2Params.Salt, System.Security.Cryptography.HashAlgorithmName.SHA1, System.Security.Cryptography.HashAlgorithmName.SHA256, System.Security.Cryptography.HashAlgorithmName.SHA384, System.Security.Cryptography.HashAlgorithmName.SHA512, System.Security.Cryptography.Asn1.Pbkdf2SaltChoice.Specified, System.value, and System.Security.Cryptography.CryptographicOperations.ZeroMemory().