Terraria: System.Security.Cryptography.PasswordBasedEncryption.OpenCipher
OpenCipher() [2/2]
static SymmetricAlgorithm System.Security.Cryptography.PasswordBasedEncryption.OpenCipher (System::Security::Cryptography::Asn1::AlgorithmIdentifierAsn encryptionScheme, int? requestedKeyLength, ref Span< byte > iv) inline static private
Definition at line 359 of file PasswordBasedEncryption.cs.
    {
        string algorithm = encryptionScheme.Algorithm;
        switch (algorithm)
        {
        case "2.16.840.1.101.3.4.1.2":
        case "2.16.840.1.101.3.4.1.22":
        case "2.16.840.1.101.3.4.1.42":
        {
            int num = algorithm switch
            {
                "2.16.840.1.101.3.4.1.2" => 16,
                "2.16.840.1.101.3.4.1.22" => 24,
                "2.16.840.1.101.3.4.1.42" => 32,
                _ => throw new CryptographicException(),
            };
            if (requestedKeyLength.HasValue && requestedKeyLength != num)
            {
                throw new CryptographicException(System.SR.Cryptography_Der_Invalid_Encoding);
            }
            ReadIvParameter(encryptionScheme.Parameters, 16, ref iv);
            Aes aes = Aes.Create();
            aes.KeySize = num * 8;
            return aes;
        }
        case "1.2.840.113549.3.7":
            if (requestedKeyLength.HasValue && requestedKeyLength != 24)
            {
                throw new CryptographicException(System.SR.Cryptography_Der_Invalid_Encoding);
            }
            ReadIvParameter(encryptionScheme.Parameters, 8, ref iv);
            return TripleDES.Create();
        case "1.2.840.113549.3.2":
        {
            if (!encryptionScheme.Parameters.HasValue)
            {
                throw new CryptographicException(System.SR.Cryptography_Der_Invalid_Encoding);
            }
            if (!requestedKeyLength.HasValue)
            {
                throw new CryptographicException(System.SR.Cryptography_Der_Invalid_Encoding);
            }
            System.Security.Cryptography.Asn1.Rc2CbcParameters rc2CbcParameters = System.Security.Cryptography.Asn1.Rc2CbcParameters.Decode(encryptionScheme.Parameters.Value, AsnEncodingRules.BER);
            if (rc2CbcParameters.Iv.Length != 8)
            {
                throw new CryptographicException(System.SR.Cryptography_Der_Invalid_Encoding);
            }
            RC2 rC = CreateRC2();
            rC.KeySize = requestedKeyLength.Value * 8;
            rC.EffectiveKeySize = rc2CbcParameters.GetEffectiveKeyBits();
            rc2CbcParameters.Iv.Span.CopyTo(iv);
            iv = iv.Slice(0, rc2CbcParameters.Iv.Length);
            return rC;
        }
        case "1.3.14.3.2.7":
            if (requestedKeyLength.HasValue && requestedKeyLength != 8)
            {
                throw new CryptographicException(System.SR.Cryptography_Der_Invalid_Encoding);
            }
            ReadIvParameter(encryptionScheme.Parameters, 8, ref iv);
            return DES.Create();
        default:
            throw new CryptographicException(System.SR.Cryptography_UnknownAlgorithmIdentifier, algorithm);
        }
    }
References System.Security.Cryptography.Aes.Create(), System.Security.Cryptography.DES.Create(), System.Security.Cryptography.TripleDES.Create(), System.Security.Cryptography.PasswordBasedEncryption.CreateRC2(), System.SR.Cryptography_Der_Invalid_Encoding, System.SR.Cryptography_UnknownAlgorithmIdentifier, System.Security.Cryptography.Asn1.Rc2CbcParameters.Decode(), System.Security.Cryptography.Asn1.Rc2CbcParameters.GetEffectiveKeyBits(), System.Security.Cryptography.Asn1.Rc2CbcParameters.Iv, System.ReadOnlyMemory< T >.Length, System.Security.Cryptography.PasswordBasedEncryption.ReadIvParameter(), and System.ReadOnlyMemory< T >.Span.