Terraria: System.Security.Cryptography.PasswordBasedEncryption.Pbes2Decrypt
Pbes2Decrypt() [2/4]
static unsafe int System.Security.Cryptography.PasswordBasedEncryption.Pbes2Decrypt (ReadOnlyMemory< byte >? algorithmParameters, ReadOnlySpan< byte > password, ReadOnlySpan< byte > encryptedData, Span< byte > destination) inline static private
Definition at line 324 of file PasswordBasedEncryption.cs.
    {
        if (!algorithmParameters.HasValue)
        {
            throw new CryptographicException(System.SR.Cryptography_Der_Invalid_Encoding);
        }
        System.Security.Cryptography.Asn1.PBES2Params pBES2Params = System.Security.Cryptography.Asn1.PBES2Params.Decode(algorithmParameters.Value, AsnEncodingRules.BER);
        if (pBES2Params.KeyDerivationFunc.Algorithm != "1.2.840.113549.1.5.12")
        {
            throw new CryptographicException(System.SR.Format(System.SR.Cryptography_UnknownAlgorithmIdentifier, pBES2Params.EncryptionScheme.Algorithm));
        }
        int? requestedKeyLength;
        Rfc2898DeriveBytes rfc2898DeriveBytes = OpenPbkdf2(password, pBES2Params.KeyDerivationFunc.Parameters, out requestedKeyLength);
        using (rfc2898DeriveBytes)
        {
            Span<byte> iv = stackalloc byte[16];
            SymmetricAlgorithm symmetricAlgorithm = OpenCipher(pBES2Params.EncryptionScheme, requestedKeyLength, ref iv);
            using (symmetricAlgorithm)
            {
                byte[] bytes = rfc2898DeriveBytes.GetBytes(symmetricAlgorithm.KeySize / 8);
                fixed (byte* ptr = bytes)
                {
                    try
                    {
                        return Decrypt(symmetricAlgorithm, bytes, iv, encryptedData, destination);
                    }
                    finally
                    {
                        CryptographicOperations.ZeroMemory(bytes);
                    }
                }
            }
        }
    }
References System.Security.Cryptography.Asn1.AlgorithmIdentifierAsn.Algorithm, System.bytes, System.SR.Cryptography_Der_Invalid_Encoding, System.SR.Cryptography_UnknownAlgorithmIdentifier, System.Security.Cryptography.Asn1.PBES2Params.Decode(), System.Security.Cryptography.PasswordBasedEncryption.Decrypt(), System.destination, System.Security.Cryptography.Asn1.PBES2Params.EncryptionScheme, System.SR.Format(), System.Security.Cryptography.Rfc2898DeriveBytes.GetBytes(), System.Security.Cryptography.Asn1.PBES2Params.KeyDerivationFunc, System.Security.Cryptography.SymmetricAlgorithm.KeySize, System.Security.Cryptography.PasswordBasedEncryption.OpenCipher(), System.Security.Cryptography.PasswordBasedEncryption.OpenPbkdf2(), System.Security.Cryptography.Asn1.AlgorithmIdentifierAsn.Parameters, and System.Security.Cryptography.CryptographicOperations.ZeroMemory().