Terraria: System.Runtime.Serialization.BitFlagsGenerator.Store
Store()
void System.Runtime.Serialization.BitFlagsGenerator.Store (int bitIndex, bool value) inline
Definition at line 77 of file BitFlagsGenerator.cs.
    {
        LocalBuilder localBuilder = _locals[GetByteIndex(bitIndex)];
        byte bitValue = GetBitValue(bitIndex);
        if (value)
        {
            _ilg.Load(localBuilder);
            _ilg.Load(bitValue);
            _ilg.Or();
            _ilg.Stloc(localBuilder);
        }
        else
        {
            _ilg.Load(localBuilder);
            _ilg.Load(bitValue);
            _ilg.Not();
            _ilg.And();
            _ilg.Stloc(localBuilder);
        }
    }
References System.Runtime.Serialization.BitFlagsGenerator._ilg, System.Runtime.Serialization.BitFlagsGenerator._locals, System.Runtime.Serialization.CodeGenerator.And(), System.Runtime.Serialization.Dictionary, System.Runtime.Serialization.BitFlagsGenerator.GetBitValue(), System.Runtime.Serialization.BitFlagsGenerator.GetByteIndex(), System.Runtime.Serialization.CodeGenerator.Load(), System.Runtime.Serialization.CodeGenerator.Not(), System.Runtime.Serialization.CodeGenerator.Or(), System.Runtime.Serialization.CodeGenerator.Stloc(), and System.value.