Terraria: System.Runtime.Serialization.BitFlagsGenerator.LoadArray
LoadArray()
void System.Runtime.Serialization.BitFlagsGenerator.LoadArray () inline
Definition at line 65 of file BitFlagsGenerator.cs.
    {
        LocalBuilder localBuilder = _ilg.DeclareLocal(Globals.TypeOfByteArray, "localArray");
        _ilg.NewArray(typeof(byte), _locals.Length);
        _ilg.Store(localBuilder);
        for (int i = 0; i < _locals.Length; i++)
        {
            _ilg.StoreArrayElement(localBuilder, i, _locals[i]);
        }
        _ilg.Load(localBuilder);
    }
References System.Runtime.Serialization.BitFlagsGenerator._ilg, System.Runtime.Serialization.BitFlagsGenerator._locals, System.Runtime.Serialization.CodeGenerator.DeclareLocal(), System.Runtime.Serialization.Dictionary, System.Runtime.Serialization.CodeGenerator.Load(), System.Runtime.Serialization.CodeGenerator.NewArray(), System.Runtime.Serialization.CodeGenerator.Store(), System.Runtime.Serialization.CodeGenerator.StoreArrayElement(), and System.Runtime.Serialization.Globals.TypeOfByteArray.