Terraria: System.Reflection.Metadata.Ecma335.SignatureTypeEncoder.FunctionPointer
FunctionPointer()
MethodSignatureEncoder System.Reflection.Metadata.Ecma335.SignatureTypeEncoder.FunctionPointer (SignatureCallingConvention convention = SignatureCallingConvention::Default, FunctionPointerAttributes attributes = FunctionPointerAttributes::None, int genericParameterCount = 0) inline
Definition at line 159 of file SignatureTypeEncoder.cs.
    {
        if (attributes != 0 && attributes != FunctionPointerAttributes.HasThis && attributes != FunctionPointerAttributes.HasExplicitThis)
        {
            throw new ArgumentException(System.SR.InvalidSignature, "attributes");
        }
        if ((uint)genericParameterCount > 65535u)
        {
            Throw.ArgumentOutOfRange("genericParameterCount");
        }
        Builder.WriteByte(27);
        Builder.WriteByte(new SignatureHeader(SignatureKind.Method, convention, (SignatureAttributes)attributes).RawValue);
        if (genericParameterCount != 0)
        {
            Builder.WriteCompressedInteger(genericParameterCount);
        }
        return new MethodSignatureEncoder(Builder, convention == SignatureCallingConvention.VarArgs);
    }
References System.Reflection.Throw.ArgumentOutOfRange(), System.Reflection.Metadata.Ecma335.SignatureTypeEncoder.Builder, System.SR.InvalidSignature, System.Reflection.Metadata.SignatureHeader.RawValue, System.Reflection.Metadata.BlobBuilder.WriteByte(), and System.Reflection.Metadata.BlobBuilder.WriteCompressedInteger().