Terraria: System.Reflection.Metadata.Ecma335.SignatureTypeEncoder.WriteTypeCode
WriteTypeCode()
void System.Reflection.Metadata.Ecma335.SignatureTypeEncoder.WriteTypeCode (SignatureTypeCode value) inline private
Definition at line 12 of file SignatureTypeEncoder.cs.
    {
        Builder.WriteByte((byte)value);
    }
References System.Reflection.Metadata.Ecma335.SignatureTypeEncoder.Builder, System.value, and System.Reflection.Metadata.BlobBuilder.WriteByte().
Referenced by System.Reflection.Metadata.Ecma335.SignatureTypeEncoder.Boolean(), System.Reflection.Metadata.Ecma335.SignatureTypeEncoder.Byte(), System.Reflection.Metadata.Ecma335.SignatureTypeEncoder.Char(), System.Reflection.Metadata.Ecma335.SignatureTypeEncoder.Double(), System.Reflection.Metadata.Ecma335.SignatureTypeEncoder.Int16(), System.Reflection.Metadata.Ecma335.SignatureTypeEncoder.Int32(), System.Reflection.Metadata.Ecma335.SignatureTypeEncoder.Int64(), System.Reflection.Metadata.Ecma335.SignatureTypeEncoder.IntPtr(), System.Reflection.Metadata.Ecma335.SignatureTypeEncoder.Object(), System.Reflection.Metadata.Ecma335.SignatureTypeEncoder.SByte(), System.Reflection.Metadata.Ecma335.SignatureTypeEncoder.Single(), System.Reflection.Metadata.Ecma335.SignatureTypeEncoder.String(), System.Reflection.Metadata.Ecma335.SignatureTypeEncoder.UInt16(), System.Reflection.Metadata.Ecma335.SignatureTypeEncoder.UInt32(), System.Reflection.Metadata.Ecma335.SignatureTypeEncoder.UInt64(), and System.Reflection.Metadata.Ecma335.SignatureTypeEncoder.UIntPtr().