Terraria: Terraria.ID.TileID.Sets.Conversion.Sand
Sand
bool [] Terraria.ID.TileID.Sets.Conversion.Sand = Factory.CreateBoolSet(53, 112, 116, 234) static
Referenced by Terraria.NPC.AI(), Terraria.WorldGen.CanUnderwaterPlantGrowHere(), Terraria.WorldGen.Check2x1(), Terraria.WorldGen.Check3x2(), Terraria.WorldGen.CheckOasisPlant(), Terraria.WorldGen.CheckPile(), Terraria.WorldGen.Convert(), Terraria.Player.FloorVisuals(), Terraria.WorldGen.OrePatch(), Terraria.WorldGen.PlaceOasisPlant(), Terraria.WorldGen.PlantSeaOat(), Terraria.NPC.Spawning_SandstoneCheck(), Terraria.NPC.SpawnNPC(), Terraria.WorldGen.StonePatch(), Terraria.WorldGen.TileFrame(), Terraria.WorldGen.TryKillingTreesAboveIfTheyWouldBecomeInvalid(), and Terraria.WorldGen.UpdateWorld_OvergroundTile().