Terraria: System.ComponentModel.ReflectPropertyDescriptor.ExtenderResetValue
ExtenderResetValue()
void System.ComponentModel.ReflectPropertyDescriptor.ExtenderResetValue (IExtenderProvider provider, object component, PropertyDescriptor notifyDesc) inline package
Definition at line 443 of file ReflectPropertyDescriptor.cs.
    {
        if (DefaultValue != s_noValue)
        {
            ExtenderSetValue(provider, component, DefaultValue, notifyDesc);
        }
        else if (AmbientValue != s_noValue)
        {
            ExtenderSetValue(provider, component, AmbientValue, notifyDesc);
        }
        else
        {
            if (!(ResetMethodValue != null))
            {
                return;
            }
            ISite site = MemberDescriptor.GetSite(component);
            IComponentChangeService componentChangeService = null;
            object oldValue = null;
            if (site != null)
            {
                componentChangeService = (IComponentChangeService)site.GetService(typeof(IComponentChangeService));
            }
            if (componentChangeService != null)
            {
                oldValue = ExtenderGetValue(provider, component);
                try
                {
                    componentChangeService.OnComponentChanging(component, notifyDesc);
                }
                catch (CheckoutException ex)
                {
                    if (ex == CheckoutException.Canceled)
                    {
                        return;
                    }
                    throw;
                }
            }
            IExtenderProvider extenderProvider = (IExtenderProvider)GetInvocationTarget(_componentClass, provider);
            if (ResetMethodValue != null)
            {
                ResetMethodValue.Invoke(extenderProvider, new object[1] { component });
                if (componentChangeService != null)
                {
                    object newValue = ExtenderGetValue(extenderProvider, component);
                    componentChangeService.OnComponentChanged(component, notifyDesc, oldValue, newValue);
                }
            }
        }
    }
References System.ComponentModel.ReflectPropertyDescriptor._componentClass, System.ComponentModel.ReflectPropertyDescriptor.AmbientValue, System.ComponentModel.Design.CheckoutException.Canceled, System.ComponentModel.ReflectPropertyDescriptor.DefaultValue, System.ComponentModel.ReflectPropertyDescriptor.ExtenderGetValue(), System.ComponentModel.ReflectPropertyDescriptor.ExtenderSetValue(), System.ComponentModel.PropertyDescriptor.GetInvocationTarget(), System.IServiceProvider.GetService(), System.ComponentModel.MemberDescriptor.GetSite(), System.Reflection.MethodBase.Invoke(), System.ComponentModel.Design.IComponentChangeService.OnComponentChanged(), System.ComponentModel.Design.IComponentChangeService.OnComponentChanging(), System.ComponentModel.ReflectPropertyDescriptor.ResetMethodValue, and System.ComponentModel.ReflectPropertyDescriptor.s_noValue.
Referenced by System.ComponentModel.ExtendedPropertyDescriptor.ResetValue().