Terraria: System.ComponentModel.ReflectPropertyDescriptor.SetValue
SetValue() [1/2]
override void System.ComponentModel.ReflectPropertyDescriptor.SetValue (object component, object value) inline
Definition at line 823 of file ReflectPropertyDescriptor.cs.
    {
        if (component == null)
        {
            return;
        }
        ISite site = MemberDescriptor.GetSite(component);
        object obj = null;
        object invocationTarget = GetInvocationTarget(_componentClass, component);
        if (IsReadOnly)
        {
            return;
        }
        IComponentChangeService componentChangeService = null;
        if (site != null)
        {
            componentChangeService = (IComponentChangeService)site.GetService(typeof(IComponentChangeService));
        }
        if (componentChangeService != null)
        {
            obj = GetMethodValue.Invoke(invocationTarget, null);
            try
            {
                componentChangeService.OnComponentChanging(component, this);
            }
            catch (CheckoutException ex)
            {
                if (ex == CheckoutException.Canceled)
                {
                    return;
                }
                throw;
            }
        }
        try
        {
            SetMethodValue.Invoke(invocationTarget, new object[1] { value });
            OnValueChanged(invocationTarget, EventArgs.Empty);
        }
        catch (Exception ex2)
        {
            value = obj;
            if (ex2 is TargetInvocationException && ex2.InnerException != null)
            {
                throw ex2.InnerException;
            }
            throw;
        }
        finally
        {
            componentChangeService?.OnComponentChanged(component, this, obj, value);
        }
    }
References System.ComponentModel.Design.CheckoutException.Canceled, System.EventArgs.Empty, System.IServiceProvider.GetService(), System.ComponentModel.MemberDescriptor.GetSite(), System.Exception.InnerException, System.obj, System.ComponentModel.Design.IComponentChangeService.OnComponentChanged(), System.ComponentModel.Design.IComponentChangeService.OnComponentChanging(), and System.value.