Terraria: System.ComponentModel.ReflectPropertyDescriptor.ResetValue
ResetValue()
override void System.ComponentModel.ReflectPropertyDescriptor.ResetValue (object component) inline
Definition at line 771 of file ReflectPropertyDescriptor.cs.
    {
        object invocationTarget = GetInvocationTarget(_componentClass, component);
        if (DefaultValue != s_noValue)
        {
            SetValue(component, DefaultValue);
        }
        else if (AmbientValue != s_noValue)
        {
            SetValue(component, AmbientValue);
        }
        else
        {
            if (!(ResetMethodValue != null))
            {
                return;
            }
            ISite site = MemberDescriptor.GetSite(component);
            IComponentChangeService componentChangeService = null;
            object oldValue = null;
            if (site != null)
            {
                componentChangeService = (IComponentChangeService)site.GetService(typeof(IComponentChangeService));
            }
            if (componentChangeService != null)
            {
                oldValue = GetMethodValue.Invoke(invocationTarget, null);
                try
                {
                    componentChangeService.OnComponentChanging(component, this);
                }
                catch (CheckoutException ex)
                {
                    if (ex == CheckoutException.Canceled)
                    {
                        return;
                    }
                    throw;
                }
            }
            if (ResetMethodValue != null)
            {
                ResetMethodValue.Invoke(invocationTarget, null);
                if (componentChangeService != null)
                {
                    object newValue = GetMethodValue.Invoke(invocationTarget, null);
                    componentChangeService.OnComponentChanged(component, this, oldValue, newValue);
                }
            }
        }
    }
References System.ComponentModel.Design.CheckoutException.Canceled, System.IServiceProvider.GetService(), System.ComponentModel.MemberDescriptor.GetSite(), System.ComponentModel.Design.IComponentChangeService.OnComponentChanged(), and System.ComponentModel.Design.IComponentChangeService.OnComponentChanging().