Terraria: System.ComponentModel.ReflectPropertyDescriptor.ExtenderCanResetValue
ExtenderCanResetValue()
bool System.ComponentModel.ReflectPropertyDescriptor.ExtenderCanResetValue (IExtenderProvider provider, object component) inline package
Definition at line 397 of file ReflectPropertyDescriptor.cs.
    {
        if (DefaultValue != s_noValue)
        {
            return !object.Equals(ExtenderGetValue(provider, component), _defaultValue);
        }
        MethodInfo resetMethodValue = ResetMethodValue;
        if (resetMethodValue != null)
        {
            MethodInfo shouldSerializeMethodValue = ShouldSerializeMethodValue;
            if (shouldSerializeMethodValue != null)
            {
                try
                {
                    IExtenderProvider obj = (IExtenderProvider)GetInvocationTarget(_componentClass, provider);
                    return (bool)shouldSerializeMethodValue.Invoke(obj, new object[1] { component });
                }
                catch
                {
                }
            }
            return true;
        }
        return false;
    }
References System.ComponentModel.ReflectPropertyDescriptor._componentClass, System.ComponentModel.ReflectPropertyDescriptor._defaultValue, System.ComponentModel.ReflectPropertyDescriptor.DefaultValue, System.ComponentModel.ReflectPropertyDescriptor.ExtenderGetValue(), System.ComponentModel.PropertyDescriptor.GetInvocationTarget(), System.Reflection.MethodBase.Invoke(), System.obj, System.ComponentModel.ReflectPropertyDescriptor.ResetMethodValue, System.ComponentModel.ReflectPropertyDescriptor.s_noValue, and System.ComponentModel.ReflectPropertyDescriptor.ShouldSerializeMethodValue.
Referenced by System.ComponentModel.ExtendedPropertyDescriptor.CanResetValue().