Terraria: System.ComponentModel.ReflectPropertyDescriptor.ExtenderShouldSerializeValue
ExtenderShouldSerializeValue()
bool System.ComponentModel.ReflectPropertyDescriptor.ExtenderShouldSerializeValue (IExtenderProvider provider, object component) inline package
Definition at line 532 of file ReflectPropertyDescriptor.cs.
    {
        IExtenderProvider extenderProvider = (IExtenderProvider)GetInvocationTarget(_componentClass, provider);
        if (IsReadOnly)
        {
            if (ShouldSerializeMethodValue != null)
            {
                try
                {
                    return (bool)ShouldSerializeMethodValue.Invoke(extenderProvider, new object[1] { component });
                }
                catch
                {
                }
            }
            return AttributesContainsDesignerVisibilityContent();
        }
        if (DefaultValue == s_noValue)
        {
            if (ShouldSerializeMethodValue != null)
            {
                try
                {
                    return (bool)ShouldSerializeMethodValue.Invoke(extenderProvider, new object[1] { component });
                }
                catch
                {
                }
            }
            return true;
        }
        return !object.Equals(DefaultValue, ExtenderGetValue(extenderProvider, component));
    }
References System.ComponentModel.ReflectPropertyDescriptor._componentClass, System.ComponentModel.ReflectPropertyDescriptor.AttributesContainsDesignerVisibilityContent(), System.ComponentModel.ReflectPropertyDescriptor.DefaultValue, System.ComponentModel.ReflectPropertyDescriptor.ExtenderGetValue(), System.ComponentModel.PropertyDescriptor.GetInvocationTarget(), System.Reflection.MethodBase.Invoke(), System.ComponentModel.ReflectPropertyDescriptor.IsReadOnly, System.ComponentModel.ReflectPropertyDescriptor.s_noValue, and System.ComponentModel.ReflectPropertyDescriptor.ShouldSerializeMethodValue.
Referenced by System.ComponentModel.ExtendedPropertyDescriptor.ShouldSerializeValue().