Terraria: System.ComponentModel.ReflectPropertyDescriptor.ReflectPropertyDescriptor
ReflectPropertyDescriptor() [4/4]
System.ComponentModel.ReflectPropertyDescriptor.ReflectPropertyDescriptor ([DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.All)] Type componentClass, PropertyDescriptor oldReflectPropertyDescriptor, Attribute[] attributes) inline
Definition at line 327 of file ReflectPropertyDescriptor.cs.
        : base(oldReflectPropertyDescriptor, attributes)
    {
        _componentClass = componentClass;
        _type = oldReflectPropertyDescriptor.PropertyType;
        if (componentClass == null)
        {
            throw new ArgumentException(System.SR.Format(System.SR.InvalidNullArgument, "componentClass"));
        }
        if (!(oldReflectPropertyDescriptor is ReflectPropertyDescriptor reflectPropertyDescriptor))
        {
            return;
        }
        if (reflectPropertyDescriptor.ComponentType == componentClass)
        {
            _propInfo = reflectPropertyDescriptor._propInfo;
            _getMethod = reflectPropertyDescriptor._getMethod;
            _setMethod = reflectPropertyDescriptor._setMethod;
            _shouldSerializeMethod = reflectPropertyDescriptor._shouldSerializeMethod;
            _resetMethod = reflectPropertyDescriptor._resetMethod;
            _defaultValue = reflectPropertyDescriptor._defaultValue;
            _ambientValue = reflectPropertyDescriptor._ambientValue;
            _state = reflectPropertyDescriptor._state;
        }
        if (attributes == null)
        {
            return;
        }
        foreach (Attribute attribute in attributes)
        {
            if (attribute is DefaultValueAttribute defaultValueAttribute)
            {
                _defaultValue = defaultValueAttribute.Value;
                if (_defaultValue != null && PropertyType.IsEnum && PropertyType.GetEnumUnderlyingType() == _defaultValue.GetType())
                {
                    _defaultValue = Enum.ToObject(PropertyType, _defaultValue);
                }
                _state.DangerousSet(s_bitDefaultValueQueried, value: true);
            }
            else if (attribute is AmbientValueAttribute ambientValueAttribute)
            {
                _ambientValue = ambientValueAttribute.Value;
                _state.DangerousSet(s_bitAmbientValueQueried, value: true);
            }
        }
    }
References System.ComponentModel.ReflectPropertyDescriptor._ambientValue, System.ComponentModel.ReflectPropertyDescriptor._componentClass, System.ComponentModel.ReflectPropertyDescriptor._defaultValue, System.ComponentModel.ReflectPropertyDescriptor._getMethod, System.ComponentModel.ReflectPropertyDescriptor._propInfo, System.ComponentModel.ReflectPropertyDescriptor._resetMethod, System.ComponentModel.ReflectPropertyDescriptor._setMethod, System.ComponentModel.ReflectPropertyDescriptor._shouldSerializeMethod, System.ComponentModel.ReflectPropertyDescriptor._state, System.ComponentModel.ReflectPropertyDescriptor._type, System.ComponentModel.InterlockedBitVector32.DangerousSet(), System.SR.Format(), System.Type.GetEnumUnderlyingType(), System.SR.InvalidNullArgument, System.Type.IsEnum, System.ComponentModel.PropertyDescriptor.PropertyType, System.ComponentModel.ReflectPropertyDescriptor.PropertyType, System.ComponentModel.ReflectPropertyDescriptor.s_bitAmbientValueQueried, System.ComponentModel.ReflectPropertyDescriptor.s_bitDefaultValueQueried, System.Enum.ToObject(), and System.value.