Terraria: System.ComponentModel.ReflectPropertyDescriptor.RemoveValueChanged
RemoveValueChanged()
override void System.ComponentModel.ReflectPropertyDescriptor.RemoveValueChanged (object component, EventHandler handler) inline virtual
Reimplemented from System.ComponentModel.PropertyDescriptor.
Definition at line 748 of file ReflectPropertyDescriptor.cs.
    {
        if (component == null)
        {
            throw new ArgumentNullException("component");
        }
        if (handler == null)
        {
            throw new ArgumentNullException("handler");
        }
        EventDescriptor changedEventValue = ChangedEventValue;
        if (changedEventValue != null && changedEventValue.EventType.IsInstanceOfType(handler))
        {
            changedEventValue.RemoveEventHandler(component, handler);
            return;
        }
        base.RemoveValueChanged(component, handler);
        if (GetValueChangedHandler(component) == null)
        {
            IPropChangedEventValue?.RemoveEventHandler(component, new PropertyChangedEventHandler(OnINotifyPropertyChanged));
        }
    }
References System.ComponentModel.EventDescriptor.EventType, System.Type.IsInstanceOfType(), System.ComponentModel.PropertyChangedEventHandler(), and System.ComponentModel.EventDescriptor.RemoveEventHandler().