Terraria: System.ComponentModel.ReflectPropertyDescriptor.ExtenderSetValue
ExtenderSetValue()
void System.ComponentModel.ReflectPropertyDescriptor.ExtenderSetValue (IExtenderProvider provider, object component, object value, PropertyDescriptor notifyDesc) inline package
Definition at line 495 of file ReflectPropertyDescriptor.cs.
    {
        if (provider == null)
        {
            return;
        }
        ISite site = MemberDescriptor.GetSite(component);
        IComponentChangeService componentChangeService = null;
        object oldValue = null;
        if (site != null)
        {
            componentChangeService = (IComponentChangeService)site.GetService(typeof(IComponentChangeService));
        }
        if (componentChangeService != null)
        {
            oldValue = ExtenderGetValue(provider, component);
            try
            {
                componentChangeService.OnComponentChanging(component, notifyDesc);
            }
            catch (CheckoutException ex)
            {
                if (ex == CheckoutException.Canceled)
                {
                    return;
                }
                throw;
            }
        }
        IExtenderProvider obj = (IExtenderProvider)GetInvocationTarget(_componentClass, provider);
        if (SetMethodValue != null)
        {
            SetMethodValue.Invoke(obj, new object[2] { component, value });
            componentChangeService?.OnComponentChanged(component, notifyDesc, oldValue, value);
        }
    }
References System.ComponentModel.ReflectPropertyDescriptor._componentClass, System.ComponentModel.Design.CheckoutException.Canceled, System.ComponentModel.ReflectPropertyDescriptor.ExtenderGetValue(), System.ComponentModel.PropertyDescriptor.GetInvocationTarget(), System.IServiceProvider.GetService(), System.ComponentModel.MemberDescriptor.GetSite(), System.Reflection.MethodBase.Invoke(), System.obj, System.ComponentModel.Design.IComponentChangeService.OnComponentChanged(), System.ComponentModel.Design.IComponentChangeService.OnComponentChanging(), System.ComponentModel.ReflectPropertyDescriptor.SetMethodValue, and System.value.
Referenced by System.ComponentModel.ReflectPropertyDescriptor.ExtenderResetValue(), and System.ComponentModel.ExtendedPropertyDescriptor.SetValue().