Terraria: Terraria.GameContent.UI.Elements.UIColoredImageButton.DrawSelf
DrawSelf()
override void Terraria.GameContent.UI.Elements.UIColoredImageButton.DrawSelf (SpriteBatch spriteBatch) inline protected virtual
Reimplemented from Terraria.UI.UIElement.
Definition at line 68 of file UIColoredImageButton.cs.
    {
        CalculatedStyle dimensions = GetDimensions();
        Vector2 position = dimensions.Position() + new Vector2(dimensions.Width, dimensions.Height) / 2f;
        spriteBatch.Draw(_backPanelTexture.Value, position, null, Color.White * (base.IsMouseHovering ? _visibilityActive : _visibilityInactive), 0f, _backPanelTexture.Size() / 2f, 1f, SpriteEffects.None, 0f);
        _ = Color.White;
        if (_hovered)
        {
            spriteBatch.Draw(_backPanelBorderTexture.Value, position, null, Color.White, 0f, _backPanelBorderTexture.Size() / 2f, 1f, SpriteEffects.None, 0f);
        }
        if (_selected)
        {
            spriteBatch.Draw(_backPanelHighlightTexture.Value, position, null, Color.White, 0f, _backPanelHighlightTexture.Size() / 2f, 1f, SpriteEffects.None, 0f);
        }
        if (_middleTexture != null)
        {
            spriteBatch.Draw(_middleTexture.Value, position, null, Color.White, 0f, _middleTexture.Size() / 2f, 1f, SpriteEffects.None, 0f);
        }
        spriteBatch.Draw(_texture.Value, position, null, _color, 0f, _texture.Size() / 2f, 1f, SpriteEffects.None, 0f);
    }
References Terraria.GameContent.UI.Elements.UIColoredImageButton._backPanelBorderTexture, Terraria.GameContent.UI.Elements.UIColoredImageButton._backPanelHighlightTexture, Terraria.GameContent.UI.Elements.UIColoredImageButton._backPanelTexture, Terraria.GameContent.UI.Elements.UIColoredImageButton._color, Terraria.GameContent.UI.Elements.UIColoredImageButton._hovered, Terraria.GameContent.UI.Elements.UIColoredImageButton._middleTexture, Terraria.GameContent.UI.Elements.UIColoredImageButton._selected, Terraria.GameContent.UI.Elements.UIColoredImageButton._texture, Terraria.GameContent.UI.Elements.UIColoredImageButton._visibilityActive, Terraria.GameContent.UI.Elements.UIColoredImageButton._visibilityInactive, Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(), Terraria.UI.UIElement.GetDimensions(), Terraria.UI.CalculatedStyle.Height, Terraria.UI.CalculatedStyle.Position(), ReLogic.Content.Asset< T >.Value, Microsoft.Xna.Framework.Graphics.Vector2, Microsoft.Xna.Framework.Color.White, and Terraria.UI.CalculatedStyle.Width.