Terraria: System.ComponentModel.ReflectPropertyDescriptor.AddValueChanged
AddValueChanged()
override void System.ComponentModel.ReflectPropertyDescriptor.AddValueChanged (object component, EventHandler handler) inline virtual
Reimplemented from System.ComponentModel.PropertyDescriptor.
Definition at line 374 of file ReflectPropertyDescriptor.cs.
    {
        if (component == null)
        {
            throw new ArgumentNullException("component");
        }
        if (handler == null)
        {
            throw new ArgumentNullException("handler");
        }
        EventDescriptor changedEventValue = ChangedEventValue;
        if (changedEventValue != null && changedEventValue.EventType.IsInstanceOfType(handler))
        {
            changedEventValue.AddEventHandler(component, handler);
            return;
        }
        if (GetValueChangedHandler(component) == null)
        {
            IPropChangedEventValue?.AddEventHandler(component, new PropertyChangedEventHandler(OnINotifyPropertyChanged));
        }
        base.AddValueChanged(component, handler);
    }
References System.ComponentModel.EventDescriptor.AddEventHandler(), System.ComponentModel.ReflectPropertyDescriptor.ChangedEventValue, System.ComponentModel.EventDescriptor.EventType, System.ComponentModel.PropertyDescriptor.GetValueChangedHandler(), System.ComponentModel.ReflectPropertyDescriptor.IPropChangedEventValue, System.Type.IsInstanceOfType(), System.ComponentModel.ReflectPropertyDescriptor.OnINotifyPropertyChanged(), and System.ComponentModel.PropertyChangedEventHandler().