Terraria: System.ComponentModel.ReflectPropertyDescriptor.GetValue
GetValue() [1/2]
override object System.ComponentModel.ReflectPropertyDescriptor.GetValue (object component) inline
Definition at line 696 of file ReflectPropertyDescriptor.cs.
    {
        if (IsExtender)
        {
            return null;
        }
        if (component != null)
        {
            component = GetInvocationTarget(_componentClass, component);
            try
            {
                return GetMethodValue.Invoke(component, null);
            }
            catch (Exception innerException)
            {
                string text = null;
                ISite site = ((component is IComponent component2) ? component2.Site : null);
                if (site != null && site.Name != null)
                {
                    text = site.Name;
                }
                if (text == null)
                {
                    text = component.GetType().FullName;
                }
                if (innerException is TargetInvocationException)
                {
                    innerException = innerException.InnerException;
                }
                string p = innerException.Message ?? innerException.GetType().Name;
                throw new TargetInvocationException(System.SR.Format(System.SR.ErrorPropertyAccessorException, Name, text, p), innerException);
            }
        }
        return null;
    }
References System.SR.ErrorPropertyAccessorException, System.SR.Format(), System.Exception.GetType(), System.Exception.InnerException, System.ComponentModel.ISite.Name, System.Reflection.MemberInfo.Name, System.Name, and System.text.
Referenced by System.ComponentModel.ReflectPropertyDescriptor.CanResetValue().