Terraria: System.ComponentModel.ReflectPropertyDescriptor.FillAttributes
FillAttributes() [2/2]
override void System.ComponentModel.ReflectPropertyDescriptor.FillAttributes (IList attributes) inline protected
Definition at line 606 of file ReflectPropertyDescriptor.cs.
    {
        foreach (Attribute attribute2 in TypeDescriptor.GetAttributes(PropertyType))
        {
            attributes.Add(attribute2);
        }
        Type type = _componentClass;
        int num = 0;
        while (type != null && type != typeof(object))
        {
            num++;
            type = type.BaseType;
        }
        if (num > 0)
        {
            type = _componentClass;
            Attribute[][] array = new Attribute[num][];
            while (type != null && type != typeof(object))
            {
                MemberInfo memberInfo = null;
                BindingFlags bindingAttr = BindingFlags.DeclaredOnly | BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic;
                memberInfo = ((!IsExtender) ? ((MemberInfo)type.GetProperty(Name, bindingAttr, null, PropertyType, Type.EmptyTypes, Array.Empty<ParameterModifier>())) : ((MemberInfo)type.GetMethod("Get" + Name, bindingAttr, null, new Type[1] { _receiverType }, null)));
                if (memberInfo != null)
                {
                    array[--num] = ReflectTypeDescriptionProvider.ReflectGetAttributes(memberInfo);
                }
                type = type.BaseType;
            }
            Attribute[][] array2 = array;
            foreach (Attribute[] array3 in array2)
            {
                if (array3 == null)
                {
                    continue;
                }
                Attribute[] array4 = array3;
                foreach (Attribute attribute in array4)
                {
                    if (!(attribute is AttributeProviderAttribute attributeProviderAttribute))
                    {
                        continue;
                    }
                    Type type2 = Type.GetType(attributeProviderAttribute.TypeName);
                    if (!(type2 != null))
                    {
                        continue;
                    }
                    Attribute[] array5 = null;
                    if (!string.IsNullOrEmpty(attributeProviderAttribute.PropertyName))
                    {
                        MemberInfo[] member = type2.GetMember(attributeProviderAttribute.PropertyName);
                        if (member.Length != 0 && member[0] != null)
{
                            array5 = ReflectTypeDescriptionProvider.ReflectGetAttributes(member[0]);
                        }
                    }
                    else
                    {
                        array5 = ReflectTypeDescriptionProvider.ReflectGetAttributes(type2);
                    }
                    if (array5 != null)
                    {
                        Attribute[] array6 = array5;
                        foreach (Attribute value2 in array6)
{
                            attributes.Add(value2);
                        }
                    }
                }
            }
            Attribute[][] array7 = array;
            foreach (Attribute[] array8 in array7)
            {
                if (array8 != null)
                {
                    Attribute[] array9 = array8;
                    foreach (Attribute value3 in array9)
                    {
                        attributes.Add(value3);
                    }
                }
            }
        }
        base.FillAttributes(attributes);
        if (SetMethodValue == null)
        {
            attributes.Add(ReadOnlyAttribute.Yes);
        }
    }
References System.ComponentModel.ReflectPropertyDescriptor._componentClass, System.ComponentModel.ReflectPropertyDescriptor._receiverType, System.array, System.Type.EmptyTypes, System.ComponentModel.TypeDescriptor.GetAttributes(), System.Type.GetMember(), System.Type.GetType(), System.ComponentModel.ReflectPropertyDescriptor.IsExtender, System.ComponentModel.MemberDescriptor.Name, System.ComponentModel.ReflectPropertyDescriptor.PropertyType, System.ComponentModel.ReflectTypeDescriptionProvider.ReflectGetAttributes(), and System.type.