Terraria: FancyClassicPlayerResourcesDisplaySet.DrawLifeBar
DrawLifeBar()
void FancyClassicPlayerResourcesDisplaySet.DrawLifeBar (SpriteBatch spriteBatch) inline private
     {
         Vector2 vector = new Vector2(Main.screenWidth - 300 + 4, 15f);
         if (_drawText)
         {
             vector.Y += 6f;
             DrawLifeBarText(spriteBatch, vector + new Vector2(-4f, 3f));
         }
         bool isHovered = false;
         ResourceDrawSettings resourceDrawSettings = default(ResourceDrawSettings);
         resourceDrawSettings.ElementCount = _heartCountRow1;
         resourceDrawSettings.ElementIndexOffset = 0;
         resourceDrawSettings.TopLeftAnchor = vector;
         resourceDrawSettings.GetTextureMethod = HeartPanelDrawer;
         resourceDrawSettings.OffsetPerDraw = Vector2.Zero;
         resourceDrawSettings.OffsetPerDrawByTexturePercentile = Vector2.UnitX;
         resourceDrawSettings.OffsetSpriteAnchor = Vector2.Zero;
         resourceDrawSettings.OffsetSpriteAnchorByTexturePercentile = Vector2.Zero;
         resourceDrawSettings.Draw(spriteBatch, ref isHovered);
         resourceDrawSettings = default(ResourceDrawSettings);
         resourceDrawSettings.ElementCount = _heartCountRow2;
         resourceDrawSettings.ElementIndexOffset = 10;
         resourceDrawSettings.TopLeftAnchor = vector + new Vector2(0f, 28f);
         resourceDrawSettings.GetTextureMethod = HeartPanelDrawer;
         resourceDrawSettings.OffsetPerDraw = Vector2.Zero;
         resourceDrawSettings.OffsetPerDrawByTexturePercentile = Vector2.UnitX;
         resourceDrawSettings.OffsetSpriteAnchor = Vector2.Zero;
         resourceDrawSettings.OffsetSpriteAnchorByTexturePercentile = Vector2.Zero;
         resourceDrawSettings.Draw(spriteBatch, ref isHovered);
         resourceDrawSettings = default(ResourceDrawSettings);
         resourceDrawSettings.ElementCount = _heartCountRow1;
         resourceDrawSettings.ElementIndexOffset = 0;
         resourceDrawSettings.TopLeftAnchor = vector + new Vector2(15f, 15f);
         resourceDrawSettings.GetTextureMethod = HeartFillingDrawer;
         resourceDrawSettings.OffsetPerDraw = Vector2.UnitX * 2f;
         resourceDrawSettings.OffsetPerDrawByTexturePercentile = Vector2.UnitX;
         resourceDrawSettings.OffsetSpriteAnchor = Vector2.Zero;
         resourceDrawSettings.OffsetSpriteAnchorByTexturePercentile = new Vector2(0.5f, 0.5f);
         resourceDrawSettings.Draw(spriteBatch, ref isHovered);
         resourceDrawSettings = default(ResourceDrawSettings);
         resourceDrawSettings.ElementCount = _heartCountRow2;
         resourceDrawSettings.ElementIndexOffset = 10;
         resourceDrawSettings.TopLeftAnchor = vector + new Vector2(15f, 15f) + new Vector2(0f, 28f);
         resourceDrawSettings.GetTextureMethod = HeartFillingDrawer;
         resourceDrawSettings.OffsetPerDraw = Vector2.UnitX * 2f;
         resourceDrawSettings.OffsetPerDrawByTexturePercentile = Vector2.UnitX;
         resourceDrawSettings.OffsetSpriteAnchor = Vector2.Zero;
         resourceDrawSettings.OffsetSpriteAnchorByTexturePercentile = new Vector2(0.5f, 0.5f);
         resourceDrawSettings.Draw(spriteBatch, ref isHovered);
         _hoverLife = isHovered;
     }
References _drawText, _heartCountRow1, _heartCountRow2, _hoverLife, ResourceDrawSettings.Draw(), DrawLifeBarText(), ResourceDrawSettings.ElementCount, ResourceDrawSettings.ElementIndexOffset, ResourceDrawSettings.GetTextureMethod, HeartFillingDrawer(), HeartPanelDrawer(), ResourceDrawSettings.OffsetPerDraw, ResourceDrawSettings.OffsetPerDrawByTexturePercentile, ResourceDrawSettings.OffsetSpriteAnchor, ResourceDrawSettings.OffsetSpriteAnchorByTexturePercentile, Main.screenWidth, and ResourceDrawSettings.TopLeftAnchor.
Referenced by Draw().