Terraria: FancyClassicPlayerResourcesDisplaySet.Draw
Draw()
void FancyClassicPlayerResourcesDisplaySet.Draw () inline
Implements IPlayerResourcesDisplaySet.
     {
         Player localPlayer = Main.LocalPlayer;
         SpriteBatch spriteBatch = Main.spriteBatch;
         PrepareFields(localPlayer);
         DrawLifeBar(spriteBatch);
         DrawManaBar(spriteBatch);
     }
References DrawLifeBar(), DrawManaBar(), Main.LocalPlayer, PrepareFields(), and Main.spriteBatch.