Terraria: System.Xml.XmlEventCache.EventsToWriter
EventsToWriter()
void System.Xml.XmlEventCache.EventsToWriter (XmlWriter writer) inline
Definition at line 136 of file XmlEventCache.cs.
    {
        if (_singleText.Count != 0)
        {
            writer.WriteString(_singleText.GetResult());
            return;
        }
        XmlRawWriter xmlRawWriter = writer as XmlRawWriter;
        for (int i = 0; i < _pages.Count; i++)
        {
            XmlEvent[] array = _pages[i];
            for (int j = 0; j < array.Length; j++)
            {
                switch (array[j].EventType)
                {
                case XmlEventType.Unknown:
                    return;
                case XmlEventType.DocType:
                    writer.WriteDocType(array[j].String1, array[j].String2, array[j].String3, (string)array[j].Object);
                    break;
                case XmlEventType.StartElem:
                    writer.WriteStartElement(array[j].String1, array[j].String2, array[j].String3);
                    break;
                case XmlEventType.StartAttr:
                    writer.WriteStartAttribute(array[j].String1, array[j].String2, array[j].String3);
                    break;
                case XmlEventType.EndAttr:
                    writer.WriteEndAttribute();
                    break;
                case XmlEventType.CData:
                    writer.WriteCData(array[j].String1);
                    break;
                case XmlEventType.Comment:
                    writer.WriteComment(array[j].String1);
                    break;
                case XmlEventType.PI:
                    writer.WriteProcessingInstruction(array[j].String1, array[j].String2);
                    break;
                case XmlEventType.Whitespace:
                    writer.WriteWhitespace(array[j].String1);
                    break;
                case XmlEventType.String:
                    writer.WriteString(array[j].String1);
                    break;
                case XmlEventType.Raw:
                    writer.WriteRaw(array[j].String1);
                    break;
                case XmlEventType.EntRef:
                    writer.WriteEntityRef(array[j].String1);
                    break;
                case XmlEventType.CharEnt:
                    writer.WriteCharEntity((char)array[j].Object);
                    break;
                case XmlEventType.SurrCharEnt:
                {
                    char[] array3 = (char[])array[j].Object;
                    writer.WriteSurrogateCharEntity(array3[0], array3[1]);
                    break;
                }
                case XmlEventType.Base64:
                {
                    byte[] array2 = (byte[])array[j].Object;
                    writer.WriteBase64(array2, 0, array2.Length);
                    break;
                }
                case XmlEventType.BinHex:
                {
                    byte[] array2 = (byte[])array[j].Object;
                    writer.WriteBinHex(array2, 0, array2.Length);
                    break;
                }
                case XmlEventType.XmlDecl1:
                    xmlRawWriter?.WriteXmlDeclaration((XmlStandalone)array[j].Object);
                    break;
                case XmlEventType.XmlDecl2:
                    xmlRawWriter?.WriteXmlDeclaration(array[j].String1);
                    break;
                case XmlEventType.StartContent:
                    xmlRawWriter?.StartElementContent();
                    break;
                case XmlEventType.EndElem:
                    if (xmlRawWriter != null)
                    {
                        xmlRawWriter.WriteEndElement(array[j].String1, array[j].String2, array[j].String3);
                    }
                    else
                    {
                        writer.WriteEndElement();
                    }
                    break;
                case XmlEventType.FullEndElem:
                    if (xmlRawWriter != null)
                    {
                        xmlRawWriter.WriteFullEndElement(array[j].String1, array[j].String2, array[j].String3);
                    }
                    else
                    {
                        writer.WriteFullEndElement();
                    }
                    break;
                case XmlEventType.Nmsp:
                    if (xmlRawWriter != null)
                    {
                        xmlRawWriter.WriteNamespaceDeclaration(array[j].String1, array[j].String2);
                    }
                    else
                    {
                        writer.WriteAttributeString("xmlns", array[j].String1, "http://www.w3.org/2000/xmlns/", array[j].String2);
                    }
                    break;
                case XmlEventType.EndBase64:
                    xmlRawWriter?.WriteEndBase64();
                    break;
                case XmlEventType.Close:
                    writer.Close();
                    break;
                case XmlEventType.Flush:
                    writer.Flush();
                    break;
                case XmlEventType.Dispose:
                    ((IDisposable)writer).Dispose();
                    break;
                }
            }
        }
    }
References System.Xml.XmlEventCache._pages, System.Xml.XmlEventCache._singleText, System.array, System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Xml.Xsl.Runtime.StringConcat.Count, System.Xml.Dictionary, System.Xml.Xsl.Runtime.StringConcat.GetResult(), and System.writer.
Referenced by System.Xml.Xsl.Runtime.RtfTreeNavigator.CopyToWriter(), System.Xml.XmlAutoDetectWriter.CreateWrappedWriter(), and System.Xml.Xsl.Runtime.NavigatorConstructor.GetNavigator().