Terraria: Terraria.Map.MapHelper.GetMapTileXnaColor
GetMapTileXnaColor()
static Color Terraria.Map.MapHelper.GetMapTileXnaColor (ref MapTile tile) inline static
    {
        Color oldColor = colorLookup[tile.Type];
        byte color = tile.Color;
        if (color > 0)
        {
            MapColor(tile.Type, ref oldColor, color);
        }
        if (tile.Light == byte.MaxValue)
        {
            return oldColor;
        }
        float num = (float)(int)tile.Light / 255f;
        oldColor.R = (byte)((float)(int)oldColor.R * num);
        oldColor.G = (byte)((float)(int)oldColor.G * num);
        oldColor.B = (byte)((float)(int)oldColor.B * num);
        return oldColor;
    }
References Terraria.Map.MapHelper.colorLookup, and Terraria.Map.MapHelper.MapColor().
Referenced by Terraria.Main.DrawToMap(), and Terraria.Main.DrawToMap_Section().