Terraria: LanternSky.ResetLantern
ResetLantern()
void LanternSky.ResetLantern (int i) inline
     {
         _lanterns[i].Depth = (1f - (float)i / (float)_lanterns.Length) * 4.4f + 1.6f;
         _lanterns[i].Speed = -1.5f - 2.5f * (float)_random.NextDouble();
         _lanterns[i].Texture = _texture.Value;
         _lanterns[i].Variant = _random.Next(3);
         _lanterns[i].TimeUntilFloat = (int)((float)(2000 + _random.Next(1200)) * 2f);
         _lanterns[i].TimeUntilFloatMax = _lanterns[i].TimeUntilFloat;
     }
References _lanterns, _random, _texture, LanternSky.Lantern.Depth, UnifiedRandom.Next(), UnifiedRandom.NextDouble(), LanternSky.Lantern.Speed, LanternSky.Lantern.Texture, LanternSky.Lantern.TimeUntilFloat, LanternSky.Lantern.TimeUntilFloatMax, Asset< T >.Value, and LanternSky.Lantern.Variant.
Referenced by GenerateLanterns(), and Update().