Terraria: MS.Internal.Xml.XPath.ParentQuery.Evaluate
Evaluate()
override object MS.Internal.Xml.XPath.ParentQuery.Evaluate (XPathNodeIterator context) inline
Definition at line 17 of file ParentQuery.cs.
    {
        base.Evaluate(context);
        XPathNavigator xPathNavigator;
        while ((xPathNavigator = qyInput.Advance()) != null)
        {
            xPathNavigator = xPathNavigator.Clone();
            if (xPathNavigator.MoveToParent() && matches(xPathNavigator))
            {
                Query.Insert(outputBuffer, xPathNavigator);
            }
        }
        return this;
    }
References MS.Internal.Xml.XPath.Query.Advance(), System.Xml.XPath.XPathNavigator.Clone(), MS.Internal.Xml.XPath.Query.Insert(), MS.Internal.Xml.XPath.BaseAxisQuery.matches(), System.Xml.XPath.XPathNavigator.MoveToParent(), MS.Internal.Xml.XPath.CacheAxisQuery.outputBuffer, and MS.Internal.Xml.XPath.BaseAxisQuery.qyInput.