Terraria: Terraria.Initializers.AssetInitializer.CreateResourcePackList
CreateResourcePackList()
static ResourcePackList Terraria.Initializers.AssetInitializer.CreateResourcePackList (IServiceProvider services) inline static
Definition at line 46 of file AssetInitializer.cs.
    {
        GetResourcePacksFolderPathAndConfirmItExists(out var resourcePackJson, out var resourcePackFolder);
        return ResourcePackList.FromJson(resourcePackJson, services, resourcePackFolder);
    }
References Terraria.IO.ResourcePackList.FromJson(), and Terraria.Initializers.AssetInitializer.GetResourcePacksFolderPathAndConfirmItExists().
Referenced by Terraria.Main.LoadContent(), and Terraria.Main.OpenResourcePacksMenu().