Terraria: Terraria.Initializers.AssetInitializer.LoadAssetsWhileInInitialBlackScreen
LoadAssetsWhileInInitialBlackScreen()
static void Terraria.Initializers.AssetInitializer.LoadAssetsWhileInInitialBlackScreen () inline static
Definition at line 80 of file AssetInitializer.cs.
    {
        LoadFonts((AssetRequestMode)1);
        LoadTextures((AssetRequestMode)1);
        LoadRenderTargetAssets((AssetRequestMode)1);
        LoadSounds((AssetRequestMode)1);
    }
References Terraria.Initializers.AssetInitializer.LoadFonts(), Terraria.Initializers.AssetInitializer.LoadRenderTargetAssets(), Terraria.Initializers.AssetInitializer.LoadSounds(), and Terraria.Initializers.AssetInitializer.LoadTextures().
Referenced by Terraria.Main.LoadContent_Deferred().