Terraria: ScreenShaderData.Apply
Apply()
override void ScreenShaderData.Apply () inline virtual inherited
Reimplemented from ShaderData.
     {
         Vector2 vector = new Vector2(Main.offScreenRange, Main.offScreenRange);
         Vector2 value = new Vector2(Main.screenWidth, Main.screenHeight) / Main.GameViewMatrix.Zoom;
         Vector2 vector2 = new Vector2(Main.screenWidth, Main.screenHeight) * 0.5f;
         Vector2 vector3 = Main.screenPosition + vector2 * (Vector2.One - Vector2.One / Main.GameViewMatrix.Zoom);
         base.Shader.Parameters["uColor"].SetValue(_uColor);
         base.Shader.Parameters["uOpacity"].SetValue(CombinedOpacity);
         base.Shader.Parameters["uSecondaryColor"].SetValue(_uSecondaryColor);
         base.Shader.Parameters["uTime"].SetValue(Main.GlobalTimeWrappedHourly);
         base.Shader.Parameters["uScreenResolution"].SetValue(value);
         base.Shader.Parameters["uScreenPosition"].SetValue(vector3 - vector);
         base.Shader.Parameters["uTargetPosition"].SetValue(_uTargetPosition - vector);
         base.Shader.Parameters["uImageOffset"].SetValue(_uImageOffset);
         base.Shader.Parameters["uIntensity"].SetValue(_uIntensity);
         base.Shader.Parameters["uProgress"].SetValue(_uProgress);
         base.Shader.Parameters["uDirection"].SetValue(_uDirection);
         base.Shader.Parameters["uZoom"].SetValue(Main.GameViewMatrix.Zoom);
         for (int i = 0; i < _uAssetImages.Length; i++)
         {
             Texture2D texture2D = _uCustomImages[i];
             if (_uAssetImages[i] != null && _uAssetImages[i].IsLoaded)
             {
                 texture2D = _uAssetImages[i].Value;
             }
             if (texture2D != null)
             {
                 Main.graphics.GraphicsDevice.Textures[i + 1] = texture2D;
                 int width = texture2D.Width;
                 int height = texture2D.Height;
                 if (_samplerStates[i] != null)
                 {
                     Main.graphics.GraphicsDevice.SamplerStates[i + 1] = _samplerStates[i];
                 }
                 else if (Utils.IsPowerOfTwo(width) && Utils.IsPowerOfTwo(height))
                 {
                     Main.graphics.GraphicsDevice.SamplerStates[i + 1] = SamplerState.LinearWrap;
                 }
                 else
                 {
                     Main.graphics.GraphicsDevice.SamplerStates[i + 1] = SamplerState.AnisotropicClamp;
                 }
                 base.Shader.Parameters["uImageSize" + (i + 1)].SetValue(new Vector2(width, height) * _imageScales[i]);
             }
         }
         base.Apply();
     }
References ScreenShaderData._imageScales, ScreenShaderData._samplerStates, ScreenShaderData._uAssetImages, ScreenShaderData._uColor, ScreenShaderData._uCustomImages, ScreenShaderData._uDirection, ScreenShaderData._uImageOffset, ScreenShaderData._uIntensity, ScreenShaderData._uProgress, ScreenShaderData._uSecondaryColor, ScreenShaderData._uTargetPosition, ScreenShaderData.CombinedOpacity, Main.GameViewMatrix, Main.GlobalTimeWrappedHourly, Main.graphics, Utils.IsPowerOfTwo(), Main.offScreenRange, Main.screenHeight, Main.screenPosition, Main.screenWidth, Asset< T >.Value, and SpriteViewMatrix.Zoom.
Referenced by Filter.Apply(), and SimpleOverlay.Draw().