Terraria: System.Guid.TryParseGuid
TryParseGuid()
static bool System.Guid.TryParseGuid (ReadOnlySpan< char > guidString, ref GuidResult result) inline static private
Definition at line 309 of file Guid.cs.
    {
        guidString = guidString.Trim();
        if (guidString.Length == 0)
        {
            result.SetFailure(overflow: false, "Format_GuidUnrecognized");
            return false;
        }
        return guidString[0] switch
        {
            '(' => TryParseExactP(guidString, ref result),
            '{' => guidString.Contains('-') ? TryParseExactB(guidString, ref result) : TryParseExactX(guidString, ref result),
            _ => guidString.Contains('-') ? TryParseExactD(guidString, ref result) : TryParseExactN(guidString, ref result),
        };
    }
References System.ReadOnlySpan< T >.Length, System.Guid.TryParseExactB(), System.Guid.TryParseExactD(), System.Guid.TryParseExactN(), System.Guid.TryParseExactP(), and System.Guid.TryParseExactX().
Referenced by System.Guid.Guid(), System.Guid.Parse(), and System.Guid.TryParse().