Terraria: System.Guid.TryParseExact
TryParseExact() [2/2]
static bool System.Guid.TryParseExact (ReadOnlySpan< char > input, ReadOnlySpan< char > format, out Guid result) inline static
Definition at line 272 of file Guid.cs.
    {
        if (format.Length != 1)
        {
            result = default(Guid);
            return false;
        }
        input = input.Trim();
        GuidResult result2 = new GuidResult(GuidParseThrowStyle.None);
        bool flag = false;
        switch ((char)(ushort)(format[0] | 0x20))
        {
        case 'd':
            flag = TryParseExactD(input, ref result2);
            break;
        case 'n':
            flag = TryParseExactN(input, ref result2);
            break;
        case 'b':
            flag = TryParseExactB(input, ref result2);
            break;
        case 'p':
            flag = TryParseExactP(input, ref result2);
            break;
        case 'x':
            flag = TryParseExactX(input, ref result2);
            break;
        }
        if (flag)
        {
            result = result2.ToGuid();
            return true;
        }
        result = default(Guid);
        return false;
    }
References System.format, System.input, System.Guid.GuidResult.ToGuid(), System.Guid.TryParseExactB(), System.Guid.TryParseExactD(), System.Guid.TryParseExactN(), System.Guid.TryParseExactP(), and System.Guid.TryParseExactX().