Terraria: System.Guid.TryParseExactP
TryParseExactP()
static bool System.Guid.TryParseExactP (ReadOnlySpan< char > guidString, ref GuidResult result) inline static private
Definition at line 445 of file Guid.cs.
    {
        if (guidString.Length != 38 || guidString[0] != '(' || guidString[37] != ')')
        {
            result.SetFailure(overflow: false, "Format_GuidInvLen");
            return false;
        }
        return TryParseExactD(guidString.Slice(1, 36), ref result);
    }
References System.ReadOnlySpan< T >.Length, System.ReadOnlySpan< T >.Slice(), and System.Guid.TryParseExactD().
Referenced by System.Guid.ParseExact(), System.Guid.TryParseExact(), and System.Guid.TryParseGuid().