Terraria: System.Guid.TryParseExactX
TryParseExactX()
static bool System.Guid.TryParseExactX (ReadOnlySpan< char > guidString, ref GuidResult result) inline static private
Definition at line 455 of file Guid.cs.
    {
        guidString = EatAllWhitespace(guidString);
        if (guidString.Length == 0 || guidString[0] != '{')
        {
            result.SetFailure(overflow: false, "Format_GuidBrace");
            return false;
        }
        if (!IsHexPrefix(guidString, 1))
        {
            result.SetFailure(overflow: false, "Format_GuidHexPrefix");
            return false;
        }
        int num = 3;
        int num2 = guidString.Slice(num).IndexOf(',');
        if (num2 <= 0)
        {
            result.SetFailure(overflow: false, "Format_GuidComma");
            return false;
        }
        bool overflow = false;
        if (!TryParseHex(guidString.Slice(num, num2), out result._a, ref overflow) || overflow)
        {
            result.SetFailure(overflow, overflow ? "Overflow_UInt32" : "Format_GuidInvalidChar");
            return false;
        }
        if (!IsHexPrefix(guidString, num + num2 + 1))
        {
            result.SetFailure(overflow: false, "Format_GuidHexPrefix");
            return false;
        }
        num = num + num2 + 3;
        num2 = guidString.Slice(num).IndexOf(',');
        if (num2 <= 0)
        {
            result.SetFailure(overflow: false, "Format_GuidComma");
            return false;
        }
        if (!TryParseHex(guidString.Slice(num, num2), out result._b, ref overflow) || overflow)
        {
            result.SetFailure(overflow, overflow ? "Overflow_UInt32" : "Format_GuidInvalidChar");
            return false;
        }
        if (!IsHexPrefix(guidString, num + num2 + 1))
        {
            result.SetFailure(overflow: false, "Format_GuidHexPrefix");
            return false;
        }
        num = num + num2 + 3;
        num2 = guidString.Slice(num).IndexOf(',');
        if (num2 <= 0)
        {
            result.SetFailure(overflow: false, "Format_GuidComma");
            return false;
        }
        if (!TryParseHex(guidString.Slice(num, num2), out result._c, ref overflow) || overflow)
        {
            result.SetFailure(overflow, overflow ? "Overflow_UInt32" : "Format_GuidInvalidChar");
            return false;
        }
        if ((uint)guidString.Length <= (uint)(num + num2 + 1) || guidString[num + num2 + 1] != '{')
        {
            result.SetFailure(overflow: false, "Format_GuidBrace");
            return false;
        }
        num2++;
        for (int i = 0; i < 8; i++)
        {
            if (!IsHexPrefix(guidString, num + num2 + 1))
            {
                result.SetFailure(overflow: false, "Format_GuidHexPrefix");
                return false;
            }
            num = num + num2 + 3;
            if (i < 7)
            {
                num2 = guidString.Slice(num).IndexOf(',');
                if (num2 <= 0)
                {
                    result.SetFailure(overflow: false, "Format_GuidComma");
                    return false;
                }
            }
            else
            {
                num2 = guidString.Slice(num).IndexOf('}');
                if (num2 <= 0)
                {
                    result.SetFailure(overflow: false, "Format_GuidBraceAfterLastNumber");
                    return false;
                }
            }
            if (!TryParseHex(guidString.Slice(num, num2), out uint result2, ref overflow) || overflow || result2 > 255)
            {
                result.SetFailure(overflow, overflow ? "Overflow_UInt32" : ((result2 > 255) ? "Overflow_Byte" : "Format_GuidInvalidChar"));
                return false;
            }
            Unsafe.Add(ref result._d, i) = (byte)result2;
        }
        if (num + num2 + 1 >= guidString.Length || guidString[num + num2 + 1] != '}')
        {
            result.SetFailure(overflow: false, "Format_GuidEndBrace");
            return false;
        }
        if (num + num2 + 1 != guidString.Length - 1)
        {
            result.SetFailure(overflow: false, "Format_ExtraJunkAtEnd");
            return false;
        }
        return true;
    }
References System.Guid.EatAllWhitespace(), System.Guid.IsHexPrefix(), System.ReadOnlySpan< T >.Length, System.ReadOnlySpan< T >.Slice(), and System.Guid.TryParseHex().
Referenced by System.Guid.ParseExact(), System.Guid.TryParseExact(), and System.Guid.TryParseGuid().