Terraria: System.Guid.Equals
Equals() [1/3]
override bool System.Guid.Equals ([NotNullWhen(true)] object? o) inline
Definition at line 706 of file Guid.cs.
    {
        if (o is Guid right)
        {
            return EqualsCore(in this, in right);
        }
        return false;
    }
References System.Guid.EqualsCore().
Referenced by System.Security.AccessControl.ObjectAccessRule.ObjectAccessRule(), System.Security.AccessControl.ObjectAuditRule.ObjectAuditRule(), System.ComponentModel.Design.CommandID.Equals(), System.Security.AccessControl.ObjectAce.InheritedObjectTypesMatch(), System.Security.AccessControl.CommonAcl.InheritedObjectTypesMatch(), System.Security.AccessControl.ObjectAce.ObjectTypesMatch(), and System.Security.AccessControl.CommonAcl.ObjectTypesMatch().