Terraria: System.Guid.TryParseExactN
TryParseExactN()
static bool System.Guid.TryParseExactN (ReadOnlySpan< char > guidString, ref GuidResult result) inline static private
Definition at line 409 of file Guid.cs.
    {
        if (guidString.Length != 32)
        {
            result.SetFailure(overflow: false, "Format_GuidInvLen");
            return false;
        }
        Span<byte> span = MemoryMarshal.AsBytes(new Span<GuidResult>(ref result, 1));
        int invalidIfNegative = 0;
        span[0] = DecodeByte(guidString[6], guidString[7], ref invalidIfNegative);
        span[1] = DecodeByte(guidString[4], guidString[5], ref invalidIfNegative);
        span[2] = DecodeByte(guidString[2], guidString[3], ref invalidIfNegative);
        span[3] = DecodeByte(guidString[0], guidString[1], ref invalidIfNegative);
        span[4] = DecodeByte(guidString[10], guidString[11], ref invalidIfNegative);
        span[5] = DecodeByte(guidString[8], guidString[9], ref invalidIfNegative);
        span[6] = DecodeByte(guidString[14], guidString[15], ref invalidIfNegative);
        span[7] = DecodeByte(guidString[12], guidString[13], ref invalidIfNegative);
        span[8] = DecodeByte(guidString[16], guidString[17], ref invalidIfNegative);
        span[9] = DecodeByte(guidString[18], guidString[19], ref invalidIfNegative);
        span[10] = DecodeByte(guidString[20], guidString[21], ref invalidIfNegative);
        span[11] = DecodeByte(guidString[22], guidString[23], ref invalidIfNegative);
        span[12] = DecodeByte(guidString[24], guidString[25], ref invalidIfNegative);
        span[13] = DecodeByte(guidString[26], guidString[27], ref invalidIfNegative);
        span[14] = DecodeByte(guidString[28], guidString[29], ref invalidIfNegative);
        span[15] = DecodeByte(guidString[30], guidString[31], ref invalidIfNegative);
        if (invalidIfNegative >= 0)
        {
            if (!BitConverter.IsLittleEndian)
            {
            }
            return true;
        }
        result.SetFailure(overflow: false, "Format_GuidInvalidChar");
        return false;
    }
References System.Guid.DecodeByte(), System.BitConverter.IsLittleEndian, and System.ReadOnlySpan< T >.Length.
Referenced by System.Guid.ParseExact(), System.Guid.TryParseExact(), and System.Guid.TryParseGuid().