Terraria: System.Guid.TryParseExactD
TryParseExactD()
static bool System.Guid.TryParseExactD (ReadOnlySpan< char > guidString, ref GuidResult result) inline static private
Definition at line 335 of file Guid.cs.
    {
        if (guidString.Length != 36 || guidString[8] != '-' || guidString[13] != '-' || guidString[18] != '-' || guidString[23] != '-')
        {
            result.SetFailure(overflow: false, (guidString.Length != 36) ? "Format_GuidInvLen" : "Format_GuidDashes");
            return false;
        }
        Span<byte> span = MemoryMarshal.AsBytes(new Span<GuidResult>(ref result, 1));
        int invalidIfNegative = 0;
        span[0] = DecodeByte(guidString[6], guidString[7], ref invalidIfNegative);
        span[1] = DecodeByte(guidString[4], guidString[5], ref invalidIfNegative);
        span[2] = DecodeByte(guidString[2], guidString[3], ref invalidIfNegative);
        span[3] = DecodeByte(guidString[0], guidString[1], ref invalidIfNegative);
        span[4] = DecodeByte(guidString[11], guidString[12], ref invalidIfNegative);
        span[5] = DecodeByte(guidString[9], guidString[10], ref invalidIfNegative);
        span[6] = DecodeByte(guidString[16], guidString[17], ref invalidIfNegative);
        span[7] = DecodeByte(guidString[14], guidString[15], ref invalidIfNegative);
        span[8] = DecodeByte(guidString[19], guidString[20], ref invalidIfNegative);
        span[9] = DecodeByte(guidString[21], guidString[22], ref invalidIfNegative);
        span[10] = DecodeByte(guidString[24], guidString[25], ref invalidIfNegative);
        span[11] = DecodeByte(guidString[26], guidString[27], ref invalidIfNegative);
        span[12] = DecodeByte(guidString[28], guidString[29], ref invalidIfNegative);
        span[13] = DecodeByte(guidString[30], guidString[31], ref invalidIfNegative);
        span[14] = DecodeByte(guidString[32], guidString[33], ref invalidIfNegative);
        span[15] = DecodeByte(guidString[34], guidString[35], ref invalidIfNegative);
        if (invalidIfNegative >= 0)
        {
            if (!BitConverter.IsLittleEndian)
            {
            }
            return true;
        }
        if (guidString.IndexOfAny('X', 'x', '+') != -1 && TryCompatParsing(guidString, ref result))
        {
            return true;
        }
        result.SetFailure(overflow: false, "Format_GuidInvalidChar");
        return false;
        static bool TryCompatParsing(ReadOnlySpan<char> guidString, ref GuidResult result)
        {
            if (TryParseHex(guidString.Slice(0, 8), out result._a) && TryParseHex(guidString.Slice(9, 4), out var result2))
            {
                result._b = (ushort)result2;
                if (TryParseHex(guidString.Slice(14, 4), out result2))
                {
                    result._c = (ushort)result2;
                    if (TryParseHex(guidString.Slice(19, 4), out result2))
                    {
                        if (!BitConverter.IsLittleEndian)
{
                        }
                        result._de = BinaryPrimitives.ReverseEndianness((ushort)result2);
                        if (TryParseHex(guidString.Slice(24, 4), out result2))
{
                            if (!BitConverter.IsLittleEndian)
{
                            }
                            result._fg = BinaryPrimitives.ReverseEndianness((ushort)result2);
                            if (Number.TryParseUInt32HexNumberStyle(guidString.Slice(28, 8), NumberStyles.AllowHexSpecifier, out result2) == Number.ParsingStatus.OK)
{
                                if (!BitConverter.IsLittleEndian)
{
                                }
                                result._hijk = BinaryPrimitives.ReverseEndianness(result2);
                                return true;
                            }
                        }
                    }
                }
            }
            return false;
        }
    }
References System.Guid.DecodeByte(), System.BitConverter.IsLittleEndian, System.ReadOnlySpan< T >.Length, System.Buffers.Binary.BinaryPrimitives.ReverseEndianness(), System.ReadOnlySpan< T >.Slice(), System.Guid.TryParseHex(), and System.Number.TryParseUInt32HexNumberStyle().
Referenced by System.Guid.ParseExact(), System.Guid.TryParseExact(), System.Guid.TryParseExactB(), System.Guid.TryParseExactP(), and System.Guid.TryParseGuid().