Terraria: System.Guid.ToString
ToString() [1/3]
override string System.Guid.ToString () inline
Definition at line 695 of file Guid.cs.
    {
        return ToString("D", null);
    }
References System.Guid.ToString().
Referenced by System.Transactions.TransactionStatePromotedNonMSDTCBase.EnlistDurable(), System.Transactions.TransactionStatePromotedNonMSDTCBase.EnlistDurable(), System.Diagnostics.Tracing.EventProvider.GetDataFromController(), System.Transactions.InternalTransaction.ThrowIfPromoterTypeIsNotMSDTC(), System.Guid.ToString(), System.Guid.ToString(), System.Transactions.TransactionsEtwProvider.TransactionManagerRecoveryComplete(), and System.Transactions.TransactionsEtwProvider.TransactionManagerReenlist().