Terraria: System.Guid.NewGuid
NewGuid()
static Guid System.Guid.NewGuid () inline static
Definition at line 1283 of file Guid.cs.
    {
        Guid guid;
        int num = Interop.Ole32.CoCreateGuid(out guid);
        if (num != 0)
        {
            Exception ex = new Exception();
            ex.HResult = num;
            throw ex;
        }
        return guid;
    }
References Interop.Ole32.CoCreateGuid().
Referenced by Terraria.Main.Main(), System.Diagnostics.RandomNumberGenerator.RandomNumberGenerator(), Terraria.Main.ClientInitialize(), Terraria.IO.WorldFileData.CopyToLocal(), Terraria.IO.WorldFile.CreateMetadata(), System.Net.WebSockets.WebSocketHandle.CreateSecKeyAndSecWebSocketAccept(), Terraria.Utilities.FastRandom.CreateWithRandomSeed(), System.Net.Http.MultipartContent.GetDefaultBoundary(), System.Diagnostics.Activity.GetRandomNumber(), System.Reflection.Metadata.BlobContentId.GetTimeBasedProvider(), Terraria.IO.WorldFile.LoadHeader(), System.Diagnostics.Metrics.MetricsEventSource.CommandHandler.OnEventCommand(), System.Security.AccessControl.ObjectAce.ParseBinaryForm(), System.Net.Http.DiagnosticsHandler.SendAsyncCore(), and System.Diagnostics.CorrelationManager.StartLogicalOperation().