Terraria: System.Net.WebSockets.WebSocketHttpListenerDuplexStream.HttpListenerAsyncEventArgs.CompletionPortCallback
CompletionPortCallback()
unsafe void System.Net.WebSockets.WebSocketHttpListenerDuplexStream.HttpListenerAsyncEventArgs.CompletionPortCallback (uint errorCode, uint numBytes, NativeOverlapped * nativeOverlapped) inline private
Definition at line 307 of file WebSocketHttpListenerDuplexStream.cs.
        {
            if (errorCode == 0 || errorCode == 38)
            {
                FinishOperationSuccess((int)numBytes, syncCompletion: false);
            }
            else
            {
                FinishOperationFailure(new HttpListenerException((int)errorCode), syncCompletion: false);
            }
        }
References System.Net.WebSockets.WebSocketHttpListenerDuplexStream.HttpListenerAsyncEventArgs.FinishOperationFailure(), and System.Net.WebSockets.WebSocketHttpListenerDuplexStream.HttpListenerAsyncEventArgs.FinishOperationSuccess().
Referenced by System.Net.WebSockets.WebSocketHttpListenerDuplexStream.HttpListenerAsyncEventArgs.InitializeOverlapped().