Terraria: System.Globalization.InvariantModeCasing.ToUpper
ToUpper() [3/3]
static string System.Globalization.InvariantModeCasing.ToUpper (string s) inline static package
Definition at line 62 of file InvariantModeCasing.cs.
    {
        if (s.Length == 0)
        {
            return string.Empty;
        }
        ReadOnlySpan<char> readOnlySpan = s;
        int num = 0;
        while (num < s.Length)
        {
            if (char.IsHighSurrogate(readOnlySpan[num]) && num < s.Length - 1 && char.IsLowSurrogate(readOnlySpan[num + 1]))
            {
                SurrogateCasing.ToUpper(readOnlySpan[num], readOnlySpan[num + 1], out var hr, out var lr);
                if (readOnlySpan[num] != hr || readOnlySpan[num + 1] != lr)
                {
                    break;
                }
                num += 2;
            }
            else
            {
                if (ToUpper(readOnlySpan[num]) != readOnlySpan[num])
                {
                    break;
                }
                num++;
            }
        }
        if (num >= s.Length)
        {
            return s;
        }
        return string.Create(s.Length, (s, num), delegate(Span<char> destination, (string s, int i) state)
        {
            ReadOnlySpan<char> readOnlySpan2 = state.s;
            readOnlySpan2.Slice(0, state.i).CopyTo(destination);
            ToUpper(readOnlySpan2.Slice(state.i), destination.Slice(state.i));
        });
    }
References System.destination, System.s, System.ReadOnlySpan< T >.Slice(), System.state, System.Globalization.InvariantModeCasing.ToUpper(), and System.Globalization.SurrogateCasing.ToUpper().