Terraria: System.Net.WebSockets.WebSocketHttpListenerDuplexStream.HttpListenerAsyncEventArgs.FinishOperationSuccess
FinishOperationSuccess()
void System.Net.WebSockets.WebSocketHttpListenerDuplexStream.HttpListenerAsyncEventArgs.FinishOperationSuccess (int bytesTransferred, bool syncCompletion) inline package
Definition at line 281 of file WebSocketHttpListenerDuplexStream.cs.
        {
            SetResults(null, bytesTransferred);
            if (System.Net.NetEventSource.Log.IsEnabled())
            {
                if (_buffer != null && System.Net.NetEventSource.Log.IsEnabled())
                {
                    string memberName = ((_completedOperation == HttpListenerAsyncOperation.Receive) ? "ReadAsyncFast" : "WriteAsyncFast");
                    System.Net.NetEventSource.DumpBuffer(_currentStream, _buffer, _offset, bytesTransferred, memberName);
                }
                else if (_bufferList != null)
                {
                    foreach (ArraySegment<byte> buffer in BufferList)
                    {
                        System.Net.NetEventSource.DumpBuffer(this, buffer.Array, buffer.Offset, buffer.Count, "WriteAsyncFast");
                    }
                }
            }
            if (_shouldCloseOutput)
            {
                _currentStream._outputStream.SetClosedFlag();
            }
            Complete();
            OnCompleted(this);
        }
References System.Net.WebSockets.WebSocketHttpListenerDuplexStream.HttpListenerAsyncEventArgs._buffer, System.Net.WebSockets.WebSocketHttpListenerDuplexStream.HttpListenerAsyncEventArgs._bufferList, System.Net.WebSockets.WebSocketHttpListenerDuplexStream.HttpListenerAsyncEventArgs._completedOperation, System.Net.WebSockets.WebSocketHttpListenerDuplexStream.HttpListenerAsyncEventArgs._currentStream, System.Net.WebSockets.WebSocketHttpListenerDuplexStream.HttpListenerAsyncEventArgs._offset, System.Net.WebSockets.WebSocketHttpListenerDuplexStream._outputStream, System.Net.WebSockets.WebSocketHttpListenerDuplexStream.HttpListenerAsyncEventArgs._shouldCloseOutput, System.buffer, System.Net.WebSockets.WebSocketHttpListenerDuplexStream.HttpListenerAsyncEventArgs.BufferList, System.Net.WebSockets.WebSocketHttpListenerDuplexStream.HttpListenerAsyncEventArgs.Complete(), System.Net.NetEventSource.DumpBuffer(), System.Net.NetEventSource.Log, System.Net.WebSockets.WebSocketHttpListenerDuplexStream.HttpListenerAsyncEventArgs.OnCompleted(), System.Net.HttpResponseStream.SetClosedFlag(), and System.Net.WebSockets.WebSocketHttpListenerDuplexStream.HttpListenerAsyncEventArgs.SetResults().
Referenced by System.Net.WebSockets.WebSocketHttpListenerDuplexStream.HttpListenerAsyncEventArgs.CompletionPortCallback().