Terraria: System.Globalization.InvariantModeCasing.ToUpper
ToUpper() [1/3]
static char System.Globalization.InvariantModeCasing.ToUpper (char c) inline static package
Definition at line 17 of file InvariantModeCasing.cs.
    {
        return CharUnicodeInfo.ToUpper(c);
    }
References System.Globalization.CharUnicodeInfo.ToUpper().
Referenced by System.Globalization.TextInfo.AddTitlecaseLetter(), System.Globalization.InvariantModeCasing.IndexOfIgnoreCase(), System.Globalization.CompareInfo.InvariantCreateSortKeyOrdinalIgnoreCase(), System.Globalization.InvariantModeCasing.LastIndexOfIgnoreCase(), System.Globalization.TextInfo.ToUpper(), System.Globalization.InvariantModeCasing.ToUpper(), System.Globalization.InvariantModeCasing.ToUpper(), System.Globalization.TextInfo.ToUpper(), System.MemoryExtensions.ToUpper(), System.Globalization.TextInfo.ToUpperInvariant(), System.MemoryExtensions.ToUpperInvariant(), and System.Globalization.Ordinal.ToUpperOrdinal().