Terraria: System.Net.WebSockets.WebSocketHttpListenerDuplexStream.HttpListenerAsyncEventArgs.Dispose
Dispose()
void System.Net.WebSockets.WebSocketHttpListenerDuplexStream.HttpListenerAsyncEventArgs.Dispose () inline
Implements System.IDisposable.
Definition at line 140 of file WebSocketHttpListenerDuplexStream.cs.
        {
            _disposeCalled = true;
            if (Interlocked.CompareExchange(ref _operating, 2, 0) == 0)
            {
                GC.SuppressFinalize(this);
            }
        }
References System.Net.WebSockets.WebSocketHttpListenerDuplexStream.HttpListenerAsyncEventArgs._disposeCalled, System.Net.WebSockets.WebSocketHttpListenerDuplexStream.HttpListenerAsyncEventArgs._operating, System.Threading.Interlocked.CompareExchange(), and System.GC.SuppressFinalize().
Referenced by System.Net.WebSockets.WebSocketHttpListenerDuplexStream.HttpListenerAsyncEventArgs.Complete(), and System.Net.WebSockets.WebSocketHttpListenerDuplexStream.Dispose().