Terraria: System.Globalization.InvariantModeCasing.IndexOfIgnoreCase
IndexOfIgnoreCase()
static unsafe int System.Globalization.InvariantModeCasing.IndexOfIgnoreCase (ReadOnlySpan< char > source, ReadOnlySpan< char > value) inline static package
Definition at line 191 of file InvariantModeCasing.cs.
    {
        fixed (char* ptr = &MemoryMarshal.GetReference(source))
        {
            fixed (char* ptr3 = &MemoryMarshal.GetReference(value))
            {
                char* ptr2 = ptr + (source.Length - value.Length);
                char* ptr4 = ptr3 + value.Length - 1;
                for (char* ptr5 = ptr; ptr5 <= ptr2; ptr5++)
                {
                    char* ptr6 = ptr3;
                    char* ptr7 = ptr5;
                    while (ptr6 <= ptr4)
                    {
                        if (!char.IsHighSurrogate(*ptr6) || ptr6 == ptr4)
{
                            if (*ptr6 != *ptr7 && ToUpper(*ptr6) != ToUpper(*ptr7))
{
                                break;
                            }
                            ptr6++;
                            ptr7++;
                        }
                        else if (char.IsHighSurrogate(*ptr7) && char.IsLowSurrogate(ptr7[1]) && char.IsLowSurrogate(ptr6[1]))
{
                            if (!SurrogateCasing.Equal(*ptr7, ptr7[1], *ptr6, ptr6[1]))
{
                                break;
                            }
                            ptr7 += 2;
                            ptr6 += 2;
                        }
                        else
{
                            if (*ptr6 != *ptr7)
{
                                break;
                            }
                            ptr7++;
                            ptr6++;
                        }
                    }
                    if (ptr6 > ptr4)
                    {
                        return (int)(ptr5 - ptr);
                    }
                }
                return -1;
            }
        }
    }
References System.Globalization.SurrogateCasing.Equal(), System.source, System.Globalization.InvariantModeCasing.ToUpper(), and System.value.
Referenced by System.Globalization.Ordinal.IndexOfOrdinalIgnoreCase().