Terraria: System.Globalization.InvariantModeCasing.ToLower
ToLower() [1/3]
static char System.Globalization.InvariantModeCasing.ToLower (char c) inline static package
Definition at line 11 of file InvariantModeCasing.cs.
    {
        return CharUnicodeInfo.ToLower(c);
    }
References System.Globalization.CharUnicodeInfo.ToLower().
Referenced by System.Globalization.TextInfo.ToLower(), System.Globalization.InvariantModeCasing.ToLower(), System.Globalization.InvariantModeCasing.ToLower(), System.Globalization.TextInfo.ToLower(), System.MemoryExtensions.ToLower(), System.Globalization.TextInfo.ToLowerInvariant(), and System.MemoryExtensions.ToLowerInvariant().