Terraria: System.Net.WebSockets.WebSocketHttpListenerDuplexStream.HttpListenerAsyncEventArgs.UpdateDataChunk
UpdateDataChunk() [2/2]
unsafe void System.Net.WebSockets.WebSocketHttpListenerDuplexStream.HttpListenerAsyncEventArgs.UpdateDataChunk (int index, byte[] buffer, int offset, int count) inline private
Definition at line 234 of file WebSocketHttpListenerDuplexStream.cs.
        {
            if (buffer == null)
            {
                _dataChunks[index].pBuffer = null;
                _dataChunks[index].BufferLength = 0u;
                return;
            }
            if (_webSocket.InternalBuffer.IsInternalBuffer(buffer, offset, count))
            {
                _dataChunks[index].pBuffer = (byte*)(void*)_webSocket.InternalBuffer.ToIntPtr(offset);
            }
            else
            {
                _dataChunks[index].pBuffer = (byte*)(void*)_webSocket.InternalBuffer.ConvertPinnedSendPayloadToNative(buffer, offset, count);
            }
            _dataChunks[index].BufferLength = (uint)count;
        }
References System.Net.WebSockets.WebSocketHttpListenerDuplexStream.HttpListenerAsyncEventArgs._dataChunks, System.Net.WebSockets.WebSocketHttpListenerDuplexStream.HttpListenerAsyncEventArgs._webSocket, System.buffer, System.Net.WebSockets.WebSocketBuffer.ConvertPinnedSendPayloadToNative(), System.count, System.index, System.Net.WebSockets.WebSocketBase.InternalBuffer, System.Net.WebSockets.WebSocketBuffer.IsInternalBuffer(), System.offset, and System.Net.WebSockets.WebSocketBuffer.ToIntPtr().