Terraria: System.Net.WebSockets.WebSocketHttpListenerDuplexStream.HttpListenerAsyncEventArgs.FreeOverlapped
FreeOverlapped()
unsafe void System.Net.WebSockets.WebSocketHttpListenerDuplexStream.HttpListenerAsyncEventArgs.FreeOverlapped (bool checkForShutdown) inline private
Definition at line 155 of file WebSocketHttpListenerDuplexStream.cs.
        {
            if (!checkForShutdown || !Environment.HasShutdownStarted)
            {
                if (_ptrNativeOverlapped != null)
                {
                    _boundHandle.FreeNativeOverlapped(_ptrNativeOverlapped);
                    _ptrNativeOverlapped = null;
                }
                if (_dataChunksGCHandle.IsAllocated)
                {
                    _dataChunksGCHandle.Free();
                    _dataChunks = null;
                }
            }
        }
References System.Net.WebSockets.WebSocketHttpListenerDuplexStream.HttpListenerAsyncEventArgs._boundHandle, System.Net.WebSockets.WebSocketHttpListenerDuplexStream.HttpListenerAsyncEventArgs._dataChunks, System.Net.WebSockets.WebSocketHttpListenerDuplexStream.HttpListenerAsyncEventArgs._dataChunksGCHandle, System.Net.WebSockets.WebSocketHttpListenerDuplexStream.HttpListenerAsyncEventArgs._ptrNativeOverlapped, System.Runtime.InteropServices.GCHandle.Free(), System.Threading.ThreadPoolBoundHandle.FreeNativeOverlapped(), System.Environment.HasShutdownStarted, and System.Runtime.InteropServices.GCHandle.IsAllocated.
Referenced by System.Net.WebSockets.WebSocketHttpListenerDuplexStream.HttpListenerAsyncEventArgs.Complete().