Terraria: System.Net.WebSockets.WebSocketHttpListenerDuplexStream.HttpListenerAsyncEventArgs.UpdateDataChunk
UpdateDataChunk() [1/2]
void System.Net.WebSockets.WebSocketHttpListenerDuplexStream.HttpListenerAsyncEventArgs.UpdateDataChunk () inline private
Definition at line 205 of file WebSocketHttpListenerDuplexStream.cs.
        {
            if (_dataChunks == null)
            {
                _dataChunks = new global::Interop.HttpApi.HTTP_DATA_CHUNK[2];
                _dataChunksGCHandle = GCHandle.Alloc(_dataChunks, GCHandleType.Pinned);
                _dataChunks[0] = default(global::Interop.HttpApi.HTTP_DATA_CHUNK);
                _dataChunks[0].DataChunkType = global::Interop.HttpApi.HTTP_DATA_CHUNK_TYPE.HttpDataChunkFromMemory;
                _dataChunks[1] = default(global::Interop.HttpApi.HTTP_DATA_CHUNK);
                _dataChunks[1].DataChunkType = global::Interop.HttpApi.HTTP_DATA_CHUNK_TYPE.HttpDataChunkFromMemory;
            }
            if (_buffer != null)
            {
                UpdateDataChunk(0, _buffer, _offset, _count);
                UpdateDataChunk(1, null, 0, 0);
                _dataChunkCount = 1;
            }
            else if (_bufferList != null)
            {
                UpdateDataChunk(0, _bufferList[0].Array, _bufferList[0].Offset, _bufferList[0].Count);
                UpdateDataChunk(1, _bufferList[1].Array, _bufferList[1].Offset, _bufferList[1].Count);
                _dataChunkCount = 2;
            }
            else
            {
                _dataChunks = null;
            }
        }
References System.Net.WebSockets.WebSocketHttpListenerDuplexStream.HttpListenerAsyncEventArgs._buffer, System.Net.WebSockets.WebSocketHttpListenerDuplexStream.HttpListenerAsyncEventArgs._bufferList, System.Net.WebSockets.WebSocketHttpListenerDuplexStream.HttpListenerAsyncEventArgs._count, System.Net.WebSockets.WebSocketHttpListenerDuplexStream.HttpListenerAsyncEventArgs._dataChunkCount, System.Net.WebSockets.WebSocketHttpListenerDuplexStream.HttpListenerAsyncEventArgs._dataChunks, System.Net.WebSockets.WebSocketHttpListenerDuplexStream.HttpListenerAsyncEventArgs._dataChunksGCHandle, System.Net.WebSockets.WebSocketHttpListenerDuplexStream.HttpListenerAsyncEventArgs._offset, System.Runtime.InteropServices.GCHandle.Alloc(), System.Net.WebSockets.WebSocketHttpListenerDuplexStream.HttpListenerAsyncEventArgs.Count, System.Net.WebSockets.WebSocketHttpListenerDuplexStream.HttpListenerAsyncEventArgs.Offset, and System.Net.WebSockets.WebSocketHttpListenerDuplexStream.HttpListenerAsyncEventArgs.UpdateDataChunk().
Referenced by System.Net.WebSockets.WebSocketHttpListenerDuplexStream.HttpListenerAsyncEventArgs.StartOperationSend(), and System.Net.WebSockets.WebSocketHttpListenerDuplexStream.HttpListenerAsyncEventArgs.UpdateDataChunk().