Terraria: System.Text.RegularExpressions.RegexReplacement.GetOrCreate
GetOrCreate()
static RegexReplacement System.Text.RegularExpressions.RegexReplacement.GetOrCreate (WeakReference< RegexReplacement > replRef, string replacement, Hashtable caps, int capsize, Hashtable capnames, RegexOptions roptions) inline static
Definition at line 81 of file RegexReplacement.cs.
    {
        if (!replRef.TryGetTarget(out var target) || !target.Pattern.Equals(replacement))
        {
            target = RegexParser.ParseReplacement(replacement, roptions, caps, capsize, capnames);
            replRef.SetTarget(target);
        }
        return target;
    }
References System.Text.RegularExpressions.RegexParser.ParseReplacement(), and System.Text.RegularExpressions.replacement.
Referenced by System.Text.RegularExpressions.Regex.Replace(), and System.Text.RegularExpressions.Match.Result().