Terraria: System.Text.RegularExpressions.RegexReplacement.Replace
Replace()
string System.Text.RegularExpressions.RegexReplacement.Replace (Regex regex, string input, int count, int startat) inline
Definition at line 151 of file RegexReplacement.cs.
    {
        if (count < -1)
        {
            ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument.count, ExceptionResource.CountTooSmall);
        }
        if ((uint)startat > (uint)input.Length)
        {
            ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument.startat, ExceptionResource.BeginIndexNotNegative);
        }
        if (count == 0)
        {
            return input;
        }
        (RegexReplacement, SegmentStringBuilder, ReadOnlyMemory<char>, int, int) state2 = (this, SegmentStringBuilder.Create(), input.AsMemory(), 0, count);
        if (!regex.RightToLeft)
        {
            regex.Run<(RegexReplacement, SegmentStringBuilder, ReadOnlyMemory<char>, int, int)>(input, startat, ref state2, delegate(ref (RegexReplacement thisRef, SegmentStringBuilder segments, ReadOnlyMemory<char> inputMemory, int prevat, int count) state, Match match)
            {
                state.segments.Add(state.inputMemory.Slice(state.prevat, match.Index - state.prevat));
                state.prevat = match.Index + match.Length;
                state.thisRef.ReplacementImpl(ref state.segments, match);
                return --state.count != 0;
            }, reuseMatchObject: true);
            if (state2.Item2.Count == 0)
            {
                return input;
            }
            state2.Item2.Add(state2.Item3.Slice(state2.Item4, input.Length - state2.Item4));
        }
        else
        {
            state2.Item4 = input.Length;
            regex.Run<(RegexReplacement, SegmentStringBuilder, ReadOnlyMemory<char>, int, int)>(input, startat, ref state2, delegate(ref (RegexReplacement thisRef, SegmentStringBuilder segments, ReadOnlyMemory<char> inputMemory, int prevat, int count) state, Match match)
            {
                state.segments.Add(state.inputMemory.Slice(match.Index + match.Length, state.prevat - match.Index - match.Length));
                state.prevat = match.Index;
                state.thisRef.ReplacementImplRTL(ref state.segments, match);
                return --state.count != 0;
            }, reuseMatchObject: true);
            if (state2.Item2.Count == 0)
            {
                return input;
            }
            state2.Item2.Add(state2.Item3.Slice(0, state2.Item4));
            state2.Item2.AsSpan().Reverse();
        }
        return state2.Item2.ToString();
    }
References System.Text.RegularExpressions.RegexReplacement.RegexReplacement(), System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Text.RegularExpressions.count, System.Text.SegmentStringBuilder.Create(), System.Text.RegularExpressions.input, System.match, System.Text.RegularExpressions.startat, System.state, and System.Text.RegularExpressions.ThrowHelper.ThrowArgumentOutOfRangeException().