Terraria: System.Data.TypeLimiter.EnterRestrictedScope
EnterRestrictedScope() [1/2]
static IDisposable System.Data.TypeLimiter.EnterRestrictedScope (DataSet dataSet) inline static
Definition at line 173 of file TypeLimiter.cs.
    {
        if (IsTypeLimitingDisabled)
        {
            return null;
        }
        return s_activeScope = new Scope(s_activeScope, GetPreviouslyDeclaredDataTypes(dataSet));
    }
References System.Data.TypeLimiter.GetPreviouslyDeclaredDataTypes(), System.Data.TypeLimiter.IsTypeLimitingDisabled, and System.Data.TypeLimiter.s_activeScope.
Referenced by System.Data.DataSet.ReadXml(), System.Data.DataTable.ReadXml(), System.Data.DataSet.ReadXml(), and System.Data.DataTable.ReadXml().