Terraria: System.Net.Http.ConnectHelper.ConnectQuicAsync
ConnectQuicAsync()
static async ValueTask< QuicConnection > System.Net.Http.ConnectHelper.ConnectQuicAsync (HttpRequestMessage request, QuicImplementationProvider quicImplementationProvider, DnsEndPoint endPoint, SslClientAuthenticationOptions clientAuthenticationOptions, CancellationToken cancellationToken) inline static
Definition at line 90 of file ConnectHelper.cs.
    {
        clientAuthenticationOptions = SetUpRemoteCertificateValidationCallback(clientAuthenticationOptions, request);
        QuicConnection con = new QuicConnection(quicImplementationProvider, endPoint, clientAuthenticationOptions);
        try
        {
            await con.ConnectAsync(cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
            return con;
        }
        catch (Exception error)
        {
            con.Dispose();
            throw CreateWrappedException(error, endPoint.Host, endPoint.Port, cancellationToken);
        }
    }
References System.cancellationToken, System.Threading.Tasks.ValueTask< TResult >.ConfigureAwait(), System.Net.Quic.QuicConnection.ConnectAsync(), System.Net.Http.ConnectHelper.CreateWrappedException(), System.Net.Quic.QuicConnection.Dispose(), System.Net.DnsEndPoint.Host, System.Net.DnsEndPoint.Port, and System.Net.Http.ConnectHelper.SetUpRemoteCertificateValidationCallback().
Referenced by System.Net.Http.HttpConnectionPool.GetHttp3ConnectionAsync().