Terraria: System.Net.Http.ConnectHelper.EstablishSslConnectionAsync
EstablishSslConnectionAsync()
static async ValueTask< SslStream > System.Net.Http.ConnectHelper.EstablishSslConnectionAsync (SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, bool async, Stream stream, CancellationToken cancellationToken) inline static
Definition at line 45 of file ConnectHelper.cs.
    {
        sslOptions = SetUpRemoteCertificateValidationCallback(sslOptions, request);
        SslStream sslStream = new SslStream(stream);
        try
        {
            if (async)
            {
                await sslStream.AuthenticateAsClientAsync(sslOptions, cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
            }
            else
            {
                using (cancellationToken.UnsafeRegister(delegate(object s)
                {
                    ((Stream)s).Dispose();
                }, stream))
                {
                    sslStream.AuthenticateAsClient(sslOptions);
                }
            }
        }
        catch (Exception ex)
        {
            sslStream.Dispose();
            if (ex is OperationCanceledException)
            {
                throw;
            }
            if (CancellationHelper.ShouldWrapInOperationCanceledException(ex, cancellationToken))
            {
                throw CancellationHelper.CreateOperationCanceledException(ex, cancellationToken);
            }
            throw new HttpRequestException(System.SR.net_http_ssl_connection_failed, ex);
        }
        if (cancellationToken.IsCancellationRequested)
        {
            sslStream.Dispose();
            throw CancellationHelper.CreateOperationCanceledException(null, cancellationToken);
        }
        return sslStream;
    }
References System.Net.Security.SslStream.AuthenticateAsClient(), System.Net.Security.SslStream.AuthenticateAsClientAsync(), System.cancellationToken, System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.Net.Http.CancellationHelper.CreateOperationCanceledException(), System.Net.Security.SslStream.Dispose(), System.SR.net_http_ssl_connection_failed, System.s, System.Net.Http.ConnectHelper.SetUpRemoteCertificateValidationCallback(), System.Net.Http.CancellationHelper.ShouldWrapInOperationCanceledException(), and System.stream.
Referenced by System.Net.Http.HttpConnectionPool.ConnectAsync().