Terraria: DropBasedOnExpertMode.ReportDroprates
ReportDroprates()
void DropBasedOnExpertMode.ReportDroprates (List< DropRateInfo > drops, DropRateInfoChainFeed ratesInfo) inline
Implements IItemDropRule.
     {
         DropRateInfoChainFeed ratesInfo2 = ratesInfo.With(1f);
         ratesInfo2.AddCondition(new Conditions.IsExpert());
         ruleForExpertMode.ReportDroprates(drops, ratesInfo2);
         DropRateInfoChainFeed ratesInfo3 = ratesInfo.With(1f);
         ratesInfo3.AddCondition(new Conditions.NotExpert());
         ruleForNormalMode.ReportDroprates(drops, ratesInfo3);
         Chains.ReportDroprates(ChainedRules, 1f, drops, ratesInfo);
     }
References DropRateInfoChainFeed.AddCondition(), ChainedRules, IItemDropRule.ReportDroprates(), Chains.ReportDroprates(), ruleForExpertMode, ruleForNormalMode, and DropRateInfoChainFeed.With().