Terraria: System.IriHelper.EscapeUnescapeIri
EscapeUnescapeIri()
static unsafe string System.IriHelper.EscapeUnescapeIri (char * pInput, int start, int end, UriComponents component) inline static package
Definition at line 84 of file IriHelper.cs.
    {
        int num = end - start;
        System.Text.ValueStringBuilder valueStringBuilder;
        if (num <= 512)
        {
            Span<char> initialBuffer = stackalloc char[512];
            valueStringBuilder = new System.Text.ValueStringBuilder(initialBuffer);
        }
        else
        {
            valueStringBuilder = new System.Text.ValueStringBuilder(num);
        }
        System.Text.ValueStringBuilder to = valueStringBuilder;
        Span<byte> destination = stackalloc byte[4];
        for (int i = start; i < end; i++)
        {
            char c = pInput[i];
            if (c == '%')
            {
                if (end - i > 2)
                {
                    c = UriHelper.DecodeHexChars(pInput[i + 1], pInput[i + 2]);
                    if (c == '\uffff' || c == '%' || CheckIsReserved(c, component) || UriHelper.IsNotSafeForUnescape(c))
                    {
                        to.Append(pInput[i++]);
                        to.Append(pInput[i++]);
                        to.Append(pInput[i]);
                    }
                    else if (c <= '\u007f')
                    {
                        to.Append(c);
                        i += 2;
                    }
                    else
                    {
                        int num2 = PercentEncodingHelper.UnescapePercentEncodedUTF8Sequence(pInput + i, end - i, ref to, component == UriComponents.Query, iriParsing: true);
                        i += num2 - 1;
                    }
                }
                else
                {
                    to.Append(pInput[i]);
                }
            }
            else if (c > '\u007f')
            {
                bool isSurrogatePair = false;
                char c2 = '\0';
                bool flag;
                if (char.IsHighSurrogate(c) && i + 1 < end)
                {
                    c2 = pInput[i + 1];
                    flag = CheckIriUnicodeRange(c, c2, out isSurrogatePair, component == UriComponents.Query);
                }
                else
                {
                    flag = CheckIriUnicodeRange(c, component == UriComponents.Query);
                }
                if (flag)
                {
                    to.Append(c);
                    if (isSurrogatePair)
                    {
                        to.Append(c2);
                    }
                }
                else
                {
                    Rune result;
                    if (isSurrogatePair)
                    {
                        result = new Rune(c, c2);
                    }
                    else if (!Rune.TryCreate(c, out result))
                    {
                        result = Rune.ReplacementChar;
                    }
                    Span<byte> span = destination[..result.EncodeToUtf8(destination)];
                    Span<byte> span2 = span;
                    for (int j = 0; j < span2.Length; j++)
                    {
                        byte b = span2[j];
                        UriHelper.EscapeAsciiChar(b, ref to);
                    }
                }
                if (isSurrogatePair)
                {
                    i++;
                }
            }
            else
            {
                to.Append(pInput[i]);
            }
        }
        return to.ToString();
    }
References System.Text.ValueStringBuilder.Append(), System.IriHelper.CheckIriUnicodeRange(), System.IriHelper.CheckIsReserved(), System.UriHelper.DecodeHexChars(), System.destination, System.Text.Rune.EncodeToUtf8(), System.UriHelper.EscapeAsciiChar(), System.UriHelper.IsNotSafeForUnescape(), System.Span< T >.Length, System.Text.Rune.ReplacementChar, System.start, System.Text.ValueStringBuilder.ToString(), System.Text.Rune.TryCreate(), and System.PercentEncodingHelper.UnescapePercentEncodedUTF8Sequence().
Referenced by System.Uri.CheckAuthorityHelper(), and System.Uri.EscapeUnescapeIri().