Terraria: System.IriHelper.CheckIriUnicodeRange
CheckIriUnicodeRange() [2/3]
static bool System.IriHelper.CheckIriUnicodeRange (char unicode, bool isQuery) inline static package
Definition at line 8 of file IriHelper.cs.
    {
        if (!IsInInclusiveRange(unicode, 160u, 55295u) && !IsInInclusiveRange(unicode, 63744u, 64975u) && !IsInInclusiveRange(unicode, 65008u, 65519u))
        {
            if (isQuery)
            {
                return IsInInclusiveRange(unicode, 57344u, 63743u);
            }
            return false;
        }
        return true;
    }
References System.IriHelper.IsInInclusiveRange().
Referenced by System.Uri.CheckCanonical(), System.IriHelper.EscapeUnescapeIri(), System.PercentEncodingHelper.UnescapePercentEncodedUTF8Sequence(), and System.UriHelper.UnescapeString().