Terraria: System.Linq.Parallel.HashJoinQueryOperatorEnumerator.MoveNext
MoveNext() [2/2]
override bool System.Linq.Parallel.HashJoinQueryOperatorEnumerator< TLeftInput, TLeftKey, TRightInput, TRightKey, THashKey, TOutput, TOutputKey >.MoveNext ([AllowNull] ref TOutput currentElement, [AllowNull] ref TOutputKey currentKey) inline package
Definition at line 44 of file HashJoinQueryOperatorEnumerator.cs.
    {
        Mutables mutables = _mutables;
        if (mutables == null)
        {
            mutables = (_mutables = new Mutables());
            mutables._rightHashLookup = _rightLookupBuilder.BuildHashLookup(_cancellationToken);
        }
        ListChunk<Pair<TRightInput, TRightKey>> currentRightMatches = mutables._currentRightMatches;
        if (currentRightMatches != null && mutables._currentRightMatchesIndex == currentRightMatches.Count)
        {
            mutables._currentRightMatches = currentRightMatches.Next;
            mutables._currentRightMatchesIndex = 0;
        }
        if (mutables._currentRightMatches == null)
        {
            Pair<TLeftInput, THashKey> currentElement2 = default(Pair<TLeftInput, THashKey>);
            TLeftKey currentKey2 = default(TLeftKey);
            while (_leftSource.MoveNext(ref currentElement2, ref currentKey2))
            {
                if ((mutables._outputLoopCount++ & 0x3F) == 0)
                {
                    _cancellationToken.ThrowIfCancellationRequested();
                }
                HashLookupValueList<TRightInput, TRightKey> value = default(HashLookupValueList<TRightInput, TRightKey>);
                TLeftInput first = currentElement2.First;
                THashKey second = currentElement2.Second;
                if (second != null && mutables._rightHashLookup.TryGetValue(second, ref value))
                {
                    mutables._currentRightMatches = value.Tail;
                    mutables._currentRightMatchesIndex = 0;
                    currentElement = _resultSelector(first, value.Head.First);
                    currentKey = _outputKeyBuilder.Combine(currentKey2, value.Head.Second);
                    if (value.Tail != null)
                    {
                        mutables._currentLeft = first;
                        mutables._currentLeftKey = currentKey2;
                    }
                    return true;
                }
            }
            return false;
        }
        Pair<TRightInput, TRightKey> pair = mutables._currentRightMatches._chunk[mutables._currentRightMatchesIndex];
        currentElement = _resultSelector(mutables._currentLeft, pair.First);
        currentKey = _outputKeyBuilder.Combine(mutables._currentLeftKey, pair.Second);
        mutables._currentRightMatchesIndex++;
        return true;
    }
References System.Linq.Parallel.HashJoinQueryOperatorEnumerator< TLeftInput, TLeftKey, TRightInput, TRightKey, THashKey, TOutput, TOutputKey >._cancellationToken, System.Linq.Parallel.HashJoinQueryOperatorEnumerator< TLeftInput, TLeftKey, TRightInput, TRightKey, THashKey, TOutput, TOutputKey >.Mutables._currentLeft, System.Linq.Parallel.HashJoinQueryOperatorEnumerator< TLeftInput, TLeftKey, TRightInput, TRightKey, THashKey, TOutput, TOutputKey >.Mutables._currentLeftKey, System.Linq.Parallel.HashJoinQueryOperatorEnumerator< TLeftInput, TLeftKey, TRightInput, TRightKey, THashKey, TOutput, TOutputKey >.Mutables._currentRightMatches, System.Linq.Parallel.HashJoinQueryOperatorEnumerator< TLeftInput, TLeftKey, TRightInput, TRightKey, THashKey, TOutput, TOutputKey >.Mutables._currentRightMatchesIndex, System.Linq.Parallel.HashJoinQueryOperatorEnumerator< TLeftInput, TLeftKey, TRightInput, TRightKey, THashKey, TOutput, TOutputKey >._leftSource, System.Linq.Parallel.HashJoinQueryOperatorEnumerator< TLeftInput, TLeftKey, TRightInput, TRightKey, THashKey, TOutput, TOutputKey >._mutables, System.Linq.Parallel.HashJoinQueryOperatorEnumerator< TLeftInput, TLeftKey, TRightInput, TRightKey, THashKey, TOutput, TOutputKey >._outputKeyBuilder, System.Linq.Parallel.HashJoinQueryOperatorEnumerator< TLeftInput, TLeftKey, TRightInput, TRightKey, THashKey, TOutput, TOutputKey >.Mutables._outputLoopCount, System.Linq.Parallel.HashJoinQueryOperatorEnumerator< TLeftInput, TLeftKey, TRightInput, TRightKey, THashKey, TOutput, TOutputKey >._resultSelector, System.Linq.Parallel.HashJoinQueryOperatorEnumerator< TLeftInput, TLeftKey, TRightInput, TRightKey, THashKey, TOutput, TOutputKey >.Mutables._rightHashLookup, System.Linq.Parallel.HashJoinQueryOperatorEnumerator< TLeftInput, TLeftKey, TRightInput, TRightKey, THashKey, TOutput, TOutputKey >._rightLookupBuilder, System.Linq.Parallel.HashLookupBuilder< TElement, TOrderKey, THashKey >.BuildHashLookup(), System.Linq.Parallel.ListChunk< TInputOutput >.Count, System.Linq.Parallel.Pair< T, U >.First, System.Linq.first, System.Linq.Parallel.ListChunk< TInputOutput >.Next, System.Linq.Parallel.Pair< T, U >.Second, System.Linq.second, System.Threading.CancellationToken.ThrowIfCancellationRequested(), System.Linq.Parallel.HashJoinHashLookup< THashKey, TElement, TOrderKey >.TryGetValue(), and System.value.