Terraria: RandomizedFrameParticle.SetTypeInfo
SetTypeInfo()
void RandomizedFrameParticle.SetTypeInfo (int animationFramesAmount, int gameFramesPerAnimationFrame, float timeToLive) inline
     {
         _timeTolive = timeToLive;
         GameFramesPerAnimationFrame = gameFramesPerAnimationFrame;
         AnimationFramesAmount = animationFramesAmount;
         RandomizeFrame();
     }
References _timeTolive, AnimationFramesAmount, GameFramesPerAnimationFrame, and RandomizeFrame().
Referenced by ParticleOrchestrator.Spawn_BlackLightningHit(), and ParticleOrchestrator.Spawn_BlackLightningSmall().