Terraria: System.Data.SqlTypes.StreamOnSqlBytes.Read
Read() [1/2]
override int System.Data.SqlTypes.StreamOnSqlBytes.Read (byte[] buffer, int offset, int count) inline
Definition at line 111 of file StreamOnSqlBytes.cs.
    {
        CheckIfStreamClosed("Read");
        Stream.ValidateBufferArguments(buffer, offset, count);
        int num = (int)_sb.Read(_lPosition, buffer, offset, count);
        _lPosition += num;
        return num;
    }
References System.Data.SqlTypes.StreamOnSqlBytes._lPosition, System.Data.SqlTypes.StreamOnSqlBytes._sb, System.buffer, System.Data.SqlTypes.StreamOnSqlBytes.CheckIfStreamClosed(), System.count, System.offset, System.Data.SqlTypes.SqlBytes.Read(), and System.IO.Stream.ValidateBufferArguments().