Terraria: Terraria.GameContent.Bestiary.BestiaryDatabaseNPCsPopulator.AddNPCBiomeRelationships_AddDecorations_Automated
AddNPCBiomeRelationships_AddDecorations_Automated()
void Terraria.GameContent.Bestiary.BestiaryDatabaseNPCsPopulator.AddNPCBiomeRelationships_AddDecorations_Automated () inline private
    {
        foreach (KeyValuePair<int, NPC> item in ContentSamples.NpcsByNetId)
        {
            BestiaryEntry bestiaryEntry = FindEntryByNPCID(item.Key);
            if (bestiaryEntry.Info.Contains(CommonTags.SpawnConditions.Events.Rain))
            {
                if (bestiaryEntry.Info.Contains(CommonTags.SpawnConditions.Biomes.Snow))
                {
                    bestiaryEntry.AddTags(CommonTags.SpawnConditions.Visuals.Blizzard);
                }
                else
                {
                    bestiaryEntry.AddTags(CommonTags.SpawnConditions.Visuals.Rain);
                }
                continue;
            }
            if (bestiaryEntry.Info.Contains(CommonTags.SpawnConditions.Events.Eclipse))
            {
                bestiaryEntry.AddTags(CommonTags.SpawnConditions.Visuals.EclipseSun);
            }
            if (bestiaryEntry.Info.Contains(CommonTags.SpawnConditions.Times.NightTime))
            {
                bestiaryEntry.AddTags(CommonTags.SpawnConditions.Visuals.Moon);
            }
            if (bestiaryEntry.Info.Contains(CommonTags.SpawnConditions.Times.DayTime))
            {
                bestiaryEntry.AddTags(CommonTags.SpawnConditions.Visuals.Sun);
            }
            if (bestiaryEntry.Info.Contains(CommonTags.SpawnConditions.Invasions.PumpkinMoon))
            {
                bestiaryEntry.AddTags(CommonTags.SpawnConditions.Visuals.PumpkinMoon);
            }
            if (bestiaryEntry.Info.Contains(CommonTags.SpawnConditions.Invasions.FrostMoon))
            {
                bestiaryEntry.AddTags(CommonTags.SpawnConditions.Visuals.FrostMoon);
            }
            if (bestiaryEntry.Info.Contains(CommonTags.SpawnConditions.Biomes.Meteor))
            {
                bestiaryEntry.AddTags(CommonTags.SpawnConditions.Visuals.Moon);
                bestiaryEntry.AddTags(CommonTags.SpawnConditions.Visuals.Meteor);
            }
        }
    }
References Terraria.GameContent.Bestiary.BestiaryEntry.AddTags(), Terraria.GameContent.Bestiary.BestiaryDatabaseNPCsPopulator.CommonTags.SpawnConditions.Visuals.Blizzard, Terraria.GameContent.Bestiary.BestiaryDatabaseNPCsPopulator.CommonTags.SpawnConditions.Times.DayTime, Terraria.GameContent.Bestiary.BestiaryDatabaseNPCsPopulator.CommonTags.SpawnConditions.Events.Eclipse, Terraria.GameContent.Bestiary.BestiaryDatabaseNPCsPopulator.CommonTags.SpawnConditions.Visuals.EclipseSun, Terraria.GameContent.Bestiary.BestiaryDatabaseNPCsPopulator.FindEntryByNPCID(), Terraria.GameContent.Bestiary.BestiaryDatabaseNPCsPopulator.CommonTags.SpawnConditions.Invasions.FrostMoon, Terraria.GameContent.Bestiary.BestiaryDatabaseNPCsPopulator.CommonTags.SpawnConditions.Visuals.FrostMoon, Terraria.GameContent.Bestiary.BestiaryEntry.Info, Terraria.GameContent.Bestiary.BestiaryDatabaseNPCsPopulator.CommonTags.SpawnConditions.Biomes.Meteor, Terraria.GameContent.Bestiary.BestiaryDatabaseNPCsPopulator.CommonTags.SpawnConditions.Visuals.Meteor, Terraria.GameContent.Bestiary.BestiaryDatabaseNPCsPopulator.CommonTags.SpawnConditions.Visuals.Moon, Terraria.GameContent.Bestiary.BestiaryDatabaseNPCsPopulator.CommonTags.SpawnConditions.Times.NightTime, Terraria.ID.ContentSamples.NpcsByNetId, Terraria.GameContent.Bestiary.BestiaryDatabaseNPCsPopulator.CommonTags.SpawnConditions.Invasions.PumpkinMoon, Terraria.GameContent.Bestiary.BestiaryDatabaseNPCsPopulator.CommonTags.SpawnConditions.Visuals.PumpkinMoon, Terraria.GameContent.Bestiary.BestiaryDatabaseNPCsPopulator.CommonTags.SpawnConditions.Events.Rain, Terraria.GameContent.Bestiary.BestiaryDatabaseNPCsPopulator.CommonTags.SpawnConditions.Visuals.Rain, Terraria.GameContent.Bestiary.BestiaryDatabaseNPCsPopulator.CommonTags.SpawnConditions.Biomes.Snow, and Terraria.GameContent.Bestiary.BestiaryDatabaseNPCsPopulator.CommonTags.SpawnConditions.Visuals.Sun.
Referenced by Terraria.GameContent.Bestiary.BestiaryDatabaseNPCsPopulator.Populate().