Terraria: System.Runtime.Serialization.EnumDataContract.WriteEnumValue
WriteEnumValue()
void System.Runtime.Serialization.EnumDataContract.WriteEnumValue (XmlWriterDelegator writer, object value) inline package
Definition at line 281 of file EnumDataContract.cs.
    {
        long num = (IsULong ? ((long)Convert.ToUInt64(value, null)) : Convert.ToInt64(value, null));
        for (int i = 0; i < Values.Count; i++)
        {
            if (num == Values[i])
            {
                writer.WriteString(ChildElementNames[i].Value);
                return;
            }
        }
        if (IsFlags)
        {
            int num2 = -1;
            bool flag = true;
            for (int j = 0; j < Values.Count; j++)
            {
                long num3 = Values[j];
                if (num3 == 0L)
                {
                    num2 = j;
                    continue;
                }
                if (num == 0L)
                {
                    break;
                }
                if ((num3 & num) == num3)
                {
                    if (flag)
                    {
                        flag = false;
                    }
                    else
                    {
                        writer.WriteString(DictionaryGlobals.Space.Value);
                    }
                    writer.WriteString(ChildElementNames[j].Value);
                    num &= ~num3;
                }
            }
            if (num != 0L)
            {
                throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(XmlObjectSerializer.CreateSerializationException(System.SR.Format(System.SR.InvalidEnumValueOnWrite, value, DataContract.GetClrTypeFullName(base.UnderlyingType))));
            }
            if (flag && num2 >= 0)
            {
                writer.WriteString(ChildElementNames[num2].Value);
            }
            return;
        }
        throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(XmlObjectSerializer.CreateSerializationException(System.SR.Format(System.SR.InvalidEnumValueOnWrite, value, DataContract.GetClrTypeFullName(base.UnderlyingType))));
    }
References System.Runtime.Serialization.EnumDataContract.ChildElementNames, System.Collections.Generic.List< T >.Count, System.Runtime.Serialization.XmlObjectSerializer.CreateSerializationException(), System.Runtime.Serialization.Dictionary, System.SR.Format(), System.Runtime.Serialization.DataContract.GetClrTypeFullName(), System.SR.InvalidEnumValueOnWrite, System.Runtime.Serialization.EnumDataContract.IsFlags, System.Runtime.Serialization.EnumDataContract.IsULong, System.L, System.Runtime.Serialization.DictionaryGlobals.Space, System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperError(), System.Convert.ToInt64(), System.Convert.ToUInt64(), System.value, System.Runtime.Serialization.EnumDataContract.Values, and System.writer.
Referenced by System.Runtime.Serialization.EnumDataContract.WriteXmlValue().