Terraria: System.Runtime.Serialization.EnumDataContract.ReadEnumValue
ReadEnumValue() [2/2]
object System.Runtime.Serialization.EnumDataContract.ReadEnumValue (XmlReaderDelegator reader) inline package
Definition at line 335 of file EnumDataContract.cs.
    {
        string text = reader.ReadElementContentAsString();
        long num = 0L;
        int i = 0;
        if (IsFlags)
        {
            for (; i < text.Length && text[i] == ' '; i++)
            {
            }
            int num2 = i;
            int num3 = 0;
            for (; i < text.Length; i++)
            {
                if (text[i] == ' ')
                {
                    num3 = i - num2;
                    if (num3 > 0)
                    {
                        num |= ReadEnumValue(text, num2, num3);
                    }
                    for (i++; i < text.Length && text[i] == ' '; i++)
                    {
                    }
                    num2 = i;
                    if (i == text.Length)
                    {
                        break;
                    }
                }
            }
            num3 = i - num2;
            if (num3 > 0)
            {
                num |= ReadEnumValue(text, num2, num3);
            }
        }
        else
        {
            if (text.Length == 0)
            {
                throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(XmlObjectSerializer.CreateSerializationException(System.SR.Format(System.SR.InvalidEnumValueOnRead, text, DataContract.GetClrTypeFullName(base.UnderlyingType))));
            }
            num = ReadEnumValue(text, 0, text.Length);
        }
        if (IsULong)
        {
            return Enum.ToObject(base.UnderlyingType, (object)(ulong)num);
        }
        return Enum.ToObject(base.UnderlyingType, (object)num);
    }
References System.Runtime.Serialization.XmlObjectSerializer.CreateSerializationException(), System.Runtime.Serialization.Dictionary, System.SR.Format(), System.Runtime.Serialization.DataContract.GetClrTypeFullName(), System.SR.InvalidEnumValueOnRead, System.Runtime.Serialization.EnumDataContract.IsFlags, System.Runtime.Serialization.EnumDataContract.IsULong, System.L, System.Runtime.Serialization.XmlReaderDelegator.ReadElementContentAsString(), System.Runtime.Serialization.EnumDataContract.ReadEnumValue(), System.text, System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperError(), and System.Enum.ToObject().
Referenced by System.Runtime.Serialization.EnumDataContract.ReadEnumValue(), and System.Runtime.Serialization.EnumDataContract.ReadXmlValue().