Terraria: System.Runtime.Serialization.EnumDataContract.ReadEnumValue
ReadEnumValue() [1/2]
long System.Runtime.Serialization.EnumDataContract.ReadEnumValue (string value, int index, int count) inline private
Definition at line 387 of file EnumDataContract.cs.
    {
        for (int i = 0; i < Members.Count; i++)
        {
            string name = Members[i].Name;
            if (name.Length == count && string.CompareOrdinal(value, index, name, 0, count) == 0)
            {
                return Values[i];
            }
        }
        throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(XmlObjectSerializer.CreateSerializationException(System.SR.Format(System.SR.InvalidEnumValueOnRead, value.Substring(index, count), DataContract.GetClrTypeFullName(base.UnderlyingType))));
    }
References System.count, System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Runtime.Serialization.XmlObjectSerializer.CreateSerializationException(), System.SR.Format(), System.Runtime.Serialization.DataContract.GetClrTypeFullName(), System.index, System.SR.InvalidEnumValueOnRead, System.Runtime.Serialization.EnumDataContract.Members, System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperError(), System.value, and System.Runtime.Serialization.EnumDataContract.Values.