Terraria: System.Linq.Expressions.Compiler.ILGen.EmitDefault
EmitDefault()
static void System.Linq.Expressions.Compiler.ILGen.EmitDefault (this ILGenerator il, Type type, ILocalCache locals) inline static package
Definition at line 844 of file ILGen.cs.
    {
        switch (type.GetTypeCode())
        {
        case TypeCode.DateTime:
            il.Emit(OpCodes.Ldsfld, CachedReflectionInfo.DateTime_MinValue);
            break;
        case TypeCode.Object:
            if (type.IsValueType)
            {
                LocalBuilder local = locals.GetLocal(type);
                il.Emit(OpCodes.Ldloca, local);
                il.Emit(OpCodes.Initobj, type);
                il.Emit(OpCodes.Ldloc, local);
                locals.FreeLocal(local);
                break;
            }
            goto case TypeCode.Empty;
        case TypeCode.Empty:
        case TypeCode.DBNull:
        case TypeCode.String:
            il.Emit(OpCodes.Ldnull);
            break;
        case TypeCode.Boolean:
        case TypeCode.Char:
        case TypeCode.SByte:
        case TypeCode.Byte:
        case TypeCode.Int16:
        case TypeCode.UInt16:
        case TypeCode.Int32:
        case TypeCode.UInt32:
            il.Emit(OpCodes.Ldc_I4_0);
            break;
        case TypeCode.Int64:
        case TypeCode.UInt64:
            il.Emit(OpCodes.Ldc_I4_0);
            il.Emit(OpCodes.Conv_I8);
            break;
        case TypeCode.Single:
            il.Emit(OpCodes.Ldc_R4, 0f);
            break;
        case TypeCode.Double:
            il.Emit(OpCodes.Ldc_R8, 0.0);
            break;
        case TypeCode.Decimal:
            il.Emit(OpCodes.Ldsfld, CachedReflectionInfo.Decimal_Zero);
            break;
        default:
            throw ContractUtils.Unreachable;
        }
    }
References System.Reflection.Emit.OpCodes.Conv_I8, System.Linq.Expressions.CachedReflectionInfo.DateTime_MinValue, System.Linq.Expressions.CachedReflectionInfo.Decimal_Zero, System.Reflection.Emit.ILGenerator.Emit(), System.Linq.Expressions.Compiler.ILocalCache.FreeLocal(), System.Linq.Expressions.Compiler.ILocalCache.GetLocal(), System.Reflection.Emit.OpCodes.Initobj, System.Reflection.Emit.OpCodes.Ldc_I4_0, System.Reflection.Emit.OpCodes.Ldc_R4, System.Reflection.Emit.OpCodes.Ldc_R8, System.Reflection.Emit.OpCodes.Ldloc, System.Reflection.Emit.OpCodes.Ldloca, System.Reflection.Emit.OpCodes.Ldnull, System.Reflection.Emit.OpCodes.Ldsfld, System.type, and System.Dynamic.Utils.ContractUtils.Unreachable.