Terraria: System.Linq.Expressions.Compiler.ILGen.EmitArray
EmitArray() [1/2]
static void System.Linq.Expressions.Compiler.ILGen.EmitArray (this ILGenerator il, Type arrayType) inline static package
Definition at line 757 of file ILGen.cs.
    {
        if (arrayType.IsSZArray)
        {
            il.Emit(OpCodes.Newarr, arrayType.GetElementType());
            return;
        }
        Type[] array = new Type[arrayType.GetArrayRank()];
        for (int i = 0; i < array.Length; i++)
        {
            array[i] = typeof(int);
        }
        ConstructorInfo constructor = arrayType.GetConstructor(array);
        il.EmitNew(constructor);
    }
References System.array, System.Reflection.Emit.ILGenerator.Emit(), System.Type.GetArrayRank(), System.Type.GetConstructor(), System.Type.GetElementType(), System.Type.IsSZArray, and System.Reflection.Emit.OpCodes.Newarr.