Terraria: System.Linq.Expressions.Compiler.ILGen.EmitNullableToNullableConversion
EmitNullableToNullableConversion()
static void System.Linq.Expressions.Compiler.ILGen.EmitNullableToNullableConversion (this ILGenerator il, Type typeFrom, Type typeTo, bool isChecked, ILocalCache locals) inline static private
Definition at line 651 of file ILGen.cs.
    {
        LocalBuilder local = locals.GetLocal(typeFrom);
        il.Emit(OpCodes.Stloc, local);
        il.Emit(OpCodes.Ldloca, local);
        il.EmitHasValue(typeFrom);
        Label label = il.DefineLabel();
        il.Emit(OpCodes.Brfalse_S, label);
        il.Emit(OpCodes.Ldloca, local);
        locals.FreeLocal(local);
        il.EmitGetValueOrDefault(typeFrom);
        Type nonNullableType = typeFrom.GetNonNullableType();
        Type nonNullableType2 = typeTo.GetNonNullableType();
        il.EmitConvertToType(nonNullableType, nonNullableType2, isChecked, locals);
        ConstructorInfo nullableConstructor = TypeUtils.GetNullableConstructor(typeTo);
        il.Emit(OpCodes.Newobj, nullableConstructor);
        Label label2 = il.DefineLabel();
        il.Emit(OpCodes.Br_S, label2);
        il.MarkLabel(label);
        LocalBuilder local2 = locals.GetLocal(typeTo);
        il.Emit(OpCodes.Ldloca, local2);
        il.Emit(OpCodes.Initobj, typeTo);
        il.Emit(OpCodes.Ldloc, local2);
        locals.FreeLocal(local2);
        il.MarkLabel(label2);
    }
References System.Reflection.Emit.OpCodes.Br_S, System.Reflection.Emit.OpCodes.Brfalse_S, System.Reflection.Emit.ILGenerator.DefineLabel(), System.Reflection.Emit.ILGenerator.Emit(), System.Linq.Expressions.Compiler.ILocalCache.FreeLocal(), System.Linq.Expressions.Compiler.ILocalCache.GetLocal(), System.Dynamic.Utils.TypeUtils.GetNullableConstructor(), System.Reflection.Emit.OpCodes.Initobj, System.Reflection.Emit.OpCodes.Ldloc, System.Reflection.Emit.OpCodes.Ldloca, System.Reflection.Emit.ILGenerator.MarkLabel(), System.Reflection.Emit.OpCodes.Newobj, and System.Reflection.Emit.OpCodes.Stloc.