Terraria: Internal.Runtime.InteropServices.ComActivationContext.Create
Create()
static unsafe ComActivationContext Internal.Runtime.InteropServices.ComActivationContext.Create (ref ComActivationContextInternal cxtInt) inline static
Definition at line 21 of file ComActivationContext.cs.
    {
        if (!Marshal.IsBuiltInComSupported)
        {
            throw new NotSupportedException(SR.NotSupported_COM);
        }
        ComActivationContext result = default(ComActivationContext);
        result.ClassId = cxtInt.ClassId;
        result.InterfaceId = cxtInt.InterfaceId;
        result.AssemblyPath = Marshal.PtrToStringUni(new IntPtr(cxtInt.AssemblyPathBuffer));
        result.AssemblyName = Marshal.PtrToStringUni(new IntPtr(cxtInt.AssemblyNameBuffer));
        result.TypeName = Marshal.PtrToStringUni(new IntPtr(cxtInt.TypeNameBuffer));
        return result;
    }
References Internal.Runtime.InteropServices.ComActivationContext.ClassId, System.Runtime.InteropServices.Marshal.IsBuiltInComSupported, System.SR.NotSupported_COM, and System.Runtime.InteropServices.Marshal.PtrToStringUni().
Referenced by Internal.Runtime.InteropServices.ComActivator.GetClassFactoryForTypeInternal(), Internal.Runtime.InteropServices.ComActivator.RegisterClassForTypeInternal(), and Internal.Runtime.InteropServices.ComActivator.UnregisterClassForTypeInternal().