Terraria: System.Enum.ValueToHexString
ValueToHexString() [1/2]
string System.Enum.ValueToHexString () inline private
Definition at line 89 of file Enum.cs.
    {
        ref byte rawData = ref this.GetRawData();
        Span<byte> destination = stackalloc byte[8];
        int length;
        switch (InternalGetCorElementType())
        {
        case CorElementType.ELEMENT_TYPE_I1:
        case CorElementType.ELEMENT_TYPE_U1:
            destination[0] = rawData;
            length = 1;
            break;
        case CorElementType.ELEMENT_TYPE_BOOLEAN:
            if (rawData == 0)
            {
                return "00";
            }
            return "01";
        case CorElementType.ELEMENT_TYPE_CHAR:
        case CorElementType.ELEMENT_TYPE_I2:
        case CorElementType.ELEMENT_TYPE_U2:
            BinaryPrimitives.WriteUInt16BigEndian(destination, Unsafe.As<byte, ushort>(ref rawData));
            length = 2;
            break;
        case CorElementType.ELEMENT_TYPE_I4:
        case CorElementType.ELEMENT_TYPE_U4:
            BinaryPrimitives.WriteUInt32BigEndian(destination, Unsafe.As<byte, uint>(ref rawData));
            length = 4;
            break;
        case CorElementType.ELEMENT_TYPE_I8:
        case CorElementType.ELEMENT_TYPE_U8:
            BinaryPrimitives.WriteUInt64BigEndian(destination, Unsafe.As<byte, ulong>(ref rawData));
            length = 8;
            break;
        default:
            throw new InvalidOperationException(SR.InvalidOperation_UnknownEnumType);
        }
        return HexConverter.ToString(destination.Slice(0, length));
    }
References System.destination, System.Enum.InternalGetCorElementType(), System.SR.InvalidOperation_UnknownEnumType, System.length, System.HexConverter.ToString(), System.Buffers.Binary.BinaryPrimitives.WriteUInt16BigEndian(), System.Buffers.Binary.BinaryPrimitives.WriteUInt32BigEndian(), and System.Buffers.Binary.BinaryPrimitives.WriteUInt64BigEndian().
Referenced by System.Enum.Format(), and System.Enum.ToString().