Terraria: System.Enum.ToUInt64
ToUInt64() [1/4]
ulong System.Enum.ToUInt64 () inline private
Definition at line 969 of file Enum.cs.
    {
        ref byte rawData = ref this.GetRawData();
        switch (InternalGetCorElementType())
        {
        case CorElementType.ELEMENT_TYPE_I1:
            return (ulong)Unsafe.As<byte, sbyte>(ref rawData);
        case CorElementType.ELEMENT_TYPE_U1:
            return rawData;
        case CorElementType.ELEMENT_TYPE_BOOLEAN:
            if (rawData == 0)
            {
                return 0uL;
            }
            return 1uL;
        case CorElementType.ELEMENT_TYPE_I2:
            return (ulong)Unsafe.As<byte, short>(ref rawData);
        case CorElementType.ELEMENT_TYPE_CHAR:
        case CorElementType.ELEMENT_TYPE_U2:
            return Unsafe.As<byte, ushort>(ref rawData);
        case CorElementType.ELEMENT_TYPE_I4:
            return (ulong)Unsafe.As<byte, int>(ref rawData);
        case CorElementType.ELEMENT_TYPE_U4:
        case CorElementType.ELEMENT_TYPE_R4:
            return Unsafe.As<byte, uint>(ref rawData);
        case CorElementType.ELEMENT_TYPE_I8:
            return (ulong)Unsafe.As<byte, long>(ref rawData);
        case CorElementType.ELEMENT_TYPE_U8:
        case CorElementType.ELEMENT_TYPE_R8:
            return Unsafe.As<byte, ulong>(ref rawData);
        case CorElementType.ELEMENT_TYPE_I:
            return (ulong)(long)Unsafe.As<byte, IntPtr>(ref rawData);
        case CorElementType.ELEMENT_TYPE_U:
            return (ulong)Unsafe.As<byte, UIntPtr>(ref rawData);
        default:
            throw new InvalidOperationException(SR.InvalidOperation_UnknownEnumType);
        }
    }
References System.Enum.InternalGetCorElementType(), and System.SR.InvalidOperation_UnknownEnumType.
Referenced by System.Enum.Format(), System.Enum.GetName< TEnum >(), System.Enum.IsDefined< TEnum >(), System.Enum.ToString(), and System.Enum.ToString().