Terraria: System.Enum.IsDefined
IsDefined()
static bool System.Enum.IsDefined (Type enumType, object value) inline static
Definition at line 359 of file Enum.cs.
    {
        if ((object)enumType == null)
        {
            throw new ArgumentNullException("enumType");
        }
        return enumType.IsEnumDefined(value);
    }
References System.Type.IsEnumDefined(), and System.value.
Referenced by System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedAttribute.DatabaseGeneratedAttribute(), System.Resources.NeutralResourcesLanguageAttribute.NeutralResourcesLanguageAttribute(), System.ComponentModel.EnumConverter.ConvertTo(), System.Diagnostics.Tracing.ManifestBuilder.CreateManifestString(), Terraria.MessageBuffer.GetData(), System.Environment.GetFolderPath(), System.ComponentModel.EnumConverter.IsValid(), System.ComponentModel.DataAnnotations.EnumDataTypeAttribute.IsValid(), and Terraria.Lighting.NextLightMode().