Terraria: System.Enum.TryParseByName
TryParseByName()
static bool System.Enum.TryParseByName (RuntimeType enumType, ReadOnlySpan< char > value, bool ignoreCase, bool throwOnFailure, out ulong result) inline static private
Definition at line 793 of file Enum.cs.
    {
        ReadOnlySpan<char> readOnlySpan = value;
        EnumInfo enumInfo = GetEnumInfo(enumType);
        string[] names = enumInfo.Names;
        ulong[] values = enumInfo.Values;
        bool flag = true;
        ulong num = 0uL;
        while (value.Length > 0)
        {
            int num2 = value.IndexOf(',');
            ReadOnlySpan<char> span;
            if (num2 == -1)
            {
                span = value.Trim();
                value = default(ReadOnlySpan<char>);
            }
            else
            {
                if (num2 == value.Length - 1)
                {
                    flag = false;
                    break;
                }
                span = value.Slice(0, num2).Trim();
                value = value.Slice(num2 + 1);
            }
            bool flag2 = false;
            if (ignoreCase)
            {
                for (int i = 0; i < names.Length; i++)
                {
                    if (span.EqualsOrdinalIgnoreCase(names[i]))
                    {
                        num |= values[i];
                        flag2 = true;
                        break;
                    }
                }
            }
            else
            {
                for (int j = 0; j < names.Length; j++)
                {
                    if (span.EqualsOrdinal(names[j]))
                    {
                        num |= values[j];
                        flag2 = true;
                        break;
                    }
                }
            }
            if (!flag2)
            {
                flag = false;
                break;
            }
        }
        if (flag)
        {
            result = num;
            return true;
        }
        if (throwOnFailure)
        {
            throw new ArgumentException(SR.Format(SR.Arg_EnumValueNotFound, readOnlySpan.ToString()));
        }
        result = 0uL;
        return false;
    }
References System.SR.Arg_EnumValueNotFound, System.SR.Format(), System.Enum.GetEnumInfo(), System.Enum.EnumInfo.Names, System.ReadOnlySpan< T >.Slice(), System.ReadOnlySpan< T >.ToString(), System.value, System.Enum.EnumInfo.Values, and System.values.
Referenced by System.Enum.TryParseInt32Enum(), System.Enum.TryParseInt64Enum(), System.Enum.TryParseRareEnum(), System.Enum.TryParseUInt32Enum(), and System.Enum.TryParseUInt64Enum().