Terraria: System.Net.FtpControlStream.CreateFtpListenerSocket
CreateFtpListenerSocket()
void System.Net.FtpControlStream.CreateFtpListenerSocket (FtpWebRequest request) inline private
Definition at line 816 of file FtpControlStream.cs.
    {
        IPEndPoint localEP = new IPEndPoint(((IPEndPoint)base.Socket.LocalEndPoint).Address, 0);
        try
        {
            _dataSocket = CreateFtpDataSocket(request, base.Socket);
        }
        catch (ObjectDisposedException)
        {
            throw ExceptionHelper.RequestAbortedException;
        }
        _dataSocket.Bind(localEP);
        _dataSocket.Listen(1);
    }
References System.Net.FtpControlStream._dataSocket, System.Net.Sockets.Socket.Bind(), System.Net.FtpControlStream.CreateFtpDataSocket(), System.Net.Sockets.Socket.Listen(), and System.Net.ExceptionHelper.RequestAbortedException.
Referenced by System.Net.FtpControlStream.BuildCommandsList().