Terraria: System.Enum.TryParse
TryParse() [6/6]
static bool System.Enum.TryParse (Type enumType, string? value, out object? result) inline static
Definition at line 416 of file Enum.cs.
    {
        return TryParse(enumType, value, ignoreCase: false, out result);
    }
References System.Enum.TryParse(), and System.value.
Referenced by Terraria.GameContent.ChromaHotkeyPainter.PaintKey.PaintKey(), Terraria.Graphics.Effects.FilterManager.Configuration_OnLoad(), Terraria.Main.LoadSettings(), System.Enum.Parse(), System.Enum.Parse(), System.Text.Json.Serialization.Converters.EnumConverter< T >.ReadAsPropertyNameCore(), System.Enum.TryParse(), System.Enum.TryParse(), System.Enum.TryParse(), System.Enum.TryParse(), and System.Enum.TryParse().