Terraria: System.Net.FtpControlStream.GetLastModifiedFrom213Response
GetLastModifiedFrom213Response()
DateTime System.Net.FtpControlStream.GetLastModifiedFrom213Response (string str) inline private
Definition at line 677 of file FtpControlStream.cs.
    {
        DateTime result = _lastModified;
        string[] array = str.Split(' ', '.');
        if (array.Length < 2)
        {
            return result;
        }
        string text = array[1];
        if (text.Length < 14)
        {
            return result;
        }
        int year = Convert.ToInt32(text.Substring(0, 4), NumberFormatInfo.InvariantInfo);
        int month = Convert.ToInt16(text.Substring(4, 2), NumberFormatInfo.InvariantInfo);
        int day = Convert.ToInt16(text.Substring(6, 2), NumberFormatInfo.InvariantInfo);
        int hour = Convert.ToInt16(text.Substring(8, 2), NumberFormatInfo.InvariantInfo);
        int minute = Convert.ToInt16(text.Substring(10, 2), NumberFormatInfo.InvariantInfo);
        int second = Convert.ToInt16(text.Substring(12, 2), NumberFormatInfo.InvariantInfo);
        int millisecond = 0;
        if (array.Length > 2)
        {
            millisecond = Convert.ToInt16(array[2], NumberFormatInfo.InvariantInfo);
        }
        try
        {
            result = new DateTime(year, month, day, hour, minute, second, millisecond);
            result = result.ToLocalTime();
        }
        catch (ArgumentOutOfRangeException)
        {
        }
        catch (ArgumentException)
        {
        }
        return result;
    }
References System.Net.FtpControlStream._lastModified, System.array, System.DateTime, System.Globalization.NumberFormatInfo.InvariantInfo, System.str, System.text, System.Convert.ToInt16(), System.Convert.ToInt32(), System.DateTime.ToLocalTime(), and System.year.
Referenced by System.Net.FtpControlStream.PipelineCallback().