Terraria: System.Enum.ToString
ToString() [3/4]
string System.Enum.ToString (string? format) inline
Definition at line 1089 of file Enum.cs.
    {
        if (string.IsNullOrEmpty(format))
        {
            return ToString();
        }
        if (format.Length == 1)
        {
            switch (format[0])
            {
            case 'G':
            case 'g':
                return ToString();
            case 'D':
            case 'd':
                return ValueToString();
            case 'X':
            case 'x':
                return ValueToHexString();
            case 'F':
            case 'f':
                return InternalFlagsFormat((RuntimeType)GetType(), ToUInt64()) ?? ValueToString();
            }
        }
        throw new FormatException(SR.Format_InvalidEnumFormatSpecification);
    }
References System.format, System.SR.Format_InvalidEnumFormatSpecification, System.Enum.InternalFlagsFormat(), System.Enum.ToString(), System.Enum.ToUInt64(), System.Enum.ValueToHexString(), and System.Enum.ValueToString().