Terraria: System.Enum.TryParse
TryParse() [1/6]
static bool System.Enum.TryParse (Type enumType, ReadOnlySpan< char > value, bool ignoreCase, bool throwOnFailure, out object result) inline static private
Definition at line 450 of file Enum.cs.
    {
        RuntimeType runtimeType = ValidateRuntimeType(enumType);
        value = value.TrimStart();
        if (value.Length == 0)
        {
            if (throwOnFailure)
            {
                throw new ArgumentException(SR.Arg_MustContainEnumInfo, "value");
            }
            result = null;
            return false;
        }
        int result3;
        uint result4;
        switch (Type.GetTypeCode(runtimeType))
        {
        case TypeCode.SByte:
        {
            bool flag = TryParseInt32Enum(runtimeType, value, -128, 127, ignoreCase, throwOnFailure, TypeCode.SByte, out result3);
            result = (flag ? InternalBoxEnum(runtimeType, result3) : null);
            return flag;
        }
        case TypeCode.Int16:
        {
            bool flag = TryParseInt32Enum(runtimeType, value, -32768, 32767, ignoreCase, throwOnFailure, TypeCode.Int16, out result3);
            result = (flag ? InternalBoxEnum(runtimeType, result3) : null);
            return flag;
        }
        case TypeCode.Int32:
        {
            bool flag = TryParseInt32Enum(runtimeType, value, int.MinValue, int.MaxValue, ignoreCase, throwOnFailure, TypeCode.Int32, out result3);
            result = (flag ? InternalBoxEnum(runtimeType, result3) : null);
            return flag;
        }
        case TypeCode.Byte:
        {
            bool flag = TryParseUInt32Enum(runtimeType, value, 255u, ignoreCase, throwOnFailure, TypeCode.Byte, out result4);
            result = (flag ? InternalBoxEnum(runtimeType, result4) : null);
            return flag;
        }
        case TypeCode.UInt16:
        {
            bool flag = TryParseUInt32Enum(runtimeType, value, 65535u, ignoreCase, throwOnFailure, TypeCode.UInt16, out result4);
            result = (flag ? InternalBoxEnum(runtimeType, result4) : null);
            return flag;
        }
        case TypeCode.UInt32:
        {
            bool flag = TryParseUInt32Enum(runtimeType, value, uint.MaxValue, ignoreCase, throwOnFailure, TypeCode.UInt32, out result4);
            result = (flag ? InternalBoxEnum(runtimeType, result4) : null);
            return flag;
        }
        case TypeCode.Int64:
        {
            long result5;
            bool flag = TryParseInt64Enum(runtimeType, value, ignoreCase, throwOnFailure, out result5);
            result = (flag ? InternalBoxEnum(runtimeType, result5) : null);
            return flag;
        }
        case TypeCode.UInt64:
        {
            ulong result2;
            bool flag = TryParseUInt64Enum(runtimeType, value, ignoreCase, throwOnFailure, out result2);
            result = (flag ? InternalBoxEnum(runtimeType, (long)result2) : null);
            return flag;
        }
        default:
            return TryParseRareEnum(runtimeType, value, ignoreCase, throwOnFailure, out result);
        }
    }
References System.SR.Arg_MustContainEnumInfo, System.Type.GetTypeCode(), System.Enum.InternalBoxEnum(), System.Reflection.MaxValue, System.Enum.TryParseInt32Enum(), System.Enum.TryParseInt64Enum(), System.Enum.TryParseRareEnum(), System.Enum.TryParseUInt32Enum(), System.Enum.TryParseUInt64Enum(), System.Enum.ValidateRuntimeType(), and System.value.