Terraria: System.Net.FtpControlStream.PipelineCallback
PipelineCallback()
override PipelineInstruction System.Net.FtpControlStream.PipelineCallback (PipelineEntry entry, ResponseDescription response, bool timeout, ref Stream stream) inline protected virtual
Reimplemented from System.Net.CommandStream.
Definition at line 241 of file FtpControlStream.cs.
    {
        if (System.Net.NetEventSource.Log.IsEnabled())
        {
            System.Net.NetEventSource.Info(this, $"Command:{entry?.Command} Description:{response?.StatusDescription}", "PipelineCallback");
        }
        if (response == null)
        {
            return PipelineInstruction.Abort;
        }
        FtpStatusCode status = (FtpStatusCode)response.Status;
        if (status != FtpStatusCode.ClosingControl)
        {
            StatusCode = status;
            StatusLine = response.StatusDescription;
        }
        if (response.InvalidStatusCode)
        {
            throw new WebException(System.SR.net_InvalidStatusCode, WebExceptionStatus.ProtocolError);
        }
        if (_index == -1)
        {
            switch (status)
            {
            case FtpStatusCode.SendUserCommand:
                _bannerMessage = new StringBuilder();
                _bannerMessage.Append(StatusLine);
                return PipelineInstruction.Advance;
            case FtpStatusCode.ServiceTemporarilyNotAvailable:
                return PipelineInstruction.Reread;
            default:
                throw GenerateException(status, response.StatusDescription, null);
            }
        }
        if (entry.Command == "OPTS utf8 on\r\n")
        {
            if (response.PositiveCompletion)
            {
                base.Encoding = Encoding.UTF8;
            }
            else
            {
                base.Encoding = Encoding.Default;
            }
            return PipelineInstruction.Advance;
        }
        if (entry.Command.IndexOf("USER", StringComparison.Ordinal) != -1 && status == FtpStatusCode.LoggedInProceed)
        {
            _loginState = FtpLoginState.LoggedIn;
            _index++;
        }
        if (response.TransientFailure || response.PermanentFailure)
        {
            if (status == FtpStatusCode.ServiceNotAvailable)
            {
                MarkAsRecoverableFailure();
            }
            throw GenerateException(status, response.StatusDescription, null);
        }
        if (_loginState != FtpLoginState.LoggedIn && entry.Command.IndexOf("PASS", StringComparison.Ordinal) != -1)
        {
            if (status != FtpStatusCode.NeedLoginAccount && status != FtpStatusCode.LoggedInProceed)
            {
                throw GenerateException(status, response.StatusDescription, null);
            }
            _loginState = FtpLoginState.LoggedIn;
        }
        if (entry.HasFlag(PipelineEntryFlags.CreateDataConnection) && (response.PositiveCompletion || response.PositiveIntermediate))
        {
            bool isSocketReady;
            PipelineInstruction result = QueueOrCreateDataConection(entry, response, timeout, ref stream, out isSocketReady);
            if (!isSocketReady)
            {
                return result;
            }
        }
        switch (status)
        {
        case FtpStatusCode.DataAlreadyOpen:
        case FtpStatusCode.OpeningData:
        {
            if (_dataSocket == null)
            {
                return PipelineInstruction.Abort;
            }
            if (!entry.HasFlag(PipelineEntryFlags.GiveDataStream))
            {
                _abortReason = System.SR.Format(System.SR.net_ftp_invalid_status_response, status, entry.Command);
                return PipelineInstruction.Abort;
            }
            TryUpdateContentLength(response.StatusDescription);
            FtpWebRequest ftpWebRequest = (FtpWebRequest)_request;
            if (ftpWebRequest.MethodInfo.ShouldParseForResponseUri)
            {
                TryUpdateResponseUri(response.StatusDescription, ftpWebRequest);
            }
            return QueueOrCreateFtpDataStream(ref stream);
        }
        case FtpStatusCode.LoggedInProceed:
            _welcomeMessage.Append(StatusLine);
            break;
        case FtpStatusCode.ClosingControl:
            _exitMessage.Append(response.StatusDescription);
            CloseSocket();
            break;
        case FtpStatusCode.ServerWantsSecureSession:
        {
            if (base.NetworkStream is TlsStream)
            {
                break;
            }
            FtpWebRequest ftpWebRequest2 = (FtpWebRequest)_request;
            TlsStream tlsStream = new TlsStream(base.NetworkStream, base.Socket, ftpWebRequest2.RequestUri.Host, ftpWebRequest2.ClientCertificates);
            if (_isAsync)
            {
                tlsStream.BeginAuthenticateAsClient(delegate(IAsyncResult ar)
                {
                    try
                    {
                        tlsStream.EndAuthenticateAsClient(ar);
                        base.NetworkStream = tlsStream;
                        ContinueCommandPipeline();
                    }
                    catch (Exception obj)
                    {
                        CloseSocket();
                        InvokeRequestCallback(obj);
                    }
                }, null);
                return PipelineInstruction.Pause;
            }
            tlsStream.AuthenticateAsClient();
            base.NetworkStream = tlsStream;
            break;
        }
        case FtpStatusCode.FileStatus:
            if (entry.Command.StartsWith("SIZE ", StringComparison.Ordinal))
            {
                _contentLength = GetContentLengthFrom213Response(response.StatusDescription);
            }
            else if (entry.Command.StartsWith("MDTM ", StringComparison.Ordinal))
            {
                _lastModified = GetLastModifiedFrom213Response(response.StatusDescription);
            }
            break;
        case FtpStatusCode.PathnameCreated:
            if (entry.Command == "PWD\r\n" && !entry.HasFlag(PipelineEntryFlags.UserCommand))
            {
                _loginDirectory = GetLoginDirectory(response.StatusDescription);
            }
            break;
        default:
            if (entry.Command.IndexOf("CWD", StringComparison.Ordinal) != -1)
            {
                _establishedServerDirectory = _requestedServerDirectory;
            }
            break;
        }
        if (response.PositiveIntermediate || (!base.UsingSecureStream && entry.Command == "AUTH TLS\r\n"))
        {
            return PipelineInstruction.Reread;
        }
        return PipelineInstruction.Advance;
    }
References System.Net.CommandStream._abortReason, System.Net.FtpControlStream._bannerMessage, System.Net.FtpControlStream._contentLength, System.Net.FtpControlStream._dataSocket, System.Net.FtpControlStream._establishedServerDirectory, System.Net.FtpControlStream._exitMessage, System.Net.CommandStream._index, System.Net.CommandStream._isAsync, System.Net.FtpControlStream._lastModified, System.Net.FtpControlStream._loginDirectory, System.Net.FtpControlStream._loginState, System.Net.CommandStream._request, System.Net.FtpControlStream._requestedServerDirectory, System.Net.FtpControlStream._welcomeMessage, System.Text.StringBuilder.Append(), System.Net.NetworkStreamWrapper.CloseSocket(), System.Net.CommandStream.ContinueCommandPipeline(), System.Text.Encoding.Default, System.SR.Format(), System.Net.CommandStream.GenerateException(), System.Net.FtpControlStream.GetContentLengthFrom213Response(), System.Net.FtpControlStream.GetLastModifiedFrom213Response(), System.Net.FtpControlStream.GetLoginDirectory(), System.Net.NetEventSource.Info(), System.Net.CommandStream.InvokeRequestCallback(), System.Net.NetEventSource.Log, System.Net.CommandStream.MarkAsRecoverableFailure(), System.SR.net_ftp_invalid_status_response, System.SR.net_InvalidStatusCode, System.obj, System.Net.FtpControlStream.QueueOrCreateDataConection(), System.Net.FtpControlStream.QueueOrCreateFtpDataStream(), System.Net.FtpControlStream.StatusCode, System.Net.FtpControlStream.StatusLine, System.stream, System.timeout, System.Net.FtpControlStream.TryUpdateContentLength(), System.Net.FtpControlStream.TryUpdateResponseUri(), and System.Text.Encoding.UTF8.