Terraria: System.Net.FtpControlStream.BuildCommandsList
BuildCommandsList()
override PipelineEntry[] System.Net.FtpControlStream.BuildCommandsList (WebRequest req) inline protected virtual
Reimplemented from System.Net.CommandStream.
Definition at line 406 of file FtpControlStream.cs.
    {
        bool flag = false;
        FtpWebRequest ftpWebRequest = (FtpWebRequest)req;
        if (System.Net.NetEventSource.Log.IsEnabled())
        {
            System.Net.NetEventSource.Info(this, null, "BuildCommandsList");
        }
        _responseUri = ftpWebRequest.RequestUri;
        List<PipelineEntry> list = new List<PipelineEntry>();
        if (ftpWebRequest.EnableSsl && !base.UsingSecureStream)
        {
            list.Add(new PipelineEntry(FormatFtpCommand("AUTH", "TLS")));
            flag = true;
        }
        if (flag)
        {
            _loginDirectory = null;
            _establishedServerDirectory = null;
            _requestedServerDirectory = null;
            _currentTypeSetting = string.Empty;
            if (_loginState == FtpLoginState.LoggedIn)
            {
                _loginState = FtpLoginState.LoggedInButNeedsRelogin;
            }
        }
        if (_loginState != FtpLoginState.LoggedIn)
        {
            Credentials = ftpWebRequest.Credentials.GetCredential(ftpWebRequest.RequestUri, "basic");
            _welcomeMessage = new StringBuilder();
            _exitMessage = new StringBuilder();
            string text = string.Empty;
            string text2 = string.Empty;
            if (Credentials != null)
            {
                text = Credentials.UserName;
                string domain = Credentials.Domain;
                if (!string.IsNullOrEmpty(domain))
                {
                    text = domain + "\\" + text;
                }
                text2 = Credentials.Password;
            }
            if (text.Length == 0 && text2.Length == 0)
            {
                text = "anonymous";
                text2 = "anonymous@";
            }
            list.Add(new PipelineEntry(FormatFtpCommand("USER", text)));
            list.Add(new PipelineEntry(FormatFtpCommand("PASS", text2), PipelineEntryFlags.DontLogParameter));
            if (ftpWebRequest.EnableSsl && !base.UsingSecureStream)
            {
                list.Add(new PipelineEntry(FormatFtpCommand("PBSZ", "0")));
                list.Add(new PipelineEntry(FormatFtpCommand("PROT", "P")));
            }
            list.Add(new PipelineEntry(FormatFtpCommand("OPTS", "utf8 on")));
            list.Add(new PipelineEntry(FormatFtpCommand("PWD", null)));
        }
        GetPathOption pathOption = GetPathOption.Normal;
        if (ftpWebRequest.MethodInfo.HasFlag(FtpMethodFlags.DoesNotTakeParameter))
        {
            pathOption = GetPathOption.AssumeNoFilename;
        }
        else if (ftpWebRequest.MethodInfo.HasFlag(FtpMethodFlags.ParameterIsDirectory))
        {
            pathOption = GetPathOption.AssumeFilename;
        }
        GetPathInfo(pathOption, ftpWebRequest.RequestUri, out var path, out var directory, out var filename);
        if (filename.Length == 0 && ftpWebRequest.MethodInfo.HasFlag(FtpMethodFlags.TakesParameter))
        {
            throw new WebException(System.SR.net_ftp_invalid_uri);
        }
        if (_establishedServerDirectory != null && _loginDirectory != null && _establishedServerDirectory != _loginDirectory)
        {
            list.Add(new PipelineEntry(FormatFtpCommand("CWD", _loginDirectory), PipelineEntryFlags.UserCommand));
            _requestedServerDirectory = _loginDirectory;
        }
        if (ftpWebRequest.MethodInfo.HasFlag(FtpMethodFlags.MustChangeWorkingDirectoryToPath) && directory.Length > 0)
        {
            list.Add(new PipelineEntry(FormatFtpCommand("CWD", directory), PipelineEntryFlags.UserCommand));
            _requestedServerDirectory = directory;
        }
        if (!ftpWebRequest.MethodInfo.IsCommandOnly)
        {
            string text3 = (ftpWebRequest.UseBinary ? "I" : "A");
            if (_currentTypeSetting != text3)
            {
                list.Add(new PipelineEntry(FormatFtpCommand("TYPE", text3)));
                _currentTypeSetting = text3;
            }
            if (ftpWebRequest.UsePassive)
            {
                string command = ((base.ServerAddress.AddressFamily == AddressFamily.InterNetwork || base.ServerAddress.IsIPv4MappedToIPv6) ? "PASV" : "EPSV");
                list.Add(new PipelineEntry(FormatFtpCommand(command, null), PipelineEntryFlags.CreateDataConnection));
            }
            else
            {
                string command2 = ((base.ServerAddress.AddressFamily == AddressFamily.InterNetwork || base.ServerAddress.IsIPv4MappedToIPv6) ? "PORT" : "EPRT");
                CreateFtpListenerSocket(ftpWebRequest);
                list.Add(new PipelineEntry(FormatFtpCommand(command2, GetPortCommandLine(ftpWebRequest))));
            }
            if (ftpWebRequest.ContentOffset > 0)
            {
                list.Add(new PipelineEntry(FormatFtpCommand("REST", ftpWebRequest.ContentOffset.ToString(CultureInfo.InvariantCulture))));
            }
        }
        PipelineEntryFlags pipelineEntryFlags = PipelineEntryFlags.UserCommand;
        if (!ftpWebRequest.MethodInfo.IsCommandOnly)
        {
            pipelineEntryFlags |= PipelineEntryFlags.GiveDataStream;
            if (!ftpWebRequest.UsePassive)
            {
                pipelineEntryFlags |= PipelineEntryFlags.CreateDataConnection;
            }
        }
        if (ftpWebRequest.MethodInfo.Operation == FtpOperation.Rename)
        {
            string text4 = ((directory.Length == 0) ? string.Empty : (directory + "/"));
            list.Add(new PipelineEntry(FormatFtpCommand("RNFR", text4 + filename), pipelineEntryFlags));
            string parameter = ((string.IsNullOrEmpty(ftpWebRequest.RenameTo) || !ftpWebRequest.RenameTo.StartsWith("/", StringComparison.OrdinalIgnoreCase)) ? (text4 + ftpWebRequest.RenameTo) : ftpWebRequest.RenameTo);
            list.Add(new PipelineEntry(FormatFtpCommand("RNTO", parameter), pipelineEntryFlags));
        }
        else if (ftpWebRequest.MethodInfo.HasFlag(FtpMethodFlags.DoesNotTakeParameter))
        {
            list.Add(new PipelineEntry(FormatFtpCommand(ftpWebRequest.Method, string.Empty), pipelineEntryFlags));
        }
        else if (ftpWebRequest.MethodInfo.HasFlag(FtpMethodFlags.MustChangeWorkingDirectoryToPath))
        {
            list.Add(new PipelineEntry(FormatFtpCommand(ftpWebRequest.Method, filename), pipelineEntryFlags));
        }
        else
        {
            list.Add(new PipelineEntry(FormatFtpCommand(ftpWebRequest.Method, path), pipelineEntryFlags));
        }
        list.Add(new PipelineEntry(FormatFtpCommand("QUIT", null)));
        return list.ToArray();
    }
References System.Net.FtpControlStream._currentTypeSetting, System.Net.FtpControlStream._establishedServerDirectory, System.Net.FtpControlStream._exitMessage, System.Net.FtpControlStream._loginDirectory, System.Net.FtpControlStream._loginState, System.Net.FtpControlStream._requestedServerDirectory, System.Net.FtpControlStream._responseUri, System.Net.FtpControlStream._welcomeMessage, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Net.FtpControlStream.CreateFtpListenerSocket(), System.Net.FtpControlStream.Credentials, System.Net.NetworkCredential.Domain, System.Net.FtpControlStream.FormatFtpCommand(), System.Net.FtpControlStream.GetPathInfo(), System.Net.FtpControlStream.GetPortCommandLine(), System.Net.NetEventSource.Info(), System.Globalization.CultureInfo.InvariantCulture, System.list, System.Net.NetEventSource.Log, System.SR.net_ftp_invalid_uri, System.Net.NetworkCredential.Password, System.text, and System.Net.NetworkCredential.UserName.