Terraria: System.Net.FtpControlStream.TryUpdateResponseUri
TryUpdateResponseUri()
void System.Net.FtpControlStream.TryUpdateResponseUri (string str, FtpWebRequest request) inline private
Definition at line 715 of file FtpControlStream.cs.
    {
        Uri uri = request.RequestUri;
        int num = str.IndexOf("for ", StringComparison.Ordinal);
        if (num == -1)
        {
            return;
        }
        num += 4;
        int num2 = str.LastIndexOf('(');
        if (num2 == -1)
        {
            num2 = str.Length;
        }
        if (num2 > num)
        {
            string text = str.Substring(num, num2 - num);
            text = text.TrimEnd(' ', '.', '\r', '\n');
            string text2 = text.Replace("%", "%25");
            text2 = text2.Replace("#", "%23");
            string absolutePath = uri.AbsolutePath;
            if (absolutePath.Length > 0 && absolutePath[absolutePath.Length - 1] != '/')
            {
                UriBuilder uriBuilder = new UriBuilder(uri);
                uriBuilder.Path = absolutePath + "/";
                uri = uriBuilder.Uri;
            }
            if (!Uri.TryCreate(uri, text2, out Uri result))
            {
                throw new FormatException(System.SR.Format(System.SR.net_ftp_invalid_response_filename, text));
            }
            if (!uri.IsBaseOf(result) || uri.Segments.Length != result.Segments.Length - 1)
            {
                throw new FormatException(System.SR.Format(System.SR.net_ftp_invalid_response_filename, text));
            }
            _responseUri = result;
        }
    }
References System.Net.FtpControlStream._responseUri, System.Uri.AbsolutePath, System.SR.Format(), System.Uri.IsBaseOf(), System.SR.net_ftp_invalid_response_filename, System.Uri.Segments, System.str, System.text, and System.Uri.TryCreate().
Referenced by System.Net.FtpControlStream.PipelineCallback().