Terraria: System.Enum.GetValue
GetValue()
object System.Enum.GetValue () inline package
Definition at line 946 of file Enum.cs.
    {
        ref byte rawData = ref this.GetRawData();
        return InternalGetCorElementType() switch
        {
            CorElementType.ELEMENT_TYPE_I1 => Unsafe.As<byte, sbyte>(ref rawData),
            CorElementType.ELEMENT_TYPE_U1 => rawData,
            CorElementType.ELEMENT_TYPE_BOOLEAN => Unsafe.As<byte, bool>(ref rawData),
            CorElementType.ELEMENT_TYPE_I2 => Unsafe.As<byte, short>(ref rawData),
            CorElementType.ELEMENT_TYPE_U2 => Unsafe.As<byte, ushort>(ref rawData),
            CorElementType.ELEMENT_TYPE_CHAR => Unsafe.As<byte, char>(ref rawData),
            CorElementType.ELEMENT_TYPE_I4 => Unsafe.As<byte, int>(ref rawData),
            CorElementType.ELEMENT_TYPE_U4 => Unsafe.As<byte, uint>(ref rawData),
            CorElementType.ELEMENT_TYPE_R4 => Unsafe.As<byte, float>(ref rawData),
            CorElementType.ELEMENT_TYPE_I8 => Unsafe.As<byte, long>(ref rawData),
            CorElementType.ELEMENT_TYPE_U8 => Unsafe.As<byte, ulong>(ref rawData),
            CorElementType.ELEMENT_TYPE_R8 => Unsafe.As<byte, double>(ref rawData),
            CorElementType.ELEMENT_TYPE_I => Unsafe.As<byte, IntPtr>(ref rawData),
            CorElementType.ELEMENT_TYPE_U => Unsafe.As<byte, UIntPtr>(ref rawData),
            _ => throw new InvalidOperationException(SR.InvalidOperation_UnknownEnumType),
        };
    }
References System.Enum.InternalGetCorElementType(), and System.SR.InvalidOperation_UnknownEnumType.
Referenced by System.Enum.ToBoolean(), System.Enum.ToByte(), System.Enum.ToChar(), System.Enum.ToDecimal(), System.Enum.ToDouble(), System.Enum.ToInt16(), System.Enum.ToInt32(), System.Enum.ToInt64(), System.Enum.ToSByte(), System.Enum.ToSingle(), System.Enum.ToUInt16(), System.Enum.ToUInt32(), and System.Enum.ToUInt64().