Terraria: System.Enum.TryParseInt32Enum
TryParseInt32Enum()
static bool System.Enum.TryParseInt32Enum (RuntimeType enumType, ReadOnlySpan< char > value, int minInclusive, int maxInclusive, bool ignoreCase, bool throwOnFailure, TypeCode type, out int result) inline static private
Definition at line 641 of file Enum.cs.
    {
        Number.ParsingStatus parsingStatus = Number.ParsingStatus.OK;
        if (StartsNumber(value[0]))
        {
            parsingStatus = Number.TryParseInt32IntegerStyle(value, NumberStyles.AllowTrailingWhite | NumberStyles.AllowLeadingSign, CultureInfo.InvariantCulture.NumberFormat, out result);
            if (parsingStatus == Number.ParsingStatus.OK)
            {
                if ((uint)(result - minInclusive) <= (uint)(maxInclusive - minInclusive))
                {
                    return true;
                }
                parsingStatus = Number.ParsingStatus.Overflow;
            }
        }
        ulong result2;
        if (parsingStatus == Number.ParsingStatus.Overflow)
        {
            if (throwOnFailure)
            {
                Number.ThrowOverflowException(type);
            }
        }
        else if (TryParseByName(enumType, value, ignoreCase, throwOnFailure, out result2))
        {
            result = (int)result2;
            return true;
        }
        result = 0;
        return false;
    }
References System.Globalization.CultureInfo.InvariantCulture, System.Enum.StartsNumber(), System.Number.ThrowOverflowException(), System.Enum.TryParseByName(), System.Number.TryParseInt32IntegerStyle(), System.type, and System.value.
Referenced by System.Enum.TryParse(), and System.Enum.TryParse< TEnum >().