Terraria: System.Enum.CompareTo
CompareTo() [1/2]
int System.Enum.CompareTo (object? target) inline
Implements System.IComparable< in T >.
Definition at line 1036 of file Enum.cs.
    {
        if (target == this)
        {
            return 0;
        }
        if (target == null)
        {
            return 1;
        }
        if (GetType() != target.GetType())
        {
            throw new ArgumentException(SR.Format(SR.Arg_EnumAndObjectMustBeSameType, target.GetType(), GetType()));
        }
        ref byte rawData = ref this.GetRawData();
        ref byte rawData2 = ref target.GetRawData();
        switch (InternalGetCorElementType())
        {
        case CorElementType.ELEMENT_TYPE_I1:
            return Unsafe.As<byte, sbyte>(ref rawData).CompareTo(Unsafe.As<byte, sbyte>(ref rawData2));
        case CorElementType.ELEMENT_TYPE_BOOLEAN:
        case CorElementType.ELEMENT_TYPE_U1:
            return rawData.CompareTo(rawData2);
        case CorElementType.ELEMENT_TYPE_I2:
            return Unsafe.As<byte, short>(ref rawData).CompareTo(Unsafe.As<byte, short>(ref rawData2));
        case CorElementType.ELEMENT_TYPE_CHAR:
        case CorElementType.ELEMENT_TYPE_U2:
            return Unsafe.As<byte, ushort>(ref rawData).CompareTo(Unsafe.As<byte, ushort>(ref rawData2));
        case CorElementType.ELEMENT_TYPE_I4:
            return Unsafe.As<byte, int>(ref rawData).CompareTo(Unsafe.As<byte, int>(ref rawData2));
        case CorElementType.ELEMENT_TYPE_U4:
            return Unsafe.As<byte, uint>(ref rawData).CompareTo(Unsafe.As<byte, uint>(ref rawData2));
        case CorElementType.ELEMENT_TYPE_I8:
        case CorElementType.ELEMENT_TYPE_I:
            return Unsafe.As<byte, long>(ref rawData).CompareTo(Unsafe.As<byte, long>(ref rawData2));
        case CorElementType.ELEMENT_TYPE_U8:
        case CorElementType.ELEMENT_TYPE_U:
            return Unsafe.As<byte, ulong>(ref rawData).CompareTo(Unsafe.As<byte, ulong>(ref rawData2));
        case CorElementType.ELEMENT_TYPE_R4:
            return Unsafe.As<byte, float>(ref rawData).CompareTo(Unsafe.As<byte, float>(ref rawData2));
        case CorElementType.ELEMENT_TYPE_R8:
            return Unsafe.As<byte, double>(ref rawData).CompareTo(Unsafe.As<byte, double>(ref rawData2));
        default:
            throw new InvalidOperationException(SR.InvalidOperation_UnknownEnumType);
        }
    }
References System.SR.Arg_EnumAndObjectMustBeSameType, System.Enum.CompareTo(), System.SR.Format(), System.Enum.InternalGetCorElementType(), and System.SR.InvalidOperation_UnknownEnumType.
Referenced by System.Enum.CompareTo(), and System.Runtime.CompilerServices.RuntimeHelpers.EnumCompareTo< T >().