Terraria: System.Enum.InternalBoxEnum
InternalBoxEnum()
static object System.Enum.InternalBoxEnum (RuntimeType enumType, long value) private
Referenced by System.Enum.ToObject(), System.Enum.ToObject(), System.Enum.ToObject(), System.Enum.ToObject(), System.Enum.ToObject(), System.Enum.ToObject(), System.Enum.ToObject(), System.Enum.ToObject(), System.Enum.ToObject(), System.Enum.ToObject(), and System.Enum.TryParse().