Terraria: System.Enum.GetName
GetName()
static ? string System.Enum.GetName (Type enumType, object value) inline static
Definition at line 281 of file Enum.cs.
    {
        if ((object)enumType == null)
        {
            throw new ArgumentNullException("enumType");
        }
        return enumType.GetEnumName(value);
    }
References System.Type.GetEnumName(), and System.value.
Referenced by Terraria.Graphics.Effects.FilterManager.Configuration_OnSave(), ReLogic.Utilities.AttributeUtilities.GetAttribute< T >(), Terraria.IO.FileMetadata.Read(), Terraria.Main.SaveSettings(), and System.ComponentModel.ToolboxItemFilterAttribute.ToString().