Terraria: System.Net.FtpControlStream.QueueOrCreateDataConection
QueueOrCreateDataConection()
PipelineInstruction System.Net.FtpControlStream.QueueOrCreateDataConection (PipelineEntry entry, ResponseDescription response, bool timeout, ref Stream stream, out bool isSocketReady) inline private
Definition at line 544 of file FtpControlStream.cs.
    {
        isSocketReady = false;
        if (_dataHandshakeStarted)
        {
            isSocketReady = true;
            return PipelineInstruction.Pause;
        }
        _dataHandshakeStarted = true;
        bool flag = false;
        int port = -1;
        if (entry.Command == "PASV\r\n" || entry.Command == "EPSV\r\n")
        {
            if (!response.PositiveCompletion)
            {
                _abortReason = System.SR.Format(System.SR.net_ftp_server_failed_passive, response.Status);
                return PipelineInstruction.Abort;
            }
            port = ((!(entry.Command == "PASV\r\n")) ? GetPortV6(response.StatusDescription) : GetPortV4(response.StatusDescription));
            flag = true;
        }
        if (flag)
        {
            try
            {
                _dataSocket = CreateFtpDataSocket((FtpWebRequest)_request, base.Socket);
            }
            catch (ObjectDisposedException)
            {
                throw ExceptionHelper.RequestAbortedException;
            }
            IPEndPoint localEP = new IPEndPoint(((IPEndPoint)base.Socket.LocalEndPoint).Address, 0);
            _dataSocket.Bind(localEP);
            _passiveEndPoint = new IPEndPoint(base.ServerAddress, port);
        }
        if (_passiveEndPoint != null)
        {
            IPEndPoint passiveEndPoint = _passiveEndPoint;
            _passiveEndPoint = null;
            if (System.Net.NetEventSource.Log.IsEnabled())
            {
                System.Net.NetEventSource.Info(this, "starting Connect()", "QueueOrCreateDataConection");
            }
            if (_isAsync)
            {
                _dataSocket.BeginConnect(passiveEndPoint, s_connectCallbackDelegate, this);
                return PipelineInstruction.Pause;
            }
            _dataSocket.Connect(passiveEndPoint);
            return PipelineInstruction.Advance;
        }
        if (System.Net.NetEventSource.Log.IsEnabled())
        {
            System.Net.NetEventSource.Info(this, "starting Accept()", "QueueOrCreateDataConection");
        }
        if (_isAsync)
        {
            _dataSocket.BeginAccept(s_acceptCallbackDelegate, this);
            return PipelineInstruction.Pause;
        }
        Socket dataSocket = _dataSocket;
        try
        {
            _dataSocket = _dataSocket.Accept();
            if (!base.ServerAddress.Equals(((IPEndPoint)_dataSocket.RemoteEndPoint).Address))
            {
                _dataSocket.Close();
                throw new WebException(System.SR.net_ftp_active_address_different, WebExceptionStatus.ProtocolError);
            }
            isSocketReady = true;
            return PipelineInstruction.Pause;
        }
        finally
        {
            dataSocket.Close();
        }
    }
References System.Net.CommandStream._abortReason, System.Net.FtpControlStream._dataHandshakeStarted, System.Net.FtpControlStream._dataSocket, System.Net.CommandStream._isAsync, System.Net.FtpControlStream._passiveEndPoint, System.Net.CommandStream._request, System.Net.Sockets.Socket.Accept(), System.Net.Sockets.Socket.BeginAccept(), System.Net.Sockets.Socket.BeginConnect(), System.Net.Sockets.Socket.Bind(), System.Net.Sockets.Socket.Close(), System.Net.Sockets.Socket.Connect(), System.Net.FtpControlStream.CreateFtpDataSocket(), System.SR.Format(), System.Net.FtpControlStream.GetPortV4(), System.Net.FtpControlStream.GetPortV6(), System.Net.NetEventSource.Info(), System.Net.NetEventSource.Log, System.SR.net_ftp_active_address_different, System.SR.net_ftp_server_failed_passive, System.Net.Sockets.Socket.RemoteEndPoint, System.Net.ExceptionHelper.RequestAbortedException, System.Net.FtpControlStream.s_acceptCallbackDelegate, and System.Net.FtpControlStream.s_connectCallbackDelegate.
Referenced by System.Net.FtpControlStream.PipelineCallback().