Terraria: System.Enum.TryParseInt64Enum
TryParseInt64Enum()
static bool System.Enum.TryParseInt64Enum (RuntimeType enumType, ReadOnlySpan< char > value, bool ignoreCase, bool throwOnFailure, out long result) inline static private
Definition at line 705 of file Enum.cs.
    {
        Number.ParsingStatus parsingStatus = Number.ParsingStatus.OK;
        if (StartsNumber(value[0]))
        {
            parsingStatus = Number.TryParseInt64IntegerStyle(value, NumberStyles.AllowTrailingWhite | NumberStyles.AllowLeadingSign, CultureInfo.InvariantCulture.NumberFormat, out result);
            if (parsingStatus == Number.ParsingStatus.OK)
            {
                return true;
            }
        }
        ulong result2;
        if (parsingStatus == Number.ParsingStatus.Overflow)
        {
            if (throwOnFailure)
            {
                Number.ThrowOverflowException(TypeCode.Int64);
            }
        }
        else if (TryParseByName(enumType, value, ignoreCase, throwOnFailure, out result2))
        {
            result = (long)result2;
            return true;
        }
        result = 0L;
        return false;
    }
References System.Globalization.CultureInfo.InvariantCulture, System.L, System.Enum.StartsNumber(), System.Number.ThrowOverflowException(), System.Enum.TryParseByName(), System.Number.TryParseInt64IntegerStyle(), and System.value.
Referenced by System.Enum.TryParse(), and System.Enum.TryParse< TEnum >().