Terraria: System.Enum.ToObject
ToObject() [6/11]
static object System.Enum.ToObject (Type enumType, object value) inline static
Definition at line 874 of file Enum.cs.
    {
        if (value == null)
        {
            throw new ArgumentNullException("value");
        }
        return Convert.GetTypeCode(value) switch
        {
            TypeCode.Int32 => ToObject(enumType, (int)value),
            TypeCode.SByte => ToObject(enumType, (sbyte)value),
            TypeCode.Int16 => ToObject(enumType, (short)value),
            TypeCode.Int64 => ToObject(enumType, (long)value),
            TypeCode.UInt32 => ToObject(enumType, (uint)value),
            TypeCode.Byte => ToObject(enumType, (byte)value),
            TypeCode.UInt16 => ToObject(enumType, (ushort)value),
            TypeCode.UInt64 => ToObject(enumType, (ulong)value),
            TypeCode.Char => ToObject(enumType, (char)value),
            TypeCode.Boolean => ToObject(enumType, (bool)value),
            _ => throw new ArgumentException(SR.Arg_MustBeEnumBaseTypeOrEnum, "value"),
        };
    }
References System.SR.Arg_MustBeEnumBaseTypeOrEnum, System.Convert.GetTypeCode(), System.Enum.ToObject(), and System.value.
Referenced by System.ComponentModel.ReflectPropertyDescriptor.ReflectPropertyDescriptor(), System.ComponentModel.EnumConverter.ConvertFrom(), System.ComponentModel.EnumConverter.ConvertTo(), System.Xml.Serialization.XmlSerializationWriterILGen.FindChoiceEnumValue(), System.RuntimeType.GetEnumValues(), System.Linq.Expressions.Interpreter.ScriptingRuntimeHelpers.GetPrimitiveDefaultValue(), System.Runtime.InteropServices.ComEventsMethod.DelegateWrapper.Invoke(), System.ComponentModel.DataAnnotations.EnumDataTypeAttribute.IsValid(), System.Formats.Asn1.AsnDecoder.ReadEnumeratedValue(), System.Formats.Asn1.AsnDecoder.ReadEnumeratedValue< TEnum >(), System.Runtime.Serialization.EnumDataContract.ReadEnumValue(), System.Runtime.Serialization.Json.JsonEnumDataContract.ReadJsonValueCore(), System.Formats.Asn1.AsnDecoder.ReadNamedBitListValue(), System.Formats.Asn1.AsnDecoder.ReadNamedBitListValue< TFlagsEnum >(), System.Linq.Expressions.Interpreter.CastReferenceToEnumInstruction.Run(), System.Linq.Expressions.Interpreter.CastToEnumInstruction.Run(), System.Enum.ToObject(), System.Enum.TryParseRareEnum(), System.Xml.Serialization.XmlSerializationReaderILGen.WriteEnumMethod(), System.Xml.Serialization.XmlSerializationWriterILGen.WriteEnumMethod(), System.Xml.Serialization.ReflectionXmlSerializationReader.WriteEnumMethod(), and System.Xml.Serialization.XmlSerializationReaderILGen.WriteHashtable().