Terraria: System.Net.FtpControlStream.GetContentLengthFrom213Response
GetContentLengthFrom213Response()
long System.Net.FtpControlStream.GetContentLengthFrom213Response (string responseString) inline private
Definition at line 667 of file FtpControlStream.cs.
    {
        string[] array = responseString.Split(' ');
        if (array.Length < 2)
        {
            throw new FormatException(System.SR.Format(System.SR.net_ftp_response_invalid_format, responseString));
        }
        return Convert.ToInt64(array[1], NumberFormatInfo.InvariantInfo);
    }
References System.array, System.SR.Format(), System.Globalization.NumberFormatInfo.InvariantInfo, System.SR.net_ftp_response_invalid_format, and System.Convert.ToInt64().
Referenced by System.Net.FtpControlStream.PipelineCallback().