Terraria: System.Enum.ValidateRuntimeType
ValidateRuntimeType()
static RuntimeType System.Enum.ValidateRuntimeType (Type enumType) inline static private
Definition at line 1269 of file Enum.cs.
    {
        if (enumType == null)
        {
            throw new ArgumentNullException("enumType");
        }
        if (!enumType.IsEnum)
        {
            throw new ArgumentException(SR.Arg_MustBeEnum, "enumType");
        }
        if (!(enumType is RuntimeType result))
        {
            throw new ArgumentException(SR.Arg_MustBeType, "enumType");
        }
        return result;
    }
References System.SR.Arg_MustBeEnum, System.SR.Arg_MustBeType, and System.Type.IsEnum.
Referenced by System.Enum.Format(), System.Enum.ToObject(), System.Enum.ToObject(), System.Enum.ToObject(), System.Enum.ToObject(), System.Enum.ToObject(), System.Enum.ToObject(), System.Enum.ToObject(), System.Enum.ToObject(), System.Enum.ToObject(), System.Enum.ToObject(), and System.Enum.TryParse().