Terraria: System.Net.FtpControlStream.GetPortCommandLine
GetPortCommandLine()
string System.Net.FtpControlStream.GetPortCommandLine (FtpWebRequest request) inline private
Definition at line 831 of file FtpControlStream.cs.
    {
        try
        {
            IPEndPoint iPEndPoint = (IPEndPoint)_dataSocket.LocalEndPoint;
            if (base.ServerAddress.AddressFamily == AddressFamily.InterNetwork || base.ServerAddress.IsIPv4MappedToIPv6)
            {
                return FormatAddress(iPEndPoint.Address, iPEndPoint.Port);
            }
            if (base.ServerAddress.AddressFamily == AddressFamily.InterNetworkV6)
            {
                return FormatAddressV6(iPEndPoint.Address, iPEndPoint.Port);
            }
            throw new System.Net.InternalException();
        }
        catch (Exception innerException)
        {
            throw GenerateException(System.SR.net_ftp_protocolerror, WebExceptionStatus.ProtocolError, innerException);
        }
    }
References System.Net.FtpControlStream._dataSocket, System.Net.FtpControlStream.FormatAddress(), System.Net.FtpControlStream.FormatAddressV6(), System.Net.CommandStream.GenerateException(), System.Net.Sockets.Socket.LocalEndPoint, and System.SR.net_ftp_protocolerror.
Referenced by System.Net.FtpControlStream.BuildCommandsList().