Terraria: System.Enum.Parse
Parse() [3/4]
static object System.Enum.Parse (Type enumType, string value) inline static
Definition at line 368 of file Enum.cs.
    {
        return Parse(enumType, value, ignoreCase: false);
    }
References System.Enum.Parse(), and System.value.
Referenced by System.ComponentModel.DefaultValueAttribute.DefaultValueAttribute(), System.OleAutBinder.ChangeType(), System.ComponentModel.EnumConverter.ConvertFrom(), System.Resources.ResourceWriter.FindTypeCode(), System.Diagnostics.Tracing.EventSource.GetCustomAttributeHelper(), System.ComponentModel.EnumConverter.GetStandardValues(), System.Xml.Serialization.ReflectionAwareILGen.ILGenForEnumMember(), Extensions.EnumerationExtensions.Include< T >(), System.ComponentModel.DataAnnotations.EnumDataTypeAttribute.IsValid(), System.Diagnostics.SourceSwitch.OnValueChanged(), System.Diagnostics.TraceSwitch.OnValueChanged(), System.Enum.Parse(), System.Enum.Parse(), System.Runtime.Serialization.Json.ReflectionJsonReader.ReadSimpleDictionary(), Extensions.EnumerationExtensions.Remove< T >(), System.Xml.Serialization.ReflectionXmlSerializationReader.WriteEnumMethod(), System.Xml.Serialization.ReflectionXmlSerializationReader.WriteLiteralStructMethod(), and System.Xml.Serialization.XmlSerializationWriterILGen.WritePrimitive().