Terraria: System.IO.Compression.GZipStream.ReadAsync
ReadAsync() [2/3]
override Task< int > System.IO.Compression.GZipStream.ReadAsync (byte[] buffer, int offset, int count, CancellationToken cancellationToken) inline virtual
Reimplemented from System.IO.Stream.
Definition at line 170 of file GZipStream.cs.
    {
        CheckDeflateStream();
        return _deflateStream.ReadAsync(buffer, offset, count, cancellationToken);
    }
References System.IO.Compression.GZipStream._deflateStream, System.buffer, System.cancellationToken, System.IO.Compression.GZipStream.CheckDeflateStream(), System.count, System.offset, and System.IO.Compression.DeflateStream.ReadAsync().
Referenced by System.IO.Compression.GZipStream.BeginRead().