Terraria: System.IO.Compression.GZipStream.CheckDeflateStream
CheckDeflateStream()
void System.IO.Compression.GZipStream.CheckDeflateStream () inline private
Definition at line 214 of file GZipStream.cs.
    {
        if (_deflateStream == null)
        {
            ThrowStreamClosedException();
        }
    }
References System.IO.Compression.GZipStream._deflateStream, and System.IO.Compression.GZipStream.ThrowStreamClosedException().
Referenced by System.IO.Compression.GZipStream.CopyTo(), System.IO.Compression.GZipStream.CopyToAsync(), System.IO.Compression.GZipStream.Flush(), System.IO.Compression.GZipStream.FlushAsync(), System.IO.Compression.GZipStream.Read(), System.IO.Compression.GZipStream.Read(), System.IO.Compression.GZipStream.ReadAsync(), System.IO.Compression.GZipStream.ReadAsync(), System.IO.Compression.GZipStream.ReadByte(), System.IO.Compression.GZipStream.Write(), System.IO.Compression.GZipStream.Write(), System.IO.Compression.GZipStream.WriteAsync(), and System.IO.Compression.GZipStream.WriteAsync().