Terraria: System.IO.Compression.GZipStream.WriteAsync
WriteAsync() [2/3]
override Task System.IO.Compression.GZipStream.WriteAsync (byte[] buffer, int offset, int count, CancellationToken cancellationToken) inline virtual
Reimplemented from System.IO.Stream.
Definition at line 186 of file GZipStream.cs.
    {
        CheckDeflateStream();
        return _deflateStream.WriteAsync(buffer, offset, count, cancellationToken);
    }
References System.IO.Compression.GZipStream._deflateStream, System.buffer, System.cancellationToken, System.IO.Compression.GZipStream.CheckDeflateStream(), System.count, System.offset, and System.IO.Compression.DeflateStream.WriteAsync().
Referenced by System.IO.Compression.GZipStream.BeginWrite().