Terraria: System.Net.NetworkInformation.SystemIPv4InterfaceProperties.GetPerAdapterInfo
GetPerAdapterInfo()
void System.Net.NetworkInformation.SystemIPv4InterfaceProperties.GetPerAdapterInfo (uint index) inline private
Definition at line 45 of file SystemIPv4InterfaceProperties.cs.
    {
        if (index == 0)
        {
            return;
        }
        uint pOutBufLen = 0u;
        uint perAdapterInfo = global::Interop.IpHlpApi.GetPerAdapterInfo(index, IntPtr.Zero, ref pOutBufLen);
        while (true)
        {
            switch (perAdapterInfo)
            {
            case 111u:
            {
                IntPtr intPtr = Marshal.AllocHGlobal((int)pOutBufLen);
                try
                {
                    perAdapterInfo = global::Interop.IpHlpApi.GetPerAdapterInfo(index, intPtr, ref pOutBufLen);
                    if (perAdapterInfo == 0)
                    {
                        global::Interop.IpHlpApi.IpPerAdapterInfo ipPerAdapterInfo = Marshal.PtrToStructure<global::Interop.IpHlpApi.IpPerAdapterInfo>(intPtr);
                        _autoConfigEnabled = ipPerAdapterInfo.autoconfigEnabled;
                        _autoConfigActive = ipPerAdapterInfo.autoconfigActive;
                    }
                }
                finally
                {
                    Marshal.FreeHGlobal(intPtr);
                }
                break;
            }
            default:
                throw new NetworkInformationException((int)perAdapterInfo);
            case 0u:
                return;
            }
        }
    }
References System.Net.NetworkInformation.SystemIPv4InterfaceProperties._autoConfigActive, System.Net.NetworkInformation.SystemIPv4InterfaceProperties._autoConfigEnabled, System.Runtime.InteropServices.Marshal.AllocHGlobal(), System.Runtime.InteropServices.Marshal.FreeHGlobal(), System.index, System.Runtime.InteropServices.Marshal.PtrToStructure(), and System.IntPtr.Zero.
Referenced by System.Net.NetworkInformation.SystemIPv4InterfaceProperties.SystemIPv4InterfaceProperties().