Terraria: Terraria.NetMessage.DecompressTileBlock
DecompressTileBlock()
static void Terraria.NetMessage.DecompressTileBlock (Stream stream) inline static
Definition at line 2213 of file NetMessage.cs.
    {
        //IL_0003: Unknown result type (might be due to invalid IL or missing references)
        //IL_0009: Expected O, but got Unknown
        DeflateStream val = new DeflateStream(stream, (CompressionMode)1, true);
        try
        {
            BinaryReader binaryReader = new BinaryReader((Stream)(object)val);
            DecompressTileBlock_Inner(binaryReader, binaryReader.ReadInt32(), binaryReader.ReadInt32(), binaryReader.ReadInt16(), binaryReader.ReadInt16());
        }
        finally
        {
            ((IDisposable)val)?.Dispose();
        }
    }
References Terraria.NetMessage.DecompressTileBlock_Inner(), System.IO.BinaryReader.ReadInt16(), System.IO.BinaryReader.ReadInt32(), and System.stream.
Referenced by Terraria.MessageBuffer.GetData().