Terraria: Terraria.NetMessage.SendObjectPlacement
SendObjectPlacement()
static void Terraria.NetMessage.SendObjectPlacement (int whoAmi, int x, int y, int type, int style, int alternative, int random, int direction) inline static
    {
        int remoteClient;
        int ignoreClient;
        if (Main.netMode == 2)
        {
            remoteClient = -1;
            ignoreClient = whoAmi;
        }
        else
        {
            remoteClient = whoAmi;
            ignoreClient = -1;
        }
        SendData(79, remoteClient, ignoreClient, null, x, y, type, style, alternative, random, direction);
    }
References Terraria.Main.netMode, and Terraria.NetMessage.SendData().
Referenced by Terraria.MessageBuffer.GetData(), Terraria.Player.PlaceThing_Tiles_PlaceIt(), and Terraria.Player.TryReplantingTree().