Terraria: Terraria.Cinematics.Film.AddKeyFrame
AddKeyFrame()
void Terraria.Cinematics.Film.AddKeyFrame (int frame, FrameEvent frameEvent) inline inherited
Definition at line 100 of file Film.cs.
    {
        _sequences.Add(new Sequence(frameEvent, frame, 1));
        _frameCount = Math.Max(_frameCount, frame + 1);
    }
References Terraria.Cinematics.Film._frameCount, Terraria.Cinematics.Film._sequences, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), and System.Math.Max().
Referenced by Terraria.Cinematics.DD2Film.DD2Film(), Terraria.Cinematics.Film.AddKeyFrames(), and Terraria.Cinematics.Film.AppendKeyFrame().