Terraria: Terraria.NetMessage.TrySendData
TrySendData()
static bool Terraria.NetMessage.TrySendData (int msgType, int remoteClient = -1, int ignoreClient = -1, NetworkText text = null, int number = 0, float number2 = 0f, float number3 = 0f, float number4 = 0f, int number5 = 0, int number6 = 0, int number7 = 0) inline static
Definition at line 75 of file NetMessage.cs.
    {
        try
        {
            SendData(msgType, remoteClient, ignoreClient, text, number, number2, number3, number4, number5, number6, number7);
        }
        catch (Exception)
        {
            return false;
        }
        return true;
    }
References Terraria.NetMessage.SendData(), and System.text.
Referenced by Terraria.MessageBuffer.GetData(), Terraria.WorldGen.KillTile(), Terraria.NPC.RerollVariation(), Terraria.Main.SkipToTime(), Terraria.MessageBuffer.TrySendingItemArray(), Terraria.Player.TrySwitchingLoadout(), and Terraria.NPC.UnlockOrExchangePet().