Terraria: Terraria.NetMessage.SendNPCHousesAndTravelShop
SendNPCHousesAndTravelShop()
static void Terraria.NetMessage.SendNPCHousesAndTravelShop (int plr) inline static private
Definition at line 2754 of file NetMessage.cs.
    {
        bool flag = false;
        for (int i = 0; i < 200; i++)
        {
            NPC nPC = Main.npc[i];
            if (!nPC.active)
            {
                continue;
            }
            bool flag2 = nPC.townNPC && NPC.TypeToDefaultHeadIndex(nPC.type) > 0;
            if (nPC.aiStyle == 7)
            {
                flag2 = true;
            }
            if (flag2)
            {
                if (!flag && nPC.type == 368)
                {
                    flag = true;
                }
                byte householdStatus = WorldGen.TownManager.GetHouseholdStatus(nPC);
                SendData(60, plr, -1, null, i, nPC.homeTileX, nPC.homeTileY, (int)householdStatus);
            }
        }
        if (flag)
        {
            SendTravelShop(plr);
        }
    }
References Terraria.Entity.active, Terraria.NPC.aiStyle, Terraria.GameContent.TownRoomManager.GetHouseholdStatus(), Terraria.NPC.homeTileX, Terraria.NPC.homeTileY, Terraria.Main.npc, Terraria.NetMessage.SendData(), Terraria.NetMessage.SendTravelShop(), Terraria.WorldGen.TownManager, Terraria.NPC.type, and Terraria.NPC.TypeToDefaultHeadIndex().
Referenced by Terraria.NetMessage.SyncConnectedPlayer().