Terraria: Terraria.NetMessage.CompressTileBlock
CompressTileBlock()
static void Terraria.NetMessage.CompressTileBlock (int xStart, int yStart, short width, short height, Stream stream) inline static
Definition at line 1873 of file NetMessage.cs.
    {
        //IL_0004: Unknown result type (might be due to invalid IL or missing references)
        //IL_000a: Expected O, but got Unknown
        DeflateStream val = new DeflateStream(stream, (CompressionMode)0, true);
        try
        {
            BinaryWriter binaryWriter = new BinaryWriter((Stream)(object)val);
            binaryWriter.Write(xStart);
            binaryWriter.Write(yStart);
            binaryWriter.Write(width);
            binaryWriter.Write(height);
            CompressTileBlock_Inner(binaryWriter, xStart, yStart, width, height);
        }
        finally
        {
            ((IDisposable)val)?.Dispose();
        }
    }
References Terraria.NetMessage.CompressTileBlock_Inner(), System.stream, and System.IO.BinaryWriter.Write().
Referenced by Terraria.NetMessage.SendData().