Terraria: Terraria.NetMessage.SendSection
SendSection()
static void Terraria.NetMessage.SendSection (int whoAmi, int sectionX, int sectionY) inline static
Definition at line 2651 of file NetMessage.cs.
    {
        if (Main.netMode != 2)
        {
            return;
        }
        try
        {
            if (sectionX < 0 || sectionY < 0 || sectionX >= Main.maxSectionsX || sectionY >= Main.maxSectionsY || Netplay.Clients[whoAmi].TileSections[sectionX, sectionY])
            {
                return;
            }
            Netplay.Clients[whoAmi].TileSections[sectionX, sectionY] = true;
            int number = sectionX * 200;
            int num = sectionY * 150;
            int num2 = 150;
            for (int i = num; i < num + 150; i += num2)
            {
                SendData(10, whoAmi, -1, null, number, i, 200f, num2);
            }
            for (int j = 0; j < 200; j++)
            {
                if (Main.npc[j].active && Main.npc[j].townNPC)
                {
                    int sectionX2 = Netplay.GetSectionX((int)(Main.npc[j].position.X / 16f));
                    int sectionY2 = Netplay.GetSectionY((int)(Main.npc[j].position.Y / 16f));
                    if (sectionX2 == sectionX && sectionY2 == sectionY)
                    {
                        SendData(23, whoAmi, -1, null, j);
                    }
                }
            }
        }
        catch
        {
        }
    }
References Terraria.Entity.active, Terraria.Netplay.Clients, Terraria.Netplay.GetSectionX(), Terraria.Netplay.GetSectionY(), Terraria.Main.maxSectionsX, Terraria.Main.maxSectionsY, Terraria.Main.netMode, Terraria.Main.npc, Terraria.Entity.position, Terraria.NetMessage.SendData(), Terraria.RemoteClient.TileSections, and Terraria.NPC.townNPC.
Referenced by Terraria.RemoteClient.CheckSection(), and Terraria.MessageBuffer.GetData().