Terraria: Terraria.NetMessage.EnsureLocalPlayerIsPresent
EnsureLocalPlayerIsPresent()
static void Terraria.NetMessage.EnsureLocalPlayerIsPresent () inline static private
Definition at line 2785 of file NetMessage.cs.
    {
        if (!Main.autoShutdown)
        {
            return;
        }
        bool flag = false;
        for (int i = 0; i < 255; i++)
        {
            if (DoesPlayerSlotCountAsAHost(i))
            {
                flag = true;
                break;
            }
        }
        if (!flag)
        {
            Console.WriteLine(Language.GetTextValue("Net.ServerAutoShutdown"));
            Netplay.Disconnect = true;
        }
    }
References Terraria.Main.autoShutdown, Terraria.NetMessage.DoesPlayerSlotCountAsAHost(), Terraria.Localization.Language.GetTextValue(), and System.Console.WriteLine().
Referenced by Terraria.NetMessage.SyncConnectedPlayer(), and Terraria.NetMessage.SyncDisconnectedPlayer().