Terraria: Terraria.NetMessage.sendWater
sendWater()
static void Terraria.NetMessage.sendWater (int x, int y) inline static
Definition at line 2710 of file NetMessage.cs.
    {
        if (Main.netMode == 1)
        {
            SendData(48, -1, -1, null, x, y);
            return;
        }
        for (int i = 0; i < 256; i++)
        {
            if ((buffer[i].broadcast || Netplay.Clients[i].State >= 3) && Netplay.Clients[i].IsConnected())
            {
                int num = x / 200;
                int num2 = y / 150;
                if (Netplay.Clients[i].TileSections[num, num2])
                {
                    SendData(48, i, -1, null, x, y);
                }
            }
        }
    }
References Terraria.NetMessage.buffer, Terraria.Netplay.Clients, Terraria.Main.netMode, and Terraria.NetMessage.SendData().
Referenced by Terraria.WorldGen.EmptyLiquid(), Terraria.Player.ItemCheck_UseBuckets(), and Terraria.WorldGen.PlaceLiquid().