Terraria: Terraria.GameContent.Biomes.Desert.DesertHive.ClusterGroup.SearchForCluster
SearchForCluster()
static void Terraria.GameContent.Biomes.Desert.DesertHive.ClusterGroup.SearchForCluster (bool blockMap[,], List< Point > pointCluster, int x, int y, int level = 2) inline static private
Definition at line 45 of file DesertHive.cs.
        {
            pointCluster.Add(new Point(x, y));
            blockMap[x, y] = false;
            level--;
            if (level != -1)
            {
                if (x > 0 && blockMap[x - 1, y])
                {
                    SearchForCluster(blockMap, pointCluster, x - 1, y, level);
                }
                if (x < blockMap.GetLength(0) - 1 && blockMap[x + 1, y])
                {
                    SearchForCluster(blockMap, pointCluster, x + 1, y, level);
                }
                if (y > 0 && blockMap[x, y - 1])
                {
                    SearchForCluster(blockMap, pointCluster, x, y - 1, level);
                }
                if (y < blockMap.GetLength(1) - 1 && blockMap[x, y + 1])
                {
                    SearchForCluster(blockMap, pointCluster, x, y + 1, level);
                }
            }
        }
References System.Collections.Generic.Dictionary< TKey, TValue >.Add(), and Terraria.GameContent.Biomes.Desert.DesertHive.ClusterGroup.SearchForCluster().
Referenced by Terraria.GameContent.Biomes.Desert.DesertHive.ClusterGroup.Generate(), and Terraria.GameContent.Biomes.Desert.DesertHive.ClusterGroup.SearchForCluster().