Terraria: System.Net.WebSockets.WebSocketBase.OutstandingOperationHelper.TryStartOperation
TryStartOperation()
bool System.Net.WebSockets.WebSocketBase.OutstandingOperationHelper.TryStartOperation (CancellationToken userCancellationToken, out CancellationToken linkedCancellationToken) inline
Definition at line 569 of file WebSocketBase.cs.
        {
            linkedCancellationToken = CancellationToken.None;
            ThrowIfDisposed();
            lock (_thisLock)
            {
                if (++_operationsOutstanding == 1)
                {
                    linkedCancellationToken = CreateLinkedCancellationToken(userCancellationToken);
                    return true;
                }
                return false;
            }
        }
References System.Net.WebSockets.WebSocketBase.OutstandingOperationHelper._operationsOutstanding, System.Net.WebSockets.WebSocketBase.OutstandingOperationHelper._thisLock, System.Net.WebSockets.WebSocketBase.OutstandingOperationHelper.CreateLinkedCancellationToken(), System.Threading.CancellationToken.None, and System.Net.WebSockets.WebSocketBase.OutstandingOperationHelper.ThrowIfDisposed().
Referenced by System.Net.WebSockets.WebSocketBase.CloseAsyncCore(), System.Net.WebSockets.WebSocketBase.CloseOutputAsyncCore(), System.Net.WebSockets.WebSocketBase.ReceiveAsyncCore(), and System.Net.WebSockets.WebSocketBase.SendAsyncCore().