Terraria: System.Net.WebSockets.WebSocketBase.OutstandingOperationHelper.CompleteOperation
CompleteOperation()
void System.Net.WebSockets.WebSocketBase.OutstandingOperationHelper.CompleteOperation (bool ownsCancellationTokenSource) inline
Definition at line 584 of file WebSocketBase.cs.
        {
            if (_isDisposed)
            {
                return;
            }
            CancellationTokenSource cancellationTokenSource = null;
            lock (_thisLock)
            {
                _operationsOutstanding--;
                if (ownsCancellationTokenSource)
                {
                    cancellationTokenSource = _cancellationTokenSource;
                    _cancellationTokenSource = null;
                }
            }
            cancellationTokenSource?.Dispose();
        }
References System.Net.WebSockets.WebSocketBase.OutstandingOperationHelper._cancellationTokenSource, System.Net.WebSockets.WebSocketBase.OutstandingOperationHelper._isDisposed, System.Net.WebSockets.WebSocketBase.OutstandingOperationHelper._operationsOutstanding, and System.Net.WebSockets.WebSocketBase.OutstandingOperationHelper._thisLock.
Referenced by System.Net.WebSockets.WebSocketBase.CloseAsyncCore(), System.Net.WebSockets.WebSocketBase.CloseOutputAsyncCore(), System.Net.WebSockets.WebSocketBase.ReceiveAsyncCore(), and System.Net.WebSockets.WebSocketBase.SendAsyncCore().