Terraria: System.Data.SqlTypes.SqlSingle.CompareTo
CompareTo() [1/3]
int System.Data.SqlTypes.SqlSingle.CompareTo (object? value) inline
Implements System.IComparable< in T >.
Definition at line 383 of file SqlSingle.cs.
    {
        if (value is SqlSingle value2)
        {
            return CompareTo(value2);
        }
        throw ADP.WrongType(value.GetType(), typeof(SqlSingle));
    }
References System.Data.SqlTypes.SqlSingle.CompareTo(), System.Xml.Dictionary, System.value, and System.Data.Common.ADP.WrongType().
Referenced by System.Data.Common.SqlSingleStorage.Compare(), System.Data.SqlTypes.SqlSingle.CompareTo(), and System.Data.Common.SqlSingleStorage.CompareValueTo().