Terraria: System.Data.SqlTypes.SqlSingle.Null
Null
readonly SqlSingle System.Data.SqlTypes.SqlSingle.Null = new SqlSingle(fNull: true) static
Definition at line 17 of file SqlSingle.cs.
Referenced by System.Data.Common.SqlConvert.ConvertToSqlSingle(), System.Data.SqlTypes.SqlSingle.operator SqlSingle(), System.Data.SqlTypes.SqlSingle.operator SqlSingle(), System.Data.SqlTypes.SqlSingle.operator SqlSingle(), System.Data.SqlTypes.SqlSingle.operator SqlSingle(), System.Data.SqlTypes.SqlSingle.operator SqlSingle(), System.Data.SqlTypes.SqlSingle.operator SqlSingle(), System.Data.SqlTypes.SqlSingle.operator SqlSingle(), System.Data.SqlTypes.SqlSingle.operator SqlSingle(), System.Data.SqlTypes.SqlSingle.operator SqlSingle(), System.Data.SqlTypes.SqlSingle.operator*(), System.Data.SqlTypes.SqlSingle.operator+(), System.Data.SqlTypes.SqlSingle.operator-(), System.Data.SqlTypes.SqlSingle.operator-(), System.Data.SqlTypes.SqlSingle.operator/(), and System.Data.SqlTypes.SqlSingle.Parse().