Terraria: Terraria.GameContent.Biomes.HiveBiome.FrameOutAllHiveContents
FrameOutAllHiveContents()
static void Terraria.GameContent.Biomes.HiveBiome.FrameOutAllHiveContents (Point origin, int squareHalfWidth) inline static private
Definition at line 128 of file HiveBiome.cs.
    {
        int num = Math.Max(10, origin.X - squareHalfWidth);
        int num2 = Math.Min(Main.maxTilesX - 10, origin.X + squareHalfWidth);
        int num3 = Math.Max(10, origin.Y - squareHalfWidth);
        int num4 = Math.Min(Main.maxTilesY - 10, origin.Y + squareHalfWidth);
        for (int i = num; i < num2; i++)
        {
            for (int j = num3; j < num4; j++)
            {
                Tile tile = Main.tile[i, j];
                if (tile.active() && tile.type == 225)
                {
                    WorldGen.SquareTileFrame(i, j);
                }
                if (tile.wall == 86)
                {
                    WorldGen.SquareWallFrame(i, j);
                }
            }
        }
    }
References Terraria.Tile.active(), System.Math.Max(), Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, System.Math.Min(), Terraria.WorldGen.SquareTileFrame(), Terraria.WorldGen.SquareWallFrame(), Terraria.Main.tile, Terraria.Tile.type, Terraria.Tile.wall, Microsoft.Xna.Framework.Point.X, and Microsoft.Xna.Framework.Point.Y.
Referenced by Terraria.GameContent.Biomes.HiveBiome.Place().