Terraria: Terraria.GameContent.Biomes.HiveBiome.CreateHiveTunnel
CreateHiveTunnel()
static Vector2D Terraria.GameContent.Biomes.HiveBiome.CreateHiveTunnel (int i, int j, UnifiedRandom random) inline static private
    {
        //IL_052f: Unknown result type (might be due to invalid IL or missing references)
        //IL_00cf: Unknown result type (might be due to invalid IL or missing references)
        //IL_011b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0126: Unknown result type (might be due to invalid IL or missing references)
        //IL_0131: Unknown result type (might be due to invalid IL or missing references)
        //IL_013c: Unknown result type (might be due to invalid IL or missing references)
        //IL_04bf: Unknown result type (might be due to invalid IL or missing references)
        //IL_04c0: Unknown result type (might be due to invalid IL or missing references)
        //IL_04c2: Unknown result type (might be due to invalid IL or missing references)
        //IL_04c7: Unknown result type (might be due to invalid IL or missing references)
        //IL_026b: Unknown result type (might be due to invalid IL or missing references)
        //IL_027a: Unknown result type (might be due to invalid IL or missing references)
        double num = random.Next(12, 21);
        double num2 = random.Next(10, 21);
        if (WorldGen.drunkWorldGen)
        {
            num = random.Next(8, 26);
            num2 = random.Next(10, 41);
            double num3 = (double)Main.maxTilesX / 4200.0;
            num3 = (num3 + 1.0) / 2.0;
            num *= num3;
            num2 *= num3;
        }
        else if (WorldGen.remixWorldGen)
        {
            num += (double)random.Next(3);
        }
        double num4 = num;
        Vector2D val = default(Vector2D);
        val.X = i;
        val.Y = j;
        Vector2D val2 = default(Vector2D);
        val2.X = (double)random.Next(-10, 11) * 0.2;
        val2.Y = (double)random.Next(-10, 11) * 0.2;
        while (num > 0.0 && num2 > 0.0)
        {
            if (val.Y > (double)(Main.maxTilesY - 250))
            {
                num2 = 0.0;
            }
            num = num4 * (1.0 + (double)random.Next(-20, 20) * 0.01);
            num2 -= 1.0;
            int num5 = (int)(val.X - num);
            int num6 = (int)(val.X + num);
            int num7 = (int)(val.Y - num);
            int num8 = (int)(val.Y + num);
            if (num5 < 1)
            {
                num5 = 1;
            }
            if (num6 > Main.maxTilesX - 1)
            {
                num6 = Main.maxTilesX - 1;
            }
            if (num7 < 1)
            {
                num7 = 1;
            }
            if (num8 > Main.maxTilesY - 1)
            {
                num8 = Main.maxTilesY - 1;
            }
            for (int k = num5; k < num6; k++)
            {
                for (int l = num7; l < num8; l++)
                {
                    if (!WorldGen.InWorld(k, l, 50))
                    {
                        num2 = 0.0;
                    }
                    else
                    {
                        if (Main.tile[k - 10, l].wall == 87)
{
                            num2 = 0.0;
                        }
                        if (Main.tile[k + 10, l].wall == 87)
{
                            num2 = 0.0;
                        }
                        if (Main.tile[k, l - 10].wall == 87)
{
                            num2 = 0.0;
                        }
                        if (Main.tile[k, l + 10].wall == 87)
{
                            num2 = 0.0;
                        }
                    }
                    if ((double)l < Main.worldSurface && Main.tile[k, l - 5].wall == 0)
                    {
                        num2 = 0.0;
                    }
                    double num9 = Math.Abs((double)k - val.X);
                    double num10 = Math.Abs((double)l - val.Y);
                    double num11 = Math.Sqrt(num9 * num9 + num10 * num10);
                    if (num11 < num4 * 0.4 * (1.0 + (double)random.Next(-10, 11) * 0.005))
                    {
                        if (random.Next(3) == 0)
{
                            Main.tile[k, l].liquid = byte.MaxValue;
                        }
                        if (WorldGen.drunkWorldGen)
{
                            Main.tile[k, l].liquid = byte.MaxValue;
                        }
                        Main.tile[k, l].honey(honey: true);
                        Main.tile[k, l].wall = 86;
                        Main.tile[k, l].active(active: false);
                        Main.tile[k, l].halfBrick(halfBrick: false);
                        Main.tile[k, l].slope(0);
                    }
                    else if (num11 < num4 * 0.75 * (1.0 + (double)random.Next(-10, 11) * 0.005))
                    {
                        Main.tile[k, l].liquid = 0;
                        if (Main.tile[k, l].wall != 86)
{
                            Main.tile[k, l].active(active: true);
                            Main.tile[k, l].halfBrick(halfBrick: false);
                            Main.tile[k, l].slope(0);
                            Main.tile[k, l].type = 225;
                        }
                    }
                    if (num11 < num4 * 0.6 * (1.0 + (double)random.Next(-10, 11) * 0.005))
                    {
                        Main.tile[k, l].wall = 86;
                        if (WorldGen.drunkWorldGen && random.Next(2) == 0)
{
                            Main.tile[k, l].liquid = byte.MaxValue;
                            Main.tile[k, l].honey(honey: true);
                        }
                    }
                }
            }
            val += val2;
            num2 -= 1.0;
            val2.Y += (double)random.Next(-10, 11) * 0.05;
            val2.X += (double)random.Next(-10, 11) * 0.05;
        }
        return val;
    }
References Terraria.Tile.active(), Terraria.WorldGen.drunkWorldGen, Terraria.Tile.halfBrick(), Terraria.Tile.honey(), Terraria.WorldGen.InWorld(), Terraria.Tile.liquid, Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.Utilities.UnifiedRandom.Next(), Terraria.WorldGen.remixWorldGen, Terraria.Tile.slope(), Terraria.Main.tile, Terraria.Tile.type, Terraria.Tile.wall, Terraria.Main.worldSurface, ReLogic.Utilities.Vector2D.X, and ReLogic.Utilities.Vector2D.Y.
Referenced by Terraria.GameContent.Biomes.HiveBiome.Place().