Terraria: Terraria.GameContent.Biomes.HiveBiome.Place
Place()
override bool Terraria.GameContent.Biomes.HiveBiome.Place (Point origin, StructureMap structures) inline
    {
        //IL_00ec: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f1: Unknown result type (might be due to invalid IL or missing references)
        //IL_0139: Unknown result type (might be due to invalid IL or missing references)
        //IL_013b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0150: Unknown result type (might be due to invalid IL or missing references)
        //IL_0158: Unknown result type (might be due to invalid IL or missing references)
        //IL_0165: Unknown result type (might be due to invalid IL or missing references)
        //IL_016a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0178: Unknown result type (might be due to invalid IL or missing references)
        //IL_017a: Unknown result type (might be due to invalid IL or missing references)
        //IL_017f: Unknown result type (might be due to invalid IL or missing references)
        //IL_018b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0247: Unknown result type (might be due to invalid IL or missing references)
        //IL_0260: Unknown result type (might be due to invalid IL or missing references)
        //IL_0262: Unknown result type (might be due to invalid IL or missing references)
        //IL_0298: Unknown result type (might be due to invalid IL or missing references)
        //IL_02a0: Unknown result type (might be due to invalid IL or missing references)
        //IL_02b0: Unknown result type (might be due to invalid IL or missing references)
        //IL_02b2: Unknown result type (might be due to invalid IL or missing references)
        //IL_02c9: Unknown result type (might be due to invalid IL or missing references)
        //IL_02d1: Unknown result type (might be due to invalid IL or missing references)
        //IL_02ea: Unknown result type (might be due to invalid IL or missing references)
        //IL_02f2: Unknown result type (might be due to invalid IL or missing references)
        //IL_0308: Unknown result type (might be due to invalid IL or missing references)
        if (!structures.CanPlace(new Rectangle(origin.X - 50, origin.Y - 50, 100, 100)))
        {
            return false;
        }
        if (TooCloseToImportantLocations(origin))
        {
            return false;
        }
        Ref<int> @ref = new Ref<int>(0);
        Ref<int> ref2 = new Ref<int>(0);
        Ref<int> ref3 = new Ref<int>(0);
        WorldUtils.Gen(origin, new Shapes.Circle(15), Actions.Chain(new Modifiers.IsSolid(), new Actions.Scanner(@ref), new Modifiers.OnlyTiles(60, 59), new Actions.Scanner(ref2), new Modifiers.OnlyTiles(60), new Actions.Scanner(ref3)));
        if ((double)ref2.Value / (double)@ref.Value < 0.75 || ref3.Value < 2)
        {
            return false;
        }
        int num = 0;
        int[] array = new int[1000];
        int[] array2 = new int[1000];
        Vector2D val = origin.ToVector2D();
        int num2 = WorldGen.genRand.Next(2, 5);
        if (WorldGen.drunkWorldGen)
        {
            num2 += WorldGen.genRand.Next(7, 10);
        }
        else if (WorldGen.remixWorldGen)
        {
            num2 += WorldGen.genRand.Next(2, 5);
        }
        for (int i = 0; i < num2; i++)
        {
            Vector2D val2 = val;
            int num3 = WorldGen.genRand.Next(2, 5);
            for (int j = 0; j < num3; j++)
            {
                val2 = CreateHiveTunnel((int)val.X, (int)val.Y, WorldGen.genRand);
            }
            val = val2;
            array[num] = (int)val.X;
            array2[num] = (int)val.Y;
            num++;
        }
        FrameOutAllHiveContents(origin, 50);
        for (int k = 0; k < num; k++)
        {
            int num4 = array[k];
            int y = array2[k];
            int num5 = 1;
            if (WorldGen.genRand.Next(2) == 0)
            {
                num5 = -1;
            }
            bool flag = false;
            while (WorldGen.InWorld(num4, y, 10) && BadSpotForHoneyFall(num4, y))
            {
                num4 += num5;
                if (Math.Abs(num4 - array[k]) > 50)
                {
                    flag = true;
                    break;
                }
            }
            if (!flag)
            {
                num4 += num5;
                if (!SpotActuallyNotInHive(num4, y))
                {
                    CreateBlockedHoneyCube(num4, y);
                    CreateDentForHoneyFall(num4, y, num5);
                }
            }
        }
        CreateStandForLarva(val);
        if (WorldGen.drunkWorldGen)
        {
            for (int l = 0; l < 1000; l++)
            {
                Vector2D val3 = val;
                val3.X += WorldGen.genRand.Next(-50, 51);
                val3.Y += WorldGen.genRand.Next(-50, 51);
                if (WorldGen.InWorld((int)val3.X, (int)val3.Y) && Vector2D.Distance(val, val3) > 10.0 && !Main.tile[(int)val3.X, (int)val3.Y].active() && Main.tile[(int)val3.X, (int)val3.Y].wall == 86)
                {
                    CreateStandForLarva(val3);
                    break;
                }
            }
        }
        structures.AddProtectedStructure(new Rectangle(origin.X - 50, origin.Y - 50, 100, 100), 5);
        return true;
    }
References Terraria.Tile.active(), Terraria.WorldBuilding.StructureMap.AddProtectedStructure(), Terraria.GameContent.Biomes.HiveBiome.BadSpotForHoneyFall(), Terraria.WorldBuilding.StructureMap.CanPlace(), Terraria.WorldBuilding.Actions.Chain(), Terraria.GameContent.Biomes.HiveBiome.CreateBlockedHoneyCube(), Terraria.GameContent.Biomes.HiveBiome.CreateDentForHoneyFall(), Terraria.GameContent.Biomes.HiveBiome.CreateHiveTunnel(), Terraria.GameContent.Biomes.HiveBiome.CreateStandForLarva(), ReLogic.Utilities.Vector2D.Distance(), Terraria.WorldGen.drunkWorldGen, Terraria.GameContent.Biomes.HiveBiome.FrameOutAllHiveContents(), Terraria.WorldBuilding.WorldUtils.Gen(), Terraria.WorldGen.genRand, Terraria.WorldGen.InWorld(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.WorldGen.remixWorldGen, Terraria.GameContent.Biomes.HiveBiome.SpotActuallyNotInHive(), Terraria.Main.tile, Terraria.GameContent.Biomes.HiveBiome.TooCloseToImportantLocations(), Terraria.Ref< T >.Value, Terraria.Tile.wall, ReLogic.Utilities.Vector2D.X, and ReLogic.Utilities.Vector2D.Y.