Terraria: Terraria.GameContent.Biomes.HiveBiome.CreateStandForLarva
CreateStandForLarva()
static void Terraria.GameContent.Biomes.HiveBiome.CreateStandForLarva (Vector2D position) inline static
    {
        //IL_000a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0029: Unknown result type (might be due to invalid IL or missing references)
        //IL_0066: Unknown result type (might be due to invalid IL or missing references)
        //IL_006e: Unknown result type (might be due to invalid IL or missing references)
        GenVars.larvaX[GenVars.numLarva] = Utils.Clamp((int)position.X, 5, Main.maxTilesX - 5);
        GenVars.larvaY[GenVars.numLarva] = Utils.Clamp((int)position.Y, 5, Main.maxTilesY - 5);
        GenVars.numLarva++;
        if (GenVars.numLarva >= GenVars.larvaX.Length)
        {
            GenVars.numLarva = GenVars.larvaX.Length - 1;
        }
        int num = (int)position.X;
        int num2 = (int)position.Y;
        for (int i = num - 1; i <= num + 1 && i > 0 && i < Main.maxTilesX; i++)
        {
            for (int j = num2 - 2; j <= num2 + 1 && j > 0 && j < Main.maxTilesY; j++)
            {
                if (j != num2 + 1)
                {
                    Main.tile[i, j].active(active: false);
                    continue;
                }
                Main.tile[i, j].active(active: true);
                Main.tile[i, j].type = 225;
                Main.tile[i, j].slope(0);
                Main.tile[i, j].halfBrick(halfBrick: false);
            }
        }
    }
References Terraria.Tile.active(), Terraria.Tile.halfBrick(), Terraria.WorldBuilding.GenVars.larvaX, Terraria.WorldBuilding.GenVars.larvaY, Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.WorldBuilding.GenVars.numLarva, Terraria.Tile.slope(), Terraria.Main.tile, Terraria.Tile.type, ReLogic.Utilities.Vector2D.X, and ReLogic.Utilities.Vector2D.Y.
Referenced by Terraria.GameContent.Biomes.HiveBiome.Place().