Terraria: AmbientSky.GastropodGroupSkyEntity.CreateGroup
CreateGroup()
static List<GastropodGroupSkyEntity> AmbientSky.GastropodGroupSkyEntity.CreateGroup (Player player, FastRandom random) inline static
         {
             List<GastropodGroupSkyEntity> list = new List<GastropodGroupSkyEntity>();
             int num = 100;
             int num2 = random.Next(3, 8);
             VirtualCamera virtualCamera = new VirtualCamera(player);
             SpriteEffects spriteEffects = ((!(Main.WindForVisuals > 0f)) ? SpriteEffects.FlipHorizontally : SpriteEffects.None);
             Vector2 vector = default(Vector2);
             if (spriteEffects == SpriteEffects.FlipHorizontally)
             {
                 vector.X = virtualCamera.Position.X + virtualCamera.Size.X + (float)num;
             }
             else
             {
                 vector.X = virtualCamera.Position.X - (float)num;
             }
             vector.Y = random.NextFloat() * ((float)Main.worldSurface * 16f - 1600f - 3200f) + 3200f;
             float num3 = random.NextFloat() * 3f + 2f;
             int num4 = random.Next(30, 61) * 60;
             Vector2 vector2 = new Vector2(random.NextFloat() * 0.1f + 0.1f, random.NextFloat() * 0.3f + 0.3f);
             Vector2 targetOffset = new Vector2(random.NextFloat() * 2f - 1f, random.NextFloat() * 2f - 1f) * 120f;
             for (int i = 0; i < num2; i++)
             {
                 GastropodGroupSkyEntity gastropodGroupSkyEntity = new GastropodGroupSkyEntity(player, random);
                 gastropodGroupSkyEntity.Depth = num3 + random.NextFloat() * 0.5f;
                 gastropodGroupSkyEntity.Position = vector + new Vector2(random.NextFloat() * 20f - 10f, random.NextFloat() * 3f) * 60f;
                 gastropodGroupSkyEntity.Effects = spriteEffects;
                 gastropodGroupSkyEntity.SetPositionInWorldBasedOnScreenSpace(gastropodGroupSkyEntity.Position);
                 gastropodGroupSkyEntity.LifeTime = num4 + random.Next(301);
                 gastropodGroupSkyEntity.SetMagnetization(vector2 * (random.NextFloat() * 0.5f) * 0.05f, targetOffset);
                 list.Add(gastropodGroupSkyEntity);
             }
             return list;
         }
References AmbientSky.GastropodGroupSkyEntity.GastropodGroupSkyEntity(), AmbientSky.SkyEntity.Depth, AmbientSky.SkyEntity.Effects, AmbientSky.FadingSkyEntity.LifeTime, FastRandom.Next(), FastRandom.NextFloat(), AmbientSky.SkyEntity.Position, VirtualCamera.Position, AmbientSky.GastropodGroupSkyEntity.SetMagnetization(), AmbientSky.SkyEntity.SetPositionInWorldBasedOnScreenSpace(), VirtualCamera.Size, Main.WindForVisuals, and Main.worldSurface.
Referenced by AmbientSky.Spawn().