Terraria: System.Decimal.ToUInt32
ToUInt32() [1/3]
static uint System.Decimal.ToUInt32 (decimal d) inline static
Definition at line 2758 of file Decimal.cs.
    {
        Truncate(ref d);
        if ((d.High | d.Mid) == 0)
        {
            uint low = d.Low;
            if (!d.IsNegative || low == 0)
            {
                return low;
            }
        }
        throw new OverflowException(SR.Overflow_UInt32);
    }
References System.Runtime.Serialization.Dictionary, System.SR.Overflow_UInt32, and System.Decimal.Truncate().
Referenced by System.Decimal.operator uint(), System.Decimal.ToByte(), and System.Decimal.ToUInt16().