Terraria: System.Decimal.ToInt32
ToInt32() [1/3]
static int System.Decimal.ToInt32 (decimal d) inline static
Definition at line 2687 of file Decimal.cs.
    {
        Truncate(ref d);
        if ((d.High | d.Mid) == 0)
        {
            int low = (int)d.Low;
            if (!d.IsNegative)
            {
                if (low >= 0)
                {
                    return low;
                }
            }
            else
            {
                low = -low;
                if (low <= 0)
                {
                    return low;
                }
            }
        }
        throw new OverflowException(SR.Overflow_Int32);
    }
References System.Runtime.Serialization.Dictionary, System.SR.Overflow_Int32, and System.Decimal.Truncate().
Referenced by System.Decimal.operator int(), System.Decimal.ToInt16(), and System.Decimal.ToSByte().