Terraria: System.Decimal.AsMutable
AsMutable()
static ref DecCalc System.Decimal.AsMutable (ref decimal d) inline static private
Definition at line 3538 of file Decimal.cs.
    {
        return ref Unsafe.As<decimal, DecCalc>(ref d);
    }
References System.Runtime.Serialization.Dictionary.
Referenced by System.Decimal.Decimal(), System.Decimal.Decimal(), System.Decimal.Add(), System.Decimal.Ceiling(), System.Decimal.DecDivMod1E9(), System.Decimal.Divide(), System.Decimal.Floor(), System.Decimal.Multiply(), System.Decimal.operator%(), System.Decimal.operator*(), System.Decimal.operator+(), System.Decimal.operator-(), System.Decimal.operator/(), System.Decimal.Remainder(), System.Decimal.Round(), System.Decimal.Subtract(), System.Decimal.ToOACurrency(), and System.Decimal.Truncate().