Terraria: System.IO.FileSystem.VerifyValidPath
VerifyValidPath()
static void System.IO.FileSystem.VerifyValidPath (string path, string argName) inline static package
Definition at line 10 of file FileSystem.cs.
    {
        if (path == null)
        {
            throw new ArgumentNullException(argName);
        }
        if (path.Length == 0)
        {
            throw new ArgumentException(SR.Arg_PathEmpty, argName);
        }
        if (path.Contains('\0'))
        {
            throw new ArgumentException(SR.Argument_InvalidPathChars, argName);
        }
    }
References System.SR.Arg_PathEmpty, System.SR.Argument_InvalidPathChars, and System.Collections.Generic.Dictionary< TKey, TValue >.Contains().
Referenced by System.IO.FileSystemInfo.CreateAsSymbolicLink(), System.IO.Directory.CreateSymbolicLink(), System.IO.File.CreateSymbolicLink(), System.IO.Directory.ResolveLinkTarget(), and System.IO.File.ResolveLinkTarget().