Terraria: System.IO.FileSystem.ReplaceFile
ReplaceFile()
static void System.IO.FileSystem.ReplaceFile (string sourceFullPath, string destFullPath, string destBackupFullPath, bool ignoreMetadataErrors) inline static
Definition at line 252 of file FileSystem.cs.
    {
        int dwReplaceFlags = (ignoreMetadataErrors ? 2 : 0);
        if (!Interop.Kernel32.ReplaceFile(destFullPath, sourceFullPath, destBackupFullPath, dwReplaceFlags, IntPtr.Zero, IntPtr.Zero))
        {
            throw Win32Marshal.GetExceptionForWin32Error(Marshal.GetLastWin32Error());
        }
    }
References System.IO.Win32Marshal.GetExceptionForWin32Error(), System.Runtime.InteropServices.Marshal.GetLastWin32Error(), Interop.Kernel32.ReplaceFile(), and System.IntPtr.Zero.
Referenced by System.IO.FileInfo.Replace(), and System.IO.File.Replace().