Terraria: System.IO.FileSystem.SetLastAccessTime
SetLastAccessTime()
static void System.IO.FileSystem.SetLastAccessTime (string fullPath, DateTimeOffset time, bool asDirectory) inline static
Definition at line 554 of file FileSystem.cs.
    {
        SetFileTime(fullPath, asDirectory, -1L, time.ToFileTime(), -1L, -1L);
    }
References System.L, System.IO.FileSystem.SetFileTime(), and System.DateTimeOffset.ToFileTime().
Referenced by System.IO.Directory.SetLastAccessTime(), System.IO.File.SetLastAccessTime(), System.IO.Directory.SetLastAccessTimeUtc(), and System.IO.File.SetLastAccessTimeUtc().