Terraria: System.IO.FileSystem.SetFileTime
SetFileTime()
static unsafe void System.IO.FileSystem.SetFileTime (string fullPath, bool asDirectory, long creationTime = -1L, long lastAccessTime = -1L, long lastWriteTime = -1L, long changeTime = -1L, uint fileAttributes = 0u) inline static private
Definition at line 533 of file FileSystem.cs.
    {
        using SafeFileHandle hFile = OpenHandle(fullPath, asDirectory);
        Interop.Kernel32.FILE_BASIC_INFO fILE_BASIC_INFO = default(Interop.Kernel32.FILE_BASIC_INFO);
        fILE_BASIC_INFO.CreationTime = creationTime;
        fILE_BASIC_INFO.LastAccessTime = lastAccessTime;
        fILE_BASIC_INFO.LastWriteTime = lastWriteTime;
        fILE_BASIC_INFO.ChangeTime = changeTime;
        fILE_BASIC_INFO.FileAttributes = fileAttributes;
        Interop.Kernel32.FILE_BASIC_INFO fILE_BASIC_INFO2 = fILE_BASIC_INFO;
        if (!Interop.Kernel32.SetFileInformationByHandle(hFile, 0, &fILE_BASIC_INFO2, (uint)sizeof(Interop.Kernel32.FILE_BASIC_INFO)))
        {
            throw Win32Marshal.GetExceptionForLastWin32Error(fullPath);
        }
    }
References System.IO.Win32Marshal.GetExceptionForLastWin32Error(), System.IO.FileSystem.OpenHandle(), and Interop.Kernel32.SetFileInformationByHandle().
Referenced by System.IO.FileSystem.SetCreationTime(), System.IO.FileSystem.SetLastAccessTime(), and System.IO.FileSystem.SetLastWriteTime().