Terraria: System.IO.FileSystem.RemoveDirectoryRecursive
RemoveDirectoryRecursive()
static void System.IO.FileSystem.RemoveDirectoryRecursive (string fullPath, ref Interop::Kernel32::WIN32_FIND_DATA findData, bool topLevel) inline static private
Definition at line 408 of file FileSystem.cs.
    {
        Exception ex = null;
        using (SafeFindHandle safeFindHandle = Interop.Kernel32.FindFirstFile(Path.Join(fullPath, "*"), ref findData))
        {
            if (safeFindHandle.IsInvalid)
            {
                throw Win32Marshal.GetExceptionForLastWin32Error(fullPath);
            }
            int lastWin32Error;
            do
            {
                if ((findData.dwFileAttributes & 0x10) == 0)
                {
                    string stringFromFixedBuffer = findData.cFileName.GetStringFromFixedBuffer();
                    if (!Interop.Kernel32.DeleteFile(Path.Combine(fullPath, stringFromFixedBuffer)) && ex == null)
                    {
                        lastWin32Error = Marshal.GetLastWin32Error();
                        if (lastWin32Error != 2)
{
                            ex = Win32Marshal.GetExceptionForWin32Error(lastWin32Error, stringFromFixedBuffer);
                        }
                    }
                }
                else
                {
                    if (findData.cFileName.FixedBufferEqualsString(".") || findData.cFileName.FixedBufferEqualsString(".."))
                    {
                        continue;
                    }
                    string stringFromFixedBuffer2 = findData.cFileName.GetStringFromFixedBuffer();
                    if (!IsNameSurrogateReparsePoint(ref findData))
                    {
                        try
{
                            RemoveDirectoryRecursive(Path.Combine(fullPath, stringFromFixedBuffer2), ref findData, topLevel: false);
                        }
                        catch (Exception ex2)
{
                            if (ex == null)
{
                                ex = ex2;
                            }
                        }
                        continue;
                    }
                    if (findData.dwReserved0 == 2684354563u)
                    {
                        string mountPoint = Path.Join(fullPath, stringFromFixedBuffer2, "\\");
                        if (!Interop.Kernel32.DeleteVolumeMountPoint(mountPoint) && ex == null)
{
                            lastWin32Error = Marshal.GetLastWin32Error();
                            if (lastWin32Error != 0 && lastWin32Error != 3)
{
                                ex = Win32Marshal.GetExceptionForWin32Error(lastWin32Error, stringFromFixedBuffer2);
                            }
                        }
                    }
                    if (!Interop.Kernel32.RemoveDirectory(Path.Combine(fullPath, stringFromFixedBuffer2)) && ex == null)
                    {
                        lastWin32Error = Marshal.GetLastWin32Error();
                        if (lastWin32Error != 3)
{
                            ex = Win32Marshal.GetExceptionForWin32Error(lastWin32Error, stringFromFixedBuffer2);
                        }
                    }
                }
            }
            while (Interop.Kernel32.FindNextFile(safeFindHandle, ref findData));
            if (ex != null)
            {
                throw ex;
            }
            lastWin32Error = Marshal.GetLastWin32Error();
            if (lastWin32Error != 0 && lastWin32Error != 18)
            {
                throw Win32Marshal.GetExceptionForWin32Error(lastWin32Error, fullPath);
            }
        }
        RemoveDirectoryInternal(fullPath, topLevel, allowDirectoryNotEmpty: true);
    }
References System.IO.Path.Combine(), Interop.Kernel32.DeleteFile(), Interop.Kernel32.DeleteVolumeMountPoint(), Interop.Kernel32.FindFirstFile(), Interop.Kernel32.FindNextFile(), System.IO.Win32Marshal.GetExceptionForLastWin32Error(), System.IO.Win32Marshal.GetExceptionForWin32Error(), System.Runtime.InteropServices.Marshal.GetLastWin32Error(), System.IO.FileSystem.IsNameSurrogateReparsePoint(), System.IO.Path.Join(), Interop.Kernel32.RemoveDirectory(), System.IO.FileSystem.RemoveDirectoryInternal(), and System.IO.FileSystem.RemoveDirectoryRecursive().
Referenced by System.IO.FileSystem.RemoveDirectory(), and System.IO.FileSystem.RemoveDirectoryRecursive().