Terraria: System.IO.FileSystem.CreateDirectory
CreateDirectory() [2/2]
static unsafe void System.IO.FileSystem.CreateDirectory (string fullPath, byte[] securityDescriptor = null) inline static
Definition at line 108 of file FileSystem.cs.
    {
        if (DirectoryExists(fullPath))
        {
            return;
        }
        List<string> list = new List<string>();
        bool flag = false;
        int num = fullPath.Length;
        if (num >= 2 && PathInternal.EndsInDirectorySeparator(fullPath.AsSpan()))
        {
            num--;
        }
        int rootLength = PathInternal.GetRootLength(fullPath.AsSpan());
        if (num > rootLength)
        {
            int num2 = num - 1;
            while (num2 >= rootLength && !flag)
            {
                string text = fullPath.Substring(0, num2 + 1);
                if (!DirectoryExists(text))
                {
                    list.Add(text);
                }
                else
                {
                    flag = true;
                }
                while (num2 > rootLength && !PathInternal.IsDirectorySeparator(fullPath[num2]))
                {
                    num2--;
                }
                num2--;
            }
        }
        int count = list.Count;
        bool flag2 = true;
        int num3 = 0;
        string path = fullPath;
        fixed (byte* ptr = securityDescriptor)
        {
            Interop.Kernel32.SECURITY_ATTRIBUTES sECURITY_ATTRIBUTES = default(Interop.Kernel32.SECURITY_ATTRIBUTES);
            sECURITY_ATTRIBUTES.nLength = (uint)sizeof(Interop.Kernel32.SECURITY_ATTRIBUTES);
            sECURITY_ATTRIBUTES.lpSecurityDescriptor = (IntPtr)ptr;
            Interop.Kernel32.SECURITY_ATTRIBUTES lpSecurityAttributes = sECURITY_ATTRIBUTES;
            while (list.Count > 0)
            {
                string text2 = list[list.Count - 1];
                list.RemoveAt(list.Count - 1);
                flag2 = Interop.Kernel32.CreateDirectory(text2, ref lpSecurityAttributes);
                if (!flag2 && num3 == 0)
                {
                    int lastError = Marshal.GetLastWin32Error();
                    if (lastError != 183)
                    {
                        num3 = lastError;
                    }
                    else if (FileExists(text2) || (!DirectoryExists(text2, out lastError) && lastError == 5))
                    {
                        num3 = lastError;
                        path = text2;
                    }
                }
            }
        }
        if (count == 0 && !flag)
        {
            string pathRoot = Path.GetPathRoot(fullPath);
            if (!DirectoryExists(pathRoot))
            {
                throw Win32Marshal.GetExceptionForWin32Error(3, pathRoot);
            }
        }
        else if (!flag2 && num3 != 0)
        {
            throw Win32Marshal.GetExceptionForWin32Error(num3, path);
        }
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.count, System.Collections.Generic.Dictionary< TKey, TValue >.Count, Interop.Kernel32.CreateDirectory(), System.IO.FileSystem.DirectoryExists(), System.IO.PathInternal.EndsInDirectorySeparator(), System.IO.FileSystem.FileExists(), System.IO.Win32Marshal.GetExceptionForWin32Error(), System.Runtime.InteropServices.Marshal.GetLastWin32Error(), System.IO.Path.GetPathRoot(), System.IO.PathInternal.GetRootLength(), System.IO.PathInternal.IsDirectorySeparator(), System.list, and System.text.