Terraria: System.IO.FileSystem.RemoveDirectory
RemoveDirectory()
static void System.IO.FileSystem.RemoveDirectory (string fullPath, bool recursive) inline static
Definition at line 364 of file FileSystem.cs.
    {
        if (!recursive)
        {
            RemoveDirectoryInternal(fullPath, topLevel: true);
            return;
        }
        Interop.Kernel32.WIN32_FIND_DATA findData = default(Interop.Kernel32.WIN32_FIND_DATA);
        GetFindData(fullPath, isDirectory: true, ignoreAccessDenied: true, ref findData);
        if (IsNameSurrogateReparsePoint(ref findData))
        {
            RemoveDirectoryInternal(fullPath, topLevel: true);
            return;
        }
        fullPath = PathInternal.EnsureExtendedPrefix(fullPath);
        RemoveDirectoryRecursive(fullPath, ref findData, topLevel: true);
    }
References System.IO.PathInternal.EnsureExtendedPrefix(), System.IO.FileSystem.GetFindData(), System.IO.FileSystem.IsNameSurrogateReparsePoint(), System.IO.FileSystem.RemoveDirectoryInternal(), and System.IO.FileSystem.RemoveDirectoryRecursive().
Referenced by System.IO.DirectoryInfo.Delete(), System.IO.Directory.Delete(), and System.IO.Directory.Delete().