Terraria: System.IO.FileSystem.ResolveLinkTarget
ResolveLinkTarget()
static FileSystemInfo System.IO.FileSystem.ResolveLinkTarget (string linkPath, bool returnFinalTarget, bool isDirectory) inline static package
Definition at line 575 of file FileSystem.cs.
    {
        string text = (returnFinalTarget ? GetFinalLinkTarget(linkPath, isDirectory) : GetImmediateLinkTarget(linkPath, isDirectory, throwOnError: true, returnFullPath: true));
        if (text != null)
        {
            if (!isDirectory)
            {
                return new FileInfo(text);
            }
            return new DirectoryInfo(text);
        }
        return null;
    }
References System.IO.FileSystem.GetFinalLinkTarget(), System.IO.FileSystem.GetImmediateLinkTarget(), and System.text.
Referenced by System.IO.FileSystemInfo.ResolveLinkTarget(), System.IO.Directory.ResolveLinkTarget(), and System.IO.File.ResolveLinkTarget().