Terraria: System.IO.FileSystem.MoveFile
MoveFile()
static void System.IO.FileSystem.MoveFile (string sourceFullPath, string destFullPath, bool overwrite) inline static
Definition at line 336 of file FileSystem.cs.
    {
        if (!Interop.Kernel32.MoveFile(sourceFullPath, destFullPath, overwrite))
        {
            throw Win32Marshal.GetExceptionForLastWin32Error();
        }
    }
References System.IO.Win32Marshal.GetExceptionForLastWin32Error(), and Interop.Kernel32.MoveFile().
Referenced by System.IO.File.Move(), and System.IO.FileInfo.MoveTo().