Terraria: System.IO.FileSystem.FillAttributeInfo
FillAttributeInfo() [1/2]
static int System.IO.FileSystem.FillAttributeInfo (string path, ref global::Interop::Kernel32::WIN32_FILE_ATTRIBUTE_DATA data, bool returnErrorOnNotFound) inline static package
Definition at line 36 of file FileSystem.cs.
    {
        int num = 0;
        path = System.IO.PathInternal.TrimEndingDirectorySeparator(path);
        using (System.IO.DisableMediaInsertionPrompt.Create())
        {
            if (!global::Interop.Kernel32.GetFileAttributesEx(path, global::Interop.Kernel32.GET_FILEEX_INFO_LEVELS.GetFileExInfoStandard, ref data))
            {
                num = Marshal.GetLastWin32Error();
                if (!IsPathUnreachableError(num))
                {
                    global::Interop.Kernel32.WIN32_FIND_DATA data2 = default(global::Interop.Kernel32.WIN32_FIND_DATA);
                    using Microsoft.Win32.SafeHandles.SafeFindHandle safeFindHandle = global::Interop.Kernel32.FindFirstFile(path, ref data2);
                    if (safeFindHandle.IsInvalid)
                    {
                        num = Marshal.GetLastWin32Error();
                    }
                    else
                    {
                        num = 0;
                        data.PopulateFrom(ref data2);
                    }
                }
            }
        }
        if (num != 0 && !returnErrorOnNotFound && ((uint)(num - 2) <= 1u || num == 21))
        {
            data.dwFileAttributes = -1;
            return 0;
        }
        return num;
    }
References System.IO.DisableMediaInsertionPrompt.Create(), System.Runtime.InteropServices.Marshal.GetLastWin32Error(), System.IO.FileSystem.IsPathUnreachableError(), and System.IO.PathInternal.TrimEndingDirectorySeparator().
Referenced by System.IO.FileSystem.DirectoryExists(), System.IO.FileSystem.FileExists(), System.IO.FileSystem.GetAttributes(), System.IO.FileSystem.GetCreationTime(), System.IO.FileSystem.GetLastAccessTime(), System.IO.FileSystem.GetLastWriteTime(), and System.IO.FileSystemInfo.RefreshCore().