Terraria: System.IO.FileSystem.Decrypt
Decrypt()
static void System.IO.FileSystem.Decrypt (string path) inline static
Definition at line 196 of file FileSystem.cs.
    {
        string fullPath = Path.GetFullPath(path);
        if (!Interop.Advapi32.DecryptFile(fullPath))
        {
            ThrowExceptionEncryptDecryptFail(fullPath);
        }
    }
References Interop.Advapi32.DecryptFile(), System.IO.Path.GetFullPath(), and System.IO.FileSystem.ThrowExceptionEncryptDecryptFail().
Referenced by System.IO.File.Decrypt().