Terraria: System.IO.FileSystem.FillAttributeInfo
FillAttributeInfo() [2/2]
static int System.IO.FileSystem.FillAttributeInfo (string path, ref Interop::Kernel32::WIN32_FILE_ATTRIBUTE_DATA data, bool returnErrorOnNotFound) inline static package
Definition at line 53 of file FileSystem.cs.
    {
        int num = 0;
        path = PathInternal.TrimEndingDirectorySeparator(path);
        using (DisableMediaInsertionPrompt.Create())
        {
            if (!Interop.Kernel32.GetFileAttributesEx(path, Interop.Kernel32.GET_FILEEX_INFO_LEVELS.GetFileExInfoStandard, ref data))
            {
                num = Marshal.GetLastWin32Error();
                if (!IsPathUnreachableError(num))
                {
                    Interop.Kernel32.WIN32_FIND_DATA data2 = default(Interop.Kernel32.WIN32_FIND_DATA);
                    using SafeFindHandle safeFindHandle = Interop.Kernel32.FindFirstFile(path, ref data2);
                    if (safeFindHandle.IsInvalid)
                    {
                        num = Marshal.GetLastWin32Error();
                    }
                    else
                    {
                        num = 0;
                        data.PopulateFrom(ref data2);
                    }
                }
            }
        }
        if (num != 0 && !returnErrorOnNotFound && ((uint)(num - 2) <= 1u || num == 21))
        {
            data.dwFileAttributes = -1;
            return 0;
        }
        return num;
    }
References System.IO.DisableMediaInsertionPrompt.Create(), Interop.Kernel32.FindFirstFile(), Interop.Kernel32.GetFileAttributesEx(), System.Runtime.InteropServices.Marshal.GetLastWin32Error(), System.IO.FileSystem.IsPathUnreachableError(), and System.IO.PathInternal.TrimEndingDirectorySeparator().