Terraria: System.IO.FileSystem.ThrowExceptionEncryptDecryptFail
ThrowExceptionEncryptDecryptFail()
static unsafe void System.IO.FileSystem.ThrowExceptionEncryptDecryptFail (string fullPath) inline static private
Definition at line 205 of file FileSystem.cs.
    {
        int lastWin32Error = Marshal.GetLastWin32Error();
        if (lastWin32Error == 5)
        {
            string text = DriveInfoInternal.NormalizeDriveName(Path.GetPathRoot(fullPath));
            using (DisableMediaInsertionPrompt.Create())
            {
                if (!Interop.Kernel32.GetVolumeInformation(text, null, 0, null, null, out var fileSystemFlags, null, 0))
                {
                    lastWin32Error = Marshal.GetLastWin32Error();
                    throw Win32Marshal.GetExceptionForWin32Error(lastWin32Error, text);
                }
                if (((ulong)fileSystemFlags & 0x20000uL) == 0L)
                {
                    throw new NotSupportedException(SR.PlatformNotSupported_FileEncryption);
                }
            }
        }
        throw Win32Marshal.GetExceptionForWin32Error(lastWin32Error, fullPath);
    }
References System.IO.DisableMediaInsertionPrompt.Create(), System.IO.Win32Marshal.GetExceptionForWin32Error(), System.Runtime.InteropServices.Marshal.GetLastWin32Error(), System.IO.Path.GetPathRoot(), Interop.Kernel32.GetVolumeInformation(), System.L, System.IO.DriveInfoInternal.NormalizeDriveName(), System.SR.PlatformNotSupported_FileEncryption, and System.text.
Referenced by System.IO.FileSystem.Decrypt(), and System.IO.FileSystem.Encrypt().