Terraria: System.IO.FileSystem.GetFinalLinkTarget
GetFinalLinkTarget()
static string System.IO.FileSystem.GetFinalLinkTarget (string linkPath, bool isDirectory) inline static private
Definition at line 669 of file FileSystem.cs.
    {
        Interop.Kernel32.WIN32_FIND_DATA findData = default(Interop.Kernel32.WIN32_FIND_DATA);
        GetFindData(linkPath, isDirectory, ignoreAccessDenied: false, ref findData);
        if ((findData.dwFileAttributes & 0x400) == 0 || (findData.dwReserved0 != 2684354572u && findData.dwReserved0 != 2684354563u))
        {
            return null;
        }
        using (SafeFileHandle safeFileHandle = OpenSafeFileHandle(linkPath, 33554435))
        {
            if (safeFileHandle.IsInvalid)
            {
                int lastWin32Error = Marshal.GetLastWin32Error();
                if (IsPathUnreachableError(lastWin32Error))
                {
                    return GetFinalLinkTargetSlow(linkPath);
                }
                throw Win32Marshal.GetExceptionForWin32Error(lastWin32Error, linkPath);
            }
            char[] array = ArrayPool<char>.Shared.Rent(4096);
            try
            {
                uint num = GetFinalPathNameByHandle(safeFileHandle, array);
                if (num > array.Length)
                {
                    char[] array2 = array;
                    array = ArrayPool<char>.Shared.Rent((int)num);
                    ArrayPool<char>.Shared.Return(array2);
                    num = GetFinalPathNameByHandle(safeFileHandle, array);
                }
                if (num == 0)
                {
                    throw Win32Marshal.GetExceptionForLastWin32Error(linkPath);
                }
                int num2 = ((!PathInternal.IsExtended(linkPath.AsSpan())) ? 4 : 0);
                return new string(array, num2, (int)num - num2);
            }
            finally
            {
                ArrayPool<char>.Shared.Return(array);
            }
        }
        string GetFinalLinkTargetSlow(string linkPath)
        {
            string immediateLinkTarget = GetImmediateLinkTarget(linkPath, isDirectory, throwOnError: false, returnFullPath: true);
            string result = null;
            while (immediateLinkTarget != null)
            {
                result = immediateLinkTarget;
                immediateLinkTarget = GetImmediateLinkTarget(immediateLinkTarget, isDirectory, throwOnError: false, returnFullPath: true);
            }
            return result;
        }
        unsafe static uint GetFinalPathNameByHandle(SafeFileHandle handle, char[] buffer)
        {
            fixed (char* lpszFilePath = buffer)
            {
                return Interop.Kernel32.GetFinalPathNameByHandle(handle, lpszFilePath, (uint)buffer.Length, 0u);
            }
        }
    }
References System.array, System.buffer, System.IO.Win32Marshal.GetExceptionForLastWin32Error(), System.IO.Win32Marshal.GetExceptionForWin32Error(), Interop.Kernel32.GetFinalPathNameByHandle(), System.IO.FileSystem.GetFindData(), System.IO.FileSystem.GetImmediateLinkTarget(), System.Runtime.InteropServices.Marshal.GetLastWin32Error(), System.handle, System.IO.PathInternal.IsExtended(), System.IO.FileSystem.IsPathUnreachableError(), and System.IO.FileSystem.OpenSafeFileHandle().
Referenced by System.IO.FileSystem.ResolveLinkTarget().