Terraria: System.IO.FileSystem.OpenHandle
OpenHandle()
static SafeFileHandle System.IO.FileSystem.OpenHandle (string fullPath, bool asDirectory) inline static private
Definition at line 344 of file FileSystem.cs.
    {
        string text = fullPath.Substring(0, PathInternal.GetRootLength(fullPath.AsSpan()));
        if (text == fullPath && text[1] == Path.VolumeSeparatorChar)
        {
            throw new ArgumentException(SR.Arg_PathIsVolume, "path");
        }
        SafeFileHandle safeFileHandle = Interop.Kernel32.CreateFile(fullPath, 1073741824, FileShare.ReadWrite | FileShare.Delete, FileMode.Open, asDirectory ? 33554432 : 0);
        if (safeFileHandle.IsInvalid)
        {
            int num = Marshal.GetLastWin32Error();
            if (!asDirectory && num == 3 && fullPath.Equals(Directory.GetDirectoryRoot(fullPath)))
            {
                num = 5;
            }
            throw Win32Marshal.GetExceptionForWin32Error(num, fullPath);
        }
        return safeFileHandle;
    }
References System.SR.Arg_PathIsVolume, Interop.Kernel32.CreateFile(), System.IO.Directory.GetDirectoryRoot(), System.IO.Win32Marshal.GetExceptionForWin32Error(), System.Runtime.InteropServices.Marshal.GetLastWin32Error(), System.IO.PathInternal.GetRootLength(), System.text, and System.IO.Path.VolumeSeparatorChar.
Referenced by System.IO.FileSystem.SetFileTime().