Terraria: System.Data.SqlTypes.SqlBytes.SetLength
SetLength()
void System.Data.SqlTypes.SqlBytes.SetLength (long value) inline
Definition at line 183 of file SqlBytes.cs.
    {
        if (value < 0)
        {
            throw new ArgumentOutOfRangeException("value");
        }
        if (FStream())
        {
            _stream.SetLength(value);
            return;
        }
        if (_rgbBuf == null)
        {
            throw new SqlTypeException(System.SR.SqlMisc_NoBufferMessage);
        }
        if (value > _rgbBuf.Length)
        {
            throw new ArgumentOutOfRangeException("value");
        }
        if (IsNull)
        {
            _state = SqlBytesCharsState.Buffer;
        }
        _lCurLen = value;
    }
References System.Data.SqlTypes.SqlBytes._lCurLen, System.Data.SqlTypes.SqlBytes._rgbBuf, System.Data.SqlTypes.SqlBytes._state, System.Data.SqlTypes.SqlBytes._stream, System.Data.SqlTypes.SqlBytes.FStream(), System.Data.SqlTypes.SqlBytes.IsNull, System.IO.Stream.SetLength(), System.SR.SqlMisc_NoBufferMessage, and System.value.
Referenced by System.Data.SqlTypes.StreamOnSqlBytes.SetLength().