Terraria: System.Data.SqlTypes.SqlBytes.Read
Read()
long System.Data.SqlTypes.SqlBytes.Read (long offset, byte[] buffer, int offsetInBuffer, int count) inline
Definition at line 209 of file SqlBytes.cs.
    {
        if (IsNull)
        {
            throw new SqlNullValueException();
        }
        if (buffer == null)
        {
            throw new ArgumentNullException("buffer");
        }
        if (offset > Length || offset < 0)
        {
            throw new ArgumentOutOfRangeException("offset");
        }
        if (offsetInBuffer > buffer.Length || offsetInBuffer < 0)
        {
            throw new ArgumentOutOfRangeException("offsetInBuffer");
        }
        if (count < 0 || count > buffer.Length - offsetInBuffer)
        {
            throw new ArgumentOutOfRangeException("count");
        }
        if (count > Length - offset)
        {
            count = (int)(Length - offset);
        }
        if (count != 0)
        {
            SqlBytesCharsState state = _state;
            if (state == SqlBytesCharsState.Stream)
            {
                if (_stream.Position != offset)
                {
                    _stream.Seek(offset, SeekOrigin.Begin);
                }
                _stream.Read(buffer, offsetInBuffer, count);
            }
            else
            {
                Array.Copy(_rgbBuf, offset, buffer, offsetInBuffer, count);
            }
        }
        return count;
    }
References System.Data.SqlTypes.SqlBytes._rgbBuf, System.Data.SqlTypes.SqlBytes._state, System.Data.SqlTypes.SqlBytes._stream, System.buffer, System.Array.Copy(), System.count, System.Runtime.Serialization.Dictionary, System.Data.SqlTypes.SqlBytes.IsNull, System.Data.SqlTypes.SqlBytes.Length, System.offset, System.IO.Stream.Position, System.IO.Stream.Read(), System.IO.Stream.Seek(), and System.state.
Referenced by System.Data.SqlTypes.StreamOnSqlBytes.Read().