Terraria: System.Data.SqlTypes.SqlBytes.Write
Write()
void System.Data.SqlTypes.SqlBytes.Write (long offset, byte[] buffer, int offsetInBuffer, int count) inline
Definition at line 254 of file SqlBytes.cs.
    {
        if (FStream())
        {
            if (_stream.Position != offset)
            {
                _stream.Seek(offset, SeekOrigin.Begin);
            }
            _stream.Write(buffer, offsetInBuffer, count);
            return;
        }
        if (buffer == null)
        {
            throw new ArgumentNullException("buffer");
        }
        if (_rgbBuf == null)
        {
            throw new SqlTypeException(System.SR.SqlMisc_NoBufferMessage);
        }
        if (offset < 0)
        {
            throw new ArgumentOutOfRangeException("offset");
        }
        if (offset > _rgbBuf.Length)
        {
            throw new SqlTypeException(System.SR.SqlMisc_BufferInsufficientMessage);
        }
        if (offsetInBuffer < 0 || offsetInBuffer > buffer.Length)
        {
            throw new ArgumentOutOfRangeException("offsetInBuffer");
        }
        if (count < 0 || count > buffer.Length - offsetInBuffer)
        {
            throw new ArgumentOutOfRangeException("count");
        }
        if (count > _rgbBuf.Length - offset)
        {
            throw new SqlTypeException(System.SR.SqlMisc_BufferInsufficientMessage);
        }
        if (IsNull)
        {
            if (offset != 0L)
            {
                throw new SqlTypeException(System.SR.SqlMisc_WriteNonZeroOffsetOnNullMessage);
            }
            _lCurLen = 0L;
            _state = SqlBytesCharsState.Buffer;
        }
        else if (offset > _lCurLen)
        {
            throw new SqlTypeException(System.SR.SqlMisc_WriteOffsetLargerThanLenMessage);
        }
        if (count != 0)
        {
            Array.Copy(buffer, offsetInBuffer, _rgbBuf, offset, count);
            if (_lCurLen < offset + count)
            {
                _lCurLen = offset + count;
            }
        }
    }
References System.Data.SqlTypes.SqlBytes._lCurLen, System.Data.SqlTypes.SqlBytes._rgbBuf, System.Data.SqlTypes.SqlBytes._state, System.Data.SqlTypes.SqlBytes._stream, System.buffer, System.Array.Copy(), System.count, System.Runtime.Serialization.Dictionary, System.Data.SqlTypes.SqlBytes.FStream(), System.Data.SqlTypes.SqlBytes.IsNull, System.L, System.offset, System.IO.Stream.Position, System.IO.Stream.Seek(), System.SR.SqlMisc_BufferInsufficientMessage, System.SR.SqlMisc_NoBufferMessage, System.SR.SqlMisc_WriteNonZeroOffsetOnNullMessage, System.SR.SqlMisc_WriteOffsetLargerThanLenMessage, and System.IO.Stream.Write().
Referenced by System.Data.SqlTypes.StreamOnSqlBytes.Write().