Terraria: System.Data.SqlTypes.SqlBytes.ReadXml
ReadXml()
void IXmlSerializable. System.Data.SqlTypes.SqlBytes.ReadXml (XmlReader r) inline private
Implements System.Xml.Serialization.IXmlSerializable.
Definition at line 374 of file SqlBytes.cs.
    {
        byte[] buffer = null;
        string attribute = r.GetAttribute("nil", "http://www.w3.org/2001/XMLSchema-instance");
        if (attribute != null && XmlConvert.ToBoolean(attribute))
        {
            r.ReadElementString();
            SetNull();
        }
        else
        {
            string text = r.ReadElementString();
            if (text == null)
            {
                buffer = Array.Empty<byte>();
            }
            else
            {
                text = text.Trim();
                buffer = ((text.Length != 0) ? Convert.FromBase64String(text) : Array.Empty<byte>());
            }
        }
        SetBuffer(buffer);
    }
References System.buffer, System.Runtime.Serialization.Dictionary, System.Convert.FromBase64String(), System.Data.SqlTypes.SqlBytes.SetBuffer(), System.Data.SqlTypes.SqlBytes.SetNull(), System.text, and System.Xml.XmlConvert.ToBoolean().