Terraria: System.Xml.Xsl.Runtime.NavigatorConstructor.GetNavigator
GetNavigator() [2/2]
XPathNavigator System.Xml.Xsl.Runtime.NavigatorConstructor.GetNavigator (XmlEventCache events, XmlNameTable nameTable) inline
Definition at line 9 of file NavigatorConstructor.cs.
    {
        if (_cache == null)
        {
            XPathDocument xPathDocument = new XPathDocument(nameTable);
            XmlRawWriter xmlRawWriter = xPathDocument.LoadFromWriter(XPathDocument.LoadFlags.AtomizeNames | ((!events.HasRootNode) ? XPathDocument.LoadFlags.Fragment : XPathDocument.LoadFlags.None), events.BaseUri);
            events.EventsToWriter(xmlRawWriter);
            xmlRawWriter.Close();
            _cache = xPathDocument;
        }
        return ((XPathDocument)_cache).CreateNavigator();
    }
References System.Xml.Xsl.Runtime.NavigatorConstructor._cache, System.Xml.XmlEventCache.BaseUri, System.Xml.Dictionary, System.Xml.XmlEventCache.EventsToWriter(), and System.Xml.XmlEventCache.HasRootNode.
Referenced by System.Xml.Xsl.Runtime.RtfTextNavigator.ToNavigator(), and System.Xml.Xsl.Runtime.RtfTreeNavigator.ToNavigator().