Terraria: ReLogic.Utilities.SlotId.Invalid
Invalid
readonly SlotId ReLogic.Utilities.SlotId.Invalid = new SlotId(65535u) static
Referenced by Terraria.NPC.AI(), Terraria.Projectile.AI_001(), Terraria.NPC.AI_107_ImprovedWalkers(), Terraria.NPC.AI_108_DivingFlyer(), Terraria.NPC.AI_110_Betsy(), Terraria.Projectile.AI_143_MonkStaffT2Ghast(), Terraria.Projectile.AI_145_BookStaffStorm(), Terraria.Projectile.AI_177_IceWhipSlicer(), Terraria.Projectile.AI_187_ShadowHand(), ReLogic.Utilities.SlotVector< T >.GetPair(), Terraria.Audio.SoundPlayer.Play(), Terraria.Audio.SoundPlayer.Play(), Terraria.Audio.SoundPlayer.PlayLooped(), Terraria.Audio.SoundEngine.PlayTrackedLoopedSound(), Terraria.Audio.SoundEngine.PlayTrackedSound(), Terraria.Audio.SoundEngine.PlayTrackedSound(), and Terraria.Player.UpdateBiomes().