Terraria: ReLogic.Utilities.SlotId.FromFloat
FromFloat()
static SlotId ReLogic.Utilities.SlotId.FromFloat (float value) inline static
Definition at line 80 of file SlotId.cs.
    {
        return new SlotId(ReinterpretCast.FloatAsUInt(value));
    }
References ReLogic.Utilities.SlotId.SlotId(), and ReLogic.Utilities.ReinterpretCast.FloatAsUInt().
Referenced by Terraria.NPC.AI(), Terraria.Projectile.AI_001(), Terraria.NPC.AI_107_ImprovedWalkers(), Terraria.NPC.AI_108_DivingFlyer(), Terraria.NPC.AI_110_Betsy(), Terraria.Projectile.AI_143_MonkStaffT2Ghast(), Terraria.Projectile.AI_145_BookStaffStorm(), Terraria.Projectile.AI_177_IceWhipSlicer(), Terraria.Projectile.AI_187_ShadowHand(), Terraria.Projectile.AI_195_JimsDrone(), Terraria.NPC.HitEffect(), and Terraria.Projectile.Kill().