Terraria: SoundEngine.PlayTrackedSound
PlayTrackedSound() [2/2]
static SlotId SoundEngine.PlayTrackedSound (SoundStyle style, Vector2 position) inline static
     {
         //IL_000e: Unknown result type (might be due to invalid IL or missing references)
         //IL_001b: Unknown result type (might be due to invalid IL or missing references)
         if (Main.dedServ || !IsAudioSupported)
         {
             return SlotId.Invalid;
         }
         return SoundPlayer.Play(style, position);
     }
References Main.dedServ, SlotId.Invalid, IsAudioSupported, and SoundPlayer.Play().
Referenced by NPC.AI(), Projectile.AI_001(), NPC.AI_107_ImprovedWalkers(), NPC.AI_108_DivingFlyer(), NPC.AI_109_DarkMage(), NPC.AI_110_Betsy(), NPC.AI_111_DD2LightningBug(), Projectile.AI_131_FlameBurstShot(), Projectile.AI_134_Ballista(), Projectile.AI_137_LightningAura(), Projectile.AI_138_ExplosiveTrap(), Projectile.AI_140_MonkStaffT1(), Projectile.AI_143_MonkStaffT2Ghast(), Projectile.AI_145_BookStaffStorm(), Projectile.AI_177_IceWhipSlicer(), Projectile.AI_187_ShadowHand(), Projectile.Kill(), AchievementInitializer.OnAchievementCompleted(), and Player.UpdateBiomes().