Terraria: SoundEngine.Update
Update()
static void SoundEngine.Update () inline static
     {
         if (IsAudioSupported)
         {
             if (Main.audioSystem != null)
             {
                 Main.audioSystem.UpdateAudioEngine();
             }
             SoundInstanceGarbageCollector.Update();
             bool flag = (!Main.hasFocus || Main.gamePaused) && Main.netMode == 0;
             if (!AreSoundsPaused && flag)
             {
                 SoundPlayer.PauseAll();
             }
             else if (AreSoundsPaused && !flag)
             {
                 SoundPlayer.ResumeAll();
             }
             AreSoundsPaused = flag;
             SoundPlayer.Update();
         }
     }
References AreSoundsPaused, Main.audioSystem, Main.gamePaused, Main.hasFocus, IsAudioSupported, Main.netMode, SoundPlayer.PauseAll(), SoundPlayer.ResumeAll(), SoundInstanceGarbageCollector.Update(), SoundPlayer.Update(), and IAudioSystem.UpdateAudioEngine().
Referenced by Main.UpdateAudio().