Terraria: System.Runtime.InteropServices.GCHandle.FromIntPtr
FromIntPtr()
static GCHandle System.Runtime.InteropServices.GCHandle.FromIntPtr (IntPtr value) inline static
Definition at line 127 of file GCHandle.cs.
    {
        ThrowIfInvalid(value);
        return new GCHandle(value);
    }
References System.Runtime.InteropServices.GCHandle.GCHandle(), System.Runtime.InteropServices.GCHandle.ThrowIfInvalid(), and System.value.
Referenced by System.Net.NameResolutionPal.GetAddrInfoExState.FromHandleAndFree(), System.Runtime.Loader.AssemblyLoadContext.GetLoadContext(), System.Net.Quic.Implementations.MsQuic.MsQuicConnection.NativeCallbackHandler(), System.Net.Quic.Implementations.MsQuic.MsQuicListener.NativeCallbackHandler(), System.Net.Quic.Implementations.MsQuic.MsQuicStream.NativeCallbackHandler(), System.Net.NetworkInformation.TeredoHelper.OnStabilized(), System.Runtime.InteropServices.GCHandle.operator GCHandle(), System.Runtime.Loader.AssemblyLoadContext.Resolve(), System.Runtime.Loader.AssemblyLoadContext.ResolveSatelliteAssembly(), System.Runtime.Loader.AssemblyLoadContext.ResolveUnmanagedDll(), System.Runtime.Loader.AssemblyLoadContext.ResolveUnmanagedDllUsingEvent(), and System.Runtime.Loader.AssemblyLoadContext.ResolveUsingResolvingEvent().