Terraria: System.Random.CompatPrng.InternalSample
InternalSample()
int System.Random.CompatPrng.InternalSample () inline package
Definition at line 389 of file Random.cs.
        {
            int inext = _inext;
            if (++inext >= 56)
            {
                inext = 1;
            }
            int inextp = _inextp;
            if (++inextp >= 56)
            {
                inextp = 1;
            }
            int[] seedArray = _seedArray;
            int num = seedArray[inext] - seedArray[inextp];
            if (num == int.MaxValue)
            {
                num--;
            }
            if (num < 0)
            {
                num += int.MaxValue;
            }
            seedArray[inext] = num;
            _inext = inext;
            _inextp = inextp;
            return num;
        }
References System.Random.CompatPrng._inext, System.Random.CompatPrng._inextp, and System.Random.CompatPrng._seedArray.
Referenced by System.Random.CompatPrng.GetSampleForLargeRange(), System.Random.Net5CompatSeedImpl.Next(), System.Random.Net5CompatDerivedImpl.Next(), System.Random.CompatPrng.NextBytes(), and System.Random.CompatPrng.Sample().