Terraria: System.Runtime.InteropServices.GCHandle.GCHandle
GCHandle() [1/2]
System.Runtime.InteropServices.GCHandle.GCHandle (object value, GCHandleType type) inline private
Definition at line 51 of file GCHandle.cs.
    {
        switch (type)
        {
        default:
            throw new ArgumentOutOfRangeException("type", SR.ArgumentOutOfRange_Enum);
        case GCHandleType.Pinned:
            if (!Marshal.IsPinnable(value))
            {
                throw new ArgumentException(SR.ArgumentException_NotIsomorphic, "value");
            }
            break;
        case GCHandleType.Weak:
        case GCHandleType.WeakTrackResurrection:
        case GCHandleType.Normal:
            break;
        }
        nint num = InternalAlloc(value, type);
        if (type == GCHandleType.Pinned)
        {
            num |= 1;
        }
        _handle = num;
    }
References System.Runtime.InteropServices.GCHandle._handle, System.SR.ArgumentException_NotIsomorphic, System.SR.ArgumentOutOfRange_Enum, System.Runtime.InteropServices.GCHandle.InternalAlloc(), System.Runtime.InteropServices.Marshal.IsPinnable(), System.type, and System.value.
Referenced by System.Runtime.InteropServices.GCHandle.Alloc(), System.Runtime.InteropServices.GCHandle.Alloc(), System.Runtime.InteropServices.GCHandle.Equals(), and System.Runtime.InteropServices.GCHandle.FromIntPtr().