Terraria: System.Runtime.InteropServices.GCHandle.AddrOfPinnedObject
AddrOfPinnedObject()
unsafe IntPtr System.Runtime.InteropServices.GCHandle.AddrOfPinnedObject () inline
Definition at line 98 of file GCHandle.cs.
    {
        IntPtr handle = _handle;
        ThrowIfInvalid(handle);
        if (!IsPinned(handle))
        {
            ThrowHelper.ThrowInvalidOperationException_HandleIsNotPinned();
        }
        object obj = InternalGet(GetHandleValue(handle));
        if (obj == null)
        {
            return (IntPtr)0;
        }
        if (RuntimeHelpers.ObjectHasComponentSize(obj))
        {
            if (obj.GetType() == typeof(string))
            {
                return (IntPtr)Unsafe.AsPointer(ref Unsafe.As<string>(obj).GetRawStringData());
            }
            return (IntPtr)Unsafe.AsPointer(ref MemoryMarshal.GetArrayDataReference(Unsafe.As<Array>(obj)));
        }
        return (IntPtr)Unsafe.AsPointer(ref obj.GetRawData());
    }
References System.Runtime.InteropServices.GCHandle._handle, System.Runtime.InteropServices.MemoryMarshal.GetArrayDataReference(), System.Runtime.InteropServices.GCHandle.GetHandleValue(), System.handle, System.Runtime.InteropServices.GCHandle.InternalGet(), System.Runtime.InteropServices.GCHandle.IsPinned(), System.obj, System.Runtime.CompilerServices.RuntimeHelpers.ObjectHasComponentSize(), System.Runtime.InteropServices.GCHandle.ThrowIfInvalid(), and System.ThrowHelper.ThrowInvalidOperationException_HandleIsNotPinned().
Referenced by System.Net.WebSockets.WebSocketBuffer.CreateProperties(), System.Diagnostics.Tracing.DataCollector.PinArray(), Microsoft.Xna.Framework.Helpers.SmartGetHashCode(), and System.Security.Principal.SecurityIdentifier.TranslateToNTAccounts().