Terraria: System.Runtime.InteropServices.GCHandle.Alloc
Alloc() [1/2]
static GCHandle System.Runtime.InteropServices.GCHandle.Alloc (object? value) inline static
Definition at line 81 of file GCHandle.cs.
    {
        return new GCHandle(value, GCHandleType.Normal);
    }
References System.Runtime.InteropServices.GCHandle.GCHandle(), and System.value.
Referenced by System.Runtime.Loader.AssemblyLoadContext.AssemblyLoadContext(), System.Gen2GcCallback.Gen2GcCallback(), System.Net.Quic.Implementations.MsQuic.MsQuicConnection.MsQuicConnection(), System.Net.Quic.Implementations.MsQuic.MsQuicConnection.MsQuicConnection(), System.Net.Quic.Implementations.MsQuic.MsQuicListener.MsQuicListener(), System.Net.Quic.Implementations.MsQuic.MsQuicStream.MsQuicStream(), System.Net.Quic.Implementations.MsQuic.MsQuicStream.MsQuicStream(), System.IO.PinnedBufferMemoryStream.PinnedBufferMemoryStream(), System.Reflection.Internal.PinnedObject.PinnedObject(), System.Net.NetworkInformation.TeredoHelper.TeredoHelper(), System.Net.WebSockets.WebSocketBuffer.WebSocketBuffer(), System.Reflection.Metadata.Ecma335.VirtualHeap.AddBlob(), System.Security.Cryptography.CryptoStream.CopyToAsyncInternal(), System.Net.NameResolutionPal.GetAddrInfoExState.CreateHandle(), System.Net.TimerThread.TimerQueue.CreateTimer(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.DrawUserIndexedPrimitives< T >(), System.IO.Pipes.PipeStream.GetSecAttrs(), System.Runtime.Loader.AssemblyLoadContext.InitiateUnload(), System.Memory< T >.Pin(), System.ReadOnlyMemory< T >.Pin(), System.Diagnostics.Tracing.DataCollector.PinArray(), System.Net.WebSockets.WebSocketBuffer.PinSendBuffer(), System.Net.Sockets.SocketAsyncEventArgs.PinSocketAddressBuffer(), System.Net.Sockets.SocketPal.Receive(), System.Net.Sockets.SocketPal.Send(), System.Net.HttpListener.SendError(), System.Net.HttpListenerResponse.SerializeHeaders(), Microsoft.Xna.Framework.Helpers.SmartGetHashCode(), Internal.Cryptography.PinAndClear.Track(), System.Security.Principal.SecurityIdentifier.TranslateToNTAccounts(), System.Net.WebSockets.WebSocketHttpListenerDuplexStream.HttpListenerAsyncEventArgs.UpdateDataChunk(), and System.Diagnostics.Tracing.EventProvider.WriteEvent().