Terraria: System.Text.UTF7Encoding.GetCharCount
GetCharCount() [4/5]
unsafe override int System.Text.UTF7Encoding.GetCharCount (byte[] bytes, int index, int count) inline
Definition at line 369 of file UTF7Encoding.cs.
    {
        if (bytes == null)
        {
            throw new ArgumentNullException("bytes", SR.ArgumentNull_Array);
        }
        if (index < 0 || count < 0)
        {
            throw new ArgumentOutOfRangeException((index < 0) ? "index" : "count", SR.ArgumentOutOfRange_NeedNonNegNum);
        }
        if (bytes.Length - index < count)
        {
            throw new ArgumentOutOfRangeException("bytes", SR.ArgumentOutOfRange_IndexCountBuffer);
        }
        if (count == 0)
        {
            return 0;
        }
        fixed (byte* ptr = bytes)
        {
            return GetCharCount(ptr + index, count, null);
        }
    }
References System.SR.ArgumentNull_Array, System.SR.ArgumentOutOfRange_IndexCountBuffer, System.SR.ArgumentOutOfRange_NeedNonNegNum, System.bytes, System.count, System.Text.UTF7Encoding.GetCharCount(), and System.index.
Referenced by System.Text.UTF7Encoding.GetCharCount(), and System.Text.UTF7Encoding.GetCharCount().