Terraria: System.Text.UTF7Encoding.GetBytes
GetBytes() [2/9]
unsafe override int System.Text.UTF7Encoding.GetBytes (char * chars, int charCount, byte * bytes, int byteCount, EncoderNLS baseEncoder) inline sealed package virtual
Reimplemented from System.Text.Encoding.
Definition at line 482 of file UTF7Encoding.cs.
    {
        Encoder encoder = (Encoder)baseEncoder;
        int num = 0;
        int num2 = -1;
        EncodingByteBuffer encodingByteBuffer = new EncodingByteBuffer(this, encoder, bytes, byteCount, chars, charCount);
        if (encoder != null)
        {
            num = encoder.bits;
            num2 = encoder.bitCount;
            while (num2 >= 6)
            {
                num2 -= 6;
                if (!encodingByteBuffer.AddByte(_base64Bytes[(num >> num2) & 0x3F]))
                {
                    ThrowBytesOverflow(encoder, encodingByteBuffer.Count == 0);
                }
            }
        }
        while (encodingByteBuffer.MoreData)
        {
            char nextChar = encodingByteBuffer.GetNextChar();
            if (nextChar < '\u0080' && _directEncode[(uint)nextChar])
            {
                if (num2 >= 0)
                {
                    if (num2 > 0)
                    {
                        if (!encodingByteBuffer.AddByte(_base64Bytes[(num << 6 - num2) & 0x3F]))
{
                            break;
                        }
                        num2 = 0;
                    }
                    if (!encodingByteBuffer.AddByte(45))
                    {
                        break;
                    }
                    num2 = -1;
                }
                if (!encodingByteBuffer.AddByte((byte)nextChar))
                {
                    break;
                }
                continue;
            }
            if (num2 < 0 && nextChar == '+')
            {
                if (!encodingByteBuffer.AddByte((byte)43, (byte)45))
                {
                    break;
                }
                continue;
            }
            if (num2 < 0)
            {
                if (!encodingByteBuffer.AddByte(43))
                {
                    break;
                }
                num2 = 0;
            }
            num = (num << 16) | nextChar;
            num2 += 16;
            while (num2 >= 6)
            {
                num2 -= 6;
                if (!encodingByteBuffer.AddByte(_base64Bytes[(num >> num2) & 0x3F]))
                {
                    num2 += 6;
                    encodingByteBuffer.GetNextChar();
                    break;
                }
            }
            if (num2 >= 6)
            {
                break;
            }
        }
        if (num2 >= 0 && (encoder == null || encoder.MustFlush))
        {
            if (num2 > 0 && encodingByteBuffer.AddByte(_base64Bytes[(num << 6 - num2) & 0x3F]))
            {
                num2 = 0;
            }
            if (encodingByteBuffer.AddByte(45))
            {
                num = 0;
                num2 = -1;
            }
            else
            {
                encodingByteBuffer.GetNextChar();
            }
        }
        if (bytes != null && encoder != null)
        {
            encoder.bits = num;
            encoder.bitCount = num2;
            encoder._charsUsed = encodingByteBuffer.CharsUsed;
        }
        return encodingByteBuffer.Count;
    }
References System.Text.UTF7Encoding._base64Bytes, System.Text.UTF7Encoding._directEncode, System.Text.Encoding.EncodingByteBuffer.AddByte(), System.Text.UTF7Encoding.Encoder.bitCount, System.Text.UTF7Encoding.Encoder.bits, System.byteCount, System.bytes, System.charCount, System.chars, System.Text.Encoding.EncodingByteBuffer.CharsUsed, System.Text.Encoding.EncodingByteBuffer.Count, System.Text.Encoding.EncodingByteBuffer.GetNextChar(), System.Text.Encoding.EncodingByteBuffer.MoreData, System.Text.EncoderNLS.MustFlush, and System.Text.Encoding.ThrowBytesOverflow().