Terraria: System.Text.UTF7Encoding.GetChars
GetChars() [4/6]
unsafe override int System.Text.UTF7Encoding.GetChars (byte[] bytes, int byteIndex, int byteCount, char[] chars, int charIndex) inline
Definition at line 407 of file UTF7Encoding.cs.
    {
        if (bytes == null || chars == null)
        {
            throw new ArgumentNullException((bytes == null) ? "bytes" : "chars", SR.ArgumentNull_Array);
        }
        if (byteIndex < 0 || byteCount < 0)
        {
            throw new ArgumentOutOfRangeException((byteIndex < 0) ? "byteIndex" : "byteCount", SR.ArgumentOutOfRange_NeedNonNegNum);
        }
        if (bytes.Length - byteIndex < byteCount)
        {
            throw new ArgumentOutOfRangeException("bytes", SR.ArgumentOutOfRange_IndexCountBuffer);
        }
        if (charIndex < 0 || charIndex > chars.Length)
        {
            throw new ArgumentOutOfRangeException("charIndex", SR.ArgumentOutOfRange_Index);
        }
        if (byteCount == 0)
        {
            return 0;
        }
        int charCount = chars.Length - charIndex;
        fixed (byte* ptr = bytes)
        {
            fixed (char* ptr2 = &MemoryMarshal.GetReference<char>(chars))
            {
                return GetChars(ptr + byteIndex, byteCount, ptr2 + charIndex, charCount, null);
            }
        }
    }
References System.SR.ArgumentNull_Array, System.SR.ArgumentOutOfRange_Index, System.SR.ArgumentOutOfRange_IndexCountBuffer, System.SR.ArgumentOutOfRange_NeedNonNegNum, System.byteCount, System.byteIndex, System.bytes, System.charCount, System.charIndex, System.chars, and System.Text.UTF7Encoding.GetChars().
Referenced by System.Text.UTF7Encoding.GetCharCount(), System.Text.UTF7Encoding.GetChars(), and System.Text.UTF7Encoding.GetChars().