Terraria: System.DateTime.IsValidTimeWithLeapSeconds
IsValidTimeWithLeapSeconds()
static unsafe bool System.DateTime.IsValidTimeWithLeapSeconds (int year, int month, int day, int hour, int minute, DateTimeKind kind) inline static package
Definition at line 1487 of file DateTime.cs.
    {
        System.Runtime.CompilerServices.Unsafe.SkipInit(out Interop.Kernel32.SYSTEMTIME sYSTEMTIME);
        sYSTEMTIME.Year = (ushort)year;
        sYSTEMTIME.Month = (ushort)month;
        sYSTEMTIME.DayOfWeek = 0;
        sYSTEMTIME.Day = (ushort)day;
        sYSTEMTIME.Hour = (ushort)hour;
        sYSTEMTIME.Minute = (ushort)minute;
        sYSTEMTIME.Second = 60;
        sYSTEMTIME.Milliseconds = 0;
        System.Runtime.CompilerServices.Unsafe.SkipInit(out Interop.Kernel32.SYSTEMTIME sYSTEMTIME2);
        if (kind != DateTimeKind.Utc && Interop.Kernel32.TzSpecificLocalTimeToSystemTime(IntPtr.Zero, &sYSTEMTIME, &sYSTEMTIME2) != 0)
        {
            return true;
        }
        System.Runtime.CompilerServices.Unsafe.SkipInit(out ulong num);
        if (kind != DateTimeKind.Local && Interop.Kernel32.SystemTimeToFileTime(&sYSTEMTIME, &num) != 0)
        {
            return true;
        }
        return false;
    }
References System.Runtime.Serialization.Dictionary, Interop.Kernel32.SystemTimeToFileTime(), Interop.Kernel32.TzSpecificLocalTimeToSystemTime(), System.year, and System.IntPtr.Zero.
Referenced by System.DateTimeOffset.DateTimeOffset(), System.DateTimeOffset.DateTimeOffset(), System.DateTimeOffset.DateTimeOffset(), System.DateTime.TryCreate(), and System.DateTime.ValidateLeapSecond().