Terraria: System.DateTime.ThrowInvalidKind
ThrowInvalidKind()
static void System.DateTime.ThrowInvalidKind () inline static private
Definition at line 208 of file DateTime.cs.
    {
        throw new ArgumentException(SR.Argument_InvalidDateTimeKind, "kind");
    }
References System.SR.Argument_InvalidDateTimeKind.
Referenced by System.DateTime.DateTime(), System.DateTime.DateTime(), System.DateTime.DateTime(), System.DateTime.DateTime(), and System.DateTime.SpecifyKind().