Terraria: System.DateTime.TryCreate
TryCreate()
static bool System.DateTime.TryCreate (int year, int month, int day, int hour, int minute, int second, int millisecond, out DateTime result) inline static package
Definition at line 1365 of file DateTime.cs.
    {
        result = default(DateTime);
        if (year < 1 || year > 9999 || month < 1 || month > 12 || day < 1)
        {
            return false;
        }
        if ((uint)hour >= 24u || (uint)minute >= 60u || (uint)millisecond >= 1000u)
        {
            return false;
        }
        uint[] array = (IsLeapYear(year) ? s_daysToMonth366 : s_daysToMonth365);
        if ((uint)day > array[month] - array[month - 1])
        {
            return false;
        }
        ulong num = (ulong)(uint)((int)(DaysToYear((uint)year) + array[month - 1]) + day - 1) * 864000000000uL;
        if ((uint)second < 60u)
        {
            num += TimeToTicks(hour, minute, second) + (uint)(millisecond * 10000);
        }
        else
        {
            if (second != 60 || !s_systemSupportsLeapSeconds || !IsValidTimeWithLeapSeconds(year, month, day, hour, minute, DateTimeKind.Unspecified))
            {
                return false;
            }
            num += TimeToTicks(hour, minute, 59) + 9990000;
        }
        result = new DateTime(num);
        return true;
    }
References System.array, System.DateTime, System.DateTime.DaysToYear(), System.Runtime.Serialization.Dictionary, System.DateTime.IsLeapYear(), System.DateTime.IsValidTimeWithLeapSeconds(), System.DateTime.s_daysToMonth365, System.DateTime.s_daysToMonth366, System.DateTime.s_systemSupportsLeapSeconds, System.DateTime.TimeToTicks(), and System.year.
Referenced by System.DateTimeParse.ParseFormatO(), and System.Globalization.GregorianCalendar.TryToDateTime().