Terraria: System.DateTime.CreateDateTimeFromSystemTime
CreateDateTimeFromSystemTime()
static DateTime System.DateTime.CreateDateTimeFromSystemTime (in Interop::Kernel32::SYSTEMTIME time, ulong hundredNanoSecond) inline static private
Definition at line 1543 of file DateTime.cs.
    {
        uint year = time.Year;
        uint[] array = (IsLeapYear((int)year) ? s_daysToMonth366 : s_daysToMonth365);
        int num = time.Month - 1;
        uint num2 = DaysToYear(year) + array[num] + time.Day - 1;
        ulong num3 = (ulong)num2 * 864000000000uL;
        num3 += (ulong)(time.Hour * 36000000000L);
        num3 += (ulong)((long)time.Minute * 600000000L);
        uint second = time.Second;
        if (second <= 59)
        {
            ulong num4 = (uint)((int)(second * 10000000) + time.Milliseconds * 10000) + hundredNanoSecond;
            return new DateTime((num3 + num4) | 0x4000000000000000uL);
        }
        num3 += 4611686019027387903L;
        return new DateTime(num3);
    }
References System.array, System.DateTime, System.DateTime.DaysToYear(), System.Runtime.Serialization.Dictionary, System.DateTime.IsLeapYear(), System.L, System.DateTime.s_daysToMonth365, System.DateTime.s_daysToMonth366, and System.year.
Referenced by System.DateTime.FromFileTimeLeapSecondsAware(), and System.DateTime.UpdateLeapSecondCacheAndReturnUtcNow().