Terraria: System.DateTime.DateTime
DateTime() [10/14]
System.DateTime.DateTime (int year, int month, int day, int hour, int minute, int second, int millisecond) inline
Definition at line 282 of file DateTime.cs.
    {
        if ((uint)millisecond >= 1000u)
        {
            ThrowMillisecondOutOfRange();
        }
        if (second != 60 || !s_systemSupportsLeapSeconds)
        {
            ulong num = DateToTicks(year, month, day) + TimeToTicks(hour, minute, second);
            num += (uint)(millisecond * 10000);
            _dateData = num;
        }
        else
        {
            this = new DateTime(year, month, day, hour, minute, 59, millisecond);
            ValidateLeapSecond();
        }
    }
References System.DateTime._dateData, System.DateTime, System.DateTime.DateToTicks(), System.Runtime.Serialization.Dictionary, System.DateTime.s_systemSupportsLeapSeconds, System.DateTime.ThrowMillisecondOutOfRange(), System.DateTime.TimeToTicks(), System.DateTime.ValidateLeapSecond(), and System.year.