Terraria: System.DateTime.ToFileTimeUtc
ToFileTimeUtc()
long System.DateTime.ToFileTimeUtc () inline
Definition at line 1053 of file DateTime.cs.
    {
        long num = (((_dateData & 0x8000000000000000uL) != 0L) ? ToUniversalTime().Ticks : Ticks);
        if (s_systemSupportsLeapSeconds)
        {
            return (long)ToFileTimeLeapSecondsAware(num);
        }
        num -= 504911232000000000L;
        if (num < 0)
        {
            throw new ArgumentOutOfRangeException(null, SR.ArgumentOutOfRange_FileTimeInvalid);
        }
        return num;
    }
References System.DateTime._dateData, System.SR.ArgumentOutOfRange_FileTimeInvalid, System.Runtime.Serialization.Dictionary, System.L, System.DateTime.s_systemSupportsLeapSeconds, System.DateTime.Ticks, System.DateTime.ToFileTimeLeapSecondsAware(), and System.DateTime.ToUniversalTime().
Referenced by System.DateTime.ToFileTime(), and System.Diagnostics.Tracing.DateTimeTypeInfo.WriteData().