Terraria: System.DateTime.DateTime
DateTime() [7/14]
System.DateTime.DateTime (int year, int month, int day, int hour, int minute, int second) inline
Definition at line 238 of file DateTime.cs.
    {
        if (second != 60 || !s_systemSupportsLeapSeconds)
        {
            _dateData = DateToTicks(year, month, day) + TimeToTicks(hour, minute, second);
            return;
        }
        this = new DateTime(year, month, day, hour, minute, 59);
        ValidateLeapSecond();
    }
References System.DateTime._dateData, System.DateTime, System.DateTime.DateToTicks(), System.DateTime.s_systemSupportsLeapSeconds, System.DateTime.TimeToTicks(), System.DateTime.ValidateLeapSecond(), and System.year.