Terraria: System.DateTime.GetHashCode
GetHashCode()
override int System.DateTime.GetHashCode () inline
Definition at line 886 of file DateTime.cs.
    {
        long ticks = Ticks;
        return (int)ticks ^ (int)(ticks >> 32);
    }
References System.DateTime.Ticks.
Referenced by System.Data.SqlTypes.SqlDateTime.GetHashCode(), System.DateTimeOffset.GetHashCode(), and System.TimeZoneInfo.AdjustmentRule.GetHashCode().