Terraria: System.DateTime.FromFileTimeUtc
FromFileTimeUtc()
static DateTime System.DateTime.FromFileTimeUtc (long fileTime) inline static
Definition at line 718 of file DateTime.cs.
    {
        if ((ulong)fileTime > 2650467743999999999uL)
        {
            throw new ArgumentOutOfRangeException("fileTime", SR.ArgumentOutOfRange_FileTimeInvalid);
        }
        if (s_systemSupportsLeapSeconds)
        {
            return FromFileTimeLeapSecondsAware((ulong)fileTime);
        }
        ulong num = (ulong)(fileTime + 504911232000000000L);
        return new DateTime(num | 0x4000000000000000uL);
    }
References System.SR.ArgumentOutOfRange_FileTimeInvalid, System.DateTime, System.Runtime.Serialization.Dictionary, System.DateTime.FromFileTimeLeapSecondsAware(), System.L, and System.DateTime.s_systemSupportsLeapSeconds.
Referenced by System.Diagnostics.Tracing.EventPipeEventDispatcher.CommitDispatchConfiguration(), System.DateTime.FromFileTime(), System.DateTimeOffset.FromFileTime(), and Interop.LongFileTime.ToDateTimeOffset().