Terraria: System.DateTime.UpdateLeapSecondCacheAndReturnUtcNow
UpdateLeapSecondCacheAndReturnUtcNow()
static unsafe DateTime System.DateTime.UpdateLeapSecondCacheAndReturnUtcNow () inline static private
Definition at line 1584 of file DateTime.cs.
    {
        System.Runtime.CompilerServices.Unsafe.SkipInit(out ulong num);
        s_pfnGetSystemTimeAsFileTime(&num);
        ulong hundredNanoSecond = num % 10000;
        System.Runtime.CompilerServices.Unsafe.SkipInit(out Interop.Kernel32.SYSTEMTIME time);
        if (Interop.Kernel32.FileTimeToSystemTime(&num, &time) == Interop.BOOL.FALSE)
        {
            return LowGranularityNonCachedFallback();
        }
        if (time.Second >= 60)
        {
            return CreateDateTimeFromSystemTime(in time, hundredNanoSecond);
        }
        ulong num2 = num + 3000000000u;
        System.Runtime.CompilerServices.Unsafe.SkipInit(out Interop.Kernel32.SYSTEMTIME sYSTEMTIME);
        if (Interop.Kernel32.FileTimeToSystemTime(&num2, &sYSTEMTIME) == Interop.BOOL.FALSE)
        {
            return LowGranularityNonCachedFallback();
        }
        ulong num3;
        ulong num4;
        if (sYSTEMTIME.Second == time.Second)
        {
            num3 = num;
            num4 = CreateDateTimeFromSystemTime(in time, hundredNanoSecond)._dateData;
        }
        else
        {
            Interop.Kernel32.SYSTEMTIME time2 = time;
            time2.Hour = 0;
            time2.Minute = 0;
            time2.Second = 0;
            time2.Milliseconds = 0;
            System.Runtime.CompilerServices.Unsafe.SkipInit(out ulong num5);
            if (Interop.Kernel32.SystemTimeToFileTime(&time2, &num5) == Interop.BOOL.FALSE)
            {
                return LowGranularityNonCachedFallback();
            }
            num3 = num5 + 863990000000L - 3000000000u;
            if (num - num3 >= 3000000000u)
            {
                return CreateDateTimeFromSystemTime(in time, hundredNanoSecond);
            }
            num4 = CreateDateTimeFromSystemTime(in time2, 0uL)._dateData + 863990000000L - 3000000000u;
        }
        Volatile.Write(ref s_leapSecondCache, new LeapSecondCache
        {
            OSFileTimeTicksAtStartOfValidityWindow = num3,
            DotnetDateDataAtStartOfValidityWindow = num4
        });
        return new DateTime(num4 + num - num3);
        [MethodImpl(MethodImplOptions.NoInlining)]
        static unsafe DateTime LowGranularityNonCachedFallback()
        {
            System.Runtime.CompilerServices.Unsafe.SkipInit(out Interop.Kernel32.SYSTEMTIME time3);
            Interop.Kernel32.GetSystemTime(&time3);
            return CreateDateTimeFromSystemTime(in time3, 0uL);
        }
    }
References System.DateTime.CreateDateTimeFromSystemTime(), System.DateTime, System.Runtime.Serialization.Dictionary, Interop.Kernel32.FileTimeToSystemTime(), Interop.Kernel32.GetSystemTime(), System.L, System.DateTime.s_leapSecondCache, System.DateTime.s_pfnGetSystemTimeAsFileTime, Interop.Kernel32.SystemTimeToFileTime(), and System.Threading.Volatile.Write().