Terraria: System.DateTime.ValidateLeapSecond
ValidateLeapSecond()
void System.DateTime.ValidateLeapSecond () inline private
Definition at line 365 of file DateTime.cs.
    {
        if (!IsValidTimeWithLeapSeconds(Year, Month, Day, Hour, Minute, Kind))
        {
            ThrowHelper.ThrowArgumentOutOfRange_BadHourMinuteSecond();
        }
    }
References System.DateTime.Day, System.DateTime.Hour, System.DateTime.IsValidTimeWithLeapSeconds(), System.DateTime.Kind, System.DateTime.Minute, System.DateTime.Month, System.ThrowHelper.ThrowArgumentOutOfRange_BadHourMinuteSecond(), and System.DateTime.Year.
Referenced by System.DateTime.DateTime(), System.DateTime.DateTime(), System.DateTime.DateTime(), System.DateTime.DateTime(), System.DateTime.DateTime(), System.DateTime.DateTime(), and System.DateTime.DateTime().