Terraria: System.DateTime.SpecifyKind
SpecifyKind()
static DateTime System.DateTime.SpecifyKind (DateTime value, DateTimeKind kind) inline static
Definition at line 756 of file DateTime.cs.
    {
        if ((uint)kind > 2u)
        {
            ThrowInvalidKind();
        }
        return new DateTime(value.UTicks | (ulong)((long)kind << 62));
    }
References System.DateTime, System.Runtime.Serialization.Dictionary, System.DateTime.ThrowInvalidKind(), and System.value.
Referenced by System.Data.Common.ObjectStorage.CopyValue(), System.DateTimeParse.DetermineTimeZoneAdjustments(), System.IO.File.GetUtcDateTimeOffset(), System.Runtime.Serialization.Json.JsonReaderDelegator.ParseJsonDateInDefaultFormat(), System.Data.Common.DateTimeStorage.Set(), System.Data.Common.DateTimeStorage.SetStorage(), and System.Data.Common.ObjectStorage.SetStorage().