Terraria: System.DateTime.FromBinary
FromBinary()
static DateTime System.DateTime.FromBinary (long dateData) inline static
Definition at line 671 of file DateTime.cs.
    {
        if ((dateData & long.MinValue) != 0L)
        {
            long num = dateData & 0x3FFFFFFFFFFFFFFFL;
            if (num > 4611685154427387904L)
            {
                num -= 4611686018427387904L;
            }
            bool isAmbiguousLocalDst = false;
            long ticks;
            if (num < 0)
            {
                ticks = TimeZoneInfo.GetLocalUtcOffset(MinValue, TimeZoneInfoOptions.NoThrowOnInvalidTime).Ticks;
            }
            else if (num > 3155378975999999999L)
            {
                ticks = TimeZoneInfo.GetLocalUtcOffset(MaxValue, TimeZoneInfoOptions.NoThrowOnInvalidTime).Ticks;
            }
            else
            {
                DateTime time = new DateTime(num, DateTimeKind.Utc);
                ticks = TimeZoneInfo.GetUtcOffsetFromUtc(time, TimeZoneInfo.Local, out var _, out isAmbiguousLocalDst).Ticks;
            }
            num += ticks;
            if (num < 0)
            {
                num += 864000000000L;
            }
            if ((ulong)num > 3155378975999999999uL)
            {
                throw new ArgumentException(SR.Argument_DateTimeBadBinaryData, "dateData");
            }
            return new DateTime(num, DateTimeKind.Local, isAmbiguousLocalDst);
        }
        if ((ulong)(dateData & 0x3FFFFFFFFFFFFFFFL) > 3155378975999999999uL)
        {
            throw new ArgumentException(SR.Argument_DateTimeBadBinaryData, "dateData");
        }
        return new DateTime((ulong)dateData);
    }
References System.SR.Argument_DateTimeBadBinaryData, System.DateTime, System.Runtime.Serialization.Dictionary, System.TimeZoneInfo.GetLocalUtcOffset(), System.TimeZoneInfo.GetUtcOffsetFromUtc(), System.L, System.TimeZoneInfo.Local, System.DateTime.MaxValue, and System.DateTime.MinValue.
Referenced by System.Resources.ResourceReader._LoadObjectV2(), Terraria.IO.WorldFile.GetAllMetadata(), Terraria.IO.WorldFile.LoadHeader(), System.Xml.XmlBufferReader.ReadDateTime(), and System.Xml.XmlConverter.ToDateTime().