Terraria: System.DateTime.FromFileTimeLeapSecondsAware
FromFileTimeLeapSecondsAware()
static unsafe DateTime System.DateTime.FromFileTimeLeapSecondsAware (ulong fileTime) inline static private
Definition at line 1511 of file DateTime.cs.
    {
        System.Runtime.CompilerServices.Unsafe.SkipInit(out Interop.Kernel32.SYSTEMTIME time);
        if (Interop.Kernel32.FileTimeToSystemTime(&fileTime, &time) == Interop.BOOL.FALSE)
        {
            throw new ArgumentOutOfRangeException("fileTime", SR.ArgumentOutOfRange_DateTimeBadTicks);
        }
        return CreateDateTimeFromSystemTime(in time, fileTime % 10000);
    }
References System.SR.ArgumentOutOfRange_DateTimeBadTicks, System.DateTime.CreateDateTimeFromSystemTime(), System.Runtime.Serialization.Dictionary, and Interop.Kernel32.FileTimeToSystemTime().
Referenced by System.DateTime.FromFileTimeUtc().