Terraria: System.DateTime.InvalidCast
InvalidCast()
static Exception System.DateTime.InvalidCast (string to) inline static private
Definition at line 1350 of file DateTime.cs.
    {
        return new InvalidCastException(SR.Format(SR.InvalidCast_FromTo, "DateTime", to));
    }
References System.Runtime.Serialization.Dictionary, System.SR.Format(), and System.SR.InvalidCast_FromTo.
Referenced by System.DateTime.ToBoolean(), System.DateTime.ToByte(), System.DateTime.ToChar(), System.DateTime.ToDecimal(), System.DateTime.ToDouble(), System.DateTime.ToInt16(), System.DateTime.ToInt32(), System.DateTime.ToInt64(), System.DateTime.ToSByte(), System.DateTime.ToSingle(), System.DateTime.ToUInt16(), System.DateTime.ToUInt32(), and System.DateTime.ToUInt64().