Terraria: System.DateTime.ToUniversalTime
ToUniversalTime()
DateTime System.DateTime.ToUniversalTime () inline
Definition at line 1134 of file DateTime.cs.
    {
        return TimeZoneInfo.ConvertTimeToUtc(this, TimeZoneInfoOptions.NoThrowOnInvalidTime);
    }
References System.TimeZoneInfo.ConvertTimeToUtc().
Referenced by System.Net.Cache.HttpRequestCachePolicy.HttpRequestCachePolicy(), System.Net.Cache.HttpRequestCachePolicy.HttpRequestCachePolicy(), System.Data.Common.DateTimeStorage.CopyValue(), System.DateTime.ToFileTime(), and System.DateTime.ToFileTimeUtc().