Terraria: System.DateTime.MaxValue
MaxValue
readonly DateTime System.DateTime.MaxValue = new DateTime(3155378975999999999L, DateTimeKind.Unspecified) static
Definition at line 37 of file DateTime.cs.
Referenced by System.TimeZoneInfo.TimeZoneInfo(), System.Net.CookieContainer.AgeCookies(), System.Data.Common.DateTimeStorage.Aggregate(), System.TimeZoneInfo.ConvertToFromUtc(), System.TimeZoneInfo.ConvertUtcToTimeZone(), System.DateTime.FromBinary(), System.Data.SqlTypes.SqlDateTime.FromDateTime(), System.Globalization.CalendricalCalculationsHelper.GetGregorianYear(), System.TimeZoneInfo.GetIsDaylightSavingsFromUtc(), System.TimeZoneInfo.GetUtcOffsetFromUtc(), System.Xml.Schema.XsdDateTime.operator DateTime(), System.Net.CookieCollection.TimeStamp(), System.Diagnostics.Tracing.EventPipeEventDispatcher.TimeStampToDateTime(), System.TimeZoneInfo.TryCreateAdjustmentRules(), System.Xml.XmlConverter.TryParseDateTime(), System.TimeZoneInfo.AdjustmentRule.ValidateAdjustmentRule(), and System.Runtime.Serialization.Json.JsonWriterDelegator.WriteDateTimeInDefaultFormat().