Terraria: System.DateTime.DaysInMonth
DaysInMonth()
static int System.DateTime.DaysInMonth (int year, int month) inline static
Definition at line 624 of file DateTime.cs.
    {
        if (month < 1 || month > 12)
        {
            ThrowHelper.ThrowArgumentOutOfRange_Month(month);
        }
        return (IsLeapYear(year) ? DaysInMonth366 : DaysInMonth365)[month - 1];
    }
References System.DateTime.DaysInMonth365, System.DateTime.DaysInMonth366, System.Runtime.Serialization.Dictionary, System.DateTime.IsLeapYear(), System.ThrowHelper.ThrowArgumentOutOfRange_Month(), and System.year.
Referenced by System.Globalization.GregorianCalendar.GetDaysInMonth(), System.Xml.Schema.XsdDateTime.Parser.Parse(), System.Xml.Schema.XsdDateTime.Parser.ParseDate(), System.TimeZoneInfo.TransitionTimeToDateTime(), System.Text.Json.JsonHelpers.TryCreateDateTime(), and System.Buffers.Text.Utf8Parser.TryCreateDateTime().