Terraria: UIList.DrawSelf
DrawSelf()
override void UIList.DrawSelf (SpriteBatch spriteBatch) inline protected virtual
Reimplemented from UIElement.
     {
         if (_scrollbar != null)
         {
             _innerList.Top.Set(0f - _scrollbar.GetValue(), 0f);
         }
         Recalculate();
     }
References _innerList, _scrollbar, UIScrollbar.GetValue(), Recalculate(), StyleDimension.Set(), and UIElement.Top.