Terraria: UIList.UpdateScrollbar
UpdateScrollbar()
void UIList.UpdateScrollbar () inline private
     {
         if (_scrollbar != null)
         {
             float height = GetInnerDimensions().Height;
             _scrollbar.SetView(height, _innerListHeight);
         }
     }
References _innerListHeight, _scrollbar, UIElement.GetInnerDimensions(), CalculatedStyle.Height, and UIScrollbar.SetView().
Referenced by Recalculate(), SetScrollbar(), and UpdateOrder().