Terraria: UIList.UpdateOrder
UpdateOrder()
void UIList.UpdateOrder () inline
     {
         if (ManualSortMethod != null)
         {
             ManualSortMethod(_items);
         }
         else
         {
             _items.Sort(SortMethod);
         }
         UpdateScrollbar();
     }
References _items, ManualSortMethod, SortMethod(), and UpdateScrollbar().
Referenced by Add(), UIAchievementsMenu.OnActivate(), and Remove().