Terraria: Microsoft.Xna.Framework.Graphics.Viewport.Project
Project()
Vector3 Microsoft.Xna.Framework.Graphics.Viewport.Project (Vector3 source, Matrix projection, Matrix view, Matrix world) inline
Definition at line 162 of file Viewport.cs.
    {
        Matrix matrix = Matrix.Multiply(world, view);
        matrix = Matrix.Multiply(matrix, projection);
        Vector3 result = Vector3.Transform(source, matrix);
        float num = source.X * matrix.M14 + source.Y * matrix.M24 + source.Z * matrix.M34 + matrix.M44;
        if (!WithinEpsilon(num, 1f))
        {
            result /= num;
        }
        result.X = (result.X + 1f) * 0.5f * (float)Width + (float)X;
        result.Y = (0f - result.Y + 1f) * 0.5f * (float)Height + (float)Y;
        result.Z = result.Z * (MaxDepth - MinDepth) + MinDepth;
        return result;
    }
References Microsoft.Xna.Framework.Graphics.Viewport.Height, Microsoft.Xna.Framework.Matrix.M44, Microsoft.Xna.Framework.Graphics.Viewport.MaxDepth, Microsoft.Xna.Framework.Graphics.Viewport.MinDepth, Microsoft.Xna.Framework.Matrix.Multiply(), Microsoft.Xna.Framework.Vector3.Transform(), Microsoft.Xna.Framework.Graphics.Viewport.Width, Microsoft.Xna.Framework.Graphics.Viewport.WithinEpsilon(), Microsoft.Xna.Framework.Graphics.Viewport.X, and Microsoft.Xna.Framework.Graphics.Viewport.Y.