Terraria: System.Xml.HWStack.Push
Push()
object System.Xml.HWStack.Push () inline package
Definition at line 52 of file HWStack.cs.
    {
        if (_used == _size)
        {
            if (_limit <= _used)
            {
                throw new XmlException(System.SR.Xml_StackOverflow, string.Empty);
            }
            object[] array = new object[_size + _growthRate];
            if (_used > 0)
            {
                Array.Copy(_stack, array, _used);
            }
            _stack = array;
            _size += _growthRate;
        }
        return _stack[_used++];
    }
References System.Xml.HWStack._growthRate, System.Xml.HWStack._limit, System.Xml.HWStack._size, System.Xml.HWStack._stack, System.Xml.HWStack._used, System.array, System.Array.Copy(), System.SR.Xml_StackOverflow, and System.Xml.XmlException.
Referenced by System.Xml.Xsl.XsltOld.OutputScopeManager.OutputScopeManager(), System.Xml.Schema.XdrBuilder.Push(), System.Xml.Schema.XsdBuilder.Push(), System.Xml.Schema.DtdValidator.Push(), System.Xml.Schema.XdrValidator.Push(), System.Xml.Schema.XmlSchemaValidator.Push(), System.Xml.Schema.XsdValidator.Push(), System.Xml.Schema.XdrBuilder.PushGroupInfo(), System.Xml.Xsl.XsltOld.Processor.PushNewFrame(), and System.Xml.Xsl.XsltOld.OutputScopeManager.PushScope().