Terraria: System.Xml.HWStack.Pop
Pop()
object System.Xml.HWStack.Pop () inline package
Definition at line 71 of file HWStack.cs.
    {
        if (0 < _used)
        {
            _used--;
            return _stack[_used];
        }
        return null;
    }
References System.Xml.HWStack._stack, and System.Xml.HWStack._used.
Referenced by System.Xml.Xsl.XsltOld.Processor.Execute(), System.Xml.Xsl.XsltOld.Processor.GetVariableValue(), System.Xml.Schema.DtdValidator.Pop(), System.Xml.Schema.XdrBuilder.Pop(), System.Xml.Schema.XdrValidator.Pop(), System.Xml.Schema.XmlSchemaValidator.Pop(), System.Xml.Schema.XsdBuilder.Pop(), System.Xml.Schema.XsdValidator.Pop(), System.Xml.Xsl.XsltOld.Processor.PopDebuggerStack(), System.Xml.Schema.XdrBuilder.PopGroupInfo(), System.Xml.Xsl.XsltOld.OutputScopeManager.PopScope(), and System.Xml.Schema.XmlSchemaValidator.Reset().