Terraria: System.Xml.HWStack.AddToTop
AddToTop()
void System.Xml.HWStack.AddToTop (object o) inline package
Definition at line 90 of file HWStack.cs.
    {
        if (_used > 0)
        {
            _stack[_used - 1] = o;
        }
    }
References System.Xml.HWStack._stack, System.Xml.HWStack._used, and System.Xml.Dictionary.
Referenced by System.Xml.Xsl.XsltOld.OutputScopeManager.OutputScopeManager(), System.Xml.Schema.DtdValidator.Push(), System.Xml.Schema.XdrValidator.Push(), System.Xml.Schema.XmlSchemaValidator.Push(), System.Xml.Schema.XsdValidator.Push(), System.Xml.Xsl.XsltOld.Processor.PushNewFrame(), and System.Xml.Xsl.XsltOld.OutputScopeManager.PushScope().