Terraria: System.Xml.HWStack.Peek
Peek()
object System.Xml.HWStack.Peek () inline package
Definition at line 81 of file HWStack.cs.
    {
        if (_used <= 0)
        {
            return null;
        }
        return _stack[_used - 1];
    }
References System.Xml.HWStack._stack, and System.Xml.HWStack._used.
Referenced by System.Xml.Xsl.XsltOld.Processor.Execute(), System.Xml.Xsl.XsltOld.Processor.GetVariableValue(), System.Xml.Schema.DtdValidator.Pop(), System.Xml.Schema.XdrValidator.Pop(), System.Xml.Schema.XmlSchemaValidator.Pop(), System.Xml.Schema.XsdValidator.Pop(), and System.Xml.Xsl.XsltOld.Processor.PushNewFrame().