Terraria: System.Text.UTF8Encoding.GetChars
GetChars() [1/6]
unsafe override int System.Text.UTF8Encoding.GetChars (byte * bytes, int byteCount, char * chars, int charCount) inline virtual inherited
Reimplemented from System.Text.Encoding.
Definition at line 394 of file UTF8Encoding.cs.
    {
        if (bytes == null || chars == null)
        {
            ThrowHelper.ThrowArgumentNullException((bytes == null) ? ExceptionArgument.bytes : ExceptionArgument.chars, ExceptionResource.ArgumentNull_Array);
        }
        if ((byteCount | charCount) < 0)
        {
            ThrowHelper.ThrowArgumentOutOfRangeException((byteCount < 0) ? ExceptionArgument.byteCount : ExceptionArgument.charCount, ExceptionResource.ArgumentOutOfRange_NeedNonNegNum);
        }
        return GetCharsCommon(bytes, byteCount, chars, charCount);
    }
References System.byteCount, System.bytes, System.charCount, System.chars, System.Text.UTF8Encoding.GetCharsCommon(), System.ThrowHelper.ThrowArgumentNullException(), and System.ThrowHelper.ThrowArgumentOutOfRangeException().