Terraria: System.Text.UTF8Encoding.GetByteCountFast
GetByteCountFast()
unsafe override int System.Text.UTF8Encoding.GetByteCountFast (char * pChars, int charsLength, EncoderFallback fallback, out int charsConsumed) inline sealed protected virtual inherited
Reimplemented from System.Text.Encoding.
Definition at line 211 of file UTF8Encoding.cs.
    {
        long utf8CodeUnitCountAdjustment;
        int scalarCountAdjustment;
        char* pointerToFirstInvalidChar = Utf16Utility.GetPointerToFirstInvalidChar(pChars, charsLength, out utf8CodeUnitCountAdjustment, out scalarCountAdjustment);
        long num = (charsConsumed = (int)(pointerToFirstInvalidChar - pChars)) + utf8CodeUnitCountAdjustment;
        if ((ulong)num > 2147483647uL)
        {
            Encoding.ThrowConversionOverflow();
        }
        return (int)num;
    }
References System.Text.Unicode.Utf16Utility.GetPointerToFirstInvalidChar(), and System.Text.Encoding.ThrowConversionOverflow().
Referenced by System.Text.UTF8Encoding.GetByteCountCommon().