Terraria: System.Text.UTF8Encoding.GetCharCount
GetCharCount() [4/5]
unsafe override int System.Text.UTF8Encoding.GetCharCount (byte[] bytes, int index, int count) inline inherited
Definition at line 324 of file UTF8Encoding.cs.
    {
        if (bytes == null)
        {
            ThrowHelper.ThrowArgumentNullException(ExceptionArgument.bytes, ExceptionResource.ArgumentNull_Array);
        }
        if ((index | count) < 0)
        {
            ThrowHelper.ThrowArgumentOutOfRangeException((index < 0) ? ExceptionArgument.index : ExceptionArgument.count, ExceptionResource.ArgumentOutOfRange_NeedNonNegNum);
        }
        if (bytes.Length - index < count)
        {
            ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument.bytes, ExceptionResource.ArgumentOutOfRange_IndexCountBuffer);
        }
        fixed (byte* ptr = bytes)
        {
            return GetCharCountCommon(ptr + index, count);
        }
    }
References System.bytes, System.count, System.Text.UTF8Encoding.GetCharCountCommon(), System.index, System.ThrowHelper.ThrowArgumentNullException(), and System.ThrowHelper.ThrowArgumentOutOfRangeException().