Terraria: System.Text.UTF8Encoding.GetBytes
GetBytes() [8/9]
unsafe override int System.Text.UTF8Encoding.GetBytes (string s, int charIndex, int charCount, byte[] bytes, int byteIndex) inline virtual inherited
Reimplemented from System.Text.Encoding.
Definition at line 224 of file UTF8Encoding.cs.
    {
        if (s == null || bytes == null)
        {
            ThrowHelper.ThrowArgumentNullException((s == null) ? ExceptionArgument.s : ExceptionArgument.bytes, ExceptionResource.ArgumentNull_Array);
        }
        if ((charIndex | charCount) < 0)
        {
            ThrowHelper.ThrowArgumentOutOfRangeException((charIndex < 0) ? ExceptionArgument.charIndex : ExceptionArgument.charCount, ExceptionResource.ArgumentOutOfRange_NeedNonNegNum);
        }
        if (s.Length - charIndex < charCount)
        {
            ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument.s, ExceptionResource.ArgumentOutOfRange_IndexCount);
        }
        if ((uint)byteIndex > bytes.Length)
        {
            ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument.byteIndex, ExceptionResource.ArgumentOutOfRange_Index);
        }
        fixed (char* ptr2 = s)
        {
            fixed (byte[] array = bytes)
            {
                byte* ptr = (byte*)((bytes != null && array.Length != 0) ? System.Runtime.CompilerServices.Unsafe.AsPointer(ref array[0]) : null);
                return GetBytesCommon(ptr2 + charIndex, charCount, ptr + byteIndex, bytes.Length - byteIndex);
            }
        }
    }
References System.array, System.byteIndex, System.bytes, System.charCount, System.charIndex, System.Text.UTF8Encoding.GetBytesCommon(), System.s, System.ThrowHelper.ThrowArgumentNullException(), and System.ThrowHelper.ThrowArgumentOutOfRangeException().
Referenced by Terraria.IO.FavoritesFile.Save(), and System.Xml.XmlConverter.ToBytes().