Terraria: System.Text.UTF8Encoding.GetBytesCommon
GetBytesCommon()
unsafe int System.Text.UTF8Encoding.GetBytesCommon (char * pChars, int charCount, byte * pBytes, int byteCount) inline private inherited
Definition at line 305 of file UTF8Encoding.cs.
    {
        int charsConsumed;
        int bytesFast = GetBytesFast(pChars, charCount, pBytes, byteCount, out charsConsumed);
        if (charsConsumed == charCount)
        {
            return bytesFast;
        }
        return GetBytesWithFallback(pChars, charCount, pBytes, byteCount, charsConsumed, bytesFast);
    }
References System.byteCount, System.charCount, System.Text.UTF8Encoding.GetBytesFast(), and System.Text.Encoding.GetBytesWithFallback().
Referenced by System.Text.UTF8Encoding.GetBytes(), System.Text.UTF8Encoding.GetBytes(), System.Text.UTF8Encoding.GetBytes(), System.Text.UTF8Encoding.GetBytes(), and System.Text.UTF8Encoding.UTF8EncodingSealed.GetBytesForSmallInput().