Terraria: System.Text.UTF8Encoding.GetCharCountCommon
GetCharCountCommon()
unsafe int System.Text.UTF8Encoding.GetCharCountCommon (byte * pBytes, int byteCount) inline private inherited
Definition at line 478 of file UTF8Encoding.cs.
    {
        int bytesConsumed;
        int num = GetCharCountFast(pBytes, byteCount, null, out bytesConsumed);
        if (bytesConsumed != byteCount)
        {
            num += GetCharCountWithFallback(pBytes, byteCount, bytesConsumed);
            if (num < 0)
            {
                Encoding.ThrowConversionOverflow();
            }
        }
        return num;
    }
References System.byteCount, System.Text.UTF8Encoding.GetCharCountFast(), System.Text.Encoding.GetCharCountWithFallback(), and System.Text.Encoding.ThrowConversionOverflow().
Referenced by System.Text.UTF8Encoding.GetCharCount(), System.Text.UTF8Encoding.GetCharCount(), and System.Text.UTF8Encoding.GetCharCount().