Terraria: System.Text.UTF8Encoding.GetByteCountCommon
GetByteCountCommon()
unsafe int System.Text.UTF8Encoding.GetByteCountCommon (char * pChars, int charCount) inline private inherited
Definition at line 195 of file UTF8Encoding.cs.
    {
        int charsConsumed;
        int num = GetByteCountFast(pChars, charCount, null, out charsConsumed);
        if (charsConsumed != charCount)
        {
            num += GetByteCountWithFallback(pChars, charCount, charsConsumed);
            if (num < 0)
            {
                Encoding.ThrowConversionOverflow();
            }
        }
        return num;
    }
References System.charCount, System.Text.UTF8Encoding.GetByteCountFast(), System.Text.Encoding.GetByteCountWithFallback(), and System.Text.Encoding.ThrowConversionOverflow().
Referenced by System.Text.UTF8Encoding.GetByteCount(), System.Text.UTF8Encoding.GetByteCount(), System.Text.UTF8Encoding.GetByteCount(), and System.Text.UTF8Encoding.GetByteCount().