Terraria: System.Text.UTF8Encoding.GetChars
GetChars() [4/6]
unsafe override int System.Text.UTF8Encoding.GetChars (byte[] bytes, int byteIndex, int byteCount, char[] chars, int charIndex) inline inherited
Definition at line 366 of file UTF8Encoding.cs.
    {
        if (bytes == null || chars == null)
        {
            ThrowHelper.ThrowArgumentNullException((bytes == null) ? ExceptionArgument.bytes : ExceptionArgument.chars, ExceptionResource.ArgumentNull_Array);
        }
        if ((byteIndex | byteCount) < 0)
        {
            ThrowHelper.ThrowArgumentOutOfRangeException((byteIndex < 0) ? ExceptionArgument.byteIndex : ExceptionArgument.byteCount, ExceptionResource.ArgumentOutOfRange_NeedNonNegNum);
        }
        if (bytes.Length - byteIndex < byteCount)
        {
            ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument.bytes, ExceptionResource.ArgumentOutOfRange_IndexCountBuffer);
        }
        if ((uint)charIndex > (uint)chars.Length)
        {
            ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument.charIndex, ExceptionResource.ArgumentOutOfRange_Index);
        }
        fixed (byte* ptr = bytes)
        {
            fixed (char* ptr2 = chars)
            {
                return GetCharsCommon(ptr + byteIndex, byteCount, ptr2 + charIndex, chars.Length - charIndex);
            }
        }
    }
References System.byteCount, System.byteIndex, System.bytes, System.charIndex, System.chars, System.Text.UTF8Encoding.GetCharsCommon(), System.ThrowHelper.ThrowArgumentNullException(), and System.ThrowHelper.ThrowArgumentOutOfRangeException().
Referenced by System.Xml.XmlConverter.ToChars().