Terraria: AmbientSky.PixiePosseSkyEntity.PixiePosseSkyEntity
PixiePosseSkyEntity()
AmbientSky.PixiePosseSkyEntity.PixiePosseSkyEntity (Player player, FastRandom random) inline
         {
             VirtualCamera virtualCamera = new VirtualCamera(player);
             Effects = ((!(Main.WindForVisuals > 0f)) ? SpriteEffects.FlipHorizontally : SpriteEffects.None);
             int num = 100;
             if (Effects == SpriteEffects.FlipHorizontally)
             {
                 Position.X = virtualCamera.Position.X + virtualCamera.Size.X + (float)num;
             }
             else
             {
                 Position.X = virtualCamera.Position.X - (float)num;
             }
             Position.Y = random.NextFloat() * ((float)Main.worldSurface * 16f - 4000f) + 4000f;
             Depth = random.NextFloat() * 3f + 2f;
             SetPositionInWorldBasedOnScreenSpace(Position);
             if (!Main.dayTime)
             {
                 pixieType = 2;
             }
             Texture = Main.Assets.Request<Texture2D>("Images/Backgrounds/Ambience/PixiePosse" + pixieType, (AssetRequestMode)1);
             Frame = new SpriteFrame(1, 25);
             LifeTime = random.Next(60, 121) * 60;
             OpacityNormalizedTimeToFadeIn = 0.15f;
             OpacityNormalizedTimeToFadeOut = 0.85f;
             BrightnessLerper = 0.6f;
             FinalOpacityMultiplier = 1f;
             FramingSpeed = 5;
         }
References Main.Assets, AmbientSky.FadingSkyEntity.BrightnessLerper, Main.dayTime, AmbientSky.SkyEntity.Depth, AmbientSky.SkyEntity.Effects, AmbientSky.FadingSkyEntity.FinalOpacityMultiplier, AmbientSky.SkyEntity.Frame, AmbientSky.FadingSkyEntity.FramingSpeed, AmbientSky.FadingSkyEntity.LifeTime, FastRandom.Next(), FastRandom.NextFloat(), AmbientSky.FadingSkyEntity.OpacityNormalizedTimeToFadeIn, AmbientSky.FadingSkyEntity.OpacityNormalizedTimeToFadeOut, AmbientSky.PixiePosseSkyEntity.pixieType, AmbientSky.SkyEntity.Position, VirtualCamera.Position, AmbientSky.SkyEntity.SetPositionInWorldBasedOnScreenSpace(), VirtualCamera.Size, AmbientSky.SkyEntity.Texture, Main.WindForVisuals, and Main.worldSurface.