Terraria: System.Runtime.Serialization.XmlObjectSerializerReadContext.ReplaceDeserializedObject
ReplaceDeserializedObject()
void System.Runtime.Serialization.XmlObjectSerializerReadContext.ReplaceDeserializedObject (string id, object oldObj, object newObj) inline inherited
Definition at line 359 of file XmlObjectSerializerReadContext.cs.
    {
        if (oldObj != newObj && id != Globals.NewObjectId)
        {
            if (DeserializedObjects.IsObjectReferenced(id))
            {
                string p = ((oldObj != null) ? DataContract.GetClrTypeFullName(oldObj.GetType()) : System.SR.UnknownNullType);
                string p2 = ((newObj != null) ? DataContract.GetClrTypeFullName(newObj.GetType()) : System.SR.UnknownNullType);
                throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(XmlObjectSerializer.CreateSerializationException(System.SR.Format(System.SR.FactoryObjectContainsSelfReference, p, p2, id)));
            }
            DeserializedObjects.Remove(id);
            DeserializedObjects.Add(id, newObj);
        }
    }
References System.Runtime.Serialization.HybridObjectCache.Add(), System.Runtime.Serialization.XmlObjectSerializer.CreateSerializationException(), System.Runtime.Serialization.XmlObjectSerializerReadContext.DeserializedObjects, System.SR.FactoryObjectContainsSelfReference, System.SR.Format(), System.Runtime.Serialization.DataContract.GetClrTypeFullName(), System.Runtime.Serialization.HybridObjectCache.IsObjectReferenced(), System.Runtime.Serialization.Globals.NewObjectId, System.Runtime.Serialization.HybridObjectCache.Remove(), System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperError(), and System.SR.UnknownNullType.
Referenced by System.Runtime.Serialization.XmlObjectSerializerReadContext.GetRealObject(), System.Runtime.Serialization.XmlObjectSerializerReadContextComplex.InternalDeserializeWithSurrogate(), and System.Runtime.Serialization.SurrogateDataContract.ReadXmlValue().