Terraria: System.Runtime.Serialization.XmlObjectSerializerReadContext.ReadUnknownCollectionData
ReadUnknownCollectionData()
CollectionDataNode System.Runtime.Serialization.XmlObjectSerializerReadContext.ReadUnknownCollectionData (XmlReaderDelegator xmlReader, string dataContractName, string dataContractNamespace) inline private inherited
Definition at line 779 of file XmlObjectSerializerReadContext.cs.
    {
        CollectionDataNode collectionDataNode = new CollectionDataNode();
        InitializeExtensionDataNode(collectionDataNode, dataContractName, dataContractNamespace);
        int arraySZSize = attributes.ArraySZSize;
        XmlNodeType xmlNodeType;
        while ((xmlNodeType = xmlReader.MoveToContent()) != XmlNodeType.EndElement)
        {
            if (xmlNodeType != XmlNodeType.Element)
            {
                throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(CreateUnexpectedStateException(XmlNodeType.Element, xmlReader));
            }
            if (collectionDataNode.ItemName == null)
            {
                collectionDataNode.ItemName = xmlReader.LocalName;
                collectionDataNode.ItemNamespace = xmlReader.NamespaceURI;
            }
            if (xmlReader.IsStartElement(collectionDataNode.ItemName, collectionDataNode.ItemNamespace))
            {
                if (collectionDataNode.Items == null)
                {
                    collectionDataNode.Items = new List<IDataNode>();
                }
                collectionDataNode.Items.Add(ReadExtensionDataValue(xmlReader));
            }
            else
            {
                SkipUnknownElement(xmlReader);
            }
        }
        xmlReader.ReadEndElement();
        if (arraySZSize != -1)
        {
            collectionDataNode.Size = arraySZSize;
            if (collectionDataNode.Items == null)
            {
                if (collectionDataNode.Size > 0)
                {
                    throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(XmlObjectSerializer.CreateSerializationException(System.SR.Format(System.SR.ArraySizeAttributeIncorrect, arraySZSize, 0)));
                }
            }
            else if (collectionDataNode.Size != collectionDataNode.Items.Count)
            {
                throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(XmlObjectSerializer.CreateSerializationException(System.SR.Format(System.SR.ArraySizeAttributeIncorrect, arraySZSize, collectionDataNode.Items.Count)));
            }
        }
        else if (collectionDataNode.Items != null)
        {
            collectionDataNode.Size = collectionDataNode.Items.Count;
        }
        else
        {
            collectionDataNode.Size = 0;
        }
        return collectionDataNode;
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.SR.ArraySizeAttributeIncorrect, System.Runtime.Serialization.Attributes.ArraySZSize, System.Runtime.Serialization.XmlObjectSerializerReadContext.attributes, System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Runtime.Serialization.XmlObjectSerializer.CreateSerializationException(), System.Runtime.Serialization.XmlObjectSerializerReadContext.CreateUnexpectedStateException(), System.Runtime.Serialization.Dictionary, System.SR.Format(), System.Runtime.Serialization.XmlObjectSerializerReadContext.InitializeExtensionDataNode(), System.Runtime.Serialization.XmlObjectSerializerReadContext.ReadExtensionDataValue(), System.Runtime.Serialization.XmlObjectSerializerReadContext.SkipUnknownElement(), and System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperError().
Referenced by System.Runtime.Serialization.XmlObjectSerializerReadContext.ReadAndResolveUnknownXmlData(), and System.Runtime.Serialization.XmlObjectSerializerReadContext.ReadExtensionDataValue().