Terraria: System.Runtime.Serialization.XmlObjectSerializerReadContext.AddNewObject
AddNewObject()
void System.Runtime.Serialization.XmlObjectSerializerReadContext.AddNewObject (object obj) inline package inherited
Definition at line 346 of file XmlObjectSerializerReadContext.cs.
    {
        AddNewObjectWithId(attributes.Id, obj);
    }
References System.Runtime.Serialization.XmlObjectSerializerReadContext.AddNewObjectWithId(), System.Runtime.Serialization.XmlObjectSerializerReadContext.attributes, System.Runtime.Serialization.Attributes.Id, and System.obj.
Referenced by System.Runtime.Serialization.Json.JsonDataContract.HandleReadValue(), System.Runtime.Serialization.PrimitiveDataContract.HandleReadValue(), System.Runtime.Serialization.XmlObjectSerializerReadContext.InitializeExtensionDataNode(), System.Runtime.Serialization.Json.JsonEnumDataContract.ReadJsonValueCore(), System.Runtime.Serialization.Json.JsonObjectDataContract.ReadJsonValueCore(), System.Runtime.Serialization.Json.JsonXmlDataContract.ReadJsonValueCore(), System.Runtime.Serialization.EnumDataContract.ReadXmlValue(), System.Runtime.Serialization.SurrogateDataContract.ReadXmlValue(), System.Runtime.Serialization.XmlDataContract.ReadXmlValue(), System.Runtime.Serialization.ReflectionReader.ReflectionReadClass(), and System.Runtime.Serialization.ReflectionReader.ReflectionReadCollectionCore().