Terraria: System.Runtime.Serialization.XmlObjectSerializerReadContext.TryHandleNullOrRef
TryHandleNullOrRef()
bool System.Runtime.Serialization.XmlObjectSerializerReadContext.TryHandleNullOrRef (XmlReaderDelegator reader, Type declaredType, string name, string ns, ref object retObj) inline protected inherited
Definition at line 124 of file XmlObjectSerializerReadContext.cs.
    {
        ReadAttributes(reader);
        if (attributes.Ref != Globals.NewObjectId)
        {
            if (_isGetOnlyCollection)
            {
                throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(XmlObjectSerializer.CreateSerializationException(System.SR.Format(System.SR.ErrorDeserializing, System.SR.Format(System.SR.ErrorTypeInfo, DataContract.GetClrTypeFullName(declaredType)), System.SR.Format(System.SR.XmlStartElementExpected, "Ref"))));
            }
            retObj = GetExistingObject(attributes.Ref, declaredType, name, ns);
            reader.Skip();
            return true;
        }
        if (attributes.XsiNil)
        {
            reader.Skip();
            return true;
        }
        return false;
    }
References System.Runtime.Serialization.XmlObjectSerializerReadContext._isGetOnlyCollection, System.Runtime.Serialization.XmlObjectSerializerReadContext.attributes, System.Runtime.Serialization.XmlObjectSerializer.CreateSerializationException(), System.SR.ErrorDeserializing, System.SR.ErrorTypeInfo, System.SR.Format(), System.Runtime.Serialization.DataContract.GetClrTypeFullName(), System.Runtime.Serialization.XmlObjectSerializerReadContext.GetExistingObject(), System.Runtime.Serialization.Globals.NewObjectId, System.Runtime.Serialization.XmlObjectSerializerReadContext.ReadAttributes(), System.Runtime.Serialization.Attributes.Ref, System.Runtime.Serialization.XmlReaderDelegator.Skip(), System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperError(), System.SR.XmlStartElementExpected, and System.Runtime.Serialization.Attributes.XsiNil.
Referenced by System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(), and System.Runtime.Serialization.XmlObjectSerializerReadContextComplex.InternalDeserializeInSharedTypeMode().