Terraria: System.Runtime.Serialization.XmlObjectSerializerReadContext.ReadSerializationInfo
ReadSerializationInfo()
SerializationInfo System.Runtime.Serialization.XmlObjectSerializerReadContext.ReadSerializationInfo (XmlReaderDelegator xmlReader, Type type) inline inherited
Definition at line 523 of file XmlObjectSerializerReadContext.cs.
    {
        SerializationInfo serializationInfo = new SerializationInfo(type, XmlObjectSerializer.FormatterConverter);
        XmlNodeType xmlNodeType;
        while ((xmlNodeType = xmlReader.MoveToContent()) != XmlNodeType.EndElement)
        {
            if (xmlNodeType != XmlNodeType.Element)
            {
                throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(CreateUnexpectedStateException(XmlNodeType.Element, xmlReader));
            }
            if (xmlReader.NamespaceURI.Length != 0)
            {
                SkipUnknownElement(xmlReader);
                continue;
            }
            string name = XmlConvert.DecodeName(xmlReader.LocalName);
            IncrementItemCount(1);
            ReadAttributes(xmlReader);
            object value;
            if (attributes.Ref != Globals.NewObjectId)
            {
                xmlReader.Skip();
                value = GetExistingObject(attributes.Ref, null, name, string.Empty);
            }
            else if (attributes.XsiNil)
            {
                xmlReader.Skip();
                value = null;
            }
            else
            {
                value = InternalDeserialize(xmlReader, Globals.TypeOfObject, name, string.Empty);
            }
            serializationInfo.AddValue(name, value);
        }
        return serializationInfo;
    }
References System.Runtime.Serialization.XmlObjectSerializerReadContext.attributes, System.Runtime.Serialization.XmlObjectSerializerReadContext.CreateUnexpectedStateException(), System.Xml.XmlConvert.DecodeName(), System.Runtime.Serialization.Dictionary, System.Runtime.Serialization.XmlObjectSerializer.FormatterConverter, System.Runtime.Serialization.XmlObjectSerializerReadContext.GetExistingObject(), System.Runtime.Serialization.XmlObjectSerializerContext.IncrementItemCount(), System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(), System.Runtime.Serialization.Globals.NewObjectId, System.Runtime.Serialization.XmlObjectSerializerReadContext.ReadAttributes(), System.Runtime.Serialization.Attributes.Ref, System.Runtime.Serialization.XmlObjectSerializerReadContext.SkipUnknownElement(), System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperError(), System.type, System.Runtime.Serialization.Globals.TypeOfObject, System.value, and System.Runtime.Serialization.Attributes.XsiNil.
Referenced by System.Runtime.Serialization.ReflectionReader.ReadISerializable(), and System.Runtime.Serialization.SurrogateDataContract.ReadXmlValue().