Terraria: System.Runtime.Serialization.XmlObjectSerializerReadContext.ReadExtensionDataValue
ReadExtensionDataValue() [1/2]
IDataNode System.Runtime.Serialization.XmlObjectSerializerReadContext.ReadExtensionDataValue (XmlReaderDelegator xmlReader) inline inherited
Definition at line 583 of file XmlObjectSerializerReadContext.cs.
    {
        ReadAttributes(xmlReader);
        IncrementItemCount(1);
        IDataNode dataNode = null;
        if (attributes.Ref != Globals.NewObjectId)
        {
            xmlReader.Skip();
            object existingObjectOrExtensionData = GetExistingObjectOrExtensionData(attributes.Ref);
            object obj;
            if (!(existingObjectOrExtensionData is IDataNode))
            {
                IDataNode dataNode2 = new DataNode<object>(existingObjectOrExtensionData);
                obj = dataNode2;
            }
            else
            {
                obj = (IDataNode)existingObjectOrExtensionData;
            }
            dataNode = (IDataNode)obj;
            dataNode.Id = attributes.Ref;
        }
        else if (attributes.XsiNil)
        {
            xmlReader.Skip();
            dataNode = null;
        }
        else
        {
            string dataContractName = null;
            string dataContractNamespace = null;
            if (attributes.XsiTypeName != null)
            {
                dataContractName = attributes.XsiTypeName;
                dataContractNamespace = attributes.XsiTypeNamespace;
            }
            if (IsReadingCollectionExtensionData(xmlReader))
            {
                Read(xmlReader);
                dataNode = ReadUnknownCollectionData(xmlReader, dataContractName, dataContractNamespace);
            }
            else if (attributes.FactoryTypeName != null)
            {
                Read(xmlReader);
                dataNode = ReadUnknownISerializableData(xmlReader, dataContractName, dataContractNamespace);
            }
            else if (IsReadingClassExtensionData(xmlReader))
            {
                Read(xmlReader);
                dataNode = ReadUnknownClassData(xmlReader, dataContractName, dataContractNamespace);
            }
            else
            {
                DataContract dataContract = ResolveDataContractFromTypeName();
                if (dataContract == null)
                {
                    dataNode = ReadExtensionDataValue(xmlReader, dataContractName, dataContractNamespace);
                }
                else if (dataContract is XmlDataContract)
                {
                    dataNode = ReadUnknownXmlData(xmlReader, dataContractName, dataContractNamespace);
                }
                else if (dataContract.IsISerializable)
                {
                    Read(xmlReader);
                    dataNode = ReadUnknownISerializableData(xmlReader, dataContractName, dataContractNamespace);
                }
                else if (dataContract is PrimitiveDataContract)
                {
                    if (attributes.Id == Globals.NewObjectId)
                    {
                        Read(xmlReader);
                        xmlReader.MoveToContent();
                        dataNode = ReadUnknownPrimitiveData(xmlReader, dataContract.UnderlyingType, dataContractName, dataContractNamespace);
                        xmlReader.ReadEndElement();
                    }
                    else
                    {
                        dataNode = new DataNode<object>(xmlReader.ReadElementContentAsAnyType(dataContract.UnderlyingType));
                        InitializeExtensionDataNode(dataNode, dataContractName, dataContractNamespace);
                    }
                }
                else if (dataContract is EnumDataContract)
                {
                    dataNode = new DataNode<object>(((EnumDataContract)dataContract).ReadEnumValue(xmlReader));
                    InitializeExtensionDataNode(dataNode, dataContractName, dataContractNamespace);
                }
                else if (dataContract is ClassDataContract)
                {
                    Read(xmlReader);
                    dataNode = ReadUnknownClassData(xmlReader, dataContractName, dataContractNamespace);
                }
                else if (dataContract is CollectionDataContract)
                {
                    Read(xmlReader);
                    dataNode = ReadUnknownCollectionData(xmlReader, dataContractName, dataContractNamespace);
                }
            }
        }
        return dataNode;
    }
References System.Runtime.Serialization.XmlObjectSerializerReadContext.attributes, System.Runtime.Serialization.Dictionary, System.Runtime.Serialization.Attributes.FactoryTypeName, System.Runtime.Serialization.XmlObjectSerializerReadContext.GetExistingObjectOrExtensionData(), System.Runtime.Serialization.Attributes.Id, System.Runtime.Serialization.XmlObjectSerializerContext.IncrementItemCount(), System.Runtime.Serialization.XmlObjectSerializerReadContext.InitializeExtensionDataNode(), System.Runtime.Serialization.XmlObjectSerializerReadContext.IsReadingClassExtensionData(), System.Runtime.Serialization.XmlObjectSerializerReadContext.IsReadingCollectionExtensionData(), System.Runtime.Serialization.Globals.NewObjectId, System.obj, System.Xml.Serialization.Read, System.Runtime.Serialization.XmlObjectSerializerReadContext.ReadAttributes(), System.Runtime.Serialization.XmlObjectSerializerReadContext.ReadExtensionDataValue(), System.Runtime.Serialization.XmlObjectSerializerReadContext.ReadUnknownClassData(), System.Runtime.Serialization.XmlObjectSerializerReadContext.ReadUnknownCollectionData(), System.Runtime.Serialization.XmlObjectSerializerReadContext.ReadUnknownISerializableData(), System.Runtime.Serialization.XmlObjectSerializerReadContext.ReadUnknownPrimitiveData(), System.Runtime.Serialization.XmlObjectSerializerReadContext.ReadUnknownXmlData(), System.Runtime.Serialization.Attributes.Ref, System.Runtime.Serialization.XmlObjectSerializerReadContext.ResolveDataContractFromTypeName(), System.Runtime.Serialization.Attributes.XsiNil, System.Runtime.Serialization.Attributes.XsiTypeName, and System.Runtime.Serialization.Attributes.XsiTypeNamespace.
Referenced by System.Runtime.Serialization.XmlObjectSerializerReadContext.ReadExtensionDataMember(), System.Runtime.Serialization.XmlObjectSerializerReadContext.ReadExtensionDataValue(), System.Runtime.Serialization.XmlObjectSerializerReadContext.ReadUnknownCollectionData(), and System.Runtime.Serialization.XmlObjectSerializerReadContext.ReadUnknownISerializableData().