Terraria: System.Runtime.Serialization.XmlObjectSerializerReadContext.CheckEndOfArray
CheckEndOfArray()
void System.Runtime.Serialization.XmlObjectSerializerReadContext.CheckEndOfArray (XmlReaderDelegator xmlReader, int arraySize, XmlDictionaryString itemName, XmlDictionaryString itemNamespace) inline package inherited
Definition at line 452 of file XmlObjectSerializerReadContext.cs.
    {
        if (xmlReader.NodeType == XmlNodeType.EndElement)
        {
            return;
        }
        while (xmlReader.IsStartElement())
        {
            if (xmlReader.IsStartElement(itemName, itemNamespace))
            {
                throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(XmlObjectSerializer.CreateSerializationException(System.SR.Format(System.SR.ArrayExceededSizeAttribute, arraySize, itemName.Value, itemNamespace.Value)));
            }
            SkipUnknownElement(xmlReader);
        }
        if (xmlReader.NodeType == XmlNodeType.EndElement)
        {
            return;
        }
        throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(CreateUnexpectedStateException(XmlNodeType.EndElement, xmlReader));
    }
References System.SR.ArrayExceededSizeAttribute, System.Runtime.Serialization.XmlObjectSerializer.CreateSerializationException(), System.Runtime.Serialization.XmlObjectSerializerReadContext.CreateUnexpectedStateException(), System.SR.Format(), System.Runtime.Serialization.XmlObjectSerializerReadContext.SkipUnknownElement(), and System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperError().