Terraria: System.Runtime.Serialization.XmlObjectSerializerReadContext.HandleMemberNotFound
HandleMemberNotFound()
void System.Runtime.Serialization.XmlObjectSerializerReadContext.HandleMemberNotFound (XmlReaderDelegator xmlReader, ExtensionDataObject extensionData, int memberIndex) inline protected inherited
Definition at line 267 of file XmlObjectSerializerReadContext.cs.
    {
        xmlReader.MoveToContent();
        if (xmlReader.NodeType != XmlNodeType.Element)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(CreateUnexpectedStateException(XmlNodeType.Element, xmlReader));
        }
        if (base.IgnoreExtensionDataObject || extensionData == null)
        {
            SkipUnknownElement(xmlReader);
        }
        else
        {
            HandleUnknownElement(xmlReader, extensionData, memberIndex);
        }
    }
References System.Runtime.Serialization.XmlObjectSerializerReadContext.CreateUnexpectedStateException(), System.Runtime.Serialization.XmlObjectSerializerReadContext.HandleUnknownElement(), System.Runtime.Serialization.XmlObjectSerializerReadContext.SkipUnknownElement(), and System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperError().
Referenced by System.Runtime.Serialization.Json.XmlObjectSerializerReadContextComplexJson.GetJsonMemberIndex(), System.Runtime.Serialization.XmlObjectSerializerReadContext.GetMemberIndex(), and System.Runtime.Serialization.XmlObjectSerializerReadContext.GetMemberIndexWithRequiredMembers().