Terraria: System.Runtime.Serialization.XmlObjectSerializerReadContext.ReadUnknownXmlData
ReadUnknownXmlData()
IDataNode System.Runtime.Serialization.XmlObjectSerializerReadContext.ReadUnknownXmlData (XmlReaderDelegator xmlReader, string dataContractName, string dataContractNamespace) inline private inherited
Definition at line 867 of file XmlObjectSerializerReadContext.cs.
    {
        XmlDataNode xmlDataNode = new XmlDataNode();
        InitializeExtensionDataNode(xmlDataNode, dataContractName, dataContractNamespace);
        xmlDataNode.OwnerDocument = Document;
        if (xmlReader.NodeType == XmlNodeType.EndElement)
        {
            return xmlDataNode;
        }
        IList<XmlAttribute> list = null;
        IList<XmlNode> list2 = null;
        XmlNodeType xmlNodeType = xmlReader.MoveToContent();
        if (xmlNodeType != XmlNodeType.Text)
        {
            while (xmlReader.MoveToNextAttribute())
            {
                string namespaceURI = xmlReader.NamespaceURI;
                if (namespaceURI != "http://schemas.microsoft.com/2003/10/Serialization/" && namespaceURI != "http://www.w3.org/2001/XMLSchema-instance")
                {
                    if (list == null)
                    {
                        list = new List<XmlAttribute>();
                    }
                    list.Add((XmlAttribute)Document.ReadNode(xmlReader.UnderlyingReader));
                }
            }
            Read(xmlReader);
        }
        while ((xmlNodeType = xmlReader.MoveToContent()) != XmlNodeType.EndElement)
        {
            if (xmlReader.EOF)
            {
                throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(XmlObjectSerializer.CreateSerializationException(System.SR.UnexpectedEndOfFile));
            }
            if (list2 == null)
            {
                list2 = new List<XmlNode>();
            }
            list2.Add(Document.ReadNode(xmlReader.UnderlyingReader));
        }
        xmlReader.ReadEndElement();
        xmlDataNode.XmlAttributes = list;
        xmlDataNode.XmlChildNodes = list2;
        return xmlDataNode;
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Runtime.Serialization.XmlObjectSerializer.CreateSerializationException(), System.Runtime.Serialization.Dictionary, System.Runtime.Serialization.XmlObjectSerializerReadContext.Document, System.Runtime.Serialization.XmlObjectSerializerReadContext.InitializeExtensionDataNode(), System.list, System.Xml.Serialization.Read, System.Xml.XmlDocument.ReadNode(), System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperError(), and System.SR.UnexpectedEndOfFile.
Referenced by System.Runtime.Serialization.XmlObjectSerializerReadContext.ReadExtensionDataValue(), and System.Runtime.Serialization.XmlObjectSerializerReadContext.ReadExtensionDataValue().