Terraria: System.Runtime.Serialization.XmlObjectSerializerReadContext.ReadAttributes
ReadAttributes()
virtual void System.Runtime.Serialization.XmlObjectSerializerReadContext.ReadAttributes (XmlReaderDelegator xmlReader) inline package virtual inherited
Reimplemented in System.Runtime.Serialization.Json.XmlObjectSerializerReadContextComplexJson.
Definition at line 319 of file XmlObjectSerializerReadContext.cs.
    {
        if (attributes == null)
        {
            attributes = new Attributes();
        }
        attributes.Read(xmlReader);
    }
References System.Runtime.Serialization.XmlObjectSerializerReadContext.attributes, and System.Runtime.Serialization.Attributes.Read().
Referenced by System.Runtime.Serialization.XmlObjectSerializerReadContextComplex.InternalDeserializeWithSurrogate(), System.Runtime.Serialization.XmlObjectSerializerReadContext.ReadExtensionDataValue(), System.Runtime.Serialization.ReflectionReader.ReadItemOfPrimitiveType(), System.Runtime.Serialization.XmlObjectSerializerReadContext.ReadSerializationInfo(), System.Runtime.Serialization.Json.ReflectionJsonReader.ReflectionReadDictionaryItem(), System.Runtime.Serialization.ReflectionXmlReader.ReflectionReadDictionaryItem(), System.Runtime.Serialization.XmlObjectSerializerReadContext.SkipUnknownElement(), and System.Runtime.Serialization.XmlObjectSerializerReadContext.TryHandleNullOrRef().