Terraria: System.Runtime.Serialization.XmlObjectSerializerReadContext.ReadExtensionDataValue
ReadExtensionDataValue() [2/2]
IDataNode System.Runtime.Serialization.XmlObjectSerializerReadContext.ReadExtensionDataValue (XmlReaderDelegator xmlReader, string dataContractName, string dataContractNamespace) inline private inherited
Definition at line 690 of file XmlObjectSerializerReadContext.cs.
    {
        StartReadExtensionDataValue(xmlReader);
        if (attributes.UnrecognizedAttributesFound)
        {
            return ReadUnknownXmlData(xmlReader, dataContractName, dataContractNamespace);
        }
        IDictionary<string, string> namespacesInScope = xmlReader.GetNamespacesInScope(XmlNamespaceScope.ExcludeXml);
        Read(xmlReader);
        xmlReader.MoveToContent();
        switch (xmlReader.NodeType)
        {
        case XmlNodeType.Text:
            return ReadPrimitiveExtensionDataValue(xmlReader, dataContractName, dataContractNamespace);
        case XmlNodeType.Element:
            if (xmlReader.NamespaceURI.StartsWith("http://schemas.datacontract.org/2004/07/", StringComparison.Ordinal))
            {
                return ReadUnknownClassData(xmlReader, dataContractName, dataContractNamespace);
            }
            return ReadAndResolveUnknownXmlData(xmlReader, namespacesInScope, dataContractName, dataContractNamespace);
        case XmlNodeType.EndElement:
        {
            IDataNode dataNode = ReadUnknownPrimitiveData(xmlReader, Globals.TypeOfObject, dataContractName, dataContractNamespace);
            xmlReader.ReadEndElement();
            dataNode.IsFinalValue = false;
            return dataNode;
        }
        default:
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(CreateUnexpectedStateException(XmlNodeType.Element, xmlReader));
        }
    }
References System.Runtime.Serialization.XmlObjectSerializerReadContext.attributes, System.Runtime.Serialization.XmlObjectSerializerReadContext.CreateUnexpectedStateException(), System.Runtime.Serialization.Dictionary, System.Xml.Serialization.Read, System.Runtime.Serialization.XmlObjectSerializerReadContext.ReadAndResolveUnknownXmlData(), System.Runtime.Serialization.XmlObjectSerializerReadContext.ReadPrimitiveExtensionDataValue(), System.Runtime.Serialization.XmlObjectSerializerReadContext.ReadUnknownClassData(), System.Runtime.Serialization.XmlObjectSerializerReadContext.ReadUnknownPrimitiveData(), System.Runtime.Serialization.XmlObjectSerializerReadContext.ReadUnknownXmlData(), System.Runtime.Serialization.XmlObjectSerializerReadContext.StartReadExtensionDataValue(), System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperError(), System.Runtime.Serialization.Globals.TypeOfObject, and System.Runtime.Serialization.Attributes.UnrecognizedAttributesFound.