Terraria: System.Reflection.RuntimeParameterInfo.GetParameters
GetParameters() [2/2]
static ParameterInfo[] System.Reflection.RuntimeParameterInfo.GetParameters (IRuntimeMethodInfo methodHandle, MemberInfo member, Signature sig, out ParameterInfo returnParameter, bool fetchReturnParameter) inline static private
Definition at line 87 of file RuntimeParameterInfo.cs.
    {
        returnParameter = null;
        int num = sig.Arguments.Length;
        ParameterInfo[] array = (fetchReturnParameter ? null : ((num == 0) ? Array.Empty<ParameterInfo>() : new ParameterInfo[num]));
        int methodDef = RuntimeMethodHandle.GetMethodDef(methodHandle);
        int num2 = 0;
        if (!System.Reflection.MetadataToken.IsNullToken(methodDef))
        {
            MetadataImport metadataImport = RuntimeTypeHandle.GetMetadataImport(RuntimeMethodHandle.GetDeclaringType(methodHandle));
            metadataImport.EnumParams(methodDef, out var result);
            num2 = result.Length;
            if (num2 > num + 1)
            {
                throw new BadImageFormatException(SR.BadImageFormat_ParameterSignatureMismatch);
            }
            for (int i = 0; i < num2; i++)
            {
                int num3 = result[i];
                metadataImport.GetParamDefProps(num3, out var sequence, out var attributes);
                sequence--;
                if (fetchReturnParameter && sequence == -1)
                {
                    if (returnParameter != null)
                    {
                        throw new BadImageFormatException(SR.BadImageFormat_ParameterSignatureMismatch);
                    }
                    returnParameter = new RuntimeParameterInfo(sig, metadataImport, num3, sequence, attributes, member);
                }
                else if (!fetchReturnParameter && sequence >= 0)
                {
                    if (sequence >= num)
                    {
                        throw new BadImageFormatException(SR.BadImageFormat_ParameterSignatureMismatch);
                    }
                    array[sequence] = new RuntimeParameterInfo(sig, metadataImport, num3, sequence, attributes, member);
                }
            }
        }
        if (fetchReturnParameter)
        {
            if (returnParameter == null)
            {
                returnParameter = new RuntimeParameterInfo(sig, MetadataImport.EmptyImport, 0, -1, ParameterAttributes.None, member);
            }
        }
        else if (num2 < array.Length + 1)
        {
            for (int j = 0; j < array.Length; j++)
            {
                if (array[j] == null)
                {
                    array[j] = new RuntimeParameterInfo(sig, MetadataImport.EmptyImport, 0, j, ParameterAttributes.None, member);
                }
            }
        }
        return array;
    }
References System.Reflection.RuntimeParameterInfo.RuntimeParameterInfo(), System.array, System.SR.BadImageFormat_ParameterSignatureMismatch, System.Reflection.MetadataImport.EmptyImport, System.RuntimeMethodHandle.GetDeclaringType(), System.RuntimeTypeHandle.GetMetadataImport(), System.RuntimeMethodHandle.GetMethodDef(), and System.Reflection.MetadataToken.IsNullToken().