Terraria: System.Reflection.RuntimeParameterInfo.GetDefaultValueInternal
GetDefaultValueInternal()
object System.Reflection.RuntimeParameterInfo.GetDefaultValueInternal (bool raw) inline private
Definition at line 214 of file RuntimeParameterInfo.cs.
    {
        if (m_noDefaultValue)
        {
            return DBNull.Value;
        }
        object obj = null;
        if (ParameterType == typeof(DateTime))
        {
            if (raw)
            {
                CustomAttributeTypedArgument customAttributeTypedArgument = RuntimeCustomAttributeData.Filter(CustomAttributeData.GetCustomAttributes(this), typeof(DateTimeConstantAttribute), 0);
                if (customAttributeTypedArgument.ArgumentType != null)
                {
                    return new DateTime((long)customAttributeTypedArgument.Value);
                }
            }
            else
            {
                object[] customAttributes = GetCustomAttributes(typeof(DateTimeConstantAttribute), inherit: false);
                if (customAttributes != null && customAttributes.Length != 0)
                {
                    return ((DateTimeConstantAttribute)customAttributes[0]).Value;
                }
            }
        }
        if (!System.Reflection.MetadataToken.IsNullToken(m_tkParamDef))
        {
            obj = MdConstant.GetValue(m_scope, m_tkParamDef, ParameterType.GetTypeHandleInternal(), raw);
        }
        if (obj == DBNull.Value)
        {
            if (raw)
            {
                foreach (CustomAttributeData customAttribute in CustomAttributeData.GetCustomAttributes(this))
                {
                    Type declaringType = customAttribute.Constructor.DeclaringType;
                    if (declaringType == typeof(DateTimeConstantAttribute))
                    {
                        obj = GetRawDateTimeConstant(customAttribute);
                    }
                    else if (declaringType == typeof(DecimalConstantAttribute))
                    {
                        obj = GetRawDecimalConstant(customAttribute);
                    }
                    else if (declaringType.IsSubclassOf(s_CustomConstantAttributeType))
                    {
                        obj = GetRawConstant(customAttribute);
                    }
                }
            }
            else
            {
                object[] customAttributes2 = GetCustomAttributes(s_CustomConstantAttributeType, inherit: false);
                if (customAttributes2.Length != 0)
                {
                    obj = ((CustomConstantAttribute)customAttributes2[0]).Value;
                }
                else
                {
                    customAttributes2 = GetCustomAttributes(s_DecimalConstantAttributeType, inherit: false);
                    if (customAttributes2.Length != 0)
                    {
                        obj = ((DecimalConstantAttribute)customAttributes2[0]).Value;
                    }
                }
            }
        }
        if (obj == DBNull.Value)
        {
            m_noDefaultValue = true;
        }
        return obj;
    }
References System.DateTime, System.Reflection.RuntimeCustomAttributeData.Filter(), System.Reflection.RuntimeParameterInfo.GetCustomAttributes(), System.Reflection.CustomAttributeData.GetCustomAttributes(), System.Reflection.RuntimeParameterInfo.GetRawConstant(), System.Reflection.RuntimeParameterInfo.GetRawDateTimeConstant(), System.Reflection.RuntimeParameterInfo.GetRawDecimalConstant(), System.Reflection.MdConstant.GetValue(), System.Reflection.MetadataToken.IsNullToken(), System.Reflection.RuntimeParameterInfo.m_noDefaultValue, System.Reflection.RuntimeParameterInfo.m_scope, System.Reflection.RuntimeParameterInfo.m_tkParamDef, System.obj, System.Reflection.RuntimeParameterInfo.ParameterType, System.Reflection.RuntimeParameterInfo.s_CustomConstantAttributeType, System.Reflection.RuntimeParameterInfo.s_DecimalConstantAttributeType, and System.DBNull.Value.
Referenced by System.Reflection.RuntimeParameterInfo.GetDefaultValue().