Terraria: System.Runtime.Serialization.XmlObjectSerializerReadContext.InitializeExtensionDataNode
InitializeExtensionDataNode()
void System.Runtime.Serialization.XmlObjectSerializerReadContext.InitializeExtensionDataNode (IDataNode dataNode, string dataContractName, string dataContractNamespace) inline protected inherited
Definition at line 738 of file XmlObjectSerializerReadContext.cs.
    {
        dataNode.DataContractName = dataContractName;
        dataNode.DataContractNamespace = dataContractNamespace;
        dataNode.ClrAssemblyName = attributes.ClrAssembly;
        dataNode.ClrTypeName = attributes.ClrType;
        AddNewObject(dataNode);
        dataNode.Id = attributes.Id;
    }
References System.Runtime.Serialization.XmlObjectSerializerReadContext.AddNewObject(), System.Runtime.Serialization.XmlObjectSerializerReadContext.attributes, System.Runtime.Serialization.Attributes.ClrAssembly, System.Runtime.Serialization.Attributes.ClrType, System.Runtime.Serialization.Dictionary, and System.Runtime.Serialization.Attributes.Id.
Referenced by System.Runtime.Serialization.XmlObjectSerializerReadContext.ReadAndResolveUnknownXmlData(), System.Runtime.Serialization.XmlObjectSerializerReadContext.ReadExtensionDataValue(), System.Runtime.Serialization.XmlObjectSerializerReadContext.ReadPrimitiveExtensionDataValue(), System.Runtime.Serialization.XmlObjectSerializerReadContext.ReadUnknownClassData(), System.Runtime.Serialization.XmlObjectSerializerReadContext.ReadUnknownCollectionData(), System.Runtime.Serialization.XmlObjectSerializerReadContext.ReadUnknownISerializableData(), System.Runtime.Serialization.XmlObjectSerializerReadContext.ReadUnknownPrimitiveData(), and System.Runtime.Serialization.XmlObjectSerializerReadContext.ReadUnknownXmlData().