Terraria: System.Runtime.Serialization.XmlObjectSerializerReadContext.GetExistingObject
GetExistingObject()
object System.Runtime.Serialization.XmlObjectSerializerReadContext.GetExistingObject (string id, Type type, string name, string ns) inline package inherited
Definition at line 374 of file XmlObjectSerializerReadContext.cs.
    {
        object @object = DeserializedObjects.GetObject(id);
        if (@object == null)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(XmlObjectSerializer.CreateSerializationException(System.SR.Format(System.SR.DeserializedObjectWithIdNotFound, id)));
        }
        return @object;
    }
References System.Runtime.Serialization.XmlObjectSerializer.CreateSerializationException(), System.Runtime.Serialization.XmlObjectSerializerReadContext.DeserializedObjects, System.SR.DeserializedObjectWithIdNotFound, System.SR.Format(), System.Runtime.Serialization.HybridObjectCache.GetObject(), and System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperError().
Referenced by System.Runtime.Serialization.ReflectionReader.ReadItemOfPrimitiveType(), System.Runtime.Serialization.XmlObjectSerializerReadContext.ReadSerializationInfo(), and System.Runtime.Serialization.XmlObjectSerializerReadContext.TryHandleNullOrRef().