Terraria: System.Runtime.Serialization.XmlObjectSerializerReadContext.CreateReaderOverChildNodes
CreateReaderOverChildNodes()
XmlReaderDelegator System.Runtime.Serialization.XmlObjectSerializerReadContext.CreateReaderOverChildNodes (IList< XmlAttribute > xmlAttributes, IList< XmlNode > xmlChildNodes) inline package inherited
Definition at line 1021 of file XmlObjectSerializerReadContext.cs.
    {
        XmlNode node = CreateWrapperXmlElement(Document, xmlAttributes, xmlChildNodes, null, null, null);
        XmlReaderDelegator xmlReaderDelegator = CreateReaderDelegatorForReader(new XmlNodeReader(node));
        xmlReaderDelegator.MoveToContent();
        Read(xmlReaderDelegator);
        return xmlReaderDelegator;
    }
References System.Runtime.Serialization.XmlObjectSerializerReadContext.CreateReaderDelegatorForReader(), System.Runtime.Serialization.XmlObjectSerializerReadContext.CreateWrapperXmlElement(), System.Runtime.Serialization.Dictionary, System.Runtime.Serialization.XmlObjectSerializerReadContext.Document, and System.Xml.Serialization.Read.
Referenced by System.Runtime.Serialization.XmlObjectSerializerReadContext.ReadAndResolveUnknownXmlData().