Terraria: System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize
InternalDeserialize() [1/4]
object System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize (XmlReaderDelegator reader, string name, string ns, Type declaredType, ref DataContract dataContract) inline protected inherited
Definition at line 146 of file XmlObjectSerializerReadContext.cs.
    {
        object retObj = null;
        if (TryHandleNullOrRef(reader, dataContract.UnderlyingType, name, ns, ref retObj))
        {
            return retObj;
        }
        bool flag = false;
        if (dataContract.KnownDataContracts != null)
        {
            scopedKnownTypes.Push(dataContract.KnownDataContracts);
            flag = true;
        }
        if (attributes.XsiTypeName != null)
        {
            DataContract dataContract2 = ResolveDataContractFromKnownTypes(attributes.XsiTypeName, attributes.XsiTypeNamespace, dataContract, declaredType);
            if (dataContract2 == null)
            {
                if (base.DataContractResolver == null)
                {
                    throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(XmlObjectSerializer.CreateSerializationException(XmlObjectSerializer.TryAddLineInfo(reader, System.SR.Format(System.SR.DcTypeNotFoundOnDeserialize, attributes.XsiTypeNamespace, attributes.XsiTypeName, reader.NamespaceURI, reader.LocalName))));
                }
                throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(XmlObjectSerializer.CreateSerializationException(XmlObjectSerializer.TryAddLineInfo(reader, System.SR.Format(System.SR.DcTypeNotResolvedOnDeserialize, attributes.XsiTypeNamespace, attributes.XsiTypeName, reader.NamespaceURI, reader.LocalName))));
            }
            dataContract = dataContract2;
            flag = ReplaceScopedKnownTypesTop(dataContract.KnownDataContracts, flag);
        }
        if (dataContract.IsISerializable && attributes.FactoryTypeName != null)
        {
            DataContract dataContract3 = ResolveDataContractFromKnownTypes(attributes.FactoryTypeName, attributes.FactoryTypeNamespace, dataContract, declaredType);
            if (dataContract3 != null)
            {
                if (!dataContract3.IsISerializable)
                {
                    throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(XmlObjectSerializer.CreateSerializationException(System.SR.Format(System.SR.FactoryTypeNotISerializable, DataContract.GetClrTypeFullName(dataContract3.UnderlyingType), DataContract.GetClrTypeFullName(dataContract.UnderlyingType))));
                }
                dataContract = dataContract3;
                flag = ReplaceScopedKnownTypesTop(dataContract.KnownDataContracts, flag);
            }
        }
        if (flag)
        {
            object result = ReadDataContractValue(dataContract, reader);
            scopedKnownTypes.Pop();
            return result;
        }
        return ReadDataContractValue(dataContract, reader);
    }
References System.Runtime.Serialization.XmlObjectSerializerReadContext.attributes, System.Runtime.Serialization.XmlObjectSerializer.CreateSerializationException(), System.SR.DcTypeNotFoundOnDeserialize, System.SR.DcTypeNotResolvedOnDeserialize, System.Runtime.Serialization.Dictionary, System.Runtime.Serialization.Attributes.FactoryTypeName, System.Runtime.Serialization.Attributes.FactoryTypeNamespace, System.SR.FactoryTypeNotISerializable, System.SR.Format(), System.Runtime.Serialization.DataContract.GetClrTypeFullName(), System.Runtime.Serialization.XmlReaderDelegator.LocalName, System.Runtime.Serialization.XmlReaderDelegator.NamespaceURI, System.Runtime.Serialization.ScopedKnownTypes.Pop(), System.Runtime.Serialization.ScopedKnownTypes.Push(), System.Runtime.Serialization.XmlObjectSerializerReadContext.ReadDataContractValue(), System.Runtime.Serialization.XmlObjectSerializerReadContext.ReplaceScopedKnownTypesTop(), System.Runtime.Serialization.XmlObjectSerializerContext.ResolveDataContractFromKnownTypes(), System.Runtime.Serialization.XmlObjectSerializerContext.scopedKnownTypes, System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperError(), System.Runtime.Serialization.XmlObjectSerializer.TryAddLineInfo(), System.Runtime.Serialization.XmlObjectSerializerReadContext.TryHandleNullOrRef(), System.Runtime.Serialization.Attributes.XsiTypeName, and System.Runtime.Serialization.Attributes.XsiTypeNamespace.