Terraria: System.Runtime.Serialization.XmlObjectSerializerReadContext.EnsureArraySize< T >
EnsureArraySize< T >()
static T[] System.Runtime.Serialization.XmlObjectSerializerReadContext.EnsureArraySize< T > (T[] array, int index) inline static package inherited
Definition at line 425 of file XmlObjectSerializerReadContext.cs.
    {
        if (array.Length <= index)
        {
            if (index == int.MaxValue)
            {
                throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(XmlObjectSerializer.CreateSerializationException(System.SR.Format(System.SR.MaxArrayLengthExceeded, int.MaxValue, DataContract.GetClrTypeFullName(typeof(T)))));
            }
            int num = ((index < 1073741823) ? (index * 2) : int.MaxValue);
            T[] array2 = new T[num];
            Array.Copy(array, array2, array.Length);
            array = array2;
        }
        return array;
    }
References System.array, System.Array.Copy(), System.Runtime.Serialization.XmlObjectSerializer.CreateSerializationException(), System.Runtime.Serialization.Dictionary, System.SR.Format(), System.Runtime.Serialization.DataContract.GetClrTypeFullName(), System.index, System.SR.MaxArrayLengthExceeded, and System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperError().