Terraria: System.Runtime.Serialization.XmlObjectSerializerReadContext.CreateUnexpectedStateException
CreateUnexpectedStateException()
static Exception System.Runtime.Serialization.XmlObjectSerializerReadContext.CreateUnexpectedStateException (XmlNodeType expectedState, XmlReaderDelegator xmlReader) inline static package inherited
Definition at line 1059 of file XmlObjectSerializerReadContext.cs.
    {
        return XmlObjectSerializer.CreateSerializationExceptionWithReaderDetails(System.SR.Format(System.SR.ExpectingState, expectedState), xmlReader);
    }
References System.Runtime.Serialization.XmlObjectSerializer.CreateSerializationExceptionWithReaderDetails(), System.SR.ExpectingState, and System.SR.Format().
Referenced by System.Runtime.Serialization.XmlSerializableReader.BeginRead(), System.Runtime.Serialization.XmlObjectSerializerReadContext.CheckEndOfArray(), System.Runtime.Serialization.XmlSerializableReader.EndRead(), System.Runtime.Serialization.XmlObjectSerializerReadContext.HandleMemberNotFound(), System.Runtime.Serialization.XmlObjectSerializerReadContext.ReadExtensionDataValue(), System.Runtime.Serialization.XmlObjectSerializerReadContext.ReadIXmlSerializable(), System.Runtime.Serialization.XmlObjectSerializerReadContext.ReadSerializationInfo(), System.Runtime.Serialization.Json.ReflectionJsonReader.ReadSimpleDictionary(), System.Runtime.Serialization.XmlObjectSerializerReadContext.ReadUnknownClassData(), System.Runtime.Serialization.XmlObjectSerializerReadContext.ReadUnknownCollectionData(), and System.Runtime.Serialization.XmlObjectSerializerReadContext.ReadUnknownISerializableData().