Terraria: System.Runtime.Serialization.XmlObjectSerializerReadContext.ReadAndResolveUnknownXmlData
ReadAndResolveUnknownXmlData()
IDataNode System.Runtime.Serialization.XmlObjectSerializerReadContext.ReadAndResolveUnknownXmlData (XmlReaderDelegator xmlReader, IDictionary< string, string > namespaces, string dataContractName, string dataContractNamespace) inline private inherited
Definition at line 914 of file XmlObjectSerializerReadContext.cs.
    {
        bool flag = true;
        bool flag2 = true;
        bool flag3 = true;
        string strA = null;
        string text = null;
        List<XmlNode> list = new List<XmlNode>();
        IList<XmlAttribute> list2 = null;
        if (namespaces != null)
        {
            list2 = new List<XmlAttribute>();
            foreach (KeyValuePair<string, string> @namespace in namespaces)
            {
                list2.Add(AddNamespaceDeclaration(@namespace.Key, @namespace.Value));
            }
        }
        XmlNodeType nodeType;
        while ((nodeType = xmlReader.NodeType) != XmlNodeType.EndElement)
        {
            if (nodeType == XmlNodeType.Element)
            {
                string namespaceURI = xmlReader.NamespaceURI;
                string localName = xmlReader.LocalName;
                if (flag)
                {
                    flag = namespaceURI.Length == 0;
                }
                if (flag2)
                {
                    if (text == null)
                    {
                        text = localName;
                        strA = namespaceURI;
                    }
                    else
                    {
                        flag2 = string.CompareOrdinal(text, localName) == 0 && string.CompareOrdinal(strA, namespaceURI) == 0;
                    }
                }
            }
            else
            {
                if (xmlReader.EOF)
                {
                    throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(XmlObjectSerializer.CreateSerializationException(System.SR.UnexpectedEndOfFile));
                }
                if (IsContentNode(xmlReader.NodeType))
                {
                    flag3 = (flag = (flag2 = false));
                }
            }
            if (_attributesInXmlData == null)
            {
                _attributesInXmlData = new Attributes();
            }
            _attributesInXmlData.Read(xmlReader);
            XmlNode xmlNode = Document.ReadNode(xmlReader.UnderlyingReader);
            list.Add(xmlNode);
            if (namespaces == null)
            {
                if (_attributesInXmlData.XsiTypeName != null)
                {
                    xmlNode.Attributes.Append(AddNamespaceDeclaration(_attributesInXmlData.XsiTypePrefix, _attributesInXmlData.XsiTypeNamespace));
                }
                if (_attributesInXmlData.FactoryTypeName != null)
                {
                    xmlNode.Attributes.Append(AddNamespaceDeclaration(_attributesInXmlData.FactoryTypePrefix, _attributesInXmlData.FactoryTypeNamespace));
                }
            }
        }
        xmlReader.ReadEndElement();
        if (text != null && flag2)
        {
            return ReadUnknownCollectionData(CreateReaderOverChildNodes(list2, list), dataContractName, dataContractNamespace);
        }
        if (flag)
        {
            return ReadUnknownISerializableData(CreateReaderOverChildNodes(list2, list), dataContractName, dataContractNamespace);
        }
        if (flag3)
        {
            return ReadUnknownClassData(CreateReaderOverChildNodes(list2, list), dataContractName, dataContractNamespace);
        }
        XmlDataNode xmlDataNode = new XmlDataNode();
        InitializeExtensionDataNode(xmlDataNode, dataContractName, dataContractNamespace);
        xmlDataNode.OwnerDocument = Document;
        xmlDataNode.XmlChildNodes = list;
        xmlDataNode.XmlAttributes = list2;
        return xmlDataNode;
    }
References System.Runtime.Serialization.XmlObjectSerializerReadContext._attributesInXmlData, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Runtime.Serialization.XmlObjectSerializerReadContext.AddNamespaceDeclaration(), System.Runtime.Serialization.XmlObjectSerializerReadContext.CreateReaderOverChildNodes(), System.Runtime.Serialization.XmlObjectSerializer.CreateSerializationException(), System.Runtime.Serialization.Dictionary, System.Runtime.Serialization.XmlObjectSerializerReadContext.Document, System.Runtime.Serialization.Attributes.FactoryTypeName, System.Runtime.Serialization.Attributes.FactoryTypeNamespace, System.Runtime.Serialization.Attributes.FactoryTypePrefix, System.Runtime.Serialization.XmlObjectSerializerReadContext.InitializeExtensionDataNode(), System.Runtime.Serialization.XmlObjectSerializerReadContext.IsContentNode(), System.list, System.Runtime.Serialization.Attributes.Read(), System.Xml.XmlDocument.ReadNode(), System.Runtime.Serialization.XmlObjectSerializerReadContext.ReadUnknownClassData(), System.Runtime.Serialization.XmlObjectSerializerReadContext.ReadUnknownCollectionData(), System.Runtime.Serialization.XmlObjectSerializerReadContext.ReadUnknownISerializableData(), System.text, System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperError(), System.SR.UnexpectedEndOfFile, System.Runtime.Serialization.Attributes.XsiTypeName, System.Runtime.Serialization.Attributes.XsiTypeNamespace, and System.Runtime.Serialization.Attributes.XsiTypePrefix.
Referenced by System.Runtime.Serialization.XmlObjectSerializerReadContext.ReadExtensionDataValue().