Terraria: System.Runtime.Serialization.XmlObjectSerializerReadContext.ThrowRequiredMemberMissingException
ThrowRequiredMemberMissingException()
static void System.Runtime.Serialization.XmlObjectSerializerReadContext.ThrowRequiredMemberMissingException (XmlReaderDelegator xmlReader, int memberIndex, int requiredIndex, XmlDictionaryString[] memberNames) inline static package inherited
Definition at line 248 of file XmlObjectSerializerReadContext.cs.
    {
        StringBuilder stringBuilder = new StringBuilder();
        if (requiredIndex == memberNames.Length)
        {
            requiredIndex--;
        }
        for (int i = memberIndex + 1; i <= requiredIndex; i++)
        {
            if (stringBuilder.Length != 0)
            {
                stringBuilder.Append(" | ");
            }
            stringBuilder.Append(memberNames[i].Value);
        }
        throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(XmlObjectSerializer.CreateSerializationException(XmlObjectSerializer.TryAddLineInfo(xmlReader, System.SR.Format(System.SR.UnexpectedElementExpectingElements, xmlReader.NodeType, xmlReader.LocalName, xmlReader.NamespaceURI, stringBuilder.ToString()))));
    }
References System.Runtime.Serialization.XmlObjectSerializer.CreateSerializationException(), System.Runtime.Serialization.Dictionary, System.SR.Format(), System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperError(), System.Runtime.Serialization.XmlObjectSerializer.TryAddLineInfo(), and System.SR.UnexpectedElementExpectingElements.
Referenced by System.Runtime.Serialization.XmlObjectSerializerReadContext.GetMemberIndexWithRequiredMembers().