Terraria: System.Runtime.Serialization.XmlObjectSerializerReadContext.GetRealObject
GetRealObject()
object System.Runtime.Serialization.XmlObjectSerializerReadContext.GetRealObject (IObjectReference obj, string id) inline inherited
Definition at line 394 of file XmlObjectSerializerReadContext.cs.
    {
        object realObject = SurrogateDataContract.GetRealObject(obj, GetStreamingContext());
        if (realObject == null)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(XmlObjectSerializer.CreateSerializationException("error"));
        }
        ReplaceDeserializedObject(id, obj, realObject);
        return realObject;
    }
References System.Runtime.Serialization.XmlObjectSerializer.CreateSerializationException(), System.Runtime.Serialization.Dictionary, System.Runtime.Serialization.SurrogateDataContract.GetRealObject(), System.Runtime.Serialization.XmlObjectSerializerContext.GetStreamingContext(), System.obj, System.Runtime.Serialization.XmlObjectSerializerReadContext.ReplaceDeserializedObject(), and System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperError().
Referenced by System.Runtime.Serialization.ReflectionReader.ReflectionReadClass().