Terraria: System.Runtime.InteropServices.ComEventsHelper.Combine
Combine()
static void System.Runtime.InteropServices.ComEventsHelper.Combine (object rcw, Guid iid, int dispid, Delegate d) inline static
Definition at line 8 of file ComEventsHelper.cs.
    {
        lock (rcw)
        {
            ComEventsInfo comEventsInfo = ComEventsInfo.FromObject(rcw);
            ComEventsSink comEventsSink = comEventsInfo.FindSink(ref iid) ?? comEventsInfo.AddSink(ref iid);
            ComEventsMethod comEventsMethod = comEventsSink.FindMethod(dispid) ?? comEventsSink.AddMethod(dispid);
            comEventsMethod.AddDelegate(d);
        }
    }
References System.Runtime.InteropServices.ComEventsMethod.AddDelegate(), System.Runtime.InteropServices.ComEventsSink.AddMethod(), System.Runtime.InteropServices.ComEventsInfo.AddSink(), System.Runtime.InteropServices.ComEventsSink.FindMethod(), System.Runtime.InteropServices.ComEventsInfo.FindSink(), and System.Runtime.InteropServices.ComEventsInfo.FromObject().
Referenced by System.Runtime.InteropServices.ComAwareEventInfo.AddEventHandler().