Terraria: Terraria.ID.NPCID.Sets.AttackTime
AttackTime
int [] Terraria.ID.NPCID.Sets.AttackTime = Factory.CreateIntSet(-1, 38, 34, 17, 34, 107, 60, 19, 40, 22, 30, 124, 34, 228, 40, 178, 24, 18, 34, 229, 60, 209, 60, 54, 60, 108, 30, 160, 60, 20, 600, 369, 34, 453, 34, 368, 60, 207, 15, 227, 60, 208, 34, 142, 34, 441, 15, 353, 12, 633, 12, 550, 34, 588, 20, 663, 60, 638, -1, 637, -1, 656, -1, 670, -1, 678, -1, 679, -1, 680, -1, 681, -1, 682, -1, 683, -1, 684, -1) static
Definition at line 4224 of file NPCID.cs.
Referenced by Terraria.NPC.AI_007_TownEntities(), Terraria.Main.DrawNPCExtras(), and Terraria.NPC.FindFrame().