Terraria: System.Runtime.InteropServices.ComEventsHelper.Remove
Remove()
static ? Delegate System.Runtime.InteropServices.ComEventsHelper.Remove (object rcw, Guid iid, int dispid, Delegate d) inline static
Definition at line 19 of file ComEventsHelper.cs.
    {
        lock (rcw)
        {
            ComEventsInfo comEventsInfo = ComEventsInfo.Find(rcw);
            if (comEventsInfo == null)
            {
                return null;
            }
            ComEventsSink comEventsSink = comEventsInfo.FindSink(ref iid);
            if (comEventsSink == null)
            {
                return null;
            }
            ComEventsMethod comEventsMethod = comEventsSink.FindMethod(dispid);
            if (comEventsMethod == null)
            {
                return null;
            }
            comEventsMethod.RemoveDelegate(d);
            if (comEventsMethod.Empty)
            {
                comEventsMethod = comEventsSink.RemoveMethod(comEventsMethod);
            }
            if (comEventsMethod == null)
            {
                comEventsSink = comEventsInfo.RemoveSink(comEventsSink);
            }
            if (comEventsSink == null)
            {
                Marshal.SetComObjectData(rcw, typeof(ComEventsInfo), null);
                GC.SuppressFinalize(comEventsInfo);
            }
            return d;
        }
    }
References System.Runtime.InteropServices.ComEventsMethod.Empty, System.Runtime.InteropServices.ComEventsInfo.Find(), System.Runtime.InteropServices.ComEventsSink.FindMethod(), System.Runtime.InteropServices.ComEventsInfo.FindSink(), System.Runtime.InteropServices.ComEventsMethod.RemoveDelegate(), System.Runtime.InteropServices.ComEventsSink.RemoveMethod(), System.Runtime.InteropServices.ComEventsInfo.RemoveSink(), System.Runtime.InteropServices.Marshal.SetComObjectData(), and System.GC.SuppressFinalize().
Referenced by System.Runtime.InteropServices.ComAwareEventInfo.RemoveEventHandler().