Terraria: Terraria.ID.NPCID.Sets.BossHeadTextures
BossHeadTextures
int [] Terraria.ID.NPCID.Sets.BossHeadTextures = Factory.CreateIntSet(-1, 4, 0, 13, 2, 344, 3, 370, 4, 246, 5, 249, 5, 345, 6, 50, 7, 396, 8, 395, 9, 325, 10, 262, 11, 327, 13, 222, 14, 125, 15, 126, 20, 346, 17, 127, 18, 35, 19, 68, 19, 113, 22, 266, 23, 439, 24, 440, 24, 134, 25, 491, 26, 517, 27, 422, 28, 507, 29, 493, 30, 549, 35, 564, 32, 565, 32, 576, 33, 577, 33, 551, 34, 548, 36, 636, 37, 657, 38, 668, 39) static
Referenced by Terraria.GameContent.UI.BigProgressBar.BrainOfCthuluBigProgressBar.Draw(), Terraria.GameContent.UI.BigProgressBar.EaterOfWorldsProgressBar.Draw(), Terraria.GameContent.UI.BigProgressBar.GolemHeadProgressBar.Draw(), Terraria.GameContent.UI.BigProgressBar.MartianSaucerBigProgressBar.Draw(), Terraria.GameContent.UI.BigProgressBar.MoonLordProgressBar.Draw(), Terraria.GameContent.UI.BigProgressBar.PirateShipBigProgressBar.Draw(), and Terraria.NPC.GetBossHeadTextureIndex().