Terraria: System.Reflection.Internal.StreamMemoryBlockProvider.TryCreateMemoryMappedFileBlock
TryCreateMemoryMappedFileBlock()
bool System.Reflection.Internal.StreamMemoryBlockProvider.TryCreateMemoryMappedFileBlock (long start, int size, [NotNullWhen(true)] out MemoryMappedFileBlock block) inline private
Definition at line 97 of file StreamMemoryBlockProvider.cs.
    {
        if (_lazyMemoryMap == null)
        {
            IDisposable disposable;
            lock (_streamGuard)
            {
                disposable = MemoryMapLightUp.CreateMemoryMap(_stream);
            }
            if (disposable == null)
            {
                block = null;
                return false;
            }
            if (Interlocked.CompareExchange(ref _lazyMemoryMap, disposable, null) != null)
            {
                disposable.Dispose();
            }
        }
        IDisposable disposable2 = MemoryMapLightUp.CreateViewAccessor(_lazyMemoryMap, start, size);
        if (disposable2 == null)
        {
            block = null;
            return false;
        }
        if (!MemoryMapLightUp.TryGetSafeBufferAndPointerOffset(disposable2, out SafeBuffer safeBuffer, out long offset))
        {
            block = null;
            return false;
        }
        block = new MemoryMappedFileBlock(disposable2, safeBuffer, offset, size);
        return true;
    }
References System.Reflection.Internal.StreamMemoryBlockProvider._lazyMemoryMap, System.Reflection.Internal.StreamMemoryBlockProvider._stream, System.Reflection.Internal.StreamMemoryBlockProvider._streamGuard, System.Threading.Interlocked.CompareExchange(), System.Reflection.Internal.MemoryMapLightUp.CreateMemoryMap(), System.Reflection.Internal.MemoryMapLightUp.CreateViewAccessor(), System.IDisposable.Dispose(), System.offset, System.start, and System.Reflection.Internal.MemoryMapLightUp.TryGetSafeBufferAndPointerOffset().
Referenced by System.Reflection.Internal.StreamMemoryBlockProvider.GetMemoryBlockImpl().