Terraria: Terraria.GameContent.Biomes.Desert.DesertDescription.CreateFromPlacement
CreateFromPlacement()
static DesertDescription Terraria.GameContent.Biomes.Desert.DesertDescription.CreateFromPlacement (Point origin) inline static
Definition at line 43 of file DesertDescription.cs.
    {
        //IL_0000: Unknown result type (might be due to invalid IL or missing references)
        //IL_0005: Unknown result type (might be due to invalid IL or missing references)
        //IL_0064: Unknown result type (might be due to invalid IL or missing references)
        //IL_0070: Unknown result type (might be due to invalid IL or missing references)
        //IL_016e: Unknown result type (might be due to invalid IL or missing references)
        Vector2D defaultBlockScale = DefaultBlockScale;
        double num = (double)Main.maxTilesX / 4200.0;
        int num2 = (int)(80.0 * num);
        int num3 = (int)((WorldGen.genRand.NextDouble() * 0.5 + 1.5) * 170.0 * num);
        if (WorldGen.remixWorldGen)
        {
            num3 = (int)(340.0 * num);
        }
        int num4 = (int)(defaultBlockScale.X * (double)num2);
        int num5 = (int)(defaultBlockScale.Y * (double)num3);
        origin.X -= num4 / 2;
        SurfaceMap surfaceMap = SurfaceMap.FromArea(origin.X - 5, num4 + 10);
        if (RowHasInvalidTiles(origin.X, surfaceMap.Bottom, num4))
        {
            return Invalid;
        }
        int num6 = (int)(surfaceMap.Average + (double)surfaceMap.Bottom) / 2;
        origin.Y = num6 + WorldGen.genRand.Next(40, 60);
        int num7 = 0;
        if (Main.tenthAnniversaryWorld)
        {
            num7 = (int)(20.0 * num);
        }
        return new DesertDescription
        {
            CombinedArea = new Rectangle(origin.X, num6, num4, origin.Y + num5 - num6),
            Hive = new Rectangle(origin.X, origin.Y + num7, num4, num5 - num7),
            Desert = new Rectangle(origin.X, num6, num4, origin.Y + num5 / 2 - num6 + num7),
            BlockScale = defaultBlockScale,
            BlockColumnCount = num2,
            BlockRowCount = num3,
            Surface = surfaceMap,
            IsValid = true
        };
    }
References Terraria.GameContent.Biomes.Desert.SurfaceMap.Average, Terraria.GameContent.Biomes.Desert.DesertDescription.BlockColumnCount, Terraria.GameContent.Biomes.Desert.DesertDescription.BlockRowCount, Terraria.GameContent.Biomes.Desert.DesertDescription.BlockScale, Terraria.GameContent.Biomes.Desert.SurfaceMap.Bottom, Terraria.GameContent.Biomes.Desert.DesertDescription.CombinedArea, Terraria.GameContent.Biomes.Desert.DesertDescription.DefaultBlockScale, Terraria.GameContent.Biomes.Desert.SurfaceMap.FromArea(), Terraria.WorldGen.genRand, Terraria.GameContent.Biomes.Desert.DesertDescription.Hive, Terraria.GameContent.Biomes.Desert.DesertDescription.Invalid, Terraria.GameContent.Biomes.Desert.DesertDescription.IsValid, Terraria.Main.maxTilesX, Terraria.WorldGen.remixWorldGen, Terraria.GameContent.Biomes.Desert.DesertDescription.RowHasInvalidTiles(), Terraria.GameContent.Biomes.Desert.DesertDescription.Surface, Terraria.Main.tenthAnniversaryWorld, ReLogic.Utilities.Vector2D.X, and ReLogic.Utilities.Vector2D.Y.
Referenced by Terraria.GameContent.Biomes.DesertBiome.Place().