Terraria: UIKeybindingSimpleListItem.DrawSelf
DrawSelf()
override void UIKeybindingSimpleListItem.DrawSelf (SpriteBatch spriteBatch) inline protected virtual
Reimplemented from UIElement.
     {
         float num = 6f;
         base.DrawSelf(spriteBatch);
         CalculatedStyle dimensions = GetDimensions();
         float num2 = dimensions.Width + 1f;
         Vector2 vector = new Vector2(dimensions.X, dimensions.Y);
         Vector2 baseScale = new Vector2(0.8f);
         Color value = (base.IsMouseHovering ? Color.White : Color.Silver);
         value = Color.Lerp(value, Color.White, base.IsMouseHovering ? 0.5f : 0f);
         Color color = (base.IsMouseHovering ? _color : _color.MultiplyRGBA(new Color(180, 180, 180)));
         Vector2 position = vector;
         Utils.DrawSettings2Panel(spriteBatch, position, num2, color);
         position.X += 8f;
         position.Y += 2f + num;
         string text = _GetTextFunction();
         Vector2 stringSize = ChatManager.GetStringSize(FontAssets.ItemStack.Value, text, baseScale);
         position.X = dimensions.X + dimensions.Width / 2f - stringSize.X / 2f;
         ChatManager.DrawColorCodedStringWithShadow(spriteBatch, FontAssets.ItemStack.Value, text, position, value, 0f, Vector2.Zero, baseScale, num2);
     }
References _color, _GetTextFunction, Color, ChatManager.DrawColorCodedStringWithShadow(), Utils.DrawSettings2Panel(), UIElement.GetDimensions(), ChatManager.GetStringSize(), FontAssets.ItemStack, Asset< T >.Value, CalculatedStyle.Width, CalculatedStyle.X, and CalculatedStyle.Y.