Terraria: Segments.PlayerSegment.Draw
Draw()
override void Segments.PlayerSegment.Draw (ref GameAnimationSegment info) inline virtual
Implements Segments.AnimationSegmentWithActions< Player >.
         {
             if ((float)info.TimeInAnimation > (float)_targetTime + base.DedicatedTimeNeeded || info.TimeInAnimation < _targetTime)
             {
                 return;
             }
             ResetPlayerAnimation(ref info);
             float localTimeForObject = info.TimeInAnimation - _targetTime;
             ProcessActions(_player, localTimeForObject);
             if (info.DisplayOpacity != 0f)
             {
                 _player.ResetEffects();
                 _player.ResetVisibleAccessories();
                 _player.UpdateMiscCounter();
                 _player.UpdateDyes();
                 _player.PlayerFrame();
                 _player.socialIgnoreLight = true;
                 _player.position += Main.screenPosition;
                 _player.position -= new Vector2(_player.width / 2, _player.height);
                 _player.opacityForAnimation *= info.DisplayOpacity;
                 Item item = _player.inventory[_player.selectedItem];
                 _player.inventory[_player.selectedItem] = _blankItem;
                 float num = 1f - _player.opacityForAnimation;
                 num = 0f;
                 if (_shaderEffect != null)
                 {
                     _shaderEffect.BeforeDrawing(ref info);
                 }
                 Main.PlayerRenderer.DrawPlayer(Main.Camera, _player, _player.position, 0f, _player.fullRotationOrigin, num);
                 if (_shaderEffect != null)
                 {
                     _shaderEffect.AfterDrawing(ref info);
                 }
                 _player.inventory[_player.selectedItem] = item;
             }
         }
References Segments.PlayerSegment._blankItem, Segments.PlayerSegment._player, Segments.PlayerSegment._shaderEffect, Segments.AnimationSegmentWithActions< Player >._targetTime, Segments.PlayerSegment.IShaderEffect.AfterDrawing(), Segments.PlayerSegment.IShaderEffect.BeforeDrawing(), Main.Camera, IPlayerRenderer.DrawPlayer(), Player.fullRotationOrigin, Entity.height, Player.inventory, Player.opacityForAnimation, Player.PlayerFrame(), Main.PlayerRenderer, Entity.position, Segments.AnimationSegmentWithActions< Player >.ProcessActions(), Player.ResetEffects(), Segments.PlayerSegment.ResetPlayerAnimation(), Player.ResetVisibleAccessories(), Main.screenPosition, Player.selectedItem, Player.socialIgnoreLight, Player.UpdateDyes(), Player.UpdateMiscCounter(), and Entity.width.