Terraria: System.Text.DBCSCodePageEncoding.ReadChar
ReadChar()
static unsafe char System.Text.DBCSCodePageEncoding.ReadChar (char * pChar) inline static package inherited
Definition at line 71 of file DBCSCodePageEncoding.cs.
    {
        if (BitConverter.IsLittleEndian)
        {
            return *pChar;
        }
        return (char)BinaryPrimitives.ReverseEndianness(*pChar);
    }
References System.BitConverter.IsLittleEndian, and System.Buffers.Binary.BinaryPrimitives.ReverseEndianness().
Referenced by System.Text.DBCSCodePageEncoding.LoadManagedCodePage(), and System.Text.DBCSCodePageEncoding.ReadBestFitTable().