Terraria: System.Text.DBCSCodePageEncoding.GetChars
GetChars() [2/6]
unsafe override int System.Text.DBCSCodePageEncoding.GetChars (byte * bytes, int byteCount, char * chars, int charCount, System::Text::DecoderNLS baseDecoder) inline virtual inherited
Reimplemented from System.Text.Encoding.
Reimplemented in System.Text.GB18030Encoding, and System.Text.ISO2022Encoding.
Definition at line 754 of file DBCSCodePageEncoding.cs.
    {
        CheckMemorySection();
        DBCSDecoder dBCSDecoder = (DBCSDecoder)baseDecoder;
        byte* ptr = bytes;
        byte* ptr2 = bytes + byteCount;
        char* ptr3 = chars;
        char* ptr4 = chars + charCount;
        bool flag = false;
        DecoderFallbackBuffer decoderFallbackBuffer = null;
        DecoderFallbackBufferHelper decoderFallbackBufferHelper = new DecoderFallbackBufferHelper(decoderFallbackBuffer);
        if (dBCSDecoder != null && dBCSDecoder.bLeftOver > 0)
        {
            if (byteCount == 0)
            {
                if (!dBCSDecoder.MustFlush)
                {
                    return 0;
                }
                decoderFallbackBuffer = dBCSDecoder.FallbackBuffer;
                decoderFallbackBufferHelper = new DecoderFallbackBufferHelper(decoderFallbackBuffer);
                decoderFallbackBufferHelper.InternalInitialize(bytes, ptr4);
                byte[] bytes2 = new byte[1] { dBCSDecoder.bLeftOver };
                if (!decoderFallbackBufferHelper.InternalFallback(bytes2, bytes, ref chars))
                {
                    ThrowCharsOverflow(dBCSDecoder, nothingDecoded: true);
                }
                dBCSDecoder.bLeftOver = 0;
                return (int)(chars - ptr3);
            }
            int num = dBCSDecoder.bLeftOver << 8;
            num |= *bytes;
            bytes++;
            char c = mapBytesToUnicode[num];
            if (c == '\0' && num != 0)
            {
                decoderFallbackBuffer = dBCSDecoder.FallbackBuffer;
                decoderFallbackBufferHelper = new DecoderFallbackBufferHelper(decoderFallbackBuffer);
                decoderFallbackBufferHelper.InternalInitialize(ptr2 - byteCount, ptr4);
                byte[] bytes3 = new byte[2]
                {
                    (byte)(num >> 8),
                    (byte)num
                };
                if (!decoderFallbackBufferHelper.InternalFallback(bytes3, bytes, ref chars))
                {
                    ThrowCharsOverflow(dBCSDecoder, nothingDecoded: true);
                }
            }
            else
            {
                if (chars >= ptr4)
                {
                    ThrowCharsOverflow(dBCSDecoder, nothingDecoded: true);
                }
                *(chars++) = c;
            }
        }
        while (bytes < ptr2)
        {
            int num2 = *bytes;
            bytes++;
            char c2 = mapBytesToUnicode[num2];
            if (c2 == '\ufffe')
            {
                if (bytes < ptr2)
                {
                    num2 <<= 8;
                    num2 |= *bytes;
                    bytes++;
                    c2 = mapBytesToUnicode[num2];
                }
                else
                {
                    if (dBCSDecoder != null && !dBCSDecoder.MustFlush)
                    {
                        flag = true;
                        dBCSDecoder.bLeftOver = (byte)num2;
                        break;
                    }
                    c2 = '\0';
                }
            }
            if (c2 == '\0' && num2 != 0)
            {
                if (decoderFallbackBuffer == null)
                {
                    decoderFallbackBuffer = ((dBCSDecoder != null) ? dBCSDecoder.FallbackBuffer : base.DecoderFallback.CreateFallbackBuffer());
                    decoderFallbackBufferHelper = new DecoderFallbackBufferHelper(decoderFallbackBuffer);
                    decoderFallbackBufferHelper.InternalInitialize(ptr2 - byteCount, ptr4);
                }
                byte[] array = ((num2 >= 256) ? new byte[2]
                {
                    (byte)(num2 >> 8),
                    (byte)num2
                } : new byte[1] { (byte)num2 });
                if (!decoderFallbackBufferHelper.InternalFallback(array, bytes, ref chars))
                {
                    bytes -= array.Length;
                    decoderFallbackBufferHelper.InternalReset();
                    ThrowCharsOverflow(dBCSDecoder, bytes == ptr);
                    break;
                }
                continue;
            }
            if (chars >= ptr4)
            {
                bytes--;
                if (num2 >= 256)
                {
                    bytes--;
                }
                ThrowCharsOverflow(dBCSDecoder, bytes == ptr);
                break;
            }
            *(chars++) = c2;
        }
        if (dBCSDecoder != null)
        {
            if (!flag)
            {
                dBCSDecoder.bLeftOver = 0;
            }
            dBCSDecoder.m_bytesUsed = (int)(bytes - ptr);
        }
        return (int)(chars - ptr3);
    }
References System.array, System.Text.DBCSCodePageEncoding.DBCSDecoder.bLeftOver, System.byteCount, System.bytes, System.charCount, System.chars, System.Text.BaseCodePageEncoding.CheckMemorySection(), System.Text.DecoderNLS.FallbackBuffer, System.Text.DecoderFallbackBufferHelper.InternalFallback(), System.Text.DecoderFallbackBufferHelper.InternalInitialize(), System.Text.DecoderFallbackBufferHelper.InternalReset(), System.Text.DBCSCodePageEncoding.mapBytesToUnicode, System.Text.DecoderNLS.MustFlush, and System.Text.EncodingNLS.ThrowCharsOverflow().