Terraria: System.Text.DBCSCodePageEncoding.GetBytes
GetBytes() [2/9]
unsafe override int System.Text.DBCSCodePageEncoding.GetBytes (char * chars, int charCount, byte * bytes, int byteCount, System::Text::EncoderNLS encoder) inline virtual inherited
Reimplemented from System.Text.Encoding.
Reimplemented in System.Text.ISO2022Encoding, and System.Text.GB18030Encoding.
Definition at line 580 of file DBCSCodePageEncoding.cs.
    {
        CheckMemorySection();
        EncoderFallbackBuffer encoderFallbackBuffer = null;
        char* ptr = chars + charCount;
        char* ptr2 = chars;
        byte* ptr3 = bytes;
        byte* ptr4 = bytes + byteCount;
        EncoderFallbackBufferHelper encoderFallbackBufferHelper = new EncoderFallbackBufferHelper(encoderFallbackBuffer);
        char c = '\0';
        if (encoder != null)
        {
            c = encoder.charLeftOver;
            encoderFallbackBuffer = encoder.FallbackBuffer;
            encoderFallbackBufferHelper = new EncoderFallbackBufferHelper(encoderFallbackBuffer);
            encoderFallbackBufferHelper.InternalInitialize(chars, ptr, encoder, _setEncoder: true);
            if (encoder.m_throwOnOverflow && encoderFallbackBuffer.Remaining > 0)
            {
                throw new ArgumentException(System.SR.Format(System.SR.Argument_EncoderFallbackNotEmpty, EncodingName, encoder.Fallback.GetType()));
            }
            if (c > '\0')
            {
                encoderFallbackBufferHelper.InternalFallback(c, ref chars);
            }
        }
        char c2;
        while ((c2 = ((encoderFallbackBuffer != null) ? encoderFallbackBufferHelper.InternalGetNextChar() : '\0')) != 0 || chars < ptr)
        {
            if (c2 == '\0')
            {
                c2 = *chars;
                chars++;
            }
            ushort num = mapUnicodeToBytes[(int)c2];
            if (num == 0 && c2 != 0)
            {
                if (encoderFallbackBuffer == null)
                {
                    encoderFallbackBuffer = base.EncoderFallback.CreateFallbackBuffer();
                    encoderFallbackBufferHelper = new EncoderFallbackBufferHelper(encoderFallbackBuffer);
                    encoderFallbackBufferHelper.InternalInitialize(ptr - charCount, ptr, encoder, _setEncoder: true);
                }
                encoderFallbackBufferHelper.InternalFallback(c2, ref chars);
                continue;
            }
            if (num >= 256)
            {
                if (bytes + 1 >= ptr4)
                {
                    if (encoderFallbackBuffer == null || !encoderFallbackBufferHelper.bFallingBack)
                    {
                        chars--;
                    }
                    else
                    {
                        encoderFallbackBuffer.MovePrevious();
                    }
                    ThrowBytesOverflow(encoder, chars == ptr2);
                    break;
                }
                *bytes = (byte)(num >> 8);
                bytes++;
            }
            else if (bytes >= ptr4)
            {
                if (encoderFallbackBuffer == null || !encoderFallbackBufferHelper.bFallingBack)
                {
                    chars--;
                }
                else
                {
                    encoderFallbackBuffer.MovePrevious();
                }
                ThrowBytesOverflow(encoder, chars == ptr2);
                break;
            }
            *bytes = (byte)(num & 0xFFu);
            bytes++;
        }
        if (encoder != null)
        {
            if (encoderFallbackBuffer != null && !encoderFallbackBufferHelper.bUsedEncoder)
            {
                encoder.charLeftOver = '\0';
            }
            encoder.m_charsUsed = (int)(chars - ptr2);
        }
        return (int)(bytes - ptr3);
    }
References System.SR.Argument_EncoderFallbackNotEmpty, System.Text.EncoderFallbackBufferHelper.bFallingBack, System.Text.EncoderFallbackBufferHelper.bUsedEncoder, System.byteCount, System.bytes, System.charCount, System.chars, System.Text.BaseCodePageEncoding.CheckMemorySection(), System.Text.EncodingNLS.EncodingName, System.SR.Format(), System.Text.EncoderFallbackBufferHelper.InternalFallback(), System.Text.EncoderFallbackBufferHelper.InternalGetNextChar(), System.Text.EncoderFallbackBufferHelper.InternalInitialize(), System.Text.DBCSCodePageEncoding.mapUnicodeToBytes, System.Text.EncoderFallbackBuffer.MovePrevious(), System.Text.EncoderFallbackBuffer.Remaining, and System.Text.EncodingNLS.ThrowBytesOverflow().