Terraria: System.Text.DBCSCodePageEncoding.LoadManagedCodePage
LoadManagedCodePage()
unsafe override void System.Text.DBCSCodePageEncoding.LoadManagedCodePage () inline protected inherited
Definition at line 80 of file DBCSCodePageEncoding.cs.
    {
        fixed (byte* ptr = &m_codePageHeader[0])
        {
            CodePageHeader* ptr2 = (CodePageHeader*)ptr;
            if (ptr2->ByteCount != 2)
            {
                throw new NotSupportedException(System.SR.Format(System.SR.NotSupported_NoCodepageData, CodePage));
            }
            _bytesUnknown = ptr2->ByteReplace;
            charUnknown = ptr2->UnicodeReplace;
            if (base.DecoderFallback is InternalDecoderBestFitFallback)
            {
                ((InternalDecoderBestFitFallback)base.DecoderFallback).cReplacement = charUnknown;
            }
            _byteCountUnknown = 1;
            if (_bytesUnknown > 255)
            {
                _byteCountUnknown++;
            }
            int num = 262148 + iExtraBytes;
            byte* nativeMemory = GetNativeMemory(num);
            Unsafe.InitBlockUnaligned(nativeMemory, 0, (uint)num);
            mapBytesToUnicode = (char*)nativeMemory;
            mapUnicodeToBytes = (ushort*)(nativeMemory + 131072);
            byte[] array = new byte[m_dataSize];
            lock (BaseCodePageEncoding.s_streamLock)
            {
                BaseCodePageEncoding.s_codePagesEncodingDataStream.Seek(m_firstDataWordOffset, SeekOrigin.Begin);
                BaseCodePageEncoding.s_codePagesEncodingDataStream.Read(array, 0, m_dataSize);
            }
            fixed (byte* ptr3 = array)
            {
                char* ptr4 = (char*)ptr3;
                int num2 = 0;
                int num3 = 0;
                while (num2 < 65536)
                {
                    char c = ReadChar(ptr4);
                    ptr4++;
                    switch (c)
                    {
                    case '\u0001':
                        num2 = ReadChar(ptr4);
                        ptr4++;
                        continue;
                    case '\u0002':
                    case '\u0003':
                    case '\u0004':
                    case '\u0005':
                    case '\u0006':
                    case '\a':
                    case '\b':
                    case '\t':
                    case '\n':
                    case '\v':
                    case '\f':
                    case '\r':
                    case '\u000e':
                    case '\u000f':
                    case '\u0010':
                    case '\u0011':
                    case '\u0012':
                    case '\u0013':
                    case '\u0014':
                    case '\u0015':
                    case '\u0016':
                    case '\u0017':
                    case '\u0018':
                    case '\u0019':
                    case '\u001a':
                    case '\u001b':
                    case '\u001c':
                    case '\u001d':
                    case '\u001e':
                    case '\u001f':
                        num2 += c;
                        continue;
                    }
                    switch (c)
                    {
                    case '\uffff':
                        num3 = num2;
                        c = (char)num2;
                        break;
                    case '\ufffe':
                        num3 = num2;
                        break;
                    case '\ufffd':
                        num2++;
                        continue;
                    default:
                        num3 = num2;
                        break;
                    }
                    if (CleanUpBytes(ref num3))
                    {
                        if (c != '\ufffe')
{
                            mapUnicodeToBytes[(int)c] = (ushort)num3;
                        }
                        mapBytesToUnicode[num3] = c;
                    }
                    num2++;
                }
            }
            CleanUpEndBytes(mapBytesToUnicode);
        }
    }
References System.Text.DBCSCodePageEncoding._byteCountUnknown, System.Text.DBCSCodePageEncoding._bytesUnknown, System.array, System.Text.BaseCodePageEncoding.CodePageHeader.ByteCount, System.Text.BaseCodePageEncoding.CodePageHeader.ByteReplace, System.Text.DBCSCodePageEncoding.charUnknown, System.Text.DBCSCodePageEncoding.CleanUpBytes(), System.Text.DBCSCodePageEncoding.CleanUpEndBytes(), System.Text.Encoding.CodePage, System.SR.Format(), System.Text.BaseCodePageEncoding.GetNativeMemory(), System.Text.BaseCodePageEncoding.iExtraBytes, System.Runtime.CompilerServices.Unsafe.InitBlockUnaligned(), System.Text.BaseCodePageEncoding.m_codePageHeader, System.Text.BaseCodePageEncoding.m_dataSize, System.Text.BaseCodePageEncoding.m_firstDataWordOffset, System.Text.DBCSCodePageEncoding.mapBytesToUnicode, System.Text.DBCSCodePageEncoding.mapUnicodeToBytes, System.SR.NotSupported_NoCodepageData, System.Text.DBCSCodePageEncoding.ReadChar(), System.Text.BaseCodePageEncoding.s_codePagesEncodingDataStream, System.Text.BaseCodePageEncoding.s_streamLock, and System.Text.BaseCodePageEncoding.CodePageHeader.UnicodeReplace.