Terraria: System.Text.DBCSCodePageEncoding.GetCharCount
GetCharCount() [2/5]
unsafe override int System.Text.DBCSCodePageEncoding.GetCharCount (byte * bytes, int count, System::Text::DecoderNLS baseDecoder) inline virtual inherited
Reimplemented from System.Text.Encoding.
Reimplemented in System.Text.GB18030Encoding, and System.Text.ISO2022Encoding.
Definition at line 670 of file DBCSCodePageEncoding.cs.
    {
        CheckMemorySection();
        DBCSDecoder dBCSDecoder = (DBCSDecoder)baseDecoder;
        DecoderFallbackBuffer decoderFallbackBuffer = null;
        byte* ptr = bytes + count;
        int num = count;
        DecoderFallbackBufferHelper decoderFallbackBufferHelper = new DecoderFallbackBufferHelper(decoderFallbackBuffer);
        if (dBCSDecoder != null && dBCSDecoder.bLeftOver > 0)
        {
            if (count == 0)
            {
                if (!dBCSDecoder.MustFlush)
                {
                    return 0;
                }
                decoderFallbackBuffer = dBCSDecoder.FallbackBuffer;
                decoderFallbackBufferHelper = new DecoderFallbackBufferHelper(decoderFallbackBuffer);
                decoderFallbackBufferHelper.InternalInitialize(bytes, null);
                byte[] bytes2 = new byte[1] { dBCSDecoder.bLeftOver };
                return decoderFallbackBufferHelper.InternalFallback(bytes2, bytes);
            }
            int num2 = dBCSDecoder.bLeftOver << 8;
            num2 |= *bytes;
            bytes++;
            if (mapBytesToUnicode[num2] == '\0' && num2 != 0)
            {
                num--;
                decoderFallbackBuffer = dBCSDecoder.FallbackBuffer;
                decoderFallbackBufferHelper = new DecoderFallbackBufferHelper(decoderFallbackBuffer);
                decoderFallbackBufferHelper.InternalInitialize(ptr - count, null);
                byte[] bytes3 = new byte[2]
                {
                    (byte)(num2 >> 8),
                    (byte)num2
                };
                num += decoderFallbackBufferHelper.InternalFallback(bytes3, bytes);
            }
        }
        while (bytes < ptr)
        {
            int num3 = *bytes;
            bytes++;
            char c = mapBytesToUnicode[num3];
            if (c == '\ufffe')
            {
                num--;
                if (bytes < ptr)
                {
                    num3 <<= 8;
                    num3 |= *bytes;
                    bytes++;
                    c = mapBytesToUnicode[num3];
                }
                else
                {
                    if (dBCSDecoder != null && !dBCSDecoder.MustFlush)
                    {
                        break;
                    }
                    num++;
                    c = '\0';
                }
            }
            if (c == '\0' && num3 != 0)
            {
                if (decoderFallbackBuffer == null)
                {
                    decoderFallbackBuffer = ((dBCSDecoder != null) ? dBCSDecoder.FallbackBuffer : base.DecoderFallback.CreateFallbackBuffer());
                    decoderFallbackBufferHelper = new DecoderFallbackBufferHelper(decoderFallbackBuffer);
                    decoderFallbackBufferHelper.InternalInitialize(ptr - count, null);
                }
                num--;
                byte[] bytes4 = ((num3 >= 256) ? new byte[2]
                {
                    (byte)(num3 >> 8),
                    (byte)num3
                } : new byte[1] { (byte)num3 });
                num += decoderFallbackBufferHelper.InternalFallback(bytes4, bytes);
            }
        }
        return num;
    }
References System.Text.DBCSCodePageEncoding.DBCSDecoder.bLeftOver, System.bytes, System.Text.BaseCodePageEncoding.CheckMemorySection(), System.count, System.Text.DecoderNLS.FallbackBuffer, System.Text.DecoderFallbackBufferHelper.InternalFallback(), System.Text.DecoderFallbackBufferHelper.InternalInitialize(), System.Text.DBCSCodePageEncoding.mapBytesToUnicode, and System.Text.DecoderNLS.MustFlush.