Terraria: System.Data.SqlTypes.SqlBoolean.Null
Null
readonly SqlBoolean System.Data.SqlTypes.SqlBoolean.Null = new SqlBoolean(0, fNull: true) static
Definition at line 21 of file SqlBoolean.cs.
Referenced by System.Data.SqlTypes.SqlString.Compare(), System.Data.Common.SqlConvert.ConvertToSqlBoolean(), System.Data.SqlTypes.SqlBoolean.operator SqlBoolean(), System.Data.SqlTypes.SqlBoolean.operator SqlBoolean(), System.Data.SqlTypes.SqlBoolean.operator SqlBoolean(), System.Data.SqlTypes.SqlBoolean.operator SqlBoolean(), System.Data.SqlTypes.SqlBoolean.operator SqlBoolean(), System.Data.SqlTypes.SqlBoolean.operator SqlBoolean(), System.Data.SqlTypes.SqlBoolean.operator SqlBoolean(), System.Data.SqlTypes.SqlBoolean.operator SqlBoolean(), System.Data.SqlTypes.SqlBoolean.operator SqlBoolean(), System.Data.SqlTypes.SqlBoolean.operator!(), System.Data.SqlTypes.SqlBoolean.operator&(), System.Data.SqlTypes.SqlBinary.operator<(), System.Data.SqlTypes.SqlBoolean.operator<(), System.Data.SqlTypes.SqlByte.operator<(), System.Data.SqlTypes.SqlDateTime.operator<(), System.Data.SqlTypes.SqlDecimal.operator<(), System.Data.SqlTypes.SqlDouble.operator<(), System.Data.SqlTypes.SqlGuid.operator<(), System.Data.SqlTypes.SqlInt16.operator<(), System.Data.SqlTypes.SqlInt32.operator<(), System.Data.SqlTypes.SqlInt64.operator<(), System.Data.SqlTypes.SqlMoney.operator<(), System.Data.SqlTypes.SqlSingle.operator<(), System.Data.SqlTypes.SqlBinary.operator<=(), System.Data.SqlTypes.SqlBoolean.operator<=(), System.Data.SqlTypes.SqlByte.operator<=(), System.Data.SqlTypes.SqlDateTime.operator<=(), System.Data.SqlTypes.SqlDecimal.operator<=(), System.Data.SqlTypes.SqlDouble.operator<=(), System.Data.SqlTypes.SqlGuid.operator<=(), System.Data.SqlTypes.SqlInt16.operator<=(), System.Data.SqlTypes.SqlInt32.operator<=(), System.Data.SqlTypes.SqlInt64.operator<=(), System.Data.SqlTypes.SqlMoney.operator<=(), System.Data.SqlTypes.SqlSingle.operator<=(), System.Data.SqlTypes.SqlBinary.operator==(), System.Data.SqlTypes.SqlBoolean.operator==(), System.Data.SqlTypes.SqlByte.operator==(), System.Data.SqlTypes.SqlDateTime.operator==(), System.Data.SqlTypes.SqlDecimal.operator==(), System.Data.SqlTypes.SqlDouble.operator==(), System.Data.SqlTypes.SqlGuid.operator==(), System.Data.SqlTypes.SqlInt16.operator==(), System.Data.SqlTypes.SqlInt32.operator==(), System.Data.SqlTypes.SqlInt64.operator==(), System.Data.SqlTypes.SqlMoney.operator==(), System.Data.SqlTypes.SqlSingle.operator==(), System.Data.SqlTypes.SqlBinary.operator>(), System.Data.SqlTypes.SqlBoolean.operator>(), System.Data.SqlTypes.SqlByte.operator>(), System.Data.SqlTypes.SqlDateTime.operator>(), System.Data.SqlTypes.SqlDecimal.operator>(), System.Data.SqlTypes.SqlDouble.operator>(), System.Data.SqlTypes.SqlGuid.operator>(), System.Data.SqlTypes.SqlInt16.operator>(), System.Data.SqlTypes.SqlInt32.operator>(), System.Data.SqlTypes.SqlInt64.operator>(), System.Data.SqlTypes.SqlMoney.operator>(), System.Data.SqlTypes.SqlSingle.operator>(), System.Data.SqlTypes.SqlBinary.operator>=(), System.Data.SqlTypes.SqlBoolean.operator>=(), System.Data.SqlTypes.SqlByte.operator>=(), System.Data.SqlTypes.SqlDateTime.operator>=(), System.Data.SqlTypes.SqlDecimal.operator>=(), System.Data.SqlTypes.SqlDouble.operator>=(), System.Data.SqlTypes.SqlGuid.operator>=(), System.Data.SqlTypes.SqlInt16.operator>=(), System.Data.SqlTypes.SqlInt32.operator>=(), System.Data.SqlTypes.SqlInt64.operator>=(), System.Data.SqlTypes.SqlMoney.operator>=(), System.Data.SqlTypes.SqlSingle.operator>=(), System.Data.SqlTypes.SqlBoolean.operator^(), System.Data.SqlTypes.SqlBoolean.operator|(), and System.Data.SqlTypes.SqlBoolean.Parse().