Terraria: System.Xml.Xsl.XPathConvert.FloatingDecimal.AdjustDbl
AdjustDbl()
double System.Xml.Xsl.XPathConvert.FloatingDecimal.AdjustDbl (double dbl) inline private
Definition at line 1459 of file XPathConvert.cs.
        {
            BigInteger bigInteger = new BigInteger();
            BigInteger bigInteger2 = new BigInteger();
            bigInteger.InitFromFloatingDecimal(this);
            int num = _exponent - _mantissaSize;
            int num3;
            int num5;
            int num4;
            int num2;
            if (num >= 0)
            {
                num3 = (num2 = num);
                num5 = (num4 = 0);
            }
            else
            {
                num3 = (num2 = 0);
                num5 = (num4 = -num);
            }
            uint num6 = DblHi(dbl);
            uint num7 = DblLo(dbl);
            int num8 = (int)((num6 >> 20) & 0x7FF);
            num6 &= 0xFFFFFu;
            uint u = 1u;
            if (num8 != 0)
            {
                if (num6 == 0 && num7 == 0 && 1 != num8)
                {
                    u = 2u;
                    num6 = 2097152u;
                    num8--;
                }
                else
                {
                    num6 |= 0x100000u;
                }
                num8 -= 1076;
            }
            else
            {
                num8 = -1075;
            }
            num6 = (num6 << 1) | (num7 >> 31);
            num7 <<= 1;
            int cu = ((num7 != 0 || num6 != 0) ? ((num6 == 0) ? 1 : 2) : 0);
            bigInteger2.InitFromDigits(num7, num6, cu);
            if (num8 >= 0)
            {
                num4 += num8;
            }
            else
            {
                num2 += -num8;
            }
            if (num4 > num2)
            {
                num4 -= num2;
                num2 = 0;
                int num9 = 0;
                while (num4 >= 32 && bigInteger[num9] == 0)
                {
                    num4 -= 32;
                    num9++;
                }
                if (num9 > 0)
                {
                    bigInteger.ShiftUsRight(num9);
                }
                uint num10 = bigInteger[0];
                for (num9 = 0; num9 < num4 && (num10 & (1L << num9)) == 0L; num9++)
                {
                }
                if (num9 > 0)
                {
                    num4 -= num9;
                    bigInteger.ShiftRight(num9);
                }
            }
            else
            {
                num2 -= num4;
                num4 = 0;
            }
            if (num5 > 0)
            {
                bigInteger2.MulPow5(num5);
            }
            else if (num3 > 0)
            {
                bigInteger.MulPow5(num3);
            }
            if (num4 > 0)
            {
                bigInteger2.ShiftLeft(num4);
            }
            else if (num2 > 0)
            {
                bigInteger.ShiftLeft(num2);
            }
            int num11 = bigInteger2.CompareTo(bigInteger);
            if (num11 == 0)
            {
                return dbl;
            }
            if (num11 > 0)
            {
                if (AddU(ref num7, uint.MaxValue) == 0)
                {
                    AddU(ref num6, uint.MaxValue);
                }
                bigInteger2.InitFromDigits(num7, num6, 1 + ((num6 != 0) ? 1 : 0));
                if (num5 > 0)
                {
                    bigInteger2.MulPow5(num5);
                }
                if (num4 > 0)
                {
                    bigInteger2.ShiftLeft(num4);
                }
                num11 = bigInteger2.CompareTo(bigInteger);
                if (num11 > 0 || (num11 == 0 && (DblLo(dbl) & (true ? 1u : 0u)) != 0))
                {
                    dbl = BitConverter.Int64BitsToDouble(BitConverter.DoubleToInt64Bits(dbl) - 1);
                }
            }
            else
            {
                if (AddU(ref num7, u) != 0)
                {
                    AddU(ref num6, 1u);
                }
                bigInteger2.InitFromDigits(num7, num6, 1 + ((num6 != 0) ? 1 : 0));
                if (num5 > 0)
                {
                    bigInteger2.MulPow5(num5);
                }
                if (num4 > 0)
                {
                    bigInteger2.ShiftLeft(num4);
                }
                num11 = bigInteger2.CompareTo(bigInteger);
                if (num11 < 0 || (num11 == 0 && (DblLo(dbl) & (true ? 1u : 0u)) != 0))
                {
                    dbl = BitConverter.Int64BitsToDouble(BitConverter.DoubleToInt64Bits(dbl) + 1);
                }
            }
            return dbl;
        }
References System.Xml.Xsl.XPathConvert.FloatingDecimal._exponent, System.Xml.Xsl.XPathConvert.FloatingDecimal._mantissaSize, System.Xml.Xsl.XPathConvert.AddU(), System.Xml.Xsl.XPathConvert.DblHi(), System.Xml.Xsl.XPathConvert.DblLo(), System.Xml.Dictionary, System.BitConverter.DoubleToInt64Bits(), System.BitConverter.Int64BitsToDouble(), and System.Xml.L.