Terraria: System.Runtime.Serialization.SerializationInfo.AddValue
AddValue() [11/16]
void System.Runtime.Serialization.SerializationInfo.AddValue (string name, object? value, Type type) inline
Definition at line 153 of file SerializationInfo.cs.
    {
        if (name == null)
        {
            throw new ArgumentNullException("name");
        }
        if ((object)type == null)
        {
            throw new ArgumentNullException("type");
        }
        AddValueInternal(name, value, type);
    }
References System.Runtime.Serialization.SerializationInfo.AddValueInternal(), System.type, and System.value.
Referenced by System.Runtime.Serialization.SerializationInfo.AddValue(), System.Runtime.Serialization.SerializationInfo.AddValue(), System.Runtime.Serialization.SerializationInfo.AddValue(), System.Runtime.Serialization.SerializationInfo.AddValue(), System.Runtime.Serialization.SerializationInfo.AddValue(), System.Runtime.Serialization.SerializationInfo.AddValue(), System.Runtime.Serialization.SerializationInfo.AddValue(), System.Runtime.Serialization.SerializationInfo.AddValue(), System.Runtime.Serialization.SerializationInfo.AddValue(), System.Runtime.Serialization.SerializationInfo.AddValue(), System.Runtime.Serialization.SerializationInfo.AddValue(), System.Runtime.Serialization.SerializationInfo.AddValue(), System.Runtime.Serialization.SerializationInfo.AddValue(), System.Runtime.Serialization.SerializationInfo.AddValue(), and System.Runtime.Serialization.SerializationInfo.AddValue().