Terraria: System.Runtime.Serialization.SerializationInfo.AddValueInternal
AddValueInternal()
void System.Runtime.Serialization.SerializationInfo.AddValueInternal (string name, object value, Type type) inline package
Definition at line 252 of file SerializationInfo.cs.
    {
        if (!_nameToIndex.TryAdd(name, _count))
        {
            throw new SerializationException(SR.Serialization_SameNameTwice);
        }
        if (_count >= _names.Length)
        {
            ExpandArrays();
        }
        _names[_count] = name;
        _values[_count] = value;
        _types[_count] = type;
        _count++;
    }
References System.Runtime.Serialization.SerializationInfo._count, System.Runtime.Serialization.SerializationInfo._names, System.Runtime.Serialization.SerializationInfo._nameToIndex, System.Runtime.Serialization.SerializationInfo._types, System.Runtime.Serialization.SerializationInfo._values, System.Runtime.Serialization.SerializationInfo.ExpandArrays(), System.SR.Serialization_SameNameTwice, System.Collections.Generic.Dictionary< TKey, TValue >.TryAdd(), System.type, and System.value.
Referenced by System.Runtime.Serialization.SerializationInfo.AddValue(), and System.Runtime.Serialization.SerializationInfo.UpdateValue().