Terraria: System.Xml.Xsl.XPathConvert.FloatingDecimal.InitFromDouble
InitFromDouble()
void System.Xml.Xsl.XPathConvert.FloatingDecimal.InitFromDouble (double dbl) inline private
Definition at line 1609 of file XPathConvert.cs.
        {
            if (0.0 == dbl || IsSpecial(dbl))
            {
                _exponent = 0;
                _sign = 1;
                _mantissaSize = 0;
                return;
            }
            if (dbl < 0.0)
            {
                _sign = -1;
                dbl = 0.0 - dbl;
            }
            else
            {
                _sign = 1;
            }
            if (!BigNumber.DblToRgbFast(dbl, _mantissa, out _exponent, out _mantissaSize))
            {
                BigNumber.DblToRgbPrecise(dbl, _mantissa, out _exponent, out _mantissaSize);
            }
        }
References System.Xml.Xsl.XPathConvert.FloatingDecimal._exponent, System.Xml.Xsl.XPathConvert.FloatingDecimal._mantissa, System.Xml.Xsl.XPathConvert.FloatingDecimal._mantissaSize, System.Xml.Xsl.XPathConvert.FloatingDecimal._sign, System.Xml.Xsl.XPathConvert.BigNumber.DblToRgbFast(), System.Xml.Xsl.XPathConvert.BigNumber.DblToRgbPrecise(), System.Xml.Dictionary, and System.Xml.Xsl.XPathConvert.IsSpecial().
Referenced by System.Xml.Xsl.XPathConvert.FloatingDecimal.FloatingDecimal().