Terraria: System.Runtime.Serialization.SerializationInfo.GetValue
GetValue()
object? System.Runtime.Serialization.SerializationInfo.GetValue (string name, Type type) inline
Definition at line 316 of file SerializationInfo.cs.
    {
        if ((object)type == null)
        {
            throw new ArgumentNullException("type");
        }
        if (!type.IsRuntimeImplemented())
        {
            throw new ArgumentException(SR.Argument_MustBeRuntimeType);
        }
        Type foundType;
        object element = GetElement(name, out foundType);
        if ((object)foundType == type || type.IsAssignableFrom(foundType) || element == null)
        {
            return element;
        }
        return _converter.Convert(element, type);
    }
References System.Runtime.Serialization.SerializationInfo._converter, System.SR.Argument_MustBeRuntimeType, System.Runtime.Serialization.IFormatterConverter.Convert(), System.Runtime.Serialization.Dictionary, System.Runtime.Serialization.SerializationInfo.GetElement(), and System.type.
Referenced by System.Collections.Specialized.OrderedDictionary.OnDeserialization(), System.Collections.Generic.LinkedList< T >.OnDeserialization(), and System.Collections.Generic.SortedSet< T >.OnDeserialization().