Terraria: System.IO.Compression.CheckSumAndSizeWriteStream.WriteAsync
WriteAsync() [3/3]
override ValueTask System.IO.Compression.CheckSumAndSizeWriteStream.WriteAsync (ReadOnlyMemory< byte > buffer, CancellationToken cancellationToken = default(CancellationToken)) inline virtual
Reimplemented from System.IO.Stream.
Definition at line 147 of file CheckSumAndSizeWriteStream.cs.
    {
        ThrowIfDisposed();
        if (buffer.IsEmpty)
        {
            return default(ValueTask);
        }
        return Core(buffer, cancellationToken);
        async ValueTask Core(ReadOnlyMemory<byte> buffer, CancellationToken cancellationToken = default(CancellationToken))
        {
            if (!_everWritten)
            {
                _initialPosition = _baseBaseStream.Position;
                _everWritten = true;
            }
            _checksum = Crc32Helper.UpdateCrc32(_checksum, buffer.Span);
            await _baseStream.WriteAsync(buffer, cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
            _position += buffer.Length;
        }
    }
References System.IO.Compression.CheckSumAndSizeWriteStream._baseBaseStream, System.IO.Compression.CheckSumAndSizeWriteStream._baseStream, System.IO.Compression.CheckSumAndSizeWriteStream._checksum, System.IO.Compression.CheckSumAndSizeWriteStream._everWritten, System.IO.Compression.CheckSumAndSizeWriteStream._initialPosition, System.IO.Compression.CheckSumAndSizeWriteStream._position, System.buffer, System.cancellationToken, System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.IO.Stream.Position, System.IO.Compression.CheckSumAndSizeWriteStream.ThrowIfDisposed(), System.IO.Compression.Crc32Helper.UpdateCrc32(), and System.IO.Stream.WriteAsync().