Terraria: System.IO.Compression.CheckSumAndSizeWriteStream.Write
Write() [2/2]
override void System.IO.Compression.CheckSumAndSizeWriteStream.Write (ReadOnlySpan< byte > source) inline virtual
Reimplemented from System.IO.Stream.
Definition at line 120 of file CheckSumAndSizeWriteStream.cs.
    {
        ThrowIfDisposed();
        if (source.Length != 0)
        {
            if (!_everWritten)
            {
                _initialPosition = _baseBaseStream.Position;
                _everWritten = true;
            }
            _checksum = Crc32Helper.UpdateCrc32(_checksum, source);
            _baseStream.Write(source);
            _position += source.Length;
        }
    }
References System.IO.Compression.CheckSumAndSizeWriteStream._baseBaseStream, System.IO.Compression.CheckSumAndSizeWriteStream._baseStream, System.IO.Compression.CheckSumAndSizeWriteStream._checksum, System.IO.Compression.CheckSumAndSizeWriteStream._everWritten, System.IO.Compression.CheckSumAndSizeWriteStream._initialPosition, System.IO.Compression.CheckSumAndSizeWriteStream._position, System.IO.Stream.Position, System.source, System.IO.Compression.CheckSumAndSizeWriteStream.ThrowIfDisposed(), System.IO.Compression.Crc32Helper.UpdateCrc32(), and System.IO.Stream.Write().