Terraria: System.IO.Compression.CheckSumAndSizeWriteStream.Write
Write() [1/2]
override void System.IO.Compression.CheckSumAndSizeWriteStream.Write (byte[] buffer, int offset, int count) inline
Definition at line 103 of file CheckSumAndSizeWriteStream.cs.
    {
        Stream.ValidateBufferArguments(buffer, offset, count);
        ThrowIfDisposed();
        if (count != 0)
        {
            if (!_everWritten)
            {
                _initialPosition = _baseBaseStream.Position;
                _everWritten = true;
            }
            _checksum = Crc32Helper.UpdateCrc32(_checksum, buffer, offset, count);
            _baseStream.Write(buffer, offset, count);
            _position += count;
        }
    }
References System.IO.Compression.CheckSumAndSizeWriteStream._baseBaseStream, System.IO.Compression.CheckSumAndSizeWriteStream._baseStream, System.IO.Compression.CheckSumAndSizeWriteStream._checksum, System.IO.Compression.CheckSumAndSizeWriteStream._everWritten, System.IO.Compression.CheckSumAndSizeWriteStream._initialPosition, System.IO.Compression.CheckSumAndSizeWriteStream._position, System.buffer, System.count, System.offset, System.IO.Stream.Position, System.IO.Compression.CheckSumAndSizeWriteStream.ThrowIfDisposed(), System.IO.Compression.Crc32Helper.UpdateCrc32(), System.IO.Stream.ValidateBufferArguments(), and System.IO.Stream.Write().
Referenced by System.IO.Compression.ZipArchiveEntry.DirectToArchiveWriterStream.Write(), and System.IO.Compression.ZipArchiveEntry.DirectToArchiveWriterStream.Write().