Terraria: System.Net.TimerThread.TimerNode.Fire
Fire()
bool System.Net.TimerThread.TimerNode.Fire () inline package
Definition at line 244 of file TimerThread.cs.
        {
            if (_timerState == TimerState.Sentinel && System.Net.NetEventSource.Log.IsEnabled())
            {
                System.Net.NetEventSource.Info(this, "TimerQueue tried to Fire a Sentinel.", "Fire");
            }
            if (_timerState != 0)
            {
                return true;
            }
            int tickCount = Environment.TickCount;
            if (IsTickBetween(base.StartTime, base.Expiration, tickCount))
            {
                if (System.Net.NetEventSource.Log.IsEnabled())
                {
                    System.Net.NetEventSource.Info(this, $"TimerThreadTimer#{base.StartTime}::Fire() Not firing ({base.StartTime} <= {tickCount} < {base.Expiration})", "Fire");
                }
                return false;
            }
            bool flag = false;
            lock (_queueLock)
            {
                if (_timerState == TimerState.Ready)
                {
                    if (System.Net.NetEventSource.Log.IsEnabled())
                    {
                        System.Net.NetEventSource.Info(this, $"TimerThreadTimer#{base.StartTime}::Fire() Firing ({base.StartTime} <= {tickCount} >= " + base.Expiration + ")", "Fire");
                    }
                    _timerState = TimerState.Fired;
                    Next.Prev = Prev;
                    Prev.Next = Next;
                    Next = null;
                    Prev = null;
                    flag = _callback != null;
                }
            }
            if (flag)
            {
                try
                {
                    Callback callback = _callback;
                    object context = _context;
                    _callback = null;
                    _context = null;
                    callback(this, tickCount, context);
                }
                catch (Exception ex)
                {
                    if (System.Net.ExceptionCheck.IsFatal(ex))
                    {
                        throw;
                    }
                    if (System.Net.NetEventSource.Log.IsEnabled())
                    {
                        System.Net.NetEventSource.Error(this, $"exception in callback: {ex}", "Fire");
                    }
                }
            }
            return true;
        }
References System.Net.TimerThread.TimerNode._callback, System.Net.TimerThread.TimerNode._context, System.Net.TimerThread.TimerNode._queueLock, System.Net.TimerThread.TimerNode._timerState, System.Net.NetEventSource.Error(), System.Net.NetEventSource.Info(), System.Net.ExceptionCheck.IsFatal(), System.Net.TimerThread.IsTickBetween(), System.Net.NetEventSource.Log, System.Net.TimerThread.TimerNode.Next, System.Net.TimerThread.TimerNode.Prev, and System.Environment.TickCount.
Referenced by System.Net.TimerThread.TimerQueue.Fire().