Terraria: System.Diagnostics.Metrics.ExponentialHistogramAggregator.Collect
Collect()
override IAggregationStatistics System.Diagnostics.Metrics.ExponentialHistogramAggregator.Collect () inline
Definition at line 46 of file ExponentialHistogramAggregator.cs.
    {
        int[][] counters;
        int count;
        lock (this)
        {
            counters = _counters;
            count = _count;
            _counters = new int[4096][];
            _count = 0;
        }
        QuantileValue[] array = new QuantileValue[_config.Quantiles.Length];
        int num = 0;
        if (num == _config.Quantiles.Length)
        {
            return new HistogramStatistics(array);
        }
        count -= GetInvalidCount(counters);
        int num2 = QuantileToRank(_config.Quantiles[num], count);
        int num3 = 0;
        foreach (Bucket item in IterateBuckets(counters))
        {
            num3 += item.Count;
            while (num3 > num2)
            {
                array[num] = new QuantileValue(_config.Quantiles[num], item.Value);
                num++;
                if (num == _config.Quantiles.Length)
                {
                    return new HistogramStatistics(array);
                }
                num2 = QuantileToRank(_config.Quantiles[num], count);
            }
        }
        return new HistogramStatistics(Array.Empty<QuantileValue>());
    }
References System.Diagnostics.Metrics.ExponentialHistogramAggregator._config, System.Diagnostics.Metrics.ExponentialHistogramAggregator._count, System.Diagnostics.Metrics.ExponentialHistogramAggregator._counters, System.array, System.count, System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Diagnostics.Metrics.ExponentialHistogramAggregator.GetInvalidCount(), System.item, System.Diagnostics.Metrics.ExponentialHistogramAggregator.IterateBuckets(), System.Diagnostics.Metrics.QuantileAggregation.Quantiles, and System.Diagnostics.Metrics.ExponentialHistogramAggregator.QuantileToRank().