Terraria: System.Runtime.InteropServices.COMException.ToString
ToString()
override string System.Runtime.InteropServices.COMException.ToString () inline
Definition at line 40 of file COMException.cs.
    {
        StringBuilder stringBuilder = new StringBuilder();
        StringBuilder stringBuilder2 = stringBuilder;
        StringBuilder.AppendInterpolatedStringHandler handler = new StringBuilder.AppendInterpolatedStringHandler(5, 2, stringBuilder2);
        handler.AppendFormatted(GetType());
        handler.AppendLiteral(" (0x");
        handler.AppendFormatted(base.HResult, "X8");
        handler.AppendLiteral(")");
        stringBuilder2.Append(ref handler);
        string message = Message;
        if (!string.IsNullOrEmpty(message))
        {
            stringBuilder.Append(": ").Append(message);
        }
        Exception innerException = base.InnerException;
        if (innerException != null)
        {
            stringBuilder.Append("\r\n ---> ").Append(innerException.ToString());
        }
        string stackTrace = StackTrace;
        if (stackTrace != null)
        {
            stringBuilder.AppendLine().Append(stackTrace);
        }
        return stringBuilder.ToString();
    }
References System.Text.StringBuilder.AppendInterpolatedStringHandler.AppendFormatted(), System.Text.StringBuilder.AppendInterpolatedStringHandler.AppendLiteral(), System.Runtime.Serialization.Dictionary, System.Exception.GetType(), System.Exception.InnerException, System.Exception.Message, and System.Exception.StackTrace.