Terraria: System.Net.Http.WinInetProxyHelper.GetProxyForUrl
GetProxyForUrl()
bool System.Net.Http.WinInetProxyHelper.GetProxyForUrl (global::Interop::WinHttp::SafeWinHttpHandle sessionHandle, Uri uri, out global::Interop::WinHttp::WINHTTP_PROXY_INFO proxyInfo) inline
Definition at line 106 of file WinInetProxyHelper.cs.
    {
        proxyInfo.AccessType = 1u;
        proxyInfo.Proxy = IntPtr.Zero;
        proxyInfo.ProxyBypass = IntPtr.Zero;
        if (!_useProxy)
        {
            return false;
        }
        bool flag = false;
        Unsafe.SkipInit(out global::Interop.WinHttp.WINHTTP_AUTOPROXY_OPTIONS autoProxyOptions);
        autoProxyOptions.AutoConfigUrl = AutoConfigUrl;
        autoProxyOptions.AutoDetectFlags = (AutoDetect ? 3u : 0u);
        autoProxyOptions.AutoLoginIfChallenged = false;
        autoProxyOptions.Flags = (AutoDetect ? 1u : 0u) | ((!string.IsNullOrEmpty(AutoConfigUrl)) ? 2u : 0u);
        autoProxyOptions.Reserved1 = IntPtr.Zero;
        autoProxyOptions.Reserved2 = 0u;
        string text = uri.AbsoluteUri;
        if (uri.Scheme == "wss")
        {
            text = "https" + text.Substring("wss".Length);
        }
        else if (uri.Scheme == "ws")
        {
            text = "http" + text.Substring("ws".Length);
        }
        bool flag2 = false;
        do
        {
            _autoDetectionFailed = false;
            if (global::Interop.WinHttp.WinHttpGetProxyForUrl(sessionHandle, text, ref autoProxyOptions, out proxyInfo))
            {
                if (System.Net.NetEventSource.Log.IsEnabled())
                {
                    System.Net.NetEventSource.Info(this, "Using autoconfig proxy settings", "GetProxyForUrl");
                }
                flag = true;
                break;
            }
            int lastWin32Error = Marshal.GetLastWin32Error();
            if (System.Net.NetEventSource.Log.IsEnabled())
            {
                System.Net.NetEventSource.Error(this, $"error={lastWin32Error}", "GetProxyForUrl");
            }
            if ((long)lastWin32Error == 12015)
            {
                if (flag2)
                {
                    break;
                }
                flag2 = true;
                autoProxyOptions.AutoLoginIfChallenged = true;
                continue;
            }
            if ((long)lastWin32Error == 12180)
            {
                _autoDetectionFailed = true;
                _lastTimeAutoDetectionFailed = Environment.TickCount;
            }
            break;
        }
        while (flag2);
        if (!flag && !string.IsNullOrEmpty(Proxy))
        {
            proxyInfo.AccessType = 3u;
            proxyInfo.Proxy = Marshal.StringToHGlobalUni(Proxy);
            proxyInfo.ProxyBypass = (string.IsNullOrEmpty(ProxyBypass) ? IntPtr.Zero : Marshal.StringToHGlobalUni(ProxyBypass));
            if (System.Net.NetEventSource.Log.IsEnabled())
            {
                System.Net.NetEventSource.Info(this, $"Fallback to Proxy={Proxy}, ProxyBypass={ProxyBypass}", "GetProxyForUrl");
            }
            flag = true;
        }
        if (System.Net.NetEventSource.Log.IsEnabled())
        {
            System.Net.NetEventSource.Info(this, $"useProxy={flag}", "GetProxyForUrl");
        }
        return flag;
    }
References System.Net.Http.WinInetProxyHelper._autoDetectionFailed, System.Net.Http.WinInetProxyHelper._lastTimeAutoDetectionFailed, System.Net.Http.WinInetProxyHelper._useProxy, System.Uri.AbsoluteUri, System.Net.Http.WinInetProxyHelper.AutoConfigUrl, System.Net.Http.WinInetProxyHelper.AutoDetect, System.Net.NetEventSource.Error(), System.Runtime.InteropServices.Marshal.GetLastWin32Error(), System.Net.NetEventSource.Info(), System.Net.NetEventSource.Log, System.Net.Http.WinInetProxyHelper.Proxy, System.Net.Http.WinInetProxyHelper.ProxyBypass, System.Uri.Scheme, System.Runtime.InteropServices.Marshal.StringToHGlobalUni(), System.text, System.Environment.TickCount, and System.IntPtr.Zero.
Referenced by System.Net.Http.HttpWindowsProxy.GetMultiProxy().