Terraria: System.Net.Http.WinInetProxyHelper.WinInetProxyHelper
WinInetProxyHelper()
System.Net.Http.WinInetProxyHelper.WinInetProxyHelper () inline
Definition at line 68 of file WinInetProxyHelper.cs.
    {
        global::Interop.WinHttp.WINHTTP_CURRENT_USER_IE_PROXY_CONFIG proxyConfig = default(global::Interop.WinHttp.WINHTTP_CURRENT_USER_IE_PROXY_CONFIG);
        try
        {
            if (global::Interop.WinHttp.WinHttpGetIEProxyConfigForCurrentUser(out proxyConfig))
            {
                _autoConfigUrl = Marshal.PtrToStringUni(proxyConfig.AutoConfigUrl);
                _autoDetect = proxyConfig.AutoDetect;
                _proxy = Marshal.PtrToStringUni(proxyConfig.Proxy);
                _proxyBypass = Marshal.PtrToStringUni(proxyConfig.ProxyBypass);
                if (System.Net.NetEventSource.Log.IsEnabled())
                {
                    System.Net.NetEventSource.Info(this, $"AutoConfigUrl={AutoConfigUrl}, AutoDetect={AutoDetect}, Proxy={Proxy}, ProxyBypass={ProxyBypass}", ".ctor");
                }
                _useProxy = true;
            }
            else
            {
                int lastWin32Error = Marshal.GetLastWin32Error();
                if (System.Net.NetEventSource.Log.IsEnabled())
                {
                    System.Net.NetEventSource.Error(this, $"error={lastWin32Error}", ".ctor");
                }
            }
            if (System.Net.NetEventSource.Log.IsEnabled())
            {
                System.Net.NetEventSource.Info(this, $"_useProxy={_useProxy}", ".ctor");
            }
        }
        finally
        {
            Marshal.FreeHGlobal(proxyConfig.AutoConfigUrl);
            Marshal.FreeHGlobal(proxyConfig.Proxy);
            Marshal.FreeHGlobal(proxyConfig.ProxyBypass);
        }
    }
References System.Net.Http.WinInetProxyHelper._autoConfigUrl, System.Net.Http.WinInetProxyHelper._autoDetect, System.Net.Http.WinInetProxyHelper._proxy, System.Net.Http.WinInetProxyHelper._proxyBypass, System.Net.Http.WinInetProxyHelper._useProxy, System.Net.NetEventSource.Error(), System.Runtime.InteropServices.Marshal.FreeHGlobal(), System.Runtime.InteropServices.Marshal.GetLastWin32Error(), System.Net.NetEventSource.Info(), System.Net.NetEventSource.Log, and System.Runtime.InteropServices.Marshal.PtrToStringUni().