Terraria: System.Xml.Schema.XmlSchemaObjectTable.Add
Add()
void System.Xml.Schema.XmlSchemaObjectTable.Add (XmlQualifiedName name, XmlSchemaObject value) inline package
Definition at line 256 of file XmlSchemaObjectTable.cs.
    {
        _table.Add(name, value);
        _entries.Add(new XmlSchemaObjectEntry(name, value));
    }
References System.Xml.Schema.XmlSchemaObjectTable._entries, System.Xml.Schema.XmlSchemaObjectTable._table, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), and System.value.
Referenced by System.Xml.Schema.BaseProcessor.AddToTable(), System.Xml.Schema.XmlSchemaSet.AddToTable(), System.Xml.Schema.SchemaCollectionCompiler.Prepare(), System.Xml.Schema.Preprocessor.PreprocessIdentityConstraint(), System.Xml.Schema.SchemaCollectionPreprocessor.PreprocessIdentityConstraint(), and System.Xml.Schema.Compiler.ProcessSubstitutionGroups().