Terraria: System.Xml.Schema.XmlSchemaObjectTable.Insert
Insert()
void System.Xml.Schema.XmlSchemaObjectTable.Insert (XmlQualifiedName name, XmlSchemaObject value) inline package
Definition at line 262 of file XmlSchemaObjectTable.cs.
    {
        XmlSchemaObject value2 = null;
        if (_table.TryGetValue(name, out value2))
        {
            _table[name] = value;
            int index = FindIndexByValue(value2);
            _entries[index] = new XmlSchemaObjectEntry(name, value);
        }
        else
        {
            Add(name, value);
        }
    }
References System.Xml.Schema.XmlSchemaObjectTable._entries, System.Xml.Schema.XmlSchemaObjectTable._table, System.Add, System.Xml.Schema.XmlSchemaObjectTable.FindIndexByValue(), System.index, System.Collections.Generic.Dictionary< TKey, TValue >.TryGetValue(), and System.value.
Referenced by System.Xml.Schema.BaseProcessor.AddToTable(), System.Xml.Schema.XmlSchemaSet.AddToTable(), System.Xml.Schema.Compiler.Compile(), System.Xml.Schema.SchemaCollectionCompiler.Compile(), System.Xml.Schema.BaseProcessor.IsValidAttributeGroupRedefine(), System.Xml.Schema.BaseProcessor.IsValidGroupRedefine(), System.Xml.Schema.BaseProcessor.IsValidTypeRedefine(), and System.Xml.Schema.Preprocessor.PreprocessRedefine().