Terraria: System.Xml.Schema.XmlSchemaObjectTable.Remove
Remove()
void System.Xml.Schema.XmlSchemaObjectTable.Remove (XmlQualifiedName name) inline package
Definition at line 293 of file XmlSchemaObjectTable.cs.
    {
        if (_table.TryGetValue(name, out var value))
        {
            _table.Remove(name);
            int index = FindIndexByValue(value);
            _entries.RemoveAt(index);
        }
    }
References System.Xml.Schema.XmlSchemaObjectTable._entries, System.Xml.Schema.XmlSchemaObjectTable._table, System.Xml.Schema.XmlSchemaObjectTable.FindIndexByValue(), System.index, System.Collections.Generic.Dictionary< TKey, TValue >.Remove(), System.Collections.Generic.Dictionary< TKey, TValue >.TryGetValue(), and System.value.
Referenced by System.Xml.Schema.SchemaCollectionCompiler.Compile(), System.Xml.Schema.XmlSchemaSet.CopyFromCompiledSet(), and System.Xml.Schema.XmlSchemaSet.RemoveSchemaFromGlobalTables().