Terraria: MartianSaucerBigProgressBar.ValidateAndCollectNecessaryInfo
ValidateAndCollectNecessaryInfo()
bool MartianSaucerBigProgressBar.ValidateAndCollectNecessaryInfo (ref BigProgressBarInfo info) inline
Implements IBigProgressBar.
     {
         if (info.npcIndexToAimAt < 0 || info.npcIndexToAimAt > 200)
         {
             return false;
         }
         NPC nPC = Main.npc[info.npcIndexToAimAt];
         if (!nPC.active || nPC.type != 395)
         {
             if (!TryFindingAnotherMartianSaucerPiece(ref info))
             {
                 return false;
             }
             nPC = Main.npc[info.npcIndexToAimAt];
         }
         int num = 0;
         if (Main.expertMode)
         {
             _referenceDummy.SetDefaults(395, nPC.GetMatchingSpawnParams());
             num += _referenceDummy.lifeMax;
         }
         _referenceDummy.SetDefaults(394, nPC.GetMatchingSpawnParams());
         num += _referenceDummy.lifeMax * 2;
         _referenceDummy.SetDefaults(393, nPC.GetMatchingSpawnParams());
         num += _referenceDummy.lifeMax * 2;
         float num2 = 0f;
         for (int i = 0; i < 200; i++)
         {
             NPC nPC2 = Main.npc[i];
             if (nPC2.active && ValidIdsToScanHp.Contains(nPC2.type) && (Main.expertMode || nPC2.type != 395))
             {
                 num2 += (float)nPC2.life;
             }
         }
         _cache.SetLife(num2, num);
         return true;
     }
References _cache, _referenceDummy, Entity.active, Main.expertMode, NPC.GetMatchingSpawnParams(), NPC.life, NPC.lifeMax, Main.npc, NPC.SetDefaults(), BigProgressBarCache.SetLife(), TryFindingAnotherMartianSaucerPiece(), NPC.type, and ValidIdsToScanHp.