Terraria: Microsoft.Xna.Framework.Graphics.SkinnedEffect.OnApply
OnApply()
override void Microsoft.Xna.Framework.Graphics.SkinnedEffect.OnApply () inline package virtual
Reimplemented from Microsoft.Xna.Framework.Graphics.Effect.
Definition at line 411 of file SkinnedEffect.cs.
    {
        dirtyFlags = EffectHelpers.SetWorldViewProjAndFog(dirtyFlags, ref world, ref view, ref projection, ref worldView, fogEnabled, fogStart, fogEnd, worldViewProjParam, fogVectorParam);
        dirtyFlags = EffectHelpers.SetLightingMatrices(dirtyFlags, ref world, ref view, worldParam, worldInverseTransposeParam, eyePositionParam);
        if ((dirtyFlags & EffectDirtyFlags.MaterialColor) != 0)
        {
            EffectHelpers.SetMaterialColor(lightingEnabled: true, alpha, ref diffuseColor, ref emissiveColor, ref ambientLightColor, diffuseColorParam, emissiveColorParam);
            dirtyFlags &= ~EffectDirtyFlags.MaterialColor;
        }
        bool flag = !light1.Enabled && !light2.Enabled;
        if (oneLight != flag)
        {
            oneLight = flag;
            dirtyFlags |= EffectDirtyFlags.ShaderIndex;
        }
        if ((dirtyFlags & EffectDirtyFlags.ShaderIndex) != 0)
        {
            int num = 0;
            if (!fogEnabled)
            {
                num++;
            }
            if (weightsPerVertex == 2)
            {
                num += 2;
            }
            else if (weightsPerVertex == 4)
            {
                num += 4;
            }
            if (preferPerPixelLighting)
            {
                num += 12;
            }
            else if (oneLight)
            {
                num += 6;
            }
            shaderIndexParam.SetValue(num);
            dirtyFlags &= ~EffectDirtyFlags.ShaderIndex;
        }
    }
References Microsoft.Xna.Framework.Graphics.SkinnedEffect.alpha, Microsoft.Xna.Framework.Graphics.SkinnedEffect.ambientLightColor, Microsoft.Xna.Framework.Graphics.SkinnedEffect.diffuseColor, Microsoft.Xna.Framework.Graphics.SkinnedEffect.diffuseColorParam, Microsoft.Xna.Framework.Graphics.SkinnedEffect.dirtyFlags, Microsoft.Xna.Framework.Graphics.SkinnedEffect.emissiveColor, Microsoft.Xna.Framework.Graphics.SkinnedEffect.emissiveColorParam, Microsoft.Xna.Framework.Graphics.DirectionalLight.Enabled, Microsoft.Xna.Framework.Graphics.SkinnedEffect.eyePositionParam, Microsoft.Xna.Framework.Graphics.SkinnedEffect.fogEnabled, Microsoft.Xna.Framework.Graphics.SkinnedEffect.fogEnd, Microsoft.Xna.Framework.Graphics.SkinnedEffect.fogStart, Microsoft.Xna.Framework.Graphics.SkinnedEffect.fogVectorParam, Microsoft.Xna.Framework.Graphics.SkinnedEffect.light2, Microsoft.Xna.Framework.Graphics.SkinnedEffect.oneLight, Microsoft.Xna.Framework.Graphics.SkinnedEffect.preferPerPixelLighting, Microsoft.Xna.Framework.Graphics.SkinnedEffect.projection, Microsoft.Xna.Framework.Graphics.EffectHelpers.SetLightingMatrices(), Microsoft.Xna.Framework.Graphics.EffectHelpers.SetMaterialColor(), Microsoft.Xna.Framework.Graphics.EffectParameter.SetValue(), Microsoft.Xna.Framework.Graphics.EffectHelpers.SetWorldViewProjAndFog(), Microsoft.Xna.Framework.Graphics.SkinnedEffect.shaderIndexParam, Microsoft.Xna.Framework.Graphics.SkinnedEffect.view, Microsoft.Xna.Framework.Graphics.SkinnedEffect.weightsPerVertex, Microsoft.Xna.Framework.Graphics.SkinnedEffect.world, Microsoft.Xna.Framework.Graphics.SkinnedEffect.worldInverseTransposeParam, Microsoft.Xna.Framework.Graphics.SkinnedEffect.worldParam, Microsoft.Xna.Framework.Graphics.SkinnedEffect.worldView, and Microsoft.Xna.Framework.Graphics.SkinnedEffect.worldViewProjParam.