Terraria: Microsoft.Xna.Framework.Graphics.SkinnedEffect.SkinnedEffect
SkinnedEffect() [1/2]
Microsoft.Xna.Framework.Graphics.SkinnedEffect.SkinnedEffect (GraphicsDevice device) inline
Definition at line 338 of file SkinnedEffect.cs.
        : base(device, SkinnedEffectCode.Code)
    {
        CacheEffectParameters(null);
        DirectionalLight0.Enabled = true;
        SpecularColor = Vector3.One;
        SpecularPower = 16f;
        Matrix[] array = new Matrix[72];
        for (int i = 0; i < 72; i++)
        {
            ref Matrix reference = ref array[i];
            reference = Matrix.Identity;
        }
        SetBoneTransforms(array);
    }
References System.array, Microsoft.Xna.Framework.Graphics.SkinnedEffect.CacheEffectParameters(), Microsoft.Xna.Framework.Matrix.Identity, Microsoft.Xna.Framework.Vector3.One, Microsoft.Xna.Framework.Graphics.SkinnedEffect.SetBoneTransforms(), Microsoft.Xna.Framework.Graphics.SkinnedEffect.SpecularColor, and Microsoft.Xna.Framework.Graphics.SkinnedEffect.SpecularPower.
Referenced by Microsoft.Xna.Framework.Graphics.SkinnedEffect.Clone().