Terraria: SkyShader.ProcessAnyDetail
ProcessAnyDetail()
void SkyShader.ProcessAnyDetail (RgbDevice device, Fragment fragment, EffectDetailLevel quality, float time) inline private
     {
         for (int i = 0; i < fragment.Count; i++)
         {
             Vector2 canvasPositionOfIndex = fragment.GetCanvasPositionOfIndex(i);
             Point gridPositionOfIndex = fragment.GetGridPositionOfIndex(i);
             float dynamicNoise = NoiseHelper.GetDynamicNoise(canvasPositionOfIndex * new Vector2(0.1f, 0.5f) + new Vector2(time * 0.05f, 0f), time / 20f);
             dynamicNoise = (float)Math.Sqrt(Math.Max(0f, 1f - 2f * dynamicNoise));
             Vector4 value = Vector4.Lerp(_processedSkyColor, _processedCloudColor, dynamicNoise);
             value = Vector4.Lerp(_baseSpaceColor, value, _backgroundTransition);
             float dynamicNoise2 = NoiseHelper.GetDynamicNoise(gridPositionOfIndex.X, gridPositionOfIndex.Y, time / 60f);
             dynamicNoise2 = Math.Max(0f, 1f - dynamicNoise2 * 20f);
             value = Vector4.Lerp(value, Vector4.One, dynamicNoise2 * 0.98f * _starVisibility);
             fragment.SetColor(i, value);
         }
     }
References _backgroundTransition, _baseSpaceColor, _processedCloudColor, _processedSkyColor, _starVisibility, Fragment.Count, Fragment.GetCanvasPositionOfIndex(), NoiseHelper.GetDynamicNoise(), Fragment.GetGridPositionOfIndex(), and Fragment.SetColor().