Terraria: System.Net.HttpRequestStream.ReadCore
ReadCore()
unsafe int System.Net.HttpRequestStream.ReadCore (byte[] buffer, int offset, int size) inline private
Definition at line 221 of file HttpRequestStream.cs.
    {
        uint num = 0u;
        if (_dataChunkIndex != -1)
        {
            num = global::Interop.HttpApi.GetChunks(_httpContext.Request.RequestBuffer, _httpContext.Request.OriginalBlobAddress, ref _dataChunkIndex, ref _dataChunkOffset, buffer, offset, size);
        }
        if (_dataChunkIndex == -1 && num < size)
        {
            if (System.Net.NetEventSource.Log.IsEnabled())
            {
                System.Net.NetEventSource.Info(this, "size:" + size + " offset:" + offset, "ReadCore");
            }
            uint num2 = 0u;
            uint bytesReturned = 0u;
            offset += (int)num;
            size -= (int)num;
            if (size > 131072)
            {
                size = 131072;
            }
            fixed (byte* ptr = buffer)
            {
                if (System.Net.NetEventSource.Log.IsEnabled())
                {
                    System.Net.NetEventSource.Info(this, "Calling Interop.HttpApi.HttpReceiveRequestEntityBody", "ReadCore");
                }
                uint flags = 0u;
                if (!_inOpaqueMode)
                {
                    flags = 1u;
                }
                num2 = global::Interop.HttpApi.HttpReceiveRequestEntityBody(_httpContext.RequestQueueHandle, _httpContext.RequestId, flags, ptr + offset, (uint)size, out bytesReturned, null);
                num += bytesReturned;
                if (System.Net.NetEventSource.Log.IsEnabled())
                {
                    System.Net.NetEventSource.Info(this, "Call to Interop.HttpApi.HttpReceiveRequestEntityBody returned:" + num2 + " dataRead:" + num, "ReadCore");
                }
            }
            if (num2 != 0 && num2 != 38)
            {
                Exception ex = new HttpListenerException((int)num2);
                if (System.Net.NetEventSource.Log.IsEnabled())
                {
                    System.Net.NetEventSource.Error(this, ex.ToString(), "ReadCore");
                }
                throw ex;
            }
            UpdateAfterRead(num2, num);
        }
        if (System.Net.NetEventSource.Log.IsEnabled())
        {
            System.Net.NetEventSource.DumpBuffer(this, buffer, offset, (int)num, "ReadCore");
            System.Net.NetEventSource.Info(this, "returning dataRead:" + num, "ReadCore");
        }
        return (int)num;
    }
References System.Net.HttpRequestStream._dataChunkIndex, System.Net.HttpRequestStream._dataChunkOffset, System.Net.HttpRequestStream._httpContext, System.Net.HttpRequestStream._inOpaqueMode, System.buffer, System.Net.NetEventSource.DumpBuffer(), System.Net.NetEventSource.Error(), System.Net.NetEventSource.Info(), System.Net.NetEventSource.Log, System.offset, System.Net.HttpListenerRequest.OriginalBlobAddress, System.Net.HttpListenerContext.Request, System.Net.HttpListenerRequest.RequestBuffer, System.Net.HttpListenerContext.RequestId, System.Net.HttpListenerContext.RequestQueueHandle, System.Exception.ToString(), and System.Net.HttpRequestStream.UpdateAfterRead().
Referenced by System.Net.HttpRequestStream.Read().