Terraria: Microsoft.Xna.Framework.Vector3.Cross
Cross() [2/2]
static Vector3 Microsoft.Xna.Framework.Vector3.Cross (Vector3 vector1, Vector3 vector2) inline static
Definition at line 204 of file Vector3.cs.
    {
        Vector3 result = default(Vector3);
        result.X = vector1.Y * vector2.Z - vector1.Z * vector2.Y;
        result.Y = vector1.Z * vector2.X - vector1.X * vector2.Z;
        result.Z = vector1.X * vector2.Y - vector1.Y * vector2.X;
        return result;
    }
References Microsoft.Xna.Framework.Vector3.X, Microsoft.Xna.Framework.Vector3.Y, and Microsoft.Xna.Framework.Vector3.Z.
Referenced by Microsoft.Xna.Framework.BoundingFrustum.ComputeIntersectionLine(), Microsoft.Xna.Framework.Matrix.CreateBillboard(), Microsoft.Xna.Framework.Matrix.CreateBillboard(), Microsoft.Xna.Framework.Matrix.CreateConstrainedBillboard(), Microsoft.Xna.Framework.Matrix.CreateConstrainedBillboard(), Microsoft.Xna.Framework.Matrix.CreateLookAt(), Microsoft.Xna.Framework.Matrix.CreateLookAt(), Microsoft.Xna.Framework.Matrix.CreateWorld(), Microsoft.Xna.Framework.Matrix.CreateWorld(), and Microsoft.Xna.Framework.Matrix.Decompose().