Terraria: Microsoft.Xna.Framework.Vector3.Clamp
Clamp() [2/2]
static Vector3 Microsoft.Xna.Framework.Vector3.Clamp (Vector3 value1, Vector3 min, Vector3 max) inline static
Definition at line 273 of file Vector3.cs.
    {
        float x = value1.X;
        x = ((x > max.X) ? max.X : x);
        x = ((x < min.X) ? min.X : x);
        float y = value1.Y;
        y = ((y > max.Y) ? max.Y : y);
        y = ((y < min.Y) ? min.Y : y);
        float z = value1.Z;
        z = ((z > max.Z) ? max.Z : z);
        z = ((z < min.Z) ? min.Z : z);
        Vector3 result = default(Vector3);
        result.X = x;
        result.Y = y;
        result.Z = z;
        return result;
    }
References Microsoft.Xna.Framework.Vector3.X, Microsoft.Xna.Framework.Vector3.Y, and Microsoft.Xna.Framework.Vector3.Z.
Referenced by Microsoft.Xna.Framework.BoundingBox.Contains(), Microsoft.Xna.Framework.BoundingBox.Contains(), Microsoft.Xna.Framework.BoundingSphere.Intersects(), Microsoft.Xna.Framework.BoundingBox.Intersects(), Microsoft.Xna.Framework.BoundingSphere.Intersects(), Microsoft.Xna.Framework.BoundingBox.Intersects(), Terraria.Initializers.UILinksInitializer.Load(), and Terraria.GameContent.UI.States.UICharacterCreation.RgbToScaledHsl().