Terraria: Microsoft.Xna.Framework.Vector3.Dot
Dot() [2/2]
static float Microsoft.Xna.Framework.Vector3.Dot (Vector3 vector1, Vector3 vector2) inline static
Definition at line 165 of file Vector3.cs.
    {
        return vector1.X * vector2.X + vector1.Y * vector2.Y + vector1.Z * vector2.Z;
    }
References Microsoft.Xna.Framework.Vector3.Z.
Referenced by Microsoft.Xna.Framework.BoundingFrustum.ComputeIntersection(), Microsoft.Xna.Framework.Matrix.CreateConstrainedBillboard(), Microsoft.Xna.Framework.Matrix.CreateConstrainedBillboard(), Microsoft.Xna.Framework.Matrix.CreateLookAt(), Microsoft.Xna.Framework.Matrix.CreateLookAt(), Microsoft.Xna.Framework.BoundingFrustum.Intersects(), Microsoft.Xna.Framework.BoundingFrustum.Intersects(), Microsoft.Xna.Framework.BoundingFrustum.Intersects(), and Microsoft.Xna.Framework.BoundingFrustum.SupportMapping().