Terraria: System.Runtime.Serialization.DataContractSet.InternalAdd
InternalAdd()
void System.Runtime.Serialization.DataContractSet.InternalAdd (XmlQualifiedName name, DataContract dataContract) inline package
Definition at line 96 of file DataContractSet.cs.
    {
        DataContract value = null;
        if (Contracts.TryGetValue(name, out value))
        {
            if (!value.Equals(dataContract))
            {
                if (dataContract.UnderlyingType == null || value.UnderlyingType == null)
                {
                    throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new InvalidOperationException(System.SR.Format(System.SR.DupContractInDataContractSet, dataContract.StableName.Name, dataContract.StableName.Namespace)));
                }
                bool flag = DataContract.GetClrTypeFullName(dataContract.UnderlyingType) == DataContract.GetClrTypeFullName(value.UnderlyingType);
                throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new InvalidOperationException(System.SR.Format(System.SR.DupTypeContractInDataContractSet, flag ? dataContract.UnderlyingType.AssemblyQualifiedName : DataContract.GetClrTypeFullName(dataContract.UnderlyingType), flag ? value.UnderlyingType.AssemblyQualifiedName : DataContract.GetClrTypeFullName(value.UnderlyingType), dataContract.StableName.Name, dataContract.StableName.Namespace)));
            }
        }
        else
        {
            Contracts.Add(name, dataContract);
            if (dataContract is ClassDataContract)
            {
                AddClassDataContract((ClassDataContract)dataContract);
            }
            else if (dataContract is CollectionDataContract)
            {
                AddCollectionDataContract((CollectionDataContract)dataContract);
            }
            else if (dataContract is XmlDataContract)
            {
                AddXmlDataContract((XmlDataContract)dataContract);
            }
        }
    }
References System.Runtime.Serialization.DataContractSet.AddClassDataContract(), System.Runtime.Serialization.DataContractSet.AddCollectionDataContract(), System.Runtime.Serialization.DataContractSet.AddXmlDataContract(), System.Runtime.Serialization.Dictionary, System.SR.DupContractInDataContractSet, System.SR.DupTypeContractInDataContractSet, System.SR.Format(), System.Runtime.Serialization.DataContract.GetClrTypeFullName(), System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperError(), and System.value.
Referenced by System.Runtime.Serialization.DataContractSet.Add().