Terraria: System.Data.SqlTypes.SqlStreamChars.Seek
Seek()
long System.Data.SqlTypes.SqlStreamChars.Seek (long offset, SeekOrigin origin) inline
Definition at line 31 of file SqlStreamChars.cs.
    {
        CheckIfStreamClosed("Seek");
        long num = 0L;
        switch (origin)
        {
        case SeekOrigin.Begin:
            if (offset < 0 || offset > _sqlchars.Length)
            {
                throw ADP.ArgumentOutOfRange("offset");
            }
            _lPosition = offset;
            break;
        case SeekOrigin.Current:
            num = _lPosition + offset;
            if (num < 0 || num > _sqlchars.Length)
            {
                throw ADP.ArgumentOutOfRange("offset");
            }
            _lPosition = num;
            break;
        case SeekOrigin.End:
            num = _sqlchars.Length + offset;
            if (num < 0 || num > _sqlchars.Length)
            {
                throw ADP.ArgumentOutOfRange("offset");
            }
            _lPosition = num;
            break;
        default:
            throw ADP.ArgumentOutOfRange("offset");
        }
        return _lPosition;
    }
References System.Data.SqlTypes.SqlStreamChars._lPosition, System.Data.SqlTypes.SqlStreamChars._sqlchars, System.Data.Common.ADP.ArgumentOutOfRange(), System.Data.SqlTypes.SqlStreamChars.CheckIfStreamClosed(), System.L, System.Data.SqlTypes.SqlChars.Length, and System.offset.
Referenced by System.Data.SqlTypes.SqlChars.CopyStreamToBuffer(), System.Data.SqlTypes.SqlChars.Read(), and System.Data.SqlTypes.SqlChars.Write().