Terraria: System.Data.SqlTypes.SqlStreamChars.Read
Read()
int System.Data.SqlTypes.SqlStreamChars.Read (char[] buffer, int offset, int count) inline
Definition at line 66 of file SqlStreamChars.cs.
    {
        CheckIfStreamClosed("Read");
        if (buffer == null)
        {
            throw new ArgumentNullException("buffer");
        }
        if (offset < 0 || offset > buffer.Length)
        {
            throw new ArgumentOutOfRangeException("offset");
        }
        if (count < 0 || count > buffer.Length - offset)
        {
            throw new ArgumentOutOfRangeException("count");
        }
        int num = (int)_sqlchars.Read(_lPosition, buffer, offset, count);
        _lPosition += num;
        return num;
    }
References System.Data.SqlTypes.SqlStreamChars._lPosition, System.Data.SqlTypes.SqlStreamChars._sqlchars, System.buffer, System.Data.SqlTypes.SqlStreamChars.CheckIfStreamClosed(), System.count, System.offset, and System.Data.SqlTypes.SqlChars.Read().
Referenced by System.Data.SqlTypes.SqlChars.CopyStreamToBuffer(), and System.Data.SqlTypes.SqlChars.Read().