Terraria: System.ComponentModel.DataAnnotations.AssociatedMetadataTypeTypeDescriptor.GetPropertiesWithMetadata
GetPropertiesWithMetadata()
PropertyDescriptorCollection System.ComponentModel.DataAnnotations.AssociatedMetadataTypeTypeDescriptor.GetPropertiesWithMetadata (PropertyDescriptorCollection originalCollection) inline private
Definition at line 105 of file AssociatedMetadataTypeTypeDescriptor.cs.
    {
        if (AssociatedMetadataType == null)
        {
            return originalCollection;
        }
        bool flag = false;
        List<PropertyDescriptor> list = new List<PropertyDescriptor>();
        foreach (PropertyDescriptor item2 in originalCollection)
        {
            Attribute[] associatedMetadata = TypeDescriptorCache.GetAssociatedMetadata(AssociatedMetadataType, item2.Name);
            PropertyDescriptor item = item2;
            if (associatedMetadata.Length != 0)
            {
                item = new MetadataPropertyDescriptorWrapper(item2, associatedMetadata);
                flag = true;
            }
            list.Add(item);
        }
        if (flag)
        {
            return new PropertyDescriptorCollection(list.ToArray(), readOnly: true);
        }
        return originalCollection;
    }
References System.ComponentModel.DataAnnotations.AssociatedMetadataTypeTypeDescriptor.AssociatedMetadataType, System.ComponentModel.DataAnnotations.AssociatedMetadataTypeTypeDescriptor.TypeDescriptorCache.GetAssociatedMetadata(), System.item, and System.list.
Referenced by System.ComponentModel.DataAnnotations.AssociatedMetadataTypeTypeDescriptor.GetProperties(), and System.ComponentModel.DataAnnotations.AssociatedMetadataTypeTypeDescriptor.GetProperties().