Terraria: System.Xml.XmlResolver.ResolveUri
ResolveUri()
virtual Uri System.Xml.XmlResolver.ResolveUri (Uri? baseUri, string? relativeUri) inline virtual
Reimplemented in System.Xml.Resolvers.XmlPreloadedResolver, System.Xml.XmlSecureResolver, and System.Xml.XmlUrlResolver.
Definition at line 18 of file XmlResolver.cs.
    {
        if (baseUri == null || (!baseUri.IsAbsoluteUri && baseUri.OriginalString.Length == 0))
        {
            Uri uri = new Uri(relativeUri, UriKind.RelativeOrAbsolute);
            if (!uri.IsAbsoluteUri && uri.OriginalString.Length > 0)
            {
                uri = new Uri(Path.GetFullPath(relativeUri));
            }
            return uri;
        }
        if (relativeUri == null || relativeUri.Length == 0)
        {
            return baseUri;
        }
        if (!baseUri.IsAbsoluteUri)
        {
            throw new NotSupportedException(System.SR.Xml_RelativeUriNotSupported);
        }
        return new Uri(baseUri, relativeUri);
    }
References System.Xml.Dictionary, System.IO.Path.GetFullPath(), System.Uri.IsAbsoluteUri, System.Uri.OriginalString, and System.SR.Xml_RelativeUriNotSupported.
Referenced by System.Xml.XmlTextReaderImpl.XmlTextReaderImpl(), System.Xml.XmlValidatingReaderImpl.XmlValidatingReaderImpl(), System.Xml.XmlValidatingReaderImpl.XmlValidatingReaderImpl(), System.Xml.XmlTextReaderImpl.DtdParserProxy_PushExternalSubset(), System.Xml.XmlTextReaderImpl.DtdParserProxy_PushExternalSubsetAsync(), System.Xml.Xsl.Runtime.XmlQueryContext.GetDataSource(), System.Xml.Schema.XdrBuilder.LoadSchema(), System.Xml.Schema.XmlSchemaValidator.LoadSchema(), System.Xml.XmlTextReaderImpl.PushExternalEntity(), System.Xml.XmlTextReaderImpl.PushExternalEntityAsync(), System.Xml.XmlTextReaderImpl.PushExternalEntityOrSubset(), System.Xml.XmlTextReaderImpl.PushExternalEntityOrSubsetAsync(), System.Xml.Schema.Preprocessor.ResolveSchemaLocationUri(), System.Xml.Schema.SchemaCollectionPreprocessor.ResolveSchemaLocationUri(), System.Xml.Xsl.XsltOld.Compiler.ResolveUri(), System.Xml.Xsl.Xslt.XsltLoader.ResolveUri(), and System.Xml.XmlSecureResolver.ResolveUri().