Terraria: System.Xml.XmlResolver.SupportsType
SupportsType()
virtual bool System.Xml.XmlResolver.SupportsType (Uri absoluteUri, Type? type) inline virtual inherited
Reimplemented in System.Xml.Resolvers.XmlPreloadedResolver.
Definition at line 40 of file XmlResolver.cs.
    {
        if (absoluteUri == null)
        {
            throw new ArgumentNullException("absoluteUri");
        }
        if (type == null || type == typeof(Stream))
        {
            return true;
        }
        return false;
    }
References System.Xml.Dictionary, and System.type.
Referenced by System.Xml.XmlTextReaderImpl.OpenAndPush(), System.Xml.XmlTextReaderImpl.OpenAndPushAsync(), and System.Xml.Resolvers.XmlPreloadedResolver.SupportsType().