Terraria: Terraria.Graphics.Capture.CaptureInterface.StartCamera
StartCamera()
static void Terraria.Graphics.Capture.CaptureInterface.StartCamera (CaptureSettings settings) inline static
Definition at line 1546 of file CaptureInterface.cs.
    {
        SoundEngine.PlaySound(40);
        CameraSettings = settings;
        CameraLock = true;
        CameraWaiting = 0f;
    }
References Terraria.Graphics.Capture.CaptureInterface.CameraLock, Terraria.Graphics.Capture.CaptureInterface.CameraSettings, Terraria.Graphics.Capture.CaptureInterface.CameraWaiting, and Terraria.Audio.SoundEngine.PlaySound().
Referenced by Terraria.Graphics.Capture.CaptureInterface.QuickScreenshot(), and Terraria.Graphics.Capture.CaptureInterface.UpdateButtons().