Terraria: Terraria.Graphics.Capture.CaptureInterface.QuickScreenshot
QuickScreenshot()
static void Terraria.Graphics.Capture.CaptureInterface.QuickScreenshot () inline static
Definition at line 1102 of file CaptureInterface.cs.
    {
        Point point = Main.ViewPosition.ToTileCoordinates();
        Point point2 = (Main.ViewPosition + Main.ViewSize).ToTileCoordinates();
        StartCamera(new CaptureSettings
        {
            Area = new Rectangle(point.X, point.Y, point2.X - point.X + 1, point2.Y - point.Y + 1),
            Biome = CaptureBiome.GetCaptureBiome(Settings.BiomeChoiceIndex),
            CaptureBackground = !Settings.TransparentBackground,
            CaptureEntities = Settings.IncludeEntities,
            UseScaling = Settings.PackImage,
            CaptureMech = WiresUI.Settings.DrawWires
        });
    }
References Terraria.Graphics.Capture.CaptureInterface.Settings.BiomeChoiceIndex, Terraria.Graphics.Capture.CaptureBiome.GetCaptureBiome(), Terraria.Graphics.Capture.CaptureInterface.Settings.IncludeEntities, Terraria.Graphics.Capture.CaptureInterface.Settings.PackImage, Terraria.Graphics.Capture.CaptureInterface.StartCamera(), Terraria.Graphics.Capture.CaptureInterface.Settings.TransparentBackground, Terraria.Main.ViewPosition, Terraria.Main.ViewSize, Microsoft.Xna.Framework.Point.X, and Microsoft.Xna.Framework.Point.Y.
Referenced by Terraria.Main.DrawPageIcons(), and Terraria.Graphics.Capture.CaptureInterface.UpdateButtons().