Terraria: ItemTransferParticle.Prepare
Prepare()
void ItemTransferParticle.Prepare (int itemType, int lifeTimeTotal, Vector2 playerPosition, Vector2 chestPosition) inline
     {
         _itemInstance.SetDefaults(itemType);
         _lifeTimeTotal = lifeTimeTotal;
         StartPosition = playerPosition;
         EndPosition = chestPosition;
         Vector2 vector = (EndPosition - StartPosition).SafeNormalize(Vector2.UnitY).RotatedBy(1.5707963705062866);
         bool num = vector.Y < 0f;
         bool flag = vector.Y == 0f;
         if (!num || (flag && Main.rand.Next(2) == 0))
         {
             vector *= -1f;
         }
         vector = new Vector2(0f, -1f);
         float num2 = Vector2.Distance(EndPosition, StartPosition);
         BezierHelper1 = vector * num2 + Main.rand.NextVector2Circular(32f, 32f);
         BezierHelper2 = -vector * num2 + Main.rand.NextVector2Circular(32f, 32f);
     }
References _itemInstance, _lifeTimeTotal, BezierHelper1, BezierHelper2, EndPosition, UnifiedRandom.Next(), Main.rand, Item.SetDefaults(), and StartPosition.
Referenced by ParticleOrchestrator.Spawn_ItemTransfer().