Terraria: System.Reflection.BlobUtilities.ReadBytes
ReadBytes()
static unsafe byte[] System.Reflection.BlobUtilities.ReadBytes (byte * buffer, int byteCount) inline static
Definition at line 14 of file BlobUtilities.cs.
    {
        if (byteCount == 0)
        {
            return EmptyArray<byte>.Instance;
        }
        byte[] array = new byte[byteCount];
        Marshal.Copy((IntPtr)buffer, array, 0, byteCount);
        return array;
    }
References System.array, System.buffer, System.byteCount, System.Runtime.InteropServices.Marshal.Copy(), and System.Reflection.Internal.EmptyArray< T >.Instance.
Referenced by System.Reflection.Internal.MemoryBlock.PeekBytes(), and System.Reflection.BlobUtilities.ReadImmutableBytes().