Terraria: System.Xml.Xsl.Xslt.XslVisitor.VisitChildren
VisitChildren()
virtual T System.Xml.Xsl.Xslt.XslVisitor< T >.VisitChildren (XslNode node) inline protected virtual
Reimplemented in System.Xml.Xsl.Xslt.XslAstAnalyzer.
Definition at line 204 of file XslVisitor.cs.
    {
        foreach (XslNode item in node.Content)
        {
            Visit(item);
        }
        return default(T);
    }
References System.Xml.Xsl.Xslt.XslNode.Content, System.Xml.Dictionary, System.item, and System.Xml.Xsl.Xslt.XslVisitor< T >.Visit().
Referenced by System.Xml.Xsl.Xslt.XslVisitor< T >.VisitApplyImports(), System.Xml.Xsl.Xslt.XslVisitor< T >.VisitApplyTemplates(), System.Xml.Xsl.Xslt.XslVisitor< T >.VisitAttribute(), System.Xml.Xsl.Xslt.XslVisitor< T >.VisitAttributeSet(), System.Xml.Xsl.Xslt.XslVisitor< T >.VisitCallTemplate(), System.Xml.Xsl.Xslt.XslVisitor< T >.VisitChoose(), System.Xml.Xsl.Xslt.XslVisitor< T >.VisitComment(), System.Xml.Xsl.Xslt.XslVisitor< T >.VisitCopy(), System.Xml.Xsl.Xslt.XslVisitor< T >.VisitCopyOf(), System.Xml.Xsl.Xslt.XslVisitor< T >.VisitElement(), System.Xml.Xsl.Xslt.XslVisitor< T >.VisitError(), System.Xml.Xsl.Xslt.XslVisitor< T >.VisitForEach(), System.Xml.Xsl.Xslt.XslVisitor< T >.VisitIf(), System.Xml.Xsl.Xslt.XslVisitor< T >.VisitKey(), System.Xml.Xsl.Xslt.XslVisitor< T >.VisitList(), System.Xml.Xsl.Xslt.XslVisitor< T >.VisitLiteralAttribute(), System.Xml.Xsl.Xslt.XslVisitor< T >.VisitLiteralElement(), System.Xml.Xsl.Xslt.XslVisitor< T >.VisitMessage(), System.Xml.Xsl.Xslt.XslVisitor< T >.VisitNop(), System.Xml.Xsl.Xslt.XslVisitor< T >.VisitNumber(), System.Xml.Xsl.Xslt.XslVisitor< T >.VisitOtherwise(), System.Xml.Xsl.Xslt.XslVisitor< T >.VisitParam(), System.Xml.Xsl.Xslt.XslVisitor< T >.VisitPI(), System.Xml.Xsl.Xslt.XslVisitor< T >.VisitSort(), System.Xml.Xsl.Xslt.XslVisitor< T >.VisitTemplate(), System.Xml.Xsl.Xslt.XslVisitor< T >.VisitText(), System.Xml.Xsl.Xslt.XslVisitor< T >.VisitUnknown(), System.Xml.Xsl.Xslt.XslVisitor< T >.VisitUseAttributeSet(), System.Xml.Xsl.Xslt.XslVisitor< T >.VisitValueOf(), System.Xml.Xsl.Xslt.XslVisitor< T >.VisitValueOfDoe(), System.Xml.Xsl.Xslt.XslVisitor< T >.VisitVariable(), and System.Xml.Xsl.Xslt.XslVisitor< T >.VisitWithParam().