Terraria: System.Xml.Xsl.Xslt.XslVisitor.Visit
Visit()
virtual T System.Xml.Xsl.Xslt.XslVisitor< T >.Visit (XslNode node) inline protected virtual
Reimplemented in System.Xml.Xsl.Xslt.XslAstAnalyzer.
Definition at line 5 of file XslVisitor.cs.
    {
        return node.NodeType switch
        {
            XslNodeType.ApplyImports => VisitApplyImports(node),
            XslNodeType.ApplyTemplates => VisitApplyTemplates(node),
            XslNodeType.Attribute => VisitAttribute((NodeCtor)node),
            XslNodeType.AttributeSet => VisitAttributeSet((AttributeSet)node),
            XslNodeType.CallTemplate => VisitCallTemplate(node),
            XslNodeType.Choose => VisitChoose(node),
            XslNodeType.Comment => VisitComment(node),
            XslNodeType.Copy => VisitCopy(node),
            XslNodeType.CopyOf => VisitCopyOf(node),
            XslNodeType.Element => VisitElement((NodeCtor)node),
            XslNodeType.Error => VisitError(node),
            XslNodeType.ForEach => VisitForEach(node),
            XslNodeType.If => VisitIf(node),
            XslNodeType.Key => VisitKey((Key)node),
            XslNodeType.List => VisitList(node),
            XslNodeType.LiteralAttribute => VisitLiteralAttribute(node),
            XslNodeType.LiteralElement => VisitLiteralElement(node),
            XslNodeType.Message => VisitMessage(node),
            XslNodeType.Nop => VisitNop(node),
            XslNodeType.Number => VisitNumber((Number)node),
            XslNodeType.Otherwise => VisitOtherwise(node),
            XslNodeType.Param => VisitParam((VarPar)node),
            XslNodeType.PI => VisitPI(node),
            XslNodeType.Sort => VisitSort((Sort)node),
            XslNodeType.Template => VisitTemplate((Template)node),
            XslNodeType.Text => VisitText((Text)node),
            XslNodeType.UseAttributeSet => VisitUseAttributeSet(node),
            XslNodeType.ValueOf => VisitValueOf(node),
            XslNodeType.ValueOfDoe => VisitValueOfDoe(node),
            XslNodeType.Variable => VisitVariable((VarPar)node),
            XslNodeType.WithParam => VisitWithParam((VarPar)node),
            _ => VisitUnknown(node),
        };
    }
References System.Xml.Dictionary, System.Xml.Xsl.Xslt.XslVisitor< T >.VisitApplyImports(), System.Xml.Xsl.Xslt.XslVisitor< T >.VisitApplyTemplates(), System.Xml.Xsl.Xslt.XslVisitor< T >.VisitAttribute(), System.Xml.Xsl.Xslt.XslVisitor< T >.VisitAttributeSet(), System.Xml.Xsl.Xslt.XslVisitor< T >.VisitCallTemplate(), System.Xml.Xsl.Xslt.XslVisitor< T >.VisitChoose(), System.Xml.Xsl.Xslt.XslVisitor< T >.VisitComment(), System.Xml.Xsl.Xslt.XslVisitor< T >.VisitCopy(), System.Xml.Xsl.Xslt.XslVisitor< T >.VisitCopyOf(), System.Xml.Xsl.Xslt.XslVisitor< T >.VisitElement(), System.Xml.Xsl.Xslt.XslVisitor< T >.VisitError(), System.Xml.Xsl.Xslt.XslVisitor< T >.VisitForEach(), System.Xml.Xsl.Xslt.XslVisitor< T >.VisitIf(), System.Xml.Xsl.Xslt.XslVisitor< T >.VisitKey(), System.Xml.Xsl.Xslt.XslVisitor< T >.VisitList(), System.Xml.Xsl.Xslt.XslVisitor< T >.VisitLiteralAttribute(), System.Xml.Xsl.Xslt.XslVisitor< T >.VisitLiteralElement(), System.Xml.Xsl.Xslt.XslVisitor< T >.VisitMessage(), System.Xml.Xsl.Xslt.XslVisitor< T >.VisitNop(), System.Xml.Xsl.Xslt.XslVisitor< T >.VisitNumber(), System.Xml.Xsl.Xslt.XslVisitor< T >.VisitOtherwise(), System.Xml.Xsl.Xslt.XslVisitor< T >.VisitParam(), System.Xml.Xsl.Xslt.XslVisitor< T >.VisitPI(), System.Xml.Xsl.Xslt.XslVisitor< T >.VisitSort(), System.Xml.Xsl.Xslt.XslVisitor< T >.VisitTemplate(), System.Xml.Xsl.Xslt.XslVisitor< T >.VisitText(), System.Xml.Xsl.Xslt.XslVisitor< T >.VisitUnknown(), System.Xml.Xsl.Xslt.XslVisitor< T >.VisitUseAttributeSet(), System.Xml.Xsl.Xslt.XslVisitor< T >.VisitValueOf(), System.Xml.Xsl.Xslt.XslVisitor< T >.VisitValueOfDoe(), System.Xml.Xsl.Xslt.XslVisitor< T >.VisitVariable(), and System.Xml.Xsl.Xslt.XslVisitor< T >.VisitWithParam().
Referenced by System.Xml.Xsl.Xslt.XslVisitor< T >.VisitChildren().