Terraria: System.Reflection.BlobUtilities.ValidateRange
ValidateRange()
static void System.Reflection.BlobUtilities.ValidateRange (int bufferLength, int start, int byteCount, string byteCountParameterName) inline static package
Definition at line 263 of file BlobUtilities.cs.
    {
        if (start < 0 || start > bufferLength)
        {
            Throw.ArgumentOutOfRange("start");
        }
        if (byteCount < 0 || byteCount > bufferLength - start)
        {
            Throw.ArgumentOutOfRange(byteCountParameterName);
        }
    }
References System.Reflection.Throw.ArgumentOutOfRange(), and System.start.
Referenced by System.Reflection.PortableExecutable.PEMemoryBlock.GetContent(), System.Reflection.PortableExecutable.PEMemoryBlock.GetReader(), System.Reflection.Metadata.BlobBuilder.ToArray(), System.Reflection.Metadata.BlobWriter.ToArray(), System.Reflection.Metadata.BlobBuilder.WriteBytes(), and System.Reflection.Metadata.BlobWriter.WriteBytes().