Terraria: GameTipsDisplay.GameTip.GameTip
GameTip()
GameTipsDisplay.GameTip.GameTip (string textKey, double spawnTime) inline
         {
             _textKey = Language.GetText(textKey);
             SpawnTime = spawnTime;
             ScreenAnchorX = 2.5f;
             Duration = 11.5f;
             object obj = Lang.CreateDialogSubstitutionObject();
             _formattedText = _textKey.FormatWith(obj);
             _formattedText = Lang.SupportGlyphs(_formattedText);
         }
References GameTipsDisplay.GameTip._formattedText, GameTipsDisplay.GameTip._textKey, Lang.CreateDialogSubstitutionObject(), GameTipsDisplay.GameTip.Duration, LocalizedText.FormatWith(), Language.GetText(), GameTipsDisplay.GameTip.ScreenAnchorX, GameTipsDisplay.GameTip.SpawnTime, and Lang.SupportGlyphs().