Terraria: System.Reflection.BlobUtilities.WriteUTF8
WriteUTF8()
static unsafe void System.Reflection.BlobUtilities.WriteUTF8 (this byte[] buffer, int start, char * charPtr, int charCount, int byteCount, bool allowUnpairedSurrogates) inline static
Definition at line 140 of file BlobUtilities.cs.
    {
        char* ptr = charPtr + charCount;
        fixed (byte* ptr2 = &buffer[0])
        {
            byte* ptr3 = ptr2 + start;
            if (byteCount == charCount)
            {
                while (charPtr < ptr)
                {
                    *(ptr3++) = (byte)(*(charPtr++));
                }
                return;
            }
            while (charPtr < ptr)
            {
                char c = *(charPtr++);
                if (c < '\u0080')
                {
                    *(ptr3++) = (byte)c;
                    continue;
                }
                if (c < 'ࠀ')
                {
                    *ptr3 = (byte)(((uint)((int)c >> 6) & 0x1Fu) | 0xC0u);
                    ptr3[1] = (byte)((c & 0x3Fu) | 0x80u);
                    ptr3 += 2;
                    continue;
                }
                if (IsSurrogateChar(c))
                {
                    if (IsHighSurrogateChar(c) && charPtr < ptr && IsLowSurrogateChar(*charPtr))
                    {
                        int num = c;
                        int num2 = *(charPtr++);
                        int num3 = (num - 55296 << 10) + num2 - 56320 + 65536;
                        *ptr3 = (byte)(((uint)(num3 >> 18) & 7u) | 0xF0u);
                        ptr3[1] = (byte)(((uint)(num3 >> 12) & 0x3Fu) | 0x80u);
                        ptr3[2] = (byte)(((uint)(num3 >> 6) & 0x3Fu) | 0x80u);
                        ptr3[3] = (byte)(((uint)num3 & 0x3Fu) | 0x80u);
                        ptr3 += 4;
                        continue;
                    }
                    if (!allowUnpairedSurrogates)
                    {
                        c = '\ufffd';
                    }
                }
                *ptr3 = (byte)(((uint)((int)c >> 12) & 0xFu) | 0xE0u);
                ptr3[1] = (byte)(((uint)((int)c >> 6) & 0x3Fu) | 0x80u);
                ptr3[2] = (byte)((c & 0x3Fu) | 0x80u);
                ptr3 += 3;
            }
        }
    }
References System.buffer, System.byteCount, System.charCount, System.Reflection.BlobUtilities.IsHighSurrogateChar(), System.Reflection.BlobUtilities.IsLowSurrogateChar(), System.Reflection.BlobUtilities.IsSurrogateChar(), and System.start.