Terraria: System.Xml.Xsl.Qil.QilDepthChecker.Check
Check() [1/2]
static void System.Xml.Xsl.Qil.QilDepthChecker.Check (QilNode input) inline static
Definition at line 9 of file QilDepthChecker.cs.
    {
        if (System.LocalAppContextSwitches.LimitXPathComplexity)
        {
            new QilDepthChecker().Check(input, 0);
        }
    }
References System.Xml.Xsl.Qil.QilDepthChecker.Check(), System.input, and System.LocalAppContextSwitches.LimitXPathComplexity.
Referenced by System.Xml.Xsl.Qil.QilDepthChecker.Check(), System.Xml.Xsl.Qil.QilDepthChecker.Check(), System.Xml.Xsl.Qil.QilCloneVisitor.Clone(), System.Xml.Xsl.Xslt.QilGenerator.Compile(), System.Xml.Xsl.Xslt.KeyMatchBuilder.PathConvertor.ConvertReletive2Absolute(), System.Xml.Xsl.XPath.XPathBuilder.FixupVisitor.Fixup(), System.Xml.Xsl.XPath.XPathBuilder.FixupVisitor.Fixup(), and System.Xml.Xsl.Xslt.ReferenceReplacer.Replace().