Terraria: System.Xml.Xsl.Qil.QilDepthChecker.Check
Check() [2/2]
void System.Xml.Xsl.Qil.QilDepthChecker.Check (QilNode input, int depth) inline private
Definition at line 17 of file QilDepthChecker.cs.
    {
        if (depth > 800)
        {
            throw XsltException.Create(System.SR.Xslt_InputTooComplex);
        }
        if (input is QilReference)
        {
            if (_visitedRef.ContainsKey(input))
            {
                return;
            }
            _visitedRef[input] = true;
        }
        int depth2 = depth + 1;
        for (int i = 0; i < input.Count; i++)
        {
            QilNode qilNode = input[i];
            if (qilNode != null)
            {
                Check(qilNode, depth2);
            }
        }
    }
References System.Xml.Xsl.Qil.QilDepthChecker._visitedRef, System.Xml.Xsl.Qil.QilDepthChecker.Check(), System.Collections.Generic.Dictionary< TKey, TValue >.ContainsKey(), System.Xml.Xsl.XsltException.Create(), System.input, and System.SR.Xslt_InputTooComplex.