Terraria: System.Threading.AsyncMutex.Exit
Exit()
void System.Threading.AsyncMutex.Exit () inline
Definition at line 115 of file AsyncMutex.cs.
    {
        if (Interlocked.Increment(ref _gate) < 1)
        {
            Contended();
        }
        void Contended()
        {
            Waiter waiter;
            lock (SyncObj)
            {
                waiter = _waitersTail;
                if (waiter == null)
                {
                    _lockedSemaphoreFull = false;
                }
                else
                {
                    if (waiter.Next == waiter)
                    {
                        _waitersTail = null;
                    }
                    else
                    {
                        waiter = waiter.Prev;
                        waiter.Next.Prev = waiter.Prev;
                        waiter.Prev.Next = waiter.Next;
                    }
                    Waiter waiter2 = waiter;
                    Waiter next = (waiter.Prev = null);
                    waiter2.Next = next;
                }
            }
            if (waiter != null)
            {
                waiter.CancellationRegistration.Unregister();
                waiter.TrySetResult();
            }
        }
    }
References System.Threading.AsyncMutex._gate, System.Threading.AsyncMutex._lockedSemaphoreFull, System.Threading.AsyncMutex._waitersTail, System.Threading.AsyncMutex.Waiter.CancellationRegistration, System.Threading.Interlocked.Increment(), System.Threading.AsyncMutex.Waiter.Next, System.Threading.AsyncMutex.Waiter.Prev, System.Threading.AsyncMutex.SyncObj, System.Threading.Tasks.TaskCompletionSource< TResult >.TrySetResult(), and System.Threading.CancellationTokenRegistration.Unregister().
Referenced by System.Net.WebSockets.ManagedWebSocket.CloseAsyncPrivate(), System.Net.WebSockets.ManagedWebSocket._003CReceiveAsyncPrivate_003Ed__63< TResult >.MoveNext(), System.Net.WebSockets.ManagedWebSocket.SendFrameFallbackAsync(), System.Net.WebSockets.ManagedWebSocket.SendFrameLockAcquiredNonCancelableAsync(), and System.Net.WebSockets.ManagedWebSocket.WaitForWriteTaskAsync().