Terraria: System.Threading.AsyncMutex.EnterAsync
EnterAsync()
Task System.Threading.AsyncMutex.EnterAsync (CancellationToken cancellationToken) inline
Definition at line 32 of file AsyncMutex.cs.
    {
        if (!cancellationToken.IsCancellationRequested)
        {
            if (Interlocked.Decrement(ref _gate) < 0)
            {
                return Contended(cancellationToken);
            }
            return Task.CompletedTask;
        }
        return Task.FromCanceled(cancellationToken);
        Task Contended(CancellationToken cancellationToken)
        {
            Waiter waiter4 = new Waiter(this);
            waiter4.CancellationRegistration = cancellationToken.UnsafeRegister(delegate(object s, CancellationToken token)
            {
                OnCancellation(s, token);
            }, waiter4);
            lock (SyncObj)
            {
                if (!_lockedSemaphoreFull)
                {
                    waiter4.CancellationRegistration.Unregister();
                    _lockedSemaphoreFull = true;
                    return Task.CompletedTask;
                }
                if (cancellationToken.IsCancellationRequested)
                {
                    waiter4.TrySetCanceled(cancellationToken);
                    return waiter4.Task;
                }
                if (_waitersTail == null)
                {
                    Waiter next2 = (waiter4.Prev = waiter4);
                    waiter4.Next = next2;
                }
                else
                {
                    waiter4.Next = _waitersTail;
                    waiter4.Prev = _waitersTail.Prev;
                    Waiter prev = waiter4.Prev;
                    Waiter next2 = (waiter4.Next.Prev = waiter4);
                    prev.Next = next2;
                }
                _waitersTail = waiter4;
            }
            return waiter4.Task;
        }
        static void OnCancellation(object state, CancellationToken cancellationToken)
        {
            Waiter waiter = (Waiter)state;
            AsyncMutex owner = waiter.Owner;
            lock (owner.SyncObj)
            {
                if (waiter.Next != null)
                {
                    Interlocked.Increment(ref owner._gate);
                    if (waiter.Next == waiter)
                    {
                        owner._waitersTail = null;
                    }
                    else
                    {
                        waiter.Next.Prev = waiter.Prev;
                        waiter.Prev.Next = waiter.Next;
                        if (owner._waitersTail == waiter)
{
                            owner._waitersTail = waiter.Next;
                        }
                    }
                    Waiter waiter2 = waiter;
                    Waiter next = (waiter.Prev = null);
                    waiter2.Next = next;
                }
                else
                {
                    waiter = null;
                }
            }
            waiter?.TrySetCanceled(cancellationToken);
        }
    }
References System.Threading.AsyncMutex._gate, System.Threading.AsyncMutex._lockedSemaphoreFull, System.Threading.AsyncMutex._waitersTail, System.Threading.AsyncMutex.Waiter.CancellationRegistration, System.cancellationToken, System.Threading.Tasks.Task< TResult >.CompletedTask, System.Threading.Interlocked.Decrement(), System.Threading.Tasks.Task< TResult >.FromCanceled(), System.Threading.Interlocked.Increment(), System.Threading.AsyncMutex.Waiter.Next, System.Threading.AsyncMutex.Waiter.Owner, System.Threading.AsyncMutex.Waiter.Prev, System.s, System.state, System.Threading.AsyncMutex.SyncObj, System.Threading.Tasks.TaskCompletionSource< TResult >.Task, System.Threading.Tasks.TaskCompletionSource< TResult >.TrySetCanceled(), and System.Threading.CancellationTokenRegistration.Unregister().
Referenced by System.Net.WebSockets.ManagedWebSocket.CloseAsyncPrivate(), System.Net.WebSockets.ManagedWebSocket._003CReceiveAsyncPrivate_003Ed__63< TResult >.MoveNext(), and System.Net.WebSockets.ManagedWebSocket.SendFrameAsync().