Terraria: Microsoft.Xna.Framework.WindowsManagedCallbackHandler._0021WindowsManagedCallbackHandler
_0021WindowsManagedCallbackHandler()
unsafe void Microsoft.Xna.Framework.WindowsManagedCallbackHandler._0021WindowsManagedCallbackHandler () inline private
Definition at line 226 of file WindowsManagedCallbackHandler.cs.
    {
        void* callManagedPlease = _callManagedPlease;
        if (callManagedPlease != null)
        {
            global::_003CModule_003E.CloseHandle(callManagedPlease);
            _callManagedPlease = null;
        }
        void* managedFunctionDataCanBeWritten = _managedFunctionDataCanBeWritten;
        if (managedFunctionDataCanBeWritten != null)
        {
            global::_003CModule_003E.CloseHandle(managedFunctionDataCanBeWritten);
            _managedFunctionDataCanBeWritten = null;
        }
        void* proxyProcessNeedsToChange = _proxyProcessNeedsToChange;
        if (proxyProcessNeedsToChange != null)
        {
            global::_003CModule_003E.CloseHandle(proxyProcessNeedsToChange);
            _proxyProcessNeedsToChange = null;
        }
        void* newCallbackRegistered = _newCallbackRegistered;
        if (newCallbackRegistered != null)
        {
            global::_003CModule_003E.CloseHandle(newCallbackRegistered);
            _newCallbackRegistered = null;
        }
        if (nativeToManagedCallbacks.Count > 0)
        {
            do
            {
                global::_003CModule_003E.CloseHandle(nativeToManagedCallbacks[0].dupedWaitHandle);
                nativeToManagedCallbacks.RemoveAt(0);
            }
            while (nativeToManagedCallbacks.Count > 0);
        }
    }
References Microsoft.Xna.Framework.WindowsManagedCallbackHandler._callManagedPlease, Microsoft.Xna.Framework.WindowsManagedCallbackHandler._managedFunctionDataCanBeWritten, Microsoft.Xna.Framework.WindowsManagedCallbackHandler._newCallbackRegistered, Microsoft.Xna.Framework.WindowsManagedCallbackHandler._proxyProcessNeedsToChange, System.Collections.Generic.List< T >.Count, Microsoft.Xna.Framework.WindowsManagedCallbackHandler.nativeToManagedCallbacks, and System.Collections.Generic.List< T >.RemoveAt().
Referenced by Microsoft.Xna.Framework.WindowsManagedCallbackHandler._007EWindowsManagedCallbackHandler(), and Microsoft.Xna.Framework.WindowsManagedCallbackHandler.Dispose().