Terraria: Microsoft.Xna.Framework.WindowsManagedCallbackHandler.WaitForAsyncOperationToFinish
WaitForAsyncOperationToFinish()
unsafe int Microsoft.Xna.Framework.WindowsManagedCallbackHandler.WaitForAsyncOperationToFinish (out ManagedCallType managedCallType, out uint managedCallArgs) inline
Definition at line 52 of file WindowsManagedCallbackHandler.cs.
    {
        int num = 0;
        System.Runtime.CompilerServices.Unsafe.SkipInit(out _0024ArrayType_0024_0024_0024BY0EA_0040PAX _0024ArrayType_0024_0024_0024BY0EA_0040PAX);
        while (true)
        {
            bool flag = false;
            uint num2 = 0u;
            uint num3 = uint.MaxValue;
            uint num4 = uint.MaxValue;
            uint num5 = uint.MaxValue;
            uint num6 = uint.MaxValue;
            uint num7 = uint.MaxValue;
            bool lockTaken = false;
            try
            {
                Monitor.Enter(nativeToManagedCallbacks, ref lockTaken);
                num2 = (uint)(nativeToManagedCallbacks.Count + 5);
                if (num2 > 64)
                {
                    return -2147220991;
                }
                for (int i = 0; i < nativeToManagedCallbacks.Count; i++)
                {
                    *(int*)((ref *(_003F*)(i * 4)) + (ref *(_003F*)(&_0024ArrayType_0024_0024_0024BY0EA_0040PAX))) = (int)nativeToManagedCallbacks[i].dupedWaitHandle;
                }
                num3 = num2 - 5;
                *(int*)((ref *(_003F*)(num3 * 4)) + (ref *(_003F*)(&_0024ArrayType_0024_0024_0024BY0EA_0040PAX))) = (int)_newCallbackRegistered;
                num4 = num2 - 4;
                *(int*)((ref *(_003F*)(num4 * 4)) + (ref *(_003F*)(&_0024ArrayType_0024_0024_0024BY0EA_0040PAX))) = (int)_callManagedPlease;
                num5 = num2 - 3;
                *(int*)((ref *(_003F*)(num5 * 4)) + (ref *(_003F*)(&_0024ArrayType_0024_0024_0024BY0EA_0040PAX))) = (int)_proxyProcessNeedsToChange;
                num6 = num2 - 2;
                *(int*)((ref *(_003F*)(num6 * 4)) + (ref *(_003F*)(&_0024ArrayType_0024_0024_0024BY0EA_0040PAX))) = (int)_parentExitEvent;
            }
            finally
            {
                if (lockTaken)
                {
                    Monitor.Exit(nativeToManagedCallbacks);
                }
            }
            bool lockTaken2 = false;
            try
            {
                Monitor.Enter(_proxyProcessHandlerSyncObject, ref lockTaken2);
                IProxyProcessHandler proxyProcessHandler = _proxyProcessHandler;
                if (proxyProcessHandler != null)
                {
                    IntPtr proxyProcessWantsToTalk = proxyProcessHandler.ProxyProcessWantsToTalk;
                    IntPtr intPtr = proxyProcessWantsToTalk;
                    IntPtr intPtr2 = proxyProcessWantsToTalk;
                    num7 = num2 - 1;
                    *(int*)((ref *(_003F*)(num7 * 4)) + (ref *(_003F*)(&_0024ArrayType_0024_0024_0024BY0EA_0040PAX))) = (int)intPtr2.ToPointer();
                }
                else
                {
                    num2--;
                }
                uint num8 = global::_003CModule_003E.WaitForMultipleObjects(num2, (void**)(&_0024ArrayType_0024_0024_0024BY0EA_0040PAX), 0, uint.MaxValue);
                if (num8 == uint.MaxValue)
                {
                    uint lastError = global::_003CModule_003E.GetLastError();
                    int num9 = (((int)lastError > 0) ? ((int)(lastError & 0xFFFF) | -2147024896) : ((int)lastError));
                    num = num9;
                }
                num8 = num8;
                if (num8 < num3)
                {
                    bool flag2 = false;
                    NativeToManagedCallback nativeToManagedCallback = nativeToManagedCallbacks[(int)num8];
                    ManagedCallType managedCallType2 = managedCallType;
                    uint num10 = managedCallArgs;
                    num = nativeToManagedCallback.eventSignalledFunction(nativeToManagedCallback.originalWaitHandle, nativeToManagedCallback.pContext, &managedCallType2, &num10, &flag2);
                    if (num >= 0)
                    {
                        managedCallType = managedCallType2;
                        managedCallArgs = num10;
                        if (flag2)
{
                            void* dupedWaitHandle = nativeToManagedCallback.dupedWaitHandle;
                            if (dupedWaitHandle != null && dupedWaitHandle != (void*)(-1))
{
                                global::_003CModule_003E.CloseHandle(dupedWaitHandle);
                                nativeToManagedCallback.dupedWaitHandle = (void*)(-1);
                            }
                            nativeToManagedCallbacks.RemoveAt((int)num8);
                        }
                    }
                }
                else if (num8 == num4)
                {
                    managedCallType = _managedCallType;
                    managedCallArgs = _managedCallArgs;
                    global::_003CModule_003E.SetEvent(_managedFunctionDataCanBeWritten);
                }
                else if (num8 != num5 && num8 != num3)
                {
                    if (num8 == num6)
                    {
                        Thread.CurrentThread.Abort();
                    }
                    else if (num7 != uint.MaxValue && num8 == num7)
                    {
                        managedCallType = _proxyProcessHandler.AsyncManagedCallType;
                        managedCallArgs = _proxyProcessHandler.AsyncManagedCallArgument;
                        num = (int)_proxyProcessHandler.AsyncHResult;
                        global::_003CModule_003E.SetEvent(_proxyProcessHandler.SharedAsyncDataSafeToWrite.ToPointer());
                    }
                }
                else
                {
                    flag = true;
                }
            }
            finally
            {
                if (lockTaken2)
                {
                    Monitor.Exit(_proxyProcessHandlerSyncObject);
                }
            }
            if (!flag)
            {
                break;
            }
            global::_003CModule_003E.Sleep(0u);
        }
        return num;
    }
References Microsoft.Xna.Framework.WindowsManagedCallbackHandler._callManagedPlease, Microsoft.Xna.Framework.WindowsManagedCallbackHandler._managedCallArgs, Microsoft.Xna.Framework.WindowsManagedCallbackHandler._managedCallType, Microsoft.Xna.Framework.WindowsManagedCallbackHandler._managedFunctionDataCanBeWritten, Microsoft.Xna.Framework.WindowsManagedCallbackHandler._newCallbackRegistered, Microsoft.Xna.Framework.WindowsManagedCallbackHandler._parentExitEvent, Microsoft.Xna.Framework.WindowsManagedCallbackHandler._proxyProcessHandler, Microsoft.Xna.Framework.WindowsManagedCallbackHandler._proxyProcessHandlerSyncObject, Microsoft.Xna.Framework.WindowsManagedCallbackHandler._proxyProcessNeedsToChange, Microsoft.Xna.Framework.IProxyProcessHandler.AsyncHResult, Microsoft.Xna.Framework.IProxyProcessHandler.AsyncManagedCallArgument, Microsoft.Xna.Framework.IProxyProcessHandler.AsyncManagedCallType, System.Collections.Generic.List< T >.Count, System.Threading.Thread.CurrentThread, System.Threading.Monitor.Enter(), System.Threading.Monitor.Exit(), Microsoft.Xna.Framework.WindowsManagedCallbackHandler.nativeToManagedCallbacks, System.Collections.Generic.List< T >.RemoveAt(), Microsoft.Xna.Framework.IProxyProcessHandler.SharedAsyncDataSafeToWrite, and System.IntPtr.ToPointer().