Terraria: Microsoft.Xna.Framework.WindowsManagedCallbackHandler.RegisterNativeToManagedCallbackImpl
RegisterNativeToManagedCallbackImpl()
unsafe int Microsoft.Xna.Framework.WindowsManagedCallbackHandler.RegisterNativeToManagedCallbackImpl (void * waitForThisHandle, delegate *< void *, void *, ManagedCallType *, uint *, bool *, int > eventSignalledFunc, void * pContext) inline private
Definition at line 326 of file WindowsManagedCallbackHandler.cs.
    {
        if (waitForThisHandle != null && eventSignalledFunc != (delegate*<void*, void*, ManagedCallType*, uint*, bool*, int>)null)
        {
            void* ptr = null;
            int num = ((global::_003CModule_003E.DuplicateHandle(global::_003CModule_003E.GetCurrentProcess(), waitForThisHandle, global::_003CModule_003E.GetCurrentProcess(), &ptr, 0u, 0, 2u) == 0) ? (-2147467259) : 0);
            int num2 = num;
            if (num < 0)
            {
                if (ptr != null && ptr != (void*)(-1))
                {
                    global::_003CModule_003E.CloseHandle(ptr);
                }
                return num;
            }
            bool lockTaken = false;
            try
            {
                Monitor.Enter(nativeToManagedCallbacks, ref lockTaken);
                num2 = HasRoomForAnotherWaitHandle();
                if (num2 >= 0)
                {
                    NativeToManagedCallback item = new NativeToManagedCallback(waitForThisHandle, ptr, eventSignalledFunc, pContext);
                    nativeToManagedCallbacks.Add(item);
                    if (global::_003CModule_003E.SetEvent(_newCallbackRegistered) == 0)
                    {
                        uint lastError = global::_003CModule_003E.GetLastError();
                        num2 = (((int)lastError > 0) ? ((int)(lastError & 0xFFFF) | -2147024896) : ((int)lastError));
                    }
                    if (num2 < 0)
                    {
                        nativeToManagedCallbacks.RemoveAt(nativeToManagedCallbacks.Count - 1);
                    }
                }
            }
            finally
            {
                if (lockTaken)
                {
                    Monitor.Exit(nativeToManagedCallbacks);
                }
            }
            return num2;
        }
        return -2147024809;
    }
References Microsoft.Xna.Framework.WindowsManagedCallbackHandler._newCallbackRegistered, System.Collections.Generic.List< T >.Add(), System.Collections.Generic.List< T >.Count, System.Threading.Monitor.Enter(), System.Threading.Monitor.Exit(), Microsoft.Xna.Framework.WindowsManagedCallbackHandler.HasRoomForAnotherWaitHandle(), System.item, Microsoft.Xna.Framework.WindowsManagedCallbackHandler.nativeToManagedCallbacks, and System.Collections.Generic.List< T >.RemoveAt().