Terraria: Terraria.Social.Steam.NetClientSocialModule.ConnectToLobby
ConnectToLobby()
void Terraria.Social.Steam.NetClientSocialModule.ConnectToLobby (ulong lobbyId) inline
Definition at line 51 of file NetClientSocialModule.cs.
    {
        //IL_000f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0014: Unknown result type (might be due to invalid IL or missing references)
        CSteamID lobbySteamId = new CSteamID(lobbyId);
        if (((CSteamID)(ref lobbySteamId)).IsValid())
        {
            Main.OpenPlayerSelect(delegate(PlayerFileData playerData)
            {
                //IL_0041: Unknown result type (might be due to invalid IL or missing references)
                Main.ServerSideCharacter = false;
                playerData.SetAsActive();
                Main.menuMode = 882;
                Main.statusText = Language.GetTextValue("Social.Joining");
                WeGameHelper.WriteDebugString(" CheckParameters， lobby.join");
                _lobby.Join(lobbySteamId, OnLobbyEntered);
            });
        }
    }
References Terraria.Social.Steam.NetSocialModule._lobby, Terraria.Localization.Language.GetTextValue(), Terraria.Social.Steam.Lobby.Join(), Terraria.Social.Steam.NetClientSocialModule.OnLobbyEntered(), Terraria.Main.OpenPlayerSelect(), Terraria.IO.PlayerFileData.SetAsActive(), and Terraria.Social.WeGame.WeGameHelper.WriteDebugString().
Referenced by Terraria.Social.Steam.NetClientSocialModule.CheckParameters().