Terraria: Terraria.Social.Steam.NetClientSocialModule.LaunchLocalServer
LaunchLocalServer()
override void Terraria.Social.Steam.NetClientSocialModule.LaunchLocalServer (Process process, ServerMode mode) inline
Definition at line 71 of file NetClientSocialModule.cs.
    {
        //IL_0039: Unknown result type (might be due to invalid IL or missing references)
        WeGameHelper.WriteDebugString("LaunchLocalServer");
        if (_lobby.State != 0)
        {
            _lobby.Leave();
        }
        ProcessStartInfo startInfo = process.StartInfo;
        startInfo.Arguments = startInfo.Arguments + " -steam -localsteamid " + SteamUser.GetSteamID().m_SteamID;
        if (mode.HasFlag(ServerMode.Lobby))
        {
            _hasLocalHost = true;
            if (mode.HasFlag(ServerMode.FriendsCanJoin))
            {
                process.StartInfo.Arguments += " -lobby friends";
            }
            else
            {
                process.StartInfo.Arguments += " -lobby private";
            }
            if (mode.HasFlag(ServerMode.FriendsOfFriends))
            {
                process.StartInfo.Arguments += " -friendsoffriends";
            }
        }
        SteamFriends.SetRichPresence("status", Language.GetTextValue("Social.StatusInGame"));
        Netplay.OnDisconnect += OnDisconnect;
        process.Start();
    }
References Terraria.Social.Steam.NetClientSocialModule._hasLocalHost, Terraria.Social.Steam.NetSocialModule._lobby, Terraria.Localization.Language.GetTextValue(), Terraria.Social.Steam.Lobby.Leave(), Terraria.Social.Steam.NetClientSocialModule.OnDisconnect(), System.Diagnostics.Process.Start(), System.Diagnostics.Process.StartInfo, Terraria.Social.Steam.Lobby.State, and Terraria.Social.WeGame.WeGameHelper.WriteDebugString().