Terraria: Terraria.Social.Steam.NetClientSocialModule.OnSessionConnectFail
OnSessionConnectFail()
void Terraria.Social.Steam.NetClientSocialModule.OnSessionConnectFail (P2PSessionConnectFail_t result) inline private
Definition at line 299 of file NetClientSocialModule.cs.
    {
        //IL_0011: Unknown result type (might be due to invalid IL or missing references)
        //IL_0012: Unknown result type (might be due to invalid IL or missing references)
        WeGameHelper.WriteDebugString(" OnSessionConnectFail");
        Close(result.m_steamIDRemote);
    }
References Terraria.Social.Steam.NetClientSocialModule.Close(), and Terraria.Social.WeGame.WeGameHelper.WriteDebugString().
Referenced by Terraria.Social.Steam.NetClientSocialModule.Initialize().