Terraria: Terraria.Social.Steam.NetClientSocialModule.OnLobbyEntered
OnLobbyEntered()
void Terraria.Social.Steam.NetClientSocialModule.OnLobbyEntered (LobbyEnter_t result, bool failure) inline private
Definition at line 195 of file NetClientSocialModule.cs.
    {
        //IL_001e: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a4: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ca: Unknown result type (might be due to invalid IL or missing references)
        //IL_00db: Unknown result type (might be due to invalid IL or missing references)
        //IL_0127: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b2: Unknown result type (might be due to invalid IL or missing references)
        //IL_002c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0082: Unknown result type (might be due to invalid IL or missing references)
        //IL_0094: Unknown result type (might be due to invalid IL or missing references)
        WeGameHelper.WriteDebugString(" OnLobbyEntered");
        SteamNetworking.AllowP2PPacketRelay(true);
        SendAuthTicket(_lobby.Owner);
        int num = 0;
        P2PSessionState_t val = default(P2PSessionState_t);
        while (SteamNetworking.GetP2PSessionState(_lobby.Owner, ref val) && val.m_bConnectionActive != 1)
        {
            switch (val.m_eP2PSessionError)
            {
            case 2:
                ClearAuthTicket();
                return;
            case 1:
                ClearAuthTicket();
                return;
            case 3:
                ClearAuthTicket();
                return;
            case 5:
                ClearAuthTicket();
                return;
            case 4:
                if (++num > 5)
                {
                    ClearAuthTicket();
                    return;
                }
                SteamNetworking.CloseP2PSessionWithUser(_lobby.Owner);
                SendAuthTicket(_lobby.Owner);
                break;
            }
        }
        _connectionStateMap[_lobby.Owner] = ConnectionState.Connected;
        SteamFriends.SetPlayedWith(_lobby.Owner);
        SteamFriends.SetRichPresence("status", Language.GetTextValue("Social.StatusInGame"));
        Main.clrInput();
        Netplay.ServerPassword = "";
        Main.GetInputText("");
        Main.autoPass = false;
        Main.netMode = 1;
        Netplay.OnConnectedToSocialServer(new SocialSocket(new SteamAddress(_lobby.Owner)));
    }
References Terraria.Social.Steam.NetSocialModule._connectionStateMap, Terraria.Social.Steam.NetSocialModule._lobby, Terraria.Social.Steam.NetClientSocialModule.ClearAuthTicket(), Terraria.Main.clrInput(), Terraria.Main.GetInputText(), Terraria.Localization.Language.GetTextValue(), Terraria.Netplay.OnConnectedToSocialServer(), Terraria.Social.Steam.Lobby.Owner, Terraria.Social.Steam.NetClientSocialModule.SendAuthTicket(), and Terraria.Social.WeGame.WeGameHelper.WriteDebugString().
Referenced by Terraria.Social.Steam.NetClientSocialModule.ConnectToLobby(), and Terraria.Social.Steam.NetClientSocialModule.OnLobbyJoinRequest().