Terraria: Terraria.Social.Steam.NetClientSocialModule.Initialize
Initialize()
override void Terraria.Social.Steam.NetClientSocialModule.Initialize () inline
Implements Terraria.Social.ISocialModule.
Definition at line 34 of file NetClientSocialModule.cs.
    {
        base.Initialize();
        _gameLobbyJoinRequested = Callback<GameLobbyJoinRequested_t>.Create((DispatchDelegate<GameLobbyJoinRequested_t>)OnLobbyJoinRequest);
        _p2pSessionRequest = Callback<P2PSessionRequest_t>.Create((DispatchDelegate<P2PSessionRequest_t>)OnP2PSessionRequest);
        _p2pSessionConnectfail = Callback<P2PSessionConnectFail_t>.Create((DispatchDelegate<P2PSessionConnectFail_t>)OnSessionConnectFail);
        Main.OnEngineLoad += CheckParameters;
    }
References Terraria.Social.Steam.NetClientSocialModule._gameLobbyJoinRequested, Terraria.Social.Steam.NetClientSocialModule._p2pSessionConnectfail, Terraria.Social.Steam.NetClientSocialModule._p2pSessionRequest, Terraria.Social.Steam.NetClientSocialModule.CheckParameters(), Terraria.Social.Steam.NetClientSocialModule.OnLobbyJoinRequest(), Terraria.Social.Steam.NetClientSocialModule.OnP2PSessionRequest(), and Terraria.Social.Steam.NetClientSocialModule.OnSessionConnectFail().