Terraria: Terraria.Social.Steam.NetClientSocialModule.Close
Close() [1/2]
void Terraria.Social.Steam.NetClientSocialModule.Close (CSteamID user) inline private
    {
        //IL_0006: Unknown result type (might be due to invalid IL or missing references)
        //IL_000f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0022: Unknown result type (might be due to invalid IL or missing references)
        //IL_003a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0046: Unknown result type (might be due to invalid IL or missing references)
        if (_connectionStateMap.ContainsKey(user))
        {
            SteamNetworking.CloseP2PSessionWithUser(user);
            ClearAuthTicket();
            _connectionStateMap[user] = ConnectionState.Inactive;
            _lobby.Leave();
            _reader.ClearUser(user);
            _writer.ClearUser(user);
        }
    }
References Terraria.Social.Steam.NetSocialModule._connectionStateMap, Terraria.Social.Steam.NetSocialModule._lobby, Terraria.Social.Steam.NetSocialModule._reader, Terraria.Social.Steam.NetSocialModule._writer, Terraria.Social.Steam.NetClientSocialModule.ClearAuthTicket(), Terraria.Social.Steam.SteamP2PReader.ClearUser(), Terraria.Social.Steam.SteamP2PWriter.ClearUser(), and Terraria.Social.Steam.Lobby.Leave().