Terraria: Terraria.Social.Steam.NetClientSocialModule.OnLobbyJoinRequest
OnLobbyJoinRequest()
void Terraria.Social.Steam.NetClientSocialModule.OnLobbyJoinRequest (GameLobbyJoinRequested_t result) inline private
    {
        //IL_000e: Unknown result type (might be due to invalid IL or missing references)
        //IL_000f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0043: Unknown result type (might be due to invalid IL or missing references)
        WeGameHelper.WriteDebugString(" OnLobbyJoinRequest");
        if (_lobby.State != 0)
        {
            _lobby.Leave();
        }
        string friendName = SteamFriends.GetFriendPersonaName(result.m_steamIDFriend);
        Main.QueueMainThreadAction(delegate
        {
            Main.OpenPlayerSelect(delegate(PlayerFileData playerData)
            {
                //IL_003c: Unknown result type (might be due to invalid IL or missing references)
                Main.ServerSideCharacter = false;
                playerData.SetAsActive();
                Main.menuMode = 882;
                Main.statusText = Language.GetTextValue("Social.JoiningFriend", friendName);
                _lobby.Join(result.m_steamIDLobby, OnLobbyEntered);
            });
        });
    }
References Terraria.Social.Steam.NetSocialModule._lobby, Terraria.Localization.Language.GetTextValue(), Terraria.Social.Steam.Lobby.Join(), Terraria.Social.Steam.Lobby.Leave(), Terraria.Social.Steam.NetClientSocialModule.OnLobbyEntered(), Terraria.Main.OpenPlayerSelect(), Terraria.Main.QueueMainThreadAction(), Terraria.IO.PlayerFileData.SetAsActive(), Terraria.Social.Steam.Lobby.State, and Terraria.Social.WeGame.WeGameHelper.WriteDebugString().
Referenced by Terraria.Social.Steam.NetClientSocialModule.Initialize().