Terraria: System.Security.Cryptography.ECDiffieHellmanPublicKey.ExportParameters
ExportParameters()
virtual ECParameters System.Security.Cryptography.ECDiffieHellmanPublicKey.ExportParameters () inline virtual
Reimplemented in System.Security.Cryptography.ECDiffieHellmanImplementation.ECDiffieHellmanCngPublicKey, and System.Security.Cryptography.ECDiffieHellmanCngPublicKey.
Definition at line 42 of file ECDiffieHellmanPublicKey.cs.
    {
        throw new NotSupportedException(System.SR.NotSupported_SubclassOverride);
    }
References System.SR.NotSupported_SubclassOverride.
Referenced by System.Security.Cryptography.ECDiffieHellmanCng.DeriveKeyMaterial(), System.Security.Cryptography.ECDiffieHellmanImplementation.ECDiffieHellmanCng.DeriveSecretAgreementHandle(), System.Security.Cryptography.ECDiffieHellmanCng.DeriveSecretAgreementHandle(), System.Security.Cryptography.ECDiffieHellmanPublicKey.ExportSubjectPublicKeyInfo(), and System.Security.Cryptography.ECDiffieHellmanPublicKey.TryExportSubjectPublicKeyInfo().