Terraria: System.Collections.Immutable.ImmutableList.Enumerator.Enumerator
Enumerator()
System.Collections.Immutable.ImmutableList< T >.Enumerator.Enumerator (Node root, Builder? builder = null, int startIndex = -1, int count = -1, bool reversed = false) inline package
Definition at line 594 of file ImmutableList.cs.
        {
            Requires.NotNull(root, "root");
            Requires.Range(startIndex >= -1, "startIndex");
            Requires.Range(count >= -1, "count");
            Requires.Argument(reversed || count == -1 || ((startIndex != -1) ? startIndex : 0) + count <= root.Count);
            Requires.Argument(!reversed || count == -1 || ((startIndex == -1) ? (root.Count - 1) : startIndex) - count + 1 >= 0);
            _root = root;
            _builder = builder;
            _current = null;
            _startIndex = ((startIndex >= 0) ? startIndex : (reversed ? (root.Count - 1) : 0));
            _count = ((count == -1) ? root.Count : count);
            _remainingCount = _count;
            _reversed = reversed;
            _enumeratingBuilderVersion = builder?.Version ?? (-1);
            _poolUserId = SecureObjectPool.NewId();
            _stack = null;
            if (_count > 0)
            {
                if (!s_EnumeratingStacks.TryTake(this, out _stack))
                {
                    _stack = s_EnumeratingStacks.PrepNew(this, new Stack<RefAsValueType<Node>>(root.Height));
                }
                ResetStack();
            }
        }
References System.Collections.Immutable.ImmutableList< T >.Enumerator._builder, System.Collections.Immutable.ImmutableList< T >.Enumerator._count, System.Collections.Immutable.ImmutableList< T >.Enumerator._current, System.Collections.Immutable.ImmutableList< T >.Enumerator._enumeratingBuilderVersion, System.Collections.Immutable.ImmutableList< T >.Enumerator._poolUserId, System.Collections.Immutable.ImmutableList< T >.Enumerator._remainingCount, System.Collections.Immutable.ImmutableList< T >.Enumerator._reversed, System.Collections.Immutable.ImmutableList< T >.Enumerator._root, System.Collections.Immutable.ImmutableList< T >.Enumerator._stack, System.Collections.Immutable.ImmutableList< T >.Enumerator._startIndex, System.Collections.Immutable.Requires.Argument(), System.Collections.Immutable.ImmutableList< T >.Node.Count, System.count, System.Collections.Immutable.ImmutableList< T >.Node.Height, System.Collections.Immutable.SecureObjectPool< T, TCaller >.NewId(), System.Collections.Immutable.Requires.Range(), System.Collections.Immutable.ImmutableList< T >.Enumerator.ResetStack(), System.Collections.Immutable.ImmutableList< T >.Enumerator.s_EnumeratingStacks, and System.startIndex.