Terraria: System.Collections.Immutable.ImmutableList.Enumerator.MoveNext
MoveNext()
bool System.Collections.Immutable.ImmutableList< T >.Enumerator.MoveNext () inline
Implements System.Collections.IEnumerator.
Definition at line 633 of file ImmutableList.cs.
        {
            ThrowIfDisposed();
            ThrowIfChanged();
            if (_stack != null)
            {
                Stack<RefAsValueType<Node>> stack = _stack.Use(ref this);
                if (_remainingCount > 0 && stack.Count > 0)
                {
                    PushNext(NextBranch(_current = stack.Pop().Value));
                    _remainingCount--;
                    return true;
                }
            }
            _current = null;
            return false;
        }
References System.Collections.Immutable.ImmutableList< T >.Enumerator._current, System.Collections.Immutable.ImmutableList< T >.Enumerator._remainingCount, System.Collections.Immutable.ImmutableList< T >.Enumerator._stack, System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Collections.Immutable.ImmutableList< T >.Enumerator.NextBranch(), System.Collections.Immutable.ImmutableList< T >.Enumerator.PushNext(), System.Collections.Immutable.ImmutableList< T >.Enumerator.ThrowIfChanged(), and System.Collections.Immutable.ImmutableList< T >.Enumerator.ThrowIfDisposed().