Terraria: GameSenseConnection.BeginConnection
BeginConnection()
void GameSenseConnection.BeginConnection () inline
     {
         //IL_0001: Unknown result type (might be due to invalid IL or missing references)
         //IL_000b: Expected O, but got Unknown
         _mSerializer = new fsSerializer();
         _mMsgQueue = new LocklessQueue<QueueMsg>(100u);
         _gameSenseThread = new Thread(_gamesenseWrk);
         _mGameSenseWrkShouldRun = true;
         _setClientState((ClientState)1);
         try
         {
             _gameSenseThread.Start();
             _addGUIDefinedEvents();
         }
         catch (Exception e)
         {
             _logException("Could not start the client thread", e);
             _setClientState((ClientState)2);
         }
     }
References _addGUIDefinedEvents(), _gameSenseThread, _gamesenseWrk(), _logException(), _mGameSenseWrkShouldRun, _mMsgQueue, _mSerializer, and _setClientState().
Referenced by SteelSeriesDeviceGroup.ConnectToGameSense().