Terraria: Internal.Cryptography.Pal.ChainPal.GetChainEngine
GetChainEngine()
static SafeChainEngineHandle Internal.Cryptography.Pal.ChainPal.GetChainEngine (X509ChainTrustMode trustMode, X509Certificate2Collection customTrustStore, bool useMachineContext) inline static private
Definition at line 127 of file ChainPal.cs.
    {
        if (trustMode == X509ChainTrustMode.CustomRootTrust)
        {
            using (SafeCertStoreHandle safeCertStoreHandle = ConvertStoreToSafeHandle(customTrustStore, returnEmptyHandle: true))
            {
                CERT_CHAIN_ENGINE_CONFIG config = default(CERT_CHAIN_ENGINE_CONFIG);
                config.cbSize = Marshal.SizeOf<CERT_CHAIN_ENGINE_CONFIG>();
                config.hExclusiveRoot = safeCertStoreHandle.DangerousGetHandle();
                return global::Interop.crypt32.CertCreateCertificateChainEngine(ref config);
            }
        }
        return useMachineContext ? SafeChainEngineHandle.MachineChainEngine : SafeChainEngineHandle.UserChainEngine;
    }
References Internal.Cryptography.Pal.ChainPal.ConvertStoreToSafeHandle(), System.Runtime.InteropServices.Marshal.SizeOf(), and Internal.Cryptography.Pal.Native.SafeChainEngineHandle.UserChainEngine.
Referenced by Internal.Cryptography.Pal.ChainPal.BuildChain().