Terraria: Internal.Cryptography.Pal.ChainPal.BuildChain
BuildChain()
static unsafe ChainPal Internal.Cryptography.Pal.ChainPal.BuildChain (bool useMachineContext, ICertificatePal cert, X509Certificate2Collection extraStore, OidCollection applicationPolicy, OidCollection certificatePolicy, X509RevocationMode revocationMode, X509RevocationFlag revocationFlag, X509Certificate2Collection customTrustStore, X509ChainTrustMode trustMode, DateTime verificationTime, TimeSpan timeout, bool disableAia) inline static
Definition at line 94 of file ChainPal.cs.
    {
        CertificatePal certificatePal = (CertificatePal)cert;
        using SafeChainEngineHandle safeChainEngineHandle = GetChainEngine(trustMode, customTrustStore, useMachineContext);
        using SafeCertStoreHandle hStore = ConvertStoreToSafeHandle(extraStore);
        CERT_CHAIN_PARA pChainPara = default(CERT_CHAIN_PARA);
        pChainPara.cbSize = Marshal.SizeOf<CERT_CHAIN_PARA>();
        int numOids;
        using SafeHandle safeHandle = applicationPolicy.ToLpstrArray(out numOids);
        if (!safeHandle.IsInvalid)
        {
            pChainPara.RequestedUsage.dwType = CertUsageMatchType.USAGE_MATCH_TYPE_AND;
            pChainPara.RequestedUsage.Usage.cUsageIdentifier = numOids;
            pChainPara.RequestedUsage.Usage.rgpszUsageIdentifier = safeHandle.DangerousGetHandle();
        }
        int numOids2;
        using SafeHandle safeHandle2 = certificatePolicy.ToLpstrArray(out numOids2);
        if (!safeHandle2.IsInvalid)
        {
            pChainPara.RequestedIssuancePolicy.dwType = CertUsageMatchType.USAGE_MATCH_TYPE_AND;
            pChainPara.RequestedIssuancePolicy.Usage.cUsageIdentifier = numOids2;
            pChainPara.RequestedIssuancePolicy.Usage.rgpszUsageIdentifier = safeHandle2.DangerousGetHandle();
        }
        pChainPara.dwUrlRetrievalTimeout = (int)Math.Floor(timeout.TotalMilliseconds);
        FILETIME fILETIME = FILETIME.FromDateTime(verificationTime);
        CertChainFlags dwFlags = MapRevocationFlags(revocationMode, revocationFlag, disableAia);
        if (!global::Interop.crypt32.CertGetCertificateChain(safeChainEngineHandle.DangerousGetHandle(), certificatePal.CertContext, &fILETIME, hStore, ref pChainPara, dwFlags, IntPtr.Zero, out var ppChainContext))
        {
            return null;
        }
        return new ChainPal(ppChainContext);
    }
References Internal.Cryptography.Pal.ChainPal.ChainPal(), Internal.Cryptography.Pal.CertificatePal.CertContext, Internal.Cryptography.Pal.ChainPal.ConvertStoreToSafeHandle(), System.Math.Floor(), Internal.Cryptography.Pal.Native.FILETIME.FromDateTime(), Internal.Cryptography.Pal.ChainPal.GetChainEngine(), Internal.Cryptography.Pal.ChainPal.MapRevocationFlags(), System.Runtime.InteropServices.Marshal.SizeOf(), System.timeout, and System.IntPtr.Zero.
Referenced by System.Security.Cryptography.X509Certificates.X509Chain.Build(), and Internal.Cryptography.Pal.FindPal.VerifyCertificateIgnoringErrors().