Terraria: System.Linq.Expressions.BinaryExpression.ReduceUserdefinedLifted
ReduceUserdefinedLifted()
Expression System.Linq.Expressions.BinaryExpression.ReduceUserdefinedLifted () inline package inherited
Definition at line 256 of file BinaryExpression.cs.
    {
        ParameterExpression parameterExpression = Expression.Parameter(Left.Type, "left");
        ParameterExpression parameterExpression2 = Expression.Parameter(Right.Type, "right");
        string name = ((NodeType == ExpressionType.AndAlso) ? "op_False" : "op_True");
        MethodInfo booleanOperator = TypeUtils.GetBooleanOperator(Method.DeclaringType, name);
        return Expression.Block(new TrueReadOnlyCollection<ParameterExpression>(parameterExpression), new TrueReadOnlyCollection<Expression>(Expression.Assign(parameterExpression, Left), Expression.Condition(GetHasValueProperty(parameterExpression), Expression.Condition(Expression.Call(booleanOperator, CallGetValueOrDefault(parameterExpression)), parameterExpression, Expression.Block(new TrueReadOnlyCollection<ParameterExpression>(parameterExpression2), new TrueReadOnlyCollection<Expression>(Expression.Assign(parameterExpression2, Right), Expression.Condition(GetHasValueProperty(parameterExpression2), Expression.Convert(Expression.Call(Method, CallGetValueOrDefault(parameterExpression), CallGetValueOrDefault(parameterExpression2)), Type), Expression.Constant(null, Type))))), Expression.Constant(null, Type))));
    }
References System.Linq.Expressions.Expression< TDelegate >.Assign(), System.Linq.Expressions.Expression< TDelegate >.Block(), System.Linq.Expressions.Expression< TDelegate >.Call(), System.Linq.Expressions.BinaryExpression.CallGetValueOrDefault(), System.Linq.Expressions.Expression< TDelegate >.Condition(), System.Linq.Expressions.Expression< TDelegate >.Constant(), System.Linq.Expressions.Expression< TDelegate >.Convert(), System.Reflection.MemberInfo.DeclaringType, System.Dynamic.Utils.TypeUtils.GetBooleanOperator(), System.Linq.Expressions.BinaryExpression.GetHasValueProperty(), System.Linq.Expressions.BinaryExpression.Left, System.Linq.Expressions.BinaryExpression.Method, System.Linq.Expressions.Expression< TDelegate >.NodeType, System.Linq.Expressions.Expression< TDelegate >.Parameter(), System.Linq.Expressions.BinaryExpression.Right, and System.Linq.Expressions.Expression< TDelegate >.Type.