Terraria: System.Linq.Expressions.BinaryExpression.Reduce
Reduce()
override Expression System.Linq.Expressions.BinaryExpression.Reduce () inline virtual inherited
Reimplemented from System.Linq.Expressions.Expression< TDelegate >.
Definition at line 125 of file BinaryExpression.cs.
    {
        if (IsOpAssignment(NodeType))
        {
            return Left.NodeType switch
            {
                ExpressionType.MemberAccess => ReduceMember(),
                ExpressionType.Index => ReduceIndex(),
                _ => ReduceVariable(),
            };
        }
        return this;
    }
References System.Linq.Expressions.BinaryExpression.IsOpAssignment(), System.Linq.Expressions.Expression< TDelegate >.NodeType, System.Linq.Expressions.BinaryExpression.ReduceIndex(), System.Linq.Expressions.BinaryExpression.ReduceMember(), and System.Linq.Expressions.BinaryExpression.ReduceVariable().