Terraria: UIWorkshopWorldImport.UpdateWorkshopWorldList
UpdateWorkshopWorldList()
void UIWorkshopWorldImport.UpdateWorkshopWorldList () inline
     {
         WorkshopWorldList.Clear();
         if (SocialAPI.Workshop == null)
         {
             return;
         }
         foreach (string listOfSubscribedWorldPath in SocialAPI.Workshop.GetListOfSubscribedWorldPaths())
         {
             WorldFileData allMetadata = WorldFile.GetAllMetadata(listOfSubscribedWorldPath, cloudSave: false);
             if (allMetadata != null)
             {
                 WorkshopWorldList.Add(allMetadata);
             }
             else
             {
                 WorkshopWorldList.Add(WorldFileData.FromInvalidWorld(listOfSubscribedWorldPath, cloudSave: false));
             }
         }
     }
References WorldFileData.FromInvalidWorld(), WorldFile.GetAllMetadata(), WorkshopSocialModule.GetListOfSubscribedWorldPaths(), SocialAPI.Workshop, and WorkshopWorldList.
Referenced by OnActivate().