Terraria: System.Linq.Expressions.BinaryExpression.ReduceMember
ReduceMember()
Expression System.Linq.Expressions.BinaryExpression.ReduceMember () inline private inherited
Definition at line 173 of file BinaryExpression.cs.
    {
        MemberExpression memberExpression = (MemberExpression)Left;
        if (memberExpression.Expression == null)
        {
            return ReduceVariable();
        }
        ParameterExpression parameterExpression = Expression.Variable(memberExpression.Expression.Type, "temp1");
        Expression expression = Expression.Assign(parameterExpression, memberExpression.Expression);
        ExpressionType binaryOpFromAssignmentOp = GetBinaryOpFromAssignmentOp(NodeType);
        Expression expression2 = Expression.MakeBinary(binaryOpFromAssignmentOp, Expression.MakeMemberAccess(parameterExpression, memberExpression.Member), Right, liftToNull: false, Method);
        LambdaExpression conversion = GetConversion();
        if (conversion != null)
        {
            expression2 = Expression.Invoke(conversion, expression2);
        }
        ParameterExpression parameterExpression2 = Expression.Variable(expression2.Type, "temp2");
        expression2 = Expression.Assign(parameterExpression2, expression2);
        Expression expression3 = Expression.Assign(Expression.MakeMemberAccess(parameterExpression, memberExpression.Member), parameterExpression2);
        Expression expression4 = parameterExpression2;
        return Expression.Block(new TrueReadOnlyCollection<ParameterExpression>(parameterExpression, parameterExpression2), new TrueReadOnlyCollection<Expression>(expression, expression2, expression3, expression4));
    }
References System.Linq.Expressions.Expression< TDelegate >.Assign(), System.Linq.Expressions.Expression< TDelegate >.Block(), System.Linq.Expressions.BinaryExpression.GetBinaryOpFromAssignmentOp(), System.Linq.Expressions.BinaryExpression.GetConversion(), System.Linq.Expressions.Expression< TDelegate >.Invoke(), System.Linq.Expressions.BinaryExpression.Left, System.Linq.Expressions.Expression< TDelegate >.MakeBinary(), System.Linq.Expressions.Expression< TDelegate >.MakeMemberAccess(), System.Linq.Expressions.BinaryExpression.Method, System.Linq.Expressions.Expression< TDelegate >.NodeType, System.Linq.Expressions.BinaryExpression.ReduceVariable(), System.Linq.Expressions.BinaryExpression.Right, and System.Linq.Expressions.Expression< TDelegate >.Variable().
Referenced by System.Linq.Expressions.BinaryExpression.Reduce().