Terraria: System.Linq.Expressions.BinaryExpression.Update
Update() [2/2]
BinaryExpression System.Linq.Expressions.BinaryExpression.Update (Expression left, LambdaExpression? conversion, Expression right) inline inherited
Definition at line 108 of file BinaryExpression.cs.
    {
        if (left == Left && right == Right && conversion == Conversion)
        {
            return this;
        }
        if (IsReferenceComparison)
        {
            if (NodeType == ExpressionType.Equal)
            {
                return Expression.ReferenceEqual(left, right);
            }
            return Expression.ReferenceNotEqual(left, right);
        }
        return Expression.MakeBinary(NodeType, left, right, IsLiftedToNull, Method, conversion);
    }
References System.Linq.Expressions.BinaryExpression.Conversion, System.Linq.Expressions.BinaryExpression.IsLiftedToNull, System.Linq.Expressions.BinaryExpression.IsReferenceComparison, System.Linq.Expressions.BinaryExpression.Left, System.Linq.Expressions.Expression< TDelegate >.MakeBinary(), System.Linq.Expressions.BinaryExpression.Method, System.Linq.Expressions.Expression< TDelegate >.NodeType, System.Linq.Expressions.Expression< TDelegate >.ReferenceEqual(), System.Linq.Expressions.Expression< TDelegate >.ReferenceNotEqual(), and System.Linq.Expressions.BinaryExpression.Right.
Referenced by System.Linq.Expressions.ExpressionVisitor.VisitBinary().