Terraria: UIWorkshopWorldImport.OnActivate
OnActivate()
override void UIWorkshopWorldImport.OnActivate () inline virtual
Reimplemented from UIElement.
     {
         Main.LoadWorlds();
         UpdateWorkshopWorldList();
         UpdateWorldsList();
         if (PlayerInput.UsingGamepadUI)
         {
             UILinkPointNavigator.ChangePoint(3000 + ((_worldList.Count == 0) ? 1 : 2));
         }
     }
References _worldList, UILinkPointNavigator.ChangePoint(), UIList.Count, Main.LoadWorlds(), UpdateWorkshopWorldList(), UpdateWorldsList(), and PlayerInput.UsingGamepadUI.