Terraria: UIWorkshopWorldImport.UpdateWorldsList
UpdateWorldsList()
void UIWorkshopWorldImport.UpdateWorldsList () inline private
     {
         _worldList.Clear();
         IOrderedEnumerable<WorldFileData> orderedEnumerable = from x in new List<WorldFileData>(WorkshopWorldList)
             orderby x.IsFavorite descending, x.Name, x.GetFileName()
             select x;
         int num = 0;
         foreach (WorldFileData item in orderedEnumerable)
         {
             _worldList.Add(new UIWorkshopImportWorldListItem(this, item, num++));
         }
     }
References _worldList, UIList.Add(), UIList.Clear(), and WorkshopWorldList.
Referenced by OnActivate().