Terraria: System.Reflection.DispatchProxyGenerator.ProxyBuilder.CreateType
CreateType()
GeneratedTypeInfo System.Reflection.DispatchProxyGenerator.ProxyBuilder.CreateType () inline package
Definition at line 310 of file DispatchProxyGenerator.cs.
        {
            Complete();
            return new GeneratedTypeInfo(_tb.CreateType(), _methodInfos.ToArray());
        }
References System.Reflection.DispatchProxyGenerator.ProxyBuilder._methodInfos, System.Reflection.DispatchProxyGenerator.ProxyBuilder._tb, System.Reflection.DispatchProxyGenerator.ProxyBuilder.Complete(), System.Reflection.Emit.TypeBuilder.CreateType(), and System.Collections.Generic.List< T >.ToArray().