Terraria: System.Reflection.DispatchProxyGenerator.ProxyBuilder.Stind
Stind()
static void System.Reflection.DispatchProxyGenerator.ProxyBuilder.Stind (ILGenerator il, Type type) inline static private
Definition at line 650 of file DispatchProxyGenerator.cs.
        {
            OpCode opcode = s_stindOpCodes[GetTypeCode(type)];
            if (!opcode.Equals(OpCodes.Nop))
            {
                il.Emit(opcode);
            }
            else
            {
                il.Emit(OpCodes.Stobj, type);
            }
        }
References System.Reflection.Emit.OpCode.Equals(), System.Reflection.DispatchProxyGenerator.ProxyBuilder.GetTypeCode(), System.Reflection.Emit.OpCodes.Nop, System.Reflection.DispatchProxyGenerator.ProxyBuilder.s_stindOpCodes, System.Reflection.Emit.OpCodes.Stobj, and System.type.
Referenced by System.Reflection.DispatchProxyGenerator.ProxyBuilder.ParametersArray.EndSet().