Terraria: System.Reflection.DispatchProxyGenerator.ProxyBuilder.GetTypeCode
GetTypeCode()
static int System.Reflection.DispatchProxyGenerator.ProxyBuilder.GetTypeCode (Type type) inline static private
Definition at line 517 of file DispatchProxyGenerator.cs.
        {
            if (type == null)
            {
                return 0;
            }
            if (type == typeof(bool))
            {
                return 3;
            }
            if (type == typeof(char))
            {
                return 4;
            }
            if (type == typeof(sbyte))
            {
                return 5;
            }
            if (type == typeof(byte))
            {
                return 6;
            }
            if (type == typeof(short))
            {
                return 7;
            }
            if (type == typeof(ushort))
            {
                return 8;
            }
            if (type == typeof(int))
            {
                return 9;
            }
            if (type == typeof(uint))
            {
                return 10;
            }
            if (type == typeof(long))
            {
                return 11;
            }
            if (type == typeof(ulong))
            {
                return 12;
            }
            if (type == typeof(float))
            {
                return 13;
            }
            if (type == typeof(double))
            {
                return 14;
            }
            if (type == typeof(decimal))
            {
                return 15;
            }
            if (type == typeof(DateTime))
            {
                return 16;
            }
            if (type == typeof(string))
            {
                return 18;
            }
            if (type.IsEnum)
            {
                return GetTypeCode(Enum.GetUnderlyingType(type));
            }
            return 1;
        }
References System.Reflection.DispatchProxyGenerator.ProxyBuilder.GetTypeCode(), System.Enum.GetUnderlyingType(), and System.type.
Referenced by System.Reflection.DispatchProxyGenerator.ProxyBuilder.Convert(), System.Reflection.DispatchProxyGenerator.ProxyBuilder.GetTypeCode(), System.Reflection.DispatchProxyGenerator.ProxyBuilder.Ldind(), and System.Reflection.DispatchProxyGenerator.ProxyBuilder.Stind().