Terraria: System.Reflection.DispatchProxyGenerator.ProxyBuilder.AddInterfaceImpl
AddInterfaceImpl()
void System.Reflection.DispatchProxyGenerator.ProxyBuilder.AddInterfaceImpl ([DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.All)] Type iface) inline package
Definition at line 316 of file DispatchProxyGenerator.cs.
        {
            _assembly.EnsureTypeIsVisible(iface);
            _tb.AddInterfaceImplementation(iface);
            Dictionary<MethodInfo, PropertyAccessorInfo> dictionary = new Dictionary<MethodInfo, PropertyAccessorInfo>();
            foreach (PropertyInfo runtimeProperty in iface.GetRuntimeProperties())
            {
                PropertyAccessorInfo value = new PropertyAccessorInfo(runtimeProperty.GetMethod, runtimeProperty.SetMethod);
                if (runtimeProperty.GetMethod != null)
                {
                    dictionary[runtimeProperty.GetMethod] = value;
                }
                if (runtimeProperty.SetMethod != null)
                {
                    dictionary[runtimeProperty.SetMethod] = value;
                }
            }
            Dictionary<MethodInfo, EventAccessorInfo> dictionary2 = new Dictionary<MethodInfo, EventAccessorInfo>();
            foreach (EventInfo runtimeEvent in iface.GetRuntimeEvents())
            {
                EventAccessorInfo value2 = new EventAccessorInfo(runtimeEvent.AddMethod, runtimeEvent.RemoveMethod, runtimeEvent.RaiseMethod);
                if (runtimeEvent.AddMethod != null)
                {
                    dictionary2[runtimeEvent.AddMethod] = value2;
                }
                if (runtimeEvent.RemoveMethod != null)
                {
                    dictionary2[runtimeEvent.RemoveMethod] = value2;
                }
                if (runtimeEvent.RaiseMethod != null)
                {
                    dictionary2[runtimeEvent.RaiseMethod] = value2;
                }
            }
            foreach (MethodInfo runtimeMethod in iface.GetRuntimeMethods())
            {
                if (!runtimeMethod.IsVirtual || runtimeMethod.IsFinal)
                {
                    continue;
                }
                int count = _methodInfos.Count;
                _methodInfos.Add(runtimeMethod);
                MethodBuilder methodBuilder = AddMethodImpl(runtimeMethod, count);
                if (dictionary.TryGetValue(runtimeMethod, out var value3))
                {
                    if (runtimeMethod.Equals(value3.InterfaceGetMethod))
                    {
                        value3.GetMethodBuilder = methodBuilder;
                    }
                    else
                    {
                        value3.SetMethodBuilder = methodBuilder;
                    }
                }
                if (dictionary2.TryGetValue(runtimeMethod, out var value4))
                {
                    if (runtimeMethod.Equals(value4.InterfaceAddMethod))
                    {
                        value4.AddMethodBuilder = methodBuilder;
                    }
                    else if (runtimeMethod.Equals(value4.InterfaceRemoveMethod))
                    {
                        value4.RemoveMethodBuilder = methodBuilder;
                    }
                    else
                    {
                        value4.RaiseMethodBuilder = methodBuilder;
                    }
                }
            }
            foreach (PropertyInfo runtimeProperty2 in iface.GetRuntimeProperties())
            {
                PropertyAccessorInfo propertyAccessorInfo = dictionary[runtimeProperty2.GetMethod ?? runtimeProperty2.SetMethod];
                if (!(propertyAccessorInfo.GetMethodBuilder == null) || !(propertyAccessorInfo.SetMethodBuilder == null))
                {
                    PropertyBuilder propertyBuilder = _tb.DefineProperty(runtimeProperty2.Name, runtimeProperty2.Attributes, runtimeProperty2.PropertyType, (from p in runtimeProperty2.GetIndexParameters()
                        select p.ParameterType).ToArray());
                    if (propertyAccessorInfo.GetMethodBuilder != null)
                    {
                        propertyBuilder.SetGetMethod(propertyAccessorInfo.GetMethodBuilder);
                    }
                    if (propertyAccessorInfo.SetMethodBuilder != null)
                    {
                        propertyBuilder.SetSetMethod(propertyAccessorInfo.SetMethodBuilder);
                    }
                }
            }
            foreach (EventInfo runtimeEvent2 in iface.GetRuntimeEvents())
            {
                EventAccessorInfo eventAccessorInfo = dictionary2[runtimeEvent2.AddMethod ?? runtimeEvent2.RemoveMethod];
                if (!(eventAccessorInfo.AddMethodBuilder == null) || !(eventAccessorInfo.RemoveMethodBuilder == null) || !(eventAccessorInfo.RaiseMethodBuilder == null))
                {
                    EventBuilder eventBuilder = _tb.DefineEvent(runtimeEvent2.Name, runtimeEvent2.Attributes, runtimeEvent2.EventHandlerType);
                    if (eventAccessorInfo.AddMethodBuilder != null)
                    {
                        eventBuilder.SetAddOnMethod(eventAccessorInfo.AddMethodBuilder);
                    }
                    if (eventAccessorInfo.RemoveMethodBuilder != null)
                    {
                        eventBuilder.SetRemoveOnMethod(eventAccessorInfo.RemoveMethodBuilder);
                    }
                    if (eventAccessorInfo.RaiseMethodBuilder != null)
                    {
                        eventBuilder.SetRaiseMethod(eventAccessorInfo.RaiseMethodBuilder);
                    }
                }
            }
        }
References System.Reflection.DispatchProxyGenerator.ProxyBuilder._assembly, System.Reflection.DispatchProxyGenerator.ProxyBuilder._methodInfos, System.Reflection.DispatchProxyGenerator.ProxyBuilder._tb, System.Collections.Generic.List< T >.Add(), System.Reflection.Emit.TypeBuilder.AddInterfaceImplementation(), System.Reflection.DispatchProxyGenerator.ProxyBuilder.AddMethodImpl(), System.count, System.Collections.Generic.List< T >.Count, System.Reflection.Emit.TypeBuilder.DefineEvent(), System.Reflection.Emit.TypeBuilder.DefineProperty(), System.dictionary, System.Reflection.DispatchProxyGenerator.ProxyAssembly.EnsureTypeIsVisible(), System.Collections.Generic.Dictionary< TKey, TValue >.TryGetValue(), and System.value.