Terraria: System.Reflection.DispatchProxyGenerator.ProxyBuilder.Convert
Convert()
static void System.Reflection.DispatchProxyGenerator.ProxyBuilder.Convert (ILGenerator il, Type source, Type target, bool isAddress) inline static private
Definition at line 590 of file DispatchProxyGenerator.cs.
        {
            if (target == source)
            {
                return;
            }
            if (source.IsByRef)
            {
                Type elementType = source.GetElementType();
                Ldind(il, elementType);
                Convert(il, elementType, target, isAddress);
            }
            else if (target.IsValueType)
            {
                if (source.IsValueType)
                {
                    OpCode opcode = s_convOpCodes[GetTypeCode(target)];
                    il.Emit(opcode);
                    return;
                }
                il.Emit(OpCodes.Unbox, target);
                if (!isAddress)
                {
                    Ldind(il, target);
                }
            }
            else if (target.IsAssignableFrom(source))
            {
                if (source.IsValueType || source.IsGenericParameter)
                {
                    if (isAddress)
                    {
                        Ldind(il, source);
                    }
                    il.Emit(OpCodes.Box, source);
                }
            }
            else if (target.IsGenericParameter)
            {
                il.Emit(OpCodes.Unbox_Any, target);
            }
            else
            {
                il.Emit(OpCodes.Castclass, target);
            }
        }
References System.Reflection.Emit.OpCodes.Box, System.Reflection.Emit.OpCodes.Castclass, System.Reflection.DispatchProxyGenerator.ProxyBuilder.Convert(), System.elementType, System.Type.GetElementType(), System.Reflection.DispatchProxyGenerator.ProxyBuilder.GetTypeCode(), System.Type.IsAssignableFrom(), System.Type.IsGenericParameter, System.Type.IsValueType, System.Reflection.DispatchProxyGenerator.ProxyBuilder.Ldind(), System.Reflection.DispatchProxyGenerator.ProxyBuilder.s_convOpCodes, System.source, System.Reflection.Emit.OpCodes.Unbox, and System.Reflection.Emit.OpCodes.Unbox_Any.
Referenced by System.Reflection.DispatchProxyGenerator.ProxyBuilder.AddMethodImpl(), System.Reflection.DispatchProxyGenerator.ProxyBuilder.Convert(), System.Reflection.DispatchProxyGenerator.ProxyBuilder.ParametersArray.EndSet(), and System.Reflection.DispatchProxyGenerator.ProxyBuilder.GenericArray< T >.EndSet().