Terraria: System.Reflection.DispatchProxyGenerator.ProxyBuilder.Ldind
Ldind()
static void System.Reflection.DispatchProxyGenerator.ProxyBuilder.Ldind (ILGenerator il, Type type) inline static private
Definition at line 637 of file DispatchProxyGenerator.cs.
        {
            OpCode opcode = s_ldindOpCodes[GetTypeCode(type)];
            if (!opcode.Equals(OpCodes.Nop))
            {
                il.Emit(opcode);
            }
            else
            {
                il.Emit(OpCodes.Ldobj, type);
            }
        }
References System.Reflection.Emit.OpCode.Equals(), System.Reflection.DispatchProxyGenerator.ProxyBuilder.GetTypeCode(), System.Reflection.Emit.OpCodes.Ldobj, System.Reflection.Emit.OpCodes.Nop, System.Reflection.DispatchProxyGenerator.ProxyBuilder.s_ldindOpCodes, and System.type.
Referenced by System.Reflection.DispatchProxyGenerator.ProxyBuilder.Convert().