Terraria: System.Reflection.DispatchProxyGenerator.ProxyBuilder.Complete
Complete()
void System.Reflection.DispatchProxyGenerator.ProxyBuilder.Complete () inline private
Definition at line 289 of file DispatchProxyGenerator.cs.
        {
            Type[] array = new Type[_fields.Count];
            for (int i = 0; i < array.Length; i++)
            {
                array[i] = _fields[i].FieldType;
            }
            ConstructorBuilder constructorBuilder = _tb.DefineConstructor(MethodAttributes.Public, CallingConventions.HasThis, array);
            ILGenerator iLGenerator = constructorBuilder.GetILGenerator();
            ConstructorInfo constructor = _proxyBaseType.GetConstructor(Type.EmptyTypes);
            iLGenerator.Emit(OpCodes.Ldarg_0);
            iLGenerator.Emit(OpCodes.Call, constructor);
            for (int j = 0; j < array.Length; j++)
            {
                iLGenerator.Emit(OpCodes.Ldarg_0);
                iLGenerator.Emit(OpCodes.Ldarg, j + 1);
                iLGenerator.Emit(OpCodes.Stfld, _fields[j]);
            }
            iLGenerator.Emit(OpCodes.Ret);
        }
References System.Reflection.DispatchProxyGenerator.ProxyBuilder._fields, System.Reflection.DispatchProxyGenerator.ProxyBuilder._proxyBaseType, System.Reflection.DispatchProxyGenerator.ProxyBuilder._tb, System.array, System.Reflection.Emit.OpCodes.Call, System.Collections.Generic.List< T >.Count, System.Reflection.Emit.TypeBuilder.DefineConstructor(), System.Type.EmptyTypes, System.Type.GetConstructor(), System.Reflection.Emit.OpCodes.Ldarg, System.Reflection.Emit.OpCodes.Ldarg_0, System.Reflection.Emit.OpCodes.Ret, and System.Reflection.Emit.OpCodes.Stfld.
Referenced by System.Reflection.DispatchProxyGenerator.ProxyBuilder.CreateType().