Terraria: UIList.UIInnerList.DrawChildren
DrawChildren()
override void UIList.UIInnerList.DrawChildren (SpriteBatch spriteBatch) inline protected virtual
Reimplemented from UIElement.
         {
             Vector2 position = base.Parent.GetDimensions().Position();
             Vector2 dimensions = new Vector2(base.Parent.GetDimensions().Width, base.Parent.GetDimensions().Height);
             foreach (UIElement element in Elements)
             {
                 Vector2 position2 = element.GetDimensions().Position();
                 Vector2 dimensions2 = new Vector2(element.GetDimensions().Width, element.GetDimensions().Height);
                 if (Collision.CheckAABBvAABBCollision(position, dimensions, position2, dimensions2))
                 {
                     element.Draw(spriteBatch);
                 }
             }
         }
References Collision.CheckAABBvAABBCollision(), UIElement.Draw(), UIElement.Elements, UIElement.GetDimensions(), CalculatedStyle.Height, CalculatedStyle.Position(), and CalculatedStyle.Width.