Terraria: MoonLordSky.GetIntensity
GetIntensity()
float MoonLordSky.GetIntensity () inline private
     {
         if (_forPlayer)
         {
             return _fadeOpacity;
         }
         if (UpdateMoonLordIndex())
         {
             float x = 0f;
             if (_moonLordIndex != -1)
             {
                 x = Vector2.Distance(Main.player[Main.myPlayer].Center, Main.npc[_moonLordIndex].Center);
             }
             return 1f - Utils.SmoothStep(3000f, 6000f, x);
         }
         return 0f;
     }
References _fadeOpacity, _forPlayer, _moonLordIndex, Entity.Center, Main.myPlayer, Main.npc, Main.player, Utils.SmoothStep(), and UpdateMoonLordIndex().
Referenced by Draw(), and OnTileColor().