Terraria: System.Xml.Serialization.SourceInfo.ConvertNullableValue
ConvertNullableValue()
void System.Xml.Serialization.SourceInfo.ConvertNullableValue ([DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicMethods | DynamicallyAccessedMemberTypes.NonPublicMethods)] Type nullableType, Type targetType) inline private
Definition at line 201 of file SourceInfo.cs.
    {
        if (targetType != nullableType)
        {
            MethodInfo method = nullableType.GetMethod("get_Value", BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, Type.EmptyTypes);
            ILG.Call(method);
            if (targetType != null)
            {
                ILG.ConvertValue(method.ReturnType, targetType);
            }
        }
    }
References System.Xml.Serialization.CodeGenerator.Call(), System.Xml.Serialization.CodeGenerator.ConvertValue(), System.Xml.Dictionary, System.Type.EmptyTypes, and System.Xml.Serialization.SourceInfo.ILG.
Referenced by System.Xml.Serialization.SourceInfo.InternalLoad().