Terraria: System.Xml.Serialization.SourceInfo.InternalLoad
InternalLoad()
void System.Xml.Serialization.SourceInfo.InternalLoad (Type elementType, bool asAddress = false) inline private
Definition at line 55 of file SourceInfo.cs.
    {
        Match match = s_regex.Match(Arg);
        if (match.Success)
        {
            object variable = ILG.GetVariable(match.Groups["a"].Value);
            Type variableType = ILG.GetVariableType(variable);
            object variable2 = ILG.GetVariable(match.Groups["ia"].Value);
            if (variableType.IsArray)
            {
                ILG.Load(variable);
                ILG.Load(variable2);
                Type elementType2 = variableType.GetElementType();
                if (CodeGenerator.IsNullableGenericType(elementType2))
                {
                    ILG.Ldelema(elementType2);
                    ConvertNullableValue(elementType2, elementType);
                    return;
                }
                if (elementType2.IsValueType)
                {
                    ILG.Ldelema(elementType2);
                    if (!asAddress)
                    {
                        ILG.Ldobj(elementType2);
                    }
                }
                else
                {
                    ILG.Ldelem(elementType2);
                }
                if (elementType != null)
                {
                    ILG.ConvertValue(elementType2, elementType);
                }
                return;
            }
            ILG.Load(variable);
            ILG.Load(variable2);
            MethodInfo methodInfo = variableType.GetMethod("get_Item", BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, new Type[1] { typeof(int) });
            if (methodInfo == null && typeof(IList).IsAssignableFrom(variableType))
            {
                methodInfo = s_iListGetItemMethod.Value;
            }
            ILG.Call(methodInfo);
            Type returnType = methodInfo.ReturnType;
            if (CodeGenerator.IsNullableGenericType(returnType))
            {
                LocalBuilder tempLocal = ILG.GetTempLocal(returnType);
                ILG.Stloc(tempLocal);
                ILG.Ldloca(tempLocal);
                ConvertNullableValue(returnType, elementType);
            }
            else
            {
                if (elementType != null && !returnType.IsAssignableFrom(elementType) && !elementType.IsAssignableFrom(returnType))
                {
                    throw new CodeGeneratorConversionException(returnType, elementType, asAddress, "IsNotAssignableFrom");
                }
                Convert(returnType, elementType, asAddress);
            }
            return;
        }
        if (Source == "null")
        {
            ILG.Load(null);
            return;
        }
        Type type;
        if (Arg.StartsWith("o.@", StringComparison.Ordinal) || MemberInfo != null)
        {
            object variable3 = ILG.GetVariable(Arg.StartsWith("o.@", StringComparison.Ordinal) ? "o" : Arg);
            type = ILG.GetVariableType(variable3);
            if (type.IsValueType)
            {
                ILG.LoadAddress(variable3);
            }
            else
            {
                ILG.Load(variable3);
            }
        }
        else
        {
            object variable3 = ILG.GetVariable(Arg);
            type = ILG.GetVariableType(variable3);
            if (CodeGenerator.IsNullableGenericType(type) && type.GetGenericArguments()[0] == elementType)
            {
                ILG.LoadAddress(variable3);
                ConvertNullableValue(type, elementType);
            }
            else if (asAddress)
            {
                ILG.LoadAddress(variable3);
            }
            else
            {
                ILG.Load(variable3);
            }
        }
        if (MemberInfo != null)
        {
            Type type2 = ((MemberInfo is FieldInfo) ? ((FieldInfo)MemberInfo).FieldType : ((PropertyInfo)MemberInfo).PropertyType);
            if (CodeGenerator.IsNullableGenericType(type2))
            {
                ILG.LoadMemberAddress(MemberInfo);
                ConvertNullableValue(type2, elementType);
            }
            else
            {
                ILG.LoadMember(MemberInfo);
                Convert(type2, elementType, asAddress);
            }
            return;
        }
        match = s_regex2.Match(Source);
        if (match.Success)
        {
            if (asAddress)
            {
                ILG.ConvertAddress(type, Type);
            }
            else
            {
                ILG.ConvertValue(type, Type);
            }
            type = Type;
        }
        Convert(type, elementType, asAddress);
    }
References System.Xml.Serialization.SourceInfo.Arg, System.Xml.Serialization.CodeGenerator.Call(), System.Xml.Serialization.SourceInfo.Convert(), System.Xml.Serialization.CodeGenerator.ConvertAddress(), System.Xml.Serialization.SourceInfo.ConvertNullableValue(), System.Xml.Serialization.CodeGenerator.ConvertValue(), System.Xml.Dictionary, System.elementType, System.Type.GetElementType(), System.Xml.Serialization.CodeGenerator.GetTempLocal(), System.Xml.Serialization.CodeGenerator.GetVariable(), System.Xml.Serialization.CodeGenerator.GetVariableType(), System.Xml.Serialization.SourceInfo.ILG, System.Xml.Serialization.CodeGenerator.IsNullableGenericType(), System.Xml.Serialization.CodeGenerator.Ldelem(), System.Xml.Serialization.CodeGenerator.Ldelema(), System.Xml.Serialization.CodeGenerator.Ldloca(), System.Xml.Serialization.CodeGenerator.Ldobj(), System.Xml.Serialization.CodeGenerator.Load(), System.Xml.Serialization.CodeGenerator.LoadAddress(), System.Xml.Serialization.CodeGenerator.LoadMember(), System.Xml.Serialization.CodeGenerator.LoadMemberAddress(), System.match, System.Xml.Serialization.SourceInfo.MemberInfo, System.Xml.Serialization.SourceInfo.s_iListGetItemMethod, System.Xml.Serialization.SourceInfo.s_regex, System.Xml.Serialization.SourceInfo.s_regex2, System.Xml.Serialization.SourceInfo.Source, System.Xml.Serialization.CodeGenerator.Stloc(), System.type, and System.Xml.Serialization.SourceInfo.Type.
Referenced by System.Xml.Serialization.SourceInfo.Load(), and System.Xml.Serialization.SourceInfo.LoadAddress().