Terraria: Chest.Lock
Lock()
static bool Chest.Lock (int X, int Y) inline static
     {
         if (Main.tile[X, Y] == null || Main.tile[X + 1, Y] == null || Main.tile[X, Y + 1] == null || Main.tile[X + 1, Y + 1] == null)
         {
             return false;
         }
         short num = 0;
         Tile tileSafely = Framing.GetTileSafely(X, Y);
         int type = tileSafely.type;
         int num2 = tileSafely.frameX / 36;
         switch (type)
         {
         case 21:
             switch (num2)
             {
             case 1:
                 num = 36;
                 break;
             case 3:
                 num = 36;
                 break;
             case 18:
             case 19:
             case 20:
             case 21:
             case 22:
                 if (!NPC.downedPlantBoss)
                 {
                     return false;
                 }
                 num = 180;
                 break;
             case 35:
             case 37:
             case 39:
                 num = 36;
                 break;
             default:
                 return false;
             }
             break;
         case 467:
             if (num2 == 12)
             {
                 if (!NPC.downedPlantBoss)
                 {
                     return false;
                 }
                 num = 36;
                 AchievementsHelper.NotifyProgressionEvent(20);
                 break;
             }
             return false;
         }
         SoundEngine.PlaySound(22, X * 16, Y * 16);
         for (int i = X; i <= X + 1; i++)
         {
             for (int j = Y; j <= Y + 1; j++)
             {
                 Tile tileSafely2 = Framing.GetTileSafely(i, j);
                 if (tileSafely2.type == type)
                 {
                     tileSafely2.frameX += num;
                     Main.tile[i, j] = tileSafely2;
                 }
             }
         }
         return true;
     }
References NPC.downedPlantBoss, Tile.frameX, Framing.GetTileSafely(), AchievementsHelper.NotifyProgressionEvent(), SoundEngine.PlaySound(), Main.tile, Tile.type, X, and Y.
Referenced by MessageBuffer.GetData(), and Player.PlaceThing_LockChest().