Terraria: Chest.AfterPlacement_Hook
AfterPlacement_Hook()
static int Chest.AfterPlacement_Hook (int x, int y, int type = 21, int style = 0, int direction = 1, int alternate = 0) inline static
     {
         Point16 baseCoords = new Point16(x, y);
         TileObjectData.OriginToTopLeft(type, style, ref baseCoords);
         int num = FindEmptyChest(baseCoords.X, baseCoords.Y);
         if (num == -1)
         {
             return -1;
         }
         if (Main.netMode != 1)
         {
             Chest chest = new Chest();
             chest.x = baseCoords.X;
             chest.y = baseCoords.Y;
             for (int i = 0; i < 40; i++)
             {
                 chest.item[i] = new Item();
             }
             Main.chest[num] = chest;
         }
         else
         {
             switch (type)
             {
             case 21:
                 NetMessage.SendData(34, -1, -1, null, 0, x, y, style);
                 break;
             case 467:
                 NetMessage.SendData(34, -1, -1, null, 4, x, y, style);
                 break;
             default:
                 NetMessage.SendData(34, -1, -1, null, 2, x, y, style);
                 break;
             }
         }
         return num;
     }
References Chest(), Main.chest, FindEmptyChest(), item, Main.netMode, TileObjectData.OriginToTopLeft(), NetMessage.SendData(), Point16.X, x, Point16.Y, and y.
Referenced by TileObjectData.Initialize().