Terraria: Chest.CreateChest
CreateChest()
static int Chest.CreateChest (int X, int Y, int id = -1) inline static
     {
         int num = id;
         if (num == -1)
         {
             num = FindEmptyChest(X, Y);
             if (num == -1)
             {
                 return -1;
             }
             if (Main.netMode == 1)
             {
                 return num;
             }
         }
         Main.chest[num] = new Chest();
         Main.chest[num].x = X;
         Main.chest[num].y = Y;
         for (int i = 0; i < 40; i++)
         {
             Main.chest[num].item[i] = new Item();
         }
         return num;
     }
References Chest(), Main.chest, FindEmptyChest(), item, Main.netMode, X, x, Y, and y.
Referenced by WorldFile.FixDresserChests(), WorldGen.Place3x2(), WorldGen.PlaceChest(), WorldGen.PlaceChestDirect(), and WorldGen.PlaceDresserDirect().