Terraria: Chest.PutItemInNearbyChest
PutItemInNearbyChest()
static Item Chest.PutItemInNearbyChest (Item item, Vector2 position) inline static
     {
         if (Main.netMode == 1)
         {
             return item;
         }
         bool flag = true;
         for (int i = 0; i < 8000; i++)
         {
             bool flag2 = false;
             bool flag3 = false;
             if (Main.chest[i] == null || IsPlayerInChest(i) || IsLocked(Main.chest[i].x, Main.chest[i].y))
             {
                 continue;
             }
             Vector2 vector = new Vector2(Main.chest[i].x * 16 + 16, Main.chest[i].y * 16 + 16);
             if ((vector - position).Length() >= 600f)
             {
                 continue;
             }
             for (int j = 0; j < Main.chest[i].item.Length; j++)
             {
                 if (Main.chest[i].item[j].IsAir)
                 {
                     flag3 = true;
                 }
                 else if (item.IsTheSameAs(Main.chest[i].item[j]))
                 {
                     flag2 = true;
                     int num = Main.chest[i].item[j].maxStack - Main.chest[i].item[j].stack;
                     if (num > 0)
                     {
                         if (num > item.stack)
{
                             num = item.stack;
                         }
                         VisualizeChestTransfer(position, vector, item, num);
                         if (flag)
{
                             item.stack -= num;
                             Main.chest[i].item[j].stack += num;
                         }
                         if (item.stack <= 0)
{
                             item.SetDefaults();
                             return item;
                         }
                     }
                 }
                 else
                 {
                     flag3 = true;
                 }
             }
             if (!(flag2 && flag3) || item.stack <= 0)
             {
                 continue;
             }
             for (int k = 0; k < Main.chest[i].item.Length; k++)
             {
                 if (Main.chest[i].item[k].type == 0 || Main.chest[i].item[k].stack == 0)
                 {
                     VisualizeChestTransfer(position, vector, item, item.stack);
                     if (flag)
                     {
                         Main.chest[i].item[k] = item.Clone();
                         item.SetDefaults();
                     }
                     return item;
                 }
             }
         }
         return item;
     }
References Main.chest, Item.Clone(), Item.IsAir, IsLocked(), IsPlayerInChest(), Item.IsTheSameAs(), item, Item.maxStack, Main.netMode, Item.SetDefaults(), Item.stack, Item.type, VisualizeChestTransfer(), x, and y.
Referenced by Player.QuickStackAllChests(), and ServerPlaceItem().