Terraria: Chest.DidDiscoverBestiaryEntry
DidDiscoverBestiaryEntry()
static bool Chest.DidDiscoverBestiaryEntry (int npcId) inline static private
     {
         return Main.BestiaryDB.FindEntryByNPCID(npcId).UIInfoProvider.GetEntryUICollectionInfo().UnlockState > BestiaryEntryUnlockState.NotKnownAtAll_0;
     }
References Main.BestiaryDB, BestiaryDatabase.FindEntryByNPCID(), IBestiaryUICollectionInfoProvider.GetEntryUICollectionInfo(), BestiaryEntry.UIInfoProvider, and BestiaryUICollectionInfo.UnlockState.
Referenced by BestiaryGirl_IsFairyTorchAvailable().