Terraria: System.Xml.XmlQualifiedName.ToString
ToString() [1/2]
override string System.Xml.XmlQualifiedName.ToString () inline
Definition at line 56 of file XmlQualifiedName.cs.
    {
        if (Namespace.Length != 0)
        {
            return Namespace + ":" + Name;
        }
        return Name;
    }
References System.Xml.XmlQualifiedName.Name, and System.Xml.XmlQualifiedName.Namespace.
Referenced by System.Xml.Serialization.SchemaObjectCache.AddItem(), System.Xml.Schema.BaseProcessor.AddToTable(), System.Xml.Schema.XmlSchemaSet.AddToTable(), System.Xml.Schema.XdrBuilder.CheckDatatype(), System.Xml.Serialization.Accessor.EscapeQName(), System.Xml.Xsl.XsltOld.CallTemplateAction.Execute(), System.Xml.Schema.XmlSchemaValidator.FastGetElementDecl(), System.Xml.Schema.SchemaInfo.GetAttributeXdr(), System.Xml.Schema.SchemaInfo.GetAttributeXsd(), System.Xml.Schema.DatatypeImplementation.GetTypeName(), System.Xml.XmlTextReaderImpl.ParseDtd(), System.Xml.XmlTextReaderImpl.ParseDtdAsync(), System.Xml.Schema.Preprocessor.PreprocessIdentityConstraint(), System.Xml.Schema.SchemaCollectionPreprocessor.PreprocessIdentityConstraint(), System.Xml.Schema.XdrBuilder.ProcessAttribute(), System.Xml.Schema.XdrBuilder.ProcessElement(), System.Data.DataTable.SerializeTableSchema(), System.Xml.Schema.DtdValidator.Validate(), System.Xml.Schema.XsdValidator.ValidateChildElement(), System.Xml.Schema.XmlSchemaValidator.ValidateElementContext(), System.Xml.Schema.XdrBuilder.XDR_BeginAttribute(), System.Xml.Schema.XdrBuilder.XDR_BuildAttributeType_Name(), System.Xml.Schema.XdrBuilder.XDR_BuildElementType_Name(), and System.Xml.Schema.XdrBuilder.XDR_EndRoot().