Terraria: System.Xml.XmlQualifiedName.Parse
Parse()
static XmlQualifiedName System.Xml.XmlQualifiedName.Parse (string s, IXmlNamespaceResolver nsmgr, out string prefix) inline static package inherited
Definition at line 141 of file XmlQualifiedName.cs.
    {
        ValidateNames.ParseQNameThrow(s, out prefix, out var localName);
        string text = nsmgr.LookupNamespace(prefix);
        if (text == null)
        {
            if (prefix.Length != 0)
            {
                throw new XmlException(System.SR.Xml_UnknownNs, prefix);
            }
            text = string.Empty;
        }
        return new XmlQualifiedName(localName, text);
    }
References System.Xml.XmlQualifiedName.XmlQualifiedName(), System.Xml.Dictionary, System.Xml.ValidateNames.ParseQNameThrow(), System.prefix, System.s, System.text, System.SR.Xml_UnknownNs, and System.Xml.XmlException.
Referenced by System.Xml.Schema.XsdBuilder.ParseQName(), System.Xml.Schema.Datatype_QNameXdr.ParseValue(), System.Xml.Schema.XdrBuilder.ProcessAttribute(), System.Xml.Schema.Datatype_NOTATION.TryParseValue(), and System.Xml.Schema.Datatype_QName.TryParseValue().