Terraria: System.Xml.XmlQualifiedName.Equals
Equals()
override bool System.Xml.XmlQualifiedName.Equals ([NotNullWhen(true)] object? other) inline inherited
Definition at line 65 of file XmlQualifiedName.cs.
    {
        if (this == other)
        {
            return true;
        }
        XmlQualifiedName xmlQualifiedName = other as XmlQualifiedName;
        if (xmlQualifiedName != null)
        {
            if (Name == xmlQualifiedName.Name)
            {
                return Namespace == xmlQualifiedName.Namespace;
            }
            return false;
        }
        return false;
    }
References System.Xml.XmlQualifiedName.XmlQualifiedName(), System.Xml.Dictionary, System.Xml.XmlQualifiedName.Name, System.Xml.XmlQualifiedName.Namespace, and System.other.
Referenced by System.Xml.Schema.XmlSchemaValidator.FastGetElementDecl(), System.Xml.Schema.SchemaInfo.GetAttributeXsd(), System.Xml.Schema.XdrBuilder.GetContent(), System.Xml.Schema.XdrBuilder.GetModel(), System.Xml.Schema.XdrBuilder.GetNextState(), System.Xml.Schema.XsdBuilder.GetNextState(), System.Xml.Schema.XdrBuilder.GetOrder(), System.Xml.Schema.XdrBuilder.ProcessAttribute(), System.Xml.Schema.XsdBuilder.ProcessAttribute(), and System.Xml.Schema.DtdValidator.ValidateElement().