Terraria: System.Xml.XmlQualifiedName.Init
Init()
void System.Xml.XmlQualifiedName.Init (string name, string ns) inline package inherited
Definition at line 114 of file XmlQualifiedName.cs.
    {
        _name = name ?? string.Empty;
        _ns = ns ?? string.Empty;
        _hash = 0;
    }
References System.Xml.XmlQualifiedName._hash, System.Xml.XmlQualifiedName._name, and System.Xml.XmlQualifiedName._ns.
Referenced by System.Xml.Schema.DtdValidator.ValidateElement(), System.Xml.Schema.XdrValidator.ValidateElement(), System.Xml.Schema.XsdValidator.ValidateElement(), System.Xml.Schema.XmlSchemaValidator.ValidateElement(), System.Xml.QueryOutputWriter.WriteStartElement(), and System.Xml.QueryOutputWriterV1.WriteStartElement().