Terraria: System.Xml.XmlQualifiedName.Clone
Clone()
XmlQualifiedName System.Xml.XmlQualifiedName.Clone () inline package inherited
Definition at line 156 of file XmlQualifiedName.cs.
    {
        return (XmlQualifiedName)MemberwiseClone();
    }
Referenced by System.Xml.Schema.XmlSchemaAttribute.Clone(), System.Xml.Schema.XmlSchemaSimpleTypeList.Clone(), System.Xml.Schema.XmlSchemaSimpleTypeRestriction.Clone(), System.Xml.Schema.XmlSchemaSimpleTypeUnion.Clone(), and System.Xml.Schema.XmlSchemaElement.Clone().