Terraria: System.Xml.XmlQualifiedName.Empty
Empty
readonly XmlQualifiedName System.Xml.XmlQualifiedName.Empty = new XmlQualifiedName(string.Empty) static inherited
Definition at line 13 of file XmlQualifiedName.cs.
Referenced by System.Xml.Xsl.XsltOld.Stylesheet.AddTemplate(), System.Xml.Schema.Compiler.CheckParticleDerivation(), System.Xml.Schema.XmlSchemaValidator.CheckXsiTypeAndNil(), System.Xml.Schema.Compiler.Compile(), System.Xml.Schema.SchemaCollectionCompiler.Compile(), System.Xml.Schema.Compiler.CompileComplexType(), System.Xml.Schema.SchemaCollectionCompiler.CompileComplexType(), System.Xml.Schema.SchemaNames.CreateTokenToQNameTable(), System.Xml.Serialization.SchemaGraph.Depends(), System.Xml.Serialization.XmlSchemaExporter.ExportStructMapping(), System.Xml.Schema.ParticleContentValidator.Finish(), System.Xml.Schema.XmlSchemaInference.GetEffectiveSchemaType(), System.Xml.Schema.SymbolsDictionary.GetNamespaceListSymbols(), System.Xml.Serialization.XmlSchemas.GetParentName(), System.Xml.Schema.XmlSchemaParticle.GetQualifiedName(), System.Xml.Schema.XmlSchemaValidator.GetSchemaElement(), System.Runtime.Serialization.XsdDataContractExporter.GetSchemaTypeName(), System.Xml.Serialization.XmlSchemaImporter.ImportAny(), System.Xml.Serialization.XmlSchemaImporter.ImportAnyMapping(), System.Xml.Serialization.SchemaImporter.ImportRootMapping(), System.Xml.Schema.XmlSchemaInference.InferElement(), System.Xml.Schema.DtdValidator.Init(), System.Xml.Schema.XdrValidator.Init(), System.Xml.Schema.XmlSchemaValidator.Init(), System.Xml.Schema.XsdValidator.Init(), System.Xml.Schema.XsdBuilder.ParseQName(), System.Xml.Schema.Preprocessor.PreprocessComplexType(), System.Xml.Schema.SchemaCollectionPreprocessor.PreprocessComplexType(), System.Xml.Schema.XmlSchemaInference.ProcessAttributes(), System.Xml.Schema.XsdValidator.ProcessXsiAttributes(), System.Xml.Serialization.XmlSerializationReader.ReadXmlQualifiedName(), System.Xml.Schema.XdrBuilder.DeclBaseInfo.Reset(), System.Xml.Serialization.SerializableMapping.RetrieveSerializableSchema(), System.Runtime.Serialization.Json.JsonWriterDelegator.WriteQName(), System.Runtime.Serialization.XmlWriterDelegator.WriteQName(), and System.Xml.Schema.XdrBuilder.XDR_InitAttributeType().