Terraria: Terraria.Chat.Commands.HelpCommand.GetCommandAliasesByID
GetCommandAliasesByID()
static Dictionary< string, List< LocalizedText > > Terraria.Chat.Commands.HelpCommand.GetCommandAliasesByID () inline static private
Definition at line 17 of file HelpCommand.cs.
    {
        object substitutions = Lang.CreateDialogSubstitutionObject();
        LocalizedText[] array = Language.FindAll(Lang.CreateDialogFilter("ChatCommandDescription.", substitutions));
        Dictionary<string, List<LocalizedText>> dictionary = new Dictionary<string, List<LocalizedText>>();
        LocalizedText[] array2 = array;
        foreach (LocalizedText localizedText in array2)
        {
            string key = localizedText.Key;
            key = key.Replace("ChatCommandDescription.", "");
            int num = key.IndexOf('_');
            if (num != -1)
            {
                key = key.Substring(0, num);
            }
            if (!dictionary.TryGetValue(key, out var value))
            {
                value = (dictionary[key] = new List<LocalizedText>());
            }
            value.Add(localizedText);
        }
        return dictionary;
    }
References Terraria.Lang.CreateDialogFilter(), Terraria.Lang.CreateDialogSubstitutionObject(), and Terraria.Localization.Language.FindAll().
Referenced by Terraria.Chat.Commands.HelpCommand.ProcessIncomingMessage().