Terraria: Terraria.Chat.Commands.HelpCommand.ComposeMessage
ComposeMessage()
static NetworkText Terraria.Chat.Commands.HelpCommand.ComposeMessage (Dictionary< string, List< LocalizedText > > aliases) inline static private
Definition at line 41 of file HelpCommand.cs.
    {
        string text = "";
        for (int i = 0; i < aliases.Count; i++)
        {
            text = text + "{" + i + "}\n";
        }
        List<NetworkText> list = new List<NetworkText>();
        foreach (KeyValuePair<string, List<LocalizedText>> alias in aliases)
        {
            list.Add(Language.GetText("ChatCommandDescription." + alias.Key).ToNetworkText());
        }
        string text2 = text;
        object[] substitutions = list.ToArray();
        return NetworkText.FromFormattable(text2, substitutions);
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Count, Terraria.Localization.NetworkText.FromFormattable(), and Terraria.Localization.Language.GetText().
Referenced by Terraria.Chat.Commands.HelpCommand.ProcessIncomingMessage().