Terraria: MS.Internal.Xml.XPath.NamespaceQuery.Advance
Advance()
override XPathNavigator MS.Internal.Xml.XPath.NamespaceQuery.Advance () inline
Definition at line 26 of file NamespaceQuery.cs.
    {
        do
        {
            if (!_onNamespace)
            {
                currentNode = qyInput.Advance();
                if (currentNode == null)
                {
                    return null;
                }
                position = 0;
                currentNode = currentNode.Clone();
                _onNamespace = currentNode.MoveToFirstNamespace();
            }
            else
            {
                _onNamespace = currentNode.MoveToNextNamespace();
            }
        }
        while (!_onNamespace || !matches(currentNode));
        position++;
        return currentNode;
    }
References MS.Internal.Xml.XPath.NamespaceQuery._onNamespace, MS.Internal.Xml.XPath.Query.Advance(), System.Xml.XPath.XPathNavigator.Clone(), MS.Internal.Xml.XPath.BaseAxisQuery.currentNode, MS.Internal.Xml.XPath.NamespaceQuery.matches(), System.Xml.XPath.XPathNavigator.MoveToFirstNamespace(), System.Xml.XPath.XPathNavigator.MoveToNextNamespace(), MS.Internal.Xml.XPath.BaseAxisQuery.position, and MS.Internal.Xml.XPath.BaseAxisQuery.qyInput.