Terraria: System.Linq.Expressions.DynamicExpression.Reduce
Reduce()
override Expression System.Linq.Expressions.DynamicExpression.Reduce () inline virtual inherited
Reimplemented from System.Linq.Expressions.Expression< TDelegate >.
Definition at line 40 of file DynamicExpression.cs.
    {
        ConstantExpression constantExpression = Expression.Constant(CallSite.Create(DelegateType, Binder));
        return Expression.Invoke(Expression.Field(constantExpression, "Target"), Arguments.AddFirst(constantExpression));
    }
References System.Linq.Expressions.DynamicExpression.Arguments, System.Linq.Expressions.DynamicExpression.Binder, System.Linq.Expressions.Expression< TDelegate >.Constant(), System.Runtime.CompilerServices.CallSite< T >.Create(), System.Linq.Expressions.DynamicExpression.DelegateType, System.Linq.Expressions.Expression< TDelegate >.Field(), and System.Linq.Expressions.Expression< TDelegate >.Invoke().