Terraria: System.Linq.Expressions.DynamicExpression.Rewrite
Rewrite() [2/3]
virtual DynamicExpression System.Linq.Expressions.DynamicExpression.Rewrite (Expression[] args) inline package virtual
Implements System.Linq.Expressions.IDynamicExpression.
Reimplemented in System.Linq.Expressions.DynamicExpression1, System.Linq.Expressions.DynamicExpression2, System.Linq.Expressions.DynamicExpression3, System.Linq.Expressions.DynamicExpression4, and System.Linq.Expressions.DynamicExpressionN.
Definition at line 107 of file DynamicExpression.cs.
    {
        throw ContractUtils.Unreachable;
    }
References System.Dynamic.Utils.ContractUtils.Unreachable.
Referenced by System.Linq.Expressions.DynamicExpression.Rewrite(), System.Linq.Expressions.DynamicExpressionVisitor.VisitDynamic(), and System.Linq.Expressions.ExpressionVisitor.VisitDynamic().