Terraria: System.Reflection.Emit.FieldBuilder.SetConstant
SetConstant()
void System.Reflection.Emit.FieldBuilder.SetConstant (object? defaultValue) inline
Definition at line 132 of file FieldBuilder.cs.
    {
        m_typeBuilder.ThrowIfCreated();
        if (defaultValue == null && m_fieldType.IsValueType && (!m_fieldType.IsGenericType || !(m_fieldType.GetGenericTypeDefinition() == typeof(Nullable<>))))
        {
            throw new ArgumentException(SR.Argument_ConstantNull);
        }
        TypeBuilder.SetConstantValue(m_typeBuilder.GetModuleBuilder(), m_fieldTok, m_fieldType, defaultValue);
    }
References System.SR.Argument_ConstantNull, System.Type.GetGenericTypeDefinition(), System.Reflection.Emit.TypeBuilder.GetModuleBuilder(), System.Type.IsGenericType, System.Type.IsValueType, System.Reflection.Emit.FieldBuilder.m_fieldTok, System.Reflection.Emit.FieldBuilder.m_fieldType, System.Reflection.Emit.FieldBuilder.m_typeBuilder, System.Reflection.Emit.TypeBuilder.SetConstantValue(), and System.Reflection.Emit.TypeBuilder.ThrowIfCreated().
Referenced by System.Reflection.Emit.EnumBuilder.DefineLiteral().