Terraria: System.Reflection.Emit.FieldBuilder.FieldBuilder
FieldBuilder()
System.Reflection.Emit.FieldBuilder.FieldBuilder (TypeBuilder typeBuilder, string fieldName, Type type, Type[] requiredCustomModifiers, Type[] optionalCustomModifiers, FieldAttributes attributes) inline package
Definition at line 60 of file FieldBuilder.cs.
    {
        if (fieldName == null)
        {
            throw new ArgumentNullException("fieldName");
        }
        if (fieldName.Length == 0)
        {
            throw new ArgumentException(SR.Argument_EmptyName, "fieldName");
        }
        if (fieldName[0] == '\0')
        {
            throw new ArgumentException(SR.Argument_IllegalName, "fieldName");
        }
        if (type == null)
        {
            throw new ArgumentNullException("type");
        }
        if (type == typeof(void))
        {
            throw new ArgumentException(SR.Argument_BadFieldType);
        }
        m_fieldName = fieldName;
        m_typeBuilder = typeBuilder;
        m_fieldType = type;
        m_Attributes = attributes & ~FieldAttributes.ReservedMask;
        SignatureHelper fieldSigHelper = SignatureHelper.GetFieldSigHelper(m_typeBuilder.Module);
        fieldSigHelper.AddArgument(type, requiredCustomModifiers, optionalCustomModifiers);
        int length;
        byte[] signature = fieldSigHelper.InternalGetSignature(out length);
        ModuleBuilder module = m_typeBuilder.GetModuleBuilder();
        m_fieldTok = TypeBuilder.DefineField(new QCallModule(ref module), typeBuilder.TypeToken, fieldName, signature, length, m_Attributes);
    }
References System.Reflection.Emit.SignatureHelper.AddArgument(), System.SR.Argument_BadFieldType, System.SR.Argument_EmptyName, System.SR.Argument_IllegalName, System.Reflection.Emit.TypeBuilder.DefineField(), System.Reflection.Emit.SignatureHelper.GetFieldSigHelper(), System.Reflection.Emit.TypeBuilder.GetModuleBuilder(), System.Reflection.Emit.SignatureHelper.InternalGetSignature(), System.length, System.Reflection.Emit.FieldBuilder.m_Attributes, System.Reflection.Emit.FieldBuilder.m_fieldName, System.Reflection.Emit.FieldBuilder.m_fieldTok, System.Reflection.Emit.FieldBuilder.m_fieldType, System.Reflection.Emit.FieldBuilder.m_typeBuilder, System.Reflection.Emit.TypeBuilder.Module, System.type, and System.Reflection.Emit.TypeBuilder.TypeToken.