Terraria: System.Reflection.Emit.FieldBuilder.SetOffset
SetOffset()
void System.Reflection.Emit.FieldBuilder.SetOffset (int iOffset) inline
Definition at line 125 of file FieldBuilder.cs.
    {
        m_typeBuilder.ThrowIfCreated();
        ModuleBuilder module = m_typeBuilder.GetModuleBuilder();
        TypeBuilder.SetFieldLayoutOffset(new QCallModule(ref module), m_fieldTok, iOffset);
    }
References System.Reflection.Emit.TypeBuilder.GetModuleBuilder(), System.Reflection.Emit.FieldBuilder.m_fieldTok, System.Reflection.Emit.FieldBuilder.m_typeBuilder, System.Reflection.Emit.TypeBuilder.SetFieldLayoutOffset(), and System.Reflection.Emit.TypeBuilder.ThrowIfCreated().