Terraria: System.Reflection.Emit.FieldBuilder.SetCustomAttribute
SetCustomAttribute() [1/2]
void System.Reflection.Emit.FieldBuilder.SetCustomAttribute (ConstructorInfo con, byte[] binaryAttribute) inline
Definition at line 142 of file FieldBuilder.cs.
    {
        if (con == null)
        {
            throw new ArgumentNullException("con");
        }
        if (binaryAttribute == null)
        {
            throw new ArgumentNullException("binaryAttribute");
        }
        ModuleBuilder moduleBuilder = m_typeBuilder.Module as ModuleBuilder;
        m_typeBuilder.ThrowIfCreated();
        TypeBuilder.DefineCustomAttribute(moduleBuilder, m_fieldTok, moduleBuilder.GetConstructorToken(con), binaryAttribute);
    }
References System.Reflection.Emit.TypeBuilder.DefineCustomAttribute(), System.Reflection.Emit.ModuleBuilder.GetConstructorToken(), System.Reflection.Emit.FieldBuilder.m_fieldTok, System.Reflection.Emit.FieldBuilder.m_typeBuilder, and System.Reflection.Emit.TypeBuilder.ThrowIfCreated().