Terraria: System.Xml.BitStack.PopBit
PopBit()
bool System.Xml.BitStack.PopBit () inline
Definition at line 25 of file BitStack.cs.
    {
        bool result = (_curr & 1) != 0;
        _curr >>= 1;
        if (_curr == 1)
        {
            PopCurr();
        }
        return result;
    }
References System.Xml.BitStack._curr, and System.Xml.BitStack.PopCurr().
Referenced by System.Xml.Xsl.Runtime.WhitespaceRuleReader.Read(), System.Xml.QueryOutputWriterV1.WriteEndElement(), System.Xml.QueryOutputWriter.WriteEndElement(), System.Xml.XmlEncodedRawTextWriterIndent.WriteEndElement(), System.Xml.XmlUtf8RawTextWriterIndent.WriteEndElement(), System.Xml.XmlEncodedRawTextWriterIndent.WriteEndElementAsync(), System.Xml.XmlUtf8RawTextWriterIndent.WriteEndElementAsync(), System.Xml.QueryOutputWriterV1.WriteFullEndElement(), System.Xml.QueryOutputWriter.WriteFullEndElement(), System.Xml.XmlEncodedRawTextWriterIndent.WriteFullEndElement(), System.Xml.XmlUtf8RawTextWriterIndent.WriteFullEndElement(), System.Xml.XmlEncodedRawTextWriterIndent.WriteFullEndElementAsync(), and System.Xml.XmlUtf8RawTextWriterIndent.WriteFullEndElementAsync().