Terraria: System.Xml.BitStack.PushBit
PushBit()
void System.Xml.BitStack.PushBit (bool bit) inline
Definition at line 16 of file BitStack.cs.
    {
        if ((_curr & 0x80000000u) != 0)
        {
            PushCurr();
        }
        _curr = (_curr << 1) | (bit ? 1u : 0u);
    }
References System.Xml.BitStack._curr, System.Xml.Dictionary, and System.Xml.BitStack.PushCurr().
Referenced by System.Xml.QueryOutputWriter.QueryOutputWriter(), System.Xml.QueryOutputWriterV1.QueryOutputWriterV1(), System.Xml.Xsl.Runtime.WhitespaceRuleReader.Read(), System.Xml.QueryOutputWriter.WriteStartElement(), System.Xml.QueryOutputWriterV1.WriteStartElement(), System.Xml.XmlEncodedRawTextWriterIndent.WriteStartElement(), System.Xml.XmlUtf8RawTextWriterIndent.WriteStartElement(), System.Xml.XmlEncodedRawTextWriterIndent.WriteStartElementAsync(), and System.Xml.XmlUtf8RawTextWriterIndent.WriteStartElementAsync().