Terraria: System.Numerics.Vector4.Vector4
Vector4() [1/5]
System.Numerics.Vector4.Vector4 (float value) inline
Definition at line 48 of file Vector4.cs.
        : this(value, value, value, value)
    {
    }
Referenced by System.Numerics.Vector4.Abs(), System.Numerics.Vector4.Max(), System.Numerics.Vector4.Min(), System.Numerics.Vector4.operator*(), System.Numerics.Vector4.operator*(), System.Numerics.Vector4.operator+(), System.Numerics.Vector4.operator-(), System.Numerics.Vector4.operator/(), System.Numerics.Vector4.operator/(), System.Numerics.Vector4.SquareRoot(), System.Numerics.Vector4.Transform(), System.Numerics.Vector4.Transform(), System.Numerics.Vector4.Transform(), System.Numerics.Vector4.Transform(), System.Numerics.Vector4.Transform(), and System.Numerics.Vector4.Transform().