Terraria: System.Numerics.Vector4.ToString
ToString() [3/3]
readonly string System.Numerics.Vector4.ToString (string? format, IFormatProvider? formatProvider) inline
Implements System.IFormattable.
Definition at line 432 of file Vector4.cs.
    {
        StringBuilder stringBuilder = new StringBuilder();
        string numberGroupSeparator = NumberFormatInfo.GetInstance(formatProvider).NumberGroupSeparator;
        stringBuilder.Append('<');
        stringBuilder.Append(X.ToString(format, formatProvider));
        stringBuilder.Append(numberGroupSeparator);
        stringBuilder.Append(' ');
        stringBuilder.Append(Y.ToString(format, formatProvider));
        stringBuilder.Append(numberGroupSeparator);
        stringBuilder.Append(' ');
        stringBuilder.Append(Z.ToString(format, formatProvider));
        stringBuilder.Append(numberGroupSeparator);
        stringBuilder.Append(' ');
        stringBuilder.Append(W.ToString(format, formatProvider));
        stringBuilder.Append('>');
        return stringBuilder.ToString();
    }
References System.Text.StringBuilder.Append(), System.format, System.Globalization.NumberFormatInfo.GetInstance(), System.Text.StringBuilder.ToString(), System.Numerics.Vector4.W, System.Numerics.Vector4.X, System.Numerics.Vector4.Y, and System.Numerics.Vector4.Z.