Terraria: Microsoft.Xna.Framework.Graphics.Texture2D.CreateTexture
CreateTexture()
unsafe void Microsoft.Xna.Framework.Graphics.Texture2D.CreateTexture (GraphicsDevice graphicsDevice, int width, int height, [MarshalAs(UnmanagedType.U1)] bool mipMap, uint usage, _D3DPOOL pool, SurfaceFormat format) inline protected
Definition at line 609 of file Texture2D.cs.
    {
        if (graphicsDevice == null)
        {
            throw new ArgumentNullException("graphicsDevice", FrameworkResources.DeviceCannotBeNullOnResourceCreate);
        }
        ValidateCreationParameters(graphicsDevice._profileCapabilities, width, height, format, mipMap);
        int num = ((!mipMap) ? 1 : 0);
        fixed (IDirect3DTexture9** ptr = &pComPtr)
        {
            int num2 = *(int*)graphicsDevice.pComPtr + 92;
            int num3 = ((delegate* unmanaged[Stdcall, Stdcall]<IntPtr, uint, uint, uint, uint, _D3DFORMAT, _D3DPOOL, IDirect3DTexture9**, void**, int>)(int)(*(uint*)num2))((nint)graphicsDevice.pComPtr, (uint)width, (uint)height, (uint)num, usage, _003CModule_003E.ConvertXnaFormatToWindows(format), pool, ptr, null);
            if (num3 < 0)
            {
                throw GraphicsHelpers.GetExceptionFromResult((uint)num3);
            }
            isDisposed = false;
            _parent = graphicsDevice;
            SurfaceFormat? format2 = format;
            InitializeDescription(format2);
            graphicsDevice.Resources.AddTrackedObject(this, pComPtr, (uint)pool, _internalHandle, ref _internalHandle);
        }
    }
References Microsoft.Xna.Framework.Graphics.GraphicsResource._internalHandle, Microsoft.Xna.Framework.Graphics.GraphicsResource._parent, Microsoft.Xna.Framework.Graphics.GraphicsDevice._profileCapabilities, Microsoft.Xna.Framework.Graphics.DeviceResourceManager.AddTrackedObject(), Microsoft.Xna.Framework.FrameworkResources.DeviceCannotBeNullOnResourceCreate, System.format, Microsoft.Xna.Framework.Graphics.GraphicsHelpers.GetExceptionFromResult(), Microsoft.Xna.Framework.Graphics.Texture2D.InitializeDescription(), Microsoft.Xna.Framework.Graphics.GraphicsResource.isDisposed, Microsoft.Xna.Framework.Graphics.GraphicsDevice.pComPtr, Microsoft.Xna.Framework.Graphics.Texture2D.pComPtr, Microsoft.Xna.Framework.Graphics.GraphicsDevice.Resources, and Microsoft.Xna.Framework.Graphics.Texture2D.ValidateCreationParameters().
Referenced by Microsoft.Xna.Framework.Graphics.Texture2D.Texture2D(), Microsoft.Xna.Framework.Graphics.Texture2D.Texture2D(), Microsoft.Xna.Framework.Graphics.Texture2D.Texture2D(), Microsoft.Xna.Framework.Graphics.RenderTarget2D.CreateRenderTarget(), and Microsoft.Xna.Framework.Graphics.RenderTarget2D.RecreateAndPopulateObject().