Terraria: Microsoft.Xna.Framework.Graphics.Texture2D.CopyOrRestoreData
CopyOrRestoreData()
unsafe int Microsoft.Xna.Framework.Graphics.Texture2D.CopyOrRestoreData ([MarshalAs(UnmanagedType.U1)] bool isStoring) inline package
Definition at line 770 of file Texture2D.cs.
    {
        IDirect3DTexture9* ptr = pComPtr;
        if (ptr == null)
        {
            return 0;
        }
        System.Runtime.CompilerServices.Unsafe.SkipInit(out _D3DSURFACE_DESC d3DSURFACE_DESC);
        int num = ((delegate* unmanaged[Stdcall, Stdcall]<IntPtr, uint, _D3DSURFACE_DESC*, int>)(int)(*(uint*)(*(int*)ptr + 68)))((nint)ptr, 0u, &d3DSURFACE_DESC);
        if (num >= 0)
        {
            if (isStoring)
            {
                pFaceData = new IntPtr[_levelCount];
            }
            uint num2 = System.Runtime.CompilerServices.Unsafe.As<_D3DSURFACE_DESC, uint>(ref System.Runtime.CompilerServices.Unsafe.AddByteOffset(ref d3DSURFACE_DESC, 24));
            uint num3 = System.Runtime.CompilerServices.Unsafe.As<_D3DSURFACE_DESC, uint>(ref System.Runtime.CompilerServices.Unsafe.AddByteOffset(ref d3DSURFACE_DESC, 28));
            bool flag = Texture.CheckCompressedTexture(*(_D3DFORMAT*)(&d3DSURFACE_DESC));
            byte b = ((!flag) ? Texture.GetExpectedByteSizeFromFormat(*(_D3DFORMAT*)(&d3DSURFACE_DESC)) : ((byte)((*(int*)(&d3DSURFACE_DESC) == 827611204) ? 8u : 16u)));
            int num4 = 0;
            int num5 = 0;
            if (0 < _levelCount)
            {
                System.Runtime.CompilerServices.Unsafe.SkipInit(out _D3DLOCKED_RECT d3DLOCKED_RECT);
                do
                {
                    byte* ptr2 = null;
                    int num6;
                    if (!isStoring)
                    {
                        ref IntPtr reference = ref pFaceData[num4];
                        num4++;
                        ptr2 = (byte*)reference.ToPointer();
                        num6 = 0;
                    }
                    else
                    {
                        num6 = 16;
                    }
                    ptr = pComPtr;
                    num = ((delegate* unmanaged[Stdcall, Stdcall]<IntPtr, uint, _D3DLOCKED_RECT*, tagRECT*, uint, int>)(int)(*(uint*)(*(int*)ptr + 76)))((nint)ptr, (uint)num5, &d3DLOCKED_RECT, null, (uint)num6);
                    if (num < 0)
                    {
                        break;
                    }
                    uint num7 = num2;
                    uint num8 = num3;
                    if (flag)
                    {
                        num7 = num2 + 3 >> 2;
                        num8 = num3 + 3 >> 2;
                    }
                    uint num9 = b * num7;
                    byte* ptr3 = (byte*)(int)System.Runtime.CompilerServices.Unsafe.As<_D3DLOCKED_RECT, uint>(ref System.Runtime.CompilerServices.Unsafe.AddByteOffset(ref d3DLOCKED_RECT, 4));
                    if (isStoring)
                    {
                        ptr2 = (byte*)_003CModule_003E.new_005B_005D(num9 * num8);
                    }
                    byte* ptr4 = ptr2;
                    if (0 < num8)
                    {
                        uint num10 = num8;
                        do
{
                            if (isStoring)
{
                                _003CModule_003E.memcpy_s(ptr4, num9 * num8, ptr3, num9);
                            }
                            else
{
                                _003CModule_003E.memcpy_s(ptr3, *(uint*)(&d3DLOCKED_RECT), ptr4, num9);
                            }
                            ptr3 = *(int*)(&d3DLOCKED_RECT) + ptr3;
                            ptr4 = (int)num9 + ptr4;
                            num10--;
                        }
                        while (num10 != 0);
                    }
                    ptr = pComPtr;
                    num = ((delegate* unmanaged[Stdcall, Stdcall]<IntPtr, uint, int>)(int)(*(uint*)(*(int*)ptr + 80)))((nint)ptr, (uint)num5);
                    if (num < 0)
                    {
                        break;
                    }
                    if (isStoring)
                    {
                        IntPtr intPtr = (IntPtr)ptr2;
                        ref IntPtr reference2 = ref pFaceData[num4];
                        num4++;
                        reference2 = intPtr;
                    }
                    num2 = ((num2 <= 1) ? 1u : (num2 >> 1));
                    num3 = ((num3 <= 1) ? 1u : (num3 >> 1));
                    num5++;
                }
                while (num5 < _levelCount);
            }
        }
        return num;
    }
References Microsoft.Xna.Framework.Graphics.Texture._levelCount, Microsoft.Xna.Framework.Graphics.Texture.CheckCompressedTexture(), Microsoft.Xna.Framework.Graphics.Texture.GetExpectedByteSizeFromFormat(), Microsoft.Xna.Framework.Graphics.Texture2D.pComPtr, and Microsoft.Xna.Framework.Graphics.Texture2D.pFaceData.
Referenced by Microsoft.Xna.Framework.Graphics.Texture2D.RecreateAndPopulateObject(), and Microsoft.Xna.Framework.Graphics.Texture2D.SaveDataForRecreation().