Terraria: Microsoft.Xna.Framework.Graphics.Texture2D.CleanupSavedData
CleanupSavedData()
unsafe void Microsoft.Xna.Framework.Graphics.Texture2D.CleanupSavedData () inline package
Definition at line 871 of file Texture2D.cs.
    {
        IntPtr[] array = pFaceData;
        if (array == null)
        {
            return;
        }
        int num = 0;
        if (0 < (nint)array.LongLength)
        {
            do
            {
                void* ptr = pFaceData[num].ToPointer();
                if (ptr != null)
                {
                    _003CModule_003E.delete_005B_005D(ptr);
                }
                ref IntPtr reference = ref pFaceData[num];
                reference = IntPtr.Zero;
                num++;
            }
            while (num < (nint)pFaceData.LongLength);
        }
        pFaceData = null;
    }
References System.array, Microsoft.Xna.Framework.Graphics.Texture2D.pFaceData, System.IntPtr.ToPointer(), and System.IntPtr.Zero.
Referenced by Microsoft.Xna.Framework.Graphics.Texture2D._0021Texture2D(), Microsoft.Xna.Framework.Graphics.Texture2D.RecreateAndPopulateObject(), and Microsoft.Xna.Framework.Graphics.Texture2D.SaveDataForRecreation().