Terraria: Microsoft.Xna.Framework.Graphics.Texture2D.GetManagedObject
GetManagedObject()
static unsafe Texture2D Microsoft.Xna.Framework.Graphics.Texture2D.GetManagedObject (IDirect3DTexture9 * pInterface, GraphicsDevice pDevice, uint pool) inline static package
Definition at line 902 of file Texture2D.cs.
    {
        Texture2D texture2D = pDevice.Resources.GetCachedObject(pInterface) as Texture2D;
        if (texture2D != null)
        {
            ((delegate* unmanaged[Stdcall, Stdcall]<IntPtr, uint>)(int)(*(uint*)(*(int*)pInterface + 8)))((nint)pInterface);
            texture2D.isDisposed = false;
            GC.ReRegisterForFinalize(texture2D);
        }
        else
        {
            texture2D = new Texture2D(pInterface, pDevice);
            pDevice.Resources.AddTrackedObject(texture2D, pInterface, pool, 0uL, ref texture2D._internalHandle);
        }
        return texture2D;
    }
References Microsoft.Xna.Framework.Graphics.Texture2D.Texture2D(), Microsoft.Xna.Framework.Graphics.GraphicsResource._internalHandle, Microsoft.Xna.Framework.Graphics.DeviceResourceManager.AddTrackedObject(), Microsoft.Xna.Framework.Graphics.DeviceResourceManager.GetCachedObject(), System.GC.ReRegisterForFinalize(), and Microsoft.Xna.Framework.Graphics.GraphicsDevice.Resources.
Referenced by Microsoft.Xna.Framework.Graphics.EffectParameter.GetValueTexture2D().