Terraria: Microsoft.Xna.Framework.Graphics.Texture2D.Texture2D
Texture2D() [6/6]
unsafe Microsoft.Xna.Framework.Graphics.Texture2D.Texture2D (GraphicsDevice graphicsDevice, Stream stream, int width, int height, SharedConstants::XnaImageOperation operation) inline package
Definition at line 114 of file Texture2D.cs.
    {
        try
        {
            if (graphicsDevice == null)
            {
                throw new ArgumentNullException("graphicsDevice", FrameworkResources.DeviceCannotBeNullOnResourceCreate);
            }
            if (stream == null)
            {
                throw new ArgumentNullException("stream", FrameworkResources.NullNotAllowed);
            }
            if (!stream.CanSeek)
            {
                throw new ArgumentException(FrameworkResources.StreamNotSeekable, "stream");
            }
            ValidateCreationParameters(graphicsDevice._profileCapabilities, width, height, SurfaceFormat.Color, mipMap: false);
            ImageStream imageStream = stream as ImageStream;
            try
            {
                if (imageStream == null)
                {
                    imageStream = ImageStream.FromStream(stream);
                }
                void* ptr = null;
                Helpers.ThrowExceptionFromErrorCode(Microsoft.Xna.Framework.Media.UnsafeNativeMethods.DecodeStreamToTexture(graphicsDevice.pComPtr, imageStream.Handle, &width, &height, (XnaImageOperation)operation, graphicsDevice._profileCapabilities.MaxTextureAspectRatio, &ptr));
                pComPtr = (IDirect3DTexture9*)ptr;
            }
            finally
            {
                if (imageStream != null && imageStream != stream)
                {
                    ((IDisposable)imageStream).Dispose();
                }
            }
            isDisposed = false;
            _parent = graphicsDevice;
            SurfaceFormat? format = SurfaceFormat.Color;
            InitializeDescription(format);
            graphicsDevice.Resources.AddTrackedObject(this, pComPtr, 1u, _internalHandle, ref _internalHandle);
            return;
        }
        catch
        {
            //try-fault
            base.Dispose(true);
            throw;
        }
    }
References Microsoft.Xna.Framework.Graphics.GraphicsResource._internalHandle, Microsoft.Xna.Framework.Graphics.GraphicsResource._parent, Microsoft.Xna.Framework.Graphics.GraphicsDevice._profileCapabilities, Microsoft.Xna.Framework.Graphics.DeviceResourceManager.AddTrackedObject(), Microsoft.Xna.Framework.FrameworkResources.DeviceCannotBeNullOnResourceCreate, System.format, Microsoft.Xna.Framework.Graphics.Texture2D.InitializeDescription(), Microsoft.Xna.Framework.Graphics.GraphicsResource.isDisposed, Microsoft.Xna.Framework.Graphics.ProfileCapabilities.MaxTextureAspectRatio, Microsoft.Xna.Framework.FrameworkResources.NullNotAllowed, Microsoft.Xna.Framework.Graphics.GraphicsDevice.pComPtr, Microsoft.Xna.Framework.Graphics.Texture2D.pComPtr, Microsoft.Xna.Framework.Graphics.GraphicsDevice.Resources, System.stream, Microsoft.Xna.Framework.FrameworkResources.StreamNotSeekable, Microsoft.Xna.Framework.Helpers.ThrowExceptionFromErrorCode(), and Microsoft.Xna.Framework.Graphics.Texture2D.ValidateCreationParameters().