Terraria: Microsoft.Xna.Framework.Graphics.Texture2D.SaveAsImage
SaveAsImage()
void Microsoft.Xna.Framework.Graphics.Texture2D.SaveAsImage (Stream stream, SharedConstants::XnaImageFormat __unnamed001, int width, int height) inline private
Definition at line 446 of file Texture2D.cs.
    {
        if (stream == null)
        {
            throw new ArgumentNullException("stream", FrameworkResources.NullNotAllowed);
        }
        if (!stream.CanWrite)
        {
            throw new ArgumentException("stream");
        }
        if (__unnamed001 != 0 && __unnamed001 != (SharedConstants.XnaImageFormat)2)
        {
            throw new ArgumentException("format");
        }
        SurfaceFormat format = _format;
        Color[] array2;
        int num;
        int height3;
        int width3;
        switch (format)
        {
        case SurfaceFormat.Color:
        {
            int width2 = _width;
            array2 = new Color[_height * width2];
            GetData(array2);
            goto IL_01da;
        }
        case SurfaceFormat.Bgr565:
            array2 = GetDataAsColor<Bgr565>();
            goto IL_01da;
        case SurfaceFormat.Bgra5551:
            array2 = GetDataAsColor<Bgra5551>();
            goto IL_01da;
        case SurfaceFormat.Bgra4444:
            array2 = GetDataAsColor<Bgra4444>();
            goto IL_01da;
        case SurfaceFormat.NormalizedByte2:
            array2 = GetDataAsColor<NormalizedByte2>();
            goto IL_01da;
        case SurfaceFormat.NormalizedByte4:
            array2 = GetDataAsColor<NormalizedByte4>();
            goto IL_01da;
        case SurfaceFormat.Rgba1010102:
            array2 = GetDataAsColor<Rgba1010102>();
            goto IL_01da;
        case SurfaceFormat.Rg32:
            array2 = GetDataAsColor<Rg32>();
            goto IL_01da;
        case SurfaceFormat.Rgba64:
            array2 = GetDataAsColor<Rgba64>();
            goto IL_01da;
        case SurfaceFormat.Alpha8:
            array2 = GetDataAsColor<Alpha8>();
            goto IL_01da;
        case SurfaceFormat.HalfSingle:
            array2 = GetDataAsColor<HalfSingle>();
            goto IL_01da;
        case SurfaceFormat.HalfVector2:
            array2 = GetDataAsColor<HalfVector2>();
            goto IL_01da;
        case SurfaceFormat.HalfVector4:
            array2 = GetDataAsColor<HalfVector4>();
            goto IL_01da;
        case SurfaceFormat.HdrBlendable:
            array2 = GetDataAsColor<HalfVector4>();
            goto IL_01da;
        case SurfaceFormat.Single:
            array2 = GetDataAsColor<float>(_003CModule_003E._003FA0x8419bba8_002ESingleToColor);
            goto IL_01da;
        case SurfaceFormat.Vector2:
            array2 = GetDataAsColor<Vector2>(_003CModule_003E._003FA0x8419bba8_002EVector2ToColor);
            goto IL_01da;
        case SurfaceFormat.Vector4:
            array2 = GetDataAsColor<Vector4>(_003CModule_003E._003FA0x8419bba8_002EVector4ToColor);
            goto IL_01da;
        case SurfaceFormat.Dxt1:
        case SurfaceFormat.Dxt3:
        case SurfaceFormat.Dxt5:
        {
            SurfaceFormat format2 = format;
            int height2 = _height;
            DxtDecoder dxtDecoder = new DxtDecoder(_width, height2, format2);
            byte[] array = new byte[dxtDecoder.PackedDataSize];
            GetData(array);
            array2 = dxtDecoder.Decode(array);
            goto IL_01da;
        }
        default:
            {
                throw new InvalidOperationException();
            }
            IL_01da:
            num = 0;
            if (0 < (nint)array2.LongLength)
            {
                do
                {
                    if (array2[num].A == 0)
                    {
                        Color transparent = Color.Transparent;
                        array2[num] = transparent;
                    }
                    num++;
                }
                while (num < (nint)array2.LongLength);
            }
            height3 = _height;
            width3 = _width;
            using (ImageStream imageStream = ImageStream.FromColors(array2, width3, height3, (XnaImageFormat)__unnamed001, width, height))
            {
                byte[] array3 = new BinaryReader(imageStream).ReadBytes((int)imageStream.Length);
                stream.Write(array3, 0, array3.Length);
                break;
            }
        }
    }
References Microsoft.Xna.Framework.Color.Color(), Microsoft.Xna.Framework.Graphics.Texture._format, Microsoft.Xna.Framework.Graphics.Texture2D._height, Microsoft.Xna.Framework.Graphics.Texture2D._width, System.A, System.array, Microsoft.Xna.Framework.Graphics.DxtDecoder.Decode(), System.format, Microsoft.Xna.Framework.FrameworkResources.NullNotAllowed, Microsoft.Xna.Framework.Graphics.DxtDecoder.PackedDataSize, System.IO.BinaryReader.ReadBytes(), System.stream, and Microsoft.Xna.Framework.Color.Transparent.
Referenced by Microsoft.Xna.Framework.Graphics.Texture2D.SaveAsJpeg(), and Microsoft.Xna.Framework.Graphics.Texture2D.SaveAsPng().