Terraria: Microsoft.Xna.Framework.Graphics.Texture2D.ReleaseNativeObject
ReleaseNativeObject() [1/2]
virtual unsafe void Microsoft.Xna.Framework.Graphics.Texture2D.ReleaseNativeObject ([MarshalAs(UnmanagedType.U1)] bool disposeManagedResource) inline package virtual
Implements Microsoft.Xna.Framework.Graphics.IGraphicsResource.
Reimplemented in Microsoft.Xna.Framework.Graphics.RenderTarget2D, and Microsoft.Xna.Framework.Graphics.RenderTarget2D.
Definition at line 748 of file Texture2D.cs.
    {
        StateTrackerTexture* ptr = pStateTracker;
        if (ptr != null)
        {
            ((delegate* unmanaged[Stdcall, Stdcall]<IntPtr, uint>)(int)(*(uint*)(*(int*)ptr + 8)))((nint)ptr);
            pStateTracker = null;
        }
        GraphicsDevice parent = _parent;
        if (parent != null && pComPtr != null)
        {
            parent.Resources.ReleaseAllReferences(_internalHandle, disposeManagedResource);
        }
        pComPtr = null;
    }
References Microsoft.Xna.Framework.Graphics.GraphicsResource._internalHandle, Microsoft.Xna.Framework.Graphics.GraphicsResource._parent, Microsoft.Xna.Framework.Graphics.Texture2D.pComPtr, Microsoft.Xna.Framework.Graphics.Texture.pStateTracker, Microsoft.Xna.Framework.Graphics.DeviceResourceManager.ReleaseAllReferences(), and Microsoft.Xna.Framework.Graphics.GraphicsDevice.Resources.
Referenced by Microsoft.Xna.Framework.Graphics.Texture2D._0021Texture2D(), Microsoft.Xna.Framework.Graphics.Texture2D.ReleaseNativeObject(), and Microsoft.Xna.Framework.Graphics.Texture2D.SaveDataForRecreation().