Terraria: Microsoft.Xna.Framework.Graphics.Texture2D.ValidateCreationParameters
ValidateCreationParameters()
static void Microsoft.Xna.Framework.Graphics.Texture2D.ValidateCreationParameters (ProfileCapabilities profile, int width, int height, SurfaceFormat format, [MarshalAs(UnmanagedType.U1)] bool mipMap) inline static protected
Definition at line 633 of file Texture2D.cs.
    {
        if (width <= 0)
        {
            throw new ArgumentOutOfRangeException("width", FrameworkResources.ResourcesMustBeGreaterThanZeroSize);
        }
        if (height <= 0)
        {
            throw new ArgumentOutOfRangeException("height", FrameworkResources.ResourcesMustBeGreaterThanZeroSize);
        }
        bool flag = Texture.CheckCompressedTexture(_003CModule_003E.ConvertXnaFormatToWindows(format));
        if (!profile.ValidTextureFormats.Contains(format))
        {
            profile.ThrowNotSupportedException(FrameworkResources.ProfileFormatNotSupported, typeof(Texture2D).Name, format);
        }
        int maxTextureSize = profile.MaxTextureSize;
        if (width > maxTextureSize || height > maxTextureSize)
        {
            profile.ThrowNotSupportedException(FrameworkResources.ProfileTooBig, typeof(Texture2D).Name, maxTextureSize);
        }
        int num = Math.Max(width, height);
        int num2 = Math.Min(width, height);
        int num3 = (num + num2 - 1) / num2;
        int maxTextureAspectRatio = profile.MaxTextureAspectRatio;
        if (num3 > maxTextureAspectRatio)
        {
            profile.ThrowNotSupportedException(FrameworkResources.ProfileAspectRatio, typeof(Texture2D).Name, maxTextureAspectRatio);
        }
        if (!profile.NonPow2Unconditional && (!Texture.IsPowerOfTwo((uint)width) || !Texture.IsPowerOfTwo((uint)height)))
        {
            if (mipMap)
            {
                profile.ThrowNotSupportedException(FrameworkResources.ProfileNotPowerOfTwoMipped, typeof(Texture2D).Name);
            }
            if (!flag)
            {
                return;
            }
            profile.ThrowNotSupportedException(FrameworkResources.ProfileNotPowerOfTwoDXT, typeof(Texture2D).Name);
        }
        if (flag && (((uint)width & 3u) != 0 || ((uint)height & 3u) != 0))
        {
            throw new ArgumentException(FrameworkResources.DxtNotMultipleOfFour);
        }
    }
References Microsoft.Xna.Framework.Graphics.Texture.CheckCompressedTexture(), System.Collections.Generic.List< T >.Contains(), Microsoft.Xna.Framework.FrameworkResources.DxtNotMultipleOfFour, System.format, Microsoft.Xna.Framework.Graphics.Texture.IsPowerOfTwo(), System.Math.Max(), Microsoft.Xna.Framework.Graphics.ProfileCapabilities.MaxTextureAspectRatio, Microsoft.Xna.Framework.Graphics.ProfileCapabilities.MaxTextureSize, System.Math.Min(), Microsoft.Xna.Framework.Graphics.GraphicsResource.Name, Microsoft.Xna.Framework.Graphics.ProfileCapabilities.NonPow2Unconditional, Microsoft.Xna.Framework.FrameworkResources.ProfileAspectRatio, Microsoft.Xna.Framework.FrameworkResources.ProfileFormatNotSupported, Microsoft.Xna.Framework.FrameworkResources.ProfileNotPowerOfTwoDXT, Microsoft.Xna.Framework.FrameworkResources.ProfileNotPowerOfTwoMipped, Microsoft.Xna.Framework.FrameworkResources.ProfileTooBig, Microsoft.Xna.Framework.FrameworkResources.ResourcesMustBeGreaterThanZeroSize, Microsoft.Xna.Framework.Graphics.ProfileCapabilities.ThrowNotSupportedException(), and Microsoft.Xna.Framework.Graphics.ProfileCapabilities.ValidTextureFormats.
Referenced by Microsoft.Xna.Framework.Graphics.Texture2D.Texture2D(), Microsoft.Xna.Framework.Graphics.RenderTarget2D.CreateRenderTarget(), and Microsoft.Xna.Framework.Graphics.Texture2D.CreateTexture().