Terraria: Microsoft.Xna.Framework.Graphics.Texture2D.SaveDataForRecreation
SaveDataForRecreation() [1/2]
virtual unsafe int Microsoft.Xna.Framework.Graphics.Texture2D.SaveDataForRecreation () inline package virtual
Implements Microsoft.Xna.Framework.Graphics.IGraphicsResource.
Reimplemented in Microsoft.Xna.Framework.Graphics.RenderTarget2D, and Microsoft.Xna.Framework.Graphics.RenderTarget2D.
Definition at line 679 of file Texture2D.cs.
    {
        if (pComPtr == null)
        {
            return 0;
        }
        CleanupSavedData();
        int num = CopyOrRestoreData(isStoring: true);
        if (num >= 0)
        {
            ReleaseNativeObject(disposeManagedResource: false);
        }
        else
        {
            CleanupSavedData();
        }
        alreadyRecreated = false;
        return num;
    }
References Microsoft.Xna.Framework.Graphics.Texture.alreadyRecreated, Microsoft.Xna.Framework.Graphics.Texture2D.CleanupSavedData(), Microsoft.Xna.Framework.Graphics.Texture2D.CopyOrRestoreData(), Microsoft.Xna.Framework.Graphics.Texture2D.pComPtr, and Microsoft.Xna.Framework.Graphics.Texture2D.ReleaseNativeObject().
Referenced by Microsoft.Xna.Framework.Graphics.Texture2D.SaveDataForRecreation().