Terraria: Microsoft.Xna.Framework.Graphics.Texture2D.RecreateAndPopulateObject
RecreateAndPopulateObject() [1/2]
virtual unsafe int Microsoft.Xna.Framework.Graphics.Texture2D.RecreateAndPopulateObject () inline package virtual
Implements Microsoft.Xna.Framework.Graphics.IGraphicsResource.
Reimplemented in Microsoft.Xna.Framework.Graphics.RenderTarget2D, and Microsoft.Xna.Framework.Graphics.RenderTarget2D.
Definition at line 705 of file Texture2D.cs.
    {
        if (_shouldNotRecreate)
        {
            return 0;
        }
        if (alreadyRecreated)
        {
            return 0;
        }
        if (pComPtr != null)
        {
            return -2147467259;
        }
        fixed (IDirect3DTexture9** ptr2 = &pComPtr)
        {
            IDirect3DDevice9* ptr = _parent.pComPtr;
            int num = *(int*)ptr + 92;
            int num2 = ((delegate* unmanaged[Stdcall, Stdcall]<IntPtr, uint, uint, uint, uint, _D3DFORMAT, _D3DPOOL, IDirect3DTexture9**, void**, int>)(int)(*(uint*)num))((nint)ptr, (uint)_width, (uint)_height, (uint)_levelCount, 0u, _003CModule_003E.ConvertXnaFormatToWindows(_format), (_D3DPOOL)1, ptr2, null);
            if (num2 >= 0)
            {
                num2 = CreateStateWrapper();
                if (num2 >= 0)
                {
                    num2 = CopyOrRestoreData(isStoring: false);
                    if (num2 >= 0)
                    {
                        _parent.Resources.AddTrackedObject(this, pComPtr, 1u, _internalHandle, ref _internalHandle);
                    }
                }
                CleanupSavedData();
            }
            alreadyRecreated = true;
            return num2;
        }
    }
References Microsoft.Xna.Framework.Graphics.Texture._format, Microsoft.Xna.Framework.Graphics.Texture2D._height, Microsoft.Xna.Framework.Graphics.GraphicsResource._internalHandle, Microsoft.Xna.Framework.Graphics.Texture._levelCount, Microsoft.Xna.Framework.Graphics.GraphicsResource._parent, Microsoft.Xna.Framework.Graphics.Texture2D._shouldNotRecreate, Microsoft.Xna.Framework.Graphics.Texture2D._width, Microsoft.Xna.Framework.Graphics.DeviceResourceManager.AddTrackedObject(), Microsoft.Xna.Framework.Graphics.Texture.alreadyRecreated, Microsoft.Xna.Framework.Graphics.Texture2D.CleanupSavedData(), Microsoft.Xna.Framework.Graphics.Texture2D.CopyOrRestoreData(), Microsoft.Xna.Framework.Graphics.Texture.CreateStateWrapper(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.pComPtr, Microsoft.Xna.Framework.Graphics.Texture2D.pComPtr, and Microsoft.Xna.Framework.Graphics.GraphicsDevice.Resources.
Referenced by Microsoft.Xna.Framework.Graphics.Texture2D.RecreateAndPopulateObject().