Terraria: Terraria.GameInput.LockOnHelper.ValidTarget
ValidTarget()
static bool Terraria.GameInput.LockOnHelper.ValidTarget (NPC n) inline static private
    {
        if (n == null || !n.active || n.dontTakeDamage || n.friendly || n.isLikeATownNPC || n.life < 1 || n.immortal)
        {
            return false;
        }
        if (n.aiStyle == 25 && n.ai[0] == 0f)
        {
            return false;
        }
        return true;
    }
References Terraria.Entity.active, Terraria.NPC.ai, Terraria.NPC.aiStyle, Terraria.NPC.dontTakeDamage, Terraria.NPC.friendly, Terraria.NPC.immortal, Terraria.NPC.isLikeATownNPC, and Terraria.NPC.life.
Referenced by Terraria.GameInput.LockOnHelper.GetClosestTarget(), Terraria.GameInput.LockOnHelper.RefreshTargets(), and Terraria.GameInput.LockOnHelper.Update().