Terraria: Terraria.GameInput.LockOnHelper.HandlePressing
HandlePressing()
static void Terraria.GameInput.LockOnHelper.HandlePressing () inline static private
Definition at line 246 of file LockOnHelper.cs.
    {
        if (UseMode == LockOnMode.TargetClosest)
        {
            SetActive(!_enabled);
        }
        else if (UseMode == LockOnMode.ThreeDS)
        {
            if (!_enabled)
            {
                SetActive(on: true);
            }
            else
            {
                CycleTargetThreeDS();
            }
        }
        else if (!_enabled)
        {
            SetActive(on: true);
        }
        else
        {
            CycleTargetFocus();
        }
    }
References Terraria.GameInput.LockOnHelper._enabled, Terraria.GameInput.LockOnHelper.CycleTargetFocus(), Terraria.GameInput.LockOnHelper.CycleTargetThreeDS(), Terraria.GameInput.LockOnHelper.SetActive(), and Terraria.GameInput.LockOnHelper.UseMode.
Referenced by Terraria.GameInput.LockOnHelper.Toggle(), and Terraria.GameInput.LockOnHelper.Update().