Terraria: Terraria.GameInput.LockOnHelper.CycleTargetThreeDS
CycleTargetThreeDS()
static void Terraria.GameInput.LockOnHelper.CycleTargetThreeDS () inline static private
Definition at line 293 of file LockOnHelper.cs.
    {
        int num = _targets[_pickedTarget];
        RefreshTargets(Main.MouseWorld, 2000f);
        GetClosestTarget(Main.MouseWorld);
        if (_targets.Count < 1 || (_targets.Count == 1 && num == _targets[0]) || num == _targets[_pickedTarget])
        {
            SetActive(on: false);
        }
    }
References Terraria.GameInput.LockOnHelper._pickedTarget, Terraria.GameInput.LockOnHelper._targets, Terraria.GameInput.LockOnHelper.GetClosestTarget(), Terraria.Main.MouseWorld, Terraria.GameInput.LockOnHelper.RefreshTargets(), and Terraria.GameInput.LockOnHelper.SetActive().
Referenced by Terraria.GameInput.LockOnHelper.HandlePressing().