Terraria: Terraria.GameInput.LockOnHelper.FindMostViableTarget
FindMostViableTarget()
static void Terraria.GameInput.LockOnHelper.FindMostViableTarget (LockOnMode context, ref int targetVar) inline static private
    {
        targetVar = -1;
        if (UseMode == context && CanUseLockonSystem())
        {
            List<int> t = new List<int>();
            int t2 = -1;
            Utils.Swap(ref t, ref _targets);
            Utils.Swap(ref t2, ref _pickedTarget);
            RefreshTargets(Main.MouseWorld, 2000f);
            GetClosestTarget(Main.MouseWorld);
            Utils.Swap(ref t, ref _targets);
            Utils.Swap(ref t2, ref _pickedTarget);
            if (t2 >= 0)
            {
                targetVar = t[t2];
            }
            t.Clear();
        }
    }
References Terraria.GameInput.LockOnHelper._pickedTarget, Terraria.GameInput.LockOnHelper._targets, Terraria.GameInput.LockOnHelper.CanUseLockonSystem(), Terraria.GameInput.LockOnHelper.GetClosestTarget(), Terraria.Main.MouseWorld, Terraria.GameInput.LockOnHelper.RefreshTargets(), and Terraria.GameInput.LockOnHelper.UseMode.
Referenced by Terraria.GameInput.LockOnHelper.Update().