Terraria: System.Drawing.Size.Size
Size() [1/2]
System.Drawing.Size.Size (Point pt) inline
Definition at line 55 of file Size.cs.
    {
        width = pt.X;
        height = pt.Y;
    }
References System.Drawing.Size.height, System.Drawing.Size.width, System.Drawing.Point.X, and System.Drawing.Point.Y.
Referenced by System.Drawing.Size.Add(), System.Drawing.Size.Ceiling(), System.Drawing.Size.Multiply(), System.Drawing.Size.operator/(), System.Drawing.Size.Round(), System.Drawing.Size.Subtract(), and System.Drawing.Size.Truncate().