Terraria: ActionVines.Apply
Apply()
override bool ActionVines.Apply (Point origin, int x, int y, params object[] args) inline virtual
Implements GenAction.
     {
         int num = GenBase._random.Next(_minLength, _maxLength + 1);
         int i;
         for (i = 0; i < num && !GenBase._tiles[x, y + i].active(); i++)
         {
             GenBase._tiles[x, y + i].type = (ushort)_vineId;
             GenBase._tiles[x, y + i].active(active: true);
         }
         if (i > 0)
         {
             return UnitApply(origin, x, y, args);
         }
         return false;
     }
References _maxLength, _minLength, GenBase._random, GenBase._tiles, _vineId, Tile.active(), UnifiedRandom.Next(), Tile.type, and GenAction.UnitApply().