Terraria: System.Xml.Serialization.XmlSerializationWriterCodeGen.GenerateTypeElement
GenerateTypeElement()
string System.Xml.Serialization.XmlSerializationWriterCodeGen.GenerateTypeElement (XmlTypeMapping xmlTypeMapping) inline private
Definition at line 538 of file XmlSerializationWriterCodeGen.cs.
    {
        ElementAccessor accessor = xmlTypeMapping.Accessor;
        TypeMapping mapping = accessor.Mapping;
        string text = NextMethodName(accessor.Name);
        base.Writer.WriteLine();
        base.Writer.Write("public void ");
        base.Writer.Write(text);
        base.Writer.WriteLine("(object o) {");
        base.Writer.Indent++;
        base.Writer.WriteLine("WriteStartDocument();");
        base.Writer.WriteLine("if (o == null) {");
        base.Writer.Indent++;
        if (accessor.IsNullable)
        {
            if (mapping.IsSoap)
            {
                WriteEncodedNullTag(accessor.Name, (accessor.Form == XmlSchemaForm.Qualified) ? accessor.Namespace : "");
            }
            else
            {
                WriteLiteralNullTag(accessor.Name, (accessor.Form == XmlSchemaForm.Qualified) ? accessor.Namespace : "");
            }
        }
        else
        {
            WriteEmptyTag(accessor.Name, (accessor.Form == XmlSchemaForm.Qualified) ? accessor.Namespace : "");
        }
        base.Writer.WriteLine("return;");
        base.Writer.Indent--;
        base.Writer.WriteLine("}");
        if (!mapping.IsSoap && !mapping.TypeDesc.IsValueType && !mapping.TypeDesc.Type.IsPrimitive)
        {
            base.Writer.WriteLine("TopLevelElement();");
        }
        WriteMember("o", null, new ElementAccessor[1] { accessor }, null, null, mapping.TypeDesc, !accessor.IsSoap);
        if (mapping.IsSoap)
        {
            base.Writer.WriteLine("WriteReferencedElements();");
        }
        base.Writer.Indent--;
        base.Writer.WriteLine("}");
        return text;
    }
References System.Xml.Serialization.Accessor.Accessor(), System.Xml.Serialization.Mapping.Mapping(), System.Xml.Dictionary, System.Xml.Serialization.ElementAccessor.IsSoap, System.Xml.Serialization.XmlSerializationWriterCodeGen.NextMethodName(), System.text, System.Xml.Serialization.XmlSerializationWriterCodeGen.WriteEmptyTag(), System.Xml.Serialization.XmlSerializationWriterCodeGen.WriteEncodedNullTag(), System.Xml.Serialization.XmlSerializationWriterCodeGen.WriteLiteralNullTag(), and System.Xml.Serialization.XmlSerializationWriterCodeGen.WriteMember().
Referenced by System.Xml.Serialization.XmlSerializationWriterCodeGen.GenerateElement().