Terraria: System.Xml.Serialization.XmlSerializationWriterCodeGen.WriteEnumMethod
WriteEnumMethod()
void System.Xml.Serialization.XmlSerializationWriterCodeGen.WriteEnumMethod (EnumMapping mapping) inline private
Definition at line 588 of file XmlSerializationWriterCodeGen.cs.
    {
        string s = (string)base.MethodNames[mapping];
        base.Writer.WriteLine();
        string cSharpName = mapping.TypeDesc.CSharpName;
        if (mapping.IsSoap)
        {
            base.Writer.Write("void ");
            base.Writer.Write(s);
            base.Writer.WriteLine("(object e) {");
            WriteLocalDecl(cSharpName, "v", "e", mapping.TypeDesc.UseReflection);
        }
        else
        {
            base.Writer.Write("string ");
            base.Writer.Write(s);
            base.Writer.Write("(");
            base.Writer.Write(mapping.TypeDesc.UseReflection ? "object" : cSharpName);
            base.Writer.WriteLine(" v) {");
        }
        base.Writer.Indent++;
        base.Writer.WriteLine("string s = null;");
        ConstantMapping[] constants = mapping.Constants;
        if (constants.Length != 0)
        {
            Hashtable hashtable = new Hashtable();
            if (mapping.TypeDesc.UseReflection)
            {
                base.Writer.WriteLine("switch (" + base.RaCodeGen.GetStringForEnumLongValue("v", mapping.TypeDesc.UseReflection) + " ){");
            }
            else
            {
                base.Writer.WriteLine("switch (v) {");
            }
            base.Writer.Indent++;
            foreach (ConstantMapping constantMapping in constants)
            {
                if (hashtable[constantMapping.Value] == null)
                {
                    WriteEnumCase(cSharpName, constantMapping, mapping.TypeDesc.UseReflection);
                    base.Writer.Write("s = ");
                    WriteQuotedCSharpString(constantMapping.XmlName);
                    base.Writer.WriteLine("; break;");
                    hashtable.Add(constantMapping.Value, constantMapping.Value);
                }
            }
            if (mapping.IsFlags)
            {
                base.Writer.Write("default: s = FromEnum(");
                base.Writer.Write(base.RaCodeGen.GetStringForEnumLongValue("v", mapping.TypeDesc.UseReflection));
                base.Writer.Write(", new string[] {");
                base.Writer.Indent++;
                for (int j = 0; j < constants.Length; j++)
                {
                    ConstantMapping constantMapping2 = constants[j];
                    if (j > 0)
                    {
                        base.Writer.WriteLine(", ");
                    }
                    WriteQuotedCSharpString(constantMapping2.XmlName);
                }
                base.Writer.Write("}, new ");
                base.Writer.Write(typeof(long).FullName);
                base.Writer.Write("[] {");
                for (int k = 0; k < constants.Length; k++)
                {
                    ConstantMapping constantMapping3 = constants[k];
                    if (k > 0)
                    {
                        base.Writer.WriteLine(", ");
                    }
                    base.Writer.Write("(long)");
                    if (mapping.TypeDesc.UseReflection)
                    {
                        base.Writer.Write(constantMapping3.Value.ToString(CultureInfo.InvariantCulture));
                        continue;
                    }
                    base.Writer.Write(cSharpName);
                    base.Writer.Write(".@");
                    CodeIdentifier.CheckValidIdentifier(constantMapping3.Name);
                    base.Writer.Write(constantMapping3.Name);
                }
                base.Writer.Indent--;
                base.Writer.Write("}, ");
                WriteQuotedCSharpString(mapping.TypeDesc.FullName);
                base.Writer.WriteLine("); break;");
            }
            else
            {
                base.Writer.Write("default: throw CreateInvalidEnumValueException(");
                base.Writer.Write(base.RaCodeGen.GetStringForEnumLongValue("v", mapping.TypeDesc.UseReflection));
                base.Writer.Write(".ToString(System.Globalization.CultureInfo.InvariantCulture), ");
                WriteQuotedCSharpString(mapping.TypeDesc.FullName);
                base.Writer.WriteLine(");");
            }
            base.Writer.Indent--;
            base.Writer.WriteLine("}");
        }
        if (mapping.IsSoap)
        {
            base.Writer.Write("WriteXsiType(");
            WriteQuotedCSharpString(mapping.TypeName);
            base.Writer.Write(", ");
            WriteQuotedCSharpString(mapping.Namespace);
            base.Writer.WriteLine(");");
            base.Writer.WriteLine("Writer.WriteString(s);");
        }
        else
        {
            base.Writer.WriteLine("return s;");
        }
        base.Writer.Indent--;
        base.Writer.WriteLine("}");
    }
References System.Xml.Serialization.CodeIdentifier.CheckValidIdentifier(), System.Xml.Dictionary, System.FullName, System.Globalization.CultureInfo.InvariantCulture, System.s, System.Xml.Serialization.XmlSerializationWriterCodeGen.WriteEnumCase(), System.Xml.Serialization.XmlSerializationWriterCodeGen.WriteLocalDecl(), and System.Xml.Serialization.XmlSerializationCodeGen.WriteQuotedCSharpString().
Referenced by System.Xml.Serialization.XmlSerializationWriterCodeGen.GenerateBegin(), and System.Xml.Serialization.XmlSerializationWriterCodeGen.GenerateMethod().