Terraria: System.Xml.Serialization.XmlSerializationWriterCodeGen.WriteStructMethod
WriteStructMethod()
void System.Xml.Serialization.XmlSerializationWriterCodeGen.WriteStructMethod (StructMapping mapping) inline private
Definition at line 800 of file XmlSerializationWriterCodeGen.cs.
    {
        if (mapping.IsSoap && mapping.TypeDesc.IsRoot)
        {
            return;
        }
        string s = (string)base.MethodNames[mapping];
        base.Writer.WriteLine();
        base.Writer.Write("void ");
        base.Writer.Write(s);
        string cSharpName = mapping.TypeDesc.CSharpName;
        if (mapping.IsSoap)
        {
            base.Writer.WriteLine("(object s) {");
            base.Writer.Indent++;
            WriteLocalDecl(cSharpName, "o", "s", mapping.TypeDesc.UseReflection);
        }
        else
        {
            base.Writer.Write("(string n, string ns, ");
            base.Writer.Write(mapping.TypeDesc.UseReflection ? "object" : cSharpName);
            base.Writer.Write(" o");
            if (mapping.TypeDesc.IsNullable)
            {
                base.Writer.Write(", bool isNullable");
            }
            base.Writer.WriteLine(", bool needType) {");
            base.Writer.Indent++;
            if (mapping.TypeDesc.IsNullable)
            {
                base.Writer.WriteLine("if ((object)o == null) {");
                base.Writer.Indent++;
                base.Writer.WriteLine("if (isNullable) WriteNullTagLiteral(n, ns);");
                base.Writer.WriteLine("return;");
                base.Writer.Indent--;
                base.Writer.WriteLine("}");
            }
            base.Writer.WriteLine("if (!needType) {");
            base.Writer.Indent++;
            base.Writer.Write(typeof(Type).FullName);
            base.Writer.WriteLine(" t = o.GetType();");
            base.Writer.Write("if (");
            WriteTypeCompare("t", cSharpName, mapping.TypeDesc.UseReflection);
            base.Writer.WriteLine(") {");
            base.Writer.WriteLine("}");
            base.Writer.WriteLine("else {");
            base.Writer.Indent++;
            WriteDerivedTypes(mapping);
            if (mapping.TypeDesc.IsRoot)
            {
                WriteEnumAndArrayTypes();
            }
            if (mapping.TypeDesc.IsRoot)
            {
                base.Writer.WriteLine("WriteTypedPrimitive(n, ns, o, true);");
                base.Writer.WriteLine("return;");
            }
            else
            {
                base.Writer.WriteLine("throw CreateUnknownTypeException(o);");
            }
            base.Writer.Indent--;
            base.Writer.WriteLine("}");
            base.Writer.Indent--;
            base.Writer.WriteLine("}");
        }
        if (!mapping.TypeDesc.IsAbstract)
        {
            if (mapping.TypeDesc.Type != null && typeof(XmlSchemaObject).IsAssignableFrom(mapping.TypeDesc.Type))
            {
                base.Writer.WriteLine("EscapeName = false;");
            }
            string text = null;
            MemberMapping[] allMembers = TypeScope.GetAllMembers(mapping);
            int num = FindXmlnsIndex(allMembers);
            if (num >= 0)
            {
                MemberMapping memberMapping = allMembers[num];
                CodeIdentifier.CheckValidIdentifier(memberMapping.Name);
                text = base.RaCodeGen.GetStringForMember("o", memberMapping.Name, mapping.TypeDesc);
                if (mapping.TypeDesc.UseReflection)
                {
                    text = "((" + memberMapping.TypeDesc.CSharpName + ")" + text + ")";
                }
            }
            if (!mapping.IsSoap)
            {
                base.Writer.Write("WriteStartElement(n, ns, o, false, ");
                if (text == null)
                {
                    base.Writer.Write("null");
                }
                else
                {
                    base.Writer.Write(text);
                }
                base.Writer.WriteLine(");");
                if (!mapping.TypeDesc.IsRoot)
                {
                    base.Writer.Write("if (needType) WriteXsiType(");
                    WriteQuotedCSharpString(mapping.TypeName);
                    base.Writer.Write(", ");
                    WriteQuotedCSharpString(mapping.Namespace);
                    base.Writer.WriteLine(");");
                }
            }
            else if (text != null)
            {
                WriteNamespaces(text);
            }
            foreach (MemberMapping memberMapping2 in allMembers)
            {
                if (memberMapping2.Attribute == null)
                {
                    continue;
                }
                CodeIdentifier.CheckValidIdentifier(memberMapping2.Name);
                if (memberMapping2.CheckShouldPersist)
                {
                    base.Writer.Write("if (");
                    string text2 = base.RaCodeGen.GetStringForMethodInvoke("o", cSharpName, "ShouldSerialize" + memberMapping2.Name, mapping.TypeDesc.UseReflection);
                    if (mapping.TypeDesc.UseReflection)
                    {
                        text2 = "((" + typeof(bool).FullName + ")" + text2 + ")";
                    }
                    base.Writer.Write(text2);
                    base.Writer.WriteLine(") {");
                    base.Writer.Indent++;
                }
                if (memberMapping2.CheckSpecified != 0)
                {
                    base.Writer.Write("if (");
                    string text3 = base.RaCodeGen.GetStringForMember("o", memberMapping2.Name + "Specified", mapping.TypeDesc);
                    if (mapping.TypeDesc.UseReflection)
                    {
                        text3 = "((" + typeof(bool).FullName + ")" + text3 + ")";
                    }
                    base.Writer.Write(text3);
                    base.Writer.WriteLine(") {");
                    base.Writer.Indent++;
                }
                WriteMember(base.RaCodeGen.GetStringForMember("o", memberMapping2.Name, mapping.TypeDesc), memberMapping2.Attribute, memberMapping2.TypeDesc, "o");
                if (memberMapping2.CheckSpecified != 0)
                {
                    base.Writer.Indent--;
                    base.Writer.WriteLine("}");
                }
                if (memberMapping2.CheckShouldPersist)
                {
                    base.Writer.Indent--;
                    base.Writer.WriteLine("}");
                }
            }
            foreach (MemberMapping memberMapping3 in allMembers)
            {
                if (memberMapping3.Xmlns != null)
                {
                    continue;
                }
                CodeIdentifier.CheckValidIdentifier(memberMapping3.Name);
                bool flag = memberMapping3.CheckShouldPersist && (memberMapping3.Elements.Length != 0 || memberMapping3.Text != null);
                if (flag)
                {
                    base.Writer.Write("if (");
                    string text4 = base.RaCodeGen.GetStringForMethodInvoke("o", cSharpName, "ShouldSerialize" + memberMapping3.Name, mapping.TypeDesc.UseReflection);
                    if (mapping.TypeDesc.UseReflection)
                    {
                        text4 = "((" + typeof(bool).FullName + ")" + text4 + ")";
                    }
                    base.Writer.Write(text4);
                    base.Writer.WriteLine(") {");
                    base.Writer.Indent++;
                }
                if (memberMapping3.CheckSpecified != 0)
                {
                    base.Writer.Write("if (");
                    string text5 = base.RaCodeGen.GetStringForMember("o", memberMapping3.Name + "Specified", mapping.TypeDesc);
                    if (mapping.TypeDesc.UseReflection)
                    {
                        text5 = "((" + typeof(bool).FullName + ")" + text5 + ")";
                    }
                    base.Writer.Write(text5);
                    base.Writer.WriteLine(") {");
                    base.Writer.Indent++;
                }
                string choiceSource = null;
                if (memberMapping3.ChoiceIdentifier != null)
                {
                    CodeIdentifier.CheckValidIdentifier(memberMapping3.ChoiceIdentifier.MemberName);
                    choiceSource = base.RaCodeGen.GetStringForMember("o", memberMapping3.ChoiceIdentifier.MemberName, mapping.TypeDesc);
                }
                WriteMember(base.RaCodeGen.GetStringForMember("o", memberMapping3.Name, mapping.TypeDesc), choiceSource, memberMapping3.ElementsSortedByDerivation, memberMapping3.Text, memberMapping3.ChoiceIdentifier, memberMapping3.TypeDesc, writeAccessors: true);
                if (memberMapping3.CheckSpecified != 0)
                {
                    base.Writer.Indent--;
                    base.Writer.WriteLine("}");
                }
                if (flag)
                {
                    base.Writer.Indent--;
                    base.Writer.WriteLine("}");
                }
            }
            if (!mapping.IsSoap)
            {
                WriteEndElement("o");
            }
        }
        base.Writer.Indent--;
        base.Writer.WriteLine("}");
    }
References System.Xml.Serialization.CodeIdentifier.CheckValidIdentifier(), System.Xml.Dictionary, System.Xml.Serialization.XmlSerializationWriterCodeGen.FindXmlnsIndex(), System.Xml.Serialization.TypeScope.GetAllMembers(), System.s, System.text, System.Xml.Serialization.XmlSerializationWriterCodeGen.WriteDerivedTypes(), System.Xml.Serialization.XmlSerializationWriterCodeGen.WriteEndElement(), System.Xml.Serialization.XmlSerializationWriterCodeGen.WriteEnumAndArrayTypes(), System.Xml.Serialization.XmlSerializationWriterCodeGen.WriteLocalDecl(), System.Xml.Serialization.XmlSerializationWriterCodeGen.WriteMember(), System.Xml.Serialization.XmlSerializationWriterCodeGen.WriteNamespaces(), System.Xml.Serialization.XmlSerializationCodeGen.WriteQuotedCSharpString(), and System.Xml.Serialization.XmlSerializationWriterCodeGen.WriteTypeCompare().
Referenced by System.Xml.Serialization.XmlSerializationWriterCodeGen.GenerateBegin(), and System.Xml.Serialization.XmlSerializationWriterCodeGen.GenerateMethod().