Terraria: System.Xml.Serialization.XmlSerializationWriterCodeGen.WriteDerivedTypes
WriteDerivedTypes()
void System.Xml.Serialization.XmlSerializationWriterCodeGen.WriteDerivedTypes (StructMapping mapping) inline private
Definition at line 703 of file XmlSerializationWriterCodeGen.cs.
    {
        for (StructMapping structMapping = mapping.DerivedMappings; structMapping != null; structMapping = structMapping.NextDerivedMapping)
        {
            string cSharpName = structMapping.TypeDesc.CSharpName;
            base.Writer.Write("if (");
            WriteTypeCompare("t", cSharpName, structMapping.TypeDesc.UseReflection);
            base.Writer.WriteLine(") {");
            base.Writer.Indent++;
            string s = ReferenceMapping(structMapping);
            base.Writer.Write(s);
            base.Writer.Write("(n, ns,");
            if (!structMapping.TypeDesc.UseReflection)
            {
                base.Writer.Write("(" + cSharpName + ")");
            }
            base.Writer.Write("o");
            if (structMapping.TypeDesc.IsNullable)
            {
                base.Writer.Write(", isNullable");
            }
            base.Writer.Write(", true");
            base.Writer.WriteLine(");");
            base.Writer.WriteLine("return;");
            base.Writer.Indent--;
            base.Writer.WriteLine("}");
            WriteDerivedTypes(structMapping);
        }
    }
References System.Xml.Serialization.StructMapping.DerivedMappings, System.Xml.Dictionary, System.Xml.Serialization.XmlSerializationCodeGen.ReferenceMapping(), System.s, System.Xml.Serialization.XmlSerializationWriterCodeGen.WriteDerivedTypes(), and System.Xml.Serialization.XmlSerializationWriterCodeGen.WriteTypeCompare().
Referenced by System.Xml.Serialization.XmlSerializationWriterCodeGen.WriteDerivedTypes(), and System.Xml.Serialization.XmlSerializationWriterCodeGen.WriteStructMethod().