Terraria: Terraria.GameContent.Tile_Entities.TEHatRack.OnPlayerUpdate
OnPlayerUpdate()
override void Terraria.GameContent.Tile_Entities.TEHatRack.OnPlayerUpdate (Player player) inline virtual
Reimplemented from Terraria.DataStructures.TileEntity.
Definition at line 301 of file TEHatRack.cs.
    {
        if (!player.InInteractionRange(player.tileEntityAnchor.X, player.tileEntityAnchor.Y, TileReachCheckSettings.Simple) || player.chest != -1 || player.talkNPC != -1)
        {
            if (player.chest == -1 && player.talkNPC == -1)
            {
                SoundEngine.PlaySound(11);
            }
            player.tileEntityAnchor.Clear();
            Recipe.FindRecipes();
        }
    }
References Terraria.Player.chest, Terraria.DataStructures.PlayerInteractionAnchor.Clear(), Terraria.Recipe.FindRecipes(), Terraria.Player.InInteractionRange(), Terraria.Audio.SoundEngine.PlaySound(), Terraria.DataStructures.TileReachCheckSettings.Simple, Terraria.Player.talkNPC, Terraria.Player.tileEntityAnchor, Terraria.DataStructures.PlayerInteractionAnchor.X, and Terraria.DataStructures.PlayerInteractionAnchor.Y.