Terraria: System.Xml.Serialization.XmlSerializationWriterCodeGen.WriteEnumAndArrayTypes
WriteEnumAndArrayTypes()
void System.Xml.Serialization.XmlSerializationWriterCodeGen.WriteEnumAndArrayTypes () inline private
Definition at line 734 of file XmlSerializationWriterCodeGen.cs.
    {
        TypeScope[] scopes = base.Scopes;
        foreach (TypeScope typeScope in scopes)
        {
            foreach (Mapping typeMapping in typeScope.TypeMappings)
            {
                if (typeMapping is EnumMapping && !typeMapping.IsSoap)
                {
                    EnumMapping enumMapping = (EnumMapping)typeMapping;
                    string cSharpName = enumMapping.TypeDesc.CSharpName;
                    base.Writer.Write("if (");
                    WriteTypeCompare("t", cSharpName, enumMapping.TypeDesc.UseReflection);
                    base.Writer.WriteLine(") {");
                    base.Writer.Indent++;
                    string s = ReferenceMapping(enumMapping);
                    base.Writer.WriteLine("Writer.WriteStartElement(n, ns);");
                    base.Writer.Write("WriteXsiType(");
                    WriteQuotedCSharpString(enumMapping.TypeName);
                    base.Writer.Write(", ");
                    WriteQuotedCSharpString(enumMapping.Namespace);
                    base.Writer.WriteLine(");");
                    base.Writer.Write("Writer.WriteString(");
                    base.Writer.Write(s);
                    base.Writer.Write("(");
                    if (!enumMapping.TypeDesc.UseReflection)
                    {
                        base.Writer.Write("(" + cSharpName + ")");
                    }
                    base.Writer.WriteLine("o));");
                    base.Writer.WriteLine("Writer.WriteEndElement();");
                    base.Writer.WriteLine("return;");
                    base.Writer.Indent--;
                    base.Writer.WriteLine("}");
                }
                else if (typeMapping is ArrayMapping && !typeMapping.IsSoap && typeMapping is ArrayMapping arrayMapping && !typeMapping.IsSoap)
                {
                    string cSharpName2 = arrayMapping.TypeDesc.CSharpName;
                    base.Writer.Write("if (");
                    if (arrayMapping.TypeDesc.IsArray)
                    {
                        WriteArrayTypeCompare("t", cSharpName2, arrayMapping.TypeDesc.ArrayElementTypeDesc.CSharpName, arrayMapping.TypeDesc.UseReflection);
                    }
                    else
                    {
                        WriteTypeCompare("t", cSharpName2, arrayMapping.TypeDesc.UseReflection);
                    }
                    base.Writer.WriteLine(") {");
                    base.Writer.Indent++;
                    base.Writer.WriteLine("Writer.WriteStartElement(n, ns);");
                    base.Writer.Write("WriteXsiType(");
                    WriteQuotedCSharpString(arrayMapping.TypeName);
                    base.Writer.Write(", ");
                    WriteQuotedCSharpString(arrayMapping.Namespace);
                    base.Writer.WriteLine(");");
                    WriteMember("o", null, arrayMapping.ElementsSortedByDerivation, null, null, arrayMapping.TypeDesc, writeAccessors: true);
                    base.Writer.WriteLine("Writer.WriteEndElement();");
                    base.Writer.WriteLine("return;");
                    base.Writer.Indent--;
                    base.Writer.WriteLine("}");
                }
            }
        }
    }
References System.Xml.Serialization.TypeDesc.CSharpName, System.Xml.Dictionary, System.Xml.Serialization.Mapping.IsSoap, System.Xml.Serialization.XmlSerializationCodeGen.ReferenceMapping(), System.s, System.Xml.Serialization.TypeMapping.TypeDesc, System.Xml.Serialization.XmlSerializationWriterCodeGen.WriteArrayTypeCompare(), System.Xml.Serialization.XmlSerializationWriterCodeGen.WriteMember(), System.Xml.Serialization.XmlSerializationCodeGen.WriteQuotedCSharpString(), and System.Xml.Serialization.XmlSerializationWriterCodeGen.WriteTypeCompare().
Referenced by System.Xml.Serialization.XmlSerializationWriterCodeGen.WriteStructMethod().