Terraria: Terraria.GameContent.Tile_Entities.TEHatRack.OverrideItemSlotLeftClick
OverrideItemSlotLeftClick()
override bool Terraria.GameContent.Tile_Entities.TEHatRack.OverrideItemSlotLeftClick (Item[] inv, int context = 0, int slot = 0) inline virtual
Reimplemented from Terraria.DataStructures.TileEntity.
Definition at line 394 of file TEHatRack.cs.
    {
        if (!ItemSlot.ShiftInUse)
        {
            return false;
        }
        if (Main.cursorOverride == 9 && context == 0)
        {
            Item item = inv[slot];
            if (Main.cursorOverride == 9 && !item.IsAir && !item.favorited && context == 0 && FitsHatRack(item))
            {
                return TryFitting(inv, context, slot);
            }
        }
        if ((Main.cursorOverride == 8 && context == 23) || context == 26 || context == 27)
        {
            inv[slot] = Main.player[Main.myPlayer].GetItem(Main.myPlayer, inv[slot], GetItemSettings.InventoryEntityToPlayerInventorySettings);
            if (Main.netMode == 1)
            {
                NetMessage.SendData(124, -1, -1, null, Main.myPlayer, ID, slot);
            }
            return true;
        }
        return false;
    }
References Terraria.Main.cursorOverride, Terraria.GameContent.Tile_Entities.TEHatRack.FitsHatRack(), Terraria.GetItemSettings.InventoryEntityToPlayerInventorySettings, Terraria.Main.myPlayer, Terraria.Main.netMode, Terraria.Main.player, Terraria.NetMessage.SendData(), Terraria.UI.ItemSlot.ShiftInUse, and Terraria.GameContent.Tile_Entities.TEHatRack.TryFitting().