Terraria: System.Xml.Serialization.XmlSerializationWriterCodeGen.WriteArrayItems
WriteArrayItems()
void System.Xml.Serialization.XmlSerializationWriterCodeGen.WriteArrayItems (ElementAccessor[] elements, TextAccessor text, ChoiceIdentifierAccessor choice, TypeDesc arrayTypeDesc, string arrayName, string choiceName) inline private
Definition at line 1271 of file XmlSerializationWriterCodeGen.cs.
    {
        TypeDesc arrayElementTypeDesc = arrayTypeDesc.ArrayElementTypeDesc;
        if (arrayTypeDesc.IsEnumerable)
        {
            base.Writer.Write(typeof(IEnumerator).FullName);
            base.Writer.Write(" e = ");
            if (arrayTypeDesc.IsPrivateImplementation)
            {
                base.Writer.Write("((");
                base.Writer.Write(typeof(IEnumerable).FullName);
                base.Writer.Write(")");
                base.Writer.Write(arrayName);
                base.Writer.WriteLine(").GetEnumerator();");
            }
            else if (arrayTypeDesc.IsGenericInterface)
            {
                if (arrayTypeDesc.UseReflection)
                {
                    base.Writer.Write("(");
                    base.Writer.Write(typeof(IEnumerator).FullName);
                    base.Writer.Write(")");
                    base.Writer.Write(base.RaCodeGen.GetReflectionVariable(arrayTypeDesc.CSharpName, "System.Collections.Generic.IEnumerable*"));
                    base.Writer.Write(".Invoke(");
                    base.Writer.Write(arrayName);
                    base.Writer.WriteLine(", new object[0]);");
                }
                else
                {
                    base.Writer.Write("((System.Collections.Generic.IEnumerable<");
                    base.Writer.Write(arrayElementTypeDesc.CSharpName);
                    base.Writer.Write(">)");
                    base.Writer.Write(arrayName);
                    base.Writer.WriteLine(").GetEnumerator();");
                }
            }
            else
            {
                if (arrayTypeDesc.UseReflection)
                {
                    base.Writer.Write("(");
                    base.Writer.Write(typeof(IEnumerator).FullName);
                    base.Writer.Write(")");
                }
                base.Writer.Write(base.RaCodeGen.GetStringForMethodInvoke(arrayName, arrayTypeDesc.CSharpName, "GetEnumerator", arrayTypeDesc.UseReflection));
                base.Writer.WriteLine(";");
            }
            base.Writer.WriteLine("if (e != null)");
            base.Writer.WriteLine("while (e.MoveNext()) {");
            base.Writer.Indent++;
            string cSharpName = arrayElementTypeDesc.CSharpName;
            WriteLocalDecl(cSharpName, arrayName + "i", "e.Current", arrayElementTypeDesc.UseReflection);
            WriteElements(arrayName + "i", choiceName + "i", elements, text, choice, arrayName + "a", writeAccessors: true, isNullable: true);
        }
        else
        {
            base.Writer.Write("for (int i");
            base.Writer.Write(arrayName);
            base.Writer.Write(" = 0; i");
            base.Writer.Write(arrayName);
            base.Writer.Write(" < ");
            if (arrayTypeDesc.IsArray)
            {
                base.Writer.Write(arrayName);
                base.Writer.Write(".Length");
            }
            else
            {
                base.Writer.Write("((");
                base.Writer.Write(typeof(ICollection).FullName);
                base.Writer.Write(")");
                base.Writer.Write(arrayName);
                base.Writer.Write(").Count");
            }
            base.Writer.Write("; i");
            base.Writer.Write(arrayName);
            base.Writer.WriteLine("++) {");
            base.Writer.Indent++;
            int num = elements.Length + ((text != null) ? 1 : 0);
            if (num > 1)
            {
                string cSharpName2 = arrayElementTypeDesc.CSharpName;
                WriteLocalDecl(cSharpName2, arrayName + "i", base.RaCodeGen.GetStringForArrayMember(arrayName, "i" + arrayName, arrayTypeDesc), arrayElementTypeDesc.UseReflection);
                if (choice != null)
                {
                    string cSharpName3 = choice.Mapping.TypeDesc.CSharpName;
                    WriteLocalDecl(cSharpName3, choiceName + "i", base.RaCodeGen.GetStringForArrayMember(choiceName, "i" + arrayName, choice.Mapping.TypeDesc), choice.Mapping.TypeDesc.UseReflection);
                }
                WriteElements(arrayName + "i", choiceName + "i", elements, text, choice, arrayName + "a", writeAccessors: true, arrayElementTypeDesc.IsNullable);
            }
            else
            {
                WriteElements(base.RaCodeGen.GetStringForArrayMember(arrayName, "i" + arrayName, arrayTypeDesc), elements, text, choice, arrayName + "a", writeAccessors: true, arrayElementTypeDesc.IsNullable);
            }
        }
        base.Writer.Indent--;
        base.Writer.WriteLine("}");
    }
References System.Xml.Serialization.TypeDesc.ArrayElementTypeDesc, System.Xml.Serialization.TypeDesc.CSharpName, System.Xml.Dictionary, System.FullName, System.text, System.Xml.Serialization.XmlSerializationWriterCodeGen.WriteElements(), and System.Xml.Serialization.XmlSerializationWriterCodeGen.WriteLocalDecl().
Referenced by System.Xml.Serialization.XmlSerializationWriterCodeGen.WriteArray(), and System.Xml.Serialization.XmlSerializationWriterCodeGen.WriteElement().