Terraria: System.Xml.Serialization.XmlSerializationWriterCodeGen.WriteCheckDefault
WriteCheckDefault()
void System.Xml.Serialization.XmlSerializationWriterCodeGen.WriteCheckDefault (TypeMapping mapping, string source, object value, bool isNullable) inline private
Definition at line 1927 of file XmlSerializationWriterCodeGen.cs.
    {
        base.Writer.Write("if (");
        if (value is string && ((string)value).Length == 0)
        {
            base.Writer.Write("(");
            base.Writer.Write(source);
            if (isNullable)
            {
                base.Writer.Write(" == null) || (");
            }
            else
            {
                base.Writer.Write(" != null) && (");
            }
            base.Writer.Write(source);
            base.Writer.Write(".Length != 0)");
        }
        else if (value is double || value is float)
        {
            base.Writer.Write("!");
            base.Writer.Write(source);
            base.Writer.Write(".Equals(");
            Type type = Type.GetType(mapping.TypeDesc.Type.FullName);
            WriteValue((type != null) ? Convert.ChangeType(value, type) : value);
            base.Writer.Write(")");
        }
        else
        {
            base.Writer.Write(source);
            base.Writer.Write(" != ");
            Type type2 = Type.GetType(mapping.TypeDesc.Type.FullName);
            WriteValue((type2 != null) ? Convert.ChangeType(value, type2) : value);
        }
        base.Writer.Write(")");
    }
References System.Convert.ChangeType(), System.Xml.Dictionary, System.Type.GetType(), System.Xml.Schema.Length, System.source, System.type, System.value, and System.Xml.Serialization.XmlSerializationWriterCodeGen.WriteValue().
Referenced by System.Xml.Serialization.XmlSerializationWriterCodeGen.WritePrimitive(), and System.Xml.Serialization.XmlSerializationWriterCodeGen.WriteQualifiedNameElement().