Terraria: System.Xml.Serialization.XmlSerializationWriterCodeGen.WriteElement
WriteElement()
void System.Xml.Serialization.XmlSerializationWriterCodeGen.WriteElement (string source, ElementAccessor element, string arrayName, bool writeAccessor) inline private
Definition at line 1654 of file XmlSerializationWriterCodeGen.cs.
    {
        string text = (writeAccessor ? element.Name : element.Mapping.TypeName);
        string text2 = ((element.Any && element.Name.Length == 0) ? null : ((element.Form != XmlSchemaForm.Qualified) ? "" : (writeAccessor ? element.Namespace : element.Mapping.Namespace)));
        if (element.Mapping is NullableMapping)
        {
            base.Writer.Write("if (");
            base.Writer.Write(source);
            base.Writer.WriteLine(" != null) {");
            base.Writer.Indent++;
            string cSharpName = element.Mapping.TypeDesc.BaseTypeDesc.CSharpName;
            string text3 = source;
            if (!element.Mapping.TypeDesc.BaseTypeDesc.UseReflection)
            {
                text3 = "((" + cSharpName + ")" + source + ")";
            }
            ElementAccessor elementAccessor = element.Clone();
            elementAccessor.Mapping = ((NullableMapping)element.Mapping).BaseMapping;
            WriteElement(elementAccessor.Any ? source : text3, elementAccessor, arrayName, writeAccessor);
            base.Writer.Indent--;
            base.Writer.WriteLine("}");
            if (element.IsNullable)
            {
                base.Writer.WriteLine("else {");
                base.Writer.Indent++;
                WriteLiteralNullTag(element.Name, (element.Form == XmlSchemaForm.Qualified) ? element.Namespace : "");
                base.Writer.Indent--;
                base.Writer.WriteLine("}");
            }
        }
        else if (element.Mapping is ArrayMapping)
        {
            ArrayMapping arrayMapping = (ArrayMapping)element.Mapping;
            if (arrayMapping.IsSoap)
            {
                base.Writer.Write("WritePotentiallyReferencingElement(");
                WriteQuotedCSharpString(text);
                base.Writer.Write(", ");
                WriteQuotedCSharpString(text2);
                base.Writer.Write(", ");
                base.Writer.Write(source);
                if (!writeAccessor)
                {
                    base.Writer.Write(", ");
                    base.Writer.Write(base.RaCodeGen.GetStringForTypeof(arrayMapping.TypeDesc.CSharpName, arrayMapping.TypeDesc.UseReflection));
                    base.Writer.Write(", true, ");
                }
                else
                {
                    base.Writer.Write(", null, false, ");
                }
                WriteValue(element.IsNullable);
                base.Writer.WriteLine(");");
                return;
            }
            if (element.IsUnbounded)
            {
                TypeDesc typeDesc = arrayMapping.TypeDesc.CreateArrayTypeDesc();
                string cSharpName2 = typeDesc.CSharpName;
                string text4 = "el" + arrayName;
                string text5 = "c" + text4;
                base.Writer.WriteLine("{");
                base.Writer.Indent++;
                WriteArrayLocalDecl(cSharpName2, text4, source, arrayMapping.TypeDesc);
                if (element.IsNullable)
                {
                    WriteNullCheckBegin(text4, element);
                }
                else
                {
                    if (arrayMapping.TypeDesc.IsNullable)
                    {
                        base.Writer.Write("if (");
                        base.Writer.Write(text4);
                        base.Writer.Write(" != null)");
                    }
                    base.Writer.WriteLine("{");
                    base.Writer.Indent++;
                }
                base.Writer.Write("for (int ");
                base.Writer.Write(text5);
                base.Writer.Write(" = 0; ");
                base.Writer.Write(text5);
                base.Writer.Write(" < ");
                if (typeDesc.IsArray)
                {
                    base.Writer.Write(text4);
                    base.Writer.Write(".Length");
                }
                else
                {
                    base.Writer.Write("((");
                    base.Writer.Write(typeof(ICollection).FullName);
                    base.Writer.Write(")");
                    base.Writer.Write(text4);
                    base.Writer.Write(").Count");
                }
                base.Writer.Write("; ");
                base.Writer.Write(text5);
                base.Writer.WriteLine("++) {");
                base.Writer.Indent++;
                element.IsUnbounded = false;
                WriteElement(text4 + "[" + text5 + "]", element, arrayName, writeAccessor);
                element.IsUnbounded = true;
                base.Writer.Indent--;
                base.Writer.WriteLine("}");
                base.Writer.Indent--;
                base.Writer.WriteLine("}");
                base.Writer.Indent--;
                base.Writer.WriteLine("}");
                return;
            }
            string cSharpName3 = arrayMapping.TypeDesc.CSharpName;
            base.Writer.WriteLine("{");
            base.Writer.Indent++;
            WriteArrayLocalDecl(cSharpName3, arrayName, source, arrayMapping.TypeDesc);
            if (element.IsNullable)
            {
                WriteNullCheckBegin(arrayName, element);
            }
            else
            {
                if (arrayMapping.TypeDesc.IsNullable)
                {
                    base.Writer.Write("if (");
                    base.Writer.Write(arrayName);
                    base.Writer.Write(" != null)");
                }
                base.Writer.WriteLine("{");
                base.Writer.Indent++;
            }
            WriteStartElement(text, text2, writePrefixed: false);
            WriteArrayItems(arrayMapping.ElementsSortedByDerivation, null, null, arrayMapping.TypeDesc, arrayName, null);
            WriteEndElement();
            base.Writer.Indent--;
            base.Writer.WriteLine("}");
            base.Writer.Indent--;
            base.Writer.WriteLine("}");
        }
        else if (element.Mapping is EnumMapping)
        {
            if (element.Mapping.IsSoap)
            {
                string s = (string)base.MethodNames[element.Mapping];
                base.Writer.Write("Writer.WriteStartElement(");
                WriteQuotedCSharpString(text);
                base.Writer.Write(", ");
                WriteQuotedCSharpString(text2);
                base.Writer.WriteLine(");");
                base.Writer.Write(s);
                base.Writer.Write("(");
                base.Writer.Write(source);
                base.Writer.WriteLine(");");
                WriteEndElement();
            }
            else
            {
                WritePrimitive("WriteElementString", text, text2, element.Default, source, element.Mapping, writeXsiType: false, isElement: true, element.IsNullable);
            }
        }
        else if (element.Mapping is PrimitiveMapping)
        {
            PrimitiveMapping primitiveMapping = (PrimitiveMapping)element.Mapping;
            if (primitiveMapping.TypeDesc == base.QnameTypeDesc)
            {
                WriteQualifiedNameElement(text, text2, element.Default, source, element.IsNullable, primitiveMapping.IsSoap, primitiveMapping);
                return;
            }
            string text6 = (primitiveMapping.IsSoap ? "Encoded" : "Literal");
            string text7 = (primitiveMapping.TypeDesc.XmlEncodingNotRequired ? "Raw" : "");
            WritePrimitive(element.IsNullable ? ("WriteNullableString" + text6 + text7) : ("WriteElementString" + text7), text, text2, element.Default, source, primitiveMapping, primitiveMapping.IsSoap, isElement: true, element.IsNullable);
        }
        else if (element.Mapping is StructMapping)
        {
            StructMapping structMapping = (StructMapping)element.Mapping;
            if (structMapping.IsSoap)
            {
                base.Writer.Write("WritePotentiallyReferencingElement(");
                WriteQuotedCSharpString(text);
                base.Writer.Write(", ");
                WriteQuotedCSharpString(text2);
                base.Writer.Write(", ");
                base.Writer.Write(source);
                if (!writeAccessor)
                {
                    base.Writer.Write(", ");
                    base.Writer.Write(base.RaCodeGen.GetStringForTypeof(structMapping.TypeDesc.CSharpName, structMapping.TypeDesc.UseReflection));
                    base.Writer.Write(", true, ");
                }
                else
                {
                    base.Writer.Write(", null, false, ");
                }
                WriteValue(element.IsNullable);
            }
            else
            {
                string s2 = ReferenceMapping(structMapping);
                base.Writer.Write(s2);
                base.Writer.Write("(");
                WriteQuotedCSharpString(text);
                base.Writer.Write(", ");
                if (text2 == null)
                {
                    base.Writer.Write("null");
                }
                else
                {
                    WriteQuotedCSharpString(text2);
                }
                base.Writer.Write(", ");
                base.Writer.Write(source);
                if (structMapping.TypeDesc.IsNullable)
                {
                    base.Writer.Write(", ");
                    WriteValue(element.IsNullable);
                }
                base.Writer.Write(", false");
            }
            base.Writer.WriteLine(");");
        }
        else
        {
            if (!(element.Mapping is SpecialMapping))
            {
                throw new InvalidOperationException(System.SR.XmlInternalError);
            }
            if (element.Mapping is SerializableMapping)
            {
                WriteElementCall("WriteSerializable", typeof(IXmlSerializable), source, text, text2, element.IsNullable, !element.Any);
                return;
            }
            base.Writer.Write("if ((");
            base.Writer.Write(source);
            base.Writer.Write(") is ");
            base.Writer.Write(typeof(XmlNode).FullName);
            base.Writer.Write(" || ");
            base.Writer.Write(source);
            base.Writer.Write(" == null");
            base.Writer.WriteLine(") {");
            base.Writer.Indent++;
            WriteElementCall("WriteElementLiteral", typeof(XmlNode), source, text, text2, element.IsNullable, element.Any);
            base.Writer.Indent--;
            base.Writer.WriteLine("}");
            base.Writer.WriteLine("else {");
            base.Writer.Indent++;
            base.Writer.Write("throw CreateInvalidAnyTypeException(");
            base.Writer.Write(source);
            base.Writer.WriteLine(");");
            base.Writer.Indent--;
            base.Writer.WriteLine("}");
        }
    }
References System.Xml.Serialization.TypeDesc.TypeDesc(), System.Xml.Serialization.Accessor.Any, System.Xml.Serialization.TypeDesc.BaseTypeDesc, System.Xml.Serialization.ElementAccessor.Clone(), System.Xml.Serialization.TypeDesc.CSharpName, System.Xml.Serialization.Accessor.Default, System.Xml.Dictionary, System.Xml.Serialization.Accessor.Form, System.FullName, System.Xml.Serialization.ElementAccessor.IsNullable, System.Xml.Serialization.Mapping.IsSoap, System.Xml.Serialization.ElementAccessor.IsUnbounded, System.Xml.Serialization.Accessor.Mapping, System.Xml.Serialization.Accessor.Name, System.Xml.Serialization.Accessor.Namespace, System.Xml.Serialization.TypeMapping.Namespace, System.Xml.Serialization.XmlSerializationCodeGen.ReferenceMapping(), System.s, System.source, System.text, System.Xml.Serialization.TypeMapping.TypeDesc, System.Xml.Serialization.TypeMapping.TypeName, System.Xml.Serialization.TypeDesc.UseReflection, System.Xml.Serialization.XmlSerializationWriterCodeGen.WriteArrayItems(), System.Xml.Serialization.XmlSerializationWriterCodeGen.WriteArrayLocalDecl(), System.Xml.Serialization.XmlSerializationWriterCodeGen.WriteElement(), System.Xml.Serialization.XmlSerializationWriterCodeGen.WriteElementCall(), System.Xml.Serialization.XmlSerializationWriterCodeGen.WriteEndElement(), System.Xml.Serialization.XmlSerializationWriterCodeGen.WriteLiteralNullTag(), System.Xml.Serialization.XmlSerializationWriterCodeGen.WriteNullCheckBegin(), System.Xml.Serialization.XmlSerializationWriterCodeGen.WritePrimitive(), System.Xml.Serialization.XmlSerializationWriterCodeGen.WriteQualifiedNameElement(), System.Xml.Serialization.XmlSerializationCodeGen.WriteQuotedCSharpString(), System.Xml.Serialization.XmlSerializationWriterCodeGen.WriteStartElement(), System.Xml.Serialization.XmlSerializationWriterCodeGen.WriteValue(), and System.SR.XmlInternalError.
Referenced by System.Xml.Serialization.XmlSerializationWriterCodeGen.WriteElement(), and System.Xml.Serialization.XmlSerializationWriterCodeGen.WriteElements().