Terraria: System.Xml.Serialization.XmlSerializationWriterCodeGen.WriteMember
WriteMember() [1/2]
void System.Xml.Serialization.XmlSerializationWriterCodeGen.WriteMember (string source, AttributeAccessor attribute, TypeDesc memberTypeDesc, string parent) inline private
Definition at line 1022 of file XmlSerializationWriterCodeGen.cs.
    {
        if (memberTypeDesc.IsAbstract)
        {
            return;
        }
        if (memberTypeDesc.IsArrayLike)
        {
            base.Writer.WriteLine("{");
            base.Writer.Indent++;
            string cSharpName = memberTypeDesc.CSharpName;
            WriteArrayLocalDecl(cSharpName, "a", source, memberTypeDesc);
            if (memberTypeDesc.IsNullable)
            {
                base.Writer.WriteLine("if (a != null) {");
                base.Writer.Indent++;
            }
            if (attribute.IsList)
            {
                if (CanOptimizeWriteListSequence(memberTypeDesc.ArrayElementTypeDesc))
                {
                    base.Writer.Write("Writer.WriteStartAttribute(null, ");
                    WriteQuotedCSharpString(attribute.Name);
                    base.Writer.Write(", ");
                    string text = ((attribute.Form == XmlSchemaForm.Qualified) ? attribute.Namespace : string.Empty);
                    if (text != null)
                    {
                        WriteQuotedCSharpString(text);
                    }
                    else
                    {
                        base.Writer.Write("null");
                    }
                    base.Writer.WriteLine(");");
                }
                else
                {
                    base.Writer.Write(typeof(StringBuilder).FullName);
                    base.Writer.Write(" sb = new ");
                    base.Writer.Write(typeof(StringBuilder).FullName);
                    base.Writer.WriteLine("();");
                }
            }
            TypeDesc arrayElementTypeDesc = memberTypeDesc.ArrayElementTypeDesc;
            if (memberTypeDesc.IsEnumerable)
            {
                base.Writer.Write(" e = ");
                base.Writer.Write(typeof(IEnumerator).FullName);
                if (memberTypeDesc.IsPrivateImplementation)
                {
                    base.Writer.Write("((");
                    base.Writer.Write(typeof(IEnumerable).FullName);
                    base.Writer.WriteLine(").GetEnumerator();");
                }
                else if (memberTypeDesc.IsGenericInterface)
                {
                    if (memberTypeDesc.UseReflection)
                    {
                        base.Writer.Write("(");
                        base.Writer.Write(typeof(IEnumerator).FullName);
                        base.Writer.Write(")");
                        base.Writer.Write(base.RaCodeGen.GetReflectionVariable(memberTypeDesc.CSharpName, "System.Collections.Generic.IEnumerable*"));
                        base.Writer.WriteLine(".Invoke(a, new object[0]);");
                    }
                    else
                    {
                        base.Writer.Write("((System.Collections.Generic.IEnumerable<");
                        base.Writer.Write(arrayElementTypeDesc.CSharpName);
                        base.Writer.WriteLine(">)a).GetEnumerator();");
                    }
                }
                else
                {
                    if (memberTypeDesc.UseReflection)
                    {
                        base.Writer.Write("(");
                        base.Writer.Write(typeof(IEnumerator).FullName);
                        base.Writer.Write(")");
                    }
                    base.Writer.Write(base.RaCodeGen.GetStringForMethodInvoke("a", memberTypeDesc.CSharpName, "GetEnumerator", memberTypeDesc.UseReflection));
                    base.Writer.WriteLine(";");
                }
                base.Writer.WriteLine("if (e != null)");
                base.Writer.WriteLine("while (e.MoveNext()) {");
                base.Writer.Indent++;
                string cSharpName2 = arrayElementTypeDesc.CSharpName;
                WriteLocalDecl(cSharpName2, "ai", "e.Current", arrayElementTypeDesc.UseReflection);
            }
            else
            {
                base.Writer.Write("for (int i = 0; i < ");
                if (memberTypeDesc.IsArray)
                {
                    base.Writer.WriteLine("a.Length; i++) {");
                }
                else
                {
                    base.Writer.Write("((");
                    base.Writer.Write(typeof(ICollection).FullName);
                    base.Writer.WriteLine(")a).Count; i++) {");
                }
                base.Writer.Indent++;
                string cSharpName3 = arrayElementTypeDesc.CSharpName;
                WriteLocalDecl(cSharpName3, "ai", base.RaCodeGen.GetStringForArrayMember("a", "i", memberTypeDesc), arrayElementTypeDesc.UseReflection);
            }
            if (attribute.IsList)
            {
                if (CanOptimizeWriteListSequence(memberTypeDesc.ArrayElementTypeDesc))
                {
                    base.Writer.WriteLine("if (i != 0) Writer.WriteString(\" \");");
                    base.Writer.Write("WriteValue(");
                }
                else
                {
                    base.Writer.WriteLine("if (i != 0) sb.Append(\" \");");
                    base.Writer.Write("sb.Append(");
                }
                if (attribute.Mapping is EnumMapping)
                {
                    WriteEnumValue((EnumMapping)attribute.Mapping, "ai");
                }
                else
                {
                    WritePrimitiveValue(arrayElementTypeDesc, "ai", isElement: true);
                }
                base.Writer.WriteLine(");");
            }
            else
            {
                WriteAttribute("ai", attribute, parent);
            }
            base.Writer.Indent--;
            base.Writer.WriteLine("}");
            if (attribute.IsList)
            {
                if (CanOptimizeWriteListSequence(memberTypeDesc.ArrayElementTypeDesc))
                {
                    base.Writer.WriteLine("Writer.WriteEndAttribute();");
                }
                else
                {
                    base.Writer.WriteLine("if (sb.Length != 0) {");
                    base.Writer.Indent++;
                    base.Writer.Write("WriteAttribute(");
                    WriteQuotedCSharpString(attribute.Name);
                    base.Writer.Write(", ");
                    string text2 = ((attribute.Form == XmlSchemaForm.Qualified) ? attribute.Namespace : string.Empty);
                    if (text2 != null)
                    {
                        WriteQuotedCSharpString(text2);
                        base.Writer.Write(", ");
                    }
                    base.Writer.WriteLine("sb.ToString());");
                    base.Writer.Indent--;
                    base.Writer.WriteLine("}");
                }
            }
            if (memberTypeDesc.IsNullable)
            {
                base.Writer.Indent--;
                base.Writer.WriteLine("}");
            }
            base.Writer.Indent--;
            base.Writer.WriteLine("}");
        }
        else
        {
            WriteAttribute(source, attribute, parent);
        }
    }
References System.Xml.Serialization.TypeDesc.ArrayElementTypeDesc, System.Xml.Serialization.XmlSerializationWriterCodeGen.CanOptimizeWriteListSequence(), System.Xml.Serialization.TypeDesc.CSharpName, System.Xml.Dictionary, System.FullName, System.source, System.text, System.Xml.Serialization.XmlSerializationWriterCodeGen.WriteArrayLocalDecl(), System.Xml.Serialization.XmlSerializationWriterCodeGen.WriteAttribute(), System.Xml.Serialization.XmlSerializationWriterCodeGen.WriteEnumValue(), System.Xml.Serialization.XmlSerializationWriterCodeGen.WriteLocalDecl(), System.Xml.Serialization.XmlSerializationWriterCodeGen.WritePrimitiveValue(), and System.Xml.Serialization.XmlSerializationCodeGen.WriteQuotedCSharpString().
Referenced by System.Xml.Serialization.XmlSerializationWriterCodeGen.GenerateMembersElement(), System.Xml.Serialization.XmlSerializationWriterCodeGen.GenerateTypeElement(), System.Xml.Serialization.XmlSerializationWriterCodeGen.WriteEnumAndArrayTypes(), and System.Xml.Serialization.XmlSerializationWriterCodeGen.WriteStructMethod().