Terraria: System.Xml.Serialization.XmlSerializationWriterCodeGen.FindChoiceEnumValue
FindChoiceEnumValue()
string System.Xml.Serialization.XmlSerializationWriterCodeGen.FindChoiceEnumValue (ElementAccessor element, EnumMapping choiceMapping, bool useReflection) inline private
Definition at line 2184 of file XmlSerializationWriterCodeGen.cs.
    {
        string text = null;
        for (int i = 0; i < choiceMapping.Constants.Length; i++)
        {
            string xmlName = choiceMapping.Constants[i].XmlName;
            if (element.Any && element.Name.Length == 0)
            {
                if (xmlName == "##any:")
                {
                    text = ((!useReflection) ? choiceMapping.Constants[i].Name : choiceMapping.Constants[i].Value.ToString(CultureInfo.InvariantCulture));
                    break;
                }
                continue;
            }
            int num = xmlName.LastIndexOf(':');
            ReadOnlySpan<char> span = ((num < 0) ? ((ReadOnlySpan<char>)choiceMapping.Namespace) : xmlName.AsSpan(0, num));
            ReadOnlySpan<char> span2 = ((num < 0) ? ((ReadOnlySpan<char>)xmlName) : xmlName.AsSpan(num + 1));
            if (span2.SequenceEqual(element.Name) && ((element.Form == XmlSchemaForm.Unqualified && span.IsEmpty) || span.SequenceEqual(element.Namespace)))
            {
                text = ((!useReflection) ? choiceMapping.Constants[i].Name : choiceMapping.Constants[i].Value.ToString(CultureInfo.InvariantCulture));
                break;
            }
        }
        if (text == null || text.Length == 0)
        {
            if (element.Any && element.Name.Length == 0)
            {
                throw new InvalidOperationException(System.SR.Format(System.SR.XmlChoiceMissingAnyValue, choiceMapping.TypeDesc.FullName));
            }
            throw new InvalidOperationException(System.SR.Format(System.SR.XmlChoiceMissingValue, choiceMapping.TypeDesc.FullName, element.Namespace + ":" + element.Name, element.Name, element.Namespace));
        }
        if (!useReflection)
        {
            CodeIdentifier.CheckValidIdentifier(text);
        }
        return text;
    }
References System.Xml.Serialization.Accessor.Any, System.Xml.Serialization.CodeIdentifier.CheckValidIdentifier(), System.Xml.Dictionary, System.SR.Format(), System.Globalization.CultureInfo.InvariantCulture, System.Xml.Serialization.Accessor.Name, System.Xml.Serialization.Accessor.Namespace, System.text, System.SR.XmlChoiceMissingAnyValue, and System.SR.XmlChoiceMissingValue.
Referenced by System.Xml.Serialization.XmlSerializationWriterCodeGen.WriteElements().