Terraria: Terraria.GameContent.Tile_Entities.TEHatRack.TryFitting
TryFitting()
bool Terraria.GameContent.Tile_Entities.TEHatRack.TryFitting (Item[] inv, int context = 0, int slot = 0, bool justCheck = false) inline private
    {
        if (!FitsHatRack(inv[slot]))
        {
            return false;
        }
        if (justCheck)
        {
            return true;
        }
        int num = hatTargetSlot;
        hatTargetSlot++;
        for (int i = 0; i < 2; i++)
        {
            if (_items[i].IsAir)
            {
                num = i;
                hatTargetSlot = i + 1;
                break;
            }
        }
        for (int j = 0; j < 2; j++)
        {
            if (inv[slot].type == _items[j].type)
            {
                num = j;
            }
        }
        if (hatTargetSlot >= 2)
        {
            hatTargetSlot = 0;
        }
        SoundEngine.PlaySound(7);
        Utils.Swap(ref _items[num], ref inv[slot]);
        if (Main.netMode == 1)
        {
            NetMessage.SendData(124, -1, -1, null, Main.myPlayer, ID, num);
        }
        return true;
    }
References Terraria.GameContent.Tile_Entities.TEHatRack._items, Terraria.GameContent.Tile_Entities.TEHatRack.FitsHatRack(), Terraria.GameContent.Tile_Entities.TEHatRack.hatTargetSlot, Terraria.Main.myPlayer, Terraria.Main.netMode, Terraria.Audio.SoundEngine.PlaySound(), Terraria.NetMessage.SendData(), and Terraria.DataStructures.TileEntity.type.
Referenced by Terraria.GameContent.Tile_Entities.TEHatRack.OverrideItemSlotLeftClick().