Terraria: System.Xml.Serialization.XmlSerializationWriterCodeGen.WriteEnumValue
WriteEnumValue()
void System.Xml.Serialization.XmlSerializationWriterCodeGen.WriteEnumValue (EnumMapping mapping, string source) inline private
Definition at line 175 of file XmlSerializationWriterCodeGen.cs.
    {
        string s = ReferenceMapping(mapping);
        base.Writer.Write(s);
        base.Writer.Write("(");
        base.Writer.Write(source);
        base.Writer.Write(")");
    }
References System.Xml.Dictionary, System.Xml.Serialization.XmlSerializationCodeGen.ReferenceMapping(), System.s, and System.source.
Referenced by System.Xml.Serialization.XmlSerializationWriterCodeGen.WriteMember(), System.Xml.Serialization.XmlSerializationWriterCodeGen.WritePrimitive(), and System.Xml.Serialization.XmlSerializationWriterCodeGen.WriteText().