Terraria: System.Xml.Serialization.XmlSerializationWriterCodeGen.GenerateBegin
GenerateBegin()
void System.Xml.Serialization.XmlSerializationWriterCodeGen.GenerateBegin () inline package
Definition at line 18 of file XmlSerializationWriterCodeGen.cs.
    {
        base.Writer.Write(base.Access);
        base.Writer.Write(" class ");
        base.Writer.Write(base.ClassName);
        base.Writer.Write(" : ");
        base.Writer.Write(typeof(XmlSerializationWriter).FullName);
        base.Writer.WriteLine(" {");
        base.Writer.Indent++;
        TypeScope[] scopes = base.Scopes;
        foreach (TypeScope typeScope in scopes)
        {
            foreach (TypeMapping typeMapping3 in typeScope.TypeMappings)
            {
                if (typeMapping3 is StructMapping || typeMapping3 is EnumMapping)
                {
                    base.MethodNames.Add(typeMapping3, NextMethodName(typeMapping3.TypeDesc.Name));
                }
            }
            base.RaCodeGen.WriteReflectionInit(typeScope);
        }
        TypeScope[] scopes2 = base.Scopes;
        foreach (TypeScope typeScope2 in scopes2)
        {
            foreach (TypeMapping typeMapping4 in typeScope2.TypeMappings)
            {
                if (typeMapping4.IsSoap)
                {
                    if (typeMapping4 is StructMapping)
                    {
                        WriteStructMethod((StructMapping)typeMapping4);
                    }
                    else if (typeMapping4 is EnumMapping)
                    {
                        WriteEnumMethod((EnumMapping)typeMapping4);
                    }
                }
            }
        }
    }
References System.Xml.Dictionary, System.FullName, System.Xml.Serialization.XmlSerializationWriterCodeGen.NextMethodName(), System.Xml.Serialization.XmlSerializationWriterCodeGen.WriteEnumMethod(), and System.Xml.Serialization.XmlSerializationWriterCodeGen.WriteStructMethod().