Terraria: System.Xml.Serialization.XmlSerializationWriterCodeGen.WriteElements
WriteElements() [2/2]
void System.Xml.Serialization.XmlSerializationWriterCodeGen.WriteElements (string source, string enumSource, ElementAccessor[] elements, TextAccessor text, ChoiceIdentifierAccessor choice, string arrayName, bool writeAccessors, bool isNullable) inline private
Definition at line 1377 of file XmlSerializationWriterCodeGen.cs.
    {
        if (elements.Length == 0 && text == null)
        {
            return;
        }
        if (elements.Length == 1 && text == null)
        {
            TypeDesc typeDesc = (elements[0].IsUnbounded ? elements[0].Mapping.TypeDesc.CreateArrayTypeDesc() : elements[0].Mapping.TypeDesc);
            if (!elements[0].Any && !elements[0].Mapping.TypeDesc.UseReflection && !elements[0].Mapping.TypeDesc.IsOptionalValue)
            {
                source = "((" + typeDesc.CSharpName + ")" + source + ")";
            }
            WriteElement(source, elements[0], arrayName, writeAccessors);
            return;
        }
        if (isNullable && choice == null)
        {
            base.Writer.Write("if ((object)(");
            base.Writer.Write(source);
            base.Writer.Write(") != null)");
        }
        base.Writer.WriteLine("{");
        base.Writer.Indent++;
        int num = 0;
        ArrayList arrayList = new ArrayList();
        ElementAccessor elementAccessor = null;
        bool flag = false;
        string text2 = choice?.Mapping.TypeDesc.FullName;
        foreach (ElementAccessor elementAccessor2 in elements)
        {
            if (elementAccessor2.Any)
            {
                num++;
                if (elementAccessor2.Name != null && elementAccessor2.Name.Length > 0)
                {
                    arrayList.Add(elementAccessor2);
                }
                else if (elementAccessor == null)
                {
                    elementAccessor = elementAccessor2;
                }
            }
            else if (choice != null)
            {
                bool useReflection = elementAccessor2.Mapping.TypeDesc.UseReflection;
                string cSharpName = elementAccessor2.Mapping.TypeDesc.CSharpName;
                bool useReflection2 = choice.Mapping.TypeDesc.UseReflection;
                string text3 = (useReflection2 ? "" : (text2 + ".@")) + FindChoiceEnumValue(elementAccessor2, (EnumMapping)choice.Mapping, useReflection2);
                if (flag)
                {
                    base.Writer.Write("else ");
                }
                else
                {
                    flag = true;
                }
                base.Writer.Write("if (");
                base.Writer.Write(useReflection2 ? base.RaCodeGen.GetStringForEnumLongValue(enumSource, useReflection2) : enumSource);
                base.Writer.Write(" == ");
                base.Writer.Write(text3);
                if (isNullable && !elementAccessor2.IsNullable)
                {
                    base.Writer.Write(" && ((object)(");
                    base.Writer.Write(source);
                    base.Writer.Write(") != null)");
                }
                base.Writer.WriteLine(") {");
                base.Writer.Indent++;
                WriteChoiceTypeCheck(source, cSharpName, useReflection, choice, text3, elementAccessor2.Mapping.TypeDesc);
                string text4 = source;
                if (!useReflection)
                {
                    text4 = "((" + cSharpName + ")" + source + ")";
                }
                WriteElement(elementAccessor2.Any ? source : text4, elementAccessor2, arrayName, writeAccessors);
                base.Writer.Indent--;
                base.Writer.WriteLine("}");
            }
            else
            {
                bool useReflection3 = elementAccessor2.Mapping.TypeDesc.UseReflection;
                TypeDesc typeDesc2 = (elementAccessor2.IsUnbounded ? elementAccessor2.Mapping.TypeDesc.CreateArrayTypeDesc() : elementAccessor2.Mapping.TypeDesc);
                string cSharpName2 = typeDesc2.CSharpName;
                if (flag)
                {
                    base.Writer.Write("else ");
                }
                else
                {
                    flag = true;
                }
                base.Writer.Write("if (");
                WriteInstanceOf(source, cSharpName2, useReflection3);
                base.Writer.WriteLine(") {");
                base.Writer.Indent++;
                string text5 = source;
                if (!useReflection3)
                {
                    text5 = "((" + cSharpName2 + ")" + source + ")";
                }
                WriteElement(elementAccessor2.Any ? source : text5, elementAccessor2, arrayName, writeAccessors);
                base.Writer.Indent--;
                base.Writer.WriteLine("}");
            }
        }
        if (num > 0)
        {
            if (elements.Length - num > 0)
            {
                base.Writer.Write("else ");
            }
            string fullName = typeof(XmlElement).FullName;
            base.Writer.Write("if (");
            base.Writer.Write(source);
            base.Writer.Write(" is ");
            base.Writer.Write(fullName);
            base.Writer.WriteLine(") {");
            base.Writer.Indent++;
            base.Writer.Write(fullName);
            base.Writer.Write(" elem = (");
            base.Writer.Write(fullName);
            base.Writer.Write(")");
            base.Writer.Write(source);
            base.Writer.WriteLine(";");
            int num2 = 0;
            foreach (ElementAccessor item in arrayList)
            {
                if (num2++ > 0)
                {
                    base.Writer.Write("else ");
                }
                string text6 = null;
                if (choice != null)
                {
                    bool useReflection4 = choice.Mapping.TypeDesc.UseReflection;
                    text6 = (useReflection4 ? "" : (text2 + ".@")) + FindChoiceEnumValue(item, (EnumMapping)choice.Mapping, useReflection4);
                    base.Writer.Write("if (");
                    base.Writer.Write(useReflection4 ? base.RaCodeGen.GetStringForEnumLongValue(enumSource, useReflection4) : enumSource);
                    base.Writer.Write(" == ");
                    base.Writer.Write(text6);
                    if (isNullable && !item.IsNullable)
                    {
                        base.Writer.Write(" && ((object)(");
                        base.Writer.Write(source);
                        base.Writer.Write(") != null)");
                    }
                    base.Writer.WriteLine(") {");
                    base.Writer.Indent++;
                }
                base.Writer.Write("if (elem.Name == ");
                WriteQuotedCSharpString(item.Name);
                base.Writer.Write(" && elem.NamespaceURI == ");
                WriteQuotedCSharpString(item.Namespace);
                base.Writer.WriteLine(") {");
                base.Writer.Indent++;
                WriteElement("elem", item, arrayName, writeAccessors);
                if (choice != null)
                {
                    base.Writer.Indent--;
                    base.Writer.WriteLine("}");
                    base.Writer.WriteLine("else {");
                    base.Writer.Indent++;
                    base.Writer.WriteLine("// throw Value '{0}' of the choice identifier '{1}' does not match element '{2}' from namespace '{3}'.");
                    base.Writer.Write("throw CreateChoiceIdentifierValueException(");
                    WriteQuotedCSharpString(text6);
                    base.Writer.Write(", ");
                    WriteQuotedCSharpString(choice.MemberName);
                    base.Writer.WriteLine(", elem.Name, elem.NamespaceURI);");
                    base.Writer.Indent--;
                    base.Writer.WriteLine("}");
                }
                base.Writer.Indent--;
                base.Writer.WriteLine("}");
            }
            if (num2 > 0)
            {
                base.Writer.WriteLine("else {");
                base.Writer.Indent++;
            }
            if (elementAccessor != null)
            {
                WriteElement("elem", elementAccessor, arrayName, writeAccessors);
            }
            else
            {
                base.Writer.WriteLine("throw CreateUnknownAnyElementException(elem.Name, elem.NamespaceURI);");
            }
            if (num2 > 0)
            {
                base.Writer.Indent--;
                base.Writer.WriteLine("}");
            }
            base.Writer.Indent--;
            base.Writer.WriteLine("}");
        }
        if (text != null)
        {
            bool useReflection5 = text.Mapping.TypeDesc.UseReflection;
            string cSharpName3 = text.Mapping.TypeDesc.CSharpName;
            if (elements.Length != 0)
            {
                base.Writer.Write("else ");
                base.Writer.Write("if (");
                WriteInstanceOf(source, cSharpName3, useReflection5);
                base.Writer.WriteLine(") {");
                base.Writer.Indent++;
                string source2 = source;
                if (!useReflection5)
                {
                    source2 = "((" + cSharpName3 + ")" + source + ")";
                }
                WriteText(source2, text);
                base.Writer.Indent--;
                base.Writer.WriteLine("}");
            }
            else
            {
                string source3 = source;
                if (!useReflection5)
                {
                    source3 = "((" + cSharpName3 + ")" + source + ")";
                }
                WriteText(source3, text);
            }
        }
        if (elements.Length != 0)
        {
            base.Writer.Write("else ");
            if (isNullable)
            {
                base.Writer.Write(" if ((object)(");
                base.Writer.Write(source);
                base.Writer.Write(") != null)");
            }
            base.Writer.WriteLine("{");
            base.Writer.Indent++;
            base.Writer.Write("throw CreateUnknownTypeException(");
            base.Writer.Write(source);
            base.Writer.WriteLine(");");
            base.Writer.Indent--;
            base.Writer.WriteLine("}");
        }
        base.Writer.Indent--;
        base.Writer.WriteLine("}");
    }
References System.Any, System.Xml.Serialization.TypeDesc.CreateArrayTypeDesc(), System.Xml.Serialization.TypeDesc.CSharpName, System.Xml.Dictionary, System.Xml.Serialization.XmlSerializationWriterCodeGen.FindChoiceEnumValue(), System.Xml.Serialization.TypeDesc.FullName, System.Xml.Serialization.TypeDesc.IsOptionalValue, System.Xml.Serialization.ElementAccessor.IsUnbounded, System.item, System.Xml.Serialization.Accessor.Mapping, System.source, System.text, System.Xml.Serialization.TypeMapping.TypeDesc, System.Xml.Serialization.XmlSerializationWriterCodeGen.WriteChoiceTypeCheck(), System.Xml.Serialization.XmlSerializationWriterCodeGen.WriteElement(), System.Xml.Serialization.XmlSerializationWriterCodeGen.WriteInstanceOf(), System.Xml.Serialization.XmlSerializationCodeGen.WriteQuotedCSharpString(), and System.Xml.Serialization.XmlSerializationWriterCodeGen.WriteText().