Terraria: System.Xml.Serialization.XmlSerializationWriterCodeGen.GenerateMembersElement
GenerateMembersElement()
string System.Xml.Serialization.XmlSerializationWriterCodeGen.GenerateMembersElement (XmlMembersMapping xmlMembersMapping) inline private
Definition at line 367 of file XmlSerializationWriterCodeGen.cs.
    {
        ElementAccessor accessor = xmlMembersMapping.Accessor;
        MembersMapping membersMapping = (MembersMapping)accessor.Mapping;
        bool hasWrapperElement = membersMapping.HasWrapperElement;
        bool writeAccessors = membersMapping.WriteAccessors;
        bool flag = xmlMembersMapping.IsSoap && writeAccessors;
        string text = NextMethodName(accessor.Name);
        base.Writer.WriteLine();
        base.Writer.Write("public void ");
        base.Writer.Write(text);
        base.Writer.WriteLine("(object[] p) {");
        base.Writer.Indent++;
        base.Writer.WriteLine("WriteStartDocument();");
        if (!membersMapping.IsSoap)
        {
            base.Writer.WriteLine("TopLevelElement();");
        }
        base.Writer.WriteLine("int pLength = p.Length;");
        if (hasWrapperElement)
        {
            WriteStartElement(accessor.Name, (accessor.Form == XmlSchemaForm.Qualified) ? accessor.Namespace : "", membersMapping.IsSoap);
            int num = FindXmlnsIndex(membersMapping.Members);
            if (num >= 0)
            {
                string source = $"(({typeof(XmlSerializerNamespaces).FullName})p[{num}])";
                base.Writer.Write("if (pLength > ");
                base.Writer.Write(num.ToString(CultureInfo.InvariantCulture));
                base.Writer.WriteLine(") {");
                base.Writer.Indent++;
                WriteNamespaces(source);
                base.Writer.Indent--;
                base.Writer.WriteLine("}");
            }
            for (int i = 0; i < membersMapping.Members.Length; i++)
            {
                MemberMapping memberMapping = membersMapping.Members[i];
                if (memberMapping.Attribute == null || memberMapping.Ignore)
                {
                    continue;
                }
                string text2 = i.ToString(CultureInfo.InvariantCulture);
                string source2 = "p[" + text2 + "]";
                string text3 = null;
                int num2 = 0;
                if (memberMapping.CheckSpecified != 0)
                {
                    string text4 = memberMapping.Name + "Specified";
                    for (int j = 0; j < membersMapping.Members.Length; j++)
                    {
                        if (membersMapping.Members[j].Name == text4)
{
                            text3 = $"((bool) p[{j}])";
                            num2 = j;
                            break;
                        }
                    }
                }
                base.Writer.Write("if (pLength > ");
                base.Writer.Write(text2);
                base.Writer.WriteLine(") {");
                base.Writer.Indent++;
                if (text3 != null)
                {
                    base.Writer.Write("if (pLength <= ");
                    base.Writer.Write(num2.ToString(CultureInfo.InvariantCulture));
                    base.Writer.Write(" || ");
                    base.Writer.Write(text3);
                    base.Writer.WriteLine(") {");
                    base.Writer.Indent++;
                }
                WriteMember(source2, memberMapping.Attribute, memberMapping.TypeDesc, "p");
                if (text3 != null)
                {
                    base.Writer.Indent--;
                    base.Writer.WriteLine("}");
                }
                base.Writer.Indent--;
                base.Writer.WriteLine("}");
            }
        }
        for (int k = 0; k < membersMapping.Members.Length; k++)
        {
            MemberMapping memberMapping2 = membersMapping.Members[k];
            if (memberMapping2.Xmlns != null || memberMapping2.Ignore)
            {
                continue;
            }
            string text5 = null;
            int num3 = 0;
            if (memberMapping2.CheckSpecified != 0)
            {
                string text6 = memberMapping2.Name + "Specified";
                for (int l = 0; l < membersMapping.Members.Length; l++)
                {
                    if (membersMapping.Members[l].Name == text6)
                    {
                        text5 = $"((bool) p[{l}])";
                        num3 = l;
                        break;
                    }
                }
            }
            string text7 = k.ToString(CultureInfo.InvariantCulture);
            base.Writer.Write("if (pLength > ");
            base.Writer.Write(text7);
            base.Writer.WriteLine(") {");
            base.Writer.Indent++;
            if (text5 != null)
            {
                base.Writer.Write("if (pLength <= ");
                base.Writer.Write(num3.ToString(CultureInfo.InvariantCulture));
                base.Writer.Write(" || ");
                base.Writer.Write(text5);
                base.Writer.WriteLine(") {");
                base.Writer.Indent++;
            }
            string source3 = "p[" + text7 + "]";
            string choiceSource = null;
            if (memberMapping2.ChoiceIdentifier != null)
            {
                for (int m = 0; m < membersMapping.Members.Length; m++)
                {
                    if (membersMapping.Members[m].Name == memberMapping2.ChoiceIdentifier.MemberName)
                    {
                        choiceSource = ((!memberMapping2.ChoiceIdentifier.Mapping.TypeDesc.UseReflection) ? $"(({membersMapping.Members[m].TypeDesc.CSharpName})p[{m}])" : $"p[{m}]");
                        break;
                    }
                }
            }
            if (flag && memberMapping2.IsReturnValue && memberMapping2.Elements.Length != 0)
            {
                base.Writer.Write("WriteRpcResult(");
                WriteQuotedCSharpString(memberMapping2.Elements[0].Name);
                base.Writer.Write(", ");
                WriteQuotedCSharpString("");
                base.Writer.WriteLine(");");
            }
            WriteMember(source3, choiceSource, memberMapping2.ElementsSortedByDerivation, memberMapping2.Text, memberMapping2.ChoiceIdentifier, memberMapping2.TypeDesc, writeAccessors || hasWrapperElement);
            if (text5 != null)
            {
                base.Writer.Indent--;
                base.Writer.WriteLine("}");
            }
            base.Writer.Indent--;
            base.Writer.WriteLine("}");
        }
        if (hasWrapperElement)
        {
            WriteEndElement();
        }
        if (accessor.IsSoap)
        {
            if (!hasWrapperElement && !writeAccessors)
            {
                base.Writer.Write("if (pLength > ");
                base.Writer.Write(membersMapping.Members.Length.ToString(CultureInfo.InvariantCulture));
                base.Writer.WriteLine(") {");
                base.Writer.Indent++;
                WriteExtraMembers(membersMapping.Members.Length.ToString(CultureInfo.InvariantCulture), "pLength");
                base.Writer.Indent--;
                base.Writer.WriteLine("}");
            }
            base.Writer.WriteLine("WriteReferencedElements();");
        }
        base.Writer.Indent--;
        base.Writer.WriteLine("}");
        return text;
    }
References System.Xml.Serialization.Accessor.Accessor(), System.Xml.Serialization.Mapping.Mapping(), System.Xml.Dictionary, System.Xml.Serialization.XmlSerializationWriterCodeGen.FindXmlnsIndex(), System.Globalization.CultureInfo.InvariantCulture, System.Xml.Serialization.XmlSerializationWriterCodeGen.NextMethodName(), System.source, System.text, System.Xml.Serialization.XmlSerializationWriterCodeGen.WriteEndElement(), System.Xml.Serialization.XmlSerializationWriterCodeGen.WriteExtraMembers(), System.Xml.Serialization.XmlSerializationWriterCodeGen.WriteMember(), System.Xml.Serialization.XmlSerializationWriterCodeGen.WriteNamespaces(), System.Xml.Serialization.XmlSerializationCodeGen.WriteQuotedCSharpString(), and System.Xml.Serialization.XmlSerializationWriterCodeGen.WriteStartElement().
Referenced by System.Xml.Serialization.XmlSerializationWriterCodeGen.GenerateElement().