Terraria: System.Xml.Serialization.XmlSerializationWriterCodeGen.WritePrimitiveValue
WritePrimitiveValue()
void System.Xml.Serialization.XmlSerializationWriterCodeGen.WritePrimitiveValue (TypeDesc typeDesc, string source, bool isElement) inline private
Definition at line 184 of file XmlSerializationWriterCodeGen.cs.
    {
        if (typeDesc == base.StringTypeDesc || typeDesc.FormatterName == "String")
        {
            base.Writer.Write(source);
        }
        else if (!typeDesc.HasCustomFormatter)
        {
            base.Writer.Write(typeof(XmlConvert).FullName);
            base.Writer.Write(".ToString((");
            base.Writer.Write(typeDesc.CSharpName);
            base.Writer.Write(")");
            base.Writer.Write(source);
            base.Writer.Write(")");
        }
        else
        {
            base.Writer.Write("From");
            base.Writer.Write(typeDesc.FormatterName);
            base.Writer.Write("(");
            base.Writer.Write(source);
            base.Writer.Write(")");
        }
    }
References System.Xml.Dictionary, System.FullName, and System.source.
Referenced by System.Xml.Serialization.XmlSerializationWriterCodeGen.WriteMember(), System.Xml.Serialization.XmlSerializationWriterCodeGen.WritePrimitive(), and System.Xml.Serialization.XmlSerializationWriterCodeGen.WriteText().