Terraria: System.Xml.Serialization.XmlSerializationWriterCodeGen.WriteValue
WriteValue()
void System.Xml.Serialization.XmlSerializationWriterCodeGen.WriteValue (object value) inline private
Definition at line 1992 of file XmlSerializationWriterCodeGen.cs.
    {
        if (value == null)
        {
            base.Writer.Write("null");
            return;
        }
        Type type = value.GetType();
        if (type == typeof(string))
        {
            string value2 = (string)value;
            WriteQuotedCSharpString(value2);
        }
        else if (type == typeof(char))
        {
            base.Writer.Write('\'');
            char c = (char)value;
            if (c == '\'')
            {
                base.Writer.Write("'");
            }
            else
            {
                base.Writer.Write(c);
            }
            base.Writer.Write('\'');
        }
        else if (type == typeof(int))
        {
            base.Writer.Write(((int)value).ToString(null, NumberFormatInfo.InvariantInfo));
        }
        else if (type == typeof(double))
        {
            if (double.IsNaN((double)value))
            {
                base.Writer.Write("System.Double.NaN");
            }
            else if (double.IsPositiveInfinity((double)value))
            {
                base.Writer.Write("System.Double.PositiveInfinity");
            }
            else if (double.IsNegativeInfinity((double)value))
            {
                base.Writer.Write("System.Double.NegativeInfinity");
            }
            else
            {
                base.Writer.Write(((double)value).ToString("R", NumberFormatInfo.InvariantInfo));
            }
        }
        else if (type == typeof(bool))
        {
            base.Writer.Write(((bool)value) ? "true" : "false");
        }
        else if (type == typeof(short) || type == typeof(long) || type == typeof(ushort) || type == typeof(uint) || type == typeof(ulong) || type == typeof(byte) || type == typeof(sbyte))
        {
            base.Writer.Write("(");
            base.Writer.Write(type.FullName);
            base.Writer.Write(")");
            base.Writer.Write("(");
            base.Writer.Write(Convert.ToString(value, NumberFormatInfo.InvariantInfo));
            base.Writer.Write(")");
        }
        else if (type == typeof(float))
        {
            if (float.IsNaN((float)value))
            {
                base.Writer.Write("System.Single.NaN");
                return;
            }
            if (float.IsPositiveInfinity((float)value))
            {
                base.Writer.Write("System.Single.PositiveInfinity");
                return;
            }
            if (float.IsNegativeInfinity((float)value))
            {
                base.Writer.Write("System.Single.NegativeInfinity");
                return;
            }
            base.Writer.Write(((float)value).ToString("R", NumberFormatInfo.InvariantInfo));
            base.Writer.Write("f");
        }
        else if (type == typeof(decimal))
        {
            base.Writer.Write(((decimal)value).ToString(null, NumberFormatInfo.InvariantInfo));
            base.Writer.Write("m");
        }
        else if (type == typeof(DateTime))
        {
            base.Writer.Write(" new ");
            base.Writer.Write(type.FullName);
            base.Writer.Write("(");
            base.Writer.Write(((DateTime)value).Ticks.ToString(CultureInfo.InvariantCulture));
            base.Writer.Write(")");
        }
        else if (type == typeof(DateTimeOffset))
        {
            base.Writer.Write(" new ");
            base.Writer.Write(type.FullName);
            base.Writer.Write("(");
            base.Writer.Write(((DateTimeOffset)value).Ticks.ToString(CultureInfo.InvariantCulture));
            base.Writer.Write(", new ");
            base.Writer.Write(((DateTimeOffset)value).Offset.GetType().FullName);
            base.Writer.Write("(");
            base.Writer.Write(((DateTimeOffset)value).Offset.Ticks.ToString(CultureInfo.InvariantCulture));
            base.Writer.Write("))");
        }
        else if (type == typeof(TimeSpan))
        {
            base.Writer.Write(" new ");
            base.Writer.Write(type.FullName);
            base.Writer.Write("(");
            base.Writer.Write(((TimeSpan)value).Ticks.ToString(CultureInfo.InvariantCulture));
            base.Writer.Write(")");
        }
        else
        {
            if (!type.IsEnum)
            {
                throw new InvalidOperationException(System.SR.Format(System.SR.XmlUnsupportedDefaultType, type.FullName));
            }
            base.Writer.Write(((int)value).ToString(null, NumberFormatInfo.InvariantInfo));
        }
    }
References System.Xml.Dictionary, System.SR.Format(), System.Type.GetType(), System.Globalization.CultureInfo.InvariantCulture, System.Globalization.NumberFormatInfo.InvariantInfo, System.Convert.ToString(), System.ToString, System.type, System.value, System.Xml.Serialization.XmlSerializationCodeGen.WriteQuotedCSharpString(), and System.SR.XmlUnsupportedDefaultType.
Referenced by System.Xml.Serialization.XmlSerializationWriterCodeGen.WriteCheckDefault(), System.Xml.Serialization.XmlSerializationWriterCodeGen.WriteElement(), and System.Xml.Serialization.XmlSerializationWriterCodeGen.WriteElementCall().