Terraria: System.Xml.Serialization.XmlSerializationWriterCodeGen.WritePrimitive
WritePrimitive()
void System.Xml.Serialization.XmlSerializationWriterCodeGen.WritePrimitive (string method, string name, string ns, object defaultValue, string source, TypeMapping mapping, bool writeXsiType, bool isElement, bool isNullable) inline private
Definition at line 210 of file XmlSerializationWriterCodeGen.cs.
    {
        TypeDesc typeDesc = mapping.TypeDesc;
        bool flag = defaultValue != null && defaultValue != DBNull.Value && mapping.TypeDesc.HasDefaultSupport;
        if (flag)
        {
            if (mapping is EnumMapping)
            {
                base.Writer.Write("if (");
                if (mapping.TypeDesc.UseReflection)
                {
                    base.Writer.Write(base.RaCodeGen.GetStringForEnumLongValue(source, mapping.TypeDesc.UseReflection));
                }
                else
                {
                    base.Writer.Write(source);
                }
                base.Writer.Write(" != ");
                if (((EnumMapping)mapping).IsFlags)
                {
                    base.Writer.Write("(");
                    string[] array = ((string)defaultValue).Split((char[]?)null);
                    for (int i = 0; i < array.Length; i++)
                    {
                        if (array[i] != null && array[i].Length != 0)
{
                            if (i > 0)
{
                                base.Writer.WriteLine(" | ");
                            }
                            base.Writer.Write(base.RaCodeGen.GetStringForEnumCompare((EnumMapping)mapping, array[i], mapping.TypeDesc.UseReflection));
                        }
                    }
                    base.Writer.Write(")");
                }
                else
                {
                    base.Writer.Write(base.RaCodeGen.GetStringForEnumCompare((EnumMapping)mapping, (string)defaultValue, mapping.TypeDesc.UseReflection));
                }
                base.Writer.Write(")");
            }
            else
            {
                WriteCheckDefault(mapping, source, defaultValue, isNullable);
            }
            base.Writer.WriteLine(" {");
            base.Writer.Indent++;
        }
        base.Writer.Write(method);
        base.Writer.Write("(");
        WriteQuotedCSharpString(name);
        if (ns != null)
        {
            base.Writer.Write(", ");
            WriteQuotedCSharpString(ns);
        }
        base.Writer.Write(", ");
        if (mapping is EnumMapping)
        {
            WriteEnumValue((EnumMapping)mapping, source);
        }
        else
        {
            WritePrimitiveValue(typeDesc, source, isElement);
        }
        if (writeXsiType)
        {
            base.Writer.Write(", new System.Xml.XmlQualifiedName(");
            WriteQuotedCSharpString(mapping.TypeName);
            base.Writer.Write(", ");
            WriteQuotedCSharpString(mapping.Namespace);
            base.Writer.Write(")");
        }
        base.Writer.WriteLine(");");
        if (flag)
        {
            base.Writer.Indent--;
            base.Writer.WriteLine("}");
        }
    }
References System.Xml.Serialization.TypeDesc.TypeDesc(), System.array, System.Xml.Dictionary, System.Xml.Schema.Length, System.source, System.Xml.Serialization.XmlSerializationWriterCodeGen.WriteCheckDefault(), System.Xml.Serialization.XmlSerializationWriterCodeGen.WriteEnumValue(), System.Xml.Serialization.XmlSerializationWriterCodeGen.WritePrimitiveValue(), and System.Xml.Serialization.XmlSerializationCodeGen.WriteQuotedCSharpString().
Referenced by System.Xml.Serialization.XmlSerializationWriterCodeGen.WriteAttribute(), and System.Xml.Serialization.XmlSerializationWriterCodeGen.WriteElement().