Terraria: System.Runtime.Serialization.Json.JsonDataContract.WriteJsonValue
WriteJsonValue()
void System.Runtime.Serialization.Json.JsonDataContract.WriteJsonValue (XmlWriterDelegator jsonWriter, object obj, XmlObjectSerializerWriteContextComplexJson context, RuntimeTypeHandle declaredTypeHandle) inline inherited
Definition at line 249 of file JsonDataContract.cs.
    {
        PushKnownDataContracts(context);
        WriteJsonValueCore(jsonWriter, obj, context, declaredTypeHandle);
        PopKnownDataContracts(context);
    }
References System.obj, System.Runtime.Serialization.Json.JsonDataContract.PopKnownDataContracts(), System.Runtime.Serialization.Json.JsonDataContract.PushKnownDataContracts(), and System.Runtime.Serialization.Json.JsonDataContract.WriteJsonValueCore().