Terraria: System.Net.Http.HttpConnectionPoolManager.SendAsyncCore
SendAsyncCore()
ValueTask< HttpResponseMessage > System.Net.Http.HttpConnectionPoolManager.SendAsyncCore (HttpRequestMessage request, Uri proxyUri, bool async, bool doRequestAuth, bool isProxyConnect, CancellationToken cancellationToken) inline
Definition at line 267 of file HttpConnectionPoolManager.cs.
    {
        HttpConnectionKey connectionKey = GetConnectionKey(request, proxyUri, isProxyConnect);
        HttpConnectionPool value;
        while (!_pools.TryGetValue(connectionKey, out value))
        {
            value = new HttpConnectionPool(this, connectionKey.Kind, connectionKey.Host, connectionKey.Port, connectionKey.SslHostName, connectionKey.ProxyUri);
            if (_cleaningTimer == null)
            {
                break;
            }
            if (!_pools.TryAdd(connectionKey, value))
            {
                continue;
            }
            lock (SyncObj)
            {
                if (!_timerIsRunning)
                {
                    SetCleaningTimer(_cleanPoolTimeout);
                }
            }
            break;
        }
        return value.SendAsync(request, async, doRequestAuth, cancellationToken);
    }
References System.Net.Http.HttpConnectionPoolManager._cleaningTimer, System.Net.Http.HttpConnectionPoolManager._cleanPoolTimeout, System.Net.Http.HttpConnectionPoolManager._pools, System.Net.Http.HttpConnectionPoolManager._timerIsRunning, System.cancellationToken, System.Net.Http.HttpConnectionPoolManager.GetConnectionKey(), System.Net.Http.HttpConnectionPoolManager.SetCleaningTimer(), System.Net.Http.HttpConnectionPoolManager.SyncObj, System.Collections.Generic.Dictionary< TKey, TValue >.TryAdd(), System.Collections.Generic.Dictionary< TKey, TValue >.TryGetValue(), and System.value.
Referenced by System.Net.Http.HttpConnectionPoolManager.SendAsync(), System.Net.Http.HttpConnectionPoolManager.SendAsyncMultiProxy(), and System.Net.Http.HttpConnectionPoolManager.SendProxyConnectAsync().