Terraria: System.Runtime.Serialization.Json.JsonDataContract.TryReadNullAtTopLevel
TryReadNullAtTopLevel()
static bool System.Runtime.Serialization.Json.JsonDataContract.TryReadNullAtTopLevel (XmlReaderDelegator reader) inline static protected inherited
Definition at line 268 of file JsonDataContract.cs.
    {
        if (reader.MoveToAttribute("type") && reader.Value == "null")
        {
            reader.Skip();
            reader.MoveToElement();
            return true;
        }
        reader.MoveToElement();
        return false;
    }
References System.Runtime.Serialization.XmlReaderDelegator.MoveToAttribute(), System.Runtime.Serialization.XmlReaderDelegator.MoveToElement(), System.Runtime.Serialization.XmlReaderDelegator.Skip(), and System.Runtime.Serialization.XmlReaderDelegator.Value.
Referenced by System.Runtime.Serialization.Json.JsonByteArrayDataContract.ReadJsonValueCore(), System.Runtime.Serialization.Json.JsonQNameDataContract.ReadJsonValueCore(), System.Runtime.Serialization.Json.JsonStringDataContract.ReadJsonValueCore(), and System.Runtime.Serialization.Json.JsonUriDataContract.ReadJsonValueCore().