Terraria: System.Net.Http.HttpConnectionPoolManager.SetCleaningTimer
SetCleaningTimer()
void System.Net.Http.HttpConnectionPoolManager.SetCleaningTimer (TimeSpan timeout) inline private
Definition at line 369 of file HttpConnectionPoolManager.cs.
    {
        try
        {
            _cleaningTimer.Change(timeout, timeout);
            _timerIsRunning = timeout != Timeout.InfiniteTimeSpan;
        }
        catch (ObjectDisposedException)
        {
        }
    }
References System.Net.Http.HttpConnectionPoolManager._cleaningTimer, System.Net.Http.HttpConnectionPoolManager._timerIsRunning, System.Threading.Timer.Change(), System.Threading.Timeout.InfiniteTimeSpan, and System.timeout.
Referenced by System.Net.Http.HttpConnectionPoolManager.RemoveStalePools(), and System.Net.Http.HttpConnectionPoolManager.SendAsyncCore().