Terraria: System.Net.Http.HttpConnectionPoolManager.StartMonitoringNetworkChanges
StartMonitoringNetworkChanges()
void System.Net.Http.HttpConnectionPoolManager.StartMonitoringNetworkChanges () inline
Definition at line 173 of file HttpConnectionPoolManager.cs.
    {
        if (_networkChangeCleanup != null)
        {
            return;
        }
        WeakReference<ConcurrentDictionary<HttpConnectionKey, HttpConnectionPool>> poolsRef = new WeakReference<ConcurrentDictionary<HttpConnectionKey, HttpConnectionPool>>(_pools);
        NetworkAddressChangedEventHandler networkAddressChangedEventHandler = delegate
        {
            if (poolsRef.TryGetTarget(out var target))
            {
                foreach (HttpConnectionPool value in target.Values)
                {
                    value.OnNetworkChanged();
                }
            }
        };
        NetworkChangeCleanup networkChangeCleanup = new NetworkChangeCleanup(networkAddressChangedEventHandler);
        if (Interlocked.CompareExchange(ref _networkChangeCleanup, networkChangeCleanup, null) != null)
        {
            GC.SuppressFinalize(networkChangeCleanup);
            return;
        }
        if (!ExecutionContext.IsFlowSuppressed())
        {
            using (ExecutionContext.SuppressFlow())
            {
                NetworkChange.NetworkAddressChanged += networkAddressChangedEventHandler;
                return;
            }
        }
        NetworkChange.NetworkAddressChanged += networkAddressChangedEventHandler;
    }
References System.Net.Http.HttpConnectionPoolManager._networkChangeCleanup, System.Net.Http.HttpConnectionPoolManager._pools, System.Threading.Interlocked.CompareExchange(), System.Threading.ExecutionContext.IsFlowSuppressed(), System.Net.NetworkInformation.NetworkAddressChangedEventHandler(), System.GC.SuppressFinalize(), System.Threading.ExecutionContext.SuppressFlow(), System.value, and System.Collections.Generic.Dictionary< TKey, TValue >.Values.
Referenced by System.Net.Http.HttpConnectionPool.HandleAltSvc().