Terraria: System.Net.Http.HttpConnectionPoolManager.Dispose
Dispose()
void System.Net.Http.HttpConnectionPoolManager.Dispose () inline
Implements System.IDisposable.
Definition at line 358 of file HttpConnectionPoolManager.cs.
    {
        _cleaningTimer?.Dispose();
        _heartBeatTimer?.Dispose();
        foreach (KeyValuePair<HttpConnectionKey, HttpConnectionPool> pool in _pools)
        {
            pool.Value.Dispose();
        }
        _networkChangeCleanup?.Dispose();
    }
References System.Net.Http.HttpConnectionPoolManager._cleaningTimer, System.Net.Http.HttpConnectionPoolManager._heartBeatTimer, System.Net.Http.HttpConnectionPoolManager._networkChangeCleanup, System.Net.Http.HttpConnectionPoolManager._pools, System.Net.Http.HttpConnectionPoolManager.NetworkChangeCleanup.Dispose(), and System.Threading.Timer.Dispose().
Referenced by System.Net.Http.HttpAuthenticatedConnectionHandler.Dispose(), and System.Net.Http.HttpConnectionHandler.Dispose().