Terraria: System.Runtime.Serialization.Json.JsonDataContract.PopKnownDataContracts
PopKnownDataContracts()
void System.Runtime.Serialization.Json.JsonDataContract.PopKnownDataContracts (XmlObjectSerializerContext context) inline protected inherited
Definition at line 280 of file JsonDataContract.cs.
    {
        if (KnownDataContracts != null)
        {
            context.scopedKnownTypes.Pop();
        }
    }
References System.Runtime.Serialization.Json.JsonDataContract.KnownDataContracts, System.Runtime.Serialization.ScopedKnownTypes.Pop(), and System.Runtime.Serialization.XmlObjectSerializerContext.scopedKnownTypes.
Referenced by System.Runtime.Serialization.Json.JsonDataContract.ReadJsonValue(), and System.Runtime.Serialization.Json.JsonDataContract.WriteJsonValue().