Terraria: System.Net.Http.HttpConnectionPoolManager.SendAsync
SendAsync()
ValueTask< HttpResponseMessage > System.Net.Http.HttpConnectionPoolManager.SendAsync (HttpRequestMessage request, bool async, bool doRequestAuth, CancellationToken cancellationToken) inline
Definition at line 299 of file HttpConnectionPoolManager.cs.
    {
        if (_proxy == null)
        {
            return SendAsyncCore(request, null, async, doRequestAuth, isProxyConnect: false, cancellationToken);
        }
        Uri uri = null;
        try
        {
            if (!_proxy.IsBypassed(request.RequestUri))
            {
                if (_proxy is IMultiWebProxy multiWebProxy)
                {
                    MultiProxy multiProxy = multiWebProxy.GetMultiProxy(request.RequestUri);
                    if (multiProxy.ReadNext(out uri, out var isFinalProxy) && !isFinalProxy)
                    {
                        return SendAsyncMultiProxy(request, async, doRequestAuth, multiProxy, uri, cancellationToken);
                    }
                }
                else
                {
                    uri = _proxy.GetProxy(request.RequestUri);
                }
            }
        }
        catch (Exception ex)
        {
            if (System.Net.NetEventSource.Log.IsEnabled())
            {
                System.Net.NetEventSource.Error(this, $"Exception from {_proxy.GetType().Name}.GetProxy({request.RequestUri}): {ex}", "SendAsync");
            }
        }
        if (uri != null && !HttpUtilities.IsSupportedProxyScheme(uri.Scheme))
        {
            throw new NotSupportedException(System.SR.net_http_invalid_proxy_scheme);
        }
        return SendAsyncCore(request, uri, async, doRequestAuth, isProxyConnect: false, cancellationToken);
    }
References System.Net.Http.HttpConnectionPoolManager._proxy, System.cancellationToken, System.Net.NetEventSource.Error(), System.Net.IWebProxy.GetProxy(), System.Net.IWebProxy.IsBypassed(), System.Net.Http.HttpUtilities.IsSupportedProxyScheme(), System.Net.NetEventSource.Log, System.SR.net_http_invalid_proxy_scheme, System.Uri.Scheme, System.Net.Http.HttpConnectionPoolManager.SendAsyncCore(), and System.Net.Http.HttpConnectionPoolManager.SendAsyncMultiProxy().
Referenced by System.Net.Http.HttpAuthenticatedConnectionHandler.SendAsync(), and System.Net.Http.HttpConnectionHandler.SendAsync().