Terraria: System.Net.Http.HttpConnectionPoolManager.SendAsyncMultiProxy
SendAsyncMultiProxy()
async ValueTask< HttpResponseMessage > System.Net.Http.HttpConnectionPoolManager.SendAsyncMultiProxy (HttpRequestMessage request, bool async, bool doRequestAuth, MultiProxy multiProxy, Uri firstProxy, CancellationToken cancellationToken) inline private
Definition at line 338 of file HttpConnectionPoolManager.cs.
    {
        HttpRequestException source;
        bool isFinalProxy;
        do
        {
            try
            {
                return await SendAsyncCore(request, firstProxy, async, doRequestAuth, isProxyConnect: false, cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
            }
            catch (HttpRequestException ex) when (ex.AllowRetry != RequestRetryType.NoRetry)
            {
                source = ex;
            }
        }
        while (multiProxy.ReadNext(out firstProxy, out isFinalProxy));
        ExceptionDispatchInfo.Throw(source);
        return null;
    }
References System.cancellationToken, System.Net.Http.HttpConnectionPoolManager.SendAsyncCore(), System.source, and System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw().
Referenced by System.Net.Http.HttpConnectionPoolManager.SendAsync().