Terraria: System.Net.Http.HttpConnectionPoolManager.HttpConnectionPoolManager
HttpConnectionPoolManager()
System.Net.Http.HttpConnectionPoolManager.HttpConnectionPoolManager (HttpConnectionSettings settings) inline
Definition at line 110 of file HttpConnectionPoolManager.cs.
    {
        _settings = settings;
        _pools = new ConcurrentDictionary<HttpConnectionKey, HttpConnectionPool>();
        if (settings._maxConnectionsPerServer != int.MaxValue || (!(settings._pooledConnectionIdleTimeout == TimeSpan.Zero) && !(settings._pooledConnectionLifetime == TimeSpan.Zero)))
        {
            if (settings._pooledConnectionIdleTimeout == Timeout.InfiniteTimeSpan)
            {
                _cleanPoolTimeout = TimeSpan.FromSeconds(30.0);
            }
            else
            {
                TimeSpan timeSpan = settings._pooledConnectionIdleTimeout / 4.0;
                _cleanPoolTimeout = ((timeSpan.TotalSeconds >= 1.0) ? timeSpan : TimeSpan.FromSeconds(1.0));
            }
            bool flag = false;
            try
            {
                if (!ExecutionContext.IsFlowSuppressed())
                {
                    ExecutionContext.SuppressFlow();
                    flag = true;
                }
                WeakReference<HttpConnectionPoolManager> state2 = new WeakReference<HttpConnectionPoolManager>(this);
                _cleaningTimer = new Timer(delegate(object s)
                {
                    WeakReference<HttpConnectionPoolManager> weakReference2 = (WeakReference<HttpConnectionPoolManager>)s;
                    if (weakReference2.TryGetTarget(out var target2))
                    {
                        target2.RemoveStalePools();
                    }
                }, state2, -1, -1);
                if (_settings._keepAlivePingDelay != Timeout.InfiniteTimeSpan)
                {
                    long num = (long)Math.Max(1000.0, Math.Min(_settings._keepAlivePingDelay.TotalMilliseconds, _settings._keepAlivePingTimeout.TotalMilliseconds) / 4.0);
                    _heartBeatTimer = new Timer(delegate(object state)
                    {
                        WeakReference<HttpConnectionPoolManager> weakReference = (WeakReference<HttpConnectionPoolManager>)state;
                        if (weakReference.TryGetTarget(out var target))
{
                            target.HeartBeat();
                        }
                    }, state2, num, num);
                }
            }
            finally
            {
                if (flag)
                {
                    ExecutionContext.RestoreFlow();
                }
            }
        }
        if (settings._useProxy)
        {
            _proxy = settings._proxy ?? HttpClient.DefaultProxy;
            if (_proxy != null)
            {
                _proxyCredentials = _proxy.Credentials ?? settings._defaultProxyCredentials;
            }
        }
    }
References System.Net.Http.HttpConnectionPoolManager._cleaningTimer, System.Net.Http.HttpConnectionPoolManager._cleanPoolTimeout, System.Net.Http.HttpConnectionSettings._defaultProxyCredentials, System.Net.Http.HttpConnectionPoolManager._heartBeatTimer, System.Net.Http.HttpConnectionSettings._keepAlivePingDelay, System.Net.Http.HttpConnectionSettings._keepAlivePingTimeout, System.Net.Http.HttpConnectionSettings._maxConnectionsPerServer, System.Net.Http.HttpConnectionSettings._pooledConnectionIdleTimeout, System.Net.Http.HttpConnectionSettings._pooledConnectionLifetime, System.Net.Http.HttpConnectionPoolManager._pools, System.Net.Http.HttpConnectionPoolManager._proxy, System.Net.Http.HttpConnectionPoolManager._proxyCredentials, System.Net.Http.HttpConnectionPoolManager._settings, System.Net.Http.HttpConnectionSettings._useProxy, System.Net.Http.HttpClient.DefaultProxy, System.TimeSpan.FromSeconds(), System.Threading.Timeout.InfiniteTimeSpan, System.Threading.ExecutionContext.IsFlowSuppressed(), System.Math.Max(), System.Math.Min(), System.Threading.ExecutionContext.RestoreFlow(), System.s, System.state, System.Threading.ExecutionContext.SuppressFlow(), System.TimeSpan.TotalMilliseconds, and System.TimeSpan.Zero.