Terraria: System.Text.RegularExpressions.RegexParser.AssignNameSlots
AssignNameSlots()
void System.Text.RegularExpressions.RegexParser.AssignNameSlots () inline private
Definition at line 1634 of file RegexParser.cs.
    {
        if (_capnames != null)
        {
            for (int i = 0; i < _capnamelist.Count; i++)
            {
                while (IsCaptureSlot(_autocap))
                {
                    _autocap++;
                }
                string key = _capnamelist[i];
                int pos = (int)_capnames[key];
                _capnames[key] = _autocap;
                NoteCaptureSlot(_autocap, pos);
                _autocap++;
            }
        }
        if (_capcount < _captop)
        {
            _capnumlist = new int[_capcount];
            int num = 0;
            IDictionaryEnumerator enumerator = _caps.GetEnumerator();
            while (enumerator.MoveNext())
            {
                _capnumlist[num++] = (int)enumerator.Key;
            }
            Array.Sort(_capnumlist);
        }
        if (_capnames == null && _capnumlist == null)
        {
            return;
        }
        int num2 = 0;
        List<string> list;
        int num3;
        if (_capnames == null)
        {
            list = null;
            _capnames = new Hashtable();
            _capnamelist = new List<string>();
            num3 = -1;
        }
        else
        {
            list = _capnamelist;
            _capnamelist = new List<string>();
            num3 = (int)_capnames[list[0]];
        }
        for (int j = 0; j < _capcount; j++)
        {
            int num4 = ((_capnumlist == null) ? j : _capnumlist[j]);
            if (num3 == num4)
            {
                _capnamelist.Add(list[num2++]);
                num3 = ((num2 == list.Count) ? (-1) : ((int)_capnames[list[num2]]));
            }
            else
            {
                string text = num4.ToString(_culture);
                _capnamelist.Add(text);
                _capnames[text] = num4;
            }
        }
    }
References System.Text.RegularExpressions.RegexParser._autocap, System.Text.RegularExpressions.RegexParser._capcount, System.Text.RegularExpressions.RegexParser._capnamelist, System.Text.RegularExpressions.RegexParser._capnames, System.Text.RegularExpressions.RegexParser._capnumlist, System.Text.RegularExpressions.RegexParser._caps, System.Text.RegularExpressions.RegexParser._captop, System.Text.RegularExpressions.RegexParser._culture, System.Collections.Generic.List< T >.Add(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Collections.Generic.List< T >.Count, System.Collections.Hashtable.GetEnumerator(), System.Text.RegularExpressions.i, System.Text.RegularExpressions.RegexParser.IsCaptureSlot(), System.key, System.list, System.Text.RegularExpressions.RegexParser.NoteCaptureSlot(), System.Array.Sort(), and System.text.
Referenced by System.Text.RegularExpressions.RegexParser.CountCaptures().