Terraria: System.Text.RegularExpressions.RegexParser.ScanGroupOpen
ScanGroupOpen()
RegexNode System.Text.RegularExpressions.RegexParser.ScanGroupOpen () inline private
Definition at line 663 of file RegexParser.cs.
    {
        if (CharsRight() == 0 || RightChar() != '?' || (RightChar() == '?' && CharsRight() > 1 && RightChar(1) == ')'))
        {
            if (UseOptionN() || _ignoreNextParen)
            {
                _ignoreNextParen = false;
                return new RegexNode(29, _options);
            }
            return new RegexNode(28, _options, _autocap++, -1);
        }
        MoveRight();
        if (CharsRight() != 0)
        {
            char c = '>';
            int type;
            switch (RightCharMoveRight())
            {
            case ':':
                type = 29;
                goto IL_0501;
            case '=':
                _options &= ~RegexOptions.RightToLeft;
                type = 30;
                goto IL_0501;
            case '!':
                _options &= ~RegexOptions.RightToLeft;
                type = 31;
                goto IL_0501;
            case '>':
                type = 32;
                goto IL_0501;
            case '\'':
                c = '\'';
                goto case '<';
            case '<':
            {
                if (CharsRight() == 0)
                {
                    break;
                }
                char c2;
                char c3 = (c2 = RightCharMoveRight());
                if (c3 != '!')
                {
                    if (c3 != '=')
                    {
                        MoveLeft();
                        int num = -1;
                        int num2 = -1;
                        bool flag = false;
                        if ((uint)(c2 - 48) <= 9u)
{
                            num = ScanDecimal();
                            if (!IsCaptureSlot(num))
{
                                num = -1;
                            }
                            if (CharsRight() > 0 && RightChar() != c && RightChar() != '-')
{
                                throw MakeException(RegexParseError.CaptureGroupNameInvalid, System.SR.CaptureGroupNameInvalid);
                            }
                            if (num == 0)
{
                                throw MakeException(RegexParseError.CaptureGroupOfZero, System.SR.CaptureGroupOfZero);
                            }
                        }
                        else if (RegexCharClass.IsWordChar(c2))
{
                            string capname = ScanCapname();
                            if (IsCaptureName(capname))
{
                                num = CaptureSlotFromName(capname);
                            }
                            if (CharsRight() > 0 && RightChar() != c && RightChar() != '-')
{
                                throw MakeException(RegexParseError.CaptureGroupNameInvalid, System.SR.CaptureGroupNameInvalid);
                            }
                        }
                        else
{
                            if (c2 != '-')
{
                                throw MakeException(RegexParseError.CaptureGroupNameInvalid, System.SR.CaptureGroupNameInvalid);
                            }
                            flag = true;
                        }
                        if ((num != -1 || flag) && CharsRight() > 1 && RightChar() == '-')
{
                            MoveRight();
                            c2 = RightChar();
                            if ((uint)(c2 - 48) <= 9u)
{
                                num2 = ScanDecimal();
                                if (!IsCaptureSlot(num2))
{
                                    throw MakeException(RegexParseError.UndefinedNumberedReference, System.SR.Format(System.SR.UndefinedNumberedReference, num2));
                                }
                                if (CharsRight() > 0 && RightChar() != c)
{
                                    throw MakeException(RegexParseError.CaptureGroupNameInvalid, System.SR.CaptureGroupNameInvalid);
                                }
                            }
                            else
{
                                if (!RegexCharClass.IsWordChar(c2))
{
                                    throw MakeException(RegexParseError.CaptureGroupNameInvalid, System.SR.CaptureGroupNameInvalid);
                                }
                                string text = ScanCapname();
                                if (!IsCaptureName(text))
{
                                    throw MakeException(RegexParseError.UndefinedNamedReference, System.SR.Format(System.SR.UndefinedNamedReference, text));
                                }
                                num2 = CaptureSlotFromName(text);
                                if (CharsRight() > 0 && RightChar() != c)
{
                                    throw MakeException(RegexParseError.CaptureGroupNameInvalid, System.SR.CaptureGroupNameInvalid);
                                }
                            }
                        }
                        if ((num != -1 || num2 != -1) && CharsRight() > 0 && RightCharMoveRight() == c)
{
                            return new RegexNode(28, _options, num, num2);
                        }
                        break;
                    }
                    if (c == '\'')
                    {
                        break;
                    }
                    _options |= RegexOptions.RightToLeft;
                    type = 30;
                }
                else
                {
                    if (c == '\'')
                    {
                        break;
                    }
                    _options |= RegexOptions.RightToLeft;
                    type = 31;
                }
                goto IL_0501;
            }
            case '(':
            {
                int num3 = Textpos();
                if (CharsRight() > 0)
                {
                    char c2 = RightChar();
                    if (c2 >= '0' && c2 <= '9')
                    {
                        int num4 = ScanDecimal();
                        if (CharsRight() > 0 && RightCharMoveRight() == ')')
{
                            if (IsCaptureSlot(num4))
{
                                return new RegexNode(33, _options, num4);
                            }
                            throw MakeException(RegexParseError.AlternationHasUndefinedReference, System.SR.Format(System.SR.AlternationHasUndefinedReference, num4.ToString()));
                        }
                        throw MakeException(RegexParseError.AlternationHasMalformedReference, System.SR.Format(System.SR.AlternationHasMalformedReference, num4.ToString()));
                    }
                    if (RegexCharClass.IsWordChar(c2))
                    {
                        string capname2 = ScanCapname();
                        if (IsCaptureName(capname2) && CharsRight() > 0 && RightCharMoveRight() == ')')
{
                            return new RegexNode(33, _options, CaptureSlotFromName(capname2));
                        }
                    }
                }
                type = 34;
                Textto(num3 - 1);
                _ignoreNextParen = true;
                int num5 = CharsRight();
                if (num5 >= 3 && RightChar(1) == '?')
                {
                    char c4 = RightChar(2);
                    switch (c4)
                    {
                    case '#':
                        throw MakeException(RegexParseError.AlternationHasComment, System.SR.AlternationHasComment);
                    case '\'':
                        throw MakeException(RegexParseError.AlternationHasNamedCapture, System.SR.AlternationHasNamedCapture);
                    }
                    if (num5 >= 4 && c4 == '<' && RightChar(3) != '!' && RightChar(3) != '=')
                    {
                        throw MakeException(RegexParseError.AlternationHasNamedCapture, System.SR.AlternationHasNamedCapture);
                    }
                }
                goto IL_0501;
            }
            default:
                {
                    MoveLeft();
                    type = 29;
                    if (_group.Type != 34)
                    {
                        ScanOptions();
                    }
                    if (CharsRight() == 0)
                    {
                        break;
                    }
                    char c2;
                    if ((c2 = RightCharMoveRight()) == ')')
                    {
                        return null;
                    }
                    if (c2 != ':')
                    {
                        break;
                    }
                    goto IL_0501;
                }
                IL_0501:
                return new RegexNode(type, _options);
            }
        }
        throw MakeException(RegexParseError.InvalidGroupingConstruct, System.SR.InvalidGroupingConstruct);
    }
References System.Text.RegularExpressions.RegexParser._autocap, System.Text.RegularExpressions.RegexParser._group, System.Text.RegularExpressions.RegexParser._ignoreNextParen, System.Text.RegularExpressions.RegexParser._options, System.SR.AlternationHasComment, System.SR.AlternationHasMalformedReference, System.SR.AlternationHasNamedCapture, System.SR.AlternationHasUndefinedReference, System.SR.CaptureGroupNameInvalid, System.SR.CaptureGroupOfZero, System.Text.RegularExpressions.RegexParser.CaptureSlotFromName(), System.Text.RegularExpressions.RegexParser.CharsRight(), System.SR.Format(), System.SR.InvalidGroupingConstruct, System.Text.RegularExpressions.RegexParser.IsCaptureName(), System.Text.RegularExpressions.RegexParser.IsCaptureSlot(), System.Text.RegularExpressions.RegexCharClass.IsWordChar(), System.Text.RegularExpressions.RegexParser.MakeException(), System.Text.RegularExpressions.RegexParser.MoveLeft(), System.Text.RegularExpressions.RegexParser.MoveRight(), System.Text.RegularExpressions.RegexParser.RightChar(), System.Text.RegularExpressions.RegexParser.RightCharMoveRight(), System.Text.RegularExpressions.RegexParser.ScanCapname(), System.Text.RegularExpressions.RegexParser.ScanDecimal(), System.Text.RegularExpressions.RegexParser.ScanOptions(), System.text, System.Text.RegularExpressions.RegexParser.Textpos(), System.Text.RegularExpressions.RegexParser.Textto(), System.type, System.Text.RegularExpressions.RegexNode.Type, System.SR.UndefinedNamedReference, System.SR.UndefinedNumberedReference, and System.Text.RegularExpressions.RegexParser.UseOptionN().
Referenced by System.Text.RegularExpressions.RegexParser.ScanRegex().