Terraria: System.Text.RegularExpressions.RegexParser.ScanBackslash
ScanBackslash()
RegexNode System.Text.RegularExpressions.RegexParser.ScanBackslash (bool scanOnly) inline private
Definition at line 946 of file RegexParser.cs.
    {
        char c;
        switch (c = RightChar())
        {
        case 'A':
        case 'B':
        case 'G':
        case 'Z':
        case 'b':
        case 'z':
            MoveRight();
            if (!scanOnly)
            {
                return new RegexNode(TypeFromCode(c), _options);
            }
            return null;
        case 'w':
            MoveRight();
            if (!scanOnly)
            {
                return new RegexNode(11, _options, UseOptionE() ? "\0\n\00:A[_`a{İı" : "\0\0\n\0\u0002\u0004\u0005\u0003\u0001\u0006\t\u0013\0");
            }
            return null;
        case 'W':
            MoveRight();
            if (!scanOnly)
            {
                return new RegexNode(11, _options, UseOptionE() ? "\u0001\n\00:A[_`a{İı" : "\u0001\0\n\0\u0002\u0004\u0005\u0003\u0001\u0006\t\u0013\0");
            }
            return null;
        case 's':
            MoveRight();
            if (!scanOnly)
            {
                return new RegexNode(11, _options, UseOptionE() ? "\0\u0004\0\t\u000e !" : "\0\0\u0001d");
            }
            return null;
        case 'S':
            MoveRight();
            if (!scanOnly)
            {
                return new RegexNode(11, _options, UseOptionE() ? "\u0001\u0004\0\t\u000e !" : "\u0001\0\u0001d");
            }
            return null;
        case 'd':
            MoveRight();
            if (!scanOnly)
            {
                return new RegexNode(11, _options, UseOptionE() ? "\0\u0002\00:" : "\0\0\u0001\t");
            }
            return null;
        case 'D':
            MoveRight();
            if (!scanOnly)
            {
                return new RegexNode(11, _options, UseOptionE() ? "\u0001\u0002\00:" : "\0\0\u0001\ufff7");
            }
            return null;
        case 'P':
        case 'p':
        {
            MoveRight();
            if (scanOnly)
            {
                return null;
            }
            RegexCharClass regexCharClass = new RegexCharClass();
            regexCharClass.AddCategoryFromName(ParseProperty(), c != 'p', UseOptionI(), _pattern, _currentPos);
            if (UseOptionI())
            {
                regexCharClass.AddLowercase(_culture);
            }
            return new RegexNode(11, _options, regexCharClass.ToStringClass());
        }
        default:
            return ScanBasicBackslash(scanOnly);
        }
    }
References System.Text.RegularExpressions.RegexParser._culture, System.Text.RegularExpressions.RegexParser._currentPos, System.Text.RegularExpressions.RegexParser._options, System.Text.RegularExpressions.RegexParser._pattern, System.Text.RegularExpressions.RegexParser.MoveRight(), System.Text.RegularExpressions.RegexParser.ParseProperty(), System.Text.RegularExpressions.RegexParser.RightChar(), System.Text.RegularExpressions.RegexParser.ScanBasicBackslash(), System.Text.RegularExpressions.RegexParser.TypeFromCode(), System.Text.RegularExpressions.RegexParser.UseOptionE(), and System.Text.RegularExpressions.RegexParser.UseOptionI().
Referenced by System.Text.RegularExpressions.RegexParser.CountCaptures(), and System.Text.RegularExpressions.RegexParser.ScanRegex().