Terraria: System.Text.RegularExpressions.RegexParser.ScanCapname
ScanCapname()
string System.Text.RegularExpressions.RegexParser.ScanCapname () inline private
Definition at line 1261 of file RegexParser.cs.
    {
        int num = Textpos();
        while (CharsRight() > 0)
        {
            if (!RegexCharClass.IsWordChar(RightCharMoveRight()))
            {
                MoveLeft();
                break;
            }
        }
        return _pattern.Substring(num, Textpos() - num);
    }
References System.Text.RegularExpressions.RegexParser._pattern, System.Text.RegularExpressions.RegexParser.CharsRight(), System.Text.RegularExpressions.RegexCharClass.IsWordChar(), System.Text.RegularExpressions.RegexParser.MoveLeft(), System.Text.RegularExpressions.RegexParser.RightCharMoveRight(), and System.Text.RegularExpressions.RegexParser.Textpos().
Referenced by System.Text.RegularExpressions.RegexParser.CountCaptures(), System.Text.RegularExpressions.RegexParser.ScanBasicBackslash(), System.Text.RegularExpressions.RegexParser.ScanDollar(), and System.Text.RegularExpressions.RegexParser.ScanGroupOpen().