Terraria: System.Text.RegularExpressions.RegexParser.ScanDollar
ScanDollar()
RegexNode System.Text.RegularExpressions.RegexParser.ScanDollar () inline private
Definition at line 1157 of file RegexParser.cs.
    {
        if (CharsRight() == 0)
        {
            return new RegexNode(9, _options, '$');
        }
        char c = RightChar();
        int num = Textpos();
        int pos = num;
        bool flag;
        if (c == '{' && CharsRight() > 1)
        {
            flag = true;
            MoveRight();
            c = RightChar();
        }
        else
        {
            flag = false;
        }
        if (c >= '0' && c <= '9')
        {
            if (!flag && UseOptionE())
            {
                int num2 = -1;
                int num3 = c - 48;
                MoveRight();
                if (IsCaptureSlot(num3))
                {
                    num2 = num3;
                    pos = Textpos();
                }
                while (CharsRight() > 0 && (c = RightChar()) >= '0' && c <= '9')
                {
                    int num4 = c - 48;
                    if (num3 > 214748364 || (num3 == 214748364 && num4 > 7))
                    {
                        throw MakeException(RegexParseError.QuantifierOrCaptureGroupOutOfRange, System.SR.QuantifierOrCaptureGroupOutOfRange);
                    }
                    num3 = num3 * 10 + num4;
                    MoveRight();
                    if (IsCaptureSlot(num3))
                    {
                        num2 = num3;
                        pos = Textpos();
                    }
                }
                Textto(pos);
                if (num2 >= 0)
                {
                    return new RegexNode(13, _options, num2);
                }
            }
            else
            {
                int num5 = ScanDecimal();
                if ((!flag || (CharsRight() > 0 && RightCharMoveRight() == '}')) && IsCaptureSlot(num5))
                {
                    return new RegexNode(13, _options, num5);
                }
            }
        }
        else if (flag && RegexCharClass.IsWordChar(c))
        {
            string capname = ScanCapname();
            if (CharsRight() > 0 && RightCharMoveRight() == '}' && IsCaptureName(capname))
            {
                return new RegexNode(13, _options, CaptureSlotFromName(capname));
            }
        }
        else if (!flag)
        {
            int num6 = 1;
            switch (c)
            {
            case '$':
                MoveRight();
                return new RegexNode(9, _options, '$');
            case '&':
                num6 = 0;
                break;
            case '`':
                num6 = -1;
                break;
            case '\'':
                num6 = -2;
                break;
            case '+':
                num6 = -3;
                break;
            case '_':
                num6 = -4;
                break;
            }
            if (num6 != 1)
            {
                MoveRight();
                return new RegexNode(13, _options, num6);
            }
        }
        Textto(num);
        return new RegexNode(9, _options, '$');
    }
References System.Text.RegularExpressions.RegexParser._options, System.Text.RegularExpressions.RegexParser.CaptureSlotFromName(), System.Text.RegularExpressions.RegexParser.CharsRight(), System.Text.RegularExpressions.RegexParser.IsCaptureName(), System.Text.RegularExpressions.RegexParser.IsCaptureSlot(), System.Text.RegularExpressions.RegexCharClass.IsWordChar(), System.Text.RegularExpressions.RegexParser.MakeException(), System.Text.RegularExpressions.RegexParser.MoveRight(), System.SR.QuantifierOrCaptureGroupOutOfRange, System.Text.RegularExpressions.RegexParser.RightChar(), System.Text.RegularExpressions.RegexParser.RightCharMoveRight(), System.Text.RegularExpressions.RegexParser.ScanCapname(), System.Text.RegularExpressions.RegexParser.ScanDecimal(), System.Text.RegularExpressions.RegexParser.Textpos(), System.Text.RegularExpressions.RegexParser.Textto(), and System.Text.RegularExpressions.RegexParser.UseOptionE().
Referenced by System.Text.RegularExpressions.RegexParser.ScanReplacement().