Terraria: System.Text.RegularExpressions.RegexParser.PopGroup
PopGroup()
void System.Text.RegularExpressions.RegexParser.PopGroup () inline private
Definition at line 1876 of file RegexParser.cs.
    {
        _concatenation = _stack;
        _alternation = _concatenation.Next;
        _group = _alternation.Next;
        _stack = _group.Next;
        if (_group.Type == 34 && _group.ChildCount() == 0)
        {
            if (_unit == null)
            {
                throw MakeException(RegexParseError.AlternationHasMalformedCondition, System.SR.AlternationHasMalformedCondition);
            }
            _group.AddChild(_unit);
            _unit = null;
        }
    }
References System.Text.RegularExpressions.RegexParser._alternation, System.Text.RegularExpressions.RegexParser._concatenation, System.Text.RegularExpressions.RegexParser._group, System.Text.RegularExpressions.RegexParser._stack, System.Text.RegularExpressions.RegexParser._unit, System.Text.RegularExpressions.RegexNode.AddChild(), System.SR.AlternationHasMalformedCondition, System.Text.RegularExpressions.RegexNode.ChildCount(), System.Text.RegularExpressions.RegexParser.MakeException(), System.Text.RegularExpressions.RegexNode.Next, and System.Text.RegularExpressions.RegexNode.Type.
Referenced by System.Text.RegularExpressions.RegexParser.ScanRegex().