Terraria: System.Text.RegularExpressions.RegexParser.ParseProperty
ParseProperty()
string System.Text.RegularExpressions.RegexParser.ParseProperty () inline private
Definition at line 1455 of file RegexParser.cs.
    {
        if (CharsRight() < 3)
        {
            throw MakeException(RegexParseError.InvalidUnicodePropertyEscape, System.SR.InvalidUnicodePropertyEscape);
        }
        char c = RightCharMoveRight();
        if (c != '{')
        {
            throw MakeException(RegexParseError.MalformedUnicodePropertyEscape, System.SR.MalformedUnicodePropertyEscape);
        }
        int num = Textpos();
        while (CharsRight() > 0)
        {
            c = RightCharMoveRight();
            if (!RegexCharClass.IsWordChar(c) && c != '-')
            {
                MoveLeft();
                break;
            }
        }
        string result = _pattern.Substring(num, Textpos() - num);
        if (CharsRight() == 0 || RightCharMoveRight() != '}')
        {
            throw MakeException(RegexParseError.InvalidUnicodePropertyEscape, System.SR.InvalidUnicodePropertyEscape);
        }
        return result;
    }
References System.Text.RegularExpressions.RegexParser._pattern, System.Text.RegularExpressions.RegexParser.CharsRight(), System.SR.InvalidUnicodePropertyEscape, System.Text.RegularExpressions.RegexCharClass.IsWordChar(), System.Text.RegularExpressions.RegexParser.MakeException(), System.SR.MalformedUnicodePropertyEscape, System.Text.RegularExpressions.RegexParser.MoveLeft(), System.Text.RegularExpressions.RegexParser.RightCharMoveRight(), and System.Text.RegularExpressions.RegexParser.Textpos().
Referenced by System.Text.RegularExpressions.RegexParser.ScanBackslash(), and System.Text.RegularExpressions.RegexParser.ScanCharClass().