Terraria: System.Text.RegularExpressions.RegexParser.NoteCaptureSlot
NoteCaptureSlot()
void System.Text.RegularExpressions.RegexParser.NoteCaptureSlot (int i, int pos) inline private
Definition at line 1606 of file RegexParser.cs.
    {
        object key = i;
        if (!_caps.ContainsKey(key))
        {
            _caps.Add(key, pos);
            _capcount++;
            if (_captop <= i)
            {
                _captop = ((i == int.MaxValue) ? i : (i + 1));
            }
        }
    }
References System.Text.RegularExpressions.RegexParser._capcount, System.Text.RegularExpressions.RegexParser._caps, System.Text.RegularExpressions.RegexParser._captop, System.Collections.Hashtable.Add(), System.Collections.Hashtable.ContainsKey(), System.Text.RegularExpressions.i, and System.key.
Referenced by System.Text.RegularExpressions.RegexParser.AssignNameSlots(), and System.Text.RegularExpressions.RegexParser.CountCaptures().