Terraria: System.Text.RegularExpressions.RegexParser.AddAlternate
AddAlternate()
void System.Text.RegularExpressions.RegexParser.AddAlternate () inline private
Definition at line 1905 of file RegexParser.cs.
    {
        if (_group.Type == 34 || _group.Type == 33)
        {
            _group.AddChild(_concatenation.ReverseLeft());
        }
        else
        {
            _alternation.AddChild(_concatenation.ReverseLeft());
        }
        _concatenation = new RegexNode(25, _options);
    }
References System.Text.RegularExpressions.RegexParser._alternation, System.Text.RegularExpressions.RegexParser._concatenation, System.Text.RegularExpressions.RegexParser._group, System.Text.RegularExpressions.RegexParser._options, System.Text.RegularExpressions.RegexNode.AddChild(), System.Text.RegularExpressions.RegexNode.ReverseLeft(), and System.Text.RegularExpressions.RegexNode.Type.
Referenced by System.Text.RegularExpressions.RegexParser.ScanRegex().