Terraria: System.Text.RegularExpressions.RegexParser.IsCaptureName
IsCaptureName()
bool System.Text.RegularExpressions.RegexParser.IsCaptureName (string capname) inline private
Definition at line 1717 of file RegexParser.cs.
    {
        if (_capnames != null)
        {
            return _capnames.ContainsKey(capname);
        }
        return false;
    }
References System.Text.RegularExpressions.RegexParser._capnames, and System.Collections.Hashtable.ContainsKey().
Referenced by System.Text.RegularExpressions.RegexParser.ScanBasicBackslash(), System.Text.RegularExpressions.RegexParser.ScanDollar(), and System.Text.RegularExpressions.RegexParser.ScanGroupOpen().