Terraria: System.Text.RegularExpressions.RegexParser.MakeException
MakeException()
RegexParseException System.Text.RegularExpressions.RegexParser.MakeException (RegexParseError error, string message) inline private
Definition at line 2006 of file RegexParser.cs.
    {
        return new RegexParseException(error, _currentPos, System.SR.Format(System.SR.MakeException, _pattern, _currentPos, message));
    }
References System.Text.RegularExpressions.RegexParser._currentPos, System.Text.RegularExpressions.RegexParser._pattern, System.SR.Format(), and System.SR.MakeException.
Referenced by System.Text.RegularExpressions.RegexParser.AddGroup(), System.Text.RegularExpressions.RegexParser.ParseProperty(), System.Text.RegularExpressions.RegexParser.PopGroup(), System.Text.RegularExpressions.RegexParser.ScanBasicBackslash(), System.Text.RegularExpressions.RegexParser.ScanBlank(), System.Text.RegularExpressions.RegexParser.ScanCharClass(), System.Text.RegularExpressions.RegexParser.ScanCharEscape(), System.Text.RegularExpressions.RegexParser.ScanControl(), System.Text.RegularExpressions.RegexParser.ScanDecimal(), System.Text.RegularExpressions.RegexParser.ScanDollar(), System.Text.RegularExpressions.RegexParser.ScanGroupOpen(), System.Text.RegularExpressions.RegexParser.ScanHex(), and System.Text.RegularExpressions.RegexParser.ScanRegex().