Terraria: System.Text.RegularExpressions.RegexParser.CharAt
CharAt()
char System.Text.RegularExpressions.RegexParser.CharAt (int i) inline private
Definition at line 2041 of file RegexParser.cs.
    {
        return _pattern[i];
    }
References System.Text.RegularExpressions.RegexParser._pattern, and System.Text.RegularExpressions.i.
Referenced by System.Text.RegularExpressions.RegexParser.IsTrueQuantifier(), System.Text.RegularExpressions.RegexParser.ScanCharClass(), and System.Text.RegularExpressions.RegexParser.ScanRegex().