Terraria: System.Text.RegularExpressions.RegexParser.ScanBasicBackslash
ScanBasicBackslash()
RegexNode System.Text.RegularExpressions.RegexParser.ScanBasicBackslash (bool scanOnly) inline private
Definition at line 1026 of file RegexParser.cs.
    {
        if (CharsRight() == 0)
        {
            throw MakeException(RegexParseError.UnescapedEndingBackslash, System.SR.UnescapedEndingBackslash);
        }
        int pos = Textpos();
        char c = '\0';
        bool flag = false;
        char c2 = RightChar();
        switch (c2)
        {
        case 'k':
            if (CharsRight() >= 2)
            {
                MoveRight();
                c2 = RightCharMoveRight();
                if (c2 == '<' || c2 == '\'')
                {
                    flag = true;
                    c = ((c2 == '\'') ? '\'' : '>');
                }
            }
            if (!flag || CharsRight() <= 0)
            {
                throw MakeException(RegexParseError.MalformedNamedReference, System.SR.MalformedNamedReference);
            }
            c2 = RightChar();
            break;
        case '\'':
        case '<':
            if (CharsRight() > 1)
            {
                flag = true;
                c = ((c2 == '\'') ? '\'' : '>');
                MoveRight();
                c2 = RightChar();
            }
            break;
        }
        if (flag && c2 >= '0' && c2 <= '9')
        {
            int num = ScanDecimal();
            if (CharsRight() > 0 && RightCharMoveRight() == c)
            {
                if (!scanOnly)
                {
                    if (!IsCaptureSlot(num))
                    {
                        throw MakeException(RegexParseError.UndefinedNumberedReference, System.SR.Format(System.SR.UndefinedNumberedReference, num.ToString()));
                    }
                    return new RegexNode(13, _options, num);
                }
                return null;
            }
        }
        else if (!flag && c2 >= '1' && c2 <= '9')
        {
            if (UseOptionE())
            {
                int num2 = -1;
                int num3 = c2 - 48;
                int num4 = Textpos() - 1;
                while (num3 <= _captop)
                {
                    if (IsCaptureSlot(num3) && (_caps == null || (int)_caps[num3] < num4))
                    {
                        num2 = num3;
                    }
                    MoveRight();
                    if (CharsRight() == 0 || (c2 = RightChar()) < '0' || c2 > '9')
                    {
                        break;
                    }
                    num3 = num3 * 10 + (c2 - 48);
                }
                if (num2 >= 0)
                {
                    if (!scanOnly)
                    {
                        return new RegexNode(13, _options, num2);
                    }
                    return null;
                }
            }
            else
            {
                int num5 = ScanDecimal();
                if (scanOnly)
                {
                    return null;
                }
                if (IsCaptureSlot(num5))
                {
                    return new RegexNode(13, _options, num5);
                }
                if (num5 <= 9)
                {
                    throw MakeException(RegexParseError.UndefinedNumberedReference, System.SR.Format(System.SR.UndefinedNumberedReference, num5.ToString()));
                }
            }
        }
        else if (flag && RegexCharClass.IsWordChar(c2))
        {
            string text = ScanCapname();
            if (CharsRight() > 0 && RightCharMoveRight() == c)
            {
                if (!scanOnly)
                {
                    if (!IsCaptureName(text))
                    {
                        throw MakeException(RegexParseError.UndefinedNamedReference, System.SR.Format(System.SR.UndefinedNamedReference, text));
                    }
                    return new RegexNode(13, _options, CaptureSlotFromName(text));
                }
                return null;
            }
        }
        Textto(pos);
        c2 = ScanCharEscape();
        if (UseOptionI())
        {
            c2 = _culture.TextInfo.ToLower(c2);
        }
        if (!scanOnly)
        {
            return new RegexNode(9, _options, c2);
        }
        return null;
    }
References System.Text.RegularExpressions.RegexParser._caps, System.Text.RegularExpressions.RegexParser._captop, System.Text.RegularExpressions.RegexParser._culture, System.Text.RegularExpressions.RegexParser._options, System.Text.RegularExpressions.RegexParser.CaptureSlotFromName(), System.Text.RegularExpressions.RegexParser.CharsRight(), System.SR.Format(), System.Text.RegularExpressions.RegexParser.IsCaptureName(), System.Text.RegularExpressions.RegexParser.IsCaptureSlot(), System.Text.RegularExpressions.RegexCharClass.IsWordChar(), System.Text.RegularExpressions.RegexParser.MakeException(), System.SR.MalformedNamedReference, System.Text.RegularExpressions.RegexParser.MoveRight(), System.Text.RegularExpressions.RegexParser.RightChar(), System.Text.RegularExpressions.RegexParser.RightCharMoveRight(), System.Text.RegularExpressions.RegexParser.ScanCapname(), System.Text.RegularExpressions.RegexParser.ScanCharEscape(), System.Text.RegularExpressions.RegexParser.ScanDecimal(), System.text, System.Globalization.CultureInfo.TextInfo, System.Text.RegularExpressions.RegexParser.Textpos(), System.Text.RegularExpressions.RegexParser.Textto(), System.SR.UndefinedNamedReference, System.SR.UndefinedNumberedReference, System.SR.UnescapedEndingBackslash, System.Text.RegularExpressions.RegexParser.UseOptionE(), and System.Text.RegularExpressions.RegexParser.UseOptionI().
Referenced by System.Text.RegularExpressions.RegexParser.ScanBackslash().