Terraria: System.Text.RegularExpressions.RegexParser.ScanControl
ScanControl()
char System.Text.RegularExpressions.RegexParser.ScanControl () inline private
Definition at line 1351 of file RegexParser.cs.
    {
        if (CharsRight() == 0)
        {
            throw MakeException(RegexParseError.MissingControlCharacter, System.SR.MissingControlCharacter);
        }
        char c = RightCharMoveRight();
        if ((uint)(c - 97) <= 25u)
        {
            c = (char)(c - 32);
        }
        if ((c = (char)(c - 64)) < ' ')
        {
            return c;
        }
        throw MakeException(RegexParseError.UnrecognizedControlCharacter, System.SR.UnrecognizedControlCharacter);
    }
References System.Text.RegularExpressions.RegexParser.CharsRight(), System.Text.RegularExpressions.RegexParser.MakeException(), System.SR.MissingControlCharacter, System.Text.RegularExpressions.RegexParser.RightCharMoveRight(), and System.SR.UnrecognizedControlCharacter.
Referenced by System.Text.RegularExpressions.RegexParser.ScanCharEscape().