Terraria: System.Text.RegularExpressions.RegexParser.RegexParser
RegexParser() [1/2]
System.Text.RegularExpressions.RegexParser.RegexParser (string pattern, RegexOptions options, CultureInfo culture, Hashtable caps, int capsize, Hashtable capnames, Span< int > optionSpan) inline private
Definition at line 64 of file RegexParser.cs.
    {
        _pattern = pattern;
        _options = options;
        _culture = culture;
        _caps = caps;
        _capsize = capsize;
        _capnames = capnames;
        _optionsStack = new System.Collections.Generic.ValueListBuilder<int>(optionSpan);
        _stack = null;
        _group = null;
        _alternation = null;
        _concatenation = null;
        _unit = null;
        _currentPos = 0;
        _autocap = 0;
        _capcount = 0;
        _captop = 0;
        _capnumlist = null;
        _capnamelist = null;
        _ignoreNextParen = false;
    }
References System.Text.RegularExpressions.RegexParser._alternation, System.Text.RegularExpressions.RegexParser._autocap, System.Text.RegularExpressions.RegexParser._capcount, System.Text.RegularExpressions.RegexParser._capnamelist, System.Text.RegularExpressions.RegexParser._capnames, System.Text.RegularExpressions.RegexParser._capnumlist, System.Text.RegularExpressions.RegexParser._caps, System.Text.RegularExpressions.RegexParser._capsize, System.Text.RegularExpressions.RegexParser._captop, System.Text.RegularExpressions.RegexParser._concatenation, System.Text.RegularExpressions.RegexParser._culture, System.Text.RegularExpressions.RegexParser._currentPos, System.Text.RegularExpressions.RegexParser._group, System.Text.RegularExpressions.RegexParser._ignoreNextParen, System.Text.RegularExpressions.RegexParser._options, System.Text.RegularExpressions.RegexParser._optionsStack, System.Text.RegularExpressions.RegexParser._pattern, System.Text.RegularExpressions.RegexParser._stack, System.Text.RegularExpressions.RegexParser._unit, System.culture, System.Text.RegularExpressions.options, and System.Text.RegularExpressions.pattern.
Referenced by System.Text.RegularExpressions.RegexParser.Parse(), System.Text.RegularExpressions.RegexParser.ParseReplacement(), and System.Text.RegularExpressions.RegexParser.UnescapeImpl().