Terraria: System.Text.RegularExpressions.RegexParser.ScanCharEscape
ScanCharEscape()
char System.Text.RegularExpressions.RegexParser.ScanCharEscape () inline private
Definition at line 1414 of file RegexParser.cs.
    {
        char c = RightCharMoveRight();
        if (c >= '0' && c <= '7')
        {
            MoveLeft();
            return ScanOctal();
        }
        switch (c)
        {
        case 'x':
            return ScanHex(2);
        case 'u':
            return ScanHex(4);
        case 'a':
            return '\a';
        case 'b':
            return '\b';
        case 'e':
            return '\u001b';
        case 'f':
            return '\f';
        case 'n':
            return '\n';
        case 'r':
            return '\r';
        case 't':
            return '\t';
        case 'v':
            return '\v';
        case 'c':
            return ScanControl();
        default:
            if (!UseOptionE() && RegexCharClass.IsWordChar(c))
            {
                throw MakeException(RegexParseError.UnrecognizedEscape, System.SR.Format(System.SR.UnrecognizedEscape, c));
            }
            return c;
        }
    }
References System.SR.Format(), System.Text.RegularExpressions.RegexCharClass.IsWordChar(), System.Text.RegularExpressions.RegexParser.MakeException(), System.Text.RegularExpressions.RegexParser.MoveLeft(), System.Text.RegularExpressions.RegexParser.RightCharMoveRight(), System.Text.RegularExpressions.RegexParser.ScanControl(), System.Text.RegularExpressions.RegexParser.ScanHex(), System.Text.RegularExpressions.RegexParser.ScanOctal(), System.SR.UnrecognizedEscape, and System.Text.RegularExpressions.RegexParser.UseOptionE().
Referenced by System.Text.RegularExpressions.RegexParser.ScanBasicBackslash(), and System.Text.RegularExpressions.RegexParser.ScanCharClass().