Terraria: System.Text.RegularExpressions.RegexParser.IsCaptureSlot
IsCaptureSlot()
bool System.Text.RegularExpressions.RegexParser.IsCaptureSlot (int i) inline private
Definition at line 1704 of file RegexParser.cs.
    {
        if (_caps != null)
        {
            return _caps.ContainsKey(i);
        }
        if (i >= 0)
        {
            return i < _capsize;
        }
        return false;
    }
References System.Text.RegularExpressions.RegexParser._caps, System.Text.RegularExpressions.RegexParser._capsize, System.Collections.Hashtable.ContainsKey(), and System.Text.RegularExpressions.i.
Referenced by System.Text.RegularExpressions.RegexParser.AssignNameSlots(), System.Text.RegularExpressions.RegexParser.ScanBasicBackslash(), System.Text.RegularExpressions.RegexParser.ScanDollar(), and System.Text.RegularExpressions.RegexParser.ScanGroupOpen().