Terraria: System.Text.RegularExpressions.RegexParser.ScanBlank
ScanBlank()
void System.Text.RegularExpressions.RegexParser.ScanBlank () inline private
Definition at line 887 of file RegexParser.cs.
    {
        if (UseOptionX())
        {
            while (true)
            {
                if (CharsRight() > 0 && IsSpace(RightChar()))
                {
                    MoveRight();
                    continue;
                }
                if (CharsRight() == 0)
                {
                    break;
                }
                if (RightChar() == '#')
                {
                    while (CharsRight() > 0 && RightChar() != '\n')
                    {
                        MoveRight();
                    }
                    continue;
                }
                if (CharsRight() >= 3 && RightChar(2) == '#' && RightChar(1) == '?' && RightChar() == '(')
                {
                    while (CharsRight() > 0 && RightChar() != ')')
                    {
                        MoveRight();
                    }
                    if (CharsRight() == 0)
                    {
                        throw MakeException(RegexParseError.UnterminatedComment, System.SR.UnterminatedComment);
                    }
                    MoveRight();
                    continue;
                }
                break;
            }
            return;
        }
        while (true)
        {
            if (CharsRight() < 3 || RightChar(2) != '#' || RightChar(1) != '?' || RightChar() != '(')
            {
                return;
            }
            while (CharsRight() > 0 && RightChar() != ')')
            {
                MoveRight();
            }
            if (CharsRight() == 0)
            {
                break;
            }
            MoveRight();
        }
        throw MakeException(RegexParseError.UnterminatedComment, System.SR.UnterminatedComment);
    }
References System.Text.RegularExpressions.RegexParser.CharsRight(), System.Text.RegularExpressions.RegexParser.IsSpace(), System.Text.RegularExpressions.RegexParser.MakeException(), System.Text.RegularExpressions.RegexParser.MoveRight(), System.Text.RegularExpressions.RegexParser.RightChar(), System.SR.UnterminatedComment, and System.Text.RegularExpressions.RegexParser.UseOptionX().
Referenced by System.Text.RegularExpressions.RegexParser.CountCaptures(), and System.Text.RegularExpressions.RegexParser.ScanRegex().