Terraria: System.Text.RegularExpressions.RegexParser.IsTrueQuantifier
IsTrueQuantifier()
bool System.Text.RegularExpressions.RegexParser.IsTrueQuantifier () inline private
Definition at line 1783 of file RegexParser.cs.
    {
        int num = Textpos();
        char c = CharAt(num);
        if (c != '{')
        {
            if (c <= '{')
            {
                return Category[c] >= 5;
            }
            return false;
        }
        int num2 = num;
        int num3 = CharsRight();
        while (--num3 > 0 && (uint)((c = CharAt(++num2)) - 48) <= 9u)
        {
        }
        if (num3 == 0 || num2 - num == 1)
        {
            return false;
        }
        switch (c)
        {
        case '}':
            return true;
        default:
            return false;
        case ',':
            break;
        }
        while (--num3 > 0 && (uint)((c = CharAt(++num2)) - 48) <= 9u)
        {
        }
        if (num3 > 0)
        {
            return c == '}';
        }
        return false;
    }
References System.Text.RegularExpressions.RegexParser.Category, System.Text.RegularExpressions.RegexParser.CharAt(), System.Text.RegularExpressions.RegexParser.CharsRight(), and System.Text.RegularExpressions.RegexParser.Textpos().
Referenced by System.Text.RegularExpressions.RegexParser.ScanRegex().