Terraria: System.Text.RegularExpressions.RegexParser.AddGroup
AddGroup()
void System.Text.RegularExpressions.RegexParser.AddGroup () inline private
Definition at line 1968 of file RegexParser.cs.
    {
        if (_group.Type == 34 || _group.Type == 33)
        {
            _group.AddChild(_concatenation.ReverseLeft());
            if ((_group.Type == 33 && _group.ChildCount() > 2) || _group.ChildCount() > 3)
            {
                throw MakeException(RegexParseError.AlternationHasTooManyConditions, System.SR.AlternationHasTooManyConditions);
            }
        }
        else
        {
            _alternation.AddChild(_concatenation.ReverseLeft());
            _group.AddChild(_alternation);
        }
        _unit = _group;
    }
References System.Text.RegularExpressions.RegexParser._alternation, System.Text.RegularExpressions.RegexParser._concatenation, System.Text.RegularExpressions.RegexParser._group, System.Text.RegularExpressions.RegexParser._unit, System.Text.RegularExpressions.RegexNode.AddChild(), System.SR.AlternationHasTooManyConditions, System.Text.RegularExpressions.RegexNode.ChildCount(), System.Text.RegularExpressions.RegexParser.MakeException(), System.Text.RegularExpressions.RegexNode.ReverseLeft(), and System.Text.RegularExpressions.RegexNode.Type.
Referenced by System.Text.RegularExpressions.RegexParser.ScanRegex().