Terraria: System.Text.RegularExpressions.RegexParser.ScanOptions
ScanOptions()
void System.Text.RegularExpressions.RegexParser.ScanOptions () inline private
Definition at line 1378 of file RegexParser.cs.
    {
        bool flag = false;
        while (CharsRight() > 0)
        {
            char c = RightChar();
            switch (c)
            {
            case '-':
                flag = true;
                break;
            case '+':
                flag = false;
                break;
            default:
            {
                RegexOptions regexOptions = OptionFromCode(c);
                if (regexOptions == RegexOptions.None || IsOnlyTopOption(regexOptions))
                {
                    return;
                }
                if (flag)
                {
                    _options &= ~regexOptions;
                }
                else
                {
                    _options |= regexOptions;
                }
                break;
            }
            }
            MoveRight();
        }
    }
References System.Text.RegularExpressions.RegexParser._options, System.Text.RegularExpressions.RegexParser.CharsRight(), System.Text.RegularExpressions.RegexParser.IsOnlyTopOption(), System.Text.RegularExpressions.RegexParser.MoveRight(), System.Text.RegularExpressions.RegexParser.OptionFromCode(), and System.Text.RegularExpressions.RegexParser.RightChar().
Referenced by System.Text.RegularExpressions.RegexParser.CountCaptures(), and System.Text.RegularExpressions.RegexParser.ScanGroupOpen().