Terraria: System.Text.RegularExpressions.RegexParser.NoteCaptureName
NoteCaptureName()
void System.Text.RegularExpressions.RegexParser.NoteCaptureName (string name, int pos) inline private
Definition at line 1620 of file RegexParser.cs.
    {
        if (_capnames == null)
        {
            _capnames = new Hashtable();
            _capnamelist = new List<string>();
        }
        if (!_capnames.ContainsKey(name))
        {
            _capnames.Add(name, pos);
            _capnamelist.Add(name);
        }
    }
References System.Text.RegularExpressions.RegexParser._capnamelist, System.Text.RegularExpressions.RegexParser._capnames, System.Collections.Hashtable.Add(), System.Collections.Generic.List< T >.Add(), System.Collections.Hashtable.ContainsKey(), and System.Text.RegularExpressions.name.
Referenced by System.Text.RegularExpressions.RegexParser.CountCaptures().