Terraria: System.Text.RegularExpressions.RegexParser.ScanOctal
ScanOctal()
char System.Text.RegularExpressions.RegexParser.ScanOctal () inline private
Definition at line 1275 of file RegexParser.cs.
    {
        int num = 3;
        if (num > CharsRight())
        {
            num = CharsRight();
        }
        int num2 = 0;
        int num3;
        while (num > 0 && (uint)(num3 = RightChar() - 48) <= 7u)
        {
            MoveRight();
            num2 = num2 * 8 + num3;
            if (UseOptionE() && num2 >= 32)
            {
                break;
            }
            num--;
        }
        num2 &= 0xFF;
        return (char)num2;
    }
References System.Text.RegularExpressions.RegexParser.CharsRight(), System.Text.RegularExpressions.RegexParser.MoveRight(), System.Text.RegularExpressions.RegexParser.RightChar(), and System.Text.RegularExpressions.RegexParser.UseOptionE().
Referenced by System.Text.RegularExpressions.RegexParser.ScanCharEscape().