Terraria: System.Text.RegularExpressions.RegexParser.ScanCharClass
ScanCharClass()
RegexCharClass System.Text.RegularExpressions.RegexParser.ScanCharClass (bool caseInsensitive, bool scanOnly) inline private
Definition at line 481 of file RegexParser.cs.
    {
        char c = '\0';
        char c2 = '\0';
        bool flag = false;
        bool flag2 = true;
        bool flag3 = false;
        RegexCharClass regexCharClass = (scanOnly ? null : new RegexCharClass());
        if (CharsRight() > 0 && RightChar() == '^')
        {
            MoveRight();
            if (!scanOnly)
            {
                regexCharClass.Negate = true;
            }
            if ((_options & RegexOptions.ECMAScript) != 0 && CharAt(_currentPos) == ']')
            {
                flag2 = false;
            }
        }
        for (; CharsRight() > 0; flag2 = false)
        {
            bool flag4 = false;
            c = RightCharMoveRight();
            if (c == ']')
            {
                if (!flag2)
                {
                    flag3 = true;
                    break;
                }
            }
            else if (c == '\\' && CharsRight() > 0)
            {
                switch (c = RightCharMoveRight())
                {
                case 'D':
                case 'd':
                    if (!scanOnly)
                    {
                        if (flag)
{
                            throw MakeException(RegexParseError.ShorthandClassInCharacterRange, System.SR.Format(System.SR.ShorthandClassInCharacterRange, c));
                        }
                        regexCharClass.AddDigit(UseOptionE(), c == 'D', _pattern, _currentPos);
                    }
                    continue;
                case 'S':
                case 's':
                    if (!scanOnly)
                    {
                        if (flag)
{
                            throw MakeException(RegexParseError.ShorthandClassInCharacterRange, System.SR.Format(System.SR.ShorthandClassInCharacterRange, c));
                        }
                        regexCharClass.AddSpace(UseOptionE(), c == 'S');
                    }
                    continue;
                case 'W':
                case 'w':
                    if (!scanOnly)
                    {
                        if (flag)
{
                            throw MakeException(RegexParseError.ShorthandClassInCharacterRange, System.SR.Format(System.SR.ShorthandClassInCharacterRange, c));
                        }
                        regexCharClass.AddWord(UseOptionE(), c == 'W');
                    }
                    continue;
                case 'P':
                case 'p':
                    if (!scanOnly)
                    {
                        if (flag)
{
                            throw MakeException(RegexParseError.ShorthandClassInCharacterRange, System.SR.Format(System.SR.ShorthandClassInCharacterRange, c));
                        }
                        regexCharClass.AddCategoryFromName(ParseProperty(), c != 'p', caseInsensitive, _pattern, _currentPos);
                    }
                    else
                    {
                        ParseProperty();
                    }
                    continue;
                case '-':
                    if (scanOnly)
                    {
                        continue;
                    }
                    if (flag)
                    {
                        if (c2 > c)
{
                            throw MakeException(RegexParseError.ReversedCharacterRange, System.SR.ReversedCharacterRange);
                        }
                        regexCharClass.AddRange(c2, c);
                        flag = false;
                        c2 = '\0';
                    }
                    else
                    {
                        regexCharClass.AddRange(c, c);
                    }
                    continue;
                }
                MoveLeft();
                c = ScanCharEscape();
                flag4 = true;
            }
            else if (c == '[' && CharsRight() > 0 && RightChar() == ':' && !flag)
            {
                int pos = Textpos();
                MoveRight();
                if (CharsRight() < 2 || RightCharMoveRight() != ':' || RightCharMoveRight() != ']')
                {
                    Textto(pos);
                }
            }
            if (flag)
            {
                flag = false;
                if (scanOnly)
                {
                    continue;
                }
                if (c == '[' && !flag4 && !flag2)
                {
                    regexCharClass.AddChar(c2);
                    regexCharClass.AddSubtraction(ScanCharClass(caseInsensitive, scanOnly));
                    if (CharsRight() > 0 && RightChar() != ']')
                    {
                        throw MakeException(RegexParseError.ExclusionGroupNotLast, System.SR.ExclusionGroupNotLast);
                    }
                }
                else
                {
                    if (c2 > c)
                    {
                        throw MakeException(RegexParseError.ReversedCharacterRange, System.SR.ReversedCharacterRange);
                    }
                    regexCharClass.AddRange(c2, c);
                }
            }
            else if (CharsRight() >= 2 && RightChar() == '-' && RightChar(1) != ']')
            {
                c2 = c;
                flag = true;
                MoveRight();
            }
            else if (CharsRight() >= 1 && c == '-' && !flag4 && RightChar() == '[' && !flag2)
            {
                if (!scanOnly)
                {
                    MoveRight(1);
                    regexCharClass.AddSubtraction(ScanCharClass(caseInsensitive, scanOnly));
                    if (CharsRight() > 0 && RightChar() != ']')
                    {
                        throw MakeException(RegexParseError.ExclusionGroupNotLast, System.SR.ExclusionGroupNotLast);
                    }
                }
                else
                {
                    MoveRight(1);
                    ScanCharClass(caseInsensitive, scanOnly);
                }
            }
            else if (!scanOnly)
            {
                regexCharClass.AddRange(c, c);
            }
        }
        if (!flag3)
        {
            throw MakeException(RegexParseError.UnterminatedBracket, System.SR.UnterminatedBracket);
        }
        if (!scanOnly && caseInsensitive)
        {
            regexCharClass.AddLowercase(_culture);
        }
        return regexCharClass;
    }
References System.Text.RegularExpressions.RegexParser._culture, System.Text.RegularExpressions.RegexParser._currentPos, System.Text.RegularExpressions.RegexParser._options, System.Text.RegularExpressions.RegexParser._pattern, System.Collections.Generic.Dictionary< TKey, TValue >.AddRange(), System.Text.RegularExpressions.RegexParser.CharAt(), System.Text.RegularExpressions.RegexParser.CharsRight(), System.SR.ExclusionGroupNotLast, System.SR.Format(), System.Text.RegularExpressions.RegexParser.MakeException(), System.Text.RegularExpressions.RegexParser.MoveLeft(), System.Text.RegularExpressions.RegexParser.MoveRight(), System.Text.RegularExpressions.RegexParser.ParseProperty(), System.SR.ReversedCharacterRange, System.Text.RegularExpressions.RegexParser.RightChar(), System.Text.RegularExpressions.RegexParser.RightCharMoveRight(), System.Text.RegularExpressions.RegexParser.ScanCharClass(), System.Text.RegularExpressions.RegexParser.ScanCharEscape(), System.SR.ShorthandClassInCharacterRange, System.Text.RegularExpressions.RegexParser.Textpos(), System.Text.RegularExpressions.RegexParser.Textto(), System.SR.UnterminatedBracket, and System.Text.RegularExpressions.RegexParser.UseOptionE().
Referenced by System.Text.RegularExpressions.RegexParser.CountCaptures(), System.Text.RegularExpressions.RegexParser.ScanCharClass(), and System.Text.RegularExpressions.RegexParser.ScanRegex().