Terraria: System.Text.RegularExpressions.RegexParser.CountCaptures
CountCaptures()
void System.Text.RegularExpressions.RegexParser.CountCaptures () inline private
Definition at line 1517 of file RegexParser.cs.
    {
        NoteCaptureSlot(0, 0);
        _autocap = 1;
        while (CharsRight() > 0)
        {
            int pos = Textpos();
            switch (RightCharMoveRight())
            {
            case '\\':
                if (CharsRight() > 0)
                {
                    ScanBackslash(scanOnly: true);
                }
                break;
            case '#':
                if (UseOptionX())
                {
                    MoveLeft();
                    ScanBlank();
                }
                break;
            case '[':
                ScanCharClass(caseInsensitive: false, scanOnly: true);
                break;
            case ')':
                if (!EmptyOptionsStack())
                {
                    PopOptions();
                }
                break;
            case '(':
                if (CharsRight() >= 2 && RightChar(1) == '#' && RightChar() == '?')
                {
                    MoveLeft();
                    ScanBlank();
                }
                else
                {
                    PushOptions();
                    if (CharsRight() > 0 && RightChar() == '?')
                    {
                        MoveRight();
                        if (CharsRight() > 1 && (RightChar() == '<' || RightChar() == '\''))
{
                            MoveRight();
                            char c = RightChar();
                            if (c != '0' && RegexCharClass.IsWordChar(c))
{
                                if ((uint)(c - 49) <= 8u)
{
                                    NoteCaptureSlot(ScanDecimal(), pos);
                                }
                                else
{
                                    NoteCaptureName(ScanCapname(), pos);
                                }
                            }
                        }
                        else
{
                            ScanOptions();
                            if (CharsRight() > 0)
{
                                if (RightChar() == ')')
{
                                    MoveRight();
                                    PopKeepOptions();
                                }
                                else if (RightChar() == '(')
{
                                    _ignoreNextParen = true;
                                    break;
                                }
                            }
                        }
                    }
                    else if (!UseOptionN() && !_ignoreNextParen)
                    {
                        NoteCaptureSlot(_autocap++, pos);
                    }
                }
                _ignoreNextParen = false;
                break;
            }
        }
        AssignNameSlots();
    }
References System.Text.RegularExpressions.RegexParser._autocap, System.Text.RegularExpressions.RegexParser._ignoreNextParen, System.Text.RegularExpressions.RegexParser.AssignNameSlots(), System.Text.RegularExpressions.RegexParser.CharsRight(), System.Text.RegularExpressions.RegexParser.EmptyOptionsStack(), System.Text.RegularExpressions.RegexCharClass.IsWordChar(), System.Text.RegularExpressions.RegexParser.MoveLeft(), System.Text.RegularExpressions.RegexParser.MoveRight(), System.Text.RegularExpressions.RegexParser.NoteCaptureName(), System.Text.RegularExpressions.RegexParser.NoteCaptureSlot(), System.Text.RegularExpressions.RegexParser.PopKeepOptions(), System.Text.RegularExpressions.RegexParser.PopOptions(), System.Text.RegularExpressions.RegexParser.PushOptions(), System.Text.RegularExpressions.RegexParser.RightChar(), System.Text.RegularExpressions.RegexParser.RightCharMoveRight(), System.Text.RegularExpressions.RegexParser.ScanBackslash(), System.Text.RegularExpressions.RegexParser.ScanBlank(), System.Text.RegularExpressions.RegexParser.ScanCapname(), System.Text.RegularExpressions.RegexParser.ScanCharClass(), System.Text.RegularExpressions.RegexParser.ScanDecimal(), System.Text.RegularExpressions.RegexParser.ScanOptions(), System.Text.RegularExpressions.RegexParser.Textpos(), System.Text.RegularExpressions.RegexParser.UseOptionN(), and System.Text.RegularExpressions.RegexParser.UseOptionX().