Terraria: System.Text.RegularExpressions.RegexParser.ScanRegex
ScanRegex()
RegexNode System.Text.RegularExpressions.RegexParser.ScanRegex () inline private
Definition at line 244 of file RegexParser.cs.
    {
        char c = '@';
        bool flag = false;
        StartGroup(new RegexNode(28, _options, 0, -1));
        while (CharsRight() > 0)
        {
            bool flag2 = flag;
            flag = false;
            ScanBlank();
            int num = Textpos();
            if (UseOptionX())
            {
                while (CharsRight() > 0 && (!IsStopperX(c = RightChar()) || (c == '{' && !IsTrueQuantifier())))
                {
                    MoveRight();
                }
            }
            else
            {
                while (CharsRight() > 0 && (!IsSpecial(c = RightChar()) || (c == '{' && !IsTrueQuantifier())))
                {
                    MoveRight();
                }
            }
            int num2 = Textpos();
            ScanBlank();
            if (CharsRight() == 0)
            {
                c = '!';
            }
            else if (IsSpecial(c = RightChar()))
            {
                flag = IsQuantifier(c);
                MoveRight();
            }
            else
            {
                c = ' ';
            }
            if (num < num2)
            {
                int num3 = num2 - num - (flag ? 1 : 0);
                flag2 = false;
                if (num3 > 0)
                {
                    AddConcatenate(num, num3, isReplacement: false);
                }
                if (flag)
                {
                    AddUnitOne(CharAt(num2 - 1));
                }
            }
            switch (c)
            {
            case '[':
                AddUnitSet(ScanCharClass(UseOptionI(), scanOnly: false).ToStringClass());
                goto IL_02cf;
            case '(':
            {
                PushOptions();
                RegexNode openGroup;
                if ((openGroup = ScanGroupOpen()) == null)
                {
                    PopKeepOptions();
                    continue;
                }
                PushGroup();
                StartGroup(openGroup);
                continue;
            }
            case '|':
                AddAlternate();
                continue;
            case ')':
                if (EmptyStack())
                {
                    throw MakeException(RegexParseError.InsufficientOpeningParentheses, System.SR.InsufficientOpeningParentheses);
                }
                AddGroup();
                PopGroup();
                PopOptions();
                if (Unit() == null)
                {
                    continue;
                }
                goto IL_02cf;
            case '\\':
                if (CharsRight() == 0)
                {
                    throw MakeException(RegexParseError.UnescapedEndingBackslash, System.SR.UnescapedEndingBackslash);
                }
                AddUnitNode(ScanBackslash(scanOnly: false));
                goto IL_02cf;
            case '^':
                AddUnitType(UseOptionM() ? 14 : 18);
                goto IL_02cf;
            case '$':
                AddUnitType(UseOptionM() ? 15 : 20);
                goto IL_02cf;
            case '.':
                if (UseOptionS())
                {
                    AddUnitSet("\0\u0001\0\0");
                }
                else
                {
                    AddUnitNotone('\n');
                }
                goto IL_02cf;
            case '*':
            case '+':
            case '?':
            case '{':
                if (Unit() == null)
                {
                    throw flag2 ? MakeException(RegexParseError.NestedQuantifiersNotParenthesized, System.SR.Format(System.SR.NestedQuantifiersNotParenthesized, c)) : MakeException(RegexParseError.QuantifierAfterNothing, System.SR.QuantifierAfterNothing);
                }
                MoveLeft();
                goto IL_02cf;
            default:
                throw new InvalidOperationException(System.SR.InternalError_ScanRegex);
            case ' ':
                continue;
            case '!':
                break;
                IL_02cf:
                ScanBlank();
                if (CharsRight() == 0 || !(flag = IsTrueQuantifier()))
                {
                    AddConcatenate();
                    continue;
                }
                c = RightCharMoveRight();
                while (Unit() != null)
                {
                    int num4;
                    int num5;
                    if ((uint)c <= 43u)
                    {
                        if (c != '*')
{
                            if (c != '+')
{
                                goto IL_03cd;
                            }
                            num4 = 1;
                            num5 = int.MaxValue;
                        }
                        else
{
                            num4 = 0;
                            num5 = int.MaxValue;
                        }
                    }
                    else if (c != '?')
                    {
                        if (c != '{')
{
                            goto IL_03cd;
                        }
                        num = Textpos();
                        num5 = (num4 = ScanDecimal());
                        if (num < Textpos() && CharsRight() > 0 && RightChar() == ',')
{
                            MoveRight();
                            num5 = ((CharsRight() != 0 && RightChar() != '}') ? ScanDecimal() : int.MaxValue);
                        }
                        if (num == Textpos() || CharsRight() == 0 || RightCharMoveRight() != '}')
{
                            AddConcatenate();
                            Textto(num - 1);
                            break;
                        }
                    }
                    else
                    {
                        num4 = 0;
                        num5 = 1;
                    }
                    ScanBlank();
                    bool lazy = false;
                    if (CharsRight() != 0 && RightChar() == '?')
                    {
                        MoveRight();
                        lazy = true;
                    }
                    if (num4 > num5)
                    {
                        throw MakeException(RegexParseError.ReversedQuantifierRange, System.SR.ReversedQuantifierRange);
                    }
                    AddConcatenate(lazy, num4, num5);
                    continue;
                    IL_03cd:
                    throw new InvalidOperationException(System.SR.InternalError_ScanRegex);
                }
                continue;
            }
            break;
        }
        if (!EmptyStack())
        {
            throw MakeException(RegexParseError.InsufficientClosingParentheses, System.SR.InsufficientClosingParentheses);
        }
        AddGroup();
        return Unit().FinalOptimize();
    }
References System.Text.RegularExpressions.RegexParser._options, System.Text.RegularExpressions.RegexParser.AddAlternate(), System.Text.RegularExpressions.RegexParser.AddConcatenate(), System.Text.RegularExpressions.RegexParser.AddGroup(), System.Text.RegularExpressions.RegexParser.AddUnitNode(), System.Text.RegularExpressions.RegexParser.AddUnitNotone(), System.Text.RegularExpressions.RegexParser.AddUnitOne(), System.Text.RegularExpressions.RegexParser.AddUnitSet(), System.Text.RegularExpressions.RegexParser.AddUnitType(), System.Text.RegularExpressions.RegexParser.CharAt(), System.Text.RegularExpressions.RegexParser.CharsRight(), System.Text.RegularExpressions.RegexParser.EmptyStack(), System.Text.RegularExpressions.RegexNode.FinalOptimize(), System.SR.Format(), System.SR.InsufficientClosingParentheses, System.SR.InsufficientOpeningParentheses, System.SR.InternalError_ScanRegex, System.Text.RegularExpressions.RegexParser.IsQuantifier(), System.Text.RegularExpressions.RegexParser.IsSpecial(), System.Text.RegularExpressions.RegexParser.IsStopperX(), System.Text.RegularExpressions.RegexParser.IsTrueQuantifier(), System.Text.RegularExpressions.RegexParser.MakeException(), System.Text.RegularExpressions.RegexParser.MoveLeft(), System.Text.RegularExpressions.RegexParser.MoveRight(), System.SR.NestedQuantifiersNotParenthesized, System.Text.RegularExpressions.RegexParser.PopGroup(), System.Text.RegularExpressions.RegexParser.PopKeepOptions(), System.Text.RegularExpressions.RegexParser.PopOptions(), System.Text.RegularExpressions.RegexParser.PushGroup(), System.Text.RegularExpressions.RegexParser.PushOptions(), System.SR.QuantifierAfterNothing, System.SR.ReversedQuantifierRange, System.Text.RegularExpressions.RegexParser.RightChar(), System.Text.RegularExpressions.RegexParser.RightCharMoveRight(), System.Text.RegularExpressions.RegexParser.ScanBackslash(), System.Text.RegularExpressions.RegexParser.ScanBlank(), System.Text.RegularExpressions.RegexParser.ScanCharClass(), System.Text.RegularExpressions.RegexParser.ScanDecimal(), System.Text.RegularExpressions.RegexParser.ScanGroupOpen(), System.Text.RegularExpressions.RegexParser.StartGroup(), System.Text.RegularExpressions.RegexParser.Textpos(), System.Text.RegularExpressions.RegexParser.Textto(), System.SR.UnescapedEndingBackslash, System.Text.RegularExpressions.RegexParser.Unit(), System.Text.RegularExpressions.RegexParser.UseOptionI(), System.Text.RegularExpressions.RegexParser.UseOptionM(), System.Text.RegularExpressions.RegexParser.UseOptionS(), and System.Text.RegularExpressions.RegexParser.UseOptionX().