Terraria: System.Net.Mail.MailHeaderInfo.GetString
GetString()
static string System.Net.Mail.MailHeaderInfo.GetString (MailHeaderID id) inline static package
Definition at line 78 of file MailHeaderInfo.cs.
    {
        if (id == MailHeaderID.Unknown || id == (MailHeaderID)33)
        {
            return null;
        }
        return s_headerInfo[(int)id].NormalizedName;
    }
References System.Net.Mail.MailHeaderInfo.s_headerInfo.
Referenced by System.Net.Mime.ContentDisposition.PersistIfNeeded(), System.Net.Mime.ContentType.PersistIfNeeded(), System.Net.Mail.Message.PrepareEnvelopeHeaders(), System.Net.Mime.MimeBasePart.PrepareHeaders(), and System.Net.Mail.Message.PrepareHeaders().