Terraria: TileEntity.BasicOpenCloseInteraction
BasicOpenCloseInteraction()
static void TileEntity.BasicOpenCloseInteraction (Player player, int x, int y, int id) inline static
     {
         player.CloseSign();
         int interactingPlayer;
         if (Main.netMode != 1)
         {
             Main.stackSplit = 600;
             player.GamepadEnableGrappleCooldown();
             if (IsOccupied(id, out interactingPlayer))
             {
                 if (interactingPlayer == player.whoAmI)
                 {
                     Recipe.FindRecipes();
                     SoundEngine.PlaySound(11);
                     player.tileEntityAnchor.Clear();
                 }
             }
             else
             {
                 SetInteractionAnchor(player, x, y, id);
             }
             return;
         }
         Main.stackSplit = 600;
         player.GamepadEnableGrappleCooldown();
         if (IsOccupied(id, out interactingPlayer))
         {
             if (interactingPlayer == player.whoAmI)
             {
                 Recipe.FindRecipes();
                 SoundEngine.PlaySound(11);
                 player.tileEntityAnchor.Clear();
                 NetMessage.SendData(122, -1, -1, null, -1, Main.myPlayer);
             }
         }
         else
         {
             NetMessage.SendData(122, -1, -1, null, id, Main.myPlayer);
         }
     }
References PlayerInteractionAnchor.Clear(), Player.CloseSign(), Recipe.FindRecipes(), Player.GamepadEnableGrappleCooldown(), IsOccupied(), Main.myPlayer, Main.netMode, SoundEngine.PlaySound(), NetMessage.SendData(), SetInteractionAnchor(), Main.stackSplit, Player.tileEntityAnchor, and Entity.whoAmI.
Referenced by TEDisplayDoll.OnPlayerInteraction(), and TEHatRack.OnPlayerInteraction().