Terraria: System.Xml.XPathNodePointer.MoveTo
MoveTo() [3/3]
bool System.Xml.XPathNodePointer.MoveTo (XPathNodePointer pointer) inline package
Definition at line 501 of file XPathNodePointer.cs.
    {
        if (_doc != pointer._doc)
        {
            return false;
        }
        _node = pointer._node;
        _column = pointer._column;
        _fOnValue = pointer._fOnValue;
        _bNeedFoliate = pointer._bNeedFoliate;
        return true;
    }
References System.Xml.XPathNodePointer._bNeedFoliate, System.Xml.XPathNodePointer._column, System.Xml.XPathNodePointer._doc, System.Xml.XPathNodePointer._fOnValue, System.Xml.XPathNodePointer._node, and System.pointer.
Referenced by System.Xml.DataDocumentXPathNavigator.GetAttribute(), System.Xml.DataDocumentXPathNavigator.MoveTo(), System.Xml.XPathNodePointer.MoveToAttribute(), and System.Xml.XPathNodePointer.MoveToNextAttribute().