Terraria: System.Xml.XPathNodePointer.RealFoliate
RealFoliate()
void System.Xml.XPathNodePointer.RealFoliate () inline private
Definition at line 1171 of file XPathNodePointer.cs.
    {
        if (!_bNeedFoliate)
        {
            return;
        }
        _bNeedFoliate = false;
        XmlNode xmlNode = null;
        if (_doc.IsTextOnly(_column))
        {
            xmlNode = _node.FirstChild;
        }
        else
        {
            if (_column.ColumnMapping == MappingType.Attribute)
            {
                xmlNode = _node.Attributes.GetNamedItem(_column.EncodedColumnName, _column.Namespace);
            }
            else
            {
                xmlNode = _node.FirstChild;
                while (xmlNode != null && (!(xmlNode.LocalName == _column.EncodedColumnName) || !(xmlNode.NamespaceURI == _column.Namespace)))
                {
                    xmlNode = xmlNode.NextSibling;
                }
            }
            if (xmlNode != null && _fOnValue)
            {
                xmlNode = xmlNode.FirstChild;
            }
        }
        if (xmlNode == null)
        {
            throw new InvalidOperationException(System.SR.DataDom_Foliation);
        }
        _node = xmlNode;
        _column = null;
        _fOnValue = false;
        _bNeedFoliate = false;
    }
References System.Xml.XmlNode.Attributes, System.SR.DataDom_Foliation, System.Xml.XmlNode.FirstChild, System.Xml.XmlNamedNodeMap.GetNamedItem(), System.Xml.XmlNode.LocalName, System.Xml.XmlNode.NamespaceURI, and System.Xml.XmlNode.NextSibling.
Referenced by System.Xml.XPathNodePointer.Clone(), System.Xml.XPathNodePointer.MoveToAttribute(), and System.Xml.XPathNodePointer.MoveToNextAttribute().