Terraria: System.Xml.XPathNodePointer.MoveToNextAttribute
MoveToNextAttribute()
bool System.Xml.XPathNodePointer.MoveToNextAttribute (bool bFirst) inline package
Definition at line 629 of file XPathNodePointer.cs.
    {
        RealFoliate();
        if (_node != null)
        {
            if (bFirst && (_column != null || _node.NodeType != XmlNodeType.Element))
            {
                return false;
            }
            if (!bFirst)
            {
                if (_column != null && _column.ColumnMapping != MappingType.Attribute)
                {
                    return false;
                }
                if (_column == null && _node.NodeType != XmlNodeType.Attribute)
                {
                    return false;
                }
            }
            if (!IsFoliated(_node))
            {
                DataColumn dataColumn = _column;
                while ((dataColumn = NextColumn(Row, dataColumn, fAttribute: true)) != null)
                {
                    if (dataColumn.Namespace != "http://www.w3.org/2000/xmlns/")
                    {
                        MoveTo(_node, dataColumn, fOnValue: false);
                        return true;
                    }
                }
                return false;
            }
            if (bFirst)
            {
                XmlAttributeCollection attributes = _node.Attributes;
                foreach (XmlAttribute item in attributes)
                {
                    if (item.NamespaceURI != "http://www.w3.org/2000/xmlns/")
                    {
                        MoveTo(item, null, fOnValue: false);
                        return true;
                    }
                }
            }
            else
            {
                XmlAttributeCollection attributes2 = ((XmlAttribute)_node).OwnerElement.Attributes;
                bool flag = false;
                foreach (XmlAttribute item2 in attributes2)
                {
                    if (flag && item2.NamespaceURI != "http://www.w3.org/2000/xmlns/")
                    {
                        MoveTo(item2, null, fOnValue: false);
                        return true;
                    }
                    if (item2 == _node)
                    {
                        flag = true;
                    }
                }
            }
        }
        return false;
    }
References System.Xml.XPathNodePointer._column, System.Xml.XPathNodePointer._node, System.Xml.XmlNode.Attributes, System.Data.DataColumn.ColumnMapping, System.Xml.Dictionary, System.Xml.XPathNodePointer.IsFoliated(), System.item, System.Xml.XPathNodePointer.MoveTo(), System.Xml.XPathNodePointer.NextColumn(), System.Xml.XmlNode.NodeType, System.Xml.XPathNodePointer.RealFoliate(), and System.Xml.XPathNodePointer.Row.
Referenced by System.Xml.DataDocumentXPathNavigator.MoveToFirstAttribute(), and System.Xml.DataDocumentXPathNavigator.MoveToNextAttribute().