Terraria: System.Xml.XPathNodePointer.NextColumn
NextColumn()
DataColumn System.Xml.XPathNodePointer.NextColumn (DataRow row, DataColumn col, bool fAttribute) inline package
Definition at line 551 of file XPathNodePointer.cs.
    {
        if (row.RowState == DataRowState.Deleted)
        {
            return null;
        }
        DataTable table = row.Table;
        DataColumnCollection columns = table.Columns;
        int i = ((col != null) ? (col.Ordinal + 1) : 0);
        int count = columns.Count;
        DataRowVersion version = ((row.RowState == DataRowState.Detached) ? DataRowVersion.Proposed : DataRowVersion.Current);
        for (; i < count; i++)
        {
            DataColumn dataColumn = columns[i];
            if (!_doc.IsNotMapped(dataColumn) && dataColumn.ColumnMapping == MappingType.Attribute == fAttribute && !Convert.IsDBNull(row[dataColumn, version]))
            {
                return dataColumn;
            }
        }
        return null;
    }
References System.Xml.XPathNodePointer._doc, System.Data.DataTable.Columns, System.count, System.Xml.Dictionary, System.Convert.IsDBNull(), and System.Xml.XmlDataDocument.IsNotMapped().
Referenced by System.Xml.XPathNodePointer.ColumnCount(), System.Xml.XPathNodePointer.MoveToAttribute(), and System.Xml.XPathNodePointer.MoveToNextAttribute().