Terraria: System.Xml.Xsl.Runtime.XmlStringSortKey.CompareTo
CompareTo() [1/3]
override int System.Xml.Xsl.Runtime.XmlStringSortKey.CompareTo (object obj) inline
Definition at line 25 of file XmlStringSortKey.cs.
    {
        if (!(obj is XmlStringSortKey xmlStringSortKey))
        {
            return CompareToEmpty(obj);
        }
        int num;
        if (_sortKey != null)
        {
            num = SortKey.Compare(_sortKey, xmlStringSortKey._sortKey);
        }
        else
        {
            int num2 = ((_sortKeyBytes.Length < xmlStringSortKey._sortKeyBytes.Length) ? _sortKeyBytes.Length : xmlStringSortKey._sortKeyBytes.Length);
            int num3 = 0;
            while (true)
            {
                if (num3 < num2)
                {
                    if (_sortKeyBytes[num3] < xmlStringSortKey._sortKeyBytes[num3])
                    {
                        num = -1;
                        break;
                    }
                    if (_sortKeyBytes[num3] > xmlStringSortKey._sortKeyBytes[num3])
                    {
                        num = 1;
                        break;
                    }
                    num3++;
                    continue;
                }
                num = ((_sortKeyBytes.Length >= xmlStringSortKey._sortKeyBytes.Length) ? ((_sortKeyBytes.Length > xmlStringSortKey._sortKeyBytes.Length) ? 1 : 0) : (-1));
                break;
            }
        }
        if (num == 0)
        {
            return BreakSortingTie(xmlStringSortKey);
        }
        if (!_descendingOrder)
        {
            return num;
        }
        return -num;
    }
References System.Xml.Xsl.Runtime.XmlStringSortKey._descendingOrder, System.Xml.Xsl.Runtime.XmlStringSortKey._sortKey, System.Xml.Xsl.Runtime.XmlStringSortKey._sortKeyBytes, System.Xml.Xsl.Runtime.XmlSortKey.BreakSortingTie(), System.Globalization.SortKey.Compare(), System.Xml.Xsl.Runtime.XmlSortKey.CompareToEmpty(), System.Xml.Dictionary, and System.obj.