using System;
using System.Diagnostics;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.Serialization;
using System.Runtime.Serialization.Json;
using System.Runtime.Versioning;
using System.Security;
using System.Security.Permissions;
using System.Xml;

[assembly: CLSCompliant(true)]
[assembly: AssemblyDefaultAlias("System.Runtime.Serialization")]
[assembly: AssemblyMetadata(".NETFrameworkAssembly", "")]
[assembly: AssemblyMetadata("Serviceable", "True")]
[assembly: AssemblyMetadata("PreferInbox", "True")]
[assembly: AssemblyMetadata("IsTrimmable", "True")]
[assembly: AssemblyCompany("Microsoft Corporation")]
[assembly: AssemblyCopyright("© Microsoft Corporation. All rights reserved.")]
[assembly: AssemblyDescription("System.Runtime.Serialization")]
[assembly: AssemblyFileVersion("6.0.21.52210")]
[assembly: AssemblyInformationalVersion("6.0.0+4822e3c3aa77eb82b2fb33c9321f923cf11ddde6")]
[assembly: AssemblyProduct("Microsoft® .NET")]
[assembly: AssemblyTitle("System.Runtime.Serialization")]
[assembly: AssemblyMetadata("RepositoryUrl", "https://github.com/dotnet/runtime")]
[assembly: AssemblyVersion("4.0.0.0")]
[assembly: TypeForwardedTo(typeof(CollectionDataContractAttribute))]
[assembly: TypeForwardedTo(typeof(ContractNamespaceAttribute))]
[assembly: TypeForwardedTo(typeof(DataContractAttribute))]
[assembly: TypeForwardedTo(typeof(DataContractResolver))]
[assembly: TypeForwardedTo(typeof(DataContractSerializer))]
[assembly: TypeForwardedTo(typeof(DataContractSerializerExtensions))]
[assembly: TypeForwardedTo(typeof(DataContractSerializerSettings))]
[assembly: TypeForwardedTo(typeof(DataMemberAttribute))]
[assembly: TypeForwardedTo(typeof(DateTimeFormat))]
[assembly: TypeForwardedTo(typeof(EmitTypeInformation))]
[assembly: TypeForwardedTo(typeof(EnumMemberAttribute))]
[assembly: TypeForwardedTo(typeof(ExportOptions))]
[assembly: TypeForwardedTo(typeof(ExtensionDataObject))]
[assembly: TypeForwardedTo(typeof(IExtensibleDataObject))]
[assembly: TypeForwardedTo(typeof(IgnoreDataMemberAttribute))]
[assembly: TypeForwardedTo(typeof(InvalidDataContractException))]
[assembly: TypeForwardedTo(typeof(ISerializationSurrogateProvider))]
[assembly: TypeForwardedTo(typeof(DataContractJsonSerializer))]
[assembly: TypeForwardedTo(typeof(DataContractJsonSerializerSettings))]
[assembly: TypeForwardedTo(typeof(IXmlJsonReaderInitializer))]
[assembly: TypeForwardedTo(typeof(IXmlJsonWriterInitializer))]
[assembly: TypeForwardedTo(typeof(JsonReaderWriterFactory))]
[assembly: TypeForwardedTo(typeof(KnownTypeAttribute))]
[assembly: TypeForwardedTo(typeof(XmlObjectSerializer))]
[assembly: TypeForwardedTo(typeof(XmlSerializableServices))]
[assembly: TypeForwardedTo(typeof(XPathQueryGenerator))]
[assembly: TypeForwardedTo(typeof(XsdDataContractExporter))]
[assembly: TypeForwardedTo(typeof(IFragmentCapableXmlDictionaryWriter))]
[assembly: TypeForwardedTo(typeof(IStreamProvider))]
[assembly: TypeForwardedTo(typeof(IXmlBinaryReaderInitializer))]
[assembly: TypeForwardedTo(typeof(IXmlBinaryWriterInitializer))]
[assembly: TypeForwardedTo(typeof(IXmlDictionary))]
[assembly: TypeForwardedTo(typeof(IXmlTextReaderInitializer))]
[assembly: TypeForwardedTo(typeof(IXmlTextWriterInitializer))]
[assembly: TypeForwardedTo(typeof(OnXmlDictionaryReaderClose))]
[assembly: TypeForwardedTo(typeof(UniqueId))]
[assembly: TypeForwardedTo(typeof(XmlBinaryReaderSession))]
[assembly: TypeForwardedTo(typeof(XmlBinaryWriterSession))]
[assembly: TypeForwardedTo(typeof(XmlDictionary))]
[assembly: TypeForwardedTo(typeof(XmlDictionaryReader))]
[assembly: TypeForwardedTo(typeof(XmlDictionaryReaderQuotas))]
[assembly: TypeForwardedTo(typeof(XmlDictionaryReaderQuotaTypes))]
[assembly: TypeForwardedTo(typeof(XmlDictionaryString))]
[assembly: TypeForwardedTo(typeof(XmlDictionaryWriter))]
[module: SkipLocalsInit]
