Terraria: System.Reflection.PortableExecutable.DebugDirectoryBuilder.AddCodeViewEntry
AddCodeViewEntry() [2/2]
void System.Reflection.PortableExecutable.DebugDirectoryBuilder.AddCodeViewEntry (string pdbPath, BlobContentId pdbContentId, ushort portablePdbVersion, int age) inline
Definition at line 69 of file DebugDirectoryBuilder.cs.
    {
        if (pdbPath == null)
        {
            Throw.ArgumentNull("pdbPath");
        }
        if (age < 1)
        {
            Throw.ArgumentOutOfRange("age");
        }
        if (pdbPath.Length == 0 || pdbPath.IndexOf('\0') == 0)
        {
            Throw.InvalidArgument(System.SR.ExpectedNonEmptyString, "pdbPath");
        }
        if (portablePdbVersion > 0 && portablePdbVersion < 256)
        {
            Throw.ArgumentOutOfRange("portablePdbVersion");
        }
        int dataSize = WriteCodeViewData(_dataBuilder, pdbPath, pdbContentId.Guid, age);
        AddEntry(DebugDirectoryEntryType.CodeView, (portablePdbVersion != 0) ? PortablePdbVersions.DebugDirectoryEntryVersion(portablePdbVersion) : 0u, pdbContentId.Stamp, dataSize);
    }
References System.Reflection.PortableExecutable.DebugDirectoryBuilder._dataBuilder, System.Reflection.PortableExecutable.DebugDirectoryBuilder.AddEntry(), System.Reflection.Throw.ArgumentNull(), System.Reflection.Throw.ArgumentOutOfRange(), System.Reflection.Metadata.PortablePdbVersions.DebugDirectoryEntryVersion(), System.SR.ExpectedNonEmptyString, System.Reflection.Throw.InvalidArgument(), and System.Reflection.PortableExecutable.DebugDirectoryBuilder.WriteCodeViewData().