Terraria: System.Runtime.InteropServices.ComAwareEventInfo.GetDataForComInvocation
GetDataForComInvocation()
static void System.Runtime.InteropServices.ComAwareEventInfo.GetDataForComInvocation (EventInfo eventInfo, out Guid sourceIid, out int dispid) inline static private
Definition at line 97 of file ComAwareEventInfo.cs.
    {
        object[] customAttributes = eventInfo.DeclaringType.GetCustomAttributes(typeof(ComEventInterfaceAttribute), inherit: false);
        if (customAttributes == null || customAttributes.Length == 0)
        {
            throw new InvalidOperationException(System.SR.InvalidOperation_NoComEventInterfaceAttribute);
        }
        if (customAttributes.Length > 1)
        {
            throw new AmbiguousMatchException(System.SR.AmbiguousMatch_MultipleEventInterfaceAttributes);
        }
        Type sourceInterface = ((ComEventInterfaceAttribute)customAttributes[0]).SourceInterface;
        Guid gUID = sourceInterface.GUID;
        MethodInfo method = sourceInterface.GetMethod(eventInfo.Name);
        Attribute customAttribute = Attribute.GetCustomAttribute(method, typeof(DispIdAttribute));
        if (customAttribute == null)
        {
            throw new InvalidOperationException(System.SR.InvalidOperation_NoDispIdAttribute);
        }
        sourceIid = gUID;
        dispid = ((DispIdAttribute)customAttribute).Value;
    }
References System.SR.AmbiguousMatch_MultipleEventInterfaceAttributes, System.Attribute.GetCustomAttribute(), System.SR.InvalidOperation_NoComEventInterfaceAttribute, and System.SR.InvalidOperation_NoDispIdAttribute.
Referenced by System.Runtime.InteropServices.ComAwareEventInfo.AddEventHandler(), and System.Runtime.InteropServices.ComAwareEventInfo.RemoveEventHandler().