Terraria: System.Transactions.TransactionStatePromotedNonMSDTCCommitted.EnterState
EnterState()
override void System.Transactions.TransactionStatePromotedNonMSDTCCommitted.EnterState (InternalTransaction tx) inline package
Definition at line 5 of file TransactionStatePromotedNonMSDTCCommitted.cs.
    {
        base.EnterState(tx);
        for (int i = 0; i < tx._phase0Volatiles._volatileEnlistmentCount; i++)
        {
            tx._phase0Volatiles._volatileEnlistments[i]._twoPhaseState.InternalCommitted(tx._phase0Volatiles._volatileEnlistments[i]);
        }
        for (int j = 0; j < tx._phase1Volatiles._volatileEnlistmentCount; j++)
        {
            tx._phase1Volatiles._volatileEnlistments[j]._twoPhaseState.InternalCommitted(tx._phase1Volatiles._volatileEnlistments[j]);
        }
        tx.FireCompletion();
        TransactionsEtwProvider log = TransactionsEtwProvider.Log;
        if (log.IsEnabled())
        {
            log.TransactionCommitted(tx.TransactionTraceId);
        }
    }
References System.Transactions.InternalTransaction._phase0Volatiles, System.Transactions.InternalTransaction._phase1Volatiles, System.Transactions.InternalEnlistment._twoPhaseState, System.Transactions.VolatileEnlistmentSet._volatileEnlistmentCount, System.Transactions.VolatileEnlistmentSet._volatileEnlistments, System.Transactions.InternalTransaction.FireCompletion(), System.Transactions.EnlistmentState.InternalCommitted(), System.Diagnostics.Tracing.EventSource.IsEnabled(), System.Transactions.TransactionsEtwProvider.Log, System.Transactions.TransactionsEtwProvider.TransactionCommitted(), and System.Transactions.InternalTransaction.TransactionTraceId.