Terraria: System.Runtime.InteropServices.ComAwareEventInfo.AddEventHandler
AddEventHandler() [1/2]
override void System.Runtime.InteropServices.ComAwareEventInfo.AddEventHandler (object target, Delegate handler) inline
Definition at line 30 of file ComAwareEventInfo.cs.
    {
        if (Marshal.IsComObject(target))
        {
            GetDataForComInvocation(_innerEventInfo, out var sourceIid, out var dispid);
            ComEventsHelper.Combine(target, sourceIid, dispid, handler);
        }
        else
        {
            _innerEventInfo.AddEventHandler(target, handler);
        }
    }
References System.Runtime.InteropServices.ComAwareEventInfo._innerEventInfo, System.Reflection.EventInfo.AddEventHandler(), System.Runtime.InteropServices.ComEventsHelper.Combine(), System.Runtime.InteropServices.ComAwareEventInfo.GetDataForComInvocation(), and System.Runtime.InteropServices.Marshal.IsComObject().