Terraria: System.Data.DataRowExtensions.UnboxT.Create
Create()
static Converter< object, T > System.Data.DataRowExtensions.UnboxT< T >.Create () inline static private
Definition at line 11 of file DataRowExtensions.cs.
        {
            if (typeof(T).IsValueType)
            {
                if (!typeof(T).IsGenericType || !(typeof(T).GetGenericTypeDefinition() == typeof(Nullable<>)))
                {
                    return ValueField;
                }
                return (Converter<object, T>)Delegate.CreateDelegate(typeof(Converter<object, T>), typeof(UnboxT<T>).GetMethod("NullableField", BindingFlags.Static | BindingFlags.NonPublic).MakeGenericMethod(typeof(T).GetGenericArguments()[0]));
            }
            return ReferenceField;
        }
References System.Delegate.CreateDelegate(), System.Data.DataRowExtensions.UnboxT< T >.ReferenceField(), and System.Data.DataRowExtensions.UnboxT< T >.ValueField().