Terraria: System.Data.DataRowExtensions.UnboxT.s_unbox
s_unbox
readonly Converter<object, T> System.Data.DataRowExtensions.UnboxT< T >.s_unbox = Create() static package
Definition at line 9 of file DataRowExtensions.cs.
Referenced by System.Data.DataRowExtensions.Field< T >(), System.Data.DataRowExtensions.Field< T >(), System.Data.DataRowExtensions.Field< T >(), System.Data.DataRowExtensions.Field< T >(), System.Data.DataRowExtensions.Field< T >(), and System.Data.DataRowExtensions.Field< T >().