Terraria: System.Net.WebHeaderCollection.Add
Add() [5/6]
override void System.Net.WebHeaderCollection.Add (string name, string? value) inline
Definition at line 310 of file WebHeaderCollection.cs.
    {
        if (name == null)
        {
            throw new ArgumentNullException("name");
        }
        if (name.Length == 0)
        {
            throw new ArgumentException(System.SR.Format(System.SR.net_emptyStringCall, "name"), "name");
        }
        name = HttpValidationHelpers.CheckBadHeaderNameChars(name);
        value = HttpValidationHelpers.CheckBadHeaderValueChars(value);
        InvalidateCachedArrays();
        InnerCollection.Add(name, value);
    }
References System.Collections.Specialized.NameValueCollection.Add(), System.Net.HttpValidationHelpers.CheckBadHeaderNameChars(), System.Net.HttpValidationHelpers.CheckBadHeaderValueChars(), System.SR.Format(), System.Net.WebHeaderCollection.InnerCollection, System.Collections.Specialized.NameValueCollection.InvalidateCachedArrays(), System.SR.net_emptyStringCall, and System.value.