Terraria: System.Reflection.Emit.__ExceptionInfo.MarkHelper
MarkHelper()
void System.Reflection.Emit.__ExceptionInfo.MarkHelper (int catchorfilterAddr, int catchEndAddr, Type catchClass, int type) inline private
Definition at line 44 of file __ExceptionInfo.cs.
    {
        int currentCatch = m_currentCatch;
        if (currentCatch >= m_catchAddr.Length)
        {
            m_filterAddr = ILGenerator.EnlargeArray(m_filterAddr);
            m_catchAddr = ILGenerator.EnlargeArray(m_catchAddr);
            m_catchEndAddr = ILGenerator.EnlargeArray(m_catchEndAddr);
            m_catchClass = ILGenerator.EnlargeArray(m_catchClass);
            m_type = ILGenerator.EnlargeArray(m_type);
        }
        if (type == 1)
        {
            m_type[currentCatch] = type;
            m_filterAddr[currentCatch] = catchorfilterAddr;
            m_catchAddr[currentCatch] = -1;
            if (currentCatch > 0)
            {
                m_catchEndAddr[currentCatch - 1] = catchorfilterAddr;
            }
        }
        else
        {
            m_catchClass[currentCatch] = catchClass;
            if (m_type[currentCatch] != 1)
            {
                m_type[currentCatch] = type;
            }
            m_catchAddr[currentCatch] = catchorfilterAddr;
            if (currentCatch > 0 && m_type[currentCatch] != 1)
            {
                m_catchEndAddr[currentCatch - 1] = catchEndAddr;
            }
            m_catchEndAddr[currentCatch] = -1;
            m_currentCatch++;
        }
        if (m_endAddr == -1)
        {
            m_endAddr = catchorfilterAddr;
        }
    }
References System.Reflection.Emit.__ExceptionInfo.m_catchAddr, System.Reflection.Emit.__ExceptionInfo.m_catchClass, System.Reflection.Emit.__ExceptionInfo.m_catchEndAddr, System.Reflection.Emit.__ExceptionInfo.m_currentCatch, System.Reflection.Emit.__ExceptionInfo.m_endAddr, System.Reflection.Emit.__ExceptionInfo.m_filterAddr, System.Reflection.Emit.__ExceptionInfo.m_type, and System.type.
Referenced by System.Reflection.Emit.__ExceptionInfo.MarkCatchAddr(), System.Reflection.Emit.__ExceptionInfo.MarkFaultAddr(), System.Reflection.Emit.__ExceptionInfo.MarkFilterAddr(), and System.Reflection.Emit.__ExceptionInfo.MarkFinallyAddr().