Terraria: System.Reflection.Emit.__ExceptionInfo.MarkFilterAddr
MarkFilterAddr()
void System.Reflection.Emit.__ExceptionInfo.MarkFilterAddr (int filterAddr) inline package
Definition at line 86 of file __ExceptionInfo.cs.
    {
        m_currentState = 1;
        MarkHelper(filterAddr, filterAddr, null, 1);
    }
References System.Reflection.Emit.__ExceptionInfo.m_currentState, and System.Reflection.Emit.__ExceptionInfo.MarkHelper().
Referenced by System.Reflection.Emit.DynamicILGenerator.BeginExceptFilterBlock(), and System.Reflection.Emit.ILGenerator.BeginExceptFilterBlock().