Terraria: Terraria.GameContent.Achievements.AchievementsHelper.HandleOnEquip
HandleOnEquip()
static void Terraria.GameContent.Achievements.AchievementsHelper.HandleOnEquip (Player player, Item item, int context) inline static
Definition at line 228 of file AchievementsHelper.cs.
    {
        if (context == 16)
        {
            Main.Achievements.GetCondition("HOLD_ON_TIGHT", "Equip").Complete();
        }
        if (context == 17)
        {
            Main.Achievements.GetCondition("THE_CAVALRY", "Equip").Complete();
        }
        if ((context == 10 || context == 11) && item.wingSlot > 0)
        {
            Main.Achievements.GetCondition("HEAD_IN_THE_CLOUDS", "Equip").Complete();
        }
        if (context == 8 && player.armor[0].stack > 0 && player.armor[1].stack > 0 && player.armor[2].stack > 0)
        {
            Main.Achievements.GetCondition("MATCHING_ATTIRE", "Equip").Complete();
        }
        if (context == 9 && player.armor[10].stack > 0 && player.armor[11].stack > 0 && player.armor[12].stack > 0)
        {
            Main.Achievements.GetCondition("FASHION_STATEMENT", "Equip").Complete();
        }
        if (context != 12 && context != 33)
        {
            return;
        }
        for (int i = 0; i < 10; i++)
        {
            if (player.IsItemSlotUnlockedAndUsable(i) && (player.dye[i].type < 1 || player.dye[i].stack < 1))
            {
                return;
            }
        }
        for (int j = 0; j < player.miscDyes.Length; j++)
        {
            if (player.miscDyes[j].type < 1 || player.miscDyes[j].stack < 1)
            {
                return;
            }
        }
        Main.Achievements.GetCondition("DYE_HARD", "Equip").Complete();
    }
References Terraria.Main.Achievements, Terraria.Player.armor, Terraria.Player.dye, Terraria.Player.IsItemSlotUnlockedAndUsable(), Terraria.Player.miscDyes, Terraria.Item.stack, and Terraria.Item.type.
Referenced by Terraria.UI.ItemSlot.LeftClick(), Terraria.UI.ItemSlot.SwapEquip(), and Terraria.UI.ItemSlot.SwapVanityEquip().