Terraria: System.Threading.CancellationToken.ThrowIfCancellationRequested
ThrowIfCancellationRequested()
void System.Threading.CancellationToken.ThrowIfCancellationRequested () inline
Definition at line 115 of file CancellationToken.cs.
    {
        if (IsCancellationRequested)
        {
            ThrowOperationCanceledException();
        }
    }
References System.Threading.CancellationToken.IsCancellationRequested, and System.Threading.CancellationToken.ThrowOperationCanceledException().
Referenced by System.Linq.Parallel.GroupByElementSelectorQueryOperatorEnumerator< TSource, TGroupKey, TElement, TOrderKey >.BuildHashLookup(), System.Linq.Parallel.GroupByIdentityQueryOperatorEnumerator< TSource, TGroupKey, TOrderKey >.BuildHashLookup(), System.Linq.Parallel.OrderedGroupByElementSelectorQueryOperatorEnumerator< TSource, TGroupKey, TElement, TOrderKey >.BuildHashLookup(), System.Linq.Parallel.OrderedGroupByIdentityQueryOperatorEnumerator< TSource, TGroupKey, TOrderKey >.BuildHashLookup(), System.Linq.Parallel.HashRepartitionEnumerator< TInputOutput, THashKey, TIgnoreKey >.EnumerateAndRedistributeElements(), System.Linq.Parallel.OrderedHashRepartitionEnumerator< TInputOutput, THashKey, TOrderKey >.EnumerateAndRedistributeElements(), System.Linq.Parallel.ForAllOperator< TInput >.ForAllEnumerator< TKey >.MoveNext(), System.Linq.Parallel.DistinctQueryOperator< TInputOutput >.OrderedDistinctQueryOperatorEnumerator< TKey >.MoveNext(), System.Linq.Parallel.WhereQueryOperator< TInputOutput >.WhereQueryOperatorEnumerator< TKey >.MoveNext(), System.Linq.Parallel.ExceptQueryOperator< TInputOutput >.OrderedExceptQueryOperatorEnumerator< TLeftKey >.MoveNext(), System.Linq.Parallel.IntersectQueryOperator< TInputOutput >.OrderedIntersectQueryOperatorEnumerator< TLeftKey >.MoveNext(), System.Linq.Parallel.UnionQueryOperator< TInputOutput >.OrderedUnionQueryOperatorEnumerator< TLeftKey, TRightKey >.MoveNext(), System.Linq.Parallel.DistinctQueryOperator< TInputOutput >.DistinctQueryOperatorEnumerator< TKey >.MoveNext(), System.Linq.Parallel.ExceptQueryOperator< TInputOutput >.ExceptQueryOperatorEnumerator< TLeftKey >.MoveNext(), System.Linq.Parallel.IndexedWhereQueryOperator< TInputOutput >.IndexedWhereQueryOperatorEnumerator.MoveNext(), System.Linq.Parallel.IntersectQueryOperator< TInputOutput >.IntersectQueryOperatorEnumerator< TLeftKey >.MoveNext(), System.Linq.Parallel.UnionQueryOperator< TInputOutput >.UnionQueryOperatorEnumerator< TLeftKey, TRightKey >.MoveNext(), System.Linq.Parallel.AssociativeAggregationOperator< TInput, TIntermediate, TOutput >.AssociativeAggregationOperatorEnumerator< TKey >.MoveNext(), System.Linq.Parallel.HashJoinQueryOperatorEnumerator< TLeftInput, TLeftKey, TRightInput, TRightKey, THashKey, TOutput, TOutputKey >.MoveNext(), System.Linq.Parallel.SelectManyQueryOperator< TLeftInput, TRightInput, TOutput >.IndexedSelectManyQueryOperatorEnumerator.MoveNext(), System.Linq.Parallel.SelectManyQueryOperator< TLeftInput, TRightInput, TOutput >.SelectManyQueryOperatorEnumerator< TLeftKey >.MoveNext(), System.Linq.Parallel.TakeOrSkipQueryOperator< TResult >.TakeOrSkipQueryOperatorEnumerator< TKey >.MoveNext(), System.Linq.Parallel.TakeOrSkipWhileQueryOperator< TResult >.TakeOrSkipWhileQueryOperatorEnumerator< TKey >.MoveNext(), System.Linq.Parallel.ReverseQueryOperator< TSource >.ReverseQueryOperatorEnumerator< TKey >.MoveNext(), System.Linq.Parallel.ElementAtQueryOperator< TSource >.ElementAtQueryOperatorEnumerator.MoveNext(), System.Linq.Parallel.FirstQueryOperator< TSource >.FirstQueryOperatorEnumerator< TKey >.MoveNext(), System.Linq.Parallel.LastQueryOperator< TSource >.LastQueryOperatorEnumerator< TKey >.MoveNext(), System.Linq.Parallel.AnyAllSearchOperator< TInput >.AnyAllSearchOperatorEnumerator< TKey >.MoveNext(), System.Linq.Parallel.ContainsSearchOperator< TInput >.ContainsSearchOperatorEnumerator< TKey >.MoveNext(), System.Linq.Parallel.DecimalMinMaxAggregationOperator.DecimalMinMaxAggregationOperatorEnumerator< TKey >.MoveNextCore(), System.Linq.Parallel.DecimalSumAggregationOperator.DecimalSumAggregationOperatorEnumerator< TKey >.MoveNextCore(), System.Linq.Parallel.NullableDecimalMinMaxAggregationOperator.NullableDecimalMinMaxAggregationOperatorEnumerator< TKey >.MoveNextCore(), System.Linq.Parallel.NullableDecimalSumAggregationOperator.NullableDecimalSumAggregationOperatorEnumerator< TKey >.MoveNextCore(), System.Linq.Parallel.DoubleMinMaxAggregationOperator.DoubleMinMaxAggregationOperatorEnumerator< TKey >.MoveNextCore(), System.Linq.Parallel.DoubleSumAggregationOperator.DoubleSumAggregationOperatorEnumerator< TKey >.MoveNextCore(), System.Linq.Parallel.FloatSumAggregationOperator.FloatSumAggregationOperatorEnumerator< TKey >.MoveNextCore(), System.Linq.Parallel.NullableDoubleMinMaxAggregationOperator.NullableDoubleMinMaxAggregationOperatorEnumerator< TKey >.MoveNextCore(), System.Linq.Parallel.NullableDoubleSumAggregationOperator.NullableDoubleSumAggregationOperatorEnumerator< TKey >.MoveNextCore(), System.Linq.Parallel.NullableFloatSumAggregationOperator.NullableFloatSumAggregationOperatorEnumerator< TKey >.MoveNextCore(), System.Linq.Parallel.FloatMinMaxAggregationOperator.FloatMinMaxAggregationOperatorEnumerator< TKey >.MoveNextCore(), System.Linq.Parallel.NullableFloatMinMaxAggregationOperator.NullableFloatMinMaxAggregationOperatorEnumerator< TKey >.MoveNextCore(), System.Linq.Parallel.CountAggregationOperator< TSource >.CountAggregationOperatorEnumerator< TKey >.MoveNextCore(), System.Linq.Parallel.IntMinMaxAggregationOperator.IntMinMaxAggregationOperatorEnumerator< TKey >.MoveNextCore(), System.Linq.Parallel.IntSumAggregationOperator.IntSumAggregationOperatorEnumerator< TKey >.MoveNextCore(), System.Linq.Parallel.NullableIntMinMaxAggregationOperator.NullableIntMinMaxAggregationOperatorEnumerator< TKey >.MoveNextCore(), System.Linq.Parallel.NullableIntSumAggregationOperator.NullableIntSumAggregationOperatorEnumerator< TKey >.MoveNextCore(), System.Linq.Parallel.LongCountAggregationOperator< TSource >.LongCountAggregationOperatorEnumerator< TKey >.MoveNextCore(), System.Linq.Parallel.LongMinMaxAggregationOperator.LongMinMaxAggregationOperatorEnumerator< TKey >.MoveNextCore(), System.Linq.Parallel.LongSumAggregationOperator.LongSumAggregationOperatorEnumerator< TKey >.MoveNextCore(), System.Linq.Parallel.NullableLongMinMaxAggregationOperator.NullableLongMinMaxAggregationOperatorEnumerator< TKey >.MoveNextCore(), System.Linq.Parallel.NullableLongSumAggregationOperator.NullableLongSumAggregationOperatorEnumerator< TKey >.MoveNextCore(), System.Linq.Parallel.DecimalAverageAggregationOperator.DecimalAverageAggregationOperatorEnumerator< TKey >.MoveNextCore(), System.Linq.Parallel.NullableDecimalAverageAggregationOperator.NullableDecimalAverageAggregationOperatorEnumerator< TKey >.MoveNextCore(), System.Linq.Parallel.DoubleAverageAggregationOperator.DoubleAverageAggregationOperatorEnumerator< TKey >.MoveNextCore(), System.Linq.Parallel.FloatAverageAggregationOperator.FloatAverageAggregationOperatorEnumerator< TKey >.MoveNextCore(), System.Linq.Parallel.NullableDoubleAverageAggregationOperator.NullableDoubleAverageAggregationOperatorEnumerator< TKey >.MoveNextCore(), System.Linq.Parallel.NullableFloatAverageAggregationOperator.NullableFloatAverageAggregationOperatorEnumerator< TKey >.MoveNextCore(), System.Linq.Parallel.IntAverageAggregationOperator.IntAverageAggregationOperatorEnumerator< TKey >.MoveNextCore(), System.Linq.Parallel.LongAverageAggregationOperator.LongAverageAggregationOperatorEnumerator< TKey >.MoveNextCore(), System.Linq.Parallel.NullableIntAverageAggregationOperator.NullableIntAverageAggregationOperatorEnumerator< TKey >.MoveNextCore(), and System.Linq.Parallel.NullableLongAverageAggregationOperator.NullableLongAverageAggregationOperatorEnumerator< TKey >.MoveNextCore().