Terraria: SpriteDrawBuffer.CreateBuffers
CreateBuffers()
void SpriteDrawBuffer.CreateBuffers () inline private
     {
         if (vertexBuffer != null)
         {
             vertexBuffer.Dispose();
         }
         vertexBuffer = new DynamicVertexBuffer(graphicsDevice, typeof(VertexPositionColorTexture), maxSprites * 4, BufferUsage.WriteOnly);
         if (indexBuffer != null)
         {
             indexBuffer.Dispose();
         }
         indexBuffer = new IndexBuffer(graphicsDevice, typeof(ushort), maxSprites * 6, BufferUsage.WriteOnly);
         indexBuffer.SetData(GenIndexBuffer(maxSprites));
         Array.Resize(ref vertices, maxSprites * 6);
         Array.Resize(ref textures, maxSprites);
     }
References GenIndexBuffer(), graphicsDevice, indexBuffer, maxSprites, textures, vertexBuffer, and vertices.
Referenced by SpriteDrawBuffer(), CheckGraphicsDevice(), and QueueSprite().