Terraria: Terraria.GameContent.PortalHelper.SupportedSlope
SupportedSlope()
static bool Terraria.GameContent.PortalHelper.SupportedSlope (int x, int y, int slope) inline static private
Definition at line 554 of file PortalHelper.cs.
    {
        Tile tile = Main.tile[x, y];
        if (tile != null && tile.nactive() && !Main.tileCut[tile.type] && !TileID.Sets.BreakableWhenPlacing[tile.type] && Main.tileSolid[tile.type] && tile.slope() == slope)
        {
            return DoesTileTypeSupportPortals(tile.type);
        }
        return false;
    }
References Terraria.ID.TileID.Sets.BreakableWhenPlacing, Terraria.GameContent.PortalHelper.DoesTileTypeSupportPortals(), Terraria.Tile.nactive(), Terraria.Tile.slope(), Terraria.Main.tile, Terraria.Main.tileCut, Terraria.Main.tileSolid, and Terraria.Tile.type.
Referenced by Terraria.GameContent.PortalHelper.SupportedTilesAreFine().