Terraria: Terraria.GameContent.PortalHelper.IsValidLine
IsValidLine()
static bool Terraria.GameContent.PortalHelper.IsValidLine (Point position, int xOffset, int yOffset) inline static private
Definition at line 267 of file PortalHelper.cs.
    {
        Tile tile = Main.tile[position.X, position.Y];
        Tile tile2 = Main.tile[position.X - xOffset, position.Y - yOffset];
        Tile tile3 = Main.tile[position.X + xOffset, position.Y + yOffset];
        if (BlockPortals(Main.tile[position.X + yOffset, position.Y - xOffset]) || BlockPortals(Main.tile[position.X + yOffset - xOffset, position.Y - xOffset - yOffset]) || BlockPortals(Main.tile[position.X + yOffset + xOffset, position.Y - xOffset + yOffset]))
        {
            return false;
        }
        if (CanPlacePortalOn(tile) && CanPlacePortalOn(tile2) && CanPlacePortalOn(tile3) && tile2.HasSameSlope(tile) && tile3.HasSameSlope(tile))
        {
            return true;
        }
        return false;
    }
References Terraria.GameContent.PortalHelper.BlockPortals(), Terraria.GameContent.PortalHelper.CanPlacePortalOn(), Terraria.Main.tile, Microsoft.Xna.Framework.Point.X, and Microsoft.Xna.Framework.Point.Y.
Referenced by Terraria.GameContent.PortalHelper.FindValidLine().