Terraria: Terraria.GameContent.PortalHelper.GetPortalColor
GetPortalColor() [1/2]
static Color Terraria.GameContent.PortalHelper.GetPortalColor (int colorIndex) inline static
Definition at line 372 of file PortalHelper.cs.
    {
        return GetPortalColor(colorIndex / 2, colorIndex % 2);
    }
References Terraria.GameContent.PortalHelper.GetPortalColor().
Referenced by Terraria.Projectile.AI_001(), Terraria.Graphics.Light.TileLightScanner.ApplyTileLight(), Terraria.Main.DrawProjDirect(), Terraria.GameContent.Drawing.TileDrawing.DrawSingleTile(), Terraria.Projectile.GetAlpha(), Terraria.GameContent.PortalHelper.GetPortalColor(), Terraria.Projectile.Kill(), Terraria.Main.TeleportEffect(), Terraria.NPC.UpdateNPC_TeleportVisuals(), and Terraria.Player.UpdateTeleportVisuals().