Terraria: System.Dynamic.BindingRestrictions.InstanceRestriction.GetExpression
GetExpression()
override Expression System.Dynamic.BindingRestrictions.InstanceRestriction.GetExpression () inline package
Definition at line 183 of file BindingRestrictions.cs.
        {
            if (_instance == null)
            {
                return Expression.Equal(Expression.Convert(_expression, typeof(object)), System.Linq.Expressions.Utils.Null);
            }
            ParameterExpression parameterExpression = Expression.Parameter(typeof(object), null);
            return Expression.Block(new TrueReadOnlyCollection<ParameterExpression>(parameterExpression), new TrueReadOnlyCollection<Expression>(Expression.Assign(parameterExpression, Expression.Constant(_instance, typeof(object))), Expression.AndAlso(Expression.NotEqual(parameterExpression, System.Linq.Expressions.Utils.Null), Expression.Equal(Expression.Convert(_expression, typeof(object)), parameterExpression))));
        }
References System.Dynamic.BindingRestrictions.InstanceRestriction._expression, System.Dynamic.BindingRestrictions.InstanceRestriction._instance, System.Linq.Expressions.Expression< TDelegate >.AndAlso(), System.Linq.Expressions.Expression< TDelegate >.Assign(), System.Linq.Expressions.Expression< TDelegate >.Block(), System.Linq.Expressions.Expression< TDelegate >.Constant(), System.Linq.Expressions.Expression< TDelegate >.Convert(), System.Linq.Expressions.Expression< TDelegate >.Equal(), System.Linq.Expressions.Expression< TDelegate >.NotEqual(), System.Linq.Expressions.Utils.Null, and System.Linq.Expressions.Expression< TDelegate >.Parameter().