Terraria: System.Xml.Serialization.StructModel.GetPropertyModel
GetPropertyModel()
FieldModel System.Xml.Serialization.StructModel.GetPropertyModel (PropertyInfo propertyInfo) inline private
Definition at line 93 of file StructModel.cs.
    {
        if (propertyInfo.DeclaringType != base.Type)
        {
            return null;
        }
        if (CheckPropertyRead(propertyInfo))
        {
            TypeDesc typeDesc = base.ModelScope.TypeScope.GetTypeDesc(propertyInfo.PropertyType, propertyInfo, directReference: true, throwOnError: false);
            if (!propertyInfo.CanWrite && typeDesc.Kind != TypeKind.Collection && typeDesc.Kind != TypeKind.Enumerable)
            {
                return null;
            }
            CheckSupportedMember(typeDesc, propertyInfo, propertyInfo.PropertyType);
            return new FieldModel(propertyInfo, propertyInfo.PropertyType, typeDesc);
        }
        return null;
    }
References System.Reflection.PropertyInfo.CanWrite, System.Xml.Serialization.StructModel.CheckPropertyRead(), System.Xml.Serialization.StructModel.CheckSupportedMember(), System.Reflection.MemberInfo.DeclaringType, System.Xml.Dictionary, and System.Reflection.PropertyInfo.PropertyType.
Referenced by System.Xml.Serialization.StructModel.GetFieldModel().