Terraria: System.Xml.Serialization.StructModel.CheckSupportedMember
CheckSupportedMember()
void System.Xml.Serialization.StructModel.CheckSupportedMember (TypeDesc typeDesc, MemberInfo member, Type type) inline private
Definition at line 54 of file StructModel.cs.
    {
        if (typeDesc == null)
        {
            return;
        }
        if (typeDesc.IsUnsupported)
        {
            if (typeDesc.Exception == null)
            {
                typeDesc.Exception = new NotSupportedException(System.SR.Format(System.SR.XmlSerializerUnsupportedType, typeDesc.FullName));
            }
            throw new InvalidOperationException(System.SR.Format(System.SR.XmlSerializerUnsupportedMember, member.DeclaringType.FullName + "." + member.Name, type.FullName), typeDesc.Exception);
        }
        CheckSupportedMember(typeDesc.BaseTypeDesc, member, type);
        CheckSupportedMember(typeDesc.ArrayElementTypeDesc, member, type);
    }
References System.Xml.Serialization.StructModel.CheckSupportedMember(), System.Reflection.MemberInfo.DeclaringType, System.Xml.Dictionary, System.SR.Format(), System.Type.FullName, System.Reflection.MemberInfo.Name, System.type, System.SR.XmlSerializerUnsupportedMember, and System.SR.XmlSerializerUnsupportedType.
Referenced by System.Xml.Serialization.StructModel.CheckSupportedMember(), System.Xml.Serialization.StructModel.GetFieldModel(), and System.Xml.Serialization.StructModel.GetPropertyModel().