Terraria: System.Linq.Expressions.Compiler.CompilerScope.ElementBoxStorage.EmitLoadBox
EmitLoadBox()
void System.Linq.Expressions.Compiler.CompilerScope.ElementBoxStorage.EmitLoadBox () inline package
Definition at line 147 of file CompilerScope.cs.
        {
            _array.EmitLoad();
            Compiler.IL.EmitPrimitive(_index);
            Compiler.IL.Emit(OpCodes.Ldelem_Ref);
            Compiler.IL.Emit(OpCodes.Castclass, _boxType);
        }
References System.Linq.Expressions.Compiler.CompilerScope.ElementBoxStorage._array, System.Linq.Expressions.Compiler.CompilerScope.ElementBoxStorage._boxType, System.Linq.Expressions.Compiler.CompilerScope.ElementBoxStorage._index, System.Reflection.Emit.OpCodes.Castclass, System.Linq.Expressions.Compiler.CompilerScope.Storage.EmitLoad(), and System.Reflection.Emit.OpCodes.Ldelem_Ref.
Referenced by System.Linq.Expressions.Compiler.CompilerScope.ElementBoxStorage.EmitAddress(), System.Linq.Expressions.Compiler.CompilerScope.ElementBoxStorage.EmitLoad(), System.Linq.Expressions.Compiler.CompilerScope.ElementBoxStorage.EmitStore(), and System.Linq.Expressions.Compiler.CompilerScope.ElementBoxStorage.EmitStore().