Terraria: System.Text.Json.Serialization.Metadata.JsonPropertyInfo.DetermineNumberHandlingForProperty
DetermineNumberHandlingForProperty()
void System.Text.Json.Serialization.Metadata.JsonPropertyInfo< T >.DetermineNumberHandlingForProperty (JsonNumberHandling? propertyNumberHandling, JsonNumberHandling? declaringTypeNumberHandling) inline package
Definition at line 237 of file JsonPropertyInfo.cs.
    {
        if (NumberHandingIsApplicable())
        {
            JsonNumberHandling? numberHandling = propertyNumberHandling ?? declaringTypeNumberHandling;
            if (!numberHandling.HasValue && Options.NumberHandling != 0)
            {
                numberHandling = Options.NumberHandling;
            }
            NumberHandling = numberHandling;
        }
        else if (propertyNumberHandling.HasValue && propertyNumberHandling != JsonNumberHandling.Strict)
        {
            ThrowHelper.ThrowInvalidOperationException_NumberHandlingOnPropertyInvalid(this);
        }
    }
References System.Text.Json.Dictionary, System.Text.Json.Serialization.Metadata.JsonPropertyInfo< T >.NumberHandingIsApplicable(), System.Text.Json.Serialization.Metadata.JsonPropertyInfo< T >.NumberHandling, System.Text.Json.JsonSerializerOptions.NumberHandling, System.Text.Json.Serialization.Metadata.JsonPropertyInfo< T >.Options, and System.Text.Json.ThrowHelper.ThrowInvalidOperationException_NumberHandlingOnPropertyInvalid().
Referenced by System.Text.Json.Serialization.Metadata.JsonPropertyInfo< T >.GetPolicies(), and System.Text.Json.Serialization.Metadata.JsonPropertyInfo< T >.InitializeForSourceGen().