Terraria: System.Text.Json.Serialization.Metadata.JsonPropertyInfo.ReadJsonAndSetMember
ReadJsonAndSetMember() [2/2]
override bool System.Text.Json.Serialization.Metadata.JsonPropertyInfo< T >.ReadJsonAndSetMember (object obj, ref ReadStack state, ref Utf8JsonReader reader) inline package
Definition at line 588 of file JsonPropertyInfo.cs.
    {
        bool flag = reader.TokenType == JsonTokenType.Null;
        bool flag2;
        if (flag && !Converter.HandleNullOnRead && !state.IsContinuation)
        {
            if (!base.PropertyTypeCanBeNull)
            {
                ThrowHelper.ThrowJsonException_DeserializeUnableToConvertValue(Converter.TypeToConvert);
            }
            if (!base.IgnoreDefaultValuesOnRead)
            {
                Set(obj, default(T));
            }
            flag2 = true;
        }
        else if (Converter.CanUseDirectReadOrWrite && !state.Current.NumberHandling.HasValue)
        {
            if (!flag || !base.IgnoreDefaultValuesOnRead || !base.PropertyTypeCanBeNull)
            {
                T arg = Converter.Read(ref reader, base.RuntimePropertyType, base.Options);
                Set(obj, arg);
            }
            flag2 = true;
        }
        else
        {
            flag2 = true;
            if (!flag || !base.IgnoreDefaultValuesOnRead || !base.PropertyTypeCanBeNull || state.IsContinuation)
            {
                flag2 = Converter.TryRead(ref reader, base.RuntimePropertyType, base.Options, ref state, out var value);
                if (flag2)
                {
                    if (_converterIsExternalAndPolymorphic)
                    {
                        if (value != null)
{
                            Type type = value.GetType();
                            if (!base.DeclaredPropertyType.IsAssignableFrom(type))
{
                                ThrowHelper.ThrowInvalidCastException_DeserializeUnableToAssignValue(type, base.DeclaredPropertyType);
                            }
                        }
                        else if (!base.PropertyTypeCanBeNull)
{
                            ThrowHelper.ThrowInvalidOperationException_DeserializeUnableToAssignNull(base.DeclaredPropertyType);
                        }
                    }
                    Set(obj, value);
                }
            }
        }
        return flag2;
    }
References System.Text.Json.Serialization.Metadata.JsonPropertyInfo< T >._converterIsExternalAndPolymorphic, System.Text.Json.Serialization.Metadata.JsonPropertyInfo< T >.Converter, System.Text.Json.Dictionary, System.Type.GetType(), System.obj, System.Text.Json.Serialization.Metadata.JsonPropertyInfo< T >.Set, System.state, System.Text.Json.ThrowHelper.ThrowInvalidCastException_DeserializeUnableToAssignValue(), System.Text.Json.ThrowHelper.ThrowInvalidOperationException_DeserializeUnableToAssignNull(), System.Text.Json.ThrowHelper.ThrowJsonException_DeserializeUnableToConvertValue(), System.type, and System.value.