Terraria: System.Text.Json.Serialization.Metadata.JsonPropertyInfo.DetermineIgnoreCondition
DetermineIgnoreCondition()
void System.Text.Json.Serialization.Metadata.JsonPropertyInfo< T >.DetermineIgnoreCondition (JsonIgnoreCondition? ignoreCondition) inline package
Definition at line 180 of file JsonPropertyInfo.cs.
    {
        if (ignoreCondition.HasValue)
        {
            if (ignoreCondition == JsonIgnoreCondition.WhenWritingDefault)
            {
                IgnoreDefaultValuesOnWrite = true;
            }
            else if (ignoreCondition == JsonIgnoreCondition.WhenWritingNull)
            {
                if (PropertyTypeCanBeNull)
                {
                    IgnoreDefaultValuesOnWrite = true;
                }
                else
                {
                    ThrowHelper.ThrowInvalidOperationException_IgnoreConditionOnValueTypeInvalid(ClrName, DeclaringType);
                }
            }
        }
        else if (Options.IgnoreNullValues)
        {
            if (PropertyTypeCanBeNull)
            {
                IgnoreDefaultValuesOnRead = true;
                IgnoreDefaultValuesOnWrite = true;
            }
        }
        else if (Options.DefaultIgnoreCondition == JsonIgnoreCondition.WhenWritingNull)
        {
            if (PropertyTypeCanBeNull)
            {
                IgnoreDefaultValuesOnWrite = true;
            }
        }
        else if (Options.DefaultIgnoreCondition == JsonIgnoreCondition.WhenWritingDefault)
        {
            IgnoreDefaultValuesOnWrite = true;
        }
    }
References System.Text.Json.Serialization.Metadata.JsonPropertyInfo< T >.ClrName, System.Text.Json.Serialization.Metadata.JsonPropertyInfo< T >.DeclaringType, System.Text.Json.JsonSerializerOptions.DefaultIgnoreCondition, System.Text.Json.Serialization.Metadata.JsonPropertyInfo< T >.IgnoreDefaultValuesOnRead, System.Text.Json.Serialization.Metadata.JsonPropertyInfo< T >.IgnoreDefaultValuesOnWrite, System.Text.Json.JsonSerializerOptions.IgnoreNullValues, System.Text.Json.Serialization.Metadata.JsonPropertyInfo< T >.Options, System.Text.Json.Serialization.Metadata.JsonPropertyInfo< T >.PropertyTypeCanBeNull, and System.Text.Json.ThrowHelper.ThrowInvalidOperationException_IgnoreConditionOnValueTypeInvalid().
Referenced by System.Text.Json.Serialization.Metadata.JsonPropertyInfo< T >.GetPolicies(), and System.Text.Json.Serialization.Metadata.JsonPropertyInfo< T >.InitializeForSourceGen().