Terraria: System.Text.Json.Serialization.Metadata.JsonPropertyInfo.DeterminePropertyName
DeterminePropertyName()
void System.Text.Json.Serialization.Metadata.JsonPropertyInfo< T >.DeterminePropertyName () inline private
Definition at line 132 of file JsonPropertyInfo.cs.
    {
        ClrName = MemberInfo.Name;
        JsonPropertyNameAttribute attribute = GetAttribute<JsonPropertyNameAttribute>(MemberInfo);
        if (attribute != null)
        {
            string name = attribute.Name;
            if (name == null)
            {
                ThrowHelper.ThrowInvalidOperationException_SerializerPropertyNameNull(DeclaringType, this);
            }
            NameAsString = name;
        }
        else if (Options.PropertyNamingPolicy != null)
        {
            string text = Options.PropertyNamingPolicy.ConvertName(MemberInfo.Name);
            if (text == null)
            {
                ThrowHelper.ThrowInvalidOperationException_SerializerPropertyNameNull(DeclaringType, this);
            }
            NameAsString = text;
        }
        else
        {
            NameAsString = MemberInfo.Name;
        }
        NameAsUtf8Bytes = Encoding.UTF8.GetBytes(NameAsString);
        EscapedNameSection = JsonHelpers.GetEscapedPropertyNameSection(NameAsUtf8Bytes, Options.Encoder);
    }
References System.Text.Json.Serialization.Metadata.JsonPropertyInfo< T >.ClrName, System.Text.Json.JsonNamingPolicy.ConvertName(), System.Text.Json.Serialization.Metadata.JsonPropertyInfo< T >.DeclaringType, System.Text.Json.Dictionary, System.Text.Json.JsonSerializerOptions.Encoder, System.Text.Json.Serialization.Metadata.JsonPropertyInfo< T >.EscapedNameSection, System.Text.Json.JsonHelpers.GetEscapedPropertyNameSection(), System.Reflection.MemberInfo.Name, System.Text.Json.Serialization.Metadata.JsonPropertyInfo< T >.NameAsString, System.Text.Json.Serialization.Metadata.JsonPropertyInfo< T >.NameAsUtf8Bytes, System.Text.Json.Serialization.Metadata.JsonPropertyInfo< T >.Options, System.Text.Json.JsonSerializerOptions.PropertyNamingPolicy, System.text, System.Text.Json.ThrowHelper.ThrowInvalidOperationException_SerializerPropertyNameNull(), and System.Text.Encoding.UTF8.
Referenced by System.Text.Json.Serialization.Metadata.JsonPropertyInfo< T >.GetPolicies().