Terraria: System.Text.Json.Serialization.Metadata.JsonPropertyInfo.ReadJsonAndAddExtensionProperty
ReadJsonAndAddExtensionProperty()
bool System.Text.Json.Serialization.Metadata.JsonPropertyInfo< T >.ReadJsonAndAddExtensionProperty (object obj, ref ReadStack state, ref Utf8JsonReader reader) inline package
Definition at line 294 of file JsonPropertyInfo.cs.
    {
        object valueAsObject = GetValueAsObject(obj);
        if (valueAsObject is IDictionary<string, object> dictionary)
        {
            if (reader.TokenType == JsonTokenType.Null)
            {
                dictionary[state.Current.JsonPropertyNameAsString] = null;
            }
            else
            {
                JsonConverter<object> jsonConverter = (JsonConverter<object>)GetDictionaryValueConverter(JsonTypeInfo.ObjectType);
                object value = jsonConverter.Read(ref reader, JsonTypeInfo.ObjectType, Options);
                dictionary[state.Current.JsonPropertyNameAsString] = value;
            }
        }
        else if (valueAsObject is IDictionary<string, JsonElement> dictionary2)
        {
            Type typeFromHandle = typeof(JsonElement);
            JsonConverter<JsonElement> jsonConverter2 = (JsonConverter<JsonElement>)GetDictionaryValueConverter(typeFromHandle);
            JsonElement value2 = jsonConverter2.Read(ref reader, typeFromHandle, Options);
            dictionary2[state.Current.JsonPropertyNameAsString] = value2;
        }
        else
        {
            ConverterBase.ReadElementAndSetProperty(valueAsObject, state.Current.JsonPropertyNameAsString, ref reader, Options, ref state);
        }
        return true;
        JsonConverter GetDictionaryValueConverter(Type dictionaryValueType)
        {
            JsonTypeInfo elementTypeInfo = RuntimeTypeInfo.ElementTypeInfo;
            if (elementTypeInfo != null)
            {
                return elementTypeInfo.PropertyInfoForTypeInfo.ConverterBase;
            }
            return Options.GetConverterInternal(dictionaryValueType);
        }
    }
References System.Text.Json.Serialization.Metadata.JsonPropertyInfo< T >.ConverterBase, System.dictionary, System.Text.Json.Dictionary, System.Text.Json.Serialization.Metadata.JsonTypeInfo< T >.ElementTypeInfo, System.Text.Json.JsonSerializerOptions.GetConverterInternal(), System.Text.Json.Serialization.Metadata.JsonPropertyInfo< T >.GetValueAsObject(), System.obj, System.Text.Json.Serialization.Metadata.JsonTypeInfo< T >.ObjectType, System.Text.Json.Serialization.Metadata.JsonPropertyInfo< T >.Options, System.Text.Json.Serialization.JsonConverter< T >.ReadElementAndSetProperty(), System.Text.Json.Serialization.Metadata.JsonPropertyInfo< T >.RuntimeTypeInfo, System.state, and System.value.