Terraria: System.Text.Json.Serialization.Metadata.JsonPropertyInfo.NumberHandingIsApplicable
NumberHandingIsApplicable()
bool System.Text.Json.Serialization.Metadata.JsonPropertyInfo< T >.NumberHandingIsApplicable () inline private
Definition at line 254 of file JsonPropertyInfo.cs.
    {
        if (ConverterBase.IsInternalConverterForNumberType)
        {
            return true;
        }
        Type type = ((ConverterBase.IsInternalConverter && ((ConverterStrategy)24 & ConverterStrategy) != 0) ? ConverterBase.ElementType : DeclaredPropertyType);
        type = Nullable.GetUnderlyingType(type) ?? type;
        if (!(type == typeof(byte)) && !(type == typeof(decimal)) && !(type == typeof(double)) && !(type == typeof(short)) && !(type == typeof(int)) && !(type == typeof(long)) && !(type == typeof(sbyte)) && !(type == typeof(float)) && !(type == typeof(ushort)) && !(type == typeof(uint)) && !(type == typeof(ulong)))
        {
            return type == JsonTypeInfo.ObjectType;
        }
        return true;
    }
References System.Text.Json.Serialization.Metadata.JsonPropertyInfo< T >.ConverterBase, System.Text.Json.Serialization.Metadata.JsonPropertyInfo< T >.ConverterStrategy, System.Text.Json.Serialization.Metadata.JsonPropertyInfo< T >.DeclaredPropertyType, System.Text.Json.Dictionary, System.Text.Json.Serialization.JsonConverter< T >.ElementType, System.Nullable< T >.GetUnderlyingType(), System.Text.Json.Serialization.JsonConverter< T >.IsInternalConverterForNumberType, System.Text.Json.Serialization.Metadata.JsonTypeInfo< T >.ObjectType, and System.type.
Referenced by System.Text.Json.Serialization.Metadata.JsonPropertyInfo< T >.DetermineNumberHandlingForProperty(), and System.Text.Json.Serialization.Metadata.JsonPropertyInfo< T >.DetermineNumberHandlingForTypeInfo().