Terraria: System.Text.Json.Serialization.Metadata.JsonPropertyInfo.InitializeForSourceGen
InitializeForSourceGen()
void System.Text.Json.Serialization.Metadata.JsonPropertyInfo< T >.InitializeForSourceGen (JsonSerializerOptions options, JsonPropertyInfoValues< T > propertyInfo) inline package
Definition at line 428 of file JsonPropertyInfo.cs.
    {
        base.Options = options;
        base.ClrName = propertyInfo.PropertyName;
        if (propertyInfo.JsonPropertyName != null)
        {
            base.NameAsString = propertyInfo.JsonPropertyName;
        }
        else if (options.PropertyNamingPolicy == null)
        {
            base.NameAsString = base.ClrName;
        }
        else
        {
            base.NameAsString = options.PropertyNamingPolicy.ConvertName(base.ClrName);
            if (base.NameAsString == null)
            {
                ThrowHelper.ThrowInvalidOperationException_SerializerPropertyNameNull(base.DeclaringType, this);
            }
        }
        if (base.NameAsUtf8Bytes == null)
        {
            byte[] array = (base.NameAsUtf8Bytes = Encoding.UTF8.GetBytes(base.NameAsString));
        }
        if (base.EscapedNameSection == null)
        {
            byte[] array = (base.EscapedNameSection = JsonHelpers.GetEscapedPropertyNameSection(base.NameAsUtf8Bytes, base.Options.Encoder));
        }
        base.SrcGen_IsPublic = propertyInfo.IsPublic;
        base.SrcGen_HasJsonInclude = propertyInfo.HasJsonInclude;
        base.SrcGen_IsExtensionData = propertyInfo.IsExtensionData;
        base.DeclaredPropertyType = typeof(T);
        JsonTypeInfo propertyTypeInfo = propertyInfo.PropertyTypeInfo;
        Type declaringType = propertyInfo.DeclaringType;
        JsonConverter jsonConverter = propertyInfo.Converter;
        if (jsonConverter == null)
        {
            jsonConverter = propertyTypeInfo.PropertyInfoForTypeInfo.ConverterBase as JsonConverter<T>;
            if (jsonConverter == null)
            {
                throw new InvalidOperationException(System.SR.Format(System.SR.ConverterForPropertyMustBeValid, declaringType, base.ClrName, typeof(T)));
            }
        }
        ConverterBase = jsonConverter;
        if (propertyInfo.IgnoreCondition == JsonIgnoreCondition.Always)
        {
            base.IsIgnored = true;
            return;
        }
        Get = propertyInfo.Getter;
        Set = propertyInfo.Setter;
        base.HasGetter = Get != null;
        base.HasSetter = Set != null;
        base.RuntimeTypeInfo = propertyTypeInfo;
        base.DeclaringType = declaringType;
        base.IgnoreCondition = propertyInfo.IgnoreCondition;
        base.MemberType = (propertyInfo.IsProperty ? MemberTypes.Property : MemberTypes.Field);
        _converterIsExternalAndPolymorphic = !ConverterBase.IsInternalConverter && base.DeclaredPropertyType != ConverterBase.TypeToConvert;
        base.PropertyTypeCanBeNull = typeof(T).CanBeNull();
        _propertyTypeEqualsTypeToConvert = ConverterBase.TypeToConvert == typeof(T);
        ConverterStrategy = Converter.ConverterStrategy;
        base.RuntimePropertyType = base.DeclaredPropertyType;
        DetermineIgnoreCondition(base.IgnoreCondition);
        DetermineNumberHandlingForProperty(propertyInfo.NumberHandling, null);
        DetermineSerializationCapabilities(base.IgnoreCondition);
    }
References System.Text.Json.Serialization.Metadata.JsonPropertyInfo< T >._converterIsExternalAndPolymorphic, System.Text.Json.Serialization.Metadata.JsonPropertyInfo< T >._propertyTypeEqualsTypeToConvert, System.array, System.Text.Json.Serialization.Metadata.JsonPropertyInfo< T >.Converter, System.Text.Json.Serialization.Metadata.JsonPropertyInfo< T >.ConverterBase, System.SR.ConverterForPropertyMustBeValid, System.Text.Json.Serialization.Metadata.JsonPropertyInfo< T >.DetermineIgnoreCondition(), System.Text.Json.Serialization.Metadata.JsonPropertyInfo< T >.DetermineNumberHandlingForProperty(), System.Text.Json.Serialization.Metadata.JsonPropertyInfo< T >.DetermineSerializationCapabilities(), System.Text.Json.Dictionary, System.SR.Format(), System.Text.Json.Serialization.Metadata.JsonPropertyInfo< T >.Get, System.Text.Json.JsonHelpers.GetEscapedPropertyNameSection(), System.options, System.Text.Json.Serialization.Metadata.JsonPropertyInfo< T >.Set, System.Text.Json.ThrowHelper.ThrowInvalidOperationException_SerializerPropertyNameNull(), System.Text.Json.Serialization.JsonConverter< T >.TypeToConvert, and System.Text.Encoding.UTF8.