Terraria: System.Text.GB18030Encoding.GetBytes
GetBytes() [2/9]
unsafe override int System.Text.GB18030Encoding.GetBytes (char * chars, int charCount, byte * bytes, int byteCount, System::Text::EncoderNLS encoder) inline virtual
Reimplemented from System.Text.DBCSCodePageEncoding.
Definition at line 146 of file GB18030Encoding.cs.
    {
        char c = '\0';
        if (encoder != null)
        {
            c = encoder.charLeftOver;
        }
        EncodingByteBuffer encodingByteBuffer = new EncodingByteBuffer(this, encoder, bytes, byteCount, chars, charCount);
        while (true)
        {
            if (encodingByteBuffer.MoreData)
            {
                char nextChar = encodingByteBuffer.GetNextChar();
                if (c != 0)
                {
                    if (!char.IsLowSurrogate(nextChar))
                    {
                        encodingByteBuffer.MovePrevious(bThrow: false);
                        if (encodingByteBuffer.Fallback(c))
{
                            c = '\0';
                            continue;
                        }
                        c = '\0';
                    }
                    else
                    {
                        int num = (c - 55296 << 10) + (nextChar - 56320);
                        byte b = (byte)(num % 10 + 48);
                        num /= 10;
                        byte b2 = (byte)(num % 126 + 129);
                        num /= 126;
                        byte b3 = (byte)(num % 10 + 48);
                        num /= 10;
                        c = '\0';
                        if (encodingByteBuffer.AddByte((byte)(num + 144), b3, b2, b))
{
                            c = '\0';
                            continue;
                        }
                        encodingByteBuffer.MovePrevious(bThrow: false);
                    }
                }
                else if (nextChar <= '\u007f')
                {
                    if (encodingByteBuffer.AddByte((byte)nextChar))
                    {
                        continue;
                    }
                }
                else
                {
                    if (char.IsHighSurrogate(nextChar))
                    {
                        c = nextChar;
                        continue;
                    }
                    if (char.IsLowSurrogate(nextChar))
                    {
                        if (encodingByteBuffer.Fallback(nextChar))
{
                            continue;
                        }
                    }
                    else
                    {
                        ushort num2 = mapUnicodeToBytes[(int)nextChar];
                        if (Is4Byte(nextChar))
{
                            byte b4 = (byte)(num2 % 10 + 48);
                            num2 /= 10;
                            byte b5 = (byte)(num2 % 126 + 129);
                            num2 /= 126;
                            byte b6 = (byte)(num2 % 10 + 48);
                            num2 /= 10;
                            if (encodingByteBuffer.AddByte((byte)(num2 + 129), b6, b5, b4))
{
                                continue;
                            }
                        }
                        else if (encodingByteBuffer.AddByte((byte)(num2 >> 8), (byte)(num2 & 0xFFu)))
{
                            continue;
                        }
                    }
                }
            }
            if ((encoder != null && !encoder.MustFlush) || c <= '\0')
            {
                break;
            }
            encodingByteBuffer.Fallback(c);
            c = '\0';
        }
        if (encoder != null)
        {
            if (bytes != null)
            {
                encoder.charLeftOver = c;
            }
            encoder.m_charsUsed = encodingByteBuffer.CharsUsed;
        }
        return encodingByteBuffer.Count;
    }
References System.Text.Encoding.EncodingByteBuffer.AddByte(), System.byteCount, System.bytes, System.charCount, System.chars, System.Text.Encoding.EncodingByteBuffer.CharsUsed, System.Text.Encoding.EncodingByteBuffer.Count, System.Text.Encoding.EncodingByteBuffer.GetNextChar(), System.Text.GB18030Encoding.Is4Byte(), System.Text.DBCSCodePageEncoding.mapUnicodeToBytes, System.Text.Encoding.EncodingByteBuffer.MoreData, and System.Text.Encoding.EncodingByteBuffer.MovePrevious().
Referenced by System.Text.GB18030Encoding.GetByteCount().