Terraria: System.Threading.ProcessorIdCache.ProcessorNumberSpeedCheck
ProcessorNumberSpeedCheck()
static bool System.Threading.ProcessorIdCache.ProcessorNumberSpeedCheck () inline static package
Definition at line 35 of file ProcessorIdCache.cs.
    {
        double num = double.MaxValue;
        double num2 = double.MaxValue;
        UninlinedThreadStatic();
        if (Thread.GetCurrentProcessorNumber() < 0)
        {
            s_processorIdRefreshRate = 65535;
            return false;
        }
        long num3 = Stopwatch.Frequency / 1000000 + 1;
        for (int i = 0; i < 10; i++)
        {
            int num4 = 8;
            long timestamp;
            do
            {
                num4 *= 2;
                timestamp = Stopwatch.GetTimestamp();
                for (int j = 0; j < num4; j++)
                {
                    Thread.GetCurrentProcessorNumber();
                }
                timestamp = Stopwatch.GetTimestamp() - timestamp;
            }
            while (timestamp < num3);
            num = Math.Min(num, (double)timestamp / (double)num4);
            num4 /= 4;
            do
            {
                num4 *= 2;
                timestamp = Stopwatch.GetTimestamp();
                for (int k = 0; k < num4; k++)
                {
                    UninlinedThreadStatic();
                }
                timestamp = Stopwatch.GetTimestamp() - timestamp;
            }
            while (timestamp < num3);
            num2 = Math.Min(num2, (double)timestamp / (double)num4);
        }
        s_processorIdRefreshRate = Math.Min((int)(num * 5.0 / num2), 5000);
        return s_processorIdRefreshRate <= 5;
    }
References System.Threading.Thread.GetCurrentProcessorNumber(), System.Diagnostics.Stopwatch.GetTimestamp(), System.Math.Min(), System.Threading.ProcessorIdCache.s_processorIdRefreshRate, and System.Threading.ProcessorIdCache.UninlinedThreadStatic().