Terraria: Terraria.GameContent.RGB.MartianMadnessShader.ProcessLowDetail
ProcessLowDetail()
void Terraria.GameContent.RGB.MartianMadnessShader.ProcessLowDetail (RgbDevice device, Fragment fragment, EffectDetailLevel quality, float time) inline private
    {
        for (int i = 0; i < fragment.Count; i++)
        {
            Vector2 canvasPositionOfIndex = fragment.GetCanvasPositionOfIndex(i);
            Point gridPositionOfIndex = fragment.GetGridPositionOfIndex(i);
            float amount = (float)Math.Sin(time * 2f + canvasPositionOfIndex.X * 5f) * 0.5f + 0.5f;
            int num = (gridPositionOfIndex.X + gridPositionOfIndex.Y) % 2;
            if (num < 0)
            {
                num += 2;
            }
            Vector4 vector = ((num == 1) ? Vector4.Lerp(_glassColor, _beamColor, amount) : _metalColor);
            fragment.SetColor(i, vector);
        }
    }
References Terraria.GameContent.RGB.MartianMadnessShader._beamColor, Terraria.GameContent.RGB.MartianMadnessShader._glassColor, Terraria.GameContent.RGB.MartianMadnessShader._metalColor, ReLogic.Peripherals.RGB.Fragment.Count, ReLogic.Peripherals.RGB.Fragment.GetCanvasPositionOfIndex(), ReLogic.Peripherals.RGB.Fragment.GetGridPositionOfIndex(), and ReLogic.Peripherals.RGB.Fragment.SetColor().
Referenced by Terraria.GameContent.RGB.MartianMadnessShader.ProcessHighDetail().