Terraria: Terraria.GameContent.RGB.MartianMadnessShader.ProcessHighDetail
ProcessHighDetail()
void Terraria.GameContent.RGB.MartianMadnessShader.ProcessHighDetail (RgbDevice device, Fragment fragment, EffectDetailLevel quality, float time) inline private
Definition at line 44 of file MartianMadnessShader.cs.
    {
        //IL_0001: Unknown result type (might be due to invalid IL or missing references)
        //IL_0009: Unknown result type (might be due to invalid IL or missing references)
        //IL_000f: Invalid comparison between Unknown and I4
        //IL_0014: Unknown result type (might be due to invalid IL or missing references)
        if ((int)device.Type != 0 && (int)device.Type != 6)
        {
            ProcessLowDetail(device, fragment, quality, time);
            return;
        }
        float num = time * 0.5f % ((float)Math.PI * 2f);
        if (num > (float)Math.PI)
        {
            num = (float)Math.PI * 2f - num;
        }
        Vector2 vector = new Vector2(1.7f + (float)Math.Cos(num) * 2f, -0.5f + (float)Math.Sin(num) * 1.1f);
        for (int i = 0; i < fragment.Count; i++)
        {
            Vector2 canvasPositionOfIndex = fragment.GetCanvasPositionOfIndex(i);
            Vector4 vector2 = _backgroundColor;
            float num2 = Math.Abs(vector.X - canvasPositionOfIndex.X);
            if (canvasPositionOfIndex.Y > vector.Y && num2 < 0.2f)
            {
                float num3 = 1f - MathHelper.Clamp((num2 - 0.2f + 0.2f) / 0.2f, 0f, 1f);
                float num4 = Math.Abs((num - (float)Math.PI / 2f) / ((float)Math.PI / 2f));
                num4 = Math.Max(0f, 1f - num4 * 3f);
                vector2 = Vector4.Lerp(vector2, _beamColor, num3 * num4);
            }
            Vector2 vector3 = vector - canvasPositionOfIndex;
            vector3.X /= 1f;
            vector3.Y /= 0.2f;
            float num5 = vector3.Length();
            if (num5 < 1f)
            {
                float amount = 1f - MathHelper.Clamp((num5 - 1f + 0.2f) / 0.2f, 0f, 1f);
                vector2 = Vector4.Lerp(vector2, _metalColor, amount);
            }
            Vector2 vector4 = vector - canvasPositionOfIndex + new Vector2(0f, -0.1f);
            vector4.X /= 0.3f;
            vector4.Y /= 0.3f;
            if (vector4.Y < 0f)
            {
                vector4.Y *= 2f;
            }
            float num6 = vector4.Length();
            if (num6 < 1f)
            {
                float amount2 = 1f - MathHelper.Clamp((num6 - 1f + 0.2f) / 0.2f, 0f, 1f);
                vector2 = Vector4.Lerp(vector2, _glassColor, amount2);
            }
            fragment.SetColor(i, vector2);
        }
    }
References Terraria.GameContent.RGB.MartianMadnessShader._backgroundColor, Terraria.GameContent.RGB.MartianMadnessShader._beamColor, Terraria.GameContent.RGB.MartianMadnessShader._glassColor, Terraria.GameContent.RGB.MartianMadnessShader._metalColor, System.Math.Abs(), Microsoft.Xna.Framework.MathHelper.Clamp(), System.Math.Cos(), ReLogic.Peripherals.RGB.Fragment.Count, ReLogic.Peripherals.RGB.Fragment.GetCanvasPositionOfIndex(), Microsoft.Xna.Framework.Vector2.Length(), Microsoft.Xna.Framework.Vector4.Lerp(), System.Math.Max(), System.Math.PI, Terraria.GameContent.RGB.MartianMadnessShader.ProcessLowDetail(), ReLogic.Peripherals.RGB.Fragment.SetColor(), System.Math.Sin(), ReLogic.Peripherals.RGB.RgbDevice.Type, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.