Terraria: System.Net.CookieCollection.InternalAdd
InternalAdd()
int System.Net.CookieCollection.InternalAdd (Cookie cookie, bool isStrict) inline package
Definition at line 148 of file CookieCollection.cs.
    {
        int result = 1;
        if (isStrict)
        {
            int num = 0;
            int count = m_list.Count;
            for (int i = 0; i < count; i++)
            {
                Cookie cookie2 = (Cookie)m_list[i];
                if (CookieComparer.Compare(cookie, cookie2) == 0)
                {
                    result = 0;
                    if (cookie2.Variant <= cookie.Variant)
                    {
                        m_list[num] = cookie;
                    }
                    break;
                }
                num++;
            }
            if (num == m_list.Count)
            {
                m_list.Add(cookie);
            }
        }
        else
        {
            m_list.Add(cookie);
        }
        if (cookie.Version != 1)
        {
            m_has_other_versions = true;
        }
        return result;
    }
References System.Collections.ArrayList.Add(), System.Net.CookieComparer.Compare(), System.Net.Cookie, System.count, System.Collections.ArrayList.Count, System.Runtime.Serialization.Dictionary, System.Net.CookieCollection.m_has_other_versions, and System.Net.CookieCollection.m_list.
Referenced by System.Net.HttpListenerResponse.SetCookie().