Terraria: System.Xml.Schema.AxisElement.MoveToChild
MoveToChild()
bool System.Xml.Schema.AxisElement.MoveToChild (string name, string URN, int depth, ForwardAxis parent) inline package
Definition at line 48 of file AxisElement.cs.
    {
        if (Asttree.IsAttribute(curNode))
        {
            return false;
        }
        if (isMatch)
        {
            isMatch = false;
        }
        if (!AxisStack.Equal(curNode.Name, curNode.Urn, name, URN))
        {
            return false;
        }
        if (curDepth == -1)
        {
            SetDepth(depth);
        }
        else if (depth > curDepth)
        {
            return false;
        }
        if (curNode == parent.TopNode)
        {
            isMatch = true;
            return true;
        }
        DoubleLinkAxis ast = (DoubleLinkAxis)curNode.Next;
        if (Asttree.IsAttribute(ast))
        {
            isMatch = true;
            return false;
        }
        curNode = ast;
        curDepth++;
        return false;
    }
References System.Xml.Schema.AxisElement.curDepth, System.Xml.Schema.AxisElement.curNode, System.Xml.Dictionary, System.Xml.Schema.AxisStack.Equal(), System.Xml.Schema.Asttree.IsAttribute(), System.Xml.Schema.AxisElement.isMatch, MS.Internal.Xml.XPath.Axis.Name, System.Xml.Schema.DoubleLinkAxis.Next, System.Xml.Schema.AxisElement.SetDepth(), System.Xml.Schema.ForwardAxis.TopNode, and MS.Internal.Xml.XPath.Axis.Urn.