Terraria: System.Text.Encodings.Web.OptimizedInboxTextEncoder.AsciiPreescapedData.PopulatePreescapedData
PopulatePreescapedData()
unsafe void System.Text.Encodings.Web.OptimizedInboxTextEncoder.AsciiPreescapedData.PopulatePreescapedData (in AllowedBmpCodePointsBitmap allowedCodePointsBmp, ScalarEscaperBase innerEncoder) inline package
Definition at line 55 of file OptimizedInboxTextEncoder.cs.
        {
            this = default(AsciiPreescapedData);
            byte* intPtr = stackalloc byte[16];
            // IL initblk instruction
            Unsafe.InitBlock(intPtr, 0, 16);
            Span<char> span = new Span<char>(intPtr, 8);
            Span<char> span2 = span;
            for (int i = 0; i < 128; i++)
            {
                Rune value = new Rune(i);
                ulong num;
                int num2;
                if (!Rune.IsControl(value) && allowedCodePointsBmp.IsCharAllowed((char)i))
                {
                    num = (uint)i;
                    num2 = 1;
                }
                else
                {
                    num2 = innerEncoder.EncodeUtf16(value, span2.Slice(0, 6));
                    num = 0uL;
                    span2.Slice(num2).Clear();
                    for (int num3 = num2 - 1; num3 >= 0; num3--)
                    {
                        uint num4 = span2[num3];
                        num = (num << 8) | num4;
                    }
                }
                Data[i] = num | ((ulong)(uint)num2 << 56);
            }
        }
References System.Text.Encodings.Web.ScalarEscaperBase.EncodeUtf16(), System.Runtime.CompilerServices.Unsafe.InitBlock(), System.Text.Rune.IsControl(), System.Span< T >.Slice(), and System.Text.Encodings.Web.value.
Referenced by System.Text.Encodings.Web.OptimizedInboxTextEncoder.OptimizedInboxTextEncoder().