Terraria: System.Reflection.CustomAttributeTypedArgument.CustomAttributeTypedArgument
CustomAttributeTypedArgument() [1/3]
System.Reflection.CustomAttributeTypedArgument.CustomAttributeTypedArgument (RuntimeModule scope, CustomAttributeEncodedArgument encodedArg) inline package
Definition at line 71 of file CustomAttributeTypedArgument.cs.
    {
        CustomAttributeEncoding encodedType = encodedArg.CustomAttributeType.EncodedType;
        switch (encodedType)
        {
        case CustomAttributeEncoding.Undefined:
            throw new ArgumentException(null, "encodedArg");
        case CustomAttributeEncoding.Enum:
            _argumentType = ResolveType(scope, encodedArg.CustomAttributeType.EnumName);
            _value = EncodedValueToRawValue(encodedArg.PrimitiveValue, encodedArg.CustomAttributeType.EncodedEnumType);
            break;
        case CustomAttributeEncoding.String:
            _argumentType = typeof(string);
            _value = encodedArg.StringValue;
            break;
        case CustomAttributeEncoding.Type:
            _argumentType = typeof(Type);
            _value = null;
            if (encodedArg.StringValue != null)
            {
                _value = ResolveType(scope, encodedArg.StringValue);
            }
            break;
        case CustomAttributeEncoding.Array:
        {
            encodedType = encodedArg.CustomAttributeType.EncodedArrayType;
            Type type = ((encodedType != CustomAttributeEncoding.Enum) ? CustomAttributeEncodingToType(encodedType) : ResolveType(scope, encodedArg.CustomAttributeType.EnumName));
            _argumentType = type.MakeArrayType();
            if (encodedArg.ArrayValue == null)
            {
                _value = null;
                break;
            }
            CustomAttributeTypedArgument[] array = new CustomAttributeTypedArgument[encodedArg.ArrayValue.Length];
            for (int i = 0; i < array.Length; i++)
            {
                array[i] = new CustomAttributeTypedArgument(scope, encodedArg.ArrayValue[i]);
            }
            _value = Array.AsReadOnly(array);
            break;
        }
        default:
            _argumentType = CustomAttributeEncodingToType(encodedType);
            _value = EncodedValueToRawValue(encodedArg.PrimitiveValue, encodedType);
            break;
        }
    }
References System.Reflection.CustomAttributeTypedArgument.CustomAttributeTypedArgument(), System.Reflection.CustomAttributeTypedArgument._argumentType, System.Reflection.CustomAttributeTypedArgument._value, System.array, System.Reflection.CustomAttributeTypedArgument.CustomAttributeEncodingToType(), System.Reflection.CustomAttributeTypedArgument.EncodedValueToRawValue(), System.Type.MakeArrayType(), System.Reflection.CustomAttributeTypedArgument.ResolveType(), and System.type.
Referenced by System.Reflection.CustomAttributeTypedArgument.CustomAttributeTypedArgument().