Terraria: Terraria.GameContent.UI.Elements.UIClothStyleButton.DrawSelf
DrawSelf()
override void Terraria.GameContent.UI.Elements.UIClothStyleButton.DrawSelf (SpriteBatch spriteBatch) inline protected virtual
Reimplemented from Terraria.UI.UIElement.
    {
        if (_hovered)
        {
            if (!_soundedHover)
            {
                SoundEngine.PlaySound(12);
            }
            _soundedHover = true;
        }
        else
        {
            _soundedHover = false;
        }
        CalculatedStyle dimensions = GetDimensions();
        Utils.DrawSplicedPanel(spriteBatch, _BasePanelTexture.Value, (int)dimensions.X, (int)dimensions.Y, (int)dimensions.Width, (int)dimensions.Height, 10, 10, 10, 10, Color.White * 0.5f);
        if (_realSkinVariant == ClothStyleId)
        {
            Utils.DrawSplicedPanel(spriteBatch, _selectedBorderTexture.Value, (int)dimensions.X + 3, (int)dimensions.Y + 3, (int)dimensions.Width - 6, (int)dimensions.Height - 6, 10, 10, 10, 10, Color.White);
        }
        if (_hovered)
        {
            Utils.DrawSplicedPanel(spriteBatch, _hoveredBorderTexture.Value, (int)dimensions.X, (int)dimensions.Y, (int)dimensions.Width, (int)dimensions.Height, 10, 10, 10, 10, Color.White);
        }
    }
References Terraria.GameContent.UI.Elements.UIClothStyleButton._BasePanelTexture, Terraria.GameContent.UI.Elements.UIClothStyleButton._hovered, Terraria.GameContent.UI.Elements.UIClothStyleButton._hoveredBorderTexture, Terraria.GameContent.UI.Elements.UIClothStyleButton._realSkinVariant, Terraria.GameContent.UI.Elements.UIClothStyleButton._selectedBorderTexture, Terraria.GameContent.UI.Elements.UIClothStyleButton._soundedHover, Terraria.GameContent.UI.Elements.UIClothStyleButton.ClothStyleId, Terraria.Utils.DrawSplicedPanel(), Terraria.UI.UIElement.GetDimensions(), Terraria.Audio.SoundEngine.PlaySound(), and ReLogic.Content.Asset< T >.Value.