Terraria: System.Threading.SpinWait.SpinOnce
SpinOnce() [1/2]
void System.Threading.SpinWait.SpinOnce () inline
Definition at line 33 of file SpinWait.cs.
    {
        SpinOnceCore(20);
    }
References System.Threading.SpinWait.SpinOnceCore().
Referenced by System.Threading.Barrier.AddParticipants(), System.Threading.Tasks.ParallelLoopStateFlags.AtomicLoopStateUpdate(), System.Threading.Tasks.ParallelLoopState.Break(), System.Threading.Tasks.ParallelLoopState.Break(), System.Net.Sockets.SafeSocketHandle.CloseAsIs(), System.IO.Pipes.NamedPipeClientStream.ConnectInternal(), System.Threading.SpinLock.ContinueTryEnter(), System.Threading.SpinLock.ContinueTryEnterWithThreadTracking(), System.Threading.SpinLock.DecrementWaiters(), System.IO.MemoryMappedFiles.MemoryMappedView.Flush(), System.Lazy< T, TMetadata >.PublicationOnlyWaitForOtherThreadToPublish(), System.Threading.Barrier.RemoveParticipants(), System.Threading.CountdownEvent.Signal(), System.Threading.Barrier.SignalAndWait(), System.Threading.SpinWait.SpinUntil(), System.Threading.CountdownEvent.TryAddCount(), System.Collections.Concurrent.ConcurrentQueueSegment< T >.TryDequeue(), System.Collections.Concurrent.ConcurrentQueueSegment< T >.TryPeek(), System.Threading.ManualResetEventSlim.UpdateStateAtomically(), System.Threading.ManualResetEventSlim.Wait(), System.Threading.SemaphoreSlim.Wait(), System.Threading.Barrier.WaitCurrentPhase(), and System.Net.LazyAsyncResult.WaitForCompletion().