Terraria: System.ComponentModel.PropertyDescriptor.RemoveValueChanged
RemoveValueChanged()
virtual void System.ComponentModel.PropertyDescriptor.RemoveValueChanged (object component, EventHandler handler) inline virtual inherited
Reimplemented in System.ComponentModel.DataAnnotations.MetadataPropertyDescriptorWrapper, MS.Internal.Xml.Linq.ComponentModel.XPropertyDescriptor< T, TProperty >, and System.ComponentModel.ReflectPropertyDescriptor.
Definition at line 275 of file PropertyDescriptor.cs.
    {
        if (component == null)
        {
            throw new ArgumentNullException("component");
        }
        if (handler == null)
        {
            throw new ArgumentNullException("handler");
        }
        if (_valueChangedHandlers != null)
        {
            EventHandler source = (EventHandler)_valueChangedHandlers[component];
            source = (EventHandler)Delegate.Remove(source, handler);
            if (source != null)
            {
                _valueChangedHandlers[component] = source;
            }
            else
            {
                _valueChangedHandlers.Remove(component);
            }
        }
    }
References System.ComponentModel.PropertyDescriptor._valueChangedHandlers, System.EventHandler(), System.Delegate.Remove(), System.Collections.Hashtable.Remove(), and System.source.
Referenced by System.ComponentModel.DataAnnotations.MetadataPropertyDescriptorWrapper.RemoveValueChanged().