Terraria: System.ComponentModel.PropertyDescriptor.GetValue
GetValue() [2/2]
object? System.ComponentModel.PropertyDescriptor.GetValue (object? component) abstract inherited
Referenced by Terraria.Localization.LocalizedText.CanFormatWith(), System.ComponentModel.TypeConverter.SimplePropertyDescriptor.CanResetValue(), Terraria.Localization.LocalizedText.FormatWith(), System.ComponentModel.Design.DesignerOptionService.GetOptionValue(), System.ComponentModel.DataAnnotations.MetadataPropertyDescriptorWrapper.GetValue(), and System.ComponentModel.Design.DesignerOptionService.DesignerOptionCollection.WrappedPropertyDescriptor.GetValue().