Terraria: System.ComponentModel.PropertyDescriptor.GetTypeFromName
GetTypeFromName()
Type? System.ComponentModel.PropertyDescriptor.GetTypeFromName ([DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicConstructors)] string? typeName) inline protected inherited
Definition at line 245 of file PropertyDescriptor.cs.
    {
        if (typeName == null || typeName.Length == 0)
        {
            return null;
        }
        Type type = Type.GetType(typeName);
        Type type2 = null;
        if (ComponentType != null && (type == null || ComponentType.Assembly.FullName.Equals(type.Assembly.FullName)))
        {
            int num = typeName.IndexOf(',');
            if (num != -1)
            {
                typeName = typeName.Substring(0, num);
            }
            type2 = ComponentType.Assembly.GetType(typeName);
        }
        return type2 ?? type;
    }
References System.Type.Assembly, System.ComponentModel.PropertyDescriptor.ComponentType, System.Reflection.Assembly.FullName, System.Reflection.Assembly.GetType(), System.Type.GetType(), and System.type.
Referenced by System.ComponentModel.PropertyDescriptor.GetEditor().