Terraria: System.ComponentModel.PropertyDescriptor.GetEditor
GetEditor()
virtual ? object System.ComponentModel.PropertyDescriptor.GetEditor (Type editorBaseType) inline virtual inherited
Definition at line 171 of file PropertyDescriptor.cs.
    {
        object obj = null;
        AttributeCollection attributes = Attributes;
        if (_editorTypes != null)
        {
            for (int i = 0; i < _editorCount; i++)
            {
                if (_editorTypes[i] == editorBaseType)
                {
                    return _editors[i];
                }
            }
        }
        if (obj == null)
        {
            for (int j = 0; j < attributes.Count; j++)
            {
                if (!(attributes[j] is EditorAttribute editorAttribute))
                {
                    continue;
                }
                Type typeFromName = GetTypeFromName(editorAttribute.EditorBaseTypeName);
                if (editorBaseType == typeFromName)
                {
                    Type typeFromName2 = GetTypeFromName(editorAttribute.EditorTypeName);
                    if (typeFromName2 != null)
                    {
                        obj = CreateInstance(typeFromName2);
                        break;
                    }
                }
            }
            if (obj == null)
            {
                obj = TypeDescriptor.GetEditor(PropertyType, editorBaseType);
            }
            if (_editorTypes == null)
            {
                _editorTypes = new Type[5];
                _editors = new object[5];
            }
            if (_editorCount >= _editorTypes.Length)
            {
                Type[] array = new Type[_editorTypes.Length * 2];
                object[] array2 = new object[_editors.Length * 2];
                Array.Copy(_editorTypes, array, _editorTypes.Length);
                Array.Copy(_editors, array2, _editors.Length);
                _editorTypes = array;
                _editors = array2;
            }
            _editorTypes[_editorCount] = editorBaseType;
            _editors[_editorCount++] = obj;
        }
        return obj;
    }
References System.ComponentModel.PropertyDescriptor._editorCount, System.ComponentModel.PropertyDescriptor._editors, System.ComponentModel.PropertyDescriptor._editorTypes, System.array, System.ComponentModel.MemberDescriptor.Attributes, System.Array.Copy(), System.ComponentModel.AttributeCollection.Count, System.Reflection.CreateInstance, System.ComponentModel.TypeDescriptor.GetEditor(), System.ComponentModel.PropertyDescriptor.GetTypeFromName(), System.obj, and System.ComponentModel.PropertyDescriptor.PropertyType.