Terraria: System.ComponentModel.PropertyDescriptor.AddValueChanged
AddValueChanged()
virtual void System.ComponentModel.PropertyDescriptor.AddValueChanged (object component, EventHandler handler) inline virtual inherited
Reimplemented in System.ComponentModel.DataAnnotations.MetadataPropertyDescriptorWrapper, MS.Internal.Xml.Linq.ComponentModel.XPropertyDescriptor< T, TProperty >, and System.ComponentModel.ReflectPropertyDescriptor.
Definition at line 79 of file PropertyDescriptor.cs.
    {
        if (component == null)
        {
            throw new ArgumentNullException("component");
        }
        if (handler == null)
        {
            throw new ArgumentNullException("handler");
        }
        if (_valueChangedHandlers == null)
        {
            _valueChangedHandlers = new Hashtable();
        }
        EventHandler a = (EventHandler)_valueChangedHandlers[component];
        _valueChangedHandlers[component] = Delegate.Combine(a, handler);
    }
References System.ComponentModel.PropertyDescriptor._valueChangedHandlers, System.Delegate.Combine(), and System.EventHandler().
Referenced by System.ComponentModel.DataAnnotations.MetadataPropertyDescriptorWrapper.AddValueChanged().