Terraria: Terraria.GameContent.Skies.StardustSky.Draw
Draw()
override void Terraria.GameContent.Skies.StardustSky.Draw (SpriteBatch spriteBatch, float minDepth, float maxDepth) inline
Definition at line 69 of file StardustSky.cs.
    {
        if (maxDepth >= float.MaxValue && minDepth < float.MaxValue)
        {
            spriteBatch.Draw(TextureAssets.BlackTile.Value, new Rectangle(0, 0, Main.screenWidth, Main.screenHeight), Color.Black * _fadeOpacity);
            spriteBatch.Draw(_bgTexture.Value, new Rectangle(0, Math.Max(0, (int)((Main.worldSurface * 16.0 - (double)Main.screenPosition.Y - 2400.0) * 0.10000000149011612)), Main.screenWidth, Main.screenHeight), Color.White * Math.Min(1f, (Main.screenPosition.Y - 800f) / 1000f * _fadeOpacity));
            Vector2 vector = new Vector2(Main.screenWidth >> 1, Main.screenHeight >> 1);
            Vector2 vector2 = 0.01f * (new Vector2((float)Main.maxTilesX * 8f, (float)Main.worldSurface / 2f) - Main.screenPosition);
            spriteBatch.Draw(_planetTexture.Value, vector + new Vector2(-200f, -200f) + vector2, null, Color.White * 0.9f * _fadeOpacity, 0f, new Vector2(_planetTexture.Width() >> 1, _planetTexture.Height() >> 1), 1f, SpriteEffects.None, 1f);
        }
        int num = -1;
        int num2 = 0;
        for (int i = 0; i < _stars.Length; i++)
        {
            float depth = _stars[i].Depth;
            if (num == -1 && depth < maxDepth)
            {
                num = i;
            }
            if (depth <= minDepth)
            {
                break;
            }
            num2 = i;
        }
        if (num == -1)
        {
            return;
        }
        float num3 = Math.Min(1f, (Main.screenPosition.Y - 1000f) / 1000f);
        Vector2 vector3 = Main.screenPosition + new Vector2(Main.screenWidth >> 1, Main.screenHeight >> 1);
        Rectangle rectangle = new Rectangle(-1000, -1000, 4000, 4000);
        for (int j = num; j < num2; j++)
        {
            Vector2 vector4 = new Vector2(1f / _stars[j].Depth, 1.1f / _stars[j].Depth);
            Vector2 position = (_stars[j].Position - vector3) * vector4 + vector3 - Main.screenPosition;
            if (rectangle.Contains((int)position.X, (int)position.Y))
            {
                float value = (float)Math.Sin(_stars[j].AlphaFrequency * Main.GlobalTimeWrappedHourly + _stars[j].SinOffset) * _stars[j].AlphaAmplitude + _stars[j].AlphaAmplitude;
                float num4 = (float)Math.Sin(_stars[j].AlphaFrequency * Main.GlobalTimeWrappedHourly * 5f + _stars[j].SinOffset) * 0.1f - 0.1f;
                value = MathHelper.Clamp(value, 0f, 1f);
                Texture2D value2 = _starTextures[_stars[j].TextureIndex].Value;
                spriteBatch.Draw(value2, position, null, Color.White * num3 * value * 0.8f * (1f - num4) * _fadeOpacity, 0f, new Vector2(value2.Width >> 1, value2.Height >> 1), (vector4.X * 0.5f + 0.5f) * (value * 0.3f + 0.7f), SpriteEffects.None, 0f);
            }
        }
    }
References Terraria.GameContent.Skies.StardustSky._bgTexture, Terraria.GameContent.Skies.StardustSky._fadeOpacity, Terraria.GameContent.Skies.StardustSky._planetTexture, Terraria.GameContent.Skies.StardustSky._stars, Terraria.GameContent.Skies.StardustSky._starTextures, Terraria.GameContent.Skies.StardustSky.Star.AlphaAmplitude, Terraria.GameContent.Skies.StardustSky.Star.AlphaFrequency, Microsoft.Xna.Framework.Color.Black, Terraria.GameContent.TextureAssets.BlackTile, Microsoft.Xna.Framework.MathHelper.Clamp(), Microsoft.Xna.Framework.Rectangle.Contains(), Microsoft.Xna.Framework.Graphics.Depth, Terraria.GameContent.Skies.StardustSky.Star.Depth, Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(), Terraria.Main.GlobalTimeWrappedHourly, Microsoft.Xna.Framework.Graphics.Texture2D.Height, System.Math.Max(), Terraria.Main.maxTilesX, System.Math.Min(), Terraria.GameContent.Skies.StardustSky.Star.Position, Terraria.Main.screenHeight, Terraria.Main.screenPosition, Terraria.Main.screenWidth, System.Math.Sin(), Terraria.GameContent.Skies.StardustSky.Star.SinOffset, Terraria.GameContent.Skies.StardustSky.Star.TextureIndex, ReLogic.Content.Asset< T >.Value, System.value, Microsoft.Xna.Framework.Graphics.Vector2, Microsoft.Xna.Framework.Color.White, Microsoft.Xna.Framework.Graphics.Texture2D.Width, Terraria.Main.worldSurface, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.