Terraria: System.Linq.Parallel.QueryOperator.ExecuteAndGetResultsAsArray
ExecuteAndGetResultsAsArray()
TOutput[] System.Linq.Parallel.QueryOperator< TOutput >.ExecuteAndGetResultsAsArray () inline package inherited
Definition at line 77 of file QueryOperator.cs.
    {
        QuerySettings querySettings = base.SpecifiedQuerySettings.WithPerExecutionSettings().WithDefaults();
        QueryLifecycle.LogicalQueryExecutionBegin(querySettings.QueryId);
        try
        {
            if (querySettings.ExecutionMode.Value == ParallelExecutionMode.Default && LimitsParallelism)
            {
                IEnumerable<TOutput> source = AsSequentialQuery(querySettings.CancellationState.ExternalCancellationToken);
                IEnumerable<TOutput> source2 = CancellableEnumerable.Wrap(source, querySettings.CancellationState.ExternalCancellationToken);
                return ExceptionAggregator.WrapEnumerable(source2, querySettings.CancellationState).ToArray();
            }
            QueryResults<TOutput> queryResults = GetQueryResults(querySettings);
            if (querySettings.CancellationState.MergedCancellationToken.IsCancellationRequested)
            {
                querySettings.CancellationState.ExternalCancellationToken.ThrowIfCancellationRequested();
                throw new OperationCanceledException();
            }
            if (queryResults.IsIndexible && OutputOrdered)
            {
                ArrayMergeHelper<TOutput> arrayMergeHelper = new ArrayMergeHelper<TOutput>(base.SpecifiedQuerySettings, queryResults);
                arrayMergeHelper.Execute();
                TOutput[] resultsAsArray = arrayMergeHelper.GetResultsAsArray();
                querySettings.CleanStateAtQueryEnd();
                return resultsAsArray;
            }
            PartitionedStreamMerger<TOutput> partitionedStreamMerger = new PartitionedStreamMerger<TOutput>(forEffectMerge: false, ParallelMergeOptions.FullyBuffered, querySettings.TaskScheduler, OutputOrdered, querySettings.CancellationState, querySettings.QueryId);
            queryResults.GivePartitionedStream(partitionedStreamMerger);
            TOutput[] resultsAsArray2 = partitionedStreamMerger.MergeExecutor.GetResultsAsArray();
            querySettings.CleanStateAtQueryEnd();
            return resultsAsArray2;
        }
        finally
        {
            QueryLifecycle.LogicalQueryExecutionEnd(querySettings.QueryId);
        }
    }
References System.Linq.Parallel.QueryOperator< TOutput >.AsSequentialQuery(), System.Linq.Parallel.QueryOperator< TOutput >.GetQueryResults(), System.Linq.Parallel.QueryOperator< TOutput >.LimitsParallelism, System.Linq.Parallel.QueryLifecycle.LogicalQueryExecutionBegin(), System.Linq.Parallel.QueryLifecycle.LogicalQueryExecutionEnd(), System.Linq.Parallel.QueryOperator< TOutput >.OutputOrdered, and System.Linq.source.