Terraria: System.Linq.Parallel.QueryOperator.GetOpenedEnumerator
GetOpenedEnumerator()
IEnumerator< TOutput > System.Linq.Parallel.QueryOperator< TOutput >.GetOpenedEnumerator (ParallelMergeOptions? mergeOptions, bool suppressOrder, bool forEffect, QuerySettings querySettings) inline package inherited
Definition at line 45 of file QueryOperator.cs.
    {
        if (querySettings.ExecutionMode.Value == ParallelExecutionMode.Default && LimitsParallelism)
        {
            IEnumerable<TOutput> source = AsSequentialQuery(querySettings.CancellationState.ExternalCancellationToken);
            return ExceptionAggregator.WrapEnumerable(source, querySettings.CancellationState).GetEnumerator();
        }
        QueryResults<TOutput> queryResults = GetQueryResults(querySettings);
        if (!mergeOptions.HasValue)
        {
            mergeOptions = querySettings.MergeOptions;
        }
        if (querySettings.CancellationState.MergedCancellationToken.IsCancellationRequested)
        {
            querySettings.CancellationState.ExternalCancellationToken.ThrowIfCancellationRequested();
            throw new OperationCanceledException();
        }
        bool outputOrdered = OutputOrdered && !suppressOrder;
        PartitionedStreamMerger<TOutput> partitionedStreamMerger = new PartitionedStreamMerger<TOutput>(forEffect, mergeOptions.GetValueOrDefault(), querySettings.TaskScheduler, outputOrdered, querySettings.CancellationState, querySettings.QueryId);
        queryResults.GivePartitionedStream(partitionedStreamMerger);
        if (forEffect)
        {
            return null;
        }
        return partitionedStreamMerger.MergeExecutor.GetEnumerator();
    }
References System.Linq.Parallel.QueryOperator< TOutput >.AsSequentialQuery(), System.Collections.Generic.Dictionary< TKey, TValue >.GetEnumerator(), System.Linq.Parallel.QueryOperator< TOutput >.GetQueryResults(), System.Linq.Parallel.QueryOperator< TOutput >.LimitsParallelism, System.Linq.Parallel.QueryOperator< TOutput >.OutputOrdered, and System.Linq.source.