Terraria: System.Security.Cryptography.X509Certificates.Asn1.TbsCertificateAsn.DecodeCore
DecodeCore()
static void System.Security.Cryptography.X509Certificates.Asn1.TbsCertificateAsn.DecodeCore (ref System::Formats::Asn1::AsnValueReader reader, Asn1Tag expectedTag, ReadOnlyMemory< byte > rebind, out TbsCertificateAsn decoded) inline static private
Definition at line 114 of file TbsCertificateAsn.cs.
    {
        decoded = default(TbsCertificateAsn);
        System.Formats.Asn1.AsnValueReader reader2 = reader.ReadSequence(expectedTag);
        ReadOnlySpan<byte> span = rebind.Span;
        System.Formats.Asn1.AsnValueReader asnValueReader;
        if (reader2.HasData && reader2.PeekTag().HasSameClassAndValue(new Asn1Tag(TagClass.ContextSpecific, 0)))
        {
            asnValueReader = reader2.ReadSequence(new Asn1Tag(TagClass.ContextSpecific, 0));
            if (!asnValueReader.TryReadInt32(out decoded.Version))
            {
                asnValueReader.ThrowIfNotEmpty();
            }
            asnValueReader.ThrowIfNotEmpty();
        }
        else
        {
            System.Formats.Asn1.AsnValueReader asnValueReader2 = new System.Formats.Asn1.AsnValueReader(DefaultVersion, AsnEncodingRules.DER);
            if (!asnValueReader2.TryReadInt32(out decoded.Version))
            {
                asnValueReader2.ThrowIfNotEmpty();
            }
        }
        ReadOnlySpan<byte> value = reader2.ReadIntegerBytes();
        decoded.SerialNumber = (span.Overlaps(value, out var elementOffset) ? rebind.Slice(elementOffset, value.Length) : ((ReadOnlyMemory<byte>)value.ToArray()));
        System.Security.Cryptography.Asn1.AlgorithmIdentifierAsn.Decode(ref reader2, rebind, out decoded.SignatureAlgorithm);
        if (!reader2.PeekTag().HasSameClassAndValue(new Asn1Tag(UniversalTagNumber.Sequence)))
        {
            throw new CryptographicException();
        }
        value = reader2.ReadEncodedValue();
        decoded.Issuer = (span.Overlaps(value, out elementOffset) ? rebind.Slice(elementOffset, value.Length) : ((ReadOnlyMemory<byte>)value.ToArray()));
        ValidityAsn.Decode(ref reader2, rebind, out decoded.Validity);
        if (!reader2.PeekTag().HasSameClassAndValue(new Asn1Tag(UniversalTagNumber.Sequence)))
        {
            throw new CryptographicException();
        }
        value = reader2.ReadEncodedValue();
        decoded.Subject = (span.Overlaps(value, out elementOffset) ? rebind.Slice(elementOffset, value.Length) : ((ReadOnlyMemory<byte>)value.ToArray()));
        System.Security.Cryptography.Asn1.SubjectPublicKeyInfoAsn.Decode(ref reader2, rebind, out decoded.SubjectPublicKeyInfo);
        int unusedBitCount;
        if (reader2.HasData && reader2.PeekTag().HasSameClassAndValue(new Asn1Tag(TagClass.ContextSpecific, 1)))
        {
            if (reader2.TryReadPrimitiveBitString(out unusedBitCount, out value, new Asn1Tag(TagClass.ContextSpecific, 1)))
            {
                decoded.IssuerUniqueId = (span.Overlaps(value, out elementOffset) ? rebind.Slice(elementOffset, value.Length) : ((ReadOnlyMemory<byte>)value.ToArray()));
            }
            else
            {
                decoded.IssuerUniqueId = reader2.ReadBitString(out unusedBitCount, new Asn1Tag(TagClass.ContextSpecific, 1));
            }
        }
        if (reader2.HasData && reader2.PeekTag().HasSameClassAndValue(new Asn1Tag(TagClass.ContextSpecific, 2)))
        {
            if (reader2.TryReadPrimitiveBitString(out unusedBitCount, out value, new Asn1Tag(TagClass.ContextSpecific, 2)))
            {
                decoded.SubjectUniqueId = (span.Overlaps(value, out elementOffset) ? rebind.Slice(elementOffset, value.Length) : ((ReadOnlyMemory<byte>)value.ToArray()));
            }
            else
            {
                decoded.SubjectUniqueId = reader2.ReadBitString(out unusedBitCount, new Asn1Tag(TagClass.ContextSpecific, 2));
            }
        }
        if (reader2.HasData && reader2.PeekTag().HasSameClassAndValue(new Asn1Tag(TagClass.ContextSpecific, 3)))
        {
            asnValueReader = reader2.ReadSequence(new Asn1Tag(TagClass.ContextSpecific, 3));
            System.Formats.Asn1.AsnValueReader reader3 = asnValueReader.ReadSequence();
            List<X509ExtensionAsn> list = new List<X509ExtensionAsn>();
            while (reader3.HasData)
            {
                X509ExtensionAsn.Decode(ref reader3, rebind, out var decoded2);
                list.Add(decoded2);
            }
            decoded.Extensions = list.ToArray();
            asnValueReader.ThrowIfNotEmpty();
        }
        reader2.ThrowIfNotEmpty();
    }
References System.Security.Cryptography.Asn1.AlgorithmIdentifierAsn.Decode(), System.Security.Cryptography.Asn1.SubjectPublicKeyInfoAsn.Decode(), System.Security.Cryptography.X509Certificates.Asn1.ValidityAsn.Decode(), System.Security.Cryptography.Asn1.X509ExtensionAsn.Decode(), System.Security.Cryptography.X509Certificates.Asn1.TbsCertificateAsn.DefaultVersion, System.list, and System.value.
Referenced by System.Security.Cryptography.X509Certificates.Asn1.TbsCertificateAsn.Decode().