Terraria: System.Security.Cryptography.X509Certificates.Asn1.TbsCertificateAsn.Encode
Encode() [1/2]
void System.Security.Cryptography.X509Certificates.Asn1.TbsCertificateAsn.Encode (AsnWriter writer) inline package
Definition at line 31 of file TbsCertificateAsn.cs.
    {
        Encode(writer, Asn1Tag.Sequence);
    }
References System.Security.Cryptography.X509Certificates.Asn1.TbsCertificateAsn.Encode(), System.Formats.Asn1.Asn1Tag.Sequence, and System.writer.
Referenced by System.Security.Cryptography.X509Certificates.Asn1.TbsCertificateAsn.Encode(), and System.Security.Cryptography.X509Certificates.Asn1.CertificateAsn.Encode().