Terraria: System.Security.Cryptography.X509Certificates.Asn1.TbsCertificateAsn.Encode
Encode() [2/2]
void System.Security.Cryptography.X509Certificates.Asn1.TbsCertificateAsn.Encode (AsnWriter writer, Asn1Tag tag) inline package
Definition at line 36 of file TbsCertificateAsn.cs.
    {
        writer.PushSequence(tag);
        AsnWriter asnWriter = new AsnWriter(AsnEncodingRules.DER);
        asnWriter.WriteInteger(Version);
        if (!asnWriter.EncodedValueEquals(DefaultVersion))
        {
            writer.PushSequence(new Asn1Tag(TagClass.ContextSpecific, 0));
            asnWriter.CopyTo(writer);
            writer.PopSequence(new Asn1Tag(TagClass.ContextSpecific, 0));
        }
        writer.WriteInteger(SerialNumber.Span);
        SignatureAlgorithm.Encode(writer);
        if (!Asn1Tag.TryDecode(Issuer.Span, out var tag2, out var bytesConsumed) || !tag2.HasSameClassAndValue(new Asn1Tag(UniversalTagNumber.Sequence)))
        {
            throw new CryptographicException();
        }
        try
        {
            writer.WriteEncodedValue(Issuer.Span);
        }
        catch (ArgumentException inner)
        {
            throw new CryptographicException(System.SR.Cryptography_Der_Invalid_Encoding, inner);
        }
        Validity.Encode(writer);
        if (!Asn1Tag.TryDecode(Subject.Span, out var tag3, out bytesConsumed) || !tag3.HasSameClassAndValue(new Asn1Tag(UniversalTagNumber.Sequence)))
        {
            throw new CryptographicException();
        }
        try
        {
            writer.WriteEncodedValue(Subject.Span);
        }
        catch (ArgumentException inner2)
        {
            throw new CryptographicException(System.SR.Cryptography_Der_Invalid_Encoding, inner2);
        }
        SubjectPublicKeyInfo.Encode(writer);
        if (IssuerUniqueId.HasValue)
        {
            writer.WriteBitString(IssuerUniqueId.Value.Span, 0, new Asn1Tag(TagClass.ContextSpecific, 1));
        }
        if (SubjectUniqueId.HasValue)
        {
            writer.WriteBitString(SubjectUniqueId.Value.Span, 0, new Asn1Tag(TagClass.ContextSpecific, 2));
        }
        if (Extensions != null)
        {
            writer.PushSequence(new Asn1Tag(TagClass.ContextSpecific, 3));
            writer.PushSequence();
            for (int i = 0; i < Extensions.Length; i++)
            {
                Extensions[i].Encode(writer);
            }
            writer.PopSequence();
            writer.PopSequence(new Asn1Tag(TagClass.ContextSpecific, 3));
        }
        writer.PopSequence(tag);
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.CopyTo(), System.SR.Cryptography_Der_Invalid_Encoding, System.Security.Cryptography.X509Certificates.Asn1.TbsCertificateAsn.DefaultVersion, System.Security.Cryptography.X509Certificates.Asn1.ValidityAsn.Encode(), System.Security.Cryptography.X509Certificates.Asn1.TbsCertificateAsn.Issuer, System.Security.Cryptography.X509Certificates.Asn1.TbsCertificateAsn.IssuerUniqueId, System.Security.Cryptography.X509Certificates.Asn1.TbsCertificateAsn.SerialNumber, System.Security.Cryptography.X509Certificates.Asn1.TbsCertificateAsn.SignatureAlgorithm, System.ReadOnlyMemory< T >.Span, System.Security.Cryptography.X509Certificates.Asn1.TbsCertificateAsn.Subject, System.Security.Cryptography.X509Certificates.Asn1.TbsCertificateAsn.SubjectPublicKeyInfo, System.Security.Cryptography.X509Certificates.Asn1.TbsCertificateAsn.SubjectUniqueId, System.Formats.Asn1.Asn1Tag.TryDecode(), System.Security.Cryptography.X509Certificates.Asn1.TbsCertificateAsn.Validity, and System.writer.