Terraria: Terraria.GameContent.DoorOpeningHelper.TallGateOpeningInfoProvider.TryCloseDoor
TryCloseDoor()
DoorCloseAttemptResult Terraria.GameContent.DoorOpeningHelper.TallGateOpeningInfoProvider.TryCloseDoor (DoorOpenCloseTogglingInfo info, PlayerInfoForClosingDoors playerInfo) inline
Implements Terraria.GameContent.DoorOpeningHelper.DoorAutoHandler.
Definition at line 187 of file DoorOpeningHelper.cs.
        {
            Point tileCoordsForToggling = info.tileCoordsForToggling;
            Tile tile = Main.tile[tileCoordsForToggling.X, tileCoordsForToggling.Y];
            if (!tile.active() || tile.type != 389)
            {
                return DoorCloseAttemptResult.DoorIsInvalidated;
            }
            _ = tile.frameY % 90 / 18;
            Rectangle value = new Rectangle(tileCoordsForToggling.X * 16, tileCoordsForToggling.Y * 16, 16, 80);
            value.Inflate(1, 0);
            Rectangle rectangle = Rectangle.Intersect(value, playerInfo.hitboxToNotCloseDoor);
            if (rectangle.Width > 0 || rectangle.Height > 0)
            {
                return DoorCloseAttemptResult.StillInDoorArea;
            }
            bool flag = true;
            if (WorldGen.ShiftTallGate(tileCoordsForToggling.X, tileCoordsForToggling.Y, flag))
            {
                NetMessage.SendData(13, -1, -1, null, Main.myPlayer);
                NetMessage.SendData(19, -1, -1, null, 4 + flag.ToInt(), tileCoordsForToggling.X, tileCoordsForToggling.Y);
                return DoorCloseAttemptResult.ClosedDoor;
            }
            return DoorCloseAttemptResult.FailedToCloseDoor;
        }
References Terraria.Tile.active(), Terraria.GameContent.DoorOpeningHelper.PlayerInfoForClosingDoors.hitboxToNotCloseDoor, Terraria.Main.myPlayer, Terraria.NetMessage.SendData(), Terraria.WorldGen.ShiftTallGate(), Terraria.Main.tile, Terraria.GameContent.DoorOpeningHelper.DoorOpenCloseTogglingInfo.tileCoordsForToggling, and Terraria.Tile.type.