Terraria: SimpleOverlay.Draw
Draw()
override void SimpleOverlay.Draw (SpriteBatch spriteBatch) inline virtual
Implements Overlay.
     {
         _shader.UseGlobalOpacity(Opacity);
         _shader.UseTargetPosition(TargetPosition);
         _shader.Apply();
         spriteBatch.Draw(_texture.Value, new Rectangle(0, 0, Main.screenWidth, Main.screenHeight), Main.ColorOfTheSkies);
     }
References _shader, _texture, ScreenShaderData.Apply(), Main.ColorOfTheSkies, GameEffect.Opacity, Main.screenHeight, Main.screenWidth, TargetPosition, ScreenShaderData.UseGlobalOpacity(), ScreenShaderData.UseTargetPosition(), and Asset< T >.Value.