Terraria: System.Buffers.StandardFormat.ParseHelper
ParseHelper()
static bool System.Buffers.StandardFormat.ParseHelper (ReadOnlySpan< char > format, out StandardFormat standardFormat, bool throws = false) inline static private
Definition at line 72 of file StandardFormat.cs.
    {
        standardFormat = default(StandardFormat);
        if (format.Length == 0)
        {
            return true;
        }
        char symbol = format[0];
        byte precision;
        if (format.Length == 1)
        {
            precision = byte.MaxValue;
        }
        else
        {
            uint num = 0u;
            for (int i = 1; i < format.Length; i++)
            {
                uint num2 = (uint)(format[i] - 48);
                if (num2 > 9)
                {
                    if (!throws)
                    {
                        return false;
                    }
                    throw new FormatException(SR.Format(SR.Argument_CannotParsePrecision, (byte)99));
                }
                num = num * 10 + num2;
                if (num > 99)
                {
                    if (!throws)
                    {
                        return false;
                    }
                    throw new FormatException(SR.Format(SR.Argument_PrecisionTooLarge, (byte)99));
                }
            }
            precision = (byte)num;
        }
        standardFormat = new StandardFormat(symbol, precision);
        return true;
    }
References System.Buffers.StandardFormat.StandardFormat(), System.SR.Argument_CannotParsePrecision, System.SR.Argument_PrecisionTooLarge, System.SR.Format(), and System.format.
Referenced by System.Buffers.StandardFormat.Parse(), and System.Buffers.StandardFormat.TryParse().