Terraria: System.Buffers.StandardFormat.Equals
Equals() [1/3]
override bool System.Buffers.StandardFormat.Equals ([NotNullWhen(true)] object? obj) inline
Definition at line 115 of file StandardFormat.cs.
    {
        if (obj is StandardFormat other)
        {
            return Equals(other);
        }
        return false;
    }
References System.Buffers.StandardFormat.Equals(), System.obj, and System.other.
Referenced by System.Buffers.StandardFormat.Equals(), System.Buffers.StandardFormat.operator!=(), and System.Buffers.StandardFormat.operator==().