Terraria: SelectionHolder.LoadContent
LoadContent()
void SelectionHolder< TCycleType >.LoadContent (AssetRequestMode mode) inline
     {
         //IL_0001: Unknown result type (might be due to invalid IL or missing references)
         PopulateOptionsAndLoadContent(mode);
         LoadedContent = true;
         SetActiveMinimapFromLoadedConfigKey();
     }
References SelectionHolder< TCycleType >.LoadedContent, SelectionHolder< TCycleType >.PopulateOptionsAndLoadContent(), and SelectionHolder< TCycleType >.SetActiveMinimapFromLoadedConfigKey().
Referenced by AssetInitializer.LoadTextures().