Terraria: System.Collections.Immutable.SortedInt32KeyNode.Mutate
Mutate()
SortedInt32KeyNode< TValue > System.Collections.Immutable.SortedInt32KeyNode< TValue >.Mutate (SortedInt32KeyNode< TValue > left = null, SortedInt32KeyNode< TValue > right = null) inline private
Definition at line 437 of file SortedInt32KeyNode.cs.
    {
        if (_frozen)
        {
            return new SortedInt32KeyNode<TValue>(_key, _value, left ?? _left, right ?? _right);
        }
        if (left != null)
        {
            _left = left;
        }
        if (right != null)
        {
            _right = right;
        }
        _height = checked((byte)(1 + Math.Max(_left._height, _right._height)));
        return this;
    }
References System.Collections.Immutable.SortedInt32KeyNode< TValue >._frozen, System.Collections.Immutable.SortedInt32KeyNode< TValue >._height, System.Collections.Immutable.SortedInt32KeyNode< TValue >._key, System.Collections.Immutable.SortedInt32KeyNode< TValue >._left, System.Collections.Immutable.SortedInt32KeyNode< TValue >._right, System.Collections.Immutable.SortedInt32KeyNode< TValue >._value, and System.Math.Max().
Referenced by System.Collections.Immutable.SortedInt32KeyNode< TValue >.RemoveRecursive(), and System.Collections.Immutable.SortedInt32KeyNode< TValue >.SetOrAdd().