Terraria: System.Collections.Immutable.SortedInt32KeyNode.RemoveRecursive
RemoveRecursive()
SortedInt32KeyNode< TValue > System.Collections.Immutable.SortedInt32KeyNode< TValue >.RemoveRecursive (int key, out bool mutated) inline private
Definition at line 379 of file SortedInt32KeyNode.cs.
    {
        if (IsEmpty)
        {
            mutated = false;
            return this;
        }
        SortedInt32KeyNode<TValue> sortedInt32KeyNode = this;
        if (key == _key)
        {
            mutated = true;
            if (_right.IsEmpty && _left.IsEmpty)
            {
                sortedInt32KeyNode = EmptyNode;
            }
            else if (_right.IsEmpty && !_left.IsEmpty)
            {
                sortedInt32KeyNode = _left;
            }
            else if (!_right.IsEmpty && _left.IsEmpty)
            {
                sortedInt32KeyNode = _right;
            }
            else
            {
                SortedInt32KeyNode<TValue> sortedInt32KeyNode2 = _right;
                while (!sortedInt32KeyNode2._left.IsEmpty)
                {
                    sortedInt32KeyNode2 = sortedInt32KeyNode2._left;
                }
                bool mutated2;
                SortedInt32KeyNode<TValue> right = _right.Remove(sortedInt32KeyNode2._key, out mutated2);
                sortedInt32KeyNode = sortedInt32KeyNode2.Mutate(_left, right);
            }
        }
        else if (key < _key)
        {
            SortedInt32KeyNode<TValue> left = _left.Remove(key, out mutated);
            if (mutated)
            {
                sortedInt32KeyNode = Mutate(left);
            }
        }
        else
        {
            SortedInt32KeyNode<TValue> right2 = _right.Remove(key, out mutated);
            if (mutated)
            {
                sortedInt32KeyNode = Mutate(null, right2);
            }
        }
        if (!sortedInt32KeyNode.IsEmpty)
        {
            return MakeBalanced(sortedInt32KeyNode);
        }
        return sortedInt32KeyNode;
    }
References System.Collections.Immutable.SortedInt32KeyNode< TValue >._key, System.Collections.Immutable.SortedInt32KeyNode< TValue >._left, System.Collections.Immutable.SortedInt32KeyNode< TValue >._right, System.Collections.Immutable.SortedInt32KeyNode< TValue >.EmptyNode, System.Collections.Immutable.SortedInt32KeyNode< TValue >.IsEmpty, System.key, System.Collections.Immutable.SortedInt32KeyNode< TValue >.MakeBalanced(), and System.Collections.Immutable.SortedInt32KeyNode< TValue >.Mutate().
Referenced by System.Collections.Immutable.SortedInt32KeyNode< TValue >.Remove().