Terraria: System.Collections.Immutable.SortedInt32KeyNode.SetOrAdd
SetOrAdd()
SortedInt32KeyNode< TValue > System.Collections.Immutable.SortedInt32KeyNode< TValue >.SetOrAdd (int key, TValue value, IEqualityComparer< TValue > valueComparer, bool overwriteExistingValue, out bool replacedExistingValue, out bool mutated) inline private
Definition at line 332 of file SortedInt32KeyNode.cs.
    {
        replacedExistingValue = false;
        if (IsEmpty)
        {
            mutated = true;
            return new SortedInt32KeyNode<TValue>(key, value, this, this);
        }
        SortedInt32KeyNode<TValue> sortedInt32KeyNode = this;
        if (key > _key)
        {
            SortedInt32KeyNode<TValue> right = _right.SetOrAdd(key, value, valueComparer, overwriteExistingValue, out replacedExistingValue, out mutated);
            if (mutated)
            {
                sortedInt32KeyNode = Mutate(null, right);
            }
        }
        else if (key < _key)
        {
            SortedInt32KeyNode<TValue> left = _left.SetOrAdd(key, value, valueComparer, overwriteExistingValue, out replacedExistingValue, out mutated);
            if (mutated)
            {
                sortedInt32KeyNode = Mutate(left);
            }
        }
        else
        {
            if (valueComparer.Equals(_value, value))
            {
                mutated = false;
                return this;
            }
            if (!overwriteExistingValue)
            {
                throw new ArgumentException(System.SR.Format(System.SR.DuplicateKey, key));
            }
            mutated = true;
            replacedExistingValue = true;
            sortedInt32KeyNode = new SortedInt32KeyNode<TValue>(key, value, _left, _right);
        }
        if (!mutated)
        {
            return sortedInt32KeyNode;
        }
        return MakeBalanced(sortedInt32KeyNode);
    }
References System.Collections.Immutable.SortedInt32KeyNode< TValue >._key, System.Collections.Immutable.SortedInt32KeyNode< TValue >._left, System.Collections.Immutable.SortedInt32KeyNode< TValue >._right, System.Collections.Immutable.SortedInt32KeyNode< TValue >._value, System.SR.DuplicateKey, System.SR.Format(), System.Collections.Immutable.SortedInt32KeyNode< TValue >.IsEmpty, System.key, System.Collections.Immutable.SortedInt32KeyNode< TValue >.MakeBalanced(), System.Collections.Immutable.SortedInt32KeyNode< TValue >.Mutate(), and System.value.
Referenced by System.Collections.Immutable.SortedInt32KeyNode< TValue >.SetItem().