Terraria: System.Collections.Immutable.SortedInt32KeyNode.RotateLeft
RotateLeft()
static SortedInt32KeyNode< TValue > System.Collections.Immutable.SortedInt32KeyNode< TValue >.RotateLeft (SortedInt32KeyNode< TValue > tree) inline static private
Definition at line 248 of file SortedInt32KeyNode.cs.
    {
        Requires.NotNull(tree, "tree");
        if (tree._right.IsEmpty)
        {
            return tree;
        }
        SortedInt32KeyNode<TValue> right = tree._right;
        return right.Mutate(tree.Mutate(null, right._left));
    }
Referenced by System.Collections.Immutable.SortedInt32KeyNode< TValue >.DoubleLeft(), System.Collections.Immutable.SortedInt32KeyNode< TValue >.DoubleRight(), and System.Collections.Immutable.SortedInt32KeyNode< TValue >.MakeBalanced().