Terraria: System.Runtime.Serialization.XsdDataContractExporter.CanExport
CanExport() [1/3]
bool System.Runtime.Serialization.XsdDataContractExporter.CanExport (ICollection< Assembly > assemblies) inline
Definition at line 268 of file XsdDataContractExporter.cs.
    {
        if (assemblies == null)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new ArgumentNullException("assemblies"));
        }
        DataContractSet dataContractSet = ((_dataContractSet == null) ? null : new DataContractSet(_dataContractSet));
        try
        {
            foreach (Assembly assembly in assemblies)
            {
                if (assembly == null)
                {
                    throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new ArgumentException(System.SR.Format(System.SR.CannotExportNullAssembly, "assemblies")));
                }
                Type[] types = assembly.GetTypes();
                for (int i = 0; i < types.Length; i++)
                {
                    CheckAndAddType(types[i]);
                }
            }
            AddKnownTypes();
            return true;
        }
        catch (InvalidDataContractException)
        {
            _dataContractSet = dataContractSet;
            return false;
        }
        catch (Exception exception)
        {
            _dataContractSet = dataContractSet;
            TraceExportError(exception);
            throw;
        }
    }
References System.Runtime.Serialization.XsdDataContractExporter._dataContractSet, System.Runtime.Serialization.XsdDataContractExporter.AddKnownTypes(), System.Xml.ArgumentException, System.SR.CannotExportNullAssembly, System.Runtime.Serialization.XsdDataContractExporter.CheckAndAddType(), System.Runtime.Serialization.XsdDataContractExporter.DataContractSet, System.Runtime.Serialization.Dictionary, System.exception, System.SR.Format(), System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperError(), and System.Runtime.Serialization.XsdDataContractExporter.TraceExportError().