Terraria: System.Runtime.Serialization.XsdDataContractExporter.AddKnownTypes
AddKnownTypes()
void System.Runtime.Serialization.XsdDataContractExporter.AddKnownTypes () inline private
Definition at line 245 of file XsdDataContractExporter.cs.
    {
        if (Options == null)
        {
            return;
        }
        Collection<Type> knownTypes = Options.KnownTypes;
        if (knownTypes == null)
        {
            return;
        }
        for (int i = 0; i < knownTypes.Count; i++)
        {
            Type type = knownTypes[i];
            if (type == null)
            {
                throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new ArgumentException(System.SR.CannotExportNullKnownType));
            }
            AddType(type);
        }
    }
References System.Runtime.Serialization.XsdDataContractExporter.AddType(), System.Xml.ArgumentException, System.SR.CannotExportNullKnownType, System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Runtime.Serialization.ExportOptions.KnownTypes, System.Runtime.Serialization.XsdDataContractExporter.Options, System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperError(), and System.type.
Referenced by System.Runtime.Serialization.XsdDataContractExporter.CanExport(), System.Runtime.Serialization.XsdDataContractExporter.CanExport(), System.Runtime.Serialization.XsdDataContractExporter.CanExport(), and System.Runtime.Serialization.XsdDataContractExporter.Export().