Terraria: System.Runtime.Serialization.XsdDataContractExporter.CanExport
CanExport() [3/3]
bool System.Runtime.Serialization.XsdDataContractExporter.CanExport (Type type) inline
Definition at line 340 of file XsdDataContractExporter.cs.
    {
        if (type == null)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new ArgumentNullException("type"));
        }
        DataContractSet dataContractSet = ((_dataContractSet == null) ? null : new DataContractSet(_dataContractSet));
        try
        {
            AddType(type);
            AddKnownTypes();
            return true;
        }
        catch (InvalidDataContractException)
        {
            _dataContractSet = dataContractSet;
            return false;
        }
        catch (Exception exception)
        {
            _dataContractSet = dataContractSet;
            TraceExportError(exception);
            throw;
        }
    }
References System.Runtime.Serialization.XsdDataContractExporter._dataContractSet, System.Runtime.Serialization.XsdDataContractExporter.AddKnownTypes(), System.Runtime.Serialization.XsdDataContractExporter.AddType(), System.Runtime.Serialization.XsdDataContractExporter.DataContractSet, System.Runtime.Serialization.Dictionary, System.exception, System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperError(), System.Runtime.Serialization.XsdDataContractExporter.TraceExportError(), and System.type.