Terraria: System.Runtime.Serialization.XsdDataContractExporter.AddType
AddType()
void System.Runtime.Serialization.XsdDataContractExporter.AddType (Type type) inline private
Definition at line 231 of file XsdDataContractExporter.cs.
    {
        DataContractSet.Add(type);
    }
References System.Runtime.Serialization.DataContractSet.Add(), and System.type.
Referenced by System.Runtime.Serialization.XsdDataContractExporter.AddKnownTypes(), System.Runtime.Serialization.XsdDataContractExporter.CanExport(), System.Runtime.Serialization.XsdDataContractExporter.CanExport(), System.Runtime.Serialization.XsdDataContractExporter.CheckAndAddType(), System.Runtime.Serialization.XsdDataContractExporter.Export(), and System.Runtime.Serialization.XsdDataContractExporter.Export().