namespace Microsoft.Xna.Framework;

internal enum KernelReturnCode : uint
{
	OutputBufferTooSmall = 2147746304u,
	TooManyPendingAsyncOperations,
	BeginEndPairDoesNotMatch,
	AsyncShutdown,
	TitleUpdate,
	ProFeatureNotSupported,
	ProfileNotSignedIn,
	ProfileNotPrivileged,
	GuideAlreadyVisible,
	NetworkError,
	PacketQueueFull,
	SessionAlreadyExists,
	SessionNotFound,
	SessionNotJoinable,
	SessionFull,
	StaleSearchResult,
	QualityOfServiceNotComplete,
	NotInvited,
	InviteeNotSignedIn,
	TrialMode,
	NetworkNotAvailable,
	LIVEn400BadRequest,
	LIVEn401Unauthorized,
	LIVEn500InternalServerError,
	LIVEn503ServiceUnavailable,
	LIVEnTitleUpdateRequired,
	LIVEnFlashUpdateRequired,
	LIVEnNotSupportedTitle,
	LIVEnAccountBanned,
	LIVEnAccountSuspended,
	LIVEnCountryNotSupported,
	LIVEnGamertagChangeRequired,
	LIVEnGamertagUpdateRequired,
	LIVEnXBLConnectionUnavailable,
	LIVEnUnexpectedNetworkError,
	LIVEnServiceNotProvisioned,
	LIVEnInvalidUser,
	LIVEnTermsOfServiceNotAccepted,
	LIVEnXBLNotEnabled,
	LIVEnNoXBLAccount,
	NetworkOperationTimedOut
}
