Terraria: System.Text.Json.Nodes.JsonValue.Create
Create() [1/35]
static JsonValue System.Text.Json.Nodes.JsonValue< TValue >.Create (bool value, JsonNodeOptions? options = null) inline static inherited
Definition at line 12 of file JsonValue.cs.
    {
        return new JsonValueTrimmable<bool>(value, JsonMetadataServices.BooleanConverter);
    }
References System.Text.Json.Serialization.Metadata.JsonMetadataServices.BooleanConverter, System.Text.Json.Dictionary, and System.value.
Referenced by System.Text.Json.Nodes.JsonNode.operator JsonNode(), System.Text.Json.Nodes.JsonNode.operator JsonNode(), System.Text.Json.Nodes.JsonNode.operator JsonNode(), System.Text.Json.Nodes.JsonNode.operator JsonNode(), System.Text.Json.Nodes.JsonNode.operator JsonNode(), System.Text.Json.Nodes.JsonNode.operator JsonNode(), System.Text.Json.Nodes.JsonNode.operator JsonNode(), System.Text.Json.Nodes.JsonNode.operator JsonNode(), System.Text.Json.Nodes.JsonNode.operator JsonNode(), System.Text.Json.Nodes.JsonNode.operator JsonNode(), System.Text.Json.Nodes.JsonNode.operator JsonNode(), System.Text.Json.Nodes.JsonNode.operator JsonNode(), System.Text.Json.Nodes.JsonNode.operator JsonNode(), System.Text.Json.Nodes.JsonNode.operator JsonNode(), System.Text.Json.Nodes.JsonNode.operator JsonNode(), System.Text.Json.Nodes.JsonNode.operator JsonNode(), System.Text.Json.Nodes.JsonNode.operator JsonNode?(), System.Text.Json.Nodes.JsonNode.operator JsonNode?(), System.Text.Json.Nodes.JsonNode.operator JsonNode?(), System.Text.Json.Nodes.JsonNode.operator JsonNode?(), System.Text.Json.Nodes.JsonNode.operator JsonNode?(), System.Text.Json.Nodes.JsonNode.operator JsonNode?(), System.Text.Json.Nodes.JsonNode.operator JsonNode?(), System.Text.Json.Nodes.JsonNode.operator JsonNode?(), System.Text.Json.Nodes.JsonNode.operator JsonNode?(), System.Text.Json.Nodes.JsonNode.operator JsonNode?(), System.Text.Json.Nodes.JsonNode.operator JsonNode?(), System.Text.Json.Nodes.JsonNode.operator JsonNode?(), System.Text.Json.Nodes.JsonNode.operator JsonNode?(), System.Text.Json.Nodes.JsonNode.operator JsonNode?(), System.Text.Json.Nodes.JsonNode.operator JsonNode?(), System.Text.Json.Nodes.JsonNode.operator JsonNode?(), and System.Text.Json.Nodes.JsonNode.operator JsonNode?().