Terraria: System.Transactions.CommittableTransaction.Commit
Commit()
void System.Transactions.CommittableTransaction.Commit () inline
Definition at line 98 of file CommittableTransaction.cs.
    {
        TransactionsEtwProvider log = TransactionsEtwProvider.Log;
        if (log.IsEnabled())
        {
            log.MethodEnter(TraceSourceType.TraceSourceLtm, this, "Commit");
            log.TransactionCommit(this, "CommittableTransaction");
        }
        if (base.Disposed)
        {
            throw new ObjectDisposedException("CommittableTransaction");
        }
        lock (_internalTransaction)
        {
            if (_complete)
            {
                throw TransactionException.CreateTransactionCompletedException(base.DistributedTxId);
            }
            _internalTransaction.State.BeginCommit(_internalTransaction, asyncCommit: false, null, null);
            while (!_internalTransaction.State.IsCompleted(_internalTransaction) && Monitor.Wait(_internalTransaction))
            {
            }
            _internalTransaction.State.EndCommit(_internalTransaction);
        }
        if (log.IsEnabled())
        {
            log.MethodExit(TraceSourceType.TraceSourceLtm, this, "Commit");
        }
    }
References System.Transactions.Transaction._complete, System.Transactions.Transaction._internalTransaction, System.Transactions.TransactionState.BeginCommit(), System.Transactions.TransactionException.CreateTransactionCompletedException(), System.Transactions.TransactionState.EndCommit(), System.Transactions.TransactionState.IsCompleted(), System.Diagnostics.Tracing.EventSource.IsEnabled(), System.Transactions.TransactionsEtwProvider.Log, System.Transactions.TransactionsEtwProvider.MethodEnter(), System.Transactions.TransactionsEtwProvider.MethodExit(), System.Transactions.InternalTransaction.State, System.Transactions.TransactionsEtwProvider.TransactionCommit(), and System.Threading.Monitor.Wait().
Referenced by System.Transactions.TransactionScope.InternalDispose().