Terraria: System.Transactions.CommittableTransaction.InternalDispose
InternalDispose()
override void System.Transactions.CommittableTransaction.InternalDispose () inline package virtual
Reimplemented from System.Transactions.Transaction.
Definition at line 128 of file CommittableTransaction.cs.
    {
        TransactionsEtwProvider log = TransactionsEtwProvider.Log;
        if (log.IsEnabled())
        {
            log.MethodEnter(TraceSourceType.TraceSourceLtm, this, "InternalDispose");
        }
        if (Interlocked.Exchange(ref _disposed, 1) == 1)
        {
            return;
        }
        if (_internalTransaction.State.get_Status(_internalTransaction) == TransactionStatus.Active)
        {
            lock (_internalTransaction)
            {
                _internalTransaction.State.DisposeRoot(_internalTransaction);
            }
        }
        long num = Interlocked.Decrement(ref _internalTransaction._cloneCount);
        if (num == 0L)
        {
            _internalTransaction.Dispose();
        }
        if (log.IsEnabled())
        {
            log.MethodExit(TraceSourceType.TraceSourceLtm, this, "InternalDispose");
        }
    }
References System.Transactions.InternalTransaction._cloneCount, System.Transactions.Transaction._disposed, System.Transactions.Transaction._internalTransaction, System.Threading.Interlocked.Decrement(), System.Transactions.InternalTransaction.Dispose(), System.Transactions.TransactionState.DisposeRoot(), System.Threading.Interlocked.Exchange(), System.Transactions.TransactionState.get_Status(), System.Diagnostics.Tracing.EventSource.IsEnabled(), System.L, System.Transactions.TransactionsEtwProvider.Log, System.Transactions.TransactionsEtwProvider.MethodEnter(), System.Transactions.TransactionsEtwProvider.MethodExit(), and System.Transactions.InternalTransaction.State.