Terraria: System.Transactions.CommittableTransaction.EndCommit
EndCommit()
void System.Transactions.CommittableTransaction.EndCommit (IAsyncResult asyncResult) inline
Definition at line 157 of file CommittableTransaction.cs.
    {
        TransactionsEtwProvider log = TransactionsEtwProvider.Log;
        if (log.IsEnabled())
        {
            log.MethodEnter(TraceSourceType.TraceSourceLtm, this, "EndCommit");
        }
        if (asyncResult != this)
        {
            throw new ArgumentException(System.SR.BadAsyncResult, "asyncResult");
        }
        lock (_internalTransaction)
        {
            while (!_internalTransaction.State.IsCompleted(_internalTransaction) && Monitor.Wait(_internalTransaction))
            {
            }
            _internalTransaction.State.EndCommit(_internalTransaction);
        }
        if (log.IsEnabled())
        {
            log.MethodExit(TraceSourceType.TraceSourceLtm, this, "EndCommit");
        }
    }
References System.Transactions.Transaction._internalTransaction, System.asyncResult, System.SR.BadAsyncResult, System.Transactions.TransactionState.EndCommit(), System.Transactions.TransactionState.IsCompleted(), System.Diagnostics.Tracing.EventSource.IsEnabled(), System.Transactions.TransactionsEtwProvider.Log, System.Transactions.TransactionsEtwProvider.MethodEnter(), System.Transactions.TransactionsEtwProvider.MethodExit(), System.Transactions.InternalTransaction.State, and System.Threading.Monitor.Wait().