Terraria: System.Xml.Schema.XmlSchemaType.GetBuiltInSimpleType
GetBuiltInSimpleType() [1/2]
static ? XmlSchemaSimpleType System.Xml.Schema.XmlSchemaType.GetBuiltInSimpleType (XmlQualifiedName qualifiedName) inline static
Definition at line 173 of file XmlSchemaType.cs.
    {
        if (qualifiedName == null)
        {
            throw new ArgumentNullException("qualifiedName");
        }
        return DatatypeImplementation.GetSimpleTypeFromXsdType(qualifiedName);
    }
References System.Xml.Dictionary, and System.Xml.Schema.DatatypeImplementation.GetSimpleTypeFromXsdType().
Referenced by System.Xml.Xsl.XmlQueryTypeFactory.ItemType.ItemType(), System.Xml.Schema.XmlBaseConverter.XmlBaseConverter(), System.Xml.Schema.XmlSchemaValidator.BuildXsiAttributes(), System.Xml.Schema.XmlAnyConverter.ChangeType(), System.Xml.Schema.XmlAnyConverter.ChangeType(), System.Xml.Schema.XmlAnyConverter.ChangeType(), System.Xml.Schema.XmlAnyConverter.ChangeType(), System.Xml.Schema.XmlAnyConverter.ChangeType(), System.Xml.Schema.XmlAnyConverter.ChangeType(), System.Xml.Schema.XmlAnyConverter.ChangeType(), System.Xml.Schema.XmlAnyConverter.ChangeType(), System.Xml.Xsl.Runtime.XmlQueryRuntime.ChangeTypeXsltResult(), System.Xml.Schema.Compiler.CleanupSimpleType(), System.Xml.Xsl.XmlQueryTypeFactory.ItemType.Create(), System.Xml.Schema.XmlSchemaInference.GetEffectiveSchemaType(), System.Xml.Xsl.XmlQueryType.IsSubtypeOfItemType(), System.Xml.DtdParser.ParseAttlistType(), System.Xml.DtdParser.ParseAttlistTypeAsync(), and System.Xml.Xsl.Runtime.XsltFunctions.SystemProperty().