Terraria: System.Linq.Expressions.Interpreter.ExceptionHelpers.UnwrapAndRethrow
UnwrapAndRethrow()
static void System.Linq.Expressions.Interpreter.ExceptionHelpers.UnwrapAndRethrow (TargetInvocationException exception) inline static
Definition at line 8 of file ExceptionHelpers.cs.
    {
        ExceptionDispatchInfo.Throw(exception.InnerException);
    }
References System.exception, and System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw().
Referenced by System.Linq.Expressions.Interpreter.ByRefMethodInfoCallInstruction.Run(), System.Linq.Expressions.Interpreter.ByRefNewInstruction.Run(), System.Linq.Expressions.Interpreter.InitializeLocalInstruction.MutableValue.Run(), System.Linq.Expressions.Interpreter.InitializeLocalInstruction.MutableBox.Run(), System.Linq.Expressions.Interpreter.MethodInfoCallInstruction.Run(), System.Linq.Expressions.Interpreter.NewInstruction.Run(), System.Linq.Expressions.Interpreter.CallInstruction.SlowCreate(), System.Linq.Expressions.Interpreter.IndexMethodByRefUpdater.Update(), and System.Linq.Expressions.Interpreter.PropertyByRefUpdater.Update().