Terraria: System.Xml.Schema.XmlSchemaType.IsDerivedFrom
IsDerivedFrom()
static bool System.Xml.Schema.XmlSchemaType.IsDerivedFrom ([NotNullWhen(true)] XmlSchemaType? derivedType, [NotNullWhen(true)] XmlSchemaType? baseType, XmlSchemaDerivationMethod except) inline static
Definition at line 257 of file XmlSchemaType.cs.
    {
        if (derivedType == null || baseType == null)
        {
            return false;
        }
        if (derivedType == baseType)
        {
            return true;
        }
        if (baseType == XmlSchemaComplexType.AnyType)
        {
            return true;
        }
        do
        {
            XmlSchemaSimpleType xmlSchemaSimpleType = derivedType as XmlSchemaSimpleType;
            if (baseType is XmlSchemaSimpleType xmlSchemaSimpleType2 && xmlSchemaSimpleType != null)
            {
                if (xmlSchemaSimpleType2 == DatatypeImplementation.AnySimpleType)
                {
                    return true;
                }
                if ((except & derivedType.DerivedBy) != 0 || !xmlSchemaSimpleType.Datatype.IsDerivedFrom(xmlSchemaSimpleType2.Datatype))
                {
                    return false;
                }
                return true;
            }
            if ((except & derivedType.DerivedBy) != 0)
            {
                return false;
            }
            derivedType = derivedType.BaseXmlSchemaType;
            if (derivedType == baseType)
            {
                return true;
            }
        }
        while (derivedType != null);
        return false;
    }
References System.Xml.Schema.DatatypeImplementation.AnySimpleType, System.Xml.Schema.XmlSchemaComplexType.AnyType, System.Xml.Schema.XmlSchemaType.BaseXmlSchemaType, and System.Xml.Dictionary.
Referenced by System.Xml.Schema.Compiler.CheckAtrributeGroupRestriction(), System.Xml.Schema.SchemaCollectionCompiler.CheckSubstitutionGroup(), System.Xml.Schema.XmlSchemaValidator.CheckXsiTypeAndNil(), System.Xml.Schema.Compiler.CompileLocalAttributes(), System.Xml.Schema.SchemaCollectionCompiler.CompileLocalAttributes(), System.Xml.Schema.XmlSchemaValidator.GetSubstitutionGroupHead(), System.Xml.Xsl.XmlQueryType.HasIntersectionItemType(), System.Xml.Schema.Compiler.IsElementFromElement(), System.Xml.Schema.SchemaCollectionCompiler.IsElementFromElement(), System.Xml.Xsl.XmlQueryType.IsSubtypeOfItemType(), System.Xml.Schema.Compiler.ProcessSubstitutionGroups(), and System.Xml.Schema.XsdValidator.ThoroughGetElementDecl().