Terraria: System.Collections.Specialized.BitVector32.CreateSectionHelper
CreateSectionHelper()
static Section System.Collections.Specialized.BitVector32.CreateSectionHelper (short maxValue, short priorMask, short priorOffset) inline static private
Definition at line 140 of file BitVector32.cs.
    {
        if (maxValue < 1)
        {
            throw new ArgumentException(System.SR.Format(System.SR.Argument_InvalidValue_TooSmall, "maxValue", 1), "maxValue");
        }
        short num = (short)(priorOffset + BitOperations.PopCount((ushort)priorMask));
        if (num >= 32)
        {
            throw new InvalidOperationException(System.SR.BitVectorFull);
        }
        short mask = (short)(BitOperations.RoundUpToPowerOf2((uint)((ushort)maxValue + 1)) - 1);
        return new Section(mask, num);
    }
References System.SR.Argument_InvalidValue_TooSmall, System.SR.BitVectorFull, System.SR.Format(), System.Numerics.BitOperations.PopCount(), and System.Numerics.BitOperations.RoundUpToPowerOf2().
Referenced by System.Collections.Specialized.BitVector32.CreateSection(), and System.Collections.Specialized.BitVector32.CreateSection().