Terraria: Terraria.Social.WeGame.IPCServer.ContinueReadOrWait
ContinueReadOrWait()
void Terraria.Social.WeGame.IPCServer.ContinueReadOrWait () inline
Definition at line 96 of file IPCServer.cs.
    {
        if (GetPipeStream().IsConnected)
        {
            BeginReadData();
            return;
        }
        try
        {
            GetPipeStream().BeginWaitForConnection(ConnectionCallback, null);
        }
        catch (IOException ex)
        {
            _pipeBrokenFlag = true;
            WeGameHelper.WriteDebugString("ContinueReadOrWait Exception, {0}", ex.Message);
        }
    }
References Terraria.Social.WeGame.IPCBase._pipeBrokenFlag, Terraria.Social.WeGame.IPCBase.BeginReadData(), System.IO.Pipes.NamedPipeServerStream.BeginWaitForConnection(), Terraria.Social.WeGame.IPCServer.ConnectionCallback(), Terraria.Social.WeGame.IPCServer.GetPipeStream(), System.Exception.Message, and Terraria.Social.WeGame.WeGameHelper.WriteDebugString().
Referenced by Terraria.Social.WeGame.IPCServer.ReadCallback().