Terraria: System.Xml.Xsl.Runtime.DescendantMergeIterator.MoveNext
MoveNext()
IteratorResult System.Xml.Xsl.Runtime.DescendantMergeIterator.MoveNext (XPathNavigator input) inline
Definition at line 37 of file DescendantMergeIterator.cs.
    {
        if (_state != IteratorState.NeedDescendant)
        {
            if (input == null)
            {
                return IteratorResult.NoMoreNodes;
            }
            if (_state != 0 && _navRoot.IsDescendant(input))
            {
                return IteratorResult.NeedInputNode;
            }
            _navCurrent = XmlQueryRuntime.SyncToNavigator(_navCurrent, input);
            _navRoot = XmlQueryRuntime.SyncToNavigator(_navRoot, input);
            _navEnd = XmlQueryRuntime.SyncToNavigator(_navEnd, input);
            _navEnd.MoveToNonDescendant();
            _state = IteratorState.NeedDescendant;
            if (_orSelf && !_filter.IsFiltered(input))
            {
                return IteratorResult.HaveCurrentNode;
            }
        }
        if (_filter.MoveToFollowing(_navCurrent, _navEnd))
        {
            return IteratorResult.HaveCurrentNode;
        }
        _state = IteratorState.NeedCurrent;
        return IteratorResult.NeedInputNode;
    }
References System.Xml.Xsl.Runtime.DescendantMergeIterator._filter, System.Xml.Xsl.Runtime.DescendantMergeIterator._navCurrent, System.Xml.Xsl.Runtime.DescendantMergeIterator._navEnd, System.Xml.Xsl.Runtime.DescendantMergeIterator._navRoot, System.Xml.Xsl.Runtime.DescendantMergeIterator._orSelf, System.Xml.Xsl.Runtime.DescendantMergeIterator._state, System.input, System.Xml.XPath.XPathNavigator.IsDescendant(), System.Xml.Xsl.Runtime.XmlNavigatorFilter.IsFiltered(), System.Xml.Xsl.Runtime.XmlNavigatorFilter.MoveToFollowing(), System.Xml.XPath.XPathNavigator.MoveToNonDescendant(), and System.Xml.Xsl.Runtime.XmlQueryRuntime.SyncToNavigator().