Terraria: System.Xml.Linq.StreamingElementWriter.PushElement
PushElement()
void System.Xml.Linq.StreamingElementWriter.PushElement () inline private
Definition at line 67 of file StreamingElementWriter.cs.
    {
        _resolver.PushScope();
        foreach (XAttribute attribute in _attributes)
        {
            if (attribute.IsNamespaceDeclaration)
            {
                _resolver.Add((attribute.Name.NamespaceName.Length == 0) ? string.Empty : attribute.Name.LocalName, XNamespace.Get(attribute.Value));
            }
        }
    }
References System.Xml.Linq.NamespaceResolver.Add(), System.Xml.Linq.XNamespace.Get(), and System.Xml.Linq.NamespaceResolver.PushScope().
Referenced by System.Xml.Linq.StreamingElementWriter.FlushElement().