Terraria: TEDisplayDoll.OnPlayerInteraction
OnPlayerInteraction()
static void TEDisplayDoll.OnPlayerInteraction (Player player, int clickX, int clickY) inline static
     {
         int num = clickX;
         int num2 = clickY;
         if (Main.tile[num, num2].frameX % 36 != 0)
         {
             num--;
         }
         num2 -= Main.tile[num, num2].frameY / 18;
         int num3 = Find(num, num2);
         if (num3 != -1)
         {
             num2++;
             accessoryTargetSlot = 3;
             TileEntity.BasicOpenCloseInteraction(player, num, num2, num3);
         }
     }
References accessoryTargetSlot, TileEntity.BasicOpenCloseInteraction(), Find(), Tile.frameX, Tile.frameY, and Main.tile.
Referenced by Player.TileInteractionsUse().