Terraria: TEDisplayDoll.TEDisplayDoll
TEDisplayDoll()
TEDisplayDoll.TEDisplayDoll () inline
     {
         _items = new Item[8];
         for (int i = 0; i < _items.Length; i++)
         {
             _items[i] = new Item();
         }
         _dyes = new Item[8];
         for (int j = 0; j < _dyes.Length; j++)
         {
             _dyes[j] = new Item();
         }
         _dollPlayer = new Player();
         _dollPlayer.hair = 15;
         _dollPlayer.skinColor = Color.White;
         _dollPlayer.skinVariant = 10;
     }
References _dollPlayer, _dyes, _items, Color, Player.hair, Player, Player.skinColor, and Player.skinVariant.
Referenced by GenerateInstance(), IsBreakable(), and Place().