Terraria: TEDisplayDoll.Hook_AfterPlacement
Hook_AfterPlacement()
static int TEDisplayDoll.Hook_AfterPlacement (int x, int y, int type = 470, int style = 0, int direction = 1, int alternate = 0) inline static
     {
         if (Main.netMode == 1)
         {
             NetMessage.SendTileSquare(Main.myPlayer, x, y - 2, 2, 3);
             NetMessage.SendData(87, -1, -1, null, x, y - 2, (int)_myEntityID);
             return -1;
         }
         return Place(x, y - 2);
     }
References _myEntityID, Main.myPlayer, Main.netMode, Place(), NetMessage.SendData(), and NetMessage.SendTileSquare().
Referenced by TileObjectData.Initialize().