Terraria: TEDisplayDoll.Framing_CheckTile
Framing_CheckTile()
static void TEDisplayDoll.Framing_CheckTile (int callX, int callY) inline static
     {
         if (WorldGen.destroyObject)
         {
             return;
         }
         int num = callX;
         int num2 = callY;
         Tile tileSafely = Framing.GetTileSafely(callX, callY);
         num -= tileSafely.frameX / 18 % 2;
         num2 -= tileSafely.frameY / 18 % 3;
         bool flag = false;
         for (int i = num; i < num + 2; i++)
         {
             for (int j = num2; j < num2 + 3; j++)
             {
                 Tile tile = Main.tile[i, j];
                 if (!tile.active() || tile.type != 470)
                 {
                     flag = true;
                 }
             }
         }
         if (!WorldGen.SolidTileAllowBottomSlope(num, num2 + 3) || !WorldGen.SolidTileAllowBottomSlope(num + 1, num2 + 3))
         {
             flag = true;
         }
         if (!flag)
         {
             return;
         }
         Kill(num, num2);
         if (Main.tile[callX, callY].frameX / 72 != 1)
         {
             Item.NewItem(new EntitySource_TileBreak(num, num2), num * 16, num2 * 16, 32, 48, 498);
         }
         else
         {
             Item.NewItem(new EntitySource_TileBreak(num, num2), num * 16, num2 * 16, 32, 48, 1989);
         }
         WorldGen.destroyObject = true;
         for (int k = num; k < num + 2; k++)
         {
             for (int l = num2; l < num2 + 3; l++)
             {
                 if (Main.tile[k, l].active() && Main.tile[k, l].type == 470)
                 {
                     WorldGen.KillTile(k, l);
                 }
             }
         }
         WorldGen.destroyObject = false;
     }
References Tile.active(), WorldGen.destroyObject, Tile.frameX, Tile.frameY, Framing.GetTileSafely(), Kill(), WorldGen.KillTile(), Item.NewItem(), WorldGen.SolidTileAllowBottomSlope(), Main.tile, and Tile.type.
Referenced by WorldGen.TileFrame().