Terraria: System.Xml.Serialization.SchemaObjectWriter.Write46_XmlSchemaElement
Write46_XmlSchemaElement()
void System.Xml.Serialization.SchemaObjectWriter.Write46_XmlSchemaElement (XmlSchemaElement o) inline private
Definition at line 847 of file SchemaObjectWriter.cs.
    {
        if (o == null)
        {
            return;
        }
        WriteStartElement("element");
        WriteAttribute("id", "", o.Id);
        WriteAttribute("minOccurs", "", XmlConvert.ToString(o.MinOccurs));
        WriteAttribute("maxOccurs", "", (o.MaxOccurs == decimal.MaxValue) ? "unbounded" : XmlConvert.ToString(o.MaxOccurs));
        if (o.IsAbstract)
        {
            WriteAttribute("abstract", "", XmlConvert.ToString(o.IsAbstract));
        }
        WriteAttribute("block", "", Write11_XmlSchemaDerivationMethod(o.BlockResolved));
        WriteAttribute("default", "", o.DefaultValue);
        WriteAttribute("final", "", Write11_XmlSchemaDerivationMethod(o.FinalResolved));
        WriteAttribute("fixed", "", o.FixedValue);
        if (o.Parent != null && !(o.Parent is XmlSchema))
        {
            if (o.QualifiedName != null && !o.QualifiedName.IsEmpty && o.QualifiedName.Namespace != null && o.QualifiedName.Namespace.Length != 0)
            {
                WriteAttribute("form", "", "qualified");
            }
            else
            {
                WriteAttribute("form", "", "unqualified");
            }
        }
        if (o.Name != null && o.Name.Length != 0)
        {
            WriteAttribute("name", "", o.Name);
        }
        if (o.IsNillable)
        {
            WriteAttribute("nillable", "", XmlConvert.ToString(o.IsNillable));
        }
        if (!o.SubstitutionGroup.IsEmpty)
        {
            WriteAttribute("substitutionGroup", "", o.SubstitutionGroup);
        }
        if (!o.RefName.IsEmpty)
        {
            WriteAttribute("ref", "", o.RefName);
        }
        else if (!o.SchemaTypeName.IsEmpty)
        {
            WriteAttribute("type", "", o.SchemaTypeName);
        }
        WriteAttributes(o.UnhandledAttributes, o);
        Write5_XmlSchemaAnnotation(o.Annotation);
        if (o.SchemaType is XmlSchemaComplexType)
        {
            Write35_XmlSchemaComplexType((XmlSchemaComplexType)o.SchemaType);
        }
        else if (o.SchemaType is XmlSchemaSimpleType)
        {
            Write9_XmlSchemaSimpleType((XmlSchemaSimpleType)o.SchemaType);
        }
        WriteSortedItems(o.Constraints);
        WriteEndElement();
    }
References System.Xml.Dictionary, System.Xml.XmlConvert.ToString(), System.Xml.Serialization.SchemaObjectWriter.Write11_XmlSchemaDerivationMethod(), System.Xml.Serialization.SchemaObjectWriter.Write35_XmlSchemaComplexType(), System.Xml.Serialization.SchemaObjectWriter.Write5_XmlSchemaAnnotation(), System.Xml.Serialization.SchemaObjectWriter.Write9_XmlSchemaSimpleType(), System.Xml.Serialization.SchemaObjectWriter.WriteAttribute(), System.Xml.Serialization.SchemaObjectWriter.WriteAttributes(), System.Xml.Serialization.SchemaObjectWriter.WriteEndElement(), System.Xml.Serialization.SchemaObjectWriter.WriteSortedItems(), and System.Xml.Serialization.SchemaObjectWriter.WriteStartElement().
Referenced by System.Xml.Serialization.SchemaObjectWriter.Write3_XmlSchemaObject(), and System.Xml.Serialization.SchemaObjectWriter.Write54_XmlSchemaSequence().