Terraria: System.Xml.Serialization.SchemaObjectWriter.Write7_XmlSchemaAppInfo
Write7_XmlSchemaAppInfo()
void System.Xml.Serialization.SchemaObjectWriter.Write7_XmlSchemaAppInfo (XmlSchemaAppInfo o) inline private
Definition at line 388 of file SchemaObjectWriter.cs.
    {
        if (o == null)
        {
            return;
        }
        WriteStartElement("appinfo");
        WriteAttribute("source", "", o.Source);
        XmlNode[] markup = o.Markup;
        if (markup != null)
        {
            foreach (XmlNode xmlNode in markup)
            {
                WriteStartElement("node");
                WriteAttribute("xml", "", xmlNode.OuterXml);
            }
        }
        WriteEndElement();
    }
References System.Xml.Dictionary, System.Xml.Serialization.SchemaObjectWriter.WriteAttribute(), System.Xml.Serialization.SchemaObjectWriter.WriteEndElement(), and System.Xml.Serialization.SchemaObjectWriter.WriteStartElement().
Referenced by System.Xml.Serialization.SchemaObjectWriter.Write3_XmlSchemaObject(), and System.Xml.Serialization.SchemaObjectWriter.Write5_XmlSchemaAnnotation().