Terraria: System.Xml.Serialization.SchemaObjectWriter.Write1_XmlSchemaAttribute
Write1_XmlSchemaAttribute()
void System.Xml.Serialization.SchemaObjectWriter.Write1_XmlSchemaAttribute (XmlSchemaAttribute o) inline private
Definition at line 173 of file SchemaObjectWriter.cs.
    {
        if (o == null)
        {
            return;
        }
        WriteStartElement("attribute");
        WriteAttribute("id", "", o.Id);
        WriteAttributes(o.UnhandledAttributes, o);
        WriteAttribute("default", "", o.DefaultValue);
        WriteAttribute("fixed", "", o.FixedValue);
        if (o.Parent != null && !(o.Parent is XmlSchema))
        {
            if (o.QualifiedName != null && !o.QualifiedName.IsEmpty && o.QualifiedName.Namespace != null && o.QualifiedName.Namespace.Length != 0)
            {
                WriteAttribute("form", "", "qualified");
            }
            else
            {
                WriteAttribute("form", "", "unqualified");
            }
        }
        WriteAttribute("name", "", o.Name);
        if (!o.RefName.IsEmpty)
        {
            WriteAttribute("ref", "", o.RefName);
        }
        else if (!o.SchemaTypeName.IsEmpty)
        {
            WriteAttribute("type", "", o.SchemaTypeName);
        }
        XmlSchemaUse v = ((o.Use == XmlSchemaUse.None) ? XmlSchemaUse.Optional : o.Use);
        WriteAttribute("use", "", Write30_XmlSchemaUse(v));
        Write5_XmlSchemaAnnotation(o.Annotation);
        Write9_XmlSchemaSimpleType(o.SchemaType);
        WriteEndElement();
    }
References System.Xml.Dictionary, System.Xml.Serialization.SchemaObjectWriter.Write30_XmlSchemaUse(), System.Xml.Serialization.SchemaObjectWriter.Write5_XmlSchemaAnnotation(), System.Xml.Serialization.SchemaObjectWriter.Write9_XmlSchemaSimpleType(), System.Xml.Serialization.SchemaObjectWriter.WriteAttribute(), System.Xml.Serialization.SchemaObjectWriter.WriteAttributes(), System.Xml.Serialization.SchemaObjectWriter.WriteEndElement(), and System.Xml.Serialization.SchemaObjectWriter.WriteStartElement().
Referenced by System.Xml.Serialization.SchemaObjectWriter.Write3_XmlSchemaObject().