Terraria: System.Xml.Serialization.SchemaObjectWriter.Write54_XmlSchemaSequence
Write54_XmlSchemaSequence()
void System.Xml.Serialization.SchemaObjectWriter.Write54_XmlSchemaSequence (XmlSchemaSequence o) inline private
Definition at line 1045 of file SchemaObjectWriter.cs.
    {
        if (o == null)
        {
            return;
        }
        WriteStartElement("sequence");
        WriteAttribute("id", "", o.Id);
        WriteAttribute("minOccurs", "", XmlConvert.ToString(o.MinOccurs));
        WriteAttribute("maxOccurs", "", (o.MaxOccurs == decimal.MaxValue) ? "unbounded" : XmlConvert.ToString(o.MaxOccurs));
        WriteAttributes(o.UnhandledAttributes, o);
        Write5_XmlSchemaAnnotation(o.Annotation);
        XmlSchemaObjectCollection items = o.Items;
        if (items != null)
        {
            for (int i = 0; i < items.Count; i++)
            {
                XmlSchemaObject xmlSchemaObject = items[i];
                if (xmlSchemaObject is XmlSchemaAny)
                {
                    Write53_XmlSchemaAny((XmlSchemaAny)xmlSchemaObject);
                }
                else if (xmlSchemaObject is XmlSchemaSequence)
                {
                    Write54_XmlSchemaSequence((XmlSchemaSequence)xmlSchemaObject);
                }
                else if (xmlSchemaObject is XmlSchemaChoice)
                {
                    Write52_XmlSchemaChoice((XmlSchemaChoice)xmlSchemaObject);
                }
                else if (xmlSchemaObject is XmlSchemaElement)
                {
                    Write46_XmlSchemaElement((XmlSchemaElement)xmlSchemaObject);
                }
                else if (xmlSchemaObject is XmlSchemaGroupRef)
                {
                    Write55_XmlSchemaGroupRef((XmlSchemaGroupRef)xmlSchemaObject);
                }
            }
        }
        WriteEndElement();
    }
References System.Collections.CollectionBase.Count, System.Xml.Dictionary, System.Xml.XmlConvert.ToString(), System.Xml.Serialization.SchemaObjectWriter.Write46_XmlSchemaElement(), System.Xml.Serialization.SchemaObjectWriter.Write52_XmlSchemaChoice(), System.Xml.Serialization.SchemaObjectWriter.Write53_XmlSchemaAny(), System.Xml.Serialization.SchemaObjectWriter.Write54_XmlSchemaSequence(), System.Xml.Serialization.SchemaObjectWriter.Write55_XmlSchemaGroupRef(), System.Xml.Serialization.SchemaObjectWriter.Write5_XmlSchemaAnnotation(), System.Xml.Serialization.SchemaObjectWriter.WriteAttribute(), System.Xml.Serialization.SchemaObjectWriter.WriteAttributes(), System.Xml.Serialization.SchemaObjectWriter.WriteEndElement(), and System.Xml.Serialization.SchemaObjectWriter.WriteStartElement().
Referenced by System.Xml.Serialization.SchemaObjectWriter.Write35_XmlSchemaComplexType(), System.Xml.Serialization.SchemaObjectWriter.Write3_XmlSchemaObject(), System.Xml.Serialization.SchemaObjectWriter.Write42_XmlSchemaComplexContentExtension(), System.Xml.Serialization.SchemaObjectWriter.Write54_XmlSchemaSequence(), System.Xml.Serialization.SchemaObjectWriter.Write56_XmlSchemaComplexContentRestriction(), and System.Xml.Serialization.SchemaObjectWriter.Write57_XmlSchemaGroup().