Terraria: System.Xml.Serialization.SchemaObjectWriter.Write15_XmlSchemaSimpleTypeRestriction
Write15_XmlSchemaSimpleTypeRestriction()
void System.Xml.Serialization.SchemaObjectWriter.Write15_XmlSchemaSimpleTypeRestriction (XmlSchemaSimpleTypeRestriction o) inline private
Definition at line 487 of file SchemaObjectWriter.cs.
    {
        if (o != null)
        {
            WriteStartElement("restriction");
            WriteAttribute("id", "", o.Id);
            WriteAttributes(o.UnhandledAttributes, o);
            if (!o.BaseTypeName.IsEmpty)
            {
                WriteAttribute("base", "", o.BaseTypeName);
            }
            Write5_XmlSchemaAnnotation(o.Annotation);
            Write9_XmlSchemaSimpleType(o.BaseType);
            WriteFacets(o.Facets);
            WriteEndElement();
        }
    }
References System.Xml.Dictionary, System.Xml.Serialization.SchemaObjectWriter.Write5_XmlSchemaAnnotation(), System.Xml.Serialization.SchemaObjectWriter.Write9_XmlSchemaSimpleType(), System.Xml.Serialization.SchemaObjectWriter.WriteAttribute(), System.Xml.Serialization.SchemaObjectWriter.WriteAttributes(), System.Xml.Serialization.SchemaObjectWriter.WriteEndElement(), System.Xml.Serialization.SchemaObjectWriter.WriteFacets(), and System.Xml.Serialization.SchemaObjectWriter.WriteStartElement().
Referenced by System.Xml.Serialization.SchemaObjectWriter.Write3_XmlSchemaObject(), and System.Xml.Serialization.SchemaObjectWriter.Write9_XmlSchemaSimpleType().