Terraria: System.Xml.Serialization.SchemaObjectWriter.Write3_XmlSchemaObject
Write3_XmlSchemaObject()
void System.Xml.Serialization.SchemaObjectWriter.Write3_XmlSchemaObject (XmlSchemaObject o) inline private
Definition at line 211 of file SchemaObjectWriter.cs.
    {
        if (o != null)
        {
            Type type = o.GetType();
            if (type == typeof(XmlSchemaComplexType))
            {
                Write35_XmlSchemaComplexType((XmlSchemaComplexType)o);
            }
            else if (type == typeof(XmlSchemaSimpleType))
            {
                Write9_XmlSchemaSimpleType((XmlSchemaSimpleType)o);
            }
            else if (type == typeof(XmlSchemaElement))
            {
                Write46_XmlSchemaElement((XmlSchemaElement)o);
            }
            else if (type == typeof(XmlSchemaAppInfo))
            {
                Write7_XmlSchemaAppInfo((XmlSchemaAppInfo)o);
            }
            else if (type == typeof(XmlSchemaDocumentation))
            {
                Write6_XmlSchemaDocumentation((XmlSchemaDocumentation)o);
            }
            else if (type == typeof(XmlSchemaAnnotation))
            {
                Write5_XmlSchemaAnnotation((XmlSchemaAnnotation)o);
            }
            else if (type == typeof(XmlSchemaGroup))
            {
                Write57_XmlSchemaGroup((XmlSchemaGroup)o);
            }
            else if (type == typeof(XmlSchemaXPath))
            {
                Write49_XmlSchemaXPath("xpath", "", (XmlSchemaXPath)o);
            }
            else if (type == typeof(XmlSchemaIdentityConstraint))
            {
                Write48_XmlSchemaIdentityConstraint((XmlSchemaIdentityConstraint)o);
            }
            else if (type == typeof(XmlSchemaUnique))
            {
                Write51_XmlSchemaUnique((XmlSchemaUnique)o);
            }
            else if (type == typeof(XmlSchemaKeyref))
            {
                Write50_XmlSchemaKeyref((XmlSchemaKeyref)o);
            }
            else if (type == typeof(XmlSchemaKey))
            {
                Write47_XmlSchemaKey((XmlSchemaKey)o);
            }
            else if (type == typeof(XmlSchemaGroupRef))
            {
                Write55_XmlSchemaGroupRef((XmlSchemaGroupRef)o);
            }
            else if (type == typeof(XmlSchemaAny))
            {
                Write53_XmlSchemaAny((XmlSchemaAny)o);
            }
            else if (type == typeof(XmlSchemaSequence))
            {
                Write54_XmlSchemaSequence((XmlSchemaSequence)o);
            }
            else if (type == typeof(XmlSchemaChoice))
            {
                Write52_XmlSchemaChoice((XmlSchemaChoice)o);
            }
            else if (type == typeof(XmlSchemaAll))
            {
                Write43_XmlSchemaAll((XmlSchemaAll)o);
            }
            else if (type == typeof(XmlSchemaComplexContentRestriction))
            {
                Write56_XmlSchemaComplexContentRestriction((XmlSchemaComplexContentRestriction)o);
            }
            else if (type == typeof(XmlSchemaComplexContentExtension))
            {
                Write42_XmlSchemaComplexContentExtension((XmlSchemaComplexContentExtension)o);
            }
            else if (type == typeof(XmlSchemaSimpleContentRestriction))
            {
                Write40_XmlSchemaSimpleContentRestriction((XmlSchemaSimpleContentRestriction)o);
            }
            else if (type == typeof(XmlSchemaSimpleContentExtension))
            {
                Write38_XmlSchemaSimpleContentExtension((XmlSchemaSimpleContentExtension)o);
            }
            else if (type == typeof(XmlSchemaComplexContent))
            {
                Write41_XmlSchemaComplexContent((XmlSchemaComplexContent)o);
            }
            else if (type == typeof(XmlSchemaSimpleContent))
            {
                Write36_XmlSchemaSimpleContent((XmlSchemaSimpleContent)o);
            }
            else if (type == typeof(XmlSchemaAnyAttribute))
            {
                Write33_XmlSchemaAnyAttribute((XmlSchemaAnyAttribute)o);
            }
            else if (type == typeof(XmlSchemaAttributeGroupRef))
            {
                Write32_XmlSchemaAttributeGroupRef((XmlSchemaAttributeGroupRef)o);
            }
            else if (type == typeof(XmlSchemaAttributeGroup))
            {
                Write31_XmlSchemaAttributeGroup((XmlSchemaAttributeGroup)o);
            }
            else if (type == typeof(XmlSchemaSimpleTypeRestriction))
            {
                Write15_XmlSchemaSimpleTypeRestriction((XmlSchemaSimpleTypeRestriction)o);
            }
            else if (type == typeof(XmlSchemaSimpleTypeList))
            {
                Write14_XmlSchemaSimpleTypeList((XmlSchemaSimpleTypeList)o);
            }
            else if (type == typeof(XmlSchemaSimpleTypeUnion))
            {
                Write12_XmlSchemaSimpleTypeUnion((XmlSchemaSimpleTypeUnion)o);
            }
            else if (type == typeof(XmlSchemaAttribute))
            {
                Write1_XmlSchemaAttribute((XmlSchemaAttribute)o);
            }
        }
    }
References System.Xml.Dictionary, System.Type.GetType(), System.type, System.Xml.Serialization.SchemaObjectWriter.Write12_XmlSchemaSimpleTypeUnion(), System.Xml.Serialization.SchemaObjectWriter.Write14_XmlSchemaSimpleTypeList(), System.Xml.Serialization.SchemaObjectWriter.Write15_XmlSchemaSimpleTypeRestriction(), System.Xml.Serialization.SchemaObjectWriter.Write1_XmlSchemaAttribute(), System.Xml.Serialization.SchemaObjectWriter.Write31_XmlSchemaAttributeGroup(), System.Xml.Serialization.SchemaObjectWriter.Write32_XmlSchemaAttributeGroupRef(), System.Xml.Serialization.SchemaObjectWriter.Write33_XmlSchemaAnyAttribute(), System.Xml.Serialization.SchemaObjectWriter.Write35_XmlSchemaComplexType(), System.Xml.Serialization.SchemaObjectWriter.Write36_XmlSchemaSimpleContent(), System.Xml.Serialization.SchemaObjectWriter.Write38_XmlSchemaSimpleContentExtension(), System.Xml.Serialization.SchemaObjectWriter.Write40_XmlSchemaSimpleContentRestriction(), System.Xml.Serialization.SchemaObjectWriter.Write41_XmlSchemaComplexContent(), System.Xml.Serialization.SchemaObjectWriter.Write42_XmlSchemaComplexContentExtension(), System.Xml.Serialization.SchemaObjectWriter.Write43_XmlSchemaAll(), System.Xml.Serialization.SchemaObjectWriter.Write46_XmlSchemaElement(), System.Xml.Serialization.SchemaObjectWriter.Write47_XmlSchemaKey(), System.Xml.Serialization.SchemaObjectWriter.Write48_XmlSchemaIdentityConstraint(), System.Xml.Serialization.SchemaObjectWriter.Write49_XmlSchemaXPath(), System.Xml.Serialization.SchemaObjectWriter.Write50_XmlSchemaKeyref(), System.Xml.Serialization.SchemaObjectWriter.Write51_XmlSchemaUnique(), System.Xml.Serialization.SchemaObjectWriter.Write52_XmlSchemaChoice(), System.Xml.Serialization.SchemaObjectWriter.Write53_XmlSchemaAny(), System.Xml.Serialization.SchemaObjectWriter.Write54_XmlSchemaSequence(), System.Xml.Serialization.SchemaObjectWriter.Write55_XmlSchemaGroupRef(), System.Xml.Serialization.SchemaObjectWriter.Write56_XmlSchemaComplexContentRestriction(), System.Xml.Serialization.SchemaObjectWriter.Write57_XmlSchemaGroup(), System.Xml.Serialization.SchemaObjectWriter.Write5_XmlSchemaAnnotation(), System.Xml.Serialization.SchemaObjectWriter.Write6_XmlSchemaDocumentation(), System.Xml.Serialization.SchemaObjectWriter.Write7_XmlSchemaAppInfo(), and System.Xml.Serialization.SchemaObjectWriter.Write9_XmlSchemaSimpleType().
Referenced by System.Xml.Serialization.SchemaObjectWriter.WriteSortedItems(), and System.Xml.Serialization.SchemaObjectWriter.WriteXmlSchemaObject().