Terraria: System.Xml.Serialization.SchemaObjectWriter.WriteFacets
WriteFacets()
void System.Xml.Serialization.SchemaObjectWriter.WriteFacets (XmlSchemaObjectCollection facets) inline private
Definition at line 505 of file SchemaObjectWriter.cs.
    {
        if (facets == null)
        {
            return;
        }
        ArrayList arrayList = new ArrayList();
        for (int i = 0; i < facets.Count; i++)
        {
            arrayList.Add(facets[i]);
        }
        arrayList.Sort(new XmlFacetComparer());
        for (int j = 0; j < arrayList.Count; j++)
        {
            XmlSchemaObject xmlSchemaObject = (XmlSchemaObject)arrayList[j];
            if (xmlSchemaObject is XmlSchemaMinExclusiveFacet)
            {
                Write_XmlSchemaFacet("minExclusive", (XmlSchemaFacet)xmlSchemaObject);
            }
            else if (xmlSchemaObject is XmlSchemaMaxInclusiveFacet)
            {
                Write_XmlSchemaFacet("maxInclusive", (XmlSchemaFacet)xmlSchemaObject);
            }
            else if (xmlSchemaObject is XmlSchemaMaxExclusiveFacet)
            {
                Write_XmlSchemaFacet("maxExclusive", (XmlSchemaFacet)xmlSchemaObject);
            }
            else if (xmlSchemaObject is XmlSchemaMinInclusiveFacet)
            {
                Write_XmlSchemaFacet("minInclusive", (XmlSchemaFacet)xmlSchemaObject);
            }
            else if (xmlSchemaObject is XmlSchemaLengthFacet)
            {
                Write_XmlSchemaFacet("length", (XmlSchemaFacet)xmlSchemaObject);
            }
            else if (xmlSchemaObject is XmlSchemaEnumerationFacet)
            {
                Write_XmlSchemaFacet("enumeration", (XmlSchemaFacet)xmlSchemaObject);
            }
            else if (xmlSchemaObject is XmlSchemaMinLengthFacet)
            {
                Write_XmlSchemaFacet("minLength", (XmlSchemaFacet)xmlSchemaObject);
            }
            else if (xmlSchemaObject is XmlSchemaPatternFacet)
            {
                Write_XmlSchemaFacet("pattern", (XmlSchemaFacet)xmlSchemaObject);
            }
            else if (xmlSchemaObject is XmlSchemaTotalDigitsFacet)
            {
                Write_XmlSchemaFacet("totalDigits", (XmlSchemaFacet)xmlSchemaObject);
            }
            else if (xmlSchemaObject is XmlSchemaMaxLengthFacet)
            {
                Write_XmlSchemaFacet("maxLength", (XmlSchemaFacet)xmlSchemaObject);
            }
            else if (xmlSchemaObject is XmlSchemaWhiteSpaceFacet)
            {
                Write_XmlSchemaFacet("whiteSpace", (XmlSchemaFacet)xmlSchemaObject);
            }
            else if (xmlSchemaObject is XmlSchemaFractionDigitsFacet)
            {
                Write_XmlSchemaFacet("fractionDigit", (XmlSchemaFacet)xmlSchemaObject);
            }
        }
    }
References System.Xml.Dictionary, and System.Xml.Serialization.SchemaObjectWriter.Write_XmlSchemaFacet().
Referenced by System.Xml.Serialization.SchemaObjectWriter.Write15_XmlSchemaSimpleTypeRestriction(), and System.Xml.Serialization.SchemaObjectWriter.Write40_XmlSchemaSimpleContentRestriction().