Terraria: Microsoft.Xna.Framework.TitleContainer.OpenStream
OpenStream()
static Stream Microsoft.Xna.Framework.TitleContainer.OpenStream (string name) inline static
Definition at line 11 of file TitleContainer.cs.
    {
        if (string.IsNullOrEmpty(name))
        {
            throw new ArgumentNullException("name");
        }
        name = GetCleanPath(name);
        if (IsCleanPathAbsolute(name))
        {
            throw new ArgumentException(FrameworkResources.InvalidTitleContainerName);
        }
        try
        {
            string uriString = name.Replace(Path.DirectorySeparatorChar, Path.AltDirectorySeparatorChar);
            new Uri(uriString, UriKind.Relative);
        }
        catch (Exception innerException)
        {
            throw new ArgumentException(FrameworkResources.InvalidTitleContainerName, innerException);
        }
        try
        {
            string path = Path.Combine(TitleLocation.Path, name);
            return File.OpenRead(path);
        }
        catch (Exception ex)
        {
            if (ex is FileNotFoundException || ex is DirectoryNotFoundException || ex is ArgumentException)
            {
                throw new FileNotFoundException(string.Format(CultureInfo.CurrentCulture, FrameworkResources.OpenStreamNotFound, new object[1] { name }));
            }
            throw new InvalidOperationException(string.Format(CultureInfo.CurrentCulture, FrameworkResources.OpenStreamError, new object[1] { name }), ex);
        }
    }
References System.IO.Path.AltDirectorySeparatorChar, System.IO.Path.Combine(), System.Globalization.CultureInfo.CurrentCulture, System.IO.Path.DirectorySeparatorChar, System.Globalization.Format, Microsoft.Xna.Framework.TitleContainer.GetCleanPath(), Microsoft.Xna.Framework.FrameworkResources.InvalidTitleContainerName, Microsoft.Xna.Framework.TitleContainer.IsCleanPathAbsolute(), System.IO.File.OpenRead(), Microsoft.Xna.Framework.FrameworkResources.OpenStreamError, Microsoft.Xna.Framework.FrameworkResources.OpenStreamNotFound, and Microsoft.Xna.Framework.TitleLocation.Path.