Terraria: System.Xml.Serialization.SchemaObjectWriter.WriteStartElement
WriteStartElement()
void System.Xml.Serialization.SchemaObjectWriter.WriteStartElement (string name) inline private
Definition at line 46 of file SchemaObjectWriter.cs.
    {
        NewLine();
        _indentLevel++;
        _w.Append('[');
        _w.Append(name);
    }
References System.Xml.Serialization.SchemaObjectWriter._indentLevel, System.Xml.Serialization.SchemaObjectWriter._w, System.Text.StringBuilder.Append(), and System.Xml.Serialization.SchemaObjectWriter.NewLine().
Referenced by System.Xml.Serialization.SchemaObjectWriter.Write12_XmlSchemaSimpleTypeUnion(), System.Xml.Serialization.SchemaObjectWriter.Write14_XmlSchemaSimpleTypeList(), System.Xml.Serialization.SchemaObjectWriter.Write15_XmlSchemaSimpleTypeRestriction(), System.Xml.Serialization.SchemaObjectWriter.Write1_XmlSchemaAttribute(), System.Xml.Serialization.SchemaObjectWriter.Write31_XmlSchemaAttributeGroup(), System.Xml.Serialization.SchemaObjectWriter.Write32_XmlSchemaAttributeGroupRef(), System.Xml.Serialization.SchemaObjectWriter.Write33_XmlSchemaAnyAttribute(), System.Xml.Serialization.SchemaObjectWriter.Write35_XmlSchemaComplexType(), System.Xml.Serialization.SchemaObjectWriter.Write36_XmlSchemaSimpleContent(), System.Xml.Serialization.SchemaObjectWriter.Write38_XmlSchemaSimpleContentExtension(), System.Xml.Serialization.SchemaObjectWriter.Write40_XmlSchemaSimpleContentRestriction(), System.Xml.Serialization.SchemaObjectWriter.Write41_XmlSchemaComplexContent(), System.Xml.Serialization.SchemaObjectWriter.Write42_XmlSchemaComplexContentExtension(), System.Xml.Serialization.SchemaObjectWriter.Write43_XmlSchemaAll(), System.Xml.Serialization.SchemaObjectWriter.Write46_XmlSchemaElement(), System.Xml.Serialization.SchemaObjectWriter.Write47_XmlSchemaKey(), System.Xml.Serialization.SchemaObjectWriter.Write49_XmlSchemaXPath(), System.Xml.Serialization.SchemaObjectWriter.Write50_XmlSchemaKeyref(), System.Xml.Serialization.SchemaObjectWriter.Write51_XmlSchemaUnique(), System.Xml.Serialization.SchemaObjectWriter.Write52_XmlSchemaChoice(), System.Xml.Serialization.SchemaObjectWriter.Write53_XmlSchemaAny(), System.Xml.Serialization.SchemaObjectWriter.Write54_XmlSchemaSequence(), System.Xml.Serialization.SchemaObjectWriter.Write55_XmlSchemaGroupRef(), System.Xml.Serialization.SchemaObjectWriter.Write56_XmlSchemaComplexContentRestriction(), System.Xml.Serialization.SchemaObjectWriter.Write57_XmlSchemaGroup(), System.Xml.Serialization.SchemaObjectWriter.Write5_XmlSchemaAnnotation(), System.Xml.Serialization.SchemaObjectWriter.Write6_XmlSchemaDocumentation(), System.Xml.Serialization.SchemaObjectWriter.Write7_XmlSchemaAppInfo(), System.Xml.Serialization.SchemaObjectWriter.Write9_XmlSchemaSimpleType(), and System.Xml.Serialization.SchemaObjectWriter.Write_XmlSchemaFacet().