Terraria: System.Xml.Serialization.SchemaObjectWriter.Write5_XmlSchemaAnnotation
Write5_XmlSchemaAnnotation()
void System.Xml.Serialization.SchemaObjectWriter.Write5_XmlSchemaAnnotation (XmlSchemaAnnotation o) inline private
Definition at line 339 of file SchemaObjectWriter.cs.
    {
        if (o == null)
        {
            return;
        }
        WriteStartElement("annotation");
        WriteAttribute("id", "", o.Id);
        WriteAttributes(o.UnhandledAttributes, o);
        XmlSchemaObjectCollection items = o.Items;
        if (items != null)
        {
            for (int i = 0; i < items.Count; i++)
            {
                XmlSchemaObject xmlSchemaObject = items[i];
                if (xmlSchemaObject is XmlSchemaAppInfo)
                {
                    Write7_XmlSchemaAppInfo((XmlSchemaAppInfo)xmlSchemaObject);
                }
                else if (xmlSchemaObject is XmlSchemaDocumentation)
                {
                    Write6_XmlSchemaDocumentation((XmlSchemaDocumentation)xmlSchemaObject);
                }
            }
        }
        WriteEndElement();
    }
References System.Collections.CollectionBase.Count, System.Xml.Dictionary, System.Xml.Serialization.SchemaObjectWriter.Write6_XmlSchemaDocumentation(), System.Xml.Serialization.SchemaObjectWriter.Write7_XmlSchemaAppInfo(), System.Xml.Serialization.SchemaObjectWriter.WriteAttribute(), System.Xml.Serialization.SchemaObjectWriter.WriteAttributes(), System.Xml.Serialization.SchemaObjectWriter.WriteEndElement(), and System.Xml.Serialization.SchemaObjectWriter.WriteStartElement().
Referenced by System.Xml.Serialization.SchemaObjectWriter.Write12_XmlSchemaSimpleTypeUnion(), System.Xml.Serialization.SchemaObjectWriter.Write14_XmlSchemaSimpleTypeList(), System.Xml.Serialization.SchemaObjectWriter.Write15_XmlSchemaSimpleTypeRestriction(), System.Xml.Serialization.SchemaObjectWriter.Write1_XmlSchemaAttribute(), System.Xml.Serialization.SchemaObjectWriter.Write31_XmlSchemaAttributeGroup(), System.Xml.Serialization.SchemaObjectWriter.Write32_XmlSchemaAttributeGroupRef(), System.Xml.Serialization.SchemaObjectWriter.Write33_XmlSchemaAnyAttribute(), System.Xml.Serialization.SchemaObjectWriter.Write35_XmlSchemaComplexType(), System.Xml.Serialization.SchemaObjectWriter.Write36_XmlSchemaSimpleContent(), System.Xml.Serialization.SchemaObjectWriter.Write38_XmlSchemaSimpleContentExtension(), System.Xml.Serialization.SchemaObjectWriter.Write3_XmlSchemaObject(), System.Xml.Serialization.SchemaObjectWriter.Write40_XmlSchemaSimpleContentRestriction(), System.Xml.Serialization.SchemaObjectWriter.Write41_XmlSchemaComplexContent(), System.Xml.Serialization.SchemaObjectWriter.Write42_XmlSchemaComplexContentExtension(), System.Xml.Serialization.SchemaObjectWriter.Write43_XmlSchemaAll(), System.Xml.Serialization.SchemaObjectWriter.Write46_XmlSchemaElement(), System.Xml.Serialization.SchemaObjectWriter.Write47_XmlSchemaKey(), System.Xml.Serialization.SchemaObjectWriter.Write49_XmlSchemaXPath(), System.Xml.Serialization.SchemaObjectWriter.Write50_XmlSchemaKeyref(), System.Xml.Serialization.SchemaObjectWriter.Write51_XmlSchemaUnique(), System.Xml.Serialization.SchemaObjectWriter.Write52_XmlSchemaChoice(), System.Xml.Serialization.SchemaObjectWriter.Write53_XmlSchemaAny(), System.Xml.Serialization.SchemaObjectWriter.Write54_XmlSchemaSequence(), System.Xml.Serialization.SchemaObjectWriter.Write55_XmlSchemaGroupRef(), System.Xml.Serialization.SchemaObjectWriter.Write56_XmlSchemaComplexContentRestriction(), System.Xml.Serialization.SchemaObjectWriter.Write57_XmlSchemaGroup(), System.Xml.Serialization.SchemaObjectWriter.Write9_XmlSchemaSimpleType(), and System.Xml.Serialization.SchemaObjectWriter.Write_XmlSchemaFacet().