Terraria: System.Xml.Serialization.SchemaObjectWriter.WriteAttributes
WriteAttributes()
void System.Xml.Serialization.SchemaObjectWriter.WriteAttributes (XmlAttribute[] a, XmlSchemaObject o) inline private
Definition at line 79 of file SchemaObjectWriter.cs.
    {
        if (a != null)
        {
            ArrayList arrayList = new ArrayList();
            for (int i = 0; i < a.Length; i++)
            {
                arrayList.Add(a[i]);
            }
            arrayList.Sort(new XmlAttributeComparer());
            for (int j = 0; j < arrayList.Count; j++)
            {
                XmlAttribute a2 = (XmlAttribute)arrayList[j];
                WriteAttribute(a2);
            }
        }
    }
References System.Xml.Dictionary, and System.Xml.Serialization.SchemaObjectWriter.WriteAttribute().
Referenced by System.Xml.Serialization.SchemaObjectWriter.Write12_XmlSchemaSimpleTypeUnion(), System.Xml.Serialization.SchemaObjectWriter.Write14_XmlSchemaSimpleTypeList(), System.Xml.Serialization.SchemaObjectWriter.Write15_XmlSchemaSimpleTypeRestriction(), System.Xml.Serialization.SchemaObjectWriter.Write1_XmlSchemaAttribute(), System.Xml.Serialization.SchemaObjectWriter.Write31_XmlSchemaAttributeGroup(), System.Xml.Serialization.SchemaObjectWriter.Write32_XmlSchemaAttributeGroupRef(), System.Xml.Serialization.SchemaObjectWriter.Write33_XmlSchemaAnyAttribute(), System.Xml.Serialization.SchemaObjectWriter.Write35_XmlSchemaComplexType(), System.Xml.Serialization.SchemaObjectWriter.Write36_XmlSchemaSimpleContent(), System.Xml.Serialization.SchemaObjectWriter.Write38_XmlSchemaSimpleContentExtension(), System.Xml.Serialization.SchemaObjectWriter.Write40_XmlSchemaSimpleContentRestriction(), System.Xml.Serialization.SchemaObjectWriter.Write41_XmlSchemaComplexContent(), System.Xml.Serialization.SchemaObjectWriter.Write42_XmlSchemaComplexContentExtension(), System.Xml.Serialization.SchemaObjectWriter.Write43_XmlSchemaAll(), System.Xml.Serialization.SchemaObjectWriter.Write46_XmlSchemaElement(), System.Xml.Serialization.SchemaObjectWriter.Write47_XmlSchemaKey(), System.Xml.Serialization.SchemaObjectWriter.Write49_XmlSchemaXPath(), System.Xml.Serialization.SchemaObjectWriter.Write50_XmlSchemaKeyref(), System.Xml.Serialization.SchemaObjectWriter.Write51_XmlSchemaUnique(), System.Xml.Serialization.SchemaObjectWriter.Write52_XmlSchemaChoice(), System.Xml.Serialization.SchemaObjectWriter.Write53_XmlSchemaAny(), System.Xml.Serialization.SchemaObjectWriter.Write54_XmlSchemaSequence(), System.Xml.Serialization.SchemaObjectWriter.Write55_XmlSchemaGroupRef(), System.Xml.Serialization.SchemaObjectWriter.Write56_XmlSchemaComplexContentRestriction(), System.Xml.Serialization.SchemaObjectWriter.Write57_XmlSchemaGroup(), System.Xml.Serialization.SchemaObjectWriter.Write5_XmlSchemaAnnotation(), System.Xml.Serialization.SchemaObjectWriter.Write9_XmlSchemaSimpleType(), and System.Xml.Serialization.SchemaObjectWriter.Write_XmlSchemaFacet().