Terraria: System.Xml.Serialization.SchemaObjectWriter.Write41_XmlSchemaComplexContent
Write41_XmlSchemaComplexContent()
void System.Xml.Serialization.SchemaObjectWriter.Write41_XmlSchemaComplexContent (XmlSchemaComplexContent o) inline private
Definition at line 777 of file SchemaObjectWriter.cs.
    {
        if (o != null)
        {
            WriteStartElement("complexContent");
            WriteAttribute("id", "", o.Id);
            WriteAttribute("mixed", "", XmlConvert.ToString(o.IsMixed));
            WriteAttributes(o.UnhandledAttributes, o);
            Write5_XmlSchemaAnnotation(o.Annotation);
            if (o.Content is XmlSchemaComplexContentRestriction)
            {
                Write56_XmlSchemaComplexContentRestriction((XmlSchemaComplexContentRestriction)o.Content);
            }
            else if (o.Content is XmlSchemaComplexContentExtension)
            {
                Write42_XmlSchemaComplexContentExtension((XmlSchemaComplexContentExtension)o.Content);
            }
            WriteEndElement();
        }
    }
References System.Xml.Dictionary, System.Xml.XmlConvert.ToString(), System.Xml.Serialization.SchemaObjectWriter.Write42_XmlSchemaComplexContentExtension(), System.Xml.Serialization.SchemaObjectWriter.Write56_XmlSchemaComplexContentRestriction(), System.Xml.Serialization.SchemaObjectWriter.Write5_XmlSchemaAnnotation(), System.Xml.Serialization.SchemaObjectWriter.WriteAttribute(), System.Xml.Serialization.SchemaObjectWriter.WriteAttributes(), System.Xml.Serialization.SchemaObjectWriter.WriteEndElement(), and System.Xml.Serialization.SchemaObjectWriter.WriteStartElement().
Referenced by System.Xml.Serialization.SchemaObjectWriter.Write35_XmlSchemaComplexType(), and System.Xml.Serialization.SchemaObjectWriter.Write3_XmlSchemaObject().