Terraria: System.Xml.Serialization.SchemaObjectWriter.Write48_XmlSchemaIdentityConstraint
Write48_XmlSchemaIdentityConstraint()
void System.Xml.Serialization.SchemaObjectWriter.Write48_XmlSchemaIdentityConstraint (XmlSchemaIdentityConstraint o) inline private
Definition at line 933 of file SchemaObjectWriter.cs.
    {
        if (o != null)
        {
            Type type = o.GetType();
            if (type == typeof(XmlSchemaUnique))
            {
                Write51_XmlSchemaUnique((XmlSchemaUnique)o);
            }
            else if (type == typeof(XmlSchemaKeyref))
            {
                Write50_XmlSchemaKeyref((XmlSchemaKeyref)o);
            }
            else if (type == typeof(XmlSchemaKey))
            {
                Write47_XmlSchemaKey((XmlSchemaKey)o);
            }
        }
    }
References System.Xml.Dictionary, System.Type.GetType(), System.type, System.Xml.Serialization.SchemaObjectWriter.Write47_XmlSchemaKey(), System.Xml.Serialization.SchemaObjectWriter.Write50_XmlSchemaKeyref(), and System.Xml.Serialization.SchemaObjectWriter.Write51_XmlSchemaUnique().
Referenced by System.Xml.Serialization.SchemaObjectWriter.Write3_XmlSchemaObject().