Terraria: Microsoft.Xna.Framework.TitleContainer.GetCleanPath
GetCleanPath()
static string Microsoft.Xna.Framework.TitleContainer.GetCleanPath (string path) inline static package
Definition at line 52 of file TitleContainer.cs.
    {
        path = path.Replace('/', '\\');
        path = path.Replace("\\.\\", "\\");
        while (path.StartsWith(".\\"))
        {
            path = path.Substring(".\\".Length);
        }
        while (path.EndsWith("\\."))
        {
            path = ((path.Length <= "\\.".Length) ? "\\" : path.Substring(0, path.Length - "\\.".Length));
        }
        int num;
        for (num = 1; num < path.Length; num = CollapseParentDirectory(ref path, num, "\\..\\".Length))
        {
            num = path.IndexOf("\\..\\", num);
            if (num < 0)
            {
                break;
            }
        }
        if (path.EndsWith("\\.."))
        {
            num = path.Length - "\\..".Length;
            if (num > 0)
            {
                CollapseParentDirectory(ref path, num, "\\..".Length);
            }
        }
        if (path == ".")
        {
            path = string.Empty;
        }
        return path;
    }
References Microsoft.Xna.Framework.TitleContainer.CollapseParentDirectory().
Referenced by Microsoft.Xna.Framework.TitleContainer.IsPathAbsolute(), and Microsoft.Xna.Framework.TitleContainer.OpenStream().