Terraria: System.Xml.Serialization.SchemaObjectWriter.Write36_XmlSchemaSimpleContent
Write36_XmlSchemaSimpleContent()
void System.Xml.Serialization.SchemaObjectWriter.Write36_XmlSchemaSimpleContent (XmlSchemaSimpleContent o) inline private
Definition at line 719 of file SchemaObjectWriter.cs.
    {
        if (o != null)
        {
            WriteStartElement("simpleContent");
            WriteAttribute("id", "", o.Id);
            WriteAttributes(o.UnhandledAttributes, o);
            Write5_XmlSchemaAnnotation(o.Annotation);
            if (o.Content is XmlSchemaSimpleContentRestriction)
            {
                Write40_XmlSchemaSimpleContentRestriction((XmlSchemaSimpleContentRestriction)o.Content);
            }
            else if (o.Content is XmlSchemaSimpleContentExtension)
            {
                Write38_XmlSchemaSimpleContentExtension((XmlSchemaSimpleContentExtension)o.Content);
            }
            WriteEndElement();
        }
    }
References System.Xml.Dictionary, System.Xml.Serialization.SchemaObjectWriter.Write38_XmlSchemaSimpleContentExtension(), System.Xml.Serialization.SchemaObjectWriter.Write40_XmlSchemaSimpleContentRestriction(), System.Xml.Serialization.SchemaObjectWriter.Write5_XmlSchemaAnnotation(), System.Xml.Serialization.SchemaObjectWriter.WriteAttribute(), System.Xml.Serialization.SchemaObjectWriter.WriteAttributes(), System.Xml.Serialization.SchemaObjectWriter.WriteEndElement(), and System.Xml.Serialization.SchemaObjectWriter.WriteStartElement().
Referenced by System.Xml.Serialization.SchemaObjectWriter.Write35_XmlSchemaComplexType(), and System.Xml.Serialization.SchemaObjectWriter.Write3_XmlSchemaObject().