Terraria: System.Xml.Serialization.SchemaObjectWriter.WriteSortedItems
WriteSortedItems()
void System.Xml.Serialization.SchemaObjectWriter.WriteSortedItems (XmlSchemaObjectCollection items) inline private
Definition at line 156 of file SchemaObjectWriter.cs.
    {
        if (items != null)
        {
            ArrayList arrayList = new ArrayList();
            for (int i = 0; i < items.Count; i++)
            {
                arrayList.Add(items[i]);
            }
            arrayList.Sort(new XmlSchemaObjectComparer());
            for (int j = 0; j < arrayList.Count; j++)
            {
                Write3_XmlSchemaObject((XmlSchemaObject)arrayList[j]);
            }
        }
    }
References System.Collections.CollectionBase.Count, System.Xml.Dictionary, and System.Xml.Serialization.SchemaObjectWriter.Write3_XmlSchemaObject().
Referenced by System.Xml.Serialization.SchemaObjectWriter.Write12_XmlSchemaSimpleTypeUnion(), System.Xml.Serialization.SchemaObjectWriter.Write31_XmlSchemaAttributeGroup(), System.Xml.Serialization.SchemaObjectWriter.Write35_XmlSchemaComplexType(), System.Xml.Serialization.SchemaObjectWriter.Write38_XmlSchemaSimpleContentExtension(), System.Xml.Serialization.SchemaObjectWriter.Write40_XmlSchemaSimpleContentRestriction(), System.Xml.Serialization.SchemaObjectWriter.Write42_XmlSchemaComplexContentExtension(), System.Xml.Serialization.SchemaObjectWriter.Write43_XmlSchemaAll(), System.Xml.Serialization.SchemaObjectWriter.Write46_XmlSchemaElement(), System.Xml.Serialization.SchemaObjectWriter.Write52_XmlSchemaChoice(), and System.Xml.Serialization.SchemaObjectWriter.Write56_XmlSchemaComplexContentRestriction().