Terraria: System.Xml.Serialization.SchemaObjectWriter.Write12_XmlSchemaSimpleTypeUnion
Write12_XmlSchemaSimpleTypeUnion()
void System.Xml.Serialization.SchemaObjectWriter.Write12_XmlSchemaSimpleTypeUnion (XmlSchemaSimpleTypeUnion o) inline private
Definition at line 439 of file SchemaObjectWriter.cs.
    {
        if (o == null)
        {
            return;
        }
        WriteStartElement("union");
        WriteAttribute("id", "", o.Id);
        WriteAttributes(o.UnhandledAttributes, o);
        if (o.MemberTypes != null)
        {
            ArrayList arrayList = new ArrayList();
            for (int i = 0; i < o.MemberTypes.Length; i++)
            {
                arrayList.Add(o.MemberTypes[i]);
            }
            arrayList.Sort(new QNameComparer());
            _w.Append(',');
            _w.Append("memberTypes=");
            for (int j = 0; j < arrayList.Count; j++)
            {
                XmlQualifiedName xmlQualifiedName = (XmlQualifiedName)arrayList[j];
                _w.Append(xmlQualifiedName.ToString());
                _w.Append(',');
            }
        }
        Write5_XmlSchemaAnnotation(o.Annotation);
        WriteSortedItems(o.BaseTypes);
        WriteEndElement();
    }
References System.Xml.Serialization.SchemaObjectWriter._w, System.Text.StringBuilder.Append(), System.Xml.Dictionary, System.Xml.Serialization.SchemaObjectWriter.Write5_XmlSchemaAnnotation(), System.Xml.Serialization.SchemaObjectWriter.WriteAttribute(), System.Xml.Serialization.SchemaObjectWriter.WriteAttributes(), System.Xml.Serialization.SchemaObjectWriter.WriteEndElement(), System.Xml.Serialization.SchemaObjectWriter.WriteSortedItems(), and System.Xml.Serialization.SchemaObjectWriter.WriteStartElement().
Referenced by System.Xml.Serialization.SchemaObjectWriter.Write3_XmlSchemaObject(), and System.Xml.Serialization.SchemaObjectWriter.Write9_XmlSchemaSimpleType().