Terraria: System.Xml.Serialization.SchemaObjectWriter.Write33_XmlSchemaAnyAttribute
Write33_XmlSchemaAnyAttribute()
void System.Xml.Serialization.SchemaObjectWriter.Write33_XmlSchemaAnyAttribute (XmlSchemaAnyAttribute o) inline private
Definition at line 637 of file SchemaObjectWriter.cs.
    {
        if (o != null)
        {
            WriteStartElement("anyAttribute");
            WriteAttribute("id", "", o.Id);
            WriteAttribute("namespace", "", ToString(o.NamespaceList));
            XmlSchemaContentProcessing v = ((o.ProcessContents == XmlSchemaContentProcessing.None) ? XmlSchemaContentProcessing.Strict : o.ProcessContents);
            WriteAttribute("processContents", "", Write34_XmlSchemaContentProcessing(v));
            WriteAttributes(o.UnhandledAttributes, o);
            Write5_XmlSchemaAnnotation(o.Annotation);
            WriteEndElement();
        }
    }
References System.Xml.Dictionary, System.ToString, System.Xml.Serialization.SchemaObjectWriter.Write34_XmlSchemaContentProcessing(), System.Xml.Serialization.SchemaObjectWriter.Write5_XmlSchemaAnnotation(), System.Xml.Serialization.SchemaObjectWriter.WriteAttribute(), System.Xml.Serialization.SchemaObjectWriter.WriteAttributes(), System.Xml.Serialization.SchemaObjectWriter.WriteEndElement(), and System.Xml.Serialization.SchemaObjectWriter.WriteStartElement().
Referenced by System.Xml.Serialization.SchemaObjectWriter.Write31_XmlSchemaAttributeGroup(), System.Xml.Serialization.SchemaObjectWriter.Write35_XmlSchemaComplexType(), System.Xml.Serialization.SchemaObjectWriter.Write38_XmlSchemaSimpleContentExtension(), System.Xml.Serialization.SchemaObjectWriter.Write3_XmlSchemaObject(), System.Xml.Serialization.SchemaObjectWriter.Write40_XmlSchemaSimpleContentRestriction(), System.Xml.Serialization.SchemaObjectWriter.Write42_XmlSchemaComplexContentExtension(), and System.Xml.Serialization.SchemaObjectWriter.Write56_XmlSchemaComplexContentRestriction().