Terraria: System.Xml.Serialization.SchemaObjectWriter.Write9_XmlSchemaSimpleType
Write9_XmlSchemaSimpleType()
void System.Xml.Serialization.SchemaObjectWriter.Write9_XmlSchemaSimpleType (XmlSchemaSimpleType o) inline private
Definition at line 408 of file SchemaObjectWriter.cs.
    {
        if (o != null)
        {
            WriteStartElement("simpleType");
            WriteAttribute("id", "", o.Id);
            WriteAttributes(o.UnhandledAttributes, o);
            WriteAttribute("name", "", o.Name);
            WriteAttribute("final", "", Write11_XmlSchemaDerivationMethod(o.FinalResolved));
            Write5_XmlSchemaAnnotation(o.Annotation);
            if (o.Content is XmlSchemaSimpleTypeUnion)
            {
                Write12_XmlSchemaSimpleTypeUnion((XmlSchemaSimpleTypeUnion)o.Content);
            }
            else if (o.Content is XmlSchemaSimpleTypeRestriction)
            {
                Write15_XmlSchemaSimpleTypeRestriction((XmlSchemaSimpleTypeRestriction)o.Content);
            }
            else if (o.Content is XmlSchemaSimpleTypeList)
            {
                Write14_XmlSchemaSimpleTypeList((XmlSchemaSimpleTypeList)o.Content);
            }
            WriteEndElement();
        }
    }
References System.Xml.Dictionary, System.Xml.Serialization.SchemaObjectWriter.Write11_XmlSchemaDerivationMethod(), System.Xml.Serialization.SchemaObjectWriter.Write12_XmlSchemaSimpleTypeUnion(), System.Xml.Serialization.SchemaObjectWriter.Write14_XmlSchemaSimpleTypeList(), System.Xml.Serialization.SchemaObjectWriter.Write15_XmlSchemaSimpleTypeRestriction(), System.Xml.Serialization.SchemaObjectWriter.Write5_XmlSchemaAnnotation(), System.Xml.Serialization.SchemaObjectWriter.WriteAttribute(), System.Xml.Serialization.SchemaObjectWriter.WriteAttributes(), System.Xml.Serialization.SchemaObjectWriter.WriteEndElement(), and System.Xml.Serialization.SchemaObjectWriter.WriteStartElement().
Referenced by System.Xml.Serialization.SchemaObjectWriter.Write14_XmlSchemaSimpleTypeList(), System.Xml.Serialization.SchemaObjectWriter.Write15_XmlSchemaSimpleTypeRestriction(), System.Xml.Serialization.SchemaObjectWriter.Write1_XmlSchemaAttribute(), System.Xml.Serialization.SchemaObjectWriter.Write3_XmlSchemaObject(), System.Xml.Serialization.SchemaObjectWriter.Write40_XmlSchemaSimpleContentRestriction(), and System.Xml.Serialization.SchemaObjectWriter.Write46_XmlSchemaElement().