Terraria: System.Xml.Serialization.SchemaObjectWriter.Write52_XmlSchemaChoice
Write52_XmlSchemaChoice()
void System.Xml.Serialization.SchemaObjectWriter.Write52_XmlSchemaChoice (XmlSchemaChoice o) inline private
Definition at line 1013 of file SchemaObjectWriter.cs.
    {
        if (o != null)
        {
            WriteStartElement("choice");
            WriteAttribute("id", "", o.Id);
            WriteAttribute("minOccurs", "", XmlConvert.ToString(o.MinOccurs));
            WriteAttribute("maxOccurs", "", (o.MaxOccurs == decimal.MaxValue) ? "unbounded" : XmlConvert.ToString(o.MaxOccurs));
            WriteAttributes(o.UnhandledAttributes, o);
            Write5_XmlSchemaAnnotation(o.Annotation);
            WriteSortedItems(o.Items);
            WriteEndElement();
        }
    }
References System.Xml.Dictionary, System.Xml.XmlConvert.ToString(), System.Xml.Serialization.SchemaObjectWriter.Write5_XmlSchemaAnnotation(), System.Xml.Serialization.SchemaObjectWriter.WriteAttribute(), System.Xml.Serialization.SchemaObjectWriter.WriteAttributes(), System.Xml.Serialization.SchemaObjectWriter.WriteEndElement(), System.Xml.Serialization.SchemaObjectWriter.WriteSortedItems(), and System.Xml.Serialization.SchemaObjectWriter.WriteStartElement().
Referenced by System.Xml.Serialization.SchemaObjectWriter.Write35_XmlSchemaComplexType(), System.Xml.Serialization.SchemaObjectWriter.Write3_XmlSchemaObject(), System.Xml.Serialization.SchemaObjectWriter.Write42_XmlSchemaComplexContentExtension(), System.Xml.Serialization.SchemaObjectWriter.Write54_XmlSchemaSequence(), System.Xml.Serialization.SchemaObjectWriter.Write56_XmlSchemaComplexContentRestriction(), and System.Xml.Serialization.SchemaObjectWriter.Write57_XmlSchemaGroup().