Terraria: Terraria.GameContent.Creative.CreativePowers.ModifyWindDirectionAndStrength.ProvideSlider
ProvideSlider()
override UIElement Terraria.GameContent.Creative.CreativePowers.ModifyWindDirectionAndStrength.ProvideSlider () inline
Implements Terraria.GameContent.Creative.IProvideSliderElement.
Definition at line 1199 of file CreativePowers.cs.
        {
            UIVerticalSlider uIVerticalSlider = CreativePowersHelper.CreateSlider(base.GetSliderValue, base.SetValueKeyboard, base.SetValueGamepad);
            uIVerticalSlider.OnUpdate += UpdateSliderAndShowMultiplierMouseOver;
            UIPanel uIPanel = new UIPanel();
            uIPanel.Width = new StyleDimension(132f, 0f);
            uIPanel.Height = new StyleDimension(180f, 0f);
            uIPanel.HAlign = 0f;
            uIPanel.VAlign = 0.5f;
            uIPanel.Append(uIVerticalSlider);
            uIPanel.OnUpdate += CreativePowersHelper.UpdateUseMouseInterface;
            UIText uIText = new UIText(Language.GetText("CreativePowers.WindWest"))
            {
                HAlign = 1f,
                VAlign = 0f
            };
            uIText.OnMouseOut += Button_OnMouseOut;
            uIText.OnMouseOver += Button_OnMouseOver;
            uIText.OnLeftClick += topText_OnClick;
            uIPanel.Append(uIText);
            UIText uIText2 = new UIText(Language.GetText("CreativePowers.WindEast"))
            {
                HAlign = 1f,
                VAlign = 1f
            };
            uIText2.OnMouseOut += Button_OnMouseOut;
            uIText2.OnMouseOver += Button_OnMouseOver;
            uIText2.OnLeftClick += bottomText_OnClick;
            uIPanel.Append(uIText2);
            UIText uIText3 = new UIText(Language.GetText("CreativePowers.WindNone"))
            {
                HAlign = 1f,
                VAlign = 0.5f
            };
            uIText3.OnMouseOut += Button_OnMouseOut;
            uIText3.OnMouseOver += Button_OnMouseOver;
            uIText3.OnLeftClick += middleText_OnClick;
            uIPanel.Append(uIText3);
            return uIPanel;
        }
References Terraria.GameContent.Creative.CreativePowers.ModifyWindDirectionAndStrength.bottomText_OnClick(), Terraria.GameContent.Creative.CreativePowers.ModifyWindDirectionAndStrength.Button_OnMouseOut(), Terraria.GameContent.Creative.CreativePowers.ModifyWindDirectionAndStrength.Button_OnMouseOver(), Terraria.GameContent.Creative.CreativePowersHelper.CreateSlider(), Terraria.Localization.Language.GetText(), Terraria.GameContent.Creative.CreativePowers.ModifyWindDirectionAndStrength.middleText_OnClick(), Terraria.GameContent.Creative.CreativePowers.ModifyWindDirectionAndStrength.topText_OnClick(), Terraria.GameContent.Creative.CreativePowers.ModifyWindDirectionAndStrength.UpdateSliderAndShowMultiplierMouseOver(), and Terraria.GameContent.Creative.CreativePowersHelper.UpdateUseMouseInterface().