Terraria: System.Xml.XmlTextReaderImpl.NodeData.SetValueNode
SetValueNode() [2/2]
void System.Xml.XmlTextReaderImpl.NodeData.SetValueNode (XmlNodeType type, string value) inline package
Definition at line 638 of file XmlTextReaderImpl.cs.
        {
            this.type = type;
            ClearName();
            _value = value;
            _valueStartPos = -1;
        }
References System.Xml.XmlTextReaderImpl.NodeData._value, System.Xml.XmlTextReaderImpl.NodeData._valueStartPos, System.Xml.XmlTextReaderImpl.NodeData.ClearName(), System.Xml.Dictionary, System.Xml.XmlTextReaderImpl.NodeData.type, and System.value.
Referenced by System.Xml.XmlTextReaderImpl._ParseTextAsync(), System.Xml.XmlTextReaderImpl.ParseAttributeValueChunk(), System.Xml.XmlTextReaderImpl.ParseCDataOrComment(), System.Xml.XmlTextReaderImpl.ParseCDataOrCommentAsync(), System.Xml.XmlTextReaderImpl.ParseRootLevelWhitespace(), System.Xml.XmlTextReaderImpl.ParseRootLevelWhitespaceAsync(), System.Xml.XmlTextReaderImpl.ParseText(), System.Xml.XmlTextReaderImpl.ParseTextAsync(), System.Xml.XmlTextReaderImpl.Read(), and System.Xml.XmlTextReaderImpl.ReadAsync().