Terraria: System.Xml.XmlTextReaderImpl.NodeData.SetNamedNode
SetNamedNode() [1/2]
void System.Xml.XmlTextReaderImpl.NodeData.SetNamedNode (XmlNodeType type, string localName) inline package
Definition at line 656 of file XmlTextReaderImpl.cs.
        {
            SetNamedNode(type, localName, string.Empty, localName);
        }
References System.Xml.XmlTextReaderImpl.NodeData.localName, System.Xml.XmlTextReaderImpl.NodeData.SetNamedNode(), and System.Xml.XmlTextReaderImpl.NodeData.type.
Referenced by System.Xml.XmlTextReaderImpl.ParseAttributeValueChunk(), System.Xml.XmlTextReaderImpl.ParseDtd(), System.Xml.XmlTextReaderImpl.ParseDtdAsync(), System.Xml.XmlTextReaderImpl.ParseElement(), System.Xml.XmlTextReaderImpl.ParseElementAsync_SetElement(), System.Xml.XmlTextReaderImpl.ParseEntityReference(), System.Xml.XmlTextReaderImpl.ParseEntityReferenceAsync(), System.Xml.XmlTextReaderImpl.ParsePI(), System.Xml.XmlTextReaderImpl.ParsePIAsync(), System.Xml.XmlTextReaderImpl.ParseXmlDeclaration(), System.Xml.XmlTextReaderImpl.ParseXmlDeclarationAsync(), System.Xml.XmlTextReaderImpl.NodeData.SetNamedNode(), and System.Xml.XmlTextReaderImpl.SetupEndEntityNodeInContent().