Terraria: System.Linq.Parallel.TakeOrSkipWhileQueryOperator.TakeOrSkipWhileQueryOperatorEnumerator.MoveNext
MoveNext() [2/2]
override bool System.Linq.Parallel.TakeOrSkipWhileQueryOperator< TResult >.TakeOrSkipWhileQueryOperatorEnumerator< TKey >.MoveNext ([AllowNull] ref TResult currentElement, [AllowNull] ref TKey currentKey) inline package
Definition at line 47 of file TakeOrSkipWhileQueryOperator.cs.
        {
            if (_buffer == null)
            {
                List<Pair<TResult, TKey>> list = new List<Pair<TResult, TKey>>();
                try
                {
                    TResult currentElement2 = default(TResult);
                    TKey currentKey2 = default(TKey);
                    int num = 0;
                    while (_source.MoveNext(ref currentElement2, ref currentKey2))
                    {
                        if ((num++ & 0x3F) == 0)
{
                            _cancellationToken.ThrowIfCancellationRequested();
                        }
                        list.Add(new Pair<TResult, TKey>(currentElement2, currentKey2));
                        if (_updatesSeen != _operatorState._updatesDone)
{
                            lock (_operatorState)
{
                                _currentLowKey = _operatorState._currentLowKey;
                                _updatesSeen = _operatorState._updatesDone;
                            }
                        }
                        if (_updatesSeen > 0 && _keyComparer.Compare(currentKey2, _currentLowKey) > 0)
{
                            break;
                        }
                        if ((_predicate == null) ? _indexedPredicate(currentElement2, currentKey2) : _predicate(currentElement2))
{
                            continue;
                        }
                        lock (_operatorState)
{
                            if (_operatorState._updatesDone == 0 || _keyComparer.Compare(_operatorState._currentLowKey, currentKey2) > 0)
{
                                _currentLowKey = (_operatorState._currentLowKey = currentKey2);
                                _updatesSeen = ++_operatorState._updatesDone;
                            }
                        }
                        break;
                    }
                }
                finally
                {
                    _sharedBarrier.Signal();
                }
                _sharedBarrier.Wait(_cancellationToken);
                _buffer = list;
                _bufferIndex = new Shared<int>(-1);
            }
            if (_take)
            {
                if (_bufferIndex.Value >= _buffer.Count - 1)
                {
                    return false;
                }
                _bufferIndex.Value++;
                currentElement = _buffer[_bufferIndex.Value].First;
                currentKey = _buffer[_bufferIndex.Value].Second;
                if (_operatorState._updatesDone != 0)
                {
                    return _keyComparer.Compare(_operatorState._currentLowKey, currentKey) > 0;
                }
                return true;
            }
            if (_operatorState._updatesDone == 0)
            {
                return false;
            }
            if (_bufferIndex.Value < _buffer.Count - 1)
            {
                _bufferIndex.Value++;
                while (_bufferIndex.Value < _buffer.Count)
                {
                    if (_keyComparer.Compare(_buffer[_bufferIndex.Value].Second, _operatorState._currentLowKey) >= 0)
                    {
                        currentElement = _buffer[_bufferIndex.Value].First;
                        currentKey = _buffer[_bufferIndex.Value].Second;
                        return true;
                    }
                    _bufferIndex.Value++;
                }
            }
            if (_source.MoveNext(ref currentElement, ref currentKey))
            {
                return true;
            }
            return false;
        }
References System.Linq.Parallel.TakeOrSkipWhileQueryOperator< TResult >.TakeOrSkipWhileQueryOperatorEnumerator< TKey >._buffer, System.Linq.Parallel.TakeOrSkipWhileQueryOperator< TResult >.TakeOrSkipWhileQueryOperatorEnumerator< TKey >._bufferIndex, System.Linq.Parallel.TakeOrSkipWhileQueryOperator< TResult >.TakeOrSkipWhileQueryOperatorEnumerator< TKey >._cancellationToken, System.Linq.Parallel.TakeOrSkipWhileQueryOperator< TResult >.TakeOrSkipWhileQueryOperatorEnumerator< TKey >._currentLowKey, System.Linq.Parallel.TakeOrSkipWhileQueryOperator< TResult >.TakeOrSkipWhileQueryOperatorEnumerator< TKey >._indexedPredicate, System.Linq.Parallel.TakeOrSkipWhileQueryOperator< TResult >.TakeOrSkipWhileQueryOperatorEnumerator< TKey >._keyComparer, System.Linq.Parallel.TakeOrSkipWhileQueryOperator< TResult >.TakeOrSkipWhileQueryOperatorEnumerator< TKey >._operatorState, System.Linq.Parallel.TakeOrSkipWhileQueryOperator< TResult >.TakeOrSkipWhileQueryOperatorEnumerator< TKey >._predicate, System.Linq.Parallel.TakeOrSkipWhileQueryOperator< TResult >.TakeOrSkipWhileQueryOperatorEnumerator< TKey >._sharedBarrier, System.Linq.Parallel.TakeOrSkipWhileQueryOperator< TResult >.TakeOrSkipWhileQueryOperatorEnumerator< TKey >._source, System.Linq.Parallel.TakeOrSkipWhileQueryOperator< TResult >.TakeOrSkipWhileQueryOperatorEnumerator< TKey >._take, System.Linq.Parallel.TakeOrSkipWhileQueryOperator< TResult >.TakeOrSkipWhileQueryOperatorEnumerator< TKey >._updatesSeen, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Collections.Generic.IComparer< in T >.Compare(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.list, System.Linq.Parallel.QueryOperatorEnumerator< TElement, TKey >.MoveNext(), System.Threading.CountdownEvent.Signal(), System.Threading.CancellationToken.ThrowIfCancellationRequested(), System.Linq.Parallel.Shared< T >.Value, and System.Threading.CountdownEvent.Wait().