Terraria: System.Xml.XmlTextReaderImpl.NodeData.CopyTo
CopyTo() [2/2]
void System.Xml.XmlTextReaderImpl.NodeData.CopyTo (int valueOffset, StringBuilder sb) inline package
Definition at line 695 of file XmlTextReaderImpl.cs.
        {
            if (_value == null)
            {
                sb.Append(_chars, _valueStartPos + valueOffset, _valueLength - valueOffset);
            }
            else if (valueOffset <= 0)
            {
                sb.Append(_value);
            }
            else
            {
                sb.Append(_value, valueOffset, _value.Length - valueOffset);
            }
        }
References System.Xml.XmlTextReaderImpl.NodeData._chars, System.Xml.XmlTextReaderImpl.NodeData._value, System.Xml.XmlTextReaderImpl.NodeData._valueLength, System.Xml.XmlTextReaderImpl.NodeData._valueStartPos, and System.Text.StringBuilder.Append().
Referenced by System.Xml.XmlTextReaderImpl.DtdParserProxy_ParseComment(), System.Xml.XmlTextReaderImpl.DtdParserProxy_ParseCommentAsync(), System.Xml.XmlTextReaderImpl.FinishPartialValue(), System.Xml.XmlTextReaderImpl.FinishPartialValueAsync(), System.Xml.XmlTextReaderImpl.ReadValueChunk(), and System.Xml.XmlTextReaderImpl.ReadValueChunkAsync().