Terraria: System.Xml.XmlTextReaderImpl.NodeData.SetValue
SetValue() [2/2]
void System.Xml.XmlTextReaderImpl.NodeData.SetValue (string value) inline package
Definition at line 672 of file XmlTextReaderImpl.cs.
        {
            _valueStartPos = -1;
            _value = value;
        }
References System.Xml.XmlTextReaderImpl.NodeData._value, System.Xml.XmlTextReaderImpl.NodeData._valueStartPos, and System.value.
Referenced by System.Xml.XmlTextReaderImpl.FinishOtherValueIterator(), System.Xml.XmlTextReaderImpl.FinishOtherValueIteratorAsync(), System.Xml.XmlTextReaderImpl.FinishPartialValue(), System.Xml.XmlTextReaderImpl.FinishPartialValueAsync(), System.Xml.XmlTextReaderImpl.ParseDtd(), System.Xml.XmlTextReaderImpl.ParseDtdAsync(), System.Xml.XmlTextReaderImpl.ParsePI(), System.Xml.XmlTextReaderImpl.ParsePIAsync(), System.Xml.XmlTextReaderImpl.ParseXmlDeclaration(), System.Xml.XmlTextReaderImpl.ParseXmlDeclarationAsync(), System.Xml.XmlTextReaderImpl.ReadContentAsBinary(), System.Xml.XmlTextReaderImpl.ReadContentAsBinaryAsync(), System.Xml.XmlTextReaderImpl.ReadValueChunk(), System.Xml.XmlTextReaderImpl.ReadValueChunkAsync(), System.Xml.XmlTextReaderImpl.SkipDtd(), and System.Xml.XmlTextReaderImpl.SkipDtdAsync().