Terraria: System.Xml.XmlTextReaderImpl.NodeData.SetLineInfo
SetLineInfo()
void System.Xml.XmlTextReaderImpl.NodeData.SetLineInfo (int lineNo, int linePos) inline package
Definition at line 628 of file XmlTextReaderImpl.cs.
        {
            lineInfo.Set(lineNo, linePos);
        }
References System.Xml.XmlTextReaderImpl.NodeData.lineInfo, and System.Xml.LineInfo.Set().
Referenced by System.Xml.XmlTextReaderImpl.XmlTextReaderImpl(), System.Xml.XmlTextReaderImpl._ParseTextAsync(), System.Xml.XmlTextReaderImpl.OnEof(), System.Xml.XmlTextReaderImpl.ParseAttributeValueChunk(), System.Xml.XmlTextReaderImpl.ParseCDataOrComment(), System.Xml.XmlTextReaderImpl.ParseCDataOrCommentAsync(), System.Xml.XmlTextReaderImpl.ParseDoctypeDecl(), System.Xml.XmlTextReaderImpl.ParseDoctypeDeclAsync(), System.Xml.XmlTextReaderImpl.ParseElement(), System.Xml.XmlTextReaderImpl.ParseElementAsync(), System.Xml.XmlTextReaderImpl.ParseEntityReference(), System.Xml.XmlTextReaderImpl.ParseEntityReferenceAsync(), System.Xml.XmlTextReaderImpl.ParsePI(), System.Xml.XmlTextReaderImpl.ParsePIAsync(), System.Xml.XmlTextReaderImpl.ParseRootLevelWhitespace(), System.Xml.XmlTextReaderImpl.ParseRootLevelWhitespaceAsync(), System.Xml.XmlTextReaderImpl.ParseText(), System.Xml.XmlTextReaderImpl.ParseTextAsync(), System.Xml.XmlTextReaderImpl.ParseXmlDeclaration(), System.Xml.XmlTextReaderImpl.ParseXmlDeclarationAsync(), System.Xml.XmlTextReaderImpl.Read(), System.Xml.XmlTextReaderImpl.ReadAsync(), System.Xml.XmlTextReaderImpl.ReadContentAsBinary(), System.Xml.XmlTextReaderImpl.ReadContentAsBinaryAsync(), System.Xml.XmlTextReaderImpl.ResetState(), and System.Xml.XmlTextReaderImpl.Throw().