Terraria: System.Xml.XmlTextReaderImpl.NodeData.AdjustLineInfo
AdjustLineInfo()
void System.Xml.XmlTextReaderImpl.NodeData.AdjustLineInfo (int valueOffset, bool isNormalized, ref LineInfo lineInfo) inline package
Definition at line 741 of file XmlTextReaderImpl.cs.
        {
            if (valueOffset != 0)
            {
                if (_valueStartPos != -1)
                {
                    XmlTextReaderImpl.AdjustLineInfo(_chars, _valueStartPos, _valueStartPos + valueOffset, isNormalized, ref lineInfo);
                }
                else
                {
                    XmlTextReaderImpl.AdjustLineInfo(_value, 0, valueOffset, isNormalized, ref lineInfo);
                }
            }
        }
References System.Xml.XmlTextReaderImpl.NodeData._chars, System.Xml.XmlTextReaderImpl.NodeData._value, System.Xml.XmlTextReaderImpl.NodeData._valueStartPos, System.Xml.XmlTextReaderImpl.AdjustLineInfo(), and System.Xml.XmlTextReaderImpl.NodeData.lineInfo.
Referenced by System.Xml.XmlTextReaderImpl.ReadContentAsBinary(), and System.Xml.XmlTextReaderImpl.ReadContentAsBinaryAsync().