Terraria: System.Runtime.Serialization.ObjectHolder.UpdateDescendentDependencyChain
UpdateDescendentDependencyChain()
void System.Runtime.Serialization.ObjectHolder.UpdateDescendentDependencyChain (int amount, ObjectManager manager) inline private
Definition at line 311 of file ObjectHolder.cs.
    {
        ObjectHolder objectHolder = this;
        do
        {
            objectHolder = manager.FindOrCreateObjectHolder(objectHolder.ContainerID);
            objectHolder.IncrementDescendentFixups(amount);
        }
        while (objectHolder.RequiresValueTypeFixup);
    }
References System.Runtime.Serialization.Dictionary, System.Runtime.Serialization.ObjectHolder.IncrementDescendentFixups(), and System.manager.
Referenced by System.Runtime.Serialization.ObjectHolder.AddFixup(), System.Runtime.Serialization.ObjectHolder.DecrementFixupsRemaining(), and System.Runtime.Serialization.ObjectHolder.UpdateData().