Terraria: System.Runtime.Serialization.CollectionDataContract.CollectionDataContractCriticalHelper.GetEnumeratorForCollection
GetEnumeratorForCollection()
IEnumerator System.Runtime.Serialization.CollectionDataContract.CollectionDataContractCriticalHelper.GetEnumeratorForCollection (object obj) inline package
Definition at line 523 of file CollectionDataContract.cs.
        {
            IEnumerator enumerator = ((IEnumerable)obj).GetEnumerator();
            if (Kind == CollectionKind.GenericDictionary)
            {
                if (_createGenericDictionaryEnumeratorDelegate == null)
                {
                    Type[] genericArguments = ItemType.GetGenericArguments();
                    MethodInfo methodInfo = GetBuildCreateGenericDictionaryEnumeratorGenericMethod(genericArguments);
                    _createGenericDictionaryEnumeratorDelegate = (CreateGenericDictionaryEnumeratorDelegate)methodInfo.Invoke(null, Array.Empty<object>());
                }
                enumerator = _createGenericDictionaryEnumeratorDelegate(enumerator);
            }
            else if (Kind == CollectionKind.Dictionary)
            {
                enumerator = new DictionaryEnumerator(((IDictionary)obj).GetEnumerator());
            }
            return enumerator;
            [UnconditionalSuppressMessage("ReflectionAnalysis", "IL2060:MakeGenericMethod", Justification = "The call to MakeGenericMethod is safe due to the fact that CollectionDataContractCriticalHelper.BuildCreateGenericDictionaryEnumerator<K,V> is not annotated.")]
            static MethodInfo GetBuildCreateGenericDictionaryEnumeratorGenericMethod(Type[] keyValueTypes)
            {
                return GetBuildCreateGenericDictionaryEnumeratorMethodInfo.MakeGenericMethod(keyValueTypes[0], keyValueTypes[1]);
            }
        }
References System.Runtime.Serialization.CollectionDataContract.CollectionDataContractCriticalHelper._createGenericDictionaryEnumeratorDelegate, System.Runtime.Serialization.CollectionDataContract.CollectionDataContractCriticalHelper.CreateGenericDictionaryEnumeratorDelegate(), System.Runtime.Serialization.Dictionary, System.Runtime.Serialization.CollectionDataContract.CollectionDataContractCriticalHelper.GetBuildCreateGenericDictionaryEnumeratorMethodInfo, System.Collections.Generic.Dictionary< TKey, TValue >.GetEnumerator(), System.Runtime.Serialization.CollectionDataContract.CollectionDataContractCriticalHelper.Kind, and System.obj.
Referenced by System.Runtime.Serialization.CollectionDataContract.GetEnumeratorForCollection().