Terraria: System.Runtime.Serialization.CollectionDataContract.CollectionDataContractCriticalHelper.CollectionDataContractCriticalHelper
CollectionDataContractCriticalHelper() [3/5]
System.Runtime.Serialization.CollectionDataContract.CollectionDataContractCriticalHelper.CollectionDataContractCriticalHelper ([DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicConstructors | DynamicallyAccessedMemberTypes.NonPublicConstructors | DynamicallyAccessedMemberTypes.PublicMethods | DynamicallyAccessedMemberTypes.NonPublicMethods | DynamicallyAccessedMemberTypes.PublicFields | DynamicallyAccessedMemberTypes.PublicProperties)] Type type, CollectionKind kind, Type itemType, MethodInfo getEnumeratorMethod, MethodInfo addMethod, ConstructorInfo constructor) inline package
Definition at line 428 of file CollectionDataContract.cs.
            : base(type)
        {
            if (getEnumeratorMethod == null)
            {
                throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new InvalidDataContractException(System.SR.Format(System.SR.CollectionMustHaveGetEnumeratorMethod, DataContract.GetClrTypeFullName(type))));
            }
            if (addMethod == null && !type.IsInterface)
            {
                throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new InvalidDataContractException(System.SR.Format(System.SR.CollectionMustHaveAddMethod, DataContract.GetClrTypeFullName(type))));
            }
            if (itemType == null)
            {
                throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new InvalidDataContractException(System.SR.Format(System.SR.CollectionMustHaveItemType, DataContract.GetClrTypeFullName(type))));
            }
            base.StableName = DataContract.GetCollectionStableName(type, itemType, out var collectionContractAttribute);
            Init(kind, itemType, collectionContractAttribute);
            _getEnumeratorMethod = getEnumeratorMethod;
            _addMethod = addMethod;
            _constructor = constructor;
        }
References System.Runtime.Serialization.CollectionDataContract.CollectionDataContractCriticalHelper._addMethod, System.Runtime.Serialization.CollectionDataContract.CollectionDataContractCriticalHelper._constructor, System.Runtime.Serialization.CollectionDataContract.CollectionDataContractCriticalHelper._getEnumeratorMethod, System.SR.CollectionMustHaveAddMethod, System.SR.CollectionMustHaveGetEnumeratorMethod, System.SR.CollectionMustHaveItemType, System.Runtime.Serialization.Dictionary, System.SR.Format(), System.Runtime.Serialization.DataContract.GetClrTypeFullName(), System.Runtime.Serialization.DataContract.GetCollectionStableName(), System.Runtime.Serialization.CollectionDataContract.CollectionDataContractCriticalHelper.Init(), System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperError(), and System.type.