Terraria: System.Runtime.Serialization.CollectionDataContract.CollectionDataContractCriticalHelper.Init
Init()
void System.Runtime.Serialization.CollectionDataContract.CollectionDataContractCriticalHelper.Init (CollectionKind kind, Type itemType, CollectionDataContractAttribute collectionContractAttribute) inline private
Definition at line 329 of file CollectionDataContract.cs.
        {
            _kind = kind;
            if (itemType != null)
            {
                _itemType = itemType;
                _isItemTypeNullable = DataContract.IsTypeNullable(itemType);
                bool flag = kind == CollectionKind.Dictionary || kind == CollectionKind.GenericDictionary;
                string text = null;
                string text2 = null;
                string text3 = null;
                if (collectionContractAttribute != null)
                {
                    if (collectionContractAttribute.IsItemNameSetExplicitly)
                    {
                        if (collectionContractAttribute.ItemName == null || collectionContractAttribute.ItemName.Length == 0)
{
                            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new InvalidDataContractException(System.SR.Format(System.SR.InvalidCollectionContractItemName, DataContract.GetClrTypeFullName(base.UnderlyingType))));
                        }
                        text = DataContract.EncodeLocalName(collectionContractAttribute.ItemName);
                        _itemNameSetExplicit = true;
                    }
                    if (collectionContractAttribute.IsKeyNameSetExplicitly)
                    {
                        if (collectionContractAttribute.KeyName == null || collectionContractAttribute.KeyName.Length == 0)
{
                            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new InvalidDataContractException(System.SR.Format(System.SR.InvalidCollectionContractKeyName, DataContract.GetClrTypeFullName(base.UnderlyingType))));
                        }
                        if (!flag)
{
                            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new InvalidDataContractException(System.SR.Format(System.SR.InvalidCollectionContractKeyNoDictionary, DataContract.GetClrTypeFullName(base.UnderlyingType), collectionContractAttribute.KeyName)));
                        }
                        text2 = DataContract.EncodeLocalName(collectionContractAttribute.KeyName);
                    }
                    if (collectionContractAttribute.IsValueNameSetExplicitly)
                    {
                        if (collectionContractAttribute.ValueName == null || collectionContractAttribute.ValueName.Length == 0)
{
                            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new InvalidDataContractException(System.SR.Format(System.SR.InvalidCollectionContractValueName, DataContract.GetClrTypeFullName(base.UnderlyingType))));
                        }
                        if (!flag)
{
                            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new InvalidDataContractException(System.SR.Format(System.SR.InvalidCollectionContractValueNoDictionary, DataContract.GetClrTypeFullName(base.UnderlyingType), collectionContractAttribute.ValueName)));
                        }
                        text3 = DataContract.EncodeLocalName(collectionContractAttribute.ValueName);
                    }
                }
                XmlDictionary xmlDictionary = (flag ? new XmlDictionary(5) : new XmlDictionary(3));
                base.Name = xmlDictionary.Add(base.StableName.Name);
                base.Namespace = xmlDictionary.Add(base.StableName.Namespace);
                _itemName = text ?? DataContract.GetStableName(DataContract.UnwrapNullableType(itemType)).Name;
                _collectionItemName = xmlDictionary.Add(_itemName);
                if (flag)
                {
                    _keyName = text2 ?? "Key";
                    _valueName = text3 ?? "Value";
                }
            }
            if (collectionContractAttribute != null)
            {
                base.IsReference = collectionContractAttribute.IsReference;
            }
        }
References System.Runtime.Serialization.CollectionDataContract.CollectionDataContractCriticalHelper._collectionItemName, System.Runtime.Serialization.CollectionDataContract.CollectionDataContractCriticalHelper._isItemTypeNullable, System.Runtime.Serialization.CollectionDataContract.CollectionDataContractCriticalHelper._itemName, System.Runtime.Serialization.CollectionDataContract.CollectionDataContractCriticalHelper._itemNameSetExplicit, System.Runtime.Serialization.CollectionDataContract.CollectionDataContractCriticalHelper._itemType, System.Runtime.Serialization.CollectionDataContract.CollectionDataContractCriticalHelper._keyName, System.Runtime.Serialization.CollectionDataContract.CollectionDataContractCriticalHelper._kind, System.Runtime.Serialization.CollectionDataContract.CollectionDataContractCriticalHelper._valueName, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Runtime.Serialization.Dictionary, System.Runtime.Serialization.DataContract.EncodeLocalName(), System.SR.Format(), System.Runtime.Serialization.DataContract.GetClrTypeFullName(), System.Runtime.Serialization.DataContract.GetStableName(), System.SR.InvalidCollectionContractItemName, System.SR.InvalidCollectionContractKeyName, System.SR.InvalidCollectionContractKeyNoDictionary, System.SR.InvalidCollectionContractValueName, System.SR.InvalidCollectionContractValueNoDictionary, System.Runtime.Serialization.DataContract.IsTypeNullable(), System.Runtime.Serialization.DataContract.DataContractCriticalHelper.Name, System.text, System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperError(), and System.Runtime.Serialization.DataContract.UnwrapNullableType().
Referenced by System.Runtime.Serialization.CollectionDataContract.CollectionDataContractCriticalHelper.CollectionDataContractCriticalHelper(), System.Runtime.Serialization.CollectionDataContract.CollectionDataContractCriticalHelper.CollectionDataContractCriticalHelper(), System.Runtime.Serialization.CollectionDataContract.CollectionDataContractCriticalHelper.CollectionDataContractCriticalHelper(), and System.Runtime.Serialization.CollectionDataContract.CollectionDataContractCriticalHelper.CollectionDataContractCriticalHelper().