Terraria: System.Runtime.Serialization.CollectionDataContract.CollectionDataContractCriticalHelper.IncrementCollectionCount
IncrementCollectionCount()
void System.Runtime.Serialization.CollectionDataContract.CollectionDataContractCriticalHelper.IncrementCollectionCount (XmlWriterDelegator xmlWriter, object obj, XmlObjectSerializerWriteContext context) inline package
Definition at line 469 of file CollectionDataContract.cs.
        {
            if (_incrementCollectionCountDelegate == null)
            {
                switch (Kind)
                {
                case CollectionKind.Dictionary:
                case CollectionKind.List:
                case CollectionKind.Collection:
                    _incrementCollectionCountDelegate = delegate(XmlWriterDelegator x, object o, XmlObjectSerializerWriteContext c)
                    {
                        c.IncrementCollectionCount(x, (ICollection)o);
                    };
                    break;
                case CollectionKind.GenericList:
                case CollectionKind.GenericCollection:
                {
                    MethodInfo methodInfo2 = GetBuildIncrementCollectionCountGenericDelegate(ItemType);
                    _incrementCollectionCountDelegate = (IncrementCollectionCountDelegate)methodInfo2.Invoke(null, Array.Empty<object>());
                    break;
                }
                case CollectionKind.GenericDictionary:
                {
                    MethodInfo methodInfo = GetBuildIncrementCollectionCountGenericDelegate(typeof(KeyValuePair<, >).MakeGenericType(ItemType.GetGenericArguments()));
                    _incrementCollectionCountDelegate = (IncrementCollectionCountDelegate)methodInfo.Invoke(null, Array.Empty<object>());
                    break;
                }
                default:
                    _incrementCollectionCountDelegate = DummyIncrementCollectionCount;
                    break;
                }
            }
            _incrementCollectionCountDelegate(xmlWriter, obj, context);
            [UnconditionalSuppressMessage("ReflectionAnalysis", "IL2060:MakeGenericMethod", Justification = "The call to MakeGenericMethod is safe due to the fact that CollectionDataContractCriticalHelper.BuildIncrementCollectionCountDelegate<T> is not annotated.")]
            static MethodInfo GetBuildIncrementCollectionCountGenericDelegate(Type type)
            {
                return BuildIncrementCollectionCountDelegateMethod.MakeGenericMethod(type);
            }
        }
References System.Collections.Generic.Dictionary< TKey, TValue >.Dictionary(), System.Runtime.Serialization.CollectionDataContract.CollectionDataContractCriticalHelper._incrementCollectionCountDelegate, System.Runtime.Serialization.CollectionDataContract.CollectionDataContractCriticalHelper.BuildIncrementCollectionCountDelegateMethod, System.Runtime.Serialization.Dictionary, System.Runtime.Serialization.CollectionDataContract.CollectionDataContractCriticalHelper.DummyIncrementCollectionCount(), System.Runtime.Serialization.CollectionDataContract.CollectionDataContractCriticalHelper.GetBuildIncrementCollectionCountGenericDelegate(), System.Runtime.Serialization.XmlObjectSerializerWriteContext.IncrementCollectionCount(), System.Runtime.Serialization.CollectionDataContract.CollectionDataContractCriticalHelper.IncrementCollectionCountDelegate(), System.Runtime.Serialization.CollectionDataContract.CollectionDataContractCriticalHelper.Kind, System.obj, and System.type.
Referenced by System.Runtime.Serialization.CollectionDataContract.IncrementCollectionCount().