Terraria: System.Runtime.Serialization.CollectionDataContract.CollectionDataContractCriticalHelper.GetCollectionElementType
GetCollectionElementType()
Type System.Runtime.Serialization.CollectionDataContract.CollectionDataContractCriticalHelper.GetCollectionElementType () inline package
Definition at line 549 of file CollectionDataContract.cs.
        {
            Type type = null;
            if (Kind != CollectionKind.GenericDictionary)
            {
                type = ((Kind != CollectionKind.Dictionary) ? GetEnumeratorMethod.ReturnType : Globals.TypeOfDictionaryEnumerator);
            }
            else
            {
                Type[] genericArguments = ItemType.GetGenericArguments();
                type = Globals.TypeOfGenericDictionaryEnumerator.MakeGenericType(genericArguments);
            }
            MethodInfo methodInfo = type.GetMethod("get_Current", BindingFlags.Instance | BindingFlags.Public, Type.EmptyTypes);
            if (methodInfo == null)
            {
                if (type.IsInterface)
                {
                    methodInfo = XmlFormatGeneratorStatics.GetCurrentMethod;
                }
                else
                {
                    Type interfaceType = Globals.TypeOfIEnumerator;
                    if (Kind == CollectionKind.GenericDictionary || Kind == CollectionKind.GenericCollection || Kind == CollectionKind.GenericEnumerable)
                    {
                        Type[] interfaces = type.GetInterfaces();
                        Type[] array = interfaces;
                        foreach (Type type2 in array)
{
                            if (type2.IsGenericType && type2.GetGenericTypeDefinition() == Globals.TypeOfIEnumeratorGeneric && type2.GetGenericArguments()[0] == ItemType)
{
                                interfaceType = type2;
                                break;
                            }
                        }
                    }
                    methodInfo = GetTargetMethodWithName("get_Current", type, interfaceType);
                }
            }
            return methodInfo.ReturnType;
        }
References System.array, System.Runtime.Serialization.Dictionary, System.Type.EmptyTypes, System.Runtime.Serialization.XmlFormatGeneratorStatics.GetCurrentMethod, System.Runtime.Serialization.CollectionDataContract.CollectionDataContractCriticalHelper.GetEnumeratorMethod, System.Type.GetInterfaces(), System.Runtime.Serialization.CollectionDataContract.GetTargetMethodWithName(), System.Runtime.Serialization.CollectionDataContract.CollectionDataContractCriticalHelper.ItemType, System.Runtime.Serialization.CollectionDataContract.CollectionDataContractCriticalHelper.Kind, System.Reflection.MethodInfo.ReturnType, System.type, System.Runtime.Serialization.Globals.TypeOfDictionaryEnumerator, System.Runtime.Serialization.Globals.TypeOfGenericDictionaryEnumerator, and System.Runtime.Serialization.Globals.TypeOfIEnumerator.
Referenced by System.Runtime.Serialization.CollectionDataContract.GetCollectionElementType().