Terraria: ContentSamples.FillNpcRarities
FillNpcRarities()
static void ContentSamples.FillNpcRarities () inline static private
     {
         NPCSpawnParams nPCSpawnParams = default(NPCSpawnParams);
         nPCSpawnParams.gameModeData = Main.RegisteredGameModes[0];
         NPCSpawnParams spawnparams = nPCSpawnParams;
         for (int i = -65; i < NPCID.Count; i++)
         {
             NPC nPC = new NPC();
             nPC.SetDefaults(i, spawnparams);
             NpcBestiaryRarityStars[i] = GetNPCBestiaryRarityStarsCount(nPC);
         }
         NpcBestiaryRarityStars[22] = 1;
         NpcBestiaryRarityStars[17] = 1;
         NpcBestiaryRarityStars[18] = 1;
         NpcBestiaryRarityStars[38] = 1;
         NpcBestiaryRarityStars[369] = 2;
         NpcBestiaryRarityStars[20] = 3;
         NpcBestiaryRarityStars[19] = 1;
         NpcBestiaryRarityStars[227] = 2;
         NpcBestiaryRarityStars[353] = 2;
         NpcBestiaryRarityStars[550] = 2;
         NpcBestiaryRarityStars[588] = 2;
         NpcBestiaryRarityStars[107] = 3;
         NpcBestiaryRarityStars[228] = 2;
         NpcBestiaryRarityStars[124] = 2;
         NpcBestiaryRarityStars[54] = 2;
         NpcBestiaryRarityStars[108] = 3;
         NpcBestiaryRarityStars[178] = 3;
         NpcBestiaryRarityStars[216] = 3;
         NpcBestiaryRarityStars[160] = 5;
         NpcBestiaryRarityStars[441] = 5;
         NpcBestiaryRarityStars[209] = 3;
         NpcBestiaryRarityStars[208] = 4;
         NpcBestiaryRarityStars[142] = 5;
         NpcBestiaryRarityStars[368] = 3;
         NpcBestiaryRarityStars[453] = 4;
         NpcBestiaryRarityStars[37] = 2;
         NpcBestiaryRarityStars[633] = 5;
         NpcBestiaryRarityStars[663] = 5;
         NpcBestiaryRarityStars[638] = 3;
         NpcBestiaryRarityStars[637] = 3;
         NpcBestiaryRarityStars[656] = 3;
         NpcBestiaryRarityStars[670] = 3;
         NpcBestiaryRarityStars[678] = 3;
         NpcBestiaryRarityStars[679] = 3;
         NpcBestiaryRarityStars[680] = 3;
         NpcBestiaryRarityStars[681] = 3;
         NpcBestiaryRarityStars[682] = 3;
         NpcBestiaryRarityStars[683] = 3;
         NpcBestiaryRarityStars[684] = 3;
         NpcBestiaryRarityStars[664] = 5;
         NpcBestiaryRarityStars[484] = 5;
         NpcBestiaryRarityStars[614] = 4;
         NpcBestiaryRarityStars[303] = 4;
         NpcBestiaryRarityStars[337] = 4;
         NpcBestiaryRarityStars[360] = 3;
         NpcBestiaryRarityStars[655] = 2;
         NpcBestiaryRarityStars[374] = 3;
         NpcBestiaryRarityStars[661] = 3;
         NpcBestiaryRarityStars[362] = 2;
         NpcBestiaryRarityStars[364] = 2;
         NpcBestiaryRarityStars[616] = 2;
         NpcBestiaryRarityStars[298] = 2;
         NpcBestiaryRarityStars[671] = 3;
         NpcBestiaryRarityStars[672] = 3;
         NpcBestiaryRarityStars[673] = 3;
         NpcBestiaryRarityStars[674] = 3;
         NpcBestiaryRarityStars[675] = 3;
         NpcBestiaryRarityStars[599] = 3;
         NpcBestiaryRarityStars[355] = 2;
         NpcBestiaryRarityStars[358] = 3;
         NpcBestiaryRarityStars[654] = 3;
         NpcBestiaryRarityStars[653] = 2;
         NpcBestiaryRarityStars[540] = 2;
         NpcBestiaryRarityStars[604] = 3;
         NpcBestiaryRarityStars[611] = 3;
         NpcBestiaryRarityStars[612] = 2;
         NpcBestiaryRarityStars[608] = 2;
         NpcBestiaryRarityStars[607] = 2;
         NpcBestiaryRarityStars[615] = 3;
         NpcBestiaryRarityStars[626] = 2;
         NpcBestiaryRarityStars[486] = 2;
         NpcBestiaryRarityStars[487] = 3;
         NpcBestiaryRarityStars[669] = 3;
         NpcBestiaryRarityStars[677] = 5;
         NpcBestiaryRarityStars[676] = 5;
         NpcBestiaryRarityStars[149] = 2;
         NpcBestiaryRarityStars[366] = 2;
         NpcBestiaryRarityStars[47] = 3;
         NpcBestiaryRarityStars[57] = 3;
         NpcBestiaryRarityStars[168] = 3;
         NpcBestiaryRarityStars[464] = 3;
         NpcBestiaryRarityStars[465] = 3;
         NpcBestiaryRarityStars[470] = 3;
         NpcBestiaryRarityStars[301] = 2;
         NpcBestiaryRarityStars[316] = 3;
         NpcBestiaryRarityStars[546] = 2;
         NpcBestiaryRarityStars[170] = 3;
         NpcBestiaryRarityStars[180] = 3;
         NpcBestiaryRarityStars[171] = 3;
         NpcBestiaryRarityStars[29] = 2;
         NpcBestiaryRarityStars[471] = 4;
         NpcBestiaryRarityStars[66] = 3;
         NpcBestiaryRarityStars[223] = 2;
         NpcBestiaryRarityStars[161] = 2;
         NpcBestiaryRarityStars[491] = 4;
         NpcBestiaryRarityStars[-9] = 3;
         NpcBestiaryRarityStars[594] = 2;
         NpcBestiaryRarityStars[628] = 2;
         NpcBestiaryRarityStars[225] = 2;
         NpcBestiaryRarityStars[224] = 2;
         NpcBestiaryRarityStars[250] = 3;
         NpcBestiaryRarityStars[16] = 2;
         NpcBestiaryRarityStars[481] = 2;
         NpcBestiaryRarityStars[483] = 2;
         NpcBestiaryRarityStars[184] = 2;
         NpcBestiaryRarityStars[185] = 3;
         NpcBestiaryRarityStars[206] = 3;
         NpcBestiaryRarityStars[541] = 4;
         NpcBestiaryRarityStars[537] = 2;
         NpcBestiaryRarityStars[205] = 4;
         NpcBestiaryRarityStars[499] = 2;
         NpcBestiaryRarityStars[494] = 2;
         NpcBestiaryRarityStars[496] = 2;
         NpcBestiaryRarityStars[302] = 3;
         NpcBestiaryRarityStars[317] = 3;
         NpcBestiaryRarityStars[318] = 3;
         NpcBestiaryRarityStars[319] = 3;
         NpcBestiaryRarityStars[320] = 3;
         NpcBestiaryRarityStars[321] = 3;
         NpcBestiaryRarityStars[331] = 3;
         NpcBestiaryRarityStars[332] = 3;
         NpcBestiaryRarityStars[322] = 3;
         NpcBestiaryRarityStars[323] = 3;
         NpcBestiaryRarityStars[324] = 3;
         NpcBestiaryRarityStars[335] = 3;
         NpcBestiaryRarityStars[336] = 3;
         NpcBestiaryRarityStars[333] = 3;
         NpcBestiaryRarityStars[334] = 3;
         NpcBestiaryRarityStars[4] = 2;
         NpcBestiaryRarityStars[50] = 2;
         NpcBestiaryRarityStars[35] = 3;
         NpcBestiaryRarityStars[13] = 3;
         NpcBestiaryRarityStars[134] = 4;
         NpcBestiaryRarityStars[262] = 4;
         NpcBestiaryRarityStars[668] = 3;
     }
References NPCID.Count, NPCSpawnParams.gameModeData, GetNPCBestiaryRarityStarsCount(), NPC, NpcBestiaryRarityStars, Main.RegisteredGameModes, and NPC.SetDefaults().
Referenced by Initialize().