Terraria: SpelunkerProjectileHelper.CheckSpot
CheckSpot()
void SpelunkerProjectileHelper.CheckSpot (Vector2 Center) inline private
     {
         int num = (int)Center.X / 16;
         int num2 = (int)Center.Y / 16;
         int num3 = Utils.Clamp(num - 30, _clampBox.Left, _clampBox.Right);
         int num4 = Utils.Clamp(num + 30, _clampBox.Left, _clampBox.Right);
         int num5 = Utils.Clamp(num2 - 30, _clampBox.Top, _clampBox.Bottom);
         int num6 = Utils.Clamp(num2 + 30, _clampBox.Top, _clampBox.Bottom);
         Point item = default(Point);
         Vector2 position = default(Vector2);
         for (int i = num3; i <= num4; i++)
         {
             for (int j = num5; j <= num6; j++)
             {
                 Tile tile = Main.tile[i, j];
                 if (tile != null && tile.active() && Main.IsTileSpelunkable(tile) && !(new Vector2(num - i, num2 - j).Length() > 30f))
                 {
                     item.X = i;
                     item.Y = j;
                     if (_tilesChecked.Add(item) && Main.rand.Next(4) == 0)
                     {
                         position.X = i * 16;
                         position.Y = j * 16;
                         Dust dust = Dust.NewDustDirect(position, 16, 16, 204, 0f, 0f, 150, default(Color), 0.3f);
                         dust.fadeIn = 0.75f;
                         dust.velocity *= 0.1f;
                         dust.noLight = true;
                     }
                 }
             }
         }
     }
References _clampBox, _tilesChecked, Tile.active(), Color, Dust.fadeIn, Main.IsTileSpelunkable(), Dust.NewDustDirect(), UnifiedRandom.Next(), Dust.noLight, Main.rand, Main.tile, and Dust.velocity.
Referenced by AddSpotToCheck().