Terraria: System.Text.Unicode.Utf8.ToUtf16
ToUtf16()
static unsafe OperationStatus System.Text.Unicode.Utf8.ToUtf16 (ReadOnlySpan< byte > source, Span< char > destination, out int bytesRead, out int charsWritten, bool replaceInvalidSequences = true, bool isFinalBlock = true) inline static
Definition at line 54 of file Utf8.cs.
    {
        _ = source.Length;
        _ = destination.Length;
        fixed (byte* ptr = &MemoryMarshal.GetReference(source))
        {
            fixed (char* ptr2 = &MemoryMarshal.GetReference(destination))
            {
                OperationStatus operationStatus = OperationStatus.Done;
                byte* pInputBufferRemaining = ptr;
                char* pOutputBufferRemaining = ptr2;
                while (!source.IsEmpty)
                {
                    operationStatus = Utf8Utility.TranscodeToUtf16((byte*)Unsafe.AsPointer(ref MemoryMarshal.GetReference(source)), source.Length, (char*)Unsafe.AsPointer(ref MemoryMarshal.GetReference(destination)), destination.Length, out pInputBufferRemaining, out pOutputBufferRemaining);
                    if (operationStatus <= OperationStatus.DestinationTooSmall || (operationStatus == OperationStatus.NeedMoreData && !isFinalBlock))
                    {
                        break;
                    }
                    if (!replaceInvalidSequences)
                    {
                        operationStatus = OperationStatus.InvalidData;
                        break;
                    }
                    destination = destination.Slice((int)(pOutputBufferRemaining - (char*)Unsafe.AsPointer(ref MemoryMarshal.GetReference(destination))));
                    if (destination.IsEmpty)
                    {
                        operationStatus = OperationStatus.DestinationTooSmall;
                        break;
                    }
                    destination[0] = '\ufffd';
                    destination = destination.Slice(1);
                    source = source.Slice((int)(pInputBufferRemaining - (byte*)Unsafe.AsPointer(ref MemoryMarshal.GetReference(source))));
                    Rune.DecodeFromUtf8(source, out var _, out var bytesConsumed);
                    source = source.Slice(bytesConsumed);
                    operationStatus = OperationStatus.Done;
                    pInputBufferRemaining = (byte*)Unsafe.AsPointer(ref MemoryMarshal.GetReference(source));
                    pOutputBufferRemaining = (char*)Unsafe.AsPointer(ref MemoryMarshal.GetReference(destination));
                }
                bytesRead = (int)(pInputBufferRemaining - ptr);
                charsWritten = (int)(pOutputBufferRemaining - ptr2);
                return operationStatus;
            }
        }
    }
References System.Text.Rune.DecodeFromUtf8(), System.destination, System.source, and System.Text.Unicode.Utf8Utility.TranscodeToUtf16().
Referenced by System.Text.UTF8Encoding.GetCharsWithFallback(), and System.Net.Http.Headers.HeaderDescriptor.TryDecodeUtf8().