Terraria: System.IO.Compression.ZipArchiveEntry.DirectToArchiveWriterStream.Write
Write() [1/2]
override void System.IO.Compression.ZipArchiveEntry.DirectToArchiveWriterStream.Write (byte[] buffer, int offset, int count) inline
Definition at line 94 of file ZipArchiveEntry.cs.
        {
            Stream.ValidateBufferArguments(buffer, offset, count);
            ThrowIfDisposed();
            if (count != 0)
            {
                if (!_everWritten)
                {
                    _everWritten = true;
                    _usedZip64inLH = _entry.WriteLocalFileHeader(isEmptyFile: false);
                }
                _crcSizeStream.Write(buffer, offset, count);
                _position += count;
            }
        }
References System.IO.Compression.ZipArchiveEntry.DirectToArchiveWriterStream._crcSizeStream, System.IO.Compression.ZipArchiveEntry.DirectToArchiveWriterStream._entry, System.IO.Compression.ZipArchiveEntry.DirectToArchiveWriterStream._everWritten, System.IO.Compression.ZipArchiveEntry.DirectToArchiveWriterStream._position, System.IO.Compression.ZipArchiveEntry.DirectToArchiveWriterStream._usedZip64inLH, System.buffer, System.count, System.offset, System.IO.Compression.ZipArchiveEntry.DirectToArchiveWriterStream.ThrowIfDisposed(), System.IO.Stream.ValidateBufferArguments(), System.IO.Compression.CheckSumAndSizeWriteStream.Write(), and System.IO.Compression.ZipArchiveEntry.WriteLocalFileHeader().