Terraria: System.IO.Compression.ZipArchiveEntry.DirectToArchiveWriterStream.Dispose
Dispose() [2/2]
override void System.IO.Compression.ZipArchiveEntry.DirectToArchiveWriterStream.Dispose (bool disposing) inline protected virtual
Reimplemented from System.IO.Stream.
Definition at line 168 of file ZipArchiveEntry.cs.
        {
            if (disposing && !_isDisposed)
            {
                _crcSizeStream.Dispose();
                if (!_everWritten)
                {
                    _entry.WriteLocalFileHeader(isEmptyFile: true);
                }
                else if (_entry._archive.ArchiveStream.CanSeek)
                {
                    _entry.WriteCrcAndSizesInLocalHeader(_usedZip64inLH);
                }
                else
                {
                    _entry.WriteDataDescriptor();
                }
                _canWrite = false;
                _isDisposed = true;
            }
            base.Dispose(disposing);
        }
References System.IO.Compression.ZipArchiveEntry._archive, System.IO.Compression.ZipArchiveEntry.DirectToArchiveWriterStream._canWrite, System.IO.Compression.ZipArchiveEntry.DirectToArchiveWriterStream._crcSizeStream, System.IO.Compression.ZipArchiveEntry.DirectToArchiveWriterStream._entry, System.IO.Compression.ZipArchiveEntry.DirectToArchiveWriterStream._everWritten, System.IO.Compression.ZipArchiveEntry.DirectToArchiveWriterStream._isDisposed, System.IO.Compression.ZipArchiveEntry.DirectToArchiveWriterStream._usedZip64inLH, System.IO.Compression.ZipArchive.ArchiveStream, System.IO.Stream.CanSeek, System.IO.Compression.CheckSumAndSizeWriteStream.Dispose(), System.IO.Compression.ZipArchiveEntry.WriteCrcAndSizesInLocalHeader(), System.IO.Compression.ZipArchiveEntry.WriteDataDescriptor(), and System.IO.Compression.ZipArchiveEntry.WriteLocalFileHeader().