Terraria: System.IO.Compression.ZipArchiveEntry.DirectToArchiveWriterStream.Write
Write() [2/2]
override void System.IO.Compression.ZipArchiveEntry.DirectToArchiveWriterStream.Write (ReadOnlySpan< byte > source) inline virtual
Reimplemented from System.IO.Stream.
Definition at line 110 of file ZipArchiveEntry.cs.
        {
            ThrowIfDisposed();
            if (source.Length != 0)
            {
                if (!_everWritten)
                {
                    _everWritten = true;
                    _usedZip64inLH = _entry.WriteLocalFileHeader(isEmptyFile: false);
                }
                _crcSizeStream.Write(source);
                _position += source.Length;
            }
        }
References System.IO.Compression.ZipArchiveEntry.DirectToArchiveWriterStream._crcSizeStream, System.IO.Compression.ZipArchiveEntry.DirectToArchiveWriterStream._entry, System.IO.Compression.ZipArchiveEntry.DirectToArchiveWriterStream._everWritten, System.IO.Compression.ZipArchiveEntry.DirectToArchiveWriterStream._position, System.IO.Compression.ZipArchiveEntry.DirectToArchiveWriterStream._usedZip64inLH, System.source, System.IO.Compression.ZipArchiveEntry.DirectToArchiveWriterStream.ThrowIfDisposed(), System.IO.Compression.CheckSumAndSizeWriteStream.Write(), and System.IO.Compression.ZipArchiveEntry.WriteLocalFileHeader().