Terraria: System.Xml.Xsl.XsltOld.ProcessingInstructionAction.Execute
Execute()
override void System.Xml.Xsl.XsltOld.ProcessingInstructionAction.Execute (Processor processor, ActionFrame frame) inline package
Definition at line 47 of file ProcessingInstructionAction.cs.
    {
        switch (frame.State)
        {
        case 0:
            if (_nameAvt == null)
            {
                frame.StoredOutput = _name;
                if (_name == null)
                {
                    frame.Finished();
                    break;
                }
            }
            else
            {
                frame.StoredOutput = _nameAvt.Evaluate(processor, frame);
                if (!IsProcessingInstructionName(frame.StoredOutput))
                {
                    frame.Finished();
                    break;
                }
            }
            goto case 3;
        case 3:
            if (!processor.BeginEvent(XPathNodeType.ProcessingInstruction, string.Empty, frame.StoredOutput, string.Empty, empty: false))
            {
                frame.State = 3;
                break;
            }
            processor.PushActionFrame(frame);
            frame.State = 1;
            break;
        case 1:
            if (!processor.EndEvent(XPathNodeType.ProcessingInstruction))
            {
                frame.State = 1;
            }
            else
            {
                frame.Finished();
            }
            break;
        default:
            frame.Finished();
            break;
        }
    }
References System.Xml.Xsl.XsltOld.ProcessingInstructionAction._name, System.Xml.Xsl.XsltOld.ProcessingInstructionAction._nameAvt, System.Xml.Dictionary, System.Xml.Xsl.XsltOld.Avt.Evaluate(), System.Xml.Xsl.XsltOld.ActionFrame.Finished(), System.Xml.Xsl.XsltOld.ProcessingInstructionAction.IsProcessingInstructionName(), System.Xml.Xsl.XsltOld.ActionFrame.State, and System.Xml.Xsl.XsltOld.ActionFrame.StoredOutput.