Terraria: System.Xml.Xsl.XsltOld.ProcessingInstructionAction.Compile
Compile()
override void System.Xml.Xsl.XsltOld.ProcessingInstructionAction.Compile (Compiler compiler) inline package
Definition at line 15 of file ProcessingInstructionAction.cs.
    {
        CompileAttributes(compiler);
        CheckRequiredAttribute(compiler, _nameAvt, "name");
        if (_nameAvt.IsConstant)
        {
            _name = _nameAvt.Evaluate(null, null);
            _nameAvt = null;
            if (!IsProcessingInstructionName(_name))
            {
                _name = null;
            }
        }
        if (compiler.Recurse())
        {
            CompileTemplate(compiler);
            compiler.ToParent();
        }
    }
References System.Xml.Xsl.XsltOld.ProcessingInstructionAction._name, System.Xml.Xsl.XsltOld.ProcessingInstructionAction._nameAvt, System.Xml.Xsl.XsltOld.CompiledAction.CheckRequiredAttribute(), System.Xml.Xsl.XsltOld.CompiledAction.CompileAttributes(), System.Xml.Xsl.XsltOld.ContainerAction.CompileTemplate(), System.Xml.Dictionary, System.Xml.Xsl.XsltOld.Avt.Evaluate(), System.Xml.Xsl.XsltOld.Avt.IsConstant, and System.Xml.Xsl.XsltOld.ProcessingInstructionAction.IsProcessingInstructionName().