Terraria: Terraria.GameContent.UI.Elements.UITextBox.SetText
SetText() [1/3]
override void Terraria.GameContent.UI.Elements.UITextBox.SetText (string text, float textScale, bool large) inline
    {
        if (text == null)
        {
            text = "";
        }
        if (text.Length > _maxLength)
        {
            text = text.Substring(0, _maxLength);
        }
        base.SetText(text, textScale, large);
        _cursor = Math.Min(base.Text.Length, _cursor);
    }
References Terraria.GameContent.UI.Elements.UITextBox._cursor, and Terraria.GameContent.UI.Elements.UITextBox._maxLength.
Referenced by Terraria.GameContent.UI.Elements.UITextBox.Backspace(), Terraria.GameContent.UI.Elements.UISearchBar.SetContents(), Terraria.GameContent.UI.Elements.UISearchBar.TrimDisplayIfOverElementDimensions(), and Terraria.GameContent.UI.Elements.UITextBox.Write().