Terraria: Terraria.GameContent.UI.Elements.UITextBox.DrawSelf
DrawSelf() [1/2]
override void Terraria.GameContent.UI.Elements.UITextBox.DrawSelf (SpriteBatch spriteBatch) inline protected
Definition at line 74 of file UITextBox.cs.
    {
        if (HideSelf)
        {
            return;
        }
        _cursor = base.Text.Length;
        base.DrawSelf(spriteBatch);
        _frameCount++;
        if ((_frameCount %= 40) <= 20 && ShowInputTicker)
        {
            CalculatedStyle innerDimensions = GetInnerDimensions();
            Vector2 pos = innerDimensions.Position();
            Vector2 vector = new Vector2((base.IsLarge ? FontAssets.DeathText.Value : FontAssets.MouseText.Value).MeasureString(base.Text.Substring(0, _cursor)).X, base.IsLarge ? 32f : 16f) * base.TextScale;
            if (base.IsLarge)
            {
                pos.Y -= 8f * base.TextScale;
            }
            else
            {
                pos.Y -= 2f * base.TextScale;
            }
            pos.X += (innerDimensions.Width - base.TextSize.X) * TextHAlign + vector.X - (base.IsLarge ? 8f : 4f) * base.TextScale + 6f;
            if (base.IsLarge)
            {
                Utils.DrawBorderStringBig(spriteBatch, "|", pos, base.TextColor, base.TextScale);
            }
            else
            {
                Utils.DrawBorderString(spriteBatch, "|", pos, base.TextColor, base.TextScale);
            }
        }
    }
References Terraria.GameContent.UI.Elements.UITextBox._cursor, Terraria.GameContent.UI.Elements.UITextBox._frameCount, Terraria.GameContent.FontAssets.DeathText, Terraria.Utils.DrawBorderString(), Terraria.Utils.DrawBorderStringBig(), Terraria.GameContent.UI.Elements.UITextBox.HideSelf, Terraria.GameContent.FontAssets.MouseText, Terraria.UI.CalculatedStyle.Position(), Terraria.GameContent.UI.Elements.UITextBox.ShowInputTicker, Terraria.GameContent.UI.Elements.UITextPanel< string >.TextHAlign, Microsoft.Xna.Framework.Graphics.Vector2, Microsoft.Xna.Framework.Vector2.X, and System.X.