Terraria: PlayerDeathReason.GetDeathText
GetDeathText()
NetworkText PlayerDeathReason.GetDeathText (string deadPlayerName) inline
     {
         if (_sourceCustomReason != null)
         {
             return NetworkText.FromLiteral(_sourceCustomReason);
         }
         return Lang.CreateDeathMessage(deadPlayerName, _sourcePlayerIndex, _sourceNPCIndex, _sourceProjectileLocalIndex, _sourceOtherIndex, _sourceProjectileType, _sourceItemType);
     }
References _sourceCustomReason, _sourceItemType, _sourceNPCIndex, _sourceOtherIndex, _sourcePlayerIndex, _sourceProjectileLocalIndex, _sourceProjectileType, Lang.CreateDeathMessage(), and NetworkText.FromLiteral().
Referenced by Player.KillMe().