Terraria: AmbientSky.SkyEntity.CommonDraw
CommonDraw()
void AmbientSky.SkyEntity.CommonDraw (SpriteBatch spriteBatch, float depthScale, float minDepth, float maxDepth) inline inherited
         {
             if (!(Depth <= minDepth) && !(Depth > maxDepth))
             {
                 Vector2 drawPositionByDepth = GetDrawPositionByDepth();
                 Color color = GetColor(Main.ColorOfTheSkies) * Main.atmo;
                 Vector2 origin = SourceRectangle.Size() / 2f;
                 float scale = depthScale / Depth;
                 spriteBatch.Draw(Texture.Value, drawPositionByDepth - Main.Camera.UnscaledPosition, SourceRectangle, color, Rotation, origin, scale, Effects, 0f);
             }
         }
References Main.atmo, Main.Camera, Color, Main.ColorOfTheSkies, AmbientSky.SkyEntity.Depth, AmbientSky.SkyEntity.Effects, AmbientSky.SkyEntity.GetColor(), AmbientSky.SkyEntity.GetDrawPositionByDepth(), AmbientSky.SkyEntity.Rotation, AmbientSky.SkyEntity.SourceRectangle, AmbientSky.SkyEntity.Texture, Camera.UnscaledPosition, and Asset< T >.Value.
Referenced by AmbientSky.SkyEntity.Draw(), AmbientSky.PixiePosseSkyEntity.Draw(), AmbientSky.SeagullsGroupSkyEntity.Draw(), and AmbientSky.GastropodGroupSkyEntity.Draw().