Terraria: AmbientSky.SkyEntity.SetPositionInWorldBasedOnScreenSpace
SetPositionInWorldBasedOnScreenSpace()
void AmbientSky.SkyEntity.SetPositionInWorldBasedOnScreenSpace (Vector2 actualWorldSpace) inline protected inherited
         {
             Vector2 vector = actualWorldSpace - Main.Camera.Center;
             Vector2 position = Main.Camera.Center + vector * (Depth / 3f);
             Position = position;
         }
References Main.Camera, Camera.Center, AmbientSky.SkyEntity.Depth, and AmbientSky.SkyEntity.Position.
Referenced by AmbientSky.AirshipSkyEntity.AirshipSkyEntity(), AmbientSky.BatsGroupSkyEntity.BatsGroupSkyEntity(), AmbientSky.BirdsPackSkyEntity.BirdsPackSkyEntity(), AmbientSky.ButterfliesSkyEntity.ButterfliesSkyEntity(), AmbientSky.EOCSkyEntity.EOCSkyEntity(), AmbientSky.GastropodGroupSkyEntity.GastropodGroupSkyEntity(), AmbientSky.HellBatsGoupSkyEntity.HellBatsGoupSkyEntity(), AmbientSky.LostKiteSkyEntity.LostKiteSkyEntity(), AmbientSky.PegasusSkyEntity.PegasusSkyEntity(), AmbientSky.PixiePosseSkyEntity.PixiePosseSkyEntity(), AmbientSky.SeagullsGroupSkyEntity.SeagullsGroupSkyEntity(), AmbientSky.SlimeBalloonGroupSkyEntity.SlimeBalloonGroupSkyEntity(), AmbientSky.VultureSkyEntity.VultureSkyEntity(), AmbientSky.WyvernSkyEntity.WyvernSkyEntity(), AmbientSky.SeagullsGroupSkyEntity.CreateGroup(), AmbientSky.GastropodGroupSkyEntity.CreateGroup(), AmbientSky.SlimeBalloonGroupSkyEntity.CreateGroup(), AmbientSky.HellBatsGoupSkyEntity.CreateGroup(), and AmbientSky.BatsGroupSkyEntity.CreateGroup().