Terraria: AmbientSky.SkyEntity.GetDrawPositionByDepth
GetDrawPositionByDepth()
Vector2 AmbientSky.SkyEntity.GetDrawPositionByDepth () inline package inherited
         {
             return (GetDrawPosition() - Main.Camera.Center) * new Vector2(1f / Depth, 0.9f / Depth) + Main.Camera.Center;
         }
References Main.Camera, Camera.Center, AmbientSky.SkyEntity.Depth, and AmbientSky.SkyEntity.GetDrawPosition().
Referenced by AmbientSky.SkyEntity.CommonDraw(), and AmbientSky.SkyEntity.Helper_GetOpacityWithAccountingForOceanWaterLine().