Terraria: Internal.Cryptography.Pal.FindPal.PositiveBigIntegerFromByteArray
PositiveBigIntegerFromByteArray()
static BigInteger Internal.Cryptography.Pal.FindPal.PositiveBigIntegerFromByteArray (byte[] bytes) inline static package
Definition at line 236 of file FindPal.cs.
    {
        if (bytes.Length == 0 || bytes[^1] < 128)
        {
            return new BigInteger(bytes);
        }
        byte[] array = new byte[bytes.Length + 1];
        Buffer.BlockCopy(bytes, 0, array, 0, bytes.Length);
        return new BigInteger(array);
    }
References System.array, System.Buffer.BlockCopy(), and System.bytes.
Referenced by Internal.Cryptography.Pal.FindPal.FindBySerialNumber(), and Internal.Cryptography.Pal.FindPal.FindFromCollection().