Terraria: Internal.Cryptography.Pal.FindPal.FindCore< TState >
FindCore< TState >() [1/2]
unsafe void Internal.Cryptography.Pal.FindPal.FindCore< TState > (CertFindType dwFindType, void * pvFindPara, TState state = default(TState), Func< TState, SafeCertContextHandle, bool > filter = null) inline private
Definition at line 531 of file FindPal.cs.
    {
        SafeCertStoreHandle safeCertStoreHandle = global::Interop.crypt32.CertOpenStore(CertStoreProvider.CERT_STORE_PROV_MEMORY, CertEncodingType.All, IntPtr.Zero, CertStoreFlags.CERT_STORE_ENUM_ARCHIVED_FLAG | CertStoreFlags.CERT_STORE_CREATE_NEW_FLAG, null);
        if (safeCertStoreHandle.IsInvalid)
        {
            throw Marshal.GetHRForLastWin32Error().ToCryptographicException();
        }
        SafeCertContextHandle pCertContext = null;
        while (global::Interop.crypt32.CertFindCertificateInStore(_storePal.SafeCertStoreHandle, dwFindType, pvFindPara, ref pCertContext))
        {
            if ((filter == null || filter(state, pCertContext)) && (!_validOnly || VerifyCertificateIgnoringErrors(pCertContext)) && !global::Interop.crypt32.CertAddCertificateLinkToStore(safeCertStoreHandle, pCertContext, CertStoreAddDisposition.CERT_STORE_ADD_ALWAYS, IntPtr.Zero))
            {
                throw Marshal.GetLastWin32Error().ToCryptographicException();
            }
        }
        using StorePal storePal = new StorePal(safeCertStoreHandle);
        storePal.CopyTo(_copyTo);
    }
References Internal.Cryptography.Pal.FindPal._copyTo, Internal.Cryptography.Pal.FindPal._storePal, Internal.Cryptography.Pal.FindPal._validOnly, System.Collections.Generic.Dictionary< TKey, TValue >.CopyTo(), System.Runtime.InteropServices.Marshal.GetHRForLastWin32Error(), System.Runtime.InteropServices.Marshal.GetLastWin32Error(), Internal.Cryptography.Pal.StorePal.SafeCertStoreHandle, System.state, Internal.Cryptography.Pal.FindPal.VerifyCertificateIgnoringErrors(), and System.IntPtr.Zero.