Terraria: Internal.Cryptography.Pal.FindPal.FindFromCollection
FindFromCollection()
static X509Certificate2Collection Internal.Cryptography.Pal.FindPal.FindFromCollection (X509Certificate2Collection coll, X509FindType findType, object findValue, bool validOnly) inline static
Definition at line 59 of file FindPal.cs.
    {
        X509Certificate2Collection x509Certificate2Collection = new X509Certificate2Collection();
        using (IFindPal findPal = OpenPal(coll, x509Certificate2Collection, validOnly))
        {
            switch (findType)
            {
            case X509FindType.FindByThumbprint:
            {
                byte[] thumbprint = ConfirmedCast<string>(findValue).DecodeHexString();
                findPal.FindByThumbprint(thumbprint);
                break;
            }
            case X509FindType.FindBySubjectName:
            {
                string subjectName = ConfirmedCast<string>(findValue);
                findPal.FindBySubjectName(subjectName);
                break;
            }
            case X509FindType.FindBySubjectDistinguishedName:
            {
                string subjectDistinguishedName = ConfirmedCast<string>(findValue);
                findPal.FindBySubjectDistinguishedName(subjectDistinguishedName);
                break;
            }
            case X509FindType.FindByIssuerName:
            {
                string issuerName = ConfirmedCast<string>(findValue);
                findPal.FindByIssuerName(issuerName);
                break;
            }
            case X509FindType.FindByIssuerDistinguishedName:
            {
                string issuerDistinguishedName = ConfirmedCast<string>(findValue);
                findPal.FindByIssuerDistinguishedName(issuerDistinguishedName);
                break;
            }
            case X509FindType.FindBySerialNumber:
            {
                string text = ConfirmedCast<string>(findValue);
                byte[] array = text.DecodeHexString();
                Array.Reverse(array);
                BigInteger hexValue = PositiveBigIntegerFromByteArray(array);
                BigInteger decimalValue = LaxParseDecimalBigInteger(text);
                findPal.FindBySerialNumber(hexValue, decimalValue);
                break;
            }
            case X509FindType.FindByTimeValid:
            {
                DateTime dateTime3 = ConfirmedCast<DateTime>(findValue);
                findPal.FindByTimeValid(dateTime3);
                break;
            }
            case X509FindType.FindByTimeNotYetValid:
            {
                DateTime dateTime2 = ConfirmedCast<DateTime>(findValue);
                findPal.FindByTimeNotYetValid(dateTime2);
                break;
            }
            case X509FindType.FindByTimeExpired:
            {
                DateTime dateTime = ConfirmedCast<DateTime>(findValue);
                findPal.FindByTimeExpired(dateTime);
                break;
            }
            case X509FindType.FindByTemplateName:
            {
                string templateName = ConfirmedCast<string>(findValue);
                findPal.FindByTemplateName(templateName);
                break;
            }
            case X509FindType.FindByApplicationPolicy:
            {
                string oidValue3 = ConfirmedOidValue(findPal, findValue, OidGroup.Policy);
                findPal.FindByApplicationPolicy(oidValue3);
                break;
            }
            case X509FindType.FindByCertificatePolicy:
            {
                string oidValue2 = ConfirmedOidValue(findPal, findValue, OidGroup.Policy);
                findPal.FindByCertificatePolicy(oidValue2);
                break;
            }
            case X509FindType.FindByExtension:
            {
                string oidValue = ConfirmedOidValue(findPal, findValue, OidGroup.ExtensionOrAttribute);
                findPal.FindByExtension(oidValue);
                break;
            }
            case X509FindType.FindByKeyUsage:
            {
                X509KeyUsageFlags keyUsage = ConfirmedX509KeyUsage(findValue);
                findPal.FindByKeyUsage(keyUsage);
                break;
            }
            case X509FindType.FindBySubjectKeyIdentifier:
            {
                byte[] keyIdentifier = ConfirmedCast<string>(findValue).DecodeHexString();
                findPal.FindBySubjectKeyIdentifier(keyIdentifier);
                break;
            }
            default:
                throw new CryptographicException(System.SR.Cryptography_X509_InvalidFindType);
            }
        }
        return x509Certificate2Collection;
    }
References System.array, Internal.Cryptography.Pal.FindPal.ConfirmedOidValue(), Internal.Cryptography.Pal.FindPal.ConfirmedX509KeyUsage(), System.SR.Cryptography_X509_InvalidFindType, Internal.Cryptography.Pal.FindPal.LaxParseDecimalBigInteger(), Internal.Cryptography.Pal.FindPal.OpenPal(), Internal.Cryptography.Pal.FindPal.PositiveBigIntegerFromByteArray(), System.Array.Reverse(), and System.text.
Referenced by System.Security.Cryptography.X509Certificates.X509Certificate2Collection.Find().