Terraria: Internal.Cryptography.Pal.FindPal.FindByTime
FindByTime()
unsafe void Internal.Cryptography.Pal.FindPal.FindByTime (DateTime dateTime, int compareResult) inline private
Definition at line 354 of file FindPal.cs.
    {
        FILETIME item = FILETIME.FromDateTime(dateTime);
        FindCore((item, compareResult), delegate((FILETIME fileTime, int compareResult) state, SafeCertContextHandle pCertContext)
        {
            int num = global::Interop.crypt32.CertVerifyTimeValidity(ref state.fileTime, pCertContext.CertContext->pCertInfo);
            GC.KeepAlive(pCertContext);
            return num == state.compareResult;
        });
    }
References Internal.Cryptography.Pal.Native.SafeCertContextHandle.CertContext, Internal.Cryptography.Pal.Native.FILETIME.FromDateTime(), System.item, System.GC.KeepAlive(), Internal.Cryptography.Pal.Native.CERT_CONTEXT.pCertInfo, and System.state.
Referenced by Internal.Cryptography.Pal.FindPal.FindByTimeExpired(), Internal.Cryptography.Pal.FindPal.FindByTimeNotYetValid(), and Internal.Cryptography.Pal.FindPal.FindByTimeValid().