Terraria: Internal.Cryptography.Pal.FindPal.VerifyCertificateIgnoringErrors
VerifyCertificateIgnoringErrors()
static bool Internal.Cryptography.Pal.FindPal.VerifyCertificateIgnoringErrors (SafeCertContextHandle pCertContext) inline static private
Definition at line 550 of file FindPal.cs.
    {
        ChainPal chainPal = ChainPal.BuildChain(useMachineContext: false, CertificatePal.FromHandle(pCertContext.DangerousGetHandle()), null, null, null, X509RevocationMode.NoCheck, X509RevocationFlag.ExcludeRoot, null, X509ChainTrustMode.System, DateTime.Now, new TimeSpan(0, 0, 0), disableAia: false);
        if (chainPal == null)
        {
            return false;
        }
        using (chainPal)
        {
            if (!chainPal.Verify(X509VerificationFlags.NoFlag, out var _).GetValueOrDefault())
            {
                return false;
            }
        }
        return true;
    }
References Internal.Cryptography.Pal.ChainPal.BuildChain(), Internal.Cryptography.Pal.CertificatePal.FromHandle(), and System.DateTime.Now.
Referenced by Internal.Cryptography.Pal.FindPal.FindCore< TState >().