Terraria: Internal.Cryptography.Pal.FindPal.FindByTemplateName
FindByTemplateName()
unsafe void Internal.Cryptography.Pal.FindPal.FindByTemplateName (string templateName) inline
Implements Internal.Cryptography.Pal.IFindPal.
Definition at line 365 of file FindPal.cs.
    {
        FindCore(templateName, delegate(string templateName, SafeCertContextHandle pCertContext)
        {
            bool foundMatch = false;
            CERT_INFO* pCertInfo = pCertContext.CertContext->pCertInfo;
            CERT_EXTENSION* ptr = global::Interop.crypt32.CertFindExtension("1.3.6.1.4.1.311.20.2", pCertInfo->cExtension, pCertInfo->rgExtension);
            if (ptr != null)
            {
                byte[] encoded = ptr->Value.ToByteArray();
                if (!encoded.DecodeObjectNoThrow(CryptDecodeObjectStructType.X509_UNICODE_ANY_STRING, delegate(void* pvDecoded, int cbDecoded)
                {
                    string value2 = Marshal.PtrToStringUni(new IntPtr(((CERT_NAME_VALUE*)pvDecoded)->Value.pbData));
                    if (templateName.Equals(value2, StringComparison.OrdinalIgnoreCase))
                    {
                        foundMatch = true;
                    }
                }))
                {
                    return false;
                }
            }
            if (!foundMatch)
            {
                CERT_EXTENSION* ptr2 = global::Interop.crypt32.CertFindExtension("1.3.6.1.4.1.311.21.7", pCertInfo->cExtension, pCertInfo->rgExtension);
                if (ptr2 != null)
                {
                    byte[] encoded2 = ptr2->Value.ToByteArray();
                    if (!encoded2.DecodeObjectNoThrow(CryptDecodeObjectStructType.X509_CERTIFICATE_TEMPLATE, delegate(void* pvDecoded, int cbDecoded)
                    {
                        string value = Marshal.PtrToStringAnsi(((CERT_TEMPLATE_EXT*)pvDecoded)->pszObjId);
                        string text = global::Interop.Crypt32.FindOidInfo(global::Interop.Crypt32.CryptOidInfoKeyType.CRYPT_OID_INFO_NAME_KEY, templateName, OidGroup.Template, fallBackToAllGroups: true).OID;
                        if (text == null)
{
                            text = templateName;
                        }
                        if (text.Equals(value, StringComparison.OrdinalIgnoreCase))
{
                            foundMatch = true;
                        }
                    }))
                    {
                        return false;
                    }
                }
            }
            GC.KeepAlive(pCertContext);
            return foundMatch;
        });
    }
References Internal.Cryptography.Pal.Native.SafeCertContextHandle.CertContext, Internal.Cryptography.Pal.Native.CERT_INFO.cExtension, System.GC.KeepAlive(), Internal.Cryptography.Pal.Native.CERT_CONTEXT.pCertInfo, System.Runtime.InteropServices.Marshal.PtrToStringAnsi(), System.Runtime.InteropServices.Marshal.PtrToStringUni(), Internal.Cryptography.Pal.Native.CERT_INFO.rgExtension, System.text, and System.value.