Terraria: System.Xml.Xsl.XsltOld.TemplateLookupAction.Execute
Execute()
override void System.Xml.Xsl.XsltOld.TemplateLookupAction.Execute (Processor processor, ActionFrame frame) inline package
Definition at line 17 of file TemplateLookupAction.cs.
    {
        Action action = null;
        action = ((!(mode != null)) ? ((importsOf == null) ? processor.Stylesheet.FindTemplate(processor, frame.Node) : importsOf.FindTemplateImports(processor, frame.Node)) : ((importsOf == null) ? processor.Stylesheet.FindTemplate(processor, frame.Node, mode) : importsOf.FindTemplateImports(processor, frame.Node, mode)));
        if (action == null)
        {
            action = BuiltInTemplate(frame.Node);
        }
        if (action != null)
        {
            frame.SetAction(action);
        }
        else
        {
            frame.Finished();
        }
    }
References System.action, System.Xml.Xsl.XsltOld.TemplateLookupAction.BuiltInTemplate(), System.Xml.Dictionary, System.Xml.Xsl.XsltOld.Stylesheet.FindTemplateImports(), System.Xml.Xsl.XsltOld.ActionFrame.Finished(), System.Xml.Xsl.XsltOld.TemplateLookupAction.importsOf, System.Xml.Xsl.XsltOld.TemplateLookupAction.mode, System.Xml.Xsl.XsltOld.ActionFrame.Node, and System.Xml.Xsl.XsltOld.ActionFrame.SetAction().