Terraria: PopupText.NewText
NewText() [2/3]
static int PopupText.NewText (PopupTextContext context, int npcNetID, Vector2 position, bool stay5TimesLonger) inline static
     {
         if (!Main.showItemText)
         {
             return -1;
         }
         if (npcNetID == 0)
         {
             return -1;
         }
         if (Main.netMode == 2)
         {
             return -1;
         }
         int num = FindNextItemTextSlot();
         if (num >= 0)
         {
             NPC nPC = new NPC();
             nPC.SetDefaults(npcNetID);
             string typeName = nPC.TypeName;
             Vector2 vector = FontAssets.MouseText.Value.MeasureString(typeName);
             PopupText popupText = Main.popupText[num];
             ResetText(popupText);
             popupText.active = true;
             popupText.position = position - vector / 2f;
             popupText.name = typeName;
             popupText.stack = 1L;
             popupText.velocity.Y = -7f;
             popupText.lifeTime = 60;
             popupText.context = context;
             if (stay5TimesLonger)
             {
                 popupText.lifeTime *= 5;
             }
             popupText.npcNetID = npcNetID;
             popupText.color = Color.White;
             if (context == PopupTextContext.SonarAlert)
             {
                 popupText.color = Color.Lerp(Color.White, Color.Crimson, 0.5f);
             }
         }
         return num;
     }
References active, Color, color, context, FindNextItemTextSlot(), L, lifeTime, FontAssets.MouseText, name, Main.netMode, NPC, npcNetID, Main.popupText, position, ResetText(), NPC.SetDefaults(), Main.showItemText, stack, NPC.TypeName, Asset< T >.Value, and velocity.