Terraria: PopupText.NewText
NewText() [1/3]
static int PopupText.NewText (AdvancedPopupRequest request, Vector2 position) inline static
     {
         if (!Main.showItemText)
         {
             return -1;
         }
         if (Main.netMode == 2)
         {
             return -1;
         }
         int num = FindNextItemTextSlot();
         if (num >= 0)
         {
             string text = request.Text;
             Vector2 vector = FontAssets.MouseText.Value.MeasureString(text);
             PopupText obj = Main.popupText[num];
             ResetText(obj);
             obj.active = true;
             obj.position = position - vector / 2f;
             obj.name = text;
             obj.stack = 1L;
             obj.velocity = request.Velocity;
             obj.lifeTime = request.DurationInFrames;
             obj.context = PopupTextContext.Advanced;
             obj.freeAdvanced = true;
             obj.color = request.Color;
         }
         return num;
     }
References active, AdvancedPopupRequest.Color, color, context, AdvancedPopupRequest.DurationInFrames, FindNextItemTextSlot(), freeAdvanced, L, lifeTime, FontAssets.MouseText, name, Main.netMode, Main.popupText, position, ResetText(), Main.showItemText, stack, AdvancedPopupRequest.Text, Asset< T >.Value, AdvancedPopupRequest.Velocity, and velocity.
Referenced by Projectile.AI_061_FishingBobber_GiveItemToPlayer(), Main.CraftItem(), Main.DrawInventory(), Player.FillAmmo(), Projectile.FishingCheck(), Player.GetItem_FillEmptyInventorySlot(), Player.GetItem_FillEmptyInventorySlot_VoidBag(), Player.GetItem_FillIntoOccupiedSlot(), Player.GetItem_FillIntoOccupiedSlot_VoidBag(), Player.PutItemInInventoryFromItemUsage(), and LucyAxeMessage.SpawnPopupText().