Terraria: UIBestiaryFilteringOptionsGrid.BuildContainer
BuildContainer()
void UIBestiaryFilteringOptionsGrid.BuildContainer () inline private
     {
         GetDisplaySettings(out var _, out var _, out var widthWithSpacing, out var heightWithSpacing, out var perRow, out var _, out var _, out var howManyRows);
         UIPanel uIPanel = new UIPanel
         {
             Width = new StyleDimension(perRow * widthWithSpacing + 10, 0f),
             Height = new StyleDimension(howManyRows * heightWithSpacing + 10, 0f),
             HAlign = 1f,
             VAlign = 0f,
             Left = new StyleDimension(0f, 0f),
             Top = new StyleDimension(0f, 0f)
         };
         uIPanel.BorderColor = new Color(89, 116, 213, 255) * 0.9f;
         uIPanel.BackgroundColor = new Color(73, 94, 171) * 0.9f;
         uIPanel.SetPadding(0f);
         Append(uIPanel);
         _container = uIPanel;
     }
References _container, UIElement.Append(), UIPanel.BackgroundColor, UIPanel.BorderColor, Color, GetDisplaySettings(), UIElement.HAlign, UIElement.Height, UIElement.Left, UIElement.SetPadding(), UIElement.Top, UIElement.VAlign, and UIElement.Width.
Referenced by UIBestiaryFilteringOptionsGrid().