Terraria: Terraria.GameContent.Biomes.DesertBiome.Place
Place()
override bool Terraria.GameContent.Biomes.DesertBiome.Place (Point origin, StructureMap structures) inline
    {
        DesertDescription desertDescription = DesertDescription.CreateFromPlacement(origin);
        if (!desertDescription.IsValid)
        {
            return false;
        }
        ExportDescriptionToEngine(desertDescription);
        SandMound.Place(desertDescription);
        desertDescription.UpdateSurfaceMap();
        if (!Main.tenthAnniversaryWorld && GenBase._random.NextDouble() <= ChanceOfEntrance)
        {
            switch (GenBase._random.Next(4))
            {
            case 0:
                ChambersEntrance.Place(desertDescription);
                break;
            case 1:
                AnthillEntrance.Place(desertDescription);
                break;
            case 2:
                LarvaHoleEntrance.Place(desertDescription);
                break;
            case 3:
                PitEntrance.Place(desertDescription);
                break;
            }
        }
        DesertHive.Place(desertDescription);
        CleanupArea(desertDescription.Hive);
        Rectangle area = new Rectangle(desertDescription.CombinedArea.X, 50, desertDescription.CombinedArea.Width, desertDescription.CombinedArea.Bottom - 20);
        structures.AddStructure(area, 10);
        return true;
    }
References Terraria.WorldBuilding.GenBase._random, Terraria.WorldBuilding.StructureMap.AddStructure(), Terraria.GameContent.Biomes.DesertBiome.ChanceOfEntrance, Terraria.GameContent.Biomes.DesertBiome.CleanupArea(), Terraria.GameContent.Biomes.Desert.DesertDescription.CombinedArea, Terraria.GameContent.Biomes.Desert.DesertDescription.CreateFromPlacement(), Terraria.GameContent.Biomes.DesertBiome.ExportDescriptionToEngine(), Terraria.GameContent.Biomes.Desert.DesertDescription.Hive, Terraria.GameContent.Biomes.Desert.DesertDescription.IsValid, Terraria.GameContent.Biomes.Desert.AnthillEntrance.Place(), Terraria.GameContent.Biomes.Desert.ChambersEntrance.Place(), Terraria.GameContent.Biomes.Desert.DesertHive.Place(), Terraria.GameContent.Biomes.Desert.LarvaHoleEntrance.Place(), Terraria.GameContent.Biomes.Desert.PitEntrance.Place(), Terraria.GameContent.Biomes.Desert.SandMound.Place(), Terraria.Main.tenthAnniversaryWorld, and Terraria.GameContent.Biomes.Desert.DesertDescription.UpdateSurfaceMap().
Referenced by Terraria.WorldGen.GenerateWorld().