Terraria: System.Linq.Expressions.Compiler.StackSpiller.MemberAssignmentRewriter.AsExpression
AsExpression()
override Expression System.Linq.Expressions.Compiler.StackSpiller.MemberAssignmentRewriter.AsExpression (Expression target) inline package
Definition at line 229 of file StackSpiller.cs.
        {
            Expression expression = MemberExpression.Make(target, _binding.Member);
            Expression expression2 = _spiller.MakeTemp(expression.Type);
            return MakeBlock(new AssignBinaryExpression(expression2, _rhs), new AssignBinaryExpression(expression, expression2), Utils.Empty);
        }
References System.Linq.Expressions.Compiler.StackSpiller.BindingRewriter._binding, System.Linq.Expressions.Compiler.StackSpiller.MemberAssignmentRewriter._rhs, System.Linq.Expressions.Compiler.StackSpiller.BindingRewriter._spiller, System.Linq.Expressions.Utils.Empty, System.Linq.Expressions.MemberExpression.Make(), System.Linq.Expressions.Compiler.StackSpiller.MakeBlock(), System.Linq.Expressions.Compiler.StackSpiller.MakeTemp(), and System.Linq.Expressions.MemberBinding.Member.