Terraria: System.Dynamic.ExpandoClass.FindNewClass
FindNewClass()
ExpandoClass System.Dynamic.ExpandoClass.FindNewClass (string newKey) inline package
Definition at line 29 of file ExpandoClass.cs.
    {
        int hashCode = _hashCode ^ newKey.GetHashCode();
        lock (this)
        {
            List<WeakReference> transitionList = GetTransitionList(hashCode);
            for (int i = 0; i < transitionList.Count; i++)
            {
                if (!(transitionList[i].Target is ExpandoClass expandoClass))
                {
                    transitionList.RemoveAt(i);
                    i--;
                }
                else if (string.Equals(expandoClass._keys[expandoClass._keys.Length - 1], newKey, StringComparison.Ordinal))
                {
                    return expandoClass;
                }
            }
            string[] array = new string[_keys.Length + 1];
            Array.Copy(_keys, array, _keys.Length);
            array[_keys.Length] = newKey;
            ExpandoClass expandoClass2 = new ExpandoClass(array, hashCode);
            transitionList.Add(new WeakReference(expandoClass2));
            return expandoClass2;
        }
    }
References System.Dynamic.ExpandoClass.ExpandoClass(), System.Dynamic.ExpandoClass._hashCode, System.Dynamic.ExpandoClass._keys, System.Collections.Generic.Dictionary< TKey, TValue >._keys, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.array, System.Array.Copy(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, and System.Dynamic.ExpandoClass.GetTransitionList().