Terraria: System.Net.NameResolutionTelemetry.AfterResolution
AfterResolution()
void System.Net.NameResolutionTelemetry.AfterResolution (ValueStopwatch stopwatch, bool successful) inline
Definition at line 91 of file NameResolutionTelemetry.cs.
    {
        if (!stopwatch.IsActive)
        {
            return;
        }
        Interlocked.Decrement(ref _currentLookups);
        _lookupsDuration.WriteMetric(stopwatch.GetElapsedTime().TotalMilliseconds);
        if (IsEnabled(EventLevel.Informational, EventKeywords.None))
        {
            if (!successful)
            {
                ResolutionFailed();
            }
            ResolutionStop();
        }
    }
References System.Net.NameResolutionTelemetry._currentLookups, System.Net.NameResolutionTelemetry._lookupsDuration, System.Threading.Interlocked.Decrement(), System.Diagnostics.Tracing.EventSource.IsEnabled(), System.Net.NameResolutionTelemetry.ResolutionFailed(), System.Net.NameResolutionTelemetry.ResolutionStop(), and System.Diagnostics.Tracing.EventCounter.WriteMetric().