Terraria: System.Dynamic.ExpandoClass.GetValueIndex
GetValueIndex()
int System.Dynamic.ExpandoClass.GetValueIndex (string name, bool caseInsensitive, ExpandoObject obj) inline package
Definition at line 69 of file ExpandoClass.cs.
    {
        if (caseInsensitive)
        {
            return GetValueIndexCaseInsensitive(name, obj);
        }
        return GetValueIndexCaseSensitive(name);
    }
References System.Dynamic.ExpandoClass.GetValueIndexCaseInsensitive(), System.Dynamic.ExpandoClass.GetValueIndexCaseSensitive(), and System.obj.
Referenced by System.Dynamic.ExpandoObject.TryDeleteValue(), and System.Dynamic.ExpandoObject.TryGetValue().