Terraria: System.Net.NameResolutionTelemetry.BeforeResolution
BeforeResolution()
ValueStopwatch System.Net.NameResolutionTelemetry.BeforeResolution (object hostNameOrAddress) inline
Definition at line 73 of file NameResolutionTelemetry.cs.
    {
        if (IsEnabled())
        {
            Interlocked.Increment(ref _lookupsRequested);
            Interlocked.Increment(ref _currentLookups);
            if (IsEnabled(EventLevel.Informational, EventKeywords.None))
            {
                string text2 = ((hostNameOrAddress is string text) ? text : ((hostNameOrAddress is KeyValuePair<string, AddressFamily> keyValuePair) ? keyValuePair.Key : ((hostNameOrAddress is IPAddress iPAddress) ? iPAddress.ToString() : ((!(hostNameOrAddress is KeyValuePair<IPAddress, AddressFamily> keyValuePair2)) ? null : keyValuePair2.Key.ToString()))));
                string hostNameOrAddress2 = text2;
                ResolutionStart(hostNameOrAddress2);
            }
            return ValueStopwatch.StartNew();
        }
        return default(ValueStopwatch);
    }
References System.Net.NameResolutionTelemetry._currentLookups, System.Net.NameResolutionTelemetry._lookupsRequested, System.Threading.Interlocked.Increment(), System.Diagnostics.Tracing.EventSource.IsEnabled(), System.Net.NameResolutionTelemetry.ResolutionStart(), Microsoft.Extensions.Internal.ValueStopwatch.StartNew(), and System.text.