Terraria: System.Net.NameResolutionTelemetry.Log
Log
readonly NameResolutionTelemetry System.Net.NameResolutionTelemetry.Log = new NameResolutionTelemetry() static
Definition at line 12 of file NameResolutionTelemetry.cs.
Referenced by System.Net.Dns.GetAddrInfoWithTelemetryAsync< T >(), System.Net.Dns.GetHostEntryOrAddressesCore(), System.Net.Dns.GetHostEntryOrAddressesCore(), System.Net.Dns.GetHostEntryOrAddressesCoreAsync(), System.Net.Dns.GetHostName(), System.Net.Dns.LogFailure(), and System.Net.Dns.RunAsync< TResult >().