Terraria: UIText.DrawSelf
DrawSelf()
override void UIText.DrawSelf (SpriteBatch spriteBatch) inline protected virtual
Reimplemented from UIElement.
     {
         base.DrawSelf(spriteBatch);
         VerifyTextState();
         CalculatedStyle innerDimensions = GetInnerDimensions();
         Vector2 position = innerDimensions.Position();
         if (_isLarge)
         {
             position.Y -= 10f * _textScale;
         }
         else
         {
             position.Y -= 2f * _textScale;
         }
         position.X += (innerDimensions.Width - _textSize.X) * TextOriginX;
         position.Y += (innerDimensions.Height - _textSize.Y) * TextOriginY;
         float num = _textScale;
         if (DynamicallyScaleDownToWidth && _textSize.X > innerDimensions.Width)
         {
             num *= innerDimensions.Width / _textSize.X;
         }
         DynamicSpriteFont value = (_isLarge ? FontAssets.DeathText : FontAssets.MouseText).Value;
         Vector2 vector = value.MeasureString(_visibleText);
         Color baseColor = _shadowColor * ((float)(int)_color.A / 255f);
         Vector2 origin = new Vector2(0f, 0f) * vector;
         Vector2 baseScale = new Vector2(num);
         TextSnippet[] snippets = ChatManager.ParseMessage(_visibleText, _color).ToArray();
         ChatManager.ConvertNormalSnippets(snippets);
         ChatManager.DrawColorCodedStringShadow(spriteBatch, value, snippets, position, baseColor, 0f, origin, baseScale, -1f, 1.5f);
         ChatManager.DrawColorCodedString(spriteBatch, value, snippets, position, Color.White, 0f, origin, baseScale, out var _, -1f);
     }
References _color, _isLarge, _shadowColor, _textScale, _textSize, _visibleText, Color, ChatManager.ConvertNormalSnippets(), FontAssets.DeathText, ChatManager.DrawColorCodedString(), ChatManager.DrawColorCodedStringShadow(), DynamicallyScaleDownToWidth, UIElement.GetInnerDimensions(), CalculatedStyle.Height, DynamicSpriteFont.MeasureString(), FontAssets.MouseText, ChatManager.ParseMessage(), CalculatedStyle.Position(), TextOriginX, TextOriginY, VerifyTextState(), and CalculatedStyle.Width.