Terraria: Wiring.HitSwitch
HitSwitch()
static void Wiring.HitSwitch (int i, int j) inline static
     {
         if (!WorldGen.InWorld(i, j) || Main.tile[i, j] == null)
         {
             return;
         }
         if (Main.tile[i, j].type == 135 || Main.tile[i, j].type == 314 || Main.tile[i, j].type == 423 || Main.tile[i, j].type == 428 || Main.tile[i, j].type == 442 || Main.tile[i, j].type == 476)
         {
             SoundEngine.PlaySound(28, i * 16, j * 16, 0);
             TripWire(i, j, 1, 1);
         }
         else if (Main.tile[i, j].type == 440)
         {
             SoundEngine.PlaySound(28, i * 16 + 16, j * 16 + 16, 0);
             TripWire(i, j, 3, 3);
         }
         else if (Main.tile[i, j].type == 136)
         {
             if (Main.tile[i, j].frameY == 0)
             {
                 Main.tile[i, j].frameY = 18;
             }
             else
             {
                 Main.tile[i, j].frameY = 0;
             }
             SoundEngine.PlaySound(28, i * 16, j * 16, 0);
             TripWire(i, j, 1, 1);
         }
         else if (Main.tile[i, j].type == 443)
         {
             GeyserTrap(i, j);
         }
         else if (Main.tile[i, j].type == 144)
         {
             if (Main.tile[i, j].frameY == 0)
             {
                 Main.tile[i, j].frameY = 18;
                 if (Main.netMode != 1)
                 {
                     CheckMech(i, j, 18000);
                 }
             }
             else
             {
                 Main.tile[i, j].frameY = 0;
             }
             SoundEngine.PlaySound(28, i * 16, j * 16, 0);
         }
         else if (Main.tile[i, j].type == 441 || Main.tile[i, j].type == 468)
         {
             int num = Main.tile[i, j].frameX / 18 * -1;
             int num2 = Main.tile[i, j].frameY / 18 * -1;
             num %= 4;
             if (num < -1)
             {
                 num += 2;
             }
             num += i;
             num2 += j;
             SoundEngine.PlaySound(28, i * 16, j * 16, 0);
             TripWire(num, num2, 2, 2);
         }
         else if (Main.tile[i, j].type == 467)
         {
             if (Main.tile[i, j].frameX / 36 == 4)
             {
                 int num3 = Main.tile[i, j].frameX / 18 * -1;
                 int num4 = Main.tile[i, j].frameY / 18 * -1;
                 num3 %= 4;
                 if (num3 < -1)
                 {
                     num3 += 2;
                 }
                 num3 += i;
                 num4 += j;
                 SoundEngine.PlaySound(28, i * 16, j * 16, 0);
                 TripWire(num3, num4, 2, 2);
             }
         }
         else
         {
             if (Main.tile[i, j].type != 132 && Main.tile[i, j].type != 411)
             {
                 return;
             }
             short num5 = 36;
             int num6 = Main.tile[i, j].frameX / 18 * -1;
             int num7 = Main.tile[i, j].frameY / 18 * -1;
             num6 %= 4;
             if (num6 < -1)
             {
                 num6 += 2;
                 num5 = -36;
             }
             num6 += i;
             num7 += j;
             if (Main.netMode != 1 && Main.tile[num6, num7].type == 411)
             {
                 CheckMech(num6, num7, 60);
             }
             for (int k = num6; k < num6 + 2; k++)
             {
                 for (int l = num7; l < num7 + 2; l++)
                 {
                     if (Main.tile[k, l].type == 132 || Main.tile[k, l].type == 411)
                     {
                         Main.tile[k, l].frameX += num5;
                     }
                 }
             }
             WorldGen.TileFrame(num6, num7);
             SoundEngine.PlaySound(28, i * 16, j * 16, 0);
             TripWire(num6, num7, 2, 2);
         }
     }
References CheckMech(), Tile.frameX, Tile.frameY, GeyserTrap(), WorldGen.InWorld(), Main.netMode, SoundEngine.PlaySound(), Main.tile, WorldGen.TileFrame(), TripWire(), and Tile.type.
Referenced by MessageBuffer.GetData(), Minecart.HitTrackSwitch(), HitWireSingle(), TELogicSensor.Kill(), PressurePlateHelper.PokeLocation(), GolfHelper.ContactListener.PutBallInCup(), WorldGen.ReplaceTIle_DoActualReplacement(), Collision.SwitchTiles(), Player.TileInteractionsUse(), WorldGen.ToggleGemLock(), Player.TryLandingOnDetonator(), and TELogicSensor.UpdateEndInternal().