Terraria: Wiring.XferWater
XferWater()
static void Wiring.XferWater () inline static private
     {
         for (int i = 0; i < _numInPump; i++)
         {
             int num = _inPumpX[i];
             int num2 = _inPumpY[i];
             int liquid = Main.tile[num, num2].liquid;
             if (liquid <= 0)
             {
                 continue;
             }
             byte b = Main.tile[num, num2].liquidType();
             for (int j = 0; j < _numOutPump; j++)
             {
                 int num3 = _outPumpX[j];
                 int num4 = _outPumpY[j];
                 int liquid2 = Main.tile[num3, num4].liquid;
                 if (liquid2 >= 255)
                 {
                     continue;
                 }
                 byte b2 = Main.tile[num3, num4].liquidType();
                 if (liquid2 == 0)
                 {
                     b2 = b;
                 }
                 if (b2 == b)
                 {
                     int num5 = liquid;
                     if (num5 + liquid2 > 255)
                     {
                         num5 = 255 - liquid2;
                     }
                     Main.tile[num3, num4].liquid += (byte)num5;
                     Main.tile[num, num2].liquid -= (byte)num5;
                     liquid = Main.tile[num, num2].liquid;
                     Main.tile[num3, num4].liquidType(b);
                     WorldGen.SquareTileFrame(num3, num4);
                     if (Main.tile[num, num2].liquid == 0)
                     {
                         Main.tile[num, num2].liquidType(0);
                         WorldGen.SquareTileFrame(num, num2);
                         break;
                     }
                 }
             }
             WorldGen.SquareTileFrame(num, num2);
         }
     }
References _inPumpX, _inPumpY, _numInPump, _numOutPump, _outPumpX, _outPumpY, Tile.liquid, Tile.liquidType(), WorldGen.SquareTileFrame(), and Main.tile.
Referenced by TripWire().