Terraria: System.Security.Cryptography.XmlKeyHelper.WriteCryptoBinary
WriteCryptoBinary() [1/2]
static void System.Security.Cryptography.XmlKeyHelper.WriteCryptoBinary (string name, int value, StringBuilder builder) inline static package
Definition at line 199 of file XmlKeyHelper.cs.
    {
        if (value == 0)
        {
            Span<byte> span = stackalloc byte[1];
            span[0] = 0;
            WriteCryptoBinary(name, span, builder);
            return;
        }
        Span<byte> destination = stackalloc byte[4];
        BinaryPrimitives.WriteInt32BigEndian(destination, value);
        int i;
        for (i = 0; destination[i] == 0; i++)
        {
        }
        WriteCryptoBinary(name, destination.Slice(i, destination.Length - i), builder);
    }
References System.destination, System.value, System.Security.Cryptography.XmlKeyHelper.WriteCryptoBinary(), and System.Buffers.Binary.BinaryPrimitives.WriteInt32BigEndian().
Referenced by System.Security.Cryptography.DSA.ToXmlString(), System.Security.Cryptography.RSA.ToXmlString(), and System.Security.Cryptography.XmlKeyHelper.WriteCryptoBinary().