Terraria: System.Security.Cryptography.XmlKeyHelper.WriteCryptoBinary
WriteCryptoBinary() [2/2]
static void System.Security.Cryptography.XmlKeyHelper.WriteCryptoBinary (string name, ReadOnlySpan< byte > value, StringBuilder builder) inline static package
Definition at line 217 of file XmlKeyHelper.cs.
    {
        builder.Append('<');
        builder.Append(name);
        builder.Append('>');
        int num = 0;
        int num2 = value.Length;
        Span<char> chars = stackalloc char[256];
        while (num2 > 0)
        {
            int num3 = Math.Min(192, num2);
            if (!Convert.TryToBase64Chars(value.Slice(num, num3), chars, out var charsWritten))
            {
                throw new CryptographicException();
            }
            builder.Append(chars.Slice(0, charsWritten));
            num2 -= num3;
            num += num3;
        }
        builder.Append('<');
        builder.Append('/');
        builder.Append(name);
        builder.Append('>');
    }
References System.Text.StringBuilder.Append(), System.chars, System.Text.StringBuilder.Length, System.Math.Min(), System.Convert.TryToBase64Chars(), and System.value.