Terraria: Wiring.UpdateMech
UpdateMech()
static void Wiring.UpdateMech () inline static
     {
         SetCurrentUser();
         for (int num = _numMechs - 1; num >= 0; num--)
         {
             _mechTime[num]--;
             int num2 = _mechX[num];
             int num3 = _mechY[num];
             if (!WorldGen.InWorld(num2, num3, 1))
             {
                 _numMechs--;
             }
             else
             {
                 Tile tile = Main.tile[num2, num3];
                 if (tile == null)
                 {
                     _numMechs--;
                 }
                 else
                 {
                     if (tile.active() && tile.type == 144)
                     {
                         if (tile.frameY == 0)
{
                             _mechTime[num] = 0;
                         }
                         else
{
                             int num4 = tile.frameX / 18;
                             switch (num4)
{
                             case 0:
                                 num4 = 60;
                                 break;
                             case 1:
                                 num4 = 180;
                                 break;
                             case 2:
                                 num4 = 300;
                                 break;
                             case 3:
                                 num4 = 30;
                                 break;
                             case 4:
                                 num4 = 15;
                                 break;
                             }
                             if (Math.IEEERemainder(_mechTime[num], num4) == 0.0)
{
                                 _mechTime[num] = 18000;
                                 TripWire(_mechX[num], _mechY[num], 1, 1);
                             }
                         }
                     }
                     if (_mechTime[num] <= 0)
                     {
                         if (tile.active() && tile.type == 144)
{
                             tile.frameY = 0;
                             NetMessage.SendTileSquare(-1, _mechX[num], _mechY[num]);
                         }
                         if (tile.active() && tile.type == 411)
{
                             int num5 = tile.frameX % 36 / 18;
                             int num6 = tile.frameY % 36 / 18;
                             int num7 = _mechX[num] - num5;
                             int num8 = _mechY[num] - num6;
                             int num9 = 36;
                             if (Main.tile[num7, num8].frameX >= 36)
{
                                 num9 = -36;
                             }
                             for (int i = num7; i < num7 + 2; i++)
{
                                 for (int j = num8; j < num8 + 2; j++)
{
                                     if (WorldGen.InWorld(i, j, 1))
{
                                         Tile tile2 = Main.tile[i, j];
                                         if (tile2 != null)
{
                                             tile2.frameX = (short)(tile2.frameX + num9);
                                         }
                                     }
                                 }
                             }
                             NetMessage.SendTileSquare(-1, num7, num8, 2, 2);
                         }
                         for (int k = num; k < _numMechs; k++)
{
                             _mechX[k] = _mechX[k + 1];
                             _mechY[k] = _mechY[k + 1];
                             _mechTime[k] = _mechTime[k + 1];
                         }
                         _numMechs--;
                     }
                 }
             }
         }
     }
References _mechTime, _mechX, _mechY, _numMechs, Tile.active(), Tile.frameX, Tile.frameY, WorldGen.InWorld(), NetMessage.SendTileSquare(), SetCurrentUser(), Main.tile, TripWire(), and Tile.type.
Referenced by WorldGen.UpdateWorld().