Terraria: Wiring.MassWireOperation
MassWireOperation()
static void Wiring.MassWireOperation (Point ps, Point pe, Player master) inline static
     {
         int wireCount = 0;
         int actuatorCount = 0;
         for (int i = 0; i < 58; i++)
         {
             if (master.inventory[i].type == 530)
             {
                 wireCount += master.inventory[i].stack;
             }
             if (master.inventory[i].type == 849)
             {
                 actuatorCount += master.inventory[i].stack;
             }
         }
         int num = wireCount;
         int num2 = actuatorCount;
         MassWireOperationInner(master, ps, pe, master.Center, master.direction == 1, ref wireCount, ref actuatorCount);
         int num3 = num - wireCount;
         int num4 = num2 - actuatorCount;
         if (Main.netMode == 2)
         {
             NetMessage.SendData(110, master.whoAmI, -1, null, 530, num3, master.whoAmI);
             NetMessage.SendData(110, master.whoAmI, -1, null, 849, num4, master.whoAmI);
             return;
         }
         for (int j = 0; j < num3; j++)
         {
             master.ConsumeItem(530);
         }
         for (int k = 0; k < num4; k++)
         {
             master.ConsumeItem(849);
         }
     }
References Entity.Center, Player.ConsumeItem(), Entity.direction, Player.inventory, MassWireOperationInner(), Main.netMode, NetMessage.SendData(), Item.stack, Item.type, and Entity.whoAmI.
Referenced by MessageBuffer.GetData(), Player.ItemCheck_UseWiringTools(), and Projectile.Kill().