Terraria: System.Security.Cryptography.XmlKeyHelper.ReadCryptoBinary
ReadCryptoBinary()
static byte[] System.Security.Cryptography.XmlKeyHelper.ReadCryptoBinary (ref ParseState state, string name, int sizeHint = -1) inline static package
Definition at line 158 of file XmlKeyHelper.cs.
    {
        string value = state.GetValue(name);
        if (value == null)
        {
            return null;
        }
        if (value.Length == 0)
        {
            return Array.Empty<byte>();
        }
        if (sizeHint < 0)
        {
            return Convert.FromBase64String(value);
        }
        byte[] array = new byte[sizeHint];
        if (Convert.TryFromBase64Chars(value.AsSpan(), array, out var bytesWritten))
        {
            if (bytesWritten == sizeHint)
            {
                return array;
            }
            int num = sizeHint - bytesWritten;
            Buffer.BlockCopy(array, 0, array, num, bytesWritten);
            array.AsSpan(0, num).Clear();
            return array;
        }
        return Convert.FromBase64String(value);
    }
References System.array, System.Buffer.BlockCopy(), System.Convert.FromBase64String(), System.state, System.Convert.TryFromBase64Chars(), and System.value.
Referenced by System.Security.Cryptography.DSA.FromXmlString(), System.Security.Cryptography.RSA.FromXmlString(), System.Security.Cryptography.DSA.ReadRequiredElement(), and System.Security.Cryptography.RSA.ReadRequiredElement().