Terraria: Wiring.TripWire
TripWire()
static void Wiring.TripWire (int left, int top, int width, int height) inline static private
     {
         if (Main.netMode == 1)
         {
             return;
         }
         running = true;
         if (_wireList.Count != 0)
         {
             _wireList.Clear(quickClear: true);
         }
         if (_wireDirectionList.Count != 0)
         {
             _wireDirectionList.Clear(quickClear: true);
         }
         Vector2[] array = new Vector2[8];
         int num = 0;
         for (int i = left; i < left + width; i++)
         {
             for (int j = top; j < top + height; j++)
             {
                 Point16 back = new Point16(i, j);
                 Tile tile = Main.tile[i, j];
                 if (tile != null && tile.wire())
                 {
                     _wireList.PushBack(back);
                 }
             }
         }
         _teleport[0].X = -1f;
         _teleport[0].Y = -1f;
         _teleport[1].X = -1f;
         _teleport[1].Y = -1f;
         if (_wireList.Count > 0)
         {
             _numInPump = 0;
             _numOutPump = 0;
             HitWire(_wireList, 1);
             if (_numInPump > 0 && _numOutPump > 0)
             {
                 XferWater();
             }
         }
         array[num++] = _teleport[0];
         array[num++] = _teleport[1];
         for (int k = left; k < left + width; k++)
         {
             for (int l = top; l < top + height; l++)
             {
                 Point16 back = new Point16(k, l);
                 Tile tile2 = Main.tile[k, l];
                 if (tile2 != null && tile2.wire2())
                 {
                     _wireList.PushBack(back);
                 }
             }
         }
         _teleport[0].X = -1f;
         _teleport[0].Y = -1f;
         _teleport[1].X = -1f;
         _teleport[1].Y = -1f;
         if (_wireList.Count > 0)
         {
             _numInPump = 0;
             _numOutPump = 0;
             HitWire(_wireList, 2);
             if (_numInPump > 0 && _numOutPump > 0)
             {
                 XferWater();
             }
         }
         array[num++] = _teleport[0];
         array[num++] = _teleport[1];
         _teleport[0].X = -1f;
         _teleport[0].Y = -1f;
         _teleport[1].X = -1f;
         _teleport[1].Y = -1f;
         for (int m = left; m < left + width; m++)
         {
             for (int n = top; n < top + height; n++)
             {
                 Point16 back = new Point16(m, n);
                 Tile tile3 = Main.tile[m, n];
                 if (tile3 != null && tile3.wire3())
                 {
                     _wireList.PushBack(back);
                 }
             }
         }
         if (_wireList.Count > 0)
         {
             _numInPump = 0;
             _numOutPump = 0;
             HitWire(_wireList, 3);
             if (_numInPump > 0 && _numOutPump > 0)
             {
                 XferWater();
             }
         }
         array[num++] = _teleport[0];
         array[num++] = _teleport[1];
         _teleport[0].X = -1f;
         _teleport[0].Y = -1f;
         _teleport[1].X = -1f;
         _teleport[1].Y = -1f;
         for (int num2 = left; num2 < left + width; num2++)
         {
             for (int num3 = top; num3 < top + height; num3++)
             {
                 Point16 back = new Point16(num2, num3);
                 Tile tile4 = Main.tile[num2, num3];
                 if (tile4 != null && tile4.wire4())
                 {
                     _wireList.PushBack(back);
                 }
             }
         }
         if (_wireList.Count > 0)
         {
             _numInPump = 0;
             _numOutPump = 0;
             HitWire(_wireList, 4);
             if (_numInPump > 0 && _numOutPump > 0)
             {
                 XferWater();
             }
         }
         array[num++] = _teleport[0];
         array[num++] = _teleport[1];
         running = false;
         for (int num4 = 0; num4 < 8; num4 += 2)
         {
             _teleport[0] = array[num4];
             _teleport[1] = array[num4 + 1];
             if (_teleport[0].X >= 0f && _teleport[1].X >= 0f)
             {
                 Teleport();
             }
         }
         PixelBoxPass();
         LogicGatePass();
     }
References _numInPump, _numOutPump, _teleport, _wireDirectionList, _wireList, DoubleStack< T1 >.Clear(), DoubleStack< T1 >.Count, HitWire(), LogicGatePass(), Main.netMode, PixelBoxPass(), DoubleStack< T1 >.PushBack(), running, Teleport(), Main.tile, Tile.wire(), Tile.wire2(), Tile.wire3(), Tile.wire4(), X, and XferWater().
Referenced by HitSwitch(), LogicGatePass(), and UpdateMech().