Terraria: Wiring.CheckLogicGate
CheckLogicGate()
static void Wiring.CheckLogicGate (int lampX, int lampY) inline static private
     {
         if (!WorldGen.InWorld(lampX, lampY, 1))
         {
             return;
         }
         for (int i = lampY; i < Main.maxTilesY; i++)
         {
             Tile tile = Main.tile[lampX, i];
             if (!tile.active())
             {
                 break;
             }
             if (tile.type == 420)
             {
                 _GatesDone.TryGetValue(new Point16(lampX, i), out var value);
                 int num = tile.frameY / 18;
                 bool flag = tile.frameX == 18;
                 bool flag2 = tile.frameX == 36;
                 if (num < 0)
                 {
                     break;
                 }
                 int num2 = 0;
                 int num3 = 0;
                 bool flag3 = false;
                 for (int num4 = i - 1; num4 > 0; num4--)
                 {
                     Tile tile2 = Main.tile[lampX, num4];
                     if (!tile2.active() || tile2.type != 419)
                     {
                         break;
                     }
                     if (tile2.frameX == 36)
                     {
                         flag3 = true;
                         break;
                     }
                     num2++;
                     num3 += (tile2.frameX == 18).ToInt();
                 }
                 bool flag4 = false;
                 switch (num)
                 {
                 default:
                     return;
                 case 0:
                     flag4 = num2 == num3;
                     break;
                 case 2:
                     flag4 = num2 != num3;
                     break;
                 case 1:
                     flag4 = num3 > 0;
                     break;
                 case 3:
                     flag4 = num3 == 0;
                     break;
                 case 4:
                     flag4 = num3 == 1;
                     break;
                 case 5:
                     flag4 = num3 != 1;
                     break;
                 }
                 bool flag5 = !flag3 && flag2;
                 bool flag6 = false;
                 if (flag3 && Framing.GetTileSafely(lampX, lampY).frameX == 36)
                 {
                     flag6 = true;
                 }
                 if (!(flag4 != flag || flag5 || flag6))
                 {
                     break;
                 }
                 _ = tile.frameX % 18 / 18;
                 tile.frameX = (short)(18 * flag4.ToInt());
                 if (flag3)
                 {
                     tile.frameX = 36;
                 }
                 SkipWire(lampX, i);
                 WorldGen.SquareTileFrame(lampX, i);
                 NetMessage.SendTileSquare(-1, lampX, i);
                 bool flag7 = !flag3 || flag6;
                 if (flag6)
                 {
                     if (num3 == 0 || num2 == 0)
                     {
                         flag7 = false;
                     }
                     flag7 = Main.rand.NextFloat() < (float)num3 / (float)num2;
                 }
                 if (flag5)
                 {
                     flag7 = false;
                 }
                 if (flag7)
                 {
                     if (!value)
                     {
                         _GatesNext.Enqueue(new Point16(lampX, i));
                         break;
                     }
                     Vector2 position = new Vector2(lampX, i) * 16f - new Vector2(10f);
                     Utils.PoofOfSmoke(position);
                     NetMessage.SendData(106, -1, -1, null, (int)position.X, position.Y);
                 }
                 break;
             }
             if (tile.type != 419)
             {
                 break;
             }
         }
     }
References _GatesDone, _GatesNext, Tile.active(), Tile.frameX, Tile.frameY, Framing.GetTileSafely(), WorldGen.InWorld(), Main.maxTilesY, Utils.PoofOfSmoke(), Main.rand, NetMessage.SendData(), NetMessage.SendTileSquare(), SkipWire(), WorldGen.SquareTileFrame(), Main.tile, and Tile.type.
Referenced by LogicGatePass().