Terraria: Wiring.HitWire
HitWire()
static void Wiring.HitWire (DoubleStack< Point16 > next, int wireType) inline static private
     {
         _wireDirectionList.Clear(quickClear: true);
         for (int i = 0; i < next.Count; i++)
         {
             Point16 point = next.PopFront();
             SkipWire(point);
             _toProcess.Add(point, 4);
             next.PushBack(point);
             _wireDirectionList.PushBack(0);
         }
         _currentWireColor = wireType;
         while (next.Count > 0)
         {
             Point16 key = next.PopFront();
             int num = _wireDirectionList.PopFront();
             int x = key.X;
             int y = key.Y;
             if (!_wireSkip.ContainsKey(key))
             {
                 HitWireSingle(x, y);
             }
             for (int j = 0; j < 4; j++)
             {
                 int num2;
                 int num3;
                 switch (j)
                 {
                 case 0:
                     num2 = x;
                     num3 = y + 1;
                     break;
                 case 1:
                     num2 = x;
                     num3 = y - 1;
                     break;
                 case 2:
                     num2 = x + 1;
                     num3 = y;
                     break;
                 case 3:
                     num2 = x - 1;
                     num3 = y;
                     break;
                 default:
                     num2 = x;
                     num3 = y + 1;
                     break;
                 }
                 if (num2 < 2 || num2 >= Main.maxTilesX - 2 || num3 < 2 || num3 >= Main.maxTilesY - 2)
                 {
                     continue;
                 }
                 Tile tile = Main.tile[num2, num3];
                 if (tile == null)
                 {
                     continue;
                 }
                 Tile tile2 = Main.tile[x, y];
                 if (tile2 == null)
                 {
                     continue;
                 }
                 byte b = 3;
                 if (tile.type == 424 || tile.type == 445)
                 {
                     b = 0;
                 }
                 if (tile2.type == 424)
                 {
                     switch (tile2.frameX / 18)
                     {
                     case 0:
                         if (j != num)
{
                             continue;
                         }
                         break;
                     case 1:
                         if ((num != 0 || j != 3) && (num != 3 || j != 0) && (num != 1 || j != 2) && (num != 2 || j != 1))
{
                             continue;
                         }
                         break;
                     case 2:
                         if ((num != 0 || j != 2) && (num != 2 || j != 0) && (num != 1 || j != 3) && (num != 3 || j != 1))
{
                             continue;
                         }
                         break;
                     }
                 }
                 if (tile2.type == 445)
                 {
                     if (j != num)
                     {
                         continue;
                     }
                     if (_PixelBoxTriggers.ContainsKey(key))
                     {
                         _PixelBoxTriggers[key] |= (byte)((!(j == 0 || j == 1)) ? 1 : 2);
                     }
                     else
                     {
                         _PixelBoxTriggers[key] = (byte)((!(j == 0 || j == 1)) ? 1u : 2u);
                     }
                 }
                 if (wireType switch
                 {
                     1 => tile.wire() ? 1 : 0,
                     2 => tile.wire2() ? 1 : 0,
                     3 => tile.wire3() ? 1 : 0,
                     4 => tile.wire4() ? 1 : 0,
                     _ => 0,
                 } == 0)
                 {
                     continue;
                 }
                 Point16 point2 = new Point16(num2, num3);
                 if (_toProcess.TryGetValue(point2, out var value))
                 {
                     value--;
                     if (value == 0)
                     {
                         _toProcess.Remove(point2);
                     }
                     else
                     {
                         _toProcess[point2] = value;
                     }
                     continue;
                 }
                 next.PushBack(point2);
                 _wireDirectionList.PushBack((byte)j);
                 if (b > 0)
                 {
                     _toProcess.Add(point2, b);
                 }
             }
         }
         _wireSkip.Clear();
         _toProcess.Clear();
     }
References _currentWireColor, _PixelBoxTriggers, _toProcess, _wireDirectionList, _wireSkip, DoubleStack< T1 >.Clear(), DoubleStack< T1 >.Count, Tile.frameX, HitWireSingle(), Main.maxTilesX, Main.maxTilesY, DoubleStack< T1 >.PopFront(), DoubleStack< T1 >.PushBack(), SkipWire(), Main.tile, Tile.type, Tile.wire(), Tile.wire2(), Tile.wire3(), Tile.wire4(), Point16.X, and Point16.Y.
Referenced by TripWire().