Terraria: Wiring.ToggleLamp
ToggleLamp()
static void Wiring.ToggleLamp (int i, int j, Tile tileCache, bool? forcedStateWhereTrueIsOn, bool doSkipWires) inline static
     {
         int num;
         for (num = tileCache.frameY / 18; num >= 3; num -= 3)
         {
         }
         num = j - num;
         short num2 = 18;
         if (tileCache.frameX > 0)
         {
             num2 = -18;
         }
         bool flag = tileCache.frameX > 0;
         if (!forcedStateWhereTrueIsOn.HasValue || !forcedStateWhereTrueIsOn.Value != flag)
         {
             Main.tile[i, num].frameX += num2;
             Main.tile[i, num + 1].frameX += num2;
             Main.tile[i, num + 2].frameX += num2;
             if (doSkipWires)
             {
                 SkipWire(i, num);
                 SkipWire(i, num + 1);
                 SkipWire(i, num + 2);
             }
             NetMessage.SendTileSquare(-1, i, num, 1, 3);
         }
     }
References Tile.frameX, Tile.frameY, NetMessage.SendTileSquare(), and Main.tile.
Referenced by HitWireSingle(), and WorldGen.TryToggleLight().