Terraria: Wiring.MassWireOperationStep
MassWireOperationStep()
static ? bool Wiring.MassWireOperationStep (Player user, Point pt, WiresUI.Settings.MultiToolMode mode, ref int wiresLeftToConsume, ref int actuatorsLeftToConstume) inline static private
     {
         if (!WorldGen.InWorld(pt.X, pt.Y, 1))
         {
             return null;
         }
         Tile tile = Main.tile[pt.X, pt.Y];
         if (tile == null)
         {
             return null;
         }
         if (user != null && !user.CanDoWireStuffHere(pt.X, pt.Y))
         {
             return null;
         }
         if (!mode.HasFlag(WiresUI.Settings.MultiToolMode.Cutter))
         {
             if (mode.HasFlag(WiresUI.Settings.MultiToolMode.Red) && !tile.wire())
             {
                 if (wiresLeftToConsume <= 0)
                 {
                     return false;
                 }
                 wiresLeftToConsume--;
                 WorldGen.PlaceWire(pt.X, pt.Y);
                 NetMessage.SendData(17, -1, -1, null, 5, pt.X, pt.Y);
             }
             if (mode.HasFlag(WiresUI.Settings.MultiToolMode.Green) && !tile.wire3())
             {
                 if (wiresLeftToConsume <= 0)
                 {
                     return false;
                 }
                 wiresLeftToConsume--;
                 WorldGen.PlaceWire3(pt.X, pt.Y);
                 NetMessage.SendData(17, -1, -1, null, 12, pt.X, pt.Y);
             }
             if (mode.HasFlag(WiresUI.Settings.MultiToolMode.Blue) && !tile.wire2())
             {
                 if (wiresLeftToConsume <= 0)
                 {
                     return false;
                 }
                 wiresLeftToConsume--;
                 WorldGen.PlaceWire2(pt.X, pt.Y);
                 NetMessage.SendData(17, -1, -1, null, 10, pt.X, pt.Y);
             }
             if (mode.HasFlag(WiresUI.Settings.MultiToolMode.Yellow) && !tile.wire4())
             {
                 if (wiresLeftToConsume <= 0)
                 {
                     return false;
                 }
                 wiresLeftToConsume--;
                 WorldGen.PlaceWire4(pt.X, pt.Y);
                 NetMessage.SendData(17, -1, -1, null, 16, pt.X, pt.Y);
             }
             if (mode.HasFlag(WiresUI.Settings.MultiToolMode.Actuator) && !tile.actuator())
             {
                 if (actuatorsLeftToConstume <= 0)
                 {
                     return false;
                 }
                 actuatorsLeftToConstume--;
                 WorldGen.PlaceActuator(pt.X, pt.Y);
                 NetMessage.SendData(17, -1, -1, null, 8, pt.X, pt.Y);
             }
         }
         if (mode.HasFlag(WiresUI.Settings.MultiToolMode.Cutter))
         {
             if (mode.HasFlag(WiresUI.Settings.MultiToolMode.Red) && tile.wire() && WorldGen.KillWire(pt.X, pt.Y))
             {
                 NetMessage.SendData(17, -1, -1, null, 6, pt.X, pt.Y);
             }
             if (mode.HasFlag(WiresUI.Settings.MultiToolMode.Green) && tile.wire3() && WorldGen.KillWire3(pt.X, pt.Y))
             {
                 NetMessage.SendData(17, -1, -1, null, 13, pt.X, pt.Y);
             }
             if (mode.HasFlag(WiresUI.Settings.MultiToolMode.Blue) && tile.wire2() && WorldGen.KillWire2(pt.X, pt.Y))
             {
                 NetMessage.SendData(17, -1, -1, null, 11, pt.X, pt.Y);
             }
             if (mode.HasFlag(WiresUI.Settings.MultiToolMode.Yellow) && tile.wire4() && WorldGen.KillWire4(pt.X, pt.Y))
             {
                 NetMessage.SendData(17, -1, -1, null, 17, pt.X, pt.Y);
             }
             if (mode.HasFlag(WiresUI.Settings.MultiToolMode.Actuator) && tile.actuator() && WorldGen.KillActuator(pt.X, pt.Y))
             {
                 NetMessage.SendData(17, -1, -1, null, 9, pt.X, pt.Y);
             }
         }
         return true;
     }
References Tile.actuator(), Player.CanDoWireStuffHere(), WorldGen.InWorld(), WorldGen.KillActuator(), WorldGen.KillWire(), WorldGen.KillWire2(), WorldGen.KillWire3(), WorldGen.KillWire4(), WorldGen.PlaceActuator(), WorldGen.PlaceWire(), WorldGen.PlaceWire2(), WorldGen.PlaceWire3(), WorldGen.PlaceWire4(), NetMessage.SendData(), Main.tile, Tile.wire(), Tile.wire2(), Tile.wire3(), and Tile.wire4().