Terraria: Wiring.ToggleCampFire
ToggleCampFire()
static void Wiring.ToggleCampFire (int i, int j, Tile tileCache, bool? forcedStateWhereTrueIsOn, bool doSkipWires) inline static
     {
         int num = tileCache.frameX % 54 / 18;
         int num2 = tileCache.frameY % 36 / 18;
         int num3 = i - num;
         int num4 = j - num2;
         bool flag = Main.tile[num3, num4].frameY >= 36;
         if (forcedStateWhereTrueIsOn.HasValue && !forcedStateWhereTrueIsOn.Value == flag)
         {
             return;
         }
         int num5 = 36;
         if (Main.tile[num3, num4].frameY >= 36)
         {
             num5 = -36;
         }
         for (int k = num3; k < num3 + 3; k++)
         {
             for (int l = num4; l < num4 + 2; l++)
             {
                 if (doSkipWires)
                 {
                     SkipWire(k, l);
                 }
                 Main.tile[k, l].frameY = (short)(Main.tile[k, l].frameY + num5);
             }
         }
         NetMessage.SendTileSquare(-1, num3, num4, 3, 2);
     }
References Tile.frameX, Tile.frameY, NetMessage.SendTileSquare(), and Main.tile.
Referenced by HitWireSingle(), and WorldGen.TryToggleLight().