Terraria: System.Xml.XmlCharacterData.ReplaceData
ReplaceData()
virtual void System.Xml.XmlCharacterData.ReplaceData (int offset, int count, string? strData) inline virtual inherited
Definition at line 157 of file XmlCharacterData.cs.
    {
        int num = ((_data != null) ? _data.Length : 0);
        if (num > 0 && num < offset + count)
        {
            count = Math.Max(num - offset, 0);
        }
        StringBuilder stringBuilder = new StringBuilder(_data).Remove(offset, count);
        string text = stringBuilder.Insert(offset, strData).ToString();
        XmlNode xmlNode = ParentNode;
        XmlNodeChangedEventArgs eventArgs = GetEventArgs(this, xmlNode, xmlNode, _data, text, XmlNodeChangedAction.Change);
        if (eventArgs != null)
        {
            BeforeEvent(eventArgs);
        }
        _data = text;
        if (eventArgs != null)
        {
            AfterEvent(eventArgs);
        }
    }
References System.Xml.XmlCharacterData._data, System.Xml.XmlNode.AfterEvent(), System.Xml.XmlNode.BeforeEvent(), System.count, System.Xml.Dictionary, System.Xml.XmlNode.GetEventArgs(), System.Text.StringBuilder.Insert(), System.Math.Max(), System.offset, System.Xml.XmlNode.ParentNode, System.Text.StringBuilder.Remove(), System.text, and System.Text.StringBuilder.ToString().