Terraria: ReLogic.OS.Windows.WindowsMessageHook.WndProc
WndProc()
IntPtr ReLogic.OS.Windows.WindowsMessageHook.WndProc (IntPtr hWnd, int msg, IntPtr wParam, IntPtr lParam) inline private
Definition at line 40 of file WindowsMessageHook.cs.
    {
        Message message = Message.Create(hWnd, msg, wParam, lParam);
        if (InternalWndProc(ref message))
        {
            return message.Result;
        }
        return NativeMethods.CallWindowProc(_previousWndProc, message.HWnd, message.Msg, message.WParam, message.LParam);
    }
References ReLogic.OS.Windows.WindowsMessageHook._previousWndProc, ReLogic.OS.Windows.NativeMethods.CallWindowProc(), ReLogic.OS.Windows.Message.Create(), ReLogic.OS.Windows.Message.HWnd, ReLogic.OS.Windows.WindowsMessageHook.InternalWndProc(), ReLogic.OS.Windows.Message.LParam, ReLogic.OS.Windows.Message.Msg, ReLogic.OS.Windows.Message.Result, and ReLogic.OS.Windows.Message.WParam.
Referenced by ReLogic.OS.Windows.WindowsMessageHook.WindowsMessageHook().