Terraria: System.Number.Grisu3.TryRunSingle
TryRunSingle()
static bool System.Number.Grisu3.TryRunSingle (float value, int requestedDigits, ref NumberBuffer number) inline static
Definition at line 894 of file Number.cs.
        {
            float value2 = (float.IsNegative(value) ? (0f - value) : value);
            DiyFp diyFp;
            bool flag;
            int length;
            int decimalExponent;
            if (requestedDigits == -1)
            {
                diyFp = DiyFp.CreateAndGetBoundaries(value2, out var mMinus, out var mPlus);
                DiyFp w = diyFp.Normalize();
                flag = TryRunShortest(in mMinus, in w, in mPlus, number.Digits, out length, out decimalExponent);
            }
            else
            {
                diyFp = new DiyFp(value2);
                DiyFp w2 = diyFp.Normalize();
                flag = TryRunCounted(in w2, requestedDigits, number.Digits, out length, out decimalExponent);
            }
            if (flag)
            {
                number.Scale = length + decimalExponent;
                number.Digits[length] = 0;
                number.DigitsCount = length;
            }
            return flag;
        }
References System.Number.DiyFp.CreateAndGetBoundaries(), System.length, System.Number.DiyFp.Normalize(), System.Number.Grisu3.TryRunCounted(), System.Number.Grisu3.TryRunShortest(), and System.value.
Referenced by System.Number.FormatSingle().