Terraria: System.Number.Grisu3.GetCachedPowerForBinaryExponentRange
GetCachedPowerForBinaryExponentRange()
static DiyFp System.Number.Grisu3.GetCachedPowerForBinaryExponentRange (int minExponent, int maxExponent, out int decimalExponent) inline static private
Definition at line 1057 of file Number.cs.
        {
            double num = Math.Ceiling((double)(minExponent + 64 - 1) * 0.3010299956639812);
            int num2 = (348 + (int)num - 1) / 8 + 1;
            decimalExponent = s_CachedPowersDecimalExponent[num2];
            return new DiyFp(s_CachedPowersSignificand[num2], s_CachedPowersBinaryExponent[num2]);
        }
References System.Math.Ceiling(), System.Number.Grisu3.s_CachedPowersBinaryExponent, System.Number.Grisu3.s_CachedPowersDecimalExponent, and System.Number.Grisu3.s_CachedPowersSignificand.
Referenced by System.Number.Grisu3.TryRunCounted(), and System.Number.Grisu3.TryRunShortest().