Terraria: System.Number.Grisu3.TryDigitGenCounted
TryDigitGenCounted()
static bool System.Number.Grisu3.TryDigitGenCounted (in DiyFp w, int requestedDigits, Span< byte > buffer, out int length, out int kappa) inline static private
Definition at line 963 of file Number.cs.
        {
            ulong num = 1uL;
            DiyFp diyFp = new DiyFp((ulong)(1L << -w.e), w.e);
            uint num2 = (uint)(w.f >> -diyFp.e);
            ulong num3 = w.f & (diyFp.f - 1);
            if (num3 == 0L && (requestedDigits >= 11 || num2 < s_SmallPowersOfTen[requestedDigits - 1]))
            {
                length = 0;
                kappa = 0;
                return false;
            }
            uint num4 = BiggestPowerTen(num2, 64 - -diyFp.e, out kappa);
            length = 0;
            while (kappa > 0)
            {
                uint num5;
                (num5, num2) = Math.DivRem(num2, num4);
                buffer[length] = (byte)(48 + num5);
                length++;
                requestedDigits--;
                kappa--;
                if (requestedDigits == 0)
                {
                    break;
                }
                num4 /= 10;
            }
            if (requestedDigits == 0)
            {
                ulong rest = ((ulong)num2 << -diyFp.e) + num3;
                return TryRoundWeedCounted(buffer, length, rest, (ulong)num4 << -diyFp.e, num, ref kappa);
            }
            while (requestedDigits > 0 && num3 > num)
            {
                num3 *= 10;
                num *= 10;
                uint num6 = (uint)(num3 >> -diyFp.e);
                buffer[length] = (byte)(48 + num6);
                length++;
                requestedDigits--;
                kappa--;
                num3 &= diyFp.f - 1;
            }
            if (requestedDigits != 0)
            {
                buffer[0] = 0;
                length = 0;
                kappa = 0;
                return false;
            }
            return TryRoundWeedCounted(buffer, length, num3, diyFp.f, num, ref kappa);
        }
References System.Number.Grisu3.BiggestPowerTen(), System.buffer, System.Math.DivRem(), System.Number.DiyFp.e, System.Number.DiyFp.f, System.L, System.length, System.Number.Grisu3.s_SmallPowersOfTen, and System.Number.Grisu3.TryRoundWeedCounted().
Referenced by System.Number.Grisu3.TryRunCounted().