Terraria: System.Number.Grisu3.TryDigitGenShortest
TryDigitGenShortest()
static bool System.Number.Grisu3.TryDigitGenShortest (in DiyFp low, in DiyFp w, in DiyFp high, Span< byte > buffer, out int length, out int kappa) inline static private
Definition at line 1017 of file Number.cs.
        {
            ulong num = 1uL;
            DiyFp other = new DiyFp(low.f - num, low.e);
            DiyFp diyFp = new DiyFp(high.f + num, high.e);
            DiyFp diyFp2 = diyFp.Subtract(in other);
            DiyFp diyFp3 = new DiyFp((ulong)(1L << -w.e), w.e);
            uint num2 = (uint)(diyFp.f >> -diyFp3.e);
            ulong num3 = diyFp.f & (diyFp3.f - 1);
            uint num4 = BiggestPowerTen(num2, 64 - -diyFp3.e, out kappa);
            length = 0;
            while (kappa > 0)
            {
                uint num5;
                (num5, num2) = Math.DivRem(num2, num4);
                buffer[length] = (byte)(48 + num5);
                length++;
                kappa--;
                ulong num6 = ((ulong)num2 << -diyFp3.e) + num3;
                if (num6 < diyFp2.f)
                {
                    return TryRoundWeedShortest(buffer, length, diyFp.Subtract(in w).f, diyFp2.f, num6, (ulong)num4 << -diyFp3.e, num);
                }
                num4 /= 10;
            }
            do
            {
                num3 *= 10;
                num *= 10;
                diyFp2 = new DiyFp(diyFp2.f * 10, diyFp2.e);
                uint num7 = (uint)(num3 >> -diyFp3.e);
                buffer[length] = (byte)(48 + num7);
                length++;
                kappa--;
                num3 &= diyFp3.f - 1;
            }
            while (num3 >= diyFp2.f);
            return TryRoundWeedShortest(buffer, length, diyFp.Subtract(in w).f * num, diyFp2.f, num3, diyFp3.f, num);
        }
References System.Number.Grisu3.BiggestPowerTen(), System.buffer, System.Math.DivRem(), System.Number.DiyFp.e, System.Number.DiyFp.f, System.L, System.length, System.other, System.Number.DiyFp.Subtract(), and System.Number.Grisu3.TryRoundWeedShortest().
Referenced by System.Number.Grisu3.TryRunShortest().