Terraria: TileLightScanner.ApplySurfaceLight
ApplySurfaceLight()
void TileLightScanner.ApplySurfaceLight (Tile tile, int x, int y, ref Vector3 lightColor) inline private
     {
         float num = 0f;
         float num2 = 0f;
         float num3 = 0f;
         float num4 = (float)(int)Main.tileColor.R / 255f;
         float num5 = (float)(int)Main.tileColor.G / 255f;
         float num6 = (float)(int)Main.tileColor.B / 255f;
         float num7 = (num4 + num5 + num6) / 3f;
         if (tile.active() && TileID.Sets.AllowLightInWater[tile.type])
         {
             if (lightColor.X < num7 && (Main.wallLight[tile.wall] || tile.wall == 73 || tile.wall == 227 || (tile.invisibleWall() && !_drawInvisibleWalls)))
             {
                 num = num4;
                 num2 = num5;
                 num3 = num6;
             }
         }
         else if ((!tile.active() || !Main.tileNoSunLight[tile.type] || ((tile.slope() != 0 || tile.halfBrick() || (tile.invisibleBlock() && !_drawInvisibleWalls)) && Main.tile[x, y - 1].liquid == 0 && Main.tile[x, y + 1].liquid == 0 && Main.tile[x - 1, y].liquid == 0 && Main.tile[x + 1, y].liquid == 0)) && lightColor.X < num7 && (Main.wallLight[tile.wall] || tile.wall == 73 || tile.wall == 227 || (tile.invisibleWall() && !_drawInvisibleWalls)))
         {
             if (tile.liquid < 200)
             {
                 if (!tile.halfBrick() || Main.tile[x, y - 1].liquid < 200)
                 {
                     num = num4;
                     num2 = num5;
                     num3 = num6;
                 }
             }
             else if (Main.liquidAlpha[13] > 0f)
             {
                 if (Main.rand == null)
                 {
                     Main.rand = new UnifiedRandom();
                 }
                 num3 = num6 * 0.175f * (1f + Main.rand.NextFloat() * 0.13f) * Main.liquidAlpha[13];
             }
         }
         if ((!tile.active() || tile.halfBrick() || !Main.tileNoSunLight[tile.type]) && ((tile.wall >= 88 && tile.wall <= 93) || tile.wall == 241) && tile.liquid < byte.MaxValue)
         {
             num = num4;
             num2 = num5;
             num3 = num6;
             int num8 = tile.wall - 88;
             if (tile.wall == 241)
             {
                 num8 = 6;
             }
             switch (num8)
             {
             case 0:
                 num *= 0.9f;
                 num2 *= 0.15f;
                 num3 *= 0.9f;
                 break;
             case 1:
                 num *= 0.9f;
                 num2 *= 0.9f;
                 num3 *= 0.15f;
                 break;
             case 2:
                 num *= 0.15f;
                 num2 *= 0.15f;
                 num3 *= 0.9f;
                 break;
             case 3:
                 num *= 0.15f;
                 num2 *= 0.9f;
                 num3 *= 0.15f;
                 break;
             case 4:
                 num *= 0.9f;
                 num2 *= 0.15f;
                 num3 *= 0.15f;
                 break;
             case 5:
             {
                 float num9 = 0.2f;
                 float num10 = 0.7f - num9;
                 num *= num10 + (float)Main.DiscoR / 255f * num9;
                 num2 *= num10 + (float)Main.DiscoG / 255f * num9;
                 num3 *= num10 + (float)Main.DiscoB / 255f * num9;
                 break;
             }
             case 6:
                 num *= 0.9f;
                 num2 *= 0.5f;
                 num3 *= 0f;
                 break;
             }
         }
         float num11 = 1f - Main.shimmerDarken;
         num *= num11;
         num2 *= num11;
         num3 *= num11;
         if (lightColor.X < num)
         {
             lightColor.X = num;
         }
         if (lightColor.Y < num2)
         {
             lightColor.Y = num2;
         }
         if (lightColor.Z < num3)
         {
             lightColor.Z = num3;
         }
     }
References Tile.active(), TileID.Sets.AllowLightInWater, Main.DiscoB, Main.DiscoG, Main.DiscoR, Tile.halfBrick(), Tile.invisibleBlock(), Tile.invisibleWall(), Tile.liquid, Main.liquidAlpha, Main.rand, Main.shimmerDarken, Tile.slope(), Main.tile, Main.tileColor, Main.tileNoSunLight, Tile.type, Tile.wall, and Main.wallLight.