Terraria: TileLightScanner.ExportTo
ExportTo()
void TileLightScanner.ExportTo (Rectangle area, LightMap outputMap, TileLightScannerOptions options) inline
     {
         //IL_0044: Unknown result type (might be due to invalid IL or missing references)
         //IL_004f: Expected O, but got Unknown
         _drawInvisibleWalls = options.DrawInvisibleWalls;
         FastParallel.For(area.Left, area.Right, (ParallelForAction)delegate(int start, int end, object context)
         {
             for (int i = start; i < end; i++)
             {
                 for (int j = area.Top; j <= area.Bottom; j++)
                 {
                     if (IsTileNullOrTouchingNull(i, j))
                     {
                         outputMap.SetMaskAt(i - area.X, j - area.Y, LightMaskMode.None);
                         outputMap[i - area.X, j - area.Y] = Vector3.Zero;
                     }
                     else
                     {
                         LightMaskMode tileMask = GetTileMask(Main.tile[i, j]);
                         outputMap.SetMaskAt(i - area.X, j - area.Y, tileMask);
                         GetTileLight(i, j, out var outputColor);
                         outputMap[i - area.X, j - area.Y] = outputColor;
                     }
                 }
             }
         }, (object)null);
     }
References _drawInvisibleWalls, TileLightScannerOptions.DrawInvisibleWalls, FastParallel.For(), and ParallelForAction().
Referenced by LegacyLighting.PreRenderPhase(), and LightingEngine.ProcessScan().