Terraria: TileLightScanner.GetTileMask
GetTileMask()
LightMaskMode TileLightScanner.GetTileMask (Tile tile) inline private
     {
         if (LightIsBlocked(tile) && tile.type != 131 && !tile.inActive() && tile.slope() == 0)
         {
             return LightMaskMode.Solid;
         }
         if (!tile.lava() && tile.liquid > 128)
         {
             if (!tile.honey())
             {
                 return LightMaskMode.Water;
             }
             return LightMaskMode.Honey;
         }
         return LightMaskMode.None;
     }
References Tile.honey(), Tile.inActive(), Tile.lava(), Tile.liquid, Tile.slope(), and Tile.type.