Terraria: IPCClient.ReadCallback
ReadCallback()
override void IPCClient.ReadCallback (IAsyncResult result) inline virtual
Reimplemented from IPCBase.
     {
         IPCContent obj = (IPCContent)result.AsyncState;
         base.ReadCallback(result);
         if (!obj.CancelToken.IsCancellationRequested)
         {
             if (GetPipeStream().IsConnected)
             {
                 BeginReadData();
             }
         }
         else
         {
             WeGameHelper.WriteDebugString("ReadCallback cancel");
         }
     }
References IPCBase.BeginReadData(), IPCContent.CancelToken, GetPipeStream(), and WeGameHelper.WriteDebugString().