Terraria: ShopHelper.AddHappinessReportText
AddHappinessReportText()
void ShopHelper.AddHappinessReportText (string textKeyInCategory, object substitutes = null) inline private
     {
         string text = "TownNPCMood_" + NPCID.Search.GetName(_currentNPCBeingTalkedTo.netID);
         if (_currentNPCBeingTalkedTo.type == 633 && _currentNPCBeingTalkedTo.altTexture == 2)
         {
             text += "Transformed";
         }
         string textValueWith = Language.GetTextValueWith(text + "." + textKeyInCategory, substitutes);
         _currentHappiness = _currentHappiness + textValueWith + " ";
     }
References _currentHappiness, _currentNPCBeingTalkedTo, NPC.altTexture, IdDictionary.GetName(), Language.GetTextValueWith(), NPC.netID, NPCID.Search, and NPC.type.
Referenced by DislikeBiome(), DislikeNPC(), HateBiome(), HateNPC(), IsFarFromHome(), IsPlayerInEvilBiomes(), LikeBiome(), LikeNPC(), LikePrincess(), LoveBiome(), LoveNPC(), LoveNPCByTypeName(), ProcessMood(), and RuinMoodIfHomeless().