Terraria: ShopHelper.ProcessMood
ProcessMood()
void ShopHelper.ProcessMood (Player player, NPC npc) inline private
     {
         _currentHappiness = "";
         _currentPriceAdjustment = 1f;
         if (Main.remixWorld)
         {
             return;
         }
         if (npc.type == 368)
         {
             _currentPriceAdjustment = 1f;
         }
         else if (npc.type == 453)
         {
             _currentPriceAdjustment = 1f;
         }
         else
         {
             if (NPCID.Sets.IsTownPet[npc.type])
             {
                 return;
             }
             if (IsNotReallyTownNPC(npc))
             {
                 _currentPriceAdjustment = 1f;
                 return;
             }
             if (RuinMoodIfHomeless(npc))
             {
                 _currentPriceAdjustment = 1000f;
             }
             else if (IsFarFromHome(npc))
             {
                 _currentPriceAdjustment = 1000f;
             }
             if (IsPlayerInEvilBiomes(player))
             {
                 _currentPriceAdjustment = 1000f;
             }
             int npcsWithinHouse;
             int npcsWithinVillage;
             List<NPC> nearbyResidentNPCs = GetNearbyResidentNPCs(npc, out npcsWithinHouse, out npcsWithinVillage);
             bool flag = true;
             float num = 1.05f;
             if (npc.type == 663)
             {
                 flag = false;
                 num = 1f;
                 if (npcsWithinHouse < 2 && npcsWithinVillage < 2)
                 {
                     AddHappinessReportText("HateLonely");
                     _currentPriceAdjustment = 1000f;
                 }
             }
             if (true && npcsWithinHouse > 3)
             {
                 for (int i = 3; i < npcsWithinHouse; i++)
                 {
                     _currentPriceAdjustment *= num;
                 }
                 if (npcsWithinHouse > 6)
                 {
                     AddHappinessReportText("HateCrowded");
                 }
                 else
                 {
                     AddHappinessReportText("DislikeCrowded");
                 }
             }
             if (flag && npcsWithinHouse <= 2 && npcsWithinVillage < 4)
             {
                 AddHappinessReportText("LoveSpace");
                 _currentPriceAdjustment *= 0.95f;
             }
             bool[] array = new bool[NPCID.Count];
             foreach (NPC item in nearbyResidentNPCs)
             {
                 array[item.type] = true;
             }
             HelperInfo helperInfo = default(HelperInfo);
             helperInfo.player = player;
             helperInfo.npc = npc;
             helperInfo.NearbyNPCs = nearbyResidentNPCs;
             helperInfo.nearbyNPCsByType = array;
             HelperInfo info = helperInfo;
             foreach (IShopPersonalityTrait shopModifier in _database.GetByNPCID(npc.type).ShopModifiers)
             {
                 shopModifier.ModifyShopPrice(info, this);
             }
             new AllPersonalitiesModifier().ModifyShopPrice(info, this);
             if (_currentHappiness == "")
             {
                 AddHappinessReportText("Content");
             }
             _currentPriceAdjustment = LimitAndRoundMultiplier(_currentPriceAdjustment);
         }
     }
References _currentHappiness, _currentPriceAdjustment, _database, AddHappinessReportText(), NPCID.Count, PersonalityDatabase.GetByNPCID(), GetNearbyResidentNPCs(), IsFarFromHome(), IsNotReallyTownNPC(), IsPlayerInEvilBiomes(), NPCID.Sets.IsTownPet, LimitAndRoundMultiplier(), AllPersonalitiesModifier.ModifyShopPrice(), IShopPersonalityTrait.ModifyShopPrice(), HelperInfo.NearbyNPCs, HelperInfo.nearbyNPCsByType, HelperInfo.npc, HelperInfo.player, Main.remixWorld, RuinMoodIfHomeless(), PersonalityProfile.ShopModifiers, and NPC.type.
Referenced by GetShoppingSettings().