Terraria: IPCClient.ConnectTo
ConnectTo()
void IPCClient.ConnectTo (string serverName) inline
     {
         if (GetPipeStream() != null)
         {
             return;
         }
         _pipeStream = new NamedPipeClientStream(".", serverName, PipeDirection.InOut, PipeOptions.Asynchronous);
         _cancelTokenSrc = new CancellationTokenSource();
         Task.Factory.StartNew(delegate(object content)
         {
             GetPipeStream().Connect();
             if (!((CancellationToken)content).IsCancellationRequested)
             {
                 GetPipeStream().ReadMode = PipeTransmissionMode.Message;
                 BeginReadData();
                 _connectedFlag = true;
             }
         }, _cancelTokenSrc.Token);
     }
References IPCBase._cancelTokenSrc, _connectedFlag, IPCBase._pipeStream, IPCBase.BeginReadData(), and GetPipeStream().
Referenced by MessageDispatcherClient.Start().