Terraria: Terraria.WorldBuilding.Searches.Chain
Chain()
static GenSearch Terraria.WorldBuilding.Searches.Chain (GenSearch search, params GenCondition[] conditions) inline static
Definition at line 123 of file Searches.cs.
    {
        return search.Conditions(conditions);
    }
References Terraria.WorldBuilding.GenSearch.Conditions().
Referenced by Terraria.NPC.AI(), Terraria.NPC.AI_109_DarkMage(), Terraria.Projectile.AI_137_LightningAura(), Terraria.Projectile.AI_140_MonkStaffT1(), Terraria.GameContent.Biomes.CaveHouse.HouseUtils.AreRoomsValid(), Terraria.Projectile.CanHitWithOwnBody(), Terraria.GameContent.Biomes.CaveHouse.HouseUtils.CreateRooms(), Terraria.GameContent.Biomes.CaveHouse.HouseBuilder.CreateSupportBeamList(), Terraria.Projectile.Damage(), Terraria.GameContent.Biomes.CaveHouse.HouseUtils.FindRoom(), Terraria.GameContent.Biomes.CaveHouse.HouseBuilder.FindSideExit(), Terraria.GameContent.Biomes.CaveHouse.HouseBuilder.FindVerticalExit(), Terraria.Player.ItemCheck_Shoot(), Terraria.GameContent.Biomes.CampsiteBiome.Place(), Terraria.GameContent.Biomes.CorruptionPitBiome.Place(), Terraria.GameContent.Biomes.EnchantedSwordBiome.Place(), Terraria.GameContent.Biomes.HoneyPatchBiome.Place(), Terraria.GameContent.Biomes.MahoganyTreeBiome.Place(), Terraria.GameContent.Biomes.MiningExplosivesBiome.Place(), and Terraria.GameContent.Events.DD2Event.RaiseGoblins().