Terraria: System.Text.SBCSCodePageEncoding.GetByteCount
GetByteCount() [2/7]
unsafe override int System.Text.SBCSCodePageEncoding.GetByteCount (char * chars, int count, System::Text::EncoderNLS encoder) inline virtual
Reimplemented from System.Text.EncodingNLS.
Definition at line 247 of file SBCSCodePageEncoding.cs.
    {
        CheckMemorySection();
        EncoderReplacementFallback encoderReplacementFallback = null;
        char c = '\0';
        if (encoder != null)
        {
            c = encoder.charLeftOver;
            encoderReplacementFallback = encoder.Fallback as EncoderReplacementFallback;
        }
        else
        {
            encoderReplacementFallback = base.EncoderFallback as EncoderReplacementFallback;
        }
        if (encoderReplacementFallback != null && encoderReplacementFallback.MaxCharCount == 1)
        {
            if (c > '\0')
            {
                count++;
            }
            return count;
        }
        EncoderFallbackBuffer encoderFallbackBuffer = null;
        int num = 0;
        char* ptr = chars + count;
        EncoderFallbackBufferHelper encoderFallbackBufferHelper = new EncoderFallbackBufferHelper(encoderFallbackBuffer);
        if (c > '\0')
        {
            encoderFallbackBuffer = encoder.FallbackBuffer;
            encoderFallbackBufferHelper = new EncoderFallbackBufferHelper(encoderFallbackBuffer);
            encoderFallbackBufferHelper.InternalInitialize(chars, ptr, encoder, _setEncoder: false);
            encoderFallbackBufferHelper.InternalFallback(c, ref chars);
        }
        char c2;
        while ((c2 = ((encoderFallbackBuffer != null) ? encoderFallbackBufferHelper.InternalGetNextChar() : '\0')) != 0 || chars < ptr)
        {
            if (c2 == '\0')
            {
                c2 = *chars;
                chars++;
            }
            if (_mapUnicodeToBytes[(int)c2] == 0 && c2 != 0)
            {
                if (encoderFallbackBuffer == null)
                {
                    encoderFallbackBuffer = ((encoder != null) ? encoder.FallbackBuffer : base.EncoderFallback.CreateFallbackBuffer());
                    encoderFallbackBufferHelper = new EncoderFallbackBufferHelper(encoderFallbackBuffer);
                    encoderFallbackBufferHelper.InternalInitialize(ptr - count, ptr, encoder, _setEncoder: false);
                }
                encoderFallbackBufferHelper.InternalFallback(c2, ref chars);
            }
            else
            {
                num++;
            }
        }
        return num;
    }
References System.Text.SBCSCodePageEncoding._mapUnicodeToBytes, System.chars, System.Text.BaseCodePageEncoding.CheckMemorySection(), System.count, System.Text.EncoderFallbackBufferHelper.InternalFallback(), System.Text.EncoderFallbackBufferHelper.InternalGetNextChar(), System.Text.EncoderFallbackBufferHelper.InternalInitialize(), and System.Text.EncoderReplacementFallback.MaxCharCount.