Terraria: System.Text.SBCSCodePageEncoding.GetBytes
GetBytes() [2/9]
unsafe override int System.Text.SBCSCodePageEncoding.GetBytes (char * chars, int charCount, byte * bytes, int byteCount, System::Text::EncoderNLS encoder) inline virtual
Reimplemented from System.Text.EncodingNLS.
Definition at line 306 of file SBCSCodePageEncoding.cs.
    {
        CheckMemorySection();
        EncoderReplacementFallback encoderReplacementFallback = null;
        char c = '\0';
        if (encoder != null)
        {
            c = encoder.charLeftOver;
            encoderReplacementFallback = encoder.Fallback as EncoderReplacementFallback;
        }
        else
        {
            encoderReplacementFallback = base.EncoderFallback as EncoderReplacementFallback;
        }
        char* ptr = chars + charCount;
        byte* ptr2 = bytes;
        char* ptr3 = chars;
        if (encoderReplacementFallback != null && encoderReplacementFallback.MaxCharCount == 1)
        {
            byte b = _mapUnicodeToBytes[(int)encoderReplacementFallback.DefaultString[0]];
            if (b != 0)
            {
                if (c > '\0')
                {
                    if (byteCount == 0)
                    {
                        ThrowBytesOverflow(encoder, nothingEncoded: true);
                    }
                    *(bytes++) = b;
                    byteCount--;
                }
                if (byteCount < charCount)
                {
                    ThrowBytesOverflow(encoder, byteCount < 1);
                    ptr = chars + byteCount;
                }
                while (chars < ptr)
                {
                    char c2 = *chars;
                    chars++;
                    byte b2 = _mapUnicodeToBytes[(int)c2];
                    if (b2 == 0 && c2 != 0)
                    {
                        *bytes = b;
                    }
                    else
                    {
                        *bytes = b2;
                    }
                    bytes++;
                }
                if (encoder != null)
                {
                    encoder.charLeftOver = '\0';
                    encoder.m_charsUsed = (int)(chars - ptr3);
                }
                return (int)(bytes - ptr2);
            }
        }
        EncoderFallbackBuffer encoderFallbackBuffer = null;
        byte* ptr4 = bytes + byteCount;
        EncoderFallbackBufferHelper encoderFallbackBufferHelper = new EncoderFallbackBufferHelper(encoderFallbackBuffer);
        if (c > '\0')
        {
            encoderFallbackBuffer = encoder.FallbackBuffer;
            encoderFallbackBufferHelper = new EncoderFallbackBufferHelper(encoderFallbackBuffer);
            encoderFallbackBufferHelper.InternalInitialize(chars, ptr, encoder, _setEncoder: true);
            encoderFallbackBufferHelper.InternalFallback(c, ref chars);
            if (encoderFallbackBuffer.Remaining > ptr4 - bytes)
            {
                ThrowBytesOverflow(encoder, nothingEncoded: true);
            }
        }
        char c3;
        while ((c3 = ((encoderFallbackBuffer != null) ? encoderFallbackBufferHelper.InternalGetNextChar() : '\0')) != 0 || chars < ptr)
        {
            if (c3 == '\0')
            {
                c3 = *chars;
                chars++;
            }
            byte b3 = _mapUnicodeToBytes[(int)c3];
            if (b3 == 0 && c3 != 0)
            {
                if (encoderFallbackBuffer == null)
                {
                    encoderFallbackBuffer = ((encoder != null) ? encoder.FallbackBuffer : base.EncoderFallback.CreateFallbackBuffer());
                    encoderFallbackBufferHelper = new EncoderFallbackBufferHelper(encoderFallbackBuffer);
                    encoderFallbackBufferHelper.InternalInitialize(ptr - charCount, ptr, encoder, _setEncoder: true);
                }
                encoderFallbackBufferHelper.InternalFallback(c3, ref chars);
                if (encoderFallbackBuffer.Remaining > ptr4 - bytes)
                {
                    chars--;
                    encoderFallbackBufferHelper.InternalReset();
                    ThrowBytesOverflow(encoder, chars == ptr3);
                    break;
                }
                continue;
            }
            if (bytes >= ptr4)
            {
                if (encoderFallbackBuffer == null || !encoderFallbackBufferHelper.bFallingBack)
                {
                    chars--;
                }
                ThrowBytesOverflow(encoder, chars == ptr3);
                break;
            }
            *bytes = b3;
            bytes++;
        }
        if (encoder != null)
        {
            if (encoderFallbackBuffer != null && !encoderFallbackBufferHelper.bUsedEncoder)
            {
                encoder.charLeftOver = '\0';
            }
            encoder.m_charsUsed = (int)(chars - ptr3);
        }
        return (int)(bytes - ptr2);
    }
References System.Text.SBCSCodePageEncoding._mapUnicodeToBytes, System.Text.EncoderFallbackBufferHelper.bFallingBack, System.Text.EncoderFallbackBufferHelper.bUsedEncoder, System.byteCount, System.bytes, System.charCount, System.chars, System.Text.BaseCodePageEncoding.CheckMemorySection(), System.Text.EncoderReplacementFallback.DefaultString, System.Text.EncoderFallbackBufferHelper.InternalFallback(), System.Text.EncoderFallbackBufferHelper.InternalGetNextChar(), System.Text.EncoderFallbackBufferHelper.InternalInitialize(), System.Text.EncoderFallbackBufferHelper.InternalReset(), System.Text.EncoderReplacementFallback.MaxCharCount, System.Text.EncoderFallbackBuffer.Remaining, and System.Text.EncodingNLS.ThrowBytesOverflow().