Terraria: System.Text.SBCSCodePageEncoding.GetCharCount
GetCharCount() [2/5]
unsafe override int System.Text.SBCSCodePageEncoding.GetCharCount (byte * bytes, int count, System::Text::DecoderNLS decoder) inline virtual
Reimplemented from System.Text.EncodingNLS.
Definition at line 429 of file SBCSCodePageEncoding.cs.
    {
        CheckMemorySection();
        bool flag = false;
        DecoderReplacementFallback decoderReplacementFallback = null;
        if (decoder == null)
        {
            decoderReplacementFallback = base.DecoderFallback as DecoderReplacementFallback;
            flag = base.DecoderFallback is InternalDecoderBestFitFallback;
        }
        else
        {
            decoderReplacementFallback = decoder.Fallback as DecoderReplacementFallback;
            flag = decoder.Fallback is InternalDecoderBestFitFallback;
        }
        if (flag || (decoderReplacementFallback != null && decoderReplacementFallback.MaxCharCount == 1))
        {
            return count;
        }
        DecoderFallbackBuffer decoderFallbackBuffer = null;
        DecoderFallbackBufferHelper decoderFallbackBufferHelper = new DecoderFallbackBufferHelper(decoderFallbackBuffer);
        int num = count;
        byte[] array = new byte[1];
        byte* ptr = bytes + count;
        while (bytes < ptr)
        {
            char c = _mapBytesToUnicode[(int)(*bytes)];
            bytes++;
            if (c == '\ufffd')
            {
                if (decoderFallbackBuffer == null)
                {
                    decoderFallbackBuffer = ((decoder != null) ? decoder.FallbackBuffer : base.DecoderFallback.CreateFallbackBuffer());
                    decoderFallbackBufferHelper = new DecoderFallbackBufferHelper(decoderFallbackBuffer);
                    decoderFallbackBufferHelper.InternalInitialize(ptr - count, null);
                }
                array[0] = *(bytes - 1);
                num--;
                num += decoderFallbackBufferHelper.InternalFallback(array, bytes);
            }
        }
        return num;
    }
References System.Text.SBCSCodePageEncoding._mapBytesToUnicode, System.array, System.bytes, System.Text.BaseCodePageEncoding.CheckMemorySection(), System.count, System.Text.DecoderFallbackBufferHelper.InternalFallback(), System.Text.DecoderFallbackBufferHelper.InternalInitialize(), and System.Text.DecoderReplacementFallback.MaxCharCount.