Terraria: System.Text.SBCSCodePageEncoding.ReadUInt16
ReadUInt16()
static unsafe ushort System.Text.SBCSCodePageEncoding.ReadUInt16 (byte * pByte) inline static package
Definition at line 45 of file SBCSCodePageEncoding.cs.
    {
        if (BitConverter.IsLittleEndian)
        {
            return *(ushort*)pByte;
        }
        return BinaryPrimitives.ReverseEndianness(*(ushort*)pByte);
    }
References System.BitConverter.IsLittleEndian, and System.Buffers.Binary.BinaryPrimitives.ReverseEndianness().
Referenced by System.Text.SBCSCodePageEncoding.LoadManagedCodePage(), and System.Text.SBCSCodePageEncoding.ReadBestFitTable().