Terraria: Microsoft.Win32.SafeHandles.SafeFileHandle.Preallocate
Preallocate()
static unsafe void Microsoft.Win32.SafeHandles.SafeFileHandle.Preallocate (string fullPath, long preallocationSize, SafeFileHandle fileHandle) inline static private
Definition at line 482 of file SafeFileHandle.cs.
    {
        Interop.Kernel32.FILE_ALLOCATION_INFO fILE_ALLOCATION_INFO = default(Interop.Kernel32.FILE_ALLOCATION_INFO);
        fILE_ALLOCATION_INFO.AllocationSize = preallocationSize;
        Interop.Kernel32.FILE_ALLOCATION_INFO fILE_ALLOCATION_INFO2 = fILE_ALLOCATION_INFO;
        if (!Interop.Kernel32.SetFileInformationByHandle(fileHandle, 5, &fILE_ALLOCATION_INFO2, (uint)sizeof(Interop.Kernel32.FILE_ALLOCATION_INFO)))
        {
            int lastPInvokeError = Marshal.GetLastPInvokeError();
            if (lastPInvokeError == 112 || lastPInvokeError == 223)
            {
                fileHandle.Dispose();
                Interop.Kernel32.DeleteFile(fullPath);
                throw new IOException(SR.Format((lastPInvokeError == 112) ? SR.IO_DiskFull_Path_AllocationSize : SR.IO_FileTooLarge_Path_AllocationSize, fullPath, preallocationSize));
            }
        }
    }
References Interop.Kernel32.DeleteFile(), System.Runtime.InteropServices.SafeHandle.Dispose(), System.SR.Format(), System.Runtime.InteropServices.Marshal.GetLastPInvokeError(), System.SR.IO_DiskFull_Path_AllocationSize, System.SR.IO_FileTooLarge_Path_AllocationSize, and Interop.Kernel32.SetFileInformationByHandle().
Referenced by Microsoft.Win32.SafeHandles.SafeFileHandle.Open().