Terraria: Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile
CreateFile()
static unsafe SafeFileHandle Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile (string fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options) inline static private
Definition at line 449 of file SafeFileHandle.cs.
    {
        Interop.Kernel32.SECURITY_ATTRIBUTES sECURITY_ATTRIBUTES = default(Interop.Kernel32.SECURITY_ATTRIBUTES);
        if ((share & FileShare.Inheritable) != 0)
        {
            Interop.Kernel32.SECURITY_ATTRIBUTES sECURITY_ATTRIBUTES2 = default(Interop.Kernel32.SECURITY_ATTRIBUTES);
            sECURITY_ATTRIBUTES2.nLength = (uint)sizeof(Interop.Kernel32.SECURITY_ATTRIBUTES);
            sECURITY_ATTRIBUTES2.bInheritHandle = Interop.BOOL.TRUE;
            sECURITY_ATTRIBUTES = sECURITY_ATTRIBUTES2;
        }
        int dwDesiredAccess = (((access & FileAccess.Read) == FileAccess.Read) ? int.MinValue : 0) | (((access & FileAccess.Write) == FileAccess.Write) ? 1073741824 : 0);
        share &= ~FileShare.Inheritable;
        if (mode == FileMode.Append)
        {
            mode = FileMode.OpenOrCreate;
        }
        int num = (int)options;
        num |= 0x100000;
        SafeFileHandle safeFileHandle = Interop.Kernel32.CreateFile(fullPath, dwDesiredAccess, share, &sECURITY_ATTRIBUTES, mode, num, IntPtr.Zero);
        if (safeFileHandle.IsInvalid)
        {
            int num2 = Marshal.GetLastPInvokeError();
            if (num2 == 3 && fullPath.Length == PathInternal.GetRootLength(fullPath))
            {
                num2 = 5;
            }
            throw Win32Marshal.GetExceptionForWin32Error(num2, fullPath);
        }
        safeFileHandle._path = fullPath;
        safeFileHandle._fileOptions = options;
        return safeFileHandle;
    }
References Interop.Kernel32.CreateFile(), System.IO.Win32Marshal.GetExceptionForWin32Error(), System.Runtime.InteropServices.Marshal.GetLastPInvokeError(), System.IO.PathInternal.GetRootLength(), System.options, and System.IntPtr.Zero.
Referenced by System.IO.FileSystemAclExtensions.CreateFileHandle(), Microsoft.Win32.SafeHandles.SafeFileHandle.Open(), and System.IO.FileSystemWatcher.StartRaisingEvents().