Terraria: Microsoft.Win32.SafeHandles.SafeFileHandle.Open
Open()
static SafeFileHandle Microsoft.Win32.SafeHandles.SafeFileHandle.Open (string fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, long preallocationSize) inline static package
Definition at line 432 of file SafeFileHandle.cs.
    {
        using (DisableMediaInsertionPrompt.Create())
        {
            SafeFileHandle safeFileHandle = CreateFile(fullPath, mode, access, share, options);
            if (preallocationSize > 0)
            {
                Preallocate(fullPath, preallocationSize, safeFileHandle);
            }
            if ((options & FileOptions.Asynchronous) != 0)
            {
                safeFileHandle.InitThreadPoolBinding();
            }
            return safeFileHandle;
        }
    }
References System.IO.DisableMediaInsertionPrompt.Create(), Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(), System.options, and Microsoft.Win32.SafeHandles.SafeFileHandle.Preallocate().
Referenced by System.IO.Strategies.Net5CompatFileStreamStrategy.Net5CompatFileStreamStrategy(), System.IO.Strategies.OSFileStreamStrategy.OSFileStreamStrategy(), and System.IO.File.OpenHandle().