Terraria: System.ByteArrayHelpers.EqualsOrdinalAsciiIgnoreCase
EqualsOrdinalAsciiIgnoreCase()
static bool System.ByteArrayHelpers.EqualsOrdinalAsciiIgnoreCase (string left, ReadOnlySpan< byte > right) inline static package
Definition at line 5 of file ByteArrayHelpers.cs.
    {
        if (left.Length != right.Length)
        {
            return false;
        }
        for (int i = 0; i < left.Length; i++)
        {
            uint num = left[i];
            uint num2 = right[i];
            if (num - 97 <= 25)
            {
                num -= 32;
            }
            if (num2 - 97 <= 25)
            {
                num2 -= 32;
            }
            if (num != num2)
            {
                return false;
            }
        }
        return true;
    }
References System.ReadOnlySpan< T >.Length.
Referenced by System.Net.Http.Headers.HeaderDescriptor.GetHeaderValue(), System.Net.Http.Headers.HeaderDescriptor.GetKnownContentType(), and System.Net.Http.Headers.KnownHeaders.TryGetKnownHeader().