Terraria: System.UInt32.Parse
Parse() [8/12]
static uint System.UInt32.Parse (string s, IFormatProvider? provider) inline static
Definition at line 136 of file UInt32.cs.
    {
        if (s == null)
        {
            ThrowHelper.ThrowArgumentNullException(ExceptionArgument.s);
        }
        return Number.ParseUInt32(s, NumberStyles.Integer, NumberFormatInfo.GetInstance(provider));
    }
References System.Globalization.NumberFormatInfo.GetInstance(), System.Number.ParseUInt32(), System.s, and System.ThrowHelper.ThrowArgumentNullException().