Terraria: System.Xml.Xsl.Runtime.XsltFunctions.MSUtc
MSUtc()
static string System.Xml.Xsl.Runtime.XsltFunctions.MSUtc (string dateTime) inline static
Definition at line 374 of file XsltFunctions.cs.
    {
        XsdDateTime result;
        DateTime dt;
        try
        {
            if (!XsdDateTime.TryParse(dateTime, XsdDateTimeFlags.AllXsd | XsdDateTimeFlags.XdrDateTime | XsdDateTimeFlags.XdrTimeNoTz, out result))
            {
                return string.Empty;
            }
            dt = result.ToZulu();
        }
        catch (ArgumentException)
        {
            return string.Empty;
        }
        char[] array = "----------T00:00:00.000".ToCharArray();
        switch (result.TypeCode)
        {
        case XmlTypeCode.DateTime:
            PrintDate(array, dt);
            PrintTime(array, dt);
            break;
        case XmlTypeCode.Time:
            PrintTime(array, dt);
            break;
        case XmlTypeCode.Date:
            PrintDate(array, dt);
            break;
        case XmlTypeCode.GYearMonth:
            PrintYear(array, dt.Year);
            ShortToCharArray(array, 5, dt.Month);
            break;
        case XmlTypeCode.GYear:
            PrintYear(array, dt.Year);
            break;
        case XmlTypeCode.GMonthDay:
            ShortToCharArray(array, 5, dt.Month);
            ShortToCharArray(array, 8, dt.Day);
            break;
        case XmlTypeCode.GDay:
            ShortToCharArray(array, 8, dt.Day);
            break;
        case XmlTypeCode.GMonth:
            ShortToCharArray(array, 5, dt.Month);
            break;
        }
        return new string(array);
    }
References System.array, System.Xml.Dictionary, System.Xml.Xsl.Runtime.XsltFunctions.PrintDate(), System.Xml.Xsl.Runtime.XsltFunctions.PrintTime(), System.Xml.Xsl.Runtime.XsltFunctions.PrintYear(), System.Xml.Xsl.Runtime.XsltFunctions.ShortToCharArray(), System.Xml.Schema.XsdDateTime.TryParse(), and System.Xml.Schema.XsdDateTime.TypeCode.