Terraria: System.Xml.Xsl.Runtime.XsltFunctions.Round
Round()
static double System.Xml.Xsl.Runtime.XsltFunctions.Round (double value) inline static
Definition at line 195 of file XsltFunctions.cs.
    {
        double num = Math.Round(value);
        if (value - num != 0.5)
        {
            return num;
        }
        return num + 1.0;
    }
References System.Math.Round(), and System.value.
Referenced by System.Xml.Xsl.Xslt.QilGenerator.CompileGroupingSizeAttribute(), System.Xml.Xsl.Runtime.NumberFormatter.FormatItem(), System.Xml.Xsl.Runtime.XsltFunctions.Substring(), and System.Xml.Xsl.Runtime.XsltFunctions.Substring().