Terraria: System.Data.Constraint.CheckStateForProperty
CheckStateForProperty()
void System.Data.Constraint.CheckStateForProperty () inline protected inherited
Definition at line 128 of file Constraint.cs.
    {
        try
        {
            CheckState();
        }
        catch (Exception ex) when (ADP.IsCatchableExceptionType(ex))
        {
            throw ExceptionBuilder.BadObjectPropertyAccess(ex.Message);
        }
    }
References System.Data.ExceptionBuilder.BadObjectPropertyAccess(), System.Data.Constraint.CheckState(), System.Data.Common.ADP.IsCatchableExceptionType(), and System.Exception.Message.