Terraria: System.Xml.Xsl.Runtime.NumberFormatterBase.ConvertToRoman
ConvertToRoman()
static void System.Xml.Xsl.Runtime.NumberFormatterBase.ConvertToRoman (StringBuilder sb, double val, bool upperCase) inline static inherited
Definition at line 28 of file NumberFormatterBase.cs.
    {
        int num = (int)val;
        string value = (upperCase ? "IIVIXXLXCCDCM" : "iivixxlxccdcm");
        int num2 = s_romanDigitValue.Length;
        while (num2-- != 0)
        {
            while (num >= s_romanDigitValue[num2])
            {
                num -= s_romanDigitValue[num2];
                sb.Append(value, num2, 1 + (num2 & 1));
            }
        }
    }
References System.Text.StringBuilder.Append(), System.Xml.Dictionary, System.Xml.Xsl.Runtime.NumberFormatterBase.s_romanDigitValue, and System.value.
Referenced by System.Xml.Xsl.XsltOld.NumberAction.NumberingFormat.FormatItem(), and System.Xml.Xsl.Runtime.NumberFormatter.FormatItem().