Terraria: System.Reflection.Emit.TypeBuilderInstantiation.Substitute
Substitute()
Type System.Reflection.Emit.TypeBuilderInstantiation.Substitute (Type[] substitutes) inline private
Definition at line 179 of file TypeBuilderInstantiation.cs.
    {
        Type[] genericArguments = GetGenericArguments();
        Type[] array = new Type[genericArguments.Length];
        for (int i = 0; i < array.Length; i++)
        {
            Type type = genericArguments[i];
            if (type is TypeBuilderInstantiation typeBuilderInstantiation)
            {
                array[i] = typeBuilderInstantiation.Substitute(substitutes);
            }
            else if (type is GenericTypeParameterBuilder)
            {
                array[i] = substitutes[type.GenericParameterPosition];
            }
            else
            {
                array[i] = type;
            }
        }
        return GetGenericTypeDefinition().MakeGenericType(array);
    }
References System.array, System.Reflection.Emit.TypeBuilderInstantiation.GetGenericArguments(), System.Reflection.Emit.TypeBuilderInstantiation.GetGenericTypeDefinition(), System.Type.MakeGenericType(), and System.type.