Terraria: System.Xml.Xsl.Runtime.NumberFormatterBase.ConvertToAlphabetic
ConvertToAlphabetic()
static void System.Xml.Xsl.Runtime.NumberFormatterBase.ConvertToAlphabetic (StringBuilder sb, double val, char firstChar, int totalChars) inline static inherited
Definition at line 13 of file NumberFormatterBase.cs.
    {
        char[] array = new char[7];
        int num = 7;
        int num2 = (int)val;
        while (num2 > totalChars)
        {
            int num3 = --num2 / totalChars;
            array[--num] = (char)(firstChar + (num2 - num3 * totalChars));
            num2 = num3;
        }
        array[--num] = (char)(firstChar + --num2);
        sb.Append(array, num, 7 - num);
    }
References System.Text.StringBuilder.Append(), System.array, and System.Xml.Dictionary.
Referenced by System.Xml.Xsl.XsltOld.NumberAction.NumberingFormat.FormatItem(), and System.Xml.Xsl.Runtime.NumberFormatter.FormatItem().