Terraria: Terraria.Main.DrawInterface_16_MapOrMinimap
DrawInterface_16_MapOrMinimap()
void Terraria.Main.DrawInterface_16_MapOrMinimap () inline private
Definition at line 42737 of file Main.cs.
    {
        mH = 0;
        if (!mapEnabled)
        {
            return;
        }
        if (!mapFullscreen && mapStyle == 1)
        {
            mH = 256;
            try
            {
                DrawMap(new GameTime());
            }
            catch (Exception e)
            {
                if (!ignoreErrors)
                {
                    throw;
                }
                TimeLogger.DrawException(e);
            }
        }
        PlayerInput.SetZoom_UI();
        if (mH + RecommendedEquipmentAreaPushUp > screenHeight)
        {
            mH = screenHeight - RecommendedEquipmentAreaPushUp;
        }
    }
References Terraria.TimeLogger.DrawException(), Terraria.Main.DrawMap(), Terraria.Main.ignoreErrors, Terraria.Main.mapEnabled, Terraria.Main.mapFullscreen, Terraria.Main.mapStyle, Terraria.Main.mH, Terraria.Main.RecommendedEquipmentAreaPushUp, Terraria.Main.screenHeight, and Terraria.GameInput.PlayerInput.SetZoom_UI().
Referenced by Terraria.Main.DrawInterface_11_IngameOptionsMenu(), and Terraria.Main.SetupDrawInterfaceLayers().