Terraria: Terraria.Main.GUIChatDraw
GUIChatDraw()
void Terraria.Main.GUIChatDraw () inline
Definition at line 43683 of file Main.cs.
    {
        if (ignoreErrors)
        {
            try
            {
                if ((npcChatText != "" || player[myPlayer].sign != -1) && !editChest)
                {
                    GUIChatDrawInner();
                }
                return;
            }
            catch (Exception e)
            {
                TimeLogger.DrawException(e);
                return;
            }
        }
        if ((npcChatText != "" || player[myPlayer].sign != -1) && !editChest)
        {
            GUIChatDrawInner();
        }
    }
References Terraria.TimeLogger.DrawException(), Terraria.Main.editChest, Terraria.Main.GUIChatDrawInner(), Terraria.Main.ignoreErrors, Terraria.Main.myPlayer, Terraria.Main.npcChatText, Terraria.Main.player, and Terraria.Main.sign.
Referenced by Terraria.UI.IngameFancyUI.Draw(), and Terraria.Main.DrawInterface_23_NPCSignsDialog().