Terraria: Terraria.Main.NotifyOfEvent
NotifyOfEvent()
static void Terraria.Main.NotifyOfEvent (GameNotificationType type) inline static
Definition at line 15651 of file Main.cs.
    {
        if (!dedServ && !instance.IsActive && _flashNotificationType.HasFlag(type))
        {
            QueueMainThreadAction(delegate
            {
                Platform.Get<IWindowService>().StartFlashingIcon(instance.Window);
            });
        }
    }
References Terraria.Main._flashNotificationType, Terraria.Main.dedServ, Terraria.Main.instance, Terraria.Main.QueueMainThreadAction(), and System.type.
Referenced by Terraria.Player.Hurt(), Terraria.Player.KillMe(), and Terraria.Player.Spawn().