Terraria: Terraria.Main.CreativeMenu
CreativeMenu
CreativeUI Terraria.Main.CreativeMenu = new CreativeUI() static
Definition at line 369 of file Main.cs.
Referenced by Terraria.GameContent.UI.Elements.UICreativeInfiniteItemsDisplay.BuildSacrificeMenuContents(), Terraria.Initializers.UILinksInitializer.CanEnterCreativeMenu(), Terraria.Player.ClearPlayerTempInfo(), Terraria.WorldGen.clearWorld(), Terraria.GameContent.UI.Elements.UICreativeInfiniteItemsDisplay.descriptionText_OnUpdate(), Terraria.Main.DrawInterface_27_Inventory(), Terraria.Main.DrawInventory(), Terraria.GameContent.UI.Elements.UICreativeInfiniteItemsDisplay.EscapeVirtualKeyboard(), Terraria.Initializers.UILinksInitializer.GetCornerWrapPageIdFromRightToLeft(), Terraria.GameContent.UI.Elements.UICreativeInfiniteItemsDisplay.GoBackHere(), Terraria.UI.Gamepad.UILinkPointNavigator.GoToDefaultPage(), Terraria.Initializers.UILinksInitializer.Load(), Terraria.UI.ItemSlot.OverrideHover(), Terraria.UI.ItemSlot.OverrideLeftClick(), Terraria.GameContent.UI.Elements.UICreativeInfiniteItemsDisplay.SacrificeWhatYouCan(), Terraria.Player.SaveTemporaryItemSlotContents(), Terraria.DataStructures.TileEntity.SetInteractionAnchor(), Terraria.Player.SetPlayerDataToOutOfClassFields(), Terraria.GameContent.UI.States.UICreativePowersMenu.SetupGamepadPoints(), Terraria.Player.ToggleCreativeMenu(), and Terraria.Main.UpdateUIStates().