Terraria: Terraria.Main.OnCharacterNamed
OnCharacterNamed()
void Terraria.Main.OnCharacterNamed (string text) inline private
Definition at line 45161 of file Main.cs.
    {
        PendingPlayer.name = text.Trim();
        PlayerFileData.CreateAndSave(PendingPlayer);
        LoadPlayers();
        menuMode = 1;
    }
References Terraria.IO.PlayerFileData.CreateAndSave(), Terraria.Main.LoadPlayers(), Terraria.Main.menuMode, Terraria.Main.PendingPlayer, and System.text.
Referenced by Terraria.Main.DrawMenu().