Terraria: Terraria.Main.DrawSunAndMoon
DrawSunAndMoon()
void Terraria.Main.DrawSunAndMoon (SceneArea sceneArea, Microsoft::Xna::Framework::Color moonColor, Microsoft::Xna::Framework::Color sunColor, float tempMushroomInfluence) inline private
Definition at line 59644 of file Main.cs.
    {
        Texture2D value = TextureAssets.Sun.Value;
        int num = moonType;
        if (!TextureAssets.Moon.IndexInRange(num))
        {
            num = Utils.Clamp(num, 0, 8);
        }
        Texture2D value2 = TextureAssets.Moon[num].Value;
        int num2 = sceneArea.bgTopY;
        int num3 = (int)(time / 54000.0 * (double)(sceneArea.totalWidth + (float)(value.Width * 2))) - value.Width;
        int num4 = 0;
        float num5 = 1f;
        float rotation = (float)(time / 54000.0) * 2f - 7.3f;
        int num6 = (int)(time / 32400.0 * (double)(sceneArea.totalWidth + (float)(value2.Width * 2))) - value2.Width;
        int num7 = 0;
        float num8 = 1f;
        float num9 = (float)(time / 32400.0) * 2f - 7.3f;
        if (dayTime)
        {
            double num10;
            if (time < 27000.0)
            {
                num10 = Math.Pow(1.0 - time / 54000.0 * 2.0, 2.0);
                num4 = (int)((double)num2 + num10 * 250.0 + 180.0);
            }
            else
            {
                num10 = Math.Pow((time / 54000.0 - 0.5) * 2.0, 2.0);
                num4 = (int)((double)num2 + num10 * 250.0 + 180.0);
            }
            num5 = (float)(1.2 - num10 * 0.4);
        }
        else
        {
            double num11;
            if (time < 16200.0)
            {
                num11 = Math.Pow(1.0 - time / 32400.0 * 2.0, 2.0);
                num7 = (int)((double)num2 + num11 * 250.0 + 180.0);
            }
            else
            {
                num11 = Math.Pow((time / 32400.0 - 0.5) * 2.0, 2.0);
                num7 = (int)((double)num2 + num11 * 250.0 + 180.0);
            }
            num8 = (float)(1.2 - num11 * 0.4);
        }
        num5 *= ForcedMinimumZoom;
        num8 *= ForcedMinimumZoom;
        if (starGame)
        {
            if (WorldGen.generatingWorld)
            {
                alreadyGrabbingSunOrMoon = true;
                if (rand.Next(60) == 0)
                {
                    for (int i = 0; i < numStars; i++)
                    {
                        if (star[i].hidden)
{
                            Star.SpawnStars(i);
                        }
                    }
                }
                if (dayTime)
                {
                    dayTime = false;
                    time = 0.0;
                }
            }
            else
            {
                starGame = false;
            }
        }
        else
        {
            starsHit = 0;
        }
        if (dayTime)
        {
            if ((remixWorld && !gameMenu) || WorldGen.remixWorldGen)
            {
                return;
            }
            num5 *= 1.1f;
            float num12 = 1f - tempMushroomInfluence;
            num12 -= cloudAlpha * 1.5f * atmo;
            if (num12 < 0f)
            {
                num12 = 0f;
            }
            Microsoft.Xna.Framework.Color color = new Microsoft.Xna.Framework.Color((byte)(255f * num12), (byte)((float)(int)sunColor.G * num12), (byte)((float)(int)sunColor.B * num12), (byte)(255f * num12));
            Microsoft.Xna.Framework.Color color2 = new Microsoft.Xna.Framework.Color((byte)((float)(int)sunColor.R * num12), (byte)((float)(int)sunColor.G * num12), (byte)((float)(int)sunColor.B * num12), (byte)((float)(int)sunColor.B * num12));
            bool flag = false;
            if (eclipse)
            {
                value = TextureAssets.Sun3.Value;
                flag = true;
            }
            else if (!gameMenu && player[myPlayer].head == 12)
            {
                value = TextureAssets.Sun2.Value;
                flag = true;
            }
            if (flag)
            {
                color2 = new Microsoft.Xna.Framework.Color((byte)((float)(int)sunColor.R * num12), (byte)((float)(int)sunColor.G * num12), (byte)((float)(int)sunColor.B * num12), (byte)((float)(sunColor.B - 60) * num12));
            }
            Vector2 origin = value.Size() / 2f;
            Vector2 position = new Vector2(num3, num4 + sunModY) + sceneArea.SceneLocalScreenPositionOffset;
            spriteBatch.Draw(value, position, null, color, rotation, origin, num5, SpriteEffects.None, 0f);
            spriteBatch.Draw(value, position, null, color2, rotation, origin, num5, SpriteEffects.None, 0f);
        }
        if (!dayTime)
        {
            float num13 = 1f - cloudAlpha * 1.5f * atmo;
            if (num13 < 0f)
            {
                num13 = 0f;
            }
            moonColor *= num13;
            Vector2 position2 = new Vector2(num6, num7 + moonModY) + sceneArea.SceneLocalScreenPositionOffset;
            if (WorldGen.drunkWorldGen)
            {
                spriteBatch.Draw(TextureAssets.SmileyMoon.Value, position2, new Microsoft.Xna.Framework.Rectangle(0, 0, TextureAssets.SmileyMoon.Width(), TextureAssets.SmileyMoon.Height()), moonColor, num9 / 2f + (float)Math.PI, new Vector2(TextureAssets.SmileyMoon.Width() / 2, TextureAssets.SmileyMoon.Width() / 2), num8, SpriteEffects.None, 0f);
            }
            else if (pumpkinMoon)
            {
                spriteBatch.Draw(TextureAssets.PumpkinMoon.Value, position2, new Microsoft.Xna.Framework.Rectangle(0, TextureAssets.PumpkinMoon.Width() * moonPhase, TextureAssets.PumpkinMoon.Width(), TextureAssets.PumpkinMoon.Width()), moonColor, num9, new Vector2(TextureAssets.PumpkinMoon.Width() / 2, TextureAssets.PumpkinMoon.Width() / 2), num8, SpriteEffects.None, 0f);
            }
            else if (snowMoon)
            {
                spriteBatch.Draw(TextureAssets.SnowMoon.Value, position2, new Microsoft.Xna.Framework.Rectangle(0, TextureAssets.SnowMoon.Width() * moonPhase, TextureAssets.SnowMoon.Width(), TextureAssets.SnowMoon.Width()), moonColor, num9, new Vector2(TextureAssets.SnowMoon.Width() / 2, TextureAssets.SnowMoon.Width() / 2), num8, SpriteEffects.None, 0f);
            }
            else
            {
                spriteBatch.Draw(TextureAssets.Moon[num].Value, position2, new Microsoft.Xna.Framework.Rectangle(0, TextureAssets.Moon[num].Width() * moonPhase, TextureAssets.Moon[num].Width(), TextureAssets.Moon[num].Width()), moonColor, num9, new Vector2(TextureAssets.Moon[num].Width() / 2, TextureAssets.Moon[num].Width() / 2), num8, SpriteEffects.None, 0f);
            }
        }
        Microsoft.Xna.Framework.Rectangle value3 = ((!dayTime) ? new Microsoft.Xna.Framework.Rectangle((int)((double)num6 - (double)TextureAssets.Moon[num].Width() * 0.5 * (double)num8), (int)((double)num7 - (double)TextureAssets.Moon[num].Width() * 0.5 * (double)num8 + (double)moonModY), (int)((float)TextureAssets.Moon[num].Width() * num8), (int)((float)TextureAssets.Moon[num].Width() * num8)) : new Microsoft.Xna.Framework.Rectangle((int)((double)num3 - (double)TextureAssets.Sun.Width() * 0.5 * (double)num5), (int)((double)num4 - (double)TextureAssets.Sun.Height() * 0.5 * (double)num5 + (double)sunModY), (int)((float)TextureAssets.Sun.Width() * num5), (int)((float)TextureAssets.Sun.Width() * num5)));
        value3.Offset((int)sceneArea.SceneLocalScreenPositionOffset.X, (int)sceneArea.SceneLocalScreenPositionOffset.Y);
        Microsoft.Xna.Framework.Rectangle rectangle = new Microsoft.Xna.Framework.Rectangle(mouseX, mouseY, 1, 1);
        sunModY = (short)((double)sunModY * 0.999);
        moonModY = (short)((double)moonModY * 0.999);
        if (!gameMenu || netMode == 1)
        {
            return;
        }
        if (rectangle.Intersects(value3) || alreadyGrabbingSunOrMoon)
        {
            player[myPlayer].mouseInterface = true;
        }
        if ((mouseLeft || starGame) && hasFocus)
        {
            if (!rectangle.Intersects(value3) && !alreadyGrabbingSunOrMoon)
            {
                return;
            }
            if (dayTime)
            {
                time = 54000.0 * (double)((float)(mouseX + TextureAssets.Sun.Width()) / ((float)screenWidth + (float)(TextureAssets.Sun.Width() * 2)));
                sunModY = (short)(mouseY - num4);
                if (time > 53990.0)
                {
                    time = 53990.0;
                }
            }
            else
            {
                time = 32400.0 * (double)((float)(mouseX + TextureAssets.Moon[num].Width()) / ((float)screenWidth + (float)(TextureAssets.Moon[num].Width() * 2)));
                moonModY = (short)(mouseY - num7);
                if (time > 32390.0)
                {
                    time = 32390.0;
                }
            }
            if (time < 10.0)
            {
                time = 10.0;
            }
            alreadyGrabbingSunOrMoon = true;
        }
        else
        {
            alreadyGrabbingSunOrMoon = false;
        }
    }
References Terraria.Main.alreadyGrabbingSunOrMoon, Terraria.Main.atmo, Terraria.Main.cloudAlpha, Terraria.Main.dayTime, Terraria.WorldGen.drunkWorldGen, Terraria.Main.eclipse, Terraria.Main.ForcedMinimumZoom, Terraria.Main.gameMenu, Terraria.WorldGen.generatingWorld, Terraria.Main.hasFocus, Terraria.GameContent.TextureAssets.Moon, Terraria.Main.moonModY, Terraria.Main.moonPhase, Terraria.Main.moonType, Terraria.Main.mouseLeft, Terraria.Main.mouseX, Terraria.Main.mouseY, Terraria.Main.myPlayer, Terraria.Main.netMode, Terraria.Main.numStars, Terraria.Main.player, Terraria.GameContent.TextureAssets.PumpkinMoon, Terraria.Main.pumpkinMoon, Terraria.Main.rand, Terraria.Main.remixWorld, Terraria.WorldGen.remixWorldGen, Terraria.Main.screenWidth, Terraria.GameContent.TextureAssets.SmileyMoon, Terraria.GameContent.TextureAssets.SnowMoon, Terraria.Main.snowMoon, Terraria.Star.SpawnStars(), Terraria.Main.spriteBatch, Terraria.Main.star, Terraria.Main.starGame, Terraria.Main.starsHit, Terraria.GameContent.TextureAssets.Sun, Terraria.GameContent.TextureAssets.Sun2, Terraria.GameContent.TextureAssets.Sun3, Terraria.Main.sunModY, Terraria.Main.time, and ReLogic.Content.Asset< T >.Value.
Referenced by Terraria.Main.DoDraw(), and Terraria.Main.DrawCapture().