Terraria: Terraria.Main.DoLightTiles
DoLightTiles()
void Terraria.Main.DoLightTiles () inline private
Definition at line 60764 of file Main.cs.
    {
        GetAreaToLight(out firstTileX, out lastTileX, out firstTileY, out lastTileY);
        if (!drawSkip)
        {
            Lighting.LightTiles(firstTileX, lastTileX, firstTileY, lastTileY);
        }
    }
References Terraria.Main.drawSkip, Terraria.Main.firstTileX, Terraria.Main.firstTileY, Terraria.Main.GetAreaToLight(), Terraria.Main.lastTileX, Terraria.Main.lastTileY, and Terraria.Lighting.LightTiles().
Referenced by Terraria.Main.DoDraw().