Terraria: Terraria.Main.DrawStar
DrawStar()
void Terraria.Main.DrawStar (ref SceneArea sceneArea, float starOpacity, Microsoft::Xna::Framework::Color bgColorForStars, int i, Star theStar, bool artificial, bool foreground = false) inline private
Definition at line 59868 of file Main.cs.
    {
        if (theStar == null || theStar.hidden)
        {
            return;
        }
        float num = shimmerAlpha;
        Microsoft.Xna.Framework.Color color = default(Microsoft.Xna.Framework.Color);
        float num2 = 1f - theStar.fadeIn;
        int num3 = (int)((float)(255 - bgColorForStars.R - 100) * theStar.twinkle * num2);
        int num4 = (int)((float)(255 - bgColorForStars.G - 100) * theStar.twinkle * num2);
        int num5 = (int)((float)(255 - bgColorForStars.B - 100) * theStar.twinkle * num2);
        num3 = (num3 + num5 + num4) / 3;
        if (num3 <= 0)
        {
            return;
        }
        num3 = (int)((double)num3 * 1.4);
        if (num3 > 255)
        {
            num3 = 255;
        }
        num4 = num3;
        num5 = num3;
        color.R = (byte)num3;
        color.G = (byte)num4;
        color.B = (byte)num5;
        color *= starOpacity;
        if (num > 0f)
        {
            Microsoft.Xna.Framework.Color value = color;
            if (i % 3 == 0)
            {
                value.G = (byte)((float)(int)color.G * (1f - num * 0f) * theStar.twinkle * theStar.twinkle);
            }
            else if (i % 3 == 1)
            {
                value.B = (byte)((float)(int)color.B * (1f - num * 0f) * theStar.twinkle * theStar.twinkle);
            }
            else if (i % 3 == 2)
            {
                value.R = (byte)((float)(int)color.R * (1f - num * 0f) * theStar.twinkle * theStar.twinkle);
            }
            color = Microsoft.Xna.Framework.Color.Lerp(color, value, num);
            if (artificial)
            {
                color *= num;
            }
            else
            {
                color *= 1f - num;
            }
        }
        Vector2 vector = new Vector2(theStar.position.X / 1920f, theStar.position.Y / 1200f) * new Vector2(sceneArea.totalWidth, sceneArea.totalHeight) + new Vector2(0f, sceneArea.bgTopY) + sceneArea.SceneLocalScreenPositionOffset;
        if (!theStar.falling)
        {
            if (vector.X < 0f)
            {
                vector.X += screenWidth;
            }
            if (vector.X > (float)screenWidth)
            {
                vector.X -= screenWidth;
            }
            if (vector.Y < 0f)
            {
                vector.Y += screenHeight;
            }
            if (vector.Y > (float)screenHeight)
            {
                vector.Y -= screenHeight;
            }
        }
        if (foreground)
        {
            Vector2 value2 = vector / ScreenSize.ToVector2();
            float fromMax = 0.35f;
            float num6 = Utils.Remap(Vector2.Distance(value2, new Vector2(0.5f, 0.5f)), 0f, fromMax, 0f, 1f);
            color *= num6;
            Microsoft.Xna.Framework.Color color2 = Lighting.GetColor((vector + screenPosition).ToTileCoordinates());
            float num7 = (float)(int)Math.Max(Math.Max(color2.R, color2.G), color2.B) / 255f;
            color *= 1f - num7;
        }
        Texture2D value3 = TextureAssets.Star[theStar.type].Value;
        Vector2 origin = value3.Size() / 2f;
        if (theStar.falling)
        {
            theStar.fadeIn = 0f;
            int num8 = theStar.fallTime;
            float num9 = 30f;
            if ((float)num8 > num9)
            {
                num8 = (int)num9;
            }
            for (int j = 1; j < num8; j++)
            {
                Vector2 vector2 = theStar.fallSpeed * j * 0.4f;
                float num10 = theStar.scale * (1f - (float)j * 1f / num9);
                Microsoft.Xna.Framework.Color color3 = color;
                _ = theStar.rotation;
                color3 *= 1f - (float)j * 1f / num9;
                spriteBatch.Draw(value3, vector - vector2, null, color3, theStar.rotation, origin, num10 * theStar.twinkle * ForcedMinimumZoom, SpriteEffects.None, 0f);
            }
            if (starGame && theStar.fallSpeed.Y > 0f && Vector2.Distance(new Vector2(mouseX, mouseY), vector) < 70f)
            {
                starsHit++;
                theStar.fallSpeed = vector - new Vector2(mouseX, mouseY);
                theStar.fallSpeed.Normalize();
                theStar.fallSpeed *= 10f;
                if (theStar.fallSpeed.Y > 0f)
                {
                    theStar.fallSpeed.Y *= -1f;
                }
                SoundEngine.PlaySound(38);
                SoundEngine.PlaySound(37);
            }
        }
        spriteBatch.Draw(value3, vector, null, color, theStar.rotation, origin, theStar.scale * theStar.twinkle * ForcedMinimumZoom, SpriteEffects.None, 0f);
    }
References Microsoft.Xna.Framework.Color.B, Microsoft.Xna.Framework.Vector2.Distance(), Terraria.Main.ForcedMinimumZoom, Microsoft.Xna.Framework.Color.G, Terraria.Lighting.GetColor(), System.Text.RegularExpressions.i, Microsoft.Xna.Framework.Color.Lerp(), System.Math.Max(), Terraria.Main.mouseX, Terraria.Main.mouseY, Terraria.Audio.SoundEngine.PlaySound(), Microsoft.Xna.Framework.Color.R, Terraria.Utils.Remap(), Terraria.Main.screenHeight, Terraria.Main.screenPosition, Terraria.Main.ScreenSize, Terraria.Main.screenWidth, Terraria.Main.shimmerAlpha, Terraria.Main.spriteBatch, Terraria.GameContent.TextureAssets.Star, Terraria.Main.starGame, Terraria.Main.starsHit, System.value, and Microsoft.Xna.Framework.Graphics.Vector2.
Referenced by Terraria.Main.DrawStarsInBackground().