Terraria: Terraria.Main.OpenShop
OpenShop()
void Terraria.Main.OpenShop (int shopIndex) inline private
Definition at line 37250 of file Main.cs.
    {
        playerInventory = true;
        stackSplit = 9999;
        npcChatText = "";
        SetNPCShopIndex(shopIndex);
        shop[npcShop].SetupShop(npcShop);
        SoundEngine.PlaySound(12);
    }
References Terraria.Main.npcChatText, Terraria.Main.npcShop, Terraria.Main.playerInventory, Terraria.Audio.SoundEngine.PlaySound(), Terraria.Main.SetNPCShopIndex(), Terraria.Chest.SetupShop(), Terraria.Main.shop, and Terraria.Main.stackSplit.
Referenced by Terraria.Main.GUIChatDrawInner().