Terraria: Terraria.Main.EntitySpriteDraw
EntitySpriteDraw() [2/3]
static void Terraria.Main.EntitySpriteDraw (Texture2D texture, Vector2 position, Microsoft::Xna::Framework::Rectangle? sourceRectangle, Microsoft::Xna::Framework::Color color, float rotation, Vector2 origin, float scale, SpriteEffects effects, float worthless = 0f) inline static
Definition at line 34658 of file Main.cs.
    {
        EntitySpriteDraw(texture, position, sourceRectangle, color, rotation, origin, new Vector2(scale), effects, worthless);
    }
References Terraria.Main.EntitySpriteDraw(), and Microsoft.Xna.Framework.Graphics.Vector2.
Referenced by Terraria.Main.DrawKite(), Terraria.Main.DrawMultisegmentPet(), Terraria.Main.DrawMurderAurora(), Terraria.Main.DrawPrettyStarSparkle(), Terraria.Main.DrawProj_EmpressBlade(), Terraria.Main.DrawProj_FishingLine(), Terraria.Main.DrawProj_FlailChains_Old(), Terraria.Main.DrawProj_Flamethrower(), Terraria.Main.DrawProj_Spear(), Terraria.Main.DrawProjDirect(), Terraria.Main.DrawProjWithStarryTrail(), Terraria.Main.DrawTrail(), Terraria.Main.DrawTwinsPet(), and Terraria.Main.EntitySpriteDraw().