Terraria: Terraria.Main.DrawCachedNPCs
DrawCachedNPCs()
void Terraria.Main.DrawCachedNPCs (List< int > npcCache, bool behindTiles) inline protected
Definition at line 34837 of file Main.cs.
    {
        for (int i = 0; i < npcCache.Count; i++)
        {
            try
            {
                DrawNPC(npcCache[i], behindTiles);
            }
            catch
            {
                npc[npcCache[i]].active = false;
            }
        }
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Count, Terraria.Main.DrawNPC(), System.Text.RegularExpressions.i, and Terraria.Main.npc.
Referenced by Terraria.Main.DoDraw(), Terraria.Main.DoDraw_DrawNPCsOverTiles(), Terraria.Main.DoDraw_WallsTilesNPCs(), and Terraria.Main.DrawCapture().