Terraria: Terraria.Main.OpenPlayerSelect
OpenPlayerSelect()
static void Terraria.Main.OpenPlayerSelect (OnPlayerSelected method) inline static
Definition at line 63193 of file Main.cs.
    {
        if ((gameMenu && (menuMode == 10 || menuMode == 14)) || WorldGen.gen)
        {
            return;
        }
        if (!gameMenu)
        {
            WorldGen.SaveAndQuit(delegate
            {
                menuMode = 888;
                _blockFancyUIWhileLoading = true;
                LoadPlayers();
                MenuUI.SetState(_characterSelectMenu);
                _blockFancyUIWhileLoading = false;
                _pendingCharacterSelect = method;
            });
        }
        else
        {
            menuMode = 888;
            _blockFancyUIWhileLoading = true;
            LoadPlayers();
            MenuUI.SetState(_characterSelectMenu);
            _blockFancyUIWhileLoading = false;
            _pendingCharacterSelect = method;
        }
    }
References Terraria.Main._blockFancyUIWhileLoading, Terraria.Main._characterSelectMenu, Terraria.Main._pendingCharacterSelect, Terraria.Main.gameMenu, Terraria.WorldGen.gen, Terraria.Main.LoadPlayers(), Terraria.Main.menuMode, Terraria.Main.MenuUI, and Terraria.WorldGen.SaveAndQuit().
Referenced by Terraria.Social.WeGame.NetClientSocialModule.CheckParameters(), Terraria.Social.Steam.NetClientSocialModule.ConnectToLobby(), Terraria.Social.Steam.NetClientSocialModule.OnLobbyJoinRequest(), and Terraria.Social.WeGame.NetClientSocialModule.OnRailRespondInvation().