Terraria: Terraria.Main.DrawMapIcons_PotionOfReturnHomePosition
DrawMapIcons_PotionOfReturnHomePosition()
void Terraria.Main.DrawMapIcons_PotionOfReturnHomePosition (SpriteBatch spriteBatch, Vector2 mapTopLeft, Vector2 mapX2Y2AndOff, Microsoft::Xna::Framework::Rectangle? mapRect, float mapScale, float drawScale, ref string mouseTextString) inline private
Definition at line 53522 of file Main.cs.
    {
        Vector2? potionOfReturnHomePosition = LocalPlayer.PotionOfReturnHomePosition;
        if (!potionOfReturnHomePosition.HasValue)
        {
            return;
        }
        Vector2 vec = (potionOfReturnHomePosition + new Vector2(0f, -LocalPlayer.height / 2)).Value / 16f - mapTopLeft;
        vec *= mapScale;
        vec += mapX2Y2AndOff;
        vec = vec.Floor();
        if (!mapRect.HasValue || mapRect.Value.Contains(vec.ToPoint()))
        {
            Texture2D value = TextureAssets.Extra[175].Value;
            Microsoft.Xna.Framework.Rectangle rectangle = value.Frame();
            spriteBatch.Draw(value, vec, rectangle, Microsoft.Xna.Framework.Color.White, 0f, rectangle.Size() / 2f, drawScale, SpriteEffects.None, 0f);
            if (Utils.CenteredRectangle(vec, rectangle.Size() * drawScale).Contains(MouseScreen.ToPoint()))
            {
                mouseTextString = Language.GetTextValue("GameUI.PotionOfReturnHomePortal");
                _ = MouseScreen + new Vector2(-28f) + new Vector2(4f, 0f);
            }
        }
    }
References Terraria.Utils.CenteredRectangle(), System.Collections.Generic.Dictionary< TKey, TValue >.Contains(), Terraria.GameContent.TextureAssets.Extra, Terraria.Localization.Language.GetTextValue(), Terraria.Main.LocalPlayer, Terraria.Main.MouseScreen, Terraria.Main.spriteBatch, System.value, Microsoft.Xna.Framework.Graphics.Vector2, and Microsoft.Xna.Framework.Color.White.
Referenced by Terraria.Main.DrawMiscMapIcons().