Terraria: Terraria.Main.MouseText_DrawItemTooltip_GetLinesInfo
MouseText_DrawItemTooltip_GetLinesInfo()
static void Terraria.Main.MouseText_DrawItemTooltip_GetLinesInfo (Item item, ref int yoyoLogo, ref int researchLine, float oldKB, ref int numLines, string[] toolTipLine, bool[] preFixLine, bool[] badPreFixLine) inline static
    {
        toolTipLine[0] = item.HoverName;
        if (item.favorited)
        {
            toolTipLine[numLines++] = Lang.tip[56].Value;
            toolTipLine[numLines++] = Lang.tip[57].Value;
            if (LocalPlayer.chest != -1)
            {
                ChestUI.GetContainerUsageInfo(out var _, out var chestinv);
                if (ChestUI.IsBlockedFromTransferIntoChest(item, chestinv))
                {
                    toolTipLine[numLines++] = Language.GetTextValue("UI.ItemCannotBePlacedInsideItself");
                }
            }
        }
        if (item.social)
        {
            toolTipLine[numLines] = Lang.tip[0].Value;
            numLines++;
            toolTipLine[numLines] = Lang.tip[1].Value;
            numLines++;
        }
        else
        {
            if (item.damage > 0 && (!item.notAmmo || item.useStyle != 0) && (item.type < 71 || item.type > 74 || player[myPlayer].HasItem(905)))
            {
                float num = 5E-06f;
                int damage = item.damage;
                damage = (int)((float)damage * ItemID.Sets.ToolTipDamageMultiplier[item.type]);
                if (item.melee)
                {
                    toolTipLine[numLines] = string.Concat((int)(LocalPlayer.meleeDamage * (float)damage + num));
                    toolTipLine[numLines] += Lang.tip[2].Value;
                }
                else if (item.ranged)
                {
                    float num2 = LocalPlayer.rangedDamage;
                    if (item.useAmmo == AmmoID.Arrow || item.useAmmo == AmmoID.Stake)
                    {
                        num2 = LocalPlayer.bowEffectiveDamage;
                        if (LocalPlayer.archery)
{
                            num2 *= 1.1f;
                        }
                    }
                    if (item.useAmmo == AmmoID.Bullet || item.useAmmo == AmmoID.CandyCorn)
                    {
                        num2 = LocalPlayer.gunEffectiveDamage;
                    }
                    if (item.useAmmo == AmmoID.Rocket || item.useAmmo == AmmoID.StyngerBolt || item.useAmmo == AmmoID.JackOLantern || item.useAmmo == AmmoID.NailFriendly || item.useAmmo == AmmoID.Coin || item.useAmmo == AmmoID.Flare || item.useAmmo == AmmoID.Dart || item.useAmmo == AmmoID.Snowball || item.useAmmo == AmmoID.Sand || item.useAmmo == AmmoID.FallenStar || item.useAmmo == AmmoID.Gel)
                    {
                        num2 = LocalPlayer.specialistEffectiveDamage;
                    }
                    if (item.type == 1156 || item.type == 3350 || item.type == 3210 || item.type == 160 || item.type == 3821)
                    {
                        num2 = LocalPlayer.specialistEffectiveDamage;
                    }
                    toolTipLine[numLines] = string.Concat((int)(num2 * (float)damage + num));
                    toolTipLine[numLines] += Lang.tip[3].Value;
                }
                else if (item.magic)
                {
                    toolTipLine[numLines] = string.Concat((int)(LocalPlayer.magicDamage * (float)damage + num));
                    toolTipLine[numLines] += Lang.tip[4].Value;
                }
                else if (item.summon)
                {
                    toolTipLine[numLines] = string.Concat((int)(LocalPlayer.minionDamage * (float)damage + num));
                    toolTipLine[numLines] += Lang.tip[53].Value;
                }
                else
                {
                    toolTipLine[numLines] = string.Concat(damage);
                    toolTipLine[numLines] += Lang.tip[55].Value;
                }
                numLines++;
                if (item.melee)
                {
                    int num3 = player[myPlayer].meleeCrit - player[myPlayer].inventory[player[myPlayer].selectedItem].crit + item.crit;
                    toolTipLine[numLines] = num3 + Lang.tip[5].Value;
                    numLines++;
                }
                else if (item.ranged)
                {
                    int num4 = player[myPlayer].rangedCrit - player[myPlayer].inventory[player[myPlayer].selectedItem].crit + item.crit;
                    toolTipLine[numLines] = num4 + Lang.tip[5].Value;
                    numLines++;
                }
                else if (item.magic)
                {
                    int num5 = player[myPlayer].magicCrit - player[myPlayer].inventory[player[myPlayer].selectedItem].crit + item.crit;
                    toolTipLine[numLines] = num5 + Lang.tip[5].Value;
                    numLines++;
                }
                if (item.useStyle != 0 && !item.summon)
                {
                    if (item.useAnimation <= 8)
                    {
                        toolTipLine[numLines] = Lang.tip[6].Value;
                    }
                    else if (item.useAnimation <= 20)
                    {
                        toolTipLine[numLines] = Lang.tip[7].Value;
                    }
                    else if (item.useAnimation <= 25)
                    {
                        toolTipLine[numLines] = Lang.tip[8].Value;
                    }
                    else if (item.useAnimation <= 30)
                    {
                        toolTipLine[numLines] = Lang.tip[9].Value;
                    }
                    else if (item.useAnimation <= 35)
                    {
                        toolTipLine[numLines] = Lang.tip[10].Value;
                    }
                    else if (item.useAnimation <= 45)
                    {
                        toolTipLine[numLines] = Lang.tip[11].Value;
                    }
                    else if (item.useAnimation <= 55)
                    {
                        toolTipLine[numLines] = Lang.tip[12].Value;
                    }
                    else
                    {
                        toolTipLine[numLines] = Lang.tip[13].Value;
                    }
                    numLines++;
                }
                float num6 = item.knockBack;
                if (item.summon)
                {
                    num6 += player[myPlayer].minionKB;
                }
                if ((player[myPlayer].magicQuiver && item.useAmmo == AmmoID.Arrow) || item.useAmmo == AmmoID.Stake)
                {
                    num6 = (int)(num6 * 1.1f);
                }
                if (player[myPlayer].inventory[player[myPlayer].selectedItem].type == 3106 && item.type == 3106)
                {
                    num6 += num6 * (1f - player[myPlayer].stealth);
                }
                if (num6 == 0f)
                {
                    toolTipLine[numLines] = Lang.tip[14].Value;
                }
                else if ((double)num6 <= 1.5)
                {
                    toolTipLine[numLines] = Lang.tip[15].Value;
                }
                else if (num6 <= 3f)
                {
                    toolTipLine[numLines] = Lang.tip[16].Value;
                }
                else if (num6 <= 4f)
                {
                    toolTipLine[numLines] = Lang.tip[17].Value;
                }
                else if (num6 <= 6f)
                {
                    toolTipLine[numLines] = Lang.tip[18].Value;
                }
                else if (num6 <= 7f)
                {
                    toolTipLine[numLines] = Lang.tip[19].Value;
                }
                else if (num6 <= 9f)
                {
                    toolTipLine[numLines] = Lang.tip[20].Value;
                }
                else if (num6 <= 11f)
                {
                    toolTipLine[numLines] = Lang.tip[21].Value;
                }
                else
                {
                    toolTipLine[numLines] = Lang.tip[22].Value;
                }
                numLines++;
            }
            if (item.fishingPole > 0)
            {
                toolTipLine[numLines] = Language.GetTextValue("GameUI.PrecentFishingPower", item.fishingPole);
                numLines++;
                toolTipLine[numLines] = Language.GetTextValue("GameUI.BaitRequired");
                numLines++;
            }
            if (item.bait > 0)
            {
                toolTipLine[numLines] = Language.GetTextValue("GameUI.BaitPower", item.bait);
                numLines++;
            }
            if (item.headSlot > 0 || item.bodySlot > 0 || item.legSlot > 0 || item.accessory || projHook[item.shoot] || item.mountType != -1 || (item.buffType > 0 && (lightPet[item.buffType] || vanityPet[item.buffType])))
            {
                if ((item.type == 854 || item.type == 3035) && npcShop > 0)
                {
                    toolTipLine[numLines] = Lang.tip[60].Value;
                }
                else
                {
                    toolTipLine[numLines] = Lang.tip[23].Value;
                }
                numLines++;
            }
            if (item.tileWand > 0)
            {
                toolTipLine[numLines] = Lang.tip[52].Value + Lang.GetItemNameValue(item.tileWand);
                numLines++;
            }
            if (item.questItem)
            {
                toolTipLine[numLines] = Lang.inter[65].Value;
                numLines++;
            }
            if (item.vanity)
            {
                toolTipLine[numLines] = Lang.tip[24].Value;
                numLines++;
            }
            if (item.defense > 0)
            {
                toolTipLine[numLines] = item.defense + Lang.tip[25].Value;
                numLines++;
            }
            if (item.pick > 0)
            {
                toolTipLine[numLines] = item.pick + Lang.tip[26].Value;
                numLines++;
            }
            if (item.axe > 0)
            {
                toolTipLine[numLines] = item.axe * 5 + Lang.tip[27].Value;
                numLines++;
            }
            if (item.hammer > 0)
            {
                toolTipLine[numLines] = item.hammer + Lang.tip[28].Value;
                numLines++;
            }
            if (item.tileBoost != 0)
            {
                int tileBoost = item.tileBoost;
                if (tileBoost > 0)
                {
                    toolTipLine[numLines] = "+" + tileBoost + Lang.tip[54].Value;
                }
                else
                {
                    toolTipLine[numLines] = tileBoost + Lang.tip[54].Value;
                }
                numLines++;
            }
            if (item.healLife > 0)
            {
                if (item.type == 3001)
                {
                    int healLife = item.healLife;
                    int num7 = 120;
                    toolTipLine[numLines] = Language.GetTextValue("CommonItemTooltip.RestoresLifeRange", healLife, num7);
                }
                else
                {
                    toolTipLine[numLines] = Language.GetTextValue("CommonItemTooltip.RestoresLife", item.healLife);
                }
                numLines++;
            }
            if (item.healMana > 0)
            {
                toolTipLine[numLines] = Language.GetTextValue("CommonItemTooltip.RestoresMana", item.healMana);
                numLines++;
            }
            if (item.mana > 0 && (item.type != 127 || !player[myPlayer].spaceGun))
            {
                toolTipLine[numLines] = Language.GetTextValue("CommonItemTooltip.UsesMana", (int)((float)item.mana * player[myPlayer].manaCost));
                numLines++;
            }
            if (item.createWall > 0 || item.createTile > -1)
            {
                if (item.type != 213 && item.type != 5295 && item.tileWand < 1)
                {
                    toolTipLine[numLines] = Lang.tip[33].Value;
                    numLines++;
                }
            }
            else if (item.ammo > 0 && !item.notAmmo)
            {
                toolTipLine[numLines] = Lang.tip[34].Value;
                numLines++;
            }
            else if (item.consumable && !item.chlorophyteExtractinatorConsumable)
            {
                toolTipLine[numLines] = Lang.tip[35].Value;
                numLines++;
            }
            if (item.material)
            {
                toolTipLine[numLines] = Lang.tip[36].Value;
                numLines++;
            }
            if (item.ToolTip != null)
            {
                for (int i = 0; i < item.ToolTip.Lines; i++)
                {
                    if (i == 0 && ItemID.Sets.UsesCursedByPlanteraTooltip[item.type] && !NPC.downedPlantBoss)
                    {
                        toolTipLine[numLines] = Lang.tip[59].Value;
                        numLines++;
                    }
                    else
                    {
                        toolTipLine[numLines] = item.ToolTip.GetLine(i);
                        numLines++;
                    }
                }
            }
            if (tenthAnniversaryWorld && item.type == 238)
            {
                toolTipLine[numLines] = Language.GetTextValue("CommonItemTooltip.WizardHatDuringAnniversary");
                numLines++;
            }
            if (getGoodWorld && remixWorld)
            {
                if (item.type == 556 || item.type == 557 || item.type == 544)
                {
                    numLines--;
                    toolTipLine[numLines] = Language.GetTextValue("CommonItemTooltip.MechSummonDuringEverything");
                    numLines++;
                }
            }
            else if (item.type == 5334)
            {
                numLines--;
                toolTipLine[numLines] = "";
                numLines--;
                toolTipLine[numLines] = Language.GetTextValue("CommonItemTooltip.MechdusaSummonNotDuringEverything");
                numLines++;
            }
            if ((item.type == 3818 || item.type == 3819 || item.type == 3820 || item.type == 3824 || item.type == 3825 || item.type == 3826 || item.type == 3829 || item.type == 3830 || item.type == 3831 || item.type == 3832 || item.type == 3833 || item.type == 3834) && !player[myPlayer].downedDD2EventAnyDifficulty)
            {
                toolTipLine[numLines] = Lang.misc[104].Value;
                numLines++;
            }
            if (item.buffType > 0 && BuffID.Sets.IsWellFed[item.buffType] && expertMode)
            {
                toolTipLine[numLines] = Lang.misc[40].Value;
                numLines++;
            }
            if (item.buffTime > 0)
            {
                string text = ((item.buffTime / 60 < 60) ? Language.GetTextValue("CommonItemTooltip.SecondDuration", Math.Round((double)item.buffTime / 60.0)) : Language.GetTextValue("CommonItemTooltip.MinuteDuration", Math.Round((double)(item.buffTime / 60) / 60.0)));
                toolTipLine[numLines] = text;
                numLines++;
            }
            if (item.type == 3262 || item.type == 3282 || item.type == 3283 || item.type == 3284 || item.type == 3285 || item.type == 3286 || item.type == 3316 || item.type == 3315 || item.type == 3317 || item.type == 3291 || item.type == 3389)
            {
                toolTipLine[numLines] = " ";
                yoyoLogo = numLines;
                numLines++;
            }
            if (item.prefix > 0)
            {
                Item item2 = tooltipPrefixComparisonItem;
                if (item2 == null || item2.netID != item.netID)
                {
                    item2 = new Item();
                    item2.netDefaults(item.netID);
                }
                if (item2.damage != item.damage)
                {
                    double num8 = (float)item.damage - (float)item2.damage;
                    num8 = num8 / (double)item2.damage * 100.0;
                    num8 = Math.Round(num8);
                    if (num8 > 0.0)
                    {
                        toolTipLine[numLines] = "+" + num8 + Lang.tip[39].Value;
                    }
                    else
                    {
                        toolTipLine[numLines] = num8 + Lang.tip[39].Value;
                    }
                    if (num8 < 0.0)
                    {
                        badPreFixLine[numLines] = true;
                    }
                    preFixLine[numLines] = true;
                    numLines++;
                }
                if (item2.useAnimation != item.useAnimation)
                {
                    double num9 = (float)item.useAnimation - (float)item2.useAnimation;
                    num9 = num9 / (double)item2.useAnimation * 100.0;
                    num9 = Math.Round(num9);
                    num9 *= -1.0;
                    if (num9 > 0.0)
                    {
                        toolTipLine[numLines] = "+" + num9 + Lang.tip[40].Value;
                    }
                    else
                    {
                        toolTipLine[numLines] = num9 + Lang.tip[40].Value;
                    }
                    if (num9 < 0.0)
                    {
                        badPreFixLine[numLines] = true;
                    }
                    preFixLine[numLines] = true;
                    numLines++;
                }
                if (item2.crit != item.crit)
                {
                    double num10 = (float)item.crit - (float)item2.crit;
                    if (num10 > 0.0)
                    {
                        toolTipLine[numLines] = "+" + num10 + Lang.tip[41].Value;
                    }
                    else
                    {
                        toolTipLine[numLines] = num10 + Lang.tip[41].Value;
                    }
                    if (num10 < 0.0)
                    {
                        badPreFixLine[numLines] = true;
                    }
                    preFixLine[numLines] = true;
                    numLines++;
                }
                if (item2.mana != item.mana)
                {
                    double num11 = (float)item.mana - (float)item2.mana;
                    num11 = num11 / (double)item2.mana * 100.0;
                    num11 = Math.Round(num11);
                    if (num11 > 0.0)
                    {
                        toolTipLine[numLines] = "+" + num11 + Lang.tip[42].Value;
                    }
                    else
                    {
                        toolTipLine[numLines] = num11 + Lang.tip[42].Value;
                    }
                    if (num11 > 0.0)
                    {
                        badPreFixLine[numLines] = true;
                    }
                    preFixLine[numLines] = true;
                    numLines++;
                }
                if (item2.scale != item.scale)
                {
                    double num12 = item.scale - item2.scale;
                    num12 = num12 / (double)item2.scale * 100.0;
                    num12 = Math.Round(num12);
                    if (num12 > 0.0)
                    {
                        toolTipLine[numLines] = "+" + num12 + Lang.tip[43].Value;
                    }
                    else
                    {
                        toolTipLine[numLines] = num12 + Lang.tip[43].Value;
                    }
                    if (num12 < 0.0)
                    {
                        badPreFixLine[numLines] = true;
                    }
                    preFixLine[numLines] = true;
                    numLines++;
                }
                if (item2.shootSpeed != item.shootSpeed)
                {
                    double num13 = item.shootSpeed - item2.shootSpeed;
                    num13 = num13 / (double)item2.shootSpeed * 100.0;
                    num13 = Math.Round(num13);
                    if (num13 > 0.0)
                    {
                        toolTipLine[numLines] = "+" + num13 + Lang.tip[44].Value;
                    }
                    else
                    {
                        toolTipLine[numLines] = num13 + Lang.tip[44].Value;
                    }
                    if (num13 < 0.0)
                    {
                        badPreFixLine[numLines] = true;
                    }
                    preFixLine[numLines] = true;
                    numLines++;
                }
                if (item2.knockBack != oldKB)
                {
                    double num14 = oldKB - item2.knockBack;
                    num14 = num14 / (double)item2.knockBack * 100.0;
                    num14 = Math.Round(num14);
                    if (num14 > 0.0)
                    {
                        toolTipLine[numLines] = "+" + num14 + Lang.tip[45].Value;
                    }
                    else
                    {
                        toolTipLine[numLines] = num14 + Lang.tip[45].Value;
                    }
                    if (num14 < 0.0)
                    {
                        badPreFixLine[numLines] = true;
                    }
                    preFixLine[numLines] = true;
                    numLines++;
                }
                if (item.prefix == 62)
                {
                    toolTipLine[numLines] = "+1" + Lang.tip[25].Value;
                    preFixLine[numLines] = true;
                    numLines++;
                }
                if (item.prefix == 63)
                {
                    toolTipLine[numLines] = "+2" + Lang.tip[25].Value;
                    preFixLine[numLines] = true;
                    numLines++;
                }
                if (item.prefix == 64)
                {
                    toolTipLine[numLines] = "+3" + Lang.tip[25].Value;
                    preFixLine[numLines] = true;
                    numLines++;
                }
                if (item.prefix == 65)
                {
                    toolTipLine[numLines] = "+4" + Lang.tip[25].Value;
                    preFixLine[numLines] = true;
                    numLines++;
                }
                if (item.prefix == 66)
                {
                    toolTipLine[numLines] = "+20 " + Lang.tip[31].Value;
                    preFixLine[numLines] = true;
                    numLines++;
                }
                if (item.prefix == 67)
                {
                    toolTipLine[numLines] = "+2" + Lang.tip[5].Value;
                    preFixLine[numLines] = true;
                    numLines++;
                }
                if (item.prefix == 68)
                {
                    toolTipLine[numLines] = "+4" + Lang.tip[5].Value;
                    preFixLine[numLines] = true;
                    numLines++;
                }
                if (item.prefix == 69)
                {
                    toolTipLine[numLines] = "+1" + Lang.tip[39].Value;
                    preFixLine[numLines] = true;
                    numLines++;
                }
                if (item.prefix == 70)
                {
                    toolTipLine[numLines] = "+2" + Lang.tip[39].Value;
                    preFixLine[numLines] = true;
                    numLines++;
                }
                if (item.prefix == 71)
                {
                    toolTipLine[numLines] = "+3" + Lang.tip[39].Value;
                    preFixLine[numLines] = true;
                    numLines++;
                }
                if (item.prefix == 72)
                {
                    toolTipLine[numLines] = "+4" + Lang.tip[39].Value;
                    preFixLine[numLines] = true;
                    numLines++;
                }
                if (item.prefix == 73)
                {
                    toolTipLine[numLines] = "+1" + Lang.tip[46].Value;
                    preFixLine[numLines] = true;
                    numLines++;
                }
                if (item.prefix == 74)
                {
                    toolTipLine[numLines] = "+2" + Lang.tip[46].Value;
                    preFixLine[numLines] = true;
                    numLines++;
                }
                if (item.prefix == 75)
                {
                    toolTipLine[numLines] = "+3" + Lang.tip[46].Value;
                    preFixLine[numLines] = true;
                    numLines++;
                }
                if (item.prefix == 76)
                {
                    toolTipLine[numLines] = "+4" + Lang.tip[46].Value;
                    preFixLine[numLines] = true;
                    numLines++;
                }
                if (item.prefix == 77)
                {
                    toolTipLine[numLines] = "+1" + Lang.tip[47].Value;
                    preFixLine[numLines] = true;
                    numLines++;
                }
                if (item.prefix == 78)
                {
                    toolTipLine[numLines] = "+2" + Lang.tip[47].Value;
                    preFixLine[numLines] = true;
                    numLines++;
                }
                if (item.prefix == 79)
                {
                    toolTipLine[numLines] = "+3" + Lang.tip[47].Value;
                    preFixLine[numLines] = true;
                    numLines++;
                }
                if (item.prefix == 80)
                {
                    toolTipLine[numLines] = "+4" + Lang.tip[47].Value;
                    preFixLine[numLines] = true;
                    numLines++;
                }
            }
            if (item.wornArmor && player[myPlayer].setBonus != "")
            {
                toolTipLine[numLines] = Lang.tip[48].Value + " " + player[myPlayer].setBonus;
                numLines++;
            }
        }
        if (item.expert)
        {
            toolTipLine[numLines] = Language.GetTextValue("GameUI.Expert");
            numLines++;
        }
        if (item.rare == -13)
        {
            toolTipLine[numLines] = Language.GetTextValue("GameUI.Master");
            numLines++;
        }
        if ((item.tooltipContext == 0 || item.tooltipContext == 2 || item.tooltipContext == 1 || item.tooltipContext == 3 || item.tooltipContext == 4 || item.tooltipContext == 32 || item.tooltipContext == 15 || item.tooltipContext == 6 || item.tooltipContext == 22 || item.tooltipContext == 7 || item.tooltipContext == 5) && LocalPlayer.difficulty == 3 && CreativeItemSacrificesCatalog.Instance.TryGetSacrificeCountCapToUnlockInfiniteItems(item.type, out var amountNeeded))
        {
            int sacrificeCount = LocalPlayerCreativeTracker.ItemSacrifices.GetSacrificeCount(item.type);
            if (amountNeeded - sacrificeCount > 0)
            {
                toolTipLine[numLines] = Language.GetTextValue("CommonItemTooltip.CreativeSacrificeNeeded", amountNeeded - sacrificeCount);
                researchLine = numLines;
                numLines++;
            }
        }
        string bestiaryNotes = item.BestiaryNotes;
        if (!string.IsNullOrWhiteSpace(bestiaryNotes))
        {
            string[] array = bestiaryNotes.Split('\n');
            foreach (string text2 in array)
            {
                toolTipLine[numLines++] = text2;
            }
        }
    }
References Terraria.ID.AmmoID.Arrow, Terraria.ID.AmmoID.Bullet, Terraria.ID.AmmoID.CandyCorn, Terraria.ID.AmmoID.Coin, Terraria.ID.AmmoID.Dart, Terraria.NPC.downedPlantBoss, Terraria.Main.expertMode, Terraria.ID.AmmoID.FallenStar, Terraria.ID.AmmoID.Flare, Terraria.ID.AmmoID.Gel, Terraria.UI.ChestUI.GetContainerUsageInfo(), Terraria.Main.getGoodWorld, Terraria.Lang.GetItemNameValue(), Terraria.Localization.Language.GetTextValue(), Terraria.GameContent.Creative.CreativeItemSacrificesCatalog.Instance, Terraria.Lang.inter, Terraria.UI.ChestUI.IsBlockedFromTransferIntoChest(), Terraria.ID.BuffID.Sets.IsWellFed, Terraria.Main.item, Terraria.ID.AmmoID.JackOLantern, Terraria.Main.lightPet, Terraria.Main.LocalPlayer, Terraria.Main.LocalPlayerCreativeTracker, Terraria.Lang.misc, Terraria.Main.myPlayer, Terraria.ID.AmmoID.NailFriendly, Terraria.Main.npcShop, Terraria.Main.player, Terraria.Main.projHook, Terraria.Main.remixWorld, Terraria.ID.AmmoID.Rocket, Terraria.ID.AmmoID.Sand, Terraria.ID.AmmoID.Snowball, Terraria.ID.AmmoID.Stake, Terraria.ID.AmmoID.StyngerBolt, Terraria.Main.tenthAnniversaryWorld, Terraria.Lang.tip, Terraria.ID.ItemID.Sets.ToolTipDamageMultiplier, Terraria.Main.tooltipPrefixComparisonItem, Terraria.ID.ItemID.Sets.UsesCursedByPlanteraTooltip, ReLogic.Content.Asset< T >.Value, and Terraria.Main.vanityPet.
Referenced by Terraria.GameContent.Creative.ItemFilters.BySearch.FitsFilter(), and Terraria.Main.MouseText_DrawItemTooltip().