Terraria: Terraria.Main.Initialize
Initialize()
override void Terraria.Main.Initialize () inline protected
    {
        musicFade[50] = 1f;
        if (dedServ)
        {
            netMode = 2;
        }
        for (int i = 0; i < 10; i++)
        {
            recentWorld[i] = "";
            recentIP[i] = "";
            recentPort[i] = 0;
        }
        if (rand == null)
        {
            rand = new UnifiedRandom((int)DateTime.Now.Ticks);
        }
        SetTitle();
        lo = rand.Next(6);
        waterfallManager = new WaterfallManager();
        _windowMover = new WindowStateController();
        sittingManager = new AnchoredEntitiesCollection();
        sleepingManager = new AnchoredEntitiesCollection();
        gameTips = new GameTipsDisplay();
        if (player[myPlayer] == null)
        {
            player[myPlayer] = new Player();
        }
        ContentSamples.Initialize();
        PlayerInput.Initialize();
        player[myPlayer] = new Player();
        WorldGen.Hooks.OnWorldLoad += delegate
        {
            AmbienceServer = new AmbienceServer();
            LocalGolfState = new GolfState();
            if (!dedServ)
            {
                Lighting.Clear();
            }
        };
        DontStarveSeed.Initialize();
        ResourceSetsManager = new PlayerResourceSetsManager();
        MinimapFrameManagerInstance = new MinimapFrameManager();
        PlayerInput.OnActionableInput += delegate
        {
            if (LocalGolfState != null)
            {
                LocalGolfState.CancelBallTracking();
            }
        };
        SceneMetrics = new SceneMetrics();
        BindSettingsTo(Configuration);
        if (dedServ)
        {
            Initialize_AlmostEverything();
            return;
        }
        TimeLogger.Initialize();
        LoadContent_TryEnteringHiDef();
        ClientInitialize();
        base.Initialize();
    }
References Terraria.Main._windowMover, Terraria.Main.AmbienceServer, Terraria.Main.BindSettingsTo(), Terraria.Lighting.Clear(), Terraria.Main.ClientInitialize(), Terraria.Main.Configuration, Terraria.Main.dedServ, Terraria.Main.gameTips, Terraria.GameContent.DontStarveSeed.Initialize(), Terraria.GameInput.PlayerInput.Initialize(), Terraria.ID.ContentSamples.Initialize(), Terraria.TimeLogger.Initialize(), Terraria.Main.Initialize_AlmostEverything(), Terraria.Main.lo, Terraria.Main.LoadContent_TryEnteringHiDef(), Terraria.Main.LocalGolfState, Terraria.Main.MinimapFrameManagerInstance, Terraria.Main.musicFade, Terraria.Main.myPlayer, Terraria.Main.netMode, Terraria.Enums.Player, Terraria.Main.player, Terraria.Main.rand, Terraria.Main.recentIP, Terraria.Main.recentPort, Terraria.Main.recentWorld, Terraria.Main.ResourceSetsManager, Terraria.Main.SceneMetrics, Terraria.Main.SetTitle(), Terraria.Main.sittingManager, Terraria.Main.sleepingManager, and Terraria.Main.waterfallManager.
Referenced by Terraria.Main.DedServ().