Terraria: Terraria.Main.DrawSurfaceBG_BackMountainsStep1
DrawSurfaceBG_BackMountainsStep1()
void Terraria.Main.DrawSurfaceBG_BackMountainsStep1 (double backgroundTopMagicNumber, float bgGlobalScaleMultiplier, int pushBGTopHack) inline private
Definition at line 56755 of file Main.cs.
    {
        Microsoft.Xna.Framework.Color colorOfSurfaceBackgroundsBase = ColorOfSurfaceBackgroundsBase;
        bgScale = 1f;
        bgTopY = (int)(backgroundTopMagicNumber * 1300.0 + 1090.0) + (int)scAdj + pushBGTopHack;
        bgScale *= bgGlobalScaleMultiplier;
        bgParallax = 0.15;
        bgWidthScaled = (int)(1024f * bgScale);
        SkyManager.Instance.DrawToDepth(spriteBatch, 1f / (float)bgParallax);
        bgStartX = (int)(0.0 - Math.IEEERemainder((double)screenPosition.X * bgParallax, bgWidthScaled) - (double)(bgWidthScaled / 2));
        if (bgWidthScaled == 0)
        {
            bgWidthScaled = 1024;
        }
        bgLoops = screenWidth / bgWidthScaled + 2;
        if (gameMenu)
        {
            bgTopY = 100 + pushBGTopHack;
        }
        if (!((double)screenPosition.Y < worldSurface * 16.0 + 16.0))
        {
            return;
        }
        if (bgAlphaFarBackLayer[0] > 0f)
        {
            ColorOfSurfaceBackgroundsModified = colorOfSurfaceBackgroundsBase * bgAlphaFarBackLayer[0];
            DrawSurfaceBG_DrawBackMountainsLayer(treeMntBGSet1[0]);
        }
        if (bgAlphaFarBackLayer[10] > 0f)
        {
            ColorOfSurfaceBackgroundsModified = colorOfSurfaceBackgroundsBase * bgAlphaFarBackLayer[10];
            DrawSurfaceBG_DrawBackMountainsLayer(treeMntBGSet2[0]);
        }
        if (bgAlphaFarBackLayer[11] > 0f)
        {
            ColorOfSurfaceBackgroundsModified = colorOfSurfaceBackgroundsBase * bgAlphaFarBackLayer[11];
            DrawSurfaceBG_DrawBackMountainsLayer(treeMntBGSet3[0]);
        }
        if (bgAlphaFarBackLayer[12] > 0f)
        {
            ColorOfSurfaceBackgroundsModified = colorOfSurfaceBackgroundsBase * bgAlphaFarBackLayer[12];
            DrawSurfaceBG_DrawBackMountainsLayer(treeMntBGSet4[0]);
        }
        if (bgAlphaFarBackLayer[1] > 0f)
        {
            ColorOfSurfaceBackgroundsModified = colorOfSurfaceBackgroundsBase * bgAlphaFarBackLayer[1];
            if (WorldGen.desertBG != 4)
            {
                DrawSurfaceBG_DrawBackMountainsLayer(23);
            }
        }
        if (bgAlphaFarBackLayer[2] > 0f)
        {
            ColorOfSurfaceBackgroundsModified = colorOfSurfaceBackgroundsBase * bgAlphaFarBackLayer[2];
            DrawSurfaceBG_DrawBackMountainsLayer(24);
        }
        if (bgAlphaFarBackLayer[4] > 0f)
        {
            ColorOfSurfaceBackgroundsModified = colorOfSurfaceBackgroundsBase * bgAlphaFarBackLayer[4];
            DrawSurfaceBG_DrawBackMountainsLayer(snowMntBG[0]);
        }
        if (bgAlphaFarBackLayer[5] > 0f)
        {
            ColorOfSurfaceBackgroundsModified = colorOfSurfaceBackgroundsBase * bgAlphaFarBackLayer[5];
            if (WorldGen.crimsonBG != 5)
            {
                DrawSurfaceBG_DrawBackMountainsLayer(24);
            }
        }
        if (bgAlphaFarBackLayer[6] > 0f && WorldGen.hallowBG == 3)
        {
            ColorOfSurfaceBackgroundsModified = colorOfSurfaceBackgroundsBase * bgAlphaFarBackLayer[6];
            DrawSurfaceBG_DrawBackMountainsLayer(246);
        }
        SkyManager.Instance.DrawToDepth(spriteBatch, 5f);
    }
References Terraria.Main.bgAlphaFarBackLayer, Terraria.Main.bgLoops, Terraria.Main.bgParallax, Terraria.Main.bgScale, Terraria.Main.bgStartX, Terraria.Main.bgTopY, Terraria.Main.bgWidthScaled, Terraria.Main.ColorOfSurfaceBackgroundsBase, Terraria.Main.ColorOfSurfaceBackgroundsModified, Terraria.WorldGen.crimsonBG, Terraria.WorldGen.desertBG, Terraria.Main.DrawSurfaceBG_DrawBackMountainsLayer(), Terraria.Main.gameMenu, Terraria.WorldGen.hallowBG, System.Math.IEEERemainder(), Terraria.Graphics.Effects.SkyManager.Instance, Terraria.Main.scAdj, Terraria.Main.screenWidth, Terraria.Main.snowMntBG, Terraria.Main.spriteBatch, Terraria.Main.treeMntBGSet1, Terraria.Main.treeMntBGSet2, Terraria.Main.treeMntBGSet3, Terraria.Main.treeMntBGSet4, and Terraria.Main.worldSurface.
Referenced by Terraria.Main.DrawSurfaceBG().