Terraria: Terraria.Main.PlayerRenderer
PlayerRenderer
IPlayerRenderer Terraria.Main.PlayerRenderer = new LegacyPlayerRenderer() static
Definition at line 291 of file Main.cs.
Referenced by Terraria.GameContent.UI.LegacyMultiplayerClosePlayersOverlay.Draw(), Terraria.GameContent.Tile_Entities.TEDisplayDoll.Draw(), Terraria.GameContent.Tile_Entities.TEHatRack.Draw(), Terraria.GameContent.Animations.Segments.PlayerSegment.Draw(), Terraria.Main.DrawClothesWindow(), Terraria.Main.DrawMenu(), Terraria.Main.DrawPlayers_AfterProjectiles(), Terraria.Main.DrawPlayers_BehindNPCs(), Terraria.GameContent.UI.Elements.UICharacter.DrawSelf(), Terraria.GameContent.UI.Elements.UIHairStyleButton.DrawSelf(), and Terraria.Main.DrawSuperSpecialProjectiles().