Terraria: Terraria.Main.DrawInterface_7_TownNPCHouseBanners
DrawInterface_7_TownNPCHouseBanners()
void Terraria.Main.DrawInterface_7_TownNPCHouseBanners () inline private
Definition at line 43191 of file Main.cs.
    {
        if (EquipPage != 1 && (!UILinkPointNavigator.Shortcuts.NPCS_IconsDisplay || !PlayerInput.UsingGamepad))
        {
            return;
        }
        if (ignoreErrors)
        {
            try
            {
                DrawNPCHousesInWorld();
                return;
            }
            catch (Exception e)
            {
                TimeLogger.DrawException(e);
                return;
            }
        }
        DrawNPCHousesInWorld();
    }
References Terraria.TimeLogger.DrawException(), Terraria.Main.DrawNPCHousesInWorld(), Terraria.Main.EquipPage, Terraria.Main.ignoreErrors, Terraria.UI.Gamepad.UILinkPointNavigator.Shortcuts.NPCS_IconsDisplay, and Terraria.GameInput.PlayerInput.UsingGamepad.
Referenced by Terraria.Main.SetupDrawInterfaceLayers().