Terraria: Terraria.Main.DrawInterface_12_IngameFancyUI
DrawInterface_12_IngameFancyUI()
static bool Terraria.Main.DrawInterface_12_IngameFancyUI () inline static private
Definition at line 43108 of file Main.cs.
    {
        spriteBatch.End();
        spriteBatch.Begin(SpriteSortMode.Deferred, BlendState.AlphaBlend, SamplerStateForCursor, DepthStencilState.None, RasterizerState.CullCounterClockwise, null, UIScaleMatrix);
        InGameUI.Draw(spriteBatch, _drawInterfaceGameTime);
        bool result = true;
        if (inFancyUI && !IngameFancyUI.Draw(spriteBatch, _drawInterfaceGameTime))
        {
            result = false;
            DrawPendingMouseText();
        }
        return result;
    }
References Terraria.Main._drawInterfaceGameTime, Microsoft.Xna.Framework.Graphics.BlendState.AlphaBlend, Microsoft.Xna.Framework.Graphics.RasterizerState.CullCounterClockwise, Terraria.UI.IngameFancyUI.Draw(), Terraria.Main.DrawPendingMouseText(), Terraria.Main.inFancyUI, Terraria.Main.InGameUI, Microsoft.Xna.Framework.Graphics.DepthStencilState.None, Terraria.Main.SamplerStateForCursor, Terraria.Main.spriteBatch, and Terraria.Main.UIScaleMatrix.
Referenced by Terraria.Main.SetupDrawInterfaceLayers().