Terraria: Terraria.Main.DrawGuideCraftText
DrawGuideCraftText()
static void Terraria.Main.DrawGuideCraftText (int adjY, Microsoft::Xna::Framework::Color craftingTipColor, out int inventoryX, out int inventoryY) inline static private
Definition at line 39175 of file Main.cs.
    {
        inventoryX = 73;
        inventoryY = 331;
        inventoryY += adjY;
        string text = null;
        _requiredObjecsForCraftingText.Clear();
        if (guideItem.IsAir)
        {
            text = Lang.inter[24].Value;
        }
        else
        {
            text = Lang.inter[21].Value + " " + guideItem.Name;
            Recipe recipe = Main.recipe[availableRecipe[focusRecipe]];
            for (int i = 0; i < Recipe.maxRequirements; i++)
            {
                int num = recipe.requiredTile[i];
                if (num == -1)
                {
                    break;
                }
                int requiredTileStyle = Recipe.GetRequiredTileStyle(num);
                string mapObjectName = Lang.GetMapObjectName(MapHelper.TileToLookup(num, requiredTileStyle));
                _requiredObjecsForCraftingText.Add(mapObjectName);
            }
            if (recipe.needWater)
            {
                _requiredObjecsForCraftingText.Add(Lang.inter[53].Value);
            }
            if (recipe.needHoney)
            {
                _requiredObjecsForCraftingText.Add(Lang.inter[58].Value);
            }
            if (recipe.needLava)
            {
                _requiredObjecsForCraftingText.Add(Lang.inter[56].Value);
            }
            if (recipe.needSnowBiome)
            {
                _requiredObjecsForCraftingText.Add(Lang.inter[123].Value);
            }
            if (recipe.needGraveyardBiome)
            {
                _requiredObjecsForCraftingText.Add(Lang.inter[124].Value);
            }
            if (_requiredObjecsForCraftingText.Count == 0)
            {
                string value = Lang.inter[23].Value;
                _requiredObjecsForCraftingText.Add(value);
            }
        }
        Microsoft.Xna.Framework.Color color = new Microsoft.Xna.Framework.Color(mouseTextColor, mouseTextColor, mouseTextColor, mouseTextColor);
        Vector2 vector = new Vector2(inventoryX + 50, inventoryY + 12);
        DynamicSpriteFont value2 = FontAssets.MouseText.Value;
        if (_requiredObjecsForCraftingText.Count > 0)
        {
            vector.Y -= 14f;
            Vector2 vector2 = vector + new Vector2(0f, 26f);
            Microsoft.Xna.Framework.Color color2 = color;
            string value3 = Lang.inter[22].Value;
            string text2 = string.Join(", ", _requiredObjecsForCraftingText);
            string text3 = value3 + " " + text2;
            DynamicSpriteFontExtensionMethods.DrawString(spriteBatch, value2, text3, vector2, color2, 0f, Vector2.Zero, 1f, SpriteEffects.None, 0f);
        }
        DynamicSpriteFontExtensionMethods.DrawString(spriteBatch, value2, text, vector, color, 0f, Vector2.Zero, 1f, SpriteEffects.None, 0f);
    }
References Terraria.Main._requiredObjecsForCraftingText, Terraria.Main.availableRecipe, ReLogic.Graphics.DynamicSpriteFontExtensionMethods.DrawString(), Terraria.Main.focusRecipe, Terraria.Lang.GetMapObjectName(), Terraria.Recipe.GetRequiredTileStyle(), Terraria.Main.guideItem, System.Text.RegularExpressions.i, Terraria.Lang.inter, Terraria.Recipe.maxRequirements, Terraria.GameContent.FontAssets.MouseText, Terraria.Main.mouseTextColor, Terraria.Main.recipe, Terraria.Main.spriteBatch, System.text, Terraria.Map.MapHelper.TileToLookup(), System.value, Microsoft.Xna.Framework.Graphics.Vector2, and Microsoft.Xna.Framework.Vector2.Zero.
Referenced by Terraria.Main.DrawInventory().