Terraria: Terraria.Main.ReportInvasionProgress
ReportInvasionProgress()
static void Terraria.Main.ReportInvasionProgress (int progress, int progressMax, int icon, int progressWave) inline static
Definition at line 44714 of file Main.cs.
    {
        invasionProgress = progress;
        invasionProgressMax = progressMax;
        invasionProgressIcon = icon;
        invasionProgressWave = progressWave;
        invasionProgressDisplayLeft = 160;
    }
References Terraria.Main.invasionProgress, Terraria.Main.invasionProgressDisplayLeft, Terraria.Main.invasionProgressIcon, Terraria.Main.invasionProgressMax, and Terraria.Main.invasionProgressWave.
Referenced by Terraria.NPC.checkDead(), Terraria.Main.CheckInvasionProgressDisplay(), Terraria.GameContent.Events.DD2Event.CheckProgress(), Terraria.NPC.CheckProgressFrostMoon(), Terraria.NPC.CheckProgressPumpkinMoon(), Terraria.MessageBuffer.GetData(), Terraria.GameContent.Events.DD2Event.ReportEventProgress(), Terraria.GameContent.Events.DD2Event.StartInvasion(), and Terraria.GameContent.Events.DD2Event.UpdateTime().