Terraria: Terraria.Main.DrawItem_GetBasics
DrawItem_GetBasics()
void Terraria.Main.DrawItem_GetBasics (Item item, int slot, out Texture2D texture, out Microsoft::Xna::Framework::Rectangle frame, out Microsoft::Xna::Framework::Rectangle glowmaskFrame) inline private
    {
        LoadItem(item.type);
        if (ItemID.Sets.AnimatesAsSoul[item.type] || ItemID.Sets.NebulaPickup[item.type])
        {
            DrawItem_AnimateSlot(slot, itemAnimations[item.type].TicksPerFrame, itemAnimations[item.type].FrameCount);
            texture = TextureAssets.Item[item.type].Value;
        }
        else if (ItemID.Sets.IsFood[item.type])
        {
            texture = TextureAssets.Item[item.type].Value;
        }
        else
        {
            switch (item.type)
            {
            case 5358:
            case 5359:
            case 5360:
            case 5361:
                LoadItem(5437);
                texture = TextureAssets.Item[5437].Value;
                break;
            case 71:
            case 72:
            case 73:
            case 74:
            {
                int num = item.type - 71;
                texture = TextureAssets.Coin[num].Value;
                DrawItem_AnimateSlot(slot, 6, 8);
                frame = (glowmaskFrame = _coinOnWorldAnimation.GetFrame(texture, itemFrameCounter[slot]));
                return;
            }
            case 3858:
                texture = TextureAssets.Item[item.type].Value;
                DrawItem_AnimateSlot(slot, 5, 3);
                frame = texture.Frame();
                glowmaskFrame = TextureAssets.GlowMask[233].Value.Frame(1, 3, 0, itemFrameCounter[slot] / 5);
                glowmaskFrame.Height -= 2;
                return;
            case 75:
                texture = TextureAssets.Item[item.type].Value;
                DrawItem_AnimateSlot(slot, itemAnimations[item.type].TicksPerFrame, itemAnimations[item.type].FrameCount * 2 - 1);
                break;
            default:
                texture = TextureAssets.Item[item.type].Value;
                break;
            }
        }
        if (itemAnimations[item.type] != null)
        {
            frame = (glowmaskFrame = itemAnimations[item.type].GetFrame(texture, itemFrameCounter[slot]));
        }
        else
        {
            frame = (glowmaskFrame = texture.Frame());
        }
    }
References Terraria.Main._coinOnWorldAnimation, Terraria.ID.ItemID.Sets.AnimatesAsSoul, Terraria.GameContent.TextureAssets.Coin, Terraria.Main.DrawItem_AnimateSlot(), Terraria.GameContent.TextureAssets.GlowMask, Terraria.ID.ItemID.Sets.IsFood, Terraria.GameContent.TextureAssets.Item, Terraria.Main.item, Terraria.Main.itemAnimations, Terraria.Main.itemFrameCounter, Terraria.Main.LoadItem(), Terraria.ID.ItemID.Sets.NebulaPickup, and ReLogic.Content.Asset< T >.Value.
Referenced by Terraria.Main.DrawItem().