Terraria: Terraria.Main.GetBackgroundRect
GetBackgroundRect()
Microsoft.Xna.Framework.? Rectangle Terraria.Main.GetBackgroundRect (int backgroundTextureIndex) inline private
Definition at line 57968 of file Main.cs.
    {
        int num = 0;
        Microsoft.Xna.Framework.Rectangle rectangle = new Microsoft.Xna.Framework.Rectangle(0, 0, 1, 1);
        switch (backgroundTextureIndex)
        {
        case 235:
            num = (int)(GetBackgroundCounter() / 20) % 4;
            rectangle = TextureAssets.Background[backgroundTextureIndex].Frame(2, 2, num % 2, num / 2);
            rectangle.Inflate(0, -2);
            return rectangle;
        case 219:
        case 220:
        case 221:
        case 271:
        case 272:
        case 273:
            num = (int)(GetBackgroundCounter() / 15) % 4;
            rectangle = TextureAssets.Background[backgroundTextureIndex].Frame(2, 2, num % 2, num / 2);
            rectangle.Inflate(0, -2);
            return rectangle;
        case 281:
            num = (int)(GetBackgroundCounter() / 5) % 4;
            rectangle = TextureAssets.Background[backgroundTextureIndex].Frame(2, 2, num % 2, num / 2);
            rectangle.Inflate(0, -2);
            return rectangle;
        default:
            return null;
        }
    }
References Terraria.GameContent.TextureAssets.Background, and Terraria.Main.GetBackgroundCounter().
Referenced by Terraria.Main.DrawSurfaceBG_DrawBackMountainsLayer(), Terraria.Main.DrawSurfaceBG_Forest(), Terraria.Main.DrawSurfaceBG_Hallow(), Terraria.Main.DrawSurfaceBG_Jungle(), and Terraria.Main.DrawSurfaceBG_Mushroom().