Terraria: Terraria.Main.GUIBarsDraw
GUIBarsDraw()
void Terraria.Main.GUIBarsDraw () inline
Definition at line 40176 of file Main.cs.
    {
        if (ignoreErrors)
        {
            try
            {
                GUIBarsDrawInner();
                return;
            }
            catch (Exception e)
            {
                TimeLogger.DrawException(e);
                return;
            }
        }
        GUIBarsDrawInner();
    }
References Terraria.TimeLogger.DrawException(), Terraria.Main.GUIBarsDrawInner(), and Terraria.Main.ignoreErrors.
Referenced by Terraria.Graphics.Capture.CaptureInterface.Draw(), Terraria.UI.IngameFancyUI.Draw(), and Terraria.Main.DrawInterface_25_ResourceBars().