Terraria: Terraria.Main.DrawBackGore
DrawBackGore()
void Terraria.Main.DrawBackGore () inline private
Definition at line 60249 of file Main.cs.
    {
        if (!drawBackGore)
        {
            return;
        }
        drawBackGore = false;
        if (ignoreErrors)
        {
            try
            {
                DrawGoreBehind();
                return;
            }
            catch (Exception e)
            {
                TimeLogger.DrawException(e);
                return;
            }
        }
        DrawGoreBehind();
    }
References Terraria.Main.drawBackGore, Terraria.TimeLogger.DrawException(), Terraria.Main.DrawGoreBehind(), and Terraria.Main.ignoreErrors.
Referenced by Terraria.Main.DoDraw_WallsTilesNPCs().