Terraria: Terraria.Main.ValueToCoins
ValueToCoins()
static string Terraria.Main.ValueToCoins (long value) inline static
Definition at line 52286 of file Main.cs.
    {
        long num = value;
        long num2 = 0L;
        long num3 = 0L;
        long num4 = 0L;
        long num5 = 0L;
        while (num >= 1000000)
        {
            num -= 1000000;
            num2++;
        }
        while (num >= 10000)
        {
            num -= 10000;
            num3++;
        }
        while (num >= 100)
        {
            num -= 100;
            num4++;
        }
        num5 = num;
        string text = "";
        if (num2 > 0)
        {
            text += string.Format("{0} {1} ", num2, Language.GetTextValue("Currency.Platinum").ToLower());
        }
        if (num3 > 0)
        {
            text += string.Format("{0} {1} ", num3, Language.GetTextValue("Currency.Gold").ToLower());
        }
        if (num4 > 0)
        {
            text += string.Format("{0} {1} ", num4, Language.GetTextValue("Currency.Silver").ToLower());
        }
        if (num5 > 0)
        {
            text += string.Format("{0} {1} ", num5, Language.GetTextValue("Currency.Copper").ToLower());
        }
        if (text.Length > 0)
        {
            text = text.Substring(0, text.Length - 1);
        }
        return text;
    }
References Terraria.Localization.Language.GetTextValue(), System.L, System.text, and System.value.
Referenced by Terraria.Player.DropCoins(), and Terraria.Player.KillMe().