Terraria: Terraria.Main.mouseItem
mouseItem
Item Terraria.Main.mouseItem = new Item() static
Definition at line 1773 of file Main.cs.
Referenced by Terraria.Player.ClearPlayerTempInfo(), Terraria.Main.CraftItem(), Terraria.GameContent.UI.Elements.UICreativeInfiniteItemsDisplay.descriptionText_OnUpdate(), Terraria.Main.DrawInterface_33_MouseText(), Terraria.Main.DrawInterface_38_MouseCarriedObject(), Terraria.Main.DrawInventory(), Terraria.Main.DrawNPCHousesInUI(), Terraria.Main.DrawPageIcons(), Terraria.Player.dropItemCheck(), Terraria.Player.DropItems(), Terraria.Player.DropSelectedItem(), Terraria.Player.DropSelectedItem(), Terraria.GameInput.PlayerInput.FastUseItemMemory.EndFastUse(), Terraria.GameInput.PlayerInput.EnterBuildingMode(), Terraria.GameInput.PlayerInput.ExitBuildingMode(), Terraria.GameContent.UI.WiresUI.WiresRadial.FlowerUpdate(), Terraria.UI.ItemSlot.GetGamepadInstructions(), Terraria.UI.ItemSlot.GetOverrideInstructions(), Terraria.Main.GUIHotbarDrawInner(), Terraria.UI.ItemSlot.HandleShopSlot(), Terraria.Player.ItemCheck_ApplyHoldStyle(), Terraria.Player.ItemCheck_TryPlacingWearablesOnMannequins(), Terraria.UI.ItemSlot.LeftClick(), Terraria.GameContent.UI.WiresUI.WiresRadial.LineUpdate(), Terraria.Initializers.UILinksInitializer.Load(), Terraria.Main.MouseTextInner(), Terraria.UI.ItemSlot.PickupItemIntoMouse(), Terraria.GameContent.Tile_Entities.TEFoodPlatter.PlaceItemInFrame(), Terraria.GameContent.Tile_Entities.TEItemFrame.PlaceItemInFrame(), Terraria.GameContent.Tile_Entities.TEWeaponsRack.PlaceItemInFrame(), Terraria.Player.PlaceWeapon(), Terraria.Player.PurgeDD2EnergyCrystals(), Terraria.UI.ItemSlot.RightClick(), Terraria.Player.SaveTemporaryItemSlotContents(), Terraria.GameContent.Creative.CreativeUI.ShouldDrawSacrificeArea(), Terraria.Player.ToggleInv(), Terraria.Main.TryAllowingToCraftRecipe(), Terraria.UI.ItemSlot.TryEnteringBuildingMode(), Terraria.UI.ItemSlot.TryEnteringFastUseMode(), Terraria.UI.ItemSlot.TryPickupDyeToCursor(), Terraria.GameInput.PlayerInput.FastUseItemMemory.TryStartForMouse(), Terraria.Graphics.Capture.CaptureInterface.Update(), Terraria.Player.UpdateDead(), and Terraria.GameInput.PlayerInput.VerifyBuildingMode().