Terraria: Terraria.Main.OpenResourcePacksMenu
OpenResourcePacksMenu()
static void Terraria.Main.OpenResourcePacksMenu (UIState uiStateToGoBackTo) inline static
Definition at line 49261 of file Main.cs.
    {
        menuMode = 888;
        MenuUI.SetState(new UIResourcePackSelectionMenu(uiStateToGoBackTo, AssetSourceController, AssetInitializer.CreateResourcePackList(instance.Services)));
    }
References Terraria.Initializers.AssetInitializer.CreateResourcePackList(), Terraria.Main.instance, Terraria.Main.menuMode, and Terraria.Main.MenuUI.
Referenced by Terraria.GameContent.UI.States.UIWorkshopHub.Click_OpenResourcePacksMenu(), and Terraria.Main.DrawMenu().