Terraria: Terraria.Main.DrawInterface_27_Inventory
DrawInterface_27_Inventory()
void Terraria.Main.DrawInterface_27_Inventory () inline private
    {
        HackForGamepadInputHell();
        if (playerInventory)
        {
            if (player[myPlayer].chest != -1)
            {
                CreativeMenu.CloseMenu();
            }
            if (ignoreErrors)
            {
                try
                {
                    DrawInventory();
                    return;
                }
                catch (Exception e)
                {
                    TimeLogger.DrawException(e);
                    return;
                }
            }
            DrawInventory();
        }
        else
        {
            CreativeMenu.CloseMenu();
            recFastScroll = true;
            SetMouseNPC(-1, -1);
            EquipPage = 0;
        }
    }
References Terraria.Main.chest, Terraria.Main.CreativeMenu, Terraria.TimeLogger.DrawException(), Terraria.Main.DrawInventory(), Terraria.Main.EquipPage, Terraria.Main.HackForGamepadInputHell(), Terraria.Main.ignoreErrors, Terraria.Main.myPlayer, Terraria.Main.player, Terraria.Main.playerInventory, Terraria.Main.recFastScroll, and Terraria.Main.SetMouseNPC().
Referenced by Terraria.Main.SetupDrawInterfaceLayers().