Terraria: Terraria.Main.PrepareDrawnProjectileDrawing
PrepareDrawnProjectileDrawing()
void Terraria.Main.PrepareDrawnProjectileDrawing (Projectile proj) inline
Definition at line 34622 of file Main.cs.
    {
        CurrentDrawnEntity = proj;
        int projectileDesiredShader = GetProjectileDesiredShader(proj);
        Matrix value = Transform;
        if (proj.isAPreviewDummy)
        {
            value = UIScaleMatrix;
        }
        PrepareDrawnEntityDrawing(proj, projectileDesiredShader, value);
    }
References Terraria.Main.CurrentDrawnEntity, Terraria.Main.GetProjectileDesiredShader(), Terraria.Main.PrepareDrawnEntityDrawing(), Terraria.Main.Transform, Terraria.Main.UIScaleMatrix, and System.value.
Referenced by Terraria.Main.DrawProj_EmpressBlade(), and Terraria.Main.DrawProjDirect().