Terraria: Terraria.Main.SetBackgroundOffsets
SetBackgroundOffsets()
void Terraria.Main.SetBackgroundOffsets (int backgroundID, double backgroundTopMagicNumber, int pushBGTopHack) inline private
Definition at line 57314 of file Main.cs.
    {
        int num = 0;
        int num2 = 0;
        switch (backgroundID)
        {
        case 18:
            if (WorldGen.hallowBG == 3)
            {
                bgParallax = 0.17;
                bgScale = 1.1f;
                num = 1400;
                num2 = 1100;
            }
            break;
        case 258:
            bgScale = 1.25f;
            bgParallax = 0.23;
            num = 1800;
            num2 = 850;
            break;
        case 259:
            bgScale = 1.31f;
            bgParallax = 0.33;
            num = 1950;
            num2 = 1500;
            break;
        case 260:
            bgScale = 1.34f;
            bgParallax = 0.4;
            num = 2100;
            num2 = 1650;
            break;
        case 263:
            bgScale = 1.25f;
            bgParallax = 0.23;
            num = 1800;
            num2 = 1450;
            break;
        case 264:
            bgScale = 1.31f;
            bgParallax = 0.33;
            num = 1950;
            num2 = 1700;
            break;
        case 265:
            bgScale = 1.34f;
            bgParallax = 0.4;
            num = 2100;
            num2 = 2000;
            break;
        case 267:
            bgScale = 1.25f;
            bgParallax = 0.23;
            num = 1700;
            num2 = 1300;
            break;
        case 266:
            bgScale = 1.31f;
            bgParallax = 0.33;
            num = 1950;
            num2 = 1600;
            break;
        case 268:
            bgScale = 1.34f;
            bgParallax = 0.41;
            num = 2100;
            num2 = 1850;
            break;
        case 248:
            bgScale = 1.3f;
            bgParallax = 0.37;
            num = 1800;
            num2 = 1100;
            break;
        case 249:
            bgScale = 1.4f;
            bgParallax = 0.43;
            num = 1950;
            num2 = 1200;
            break;
        case 250:
            bgScale = 1.7f;
            bgParallax = 0.49;
            num = 2000;
            num2 = 1000;
            break;
        case 255:
            bgScale = 1.15f;
            bgParallax = 0.25;
            num = 1800;
            num2 = 1450;
            break;
        case 256:
            bgScale = 1.21f;
            bgParallax = 0.32;
            num = 1950;
            num2 = 1550;
            break;
        case 257:
            bgScale = 1.34f;
            bgParallax = 0.4;
            num = 2100;
            num2 = 1550;
            break;
        case 240:
            bgScale = 1.15f;
            bgParallax = 0.3;
            num = 1800;
            num2 = 1500;
            break;
        case 241:
            bgScale = 1.21f;
            bgParallax = 0.43;
            num = 1950;
            num2 = 1300;
            break;
        case 242:
            bgScale = 1.34f;
            bgParallax = 0.49;
            num = 2100;
            num2 = 1400;
            break;
        case 243:
            bgScale = 1.15f;
            bgParallax = 0.25;
            num = 1800;
            num2 = 1400;
            break;
        case 244:
            bgScale = 1.21f;
            bgParallax = 0.35;
            num = 1950;
            num2 = 1550;
            break;
        case 245:
            bgScale = 1.24f;
            bgParallax = 0.45;
            num = 2100;
            num2 = 1650;
            break;
        case 273:
            bgParallax = 0.49000000953674316;
            num = 2100;
            num2 = 1560;
            break;
        case 234:
            bgParallax = 0.23;
            num = 1700;
            num2 = 1150;
            break;
        case 235:
            bgParallax = 0.33;
            num = 1950;
            num2 = 1550;
            break;
        case 236:
            bgParallax = 0.41;
            num = 2100;
            num2 = 2000;
            break;
        case 279:
            bgScale = 2.5f;
            bgParallax = 0.3499999940395355;
            num = 1850;
            num2 = 1750;
            break;
        case 282:
            bgScale = 2.6f;
            bgParallax = 0.25;
            num = 1800;
            num2 = 1340;
            break;
        case 261:
            bgParallax = 0.27;
            break;
        case 262:
            bgParallax = 0.4;
            break;
        case 219:
            bgParallax = 0.25;
            break;
        case 220:
            bgParallax = 0.34;
            break;
        case 221:
            bgParallax = 0.43;
            break;
        case 222:
            num = 1800;
            num2 = 1400;
            break;
        case 223:
            num = 2150;
            num2 = 1850;
            break;
        case 224:
            num = 2500;
            num2 = 2400;
            break;
        case 237:
            num = 1800;
            num2 = 1500;
            break;
        case 238:
            num = 1950;
            num2 = 1500;
            break;
        case 239:
            num = 2100;
            num2 = 1900;
            break;
        case 284:
            bgParallax = 0.23;
            num = 1600;
            num2 = 900;
            break;
        case 285:
            bgParallax = 0.36;
            num = 1900;
            num2 = 960;
            break;
        case 286:
            bgParallax = 0.42;
            num = 2100;
            num2 = 1200;
            break;
        case 287:
            bgParallax = 0.21;
            num = 1700;
            num2 = 1560;
            break;
        case 288:
            bgParallax = 0.33;
            num = 1950;
            num2 = 1730;
            break;
        case 289:
            bgParallax = 0.41;
            num = 2100;
            num2 = 1400;
            break;
        case 207:
            bgParallax = 0.32;
            break;
        }
        if (num != 0 || num2 != 0)
        {
            bgTopY = (int)(backgroundTopMagicNumber * (double)num + (double)num2) + (int)scAdj + pushBGTopHack;
        }
    }
References Terraria.Main.bgParallax, Terraria.Main.bgScale, Terraria.Main.bgTopY, Terraria.WorldGen.hallowBG, and Terraria.Main.scAdj.
Referenced by Terraria.Main.DrawSurfaceBG(), Terraria.Main.DrawSurfaceBG_Corrupt(), Terraria.Main.DrawSurfaceBG_Crimson(), Terraria.Main.DrawSurfaceBG_Desert(), Terraria.Main.DrawSurfaceBG_Forest(), Terraria.Main.DrawSurfaceBG_Hallow(), Terraria.Main.DrawSurfaceBG_Jungle(), Terraria.Main.DrawSurfaceBG_Mushroom(), and Terraria.Main.DrawSurfaceBG_Snow().