Terraria: Terraria.Main.SortBabyBirdProjectiles
SortBabyBirdProjectiles()
void Terraria.Main.SortBabyBirdProjectiles (List< int > list) inline private
Definition at line 34938 of file Main.cs.
    {
        List<int> list2 = new List<int>();
        for (int num = list.Count - 1; num >= 0; num--)
        {
            int num2 = list[num];
            if (Main.projectile[num2].type == 759)
            {
                list2.Add(num2);
                list.RemoveAt(num);
                Projectile projectile = Main.projectile[num2];
                Player master = player[projectile.owner];
                int stackedIndex = (int)projectile.localAI[0];
                if (projectile.frame == projFrames[projectile.type] - 1)
                {
                    projectile.Center = Projectile.AI_158_GetHomeLocation(master, stackedIndex);
                    projectile.velocity = Vector2.Zero;
                }
            }
        }
        list.AddRange(list2);
        list2.Clear();
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Add(), Terraria.Projectile.AI_158_GetHomeLocation(), System.Collections.Generic.Dictionary< TKey, TValue >.Clear(), System.list, Terraria.Main.player, Terraria.Main.projectile, Terraria.Main.projFrames, and Microsoft.Xna.Framework.Vector2.Zero.
Referenced by Terraria.Main.SortDrawCacheWorms().