Terraria: Terraria.Main.maxTilesX
maxTilesX
int Terraria.Main.maxTilesX = (int)rightWorld / 16 + 1 static
Referenced by Terraria.Main.Main(), Terraria.GameContent.Skies.NebulaSky.Activate(), Terraria.GameContent.Skies.SolarSky.Activate(), Terraria.GameContent.Skies.StardustSky.Activate(), Terraria.WorldGen.AddBuriedChest(), Terraria.WorldGen.AddHellHouses(), Terraria.WorldGen.AddShadowOrb(), Terraria.WorldGen.AddTrees(), Terraria.Liquid.AddWater(), Terraria.Collision.AdvancedTileCollision(), Terraria.NPC.AI(), Terraria.NPC.AI_006_Worms(), Terraria.Projectile.AI_007_GrapplingHooks(), Terraria.NPC.AI_007_TownEntities(), Terraria.Projectile.AI_016(), Terraria.NPC.AI_037_Destroyer(), Terraria.NPC.AI_107_ImprovedWalkers(), Terraria.Projectile.AI_121_StardustDragon(), Terraria.Projectile.AI_174_MultisegmentPet(), Terraria.Collision.AnyCollision(), Terraria.Collision.AnyCollisionWithSpecificTiles(), Terraria.GameContent.Biomes.JunglePass.ApplyPass(), Terraria.GameContent.Biomes.TerrainPass.ApplyPass(), Terraria.Main.autoCreate(), Terraria.Netplay.BroadcastThread(), Terraria.GameContent.ItemDropRules.Conditions.PirateMap.CanDrop(), Terraria.Collision.CanHit(), Terraria.Collision.CanHitLine(), Terraria.Collision.CanHitWithCheck(), Terraria.WorldGen.CanKillTile(), Terraria.TileObject.CanPlace(), Terraria.WorldBuilding.StructureMap.CanPlace(), Terraria.WorldGen.CanPlaceSink(), Terraria.DelegateMethods.CastLight(), Terraria.DelegateMethods.CastLightOpen(), Terraria.DelegateMethods.CastLightOpen_StopForSolids(), Terraria.DelegateMethods.CastLightOpen_StopForSolids_ScaleWithDistance(), Terraria.WorldGen.CaveOpenater(), Terraria.WorldGen.Cavinator(), Terraria.WorldGen.ChasmRunner(), Terraria.WorldGen.ChasmRunnerSideways(), Terraria.Player.CheckForGoodTeleportationSpot(), Terraria.WorldGen.CheckRoom(), Terraria.WorldGen.CheckSign(), Terraria.Player.CheckSpawn_Internal(), Terraria.DelegateMethods.CheckStopForSolids(), Terraria.WorldGen.checkUnderground(), Terraria.WorldBuilding.WorldUtils.ClampToWorld(), Terraria.Utils.ClampWithinWorld(), Terraria.IO.WorldFile.ClearTempTiles(), Terraria.WorldGen.clearWorld(), Terraria.WorldGen.CloudIsland(), Terraria.WorldGen.CloudLake(), Terraria.IO.WorldFile.ConvertIlluminantPaintToNewField(), Terraria.IO.WorldFile.ConvertOldTileEntities(), Terraria.WorldGen.CountNearBlocksTypes(), Terraria.StrayMethods.CountSandHorizontally(), Terraria.WorldGen.CountTileTypesInWorld(), Terraria.GameContent.Biomes.HiveBiome.CreateDentForHoneyFall(), Terraria.GameContent.Biomes.Desert.DesertDescription.CreateFromPlacement(), Terraria.GameContent.Biomes.HiveBiome.CreateHiveTunnel(), Terraria.GameContent.Biomes.HiveBiome.CreateStandForLarva(), Terraria.WorldGen.CrimStart(), Terraria.Projectile.CutTilesAt(), Terraria.Main.DedServ(), Terraria.WorldGen.DesertCloudIsland(), Terraria.WorldGen.DestroyHeart(), Terraria.WorldGen.digTunnel(), Terraria.WorldGen.DirtyRockRunner(), Terraria.GameContent.Skies.NebulaSky.Draw(), Terraria.GameContent.Skies.SolarSky.Draw(), Terraria.GameContent.Skies.StardustSky.Draw(), Terraria.GameContent.Skies.VortexSky.Draw(), Terraria.Main.DrawBackground(), Terraria.Main.DrawBlack(), Terraria.Main.DrawCapture(), Terraria.Main.DrawInfoAccs(), Terraria.Main.DrawMap(), Terraria.Main.DrawMapFullscreenBackground(), Terraria.Main.DrawMenu(), Terraria.Main.DrawToMap(), Terraria.GameContent.Drawing.WallDrawing.DrawWalls(), Terraria.WaterfallManager.DrawWaterfall(), Terraria.Main.DrawWaters(), Terraria.Main.DrawWires(), Terraria.WorldGen.dropMeteor(), Terraria.Collision.DrownCollision(), Terraria.WorldGen.DungeonEnt(), Terraria.WorldGen.DungeonHalls(), Terraria.WorldGen.DungeonRoom(), Terraria.WorldGen.DungeonStairs(), Terraria.DelegateMethods.EmitGolfCartDust_StopForSolids(), Terraria.WorldGen.EmptyTileCheck(), Terraria.WorldGen.EveryTileFrame(), Terraria.Graphics.Light.LightingEngine.ExportToMiniMap(), Terraria.WorldGen.FillWallHolesInArea(), Terraria.WorldGen.FillWallHolesInColumn(), Terraria.Player.FindSharpTearsSpot(), Terraria.WaterfallManager.FindWaterfalls(), Terraria.WorldGen.FinishDrunkGen(), Terraria.WorldGen.FinishGetGoodWorld(), Terraria.WorldGen.FinishNotTheBees(), Terraria.WorldGen.FinishRemixWorld(), Terraria.Projectile.FishingCheck(), Terraria.Projectile.FishingCheck_RollItemDrop(), Terraria.IO.WorldFile.FixDresserChests(), Terraria.WorldGen.FixHeart(), Terraria.WorldGen.FixHearts(), Terraria.WorldGen.FloatingIsland(), Terraria.GameContent.Biomes.HiveBiome.FrameOutAllHiveContents(), Terraria.GameContent.Skies.PartySky.GenerateBalloons(), Terraria.GameContent.Biomes.JunglePass.GenerateFinishingTouches(), Terraria.GameContent.Biomes.JunglePass.GenerateHolesInMudWalls(), Terraria.GameContent.Skies.LanternSky.GenerateLanterns(), Terraria.WorldGen.GeneratePlanteraBulbOnAllMechsDefeated(), Terraria.GameContent.Skies.SlimeSky.GenerateSlimes(), Terraria.GameContent.Biomes.JunglePass.GenerateTunnelToSurface(), Terraria.GameContent.Skies.MartianSky.GenerateUfos(), Terraria.WorldGen.GenerateWorld(), Terraria.WorldGen.GERunner(), Terraria.WorldGen.GetCommonTreeFoliageData(), Terraria.MessageBuffer.GetData(), Terraria.NPC.GetFairyTreasureCoords(), Terraria.Projectile.GetFishingPondWidth(), Terraria.Graphics.Capture.CaptureInterface.GetMapCoords(), Terraria.Player.GetPickaxeDamage(), Terraria.GameContent.Drawing.TileDrawing.GetScreenDrawArea(), Terraria.WorldGen.GetSectionBounds(), Terraria.Map.MapHelper.GetTileBaseOption(), Terraria.GameContent.Drawing.TileDrawing.GetTileDrawData(), Terraria.Collision.GetTilesIn(), Terraria.GameContent.ShopHelper.GetTravelingMerchantPrices(), Terraria.WorldGen.GetWorldSize(), Terraria.WorldGen.GrowGlowTulips(), Terraria.WorldGen.GrowLivingTreePassageRoom(), Terraria.Projectile.HandleMovement(), Terraria.WorldGen.HasAnyWireNearby(), Terraria.WorldGen.HellFort(), Terraria.Collision.HitTiles(), Terraria.Wiring.HitWire(), Terraria.WorldGen.Housing_GetTestedRoomBounds(), Terraria.Collision.HurtTiles(), Terraria.GameContent.Skies.MartianSky.ZipBehavior.InitializeUfo(), Terraria.GameContent.Skies.MartianSky.HoverBehavior.InitializeUfo(), Terraria.Netplay.InnerClientLoop(), Terraria.Map.MapHelper.InternalSaveMap(), Terraria.WorldGen.InWorld(), Terraria.Physics.BallCollision.IsBallInWorld(), Terraria.WorldGen.IsDungeon(), Terraria.WorldGen.IslandHouse(), Terraria.GameContent.Generation.TrackGenerator.IsLocationInvalid(), Terraria.Player.IsTileTypeInInteractionRange(), Terraria.WorldGen.IsUndergroundDesert(), Terraria.Player.ItemCheck_UseTeleportRod(), Terraria.Projectile.Kill(), Terraria.WorldGen.KillTile(), Terraria.WorldGen.KillTile_MakeTileDust(), Terraria.WorldGen.KillWall(), Terraria.WorldGen.Lakinater(), Terraria.Collision.LavaCollision(), Terraria.Map.MapHelper.LoadMapVersion1(), Terraria.Map.MapHelper.LoadMapVersion2(), Terraria.IO.WorldFile.LoadWorld_Version1_Old_BeforeRelease88(), Terraria.IO.WorldFile.LoadWorldTiles(), Terraria.Player.MagicConch(), Terraria.WorldGen.MakeDungeon(), Terraria.WorldGen.MakeDungeon_Banners(), Terraria.WorldGen.MakeDungeon_GroundFurniture(), Terraria.WorldGen.MakeDungeon_Lights(), Terraria.WorldGen.MakeDungeon_Pictures(), Terraria.WorldGen.MakeDungeon_Traps(), Terraria.GameContent.Drawing.TileDrawing.MakeExtraPreparations(), Terraria.Rain.MakeRain(), Terraria.WorldGen.makeTemple(), Terraria.WorldGen.MarblePileWithStatues(), Terraria.WorldGen.meteor(), Terraria.WorldGen.MineHouse(), Terraria.WorldGen.Mountinater(), Terraria.WorldGen.MudWallRunner(), Terraria.WorldGen.nearbyChlorophyte(), Terraria.WorldGen.NearFriendlyWall(), Terraria.WorldGen.neonMossBiome(), Terraria.Rain.NewRain(), Terraria.WorldGen.nextCount(), Terraria.WorldGen.nextDirtCount(), Terraria.WorldGen.NoNearbyAbigailsFlower(), Terraria.WorldGen.NoNearbyGlowTulips(), Terraria.Collision.noSlopeCollision(), Terraria.WorldGen.NotTheBees(), Terraria.WorldGen.OasisPlantWaterCheck(), Terraria.WorldGen.oceanCave(), Terraria.WorldGen.oceanDepths(), Terraria.Main.oldDrawWater(), Terraria.GameContent.SpelunkerProjectileHelper.OnPreUpdateAllProjectiles(), Terraria.WorldGen.OreRunner(), Terraria.WorldGen.PaintTheClouds(), Terraria.WorldGen.PaintTheDungeon(), Terraria.WorldGen.PaintTheLivingTrees(), Terraria.WorldGen.PaintThePurityGrass(), Terraria.WorldGen.PaintThePyramids(), Terraria.WorldGen.PaintTheTemple(), Terraria.GameContent.Generation.ShapeFloodFill.Perform(), Terraria.WorldGen.Place2x2(), Terraria.WorldGen.Place2x2Horizontal(), Terraria.WorldGen.Place2x2Style(), Terraria.WorldGen.Place3x1(), Terraria.WorldGen.Place3x2(), Terraria.WorldGen.Place3x4(), Terraria.WorldGen.Place4x2(), Terraria.WorldGen.Place5x4(), Terraria.WorldGen.Place6x3(), Terraria.WorldGen.PlaceCannon(), Terraria.WorldGen.PlaceCatTail(), Terraria.WorldGen.PlaceJunglePlant(), Terraria.WorldGen.PlaceLilyPad(), Terraria.WorldGen.PlaceMB(), Terraria.WorldGen.PlaceOasis(), Terraria.WorldGen.PlaceOasisPlant(), Terraria.WorldGen.PlacePot(), Terraria.WorldGen.PlacePumpkin(), Terraria.WorldGen.PlaceSign(), Terraria.WorldGen.PlaceTile(), Terraria.WorldGen.placeTrap(), Terraria.WorldGen.PlaceWall(), Terraria.WorldGen.PlantAlch(), Terraria.WorldGen.PlantCheck(), Terraria.WorldGen.plantDye(), Terraria.WorldGen.playWorldCallBack(), Terraria.Graphics.Capture.CaptureInterface.PointWorldClamp(), Terraria.Graphics.Light.LegacyLighting.PreRenderPhase(), Terraria.GameContent.UI.EmoteBubble.ProbeBiomes(), Terraria.GameContent.UI.EmoteBubble.ProbeWeather(), Terraria.WorldGen.QuickFindHome(), Terraria.Player.QuickMinecart(), Terraria.Player.QuickStackAllChests(), Terraria.WorldGen.RandomizeCaveBackgrounds(), Terraria.WorldGen.RandomizeTreeStyle(), Terraria.WorldGen.RandomWorldPoint(), Terraria.IO.WorldFile.SaveChests(), Terraria.IO.WorldFile.SaveWorldHeader(), Terraria.IO.WorldFile.SaveWorldTiles(), Terraria.WorldBuilding.WorldGenRange.ScaleValue(), Terraria.WorldGen.SeaOatWaterCheck(), Terraria.NetMessage.SendData(), Terraria.WorldGen.setMoss(), Terraria.Liquid.SettleWaterAt(), Terraria.Chest.SetupShop(), Terraria.WorldGen.ShimmeratorNext(), Terraria.WorldGen.ShimmerMakeBiomeOpening(), Terraria.WorldGen.ShroomPatch(), Terraria.NPC.SlimeRainSpawns(), Terraria.Collision.SlopeCollision(), Terraria.GameContent.SmartCursorHelper.SmartCursorLookup(), Terraria.Player.SmartInteractLookup_PrepareCommonlyUsedInfo(), Terraria.WorldGen.SmashAltar(), Terraria.WorldGen.smCallBack(), Terraria.WorldGen.SnowCloudIsland(), Terraria.Collision.SolidCollision(), Terraria.Collision.SolidCollision(), Terraria.Collision.SolidTiles(), Terraria.Collision.SolidTiles(), Terraria.WorldGen.SonOfLakinater(), Terraria.NPC.SpawnFaelings(), Terraria.NPC.SpawnNPC(), Terraria.NPC.SpawnOnPlayer(), Terraria.WorldGen.SpawnThingsFromPot(), Terraria.WorldGen.SpawnTownNPC(), Terraria.WorldGen.SpawnTravelNPC(), Terraria.Projectile.SpawnWebs(), Terraria.NPC.SpawnWOF(), Terraria.GameContent.Biomes.HiveBiome.SpotActuallyNotInHive(), Terraria.WorldGen.SpreadGrass(), Terraria.Main.StartInvasion(), Terraria.Collision.StickyTiles(), Terraria.Collision.SwitchTiles(), Terraria.Collision.SwitchTilesNew(), Terraria.WorldGen.templePart2(), Terraria.DelegateMethods.TestDust(), Terraria.Collision.TileCollision(), Terraria.WorldGen.tileCounterNext(), Terraria.WorldGen.TileFrame(), Terraria.WorldGen.TileRunner(), Terraria.GameContent.Biomes.HiveBiome.TooCloseToImportantLocations(), Terraria.Player.TorchAttack(), Terraria.WorldGen.TryGrowingAbigailsFlower(), Terraria.WorldGen.TryGrowingGlowTulip(), Terraria.Player.TryPlacingAGolfBallNearANearbyTee(), Terraria.Player.TryRecalculatingTorchLuck(), Terraria.Graphics.Light.LegacyLighting.TryUpdatingMapWithLight(), Terraria.Collision.TupleHitLine(), Terraria.Collision.TupleHitLineWall(), Terraria.GameContent.Skies.LanternSky.Update(), Terraria.GameContent.Skies.PartySky.Update(), Terraria.GameContent.Skies.SlimeSky.Update(), Terraria.GameContent.Skies.VortexSky.Update(), Terraria.Player.Update(), Terraria.Main.UpdateAtmosphereTransparencyToSkyColor(), Terraria.Main.UpdateAudio_DecideOnNewMusic(), Terraria.Main.UpdateAudio_DecideOnTOWMusic(), Terraria.Player.UpdateBiomes(), Terraria.Item.UpdateItem(), Terraria.Graphics.Light.LegacyLighting.UpdateLightToSkyColor(), Terraria.NPC.UpdateNPC_UpdateGravity(), Terraria.Main.UpdateTime(), Terraria.WorldGen.UpdateWorld(), Terraria.WorldGen.UpdateWorld_OvergroundTile(), Terraria.WorldGen.UpdateWorld_UndergroundTile(), Terraria.IO.WorldFile.ValidateWorld(), Terraria.Collision.WalkDownSlope(), Terraria.Framing.WallFrame(), Terraria.Collision.WaterCollision(), Terraria.Collision.WetCollision(), and Terraria.Player.WOFTongue().