Terraria: Terraria.Main.GetScreenOverdrawOffset
GetScreenOverdrawOffset()
static Microsoft.Xna.Framework.Point Terraria.Main.GetScreenOverdrawOffset () inline static
Definition at line 50910 of file Main.cs.
    {
        return (Camera.ScaledPosition - Camera.UnscaledPosition).ToTileCoordinates();
    }
References Terraria.Graphics.Camera.ScaledPosition, and Terraria.Graphics.Camera.UnscaledPosition.
Referenced by Terraria.Main.DrawBlack(), Terraria.GameContent.Drawing.WallDrawing.DrawWalls(), and Terraria.Main.DrawWires().