Terraria: Terraria.Main.DrawInterface_35_YouDied
DrawInterface_35_YouDied()
static void Terraria.Main.DrawInterface_35_YouDied () inline static private
Definition at line 42210 of file Main.cs.
    {
        if (player[myPlayer].dead)
        {
            float num = -60f;
            string value = Lang.inter[38].Value;
            DynamicSpriteFontExtensionMethods.DrawString(spriteBatch, FontAssets.DeathText.Value, value, new Vector2((float)(screenWidth / 2) - FontAssets.DeathText.Value.MeasureString(value).X / 2f, (float)(screenHeight / 2) + num), player[myPlayer].GetDeathAlpha(Microsoft.Xna.Framework.Color.Transparent), 0f, default(Vector2), 1f, SpriteEffects.None, 0f);
            if (player[myPlayer].lostCoins > 0)
            {
                num += 50f;
                string textValue = Language.GetTextValue("Game.DroppedCoins", player[myPlayer].lostCoinString);
                DynamicSpriteFontExtensionMethods.DrawString(spriteBatch, FontAssets.MouseText.Value, textValue, new Vector2((float)(screenWidth / 2) - FontAssets.MouseText.Value.MeasureString(textValue).X / 2f, (float)(screenHeight / 2) + num), player[myPlayer].GetDeathAlpha(Microsoft.Xna.Framework.Color.Transparent), 0f, default(Vector2), 1f, SpriteEffects.None, 0f);
            }
            num += (float)((player[myPlayer].lostCoins > 0) ? 24 : 50);
            num += 20f;
            float num2 = 0.7f;
            string textValue2 = Language.GetTextValue("Game.RespawnInSuffix", ((float)(int)(1f + (float)player[myPlayer].respawnTimer / 60f)).ToString());
            DynamicSpriteFontExtensionMethods.DrawString(spriteBatch, FontAssets.DeathText.Value, textValue2, new Vector2((float)(screenWidth / 2) - FontAssets.MouseText.Value.MeasureString(textValue2).X * num2 / 2f, (float)(screenHeight / 2) + num), player[myPlayer].GetDeathAlpha(Microsoft.Xna.Framework.Color.Transparent), 0f, default(Vector2), num2, SpriteEffects.None, 0f);
        }
    }
References Terraria.GameContent.FontAssets.DeathText, ReLogic.Graphics.DynamicSpriteFontExtensionMethods.DrawString(), Terraria.Localization.Language.GetTextValue(), Terraria.Lang.inter, Terraria.GameContent.FontAssets.MouseText, Terraria.Main.myPlayer, Terraria.Main.player, Terraria.Main.screenHeight, Terraria.Main.screenWidth, Terraria.Main.spriteBatch, Microsoft.Xna.Framework.Color.Transparent, and System.value.
Referenced by Terraria.Main.SetupDrawInterfaceLayers().