Terraria: Terraria.Main.DrawWhip_WhipScythe
DrawWhip_WhipScythe()
static Vector2 Terraria.Main.DrawWhip_WhipScythe (Projectile proj, List< Vector2 > controlPoints) inline static
Definition at line 33652 of file Main.cs.
    {
        SpriteEffects spriteEffects = SpriteEffects.None;
        if (proj.spriteDirection == 1)
        {
            spriteEffects ^= SpriteEffects.FlipHorizontally;
        }
        Texture2D value = TextureAssets.Projectile[proj.type].Value;
        Microsoft.Xna.Framework.Rectangle rectangle = value.Frame(1, 5);
        int height = rectangle.Height;
        rectangle.Height -= 2;
        Vector2 vector = rectangle.Size() / 2f;
        Vector2 vector2 = controlPoints[0];
        for (int i = 0; i < controlPoints.Count - 1; i++)
        {
            bool flag = false;
            Vector2 origin = vector;
            float scale = 1f;
            if (i == 0)
            {
                origin.Y -= 4f;
                flag = true;
            }
            else if (i % 2 == 0)
            {
                flag = true;
                int num = 1;
                if (i > 10)
                {
                    num = 2;
                }
                if (i > 20)
                {
                    num = 3;
                }
                rectangle.Y = height * num;
            }
            if (i == controlPoints.Count - 2)
            {
                flag = true;
                rectangle.Y = height * 4;
                scale = 1.3f;
                Projectile.GetWhipSettings(proj, out var timeToFlyOut, out var _, out var _);
                float t = proj.ai[0] / timeToFlyOut;
                float amount = Utils.GetLerpValue(0.1f, 0.7f, t, clamped: true) * Utils.GetLerpValue(0.9f, 0.7f, t, clamped: true);
                scale = MathHelper.Lerp(0.5f, 1.5f, amount);
            }
            Vector2 vector3 = controlPoints[i];
            Vector2 vector4 = controlPoints[i + 1] - vector3;
            if (flag)
            {
                float rotation = vector4.ToRotation() - (float)Math.PI / 2f;
                Microsoft.Xna.Framework.Color color = Lighting.GetColor(vector3.ToTileCoordinates());
                spriteBatch.Draw(value, vector2 - screenPosition, rectangle, color, rotation, origin, scale, spriteEffects, 0f);
            }
            vector2 += vector4;
        }
        return vector2;
    }
References Terraria.Lighting.GetColor(), Terraria.Utils.GetLerpValue(), Terraria.Projectile.GetWhipSettings(), Terraria.GameContent.TextureAssets.Projectile, Terraria.Main.screenPosition, Terraria.Main.spriteBatch, and ReLogic.Content.Asset< T >.Value.
Referenced by Terraria.Main.DrawWhip().