Terraria: Terraria.Main.LoadWorlds
LoadWorlds()
static void Terraria.Main.LoadWorlds () inline static
Definition at line 3642 of file Main.cs.
    {
        WorldList.Clear();
        if (!Utils.TryCreatingDirectory(WorldPath))
        {
            return;
        }
        string[] files = Directory.GetFiles(WorldPath, "*.wld");
        int num = Math.Min(files.Length, maxLoadWorld);
        if (dedServ)
        {
            for (int i = 0; i < num; i++)
            {
                WorldFileData allMetadata = WorldFile.GetAllMetadata(files[i], cloudSave: false);
                if (allMetadata != null)
                {
                    WorldList.Add(allMetadata);
                }
                else
                {
                    WorldList.Add(WorldFileData.FromInvalidWorld(files[i], cloudSave: false));
                }
            }
        }
        else
        {
            for (int j = 0; j < num; j++)
            {
                WorldFileData allMetadata2 = WorldFile.GetAllMetadata(files[j], cloudSave: false);
                if (allMetadata2 != null)
                {
                    WorldList.Add(allMetadata2);
                }
                else
                {
                    WorldList.Add(WorldFileData.FromInvalidWorld(files[j], cloudSave: false));
                }
            }
        }
        if (SocialAPI.Cloud != null)
        {
            foreach (string item in from path in SocialAPI.Cloud.GetFiles()
                where path.StartsWith(CloudWorldPath, StringComparison.CurrentCultureIgnoreCase) && path.EndsWith(".wld", StringComparison.CurrentCultureIgnoreCase)
                select path)
            {
                WorldFileData allMetadata3 = WorldFile.GetAllMetadata(item, cloudSave: true);
                if (allMetadata3 != null)
                {
                    WorldList.Add(allMetadata3);
                }
                else
                {
                    WorldList.Add(WorldFileData.FromInvalidWorld(item, cloudSave: true));
                }
            }
        }
        WorldList.Sort(WorldListSortMethod);
    }
References Terraria.Social.SocialAPI.Cloud, Terraria.Main.CloudWorldPath, Terraria.Main.dedServ, Terraria.IO.WorldFileData.FromInvalidWorld(), Terraria.IO.WorldFile.GetAllMetadata(), Terraria.Main.item, Terraria.Main.maxLoadWorld, Terraria.Utils.TryCreatingDirectory(), Terraria.Main.WorldList, Terraria.Main.WorldListSortMethod(), and Terraria.Main.WorldPath.
Referenced by Terraria.Main.DedServ(), Terraria.Main.EraseWorld(), Terraria.Main.Initialize_AlmostEverything(), Terraria.GameContent.UI.States.UIWorkshopWorldImport.OnActivate(), Terraria.GameContent.UI.States.UIWorldSelect.OnActivate(), Terraria.GameContent.UI.States.UIWorkshopSelectWorldToPublish.PopulateEntries(), Terraria.WorldGen.RenameWorldCallBack(), and Terraria.Main.SelectPlayer().