Terraria: Terraria.Main.RenderBackground
RenderBackground()
void Terraria.Main.RenderBackground () inline protected
Definition at line 52004 of file Main.cs.
    {
        if (drawToScreen)
        {
            return;
        }
        base.GraphicsDevice.SetRenderTarget(backWaterTarget);
        base.GraphicsDevice.Clear(Microsoft.Xna.Framework.Color.Transparent);
        spriteBatch.Begin();
        tileBatch.Begin();
        try
        {
            DrawWaters(isBackground: true);
        }
        catch
        {
        }
        tileBatch.End();
        spriteBatch.End();
        base.GraphicsDevice.SetRenderTarget(null);
        base.GraphicsDevice.SetRenderTarget(backgroundTarget);
        base.GraphicsDevice.Clear(Microsoft.Xna.Framework.Color.Transparent);
        spriteBatch.Begin();
        tileBatch.Begin();
        if (ignoreErrors)
        {
            try
            {
                DrawBackground();
            }
            catch (Exception e)
            {
                TimeLogger.DrawException(e);
            }
        }
        else
        {
            DrawBackground();
        }
        TimeLogger.DetailedDrawReset();
        tileBatch.End();
        spriteBatch.End();
        TimeLogger.DetailedDrawTime(33);
        base.GraphicsDevice.SetRenderTarget(null);
    }
References Terraria.Main.backgroundTarget, Terraria.Main.backWaterTarget, Terraria.TimeLogger.DetailedDrawReset(), Terraria.TimeLogger.DetailedDrawTime(), Terraria.Main.DrawBackground(), Terraria.TimeLogger.DrawException(), Terraria.Main.drawToScreen, Terraria.Main.DrawWaters(), Terraria.Main.ignoreErrors, Terraria.Main.spriteBatch, and Terraria.Main.tileBatch.
Referenced by Terraria.Main.DoDraw().