Terraria: Terraria.Main.DrawItemTextPopups
DrawItemTextPopups()
static void Terraria.Main.DrawItemTextPopups (float scaleTarget) inline static private
Definition at line 59201 of file Main.cs.
    {
        for (int i = 0; i < 20; i++)
        {
            PopupText popupText = Main.popupText[i];
            if (!popupText.active)
            {
                continue;
            }
            string text = popupText.name;
            if (popupText.stack > 1)
            {
                text = text + " (" + popupText.stack + ")";
            }
            Vector2 vector = FontAssets.MouseText.Value.MeasureString(text);
            Vector2 vector2 = new Vector2(vector.X * 0.5f, vector.Y * 0.5f);
            float num = popupText.scale / scaleTarget;
            int num2 = (int)(255f - 255f * num);
            float num3 = (int)popupText.color.R;
            float num4 = (int)popupText.color.G;
            float num5 = (int)popupText.color.B;
            float num6 = (int)popupText.color.A;
            num3 *= num * popupText.alpha * 0.3f;
            num5 *= num * popupText.alpha * 0.3f;
            num4 *= num * popupText.alpha * 0.3f;
            num6 *= num * popupText.alpha;
            Microsoft.Xna.Framework.Color color = new Microsoft.Xna.Framework.Color((int)num3, (int)num4, (int)num5, (int)num6);
            Microsoft.Xna.Framework.Color color2 = Microsoft.Xna.Framework.Color.Black;
            float num7 = 1f;
            Texture2D texture2D = null;
            switch (popupText.context)
            {
            case PopupTextContext.ItemPickupToVoidContainer:
                color2 = new Microsoft.Xna.Framework.Color(127, 20, 255) * 0.4f;
                num7 = 0.8f;
                break;
            case PopupTextContext.SonarAlert:
                color2 = Microsoft.Xna.Framework.Color.Blue * 0.4f;
                if (popupText.npcNetID != 0)
                {
                    color2 = Microsoft.Xna.Framework.Color.Red * 0.4f;
                }
                num7 = 1f;
                break;
            }
            float num8 = (float)num2 / 255f;
            for (int j = 0; j < 5; j++)
            {
                color = color2;
                float num9 = 0f;
                float num10 = 0f;
                switch (j)
                {
                case 0:
                    num9 -= scaleTarget * 2f;
                    break;
                case 1:
                    num9 += scaleTarget * 2f;
                    break;
                case 2:
                    num10 -= scaleTarget * 2f;
                    break;
                case 3:
                    num10 += scaleTarget * 2f;
                    break;
                default:
                    color = popupText.color * num * popupText.alpha * num7;
                    break;
                }
                if (j < 4)
                {
                    num6 = (float)(int)popupText.color.A * num * popupText.alpha;
                    color = new Microsoft.Xna.Framework.Color(0, 0, 0, (int)num6);
                }
                if (color2 != Microsoft.Xna.Framework.Color.Black && j < 4)
                {
                    num9 *= 1.3f + 1.3f * num8;
                    num10 *= 1.3f + 1.3f * num8;
                }
                float num11 = popupText.position.Y - screenPosition.Y + num10;
                if (player[myPlayer].gravDir == -1f)
                {
                    num11 = (float)screenHeight - num11;
                }
                if (color2 != Microsoft.Xna.Framework.Color.Black && j < 4)
                {
                    Microsoft.Xna.Framework.Color color3 = color2;
                    color3.A = (byte)MathHelper.Lerp(60f, 127f, Utils.GetLerpValue(0f, 255f, num6, clamped: true));
                    DynamicSpriteFontExtensionMethods.DrawString(spriteBatch, FontAssets.MouseText.Value, text, new Vector2(popupText.position.X - screenPosition.X + num9 + vector2.X, num11 + vector2.Y), Microsoft.Xna.Framework.Color.Lerp(color, color3, 0.5f), popupText.rotation, vector2, popupText.scale, SpriteEffects.None, 0f);
                    DynamicSpriteFontExtensionMethods.DrawString(spriteBatch, FontAssets.MouseText.Value, text, new Vector2(popupText.position.X - screenPosition.X + num9 + vector2.X, num11 + vector2.Y), color3, popupText.rotation, vector2, popupText.scale, SpriteEffects.None, 0f);
                }
                else
                {
                    DynamicSpriteFontExtensionMethods.DrawString(spriteBatch, FontAssets.MouseText.Value, text, new Vector2(popupText.position.X - screenPosition.X + num9 + vector2.X, num11 + vector2.Y), color, popupText.rotation, vector2, popupText.scale, SpriteEffects.None, 0f);
                }
                if (texture2D != null)
                {
                    float scale = (1.3f - num8) * popupText.scale * 0.7f;
                    Vector2 vector3 = new Vector2(popupText.position.X - screenPosition.X + num9 + vector2.X, num11 + vector2.Y);
                    Microsoft.Xna.Framework.Color color4 = color2 * 0.6f;
                    if (j == 4)
                    {
                        color4 = Microsoft.Xna.Framework.Color.White * 0.6f;
                    }
                    color4.A = (byte)((float)(int)color4.A * 0.5f);
                    int num12 = 25;
                    spriteBatch.Draw(texture2D, vector3 + new Vector2(vector2.X * -0.5f - (float)num12 - texture2D.Size().X / 2f, 0f), null, color4 * popupText.scale, 0f, texture2D.Size() / 2f, scale, SpriteEffects.None, 0f);
                    spriteBatch.Draw(texture2D, vector3 + new Vector2(vector2.X * 0.5f + (float)num12 + texture2D.Size().X / 2f, 0f), null, color4 * popupText.scale, 0f, texture2D.Size() / 2f, scale, SpriteEffects.None, 0f);
                }
            }
        }
    }
References Microsoft.Xna.Framework.Color.Black, ReLogic.Graphics.DynamicSpriteFontExtensionMethods.DrawString(), Terraria.Utils.GetLerpValue(), System.Text.RegularExpressions.i, Microsoft.Xna.Framework.Color.Lerp(), Microsoft.Xna.Framework.MathHelper.Lerp(), Terraria.GameContent.FontAssets.MouseText, Terraria.Main.myPlayer, Terraria.Main.player, Terraria.Main.popupText, Terraria.Main.screenHeight, Terraria.Main.screenPosition, Terraria.Main.spriteBatch, System.text, and Microsoft.Xna.Framework.Graphics.Vector2.
Referenced by Terraria.Main.DoDraw().