Terraria: Terraria.Main.DrawProjDirect
DrawProjDirect()
void Terraria.Main.DrawProjDirect (Projectile proj) inline
Definition at line 26150 of file Main.cs.
    {
        PrepareDrawnProjectileDrawing(proj);
        if (proj.type == 734)
        {
            VoidLensHelper voidLensHelper = new VoidLensHelper(proj);
            _voidLensData.Clear();
            int selectionMode = TryInteractingWithVoidLens(proj);
            voidLensHelper.DrawToDrawData(_voidLensData, selectionMode);
            {
                foreach (DrawData voidLensDatum in _voidLensData)
                {
                    EntitySpriteDraw(voidLensDatum);
                }
                return;
            }
        }
        float polePosX = 0f;
        float polePosY = 0f;
        LoadProjectile(proj.type);
        Vector2 mountedCenter = Main.player[proj.owner].MountedCenter;
        if (Main.player[proj.owner].mount.Active && Main.player[proj.owner].mount.Type == 52)
        {
            mountedCenter += new Vector2(Main.player[proj.owner].direction * 14, -10f);
        }
        if (proj.aiStyle == 99)
        {
            Vector2 vector = mountedCenter;
            vector.Y += Main.player[proj.owner].gfxOffY;
            float num = proj.Center.X - vector.X;
            float num2 = proj.Center.Y - vector.Y;
            Math.Sqrt(num * num + num2 * num2);
            float num3 = (float)Math.Atan2(num2, num) - 1.57f;
            if (!proj.counterweight)
            {
                int num4 = -1;
                if (proj.position.X + (float)(proj.width / 2) < Main.player[proj.owner].position.X + (float)(Main.player[proj.owner].width / 2))
                {
                    num4 = 1;
                }
                num4 *= -1;
                Main.player[proj.owner].itemRotation = (float)Math.Atan2(num2 * (float)num4, num * (float)num4);
            }
            bool flag = true;
            bool flag2 = true;
            if (num == 0f && num2 == 0f)
            {
                flag = false;
            }
            else
            {
                float num5 = (float)Math.Sqrt(num * num + num2 * num2);
                num5 = 12f / num5;
                num *= num5;
                num2 *= num5;
                vector.X -= num * 0.1f;
                vector.Y -= num2 * 0.1f;
                num = proj.position.X + (float)proj.width * 0.5f - vector.X;
                num2 = proj.position.Y + (float)proj.height * 0.5f - vector.Y;
            }
            while (flag)
            {
                float num6 = 12f;
                float num7 = (float)Math.Sqrt(num * num + num2 * num2);
                float num8 = num7;
                if (float.IsNaN(num7) || float.IsNaN(num8))
                {
                    flag = false;
                    continue;
                }
                if (num7 < 20f)
                {
                    num6 = num7 - 8f;
                    flag = false;
                }
                num7 = 12f / num7;
                num *= num7;
                num2 *= num7;
                if (flag2)
                {
                    flag2 = false;
                }
                else
                {
                    vector.X += num;
                    vector.Y += num2;
                }
                num = proj.position.X + (float)proj.width * 0.5f - vector.X;
                num2 = proj.position.Y + (float)proj.height * 0.1f - vector.Y;
                if (num8 > 12f)
                {
                    float num9 = 0.3f;
                    float num10 = Math.Abs(proj.velocity.X) + Math.Abs(proj.velocity.Y);
                    if (num10 > 16f)
                    {
                        num10 = 16f;
                    }
                    num10 = 1f - num10 / 16f;
                    num9 *= num10;
                    num10 = num8 / 80f;
                    if (num10 > 1f)
                    {
                        num10 = 1f;
                    }
                    num9 *= num10;
                    if (num9 < 0f)
                    {
                        num9 = 0f;
                    }
                    num9 *= num10;
                    num9 *= 0.5f;
                    if (num2 > 0f)
                    {
                        num2 *= 1f + num9;
                        num *= 1f - num9;
                    }
                    else
                    {
                        num10 = Math.Abs(proj.velocity.X) / 3f;
                        if (num10 > 1f)
{
                            num10 = 1f;
                        }
                        num10 -= 0.5f;
                        num9 *= num10;
                        if (num9 > 0f)
{
                            num9 *= 2f;
                        }
                        num2 *= 1f + num9;
                        num *= 1f - num9;
                    }
                }
                num3 = (float)Math.Atan2(num2, num) - 1.57f;
                Microsoft.Xna.Framework.Color white = Microsoft.Xna.Framework.Color.White;
                white.A = (byte)((float)(int)white.A * 0.4f);
                white = TryApplyingPlayerStringColor(Main.player[proj.owner].stringColor, white);
                float num11 = 0.5f;
                white = Lighting.GetColor((int)vector.X / 16, (int)(vector.Y / 16f), white);
                EntitySpriteDraw(color: new Microsoft.Xna.Framework.Color((byte)((float)(int)white.R * num11), (byte)((float)(int)white.G * num11), (byte)((float)(int)white.B * num11), (byte)((float)(int)white.A * num11)), texture: TextureAssets.FishingLine.Value, position: new Vector2(vector.X - screenPosition.X + (float)TextureAssets.FishingLine.Width() * 0.5f, vector.Y - screenPosition.Y + (float)TextureAssets.FishingLine.Height() * 0.5f) - new Vector2(6f, 0f), sourceRectangle: new Microsoft.Xna.Framework.Rectangle(0, 0, TextureAssets.FishingLine.Width(), (int)num6), rotation: num3, origin: new Vector2((float)TextureAssets.FishingLine.Width() * 0.5f, 0f), scale: 1f, effects: SpriteEffects.None);
            }
        }
        else
        {
            if (proj.aiStyle == 160)
            {
                DrawKite(proj);
                return;
            }
            if (proj.aiStyle == 165)
            {
                DrawWhip(proj);
                return;
            }
        }
        if (proj.type == 879 || proj.type == 877 || proj.type == 878)
        {
            proj.position.Y -= Main.player[proj.owner].gfxOffY;
        }
        if (proj.aiStyle == 174)
        {
            DrawMultisegmentPet(proj);
            return;
        }
        if (proj.type == 1020)
        {
            DrawContinuousTrail(proj);
        }
        bool flag3 = true;
        switch (proj.type)
        {
        default:
            flag3 = false;
            break;
        case 932:
            DrawProj_FairyQueenRangedItemShot(proj);
            break;
        case 919:
            DrawProj_FairyQueenLance(proj);
            break;
        case 974:
            DrawProj_LightsBane(proj);
            break;
        case 972:
            DrawProj_NightsEdge(proj);
            break;
        case 973:
            DrawProj_TrueNightsEdge(proj);
            break;
        case 982:
            DrawProj_Excalibur(proj);
            break;
        case 997:
            DrawProj_TheHorsemansBlade(proj);
            break;
        case 984:
            DrawProj_TerraBlade2(proj);
            break;
        case 985:
            DrawProj_TerraBlade2Shot(proj);
            break;
        case 983:
            DrawProj_TrueExcalibur(proj);
            break;
        case 995:
            _stardewAnimation.Draw(spriteBatch, (int)proj.ai[0], proj.Center - screenPosition);
            flag3 = false;
            break;
        }
        if (flag3)
        {
            return;
        }
        if (proj.type == 34)
        {
            default(FlameLashDrawer).Draw(proj);
        }
        if (proj.type == 16)
        {
            default(MagicMissileDrawer).Draw(proj);
        }
        if (proj.type == 106)
        {
            default(LightDiscDrawer).Draw(proj);
        }
        if (proj.type == 933)
        {
            default(FinalFractalHelper).Draw(proj);
        }
        if (proj.type == 79)
        {
            default(RainbowRodDrawer).Draw(proj);
        }
        if (proj.type == 946)
        {
            EmpressBladeDrawer empressBladeDrawer = default(EmpressBladeDrawer);
            float num12 = GlobalTimeWrappedHourly % 3f / 3f;
            Player player = Main.player[proj.owner];
            float num13 = MathHelper.Max(1f, player.maxMinions);
            float num14 = (float)proj.identity % num13 / num13 + num12;
            Microsoft.Xna.Framework.Color fairyQueenWeaponsColor = proj.GetFairyQueenWeaponsColor(0f, 0f, num14 % 1f);
            Microsoft.Xna.Framework.Color fairyQueenWeaponsColor2 = proj.GetFairyQueenWeaponsColor(0f, 0f, (num14 + 0.5f) % 1f);
            empressBladeDrawer.ColorStart = fairyQueenWeaponsColor;
            empressBladeDrawer.ColorEnd = fairyQueenWeaponsColor2;
            empressBladeDrawer.Draw(proj);
            DrawProj_EmpressBlade(proj, num14);
            return;
        }
        if (proj.type == 927)
        {
            DrawProj_PiercingStarlight(proj);
            return;
        }
        if (proj.type == 917)
        {
            DrawProj_CoolWhipMinion(proj);
            return;
        }
        if (proj.type == 923)
        {
            Vector2 position = proj.Center - screenPosition;
            Texture2D value = TextureAssets.Projectile[proj.type].Value;
            Microsoft.Xna.Framework.Rectangle rectangle = value.Frame(1, 2);
            Microsoft.Xna.Framework.Rectangle value2 = value.Frame(1, 2, 0, 1);
            Vector2 origin = rectangle.Size() * new Vector2(0.03f, 0.5f);
            float num15 = 180f;
            float num16 = proj.ai[0] / ((float)Math.PI * 2f) + proj.localAI[0] / num15;
            float num17 = Utils.GetLerpValue(0f, 30f, proj.localAI[0], clamped: true) * Utils.GetLerpValue(num15, num15 - 30f, proj.localAI[0], clamped: true);
            Microsoft.Xna.Framework.Color color2 = hslToRgb(num16 % 1f, 1f, 1f) * num17;
            float lerpValue = Utils.GetLerpValue(40f, 60f, proj.localAI[0], clamped: true);
            Vector2 vector2 = new Vector2(1f, MathHelper.Lerp(0.25f, 0.7f, lerpValue)) * proj.scale;
            Microsoft.Xna.Framework.Color value3 = hslToRgb((num16 + 0.3f) % 1f, 1f, MathHelper.Lerp(0.3f, 0.66f, lerpValue)) * num17;
            if (NPC.ShouldEmpressBeEnraged())
            {
                value3 = OurFavoriteColor * num17;
            }
            value3 = Microsoft.Xna.Framework.Color.Lerp(value3, Microsoft.Xna.Framework.Color.White, 0.1f);
            value3.A /= 2;
            spriteBatch.Draw(value, position, value2, value3, proj.rotation, origin, vector2 * 1.2f, SpriteEffects.None, 0f);
            Microsoft.Xna.Framework.Color value4 = hslToRgb((num16 + 0.15f) % 1f, 1f, MathHelper.Lerp(0.3f, 0.5f, lerpValue)) * num17;
            if (NPC.ShouldEmpressBeEnraged())
            {
                value4 = OurFavoriteColor * num17;
            }
            value4 = Microsoft.Xna.Framework.Color.Lerp(value4, Microsoft.Xna.Framework.Color.White, 0.1f);
            value4.A /= 2;
            spriteBatch.Draw(value, position, value2, value4, proj.rotation, origin, vector2 * 1.1f, SpriteEffects.None, 0f);
            spriteBatch.Draw(value, position, rectangle, color2 * 0.5f, proj.rotation, origin, vector2, SpriteEffects.None, 0f);
            spriteBatch.Draw(value, position, value2, color2 * lerpValue, proj.rotation, origin, vector2, SpriteEffects.None, 0f);
            return;
        }
        if (proj.type == 950)
        {
            Vector2 position2 = proj.Center - screenPosition;
            Texture2D value5 = TextureAssets.Projectile[proj.type].Value;
            Microsoft.Xna.Framework.Rectangle rectangle2 = value5.Frame();
            Vector2 origin2 = rectangle2.Size() * new Vector2(0.5f, 0.5f);
            Microsoft.Xna.Framework.Color color3 = new Microsoft.Xna.Framework.Color(255, 255, 255, 0) * proj.Opacity;
            float hue = ((proj.ai[2] == 1f) ? 0.96f : 0.92f);
            if (proj.ai[2] == 1f)
            {
                color3 = new Microsoft.Xna.Framework.Color(255, 0, 30, 180) * proj.Opacity;
            }
            Microsoft.Xna.Framework.Color color4 = hslToRgb(hue, 1f, 0.5f) * proj.Opacity;
            color4.A = 0;
            color3 *= 0.6f;
            color4 *= 0.6f;
            float scale = proj.scale;
            float num18 = proj.localAI[0];
            spriteBatch.Draw(value5, position2, rectangle2, color3, proj.rotation, origin2, num18, SpriteEffects.None, 0f);
            spriteBatch.Draw(value5, position2, rectangle2, color4, proj.rotation, origin2, num18 * 0.95f, SpriteEffects.None, 0f);
            spriteBatch.Draw(value5, position2, rectangle2, color3, proj.rotation, origin2, scale, SpriteEffects.None, 0f);
            spriteBatch.Draw(value5, position2, rectangle2, color4, proj.rotation, origin2, scale * 0.95f, SpriteEffects.None, 0f);
            return;
        }
        if (proj.type == 888)
        {
            DrawTwinsPet(proj);
            return;
        }
        if (proj.type == 874)
        {
            DrawMurderAurora(proj);
            return;
        }
        if (proj.type == 871)
        {
            Texture2D value6 = TextureAssets.Projectile[proj.type].Value;
            Microsoft.Xna.Framework.Rectangle rectangle3 = value6.Frame(1, 4);
            Vector2 origin3 = rectangle3.Size() / 2f;
            Microsoft.Xna.Framework.Color color5 = Microsoft.Xna.Framework.Color.White * proj.Opacity;
            SpriteEffects effects = SpriteEffects.None;
            color5.A /= 2;
            Microsoft.Xna.Framework.Color color6 = proj.AI_171_GetColor();
            color6.A /= 2;
            float num19 = proj.scale * 1.3f;
            float num20 = 1f;
            int num21 = proj.AI_172_GetPelletStormsCount();
            bool flag4 = false;
            float num22 = float.PositiveInfinity;
            for (int i = 0; i < num21; i++)
            {
                Projectile.HallowBossPelletStormInfo hallowBossPelletStormInfo = proj.AI_172_GetPelletStormInfo(i);
                for (int j = 0; j < hallowBossPelletStormInfo.BulletsInStorm; j++)
                {
                    float bulletProgress = hallowBossPelletStormInfo.GetBulletProgress(j);
                    if (bulletProgress < num22)
                    {
                        num22 = bulletProgress;
                    }
                    if (hallowBossPelletStormInfo.IsValid(j))
                    {
                        if (i == num21 - 1 && bulletProgress > 0f)
{
                            flag4 = true;
                        }
                        rectangle3 = value6.Frame(1, 4, 0, (int)((double)(j + i * 6) + timeForVisualEffects / 4.0) % 4);
                        float num23 = Utils.GetLerpValue(0f, 0.1f, bulletProgress, clamped: true) * Utils.GetLerpValue(1f, 0.8f, bulletProgress, clamped: true);
                        Vector2 bulletPosition = hallowBossPelletStormInfo.GetBulletPosition(j, proj.Center);
                        EntitySpriteDraw(value6, bulletPosition - screenPosition + new Vector2(0f, proj.gfxOffY), rectangle3, color6 * num23, proj.rotation, origin3, num19 * num20, effects);
                        EntitySpriteDraw(value6, bulletPosition - screenPosition + new Vector2(0f, proj.gfxOffY), rectangle3, color5 * num23, proj.rotation, origin3, proj.scale * num20, effects);
                    }
                }
            }
            if (!flag4 && num22 <= 1f)
            {
                EntitySpriteDraw(value6, proj.Center - screenPosition + new Vector2(0f, proj.gfxOffY), rectangle3, color6, proj.rotation, origin3, num19, effects);
                EntitySpriteDraw(value6, proj.Center - screenPosition + new Vector2(0f, proj.gfxOffY), rectangle3, color5, proj.rotation, origin3, proj.scale, effects);
            }
            return;
        }
        if (proj.bobber && Main.player[proj.owner].inventory[Main.player[proj.owner].selectedItem].holdStyle != 0)
        {
            DrawProj_FishingLine(proj, ref polePosX, ref polePosY, mountedCenter);
        }
        else if (proj.type == 32)
        {
            Vector2 vector3 = new Vector2(proj.position.X + (float)proj.width * 0.5f, proj.position.Y + (float)proj.height * 0.5f);
            float num24 = mountedCenter.X - vector3.X;
            float num25 = mountedCenter.Y - vector3.Y;
            float rotation = (float)Math.Atan2(num25, num24) - 1.57f;
            bool flag5 = true;
            if (num24 == 0f && num25 == 0f)
            {
                flag5 = false;
            }
            else
            {
                float num26 = (float)Math.Sqrt(num24 * num24 + num25 * num25);
                num26 = 8f / num26;
                num24 *= num26;
                num25 *= num26;
                vector3.X -= num24;
                vector3.Y -= num25;
                num24 = mountedCenter.X - vector3.X;
                num25 = mountedCenter.Y - vector3.Y;
            }
            while (flag5)
            {
                float num27 = (float)Math.Sqrt(num24 * num24 + num25 * num25);
                if (num27 < 28f)
                {
                    flag5 = false;
                    continue;
                }
                if (float.IsNaN(num27))
                {
                    flag5 = false;
                    continue;
                }
                num27 = 28f / num27;
                num24 *= num27;
                num25 *= num27;
                vector3.X += num24;
                vector3.Y += num25;
                num24 = mountedCenter.X - vector3.X;
                num25 = mountedCenter.Y - vector3.Y;
                Microsoft.Xna.Framework.Color color7 = Lighting.GetColor((int)vector3.X / 16, (int)(vector3.Y / 16f));
                EntitySpriteDraw(TextureAssets.Chain5.Value, new Vector2(vector3.X - screenPosition.X, vector3.Y - screenPosition.Y), new Microsoft.Xna.Framework.Rectangle(0, 0, TextureAssets.Chain5.Width(), TextureAssets.Chain5.Height()), color7, rotation, new Vector2((float)TextureAssets.Chain5.Width() * 0.5f, (float)TextureAssets.Chain5.Height() * 0.5f), 1f, SpriteEffects.None);
            }
        }
        else if (proj.type == 73)
        {
            Vector2 vector4 = new Vector2(proj.position.X + (float)proj.width * 0.5f, proj.position.Y + (float)proj.height * 0.5f);
            float num28 = mountedCenter.X - vector4.X;
            float num29 = mountedCenter.Y - vector4.Y;
            float rotation2 = (float)Math.Atan2(num29, num28) - 1.57f;
            bool flag6 = true;
            while (flag6)
            {
                float num30 = (float)Math.Sqrt(num28 * num28 + num29 * num29);
                if (num30 < 25f)
                {
                    flag6 = false;
                    continue;
                }
                if (float.IsNaN(num30))
                {
                    flag6 = false;
                    continue;
                }
                num30 = 12f / num30;
                num28 *= num30;
                num29 *= num30;
                vector4.X += num28;
                vector4.Y += num29;
                num28 = mountedCenter.X - vector4.X;
                num29 = mountedCenter.Y - vector4.Y;
                Microsoft.Xna.Framework.Color color8 = Lighting.GetColor((int)vector4.X / 16, (int)(vector4.Y / 16f));
                EntitySpriteDraw(TextureAssets.Chain8.Value, new Vector2(vector4.X - screenPosition.X, vector4.Y - screenPosition.Y), new Microsoft.Xna.Framework.Rectangle(0, 0, TextureAssets.Chain8.Width(), TextureAssets.Chain8.Height()), color8, rotation2, new Vector2((float)TextureAssets.Chain8.Width() * 0.5f, (float)TextureAssets.Chain8.Height() * 0.5f), 1f, SpriteEffects.None);
            }
        }
        else if (proj.type == 186)
        {
            Vector2 vector5 = new Vector2(proj.localAI[0], proj.localAI[1]);
            float num31 = Vector2.Distance(proj.Center, vector5) - proj.velocity.Length();
            float num32 = (float)TextureAssets.Chain17.Height() - num31;
            if (num31 > 0f && proj.ai[1] > 0f)
            {
                Microsoft.Xna.Framework.Color color9 = Lighting.GetColor((int)proj.position.X / 16, (int)proj.position.Y / 16);
                EntitySpriteDraw(TextureAssets.Chain17.Value, vector5 - screenPosition, new Microsoft.Xna.Framework.Rectangle(0, (int)num32, TextureAssets.Chain17.Width(), (int)num31), color9, proj.rotation, new Vector2(TextureAssets.Chain17.Width() / 2, 0f), 1f, SpriteEffects.None);
            }
        }
        else if (proj.type == 74)
        {
            Vector2 vector6 = new Vector2(proj.position.X + (float)proj.width * 0.5f, proj.position.Y + (float)proj.height * 0.5f);
            float num33 = mountedCenter.X - vector6.X;
            float num34 = mountedCenter.Y - vector6.Y;
            float rotation3 = (float)Math.Atan2(num34, num33) - 1.57f;
            bool flag7 = true;
            while (flag7)
            {
                float num35 = (float)Math.Sqrt(num33 * num33 + num34 * num34);
                if (num35 < 25f)
                {
                    flag7 = false;
                    continue;
                }
                if (float.IsNaN(num35))
                {
                    flag7 = false;
                    continue;
                }
                num35 = 12f / num35;
                num33 *= num35;
                num34 *= num35;
                vector6.X += num33;
                vector6.Y += num34;
                num33 = mountedCenter.X - vector6.X;
                num34 = mountedCenter.Y - vector6.Y;
                Microsoft.Xna.Framework.Color color10 = Lighting.GetColor((int)vector6.X / 16, (int)(vector6.Y / 16f));
                EntitySpriteDraw(TextureAssets.Chain9.Value, new Vector2(vector6.X - screenPosition.X, vector6.Y - screenPosition.Y), new Microsoft.Xna.Framework.Rectangle(0, 0, TextureAssets.Chain8.Width(), TextureAssets.Chain8.Height()), color10, rotation3, new Vector2((float)TextureAssets.Chain8.Width() * 0.5f, (float)TextureAssets.Chain8.Height() * 0.5f), 1f, SpriteEffects.None);
            }
        }
        else if (proj.type == 171)
        {
            Vector2 vector7 = new Vector2(proj.position.X + (float)proj.width * 0.5f, proj.position.Y + (float)proj.height * 0.5f);
            float num36 = 0f - proj.velocity.X;
            float num37 = 0f - proj.velocity.Y;
            float num38 = 1f;
            if (proj.ai[0] <= 17f)
            {
                num38 = proj.ai[0] / 17f;
            }
            int num39 = (int)(30f * num38);
            float num40 = 1f;
            if (proj.ai[0] <= 30f)
            {
                num40 = proj.ai[0] / 30f;
            }
            float num41 = 0.4f * num40;
            float num42 = num41;
            num37 += num42;
            Vector2[] array = new Vector2[num39];
            float[] array2 = new float[num39];
            for (int k = 0; k < num39; k++)
            {
                float num43 = (float)Math.Sqrt(num36 * num36 + num37 * num37);
                float num44 = 5.6f;
                if (Math.Abs(num36) + Math.Abs(num37) < 1f)
                {
                    num44 *= Math.Abs(num36) + Math.Abs(num37) / 1f;
                }
                num43 = num44 / num43;
                num36 *= num43;
                num37 *= num43;
                float num45 = (float)Math.Atan2(num37, num36) - 1.57f;
                array[k].X = vector7.X;
                array[k].Y = vector7.Y;
                array2[k] = num45;
                vector7.X += num36;
                vector7.Y += num37;
                num36 = 0f - proj.velocity.X;
                num37 = 0f - proj.velocity.Y;
                num42 += num41;
                num37 += num42;
            }
            for (int num46 = --num39; num46 >= 0; num46--)
            {
                vector7.X = array[num46].X;
                vector7.Y = array[num46].Y;
                float rotation4 = array2[num46];
                Microsoft.Xna.Framework.Color color11 = Lighting.GetColor((int)vector7.X / 16, (int)(vector7.Y / 16f));
                EntitySpriteDraw(TextureAssets.Chain16.Value, new Vector2(vector7.X - screenPosition.X, vector7.Y - screenPosition.Y), new Microsoft.Xna.Framework.Rectangle(0, 0, TextureAssets.Chain16.Width(), TextureAssets.Chain16.Height()), color11, rotation4, new Vector2((float)TextureAssets.Chain16.Width() * 0.5f, (float)TextureAssets.Chain16.Height() * 0.5f), 0.8f, SpriteEffects.None);
            }
        }
        else if (proj.type == 475)
        {
            Vector2 vector8 = new Vector2(proj.position.X + (float)proj.width * 0.5f, proj.position.Y + (float)proj.height * 0.5f);
            float num47 = 0f - proj.velocity.X;
            float num48 = 0f - proj.velocity.Y;
            float num49 = 1f;
            if (proj.ai[0] <= 17f)
            {
                num49 = proj.ai[0] / 17f;
            }
            int num50 = (int)(30f * num49);
            float num51 = 1f;
            if (proj.ai[0] <= 30f)
            {
                num51 = proj.ai[0] / 30f;
            }
            float num52 = 0.4f * num51;
            float num53 = num52;
            num48 += num53;
            Vector2[] array3 = new Vector2[num50];
            float[] array4 = new float[num50];
            for (int l = 0; l < num50; l++)
            {
                float num54 = (float)Math.Sqrt(num47 * num47 + num48 * num48);
                float num55 = 5.6f;
                if (Math.Abs(num47) + Math.Abs(num48) < 1f)
                {
                    num55 *= Math.Abs(num47) + Math.Abs(num48) / 1f;
                }
                num54 = num55 / num54;
                num47 *= num54;
                num48 *= num54;
                float num56 = (float)Math.Atan2(num48, num47) - 1.57f;
                array3[l].X = vector8.X;
                array3[l].Y = vector8.Y;
                array4[l] = num56;
                vector8.X += num47;
                vector8.Y += num48;
                num47 = 0f - proj.velocity.X;
                num48 = 0f - proj.velocity.Y;
                num53 += num52;
                num48 += num53;
            }
            int num57 = 0;
            for (int num58 = --num50; num58 >= 0; num58--)
            {
                vector8.X = array3[num58].X;
                vector8.Y = array3[num58].Y;
                float rotation5 = array4[num58];
                Microsoft.Xna.Framework.Color color12 = Lighting.GetColor((int)vector8.X / 16, (int)(vector8.Y / 16f));
                if (num57 % 2 == 0)
                {
                    EntitySpriteDraw(TextureAssets.Chain38.Value, new Vector2(vector8.X - screenPosition.X, vector8.Y - screenPosition.Y), new Microsoft.Xna.Framework.Rectangle(0, 0, TextureAssets.Chain38.Width(), TextureAssets.Chain38.Height()), color12, rotation5, new Vector2((float)TextureAssets.Chain38.Width() * 0.5f, (float)TextureAssets.Chain38.Height() * 0.5f), 0.8f, SpriteEffects.None);
                }
                else
                {
                    EntitySpriteDraw(TextureAssets.Chain39.Value, new Vector2(vector8.X - screenPosition.X, vector8.Y - screenPosition.Y), new Microsoft.Xna.Framework.Rectangle(0, 0, TextureAssets.Chain39.Width(), TextureAssets.Chain39.Height()), color12, rotation5, new Vector2((float)TextureAssets.Chain39.Width() * 0.5f, (float)TextureAssets.Chain39.Height() * 0.5f), 0.8f, SpriteEffects.None);
                }
                num57++;
            }
        }
        else if (proj.type == 505 || proj.type == 506)
        {
            Vector2 vector9 = new Vector2(proj.position.X + (float)proj.width * 0.5f, proj.position.Y + (float)proj.height * 0.5f);
            float num59 = 0f - proj.velocity.X;
            float num60 = 0f - proj.velocity.Y;
            float num61 = 1f;
            if (proj.ai[0] <= 17f)
            {
                num61 = proj.ai[0] / 17f;
            }
            int num62 = (int)(30f * num61);
            float num63 = 1f;
            if (proj.ai[0] <= 30f)
            {
                num63 = proj.ai[0] / 30f;
            }
            float num64 = 0.4f * num63;
            float num65 = num64;
            num60 += num65;
            Vector2[] array5 = new Vector2[num62];
            float[] array6 = new float[num62];
            for (int m = 0; m < num62; m++)
            {
                float num66 = (float)Math.Sqrt(num59 * num59 + num60 * num60);
                float num67 = 5.6f;
                if (Math.Abs(num59) + Math.Abs(num60) < 1f)
                {
                    num67 *= Math.Abs(num59) + Math.Abs(num60) / 1f;
                }
                num66 = num67 / num66;
                num59 *= num66;
                num60 *= num66;
                float num68 = (float)Math.Atan2(num60, num59) - 1.57f;
                array5[m].X = vector9.X;
                array5[m].Y = vector9.Y;
                array6[m] = num68;
                vector9.X += num59;
                vector9.Y += num60;
                num59 = 0f - proj.velocity.X;
                num60 = 0f - proj.velocity.Y;
                num65 += num64;
                num60 += num65;
            }
            int num69 = 0;
            for (int num70 = --num62; num70 >= 0; num70--)
            {
                vector9.X = array5[num70].X;
                vector9.Y = array5[num70].Y;
                float rotation6 = array6[num70];
                Microsoft.Xna.Framework.Color color13 = Lighting.GetColor((int)vector9.X / 16, (int)(vector9.Y / 16f));
                int num71 = 4;
                if (proj.type == 506)
                {
                    num71 = 6;
                }
                num71 += num69 % 2;
                EntitySpriteDraw(TextureAssets.Chains[num71].Value, new Vector2(vector9.X - screenPosition.X, vector9.Y - screenPosition.Y), new Microsoft.Xna.Framework.Rectangle(0, 0, TextureAssets.Chains[num71].Width(), TextureAssets.Chains[num71].Height()), color13, rotation6, new Vector2((float)TextureAssets.Chains[num71].Width() * 0.5f, (float)TextureAssets.Chains[num71].Height() * 0.5f), 0.8f, SpriteEffects.None);
                num69++;
            }
        }
        else if (proj.type == 165)
        {
            Vector2 vector10 = new Vector2(proj.position.X + (float)proj.width * 0.5f, proj.position.Y + (float)proj.height * 0.5f);
            float num72 = mountedCenter.X - vector10.X;
            float num73 = mountedCenter.Y - vector10.Y;
            float rotation7 = (float)Math.Atan2(num73, num72) - 1.57f;
            bool flag8 = true;
            while (flag8)
            {
                float num74 = (float)Math.Sqrt(num72 * num72 + num73 * num73);
                if (num74 < 25f)
                {
                    flag8 = false;
                    continue;
                }
                if (float.IsNaN(num74))
                {
                    flag8 = false;
                    continue;
                }
                num74 = 24f / num74;
                num72 *= num74;
                num73 *= num74;
                vector10.X += num72;
                vector10.Y += num73;
                num72 = mountedCenter.X - vector10.X;
                num73 = mountedCenter.Y - vector10.Y;
                Microsoft.Xna.Framework.Color color14 = Lighting.GetColor((int)vector10.X / 16, (int)(vector10.Y / 16f));
                EntitySpriteDraw(TextureAssets.Chain15.Value, new Vector2(vector10.X - screenPosition.X, vector10.Y - screenPosition.Y), new Microsoft.Xna.Framework.Rectangle(0, 0, TextureAssets.Chain15.Width(), TextureAssets.Chain15.Height()), color14, rotation7, new Vector2((float)TextureAssets.Chain15.Width() * 0.5f, (float)TextureAssets.Chain15.Height() * 0.5f), 1f, SpriteEffects.None);
            }
        }
        else if (proj.type >= 230 && proj.type <= 235)
        {
            int num75 = proj.type - 229;
            Vector2 vector11 = new Vector2(proj.position.X + (float)proj.width * 0.5f, proj.position.Y + (float)proj.height * 0.5f);
            float num76 = mountedCenter.X - vector11.X;
            float num77 = mountedCenter.Y - vector11.Y;
            float rotation8 = (float)Math.Atan2(num77, num76) - 1.57f;
            bool flag9 = true;
            while (flag9)
            {
                float num78 = (float)Math.Sqrt(num76 * num76 + num77 * num77);
                if (num78 < 25f)
                {
                    flag9 = false;
                    continue;
                }
                if (float.IsNaN(num78))
                {
                    flag9 = false;
                    continue;
                }
                num78 = (float)TextureAssets.GemChain[num75].Height() / num78;
                num76 *= num78;
                num77 *= num78;
                vector11.X += num76;
                vector11.Y += num77;
                num76 = mountedCenter.X - vector11.X;
                num77 = mountedCenter.Y - vector11.Y;
                Microsoft.Xna.Framework.Color color15 = Lighting.GetColor((int)vector11.X / 16, (int)(vector11.Y / 16f));
                EntitySpriteDraw(TextureAssets.GemChain[num75].Value, new Vector2(vector11.X - screenPosition.X, vector11.Y - screenPosition.Y), new Microsoft.Xna.Framework.Rectangle(0, 0, TextureAssets.GemChain[num75].Width(), TextureAssets.GemChain[num75].Height()), color15, rotation8, new Vector2((float)TextureAssets.GemChain[num75].Width() * 0.5f, (float)TextureAssets.GemChain[num75].Height() * 0.5f), 1f, SpriteEffects.None);
            }
        }
        else if (proj.type == 753)
        {
            Vector2 vector12 = new Vector2(proj.position.X + (float)proj.width * 0.5f, proj.position.Y + (float)proj.height * 0.5f);
            float num79 = mountedCenter.X - vector12.X;
            float num80 = mountedCenter.Y - vector12.Y;
            float rotation9 = (float)Math.Atan2(num80, num79) - 1.57f;
            bool flag10 = true;
            Texture2D value7 = TextureAssets.Extra[95].Value;
            while (flag10)
            {
                float num81 = (float)Math.Sqrt(num79 * num79 + num80 * num80);
                if (num81 < 25f)
                {
                    flag10 = false;
                    continue;
                }
                if (float.IsNaN(num81))
                {
                    flag10 = false;
                    continue;
                }
                num81 = (float)value7.Height / num81;
                num79 *= num81;
                num80 *= num81;
                vector12.X += num79;
                vector12.Y += num80;
                num79 = mountedCenter.X - vector12.X;
                num80 = mountedCenter.Y - vector12.Y;
                Microsoft.Xna.Framework.Color color16 = Lighting.GetColor((int)vector12.X / 16, (int)(vector12.Y / 16f));
                EntitySpriteDraw(value7, new Vector2(vector12.X - screenPosition.X, vector12.Y - screenPosition.Y), null, color16, rotation9, value7.Size() / 2f, 1f, SpriteEffects.None);
            }
        }
        else if (proj.type == 865)
        {
            Vector2 vector13 = new Vector2(proj.position.X + (float)proj.width * 0.5f, proj.position.Y + (float)proj.height * 0.5f);
            float num82 = mountedCenter.X - vector13.X;
            float num83 = mountedCenter.Y - vector13.Y;
            float rotation10 = (float)Math.Atan2(num83, num82) - 1.57f;
            bool flag11 = true;
            bool flag12 = true;
            Texture2D value8 = TextureAssets.Extra[154].Value;
            while (flag11)
            {
                float num84 = (float)Math.Sqrt(num82 * num82 + num83 * num83);
                if (num84 < 25f)
                {
                    flag11 = false;
                    continue;
                }
                if (float.IsNaN(num84))
                {
                    flag11 = false;
                    continue;
                }
                num84 = (float)value8.Height / num84;
                num82 *= num84;
                num83 *= num84;
                vector13.X += num82;
                vector13.Y += num83;
                num82 = mountedCenter.X - vector13.X;
                num83 = mountedCenter.Y - vector13.Y;
                if (!flag12)
                {
                    Microsoft.Xna.Framework.Color color17 = Lighting.GetColor((int)vector13.X / 16, (int)(vector13.Y / 16f));
                    EntitySpriteDraw(value8, new Vector2(vector13.X - screenPosition.X, vector13.Y - screenPosition.Y), null, color17, rotation10, value8.Size() / 2f, 1f, SpriteEffects.None);
                }
                flag12 = false;
            }
        }
        else if (proj.type == 935)
        {
            Vector2 vector14 = new Vector2(proj.position.X + (float)proj.width * 0.5f, proj.position.Y + (float)proj.height * 0.5f);
            float num85 = mountedCenter.X - vector14.X;
            float num86 = mountedCenter.Y - vector14.Y;
            float rotation11 = (float)Math.Atan2(num86, num85) - 1.57f;
            bool flag13 = true;
            bool flag14 = true;
            Texture2D value9 = TextureAssets.Extra[208].Value;
            while (flag13)
            {
                float num87 = (float)Math.Sqrt(num85 * num85 + num86 * num86);
                if (num87 < 8f)
                {
                    flag13 = false;
                    continue;
                }
                if (float.IsNaN(num87))
                {
                    flag13 = false;
                    continue;
                }
                num87 = (float)value9.Height / num87;
                num85 *= num87;
                num86 *= num87;
                vector14.X += num85;
                vector14.Y += num86;
                num85 = mountedCenter.X - vector14.X;
                num86 = mountedCenter.Y - vector14.Y;
                if (!flag14)
                {
                    Microsoft.Xna.Framework.Color color18 = Lighting.GetColor((int)vector14.X / 16, (int)(vector14.Y / 16f));
                    EntitySpriteDraw(value9, new Vector2(vector14.X - screenPosition.X, vector14.Y - screenPosition.Y), null, color18, rotation11, value9.Size() / 2f, 1f, SpriteEffects.None);
                }
                flag14 = false;
            }
        }
        else if (proj.type == 256)
        {
            Vector2 vector15 = new Vector2(proj.position.X + (float)proj.width * 0.5f, proj.position.Y + (float)proj.height * 0.5f);
            float num88 = mountedCenter.X - vector15.X;
            float num89 = mountedCenter.Y - vector15.Y;
            float num90 = (float)Math.Atan2(num89, num88) - 1.57f;
            bool flag15 = true;
            while (flag15)
            {
                float num91 = (float)Math.Sqrt(num88 * num88 + num89 * num89);
                if (num91 < 26f)
                {
                    flag15 = false;
                    continue;
                }
                if (float.IsNaN(num91))
                {
                    flag15 = false;
                    continue;
                }
                num91 = 26f / num91;
                num88 *= num91;
                num89 *= num91;
                vector15.X += num88;
                vector15.Y += num89;
                num88 = Main.player[proj.owner].position.X + (float)(Main.player[proj.owner].width / 2) - vector15.X;
                num89 = Main.player[proj.owner].position.Y + (float)(Main.player[proj.owner].height / 2) - vector15.Y;
                Microsoft.Xna.Framework.Color color19 = Lighting.GetColor((int)vector15.X / 16, (int)(vector15.Y / 16f));
                EntitySpriteDraw(TextureAssets.Chain20.Value, new Vector2(vector15.X - screenPosition.X, vector15.Y - screenPosition.Y), new Microsoft.Xna.Framework.Rectangle(0, 0, TextureAssets.Chain20.Width(), TextureAssets.Chain20.Height()), color19, num90 - 0.785f, new Vector2((float)TextureAssets.Chain20.Width() * 0.5f, (float)TextureAssets.Chain20.Height() * 0.5f), 1f, SpriteEffects.None);
            }
        }
        else if (proj.type == 322)
        {
            Vector2 vector16 = new Vector2(proj.position.X + (float)proj.width * 0.5f, proj.position.Y + (float)proj.height * 0.5f);
            float num92 = mountedCenter.X - vector16.X;
            float num93 = mountedCenter.Y - vector16.Y;
            float rotation12 = (float)Math.Atan2(num93, num92) - 1.57f;
            bool flag16 = true;
            while (flag16)
            {
                float num94 = (float)Math.Sqrt(num92 * num92 + num93 * num93);
                if (num94 < 22f)
                {
                    flag16 = false;
                    continue;
                }
                if (float.IsNaN(num94))
                {
                    flag16 = false;
                    continue;
                }
                num94 = 22f / num94;
                num92 *= num94;
                num93 *= num94;
                vector16.X += num92;
                vector16.Y += num93;
                num92 = mountedCenter.X - vector16.X;
                num93 = mountedCenter.Y - vector16.Y;
                Microsoft.Xna.Framework.Color color20 = Lighting.GetColor((int)vector16.X / 16, (int)(vector16.Y / 16f));
                EntitySpriteDraw(TextureAssets.Chain29.Value, new Vector2(vector16.X - screenPosition.X, vector16.Y - screenPosition.Y), new Microsoft.Xna.Framework.Rectangle(0, 0, TextureAssets.Chain29.Width(), TextureAssets.Chain29.Height()), color20, rotation12, new Vector2((float)TextureAssets.Chain29.Width() * 0.5f, (float)TextureAssets.Chain29.Height() * 0.5f), 1f, SpriteEffects.None);
            }
        }
        else if (proj.type == 315)
        {
            Vector2 vector17 = new Vector2(proj.position.X + (float)proj.width * 0.5f, proj.position.Y + (float)proj.height * 0.5f);
            float num95 = mountedCenter.X - vector17.X;
            float num96 = mountedCenter.Y - vector17.Y;
            float rotation13 = (float)Math.Atan2(num96, num95) - 1.57f;
            bool flag17 = true;
            while (flag17)
            {
                float num97 = (float)Math.Sqrt(num95 * num95 + num96 * num96);
                if (num97 < 50f)
                {
                    flag17 = false;
                    continue;
                }
                if (float.IsNaN(num97))
                {
                    flag17 = false;
                    continue;
                }
                num97 = 40f / num97;
                num95 *= num97;
                num96 *= num97;
                vector17.X += num95;
                vector17.Y += num96;
                num95 = mountedCenter.X - vector17.X;
                num96 = mountedCenter.Y - vector17.Y;
                Microsoft.Xna.Framework.Color color21 = Lighting.GetColor((int)vector17.X / 16, (int)(vector17.Y / 16f));
                EntitySpriteDraw(TextureAssets.Chain28.Value, new Vector2(vector17.X - screenPosition.X, vector17.Y - screenPosition.Y), new Microsoft.Xna.Framework.Rectangle(0, 0, TextureAssets.Chain28.Width(), TextureAssets.Chain28.Height()), color21, rotation13, new Vector2((float)TextureAssets.Chain28.Width() * 0.5f, (float)TextureAssets.Chain28.Height() * 0.5f), 1f, SpriteEffects.None);
            }
        }
        else if (proj.type == 331)
        {
            Vector2 vector18 = new Vector2(proj.position.X + (float)proj.width * 0.5f, proj.position.Y + (float)proj.height * 0.5f);
            float num98 = mountedCenter.X - vector18.X;
            float num99 = mountedCenter.Y - vector18.Y;
            float rotation14 = (float)Math.Atan2(num99, num98) - 1.57f;
            bool flag18 = true;
            while (flag18)
            {
                float num100 = (float)Math.Sqrt(num98 * num98 + num99 * num99);
                if (num100 < 30f)
                {
                    flag18 = false;
                    continue;
                }
                if (float.IsNaN(num100))
                {
                    flag18 = false;
                    continue;
                }
                num100 = 24f / num100;
                num98 *= num100;
                num99 *= num100;
                vector18.X += num98;
                vector18.Y += num99;
                num98 = mountedCenter.X - vector18.X;
                num99 = mountedCenter.Y - vector18.Y;
                Microsoft.Xna.Framework.Color color22 = Lighting.GetColor((int)vector18.X / 16, (int)(vector18.Y / 16f));
                EntitySpriteDraw(TextureAssets.Chain30.Value, new Vector2(vector18.X - screenPosition.X, vector18.Y - screenPosition.Y), new Microsoft.Xna.Framework.Rectangle(0, 0, TextureAssets.Chain30.Width(), TextureAssets.Chain30.Height()), color22, rotation14, new Vector2((float)TextureAssets.Chain30.Width() * 0.5f, (float)TextureAssets.Chain30.Height() * 0.5f), 1f, SpriteEffects.None);
            }
        }
        else if (proj.type == 332)
        {
            int num101 = 0;
            Vector2 vector19 = new Vector2(proj.position.X + (float)proj.width * 0.5f, proj.position.Y + (float)proj.height * 0.5f);
            float num102 = mountedCenter.X - vector19.X;
            float num103 = mountedCenter.Y - vector19.Y;
            float rotation15 = (float)Math.Atan2(num103, num102) - 1.57f;
            bool flag19 = true;
            while (flag19)
            {
                float num104 = (float)Math.Sqrt(num102 * num102 + num103 * num103);
                if (num104 < 30f)
                {
                    flag19 = false;
                    continue;
                }
                if (float.IsNaN(num104))
                {
                    flag19 = false;
                    continue;
                }
                int i2 = (int)vector19.X / 16;
                int j2 = (int)vector19.Y / 16;
                if (num101 == 0)
                {
                    Lighting.AddLight(i2, j2, 0f, 0.2f, 0.2f);
                }
                if (num101 == 1)
                {
                    Lighting.AddLight(i2, j2, 0.1f, 0.2f, 0f);
                }
                if (num101 == 2)
                {
                    Lighting.AddLight(i2, j2, 0.2f, 0.1f, 0f);
                }
                if (num101 == 3)
                {
                    Lighting.AddLight(i2, j2, 0.2f, 0f, 0.2f);
                }
                num104 = 16f / num104;
                num102 *= num104;
                num103 *= num104;
                vector19.X += num102;
                vector19.Y += num103;
                num102 = mountedCenter.X - vector19.X;
                num103 = mountedCenter.Y - vector19.Y;
                Microsoft.Xna.Framework.Color color23 = Lighting.GetColor((int)vector19.X / 16, (int)(vector19.Y / 16f));
                EntitySpriteDraw(TextureAssets.Chain31.Value, new Vector2(vector19.X - screenPosition.X, vector19.Y - screenPosition.Y), new Microsoft.Xna.Framework.Rectangle(0, TextureAssets.Chain31.Height() / 4 * num101, TextureAssets.Chain31.Width(), TextureAssets.Chain31.Height() / 4), color23, rotation15, new Vector2((float)TextureAssets.Chain30.Width() * 0.5f, TextureAssets.Chain30.Height() / 8), 1f, SpriteEffects.None);
                EntitySpriteDraw(TextureAssets.Chain32.Value, new Vector2(vector19.X - screenPosition.X, vector19.Y - screenPosition.Y), new Microsoft.Xna.Framework.Rectangle(0, TextureAssets.Chain31.Height() / 4 * num101, TextureAssets.Chain31.Width(), TextureAssets.Chain31.Height() / 4), new Microsoft.Xna.Framework.Color(200, 200, 200, 0), rotation15, new Vector2((float)TextureAssets.Chain30.Width() * 0.5f, TextureAssets.Chain30.Height() / 8), 1f, SpriteEffects.None);
                num101++;
                if (num101 > 3)
                {
                    num101 = 0;
                }
            }
        }
        else if (proj.type == 372 || proj.type == 383 || proj.type == 396 || proj.type == 403 || proj.type == 404 || proj.type == 446 || (proj.type >= 486 && proj.type <= 489) || (proj.type >= 646 && proj.type <= 649) || proj.type == 652)
        {
            Texture2D texture2D = null;
            Microsoft.Xna.Framework.Color color24 = Microsoft.Xna.Framework.Color.Transparent;
            Texture2D value10 = TextureAssets.Chain33.Value;
            if (proj.type == 383)
            {
                value10 = TextureAssets.Chain34.Value;
            }
            if (proj.type == 396)
            {
                value10 = TextureAssets.Chain35.Value;
            }
            if (proj.type == 403)
            {
                value10 = TextureAssets.Chain36.Value;
            }
            if (proj.type == 404)
            {
                value10 = TextureAssets.Chain37.Value;
            }
            if (proj.type == 446)
            {
                value10 = TextureAssets.Extra[3].Value;
            }
            if (proj.type >= 486 && proj.type <= 489)
            {
                value10 = TextureAssets.Chains[proj.type - 486].Value;
            }
            if (proj.type >= 646 && proj.type <= 649)
            {
                value10 = TextureAssets.Chains[proj.type - 646 + 8].Value;
                texture2D = TextureAssets.Chains[proj.type - 646 + 12].Value;
                color24 = new Microsoft.Xna.Framework.Color(255, 255, 255, 127);
            }
            if (proj.type == 652)
            {
                value10 = TextureAssets.Chains[16].Value;
            }
            Vector2 center = proj.Center;
            Microsoft.Xna.Framework.Rectangle? sourceRectangle = null;
            Vector2 origin4 = new Vector2((float)value10.Width * 0.5f, (float)value10.Height * 0.5f);
            float num105 = value10.Height;
            float num106 = 0f;
            if (proj.type == 446)
            {
                int num107 = 7;
                int num108 = (int)proj.localAI[0] / num107;
                sourceRectangle = new Microsoft.Xna.Framework.Rectangle(0, value10.Height / 4 * num108, value10.Width, value10.Height / 4);
                origin4.Y /= 4f;
                num105 /= 4f;
            }
            switch (proj.type)
            {
            case 383:
                num106 = 14f;
                break;
            case 446:
                num106 = 20f;
                break;
            case 489:
                num106 = 10f;
                break;
            case 487:
                num106 = 8f;
                break;
            }
            if (num106 != 0f)
            {
                float num109 = -1.57f;
                Vector2 vector20 = new Vector2((float)Math.Cos(proj.rotation + num109), (float)Math.Sin(proj.rotation + num109));
                center -= vector20 * num106;
                vector20 = mountedCenter - center;
                vector20.Normalize();
                center -= vector20 * num105 / 2f;
            }
            Vector2 vector21 = mountedCenter - center;
            float rotation16 = (float)Math.Atan2(vector21.Y, vector21.X) - 1.57f;
            bool flag20 = true;
            if (float.IsNaN(center.X) && float.IsNaN(center.Y))
            {
                flag20 = false;
            }
            if (float.IsNaN(vector21.X) && float.IsNaN(vector21.Y))
            {
                flag20 = false;
            }
            while (flag20)
            {
                if (vector21.Length() < num105 + 1f)
                {
                    flag20 = false;
                    continue;
                }
                Vector2 vector22 = vector21;
                vector22.Normalize();
                center += vector22 * num105;
                vector21 = mountedCenter - center;
                Microsoft.Xna.Framework.Color color25 = Lighting.GetColor((int)center.X / 16, (int)(center.Y / 16f));
                if (proj.type == 396)
                {
                    color25 *= (float)(255 - proj.alpha) / 255f;
                }
                if (proj.type == 446)
                {
                    color25 = proj.GetAlpha(color25);
                }
                if (proj.type == 488)
                {
                    Lighting.AddLight(center, 0.2f, 0f, 0.175f);
                    color25 = new Microsoft.Xna.Framework.Color(255, 255, 255, 255);
                }
                if (proj.type >= 646 && proj.type <= 649)
                {
                    color25 = proj.GetAlpha(color25);
                }
                EntitySpriteDraw(value10, center - screenPosition, sourceRectangle, color25, rotation16, origin4, 1f, SpriteEffects.None);
                if (texture2D != null)
                {
                    EntitySpriteDraw(texture2D, center - screenPosition, sourceRectangle, color24, rotation16, origin4, 1f, SpriteEffects.None);
                }
            }
        }
        else if (proj.aiStyle == 7)
        {
            Vector2 vector23 = new Vector2(proj.position.X + (float)proj.width * 0.5f, proj.position.Y + (float)proj.height * 0.5f);
            float num110 = mountedCenter.X - vector23.X;
            float num111 = mountedCenter.Y - vector23.Y;
            float rotation17 = (float)Math.Atan2(num111, num110) - 1.57f;
            bool flag21 = true;
            while (flag21)
            {
                float num112 = (float)Math.Sqrt(num110 * num110 + num111 * num111);
                if (num112 < 25f)
                {
                    flag21 = false;
                    continue;
                }
                if (float.IsNaN(num112))
                {
                    flag21 = false;
                    continue;
                }
                num112 = 12f / num112;
                num110 *= num112;
                num111 *= num112;
                vector23.X += num110;
                vector23.Y += num111;
                num110 = mountedCenter.X - vector23.X;
                num111 = mountedCenter.Y - vector23.Y;
                Microsoft.Xna.Framework.Color color26 = Lighting.GetColor((int)vector23.X / 16, (int)(vector23.Y / 16f));
                EntitySpriteDraw(TextureAssets.Chain.Value, new Vector2(vector23.X - screenPosition.X, vector23.Y - screenPosition.Y), new Microsoft.Xna.Framework.Rectangle(0, 0, TextureAssets.Chain.Width(), TextureAssets.Chain.Height()), color26, rotation17, new Vector2((float)TextureAssets.Chain.Width() * 0.5f, (float)TextureAssets.Chain.Height() * 0.5f), 1f, SpriteEffects.None);
            }
        }
        else if (proj.type == 262)
        {
            float x = proj.Center.X;
            float y = proj.Center.Y;
            float x2 = proj.velocity.X;
            float y2 = proj.velocity.Y;
            float num113 = (float)Math.Sqrt(x2 * x2 + y2 * y2);
            num113 = 4f / num113;
            if (proj.ai[0] == 0f)
            {
                x -= proj.velocity.X * num113;
                y -= proj.velocity.Y * num113;
            }
            else
            {
                x += proj.velocity.X * num113;
                y += proj.velocity.Y * num113;
            }
            Vector2 vector24 = new Vector2(x, y);
            x2 = mountedCenter.X - vector24.X;
            y2 = mountedCenter.Y - vector24.Y;
            float rotation18 = (float)Math.Atan2(y2, x2) - 1.57f;
            if (proj.alpha == 0)
            {
                int num114 = -1;
                if (proj.position.X + (float)(proj.width / 2) < mountedCenter.X)
                {
                    num114 = 1;
                }
                if (Main.player[proj.owner].direction == 1)
                {
                    Main.player[proj.owner].itemRotation = (float)Math.Atan2(y2 * (float)num114, x2 * (float)num114);
                }
                else
                {
                    Main.player[proj.owner].itemRotation = (float)Math.Atan2(y2 * (float)num114, x2 * (float)num114);
                }
            }
            bool flag22 = true;
            while (flag22)
            {
                float num115 = (float)Math.Sqrt(x2 * x2 + y2 * y2);
                if (num115 < 25f)
                {
                    flag22 = false;
                    continue;
                }
                if (float.IsNaN(num115))
                {
                    flag22 = false;
                    continue;
                }
                num115 = 12f / num115;
                x2 *= num115;
                y2 *= num115;
                vector24.X += x2;
                vector24.Y += y2;
                x2 = mountedCenter.X - vector24.X;
                y2 = mountedCenter.Y - vector24.Y;
                Microsoft.Xna.Framework.Color color27 = Lighting.GetColor((int)vector24.X / 16, (int)(vector24.Y / 16f));
                EntitySpriteDraw(TextureAssets.Chain22.Value, new Vector2(vector24.X - screenPosition.X, vector24.Y - screenPosition.Y), new Microsoft.Xna.Framework.Rectangle(0, 0, TextureAssets.Chain22.Width(), TextureAssets.Chain22.Height()), color27, rotation18, new Vector2((float)TextureAssets.Chain22.Width() * 0.5f, (float)TextureAssets.Chain22.Height() * 0.5f), 1f, SpriteEffects.None);
            }
        }
        else if (proj.type == 273)
        {
            float x3 = proj.Center.X;
            float y3 = proj.Center.Y;
            float x4 = proj.velocity.X;
            float y4 = proj.velocity.Y;
            float num116 = (float)Math.Sqrt(x4 * x4 + y4 * y4);
            num116 = 4f / num116;
            if (proj.ai[0] == 0f)
            {
                x3 -= proj.velocity.X * num116;
                y3 -= proj.velocity.Y * num116;
            }
            else
            {
                x3 += proj.velocity.X * num116;
                y3 += proj.velocity.Y * num116;
            }
            Vector2 vector25 = new Vector2(x3, y3);
            x4 = mountedCenter.X - vector25.X;
            y4 = mountedCenter.Y - vector25.Y;
            float rotation19 = (float)Math.Atan2(y4, x4) - 1.57f;
            if (proj.alpha == 0)
            {
                int num117 = -1;
                if (proj.position.X + (float)(proj.width / 2) < mountedCenter.X)
                {
                    num117 = 1;
                }
                if (Main.player[proj.owner].direction == 1)
                {
                    Main.player[proj.owner].itemRotation = (float)Math.Atan2(y4 * (float)num117, x4 * (float)num117);
                }
                else
                {
                    Main.player[proj.owner].itemRotation = (float)Math.Atan2(y4 * (float)num117, x4 * (float)num117);
                }
            }
            bool flag23 = true;
            while (flag23)
            {
                float num118 = (float)Math.Sqrt(x4 * x4 + y4 * y4);
                if (num118 < 25f)
                {
                    flag23 = false;
                    continue;
                }
                if (float.IsNaN(num118))
                {
                    flag23 = false;
                    continue;
                }
                num118 = 12f / num118;
                x4 *= num118;
                y4 *= num118;
                vector25.X += x4;
                vector25.Y += y4;
                x4 = mountedCenter.X - vector25.X;
                y4 = mountedCenter.Y - vector25.Y;
                Microsoft.Xna.Framework.Color color28 = Lighting.GetColor((int)vector25.X / 16, (int)(vector25.Y / 16f));
                EntitySpriteDraw(TextureAssets.Chain23.Value, new Vector2(vector25.X - screenPosition.X, vector25.Y - screenPosition.Y), new Microsoft.Xna.Framework.Rectangle(0, 0, TextureAssets.Chain23.Width(), TextureAssets.Chain23.Height()), color28, rotation19, new Vector2((float)TextureAssets.Chain23.Width() * 0.5f, (float)TextureAssets.Chain23.Height() * 0.5f), 1f, SpriteEffects.None);
            }
        }
        else if (proj.type == 481)
        {
            float x5 = proj.Center.X;
            float y5 = proj.Center.Y;
            float x6 = proj.velocity.X;
            float y6 = proj.velocity.Y;
            float num119 = (float)Math.Sqrt(x6 * x6 + y6 * y6);
            num119 = 4f / num119;
            if (proj.ai[0] == 0f)
            {
                x5 -= proj.velocity.X * num119;
                y5 -= proj.velocity.Y * num119;
            }
            else
            {
                x5 += proj.velocity.X * num119;
                y5 += proj.velocity.Y * num119;
            }
            Vector2 origin5 = new Vector2(x5, y5);
            x6 = mountedCenter.X - origin5.X;
            y6 = mountedCenter.Y - origin5.Y;
            float rotation20 = (float)Math.Atan2(y6, x6) - 1.57f;
            if (proj.alpha == 0)
            {
                int num120 = -1;
                if (proj.position.X + (float)(proj.width / 2) < mountedCenter.X)
                {
                    num120 = 1;
                }
                if (Main.player[proj.owner].direction == 1)
                {
                    Main.player[proj.owner].itemRotation = (float)Math.Atan2(y6 * (float)num120, x6 * (float)num120);
                }
                else
                {
                    Main.player[proj.owner].itemRotation = (float)Math.Atan2(y6 * (float)num120, x6 * (float)num120);
                }
            }
            bool flag24 = true;
            while (flag24)
            {
                float num121 = 0.85f;
                float num122 = origin5.Distance(mountedCenter);
                float num123 = num122;
                if ((double)num122 < (double)TextureAssets.Chain40.Height() * 1.5)
                {
                    flag24 = false;
                    continue;
                }
                if (float.IsNaN(num122))
                {
                    flag24 = false;
                    continue;
                }
                num122 = (float)TextureAssets.Chain40.Height() * num121 / num122;
                x6 *= num122;
                y6 *= num122;
                origin5.X += x6;
                origin5.Y += y6;
                x6 = mountedCenter.X - origin5.X;
                y6 = mountedCenter.Y - origin5.Y;
                if (num123 > (float)(TextureAssets.Chain40.Height() * 2))
                {
                    for (int n = 0; n < 2; n++)
                    {
                        float num124 = 0.75f;
                        float num125 = 1f;
                        num125 = ((n != 0) ? Math.Abs(Main.player[proj.owner].velocity.Y) : Math.Abs(Main.player[proj.owner].velocity.X));
                        if (num125 > 10f)
{
                            num125 = 10f;
                        }
                        num125 /= 10f;
                        num124 *= num125;
                        num125 = num123 / 80f;
                        if (num125 > 1f)
{
                            num125 = 1f;
                        }
                        num124 *= num125;
                        if (num124 < 0f)
{
                            num124 = 0f;
                        }
                        if (float.IsNaN(num124))
{
                            continue;
                        }
                        if (n == 0)
{
                            if (Main.player[proj.owner].velocity.X < 0f && proj.Center.X < mountedCenter.X)
{
                                y6 *= 1f - num124;
                            }
                            if (Main.player[proj.owner].velocity.X > 0f && proj.Center.X > mountedCenter.X)
{
                                y6 *= 1f - num124;
                            }
                        }
                        else
{
                            if (Main.player[proj.owner].velocity.Y < 0f && proj.Center.Y < mountedCenter.Y)
{
                                x6 *= 1f - num124;
                            }
                            if (Main.player[proj.owner].velocity.Y > 0f && proj.Center.Y > mountedCenter.Y)
{
                                x6 *= 1f - num124;
                            }
                        }
                    }
                }
                Microsoft.Xna.Framework.Color color29 = Lighting.GetColor((int)origin5.X / 16, (int)(origin5.Y / 16f));
                EntitySpriteDraw(TextureAssets.Chain40.Value, new Vector2(origin5.X - screenPosition.X, origin5.Y - screenPosition.Y), new Microsoft.Xna.Framework.Rectangle(0, 0, TextureAssets.Chain40.Width(), TextureAssets.Chain40.Height()), color29, rotation20, new Vector2((float)TextureAssets.Chain40.Width() * 0.5f, (float)TextureAssets.Chain40.Height() * 0.5f), num121, SpriteEffects.None);
            }
        }
        else if (proj.type == 271)
        {
            float x7 = proj.Center.X;
            float y7 = proj.Center.Y;
            float x8 = proj.velocity.X;
            float y8 = proj.velocity.Y;
            float num126 = (float)Math.Sqrt(x8 * x8 + y8 * y8);
            num126 = 4f / num126;
            if (proj.ai[0] == 0f)
            {
                x7 -= proj.velocity.X * num126;
                y7 -= proj.velocity.Y * num126;
            }
            else
            {
                x7 += proj.velocity.X * num126;
                y7 += proj.velocity.Y * num126;
            }
            Vector2 vector26 = new Vector2(x7, y7);
            x8 = mountedCenter.X - vector26.X;
            y8 = mountedCenter.Y - vector26.Y;
            float rotation21 = (float)Math.Atan2(y8, x8) - 1.57f;
            if (proj.alpha == 0)
            {
                int num127 = -1;
                if (proj.position.X + (float)(proj.width / 2) < mountedCenter.X)
                {
                    num127 = 1;
                }
                if (Main.player[proj.owner].direction == 1)
                {
                    Main.player[proj.owner].itemRotation = (float)Math.Atan2(y8 * (float)num127, x8 * (float)num127);
                }
                else
                {
                    Main.player[proj.owner].itemRotation = (float)Math.Atan2(y8 * (float)num127, x8 * (float)num127);
                }
            }
            bool flag25 = true;
            while (flag25)
            {
                float num128 = (float)Math.Sqrt(x8 * x8 + y8 * y8);
                if (num128 < 25f)
                {
                    flag25 = false;
                    continue;
                }
                if (float.IsNaN(num128))
                {
                    flag25 = false;
                    continue;
                }
                num128 = 12f / num128;
                x8 *= num128;
                y8 *= num128;
                vector26.X += x8;
                vector26.Y += y8;
                x8 = mountedCenter.X - vector26.X;
                y8 = mountedCenter.Y - vector26.Y;
                Microsoft.Xna.Framework.Color color30 = Lighting.GetColor((int)vector26.X / 16, (int)(vector26.Y / 16f));
                EntitySpriteDraw(TextureAssets.Chain18.Value, new Vector2(vector26.X - screenPosition.X, vector26.Y - screenPosition.Y), new Microsoft.Xna.Framework.Rectangle(0, 0, TextureAssets.Chain18.Width(), TextureAssets.Chain18.Height()), color30, rotation21, new Vector2((float)TextureAssets.Chain18.Width() * 0.5f, (float)TextureAssets.Chain18.Height() * 0.5f), 1f, SpriteEffects.None);
            }
        }
        else if (proj.aiStyle == 13)
        {
            float num129 = proj.position.X + 8f;
            float num130 = proj.position.Y + 2f;
            float x9 = proj.velocity.X;
            float num131 = proj.velocity.Y;
            if (x9 == 0f && num131 == 0f)
            {
                num131 = 0.0001f;
                num131 = 0.0001f;
            }
            float num132 = (float)Math.Sqrt(x9 * x9 + num131 * num131);
            num132 = 20f / num132;
            if (proj.ai[0] == 0f)
            {
                num129 -= proj.velocity.X * num132;
                num130 -= proj.velocity.Y * num132;
            }
            else
            {
                num129 += proj.velocity.X * num132;
                num130 += proj.velocity.Y * num132;
            }
            Vector2 vector27 = new Vector2(num129, num130);
            x9 = mountedCenter.X - vector27.X;
            num131 = mountedCenter.Y - vector27.Y;
            float rotation22 = (float)Math.Atan2(num131, x9) - 1.57f;
            if (proj.alpha == 0)
            {
                int num133 = -1;
                if (proj.position.X + (float)(proj.width / 2) < mountedCenter.X)
                {
                    num133 = 1;
                }
                if (Main.player[proj.owner].direction == 1)
                {
                    Main.player[proj.owner].itemRotation = (float)Math.Atan2(num131 * (float)num133, x9 * (float)num133);
                }
                else
                {
                    Main.player[proj.owner].itemRotation = (float)Math.Atan2(num131 * (float)num133, x9 * (float)num133);
                }
            }
            bool flag26 = true;
            while (flag26)
            {
                float num134 = (float)Math.Sqrt(x9 * x9 + num131 * num131);
                if (num134 < 25f)
                {
                    flag26 = false;
                    continue;
                }
                if (float.IsNaN(num134))
                {
                    flag26 = false;
                    continue;
                }
                num134 = 12f / num134;
                x9 *= num134;
                num131 *= num134;
                vector27.X += x9;
                vector27.Y += num131;
                x9 = mountedCenter.X - vector27.X;
                num131 = mountedCenter.Y - vector27.Y;
                Microsoft.Xna.Framework.Color color31 = Lighting.GetColor((int)vector27.X / 16, (int)(vector27.Y / 16f));
                EntitySpriteDraw(TextureAssets.Chain.Value, new Vector2(vector27.X - screenPosition.X, vector27.Y - screenPosition.Y), new Microsoft.Xna.Framework.Rectangle(0, 0, TextureAssets.Chain.Width(), TextureAssets.Chain.Height()), color31, rotation22, new Vector2((float)TextureAssets.Chain.Width() * 0.5f, (float)TextureAssets.Chain.Height() * 0.5f), 1f, SpriteEffects.None);
            }
        }
        else if (proj.type == 190)
        {
            float x10 = proj.position.X + (float)(proj.width / 2);
            float y9 = proj.position.Y + (float)(proj.height / 2);
            float x11 = proj.velocity.X;
            float y10 = proj.velocity.Y;
            Math.Sqrt(x11 * x11 + y10 * y10);
            Vector2 vector28 = new Vector2(x10, y9);
            x11 = mountedCenter.X - vector28.X;
            y10 = mountedCenter.Y + Main.player[proj.owner].gfxOffY - vector28.Y;
            Math.Atan2(y10, x11);
            if (proj.alpha == 0)
            {
                int num135 = -1;
                if (proj.position.X + (float)(proj.width / 2) < mountedCenter.X)
                {
                    num135 = 1;
                }
                if (Main.player[proj.owner].direction == 1)
                {
                    Main.player[proj.owner].itemRotation = (float)Math.Atan2(y10 * (float)num135, x11 * (float)num135);
                }
                else
                {
                    Main.player[proj.owner].itemRotation = (float)Math.Atan2(y10 * (float)num135, x11 * (float)num135);
                }
            }
        }
        else if (proj.aiStyle == 15)
        {
            DrawProj_FlailChains(proj, mountedCenter);
        }
        Microsoft.Xna.Framework.Color projectileColor = Lighting.GetColor((int)((double)proj.position.X + (double)proj.width * 0.5) / 16, (int)(((double)proj.position.Y + (double)proj.height * 0.5) / 16.0));
        if (proj.hide && !ProjectileID.Sets.DontAttachHideToAlpha[proj.type])
        {
            projectileColor = Lighting.GetColor((int)mountedCenter.X / 16, (int)(mountedCenter.Y / 16f));
        }
        if (proj.type == 14)
        {
            projectileColor = Microsoft.Xna.Framework.Color.White;
        }
        int num136 = 0;
        int num137 = 0;
        if (proj.type == 175)
        {
            num136 = 10;
        }
        if (proj.type == 392)
        {
            num136 = -2;
        }
        if (proj.type == 499)
        {
            num136 = 12;
        }
        if (proj.type == 765)
        {
            num136 = 22;
            num137 = -16;
        }
        if (proj.type == 966)
        {
            num136 = -26;
            num137 = -6;
        }
        if (proj.bobber)
        {
            num136 = 8;
        }
        if (proj.type == 519)
        {
            num136 = 6;
            num137 -= 6;
        }
        if (proj.type == 520)
        {
            num136 = 12;
        }
        if (proj.type == 492)
        {
            num137 -= 4;
            num136 += 5;
        }
        if (proj.type == 498)
        {
            num136 = 6;
        }
        if (proj.type == 489)
        {
            num136 = -2;
        }
        if (proj.type == 486)
        {
            num136 = -6;
        }
        if (proj.type == 525)
        {
            num136 = 5;
        }
        if (proj.type == 488)
        {
            num137 -= 8;
        }
        if (proj.type == 373)
        {
            num137 = -10;
            num136 = 6;
        }
        if (proj.type == 375)
        {
            num137 = -11;
            num136 = 12;
        }
        if (proj.type == 423)
        {
            num137 = -5;
        }
        if (proj.type == 346)
        {
            num136 = 4;
        }
        if (proj.type == 331)
        {
            num137 = -4;
        }
        if (proj.type == 254)
        {
            num136 = 3;
        }
        if (proj.type == 273)
        {
            num137 = 2;
        }
        if (proj.type == 335)
        {
            num136 = 6;
        }
        if (proj.type == 162)
        {
            num136 = 1;
            num137 = 1;
        }
        if (proj.type == 377)
        {
            num136 = -6;
        }
        if (proj.type == 353)
        {
            num136 = 36;
            num137 = -12;
        }
        if (proj.type == 324)
        {
            num136 = 22;
            num137 = -6;
        }
        if (proj.type == 266)
        {
            num136 = 10;
            num137 = -10;
        }
        if (proj.type == 319)
        {
            num136 = 10;
            num137 = -12;
        }
        if (proj.type == 315)
        {
            num136 = -13;
            num137 = -6;
        }
        if (proj.type == 313 && proj.height != 54)
        {
            num137 = -12;
            num136 = 20;
        }
        if (proj.type == 314)
        {
            num137 = -8;
            num136 = 0;
        }
        if (proj.type == 269)
        {
            num136 = 18;
            num137 = -14;
        }
        if (proj.type == 268)
        {
            num136 = 22;
            num137 = -2;
        }
        if (proj.type == 18)
        {
            num136 = 3;
            num137 = 3;
        }
        if (proj.type == 16)
        {
            num136 = 6;
        }
        if (proj.type == 17 || proj.type == 31)
        {
            num136 = 2;
        }
        if (proj.type == 25 || proj.type == 26 || proj.type == 35 || proj.type == 63 || proj.type == 154)
        {
            num136 = 6;
            num137 -= 6;
        }
        if (proj.type == 947 || proj.type == 948)
        {
            num136 = 4;
            num137 -= 4;
        }
        if (proj.type == 28 || proj.type == 37 || proj.type == 75)
        {
            num136 = 8;
        }
        if (proj.type == 29 || proj.type == 470 || proj.type == 637)
        {
            num136 = 11;
        }
        if (proj.type == 43)
        {
            num136 = 4;
        }
        if (proj.type == 208)
        {
            num136 = 2;
            num137 -= 12;
        }
        if (proj.type == 209)
        {
            num136 = 4;
            num137 -= 8;
        }
        if (proj.type == 210)
        {
            num136 = 2;
            num137 -= 22;
        }
        if (proj.type == 251)
        {
            num136 = 18;
            num137 -= 10;
        }
        if (proj.type == 163 || proj.type == 310 || proj.type == 1009 || proj.type == 1010 || proj.type == 1011 || proj.type == 1008)
        {
            num136 = 10;
        }
        if (proj.type == 69 || proj.type == 70)
        {
            num136 = 4;
            num137 = 4;
        }
        float num138 = (float)(TextureAssets.Projectile[proj.type].Width() - proj.width) * 0.5f + (float)proj.width * 0.5f;
        if (proj.type == 50 || proj.type == 53 || proj.type == 515 || proj.type == 870)
        {
            num137 = -8;
        }
        if (proj.type == 473)
        {
            num137 = -6;
            num136 = 2;
        }
        if (proj.type == 72 || proj.type == 86 || proj.type == 87)
        {
            num137 = -16;
            num136 = 8;
        }
        if (proj.type == 74)
        {
            num137 = -6;
        }
        if (proj.type == 99 || proj.type == 727 || proj.type == 1013 || proj.type == 1014)
        {
            num136 = 1;
        }
        if (proj.type == 655)
        {
            num136 = 1;
        }
        if (proj.type == 111)
        {
            num136 = 18;
            num137 = -16;
        }
        if (proj.type == 875)
        {
            num136 = 16;
            num137 = -16;
        }
        if (proj.type == 881)
        {
            num136 = 14;
            num137 = -8;
        }
        if (proj.type == 934)
        {
            num136 = 14;
            num137 = -20;
        }
        if (proj.type == 934)
        {
            num136 = 14;
            num137 = -20;
        }
        if (proj.type == 884)
        {
            num136 = 16;
            num137 = -12;
        }
        if (proj.type == 890)
        {
            num136 = 26;
            num137 = -9;
        }
        if (proj.type == 891)
        {
            num136 = 30;
            num137 = -12;
        }
        if (proj.type == 897)
        {
            num136 = 38;
            num137 = -13;
        }
        if (proj.type == 899)
        {
            num136 = 28;
            num137 = -12;
        }
        if (proj.type == 900)
        {
            num136 = 54;
            num137 = -30;
        }
        if (proj.type == 334)
        {
            num137 = -18;
            num136 = 8;
        }
        if (proj.type == 816)
        {
            num137 = -19;
            num136 = 6;
        }
        if (proj.type == 821)
        {
            num137 = -10;
            num136 = 6;
        }
        if (proj.type == 825)
        {
            num137 = -19;
            num136 = 14;
        }
        if (proj.type == 854)
        {
            num137 = -14;
            num136 = 10;
        }
        if (proj.type == 858)
        {
            num137 = -8;
            num136 = 16;
        }
        if (proj.type == 859)
        {
            num137 = -8;
            num136 = 8;
        }
        if (proj.type == 860)
        {
            num137 = -8;
            num136 = 34;
        }
        if (proj.type == 958)
        {
            num137 = -20;
            num136 = 48;
        }
        if (proj.type == 960)
        {
            num137 = -14;
            num136 = 24;
        }
        if (proj.type == 956)
        {
            num137 = -12;
            num136 = 16;
        }
        if (proj.type == 959)
        {
            num137 = -14 + ((proj.spriteDirection == -1) ? (-8) : 0);
            num136 = 40;
        }
        if (proj.type == 994)
        {
            num137 = -10;
            num136 = 18;
        }
        if (proj.type == 998)
        {
            num137 = -10;
            num136 = 14;
        }
        if (proj.type == 1003)
        {
            num137 = -18 + ((proj.spriteDirection == 1) ? 8 : 0);
            num136 = 22;
        }
        if (proj.type == 1004)
        {
            num137 = -18 + ((proj.spriteDirection == 1) ? 6 : 0);
            num136 = 26;
        }
        if (proj.type == 200)
        {
            num136 = 12;
            num137 = -12;
        }
        if (proj.type == 211)
        {
            num136 = 14;
            num137 = 0;
        }
        if (proj.type == 236)
        {
            num136 = 30;
            num137 = -14;
        }
        if (proj.type >= 191 && proj.type <= 194)
        {
            num136 = 26;
            num137 = ((proj.direction != 1) ? (-22) : (-10));
        }
        if (proj.type >= 390 && proj.type <= 392)
        {
            num137 = 4 * proj.direction;
        }
        if (proj.type == 112)
        {
            num136 = 14;
            num137 = -8 + 4 * proj.spriteDirection;
        }
        _ = proj.type;
        _ = 118;
        if (proj.type == 517 || proj.type == 681)
        {
            num136 = 6;
        }
        if (proj.type == 516)
        {
            num136 = 6;
        }
        if (proj.type == 127)
        {
            num136 = 8;
        }
        if (proj.type == 155)
        {
            num136 = 3;
            num137 = 3;
        }
        if (proj.type == 397)
        {
            num138 -= 1f;
            num136 = -2;
            num137 = -2;
        }
        if (proj.type == 398)
        {
            num136 = 8;
        }
        SpriteEffects dir = SpriteEffects.None;
        if (proj.spriteDirection == -1)
        {
            dir = SpriteEffects.FlipHorizontally;
        }
        if (proj.type == 681 && proj.velocity.X > 0f)
        {
            dir ^= SpriteEffects.FlipHorizontally;
        }
        if (proj.type == 221)
        {
            for (int num139 = 1; num139 < 10; num139++)
            {
                float num140 = proj.velocity.X * (float)num139 * 0.5f;
                float num141 = proj.velocity.Y * (float)num139 * 0.5f;
                Microsoft.Xna.Framework.Color alpha = proj.GetAlpha(projectileColor);
                float num142 = 0f;
                if (num139 == 1)
                {
                    num142 = 0.9f;
                }
                if (num139 == 2)
                {
                    num142 = 0.8f;
                }
                if (num139 == 3)
                {
                    num142 = 0.7f;
                }
                if (num139 == 4)
                {
                    num142 = 0.6f;
                }
                if (num139 == 5)
                {
                    num142 = 0.5f;
                }
                if (num139 == 6)
                {
                    num142 = 0.4f;
                }
                if (num139 == 7)
                {
                    num142 = 0.3f;
                }
                if (num139 == 8)
                {
                    num142 = 0.2f;
                }
                if (num139 == 9)
                {
                    num142 = 0.1f;
                }
                alpha.R = (byte)((float)(int)alpha.R * num142);
                alpha.G = (byte)((float)(int)alpha.G * num142);
                alpha.B = (byte)((float)(int)alpha.B * num142);
                alpha.A = (byte)((float)(int)alpha.A * num142);
                int num143 = TextureAssets.Projectile[proj.type].Height() / projFrames[proj.type];
                int y11 = num143 * proj.frame;
                EntitySpriteDraw(TextureAssets.Projectile[proj.type].Value, new Vector2(proj.position.X - screenPosition.X + num138 + (float)num137 - num140, proj.position.Y - screenPosition.Y + (float)(proj.height / 2) + proj.gfxOffY - num141), new Microsoft.Xna.Framework.Rectangle(0, y11, TextureAssets.Projectile[proj.type].Width(), num143), alpha, proj.rotation, new Vector2(num138, proj.height / 2 + num136), proj.scale, dir);
            }
        }
        if (proj.type == 408 || proj.type == 435 || proj.type == 436 || proj.type == 438 || proj.type == 452 || proj.type == 454 || proj.type == 459 || proj.type == 462 || proj.type == 503 || proj.type == 532 || proj.type == 533 || proj.type == 573 || proj.type == 582 || proj.type == 585 || proj.type == 592 || proj.type == 601 || proj.type == 636 || proj.type == 638 || proj.type == 640 || proj.type == 639 || proj.type == 424 || proj.type == 425 || proj.type == 426 || proj.type == 660 || proj.type == 661 || proj.type == 671 || proj.type == 664 || proj.type == 666 || proj.type == 668 || proj.type == 675 || proj.type == 680 || proj.type == 682 || proj.type == 684 || proj.type == 686 || proj.type == 700 || proj.type == 706 || proj.type == 709 || proj.type == 710 || proj.type == 711 || proj.type == 261 || ProjectileID.Sets.IsAGolfBall[proj.type] || proj.type == 729 || proj.type == 732 || proj.type == 731 || proj.type == 755 || proj.type == 811 || proj.type == 814 || proj.type == 819 || proj.type == 864 || proj.type == 873 || proj.type == 872 || proj.type == 833 || proj.type == 834 || proj.type == 835 || proj.type == 818 || proj.type == 902 || proj.type == 894 || proj.type == 901 || proj.type == 909 || proj.type == 916 || proj.type == 931 || proj.type == 933 || proj.type == 964 || proj.type == 965 || proj.type == 977 || proj.type == 976 || proj.type == 1001)
        {
            Texture2D value11 = TextureAssets.Projectile[proj.type].Value;
            int num144 = TextureAssets.Projectile[proj.type].Height() / projFrames[proj.type];
            int y12 = num144 * proj.frame;
            Microsoft.Xna.Framework.Rectangle rectangle4 = new Microsoft.Xna.Framework.Rectangle(0, y12, value11.Width, num144);
            Vector2 origin6 = rectangle4.Size() / 2f;
            Vector2 zero = Vector2.Zero;
            float num145 = 0f;
            if (proj.type == 503)
            {
                origin6.Y = 70f;
            }
            if (proj.type == 686 || proj.type == 711)
            {
                origin6.Y = rectangle4.Height - 70;
            }
            if (proj.type == 438)
            {
                rectangle4.Y = 0;
            }
            if (proj.type == 452)
            {
                rectangle4.Y = 0;
            }
            if (proj.type == 408)
            {
                rectangle4.Y = num144;
            }
            if (proj.type == 636)
            {
                origin6.Y = 10f;
            }
            if (proj.type == 638)
            {
                origin6.Y = 2f;
            }
            if (proj.type == 640 || proj.type == 639 || proj.type == 710)
            {
                origin6.Y = 5f;
            }
            if (proj.type == 700)
            {
                origin6.X = ((proj.spriteDirection == 1) ? (rectangle4.Width - 20) : 20);
            }
            if (proj.type == 965 || proj.type == 964)
            {
                origin6.X = ((proj.spriteDirection == 1) ? (rectangle4.Width - 20) : 20);
            }
            if (proj.type == 872)
            {
                rectangle4.Width /= 2;
                origin6.X /= 2f;
            }
            if (proj.type == 933)
            {
                int num146 = (int)proj.ai[1];
                if (TextureAssets.Item.IndexInRange(num146))
                {
                    instance.LoadItem(num146);
                    value11 = TextureAssets.Item[num146].Value;
                    rectangle4 = value11.Frame();
                    origin6 = rectangle4.Size() / 2f;
                    num145 = -(float)Math.PI / 4f * (float)proj.spriteDirection;
                }
            }
            if (proj.type == 833 && proj.frame != 8)
            {
                zero.Y += proj.height / 2;
                origin6 = rectangle4.Size() * new Vector2(0.5f, 1f);
                origin6.Y -= 4f;
                origin6.X -= 7 * dir.HasFlag(SpriteEffects.FlipHorizontally).ToDirectionInt();
            }
            if ((proj.type == 834 || proj.type == 835) && proj.frame != 10)
            {
                zero.Y += proj.height / 2;
                origin6 = rectangle4.Size() * new Vector2(0.5f, 1f);
                origin6.Y -= 4f;
                origin6.X -= 2 * dir.HasFlag(SpriteEffects.FlipHorizontally).ToDirectionInt();
            }
            int num147 = 8;
            int num148 = 2;
            int num149 = 1;
            float value12 = 1f;
            float num150 = 15f;
            float num151 = 0f;
            Microsoft.Xna.Framework.Rectangle value13 = rectangle4;
            UnifiedRandom unifiedRandom = null;
            if (proj.type == 909)
            {
                num149 = 5;
                num147 = 0;
                num148 = -1;
            }
            else if (proj.type == 503)
            {
                num147 = 9;
                num148 = 3;
                value12 = 0.5f;
            }
            else if (proj.type == 261)
            {
                num149 = 18;
                num147 = 0;
                num148 = -2;
                value12 = 1.3f;
            }
            else if (proj.type == 833 || proj.type == 834 || proj.type == 835)
            {
                num149 = 6;
                num147 = 0;
                num148 = -1;
                value12 = 1.5f;
            }
            else if (proj.type == 818)
            {
                num149 = 18;
                num147 = 0;
                num148 = -2;
                value12 = 1f;
            }
            else if (proj.type == 729)
            {
                num149 = 18;
                num147 = 0;
                num148 = -2;
                value12 = 1.3f;
            }
            else if (proj.type == 977)
            {
                num149 = 18;
                num147 = 0;
                num148 = -2;
                value12 = 1.3f;
            }
            else if (proj.type == 1001)
            {
                num149 = 10;
                num147 = 0;
                num148 = -2;
                value12 = 1.3f;
                dir = ((proj.spriteDirection != 1) ? SpriteEffects.FlipVertically : SpriteEffects.None);
            }
            else if (proj.type == 976)
            {
                num149 = 18;
                num147 = 0;
                num148 = -3;
                value12 = 1.3f;
                rectangle4 = new Microsoft.Xna.Framework.Rectangle(0, 20 * proj.frame, 32, 18);
                value13 = rectangle4;
                origin6 = rectangle4.Size() / 2f;
            }
            else if (proj.type == 686 || proj.type == 711)
            {
                num149 = 19;
                num147 = 0;
                num148 = -3;
                value12 = 0.5f;
            }
            else if (ProjectileID.Sets.IsAGolfBall[proj.type])
            {
                num149 = 0;
                num147 = 0;
                num148 = -1;
                value12 = 2f;
            }
            else if (proj.type == 671)
            {
                num149 = 5;
                num147 = 0;
                num148 = -1;
                value12 = 2.6f;
            }
            else if (proj.type == 811)
            {
                num149 = 5;
                num147 = 0;
                num148 = -1;
                value12 = 2.6f;
                projectileColor = Microsoft.Xna.Framework.Color.Lerp(projectileColor, Microsoft.Xna.Framework.Color.White, Utils.Remap(proj.ai[0], 0f, 15f, 1f, 0.3f));
            }
            else if (proj.type == 814)
            {
                num149 = 18;
                num147 = 0;
                num148 = -1;
                value12 = 1f;
                projectileColor = Microsoft.Xna.Framework.Color.Lerp(projectileColor, Microsoft.Xna.Framework.Color.White, 0.35f);
            }
            else if (proj.type == 755)
            {
                num149 = 5;
                num147 = 0;
                num148 = -1;
                value12 = 2.6f;
            }
            else if (proj.type == 700)
            {
                num147 = 5;
                num148 = 1;
                value12 = 2.6f;
            }
            else if (proj.type == 965 || proj.type == 964)
            {
                num147 = 5;
                num148 = 1;
                value12 = 2.6f;
            }
            else if (proj.type == 731)
            {
                num149 = 19;
                num147 = 0;
                num148 = -1;
                value12 = 0.5f;
            }
            else if (proj.type == 864)
            {
                num149 = 12;
                num147 = 0;
                num148 = -1;
                value12 = 1.4f;
                value13.Y += value13.Height;
            }
            else if (proj.type == 916)
            {
                num149 = 19;
                num147 = 0;
                num148 = -1;
                value12 = 1.4f;
                value13.Y += value13.Height;
                unifiedRandom = _tempSeededRandom;
                unifiedRandom.SetSeed(proj.timeLeft);
            }
            else if (proj.type == 873)
            {
                num149 = 39;
                num150 = 40f;
                num147 = 0;
                num148 = -1;
                value12 = 1.4f;
            }
            else if (proj.type == 931)
            {
                num149 = 19;
                num150 = 20f;
                num147 = 0;
                num148 = -1;
                value12 = 0.7f;
            }
            else if (proj.type == 933)
            {
                num149 = 60;
                num150 = 60f;
                num147 = 0;
                num148 = -15;
                value12 = 1f;
            }
            else if (proj.type == 872)
            {
                num149 = 79;
                num150 = 10f;
                num147 = 0;
                num148 = -1;
                value12 = 1f;
                value13.X += value13.Width;
            }
            else if (proj.type == 664 || proj.type == 666 || proj.type == 668)
            {
                num147 = 8;
                num148 = 2;
                value12 = 0.4f;
            }
            else if (proj.type == 582 || proj.type == 902)
            {
                if (proj.ai[2] == 1f)
                {
                    value11 = TextureAssets.Extra[263].Value;
                }
                num147 = 10;
                num148 = 2;
                value12 = 0.7f;
                num151 = 0.2f;
            }
            else if (proj.type == 675)
            {
                num147 = 5;
                num148 = 1;
                value12 = 0.4f;
            }
            else if (proj.type == 638)
            {
                num147 = 5;
                num148 = 1;
                value12 = 1f;
            }
            else if (proj.type == 660)
            {
                num147 = 3;
                num148 = 1;
                value12 = 8f;
                rectangle4 = new Microsoft.Xna.Framework.Rectangle(38 * proj.frame, 0, 38, 38);
                value13 = rectangle4;
                origin6 = rectangle4.Size() / 2f;
            }
            else if (proj.type == 684)
            {
                num147 = 8;
                num148 = 1;
                value12 = 0.75f;
            }
            else if (proj.type == 639)
            {
                num147 = 10;
                num148 = 1;
                value12 = 1f;
            }
            else if (proj.type == 710)
            {
                num149 = 9;
                num147 = 0;
                num148 = -2;
                value12 = 0.5f;
            }
            else if (proj.type == 640)
            {
                num147 = 20;
                num148 = 1;
                value12 = 1f;
            }
            else if (proj.type == 436)
            {
                num148 = 2;
                value12 = 0.5f;
            }
            else if (proj.type == 424 || proj.type == 425 || proj.type == 426)
            {
                num147 = 10;
                num148 = 2;
                value12 = 0.6f;
            }
            else if (proj.type == 438)
            {
                num147 = 10;
                num148 = 2;
                value12 = 1f;
            }
            else if (proj.type == 452)
            {
                num147 = 10;
                num148 = 3;
                value12 = 0.5f;
            }
            else if (proj.type == 454)
            {
                num147 = 5;
                num148 = 1;
                value12 = 0.2f;
            }
            else if (proj.type == 462)
            {
                num147 = 7;
                num148 = 1;
                value12 = 0.2f;
            }
            else if (proj.type == 661)
            {
                num147 = 0;
                num148 = 1;
                value12 = 0.5f;
            }
            else if (proj.type == 706)
            {
                num149 = 9;
                num147 = 0;
                num148 = -2;
                value12 = 0.5f;
            }
            else if (proj.type == 585)
            {
                num147 = 7;
                num148 = 1;
                value12 = 0.2f;
            }
            else if (proj.type == 459)
            {
                num147 = (int)(proj.scale * 8f);
                num148 = num147 / 4;
                if (num148 < 1)
                {
                    num148 = 1;
                }
                value12 = 0.3f;
            }
            else if (proj.type == 709)
            {
                num147 = 8;
                num148 = num147 / 4;
                if (num148 < 1)
                {
                    num148 = 1;
                }
                value12 = 0.5f;
            }
            else if (proj.type == 532)
            {
                num147 = 10;
                num148 = 1;
                value12 = 0.7f;
                num151 = 0.2f;
            }
            else if (proj.type == 592)
            {
                num147 = 10;
                num148 = 2;
                value12 = 1f;
            }
            else if (proj.type == 601)
            {
                num147 = 8;
                num148 = 1;
                value12 = 0.3f;
            }
            else if (proj.type == 636)
            {
                num147 = 20;
                num148 = 3;
                value12 = 0.5f;
            }
            else if (proj.type == 680)
            {
                num147 = 9;
                num148 = 3;
                value12 = 0.5f;
            }
            else if (proj.type == 533)
            {
                if (proj.ai[0] >= 6f && proj.ai[0] <= 8f)
                {
                    num147 = ((proj.ai[0] == 6f) ? 8 : 4);
                    num148 = 1;
                    if (proj.ai[0] != 7f)
                    {
                        num151 = 0.2f;
                    }
                }
                else
                {
                    num147 = (num148 = 0);
                }
            }
            for (int num152 = num149; (num148 > 0 && num152 < num147) || (num148 < 0 && num152 > num147); num152 += num148)
            {
                if (num152 >= proj.oldPos.Length)
                {
                    continue;
                }
                Microsoft.Xna.Framework.Color color32 = projectileColor;
                if (proj.type == 408 || proj.type == 435 || proj.type == 682 || proj.type == 732 || proj.type == 731)
                {
                    color32 = Microsoft.Xna.Framework.Color.Lerp(color32, Microsoft.Xna.Framework.Color.Blue, 0.5f);
                }
                else if (proj.type == 436)
                {
                    color32 = Microsoft.Xna.Framework.Color.Lerp(color32, Microsoft.Xna.Framework.Color.LimeGreen, 0.5f);
                }
                else if (proj.type >= 424 && proj.type <= 426)
                {
                    color32 = Microsoft.Xna.Framework.Color.Lerp(color32, Microsoft.Xna.Framework.Color.Red, 0.5f);
                }
                else if (proj.type == 640 || proj.type == 639)
                {
                    color32.A = 127;
                }
                else if (proj.type == 671)
                {
                    color32 = Microsoft.Xna.Framework.Color.Lerp(color32, Microsoft.Xna.Framework.Color.Purple, (float)num152 / (float)num147);
                }
                else if (proj.type == 811)
                {
                    color32 = Microsoft.Xna.Framework.Color.Lerp(color32, Microsoft.Xna.Framework.Color.Crimson * 0.5f, (float)num152 / (float)num147);
                }
                else if (proj.type == 814)
                {
                    color32 = Microsoft.Xna.Framework.Color.Lerp(color32, color32 * 0.5f, (float)num152 / (float)num147);
                }
                else if (proj.type == 261)
                {
                    color32 = Microsoft.Xna.Framework.Color.Lerp(color32, new Microsoft.Xna.Framework.Color(60, 60, 60, 60), (float)num152 / (float)num147);
                }
                else if (ProjectileID.Sets.IsAGolfBall[proj.type])
                {
                    color32 = Microsoft.Xna.Framework.Color.Lerp(color32, new Microsoft.Xna.Framework.Color(255, 230, 40, 20), (float)num152 / (float)num147);
                }
                color32 = proj.GetAlpha(color32);
                if (proj.type == 438)
                {
                    color32.G /= (byte)num152;
                    color32.B /= (byte)num152;
                }
                else if (proj.type == 755)
                {
                    color32 = proj.AI_156_GetColor();
                }
                else if (proj.type == 873)
                {
                    color32 = proj.AI_171_GetColor();
                    color32.A /= 2;
                    color32 *= Utils.GetLerpValue(0f, 20f, proj.timeLeft, clamped: true);
                }
                else if (proj.type == 931)
                {
                    color32 = proj.GetFairyQueenWeaponsColor(0.5f);
                    color32 *= Utils.GetLerpValue(0f, 20f, proj.timeLeft, clamped: true);
                }
                else if (proj.type == 872)
                {
                    color32 = proj.AI_173_GetColor();
                    color32 *= 0.4f;
                    color32.A = (byte)((float)(int)color32.A * 0.6f);
                    if (num152 > 80)
                    {
                        color32 *= 0.15f * Utils.GetLerpValue(120f, 80f, num152, clamped: true);
                    }
                }
                else if (proj.type == 864)
                {
                    color32 = proj.GetFloatingDaggerMinionGlowColor();
                    color32.A /= 4;
                }
                else if (proj.type == 682)
                {
                    color32.G /= (byte)num152;
                }
                else if (proj.type == 686)
                {
                    if (proj.oldPos[num152] == Vector2.Zero)
                    {
                        continue;
                    }
                    float num153 = (float)num152 / (float)num149;
                    color32 = ((!(num153 < 0.5f)) ? Microsoft.Xna.Framework.Color.Lerp(Microsoft.Xna.Framework.Color.Purple, Microsoft.Xna.Framework.Color.Black, Utils.GetLerpValue(0.5f, 1f, num153)) : Microsoft.Xna.Framework.Color.Lerp(color32, Microsoft.Xna.Framework.Color.Purple, Utils.GetLerpValue(0f, 0.5f, num153)));
                }
                else if (proj.type == 711)
                {
                    if (proj.oldPos[num152] == Vector2.Zero)
                    {
                        continue;
                    }
                    float num154 = (float)num152 / (float)num149;
                    color32 = ((!(num154 < 0.5f)) ? Microsoft.Xna.Framework.Color.Lerp(new Microsoft.Xna.Framework.Color(128, 0, 255, 180), Microsoft.Xna.Framework.Color.Black, Utils.GetLerpValue(0.5f, 1f, num154)) : Microsoft.Xna.Framework.Color.Lerp(color32, new Microsoft.Xna.Framework.Color(128, 0, 255, 180), Utils.GetLerpValue(0f, 0.5f, num154)));
                }
                else if (proj.type == 684)
                {
                    if (num152 == 1)
                    {
                        color32.B /= 2;
                        color32.G /= 2;
                        color32.A /= 2;
                    }
                    color32.B /= (byte)num152;
                    color32.G /= (byte)num152;
                    color32.A /= (byte)num152;
                }
                else if (proj.type == 706 || proj.type == 710)
                {
                    color32.B /= (byte)num152;
                    color32.G /= (byte)num152;
                    color32.A /= (byte)num152;
                }
                else if (proj.type == 818)
                {
                    float num155 = 0.3f;
                    float num156 = Utils.GetLerpValue(0f, num155, proj.ai[0], clamped: true) * Utils.GetLerpValue(1f, 1f - num155, proj.ai[0], clamped: true);
                    Utils.GetLerpValue(0f, num148 * -3, num152, clamped: true);
                    Utils.GetLerpValue(num149, num149 + num148 * 3, num152, clamped: true);
                    Microsoft.Xna.Framework.Color value14 = new Microsoft.Xna.Framework.Color(255, 255, 255, 0);
                    Microsoft.Xna.Framework.Color ourFavoriteColor = OurFavoriteColor;
                    ourFavoriteColor.A = 0;
                    ourFavoriteColor *= num156;
                    color32 = Microsoft.Xna.Framework.Color.Lerp(ourFavoriteColor, value14, num156);
                }
                else if (proj.type == 833 || proj.type == 834 || proj.type == 835)
                {
                    float lerpValue2 = Utils.GetLerpValue(0f, 6f, proj.velocity.Length(), clamped: true);
                    color32 = Microsoft.Xna.Framework.Color.Lerp(color32, Microsoft.Xna.Framework.Color.White, lerpValue2 * 0.5f);
                    color32.A = 0;
                    color32 *= lerpValue2;
                }
                else if (proj.type == 592)
                {
                    color32.R /= (byte)num152;
                    color32.G /= (byte)num152;
                }
                else if (proj.type == 640)
                {
                    color32.R /= (byte)num152;
                    color32.A /= (byte)num152;
                }
                else if (proj.type >= 424 && proj.type <= 426)
                {
                    color32.B /= (byte)num152;
                    color32.G /= (byte)num152;
                    color32.A /= (byte)num152;
                }
                else if (proj.type == 964 || proj.type == 965)
                {
                    color32 = Microsoft.Xna.Framework.Color.Black * proj.Opacity;
                }
                float num157 = num147 - num152;
                if (num148 < 0)
                {
                    num157 = num149 - num152;
                }
                color32 *= num157 / ((float)ProjectileID.Sets.TrailCacheLength[proj.type] * 1.5f);
                Vector2 vector29 = proj.oldPos[num152];
                float num158 = proj.rotation;
                SpriteEffects effects2 = dir;
                if (ProjectileID.Sets.TrailingMode[proj.type] == 2 || ProjectileID.Sets.TrailingMode[proj.type] == 3 || ProjectileID.Sets.TrailingMode[proj.type] == 4)
                {
                    num158 = proj.oldRot[num152];
                    effects2 = ((proj.oldSpriteDirection[num152] == -1) ? SpriteEffects.FlipHorizontally : SpriteEffects.None);
                }
                if (vector29 == Vector2.Zero)
                {
                    continue;
                }
                if (proj.type == 916)
                {
                    value13.Y += value13.Height;
                    value13.Y %= value13.Height * projFrames[proj.type];
                    _ = num157 / ((float)ProjectileID.Sets.TrailCacheLength[proj.type] * 1.5f);
                    Microsoft.Xna.Framework.Color color33 = new Microsoft.Xna.Framework.Color(0, 0, 0, 255);
                    int num159 = unifiedRandom.Next(3);
                    if (num159 == 2 || num159 == 1)
                    {
                        color33 = Microsoft.Xna.Framework.Color.Lerp(new Microsoft.Xna.Framework.Color(106, 90, 205, 127), Microsoft.Xna.Framework.Color.Black, 0.2f + 0.8f * unifiedRandom.NextFloat());
                    }
                    color32 = color33;
                    float num160 = num157 / (float)ProjectileID.Sets.TrailCacheLength[proj.type];
                    num160 = Utils.GetLerpValue(0f, (float)ProjectileID.Sets.TrailCacheLength[proj.type] * 0.75f, num157, clamped: true);
                    color32 *= num160;
                    vector29 += unifiedRandom.NextVector2Circular(8f, 8f);
                }
                if (proj.type == 976)
                {
                    int num161 = value13.Height + 2;
                    value13.Y += num161;
                    value13.Y %= num161 * 7;
                    color32 *= Lighting.GetColor((vector29 + zero + proj.Size / 2f).ToTileCoordinates()).ToVector3().Length() / 1.74f;
                }
                if (proj.type == 933)
                {
                    float t = proj.localAI[0] - (float)num152;
                    float num162 = Utils.GetLerpValue(0f, 20f, t, clamped: true) * Utils.GetLerpValue(68f, 60f, t, clamped: true);
                    float lerpValue3 = Utils.GetLerpValue(0f, ProjectileID.Sets.TrailCacheLength[proj.type], num157, clamped: true);
                    color32 = Microsoft.Xna.Framework.Color.White * lerpValue3 * proj.Opacity * num162;
                }
                Vector2 position3 = vector29 + zero + proj.Size / 2f - screenPosition + new Vector2(0f, proj.gfxOffY);
                EntitySpriteDraw(value11, position3, value13, color32, num158 + num145 + proj.rotation * num151 * (float)(num152 - 1) * (float)(-dir.HasFlag(SpriteEffects.FlipHorizontally).ToDirectionInt()), origin6, MathHelper.Lerp(proj.scale, value12, (float)num152 / num150), effects2);
            }
            if (proj.type == 661)
            {
                Microsoft.Xna.Framework.Color color34 = new Microsoft.Xna.Framework.Color(120, 40, 222, 120);
                for (int num163 = 0; num163 < 4; num163++)
                {
                    EntitySpriteDraw(TextureAssets.Extra[75].Value, proj.Center - screenPosition + new Vector2(0f, proj.gfxOffY) + proj.rotation.ToRotationVector2().RotatedBy((float)Math.PI / 2f * (float)num163) * 4f, rectangle4, color34, proj.rotation, origin6, proj.scale, dir);
                }
            }
            if (proj.type == 864)
            {
                Microsoft.Xna.Framework.Color floatingDaggerMinionGlowColor = proj.GetFloatingDaggerMinionGlowColor();
                floatingDaggerMinionGlowColor.A /= 4;
                Microsoft.Xna.Framework.Rectangle value15 = rectangle4;
                value15.Y += value15.Height;
                for (int num164 = 0; num164 < 4; num164++)
                {
                    EntitySpriteDraw(value11, proj.Center - screenPosition + new Vector2(0f, proj.gfxOffY) + proj.rotation.ToRotationVector2().RotatedBy((float)Math.PI / 2f * (float)num164) * 2f, value15, floatingDaggerMinionGlowColor, proj.rotation, origin6, proj.scale, dir);
                }
            }
            if (proj.type == 873 || proj.type == 931)
            {
                Microsoft.Xna.Framework.Color color35 = proj.AI_171_GetColor() * 0.5f;
                color35.A = 0;
                if (proj.type == 931)
                {
                    color35 = proj.GetFairyQueenWeaponsColor(0f);
                }
                Vector2 vector30 = proj.Center - screenPosition + new Vector2(0f, proj.gfxOffY);
                EntitySpriteDraw(value11, vector30, rectangle4, color35, proj.rotation, origin6, proj.scale * 0.9f, dir);
                Texture2D value16 = TextureAssets.Extra[98].Value;
                Microsoft.Xna.Framework.Color color36 = color35;
                Vector2 origin7 = value16.Size() / 2f;
                Microsoft.Xna.Framework.Color color37 = color35 * 0.5f;
                float num165 = Utils.GetLerpValue(15f, 30f, proj.timeLeft, clamped: true) * Utils.GetLerpValue(240f, 200f, proj.timeLeft, clamped: true) * (1f + 0.2f * (float)Math.Cos(GlobalTimeWrappedHourly % 30f / 0.5f * ((float)Math.PI * 2f) * 3f)) * 0.8f;
                Vector2 vector31 = new Vector2(0.5f, 5f) * num165;
                Vector2 vector32 = new Vector2(0.5f, 2f) * num165;
                color36 *= num165;
                color37 *= num165;
                int num166 = 0;
                Vector2 position4 = vector30 + proj.velocity.SafeNormalize(Vector2.Zero) * MathHelper.Lerp(0.5f, 1f, proj.localAI[0] / 60f) * num166;
                if (proj.type == 931)
                {
                    vector31 *= 0.4f;
                    vector32 *= 0.4f;
                }
                EntitySpriteDraw(value16, position4, null, color36, (float)Math.PI / 2f, origin7, vector31, dir);
                EntitySpriteDraw(value16, position4, null, color36, 0f, origin7, vector32, dir);
                EntitySpriteDraw(value16, position4, null, color37, (float)Math.PI / 2f, origin7, vector31 * 0.6f, dir);
                EntitySpriteDraw(value16, position4, null, color37, 0f, origin7, vector32 * 0.6f, dir);
            }
            if (proj.type == 755)
            {
                Microsoft.Xna.Framework.Color color38 = proj.AI_156_GetColor();
                color38.A = 120;
                for (int num167 = 0; num167 < 4; num167++)
                {
                    EntitySpriteDraw(value11, proj.Center - screenPosition + new Vector2(0f, proj.gfxOffY) + proj.rotation.ToRotationVector2().RotatedBy((float)Math.PI / 2f * (float)num167) * 2f, rectangle4, color38, proj.rotation, origin6, proj.scale, dir);
                }
            }
            else if (proj.type == 684)
            {
                float x12 = (proj.localAI[0] * ((float)Math.PI * 2f) / 30f).ToRotationVector2().X;
                Microsoft.Xna.Framework.Color color39 = new Microsoft.Xna.Framework.Color(220, 40, 30, 40);
                color39 *= 0.75f + 0.25f * x12;
                for (int num168 = 0; num168 < 8; num168++)
                {
                    EntitySpriteDraw(value11, proj.Center - screenPosition + new Vector2(0f, proj.gfxOffY) + proj.rotation.ToRotationVector2().RotatedBy((float)Math.PI / 4f * (float)num168) * (4f + 1f * x12), rectangle4, color39, proj.rotation, origin6, proj.scale, dir);
                }
            }
            else if (ProjectileID.Sets.IsAGolfBall[proj.type])
            {
                Player player2 = Main.player[proj.owner];
                bool flag27 = GolfHelper.IsPlayerHoldingClub(player2);
                bool flag28 = false;
                if (flag27)
                {
                    flag28 |= player2.ownedProjectileCounts[722] > 0 && player2.itemAnimation >= player2.itemAnimationMax;
                    flag28 |= player2.itemAnimation == 0;
                    flag28 &= player2.velocity.Y == 0f;
                }
                Vector2 shotVector = MouseWorld - proj.Center;
                if (proj.owner == myPlayer && flag27 && flag28 && GolfHelper.IsGolfBallResting(proj) && GolfHelper.ValidateShot(proj, player2, ref shotVector))
                {
                    projectileColor = Microsoft.Xna.Framework.Color.White;
                    Projectile projectile = null;
                    for (int num169 = 0; num169 < 1000; num169++)
                    {
                        Projectile projectile2 = Main.projectile[num169];
                        if (projectile2.active && projectile2.owner == player2.whoAmI && projectile2.type == 722)
{
                            projectile = projectile2;
                            break;
                        }
                    }
                    if (projectile != null)
                    {
                        GolfHelper.ShotStrength shotStrength = GolfHelper.CalculateShotStrength(projectile, proj);
                        Vector2 impactVelocity = Vector2.Normalize(shotVector) * shotStrength.AbsoluteStrength;
                        if (impactVelocity.Length() > 0.05f)
{
                            GolfHelper.DrawPredictionLine(proj, impactVelocity, shotStrength.RelativeStrength, shotStrength.RoughLandResistance);
                        }
                    }
                }
                if (!GolfHelper.IsGolfBallResting(proj))
                {
                    Microsoft.Xna.Framework.Color golfTrailColor = Projectile.GetGolfTrailColor(proj);
                    float num170 = proj.velocity.Length() / 16f;
                    if (num170 > 1f)
                    {
                        num170 = 1f;
                    }
                    golfTrailColor *= num170;
                    if (proj.oldPos[4] != Vector2.Zero)
                    {
                        projectileColor = Microsoft.Xna.Framework.Color.White;
                        for (float num171 = 0f; num171 <= 1f; num171 += 0.04f)
{
                            EntitySpriteDraw(value11, Vector2.Lerp(proj.oldPos[4], proj.position, num171) + proj.Size / 2f - screenPosition + new Vector2(0f, proj.gfxOffY), rectangle4, golfTrailColor * num171, proj.rotation, origin6, proj.scale * MathHelper.Lerp(0.7f, 1.5f, num171), dir);
                        }
                    }
                    EntitySpriteDraw(value11, proj.position + proj.Size / 2f - screenPosition + new Vector2(0f, proj.gfxOffY), rectangle4, golfTrailColor, proj.rotation, origin6, proj.scale * 1.5f, dir);
                }
            }
            if (proj.type == 964 || proj.type == 965)
            {
                Microsoft.Xna.Framework.Color color40 = Microsoft.Xna.Framework.Color.Violet;
                if (proj.type == 965)
                {
                    color40 = Microsoft.Xna.Framework.Color.Lerp(Microsoft.Xna.Framework.Color.Red, Microsoft.Xna.Framework.Color.White, 0.5f);
                }
                Microsoft.Xna.Framework.Color color41 = color40 * 0.5f * proj.Opacity;
                float num172 = ((proj.type == 964) ? 60 : 30);
                for (int num173 = 0; num173 < 4; num173++)
                {
                    EntitySpriteDraw(value11, proj.Center - screenPosition + new Vector2(0f, proj.gfxOffY) + proj.rotation.ToRotationVector2().RotatedBy(proj.ai[0] / num172 * ((float)Math.PI * 2f) + (float)Math.PI / 2f * (float)num173) * 6f, rectangle4, color41, proj.rotation, origin6, proj.scale, dir);
                }
            }
            Microsoft.Xna.Framework.Color color42 = proj.GetAlpha(projectileColor);
            float num174 = proj.scale;
            float rotation23 = proj.rotation + num145;
            if (proj.type == 640)
            {
                color42 = Microsoft.Xna.Framework.Color.Transparent;
            }
            if (proj.type == 684)
            {
                color42.A = 127;
            }
            if (proj.type == 873)
            {
                color42.A /= 2;
            }
            if (proj.type == 931)
            {
                color42.A /= 2;
            }
            if (proj.type == 872)
            {
                color42 = new Microsoft.Xna.Framework.Color(255, 255, 255, 0) * proj.Opacity;
                num174 *= 0.9f;
            }
            if (proj.type == 818)
            {
                color42 = Microsoft.Xna.Framework.Color.Transparent;
            }
            if (proj.type == 916)
            {
                color42 = Microsoft.Xna.Framework.Color.Black;
            }
            if (proj.type == 964 || proj.type == 965)
            {
                color42 = Microsoft.Xna.Framework.Color.Black * proj.Opacity;
            }
            if (proj.type == 933)
            {
                float t2 = proj.localAI[0];
                float num175 = Utils.GetLerpValue(0f, 20f, t2, clamped: true) * Utils.GetLerpValue(68f, 60f, t2, clamped: true);
                color42 *= num175;
            }
            EntitySpriteDraw(value11, proj.Center + zero - screenPosition + new Vector2(0f, proj.gfxOffY), rectangle4, color42, rotation23, origin6, num174, dir);
            if (proj.type == 894)
            {
                float num176 = Utils.WrappedLerp(0.6f, 1f, (float)((int)timeForVisualEffects % 70) / 70f);
                EntitySpriteDraw(color: new Microsoft.Xna.Framework.Color(num176, num176, num176, 150f), texture: TextureAssets.GlowMask[282].Value, position: proj.Center + zero - screenPosition + new Vector2(0f, proj.gfxOffY), sourceRectangle: rectangle4, rotation: proj.rotation, origin: origin6, scale: proj.scale, effects: dir);
            }
            if (proj.type == 503)
            {
                EntitySpriteDraw(TextureAssets.Extra[36].Value, proj.Center - screenPosition + new Vector2(0f, proj.gfxOffY), rectangle4, Microsoft.Xna.Framework.Color.White, proj.localAI[0], origin6, proj.scale, dir);
            }
            else if (proj.type == 533)
            {
                EntitySpriteDraw(TextureAssets.GlowMask[128].Value, proj.Center - screenPosition + new Vector2(0f, proj.gfxOffY), rectangle4, Microsoft.Xna.Framework.Color.White * 0.3f, proj.rotation, origin6, proj.scale, dir);
            }
            else if (proj.type == 261)
            {
                float num177 = 0.7f;
                float num178 = proj.velocity.Length();
                if (num178 < 0.3f && proj.velocity.Y == 0f)
                {
                    num177 = Utils.GetLerpValue(0.02f, 0.3f, num178, clamped: true) * 0.7f;
                }
                EntitySpriteDraw(TextureAssets.GlowMask[252].Value, proj.Center - screenPosition + new Vector2(0f, proj.gfxOffY), rectangle4, Microsoft.Xna.Framework.Color.White * num177, proj.rotation, origin6, proj.scale, dir);
            }
            else if (proj.type == 601)
            {
                Microsoft.Xna.Framework.Color white2 = Microsoft.Xna.Framework.Color.White;
                white2.A = 0;
                EntitySpriteDraw(value11, proj.Center - screenPosition + new Vector2(0f, proj.gfxOffY), rectangle4, white2, proj.rotation, origin6, proj.scale * 0.7f, dir);
            }
            else if (ProjectileID.Sets.IsAGolfBall[proj.type] && GolfHelper.IsGolfBallResting(proj) && GolfHelper.IsPlayerHoldingClub(LocalPlayer) && GolfHelper.IsGolfShotValid(proj, LocalPlayer) && proj.owner == myPlayer)
            {
                EntitySpriteDraw(TextureAssets.GolfBallOutline.Value, proj.Center - screenPosition + new Vector2(0f, proj.gfxOffY), rectangle4, Microsoft.Xna.Framework.Color.White, proj.rotation, origin6, proj.scale, dir);
            }
            if (proj.type == 933)
            {
                float t3 = proj.localAI[0];
                float num179 = Utils.GetLerpValue(0f, 20f, t3, clamped: true) * Utils.GetLerpValue(68f, 60f, t3, clamped: true);
                EntitySpriteDraw(value11, proj.Center + zero - screenPosition + new Vector2(0f, proj.gfxOffY), rectangle4, new Microsoft.Xna.Framework.Color(255, 255, 255, 127) * proj.Opacity * num179, rotation23, origin6, num174 * 1.25f, dir);
                FinalFractalHelper.FinalFractalProfile finalFractalProfile = FinalFractalHelper.GetFinalFractalProfile((int)proj.ai[1]);
                Microsoft.Xna.Framework.Color trailColor = finalFractalProfile.trailColor;
                trailColor.A /= 2;
                DrawPrettyStarSparkle(proj.Opacity, dir, proj.Center + zero - screenPosition + new Vector2(0f, proj.gfxOffY) + (proj.rotation - (float)Math.PI / 2f).ToRotationVector2() * finalFractalProfile.trailWidth, Microsoft.Xna.Framework.Color.White * num179, trailColor * num179, proj.localAI[0], 15f, 30f, 30f, 45f, 0f, new Vector2(5f, 2f), Vector2.One);
            }
        }
        else if (proj.type == 672)
        {
            Vector2 position5 = proj.Center - screenPosition;
            if (proj.localAI[1] == 0f)
            {
                position5.Y += 60f;
                float num180 = proj.localAI[0] / 120f;
                for (int num181 = 0; num181 < 4; num181++)
                {
                    float value17 = num180 * 2f - (float)num181 / 3f;
                    value17 = MathHelper.Clamp(value17, 0f, 1f);
                    float num182 = 1f - MathHelper.Clamp((num180 - 0.8f) / 0.2f, 0f, 1f);
                    EntitySpriteDraw(TextureAssets.MagicPixel.Value, position5, null, new Microsoft.Xna.Framework.Color(0.4f, 0.17f, 0.4f, 0f) * (value17 * num182) * 1.3f, 0f, new Vector2((float)TextureAssets.MagicPixel.Width() / 2f, TextureAssets.MagicPixel.Height()), new Vector2((float)Math.Sqrt(value17) * 100f, value17 * 2f), SpriteEffects.None);
                }
            }
            else if (proj.localAI[1] == 1f)
            {
                _ = proj.localAI[0] / 300f;
                float num183 = Math.Min(1f, proj.localAI[0] / 30f);
                int num184 = (int)(GlobalTimeWrappedHourly * 10f) % 8;
                DrawElderEye(spriteBatch, proj.Center, 1f, 1f, num184, Microsoft.Xna.Framework.Color.White * num183);
                DrawElderEye(spriteBatch, proj.Center, 1f, 1f, (num184 + 1) % 8, new Microsoft.Xna.Framework.Color(0.2f, 0.2f, 0.2f, 0f) * num183);
            }
            else if (proj.localAI[1] == 2f)
            {
                int num185 = (int)(GlobalTimeWrappedHourly * 10f) % 8;
                DrawElderEye(spriteBatch, proj.Center, 1f, 1f, num185, Microsoft.Xna.Framework.Color.White);
                DrawElderEye(spriteBatch, proj.Center, 1f, 1f, (num185 + 1) % 8, new Microsoft.Xna.Framework.Color(0.2f, 0.2f, 0.2f, 0f));
            }
        }
        else
        {
            if (proj.type == 713)
            {
                return;
            }
            if (proj.type == 754)
            {
                Texture2D value18 = TextureAssets.Projectile[proj.type].Value;
                Microsoft.Xna.Framework.Rectangle rectangle5 = value18.Frame(5, 2, proj.frame);
                rectangle5.Width -= 2;
                rectangle5.Height -= 2;
                Vector2 origin8 = new Vector2(rectangle5.Width / 2, 0f);
                float y13 = proj.position.Y;
                float num186 = proj.ai[0] + 8f + 2f - (float)rectangle5.Height + 2f;
                Microsoft.Xna.Framework.Color alpha2 = proj.GetAlpha(projectileColor);
                Vector2 top = proj.Top;
                if (proj.ai[1] == 2f)
                {
                    rectangle5 = value18.Frame(5, 2, 4);
                    rectangle5.Width -= 2;
                    rectangle5.Height -= 2;
                    origin8 = new Vector2(rectangle5.Width / 2, 0f);
                    alpha2 = proj.GetAlpha(Lighting.GetColor((int)(top.X + (float)(rectangle5.Width / 2)) / 16, (int)((num186 - 2f + (float)(rectangle5.Height / 2)) / 16f)));
                    EntitySpriteDraw(value18, new Vector2(top.X, num186 - 2f) - screenPosition + new Vector2(0f, proj.gfxOffY), rectangle5, alpha2, proj.rotation, origin8, proj.scale, dir);
                    return;
                }
                for (float num187 = y13; num187 < num186; num187 += (float)rectangle5.Height)
                {
                    Vector2 vector33 = top;
                    vector33.Y = num187;
                    Microsoft.Xna.Framework.Rectangle value19 = rectangle5;
                    float num188 = num186 - num187;
                    if (num188 < (float)value19.Height)
                    {
                        value19.Height = (int)num188;
                    }
                    alpha2 = proj.GetAlpha(Lighting.GetColor((int)(vector33.X + (float)(value19.Width / 2)) / 16, (int)((vector33.Y + (float)(value19.Height / 2)) / 16f)));
                    EntitySpriteDraw(value18, vector33 - screenPosition + new Vector2(0f, proj.gfxOffY), value19, alpha2, proj.rotation, origin8, proj.scale, dir);
                    if (rectangle5.Y == 0)
                    {
                        rectangle5.Y += rectangle5.Height + 2;
                    }
                }
                rectangle5 = value18.Frame(5, 2, 4);
                rectangle5.Width -= 2;
                rectangle5.Height -= 2;
                origin8 = new Vector2(rectangle5.Width / 2, 0f);
                alpha2 = proj.GetAlpha(Lighting.GetColor((int)(top.X + (float)(rectangle5.Width / 2)) / 16, (int)((num186 - 2f + (float)(rectangle5.Height / 2)) / 16f)));
                EntitySpriteDraw(value18, new Vector2(top.X, num186 - 2f) - screenPosition + new Vector2(0f, proj.gfxOffY), rectangle5, alpha2, proj.rotation, origin8, proj.scale, dir);
                return;
            }
            if (proj.type == 12 || proj.type == 728 || proj.type == 955)
            {
                Texture2D value20 = TextureAssets.Projectile[proj.type].Value;
                Microsoft.Xna.Framework.Rectangle rectangle6 = new Microsoft.Xna.Framework.Rectangle(0, 0, value20.Width, value20.Height);
                Vector2 origin9 = rectangle6.Size() / 2f;
                Microsoft.Xna.Framework.Color alpha3 = proj.GetAlpha(projectileColor);
                Texture2D value21 = TextureAssets.Extra[91].Value;
                Microsoft.Xna.Framework.Rectangle value22 = value21.Frame();
                Vector2 origin10 = new Vector2((float)value22.Width / 2f, 10f);
                Vector2 vector34 = new Vector2(0f, proj.gfxOffY);
                Vector2 spinningpoint = new Vector2(0f, -10f);
                float num189 = (float)timeForVisualEffects / 60f;
                Vector2 vector35 = proj.Center + proj.velocity;
                Microsoft.Xna.Framework.Color color44 = Microsoft.Xna.Framework.Color.Blue * 0.2f;
                Microsoft.Xna.Framework.Color color45 = Microsoft.Xna.Framework.Color.White * 0.5f;
                color45.A = 0;
                float num190 = 0f;
                if (tenthAnniversaryWorld)
                {
                    color44 = Microsoft.Xna.Framework.Color.HotPink * 0.3f;
                    color45 = Microsoft.Xna.Framework.Color.White * 0.75f;
                    color45.A = 0;
                    num190 = -0.1f;
                }
                if (proj.type == 728)
                {
                    color44 = Microsoft.Xna.Framework.Color.Orange * 0.2f;
                    color45 = Microsoft.Xna.Framework.Color.Gold * 0.5f;
                    color45.A = 50;
                    num190 = -0.2f;
                }
                Microsoft.Xna.Framework.Color color46 = color44;
                color46.A = 0;
                Microsoft.Xna.Framework.Color color47 = color44;
                color47.A = 0;
                Microsoft.Xna.Framework.Color color48 = color44;
                color48.A = 0;
                EntitySpriteDraw(value21, vector35 - screenPosition + vector34 + spinningpoint.RotatedBy((float)Math.PI * 2f * num189), value22, color46, proj.velocity.ToRotation() + (float)Math.PI / 2f, origin10, 1.5f + num190, SpriteEffects.None);
                EntitySpriteDraw(value21, vector35 - screenPosition + vector34 + spinningpoint.RotatedBy((float)Math.PI * 2f * num189 + (float)Math.PI * 2f / 3f), value22, color47, proj.velocity.ToRotation() + (float)Math.PI / 2f, origin10, 1.1f + num190, SpriteEffects.None);
                EntitySpriteDraw(value21, vector35 - screenPosition + vector34 + spinningpoint.RotatedBy((float)Math.PI * 2f * num189 + 4.1887903f), value22, color48, proj.velocity.ToRotation() + (float)Math.PI / 2f, origin10, 1.3f + num190, SpriteEffects.None);
                Vector2 vector36 = proj.Center - proj.velocity * 0.5f;
                for (float num191 = 0f; num191 < 1f; num191 += 0.5f)
                {
                    float num192 = num189 % 0.5f / 0.5f;
                    num192 = (num192 + num191) % 1f;
                    float num193 = num192 * 2f;
                    if (num193 > 1f)
                    {
                        num193 = 2f - num193;
                    }
                    EntitySpriteDraw(value21, vector36 - screenPosition + vector34, value22, color45 * num193, proj.velocity.ToRotation() + (float)Math.PI / 2f, origin10, 0.3f + num192 * 0.5f, SpriteEffects.None);
                }
                EntitySpriteDraw(value20, proj.Center - screenPosition + new Vector2(0f, proj.gfxOffY), rectangle6, alpha3, proj.rotation, origin9, proj.scale + 0.1f, dir);
                return;
            }
            if (proj.type == 756)
            {
                Texture2D value23 = TextureAssets.Projectile[proj.type].Value;
                Microsoft.Xna.Framework.Rectangle value24 = value23.Frame(1, 6, 0, proj.frame);
                Vector2 origin11 = new Vector2(16f, value24.Height / 2);
                Microsoft.Xna.Framework.Color alpha4 = proj.GetAlpha(projectileColor);
                Vector2 scale2 = new Vector2(proj.scale);
                float lerpValue4 = Utils.GetLerpValue(35f, 35f - 5f, proj.ai[0], clamped: true);
                scale2.Y *= lerpValue4;
                Vector4 vector37 = projectileColor.ToVector4();
                Vector4 vector38 = new Microsoft.Xna.Framework.Color(67, 17, 17).ToVector4();
                vector38 *= vector37;
                EntitySpriteDraw(TextureAssets.Extra[98].Value, proj.Center - screenPosition + new Vector2(0f, proj.gfxOffY) - proj.velocity * proj.scale * 0.5f, null, proj.GetAlpha(new Microsoft.Xna.Framework.Color(vector38.X, vector38.Y, vector38.Z, vector38.W)) * 1f, proj.rotation + (float)Math.PI / 2f, TextureAssets.Extra[98].Value.Size() / 2f, proj.scale * 0.9f, dir);
                EntitySpriteDraw(value23, proj.Center - screenPosition + new Vector2(0f, proj.gfxOffY), value24, alpha4, proj.rotation, origin11, scale2, dir);
                return;
            }
            if (proj.type == 961)
            {
                Texture2D value25 = TextureAssets.Projectile[proj.type].Value;
                Microsoft.Xna.Framework.Rectangle value26 = value25.Frame(1, 5, 0, proj.frame);
                Vector2 origin12 = new Vector2(16f, value26.Height / 2);
                Microsoft.Xna.Framework.Color alpha5 = proj.GetAlpha(projectileColor);
                Vector2 vector39 = new Vector2(proj.scale);
                float lerpValue5 = Utils.GetLerpValue(30f, 25f, proj.ai[0], clamped: true);
                vector39.Y *= lerpValue5;
                Vector4 vector40 = projectileColor.ToVector4();
                Vector4 vector41 = new Microsoft.Xna.Framework.Color(67, 17, 17).ToVector4();
                vector41 *= vector40;
                EntitySpriteDraw(TextureAssets.Extra[98].Value, proj.Center - screenPosition + new Vector2(0f, proj.gfxOffY) - proj.velocity * proj.scale * 0.5f, null, proj.GetAlpha(new Microsoft.Xna.Framework.Color(vector41.X, vector41.Y, vector41.Z, vector41.W)) * 1f, proj.rotation + (float)Math.PI / 2f, TextureAssets.Extra[98].Value.Size() / 2f, proj.scale * 0.9f, dir);
                Microsoft.Xna.Framework.Color color49 = proj.GetAlpha(Microsoft.Xna.Framework.Color.White) * Utils.Remap(proj.ai[0], 0f, 20f, 0.5f, 0f);
                color49.A = 0;
                for (int num194 = 0; num194 < 4; num194++)
                {
                    EntitySpriteDraw(value25, proj.Center - screenPosition + new Vector2(0f, proj.gfxOffY) + proj.rotation.ToRotationVector2().RotatedBy((float)Math.PI / 2f * (float)num194) * 2f * vector39, value26, color49, proj.rotation, origin12, vector39, dir);
                }
                EntitySpriteDraw(value25, proj.Center - screenPosition + new Vector2(0f, proj.gfxOffY), value26, alpha5, proj.rotation, origin12, vector39, dir);
                return;
            }
            if (proj.type == 723 || proj.type == 726 || proj.type == 725 || proj.type == 724 || proj.type == 9)
            {
                Texture2D value27 = TextureAssets.Projectile[proj.type].Value;
                Microsoft.Xna.Framework.Rectangle rectangle7 = new Microsoft.Xna.Framework.Rectangle(0, 0, value27.Width, value27.Height);
                Vector2 origin13 = rectangle7.Size() / 2f;
                Microsoft.Xna.Framework.Color color50 = proj.GetAlpha(projectileColor);
                Texture2D value28 = TextureAssets.Extra[91].Value;
                Microsoft.Xna.Framework.Rectangle value29 = value28.Frame();
                Vector2 origin14 = new Vector2((float)value29.Width / 2f, 10f);
                _ = Microsoft.Xna.Framework.Color.White * 0.2f;
                Vector2 vector42 = new Vector2(0f, proj.gfxOffY);
                Vector2 spinningpoint2 = new Vector2(0f, -5f);
                float num195 = (float)timeForVisualEffects / 60f;
                Vector2 vector43 = proj.Center + proj.velocity;
                float num196 = 1.5f;
                float num197 = 1.1f;
                float num198 = 1.3f;
                Microsoft.Xna.Framework.Color color51 = Microsoft.Xna.Framework.Color.Blue * 0.1f;
                Microsoft.Xna.Framework.Color color52 = Microsoft.Xna.Framework.Color.White * 0.3f;
                color52.A = 0;
                byte a = 0;
                float num199 = 1f;
                bool flag29 = true;
                float num200 = proj.scale + 0.1f;
                if (proj.type == 726)
                {
                    Microsoft.Xna.Framework.Color color53 = new Microsoft.Xna.Framework.Color(180, 20, 255);
                    color51 = color53 * 0.3f;
                    color52 = color53 * 0.3f;
                    a = 60;
                    float num201 = 0.6f;
                    num196 -= num201;
                    num197 -= num201;
                    num198 -= num201;
                }
                if (proj.type == 725)
                {
                    Microsoft.Xna.Framework.Color value30 = new Microsoft.Xna.Framework.Color(255, 80, 255);
                    Microsoft.Xna.Framework.Color value31 = new Microsoft.Xna.Framework.Color(255, 255, 0);
                    color51 = Microsoft.Xna.Framework.Color.Lerp(value30, value31, 0.2f) * 0.3f;
                    color52 = Microsoft.Xna.Framework.Color.Lerp(value30, value31, 0.8f) * 0.4f;
                    a = 50;
                    float num202 = 0.5f;
                    num196 -= num202;
                    num197 -= num202;
                    num198 -= num202;
                }
                if (proj.type == 724)
                {
                    Microsoft.Xna.Framework.Color.Lerp(Microsoft.Xna.Framework.Color.Black, Microsoft.Xna.Framework.Color.Orange, 0.75f);
                    Microsoft.Xna.Framework.Color color54 = Microsoft.Xna.Framework.Color.Lerp(Microsoft.Xna.Framework.Color.Black, Microsoft.Xna.Framework.Color.Yellow, 0.5f);
                    Microsoft.Xna.Framework.Color value32 = Microsoft.Xna.Framework.Color.Orange * 0.75f;
                    color54 = Microsoft.Xna.Framework.Color.Yellow * 0.5f;
                    color51 = Microsoft.Xna.Framework.Color.Lerp(value32, color54, 0.2f) * 0.3f;
                    color52 = Microsoft.Xna.Framework.Color.Lerp(value32, color54, 0.8f) * 0.4f;
                    a = 0;
                    float num203 = 0.5f;
                    num196 -= num203;
                    num197 -= num203;
                    num198 -= num203;
                }
                if (proj.type == 9)
                {
                    num196 = 0.9f;
                    num197 = 0f;
                    num198 = 0f;
                    flag29 = false;
                    spinningpoint2 = Vector2.Zero;
                    vector42 += proj.velocity.SafeNormalize(Vector2.Zero) * 8f;
                    num199 *= 0.75f;
                    vector43 -= proj.velocity;
                    Microsoft.Xna.Framework.Color value33 = new Microsoft.Xna.Framework.Color(194, 22, 134);
                    value33 *= 0.75f;
                    value33.A /= 2;
                    Microsoft.Xna.Framework.Color value34 = Microsoft.Xna.Framework.Color.Lerp(Microsoft.Xna.Framework.Color.Gold, Microsoft.Xna.Framework.Color.White, 0.5f);
                    value34.A /= 4;
                    value34 *= 0.85f;
                    value34 *= 0.75f;
                    Microsoft.Xna.Framework.Color gold = Microsoft.Xna.Framework.Color.Gold;
                    gold.A = 180;
                    Microsoft.Xna.Framework.Color value35 = new Microsoft.Xna.Framework.Color(194, 22, 134, 127);
                    Microsoft.Xna.Framework.Color value36 = new Microsoft.Xna.Framework.Color(180, 20, 255) * 0.75f * 0.3f;
                    Microsoft.Xna.Framework.Color value37 = new Microsoft.Xna.Framework.Color(255, 255, 255, 0) * 0.5f * 0.3f;
                    float num204 = 0.5f;
                    float num205 = proj.rotation * num204 % ((float)Math.PI * 2f);
                    if (num205 < 0f)
                    {
                        num205 += (float)Math.PI * 2f;
                    }
                    num205 /= (float)Math.PI * 2f;
                    float num206 = Utils.Remap(num205, 0.15f, 0.5f, 0f, 1f) * Utils.Remap(num205, 0.5f, 0.85f, 1f, 0f);
                    num206 = 1f - num206;
                    color50 = Microsoft.Xna.Framework.Color.Lerp(gold, value35, num206);
                    color51 = Microsoft.Xna.Framework.Color.Lerp(value33, value36, num206);
                    color52 = Microsoft.Xna.Framework.Color.Lerp(value34, value37, num206);
                    num200 += num206 * 0.2f;
                }
                Microsoft.Xna.Framework.Color color55 = color51;
                Microsoft.Xna.Framework.Color color56 = color51;
                Microsoft.Xna.Framework.Color color57 = color51;
                if (flag29)
                {
                    color55.A = a;
                    color56.A = a;
                    color57.A = a;
                }
                EntitySpriteDraw(value28, vector43 - screenPosition + vector42 + spinningpoint2.RotatedBy((float)Math.PI * 2f * num195), value29, color55, proj.velocity.ToRotation() + (float)Math.PI / 2f, origin14, num196, SpriteEffects.None);
                EntitySpriteDraw(value28, vector43 - screenPosition + vector42 + spinningpoint2.RotatedBy((float)Math.PI * 2f * num195 + (float)Math.PI * 2f / 3f), value29, color56, proj.velocity.ToRotation() + (float)Math.PI / 2f, origin14, num197, SpriteEffects.None);
                EntitySpriteDraw(value28, vector43 - screenPosition + vector42 + spinningpoint2.RotatedBy((float)Math.PI * 2f * num195 + 4.1887903f), value29, color57, proj.velocity.ToRotation() + (float)Math.PI / 2f, origin14, num198, SpriteEffects.None);
                Vector2 vector44 = proj.Center - proj.velocity * 0.5f;
                for (float num207 = 0f; num207 < 1f; num207 += 0.5f)
                {
                    float num208 = num195 % 0.5f / 0.5f;
                    num208 = (num208 + num207) % 1f;
                    float num209 = num208 * 2f;
                    if (num209 > 1f)
                    {
                        num209 = 2f - num209;
                    }
                    EntitySpriteDraw(value28, vector44 - screenPosition + vector42, value29, color52 * num209, proj.velocity.ToRotation() + (float)Math.PI / 2f, origin14, (0.5f + num208 * 0.5f) * num199, SpriteEffects.None);
                }
                EntitySpriteDraw(value27, proj.Center - screenPosition + new Vector2(0f, proj.gfxOffY), rectangle7, color50, proj.rotation, origin13, num200, dir);
                return;
            }
            if (proj.type == 674)
            {
                Texture2D value38 = TextureAssets.Extra[60].Value;
                Vector2 origin15 = new Vector2(66f, 86f);
                Vector2 position6 = proj.Center - screenPosition;
                Vector2 one = Vector2.One;
                one = new Vector2(4f, 1f) * 1.4f;
                Microsoft.Xna.Framework.Color color58 = new Microsoft.Xna.Framework.Color(115, 0, 155, 0);
                Microsoft.Xna.Framework.Color color59 = new Microsoft.Xna.Framework.Color(255, 180, 255, 0);
                float num210 = 0f;
                if (proj.ai[0] < 30f)
                {
                    num210 = Utils.GetLerpValue(0f, 30f, proj.ai[0], clamped: true);
                }
                else if (proj.ai[0] < 40f)
                {
                    num210 = 1f + Utils.GetLerpValue(30f, 40f, proj.ai[0], clamped: true);
                }
                Vector2 vector45 = new Vector2(1f, 1f);
                Vector2 vector46 = new Vector2(0.8f, 2f);
                if (num210 < 1f)
                {
                    vector45.X *= num210;
                }
                one *= num210;
                if (num210 < 1f)
                {
                    color58 *= num210;
                    color59 *= num210;
                }
                if (num210 > 1.5f)
                {
                    float lerpValue6 = Utils.GetLerpValue(2f, 1.5f, num210, clamped: true);
                    color58 *= lerpValue6;
                    color59 *= lerpValue6;
                }
                float num211 = 0.42f;
                color58 *= num211;
                color59 *= num211;
                EntitySpriteDraw(value38, position6, null, color58, 0f, origin15, one * vector45, SpriteEffects.None);
                EntitySpriteDraw(value38, position6, null, color59, 0f, origin15, one * vector46, SpriteEffects.None);
                EntitySpriteDraw(TextureAssets.Extra[59].Value, position6, null, color58, 0f, origin15, one * vector45 * new Vector2(1f, 0.3f), SpriteEffects.None);
                return;
            }
            if (proj.type == 440 || proj.type == 449 || proj.type == 606)
            {
                Microsoft.Xna.Framework.Rectangle value39 = new Microsoft.Xna.Framework.Rectangle((int)screenPosition.X - 500, (int)screenPosition.Y - 500, screenWidth + 1000, screenHeight + 1000);
                if (proj.getRect().Intersects(value39))
                {
                    Vector2 vector47 = new Vector2(proj.position.X - screenPosition.X + num138 + (float)num137, proj.position.Y - screenPosition.Y + (float)(proj.height / 2) + proj.gfxOffY);
                    float num212 = 100f;
                    float num213 = 3f;
                    if (proj.type == 606)
                    {
                        num212 = 150f;
                        num213 = 3f;
                    }
                    if (proj.ai[1] == 1f)
                    {
                        num212 = (int)proj.localAI[0];
                    }
                    for (int num214 = 1; num214 <= (int)proj.localAI[0]; num214++)
                    {
                        Vector2 vector48 = Vector2.Normalize(proj.velocity) * num214 * num213;
                        Microsoft.Xna.Framework.Color alpha6 = proj.GetAlpha(projectileColor);
                        alpha6 *= (num212 - (float)num214) / num212;
                        alpha6.A = 0;
                        EntitySpriteDraw(TextureAssets.Projectile[proj.type].Value, vector47 - vector48, null, alpha6, proj.rotation, new Vector2(num138, proj.height / 2 + num136), proj.scale, dir);
                    }
                }
                return;
            }
            if (proj.type == 85)
            {
                DrawProj_Flamethrower(proj);
                return;
            }
            if (proj.type == 687)
            {
                Vector2 center2 = proj.Center;
                center2 -= screenPosition;
                float num215 = 40f;
                float num216 = num215 * 2f;
                float num217 = (float)proj.frameCounter / num215;
                Texture2D value40 = TextureAssets.Projectile[proj.type].Value;
                Microsoft.Xna.Framework.Color transparent = Microsoft.Xna.Framework.Color.Transparent;
                Microsoft.Xna.Framework.Color color60 = new Microsoft.Xna.Framework.Color(255, 255, 255, 0);
                Microsoft.Xna.Framework.Color color61 = new Microsoft.Xna.Framework.Color(180, 30, 30, 200);
                Microsoft.Xna.Framework.Color color62 = new Microsoft.Xna.Framework.Color(0, 0, 0, 30);
                ulong seed = 1uL;
                for (float num218 = 0f; num218 < 15f; num218 += 1f)
                {
                    float num219 = Utils.RandomFloat(ref seed) * 0.25f - 0.125f;
                    Vector2 vector49 = (proj.rotation + num219).ToRotationVector2();
                    Vector2 value41 = center2 + vector49 * 400f;
                    float num220 = num217 + num218 * (1f / 15f);
                    int num221 = (int)(num220 / (1f / 15f));
                    num220 %= 1f;
                    if ((!(num220 > num217 % 1f) || !((float)proj.frameCounter < num215)) && (!(num220 < num217 % 1f) || !((float)proj.frameCounter >= num216 - num215)))
                    {
                        transparent = ((num220 < 0.1f) ? Microsoft.Xna.Framework.Color.Lerp(Microsoft.Xna.Framework.Color.Transparent, color60, Utils.GetLerpValue(0f, 0.1f, num220, clamped: true)) : ((num220 < 0.35f) ? color60 : ((num220 < 0.7f) ? Microsoft.Xna.Framework.Color.Lerp(color60, color61, Utils.GetLerpValue(0.35f, 0.7f, num220, clamped: true)) : ((num220 < 0.9f) ? Microsoft.Xna.Framework.Color.Lerp(color61, color62, Utils.GetLerpValue(0.7f, 0.9f, num220, clamped: true)) : ((!(num220 < 1f)) ? Microsoft.Xna.Framework.Color.Transparent : Microsoft.Xna.Framework.Color.Lerp(color62, Microsoft.Xna.Framework.Color.Transparent, Utils.GetLerpValue(0.9f, 1f, num220, clamped: true)))))));
                        float num222 = 0.9f + num220 * 0.8f;
                        num222 *= num222;
                        num222 *= 0.8f;
                        Vector2 position7 = Vector2.SmoothStep(center2, value41, num220);
                        Microsoft.Xna.Framework.Rectangle rectangle8 = value40.Frame(1, 7, 0, (int)(num220 * 7f));
                        EntitySpriteDraw(value40, position7, rectangle8, transparent, proj.rotation + (float)Math.PI * 2f * (num220 + GlobalTimeWrappedHourly * 1.2f) * 0.2f + (float)num221 * ((float)Math.PI * 2f / 5f), rectangle8.Size() / 2f, num222, SpriteEffects.None);
                    }
                }
                return;
            }
            if (proj.type == 651)
            {
                if (proj.owner != myPlayer)
                {
                    return;
                }
                Player player3 = Main.player[proj.owner];
                Microsoft.Xna.Framework.Point point = new Vector2(proj.ai[0], proj.ai[1]).ToPoint();
                Microsoft.Xna.Framework.Point point2 = proj.Center.ToTileCoordinates();
                Microsoft.Xna.Framework.Color color63 = new Microsoft.Xna.Framework.Color(255, 255, 255, 0);
                Microsoft.Xna.Framework.Color color64 = new Microsoft.Xna.Framework.Color(127, 127, 127, 0);
                int num223 = 1;
                float num224 = 0f;
                WiresUI.Settings.MultiToolMode toolMode = WiresUI.Settings.ToolMode;
                bool flag30 = toolMode.HasFlag(WiresUI.Settings.MultiToolMode.Actuator);
                if (toolMode.HasFlag(WiresUI.Settings.MultiToolMode.Red))
                {
                    num224 += 1f;
                    color64 = Microsoft.Xna.Framework.Color.Lerp(color64, Microsoft.Xna.Framework.Color.Red, 1f / num224);
                }
                if (toolMode.HasFlag(WiresUI.Settings.MultiToolMode.Blue))
                {
                    num224 += 1f;
                    color64 = Microsoft.Xna.Framework.Color.Lerp(color64, Microsoft.Xna.Framework.Color.Blue, 1f / num224);
                }
                if (toolMode.HasFlag(WiresUI.Settings.MultiToolMode.Green))
                {
                    num224 += 1f;
                    color64 = Microsoft.Xna.Framework.Color.Lerp(color64, new Microsoft.Xna.Framework.Color(0, 255, 0), 1f / num224);
                }
                if (toolMode.HasFlag(WiresUI.Settings.MultiToolMode.Yellow))
                {
                    num224 += 1f;
                    color64 = Microsoft.Xna.Framework.Color.Lerp(color64, new Microsoft.Xna.Framework.Color(255, 255, 0), 1f / num224);
                }
                if (toolMode.HasFlag(WiresUI.Settings.MultiToolMode.Cutter))
                {
                    color63 = new Microsoft.Xna.Framework.Color(50, 50, 50, 255);
                }
                color64.A = 0;
                if (point == point2)
                {
                    Vector2 position8 = point2.ToVector2() * 16f - screenPosition;
                    Microsoft.Xna.Framework.Rectangle value42 = new Microsoft.Xna.Framework.Rectangle(0, 0, 16, 16);
                    if (flag30)
                    {
                        EntitySpriteDraw(TextureAssets.WireUi[11].Value, position8, null, color63, 0f, Vector2.Zero, 1f, SpriteEffects.None);
                    }
                    EntitySpriteDraw(TextureAssets.Projectile[proj.type].Value, position8, value42, color64, 0f, Vector2.Zero, 1f, SpriteEffects.None);
                    value42.Y = 18;
                    EntitySpriteDraw(TextureAssets.Projectile[proj.type].Value, position8, value42, color63, 0f, Vector2.Zero, 1f, SpriteEffects.None);
                    return;
                }
                if (point.X == point2.X)
                {
                    int num225 = point2.Y - point.Y;
                    int num226 = Math.Sign(num225);
                    Vector2 position9 = point.ToVector2() * 16f - screenPosition;
                    Microsoft.Xna.Framework.Rectangle value43 = new Microsoft.Xna.Framework.Rectangle((num225 * num223 > 0) ? 72 : 18, 0, 16, 16);
                    if (flag30)
                    {
                        EntitySpriteDraw(TextureAssets.WireUi[11].Value, position9, null, color63, 0f, Vector2.Zero, 1f, SpriteEffects.None);
                    }
                    EntitySpriteDraw(TextureAssets.Projectile[proj.type].Value, position9, value43, color64, 0f, Vector2.Zero, 1f, SpriteEffects.None);
                    value43.Y = 18;
                    EntitySpriteDraw(TextureAssets.Projectile[proj.type].Value, position9, value43, color63, 0f, Vector2.Zero, 1f, SpriteEffects.None);
                    for (int num227 = point.Y + num226; num227 != point2.Y; num227 += num226)
                    {
                        position9 = new Vector2(point.X * 16, num227 * 16) - screenPosition;
                        value43.Y = 0;
                        value43.X = 90;
                        if (flag30)
{
                            EntitySpriteDraw(TextureAssets.WireUi[11].Value, position9, null, color63, 0f, Vector2.Zero, 1f, SpriteEffects.None);
                        }
                        EntitySpriteDraw(TextureAssets.Projectile[proj.type].Value, position9, value43, color64, 0f, Vector2.Zero, 1f, SpriteEffects.None);
                        value43.Y = 18;
                        EntitySpriteDraw(TextureAssets.Projectile[proj.type].Value, position9, value43, color63, 0f, Vector2.Zero, 1f, SpriteEffects.None);
                    }
                    position9 = point2.ToVector2() * 16f - screenPosition;
                    value43 = new Microsoft.Xna.Framework.Rectangle((num225 * num223 > 0) ? 18 : 72, 0, 16, 16);
                    if (flag30)
                    {
                        EntitySpriteDraw(TextureAssets.WireUi[11].Value, position9, null, color63, 0f, Vector2.Zero, 1f, SpriteEffects.None);
                    }
                    EntitySpriteDraw(TextureAssets.Projectile[proj.type].Value, position9, value43, color64, 0f, Vector2.Zero, 1f, SpriteEffects.None);
                    value43.Y = 18;
                    EntitySpriteDraw(TextureAssets.Projectile[proj.type].Value, position9, value43, color63, 0f, Vector2.Zero, 1f, SpriteEffects.None);
                    return;
                }
                if (point.Y == point2.Y)
                {
                    int num228 = point2.X - point.X;
                    int num229 = Math.Sign(num228);
                    Vector2 position10 = point.ToVector2() * 16f - screenPosition;
                    Microsoft.Xna.Framework.Rectangle value44 = new Microsoft.Xna.Framework.Rectangle((num228 > 0) ? 36 : 144, 0, 16, 16);
                    if (flag30)
                    {
                        EntitySpriteDraw(TextureAssets.WireUi[11].Value, position10, null, color63, 0f, Vector2.Zero, 1f, SpriteEffects.None);
                    }
                    EntitySpriteDraw(TextureAssets.Projectile[proj.type].Value, position10, value44, color64, 0f, Vector2.Zero, 1f, SpriteEffects.None);
                    value44.Y = 18;
                    EntitySpriteDraw(TextureAssets.Projectile[proj.type].Value, position10, value44, color63, 0f, Vector2.Zero, 1f, SpriteEffects.None);
                    for (int num230 = point.X + num229; num230 != point2.X; num230 += num229)
                    {
                        position10 = new Vector2(num230 * 16, point.Y * 16) - screenPosition;
                        value44.Y = 0;
                        value44.X = 180;
                        if (flag30)
{
                            EntitySpriteDraw(TextureAssets.WireUi[11].Value, position10, null, color63, 0f, Vector2.Zero, 1f, SpriteEffects.None);
                        }
                        EntitySpriteDraw(TextureAssets.Projectile[proj.type].Value, position10, value44, color64, 0f, Vector2.Zero, 1f, SpriteEffects.None);
                        value44.Y = 18;
                        EntitySpriteDraw(TextureAssets.Projectile[proj.type].Value, position10, value44, color63, 0f, Vector2.Zero, 1f, SpriteEffects.None);
                    }
                    position10 = point2.ToVector2() * 16f - screenPosition;
                    value44 = new Microsoft.Xna.Framework.Rectangle((num228 > 0) ? 144 : 36, 0, 16, 16);
                    if (flag30)
                    {
                        EntitySpriteDraw(TextureAssets.WireUi[11].Value, position10, null, color63, 0f, Vector2.Zero, 1f, SpriteEffects.None);
                    }
                    EntitySpriteDraw(TextureAssets.Projectile[proj.type].Value, position10, value44, color64, 0f, Vector2.Zero, 1f, SpriteEffects.None);
                    value44.Y = 18;
                    EntitySpriteDraw(TextureAssets.Projectile[proj.type].Value, position10, value44, color63, 0f, Vector2.Zero, 1f, SpriteEffects.None);
                    return;
                }
                Math.Abs(point.X - point2.X);
                Math.Abs(point.Y - point2.Y);
                int num231 = Math.Sign(point2.X - point.X);
                int num232 = Math.Sign(point2.Y - point.Y);
                Microsoft.Xna.Framework.Point p = default(Microsoft.Xna.Framework.Point);
                bool flag31 = false;
                bool flag32 = player3.direction == 1;
                int num233;
                int num234;
                int num235;
                if (flag32)
                {
                    p.X = point.X;
                    num233 = point.Y;
                    num234 = point2.Y;
                    num235 = num232;
                }
                else
                {
                    p.Y = point.Y;
                    num233 = point.X;
                    num234 = point2.X;
                    num235 = num231;
                }
                Vector2 position11 = point.ToVector2() * 16f - screenPosition;
                Microsoft.Xna.Framework.Rectangle value45 = new Microsoft.Xna.Framework.Rectangle(0, 0, 16, 16);
                if (!flag32)
                {
                    value45.X = ((num235 > 0) ? 36 : 144);
                }
                else
                {
                    value45.X = ((num235 > 0) ? 72 : 18);
                }
                if (flag30)
                {
                    EntitySpriteDraw(TextureAssets.WireUi[11].Value, position11, null, color63, 0f, Vector2.Zero, 1f, SpriteEffects.None);
                }
                EntitySpriteDraw(TextureAssets.Projectile[proj.type].Value, position11, value45, color64, 0f, Vector2.Zero, 1f, SpriteEffects.None);
                value45.Y = 18;
                EntitySpriteDraw(TextureAssets.Projectile[proj.type].Value, position11, value45, color63, 0f, Vector2.Zero, 1f, SpriteEffects.None);
                for (int num236 = num233 + num235; num236 != num234; num236 += num235)
                {
                    if (flag31)
                    {
                        break;
                    }
                    if (flag32)
                    {
                        p.Y = num236;
                    }
                    else
                    {
                        p.X = num236;
                    }
                    if (WorldGen.InWorld(p.X, p.Y, 1) && tile[p.X, p.Y] != null)
                    {
                        position11 = p.ToVector2() * 16f - screenPosition;
                        value45.Y = 0;
                        if (!flag32)
{
                            value45.X = 180;
                        }
                        else
{
                            value45.X = 90;
                        }
                        if (flag30)
{
                            EntitySpriteDraw(TextureAssets.WireUi[11].Value, position11, null, color63, 0f, Vector2.Zero, 1f, SpriteEffects.None);
                        }
                        EntitySpriteDraw(TextureAssets.Projectile[proj.type].Value, position11, value45, color64, 0f, Vector2.Zero, 1f, SpriteEffects.None);
                        value45.Y = 18;
                        EntitySpriteDraw(TextureAssets.Projectile[proj.type].Value, position11, value45, color63, 0f, Vector2.Zero, 1f, SpriteEffects.None);
                    }
                }
                if (flag32)
                {
                    p.Y = point2.Y;
                    num233 = point.X;
                    num234 = point2.X;
                    num235 = num231;
                }
                else
                {
                    p.X = point2.X;
                    num233 = point.Y;
                    num234 = point2.Y;
                    num235 = num232;
                }
                position11 = p.ToVector2() * 16f - screenPosition;
                value45 = new Microsoft.Xna.Framework.Rectangle(0, 0, 16, 16);
                if (!flag32)
                {
                    value45.X += ((num231 > 0) ? 144 : 36);
                    value45.X += ((num232 * num223 > 0) ? 72 : 18);
                }
                else
                {
                    value45.X += ((num231 > 0) ? 36 : 144);
                    value45.X += ((num232 * num223 > 0) ? 18 : 72);
                }
                if (flag30)
                {
                    EntitySpriteDraw(TextureAssets.WireUi[11].Value, position11, null, color63, 0f, Vector2.Zero, 1f, SpriteEffects.None);
                }
                EntitySpriteDraw(TextureAssets.Projectile[proj.type].Value, position11, value45, color64, 0f, Vector2.Zero, 1f, SpriteEffects.None);
                value45.Y = 18;
                EntitySpriteDraw(TextureAssets.Projectile[proj.type].Value, position11, value45, color63, 0f, Vector2.Zero, 1f, SpriteEffects.None);
                for (int num237 = num233 + num235; num237 != num234; num237 += num235)
                {
                    if (flag31)
                    {
                        break;
                    }
                    if (!flag32)
                    {
                        p.Y = num237;
                    }
                    else
                    {
                        p.X = num237;
                    }
                    if (WorldGen.InWorld(p.X, p.Y, 1) && tile[p.X, p.Y] != null)
                    {
                        position11 = p.ToVector2() * 16f - screenPosition;
                        value45.Y = 0;
                        if (!flag32)
{
                            value45.X = 90;
                        }
                        else
{
                            value45.X = 180;
                        }
                        if (flag30)
{
                            EntitySpriteDraw(TextureAssets.WireUi[11].Value, position11, null, color63, 0f, Vector2.Zero, 1f, SpriteEffects.None);
                        }
                        EntitySpriteDraw(TextureAssets.Projectile[proj.type].Value, position11, value45, color64, 0f, Vector2.Zero, 1f, SpriteEffects.None);
                        value45.Y = 18;
                        EntitySpriteDraw(TextureAssets.Projectile[proj.type].Value, position11, value45, color63, 0f, Vector2.Zero, 1f, SpriteEffects.None);
                    }
                }
                position11 = point2.ToVector2() * 16f - screenPosition;
                value45 = new Microsoft.Xna.Framework.Rectangle(0, 0, 16, 16);
                if (!flag32)
                {
                    value45.X += ((num232 * num223 > 0) ? 18 : 72);
                }
                else
                {
                    value45.X += ((num231 > 0) ? 144 : 36);
                }
                if (flag30)
                {
                    EntitySpriteDraw(TextureAssets.WireUi[11].Value, position11, null, color63, 0f, Vector2.Zero, 1f, SpriteEffects.None);
                }
                EntitySpriteDraw(TextureAssets.Projectile[proj.type].Value, position11, value45, color64, 0f, Vector2.Zero, 1f, SpriteEffects.None);
                value45.Y = 18;
                EntitySpriteDraw(TextureAssets.Projectile[proj.type].Value, position11, value45, color63, 0f, Vector2.Zero, 1f, SpriteEffects.None);
                return;
            }
            if (proj.type == 586)
            {
                float num238 = 300f;
                if (proj.ai[0] >= 100f)
                {
                    num238 = MathHelper.Lerp(300f, 600f, (proj.ai[0] - 100f) / 200f);
                }
                if (num238 > 600f)
                {
                    num238 = 600f;
                }
                if (proj.ai[0] >= 500f)
                {
                    num238 = MathHelper.Lerp(600f, 1200f, (proj.ai[0] - 500f) / 100f);
                }
                float rotation24 = proj.rotation;
                Texture2D value46 = TextureAssets.Projectile[proj.type].Value;
                int num239 = (int)(proj.ai[0] / 6f);
                Vector2 spinningpoint3 = new Vector2(0f, 0f - num238);
                for (int num240 = 0; (float)num240 < 10f; num240++)
                {
                    Microsoft.Xna.Framework.Rectangle rectangle9 = value46.Frame(1, 5, 0, (num239 + num240) % 5);
                    float num241 = rotation24 + (float)Math.PI / 5f * (float)num240;
                    Vector2 vector50 = spinningpoint3.RotatedBy(num241) / 3f + proj.Center;
                    Microsoft.Xna.Framework.Color alpha7 = proj.GetAlpha(Lighting.GetColor(vector50.ToTileCoordinates()));
                    alpha7.A /= 2;
                    EntitySpriteDraw(value46, vector50 - screenPosition, rectangle9, alpha7, num241, rectangle9.Size() / 2f, proj.scale, SpriteEffects.None);
                }
                for (int num242 = 0; (float)num242 < 20f; num242++)
                {
                    Microsoft.Xna.Framework.Rectangle rectangle10 = value46.Frame(1, 5, 0, (num239 + num242) % 5);
                    float num243 = 0f - rotation24 + (float)Math.PI / 10f * (float)num242;
                    num243 *= 2f;
                    Vector2 vector51 = spinningpoint3.RotatedBy(num243) + proj.Center;
                    Microsoft.Xna.Framework.Color alpha7 = proj.GetAlpha(Lighting.GetColor(vector51.ToTileCoordinates()));
                    alpha7.A /= 2;
                    EntitySpriteDraw(value46, vector51 - screenPosition, rectangle10, alpha7, num243, rectangle10.Size() / 2f, proj.scale, SpriteEffects.None);
                }
                return;
            }
            if (proj.type == 536 || proj.type == 607)
            {
                Texture2D value47 = TextureAssets.Projectile[proj.type].Value;
                Vector2 position12 = proj.position + new Vector2(proj.width, proj.height) / 2f + Vector2.UnitY * proj.gfxOffY - screenPosition;
                EntitySpriteDraw(scale: new Vector2(1f, proj.velocity.Length() / (float)value47.Height), texture: value47, position: position12, sourceRectangle: null, color: proj.GetAlpha(projectileColor), rotation: proj.rotation, origin: value47.Frame().Bottom(), effects: dir);
                return;
            }
            if (proj.type == 591)
            {
                Texture2D value48 = TextureAssets.Projectile[proj.type].Value;
                Vector2 position13 = proj.position + new Vector2(proj.width, proj.height) / 2f + Vector2.UnitY * proj.gfxOffY - screenPosition;
                Vector2 scale4 = new Vector2(1f, proj.velocity.Length() / (float)value48.Height);
                LoadNPC(139);
                Texture2D value49 = TextureAssets.Npc[139].Value;
                bool num244 = proj.velocity.X >= 0f;
                float rotation25 = proj.velocity.ToRotation() + (float)Math.PI;
                SpriteEffects effects3 = (num244 ? SpriteEffects.FlipVertically : SpriteEffects.None);
                float fromValue = 1f - proj.Opacity;
                float num245 = Utils.Remap(fromValue, 0f, 0.2f, 0f, 1f) * Utils.Remap(fromValue, 0.2f, 1f, 1f, 0f);
                EntitySpriteDraw(value49, position13, null, projectileColor * num245, rotation25, value49.Size() / 2f, 0.65f, effects3);
                Microsoft.Xna.Framework.Color color65 = new Microsoft.Xna.Framework.Color(255, 189, 163, 127) * num245;
                Microsoft.Xna.Framework.Color color66 = new Microsoft.Xna.Framework.Color(255, 21, 21, 127) * num245;
                Microsoft.Xna.Framework.Rectangle rectangle11 = value48.Frame(2);
                Vector2 origin16 = rectangle11.Bottom();
                EntitySpriteDraw(value48, position13, rectangle11, color65, proj.rotation, origin16, scale4, dir);
                rectangle11 = value48.Frame(2, 1, 1);
                EntitySpriteDraw(value48, position13, rectangle11, color66, proj.rotation, origin16, scale4, dir);
                return;
            }
            if (proj.type == 688 || proj.type == 689 || proj.type == 690)
            {
                Texture2D value50 = TextureAssets.Projectile[proj.type].Value;
                Vector2 position14 = proj.Top + Vector2.UnitY * proj.gfxOffY - screenPosition;
                Microsoft.Xna.Framework.Rectangle rectangle12 = value50.Frame(1, projFrames[proj.type], 0, proj.frame);
                Vector2 origin17 = rectangle12.Size() * new Vector2(0.5f, 0f);
                Microsoft.Xna.Framework.Color color67 = Microsoft.Xna.Framework.Color.Lerp(proj.GetAlpha(projectileColor), Microsoft.Xna.Framework.Color.White, 0.5f);
                Microsoft.Xna.Framework.Color color68 = color67;
                color68.A = 127;
                Texture2D texture2D2 = null;
                Texture2D texture2D3 = null;
                switch (proj.type)
                {
                case 688:
                    texture2D2 = TextureAssets.GlowMask[228].Value;
                    texture2D3 = TextureAssets.Extra[86].Value;
                    break;
                case 689:
                    texture2D2 = TextureAssets.GlowMask[229].Value;
                    texture2D3 = TextureAssets.Extra[87].Value;
                    break;
                case 690:
                    texture2D2 = TextureAssets.GlowMask[230].Value;
                    texture2D3 = TextureAssets.Extra[88].Value;
                    break;
                }
                EntitySpriteDraw(value50, position14, rectangle12, color67, proj.rotation, origin17, proj.scale, dir);
                if (texture2D2 != null)
                {
                    EntitySpriteDraw(texture2D2, position14, rectangle12, color68, proj.rotation, origin17, proj.scale, dir);
                }
                if (texture2D3 != null)
                {
                    Vector2 position15 = proj.Center + Vector2.UnitY * proj.gfxOffY - screenPosition;
                    rectangle12 = texture2D3.Frame();
                    origin17 = rectangle12.Size() * new Vector2(0.5f, 1f);
                    origin17.Y -= 2f;
                    EntitySpriteDraw(texture2D3, position15, rectangle12, color67, proj.rotation, origin17, proj.scale, dir);
                }
                return;
            }
            if (proj.type == 694 || proj.type == 695 || proj.type == 696)
            {
                Texture2D value51 = TextureAssets.Projectile[proj.type].Value;
                Vector2 position16 = proj.Bottom + Vector2.UnitY * proj.gfxOffY - screenPosition;
                Microsoft.Xna.Framework.Rectangle rectangle13 = value51.Frame(1, projFrames[proj.type], 0, proj.frame);
                Vector2 origin18 = rectangle13.Size() * new Vector2(0.5f, 1f);
                origin18.Y -= 8f;
                int type = proj.type;
                if ((uint)(type - 694) <= 1u)
                {
                    origin18.X += 3f;
                }
                Microsoft.Xna.Framework.Color color69 = Microsoft.Xna.Framework.Color.Lerp(proj.GetAlpha(projectileColor), Microsoft.Xna.Framework.Color.White, 0f);
                EntitySpriteDraw(value51, position16, rectangle13, color69, proj.rotation, origin18, proj.scale, dir);
                EntitySpriteDraw(value51, position16, rectangle13, color69 * 0.3f, proj.rotation, origin18, proj.scale * 1.1f, dir);
                return;
            }
            if (proj.type == 409)
            {
                Texture2D value52 = TextureAssets.Projectile[proj.type].Value;
                int num246 = TextureAssets.Projectile[proj.type].Height() / projFrames[proj.type];
                int y14 = num246 * proj.frame;
                int num247 = 10;
                int num248 = 2;
                float value53 = 0.5f;
                for (int num249 = 1; num249 < num247; num249 += num248)
                {
                    _ = ref proj.oldPos[num249];
                    Microsoft.Xna.Framework.Color newColor = projectileColor;
                    newColor = proj.GetAlpha(newColor);
                    newColor *= (float)(num247 - num249) / 15f;
                    _ = proj.oldPos[num249] - screenPosition + new Vector2(num138 + (float)num137, (float)(proj.height / 2) + proj.gfxOffY);
                    EntitySpriteDraw(value52, proj.oldPos[num249] + new Vector2(proj.width, proj.height) / 2f - screenPosition + new Vector2(0f, proj.gfxOffY), new Microsoft.Xna.Framework.Rectangle(0, y14, value52.Width, num246), newColor, proj.rotation, new Vector2((float)value52.Width / 2f, (float)num246 / 2f), MathHelper.Lerp(proj.scale, value53, (float)num249 / 15f), dir);
                }
                EntitySpriteDraw(value52, proj.Center - screenPosition + new Vector2(0f, proj.gfxOffY), new Microsoft.Xna.Framework.Rectangle(0, y14, value52.Width, num246), proj.GetAlpha(projectileColor), proj.rotation, new Vector2((float)value52.Width / 2f, (float)num246 / 2f), proj.scale, dir);
                return;
            }
            if (proj.type == 437)
            {
                Texture2D value54 = TextureAssets.Projectile[proj.type].Value;
                int num250 = TextureAssets.Projectile[proj.type].Height() / projFrames[proj.type];
                int y15 = num250 * proj.frame;
                int num251 = 10;
                int num252 = 2;
                float value55 = 0.2f;
                for (int num253 = 1; num253 < num251; num253 += num252)
                {
                    _ = ref proj.oldPos[num253];
                    Microsoft.Xna.Framework.Color newColor2 = projectileColor;
                    newColor2 = proj.GetAlpha(newColor2);
                    newColor2 *= (float)(num251 - num253) / 15f;
                    _ = proj.oldPos[num253] - screenPosition + new Vector2(num138 + (float)num137, (float)(proj.height / 2) + proj.gfxOffY);
                    EntitySpriteDraw(value54, proj.oldPos[num253] + new Vector2(proj.width, proj.height) / 2f - screenPosition + new Vector2(0f, proj.gfxOffY), new Microsoft.Xna.Framework.Rectangle(0, y15, value54.Width, num250), newColor2, proj.rotation, new Vector2((float)value54.Width / 2f, (float)num250 / 2f), MathHelper.Lerp(proj.scale, value55, (float)num253 / 15f), dir);
                }
                EntitySpriteDraw(value54, proj.Center - screenPosition + new Vector2(0f, proj.gfxOffY), new Microsoft.Xna.Framework.Rectangle(0, y15, value54.Width, num250), Microsoft.Xna.Framework.Color.White, proj.rotation, new Vector2((float)value54.Width / 2f, (float)num250 / 2f), proj.scale + 0.2f, dir);
                EntitySpriteDraw(value54, proj.Center - screenPosition + new Vector2(0f, proj.gfxOffY), new Microsoft.Xna.Framework.Rectangle(0, y15, value54.Width, num250), proj.GetAlpha(Microsoft.Xna.Framework.Color.White), proj.rotation, new Vector2((float)value54.Width / 2f, (float)num250 / 2f), proj.scale + 0.2f, dir);
                return;
            }
            if (proj.type == 384 || proj.type == 386)
            {
                Texture2D value56 = TextureAssets.Projectile[proj.type].Value;
                int num254 = TextureAssets.Projectile[proj.type].Height() / projFrames[proj.type];
                int y16 = num254 * proj.frame;
                EntitySpriteDraw(value56, proj.Center - screenPosition + new Vector2(0f, proj.gfxOffY), new Microsoft.Xna.Framework.Rectangle(0, y16, value56.Width, num254), proj.GetAlpha(projectileColor), proj.rotation, new Vector2((float)value56.Width / 2f, (float)num254 / 2f), proj.scale, dir);
                return;
            }
            if (proj.type == 439 || proj.type == 460 || proj.type == 600 || proj.type == 615 || proj.type == 630 || proj.type == 633 || proj.type == 705 || proj.type == 714)
            {
                Texture2D value57 = TextureAssets.Projectile[proj.type].Value;
                if (Main.player[proj.owner].gravDir == -1f)
                {
                    if (proj.type == 705)
                    {
                        dir |= SpriteEffects.FlipVertically;
                    }
                    if (proj.type == 615 || proj.type == 714)
                    {
                        if (Main.player[proj.owner].direction == 1)
{
                            dir = SpriteEffects.FlipVertically;
                        }
                        else if (Main.player[proj.owner].direction == -1)
{
                            dir = SpriteEffects.FlipHorizontally | SpriteEffects.FlipVertically;
                        }
                    }
                    else if (proj.type == 600 || proj.type == 439)
                    {
                        if (Main.player[proj.owner].direction == 1)
{
                            dir = SpriteEffects.FlipHorizontally;
                        }
                        else if (Main.player[proj.owner].direction == -1)
{
                            dir = SpriteEffects.None;
                        }
                    }
                }
                int num255 = TextureAssets.Projectile[proj.type].Height() / projFrames[proj.type];
                int y17 = num255 * proj.frame;
                Vector2 vector52 = (proj.position + new Vector2(proj.width, proj.height) / 2f + Vector2.UnitY * proj.gfxOffY - screenPosition).Floor();
                float num256 = 1f;
                if (Main.player[proj.owner].shroomiteStealth && Main.player[proj.owner].inventory[Main.player[proj.owner].selectedItem].ranged)
                {
                    float num257 = Main.player[proj.owner].stealth;
                    if ((double)num257 < 0.03)
                    {
                        num257 = 0.03f;
                    }
                    _ = (1f + num257 * 10f) / 11f;
                    projectileColor *= num257;
                    num256 = num257;
                }
                if (Main.player[proj.owner].setVortex && Main.player[proj.owner].inventory[Main.player[proj.owner].selectedItem].ranged)
                {
                    float num258 = Main.player[proj.owner].stealth;
                    if ((double)num258 < 0.03)
                    {
                        num258 = 0.03f;
                    }
                    _ = (1f + num258 * 10f) / 11f;
                    projectileColor = projectileColor.MultiplyRGBA(new Microsoft.Xna.Framework.Color(Vector4.Lerp(Vector4.One, new Vector4(0f, 0.12f, 0.16f, 0f), 1f - num258)));
                    num256 = num258;
                }
                if (proj.type == 714)
                {
                    y17 = 0;
                    instance.LoadItem(3930);
                    value57 = TextureAssets.Item[3930].Value;
                }
                EntitySpriteDraw(value57, vector52, new Microsoft.Xna.Framework.Rectangle(0, y17, value57.Width, num255), proj.GetAlpha(projectileColor), proj.rotation, new Vector2((float)value57.Width / 2f, (float)num255 / 2f), proj.scale, dir);
                if (proj.type == 439)
                {
                    EntitySpriteDraw(TextureAssets.GlowMask[35].Value, vector52, new Microsoft.Xna.Framework.Rectangle(0, y17, value57.Width, num255), new Microsoft.Xna.Framework.Color(255, 255, 255, 0) * num256, proj.rotation, new Vector2((float)value57.Width / 2f, (float)num255 / 2f), proj.scale, dir);
                }
                else if (proj.type == 714)
                {
                    y17 = num255 * proj.frame;
                    Microsoft.Xna.Framework.Color color70 = hslToRgb(proj.ai[0] / 90f % 1f, 1f, 0.5f);
                    color70.A = 120;
                    EntitySpriteDraw(TextureAssets.Projectile[proj.type].Value, vector52, new Microsoft.Xna.Framework.Rectangle(0, y17, value57.Width, num255), color70 * num256, proj.rotation, new Vector2((float)value57.Width / 2f, (float)num255 / 2f), proj.scale, dir);
                }
                else if (proj.type == 615)
                {
                    EntitySpriteDraw(TextureAssets.GlowMask[192].Value, vector52, new Microsoft.Xna.Framework.Rectangle(0, y17, value57.Width, num255), new Microsoft.Xna.Framework.Color(255, 255, 255, 127) * num256, proj.rotation, new Vector2((float)value57.Width / 2f, (float)num255 / 2f), proj.scale, dir);
                }
                else if (proj.type == 630)
                {
                    EntitySpriteDraw(TextureAssets.GlowMask[200].Value, vector52, new Microsoft.Xna.Framework.Rectangle(0, y17, value57.Width, num255), new Microsoft.Xna.Framework.Color(255, 255, 255, 127) * num256, proj.rotation, new Vector2((float)value57.Width / 2f, (float)num255 / 2f), proj.scale, dir);
                    if (proj.localAI[0] > 0f)
                    {
                        int frameY = 6 - (int)(proj.localAI[0] / 1f);
                        value57 = TextureAssets.Extra[65].Value;
                        EntitySpriteDraw(value57, vector52 + Vector2.Normalize(proj.velocity) * 2f, value57.Frame(1, 6, 0, frameY), new Microsoft.Xna.Framework.Color(255, 255, 255, 127) * num256, proj.rotation, new Vector2(dir.HasFlag(SpriteEffects.FlipHorizontally) ? value57.Width : 0, (float)num255 / 2f - 2f), proj.scale, dir);
                    }
                }
                else if (proj.type == 600)
                {
                    Microsoft.Xna.Framework.Color portalColor = PortalHelper.GetPortalColor(proj.owner, (int)proj.ai[1]);
                    portalColor.A = 70;
                    EntitySpriteDraw(TextureAssets.GlowMask[173].Value, vector52, new Microsoft.Xna.Framework.Rectangle(0, y17, value57.Width, num255), portalColor, proj.rotation, new Vector2((float)value57.Width / 2f, (float)num255 / 2f), proj.scale, dir);
                }
                else if (proj.type == 460)
                {
                    if (Math.Abs(proj.rotation - (float)Math.PI / 2f) > (float)Math.PI / 2f)
                    {
                        dir |= SpriteEffects.FlipVertically;
                    }
                    EntitySpriteDraw(TextureAssets.GlowMask[102].Value, vector52, new Microsoft.Xna.Framework.Rectangle(0, y17, value57.Width, num255), new Microsoft.Xna.Framework.Color(255, 255, 255, 0), proj.rotation - (float)Math.PI / 2f, new Vector2((float)value57.Width / 2f, (float)num255 / 2f), proj.scale, dir);
                    if (proj.ai[0] > 180f && Main.projectile[(int)proj.ai[1]].type == 461)
                    {
                        DrawProj((int)proj.ai[1]);
                    }
                }
                else if (proj.type == 633)
                {
                    float num259 = (float)Math.Cos((float)Math.PI * 2f * (proj.ai[0] / 30f)) * 2f + 2f;
                    if (proj.ai[0] > 120f)
                    {
                        num259 = 4f;
                    }
                    for (float num260 = 0f; num260 < 4f; num260 += 1f)
                    {
                        EntitySpriteDraw(value57, vector52 + Vector2.UnitY.RotatedBy(num260 * ((float)Math.PI * 2f) / 4f) * num259, new Microsoft.Xna.Framework.Rectangle(0, y17, value57.Width, num255), proj.GetAlpha(projectileColor).MultiplyRGBA(new Microsoft.Xna.Framework.Color(255, 255, 255, 0)) * 0.03f, proj.rotation, new Vector2((float)value57.Width / 2f, (float)num255 / 2f), proj.scale, dir);
                    }
                }
                return;
            }
            if (proj.type == 442)
            {
                Texture2D value58 = TextureAssets.Projectile[proj.type].Value;
                int num261 = TextureAssets.Projectile[proj.type].Height() / projFrames[proj.type];
                int y18 = num261 * proj.frame;
                Vector2 position17 = proj.position + new Vector2(proj.width, proj.height) / 2f + Vector2.UnitY * proj.gfxOffY - screenPosition;
                EntitySpriteDraw(value58, position17, new Microsoft.Xna.Framework.Rectangle(0, y18, value58.Width, num261), proj.GetAlpha(projectileColor), proj.rotation, new Vector2((float)value58.Width / 2f, (float)num261 / 2f), proj.scale, dir);
                EntitySpriteDraw(TextureAssets.GlowMask[37].Value, position17, new Microsoft.Xna.Framework.Rectangle(0, y18, value58.Width, num261), new Microsoft.Xna.Framework.Color(255, 255, 255, 0) * (1f - (float)proj.alpha / 255f), proj.rotation, new Vector2((float)value58.Width / 2f, (float)num261 / 2f), proj.scale, dir);
                return;
            }
            if (proj.type == 447)
            {
                Texture2D value59 = TextureAssets.Projectile[proj.type].Value;
                Texture2D value60 = TextureAssets.Extra[4].Value;
                int num262 = value59.Height / projFrames[proj.type];
                int y19 = num262 * proj.frame;
                int num263 = value60.Height / projFrames[proj.type];
                int num264 = num263 * proj.frame;
                Microsoft.Xna.Framework.Rectangle value61 = new Microsoft.Xna.Framework.Rectangle(0, num264, value60.Width, num263);
                Vector2 vector53 = proj.position + new Vector2(proj.width, 0f) / 2f + Vector2.UnitY * proj.gfxOffY - screenPosition;
                EntitySpriteDraw(TextureAssets.Extra[4].Value, vector53, value61, proj.GetAlpha(projectileColor), proj.rotation, new Vector2(value60.Width / 2, 0f), proj.scale, dir);
                int num265 = proj.height - num262 - 14;
                if (num265 < 0)
                {
                    num265 = 0;
                }
                if (num265 > 0)
                {
                    if (num264 == num263 * 3)
                    {
                        num264 = num263 * 2;
                    }
                    EntitySpriteDraw(TextureAssets.Extra[4].Value, vector53 + Vector2.UnitY * (num263 - 1), new Microsoft.Xna.Framework.Rectangle(0, num264 + num263 - 1, value60.Width, 1), proj.GetAlpha(projectileColor), proj.rotation, new Vector2(value60.Width / 2, 0f), new Vector2(1f, num265), dir);
                }
                value61.Width = value59.Width;
                value61.Y = y19;
                EntitySpriteDraw(value59, vector53 + Vector2.UnitY * (num263 - 1 + num265), value61, proj.GetAlpha(projectileColor), proj.rotation, new Vector2((float)value59.Width / 2f, 0f), proj.scale, dir);
                return;
            }
            if (proj.type == 455)
            {
                if (proj.velocity == Vector2.Zero)
                {
                    return;
                }
                Texture2D value62 = TextureAssets.Projectile[proj.type].Value;
                Texture2D value63 = TextureAssets.Extra[21].Value;
                Texture2D value64 = TextureAssets.Extra[22].Value;
                float num266 = proj.localAI[1];
                Microsoft.Xna.Framework.Color color71 = new Microsoft.Xna.Framework.Color(255, 255, 255, 0) * 0.9f;
                EntitySpriteDraw(value62, proj.Center - screenPosition, null, color71, proj.rotation, value62.Size() / 2f, proj.scale, SpriteEffects.None);
                num266 -= (float)(value62.Height / 2 + value64.Height) * proj.scale;
                Vector2 center3 = proj.Center;
                center3 += proj.velocity * proj.scale * value62.Height / 2f;
                if (num266 > 0f)
                {
                    float num267 = 0f;
                    Microsoft.Xna.Framework.Rectangle value65 = new Microsoft.Xna.Framework.Rectangle(0, 16 * (proj.timeLeft / 3 % 5), value63.Width, 16);
                    while (num267 + 1f < num266)
                    {
                        if (num266 - num267 < (float)value65.Height)
{
                            value65.Height = (int)(num266 - num267);
                        }
                        EntitySpriteDraw(value63, center3 - screenPosition, value65, color71, proj.rotation, new Vector2(value65.Width / 2, 0f), proj.scale, SpriteEffects.None);
                        num267 += (float)value65.Height * proj.scale;
                        center3 += proj.velocity * value65.Height * proj.scale;
                        value65.Y += 16;
                        if (value65.Y + value65.Height > value63.Height)
{
                            value65.Y = 0;
                        }
                    }
                }
                EntitySpriteDraw(value64, center3 - screenPosition, null, color71, proj.rotation, value64.Frame().Top(), proj.scale, SpriteEffects.None);
                return;
            }
            if (proj.type == 461)
            {
                if (proj.velocity == Vector2.Zero)
                {
                    return;
                }
                Texture2D value66 = TextureAssets.Projectile[proj.type].Value;
                float num268 = proj.localAI[1];
                Microsoft.Xna.Framework.Color color72 = new Microsoft.Xna.Framework.Color(255, 255, 255, 0) * 0.9f;
                Microsoft.Xna.Framework.Rectangle rectangle14 = new Microsoft.Xna.Framework.Rectangle(0, 0, value66.Width, 22);
                Vector2 vector54 = new Vector2(0f, Main.player[proj.owner].gfxOffY);
                EntitySpriteDraw(value66, proj.Center.Floor() - screenPosition + vector54, rectangle14, color72, proj.rotation, rectangle14.Size() / 2f, proj.scale, SpriteEffects.None);
                num268 -= 33f * proj.scale;
                Vector2 vector55 = proj.Center.Floor();
                vector55 += proj.velocity * proj.scale * 10.5f;
                rectangle14 = new Microsoft.Xna.Framework.Rectangle(0, 25, value66.Width, 28);
                if (num268 > 0f)
                {
                    float num269 = 0f;
                    while (num269 + 1f < num268)
                    {
                        if (num268 - num269 < (float)rectangle14.Height)
{
                            rectangle14.Height = (int)(num268 - num269);
                        }
                        EntitySpriteDraw(value66, vector55 - screenPosition + vector54, rectangle14, color72, proj.rotation, new Vector2(rectangle14.Width / 2, 0f), proj.scale, SpriteEffects.None);
                        num269 += (float)rectangle14.Height * proj.scale;
                        vector55 += proj.velocity * rectangle14.Height * proj.scale;
                    }
                }
                EntitySpriteDraw(sourceRectangle: new Microsoft.Xna.Framework.Rectangle(0, 56, value66.Width, 22), texture: value66, position: vector55 - screenPosition + vector54, color: color72, rotation: proj.rotation, origin: value66.Frame().Top(), scale: proj.scale, effects: SpriteEffects.None);
                return;
            }
            if (proj.type == 632)
            {
                if (!(proj.velocity == Vector2.Zero))
                {
                    Texture2D value67 = TextureAssets.Projectile[proj.type].Value;
                    float num270 = proj.localAI[1];
                    float laserLuminance = 0.5f;
                    float laserAlphaMultiplier = 0f;
                    Microsoft.Xna.Framework.Color color73 = hslToRgb(proj.GetLastPrismHue(proj.ai[0], ref laserLuminance, ref laserAlphaMultiplier), 1f, laserLuminance);
                    color73.A = (byte)((float)(int)color73.A * laserAlphaMultiplier);
                    Vector2 vector56 = proj.Center.Floor();
                    vector56 += proj.velocity * proj.scale * 10.5f;
                    num270 -= proj.scale * 14.5f * proj.scale;
                    Vector2 vector57 = new Vector2(proj.scale);
                    DelegateMethods.f_1 = 1f;
                    DelegateMethods.c_1 = color73 * 0.75f * proj.Opacity;
                    _ = proj.oldPos[0] + new Vector2(proj.width, proj.height) / 2f + Vector2.UnitY * proj.gfxOffY - screenPosition;
                    Utils.DrawLaser(spriteBatch, value67, vector56 - screenPosition, vector56 + proj.velocity * num270 - screenPosition, vector57, DelegateMethods.RainbowLaserDraw);
                    DelegateMethods.c_1 = new Microsoft.Xna.Framework.Color(255, 255, 255, 127) * 0.75f * proj.Opacity;
                    Utils.DrawLaser(spriteBatch, value67, vector56 - screenPosition, vector56 + proj.velocity * num270 - screenPosition, vector57 / 2f, DelegateMethods.RainbowLaserDraw);
                }
                return;
            }
            if (proj.type == 642)
            {
                if (!(proj.velocity == Vector2.Zero))
                {
                    Texture2D value68 = TextureAssets.Projectile[proj.type].Value;
                    float num271 = proj.localAI[1];
                    Microsoft.Xna.Framework.Color c_ = new Microsoft.Xna.Framework.Color(255, 255, 255, 127);
                    Vector2 vector58 = proj.Center.Floor();
                    num271 -= proj.scale * 10.5f;
                    Vector2 vector59 = new Vector2(proj.scale);
                    DelegateMethods.f_1 = 1f;
                    DelegateMethods.c_1 = c_;
                    DelegateMethods.i_1 = 54000 - (int)time / 2;
                    _ = proj.oldPos[0] + new Vector2(proj.width, proj.height) / 2f + Vector2.UnitY * proj.gfxOffY - screenPosition;
                    Utils.DrawLaser(spriteBatch, value68, vector58 - screenPosition, vector58 + proj.velocity * num271 - screenPosition, vector59, DelegateMethods.TurretLaserDraw);
                    DelegateMethods.c_1 = new Microsoft.Xna.Framework.Color(255, 255, 255, 127) * 0.75f * proj.Opacity;
                    Utils.DrawLaser(spriteBatch, value68, vector58 - screenPosition, vector58 + proj.velocity * num271 - screenPosition, vector59 / 2f, DelegateMethods.TurretLaserDraw);
                }
                return;
            }
            if (proj.type == 611)
            {
                _ = proj.position + new Vector2(proj.width, proj.height) / 2f + Vector2.UnitY * proj.gfxOffY - screenPosition;
                Texture2D value69 = TextureAssets.Projectile[proj.type].Value;
                Microsoft.Xna.Framework.Color alpha8 = proj.GetAlpha(projectileColor);
                if (proj.velocity == Vector2.Zero)
                {
                    return;
                }
                float num272 = proj.velocity.Length() + 16f;
                bool flag33 = num272 < 100f;
                Vector2 vector60 = Vector2.Normalize(proj.velocity);
                Microsoft.Xna.Framework.Rectangle rectangle15 = new Microsoft.Xna.Framework.Rectangle(0, 2, value69.Width, 40);
                Vector2 vector61 = new Vector2(0f, Main.player[proj.owner].gfxOffY);
                float rotation26 = proj.rotation + (float)Math.PI;
                EntitySpriteDraw(value69, proj.Center.Floor() - screenPosition + vector61, rectangle15, alpha8, rotation26, rectangle15.Size() / 2f - Vector2.UnitY * 4f, proj.scale, SpriteEffects.None);
                num272 -= 40f * proj.scale;
                Vector2 vector62 = proj.Center.Floor();
                vector62 += vector60 * proj.scale * 24f;
                rectangle15 = new Microsoft.Xna.Framework.Rectangle(0, 68, value69.Width, 18);
                if (num272 > 0f)
                {
                    float num273 = 0f;
                    while (num273 + 1f < num272)
                    {
                        if (num272 - num273 < (float)rectangle15.Height)
{
                            rectangle15.Height = (int)(num272 - num273);
                        }
                        EntitySpriteDraw(value69, vector62 - screenPosition + vector61, rectangle15, alpha8, rotation26, new Vector2(rectangle15.Width / 2, 0f), proj.scale, SpriteEffects.None);
                        num273 += (float)rectangle15.Height * proj.scale;
                        vector62 += vector60 * rectangle15.Height * proj.scale;
                    }
                }
                Vector2 vector63 = vector62;
                vector62 = proj.Center.Floor();
                vector62 += vector60 * proj.scale * 24f;
                rectangle15 = new Microsoft.Xna.Framework.Rectangle(0, 46, value69.Width, 18);
                int num274 = 18;
                if (flag33)
                {
                    num274 = 9;
                }
                float num275 = num272;
                if (num272 > 0f)
                {
                    float num276 = 0f;
                    float num277 = num275 / (float)num274;
                    num276 += num277 * 0.25f;
                    vector62 += vector60 * num277 * 0.25f;
                    for (int num278 = 0; num278 < num274; num278++)
                    {
                        float num279 = num277;
                        if (num278 == 0)
{
                            num279 *= 0.75f;
                        }
                        EntitySpriteDraw(value69, vector62 - screenPosition + vector61, rectangle15, alpha8, rotation26, new Vector2(rectangle15.Width / 2, 0f), proj.scale, SpriteEffects.None);
                        num276 += num279;
                        vector62 += vector60 * num279;
                    }
                }
                EntitySpriteDraw(sourceRectangle: new Microsoft.Xna.Framework.Rectangle(0, 90, value69.Width, 48), texture: value69, position: vector63 - screenPosition + vector61, color: alpha8, rotation: rotation26, origin: value69.Frame().Top(), scale: proj.scale, effects: SpriteEffects.None);
                return;
            }
            if (proj.type == 537)
            {
                if (proj.velocity == Vector2.Zero)
                {
                    return;
                }
                Texture2D value70 = TextureAssets.Projectile[proj.type].Value;
                float num280 = proj.localAI[1];
                float fromValue2 = Utils.Remap(proj.localAI[0], 20f, 30f, 0f, 1f) * Utils.Remap(proj.localAI[0], 60f, 90f, 1f, 0f);
                float toMax = 1.5f;
                float num281 = Utils.Remap(fromValue2, 0f, 1f, 0.25f, toMax);
                Microsoft.Xna.Framework.Color color74 = new Microsoft.Xna.Framework.Color(255, 255, 255, 0) * 0.9f;
                Microsoft.Xna.Framework.Rectangle rectangle16 = new Microsoft.Xna.Framework.Rectangle(0, 0, value70.Width, 22);
                Vector2 vector64 = new Vector2(0f, npc[(int)proj.ai[1]].gfxOffY);
                EntitySpriteDraw(value70, proj.Center.Floor() - screenPosition + vector64, rectangle16, color74, proj.rotation, rectangle16.Size() / 2f, num281, SpriteEffects.None);
                num280 -= 33f * proj.scale;
                Vector2 vector65 = proj.Center.Floor();
                vector65 += proj.velocity * num281 * 10.5f;
                rectangle16 = new Microsoft.Xna.Framework.Rectangle(0, 25, value70.Width, 28);
                if (num280 > 0f)
                {
                    float num282 = 0f;
                    while (num282 + 1f < num280)
                    {
                        if (num280 - num282 < (float)rectangle16.Height)
{
                            rectangle16.Height = (int)(num280 - num282);
                        }
                        EntitySpriteDraw(value70, vector65 - screenPosition + vector64, rectangle16, color74, proj.rotation, new Vector2(rectangle16.Width / 2, 0f), num281, SpriteEffects.None);
                        num282 += (float)rectangle16.Height * num281;
                        vector65 += proj.velocity * rectangle16.Height * num281;
                    }
                }
                EntitySpriteDraw(sourceRectangle: new Microsoft.Xna.Framework.Rectangle(0, 56, value70.Width, 22), texture: value70, position: vector65 - screenPosition + vector64, color: color74, rotation: proj.rotation, origin: value70.Frame().Top(), scale: num281, effects: SpriteEffects.None);
                return;
            }
            if (proj.type == 456)
            {
                Texture2D value71 = TextureAssets.Projectile[proj.type].Value;
                Texture2D value72 = TextureAssets.Extra[23].Value;
                Texture2D value73 = TextureAssets.Extra[24].Value;
                Vector2 vector66 = new Vector2(0f, 216f);
                Vector2 value74 = npc[(int)Math.Abs(proj.ai[0]) - 1].Center - proj.Center + vector66;
                float num283 = value74.Length();
                Vector2 vector67 = Vector2.Normalize(value74);
                Microsoft.Xna.Framework.Rectangle rectangle17 = value71.Frame();
                rectangle17.Height /= 4;
                rectangle17.Y += proj.frame * rectangle17.Height;
                EntitySpriteDraw(color: proj.GetAlpha(Microsoft.Xna.Framework.Color.Lerp(projectileColor, Microsoft.Xna.Framework.Color.White, 0.3f)), texture: value71, position: proj.Center - screenPosition, sourceRectangle: rectangle17, rotation: proj.rotation, origin: rectangle17.Size() / 2f, scale: proj.scale, effects: SpriteEffects.None);
                num283 -= (float)(rectangle17.Height / 2 + value73.Height) * proj.scale;
                Vector2 center4 = proj.Center;
                center4 += vector67 * proj.scale * rectangle17.Height / 2f;
                if (num283 > 0f)
                {
                    float num284 = 0f;
                    Microsoft.Xna.Framework.Rectangle rectangle18 = new Microsoft.Xna.Framework.Rectangle(0, 0, value72.Width, value72.Height);
                    while (num284 + 1f < num283)
                    {
                        if (num283 - num284 < (float)rectangle18.Height)
{
                            rectangle18.Height = (int)(num283 - num284);
                        }
                        Microsoft.Xna.Framework.Point point3 = center4.ToTileCoordinates();
                        Microsoft.Xna.Framework.Color color75 = Lighting.GetColor(point3.X, point3.Y);
                        color75 = Microsoft.Xna.Framework.Color.Lerp(color75, Microsoft.Xna.Framework.Color.White, 0.3f);
                        EntitySpriteDraw(value72, center4 - screenPosition, rectangle18, proj.GetAlpha(color75), proj.rotation, rectangle18.Bottom(), proj.scale, SpriteEffects.None);
                        num284 += (float)rectangle18.Height * proj.scale;
                        center4 += vector67 * rectangle18.Height * proj.scale;
                    }
                }
                Microsoft.Xna.Framework.Point point4 = center4.ToTileCoordinates();
                Microsoft.Xna.Framework.Color color76 = Lighting.GetColor(point4.X, point4.Y);
                color76 = Microsoft.Xna.Framework.Color.Lerp(color76, Microsoft.Xna.Framework.Color.White, 0.3f);
                Microsoft.Xna.Framework.Rectangle value75 = value73.Frame();
                if (num283 < 0f)
                {
                    value75.Height += (int)num283;
                }
                EntitySpriteDraw(value73, center4 - screenPosition, value75, color76, proj.rotation, new Vector2((float)value75.Width / 2f, value75.Height), proj.scale, SpriteEffects.None);
                return;
            }
            if (proj.type == 443)
            {
                Texture2D value76 = TextureAssets.Projectile[proj.type].Value;
                float num285 = 30f;
                float num286 = num285 * 4f;
                float num287 = (float)Math.PI * 2f * proj.ai[0] / num285;
                float num288 = (float)Math.PI * 2f * proj.ai[0] / num286;
                Vector2 vector68 = -Vector2.UnitY.RotatedBy(num287);
                float scale5 = 0.75f + vector68.Y * 0.25f;
                float scale6 = 0.8f - vector68.Y * 0.2f;
                int num289 = TextureAssets.Projectile[proj.type].Height() / projFrames[proj.type];
                int y20 = num289 * proj.frame;
                Vector2 position18 = proj.position + new Vector2(proj.width, proj.height) / 2f + Vector2.UnitY * proj.gfxOffY - screenPosition;
                EntitySpriteDraw(value76, position18, new Microsoft.Xna.Framework.Rectangle(0, y20, value76.Width, num289), proj.GetAlpha(projectileColor), proj.rotation + num288, new Vector2((float)value76.Width / 2f, (float)num289 / 2f), scale5, dir);
                EntitySpriteDraw(value76, position18, new Microsoft.Xna.Framework.Rectangle(0, y20, value76.Width, num289), proj.GetAlpha(projectileColor), proj.rotation + ((float)Math.PI * 2f - num288), new Vector2((float)value76.Width / 2f, (float)num289 / 2f), scale6, dir);
                return;
            }
            if (proj.type == 656 || proj.type == 657)
            {
                float num290 = 900f;
                if (proj.type == 657)
                {
                    num290 = 300f;
                }
                float num291 = 15f;
                float num292 = 15f;
                float num293 = proj.ai[0];
                float num294 = MathHelper.Clamp(num293 / 30f, 0f, 1f);
                if (num293 > num290 - 60f)
                {
                    num294 = MathHelper.Lerp(1f, 0f, (num293 - (num290 - 60f)) / 60f);
                }
                Microsoft.Xna.Framework.Point point5 = proj.Center.ToTileCoordinates();
                Collision.ExpandVertically(point5.X, point5.Y, out var topY, out var bottomY, (int)num291, (int)num292);
                topY++;
                bottomY--;
                float num295 = 0.2f;
                Vector2 value77 = new Vector2(point5.X, topY) * 16f + new Vector2(8f);
                Vector2 value78 = new Vector2(point5.X, bottomY) * 16f + new Vector2(8f);
                Vector2.Lerp(value77, value78, 0.5f);
                Vector2 vector69 = new Vector2(0f, value78.Y - value77.Y);
                vector69.X = vector69.Y * num295;
                new Vector2(value77.X - vector69.X / 2f, value77.Y);
                Texture2D value79 = TextureAssets.Projectile[proj.type].Value;
                Microsoft.Xna.Framework.Rectangle rectangle19 = value79.Frame();
                Vector2 origin19 = rectangle19.Size() / 2f;
                float num296 = -(float)Math.PI / 50f * num293;
                Vector2 spinningpoint4 = Vector2.UnitY.RotatedBy(num293 * 0.1f);
                float num297 = 0f;
                float num298 = 5.1f;
                Microsoft.Xna.Framework.Color value80 = new Microsoft.Xna.Framework.Color(212, 192, 100);
                for (float num299 = (int)value78.Y; num299 > (float)(int)value77.Y; num299 -= num298)
                {
                    num297 += num298;
                    float num300 = num297 / vector69.Y;
                    float num301 = num297 * ((float)Math.PI * 2f) / -20f;
                    float num302 = num300 - 0.15f;
                    Vector2 position19 = spinningpoint4.RotatedBy(num301);
                    Vector2 vector70 = new Vector2(0f, num300 + 1f);
                    vector70.X = vector70.Y * num295;
                    Microsoft.Xna.Framework.Color color77 = Microsoft.Xna.Framework.Color.Lerp(Microsoft.Xna.Framework.Color.Transparent, value80, num300 * 2f);
                    if (num300 > 0.5f)
                    {
                        color77 = Microsoft.Xna.Framework.Color.Lerp(Microsoft.Xna.Framework.Color.Transparent, value80, 2f - num300 * 2f);
                    }
                    color77.A = (byte)((float)(int)color77.A * 0.5f);
                    color77 *= num294;
                    position19 *= vector70 * 100f;
                    position19.Y = 0f;
                    position19.X = 0f;
                    position19 += new Vector2(value78.X, num299) - screenPosition;
                    EntitySpriteDraw(value79, position19, rectangle19, color77, num296 + num301, origin19, 1f + num302, SpriteEffects.None);
                }
                return;
            }
            if (proj.type == 704)
            {
                float num303 = 300f;
                float num304 = proj.ai[0];
                float num305 = MathHelper.Clamp(num304 / 30f, 0f, 1f);
                if (num304 > num303 - 60f)
                {
                    num305 = MathHelper.Lerp(1f, 0f, (num304 - (num303 - 60f)) / 60f);
                }
                float num306 = 0.2f;
                Vector2 top2 = proj.Top;
                Vector2 bottom = proj.Bottom;
                Vector2.Lerp(top2, bottom, 0.5f);
                Vector2 vector71 = new Vector2(0f, bottom.Y - top2.Y);
                vector71.X = vector71.Y * num306;
                new Vector2(top2.X - vector71.X / 2f, top2.Y);
                Texture2D value81 = TextureAssets.Projectile[proj.type].Value;
                Microsoft.Xna.Framework.Rectangle rectangle20 = value81.Frame();
                Vector2 origin20 = rectangle20.Size() / 2f;
                float num307 = -(float)Math.PI / 20f * num304 * (float)((!(proj.velocity.X > 0f)) ? 1 : (-1));
                SpriteEffects effects4 = ((proj.velocity.X > 0f) ? SpriteEffects.FlipVertically : SpriteEffects.None);
                bool flag34 = proj.velocity.X > 0f;
                Vector2 spinningpoint5 = Vector2.UnitY.RotatedBy(num304 * 0.14f);
                float num308 = 0f;
                float num309 = 5.01f + num304 / 150f * -0.9f;
                if (num309 < 4.11f)
                {
                    num309 = 4.11f;
                }
                Microsoft.Xna.Framework.Color value82 = new Microsoft.Xna.Framework.Color(160, 140, 100, 127);
                Microsoft.Xna.Framework.Color color78 = new Microsoft.Xna.Framework.Color(140, 160, 255, 127);
                float num310 = num304 % 60f;
                if (num310 < 30f)
                {
                    color78 *= Utils.GetLerpValue(22f, 30f, num310, clamped: true);
                }
                else
                {
                    color78 *= Utils.GetLerpValue(38f, 30f, num310, clamped: true);
                }
                bool flag35 = color78 != Microsoft.Xna.Framework.Color.Transparent;
                for (float num311 = (int)bottom.Y; num311 > (float)(int)top2.Y; num311 -= num309)
                {
                    num308 += num309;
                    float num312 = num308 / vector71.Y;
                    float num313 = num308 * ((float)Math.PI * 2f) / -20f;
                    if (flag34)
                    {
                        num313 *= -1f;
                    }
                    float num314 = num312 - 0.35f;
                    Vector2 position20 = spinningpoint5.RotatedBy(num313);
                    Vector2 vector72 = new Vector2(0f, num312 + 1f);
                    vector72.X = vector72.Y * num306;
                    Microsoft.Xna.Framework.Color color79 = Microsoft.Xna.Framework.Color.Lerp(Microsoft.Xna.Framework.Color.Transparent, value82, num312 * 2f);
                    if (num312 > 0.5f)
                    {
                        color79 = Microsoft.Xna.Framework.Color.Lerp(Microsoft.Xna.Framework.Color.Transparent, value82, 2f - num312 * 2f);
                    }
                    color79.A = (byte)((float)(int)color79.A * 0.5f);
                    color79 *= num305;
                    position20 *= vector72 * 100f;
                    position20.Y = 0f;
                    position20.X = 0f;
                    position20 += new Vector2(bottom.X, num311) - screenPosition;
                    if (flag35)
                    {
                        Microsoft.Xna.Framework.Color color80 = Microsoft.Xna.Framework.Color.Lerp(Microsoft.Xna.Framework.Color.Transparent, color78, num312 * 2f);
                        if (num312 > 0.5f)
{
                            color80 = Microsoft.Xna.Framework.Color.Lerp(Microsoft.Xna.Framework.Color.Transparent, color78, 2f - num312 * 2f);
                        }
                        color80.A = (byte)((float)(int)color80.A * 0.5f);
                        color80 *= num305;
                        EntitySpriteDraw(value81, position20, rectangle20, color80, num307 + num313, origin20, (1f + num314) * 0.8f, effects4);
                    }
                    EntitySpriteDraw(value81, position20, rectangle20, color79, num307 + num313, origin20, 1f + num314, effects4);
                }
                return;
            }
            if (proj.type == 444 || proj.type == 446 || proj.type == 490 || proj.type == 464 || proj.type == 502 || proj.type == 538 || proj.type == 540 || proj.type == 579 || proj.type == 578 || proj.type == 813 || proj.type == 583 || proj.type == 584 || proj.type == 616 || proj.type == 617 || proj.type == 618 || proj.type == 641 || (proj.type >= 646 && proj.type <= 649) || proj.type == 653 || proj.type == 186 || proj.type == 662 || proj.type == 685 || proj.type == 673 || proj.type == 676 || proj.type == 697 || proj.type == 699 || proj.type == 707 || proj.type == 708 || proj.type == 719 || proj.type == 761 || proj.type == 762 || proj.type == 763 || proj.type == 772 || proj.type == 802 || proj.type == 842 || proj.type == 865 || proj.type == 921 || proj.type == 926 || proj.type == 757 || proj.type == 25 || proj.type == 35 || proj.type == 63 || proj.type == 154 || proj.type == 247 || proj.type == 26 || proj.type == 928 || proj.type == 16 || proj.type == 34 || proj.type == 79 || proj.type == 936 || proj.type == 937 || proj.type == 938 || proj.type == 939 || proj.type == 940 || proj.type == 941 || proj.type == 942 || proj.type == 943 || proj.type == 944 || proj.type == 945 || proj.type == 971 || proj.type == 975 || proj.type == 1000 || proj.type == 1012 || proj.type == 1018 || proj.type == 1020 || (((proj.type >= 776 && proj.type <= 801) || (proj.type >= 803 && proj.type <= 810)) && proj.type != 779 && proj.type != 783 && proj.type != 862 && proj.type != 863))
            {
                Vector2 vector73 = proj.position + new Vector2(proj.width, proj.height) / 2f + Vector2.UnitY * proj.gfxOffY - screenPosition;
                Texture2D value83 = TextureAssets.Projectile[proj.type].Value;
                Microsoft.Xna.Framework.Color color81 = proj.GetAlpha(projectileColor);
                Vector2 origin21 = new Vector2(value83.Width, value83.Height) / 2f;
                float num315 = proj.rotation;
                Vector2 vector74 = Vector2.One * proj.scale;
                Microsoft.Xna.Framework.Rectangle? sourceRectangle5 = null;
                if (proj.type == 446)
                {
                    origin21.Y = 4f;
                }
                if (proj.type == 1020)
                {
                    origin21.Y = 14f;
                }
                if (proj.type == 865)
                {
                    vector73 += new Vector2(1f, -1f);
                    dir = ((proj.DirectionFrom(Main.player[proj.owner].Center).SafeNormalize(Vector2.Zero).X > 0f) ? SpriteEffects.FlipHorizontally : SpriteEffects.None);
                }
                if (proj.type == 16)
                {
                    float lerpValue7 = Utils.GetLerpValue(0f, 8f, proj.velocity.Length(), clamped: true);
                    num315 *= lerpValue7;
                    vector74 *= 0.6f;
                    vector74.Y *= MathHelper.Lerp(1f, 0.8f, lerpValue7);
                    vector74.X *= MathHelper.Lerp(1f, 1.5f, lerpValue7);
                }
                if (proj.type == 34)
                {
                    float lerpValue8 = Utils.GetLerpValue(0f, 8f, proj.velocity.Length(), clamped: true);
                    num315 *= lerpValue8;
                    vector74.X *= MathHelper.Lerp(1f, 0.8f, lerpValue8);
                    num315 += -(float)Math.PI / 2f * lerpValue8;
                    sourceRectangle5 = value83.Frame(1, projFrames[proj.type], 0, proj.frame);
                    origin21 = sourceRectangle5.Value.Size() / 2f;
                    vector73 -= proj.velocity * 1f;
                    vector73 = proj.oldPos[0] + proj.Size / 2f - screenPosition - proj.velocity / 2f;
                }
                if (proj.type == 79)
                {
                    num315 = 0f;
                    vector74 *= Utils.GetLerpValue(32f, 0f, proj.position.Distance(proj.oldPos[12]), clamped: true);
                    color81 = new Microsoft.Xna.Framework.Color(255, 255, 255, 0);
                }
                if (proj.type == 761 || proj.type == 762)
                {
                    dir = ((proj.spriteDirection <= 0) ? SpriteEffects.FlipVertically : SpriteEffects.None);
                }
                if (proj.type == 662 || proj.type == 685)
                {
                    origin21 = new Vector2(6f, 6f);
                }
                if (proj.type == 699 || proj.type == 708)
                {
                    Player player4 = Main.player[proj.owner];
                    origin21 = new Vector2((proj.spriteDirection == 1) ? ((float)value83.Width - -8f) : (-8f), (player4.gravDir == 1f) ? (-8f) : ((float)value83.Height - -8f));
                    if (player4.gravDir == -1f)
                    {
                        dir |= SpriteEffects.FlipVertically;
                        num315 += (float)Math.PI / 2f * (float)(-proj.spriteDirection);
                    }
                }
                if (proj.type == 938 || proj.type == 939 || proj.type == 940 || proj.type == 941 || proj.type == 942 || proj.type == 943 || proj.type == 944 || proj.type == 945)
                {
                    num315 -= (float)Math.PI / 4f * (float)proj.spriteDirection;
                }
                if (proj.type == 502)
                {
                    LoadProjectile(250);
                    Texture2D value84 = TextureAssets.Projectile[250].Value;
                    Vector2 origin22 = new Vector2(value84.Width / 2, 0f);
                    Vector2 vector75 = new Vector2(proj.width, proj.height) / 2f;
                    Microsoft.Xna.Framework.Color white3 = Microsoft.Xna.Framework.Color.White;
                    white3.A = 127;
                    for (int num316 = proj.oldPos.Length - 1; num316 > 0; num316--)
                    {
                        Vector2 vector76 = proj.oldPos[num316] + vector75;
                        if (!(vector76 == vector75))
{
                            Vector2 vector77 = proj.oldPos[num316 - 1] + vector75;
                            float rotation27 = (vector77 - vector76).ToRotation() - (float)Math.PI / 2f;
                            Vector2 scale7 = new Vector2(1f, Vector2.Distance(vector76, vector77) / (float)value84.Height);
                            Microsoft.Xna.Framework.Color color82 = white3 * (1f - (float)num316 / (float)proj.oldPos.Length);
                            EntitySpriteDraw(value84, vector76 - screenPosition, null, color82, rotation27, origin22, scale7, dir);
                        }
                    }
                }
                else if (proj.type == 540 && proj.velocity != Vector2.Zero)
                {
                    float num317 = 0f;
                    if (proj.ai[0] >= 10f)
                    {
                        num317 = (proj.ai[0] - 10f) / 10f;
                    }
                    if (proj.ai[0] >= 20f)
                    {
                        num317 = (20f - proj.ai[0]) / 10f;
                    }
                    if (num317 > 1f)
                    {
                        num317 = 1f;
                    }
                    if (num317 < 0f)
                    {
                        num317 = 0f;
                    }
                    if (num317 != 0f)
                    {
                        Texture2D value85 = TextureAssets.Extra[47].Value;
                        Vector2 origin23 = new Vector2(value85.Width / 2, 0f);
                        Microsoft.Xna.Framework.Color color83 = color81 * num317 * 0.7f;
                        Vector2 position21 = proj.Center - screenPosition;
                        Vector2 vector78 = proj.velocity.ToRotation().ToRotationVector2() * value83.Width / 3f;
                        vector78 = Vector2.Zero;
                        position21 += vector78;
                        float rotation28 = proj.velocity.ToRotation() - (float)Math.PI / 2f;
                        Vector2 scale8 = new Vector2(1f, (proj.velocity.Length() - vector78.Length() * 2f) / (float)value85.Height);
                        EntitySpriteDraw(value85, position21, null, color83, rotation28, origin23, scale8, SpriteEffects.None);
                    }
                }
                if (proj.type == 578 || proj.type == 579 || proj.type == 641 || proj.type == 813)
                {
                    Microsoft.Xna.Framework.Color color84 = color81 * 0.8f;
                    color84.A /= 2;
                    Microsoft.Xna.Framework.Color color85 = Microsoft.Xna.Framework.Color.Lerp(color81, Microsoft.Xna.Framework.Color.Black, 0.5f);
                    color85.A = color81.A;
                    float num318 = 0.95f + (proj.rotation * 0.75f).ToRotationVector2().Y * 0.1f;
                    color85 *= num318;
                    float scale9 = 0.6f + proj.scale * 0.6f * num318;
                    Texture2D value86 = TextureAssets.Extra[50].Value;
                    bool flag36 = true;
                    if (proj.type == 813)
                    {
                        flag36 = false;
                        value86 = TextureAssets.Extra[131].Value;
                    }
                    Vector2 origin24 = value86.Size() / 2f;
                    EntitySpriteDraw(value86, vector73, null, color85, 0f - num315 + 0.35f, origin24, scale9, dir ^ SpriteEffects.FlipHorizontally);
                    EntitySpriteDraw(value86, vector73, null, color81, 0f - num315, origin24, proj.scale, dir ^ SpriteEffects.FlipHorizontally);
                    if (flag36)
                    {
                        EntitySpriteDraw(value83, vector73, null, color84, (0f - num315) * 0.7f, origin21, proj.scale, dir ^ SpriteEffects.FlipHorizontally);
                    }
                    EntitySpriteDraw(value86, vector73, null, color81 * 0.8f, num315 * 0.5f, origin24, proj.scale * 0.9f, dir);
                    color81.A = 0;
                    if (proj.type == 813)
                    {
                        num315 = 0f;
                    }
                }
                if (proj.type == 617)
                {
                    Microsoft.Xna.Framework.Color color86 = color81 * 0.8f;
                    color86.A /= 2;
                    Microsoft.Xna.Framework.Color color87 = Microsoft.Xna.Framework.Color.Lerp(color81, Microsoft.Xna.Framework.Color.Black, 0.5f);
                    color87.A = color81.A;
                    float num319 = 0.95f + (proj.rotation * 0.75f).ToRotationVector2().Y * 0.1f;
                    color87 *= num319;
                    float scale10 = 0.6f + proj.scale * 0.6f * num319;
                    EntitySpriteDraw(TextureAssets.Extra[50].Value, vector73, null, color87, 0f - proj.rotation + 0.35f, origin21, scale10, dir ^ SpriteEffects.FlipHorizontally);
                    EntitySpriteDraw(TextureAssets.Extra[50].Value, vector73, null, color81, 0f - proj.rotation, origin21, proj.scale, dir ^ SpriteEffects.FlipHorizontally);
                    EntitySpriteDraw(value83, vector73, null, color86, (0f - proj.rotation) * 0.7f, origin21, proj.scale, dir ^ SpriteEffects.FlipHorizontally);
                    EntitySpriteDraw(TextureAssets.Extra[50].Value, vector73, null, color81 * 0.8f, proj.rotation * 0.5f, origin21, proj.scale * 0.9f, dir);
                    color81.A = 0;
                }
                if (proj.type == 757 || proj.type == 25 || proj.type == 35 || proj.type == 63 || proj.type == 154 || proj.type == 247 || proj.type == 26)
                {
                    if (proj.ai[0] == 1f)
                    {
                        Microsoft.Xna.Framework.Color color88 = color81;
                        color88.A = 127;
                        color88 *= 0.5f;
                        int num320 = (int)proj.ai[1];
                        if (num320 > 5)
{
                            num320 = 5;
                        }
                        for (float num321 = 1f; num321 >= 0f; num321 -= 0.125f)
{
                            float num322 = 1f - num321;
                            Vector2 vector79 = proj.velocity * -num320 * num321;
                            EntitySpriteDraw(value83, vector73 + vector79, null, color88 * num322, num315, origin21, proj.scale * 1.15f * MathHelper.Lerp(0.5f, 1f, num322), dir);
                        }
                    }
                }
                else if (proj.type == 79)
                {
                    Vector2 scale11 = vector74 * 1.4f;
                    Vector2 spinningpoint6 = new Vector2(2f * scale11.X + (float)Math.Cos(GlobalTimeWrappedHourly * ((float)Math.PI * 2f)) * 0.4f, 0f).RotatedBy(num315 + GlobalTimeWrappedHourly * ((float)Math.PI * 2f));
                    for (float num323 = 0f; num323 < 1f; num323 += 1f / 6f)
                    {
                        Microsoft.Xna.Framework.Color color89 = hslToRgb(num323, 1f, 0.5f) * 0.3f;
                        color89.A = 0;
                        EntitySpriteDraw(value83, vector73 + spinningpoint6.RotatedBy(num323 * ((float)Math.PI * 2f)), null, color89, num315, origin21, scale11, dir);
                    }
                    EntitySpriteDraw(value83, vector73, null, color81, num315, origin21, vector74, dir);
                }
                if ((0u | ((proj.type == 464 && proj.ai[1] != 1f) ? 1u : 0u)) == 0)
                {
                    EntitySpriteDraw(value83, vector73, sourceRectangle5, color81, num315, origin21, vector74, dir);
                }
                if (proj.type == 464 && proj.ai[1] != 1f)
                {
                    value83 = TextureAssets.Extra[35].Value;
                    Microsoft.Xna.Framework.Rectangle rectangle21 = value83.Frame(1, 3);
                    origin21 = rectangle21.Size() / 2f;
                    Vector2 vector80 = new Vector2(0f, -720f).RotatedBy(proj.velocity.ToRotation());
                    float num324 = proj.ai[0] % 45f / 45f;
                    Vector2 spinningpoint7 = vector80 * num324;
                    for (int num325 = 0; num325 < 6; num325++)
                    {
                        float num326 = (float)num325 * ((float)Math.PI * 2f) / 6f;
                        Vector2 vector81 = proj.Center + spinningpoint7.RotatedBy(num326);
                        EntitySpriteDraw(value83, vector81 - screenPosition, rectangle21, color81, num326 + proj.velocity.ToRotation() + (float)Math.PI, origin21, proj.scale, dir);
                        rectangle21.Y += rectangle21.Height;
                        if (rectangle21.Y >= value83.Height)
{
                            rectangle21.Y = 0;
                        }
                    }
                }
                else if (proj.type == 490)
                {
                    EntitySpriteDraw(TextureAssets.Extra[34].Value, vector73, null, color81, 0f - proj.rotation, TextureAssets.Extra[34].Value.Size() / 2f, proj.scale, dir);
                    EntitySpriteDraw(value83, vector73, null, color81, proj.rotation, origin21, proj.scale * 0.42f, dir);
                    EntitySpriteDraw(TextureAssets.Extra[34].Value, vector73, null, color81, 0f - proj.rotation, TextureAssets.Extra[34].Value.Size() / 2f, proj.scale * 0.42f, dir);
                }
                else if (proj.type == 616)
                {
                    value83 = TextureAssets.GlowMask[193].Value;
                    EntitySpriteDraw(value83, vector73, null, new Microsoft.Xna.Framework.Color(127, 127, 127, 0), proj.rotation, origin21, proj.scale, dir);
                }
                else if (proj.type >= 646 && proj.type <= 649)
                {
                    value83 = TextureAssets.GlowMask[203 + proj.type - 646].Value;
                    EntitySpriteDraw(value83, vector73, null, new Microsoft.Xna.Framework.Color(255, 255, 255, 127), proj.rotation, origin21, proj.scale, dir);
                }
                else if (proj.type == 699)
                {
                    value83 = TextureAssets.GlowMask[231].Value;
                    EntitySpriteDraw(value83, vector73, null, new Microsoft.Xna.Framework.Color(255, 255, 255, 127), num315, origin21, proj.scale, dir);
                }
                else if (proj.type == 707 || proj.type == 708)
                {
                    float num327 = 0.5f;
                    value83 = TextureAssets.GlowMask[232].Value;
                    Microsoft.Xna.Framework.Rectangle value87 = value83.Frame(1, 3, 0, (int)(proj.ai[0] % 9f) / 3);
                    if (proj.type == 708)
                    {
                        value87 = value83.Frame(1, 3, 0, Main.player[proj.owner].itemAnimation % 9 / 3);
                        num327 = 0.75f;
                    }
                    Microsoft.Xna.Framework.Color color90 = new Microsoft.Xna.Framework.Color(255, 255, 255, 127) * num327;
                    Vector2 spinningpoint8 = new Vector2(2f, 0f).RotatedBy(proj.rotation);
                    for (float num328 = 0f; num328 < 4f; num328 += 1f)
                    {
                        EntitySpriteDraw(value83, vector73 + spinningpoint8.RotatedBy(num328 * ((float)Math.PI / 2f)), value87, color90 * 0.5f, proj.rotation, origin21, proj.scale, dir);
                    }
                    EntitySpriteDraw(value83, vector73, value87, color90, proj.rotation, origin21, proj.scale, dir);
                }
                else if (proj.type == 719)
                {
                    float num329 = 0.3f;
                    Microsoft.Xna.Framework.Color color91 = new Microsoft.Xna.Framework.Color(80, 80, 80, 255) * num329;
                    float num330 = proj.scale * 1.5f;
                    Vector2 spinningpoint9 = new Vector2(2f * num330, 0f).RotatedBy(proj.rotation);
                    for (float num331 = 0f; num331 < 4f; num331 += 1f)
                    {
                        EntitySpriteDraw(value83, vector73 + -proj.velocity * num331 * 1.25f, null, color91 * 0.7f, proj.rotation, origin21, num330, dir);
                    }
                    for (float num332 = 0f; num332 < 3f; num332 += 1f)
                    {
                        EntitySpriteDraw(value83, vector73 + spinningpoint9.RotatedBy(num332 * ((float)Math.PI / 2f)), null, color91 * 0.9f, proj.rotation, origin21, num330, dir);
                    }
                    EntitySpriteDraw(value83, vector73, null, color81, proj.rotation, origin21, proj.scale, dir);
                }
                else if (proj.type == 16)
                {
                    Microsoft.Xna.Framework.Color color92 = new Microsoft.Xna.Framework.Color(80, 80, 80, 0);
                    Vector2 scale12 = vector74 + vector74 * (float)Math.Cos(GlobalTimeWrappedHourly * ((float)Math.PI * 2f)) * 0.4f;
                    Vector2 spinningpoint10 = new Vector2(2f * scale12.X, 0f).RotatedBy(num315);
                    for (float num333 = 0f; num333 < 1f; num333 += 0.25f)
                    {
                        EntitySpriteDraw(value83, vector73 + spinningpoint10.RotatedBy(num333 * ((float)Math.PI * 2f)), null, color92, num315, origin21, scale12, dir);
                    }
                    EntitySpriteDraw(value83, vector73, null, color81, num315, origin21, vector74, dir);
                }
                else if (proj.type == 34)
                {
                    float lerpValue9 = Utils.GetLerpValue(0f, 6f, proj.localAI[0], clamped: true);
                    Microsoft.Xna.Framework.Color color93 = new Microsoft.Xna.Framework.Color(255, 255, 255, 127) * 0.75f;
                    Vector2 scale13 = new Vector2(lerpValue9);
                    Vector2 spinningpoint11 = new Vector2(4f * scale13.X, 0f).RotatedBy(num315);
                    for (float num334 = 0f; num334 < 1f; num334 += 0.25f)
                    {
                        EntitySpriteDraw(value83, vector73 + spinningpoint11.RotatedBy(num334 * ((float)Math.PI * 2f)), sourceRectangle5, color93, num315, origin21, scale13, dir);
                    }
                }
                return;
            }
            if (proj.type == 465 || proj.type == 467 || proj.type == 468 || proj.type == 500 || proj.type == 518 || proj.type == 535 || proj.type == 539 || proj.type == 575 || proj.type == 574 || proj.type == 589 || proj.type == 590 || proj.type == 593 || proj.type == 602 || proj.type == 596 || proj.type == 612 || proj.type == 953 || proj.type == 613 || proj.type == 614 || proj.type == 623 || proj.type == 625 || proj.type == 626 || proj.type == 627 || proj.type == 628 || proj.type == 634 || proj.type == 635 || proj.type == 643 || proj.type == 644 || proj.type == 645 || proj.type == 650 || proj.type == 652 || proj.type == 658 || proj.type == 659 || proj.type == 663 || proj.type == 665 || proj.type == 667 || proj.type == 677 || proj.type == 678 || proj.type == 679 || proj.type == 691 || proj.type == 692 || proj.type == 693 || proj.type == 702 || proj.type == 703 || proj.type == 701 || proj.type == 712 || proj.type == 715 || proj.type == 716 || proj.type == 717 || proj.type == 718 || proj.type == 758 || proj.type == 759 || proj.type == 764 || proj.type == 779 || proj.type == 783 || proj.type == 773 || proj.type == 820 || proj.type == 831 || proj.type == 970 || proj.type == 836 || proj.type == 851 || proj.type == 855 || proj.type == 856 || proj.type == 857 || proj.type == 861 || proj.type == 862 || proj.type == 863 || proj.type == 866 || proj.type == 870 || proj.type == 882 || proj.type == 885 || proj.type == 889 || proj.type == 895 || proj.type == 896 || proj.type == 898 || proj.type == 903 || proj.type == 904 || proj.type == 905 || proj.type == 906 || proj.type == 908 || proj.type == 910 || proj.type == 911 || proj.type == 951 || proj.type == 957 || proj.type == 962 || proj.type == 963 || proj.type == 967 || proj.type == 968 || proj.type == 978 || proj.type == 995 || proj.type == 886 || proj.type == 892)
            {
                Vector2 vector82 = proj.position + new Vector2(proj.width, proj.height) / 2f + Vector2.UnitY * proj.gfxOffY - screenPosition;
                Texture2D texture2D4 = TextureAssets.Projectile[proj.type].Value;
                Microsoft.Xna.Framework.Rectangle rectangle22 = texture2D4.Frame(1, projFrames[proj.type], 0, proj.frame);
                if (proj.type == 963)
                {
                    rectangle22 = texture2D4.Frame(4, projFrames[proj.type], 0, proj.frame);
                }
                if (proj.type == 957)
                {
                    int horizontalFrames = 3;
                    int frameX = proj.frame / projFrames[proj.type];
                    int frameY2 = proj.frame % projFrames[proj.type];
                    rectangle22 = texture2D4.Frame(horizontalFrames, projFrames[proj.type], frameX, frameY2);
                }
                if (proj.type == 962)
                {
                    int verticalFrames = 4;
                    int frameY3 = proj.frame / projFrames[proj.type];
                    int frameX2 = proj.frame % projFrames[proj.type];
                    rectangle22 = texture2D4.Frame(projFrames[proj.type], verticalFrames, frameX2, frameY3);
                }
                Microsoft.Xna.Framework.Color color94 = proj.GetAlpha(projectileColor);
                if (proj.type == 623 && CurrentDrawnEntityShader != 0)
                {
                    color94.A = 127;
                }
                if (proj.type == 995)
                {
                    Projectile.AI_192_GetJuminoFall(proj, out var timeSinceFall, out var fall);
                    vector82.Y -= 4f;
                    vector82.Y += fall;
                    float amount = Utils.Remap(timeSinceFall, 0f, 10f, 1f, 0f);
                    color94 = Microsoft.Xna.Framework.Color.Lerp(color94, Microsoft.Xna.Framework.Color.White * proj.Opacity, amount);
                }
                Vector2 origin25 = rectangle22.Size() / 2f;
                if (proj.type == 703)
                {
                    rectangle22.Height -= 2;
                }
                if (proj.type == 957)
                {
                    float num335 = (float)(Math.Cos((float)(int)mouseTextColor / 255f * ((float)Math.PI * 2f) * 2f) * 4.0);
                    num335 *= Math.Max(0f, Math.Min(1f, proj.localAI[0] / 100f));
                    float num336 = 0f;
                    if (proj.frame > projFrames[proj.type] * 2)
                    {
                        switch (proj.frame % projFrames[proj.type])
{
                        case 5:
                        case 11:
                            num336 = 2f;
                            break;
                        case 6:
                        case 10:
                            num336 = 6f;
                            break;
                        case 7:
                            num336 = 8f;
                            break;
                        case 8:
                        case 9:
                            num336 = 10f;
                            break;
                        }
                    }
                    vector82.Y += -2f + num335 + num336;
                }
                if (proj.type == 895 || proj.type == 896 || proj.type == 898 || proj.type == 963)
                {
                    float num337 = 2f;
                    if (proj.isAPreviewDummy)
                    {
                        num337 = 0.5f;
                    }
                    vector82.Y += 0f - num337 + (float)(Math.Cos((float)(int)mouseTextColor / 255f * ((float)Math.PI * 2f) * 2f) * (double)(num337 * 2f));
                }
                if (proj.type == 963 && proj.localAI[1] >= 0f)
                {
                    float num338 = proj.localAI[1];
                    float num339 = 1f - num338;
                    Microsoft.Xna.Framework.Color color95 = proj.GetAlpha(new Microsoft.Xna.Framework.Color(255, 220, 220)) * num339 * num339 * 0.8f;
                    color95.A = 0;
                    short num340 = 536;
                    LoadProjectile(num340);
                    Texture2D value88 = TextureAssets.Projectile[num340].Value;
                    Vector2 origin26 = value88.Size() * new Vector2(0.5f, 1f);
                    float num341 = 9f;
                    float num342 = proj.velocity.ToRotation();
                    if (proj.velocity.Length() < 0.1f)
                    {
                        num342 = ((proj.direction == 1) ? 0f : ((float)Math.PI));
                    }
                    Vector2 value89 = (num342 + (float)Math.PI / 2f).ToRotationVector2();
                    for (int num343 = 0; (float)num343 < num341; num343++)
                    {
                        float num344 = ((num343 % 2 != 0) ? 1 : (-1));
                        float num345 = ((float)num343 + 1f) * num344 * 0.2f * (0.2f + 2f * num338) + num342 + (float)Math.PI / 2f;
                        float num346 = Utils.Remap(Vector2.Dot(num345.ToRotationVector2(), value89), -1f, 1f, 0f, 1f);
                        float num347 = proj.scale * (0.15f + 0.6f * (float)Math.Sin(GlobalTimeWrappedHourly + (float)num343 * 0.739f)) * num346;
                        EntitySpriteDraw(value88, vector82 + proj.rotation.ToRotationVector2().RotatedBy((float)Math.PI * 2f * (1f / num341) * (float)num343 + GlobalTimeWrappedHourly) * 4f * proj.scale, null, color95 * num346, num345, origin26, new Vector2(num347 * 1.5f, num347), SpriteEffects.None);
                    }
                }
                if (proj.type == 962)
                {
                    float num348 = Utils.Remap(proj.ai[0], 0f, 30f, 1f, 0f);
                    Microsoft.Xna.Framework.Color color96 = proj.GetAlpha(Microsoft.Xna.Framework.Color.White) * num348 * num348 * 0.3f;
                    color96.A = 0;
                    for (int num349 = 0; num349 < 4; num349++)
                    {
                        EntitySpriteDraw(texture2D4, vector82 + proj.rotation.ToRotationVector2().RotatedBy((float)Math.PI / 2f * (float)num349) * 2f * proj.scale, rectangle22, color96, proj.rotation, origin25, proj.scale, dir);
                    }
                }
                if (proj.type == 855)
                {
                    float y21 = (GlobalTimeWrappedHourly % 6f / 6f * ((float)Math.PI * 2f)).ToRotationVector2().Y;
                    float num350 = y21 * 0.3f + 0.7f;
                    Microsoft.Xna.Framework.Color color97 = color94 * num350 * 0.3f;
                    for (int num351 = 0; num351 < 4; num351++)
                    {
                        float x13 = 0f;
                        float y22 = 0f;
                        switch (num351)
{
                        case 0:
                            x13 = 4f;
                            break;
                        case 1:
                            x13 = -4f;
                            break;
                        case 2:
                            y22 = 4f;
                            break;
                        case 3:
                            y22 = -4f;
                            break;
                        }
                        Vector2 vector83 = new Vector2(x13, y22).RotatedBy(proj.rotation) * y21;
                        spriteBatch.Draw(texture2D4, vector82 + vector83, rectangle22, color97, proj.rotation, rectangle22.Size() / 2f, 1f, SpriteEffects.None, 0f);
                    }
                }
                else if (proj.type == 908)
                {
                    PlayerTitaniumStormBuffTextureContent playerTitaniumStormBuff = TextureAssets.RenderTargets.PlayerTitaniumStormBuff;
                    vector82 += (GlobalTimeWrappedHourly * 8f + (float)proj.whoAmI).ToRotationVector2() * 4f;
                    playerTitaniumStormBuff.Request();
                    if (playerTitaniumStormBuff.IsReady)
                    {
                        texture2D4 = playerTitaniumStormBuff.GetTarget();
                    }
                    rectangle22 = texture2D4.Frame(projFrames[proj.type], 1, proj.frame);
                    origin25 = rectangle22.Size() / 2f;
                }
                else if (proj.type == 764)
                {
                    DrawProjWithStarryTrail(proj, projectileColor, dir);
                }
                else if (proj.type == 856)
                {
                    DrawProjWithStarryTrail(proj, projectileColor, dir);
                }
                else if (proj.type == 857)
                {
                    DrawProjWithStarryTrail(proj, projectileColor, dir);
                    color94 = Microsoft.Xna.Framework.Color.White * proj.Opacity * 0.9f;
                    color94.A /= 2;
                    rectangle22 = texture2D4.Frame(15, 1, proj.frame);
                    origin25 = rectangle22.Size() / 2f;
                    DrawPrettyStarSparkle(proj.Opacity, dir, vector82, color94, proj.GetFirstFractalColor(), proj.localAI[0], 15f, 30f, 30f, 45f, 0f, new Vector2(5f, 2f), Vector2.One);
                }
                else if (proj.type == 539)
                {
                    if (proj.ai[0] >= 210f)
                    {
                        float num352 = proj.ai[0] - 210f;
                        num352 /= 20f;
                        if (num352 > 1f)
{
                            num352 = 1f;
                        }
                        EntitySpriteDraw(TextureAssets.Extra[46].Value, vector82, null, new Microsoft.Xna.Framework.Color(255, 255, 255, 128) * num352, proj.rotation, new Vector2(17f, 22f), proj.scale, dir);
                    }
                }
                else if (proj.type == 773)
                {
                    origin25.Y = rectangle22.Height - 12;
                }
                else if (proj.type == 866)
                {
                    origin25.X += 14f;
                }
                else if (proj.type == 759)
                {
                    origin25.Y = rectangle22.Height - 2;
                    origin25.X += (dir.HasFlag(SpriteEffects.FlipHorizontally) ? 1 : (-1));
                }
                else if (proj.type == 758)
                {
                    vector82.Y += proj.height / 2;
                    origin25 = rectangle22.Size() * new Vector2(0.5f, 1f);
                    origin25.Y -= 4f;
                }
                else if (proj.type == 951)
                {
                    vector82.Y += proj.height / 2;
                    vector82.Y -= (float)rectangle22.Height * 0.5f;
                    vector82.Y += 4f;
                    origin25 = rectangle22.Size() * new Vector2(0.5f, 0.5f);
                }
                else if (proj.type == 833)
                {
                    if (proj.frame != 8)
                    {
                        vector82.Y += proj.height / 2;
                        origin25 = rectangle22.Size() * new Vector2(0.5f, 1f);
                        origin25.Y -= 4f;
                        origin25.X -= 7 * dir.HasFlag(SpriteEffects.FlipHorizontally).ToDirectionInt();
                    }
                }
                else if (proj.type == 834 || proj.type == 835)
                {
                    if (proj.frame != 10)
                    {
                        vector82.Y += proj.height / 2;
                        origin25 = rectangle22.Size() * new Vector2(0.5f, 1f);
                        origin25.Y -= 4f;
                        origin25.X -= 2 * dir.HasFlag(SpriteEffects.FlipHorizontally).ToDirectionInt();
                    }
                }
                else if (proj.type == 715 || proj.type == 716 || proj.type == 717 || proj.type == 718)
                {
                    rectangle22 = texture2D4.Frame(3);
                    origin25 = rectangle22.Size() / 2f;
                    int num353 = (int)proj.ai[0];
                    Vector2 origin27 = new Vector2(rectangle22.Width / 2, 0f);
                    Vector2 vector84 = proj.Size / 2f;
                    Microsoft.Xna.Framework.Color celeb2Color = proj.GetCeleb2Color();
                    celeb2Color.A = 127;
                    celeb2Color *= 0.8f;
                    Microsoft.Xna.Framework.Rectangle value90 = rectangle22;
                    value90.X += value90.Width * 2;
                    for (int num354 = proj.oldPos.Length - 1; num354 > 0; num354--)
                    {
                        Vector2 vector85 = proj.oldPos[num354] + vector84;
                        if (!(vector85 == vector84))
{
                            Vector2 value91 = proj.oldPos[num354 - 1] + vector84;
                            float num355 = proj.oldRot[num354];
                            Vector2 scale14 = new Vector2(Vector2.Distance(vector85, value91) / (float)rectangle22.Width, 1f);
                            Microsoft.Xna.Framework.Color color98 = celeb2Color * (1f - (float)num354 / (float)proj.oldPos.Length);
                            switch (num353)
{
                            case 2:
{
                                Vector2 vector86 = num355.ToRotationVector2();
                                int num356 = num354 + proj.timeLeft;
                                if (num356 < 0)
{
                                    num356 += 20 * (num356 / -20) + 20;
                                }
                                num356 %= 20;
                                float num357 = 0f;
                                scale14 *= 0.6f;
                                switch (num356)
{
                                case 1:
                                    num357 = 1f;
                                    break;
                                case 2:
                                    num357 = 2f;
                                    break;
                                case 3:
                                    num357 = 3f;
                                    break;
                                case 4:
                                    num357 = 2f;
                                    break;
                                case 5:
                                    num357 = 1f;
                                    break;
                                case 7:
                                    num357 = -1f;
                                    break;
                                case 8:
                                    num357 = -2f;
                                    break;
                                case 9:
                                    num357 = -3f;
                                    break;
                                case 10:
                                    num357 = -2f;
                                    break;
                                case 11:
                                    num357 = -1f;
                                    break;
                                }
                                vector85 += vector86 * num357 * 4f;
                                break;
                            }
                            case 5:
                                scale14 *= 0.5f;
                                break;
                            }
                            EntitySpriteDraw(texture2D4, vector85 - screenPosition, value90, color98, num355, origin27, scale14, dir);
                        }
                    }
                }
                else if (proj.type == 663 || proj.type == 665 || proj.type == 667)
                {
                    vector82 = proj.Bottom + Vector2.UnitY * proj.gfxOffY - screenPosition;
                    origin25 = rectangle22.Size() * new Vector2(0.5f, 1f);
                    origin25.Y -= 2f;
                    origin25.Y -= 2f;
                }
                else if (proj.type == 691 || proj.type == 692 || proj.type == 693)
                {
                    vector82 = proj.Bottom + Vector2.UnitY * proj.gfxOffY - screenPosition;
                    origin25 = rectangle22.Size() * new Vector2(0.5f, 1f);
                    origin25.Y -= 2f;
                    origin25.Y -= 2f;
                }
                else if (proj.type == 677 || proj.type == 678 || proj.type == 679)
                {
                    if (proj.spriteDirection == -1)
                    {
                        dir ^= SpriteEffects.FlipHorizontally | SpriteEffects.FlipVertically;
                    }
                    Texture2D value92 = TextureAssets.Extra[83].Value;
                    if (proj.type == 678)
                    {
                        value92 = TextureAssets.Extra[84].Value;
                    }
                    if (proj.type == 679)
                    {
                        value92 = TextureAssets.Extra[85].Value;
                    }
                    Vector2 position22 = proj.Bottom + Vector2.UnitY * proj.gfxOffY - screenPosition;
                    Vector2 origin28 = value92.Size() * new Vector2(0.5f, 1f);
                    origin28.Y -= 2f;
                    EntitySpriteDraw(value92, position22, null, color94, 0f, origin28, 1f, dir & SpriteEffects.FlipHorizontally);
                    origin25.X += dir.HasFlag(SpriteEffects.FlipHorizontally).ToDirectionInt();
                    vector82.Y += 1f;
                    vector82.Y += 2f;
                    if (proj.type == 678)
                    {
                        vector82.Y += -4f;
                    }
                    if (proj.type == 679)
                    {
                        vector82.Y -= 2f;
                        if (!dir.HasFlag(SpriteEffects.FlipVertically))
{
                            origin25.Y += 4f;
                        }
                        else
{
                            origin25.Y -= 4f;
                        }
                        origin25.X += dir.HasFlag(SpriteEffects.FlipHorizontally).ToDirectionInt() * 4;
                    }
                }
                else if (proj.type == 602)
                {
                    origin25.X = rectangle22.Width - 6;
                    origin25.Y -= 1f;
                    rectangle22.Height -= 2;
                }
                else if (proj.type == 589)
                {
                    rectangle22 = texture2D4.Frame(5, 1, (int)proj.ai[1]);
                    origin25 = rectangle22.Size() / 2f;
                }
                else if (proj.type == 590)
                {
                    if (proj.ai[2] == 1f && proj.frame < 3)
                    {
                        proj.frame = 3;
                    }
                    rectangle22 = texture2D4.Frame(6, 1, proj.frame);
                    origin25 = rectangle22.Size() / 2f;
                }
                else if (proj.type == 836)
                {
                    rectangle22 = texture2D4.Frame(4, 1, proj.frame);
                    origin25 = rectangle22.Size() / 2f;
                }
                else if (proj.type == 650 || proj.type == 882 || proj.type == 888 || proj.type == 894 || proj.type == 895 || proj.type == 896 || proj.type == 898 || proj.type == 901 || proj.type == 957)
                {
                    origin25.Y -= 4f;
                }
                else if (proj.type == 623)
                {
                    if (!gamePaused && proj.ai[0] == 2f)
                    {
                        vector82 += rand.NextVector2Circular(2f, 2f);
                    }
                    if (CurrentDrawnEntityShader == 0)
                    {
                        color94.A /= 2;
                    }
                }
                else if (proj.type >= 625 && proj.type <= 628)
                {
                    color94.A /= 2;
                }
                else if (proj.type == 644)
                {
                    Microsoft.Xna.Framework.Color color99 = hslToRgb(proj.ai[0], 1f, 0.5f).MultiplyRGBA(new Microsoft.Xna.Framework.Color(255, 255, 255, 0));
                    EntitySpriteDraw(texture2D4, vector82, rectangle22, color99, proj.rotation, origin25, proj.scale * 2f, dir);
                    EntitySpriteDraw(texture2D4, vector82, rectangle22, color99, 0f, origin25, proj.scale * 2f, dir);
                    if (proj.ai[1] != -1f && proj.Opacity > 0.3f)
                    {
                        Vector2 vector87 = Main.projectile[(int)proj.ai[1]].Center - proj.Center;
                        Vector2 vector88 = new Vector2(1f, vector87.Length() / (float)texture2D4.Height);
                        float rotation29 = vector87.ToRotation() + (float)Math.PI / 2f;
                        float value93 = MathHelper.Distance(30f, proj.localAI[1]) / 20f;
                        value93 = MathHelper.Clamp(value93, 0f, 1f);
                        if (value93 > 0f)
{
                            EntitySpriteDraw(texture2D4, vector82 + vector87 / 2f, rectangle22, color99 * value93, rotation29, origin25, vector88, dir);
                            EntitySpriteDraw(texture2D4, vector82 + vector87 / 2f, rectangle22, color94 * value93, rotation29, origin25, vector88 / 2f, dir);
                        }
                    }
                }
                else if (proj.type == 658)
                {
                    Microsoft.Xna.Framework.Color color100 = hslToRgb(0.136f, 1f, 0.5f).MultiplyRGBA(new Microsoft.Xna.Framework.Color(255, 255, 255, 0));
                    EntitySpriteDraw(texture2D4, vector82, rectangle22, color100, 0f, origin25, new Vector2(1f, 5f) * proj.scale * 2f, dir);
                }
                EntitySpriteDraw(texture2D4, vector82, rectangle22, color94, proj.rotation, origin25, proj.scale, dir);
                if (proj.type == 896)
                {
                    Texture2D value94 = TextureAssets.GlowMask[278].Value;
                    Microsoft.Xna.Framework.Color color101 = new Microsoft.Xna.Framework.Color(150, 150, 150, 100);
                    for (int num358 = 0; num358 < 2; num358++)
                    {
                        Vector2 position23 = vector82 + new Vector2((float)rand.Next(-10, 11) * 0.1f, (float)rand.Next(-10, 11) * 0.1f);
                        EntitySpriteDraw(value94, position23, rectangle22, color101, proj.rotation, origin25, proj.scale, dir);
                    }
                    EntitySpriteDraw(value94, vector82, rectangle22, Microsoft.Xna.Framework.Color.White, proj.rotation, origin25, proj.scale, dir);
                }
                if (proj.type == 889)
                {
                    Texture2D value95 = TextureAssets.GlowMask[276].Value;
                    Microsoft.Xna.Framework.Color color102 = Microsoft.Xna.Framework.Color.White * (int)mouseTextColor;
                    EntitySpriteDraw(value95, vector82, rectangle22, color102, proj.rotation, origin25, proj.scale, dir);
                    if (!proj.isAPreviewDummy)
                    {
                        for (int num359 = 0; num359 < 4; num359++)
{
                            int num360 = 28;
                            int num361 = 7 + num359;
                            float num362 = 100f;
                            bool flag37 = num361 == 8;
                            Microsoft.Xna.Framework.Rectangle value96 = texture2D4.Frame(1, projFrames[proj.type], 0, num361);
                            Vector2 value97 = vector82;
                            Vector2 vector89 = vector82;
                            SpriteEffects effects5 = SpriteEffects.None;
                            float num363 = 0f;
                            float num364 = GlobalTimeWrappedHourly * 2f;
                            switch (num359)
{
                            case 1:
                                num364 += (float)Math.PI / 2f;
                                break;
                            case 2:
                                num364 += (float)Math.PI;
                                break;
                            case 3:
                                num364 += 4.712389f;
                                break;
                            }
                            num364 *= 3f;
                            num363 = num364;
                            vector89 += num364.ToRotationVector2() * num360;
                            if (proj.localAI[0] == num362)
{
                                EntitySpriteDraw(texture2D4, vector89, value96, color94, num363, origin25, proj.scale, effects5);
                                if (flag37)
{
                                    EntitySpriteDraw(value95, vector89, value96, color102, num363, origin25, proj.scale, effects5);
                                }
                                continue;
                            }
                            Vector2 vector90 = new Vector2(num360, -16f) + proj.velocity * 1.5f;
                            float num365 = 4f;
                            float num366 = -0.35f;
                            switch (num359)
{
                            case 1:
                                vector90.X *= -1f;
                                effects5 = SpriteEffects.FlipHorizontally;
                                num366 = 0.35f;
                                num365 = -3f;
                                break;
                            case 2:
                                vector90.Y = 16f;
                                num366 = 0.35f;
                                num365 = 2f;
                                break;
                            case 3:
                                vector90.X *= -1f;
                                vector90.Y = 16f;
                                effects5 = SpriteEffects.FlipHorizontally;
                                num366 = -0.35f;
                                num365 = -1f;
                                break;
                            }
                            vector90 += (GlobalTimeWrappedHourly * num365).ToRotationVector2() * 4f;
                            value97 += vector90;
                            float num367 = proj.localAI[0] / num362;
                            value97 = Vector2.Lerp(value97, vector89, num367);
                            num363 = ((num367 > 0.5f) ? num364 : num366);
                            EntitySpriteDraw(texture2D4, value97, value96, color94, num363, origin25, proj.scale, effects5);
                            if (flag37)
{
                                EntitySpriteDraw(value95, value97, value96, color102, num363, origin25, proj.scale, effects5);
                            }
                        }
                    }
                }
                if (proj.type == 885 && !proj.isAPreviewDummy)
                {
                    for (int num368 = 0; num368 < 2; num368++)
                    {
                        SpriteEffects effects6 = SpriteEffects.None;
                        int num369 = -30;
                        if (num368 == 1)
{
                            num369 = 30;
                            effects6 = SpriteEffects.FlipHorizontally;
                        }
                        int num370 = (int)proj.localAI[0];
                        if (proj.frame == 6)
{
                            num370 = 0;
                        }
                        else if (num368 == 1)
{
                            num370 = 2 - num370;
                        }
                        num370 += 7;
                        Microsoft.Xna.Framework.Rectangle value98 = texture2D4.Frame(1, projFrames[proj.type], 0, num370);
                        Vector2 position24 = vector82 + new Vector2(num369, 0f);
                        Vector2 vector91 = (GlobalTimeWrappedHourly * 2f).ToRotationVector2() * 4f;
                        vector91 += proj.velocity * -1.5f;
                        Vector2 vector92 = (GlobalTimeWrappedHourly * 1f).ToRotationVector2() * 3f;
                        if (num368 == 1)
{
                            position24 += vector91 + vector92;
                        }
                        else
{
                            position24 -= vector91;
                        }
                        EntitySpriteDraw(texture2D4, position24, value98, color94, 0f, origin25, proj.scale, effects6);
                    }
                }
                if (proj.type == 535)
                {
                    for (int num371 = 0; num371 < 1000; num371++)
                    {
                        if (Main.projectile[num371].active && Main.projectile[num371].owner == proj.owner && Main.projectile[num371].type == 536)
{
                            DrawProj(num371);
                        }
                    }
                }
                else if (proj.type == 715 || proj.type == 716 || proj.type == 717 || proj.type == 718)
                {
                    rectangle22.X += rectangle22.Width;
                    Microsoft.Xna.Framework.Color celeb2Color2 = proj.GetCeleb2Color();
                    celeb2Color2.A = 80;
                    EntitySpriteDraw(texture2D4, vector82, rectangle22, celeb2Color2, proj.rotation, origin25, proj.scale, dir);
                }
                else if (proj.type == 702)
                {
                    Texture2D value99 = TextureAssets.Flames[5].Value;
                    Vector2 origin29 = value99.Size() / 2f;
                    Vector2 vector93 = new Vector2(5 * proj.spriteDirection, -10f).RotatedBy(proj.rotation);
                    ulong seed2 = (ulong)(proj.localAI[0] / 4f);
                    for (int num372 = 0; num372 < 5; num372++)
                    {
                        Microsoft.Xna.Framework.Color color103 = new Microsoft.Xna.Framework.Color(100, 100, 100, 0);
                        float x14 = (float)Utils.RandomInt(ref seed2, -10, 11) * 0.15f;
                        float y23 = (float)Utils.RandomInt(ref seed2, -10, 1) * 0.35f;
                        EntitySpriteDraw(value99, vector82 + vector93 + new Vector2(x14, y23), null, color103, proj.rotation, origin29, 1f, dir);
                    }
                }
                else if (proj.type == 663 || proj.type == 665 || proj.type == 667)
                {
                    Texture2D value100 = TextureAssets.GlowMask[221].Value;
                    switch (proj.type)
                    {
                    case 665:
                        value100 = TextureAssets.GlowMask[222].Value;
                        break;
                    case 667:
                        value100 = TextureAssets.GlowMask[223].Value;
                        break;
                    }
                    float num373 = (proj.localAI[0] / 100f * ((float)Math.PI * 2f)).ToRotationVector2().X * 1f + 1f;
                    Microsoft.Xna.Framework.Color color104 = new Microsoft.Xna.Framework.Color(140, 100, 40, 0) * (num373 / 4f + 0.5f) * 1f;
                    for (float num374 = 0f; num374 < 4f; num374 += 1f)
                    {
                        EntitySpriteDraw(value100, vector82 + (num374 * ((float)Math.PI / 2f)).ToRotationVector2() * num373, rectangle22, color104, proj.rotation, origin25, proj.scale, dir);
                    }
                }
                else if (proj.type == 644)
                {
                    EntitySpriteDraw(texture2D4, vector82, rectangle22, color94, 0f, origin25, proj.scale, dir);
                }
                else if (proj.type == 963)
                {
                    int num375 = Main.player[proj.owner].ownedProjectileCounts[970] - 1;
                    int num376 = (num375 + 3) % 3;
                    int num377 = num375 / 3;
                    Vector3 vector94 = rgbToHsl(new Microsoft.Xna.Framework.Color(250, 150, 180));
                    vector94 = new Vector3(0f, 1f, 0.6f);
                    if (num377 == 1)
                    {
                        vector94 = rgbToHsl(Microsoft.Xna.Framework.Color.HotPink);
                        vector94.Z += 0.1f;
                        vector94.X -= 0.05f;
                    }
                    vector94.X = (vector94.X - (float)num377 * 0.13f + 1f) % 1f;
                    Microsoft.Xna.Framework.Color oldColor = hslToRgb(vector94);
                    Microsoft.Xna.Framework.Color color105 = Lighting.GetColor((int)(proj.Center.X / 16f), (int)(proj.Center.Y / 16f), oldColor);
                    rectangle22.X += rectangle22.Width * (1 + num376);
                    EntitySpriteDraw(texture2D4, vector82, rectangle22, color105, proj.rotation, origin25, proj.scale, dir);
                }
                else if (proj.type == 773 && proj.velocity.Length() == 0f)
                {
                    EntitySpriteDraw(TextureAssets.GlowMask[266].Value, color: Microsoft.Xna.Framework.Color.White * (int)mouseTextColor, position: vector82, sourceRectangle: rectangle22, rotation: proj.rotation, origin: origin25, scale: proj.scale, effects: dir);
                }
                else if (proj.type == 658)
                {
                    EntitySpriteDraw(texture2D4, vector82, rectangle22, color94, 0f, origin25, new Vector2(1f, 8f) * proj.scale, dir);
                }
                else if (proj.type == 602)
                {
                    texture2D4 = TextureAssets.Extra[60].Value;
                    Microsoft.Xna.Framework.Color color107 = color94;
                    color107.A = 0;
                    color107 *= 0.3f;
                    origin25 = texture2D4.Size() / 2f;
                    EntitySpriteDraw(texture2D4, vector82, null, color107, proj.rotation - (float)Math.PI / 2f, origin25, proj.scale, dir);
                    texture2D4 = TextureAssets.Extra[59].Value;
                    color107 = color94;
                    color107.A = 0;
                    color107 *= 0.13f;
                    origin25 = texture2D4.Size() / 2f;
                    EntitySpriteDraw(texture2D4, vector82, null, color107, proj.rotation - (float)Math.PI / 2f, origin25, proj.scale * 0.9f, dir);
                }
                else if (proj.type == 539)
                {
                    EntitySpriteDraw(TextureAssets.GlowMask[140].Value, vector82, rectangle22, new Microsoft.Xna.Framework.Color(255, 255, 255, 0), proj.rotation, origin25, proj.scale, dir);
                }
                else if (proj.type == 613)
                {
                    EntitySpriteDraw(TextureAssets.GlowMask[189].Value, vector82, rectangle22, new Microsoft.Xna.Framework.Color(128 - proj.alpha / 2, 128 - proj.alpha / 2, 128 - proj.alpha / 2, 0), proj.rotation, origin25, proj.scale, dir);
                }
                else if (proj.type == 614)
                {
                    EntitySpriteDraw(TextureAssets.GlowMask[190].Value, vector82, rectangle22, new Microsoft.Xna.Framework.Color(128 - proj.alpha / 2, 128 - proj.alpha / 2, 128 - proj.alpha / 2, 0), proj.rotation, origin25, proj.scale, dir);
                }
                else if (proj.type == 574)
                {
                    EntitySpriteDraw(TextureAssets.GlowMask[148].Value, vector82, rectangle22, new Microsoft.Xna.Framework.Color(255, 255, 255, 0), proj.rotation, origin25, proj.scale, dir);
                }
                else if (proj.type == 691 || proj.type == 692 || proj.type == 693)
                {
                    Texture2D value102 = TextureAssets.GlowMask[235].Value;
                    switch (proj.type)
                    {
                    case 692:
                        value102 = TextureAssets.GlowMask[236].Value;
                        break;
                    case 693:
                        value102 = TextureAssets.GlowMask[237].Value;
                        break;
                    }
                    EntitySpriteDraw(value102, vector82, rectangle22, new Microsoft.Xna.Framework.Color(255, 255, 255, 127), proj.rotation, origin25, proj.scale, dir);
                }
                else if (proj.type == 590)
                {
                    EntitySpriteDraw(TextureAssets.GlowMask[168].Value, vector82, rectangle22, new Microsoft.Xna.Framework.Color(127 - proj.alpha / 2, 127 - proj.alpha / 2, 127 - proj.alpha / 2, 0), proj.rotation, origin25, proj.scale, dir);
                }
                else if (proj.type == 623 || (proj.type >= 625 && proj.type <= 628))
                {
                    if (Main.player[proj.owner].ghostFade != 0f)
                    {
                        float num378 = Main.player[proj.owner].ghostFade * 5f;
                        for (float num379 = 0f; num379 < 4f; num379 += 1f)
{
                            EntitySpriteDraw(texture2D4, vector82 + Vector2.UnitY.RotatedBy(num379 * ((float)Math.PI * 2f) / 4f) * num378, rectangle22, color94 * 0.1f, proj.rotation, origin25, proj.scale, dir);
                        }
                    }
                    if (proj.type == 623 && proj.ai[0] == 2f && proj.frame >= 14)
                    {
                        DrawProj_StardustGuardianPunching(proj);
                    }
                }
                else if (proj.type == 643)
                {
                    float num380 = (float)Math.Cos((float)Math.PI * 2f * (proj.localAI[0] / 60f)) + 3f + 3f;
                    for (float num381 = 0f; num381 < 4f; num381 += 1f)
                    {
                        EntitySpriteDraw(texture2D4, vector82 + Vector2.UnitY.RotatedBy(num381 * ((float)Math.PI / 2f)) * num380, rectangle22, color94 * 0.2f, proj.rotation, origin25, proj.scale, dir);
                    }
                }
                else if (proj.type == 650)
                {
                    int num382 = (int)(proj.localAI[0] / ((float)Math.PI * 2f));
                    float f = proj.localAI[0] % ((float)Math.PI * 2f) - (float)Math.PI;
                    float num383 = (float)Math.IEEERemainder(proj.localAI[1], 1.0);
                    if (num383 < 0f)
                    {
                        num383 += 1f;
                    }
                    int num384 = (int)Math.Floor(proj.localAI[1]);
                    float num385 = 1f;
                    float num386 = 5f;
                    num385 = 1f + (float)num384 * 0.02f;
                    if ((float)num382 == 1f)
                    {
                        num386 = 7f;
                    }
                    Vector2 vector95 = f.ToRotationVector2() * num383 * num386 * proj.scale;
                    texture2D4 = TextureAssets.Extra[66].Value;
                    EntitySpriteDraw(texture2D4, vector82 + vector95, null, color94, proj.rotation, texture2D4.Size() / 2f, num385, SpriteEffects.None);
                }
                return;
            }
            if (proj.type == 466)
            {
                Vector2 end = proj.position + new Vector2(proj.width, proj.height) / 2f + Vector2.UnitY * proj.gfxOffY - screenPosition;
                Texture2D value103 = TextureAssets.Extra[33].Value;
                proj.GetAlpha(projectileColor);
                Vector2 vector96 = new Vector2(proj.scale) / 2f;
                for (int num387 = 0; num387 < 3; num387++)
                {
                    switch (num387)
                    {
                    case 0:
                        vector96 = new Vector2(proj.scale) * 0.6f;
                        DelegateMethods.c_1 = new Microsoft.Xna.Framework.Color(115, 204, 219, 0) * 0.5f;
                        break;
                    case 1:
                        vector96 = new Vector2(proj.scale) * 0.4f;
                        DelegateMethods.c_1 = new Microsoft.Xna.Framework.Color(113, 251, 255, 0) * 0.5f;
                        break;
                    default:
                        vector96 = new Vector2(proj.scale) * 0.2f;
                        DelegateMethods.c_1 = new Microsoft.Xna.Framework.Color(255, 255, 255, 0) * 0.5f;
                        break;
                    }
                    DelegateMethods.f_1 = 1f;
                    for (int num388 = proj.oldPos.Length - 1; num388 > 0; num388--)
                    {
                        if (!(proj.oldPos[num388] == Vector2.Zero))
{
                            Vector2 start = proj.oldPos[num388] + new Vector2(proj.width, proj.height) / 2f + Vector2.UnitY * proj.gfxOffY - screenPosition;
                            Vector2 end2 = proj.oldPos[num388 - 1] + new Vector2(proj.width, proj.height) / 2f + Vector2.UnitY * proj.gfxOffY - screenPosition;
                            Utils.DrawLaser(spriteBatch, value103, start, end2, vector96, DelegateMethods.LightningLaserDraw);
                        }
                    }
                    if (proj.oldPos[0] != Vector2.Zero)
                    {
                        DelegateMethods.f_1 = 1f;
                        Vector2 start2 = proj.oldPos[0] + new Vector2(proj.width, proj.height) / 2f + Vector2.UnitY * proj.gfxOffY - screenPosition;
                        Utils.DrawLaser(spriteBatch, value103, start2, end, vector96, DelegateMethods.LightningLaserDraw);
                    }
                }
                return;
            }
            if (proj.type == 580)
            {
                Vector2 end3 = proj.position + new Vector2(proj.width, proj.height) / 2f + Vector2.UnitY * proj.gfxOffY - screenPosition;
                Texture2D value104 = TextureAssets.Extra[33].Value;
                proj.GetAlpha(projectileColor);
                Vector2 vector97 = new Vector2(proj.scale) / 2f;
                for (int num389 = 0; num389 < 2; num389++)
                {
                    float num390 = ((proj.localAI[1] == -1f || proj.localAI[1] == 1f) ? (-0.2f) : 0f);
                    if (num389 == 0)
                    {
                        vector97 = new Vector2(proj.scale) * (0.5f + num390);
                        DelegateMethods.c_1 = new Microsoft.Xna.Framework.Color(115, 244, 219, 0) * 0.5f;
                    }
                    else
                    {
                        vector97 = new Vector2(proj.scale) * (0.3f + num390);
                        DelegateMethods.c_1 = new Microsoft.Xna.Framework.Color(255, 255, 255, 0) * 0.5f;
                    }
                    DelegateMethods.f_1 = 1f;
                    for (int num391 = proj.oldPos.Length - 1; num391 > 0; num391--)
                    {
                        if (!(proj.oldPos[num391] == Vector2.Zero))
{
                            Vector2 start3 = proj.oldPos[num391] + new Vector2(proj.width, proj.height) / 2f + Vector2.UnitY * proj.gfxOffY - screenPosition;
                            Vector2 end4 = proj.oldPos[num391 - 1] + new Vector2(proj.width, proj.height) / 2f + Vector2.UnitY * proj.gfxOffY - screenPosition;
                            Utils.DrawLaser(spriteBatch, value104, start3, end4, vector97, DelegateMethods.LightningLaserDraw);
                        }
                    }
                    if (proj.oldPos[0] != Vector2.Zero)
                    {
                        DelegateMethods.f_1 = 1f;
                        Vector2 start4 = proj.oldPos[0] + new Vector2(proj.width, proj.height) / 2f + Vector2.UnitY * proj.gfxOffY - screenPosition;
                        Utils.DrawLaser(spriteBatch, value104, start4, end3, vector97, DelegateMethods.LightningLaserDraw);
                    }
                }
                return;
            }
            if (proj.type == 445)
            {
                if (Main.player[proj.owner].gravDir == -1f)
                {
                    dir |= SpriteEffects.FlipVertically;
                }
                Vector2 vector98 = proj.position + new Vector2(proj.width, proj.height) / 2f + Vector2.UnitY * proj.gfxOffY - screenPosition;
                Texture2D value105 = TextureAssets.Projectile[proj.type].Value;
                Microsoft.Xna.Framework.Color alpha10 = proj.GetAlpha(projectileColor);
                Vector2 vector99 = Main.player[proj.owner].RotatedRelativePoint(mountedCenter) + Vector2.UnitY * Main.player[proj.owner].gfxOffY;
                Vector2 vector100 = vector98 + screenPosition - vector99;
                Vector2 vector101 = Vector2.Normalize(vector100);
                float num392 = vector100.Length();
                float num393 = vector100.ToRotation() + (float)Math.PI / 2f;
                float num394 = -5f;
                float num395 = num394 + 30f;
                new Vector2(2f, num392 - num395);
                Vector2 vector102 = Vector2.Lerp(vector98 + screenPosition, vector99 + vector101 * num395, 0.5f);
                Vector2 vector103 = -Vector2.UnitY.RotatedBy(proj.localAI[0] / 60f * (float)Math.PI);
                Vector2[] array7 = new Vector2[4]
                {
                    vector103,
                    vector103.RotatedBy(1.5707963705062866),
                    vector103.RotatedBy(3.1415927410125732),
                    vector103.RotatedBy(4.71238899230957)
                };
                if (num392 > num395)
                {
                    for (int num396 = 0; num396 < 2; num396++)
                    {
                        Microsoft.Xna.Framework.Color white4 = Microsoft.Xna.Framework.Color.White;
                        if (num396 % 2 == 0)
{
                            white4 = Microsoft.Xna.Framework.Color.LimeGreen;
                            white4.A = 128;
                            white4 *= 0.5f;
                        }
                        else
{
                            white4 = Microsoft.Xna.Framework.Color.CornflowerBlue;
                            white4.A = 128;
                            white4 *= 0.5f;
                        }
                        Vector2 vector104 = new Vector2(array7[num396].X, 0f).RotatedBy(num393) * 4f;
                        EntitySpriteDraw(TextureAssets.MagicPixel.Value, vector102 - screenPosition + vector104, new Microsoft.Xna.Framework.Rectangle(0, 0, 1, 1), white4, num393, Vector2.One / 2f, new Vector2(2f, num392 - num395), dir);
                    }
                }
                int type2 = Main.player[proj.owner].inventory[Main.player[proj.owner].selectedItem].type;
                instance.LoadItem(type2);
                Texture2D value106 = TextureAssets.Item[type2].Value;
                Microsoft.Xna.Framework.Color color108 = Lighting.GetColor((int)vector99.X / 16, (int)vector99.Y / 16);
                EntitySpriteDraw(value106, vector99 - screenPosition + vector101 * num394, null, color108, proj.rotation + (float)Math.PI / 2f + ((dir == SpriteEffects.None || dir == SpriteEffects.FlipVertically) ? ((float)Math.PI) : 0f), new Vector2((dir != 0 && dir != SpriteEffects.FlipVertically) ? value106.Width : 0, (float)value106.Height / 2f) + Vector2.UnitY * 1f, Main.player[proj.owner].inventory[Main.player[proj.owner].selectedItem].scale, dir);
                EntitySpriteDraw(TextureAssets.GlowMask[39].Value, vector99 - screenPosition + vector101 * num394, null, new Microsoft.Xna.Framework.Color(255, 255, 255, 0), proj.rotation + (float)Math.PI / 2f + ((dir == SpriteEffects.None || dir == SpriteEffects.FlipVertically) ? ((float)Math.PI) : 0f), new Vector2((dir != 0 && dir != SpriteEffects.FlipVertically) ? value106.Width : 0, (float)value106.Height / 2f) + Vector2.UnitY * 1f, Main.player[proj.owner].inventory[Main.player[proj.owner].selectedItem].scale, dir);
                if (num392 > num395)
                {
                    for (int num397 = 2; num397 < 4; num397++)
                    {
                        Microsoft.Xna.Framework.Color white5 = Microsoft.Xna.Framework.Color.White;
                        if (num397 % 2 == 0)
{
                            white5 = Microsoft.Xna.Framework.Color.LimeGreen;
                            white5.A = 128;
                            white5 *= 0.5f;
                        }
                        else
{
                            white5 = Microsoft.Xna.Framework.Color.CornflowerBlue;
                            white5.A = 128;
                            white5 *= 0.5f;
                        }
                        Vector2 vector105 = new Vector2(array7[num397].X, 0f).RotatedBy(num393) * 4f;
                        EntitySpriteDraw(TextureAssets.MagicPixel.Value, vector102 - screenPosition + vector105, new Microsoft.Xna.Framework.Rectangle(0, 0, 1, 1), white5, num393, Vector2.One / 2f, new Vector2(2f, num392 - num395), dir);
                    }
                }
                float num398 = proj.localAI[0] / 60f;
                if (num398 > 0.5f)
                {
                    num398 = 1f - num398;
                }
                EntitySpriteDraw(value105, vector98, null, alpha10 * num398 * 2f, proj.rotation, new Vector2(value105.Width, value105.Height) / 2f, proj.scale, dir);
                EntitySpriteDraw(TextureAssets.GlowMask[40].Value, vector98, null, alpha10 * (0.5f - num398) * 2f, proj.rotation, new Vector2(value105.Width, value105.Height) / 2f, proj.scale, dir);
                return;
            }
            if ((proj.type >= 393 && proj.type <= 395) || proj.type == 398 || proj.type == 423 || proj.type == 450)
            {
                Texture2D value107 = TextureAssets.Projectile[proj.type].Value;
                int num399 = TextureAssets.Projectile[proj.type].Height() / projFrames[proj.type];
                int y24 = num399 * proj.frame;
                EntitySpriteDraw(value107, proj.Center - screenPosition + new Vector2(0f, proj.gfxOffY - 2f), new Microsoft.Xna.Framework.Rectangle(0, y24, value107.Width, num399), proj.GetAlpha(projectileColor), proj.rotation, new Vector2((float)value107.Width / 2f, (float)num399 / 2f), proj.scale, dir);
                if (proj.type == 398)
                {
                    value107 = TextureAssets.MiniMinotaur.Value;
                    EntitySpriteDraw(value107, proj.Center - screenPosition + new Vector2(0f, proj.gfxOffY - 2f), new Microsoft.Xna.Framework.Rectangle(0, y24, value107.Width, num399), new Microsoft.Xna.Framework.Color(250, 250, 250, proj.alpha), proj.rotation, new Vector2((float)value107.Width / 2f, (float)num399 / 2f), proj.scale, dir);
                }
                if (proj.type == 423)
                {
                    value107 = TextureAssets.GlowMask[0].Value;
                    EntitySpriteDraw(value107, proj.Center - screenPosition + new Vector2(0f, proj.gfxOffY - 2f), new Microsoft.Xna.Framework.Rectangle(0, y24, value107.Width, num399), new Microsoft.Xna.Framework.Color(250, 250, 250, proj.alpha), proj.rotation, new Vector2((float)value107.Width / 2f, (float)num399 / 2f), proj.scale, dir);
                }
                return;
            }
            if (proj.type == 385)
            {
                Texture2D value108 = TextureAssets.Projectile[proj.type].Value;
                int num400 = value108.Height / projFrames[proj.type];
                int y25 = num400 * proj.frame;
                int num401 = 8;
                int num402 = 2;
                float value109 = 0.4f;
                for (int num403 = 1; num403 < num401; num403 += num402)
                {
                    _ = ref proj.oldPos[num403];
                    Microsoft.Xna.Framework.Color newColor3 = projectileColor;
                    newColor3 = proj.GetAlpha(newColor3);
                    newColor3 *= (float)(num401 - num403) / 15f;
                    Microsoft.Xna.Framework.Color alpha11 = proj.GetAlpha(projectileColor);
                    _ = proj.oldPos[num403] - screenPosition + new Vector2(num138 + (float)num137, (float)(proj.height / 2) + proj.gfxOffY);
                    EntitySpriteDraw(value108, proj.oldPos[num403] + new Vector2(proj.width, proj.height) / 2f - screenPosition + new Vector2(0f, proj.gfxOffY), new Microsoft.Xna.Framework.Rectangle(0, y25, value108.Width, num400), Microsoft.Xna.Framework.Color.Lerp(alpha11, newColor3, 0.3f), proj.rotation, new Vector2((float)value108.Width / 2f, (float)num400 / 2f), MathHelper.Lerp(proj.scale, value109, (float)num403 / 15f), dir);
                }
                EntitySpriteDraw(value108, proj.Center - screenPosition + new Vector2(0f, proj.gfxOffY), new Microsoft.Xna.Framework.Rectangle(0, y25, value108.Width, num400), proj.GetAlpha(projectileColor), proj.rotation, new Vector2((float)value108.Width / 2f, (float)num400 / 2f), proj.scale, dir);
                return;
            }
            if (proj.type == 388)
            {
                Texture2D value110 = TextureAssets.Projectile[proj.type].Value;
                int num404 = value110.Height / projFrames[proj.type];
                int y26 = num404 * proj.frame;
                int num405 = 0;
                int num406 = 0;
                if (proj.ai[0] == 2f)
                {
                    num405 = 10;
                    num406 = 1;
                }
                else
                {
                    num405 = 3;
                    num406 = 1;
                }
                for (int num407 = 1; num407 < num405; num407 += num406)
                {
                    _ = ref proj.oldPos[num407];
                    Microsoft.Xna.Framework.Color newColor4 = projectileColor;
                    newColor4 = proj.GetAlpha(newColor4);
                    newColor4 *= (float)(num405 - num407) / 15f;
                    Vector2 position25 = proj.oldPos[num407] - screenPosition + new Vector2(num138 + (float)num137, (float)(proj.height / 2) + proj.gfxOffY);
                    EntitySpriteDraw(value110, position25, new Microsoft.Xna.Framework.Rectangle(0, y26, value110.Width, num404), newColor4, proj.rotation, new Vector2(num138, proj.height / 2 + num136), proj.scale, dir);
                }
                EntitySpriteDraw(value110, proj.position - screenPosition + new Vector2(num138 + (float)num137, (float)(proj.height / 2) + proj.gfxOffY), new Microsoft.Xna.Framework.Rectangle(0, y26, value110.Width, num404), proj.GetAlpha(projectileColor), proj.rotation, new Vector2(num138, proj.height / 2 + num136), proj.scale, dir);
                return;
            }
            if (projFrames[proj.type] > 1)
            {
                int num408 = TextureAssets.Projectile[proj.type].Height() / projFrames[proj.type];
                int y27 = num408 * proj.frame;
                if (proj.type == 111)
                {
                    int r = Main.player[proj.owner].shirtColor.R;
                    int g = Main.player[proj.owner].shirtColor.G;
                    int b = Main.player[proj.owner].shirtColor.B;
                    projectileColor = Lighting.GetColor(oldColor: new Microsoft.Xna.Framework.Color((byte)r, (byte)g, (byte)b), x: (int)((double)proj.position.X + (double)proj.width * 0.5) / 16, y: (int)(((double)proj.position.Y + (double)proj.height * 0.5) / 16.0));
                    EntitySpriteDraw(TextureAssets.Projectile[proj.type].Value, new Vector2(proj.position.X - screenPosition.X + num138 + (float)num137, proj.position.Y - screenPosition.Y + (float)(proj.height / 2) + proj.gfxOffY), new Microsoft.Xna.Framework.Rectangle(0, y27, TextureAssets.Projectile[proj.type].Width(), num408), proj.GetAlpha(projectileColor), proj.rotation, new Vector2(num138, proj.height / 2 + num136), proj.scale, dir);
                    return;
                }
                Microsoft.Xna.Framework.Color alpha12 = proj.GetAlpha(projectileColor);
                if (proj.type == 211 && CurrentDrawnEntityShader != 0)
                {
                    alpha12.A = 127;
                }
                if (proj.type == 344)
                {
                    float num409 = MathHelper.Min(60f, proj.ai[0]) / 2f;
                    for (float num410 = 0.9f; num410 > 0f; num410 -= 0.25f)
                    {
                        Vector2 vector106 = num410 * (proj.velocity * 0.33f) * num409;
                        EntitySpriteDraw(TextureAssets.Projectile[proj.type].Value, new Vector2(proj.position.X - screenPosition.X + num138 + (float)num137, proj.position.Y - screenPosition.Y + (float)(proj.height / 2) + proj.gfxOffY) - vector106, new Microsoft.Xna.Framework.Rectangle(0, y27, TextureAssets.Projectile[proj.type].Width(), num408 - 1), alpha12 * (1f - num410) * 0.75f, proj.rotation, new Vector2(num138, proj.height / 2 + num136), proj.scale * (0.4f + (1f - num410) * 0.6f), dir);
                    }
                }
                if (proj.type == 920 || proj.type == 921)
                {
                    for (float num411 = 0.25f; num411 < 1f; num411 += 0.5f)
                    {
                        Vector2 vector107 = num411 * proj.velocity * 4f;
                        EntitySpriteDraw(TextureAssets.Projectile[proj.type].Value, new Vector2(proj.position.X - screenPosition.X + num138 + (float)num137, proj.position.Y - screenPosition.Y + (float)(proj.height / 2) + proj.gfxOffY) - vector107, new Microsoft.Xna.Framework.Rectangle(0, y27, TextureAssets.Projectile[proj.type].Width(), num408 - 1), alpha12 * (1f - num411) * 0.75f, proj.rotation, new Vector2(num138, proj.height / 2 + num136), proj.scale, dir);
                    }
                }
                EntitySpriteDraw(TextureAssets.Projectile[proj.type].Value, new Vector2(proj.position.X - screenPosition.X + num138 + (float)num137, proj.position.Y - screenPosition.Y + (float)(proj.height / 2) + proj.gfxOffY), new Microsoft.Xna.Framework.Rectangle(0, y27, TextureAssets.Projectile[proj.type].Width(), num408 - 1), alpha12, proj.rotation, new Vector2(num138, proj.height / 2 + num136), proj.scale, dir);
                if (proj.type == 966)
                {
                    Vector2 vector108 = new Vector2(0f, -30f);
                    vector108.Y += -1f + (float)(Math.Cos((float)(int)mouseTextColor / 255f * ((float)Math.PI * 2f) * 2f) * 2.0);
                    Vector2 vector109 = new Vector2(-1f, -1f);
                    float num412 = 3f;
                    Vector2 vector110 = proj.Center + vector108;
                    Vector2 vector111 = proj.Center;
                    int num413 = (int)proj.ai[1];
                    if (num413 >= 0)
                    {
                        if (npc[num413].active)
{
                            vector111 = npc[num413].Center;
                        }
                        else
{
                            num413 = -1;
                        }
                    }
                    if (num413 <= -1)
                    {
                        Player player5 = Main.player[proj.owner];
                        vector111 = ((!player5.dead) ? player5.Center : (vector110 + new Vector2(2f, 0f)));
                    }
                    vector109 += (vector111 - vector110).SafeNormalize(Vector2.Zero) * num412;
                    EntitySpriteDraw(TextureAssets.Projectile[proj.type].Value, new Vector2(proj.position.X - screenPosition.X + num138 + (float)num137, proj.position.Y - screenPosition.Y + (float)(proj.height / 2) + proj.gfxOffY) + vector108, new Microsoft.Xna.Framework.Rectangle(0, num408, TextureAssets.Projectile[proj.type].Width(), num408 - 1), alpha12, proj.rotation, new Vector2(num138, proj.height / 2 + num136), proj.scale, dir);
                    EntitySpriteDraw(TextureAssets.Projectile[proj.type].Value, new Vector2(proj.position.X - screenPosition.X + num138 + (float)num137, proj.position.Y - screenPosition.Y + (float)(proj.height / 2) + proj.gfxOffY) + vector108 + vector109, new Microsoft.Xna.Framework.Rectangle(0, num408 * 2, TextureAssets.Projectile[proj.type].Width(), num408 - 1), alpha12, proj.rotation, new Vector2(num138, proj.height / 2 + num136), proj.scale, dir);
                }
                if (proj.type == 335)
                {
                    EntitySpriteDraw(TextureAssets.Projectile[proj.type].Value, new Vector2(proj.position.X - screenPosition.X + num138 + (float)num137, proj.position.Y - screenPosition.Y + (float)(proj.height / 2) + proj.gfxOffY), new Microsoft.Xna.Framework.Rectangle(0, y27, TextureAssets.Projectile[proj.type].Width(), num408 - 1), new Microsoft.Xna.Framework.Color(100, 100, 100, 0), proj.rotation, new Vector2(num138, proj.height / 2 + num136), proj.scale, dir);
                }
                if (proj.type == 897 || proj.type == 899)
                {
                    int num414 = 279;
                    if (proj.type == 899)
                    {
                        num414 = 281;
                    }
                    EntitySpriteDraw(TextureAssets.GlowMask[num414].Value, new Vector2(proj.position.X - screenPosition.X + num138 + (float)num137, proj.position.Y - screenPosition.Y + (float)(proj.height / 2) + proj.gfxOffY), new Microsoft.Xna.Framework.Rectangle(0, y27, TextureAssets.Projectile[proj.type].Width(), num408 - 1), Microsoft.Xna.Framework.Color.White, proj.rotation, new Vector2(num138, proj.height / 2 + num136), proj.scale, dir);
                }
                if (proj.type == 891)
                {
                    float num415 = Utils.WrappedLerp(0.6f, 1f, (float)((int)timeForVisualEffects % 100) / 100f);
                    EntitySpriteDraw(color: new Microsoft.Xna.Framework.Color(num415, num415, num415, 150f), texture: TextureAssets.GlowMask[277].Value, position: new Vector2(proj.position.X - screenPosition.X + num138 + (float)num137, proj.position.Y - screenPosition.Y + (float)(proj.height / 2) + proj.gfxOffY), sourceRectangle: new Microsoft.Xna.Framework.Rectangle(0, y27, TextureAssets.Projectile[proj.type].Width(), num408 - 1), rotation: proj.rotation, origin: new Vector2(num138, proj.height / 2 + num136), scale: proj.scale, effects: dir);
                }
                if (proj.type == 595)
                {
                    Player player6 = Main.player[proj.owner];
                    if (player6.active && player6.body == 208)
                    {
                        for (float num416 = 0f; num416 <= 1f; num416 += 0.2f)
{
                            Microsoft.Xna.Framework.Color underShirtColor = player6.underShirtColor;
                            underShirtColor.A = (byte)(120f * (1f - num416 * 0.5f));
                            EntitySpriteDraw(TextureAssets.Projectile[proj.type].Value, new Vector2(proj.position.X - screenPosition.X + num138 + (float)num137, proj.position.Y - screenPosition.Y + (float)(proj.height / 2) + proj.gfxOffY), new Microsoft.Xna.Framework.Rectangle(0, y27, TextureAssets.Projectile[proj.type].Width(), num408 - 1), underShirtColor, proj.rotation, new Vector2(num138, proj.height / 2 + num136), proj.scale * MathHelper.Lerp(0.8f, 1.3f, num416), dir);
                        }
                    }
                }
                if (proj.type == 387)
                {
                    EntitySpriteDraw(TextureAssets.EyeLaserSmall.Value, new Vector2(proj.position.X - screenPosition.X + num138 + (float)num137, proj.position.Y - screenPosition.Y + (float)(proj.height / 2) + proj.gfxOffY), new Microsoft.Xna.Framework.Rectangle(0, y27, TextureAssets.Projectile[proj.type].Width(), num408), new Microsoft.Xna.Framework.Color(255, 255, 255, 0), proj.rotation, new Vector2(num138, proj.height / 2 + num136), proj.scale, dir);
                }
                if (proj.type != 525 && proj.type != 960)
                {
                    return;
                }
                int num417 = TryInteractingWithMoneyTrough(proj);
                if (num417 == 0)
                {
                    return;
                }
                int num418 = (projectileColor.R + projectileColor.G + projectileColor.B) / 3;
                if (num418 > 10)
                {
                    int num419 = 94;
                    if (proj.type == 960)
                    {
                        num419 = 244;
                    }
                    Microsoft.Xna.Framework.Color selectionGlowColor = Colors.GetSelectionGlowColor(num417 == 2, num418);
                    EntitySpriteDraw(TextureAssets.Extra[num419].Value, new Vector2(proj.position.X - screenPosition.X + num138 + (float)num137, proj.position.Y - screenPosition.Y + (float)(proj.height / 2) + proj.gfxOffY), new Microsoft.Xna.Framework.Rectangle(0, y27, TextureAssets.Projectile[proj.type].Width(), num408 - 1), selectionGlowColor, proj.rotation, new Vector2(num138, proj.height / 2 + num136), 1f, dir);
                }
                return;
            }
            if (proj.type == 383 || proj.type == 399)
            {
                Texture2D value111 = TextureAssets.Projectile[proj.type].Value;
                EntitySpriteDraw(value111, proj.Center - screenPosition, null, proj.GetAlpha(projectileColor), proj.rotation, new Vector2(value111.Width, value111.Height) / 2f, proj.scale, dir);
                return;
            }
            if (proj.type == 157 || proj.type == 378)
            {
                EntitySpriteDraw(TextureAssets.Projectile[proj.type].Value, new Vector2(proj.position.X - screenPosition.X + (float)(proj.width / 2), proj.position.Y - screenPosition.Y + (float)(proj.height / 2)), new Microsoft.Xna.Framework.Rectangle(0, 0, TextureAssets.Projectile[proj.type].Width(), TextureAssets.Projectile[proj.type].Height()), proj.GetAlpha(projectileColor), proj.rotation, new Vector2(TextureAssets.Projectile[proj.type].Width() / 2, TextureAssets.Projectile[proj.type].Height() / 2), proj.scale, dir);
                return;
            }
            if (proj.type == 306)
            {
                EntitySpriteDraw(TextureAssets.Projectile[proj.type].Value, new Vector2(proj.position.X - screenPosition.X + (float)(proj.width / 2), proj.position.Y - screenPosition.Y + (float)(proj.height / 2)), new Microsoft.Xna.Framework.Rectangle(0, 0, TextureAssets.Projectile[proj.type].Width(), TextureAssets.Projectile[proj.type].Height()), proj.GetAlpha(projectileColor), proj.rotation, new Vector2(TextureAssets.Projectile[proj.type].Width() / 2, TextureAssets.Projectile[proj.type].Height() / 2), proj.scale, dir);
                return;
            }
            if (proj.type == 256)
            {
                EntitySpriteDraw(TextureAssets.Projectile[proj.type].Value, new Vector2(proj.position.X - screenPosition.X + (float)(proj.width / 2), proj.position.Y - screenPosition.Y + (float)(proj.height / 2)), new Microsoft.Xna.Framework.Rectangle(0, 0, TextureAssets.Projectile[proj.type].Width(), TextureAssets.Projectile[proj.type].Height()), proj.GetAlpha(projectileColor), proj.rotation, new Vector2(TextureAssets.Projectile[proj.type].Width() / 2, TextureAssets.Projectile[proj.type].Height() / 2), proj.scale, dir);
                return;
            }
            if (proj.aiStyle == 27)
            {
                EntitySpriteDraw(TextureAssets.Projectile[proj.type].Value, new Vector2(proj.position.X - screenPosition.X + (float)(proj.width / 2), proj.position.Y - screenPosition.Y + (float)(proj.height / 2)), new Microsoft.Xna.Framework.Rectangle(0, 0, TextureAssets.Projectile[proj.type].Width(), TextureAssets.Projectile[proj.type].Height()), proj.GetAlpha(projectileColor), proj.rotation, new Vector2(TextureAssets.Projectile[proj.type].Width(), 0f), proj.scale, dir);
                return;
            }
            if (proj.aiStyle == 19)
            {
                DrawProj_Spear(proj, ref projectileColor, ref dir);
                return;
            }
            if (proj.type == 451)
            {
                EntitySpriteDraw(TextureAssets.Projectile[proj.type].Value, proj.Center - screenPosition, null, proj.GetAlpha(projectileColor), proj.rotation, new Vector2(TextureAssets.Projectile[proj.type].Width(), 0f), proj.scale, dir);
                return;
            }
            if (proj.type == 434)
            {
                Vector2 vector112 = new Vector2(proj.ai[0], proj.ai[1]);
                Vector2 v = proj.position - vector112;
                float num420 = (float)Math.Sqrt(v.X * v.X + v.Y * v.Y);
                new Vector2(4f, num420);
                float rotation30 = v.ToRotation() + (float)Math.PI / 2f;
                Vector2 vector113 = Vector2.Lerp(proj.position, vector112, 0.5f);
                Microsoft.Xna.Framework.Color red = Microsoft.Xna.Framework.Color.Red;
                red.A = 0;
                Microsoft.Xna.Framework.Color white6 = Microsoft.Xna.Framework.Color.White;
                red *= proj.localAI[0];
                white6 *= proj.localAI[0];
                float num421 = (float)Math.Sqrt(proj.damage / 50);
                EntitySpriteDraw(TextureAssets.MagicPixel.Value, vector113 - screenPosition, new Microsoft.Xna.Framework.Rectangle(0, 0, 1, 1), red, rotation30, Vector2.One / 2f, new Vector2(2f * num421, num420 + 8f), dir);
                EntitySpriteDraw(TextureAssets.MagicPixel.Value, vector113 - screenPosition, new Microsoft.Xna.Framework.Rectangle(0, 0, 1, 1), red, rotation30, Vector2.One / 2f, new Vector2(4f * num421, num420), dir);
                EntitySpriteDraw(TextureAssets.MagicPixel.Value, vector113 - screenPosition, new Microsoft.Xna.Framework.Rectangle(0, 0, 1, 1), white6, rotation30, Vector2.One / 2f, new Vector2(2f * num421, num420), dir);
                return;
            }
            if (proj.type == 94 && proj.ai[1] > 6f)
            {
                for (int num422 = 0; num422 < 10; num422++)
                {
                    Microsoft.Xna.Framework.Color alpha13 = proj.GetAlpha(projectileColor);
                    float num423 = (float)(9 - num422) / 9f;
                    alpha13.R = (byte)((float)(int)alpha13.R * num423);
                    alpha13.G = (byte)((float)(int)alpha13.G * num423);
                    alpha13.B = (byte)((float)(int)alpha13.B * num423);
                    alpha13.A = (byte)((float)(int)alpha13.A * num423);
                    float num424 = (float)(9 - num422) / 9f;
                    EntitySpriteDraw(TextureAssets.Projectile[proj.type].Value, new Vector2(proj.oldPos[num422].X - screenPosition.X + num138 + (float)num137, proj.oldPos[num422].Y - screenPosition.Y + (float)(proj.height / 2) + proj.gfxOffY), new Microsoft.Xna.Framework.Rectangle(0, 0, TextureAssets.Projectile[proj.type].Width(), TextureAssets.Projectile[proj.type].Height()), alpha13, proj.rotation, new Vector2(num138, proj.height / 2 + num136), num424 * proj.scale, dir);
                }
            }
            if (proj.type == 301)
            {
                for (int num425 = 0; num425 < 10; num425++)
                {
                    Microsoft.Xna.Framework.Color alpha14 = proj.GetAlpha(projectileColor);
                    float num426 = (float)(9 - num425) / 9f;
                    alpha14.R = (byte)((float)(int)alpha14.R * num426);
                    alpha14.G = (byte)((float)(int)alpha14.G * num426);
                    alpha14.B = (byte)((float)(int)alpha14.B * num426);
                    alpha14.A = (byte)((float)(int)alpha14.A * num426);
                    float num427 = (float)(9 - num425) / 9f;
                    EntitySpriteDraw(TextureAssets.Projectile[proj.type].Value, new Vector2(proj.oldPos[num425].X - screenPosition.X + num138 + (float)num137, proj.oldPos[num425].Y - screenPosition.Y + (float)(proj.height / 2) + proj.gfxOffY), new Microsoft.Xna.Framework.Rectangle(0, 0, TextureAssets.Projectile[proj.type].Width(), TextureAssets.Projectile[proj.type].Height()), alpha14, proj.rotation, new Vector2(num138, proj.height / 2 + num136), num427 * proj.scale, dir);
                }
            }
            if (proj.type == 323 && proj.alpha == 0)
            {
                for (int num428 = 1; num428 < 8; num428++)
                {
                    float num429 = proj.velocity.X * (float)num428;
                    float num430 = proj.velocity.Y * (float)num428;
                    Microsoft.Xna.Framework.Color alpha15 = proj.GetAlpha(projectileColor);
                    float num431 = 0f;
                    if (num428 == 1)
                    {
                        num431 = 0.7f;
                    }
                    if (num428 == 2)
                    {
                        num431 = 0.6f;
                    }
                    if (num428 == 3)
                    {
                        num431 = 0.5f;
                    }
                    if (num428 == 4)
                    {
                        num431 = 0.4f;
                    }
                    if (num428 == 5)
                    {
                        num431 = 0.3f;
                    }
                    if (num428 == 6)
                    {
                        num431 = 0.2f;
                    }
                    if (num428 == 7)
                    {
                        num431 = 0.1f;
                    }
                    alpha15.R = (byte)((float)(int)alpha15.R * num431);
                    alpha15.G = (byte)((float)(int)alpha15.G * num431);
                    alpha15.B = (byte)((float)(int)alpha15.B * num431);
                    alpha15.A = (byte)((float)(int)alpha15.A * num431);
                    EntitySpriteDraw(TextureAssets.Projectile[proj.type].Value, new Vector2(proj.position.X - screenPosition.X + num138 + (float)num137 - num429, proj.position.Y - screenPosition.Y + (float)(proj.height / 2) + proj.gfxOffY - num430), new Microsoft.Xna.Framework.Rectangle(0, 0, TextureAssets.Projectile[proj.type].Width(), TextureAssets.Projectile[proj.type].Height()), alpha15, proj.rotation, new Vector2(num138, proj.height / 2 + num136), num431 + 0.2f, dir);
                }
            }
            if (proj.type == 117 && proj.ai[0] > 3f)
            {
                for (int num432 = 1; num432 < 5; num432++)
                {
                    float num433 = proj.velocity.X * (float)num432;
                    float num434 = proj.velocity.Y * (float)num432;
                    Microsoft.Xna.Framework.Color alpha16 = proj.GetAlpha(projectileColor);
                    float num435 = 0f;
                    if (num432 == 1)
                    {
                        num435 = 0.4f;
                    }
                    if (num432 == 2)
                    {
                        num435 = 0.3f;
                    }
                    if (num432 == 3)
                    {
                        num435 = 0.2f;
                    }
                    if (num432 == 4)
                    {
                        num435 = 0.1f;
                    }
                    alpha16.R = (byte)((float)(int)alpha16.R * num435);
                    alpha16.G = (byte)((float)(int)alpha16.G * num435);
                    alpha16.B = (byte)((float)(int)alpha16.B * num435);
                    alpha16.A = (byte)((float)(int)alpha16.A * num435);
                    EntitySpriteDraw(TextureAssets.Projectile[proj.type].Value, new Vector2(proj.position.X - screenPosition.X + num138 + (float)num137 - num433, proj.position.Y - screenPosition.Y + (float)(proj.height / 2) + proj.gfxOffY - num434), new Microsoft.Xna.Framework.Rectangle(0, 0, TextureAssets.Projectile[proj.type].Width(), TextureAssets.Projectile[proj.type].Height()), alpha16, proj.rotation, new Vector2(num138, proj.height / 2 + num136), proj.scale, dir);
                }
            }
            if (proj.bobber)
            {
                if (proj.ai[1] > 0f && proj.ai[1] < (float)ItemID.Count && proj.ai[0] == 1f)
                {
                    int num436 = (int)proj.ai[1];
                    Vector2 center5 = proj.Center;
                    float rotation31 = proj.rotation;
                    Vector2 vector114 = center5;
                    float num437 = polePosX - vector114.X;
                    float num438 = polePosY - vector114.Y;
                    rotation31 = (float)Math.Atan2(num438, num437);
                    if (proj.velocity.X > 0f)
                    {
                        dir = SpriteEffects.None;
                        rotation31 = (float)Math.Atan2(num438, num437);
                        rotation31 += 0.785f;
                        if (proj.ai[1] == 2342f)
{
                            rotation31 -= 0.785f;
                        }
                    }
                    else
                    {
                        dir = SpriteEffects.FlipHorizontally;
                        rotation31 = (float)Math.Atan2(0f - num438, 0f - num437);
                        rotation31 -= 0.785f;
                        if (proj.ai[1] == 2342f)
{
                            rotation31 += 0.785f;
                        }
                    }
                    instance.LoadItem(num436);
                    Texture2D value112 = TextureAssets.Item[num436].Value;
                    Microsoft.Xna.Framework.Rectangle value113 = value112.Frame();
                    if (ItemID.Sets.IsFood[num436] && itemAnimations[num436] != null)
                    {
                        value113 = itemAnimations[num436].GetFrame(value112, 0);
                    }
                    EntitySpriteDraw(value112, new Vector2(center5.X - screenPosition.X, center5.Y - screenPosition.Y), value113, projectileColor, rotation31, new Vector2(value113.Width / 2, value113.Height / 2), proj.scale, dir);
                }
                else if (proj.ai[0] <= 1f)
                {
                    EntitySpriteDraw(TextureAssets.Projectile[proj.type].Value, new Vector2(proj.position.X - screenPosition.X + num138 + (float)num137, proj.position.Y - screenPosition.Y + (float)(proj.height / 2) + proj.gfxOffY), new Microsoft.Xna.Framework.Rectangle(0, 0, TextureAssets.Projectile[proj.type].Width(), TextureAssets.Projectile[proj.type].Height()), proj.GetAlpha(projectileColor), proj.rotation, new Vector2(num138, proj.height / 2 + num136), proj.scale, dir);
                    if (proj.glowMask != -1)
                    {
                        Texture2D value114 = TextureAssets.GlowMask[proj.glowMask].Value;
                        Microsoft.Xna.Framework.Color newColor5 = Microsoft.Xna.Framework.Color.White;
                        if (proj.type == 993)
{
                            newColor5 = new Microsoft.Xna.Framework.Color(DiscoR, DiscoG, DiscoB);
                        }
                        EntitySpriteDraw(value114, new Vector2(proj.position.X - screenPosition.X + num138 + (float)num137, proj.position.Y - screenPosition.Y + (float)(proj.height / 2) + proj.gfxOffY), new Microsoft.Xna.Framework.Rectangle(0, 0, value114.Width, value114.Height), proj.GetAlpha(newColor5), proj.rotation, new Vector2(num138, proj.height / 2 + num136), proj.scale, dir);
                    }
                }
            }
            else
            {
                if (proj.ownerHitCheck && Main.player[proj.owner].gravDir == -1f)
                {
                    if (Main.player[proj.owner].direction == 1)
                    {
                        dir = SpriteEffects.FlipHorizontally;
                    }
                    else if (Main.player[proj.owner].direction == -1)
                    {
                        dir = SpriteEffects.None;
                    }
                }
                EntitySpriteDraw(TextureAssets.Projectile[proj.type].Value, new Vector2(proj.position.X - screenPosition.X + num138 + (float)num137, proj.position.Y - screenPosition.Y + (float)(proj.height / 2) + proj.gfxOffY), new Microsoft.Xna.Framework.Rectangle(0, 0, TextureAssets.Projectile[proj.type].Width(), TextureAssets.Projectile[proj.type].Height()), proj.GetAlpha(projectileColor), proj.rotation, new Vector2(num138, proj.height / 2 + num136), proj.scale, dir);
                if (proj.glowMask != -1)
                {
                    EntitySpriteDraw(TextureAssets.GlowMask[proj.glowMask].Value, new Vector2(proj.position.X - screenPosition.X + num138 + (float)num137, proj.position.Y - screenPosition.Y + (float)(proj.height / 2) + proj.gfxOffY), new Microsoft.Xna.Framework.Rectangle(0, 0, TextureAssets.Projectile[proj.type].Width(), TextureAssets.Projectile[proj.type].Height()), new Microsoft.Xna.Framework.Color(250, 250, 250, proj.alpha), proj.rotation, new Vector2(num138, proj.height / 2 + num136), proj.scale, dir);
                }
                if (proj.type == 473)
                {
                    EntitySpriteDraw(TextureAssets.Projectile[proj.type].Value, new Vector2(proj.position.X - screenPosition.X + num138 + (float)num137, proj.position.Y - screenPosition.Y + (float)(proj.height / 2) + proj.gfxOffY), new Microsoft.Xna.Framework.Rectangle(0, 0, TextureAssets.Projectile[proj.type].Width(), TextureAssets.Projectile[proj.type].Height()), new Microsoft.Xna.Framework.Color(255, 255, 0, 0), proj.rotation, new Vector2(num138, proj.height / 2 + num136), proj.scale, dir);
                }
                if (proj.type >= 511 && proj.type <= 513)
                {
                    EntitySpriteDraw(TextureAssets.Projectile[proj.type].Value, new Vector2(proj.position.X - screenPosition.X + num138 + (float)num137, proj.position.Y - screenPosition.Y + (float)(proj.height / 2) + proj.gfxOffY), new Microsoft.Xna.Framework.Rectangle(0, 0, TextureAssets.Projectile[proj.type].Width(), TextureAssets.Projectile[proj.type].Height()), proj.GetAlpha(projectileColor) * 0.25f, proj.rotation, new Vector2(num138, proj.height / 2 + num136), proj.scale * (1f + proj.Opacity * 1.75f), dir);
                }
                if (proj.type == 312)
                {
                    ulong seed3 = TileFrameSeed;
                    for (int num439 = 0; num439 < 4; num439++)
                    {
                        Vector2 vector115 = new Vector2(Utils.RandomInt(ref seed3, -2, 3), Utils.RandomInt(ref seed3, -2, 3));
                        EntitySpriteDraw(TextureAssets.GlowMask[proj.glowMask].Value, new Vector2(proj.position.X - screenPosition.X + num138 + (float)num137, proj.position.Y - screenPosition.Y + (float)(proj.height / 2) + proj.gfxOffY) + vector115, new Microsoft.Xna.Framework.Rectangle(0, 0, TextureAssets.Projectile[proj.type].Width(), TextureAssets.Projectile[proj.type].Height()), new Microsoft.Xna.Framework.Color(255, 255, 255, 255) * 0.2f, proj.rotation, new Vector2(num138, proj.height / 2 + num136), proj.scale, dir);
                    }
                }
            }
            if (proj.type == 106)
            {
                Texture2D value115 = TextureAssets.LightDisc.Value;
                Vector2 position26 = new Vector2(proj.position.X - screenPosition.X + num138 + (float)num137, proj.position.Y - screenPosition.Y + (float)(proj.height / 2));
                Microsoft.Xna.Framework.Rectangle value116 = value115.Frame();
                EntitySpriteDraw(value115, position26, value116, new Microsoft.Xna.Framework.Color(200, 200, 200, 0), proj.rotation, new Vector2(num138, proj.height / 2 + num136), proj.scale, dir);
            }
            if (proj.type >= 326 && proj.type <= 328)
            {
                ulong seed4 = TileFrameSeed;
                for (int num440 = 0; num440 < 4; num440++)
                {
                    Vector2 vector116 = new Vector2(Utils.RandomInt(ref seed4, -2, 3), Utils.RandomInt(ref seed4, -2, 3));
                    EntitySpriteDraw(TextureAssets.Projectile[proj.type].Value, new Vector2(proj.position.X - screenPosition.X + num138 + (float)num137, proj.position.Y - screenPosition.Y + (float)(proj.height / 2)) + vector116 - proj.velocity * 0.25f * num440, new Microsoft.Xna.Framework.Rectangle(0, 0, TextureAssets.Projectile[proj.type].Width(), TextureAssets.Projectile[proj.type].Height()), new Microsoft.Xna.Framework.Color(120, 120, 120, 60) * 1f, proj.rotation, new Vector2(num138, proj.height / 2 + num136), proj.scale - (float)num440 * 0.2f, dir);
                }
            }
            if (proj.type == 554 || proj.type == 603)
            {
                for (int num441 = 1; num441 < 5; num441++)
                {
                    float num442 = proj.velocity.X * (float)num441 * 0.5f;
                    float num443 = proj.velocity.Y * (float)num441 * 0.5f;
                    Microsoft.Xna.Framework.Color alpha17 = proj.GetAlpha(projectileColor);
                    float num444 = 0f;
                    if (num441 == 1)
                    {
                        num444 = 0.4f;
                    }
                    if (num441 == 2)
                    {
                        num444 = 0.3f;
                    }
                    if (num441 == 3)
                    {
                        num444 = 0.2f;
                    }
                    if (num441 == 4)
                    {
                        num444 = 0.1f;
                    }
                    alpha17.R = (byte)((float)(int)alpha17.R * num444);
                    alpha17.G = (byte)((float)(int)alpha17.G * num444);
                    alpha17.B = (byte)((float)(int)alpha17.B * num444);
                    alpha17.A = (byte)((float)(int)alpha17.A * num444);
                    EntitySpriteDraw(TextureAssets.Projectile[proj.type].Value, new Vector2(proj.position.X - screenPosition.X + num138 + (float)num137 - num442, proj.position.Y - screenPosition.Y + (float)(proj.height / 2) + proj.gfxOffY - num443), new Microsoft.Xna.Framework.Rectangle(0, 0, TextureAssets.Projectile[proj.type].Width(), TextureAssets.Projectile[proj.type].Height()), alpha17, proj.rotation, new Vector2(num138, proj.height / 2 + num136), proj.scale, dir);
                }
            }
            else if (proj.type == 604)
            {
                int num445 = (int)proj.ai[1] + 1;
                if (num445 > 7)
                {
                    num445 = 7;
                }
                for (int num446 = 1; num446 < num445; num446++)
                {
                    float num447 = proj.velocity.X * (float)num446 * 1.5f;
                    float num448 = proj.velocity.Y * (float)num446 * 1.5f;
                    Microsoft.Xna.Framework.Color alpha18 = proj.GetAlpha(projectileColor);
                    float num449 = 0f;
                    if (num446 == 1)
                    {
                        num449 = 0.4f;
                    }
                    if (num446 == 2)
                    {
                        num449 = 0.3f;
                    }
                    if (num446 == 3)
                    {
                        num449 = 0.2f;
                    }
                    if (num446 == 4)
                    {
                        num449 = 0.1f;
                    }
                    num449 = 0.4f - (float)num446 * 0.06f;
                    num449 *= 1f - (float)proj.alpha / 255f;
                    alpha18.R = (byte)((float)(int)alpha18.R * num449);
                    alpha18.G = (byte)((float)(int)alpha18.G * num449);
                    alpha18.B = (byte)((float)(int)alpha18.B * num449);
                    alpha18.A = (byte)((float)(int)alpha18.A * num449 / 2f);
                    float scale15 = proj.scale;
                    scale15 -= (float)num446 * 0.1f;
                    EntitySpriteDraw(TextureAssets.Projectile[proj.type].Value, new Vector2(proj.position.X - screenPosition.X + num138 + (float)num137 - num447, proj.position.Y - screenPosition.Y + (float)(proj.height / 2) + proj.gfxOffY - num448), new Microsoft.Xna.Framework.Rectangle(0, 0, TextureAssets.Projectile[proj.type].Width(), TextureAssets.Projectile[proj.type].Height()), alpha18, proj.rotation, new Vector2(num138, proj.height / 2 + num136), scale15, dir);
                }
            }
            else
            {
                if (proj.type != 553)
                {
                    return;
                }
                for (int num450 = 1; num450 < 5; num450++)
                {
                    float num451 = proj.velocity.X * (float)num450 * 0.4f;
                    float num452 = proj.velocity.Y * (float)num450 * 0.4f;
                    Microsoft.Xna.Framework.Color alpha19 = proj.GetAlpha(projectileColor);
                    float num453 = 0f;
                    if (num450 == 1)
                    {
                        num453 = 0.4f;
                    }
                    if (num450 == 2)
                    {
                        num453 = 0.3f;
                    }
                    if (num450 == 3)
                    {
                        num453 = 0.2f;
                    }
                    if (num450 == 4)
                    {
                        num453 = 0.1f;
                    }
                    alpha19.R = (byte)((float)(int)alpha19.R * num453);
                    alpha19.G = (byte)((float)(int)alpha19.G * num453);
                    alpha19.B = (byte)((float)(int)alpha19.B * num453);
                    alpha19.A = (byte)((float)(int)alpha19.A * num453);
                    EntitySpriteDraw(TextureAssets.Projectile[proj.type].Value, new Vector2(proj.position.X - screenPosition.X + num138 + (float)num137 - num451, proj.position.Y - screenPosition.Y + (float)(proj.height / 2) + proj.gfxOffY - num452), new Microsoft.Xna.Framework.Rectangle(0, 0, TextureAssets.Projectile[proj.type].Width(), TextureAssets.Projectile[proj.type].Height()), alpha19, proj.rotation, new Vector2(num138, proj.height / 2 + num136), proj.scale, dir);
                }
            }
        }
    }
References Terraria.Main._stardewAnimation, Terraria.Main._tempSeededRandom, Terraria.Main._voidLensData, System.Math.Abs(), Terraria.Lighting.AddLight(), Terraria.Projectile.AI_192_GetJuminoFall(), System.array, System.Math.Atan2(), Microsoft.Xna.Framework.Color.Black, Microsoft.Xna.Framework.Color.Blue, Terraria.GameContent.Golf.GolfHelper.CalculateShotStrength(), Terraria.GameContent.TextureAssets.Chain, Terraria.GameContent.TextureAssets.Chain15, Terraria.GameContent.TextureAssets.Chain16, Terraria.GameContent.TextureAssets.Chain17, Terraria.GameContent.TextureAssets.Chain18, Terraria.GameContent.TextureAssets.Chain20, Terraria.GameContent.TextureAssets.Chain22, Terraria.GameContent.TextureAssets.Chain23, Terraria.GameContent.TextureAssets.Chain28, Terraria.GameContent.TextureAssets.Chain29, Terraria.GameContent.TextureAssets.Chain30, Terraria.GameContent.TextureAssets.Chain31, Terraria.GameContent.TextureAssets.Chain32, Terraria.GameContent.TextureAssets.Chain33, Terraria.GameContent.TextureAssets.Chain34, Terraria.GameContent.TextureAssets.Chain35, Terraria.GameContent.TextureAssets.Chain36, Terraria.GameContent.TextureAssets.Chain37, Terraria.GameContent.TextureAssets.Chain38, Terraria.GameContent.TextureAssets.Chain39, Terraria.GameContent.TextureAssets.Chain40, Terraria.GameContent.TextureAssets.Chain5, Terraria.GameContent.TextureAssets.Chain8, Terraria.GameContent.TextureAssets.Chain9, Terraria.GameContent.TextureAssets.Chains, Microsoft.Xna.Framework.MathHelper.Clamp(), System.Collections.Generic.List< T >.Clear(), Microsoft.Xna.Framework.Color.CornflowerBlue, System.Math.Cos(), Terraria.ID.ItemID.Count, Microsoft.Xna.Framework.Color.Crimson, Terraria.Main.CurrentDrawnEntityShader, Terraria.Main.DiscoB, Terraria.Main.DiscoG, Terraria.Main.DiscoR, Microsoft.Xna.Framework.MathHelper.Distance(), Microsoft.Xna.Framework.Vector2.Distance(), Terraria.ID.ProjectileID.Sets.DontAttachHideToAlpha, Microsoft.Xna.Framework.Vector2.Dot(), Terraria.Main.DrawContinuousTrail(), Terraria.Main.DrawElderEye(), Terraria.Main.DrawKite(), Terraria.Utils.DrawLaser(), Terraria.Main.DrawMultisegmentPet(), Terraria.Main.DrawMurderAurora(), Terraria.GameContent.Golf.GolfHelper.DrawPredictionLine(), Terraria.Main.DrawPrettyStarSparkle(), Terraria.Main.DrawProj(), Terraria.Main.DrawProj_CoolWhipMinion(), Terraria.Main.DrawProj_EmpressBlade(), Terraria.Main.DrawProj_Excalibur(), Terraria.Main.DrawProj_FairyQueenLance(), Terraria.Main.DrawProj_FairyQueenRangedItemShot(), Terraria.Main.DrawProj_FishingLine(), Terraria.Main.DrawProj_FlailChains(), Terraria.Main.DrawProj_Flamethrower(), Terraria.Main.DrawProj_LightsBane(), Terraria.Main.DrawProj_NightsEdge(), Terraria.Main.DrawProj_PiercingStarlight(), Terraria.Main.DrawProj_Spear(), Terraria.Main.DrawProj_StardustGuardianPunching(), Terraria.Main.DrawProj_TerraBlade2(), Terraria.Main.DrawProj_TerraBlade2Shot(), Terraria.Main.DrawProj_TheHorsemansBlade(), Terraria.Main.DrawProj_TrueExcalibur(), Terraria.Main.DrawProj_TrueNightsEdge(), Terraria.Main.DrawProjWithStarryTrail(), Terraria.Main.DrawTwinsPet(), Terraria.Main.DrawWhip(), Terraria.Main.EntitySpriteDraw(), Terraria.Collision.ExpandVertically(), Terraria.GameContent.TextureAssets.Extra, Terraria.GameContent.TextureAssets.EyeLaserSmall, Terraria.GameContent.TextureAssets.FishingLine, Terraria.GameContent.TextureAssets.Flames, System.Math.Floor(), Terraria.Main.gamePaused, Terraria.GameContent.TextureAssets.GemChain, Terraria.Lighting.GetColor(), Terraria.Graphics.FinalFractalHelper.GetFinalFractalProfile(), Terraria.Projectile.GetGolfTrailColor(), Terraria.Utils.GetLerpValue(), Terraria.GameContent.PortalHelper.GetPortalColor(), Terraria.ID.Colors.GetSelectionGlowColor(), Terraria.Main.GlobalTimeWrappedHourly, Terraria.GameContent.TextureAssets.GlowMask, Microsoft.Xna.Framework.Color.Gold, Terraria.GameContent.TextureAssets.GolfBallOutline, Microsoft.Xna.Framework.Color.HotPink, Terraria.Main.hslToRgb(), System.Text.RegularExpressions.i, System.Math.IEEERemainder(), Terraria.Main.instance, Terraria.WorldGen.InWorld(), Terraria.ID.ProjectileID.Sets.IsAGolfBall, Terraria.ID.ItemID.Sets.IsFood, Terraria.GameContent.Golf.GolfHelper.IsGolfBallResting(), Terraria.GameContent.Golf.GolfHelper.IsGolfShotValid(), Terraria.GameContent.Golf.GolfHelper.IsPlayerHoldingClub(), Terraria.GameContent.TextureAssets.Item, Terraria.Main.itemAnimations, Microsoft.Xna.Framework.Color.Lerp(), Microsoft.Xna.Framework.MathHelper.Lerp(), Microsoft.Xna.Framework.Vector2.Lerp(), Microsoft.Xna.Framework.Vector4.Lerp(), Terraria.GameContent.TextureAssets.LightDisc, Terraria.DelegateMethods.LightningLaserDraw(), Microsoft.Xna.Framework.Color.LimeGreen, Terraria.Main.LoadNPC(), Terraria.Main.LoadProjectile(), Terraria.Main.LocalPlayer, Terraria.GameContent.TextureAssets.MagicPixel, System.Math.Max(), Microsoft.Xna.Framework.MathHelper.Max(), System.Math.Min(), Microsoft.Xna.Framework.MathHelper.Min(), Terraria.GameContent.TextureAssets.MiniMinotaur, Terraria.Main.mouseTextColor, Terraria.Main.MouseWorld, Terraria.Main.myPlayer, Microsoft.Xna.Framework.Vector2.Normalize(), Terraria.GameContent.TextureAssets.Npc, Terraria.Main.npc, Microsoft.Xna.Framework.Vector2.One, Microsoft.Xna.Framework.Vector4.One, Microsoft.Xna.Framework.Color.Orange, Terraria.Main.OurFavoriteColor, System.Math.PI, Terraria.Main.player, Terraria.GameContent.TextureAssets.RenderTargets.PlayerTitaniumStormBuff, Terraria.Main.PrepareDrawnProjectileDrawing(), Terraria.GameContent.TextureAssets.Projectile, Terraria.Main.projectile, Terraria.Main.projFrames, Microsoft.Xna.Framework.Color.Purple, Terraria.DelegateMethods.RainbowLaserDraw(), Terraria.Main.rand, Terraria.Utils.RandomFloat(), Terraria.Utils.RandomInt(), Microsoft.Xna.Framework.Color.Red, Terraria.Utils.Remap(), Terraria.Main.rgbToHsl(), Terraria.Main.screenHeight, Terraria.Main.screenPosition, Terraria.Main.screenWidth, Terraria.NPC.ShouldEmpressBeEnraged(), System.Math.Sign(), System.Math.Sin(), Microsoft.Xna.Framework.Vector2.SmoothStep(), Terraria.Main.spriteBatch, System.Math.Sqrt(), System.start, Terraria.Main.tenthAnniversaryWorld, Terraria.Main.tile, Terraria.Main.TileFrameSeed, Terraria.Main.time, Terraria.Main.timeForVisualEffects, Terraria.GameContent.UI.WiresUI.Settings.ToolMode, Microsoft.Xna.Framework.Color.ToVector4(), Terraria.ID.ProjectileID.Sets.TrailCacheLength, Terraria.ID.ProjectileID.Sets.TrailingMode, Microsoft.Xna.Framework.Color.Transparent, Terraria.Main.TryApplyingPlayerStringColor(), Terraria.Main.TryInteractingWithMoneyTrough(), Terraria.Main.TryInteractingWithVoidLens(), Terraria.DelegateMethods.TurretLaserDraw(), System.type, Microsoft.Xna.Framework.Vector2.UnitY, Terraria.GameContent.Golf.GolfHelper.ValidateShot(), System.value, Microsoft.Xna.Framework.Graphics.Vector2, Microsoft.Xna.Framework.Graphics.Vector3, Microsoft.Xna.Framework.Color.Violet, Microsoft.Xna.Framework.Color.White, Terraria.GameContent.TextureAssets.WireUi, Terraria.Utils.WrappedLerp(), Microsoft.Xna.Framework.Point.X, Microsoft.Xna.Framework.Vector2.X, System.X, Microsoft.Xna.Framework.Point.Y, Microsoft.Xna.Framework.Vector2.Y, Microsoft.Xna.Framework.Color.Yellow, and Microsoft.Xna.Framework.Vector2.Zero.
Referenced by Terraria.Main.DrawProj().