Terraria: Terraria.Main.DrawInterface_11_IngameOptionsMenu
DrawInterface_11_IngameOptionsMenu()
bool Terraria.Main.DrawInterface_11_IngameOptionsMenu () inline private
Definition at line 43122 of file Main.cs.
    {
        bool result = true;
        if (ingameOptionsWindow)
        {
            DrawInterface_16_MapOrMinimap();
            PlayerInput.SetZoom_UI();
            Matrix uIScaleMatrix = UIScaleMatrix;
            spriteBatch.End();
            spriteBatch.Begin(SpriteSortMode.Deferred, null, null, null, null, null, uIScaleMatrix);
            IngameOptions.Draw(this, spriteBatch);
            DrawInterface_40_InteractItemIcon();
            DrawPendingMouseText();
            result = false;
            _MouseOversCanClear = true;
        }
        return result;
    }
References Terraria.Main._MouseOversCanClear, Terraria.IngameOptions.Draw(), Terraria.Main.DrawInterface_16_MapOrMinimap(), Terraria.Main.DrawInterface_40_InteractItemIcon(), Terraria.Main.DrawPendingMouseText(), Terraria.Main.ingameOptionsWindow, Terraria.GameInput.PlayerInput.SetZoom_UI(), Terraria.Main.spriteBatch, and Terraria.Main.UIScaleMatrix.
Referenced by Terraria.Main.SetupDrawInterfaceLayers().