Terraria: Terraria.Main.DrawPendingMouseText
DrawPendingMouseText()
static void Terraria.Main.DrawPendingMouseText () inline static private
Definition at line 41922 of file Main.cs.
    {
        DrawGamepadInstructions();
        if (instance._mouseTextCache.isValid)
        {
            instance.MouseTextInner(instance._mouseTextCache);
            DrawInterface_36_Cursor();
            instance._mouseTextCache.isValid = false;
            instance._mouseTextCache.noOverride = false;
        }
    }
References Terraria.Main.DrawGamepadInstructions(), Terraria.Main.DrawInterface_36_Cursor(), and Terraria.Main.instance.
Referenced by Terraria.Main.DoDraw(), Terraria.Main.DrawInterface_10_CheckCaptureManager(), Terraria.Main.DrawInterface_11_IngameOptionsMenu(), Terraria.Main.DrawInterface_12_IngameFancyUI(), Terraria.Main.DrawInterface_41_InterfaceLogic4(), Terraria.Main.DrawInterface_8_CheckF11UIHideToggle(), and Terraria.Main.DrawMenu().