Terraria: Terraria.Main.clrInput
clrInput()
static void Terraria.Main.clrInput () inline static
Definition at line 18584 of file Main.cs.
    {
        keyCount = 0;
        inputTextEscape = false;
    }
References Terraria.Main.inputTextEscape, and Terraria.Main.keyCount.
Referenced by Terraria.GameContent.UI.States.UICharacterCreation.Click_Naming(), Terraria.GameContent.UI.States.UICharacterCreation.Click_NamingAndCreating(), Terraria.GameContent.UI.States.UIWorldCreation.Click_NamingAndCreating(), Terraria.GameContent.UI.States.UIWorldCreation.Click_SetName(), Terraria.GameContent.UI.States.UIWorldCreation.Click_SetSeed(), Terraria.Main.DrawMenu(), Terraria.GameContent.UI.Elements.UIWorkshopImportWorldListItem.ImportButtonClick_ImportWorldToLocalFiles(), Terraria.Social.WeGame.NetClientSocialModule.OnAuthSuccess(), Terraria.Social.Steam.NetClientSocialModule.OnLobbyEntered(), Terraria.Main.OnSubmitServerIP(), Terraria.Main.OpenPlayerChat(), Terraria.UI.IngameFancyUI.OpenVirtualKeyboard(), Terraria.GameContent.UI.Elements.UIWorldListItem.PlayGame(), Terraria.GameContent.UI.Elements.UICharacterListItem.RenameButtonClick(), Terraria.GameContent.UI.Elements.UIWorldListItem.RenameButtonClick(), Terraria.Main.SelectPlayer(), and Terraria.GameContent.UI.Elements.UISearchBar.ToggleTakingText().