Terraria: Terraria.Main.SkipToTime
SkipToTime()
static void Terraria.Main.SkipToTime (int timeToSet, bool setIsDayTime) inline static
Definition at line 61890 of file Main.cs.
    {
        _ = time;
        _ = dayTime;
        while (setIsDayTime != dayTime)
        {
            bool stopEvents = ShouldNormalEventsBeAbleToStart();
            if (dayTime)
            {
                UpdateTime_StartNight(ref stopEvents);
            }
            else
            {
                UpdateTime_StartDay(ref stopEvents);
            }
        }
        time = timeToSet;
        if (netMode == 2)
        {
            NetMessage.TrySendData(7);
        }
    }
References Terraria.Main.dayTime, Terraria.Main.netMode, Terraria.Main.ShouldNormalEventsBeAbleToStart(), Terraria.Main.time, Terraria.NetMessage.TrySendData(), Terraria.Main.UpdateTime_StartDay(), and Terraria.Main.UpdateTime_StartNight().
Referenced by Terraria.GameContent.Creative.CreativePowers.StartDayImmediately.UsePower(), Terraria.GameContent.Creative.CreativePowers.StartNightImmediately.UsePower(), Terraria.GameContent.Creative.CreativePowers.StartNoonImmediately.UsePower(), and Terraria.GameContent.Creative.CreativePowers.StartMidnightImmediately.UsePower().