Terraria: Terraria.Main.ShouldShowInvisibleWalls
ShouldShowInvisibleWalls()
static bool Terraria.Main.ShouldShowInvisibleWalls () inline static
    {
        if (!SceneMetrics.EchoMonolith)
        {
            return LocalPlayer.CanSeeInvisibleBlocks;
        }
        return true;
    }
References Terraria.SceneMetrics.EchoMonolith, and Terraria.Main.LocalPlayer.
Referenced by Terraria.Main.DrawBlack(), Terraria.HitTile.DrawFreshAnimations(), Terraria.Main.DrawTileCracks(), Terraria.Graphics.Light.LegacyLighting.PreRenderPhase(), Terraria.Graphics.Light.LightingEngine.ProcessScan(), Terraria.WorldGen.TileFrame(), Terraria.GameContent.Drawing.TileDrawing.Update(), Terraria.GameContent.Drawing.WallDrawing.Update(), Terraria.Framing.WallFrame(), and Terraria.Main.WallLightAt().