Terraria: Terraria.Main.DrawSurfaceBG_GetLayerYOffset
DrawSurfaceBG_GetLayerYOffset()
int Terraria.Main.DrawSurfaceBG_GetLayerYOffset (int bgTextureIndex) inline private
Definition at line 56695 of file Main.cs.
    {
        switch (bgTextureIndex)
        {
        case 59:
            return -550;
        case 93:
        case 168:
        case 169:
        case 170:
            return -50;
        case 171:
            return -100;
        case 172:
            return 130;
        case 176:
            return -760;
        case 177:
            return -200;
        case 179:
            return -100;
        case 180:
        case 181:
        case 182:
        case 183:
            return -350;
        case 246:
            return -150;
        case 247:
            return -150;
        case 263:
            return -700;
        case 269:
            return -100;
        case 270:
            return -50;
        case 271:
            return -300;
        case 272:
            return -380;
        case 277:
            return -260;
        case 278:
            return -120;
        case 280:
            return -170;
        case 281:
            return -300;
        case 283:
            return -800;
        default:
            return 0;
        }
    }
Referenced by Terraria.Main.DrawSurfaceBG_DrawBackMountainsLayer(), Terraria.Main.DrawSurfaceBG_Jungle(), Terraria.Main.DrawSurfaceBG_Snow(), and Terraria.Main.UpdateOceanWaterLineForAmbience().