Terraria: Terraria.Main.DrawSurfaceBG_DrawBackMountainsLayer
DrawSurfaceBG_DrawBackMountainsLayer()
void Terraria.Main.DrawSurfaceBG_DrawBackMountainsLayer (int bgTextureIndex) inline private
Definition at line 56680 of file Main.cs.
    {
        if (bgTextureIndex >= 0)
        {
            LoadBackground(bgTextureIndex);
            int num = DrawSurfaceBG_GetLayerYOffset(bgTextureIndex);
            bgTopY += num;
            for (int i = 0; i < bgLoops; i++)
            {
                spriteBatch.Draw(TextureAssets.Background[bgTextureIndex].Value, new Vector2(bgStartX + bgWidthScaled * i, bgTopY), GetBackgroundRect(bgTextureIndex), ColorOfSurfaceBackgroundsModified, 0f, default(Vector2), bgScale, SpriteEffects.None, 0f);
            }
            bgTopY -= num;
        }
    }
References Terraria.GameContent.TextureAssets.Background, Terraria.Main.bgLoops, Terraria.Main.bgScale, Terraria.Main.bgStartX, Terraria.Main.bgTopY, Terraria.Main.bgWidthScaled, Terraria.Main.ColorOfSurfaceBackgroundsModified, Terraria.Main.DrawSurfaceBG_GetLayerYOffset(), Terraria.Main.GetBackgroundRect(), System.Text.RegularExpressions.i, Terraria.Main.LoadBackground(), and Terraria.Main.spriteBatch.
Referenced by Terraria.Main.DrawSurfaceBG_BackMountainsStep1(), and Terraria.Main.DrawSurfaceBG_BackMountainsStep2().