Terraria: Terraria.Main.SetBackColor
SetBackColor()
static void Terraria.Main.SetBackColor (InfoToSetBackColor info, out Microsoft::Xna::Framework::Color sunColor, out Microsoft::Xna::Framework::Color moonColor) inline static private
    {
        double num = time;
        Microsoft.Xna.Framework.Color bgColorToSet = Microsoft.Xna.Framework.Color.White;
        sunColor = Microsoft.Xna.Framework.Color.White;
        moonColor = Microsoft.Xna.Framework.Color.White;
        float num2 = 0f;
        bool isInGameMenuOrIsServer = info.isInGameMenuOrIsServer;
        if (dayTime)
        {
            if (num < 13500.0)
            {
                num2 = (float)(num / 13500.0);
                sunColor.R = (byte)(num2 * 200f + 55f);
                sunColor.G = (byte)(num2 * 180f + 75f);
                sunColor.B = (byte)(num2 * 250f + 5f);
                bgColorToSet.R = (byte)(num2 * 230f + 25f);
                bgColorToSet.G = (byte)(num2 * 220f + 35f);
                bgColorToSet.B = (byte)(num2 * 220f + 35f);
            }
            if (num > 45900.0)
            {
                num2 = (float)(1.0 - (num / 54000.0 - 0.85) * 6.666666666666667);
                sunColor.R = (byte)(num2 * 120f + 55f);
                sunColor.G = (byte)(num2 * 100f + 25f);
                sunColor.B = (byte)(num2 * 120f + 55f);
                bgColorToSet.R = (byte)(num2 * 200f + 35f);
                bgColorToSet.G = (byte)(num2 * 85f + 35f);
                bgColorToSet.B = (byte)(num2 * 135f + 35f);
            }
            else if (num > 37800.0)
            {
                num2 = (float)(1.0 - (num / 54000.0 - 0.7) * 6.666666666666667);
                sunColor.R = (byte)(num2 * 80f + 175f);
                sunColor.G = (byte)(num2 * 130f + 125f);
                sunColor.B = (byte)(num2 * 100f + 155f);
                bgColorToSet.R = (byte)(num2 * 20f + 235f);
                bgColorToSet.G = (byte)(num2 * 135f + 120f);
                bgColorToSet.B = (byte)(num2 * 85f + 170f);
            }
        }
        if (!dayTime)
        {
            if (info.BloodMoonActive)
            {
                if (num < 16200.0)
                {
                    num2 = (float)(1.0 - num / 16200.0);
                    moonColor.R = (byte)(num2 * 10f + 205f);
                    moonColor.G = (byte)(num2 * 170f + 55f);
                    moonColor.B = (byte)(num2 * 200f + 55f);
                    bgColorToSet.R = (byte)(40f - num2 * 40f + 35f);
                    bgColorToSet.G = (byte)(num2 * 20f + 15f);
                    bgColorToSet.B = (byte)(num2 * 20f + 15f);
                }
                else if (num >= 16200.0)
                {
                    num2 = (float)((num / 32400.0 - 0.5) * 2.0);
                    moonColor.R = (byte)(num2 * 50f + 205f);
                    moonColor.G = (byte)(num2 * 100f + 155f);
                    moonColor.B = (byte)(num2 * 100f + 155f);
                    moonColor.R = (byte)(num2 * 10f + 205f);
                    moonColor.G = (byte)(num2 * 170f + 55f);
                    moonColor.B = (byte)(num2 * 200f + 55f);
                    bgColorToSet.R = (byte)(40f - num2 * 40f + 35f);
                    bgColorToSet.G = (byte)(num2 * 20f + 15f);
                    bgColorToSet.B = (byte)(num2 * 20f + 15f);
                }
            }
            else if (num < 16200.0)
            {
                num2 = (float)(1.0 - num / 16200.0);
                moonColor.R = (byte)(num2 * 10f + 205f);
                moonColor.G = (byte)(num2 * 70f + 155f);
                moonColor.B = (byte)(num2 * 100f + 155f);
                bgColorToSet.R = (byte)(num2 * 30f + 5f);
                bgColorToSet.G = (byte)(num2 * 30f + 5f);
                bgColorToSet.B = (byte)(num2 * 30f + 5f);
            }
            else if (num >= 16200.0)
            {
                num2 = (float)((num / 32400.0 - 0.5) * 2.0);
                moonColor.R = (byte)(num2 * 50f + 205f);
                moonColor.G = (byte)(num2 * 100f + 155f);
                moonColor.B = (byte)(num2 * 100f + 155f);
                bgColorToSet.R = (byte)(num2 * 20f + 5f);
                bgColorToSet.G = (byte)(num2 * 30f + 5f);
                bgColorToSet.B = (byte)(num2 * 30f + 5f);
            }
            if (dontStarveWorld)
            {
                DontStarveSeed.ModifyNightColor(ref bgColorToSet, ref moonColor);
            }
        }
        if (cloudAlpha > 0f && !remixWorld)
        {
            float num3 = 1f - cloudAlpha * 0.9f * atmo;
            bgColorToSet.R = (byte)((float)(int)bgColorToSet.R * num3);
            bgColorToSet.G = (byte)((float)(int)bgColorToSet.G * num3);
            bgColorToSet.B = (byte)((float)(int)bgColorToSet.B * num3);
        }
        if (info.GraveyardInfluence > 0f && !remixWorld)
        {
            float num4 = 1f - info.GraveyardInfluence * 0.6f;
            bgColorToSet.R = (byte)((float)(int)bgColorToSet.R * num4);
            bgColorToSet.G = (byte)((float)(int)bgColorToSet.G * num4);
            bgColorToSet.B = (byte)((float)(int)bgColorToSet.B * num4);
        }
        if (isInGameMenuOrIsServer && !dayTime)
        {
            bgColorToSet.R = 35;
            bgColorToSet.G = 35;
            bgColorToSet.B = 35;
        }
        if (info.CorruptionBiomeInfluence > 0f)
        {
            float num5 = info.CorruptionBiomeInfluence;
            if (num5 > 1f)
            {
                num5 = 1f;
            }
            int r = bgColorToSet.R;
            int g = bgColorToSet.G;
            int b = bgColorToSet.B;
            r -= (int)(90f * num5 * ((float)(int)bgColorToSet.R / 255f));
            g -= (int)(140f * num5 * ((float)(int)bgColorToSet.G / 255f));
            b -= (int)(70f * num5 * ((float)(int)bgColorToSet.B / 255f));
            if (r < 15)
            {
                r = 15;
            }
            if (g < 15)
            {
                g = 15;
            }
            if (b < 15)
            {
                b = 15;
            }
            DontStarveSeed.FixBiomeDarkness(ref bgColorToSet, ref r, ref g, ref b);
            bgColorToSet.R = (byte)r;
            bgColorToSet.G = (byte)g;
            bgColorToSet.B = (byte)b;
            r = sunColor.R;
            g = sunColor.G;
            b = sunColor.B;
            r -= (int)(100f * num5 * ((float)(int)sunColor.R / 255f));
            g -= (int)(100f * num5 * ((float)(int)sunColor.G / 255f));
            b -= (int)(0f * num5 * ((float)(int)sunColor.B / 255f));
            if (r < 15)
            {
                r = 15;
            }
            if (g < 15)
            {
                g = 15;
            }
            if (b < 15)
            {
                b = 15;
            }
            sunColor.R = (byte)r;
            sunColor.G = (byte)g;
            sunColor.B = (byte)b;
        }
        if (info.CrimsonBiomeInfluence > 0f)
        {
            float num6 = info.CrimsonBiomeInfluence;
            if (num6 > 1f)
            {
                num6 = 1f;
            }
            int r2 = bgColorToSet.R;
            int g2 = bgColorToSet.G;
            int b2 = bgColorToSet.B;
            r2 -= (int)(40f * num6 * ((float)(int)bgColorToSet.G / 255f));
            g2 -= (int)(110f * num6 * ((float)(int)bgColorToSet.G / 255f));
            b2 -= (int)(140f * num6 * ((float)(int)bgColorToSet.B / 255f));
            if (r2 < 15)
            {
                r2 = 15;
            }
            if (g2 < 15)
            {
                g2 = 15;
            }
            if (b2 < 15)
            {
                b2 = 15;
            }
            DontStarveSeed.FixBiomeDarkness(ref bgColorToSet, ref r2, ref g2, ref b2);
            bgColorToSet.R = (byte)r2;
            bgColorToSet.G = (byte)g2;
            bgColorToSet.B = (byte)b2;
            r2 = sunColor.R;
            g2 = sunColor.G;
            b2 = sunColor.B;
            g2 -= (int)(90f * num6 * ((float)(int)sunColor.G / 255f));
            b2 -= (int)(110f * num6 * ((float)(int)sunColor.B / 255f));
            if (r2 < 15)
            {
                r2 = 15;
            }
            if (g2 < 15)
            {
                g2 = 15;
            }
            if (b2 < 15)
            {
                b2 = 15;
            }
            sunColor.R = (byte)r2;
            sunColor.G = (byte)g2;
            sunColor.B = (byte)b2;
        }
        if (info.JungleBiomeInfluence > 0f)
        {
            float num7 = info.JungleBiomeInfluence;
            if (num7 > 1f)
            {
                num7 = 1f;
            }
            int r3 = bgColorToSet.R;
            int G = bgColorToSet.G;
            int b3 = bgColorToSet.B;
            r3 -= (int)(40f * num7 * ((float)(int)bgColorToSet.R / 255f));
            b3 -= (int)(70f * num7 * ((float)(int)bgColorToSet.B / 255f));
            if (G > 255)
            {
                G = 255;
            }
            if (G < 15)
            {
                G = 15;
            }
            if (r3 > 255)
            {
                r3 = 255;
            }
            if (r3 < 15)
            {
                r3 = 15;
            }
            if (b3 < 15)
            {
                b3 = 15;
            }
            DontStarveSeed.FixBiomeDarkness(ref bgColorToSet, ref r3, ref G, ref b3);
            bgColorToSet.R = (byte)r3;
            bgColorToSet.G = (byte)G;
            bgColorToSet.B = (byte)b3;
            r3 = sunColor.R;
            G = sunColor.G;
            b3 = sunColor.B;
            r3 -= (int)(30f * num7 * ((float)(int)sunColor.R / 255f));
            b3 -= (int)(10f * num7 * ((float)(int)sunColor.B / 255f));
            if (r3 < 15)
            {
                r3 = 15;
            }
            if (G < 15)
            {
                G = 15;
            }
            if (b3 < 15)
            {
                b3 = 15;
            }
            sunColor.R = (byte)r3;
            sunColor.G = (byte)G;
            sunColor.B = (byte)b3;
        }
        if (info.MushroomBiomeInfluence > 0f)
        {
            float mushroomBiomeInfluence = info.MushroomBiomeInfluence;
            int r4 = bgColorToSet.R;
            int g3 = bgColorToSet.G;
            int b4 = bgColorToSet.B;
            g3 -= (int)(250f * mushroomBiomeInfluence * ((float)(int)bgColorToSet.G / 255f));
            r4 -= (int)(250f * mushroomBiomeInfluence * ((float)(int)bgColorToSet.R / 255f));
            b4 -= (int)(250f * mushroomBiomeInfluence * ((float)(int)bgColorToSet.B / 255f));
            if (g3 < 15)
            {
                g3 = 15;
            }
            if (r4 < 15)
            {
                r4 = 15;
            }
            if (b4 < 15)
            {
                b4 = 15;
            }
            DontStarveSeed.FixBiomeDarkness(ref bgColorToSet, ref r4, ref g3, ref b4);
            bgColorToSet.R = (byte)r4;
            bgColorToSet.G = (byte)g3;
            bgColorToSet.B = (byte)b4;
            r4 = sunColor.R;
            g3 = sunColor.G;
            b4 = sunColor.B;
            g3 -= (int)(10f * mushroomBiomeInfluence * ((float)(int)sunColor.G / 255f));
            r4 -= (int)(30f * mushroomBiomeInfluence * ((float)(int)sunColor.R / 255f));
            b4 -= (int)(10f * mushroomBiomeInfluence * ((float)(int)sunColor.B / 255f));
            if (r4 < 15)
            {
                r4 = 15;
            }
            if (g3 < 15)
            {
                g3 = 15;
            }
            if (b4 < 15)
            {
                b4 = 15;
            }
            sunColor.R = (byte)r4;
            sunColor.G = (byte)g3;
            sunColor.B = (byte)b4;
            r4 = moonColor.R;
            g3 = moonColor.G;
            b4 = moonColor.B;
            g3 -= (int)(140f * mushroomBiomeInfluence * ((float)(int)moonColor.R / 255f));
            r4 -= (int)(170f * mushroomBiomeInfluence * ((float)(int)moonColor.G / 255f));
            b4 -= (int)(190f * mushroomBiomeInfluence * ((float)(int)moonColor.B / 255f));
            if (r4 < 15)
            {
                r4 = 15;
            }
            if (g3 < 15)
            {
                g3 = 15;
            }
            if (b4 < 15)
            {
                b4 = 15;
            }
            moonColor.R = (byte)r4;
            moonColor.G = (byte)g3;
            moonColor.B = (byte)b4;
        }
        byte minimalLight = 15;
        switch (GetMoonPhase())
        {
        case MoonPhase.Empty:
            minimalLight = 11;
            break;
        case MoonPhase.QuarterAtLeft:
        case MoonPhase.QuarterAtRight:
            minimalLight = 13;
            break;
        case MoonPhase.HalfAtLeft:
        case MoonPhase.HalfAtRight:
            minimalLight = 15;
            break;
        case MoonPhase.ThreeQuartersAtLeft:
        case MoonPhase.ThreeQuartersAtRight:
            minimalLight = 17;
            break;
        case MoonPhase.Full:
            minimalLight = 19;
            break;
        }
        if (dontStarveWorld)
        {
            DontStarveSeed.ModifyMinimumLightColorAtNight(ref minimalLight);
        }
        if (bgColorToSet.R < minimalLight)
        {
            bgColorToSet.R = minimalLight;
        }
        if (bgColorToSet.G < minimalLight)
        {
            bgColorToSet.G = minimalLight;
        }
        if (bgColorToSet.B < minimalLight)
        {
            bgColorToSet.B = minimalLight;
        }
        if (info.BloodMoonActive)
        {
            if (bgColorToSet.R < 25)
            {
                bgColorToSet.R = 25;
            }
            if (bgColorToSet.G < 25)
            {
                bgColorToSet.G = 25;
            }
            if (bgColorToSet.B < 25)
            {
                bgColorToSet.B = 25;
            }
        }
        if (eclipse && dayTime)
        {
            float num8 = 1242f;
            eclipseLight = (float)(num / (double)num8);
            if (eclipseLight > 1f)
            {
                eclipseLight = 1f;
            }
        }
        else if (eclipseLight > 0f)
        {
            eclipseLight -= 0.01f;
            if (eclipseLight < 0f)
            {
                eclipseLight = 0f;
            }
        }
        if (eclipseLight > 0f)
        {
            float num9 = 1f - 0.925f * eclipseLight;
            float num10 = 1f - 0.96f * eclipseLight;
            float num11 = 1f - 1f * eclipseLight;
            int num12 = (int)((float)(int)bgColorToSet.R * num9);
            int num13 = (int)((float)(int)bgColorToSet.G * num10);
            int num14 = (int)((float)(int)bgColorToSet.B * num11);
            bgColorToSet.R = (byte)num12;
            bgColorToSet.G = (byte)num13;
            bgColorToSet.B = (byte)num14;
            sunColor.R = byte.MaxValue;
            sunColor.G = 127;
            sunColor.B = 67;
            if (bgColorToSet.R < 20)
            {
                bgColorToSet.R = 20;
            }
            if (bgColorToSet.G < 10)
            {
                bgColorToSet.G = 10;
            }
            if (!Lighting.NotRetro)
            {
                if (bgColorToSet.R < 20)
                {
                    bgColorToSet.R = 20;
                }
                if (bgColorToSet.G < 14)
                {
                    bgColorToSet.G = 14;
                }
                if (bgColorToSet.B < 6)
                {
                    bgColorToSet.B = 6;
                }
            }
        }
        if ((remixWorld && !gameMenu) || WorldGen.remixWorldGen)
        {
            bgColorToSet.R = 1;
            bgColorToSet.G = 1;
            bgColorToSet.B = 1;
        }
        if (lightning > 0f)
        {
            float value = (float)(int)bgColorToSet.R / 255f;
            float value2 = (float)(int)bgColorToSet.G / 255f;
            float value3 = (float)(int)bgColorToSet.B / 255f;
            value = MathHelper.Lerp(value, 1f, lightning);
            value2 = MathHelper.Lerp(value2, 1f, lightning);
            value3 = MathHelper.Lerp(value3, 1f, lightning);
            bgColorToSet.R = (byte)(value * 255f);
            bgColorToSet.G = (byte)(value2 * 255f);
            bgColorToSet.B = (byte)(value3 * 255f);
        }
        if (!info.BloodMoonActive)
        {
            moonColor = Microsoft.Xna.Framework.Color.White;
        }
        ColorOfTheSkies = bgColorToSet;
    }
References Terraria.Main.atmo, Terraria.Main.cloudAlpha, Terraria.Main.ColorOfTheSkies, Terraria.Main.dayTime, Terraria.Main.dontStarveWorld, Terraria.Main.eclipse, Terraria.Main.eclipseLight, ReLogic.Content.Asset< T >.Empty, Terraria.GameContent.DontStarveSeed.FixBiomeDarkness(), Terraria.Main.gameMenu, Terraria.Main.GetMoonPhase(), Terraria.Main.lightning, Terraria.GameContent.DontStarveSeed.ModifyMinimumLightColorAtNight(), Terraria.GameContent.DontStarveSeed.ModifyNightColor(), Terraria.Lighting.NotRetro, Terraria.Main.remixWorld, Terraria.WorldGen.remixWorldGen, and Terraria.Main.time.
Referenced by Terraria.Main.DoDraw(), and Terraria.Main.DrawCapture().