Terraria: Terraria.Main.ErasePlayer
ErasePlayer()
static void Terraria.Main.ErasePlayer (int i) inline static private
Definition at line 4413 of file Main.cs.
    {
        try
        {
            FileUtilities.Delete(PlayerList[i].Path, PlayerList[i].IsCloudSave);
            FileUtilities.Delete(PlayerList[i].Path + ".bak", PlayerList[i].IsCloudSave);
        }
        catch
        {
        }
        try
        {
            string text = PlayerList[i].Path.Substring(0, PlayerList[i].Path.Length - 4);
            if (text.Substring(text.Length - 1) != "." && text.Substring(text.Length - 1) != "\\" && Directory.Exists(text))
            {
                Directory.Delete(text, recursive: true);
            }
            LoadPlayers();
        }
        catch
        {
        }
    }
References System.IO.Directory.Delete(), Terraria.Utilities.FileUtilities.Delete(), System.IO.Directory.Exists(), System.Text.RegularExpressions.i, Terraria.Main.LoadPlayers(), Terraria.Main.PlayerList, and System.text.
Referenced by Terraria.Main.DrawMenu().