Terraria: Terraria.Main.LoadBackground
LoadBackground()
void Terraria.Main.LoadBackground (int i) inline
Definition at line 55998 of file Main.cs.
    {
        //IL_000e: Unknown result type (might be due to invalid IL or missing references)
        if (i >= 0 && (int)TextureAssets.Background[i].State == 0)
        {
            Assets.Request<Texture2D>(TextureAssets.Background[i].Name, (AssetRequestMode)1);
            backgroundWidth[i] = TextureAssets.Background[i].Width();
            backgroundHeight[i] = TextureAssets.Background[i].Height();
            switch (i)
            {
            case 219:
            case 220:
            case 221:
            case 235:
            case 271:
            case 272:
            case 273:
            case 281:
                backgroundWidth[i] /= 2;
                backgroundHeight[i] /= 2;
                break;
            }
        }
    }
References Terraria.Main.Assets, Terraria.GameContent.TextureAssets.Background, Terraria.Main.backgroundHeight, Terraria.Main.backgroundWidth, and System.Text.RegularExpressions.i.
Referenced by Terraria.Main.DrawBackground(), Terraria.Main.DrawSurfaceBG(), Terraria.Main.DrawSurfaceBG_Corrupt(), Terraria.Main.DrawSurfaceBG_Crimson(), Terraria.Main.DrawSurfaceBG_Desert(), Terraria.Main.DrawSurfaceBG_DrawBackMountainsLayer(), Terraria.Main.DrawSurfaceBG_Forest(), Terraria.Main.DrawSurfaceBG_GoodEvilDesert(), Terraria.Main.DrawSurfaceBG_Hallow(), Terraria.Main.DrawSurfaceBG_Jungle(), Terraria.Main.DrawSurfaceBG_Mushroom(), Terraria.Main.DrawSurfaceBG_Snow(), and Terraria.Main.OldDrawBackground().