Terraria: Terraria.Main.DrawProjWithStarryTrail
DrawProjWithStarryTrail()
void Terraria.Main.DrawProjWithStarryTrail (Projectile proj, Microsoft::Xna::Framework::Color projectileColor, SpriteEffects dir) inline private
Definition at line 34287 of file Main.cs.
    {
        Microsoft.Xna.Framework.Color color = new Microsoft.Xna.Framework.Color(255, 255, 255, projectileColor.A - proj.alpha);
        Vector2 vector = proj.velocity;
        Microsoft.Xna.Framework.Color color2 = Microsoft.Xna.Framework.Color.Blue * 0.1f;
        Vector2 spinningpoint = new Vector2(0f, -4f);
        float num = 0f;
        float t = vector.Length();
        float num2 = Utils.GetLerpValue(3f, 5f, t, clamped: true);
        bool flag = true;
        if (proj.type == 856 || proj.type == 857)
        {
            vector = proj.position - proj.oldPos[1];
            float num3 = vector.Length();
            if (num3 == 0f)
            {
                vector = Vector2.UnitY;
            }
            else
            {
                vector *= 5f / num3;
            }
            Vector2 origin = new Vector2(proj.ai[0], proj.ai[1]);
            Vector2 center = player[proj.owner].Center;
            float lerpValue = Utils.GetLerpValue(0f, 120f, origin.Distance(center), clamped: true);
            float num4 = 90f;
            if (proj.type == 857)
            {
                num4 = 60f;
                flag = false;
            }
            float lerpValue2 = Utils.GetLerpValue(num4, num4 * (5f / 6f), proj.localAI[0], clamped: true);
            float lerpValue3 = Utils.GetLerpValue(0f, 120f, proj.Center.Distance(center), clamped: true);
            lerpValue *= lerpValue3;
            lerpValue2 *= Utils.GetLerpValue(0f, 15f, proj.localAI[0], clamped: true);
            color2 = Microsoft.Xna.Framework.Color.HotPink * 0.15f * (lerpValue2 * lerpValue);
            if (proj.type == 857)
            {
                color2 = proj.GetFirstFractalColor() * 0.15f * (lerpValue2 * lerpValue);
            }
            spinningpoint = new Vector2(0f, -2f);
            float lerpValue4 = Utils.GetLerpValue(num4, num4 * (2f / 3f), proj.localAI[0], clamped: true);
            lerpValue4 *= Utils.GetLerpValue(0f, 20f, proj.localAI[0], clamped: true);
            num = -0.3f * (1f - lerpValue4);
            num += -1f * Utils.GetLerpValue(15f, 0f, proj.localAI[0], clamped: true);
            num *= lerpValue;
            num2 = lerpValue2 * lerpValue;
        }
        Vector2 vector2 = proj.Center + vector;
        Texture2D value = TextureAssets.Projectile[proj.type].Value;
        _ = new Microsoft.Xna.Framework.Rectangle(0, 0, value.Width, value.Height).Size() / 2f;
        Texture2D value2 = TextureAssets.Extra[91].Value;
        Microsoft.Xna.Framework.Rectangle value3 = value2.Frame();
        Vector2 origin2 = new Vector2((float)value3.Width / 2f, 10f);
        _ = Microsoft.Xna.Framework.Color.Cyan * 0.5f * num2;
        Vector2 vector3 = new Vector2(0f, proj.gfxOffY);
        float num5 = (float)timeForVisualEffects / 60f;
        Vector2 vector4 = vector2 + vector * 0.5f;
        Microsoft.Xna.Framework.Color color3 = Microsoft.Xna.Framework.Color.White * 0.5f * num2;
        color3.A = 0;
        Microsoft.Xna.Framework.Color color4 = color2 * num2;
        color4.A = 0;
        Microsoft.Xna.Framework.Color color5 = color2 * num2;
        color5.A = 0;
        Microsoft.Xna.Framework.Color color6 = color2 * num2;
        color6.A = 0;
        float num6 = vector.ToRotation();
        EntitySpriteDraw(value2, vector4 - screenPosition + vector3 + spinningpoint.RotatedBy((float)Math.PI * 2f * num5), value3, color4, num6 + (float)Math.PI / 2f, origin2, 1.5f + num, SpriteEffects.None);
        EntitySpriteDraw(value2, vector4 - screenPosition + vector3 + spinningpoint.RotatedBy((float)Math.PI * 2f * num5 + (float)Math.PI * 2f / 3f), value3, color5, num6 + (float)Math.PI / 2f, origin2, 1.1f + num, SpriteEffects.None);
        EntitySpriteDraw(value2, vector4 - screenPosition + vector3 + spinningpoint.RotatedBy((float)Math.PI * 2f * num5 + 4.1887903f), value3, color6, num6 + (float)Math.PI / 2f, origin2, 1.3f + num, SpriteEffects.None);
        Vector2 vector5 = vector2 - vector * 0.5f;
        for (float num7 = 0f; num7 < 1f; num7 += 0.5f)
        {
            float num8 = num5 % 0.5f / 0.5f;
            num8 = (num8 + num7) % 1f;
            float num9 = num8 * 2f;
            if (num9 > 1f)
            {
                num9 = 2f - num9;
            }
            EntitySpriteDraw(value2, vector5 - screenPosition + vector3, value3, color3 * num9, num6 + (float)Math.PI / 2f, origin2, 0.3f + num8 * 0.5f, SpriteEffects.None);
        }
        if (flag)
        {
            float rotation = proj.rotation + proj.localAI[1];
            _ = (float)timeForVisualEffects / 240f;
            _ = GlobalTimeWrappedHourly;
            float globalTimeWrappedHourly = GlobalTimeWrappedHourly;
            globalTimeWrappedHourly %= 5f;
            globalTimeWrappedHourly /= 2.5f;
            if (globalTimeWrappedHourly >= 1f)
            {
                globalTimeWrappedHourly = 2f - globalTimeWrappedHourly;
            }
            globalTimeWrappedHourly = globalTimeWrappedHourly * 0.5f + 0.5f;
            Vector2 position = proj.Center - screenPosition;
            instance.LoadItem(75);
            Texture2D value4 = TextureAssets.Item[75].Value;
            Microsoft.Xna.Framework.Rectangle rectangle = value4.Frame(1, 8);
            EntitySpriteDraw(origin: rectangle.Size() / 2f, texture: value4, position: position, sourceRectangle: rectangle, color: color, rotation: rotation, scale: proj.scale, effects: SpriteEffects.None);
        }
    }
References Microsoft.Xna.Framework.Vector2.Distance(), Terraria.Main.EntitySpriteDraw(), Terraria.GameContent.TextureAssets.Extra, Terraria.Utils.GetLerpValue(), Terraria.Main.GlobalTimeWrappedHourly, Terraria.Main.instance, Terraria.GameContent.TextureAssets.Item, System.Math.PI, Terraria.Main.player, Terraria.GameContent.TextureAssets.Projectile, Terraria.Main.screenPosition, Terraria.Main.timeForVisualEffects, Microsoft.Xna.Framework.Vector2.UnitY, System.value, and Microsoft.Xna.Framework.Graphics.Vector2.
Referenced by Terraria.Main.DrawProjDirect().