Terraria: Terraria.Main.DrawTwinsPet
DrawTwinsPet()
void Terraria.Main.DrawTwinsPet (Projectile proj) inline private
Definition at line 33772 of file Main.cs.
    {
        Texture2D value = TextureAssets.Projectile[proj.type].Value;
        SpriteEffects effects = ((proj.spriteDirection != 1) ? SpriteEffects.FlipHorizontally : SpriteEffects.None);
        Microsoft.Xna.Framework.Rectangle rectangle = value.Frame(1, projFrames[proj.type], 0, proj.frame);
        Vector2 origin = rectangle.Size() / 2f;
        Vector2 vector = proj.Center - screenPosition;
        Microsoft.Xna.Framework.Color alpha = proj.GetAlpha(Lighting.GetColor(proj.Center.ToTileCoordinates()));
        float num = 18f;
        if (proj.isAPreviewDummy)
        {
            num = 8f;
        }
        Vector2 position = vector + (GlobalTimeWrappedHourly * 2f).ToRotationVector2() * num;
        EntitySpriteDraw(value, position, rectangle, alpha, proj.rotation, origin, proj.scale, effects);
        position = vector - (GlobalTimeWrappedHourly * 2f).ToRotationVector2() * num;
        rectangle = value.Frame(1, projFrames[proj.type], 0, proj.frame + 18);
        EntitySpriteDraw(value, position, rectangle, alpha, proj.rotation, origin, proj.scale, effects);
    }
References Terraria.Main.EntitySpriteDraw(), Terraria.Lighting.GetColor(), Terraria.Main.GlobalTimeWrappedHourly, Terraria.GameContent.TextureAssets.Projectile, Terraria.Main.projFrames, Terraria.Main.screenPosition, and ReLogic.Content.Asset< T >.Value.
Referenced by Terraria.Main.DrawProjDirect().