Terraria: Terraria.Main.DrawGuideCraftText_Old
DrawGuideCraftText_Old()
static void Terraria.Main.DrawGuideCraftText_Old (int adjY, Microsoft::Xna::Framework::Color craftingTipColor, out int inventoryX, out int inventoryY) inline static private
    {
        inventoryX = 73;
        inventoryY = 331;
        inventoryY += adjY;
        int num = 0;
        int num2 = 0;
        inventoryX += num;
        inventoryY += num2;
        string text;
        if (guideItem.type > 0)
        {
            text = Lang.inter[21].Value + " " + guideItem.Name;
            DynamicSpriteFontExtensionMethods.DrawString(spriteBatch, FontAssets.MouseText.Value, Lang.inter[22].Value, new Vector2(inventoryX, inventoryY + 118), craftingTipColor, 0f, default(Vector2), 1f, SpriteEffects.None, 0f);
            int num3 = focusRecipe;
            int num4 = 0;
            for (int i = 0; i < Recipe.maxRequirements; i++)
            {
                int num5 = (i + 1) * 26;
                if (recipe[availableRecipe[num3]].requiredTile[i] == -1)
                {
                    if (i == 0 && !recipe[availableRecipe[num3]].needWater && !recipe[availableRecipe[num3]].needHoney && !recipe[availableRecipe[num3]].needLava && !recipe[availableRecipe[num3]].needSnowBiome && !recipe[availableRecipe[num3]].needGraveyardBiome)
                    {
                        DynamicSpriteFontExtensionMethods.DrawString(spriteBatch, FontAssets.MouseText.Value, Lang.inter[23].Value, new Vector2(inventoryX, inventoryY + 118 + num5), craftingTipColor, 0f, default(Vector2), 1f, SpriteEffects.None, 0f);
                    }
                    break;
                }
                num4++;
                int num6 = recipe[availableRecipe[num3]].requiredTile[i];
                DynamicSpriteFontExtensionMethods.DrawString(spriteBatch, FontAssets.MouseText.Value, Lang.GetMapObjectName(MapHelper.TileToLookup(num6, Recipe.GetRequiredTileStyle(num6))), new Vector2(inventoryX, inventoryY + 118 + num5), craftingTipColor, 0f, default(Vector2), 1f, SpriteEffects.None, 0f);
            }
            if (recipe[availableRecipe[num3]].needWater)
            {
                int num7 = (num4 + 1) * 26;
                DynamicSpriteFontExtensionMethods.DrawString(spriteBatch, FontAssets.MouseText.Value, Lang.inter[53].Value, new Vector2(inventoryX, inventoryY + 118 + num7), craftingTipColor, 0f, default(Vector2), 1f, SpriteEffects.None, 0f);
            }
            if (recipe[availableRecipe[num3]].needHoney)
            {
                int num8 = (num4 + 1) * 26;
                DynamicSpriteFontExtensionMethods.DrawString(spriteBatch, FontAssets.MouseText.Value, Lang.inter[58].Value, new Vector2(inventoryX, inventoryY + 118 + num8), craftingTipColor, 0f, default(Vector2), 1f, SpriteEffects.None, 0f);
            }
            if (recipe[availableRecipe[num3]].needLava)
            {
                int num9 = (num4 + 1) * 26;
                DynamicSpriteFontExtensionMethods.DrawString(spriteBatch, FontAssets.MouseText.Value, Lang.inter[56].Value, new Vector2(inventoryX, inventoryY + 118 + num9), craftingTipColor, 0f, default(Vector2), 1f, SpriteEffects.None, 0f);
            }
            if (recipe[availableRecipe[num3]].needSnowBiome)
            {
                int num10 = (num4 + 1) * 26;
                DynamicSpriteFontExtensionMethods.DrawString(spriteBatch, FontAssets.MouseText.Value, Lang.inter[123].Value, new Vector2(inventoryX, inventoryY + 118 + num10), craftingTipColor, 0f, default(Vector2), 1f, SpriteEffects.None, 0f);
            }
            if (recipe[availableRecipe[num3]].needGraveyardBiome)
            {
                int num11 = (num4 + 1) * 26;
                DynamicSpriteFontExtensionMethods.DrawString(spriteBatch, FontAssets.MouseText.Value, Lang.inter[124].Value, new Vector2(inventoryX, inventoryY + 118 + num11), craftingTipColor, 0f, default(Vector2), 1f, SpriteEffects.None, 0f);
            }
        }
        else
        {
            text = Lang.inter[24].Value;
        }
        inventoryX -= num;
        inventoryY -= num2;
        DynamicSpriteFontExtensionMethods.DrawString(spriteBatch, FontAssets.MouseText.Value, text, new Vector2(inventoryX + 50, inventoryY + 12), new Microsoft.Xna.Framework.Color(mouseTextColor, mouseTextColor, mouseTextColor, mouseTextColor), 0f, default(Vector2), 1f, SpriteEffects.None, 0f);
    }
References Terraria.Main.availableRecipe, ReLogic.Graphics.DynamicSpriteFontExtensionMethods.DrawString(), Terraria.Main.focusRecipe, Terraria.Lang.GetMapObjectName(), Terraria.Recipe.GetRequiredTileStyle(), Terraria.Main.guideItem, Terraria.Lang.inter, Terraria.Recipe.maxRequirements, Terraria.GameContent.FontAssets.MouseText, Terraria.Main.mouseTextColor, ReLogic.Content.Asset< T >.Name, Terraria.Main.recipe, Terraria.Main.spriteBatch, Terraria.Map.MapHelper.TileToLookup(), and ReLogic.Content.Asset< T >.Value.