Terraria: Terraria.Main.DrawWoF
DrawWoF()
void Terraria.Main.DrawWoF () inline protected
Definition at line 35022 of file Main.cs.
    {
        if (wofNPCIndex < 0 || !npc[wofNPCIndex].active || npc[wofNPCIndex].life <= 0)
        {
            return;
        }
        for (int i = 0; i < 255; i++)
        {
            if (player[i].active && player[i].tongued && !player[i].dead)
            {
                DrawWOFTongueToPlayer(i);
            }
        }
        for (int j = 0; j < 200; j++)
        {
            if (npc[j].active && npc[j].aiStyle == 29)
            {
                DrawWOFRopeToTheHungry(j);
            }
        }
        DrawWOFBody();
    }
References Terraria.Main.DrawWOFBody(), Terraria.Main.DrawWOFRopeToTheHungry(), Terraria.Main.DrawWOFTongueToPlayer(), Terraria.Main.npc, Terraria.Main.player, and Terraria.Main.wofNPCIndex.
Referenced by Terraria.Main.DoDraw_WallsTilesNPCs(), and Terraria.Main.DrawCapture().