Terraria: Terraria.Main.CacheNPCDraws
CacheNPCDraws()
void Terraria.Main.CacheNPCDraws () inline protected
Definition at line 34699 of file Main.cs.
    {
        DrawCacheNPCsMoonMoon.Clear();
        DrawCacheNPCsOverPlayers.Clear();
        DrawCacheNPCProjectiles.Clear();
        DrawCacheNPCsBehindNonSolidTiles.Clear();
        for (int i = 0; i < 200; i++)
        {
            if (!npc[i].active)
            {
                continue;
            }
            if (npc[i].type == 398 && npc[i].ai[0] >= 0f)
            {
                int num = i;
                int num2 = -1;
                int num3 = -1;
                int num4 = -1;
                for (int j = 0; j < 200; j++)
                {
                    if (npc[j].active && npc[j].ai[3] == (float)num)
                    {
                        if (num2 == -1 && npc[j].type == 397 && npc[j].ai[2] == 0f)
{
                            num2 = j;
                        }
                        if (num3 == -1 && npc[j].type == 397 && npc[j].ai[2] == 1f)
{
                            num3 = j;
                        }
                        if (num4 == -1 && npc[j].type == 396)
{
                            num4 = j;
                        }
                        if (num2 != -1 && num3 != -1 && num4 != -1)
{
                            break;
                        }
                    }
                }
                if (num2 != -1 && num3 != -1 && num4 != -1)
                {
                    DrawCacheNPCsMoonMoon.Add(num);
                    if (num2 != -1)
                    {
                        DrawCacheNPCsMoonMoon.Add(num2);
                    }
                    if (num3 != -1)
                    {
                        DrawCacheNPCsMoonMoon.Add(num3);
                    }
                    if (num4 != -1)
                    {
                        DrawCacheNPCsMoonMoon.Add(num4);
                    }
                }
            }
            else if (npc[i].type == 421 && npc[i].ai[0] == 5f)
            {
                DrawCacheNPCsOverPlayers.Add(i);
            }
            else if (npc[i].type == 516 || npc[i].type == 519)
            {
                DrawCacheNPCProjectiles.Add(i);
            }
            else if (npc[i].type == 548)
            {
                DrawCacheNPCsBehindNonSolidTiles.Add(i);
            }
        }
    }
References System.Collections.Generic.List< T >.Add(), System.Collections.Generic.List< T >.Clear(), Terraria.Main.DrawCacheNPCProjectiles, Terraria.Main.DrawCacheNPCsBehindNonSolidTiles, Terraria.Main.DrawCacheNPCsMoonMoon, Terraria.Main.DrawCacheNPCsOverPlayers, System.Text.RegularExpressions.i, Terraria.Main.npc, and System.type.
Referenced by Terraria.Main.DoDraw_WallsTilesNPCs(), and Terraria.Main.DrawCapture().