Terraria: Terraria.Main.DrawNPCHousesInUI
DrawNPCHousesInUI()
void Terraria.Main.DrawNPCHousesInUI () inline private
Definition at line 39049 of file Main.cs.
    {
        UILinkPointNavigator.Shortcuts.NPCS_LastHovered = -2;
        if (mouseX > screenWidth - 64 - 28 && mouseX < (int)((float)(screenWidth - 64 - 28) + 56f * inventoryScale) && mouseY > 174 + mH && mouseY < (int)((float)(174 + mH) + 448f * inventoryScale) && !PlayerInput.IgnoreMouseInterface)
        {
            player[myPlayer].mouseInterface = true;
        }
        int num = 0;
        string text = "";
        int num2 = 0;
        int num3 = 0;
        _npcTypesThatAlreadyDrewAHead.Clear();
        for (int i = 0; i < _npcIndexWhoHoldsHeadIndex.Length; i++)
        {
            _npcIndexWhoHoldsHeadIndex[i] = -1;
        }
        for (int j = 0; j < 200; j++)
        {
            if (npc[j].active && !_npcTypesThatAlreadyDrewAHead.Contains(npc[j].type))
            {
                int headIndexSafe = TownNPCProfiles.GetHeadIndexSafe(npc[j]);
                if (headIndexSafe > 0 && headIndexSafe <= NPCHeadID.Count && !NPCHeadID.Sets.CannotBeDrawnInHousingUI[headIndexSafe] && _npcIndexWhoHoldsHeadIndex[headIndexSafe] == -1)
                {
                    _npcIndexWhoHoldsHeadIndex[headIndexSafe] = j;
                    _npcTypesThatAlreadyDrewAHead.Add(npc[j].type);
                }
            }
        }
        hidePVPIcons = false;
        int num4 = 0;
        int num5 = 0;
        UILinkPointNavigator.Shortcuts.NPCS_IconsPerColumn = 1;
        for (int k = 0; k < TextureAssets.NpcHead.Length; k++)
        {
            if (k != 0 && _npcIndexWhoHoldsHeadIndex[k] == -1)
            {
                continue;
            }
            int num6 = _npcIndexWhoHoldsHeadIndex[k];
            int num7 = screenWidth - 64 - 28 + num3;
            int num8 = (int)((float)(174 + mH) + (float)(num * 56) * inventoryScale) + num2;
            Microsoft.Xna.Framework.Color color = new Microsoft.Xna.Framework.Color(100, 100, 100, 100);
            if (num8 > screenHeight - 80)
            {
                num3 -= 48;
                num2 -= num8 - (174 + mH);
                num7 = screenWidth - 64 - 28 + num3;
                num8 = (int)((float)(174 + mH) + (float)(num * 56) * inventoryScale) + num2;
                UILinkPointNavigator.Shortcuts.NPCS_IconsPerColumn = num5;
                if (num3 <= -144)
                {
                    hidePVPIcons = true;
                }
                num5 = 0;
            }
            if (mouseX >= num7 && (float)mouseX <= (float)num7 + (float)TextureAssets.InventoryBack.Width() * inventoryScale && mouseY >= num8 && (float)mouseY <= (float)num8 + (float)TextureAssets.InventoryBack.Height() * inventoryScale)
            {
                UILinkPointNavigator.Shortcuts.NPCS_LastHovered = num6;
                mouseText = true;
                text = ((k != 0) ? npc[num6].FullName : Lang.inter[8].Value);
                if (!PlayerInput.IgnoreMouseInterface)
                {
                    player[myPlayer].mouseInterface = true;
                    if (mouseLeftRelease && mouseLeft && !PlayerInput.UsingGamepadUI && mouseItem.type == 0)
                    {
                        SoundEngine.PlaySound(12);
                        if (k == 0)
{
                            SetMouseNPC_ToHousingQuery();
                        }
                        else
{
                            SetMouseNPC(num6, npc[num6].type);
                        }
                        mouseLeftRelease = false;
                    }
                }
            }
            UILinkPointNavigator.SetPosition(600 + num, new Vector2(num7, num8) + TextureAssets.InventoryBack.Value.Size() * 0.75f);
            Texture2D value = TextureAssets.InventoryBack11.Value;
            Microsoft.Xna.Framework.Color white = inventoryBack;
            if (UILinkPointNavigator.CurrentPoint - 600 == num)
            {
                value = TextureAssets.InventoryBack14.Value;
                white = Microsoft.Xna.Framework.Color.White;
            }
            spriteBatch.Draw(value, new Vector2(num7, num8), null, white, 0f, default(Vector2), inventoryScale, SpriteEffects.None, 0f);
            color = Microsoft.Xna.Framework.Color.White;
            int num9 = k;
            float scale = 1f;
            float num10 = 0f;
            num10 = ((TextureAssets.NpcHead[num9].Width() <= TextureAssets.NpcHead[num9].Height()) ? ((float)TextureAssets.NpcHead[num9].Height()) : ((float)TextureAssets.NpcHead[num9].Width()));
            if (num10 > 36f)
            {
                scale = 36f / num10;
            }
            spriteBatch.Draw(TextureAssets.NpcHead[num9].Value, new Vector2((float)num7 + 26f * inventoryScale, (float)num8 + 26f * inventoryScale), null, color, 0f, new Vector2(TextureAssets.NpcHead[num9].Width() / 2, TextureAssets.NpcHead[num9].Height() / 2), scale, SpriteEffects.None, 0f);
            num++;
            num4++;
            num5++;
        }
        UILinkPointNavigator.Shortcuts.NPCS_IconsTotal = num4;
        if (text != "" && mouseItem.type == 0)
        {
            MouseText(text, 0, 0);
        }
    }
References Terraria.Main._npcIndexWhoHoldsHeadIndex, Terraria.Main._npcTypesThatAlreadyDrewAHead, System.Collections.Generic.List< T >.Add(), Terraria.ID.NPCHeadID.Sets.CannotBeDrawnInHousingUI, System.Collections.Generic.List< T >.Clear(), System.Collections.Generic.List< T >.Contains(), Terraria.ID.NPCHeadID.Count, Terraria.UI.Gamepad.UILinkPointNavigator.CurrentPoint, System.FullName, Terraria.GameContent.TownNPCProfiles.GetHeadIndexSafe(), Terraria.Main.hidePVPIcons, System.Text.RegularExpressions.i, Terraria.GameInput.PlayerInput.IgnoreMouseInterface, Terraria.Lang.inter, Terraria.GameContent.TextureAssets.InventoryBack, Terraria.Main.inventoryBack, Terraria.GameContent.TextureAssets.InventoryBack11, Terraria.GameContent.TextureAssets.InventoryBack14, Terraria.Main.inventoryScale, Terraria.Main.mH, Terraria.Main.mouseItem, Terraria.Main.mouseLeft, Terraria.Main.mouseLeftRelease, Terraria.Main.mouseText, Terraria.Main.MouseText(), Terraria.Main.mouseX, Terraria.Main.mouseY, Terraria.Main.myPlayer, Terraria.Main.npc, Terraria.GameContent.TextureAssets.NpcHead, Terraria.Main.player, Terraria.Audio.SoundEngine.PlaySound(), Terraria.Main.screenHeight, Terraria.Main.screenWidth, Terraria.Main.SetMouseNPC(), Terraria.Main.SetMouseNPC_ToHousingQuery(), Terraria.UI.Gamepad.UILinkPointNavigator.SetPosition(), Terraria.Main.spriteBatch, System.text, System.type, Terraria.GameInput.PlayerInput.UsingGamepadUI, System.value, Microsoft.Xna.Framework.Graphics.Vector2, and Microsoft.Xna.Framework.Color.White.
Referenced by Terraria.Main.DrawInventory().