Terraria: Terraria.Main.AnimateTiles_CritterCages
AnimateTiles_CritterCages()
static void Terraria.Main.AnimateTiles_CritterCages () inline static
References Terraria.Main.birdCageFrame, Terraria.Main.birdCageFrameCounter, Terraria.Main.blueBirdCageFrame, Terraria.Main.blueBirdCageFrameCounter, Terraria.Main.bunnyCageFrame, Terraria.Main.bunnyCageFrameCounter, Terraria.Main.butterflyCageFrame, Terraria.Main.butterflyCageFrameCounter, Terraria.Main.butterflyCageMode, Terraria.Main.cageFrames, Terraria.Main.critterCage, Terraria.Main.duckCageFrame, Terraria.Main.duckCageFrameCounter, Terraria.Main.fairyJarFrame, Terraria.Main.fairyJarFrameCounter, Terraria.Main.fishBowlFrame, Terraria.Main.fishBowlFrameCounter, Terraria.Main.fishBowlFrameMode, Terraria.Main.frogCageFrame, Terraria.Main.frogCageFrameCounter, Terraria.Main.grasshopperCageFrame, Terraria.Main.grasshopperCageFrameCounter, Terraria.Main.grebeCageFrame, Terraria.Main.grebeCageFrameCounter, Terraria.Main.jellyfishCageFrame, Terraria.Main.jellyfishCageFrameCounter, Terraria.Main.jellyfishCageMode, Terraria.Main.ladybugCageFrame, Terraria.Main.ladybugCageFrameCounter, Terraria.Main.lavaFishBowlFrame, Terraria.Main.lavaFishBowlFrameCounter, Terraria.Main.macawCageFrame, Terraria.Main.macawCageFrameCounter, Terraria.Main.maggotCageFrame, Terraria.Main.maggotCageFrameCounter, Terraria.Main.mallardCageFrame, Terraria.Main.mallardCageFrameCounter, Terraria.Main.mouseCageFrame, Terraria.Main.mouseCageFrameCounter, Terraria.Main.penguinCageFrame, Terraria.Main.penguinCageFrameCounter, Terraria.Main.rand, Terraria.Main.ratCageFrame, Terraria.Main.ratCageFrameCounter, Terraria.Main.redBirdCageFrame, Terraria.Main.redBirdCageFrameCounter, Terraria.Main.scorpionCageFrame, Terraria.Main.scorpionCageFrameCounter, Terraria.Main.seagullCageFrame, Terraria.Main.seagullCageFrameCounter, Terraria.Main.seahorseCageFrame, Terraria.Main.seahorseCageFrameCounter, Terraria.Main.slugCageFrame, Terraria.Main.slugCageFrameCounter, Terraria.Main.snail2CageFrame, Terraria.Main.snail2CageFrameCounter, Terraria.Main.snailCageFrame, Terraria.Main.snailCageFrameCounter, Terraria.Main.squirrelCageFrame, Terraria.Main.squirrelCageFrameCounter, Terraria.Main.squirrelCageFrameCounterOrange, Terraria.Main.squirrelCageFrameOrange, Terraria.Main.turtleCageFrame, Terraria.Main.turtleCageFrameCounter, Terraria.Main.UpdateDragonflyJarFrames(), Terraria.Main.UpdateOwlCageFrames(), Terraria.Main.waterStriderCageFrame, Terraria.Main.waterStriderCageFrameCounter, Terraria.Main.wormCageFrame, and Terraria.Main.wormCageFrameCounter.
Referenced by Terraria.Main.AnimateTiles(), and Terraria.Main.Initialize_TileAndNPCData2().