Terraria: Terraria.Main.ToggleGameplayUpdates
ToggleGameplayUpdates()
static void Terraria.Main.ToggleGameplayUpdates (bool state) inline static
    {
        CanUpdateGameplay = state;
    }
References Terraria.Main.CanUpdateGameplay.
Referenced by Terraria.Player.Hooks.EnterWorld(), Terraria.Netplay.InnerClientLoop(), Terraria.WorldGen.playWorldCallBack(), and Terraria.WorldGen.RenameWorldCallBack().