Terraria: Terraria.Main.UpdateDisplaySettings
UpdateDisplaySettings()
void Terraria.Main.UpdateDisplaySettings () inline
Definition at line 63184 of file Main.cs.
    {
        if (startFullscreen)
        {
            FullscreenStartup();
        }
        SetResolution(base.GraphicsDevice.Viewport.Width, base.GraphicsDevice.Viewport.Height);
    }
References Terraria.Main.FullscreenStartup(), Terraria.Main.SetResolution(), and Terraria.Main.startFullscreen.
Referenced by Terraria.Main.ClientInitialize(), Terraria.Main.DoDraw(), and Terraria.Main.InitTargets().