Terraria: Terraria.Main.SetNPCShopIndex
SetNPCShopIndex()
static void Terraria.Main.SetNPCShopIndex (int index) inline static
Definition at line 37260 of file Main.cs.
    {
        npcShop = index;
    }
References System.Linq.index, and Terraria.Main.npcShop.
Referenced by Terraria.Main.DrawInventory(), Terraria.Main.HoverOverNPCs(), Terraria.Main.OpenShop(), Terraria.Main.TryInteractingWithMoneyTrough(), Terraria.Main.TryInteractingWithMoneyTrough2(), and Terraria.Main.TryInteractingWithVoidLens().