Terraria: Terraria.Main.DrawTiles
DrawTiles()
void Terraria.Main.DrawTiles (bool solidLayer, bool forRenderTargets, bool intoRenderTargets, int waterStyleOverride = -1) inline protected
    {
        TilesRenderer.Draw(solidLayer, forRenderTargets, intoRenderTargets, waterStyleOverride);
    }
References Terraria.GameContent.Drawing.TileDrawing.Draw(), and Terraria.Main.TilesRenderer.
Referenced by Terraria.Main.DoDraw_Tiles_NonSolid(), Terraria.Main.DoDraw_Tiles_Solid(), Terraria.Main.DrawCapture(), Terraria.Main.RenderTiles(), and Terraria.Main.RenderTiles2().