Terraria: Terraria.Main.MouseTextHackZoom
MouseTextHackZoom() [2/2]
void Terraria.Main.MouseTextHackZoom (string text, string buffTooltip = null) inline
Definition at line 18714 of file Main.cs.
    {
        MouseTextHackZoom(text, 0, 0, buffTooltip);
    }
References Terraria.Main.MouseTextHackZoom(), and System.text.
Referenced by Terraria.Main.DrawInterface_Resources_Buffs(), Terraria.Main.DrawInventory(), Terraria.Main.DrawMouseOver(), Terraria.Main.HoverOverNPCs(), and Terraria.Main.MouseTextHackZoom().