Terraria: Terraria.Main.DrawTileInWater
DrawTileInWater()
static void Terraria.Main.DrawTileInWater (Vector2 drawOffset, int x, int y) inline static
Definition at line 54316 of file Main.cs.
    {
        if (Main.tile[x, y] != null && Main.tile[x, y].active() && Main.tile[x, y].type == 518)
        {
            instance.LoadTiles(Main.tile[x, y].type);
            Tile tile = Main.tile[x, y];
            int num = tile.liquid / 16;
            num -= 3;
            if (WorldGen.SolidTile(x, y - 1) && num > 8)
            {
                num = 8;
            }
            Microsoft.Xna.Framework.Rectangle value = new Microsoft.Xna.Framework.Rectangle(tile.frameX, tile.frameY, 16, 16);
            spriteBatch.Draw(TextureAssets.Tile[tile.type].Value, new Vector2(x * 16, y * 16 - num) + drawOffset, value, Lighting.GetColor(x, y), 0f, default(Vector2), 1f, SpriteEffects.None, 0f);
        }
    }
References Terraria.Lighting.GetColor(), Terraria.Main.instance, Terraria.WorldGen.SolidTile(), Terraria.Main.spriteBatch, Terraria.GameContent.TextureAssets.Tile, Terraria.Main.tile, and System.value.
Referenced by Terraria.GameContent.Liquid.LiquidRenderer.DrawNormalLiquids(), Terraria.GameContent.Liquid.LiquidRenderer.DrawShimmer(), and Terraria.Main.oldDrawWater().