Terraria: Terraria.Main.RenderWalls
RenderWalls()
void Terraria.Main.RenderWalls () inline protected
Definition at line 54928 of file Main.cs.
    {
        if (drawToScreen)
        {
            return;
        }
        base.GraphicsDevice.SetRenderTarget(wallTarget);
        base.GraphicsDevice.DepthStencilState = new DepthStencilState
        {
            DepthBufferEnable = true
        };
        base.GraphicsDevice.Clear(Microsoft.Xna.Framework.Color.Transparent);
        spriteBatch.Begin(SpriteSortMode.Deferred, BlendState.AlphaBlend);
        tileBatch.Begin();
        if (ignoreErrors)
        {
            try
            {
                DrawWalls();
            }
            catch (Exception e)
            {
                TimeLogger.DrawException(e);
            }
        }
        else
        {
            DrawWalls();
        }
        TimeLogger.DetailedDrawReset();
        tileBatch.End();
        spriteBatch.End();
        TimeLogger.DetailedDrawTime(32);
        base.GraphicsDevice.SetRenderTarget(null);
    }
References Terraria.TimeLogger.DetailedDrawReset(), Terraria.TimeLogger.DetailedDrawTime(), Terraria.TimeLogger.DrawException(), Terraria.Main.drawToScreen, Terraria.Main.DrawWalls(), Terraria.Main.ignoreErrors, Terraria.Main.spriteBatch, Terraria.Main.tileBatch, and Terraria.Main.wallTarget.
Referenced by Terraria.Main.DoDraw().