Terraria: Terraria.Main.DrawTorchBiomeSwapIcon
DrawTorchBiomeSwapIcon()
void Terraria.Main.DrawTorchBiomeSwapIcon (int pivotTopLeftX, int pivotTopLeftY, bool pushSideToolsUp, int gamepadPointOffset) inline private
Definition at line 39640 of file Main.cs.
    {
        if (!playerInventory)
        {
            return;
        }
        int num = 68 + pivotTopLeftY;
        _ = player[myPlayer];
        if (pushSideToolsUp)
        {
            num = 47 + pivotTopLeftY;
        }
        float num2 = 0.9f;
        int num3 = 11;
        bool flag = player[myPlayer].builderAccStatus[num3] == 0;
        Texture2D value = TextureAssets.Extra[211].Value;
        Microsoft.Xna.Framework.Rectangle rectangle = value.Frame(4, 1, flag ? 1 : 0);
        bool flag2 = false;
        if (mouseX > pivotTopLeftX && (float)mouseX < (float)pivotTopLeftX + (float)rectangle.Width * num2 && mouseY > num && (float)mouseY < (float)num + (float)rectangle.Height * num2)
        {
            flag2 = true;
            player[myPlayer].mouseInterface = true;
            MouseText(flag ? Language.GetTextValue("GameUI.TorchTypeSwapperOn") : Language.GetTextValue("GameUI.TorchTypeSwapperOff"), 0, 0);
            mouseText = true;
            if (mouseLeft && mouseLeftRelease)
            {
                SoundEngine.PlaySound(22);
                player[myPlayer].builderAccStatus[num3] = (flag ? 1 : 0);
            }
        }
        Vector2 vector = new Vector2(pivotTopLeftX, num);
        spriteBatch.Draw(value, vector, rectangle, Microsoft.Xna.Framework.Color.White, 0f, default(Vector2), num2, SpriteEffects.None, 0f);
        if (flag2)
        {
            spriteBatch.Draw(value, vector, value.Frame(4, 1, flag ? 3 : 2), OurFavoriteColor, 0f, default(Vector2), num2, SpriteEffects.None, 0f);
        }
        UILinkPointNavigator.SetPosition(6000 + gamepadPointOffset, vector + rectangle.Size() * 0.65f);
    }
References Terraria.GameContent.TextureAssets.Extra, Terraria.Localization.Language.GetTextValue(), Terraria.Main.mouseLeft, Terraria.Main.mouseLeftRelease, Terraria.Main.mouseText, Terraria.Main.MouseText(), Terraria.Main.mouseX, Terraria.Main.mouseY, Terraria.Main.myPlayer, Terraria.Main.OurFavoriteColor, Terraria.Main.player, Terraria.Main.playerInventory, Terraria.Audio.SoundEngine.PlaySound(), Terraria.UI.Gamepad.UILinkPointNavigator.SetPosition(), Terraria.Main.spriteBatch, System.value, Microsoft.Xna.Framework.Graphics.Vector2, and Microsoft.Xna.Framework.Color.White.
Referenced by Terraria.Main.DrawBuilderAccToggles().