Terraria: Terraria.Main.PostContentLoadInitialize
PostContentLoadInitialize()
static void Terraria.Main.PostContentLoadInitialize () inline static private
Definition at line 10022 of file Main.cs.
    {
        LiquidRenderer.LoadContent();
        AchievementInitializer.Load();
        AchievementAdvisor.Initialize();
        DyeInitializer.Load();
        ScreenEffectInitializer.Load();
        InGameNotificationsTracker.Initialize();
        LinkButtonsInitializer.Load();
        _stardewAnimation = new StardewValleyAnimation();
        moonType = rand.Next(9);
        windSpeedCurrent = (float)rand.Next(-800, 801) * 0.001f;
        windSpeedTarget = windSpeedCurrent;
        numClouds = rand.Next(200);
        Mount.Initialize();
        Minecart.Initialize();
        CacheSupportedDisplaySizes();
        ContentSamples.RebuildItemCreativeSortingIDsAfterRecipesAreSetUp();
        ContentSamples.CommonlyUsedContentSamples.PrepareAfterEverythingElseLoaded();
    }
References Terraria.Main._stardewAnimation, Terraria.Main.CacheSupportedDisplaySizes(), Terraria.UI.AchievementAdvisor.Initialize(), Terraria.UI.InGameNotificationsTracker.Initialize(), Terraria.Minecart.Initialize(), Terraria.Mount.Initialize(), Terraria.Initializers.AchievementInitializer.Load(), Terraria.Initializers.DyeInitializer.Load(), Terraria.Initializers.LinkButtonsInitializer.Load(), Terraria.Initializers.ScreenEffectInitializer.Load(), Terraria.GameContent.Liquid.LiquidRenderer.LoadContent(), Terraria.Main.moonType, Terraria.Main.numClouds, Terraria.ID.ContentSamples.CommonlyUsedContentSamples.PrepareAfterEverythingElseLoaded(), Terraria.Main.rand, Terraria.ID.ContentSamples.RebuildItemCreativeSortingIDsAfterRecipesAreSetUp(), Terraria.Main.windSpeedCurrent, and Terraria.Main.windSpeedTarget.
Referenced by Terraria.Main.DrawSplash().