Terraria: Terraria.Main.MouseText_DrawBuffTooltip
MouseText_DrawBuffTooltip()
void Terraria.Main.MouseText_DrawBuffTooltip (string buffString, ref int X, ref int Y) inline private
Definition at line 19866 of file Main.cs.
    {
        Microsoft.Xna.Framework.Point p = new Microsoft.Xna.Framework.Point(X, Y);
        int num = 220;
        int num2 = 72;
        int num3 = -1;
        float num4 = 1f;
        List<Vector2> list = new List<Vector2>();
        Vector2 vector = FontAssets.MouseText.Value.MeasureString(buffString);
        list.Add(vector);
        int num5 = (int)((float)(screenHeight - Y - 24 - num2) * num4) / 20;
        if (num5 < 1)
        {
            num5 = 1;
        }
        if (bannerMouseOver)
        {
            int num6 = 0;
            for (int i = 0; i < 290; i++)
            {
                if (Item.BannerToNPC(i) != 0 && player[myPlayer].HasNPCBannerBuff(i))
                {
                    num6++;
                    string nPCNameValue = Lang.GetNPCNameValue(Item.BannerToNPC(i));
                    Vector2 vector2 = FontAssets.MouseText.Value.MeasureString(nPCNameValue);
                    int num7 = X;
                    int num8 = Y + (int)vector2.Y + num6 * 20 + 10;
                    int num9 = 0;
                    int num10 = num6 / num5;
                    for (int j = 0; j < num10; j++)
                    {
                        num9++;
                        num7 += num;
                        num8 -= num5 * 20;
                    }
                    if ((float)(num7 - 24 - num) > (float)screenWidth * num4)
                    {
                        num3 = num6;
                        break;
                    }
                    list.Add(new Vector2(num7, num8) + vector2 - p.ToVector2());
                }
            }
        }
        Vector2 zero = Vector2.Zero;
        foreach (Vector2 item in list)
        {
            if (zero.X < item.X)
            {
                zero.X = item.X;
            }
            if (zero.Y < item.Y)
            {
                zero.Y = item.Y;
            }
        }
        if ((float)X + zero.X + 24f > (float)screenWidth * num4)
        {
            X = (int)((float)screenWidth * num4 - zero.X - 24f);
        }
        if ((float)Y + zero.Y + 4f > (float)screenHeight * num4)
        {
            Y = (int)((float)screenHeight * num4 - zero.Y - 4f);
        }
        for (int k = 0; k < 5; k++)
        {
            int num11 = X;
            int num12 = Y + (int)FontAssets.MouseText.Value.MeasureString(buffString).Y;
            Microsoft.Xna.Framework.Color color = Microsoft.Xna.Framework.Color.Black;
            switch (k)
            {
            case 0:
                num11 -= 2;
                break;
            case 1:
                num11 += 2;
                break;
            case 2:
                num12 -= 2;
                break;
            case 3:
                num12 += 2;
                break;
            default:
                color = new Microsoft.Xna.Framework.Color(mouseTextColor, mouseTextColor, mouseTextColor, mouseTextColor);
                break;
            }
            DynamicSpriteFontExtensionMethods.DrawString(spriteBatch, FontAssets.MouseText.Value, buffString, new Vector2(num11, num12), color, 0f, default(Vector2), 1f, SpriteEffects.None, 0f);
        }
        if (!bannerMouseOver)
        {
            return;
        }
        int num13 = 0;
        for (int l = 0; l < 290; l++)
        {
            if (Item.BannerToNPC(l) == 0 || !player[myPlayer].HasNPCBannerBuff(l))
            {
                continue;
            }
            num13++;
            bool flag = false;
            for (int m = 0; m < 5; m++)
            {
                int num14 = X;
                int num15 = Y + (int)vector.Y + num13 * 20 + 10;
                int num16 = (num13 - 1) / num5;
                num14 += num * num16;
                num15 -= num5 * 20 * num16;
                string text = Lang.GetNPCNameValue(Item.BannerToNPC(l));
                if (num3 == num13)
                {
                    text = Language.GetTextValue("UI.Ellipsis");
                    flag = true;
                }
                Microsoft.Xna.Framework.Color color2 = Microsoft.Xna.Framework.Color.Black;
                switch (m)
                {
                case 0:
                    num14 -= 2;
                    break;
                case 1:
                    num14 += 2;
                    break;
                case 2:
                    num15 -= 2;
                    break;
                case 3:
                    num15 += 2;
                    break;
                default:
                {
                    float num17 = (float)(int)mouseTextColor / 255f;
                    color2 = new Microsoft.Xna.Framework.Color((byte)(80f * num17), (byte)(255f * num17), (byte)(120f * num17), mouseTextColor);
                    break;
                }
                }
                DynamicSpriteFontExtensionMethods.DrawString(spriteBatch, FontAssets.MouseText.Value, text, new Vector2(num14, num15), color2, 0f, default(Vector2), 1f, SpriteEffects.None, 0f);
            }
            if (flag)
            {
                break;
            }
        }
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Add(), Terraria.Main.bannerMouseOver, Terraria.Item.BannerToNPC(), Microsoft.Xna.Framework.Color.Black, Terraria.Main.buffString, ReLogic.Graphics.DynamicSpriteFontExtensionMethods.DrawString(), Terraria.Lang.GetNPCNameValue(), Terraria.Localization.Language.GetTextValue(), System.Text.RegularExpressions.i, Terraria.Main.item, System.list, Terraria.GameContent.FontAssets.MouseText, Terraria.Main.mouseTextColor, Terraria.Main.myPlayer, Terraria.Main.player, Terraria.Main.screenHeight, Terraria.Main.screenWidth, Terraria.Main.spriteBatch, System.text, Microsoft.Xna.Framework.Graphics.Vector2, System.X, System.Y, and Microsoft.Xna.Framework.Vector2.Zero.
Referenced by Terraria.Main.MouseTextInner().