Terraria: Terraria.Main.DrawProjectiles
DrawProjectiles()
void Terraria.Main.DrawProjectiles () inline protected
Definition at line 20676 of file Main.cs.
    {
        PlayerInput.SetZoom_MouseInWorld();
        spriteBatch.Begin(SpriteSortMode.Deferred, BlendState.AlphaBlend, DefaultSamplerState, DepthStencilState.None, Rasterizer, null, Transform);
        int num = 0;
        CurrentDrawnEntity = null;
        CurrentDrawnEntityShader = 0;
        if (ignoreErrors)
        {
            for (int i = 0; i < 1000; i++)
            {
                if (projectile[i].active && projectile[i].type > 0 && !projectile[i].hide)
                {
                    num++;
                    try
                    {
                        DrawProj(i);
                    }
                    catch (Exception e)
                    {
                        TimeLogger.DrawException(e);
                        projectile[i].active = false;
                    }
                }
            }
        }
        else
        {
            for (int j = 0; j < 1000; j++)
            {
                if (projectile[j].active && projectile[j].type > 0 && !projectile[j].hide)
                {
                    DrawProj(j);
                }
            }
        }
        CurrentDrawnEntity = null;
        CurrentDrawnEntityShader = 0;
        spriteBatch.End();
        TimeLogger.DetailedDrawTime(20);
    }
References Microsoft.Xna.Framework.Graphics.BlendState.AlphaBlend, Terraria.Main.CurrentDrawnEntity, Terraria.Main.CurrentDrawnEntityShader, Terraria.Main.DefaultSamplerState, Terraria.TimeLogger.DetailedDrawTime(), Terraria.TimeLogger.DrawException(), Terraria.Main.DrawProj(), System.Text.RegularExpressions.i, Terraria.Main.ignoreErrors, Microsoft.Xna.Framework.Graphics.DepthStencilState.None, Terraria.Main.projectile, Terraria.Main.Rasterizer, Terraria.GameInput.PlayerInput.SetZoom_MouseInWorld(), Terraria.Main.spriteBatch, Terraria.Main.Transform, and System.type.
Referenced by Terraria.Main.DoDraw(), and Terraria.Main.DrawCapture().