Terraria: Terraria.Main.ReleaseTargets
ReleaseTargets()
void Terraria.Main.ReleaseTargets () inline protected
    {
        try
        {
            if (!dedServ)
            {
                offScreenRange = 0;
                targetSet = false;
                if (waterTarget != null)
                {
                    waterTarget.Dispose();
                }
                if (backWaterTarget != null)
                {
                    backWaterTarget.Dispose();
                }
                if (blackTarget != null)
                {
                    blackTarget.Dispose();
                }
                if (tileTarget != null)
                {
                    tileTarget.Dispose();
                }
                if (tile2Target != null)
                {
                    tile2Target.Dispose();
                }
                if (wallTarget != null)
                {
                    wallTarget.Dispose();
                }
                if (screenTarget != null)
                {
                    screenTarget.Dispose();
                }
                if (screenTargetSwap != null)
                {
                    screenTargetSwap.Dispose();
                }
                if (backgroundTarget != null)
                {
                    backgroundTarget.Dispose();
                }
                if (Main.OnRenderTargetsReleased != null)
                {
                    Main.OnRenderTargetsReleased();
                }
            }
        }
        catch
        {
        }
    }
References Terraria.Main.backgroundTarget, Terraria.Main.backWaterTarget, Terraria.Main.blackTarget, Terraria.Main.dedServ, ReLogic.Content.Asset< T >.Dispose(), Terraria.Main.offScreenRange, Terraria.Main.OnRenderTargetsReleased, Terraria.Main.screenTarget, Terraria.Main.screenTargetSwap, Terraria.Main.targetSet, Terraria.Main.tile2Target, Terraria.Main.tileTarget, Terraria.Main.wallTarget, and Terraria.Main.waterTarget.
Referenced by Terraria.Main.DoDraw(), and Terraria.Main.InitTargets().