Terraria: Terraria.Main.DrawInterface_InstrumentMouseText
DrawInterface_InstrumentMouseText()
void Terraria.Main.DrawInterface_InstrumentMouseText () inline private
Definition at line 42280 of file Main.cs.
    {
        Player localPlayer = LocalPlayer;
        if (_mouseTextCache.isValid || signHover > -1 || localPlayer.cursorItemIconID > 0 || localPlayer.selectedItem == 58 || (localPlayer.rulerLine && localPlayer.builderAccStatus[0] == 0) || localPlayer.mouseInterface)
        {
            instrumentMouseFixHack = 3;
            return;
        }
        if (instrumentMouseFixHack > 0)
        {
            instrumentMouseFixHack--;
            return;
        }
        int type = localPlayer.inventory[localPlayer.selectedItem].type;
        if (type == 4057 || type == 4372 || type == 4715 || type == 4673)
        {
            float musicDist = localPlayer.musicDist;
            string text = "GameUI.GuitarAm";
            if (type == 4673)
            {
                int num = 10;
                float num2 = 1f / (float)num;
                text = ((musicDist > num2 * 9f) ? "GameUI.DrumCymbol" : ((musicDist > num2 * 8f) ? "GameUI.DrumCymbol1" : ((musicDist > num2 * 7f) ? "GameUI.DrumHiHat" : ((musicDist > num2 * 6f) ? "GameUI.DrumClosedHiHat" : ((musicDist > num2 * 5f) ? "GameUI.DrumFloorTom" : ((musicDist > num2 * 4f) ? "GameUI.DrumTamaSnare" : ((musicDist > num2 * 3f) ? "GameUI.DrumTomHigh" : ((musicDist > num2 * 2f) ? "GameUI.DrumTomMid" : ((!(musicDist > num2 * 1f)) ? "GameUI.DrumKick" : "GameUI.DrumTomLow")))))))));
            }
            else
            {
                int num3 = 6;
                float num4 = 1f / (float)num3;
                text = ((musicDist > num4 * 5f) ? "GameUI.GuitarEm" : ((musicDist > num4 * 4f) ? "GameUI.GuitarD" : ((musicDist > num4 * 3f) ? "GameUI.GuitarC" : ((musicDist > num4 * 2f) ? "GameUI.GuitarBm" : ((!(musicDist > num4 * 1f)) ? "GameUI.GuitarG" : "GameUI.GuitarAm")))));
            }
            MouseText(Language.GetTextValue(Language.GetTextValue(text)), 0, 0);
        }
    }
References Terraria.Main._mouseTextCache, Terraria.Localization.Language.GetTextValue(), Terraria.Main.instrumentMouseFixHack, Terraria.Main.MouseTextCache.isValid, Terraria.Main.LocalPlayer, Terraria.Main.MouseText(), Terraria.Main.signHover, System.text, and System.type.
Referenced by Terraria.Main.DrawInterface_33_MouseText().