Terraria: Terraria.Main.DrawInterface_10_CheckCaptureManager
DrawInterface_10_CheckCaptureManager()
static bool Terraria.Main.DrawInterface_10_CheckCaptureManager () inline static private
Definition at line 43154 of file Main.cs.
    {
        bool result = true;
        PlayerInput.SetDesiredZoomContext(ZoomContext.Unscaled_MouseInWorld);
        CaptureManager.Instance.Update();
        if (CaptureManager.Instance.Active)
        {
            CaptureManager.Instance.Draw(spriteBatch);
            result = false;
            _MouseOversCanClear = true;
            PlayerInput.SetZoom_UI();
            Matrix uIScaleMatrix = UIScaleMatrix;
            spriteBatch.End();
            spriteBatch.Begin(SpriteSortMode.Deferred, null, null, null, null, null, uIScaleMatrix);
            DrawPendingMouseText();
        }
        return result;
    }
References Terraria.Main._MouseOversCanClear, Terraria.Main.DrawPendingMouseText(), Terraria.Graphics.Capture.CaptureManager.Instance, Terraria.GameInput.PlayerInput.SetDesiredZoomContext(), Terraria.GameInput.PlayerInput.SetZoom_UI(), Terraria.Main.spriteBatch, and Terraria.Main.UIScaleMatrix.
Referenced by Terraria.Main.SetupDrawInterfaceLayers().