Terraria: Terraria.Main.guideItem
guideItem
Item Terraria.Main.guideItem = new Item() static
Definition at line 1775 of file Main.cs.
Referenced by Terraria.Player.ClearPlayerTempInfo(), Terraria.Recipe.CollectGuideRecipes(), Terraria.Main.DrawGuideCraftText(), Terraria.Main.DrawGuideCraftText_Old(), Terraria.Main.DrawInventory(), Terraria.Player.dropItemCheck(), Terraria.Recipe.FindRecipes(), Terraria.Main.HoverOverCraftingItemButton(), Terraria.Initializers.UILinksInitializer.Load(), Terraria.UI.ItemSlot.OverrideLeftClick(), and Terraria.Player.SaveTemporaryItemSlotContents().