Terraria: Terraria.Main.NewText
NewText()
static void Terraria.Main.NewText (string newText, byte R = byte::MaxValue, byte G = byte::MaxValue, byte B = byte::MaxValue) inline static
Definition at line 61429 of file Main.cs.
    {
        chatMonitor.NewText(newText, R, G, B);
        SoundEngine.PlaySound(12);
    }
References Terraria.Main.chatMonitor, and Terraria.Audio.SoundEngine.PlaySound().
Referenced by Terraria.WorldGen.BroadcastText(), Terraria.GameContent.CoinLossRevengeSystem.CacheEnemy(), Terraria.NPC.checkDead(), Terraria.WorldGen.CheckOrb(), Terraria.NPC.CheckProgressFrostMoon(), Terraria.NPC.CheckProgressPumpkinMoon(), Terraria.Player.CheckSpawn_Internal(), Terraria.NPC.CountKillForBannersAndDropThem(), Terraria.WorldBuilding.WorldUtils.DebugRegen(), Terraria.Net.LegacyNetBufferPool.DisplayBufferSizes(), Terraria.NPC.DoDeathEvents(), Terraria.NPC.DoDeathEvents_CelebrateBossDeath(), Terraria.Main.DrawInterface_38_MouseCarriedObject(), Terraria.Main.DrawPVPIcons(), Terraria.TimeLogger.EndDrawFrame(), Terraria.GameContent.Events.DD2Event.FailureMessage(), Terraria.Projectile.HandleMovement(), Terraria.Main.InvasionWarning(), Terraria.Player.ItemCheck_UseCombatBook(), Terraria.Player.ItemCheck_UseEventItems(), Terraria.Player.ItemCheck_UsePeddlersSatchel(), Terraria.Player.KillMe(), Terraria.Initializers.UILinksInitializer.Load(), Terraria.WorldGen.meteor(), Terraria.WorldGen.MoveTownNPC(), Terraria.TimeLogger.NewDrawFrame(), Terraria.NPC.NewNPC(), Terraria.NPC.NPCLoot(), Terraria.Initializers.AchievementInitializer.OnAchievementCompleted(), Terraria.Cinematics.DD2Film.OnBegin(), Terraria.Cinematics.DD2Film.OnEnd(), Terraria.GameContent.Golf.GolfHelper.ContactListener.PutBallInCup_TextAndEffects(), Terraria.WorldGen.SmashAltar(), Terraria.WorldGen.smCallBack(), Terraria.NPC.SpawnBoss(), Terraria.GameContent.CoinLossRevengeSystem.RevengeMarker.SpawnEnemy(), Terraria.NPC.SpawnOnPlayer(), Terraria.NPC.SpawnSkeletron(), Terraria.WorldGen.SpawnTownNPC(), Terraria.WorldGen.SpawnTravelNPC(), Terraria.NPC.SpawnWOF(), Terraria.TimeLogger.Start(), Terraria.Main.startPumpkinMoon(), Terraria.Main.startSnowMoon(), Terraria.GameContent.PortalHelper.SupportedTilesAreFine(), Terraria.Player.TileInteractionsUse(), Terraria.WorldGen.UnspawnTravelNPC(), Terraria.TestHighFPSIssues.Update(), Terraria.GameContent.DontStarveDarknessDamageDealer.UpdateDarknessState(), Terraria.Main.UpdateSlimeRainWarning(), Terraria.Main.UpdateTime_StartDay(), and Terraria.Main.UpdateTime_StartNight().