Terraria: Terraria.Main.GetAreaToLight
GetAreaToLight()
static void Terraria.Main.GetAreaToLight (out int firstTileX, out int lastTileX, out int firstTileY, out int lastTileY) inline static
Definition at line 60773 of file Main.cs.
    {
        Vector2 vector = Camera.ScaledPosition;
        Vector2 vector2 = Camera.ScaledSize;
        if (!Lighting.UsingNewLighting)
        {
            vector = Camera.UnscaledPosition;
            vector2 = Camera.UnscaledSize;
        }
        firstTileX = (int)Math.Floor(vector.X / 16f) - 1;
        lastTileX = (int)Math.Floor((vector.X + vector2.X) / 16f) + 2;
        firstTileY = (int)Math.Floor(vector.Y / 16f) - 1;
        lastTileY = (int)Math.Floor((vector.Y + vector2.Y) / 16f) + 2;
    }
References Terraria.Main.firstTileX, Terraria.Main.firstTileY, System.Math.Floor(), Terraria.Main.lastTileX, Terraria.Main.lastTileY, Terraria.Graphics.Camera.ScaledPosition, Terraria.Graphics.Camera.ScaledSize, Terraria.Graphics.Camera.UnscaledPosition, Terraria.Graphics.Camera.UnscaledSize, and Terraria.Lighting.UsingNewLighting.
Referenced by Terraria.Main.DoLightTiles(), and Terraria.Player.ForceUpdateBiomes().