Terraria: Terraria.Main.SetGraphicsProfileInternal
SetGraphicsProfileInternal()
static void Terraria.Main.SetGraphicsProfileInternal () inline static private
Definition at line 3466 of file Main.cs.
    {
        _currentGraphicsProfile = _selectedGraphicsProfile;
        graphics.GraphicsProfile = _selectedGraphicsProfile;
        switch (_selectedGraphicsProfile)
        {
        case GraphicsProfile.HiDef:
            maxScreenW = 4096;
            maxScreenH = 4096;
            _renderTargetMaxSize = 4096;
            TrySupporting8K();
            break;
        case GraphicsProfile.Reach:
            maxScreenW = 1920;
            maxScreenH = 1200;
            _renderTargetMaxSize = 2048;
            break;
        }
        try
        {
            graphics.ApplyChanges();
        }
        catch (NoSuitableGraphicsDeviceException)
        {
            if (_currentGraphicsProfile == GraphicsProfile.HiDef)
            {
                _selectedGraphicsProfile = GraphicsProfile.Reach;
                SetGraphicsProfileInternal();
            }
        }
        instance.EnsureRenderTargetContent();
    }
References Terraria.Main._currentGraphicsProfile, Terraria.Main._renderTargetMaxSize, Terraria.Main._selectedGraphicsProfile, Terraria.Main.graphics, Terraria.Main.instance, Terraria.Main.maxScreenH, Terraria.Main.maxScreenW, Terraria.Main.SetGraphicsProfileInternal(), and Terraria.Main.TrySupporting8K().
Referenced by Terraria.Main.SetGraphicsProfile(), and Terraria.Main.SetGraphicsProfileInternal().