Terraria: Terraria.Main.DrawProj_Spear
DrawProj_Spear()
static void Terraria.Main.DrawProj_Spear (Projectile proj, ref Microsoft::Xna::Framework::Color projectileColor, ref SpriteEffects dir) inline static private
Definition at line 32404 of file Main.cs.
    {
        dir = SpriteEffects.None;
        float num = (float)Math.Atan2(proj.velocity.Y, proj.velocity.X) + 2.355f;
        Asset<Texture2D> val = TextureAssets.Projectile[proj.type];
        Player player = Main.player[proj.owner];
        Microsoft.Xna.Framework.Rectangle value = val.Frame();
        Microsoft.Xna.Framework.Rectangle rect = proj.getRect();
        Vector2 vector = Vector2.Zero;
        if (player.direction > 0)
        {
            dir = SpriteEffects.FlipHorizontally;
            vector.X = val.Width();
            num -= (float)Math.PI / 2f;
        }
        if (player.gravDir == -1f)
        {
            if (proj.direction == 1)
            {
                dir = SpriteEffects.FlipHorizontally | SpriteEffects.FlipVertically;
                vector = new Vector2(val.Width(), val.Height());
                num -= (float)Math.PI / 2f;
            }
            else if (proj.direction == -1)
            {
                dir = SpriteEffects.FlipVertically;
                vector = new Vector2(0f, val.Height());
                num += (float)Math.PI / 2f;
            }
        }
        Vector2.Lerp(vector, value.Center.ToVector2(), 0.25f);
        float num2 = 0f;
        Vector2 vector2 = proj.Center + new Vector2(0f, proj.gfxOffY);
        if (proj.AI_019_Spears_GetExtensionHitbox(out var extensionBox))
        {
            Vector2 value2 = player.RotatedRelativePoint(player.MountedCenter, reverseRotation: false, addGfxOffY: false);
            float num3 = extensionBox.Size().Length() / proj.Hitbox.Size().Length();
            _ = new Microsoft.Xna.Framework.Color(255, 255, 255, 0) * 1f;
            float num4 = Utils.Remap(player.itemAnimation, player.itemAnimationMax, (float)player.itemAnimationMax / 3f, 0f, 1f);
            float num5 = Utils.Remap(num4, 0f, 0.3f, 0f, 1f) * Utils.Remap(num4, 0.3f, 1f, 1f, 0f);
            num5 = 1f - (1f - num5) * (1f - num5);
            Vector2 vector3 = extensionBox.Center.ToVector2() + new Vector2(0f, proj.gfxOffY);
            Vector2.Lerp(value2, vector3, 1.1f);
            Texture2D value3 = TextureAssets.Extra[98].Value;
            Vector2 origin = value3.Size() / 2f;
            Microsoft.Xna.Framework.Color color = new Microsoft.Xna.Framework.Color(255, 255, 255, 0) * 0.5f;
            switch (proj.type)
            {
            case 105:
                color = new Microsoft.Xna.Framework.Color(255, 220, 80, 0);
                break;
            case 46:
                color = new Microsoft.Xna.Framework.Color(180, 80, 255, 0);
                break;
            case 342:
                color = new Microsoft.Xna.Framework.Color(80, 140, 255, 0);
                break;
            case 153:
                color = new Microsoft.Xna.Framework.Color(255, 50, 30, 15);
                break;
            }
            float num6 = num - (float)Math.PI / 4f * (float)proj.spriteDirection;
            if (player.gravDir < 0f)
            {
                num6 -= (float)Math.PI / 2f * (float)proj.spriteDirection;
            }
            EntitySpriteDraw(value3, Vector2.Lerp(vector3, vector2, 0.5f) - screenPosition, null, color * num5, num6, origin, new Vector2(num5 * num3, num3) * proj.scale * num3, dir);
            EntitySpriteDraw(value3, Vector2.Lerp(vector3, vector2, 1f) - screenPosition, null, color * num5, num6, origin, new Vector2(num5 * num3, num3 * 1.5f) * proj.scale * num3, dir);
            EntitySpriteDraw(value3, Vector2.Lerp(value2, vector2, num4 * 1.5f - 0.5f) - screenPosition + new Vector2(0f, 2f), null, color * num5, num6, origin, new Vector2(num5 * num3 * 1f * num5, num3 * 2f * num5) * proj.scale * num3, dir);
            for (float num7 = 0.4f; num7 <= 1f; num7 += 0.1f)
            {
                Vector2 vector4 = Vector2.Lerp(value2, vector3, num7 + 0.2f);
                EntitySpriteDraw(value3, vector4 - screenPosition + new Vector2(0f, 2f), null, color * num5 * 0.75f * num7, num6, origin, new Vector2(num5 * num3 * 1f * num5, num3 * 2f * num5) * proj.scale * num3, dir);
            }
            extensionBox.Offset((int)(0f - screenPosition.X), (int)(0f - screenPosition.Y));
        }
        EntitySpriteDraw(val.Value, vector2 - screenPosition, value, proj.GetAlpha(projectileColor), num, vector, proj.scale, dir);
        rect.Offset((int)(0f - screenPosition.X), (int)(0f - screenPosition.Y));
        spriteBatch.Draw(TextureAssets.MagicPixel.Value, rect, Microsoft.Xna.Framework.Color.White * num2);
    }
References System.Math.Atan2(), Terraria.Main.EntitySpriteDraw(), Terraria.GameContent.TextureAssets.Extra, Microsoft.Xna.Framework.Vector2.Lerp(), Terraria.GameContent.TextureAssets.MagicPixel, System.Math.PI, Terraria.Main.player, Terraria.GameContent.TextureAssets.Projectile, Terraria.Utils.Remap(), Terraria.Main.screenPosition, Terraria.Main.spriteBatch, System.value, Microsoft.Xna.Framework.Graphics.Vector2, Microsoft.Xna.Framework.Color.White, and Microsoft.Xna.Framework.Vector2.Zero.
Referenced by Terraria.Main.DrawProjDirect().