Terraria: Terraria.Main.DrawMiscMapIcons
DrawMiscMapIcons()
void Terraria.Main.DrawMiscMapIcons (SpriteBatch spriteBatch, Vector2 mapTopLeft, Vector2 mapX2Y2AndOff, Microsoft::Xna::Framework::Rectangle? mapRect, float mapScale, float drawScale, ref string mouseTextString) inline private
Definition at line 53491 of file Main.cs.
    {
        DrawMapIcons_PotionOfReturnHomePosition(spriteBatch, mapTopLeft, mapX2Y2AndOff, mapRect, mapScale, drawScale, ref mouseTextString);
        DrawMapIcons_PotionOfReturnAppearAfterUsePosition(spriteBatch, mapTopLeft, mapX2Y2AndOff, mapRect, mapScale, drawScale, ref mouseTextString);
        DrawMapIcons_LastGolfballHit(spriteBatch, mapTopLeft, mapX2Y2AndOff, mapRect, mapScale, drawScale, ref mouseTextString);
    }
References Terraria.Main.DrawMapIcons_LastGolfballHit(), Terraria.Main.DrawMapIcons_PotionOfReturnAppearAfterUsePosition(), Terraria.Main.DrawMapIcons_PotionOfReturnHomePosition(), and Terraria.Main.spriteBatch.
Referenced by Terraria.Main.DrawMap().