Terraria: Terraria.Main.DrawNPC
DrawNPC()
void Terraria.Main.DrawNPC (int iNPCIndex, bool behindTiles) inline protected
    {
        NPC rCurrentNPC = npc[iNPCIndex];
        Vector2 screenPos = screenPosition;
        DrawNPCDirect(spriteBatch, rCurrentNPC, behindTiles, screenPos);
    }
References Terraria.Main.DrawNPCDirect(), Terraria.Main.npc, Terraria.Main.screenPosition, and Terraria.Main.spriteBatch.
Referenced by Terraria.Main.DrawCachedNPCs(), and Terraria.Main.DrawNPCs().