Terraria: Terraria.Main.checkHalloween
checkHalloween()
static void Terraria.Main.checkHalloween () inline static
    {
        DateTime now = DateTime.Now;
        int day = now.Day;
        int month = now.Month;
        if (day >= 10 && month == 10)
        {
            halloween = true;
        }
        else if (day <= 1 && month == 11)
        {
            halloween = true;
        }
        else
        {
            halloween = false;
        }
        if (forceHalloweenForToday)
        {
            halloween = true;
        }
    }
References Terraria.Main.forceHalloweenForToday, and Terraria.Main.halloween.
Referenced by Terraria.WorldGen.clearWorld(), Terraria.WorldGen.GenerateWorld(), Terraria.MessageBuffer.GetData(), Terraria.WorldGen.Hooks.Initialize(), Terraria.IO.WorldFile.LoadWorld(), and Terraria.Main.UpdateTime_StartDay().