Terraria: Terraria.Main.SetMonitorOnce
SetMonitorOnce()
static void Terraria.Main.SetMonitorOnce (object sender, PreparingDeviceSettingsEventArgs e) inline static private
Definition at line 5812 of file Main.cs.
    {
        string displayName = Configuration.Get("Display", "");
        GraphicsAdapter graphicsAdapter = GraphicsAdapter.Adapters.Where((GraphicsAdapter adapter) => adapter.DeviceName == displayName).FirstOrDefault();
        if (graphicsAdapter != null)
        {
            e.GraphicsDeviceInformation.Adapter = graphicsAdapter;
        }
        graphics.PreparingDeviceSettings -= SetMonitorOnce;
    }
References Microsoft.Xna.Framework.Graphics.GraphicsAdapter.Adapters, Microsoft.Xna.Framework.Graphics.GraphicsAdapter.DeviceName, and Terraria.Main.SetMonitorOnce().
Referenced by Terraria.Main.SetDisplayMonitor(), and Terraria.Main.SetMonitorOnce().