Terraria: Terraria.Main.SyncAnInvasion
SyncAnInvasion()
static void Terraria.Main.SyncAnInvasion (int toWho) inline static
Definition at line 44677 of file Main.cs.
    {
        int waveNumber = NPC.waveNumber;
        if (snowMoon)
        {
            int num = (new int[21]
            {
                0, 25, 15, 10, 30, 100, 160, 180, 200, 250,
                300, 375, 450, 525, 675, 850, 1025, 1325, 1550, 2000,
                0
            })[waveNumber];
            NetMessage.SendData(78, toWho, -1, null, (int)NPC.waveKills, num, 1f, waveNumber);
        }
        else if (pumpkinMoon)
        {
            int num2 = (new int[16]
            {
                0, 25, 40, 50, 80, 100, 160, 180, 200, 250,
                300, 375, 450, 525, 675, 0
            })[waveNumber];
            NetMessage.SendData(78, toWho, -1, null, (int)NPC.waveKills, num2, 2f, waveNumber);
        }
        else if (DD2Event.Ongoing)
        {
            DD2Event.SyncInvasionProgress(toWho);
        }
        else if (invasionType > 0)
        {
            int num3 = 1;
            if (invasionType != 0 && invasionSizeStart != 0)
            {
                num3 = invasionSizeStart;
            }
            NetMessage.SendData(78, toWho, -1, null, invasionSizeStart - invasionSize, num3, invasionType + 3);
        }
    }
References Terraria.Main.invasionSize, Terraria.Main.invasionSizeStart, Terraria.Main.invasionType, Terraria.GameContent.Events.DD2Event.Ongoing, Terraria.Main.pumpkinMoon, Terraria.NetMessage.SendData(), Terraria.Main.snowMoon, Terraria.GameContent.Events.DD2Event.SyncInvasionProgress(), Terraria.NPC.waveKills, and Terraria.NPC.waveNumber.
Referenced by Terraria.MessageBuffer.GetData().