Terraria: System.Xml.Xsl.IlGen.XmlILAnnotation.Write
Write()
static XmlILAnnotation System.Xml.Xsl.IlGen.XmlILAnnotation.Write (QilNode nd) inline static
Definition at line 117 of file XmlILAnnotation.cs.
    {
        XmlILAnnotation xmlILAnnotation = nd.Annotation as XmlILAnnotation;
        if (xmlILAnnotation == null)
        {
            xmlILAnnotation = (XmlILAnnotation)(nd.Annotation = new XmlILAnnotation(nd.Annotation));
        }
        return xmlILAnnotation;
    }
References System.Xml.Xsl.IlGen.XmlILAnnotation.XmlILAnnotation(), and System.Xml.Dictionary.
Referenced by System.Xml.Xsl.XmlILGenerator.CreateFunctionMetadata(), System.Xml.Xsl.XmlILGenerator.CreateGlobalValueMetadata(), System.Xml.Xsl.XmlILGenerator.EvaluateGlobalValues(), System.Xml.Xsl.IlGen.XmlILVisitor.Function(), System.Xml.Xsl.IlGen.XmlILVisitor.PrepareGlobalValues(), System.Xml.Xsl.IlGen.XmlILVisitor.StartBinding(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitFor(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitGlobalValues(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitInvoke(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitPositionOf(), System.Xml.Xsl.IlGen.OptimizerPatterns.Write(), and System.Xml.Xsl.IlGen.XmlILConstructInfo.Write().