Terraria: System.Linq.Parallel.ExceptionAggregator.ThrowOCEorAggregateException
ThrowOCEorAggregateException()
static void System.Linq.Parallel.ExceptionAggregator.ThrowOCEorAggregateException (Exception ex, CancellationState cancellationState) inline static package
Definition at line 57 of file ExceptionAggregator.cs.
    {
        if (ThrowAnOCE(ex, cancellationState))
        {
            CancellationState.ThrowWithStandardMessageIfCanceled(cancellationState.ExternalCancellationToken);
            return;
        }
        throw new AggregateException(ex);
    }
References System.Linq.Parallel.ExceptionAggregator.ThrowAnOCE(), and System.Linq.Parallel.CancellationState.ThrowWithStandardMessageIfCanceled().
Referenced by System.Linq.ParallelEnumerable.DisposeEnumerator< TSource >(), System.Linq.ParallelEnumerable.SequenceEqual< TSource >(), System.Linq.Parallel.ExceptionAggregator.WrapEnumerable< TElement >(), System.Linq.Parallel.ExceptionAggregator.WrapFunc< T, U >(), and System.Linq.Parallel.ExceptionAggregator.WrapQueryEnumerator< TElement, TIgnoreKey >().