Terraria: UIResourcePackInfoMenu.SetupGamepadPoints
SetupGamepadPoints()
void UIResourcePackInfoMenu.SetupGamepadPoints (SpriteBatch spriteBatch) inline private
     {
         UILinkPointNavigator.Shortcuts.BackButtonCommand = 1;
         int num = 3000;
         int idRangeEndExclusive = num;
         List<SnapPoint> snapPoints = GetSnapPoints();
         for (int i = 0; i < snapPoints.Count; i++)
         {
             SnapPoint snapPoint = snapPoints[i];
             string name = snapPoint.Name;
             if (name == "GoBack")
             {
                 _helper.MakeLinkPointFromSnapPoint(idRangeEndExclusive++, snapPoint);
             }
         }
         _helper.MoveToVisuallyClosestPoint(num, idRangeEndExclusive);
     }
References _helper, UILinkPointNavigator.Shortcuts.BackButtonCommand, UIElement.GetSnapPoints(), UIGamepadHelper.MakeLinkPointFromSnapPoint(), UIGamepadHelper.MoveToVisuallyClosestPoint(), and SnapPoint.Name.
Referenced by Draw().