Terraria: System.Net.Http.Headers.NameValueHeaderValue.GetHashCode
GetHashCode() [1/2]
override int System.Net.Http.Headers.NameValueHeaderValue.GetHashCode () inline
Definition at line 52 of file NameValueHeaderValue.cs.
    {
        int hashCode = StringComparer.OrdinalIgnoreCase.GetHashCode(_name);
        if (!string.IsNullOrEmpty(_value))
        {
            if (_value[0] == '"')
            {
                return hashCode ^ _value.GetHashCode();
            }
            return hashCode ^ StringComparer.OrdinalIgnoreCase.GetHashCode(_value);
        }
        return hashCode;
    }
References System.Net.Http.Headers.NameValueHeaderValue._name, System.Net.Http.Headers.NameValueHeaderValue._value, and System.StringComparer.OrdinalIgnoreCase.
Referenced by System.Net.Http.Headers.ContentDispositionHeaderValue.GetHashCode(), System.Net.Http.Headers.MediaTypeHeaderValue.GetHashCode(), System.Net.Http.Headers.NameValueWithParametersHeaderValue.GetHashCode(), and System.Net.Http.Headers.TransferCodingHeaderValue.GetHashCode().