Terraria: System.Net.Http.Headers.NameValueHeaderValue.GetNameValueListLength
GetNameValueListLength()
static int System.Net.Http.Headers.NameValueHeaderValue.GetNameValueListLength (string input, int startIndex, char delimiter, ObjectCollection< NameValueHeaderValue > nameValueCollection) inline static package inherited
Definition at line 202 of file NameValueHeaderValue.cs.
    {
        if (string.IsNullOrEmpty(input) || startIndex >= input.Length)
        {
            return 0;
        }
        int num = startIndex + HttpRuleParser.GetWhitespaceLength(input, startIndex);
        while (true)
        {
            NameValueHeaderValue parsedValue;
            int nameValueLength = GetNameValueLength(input, num, s_defaultNameValueCreator, out parsedValue);
            if (nameValueLength == 0)
            {
                return 0;
            }
            nameValueCollection.Add(parsedValue);
            num += nameValueLength;
            num += HttpRuleParser.GetWhitespaceLength(input, num);
            if (num == input.Length || input[num] != delimiter)
            {
                break;
            }
            num++;
            num += HttpRuleParser.GetWhitespaceLength(input, num);
        }
        return num - startIndex;
    }
References System.Net.Http.Headers.ObjectCollection< T >.Add(), System.Net.Http.Headers.NameValueHeaderValue.GetNameValueLength(), System.Net.Http.HttpRuleParser.GetWhitespaceLength(), System.input, System.Net.Http.Headers.NameValueHeaderValue.s_defaultNameValueCreator, and System.startIndex.
Referenced by System.Net.Http.Headers.ContentDispositionHeaderValue.GetDispositionTypeLength(), System.Net.Http.Headers.MediaTypeHeaderValue.GetMediaTypeLength(), System.Net.Http.Headers.NameValueWithParametersHeaderValue.GetNameValueWithParametersLength(), and System.Net.Http.Headers.TransferCodingHeaderValue.GetTransferCodingLength().