Terraria: System.Net.Http.Headers.NameValueHeaderValue.CheckNameValueFormat
CheckNameValueFormat()
static void System.Net.Http.Headers.NameValueHeaderValue.CheckNameValueFormat (string name, string value) inline static private inherited
Definition at line 260 of file NameValueHeaderValue.cs.
    {
        HeaderUtilities.CheckValidToken(name, "name");
        CheckValueFormat(value);
    }
References System.Net.Http.Headers.HeaderUtilities.CheckValidToken(), System.Net.Http.Headers.NameValueHeaderValue.CheckValueFormat(), and System.value.
Referenced by System.Net.Http.Headers.NameValueHeaderValue.NameValueHeaderValue().