Terraria: System.Net.Http.Headers.NameValueHeaderValue.Find
Find()
static NameValueHeaderValue System.Net.Http.Headers.NameValueHeaderValue.Find (ObjectCollection< NameValueHeaderValue > values, string name) inline static package inherited
Definition at line 230 of file NameValueHeaderValue.cs.
    {
        if (values == null || values.Count == 0)
        {
            return null;
        }
        foreach (NameValueHeaderValue value in values)
        {
            if (string.Equals(value.Name, name, StringComparison.OrdinalIgnoreCase))
            {
                return value;
            }
        }
        return null;
    }
References System.Net.Equals, System.value, and System.values.
Referenced by System.Net.Http.Headers.ContentDispositionHeaderValue.GetDate(), System.Net.Http.Headers.ContentDispositionHeaderValue.GetName(), System.Net.Http.Headers.HeaderUtilities.GetQuality(), System.Net.Http.Headers.ContentDispositionHeaderValue.SetDate(), System.Net.Http.Headers.ContentDispositionHeaderValue.SetName(), and System.Net.Http.Headers.HeaderUtilities.SetQuality().