Terraria: System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.LoadArray
LoadArray()
void System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.LoadArray (byte[] array, string name) inline private
Definition at line 370 of file JsonFormatReaderGenerator.cs.
        {
            LocalBuilder localBuilder = _ilg.DeclareLocal(Globals.TypeOfByteArray, name);
            _ilg.NewArray(typeof(byte), array.Length);
            _ilg.Store(localBuilder);
            for (int i = 0; i < array.Length; i++)
            {
                _ilg.StoreArrayElement(localBuilder, i, array[i]);
            }
            _ilg.Load(localBuilder);
        }
References System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper._ilg, System.array, System.Runtime.Serialization.CodeGenerator.DeclareLocal(), System.Runtime.Serialization.Dictionary, System.Runtime.Serialization.CodeGenerator.Load(), System.Runtime.Serialization.CodeGenerator.NewArray(), System.Runtime.Serialization.CodeGenerator.Store(), System.Runtime.Serialization.CodeGenerator.StoreArrayElement(), and System.Runtime.Serialization.Globals.TypeOfByteArray.
Referenced by System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.ReadMembers().