Terraria: System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.ReadGetOnlyCollection
ReadGetOnlyCollection()
void System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.ReadGetOnlyCollection (CollectionDataContract collectionContract) inline private
Definition at line 749 of file JsonFormatReaderGenerator.cs.
        {
            Type underlyingType = collectionContract.UnderlyingType;
            Type itemType = collectionContract.ItemType;
            bool flag = collectionContract.Kind == CollectionKind.Array;
            LocalBuilder localBuilder = _ilg.DeclareLocal(Globals.TypeOfInt, "arraySize");
            _objectLocal = _ilg.DeclareLocal(underlyingType, "objectDeserialized");
            _ilg.Load(_contextArg);
            _ilg.LoadMember(XmlFormatGeneratorStatics.GetCollectionMemberMethod);
            _ilg.ConvertValue(Globals.TypeOfObject, underlyingType);
            _ilg.Stloc(_objectLocal);
            bool flag2 = collectionContract.Kind == CollectionKind.Dictionary || collectionContract.Kind == CollectionKind.GenericDictionary;
            if (flag2)
            {
                _ilg.Load(_contextArg);
                _ilg.LoadMember(JsonFormatGeneratorStatics.UseSimpleDictionaryFormatReadProperty);
                _ilg.If();
                if (!underlyingType.IsValueType)
                {
                    _ilg.If(_objectLocal, Cmp.EqualTo, null);
                    _ilg.Call(null, XmlFormatGeneratorStatics.ThrowNullValueReturnedForGetOnlyCollectionExceptionMethod, underlyingType);
                    _ilg.EndIf();
                }
                ReadSimpleDictionary(collectionContract, itemType);
                _ilg.Call(_contextArg, XmlFormatGeneratorStatics.CheckEndOfArrayMethod, _xmlReaderArg, localBuilder, _memberNamesArg, _emptyDictionaryStringArg);
                _ilg.Else();
            }
            IsStartElement(_memberNamesArg, _emptyDictionaryStringArg);
            _ilg.If();
            if (!underlyingType.IsValueType)
            {
                _ilg.If(_objectLocal, Cmp.EqualTo, null);
                _ilg.Call(null, XmlFormatGeneratorStatics.ThrowNullValueReturnedForGetOnlyCollectionExceptionMethod, underlyingType);
                _ilg.EndIf();
            }
            if (flag)
            {
                _ilg.Load(_objectLocal);
                _ilg.Call(XmlFormatGeneratorStatics.GetArrayLengthMethod);
                _ilg.Stloc(localBuilder);
            }
            LocalBuilder localBuilder2 = _ilg.DeclareLocal(Globals.TypeOfInt, "i");
            object forState = _ilg.For(localBuilder2, 0, int.MaxValue);
            IsStartElement(_memberNamesArg, _emptyDictionaryStringArg);
            _ilg.If();
            _ilg.Call(_contextArg, XmlFormatGeneratorStatics.IncrementItemCountMethod, 1);
            LocalBuilder value = ReadCollectionItem(collectionContract, itemType);
            if (flag)
            {
                _ilg.If(localBuilder, Cmp.EqualTo, localBuilder2);
                _ilg.Call(null, XmlFormatGeneratorStatics.ThrowArrayExceededSizeExceptionMethod, localBuilder, underlyingType);
                _ilg.Else();
                _ilg.StoreArrayElement(_objectLocal, localBuilder2, value);
                _ilg.EndIf();
            }
            else
            {
                StoreCollectionValue(_objectLocal, value, collectionContract);
            }
            _ilg.Else();
            IsEndElement();
            _ilg.If();
            _ilg.Break(forState);
            _ilg.Else();
            HandleUnexpectedItemInCollection(localBuilder2);
            _ilg.EndIf();
            _ilg.EndIf();
            _ilg.EndFor();
            _ilg.Call(_contextArg, XmlFormatGeneratorStatics.CheckEndOfArrayMethod, _xmlReaderArg, localBuilder, _memberNamesArg, _emptyDictionaryStringArg);
            _ilg.EndIf();
            if (flag2)
            {
                _ilg.EndIf();
            }
        }
References System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper._contextArg, System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper._emptyDictionaryStringArg, System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper._ilg, System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper._memberNamesArg, System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper._objectLocal, System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper._xmlReaderArg, System.Runtime.Serialization.CodeGenerator.Break(), System.Runtime.Serialization.CodeGenerator.Call(), System.Runtime.Serialization.XmlFormatGeneratorStatics.CheckEndOfArrayMethod, System.Runtime.Serialization.CodeGenerator.ConvertValue(), System.Runtime.Serialization.CodeGenerator.DeclareLocal(), System.Runtime.Serialization.Dictionary, System.Runtime.Serialization.CodeGenerator.Else(), System.Runtime.Serialization.CodeGenerator.EndFor(), System.Runtime.Serialization.CodeGenerator.EndIf(), System.Runtime.Serialization.CodeGenerator.For(), System.Runtime.Serialization.XmlFormatGeneratorStatics.GetArrayLengthMethod, System.Runtime.Serialization.XmlFormatGeneratorStatics.GetCollectionMemberMethod, System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.HandleUnexpectedItemInCollection(), System.Runtime.Serialization.CodeGenerator.If(), System.Runtime.Serialization.XmlFormatGeneratorStatics.IncrementItemCountMethod, System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.IsEndElement(), System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.IsStartElement(), System.Runtime.Serialization.CodeGenerator.Load(), System.Runtime.Serialization.CodeGenerator.LoadMember(), System.Reflection.MaxValue, System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.ReadCollectionItem(), System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.ReadSimpleDictionary(), System.Runtime.Serialization.CodeGenerator.Stloc(), System.Runtime.Serialization.CodeGenerator.StoreArrayElement(), System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.StoreCollectionValue(), System.Runtime.Serialization.XmlFormatGeneratorStatics.ThrowArrayExceededSizeExceptionMethod, System.Runtime.Serialization.XmlFormatGeneratorStatics.ThrowNullValueReturnedForGetOnlyCollectionExceptionMethod, System.Runtime.Serialization.Globals.TypeOfInt, System.Runtime.Serialization.Globals.TypeOfObject, System.Runtime.Serialization.JsonFormatGeneratorStatics.UseSimpleDictionaryFormatReadProperty, and System.value.
Referenced by System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.GenerateGetOnlyCollectionReader().