Terraria: System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.ReadValue
ReadValue()
LocalBuilder System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.ReadValue (Type type, string name) inline private
Definition at line 430 of file JsonFormatReaderGenerator.cs.
        {
            LocalBuilder localBuilder = _ilg.DeclareLocal(type, "valueRead");
            LocalBuilder localBuilder2 = null;
            int num = 0;
            while (type.IsGenericType && type.GetGenericTypeDefinition() == Globals.TypeOfNullable)
            {
                num++;
                type = type.GetGenericArguments()[0];
            }
            PrimitiveDataContract primitiveDataContract = PrimitiveDataContract.GetPrimitiveDataContract(type);
            if ((primitiveDataContract != null && primitiveDataContract.UnderlyingType != Globals.TypeOfObject) || num != 0 || type.IsValueType)
            {
                LocalBuilder localBuilder3 = _ilg.DeclareLocal(Globals.TypeOfString, "objectIdRead");
                _ilg.Call(_contextArg, XmlFormatGeneratorStatics.ReadAttributesMethod, _xmlReaderArg);
                _ilg.Call(_contextArg, XmlFormatGeneratorStatics.ReadIfNullOrRefMethod, _xmlReaderArg, type, DataContract.IsTypeSerializable(type));
                _ilg.Stloc(localBuilder3);
                _ilg.If(localBuilder3, Cmp.EqualTo, null);
                if (num != 0)
                {
                    _ilg.LoadAddress(localBuilder);
                    _ilg.InitObj(localBuilder.LocalType);
                }
                else if (type.IsValueType)
                {
                    ThrowSerializationException(System.SR.Format(System.SR.ValueTypeCannotBeNull, DataContract.GetClrTypeFullName(type)));
                }
                else
                {
                    _ilg.Load(null);
                    _ilg.Stloc(localBuilder);
                }
                _ilg.ElseIfIsEmptyString(localBuilder3);
                _ilg.Call(_contextArg, XmlFormatGeneratorStatics.GetObjectIdMethod);
                _ilg.Stloc(localBuilder3);
                if (type.IsValueType)
                {
                    _ilg.IfNotIsEmptyString(localBuilder3);
                    ThrowSerializationException(System.SR.Format(System.SR.ValueTypeCannotHaveId, DataContract.GetClrTypeFullName(type)));
                    _ilg.EndIf();
                }
                if (num != 0)
                {
                    localBuilder2 = localBuilder;
                    localBuilder = _ilg.DeclareLocal(type, "innerValueRead");
                }
                if (primitiveDataContract != null && primitiveDataContract.UnderlyingType != Globals.TypeOfObject)
                {
                    _ilg.Call(_xmlReaderArg, primitiveDataContract.XmlFormatReaderMethod);
                    _ilg.Stloc(localBuilder);
                    if (!type.IsValueType)
                    {
                        _ilg.Call(_contextArg, XmlFormatGeneratorStatics.AddNewObjectMethod, localBuilder);
                    }
                }
                else
                {
                    InternalDeserialize(localBuilder, type, name);
                }
                _ilg.Else();
                if (type.IsValueType)
                {
                    ThrowSerializationException(System.SR.Format(System.SR.ValueTypeCannotHaveRef, DataContract.GetClrTypeFullName(type)));
                }
                else
                {
                    _ilg.Call(_contextArg, XmlFormatGeneratorStatics.GetExistingObjectMethod, localBuilder3, type, name, string.Empty);
                    _ilg.ConvertValue(Globals.TypeOfObject, type);
                    _ilg.Stloc(localBuilder);
                }
                _ilg.EndIf();
                if (localBuilder2 != null)
                {
                    _ilg.If(localBuilder3, Cmp.NotEqualTo, null);
                    WrapNullableObject(localBuilder, localBuilder2, num);
                    _ilg.EndIf();
                    localBuilder = localBuilder2;
                }
            }
            else
            {
                InternalDeserialize(localBuilder, type, name);
            }
            return localBuilder;
        }
References System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper._contextArg, System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper._ilg, System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper._xmlReaderArg, System.Runtime.Serialization.XmlFormatGeneratorStatics.AddNewObjectMethod, System.Runtime.Serialization.CodeGenerator.Call(), System.Runtime.Serialization.CodeGenerator.ConvertValue(), System.Runtime.Serialization.CodeGenerator.DeclareLocal(), System.Runtime.Serialization.Dictionary, System.Runtime.Serialization.CodeGenerator.Else(), System.Runtime.Serialization.CodeGenerator.ElseIfIsEmptyString(), System.Runtime.Serialization.CodeGenerator.EndIf(), System.SR.Format(), System.Runtime.Serialization.DataContract.GetClrTypeFullName(), System.Runtime.Serialization.XmlFormatGeneratorStatics.GetExistingObjectMethod, System.Runtime.Serialization.XmlFormatGeneratorStatics.GetObjectIdMethod, System.Runtime.Serialization.PrimitiveDataContract.GetPrimitiveDataContract(), System.Runtime.Serialization.CodeGenerator.If(), System.Runtime.Serialization.CodeGenerator.IfNotIsEmptyString(), System.Runtime.Serialization.CodeGenerator.InitObj(), System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.InternalDeserialize(), System.Runtime.Serialization.DataContract.IsTypeSerializable(), System.Runtime.Serialization.CodeGenerator.Load(), System.Runtime.Serialization.CodeGenerator.LoadAddress(), System.Runtime.Serialization.XmlFormatGeneratorStatics.ReadAttributesMethod, System.Runtime.Serialization.XmlFormatGeneratorStatics.ReadIfNullOrRefMethod, System.Runtime.Serialization.CodeGenerator.Stloc(), System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.ThrowSerializationException(), System.type, System.Runtime.Serialization.Globals.TypeOfNullable, System.Runtime.Serialization.Globals.TypeOfObject, System.Runtime.Serialization.Globals.TypeOfString, System.SR.ValueTypeCannotBeNull, System.SR.ValueTypeCannotHaveId, System.SR.ValueTypeCannotHaveRef, and System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.WrapNullableObject().
Referenced by System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.ReadCollectionItem(), System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.ReadMembers(), and System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.ReadSimpleDictionary().