Terraria: System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.InvokeFactoryMethod
InvokeFactoryMethod()
bool System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.InvokeFactoryMethod (ClassDataContract classContract) inline private
Definition at line 236 of file JsonFormatReaderGenerator.cs.
        {
            if (HasFactoryMethod(classContract))
            {
                _ilg.Load(_contextArg);
                _ilg.LoadAddress(_objectLocal);
                _ilg.ConvertAddress(_objectLocal.LocalType, Globals.TypeOfIObjectReference);
                _ilg.Load(Globals.NewObjectId);
                _ilg.Call(XmlFormatGeneratorStatics.GetRealObjectMethod);
                _ilg.ConvertValue(Globals.TypeOfObject, _ilg.CurrentMethod.ReturnType);
                return true;
            }
            return false;
        }
References System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper._contextArg, System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper._ilg, System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper._objectLocal, System.Runtime.Serialization.CodeGenerator.Call(), System.Runtime.Serialization.CodeGenerator.ConvertAddress(), System.Runtime.Serialization.CodeGenerator.ConvertValue(), System.Runtime.Serialization.CodeGenerator.CurrentMethod, System.Runtime.Serialization.XmlFormatGeneratorStatics.GetRealObjectMethod, System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.HasFactoryMethod(), System.Runtime.Serialization.CodeGenerator.Load(), System.Runtime.Serialization.CodeGenerator.LoadAddress(), System.Reflection.Emit.LocalBuilder.LocalType, System.Runtime.Serialization.Globals.NewObjectId, System.Reflection.MethodInfo.ReturnType, System.Runtime.Serialization.Globals.TypeOfIObjectReference, and System.Runtime.Serialization.Globals.TypeOfObject.
Referenced by System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.GenerateClassReader().