Terraria: System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.InitArgs
InitArgs()
void System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.InitArgs () inline private
Definition at line 159 of file JsonFormatReaderGenerator.cs.
        {
            _xmlReaderArg = _ilg.GetArg(0);
            _contextArg = _ilg.GetArg(1);
            _emptyDictionaryStringArg = _ilg.GetArg(2);
            _memberNamesArg = _ilg.GetArg(3);
        }
References System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper._contextArg, System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper._emptyDictionaryStringArg, System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper._ilg, System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper._memberNamesArg, System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper._xmlReaderArg, and System.Runtime.Serialization.CodeGenerator.GetArg().
Referenced by System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.GenerateClassReader(), and System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.GenerateCollectionReaderHelper().