Terraria: System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.GenerateClassReader
GenerateClassReader()
JsonFormatClassReaderDelegate System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.GenerateClassReader (ClassDataContract classContract) inline
Definition at line 39 of file JsonFormatReaderGenerator.cs.
        {
            _ilg = new CodeGenerator();
            bool flag = classContract.RequiresMemberAccessForRead(null);
            try
            {
                BeginMethod(_ilg, "Read" + DataContract.SanitizeTypeName(classContract.StableName.Name) + "FromJson", typeof(JsonFormatClassReaderDelegate), flag);
            }
            catch (SecurityException securityException)
            {
                if (!flag)
                {
                    throw;
                }
                classContract.RequiresMemberAccessForRead(securityException);
            }
            InitArgs();
            CreateObject(classContract);
            _ilg.Call(_contextArg, XmlFormatGeneratorStatics.AddNewObjectMethod, _objectLocal);
            InvokeOnDeserializing(classContract);
            if (classContract.IsISerializable)
            {
                ReadISerializable(classContract);
            }
            else
            {
                ReadClass(classContract);
            }
            if (Globals.TypeOfIDeserializationCallback.IsAssignableFrom(classContract.UnderlyingType))
            {
                _ilg.Call(_objectLocal, JsonFormatGeneratorStatics.OnDeserializationMethod, null);
            }
            InvokeOnDeserialized(classContract);
            if (!InvokeFactoryMethod(classContract))
            {
                _ilg.Load(_objectLocal);
                if (classContract.UnderlyingType == Globals.TypeOfDateTimeOffsetAdapter)
                {
                    _ilg.ConvertValue(_objectLocal.LocalType, Globals.TypeOfDateTimeOffsetAdapter);
                    _ilg.Call(XmlFormatGeneratorStatics.GetDateTimeOffsetMethod);
                    _ilg.ConvertValue(Globals.TypeOfDateTimeOffset, _ilg.CurrentMethod.ReturnType);
                }
                else if (classContract.UnderlyingType == Globals.TypeOfMemoryStreamAdapter)
                {
                    _ilg.ConvertValue(_objectLocal.LocalType, Globals.TypeOfMemoryStreamAdapter);
                    _ilg.Call(XmlFormatGeneratorStatics.GetMemoryStreamMethod);
                    _ilg.ConvertValue(Globals.TypeOfMemoryStream, _ilg.CurrentMethod.ReturnType);
                }
                else if (classContract.IsKeyValuePairAdapter)
                {
                    _ilg.Call(classContract.GetKeyValuePairMethodInfo);
                    _ilg.ConvertValue(Globals.TypeOfKeyValuePair.MakeGenericType(classContract.KeyValuePairGenericArguments), _ilg.CurrentMethod.ReturnType);
                }
                else
                {
                    _ilg.ConvertValue(_objectLocal.LocalType, _ilg.CurrentMethod.ReturnType);
                }
            }
            return (JsonFormatClassReaderDelegate)_ilg.EndMethod();
        }
References System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper._contextArg, System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper._ilg, System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper._objectLocal, System.Runtime.Serialization.XmlFormatGeneratorStatics.AddNewObjectMethod, System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.BeginMethod(), System.Runtime.Serialization.CodeGenerator.Call(), System.Runtime.Serialization.CodeGenerator.ConvertValue(), System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.CreateObject(), System.Runtime.Serialization.CodeGenerator.CurrentMethod, System.Runtime.Serialization.CodeGenerator.EndMethod(), System.Runtime.Serialization.XmlFormatGeneratorStatics.GetDateTimeOffsetMethod, System.Runtime.Serialization.XmlFormatGeneratorStatics.GetMemoryStreamMethod, System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.InitArgs(), System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.InvokeFactoryMethod(), System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.InvokeOnDeserialized(), System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.InvokeOnDeserializing(), System.Runtime.Serialization.CodeGenerator.Load(), System.Reflection.Emit.LocalBuilder.LocalType, System.Runtime.Serialization.JsonFormatGeneratorStatics.OnDeserializationMethod, System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.ReadClass(), System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.ReadISerializable(), System.Reflection.MethodInfo.ReturnType, System.Runtime.Serialization.DataContract.SanitizeTypeName(), System.Runtime.Serialization.Globals.TypeOfDateTimeOffset, System.Runtime.Serialization.Globals.TypeOfDateTimeOffsetAdapter, System.Runtime.Serialization.Globals.TypeOfIDeserializationCallback, System.Runtime.Serialization.Globals.TypeOfKeyValuePair, System.Runtime.Serialization.Globals.TypeOfMemoryStream, and System.Runtime.Serialization.Globals.TypeOfMemoryStreamAdapter.
Referenced by System.Runtime.Serialization.Json.JsonFormatReaderGenerator.GenerateClassReader().