Terraria: System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.TryReadPrimitiveArray
TryReadPrimitiveArray()
bool System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.TryReadPrimitiveArray (Type itemType) inline private
Definition at line 826 of file JsonFormatReaderGenerator.cs.
        {
            PrimitiveDataContract primitiveDataContract = PrimitiveDataContract.GetPrimitiveDataContract(itemType);
            if (primitiveDataContract == null)
            {
                return false;
            }
            string text = null;
            switch (itemType.GetTypeCode())
            {
            case TypeCode.Boolean:
                text = "TryReadBooleanArray";
                break;
            case TypeCode.Decimal:
                text = "TryReadDecimalArray";
                break;
            case TypeCode.Int32:
                text = "TryReadInt32Array";
                break;
            case TypeCode.Int64:
                text = "TryReadInt64Array";
                break;
            case TypeCode.Single:
                text = "TryReadSingleArray";
                break;
            case TypeCode.Double:
                text = "TryReadDoubleArray";
                break;
            case TypeCode.DateTime:
                text = "TryReadJsonDateTimeArray";
                break;
            }
            if (text != null)
            {
                _ilg.Load(_xmlReaderArg);
                _ilg.ConvertValue(typeof(XmlReaderDelegator), typeof(JsonReaderDelegator));
                _ilg.Load(_contextArg);
                _ilg.Load(_memberNamesArg);
                _ilg.Load(_emptyDictionaryStringArg);
                _ilg.Load(-1);
                _ilg.Ldloca(_objectLocal);
                _ilg.Call(typeof(JsonReaderDelegator).GetMethod(text, BindingFlags.Instance | BindingFlags.Static | BindingFlags.Public | BindingFlags.NonPublic));
                return true;
            }
            return false;
        }
References System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper._contextArg, System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper._emptyDictionaryStringArg, System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper._ilg, System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper._memberNamesArg, System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper._objectLocal, System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper._xmlReaderArg, System.Runtime.Serialization.CodeGenerator.Call(), System.Runtime.Serialization.CodeGenerator.ConvertValue(), System.Runtime.Serialization.Dictionary, System.Runtime.Serialization.PrimitiveDataContract.GetPrimitiveDataContract(), System.Runtime.Serialization.CodeGenerator.Ldloca(), System.Runtime.Serialization.CodeGenerator.Load(), and System.text.
Referenced by System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.ReadCollection().