Terraria: System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.CheckRequiredElements
CheckRequiredElements()
void System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.CheckRequiredElements (BitFlagsGenerator expectedElements, byte[] requiredElements, Label throwMissingRequiredMembersLabel) inline private
Definition at line 357 of file JsonFormatReaderGenerator.cs.
        {
            for (int i = 0; i < requiredElements.Length; i++)
            {
                _ilg.Load(expectedElements.GetLocal(i));
                _ilg.Load(requiredElements[i]);
                _ilg.And();
                _ilg.Load(0);
                _ilg.Ceq();
                _ilg.Brfalse(throwMissingRequiredMembersLabel);
            }
        }
References System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper._ilg, System.Runtime.Serialization.CodeGenerator.And(), System.Runtime.Serialization.CodeGenerator.Brfalse(), System.Runtime.Serialization.CodeGenerator.Ceq(), and System.Runtime.Serialization.CodeGenerator.Load().
Referenced by System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.ReadMembers().