Terraria: System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.ReadISerializable
ReadISerializable()
void System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.ReadISerializable (ClassDataContract classContract) inline private
Definition at line 414 of file JsonFormatReaderGenerator.cs.
        {
            ConstructorInfo constructor = classContract.UnderlyingType.GetConstructor(BindingFlags.Instance | BindingFlags.Static | BindingFlags.Public | BindingFlags.NonPublic, JsonFormatGeneratorStatics.SerInfoCtorArgs);
            if (constructor == null)
            {
                throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(XmlObjectSerializer.CreateSerializationException(System.SR.Format(System.SR.SerializationInfo_ConstructorNotFound, DataContract.GetClrTypeFullName(classContract.UnderlyingType))));
            }
            _ilg.LoadAddress(_objectLocal);
            _ilg.ConvertAddress(_objectLocal.LocalType, _objectType);
            _ilg.Call(_contextArg, XmlFormatGeneratorStatics.ReadSerializationInfoMethod, _xmlReaderArg, classContract.UnderlyingType);
            _ilg.Load(_contextArg);
            _ilg.LoadMember(XmlFormatGeneratorStatics.GetStreamingContextMethod);
            _ilg.Call(constructor);
        }
References System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper._contextArg, System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper._ilg, System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper._objectLocal, System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper._objectType, System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper._xmlReaderArg, System.Runtime.Serialization.CodeGenerator.Call(), System.Runtime.Serialization.CodeGenerator.ConvertAddress(), System.Runtime.Serialization.XmlObjectSerializer.CreateSerializationException(), System.SR.Format(), System.Runtime.Serialization.DataContract.GetClrTypeFullName(), System.Runtime.Serialization.XmlFormatGeneratorStatics.GetStreamingContextMethod, System.Runtime.Serialization.CodeGenerator.Load(), System.Runtime.Serialization.CodeGenerator.LoadAddress(), System.Runtime.Serialization.CodeGenerator.LoadMember(), System.Reflection.Emit.LocalBuilder.LocalType, System.Runtime.Serialization.XmlFormatGeneratorStatics.ReadSerializationInfoMethod, System.SR.SerializationInfo_ConstructorNotFound, System.Runtime.Serialization.JsonFormatGeneratorStatics.SerInfoCtorArgs, and System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperError().
Referenced by System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.GenerateClassReader().