Terraria: System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.BeginMethod
BeginMethod()
void System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.BeginMethod (CodeGenerator ilg, string methodName, Type delegateType, bool allowPrivateMemberAccess) inline private
Definition at line 146 of file JsonFormatReaderGenerator.cs.
        {
            MethodInfo invokeMethod = JsonFormatWriterGenerator.GetInvokeMethod(delegateType);
            ParameterInfo[] parameters = invokeMethod.GetParameters();
            Type[] array = new Type[parameters.Length];
            for (int i = 0; i < parameters.Length; i++)
            {
                array[i] = parameters[i].ParameterType;
            }
            DynamicMethod dynamicMethod = new DynamicMethod(methodName, invokeMethod.ReturnType, array, typeof(JsonFormatReaderGenerator).Module, allowPrivateMemberAccess);
            ilg.BeginMethod(dynamicMethod, delegateType, methodName, array, allowPrivateMemberAccess);
        }
References System.array, System.Runtime.Serialization.CodeGenerator.BeginMethod(), System.Runtime.Serialization.Json.JsonFormatWriterGenerator.GetInvokeMethod(), and System.Reflection.ParameterInfo.ParameterType.
Referenced by System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.GenerateClassReader(), and System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.GenerateCollectionReaderHelper().