Terraria: System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.ReadCollection
ReadCollection()
void System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.ReadCollection (CollectionDataContract collectionContract) inline private
Definition at line 554 of file JsonFormatReaderGenerator.cs.
        {
            Type type = collectionContract.UnderlyingType;
            Type itemType2 = collectionContract.ItemType;
            bool flag = collectionContract.Kind == CollectionKind.Array;
            ConstructorInfo constructor = collectionContract.Constructor;
            if (type.IsInterface)
            {
                switch (collectionContract.Kind)
                {
                case CollectionKind.GenericDictionary:
                    type = Globals.TypeOfDictionaryGeneric.MakeGenericType(itemType2.GetGenericArguments());
                    constructor = type.GetConstructor(BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, Type.EmptyTypes);
                    break;
                case CollectionKind.Dictionary:
                    type = Globals.TypeOfHashtable;
                    constructor = type.GetConstructor(BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, Type.EmptyTypes);
                    break;
                case CollectionKind.GenericList:
                case CollectionKind.GenericCollection:
                case CollectionKind.List:
                case CollectionKind.GenericEnumerable:
                case CollectionKind.Collection:
                case CollectionKind.Enumerable:
                    type = itemType2.MakeArrayType();
                    flag = true;
                    break;
                }
            }
            _objectLocal = _ilg.DeclareLocal(type, "objectDeserialized");
            if (!flag)
            {
                if (type.IsValueType)
                {
                    _ilg.Ldloca(_objectLocal);
                    _ilg.InitObj(type);
                }
                else
                {
                    _ilg.New(constructor);
                    _ilg.Stloc(_objectLocal);
                    _ilg.Call(_contextArg, XmlFormatGeneratorStatics.AddNewObjectMethod, _objectLocal);
                }
            }
            bool flag2 = collectionContract.Kind == CollectionKind.Dictionary || collectionContract.Kind == CollectionKind.GenericDictionary;
            if (flag2)
            {
                _ilg.Load(_contextArg);
                _ilg.LoadMember(JsonFormatGeneratorStatics.UseSimpleDictionaryFormatReadProperty);
                _ilg.If();
                ReadSimpleDictionary(collectionContract, itemType2);
                _ilg.Else();
            }
            LocalBuilder localBuilder = _ilg.DeclareLocal(Globals.TypeOfString, "objectIdRead");
            _ilg.Call(_contextArg, XmlFormatGeneratorStatics.GetObjectIdMethod);
            _ilg.Stloc(localBuilder);
            bool flag3 = false;
            if (flag && TryReadPrimitiveArray(itemType2))
            {
                flag3 = true;
                _ilg.IfNot();
            }
            LocalBuilder localBuilder2 = null;
            if (flag)
            {
                localBuilder2 = _ilg.DeclareLocal(type, "growingCollection");
                _ilg.NewArray(itemType2, 32);
                _ilg.Stloc(localBuilder2);
            }
            LocalBuilder localBuilder3 = _ilg.DeclareLocal(Globals.TypeOfInt, "i");
            object forState = _ilg.For(localBuilder3, 0, int.MaxValue);
            IsStartElement(_memberNamesArg, _emptyDictionaryStringArg);
            _ilg.If();
            _ilg.Call(_contextArg, XmlFormatGeneratorStatics.IncrementItemCountMethod, 1);
            LocalBuilder value = ReadCollectionItem(collectionContract, itemType2);
            if (flag)
            {
                MethodInfo methodInfo = MakeGenericMethod(XmlFormatGeneratorStatics.EnsureArraySizeMethod, itemType2);
                _ilg.Call(null, methodInfo, localBuilder2, localBuilder3);
                _ilg.Stloc(localBuilder2);
                _ilg.StoreArrayElement(localBuilder2, localBuilder3, value);
            }
            else
            {
                StoreCollectionValue(_objectLocal, value, collectionContract);
            }
            _ilg.Else();
            IsEndElement();
            _ilg.If();
            _ilg.Break(forState);
            _ilg.Else();
            HandleUnexpectedItemInCollection(localBuilder3);
            _ilg.EndIf();
            _ilg.EndIf();
            _ilg.EndFor();
            if (flag)
            {
                MethodInfo methodInfo2 = MakeGenericMethod(XmlFormatGeneratorStatics.TrimArraySizeMethod, itemType2);
                _ilg.Call(null, methodInfo2, localBuilder2, localBuilder3);
                _ilg.Stloc(_objectLocal);
                _ilg.Call(_contextArg, XmlFormatGeneratorStatics.AddNewObjectWithIdMethod, localBuilder, _objectLocal);
            }
            if (flag3)
            {
                _ilg.Else();
                _ilg.Call(_contextArg, XmlFormatGeneratorStatics.AddNewObjectWithIdMethod, localBuilder, _objectLocal);
                _ilg.EndIf();
            }
            if (flag2)
            {
                _ilg.EndIf();
            }
            [UnconditionalSuppressMessage("ReflectionAnalysis", "IL2060:MakeGenericMethod", Justification = "The call to MakeGenericMethod is safe due to the fact that EnsureArraySizeMethod and TrimArraySizeMethod are not annotated.")]
            static MethodInfo MakeGenericMethod(MethodInfo method, Type itemType)
            {
                return method.MakeGenericMethod(itemType);
            }
        }
References System.Collections.Generic.Dictionary< TKey, TValue >.Dictionary(), System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper._contextArg, System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper._emptyDictionaryStringArg, System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper._ilg, System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper._memberNamesArg, System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper._objectLocal, System.Runtime.Serialization.XmlFormatGeneratorStatics.AddNewObjectMethod, System.Runtime.Serialization.XmlFormatGeneratorStatics.AddNewObjectWithIdMethod, System.Runtime.Serialization.CodeGenerator.Break(), System.Runtime.Serialization.CodeGenerator.Call(), System.Runtime.Serialization.CodeGenerator.DeclareLocal(), System.Runtime.Serialization.Dictionary, System.Runtime.Serialization.CodeGenerator.Else(), System.Type.EmptyTypes, System.Runtime.Serialization.CodeGenerator.EndFor(), System.Runtime.Serialization.CodeGenerator.EndIf(), System.Runtime.Serialization.XmlFormatGeneratorStatics.EnsureArraySizeMethod, System.Runtime.Serialization.CodeGenerator.For(), System.Runtime.Serialization.XmlFormatGeneratorStatics.GetObjectIdMethod, System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.HandleUnexpectedItemInCollection(), System.Runtime.Serialization.CodeGenerator.If(), System.Runtime.Serialization.CodeGenerator.IfNot(), System.Runtime.Serialization.XmlFormatGeneratorStatics.IncrementItemCountMethod, System.Runtime.Serialization.CodeGenerator.InitObj(), System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.IsEndElement(), System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.IsStartElement(), System.Runtime.Serialization.CodeGenerator.Ldloca(), System.Runtime.Serialization.CodeGenerator.Load(), System.Runtime.Serialization.CodeGenerator.LoadMember(), System.Reflection.MaxValue, System.Runtime.Serialization.CodeGenerator.New(), System.Runtime.Serialization.CodeGenerator.NewArray(), System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.ReadCollectionItem(), System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.ReadSimpleDictionary(), System.Runtime.Serialization.CodeGenerator.Stloc(), System.Runtime.Serialization.CodeGenerator.StoreArrayElement(), System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.StoreCollectionValue(), System.Runtime.Serialization.XmlFormatGeneratorStatics.TrimArraySizeMethod, System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.TryReadPrimitiveArray(), System.type, System.Runtime.Serialization.Globals.TypeOfDictionaryGeneric, System.Runtime.Serialization.Globals.TypeOfHashtable, System.Runtime.Serialization.Globals.TypeOfInt, System.Runtime.Serialization.Globals.TypeOfString, System.Runtime.Serialization.JsonFormatGeneratorStatics.UseSimpleDictionaryFormatReadProperty, and System.value.
Referenced by System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.GenerateCollectionReader().