Terraria: System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.InvokeOnDeserialized
InvokeOnDeserialized()
void System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.InvokeOnDeserialized (ClassDataContract classContract) inline private
Definition at line 215 of file JsonFormatReaderGenerator.cs.
        {
            if (classContract.BaseContract != null)
            {
                InvokeOnDeserialized(classContract.BaseContract);
            }
            if (classContract.OnDeserialized != null)
            {
                _ilg.LoadAddress(_objectLocal);
                _ilg.ConvertAddress(_objectLocal.LocalType, _objectType);
                _ilg.Load(_contextArg);
                _ilg.LoadMember(XmlFormatGeneratorStatics.GetStreamingContextMethod);
                _ilg.Call(classContract.OnDeserialized);
            }
        }
References System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper._contextArg, System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper._ilg, System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper._objectLocal, System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper._objectType, System.Runtime.Serialization.CodeGenerator.Call(), System.Runtime.Serialization.CodeGenerator.ConvertAddress(), System.Runtime.Serialization.XmlFormatGeneratorStatics.GetStreamingContextMethod, System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.InvokeOnDeserialized(), System.Runtime.Serialization.CodeGenerator.Load(), System.Runtime.Serialization.CodeGenerator.LoadAddress(), System.Runtime.Serialization.CodeGenerator.LoadMember(), and System.Reflection.Emit.LocalBuilder.LocalType.
Referenced by System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.GenerateClassReader(), and System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.InvokeOnDeserialized().