Terraria: System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.GenerateCollectionReaderHelper
GenerateCollectionReaderHelper()
CodeGenerator System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.GenerateCollectionReaderHelper (CollectionDataContract collectionContract, bool isGetOnlyCollection) inline private
Definition at line 118 of file JsonFormatReaderGenerator.cs.
        {
            _ilg = new CodeGenerator();
            bool flag = collectionContract.RequiresMemberAccessForRead(null);
            try
            {
                if (isGetOnlyCollection)
                {
                    BeginMethod(_ilg, "Read" + DataContract.SanitizeTypeName(collectionContract.StableName.Name) + "FromJsonIsGetOnly", typeof(JsonFormatGetOnlyCollectionReaderDelegate), flag);
                }
                else
                {
                    BeginMethod(_ilg, "Read" + DataContract.SanitizeTypeName(collectionContract.StableName.Name) + "FromJson", typeof(JsonFormatCollectionReaderDelegate), flag);
                }
            }
            catch (SecurityException securityException)
            {
                if (!flag)
                {
                    throw;
                }
                collectionContract.RequiresMemberAccessForRead(securityException);
            }
            InitArgs();
            _collectionContractArg = _ilg.GetArg(4);
            return _ilg;
        }
References System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper._collectionContractArg, System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper._ilg, System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.BeginMethod(), System.Runtime.Serialization.CodeGenerator.GetArg(), System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.InitArgs(), and System.Runtime.Serialization.DataContract.SanitizeTypeName().
Referenced by System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.GenerateCollectionReader(), and System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.GenerateGetOnlyCollectionReader().