Terraria: System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.ReadMembers
ReadMembers() [2/2]
void System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.ReadMembers (ClassDataContract classContract, LocalBuilder extensionDataLocal) inline private
Definition at line 276 of file JsonFormatReaderGenerator.cs.
        {
            int num = classContract.MemberNames.Length;
            _ilg.Call(_contextArg, XmlFormatGeneratorStatics.IncrementItemCountMethod, num);
            BitFlagsGenerator bitFlagsGenerator = new BitFlagsGenerator(num, _ilg, classContract.UnderlyingType.Name + "_ExpectedElements");
            byte[] array = new byte[bitFlagsGenerator.GetLocalCount()];
            SetRequiredElements(classContract, array);
            SetExpectedElements(bitFlagsGenerator, 0);
            LocalBuilder localBuilder = _ilg.DeclareLocal(Globals.TypeOfInt, "memberIndex", -1);
            Label label = _ilg.DefineLabel();
            Label label2 = _ilg.DefineLabel();
            object forState = _ilg.For(null, null, null);
            _ilg.Call(null, XmlFormatGeneratorStatics.MoveToNextElementMethod, _xmlReaderArg);
            _ilg.IfFalseBreak(forState);
            _ilg.Call(_contextArg, JsonFormatGeneratorStatics.GetJsonMemberIndexMethod, _xmlReaderArg, _memberNamesArg, localBuilder, extensionDataLocal);
            if (num > 0)
            {
                Label[] memberLabels = _ilg.Switch(num);
                ReadMembers(classContract, bitFlagsGenerator, memberLabels, label, localBuilder);
                _ilg.EndSwitch();
            }
            else
            {
                _ilg.Pop();
            }
            _ilg.EndFor();
            CheckRequiredElements(bitFlagsGenerator, array, label2);
            Label label3 = _ilg.DefineLabel();
            _ilg.Br(label3);
            _ilg.MarkLabel(label);
            _ilg.Call(null, JsonFormatGeneratorStatics.ThrowDuplicateMemberExceptionMethod, _objectLocal, _memberNamesArg, localBuilder);
            _ilg.MarkLabel(label2);
            _ilg.Load(_objectLocal);
            _ilg.ConvertValue(_objectLocal.LocalType, Globals.TypeOfObject);
            _ilg.Load(_memberNamesArg);
            bitFlagsGenerator.LoadArray();
            LoadArray(array, "requiredElements");
            _ilg.Call(JsonFormatGeneratorStatics.ThrowMissingRequiredMembersMethod);
            _ilg.MarkLabel(label3);
        }
References System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper._contextArg, System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper._ilg, System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper._memberNamesArg, System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper._objectLocal, System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper._xmlReaderArg, System.array, System.Runtime.Serialization.CodeGenerator.Br(), System.Runtime.Serialization.CodeGenerator.Call(), System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.CheckRequiredElements(), System.Runtime.Serialization.CodeGenerator.ConvertValue(), System.Runtime.Serialization.CodeGenerator.DeclareLocal(), System.Runtime.Serialization.CodeGenerator.DefineLabel(), System.Runtime.Serialization.CodeGenerator.EndFor(), System.Runtime.Serialization.CodeGenerator.EndSwitch(), System.Runtime.Serialization.CodeGenerator.For(), System.Runtime.Serialization.JsonFormatGeneratorStatics.GetJsonMemberIndexMethod, System.Runtime.Serialization.CodeGenerator.IfFalseBreak(), System.Runtime.Serialization.XmlFormatGeneratorStatics.IncrementItemCountMethod, System.Runtime.Serialization.CodeGenerator.Load(), System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.LoadArray(), System.Reflection.Emit.LocalBuilder.LocalType, System.Runtime.Serialization.CodeGenerator.MarkLabel(), System.Runtime.Serialization.XmlFormatGeneratorStatics.MoveToNextElementMethod, System.Runtime.Serialization.CodeGenerator.Pop(), System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.ReadMembers(), System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.SetExpectedElements(), System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.SetRequiredElements(), System.Runtime.Serialization.CodeGenerator.Switch(), System.Runtime.Serialization.JsonFormatGeneratorStatics.ThrowDuplicateMemberExceptionMethod, System.Runtime.Serialization.JsonFormatGeneratorStatics.ThrowMissingRequiredMembersMethod, System.Runtime.Serialization.Globals.TypeOfInt, and System.Runtime.Serialization.Globals.TypeOfObject.
Referenced by System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.ReadClass(), System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.ReadMembers(), and System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.ReadMembers().