Terraria: System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.ReadClass
ReadClass()
void System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.ReadClass (ClassDataContract classContract) inline private
Definition at line 252 of file JsonFormatReaderGenerator.cs.
        {
            if (classContract.HasExtensionData)
            {
                LocalBuilder localBuilder = _ilg.DeclareLocal(Globals.TypeOfExtensionDataObject, "extensionData");
                _ilg.New(JsonFormatGeneratorStatics.ExtensionDataObjectCtor);
                _ilg.Store(localBuilder);
                ReadMembers(classContract, localBuilder);
                for (ClassDataContract classDataContract = classContract; classDataContract != null; classDataContract = classDataContract.BaseContract)
                {
                    MethodInfo extensionDataSetMethod = classDataContract.ExtensionDataSetMethod;
                    if (extensionDataSetMethod != null)
                    {
                        _ilg.Call(_objectLocal, extensionDataSetMethod, localBuilder);
                    }
                }
            }
            else
            {
                ReadMembers(classContract, null);
            }
        }
References System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper._ilg, System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper._objectLocal, System.Runtime.Serialization.CodeGenerator.Call(), System.Runtime.Serialization.CodeGenerator.DeclareLocal(), System.Runtime.Serialization.JsonFormatGeneratorStatics.ExtensionDataObjectCtor, System.Runtime.Serialization.CodeGenerator.New(), System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.ReadMembers(), System.Runtime.Serialization.CodeGenerator.Store(), and System.Runtime.Serialization.Globals.TypeOfExtensionDataObject.
Referenced by System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.GenerateClassReader().