Terraria: System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.ReadSimpleDictionary
ReadSimpleDictionary()
void System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.ReadSimpleDictionary (CollectionDataContract collectionContract, Type keyValueType) inline private
Definition at line 674 of file JsonFormatReaderGenerator.cs.
        {
            Type[] genericArguments = keyValueType.GetGenericArguments();
            Type type = genericArguments[0];
            Type type2 = genericArguments[1];
            int num = 0;
            Type type3 = type;
            while (type.IsGenericType && type.GetGenericTypeDefinition() == Globals.TypeOfNullable)
            {
                num++;
                type = type.GetGenericArguments()[0];
            }
            ClassDataContract classDataContract = (ClassDataContract)collectionContract.ItemContract;
            DataContract memberTypeContract = classDataContract.Members[0].MemberTypeContract;
            KeyParseMode keyParseMode = KeyParseMode.Fail;
            if (type == Globals.TypeOfString || type == Globals.TypeOfObject)
            {
                keyParseMode = KeyParseMode.AsString;
            }
            else if (type.IsEnum)
            {
                keyParseMode = KeyParseMode.UsingParseEnum;
            }
            else if (memberTypeContract.ParseMethod != null)
            {
                keyParseMode = KeyParseMode.UsingCustomParse;
            }
            if (keyParseMode == KeyParseMode.Fail)
            {
                ThrowSerializationException(System.SR.Format(System.SR.KeyTypeCannotBeParsedInSimpleDictionary, DataContract.GetClrTypeFullName(collectionContract.UnderlyingType), DataContract.GetClrTypeFullName(type)));
                return;
            }
            LocalBuilder localBuilder = _ilg.DeclareLocal(typeof(XmlNodeType), "nodeType");
            _ilg.BeginWhileCondition();
            _ilg.Call(_xmlReaderArg, JsonFormatGeneratorStatics.MoveToContentMethod);
            _ilg.Stloc(localBuilder);
            _ilg.Load(localBuilder);
            _ilg.Load(XmlNodeType.EndElement);
            _ilg.BeginWhileBody(Cmp.NotEqualTo);
            _ilg.Load(localBuilder);
            _ilg.Load(XmlNodeType.Element);
            _ilg.If(Cmp.NotEqualTo);
            ThrowUnexpectedStateException(XmlNodeType.Element);
            _ilg.EndIf();
            _ilg.Call(_contextArg, XmlFormatGeneratorStatics.IncrementItemCountMethod, 1);
            if (keyParseMode == KeyParseMode.UsingParseEnum)
            {
                _ilg.Load(type);
            }
            _ilg.Load(_xmlReaderArg);
            _ilg.Call(JsonFormatGeneratorStatics.GetJsonMemberNameMethod);
            switch (keyParseMode)
            {
            case KeyParseMode.UsingParseEnum:
                _ilg.Call(JsonFormatGeneratorStatics.ParseEnumMethod);
                _ilg.ConvertValue(Globals.TypeOfObject, type);
                break;
            case KeyParseMode.UsingCustomParse:
                _ilg.Call(memberTypeContract.ParseMethod);
                break;
            }
            LocalBuilder localBuilder2 = _ilg.DeclareLocal(type, "key");
            _ilg.Stloc(localBuilder2);
            if (num > 0)
            {
                LocalBuilder localBuilder3 = _ilg.DeclareLocal(type3, "keyOriginal");
                WrapNullableObject(localBuilder2, localBuilder3, num);
                localBuilder2 = localBuilder3;
            }
            LocalBuilder pairValue = ReadValue(type2, string.Empty);
            StoreKeyValuePair(_objectLocal, collectionContract, localBuilder2, pairValue);
            _ilg.EndWhile();
        }
References System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper._contextArg, System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper._ilg, System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper._objectLocal, System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper._xmlReaderArg, System.Runtime.Serialization.CodeGenerator.BeginWhileBody(), System.Runtime.Serialization.CodeGenerator.BeginWhileCondition(), System.Runtime.Serialization.CodeGenerator.Call(), System.Runtime.Serialization.CodeGenerator.ConvertValue(), System.Runtime.Serialization.CodeGenerator.DeclareLocal(), System.Runtime.Serialization.Dictionary, System.Runtime.Serialization.CodeGenerator.EndIf(), System.Runtime.Serialization.CodeGenerator.EndWhile(), System.SR.Format(), System.Runtime.Serialization.DataContract.GetClrTypeFullName(), System.Runtime.Serialization.JsonFormatGeneratorStatics.GetJsonMemberNameMethod, System.Runtime.Serialization.CodeGenerator.If(), System.Runtime.Serialization.XmlFormatGeneratorStatics.IncrementItemCountMethod, System.SR.KeyTypeCannotBeParsedInSimpleDictionary, System.Runtime.Serialization.CodeGenerator.Load(), System.Runtime.Serialization.JsonFormatGeneratorStatics.MoveToContentMethod, System.Runtime.Serialization.JsonFormatGeneratorStatics.ParseEnumMethod, System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.ReadValue(), System.Runtime.Serialization.CodeGenerator.Stloc(), System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.StoreKeyValuePair(), System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.ThrowSerializationException(), System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.ThrowUnexpectedStateException(), System.type, System.Runtime.Serialization.Globals.TypeOfNullable, System.Runtime.Serialization.Globals.TypeOfObject, System.Runtime.Serialization.Globals.TypeOfString, and System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.WrapNullableObject().
Referenced by System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.ReadCollection(), and System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.ReadGetOnlyCollection().