Terraria: System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.StoreCollectionValue
StoreCollectionValue()
void System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.StoreCollectionValue (LocalBuilder collection, LocalBuilder value, CollectionDataContract collectionContract) inline private
Definition at line 894 of file JsonFormatReaderGenerator.cs.
        {
            if (collectionContract.Kind == CollectionKind.GenericDictionary || collectionContract.Kind == CollectionKind.Dictionary)
            {
                ClassDataContract classDataContract = DataContract.GetDataContract(value.LocalType) as ClassDataContract;
                DataMember dataMember = classDataContract.Members[0];
                DataMember dataMember2 = classDataContract.Members[1];
                LocalBuilder localBuilder = _ilg.DeclareLocal(dataMember.MemberType, dataMember.Name);
                LocalBuilder localBuilder2 = _ilg.DeclareLocal(dataMember2.MemberType, dataMember2.Name);
                _ilg.LoadAddress(value);
                _ilg.LoadMember(dataMember.MemberInfo);
                _ilg.Stloc(localBuilder);
                _ilg.LoadAddress(value);
                _ilg.LoadMember(dataMember2.MemberInfo);
                _ilg.Stloc(localBuilder2);
                StoreKeyValuePair(collection, collectionContract, localBuilder, localBuilder2);
            }
            else
            {
                _ilg.Call(collection, collectionContract.AddMethod, value);
                if (collectionContract.AddMethod.ReturnType != Globals.TypeOfVoid)
                {
                    _ilg.Pop();
                }
            }
        }
References System.Collections.Generic.Dictionary< TKey, TValue >.Dictionary(), System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper._ilg, System.Runtime.Serialization.CodeGenerator.Call(), System.collection, System.Runtime.Serialization.CodeGenerator.DeclareLocal(), System.Runtime.Serialization.DataContract.GetDataContract(), System.Runtime.Serialization.CodeGenerator.LoadAddress(), System.Runtime.Serialization.CodeGenerator.LoadMember(), System.Runtime.Serialization.CodeGenerator.Pop(), System.Runtime.Serialization.CodeGenerator.Stloc(), System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.StoreKeyValuePair(), System.Runtime.Serialization.Globals.TypeOfVoid, and System.value.
Referenced by System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.ReadCollection(), and System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.ReadGetOnlyCollection().