Terraria: System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.ThrowSerializationException
ThrowSerializationException() [2/2]
void System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.ThrowSerializationException (string msg, params object[] values) inline private
Definition at line 965 of file JsonFormatReaderGenerator.cs.
        {
            if (values != null && values.Length != 0)
            {
                _ilg.CallStringFormat(msg, values);
            }
            else
            {
                _ilg.Load(msg);
            }
            ThrowSerializationException();
        }
References System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper._ilg, System.Runtime.Serialization.CodeGenerator.CallStringFormat(), System.Runtime.Serialization.CodeGenerator.Load(), System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.ThrowSerializationException(), and System.values.