Terraria: System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.ThrowSerializationException
ThrowSerializationException() [1/2]
void System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.ThrowSerializationException () inline private
Definition at line 978 of file JsonFormatReaderGenerator.cs.
        {
            _ilg.New(JsonFormatGeneratorStatics.SerializationExceptionCtor);
            _ilg.Throw();
        }
References System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper._ilg, System.Runtime.Serialization.CodeGenerator.New(), System.Runtime.Serialization.JsonFormatGeneratorStatics.SerializationExceptionCtor, and System.Runtime.Serialization.CodeGenerator.Throw().
Referenced by System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.ReadSimpleDictionary(), System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.ReadValue(), and System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.ThrowSerializationException().