Terraria: System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.SetRequiredElements
SetRequiredElements()
int System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.SetRequiredElements (ClassDataContract contract, byte[] requiredElements) inline private
Definition at line 382 of file JsonFormatReaderGenerator.cs.
        {
            int num = ((contract.BaseContract != null) ? SetRequiredElements(contract.BaseContract, requiredElements) : 0);
            List<DataMember> members = contract.Members;
            int num2 = 0;
            while (num2 < members.Count)
            {
                if (members[num2].IsRequired)
                {
                    BitFlagsGenerator.SetBit(requiredElements, num);
                }
                num2++;
                num++;
            }
            return num;
        }
References System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Runtime.Serialization.Dictionary, System.Runtime.Serialization.BitFlagsGenerator.SetBit(), and System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.SetRequiredElements().
Referenced by System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.ReadMembers(), and System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.SetRequiredElements().