Terraria: System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.CreateObject
CreateObject()
void System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.CreateObject (ClassDataContract classContract) inline private
Definition at line 168 of file JsonFormatReaderGenerator.cs.
        {
            _objectType = classContract.UnderlyingType;
            Type objectType = classContract.ObjectType;
            _objectLocal = _ilg.DeclareLocal(objectType, "objectDeserialized");
            if (classContract.UnderlyingType == Globals.TypeOfDBNull)
            {
                _ilg.LoadMember(Globals.TypeOfDBNull.GetField("Value"));
                _ilg.Stloc(_objectLocal);
            }
            else if (classContract.IsNonAttributedType)
            {
                if (objectType.IsValueType)
                {
                    _ilg.Ldloca(_objectLocal);
                    _ilg.InitObj(objectType);
                }
                else
                {
                    _ilg.New(classContract.GetNonAttributedTypeConstructor());
                    _ilg.Stloc(_objectLocal);
                }
            }
            else
            {
                _ilg.Call(null, JsonFormatGeneratorStatics.GetUninitializedObjectMethod, classContract.TypeForInitialization);
                _ilg.ConvertValue(Globals.TypeOfObject, objectType);
                _ilg.Stloc(_objectLocal);
            }
        }
References System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper._ilg, System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper._objectLocal, System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper._objectType, System.Runtime.Serialization.CodeGenerator.Call(), System.Runtime.Serialization.CodeGenerator.ConvertValue(), System.Runtime.Serialization.CodeGenerator.DeclareLocal(), System.Runtime.Serialization.JsonFormatGeneratorStatics.GetUninitializedObjectMethod, System.Runtime.Serialization.CodeGenerator.InitObj(), System.Runtime.Serialization.CodeGenerator.Ldloca(), System.Runtime.Serialization.CodeGenerator.LoadMember(), System.Runtime.Serialization.CodeGenerator.New(), System.Runtime.Serialization.CodeGenerator.Stloc(), System.Runtime.Serialization.Globals.TypeOfDBNull, and System.Runtime.Serialization.Globals.TypeOfObject.
Referenced by System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.GenerateClassReader().