Terraria: System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.StoreKeyValuePair
StoreKeyValuePair()
void System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.StoreKeyValuePair (LocalBuilder collection, CollectionDataContract collectionContract, LocalBuilder pairKey, LocalBuilder pairValue) inline private
Definition at line 921 of file JsonFormatReaderGenerator.cs.
        {
            _ilg.Call(collection, collectionContract.AddMethod, pairKey, pairValue);
            if (collectionContract.AddMethod.ReturnType != Globals.TypeOfVoid)
            {
                _ilg.Pop();
            }
        }
References System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper._ilg, System.Runtime.Serialization.CodeGenerator.Call(), System.collection, System.Runtime.Serialization.CodeGenerator.Pop(), and System.Runtime.Serialization.Globals.TypeOfVoid.
Referenced by System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.ReadSimpleDictionary(), and System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.StoreCollectionValue().