Terraria: System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.WrapNullableObject
WrapNullableObject()
void System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.WrapNullableObject (LocalBuilder innerValue, LocalBuilder outerValue, int nullables) inline private
Definition at line 538 of file JsonFormatReaderGenerator.cs.
        {
            Type type = innerValue.LocalType;
            Type localType = outerValue.LocalType;
            _ilg.LoadAddress(outerValue);
            _ilg.Load(innerValue);
            for (int i = 1; i < nullables; i++)
            {
                Type type2 = Globals.TypeOfNullable.MakeGenericType(type);
                _ilg.New(type2.GetConstructor(new Type[1] { type }));
                type = type2;
            }
            _ilg.Call(localType.GetConstructor(new Type[1] { type }));
        }
References System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper._ilg, System.Runtime.Serialization.CodeGenerator.Call(), System.Runtime.Serialization.Dictionary, System.Runtime.Serialization.CodeGenerator.Load(), System.Runtime.Serialization.CodeGenerator.LoadAddress(), System.Runtime.Serialization.CodeGenerator.New(), System.type, and System.Runtime.Serialization.Globals.TypeOfNullable.
Referenced by System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.ReadSimpleDictionary(), and System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.ReadValue().