Terraria: System.Linq.Expressions.Interpreter.InstructionList.DebugView.GetInstructionViews
GetInstructionViews() [1/2]
InstructionView[] System.Linq.Expressions.Interpreter.InstructionList.DebugView.GetInstructionViews (bool includeDebugCookies = false) inline
Definition at line 63 of file InstructionList.cs.
        {
            return GetInstructionViews(_list._instructions, _list._objects, (int index) => _list._labels[index].TargetIndex, null);
        }
References System.Linq.Expressions.Interpreter.InstructionList._instructions, System.Linq.Expressions.Interpreter.InstructionList._labels, System.Linq.Expressions.Interpreter.InstructionList.DebugView._list, System.Linq.Expressions.Interpreter.InstructionList._objects, System.Linq.Expressions.Interpreter.InstructionList.DebugView.GetInstructionViews(), and System.Linq.index.
Referenced by System.Linq.Expressions.Interpreter.InstructionArray.DebugView.GetInstructionViews(), and System.Linq.Expressions.Interpreter.InstructionList.DebugView.GetInstructionViews().