Terraria: TileObjectData.CallPostPlacementPlayerHook
CallPostPlacementPlayerHook()
static bool TileObjectData.CallPostPlacementPlayerHook (int tileX, int tileY, int type, int style, int dir, int alternate, TileObject data) inline static
     {
         TileObjectData tileData = GetTileData(type, style, data.alternate);
         if (tileData == null || tileData._placementHooks == null || tileData._placementHooks.postPlaceMyPlayer.hook == null)
         {
             return false;
         }
         PlacementHook postPlaceMyPlayer = tileData._placementHooks.postPlaceMyPlayer;
         if (postPlaceMyPlayer.processedCoordinates)
         {
             tileX -= tileData.Origin.X;
             tileY -= tileData.Origin.Y;
         }
         return postPlaceMyPlayer.hook(tileX, tileY, type, style, dir, data.alternate) == postPlaceMyPlayer.badReturn;
     }
References _placementHooks, TileObject.alternate, PlacementHook.badReturn, GetTileData(), PlacementHook.hook, Origin, TilePlacementHooksModule.postPlaceMyPlayer, PlacementHook.processedCoordinates, Point16.X, and Point16.Y.
Referenced by Player.PlaceThing_Tiles_PlaceIt(), and Player.TryReplantingTree().