Terraria: TileObjectData.Calculate
Calculate()
void TileObjectData.Calculate () inline private
     {
         if (_tileObjectCoords.calculated)
         {
             return;
         }
         _tileObjectCoords.calculated = true;
         _tileObjectCoords.styleWidth = (_tileObjectCoords.width + _tileObjectCoords.padding) * Width + _tileObjectCoords.paddingFix.X;
         int num = 0;
         _tileObjectCoords.styleHeight = 0;
         for (int i = 0; i < _tileObjectCoords.heights.Length; i++)
         {
             num += _tileObjectCoords.heights[i] + _tileObjectCoords.padding;
         }
         num += _tileObjectCoords.paddingFix.Y;
         _tileObjectCoords.styleHeight = num;
         if (_hasOwnLiquidDeath)
         {
             if (_liquidDeath.lava)
             {
                 LavaPlacement = LiquidPlacement.NotAllowed;
             }
             if (_liquidDeath.water)
             {
                 WaterPlacement = LiquidPlacement.NotAllowed;
             }
         }
     }
References _hasOwnLiquidDeath, _liquidDeath, _tileObjectCoords, TileObjectCoordinatesModule.calculated, TileObjectCoordinatesModule.heights, LiquidDeathModule.lava, LavaPlacement, TileObjectCoordinatesModule.padding, TileObjectCoordinatesModule.paddingFix, TileObjectCoordinatesModule.styleHeight, TileObjectCoordinatesModule.styleWidth, LiquidDeathModule.water, WaterPlacement, TileObjectCoordinatesModule.width, Width, Point16.X, and Point16.Y.
Referenced by addAlternate(), addBaseTile(), addSubTile(), and addTile().