Terraria: TileObjectData.LiquidPlace
LiquidPlace() [2/2]
bool TileObjectData.LiquidPlace (Tile checkTile) inline
     {
         if (checkTile == null)
         {
             return false;
         }
         if (checkTile.liquid > 0)
         {
             switch (checkTile.liquidType())
             {
             case 1:
                 if (LavaPlacement == LiquidPlacement.NotAllowed)
                 {
                     return false;
                 }
                 if (LavaPlacement == LiquidPlacement.OnlyInFullLiquid && checkTile.liquid != byte.MaxValue)
                 {
                     return false;
                 }
                 break;
             case 0:
             case 2:
             case 3:
                 if (WaterPlacement == LiquidPlacement.NotAllowed)
                 {
                     return false;
                 }
                 if (WaterPlacement == LiquidPlacement.OnlyInFullLiquid && checkTile.liquid != byte.MaxValue)
                 {
                     return false;
                 }
                 break;
             }
         }
         else
         {
             switch (checkTile.liquidType())
             {
             case 1:
                 if (LavaPlacement == LiquidPlacement.OnlyInFullLiquid || LavaPlacement == LiquidPlacement.OnlyInLiquid)
                 {
                     return false;
                 }
                 break;
             case 0:
             case 2:
             case 3:
                 if (WaterPlacement == LiquidPlacement.OnlyInFullLiquid || WaterPlacement == LiquidPlacement.OnlyInLiquid)
                 {
                     return false;
                 }
                 break;
             }
         }
         return true;
     }
References LavaPlacement, Tile.liquid, Tile.liquidType(), and WaterPlacement.
Referenced by TileObject.CanPlace(), and CheckLiquidPlacement().