Terraria: TileObjectData.addAlternate
addAlternate()
static void TileObjectData.addAlternate (int baseStyle) inline static private
     {
         newAlternate.Calculate();
         if (!newTile._hasOwnAlternates)
         {
             newTile.Alternates = new List<TileObjectData>();
         }
         newAlternate.Style = baseStyle;
         newAlternate._parent = newTile;
         newTile.Alternates.Add(newAlternate);
         newAlternate = new TileObjectData(_baseObject);
     }
References TileObjectData(), _baseObject, _hasOwnAlternates, _parent, Alternates, Calculate(), newAlternate, newTile, and Style.
Referenced by Initialize().