Terraria: TileObjectData.CustomPlace
CustomPlace()
static bool TileObjectData.CustomPlace (int type, int style) inline static
     {
         if (type < 0 || type >= _data.Count || style < 0)
         {
             return false;
         }
         TileObjectData tileObjectData = _data[type];
         if (tileObjectData == null)
         {
             return false;
         }
         List<TileObjectData> subTiles = tileObjectData.SubTiles;
         if (subTiles != null && style < subTiles.Count)
         {
             TileObjectData tileObjectData2 = subTiles[style];
             if (tileObjectData2 != null)
             {
                 return tileObjectData2._usesCustomCanPlace;
             }
         }
         return tileObjectData._usesCustomCanPlace;
     }
References _data, _usesCustomCanPlace, and SubTiles.
Referenced by Projectile.GasTrapCheck(), Player.PlaceThing_Tiles(), and Player.UpdatePlacementPreview().