Terraria: Terraria.GameInput.PlayerInputProfile.CopyKeysFrom
CopyKeysFrom()
void Terraria.GameInput.PlayerInputProfile.CopyKeysFrom (PlayerInputProfile profile, InputMode mode, string[] keysToCopy) inline private
Definition at line 322 of file PlayerInputProfile.cs.
    {
        for (int i = 0; i < keysToCopy.Length; i++)
        {
            if (profile.InputModes[mode].KeyStatus.TryGetValue(keysToCopy[i], out var value))
            {
                InputModes[mode].KeyStatus[keysToCopy[i]].Clear();
                InputModes[mode].KeyStatus[keysToCopy[i]].AddRange(value);
            }
        }
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.AddRange(), System.Collections.Generic.Dictionary< TKey, TValue >.Clear(), Terraria.GameInput.PlayerInputProfile.InputModes, System.Collections.Generic.Dictionary< TKey, TValue >.TryGetValue(), and System.value.
Referenced by Terraria.GameInput.PlayerInputProfile.CopyGamepadSettingsFrom(), Terraria.GameInput.PlayerInputProfile.CopyGameplaySettingsFrom(), Terraria.GameInput.PlayerInputProfile.CopyHotbarSettingsFrom(), and Terraria.GameInput.PlayerInputProfile.CopyMapSettingsFrom().