Terraria: Terraria.GameInput.PlayerInputProfile.Load
Load()
bool Terraria.GameInput.PlayerInputProfile.Load (Dictionary< string, object > dict) inline
Definition at line 77 of file PlayerInputProfile.cs.
    {
        //IL_0035: Unknown result type (might be due to invalid IL or missing references)
        //IL_003f: Expected O, but got Unknown
        //IL_0065: Unknown result type (might be due to invalid IL or missing references)
        //IL_006f: Expected O, but got Unknown
        //IL_0095: Unknown result type (might be due to invalid IL or missing references)
        //IL_009f: Expected O, but got Unknown
        //IL_00c5: Unknown result type (might be due to invalid IL or missing references)
        //IL_00cf: Expected O, but got Unknown
        //IL_0304: Unknown result type (might be due to invalid IL or missing references)
        //IL_030e: Expected O, but got Unknown
        int num = 0;
        if (dict.TryGetValue("Last Launched Version", out var value))
        {
            num = (int)(long)value;
        }
        if (dict.TryGetValue("Mouse And Keyboard", out value))
        {
            InputModes[InputMode.Keyboard].ReadPreferences(JsonConvert.DeserializeObject<Dictionary<string, List<string>>>(((object)(JObject)value).ToString()));
        }
        if (dict.TryGetValue("Gamepad", out value))
        {
            InputModes[InputMode.XBoxGamepad].ReadPreferences(JsonConvert.DeserializeObject<Dictionary<string, List<string>>>(((object)(JObject)value).ToString()));
        }
        if (dict.TryGetValue("Mouse And Keyboard UI", out value))
        {
            InputModes[InputMode.KeyboardUI].ReadPreferences(JsonConvert.DeserializeObject<Dictionary<string, List<string>>>(((object)(JObject)value).ToString()));
        }
        if (dict.TryGetValue("Gamepad UI", out value))
        {
            InputModes[InputMode.XBoxGamepadUI].ReadPreferences(JsonConvert.DeserializeObject<Dictionary<string, List<string>>>(((object)(JObject)value).ToString()));
        }
        if (num < 190)
        {
            InputModes[InputMode.Keyboard].KeyStatus["ViewZoomIn"] = new List<string>();
            InputModes[InputMode.Keyboard].KeyStatus["ViewZoomIn"].AddRange(PlayerInput.OriginalProfiles["Redigit's Pick"].InputModes[InputMode.Keyboard].KeyStatus["ViewZoomIn"]);
            InputModes[InputMode.Keyboard].KeyStatus["ViewZoomOut"] = new List<string>();
            InputModes[InputMode.Keyboard].KeyStatus["ViewZoomOut"].AddRange(PlayerInput.OriginalProfiles["Redigit's Pick"].InputModes[InputMode.Keyboard].KeyStatus["ViewZoomOut"]);
        }
        if (num < 218)
        {
            InputModes[InputMode.Keyboard].KeyStatus["ToggleCreativeMenu"] = new List<string>();
            InputModes[InputMode.Keyboard].KeyStatus["ToggleCreativeMenu"].AddRange(PlayerInput.OriginalProfiles["Redigit's Pick"].InputModes[InputMode.Keyboard].KeyStatus["ToggleCreativeMenu"]);
        }
        if (num < 227)
        {
            List<string> list = InputModes[InputMode.KeyboardUI].KeyStatus["MouseLeft"];
            string item = "Mouse1";
            if (!list.Contains(item))
            {
                list.Add(item);
            }
        }
        if (num < 265)
        {
            string[] array = new string[4] { "Loadout1", "Loadout2", "Loadout3", "ToggleCameraMode" };
            foreach (string key in array)
            {
                InputModes[InputMode.Keyboard].KeyStatus[key] = new List<string>(PlayerInput.OriginalProfiles["Redigit's Pick"].InputModes[InputMode.Keyboard].KeyStatus[key]);
            }
        }
        if (dict.TryGetValue("Settings", out value))
        {
            Dictionary<string, object> dictionary = JsonConvert.DeserializeObject<Dictionary<string, object>>(((object)(JObject)value).ToString());
            if (dictionary.TryGetValue("Edittable", out value))
            {
                AllowEditting = (bool)value;
            }
            if (dictionary.TryGetValue("Gamepad - HotbarRadialHoldTime", out value))
            {
                HotbarRadialHoldTimeRequired = (int)(long)value;
            }
            if (dictionary.TryGetValue("Gamepad - LeftThumbstickDeadzoneX", out value))
            {
                LeftThumbstickDeadzoneX = (float)(double)value;
            }
            if (dictionary.TryGetValue("Gamepad - LeftThumbstickDeadzoneY", out value))
            {
                LeftThumbstickDeadzoneY = (float)(double)value;
            }
            if (dictionary.TryGetValue("Gamepad - RightThumbstickDeadzoneX", out value))
            {
                RightThumbstickDeadzoneX = (float)(double)value;
            }
            if (dictionary.TryGetValue("Gamepad - RightThumbstickDeadzoneY", out value))
            {
                RightThumbstickDeadzoneY = (float)(double)value;
            }
            if (dictionary.TryGetValue("Gamepad - LeftThumbstickInvertX", out value))
            {
                LeftThumbstickInvertX = (bool)value;
            }
            if (dictionary.TryGetValue("Gamepad - LeftThumbstickInvertY", out value))
            {
                LeftThumbstickInvertY = (bool)value;
            }
            if (dictionary.TryGetValue("Gamepad - RightThumbstickInvertX", out value))
            {
                RightThumbstickInvertX = (bool)value;
            }
            if (dictionary.TryGetValue("Gamepad - RightThumbstickInvertY", out value))
            {
                RightThumbstickInvertY = (bool)value;
            }
            if (dictionary.TryGetValue("Gamepad - TriggersDeadzone", out value))
            {
                TriggersDeadzone = (float)(double)value;
            }
            if (dictionary.TryGetValue("Gamepad - InterfaceDeadzoneX", out value))
            {
                InterfaceDeadzoneX = (float)(double)value;
            }
            if (dictionary.TryGetValue("Gamepad - InventoryMoveCD", out value))
            {
                InventoryMoveCD = (int)(long)value;
            }
        }
        return true;
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Collections.Generic.Dictionary< TKey, TValue >.AddRange(), Terraria.GameInput.PlayerInputProfile.AllowEditting, System.array, System.dictionary, Terraria.GameInput.PlayerInputProfile.HotbarRadialHoldTimeRequired, Terraria.GameInput.PlayerInputProfile.InputModes, Terraria.GameInput.PlayerInputProfile.InterfaceDeadzoneX, Terraria.GameInput.PlayerInputProfile.InventoryMoveCD, System.item, System.key, Terraria.GameInput.PlayerInputProfile.LeftThumbstickDeadzoneX, Terraria.GameInput.PlayerInputProfile.LeftThumbstickDeadzoneY, Terraria.GameInput.PlayerInputProfile.LeftThumbstickInvertX, Terraria.GameInput.PlayerInputProfile.LeftThumbstickInvertY, System.list, Terraria.GameInput.PlayerInput.OriginalProfiles, Terraria.GameInput.PlayerInputProfile.RightThumbstickDeadzoneX, Terraria.GameInput.PlayerInputProfile.RightThumbstickDeadzoneY, Terraria.GameInput.PlayerInputProfile.RightThumbstickInvertX, Terraria.GameInput.PlayerInputProfile.RightThumbstickInvertY, System.ToString, Terraria.GameInput.PlayerInputProfile.TriggersDeadzone, System.Collections.Generic.Dictionary< TKey, TValue >.TryGetValue(), and System.value.