Terraria: System.Text.CodePagesEncodingProvider.GetEncoding
GetEncoding() [1/4]
override? Encoding System.Text.CodePagesEncodingProvider.GetEncoding (int codepage) inline
Definition at line 32 of file CodePagesEncodingProvider.cs.
    {
        if (codepage < 0 || codepage > 65535)
        {
            return null;
        }
        if (codepage == 0)
        {
            int systemDefaultCodePage = SystemDefaultCodePage;
            if (systemDefaultCodePage == 0)
            {
                return null;
            }
            return GetEncoding(systemDefaultCodePage);
        }
        Encoding value = null;
        _cacheLock.EnterUpgradeableReadLock();
        try
        {
            if (_encodings.TryGetValue(codepage, out value))
            {
                return value;
            }
            switch (BaseCodePageEncoding.GetCodePageByteSize(codepage))
            {
            case 1:
                value = new SBCSCodePageEncoding(codepage);
                break;
            case 2:
                value = new DBCSCodePageEncoding(codepage);
                break;
            default:
                value = GetEncodingRare(codepage);
                if (value == null)
                {
                    return null;
                }
                break;
            }
            _cacheLock.EnterWriteLock();
            try
            {
                if (_encodings.TryGetValue(codepage, out var value2))
                {
                    return value2;
                }
                _encodings.Add(codepage, value);
                return value;
            }
            finally
            {
                _cacheLock.ExitWriteLock();
            }
        }
        finally
        {
            _cacheLock.ExitUpgradeableReadLock();
        }
    }
References System.Text.CodePagesEncodingProvider._cacheLock, System.Text.CodePagesEncodingProvider._encodings, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Threading.ReaderWriterLockSlim.EnterUpgradeableReadLock(), System.Threading.ReaderWriterLockSlim.EnterWriteLock(), System.Threading.ReaderWriterLockSlim.ExitUpgradeableReadLock(), System.Threading.ReaderWriterLockSlim.ExitWriteLock(), System.Text.BaseCodePageEncoding.GetCodePageByteSize(), System.Text.CodePagesEncodingProvider.GetEncoding(), System.Text.CodePagesEncodingProvider.GetEncodingRare(), System.Text.CodePagesEncodingProvider.SystemDefaultCodePage, System.Collections.Generic.Dictionary< TKey, TValue >.TryGetValue(), and System.value.
Referenced by System.Text.CodePagesEncodingProvider.GetEncoding(), and System.Text.CodePagesEncodingProvider.GetEncoding().