Terraria: UIWorkshopImportWorldListItem.DrawSelf
DrawSelf()
override void UIWorkshopImportWorldListItem.DrawSelf (SpriteBatch spriteBatch) inline protected virtual
Reimplemented from UIPanel.
     {
         base.DrawSelf(spriteBatch);
         CalculatedStyle innerDimensions = GetInnerDimensions();
         CalculatedStyle dimensions = _worldIcon.GetDimensions();
         float num = dimensions.X + dimensions.Width;
         Color color = (_data.IsValid ? Color.White : Color.Gray);
         string worldName = _data.GetWorldName(allowCropping: true);
         if (worldName != null)
         {
             Utils.DrawBorderString(spriteBatch, worldName, new Vector2(num + 6f, dimensions.Y - 2f), color);
         }
         spriteBatch.Draw(_workshopIconTexture.Value, new Vector2(GetDimensions().X + GetDimensions().Width - (float)_workshopIconTexture.Width() - 3f, GetDimensions().Y + 2f), _workshopIconTexture.Frame(), Color.White);
         spriteBatch.Draw(_dividerTexture.Value, new Vector2(num, innerDimensions.Y + 21f), null, Color.White, 0f, Vector2.Zero, new Vector2((GetDimensions().X + GetDimensions().Width - num) / 8f, 1f), SpriteEffects.None, 0f);
         Vector2 vector = new Vector2(num + 6f, innerDimensions.Y + 29f);
         float num2 = 100f;
         DrawPanel(spriteBatch, vector, num2);
         string expertText = "";
         Color gameModeColor = Color.White;
         GetDifficulty(out expertText, out gameModeColor);
         float x = FontAssets.MouseText.Value.MeasureString(expertText).X;
         float x2 = num2 * 0.5f - x * 0.5f;
         Utils.DrawBorderString(spriteBatch, expertText, vector + new Vector2(x2, 3f), gameModeColor);
         vector.X += num2 + 5f;
         if (_data._worldSizeName != null)
         {
             float num3 = 150f;
             if (!GameCulture.FromCultureName(GameCulture.CultureName.English).IsActive)
             {
                 num3 += 40f;
             }
             DrawPanel(spriteBatch, vector, num3);
             string textValue = Language.GetTextValue("UI.WorldSizeFormat", _data.WorldSizeName);
             float x3 = FontAssets.MouseText.Value.MeasureString(textValue).X;
             float x4 = num3 * 0.5f - x3 * 0.5f;
             Utils.DrawBorderString(spriteBatch, textValue, vector + new Vector2(x4, 3f), Color.White);
             vector.X += num3 + 5f;
         }
         float num4 = innerDimensions.X + innerDimensions.Width - vector.X;
         DrawPanel(spriteBatch, vector, num4);
         string arg = ((!GameCulture.FromCultureName(GameCulture.CultureName.English).IsActive) ? _data.CreationTime.ToShortDateString() : _data.CreationTime.ToString("d MMMM yyyy"));
         string textValue2 = Language.GetTextValue("UI.WorldCreatedFormat", arg);
         float x5 = FontAssets.MouseText.Value.MeasureString(textValue2).X;
         float x6 = num4 * 0.5f - x5 * 0.5f;
         Utils.DrawBorderString(spriteBatch, textValue2, vector + new Vector2(x6, 3f), Color.White);
         vector.X += num4 + 5f;
     }
References AWorldListItem._data, _dividerTexture, _workshopIconTexture, _worldIcon, WorldFileData._worldSizeName, Color, WorldFileData.CreationTime, Utils.DrawBorderString(), DrawPanel(), GameCulture.FromCultureName(), AWorldListItem.GetDifficulty(), UIElement.GetDimensions(), UIElement.GetInnerDimensions(), Language.GetTextValue(), WorldFileData.GetWorldName(), GameCulture.IsActive, WorldFileData.IsValid, FontAssets.MouseText, Asset< T >.Value, CalculatedStyle.Width, UIElement.Width, WorldFileData.WorldSizeName, X, CalculatedStyle.X, Y, and CalculatedStyle.Y.