Terraria: System.Xml.XmlSqlBinaryReader.MoveToNextAttribute
MoveToNextAttribute()
override bool System.Xml.XmlSqlBinaryReader.MoveToNextAttribute () inline
Definition at line 779 of file XmlSqlBinaryReader.cs.
    {
        switch (_state)
        {
        case ScanState.Doc:
        case ScanState.Attr:
        case ScanState.AttrVal:
        case ScanState.AttrValPseudoValue:
            if (_attrIndex >= _attrCount)
            {
                return false;
            }
            PositionOnAttribute(++_attrIndex);
            return true;
        case ScanState.XmlText:
            return UpdateFromTextReader(_textXmlReader.MoveToNextAttribute());
        default:
            return false;
        }
    }
References System.Xml.XmlSqlBinaryReader._attrCount, System.Xml.XmlSqlBinaryReader._attrIndex, System.Xml.XmlSqlBinaryReader._state, System.Xml.XmlSqlBinaryReader._textXmlReader, System.Xml.XmlReader.MoveToNextAttribute(), System.Xml.XmlSqlBinaryReader.PositionOnAttribute(), and System.Xml.XmlSqlBinaryReader.UpdateFromTextReader().