Terraria: System.Xml.XmlSqlBinaryReader.ImplReadDoctype
ImplReadDoctype()
void System.Xml.XmlSqlBinaryReader.ImplReadDoctype () inline private
Definition at line 2944 of file XmlSqlBinaryReader.cs.
    {
        if (_dtdProcessing == DtdProcessing.Prohibit)
        {
            throw ThrowXmlException(System.SR.Xml_DtdIsProhibited);
        }
        switch (_docState)
        {
        case 9:
            throw ThrowXmlException(System.SR.Xml_DtdNotAllowedInFragment);
        default:
            throw ThrowXmlException(System.SR.Xml_BadDTDLocation);
        case 0:
        case 1:
            _docState = 2;
            _qnameOther.localname = ParseText();
            if (BinXmlToken.System == PeekToken())
            {
                _pos++;
                _attributes[_attrCount++].Set(new QName(string.Empty, _xnt.Add("SYSTEM"), string.Empty), ParseText());
            }
            if (BinXmlToken.Public == PeekToken())
            {
                _pos++;
                _attributes[_attrCount++].Set(new QName(string.Empty, _xnt.Add("PUBLIC"), string.Empty), ParseText());
            }
            if (BinXmlToken.Subset == PeekToken())
            {
                _pos++;
                _mark = _pos;
                _tokLen = ScanText(out _tokDataPos);
            }
            else
            {
                _tokLen = (_tokDataPos = 0);
            }
            _nodetype = XmlNodeType.DocumentType;
            _posAfterAttrs = _pos;
            break;
        }
    }
References System.Xml.XmlSqlBinaryReader._attrCount, System.Xml.XmlSqlBinaryReader._attributes, System.Xml.XmlSqlBinaryReader._docState, System.Xml.XmlSqlBinaryReader._dtdProcessing, System.Xml.XmlSqlBinaryReader._mark, System.Xml.XmlSqlBinaryReader._nodetype, System.Xml.XmlSqlBinaryReader._pos, System.Xml.XmlSqlBinaryReader._posAfterAttrs, System.Xml.XmlSqlBinaryReader._tokDataPos, System.Xml.XmlSqlBinaryReader._tokLen, System.Xml.XmlSqlBinaryReader._xnt, System.Xml.XmlNameTable.Add(), System.Xml.Dictionary, System.Xml.XmlSqlBinaryReader.ParseText(), System.Xml.XmlSqlBinaryReader.PeekToken(), System.Xml.QName, System.Xml.XmlSqlBinaryReader.ScanText(), System.Xml.XmlSqlBinaryReader.AttrInfo.Set(), System.Xml.XmlSqlBinaryReader.ThrowXmlException(), System.SR.Xml_BadDTDLocation, System.SR.Xml_DtdIsProhibited, and System.SR.Xml_DtdNotAllowedInFragment.
Referenced by System.Xml.XmlSqlBinaryReader.ReadDoc().