Terraria: System.Xml.XmlSqlBinaryReader.FinishEndElement
FinishEndElement()
void System.Xml.XmlSqlBinaryReader.FinishEndElement () inline private
Definition at line 2642 of file XmlSqlBinaryReader.cs.
    {
        NamespaceDecl firstInScopeChain = _elementStack[_elemDepth].Clear();
        PopNamespaces(firstInScopeChain);
        _elemDepth--;
    }
References System.Xml.XmlSqlBinaryReader._elemDepth, System.Xml.XmlSqlBinaryReader._elementStack, System.Xml.XmlSqlBinaryReader.ElemInfo.Clear(), and System.Xml.XmlSqlBinaryReader.PopNamespaces().
Referenced by System.Xml.XmlSqlBinaryReader.ReadDoc().