Terraria: System.Xml.XmlSqlBinaryReader.ValueAsDouble
ValueAsDouble()
double System.Xml.XmlSqlBinaryReader.ValueAsDouble () inline private
Definition at line 3493 of file XmlSqlBinaryReader.cs.
    {
        CheckValueTokenBounds();
        switch (_token)
        {
        case BinXmlToken.SQL_SMALLINT:
        case BinXmlToken.SQL_INT:
        case BinXmlToken.SQL_BIT:
        case BinXmlToken.SQL_TINYINT:
        case BinXmlToken.SQL_BIGINT:
        case BinXmlToken.XSD_BYTE:
        case BinXmlToken.XSD_UNSIGNEDSHORT:
        case BinXmlToken.XSD_UNSIGNEDINT:
            return ValueAsLong();
        case BinXmlToken.XSD_UNSIGNEDLONG:
            return ValueAsULong();
        case BinXmlToken.SQL_REAL:
            return GetSingle(_tokDataPos);
        case BinXmlToken.SQL_FLOAT:
            return GetDouble(_tokDataPos);
        case BinXmlToken.SQL_MONEY:
        case BinXmlToken.SQL_DECIMAL:
        case BinXmlToken.SQL_NUMERIC:
        case BinXmlToken.SQL_SMALLMONEY:
        case BinXmlToken.XSD_DECIMAL:
            return (double)ValueAsDecimal();
        default:
            throw ThrowUnexpectedToken(_token);
        }
    }
References System.Xml.XmlSqlBinaryReader._tokDataPos, System.Xml.XmlSqlBinaryReader._token, System.Xml.XmlSqlBinaryReader.CheckValueTokenBounds(), System.Xml.XmlSqlBinaryReader.GetDouble(), System.Xml.XmlSqlBinaryReader.GetSingle(), System.Xml.XmlSqlBinaryReader.ThrowUnexpectedToken(), System.Xml.XmlSqlBinaryReader.ValueAsDecimal(), System.Xml.XmlSqlBinaryReader.ValueAsLong(), and System.Xml.XmlSqlBinaryReader.ValueAsULong().
Referenced by System.Xml.XmlSqlBinaryReader.ReadContentAsDouble(), System.Xml.XmlSqlBinaryReader.ReadContentAsFloat(), and System.Xml.XmlSqlBinaryReader.ValueAsLong().