Terraria: System.Xml.XmlSqlBinaryReader.ReadContentAs
ReadContentAs() [1/2]
override object System.Xml.XmlSqlBinaryReader.ReadContentAs (Type returnType, IXmlNamespaceResolver namespaceResolver) inline
Definition at line 1626 of file XmlSqlBinaryReader.cs.
    {
        int num = _pos;
        try
        {
            if (SetupContentAsXXX("ReadContentAs"))
            {
                object result;
                try
                {
                    result = ((NodeType != XmlNodeType.Element && NodeType != XmlNodeType.EndElement) ? ((!(returnType == ValueType) && !(returnType == typeof(object))) ? ValueAs(_token, returnType, namespaceResolver) : ValueAsObject(_token, returnInternalTypes: false)) : string.Empty);
                }
                catch (InvalidCastException innerException)
                {
                    throw new XmlException(System.SR.Xml_ReadContentAsFormatException, returnType.ToString(), innerException, null);
                }
                catch (FormatException innerException2)
                {
                    throw new XmlException(System.SR.Xml_ReadContentAsFormatException, returnType.ToString(), innerException2, null);
                }
                catch (OverflowException innerException3)
                {
                    throw new XmlException(System.SR.Xml_ReadContentAsFormatException, returnType.ToString(), innerException3, null);
                }
                num = FinishContentAsXXX(num);
                return result;
            }
        }
        finally
        {
            _pos = num;
        }
        return base.ReadContentAs(returnType, namespaceResolver);
    }
References System.Xml.XmlSqlBinaryReader._pos, System.Xml.XmlSqlBinaryReader._token, System.Xml.Dictionary, System.Xml.XmlSqlBinaryReader.FinishContentAsXXX(), System.Xml.XmlSqlBinaryReader.NodeType, System.Xml.XmlSqlBinaryReader.SetupContentAsXXX(), System.Xml.XmlSqlBinaryReader.ValueAs(), System.Xml.XmlSqlBinaryReader.ValueAsObject(), System.SR.Xml_ReadContentAsFormatException, and System.Xml.XmlException.