Terraria: System.Xml.XmlSqlBinaryReader.XmlSqlBinaryReader
XmlSqlBinaryReader()
System.Xml.XmlSqlBinaryReader.XmlSqlBinaryReader (Stream stream, byte[] data, int len, string baseUri, bool closeInput, XmlReaderSettings settings) inline
Definition at line 594 of file XmlSqlBinaryReader.cs.
    {
        _xnt = settings.NameTable;
        if (_xnt == null)
        {
            _xnt = new NameTable();
            _xntFromSettings = false;
        }
        else
        {
            _xntFromSettings = true;
        }
        _xml = _xnt.Add("xml");
        _xmlns = _xnt.Add("xmlns");
        _nsxmlns = _xnt.Add("http://www.w3.org/2000/xmlns/");
        _baseUri = baseUri;
        _state = ScanState.Init;
        _nodetype = XmlNodeType.None;
        _token = BinXmlToken.Error;
        _elementStack = new ElemInfo[16];
        _attributes = new AttrInfo[8];
        _attrHashTbl = new int[8];
        _symbolTables.Init();
        _qnameOther.Clear();
        _qnameElement.Clear();
        _xmlspacePreserve = false;
        _namespaces = new Dictionary<string, NamespaceDecl>();
        AddInitNamespace(string.Empty, string.Empty);
        AddInitNamespace(_xml, _xnt.Add("http://www.w3.org/XML/1998/namespace"));
        AddInitNamespace(_xmlns, _nsxmlns);
        _valueType = TypeOfString;
        _inStrm = stream;
        if (data != null)
        {
            _data = data;
            _end = len;
            _pos = 2;
            _sniffed = true;
        }
        else
        {
            _data = new byte[4096];
            _end = stream.Read(_data, 0, 4096);
            _pos = 0;
            _sniffed = false;
        }
        _mark = -1;
        _eof = _end == 0;
        _closeInput = closeInput;
        switch (settings.ConformanceLevel)
        {
        case ConformanceLevel.Auto:
            _docState = 0;
            break;
        case ConformanceLevel.Fragment:
            _docState = 9;
            break;
        case ConformanceLevel.Document:
            _docState = 1;
            break;
        }
        _checkCharacters = settings.CheckCharacters;
        _dtdProcessing = settings.DtdProcessing;
        _ignoreWhitespace = settings.IgnoreWhitespace;
        _ignorePIs = settings.IgnoreProcessingInstructions;
        _ignoreComments = settings.IgnoreComments;
        s_tokenTypeMap = s_tokenTypeMap ?? GenerateTokenTypeMap();
    }
References System.Xml.XmlSqlBinaryReader._attrHashTbl, System.Xml.XmlSqlBinaryReader._attributes, System.Xml.XmlSqlBinaryReader._baseUri, System.Xml.XmlSqlBinaryReader._checkCharacters, System.Xml.XmlSqlBinaryReader._closeInput, System.Xml.XmlSqlBinaryReader._data, System.Xml.XmlSqlBinaryReader._docState, System.Xml.XmlSqlBinaryReader._dtdProcessing, System.Xml.XmlSqlBinaryReader._elementStack, System.Xml.XmlSqlBinaryReader._end, System.Xml.XmlSqlBinaryReader._eof, System.Xml.XmlSqlBinaryReader._ignoreComments, System.Xml.XmlSqlBinaryReader._ignorePIs, System.Xml.XmlSqlBinaryReader._ignoreWhitespace, System.Xml.XmlSqlBinaryReader._inStrm, System.Xml.XmlSqlBinaryReader._mark, System.Xml.XmlSqlBinaryReader._namespaces, System.Xml.XmlSqlBinaryReader._nodetype, System.Xml.XmlSqlBinaryReader._nsxmlns, System.Xml.XmlSqlBinaryReader._pos, System.Xml.XmlSqlBinaryReader._qnameElement, System.Xml.XmlSqlBinaryReader._qnameOther, System.Xml.XmlSqlBinaryReader._sniffed, System.Xml.XmlSqlBinaryReader._state, System.Xml.XmlSqlBinaryReader._symbolTables, System.Xml.XmlSqlBinaryReader._token, System.Xml.XmlSqlBinaryReader._valueType, System.Xml.XmlSqlBinaryReader._xml, System.Xml.XmlSqlBinaryReader._xmlns, System.Xml.XmlSqlBinaryReader._xmlspacePreserve, System.Xml.XmlSqlBinaryReader._xnt, System.Xml.XmlSqlBinaryReader._xntFromSettings, System.Xml.XmlNameTable.Add(), System.Xml.XmlSqlBinaryReader.AddInitNamespace(), System.Xml.XmlReaderSettings.CheckCharacters, System.Xml.XmlSqlBinaryReader.QName.Clear(), System.Xml.XmlReaderSettings.ConformanceLevel, System.Xml.Dictionary, System.Xml.XmlReaderSettings.DtdProcessing, System.Xml.XmlSqlBinaryReader.GenerateTokenTypeMap(), System.Xml.XmlReaderSettings.IgnoreComments, System.Xml.XmlReaderSettings.IgnoreProcessingInstructions, System.Xml.XmlReaderSettings.IgnoreWhitespace, System.Xml.XmlSqlBinaryReader.SymbolTables.Init(), System.len, System.Xml.XmlReaderSettings.NameTable, System.Xml.XmlSqlBinaryReader.NameTable, System.Xml.XmlSqlBinaryReader.s_tokenTypeMap, System.stream, and System.Xml.XmlSqlBinaryReader.TypeOfString.