Terraria: System.Xml.XmlSqlBinaryReader.ReScanOverValue
ReScanOverValue()
void System.Xml.XmlSqlBinaryReader.ReScanOverValue (BinXmlToken token) inline private
Definition at line 3134 of file XmlSqlBinaryReader.cs.
    {
        ScanOverValue(token, attr: true, checkChars: false);
    }
References System.Xml.Dictionary, and System.Xml.XmlSqlBinaryReader.ScanOverValue().
Referenced by System.Xml.XmlSqlBinaryReader.GetAttributeText(), System.Xml.XmlSqlBinaryReader.ReadAttributeValue(), and System.Xml.XmlSqlBinaryReader.SetupContentAsXXX().