Terraria: System.Xml.XmlSqlBinaryReader.ValueAsDateTimeString
ValueAsDateTimeString()
string System.Xml.XmlSqlBinaryReader.ValueAsDateTimeString () inline private
Definition at line 3587 of file XmlSqlBinaryReader.cs.
    {
        CheckValueTokenBounds();
        switch (_token)
        {
        case BinXmlToken.SQL_DATETIME:
        {
            int tokDataPos2 = _tokDataPos;
            int int5 = GetInt32(tokDataPos2);
            uint uInt2 = GetUInt32(tokDataPos2 + 4);
            return BinXmlDateTime.SqlDateTimeToString(int5, uInt2);
        }
        case BinXmlToken.SQL_SMALLDATETIME:
        {
            int tokDataPos = _tokDataPos;
            short int4 = GetInt16(tokDataPos);
            ushort uInt = GetUInt16(tokDataPos + 2);
            return BinXmlDateTime.SqlSmallDateTimeToString(int4, uInt);
        }
        case BinXmlToken.XSD_TIME:
        {
            long int3 = GetInt64(_tokDataPos);
            return BinXmlDateTime.XsdTimeToString(int3);
        }
        case BinXmlToken.XSD_DATE:
        {
            long int2 = GetInt64(_tokDataPos);
            return BinXmlDateTime.XsdDateToString(int2);
        }
        case BinXmlToken.XSD_DATETIME:
        {
            long @int = GetInt64(_tokDataPos);
            return BinXmlDateTime.XsdDateTimeToString(@int);
        }
        case BinXmlToken.XSD_KATMAI_DATE:
            return BinXmlDateTime.XsdKatmaiDateToString(_data, _tokDataPos);
        case BinXmlToken.XSD_KATMAI_DATETIME:
            return BinXmlDateTime.XsdKatmaiDateTimeToString(_data, _tokDataPos);
        case BinXmlToken.XSD_KATMAI_TIME:
            return BinXmlDateTime.XsdKatmaiTimeToString(_data, _tokDataPos);
        case BinXmlToken.XSD_KATMAI_DATEOFFSET:
            return BinXmlDateTime.XsdKatmaiDateOffsetToString(_data, _tokDataPos);
        case BinXmlToken.XSD_KATMAI_DATETIMEOFFSET:
            return BinXmlDateTime.XsdKatmaiDateTimeOffsetToString(_data, _tokDataPos);
        case BinXmlToken.XSD_KATMAI_TIMEOFFSET:
            return BinXmlDateTime.XsdKatmaiTimeOffsetToString(_data, _tokDataPos);
        default:
            throw ThrowUnexpectedToken(_token);
        }
    }
References System.Xml.XmlSqlBinaryReader._data, System.Xml.XmlSqlBinaryReader._tokDataPos, System.Xml.XmlSqlBinaryReader._token, System.Xml.XmlSqlBinaryReader.CheckValueTokenBounds(), System.Xml.XmlSqlBinaryReader.GetInt16(), System.Xml.XmlSqlBinaryReader.GetInt32(), System.Xml.XmlSqlBinaryReader.GetInt64(), System.Xml.XmlSqlBinaryReader.GetUInt16(), System.Xml.XmlSqlBinaryReader.GetUInt32(), System.Xml.BinXmlDateTime.SqlDateTimeToString(), System.Xml.BinXmlDateTime.SqlSmallDateTimeToString(), System.Xml.XmlSqlBinaryReader.ThrowUnexpectedToken(), System.Xml.BinXmlDateTime.XsdDateTimeToString(), System.Xml.BinXmlDateTime.XsdDateToString(), System.Xml.BinXmlDateTime.XsdKatmaiDateOffsetToString(), System.Xml.BinXmlDateTime.XsdKatmaiDateTimeOffsetToString(), System.Xml.BinXmlDateTime.XsdKatmaiDateTimeToString(), System.Xml.BinXmlDateTime.XsdKatmaiDateToString(), System.Xml.BinXmlDateTime.XsdKatmaiTimeOffsetToString(), System.Xml.BinXmlDateTime.XsdKatmaiTimeToString(), and System.Xml.BinXmlDateTime.XsdTimeToString().
Referenced by System.Xml.XmlSqlBinaryReader.ValueAsString().