Terraria: System.Xml.XmlSqlBinaryReader.ValueAsDecimal
ValueAsDecimal()
decimal System.Xml.XmlSqlBinaryReader.ValueAsDecimal () inline private
Definition at line 3460 of file XmlSqlBinaryReader.cs.
    {
        CheckValueTokenBounds();
        switch (_token)
        {
        case BinXmlToken.SQL_SMALLINT:
        case BinXmlToken.SQL_INT:
        case BinXmlToken.SQL_BIT:
        case BinXmlToken.SQL_TINYINT:
        case BinXmlToken.SQL_BIGINT:
        case BinXmlToken.XSD_BYTE:
        case BinXmlToken.XSD_UNSIGNEDSHORT:
        case BinXmlToken.XSD_UNSIGNEDINT:
            return new decimal(ValueAsLong());
        case BinXmlToken.XSD_UNSIGNEDLONG:
            return new decimal(ValueAsULong());
        case BinXmlToken.SQL_REAL:
            return new decimal(GetSingle(_tokDataPos));
        case BinXmlToken.SQL_FLOAT:
            return new decimal(GetDouble(_tokDataPos));
        case BinXmlToken.SQL_SMALLMONEY:
            return new BinXmlSqlMoney(GetInt32(_tokDataPos)).ToDecimal();
        case BinXmlToken.SQL_MONEY:
            return new BinXmlSqlMoney(GetInt64(_tokDataPos)).ToDecimal();
        case BinXmlToken.SQL_DECIMAL:
        case BinXmlToken.SQL_NUMERIC:
        case BinXmlToken.XSD_DECIMAL:
            return new BinXmlSqlDecimal(_data, _tokDataPos, _token == BinXmlToken.XSD_DECIMAL).ToDecimal();
        default:
            throw ThrowUnexpectedToken(_token);
        }
    }
References System.Xml.XmlSqlBinaryReader._data, System.Xml.XmlSqlBinaryReader._tokDataPos, System.Xml.XmlSqlBinaryReader._token, System.Xml.XmlSqlBinaryReader.CheckValueTokenBounds(), System.Xml.XmlSqlBinaryReader.GetDouble(), System.Xml.XmlSqlBinaryReader.GetInt32(), System.Xml.XmlSqlBinaryReader.GetInt64(), System.Xml.XmlSqlBinaryReader.GetSingle(), System.Xml.XmlSqlBinaryReader.ThrowUnexpectedToken(), System.Xml.BinXmlSqlDecimal.ToDecimal(), System.Xml.BinXmlSqlMoney.ToDecimal(), System.Xml.XmlSqlBinaryReader.ValueAsLong(), and System.Xml.XmlSqlBinaryReader.ValueAsULong().
Referenced by System.Xml.XmlSqlBinaryReader.ReadContentAsDecimal(), System.Xml.XmlSqlBinaryReader.ValueAsDouble(), and System.Xml.XmlSqlBinaryReader.ValueAsLong().