Terraria: System.Xml.XmlSqlBinaryReader.ScanOverAnyValue
ScanOverAnyValue()
XmlNodeType System.Xml.XmlSqlBinaryReader.ScanOverAnyValue (BinXmlToken token, bool attr, bool checkChars) inline private
Definition at line 3167 of file XmlSqlBinaryReader.cs.
    {
        if (_mark < 0)
        {
            _mark = _pos;
        }
        checked
        {
            switch (token)
            {
            case BinXmlToken.SQL_BIT:
            case BinXmlToken.SQL_TINYINT:
            case BinXmlToken.XSD_BOOLEAN:
            case BinXmlToken.XSD_BYTE:
                _tokDataPos = _pos;
                _tokLen = 1;
                _pos++;
                break;
            case BinXmlToken.SQL_SMALLINT:
            case BinXmlToken.XSD_UNSIGNEDSHORT:
                _tokDataPos = _pos;
                _tokLen = 2;
                _pos += 2;
                break;
            case BinXmlToken.SQL_INT:
            case BinXmlToken.SQL_REAL:
            case BinXmlToken.SQL_SMALLDATETIME:
            case BinXmlToken.SQL_SMALLMONEY:
            case BinXmlToken.XSD_UNSIGNEDINT:
                _tokDataPos = _pos;
                _tokLen = 4;
                _pos += 4;
                break;
            case BinXmlToken.SQL_FLOAT:
            case BinXmlToken.SQL_MONEY:
            case BinXmlToken.SQL_BIGINT:
            case BinXmlToken.SQL_DATETIME:
            case BinXmlToken.XSD_TIME:
            case BinXmlToken.XSD_DATETIME:
            case BinXmlToken.XSD_DATE:
            case BinXmlToken.XSD_UNSIGNEDLONG:
                _tokDataPos = _pos;
                _tokLen = 8;
                _pos += 8;
                break;
            case BinXmlToken.SQL_UUID:
                _tokDataPos = _pos;
                _tokLen = 16;
                _pos += 16;
                break;
            case BinXmlToken.SQL_DECIMAL:
            case BinXmlToken.SQL_NUMERIC:
            case BinXmlToken.XSD_DECIMAL:
                _tokDataPos = _pos;
                _tokLen = ParseMB64();
                _pos += _tokLen;
                break;
            case BinXmlToken.SQL_BINARY:
            case BinXmlToken.SQL_VARBINARY:
            case BinXmlToken.SQL_IMAGE:
            case BinXmlToken.SQL_UDT:
            case BinXmlToken.XSD_BINHEX:
            case BinXmlToken.XSD_BASE64:
                _tokLen = ParseMB64();
                _tokDataPos = _pos;
                _pos += _tokLen;
                break;
            case BinXmlToken.SQL_CHAR:
            case BinXmlToken.SQL_VARCHAR:
            case BinXmlToken.SQL_TEXT:
                _tokLen = ParseMB64();
                _tokDataPos = _pos;
                _pos += _tokLen;
                if (checkChars && _checkCharacters)
                {
                    Fill(-1);
                    string text = ValueAsString(token);
                    XmlConvert.VerifyCharData(text, ExceptionType.ArgumentException, ExceptionType.XmlException);
                    _stringValue = text;
                }
                break;
            case BinXmlToken.SQL_NCHAR:
            case BinXmlToken.SQL_NVARCHAR:
            case BinXmlToken.SQL_NTEXT:
                return ScanOverValue(BinXmlToken.SQL_NVARCHAR, attr, checkChars);
            case BinXmlToken.XSD_QNAME:
                _tokDataPos = _pos;
                ParseMB32();
                break;
            case BinXmlToken.XSD_KATMAI_TIMEOFFSET:
            case BinXmlToken.XSD_KATMAI_DATETIMEOFFSET:
            case BinXmlToken.XSD_KATMAI_DATEOFFSET:
            case BinXmlToken.XSD_KATMAI_TIME:
            case BinXmlToken.XSD_KATMAI_DATETIME:
            case BinXmlToken.XSD_KATMAI_DATE:
                VerifyVersion(2, token);
                _tokDataPos = _pos;
                _tokLen = GetXsdKatmaiTokenLength(token);
                _pos += _tokLen;
                break;
            default:
                throw ThrowUnexpectedToken(token);
            }
            Fill(-1);
            return XmlNodeType.Text;
        }
    }
References System.Xml.XmlSqlBinaryReader._checkCharacters, System.Xml.XmlSqlBinaryReader._mark, System.Xml.XmlSqlBinaryReader._pos, System.Xml.XmlSqlBinaryReader._stringValue, System.Xml.XmlSqlBinaryReader._tokDataPos, System.Xml.XmlSqlBinaryReader._tokLen, System.Xml.XmlSqlBinaryReader.Fill(), System.Xml.XmlSqlBinaryReader.GetXsdKatmaiTokenLength(), System.Xml.XmlSqlBinaryReader.ParseMB32(), System.Xml.XmlSqlBinaryReader.ParseMB64(), System.Xml.XmlSqlBinaryReader.ScanOverValue(), System.text, System.Xml.XmlSqlBinaryReader.ThrowUnexpectedToken(), System.Xml.XmlSqlBinaryReader.ValueAsString(), System.Xml.XmlConvert.VerifyCharData(), and System.Xml.XmlSqlBinaryReader.VerifyVersion().
Referenced by System.Xml.XmlSqlBinaryReader.ScanOverValue().