Terraria: System.Xml.XmlSqlBinaryReader.ReadByte
ReadByte()
byte System.Xml.XmlSqlBinaryReader.ReadByte () inline private
Definition at line 1911 of file XmlSqlBinaryReader.cs.
    {
        Fill(0);
        return _data[_pos++];
    }
References System.Xml.XmlSqlBinaryReader._data, System.Xml.XmlSqlBinaryReader._pos, and System.Xml.XmlSqlBinaryReader.Fill().
Referenced by System.Xml.XmlSqlBinaryReader.ImplReadElement(), System.Xml.XmlSqlBinaryReader.ParseMB32(), System.Xml.XmlSqlBinaryReader.ParseMB32_(), System.Xml.XmlSqlBinaryReader.ParseMB64(), and System.Xml.XmlSqlBinaryReader.ReadInit().