Terraria: System.Xml.XmlSqlBinaryReader.FinishCDATA
FinishCDATA()
void System.Xml.XmlSqlBinaryReader.FinishCDATA () inline private
Definition at line 2623 of file XmlSqlBinaryReader.cs.
    {
        while (true)
        {
            switch (PeekToken())
            {
            case BinXmlToken.CData:
                break;
            case BinXmlToken.EndCData:
                _pos++;
                return;
            default:
                throw new XmlException(System.SR.XmlBin_MissingEndCDATA);
            }
            _pos++;
            ScanText(out var _);
        }
    }
References System.Xml.XmlSqlBinaryReader._pos, System.Xml.XmlSqlBinaryReader.PeekToken(), System.Xml.XmlSqlBinaryReader.ScanText(), System.SR.XmlBin_MissingEndCDATA, and System.Xml.XmlException.
Referenced by System.Xml.XmlSqlBinaryReader.ReadDoc().