Terraria: System.Xml.XmlSqlBinaryReader.ReadToken
ReadToken()
BinXmlToken System.Xml.XmlSqlBinaryReader.ReadToken () inline private
Definition at line 2026 of file XmlSqlBinaryReader.cs.
    {
        while (_pos >= _end && FillAllowEOF())
        {
        }
        if (_pos >= _end)
        {
            return BinXmlToken.EOF;
        }
        return (BinXmlToken)_data[_pos++];
    }
References System.Xml.XmlSqlBinaryReader._data, System.Xml.XmlSqlBinaryReader._end, System.Xml.XmlSqlBinaryReader._pos, and System.Xml.XmlSqlBinaryReader.FillAllowEOF().
Referenced by System.Xml.XmlSqlBinaryReader.NextToken1(), System.Xml.XmlSqlBinaryReader.NextToken2(), and System.Xml.XmlSqlBinaryReader.RescanNextToken().