Terraria: System.Xml.XmlSqlBinaryReader.CDATAValue
CDATAValue()
string System.Xml.XmlSqlBinaryReader.CDATAValue () inline private
Definition at line 2601 of file XmlSqlBinaryReader.cs.
    {
        string text = GetString(_tokDataPos, _tokLen);
        StringBuilder stringBuilder = null;
        while (PeekToken() == BinXmlToken.CData)
        {
            _pos++;
            if (stringBuilder == null)
            {
                stringBuilder = new StringBuilder(text.Length + text.Length / 2);
                stringBuilder.Append(text);
            }
            stringBuilder.Append(ParseText());
        }
        if (stringBuilder != null)
        {
            text = stringBuilder.ToString();
        }
        _stringValue = text;
        return text;
    }
References System.Xml.XmlSqlBinaryReader._pos, System.Xml.XmlSqlBinaryReader._stringValue, System.Xml.XmlSqlBinaryReader._tokDataPos, System.Xml.XmlSqlBinaryReader._tokLen, System.Xml.XmlSqlBinaryReader.GetString(), System.Xml.XmlSqlBinaryReader.ParseText(), System.Xml.XmlSqlBinaryReader.PeekToken(), and System.text.