Terraria: System.Xml.XmlSqlBinaryReader.ReadAttributeValue
ReadAttributeValue()
override bool System.Xml.XmlSqlBinaryReader.ReadAttributeValue () inline
Definition at line 833 of file XmlSqlBinaryReader.cs.
    {
        _stringValue = null;
        switch (_state)
        {
        case ScanState.Attr:
            if (_attributes[_attrIndex - 1].val == null)
            {
                _pos = _attributes[_attrIndex - 1].contentPos;
                BinXmlToken binXmlToken = RescanNextToken();
                if (BinXmlToken.Attr == binXmlToken || BinXmlToken.EndAttrs == binXmlToken)
                {
                    return false;
                }
                _token = binXmlToken;
                ReScanOverValue(binXmlToken);
                _valueType = GetValueType(binXmlToken);
                _state = ScanState.AttrVal;
            }
            else
            {
                _token = BinXmlToken.Error;
                _valueType = TypeOfString;
                _state = ScanState.AttrValPseudoValue;
            }
            _qnameOther.Clear();
            _nodetype = XmlNodeType.Text;
            return true;
        case ScanState.AttrVal:
            return false;
        case ScanState.XmlText:
            return UpdateFromTextReader(_textXmlReader.ReadAttributeValue());
        default:
            return false;
        }
    }
References System.Xml.XmlSqlBinaryReader._attributes, System.Xml.XmlSqlBinaryReader._attrIndex, System.Xml.XmlSqlBinaryReader._nodetype, System.Xml.XmlSqlBinaryReader._pos, System.Xml.XmlSqlBinaryReader._qnameOther, System.Xml.XmlSqlBinaryReader._state, System.Xml.XmlSqlBinaryReader._stringValue, System.Xml.XmlSqlBinaryReader._textXmlReader, System.Xml.XmlSqlBinaryReader._token, System.Xml.XmlSqlBinaryReader._valueType, System.Xml.XmlSqlBinaryReader.QName.Clear(), System.Xml.XmlSqlBinaryReader.AttrInfo.contentPos, System.Xml.Dictionary, System.Xml.XmlSqlBinaryReader.GetValueType(), System.Xml.XmlReader.ReadAttributeValue(), System.Xml.XmlSqlBinaryReader.RescanNextToken(), System.Xml.XmlSqlBinaryReader.ReScanOverValue(), System.Xml.XmlSqlBinaryReader.TypeOfString, and System.Xml.XmlSqlBinaryReader.UpdateFromTextReader().