Terraria: System.Xml.XmlSqlBinaryReader.GetUInt32
GetUInt32()
uint System.Xml.XmlSqlBinaryReader.GetUInt32 (int pos) inline private
Definition at line 3999 of file XmlSqlBinaryReader.cs.
    {
        return BinaryPrimitives.ReadUInt32LittleEndian(_data.AsSpan(pos));
    }
References System.Xml.XmlSqlBinaryReader._data, and System.Buffers.Binary.BinaryPrimitives.ReadUInt32LittleEndian().
Referenced by System.Xml.XmlSqlBinaryReader.ValueAs(), System.Xml.XmlSqlBinaryReader.ValueAsDateTime(), System.Xml.XmlSqlBinaryReader.ValueAsDateTimeString(), System.Xml.XmlSqlBinaryReader.ValueAsLong(), and System.Xml.XmlSqlBinaryReader.ValueAsObject().