Terraria: System.Xml.XmlSqlBinaryReader.ImplReadCDATA
ImplReadCDATA()
void System.Xml.XmlSqlBinaryReader.ImplReadCDATA () inline private
Definition at line 3001 of file XmlSqlBinaryReader.cs.
    {
        CheckAllowContent();
        _nodetype = XmlNodeType.CDATA;
        _mark = _pos;
        _tokLen = ScanText(out _tokDataPos);
    }
References System.Xml.XmlSqlBinaryReader._mark, System.Xml.XmlSqlBinaryReader._nodetype, System.Xml.XmlSqlBinaryReader._pos, System.Xml.XmlSqlBinaryReader._tokDataPos, System.Xml.XmlSqlBinaryReader._tokLen, System.Xml.XmlSqlBinaryReader.CheckAllowContent(), and System.Xml.XmlSqlBinaryReader.ScanText().
Referenced by System.Xml.XmlSqlBinaryReader.ReadDoc().