Terraria: System.Xml.XmlSqlBinaryReader.ValueAsULong
ValueAsULong()
ulong System.Xml.XmlSqlBinaryReader.ValueAsULong () inline private
Definition at line 3450 of file XmlSqlBinaryReader.cs.
    {
        if (BinXmlToken.XSD_UNSIGNEDLONG == _token)
        {
            CheckValueTokenBounds();
            return GetUInt64(_tokDataPos);
        }
        throw ThrowUnexpectedToken(_token);
    }
References System.Xml.XmlSqlBinaryReader._tokDataPos, System.Xml.XmlSqlBinaryReader._token, System.Xml.XmlSqlBinaryReader.CheckValueTokenBounds(), System.Xml.XmlSqlBinaryReader.GetUInt64(), and System.Xml.XmlSqlBinaryReader.ThrowUnexpectedToken().
Referenced by System.Xml.XmlSqlBinaryReader.ValueAsDecimal(), System.Xml.XmlSqlBinaryReader.ValueAsDouble(), and System.Xml.XmlSqlBinaryReader.ValueAsString().