Terraria: System.Xml.XmlSqlBinaryReader.ScanOverValue
ScanOverValue()
XmlNodeType System.Xml.XmlSqlBinaryReader.ScanOverValue (BinXmlToken token, bool attr, bool checkChars) inline private
Definition at line 3139 of file XmlSqlBinaryReader.cs.
    {
        checked
        {
            if (token == BinXmlToken.SQL_NVARCHAR)
            {
                if (_mark < 0)
                {
                    _mark = _pos;
                }
                _tokLen = ParseMB32();
                _tokDataPos = _pos;
                _pos += _tokLen * 2;
                Fill(-1);
                if (checkChars && _checkCharacters)
                {
                    return CheckText(attr);
                }
                if (!attr)
                {
                    return CheckTextIsWS();
                }
                return XmlNodeType.Text;
            }
            return ScanOverAnyValue(token, attr, checkChars);
        }
    }
References System.Xml.XmlSqlBinaryReader._checkCharacters, System.Xml.XmlSqlBinaryReader._mark, System.Xml.XmlSqlBinaryReader._pos, System.Xml.XmlSqlBinaryReader._tokDataPos, System.Xml.XmlSqlBinaryReader._tokLen, System.Xml.XmlSqlBinaryReader.CheckText(), System.Xml.XmlSqlBinaryReader.CheckTextIsWS(), System.Xml.XmlSqlBinaryReader.Fill(), System.Xml.XmlSqlBinaryReader.ParseMB32(), and System.Xml.XmlSqlBinaryReader.ScanOverAnyValue().
Referenced by System.Xml.XmlSqlBinaryReader.ImplReadData(), System.Xml.XmlSqlBinaryReader.ReScanOverValue(), System.Xml.XmlSqlBinaryReader.ScanAttributes(), and System.Xml.XmlSqlBinaryReader.ScanOverAnyValue().