Terraria: System.Xml.XmlSqlBinaryReader.SetupContentAsXXX
SetupContentAsXXX()
bool System.Xml.XmlSqlBinaryReader.SetupContentAsXXX (string name) inline private
Definition at line 947 of file XmlSqlBinaryReader.cs.
    {
        if (!XmlReader.CanReadContentAs(NodeType))
        {
            throw CreateReadContentAsException(name);
        }
        switch (_state)
        {
        case ScanState.Doc:
            if (NodeType == XmlNodeType.EndElement)
            {
                return true;
            }
            if (NodeType == XmlNodeType.ProcessingInstruction || NodeType == XmlNodeType.Comment)
            {
                while (Read() && (NodeType == XmlNodeType.ProcessingInstruction || NodeType == XmlNodeType.Comment))
                {
                }
                if (NodeType == XmlNodeType.EndElement)
                {
                    return true;
                }
            }
            if (_hasTypedValue)
            {
                return true;
            }
            break;
        case ScanState.Attr:
        {
            _pos = _attributes[_attrIndex - 1].contentPos;
            BinXmlToken binXmlToken = RescanNextToken();
            if (BinXmlToken.Attr != binXmlToken && BinXmlToken.EndAttrs != binXmlToken)
            {
                _token = binXmlToken;
                ReScanOverValue(binXmlToken);
                return true;
            }
            break;
        }
        case ScanState.AttrVal:
            return true;
        }
        return false;
    }
References System.Xml.XmlSqlBinaryReader._attributes, System.Xml.XmlSqlBinaryReader._attrIndex, System.Xml.XmlSqlBinaryReader._hasTypedValue, System.Xml.XmlSqlBinaryReader._pos, System.Xml.XmlSqlBinaryReader._state, System.Xml.XmlSqlBinaryReader._token, System.Xml.XmlReader.CanReadContentAs(), System.Xml.XmlSqlBinaryReader.AttrInfo.contentPos, System.Xml.XmlReader.CreateReadContentAsException(), System.Xml.Dictionary, System.Xml.XmlSqlBinaryReader.NodeType, System.Xml.XmlSqlBinaryReader.Read(), System.Xml.XmlSqlBinaryReader.RescanNextToken(), and System.Xml.XmlSqlBinaryReader.ReScanOverValue().
Referenced by System.Xml.XmlSqlBinaryReader.ReadContentAs(), System.Xml.XmlSqlBinaryReader.ReadContentAsBoolean(), System.Xml.XmlSqlBinaryReader.ReadContentAsDateTime(), System.Xml.XmlSqlBinaryReader.ReadContentAsDecimal(), System.Xml.XmlSqlBinaryReader.ReadContentAsDouble(), System.Xml.XmlSqlBinaryReader.ReadContentAsFloat(), System.Xml.XmlSqlBinaryReader.ReadContentAsInt(), System.Xml.XmlSqlBinaryReader.ReadContentAsLong(), and System.Xml.XmlSqlBinaryReader.ReadContentAsObject().