Terraria: System.Xml.XmlSqlBinaryReader.ValueAsString
ValueAsString()
string System.Xml.XmlSqlBinaryReader.ValueAsString (BinXmlToken token) inline private
Definition at line 3638 of file XmlSqlBinaryReader.cs.
    {
        try
        {
            CheckValueTokenBounds();
            switch (token)
            {
            case BinXmlToken.SQL_NCHAR:
            case BinXmlToken.SQL_NVARCHAR:
            case BinXmlToken.SQL_NTEXT:
                return GetString(_tokDataPos, _tokLen);
            case BinXmlToken.XSD_BOOLEAN:
                if (_data[_tokDataPos] == 0)
                {
                    return "false";
                }
                return "true";
            case BinXmlToken.SQL_SMALLINT:
            case BinXmlToken.SQL_INT:
            case BinXmlToken.SQL_BIT:
            case BinXmlToken.SQL_TINYINT:
            case BinXmlToken.SQL_BIGINT:
            case BinXmlToken.XSD_BYTE:
            case BinXmlToken.XSD_UNSIGNEDSHORT:
            case BinXmlToken.XSD_UNSIGNEDINT:
                return ValueAsLong().ToString(CultureInfo.InvariantCulture);
            case BinXmlToken.XSD_UNSIGNEDLONG:
                return ValueAsULong().ToString(CultureInfo.InvariantCulture);
            case BinXmlToken.SQL_REAL:
                return XmlConvert.ToString(GetSingle(_tokDataPos));
            case BinXmlToken.SQL_FLOAT:
                return XmlConvert.ToString(GetDouble(_tokDataPos));
            case BinXmlToken.SQL_UUID:
            {
                int tokDataPos2 = _tokDataPos;
                int int2 = GetInt32(tokDataPos2);
                short int3 = GetInt16(tokDataPos2 + 4);
                short int4 = GetInt16(tokDataPos2 + 6);
                return new Guid(int2, int3, int4, _data[tokDataPos2 + 8], _data[tokDataPos2 + 9], _data[tokDataPos2 + 10], _data[tokDataPos2 + 11], _data[tokDataPos2 + 12], _data[tokDataPos2 + 13], _data[tokDataPos2 + 14], _data[tokDataPos2 + 15]).ToString();
            }
            case BinXmlToken.SQL_SMALLMONEY:
                return new BinXmlSqlMoney(GetInt32(_tokDataPos)).ToString();
            case BinXmlToken.SQL_MONEY:
                return new BinXmlSqlMoney(GetInt64(_tokDataPos)).ToString();
            case BinXmlToken.SQL_DECIMAL:
            case BinXmlToken.SQL_NUMERIC:
            case BinXmlToken.XSD_DECIMAL:
                return new BinXmlSqlDecimal(_data, _tokDataPos, token == BinXmlToken.XSD_DECIMAL).ToString();
            case BinXmlToken.SQL_CHAR:
            case BinXmlToken.SQL_VARCHAR:
            case BinXmlToken.SQL_TEXT:
            {
                int tokDataPos = _tokDataPos;
                int @int = GetInt32(tokDataPos);
                Encoding encoding = Encoding.GetEncoding(@int);
                return encoding.GetString(_data, tokDataPos + 4, _tokLen - 4);
            }
            case BinXmlToken.SQL_BINARY:
            case BinXmlToken.SQL_VARBINARY:
            case BinXmlToken.SQL_IMAGE:
            case BinXmlToken.SQL_UDT:
            case BinXmlToken.XSD_BASE64:
                return Convert.ToBase64String(_data, _tokDataPos, _tokLen);
            case BinXmlToken.XSD_BINHEX:
                return BinHexEncoder.Encode(_data, _tokDataPos, _tokLen);
            case BinXmlToken.SQL_DATETIME:
            case BinXmlToken.SQL_SMALLDATETIME:
            case BinXmlToken.XSD_KATMAI_TIMEOFFSET:
            case BinXmlToken.XSD_KATMAI_DATETIMEOFFSET:
            case BinXmlToken.XSD_KATMAI_DATEOFFSET:
            case BinXmlToken.XSD_KATMAI_TIME:
            case BinXmlToken.XSD_KATMAI_DATETIME:
            case BinXmlToken.XSD_KATMAI_DATE:
            case BinXmlToken.XSD_TIME:
            case BinXmlToken.XSD_DATETIME:
            case BinXmlToken.XSD_DATE:
                return ValueAsDateTimeString();
            case BinXmlToken.XSD_QNAME:
            {
                int num = ParseMB32(_tokDataPos);
                if (num < 0 || num >= _symbolTables.qnameCount)
                {
                    throw new XmlException(System.SR.XmlBin_InvalidQNameID, string.Empty);
                }
                QName qName = _symbolTables.qnametable[num];
                if (qName.prefix.Length == 0)
                {
                    return qName.localname;
                }
                return qName.prefix + ":" + qName.localname;
            }
            default:
                throw ThrowUnexpectedToken(_token);
            }
        }
        catch
        {
            _state = ScanState.Error;
            throw;
        }
    }
References System.Xml.XmlSqlBinaryReader._data, System.Xml.XmlSqlBinaryReader._state, System.Xml.XmlSqlBinaryReader._symbolTables, System.Xml.XmlSqlBinaryReader._tokDataPos, System.Xml.XmlSqlBinaryReader._token, System.Xml.XmlSqlBinaryReader._tokLen, System.Xml.XmlSqlBinaryReader.CheckValueTokenBounds(), System.Xml.Dictionary, System.Xml.BinHexEncoder.Encode(), System.Xml.XmlSqlBinaryReader.GetDouble(), System.Text.Encoding.GetEncoding(), System.Xml.XmlSqlBinaryReader.GetInt16(), System.Xml.XmlSqlBinaryReader.GetInt32(), System.Xml.XmlSqlBinaryReader.GetInt64(), System.Xml.XmlSqlBinaryReader.GetSingle(), System.Text.Encoding.GetString(), System.Xml.XmlSqlBinaryReader.GetString(), System.Xml.Guid, System.Globalization.CultureInfo.InvariantCulture, System.Xml.XmlSqlBinaryReader.ParseMB32(), System.Xml.XmlSqlBinaryReader.SymbolTables.qnameCount, System.Xml.XmlSqlBinaryReader.SymbolTables.qnametable, System.Xml.XmlSqlBinaryReader.ThrowUnexpectedToken(), System.Convert.ToBase64String(), System.Xml.BinXmlSqlDecimal.ToString(), System.Xml.BinXmlSqlMoney.ToString(), System.Xml.XmlConvert.ToString(), System.Xml.XmlSqlBinaryReader.ValueAsDateTimeString(), System.Xml.XmlSqlBinaryReader.ValueAsLong(), System.Xml.XmlSqlBinaryReader.ValueAsULong(), System.SR.XmlBin_InvalidQNameID, and System.Xml.XmlException.
Referenced by System.Xml.XmlSqlBinaryReader.GetAttributeText(), System.Xml.XmlSqlBinaryReader.ScanAttributes(), System.Xml.XmlSqlBinaryReader.ScanOverAnyValue(), and System.Xml.XmlSqlBinaryReader.ValueAs().