Terraria: System.Xml.XmlSqlBinaryReader.ReadInit
ReadInit()
bool System.Xml.XmlSqlBinaryReader.ReadInit (bool skipXmlDecl) inline private
Definition at line 2366 of file XmlSqlBinaryReader.cs.
    {
        string text = null;
        if (!_sniffed)
        {
            ushort num = ReadUShort();
            if (num != 65503)
            {
                text = System.SR.XmlBinary_InvalidSignature;
                goto IL_01e6;
            }
        }
        _version = ReadByte();
        if (_version != 1 && _version != 2)
        {
            text = System.SR.XmlBinary_InvalidProtocolVersion;
        }
        else
        {
            if (1200 == ReadUShort())
            {
                _state = ScanState.Doc;
                if (BinXmlToken.XmlDecl == PeekToken())
                {
                    _pos++;
                    _attributes[0].Set(new QName(string.Empty, _xnt.Add("version"), string.Empty), ParseText());
                    _attrCount = 1;
                    if (BinXmlToken.Encoding == PeekToken())
                    {
                        _pos++;
                        _attributes[1].Set(new QName(string.Empty, _xnt.Add("encoding"), string.Empty), ParseText());
                        _attrCount++;
                    }
                    byte b = ReadByte();
                    if (b != 0)
                    {
                        if ((uint)(b - 1) > 1u)
{
                            text = System.SR.XmlBinary_InvalidStandalone;
                            goto IL_01e6;
                        }
                        _attributes[_attrCount].Set(new QName(string.Empty, _xnt.Add("standalone"), string.Empty), (b == 1) ? "yes" : "no");
                        _attrCount++;
                    }
                    if (!skipXmlDecl)
                    {
                        QName qnameElement = new QName(string.Empty, _xnt.Add("xml"), string.Empty);
                        _qnameOther = (_qnameElement = qnameElement);
                        _nodetype = XmlNodeType.XmlDeclaration;
                        _posAfterAttrs = _pos;
                        return true;
                    }
                }
                return ReadDoc();
            }
            text = System.SR.XmlBinary_UnsupportedCodePage;
        }
        goto IL_01e6;
        IL_01e6:
        _state = ScanState.Error;
        throw new XmlException(text, (string[])null);
    }
References System.Xml.XmlSqlBinaryReader._attrCount, System.Xml.XmlSqlBinaryReader._attributes, System.Xml.XmlSqlBinaryReader._nodetype, System.Xml.XmlSqlBinaryReader._pos, System.Xml.XmlSqlBinaryReader._posAfterAttrs, System.Xml.XmlSqlBinaryReader._qnameElement, System.Xml.XmlSqlBinaryReader._qnameOther, System.Xml.XmlSqlBinaryReader._sniffed, System.Xml.XmlSqlBinaryReader._state, System.Xml.XmlSqlBinaryReader._version, System.Xml.XmlSqlBinaryReader._xnt, System.Xml.XmlNameTable.Add(), System.Xml.Dictionary, System.Xml.XmlSqlBinaryReader.ParseText(), System.Xml.XmlSqlBinaryReader.PeekToken(), System.Xml.QName, System.Xml.XmlSqlBinaryReader.ReadByte(), System.Xml.XmlSqlBinaryReader.ReadDoc(), System.Xml.XmlSqlBinaryReader.ReadUShort(), System.Xml.XmlSqlBinaryReader.AttrInfo.Set(), System.text, System.SR.XmlBinary_InvalidProtocolVersion, System.SR.XmlBinary_InvalidSignature, System.SR.XmlBinary_InvalidStandalone, System.SR.XmlBinary_UnsupportedCodePage, and System.Xml.XmlException.
Referenced by System.Xml.XmlSqlBinaryReader.Read(), and System.Xml.XmlSqlBinaryReader.ReadDoc().