Terraria: System.Xml.XmlSqlBinaryReader.ValueAsLong
ValueAsLong()
long System.Xml.XmlSqlBinaryReader.ValueAsLong () inline private
Definition at line 3399 of file XmlSqlBinaryReader.cs.
    {
        CheckValueTokenBounds();
        switch (_token)
        {
        case BinXmlToken.SQL_BIT:
        case BinXmlToken.SQL_TINYINT:
        {
            byte b2 = _data[_tokDataPos];
            return b2;
        }
        case BinXmlToken.XSD_BYTE:
        {
            sbyte b = (sbyte)_data[_tokDataPos];
            return b;
        }
        case BinXmlToken.SQL_SMALLINT:
            return GetInt16(_tokDataPos);
        case BinXmlToken.SQL_INT:
            return GetInt32(_tokDataPos);
        case BinXmlToken.SQL_BIGINT:
            return GetInt64(_tokDataPos);
        case BinXmlToken.XSD_UNSIGNEDSHORT:
            return GetUInt16(_tokDataPos);
        case BinXmlToken.XSD_UNSIGNEDINT:
            return GetUInt32(_tokDataPos);
        case BinXmlToken.XSD_UNSIGNEDLONG:
        {
            ulong uInt = GetUInt64(_tokDataPos);
            return checked((long)uInt);
        }
        case BinXmlToken.SQL_REAL:
        case BinXmlToken.SQL_FLOAT:
        {
            double num2 = ValueAsDouble();
            return (long)num2;
        }
        case BinXmlToken.SQL_MONEY:
        case BinXmlToken.SQL_DECIMAL:
        case BinXmlToken.SQL_NUMERIC:
        case BinXmlToken.SQL_SMALLMONEY:
        case BinXmlToken.XSD_DECIMAL:
        {
            decimal num = ValueAsDecimal();
            return (long)num;
        }
        default:
            throw ThrowUnexpectedToken(_token);
        }
    }
References System.Xml.XmlSqlBinaryReader._data, System.Xml.XmlSqlBinaryReader._tokDataPos, System.Xml.XmlSqlBinaryReader._token, System.Xml.XmlSqlBinaryReader.CheckValueTokenBounds(), System.Xml.Dictionary, System.Xml.XmlSqlBinaryReader.GetInt16(), System.Xml.XmlSqlBinaryReader.GetInt32(), System.Xml.XmlSqlBinaryReader.GetInt64(), System.Xml.XmlSqlBinaryReader.GetUInt16(), System.Xml.XmlSqlBinaryReader.GetUInt32(), System.Xml.XmlSqlBinaryReader.GetUInt64(), System.Xml.XmlSqlBinaryReader.ThrowUnexpectedToken(), System.Xml.XmlSqlBinaryReader.ValueAsDecimal(), and System.Xml.XmlSqlBinaryReader.ValueAsDouble().
Referenced by System.Xml.XmlSqlBinaryReader.ReadContentAsInt(), System.Xml.XmlSqlBinaryReader.ReadContentAsLong(), System.Xml.XmlSqlBinaryReader.ValueAsDecimal(), System.Xml.XmlSqlBinaryReader.ValueAsDouble(), and System.Xml.XmlSqlBinaryReader.ValueAsString().