Terraria: System.Xml.XmlSqlBinaryReader.GetXsdKatmaiTokenLength
GetXsdKatmaiTokenLength()
int System.Xml.XmlSqlBinaryReader.GetXsdKatmaiTokenLength (BinXmlToken token) inline private
Definition at line 3364 of file XmlSqlBinaryReader.cs.
    {
        switch (token)
        {
        case BinXmlToken.XSD_KATMAI_DATE:
            return 3;
        case BinXmlToken.XSD_KATMAI_TIME:
        case BinXmlToken.XSD_KATMAI_DATETIME:
        {
            Fill(0);
            byte scale = _data[_pos];
            return 4 + XsdKatmaiTimeScaleToValueLength(scale);
        }
        case BinXmlToken.XSD_KATMAI_TIMEOFFSET:
        case BinXmlToken.XSD_KATMAI_DATETIMEOFFSET:
        case BinXmlToken.XSD_KATMAI_DATEOFFSET:
        {
            Fill(0);
            byte scale = _data[_pos];
            return 6 + XsdKatmaiTimeScaleToValueLength(scale);
        }
        default:
            throw ThrowUnexpectedToken(_token);
        }
    }
References System.Xml.XmlSqlBinaryReader._data, System.Xml.XmlSqlBinaryReader._pos, System.Xml.XmlSqlBinaryReader._token, System.Xml.XmlSqlBinaryReader.Fill(), System.Xml.XmlSqlBinaryReader.ThrowUnexpectedToken(), and System.Xml.XmlSqlBinaryReader.XsdKatmaiTimeScaleToValueLength().
Referenced by System.Xml.XmlSqlBinaryReader.ScanOverAnyValue().