Terraria: System.Xml.XmlSqlBinaryReader.Fill
Fill()
void System.Xml.XmlSqlBinaryReader.Fill (int require) inline private
Definition at line 1903 of file XmlSqlBinaryReader.cs.
    {
        if (_pos + require >= _end)
        {
            Fill_(require);
        }
    }
References System.Xml.XmlSqlBinaryReader._end, System.Xml.XmlSqlBinaryReader._pos, and System.Xml.XmlSqlBinaryReader.Fill_().
Referenced by System.Xml.XmlSqlBinaryReader.GetXsdKatmaiTokenLength(), System.Xml.XmlSqlBinaryReader.ReadByte(), System.Xml.XmlSqlBinaryReader.ReadUShort(), System.Xml.XmlSqlBinaryReader.ScanOverAnyValue(), System.Xml.XmlSqlBinaryReader.ScanOverValue(), System.Xml.XmlSqlBinaryReader.ScanText(), and System.Xml.XmlSqlBinaryReader.SkipExtn().