Terraria: System.Xml.XmlSqlBinaryReader.ValueAsDateTime
ValueAsDateTime()
DateTime System.Xml.XmlSqlBinaryReader.ValueAsDateTime () inline private
Definition at line 3524 of file XmlSqlBinaryReader.cs.
    {
        CheckValueTokenBounds();
        switch (_token)
        {
        case BinXmlToken.SQL_DATETIME:
        {
            int tokDataPos2 = _tokDataPos;
            int int5 = GetInt32(tokDataPos2);
            uint uInt2 = GetUInt32(tokDataPos2 + 4);
            return BinXmlDateTime.SqlDateTimeToDateTime(int5, uInt2);
        }
        case BinXmlToken.SQL_SMALLDATETIME:
        {
            int tokDataPos = _tokDataPos;
            short int4 = GetInt16(tokDataPos);
            ushort uInt = GetUInt16(tokDataPos + 2);
            return BinXmlDateTime.SqlSmallDateTimeToDateTime(int4, uInt);
        }
        case BinXmlToken.XSD_TIME:
        {
            long int3 = GetInt64(_tokDataPos);
            return BinXmlDateTime.XsdTimeToDateTime(int3);
        }
        case BinXmlToken.XSD_DATE:
        {
            long int2 = GetInt64(_tokDataPos);
            return BinXmlDateTime.XsdDateToDateTime(int2);
        }
        case BinXmlToken.XSD_DATETIME:
        {
            long @int = GetInt64(_tokDataPos);
            return BinXmlDateTime.XsdDateTimeToDateTime(@int);
        }
        case BinXmlToken.XSD_KATMAI_DATE:
            return BinXmlDateTime.XsdKatmaiDateToDateTime(_data, _tokDataPos);
        case BinXmlToken.XSD_KATMAI_DATETIME:
            return BinXmlDateTime.XsdKatmaiDateTimeToDateTime(_data, _tokDataPos);
        case BinXmlToken.XSD_KATMAI_TIME:
            return BinXmlDateTime.XsdKatmaiTimeToDateTime(_data, _tokDataPos);
        case BinXmlToken.XSD_KATMAI_DATEOFFSET:
            return BinXmlDateTime.XsdKatmaiDateOffsetToDateTime(_data, _tokDataPos);
        case BinXmlToken.XSD_KATMAI_DATETIMEOFFSET:
            return BinXmlDateTime.XsdKatmaiDateTimeOffsetToDateTime(_data, _tokDataPos);
        case BinXmlToken.XSD_KATMAI_TIMEOFFSET:
            return BinXmlDateTime.XsdKatmaiTimeOffsetToDateTime(_data, _tokDataPos);
        default:
            throw ThrowUnexpectedToken(_token);
        }
    }
References System.Xml.XmlSqlBinaryReader._data, System.Xml.XmlSqlBinaryReader._tokDataPos, System.Xml.XmlSqlBinaryReader._token, System.Xml.XmlSqlBinaryReader.CheckValueTokenBounds(), System.Xml.XmlSqlBinaryReader.GetInt16(), System.Xml.XmlSqlBinaryReader.GetInt32(), System.Xml.XmlSqlBinaryReader.GetInt64(), System.Xml.XmlSqlBinaryReader.GetUInt16(), System.Xml.XmlSqlBinaryReader.GetUInt32(), System.Xml.BinXmlDateTime.SqlDateTimeToDateTime(), System.Xml.BinXmlDateTime.SqlSmallDateTimeToDateTime(), System.Xml.XmlSqlBinaryReader.ThrowUnexpectedToken(), System.Xml.BinXmlDateTime.XsdDateTimeToDateTime(), System.Xml.BinXmlDateTime.XsdDateToDateTime(), System.Xml.BinXmlDateTime.XsdKatmaiDateOffsetToDateTime(), System.Xml.BinXmlDateTime.XsdKatmaiDateTimeOffsetToDateTime(), System.Xml.BinXmlDateTime.XsdKatmaiDateTimeToDateTime(), System.Xml.BinXmlDateTime.XsdKatmaiDateToDateTime(), System.Xml.BinXmlDateTime.XsdKatmaiTimeOffsetToDateTime(), System.Xml.BinXmlDateTime.XsdKatmaiTimeToDateTime(), and System.Xml.BinXmlDateTime.XsdTimeToDateTime().
Referenced by System.Xml.XmlSqlBinaryReader.ReadContentAsDateTime(), System.Xml.XmlSqlBinaryReader.ValueAs(), and System.Xml.XmlSqlBinaryReader.ValueAsObject().