Terraria: System.Xml.XmlSqlBinaryReader.ImplReadData
ImplReadData()
void System.Xml.XmlSqlBinaryReader.ImplReadData (BinXmlToken tokenType) inline private
Definition at line 2794 of file XmlSqlBinaryReader.cs.
    {
        _mark = _pos;
        switch (tokenType)
        {
        case BinXmlToken.SQL_CHAR:
        case BinXmlToken.SQL_NCHAR:
        case BinXmlToken.SQL_VARCHAR:
        case BinXmlToken.SQL_NVARCHAR:
        case BinXmlToken.SQL_TEXT:
        case BinXmlToken.SQL_NTEXT:
            _valueType = TypeOfString;
            _hasTypedValue = false;
            break;
        default:
            _valueType = GetValueType(_token);
            _hasTypedValue = true;
            break;
        }
        _nodetype = ScanOverValue(_token, attr: false, checkChars: true);
        switch (PeekNextToken())
        {
        case BinXmlToken.SQL_SMALLINT:
        case BinXmlToken.SQL_INT:
        case BinXmlToken.SQL_REAL:
        case BinXmlToken.SQL_FLOAT:
        case BinXmlToken.SQL_MONEY:
        case BinXmlToken.SQL_BIT:
        case BinXmlToken.SQL_TINYINT:
        case BinXmlToken.SQL_BIGINT:
        case BinXmlToken.SQL_UUID:
        case BinXmlToken.SQL_DECIMAL:
        case BinXmlToken.SQL_NUMERIC:
        case BinXmlToken.SQL_BINARY:
        case BinXmlToken.SQL_CHAR:
        case BinXmlToken.SQL_NCHAR:
        case BinXmlToken.SQL_VARBINARY:
        case BinXmlToken.SQL_VARCHAR:
        case BinXmlToken.SQL_NVARCHAR:
        case BinXmlToken.SQL_DATETIME:
        case BinXmlToken.SQL_SMALLDATETIME:
        case BinXmlToken.SQL_SMALLMONEY:
        case BinXmlToken.SQL_TEXT:
        case BinXmlToken.SQL_IMAGE:
        case BinXmlToken.SQL_NTEXT:
        case BinXmlToken.SQL_UDT:
        case BinXmlToken.XSD_KATMAI_TIMEOFFSET:
        case BinXmlToken.XSD_KATMAI_DATETIMEOFFSET:
        case BinXmlToken.XSD_KATMAI_DATEOFFSET:
        case BinXmlToken.XSD_KATMAI_TIME:
        case BinXmlToken.XSD_KATMAI_DATETIME:
        case BinXmlToken.XSD_KATMAI_DATE:
        case BinXmlToken.XSD_TIME:
        case BinXmlToken.XSD_DATETIME:
        case BinXmlToken.XSD_DATE:
        case BinXmlToken.XSD_BINHEX:
        case BinXmlToken.XSD_BASE64:
        case BinXmlToken.XSD_BOOLEAN:
        case BinXmlToken.XSD_DECIMAL:
        case BinXmlToken.XSD_BYTE:
        case BinXmlToken.XSD_UNSIGNEDSHORT:
        case BinXmlToken.XSD_UNSIGNEDINT:
        case BinXmlToken.XSD_UNSIGNEDLONG:
        case BinXmlToken.XSD_QNAME:
            throw ThrowNotSupported(System.SR.XmlBinary_ListsOfValuesNotSupported);
        }
    }
References System.Xml.XmlSqlBinaryReader._hasTypedValue, System.Xml.XmlSqlBinaryReader._mark, System.Xml.XmlSqlBinaryReader._nodetype, System.Xml.XmlSqlBinaryReader._pos, System.Xml.XmlSqlBinaryReader._token, System.Xml.XmlSqlBinaryReader._valueType, System.Xml.Dictionary, System.Xml.XmlSqlBinaryReader.GetValueType(), System.Xml.XmlSqlBinaryReader.PeekNextToken(), System.Xml.XmlSqlBinaryReader.ScanOverValue(), System.Xml.XmlSqlBinaryReader.ThrowNotSupported(), System.Xml.XmlSqlBinaryReader.TypeOfString, and System.SR.XmlBinary_ListsOfValuesNotSupported.
Referenced by System.Xml.XmlSqlBinaryReader.ReadDoc().