Terraria: System.Xml.XmlSqlBinaryReader.FinishContentAsXXX
FinishContentAsXXX()
int System.Xml.XmlSqlBinaryReader.FinishContentAsXXX (int origPos) inline private
Definition at line 993 of file XmlSqlBinaryReader.cs.
    {
        if (_state == ScanState.Doc)
        {
            if (NodeType != XmlNodeType.Element && NodeType != XmlNodeType.EndElement)
            {
                while (Read())
                {
                    XmlNodeType nodeType = NodeType;
                    if (nodeType == XmlNodeType.Element)
                    {
                        break;
                    }
                    if ((uint)(nodeType - 7) > 1u)
                    {
                        if (nodeType == XmlNodeType.EndElement)
{
                            break;
                        }
                        throw ThrowNotSupported(System.SR.XmlBinary_ListsOfValuesNotSupported);
                    }
                }
            }
            return _pos;
        }
        return origPos;
    }
References System.Xml.XmlSqlBinaryReader._pos, System.Xml.XmlSqlBinaryReader._state, System.Xml.Dictionary, System.Xml.XmlSqlBinaryReader.NodeType, System.Xml.XmlSqlBinaryReader.Read(), System.Xml.XmlSqlBinaryReader.ThrowNotSupported(), and System.SR.XmlBinary_ListsOfValuesNotSupported.
Referenced by System.Xml.XmlSqlBinaryReader.ReadContentAs(), System.Xml.XmlSqlBinaryReader.ReadContentAsBoolean(), System.Xml.XmlSqlBinaryReader.ReadContentAsDateTime(), System.Xml.XmlSqlBinaryReader.ReadContentAsDecimal(), System.Xml.XmlSqlBinaryReader.ReadContentAsDouble(), System.Xml.XmlSqlBinaryReader.ReadContentAsFloat(), System.Xml.XmlSqlBinaryReader.ReadContentAsInt(), System.Xml.XmlSqlBinaryReader.ReadContentAsLong(), and System.Xml.XmlSqlBinaryReader.ReadContentAsObject().