Terraria: System.Xml.XmlSqlBinaryReader.ValueAsObject
ValueAsObject()
object System.Xml.XmlSqlBinaryReader.ValueAsObject (BinXmlToken token, bool returnInternalTypes) inline private
Definition at line 3740 of file XmlSqlBinaryReader.cs.
    {
        CheckValueTokenBounds();
        switch (token)
        {
        case BinXmlToken.SQL_NCHAR:
        case BinXmlToken.SQL_NVARCHAR:
        case BinXmlToken.SQL_NTEXT:
            return GetString(_tokDataPos, _tokLen);
        case BinXmlToken.XSD_BOOLEAN:
            return _data[_tokDataPos] != 0;
        case BinXmlToken.SQL_BIT:
            return (int)_data[_tokDataPos];
        case BinXmlToken.SQL_TINYINT:
            return _data[_tokDataPos];
        case BinXmlToken.SQL_SMALLINT:
            return GetInt16(_tokDataPos);
        case BinXmlToken.SQL_INT:
            return GetInt32(_tokDataPos);
        case BinXmlToken.SQL_BIGINT:
            return GetInt64(_tokDataPos);
        case BinXmlToken.XSD_BYTE:
        {
            sbyte b = (sbyte)_data[_tokDataPos];
            return b;
        }
        case BinXmlToken.XSD_UNSIGNEDSHORT:
            return GetUInt16(_tokDataPos);
        case BinXmlToken.XSD_UNSIGNEDINT:
            return GetUInt32(_tokDataPos);
        case BinXmlToken.XSD_UNSIGNEDLONG:
            return GetUInt64(_tokDataPos);
        case BinXmlToken.SQL_REAL:
            return GetSingle(_tokDataPos);
        case BinXmlToken.SQL_FLOAT:
            return GetDouble(_tokDataPos);
        case BinXmlToken.SQL_UUID:
        {
            int tokDataPos2 = _tokDataPos;
            int int2 = GetInt32(tokDataPos2);
            short int3 = GetInt16(tokDataPos2 + 4);
            short int4 = GetInt16(tokDataPos2 + 6);
            return new Guid(int2, int3, int4, _data[tokDataPos2 + 8], _data[tokDataPos2 + 9], _data[tokDataPos2 + 10], _data[tokDataPos2 + 11], _data[tokDataPos2 + 12], _data[tokDataPos2 + 13], _data[tokDataPos2 + 14], _data[tokDataPos2 + 15]).ToString();
        }
        case BinXmlToken.SQL_SMALLMONEY:
        {
            BinXmlSqlMoney binXmlSqlMoney2 = new BinXmlSqlMoney(GetInt32(_tokDataPos));
            if (returnInternalTypes)
            {
                return binXmlSqlMoney2;
            }
            return binXmlSqlMoney2.ToDecimal();
        }
        case BinXmlToken.SQL_MONEY:
        {
            BinXmlSqlMoney binXmlSqlMoney = new BinXmlSqlMoney(GetInt64(_tokDataPos));
            if (returnInternalTypes)
            {
                return binXmlSqlMoney;
            }
            return binXmlSqlMoney.ToDecimal();
        }
        case BinXmlToken.SQL_DECIMAL:
        case BinXmlToken.SQL_NUMERIC:
        case BinXmlToken.XSD_DECIMAL:
        {
            BinXmlSqlDecimal binXmlSqlDecimal = new BinXmlSqlDecimal(_data, _tokDataPos, token == BinXmlToken.XSD_DECIMAL);
            if (returnInternalTypes)
            {
                return binXmlSqlDecimal;
            }
            return binXmlSqlDecimal.ToDecimal();
        }
        case BinXmlToken.SQL_CHAR:
        case BinXmlToken.SQL_VARCHAR:
        case BinXmlToken.SQL_TEXT:
        {
            int tokDataPos = _tokDataPos;
            int @int = GetInt32(tokDataPos);
            Encoding encoding = Encoding.GetEncoding(@int);
            return encoding.GetString(_data, tokDataPos + 4, _tokLen - 4);
        }
        case BinXmlToken.SQL_BINARY:
        case BinXmlToken.SQL_VARBINARY:
        case BinXmlToken.SQL_IMAGE:
        case BinXmlToken.SQL_UDT:
        case BinXmlToken.XSD_BINHEX:
        case BinXmlToken.XSD_BASE64:
        {
            byte[] array = new byte[_tokLen];
            Array.Copy(_data, _tokDataPos, array, 0, _tokLen);
            return array;
        }
        case BinXmlToken.SQL_DATETIME:
        case BinXmlToken.SQL_SMALLDATETIME:
        case BinXmlToken.XSD_KATMAI_TIME:
        case BinXmlToken.XSD_KATMAI_DATETIME:
        case BinXmlToken.XSD_KATMAI_DATE:
        case BinXmlToken.XSD_TIME:
        case BinXmlToken.XSD_DATETIME:
        case BinXmlToken.XSD_DATE:
            return ValueAsDateTime();
        case BinXmlToken.XSD_KATMAI_TIMEOFFSET:
        case BinXmlToken.XSD_KATMAI_DATETIMEOFFSET:
        case BinXmlToken.XSD_KATMAI_DATEOFFSET:
            return ValueAsDateTimeOffset();
        case BinXmlToken.XSD_QNAME:
        {
            int num = ParseMB32(_tokDataPos);
            if (num < 0 || num >= _symbolTables.qnameCount)
            {
                throw new XmlException(System.SR.XmlBin_InvalidQNameID, string.Empty);
            }
            QName qName = _symbolTables.qnametable[num];
            return new XmlQualifiedName(qName.localname, qName.namespaceUri);
        }
        default:
            throw ThrowUnexpectedToken(_token);
        }
    }
References System.Xml.XmlSqlBinaryReader._data, System.Xml.XmlSqlBinaryReader._symbolTables, System.Xml.XmlSqlBinaryReader._tokDataPos, System.Xml.XmlSqlBinaryReader._token, System.Xml.XmlSqlBinaryReader._tokLen, System.array, System.Xml.XmlSqlBinaryReader.CheckValueTokenBounds(), System.Array.Copy(), System.Xml.Dictionary, System.Xml.XmlSqlBinaryReader.GetDouble(), System.Text.Encoding.GetEncoding(), System.Xml.XmlSqlBinaryReader.GetInt16(), System.Xml.XmlSqlBinaryReader.GetInt32(), System.Xml.XmlSqlBinaryReader.GetInt64(), System.Xml.XmlSqlBinaryReader.GetSingle(), System.Text.Encoding.GetString(), System.Xml.XmlSqlBinaryReader.GetString(), System.Xml.XmlSqlBinaryReader.GetUInt16(), System.Xml.XmlSqlBinaryReader.GetUInt32(), System.Xml.XmlSqlBinaryReader.GetUInt64(), System.Xml.Guid, System.Xml.XmlSqlBinaryReader.ParseMB32(), System.Xml.XmlSqlBinaryReader.SymbolTables.qnameCount, System.Xml.XmlSqlBinaryReader.SymbolTables.qnametable, System.Xml.XmlSqlBinaryReader.ThrowUnexpectedToken(), System.Xml.XmlSqlBinaryReader.ValueAsDateTime(), System.Xml.XmlSqlBinaryReader.ValueAsDateTimeOffset(), System.SR.XmlBin_InvalidQNameID, and System.Xml.XmlException.
Referenced by System.Xml.XmlSqlBinaryReader.ReadContentAs(), and System.Xml.XmlSqlBinaryReader.ReadContentAsObject().