Terraria: System.Xml.XmlSqlBinaryReader.ThrowXmlException
ThrowXmlException() [1/2]
Exception System.Xml.XmlSqlBinaryReader.ThrowXmlException (string res) inline private
Definition at line 4029 of file XmlSqlBinaryReader.cs.
    {
        _state = ScanState.Error;
        return new XmlException(res, (string[])null);
    }
References System.Xml.XmlSqlBinaryReader._state, and System.Xml.XmlException.
Referenced by System.Xml.XmlSqlBinaryReader.CheckAllowContent(), System.Xml.XmlSqlBinaryReader.CheckText(), System.Xml.XmlSqlBinaryReader.CheckValueTokenBounds(), System.Xml.XmlSqlBinaryReader.Fill_(), System.Xml.XmlSqlBinaryReader.ImplReadDoctype(), System.Xml.XmlSqlBinaryReader.ImplReadEndElement(), System.Xml.XmlSqlBinaryReader.ParseMB32(), System.Xml.XmlSqlBinaryReader.ParseMB32_(), System.Xml.XmlSqlBinaryReader.ScanAttributes(), and System.Xml.XmlSqlBinaryReader.ThrowUnexpectedToken().