Terraria: System.Xml.XmlSqlBinaryReader.GetString
GetString()
string System.Xml.XmlSqlBinaryReader.GetString (int pos, int cch) inline private
Definition at line 2182 of file XmlSqlBinaryReader.cs.
    {
        checked
        {
            if (pos + cch * 2 > _end)
            {
                throw new XmlException(System.SR.Xml_UnexpectedEOF1, (string[])null);
            }
            if (cch == 0)
            {
                return string.Empty;
            }
            return string.Create(cch, (_data, pos), delegate(Span<char> dstChars, (byte[] _data, int pos) state)
            {
                int length = dstChars.Length;
                ReadOnlySpan<byte> readOnlySpan = state._data.AsSpan(state.pos, length * 2);
                Span<byte> destination = MemoryMarshal.AsBytes(dstChars);
                readOnlySpan.CopyTo(destination);
            });
        }
    }
References System.Xml.XmlSqlBinaryReader._data, System.Xml.XmlSqlBinaryReader._end, System.Collections.Generic.Dictionary< TKey, TValue >.CopyTo(), System.destination, System.Xml.Dictionary, System.length, System.state, System.SR.Xml_UnexpectedEOF1, and System.Xml.XmlException.
Referenced by System.Xml.XmlSqlBinaryReader.CDATAValue(), System.Xml.XmlSqlBinaryReader.ParseText(), System.Xml.XmlSqlBinaryReader.ValueAs(), System.Xml.XmlSqlBinaryReader.ValueAsObject(), and System.Xml.XmlSqlBinaryReader.ValueAsString().