Terraria: System.Xml.XmlSqlBinaryReader.ValueAs
ValueAs()
object System.Xml.XmlSqlBinaryReader.ValueAs (BinXmlToken token, Type returnType, IXmlNamespaceResolver namespaceResolver) inline private
Definition at line 3867 of file XmlSqlBinaryReader.cs.
    {
        CheckValueTokenBounds();
        switch (token)
        {
        case BinXmlToken.SQL_NCHAR:
        case BinXmlToken.SQL_NVARCHAR:
        case BinXmlToken.SQL_NTEXT:
            return GetValueConverter(XmlTypeCode.UntypedAtomic).ChangeType(GetString(_tokDataPos, _tokLen), returnType, namespaceResolver);
        case BinXmlToken.XSD_BOOLEAN:
            return GetValueConverter(XmlTypeCode.Boolean).ChangeType(_data[_tokDataPos] != 0, returnType, namespaceResolver);
        case BinXmlToken.SQL_BIT:
            return GetValueConverter(XmlTypeCode.NonNegativeInteger).ChangeType((int)_data[_tokDataPos], returnType, namespaceResolver);
        case BinXmlToken.SQL_TINYINT:
            return GetValueConverter(XmlTypeCode.UnsignedByte).ChangeType(_data[_tokDataPos], returnType, namespaceResolver);
        case BinXmlToken.SQL_SMALLINT:
        {
            int @int = GetInt16(_tokDataPos);
            return GetValueConverter(XmlTypeCode.Short).ChangeType(@int, returnType, namespaceResolver);
        }
        case BinXmlToken.SQL_INT:
        {
            int int2 = GetInt32(_tokDataPos);
            return GetValueConverter(XmlTypeCode.Int).ChangeType(int2, returnType, namespaceResolver);
        }
        case BinXmlToken.SQL_BIGINT:
        {
            long int4 = GetInt64(_tokDataPos);
            return GetValueConverter(XmlTypeCode.Long).ChangeType(int4, returnType, namespaceResolver);
        }
        case BinXmlToken.XSD_BYTE:
            return GetValueConverter(XmlTypeCode.Byte).ChangeType((int)(sbyte)_data[_tokDataPos], returnType, namespaceResolver);
        case BinXmlToken.XSD_UNSIGNEDSHORT:
        {
            int uInt = GetUInt16(_tokDataPos);
            return GetValueConverter(XmlTypeCode.UnsignedShort).ChangeType(uInt, returnType, namespaceResolver);
        }
        case BinXmlToken.XSD_UNSIGNEDINT:
        {
            long num3 = GetUInt32(_tokDataPos);
            return GetValueConverter(XmlTypeCode.UnsignedInt).ChangeType(num3, returnType, namespaceResolver);
        }
        case BinXmlToken.XSD_UNSIGNEDLONG:
        {
            decimal num2 = GetUInt64(_tokDataPos);
            return GetValueConverter(XmlTypeCode.UnsignedLong).ChangeType(num2, returnType, namespaceResolver);
        }
        case BinXmlToken.SQL_REAL:
        {
            float single = GetSingle(_tokDataPos);
            return GetValueConverter(XmlTypeCode.Float).ChangeType(single, returnType, namespaceResolver);
        }
        case BinXmlToken.SQL_FLOAT:
        {
            double @double = GetDouble(_tokDataPos);
            return GetValueConverter(XmlTypeCode.Double).ChangeType(@double, returnType, namespaceResolver);
        }
        case BinXmlToken.SQL_UUID:
            return GetValueConverter(XmlTypeCode.String).ChangeType(ValueAsString(token), returnType, namespaceResolver);
        case BinXmlToken.SQL_SMALLMONEY:
            return GetValueConverter(XmlTypeCode.Decimal).ChangeType(new BinXmlSqlMoney(GetInt32(_tokDataPos)).ToDecimal(), returnType, namespaceResolver);
        case BinXmlToken.SQL_MONEY:
            return GetValueConverter(XmlTypeCode.Decimal).ChangeType(new BinXmlSqlMoney(GetInt64(_tokDataPos)).ToDecimal(), returnType, namespaceResolver);
        case BinXmlToken.SQL_DECIMAL:
        case BinXmlToken.SQL_NUMERIC:
        case BinXmlToken.XSD_DECIMAL:
            return GetValueConverter(XmlTypeCode.Decimal).ChangeType(new BinXmlSqlDecimal(_data, _tokDataPos, token == BinXmlToken.XSD_DECIMAL).ToDecimal(), returnType, namespaceResolver);
        case BinXmlToken.SQL_CHAR:
        case BinXmlToken.SQL_VARCHAR:
        case BinXmlToken.SQL_TEXT:
        {
            int tokDataPos = _tokDataPos;
            int int3 = GetInt32(tokDataPos);
            Encoding encoding = Encoding.GetEncoding(int3);
            return GetValueConverter(XmlTypeCode.UntypedAtomic).ChangeType(encoding.GetString(_data, tokDataPos + 4, _tokLen - 4), returnType, namespaceResolver);
        }
        case BinXmlToken.SQL_BINARY:
        case BinXmlToken.SQL_VARBINARY:
        case BinXmlToken.SQL_IMAGE:
        case BinXmlToken.SQL_UDT:
        case BinXmlToken.XSD_BINHEX:
        case BinXmlToken.XSD_BASE64:
        {
            byte[] array = new byte[_tokLen];
            Array.Copy(_data, _tokDataPos, array, 0, _tokLen);
            return GetValueConverter((token == BinXmlToken.XSD_BINHEX) ? XmlTypeCode.HexBinary : XmlTypeCode.Base64Binary).ChangeType(array, returnType, namespaceResolver);
        }
        case BinXmlToken.SQL_DATETIME:
        case BinXmlToken.SQL_SMALLDATETIME:
        case BinXmlToken.XSD_KATMAI_TIME:
        case BinXmlToken.XSD_KATMAI_DATETIME:
        case BinXmlToken.XSD_KATMAI_DATE:
        case BinXmlToken.XSD_DATETIME:
            return GetValueConverter(XmlTypeCode.DateTime).ChangeType(ValueAsDateTime(), returnType, namespaceResolver);
        case BinXmlToken.XSD_KATMAI_TIMEOFFSET:
        case BinXmlToken.XSD_KATMAI_DATETIMEOFFSET:
        case BinXmlToken.XSD_KATMAI_DATEOFFSET:
            return GetValueConverter(XmlTypeCode.DateTime).ChangeType(ValueAsDateTimeOffset(), returnType, namespaceResolver);
        case BinXmlToken.XSD_TIME:
            return GetValueConverter(XmlTypeCode.Time).ChangeType(ValueAsDateTime(), returnType, namespaceResolver);
        case BinXmlToken.XSD_DATE:
            return GetValueConverter(XmlTypeCode.Date).ChangeType(ValueAsDateTime(), returnType, namespaceResolver);
        case BinXmlToken.XSD_QNAME:
        {
            int num = ParseMB32(_tokDataPos);
            if (num < 0 || num >= _symbolTables.qnameCount)
            {
                throw new XmlException(System.SR.XmlBin_InvalidQNameID, string.Empty);
            }
            QName qName = _symbolTables.qnametable[num];
            return GetValueConverter(XmlTypeCode.QName).ChangeType(new XmlQualifiedName(qName.localname, qName.namespaceUri), returnType, namespaceResolver);
        }
        default:
            throw ThrowUnexpectedToken(_token);
        }
    }
References System.Xml.XmlSqlBinaryReader._data, System.Xml.XmlSqlBinaryReader._symbolTables, System.Xml.XmlSqlBinaryReader._tokDataPos, System.Xml.XmlSqlBinaryReader._token, System.Xml.XmlSqlBinaryReader._tokLen, System.array, System.Xml.Schema.XmlValueConverter.ChangeType(), System.Xml.XmlSqlBinaryReader.CheckValueTokenBounds(), System.Array.Copy(), System.Xml.XmlSqlBinaryReader.GetDouble(), System.Text.Encoding.GetEncoding(), System.Xml.XmlSqlBinaryReader.GetInt16(), System.Xml.XmlSqlBinaryReader.GetInt32(), System.Xml.XmlSqlBinaryReader.GetInt64(), System.Xml.XmlSqlBinaryReader.GetSingle(), System.Text.Encoding.GetString(), System.Xml.XmlSqlBinaryReader.GetString(), System.Xml.XmlSqlBinaryReader.GetUInt16(), System.Xml.XmlSqlBinaryReader.GetUInt32(), System.Xml.XmlSqlBinaryReader.GetUInt64(), System.Xml.XmlSqlBinaryReader.GetValueConverter(), System.Xml.XmlSqlBinaryReader.ParseMB32(), System.Xml.XmlSqlBinaryReader.SymbolTables.qnameCount, System.Xml.XmlSqlBinaryReader.SymbolTables.qnametable, System.Xml.XmlSqlBinaryReader.ThrowUnexpectedToken(), System.Xml.BinXmlSqlDecimal.ToDecimal(), System.Xml.XmlSqlBinaryReader.ValueAsDateTime(), System.Xml.XmlSqlBinaryReader.ValueAsDateTimeOffset(), System.Xml.XmlSqlBinaryReader.ValueAsString(), System.SR.XmlBin_InvalidQNameID, and System.Xml.XmlException.
Referenced by System.Xml.XmlSqlBinaryReader.ReadContentAs().