Terraria: System.Xml.XmlSqlBinaryReader.Read
Read()
override bool System.Xml.XmlSqlBinaryReader.Read () inline
Definition at line 907 of file XmlSqlBinaryReader.cs.
    {
        try
        {
            switch (_state)
            {
            case ScanState.Init:
                return ReadInit(skipXmlDecl: false);
            case ScanState.Doc:
                return ReadDoc();
            case ScanState.XmlText:
                if (_textXmlReader.Read())
                {
                    return UpdateFromTextReader(needUpdate: true);
                }
                _state = ScanState.Doc;
                _nodetype = XmlNodeType.None;
                _isEmpty = false;
                goto case ScanState.Doc;
            case ScanState.Attr:
            case ScanState.AttrVal:
            case ScanState.AttrValPseudoValue:
                MoveToElement();
                goto case ScanState.Doc;
            default:
                return false;
            }
        }
        catch (OverflowException ex)
        {
            _state = ScanState.Error;
            throw new XmlException(ex.Message, ex);
        }
        catch
        {
            _state = ScanState.Error;
            throw;
        }
    }
References System.Xml.XmlSqlBinaryReader._isEmpty, System.Xml.XmlSqlBinaryReader._nodetype, System.Xml.XmlSqlBinaryReader._state, System.Xml.XmlSqlBinaryReader._textXmlReader, System.Xml.XmlSqlBinaryReader.MoveToElement(), System.Xml.XmlReader.Read(), System.Xml.XmlSqlBinaryReader.ReadDoc(), System.Xml.XmlSqlBinaryReader.ReadInit(), System.Xml.XmlSqlBinaryReader.UpdateFromTextReader(), and System.Xml.XmlException.
Referenced by System.Xml.XmlSqlBinaryReader.FinishContentAsXXX(), and System.Xml.XmlSqlBinaryReader.SetupContentAsXXX().