Terraria: System.Xml.XmlSqlBinaryReader.ReadContentAsObject
ReadContentAsObject()
override object System.Xml.XmlSqlBinaryReader.ReadContentAsObject () inline virtual
Reimplemented from System.Xml.XmlReader.
Definition at line 1591 of file XmlSqlBinaryReader.cs.
    {
        int num = _pos;
        try
        {
            if (SetupContentAsXXX("ReadContentAsObject"))
            {
                object result;
                try
                {
                    result = ((NodeType != XmlNodeType.Element && NodeType != XmlNodeType.EndElement) ? ValueAsObject(_token, returnInternalTypes: false) : string.Empty);
                }
                catch (InvalidCastException innerException)
                {
                    throw new XmlException(System.SR.Xml_ReadContentAsFormatException, "Object", innerException, null);
                }
                catch (FormatException innerException2)
                {
                    throw new XmlException(System.SR.Xml_ReadContentAsFormatException, "Object", innerException2, null);
                }
                catch (OverflowException innerException3)
                {
                    throw new XmlException(System.SR.Xml_ReadContentAsFormatException, "Object", innerException3, null);
                }
                num = FinishContentAsXXX(num);
                return result;
            }
        }
        finally
        {
            _pos = num;
        }
        return base.ReadContentAsObject();
    }
References System.Xml.XmlSqlBinaryReader._pos, System.Xml.XmlSqlBinaryReader._token, System.Xml.Dictionary, System.Xml.XmlSqlBinaryReader.FinishContentAsXXX(), System.Xml.XmlSqlBinaryReader.NodeType, System.Xml.XmlSqlBinaryReader.SetupContentAsXXX(), System.Xml.XmlSqlBinaryReader.ValueAsObject(), System.SR.Xml_ReadContentAsFormatException, and System.Xml.XmlException.