Terraria: System.Xml.XmlSqlBinaryReader.GetAttributeText
GetAttributeText()
string System.Xml.XmlSqlBinaryReader.GetAttributeText (int i) inline private
Definition at line 2204 of file XmlSqlBinaryReader.cs.
    {
        string val = _attributes[i].val;
        if (val != null)
        {
            return val;
        }
        int pos = _pos;
        try
        {
            _pos = _attributes[i].contentPos;
            BinXmlToken binXmlToken = RescanNextToken();
            if (BinXmlToken.Attr == binXmlToken || BinXmlToken.EndAttrs == binXmlToken)
            {
                return "";
            }
            _token = binXmlToken;
            ReScanOverValue(binXmlToken);
            return ValueAsString(binXmlToken);
        }
        finally
        {
            _pos = pos;
        }
    }
References System.Xml.XmlSqlBinaryReader._attributes, System.Xml.XmlSqlBinaryReader._pos, System.Xml.XmlSqlBinaryReader._token, System.Xml.XmlSqlBinaryReader.AttrInfo.contentPos, System.Xml.Dictionary, System.Xml.XmlSqlBinaryReader.RescanNextToken(), System.Xml.XmlSqlBinaryReader.ReScanOverValue(), System.Xml.XmlSqlBinaryReader.AttrInfo.val, and System.Xml.XmlSqlBinaryReader.ValueAsString().
Referenced by System.Xml.XmlSqlBinaryReader.GetAttribute(), and System.Xml.XmlSqlBinaryReader.ScanAttributes().