Terraria: System.Xml.XmlSqlBinaryReader.ReadContentAsDateTime
ReadContentAsDateTime()
override DateTime System.Xml.XmlSqlBinaryReader.ReadContentAsDateTime () inline virtual
Reimplemented from System.Xml.XmlReader.
Definition at line 1099 of file XmlSqlBinaryReader.cs.
    {
        int num = _pos;
        try
        {
            DateTime result;
            if (SetupContentAsXXX("ReadContentAsDateTime"))
            {
                try
                {
                    switch (_token)
                    {
                    case BinXmlToken.SQL_DATETIME:
                    case BinXmlToken.SQL_SMALLDATETIME:
                    case BinXmlToken.XSD_KATMAI_TIMEOFFSET:
                    case BinXmlToken.XSD_KATMAI_DATETIMEOFFSET:
                    case BinXmlToken.XSD_KATMAI_DATEOFFSET:
                    case BinXmlToken.XSD_KATMAI_TIME:
                    case BinXmlToken.XSD_KATMAI_DATETIME:
                    case BinXmlToken.XSD_KATMAI_DATE:
                    case BinXmlToken.XSD_TIME:
                    case BinXmlToken.XSD_DATETIME:
                    case BinXmlToken.XSD_DATE:
                        result = ValueAsDateTime();
                        goto IL_016f;
                    case BinXmlToken.SQL_SMALLINT:
                    case BinXmlToken.SQL_INT:
                    case BinXmlToken.SQL_REAL:
                    case BinXmlToken.SQL_FLOAT:
                    case BinXmlToken.SQL_MONEY:
                    case BinXmlToken.SQL_BIT:
                    case BinXmlToken.SQL_TINYINT:
                    case BinXmlToken.SQL_BIGINT:
                    case BinXmlToken.SQL_UUID:
                    case BinXmlToken.SQL_DECIMAL:
                    case BinXmlToken.SQL_NUMERIC:
                    case BinXmlToken.SQL_BINARY:
                    case BinXmlToken.SQL_VARBINARY:
                    case BinXmlToken.SQL_SMALLMONEY:
                    case BinXmlToken.SQL_IMAGE:
                    case BinXmlToken.SQL_UDT:
                    case BinXmlToken.XSD_BINHEX:
                    case BinXmlToken.XSD_BASE64:
                    case BinXmlToken.XSD_BOOLEAN:
                    case BinXmlToken.XSD_DECIMAL:
                    case BinXmlToken.XSD_BYTE:
                    case BinXmlToken.XSD_UNSIGNEDSHORT:
                    case BinXmlToken.XSD_UNSIGNEDINT:
                    case BinXmlToken.XSD_UNSIGNEDLONG:
                    case BinXmlToken.XSD_QNAME:
                        throw new InvalidCastException(System.SR.Format(System.SR.XmlBinary_CastNotSupported, _token, "DateTime"));
                    case BinXmlToken.EndElem:
                    case BinXmlToken.Element:
                        return XmlConvert.ToDateTime(string.Empty, XmlDateTimeSerializationMode.RoundtripKind);
                    }
                }
                catch (InvalidCastException innerException)
                {
                    throw new XmlException(System.SR.Xml_ReadContentAsFormatException, "DateTime", innerException, null);
                }
                catch (FormatException innerException2)
                {
                    throw new XmlException(System.SR.Xml_ReadContentAsFormatException, "DateTime", innerException2, null);
                }
                catch (OverflowException innerException3)
                {
                    throw new XmlException(System.SR.Xml_ReadContentAsFormatException, "DateTime", innerException3, null);
                }
            }
            goto end_IL_0007;
            IL_016f:
            num = FinishContentAsXXX(num);
            return result;
            end_IL_0007:;
        }
        finally
        {
            _pos = num;
        }
        return base.ReadContentAsDateTime();
    }
References System.Xml.XmlSqlBinaryReader._pos, System.Xml.XmlSqlBinaryReader._token, System.Xml.Dictionary, System.Xml.XmlSqlBinaryReader.FinishContentAsXXX(), System.SR.Format(), System.Xml.XmlSqlBinaryReader.SetupContentAsXXX(), System.Xml.XmlConvert.ToDateTime(), System.Xml.XmlSqlBinaryReader.ValueAsDateTime(), System.SR.Xml_ReadContentAsFormatException, System.SR.XmlBinary_CastNotSupported, and System.Xml.XmlException.