Terraria: System.Xml.XmlSqlBinaryReader.MoveToElement
MoveToElement()
override bool System.Xml.XmlSqlBinaryReader.MoveToElement () inline
Definition at line 800 of file XmlSqlBinaryReader.cs.
    {
        switch (_state)
        {
        case ScanState.Attr:
        case ScanState.AttrVal:
        case ScanState.AttrValPseudoValue:
            _attrIndex = 0;
            _qnameOther = _qnameElement;
            if (XmlNodeType.Element == _parentNodeType)
            {
                _token = BinXmlToken.Element;
            }
            else if (XmlNodeType.XmlDeclaration == _parentNodeType)
            {
                _token = BinXmlToken.XmlDecl;
            }
            else if (XmlNodeType.DocumentType == _parentNodeType)
            {
                _token = BinXmlToken.DocType;
            }
            _nodetype = _parentNodeType;
            _state = ScanState.Doc;
            _pos = _posAfterAttrs;
            _stringValue = null;
            return true;
        case ScanState.XmlText:
            return UpdateFromTextReader(_textXmlReader.MoveToElement());
        default:
            return false;
        }
    }
References System.Xml.XmlSqlBinaryReader._attrIndex, System.Xml.XmlSqlBinaryReader._nodetype, System.Xml.XmlSqlBinaryReader._parentNodeType, System.Xml.XmlSqlBinaryReader._pos, System.Xml.XmlSqlBinaryReader._posAfterAttrs, System.Xml.XmlSqlBinaryReader._qnameElement, System.Xml.XmlSqlBinaryReader._qnameOther, System.Xml.XmlSqlBinaryReader._state, System.Xml.XmlSqlBinaryReader._stringValue, System.Xml.XmlSqlBinaryReader._textXmlReader, System.Xml.XmlSqlBinaryReader._token, System.Xml.XmlReader.MoveToElement(), and System.Xml.XmlSqlBinaryReader.UpdateFromTextReader().
Referenced by System.Xml.XmlSqlBinaryReader.Read().