Terraria: System.Xml.XmlSqlBinaryReader.CheckValueTokenBounds
CheckValueTokenBounds()
void System.Xml.XmlSqlBinaryReader.CheckValueTokenBounds () inline private
Definition at line 3356 of file XmlSqlBinaryReader.cs.
    {
        if (_end - _tokDataPos < _tokLen)
        {
            throw ThrowXmlException(System.SR.Xml_UnexpectedEOF1);
        }
    }
References System.Xml.XmlSqlBinaryReader._end, System.Xml.XmlSqlBinaryReader._tokDataPos, System.Xml.XmlSqlBinaryReader._tokLen, System.Xml.XmlSqlBinaryReader.ThrowXmlException(), and System.SR.Xml_UnexpectedEOF1.
Referenced by System.Xml.XmlSqlBinaryReader.ValueAs(), System.Xml.XmlSqlBinaryReader.ValueAsDateTime(), System.Xml.XmlSqlBinaryReader.ValueAsDateTimeOffset(), System.Xml.XmlSqlBinaryReader.ValueAsDateTimeString(), System.Xml.XmlSqlBinaryReader.ValueAsDecimal(), System.Xml.XmlSqlBinaryReader.ValueAsDouble(), System.Xml.XmlSqlBinaryReader.ValueAsLong(), System.Xml.XmlSqlBinaryReader.ValueAsObject(), System.Xml.XmlSqlBinaryReader.ValueAsString(), and System.Xml.XmlSqlBinaryReader.ValueAsULong().