Terraria: System.Xml.XmlSqlBinaryReader.GetValueType
GetValueType()
Type System.Xml.XmlSqlBinaryReader.GetValueType (BinXmlToken token) inline private
Definition at line 3124 of file XmlSqlBinaryReader.cs.
    {
        Type type = s_tokenTypeMap[(int)token];
        if (type == null)
        {
            throw ThrowUnexpectedToken(token);
        }
        return type;
    }
References System.Xml.XmlSqlBinaryReader.s_tokenTypeMap, System.Xml.XmlSqlBinaryReader.ThrowUnexpectedToken(), and System.type.
Referenced by System.Xml.XmlSqlBinaryReader.ImplReadData(), and System.Xml.XmlSqlBinaryReader.ReadAttributeValue().