Terraria: System.Xml.XmlSqlBinaryReader.GetDouble
GetDouble()
double System.Xml.XmlSqlBinaryReader.GetDouble (int offset) inline private
Definition at line 4019 of file XmlSqlBinaryReader.cs.
    {
        return BinaryPrimitives.ReadDoubleLittleEndian(_data.AsSpan(offset));
    }
References System.Xml.XmlSqlBinaryReader._data, System.offset, and System.Buffers.Binary.BinaryPrimitives.ReadDoubleLittleEndian().
Referenced by System.Xml.XmlSqlBinaryReader.ValueAs(), System.Xml.XmlSqlBinaryReader.ValueAsDecimal(), System.Xml.XmlSqlBinaryReader.ValueAsDouble(), System.Xml.XmlSqlBinaryReader.ValueAsObject(), and System.Xml.XmlSqlBinaryReader.ValueAsString().