Terraria: System.Xml.XmlSqlBinaryReader.HashCheckForDuplicateAttributes
HashCheckForDuplicateAttributes()
void System.Xml.XmlSqlBinaryReader.HashCheckForDuplicateAttributes () inline private
Definition at line 2552 of file XmlSqlBinaryReader.cs.
    {
        int num;
        for (num = 256; num < _attrCount; num = checked(num * 2))
        {
        }
        if (_attrHashTbl.Length < num)
        {
            _attrHashTbl = new int[num];
        }
        for (int i = 0; i < _attrCount; i++)
        {
            string localname;
            string namespaceUri;
            int localnameAndNamespaceUriAndHash = _attributes[i].GetLocalnameAndNamespaceUriAndHash(out localname, out namespaceUri);
            int num2 = localnameAndNamespaceUriAndHash & (num - 1);
            int num3 = _attrHashTbl[num2];
            _attrHashTbl[num2] = i + 1;
            _attributes[i].prevHash = num3;
            while (num3 != 0)
            {
                num3--;
                if (_attributes[num3].MatchHashNS(localnameAndNamespaceUriAndHash, localname, namespaceUri))
                {
                    throw new XmlException(System.SR.Xml_DupAttributeName, _attributes[i].name.ToString());
                }
                num3 = _attributes[num3].prevHash;
            }
        }
        Array.Clear(_attrHashTbl, 0, num);
    }
References System.Xml.XmlSqlBinaryReader._attrCount, System.Xml.XmlSqlBinaryReader._attrHashTbl, System.Xml.XmlSqlBinaryReader._attributes, System.Array.Clear(), System.Xml.Dictionary, System.Xml.XmlSqlBinaryReader.AttrInfo.GetLocalnameAndNamespaceUriAndHash(), System.Xml.XmlSqlBinaryReader.AttrInfo.name, System.Xml.XmlSqlBinaryReader.AttrInfo.prevHash, System.Xml.XmlSqlBinaryReader.QName.ToString(), System.SR.Xml_DupAttributeName, and System.Xml.XmlException.
Referenced by System.Xml.XmlSqlBinaryReader.ScanAttributes().