Terraria: System.Xml.XmlSqlBinaryReader.AddQName
AddQName()
void System.Xml.XmlSqlBinaryReader.AddQName () inline private
Definition at line 1750 of file XmlSqlBinaryReader.cs.
    {
        int num = ReadNameRef();
        int num2 = ReadNameRef();
        int num3 = ReadNameRef();
        int num4 = _symbolTables.qnameCount++;
        QName[] array = _symbolTables.qnametable;
        if (num4 == array.Length)
        {
            QName[] array2 = new QName[checked(num4 * 2)];
            Array.Copy(array, array2, num4);
            array = (_symbolTables.qnametable = array2);
        }
        string[] symtable = _symbolTables.symtable;
        string text = symtable[num2];
        string lname;
        string nsUri;
        if (num3 == 0)
        {
            if (num2 == 0 && num == 0)
            {
                return;
            }
            if (!text.StartsWith("xmlns", StringComparison.Ordinal))
            {
                goto IL_0104;
            }
            if (5 < text.Length)
            {
                if (6 == text.Length || ':' != text[5])
                {
                    goto IL_0104;
                }
                lname = _xnt.Add(text.Substring(6));
                text = _xmlns;
            }
            else
            {
                lname = text;
                text = string.Empty;
            }
            nsUri = _nsxmlns;
        }
        else
        {
            lname = symtable[num3];
            nsUri = symtable[num];
        }
        array[num4].Set(text, lname, nsUri);
        return;
        IL_0104:
        throw new XmlException(System.SR.Xml_BadNamespaceDecl, (string[])null);
    }
References System.Xml.XmlSqlBinaryReader._nsxmlns, System.Xml.XmlSqlBinaryReader._symbolTables, System.Xml.XmlSqlBinaryReader._xmlns, System.Xml.XmlSqlBinaryReader._xnt, System.Xml.XmlNameTable.Add(), System.array, System.Array.Copy(), System.Xml.Dictionary, System.Xml.XmlSqlBinaryReader.SymbolTables.qnameCount, System.Xml.XmlSqlBinaryReader.SymbolTables.qnametable, System.Xml.XmlSqlBinaryReader.ReadNameRef(), System.Xml.XmlSqlBinaryReader.SymbolTables.symtable, System.text, System.SR.Xml_BadNamespaceDecl, and System.Xml.XmlException.
Referenced by System.Xml.XmlSqlBinaryReader.NextToken2().