Terraria: System.Xml.XmlSqlBinaryReader.NextToken2
NextToken2()
BinXmlToken System.Xml.XmlSqlBinaryReader.NextToken2 (BinXmlToken token) inline private
Definition at line 2038 of file XmlSqlBinaryReader.cs.
    {
        while (true)
        {
            switch (token)
            {
            case BinXmlToken.Name:
                AddName();
                break;
            case BinXmlToken.QName:
                AddQName();
                break;
            case BinXmlToken.NmFlush:
                NameFlush();
                break;
            case BinXmlToken.Extn:
                SkipExtn();
                break;
            default:
                return token;
            }
            token = ReadToken();
        }
    }
References System.Xml.XmlSqlBinaryReader.AddName(), System.Xml.XmlSqlBinaryReader.AddQName(), System.Xml.XmlSqlBinaryReader.NameFlush(), System.Xml.XmlSqlBinaryReader.ReadToken(), and System.Xml.XmlSqlBinaryReader.SkipExtn().
Referenced by System.Xml.XmlSqlBinaryReader.NextToken1().