Terraria: System.Xml.XmlSqlBinaryReader.CheckText
CheckText()
XmlNodeType System.Xml.XmlSqlBinaryReader.CheckText (bool attr) inline private
Definition at line 3275 of file XmlSqlBinaryReader.cs.
    {
        ReadOnlySpan<byte> source = _data.AsSpan(_tokDataPos, _end - _tokDataPos);
        if (!attr)
        {
            while (true)
            {
                if (!BinaryPrimitives.TryReadUInt16LittleEndian(source, out var value))
                {
                    if (!_xmlspacePreserve)
                    {
                        return XmlNodeType.Whitespace;
                    }
                    return XmlNodeType.SignificantWhitespace;
                }
                if (value > 255 || !XmlCharType.IsWhiteSpace((char)value))
                {
                    break;
                }
                source = source.Slice(2);
            }
        }
        char c;
        ushort value3;
        while (true)
        {
            if (!BinaryPrimitives.TryReadUInt16LittleEndian(source, out var value2))
            {
                return XmlNodeType.Text;
            }
            source = source.Slice(2);
            c = (char)value2;
            if (!XmlCharType.IsCharData(c))
            {
                if (!XmlCharType.IsHighSurrogate(c))
                {
                    throw XmlConvert.CreateInvalidCharException(c, '\0', ExceptionType.XmlException);
                }
                if (!BinaryPrimitives.TryReadUInt16LittleEndian(source, out value3))
                {
                    throw ThrowXmlException(System.SR.Xml_InvalidSurrogateMissingLowChar);
                }
                if (!XmlCharType.IsLowSurrogate(value3))
                {
                    break;
                }
                source = source.Slice(2);
            }
        }
        throw XmlConvert.CreateInvalidSurrogatePairException(c, (char)value3);
    }
References System.Xml.XmlSqlBinaryReader._data, System.Xml.XmlSqlBinaryReader._end, System.Xml.XmlSqlBinaryReader._tokDataPos, System.Xml.XmlSqlBinaryReader._xmlspacePreserve, System.Xml.XmlConvert.CreateInvalidCharException(), System.Xml.XmlConvert.CreateInvalidSurrogatePairException(), System.Xml.Dictionary, System.Xml.XmlCharType.IsCharData(), System.Xml.XmlCharType.IsHighSurrogate(), System.Xml.XmlCharType.IsLowSurrogate(), System.Xml.XmlCharType.IsWhiteSpace(), System.source, System.Xml.XmlSqlBinaryReader.ThrowXmlException(), System.Buffers.Binary.BinaryPrimitives.TryReadUInt16LittleEndian(), System.value, and System.SR.Xml_InvalidSurrogateMissingLowChar.
Referenced by System.Xml.XmlSqlBinaryReader.ScanOverValue().