Terraria: System.Xml.XmlSqlBinaryReader.ScanAttributes
ScanAttributes()
void System.Xml.XmlSqlBinaryReader.ScanAttributes () inline private
Definition at line 2429 of file XmlSqlBinaryReader.cs.
    {
        int num = -1;
        int num2 = -1;
        _mark = _pos;
        string text = null;
        bool flag = false;
        BinXmlToken binXmlToken;
        while (BinXmlToken.EndAttrs != (binXmlToken = NextToken()))
        {
            if (BinXmlToken.Attr == binXmlToken)
            {
                if (text != null)
                {
                    PushNamespace(text, string.Empty, implied: false);
                    text = null;
                }
                if (_attrCount == _attributes.Length)
                {
                    GrowAttributes();
                }
                QName n = _symbolTables.qnametable[ReadQNameRef()];
                _attributes[_attrCount].Set(n, _pos);
                if (n.prefix == "xml")
                {
                    if (n.localname == "lang")
                    {
                        num2 = _attrCount;
                    }
                    else if (n.localname == "space")
                    {
                        num = _attrCount;
                    }
                }
                else if (Ref.Equal(n.namespaceUri, _nsxmlns))
                {
                    text = n.localname;
                    if (text == "xmlns")
                    {
                        text = string.Empty;
                    }
                }
                else if (n.prefix.Length != 0)
                {
                    if (n.namespaceUri.Length == 0)
                    {
                        throw new XmlException(System.SR.Xml_PrefixForEmptyNs, string.Empty);
                    }
                    PushNamespace(n.prefix, n.namespaceUri, implied: true);
                }
                else if (n.namespaceUri.Length != 0)
                {
                    throw ThrowXmlException(System.SR.XmlBinary_AttrWithNsNoPrefix, n.localname, n.namespaceUri);
                }
                _attrCount++;
                flag = false;
            }
            else
            {
                ScanOverValue(binXmlToken, attr: true, checkChars: true);
                if (flag)
                {
                    throw ThrowNotSupported(System.SR.XmlBinary_ListsOfValuesNotSupported);
                }
                string stringValue = _stringValue;
                if (stringValue != null)
                {
                    _attributes[_attrCount - 1].val = stringValue;
                    _stringValue = null;
                }
                if (text != null)
                {
                    string ns = _xnt.Add(ValueAsString(binXmlToken));
                    PushNamespace(text, ns, implied: false);
                    text = null;
                }
                flag = true;
            }
        }
        if (num != -1)
        {
            string attributeText = GetAttributeText(num);
            XmlSpace xmlSpace = XmlSpace.None;
            if (attributeText == "preserve")
            {
                xmlSpace = XmlSpace.Preserve;
            }
            else if (attributeText == "default")
            {
                xmlSpace = XmlSpace.Default;
            }
            _elementStack[_elemDepth].xmlSpace = xmlSpace;
            _xmlspacePreserve = XmlSpace.Preserve == xmlSpace;
        }
        if (num2 != -1)
        {
            _elementStack[_elemDepth].xmlLang = GetAttributeText(num2);
        }
        if (_attrCount < 200)
        {
            SimpleCheckForDuplicateAttributes();
        }
        else
        {
            HashCheckForDuplicateAttributes();
        }
    }
References System.Xml.XmlSqlBinaryReader._attrCount, System.Xml.XmlSqlBinaryReader._attributes, System.Xml.XmlSqlBinaryReader._elemDepth, System.Xml.XmlSqlBinaryReader._elementStack, System.Xml.XmlSqlBinaryReader._mark, System.Xml.XmlSqlBinaryReader._nsxmlns, System.Xml.XmlSqlBinaryReader._pos, System.Xml.XmlSqlBinaryReader._stringValue, System.Xml.XmlSqlBinaryReader._symbolTables, System.Xml.XmlSqlBinaryReader._xmlspacePreserve, System.Xml.XmlSqlBinaryReader._xnt, System.Xml.XmlNameTable.Add(), System.Xml.Dictionary, System.Xml.Ref.Equal(), System.Xml.XmlSqlBinaryReader.GetAttributeText(), System.Xml.XmlSqlBinaryReader.GrowAttributes(), System.Xml.XmlSqlBinaryReader.HashCheckForDuplicateAttributes(), System.Xml.XmlSqlBinaryReader.NextToken(), System.Xml.XmlSqlBinaryReader.PushNamespace(), System.Xml.XmlSqlBinaryReader.SymbolTables.qnametable, System.Xml.XmlSqlBinaryReader.ReadQNameRef(), System.Xml.XmlSqlBinaryReader.ScanOverValue(), System.Xml.XmlSqlBinaryReader.AttrInfo.Set(), System.Xml.XmlSqlBinaryReader.SimpleCheckForDuplicateAttributes(), System.text, System.Xml.XmlSqlBinaryReader.ThrowNotSupported(), System.Xml.XmlSqlBinaryReader.ThrowXmlException(), System.Xml.XmlSqlBinaryReader.AttrInfo.val, System.Xml.XmlSqlBinaryReader.ValueAsString(), System.SR.Xml_PrefixForEmptyNs, System.SR.XmlBinary_AttrWithNsNoPrefix, System.SR.XmlBinary_ListsOfValuesNotSupported, System.Xml.XmlException, System.Xml.XmlSqlBinaryReader.ElemInfo.xmlLang, and System.Xml.XmlSqlBinaryReader.ElemInfo.xmlSpace.
Referenced by System.Xml.XmlSqlBinaryReader.ImplReadElement().