Terraria: System.Xml.XmlSqlBinaryReader.ParseMB32_
ParseMB32_()
int System.Xml.XmlSqlBinaryReader.ParseMB32_ (byte b) inline private
Definition at line 1937 of file XmlSqlBinaryReader.cs.
    {
        uint num = b & 0x7Fu;
        b = ReadByte();
        uint num2 = b & 0x7Fu;
        num += num2 << 7;
        if (b > 127)
        {
            b = ReadByte();
            num2 = b & 0x7Fu;
            num += num2 << 14;
            if (b > 127)
            {
                b = ReadByte();
                num2 = b & 0x7Fu;
                num += num2 << 21;
                if (b > 127)
                {
                    b = ReadByte();
                    num2 = b & 7u;
                    if (b > 7)
                    {
                        throw ThrowXmlException(System.SR.XmlBinary_ValueTooBig);
                    }
                    num += num2 << 28;
                }
            }
        }
        return (int)num;
    }
References System.Xml.Dictionary, System.Xml.XmlSqlBinaryReader.ReadByte(), System.Xml.XmlSqlBinaryReader.ThrowXmlException(), and System.SR.XmlBinary_ValueTooBig.
Referenced by System.Xml.XmlSqlBinaryReader.ParseMB32(), and System.Xml.XmlSqlBinaryReader.ParseMB64().