Terraria: System.Xml.XmlSqlBinaryReader.PositionOnAttribute
PositionOnAttribute()
void System.Xml.XmlSqlBinaryReader.PositionOnAttribute (int i) inline private
Definition at line 2255 of file XmlSqlBinaryReader.cs.
    {
        _attrIndex = i;
        _qnameOther = _attributes[i - 1].name;
        if (_state == ScanState.Doc)
        {
            _parentNodeType = _nodetype;
        }
        _token = BinXmlToken.Attr;
        _nodetype = XmlNodeType.Attribute;
        _state = ScanState.Attr;
        _valueType = TypeOfObject;
        _stringValue = null;
    }
References System.Xml.XmlSqlBinaryReader._attributes, System.Xml.XmlSqlBinaryReader._attrIndex, System.Xml.XmlSqlBinaryReader._nodetype, System.Xml.XmlSqlBinaryReader._parentNodeType, System.Xml.XmlSqlBinaryReader._qnameOther, System.Xml.XmlSqlBinaryReader._state, System.Xml.XmlSqlBinaryReader._stringValue, System.Xml.XmlSqlBinaryReader._token, System.Xml.XmlSqlBinaryReader._valueType, System.Xml.XmlSqlBinaryReader.AttrInfo.name, and System.Xml.XmlSqlBinaryReader.TypeOfObject.
Referenced by System.Xml.XmlSqlBinaryReader.MoveToAttribute(), System.Xml.XmlSqlBinaryReader.MoveToAttribute(), System.Xml.XmlSqlBinaryReader.MoveToAttribute(), System.Xml.XmlSqlBinaryReader.MoveToFirstAttribute(), and System.Xml.XmlSqlBinaryReader.MoveToNextAttribute().