Terraria: System.Xml.XmlSqlBinaryReader.NextToken1
NextToken1()
BinXmlToken System.Xml.XmlSqlBinaryReader.NextToken1 () inline private
Definition at line 2063 of file XmlSqlBinaryReader.cs.
    {
        int pos = _pos;
        BinXmlToken binXmlToken;
        if (pos >= _end)
        {
            binXmlToken = ReadToken();
        }
        else
        {
            binXmlToken = (BinXmlToken)_data[pos];
            _pos = pos + 1;
        }
        if (binXmlToken >= BinXmlToken.NmFlush && binXmlToken <= BinXmlToken.Name)
        {
            return NextToken2(binXmlToken);
        }
        return binXmlToken;
    }
References System.Xml.XmlSqlBinaryReader._data, System.Xml.XmlSqlBinaryReader._end, System.Xml.XmlSqlBinaryReader._pos, System.Xml.Dictionary, System.Xml.XmlSqlBinaryReader.NextToken2(), and System.Xml.XmlSqlBinaryReader.ReadToken().
Referenced by System.Xml.XmlSqlBinaryReader.NextToken().