Terraria: System.Xml.XmlSqlBinaryReader.ScanText
ScanText()
int System.Xml.XmlSqlBinaryReader.ScanText (out int start) inline private
Definition at line 2165 of file XmlSqlBinaryReader.cs.
    {
        int num = ParseMB32();
        int mark = _mark;
        int pos = _pos;
        checked
        {
            _pos += num * 2;
            if (_pos > _end)
            {
                Fill(-1);
            }
        }
        start = pos - (mark - _mark);
        return num;
    }
References System.Xml.XmlSqlBinaryReader._end, System.Xml.XmlSqlBinaryReader._mark, System.Xml.XmlSqlBinaryReader._pos, System.Xml.XmlSqlBinaryReader.Fill(), System.Xml.XmlSqlBinaryReader.ParseMB32(), and System.start.
Referenced by System.Xml.XmlSqlBinaryReader.FinishCDATA(), System.Xml.XmlSqlBinaryReader.ImplReadCDATA(), System.Xml.XmlSqlBinaryReader.ImplReadComment(), System.Xml.XmlSqlBinaryReader.ImplReadDoctype(), System.Xml.XmlSqlBinaryReader.ImplReadPI(), and System.Xml.XmlSqlBinaryReader.ParseText().