Terraria: System.Xml.XmlSqlBinaryReader.ValueAsDateTimeOffset
ValueAsDateTimeOffset()
DateTimeOffset System.Xml.XmlSqlBinaryReader.ValueAsDateTimeOffset () inline private
Definition at line 3575 of file XmlSqlBinaryReader.cs.
    {
        CheckValueTokenBounds();
        return _token switch
        {
            BinXmlToken.XSD_KATMAI_DATEOFFSET => BinXmlDateTime.XsdKatmaiDateOffsetToDateTimeOffset(_data, _tokDataPos),
            BinXmlToken.XSD_KATMAI_DATETIMEOFFSET => BinXmlDateTime.XsdKatmaiDateTimeOffsetToDateTimeOffset(_data, _tokDataPos),
            BinXmlToken.XSD_KATMAI_TIMEOFFSET => BinXmlDateTime.XsdKatmaiTimeOffsetToDateTimeOffset(_data, _tokDataPos),
            _ => throw ThrowUnexpectedToken(_token),
        };
    }
References System.Xml.XmlSqlBinaryReader._data, System.Xml.XmlSqlBinaryReader._tokDataPos, System.Xml.XmlSqlBinaryReader._token, System.Xml.XmlSqlBinaryReader.CheckValueTokenBounds(), System.Xml.Dictionary, System.Xml.XmlSqlBinaryReader.ThrowUnexpectedToken(), System.Xml.BinXmlDateTime.XsdKatmaiDateOffsetToDateTimeOffset(), System.Xml.BinXmlDateTime.XsdKatmaiDateTimeOffsetToDateTimeOffset(), and System.Xml.BinXmlDateTime.XsdKatmaiTimeOffsetToDateTimeOffset().
Referenced by System.Xml.XmlSqlBinaryReader.ValueAs(), and System.Xml.XmlSqlBinaryReader.ValueAsObject().