Terraria: System.Xml.XmlSqlBinaryReader.ImplReadXmlText
ImplReadXmlText()
void System.Xml.XmlSqlBinaryReader.ImplReadXmlText () inline private
Definition at line 3025 of file XmlSqlBinaryReader.cs.
    {
        CheckAllowContent();
        string xmlFragment = ParseText();
        XmlNamespaceManager xmlNamespaceManager = new XmlNamespaceManager(_xnt);
        foreach (NamespaceDecl value in _namespaces.Values)
        {
            if (value.scope > 0)
            {
                xmlNamespaceManager.AddNamespace(value.prefix, value.uri);
            }
        }
        XmlReaderSettings settings = Settings;
        settings.ReadOnly = false;
        settings.NameTable = _xnt;
        settings.DtdProcessing = DtdProcessing.Prohibit;
        if (_elemDepth != 0)
        {
            settings.ConformanceLevel = ConformanceLevel.Fragment;
        }
        settings.ReadOnly = true;
        XmlParserContext context = new XmlParserContext(_xnt, xmlNamespaceManager, XmlLang, XmlSpace);
        _textXmlReader = new XmlTextReaderImpl(xmlFragment, context, settings);
        if (!_textXmlReader.Read() || (_textXmlReader.NodeType == XmlNodeType.XmlDeclaration && !_textXmlReader.Read()))
        {
            _state = ScanState.Doc;
            ReadDoc();
        }
        else
        {
            _state = ScanState.XmlText;
            UpdateFromTextReader();
        }
    }
References System.Xml.XmlSqlBinaryReader._elemDepth, System.Xml.XmlSqlBinaryReader._namespaces, System.Xml.XmlSqlBinaryReader._state, System.Xml.XmlSqlBinaryReader._textXmlReader, System.Xml.XmlSqlBinaryReader._xnt, System.Xml.XmlSqlBinaryReader.CheckAllowContent(), System.Xml.Dictionary, System.Xml.XmlReader.NodeType, System.Xml.XmlSqlBinaryReader.ParseText(), System.Xml.XmlReader.Read(), System.Xml.XmlSqlBinaryReader.ReadDoc(), System.Xml.XmlSqlBinaryReader.Settings, System.Xml.XmlSqlBinaryReader.UpdateFromTextReader(), System.value, System.Collections.Generic.Dictionary< TKey, TValue >.Values, and System.Xml.XmlSqlBinaryReader.XmlLang.
Referenced by System.Xml.XmlSqlBinaryReader.ReadDoc().