Terraria: System.Xml.XmlSqlBinaryReader.ReadDoc
ReadDoc()
bool System.Xml.XmlSqlBinaryReader.ReadDoc () inline private
Definition at line 2649 of file XmlSqlBinaryReader.cs.
    {
        switch (_nodetype)
        {
        case XmlNodeType.CDATA:
            FinishCDATA();
            break;
        case XmlNodeType.EndElement:
            FinishEndElement();
            break;
        case XmlNodeType.Element:
            if (_isEmpty)
            {
                FinishEndElement();
                _isEmpty = false;
            }
            break;
        }
        while (true)
        {
            _nodetype = XmlNodeType.None;
            _mark = -1;
            if (_qnameOther.localname.Length != 0)
            {
                _qnameOther.Clear();
            }
            ClearAttributes();
            _attrCount = 0;
            _valueType = TypeOfString;
            _stringValue = null;
            _hasTypedValue = false;
            _token = NextToken();
            switch (_token)
            {
            case BinXmlToken.EOF:
                if (_elemDepth > 0)
                {
                    throw new XmlException(System.SR.Xml_UnexpectedEOF1, (string[])null);
                }
                _state = ScanState.EOF;
                return false;
            case BinXmlToken.Element:
                ImplReadElement();
                break;
            case BinXmlToken.EndElem:
                ImplReadEndElement();
                break;
            case BinXmlToken.DocType:
                ImplReadDoctype();
                if (_dtdProcessing == DtdProcessing.Ignore || _prevNameInfo != null)
                {
                    continue;
                }
                break;
            case BinXmlToken.PI:
                ImplReadPI();
                if (_ignorePIs)
                {
                    continue;
                }
                break;
            case BinXmlToken.Comment:
                ImplReadComment();
                if (_ignoreComments)
                {
                    continue;
                }
                break;
            case BinXmlToken.CData:
                ImplReadCDATA();
                break;
            case BinXmlToken.Nest:
                ImplReadNest();
                _sniffed = false;
                return ReadInit(skipXmlDecl: true);
            case BinXmlToken.EndNest:
                if (_prevNameInfo != null)
                {
                    ImplReadEndNest();
                    return ReadDoc();
                }
                goto default;
            case BinXmlToken.XmlText:
                ImplReadXmlText();
                break;
            case BinXmlToken.SQL_SMALLINT:
            case BinXmlToken.SQL_INT:
            case BinXmlToken.SQL_REAL:
            case BinXmlToken.SQL_FLOAT:
            case BinXmlToken.SQL_MONEY:
            case BinXmlToken.SQL_BIT:
            case BinXmlToken.SQL_TINYINT:
            case BinXmlToken.SQL_BIGINT:
            case BinXmlToken.SQL_UUID:
            case BinXmlToken.SQL_DECIMAL:
            case BinXmlToken.SQL_NUMERIC:
            case BinXmlToken.SQL_BINARY:
            case BinXmlToken.SQL_CHAR:
            case BinXmlToken.SQL_NCHAR:
            case BinXmlToken.SQL_VARBINARY:
            case BinXmlToken.SQL_VARCHAR:
            case BinXmlToken.SQL_NVARCHAR:
            case BinXmlToken.SQL_DATETIME:
            case BinXmlToken.SQL_SMALLDATETIME:
            case BinXmlToken.SQL_SMALLMONEY:
            case BinXmlToken.SQL_TEXT:
            case BinXmlToken.SQL_IMAGE:
            case BinXmlToken.SQL_NTEXT:
            case BinXmlToken.SQL_UDT:
            case BinXmlToken.XSD_KATMAI_TIMEOFFSET:
            case BinXmlToken.XSD_KATMAI_DATETIMEOFFSET:
            case BinXmlToken.XSD_KATMAI_DATEOFFSET:
            case BinXmlToken.XSD_KATMAI_TIME:
            case BinXmlToken.XSD_KATMAI_DATETIME:
            case BinXmlToken.XSD_KATMAI_DATE:
            case BinXmlToken.XSD_TIME:
            case BinXmlToken.XSD_DATETIME:
            case BinXmlToken.XSD_DATE:
            case BinXmlToken.XSD_BINHEX:
            case BinXmlToken.XSD_BASE64:
            case BinXmlToken.XSD_BOOLEAN:
            case BinXmlToken.XSD_DECIMAL:
            case BinXmlToken.XSD_BYTE:
            case BinXmlToken.XSD_UNSIGNEDSHORT:
            case BinXmlToken.XSD_UNSIGNEDINT:
            case BinXmlToken.XSD_UNSIGNEDLONG:
            case BinXmlToken.XSD_QNAME:
                ImplReadData(_token);
                if (XmlNodeType.Text == _nodetype)
                {
                    CheckAllowContent();
                }
                else if (_ignoreWhitespace && !_xmlspacePreserve)
                {
                    continue;
                }
                return true;
            default:
                throw ThrowUnexpectedToken(_token);
            }
            break;
        }
        return true;
    }
References System.Xml.XmlSqlBinaryReader._attrCount, System.Xml.XmlSqlBinaryReader._dtdProcessing, System.Xml.XmlSqlBinaryReader._elemDepth, System.Xml.XmlSqlBinaryReader._hasTypedValue, System.Xml.XmlSqlBinaryReader._ignoreComments, System.Xml.XmlSqlBinaryReader._ignorePIs, System.Xml.XmlSqlBinaryReader._ignoreWhitespace, System.Xml.XmlSqlBinaryReader._isEmpty, System.Xml.XmlSqlBinaryReader._mark, System.Xml.XmlSqlBinaryReader._nodetype, System.Xml.XmlSqlBinaryReader._prevNameInfo, System.Xml.XmlSqlBinaryReader._qnameOther, System.Xml.XmlSqlBinaryReader._sniffed, System.Xml.XmlSqlBinaryReader._state, System.Xml.XmlSqlBinaryReader._stringValue, System.Xml.XmlSqlBinaryReader._token, System.Xml.XmlSqlBinaryReader._valueType, System.Xml.XmlSqlBinaryReader._xmlspacePreserve, System.Xml.XmlSqlBinaryReader.CheckAllowContent(), System.Xml.XmlSqlBinaryReader.QName.Clear(), System.Xml.XmlSqlBinaryReader.ClearAttributes(), System.Xml.XmlSqlBinaryReader.FinishCDATA(), System.Xml.XmlSqlBinaryReader.FinishEndElement(), System.Xml.XmlSqlBinaryReader.ImplReadCDATA(), System.Xml.XmlSqlBinaryReader.ImplReadComment(), System.Xml.XmlSqlBinaryReader.ImplReadData(), System.Xml.XmlSqlBinaryReader.ImplReadDoctype(), System.Xml.XmlSqlBinaryReader.ImplReadElement(), System.Xml.XmlSqlBinaryReader.ImplReadEndElement(), System.Xml.XmlSqlBinaryReader.ImplReadEndNest(), System.Xml.XmlSqlBinaryReader.ImplReadNest(), System.Xml.XmlSqlBinaryReader.ImplReadPI(), System.Xml.XmlSqlBinaryReader.ImplReadXmlText(), System.Xml.XmlSqlBinaryReader.QName.localname, System.Xml.XmlSqlBinaryReader.NextToken(), System.Xml.XmlSqlBinaryReader.ReadDoc(), System.Xml.XmlSqlBinaryReader.ReadInit(), System.Xml.XmlSqlBinaryReader.ThrowUnexpectedToken(), System.Xml.XmlSqlBinaryReader.TypeOfString, System.SR.Xml_UnexpectedEOF1, and System.Xml.XmlException.
Referenced by System.Xml.XmlSqlBinaryReader.ImplReadXmlText(), System.Xml.XmlSqlBinaryReader.Read(), System.Xml.XmlSqlBinaryReader.ReadDoc(), and System.Xml.XmlSqlBinaryReader.ReadInit().