Terraria: System.Xml.XmlSqlBinaryReader.FillAllowEOF
FillAllowEOF()
bool System.Xml.XmlSqlBinaryReader.FillAllowEOF () inline private
Definition at line 1841 of file XmlSqlBinaryReader.cs.
    {
        if (_eof)
        {
            return false;
        }
        byte[] array = _data;
        int pos = _pos;
        int num = _mark;
        int end = _end;
        if (num == -1)
        {
            num = pos;
        }
        if (num >= 0 && num < end)
        {
            int num2 = end - num;
            if (num2 > 7 * (array.Length / 8))
            {
                byte[] array2 = new byte[checked(array.Length * 2)];
                Array.Copy(array, num, array2, 0, num2);
                array = (_data = array2);
            }
            else
            {
                Array.Copy(array, num, array, 0, num2);
            }
            pos -= num;
            end -= num;
            _tokDataPos -= num;
            for (int i = 0; i < _attrCount; i++)
            {
                _attributes[i].AdjustPosition(-num);
            }
            _pos = pos;
            _mark = 0;
        }
        else
        {
            _pos -= end;
            _mark -= end;
            _tokDataPos -= end;
            end = 0;
        }
        int count = array.Length - end;
        int num3 = _inStrm.Read(array, end, count);
        _end = end + num3;
        _eof = num3 <= 0;
        return num3 > 0;
    }
References System.Xml.XmlSqlBinaryReader._attrCount, System.Xml.XmlSqlBinaryReader._attributes, System.Xml.XmlSqlBinaryReader._data, System.Xml.XmlSqlBinaryReader._end, System.Xml.XmlSqlBinaryReader._eof, System.Xml.XmlSqlBinaryReader._inStrm, System.Xml.XmlSqlBinaryReader._mark, System.Xml.XmlSqlBinaryReader._pos, System.Xml.XmlSqlBinaryReader._tokDataPos, System.Xml.XmlSqlBinaryReader.AttrInfo.AdjustPosition(), System.array, System.Array.Copy(), System.count, System.Xml.Dictionary, and System.IO.Stream.Read().
Referenced by System.Xml.XmlSqlBinaryReader.Fill_(), System.Xml.XmlSqlBinaryReader.PeekToken(), and System.Xml.XmlSqlBinaryReader.ReadToken().