Terraria: System.Xml.XmlSqlBinaryReader.Fill_
Fill_()
void System.Xml.XmlSqlBinaryReader.Fill_ (int require) inline private
Definition at line 1892 of file XmlSqlBinaryReader.cs.
    {
        while (FillAllowEOF() && _pos + require >= _end)
        {
        }
        if (_pos + require >= _end)
        {
            throw ThrowXmlException(System.SR.Xml_UnexpectedEOF1);
        }
    }
References System.Xml.XmlSqlBinaryReader._end, System.Xml.XmlSqlBinaryReader._pos, System.Xml.XmlSqlBinaryReader.FillAllowEOF(), System.Xml.XmlSqlBinaryReader.ThrowXmlException(), and System.SR.Xml_UnexpectedEOF1.
Referenced by System.Xml.XmlSqlBinaryReader.Fill().