Terraria: System.Xml.XmlSqlBinaryReader.ImplReadElement
ImplReadElement()
void System.Xml.XmlSqlBinaryReader.ImplReadElement () inline private
Definition at line 2862 of file XmlSqlBinaryReader.cs.
    {
        if (3 != _docState || 9 != _docState)
        {
            switch (_docState)
            {
            case 0:
                _docState = 9;
                break;
            case 1:
            case 2:
                _docState = 3;
                break;
            case -1:
                throw ThrowUnexpectedToken(_token);
            }
        }
        _elemDepth++;
        if (_elemDepth == _elementStack.Length)
        {
            GrowElements();
        }
        QName qName = _symbolTables.qnametable[ReadQNameRef()];
        _qnameOther = (_qnameElement = qName);
        _elementStack[_elemDepth].Set(qName, _xmlspacePreserve);
        PushNamespace(qName.prefix, qName.namespaceUri, implied: true);
        BinXmlToken binXmlToken = PeekNextToken();
        if (BinXmlToken.Attr == binXmlToken)
        {
            ScanAttributes();
            binXmlToken = PeekNextToken();
        }
        GenerateImpliedXmlnsAttrs();
        if (BinXmlToken.EndElem == binXmlToken)
        {
            NextToken();
            _isEmpty = true;
        }
        else if (BinXmlToken.SQL_NVARCHAR == binXmlToken)
        {
            if (_mark < 0)
            {
                _mark = _pos;
            }
            _pos++;
            if (ReadByte() == 0)
            {
                if (247 != ReadByte())
                {
                    _pos -= 3;
                }
                else
                {
                    _pos--;
                }
            }
            else
            {
                _pos -= 2;
            }
        }
        _nodetype = XmlNodeType.Element;
        _valueType = TypeOfObject;
        _posAfterAttrs = _pos;
    }
References System.Xml.XmlSqlBinaryReader._docState, System.Xml.XmlSqlBinaryReader._elemDepth, System.Xml.XmlSqlBinaryReader._elementStack, System.Xml.XmlSqlBinaryReader._isEmpty, System.Xml.XmlSqlBinaryReader._mark, System.Xml.XmlSqlBinaryReader._nodetype, System.Xml.XmlSqlBinaryReader._pos, System.Xml.XmlSqlBinaryReader._posAfterAttrs, System.Xml.XmlSqlBinaryReader._qnameElement, System.Xml.XmlSqlBinaryReader._qnameOther, System.Xml.XmlSqlBinaryReader._symbolTables, System.Xml.XmlSqlBinaryReader._token, System.Xml.XmlSqlBinaryReader._valueType, System.Xml.XmlSqlBinaryReader._xmlspacePreserve, System.Xml.Dictionary, System.Xml.XmlSqlBinaryReader.GenerateImpliedXmlnsAttrs(), System.Xml.XmlSqlBinaryReader.GrowElements(), System.Xml.XmlSqlBinaryReader.NextToken(), System.Xml.XmlSqlBinaryReader.PeekNextToken(), System.Xml.XmlSqlBinaryReader.PushNamespace(), System.Xml.XmlSqlBinaryReader.SymbolTables.qnametable, System.Xml.XmlSqlBinaryReader.ReadByte(), System.Xml.XmlSqlBinaryReader.ReadQNameRef(), System.Xml.XmlSqlBinaryReader.ScanAttributes(), System.Xml.XmlSqlBinaryReader.ElemInfo.Set(), System.Xml.XmlSqlBinaryReader.ThrowUnexpectedToken(), and System.Xml.XmlSqlBinaryReader.TypeOfObject.
Referenced by System.Xml.XmlSqlBinaryReader.ReadDoc().