Terraria: System.Xml.XmlSqlBinaryReader.GenerateImpliedXmlnsAttrs
GenerateImpliedXmlnsAttrs()
void System.Xml.XmlSqlBinaryReader.GenerateImpliedXmlnsAttrs () inline private
Definition at line 2349 of file XmlSqlBinaryReader.cs.
    {
        for (NamespaceDecl namespaceDecl = _elementStack[_elemDepth].nsdecls; namespaceDecl != null; namespaceDecl = namespaceDecl.scopeLink)
        {
            if (namespaceDecl.implied)
            {
                if (_attrCount == _attributes.Length)
                {
                    GrowAttributes();
                }
                QName n = ((namespaceDecl.prefix.Length != 0) ? new QName(_xmlns, _xnt.Add(namespaceDecl.prefix), _nsxmlns) : new QName(string.Empty, _xmlns, _nsxmlns));
                _attributes[_attrCount].Set(n, namespaceDecl.uri);
                _attrCount++;
            }
        }
    }
References System.Xml.XmlSqlBinaryReader._attrCount, System.Xml.XmlSqlBinaryReader._attributes, System.Xml.XmlSqlBinaryReader._elemDepth, System.Xml.XmlSqlBinaryReader._elementStack, System.Xml.XmlSqlBinaryReader._nsxmlns, System.Xml.XmlSqlBinaryReader._xmlns, System.Xml.XmlSqlBinaryReader._xnt, System.Xml.XmlNameTable.Add(), System.Xml.Dictionary, System.Xml.XmlSqlBinaryReader.GrowAttributes(), System.Xml.QName, and System.Xml.XmlSqlBinaryReader.AttrInfo.Set().
Referenced by System.Xml.XmlSqlBinaryReader.ImplReadElement().