Terraria: System.EventArgs.Empty
Empty
readonly EventArgs System.EventArgs.Empty = new EventArgs() static inherited
Definition at line 9 of file EventArgs.cs.
Referenced by Microsoft.Xna.Framework.Graphics.GuideRenderer.GuideRenderer(), Microsoft.Xna.Framework.Graphics.GraphicsDevice._007EGraphicsDevice(), Microsoft.Xna.Framework.Graphics.GraphicsResource._007EGraphicsResource(), Microsoft.Xna.Framework.Graphics.GuideRenderer._007EGuideRenderer(), System.Net.NetworkInformation.NetworkChange.AddressChangeListener.AddressChangedCallback(), System.ComponentModel.Component.Dispose(), System.ComponentModel.MarshalByValueComponent.Dispose(), System.IO.Compression.ZipArchiveEntry.GetDataCompressor(), System.ComponentModel.Design.MenuCommand.Invoke(), MS.Internal.Xml.Linq.ComponentModel.XAttributeValuePropertyDescriptor.OnChanged(), MS.Internal.Xml.Linq.ComponentModel.XElementAttributePropertyDescriptor.OnChanged(), MS.Internal.Xml.Linq.ComponentModel.XElementDescendantsPropertyDescriptor.OnChanged(), MS.Internal.Xml.Linq.ComponentModel.XElementElementPropertyDescriptor.OnChanged(), MS.Internal.Xml.Linq.ComponentModel.XElementElementsPropertyDescriptor.OnChanged(), MS.Internal.Xml.Linq.ComponentModel.XElementValuePropertyDescriptor.OnChanged(), MS.Internal.Xml.Linq.ComponentModel.XElementXmlPropertyDescriptor.OnChanged(), System.Diagnostics.Process.OnExited(), System.Data.DataSet.OnInitialized(), System.Data.DataTable.OnInitialized(), System.Data.DataView.OnInitialized(), System.AppContext.OnProcessExit(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.Present(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.Reset(), System.Net.NetworkInformation.NetworkChange.RunAddressChangedHandler(), Microsoft.Xna.Framework.Graphics.DynamicIndexBuffer.SetContentLost(), Microsoft.Xna.Framework.Graphics.DynamicVertexBuffer.SetContentLost(), Microsoft.Xna.Framework.Graphics.RenderTarget2D.SetContentLost(), Microsoft.Xna.Framework.Graphics.RenderTargetCube.SetContentLost(), System.ComponentModel.Design.MenuCommand.SetStatus(), System.ComponentModel.ReflectPropertyDescriptor.SetValue(), System.Data.DataColumnPropertyDescriptor.SetValue(), System.ComponentModel.ArrayConverter.ArrayPropertyDescriptor.SetValue(), and Microsoft.Xna.Framework.FrameworkDispatcher.Update().