namespace System.Net.Quic.Implementations.MsQuic.Internal;

internal enum QUIC_EXECUTION_PROFILE : uint
{
	QUIC_EXECUTION_PROFILE_LOW_LATENCY,
	QUIC_EXECUTION_PROFILE_TYPE_MAX_THROUGHPUT,
	QUIC_EXECUTION_PROFILE_TYPE_SCAVENGER,
	QUIC_EXECUTION_PROFILE_TYPE_REAL_TIME
}
