namespace System.Net.Quic.Implementations.MsQuic.Internal;

[Flags]
internal enum QUIC_CREDENTIAL_FLAGS : uint
{
	NONE = 0u,
	CLIENT = 1u,
	LOAD_ASYNCHRONOUS = 2u,
	NO_CERTIFICATE_VALIDATION = 4u,
	ENABLE_OCSP = 8u,
	INDICATE_CERTIFICATE_RECEIVED = 0x10u,
	DEFER_CERTIFICATE_VALIDATION = 0x20u,
	REQUIRE_CLIENT_AUTHENTICATION = 0x40u,
	USE_TLS_BUILTIN_CERTIFICATE_VALIDATION = 0x80u,
	USE_PORTABLE_CERTIFICATES = 0x4000u
}
