namespace System.Net.Quic.Implementations.MsQuic.Internal;

internal enum QUIC_CONNECTION_EVENT_TYPE : uint
{
	CONNECTED,
	SHUTDOWN_INITIATED_BY_TRANSPORT,
	SHUTDOWN_INITIATED_BY_PEER,
	SHUTDOWN_COMPLETE,
	LOCAL_ADDRESS_CHANGED,
	PEER_ADDRESS_CHANGED,
	PEER_STREAM_STARTED,
	STREAMS_AVAILABLE,
	PEER_NEEDS_STREAMS,
	IDEAL_PROCESSOR_CHANGED,
	DATAGRAM_STATE_CHANGED,
	DATAGRAM_RECEIVED,
	DATAGRAM_SEND_STATE_CHANGED,
	RESUMED,
	RESUMPTION_TICKET_RECEIVED,
	PEER_CERTIFICATE_RECEIVED
}
