namespace System.Net.Quic.Implementations.MsQuic.Internal;

internal enum QUIC_STREAM_EVENT_TYPE : uint
{
	START_COMPLETE,
	RECEIVE,
	SEND_COMPLETE,
	PEER_SEND_SHUTDOWN,
	PEER_SEND_ABORTED,
	PEER_RECEIVE_ABORTED,
	SEND_SHUTDOWN_COMPLETE,
	SHUTDOWN_COMPLETE,
	IDEAL_SEND_BUFFER_SIZE
}
