Terraria: System.Net.Mail.SmtpReplyReaderFactory.Read
Read()
int System.Net.Mail.SmtpReplyReaderFactory.Read (SmtpReplyReader caller, byte[] buffer, int offset, int count) inline package
Definition at line 367 of file SmtpReplyReaderFactory.cs.
    {
        if (count == 0 || _currentReader != caller || _readState == ReadState.Done)
        {
            return 0;
        }
        int num = _bufferedStream.Read(buffer, offset, count);
        int num2 = ProcessRead(buffer, offset, num, readLine: false);
        if (num2 < num)
        {
            _bufferedStream.Push(buffer, offset + num2, num - num2);
        }
        return num2;
    }
References System.Net.Mail.SmtpReplyReaderFactory._bufferedStream, System.Net.Mail.SmtpReplyReaderFactory._currentReader, System.Net.Mail.SmtpReplyReaderFactory._readState, System.buffer, System.count, System.offset, System.Net.Mail.SmtpReplyReaderFactory.ProcessRead(), System.Net.BufferedReadStream.Push(), and System.Net.BufferedReadStream.Read().