Terraria: System.Net.Mail.SmtpReplyReaderFactory.ReadLines
ReadLines() [2/2]
LineInfo[] System.Net.Mail.SmtpReplyReaderFactory.ReadLines (SmtpReplyReader caller, bool oneLine) inline package
Definition at line 397 of file SmtpReplyReaderFactory.cs.
    {
        if (caller != _currentReader || _readState == ReadState.Done)
        {
            return Array.Empty<LineInfo>();
        }
        if (_byteBuffer == null)
        {
            _byteBuffer = new byte[256];
        }
        StringBuilder stringBuilder = new StringBuilder();
        List<LineInfo> list = new List<LineInfo>();
        int num = 0;
        int num2 = 0;
        int num3 = 0;
        while (true)
        {
            if (num2 == num3)
            {
                num3 = _bufferedStream.Read(_byteBuffer, 0, _byteBuffer.Length);
                num2 = 0;
            }
            int num4 = ProcessRead(_byteBuffer, num2, num3 - num2, readLine: true);
            if (num < 4)
            {
                int num5 = Math.Min(4 - num, num4);
                num += num5;
                num2 += num5;
                num4 -= num5;
                if (num4 == 0)
                {
                    continue;
                }
            }
            stringBuilder.Append(Encoding.UTF8.GetString(_byteBuffer, num2, num4));
            num2 += num4;
            if (_readState == ReadState.Status0)
            {
                num = 0;
                list.Add(new LineInfo(_statusCode, stringBuilder.ToString(0, stringBuilder.Length - 2)));
                if (oneLine)
                {
                    _bufferedStream.Push(_byteBuffer, num2, num3 - num2);
                    return list.ToArray();
                }
                stringBuilder = new StringBuilder();
            }
            else if (_readState == ReadState.Done)
            {
                break;
            }
        }
        list.Add(new LineInfo(_statusCode, stringBuilder.ToString(0, stringBuilder.Length - 2)));
        _bufferedStream.Push(_byteBuffer, num2, num3 - num2);
        return list.ToArray();
    }
References System.Net.Mail.SmtpReplyReaderFactory._bufferedStream, System.Net.Mail.SmtpReplyReaderFactory._byteBuffer, System.Net.Mail.SmtpReplyReaderFactory._currentReader, System.Net.Mail.SmtpReplyReaderFactory._readState, System.Net.Mail.SmtpReplyReaderFactory._statusCode, System.list, System.Math.Min(), System.Net.Mail.SmtpReplyReaderFactory.ProcessRead(), System.Net.BufferedReadStream.Push(), System.Net.BufferedReadStream.Read(), and System.Text.Encoding.UTF8.