Terraria: System.Net.Mail.SmtpReplyReaderFactory.GetNextReplyReader
GetNextReplyReader()
SmtpReplyReader System.Net.Mail.SmtpReplyReaderFactory.GetNextReplyReader () inline package
Definition at line 228 of file SmtpReplyReaderFactory.cs.
    {
        if (_currentReader != null)
        {
            _currentReader.Close();
        }
        _readState = ReadState.Status0;
        _currentReader = new SmtpReplyReader(this);
        return _currentReader;
    }
References System.Net.Mail.SmtpReplyReaderFactory._currentReader, System.Net.Mail.SmtpReplyReaderFactory._readState, and System.Net.Mail.SmtpReplyReader.Close().
Referenced by System.Net.Mail.CheckCommand.BeginSend(), System.Net.Mail.ReadLinesCommand.BeginSend(), System.Net.Mail.SmtpConnection.GetConnection(), System.Net.Mail.SmtpConnection.ConnectAndHandshakeAsyncResult.Handshake(), System.Net.Mail.ReadLinesCommand.Send(), and System.Net.Mail.CheckCommand.Send().