Terraria: System.Net.Mail.SmtpReplyReaderFactory.ProcessRead
ProcessRead()
unsafe int System.Net.Mail.SmtpReplyReaderFactory.ProcessRead (byte[] buffer, int offset, int read, bool readLine) inline private
Definition at line 239 of file SmtpReplyReaderFactory.cs.
    {
        if (read == 0)
        {
            throw new IOException(System.SR.Format(System.SR.net_io_readfailure, System.SR.net_io_connectionclosed));
        }
        fixed (byte* ptr = buffer)
        {
            byte* ptr2 = ptr + offset;
            byte* ptr3 = ptr2;
            byte* ptr4 = ptr3 + read;
            switch (_readState)
            {
            case ReadState.Status0:
                if (ptr3 < ptr4)
                {
                    byte b = *(ptr3++);
                    if (b < 48 && b > 57)
                    {
                        throw new FormatException(System.SR.SmtpInvalidResponse);
                    }
                    _statusCode = (SmtpStatusCode)(100 * (b - 48));
                    goto case ReadState.Status1;
                }
                _readState = ReadState.Status0;
                break;
            case ReadState.Status1:
                if (ptr3 < ptr4)
                {
                    byte b3 = *(ptr3++);
                    if (b3 < 48 && b3 > 57)
                    {
                        throw new FormatException(System.SR.SmtpInvalidResponse);
                    }
                    _statusCode += 10 * (b3 - 48);
                    goto case ReadState.Status2;
                }
                _readState = ReadState.Status1;
                break;
            case ReadState.Status2:
                if (ptr3 < ptr4)
                {
                    byte b2 = *(ptr3++);
                    if (b2 < 48 && b2 > 57)
                    {
                        throw new FormatException(System.SR.SmtpInvalidResponse);
                    }
                    _statusCode += b2 - 48;
                    goto case ReadState.ContinueFlag;
                }
                _readState = ReadState.Status2;
                break;
            case ReadState.ContinueFlag:
                if (ptr3 < ptr4)
                {
                    byte b4 = *(ptr3++);
                    if (b4 != 32)
                    {
                        if (b4 != 45)
{
                            throw new FormatException(System.SR.SmtpInvalidResponse);
                        }
                        goto case ReadState.ContinueCR;
                    }
                    goto case ReadState.LastCR;
                }
                _readState = ReadState.ContinueFlag;
                break;
            case ReadState.ContinueCR:
                while (ptr3 < ptr4)
                {
                    if (*(ptr3++) != 13)
                    {
                        continue;
                    }
                    goto case ReadState.ContinueLF;
                }
                _readState = ReadState.ContinueCR;
                break;
            case ReadState.ContinueLF:
                if (ptr3 < ptr4)
                {
                    if (*(ptr3++) != 10)
                    {
                        throw new FormatException(System.SR.SmtpInvalidResponse);
                    }
                    if (readLine)
                    {
                        _readState = ReadState.Status0;
                        return (int)(ptr3 - ptr2);
                    }
                    goto case ReadState.Status0;
                }
                _readState = ReadState.ContinueLF;
                break;
            case ReadState.LastCR:
                while (ptr3 < ptr4)
                {
                    if (*(ptr3++) != 13)
                    {
                        continue;
                    }
                    goto case ReadState.LastLF;
                }
                _readState = ReadState.LastCR;
                break;
            case ReadState.LastLF:
                if (ptr3 < ptr4)
                {
                    if (*(ptr3++) != 10)
                    {
                        throw new FormatException(System.SR.SmtpInvalidResponse);
                    }
                    goto case ReadState.Done;
                }
                _readState = ReadState.LastLF;
                break;
            case ReadState.Done:
            {
                int result = (int)(ptr3 - ptr2);
                _readState = ReadState.Done;
                return result;
            }
            }
            return (int)(ptr3 - ptr2);
        }
    }
References System.Net.Mail.SmtpReplyReaderFactory._readState, System.Net.Mail.SmtpReplyReaderFactory._statusCode, System.buffer, System.SR.Format(), System.SR.net_io_connectionclosed, System.SR.net_io_readfailure, System.offset, and System.SR.SmtpInvalidResponse.
Referenced by System.Net.Mail.SmtpReplyReaderFactory.ReadLinesAsyncResult.ProcessRead(), System.Net.Mail.SmtpReplyReaderFactory.Read(), and System.Net.Mail.SmtpReplyReaderFactory.ReadLines().