Terraria: System.Resources.ResourceWriter.AddResourceInternal
AddResourceInternal()
void System.Resources.ResourceWriter.AddResourceInternal (string name, Stream value, bool closeAfterWrite) inline private
Definition at line 157 of file ResourceWriter.cs.
    {
        if (value == null)
        {
            _caseInsensitiveDups.Add(name, null);
            _resourceList.Add(name, value);
            return;
        }
        if (!value.CanSeek)
        {
            throw new ArgumentException(System.SR.NotSupported_UnseekableStream);
        }
        _caseInsensitiveDups.Add(name, null);
        _resourceList.Add(name, new StreamWrapper(value, closeAfterWrite));
    }
References System.Resources.ResourceWriter._caseInsensitiveDups, System.Resources.ResourceWriter._resourceList, System.Collections.Generic.SortedDictionary< TKey, TValue >.Add(), System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.SR.NotSupported_UnseekableStream, and System.value.
Referenced by System.Resources.ResourceWriter.AddResource(), System.Resources.ResourceWriter.AddResource(), and System.Resources.ResourceWriter.AddResource().