Terraria: System.Resources.ResourceWriter.FindTypeCode
FindTypeCode()
System.Resources.ResourceTypeCode System.Resources.ResourceWriter.FindTypeCode (object value, List< string > types) inline private
Definition at line 332 of file ResourceWriter.cs.
    {
        if (value == null)
        {
            return System.Resources.ResourceTypeCode.Null;
        }
        Type type = value.GetType();
        if (type == typeof(string))
        {
            return System.Resources.ResourceTypeCode.String;
        }
        if (type == typeof(int))
        {
            return System.Resources.ResourceTypeCode.Int32;
        }
        if (type == typeof(bool))
        {
            return System.Resources.ResourceTypeCode.Boolean;
        }
        if (type == typeof(char))
        {
            return System.Resources.ResourceTypeCode.Char;
        }
        if (type == typeof(byte))
        {
            return System.Resources.ResourceTypeCode.Byte;
        }
        if (type == typeof(sbyte))
        {
            return System.Resources.ResourceTypeCode.SByte;
        }
        if (type == typeof(short))
        {
            return System.Resources.ResourceTypeCode.Int16;
        }
        if (type == typeof(long))
        {
            return System.Resources.ResourceTypeCode.Int64;
        }
        if (type == typeof(ushort))
        {
            return System.Resources.ResourceTypeCode.UInt16;
        }
        if (type == typeof(uint))
        {
            return System.Resources.ResourceTypeCode.UInt32;
        }
        if (type == typeof(ulong))
        {
            return System.Resources.ResourceTypeCode.UInt64;
        }
        if (type == typeof(float))
        {
            return System.Resources.ResourceTypeCode.Single;
        }
        if (type == typeof(double))
        {
            return System.Resources.ResourceTypeCode.Double;
        }
        if (type == typeof(decimal))
        {
            return System.Resources.ResourceTypeCode.Decimal;
        }
        if (type == typeof(DateTime))
        {
            return System.Resources.ResourceTypeCode.DateTime;
        }
        if (type == typeof(TimeSpan))
        {
            return System.Resources.ResourceTypeCode.TimeSpan;
        }
        if (type == typeof(byte[]))
        {
            return System.Resources.ResourceTypeCode.ByteArray;
        }
        if (type == typeof(StreamWrapper))
        {
            return System.Resources.ResourceTypeCode.Stream;
        }
        if (type == typeof(PrecannedResource))
        {
            string typeName = ((PrecannedResource)value).TypeName;
            if (typeName.StartsWith("ResourceTypeCode.", StringComparison.Ordinal))
            {
                typeName = typeName.Substring(17);
                return (System.Resources.ResourceTypeCode)Enum.Parse(typeof(System.Resources.ResourceTypeCode), typeName);
            }
            int num = types.IndexOf(typeName);
            if (num == -1)
            {
                num = types.Count;
                types.Add(typeName);
            }
            return (System.Resources.ResourceTypeCode)(num + 64);
        }
        throw new PlatformNotSupportedException(System.SR.NotSupported_BinarySerializedResources);
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Type.GetType(), System.SR.NotSupported_BinarySerializedResources, System.Enum.Parse(), System.type, and System.value.
Referenced by System.Resources.ResourceWriter.Generate().