Terraria: System.Diagnostics.CorrelationManager.StartLogicalOperation
StartLogicalOperation() [1/2]
void System.Diagnostics.CorrelationManager.StartLogicalOperation () inline
Definition at line 151 of file CorrelationManager.cs.
    {
        StartLogicalOperation(Guid.NewGuid());
    }
References System.Guid.NewGuid(), and System.Diagnostics.CorrelationManager.StartLogicalOperation().
Referenced by System.Diagnostics.CorrelationManager.StartLogicalOperation().