Terraria: System.Net.Http.Headers.HeaderDescriptor.GetHeaderValue
GetHeaderValue()
string System.Net.Http.Headers.HeaderDescriptor.GetHeaderValue (ReadOnlySpan< byte > headerValue, Encoding valueEncoding) inline
Definition at line 115 of file HeaderDescriptor.cs.
    {
        if (headerValue.Length == 0)
        {
            return string.Empty;
        }
        if (_knownHeader != null)
        {
            string[] knownValues = _knownHeader.KnownValues;
            if (knownValues != null)
            {
                for (int i = 0; i < knownValues.Length; i++)
                {
                    if (ByteArrayHelpers.EqualsOrdinalAsciiIgnoreCase(knownValues[i], headerValue))
                    {
                        return knownValues[i];
                    }
                }
            }
            string decoded;
            if (_knownHeader == KnownHeaders.ContentType)
            {
                string knownContentType = GetKnownContentType(headerValue);
                if (knownContentType != null)
                {
                    return knownContentType;
                }
            }
            else if (_knownHeader == KnownHeaders.Location && TryDecodeUtf8(headerValue, out decoded))
            {
                return decoded;
            }
        }
        return (valueEncoding ?? HttpRuleParser.DefaultHttpEncoding).GetString(headerValue);
    }
References System.Net.Http.Headers.HeaderDescriptor._knownHeader, System.Net.Http.Headers.KnownHeaders.ContentType, System.Net.Http.HttpRuleParser.DefaultHttpEncoding, System.ByteArrayHelpers.EqualsOrdinalAsciiIgnoreCase(), System.Net.Http.Headers.HeaderDescriptor.GetKnownContentType(), System.Net.Http.Headers.KnownHeader.KnownValues, System.ReadOnlySpan< T >.Length, System.Net.Http.Headers.KnownHeaders.Location, and System.Net.Http.Headers.HeaderDescriptor.TryDecodeUtf8().
Referenced by System.Net.Http.HttpConnectionBase.GetResponseHeaderValueWithCaching(), and System.Net.Http.Http2Connection.Http2Stream.OnHeader().