Terraria: System.Net.Http.Headers.HeaderDescriptor.TryGet
TryGet() [2/2]
static bool System.Net.Http.Headers.HeaderDescriptor.TryGet (string headerName, out HeaderDescriptor descriptor) inline static
Definition at line 63 of file HeaderDescriptor.cs.
    {
        KnownHeader knownHeader = KnownHeaders.TryGetKnownHeader(headerName);
        if (knownHeader != null)
        {
            descriptor = new HeaderDescriptor(knownHeader);
            return true;
        }
        if (!HttpRuleParser.IsToken(headerName))
        {
            descriptor = default(HeaderDescriptor);
            return false;
        }
        descriptor = new HeaderDescriptor(headerName);
        return true;
    }
References System.Net.Http.Headers.HeaderDescriptor.HeaderDescriptor(), System.Net.Http.HttpRuleParser.IsToken(), and System.Net.Http.Headers.KnownHeaders.TryGetKnownHeader().
Referenced by System.Net.Http.DiagnosticsHandler.DiagnosticsHandler(), System.Net.Http.Headers.HttpHeadersNonValidated.Contains(), System.Net.Http.Headers.HttpHeaders.GetHeaderDescriptor(), System.Net.Http.DiagnosticsHandler.InjectHeaders(), System.Net.Http.Http2Connection.Http2Stream.OnHeader(), System.Net.Http.Http3RequestStream.OnHeader(), System.Net.Http.HttpConnection.ParseHeaderNameValue(), System.Net.Http.Headers.HttpHeaders.TryGetHeaderDescriptor(), and System.Net.Http.Headers.HttpHeadersNonValidated.TryGetValues().