Terraria: System.Net.Http.Headers.HeaderDescriptor.HeaderDescriptor
HeaderDescriptor() [1/2]
System.Net.Http.Headers.HeaderDescriptor.HeaderDescriptor (KnownHeader knownHeader) inline
Definition at line 32 of file HeaderDescriptor.cs.
    {
        _knownHeader = knownHeader;
        _headerName = knownHeader.Name;
    }
References System.Net.Http.Headers.HeaderDescriptor._headerName, System.Net.Http.Headers.HeaderDescriptor._knownHeader, and System.Net.Http.Headers.KnownHeader.Name.
Referenced by System.Net.Http.Headers.HeaderDescriptor.AsCustomHeader(), System.Net.Http.Headers.HeaderDescriptor.TryGet(), System.Net.Http.Headers.HeaderDescriptor.TryGet(), and System.Net.Http.Headers.HeaderDescriptor.TryGetStaticQPackHeader().