Terraria: System.ArgumentNullException.ThrowIfNull
ThrowIfNull()
static void System.ArgumentNullException.ThrowIfNull ([NotNull] object? argument, [CallerArgumentExpression("argument")] string? paramName = null) inline static
Definition at line 40 of file ArgumentNullException.cs.
    {
        if (argument == null)
        {
            Throw(paramName);
        }
    }
References System.Runtime.Serialization.Dictionary, and System.ArgumentNullException.Throw().
Referenced by System.Net.WebClient.DownloadData(), System.Net.WebClient.DownloadDataAsync(), System.Net.WebClient.DownloadFile(), System.Net.WebClient.DownloadFileAsync(), System.Net.WebClient.DownloadString(), System.Net.WebClient.DownloadStringAsync(), System.Reflection.PropertyInfoExtensions.GetAccessors(), System.Reflection.PropertyInfoExtensions.GetAccessors(), System.Reflection.EventInfoExtensions.GetAddMethod(), System.Reflection.EventInfoExtensions.GetAddMethod(), System.Reflection.MethodInfoExtensions.GetBaseDefinition(), System.Reflection.TypeExtensions.GetConstructor(), System.Reflection.TypeExtensions.GetConstructors(), System.Reflection.TypeExtensions.GetConstructors(), System.Reflection.TypeExtensions.GetDefaultMembers(), System.Reflection.TypeExtensions.GetEvent(), System.Reflection.TypeExtensions.GetEvent(), System.Reflection.TypeExtensions.GetEvents(), System.Reflection.TypeExtensions.GetEvents(), System.Reflection.AssemblyExtensions.GetExportedTypes(), System.Reflection.TypeExtensions.GetField(), System.Reflection.TypeExtensions.GetField(), System.Reflection.TypeExtensions.GetFields(), System.Reflection.TypeExtensions.GetFields(), System.Reflection.TypeExtensions.GetGenericArguments(), System.Reflection.PropertyInfoExtensions.GetGetMethod(), System.Reflection.PropertyInfoExtensions.GetGetMethod(), System.Reflection.TypeExtensions.GetInterfaces(), System.Reflection.TypeExtensions.GetMember(), System.Reflection.TypeExtensions.GetMember(), System.Reflection.TypeExtensions.GetMembers(), System.Reflection.TypeExtensions.GetMembers(), System.Reflection.MemberInfoExtensions.GetMetadataToken(), System.Reflection.TypeExtensions.GetMethod(), System.Reflection.TypeExtensions.GetMethod(), System.Reflection.TypeExtensions.GetMethod(), System.Reflection.TypeExtensions.GetMethods(), System.Reflection.TypeExtensions.GetMethods(), System.Reflection.AssemblyExtensions.GetModules(), System.Reflection.ModuleExtensions.GetModuleVersionId(), System.Reflection.TypeExtensions.GetNestedType(), System.Reflection.TypeExtensions.GetNestedTypes(), System.Reflection.TypeExtensions.GetProperties(), System.Reflection.TypeExtensions.GetProperties(), System.Reflection.TypeExtensions.GetProperty(), System.Reflection.TypeExtensions.GetProperty(), System.Reflection.TypeExtensions.GetProperty(), System.Reflection.TypeExtensions.GetProperty(), System.Reflection.EventInfoExtensions.GetRaiseMethod(), System.Reflection.EventInfoExtensions.GetRaiseMethod(), System.Reflection.EventInfoExtensions.GetRemoveMethod(), System.Reflection.EventInfoExtensions.GetRemoveMethod(), System.Reflection.PropertyInfoExtensions.GetSetMethod(), System.Reflection.PropertyInfoExtensions.GetSetMethod(), System.Reflection.AssemblyExtensions.GetTypes(), System.Net.WebClient.GetUri(), System.Net.WebClient.GetUri(), System.Reflection.MemberInfoExtensions.HasMetadataToken(), System.Reflection.ModuleExtensions.HasModuleVersionId(), System.Reflection.TypeExtensions.IsAssignableFrom(), System.Reflection.TypeExtensions.IsInstanceOfType(), System.Net.WebClient.OpenRead(), System.Net.WebClient.OpenReadAsync(), System.Net.WebClient.OpenWrite(), System.Net.WebClient.OpenWriteAsync(), System.ComponentModel.DataAnnotations.Validator.TryValidateValue(), System.Net.WebClient.UploadData(), System.Net.WebClient.UploadDataAsync(), System.Net.WebClient.UploadFile(), System.Net.WebClient.UploadFileAsync(), System.Net.WebClient.UploadString(), System.Net.WebClient.UploadStringAsync(), System.Net.WebClient.UploadValues(), System.Net.WebClient.UploadValuesAsync(), and System.ComponentModel.DataAnnotations.Validator.ValidateValue().