Terraria: System.Xml.Serialization.XmlSchemas.Find
Find() [2/3]
object System.Xml.Serialization.XmlSchemas.Find (XmlQualifiedName name, Type type, bool checkCache) inline package
Definition at line 281 of file XmlSchemas.cs.
    {
        if (!IsCompiled)
        {
            foreach (XmlSchema item in base.List)
            {
                Preprocess(item);
            }
        }
        IList list = (IList)SchemaSet.Schemas(name.Namespace);
        if (list == null)
        {
            return null;
        }
        foreach (XmlSchema item2 in list)
        {
            Preprocess(item2);
            XmlSchemaObject xmlSchemaObject = null;
            if (typeof(XmlSchemaType).IsAssignableFrom(type))
            {
                xmlSchemaObject = item2.SchemaTypes[name];
                if (xmlSchemaObject == null || !type.IsAssignableFrom(xmlSchemaObject.GetType()))
                {
                    continue;
                }
            }
            else if (type == typeof(XmlSchemaGroup))
            {
                xmlSchemaObject = item2.Groups[name];
            }
            else if (type == typeof(XmlSchemaAttributeGroup))
            {
                xmlSchemaObject = item2.AttributeGroups[name];
            }
            else if (type == typeof(XmlSchemaElement))
            {
                xmlSchemaObject = item2.Elements[name];
            }
            else if (type == typeof(XmlSchemaAttribute))
            {
                xmlSchemaObject = item2.Attributes[name];
            }
            else if (type == typeof(XmlSchemaNotation))
            {
                xmlSchemaObject = item2.Notations[name];
            }
            if (xmlSchemaObject != null && _shareTypes && checkCache && !IsReference(xmlSchemaObject))
            {
                xmlSchemaObject = Cache.AddItem(xmlSchemaObject, name, this);
            }
            if (xmlSchemaObject != null)
            {
                return xmlSchemaObject;
            }
        }
        return null;
    }
References System.Xml.Serialization.XmlSchemas._shareTypes, System.Xml.Dictionary, System.Xml.Serialization.XmlSchemas.IsCompiled, System.Xml.Serialization.XmlSchemas.IsReference(), System.item, System.list, System.Xml.Serialization.XmlSchemas.Preprocess(), System.Xml.Schema.XmlSchemaSet.Schemas(), System.Xml.Serialization.XmlSchemas.SchemaSet, and System.type.