Terraria: System.Xml.Serialization.XmlSchemas.Merge
Merge() [1/2]
void System.Xml.Serialization.XmlSchemas.Merge (IList originals, XmlSchema schema) inline private
Definition at line 429 of file XmlSchemas.cs.
    {
        foreach (XmlSchema original in originals)
        {
            if (schema == original)
            {
                return;
            }
        }
        foreach (XmlSchemaExternal include in schema.Includes)
        {
            if (include is XmlSchemaImport)
            {
                include.SchemaLocation = null;
                if (include.Schema != null)
                {
                    Merge(include.Schema);
                }
                else
                {
                    AddImport(originals, ((XmlSchemaImport)include).Namespace);
                }
            }
            else if (include.Schema == null)
            {
                if (include.SchemaLocation != null)
                {
                    throw new InvalidOperationException(System.SR.Format(System.SR.XmlSchemaIncludeLocation, GetType().Name, include.SchemaLocation));
                }
            }
            else
            {
                include.SchemaLocation = null;
                Merge(originals, include.Schema);
            }
        }
        bool[] array = new bool[schema.Items.Count];
        int num = 0;
        for (int i = 0; i < schema.Items.Count; i++)
        {
            XmlSchemaObject xmlSchemaObject = schema.Items[i];
            XmlSchemaObject xmlSchemaObject2 = Find(xmlSchemaObject, originals);
            if (xmlSchemaObject2 != null)
            {
                if (!Cache.Match(xmlSchemaObject2, xmlSchemaObject, _shareTypes))
                {
                    throw new InvalidOperationException(MergeFailedMessage(xmlSchemaObject, xmlSchemaObject2, schema.TargetNamespace));
                }
                array[i] = true;
                num++;
            }
        }
        if (num == schema.Items.Count)
        {
            return;
        }
        XmlSchema xmlSchema2 = (XmlSchema)originals[0];
        for (int j = 0; j < schema.Items.Count; j++)
        {
            if (!array[j])
            {
                xmlSchema2.Items.Add(schema.Items[j]);
            }
        }
        xmlSchema2.IsPreprocessed = false;
        Preprocess(xmlSchema2);
    }
References System.Xml.Serialization.XmlSchemas._shareTypes, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Xml.Serialization.XmlSchemas.AddImport(), System.array, System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Xml.Dictionary, System.Xml.Serialization.XmlSchemas.Find(), System.SR.Format(), System.Xml.Serialization.XmlSchemas.Merge(), System.Xml.Serialization.XmlSchemas.MergeFailedMessage(), System.Xml.Name, System.Xml.Schema.Namespace, System.Xml.Serialization.XmlSchemas.Preprocess(), System.Xml.Serialization.XmlSchemas.XmlSchema, and System.SR.XmlSchemaIncludeLocation.