Terraria: System.Xml.Serialization.XmlSchemas.Merge
Merge() [2/2]
void System.Xml.Serialization.XmlSchemas.Merge (XmlSchema schema) inline private
Definition at line 388 of file XmlSchemas.cs.
    {
        if (MergedSchemas[schema] == null)
        {
            IList list = (IList)SchemaSet.Schemas(schema.TargetNamespace);
            if (list != null && list.Count > 0)
            {
                MergedSchemas.Add(schema, schema);
                Merge(list, schema);
            }
            else
            {
                Add(schema);
                MergedSchemas.Add(schema, schema);
            }
        }
    }
References System.Add, System.Collections.Hashtable.Add(), System.list, System.Xml.Serialization.XmlSchemas.Merge(), System.Xml.Serialization.XmlSchemas.MergedSchemas, System.Xml.Schema.XmlSchemaSet.Schemas(), and System.Xml.Serialization.XmlSchemas.SchemaSet.
Referenced by System.Xml.Serialization.XmlSchemas.Compile(), System.Xml.Serialization.XmlSchemas.Merge(), and System.Xml.Serialization.XmlSchemas.Merge().