Terraria: System.Xml.Serialization.XmlSchemas.AddName
AddName()
void System.Xml.Serialization.XmlSchemas.AddName (XmlSchema schema) inline private
Definition at line 239 of file XmlSchemas.cs.
    {
        if (_isCompiled)
        {
            throw new InvalidOperationException(System.SR.XmlSchemaCompiled);
        }
        if (SchemaSet.Contains(schema))
        {
            SchemaSet.Reprocess(schema);
            return;
        }
        Prepare(schema);
        SchemaSet.Add(schema);
    }
References System.Xml.Serialization.XmlSchemas._isCompiled, System.Xml.Schema.XmlSchemaSet.Add(), System.Xml.Schema.XmlSchemaSet.Contains(), System.Xml.Serialization.XmlSchemas.Prepare(), System.Xml.Schema.XmlSchemaSet.Reprocess(), System.Xml.Serialization.XmlSchemas.SchemaSet, and System.SR.XmlSchemaCompiled.
Referenced by System.Xml.Serialization.XmlSchemas.OnInsert(), and System.Xml.Serialization.XmlSchemas.OnSet().