Terraria: System.Xml.Serialization.XmlSchemas.Compile
Compile()
void System.Xml.Serialization.XmlSchemas.Compile (ValidationEventHandler? handler, bool fullCompile) inline
Definition at line 665 of file XmlSchemas.cs.
    {
        if (_isCompiled)
        {
            return;
        }
        foreach (XmlSchema value in delayedSchemas.Values)
        {
            Merge(value);
        }
        delayedSchemas.Clear();
        if (fullCompile)
        {
            _schemaSet = new XmlSchemaSet();
            _schemaSet.XmlResolver = null;
            _schemaSet.ValidationEventHandler += handler;
            foreach (XmlSchema value2 in References.Values)
            {
                _schemaSet.Add(value2);
            }
            int num = _schemaSet.Count;
            foreach (XmlSchema item in base.List)
            {
                if (!SchemaSet.Contains(item))
                {
                    _schemaSet.Add(item);
                    num++;
                }
            }
            if (!SchemaSet.Contains("http://www.w3.org/2001/XMLSchema"))
            {
                AddReference(XsdSchema);
                _schemaSet.Add(XsdSchema);
                num++;
            }
            if (!SchemaSet.Contains("http://www.w3.org/XML/1998/namespace"))
            {
                AddReference(XmlSchema);
                _schemaSet.Add(XmlSchema);
                num++;
            }
            _schemaSet.Compile();
            _schemaSet.ValidationEventHandler -= handler;
            _isCompiled = _schemaSet.IsCompiled && num == _schemaSet.Count;
            return;
        }
        try
        {
            XmlNameTable nameTable = new System.Xml.NameTable();
            Preprocessor preprocessor = new Preprocessor(nameTable, new SchemaNames(nameTable), null);
            preprocessor.XmlResolver = null;
            preprocessor.SchemaLocations = new Hashtable();
            preprocessor.ChameleonSchemas = new Hashtable();
            foreach (XmlSchema item2 in SchemaSet.Schemas())
            {
                preprocessor.Execute(item2, item2.TargetNamespace, loadExternals: true);
            }
        }
        catch (XmlSchemaException ex)
        {
            throw CreateValidationException(ex, ex.Message);
        }
    }
References System.Xml.Serialization.XmlSchemas._isCompiled, System.Xml.Serialization.XmlSchemas._schemaSet, System.Xml.Schema.XmlSchemaSet.Add(), System.Xml.Serialization.XmlSchemas.AddReference(), System.Collections.Hashtable.Clear(), System.Xml.Schema.XmlSchemaSet.Compile(), System.Xml.Schema.XmlSchemaSet.Contains(), System.Xml.Schema.XmlSchemaSet.Count, System.Xml.Serialization.XmlSchemas.CreateValidationException(), System.Xml.Serialization.XmlSchemas.delayedSchemas, System.Xml.Dictionary, System.item, System.Xml.Serialization.XmlSchemas.Merge(), System.Xml.Serialization.XmlSchemas.References, System.Xml.Schema.XmlSchemaSet.Schemas(), System.Xml.Serialization.XmlSchemas.SchemaSet, System.value, System.Collections.Hashtable.Values, and System.Xml.Serialization.XmlSchemas.XsdSchema.
Referenced by System.Xml.Serialization.SchemaGraph.SchemaGraph().