Terraria: System.Xml.Serialization.XmlSchemas.CreateValidationException
CreateValidationException()
static Exception System.Xml.Serialization.XmlSchemas.CreateValidationException (XmlSchemaException exception, string message) inline static package
Definition at line 729 of file XmlSchemas.cs.
    {
        XmlSchemaObject xmlSchemaObject = exception.SourceSchemaObject;
        if (exception.LineNumber == 0 && exception.LinePosition == 0)
        {
            throw new InvalidOperationException(GetSchemaItem(xmlSchemaObject, null, message), exception);
        }
        string text = null;
        if (xmlSchemaObject != null)
        {
            while (xmlSchemaObject.Parent != null)
            {
                xmlSchemaObject = xmlSchemaObject.Parent;
            }
            if (xmlSchemaObject is XmlSchema)
            {
                text = ((XmlSchema)xmlSchemaObject).TargetNamespace;
            }
        }
        throw new InvalidOperationException(System.SR.Format(System.SR.XmlSchemaSyntaxErrorDetails, text, message, exception.LineNumber, exception.LinePosition), exception);
    }
References System.exception, System.SR.Format(), System.Xml.Serialization.XmlSchemas.GetSchemaItem(), System.text, System.Xml.Serialization.XmlSchemas.XmlSchema, and System.SR.XmlSchemaSyntaxErrorDetails.
Referenced by System.Xml.Serialization.XmlSchemas.Compile(), and System.Xml.Serialization.XmlSchemas.Preprocess().