Terraria: System.Xml.Serialization.XmlSchemas.Preprocess
Preprocess()
static void System.Xml.Serialization.XmlSchemas.Preprocess (XmlSchema schema) inline static package
Definition at line 344 of file XmlSchemas.cs.
    {
        if (!schema.IsPreprocessed)
        {
            try
            {
                XmlNameTable nameTable = new System.Xml.NameTable();
                Preprocessor preprocessor = new Preprocessor(nameTable, new SchemaNames(nameTable), null);
                preprocessor.SchemaLocations = new Hashtable();
                preprocessor.Execute(schema, schema.TargetNamespace, loadExternals: false);
            }
            catch (XmlSchemaException ex)
            {
                throw CreateValidationException(ex, ex.Message);
            }
        }
    }
References System.Xml.Serialization.XmlSchemas.CreateValidationException(), and System.Xml.Dictionary.
Referenced by System.Xml.Serialization.XmlSchemaImporter.AttributeForm(), System.Xml.Serialization.SerializableMapping.CheckDuplicateElement(), System.Xml.Serialization.XmlSchemaImporter.ElementForm(), System.Xml.Serialization.XmlSchemas.Find(), System.Xml.Serialization.XmlSchemaImporter.ImportDerivedTypes(), and System.Xml.Serialization.XmlSchemas.Merge().