Terraria: NetBestiaryModule.Deserialize
Deserialize()
override bool NetBestiaryModule.Deserialize (BinaryReader reader, int userId) inline virtual
Implements NetModule.
     {
         if (Main.dedServ)
         {
             return false;
         }
         switch ((BestiaryUnlockType)reader.ReadByte())
         {
         case BestiaryUnlockType.Kill:
         {
             short key3 = reader.ReadInt16();
             string bestiaryCreditId3 = ContentSamples.NpcsByNetId[key3].GetBestiaryCreditId();
             ushort killCount = reader.ReadUInt16();
             Main.BestiaryTracker.Kills.SetKillCountDirectly(bestiaryCreditId3, killCount);
             break;
         }
         case BestiaryUnlockType.Chat:
         {
             short key2 = reader.ReadInt16();
             string bestiaryCreditId2 = ContentSamples.NpcsByNetId[key2].GetBestiaryCreditId();
             Main.BestiaryTracker.Chats.SetWasChatWithDirectly(bestiaryCreditId2);
             break;
         }
         case BestiaryUnlockType.Sight:
         {
             short key = reader.ReadInt16();
             string bestiaryCreditId = ContentSamples.NpcsByNetId[key].GetBestiaryCreditId();
             Main.BestiaryTracker.Sights.SetWasSeenDirectly(bestiaryCreditId);
             break;
         }
         }
         return true;
     }
References Main.BestiaryTracker, BestiaryUnlocksTracker.Chats, Main.dedServ, BestiaryUnlocksTracker.Kills, ContentSamples.NpcsByNetId, NPCKillsTracker.SetKillCountDirectly(), NPCWasChatWithTracker.SetWasChatWithDirectly(), NPCWasNearPlayerTracker.SetWasSeenDirectly(), and BestiaryUnlocksTracker.Sights.