Terraria: System.Xml.Serialization.XmlSchemas.Dump
Dump()
static string System.Xml.Serialization.XmlSchemas.Dump (XmlSchemaObject o) inline static private
Definition at line 621 of file XmlSchemas.cs.
    {
        XmlWriterSettings xmlWriterSettings = new XmlWriterSettings();
        xmlWriterSettings.OmitXmlDeclaration = true;
        xmlWriterSettings.Indent = true;
        XmlSerializer xmlSerializer = new XmlSerializer(o.GetType());
        StringWriter stringWriter = new StringWriter(CultureInfo.InvariantCulture);
        XmlWriter xmlWriter = XmlWriter.Create(stringWriter, xmlWriterSettings);
        XmlSerializerNamespaces xmlSerializerNamespaces = new XmlSerializerNamespaces();
        xmlSerializerNamespaces.Add("xs", "http://www.w3.org/2001/XMLSchema");
        xmlSerializer.Serialize(xmlWriter, o, xmlSerializerNamespaces);
        return stringWriter.ToString();
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Xml.XmlWriter.Create(), System.Xml.Dictionary, and System.Globalization.CultureInfo.InvariantCulture.
Referenced by System.Xml.Serialization.XmlSchemas.MergeFailedMessage().