Terraria: System.Xml.Serialization.XmlSchemas.MergeFailedMessage
MergeFailedMessage()
static string System.Xml.Serialization.XmlSchemas.MergeFailedMessage (XmlSchemaObject src, XmlSchemaObject dest, string ns) inline static private
Definition at line 636 of file XmlSchemas.cs.
    {
        string text = System.SR.Format(System.SR.XmlSerializableMergeItem, ns, GetSchemaItem(src, ns, null));
        text = text + "\r\n" + Dump(src);
        return text + "\r\n" + Dump(dest);
    }
References System.Xml.Serialization.XmlSchemas.Dump(), System.SR.Format(), System.Xml.Serialization.XmlSchemas.GetSchemaItem(), System.text, and System.SR.XmlSerializableMergeItem.
Referenced by System.Xml.Serialization.XmlSchemas.Merge().