Terraria: System.Xml.Serialization.XmlSchemas.GetSchemaItem
GetSchemaItem()
static string System.Xml.Serialization.XmlSchemas.GetSchemaItem (XmlSchemaObject o, string ns, string details) inline static private
Definition at line 544 of file XmlSchemas.cs.
    {
        if (o == null)
        {
            return null;
        }
        while (o.Parent != null && !(o.Parent is XmlSchema))
        {
            o = o.Parent;
        }
        if (ns == null || ns.Length == 0)
        {
            XmlSchemaObject xmlSchemaObject = o;
            while (xmlSchemaObject.Parent != null)
            {
                xmlSchemaObject = xmlSchemaObject.Parent;
            }
            if (xmlSchemaObject is XmlSchema)
            {
                ns = ((XmlSchema)xmlSchemaObject).TargetNamespace;
            }
        }
        string text = null;
        if (o is XmlSchemaNotation)
        {
            return System.SR.Format(System.SR.XmlSchemaNamedItem, ns, "notation", ((XmlSchemaNotation)o).Name, details);
        }
        if (o is XmlSchemaGroup)
        {
            return System.SR.Format(System.SR.XmlSchemaNamedItem, ns, "group", ((XmlSchemaGroup)o).Name, details);
        }
        if (o is XmlSchemaElement)
        {
            XmlSchemaElement xmlSchemaElement = (XmlSchemaElement)o;
            if (xmlSchemaElement.Name == null || xmlSchemaElement.Name.Length == 0)
            {
                XmlQualifiedName parentName = GetParentName(o);
                return System.SR.Format(System.SR.XmlSchemaElementReference, xmlSchemaElement.RefName.ToString(), parentName.Name, parentName.Namespace);
            }
            return System.SR.Format(System.SR.XmlSchemaNamedItem, ns, "element", xmlSchemaElement.Name, details);
        }
        if (o is XmlSchemaType)
        {
            return System.SR.Format(System.SR.XmlSchemaNamedItem, ns, (o.GetType() == typeof(XmlSchemaSimpleType)) ? "simpleType" : "complexType", ((XmlSchemaType)o).Name, null);
        }
        if (o is XmlSchemaAttributeGroup)
        {
            return System.SR.Format(System.SR.XmlSchemaNamedItem, ns, "attributeGroup", ((XmlSchemaAttributeGroup)o).Name, details);
        }
        if (o is XmlSchemaAttribute)
        {
            XmlSchemaAttribute xmlSchemaAttribute = (XmlSchemaAttribute)o;
            if (xmlSchemaAttribute.Name == null || xmlSchemaAttribute.Name.Length == 0)
            {
                XmlQualifiedName parentName2 = GetParentName(o);
                return System.SR.Format(System.SR.XmlSchemaAttributeReference, xmlSchemaAttribute.RefName.ToString(), parentName2.Name, parentName2.Namespace);
            }
            return System.SR.Format(System.SR.XmlSchemaNamedItem, ns, "attribute", xmlSchemaAttribute.Name, details);
        }
        if (o is XmlSchemaContent)
        {
            XmlQualifiedName parentName3 = GetParentName(o);
            return System.SR.Format(System.SR.XmlSchemaContentDef, parentName3.Name, parentName3.Namespace, null);
        }
        if (o is XmlSchemaExternal)
        {
            string p = ((o is XmlSchemaImport) ? "import" : ((o is XmlSchemaInclude) ? "include" : ((o is XmlSchemaRedefine) ? "redefine" : o.GetType().Name)));
            return System.SR.Format(System.SR.XmlSchemaItem, ns, p, details);
        }
        if (o is XmlSchema)
        {
            return System.SR.Format(System.SR.XmlSchema, ns, details);
        }
        return System.SR.Format(System.SR.XmlSchemaNamedItem, ns, o.GetType().Name, null, details);
    }
References System.Xml.Dictionary, System.SR.Format(), System.Xml.Serialization.XmlSchemas.GetParentName(), System.Xml.Name, System.text, System.Xml.Serialization.XmlSchemas.XmlSchema, System.SR.XmlSchema, System.SR.XmlSchemaAttributeReference, System.SR.XmlSchemaContentDef, System.SR.XmlSchemaElementReference, System.SR.XmlSchemaItem, and System.SR.XmlSchemaNamedItem.
Referenced by System.Xml.Serialization.XmlSchemas.CreateValidationException(), and System.Xml.Serialization.XmlSchemas.MergeFailedMessage().