Terraria: NativeClipboard.TryGetText
TryGetText()
static bool NativeClipboard.TryGetText (out string text) inline static
     {
         text = null;
         if (!IsClipboardFormatAvailable(13u))
         {
             return false;
         }
         try
         {
             if (!OpenClipboard(IntPtr.Zero))
             {
                 return false;
             }
             IntPtr handle = GetClipboardData(13u);
             if (handle == IntPtr.Zero)
             {
                 return false;
             }
             IntPtr pointer = IntPtr.Zero;
             try
             {
                 pointer = GlobalLock(handle);
                 if (pointer == IntPtr.Zero)
                 {
                     return false;
                 }
                 int size = GlobalSize(handle);
                 byte[] buff = new byte[size];
                 Marshal.Copy(pointer, buff, 0, size);
                 text = Encoding.Unicode.GetString(buff).TrimEnd('\0');
                 return !string.IsNullOrEmpty(text);
             }
             finally
             {
                 if (pointer != IntPtr.Zero)
                 {
                     GlobalUnlock(handle);
                 }
             }
         }
         finally
         {
             CloseClipboard();
         }
     }
References CloseClipboard(), GetClipboardData(), GlobalLock(), GlobalSize(), GlobalUnlock(), IsClipboardFormatAvailable(), and OpenClipboard().
Referenced by Clipboard.TryToGetClipboardText().