Terraria: System.Security.Cryptography.DSAKeyFormatHelper.ReadDsaPrivateKey
ReadDsaPrivateKey()
static void System.Security.Cryptography.DSAKeyFormatHelper.ReadDsaPrivateKey (ReadOnlyMemory< byte > xBytes, in AlgorithmIdentifierAsn algId, out DSAParameters ret) inline static package
Definition at line 11 of file DSAKeyFormatHelper.cs.
    {
        if (!algId.Parameters.HasValue)
        {
            throw new CryptographicException(System.SR.Cryptography_Der_Invalid_Encoding);
        }
        DssParms dssParms = DssParms.Decode(algId.Parameters.Value, AsnEncodingRules.BER);
        ret = new DSAParameters
        {
            P = dssParms.P.ToByteArray(isUnsigned: true, isBigEndian: true),
            Q = dssParms.Q.ToByteArray(isUnsigned: true, isBigEndian: true)
        };
        ret.G = dssParms.G.ExportKeyParameter(ret.P.Length);
        BigInteger bigInteger;
        try
        {
            int bytesConsumed;
            ReadOnlySpan<byte> value = AsnDecoder.ReadIntegerBytes(xBytes.Span, AsnEncodingRules.DER, out bytesConsumed);
            if (bytesConsumed != xBytes.Length)
            {
                throw new CryptographicException(System.SR.Cryptography_Der_Invalid_Encoding);
            }
            bigInteger = new BigInteger(value, isUnsigned: true, isBigEndian: true);
        }
        catch (AsnContentException inner)
        {
            throw new CryptographicException(System.SR.Cryptography_Der_Invalid_Encoding, inner);
        }
        ret.X = bigInteger.ExportKeyParameter(ret.Q.Length);
        BigInteger value2 = BigInteger.ModPow(dssParms.G, bigInteger, dssParms.P);
        ret.Y = value2.ExportKeyParameter(ret.P.Length);
    }
References System.SR.Cryptography_Der_Invalid_Encoding, System.Security.Cryptography.Asn1.DssParms.Decode(), System.Security.Cryptography.Asn1.DssParms.G, System.ReadOnlyMemory< T >.Length, System.Numerics.BigInteger.ModPow(), System.P, System.Security.Cryptography.Asn1.DssParms.P, System.Q, System.Security.Cryptography.Asn1.DssParms.Q, System.Formats.Asn1.AsnDecoder.ReadIntegerBytes(), System.ReadOnlyMemory< T >.Span, System.Numerics.BigInteger.ToByteArray(), and System.value.
Referenced by System.Security.Cryptography.DSAKeyFormatHelper.ReadEncryptedPkcs8(), System.Security.Cryptography.DSAKeyFormatHelper.ReadEncryptedPkcs8(), and System.Security.Cryptography.DSAKeyFormatHelper.ReadPkcs8().