Terraria: System.Security.Cryptography.DSAKeyFormatHelper.WriteSubjectPublicKeyInfo
WriteSubjectPublicKeyInfo()
static AsnWriter System.Security.Cryptography.DSAKeyFormatHelper.WriteSubjectPublicKeyInfo (in DSAParameters dsaParameters) inline static package
Definition at line 93 of file DSAKeyFormatHelper.cs.
    {
        AsnWriter asnWriter = new AsnWriter(AsnEncodingRules.DER);
        asnWriter.PushSequence();
        WriteAlgorithmId(asnWriter, in dsaParameters);
        WriteKeyComponent(asnWriter, dsaParameters.Y, bitString: true);
        asnWriter.PopSequence();
        return asnWriter;
    }
References System.Formats.Asn1.AsnWriter.PopSequence(), System.Formats.Asn1.AsnWriter.PushSequence(), System.Security.Cryptography.DSAKeyFormatHelper.WriteAlgorithmId(), and System.Security.Cryptography.DSAKeyFormatHelper.WriteKeyComponent().
Referenced by System.Security.Cryptography.DSA.WriteSubjectPublicKeyInfo().