Terraria: System.Linq.Expressions.Compiler.DelegateHelpers.MakeNewDelegate
MakeNewDelegate()
static Type System.Linq.Expressions.Compiler.DelegateHelpers.MakeNewDelegate (Type[] types) inline static package
Definition at line 153 of file DelegateHelpers.cs.
    {
        bool flag;
        if (types.Length > 17)
        {
            flag = true;
        }
        else
        {
            flag = false;
            foreach (Type type in types)
            {
                if (type.IsByRef || type.IsByRefLike || type.IsPointer)
                {
                    flag = true;
                    break;
                }
            }
        }
        if (flag)
        {
            return MakeNewCustomDelegate(types);
        }
        if (types[^1] == typeof(void))
        {
            return GetActionType(types.RemoveLast());
        }
        return GetFuncType(types);
    }
References System.Linq.Expressions.Compiler.DelegateHelpers.GetActionType(), System.Linq.Expressions.Compiler.DelegateHelpers.GetFuncType(), System.Linq.Expressions.Compiler.DelegateHelpers.MakeNewCustomDelegate(), and System.type.
Referenced by System.Linq.Expressions.Compiler.DelegateHelpers.MakeDeferredSiteDelegate(), System.Linq.Expressions.Compiler.TypeInfoExtensions.MakeDelegateType(), and System.Linq.Expressions.Compiler.DelegateHelpers.MakeDelegateType().