Terraria: System.Security.Cryptography.DSAKeyFormatHelper.WriteKeyComponent
WriteKeyComponent()
static void System.Security.Cryptography.DSAKeyFormatHelper.WriteKeyComponent (AsnWriter writer, byte[] component, bool bitString) inline static private
Definition at line 126 of file DSAKeyFormatHelper.cs.
    {
        if (bitString)
        {
            AsnWriter asnWriter = new AsnWriter(AsnEncodingRules.DER);
            asnWriter.WriteKeyParameterInteger(component);
            byte[] array = System.Security.Cryptography.CryptoPool.Rent(asnWriter.GetEncodedLength());
            if (!asnWriter.TryEncode(array, out var bytesWritten))
            {
                throw new CryptographicException();
            }
            writer.WriteBitString(array.AsSpan(0, bytesWritten));
            System.Security.Cryptography.CryptoPool.Return(array, bytesWritten);
            return;
        }
        using (writer.PushOctetString())
        {
            writer.WriteKeyParameterInteger(component);
        }
    }
References System.array, System.Formats.Asn1.AsnWriter.GetEncodedLength(), System.Security.Cryptography.CryptoPool.Rent(), System.Security.Cryptography.CryptoPool.Return(), System.Formats.Asn1.AsnWriter.TryEncode(), and System.writer.
Referenced by System.Security.Cryptography.DSAKeyFormatHelper.WritePkcs8(), and System.Security.Cryptography.DSAKeyFormatHelper.WriteSubjectPublicKeyInfo().