Terraria: System.Linq.Expressions.Compiler.DelegateHelpers.GetActionType
GetActionType()
static Type System.Linq.Expressions.Compiler.DelegateHelpers.GetActionType (Type[] types) inline static package
Definition at line 208 of file DelegateHelpers.cs.
    {
        return types.Length switch
        {
            0 => typeof(Action),
            1 => typeof(Action<>).MakeGenericType(types),
            2 => typeof(Action<, >).MakeGenericType(types),
            3 => typeof(Action<, , >).MakeGenericType(types),
            4 => typeof(Action<, , , >).MakeGenericType(types),
            5 => typeof(Action<, , , , >).MakeGenericType(types),
            6 => typeof(Action<, , , , , >).MakeGenericType(types),
            7 => typeof(Action<, , , , , , >).MakeGenericType(types),
            8 => typeof(Action<, , , , , , , >).MakeGenericType(types),
            9 => typeof(Action<, , , , , , , , >).MakeGenericType(types),
            10 => typeof(Action<, , , , , , , , , >).MakeGenericType(types),
            11 => typeof(Action<, , , , , , , , , , >).MakeGenericType(types),
            12 => typeof(Action<, , , , , , , , , , , >).MakeGenericType(types),
            13 => typeof(Action<, , , , , , , , , , , , >).MakeGenericType(types),
            14 => typeof(Action<, , , , , , , , , , , , , >).MakeGenericType(types),
            15 => typeof(Action<, , , , , , , , , , , , , , >).MakeGenericType(types),
            16 => typeof(Action<, , , , , , , , , , , , , , , >).MakeGenericType(types),
            _ => null,
        };
    }
Referenced by System.Linq.Expressions.Expression< TDelegate >.GetActionType(), System.Linq.Expressions.Compiler.DelegateHelpers.MakeNewDelegate(), System.Runtime.CompilerServices.CallSite< T >.MakeUpdateDelegate(), and System.Linq.Expressions.Expression< TDelegate >.TryGetActionType().