Terraria: System.Linq.Expressions.Compiler.DelegateHelpers.MakeDeferredSiteDelegate
MakeDeferredSiteDelegate()
static Type System.Linq.Expressions.Compiler.DelegateHelpers.MakeDeferredSiteDelegate (DynamicMetaObject[] args, Type returnType) inline static package
Definition at line 47 of file DelegateHelpers.cs.
    {
        lock (_DelegateCache)
        {
            TypeInfo delegateCache = _DelegateCache;
            delegateCache = NextTypeInfo(typeof(CallSite), delegateCache);
            foreach (DynamicMetaObject dynamicMetaObject in args)
            {
                Type type = dynamicMetaObject.Expression.Type;
                if (IsByRef(dynamicMetaObject))
                {
                    type = type.MakeByRefType();
                }
                delegateCache = NextTypeInfo(type, delegateCache);
            }
            delegateCache = NextTypeInfo(returnType, delegateCache);
            if (delegateCache.DelegateType == null)
            {
                Type[] array = new Type[args.Length + 2];
                array[0] = typeof(CallSite);
                array[^1] = returnType;
                for (int j = 0; j < args.Length; j++)
                {
                    DynamicMetaObject dynamicMetaObject2 = args[j];
                    Type type2 = dynamicMetaObject2.Expression.Type;
                    if (IsByRef(dynamicMetaObject2))
                    {
                        type2 = type2.MakeByRefType();
                    }
                    array[j + 1] = type2;
                }
                delegateCache.DelegateType = MakeNewDelegate(array);
            }
            return delegateCache.DelegateType;
        }
    }
References System.Linq.Expressions.Compiler.DelegateHelpers._DelegateCache, System.array, System.Reflection.Emit.IsByRef, System.Linq.Expressions.Compiler.DelegateHelpers.MakeNewDelegate(), System.Linq.Expressions.Compiler.DelegateHelpers.NextTypeInfo(), and System.type.
Referenced by System.Dynamic.DynamicMetaObjectBinder.MakeDeferred().