Terraria: System.Security.Cryptography.DSAKeyFormatHelper.ReadPkcs8
ReadPkcs8()
static void System.Security.Cryptography.DSAKeyFormatHelper.ReadPkcs8 (ReadOnlySpan< byte > source, out int bytesRead, out DSAParameters key) inline static package
Definition at line 78 of file DSAKeyFormatHelper.cs.
    {
        KeyFormatHelper.ReadPkcs8(s_validOids, source, (KeyFormatHelper.KeyReader<DSAParameters>)ReadDsaPrivateKey, out bytesRead, out key);
    }
References System.key, System.Security.Cryptography.DSAKeyFormatHelper.ReadDsaPrivateKey(), System.Security.Cryptography.KeyFormatHelper.ReadPkcs8(), System.Security.Cryptography.DSAKeyFormatHelper.s_validOids, and System.source.
Referenced by System.Security.Cryptography.DSA.ImportPkcs8PrivateKey().