Terraria: System.Linq.Expressions.Compiler.DelegateHelpers.MakeNewCustomDelegate
MakeNewCustomDelegate()
static Type System.Linq.Expressions.Compiler.DelegateHelpers.MakeNewCustomDelegate (Type[] types) inline static private
Definition at line 93 of file DelegateHelpers.cs.
    {
        Type returnType = types[^1];
        Type[] parameterTypes = types.RemoveLast();
        TypeBuilder typeBuilder = AssemblyGen.DefineDelegateType("Delegate" + types.Length);
        typeBuilder.DefineConstructor(MethodAttributes.Public | MethodAttributes.HideBySig | MethodAttributes.RTSpecialName, CallingConventions.Standard, s_delegateCtorSignature).SetImplementationFlags(MethodImplAttributes.CodeTypeMask);
        typeBuilder.DefineMethod("Invoke", MethodAttributes.Public | MethodAttributes.Virtual | MethodAttributes.HideBySig | MethodAttributes.VtableLayoutMask, returnType, parameterTypes).SetImplementationFlags(MethodImplAttributes.CodeTypeMask);
        return typeBuilder.CreateTypeInfo();
    }
References System.Reflection.Emit.TypeBuilder.CreateTypeInfo(), System.Reflection.Emit.TypeBuilder.DefineConstructor(), System.Linq.Expressions.Compiler.AssemblyGen.DefineDelegateType(), System.Reflection.Emit.TypeBuilder.DefineMethod(), System.Linq.Expressions.Compiler.DelegateHelpers.s_delegateCtorSignature, and System.Reflection.Emit.ConstructorBuilder.SetImplementationFlags().
Referenced by System.Linq.Expressions.Compiler.DelegateHelpers.MakeNewDelegate().