Terraria: System.Xml.Schema.XdrValidator.LoadSchemaFromLocation
LoadSchemaFromLocation()
void System.Xml.Schema.XdrValidator.LoadSchemaFromLocation (string uri) inline private
Definition at line 324 of file XdrValidator.cs.
    {
        if (!XdrBuilder.IsXdrSchema(uri))
        {
            return;
        }
        string relativeUri = uri.Substring("x-schema:".Length);
        XmlReader xmlReader = null;
        SchemaInfo schemaInfo = null;
        try
        {
            Uri uri2 = base.XmlResolver.ResolveUri(base.BaseUri, relativeUri);
            Stream input = (Stream)base.XmlResolver.GetEntity(uri2, null, null);
            xmlReader = new XmlTextReader(uri2.ToString(), input, base.NameTable);
            ((XmlTextReader)xmlReader).XmlResolver = base.XmlResolver;
            Parser parser = new Parser(SchemaType.XDR, base.NameTable, base.SchemaNames, base.EventHandler);
            parser.XmlResolver = base.XmlResolver;
            parser.Parse(xmlReader, uri);
            while (xmlReader.Read())
            {
            }
            schemaInfo = parser.XdrSchema;
        }
        catch (XmlSchemaException ex)
        {
            SendValidationEvent(System.SR.Sch_CannotLoadSchema, new string[2] { uri, ex.Message }, XmlSeverityType.Error);
        }
        catch (Exception ex2)
        {
            SendValidationEvent(System.SR.Sch_CannotLoadSchema, new string[2] { uri, ex2.Message }, XmlSeverityType.Warning);
        }
        finally
        {
            xmlReader?.Close();
        }
        if (schemaInfo != null && schemaInfo.ErrorCount == 0)
        {
            base.schemaInfo.Add(schemaInfo, base.EventHandler);
            base.SchemaCollection.Add(uri, schemaInfo, null, compile: false);
        }
    }
References System.Xml.Dictionary, System.Xml.Schema.SchemaInfo.ErrorCount, System.input, System.Xml.Schema.XdrBuilder.IsXdrSchema(), System.Xml.Schema.Length, System.SR.Sch_CannotLoadSchema, System.Xml.Schema.BaseValidator.schemaInfo, and System.Xml.Schema.BaseValidator.SendValidationEvent().
Referenced by System.Xml.Schema.XdrValidator.LoadSchema().