Terraria: System.Xml.Schema.XdrValidator.Init
Init()
void System.Xml.Schema.XdrValidator.Init () inline private
Definition at line 58 of file XdrValidator.cs.
    {
        _nsManager = reader.NamespaceManager;
        if (_nsManager == null)
        {
            _nsManager = new XmlNamespaceManager(base.NameTable);
            _isProcessContents = true;
        }
        _validationStack = new HWStack(10);
        textValue = new StringBuilder();
        _name = XmlQualifiedName.Empty;
        _attPresence = new Hashtable();
        Push(XmlQualifiedName.Empty);
        schemaInfo = new SchemaInfo();
        checkDatatype = false;
    }
References System.Xml.Schema.XdrValidator._attPresence, System.Xml.Schema.XdrValidator._isProcessContents, System.Xml.Schema.XdrValidator._name, System.Xml.Schema.XdrValidator._nsManager, System.Xml.Schema.XdrValidator._validationStack, System.Xml.Schema.BaseValidator.checkDatatype, System.Xml.Dictionary, System.Xml.XmlQualifiedName.Empty, System.Xml.XmlValidatingReaderImpl.NamespaceManager, System.Xml.Schema.XdrValidator.Push(), System.Xml.Schema.BaseValidator.reader, System.Xml.Schema.BaseValidator.schemaInfo, System.Xml.Schema.BaseValidator.SchemaInfo, and System.Xml.Schema.BaseValidator.textValue.
Referenced by System.Xml.Schema.XdrValidator.XdrValidator(), and System.Xml.Schema.XdrValidator.XdrValidator().