Terraria: System.Xml.Schema.XdrValidator.ValidateStartElement
ValidateStartElement()
void System.Xml.Schema.XdrValidator.ValidateStartElement () inline private
Definition at line 234 of file XdrValidator.cs.
    {
        if (context.ElementDecl != null)
        {
            if (context.ElementDecl.SchemaType != null)
            {
                reader.SchemaTypeObject = context.ElementDecl.SchemaType;
            }
            else
            {
                reader.SchemaTypeObject = context.ElementDecl.Datatype;
            }
            if (reader.IsEmptyElement && !context.IsNill && context.ElementDecl.DefaultValueTyped != null)
            {
                reader.TypedValueObject = context.ElementDecl.DefaultValueTyped;
                context.IsNill = true;
            }
            if (context.ElementDecl.HasRequiredAttribute)
            {
                _attPresence.Clear();
            }
        }
        if (!reader.MoveToFirstAttribute())
        {
            return;
        }
        do
        {
            if ((object)reader.NamespaceURI == base.SchemaNames.NsXmlNs)
            {
                continue;
            }
            try
            {
                reader.SchemaTypeObject = null;
                SchemaAttDef attributeXdr = schemaInfo.GetAttributeXdr(context.ElementDecl, QualifiedName(reader.LocalName, reader.NamespaceURI));
                if (attributeXdr != null)
                {
                    if (context.ElementDecl != null && context.ElementDecl.HasRequiredAttribute)
                    {
                        _attPresence.Add(attributeXdr.Name, attributeXdr);
                    }
                    reader.SchemaTypeObject = ((attributeXdr.SchemaType != null) ? ((object)attributeXdr.SchemaType) : ((object)attributeXdr.Datatype));
                    if (attributeXdr.Datatype != null)
                    {
                        string value = reader.Value;
                        CheckValue(value, attributeXdr);
                    }
                }
            }
            catch (XmlSchemaException ex)
            {
                ex.SetSource(reader.BaseURI, base.PositionInfo.LineNumber, base.PositionInfo.LinePosition);
                SendValidationEvent(ex);
            }
        }
        while (reader.MoveToNextAttribute());
        reader.MoveToElement();
    }
References System.Xml.Schema.XdrValidator._attPresence, System.Collections.Hashtable.Add(), System.Xml.XmlValidatingReaderImpl.BaseURI, System.Xml.Schema.XdrValidator.CheckValue(), System.Collections.Hashtable.Clear(), System.Xml.Schema.BaseValidator.context, System.Xml.Schema.SchemaDeclBase.Datatype, System.Xml.Schema.SchemaDeclBase.DefaultValueTyped, System.Xml.Dictionary, System.Xml.Schema.ValidationState.ElementDecl, System.Xml.Schema.SchemaInfo.GetAttributeXdr(), System.Xml.Schema.SchemaElementDecl.HasRequiredAttribute, System.Xml.XmlValidatingReaderImpl.IsEmptyElement, System.Xml.Schema.ValidationState.IsNill, System.Xml.XmlValidatingReaderImpl.LocalName, System.Xml.XmlValidatingReaderImpl.MoveToElement(), System.Xml.XmlValidatingReaderImpl.MoveToFirstAttribute(), System.Xml.XmlValidatingReaderImpl.MoveToNextAttribute(), System.Xml.XmlValidatingReaderImpl.NamespaceURI, System.Xml.Schema.XdrValidator.QualifiedName(), System.Xml.Schema.BaseValidator.reader, System.Xml.Schema.BaseValidator.schemaInfo, System.Xml.Schema.SchemaDeclBase.SchemaType, System.Xml.Schema.BaseValidator.SendValidationEvent(), System.value, and System.Xml.XmlValidatingReaderImpl.Value.
Referenced by System.Xml.Schema.XdrValidator.ProcessElement().