Terraria: System.Xml.Schema.XdrValidator.ProcessInlineSchema
ProcessInlineSchema()
void System.Xml.Schema.XdrValidator.ProcessInlineSchema () inline private
Definition at line 134 of file XdrValidator.cs.
    {
        if (_inlineSchemaParser.ParseReaderNode())
        {
            return;
        }
        _inlineSchemaParser.FinishParsing();
        SchemaInfo xdrSchema = _inlineSchemaParser.XdrSchema;
        if (xdrSchema != null && xdrSchema.ErrorCount == 0)
        {
            foreach (string key in xdrSchema.TargetNamespaces.Keys)
            {
                if (!schemaInfo.HasSchema(key))
                {
                    schemaInfo.Add(xdrSchema, base.EventHandler);
                    base.SchemaCollection.Add(key, xdrSchema, null, compile: false);
                    break;
                }
            }
        }
        _inlineSchemaParser = null;
    }
References System.Xml.Schema.XdrValidator._inlineSchemaParser, System.Xml.Schema.SchemaInfo.Add(), System.Xml.Dictionary, System.Xml.Schema.Parser.FinishParsing(), System.Xml.Schema.SchemaInfo.HasSchema(), System.key, System.Xml.Schema.Parser.ParseReaderNode(), System.Xml.Schema.BaseValidator.schemaInfo, and System.Xml.Schema.Parser.XdrSchema.
Referenced by System.Xml.Schema.XdrValidator.Validate().