Terraria: System.Xml.Schema.XdrValidator.ValidateEndStartElement
ValidateEndStartElement()
void System.Xml.Schema.XdrValidator.ValidateEndStartElement () inline private
Definition at line 294 of file XdrValidator.cs.
    {
        if (context.ElementDecl.HasDefaultAttribute)
        {
            for (int i = 0; i < context.ElementDecl.DefaultAttDefs.Count; i++)
            {
                reader.AddDefaultAttribute((SchemaAttDef)context.ElementDecl.DefaultAttDefs[i]);
            }
        }
        if (context.ElementDecl.HasRequiredAttribute)
        {
            try
            {
                context.ElementDecl.CheckAttributes(_attPresence, reader.StandAlone);
            }
            catch (XmlSchemaException ex)
            {
                ex.SetSource(reader.BaseURI, base.PositionInfo.LineNumber, base.PositionInfo.LinePosition);
                SendValidationEvent(ex);
            }
        }
        if (context.ElementDecl.Datatype != null)
        {
            checkDatatype = true;
            hasSibling = false;
            textString = string.Empty;
            textValue.Length = 0;
        }
    }
References System.Xml.Schema.XdrValidator._attPresence, System.Xml.XmlValidatingReaderImpl.AddDefaultAttribute(), System.Xml.XmlValidatingReaderImpl.BaseURI, System.Xml.Schema.SchemaElementDecl.CheckAttributes(), System.Xml.Schema.BaseValidator.checkDatatype, System.Xml.Schema.BaseValidator.context, System.Xml.Schema.SchemaDeclBase.Datatype, System.Xml.Schema.SchemaElementDecl.DefaultAttDefs, System.Xml.Dictionary, System.Xml.Schema.ValidationState.ElementDecl, System.Xml.Schema.SchemaElementDecl.HasDefaultAttribute, System.Xml.Schema.SchemaElementDecl.HasRequiredAttribute, System.Xml.Schema.BaseValidator.hasSibling, System.Xml.Schema.BaseValidator.reader, System.Xml.Schema.BaseValidator.SendValidationEvent(), System.Xml.XmlValidatingReaderImpl.StandAlone, and System.Xml.Schema.BaseValidator.textString.
Referenced by System.Xml.Schema.XdrValidator.ProcessElement().