Terraria: System.Xml.Schema.XdrValidator.ThoroughGetElementDecl
ThoroughGetElementDecl()
SchemaElementDecl System.Xml.Schema.XdrValidator.ThoroughGetElementDecl () inline private
Definition at line 198 of file XdrValidator.cs.
    {
        if (reader.Depth == 0)
        {
            LoadSchema(string.Empty);
        }
        if (reader.MoveToFirstAttribute())
        {
            do
            {
                string namespaceURI = reader.NamespaceURI;
                string localName = reader.LocalName;
                if (Ref.Equal(namespaceURI, base.SchemaNames.NsXmlNs))
                {
                    LoadSchema(reader.Value);
                    if (_isProcessContents)
                    {
                        _nsManager.AddNamespace((reader.Prefix.Length == 0) ? string.Empty : reader.LocalName, reader.Value);
                    }
                }
                if (Ref.Equal(namespaceURI, base.SchemaNames.QnDtDt.Namespace) && Ref.Equal(localName, base.SchemaNames.QnDtDt.Name))
                {
                    reader.SchemaTypeObject = XmlSchemaDatatype.FromXdrName(reader.Value);
                }
            }
            while (reader.MoveToNextAttribute());
            reader.MoveToElement();
        }
        SchemaElementDecl elementDecl = schemaInfo.GetElementDecl(elementName);
        if (elementDecl == null && schemaInfo.TargetNamespaces.ContainsKey(context.Namespace))
        {
            SendValidationEvent(System.SR.Sch_UndeclaredElement, XmlSchemaValidator.QNameString(context.LocalName, context.Namespace));
        }
        return elementDecl;
    }
References System.Xml.Schema.XdrValidator._isProcessContents, System.Xml.Schema.XdrValidator._nsManager, System.Xml.XmlNamespaceManager.AddNamespace(), System.Collections.Generic.Dictionary< TKey, TValue >.ContainsKey(), System.Xml.Schema.BaseValidator.context, System.Xml.XmlValidatingReaderImpl.Depth, System.Xml.Dictionary, System.Xml.Schema.BaseValidator.elementName, System.Xml.Ref.Equal(), System.Xml.Schema.XmlSchemaDatatype.FromXdrName(), System.Xml.Schema.SchemaInfo.GetElementDecl(), System.Xml.Schema.XdrValidator.LoadSchema(), System.Xml.Schema.ValidationState.LocalName, System.Xml.XmlValidatingReaderImpl.LocalName, System.Xml.XmlValidatingReaderImpl.MoveToElement(), System.Xml.XmlValidatingReaderImpl.MoveToFirstAttribute(), System.Xml.XmlValidatingReaderImpl.MoveToNextAttribute(), System.Xml.Schema.ValidationState.Namespace, System.Xml.XmlValidatingReaderImpl.NamespaceURI, System.Xml.XmlValidatingReaderImpl.Prefix, System.Xml.Schema.XmlSchemaValidator.QNameString(), System.Xml.Schema.BaseValidator.reader, System.SR.Sch_UndeclaredElement, System.Xml.Schema.BaseValidator.schemaInfo, System.Xml.Schema.BaseValidator.SendValidationEvent(), System.Xml.Schema.SchemaInfo.TargetNamespaces, and System.Xml.XmlValidatingReaderImpl.Value.
Referenced by System.Xml.Schema.XdrValidator.ProcessElement().