Terraria: System.Xml.Schema.XdrValidator.ValidateElement
ValidateElement()
void System.Xml.Schema.XdrValidator.ValidateElement () inline private
Definition at line 105 of file XdrValidator.cs.
    {
        elementName.Init(reader.LocalName, XmlSchemaDatatype.XdrCanonizeUri(reader.NamespaceURI, base.NameTable, base.SchemaNames));
        ValidateChildElement();
        if (base.SchemaNames.IsXDRRoot(elementName.Name, elementName.Namespace) && reader.Depth > 0)
        {
            _inlineSchemaParser = new Parser(SchemaType.XDR, base.NameTable, base.SchemaNames, base.EventHandler);
            _inlineSchemaParser.StartParsing(reader, null);
            _inlineSchemaParser.ParseReaderNode();
        }
        else
        {
            ProcessElement();
        }
    }
References System.Xml.Schema.XdrValidator._inlineSchemaParser, System.Xml.XmlValidatingReaderImpl.Depth, System.Xml.Dictionary, System.Xml.Schema.BaseValidator.elementName, System.Xml.XmlQualifiedName.Init(), System.Xml.XmlValidatingReaderImpl.LocalName, System.Xml.XmlQualifiedName.Name, System.Xml.XmlQualifiedName.Namespace, System.Xml.XmlValidatingReaderImpl.NamespaceURI, System.Xml.Schema.Parser.ParseReaderNode(), System.Xml.Schema.XdrValidator.ProcessElement(), System.Xml.Schema.BaseValidator.reader, System.Xml.Schema.Parser.StartParsing(), System.Xml.Schema.XdrValidator.ValidateChildElement(), and System.Xml.Schema.XmlSchemaDatatype.XdrCanonizeUri().
Referenced by System.Xml.Schema.XdrValidator.Validate().