Terraria: System.Xml.Schema.XdrValidator.ValidateChildElement
ValidateChildElement()
void System.Xml.Schema.XdrValidator.ValidateChildElement () inline private
Definition at line 121 of file XdrValidator.cs.
    {
        if (context.NeedValidateChildren)
        {
            int errorCode = 0;
            context.ElementDecl.ContentValidator.ValidateElement(elementName, context, out errorCode);
            if (errorCode < 0)
            {
                XmlSchemaValidator.ElementValidationError(elementName, context, base.EventHandler, reader, reader.BaseURI, base.PositionInfo.LineNumber, base.PositionInfo.LinePosition, null);
            }
        }
    }
References System.Xml.XmlValidatingReaderImpl.BaseURI, System.Xml.Schema.SchemaElementDecl.ContentValidator, System.Xml.Schema.BaseValidator.context, System.Xml.Dictionary, System.Xml.Schema.ValidationState.ElementDecl, System.Xml.Schema.BaseValidator.elementName, System.Xml.Schema.XmlSchemaValidator.ElementValidationError(), System.Xml.Schema.ValidationState.NeedValidateChildren, System.Xml.Schema.BaseValidator.reader, and System.Xml.Schema.ContentValidator.ValidateElement().
Referenced by System.Xml.Schema.XdrValidator.ValidateElement().