Terraria: System.Xml.Schema.XdrValidator.Pop
Pop()
void System.Xml.Schema.XdrValidator.Pop () inline private
Definition at line 609 of file XdrValidator.cs.
    {
        if (_validationStack.Length > 1)
        {
            _validationStack.Pop();
            context = (ValidationState)_validationStack.Peek();
        }
    }
References System.Xml.Schema.XdrValidator._validationStack, System.Xml.Schema.BaseValidator.context, System.Xml.HWStack.Length, System.Xml.HWStack.Peek(), and System.Xml.HWStack.Pop().
Referenced by System.Xml.Schema.XdrValidator.ValidateEndElement().