Terraria: System.Xml.Schema.XdrValidator.Push
Push()
void System.Xml.Schema.XdrValidator.Push (XmlQualifiedName elementName) inline private
Definition at line 594 of file XdrValidator.cs.
    {
        context = (ValidationState)_validationStack.Push();
        if (context == null)
        {
            context = new ValidationState();
            _validationStack.AddToTop(context);
        }
        context.LocalName = elementName.Name;
        context.Namespace = elementName.Namespace;
        context.HasMatched = false;
        context.IsNill = false;
        context.NeedValidateChildren = false;
    }
References System.Xml.Schema.XdrValidator._validationStack, System.Xml.HWStack.AddToTop(), System.Xml.Schema.BaseValidator.context, System.Xml.Dictionary, System.Xml.Schema.BaseValidator.elementName, System.Xml.XmlQualifiedName.Name, System.Xml.XmlQualifiedName.Namespace, and System.Xml.HWStack.Push().
Referenced by System.Xml.Schema.XdrValidator.Init(), and System.Xml.Schema.XdrValidator.ProcessElement().