Terraria: System.Xml.Schema.XdrValidator.ProcessElement
ProcessElement()
void System.Xml.Schema.XdrValidator.ProcessElement () inline private
Definition at line 157 of file XdrValidator.cs.
    {
        Push(elementName);
        if (_isProcessContents)
        {
            _nsManager.PopScope();
        }
        context.ElementDecl = ThoroughGetElementDecl();
        if (context.ElementDecl != null)
        {
            ValidateStartElement();
            ValidateEndStartElement();
            context.NeedValidateChildren = true;
            context.ElementDecl.ContentValidator.InitValidation(context);
        }
    }
References System.Xml.Schema.XdrValidator._isProcessContents, System.Xml.Schema.XdrValidator._nsManager, System.Xml.Schema.SchemaElementDecl.ContentValidator, System.Xml.Schema.BaseValidator.context, System.Xml.Dictionary, System.Xml.Schema.ValidationState.ElementDecl, System.Xml.Schema.BaseValidator.elementName, System.Xml.Schema.ContentValidator.InitValidation(), System.Xml.XmlNamespaceManager.PopScope(), System.Xml.Schema.XdrValidator.Push(), System.Xml.Schema.XdrValidator.ThoroughGetElementDecl(), System.Xml.Schema.XdrValidator.ValidateEndStartElement(), and System.Xml.Schema.XdrValidator.ValidateStartElement().
Referenced by System.Xml.Schema.XdrValidator.ValidateElement().