Terraria: System.Xml.Schema.XdrValidator.Validate
Validate()
override void System.Xml.Schema.XdrValidator.Validate () inline virtual
Reimplemented from System.Xml.Schema.BaseValidator.
Definition at line 75 of file XdrValidator.cs.
    {
        if (IsInlineSchemaStarted)
        {
            ProcessInlineSchema();
            return;
        }
        switch (reader.NodeType)
        {
        case XmlNodeType.Element:
            ValidateElement();
            if (reader.IsEmptyElement)
            {
                goto case XmlNodeType.EndElement;
            }
            break;
        case XmlNodeType.Whitespace:
            ValidateWhitespace();
            break;
        case XmlNodeType.Text:
        case XmlNodeType.CDATA:
        case XmlNodeType.SignificantWhitespace:
            ValidateText();
            break;
        case XmlNodeType.EndElement:
            ValidateEndElement();
            break;
        }
    }
References System.Xml.XmlValidatingReaderImpl.IsEmptyElement, System.Xml.Schema.XdrValidator.IsInlineSchemaStarted, System.Xml.XmlValidatingReaderImpl.NodeType, System.Xml.Schema.XdrValidator.ProcessInlineSchema(), System.Xml.Schema.BaseValidator.reader, System.Xml.Schema.XdrValidator.ValidateElement(), System.Xml.Schema.XdrValidator.ValidateEndElement(), System.Xml.Schema.BaseValidator.ValidateText(), and System.Xml.Schema.BaseValidator.ValidateWhitespace().