Terraria: System.Xml.Schema.XdrValidator.ValidateEndElement
ValidateEndElement()
void System.Xml.Schema.XdrValidator.ValidateEndElement () inline private
Definition at line 174 of file XdrValidator.cs.
    {
        if (_isProcessContents)
        {
            _nsManager.PopScope();
        }
        if (context.ElementDecl != null)
        {
            if (context.NeedValidateChildren && !context.ElementDecl.ContentValidator.CompleteValidation(context))
            {
                XmlSchemaValidator.CompleteValidationError(context, base.EventHandler, reader, reader.BaseURI, base.PositionInfo.LineNumber, base.PositionInfo.LinePosition, null);
            }
            if (checkDatatype)
            {
                string value = ((!hasSibling) ? textString : textValue.ToString());
                CheckValue(value, null);
                checkDatatype = false;
                textValue.Length = 0;
                textString = string.Empty;
            }
        }
        Pop();
    }
References System.Xml.Schema.XdrValidator._isProcessContents, System.Xml.Schema.XdrValidator._nsManager, System.Xml.XmlValidatingReaderImpl.BaseURI, System.Xml.Schema.BaseValidator.checkDatatype, System.Xml.Schema.XdrValidator.CheckValue(), System.Xml.Schema.ContentValidator.CompleteValidation(), System.Xml.Schema.XmlSchemaValidator.CompleteValidationError(), System.Xml.Schema.SchemaElementDecl.ContentValidator, System.Xml.Schema.BaseValidator.context, System.Xml.Dictionary, System.Xml.Schema.ValidationState.ElementDecl, System.Xml.Schema.BaseValidator.hasSibling, System.Xml.Schema.ValidationState.NeedValidateChildren, System.Xml.Schema.XdrValidator.Pop(), System.Xml.XmlNamespaceManager.PopScope(), System.Xml.Schema.BaseValidator.reader, System.Xml.Schema.BaseValidator.textString, System.Xml.Schema.BaseValidator.textValue, System.Text.StringBuilder.ToString(), and System.value.
Referenced by System.Xml.Schema.XdrValidator.Validate().