Terraria: System.Xml.XmlDataDocument.GetRowFromElement
GetRowFromElement()
DataRow? System.Xml.XmlDataDocument.GetRowFromElement (XmlElement? e) inline
Definition at line 688 of file XmlDataDocument.cs.
    {
        return _mapper.GetRowFromElement(e);
    }
References System.Xml.XmlDataDocument._mapper, and System.Xml.DataSetMapper.GetRowFromElement().
Referenced by System.Xml.XmlDataDocument.EnsureNonRowDocumentElement(), System.Xml.XmlDataDocument.LoadRows(), System.Xml.XmlDataDocument.OnAddRow(), and System.Xml.XmlDataDocument.OnNestedParentChange().