Terraria: System.Xml.XmlDataDocument.GetColumnInsertAfterLocation
GetColumnInsertAfterLocation()
XmlNode System.Xml.XmlDataDocument.GetColumnInsertAfterLocation (DataRow row, DataColumn col, XmlBoundElement rowElement) inline private
Definition at line 618 of file XmlDataDocument.cs.
    {
        XmlNode result = null;
        XmlNode xmlNode = null;
        if (IsTextOnly(col))
        {
            return null;
        }
        xmlNode = rowElement.FirstChild;
        while (xmlNode != null && IsTextLikeNode(xmlNode))
        {
            result = xmlNode;
            xmlNode = xmlNode.NextSibling;
        }
        while (xmlNode != null && xmlNode.NodeType == XmlNodeType.Element)
        {
            XmlElement e = xmlNode as XmlElement;
            if (_mapper.GetRowFromElement(e) != null)
            {
                break;
            }
            object columnSchemaForNode = _mapper.GetColumnSchemaForNode(rowElement, xmlNode);
            if (columnSchemaForNode == null || !(columnSchemaForNode is DataColumn) || ((DataColumn)columnSchemaForNode).Ordinal > col.Ordinal)
            {
                break;
            }
            result = xmlNode;
            xmlNode = xmlNode.NextSibling;
        }
        return result;
    }
References System.Xml.XmlDataDocument._mapper, System.Xml.Dictionary, System.Xml.DataSetMapper.GetColumnSchemaForNode(), System.Xml.DataSetMapper.GetRowFromElement(), System.Xml.XmlDataDocument.IsTextLikeNode(), System.Xml.XmlDataDocument.IsTextOnly(), and System.Ordinal.
Referenced by System.Xml.XmlDataDocument.OnColumnValueChanged().