Terraria: System.Xml.XmlDataDocument.OnUndeleteRow
OnUndeleteRow()
void System.Xml.XmlDataDocument.OnUndeleteRow (DataRow row, XmlElement rowElement) inline private
Definition at line 1799 of file XmlDataDocument.cs.
    {
        if (rowElement.ParentNode != null)
        {
            rowElement.ParentNode.RemoveChild(rowElement);
        }
        DataRow nestedParent = GetNestedParent(row);
        XmlElement xmlElement = ((nestedParent != null) ? GetElementFromRow(nestedParent) : EnsureNonRowDocumentElement());
        XmlNode rowInsertBeforeLocation;
        if ((rowInsertBeforeLocation = GetRowInsertBeforeLocation(row, rowElement, xmlElement)) != null)
        {
            xmlElement.InsertBefore(rowElement, rowInsertBeforeLocation);
        }
        else
        {
            xmlElement.AppendChild(rowElement);
        }
        FixNestedChildren(row, rowElement);
    }
References System.Xml.Dictionary, System.Xml.XmlDataDocument.EnsureNonRowDocumentElement(), System.Xml.XmlDataDocument.FixNestedChildren(), System.Xml.XmlDataDocument.GetElementFromRow(), System.Xml.XmlDataDocument.GetNestedParent(), and System.Xml.XmlDataDocument.GetRowInsertBeforeLocation().
Referenced by System.Xml.XmlDataDocument.OnRowChanged().