Terraria: System.Xml.XmlDataDocument.SyncRows
SyncRows()
void System.Xml.XmlDataDocument.SyncRows (DataRow parentRow, XmlNode node, bool fAddRowsToTable) inline package
Definition at line 147 of file XmlDataDocument.cs.
    {
        if (node is XmlBoundElement { Row: var row } xmlBoundElement)
        {
            if (row != null && xmlBoundElement.ElementState == ElementState.Defoliated)
            {
                return;
            }
            if (row != null)
            {
                SynchronizeRowFromRowElement(xmlBoundElement);
                xmlBoundElement.ElementState = ElementState.WeakFoliation;
                DefoliateRegion(xmlBoundElement);
                if (parentRow != null)
                {
                    SetNestedParentRow(row, parentRow);
                }
                if (fAddRowsToTable && row.RowState == DataRowState.Detached)
                {
                    row.Table.Rows.Add(row);
                }
                parentRow = row;
            }
        }
        for (XmlNode xmlNode = node.FirstChild; xmlNode != null; xmlNode = xmlNode.NextSibling)
        {
            SyncRows(parentRow, xmlNode, fAddRowsToTable);
        }
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Xml.XmlDataDocument.DefoliateRegion(), System.Xml.Dictionary, System.Xml.XmlDataDocument.SetNestedParentRow(), System.Xml.XmlDataDocument.SynchronizeRowFromRowElement(), and System.Xml.XmlDataDocument.SyncRows().
Referenced by System.Xml.XmlDataDocument.CloneTree(), System.Xml.XmlDataDocument.LoadDataSetFromTree(), System.Xml.XmlDataDocument.SyncRows(), and System.Xml.XmlDataDocument.SyncTree().