Terraria: System.Xml.XmlDataDocument.ForceFoliation
ForceFoliation()
void System.Xml.XmlDataDocument.ForceFoliation (XmlBoundElement node, ElementState newState) inline private
Definition at line 534 of file XmlDataDocument.cs.
    {
        lock (_foliationLock)
        {
            if (node.ElementState != ElementState.Defoliated)
            {
                return;
            }
            node.ElementState = ElementState.Foliating;
            bool ignoreXmlEvents = IgnoreXmlEvents;
            IgnoreXmlEvents = true;
            try
            {
                XmlNode xmlNode = null;
                DataRow row = node.Row;
                DataRowVersion version = ((row.RowState == DataRowState.Detached) ? DataRowVersion.Proposed : DataRowVersion.Current);
                foreach (DataColumn column in row.Table.Columns)
                {
                    if (IsNotMapped(column))
                    {
                        continue;
                    }
                    object value = row[column, version];
                    if (!Convert.IsDBNull(value))
                    {
                        if (column.ColumnMapping == MappingType.Attribute)
{
                            node.SetAttribute(column.EncodedColumnName, column.Namespace, column.ConvertObjectToXml(value));
                            continue;
                        }
                        XmlNode xmlNode2 = null;
                        if (column.ColumnMapping == MappingType.Element)
{
                            xmlNode2 = new XmlBoundElement(string.Empty, column.EncodedColumnName, column.Namespace, this);
                            xmlNode2.AppendChild(CreateTextNode(column.ConvertObjectToXml(value)));
                            if (xmlNode != null)
{
                                node.InsertAfter(xmlNode2, xmlNode);
                            }
                            else if (node.FirstChild != null)
{
                                node.InsertBefore(xmlNode2, node.FirstChild);
                            }
                            else
{
                                node.AppendChild(xmlNode2);
                            }
                            xmlNode = xmlNode2;
                        }
                        else
{
                            xmlNode2 = CreateTextNode(column.ConvertObjectToXml(value));
                            if (node.FirstChild != null)
{
                                node.InsertBefore(xmlNode2, node.FirstChild);
                            }
                            else
{
                                node.AppendChild(xmlNode2);
                            }
                            if (xmlNode == null)
{
                                xmlNode = xmlNode2;
                            }
                        }
                    }
                    else if (column.ColumnMapping == MappingType.SimpleContent)
                    {
                        XmlAttribute xmlAttribute = CreateAttribute("xsi", "nil", "http://www.w3.org/2001/XMLSchema-instance");
                        xmlAttribute.Value = "true";
                        node.SetAttributeNode(xmlAttribute);
                        _bHasXSINIL = true;
                    }
                }
            }
            finally
            {
                IgnoreXmlEvents = ignoreXmlEvents;
                node.ElementState = newState;
            }
            OnFoliated(node);
        }
    }
References System.Xml.XmlDataDocument._bHasXSINIL, System.Xml.XmlDataDocument._foliationLock, System.Xml.XmlDocument.CreateAttribute(), System.Xml.XmlDocument.CreateTextNode(), System.Xml.Dictionary, System.Xml.XmlDataDocument.IgnoreXmlEvents, System.Convert.IsDBNull(), System.Xml.XmlDataDocument.IsNotMapped(), System.Xml.XmlDataDocument.OnFoliated(), and System.value.
Referenced by System.Xml.XmlDataDocument.EnsureFoliation(), System.Xml.XmlDataDocument.Foliate(), System.Xml.XmlDataDocument.OnAddRow(), and System.Xml.XmlDataDocument.OnColumnValueChanged().