Terraria: System.Xml.XmlDataDocument.BindForLoad
BindForLoad()
void System.Xml.XmlDataDocument.BindForLoad () inline private
Definition at line 213 of file XmlDataDocument.cs.
    {
        _ignoreDataSetEvents = true;
        _mapper.SetupMapping(this, _dataSet);
        if (_dataSet.Tables.Count > 0)
        {
            LoadDataSetFromTree();
        }
        BindListeners();
        _ignoreDataSetEvents = false;
    }
References System.Xml.XmlDataDocument._dataSet, System.Xml.XmlDataDocument._ignoreDataSetEvents, System.Xml.XmlDataDocument._mapper, System.Xml.XmlDataDocument.BindListeners(), System.Data.InternalDataCollectionBase.Count, System.Xml.XmlDataDocument.LoadDataSetFromTree(), System.Xml.DataSetMapper.SetupMapping(), and System.Data.DataSet.Tables.
Referenced by System.Xml.XmlDataDocument.Load().