Terraria: System.Xml.XmlDataDocument.CloneNode
CloneNode() [1/2]
override XmlNode System.Xml.XmlDataDocument.CloneNode (bool deep) inline
Definition at line 826 of file XmlDataDocument.cs.
    {
        XmlDataDocument xmlDataDocument = (XmlDataDocument)base.CloneNode(deep: false);
        xmlDataDocument.Init(DataSet.Clone());
        xmlDataDocument._dataSet.EnforceConstraints = _dataSet.EnforceConstraints;
        if (deep)
        {
            DataPointer dataPointer = new DataPointer(this, this);
            try
            {
                dataPointer.AddPointer();
                bool flag = dataPointer.MoveToFirstChild();
                while (flag)
                {
                    XmlNode newChild = ((dataPointer.NodeType != XmlNodeType.Element) ? xmlDataDocument.CloneNode(dataPointer) : xmlDataDocument.CloneTree(dataPointer));
                    xmlDataDocument.AppendChild(newChild);
                    flag = dataPointer.MoveToNextSibling();
                }
            }
            finally
            {
                dataPointer.SetNoLongerUse();
            }
        }
        return xmlDataDocument;
    }
References System.Xml.XmlDataDocument.XmlDataDocument(), System.Xml.XmlDataDocument._dataSet, System.Data.DataSet.Clone(), System.Xml.Dictionary, and System.Data.DataSet.EnforceConstraints.
Referenced by System.Xml.XmlDataDocument.CloneTreeInternal().