Terraria: System.Xml.XmlDataDocument.OnNodeRemoved
OnNodeRemoved()
void System.Xml.XmlDataDocument.OnNodeRemoved (object sender, XmlNodeChangedEventArgs args) inline private
Definition at line 1499 of file XmlDataDocument.cs.
    {
        if (_ignoreXmlEvents)
        {
            return;
        }
        bool ignoreDataSetEvents = _ignoreDataSetEvents;
        bool ignoreXmlEvents = _ignoreXmlEvents;
        bool isFoliationEnabled = IsFoliationEnabled;
        _ignoreDataSetEvents = true;
        _ignoreXmlEvents = true;
        IsFoliationEnabled = false;
        bool fEnableCascading = DataSet._fEnableCascading;
        DataSet._fEnableCascading = false;
        try
        {
            XmlNode node = args.Node;
            XmlNode oldParent = args.OldParent;
            if (IsConnected(oldParent))
            {
                OnNodeRemovedFromTree(node, oldParent);
            }
            else
            {
                OnNodeRemovedFromFragment(node, oldParent);
            }
        }
        finally
        {
            _ignoreDataSetEvents = ignoreDataSetEvents;
            _ignoreXmlEvents = ignoreXmlEvents;
            IsFoliationEnabled = isFoliationEnabled;
            DataSet._fEnableCascading = fEnableCascading;
        }
    }
References System.Data.DataSet._fEnableCascading, System.Xml.XmlDataDocument._ignoreDataSetEvents, System.Xml.XmlDataDocument._ignoreXmlEvents, System.Xml.Dictionary, System.Xml.XmlNode.IsConnected(), System.Xml.XmlDataDocument.IsFoliationEnabled, System.Xml.XmlDataDocument.OnNodeRemovedFromFragment(), and System.Xml.XmlDataDocument.OnNodeRemovedFromTree().
Referenced by System.Xml.XmlDataDocument.BindToDocument().