Terraria: System.Xml.XmlDataDocument.OnNestedParentChange
OnNestedParentChange()
void System.Xml.XmlDataDocument.OnNestedParentChange (DataRow child, XmlBoundElement childElement, DataColumn childCol) inline private
Definition at line 1382 of file XmlDataDocument.cs.
    {
        DataRow dataRow = ((childElement != base.DocumentElement && childElement.ParentNode != null) ? GetRowFromElement((XmlElement)childElement.ParentNode) : null);
        DataRow nestedParent = GetNestedParent(child);
        if (dataRow == nestedParent)
        {
            return;
        }
        if (nestedParent != null)
        {
            XmlElement elementFromRow = GetElementFromRow(nestedParent);
            elementFromRow.AppendChild(childElement);
            return;
        }
        DataRelation nestedParentRelation = GetNestedParentRelation(child);
        if (childCol == null || nestedParentRelation == null || Convert.IsDBNull(child[childCol]))
        {
            EnsureNonRowDocumentElement().AppendChild(childElement);
            return;
        }
        DataColumn dataColumn = FindAssociatedParentColumn(nestedParentRelation, childCol);
        object value = dataColumn.ConvertValue(child[childCol]);
        if (dataRow._tempRecord != -1 && dataColumn.CompareValueTo(dataRow._tempRecord, value) != 0)
        {
            EnsureNonRowDocumentElement().AppendChild(childElement);
        }
    }
References System.Xml.XmlNode.AppendChild(), System.Xml.Dictionary, System.Xml.XmlDataDocument.EnsureNonRowDocumentElement(), System.Xml.XmlDataDocument.FindAssociatedParentColumn(), System.Xml.XmlDataDocument.GetElementFromRow(), System.Xml.XmlDataDocument.GetNestedParent(), System.Xml.XmlDataDocument.GetNestedParentRelation(), System.Xml.XmlDataDocument.GetRowFromElement(), System.Convert.IsDBNull(), and System.value.
Referenced by System.Xml.XmlDataDocument.OnAddRow(), and System.Xml.XmlDataDocument.OnColumnValueChanged().