Terraria: System.Xml.XmlDataDocument.SynchronizeRowFromRowElementEx
SynchronizeRowFromRowElementEx()
void System.Xml.XmlDataDocument.SynchronizeRowFromRowElementEx (XmlBoundElement rowElement, ArrayList rowElemList) inline private
Definition at line 1972 of file XmlDataDocument.cs.
    {
        DataRow row = rowElement.Row;
        Hashtable hashtable = new Hashtable();
        string empty = string.Empty;
        RegionIterator regionIterator = new RegionIterator(rowElement);
        DataColumn textOnlyColumn = GetTextOnlyColumn(row);
        bool flag;
        if (textOnlyColumn != null)
        {
            hashtable[textOnlyColumn] = textOnlyColumn;
            flag = regionIterator.NextInitialTextLikeNodes(out var value);
            if (value.Length == 0 && ((empty = rowElement.GetAttribute("xsi:nil")) == "1" || empty == "true"))
            {
                row[textOnlyColumn] = DBNull.Value;
            }
            else
            {
                SetRowValueFromXmlText(row, textOnlyColumn, value);
            }
        }
        else
        {
            flag = regionIterator.Next();
        }
        while (flag)
        {
            if (!(regionIterator.CurrentNode is XmlElement xmlElement))
            {
                flag = regionIterator.Next();
                continue;
            }
            if (xmlElement is XmlBoundElement { Row: not null })
            {
                rowElemList?.Add(xmlElement);
                flag = regionIterator.NextRight();
                continue;
            }
            DataColumn columnSchemaForNode = _mapper.GetColumnSchemaForNode(rowElement, xmlElement);
            if (columnSchemaForNode != null && hashtable[columnSchemaForNode] == null)
            {
                hashtable[columnSchemaForNode] = columnSchemaForNode;
                flag = regionIterator.NextInitialTextLikeNodes(out var value2);
                if (value2.Length == 0 && ((empty = xmlElement.GetAttribute("xsi:nil")) == "1" || empty == "true"))
                {
                    row[columnSchemaForNode] = DBNull.Value;
                }
                else
                {
                    SetRowValueFromXmlText(row, columnSchemaForNode, value2);
                }
            }
            else
            {
                flag = regionIterator.Next();
            }
        }
        foreach (XmlAttribute attribute in rowElement.Attributes)
        {
            DataColumn columnSchemaForNode2 = _mapper.GetColumnSchemaForNode(rowElement, attribute);
            if (columnSchemaForNode2 != null && hashtable[columnSchemaForNode2] == null)
            {
                hashtable[columnSchemaForNode2] = columnSchemaForNode2;
                SetRowValueFromXmlText(row, columnSchemaForNode2, attribute.Value);
            }
        }
        foreach (DataColumn column in row.Table.Columns)
        {
            if (hashtable[column] == null && !IsNotMapped(column))
            {
                if (!column.AutoIncrement)
                {
                    SetRowValueToNull(row, column);
                }
                else
                {
                    column.Init(row._tempRecord);
                }
            }
        }
    }
References System.Xml.XmlDataDocument._mapper, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Xml.Dictionary, System.Xml.DataSetMapper.GetColumnSchemaForNode(), System.Xml.XmlDataDocument.GetTextOnlyColumn(), System.Xml.XmlDataDocument.IsNotMapped(), System.Xml.XmlDataDocument.SetRowValueFromXmlText(), System.Xml.XmlDataDocument.SetRowValueToNull(), System.DBNull.Value, and System.value.
Referenced by System.Xml.XmlDataDocument.OnNonRowElementInsertedInFragment(), and System.Xml.XmlDataDocument.SynchronizeRowFromRowElement().