Terraria: DesertDescription.CreateFromPlacement
CreateFromPlacement()
static DesertDescription DesertDescription.CreateFromPlacement (Point origin) inline static
     {
         //IL_0000: Unknown result type (might be due to invalid IL or missing references)
         //IL_0005: Unknown result type (might be due to invalid IL or missing references)
         //IL_0064: Unknown result type (might be due to invalid IL or missing references)
         //IL_0070: Unknown result type (might be due to invalid IL or missing references)
         //IL_016e: Unknown result type (might be due to invalid IL or missing references)
         Vector2D defaultBlockScale = DefaultBlockScale;
         double num = (double)Main.maxTilesX / 4200.0;
         int num2 = (int)(80.0 * num);
         int num3 = (int)((WorldGen.genRand.NextDouble() * 0.5 + 1.5) * 170.0 * num);
         if (WorldGen.remixWorldGen)
         {
             num3 = (int)(340.0 * num);
         }
         int num4 = (int)(defaultBlockScale.X * (double)num2);
         int num5 = (int)(defaultBlockScale.Y * (double)num3);
         origin.X -= num4 / 2;
         SurfaceMap surfaceMap = SurfaceMap.FromArea(origin.X - 5, num4 + 10);
         if (RowHasInvalidTiles(origin.X, surfaceMap.Bottom, num4))
         {
             return Invalid;
         }
         int num6 = (int)(surfaceMap.Average + (double)surfaceMap.Bottom) / 2;
         origin.Y = num6 + WorldGen.genRand.Next(40, 60);
         int num7 = 0;
         if (Main.tenthAnniversaryWorld)
         {
             num7 = (int)(20.0 * num);
         }
         return new DesertDescription
         {
             CombinedArea = new Rectangle(origin.X, num6, num4, origin.Y + num5 - num6),
             Hive = new Rectangle(origin.X, origin.Y + num7, num4, num5 - num7),
             Desert = new Rectangle(origin.X, num6, num4, origin.Y + num5 / 2 - num6 + num7),
             BlockScale = defaultBlockScale,
             BlockColumnCount = num2,
             BlockRowCount = num3,
             Surface = surfaceMap,
             IsValid = true
         };
     }
References SurfaceMap.Average, BlockColumnCount, BlockRowCount, BlockScale, SurfaceMap.Bottom, CombinedArea, DefaultBlockScale, Desert, SurfaceMap.FromArea(), WorldGen.genRand, Hive, Invalid, IsValid, Main.maxTilesX, UnifiedRandom.Next(), UnifiedRandom.NextDouble(), WorldGen.remixWorldGen, RowHasInvalidTiles(), Surface, Main.tenthAnniversaryWorld, Vector2D.X, and Vector2D.Y.
Referenced by DesertBiome.Place().