Terraria: System.Xml.XmlDataDocument.SetRowValueFromXmlText
SetRowValueFromXmlText()
static void System.Xml.XmlDataDocument.SetRowValueFromXmlText (DataRow row, DataColumn col, string xmlText) inline static package
Definition at line 1935 of file XmlDataDocument.cs.
    {
        object obj;
        try
        {
            obj = col.ConvertXmlToObject(xmlText);
        }
        catch (Exception e) when (ADP.IsCatchableExceptionType(e))
        {
            SetRowValueToNull(row, col);
            return;
        }
        if (!obj.Equals(row[col]))
        {
            row[col] = obj;
        }
    }
References System.Xml.Dictionary, System.Data.Common.ADP.IsCatchableExceptionType(), System.obj, and System.Xml.XmlDataDocument.SetRowValueToNull().
Referenced by System.Xml.XmlDataDocument.SynchronizeRowFromRowElementEx().