Terraria: System.Xml.XmlDataDocument.BindToDocument
BindToDocument()
void System.Xml.XmlDataDocument.BindToDocument () inline private
Definition at line 304 of file XmlDataDocument.cs.
    {
        if (!_fBoundToDocument)
        {
            base.NodeInserting += OnNodeInserting;
            base.NodeInserted += OnNodeInserted;
            base.NodeRemoving += OnNodeRemoving;
            base.NodeRemoved += OnNodeRemoved;
            base.NodeChanging += OnNodeChanging;
            base.NodeChanged += OnNodeChanged;
            _fBoundToDocument = true;
        }
    }
References System.Xml.XmlDataDocument._fBoundToDocument, System.Xml.Dictionary, System.Xml.XmlDataDocument.OnNodeChanged(), System.Xml.XmlDataDocument.OnNodeChanging(), System.Xml.XmlDataDocument.OnNodeInserted(), System.Xml.XmlDataDocument.OnNodeInserting(), System.Xml.XmlDataDocument.OnNodeRemoved(), and System.Xml.XmlDataDocument.OnNodeRemoving().
Referenced by System.Xml.XmlDataDocument.BindListeners().