Terraria: System.Xml.XmlDataDocument.BindToTable
BindToTable()
void System.Xml.XmlDataDocument.BindToTable (DataTable t) inline private
Definition at line 319 of file XmlDataDocument.cs.
    {
        t.ColumnChanged += OnColumnChanged;
        t.RowChanging += OnRowChanging;
        t.RowChanged += OnRowChanged;
        t.RowDeleting += OnRowChanging;
        t.RowDeleted += OnRowChanged;
        t.PropertyChanging += OnTablePropertyChanging;
        t.Columns.CollectionChanging += OnTableColumnsChanging;
        foreach (DataColumn column in t.Columns)
        {
            column.PropertyChanging += OnColumnPropertyChanging;
        }
    }
References System.Xml.Dictionary, System.Xml.XmlDataDocument.OnColumnChanged(), System.Xml.XmlDataDocument.OnColumnPropertyChanging(), System.Xml.XmlDataDocument.OnRowChanged(), System.Xml.XmlDataDocument.OnRowChanging(), System.Xml.XmlDataDocument.OnTableColumnsChanging(), and System.Xml.XmlDataDocument.OnTablePropertyChanging().
Referenced by System.Xml.XmlDataDocument.BindToDataSet().