Terraria: System.Xml.XmlDataDocument.PromoteInnerRegions
PromoteInnerRegions()
void System.Xml.XmlDataDocument.PromoteInnerRegions (XmlNode parent) inline private
Definition at line 1829 of file XmlDataDocument.cs.
    {
        _mapper.GetRegion(parent.ParentNode, out var rowElem);
        TreeIterator treeIterator = new TreeIterator(parent);
        bool flag = treeIterator.NextRowElement();
        while (flag)
        {
            XmlBoundElement xmlBoundElement = (XmlBoundElement)treeIterator.CurrentNode;
            flag = treeIterator.NextRightRowElement();
            PromoteChild(xmlBoundElement, parent);
            SetNestedParentRegion(xmlBoundElement, rowElem);
        }
    }
References System.Xml.XmlDataDocument._mapper, System.Xml.DataSetMapper.GetRegion(), System.Xml.XmlNode.ParentNode, System.Xml.XmlDataDocument.PromoteChild(), and System.Xml.XmlDataDocument.SetNestedParentRegion().
Referenced by System.Xml.XmlDataDocument.OnDeleteRow().