Terraria: System.Xml.XmlDataDocument.EnsurePopulatedMode
EnsurePopulatedMode()
void System.Xml.XmlDataDocument.EnsurePopulatedMode () inline private
Definition at line 453 of file XmlDataDocument.cs.
    {
        if (_fDataRowCreatedSpecial)
        {
            UnBindSpecialListeners();
            _mapper.SetupMapping(this, _dataSet);
            BindListeners();
            _fAssociateDataRow = true;
        }
    }
References System.Xml.XmlDataDocument._dataSet, System.Xml.XmlDataDocument._fAssociateDataRow, System.Xml.XmlDataDocument._fDataRowCreatedSpecial, System.Xml.XmlDataDocument._mapper, System.Xml.XmlDataDocument.BindListeners(), System.Xml.DataSetMapper.SetupMapping(), and System.Xml.XmlDataDocument.UnBindSpecialListeners().
Referenced by System.Xml.XmlDataDocument.CloneTree(), and System.Xml.XmlDataDocument.CreateElement().