Terraria: System.Xml.XmlDataDocument.SyncTree
SyncTree()
void System.Xml.XmlDataDocument.SyncTree (XmlNode node) inline package
Definition at line 178 of file XmlDataDocument.cs.
    {
        XmlBoundElement rowElem = null;
        _mapper.GetRegion(node, out rowElem);
        DataRow parentRow = null;
        bool flag = IsConnected(node);
        if (rowElem != null)
        {
            DataRow row = rowElem.Row;
            if (row != null && rowElem.ElementState == ElementState.Defoliated)
            {
                return;
            }
            if (row != null)
            {
                SynchronizeRowFromRowElement(rowElem);
                if (node == rowElem)
                {
                    rowElem.ElementState = ElementState.WeakFoliation;
                    DefoliateRegion(rowElem);
                }
                if (flag && row.RowState == DataRowState.Detached)
                {
                    row.Table.Rows.Add(row);
                }
                parentRow = row;
            }
        }
        for (XmlNode xmlNode = node.FirstChild; xmlNode != null; xmlNode = xmlNode.NextSibling)
        {
            SyncRows(parentRow, xmlNode, flag);
        }
    }
References System.Xml.XmlDataDocument._mapper, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Xml.XmlDataDocument.DefoliateRegion(), System.Xml.Dictionary, System.Xml.DataSetMapper.GetRegion(), System.Xml.XmlNode.IsConnected(), System.Xml.XmlDataDocument.SynchronizeRowFromRowElement(), and System.Xml.XmlDataDocument.SyncRows().