Terraria: System.Xml.XmlDataDocument.ReplaceInitialChildText
ReplaceInitialChildText()
void System.Xml.XmlDataDocument.ReplaceInitialChildText (XmlNode parent, string value) inline private
Definition at line 1873 of file XmlDataDocument.cs.
    {
        XmlNode xmlNode = parent.FirstChild;
        while (xmlNode != null && xmlNode.NodeType == XmlNodeType.Whitespace)
        {
            xmlNode = xmlNode.NextSibling;
        }
        if (xmlNode != null)
        {
            if (xmlNode.NodeType == XmlNodeType.Text)
            {
                xmlNode.Value = value;
            }
            else
            {
                xmlNode = parent.InsertBefore(CreateTextNode(value), xmlNode);
            }
            RemoveInitialTextNodes(xmlNode.NextSibling);
        }
        else
        {
            parent.AppendChild(CreateTextNode(value));
        }
    }
References System.Xml.XmlNode.AppendChild(), System.Xml.XmlDocument.CreateTextNode(), System.Xml.Dictionary, System.Xml.XmlNode.FirstChild, System.Xml.XmlNode.InsertBefore(), System.Xml.XmlDataDocument.RemoveInitialTextNodes(), and System.value.
Referenced by System.Xml.XmlDataDocument.OnColumnValueChanged().