Terraria: System.Xml.XmlDataDocument.SetNestedParentRow
SetNestedParentRow()
static void System.Xml.XmlDataDocument.SetNestedParentRow (DataRow childRow, DataRow parentRow) inline static private
Definition at line 2156 of file XmlDataDocument.cs.
    {
        DataRelation nestedParentRelation = GetNestedParentRelation(childRow);
        if (nestedParentRelation != null)
        {
            if (parentRow == null || nestedParentRelation.ParentKey.Table != parentRow.Table)
            {
                childRow.SetParentRow(null, nestedParentRelation);
            }
            else
            {
                childRow.SetParentRow(parentRow, nestedParentRelation);
            }
        }
    }
References System.Xml.XmlDataDocument.GetNestedParentRelation().
Referenced by System.Xml.XmlDataDocument.SetNestedParentRegion(), and System.Xml.XmlDataDocument.SyncRows().