Terraria: System.Xml.XmlDataDocument.BindToDataSet
BindToDataSet()
void System.Xml.XmlDataDocument.BindToDataSet () inline private
Definition at line 274 of file XmlDataDocument.cs.
    {
        if (_fBoundToDataSet)
        {
            return;
        }
        if (_fDataRowCreatedSpecial)
        {
            UnBindSpecialListeners();
        }
        _dataSet.Tables.CollectionChanging += OnDataSetTablesChanging;
        _dataSet.Relations.CollectionChanging += OnDataSetRelationsChanging;
        _dataSet.DataRowCreated += OnDataRowCreated;
        _dataSet.PropertyChanging += OnDataSetPropertyChanging;
        _dataSet.ClearFunctionCalled += OnClearCalled;
        if (_dataSet.Tables.Count > 0)
        {
            foreach (DataTable table in _dataSet.Tables)
            {
                BindToTable(table);
            }
        }
        foreach (DataRelation relation in _dataSet.Relations)
        {
            relation.PropertyChanging += OnRelationPropertyChanging;
        }
        _fBoundToDataSet = true;
    }
References System.Xml.XmlDataDocument._dataSet, System.Xml.XmlDataDocument._fBoundToDataSet, System.Xml.XmlDataDocument._fDataRowCreatedSpecial, System.Xml.XmlDataDocument.BindToTable(), System.Data.InternalDataCollectionBase.Count, System.Xml.Dictionary, System.Xml.XmlDataDocument.OnClearCalled(), System.Xml.XmlDataDocument.OnDataRowCreated(), System.Xml.XmlDataDocument.OnDataSetPropertyChanging(), System.Xml.XmlDataDocument.OnDataSetRelationsChanging(), System.Xml.XmlDataDocument.OnDataSetTablesChanging(), System.Xml.XmlDataDocument.OnRelationPropertyChanging(), System.Data.DataSet.Relations, System.Data.DataSet.Tables, and System.Xml.XmlDataDocument.UnBindSpecialListeners().
Referenced by System.Xml.XmlDataDocument.BindListeners().