Terraria: System.Xml.XmlDataDocument.GetRowInsertBeforeLocation
GetRowInsertBeforeLocation()
XmlNode System.Xml.XmlDataDocument.GetRowInsertBeforeLocation (DataRow row, XmlElement rowElement, XmlNode parentElement) inline private
Definition at line 693 of file XmlDataDocument.cs.
    {
        DataRow dataRow = row;
        int num = 0;
        for (num = 0; num < row.Table.Rows.Count && row != row.Table.Rows[num]; num++)
        {
        }
        int num2 = num;
        DataRow nestedParent = GetNestedParent(row);
        for (num = num2 + 1; num < row.Table.Rows.Count; num++)
        {
            dataRow = row.Table.Rows[num];
            if (GetNestedParent(dataRow) == nestedParent && GetElementFromRow(dataRow).ParentNode == parentElement)
            {
                break;
            }
        }
        if (num < row.Table.Rows.Count)
        {
            return GetElementFromRow(dataRow);
        }
        return null;
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Xml.Dictionary, System.Xml.XmlDataDocument.GetElementFromRow(), System.Xml.XmlDataDocument.GetNestedParent(), and System.Xml.XmlDocument.ParentNode.
Referenced by System.Xml.XmlDataDocument.OnUndeleteRow().