Terraria: System.Xml.XmlDataDocument.OnColumnValuesChanged
OnColumnValuesChanged()
void System.Xml.XmlDataDocument.OnColumnValuesChanged (DataRow row, XmlBoundElement rowElement) inline private
Definition at line 1283 of file XmlDataDocument.cs.
    {
        if (_columnChangeList.Count > 0)
        {
            if (((DataColumn)_columnChangeList[0]).Table == row.Table)
            {
                foreach (DataColumn columnChange in _columnChangeList)
                {
                    OnColumnValueChanged(row, columnChange, rowElement);
                }
            }
            else
            {
                foreach (DataColumn column in row.Table.Columns)
                {
                    OnColumnValueChanged(row, column, rowElement);
                }
            }
        }
        else
        {
            foreach (DataColumn column2 in row.Table.Columns)
            {
                OnColumnValueChanged(row, column2, rowElement);
            }
        }
        _columnChangeList.Clear();
    }
References System.Xml.XmlDataDocument._columnChangeList, System.Collections.ArrayList.Clear(), System.Collections.ArrayList.Count, and System.Xml.XmlDataDocument.OnColumnValueChanged().
Referenced by System.Xml.XmlDataDocument.OnRowChanged().