Terraria: System.Xml.XmlDataDocument.LoadTreeFromDataSet
LoadTreeFromDataSet()
void System.Xml.XmlDataDocument.LoadTreeFromDataSet (DataSet ds) inline private
Definition at line 986 of file XmlDataDocument.cs.
    {
        _ignoreDataSetEvents = true;
        _ignoreXmlEvents = true;
        bool isFoliationEnabled = IsFoliationEnabled;
        IsFoliationEnabled = false;
        _fAssociateDataRow = false;
        DataTable[] array = OrderTables(ds);
        try
        {
            foreach (DataTable dataTable in array)
            {
                foreach (DataRow row in dataTable.Rows)
                {
                    AttachBoundElementToDataRow(row);
                    switch (row.RowState)
                    {
                    case DataRowState.Unchanged:
                    case DataRowState.Added:
                    case DataRowState.Modified:
                        OnAddRow(row);
                        break;
                    }
                }
            }
        }
        finally
        {
            _ignoreDataSetEvents = false;
            _ignoreXmlEvents = false;
            IsFoliationEnabled = isFoliationEnabled;
            _fAssociateDataRow = true;
        }
    }
References System.Xml.XmlDataDocument._fAssociateDataRow, System.Xml.XmlDataDocument._ignoreDataSetEvents, System.Xml.XmlDataDocument._ignoreXmlEvents, System.array, System.Xml.XmlDataDocument.AttachBoundElementToDataRow(), System.Xml.Dictionary, System.Xml.XmlDataDocument.IsFoliationEnabled, System.Xml.XmlDataDocument.OnAddRow(), and System.Xml.XmlDataDocument.OrderTables().
Referenced by System.Xml.XmlDataDocument.Bind().