Terraria: System.Xml.XmlDataDocument.Init
Init() [1/2]
void System.Xml.XmlDataDocument.Init () inline private
Definition at line 2096 of file XmlDataDocument.cs.
    {
        _pointers = new Hashtable();
        _countAddPointer = 0;
        _columnChangeList = new ArrayList();
        _ignoreDataSetEvents = false;
        _isFoliationEnabled = true;
        _optimizeStorage = true;
        _fDataRowCreatedSpecial = false;
        _autoFoliationState = ElementState.StrongFoliation;
        _fAssociateDataRow = true;
        _mapper = new DataSetMapper();
        _foliationLock = new object();
        _ignoreXmlEvents = true;
        _attrXml = CreateAttribute("xmlns", "xml", "http://www.w3.org/2000/xmlns/");
        _attrXml.Value = "http://www.w3.org/XML/1998/namespace";
        _ignoreXmlEvents = false;
    }
References System.Xml.XmlDataDocument._attrXml, System.Xml.XmlDataDocument._autoFoliationState, System.Xml.XmlDataDocument._columnChangeList, System.Xml.XmlDataDocument._countAddPointer, System.Xml.XmlDataDocument._fAssociateDataRow, System.Xml.XmlDataDocument._fDataRowCreatedSpecial, System.Xml.XmlDataDocument._foliationLock, System.Xml.XmlDataDocument._ignoreDataSetEvents, System.Xml.XmlDataDocument._ignoreXmlEvents, System.Xml.XmlDataDocument._isFoliationEnabled, System.Xml.XmlDataDocument._mapper, System.Xml.XmlDataDocument._optimizeStorage, System.Xml.XmlDataDocument._pointers, System.Xml.XmlDocument.CreateAttribute(), and System.Xml.Dictionary.
Referenced by System.Xml.XmlDataDocument.XmlDataDocument(), System.Xml.XmlDataDocument.XmlDataDocument(), and System.Xml.XmlDataDocument.Init().