Terraria: System.Xml.XmlDataDocument.OnRowChanging
OnRowChanging()
void System.Xml.XmlDataDocument.OnRowChanging (object sender, DataRowChangeEventArgs args) inline private
Definition at line 1647 of file XmlDataDocument.cs.
    {
        DataRow row = args.Row;
        if (args.Action == DataRowAction.Delete && row.Element != null)
        {
            OnDeletingRow(row, row.Element);
        }
        else
        {
            if (_ignoreDataSetEvents)
            {
                return;
            }
            bool isFoliationEnabled = IsFoliationEnabled;
            IsFoliationEnabled = false;
            try
            {
                _ignoreXmlEvents = true;
                XmlElement elementFromRow = GetElementFromRow(row);
                int num = -1;
                int num2 = -1;
                if (elementFromRow == null)
                {
                    return;
                }
                switch (args.Action)
                {
                case DataRowAction.Rollback:
                    _rollbackState = row.RowState;
                    switch (_rollbackState)
                    {
                    case DataRowState.Modified:
                        _columnChangeList.Clear();
                        num = row.GetRecordFromVersion(DataRowVersion.Original);
                        num2 = row.GetRecordFromVersion(DataRowVersion.Current);
{
                            foreach (DataColumn column in row.Table.Columns)
{
                                if (!IsSame(column, num, num2))
{
                                    _columnChangeList.Add(column);
                                }
                            }
                            break;
                        }
                    }
                    break;
                case DataRowAction.Change:
                    _columnChangeList.Clear();
                    num = row.GetRecordFromVersion(DataRowVersion.Proposed);
                    num2 = row.GetRecordFromVersion(DataRowVersion.Current);
                    {
                        foreach (DataColumn column2 in row.Table.Columns)
{
                            object value = row[column2, DataRowVersion.Proposed];
                            object value2 = row[column2, DataRowVersion.Current];
                            if (Convert.IsDBNull(value) && !Convert.IsDBNull(value2) && column2.ColumnMapping != MappingType.Hidden)
{
                                FoliateIfDataPointers(row, elementFromRow);
                            }
                            if (!IsSame(column2, num, num2))
{
                                _columnChangeList.Add(column2);
                            }
                        }
                        break;
                    }
                }
            }
            finally
            {
                _ignoreXmlEvents = false;
                IsFoliationEnabled = isFoliationEnabled;
            }
        }
    }
References System.Xml.XmlDataDocument._columnChangeList, System.Xml.XmlDataDocument._ignoreDataSetEvents, System.Xml.XmlDataDocument._ignoreXmlEvents, System.Xml.XmlDataDocument._rollbackState, System.Collections.ArrayList.Add(), System.Collections.ArrayList.Clear(), System.Xml.Dictionary, System.Xml.XmlDataDocument.FoliateIfDataPointers(), System.Xml.XmlDataDocument.GetElementFromRow(), System.Convert.IsDBNull(), System.Xml.XmlDataDocument.IsFoliationEnabled, System.Xml.XmlDataDocument.IsSame(), System.Xml.XmlDataDocument.OnDeletingRow(), and System.value.
Referenced by System.Xml.XmlDataDocument.BindToTable().