Terraria: System.Xml.XmlDataDocument.OnAddRow
OnAddRow()
void System.Xml.XmlDataDocument.OnAddRow (DataRow row) inline private
Definition at line 1092 of file XmlDataDocument.cs.
    {
        XmlBoundElement xmlBoundElement = (XmlBoundElement)GetElementFromRow(row);
        if (NeedXSI_NilAttr(row) && !xmlBoundElement.IsFoliated)
        {
            ForceFoliation(xmlBoundElement, AutoFoliationState);
        }
        DataRow rowFromElement = GetRowFromElement(base.DocumentElement);
        if (rowFromElement != null)
        {
            DataRow nestedParent = GetNestedParent(row);
            if (nestedParent == null)
            {
                DemoteDocumentElement();
            }
        }
        EnsureDocumentElement().AppendChild(xmlBoundElement);
        FixNestedChildren(row, xmlBoundElement);
        OnNestedParentChange(row, xmlBoundElement, null);
    }
References System.Xml.XmlNode.AppendChild(), System.Xml.XmlDataDocument.AutoFoliationState, System.Xml.XmlDataDocument.DemoteDocumentElement(), System.Xml.XmlDataDocument.EnsureDocumentElement(), System.Xml.XmlDataDocument.FixNestedChildren(), System.Xml.XmlDataDocument.ForceFoliation(), System.Xml.XmlDataDocument.GetElementFromRow(), System.Xml.XmlDataDocument.GetNestedParent(), System.Xml.XmlDataDocument.GetRowFromElement(), System.Xml.XmlDataDocument.NeedXSI_NilAttr(), and System.Xml.XmlDataDocument.OnNestedParentChange().
Referenced by System.Xml.XmlDataDocument.LoadTreeFromDataSet(), and System.Xml.XmlDataDocument.OnRowChanged().