Terraria: System.Xml.XmlDataDocument.AddPointer
AddPointer()
void System.Xml.XmlDataDocument.AddPointer (IXmlDataVirtualNode pointer) inline package
Definition at line 107 of file XmlDataDocument.cs.
    {
        lock (_pointers)
        {
            _countAddPointer++;
            if (_countAddPointer >= 5)
            {
                ArrayList arrayList = new ArrayList();
                foreach (DictionaryEntry pointer2 in _pointers)
                {
                    IXmlDataVirtualNode xmlDataVirtualNode = (IXmlDataVirtualNode)pointer2.Value;
                    if (!xmlDataVirtualNode.IsInUse())
                    {
                        arrayList.Add(xmlDataVirtualNode);
                    }
                }
                for (int i = 0; i < arrayList.Count; i++)
                {
                    _pointers.Remove(arrayList[i]);
                }
                _countAddPointer = 0;
            }
            _pointers[pointer] = pointer;
        }
    }
References System.Xml.XmlDataDocument._countAddPointer, System.Xml.XmlDataDocument._pointers, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Xml.Dictionary, System.pointer, and System.Collections.Hashtable.Remove().
Referenced by System.Xml.XPathNodePointer.XPathNodePointer(), and System.Xml.DataPointer.AddPointer().