Terraria: System.Xml.XmlDataDocument.FixNestedChildren
FixNestedChildren()
void System.Xml.XmlDataDocument.FixNestedChildren (DataRow row, XmlElement rowElement) inline private
Definition at line 464 of file XmlDataDocument.cs.
    {
        foreach (DataRelation nestedChildRelation in GetNestedChildRelations(row))
        {
            DataRow[] childRows = row.GetChildRows(nestedChildRelation);
            foreach (DataRow dataRow in childRows)
            {
                XmlElement element = dataRow.Element;
                if (element != null && element.ParentNode != rowElement)
                {
                    element.ParentNode.RemoveChild(element);
                    rowElement.AppendChild(element);
                }
            }
        }
    }
References System.Xml.XmlDataDocument.GetNestedChildRelations(), and System.Xml.XmlElement.ParentNode.
Referenced by System.Xml.XmlDataDocument.OnAddRow(), and System.Xml.XmlDataDocument.OnUndeleteRow().