Terraria: System.Xml.XmlDataDocument.CloneTree
CloneTree()
XmlNode System.Xml.XmlDataDocument.CloneTree (DataPointer other) inline package
Definition at line 763 of file XmlDataDocument.cs.
    {
        EnsurePopulatedMode();
        bool ignoreDataSetEvents = _ignoreDataSetEvents;
        bool ignoreXmlEvents = _ignoreXmlEvents;
        bool isFoliationEnabled = IsFoliationEnabled;
        bool fAssociateDataRow = _fAssociateDataRow;
        try
        {
            _ignoreDataSetEvents = true;
            _ignoreXmlEvents = true;
            IsFoliationEnabled = false;
            _fAssociateDataRow = false;
            XmlNode xmlNode = CloneTreeInternal(other);
            LoadRows(null, xmlNode);
            SyncRows(null, xmlNode, fAddRowsToTable: false);
            return xmlNode;
        }
        finally
        {
            _ignoreDataSetEvents = ignoreDataSetEvents;
            _ignoreXmlEvents = ignoreXmlEvents;
            IsFoliationEnabled = isFoliationEnabled;
            _fAssociateDataRow = fAssociateDataRow;
        }
    }
References System.Xml.XmlDataDocument._fAssociateDataRow, System.Xml.XmlDataDocument._ignoreDataSetEvents, System.Xml.XmlDataDocument._ignoreXmlEvents, System.Xml.XmlDataDocument.CloneTreeInternal(), System.Xml.Dictionary, System.Xml.XmlDataDocument.EnsurePopulatedMode(), System.Xml.XmlDataDocument.IsFoliationEnabled, System.Xml.XmlDataDocument.LoadRows(), System.other, and System.Xml.XmlDataDocument.SyncRows().