Terraria: System.Xml.XmlDataDocument.DefoliateRegion
DefoliateRegion()
void System.Xml.XmlDataDocument.DefoliateRegion (XmlBoundElement rowElem) inline private
Definition at line 373 of file XmlDataDocument.cs.
    {
        if (!_optimizeStorage || rowElem.ElementState != ElementState.WeakFoliation || !_mapper.IsRegionRadical(rowElem))
        {
            return;
        }
        bool ignoreXmlEvents = IgnoreXmlEvents;
        IgnoreXmlEvents = true;
        rowElem.ElementState = ElementState.Defoliating;
        try
        {
            rowElem.RemoveAllAttributes();
            XmlNode xmlNode = rowElem.FirstChild;
            while (xmlNode != null)
            {
                XmlNode nextSibling = xmlNode.NextSibling;
                if (xmlNode is XmlBoundElement { Row: not null })
                {
                    break;
                }
                rowElem.RemoveChild(xmlNode);
                xmlNode = nextSibling;
            }
            rowElem.ElementState = ElementState.Defoliated;
        }
        finally
        {
            IgnoreXmlEvents = ignoreXmlEvents;
        }
    }
References System.Xml.XmlDataDocument._mapper, System.Xml.XmlDataDocument._optimizeStorage, System.Xml.Dictionary, System.Xml.XmlDataDocument.IgnoreXmlEvents, and System.Xml.DataSetMapper.IsRegionRadical().
Referenced by System.Xml.XmlDataDocument.SyncRows(), and System.Xml.XmlDataDocument.SyncTree().