Terraria: System.Xml.XmlDataDocument.CloneNode
CloneNode() [2/2]
XmlNode System.Xml.XmlDataDocument.CloneNode (DataPointer dp) inline private
Definition at line 854 of file XmlDataDocument.cs.
    {
        return dp.NodeType switch
        {
            XmlNodeType.DocumentFragment => CreateDocumentFragment(),
            XmlNodeType.DocumentType => CreateDocumentType(dp.Name, dp.PublicId, dp.SystemId, dp.InternalSubset),
            XmlNodeType.XmlDeclaration => CreateXmlDeclaration(dp.Version, dp.Encoding, dp.Standalone),
            XmlNodeType.Text => CreateTextNode(dp.Value),
            XmlNodeType.CDATA => CreateCDataSection(dp.Value),
            XmlNodeType.ProcessingInstruction => CreateProcessingInstruction(dp.Name, dp.Value),
            XmlNodeType.Comment => CreateComment(dp.Value),
            XmlNodeType.Whitespace => CreateWhitespace(dp.Value),
            XmlNodeType.SignificantWhitespace => CreateSignificantWhitespace(dp.Value),
            XmlNodeType.Element => CreateElement(dp.Prefix, dp.LocalName, dp.NamespaceURI),
            XmlNodeType.Attribute => CreateAttribute(dp.Prefix, dp.LocalName, dp.NamespaceURI),
            XmlNodeType.EntityReference => CreateEntityReference(dp.Name),
            _ => throw new InvalidOperationException(System.SR.Format(System.SR.DataDom_CloneNode, dp.NodeType.ToString())),
        };
    }
References System.Xml.XmlDocument.CreateAttribute(), System.Xml.XmlDocument.CreateCDataSection(), System.Xml.XmlDocument.CreateComment(), System.Xml.XmlDocument.CreateDocumentFragment(), System.Xml.XmlDocument.CreateDocumentType(), System.Xml.XmlDataDocument.CreateElement(), System.Xml.XmlDataDocument.CreateEntityReference(), System.Xml.XmlDocument.CreateProcessingInstruction(), System.Xml.XmlDocument.CreateSignificantWhitespace(), System.Xml.XmlDocument.CreateTextNode(), System.Xml.XmlDocument.CreateWhitespace(), System.Xml.XmlDocument.CreateXmlDeclaration(), System.SR.DataDom_CloneNode, System.Xml.Dictionary, and System.SR.Format().