Terraria: System.Xml.XmlDataDocument.CreateElement
CreateElement() [3/3]
override XmlElement System.Xml.XmlDataDocument.CreateElement (string? prefix, string localName, string? namespaceURI) inline virtual
Reimplemented from System.Xml.XmlDocument.
Definition at line 335 of file XmlDataDocument.cs.
    {
        if (prefix == null)
        {
            prefix = string.Empty;
        }
        if (namespaceURI == null)
        {
            namespaceURI = string.Empty;
        }
        if (!_fAssociateDataRow)
        {
            return new XmlBoundElement(prefix, localName, namespaceURI, this);
        }
        EnsurePopulatedMode();
        DataTable dataTable = _mapper.SearchMatchingTableSchema(localName, namespaceURI);
        if (dataTable != null)
        {
            DataRow dataRow = dataTable.CreateEmptyRow();
            foreach (DataColumn column in dataTable.Columns)
            {
                if (column.ColumnMapping != MappingType.Hidden)
                {
                    SetRowValueToNull(dataRow, column);
                }
            }
            XmlBoundElement element = dataRow.Element;
            element.Prefix = prefix;
            return element;
        }
        return new XmlBoundElement(prefix, localName, namespaceURI, this);
    }
References System.Xml.XmlDataDocument._fAssociateDataRow, System.Xml.XmlDataDocument._mapper, System.Xml.Dictionary, System.Xml.XmlDataDocument.EnsurePopulatedMode(), System.prefix, System.Xml.DataSetMapper.SearchMatchingTableSchema(), and System.Xml.XmlDataDocument.SetRowValueToNull().
Referenced by System.Xml.XmlDataDocument.CloneNode().