Terraria: System.Xml.XmlDataDocument.OnColumnValueChanged
OnColumnValueChanged()
void System.Xml.XmlDataDocument.OnColumnValueChanged (DataRow row, DataColumn col, XmlBoundElement rowElement) inline private
Definition at line 1114 of file XmlDataDocument.cs.
    {
        if (!IsNotMapped(col))
        {
            object value = row[col];
            if (col.ColumnMapping == MappingType.SimpleContent && Convert.IsDBNull(value) && !rowElement.IsFoliated)
            {
                ForceFoliation(rowElement, ElementState.WeakFoliation);
            }
            else if (!IsFoliated(rowElement))
            {
                goto IL_0318;
            }
            if (IsTextOnly(col))
            {
                if (Convert.IsDBNull(value))
                {
                    value = string.Empty;
                    XmlAttribute attributeNode = rowElement.GetAttributeNode("xsi:nil");
                    if (attributeNode == null)
                    {
                        attributeNode = CreateAttribute("xsi", "nil", "http://www.w3.org/2001/XMLSchema-instance");
                        attributeNode.Value = "true";
                        rowElement.SetAttributeNode(attributeNode);
                        _bHasXSINIL = true;
                    }
                    else
                    {
                        attributeNode.Value = "true";
                    }
                }
                else
                {
                    XmlAttribute attributeNode2 = rowElement.GetAttributeNode("xsi:nil");
                    if (attributeNode2 != null)
                    {
                        attributeNode2.Value = "false";
                    }
                }
                ReplaceInitialChildText(rowElement, col.ConvertObjectToXml(value));
            }
            else
            {
                bool flag = false;
                if (col.ColumnMapping == MappingType.Attribute)
                {
                    foreach (XmlAttribute attribute in rowElement.Attributes)
                    {
                        if (attribute.LocalName == col.EncodedColumnName && attribute.NamespaceURI == col.Namespace)
{
                            if (Convert.IsDBNull(value))
{
                                attribute.OwnerElement.Attributes.Remove(attribute);
                            }
                            else
{
                                attribute.Value = col.ConvertObjectToXml(value);
                            }
                            flag = true;
                            break;
                        }
                    }
                    if (!flag && !Convert.IsDBNull(value))
                    {
                        rowElement.SetAttribute(col.EncodedColumnName, col.Namespace, col.ConvertObjectToXml(value));
                    }
                }
                else
                {
                    RegionIterator regionIterator = new RegionIterator(rowElement);
                    bool flag2 = regionIterator.Next();
                    while (true)
                    {
                        if (flag2)
{
                            if (regionIterator.CurrentNode.NodeType == XmlNodeType.Element)
{
                                XmlElement xmlElement = (XmlElement)regionIterator.CurrentNode;
                                if (xmlElement is XmlBoundElement { Row: not null })
{
                                    flag2 = regionIterator.NextRight();
                                    continue;
                                }
                                if (xmlElement.LocalName == col.EncodedColumnName && xmlElement.NamespaceURI == col.Namespace)
{
                                    flag = true;
                                    if (Convert.IsDBNull(value))
{
                                        PromoteNonValueChildren(xmlElement);
                                        flag2 = regionIterator.NextRight();
                                        xmlElement.ParentNode.RemoveChild(xmlElement);
                                        continue;
                                    }
                                    ReplaceInitialChildText(xmlElement, col.ConvertObjectToXml(value));
                                    XmlAttribute attributeNode3 = xmlElement.GetAttributeNode("xsi:nil");
                                    if (attributeNode3 != null)
{
                                        attributeNode3.Value = "false";
                                    }
                                    break;
                                }
                            }
                            flag2 = regionIterator.Next();
                            continue;
                        }
                        if (!flag && !Convert.IsDBNull(value))
{
                            XmlElement xmlElement2 = new XmlBoundElement(string.Empty, col.EncodedColumnName, col.Namespace, this);
                            xmlElement2.AppendChild(CreateTextNode(col.ConvertObjectToXml(value)));
                            XmlNode columnInsertAfterLocation = GetColumnInsertAfterLocation(row, col, rowElement);
                            if (columnInsertAfterLocation != null)
{
                                rowElement.InsertAfter(xmlElement2, columnInsertAfterLocation);
                            }
                            else if (rowElement.FirstChild != null)
{
                                rowElement.InsertBefore(xmlElement2, rowElement.FirstChild);
                            }
                            else
{
                                rowElement.AppendChild(xmlElement2);
                            }
                        }
                        break;
                    }
                }
            }
        }
        goto IL_0318;
        IL_0318:
        DataRelation nestedParentRelation = GetNestedParentRelation(row);
        if (nestedParentRelation != null && nestedParentRelation.ChildKey.ContainsColumn(col))
        {
            OnNestedParentChange(row, rowElement, col);
        }
    }
References System.Xml.XmlDataDocument._bHasXSINIL, System.Xml.XmlDocument.CreateAttribute(), System.Xml.XmlDocument.CreateTextNode(), System.Xml.Dictionary, System.Xml.XmlDataDocument.ForceFoliation(), System.Xml.XmlDataDocument.GetColumnInsertAfterLocation(), System.Xml.XmlDataDocument.GetNestedParentRelation(), System.Convert.IsDBNull(), System.Xml.XmlDataDocument.IsFoliated(), System.Xml.XmlDataDocument.IsNotMapped(), System.Xml.XmlDataDocument.IsTextOnly(), System.Xml.XmlDataDocument.OnNestedParentChange(), System.Xml.XmlDataDocument.PromoteNonValueChildren(), System.Collections.Generic.Dictionary< TKey, TValue >.Remove(), System.Xml.XmlDataDocument.ReplaceInitialChildText(), and System.value.
Referenced by System.Xml.XmlDataDocument.OnColumnChanged(), System.Xml.XmlDataDocument.OnColumnValuesChanged(), and System.Xml.XmlDataDocument.UpdateAllColumns().