Terraria: System.Xml.XmlDataDocument.LoadRows
LoadRows()
void System.Xml.XmlDataDocument.LoadRows (XmlBoundElement rowElem, XmlNode node) inline private
Definition at line 1022 of file XmlDataDocument.cs.
    {
        if (node is XmlBoundElement xmlBoundElement)
        {
            DataTable dataTable = _mapper.SearchMatchingTableSchema(rowElem, xmlBoundElement);
            if (dataTable != null)
            {
                DataRow rowFromElement = GetRowFromElement(xmlBoundElement);
                if (xmlBoundElement.ElementState == ElementState.None)
                {
                    xmlBoundElement.ElementState = ElementState.WeakFoliation;
                }
                rowFromElement = dataTable.CreateEmptyRow();
                Bind(rowFromElement, xmlBoundElement);
                rowElem = xmlBoundElement;
            }
        }
        for (XmlNode xmlNode = node.FirstChild; xmlNode != null; xmlNode = xmlNode.NextSibling)
        {
            LoadRows(rowElem, xmlNode);
        }
    }
References System.Xml.XmlDataDocument._mapper, System.Xml.XmlDataDocument.Bind(), System.Xml.Dictionary, System.Xml.XmlDataDocument.GetRowFromElement(), System.Xml.XmlDataDocument.LoadRows(), and System.Xml.DataSetMapper.SearchMatchingTableSchema().
Referenced by System.Xml.XmlDataDocument.CloneTree(), System.Xml.XmlDataDocument.LoadDataSetFromTree(), and System.Xml.XmlDataDocument.LoadRows().