Terraria: System.Xml.XmlDataDocument.EnsureDocumentElement
EnsureDocumentElement()
XmlElement System.Xml.XmlDataDocument.EnsureDocumentElement () inline private
Definition at line 405 of file XmlDataDocument.cs.
    {
        XmlElement xmlElement = base.DocumentElement;
        if (xmlElement == null)
        {
            string text = XmlConvert.EncodeLocalName(DataSet.DataSetName);
            if (text == null || text.Length == 0)
            {
                text = "Xml";
            }
            string text2 = DataSet.Namespace;
            if (text2 == null)
            {
                text2 = string.Empty;
            }
            xmlElement = new XmlBoundElement(string.Empty, text, text2, this);
            AppendChild(xmlElement);
        }
        return xmlElement;
    }
References System.Xml.AppendChild, System.Data.DataSet.DataSetName, System.Xml.Dictionary, System.Xml.XmlConvert.EncodeLocalName(), System.Data.DataSet.Namespace, and System.text.
Referenced by System.Xml.XmlDataDocument.DemoteDocumentElement(), System.Xml.XmlDataDocument.EnsureNonRowDocumentElement(), and System.Xml.XmlDataDocument.OnAddRow().