Terraria: System.Xml.XmlDataDocument.OrderTables
OrderTables()
DataTable[] System.Xml.XmlDataDocument.OrderTables (DataSet ds) inline private
Definition at line 2377 of file XmlDataDocument.cs.
    {
        DataTable[] array = null;
        if (ds == null || ds.Tables.Count == 0)
        {
            array = Array.Empty<DataTable>();
        }
        else if (TablesAreOrdered(ds))
        {
            array = new DataTable[ds.Tables.Count];
            ds.Tables.CopyTo(array, 0);
        }
        if (array == null)
        {
            array = new DataTable[ds.Tables.Count];
            List<DataTable> list = new List<DataTable>();
            foreach (DataTable table in ds.Tables)
            {
                if (table.ParentRelations.Count == 0)
                {
                    list.Add(table);
                }
            }
            if (list.Count > 0)
            {
                foreach (DataTable table2 in ds.Tables)
                {
                    if (IsSelfRelatedDataTable(table2))
                    {
                        list.Add(table2);
                    }
                }
                for (int i = 0; i < list.Count; i++)
                {
                    foreach (DataRelation childRelation in list[i].ChildRelations)
                    {
                        DataTable childTable = childRelation.ChildTable;
                        if (!list.Contains(childTable))
{
                            list.Add(childTable);
                        }
                    }
                }
                list.CopyTo(array);
            }
            else
            {
                ds.Tables.CopyTo(array, 0);
            }
        }
        return array;
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.array, System.Collections.Generic.Dictionary< TKey, TValue >.CopyTo(), System.Data.InternalDataCollectionBase.Count, System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Xml.Dictionary, System.Xml.XmlDataDocument.IsSelfRelatedDataTable(), System.list, System.Data.DataTable.ParentRelations, and System.Xml.XmlDataDocument.TablesAreOrdered().
Referenced by System.Xml.XmlDataDocument.LoadTreeFromDataSet().