Terraria: System.Xml.XmlDataDocument.LoadDataSetFromTree
LoadDataSetFromTree()
void System.Xml.XmlDataDocument.LoadDataSetFromTree () inline private
Definition at line 963 of file XmlDataDocument.cs.
    {
        _ignoreDataSetEvents = true;
        _ignoreXmlEvents = true;
        bool isFoliationEnabled = IsFoliationEnabled;
        IsFoliationEnabled = false;
        bool enforceConstraints = _dataSet.EnforceConstraints;
        _dataSet.EnforceConstraints = false;
        try
        {
            LoadRows(null, base.DocumentElement);
            SyncRows(null, base.DocumentElement, fAddRowsToTable: true);
            _dataSet.EnforceConstraints = enforceConstraints;
        }
        finally
        {
            _ignoreDataSetEvents = false;
            _ignoreXmlEvents = false;
            IsFoliationEnabled = isFoliationEnabled;
        }
    }
References System.Xml.XmlDataDocument._dataSet, System.Xml.XmlDataDocument._ignoreDataSetEvents, System.Xml.XmlDataDocument._ignoreXmlEvents, System.Xml.Dictionary, System.Data.DataSet.EnforceConstraints, System.Xml.XmlDataDocument.IsFoliationEnabled, System.Xml.XmlDataDocument.LoadRows(), and System.Xml.XmlDataDocument.SyncRows().
Referenced by System.Xml.XmlDataDocument.Bind(), and System.Xml.XmlDataDocument.BindForLoad().