Terraria: System.Xml.XmlDataDocument.PromoteNonValueChildren
PromoteNonValueChildren()
void System.Xml.XmlDataDocument.PromoteNonValueChildren (XmlNode parent) inline private
Definition at line 1843 of file XmlDataDocument.cs.
    {
        XmlNode prevSibling = parent;
        XmlNode xmlNode = parent.FirstChild;
        bool flag = true;
        XmlNode xmlNode2 = null;
        while (xmlNode != null)
        {
            xmlNode2 = xmlNode.NextSibling;
            if (!flag || !IsTextLikeNode(xmlNode))
            {
                flag = false;
                xmlNode2 = xmlNode.NextSibling;
                PromoteChild(xmlNode, prevSibling);
                prevSibling = xmlNode;
            }
            xmlNode = xmlNode2;
        }
    }
References System.Xml.Dictionary, System.Xml.XmlNode.FirstChild, System.Xml.XmlDataDocument.IsTextLikeNode(), and System.Xml.XmlDataDocument.PromoteChild().
Referenced by System.Xml.XmlDataDocument.OnColumnValueChanged().