Terraria: System.Xml.XmlDataDocument.OnRowElementInsertedInTree
OnRowElementInsertedInTree()
void System.Xml.XmlDataDocument.OnRowElementInsertedInTree (XmlBoundElement rowElem, ArrayList rowElemList) inline private
Definition at line 2228 of file XmlDataDocument.cs.
    {
        DataRow row = rowElem.Row;
        switch (row.RowState)
        {
        case DataRowState.Detached:
            row.Table.Rows.Add(row);
            SetNestedParentRegion(rowElem);
            if (rowElemList != null)
            {
                RegionIterator regionIterator = new RegionIterator(rowElem);
                bool flag = regionIterator.NextRowElement();
                while (flag)
                {
                    rowElemList.Add(regionIterator.CurrentNode);
                    flag = regionIterator.NextRightRowElement();
                }
            }
            break;
        case DataRowState.Deleted:
            row.RejectChanges();
            SynchronizeRowFromRowElement(rowElem, rowElemList);
            SetNestedParentRegion(rowElem);
            break;
        }
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Xml.XmlDataDocument.SetNestedParentRegion(), and System.Xml.XmlDataDocument.SynchronizeRowFromRowElement().
Referenced by System.Xml.XmlDataDocument.OnNodeInsertedInTree().