Terraria: System.Xml.XmlDataDocument.EnsureDisconnectedDataRow
EnsureDisconnectedDataRow()
void System.Xml.XmlDataDocument.EnsureDisconnectedDataRow (XmlBoundElement rowElem) inline private
Definition at line 2256 of file XmlDataDocument.cs.
    {
        DataRow row = rowElem.Row;
        switch (row.RowState)
        {
        case DataRowState.Detached:
            SetNestedParentRegion(rowElem);
            break;
        case DataRowState.Unchanged:
        case DataRowState.Modified:
            EnsureFoliation(rowElem, ElementState.WeakFoliation);
            row.Delete();
            break;
        case DataRowState.Added:
            EnsureFoliation(rowElem, ElementState.WeakFoliation);
            row.Delete();
            SetNestedParentRegion(rowElem);
            break;
        }
    }
References System.Xml.XmlDataDocument.EnsureFoliation(), and System.Xml.XmlDataDocument.SetNestedParentRegion().
Referenced by System.Xml.XmlDataDocument.OnNodeRemovedFromTree().