Terraria: System.Xml.XmlDataDocument.IsNotMapped
IsNotMapped()
bool System.Xml.XmlDataDocument.IsNotMapped (DataColumn c) inline package
Definition at line 890 of file XmlDataDocument.cs.
    {
        return DataSetMapper.IsNotMapped(c);
    }
References System.Xml.DataSetMapper.IsNotMapped().
Referenced by System.Xml.XmlDataDocument.ForceFoliation(), System.Xml.XPathNodePointer.NextColumn(), System.Xml.DataPointer.NextColumn(), System.Xml.XmlDataDocument.OnColumnValueChanged(), System.Xml.XPathNodePointer.PreviousColumn(), and System.Xml.XmlDataDocument.SynchronizeRowFromRowElementEx().