Terraria: System.Xml.XmlDataDocument.OnRowChanged
OnRowChanged()
void System.Xml.XmlDataDocument.OnRowChanged (object sender, DataRowChangeEventArgs args) inline private
Definition at line 1592 of file XmlDataDocument.cs.
    {
        if (_ignoreDataSetEvents)
        {
            return;
        }
        _ignoreXmlEvents = true;
        bool isFoliationEnabled = IsFoliationEnabled;
        IsFoliationEnabled = false;
        try
        {
            DataRow row = args.Row;
            XmlBoundElement element = row.Element;
            switch (args.Action)
            {
            case DataRowAction.Add:
                OnAddRow(row);
                break;
            case DataRowAction.Delete:
                OnDeleteRow(row, element);
                break;
            case DataRowAction.Rollback:
                switch (_rollbackState)
                {
                case DataRowState.Deleted:
                    OnUndeleteRow(row, element);
                    UpdateAllColumns(row, element);
                    break;
                case DataRowState.Added:
                    element.ParentNode.RemoveChild(element);
                    break;
                case DataRowState.Modified:
                    OnColumnValuesChanged(row, element);
                    break;
                }
                break;
            case DataRowAction.Change:
                OnColumnValuesChanged(row, element);
                break;
            case DataRowAction.Commit:
                if (row.RowState == DataRowState.Detached)
                {
                    element.RemoveAll();
                }
                break;
            }
        }
        finally
        {
            IsFoliationEnabled = isFoliationEnabled;
            _ignoreXmlEvents = false;
        }
    }
References System.Xml.XmlDataDocument._ignoreDataSetEvents, System.Xml.XmlDataDocument._ignoreXmlEvents, System.Xml.XmlDataDocument._rollbackState, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Xml.Dictionary, System.Xml.XmlDataDocument.IsFoliationEnabled, System.Xml.XmlDataDocument.OnAddRow(), System.Xml.XmlDataDocument.OnColumnValuesChanged(), System.Xml.XmlDataDocument.OnDeleteRow(), System.Xml.XmlDataDocument.OnUndeleteRow(), System.Xml.XmlElement.ParentNode, System.Xml.XmlElement.RemoveAll(), and System.Xml.XmlDataDocument.UpdateAllColumns().
Referenced by System.Xml.XmlDataDocument.BindToTable().