Terraria: NPCHeadRenderer.DrawWithOutlines
DrawWithOutlines()
void NPCHeadRenderer.DrawWithOutlines (Entity entity, int headId, Vector2 position, Color color, float rotation, float scale, SpriteEffects effects) inline
     {
         if (_contents[headId] == null)
         {
             _contents[headId] = new NPCHeadDrawRenderTargetContent();
             _contents[headId].SetTexture(_matchingArray[headId].Value);
         }
         NPCHeadDrawRenderTargetContent nPCHeadDrawRenderTargetContent = _contents[headId];
         if (nPCHeadDrawRenderTargetContent.IsReady)
         {
             RenderTarget2D target = nPCHeadDrawRenderTargetContent.GetTarget();
             Main.spriteBatch.Draw(target, position, null, color, rotation, ((Texture2D)target).Size() / 2f, scale, effects, 0f);
         }
         else
         {
             nPCHeadDrawRenderTargetContent.Request();
         }
     }
References _contents, _matchingArray, ARenderTargetContentByRequest.GetTarget(), ARenderTargetContentByRequest.IsReady, ARenderTargetContentByRequest.Request(), NPCHeadDrawRenderTargetContent.SetTexture(), and Main.spriteBatch.
Referenced by Main.DrawNPCHeadBoss(), and Main.DrawNPCHeadFriendly().