Terraria: System.Data.Common.ADP.Argument
Argument() [1/3]
static ArgumentException System.Data.Common.ADP.Argument (string error) inline static package
Definition at line 678 of file ADP.cs.
    {
        ArgumentException ex = new ArgumentException(error);
        TraceExceptionAsReturnValue(ex);
        return ex;
    }
References System.Data.Common.ADP.TraceExceptionAsReturnValue().
Referenced by System.Data.Common.ADP.CheckArgumentLength(), System.Data.Common.ADP.CheckArgumentLength(), System.Data.Common.ADP.CollectionRemoveInvalidObject(), System.Data.Common.ADP.CollectionUniqueValue(), System.Data.Common.ADP.ConnectionStringSyntax(), System.Data.Common.ADP.ConvertFailed(), System.Data.Common.ADP.FillRequiresSourceTableName(), System.Data.Common.ADP.FillSchemaRequiresSourceTableName(), System.Data.Common.DbProviderFactories.GetFactory(), System.Data.Common.DbProviderFactories.GetFactory(), System.Data.Common.DbProviderFactories.GetFactoryInstance(), System.Data.Common.DbProviderFactories.GetProviderTypeFromTypeName(), System.Data.Common.ADP.InvalidKeyname(), System.Data.Common.ADP.InvalidMaxRecords(), System.Data.Common.ADP.InvalidSourceColumn(), System.Data.Common.ADP.InvalidSourceTable(), System.Data.Common.ADP.InvalidStartRecord(), System.Data.Common.ADP.InvalidValue(), System.Data.Common.ADP.KeywordNotSupported(), System.Data.Common.ADP.ParametersIsNotParent(), System.Data.Common.ADP.ParametersIsParent(), System.Data.Common.ADP.UnwantedStatementType(), System.Data.Common.ADP.UpdateMismatchRowTable(), and System.Data.Common.ADP.WrongType().