Terraria: System.Data.Common.ADP.InvalidStatementType
InvalidStatementType()
static ArgumentOutOfRangeException System.Data.Common.ADP.InvalidStatementType (StatementType value) inline static package
Definition at line 149 of file ADP.cs.
    {
        return InvalidEnumerationValue(typeof(StatementType), (int)value);
    }
References System.Data.Common.ADP.InvalidEnumerationValue(), and System.value.
Referenced by System.Data.Common.RowUpdatedEventArgs.RowUpdatedEventArgs(), System.Data.Common.RowUpdatingEventArgs.RowUpdatingEventArgs(), System.Data.Common.DbDataAdapter.GetParameterSourceVersion(), System.Data.Common.DbCommandBuilder.RowUpdatingHandler(), System.Data.Common.DbCommandBuilder.RowUpdatingHandlerBuilder(), System.Data.Common.ADP.UpdateConnectionRequired(), System.Data.Common.ADP.UpdateOpenConnectionRequired(), and System.Data.Common.ADP.UpdateRequiresCommand().