Terraria: System.Data.Common.ADP.InvalidSourceBufferIndex
InvalidSourceBufferIndex()
static ArgumentOutOfRangeException System.Data.Common.ADP.InvalidSourceBufferIndex (int maxLen, long srcOffset, string parameterName) inline static package
Definition at line 927 of file ADP.cs.
    {
        return ArgumentOutOfRange(System.SR.Format(System.SR.ADP_InvalidSourceBufferIndex, maxLen.ToString(CultureInfo.InvariantCulture), srcOffset.ToString(CultureInfo.InvariantCulture)), parameterName);
    }
References System.SR.ADP_InvalidSourceBufferIndex, System.Data.Common.ADP.ArgumentOutOfRange(), System.SR.Format(), and System.Globalization.CultureInfo.InvariantCulture.
Referenced by System.Data.Common.DataRecordInternal.GetBytes(), System.Data.DataTableReader.GetBytes(), System.Data.Common.DataRecordInternal.GetChars(), and System.Data.DataTableReader.GetChars().