Terraria: System.Data.Common.ADP.FillRequires
FillRequires()
static Exception System.Data.Common.ADP.FillRequires (string parameter) inline static package
Definition at line 390 of file ADP.cs.
    {
        return ArgumentNull(parameter);
    }
References System.ArgumentNull.
Referenced by System.Data.Common.DbDataAdapter.Fill(), System.Data.Common.DataAdapter.Fill(), System.Data.Common.DataAdapter.Fill(), System.Data.Common.DbDataAdapter.Fill(), System.Data.Common.DataAdapter.FillSchema(), and System.Data.Common.DataAdapter.FillSchema().