Terraria: System.Data.Common.ADP.InvalidOperation
InvalidOperation()
static InvalidOperationException System.Data.Common.ADP.InvalidOperation (string error) inline static package
Definition at line 746 of file ADP.cs.
    {
        InvalidOperationException ex = new InvalidOperationException(error);
        TraceExceptionAsReturnValue(ex);
        return ex;
    }
References System.Data.Common.ADP.TraceExceptionAsReturnValue().
Referenced by System.Data.Common.ADP.ColumnSchemaMissing(), System.Data.Common.ADP.ConnectionRequired_Res(), System.Data.Common.ADP.DataAdapter(), System.Data.Common.ADP.DataMapping(), System.Data.Common.ADP.DataReaderClosed(), System.Data.Common.ADP.DynamicSQLJoinUnsupported(), System.Data.Common.ADP.DynamicSQLNestedQuote(), System.Data.Common.ADP.DynamicSQLNoKeyInfoDelete(), System.Data.Common.ADP.DynamicSQLNoKeyInfoRowVersionDelete(), System.Data.Common.ADP.DynamicSQLNoKeyInfoRowVersionUpdate(), System.Data.Common.ADP.DynamicSQLNoKeyInfoUpdate(), System.Data.Common.ADP.DynamicSQLNoTableInfo(), System.Data.Common.ADP.FillChapterAutoIncrement(), System.Data.Common.DbProviderFactories.GetFactoryInstance(), System.Data.Common.ADP.InternalError(), System.Data.Common.ADP.MissingSourceCommand(), System.Data.Common.ADP.MissingSourceCommandConnection(), System.Data.Common.ADP.NoQuoteChange(), System.Data.Common.ADP.Provider(), System.Data.Common.ADP.StreamClosed(), System.Data.Common.ADP.UpdateConnectionRequired(), System.Data.Common.ADP.UpdateOpenConnectionRequired(), System.Data.Common.ADP.UpdateRequiresCommand(), System.Data.Common.ADP.UpdateRequiresSourceTable(), System.Data.Common.ADP.UpdateRequiresSourceTableName(), and System.Data.Common.ObjectStorage.VerifyIDynamicMetaObjectProvider().