Terraria: System.Data.Common.ADP.CheckArgumentNull
CheckArgumentNull()
static void System.Data.Common.ADP.CheckArgumentNull ([NotNull] object value, string parameterName) inline static package
Definition at line 782 of file ADP.cs.
    {
        if (value == null)
        {
            throw ArgumentNull(parameterName);
        }
    }
References System.ArgumentNull, and System.value.
Referenced by System.Data.Common.RowUpdatingEventArgs.RowUpdatingEventArgs(), System.Data.Common.DbConnectionOptions.AppendKeyValuePairBuilder(), System.Data.Common.ADP.CheckArgumentLength(), System.Data.Common.ADP.CheckArgumentLength(), System.Data.Common.DbConnectionStringBuilder.ContainsKey(), System.Data.Common.DbConnectionStringBuilder.EquivalentTo(), System.Data.Common.DbProviderFactories.GetFactory(), System.Data.Common.DbProviderFactories.GetFactory(), System.Data.Common.DbProviderFactories.GetFactoryInstance(), System.Data.DataSet.Load(), System.Data.DataSet.Load(), System.Data.Common.DbProviderFactories.RegisterFactory(), System.Data.Common.DbConnectionStringBuilder.Remove(), System.Data.Common.DbConnectionStringBuilder.ShouldSerialize(), System.Data.Common.DbConnectionStringBuilder.TryGetValue(), System.Data.DataSet.WriteXmlSchema(), System.Data.DataSet.WriteXmlSchema(), System.Data.DataSet.WriteXmlSchema(), and System.Data.DataSet.WriteXmlSchema().