Terraria: System.Data.Common.ADP.UpdateOpenConnectionRequired
UpdateOpenConnectionRequired()
static InvalidOperationException System.Data.Common.ADP.UpdateOpenConnectionRequired (StatementType statementType, bool isRowUpdatingCommand, ConnectionState state) inline static package
Definition at line 358 of file ADP.cs.
    {
        string resourceFormat = (isRowUpdatingCommand ? System.SR.ADP_OpenConnectionRequired_Clone : (statementType switch
        {
            StatementType.Insert => System.SR.ADP_OpenConnectionRequired_Insert,
            StatementType.Update => System.SR.ADP_OpenConnectionRequired_Update,
            StatementType.Delete => System.SR.ADP_OpenConnectionRequired_Delete,
            _ => throw InvalidStatementType(statementType),
        }));
        return InvalidOperation(System.SR.Format(resourceFormat, ConnectionStateMsg(state)));
    }
References System.SR.ADP_OpenConnectionRequired_Delete, System.SR.ADP_OpenConnectionRequired_Insert, System.SR.ADP_OpenConnectionRequired_Update, System.Data.Common.ADP.ConnectionStateMsg(), System.SR.Format(), System.Data.Common.ADP.InvalidOperation(), System.Data.Common.ADP.InvalidStatementType(), and System.state.
Referenced by System.Data.Common.DbDataAdapter.Update().