Terraria: System.Data.Common.ADP.UpdateConnectionRequired
UpdateConnectionRequired()
static InvalidOperationException System.Data.Common.ADP.UpdateConnectionRequired (StatementType statementType, bool isRowUpdatingCommand) inline static package
Definition at line 323 of file ADP.cs.
    {
        string error;
        if (isRowUpdatingCommand)
        {
            error = System.SR.ADP_ConnectionRequired_Clone;
        }
        else
        {
            switch (statementType)
            {
            case StatementType.Insert:
                error = System.SR.ADP_ConnectionRequired_Insert;
                break;
            case StatementType.Update:
                error = System.SR.ADP_ConnectionRequired_Update;
                break;
            case StatementType.Delete:
                error = System.SR.ADP_ConnectionRequired_Delete;
                break;
            case StatementType.Batch:
                error = System.SR.ADP_ConnectionRequired_Batch;
                goto default;
            default:
                throw InvalidStatementType(statementType);
            }
        }
        return InvalidOperation(error);
    }
References System.SR.ADP_ConnectionRequired_Batch, System.SR.ADP_ConnectionRequired_Clone, System.SR.ADP_ConnectionRequired_Delete, System.SR.ADP_ConnectionRequired_Insert, System.SR.ADP_ConnectionRequired_Update, System.Data.Common.ADP.InvalidOperation(), and System.Data.Common.ADP.InvalidStatementType().
Referenced by System.Data.Common.DbDataAdapter.GetConnection1(), and System.Data.Common.DbDataAdapter.GetConnection4().