Terraria: System.Data.Common.ADP.UnwantedStatementType
UnwantedStatementType()
static ArgumentException System.Data.Common.ADP.UnwantedStatementType (StatementType statementType) inline static package
Definition at line 370 of file ADP.cs.
    {
        return Argument(System.SR.Format(System.SR.ADP_UnwantedStatementType, statementType.ToString()));
    }
References System.SR.ADP_UnwantedStatementType, System.Data.Common.ADP.Argument(), and System.SR.Format().
Referenced by System.Data.Common.DbDataAdapter.GetParameterSourceVersion().