Terraria: System.Data.Common.ADP.ParametersIsParent
ParametersIsParent()
static ArgumentException System.Data.Common.ADP.ParametersIsParent (Type parameterType, ICollection collection) inline static package
Definition at line 912 of file ADP.cs.
    {
        return Argument(System.SR.Format(System.SR.ADP_CollectionIsNotParent, parameterType.Name, collection.GetType().Name));
    }
References System.SR.ADP_CollectionIsNotParent, System.Data.Common.ADP.Argument(), System.collection, and System.SR.Format().
Referenced by System.Data.Common.ADP.ColumnsIsParent(), and System.Data.Common.ADP.TablesIsParent().