Terraria: System.Data.Common.ADP.ColumnSchemaMissing
ColumnSchemaMissing()
static InvalidOperationException System.Data.Common.ADP.ColumnSchemaMissing (string cacheColumn, string tableName, string srcColumn) inline static package
Definition at line 204 of file ADP.cs.
    {
        if (string.IsNullOrEmpty(tableName))
        {
            return InvalidOperation(System.SR.Format(System.SR.ADP_ColumnSchemaMissing1, cacheColumn, tableName, srcColumn));
        }
        return DataMapping(System.SR.Format(System.SR.ADP_ColumnSchemaMissing2, cacheColumn, tableName, srcColumn));
    }
References System.SR.ADP_ColumnSchemaMissing1, System.SR.ADP_ColumnSchemaMissing2, System.Data.Common.ADP.DataMapping(), System.SR.Format(), and System.Data.Common.ADP.InvalidOperation().
Referenced by System.Data.Common.DataColumnMapping.CreateDataColumnBySchemaAction().