Terraria: System.Data.Common.ADP.MissingTableMappingDestination
MissingTableMappingDestination()
static InvalidOperationException System.Data.Common.ADP.MissingTableMappingDestination (string dstTable) inline static package
Definition at line 228 of file ADP.cs.
    {
        return DataMapping(System.SR.Format(System.SR.ADP_MissingTableMappingDestination, dstTable));
    }
References System.SR.ADP_MissingTableMappingDestination, System.Data.Common.ADP.DataMapping(), and System.SR.Format().
Referenced by System.Data.ProviderBase.SchemaMapping.SchemaMapping(), System.Data.Common.DbDataAdapter.GetTableMapping(), and System.Data.Common.DbDataAdapter.Update().