Terraria: System.Data.Common.ADP.NotSupported
NotSupported() [1/2]
static NotSupportedException System.Data.Common.ADP.NotSupported () inline static package
Definition at line 753 of file ADP.cs.
    {
        NotSupportedException ex = new NotSupportedException();
        TraceExceptionAsReturnValue(ex);
        return ex;
    }
References System.Data.Common.ADP.TraceExceptionAsReturnValue().
Referenced by System.Data.Common.DbDataAdapter.AddToBatch(), System.Data.Common.DbDataAdapter.ClearBatch(), System.Data.ExceptionBuilder.ColumnTypeNotSupported(), System.Data.Common.DbConnection.EnlistTransaction(), System.Data.Common.DbDataAdapter.ExecuteBatch(), System.Data.Common.DataAdapter.Fill(), System.Data.Common.DataAdapter.Fill(), System.Data.Common.DataAdapter.FillSchema(), System.Data.Common.DbDataAdapter.GetBatchedParameter(), System.Data.Common.DbDataRecord.GetDbDataReader(), System.Data.Common.DbDataReader.GetDbDataReader(), System.Data.Common.DbConnection.GetSchema(), System.Data.Common.DbConnection.GetSchema(), System.Data.Common.DbConnection.GetSchema(), System.Data.Common.DbDataAdapter.InitializeBatching(), System.Data.Common.DbCommandBuilder.QuoteIdentifier(), System.Data.Common.DbEnumerator.Reset(), System.Data.Common.DbEnumerator.DbColumnDescriptor.ResetValue(), System.Data.Common.DbEnumerator.DbColumnDescriptor.SetValue(), System.Data.Common.DbDataAdapter.TerminateBatching(), System.Data.Common.DbCommandBuilder.UnquoteIdentifier(), and System.Data.Common.DataAdapter.Update().