Terraria: System.Data.Common.ADP.ArgumentOutOfRange
ArgumentOutOfRange() [2/2]
static ArgumentOutOfRangeException System.Data.Common.ADP.ArgumentOutOfRange (string parameterName) inline static package
Definition at line 713 of file ADP.cs.
    {
        ArgumentOutOfRangeException ex = new ArgumentOutOfRangeException(parameterName);
        TraceExceptionAsReturnValue(ex);
        return ex;
    }
References System.Data.Common.ADP.TraceExceptionAsReturnValue().
Referenced by System.Data.SqlTypes.SqlString.CompareOptionsFromSqlCompareOptions(), System.Data.Common.ADP.InvalidDestinationBufferIndex(), System.Data.Common.ADP.InvalidEnumerationValue(), System.Data.Common.ADP.InvalidSeekOrigin(), System.Data.Common.ADP.InvalidSourceBufferIndex(), System.Data.Common.ADP.NotSupportedEnumerationValue(), and System.Data.SqlTypes.SqlStreamChars.Seek().