Terraria: System.Data.Common.ADP.BuildSchemaTableInfoTableNames
BuildSchemaTableInfoTableNames()
static void System.Data.Common.ADP.BuildSchemaTableInfoTableNames (string[] columnNameArray) inline static package
Definition at line 592 of file ADP.cs.
    {
        Dictionary<string, int> dictionary = new Dictionary<string, int>(columnNameArray.Length);
        int num = columnNameArray.Length;
        int num2 = columnNameArray.Length - 1;
        while (0 <= num2)
        {
            string text = columnNameArray[num2];
            if (text != null && 0 < text.Length)
            {
                text = text.ToLowerInvariant();
                if (dictionary.TryGetValue(text, out var value))
                {
                    num = Math.Min(num, value);
                }
                dictionary[text] = num2;
            }
            else
            {
                columnNameArray[num2] = string.Empty;
                num = num2;
            }
            num2--;
        }
        int uniqueIndex = 1;
        for (int i = num; i < columnNameArray.Length; i++)
        {
            string text2 = columnNameArray[i];
            if (text2.Length == 0)
            {
                columnNameArray[i] = "Column";
                uniqueIndex = GenerateUniqueName(dictionary, ref columnNameArray[i], i, uniqueIndex);
                continue;
            }
            text2 = text2.ToLowerInvariant();
            if (i != dictionary[text2])
            {
                GenerateUniqueName(dictionary, ref columnNameArray[i], i, 1);
            }
        }
    }
References System.dictionary, System.Data.Common.ADP.GenerateUniqueName(), System.Math.Min(), System.text, and System.value.
Referenced by System.Data.Common.DbCommandBuilder.BuildCache(), System.Data.Common.DbEnumerator.BuildSchemaInfo(), and System.Data.ProviderBase.SchemaMapping.GenerateFieldNames().