Terraria: System.Data.Common.ADP.InvalidEnumerationValue
InvalidEnumerationValue()
static ArgumentOutOfRangeException System.Data.Common.ADP.InvalidEnumerationValue (Type type, int value) inline static package
Definition at line 810 of file ADP.cs.
    {
        return ArgumentOutOfRange(System.SR.Format(System.SR.ADP_InvalidEnumerationValue, type.Name, value.ToString(CultureInfo.InvariantCulture)), type.Name);
    }
References System.SR.ADP_InvalidEnumerationValue, System.Data.Common.ADP.ArgumentOutOfRange(), System.SR.Format(), System.Globalization.CultureInfo.InvariantCulture, System.type, and System.value.
Referenced by System.Data.Common.ADP.InvalidAcceptRejectRule(), System.Data.Common.ADP.InvalidCatalogLocation(), System.Data.Common.ADP.InvalidConflictOptions(), System.Data.Common.ADP.InvalidDataRowState(), System.Data.Common.ADP.InvalidLoadOption(), System.Data.Common.ADP.InvalidMissingMappingAction(), System.Data.Common.ADP.InvalidMissingSchemaAction(), System.Data.Common.ADP.InvalidRule(), System.Data.Common.ADP.InvalidSchemaType(), System.Data.Common.ADP.InvalidStatementType(), and System.Data.Common.ADP.InvalidUpdateStatus().