Terraria: System.Data.Common.ADP.UpdateConcurrencyViolation
UpdateConcurrencyViolation()
static Exception System.Data.Common.ADP.UpdateConcurrencyViolation (StatementType statementType, int affected, int expected, DataRow[] dataRows) inline static package
Definition at line 435 of file ADP.cs.
    {
        DBConcurrencyException ex = new DBConcurrencyException(System.SR.Format(statementType switch
        {
            StatementType.Update => System.SR.ADP_UpdateConcurrencyViolation_Update,
            StatementType.Delete => System.SR.ADP_UpdateConcurrencyViolation_Delete,
            StatementType.Batch => System.SR.ADP_UpdateConcurrencyViolation_Batch,
            _ => throw InvalidStatementType(statementType),
        }, affected.ToString(CultureInfo.InvariantCulture), expected.ToString(CultureInfo.InvariantCulture)), null, dataRows);
        TraceExceptionAsReturnValue(ex);
        return ex;
    }
References System.SR.Format(), System.Globalization.CultureInfo.InvariantCulture, and System.Data.Common.ADP.TraceExceptionAsReturnValue().
Referenced by System.Data.Common.DbDataAdapter.UpdateBatchExecute(), and System.Data.Common.DbDataAdapter.UpdateRowExecute().