Terraria: System.Data.Common.ADP.IsCatchableExceptionType
IsCatchableExceptionType()
static bool System.Data.Common.ADP.IsCatchableExceptionType (Exception e) inline static package
Definition at line 790 of file ADP.cs.
    {
        Type type = e.GetType();
        if (type != s_stackOverflowType && type != s_outOfMemoryType && type != s_threadAbortType && type != s_nullReferenceType && type != s_accessViolationType)
        {
            return !s_securityType.IsAssignableFrom(type);
        }
        return false;
    }
References System.Exception.GetType(), System.Data.Common.ADP.s_accessViolationType, System.Data.Common.ADP.s_nullReferenceType, System.Data.Common.ADP.s_outOfMemoryType, System.Data.Common.ADP.s_securityType, System.Data.Common.ADP.s_stackOverflowType, System.Data.Common.ADP.s_threadAbortType, and System.type.
Referenced by System.Data.Select.AcceptRecord(), System.Data.DataRelationCollection.DataSetRelationCollection.AddCore(), System.Data.NameNode.Bind(), System.Data.Constraint.CheckStateForProperty(), System.Data.DataRelation.CheckStateForProperty(), System.Data.SqlTypes.SqlXml.CreateSqlXmlReader(), System.Data.DataExpression.Evaluate(), System.Data.Common.DataAdapter.FillLoadDataRow(), System.Data.Common.DataAdapter.FillLoadDataRowChunk(), System.Data.Common.DataAdapter.FillMapping(), System.Data.Common.DataAdapter.FillNextResult(), System.Data.Common.DataRecordInternal.GetBytes(), System.Data.Common.DataRecordInternal.GetChars(), System.Data.XDRSchema.GetMinMax(), System.Xml.XmlDataDocument.HasPointers(), System.Data.Merger.MergeRelation(), System.Xml.XmlDataDocument.OnFoliated(), System.Data.DataView.OnListChanged(), System.Data.DataViewManager.OnListChanged(), System.Data.ExpressionParser.Parse(), System.Data.ExpressionParser.ParseAggregateArgument(), System.Data.DataTable.RaiseRowChanged(), System.Data.DataTable.RestoreIndexEvents(), System.Data.Common.DbCommandBuilder.RowUpdatingHandler(), System.Data.DataView.SetDataViewManager(), System.Data.DataSet.SetLocaleValue(), System.Data.XmlTreeGen.SetMSDataAttribute(), System.Data.DataTable.SetNewRecordWorker(), System.Xml.XmlDataDocument.SetRowValueFromXmlText(), System.Data.DataExpression.ToBoolean(), and System.Data.Common.DbDataAdapter.Update().