Terraria: System.Data.Common.ADP.IsCatchableOrSecurityExceptionType
IsCatchableOrSecurityExceptionType()
static bool System.Data.Common.ADP.IsCatchableOrSecurityExceptionType (Exception e) inline static package
Definition at line 800 of file ADP.cs.
    {
        Type type = e.GetType();
        if (type != s_stackOverflowType && type != s_outOfMemoryType && type != s_threadAbortType && type != s_nullReferenceType)
        {
            return type != s_accessViolationType;
        }
        return false;
    }
References System.Exception.GetType(), System.Data.Common.ADP.s_accessViolationType, System.Data.Common.ADP.s_nullReferenceType, System.Data.Common.ADP.s_outOfMemoryType, System.Data.Common.ADP.s_stackOverflowType, System.Data.Common.ADP.s_threadAbortType, and System.type.
Referenced by System.Data.DataColumnCollection.BaseAdd(), System.Data.ConstraintCollection.Clear(), System.Data.DataColumnCollection.Clear(), System.Data.RecordManager.CopyRecord(), System.Data.DataTable.NewRecordFromArray(), System.Data.ProviderBase.SchemaMapping.SetupSchemaWithKeyInfo(), and System.Data.ProviderBase.SchemaMapping.SetupSchemaWithoutKeyInfo().