Terraria: System.Xml.Serialization.XmlSerializationWriterILGen.WriteArray
WriteArray()
void System.Xml.Serialization.XmlSerializationWriterILGen.WriteArray (SourceInfo source, string choiceSource, ElementAccessor[] elements, TextAccessor text, ChoiceIdentifierAccessor choice, TypeDesc arrayTypeDesc) inline private
Definition at line 1191 of file XmlSerializationWriterILGen.cs.
    {
        if (elements.Length != 0 || text != null)
        {
            string cSharpName = arrayTypeDesc.CSharpName;
            string text2 = "a" + arrayTypeDesc.Name;
            ilg.EnterScope();
            WriteArrayLocalDecl(cSharpName, text2, source, arrayTypeDesc);
            LocalBuilder local = ilg.GetLocal(text2);
            if (arrayTypeDesc.IsNullable)
            {
                ilg.Ldloc(local);
                ilg.Load(null);
                ilg.If(Cmp.NotEqualTo);
            }
            string text3 = null;
            if (choice != null)
            {
                string cSharpName2 = choice.Mapping.TypeDesc.CSharpName;
                SourceInfo initValue = new SourceInfo(choiceSource, null, choice.MemberInfo, null, ilg);
                text3 = "c" + choice.Mapping.TypeDesc.Name;
                WriteArrayLocalDecl(cSharpName2 + "[]", text3, initValue, choice.Mapping.TypeDesc);
                Label label = ilg.DefineLabel();
                Label label2 = ilg.DefineLabel();
                LocalBuilder local2 = ilg.GetLocal(text3);
                ilg.Ldloc(local2);
                ilg.Load(null);
                ilg.Beq(label2);
                ilg.Ldloc(local2);
                ilg.Ldlen();
                ilg.Ldloc(local);
                ilg.Ldlen();
                ilg.Clt();
                ilg.Br(label);
                ilg.MarkLabel(label2);
                ilg.Ldc(boolVar: true);
                ilg.MarkLabel(label);
                ilg.If();
                MethodInfo method = typeof(XmlSerializationWriter).GetMethod("CreateInvalidChoiceIdentifierValueException", BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, new Type[2]
                {
                    typeof(string),
                    typeof(string)
                });
                ilg.Ldarg(0);
                ilg.Ldstr(GetCSharpString(choice.Mapping.TypeDesc.FullName));
                ilg.Ldstr(GetCSharpString(choice.MemberName));
                ilg.Call(method);
                ilg.Throw();
                ilg.EndIf();
            }
            WriteArrayItems(elements, text, choice, arrayTypeDesc, text2, text3);
            if (arrayTypeDesc.IsNullable)
            {
                ilg.EndIf();
            }
            ilg.ExitScope();
        }
    }
References System.Xml.Serialization.CodeGenerator.Beq(), System.Xml.Serialization.CodeGenerator.Br(), System.Xml.Serialization.CodeGenerator.Call(), System.Xml.Serialization.CodeGenerator.Clt(), System.Xml.Serialization.CodeGenerator.DefineLabel(), System.Xml.Dictionary, System.Xml.Serialization.CodeGenerator.EndIf(), System.Xml.Serialization.CodeGenerator.EnterScope(), System.Xml.Serialization.CodeGenerator.ExitScope(), System.Xml.Serialization.XmlSerializationILGen.GetCSharpString(), System.Xml.Serialization.CodeGenerator.GetLocal(), System.Xml.Serialization.CodeGenerator.If(), System.Xml.Serialization.XmlSerializationILGen.ilg, System.Xml.Serialization.CodeGenerator.Ldarg(), System.Xml.Serialization.CodeGenerator.Ldc(), System.Xml.Serialization.CodeGenerator.Ldlen(), System.Xml.Serialization.CodeGenerator.Ldloc(), System.Xml.Serialization.CodeGenerator.Ldstr(), System.Xml.Serialization.CodeGenerator.Load(), System.Xml.Serialization.CodeGenerator.MarkLabel(), System.source, System.text, System.Xml.Serialization.CodeGenerator.Throw(), System.Xml.Serialization.XmlSerializationWriterILGen.WriteArrayItems(), and System.Xml.Serialization.XmlSerializationWriterILGen.WriteArrayLocalDecl().
Referenced by System.Xml.Serialization.XmlSerializationWriterILGen.WriteMember().