Terraria: System.Xml.Serialization.XmlSerializationWriterILGen.WriteElements
WriteElements()
void System.Xml.Serialization.XmlSerializationWriterILGen.WriteElements (SourceInfo source, string enumSource, ElementAccessor[] elements, TextAccessor text, ChoiceIdentifierAccessor choice, string arrayName, bool writeAccessors, bool isNullable) inline private
Definition at line 1318 of file XmlSerializationWriterILGen.cs.
    {
        if (elements.Length == 0 && text == null)
        {
            return;
        }
        if (elements.Length == 1 && text == null)
        {
            TypeDesc td = (elements[0].IsUnbounded ? elements[0].Mapping.TypeDesc.CreateArrayTypeDesc() : elements[0].Mapping.TypeDesc);
            if (!elements[0].Any && !elements[0].Mapping.TypeDesc.IsOptionalValue)
            {
                source = source.CastTo(td);
            }
            WriteElement(source, elements[0], arrayName, writeAccessors);
            return;
        }
        bool flag = false;
        if (isNullable && choice == null)
        {
            source.Load(typeof(object));
            ilg.Load(null);
            ilg.If(Cmp.NotEqualTo);
            flag = true;
        }
        int num = 0;
        List<ElementAccessor> list = new List<ElementAccessor>();
        ElementAccessor elementAccessor = null;
        bool flag2 = false;
        string text2 = choice?.Mapping.TypeDesc.FullName;
        foreach (ElementAccessor elementAccessor2 in elements)
        {
            if (elementAccessor2.Any)
            {
                num++;
                if (elementAccessor2.Name != null && elementAccessor2.Name.Length > 0)
                {
                    list.Add(elementAccessor2);
                }
                else if (elementAccessor == null)
                {
                    elementAccessor = elementAccessor2;
                }
            }
            else if (choice != null)
            {
                string cSharpName = elementAccessor2.Mapping.TypeDesc.CSharpName;
                object eValue;
                string enumName = text2 + ".@" + FindChoiceEnumValue(elementAccessor2, (EnumMapping)choice.Mapping, out eValue);
                if (flag2)
                {
                    ilg.InitElseIf();
                }
                else
                {
                    flag2 = true;
                    ilg.InitIf();
                }
                ILGenLoad(enumSource, choice?.Mapping.TypeDesc.Type);
                ilg.Load(eValue);
                ilg.Ceq();
                if (isNullable && !elementAccessor2.IsNullable)
                {
                    Label label = ilg.DefineLabel();
                    Label label2 = ilg.DefineLabel();
                    ilg.Brfalse(label);
                    source.Load(typeof(object));
                    ilg.Load(null);
                    ilg.Cne();
                    ilg.Br_S(label2);
                    ilg.MarkLabel(label);
                    ilg.Ldc(boolVar: false);
                    ilg.MarkLabel(label2);
                }
                ilg.AndIf();
                WriteChoiceTypeCheck(source, cSharpName, choice, enumName, elementAccessor2.Mapping.TypeDesc);
                SourceInfo sourceInfo = source.CastTo(elementAccessor2.Mapping.TypeDesc);
                WriteElement(elementAccessor2.Any ? source : sourceInfo, elementAccessor2, arrayName, writeAccessors);
            }
            else
            {
                TypeDesc typeDesc = (elementAccessor2.IsUnbounded ? elementAccessor2.Mapping.TypeDesc.CreateArrayTypeDesc() : elementAccessor2.Mapping.TypeDesc);
                if (flag2)
                {
                    ilg.InitElseIf();
                }
                else
                {
                    flag2 = true;
                    ilg.InitIf();
                }
                WriteInstanceOf(source, typeDesc.Type);
                ilg.AndIf();
                SourceInfo sourceInfo2 = source.CastTo(typeDesc);
                WriteElement(elementAccessor2.Any ? source : sourceInfo2, elementAccessor2, arrayName, writeAccessors);
            }
        }
        if (flag2 && num > 0 && elements.Length - num <= 0)
        {
            ilg.EndIf();
        }
        if (num > 0)
        {
            if (elements.Length - num > 0)
            {
                ilg.InitElseIf();
            }
            else
            {
                ilg.InitIf();
            }
            source.Load(typeof(object));
            ilg.IsInst(typeof(XmlElement));
            ilg.Load(null);
            ilg.Cne();
            ilg.AndIf();
            LocalBuilder localBuilder = ilg.DeclareLocal(typeof(XmlElement), "elem");
            source.Load(typeof(XmlElement));
            ilg.Stloc(localBuilder);
            int num2 = 0;
            foreach (ElementAccessor item in list)
            {
                if (num2++ > 0)
                {
                    ilg.InitElseIf();
                }
                else
                {
                    ilg.InitIf();
                }
                string value = null;
                Label label3;
                Label label4;
                if (choice != null)
                {
                    value = text2 + ".@" + FindChoiceEnumValue(item, (EnumMapping)choice.Mapping, out var eValue2);
                    label3 = ilg.DefineLabel();
                    label4 = ilg.DefineLabel();
                    ILGenLoad(enumSource, choice?.Mapping.TypeDesc.Type);
                    ilg.Load(eValue2);
                    ilg.Bne(label3);
                    if (isNullable && !item.IsNullable)
                    {
                        source.Load(typeof(object));
                        ilg.Load(null);
                        ilg.Cne();
                    }
                    else
                    {
                        ilg.Ldc(boolVar: true);
                    }
                    ilg.Br(label4);
                    ilg.MarkLabel(label3);
                    ilg.Ldc(boolVar: false);
                    ilg.MarkLabel(label4);
                    ilg.AndIf();
                }
                label3 = ilg.DefineLabel();
                label4 = ilg.DefineLabel();
                MethodInfo method = typeof(XmlNode).GetMethod("get_Name", BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, Type.EmptyTypes);
                MethodInfo method2 = typeof(XmlNode).GetMethod("get_NamespaceURI", BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, Type.EmptyTypes);
                ilg.Ldloc(localBuilder);
                ilg.Call(method);
                ilg.Ldstr(GetCSharpString(item.Name));
                MethodInfo method3 = typeof(string).GetMethod("op_Equality", BindingFlags.Static | BindingFlags.Public | BindingFlags.NonPublic, new Type[2]
                {
                    typeof(string),
                    typeof(string)
                });
                ilg.Call(method3);
                ilg.Brfalse(label3);
                ilg.Ldloc(localBuilder);
                ilg.Call(method2);
                ilg.Ldstr(GetCSharpString(item.Namespace));
                ilg.Call(method3);
                ilg.Br(label4);
                ilg.MarkLabel(label3);
                ilg.Ldc(boolVar: false);
                ilg.MarkLabel(label4);
                if (choice != null)
                {
                    ilg.If();
                }
                else
                {
                    ilg.AndIf();
                }
                WriteElement(new SourceInfo("elem", null, null, localBuilder.LocalType, ilg), item, arrayName, writeAccessors);
                if (choice != null)
                {
                    ilg.Else();
                    MethodInfo method4 = typeof(XmlSerializationWriter).GetMethod("CreateChoiceIdentifierValueException", BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, new Type[4]
                    {
                        typeof(string),
                        typeof(string),
                        typeof(string),
                        typeof(string)
                    });
                    ilg.Ldarg(0);
                    ilg.Ldstr(GetCSharpString(value));
                    ilg.Ldstr(GetCSharpString(choice.MemberName));
                    ilg.Ldloc(localBuilder);
                    ilg.Call(method);
                    ilg.Ldloc(localBuilder);
                    ilg.Call(method2);
                    ilg.Call(method4);
                    ilg.Throw();
                    ilg.EndIf();
                }
            }
            if (num2 > 0)
            {
                ilg.Else();
            }
            if (elementAccessor != null)
            {
                WriteElement(new SourceInfo("elem", null, null, localBuilder.LocalType, ilg), elementAccessor, arrayName, writeAccessors);
            }
            else
            {
                MethodInfo method5 = typeof(XmlSerializationWriter).GetMethod("CreateUnknownAnyElementException", BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, new Type[2]
                {
                    typeof(string),
                    typeof(string)
                });
                ilg.Ldarg(0);
                ilg.Ldloc(localBuilder);
                MethodInfo method6 = typeof(XmlNode).GetMethod("get_Name", BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, Type.EmptyTypes);
                MethodInfo method7 = typeof(XmlNode).GetMethod("get_NamespaceURI", BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, Type.EmptyTypes);
                ilg.Call(method6);
                ilg.Ldloc(localBuilder);
                ilg.Call(method7);
                ilg.Call(method5);
                ilg.Throw();
            }
            if (num2 > 0)
            {
                ilg.EndIf();
            }
        }
        if (text != null)
        {
            if (elements.Length != 0)
            {
                ilg.InitElseIf();
                WriteInstanceOf(source, text.Mapping.TypeDesc.Type);
                ilg.AndIf();
                SourceInfo source2 = source.CastTo(text.Mapping.TypeDesc);
                WriteText(source2, text);
            }
            else
            {
                SourceInfo source3 = source.CastTo(text.Mapping.TypeDesc);
                WriteText(source3, text);
            }
        }
        if (elements.Length != 0)
        {
            if (isNullable)
            {
                ilg.InitElseIf();
                source.Load(null);
                ilg.Load(null);
                ilg.AndIf(Cmp.NotEqualTo);
            }
            else
            {
                ilg.Else();
            }
            MethodInfo method8 = typeof(XmlSerializationWriter).GetMethod("CreateUnknownTypeException", BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, new Type[1] { typeof(object) });
            ilg.Ldarg(0);
            source.Load(typeof(object));
            ilg.Call(method8);
            ilg.Throw();
            ilg.EndIf();
        }
        if (flag)
        {
            ilg.EndIf();
        }
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Xml.Serialization.CodeGenerator.AndIf(), System.Any, System.Xml.Serialization.CodeGenerator.Bne(), System.Xml.Serialization.CodeGenerator.Br(), System.Xml.Serialization.CodeGenerator.Br_S(), System.Xml.Serialization.CodeGenerator.Brfalse(), System.Xml.Serialization.CodeGenerator.Call(), System.Xml.Serialization.CodeGenerator.Ceq(), System.Xml.Serialization.CodeGenerator.Cne(), System.Xml.Serialization.TypeDesc.CreateArrayTypeDesc(), System.Xml.Serialization.CodeGenerator.DeclareLocal(), System.Xml.Serialization.CodeGenerator.DefineLabel(), System.Xml.Dictionary, System.Xml.Serialization.CodeGenerator.Else(), System.Type.EmptyTypes, System.Xml.Serialization.CodeGenerator.EndIf(), System.Xml.Serialization.XmlSerializationWriterILGen.FindChoiceEnumValue(), System.Xml.Serialization.XmlSerializationILGen.GetCSharpString(), System.Xml.Serialization.CodeGenerator.If(), System.Xml.Serialization.XmlSerializationILGen.ilg, System.Xml.Serialization.XmlSerializationILGen.ILGenLoad(), System.Xml.Serialization.CodeGenerator.InitElseIf(), System.Xml.Serialization.CodeGenerator.InitIf(), System.Xml.Serialization.CodeGenerator.IsInst(), System.Xml.Serialization.ElementAccessor.IsUnbounded, System.item, System.Xml.Serialization.CodeGenerator.Ldarg(), System.Xml.Serialization.CodeGenerator.Ldc(), System.Xml.Serialization.CodeGenerator.Ldloc(), System.Xml.Serialization.CodeGenerator.Ldstr(), System.list, System.Xml.Serialization.CodeGenerator.Load(), System.Xml.Serialization.Accessor.Mapping, System.Xml.Serialization.CodeGenerator.MarkLabel(), System.source, System.Xml.Serialization.CodeGenerator.Stloc(), System.text, System.Xml.Serialization.CodeGenerator.Throw(), System.Xml.Serialization.TypeMapping.TypeDesc, System.value, System.Xml.Serialization.XmlSerializationWriterILGen.WriteChoiceTypeCheck(), System.Xml.Serialization.XmlSerializationWriterILGen.WriteElement(), System.Xml.Serialization.XmlSerializationWriterILGen.WriteInstanceOf(), and System.Xml.Serialization.XmlSerializationWriterILGen.WriteText().
Referenced by System.Xml.Serialization.XmlSerializationWriterILGen.WriteArrayItems(), and System.Xml.Serialization.XmlSerializationWriterILGen.WriteMember().