Terraria: System.Xml.Serialization.XmlSerializationWriterILGen.WriteCheckDefault
WriteCheckDefault()
void System.Xml.Serialization.XmlSerializationWriterILGen.WriteCheckDefault (SourceInfo source, object value, bool isNullable) inline private
Definition at line 1795 of file XmlSerializationWriterILGen.cs.
    {
        if (value is string && ((string)value).Length == 0)
        {
            Label label = ilg.DefineLabel();
            Label label2 = ilg.DefineLabel();
            Label label3 = ilg.DefineLabel();
            source.Load(typeof(string));
            if (isNullable)
            {
                ilg.Brfalse(label3);
            }
            else
            {
                ilg.Brfalse(label2);
            }
            MethodInfo method = typeof(string).GetMethod("get_Length", BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, Type.EmptyTypes);
            source.Load(typeof(string));
            ilg.Call(method);
            ilg.Ldc(0);
            ilg.Cne();
            ilg.Br(label);
            if (isNullable)
            {
                ilg.MarkLabel(label3);
                ilg.Ldc(boolVar: true);
            }
            else
            {
                ilg.MarkLabel(label2);
                ilg.Ldc(boolVar: false);
            }
            ilg.MarkLabel(label);
            ilg.If();
            return;
        }
        if (value == null)
        {
            source.Load(typeof(object));
            ilg.Load(null);
            ilg.Cne();
        }
        else if (value.GetType().IsPrimitive)
        {
            source.Load(null);
            ilg.Ldc(Convert.ChangeType(value, source.Type, CultureInfo.InvariantCulture));
            ilg.Cne();
        }
        else
        {
            Type type = value.GetType();
            source.Load(type);
            ilg.Ldc((value is string) ? GetCSharpString((string)value) : value);
            MethodInfo method2 = type.GetMethod("op_Inequality", BindingFlags.Static | BindingFlags.Public | BindingFlags.NonPublic, new Type[2] { type, type });
            if (method2 != null)
            {
                ilg.Call(method2);
            }
            else
            {
                ilg.Cne();
            }
        }
        ilg.If();
    }
References System.Xml.Serialization.CodeGenerator.Br(), System.Xml.Serialization.CodeGenerator.Brfalse(), System.Xml.Serialization.CodeGenerator.Call(), System.Convert.ChangeType(), System.Xml.Serialization.CodeGenerator.Cne(), System.Xml.Serialization.CodeGenerator.DefineLabel(), System.Xml.Dictionary, System.Type.EmptyTypes, System.Xml.Serialization.XmlSerializationILGen.GetCSharpString(), System.Type.GetType(), System.Xml.Serialization.CodeGenerator.If(), System.Xml.Serialization.XmlSerializationILGen.ilg, System.Globalization.CultureInfo.InvariantCulture, System.Xml.Serialization.CodeGenerator.Ldc(), System.Xml.Schema.Length, System.Xml.Serialization.CodeGenerator.Load(), System.Xml.Serialization.CodeGenerator.MarkLabel(), System.source, System.type, and System.value.
Referenced by System.Xml.Serialization.XmlSerializationWriterILGen.WritePrimitive().