Terraria: System.Xml.Serialization.XmlSerializationWriterILGen.GenerateEnd
GenerateEnd()
Type System.Xml.Serialization.XmlSerializationWriterILGen.GenerateEnd () inline package
Definition at line 56 of file XmlSerializationWriterILGen.cs.
    {
        GenerateReferencedMethods();
        GenerateInitCallbacksMethod();
        typeBuilder.DefineDefaultConstructor(MethodAttributes.Public | MethodAttributes.HideBySig);
        return typeBuilder.CreateTypeInfo().AsType();
    }
References System.Reflection.TypeInfo.AsType(), System.Reflection.Emit.TypeBuilder.CreateTypeInfo(), System.Reflection.Emit.TypeBuilder.DefineDefaultConstructor(), System.Xml.Serialization.XmlSerializationWriterILGen.GenerateInitCallbacksMethod(), System.Xml.Serialization.XmlSerializationILGen.GenerateReferencedMethods(), and System.Xml.Serialization.XmlSerializationILGen.typeBuilder.