Terraria: System.Xml.Serialization.XmlSerializationWriterILGen.GenerateTypeElement
GenerateTypeElement()
string System.Xml.Serialization.XmlSerializationWriterILGen.GenerateTypeElement (XmlTypeMapping xmlTypeMapping) inline private
Definition at line 471 of file XmlSerializationWriterILGen.cs.
    {
        ElementAccessor accessor = xmlTypeMapping.Accessor;
        TypeMapping mapping = accessor.Mapping;
        string text = NextMethodName(accessor.Name);
        ilg = new CodeGenerator(typeBuilder);
        ilg.BeginMethod(typeof(void), text, new Type[1] { typeof(object) }, new string[1] { "o" }, MethodAttributes.Public | MethodAttributes.HideBySig);
        MethodInfo method = typeof(XmlSerializationWriter).GetMethod("WriteStartDocument", BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, Type.EmptyTypes);
        ilg.Ldarg(0);
        ilg.Call(method);
        ilg.If(ilg.GetArg("o"), Cmp.EqualTo, null);
        if (accessor.IsNullable)
        {
            WriteLiteralNullTag(accessor.Name, (accessor.Form == XmlSchemaForm.Qualified) ? accessor.Namespace : "");
        }
        else
        {
            WriteEmptyTag(accessor.Name, (accessor.Form == XmlSchemaForm.Qualified) ? accessor.Namespace : "");
        }
        ilg.GotoMethodEnd();
        ilg.EndIf();
        if (!mapping.TypeDesc.IsValueType && !mapping.TypeDesc.Type.IsPrimitive)
        {
            MethodInfo method2 = typeof(XmlSerializationWriter).GetMethod("TopLevelElement", BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, Type.EmptyTypes);
            ilg.Ldarg(0);
            ilg.Call(method2);
        }
        WriteMember(new SourceInfo("o", "o", null, typeof(object), ilg), null, new ElementAccessor[1] { accessor }, null, null, mapping.TypeDesc, writeAccessors: true);
        ilg.EndMethod();
        return text;
    }
References System.Xml.Serialization.CodeGenerator.BeginMethod(), System.Xml.Serialization.CodeGenerator.Call(), System.Xml.Dictionary, System.Type.EmptyTypes, System.Xml.Serialization.CodeGenerator.EndIf(), System.Xml.Serialization.CodeGenerator.EndMethod(), System.Xml.Serialization.CodeGenerator.GetArg(), System.Xml.Serialization.CodeGenerator.GotoMethodEnd(), System.Xml.Serialization.CodeGenerator.If(), System.Xml.Serialization.XmlSerializationILGen.ilg, System.Xml.Serialization.CodeGenerator.Ldarg(), System.Xml.Serialization.XmlSerializationWriterILGen.NextMethodName(), System.text, System.Xml.Serialization.XmlSerializationILGen.typeBuilder, System.Xml.Serialization.XmlSerializationWriterILGen.WriteEmptyTag(), System.Xml.Serialization.XmlSerializationWriterILGen.WriteLiteralNullTag(), and System.Xml.Serialization.XmlSerializationWriterILGen.WriteMember().
Referenced by System.Xml.Serialization.XmlSerializationWriterILGen.GenerateElement().