Terraria: System.Xml.Serialization.XmlSerializationWriterILGen.WriteElementCall
WriteElementCall()
void System.Xml.Serialization.XmlSerializationWriterILGen.WriteElementCall (string func, Type cast, SourceInfo source, string name, string ns, bool isNullable, bool isAny) inline private
Definition at line 1775 of file XmlSerializationWriterILGen.cs.
    {
        MethodInfo method = typeof(XmlSerializationWriter).GetMethod(func, BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, new Type[5]
        {
            cast,
            typeof(string),
            typeof(string),
            typeof(bool),
            typeof(bool)
        });
        ilg.Ldarg(0);
        source.Load(cast);
        ilg.Ldstr(GetCSharpString(name));
        ilg.Ldstr(GetCSharpString(ns));
        ilg.Ldc(isNullable);
        ilg.Ldc(isAny);
        ilg.Call(method);
    }
References System.Xml.Serialization.CodeGenerator.Call(), System.Xml.Dictionary, System.Xml.Serialization.XmlSerializationILGen.GetCSharpString(), System.Xml.Serialization.XmlSerializationILGen.ilg, System.Xml.Serialization.CodeGenerator.Ldarg(), System.Xml.Serialization.CodeGenerator.Ldc(), System.Xml.Serialization.CodeGenerator.Ldstr(), and System.source.
Referenced by System.Xml.Serialization.XmlSerializationWriterILGen.WriteElement().