Terraria: System.Xml.Serialization.XmlSerializationWriterILGen.FindChoiceEnumValue
FindChoiceEnumValue()
string System.Xml.Serialization.XmlSerializationWriterILGen.FindChoiceEnumValue (ElementAccessor element, EnumMapping choiceMapping, out object eValue) inline private
Definition at line 1952 of file XmlSerializationWriterILGen.cs.
    {
        string text = null;
        eValue = null;
        for (int i = 0; i < choiceMapping.Constants.Length; i++)
        {
            string xmlName = choiceMapping.Constants[i].XmlName;
            if (element.Any && element.Name.Length == 0)
            {
                if (xmlName == "##any:")
                {
                    text = choiceMapping.Constants[i].Name;
                    eValue = Enum.ToObject(choiceMapping.TypeDesc.Type, choiceMapping.Constants[i].Value);
                    break;
                }
                continue;
            }
            int num = xmlName.LastIndexOf(':');
            string text2 = ((num < 0) ? choiceMapping.Namespace : xmlName.Substring(0, num));
            string text3 = ((num < 0) ? xmlName : xmlName.Substring(num + 1));
            if (element.Name == text3 && ((element.Form == XmlSchemaForm.Unqualified && string.IsNullOrEmpty(text2)) || element.Namespace == text2))
            {
                text = choiceMapping.Constants[i].Name;
                eValue = Enum.ToObject(choiceMapping.TypeDesc.Type, choiceMapping.Constants[i].Value);
                break;
            }
        }
        if (text == null || text.Length == 0)
        {
            if (element.Any && element.Name.Length == 0)
            {
                throw new InvalidOperationException(System.SR.Format(System.SR.XmlChoiceMissingAnyValue, choiceMapping.TypeDesc.FullName));
            }
            throw new InvalidOperationException(System.SR.Format(System.SR.XmlChoiceMissingValue, choiceMapping.TypeDesc.FullName, element.Namespace + ":" + element.Name, element.Name, element.Namespace));
        }
        CodeIdentifier.CheckValidIdentifier(text);
        return text;
    }
References System.Xml.Serialization.Accessor.Any, System.Xml.Serialization.CodeIdentifier.CheckValidIdentifier(), System.Xml.Serialization.Accessor.Form, System.SR.Format(), System.Xml.Serialization.Accessor.Name, System.Xml.Serialization.Accessor.Namespace, System.text, System.Enum.ToObject(), System.SR.XmlChoiceMissingAnyValue, and System.SR.XmlChoiceMissingValue.
Referenced by System.Xml.Serialization.XmlSerializationWriterILGen.WriteElements().