Terraria: System.Xml.Serialization.XmlSerializationWriterILGen.GenerateMembersElement
GenerateMembersElement()
string System.Xml.Serialization.XmlSerializationWriterILGen.GenerateMembersElement (XmlMembersMapping xmlMembersMapping) inline private
Definition at line 316 of file XmlSerializationWriterILGen.cs.
    {
        ElementAccessor accessor = xmlMembersMapping.Accessor;
        MembersMapping membersMapping = (MembersMapping)accessor.Mapping;
        bool hasWrapperElement = membersMapping.HasWrapperElement;
        bool writeAccessors = membersMapping.WriteAccessors;
        string text = NextMethodName(accessor.Name);
        ilg = new CodeGenerator(typeBuilder);
        ilg.BeginMethod(typeof(void), text, new Type[1] { typeof(object[]) }, new string[1] { "p" }, MethodAttributes.Public | MethodAttributes.HideBySig);
        MethodInfo method = typeof(XmlSerializationWriter).GetMethod("WriteStartDocument", BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, Type.EmptyTypes);
        ilg.Ldarg(0);
        ilg.Call(method);
        MethodInfo method2 = typeof(XmlSerializationWriter).GetMethod("TopLevelElement", BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, Type.EmptyTypes);
        ilg.Ldarg(0);
        ilg.Call(method2);
        LocalBuilder localBuilder = ilg.DeclareLocal(typeof(int), "pLength");
        ilg.Ldarg("p");
        ilg.Ldlen();
        ilg.Stloc(localBuilder);
        if (hasWrapperElement)
        {
            WriteStartElement(accessor.Name, (accessor.Form == XmlSchemaForm.Qualified) ? accessor.Namespace : "", writePrefixed: false);
            int num = FindXmlnsIndex(membersMapping.Members);
            if (num >= 0)
            {
                IFormatProvider invariantCulture = CultureInfo.InvariantCulture;
                DefaultInterpolatedStringHandler handler = new DefaultInterpolatedStringHandler(7, 2, invariantCulture);
                handler.AppendLiteral("((");
                handler.AppendFormatted(typeof(XmlSerializerNamespaces).FullName);
                handler.AppendLiteral(")p[");
                handler.AppendFormatted(num);
                handler.AppendLiteral("])");
                string source = string.Create(invariantCulture, ref handler);
                ilg.Ldloc(localBuilder);
                ilg.Ldc(num);
                ilg.If(Cmp.GreaterThan);
                WriteNamespaces(source);
                ilg.EndIf();
            }
            for (int i = 0; i < membersMapping.Members.Length; i++)
            {
                MemberMapping memberMapping = membersMapping.Members[i];
                if (memberMapping.Attribute == null || memberMapping.Ignore)
                {
                    continue;
                }
                SourceInfo source2 = new SourceInfo($"p[{i}]", null, null, localBuilder.LocalType.GetElementType(), ilg);
                SourceInfo sourceInfo = null;
                int intVar = 0;
                if (memberMapping.CheckSpecified != 0)
                {
                    string text2 = memberMapping.Name + "Specified";
                    for (int j = 0; j < membersMapping.Members.Length; j++)
                    {
                        if (membersMapping.Members[j].Name == text2)
{
                            sourceInfo = new SourceInfo($"((bool)p[{j}])", null, null, typeof(bool), ilg);
                            intVar = j;
                            break;
                        }
                    }
                }
                ilg.Ldloc(localBuilder);
                ilg.Ldc(i);
                ilg.If(Cmp.GreaterThan);
                if (sourceInfo != null)
                {
                    Label label = ilg.DefineLabel();
                    Label label2 = ilg.DefineLabel();
                    ilg.Ldloc(localBuilder);
                    ilg.Ldc(intVar);
                    ilg.Ble(label);
                    sourceInfo.Load(typeof(bool));
                    ilg.Br_S(label2);
                    ilg.MarkLabel(label);
                    ilg.Ldc(boolVar: true);
                    ilg.MarkLabel(label2);
                    ilg.If();
                }
                WriteMember(source2, memberMapping.Attribute, memberMapping.TypeDesc, "p");
                if (sourceInfo != null)
                {
                    ilg.EndIf();
                }
                ilg.EndIf();
            }
        }
        for (int k = 0; k < membersMapping.Members.Length; k++)
        {
            MemberMapping memberMapping2 = membersMapping.Members[k];
            if (memberMapping2.Xmlns != null || memberMapping2.Ignore)
            {
                continue;
            }
            SourceInfo sourceInfo2 = null;
            int intVar2 = 0;
            if (memberMapping2.CheckSpecified != 0)
            {
                string text3 = memberMapping2.Name + "Specified";
                for (int l = 0; l < membersMapping.Members.Length; l++)
                {
                    if (membersMapping.Members[l].Name == text3)
                    {
                        sourceInfo2 = new SourceInfo($"((bool)p[{l}])", null, null, typeof(bool), ilg);
                        intVar2 = l;
                        break;
                    }
                }
            }
            ilg.Ldloc(localBuilder);
            ilg.Ldc(k);
            ilg.If(Cmp.GreaterThan);
            if (sourceInfo2 != null)
            {
                Label label3 = ilg.DefineLabel();
                Label label4 = ilg.DefineLabel();
                ilg.Ldloc(localBuilder);
                ilg.Ldc(intVar2);
                ilg.Ble(label3);
                sourceInfo2.Load(typeof(bool));
                ilg.Br_S(label4);
                ilg.MarkLabel(label3);
                ilg.Ldc(boolVar: true);
                ilg.MarkLabel(label4);
                ilg.If();
            }
            string text4 = $"p[{k}]";
            string choiceSource = null;
            if (memberMapping2.ChoiceIdentifier != null)
            {
                for (int m = 0; m < membersMapping.Members.Length; m++)
                {
                    if (membersMapping.Members[m].Name == memberMapping2.ChoiceIdentifier.MemberName)
                    {
                        choiceSource = $"(({membersMapping.Members[m].TypeDesc.CSharpName})p[{m}])";
                        break;
                    }
                }
            }
            WriteMember(new SourceInfo(text4, text4, null, null, ilg), choiceSource, memberMapping2.ElementsSortedByDerivation, memberMapping2.Text, memberMapping2.ChoiceIdentifier, memberMapping2.TypeDesc, writeAccessors || hasWrapperElement);
            if (sourceInfo2 != null)
            {
                ilg.EndIf();
            }
            ilg.EndIf();
        }
        if (hasWrapperElement)
        {
            WriteEndElement();
        }
        ilg.EndMethod();
        return text;
    }
References System.Runtime.CompilerServices.DefaultInterpolatedStringHandler.AppendFormatted(), System.Runtime.CompilerServices.DefaultInterpolatedStringHandler.AppendLiteral(), System.Xml.Serialization.CodeGenerator.BeginMethod(), System.Xml.Serialization.CodeGenerator.Ble(), System.Xml.Serialization.CodeGenerator.Br_S(), System.Xml.Serialization.CodeGenerator.Call(), System.Xml.Serialization.CodeGenerator.DeclareLocal(), System.Xml.Serialization.CodeGenerator.DefineLabel(), System.Xml.Dictionary, System.Type.EmptyTypes, System.Xml.Serialization.CodeGenerator.EndIf(), System.Xml.Serialization.CodeGenerator.EndMethod(), System.Xml.Serialization.XmlSerializationWriterILGen.FindXmlnsIndex(), System.FullName, System.Xml.Serialization.CodeGenerator.If(), System.Xml.Serialization.XmlSerializationILGen.ilg, System.Globalization.CultureInfo.InvariantCulture, System.Xml.Serialization.CodeGenerator.Ldarg(), System.Xml.Serialization.CodeGenerator.Ldc(), System.Xml.Serialization.CodeGenerator.Ldlen(), System.Xml.Serialization.CodeGenerator.Ldloc(), System.Xml.Serialization.CodeGenerator.MarkLabel(), System.Xml.Serialization.XmlSerializationWriterILGen.NextMethodName(), System.source, System.Xml.Serialization.CodeGenerator.Stloc(), System.text, System.Xml.Serialization.XmlSerializationILGen.typeBuilder, System.Xml.Serialization.XmlSerializationWriterILGen.WriteEndElement(), System.Xml.Serialization.XmlSerializationWriterILGen.WriteMember(), System.Xml.Serialization.XmlSerializationWriterILGen.WriteNamespaces(), and System.Xml.Serialization.XmlSerializationWriterILGen.WriteStartElement().
Referenced by System.Xml.Serialization.XmlSerializationWriterILGen.GenerateElement().