Terraria: System.Xml.Serialization.XmlSerializationWriterILGen.WriteEnumAndArrayTypes
WriteEnumAndArrayTypes()
void System.Xml.Serialization.XmlSerializationWriterILGen.WriteEnumAndArrayTypes () inline private
Definition at line 661 of file XmlSerializationWriterILGen.cs.
    {
        TypeScope[] scopes = base.Scopes;
        foreach (TypeScope typeScope in scopes)
        {
            foreach (Mapping typeMapping in typeScope.TypeMappings)
            {
                if (typeMapping is EnumMapping)
                {
                    EnumMapping enumMapping = (EnumMapping)typeMapping;
                    ilg.InitElseIf();
                    WriteTypeCompare("t", enumMapping.TypeDesc.Type);
                    ilg.AndIf();
                    string methodName = ReferenceMapping(enumMapping);
                    MethodInfo method = typeof(XmlSerializationWriter).GetMethod("get_Writer", BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, Type.EmptyTypes);
                    MethodInfo method2 = typeof(XmlWriter).GetMethod("WriteStartElement", BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, new Type[2]
                    {
                        typeof(string),
                        typeof(string)
                    });
                    ilg.Ldarg(0);
                    ilg.Call(method);
                    ilg.Ldarg("n");
                    ilg.Ldarg("ns");
                    ilg.Call(method2);
                    MethodInfo method3 = typeof(XmlSerializationWriter).GetMethod("WriteXsiType", BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, new Type[2]
                    {
                        typeof(string),
                        typeof(string)
                    });
                    ilg.Ldarg(0);
                    ilg.Ldstr(GetCSharpString(enumMapping.TypeName));
                    ilg.Ldstr(GetCSharpString(enumMapping.Namespace));
                    ilg.Call(method3);
                    MethodBuilder methodInfo = EnsureMethodBuilder(typeBuilder, methodName, MethodAttributes.Private | MethodAttributes.HideBySig, typeof(string), new Type[1] { enumMapping.TypeDesc.Type });
                    MethodInfo method4 = typeof(XmlWriter).GetMethod("WriteString", BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, new Type[1] { typeof(string) });
                    ilg.Ldarg(0);
                    ilg.Call(method);
                    object variable = ilg.GetVariable("o");
                    ilg.Ldarg(0);
                    ilg.Load(variable);
                    ilg.ConvertValue(ilg.GetVariableType(variable), enumMapping.TypeDesc.Type);
                    ilg.Call(methodInfo);
                    ilg.Call(method4);
                    MethodInfo method5 = typeof(XmlWriter).GetMethod("WriteEndElement", BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, Type.EmptyTypes);
                    ilg.Ldarg(0);
                    ilg.Call(method);
                    ilg.Call(method5);
                    ilg.GotoMethodEnd();
                }
                else if (typeMapping is ArrayMapping && typeMapping is ArrayMapping arrayMapping)
                {
                    ilg.InitElseIf();
                    if (arrayMapping.TypeDesc.IsArray)
                    {
                        WriteArrayTypeCompare("t", arrayMapping.TypeDesc.Type);
                    }
                    else
                    {
                        WriteTypeCompare("t", arrayMapping.TypeDesc.Type);
                    }
                    ilg.AndIf();
                    ilg.EnterScope();
                    MethodInfo method6 = typeof(XmlSerializationWriter).GetMethod("get_Writer", BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, Type.EmptyTypes);
                    MethodInfo method7 = typeof(XmlWriter).GetMethod("WriteStartElement", BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, new Type[2]
                    {
                        typeof(string),
                        typeof(string)
                    });
                    ilg.Ldarg(0);
                    ilg.Call(method6);
                    ilg.Ldarg("n");
                    ilg.Ldarg("ns");
                    ilg.Call(method7);
                    MethodInfo method8 = typeof(XmlSerializationWriter).GetMethod("WriteXsiType", BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, new Type[2]
                    {
                        typeof(string),
                        typeof(string)
                    });
                    ilg.Ldarg(0);
                    ilg.Ldstr(GetCSharpString(arrayMapping.TypeName));
                    ilg.Ldstr(GetCSharpString(arrayMapping.Namespace));
                    ilg.Call(method8);
                    WriteMember(new SourceInfo("o", "o", null, null, ilg), null, arrayMapping.ElementsSortedByDerivation, null, null, arrayMapping.TypeDesc, writeAccessors: true);
                    MethodInfo method9 = typeof(XmlWriter).GetMethod("WriteEndElement", BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, Type.EmptyTypes);
                    ilg.Ldarg(0);
                    ilg.Call(method6);
                    ilg.Call(method9);
                    ilg.GotoMethodEnd();
                    ilg.ExitScope();
                }
            }
        }
    }
References System.Xml.Serialization.CodeGenerator.AndIf(), System.Xml.Serialization.CodeGenerator.Call(), System.Xml.Serialization.CodeGenerator.ConvertValue(), System.Xml.Dictionary, System.Type.EmptyTypes, System.Xml.Serialization.XmlSerializationILGen.EnsureMethodBuilder(), System.Xml.Serialization.CodeGenerator.EnterScope(), System.Xml.Serialization.CodeGenerator.ExitScope(), System.Xml.Serialization.XmlSerializationILGen.GetCSharpString(), System.Xml.Serialization.CodeGenerator.GetVariable(), System.Xml.Serialization.CodeGenerator.GetVariableType(), System.Xml.Serialization.CodeGenerator.GotoMethodEnd(), System.Xml.Serialization.XmlSerializationILGen.ilg, System.Xml.Serialization.CodeGenerator.InitElseIf(), System.Xml.Serialization.CodeGenerator.Ldarg(), System.Xml.Serialization.CodeGenerator.Ldstr(), System.Xml.Serialization.CodeGenerator.Load(), System.Xml.Serialization.XmlSerializationILGen.ReferenceMapping(), System.Xml.Serialization.XmlSerializationILGen.typeBuilder, System.Xml.Serialization.XmlSerializationWriterILGen.WriteArrayTypeCompare(), System.Xml.Serialization.XmlSerializationWriterILGen.WriteMember(), and System.Xml.Serialization.XmlSerializationWriterILGen.WriteTypeCompare().
Referenced by System.Xml.Serialization.XmlSerializationWriterILGen.WriteStructMethod().