Terraria: System.Xml.Serialization.XmlSerializationWriterILGen.WriteMember
WriteMember() [1/2]
void System.Xml.Serialization.XmlSerializationWriterILGen.WriteMember (SourceInfo source, AttributeAccessor attribute, TypeDesc memberTypeDesc, string parent) inline private
Definition at line 972 of file XmlSerializationWriterILGen.cs.
    {
        if (memberTypeDesc.IsAbstract)
        {
            return;
        }
        if (memberTypeDesc.IsArrayLike)
        {
            string text = "a" + memberTypeDesc.Name;
            string text2 = "ai" + memberTypeDesc.Name;
            string text3 = "i";
            string cSharpName = memberTypeDesc.CSharpName;
            ilg.EnterScope();
            WriteArrayLocalDecl(cSharpName, text, source, memberTypeDesc);
            if (memberTypeDesc.IsNullable)
            {
                ilg.Ldloc(memberTypeDesc.Type, text);
                ilg.Load(null);
                ilg.If(Cmp.NotEqualTo);
            }
            if (attribute.IsList)
            {
                if (CanOptimizeWriteListSequence(memberTypeDesc.ArrayElementTypeDesc))
                {
                    string value = ((attribute.Form == XmlSchemaForm.Qualified) ? attribute.Namespace : string.Empty);
                    MethodInfo method = typeof(XmlSerializationWriter).GetMethod("get_Writer", BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, Type.EmptyTypes);
                    MethodInfo method2 = typeof(XmlWriter).GetMethod("WriteStartAttribute", BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, new Type[3]
                    {
                        typeof(string),
                        typeof(string),
                        typeof(string)
                    });
                    ilg.Ldarg(0);
                    ilg.Call(method);
                    ilg.Load(null);
                    ilg.Ldstr(GetCSharpString(attribute.Name));
                    ilg.Ldstr(GetCSharpString(value));
                    ilg.Call(method2);
                }
                else
                {
                    LocalBuilder local = ilg.DeclareOrGetLocal(typeof(StringBuilder), "sb");
                    ConstructorInfo constructor = typeof(StringBuilder).GetConstructor(BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, Type.EmptyTypes);
                    ilg.New(constructor);
                    ilg.Stloc(local);
                }
            }
            TypeDesc arrayElementTypeDesc = memberTypeDesc.ArrayElementTypeDesc;
            if (memberTypeDesc.IsEnumerable)
            {
                throw Globals.NotSupported("Also fail in IEnumerable member with XmlAttributeAttribute");
            }
            LocalBuilder local2 = ilg.DeclareOrGetLocal(typeof(int), text3);
            ilg.For(local2, 0, ilg.GetLocal(text));
            WriteLocalDecl(text2, base.RaCodeGen.GetStringForArrayMember(text, text3, memberTypeDesc), arrayElementTypeDesc.Type);
            if (attribute.IsList)
            {
                Type returnType = typeof(string);
                string name;
                Type typeFromHandle;
                if (CanOptimizeWriteListSequence(memberTypeDesc.ArrayElementTypeDesc))
                {
                    ilg.Ldloc(text3);
                    ilg.Ldc(0);
                    ilg.If(Cmp.NotEqualTo);
                    MethodInfo method3 = typeof(XmlSerializationWriter).GetMethod("get_Writer", BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, Type.EmptyTypes);
                    MethodInfo method4 = typeof(XmlWriter).GetMethod("WriteString", BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, new Type[1] { typeof(string) });
                    ilg.Ldarg(0);
                    ilg.Call(method3);
                    ilg.Ldstr(" ");
                    ilg.Call(method4);
                    ilg.EndIf();
                    ilg.Ldarg(0);
                    name = "WriteValue";
                    typeFromHandle = typeof(XmlSerializationWriter);
                }
                else
                {
                    MethodInfo method5 = typeof(StringBuilder).GetMethod("Append", BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, new Type[1] { typeof(string) });
                    ilg.Ldloc(text3);
                    ilg.Ldc(0);
                    ilg.If(Cmp.NotEqualTo);
                    ilg.Ldloc("sb");
                    ilg.Ldstr(" ");
                    ilg.Call(method5);
                    ilg.Pop();
                    ilg.EndIf();
                    ilg.Ldloc("sb");
                    name = "Append";
                    typeFromHandle = typeof(StringBuilder);
                }
                if (attribute.Mapping is EnumMapping)
                {
                    WriteEnumValue((EnumMapping)attribute.Mapping, new SourceInfo(text2, text2, null, arrayElementTypeDesc.Type, ilg), out returnType);
                }
                else
                {
                    WritePrimitiveValue(arrayElementTypeDesc, new SourceInfo(text2, text2, null, arrayElementTypeDesc.Type, ilg), out returnType);
                }
                MethodInfo method6 = typeFromHandle.GetMethod(name, BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, new Type[1] { returnType });
                ilg.Call(method6);
                if (method6.ReturnType != typeof(void))
                {
                    ilg.Pop();
                }
            }
            else
            {
                WriteAttribute(new SourceInfo(text2, text2, null, null, ilg), attribute, parent);
            }
            if (memberTypeDesc.IsEnumerable)
            {
                throw Globals.NotSupported("Also fail in whidbey IEnumerable member with XmlAttributeAttribute");
            }
            ilg.EndFor();
            if (attribute.IsList)
            {
                if (CanOptimizeWriteListSequence(memberTypeDesc.ArrayElementTypeDesc))
                {
                    MethodInfo method7 = typeof(XmlSerializationWriter).GetMethod("get_Writer", BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, Type.EmptyTypes);
                    MethodInfo method8 = typeof(XmlWriter).GetMethod("WriteEndAttribute", BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, Type.EmptyTypes);
                    ilg.Ldarg(0);
                    ilg.Call(method7);
                    ilg.Call(method8);
                }
                else
                {
                    MethodInfo method9 = typeof(StringBuilder).GetMethod("get_Length", BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, Type.EmptyTypes);
                    ilg.Ldloc("sb");
                    ilg.Call(method9);
                    ilg.Ldc(0);
                    ilg.If(Cmp.NotEqualTo);
                    List<Type> list = new List<Type>();
                    ilg.Ldarg(0);
                    ilg.Ldstr(GetCSharpString(attribute.Name));
                    list.Add(typeof(string));
                    string text4 = ((attribute.Form == XmlSchemaForm.Qualified) ? attribute.Namespace : string.Empty);
                    if (text4 != null)
                    {
                        ilg.Ldstr(GetCSharpString(text4));
                        list.Add(typeof(string));
                    }
                    MethodInfo method10 = typeof(object).GetMethod("ToString", BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, Type.EmptyTypes);
                    ilg.Ldloc("sb");
                    ilg.Call(method10);
                    list.Add(typeof(string));
                    MethodInfo method11 = typeof(XmlSerializationWriter).GetMethod("WriteAttribute", BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, list.ToArray());
                    ilg.Call(method11);
                    ilg.EndIf();
                }
            }
            if (memberTypeDesc.IsNullable)
            {
                ilg.EndIf();
            }
            ilg.ExitScope();
        }
        else
        {
            WriteAttribute(source, attribute, parent);
        }
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Xml.Serialization.CodeGenerator.Call(), System.Xml.Serialization.XmlSerializationWriterILGen.CanOptimizeWriteListSequence(), System.Xml.Serialization.CodeGenerator.DeclareOrGetLocal(), System.Xml.Dictionary, System.Type.EmptyTypes, System.Xml.Serialization.CodeGenerator.EndFor(), System.Xml.Serialization.CodeGenerator.EndIf(), System.Xml.Serialization.CodeGenerator.EnterScope(), System.Xml.Serialization.CodeGenerator.ExitScope(), System.Xml.Serialization.CodeGenerator.For(), System.Xml.Serialization.XmlSerializationILGen.GetCSharpString(), System.Xml.Serialization.CodeGenerator.GetLocal(), System.Xml.Serialization.CodeGenerator.If(), System.Xml.Serialization.XmlSerializationILGen.ilg, System.Xml.Serialization.CodeGenerator.Ldarg(), System.Xml.Serialization.CodeGenerator.Ldc(), System.Xml.Serialization.CodeGenerator.Ldloc(), System.Xml.Serialization.CodeGenerator.Ldstr(), System.list, System.Xml.Serialization.CodeGenerator.Load(), System.Xml.Serialization.CodeGenerator.New(), System.Xml.Serialization.Globals.NotSupported(), System.Xml.Serialization.CodeGenerator.Pop(), System.source, System.Xml.Serialization.CodeGenerator.Stloc(), System.text, System.value, System.Xml.Serialization.XmlSerializationWriterILGen.WriteArrayLocalDecl(), System.Xml.Serialization.XmlSerializationWriterILGen.WriteAttribute(), System.Xml.Serialization.XmlSerializationWriterILGen.WriteEnumValue(), System.Xml.Serialization.XmlSerializationWriterILGen.WriteLocalDecl(), and System.Xml.Serialization.XmlSerializationWriterILGen.WritePrimitiveValue().
Referenced by System.Xml.Serialization.XmlSerializationWriterILGen.GenerateMembersElement(), System.Xml.Serialization.XmlSerializationWriterILGen.GenerateTypeElement(), System.Xml.Serialization.XmlSerializationWriterILGen.WriteEnumAndArrayTypes(), and System.Xml.Serialization.XmlSerializationWriterILGen.WriteStructMethod().