Terraria: System.Xml.Serialization.XmlSerializationWriterILGen.WriteEnumValue
WriteEnumValue()
void System.Xml.Serialization.XmlSerializationWriterILGen.WriteEnumValue (EnumMapping mapping, SourceInfo source, out Type returnType) inline private
Definition at line 121 of file XmlSerializationWriterILGen.cs.
    {
        string methodName = ReferenceMapping(mapping);
        MethodBuilder methodInfo = EnsureMethodBuilder(typeBuilder, methodName, MethodAttributes.Private | MethodAttributes.HideBySig, typeof(string), new Type[1] { mapping.TypeDesc.Type });
        ilg.Ldarg(0);
        source.Load(mapping.TypeDesc.Type);
        ilg.Call(methodInfo);
        returnType = typeof(string);
    }
References System.Xml.Serialization.CodeGenerator.Call(), System.Xml.Dictionary, System.Xml.Serialization.XmlSerializationILGen.EnsureMethodBuilder(), System.Xml.Serialization.XmlSerializationILGen.ilg, System.Xml.Serialization.CodeGenerator.Ldarg(), System.Xml.Serialization.XmlSerializationILGen.ReferenceMapping(), System.source, and System.Xml.Serialization.XmlSerializationILGen.typeBuilder.
Referenced by System.Xml.Serialization.XmlSerializationWriterILGen.WriteMember(), System.Xml.Serialization.XmlSerializationWriterILGen.WritePrimitive(), and System.Xml.Serialization.XmlSerializationWriterILGen.WriteText().