Terraria: System.Xml.Serialization.XmlSerializationWriterILGen.WriteEnumMethod
WriteEnumMethod()
void System.Xml.Serialization.XmlSerializationWriterILGen.WriteEnumMethod (EnumMapping mapping) inline private
Definition at line 508 of file XmlSerializationWriterILGen.cs.
    {
        base.MethodNames.TryGetValue(mapping, out var value);
        List<Type> list = new List<Type>();
        List<string> list2 = new List<string>();
        list.Add(mapping.TypeDesc.Type);
        list2.Add("v");
        ilg = new CodeGenerator(typeBuilder);
        ilg.BeginMethod(typeof(string), GetMethodBuilder(value), list.ToArray(), list2.ToArray(), MethodAttributes.Private | MethodAttributes.HideBySig);
        LocalBuilder localBuilder = ilg.DeclareLocal(typeof(string), "s");
        ilg.Load(null);
        ilg.Stloc(localBuilder);
        ConstantMapping[] constants = mapping.Constants;
        if (constants.Length != 0)
        {
            HashSet<long> hashSet = new HashSet<long>();
            List<Label> list3 = new List<Label>();
            List<string> list4 = new List<string>();
            Label label = ilg.DefineLabel();
            Label label2 = ilg.DefineLabel();
            LocalBuilder localBuilder2 = ilg.DeclareLocal(mapping.TypeDesc.Type, "localTmp");
            ilg.Ldarg("v");
            ilg.Stloc(localBuilder2);
            foreach (ConstantMapping constantMapping in constants)
            {
                if (hashSet.Add(constantMapping.Value))
                {
                    Label label3 = ilg.DefineLabel();
                    ilg.Ldloc(localBuilder2);
                    ilg.Ldc(Enum.ToObject(mapping.TypeDesc.Type, constantMapping.Value));
                    ilg.Beq(label3);
                    list3.Add(label3);
                    list4.Add(GetCSharpString(constantMapping.XmlName));
                }
            }
            if (mapping.IsFlags)
            {
                ilg.Br(label);
                for (int j = 0; j < list3.Count; j++)
                {
                    ilg.MarkLabel(list3[j]);
                    ilg.Ldc(list4[j]);
                    ilg.Stloc(localBuilder);
                    ilg.Br(label2);
                }
                ilg.MarkLabel(label);
                base.RaCodeGen.ILGenForEnumLongValue(ilg, "v");
                LocalBuilder localBuilder3 = ilg.DeclareLocal(typeof(string[]), "strArray");
                ilg.NewArray(typeof(string), constants.Length);
                ilg.Stloc(localBuilder3);
                for (int k = 0; k < constants.Length; k++)
                {
                    ConstantMapping constantMapping2 = constants[k];
                    ilg.Ldloc(localBuilder3);
                    ilg.Ldc(k);
                    ilg.Ldstr(GetCSharpString(constantMapping2.XmlName));
                    ilg.Stelem(typeof(string));
                }
                ilg.Ldloc(localBuilder3);
                LocalBuilder localBuilder4 = ilg.DeclareLocal(typeof(long[]), "longArray");
                ilg.NewArray(typeof(long), constants.Length);
                ilg.Stloc(localBuilder4);
                for (int l = 0; l < constants.Length; l++)
                {
                    ConstantMapping constantMapping3 = constants[l];
                    ilg.Ldloc(localBuilder4);
                    ilg.Ldc(l);
                    ilg.Ldc(constantMapping3.Value);
                    ilg.Stelem(typeof(long));
                }
                ilg.Ldloc(localBuilder4);
                ilg.Ldstr(GetCSharpString(mapping.TypeDesc.FullName));
                MethodInfo method = typeof(XmlSerializationWriter).GetMethod("FromEnum", BindingFlags.Static | BindingFlags.Public | BindingFlags.NonPublic, new Type[4]
                {
                    typeof(long),
                    typeof(string[]),
                    typeof(long[]),
                    typeof(string)
                });
                ilg.Call(method);
                ilg.Stloc(localBuilder);
                ilg.Br(label2);
            }
            else
            {
                ilg.Br(label);
                for (int m = 0; m < list3.Count; m++)
                {
                    ilg.MarkLabel(list3[m]);
                    ilg.Ldc(list4[m]);
                    ilg.Stloc(localBuilder);
                    ilg.Br(label2);
                }
                MethodInfo method2 = typeof(CultureInfo).GetMethod("get_InvariantCulture", BindingFlags.Static | BindingFlags.Public | BindingFlags.NonPublic, Type.EmptyTypes);
                MethodInfo method3 = typeof(long).GetMethod("ToString", BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, new Type[1] { typeof(IFormatProvider) });
                MethodInfo method4 = typeof(XmlSerializationWriter).GetMethod("CreateInvalidEnumValueException", BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, new Type[2]
                {
                    typeof(object),
                    typeof(string)
                });
                ilg.MarkLabel(label);
                ilg.Ldarg(0);
                ilg.Ldarg("v");
                ilg.ConvertValue(mapping.TypeDesc.Type, typeof(long));
                LocalBuilder localBuilder5 = ilg.DeclareLocal(typeof(long), "num");
                ilg.Stloc(localBuilder5);
                ilg.LdlocAddress(localBuilder5);
                ilg.Call(method2);
                ilg.Call(method3);
                ilg.Ldstr(GetCSharpString(mapping.TypeDesc.FullName));
                ilg.Call(method4);
                ilg.Throw();
            }
            ilg.MarkLabel(label2);
        }
        ilg.Ldloc(localBuilder);
        ilg.EndMethod();
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Xml.Serialization.CodeGenerator.BeginMethod(), System.Xml.Serialization.CodeGenerator.Beq(), System.Xml.Serialization.CodeGenerator.Br(), System.Xml.Serialization.CodeGenerator.Call(), System.Xml.Serialization.CodeGenerator.ConvertValue(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Xml.Serialization.CodeGenerator.DeclareLocal(), System.Xml.Serialization.CodeGenerator.DefineLabel(), System.Xml.Dictionary, System.Type.EmptyTypes, System.Xml.Serialization.CodeGenerator.EndMethod(), System.Xml.Serialization.XmlSerializationILGen.GetCSharpString(), System.Xml.Serialization.XmlSerializationILGen.GetMethodBuilder(), System.Xml.Serialization.XmlSerializationILGen.ilg, System.Xml.Serialization.CodeGenerator.Ldarg(), System.Xml.Serialization.CodeGenerator.Ldc(), System.Xml.Serialization.CodeGenerator.Ldloc(), System.Xml.Serialization.CodeGenerator.LdlocAddress(), System.Xml.Serialization.CodeGenerator.Ldstr(), System.list, System.Xml.Serialization.CodeGenerator.Load(), System.Xml.Serialization.CodeGenerator.MarkLabel(), System.Xml.Serialization.CodeGenerator.NewArray(), System.Xml.Serialization.CodeGenerator.Stelem(), System.Xml.Serialization.CodeGenerator.Stloc(), System.Xml.Serialization.CodeGenerator.Throw(), System.Enum.ToObject(), System.Collections.Generic.Dictionary< TKey, TValue >.TryGetValue(), System.Xml.Serialization.XmlSerializationILGen.typeBuilder, and System.value.
Referenced by System.Xml.Serialization.XmlSerializationWriterILGen.GenerateMethod().