Terraria: System.Xml.Serialization.XmlSerializationWriterILGen.WriteAttribute
WriteAttribute()
void System.Xml.Serialization.XmlSerializationWriterILGen.WriteAttribute (SourceInfo source, AttributeAccessor attribute, string parent) inline private
Definition at line 1136 of file XmlSerializationWriterILGen.cs.
    {
        if (attribute.Mapping is SpecialMapping)
        {
            SpecialMapping specialMapping = (SpecialMapping)attribute.Mapping;
            if (specialMapping.TypeDesc.Kind != TypeKind.Attribute && !specialMapping.TypeDesc.CanBeAttributeValue)
            {
                throw new InvalidOperationException(System.SR.XmlInternalError);
            }
            MethodInfo method = typeof(XmlSerializationWriter).GetMethod("WriteXmlAttribute", BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, new Type[2]
            {
                typeof(XmlNode),
                typeof(object)
            });
            ilg.Ldarg(0);
            ilg.Ldloc(source.Source);
            ilg.Ldarg(parent);
            ilg.ConvertValue(ilg.GetArg(parent).ArgType, typeof(object));
            ilg.Call(method);
        }
        else
        {
            TypeDesc typeDesc = attribute.Mapping.TypeDesc;
            source = source.CastTo(typeDesc);
            WritePrimitive("WriteAttribute", attribute.Name, (attribute.Form == XmlSchemaForm.Qualified) ? attribute.Namespace : "", GetConvertedDefaultValue(source.Type, attribute.Default), source, attribute.Mapping, writeXsiType: false, isElement: false, isNullable: false);
        }
    }
References System.Xml.Serialization.ArgBuilder.ArgType, System.Xml.Serialization.CodeGenerator.Call(), System.Xml.Serialization.CodeGenerator.ConvertValue(), System.Xml.Dictionary, System.Xml.Serialization.CodeGenerator.GetArg(), System.Xml.Serialization.XmlSerializationWriterILGen.GetConvertedDefaultValue(), System.Xml.Serialization.XmlSerializationILGen.ilg, System.Xml.Serialization.CodeGenerator.Ldarg(), System.Xml.Serialization.CodeGenerator.Ldloc(), System.source, System.Xml.Serialization.XmlSerializationWriterILGen.WritePrimitive(), and System.SR.XmlInternalError.
Referenced by System.Xml.Serialization.XmlSerializationWriterILGen.WriteMember().