Terraria: System.Xml.Serialization.XmlSerializationWriterILGen.WriteArrayItems
WriteArrayItems()
void System.Xml.Serialization.XmlSerializationWriterILGen.WriteArrayItems (ElementAccessor[] elements, TextAccessor text, ChoiceIdentifierAccessor choice, TypeDesc arrayTypeDesc, string arrayName, string choiceName) inline private
Definition at line 1251 of file XmlSerializationWriterILGen.cs.
    {
        TypeDesc arrayElementTypeDesc = arrayTypeDesc.ArrayElementTypeDesc;
        if (arrayTypeDesc.IsEnumerable)
        {
            LocalBuilder localBuilder = ilg.DeclareLocal(typeof(IEnumerator), "e");
            ilg.LoadAddress(ilg.GetVariable(arrayName));
            MethodInfo method;
            if (arrayTypeDesc.IsPrivateImplementation)
            {
                Type typeFromHandle = typeof(IEnumerable);
                method = typeFromHandle.GetMethod("GetEnumerator", BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, Type.EmptyTypes);
                ilg.ConvertValue(arrayTypeDesc.Type, typeFromHandle);
            }
            else if (arrayTypeDesc.IsGenericInterface)
            {
                Type type = typeof(IEnumerable<>).MakeGenericType(arrayElementTypeDesc.Type);
                method = type.GetMethod("GetEnumerator", BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, Type.EmptyTypes);
                ilg.ConvertValue(arrayTypeDesc.Type, type);
            }
            else
            {
                method = arrayTypeDesc.Type.GetMethod("GetEnumerator", Type.EmptyTypes);
            }
            ilg.Call(method);
            ilg.ConvertValue(method.ReturnType, typeof(IEnumerator));
            ilg.Stloc(localBuilder);
            ilg.Ldloc(localBuilder);
            ilg.Load(null);
            ilg.If(Cmp.NotEqualTo);
            ilg.WhileBegin();
            string arrayName2 = arrayName.Replace(arrayTypeDesc.Name, "") + "a" + arrayElementTypeDesc.Name;
            string text2 = arrayName.Replace(arrayTypeDesc.Name, "") + "i" + arrayElementTypeDesc.Name;
            WriteLocalDecl(text2, "e.Current", arrayElementTypeDesc.Type);
            WriteElements(new SourceInfo(text2, null, null, arrayElementTypeDesc.Type, ilg), choiceName + "i", elements, text, choice, arrayName2, writeAccessors: true, isNullable: true);
            ilg.WhileBeginCondition();
            MethodInfo method2 = typeof(IEnumerator).GetMethod("MoveNext", BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, Type.EmptyTypes);
            ilg.Ldloc(localBuilder);
            ilg.Call(method2);
            ilg.WhileEndCondition();
            ilg.WhileEnd();
            ilg.EndIf();
            return;
        }
        string text3 = "i" + arrayName.Replace(arrayTypeDesc.Name, "");
        string arrayName3 = arrayName.Replace(arrayTypeDesc.Name, "") + "a" + arrayElementTypeDesc.Name;
        string text4 = arrayName.Replace(arrayTypeDesc.Name, "") + "i" + arrayElementTypeDesc.Name;
        LocalBuilder local = ilg.DeclareOrGetLocal(typeof(int), text3);
        ilg.For(local, 0, ilg.GetLocal(arrayName));
        int num = elements.Length + ((text != null) ? 1 : 0);
        if (num > 1)
        {
            WriteLocalDecl(text4, base.RaCodeGen.GetStringForArrayMember(arrayName, text3, arrayTypeDesc), arrayElementTypeDesc.Type);
            if (choice != null)
            {
                WriteLocalDecl(choiceName + "i", base.RaCodeGen.GetStringForArrayMember(choiceName, text3, choice.Mapping.TypeDesc), choice.Mapping.TypeDesc.Type);
            }
            WriteElements(new SourceInfo(text4, null, null, arrayElementTypeDesc.Type, ilg), choiceName + "i", elements, text, choice, arrayName3, writeAccessors: true, arrayElementTypeDesc.IsNullable);
        }
        else
        {
            WriteElements(new SourceInfo(base.RaCodeGen.GetStringForArrayMember(arrayName, text3, arrayTypeDesc), null, null, arrayElementTypeDesc.Type, ilg), null, elements, text, choice, arrayName3, writeAccessors: true, arrayElementTypeDesc.IsNullable);
        }
        ilg.EndFor();
    }
References System.Xml.Serialization.CodeGenerator.Call(), System.Xml.Serialization.CodeGenerator.ConvertValue(), System.Xml.Serialization.CodeGenerator.DeclareLocal(), System.Xml.Serialization.CodeGenerator.DeclareOrGetLocal(), System.Xml.Dictionary, System.Type.EmptyTypes, System.Xml.Serialization.CodeGenerator.EndFor(), System.Xml.Serialization.CodeGenerator.EndIf(), System.Xml.Serialization.CodeGenerator.For(), System.Xml.Serialization.CodeGenerator.GetLocal(), System.Xml.Serialization.CodeGenerator.GetVariable(), System.Xml.Serialization.CodeGenerator.If(), System.Xml.Serialization.XmlSerializationILGen.ilg, System.Xml.Serialization.CodeGenerator.Ldloc(), System.Xml.Serialization.CodeGenerator.Load(), System.Xml.Serialization.CodeGenerator.LoadAddress(), System.Type.MakeGenericType(), System.Xml.Serialization.CodeGenerator.Stloc(), System.text, System.type, System.Xml.Serialization.CodeGenerator.WhileBegin(), System.Xml.Serialization.CodeGenerator.WhileBeginCondition(), System.Xml.Serialization.CodeGenerator.WhileEnd(), System.Xml.Serialization.CodeGenerator.WhileEndCondition(), System.Xml.Serialization.XmlSerializationWriterILGen.WriteElements(), and System.Xml.Serialization.XmlSerializationWriterILGen.WriteLocalDecl().
Referenced by System.Xml.Serialization.XmlSerializationWriterILGen.WriteArray(), and System.Xml.Serialization.XmlSerializationWriterILGen.WriteElement().