Terraria: System.Xml.Serialization.XmlSerializationWriterILGen.WriteDerivedTypes
WriteDerivedTypes()
void System.Xml.Serialization.XmlSerializationWriterILGen.WriteDerivedTypes (StructMapping mapping) inline private
Definition at line 627 of file XmlSerializationWriterILGen.cs.
    {
        for (StructMapping structMapping = mapping.DerivedMappings; structMapping != null; structMapping = structMapping.NextDerivedMapping)
        {
            ilg.InitElseIf();
            WriteTypeCompare("t", structMapping.TypeDesc.Type);
            ilg.AndIf();
            string methodName = ReferenceMapping(structMapping);
            List<Type> list = new List<Type>();
            ilg.Ldarg(0);
            list.Add(typeof(string));
            ilg.Ldarg("n");
            list.Add(typeof(string));
            ilg.Ldarg("ns");
            object variable = ilg.GetVariable("o");
            Type variableType = ilg.GetVariableType(variable);
            ilg.Load(variable);
            ilg.ConvertValue(variableType, structMapping.TypeDesc.Type);
            list.Add(structMapping.TypeDesc.Type);
            if (structMapping.TypeDesc.IsNullable)
            {
                list.Add(typeof(bool));
                ilg.Ldarg("isNullable");
            }
            list.Add(typeof(bool));
            ilg.Ldc(boolVar: true);
            MethodInfo methodInfo = EnsureMethodBuilder(typeBuilder, methodName, MethodAttributes.Private | MethodAttributes.HideBySig, typeof(void), list.ToArray());
            ilg.Call(methodInfo);
            ilg.GotoMethodEnd();
            WriteDerivedTypes(structMapping);
        }
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Xml.Serialization.CodeGenerator.AndIf(), System.Xml.Serialization.CodeGenerator.Call(), System.Xml.Serialization.CodeGenerator.ConvertValue(), System.Xml.Dictionary, System.Xml.Serialization.XmlSerializationILGen.EnsureMethodBuilder(), System.Xml.Serialization.CodeGenerator.GetVariable(), System.Xml.Serialization.CodeGenerator.GetVariableType(), System.Xml.Serialization.CodeGenerator.GotoMethodEnd(), System.Xml.Serialization.XmlSerializationILGen.ilg, System.Xml.Serialization.CodeGenerator.InitElseIf(), System.Xml.Serialization.CodeGenerator.Ldarg(), System.Xml.Serialization.CodeGenerator.Ldc(), System.list, System.Xml.Serialization.CodeGenerator.Load(), System.Xml.Serialization.XmlSerializationILGen.ReferenceMapping(), System.Xml.Serialization.XmlSerializationILGen.typeBuilder, System.Xml.Serialization.XmlSerializationWriterILGen.WriteDerivedTypes(), and System.Xml.Serialization.XmlSerializationWriterILGen.WriteTypeCompare().
Referenced by System.Xml.Serialization.XmlSerializationWriterILGen.WriteDerivedTypes(), and System.Xml.Serialization.XmlSerializationWriterILGen.WriteStructMethod().