Terraria: System.Xml.Serialization.XmlSerializationWriterILGen.WriteStructMethod
WriteStructMethod()
void System.Xml.Serialization.XmlSerializationWriterILGen.WriteStructMethod (StructMapping mapping) inline private
Definition at line 757 of file XmlSerializationWriterILGen.cs.
    {
        base.MethodNames.TryGetValue(mapping, out var value);
        ilg = new CodeGenerator(typeBuilder);
        List<Type> list = new List<Type>(5);
        List<string> list2 = new List<string>(5);
        list.Add(typeof(string));
        list2.Add("n");
        list.Add(typeof(string));
        list2.Add("ns");
        list.Add(mapping.TypeDesc.Type);
        list2.Add("o");
        if (mapping.TypeDesc.IsNullable)
        {
            list.Add(typeof(bool));
            list2.Add("isNullable");
        }
        list.Add(typeof(bool));
        list2.Add("needType");
        ilg.BeginMethod(typeof(void), GetMethodBuilder(value), list.ToArray(), list2.ToArray(), MethodAttributes.Private | MethodAttributes.HideBySig);
        if (mapping.TypeDesc.IsNullable)
        {
            ilg.If(ilg.GetArg("o"), Cmp.EqualTo, null);
            ilg.If(ilg.GetArg("isNullable"), Cmp.EqualTo, true);
            MethodInfo method = typeof(XmlSerializationWriter).GetMethod("WriteNullTagLiteral", BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, new Type[2]
            {
                typeof(string),
                typeof(string)
            });
            ilg.Ldarg(0);
            ilg.Ldarg("n");
            ilg.Ldarg("ns");
            ilg.Call(method);
            ilg.EndIf();
            ilg.GotoMethodEnd();
            ilg.EndIf();
        }
        ilg.If(ilg.GetArg("needType"), Cmp.NotEqualTo, true);
        LocalBuilder local = ilg.DeclareLocal(typeof(Type), "t");
        MethodInfo method2 = typeof(object).GetMethod("GetType", BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, Type.EmptyTypes);
        ArgBuilder arg = ilg.GetArg("o");
        ilg.LdargAddress(arg);
        ilg.ConvertAddress(arg.ArgType, typeof(object));
        ilg.Call(method2);
        ilg.Stloc(local);
        WriteTypeCompare("t", mapping.TypeDesc.Type);
        ilg.If();
        WriteDerivedTypes(mapping);
        if (mapping.TypeDesc.IsRoot)
        {
            WriteEnumAndArrayTypes();
        }
        ilg.Else();
        if (mapping.TypeDesc.IsRoot)
        {
            MethodInfo method3 = typeof(XmlSerializationWriter).GetMethod("WriteTypedPrimitive", BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, new Type[4]
            {
                typeof(string),
                typeof(string),
                typeof(object),
                typeof(bool)
            });
            ilg.Ldarg(0);
            ilg.Ldarg("n");
            ilg.Ldarg("ns");
            ilg.Ldarg("o");
            ilg.Ldc(boolVar: true);
            ilg.Call(method3);
            ilg.GotoMethodEnd();
        }
        else
        {
            MethodInfo method4 = typeof(XmlSerializationWriter).GetMethod("CreateUnknownTypeException", BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, new Type[1] { typeof(object) });
            ilg.Ldarg(0);
            ilg.Ldarg(arg);
            ilg.ConvertValue(arg.ArgType, typeof(object));
            ilg.Call(method4);
            ilg.Throw();
        }
        ilg.EndIf();
        ilg.EndIf();
        if (!mapping.TypeDesc.IsAbstract)
        {
            if (mapping.TypeDesc.Type != null && typeof(XmlSchemaObject).IsAssignableFrom(mapping.TypeDesc.Type))
            {
                MethodInfo method5 = typeof(XmlSerializationWriter).GetMethod("set_EscapeName", BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, new Type[1] { typeof(bool) });
                ilg.Ldarg(0);
                ilg.Ldc(boolVar: false);
                ilg.Call(method5);
            }
            string text = null;
            MemberMapping[] allMembers = TypeScope.GetAllMembers(mapping, memberInfos);
            int num = FindXmlnsIndex(allMembers);
            if (num >= 0)
            {
                MemberMapping memberMapping = allMembers[num];
                CodeIdentifier.CheckValidIdentifier(memberMapping.Name);
                text = base.RaCodeGen.GetStringForMember("o", memberMapping.Name, mapping.TypeDesc);
            }
            ilg.Ldarg(0);
            ilg.Ldarg("n");
            ilg.Ldarg("ns");
            ArgBuilder arg2 = ilg.GetArg("o");
            ilg.Ldarg(arg2);
            ilg.ConvertValue(arg2.ArgType, typeof(object));
            ilg.Ldc(boolVar: false);
            if (text == null)
            {
                ilg.Load(null);
            }
            else
            {
                ILGenLoad(text);
            }
            MethodInfo method6 = typeof(XmlSerializationWriter).GetMethod("WriteStartElement", BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, new Type[5]
            {
                typeof(string),
                typeof(string),
                typeof(object),
                typeof(bool),
                typeof(XmlSerializerNamespaces)
            });
            ilg.Call(method6);
            if (!mapping.TypeDesc.IsRoot)
            {
                ilg.If(ilg.GetArg("needType"), Cmp.EqualTo, true);
                MethodInfo method7 = typeof(XmlSerializationWriter).GetMethod("WriteXsiType", BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, new Type[2]
                {
                    typeof(string),
                    typeof(string)
                });
                ilg.Ldarg(0);
                ilg.Ldstr(GetCSharpString(mapping.TypeName));
                ilg.Ldstr(GetCSharpString(mapping.Namespace));
                ilg.Call(method7);
                ilg.EndIf();
            }
            foreach (MemberMapping memberMapping2 in allMembers)
            {
                if (memberMapping2.Attribute != null)
                {
                    CodeIdentifier.CheckValidIdentifier(memberMapping2.Name);
                    if (memberMapping2.CheckShouldPersist)
                    {
                        ilg.LdargAddress(arg);
                        ilg.Call(memberMapping2.CheckShouldPersistMethodInfo);
                        ilg.If();
                    }
                    if (memberMapping2.CheckSpecified != 0)
                    {
                        string stringForMember = base.RaCodeGen.GetStringForMember("o", memberMapping2.Name + "Specified", mapping.TypeDesc);
                        ILGenLoad(stringForMember);
                        ilg.If();
                    }
                    WriteMember(base.RaCodeGen.GetSourceForMember("o", memberMapping2, mapping.TypeDesc, ilg), memberMapping2.Attribute, memberMapping2.TypeDesc, "o");
                    if (memberMapping2.CheckSpecified != 0)
                    {
                        ilg.EndIf();
                    }
                    if (memberMapping2.CheckShouldPersist)
                    {
                        ilg.EndIf();
                    }
                }
            }
            foreach (MemberMapping memberMapping3 in allMembers)
            {
                if (memberMapping3.Xmlns == null)
                {
                    CodeIdentifier.CheckValidIdentifier(memberMapping3.Name);
                    bool flag = memberMapping3.CheckShouldPersist && (memberMapping3.Elements.Length != 0 || memberMapping3.Text != null);
                    if (flag)
                    {
                        ilg.LdargAddress(arg);
                        ilg.Call(memberMapping3.CheckShouldPersistMethodInfo);
                        ilg.If();
                    }
                    if (memberMapping3.CheckSpecified != 0)
                    {
                        string stringForMember2 = base.RaCodeGen.GetStringForMember("o", memberMapping3.Name + "Specified", mapping.TypeDesc);
                        ILGenLoad(stringForMember2);
                        ilg.If();
                    }
                    string choiceSource = null;
                    if (memberMapping3.ChoiceIdentifier != null)
                    {
                        CodeIdentifier.CheckValidIdentifier(memberMapping3.ChoiceIdentifier.MemberName);
                        choiceSource = base.RaCodeGen.GetStringForMember("o", memberMapping3.ChoiceIdentifier.MemberName, mapping.TypeDesc);
                    }
                    WriteMember(base.RaCodeGen.GetSourceForMember("o", memberMapping3, memberMapping3.MemberInfo, mapping.TypeDesc, ilg), choiceSource, memberMapping3.ElementsSortedByDerivation, memberMapping3.Text, memberMapping3.ChoiceIdentifier, memberMapping3.TypeDesc, writeAccessors: true);
                    if (memberMapping3.CheckSpecified != 0)
                    {
                        ilg.EndIf();
                    }
                    if (flag)
                    {
                        ilg.EndIf();
                    }
                }
            }
            WriteEndElement("o");
        }
        ilg.EndMethod();
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Xml.Serialization.CodeGenerator.BeginMethod(), System.Xml.Serialization.CodeGenerator.Call(), System.Xml.Serialization.CodeIdentifier.CheckValidIdentifier(), System.Xml.Serialization.CodeGenerator.ConvertAddress(), System.Xml.Serialization.CodeGenerator.ConvertValue(), System.Xml.Serialization.CodeGenerator.DeclareLocal(), System.Xml.Dictionary, System.Xml.Serialization.CodeGenerator.Else(), System.Type.EmptyTypes, System.Xml.Serialization.CodeGenerator.EndIf(), System.Xml.Serialization.CodeGenerator.EndMethod(), System.Xml.Serialization.XmlSerializationWriterILGen.FindXmlnsIndex(), System.Xml.Serialization.TypeScope.GetAllMembers(), System.Xml.Serialization.CodeGenerator.GetArg(), System.Xml.Serialization.XmlSerializationILGen.GetCSharpString(), System.Xml.Serialization.XmlSerializationILGen.GetMethodBuilder(), System.Xml.Serialization.CodeGenerator.GotoMethodEnd(), System.Xml.Serialization.CodeGenerator.If(), System.Xml.Serialization.XmlSerializationILGen.ilg, System.Xml.Serialization.XmlSerializationILGen.ILGenLoad(), System.Xml.Serialization.CodeGenerator.Ldarg(), System.Xml.Serialization.CodeGenerator.LdargAddress(), System.Xml.Serialization.CodeGenerator.Ldc(), System.Xml.Serialization.CodeGenerator.Ldstr(), System.list, System.Xml.Serialization.CodeGenerator.Load(), System.Xml.Serialization.XmlSerializationILGen.memberInfos, System.Xml.Serialization.CodeGenerator.Stloc(), System.text, System.Xml.Serialization.CodeGenerator.Throw(), System.Collections.Generic.Dictionary< TKey, TValue >.TryGetValue(), System.Xml.Serialization.XmlSerializationILGen.typeBuilder, System.value, System.Xml.Serialization.XmlSerializationWriterILGen.WriteDerivedTypes(), System.Xml.Serialization.XmlSerializationWriterILGen.WriteEndElement(), System.Xml.Serialization.XmlSerializationWriterILGen.WriteEnumAndArrayTypes(), System.Xml.Serialization.XmlSerializationWriterILGen.WriteMember(), and System.Xml.Serialization.XmlSerializationWriterILGen.WriteTypeCompare().
Referenced by System.Xml.Serialization.XmlSerializationWriterILGen.GenerateMethod().