Terraria: System.Net.Mime.BaseWriter.EndGetContentStream
EndGetContentStream()
Stream System.Net.Mime.BaseWriter.EndGetContentStream (IAsyncResult result) inline package inherited
Definition at line 126 of file BaseWriter.cs.
    {
        object obj = MultiAsyncResult.End(result);
        if (obj is Exception source)
        {
            ExceptionDispatchInfo.Throw(source);
        }
        return (Stream)obj;
    }
References System.Net.Mime.MultiAsyncResult.End(), System.obj, System.source, and System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw().
Referenced by System.Net.Mime.MimePart.ContentStreamCallbackHandler(), and System.Net.Mail.Message.EmptySendCallback().