Terraria: System.Net.Mime.BaseWriter.WriteHeader
WriteHeader()
void System.Net.Mime.BaseWriter.WriteHeader (string name, string value, bool allowUnicode) inline package inherited
Definition at line 43 of file BaseWriter.cs.
    {
        if (name == null)
        {
            throw new ArgumentNullException("name");
        }
        if (value == null)
        {
            throw new ArgumentNullException("value");
        }
        if (_isInContent)
        {
            throw new InvalidOperationException(System.SR.MailWriterIsInContent);
        }
        CheckBoundary();
        _bufferBuilder.Append(name);
        _bufferBuilder.Append(": ");
        WriteAndFold(value, name.Length + 2, allowUnicode);
        _bufferBuilder.Append(s_crlf);
    }
References System.Net.Mime.BaseWriter._bufferBuilder, System.Net.Mime.BaseWriter._isInContent, System.Net.Mail.BufferBuilder.Append(), System.Net.Mime.BaseWriter.CheckBoundary(), System.SR.MailWriterIsInContent, System.Net.Mime.BaseWriter.s_crlf, System.value, and System.Net.Mime.BaseWriter.WriteAndFold().
Referenced by System.Net.Mail.MailWriter.WriteHeaders(), and System.Net.Mime.MimeWriter.WriteHeaders().