Terraria: System.Net.Mime.BaseWriter.Flush
Flush()
void System.Net.Mime.BaseWriter.Flush (MultiAsyncResult multiResult) inline protected inherited
Definition at line 136 of file BaseWriter.cs.
    {
        if (_bufferBuilder.Length <= 0)
        {
            return;
        }
        if (multiResult != null)
        {
            multiResult.Enter();
            IAsyncResult asyncResult = _stream.BeginWrite(_bufferBuilder.GetBuffer(), 0, _bufferBuilder.Length, s_onWrite, multiResult);
            if (asyncResult.CompletedSynchronously)
            {
                _stream.EndWrite(asyncResult);
                multiResult.Leave();
            }
        }
        else
        {
            _stream.Write(_bufferBuilder.GetBuffer(), 0, _bufferBuilder.Length);
        }
        _bufferBuilder.Reset();
    }
References System.Net.Mime.BaseWriter._bufferBuilder, System.Net.Mime.BaseWriter._stream, System.asyncResult, System.IO.Stream.BeginWrite(), System.IO.Stream.EndWrite(), System.Net.Mime.MultiAsyncResult.Enter(), System.Net.Mail.BufferBuilder.GetBuffer(), System.Net.Mime.MultiAsyncResult.Leave(), System.Net.Mail.BufferBuilder.Length, System.Net.Mail.BufferBuilder.Reset(), System.Net.Mime.BaseWriter.s_onWrite, and System.IO.Stream.Write().
Referenced by System.Net.Mail.MailWriter.Close(), System.Net.Mime.MimeWriter.Close(), and System.Net.Mime.BaseWriter.GetContentStream().