Terraria: UIKeybindingSliderItem.DrawSelf
DrawSelf()
override void UIKeybindingSliderItem.DrawSelf (SpriteBatch spriteBatch) inline protected virtual
Reimplemented from UIElement.
     {
         float num = 6f;
         base.DrawSelf(spriteBatch);
         int num2 = 0;
         IngameOptions.rightHover = -1;
         if (!Main.mouseLeft)
         {
             IngameOptions.rightLock = -1;
         }
         if (IngameOptions.rightLock == _sliderIDInPage)
         {
             num2 = 1;
         }
         else if (IngameOptions.rightLock != -1)
         {
             num2 = 2;
         }
         CalculatedStyle dimensions = GetDimensions();
         float num3 = dimensions.Width + 1f;
         Vector2 vector = new Vector2(dimensions.X, dimensions.Y);
         bool flag = base.IsMouseHovering;
         if (num2 == 1)
         {
             flag = true;
         }
         if (num2 == 2)
         {
             flag = false;
         }
         Vector2 baseScale = new Vector2(0.8f);
         Color value = (false ? Color.Gold : (flag ? Color.White : Color.Silver));
         value = Color.Lerp(value, Color.White, flag ? 0.5f : 0f);
         Color color = (flag ? _color : _color.MultiplyRGBA(new Color(180, 180, 180)));
         Vector2 position = vector;
         Utils.DrawSettingsPanel(spriteBatch, position, num3, color);
         position.X += 8f;
         position.Y += 2f + num;
         ChatManager.DrawColorCodedStringWithShadow(spriteBatch, FontAssets.ItemStack.Value, _TextDisplayFunction(), position, value, 0f, Vector2.Zero, baseScale, num3);
         position.X -= 17f;
         TextureAssets.ColorBar.Frame();
         position = new Vector2(dimensions.X + dimensions.Width - 10f, dimensions.Y + 10f + num);
         IngameOptions.valuePosition = position;
         float obj = IngameOptions.DrawValueBar(spriteBatch, 1f, _GetStatusFunction(), num2);
         if (IngameOptions.inBar || IngameOptions.rightLock == _sliderIDInPage)
         {
             IngameOptions.rightHover = _sliderIDInPage;
             if (PlayerInput.Triggers.Current.MouseLeft && PlayerInput.CurrentProfile.AllowEditting && !PlayerInput.UsingGamepad && IngameOptions.rightLock == _sliderIDInPage)
             {
                 _SlideKeyboardAction(obj);
             }
         }
         if (IngameOptions.rightHover != -1 && IngameOptions.rightLock == -1)
         {
             IngameOptions.rightLock = IngameOptions.rightHover;
         }
         if (base.IsMouseHovering && PlayerInput.CurrentProfile.AllowEditting)
         {
             _SlideGamepadAction();
         }
     }
References _color, _GetStatusFunction, _SlideGamepadAction, _SlideKeyboardAction, _sliderIDInPage, _TextDisplayFunction, PlayerInputProfile.AllowEditting, Color, TextureAssets.ColorBar, TriggersPack.Current, PlayerInput.CurrentProfile, ChatManager.DrawColorCodedStringWithShadow(), Utils.DrawSettingsPanel(), IngameOptions.DrawValueBar(), UIElement.GetDimensions(), IngameOptions.inBar, FontAssets.ItemStack, TriggersSet.MouseLeft, Main.mouseLeft, IngameOptions.rightHover, IngameOptions.rightLock, PlayerInput.Triggers, PlayerInput.UsingGamepad, Asset< T >.Value, IngameOptions.valuePosition, CalculatedStyle.Width, CalculatedStyle.X, and CalculatedStyle.Y.