Terraria: Terraria.Map.WorldMap.Clear
Clear()
void Terraria.Map.WorldMap.Clear () inline
    {
        for (int i = 0; i < MaxWidth; i++)
        {
            for (int j = 0; j < MaxHeight; j++)
            {
                _tiles[i, j].Clear();
            }
        }
    }
References Terraria.Map.WorldMap._tiles, Terraria.Map.MapTile.Clear(), Terraria.Map.WorldMap.MaxHeight, and Terraria.Map.WorldMap.MaxWidth.
Referenced by Terraria.WorldGen.clearWorld(), and Terraria.Map.WorldMap.Load().