Terraria: System.Dynamic.DynamicObject.MetaDynamic.IsOverridden
IsOverridden()
bool System.Dynamic.DynamicObject.MetaDynamic.IsOverridden (MethodInfo method) inline private
Definition at line 282 of file DynamicObject.cs.
        {
            MemberInfo[] member = Value.GetType().GetMember(method.Name, MemberTypes.Method, BindingFlags.Instance | BindingFlags.Public);
            MemberInfo[] array = member;
            for (int i = 0; i < array.Length; i++)
            {
                MethodInfo methodInfo = (MethodInfo)array[i];
                if (methodInfo.DeclaringType != typeof(DynamicObject) && methodInfo.GetBaseDefinition() == method)
                {
                    return true;
                }
            }
            return false;
        }
References System.array, and System.Dynamic.DynamicObject.MetaDynamic.Value.
Referenced by System.Dynamic.DynamicObject.MetaDynamic.BindBinaryOperation(), System.Dynamic.DynamicObject.MetaDynamic.BindConvert(), System.Dynamic.DynamicObject.MetaDynamic.BindCreateInstance(), System.Dynamic.DynamicObject.MetaDynamic.BindDeleteIndex(), System.Dynamic.DynamicObject.MetaDynamic.BindDeleteMember(), System.Dynamic.DynamicObject.MetaDynamic.BindGetIndex(), System.Dynamic.DynamicObject.MetaDynamic.BindGetMember(), System.Dynamic.DynamicObject.MetaDynamic.BindInvoke(), System.Dynamic.DynamicObject.MetaDynamic.BindSetIndex(), System.Dynamic.DynamicObject.MetaDynamic.BindSetMember(), System.Dynamic.DynamicObject.MetaDynamic.BindUnaryOperation(), and System.Dynamic.DynamicObject.MetaDynamic.BuildCallMethodWithResult< TBinder >().