Terraria: System.Dynamic.DynamicObject.MetaDynamic.GetLimitedSelf
GetLimitedSelf()
Expression System.Dynamic.DynamicObject.MetaDynamic.GetLimitedSelf () inline private
Definition at line 302 of file DynamicObject.cs.
        {
            if (TypeUtils.AreEquivalent(base.Expression.Type, typeof(DynamicObject)))
            {
                return base.Expression;
            }
            return System.Linq.Expressions.Expression.Convert(base.Expression, typeof(DynamicObject));
        }
References System.Dynamic.Utils.TypeUtils.AreEquivalent(), and System.Linq.Expressions.Expression< TDelegate >.Convert().
Referenced by System.Dynamic.DynamicObject.MetaDynamic.BuildCallMethodWithResult< TBinder >(), System.Dynamic.DynamicObject.MetaDynamic.CallMethodNoResult< TBinder >(), and System.Dynamic.DynamicObject.MetaDynamic.CallMethodReturnLast< TBinder >().