Terraria: System.Dynamic.DynamicObject.MetaDynamic.CallMethodNoResult< TBinder >
CallMethodNoResult< TBinder >()
DynamicMetaObject System.Dynamic.DynamicObject.MetaDynamic.CallMethodNoResult< TBinder > (MethodInfo method, TBinder binder, Expression[] args, Fallback< TBinder > fallback) inline private
Type Constraints
TBinder : DynamicMetaObjectBinder
Definition at line 272 of file DynamicObject.cs.
                                                                                                                                                              : DynamicMetaObjectBinder
        {
            DynamicMetaObject dynamicMetaObject = fallback(this, binder, null);
            ParameterExpression parameterExpression = System.Linq.Expressions.Expression.Parameter(typeof(object[]), null);
            ReadOnlyCollection<Expression> convertedArgs = GetConvertedArgs(args);
            DynamicMetaObject errorSuggestion = new DynamicMetaObject(System.Linq.Expressions.Expression.Block(new TrueReadOnlyCollection<ParameterExpression>(parameterExpression), new TrueReadOnlyCollection<Expression>(System.Linq.Expressions.Expression.Assign(parameterExpression, System.Linq.Expressions.Expression.NewArrayInit(typeof(object), convertedArgs)), System.Linq.Expressions.Expression.Condition(System.Linq.Expressions.Expression.Call(GetLimitedSelf(), method, BuildCallArgs(binder, args, parameterExpression, null)), System.Linq.Expressions.Expression.Block(ReferenceArgAssign(parameterExpression, args), System.Linq.Expressions.Utils.Empty), dynamicMetaObject.Expression, typeof(void)))), GetRestrictions().Merge(dynamicMetaObject.Restrictions));
            return fallback(this, binder, errorSuggestion);
        }
References System.Dynamic.DynamicMetaObject.DynamicMetaObject(), System.Linq.Expressions.Expression< TDelegate >.Assign(), System.Linq.Expressions.Expression< TDelegate >.Block(), System.Linq.Expressions.Expression< TDelegate >.Call(), System.Linq.Expressions.Expression< TDelegate >.Condition(), System.Linq.Expressions.Utils.Empty, System.Dynamic.DynamicObject.MetaDynamic.GetConvertedArgs(), System.Dynamic.DynamicObject.MetaDynamic.GetLimitedSelf(), System.Dynamic.DynamicObject.MetaDynamic.GetRestrictions(), System.Linq.Expressions.Expression< TDelegate >.NewArrayInit(), System.Linq.Expressions.Expression< TDelegate >.Parameter(), and System.Dynamic.DynamicObject.MetaDynamic.ReferenceArgAssign().