Terraria: System.Dynamic.DynamicObject.MetaDynamic.BuildCallMethodWithResult< TBinder >
BuildCallMethodWithResult< TBinder >()
DynamicMetaObject System.Dynamic.DynamicObject.MetaDynamic.BuildCallMethodWithResult< TBinder > (MethodInfo method, TBinder binder, Expression[] args, DynamicMetaObject fallbackResult, Fallback< TBinder > fallbackInvoke) inline private
Type Constraints
TBinder : DynamicMetaObjectBinder
Definition at line 237 of file DynamicObject.cs.
                                                                                                                                                                                                             : DynamicMetaObjectBinder
        {
            if (!IsOverridden(method))
            {
                return fallbackResult;
            }
            ParameterExpression parameterExpression = System.Linq.Expressions.Expression.Parameter(typeof(object), null);
            ParameterExpression parameterExpression2 = ((method != CachedReflectionInfo.DynamicObject_TryBinaryOperation) ? System.Linq.Expressions.Expression.Parameter(typeof(object[]), null) : System.Linq.Expressions.Expression.Parameter(typeof(object), null));
            ReadOnlyCollection<Expression> convertedArgs = GetConvertedArgs(args);
            DynamicMetaObject dynamicMetaObject = new DynamicMetaObject(parameterExpression, BindingRestrictions.Empty);
            if (binder.ReturnType != typeof(object))
            {
                UnaryExpression ifTrue = System.Linq.Expressions.Expression.Convert(dynamicMetaObject.Expression, binder.ReturnType);
                string value = Strings.DynamicObjectResultNotAssignable("{0}", Value.GetType(), binder.GetType(), binder.ReturnType);
                Expression test = ((!binder.ReturnType.IsValueType || !(Nullable.GetUnderlyingType(binder.ReturnType) == null)) ? ((Expression)System.Linq.Expressions.Expression.OrElse(System.Linq.Expressions.Expression.Equal(dynamicMetaObject.Expression, System.Linq.Expressions.Utils.Null), System.Linq.Expressions.Expression.TypeIs(dynamicMetaObject.Expression, binder.ReturnType))) : ((Expression)System.Linq.Expressions.Expression.TypeIs(dynamicMetaObject.Expression, binder.ReturnType)));
                Expression expression = System.Linq.Expressions.Expression.Condition(test, ifTrue, System.Linq.Expressions.Expression.Throw(System.Linq.Expressions.Expression.New(CachedReflectionInfo.InvalidCastException_Ctor_String, new TrueReadOnlyCollection<Expression>(System.Linq.Expressions.Expression.Call(CachedReflectionInfo.String_Format_String_ObjectArray, System.Linq.Expressions.Expression.Constant(value), System.Linq.Expressions.Expression.NewArrayInit(typeof(object), new TrueReadOnlyCollection<Expression>(System.Linq.Expressions.Expression.Condition(System.Linq.Expressions.Expression.Equal(dynamicMetaObject.Expression, System.Linq.Expressions.Utils.Null), System.Linq.Expressions.Expression.Constant("null"), System.Linq.Expressions.Expression.Call(dynamicMetaObject.Expression, CachedReflectionInfo.Object_GetType), typeof(object))))))), binder.ReturnType), binder.ReturnType);
                dynamicMetaObject = new DynamicMetaObject(expression, dynamicMetaObject.Restrictions);
            }
            if (fallbackInvoke != null)
            {
                dynamicMetaObject = fallbackInvoke(this, binder, dynamicMetaObject);
            }
            return new DynamicMetaObject(System.Linq.Expressions.Expression.Block(new TrueReadOnlyCollection<ParameterExpression>(parameterExpression, parameterExpression2), new TrueReadOnlyCollection<Expression>((method != CachedReflectionInfo.DynamicObject_TryBinaryOperation) ? System.Linq.Expressions.Expression.Assign(parameterExpression2, System.Linq.Expressions.Expression.NewArrayInit(typeof(object), convertedArgs)) : System.Linq.Expressions.Expression.Assign(parameterExpression2, convertedArgs[0]), System.Linq.Expressions.Expression.Condition(System.Linq.Expressions.Expression.Call(GetLimitedSelf(), method, BuildCallArgs(binder, args, parameterExpression2, parameterExpression)), System.Linq.Expressions.Expression.Block((method != CachedReflectionInfo.DynamicObject_TryBinaryOperation) ? ReferenceArgAssign(parameterExpression2, args) : System.Linq.Expressions.Utils.Empty, dynamicMetaObject.Expression), fallbackResult.Expression, binder.ReturnType))), GetRestrictions().Merge(dynamicMetaObject.Restrictions).Merge(fallbackResult.Restrictions));
        }
References System.Dynamic.DynamicMetaObject.DynamicMetaObject(), System.Linq.Expressions.Expression< TDelegate >.Assign(), System.Linq.Expressions.Expression< TDelegate >.Block(), System.Linq.Expressions.Expression< TDelegate >.Call(), System.Linq.Expressions.Expression< TDelegate >.Condition(), System.Linq.Expressions.Expression< TDelegate >.Constant(), System.Linq.Expressions.Expression< TDelegate >.Convert(), System.Linq.Expressions.CachedReflectionInfo.DynamicObject_TryBinaryOperation, System.Linq.Expressions.Strings.DynamicObjectResultNotAssignable(), System.Dynamic.BindingRestrictions.Empty, System.Linq.Expressions.Utils.Empty, System.Linq.Expressions.Expression< TDelegate >.Equal(), System.Dynamic.DynamicMetaObject.Expression, System.Dynamic.DynamicObject.MetaDynamic.GetConvertedArgs(), System.Dynamic.DynamicObject.MetaDynamic.GetLimitedSelf(), System.Dynamic.DynamicObject.MetaDynamic.GetRestrictions(), System.Nullable< T >.GetUnderlyingType(), System.Linq.Expressions.CachedReflectionInfo.InvalidCastException_Ctor_String, System.Dynamic.DynamicObject.MetaDynamic.IsOverridden(), System.Dynamic.BindingRestrictions.Merge(), System.Linq.Expressions.Expression< TDelegate >.New(), System.Linq.Expressions.Expression< TDelegate >.NewArrayInit(), System.Linq.Expressions.Utils.Null, System.Linq.Expressions.CachedReflectionInfo.Object_GetType, System.Linq.Expressions.Expression< TDelegate >.OrElse(), System.Linq.Expressions.Expression< TDelegate >.Parameter(), System.Dynamic.DynamicObject.MetaDynamic.ReferenceArgAssign(), System.Linq.Expressions.CachedReflectionInfo.String_Format_String_ObjectArray, System.Linq.Expressions.Expression< TDelegate >.Throw(), System.Linq.Expressions.Expression< TDelegate >.TypeIs(), System.Dynamic.DynamicObject.MetaDynamic.Value, and System.value.