Terraria: System.Dynamic.DynamicObject.MetaDynamic.ReferenceArgAssign
ReferenceArgAssign()
static Expression System.Dynamic.DynamicObject.MetaDynamic.ReferenceArgAssign (Expression callArgs, Expression[] args) inline static private
Definition at line 167 of file DynamicObject.cs.
        {
            ReadOnlyCollectionBuilder<Expression> readOnlyCollectionBuilder = null;
            for (int i = 0; i < args.Length; i++)
            {
                ParameterExpression parameterExpression = args[i] as ParameterExpression;
                ContractUtils.Requires(parameterExpression != null, "args");
                if (parameterExpression.IsByRef)
                {
                    if (readOnlyCollectionBuilder == null)
                    {
                        readOnlyCollectionBuilder = new ReadOnlyCollectionBuilder<Expression>();
                    }
                    readOnlyCollectionBuilder.Add(System.Linq.Expressions.Expression.Assign(parameterExpression, System.Linq.Expressions.Expression.Convert(System.Linq.Expressions.Expression.ArrayIndex(callArgs, System.Linq.Expressions.Utils.Constant(i)), parameterExpression.Type)));
                }
            }
            if (readOnlyCollectionBuilder != null)
            {
                return System.Linq.Expressions.Expression.Block(readOnlyCollectionBuilder);
            }
            return System.Linq.Expressions.Utils.Empty;
        }
References System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Linq.Expressions.Expression< TDelegate >.ArrayIndex(), System.Linq.Expressions.Expression< TDelegate >.Assign(), System.Linq.Expressions.Expression< TDelegate >.Block(), System.Linq.Expressions.Utils.Constant(), System.Linq.Expressions.Expression< TDelegate >.Convert(), System.Linq.Expressions.Utils.Empty, and System.Dynamic.Utils.ContractUtils.Requires().
Referenced by System.Dynamic.DynamicObject.MetaDynamic.BuildCallMethodWithResult< TBinder >(), System.Dynamic.DynamicObject.MetaDynamic.CallMethodNoResult< TBinder >(), and System.Dynamic.DynamicObject.MetaDynamic.CallMethodReturnLast< TBinder >().