Terraria: System.Security.Cryptography.Rfc2898DeriveBytes.ValidateHashAlgorithm
ValidateHashAlgorithm()
static void System.Security.Cryptography.Rfc2898DeriveBytes.ValidateHashAlgorithm (HashAlgorithmName hashAlgorithm) inline static private
Definition at line 396 of file Rfc2898DeriveBytes.cs.
    {
        if (string.IsNullOrEmpty(hashAlgorithm.Name))
        {
            throw new ArgumentException(System.SR.Cryptography_HashAlgorithmNameNullOrEmpty, "hashAlgorithm");
        }
        string name = hashAlgorithm.Name;
        if (name != HashAlgorithmName.SHA1.Name && name != HashAlgorithmName.SHA256.Name && name != HashAlgorithmName.SHA384.Name && name != HashAlgorithmName.SHA512.Name)
        {
            throw new CryptographicException(System.SR.Format(System.SR.Cryptography_UnknownHashAlgorithm, name));
        }
    }
References System.SR.Cryptography_HashAlgorithmNameNullOrEmpty, System.SR.Cryptography_UnknownHashAlgorithm, System.SR.Format(), System.Security.Cryptography.HashAlgorithmName.Name, System.Security.Cryptography.HashAlgorithmName.SHA1, System.Security.Cryptography.HashAlgorithmName.SHA256, System.Security.Cryptography.HashAlgorithmName.SHA384, and System.Security.Cryptography.HashAlgorithmName.SHA512.
Referenced by System.Security.Cryptography.Rfc2898DeriveBytes.Pbkdf2(), System.Security.Cryptography.Rfc2898DeriveBytes.Pbkdf2(), System.Security.Cryptography.Rfc2898DeriveBytes.Pbkdf2(), and System.Security.Cryptography.Rfc2898DeriveBytes.Pbkdf2().