Terraria: System.Security.Cryptography.Rfc2898DeriveBytes.Rfc2898DeriveBytes
Rfc2898DeriveBytes() [8/9]
System.Security.Cryptography.Rfc2898DeriveBytes.Rfc2898DeriveBytes (string password, int saltSize, int iterations, HashAlgorithmName hashAlgorithm) inline
Definition at line 102 of file Rfc2898DeriveBytes.cs.
    {
        if (saltSize < 0)
        {
            throw new ArgumentOutOfRangeException("saltSize", System.SR.ArgumentOutOfRange_NeedNonNegNum);
        }
        if (iterations <= 0)
        {
            throw new ArgumentOutOfRangeException("iterations", System.SR.ArgumentOutOfRange_NeedPosNum);
        }
        _salt = new byte[saltSize + 4];
        RandomNumberGenerator.Fill(_salt.AsSpan(0, saltSize));
        _iterations = (uint)iterations;
        byte[] bytes = Encoding.UTF8.GetBytes(password);
        HashAlgorithm = hashAlgorithm;
        _hmac = OpenHmac(bytes);
        CryptographicOperations.ZeroMemory(bytes);
        _blockSize = _hmac.HashSize >> 3;
        Initialize();
    }
References System.Security.Cryptography.Rfc2898DeriveBytes._blockSize, System.Security.Cryptography.Rfc2898DeriveBytes._hmac, System.Security.Cryptography.Rfc2898DeriveBytes._iterations, System.Security.Cryptography.Rfc2898DeriveBytes._salt, System.SR.ArgumentOutOfRange_NeedNonNegNum, System.SR.ArgumentOutOfRange_NeedPosNum, System.bytes, System.Security.Cryptography.RandomNumberGenerator.Fill(), System.Security.Cryptography.Rfc2898DeriveBytes.Initialize(), System.Security.Cryptography.Rfc2898DeriveBytes.OpenHmac(), System.Text.Encoding.UTF8, and System.Security.Cryptography.CryptographicOperations.ZeroMemory().