Terraria: System.Security.Cryptography.Rfc2898DeriveBytes.Initialize
Initialize()
void System.Security.Cryptography.Rfc2898DeriveBytes.Initialize () inline private
Definition at line 247 of file Rfc2898DeriveBytes.cs.
    {
        if (_buffer != null)
        {
            Array.Clear(_buffer);
        }
        _buffer = new byte[_blockSize];
        _block = 0u;
        _startIndex = (_endIndex = 0);
    }
References System.Security.Cryptography.Rfc2898DeriveBytes._block, System.Security.Cryptography.Rfc2898DeriveBytes._blockSize, System.Security.Cryptography.Rfc2898DeriveBytes._buffer, System.Security.Cryptography.Rfc2898DeriveBytes._endIndex, System.Security.Cryptography.Rfc2898DeriveBytes._startIndex, and System.Array.Clear().
Referenced by System.Security.Cryptography.Rfc2898DeriveBytes.Rfc2898DeriveBytes(), System.Security.Cryptography.Rfc2898DeriveBytes.Rfc2898DeriveBytes(), and System.Security.Cryptography.Rfc2898DeriveBytes.Reset().