Terraria: System.Runtime.Serialization.Json.JsonEncodingStreamWrapper.InitForReading
InitForReading()
void System.Runtime.Serialization.Json.JsonEncodingStreamWrapper.InitForReading (Stream inputStream, Encoding expectedEncoding) inline private
Definition at line 381 of file JsonEncodingStreamWrapper.cs.
    {
        try
        {
            _stream = new BufferedStream(inputStream);
            SupportedEncoding supportedEncoding = GetSupportedEncoding(expectedEncoding);
            SupportedEncoding supportedEncoding2 = ReadEncoding();
            if (supportedEncoding != SupportedEncoding.None && supportedEncoding != supportedEncoding2)
            {
                ThrowExpectedEncodingMismatch(supportedEncoding, supportedEncoding2);
            }
            if (supportedEncoding2 != 0)
            {
                EnsureBuffers();
                FillBuffer(254);
                _encodingCode = supportedEncoding2;
                _encoding = GetEncoding(supportedEncoding2);
                CleanupCharBreak();
                int chars = _encoding.GetChars(_bytes, _byteOffset, _byteCount, _chars, 0);
                _byteOffset = 0;
                _byteCount = s_validatingUTF8.GetBytes(_chars, 0, chars, _bytes, 0);
            }
        }
        catch (DecoderFallbackException innerException)
        {
            throw new XmlException(System.SR.JsonInvalidBytes, innerException);
        }
    }
References System.Runtime.Serialization.Json.JsonEncodingStreamWrapper._byteCount, System.Runtime.Serialization.Json.JsonEncodingStreamWrapper._byteOffset, System.Runtime.Serialization.Json.JsonEncodingStreamWrapper._bytes, System.Runtime.Serialization.Json.JsonEncodingStreamWrapper._chars, System.Runtime.Serialization.Json.JsonEncodingStreamWrapper._encoding, System.Runtime.Serialization.Json.JsonEncodingStreamWrapper._encodingCode, System.Runtime.Serialization.Json.JsonEncodingStreamWrapper._stream, System.chars, System.Runtime.Serialization.Json.JsonEncodingStreamWrapper.CleanupCharBreak(), System.Runtime.Serialization.Dictionary, System.Runtime.Serialization.Json.JsonEncodingStreamWrapper.EnsureBuffers(), System.Runtime.Serialization.Json.JsonEncodingStreamWrapper.FillBuffer(), System.Text.Encoding.GetChars(), System.Runtime.Serialization.Json.JsonEncodingStreamWrapper.GetEncoding(), System.Runtime.Serialization.Json.JsonEncodingStreamWrapper.GetSupportedEncoding(), System.SR.JsonInvalidBytes, System.Runtime.Serialization.Json.JsonEncodingStreamWrapper.ReadEncoding(), System.Runtime.Serialization.Json.JsonEncodingStreamWrapper.s_validatingUTF8, System.Runtime.Serialization.Json.JsonEncodingStreamWrapper.ThrowExpectedEncodingMismatch(), and System.Xml.XmlException.
Referenced by System.Runtime.Serialization.Json.JsonEncodingStreamWrapper.JsonEncodingStreamWrapper().