Terraria: System.Security.Cryptography.Rfc2898DeriveBytes.GetBytes
GetBytes()
override byte[] System.Security.Cryptography.Rfc2898DeriveBytes.GetBytes (int cb) inline
Definition at line 171 of file Rfc2898DeriveBytes.cs.
    {
        if (cb <= 0)
        {
            throw new ArgumentOutOfRangeException("cb", System.SR.ArgumentOutOfRange_NeedPosNum);
        }
        byte[] array = new byte[cb];
        int i = 0;
        int num = _endIndex - _startIndex;
        if (num > 0)
        {
            if (cb < num)
            {
                Buffer.BlockCopy(_buffer, _startIndex, array, 0, cb);
                _startIndex += cb;
                return array;
            }
            Buffer.BlockCopy(_buffer, _startIndex, array, 0, num);
            _startIndex = (_endIndex = 0);
            i += num;
        }
        for (; i < cb; i += _blockSize)
        {
            Func();
            int num2 = cb - i;
            if (num2 >= _blockSize)
            {
                Buffer.BlockCopy(_buffer, 0, array, i, _blockSize);
                continue;
            }
            Buffer.BlockCopy(_buffer, 0, array, i, num2);
            _startIndex = num2;
            _endIndex = _buffer.Length;
            return array;
        }
        return array;
    }
References System.Security.Cryptography.Rfc2898DeriveBytes._blockSize, System.Security.Cryptography.Rfc2898DeriveBytes._buffer, System.Security.Cryptography.Rfc2898DeriveBytes._endIndex, System.Security.Cryptography.Rfc2898DeriveBytes._startIndex, System.SR.ArgumentOutOfRange_NeedPosNum, System.array, System.Buffer.BlockCopy(), and System.Security.Cryptography.Rfc2898DeriveBytes.Func().
Referenced by System.Security.Cryptography.PasswordBasedEncryption.Encrypt(), and System.Security.Cryptography.PasswordBasedEncryption.Pbes2Decrypt().