Terraria: System.Runtime.Serialization.Json.JsonEncodingStreamWrapper.CleanupCharBreak
CleanupCharBreak()
void System.Runtime.Serialization.Json.JsonEncodingStreamWrapper.CleanupCharBreak () inline private
Definition at line 315 of file JsonEncodingStreamWrapper.cs.
    {
        int num = _byteOffset + _byteCount;
        if (_byteCount % 2 != 0)
        {
            int num2 = _stream.ReadByte();
            if (num2 < 0)
            {
                throw new XmlException(System.SR.JsonUnexpectedEndOfFile);
            }
            _bytes[num++] = (byte)num2;
            _byteCount++;
        }
        int num3 = ((_encodingCode != SupportedEncoding.UTF16LE) ? (_bytes[num - 1] + (_bytes[num - 2] << 8)) : (_bytes[num - 2] + (_bytes[num - 1] << 8)));
        if ((num3 & 0xDC00) != 56320 && num3 >= 55296 && num3 <= 56319)
        {
            int num4 = _stream.ReadByte();
            int num5 = _stream.ReadByte();
            if (num5 < 0)
            {
                throw new XmlException(System.SR.JsonUnexpectedEndOfFile);
            }
            _bytes[num++] = (byte)num4;
            _bytes[num++] = (byte)num5;
            _byteCount += 2;
        }
    }
References System.Runtime.Serialization.Json.JsonEncodingStreamWrapper._byteCount, System.Runtime.Serialization.Json.JsonEncodingStreamWrapper._byteOffset, System.Runtime.Serialization.Json.JsonEncodingStreamWrapper._bytes, System.Runtime.Serialization.Json.JsonEncodingStreamWrapper._encodingCode, System.Runtime.Serialization.Json.JsonEncodingStreamWrapper._stream, System.Runtime.Serialization.Dictionary, System.SR.JsonUnexpectedEndOfFile, System.IO.Stream.ReadByte(), and System.Xml.XmlException.
Referenced by System.Runtime.Serialization.Json.JsonEncodingStreamWrapper.InitForReading(), and System.Runtime.Serialization.Json.JsonEncodingStreamWrapper.Read().