Terraria: System.Runtime.Serialization.Json.JsonEncodingStreamWrapper.ProcessBuffer
ProcessBuffer()
static ArraySegment< byte > System.Runtime.Serialization.Json.JsonEncodingStreamWrapper.ProcessBuffer (byte[] buffer, int offset, int count, Encoding encoding) inline static
Definition at line 129 of file JsonEncodingStreamWrapper.cs.
    {
        try
        {
            SupportedEncoding supportedEncoding = GetSupportedEncoding(encoding);
            SupportedEncoding supportedEncoding2 = ((count >= 2) ? ReadEncoding(buffer[offset], buffer[offset + 1]) : SupportedEncoding.UTF8);
            if (supportedEncoding != SupportedEncoding.None && supportedEncoding != supportedEncoding2)
            {
                ThrowExpectedEncodingMismatch(supportedEncoding, supportedEncoding2);
            }
            if (supportedEncoding2 == SupportedEncoding.UTF8)
            {
                return new ArraySegment<byte>(buffer, offset, count);
            }
            return new ArraySegment<byte>(s_validatingUTF8.GetBytes(GetEncoding(supportedEncoding2).GetChars(buffer, offset, count)));
        }
        catch (DecoderFallbackException innerException)
        {
            throw new XmlException(System.SR.JsonInvalidBytes, innerException);
        }
    }
References System.buffer, System.count, System.Runtime.Serialization.Dictionary, System.Runtime.Serialization.Json.JsonEncodingStreamWrapper.GetEncoding(), System.Runtime.Serialization.Json.JsonEncodingStreamWrapper.GetSupportedEncoding(), System.SR.JsonInvalidBytes, System.offset, System.Runtime.Serialization.Json.JsonEncodingStreamWrapper.ReadEncoding(), System.Runtime.Serialization.Json.JsonEncodingStreamWrapper.s_validatingUTF8, System.Runtime.Serialization.Json.JsonEncodingStreamWrapper.ThrowExpectedEncodingMismatch(), and System.Xml.XmlException.
Referenced by System.Runtime.Serialization.Json.XmlJsonReader.SetInput().