Terraria: System.Security.Cryptography.Rfc2898DeriveBytes.Func
Func()
void System.Security.Cryptography.Rfc2898DeriveBytes.Func () inline private
Definition at line 258 of file Rfc2898DeriveBytes.cs.
    {
        if (_block == uint.MaxValue)
        {
            throw new CryptographicException(System.SR.Cryptography_ExceedKdfExtractLimit);
        }
        BinaryPrimitives.WriteUInt32BigEndian(_salt.AsSpan(_salt.Length - 4), _block + 1);
        Span<byte> span = stackalloc byte[64];
        span = span.Slice(0, _blockSize);
        if (!_hmac.TryComputeHash(_salt, span, out var bytesWritten) || bytesWritten != _blockSize)
        {
            throw new CryptographicException();
        }
        span.CopyTo(_buffer);
        for (int i = 2; i <= _iterations; i++)
        {
            if (!_hmac.TryComputeHash(span, span, out bytesWritten) || bytesWritten != _blockSize)
            {
                throw new CryptographicException();
            }
            for (int num = _buffer.Length - 1; num >= 0; num--)
            {
                _buffer[num] ^= span[num];
            }
        }
        _block++;
    }
References System.Security.Cryptography.Rfc2898DeriveBytes._block, System.Security.Cryptography.Rfc2898DeriveBytes._blockSize, System.Security.Cryptography.Rfc2898DeriveBytes._buffer, System.Security.Cryptography.Rfc2898DeriveBytes._hmac, System.Security.Cryptography.Rfc2898DeriveBytes._iterations, System.Security.Cryptography.Rfc2898DeriveBytes._salt, System.Span< T >.CopyTo(), System.SR.Cryptography_ExceedKdfExtractLimit, System.Span< T >.Slice(), System.Security.Cryptography.HashAlgorithm.TryComputeHash(), and System.Buffers.Binary.BinaryPrimitives.WriteUInt32BigEndian().
Referenced by System.Security.Cryptography.Rfc2898DeriveBytes.GetBytes().