Terraria: System.Runtime.Serialization.Json.JsonEncodingStreamWrapper.Write
Write() [1/2]
override void System.Runtime.Serialization.Json.JsonEncodingStreamWrapper.Write (byte[] buffer, int offset, int count) inline
Definition at line 221 of file JsonEncodingStreamWrapper.cs.
    {
        if (_encodingCode == SupportedEncoding.UTF8)
        {
            _stream.Write(buffer, offset, count);
            return;
        }
        while (count > 0)
        {
            int num = ((_chars.Length < count) ? _chars.Length : count);
            int chars = _dec.GetChars(buffer, offset, num, _chars, 0, flush: false);
            _byteCount = _enc.GetBytes(_chars, 0, chars, _bytes, 0, flush: false);
            _stream.Write(_bytes, 0, _byteCount);
            offset += num;
            count -= num;
        }
    }
References System.Runtime.Serialization.Json.JsonEncodingStreamWrapper._byteCount, System.Runtime.Serialization.Json.JsonEncodingStreamWrapper._bytes, System.Runtime.Serialization.Json.JsonEncodingStreamWrapper._chars, System.Runtime.Serialization.Json.JsonEncodingStreamWrapper._dec, System.Runtime.Serialization.Json.JsonEncodingStreamWrapper._enc, System.Runtime.Serialization.Json.JsonEncodingStreamWrapper._encodingCode, System.Runtime.Serialization.Json.JsonEncodingStreamWrapper._stream, System.buffer, System.chars, System.count, System.Runtime.Serialization.Dictionary, System.Text.Encoder.GetBytes(), System.Text.Decoder.GetChars(), System.offset, and System.IO.Stream.Write().