Terraria: System.Runtime.Serialization.Json.JsonEncodingStreamWrapper.Read
Read() [1/2]
override int System.Runtime.Serialization.Json.JsonEncodingStreamWrapper.Read (byte[] buffer, int offset, int count) inline
Definition at line 163 of file JsonEncodingStreamWrapper.cs.
    {
        try
        {
            if (_byteCount == 0)
            {
                if (_encodingCode == SupportedEncoding.UTF8)
                {
                    return _stream.Read(buffer, offset, count);
                }
                _byteOffset = 0;
                _byteCount = _stream.Read(_bytes, _byteCount, (_chars.Length - 1) * 2);
                if (_byteCount == 0)
                {
                    return 0;
                }
                CleanupCharBreak();
                int chars = _encoding.GetChars(_bytes, 0, _byteCount, _chars, 0);
                _byteCount = Encoding.UTF8.GetBytes(_chars, 0, chars, _bytes, 0);
            }
            if (_byteCount < count)
            {
                count = _byteCount;
            }
            Buffer.BlockCopy(_bytes, _byteOffset, buffer, offset, count);
            _byteOffset += count;
            _byteCount -= count;
            return count;
        }
        catch (DecoderFallbackException innerException)
        {
            throw new XmlException(System.SR.JsonInvalidBytes, innerException);
        }
    }
References System.Runtime.Serialization.Json.JsonEncodingStreamWrapper._byteCount, System.Runtime.Serialization.Json.JsonEncodingStreamWrapper._byteOffset, System.Runtime.Serialization.Json.JsonEncodingStreamWrapper._bytes, System.Runtime.Serialization.Json.JsonEncodingStreamWrapper._chars, System.Runtime.Serialization.Json.JsonEncodingStreamWrapper._encoding, System.Runtime.Serialization.Json.JsonEncodingStreamWrapper._encodingCode, System.Runtime.Serialization.Json.JsonEncodingStreamWrapper._stream, System.Buffer.BlockCopy(), System.buffer, System.chars, System.Runtime.Serialization.Json.JsonEncodingStreamWrapper.CleanupCharBreak(), System.count, System.Runtime.Serialization.Dictionary, System.Text.Encoding.GetChars(), System.SR.JsonInvalidBytes, System.offset, System.IO.Stream.Read(), System.Text.Encoding.UTF8, and System.Xml.XmlException.