Terraria: System.Security.Cryptography.Rfc2898DeriveBytes.Pbkdf2Core
Pbkdf2Core() [2/2]
static void System.Security.Cryptography.Rfc2898DeriveBytes.Pbkdf2Core (ReadOnlySpan< char > password, ReadOnlySpan< byte > salt, Span< byte > destination, int iterations, HashAlgorithmName hashAlgorithm) inline static private
Definition at line 364 of file Rfc2898DeriveBytes.cs.
    {
        if (!destination.IsEmpty)
        {
            byte[] array = null;
            int maxByteCount = s_throwingUtf8Encoding.GetMaxByteCount(password.Length);
            Span<byte> span = ((maxByteCount <= 256) ? stackalloc byte[256] : ((Span<byte>)(array = System.Security.Cryptography.CryptoPool.Rent(maxByteCount))));
            Span<byte> bytes = span;
            Span<byte> span2 = bytes[..s_throwingUtf8Encoding.GetBytes(password, bytes)];
            try
            {
                Pbkdf2Implementation.Fill(span2, salt, iterations, hashAlgorithm, destination);
            }
            finally
            {
                CryptographicOperations.ZeroMemory(span2);
            }
            if (array != null)
            {
                System.Security.Cryptography.CryptoPool.Return(array, 0);
            }
        }
    }
References System.array, System.bytes, System.destination, Internal.Cryptography.Pbkdf2Implementation.Fill(), System.ReadOnlySpan< T >.Length, System.Security.Cryptography.CryptoPool.Rent(), System.Security.Cryptography.CryptoPool.Return(), System.Security.Cryptography.Rfc2898DeriveBytes.s_throwingUtf8Encoding, and System.Security.Cryptography.CryptographicOperations.ZeroMemory().
Referenced by System.Security.Cryptography.Rfc2898DeriveBytes.Pbkdf2(), System.Security.Cryptography.Rfc2898DeriveBytes.Pbkdf2(), System.Security.Cryptography.Rfc2898DeriveBytes.Pbkdf2(), and System.Security.Cryptography.Rfc2898DeriveBytes.Pbkdf2().