Terraria: System.Runtime.Serialization.Json.JsonEncodingStreamWrapper.GetSupportedEncoding
GetSupportedEncoding()
static SupportedEncoding System.Runtime.Serialization.Json.JsonEncodingStreamWrapper.GetSupportedEncoding (Encoding encoding) inline static private
Definition at line 272 of file JsonEncodingStreamWrapper.cs.
    {
        if (encoding == null)
        {
            return SupportedEncoding.None;
        }
        if (encoding.WebName == s_validatingUTF8.WebName)
        {
            return SupportedEncoding.UTF8;
        }
        if (encoding.WebName == s_validatingUTF16.WebName)
        {
            return SupportedEncoding.UTF16LE;
        }
        if (encoding.WebName == s_validatingBEUTF16.WebName)
        {
            return SupportedEncoding.UTF16BE;
        }
        throw new XmlException(System.SR.JsonEncodingNotSupported);
    }
References System.SR.JsonEncodingNotSupported, System.Runtime.Serialization.Json.JsonEncodingStreamWrapper.s_validatingBEUTF16, System.Runtime.Serialization.Json.JsonEncodingStreamWrapper.s_validatingUTF16, System.Runtime.Serialization.Json.JsonEncodingStreamWrapper.s_validatingUTF8, System.Text.Encoding.WebName, and System.Xml.XmlException.
Referenced by System.Runtime.Serialization.Json.JsonEncodingStreamWrapper.InitForReading(), System.Runtime.Serialization.Json.JsonEncodingStreamWrapper.InitForWriting(), and System.Runtime.Serialization.Json.JsonEncodingStreamWrapper.ProcessBuffer().