Terraria: System.Security.Cryptography.Rfc2898DeriveBytes.OpenHmac
OpenHmac()
HMAC System.Security.Cryptography.Rfc2898DeriveBytes.OpenHmac (byte[] password) inline private
Definition at line 220 of file Rfc2898DeriveBytes.cs.
    {
        HashAlgorithmName hashAlgorithm = HashAlgorithm;
        if (string.IsNullOrEmpty(hashAlgorithm.Name))
        {
            throw new CryptographicException(System.SR.Cryptography_HashAlgorithmNameNullOrEmpty);
        }
        if (hashAlgorithm == HashAlgorithmName.SHA1)
        {
            return new HMACSHA1(password);
        }
        if (hashAlgorithm == HashAlgorithmName.SHA256)
        {
            return new HMACSHA256(password);
        }
        if (hashAlgorithm == HashAlgorithmName.SHA384)
        {
            return new HMACSHA384(password);
        }
        if (hashAlgorithm == HashAlgorithmName.SHA512)
        {
            return new HMACSHA512(password);
        }
        throw new CryptographicException(System.SR.Format(System.SR.Cryptography_UnknownHashAlgorithm, hashAlgorithm.Name));
    }
References System.SR.Cryptography_HashAlgorithmNameNullOrEmpty, System.SR.Cryptography_UnknownHashAlgorithm, System.SR.Format(), System.Security.Cryptography.Rfc2898DeriveBytes.HashAlgorithm, System.Security.Cryptography.HashAlgorithmName.Name, System.Security.Cryptography.HashAlgorithmName.SHA1, System.Security.Cryptography.HashAlgorithmName.SHA256, System.Security.Cryptography.HashAlgorithmName.SHA384, and System.Security.Cryptography.HashAlgorithmName.SHA512.
Referenced by System.Security.Cryptography.Rfc2898DeriveBytes.Rfc2898DeriveBytes(), and System.Security.Cryptography.Rfc2898DeriveBytes.Rfc2898DeriveBytes().