Terraria: Microsoft.Win32.SafeHandles.SafeFileHandle.OverlappedValueTaskSource.Complete
Complete()
void Microsoft.Win32.SafeHandles.SafeFileHandle.OverlappedValueTaskSource.Complete (uint errorCode, uint numBytes) inline package
Definition at line 357 of file SafeFileHandle.cs.
        {
            OSFileStreamStrategy strategy = _strategy;
            ReleaseResources();
            switch (errorCode)
            {
            case 0u:
            case 38u:
            case 109u:
            case 232u:
                if (_bufferSize != numBytes)
                {
                    strategy?.OnIncompleteOperation(_bufferSize, (int)numBytes);
                }
                _source.SetResult((int)numBytes);
                break;
            case 995u:
            {
                strategy?.OnIncompleteOperation(_bufferSize, 0);
                CancellationToken token = _cancellationRegistration.Token;
                _source.SetException(token.IsCancellationRequested ? new OperationCanceledException(token) : new OperationCanceledException());
                break;
            }
            default:
                strategy?.OnIncompleteOperation(_bufferSize, 0);
                _source.SetException(Win32Marshal.GetExceptionForWin32Error((int)errorCode));
                break;
            }
        }
References Microsoft.Win32.SafeHandles.SafeFileHandle.OverlappedValueTaskSource._bufferSize, Microsoft.Win32.SafeHandles.SafeFileHandle.OverlappedValueTaskSource._cancellationRegistration, Microsoft.Win32.SafeHandles.SafeFileHandle.OverlappedValueTaskSource._source, Microsoft.Win32.SafeHandles.SafeFileHandle.OverlappedValueTaskSource._strategy, System.IO.Win32Marshal.GetExceptionForWin32Error(), System.Threading.CancellationToken.IsCancellationRequested, System.IO.Strategies.OSFileStreamStrategy.OnIncompleteOperation(), Microsoft.Win32.SafeHandles.SafeFileHandle.OverlappedValueTaskSource.ReleaseResources(), System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore< TResult >.SetException(), System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore< TResult >.SetResult(), and System.Threading.CancellationTokenRegistration.Token.
Referenced by Microsoft.Win32.SafeHandles.SafeFileHandle.OverlappedValueTaskSource.FinishedScheduling().