Terraria: Microsoft.Win32.SafeHandles.SafeFileHandle.OverlappedValueTaskSource.IOCallback
IOCallback()
static unsafe void Microsoft.Win32.SafeHandles.SafeFileHandle.OverlappedValueTaskSource.IOCallback (uint errorCode, uint numBytes, NativeOverlapped * pOverlapped) inline static private
Definition at line 348 of file SafeFileHandle.cs.
        {
            OverlappedValueTaskSource overlappedValueTaskSource = (OverlappedValueTaskSource)ThreadPoolBoundHandle.GetNativeOverlappedState(pOverlapped);
            if (Interlocked.Exchange(ref overlappedValueTaskSource._result, 0x8000000000000000uL | ((ulong)numBytes << 32) | errorCode) != 0L)
            {
                overlappedValueTaskSource.Complete(errorCode, numBytes);
            }
        }
References Microsoft.Win32.SafeHandles.SafeFileHandle.OverlappedValueTaskSource.OverlappedValueTaskSource(), System.Threading.Interlocked.Exchange(), System.Threading.ThreadPoolBoundHandle.GetNativeOverlappedState(), and System.L.