Terraria: Microsoft.Win32.SafeHandles.SafeFileHandle.OverlappedValueTaskSource.ReleaseResources
ReleaseResources()
unsafe void Microsoft.Win32.SafeHandles.SafeFileHandle.OverlappedValueTaskSource.ReleaseResources () inline private
Definition at line 327 of file SafeFileHandle.cs.
        {
            _strategy = null;
            _cancellationRegistration.Dispose();
            _memoryHandle.Dispose();
            if (_overlapped != null)
            {
                _fileHandle.ThreadPoolBinding.FreeNativeOverlapped(_overlapped);
                _overlapped = null;
            }
        }
References Microsoft.Win32.SafeHandles.SafeFileHandle.OverlappedValueTaskSource._cancellationRegistration, Microsoft.Win32.SafeHandles.SafeFileHandle.OverlappedValueTaskSource._fileHandle, Microsoft.Win32.SafeHandles.SafeFileHandle.OverlappedValueTaskSource._memoryHandle, Microsoft.Win32.SafeHandles.SafeFileHandle.OverlappedValueTaskSource._overlapped, Microsoft.Win32.SafeHandles.SafeFileHandle.OverlappedValueTaskSource._strategy, System.Buffers.MemoryHandle.Dispose(), System.Threading.CancellationTokenRegistration.Dispose(), System.Threading.ThreadPoolBoundHandle.FreeNativeOverlapped(), and Microsoft.Win32.SafeHandles.SafeFileHandle.ThreadPoolBinding.
Referenced by Microsoft.Win32.SafeHandles.SafeFileHandle.OverlappedValueTaskSource.Complete(), and Microsoft.Win32.SafeHandles.SafeFileHandle.OverlappedValueTaskSource.Dispose().