Terraria: Microsoft.Win32.SafeHandles.SafeFileHandle.OverlappedValueTaskSource.OverlappedValueTaskSource
OverlappedValueTaskSource()
Microsoft.Win32.SafeHandles.SafeFileHandle.OverlappedValueTaskSource.OverlappedValueTaskSource (SafeFileHandle fileHandle) inline package
Definition at line 238 of file SafeFileHandle.cs.
        {
            _fileHandle = fileHandle;
            _source.RunContinuationsAsynchronously = true;
            _preallocatedOverlapped = PreAllocatedOverlapped.UnsafeCreate(s_ioCallback, this, null);
        }
References Microsoft.Win32.SafeHandles.SafeFileHandle.OverlappedValueTaskSource._fileHandle, Microsoft.Win32.SafeHandles.SafeFileHandle.OverlappedValueTaskSource._preallocatedOverlapped, Microsoft.Win32.SafeHandles.SafeFileHandle.OverlappedValueTaskSource.s_ioCallback, and System.Threading.PreAllocatedOverlapped.UnsafeCreate().
Referenced by Microsoft.Win32.SafeHandles.SafeFileHandle.OverlappedValueTaskSource.IOCallback(), and Microsoft.Win32.SafeHandles.SafeFileHandle.OverlappedValueTaskSource.RegisterForCancellation().