Terraria: System.Net.Security.SafeFreeContextBufferChannelBinding.QueryContextChannelBinding
QueryContextChannelBinding()
static unsafe int System.Net.Security.SafeFreeContextBufferChannelBinding.QueryContextChannelBinding (SafeDeleteContext phContext, global::Interop::SspiCli::ContextAttribute contextAttribute, SecPkgContext_Bindings * buffer, SafeFreeContextBufferChannelBinding refHandle) inline static inherited
Definition at line 34 of file SafeFreeContextBufferChannelBinding.cs.
    {
        int num = -2146893055;
        if (contextAttribute != global::Interop.SspiCli.ContextAttribute.SECPKG_ATTR_ENDPOINT_BINDINGS && contextAttribute != global::Interop.SspiCli.ContextAttribute.SECPKG_ATTR_UNIQUE_BINDINGS)
        {
            return num;
        }
        try
        {
            bool success = false;
            phContext.DangerousAddRef(ref success);
            num = global::Interop.SspiCli.QueryContextAttributesW(ref phContext._handle, contextAttribute, buffer);
        }
        finally
        {
            phContext.DangerousRelease();
        }
        if (num == 0 && refHandle != null)
        {
            refHandle.Set(buffer->Bindings);
            refHandle._size = buffer->BindingsLength;
        }
        if (num != 0)
        {
            refHandle?.SetHandleAsInvalid();
        }
        return num;
    }
References System.Net.Security.SafeDeleteContext._handle, System.buffer, System.Runtime.InteropServices.SafeHandle.DangerousAddRef(), System.Runtime.InteropServices.SafeHandle.DangerousRelease(), System.Net.Security.SafeFreeContextBufferChannelBinding.Set(), and System.Runtime.InteropServices.SafeHandle.SetHandleAsInvalid().
Referenced by System.Net.SSPISecureChannelType.QueryContextChannelBinding().