Terraria: System.Transactions.TransactionState.BeginCommit
BeginCommit()
virtual void System.Transactions.TransactionState.BeginCommit (InternalTransaction tx, bool asyncCommit, AsyncCallback asyncCallback, object asyncState) inline package virtual inherited
Reimplemented in System.Transactions.TransactionStateAborted, System.Transactions.TransactionStateActive, System.Transactions.TransactionStateDelegated, System.Transactions.TransactionStateDelegatedAborting, System.Transactions.TransactionStatePromotedAborted, System.Transactions.TransactionStatePromotedAborting, System.Transactions.TransactionStatePromotedBase, System.Transactions.TransactionStatePromotedCommitting, System.Transactions.TransactionStatePromotedNonMSDTCAborted, System.Transactions.TransactionStatePromotedNonMSDTCBase, System.Transactions.TransactionStatePromotedNonMSDTCPhase0, System.Transactions.TransactionStatePromotedNonMSDTCSinglePhaseCommit, System.Transactions.TransactionStatePromotedNonMSDTCVolatilePhase1, and System.Transactions.TransactionStatePromotedP0Wave.
Definition at line 136 of file TransactionState.cs.
    {
        throw TransactionException.CreateTransactionStateException(tx._innerException, tx.DistributedTxId);
    }
References System.Transactions.InternalTransaction._innerException, System.Transactions.TransactionException.CreateTransactionStateException(), and System.Transactions.InternalTransaction.DistributedTxId.
Referenced by System.Transactions.CommittableTransaction.BeginCommit(), and System.Transactions.CommittableTransaction.Commit().