Terraria: System.Transactions.TransactionState.EnlistVolatile
EnlistVolatile() [1/2]
virtual Enlistment System.Transactions.TransactionState.EnlistVolatile (InternalTransaction tx, IEnlistmentNotification enlistmentNotification, EnlistmentOptions enlistmentOptions, Transaction atomicTransaction) inline package virtual inherited
Reimplemented in System.Transactions.TransactionStateActive, System.Transactions.TransactionStatePhase0, System.Transactions.TransactionStatePromotedBase, System.Transactions.TransactionStatePromotedNonMSDTCBase, System.Transactions.TransactionStatePromotedNonMSDTCSinglePhaseCommit, System.Transactions.TransactionStatePromotedNonMSDTCVolatilePhase1, and System.Transactions.TransactionStateSubordinateActive.
Definition at line 161 of file TransactionState.cs.
    {
        throw TransactionException.CreateTransactionStateException(tx._innerException, tx.DistributedTxId);
    }
References System.Transactions.InternalTransaction._innerException, System.Transactions.TransactionException.CreateTransactionStateException(), and System.Transactions.InternalTransaction.DistributedTxId.
Referenced by System.Transactions.Transaction.EnlistVolatile(), System.Transactions.TransactionStateSubordinateActive.EnlistVolatile(), System.Transactions.TransactionStateSubordinateActive.EnlistVolatile(), and System.Transactions.Transaction.EnlistVolatile().