Terraria: System.Transactions.TransactionState.ChangeStateTransactionAborted
ChangeStateTransactionAborted()
virtual void System.Transactions.TransactionState.ChangeStateTransactionAborted (InternalTransaction tx, Exception e) inline package virtual inherited
Reimplemented in System.Transactions.TransactionStateAborted, System.Transactions.TransactionStatePhase0, System.Transactions.TransactionStatePromotedAborted, System.Transactions.TransactionStatePromotedAborting, System.Transactions.TransactionStatePromotedNonMSDTCAborted, System.Transactions.TransactionStatePromotedNonMSDTCBase, System.Transactions.TransactionStatePromotedNonMSDTCSinglePhaseCommit, System.Transactions.TransactionStatePromotedP0Wave, System.Transactions.TransactionStateSPC, System.Transactions.TransactionStateVolatilePhase1, and System.Transactions.TransactionStateVolatileSPC.
Definition at line 210 of file TransactionState.cs.
    {
        TransactionsEtwProvider log = TransactionsEtwProvider.Log;
        if (log.IsEnabled())
        {
            log.TransactionExceptionTrace(TransactionExceptionType.InvalidOperationException, tx?.TransactionTraceId.TransactionIdentifier ?? string.Empty, e.ToString());
        }
        throw new InvalidOperationException();
    }
References System.Transactions.InvalidOperationException, System.Diagnostics.Tracing.EventSource.IsEnabled(), System.Transactions.TransactionsEtwProvider.Log, System.Exception.ToString(), System.Transactions.TransactionsEtwProvider.TransactionExceptionTrace(), System.Transactions.TransactionTraceIdentifier.TransactionIdentifier, and System.Transactions.InternalTransaction.TransactionTraceId.
Referenced by System.Transactions.DurableEnlistmentCommitting.Aborted(), System.Transactions.VolatileEnlistmentSPC.Aborted(), and System.Transactions.VolatileEnlistmentPreparing.ForceRollback().