Terraria: System.Transactions.TransactionState.ChangeStateTransactionCommitted
ChangeStateTransactionCommitted()
virtual void System.Transactions.TransactionState.ChangeStateTransactionCommitted (InternalTransaction tx) inline package virtual inherited
Reimplemented in System.Transactions.TransactionStatePromotedNonMSDTCSinglePhaseCommit, System.Transactions.TransactionStateSPC, and System.Transactions.TransactionStateVolatileSPC.
Definition at line 220 of file TransactionState.cs.
    {
        TransactionsEtwProvider log = TransactionsEtwProvider.Log;
        if (log.IsEnabled())
        {
            log.TransactionExceptionTrace(TransactionExceptionType.InvalidOperationException, tx?.TransactionTraceId.TransactionIdentifier ?? string.Empty, string.Empty);
        }
        throw new InvalidOperationException();
    }
References System.Transactions.InvalidOperationException, System.Diagnostics.Tracing.EventSource.IsEnabled(), System.Transactions.TransactionsEtwProvider.Log, System.Transactions.TransactionsEtwProvider.TransactionExceptionTrace(), System.Transactions.TransactionTraceIdentifier.TransactionIdentifier, and System.Transactions.InternalTransaction.TransactionTraceId.
Referenced by System.Transactions.DurableEnlistmentCommitting.Committed(), System.Transactions.VolatileEnlistmentSPC.Committed(), System.Transactions.DurableEnlistmentCommitting.EnlistmentDone(), and System.Transactions.VolatileEnlistmentSPC.EnlistmentDone().