Terraria: System.Transactions.TransactionState.CommonEnterState
CommonEnterState()
void System.Transactions.TransactionState.CommonEnterState (InternalTransaction tx) inline package inherited
Definition at line 129 of file TransactionState.cs.
    {
        tx.State = this;
    }
Referenced by System.Transactions.TransactionStateAborted.EnterState(), System.Transactions.TransactionStateActive.EnterState(), System.Transactions.TransactionStateCommitted.EnterState(), System.Transactions.TransactionStateDelegatedAborting.EnterState(), System.Transactions.TransactionStateDelegatedBase.EnterState(), System.Transactions.TransactionStateDelegatedCommitting.EnterState(), System.Transactions.TransactionStateDelegatedNonMSDTC.EnterState(), System.Transactions.TransactionStateInDoubt.EnterState(), System.Transactions.TransactionStateNonCommittablePromoted.EnterState(), System.Transactions.TransactionStatePhase0.EnterState(), System.Transactions.TransactionStatePromoted.EnterState(), System.Transactions.TransactionStatePromotedAborting.EnterState(), System.Transactions.TransactionStatePromotedCommitting.EnterState(), System.Transactions.TransactionStatePromotedEnded.EnterState(), System.Transactions.TransactionStatePromotedNonMSDTCEnded.EnterState(), System.Transactions.TransactionStatePromotedNonMSDTCPhase0.EnterState(), System.Transactions.TransactionStatePromotedNonMSDTCSinglePhaseCommit.EnterState(), System.Transactions.TransactionStatePromotedNonMSDTCVolatilePhase1.EnterState(), System.Transactions.TransactionStatePromotedP0Aborting.EnterState(), System.Transactions.TransactionStatePromotedP0Wave.EnterState(), System.Transactions.TransactionStateSPC.EnterState(), System.Transactions.TransactionStateSubordinateActive.EnterState(), System.Transactions.TransactionStateVolatilePhase1.EnterState(), System.Transactions.TransactionStateVolatileSPC.EnterState(), System.Transactions.TransactionStatePSPEOperation.Phase0PSPEInitialize(), System.Transactions.TransactionStatePSPEOperation.PSPEInitialize(), and System.Transactions.TransactionStatePSPEOperation.PSPEPromote().
html>