Terraria: System.Transactions.TransactionState.CheckForFinishedTransaction
CheckForFinishedTransaction()
virtual void System.Transactions.TransactionState.CheckForFinishedTransaction (InternalTransaction tx) inline package virtual inherited
Reimplemented in System.Transactions.TransactionStateAborted, System.Transactions.TransactionStateInDoubt, System.Transactions.TransactionStatePromotedAborted, System.Transactions.TransactionStatePromotedIndoubt, System.Transactions.TransactionStatePromotedNonMSDTCAborted, and System.Transactions.TransactionStatePromotedNonMSDTCIndoubt.
Definition at line 171 of file TransactionState.cs.
    {
    }
Referenced by System.Transactions.EnlistableStates.Promote(), System.Transactions.TransactionStatePhase0.Promote(), and System.Transactions.EnlistableStates.PromotedToken().
html>