Terraria: System.Transactions.TransactionState.RestartCommitIfNeeded
RestartCommitIfNeeded()
virtual void System.Transactions.TransactionState.RestartCommitIfNeeded (InternalTransaction tx) inline package virtual inherited
Reimplemented in System.Transactions.TransactionStateAborted, System.Transactions.TransactionStateDelegated, System.Transactions.TransactionStatePhase0, System.Transactions.TransactionStatePromotedAborted, System.Transactions.TransactionStatePromotedAborting, System.Transactions.TransactionStatePromotedBase, and System.Transactions.TransactionStatePromotedIndoubt.
Definition at line 284 of file TransactionState.cs.
    {
        TransactionsEtwProvider log = TransactionsEtwProvider.Log;
        if (log.IsEnabled())
        {
            log.TransactionExceptionTrace(TransactionExceptionType.InvalidOperationException, tx?.TransactionTraceId.TransactionIdentifier ?? string.Empty, string.Empty);
        }
        throw new InvalidOperationException();
    }
References System.Transactions.InvalidOperationException, System.Diagnostics.Tracing.EventSource.IsEnabled(), System.Transactions.TransactionsEtwProvider.Log, System.Transactions.TransactionsEtwProvider.TransactionExceptionTrace(), System.Transactions.TransactionTraceIdentifier.TransactionIdentifier, and System.Transactions.InternalTransaction.TransactionTraceId.
Referenced by System.Transactions.TransactionStatePhase0.EnlistDurable(), System.Transactions.TransactionStatePhase0.EnlistDurable(), and System.Transactions.TransactionStatePhase0.Promote().