Terraria: System.Transactions.TransactionState.CreateBlockingClone
CreateBlockingClone()
virtual void System.Transactions.TransactionState.CreateBlockingClone (InternalTransaction tx) inline package virtual inherited
Reimplemented in System.Transactions.EnlistableStates, System.Transactions.TransactionStateAborted, System.Transactions.TransactionStatePromotedAborted, System.Transactions.TransactionStatePromotedAborting, System.Transactions.TransactionStatePromotedBase, System.Transactions.TransactionStatePromotedEnded, System.Transactions.TransactionStatePromotedNonMSDTCAborted, System.Transactions.TransactionStatePromotedNonMSDTCBase, System.Transactions.TransactionStatePromotedNonMSDTCEnded, System.Transactions.TransactionStatePromotedNonMSDTCIndoubt, System.Transactions.TransactionStatePromotedNonMSDTCSinglePhaseCommit, System.Transactions.TransactionStatePromotedNonMSDTCVolatilePhase1, and System.Transactions.TransactionStateSubordinateActive.
Definition at line 200 of file TransactionState.cs.
    {
        throw TransactionException.CreateTransactionStateException(tx._innerException, tx.DistributedTxId);
    }
References System.Transactions.InternalTransaction._innerException, System.Transactions.TransactionException.CreateTransactionStateException(), and System.Transactions.InternalTransaction.DistributedTxId.
Referenced by System.Transactions.DependentTransaction.DependentTransaction(), and System.Transactions.TransactionStateSubordinateActive.CreateBlockingClone().