Terraria: System.Reflection.Metadata.Ecma335.CustomAttributeDecoder.DecodeNamedArgumentType
DecodeNamedArgumentType()
ArgumentTypeInfo System.Reflection.Metadata.Ecma335.CustomAttributeDecoder< TType >.DecodeNamedArgumentType (ref BlobReader valueReader, bool isElementType = false) inline private
Definition at line 149 of file CustomAttributeDecoder.cs.
    {
        ArgumentTypeInfo argumentTypeInfo = default(ArgumentTypeInfo);
        argumentTypeInfo.TypeCode = valueReader.ReadSerializationTypeCode();
        ArgumentTypeInfo result = argumentTypeInfo;
        switch (result.TypeCode)
        {
        case SerializationTypeCode.Boolean:
        case SerializationTypeCode.Char:
        case SerializationTypeCode.SByte:
        case SerializationTypeCode.Byte:
        case SerializationTypeCode.Int16:
        case SerializationTypeCode.UInt16:
        case SerializationTypeCode.Int32:
        case SerializationTypeCode.UInt32:
        case SerializationTypeCode.Int64:
        case SerializationTypeCode.UInt64:
        case SerializationTypeCode.Single:
        case SerializationTypeCode.Double:
        case SerializationTypeCode.String:
            result.Type = _provider.GetPrimitiveType((PrimitiveTypeCode)result.TypeCode);
            break;
        case SerializationTypeCode.Type:
            result.Type = _provider.GetSystemType();
            break;
        case SerializationTypeCode.TaggedObject:
            result.Type = _provider.GetPrimitiveType(PrimitiveTypeCode.Object);
            break;
        case SerializationTypeCode.SZArray:
        {
            if (isElementType)
            {
                throw new BadImageFormatException();
            }
            ArgumentTypeInfo argumentTypeInfo2 = DecodeNamedArgumentType(ref valueReader, isElementType: true);
            result.ElementType = argumentTypeInfo2.Type;
            result.ElementTypeCode = argumentTypeInfo2.TypeCode;
            result.Type = _provider.GetSZArrayType(result.ElementType);
            break;
        }
        case SerializationTypeCode.Enum:
        {
            string name = valueReader.ReadSerializedString();
            result.Type = _provider.GetTypeFromSerializedName(name);
            result.TypeCode = (SerializationTypeCode)_provider.GetUnderlyingEnumType(result.Type);
            break;
        }
        default:
            throw new BadImageFormatException();
        }
        return result;
    }
References System.Reflection.Metadata.Ecma335.CustomAttributeDecoder< TType >._provider, System.Reflection.Metadata.Ecma335.CustomAttributeDecoder< TType >.DecodeNamedArgumentType(), System.Reflection.Metadata.Ecma335.CustomAttributeDecoder< TType >.ArgumentTypeInfo.ElementType, System.Reflection.Metadata.Ecma335.CustomAttributeDecoder< TType >.ArgumentTypeInfo.Type, and System.Reflection.Metadata.Ecma335.CustomAttributeDecoder< TType >.ArgumentTypeInfo.TypeCode.
Referenced by System.Reflection.Metadata.Ecma335.CustomAttributeDecoder< TType >.DecodeArgument(), System.Reflection.Metadata.Ecma335.CustomAttributeDecoder< TType >.DecodeNamedArguments(), and System.Reflection.Metadata.Ecma335.CustomAttributeDecoder< TType >.DecodeNamedArgumentType().