Terraria: System.Reflection.Metadata.Ecma335.MethodBodyStreamEncoder.AddMethodBody
AddMethodBody() [2/4]
int System.Reflection.Metadata.Ecma335.MethodBodyStreamEncoder.AddMethodBody (InstructionEncoder instructionEncoder, int maxStack = 8, StandaloneSignatureHandle localVariablesSignature = default(StandaloneSignatureHandle), MethodBodyAttributes attributes = MethodBodyAttributes::InitLocals, bool hasDynamicStackAllocation = false) inline
Definition at line 66 of file MethodBodyStreamEncoder.cs.
    {
        if ((uint)maxStack > 65535u)
        {
            Throw.ArgumentOutOfRange("maxStack");
        }
        BlobBuilder codeBuilder = instructionEncoder.CodeBuilder;
        ControlFlowBuilder controlFlowBuilder = instructionEncoder.ControlFlowBuilder;
        if (codeBuilder == null)
        {
            Throw.ArgumentNull("instructionEncoder");
        }
        int exceptionRegionCount = controlFlowBuilder?.ExceptionHandlerCount ?? 0;
        if (!ExceptionRegionEncoder.IsExceptionRegionCountInBounds(exceptionRegionCount))
        {
            Throw.ArgumentOutOfRange("instructionEncoder", System.SR.TooManyExceptionRegions);
        }
        int result = SerializeHeader(codeBuilder.Count, (ushort)maxStack, exceptionRegionCount, attributes, localVariablesSignature, hasDynamicStackAllocation);
        if (controlFlowBuilder != null && controlFlowBuilder.BranchCount > 0)
        {
            controlFlowBuilder.CopyCodeAndFixupBranches(codeBuilder, Builder);
        }
        else
        {
            codeBuilder.WriteContentTo(Builder);
        }
        controlFlowBuilder?.SerializeExceptionTable(Builder);
        return result;
    }
References System.Reflection.Throw.ArgumentNull(), System.Reflection.Throw.ArgumentOutOfRange(), System.Reflection.Metadata.Ecma335.ControlFlowBuilder.BranchCount, System.Reflection.Metadata.Ecma335.MethodBodyStreamEncoder.Builder, System.Reflection.Metadata.Ecma335.InstructionEncoder.CodeBuilder, System.Reflection.Metadata.Ecma335.InstructionEncoder.ControlFlowBuilder, System.Reflection.Metadata.Ecma335.ControlFlowBuilder.CopyCodeAndFixupBranches(), System.Reflection.Metadata.BlobBuilder.Count, System.Reflection.Metadata.Ecma335.ControlFlowBuilder.ExceptionHandlerCount, System.Reflection.Metadata.Ecma335.ExceptionRegionEncoder.IsExceptionRegionCountInBounds(), System.Reflection.Metadata.Ecma335.ControlFlowBuilder.SerializeExceptionTable(), System.Reflection.Metadata.Ecma335.MethodBodyStreamEncoder.SerializeHeader(), System.SR.TooManyExceptionRegions, and System.Reflection.Metadata.BlobBuilder.WriteContentTo().