Terraria: System.Reflection.Metadata.Ecma335.MethodBodyStreamEncoder.SerializeHeader
SerializeHeader()
int System.Reflection.Metadata.Ecma335.MethodBodyStreamEncoder.SerializeHeader (int codeSize, ushort maxStack, int exceptionRegionCount, MethodBodyAttributes attributes, StandaloneSignatureHandle localVariablesSignature, bool hasDynamicStackAllocation) inline private
Definition at line 96 of file MethodBodyStreamEncoder.cs.
    {
        bool flag = (attributes & MethodBodyAttributes.InitLocals) != 0;
        int count;
        if (codeSize < 64 && maxStack <= 8 && localVariablesSignature.IsNil && (!hasDynamicStackAllocation || !flag) && exceptionRegionCount == 0)
        {
            count = Builder.Count;
            Builder.WriteByte((byte)((uint)(codeSize << 2) | 2u));
        }
        else
        {
            Builder.Align(4);
            count = Builder.Count;
            ushort num = 12291;
            if (exceptionRegionCount > 0)
            {
                num = (ushort)(num | 8u);
            }
            if (flag)
            {
                num = (ushort)(num | 0x10u);
            }
            Builder.WriteUInt16((ushort)((uint)attributes | (uint)num));
            Builder.WriteUInt16(maxStack);
            Builder.WriteInt32(codeSize);
            Builder.WriteInt32((!localVariablesSignature.IsNil) ? MetadataTokens.GetToken(localVariablesSignature) : 0);
        }
        return count;
    }
References System.Reflection.Metadata.BlobBuilder.Align(), System.Reflection.Metadata.Ecma335.MethodBodyStreamEncoder.Builder, System.count, System.Reflection.Metadata.BlobBuilder.Count, System.Reflection.Metadata.Ecma335.MetadataTokens.GetToken(), System.Reflection.Metadata.StandaloneSignatureHandle.IsNil, System.Reflection.Metadata.BlobBuilder.WriteByte(), System.Reflection.Metadata.BlobBuilder.WriteInt32(), and System.Reflection.Metadata.BlobBuilder.WriteUInt16().
Referenced by System.Reflection.Metadata.Ecma335.MethodBodyStreamEncoder.AddMethodBody(), and System.Reflection.Metadata.Ecma335.MethodBodyStreamEncoder.AddMethodBody().