Terraria: System.Reflection.Metadata.Ecma335.CustomAttributeDecoder.DecodeValue
DecodeValue()
CustomAttributeValue< TType > System.Reflection.Metadata.Ecma335.CustomAttributeDecoder< TType >.DecodeValue (EntityHandle constructor, BlobHandle value) inline
Definition at line 28 of file CustomAttributeDecoder.cs.
    {
        BlobHandle handle = constructor.Kind switch
        {
            HandleKind.MethodDefinition => _reader.GetMethodDefinition((MethodDefinitionHandle)constructor).Signature,
            HandleKind.MemberReference => _reader.GetMemberReference((MemberReferenceHandle)constructor).Signature,
            _ => throw new BadImageFormatException(),
        };
        BlobReader signatureReader = _reader.GetBlobReader(handle);
        BlobReader valueReader = _reader.GetBlobReader(value);
        ushort num = valueReader.ReadUInt16();
        if (num != 1)
        {
            throw new BadImageFormatException();
        }
        SignatureHeader signatureHeader = signatureReader.ReadSignatureHeader();
        if (signatureHeader.Kind != 0 || signatureHeader.IsGeneric)
        {
            throw new BadImageFormatException();
        }
        int count = signatureReader.ReadCompressedInteger();
        SignatureTypeCode signatureTypeCode = signatureReader.ReadSignatureTypeCode();
        if (signatureTypeCode != SignatureTypeCode.Void)
        {
            throw new BadImageFormatException();
        }
        ImmutableArray<CustomAttributeTypedArgument<TType>> fixedArguments = DecodeFixedArguments(ref signatureReader, ref valueReader, count);
        ImmutableArray<CustomAttributeNamedArgument<TType>> namedArguments = DecodeNamedArguments(ref valueReader);
        return new CustomAttributeValue<TType>(fixedArguments, namedArguments);
    }
References System.Reflection.Metadata.Ecma335.CustomAttributeDecoder< TType >._reader, System.count, System.Reflection.Metadata.Ecma335.CustomAttributeDecoder< TType >.DecodeFixedArguments(), System.Reflection.Metadata.Ecma335.CustomAttributeDecoder< TType >.DecodeNamedArguments(), System.Reflection.Metadata.MetadataReader.GetBlobReader(), System.Reflection.Metadata.MetadataReader.GetMemberReference(), System.Reflection.Metadata.MetadataReader.GetMethodDefinition(), System.handle, System.Reflection.Metadata.SignatureHeader.IsGeneric, System.Reflection.Metadata.SignatureHeader.Kind, System.Reflection.Metadata.BlobReader.ReadCompressedInteger(), System.Reflection.Metadata.BlobReader.ReadSignatureHeader(), System.Reflection.Metadata.BlobReader.ReadSignatureTypeCode(), System.Reflection.Metadata.BlobReader.ReadUInt16(), System.Reflection.Metadata.MemberReference.Signature, System.Reflection.Metadata.MethodDefinition.Signature, and System.value.
Referenced by System.Reflection.Metadata.CustomAttribute.DecodeValue< TType >().