Terraria: System.Reflection.Metadata.Ecma335.CustomAttributeDecoder.DecodeNamedArguments
DecodeNamedArguments()
ImmutableArray< CustomAttributeNamedArgument< TType > > System.Reflection.Metadata.Ecma335.CustomAttributeDecoder< TType >.DecodeNamedArguments (ref BlobReader valueReader) inline private
Definition at line 74 of file CustomAttributeDecoder.cs.
    {
        int num = valueReader.ReadUInt16();
        if (num == 0)
        {
            return ImmutableArray<CustomAttributeNamedArgument<TType>>.Empty;
        }
        ImmutableArray<CustomAttributeNamedArgument<TType>>.Builder builder = ImmutableArray.CreateBuilder<CustomAttributeNamedArgument<TType>>(num);
        for (int i = 0; i < num; i++)
        {
            CustomAttributeNamedArgumentKind customAttributeNamedArgumentKind = (CustomAttributeNamedArgumentKind)valueReader.ReadSerializationTypeCode();
            if (customAttributeNamedArgumentKind != CustomAttributeNamedArgumentKind.Field && customAttributeNamedArgumentKind != CustomAttributeNamedArgumentKind.Property)
            {
                throw new BadImageFormatException();
            }
            ArgumentTypeInfo info = DecodeNamedArgumentType(ref valueReader);
            string name = valueReader.ReadSerializedString();
            CustomAttributeTypedArgument<TType> customAttributeTypedArgument = DecodeArgument(ref valueReader, info);
            builder.Add(new CustomAttributeNamedArgument<TType>(name, customAttributeNamedArgumentKind, customAttributeTypedArgument.Type, customAttributeTypedArgument.Value));
        }
        return builder.MoveToImmutable();
    }
References System.Reflection.Metadata.Ecma335.CustomAttributeDecoder< TType >.DecodeArgument(), System.Reflection.Metadata.Ecma335.CustomAttributeDecoder< TType >.DecodeNamedArgumentType(), System.Collections.Immutable.ImmutableArray< T >.Empty, System.info, System.Reflection.Metadata.CustomAttributeTypedArgument< TType >.Type, and System.Reflection.Metadata.CustomAttributeTypedArgument< TType >.Value.
Referenced by System.Reflection.Metadata.Ecma335.CustomAttributeDecoder< TType >.DecodeValue().