Terraria: System.Reflection.Metadata.Ecma335.MethodBodyStreamEncoder.AddMethodBody
AddMethodBody() [4/4]
MethodBody System.Reflection.Metadata.Ecma335.MethodBodyStreamEncoder.AddMethodBody (int codeSize, int maxStack = 8, int exceptionRegionCount = 0, bool hasSmallExceptionRegions = true, StandaloneSignatureHandle localVariablesSignature = default(StandaloneSignatureHandle), MethodBodyAttributes attributes = MethodBodyAttributes::InitLocals, bool hasDynamicStackAllocation = false) inline
Definition at line 41 of file MethodBodyStreamEncoder.cs.
    {
        if (codeSize < 0)
        {
            Throw.ArgumentOutOfRange("codeSize");
        }
        if ((uint)maxStack > 65535u)
        {
            Throw.ArgumentOutOfRange("maxStack");
        }
        if (!ExceptionRegionEncoder.IsExceptionRegionCountInBounds(exceptionRegionCount))
        {
            Throw.ArgumentOutOfRange("exceptionRegionCount");
        }
        int bodyOffset = SerializeHeader(codeSize, (ushort)maxStack, exceptionRegionCount, attributes, localVariablesSignature, hasDynamicStackAllocation);
        Blob instructions = Builder.ReserveBytes(codeSize);
        ExceptionRegionEncoder exceptionRegions = ((exceptionRegionCount > 0) ? ExceptionRegionEncoder.SerializeTableHeader(Builder, exceptionRegionCount, hasSmallExceptionRegions) : default(ExceptionRegionEncoder));
        return new MethodBody(bodyOffset, instructions, exceptionRegions);
    }
References System.Reflection.Throw.ArgumentOutOfRange(), System.Reflection.Metadata.Ecma335.MethodBodyStreamEncoder.Builder, System.Reflection.Metadata.Ecma335.ExceptionRegionEncoder.IsExceptionRegionCountInBounds(), System.Reflection.Metadata.BlobBuilder.ReserveBytes(), System.Reflection.Metadata.Ecma335.MethodBodyStreamEncoder.SerializeHeader(), and System.Reflection.Metadata.Ecma335.ExceptionRegionEncoder.SerializeTableHeader().