Terraria: System.Reflection.Metadata.Ecma335.CustomAttributeDecoder.DecodeArgument
DecodeArgument()
CustomAttributeTypedArgument< TType > System.Reflection.Metadata.Ecma335.CustomAttributeDecoder< TType >.DecodeArgument (ref BlobReader valueReader, ArgumentTypeInfo info) inline private
Definition at line 202 of file CustomAttributeDecoder.cs.
    {
        if (info.TypeCode == SerializationTypeCode.TaggedObject)
        {
            info = DecodeNamedArgumentType(ref valueReader);
        }
        object value;
        switch (info.TypeCode)
        {
        case SerializationTypeCode.Boolean:
            value = valueReader.ReadBoolean();
            break;
        case SerializationTypeCode.Byte:
            value = valueReader.ReadByte();
            break;
        case SerializationTypeCode.Char:
            value = valueReader.ReadChar();
            break;
        case SerializationTypeCode.Double:
            value = valueReader.ReadDouble();
            break;
        case SerializationTypeCode.Int16:
            value = valueReader.ReadInt16();
            break;
        case SerializationTypeCode.Int32:
            value = valueReader.ReadInt32();
            break;
        case SerializationTypeCode.Int64:
            value = valueReader.ReadInt64();
            break;
        case SerializationTypeCode.SByte:
            value = valueReader.ReadSByte();
            break;
        case SerializationTypeCode.Single:
            value = valueReader.ReadSingle();
            break;
        case SerializationTypeCode.UInt16:
            value = valueReader.ReadUInt16();
            break;
        case SerializationTypeCode.UInt32:
            value = valueReader.ReadUInt32();
            break;
        case SerializationTypeCode.UInt64:
            value = valueReader.ReadUInt64();
            break;
        case SerializationTypeCode.String:
            value = valueReader.ReadSerializedString();
            break;
        case SerializationTypeCode.Type:
        {
            string name = valueReader.ReadSerializedString();
            value = _provider.GetTypeFromSerializedName(name);
            break;
        }
        case SerializationTypeCode.SZArray:
            value = DecodeArrayArgument(ref valueReader, info);
            break;
        default:
            throw new BadImageFormatException();
        }
        return new CustomAttributeTypedArgument<TType>(info.Type, value);
    }
References System.Reflection.Metadata.Ecma335.CustomAttributeDecoder< TType >._provider, System.Reflection.Metadata.Ecma335.CustomAttributeDecoder< TType >.DecodeArrayArgument(), System.Reflection.Metadata.Ecma335.CustomAttributeDecoder< TType >.DecodeNamedArgumentType(), System.info, and System.value.
Referenced by System.Reflection.Metadata.Ecma335.CustomAttributeDecoder< TType >.DecodeArrayArgument(), System.Reflection.Metadata.Ecma335.CustomAttributeDecoder< TType >.DecodeFixedArguments(), and System.Reflection.Metadata.Ecma335.CustomAttributeDecoder< TType >.DecodeNamedArguments().