Terraria: System.Xml.Xsl.XsltOld.CopyAction.Execute
Execute()
override void System.Xml.Xsl.XsltOld.CopyAction.Execute (Processor processor, ActionFrame frame) inline package
Definition at line 34 of file CopyAction.cs.
    {
        while (processor.CanContinue)
        {
            switch (frame.State)
            {
            default:
                return;
            case 0:
                if (Processor.IsRoot(frame.Node))
                {
                    processor.PushActionFrame(frame);
                    frame.State = 8;
                    return;
                }
                if (processor.CopyBeginEvent(frame.Node, _empty))
                {
                    frame.State = 5;
                    break;
                }
                return;
            case 5:
                frame.State = 6;
                if (frame.Node.NodeType == XPathNodeType.Element)
                {
                    processor.PushActionFrame(CopyNamespacesAction.GetAction(), frame.NodeSet);
                    return;
                }
                break;
            case 6:
                if (frame.Node.NodeType == XPathNodeType.Element && !_empty)
                {
                    processor.PushActionFrame(frame);
                    frame.State = 7;
                    return;
                }
                if (processor.CopyTextEvent(frame.Node))
                {
                    frame.State = 7;
                    break;
                }
                return;
            case 7:
                if (processor.CopyEndEvent(frame.Node))
                {
                    frame.Finished();
                }
                return;
            case 8:
                frame.Finished();
                return;
            case 1:
            case 2:
            case 3:
            case 4:
                return;
            }
        }
    }
References System.Xml.Xsl.XsltOld.CopyAction._empty, System.Xml.Dictionary, System.Xml.Xsl.XsltOld.ActionFrame.Finished(), System.Xml.Xsl.XsltOld.CopyNamespacesAction.GetAction(), System.Xml.Xsl.XsltOld.Processor.IsRoot(), System.Xml.Xsl.XsltOld.ActionFrame.Node, System.Xml.Xsl.XsltOld.ActionFrame.NodeSet, System.Xml.XPath.XPathNavigator.NodeType, and System.Xml.Xsl.XsltOld.ActionFrame.State.