Terraria: System.Xml.Xsl.Xslt.QilStrConcatenator.Append
Append() [2/3]
void System.Xml.Xsl.Xslt.QilStrConcatenator.Append (QilNode value) inline
Definition at line 53 of file QilStrConcatenator.cs.
    {
        if (value != null)
        {
            if (value.NodeType == QilNodeType.LiteralString)
            {
                _builder.Append((string)(QilLiteral)value);
                return;
            }
            FlushBuilder();
            _concat.Add(value);
        }
    }
References System.Xml.Xsl.Xslt.QilStrConcatenator._builder, System.Xml.Xsl.Xslt.QilStrConcatenator._concat, System.Xml.Xsl.Qil.QilNode.Add(), System.Text.StringBuilder.Append(), System.Xml.Xsl.Xslt.QilStrConcatenator.FlushBuilder(), and System.value.