Terraria: System.Xml.Xsl.Xslt.QilStrConcatenator.FlushBuilder
FlushBuilder()
void System.Xml.Xsl.Xslt.QilStrConcatenator.FlushBuilder () inline private
Definition at line 30 of file QilStrConcatenator.cs.
    {
        if (_concat == null)
        {
            _concat = _f.BaseFactory.Sequence();
        }
        if (_builder.Length != 0)
        {
            _concat.Add(_f.String(_builder.ToString()));
            _builder.Length = 0;
        }
    }
References System.Xml.Xsl.Xslt.QilStrConcatenator._builder, System.Xml.Xsl.Xslt.QilStrConcatenator._concat, System.Xml.Xsl.Xslt.QilStrConcatenator._f, System.Xml.Xsl.Qil.QilNode.Add(), System.Xml.Xsl.Qil.QilPatternFactory.BaseFactory, System.Xml.Dictionary, System.Text.StringBuilder.Length, System.Xml.Xsl.Qil.QilFactory.Sequence(), System.Xml.Xsl.Qil.QilPatternFactory.String(), and System.Text.StringBuilder.ToString().
Referenced by System.Xml.Xsl.Xslt.QilStrConcatenator.Append(), and System.Xml.Xsl.Xslt.QilStrConcatenator.ToQil().