Terraria: System.Xml.Xsl.Xslt.QilStrConcatenator.ToQil
ToQil()
QilNode System.Xml.Xsl.Xslt.QilStrConcatenator.ToQil () inline
Definition at line 67 of file QilStrConcatenator.cs.
    {
        _inUse = false;
        if (_concat == null)
        {
            return _f.String(_builder.ToString());
        }
        FlushBuilder();
        return _f.StrConcat(_concat);
    }
References System.Xml.Xsl.Xslt.QilStrConcatenator._builder, System.Xml.Xsl.Xslt.QilStrConcatenator._concat, System.Xml.Xsl.Xslt.QilStrConcatenator._f, System.Xml.Xsl.Xslt.QilStrConcatenator._inUse, System.Xml.Xsl.Xslt.QilStrConcatenator.FlushBuilder(), System.Xml.Xsl.Qil.QilPatternFactory.StrConcat(), System.Xml.Xsl.Qil.QilPatternFactory.String(), and System.Text.StringBuilder.ToString().
Referenced by System.Xml.Xsl.Xslt.QilGenerator.CompileSort().