Terraria: MS.Internal.Xml.XPath.SortQuery.BuildResultsList
BuildResultsList()
void MS.Internal.Xml.XPath.SortQuery.BuildResultsList () inline private
Definition at line 68 of file SortQuery.cs.
    {
        int numSorts = _comparer.NumSorts;
        XPathNavigator xPathNavigator;
        while ((xPathNavigator = _qyInput.Advance()) != null)
        {
            SortKey sortKey = new SortKey(numSorts, _results.Count, xPathNavigator.Clone());
            for (int i = 0; i < numSorts; i++)
            {
                sortKey[i] = _comparer.Expression(i).Evaluate(_qyInput);
            }
            _results.Add(sortKey);
        }
        _results.Sort(_comparer);
    }
References MS.Internal.Xml.XPath.SortQuery._comparer, MS.Internal.Xml.XPath.SortQuery._qyInput, MS.Internal.Xml.XPath.SortQuery._results, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), MS.Internal.Xml.XPath.Query.Advance(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, MS.Internal.Xml.XPath.Query.Evaluate(), MS.Internal.Xml.XPath.XPathSortComparer.Expression(), and MS.Internal.Xml.XPath.XPathSortComparer.NumSorts.
Referenced by MS.Internal.Xml.XPath.SortQuery.Evaluate().