Terraria: Microsoft.Win32.SafeHandles.SafeLocalAllocHandle.LocalAlloc
LocalAlloc() [1/3]
static Microsoft.Win32.SafeHandles.SafeLocalAllocHandle Microsoft.Win32.SafeHandles.SafeLocalAllocHandle.LocalAlloc (int cb) inline static package
Definition at line 14 of file SafeLocalAllocHandle.cs.
    {
        Microsoft.Win32.SafeHandles.SafeLocalAllocHandle safeLocalAllocHandle = new Microsoft.Win32.SafeHandles.SafeLocalAllocHandle();
        safeLocalAllocHandle.SetHandle(Marshal.AllocHGlobal(cb));
        safeLocalAllocHandle.Initialize((ulong)cb);
        return safeLocalAllocHandle;
    }
References System.Runtime.InteropServices.Marshal.AllocHGlobal(), System.Runtime.InteropServices.SafeBuffer.Initialize(), and System.Runtime.InteropServices.SafeHandle.SetHandle().
Referenced by System.Security.Principal.WindowsIdentity.WindowsIdentity(), System.Net.NetworkInformation.Ping.DoSendPingCore(), System.Security.Principal.WindowsIdentity.GetTokenInformation(), System.Net.NetworkInformation.Ping.SetUnmanagedStructures(), and System.Net.HttpResponseStream.WriteCore().