Terraria: MS.Internal.Xml.XPath.SortQuery.Evaluate
Evaluate()
override object MS.Internal.Xml.XPath.SortQuery.Evaluate (XPathNodeIterator context) inline
Definition at line 84 of file SortQuery.cs.
    {
        _qyInput.Evaluate(context);
        _results.Clear();
        BuildResultsList();
        count = 0;
        return this;
    }
References MS.Internal.Xml.XPath.SortQuery._qyInput, MS.Internal.Xml.XPath.SortQuery._results, MS.Internal.Xml.XPath.SortQuery.BuildResultsList(), System.Collections.Generic.Dictionary< TKey, TValue >.Clear(), System.Xml.XPath.XPathNodeIterator.count, and MS.Internal.Xml.XPath.Query.Evaluate().