Terraria: Terraria.GameContent.RGB.SurfaceBiomeShader.ProcessHighDetail
ProcessHighDetail()
void Terraria.GameContent.RGB.SurfaceBiomeShader.ProcessHighDetail (RgbDevice device, Fragment fragment, EffectDetailLevel quality, float time) inline private
Definition at line 57 of file SurfaceBiomeShader.cs.
    {
        Vector4 value = _primaryColor * _surfaceColor;
        Vector4 value2 = _secondaryColor * _surfaceColor;
        for (int i = 0; i < fragment.Count; i++)
        {
            Vector2 canvasPositionOfIndex = fragment.GetCanvasPositionOfIndex(i);
            Point gridPositionOfIndex = fragment.GetGridPositionOfIndex(i);
            float amount = (float)Math.Sin(canvasPositionOfIndex.X * 1.5f + canvasPositionOfIndex.Y + time) * 0.5f + 0.5f;
            Vector4 value3 = Vector4.Lerp(value, value2, amount);
            float dynamicNoise = NoiseHelper.GetDynamicNoise(gridPositionOfIndex.X, gridPositionOfIndex.Y, time / 60f);
            dynamicNoise = Math.Max(0f, 1f - dynamicNoise * 20f);
            dynamicNoise *= 1f - _surfaceColor.X;
            value3 = Vector4.Max(value3, new Vector4(dynamicNoise * _starVisibility));
            fragment.SetColor(i, value3);
        }
    }
References Terraria.GameContent.RGB.SurfaceBiomeShader._primaryColor, Terraria.GameContent.RGB.SurfaceBiomeShader._secondaryColor, Terraria.GameContent.RGB.SurfaceBiomeShader._starVisibility, Terraria.GameContent.RGB.SurfaceBiomeShader._surfaceColor, ReLogic.Peripherals.RGB.Fragment.Count, ReLogic.Peripherals.RGB.Fragment.GetCanvasPositionOfIndex(), Terraria.GameContent.RGB.NoiseHelper.GetDynamicNoise(), ReLogic.Peripherals.RGB.Fragment.GetGridPositionOfIndex(), Microsoft.Xna.Framework.Vector4.Lerp(), System.Math.Max(), Microsoft.Xna.Framework.Vector4.Max(), ReLogic.Peripherals.RGB.Fragment.SetColor(), System.Math.Sin(), System.value, Microsoft.Xna.Framework.Point.X, Microsoft.Xna.Framework.Vector2.X, Microsoft.Xna.Framework.Vector4.X, Microsoft.Xna.Framework.Point.Y, and Microsoft.Xna.Framework.Vector2.Y.