Terraria: System.IO.Strategies.Net5CompatFileStreamStrategy.CompletionSource.SetCompletedSynchronously
SetCompletedSynchronously()
void System.IO.Strategies.Net5CompatFileStreamStrategy.CompletionSource.SetCompletedSynchronously (int numBytes) inline inherited
Definition at line 38 of file Net5CompatFileStreamStrategy.cs.
        {
            ReleaseNativeResource();
            TrySetResult(numBytes + _numBufferedBytes);
        }
References System.IO.Strategies.Net5CompatFileStreamStrategy.CompletionSource._numBufferedBytes, System.IO.Strategies.Net5CompatFileStreamStrategy.CompletionSource.ReleaseNativeResource(), and System.Threading.Tasks.TaskCompletionSource< int >.TrySetResult().
Referenced by System.IO.Strategies.Net5CompatFileStreamStrategy.ReadNativeAsync(), and System.IO.Strategies.Net5CompatFileStreamStrategy.WriteAsyncInternalCore().