Terraria: System.IO.Strategies.Net5CompatFileStreamStrategy.CompletionSource.Cancel
Cancel()
static unsafe void System.IO.Strategies.Net5CompatFileStreamStrategy.CompletionSource.Cancel (object state) inline static private inherited
Definition at line 115 of file Net5CompatFileStreamStrategy.cs.
        {
            CompletionSource completionSource = (CompletionSource)state;
            if (!completionSource._strategy._fileHandle.IsInvalid && !Interop.Kernel32.CancelIoEx(completionSource._strategy._fileHandle, completionSource._overlapped))
            {
                int lastPInvokeError = Marshal.GetLastPInvokeError();
                if (lastPInvokeError != 1168)
                {
                    throw Win32Marshal.GetExceptionForWin32Error(lastPInvokeError);
                }
            }
        }
References System.IO.Strategies.Net5CompatFileStreamStrategy.CompletionSource.CompletionSource(), System.IO.Strategies.Net5CompatFileStreamStrategy._fileHandle, System.IO.Strategies.Net5CompatFileStreamStrategy.CompletionSource._overlapped, System.IO.Strategies.Net5CompatFileStreamStrategy.CompletionSource._strategy, Interop.Kernel32.CancelIoEx(), System.IO.Win32Marshal.GetExceptionForWin32Error(), System.Runtime.InteropServices.Marshal.GetLastPInvokeError(), Microsoft.Win32.SafeHandles.SafeHandleZeroOrMinusOneIsInvalid.IsInvalid, and System.state.