Terraria: System.IO.Strategies.Net5CompatFileStreamStrategy.CompletionSource.CompletionSource
CompletionSource()
unsafe System.IO.Strategies.Net5CompatFileStreamStrategy.CompletionSource.CompletionSource (Net5CompatFileStreamStrategy strategy, PreAllocatedOverlapped preallocatedOverlapped, int numBufferedBytes, byte[] bytes) inline package
Definition at line 29 of file Net5CompatFileStreamStrategy.cs.
            : base(TaskCreationOptions.RunContinuationsAsynchronously)
        {
            _numBufferedBytes = numBufferedBytes;
            _strategy = strategy;
            _result = 0L;
            _overlapped = ((bytes != null && strategy.CompareExchangeCurrentOverlappedOwner(this, null) == null) ? strategy._fileHandle.ThreadPoolBinding.AllocateNativeOverlapped(preallocatedOverlapped) : strategy._fileHandle.ThreadPoolBinding.AllocateNativeOverlapped(s_ioCallback, this, bytes));
        }
References System.IO.Strategies.Net5CompatFileStreamStrategy._fileHandle, System.IO.Strategies.Net5CompatFileStreamStrategy.CompletionSource._numBufferedBytes, System.IO.Strategies.Net5CompatFileStreamStrategy.CompletionSource._overlapped, System.IO.Strategies.Net5CompatFileStreamStrategy.CompletionSource._result, System.IO.Strategies.Net5CompatFileStreamStrategy.CompletionSource._strategy, System.Threading.ThreadPoolBoundHandle.AllocateNativeOverlapped(), System.bytes, System.IO.Strategies.Net5CompatFileStreamStrategy.CompareExchangeCurrentOverlappedOwner(), System.L, System.IO.Strategies.Net5CompatFileStreamStrategy.CompletionSource.s_ioCallback, and Microsoft.Win32.SafeHandles.SafeFileHandle.ThreadPoolBinding.
Referenced by System.IO.Strategies.Net5CompatFileStreamStrategy.CompletionSource.Cancel(), System.IO.Strategies.Net5CompatFileStreamStrategy.CompletionSource.Create(), and System.IO.Strategies.Net5CompatFileStreamStrategy.CompletionSource.IOCallback().