Terraria: System.IO.Strategies.Net5CompatFileStreamStrategy.CompletionSource.CompleteCallback
CompleteCallback()
void System.IO.Strategies.Net5CompatFileStreamStrategy.CompletionSource.CompleteCallback (ulong packedResult) inline private inherited
Definition at line 92 of file Net5CompatFileStreamStrategy.cs.
        {
            CancellationToken token = _cancellationRegistration.Token;
            ReleaseNativeResource();
            long num = (long)packedResult & -4294967296L;
            if (num == 8589934592L)
            {
                int num2 = (int)(packedResult & 0xFFFFFFFFu);
                if (num2 == 995)
                {
                    TrySetCanceled(token.IsCancellationRequested ? token : new CancellationToken(canceled: true));
                    return;
                }
                Exception exceptionForWin32Error = Win32Marshal.GetExceptionForWin32Error(num2);
                exceptionForWin32Error.SetCurrentStackTrace();
                TrySetException(exceptionForWin32Error);
            }
            else
            {
                TrySetResult((int)(packedResult & 0xFFFFFFFFu) + _numBufferedBytes);
            }
        }
References System.IO.Strategies.Net5CompatFileStreamStrategy.CompletionSource._cancellationRegistration, System.IO.Strategies.Net5CompatFileStreamStrategy.CompletionSource._numBufferedBytes, System.IO.Win32Marshal.GetExceptionForWin32Error(), System.Threading.CancellationToken.IsCancellationRequested, System.L, System.IO.Strategies.Net5CompatFileStreamStrategy.CompletionSource.ReleaseNativeResource(), System.Exception.SetCurrentStackTrace(), System.Threading.CancellationTokenRegistration.Token, System.Threading.Tasks.TaskCompletionSource< int >.TrySetCanceled(), System.Threading.Tasks.TaskCompletionSource< int >.TrySetException(), and System.Threading.Tasks.TaskCompletionSource< int >.TrySetResult().
Referenced by System.IO.Strategies.Net5CompatFileStreamStrategy.CompletionSource.IOCallback(), and System.IO.Strategies.Net5CompatFileStreamStrategy.CompletionSource.RegisterForCancellation().