Terraria: System.IO.Strategies.Net5CompatFileStreamStrategy.CompletionSource.ReleaseNativeResource
ReleaseNativeResource()
virtual unsafe void System.IO.Strategies.Net5CompatFileStreamStrategy.CompletionSource.ReleaseNativeResource () inline package virtual
Reimplemented in System.IO.Strategies.Net5CompatFileStreamStrategy.MemoryFileStreamCompletionSource.
Definition at line 69 of file Net5CompatFileStreamStrategy.cs.
        {
            _cancellationRegistration.Dispose();
            if (_overlapped != null)
            {
                _strategy._fileHandle.ThreadPoolBinding.FreeNativeOverlapped(_overlapped);
                _overlapped = null;
            }
            _strategy.CompareExchangeCurrentOverlappedOwner(null, this);
        }
References System.IO.Strategies.Net5CompatFileStreamStrategy.CompletionSource._cancellationRegistration, System.IO.Strategies.Net5CompatFileStreamStrategy._fileHandle, System.IO.Strategies.Net5CompatFileStreamStrategy.CompletionSource._overlapped, System.IO.Strategies.Net5CompatFileStreamStrategy.CompletionSource._strategy, System.IO.Strategies.Net5CompatFileStreamStrategy.CompareExchangeCurrentOverlappedOwner(), System.Threading.CancellationTokenRegistration.Dispose(), System.Threading.ThreadPoolBoundHandle.FreeNativeOverlapped(), and Microsoft.Win32.SafeHandles.SafeFileHandle.ThreadPoolBinding.
Referenced by System.IO.Strategies.Net5CompatFileStreamStrategy.CompletionSource.CompleteCallback(), System.IO.Strategies.Net5CompatFileStreamStrategy.ReadNativeAsync(), System.IO.Strategies.Net5CompatFileStreamStrategy.CompletionSource.SetCompletedSynchronously(), and System.IO.Strategies.Net5CompatFileStreamStrategy.WriteAsyncInternalCore().