Terraria: System.IO.Strategies.Net5CompatFileStreamStrategy.CompletionSource.RegisterForCancellation
RegisterForCancellation()
unsafe void System.IO.Strategies.Net5CompatFileStreamStrategy.CompletionSource.RegisterForCancellation (CancellationToken cancellationToken) inline inherited
Definition at line 44 of file Net5CompatFileStreamStrategy.cs.
        {
            if (_overlapped != null)
            {
                Action<object> callback = Cancel;
                long num = Interlocked.CompareExchange(ref _result, 17179869184L, 0L);
                switch (num)
                {
                case 0L:
                    _cancellationRegistration = cancellationToken.UnsafeRegister(callback, this);
                    num = Interlocked.Exchange(ref _result, 0L);
                    break;
                default:
                    num = Interlocked.Exchange(ref _result, 0L);
                    break;
                case 34359738368L:
                    break;
                }
                if (num != 0L && num != 34359738368L && num != 17179869184L)
                {
                    CompleteCallback((ulong)num);
                }
            }
        }
References System.IO.Strategies.Net5CompatFileStreamStrategy.CompletionSource._cancellationRegistration, System.IO.Strategies.Net5CompatFileStreamStrategy.CompletionSource._overlapped, System.IO.Strategies.Net5CompatFileStreamStrategy.CompletionSource._result, System.Threading.Tasks.Cancel, System.cancellationToken, System.Threading.Interlocked.CompareExchange(), System.IO.Strategies.Net5CompatFileStreamStrategy.CompletionSource.CompleteCallback(), System.Threading.Interlocked.Exchange(), and System.L.
Referenced by System.IO.Strategies.Net5CompatFileStreamStrategy.ReadNativeAsync(), and System.IO.Strategies.Net5CompatFileStreamStrategy.WriteAsyncInternalCore().