Terraria: System.IO.Strategies.Net5CompatFileStreamStrategy.CompletionSource.IOCallback
IOCallback()
static unsafe void System.IO.Strategies.Net5CompatFileStreamStrategy.CompletionSource.IOCallback (uint errorCode, uint numBytes, NativeOverlapped * pOverlapped) inline static package inherited
Definition at line 80 of file Net5CompatFileStreamStrategy.cs.
        {
            object nativeOverlappedState = ThreadPoolBoundHandle.GetNativeOverlappedState(pOverlapped);
            CompletionSource completionSource = ((!(nativeOverlappedState is Net5CompatFileStreamStrategy net5CompatFileStreamStrategy)) ? ((CompletionSource)nativeOverlappedState) : net5CompatFileStreamStrategy._currentOverlappedOwner);
            CompletionSource completionSource2 = completionSource;
            ulong num = ((errorCode == 0 || errorCode == 109 || errorCode == 232) ? (0x100000000uL | numBytes) : (0x200000000uL | errorCode));
            if (Interlocked.Exchange(ref completionSource2._result, (long)num) == 0L && Interlocked.Exchange(ref completionSource2._result, 34359738368L) != 0L)
            {
                completionSource2.CompleteCallback(num);
            }
        }
References System.IO.Strategies.Net5CompatFileStreamStrategy.CompletionSource.CompletionSource(), System.IO.Strategies.Net5CompatFileStreamStrategy.CompletionSource._result, System.IO.Strategies.Net5CompatFileStreamStrategy.CompletionSource.CompleteCallback(), System.Threading.Interlocked.Exchange(), System.Threading.ThreadPoolBoundHandle.GetNativeOverlappedState(), and System.L.