Terraria: System.Reflection.Metadata.Ecma335.PortablePdbBuilder.ValidateTypeSystemRowCounts
ValidateTypeSystemRowCounts()
static void System.Reflection.Metadata.Ecma335.PortablePdbBuilder.ValidateTypeSystemRowCounts (ImmutableArray< int > typeSystemRowCounts) inline static private
Definition at line 35 of file PortablePdbBuilder.cs.
    {
        if (typeSystemRowCounts.IsDefault)
        {
            Throw.ArgumentNull("typeSystemRowCounts");
        }
        if (typeSystemRowCounts.Length != MetadataTokens.TableCount)
        {
            throw new ArgumentException(System.SR.Format(System.SR.ExpectedArrayOfSize, MetadataTokens.TableCount), "typeSystemRowCounts");
        }
        for (int i = 0; i < typeSystemRowCounts.Length; i++)
        {
            if (typeSystemRowCounts[i] != 0)
            {
                if (((uint)typeSystemRowCounts[i] & 0xFF000000u) != 0)
                {
                    throw new ArgumentOutOfRangeException("typeSystemRowCounts", System.SR.Format(System.SR.RowCountOutOfRange, i));
                }
                if (((1L << i) & 0x1FC93FB7FF57L) == 0L)
                {
                    throw new ArgumentException(System.SR.Format(System.SR.RowCountMustBeZero, i), "typeSystemRowCounts");
                }
            }
        }
    }
References System.Reflection.Throw.ArgumentNull(), System.SR.ExpectedArrayOfSize, System.SR.Format(), System.L, System.SR.RowCountMustBeZero, System.SR.RowCountOutOfRange, and System.Reflection.Metadata.Ecma335.MetadataTokens.TableCount.
Referenced by System.Reflection.Metadata.Ecma335.PortablePdbBuilder.PortablePdbBuilder().