Terraria: System.Reflection.Metadata.Ecma335.PortablePdbBuilder.PortablePdbBuilder
PortablePdbBuilder()
System.Reflection.Metadata.Ecma335.PortablePdbBuilder.PortablePdbBuilder (MetadataBuilder tablesAndHeaps, ImmutableArray< int > typeSystemRowCounts, MethodDefinitionHandle entryPoint, Func< IEnumerable< Blob >, BlobContentId >? idProvider = null) inline
Definition at line 22 of file PortablePdbBuilder.cs.
    {
        if (tablesAndHeaps == null)
        {
            Throw.ArgumentNull("tablesAndHeaps");
        }
        ValidateTypeSystemRowCounts(typeSystemRowCounts);
        _builder = tablesAndHeaps;
        _entryPoint = entryPoint;
        _serializedMetadata = tablesAndHeaps.GetSerializedMetadata(typeSystemRowCounts, MetadataVersion.Length, isStandaloneDebugMetadata: true);
        IdProvider = idProvider ?? BlobContentId.GetTimeBasedProvider();
    }
References System.Reflection.Metadata.Ecma335.PortablePdbBuilder._builder, System.Reflection.Metadata.Ecma335.PortablePdbBuilder._entryPoint, System.Reflection.Metadata.Ecma335.PortablePdbBuilder._serializedMetadata, System.Reflection.Throw.ArgumentNull(), System.Reflection.Metadata.BlobContentId.GetTimeBasedProvider(), System.Reflection.Metadata.Ecma335.PortablePdbBuilder.IdProvider, System.Reflection.Metadata.Ecma335.PortablePdbBuilder.MetadataVersion, and System.Reflection.Metadata.Ecma335.PortablePdbBuilder.ValidateTypeSystemRowCounts().