Terraria: System.Security.Cryptography.X509Certificates.RSAPssX509SignatureGenerator.GetSignatureAlgorithmIdentifier
GetSignatureAlgorithmIdentifier()
override byte[] System.Security.Cryptography.X509Certificates.RSAPssX509SignatureGenerator.GetSignatureAlgorithmIdentifier (HashAlgorithmName hashAlgorithm) inline
Definition at line 18 of file RSAPssX509SignatureGenerator.cs.
    {
        if (_padding != RSASignaturePadding.Pss)
        {
            throw new CryptographicException(System.SR.Cryptography_InvalidPaddingMode);
        }
        int saltLength;
        string text;
        if (hashAlgorithm == HashAlgorithmName.SHA256)
        {
            saltLength = 32;
            text = "2.16.840.1.101.3.4.2.1";
        }
        else if (hashAlgorithm == HashAlgorithmName.SHA384)
        {
            saltLength = 48;
            text = "2.16.840.1.101.3.4.2.2";
        }
        else
        {
            if (!(hashAlgorithm == HashAlgorithmName.SHA512))
            {
                throw new ArgumentOutOfRangeException("hashAlgorithm", hashAlgorithm, System.SR.Format(System.SR.Cryptography_UnknownHashAlgorithm, hashAlgorithm.Name));
            }
            saltLength = 64;
            text = "2.16.840.1.101.3.4.2.3";
        }
        PssParamsAsn pssParamsAsn = default(PssParamsAsn);
        pssParamsAsn.HashAlgorithm = new System.Security.Cryptography.Asn1.AlgorithmIdentifierAsn
        {
            Algorithm = text
        };
        pssParamsAsn.MaskGenAlgorithm = new System.Security.Cryptography.Asn1.AlgorithmIdentifierAsn
        {
            Algorithm = "1.2.840.113549.1.1.8"
        };
        pssParamsAsn.SaltLength = saltLength;
        pssParamsAsn.TrailerField = 1;
        PssParamsAsn pssParamsAsn2 = pssParamsAsn;
        AsnWriter asnWriter = new AsnWriter(AsnEncodingRules.DER);
        using (asnWriter.PushSequence())
        {
            asnWriter.WriteObjectIdentifierForCrypto(text);
        }
        pssParamsAsn2.MaskGenAlgorithm.Parameters = asnWriter.Encode();
        asnWriter.Reset();
        pssParamsAsn2.Encode(asnWriter);
        System.Security.Cryptography.Asn1.AlgorithmIdentifierAsn algorithmIdentifierAsn = default(System.Security.Cryptography.Asn1.AlgorithmIdentifierAsn);
        algorithmIdentifierAsn.Algorithm = "1.2.840.113549.1.1.10";
        algorithmIdentifierAsn.Parameters = asnWriter.Encode();
        System.Security.Cryptography.Asn1.AlgorithmIdentifierAsn algorithmIdentifierAsn2 = algorithmIdentifierAsn;
        asnWriter.Reset();
        algorithmIdentifierAsn2.Encode(asnWriter);
        return asnWriter.Encode();
    }
References System.Security.Cryptography.X509Certificates.RSAPssX509SignatureGenerator._padding, System.SR.Cryptography_InvalidPaddingMode, System.SR.Cryptography_UnknownHashAlgorithm, System.Security.Cryptography.Asn1.AlgorithmIdentifierAsn.Encode(), System.Security.Cryptography.Asn1.PssParamsAsn.Encode(), System.Formats.Asn1.AsnWriter.Encode(), System.SR.Format(), System.Security.Cryptography.HashAlgorithmName.Name, System.Security.Cryptography.RSASignaturePadding.Pss, System.Formats.Asn1.AsnWriter.PushSequence(), System.Formats.Asn1.AsnWriter.Reset(), System.Security.Cryptography.HashAlgorithmName.SHA256, System.Security.Cryptography.HashAlgorithmName.SHA384, System.Security.Cryptography.HashAlgorithmName.SHA512, and System.text.