Terraria: System.Reflection.Metadata.Ecma335.PortablePdbBuilder.SerializeStandalonePdbStream
SerializeStandalonePdbStream()
void System.Reflection.Metadata.Ecma335.PortablePdbBuilder.SerializeStandalonePdbStream (BlobBuilder builder) inline private
Definition at line 61 of file PortablePdbBuilder.cs.
    {
        int count = builder.Count;
        _pdbIdBlob = builder.ReserveBytes(20);
        builder.WriteInt32((!_entryPoint.IsNil) ? MetadataTokens.GetToken(_entryPoint) : 0);
        builder.WriteUInt64(_serializedMetadata.Sizes.ExternalTablesMask);
        MetadataWriterUtilities.SerializeRowCounts(builder, _serializedMetadata.Sizes.ExternalRowCounts);
        int count2 = builder.Count;
    }
References System.Reflection.Metadata.Ecma335.PortablePdbBuilder._entryPoint, System.Reflection.Metadata.Ecma335.PortablePdbBuilder._pdbIdBlob, System.Reflection.Metadata.Ecma335.PortablePdbBuilder._serializedMetadata, System.count, System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Reflection.Metadata.Ecma335.MetadataSizes.ExternalRowCounts, System.Reflection.Metadata.Ecma335.MetadataSizes.ExternalTablesMask, System.Reflection.Metadata.Ecma335.MetadataTokens.GetToken(), System.Reflection.Metadata.MethodDefinitionHandle.IsNil, System.Reflection.Metadata.Ecma335.MetadataWriterUtilities.SerializeRowCounts(), and System.Reflection.Metadata.Ecma335.SerializedMetadata.Sizes.
Referenced by System.Reflection.Metadata.Ecma335.PortablePdbBuilder.Serialize().