Terraria: Terraria.Graphics.Renderers.ItemTransferParticle.Prepare
Prepare()
void Terraria.Graphics.Renderers.ItemTransferParticle.Prepare (int itemType, int lifeTimeTotal, Vector2 playerPosition, Vector2 chestPosition) inline
Definition at line 40 of file ItemTransferParticle.cs.
    {
        _itemInstance.SetDefaults(itemType);
        _lifeTimeTotal = lifeTimeTotal;
        StartPosition = playerPosition;
        EndPosition = chestPosition;
        Vector2 vector = (EndPosition - StartPosition).SafeNormalize(Vector2.UnitY).RotatedBy(1.5707963705062866);
        bool num = vector.Y < 0f;
        bool flag = vector.Y == 0f;
        if (!num || (flag && Main.rand.Next(2) == 0))
        {
            vector *= -1f;
        }
        vector = new Vector2(0f, -1f);
        float num2 = Vector2.Distance(EndPosition, StartPosition);
        BezierHelper1 = vector * num2 + Main.rand.NextVector2Circular(32f, 32f);
        BezierHelper2 = -vector * num2 + Main.rand.NextVector2Circular(32f, 32f);
    }
References Terraria.Graphics.Renderers.ItemTransferParticle._itemInstance, Terraria.Graphics.Renderers.ItemTransferParticle._lifeTimeTotal, Terraria.Graphics.Renderers.ItemTransferParticle.BezierHelper1, Terraria.Graphics.Renderers.ItemTransferParticle.BezierHelper2, Microsoft.Xna.Framework.Vector2.Distance(), Terraria.Graphics.Renderers.ItemTransferParticle.EndPosition, Terraria.Main.rand, Terraria.Item.SetDefaults(), Terraria.Graphics.Renderers.ItemTransferParticle.StartPosition, Microsoft.Xna.Framework.Vector2.UnitY, and Microsoft.Xna.Framework.Graphics.Vector2.
Referenced by Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_ItemTransfer().