Terraria: System.Security.Cryptography.DSASignatureFormatHelpers.CreateUnknownValueException
CreateUnknownValueException()
static Exception System.Security.Cryptography.DSASignatureFormatHelpers.CreateUnknownValueException (DSASignatureFormat signatureFormat) inline static package
Definition at line 14 of file DSASignatureFormatHelpers.cs.
    {
        return new ArgumentOutOfRangeException("signatureFormat", System.SR.Format(System.SR.Cryptography_UnknownSignatureFormat, signatureFormat));
    }
References System.SR.Cryptography_UnknownSignatureFormat, and System.SR.Format().
Referenced by System.Security.Cryptography.DSA.CreateSignature(), System.Security.Cryptography.DSA.SignData(), System.Security.Cryptography.ECDsa.SignData(), System.Security.Cryptography.DSA.SignData(), System.Security.Cryptography.ECDsa.SignData(), System.Security.Cryptography.DSA.SignData(), System.Security.Cryptography.ECDsa.SignData(), System.Security.Cryptography.ECDsa.SignHash(), System.Security.Cryptography.DSA.TryCreateSignature(), System.Security.Cryptography.DSA.TrySignData(), System.Security.Cryptography.ECDsa.TrySignData(), System.Security.Cryptography.ECDsa.TrySignHash(), System.Security.Cryptography.DSA.VerifyData(), System.Security.Cryptography.ECDsa.VerifyData(), System.Security.Cryptography.DSA.VerifyData(), System.Security.Cryptography.ECDsa.VerifyData(), System.Security.Cryptography.DSA.VerifyData(), System.Security.Cryptography.ECDsa.VerifyData(), System.Security.Cryptography.DSA.VerifyData(), System.Security.Cryptography.ECDsa.VerifyData(), System.Security.Cryptography.ECDsa.VerifyHash(), System.Security.Cryptography.ECDsa.VerifyHash(), System.Security.Cryptography.DSA.VerifySignature(), and System.Security.Cryptography.DSA.VerifySignature().