Terraria: System.Net.HttpListenerContext.GetKnownMethod
GetKnownMethod()
global.Interop.HttpApi.HTTP_VERB System.Net.HttpListenerContext.GetKnownMethod () inline package
Definition at line 140 of file HttpListenerContext.cs.
    {
        if (System.Net.NetEventSource.Log.IsEnabled())
        {
            System.Net.NetEventSource.Info(this, FormattableStringFactory.Create("Visited {0}()", "GetKnownMethod"), "GetKnownMethod");
        }
        return global::Interop.HttpApi.GetKnownVerb(Request.RequestBuffer, Request.OriginalBlobAddress);
    }
References System.Runtime.CompilerServices.FormattableStringFactory.Create(), System.Net.NetEventSource.Info(), System.Net.NetEventSource.Log, System.Net.HttpListenerRequest.OriginalBlobAddress, System.Net.HttpListenerContext.Request, and System.Net.HttpListenerRequest.RequestBuffer.
Referenced by System.Net.HttpResponseStream.ComputeLeftToWrite().