Terraria: System.Net.HttpListenerContext.Abort
Abort()
void System.Net.HttpListenerContext.Abort () inline package
Definition at line 127 of file HttpListenerContext.cs.
    {
        ForceCancelRequest(RequestQueueHandle, Request.RequestId);
        try
        {
            Request.Close();
        }
        finally
        {
            (_user?.Identity as IDisposable)?.Dispose();
        }
    }
References System.Net.HttpListenerContext._user, System.Net.HttpListenerRequest.Close(), System.Net.HttpListenerContext.ForceCancelRequest(), System.Security.Principal.IPrincipal.Identity, System.Net.HttpListenerContext.Request, System.Net.HttpListenerRequest.RequestId, and System.Net.HttpListenerContext.RequestQueueHandle.
Referenced by System.Net.HttpListenerResponse.Abort(), System.Net.HttpResponseStream.BeginWriteCore(), System.Net.HttpResponseStream.DisposeCore(), System.Net.HttpResponseStream.EndWriteCore(), System.Net.WebSockets.WebSocketHttpListenerDuplexStream.ReadAsyncFast(), System.Net.WebSockets.WebSocketHttpListenerDuplexStream.WriteAsyncFast(), and System.Net.HttpResponseStream.WriteCore().