Terraria: System.Net.HttpListenerContext.Close
Close()
void System.Net.HttpListenerContext.Close () inline package
Definition at line 104 of file HttpListenerContext.cs.
    {
        try
        {
            _response?.Close();
        }
        finally
        {
            try
            {
                Request.Close();
            }
            finally
            {
                IDisposable disposable = ((_user == null) ? null : (_user.Identity as IDisposable));
                if (disposable != null && _user.Identity.AuthenticationType != "NTLM" && !_listener.UnsafeConnectionNtlmAuthentication)
                {
                    disposable.Dispose();
                }
            }
        }
    }
References System.Net.HttpListenerContext._listener, System.Net.HttpListenerContext._response, System.Net.HttpListenerContext._user, System.Security.Principal.IIdentity.AuthenticationType, System.Net.HttpListenerRequest.Close(), System.Net.HttpListenerResponse.Close(), System.IDisposable.Dispose(), System.Security.Principal.IPrincipal.Identity, System.Net.HttpListenerContext.Request, and System.Net.HttpListener.UnsafeConnectionNtlmAuthentication.
Referenced by System.Net.HttpListenerResponse.Close(), System.Net.HttpListenerResponse.Dispose(), and System.Net.HttpListenerResponse.NonBlockingCloseCallback().