Terraria: TrackedProjectileReference.Set
Set()
void TrackedProjectileReference.Set (Projectile proj) inline
     {
         ProjectileLocalIndex = proj.whoAmI;
         ProjectileOwnerIndex = proj.owner;
         ProjectileIdentity = proj.identity;
         ProjectileType = proj.type;
         IsTrackingSomething = true;
     }
References Projectile.identity, IsTrackingSomething, Projectile.owner, ProjectileIdentity, ProjectileLocalIndex, ProjectileOwnerIndex, ProjectileType, Projectile.type, and Entity.whoAmI.
Referenced by Main.TryInteractingWithMoneyTrough(), Main.TryInteractingWithMoneyTrough2(), Main.TryInteractingWithVoidLens(), and TryReading().