Terraria: SlotVector.Add
Add()
SlotId SlotVector< T >.Add (T value) inline
     {
         if (_freeHead == 65535)
         {
             return new SlotId(65535u);
         }
         uint freeHead = _freeHead;
         ItemPair itemPair = _array[freeHead];
         if (_freeHead >= _usedSpaceLength)
         {
             _usedSpaceLength = _freeHead + 1;
         }
         _freeHead = itemPair.Id.Index;
         _array[freeHead] = new ItemPair(value, itemPair.Id.ToActive(freeHead));
         Count++;
         return _array[freeHead].Id;
     }
References SlotVector< T >._array, SlotVector< T >._freeHead, SlotVector< T >._usedSpaceLength, SlotVector< T >.Count, SlotVector< T >.ItemPair.Id, SlotId.Index, and SlotId.ToActive().
Referenced by SoundPlayer.Play(), and SoundPlayer.PlayLooped().