Terraria: WeGameHelper.WriteDebugString
WriteDebugString()
static void WeGameHelper.WriteDebugString (string format, params object[] args) inline static
Referenced by NetServerSocialModule.AcceptAnUserSession(), IPCBase.BeginReadData(), NetClientSocialModule.CheckParameters(), NetClientSocialModule.Close(), NetServerSocialModule.CloseAndUpdateUserState(), IPCServer.ConnectionCallback(), NetClientSocialModule.ConnectToLobby(), IPCServer.ContinueReadOrWait(), NetSocialModule.GetSessionState(), FriendsSocialModule.GetUsername(), Lobby.Join(), NetClientSocialModule.JoinServer(), NetClientSocialModule.LaunchLocalServer(), SocialAPI.LoadSteam(), SocialAPI.LoadWeGame(), NetClientSocialModule.OnAuthSuccess(), NetServerSocialModule.OnConnected(), NetServerSocialModule.OnCreateSessionFailed(), NetServerSocialModule.OnCreateSessionRequest(), NetClientSocialModule.OnGetFriendMetaData(), NetClientSocialModule.OnIPCClientAccess(), NetServerSocialModule.OnLobbyCreated(), NetClientSocialModule.OnLobbyEntered(), NetClientSocialModule.OnLobbyJoinRequest(), NetClientSocialModule.OnP2PSessionRequest(), NetClientSocialModule.OnPacketRead(), NetServerSocialModule.OnPacketRead(), NetClientSocialModule.OnRailCreateSessionFailed(), NetClientSocialModule.OnRailCreateSessionRequest(), NetServerSocialModule.OnRailEvent(), Lobby.OnRailEvent(), NetClientSocialModule.OnRailEvent(), NetClientSocialModule.OnRailRespondInvation(), NetClientSocialModule.OnRailSetMetaData(), NetClientSocialModule.OnReportServerID(), NetClientSocialModule.OnSessionConnectFail(), Lobby.OpenInviteOverlay(), FriendsSocialModule.OpenJoinInterface(), IPCBase.ReadCallback(), IPCClient.ReadCallback(), IPCServer.ReadCallback(), IPCBase.Send(), NetClientSocialModule.SendAuthTicket(), IPCBase.SendCallback(), NetClientSocialModule.SendFriendListToLocalServer(), IPCServer.StartListen(), NetClientSocialModule.TryAuthUserByRecvData(), NetServerSocialModule.TryAuthUserByRecvData(), NetServerSocialModule.UpdateFriendList(), and NetServerSocialModule.UpdateUserStateBySessionAuthResult().