Terraria: System.Security.AccessControl.CommonSecurityDescriptor.CreateFromParts
CreateFromParts()
void System.Security.AccessControl.CommonSecurityDescriptor.CreateFromParts (bool isContainer, bool isDS, ControlFlags flags, SecurityIdentifier owner, SecurityIdentifier group, SystemAcl systemAcl, DiscretionaryAcl discretionaryAcl) inline private
Definition at line 146 of file CommonSecurityDescriptor.cs.
    {
        if (systemAcl != null && systemAcl.IsContainer != isContainer)
        {
            throw new ArgumentException(isContainer ? System.SR.AccessControl_MustSpecifyContainerAcl : System.SR.AccessControl_MustSpecifyLeafObjectAcl, "systemAcl");
        }
        if (discretionaryAcl != null && discretionaryAcl.IsContainer != isContainer)
        {
            throw new ArgumentException(isContainer ? System.SR.AccessControl_MustSpecifyContainerAcl : System.SR.AccessControl_MustSpecifyLeafObjectAcl, "discretionaryAcl");
        }
        _isContainer = isContainer;
        if (systemAcl != null && systemAcl.IsDS != isDS)
        {
            throw new ArgumentException(isDS ? System.SR.AccessControl_MustSpecifyDirectoryObjectAcl : System.SR.AccessControl_MustSpecifyNonDirectoryObjectAcl, "systemAcl");
        }
        if (discretionaryAcl != null && discretionaryAcl.IsDS != isDS)
        {
            throw new ArgumentException(isDS ? System.SR.AccessControl_MustSpecifyDirectoryObjectAcl : System.SR.AccessControl_MustSpecifyNonDirectoryObjectAcl, "discretionaryAcl");
        }
        _isDS = isDS;
        _sacl = systemAcl;
        if (discretionaryAcl == null)
        {
            discretionaryAcl = System.Security.AccessControl.DiscretionaryAcl.CreateAllowEveryoneFullAccess(_isDS, _isContainer);
        }
        _dacl = discretionaryAcl;
        ControlFlags controlFlags = flags | ControlFlags.DiscretionaryAclPresent;
        controlFlags = ((systemAcl != null) ? (controlFlags | ControlFlags.SystemAclPresent) : (controlFlags & ~ControlFlags.SystemAclPresent));
        _rawSd = new RawSecurityDescriptor(controlFlags, owner, group, systemAcl?.RawAcl, discretionaryAcl.RawAcl);
    }
References System.Security.AccessControl.CommonSecurityDescriptor._dacl, System.Security.AccessControl.CommonSecurityDescriptor._isContainer, System.Security.AccessControl.CommonSecurityDescriptor._isDS, System.Security.AccessControl.CommonSecurityDescriptor._rawSd, System.Security.AccessControl.CommonSecurityDescriptor._sacl, System.SR.AccessControl_MustSpecifyContainerAcl, System.SR.AccessControl_MustSpecifyDirectoryObjectAcl, System.SR.AccessControl_MustSpecifyLeafObjectAcl, System.SR.AccessControl_MustSpecifyNonDirectoryObjectAcl, System.Security.AccessControl.DiscretionaryAcl.CreateAllowEveryoneFullAccess(), System.Security.AccessControl.CommonAcl.IsContainer, System.Security.AccessControl.CommonAcl.IsDS, and System.Security.AccessControl.CommonAcl.RawAcl.
Referenced by System.Security.AccessControl.CommonSecurityDescriptor.CommonSecurityDescriptor(), and System.Security.AccessControl.CommonSecurityDescriptor.CommonSecurityDescriptor().