Terraria: System.Security.AccessControl.CommonSecurityDescriptor.SetDiscretionaryAclProtection
SetDiscretionaryAclProtection()
void System.Security.AccessControl.CommonSecurityDescriptor.SetDiscretionaryAclProtection (bool isProtected, bool preserveInheritance) inline
Definition at line 220 of file CommonSecurityDescriptor.cs.
    {
        if (!isProtected)
        {
            RemoveControlFlags(ControlFlags.DiscretionaryAclProtected);
        }
        else
        {
            if (!preserveInheritance && DiscretionaryAcl != null)
            {
                DiscretionaryAcl.RemoveInheritedAces();
            }
            AddControlFlags(ControlFlags.DiscretionaryAclProtected);
        }
        if (DiscretionaryAcl != null && DiscretionaryAcl.EveryOneFullAccessForNullDacl)
        {
            DiscretionaryAcl.EveryOneFullAccessForNullDacl = false;
        }
    }
References System.Security.AccessControl.CommonSecurityDescriptor.AddControlFlags(), System.Security.AccessControl.DiscretionaryAcl.EveryOneFullAccessForNullDacl, System.Security.AccessControl.CommonSecurityDescriptor.RemoveControlFlags(), and System.Security.AccessControl.CommonAcl.RemoveInheritedAces().
Referenced by System.Security.AccessControl.ObjectSecurity< T >.SetAccessRuleProtection().