Terraria: Terraria.Net.Sockets.TcpSocket.StartListening
StartListening()
bool ISocket. Terraria.Net.Sockets.TcpSocket.StartListening (SocketConnectionAccepted callback) inline private
Implements Terraria.Net.Sockets.ISocket.
Definition at line 139 of file TcpSocket.cs.
    {
        IPAddress address = IPAddress.Any;
        if (Program.LaunchParameters.TryGetValue("-ip", out var value) && !IPAddress.TryParse(value, out address))
        {
            address = IPAddress.Any;
        }
        _isListening = true;
        _listenerCallback = callback;
        if (_listener == null)
        {
            _listener = new TcpListener(address, Netplay.ListenPort);
        }
        try
        {
            _listener.Start();
        }
        catch (Exception)
        {
            return false;
        }
        Thread thread = new Thread(ListenLoop);
        thread.IsBackground = true;
        thread.Name = "TCP Listen Thread";
        thread.Start();
        return true;
    }
References Terraria.Net.Sockets.TcpSocket._isListening, Terraria.Net.Sockets.TcpSocket._listener, Terraria.Net.Sockets.TcpSocket._listenerCallback, System.Net.IPAddress.Any, Terraria.Program.LaunchParameters, Terraria.Net.Sockets.TcpSocket.ListenLoop(), Terraria.Netplay.ListenPort, System.Net.Sockets.TcpListener.Start(), System.Net.IPAddress.TryParse(), and System.value.