Terraria: System.Xml.Schema.XmlSchemaAnyAttribute.Intersection
Intersection()
static XmlSchemaAnyAttribute System.Xml.Schema.XmlSchemaAnyAttribute.Intersection (XmlSchemaAnyAttribute o1, XmlSchemaAnyAttribute o2, bool v1Compat) inline static package
Definition at line 101 of file XmlSchemaAnyAttribute.cs.
    {
        NamespaceList namespaceList = System.Xml.Schema.NamespaceList.Intersection(o1.NamespaceList, o2.NamespaceList, v1Compat);
        if (namespaceList != null)
        {
            XmlSchemaAnyAttribute xmlSchemaAnyAttribute = new XmlSchemaAnyAttribute();
            xmlSchemaAnyAttribute._namespaceList = namespaceList;
            xmlSchemaAnyAttribute.ProcessContents = o1.ProcessContents;
            xmlSchemaAnyAttribute.Annotation = o1.Annotation;
            return xmlSchemaAnyAttribute;
        }
        return null;
    }
References System.Xml.Dictionary, and System.Xml.Schema.NamespaceList.Intersection().
Referenced by System.Xml.Schema.Compiler.CompileAnyAttributeIntersection(), and System.Xml.Schema.SchemaCollectionCompiler.CompileAnyAttributeIntersection().