Terraria: Terraria.Net.Sockets.TcpSocket.ListenLoop
ListenLoop()
void Terraria.Net.Sockets.TcpSocket.ListenLoop () inline private
Definition at line 172 of file TcpSocket.cs.
    {
        while (_isListening && !Netplay.Disconnect)
        {
            try
            {
                ISocket socket = new TcpSocket(_listener.AcceptTcpClient());
                Console.WriteLine(Language.GetTextValue("Net.ClientConnecting", socket.GetRemoteAddress()));
                _listenerCallback(socket);
            }
            catch (Exception)
            {
            }
        }
        _listener.Stop();
    }
References Terraria.Net.Sockets.TcpSocket.TcpSocket(), Terraria.Net.Sockets.TcpSocket._isListening, Terraria.Net.Sockets.TcpSocket._listener, Terraria.Net.Sockets.TcpSocket._listenerCallback, System.Net.Sockets.TcpListener.AcceptTcpClient(), Terraria.Netplay.Disconnect, Terraria.Localization.Language.GetTextValue(), System.Net.Sockets.TcpListener.Stop(), and System.Console.WriteLine().
Referenced by Terraria.Net.Sockets.TcpSocket.StartListening().