Terraria: System.IPv6AddressHelper.Parse
Parse() [2/2]
static void System.IPv6AddressHelper.Parse (ReadOnlySpan< char > address, Span< ushort > numbers, int start, ref string scopeId) inline static package
Definition at line 287 of file IPv6AddressHelper.cs.
    {
        int num = 0;
        int num2 = 0;
        int num3 = -1;
        bool flag = true;
        int num4 = 0;
        if (address[start] == '[')
        {
            start++;
        }
        int i = start;
        while (i < address.Length && address[i] != ']')
        {
            switch (address[i])
            {
            case '%':
                if (flag)
                {
                    numbers[num2++] = (ushort)num;
                    flag = false;
                }
                start = i;
                for (i++; i < address.Length && address[i] != ']' && address[i] != '/'; i++)
                {
                }
                scopeId = new string(address.Slice(start, i - start));
                for (; i < address.Length && address[i] != ']'; i++)
                {
                }
                break;
            case ':':
            {
                numbers[num2++] = (ushort)num;
                num = 0;
                i++;
                if (address[i] == ':')
                {
                    num3 = num2;
                    i++;
                }
                else if (num3 < 0 && num2 < 6)
                {
                    break;
                }
                for (int j = i; j < address.Length && address[j] != ']' && address[j] != ':' && address[j] != '%' && address[j] != '/' && j < i + 4; j++)
                {
                    if (address[j] == '.')
                    {
                        for (; j < address.Length && address[j] != ']' && address[j] != '/' && address[j] != '%'; j++)
{
                        }
                        num = IPv4AddressHelper.ParseHostNumber(address, i, j);
                        numbers[num2++] = (ushort)(num >> 16);
                        numbers[num2++] = (ushort)num;
                        i = j;
                        num = 0;
                        flag = false;
                        break;
                    }
                }
                break;
            }
            case '/':
                if (flag)
                {
                    numbers[num2++] = (ushort)num;
                    flag = false;
                }
                for (i++; address[i] != ']'; i++)
                {
                    num4 = num4 * 10 + (address[i] - 48);
                }
                break;
            default:
                num = num * 16 + Uri.FromHex(address[i++]);
                break;
            }
        }
        if (flag)
        {
            numbers[num2++] = (ushort)num;
        }
        if (num3 <= 0)
        {
            return;
        }
        int num5 = 7;
        int num6 = num2 - 1;
        if (num6 != num5)
        {
            for (int num7 = num2 - num3; num7 > 0; num7--)
            {
                numbers[num5--] = numbers[num6];
                numbers[num6--] = 0;
            }
        }
    }
References System.Uri.FromHex(), System.ReadOnlySpan< T >.Length, System.IPv4AddressHelper.ParseHostNumber(), System.ReadOnlySpan< T >.Slice(), and System.start.