Terraria: System.Web.Util.HttpEncoder.UrlDecode
UrlDecode() [2/3]
static string System.Web.Util.HttpEncoder.UrlDecode (byte[] bytes, int offset, int count, Encoding encoding) inline static package
Definition at line 335 of file HttpEncoder.cs.
    {
        if (!ValidateUrlEncodingParameters(bytes, offset, count))
        {
            return null;
        }
        UrlDecoder urlDecoder = new UrlDecoder(count, encoding);
        for (int i = 0; i < count; i++)
        {
            int num = offset + i;
            byte b = bytes[num];
            switch (b)
            {
            case 43:
                b = 32;
                break;
            case 37:
                if (i >= count - 2)
                {
                    break;
                }
                if (bytes[num + 1] == 117 && i < count - 5)
                {
                    int num2 = System.HexConverter.FromChar(bytes[num + 2]);
                    int num3 = System.HexConverter.FromChar(bytes[num + 3]);
                    int num4 = System.HexConverter.FromChar(bytes[num + 4]);
                    int num5 = System.HexConverter.FromChar(bytes[num + 5]);
                    if ((num2 | num3 | num4 | num5) != 255)
                    {
                        char ch = (char)((num2 << 12) | (num3 << 8) | (num4 << 4) | num5);
                        i += 5;
                        urlDecoder.AddChar(ch);
                        continue;
                    }
                }
                else
                {
                    int num6 = System.HexConverter.FromChar(bytes[num + 1]);
                    int num7 = System.HexConverter.FromChar(bytes[num + 2]);
                    if ((num6 | num7) != 255)
                    {
                        b = (byte)((num6 << 4) | num7);
                        i += 2;
                    }
                }
                break;
            }
            urlDecoder.AddByte(b);
        }
        return Utf16StringValidator.ValidateString(urlDecoder.GetString());
    }
References System.Web.Util.HttpEncoder.UrlDecoder.AddByte(), System.Web.Util.HttpEncoder.UrlDecoder.AddChar(), System.bytes, System.ch, System.count, System.HexConverter.FromChar(), System.Web.Util.HttpEncoder.UrlDecoder.GetString(), System.offset, System.Web.Util.Utf16StringValidator.ValidateString(), and System.Web.Util.HttpEncoder.ValidateUrlEncodingParameters().