Terraria: System.Web.Util.HttpEncoder.UrlDecode
UrlDecode() [3/3]
static string System.Web.Util.HttpEncoder.UrlDecode (string value, Encoding encoding) inline static package
Definition at line 388 of file HttpEncoder.cs.
    {
        if (value == null)
        {
            return null;
        }
        int length = value.Length;
        UrlDecoder urlDecoder = new UrlDecoder(length, encoding);
        for (int i = 0; i < length; i++)
        {
            char c = value[i];
            switch (c)
            {
            case '+':
                c = ' ';
                break;
            case '%':
                if (i >= length - 2)
                {
                    break;
                }
                if (value[i + 1] == 'u' && i < length - 5)
                {
                    int num = System.HexConverter.FromChar(value[i + 2]);
                    int num2 = System.HexConverter.FromChar(value[i + 3]);
                    int num3 = System.HexConverter.FromChar(value[i + 4]);
                    int num4 = System.HexConverter.FromChar(value[i + 5]);
                    if ((num | num2 | num3 | num4) != 255)
                    {
                        c = (char)((num << 12) | (num2 << 8) | (num3 << 4) | num4);
                        i += 5;
                        urlDecoder.AddChar(c);
                        continue;
                    }
                }
                else
                {
                    int num5 = System.HexConverter.FromChar(value[i + 1]);
                    int num6 = System.HexConverter.FromChar(value[i + 2]);
                    if ((num5 | num6) != 255)
                    {
                        byte b = (byte)((num5 << 4) | num6);
                        i += 2;
                        urlDecoder.AddByte(b);
                        continue;
                    }
                }
                break;
            }
            if ((c & 0xFF80) == 0)
            {
                urlDecoder.AddByte((byte)c);
            }
            else
            {
                urlDecoder.AddChar(c);
            }
        }
        return Utf16StringValidator.ValidateString(urlDecoder.GetString());
    }
References System.Web.Util.HttpEncoder.UrlDecoder.AddByte(), System.Web.Util.HttpEncoder.UrlDecoder.AddChar(), System.HexConverter.FromChar(), System.Web.Util.HttpEncoder.UrlDecoder.GetString(), System.length, System.Web.Util.Utf16StringValidator.ValidateString(), and System.value.