Terraria: System.Web.Util.HttpEncoder.JavaScriptStringEncode
JavaScriptStringEncode()
static string System.Web.Util.HttpEncoder.JavaScriptStringEncode (string value) inline static package
Definition at line 224 of file HttpEncoder.cs.
    {
        if (string.IsNullOrEmpty(value))
        {
            return string.Empty;
        }
        StringBuilder stringBuilder = null;
        int startIndex = 0;
        int num = 0;
        for (int i = 0; i < value.Length; i++)
        {
            char c = value[i];
            if (CharRequiresJavaScriptEncoding(c))
            {
                if (stringBuilder == null)
                {
                    stringBuilder = new StringBuilder(value.Length + 5);
                }
                if (num > 0)
                {
                    stringBuilder.Append(value, startIndex, num);
                }
                startIndex = i + 1;
                num = 0;
                switch (c)
                {
                case '\r':
                    stringBuilder.Append("\\r");
                    break;
                case '\t':
                    stringBuilder.Append("\\t");
                    break;
                case '"':
                    stringBuilder.Append("\\\"");
                    break;
                case '\\':
                    stringBuilder.Append("\\\\");
                    break;
                case '\n':
                    stringBuilder.Append("\\n");
                    break;
                case '\b':
                    stringBuilder.Append("\\b");
                    break;
                case '\f':
                    stringBuilder.Append("\\f");
                    break;
                default:
                    AppendCharAsUnicodeJavaScript(stringBuilder, c);
                    break;
                }
            }
            else
            {
                num++;
            }
        }
        if (stringBuilder == null)
        {
            return value;
        }
        if (num > 0)
        {
            stringBuilder.Append(value, startIndex, num);
        }
        return stringBuilder.ToString();
    }
References System.Text.StringBuilder.Append(), System.Web.Util.HttpEncoder.AppendCharAsUnicodeJavaScript(), System.Web.Util.HttpEncoder.CharRequiresJavaScriptEncoding(), System.startIndex, System.Text.StringBuilder.ToString(), and System.value.
Referenced by System.Web.HttpUtility.JavaScriptStringEncode(), and System.Web.HttpUtility.JavaScriptStringEncode().