Terraria: System.Web.Util.HttpEncoder.UrlDecode
UrlDecode() [1/3]
static byte[] System.Web.Util.HttpEncoder.UrlDecode (byte[] bytes, int offset, int count) inline static package
Definition at line 293 of file HttpEncoder.cs.
    {
        if (!ValidateUrlEncodingParameters(bytes, offset, count))
        {
            return null;
        }
        int num = 0;
        byte[] array = new byte[count];
        for (int i = 0; i < count; i++)
        {
            int num2 = offset + i;
            byte b = bytes[num2];
            switch (b)
            {
            case 43:
                b = 32;
                break;
            case 37:
                if (i < count - 2)
                {
                    int num3 = System.HexConverter.FromChar(bytes[num2 + 1]);
                    int num4 = System.HexConverter.FromChar(bytes[num2 + 2]);
                    if ((num3 | num4) != 255)
                    {
                        b = (byte)((num3 << 4) | num4);
                        i += 2;
                    }
                }
                break;
            }
            array[num++] = b;
        }
        if (num < array.Length)
        {
            byte[] array2 = new byte[num];
            Array.Copy(array, array2, num);
            array = array2;
        }
        return array;
    }
References System.array, System.bytes, System.Array.Copy(), System.count, System.HexConverter.FromChar(), System.offset, and System.Web.Util.HttpEncoder.ValidateUrlEncodingParameters().
Referenced by System.Web.HttpUtility.UrlDecode(), System.Web.HttpUtility.UrlDecode(), and System.Web.HttpUtility.UrlDecodeToBytes().