Terraria: System.Web.Util.HttpEncoder.UrlEncodeUnicode
UrlEncodeUnicode()
static string System.Web.Util.HttpEncoder.UrlEncodeUnicode (string value) inline static package
Definition at line 556 of file HttpEncoder.cs.
    {
        if (value == null)
        {
            return null;
        }
        int length = value.Length;
        StringBuilder stringBuilder = new StringBuilder(length);
        for (int i = 0; i < length; i++)
        {
            char c = value[i];
            if ((c & 0xFF80) == 0)
            {
                if (HttpEncoderUtility.IsUrlSafeChar(c))
                {
                    stringBuilder.Append(c);
                    continue;
                }
                if (c == ' ')
                {
                    stringBuilder.Append('+');
                    continue;
                }
                stringBuilder.Append('%');
                stringBuilder.Append(System.HexConverter.ToCharLower((int)c >> 4));
                stringBuilder.Append(System.HexConverter.ToCharLower(c));
            }
            else
            {
                stringBuilder.Append("%u");
                stringBuilder.Append(System.HexConverter.ToCharLower((int)c >> 12));
                stringBuilder.Append(System.HexConverter.ToCharLower((int)c >> 8));
                stringBuilder.Append(System.HexConverter.ToCharLower((int)c >> 4));
                stringBuilder.Append(System.HexConverter.ToCharLower(c));
            }
        }
        return stringBuilder.ToString();
    }
References System.Text.StringBuilder.Append(), System.Web.Util.HttpEncoderUtility.IsUrlSafeChar(), System.length, System.HexConverter.ToCharLower(), System.Text.StringBuilder.ToString(), and System.value.
Referenced by System.Web.HttpUtility.UrlEncodeUnicode().