Terraria: System.Web.Util.HttpEncoder.HtmlAttributeEncode
HtmlAttributeEncode() [1/2]
static string System.Web.Util.HttpEncoder.HtmlAttributeEncode (string value) inline static package
Definition at line 91 of file HttpEncoder.cs.
    {
        if (string.IsNullOrEmpty(value))
        {
            return value;
        }
        int num = IndexOfHtmlAttributeEncodingChars(value, 0);
        if (num == -1)
        {
            return value;
        }
        StringWriter stringWriter = new StringWriter(CultureInfo.InvariantCulture);
        HtmlAttributeEncode(value, stringWriter);
        return stringWriter.ToString();
    }
References System.Web.Util.HttpEncoder.HtmlAttributeEncode(), System.Web.Util.HttpEncoder.IndexOfHtmlAttributeEncodingChars(), System.Globalization.CultureInfo.InvariantCulture, System.IO.StringWriter.ToString(), and System.value.
Referenced by System.Web.Util.HttpEncoder.HtmlAttributeEncode(), System.Web.HttpUtility.HtmlAttributeEncode(), and System.Web.HttpUtility.HtmlAttributeEncode().