Terraria: System.Web.Util.HttpEncoder.AppendCharAsUnicodeJavaScript
AppendCharAsUnicodeJavaScript()
static void System.Web.Util.HttpEncoder.AppendCharAsUnicodeJavaScript (StringBuilder builder, char c) inline static private
Definition at line 73 of file HttpEncoder.cs.
    {
        StringBuilder.AppendInterpolatedStringHandler handler = new StringBuilder.AppendInterpolatedStringHandler(2, 1, builder);
        handler.AppendLiteral("\\u");
        handler.AppendFormatted((int)c, "x4");
        builder.Append(ref handler);
    }
References System.Text.StringBuilder.Append(), System.Text.StringBuilder.AppendInterpolatedStringHandler.AppendFormatted(), and System.Text.StringBuilder.AppendInterpolatedStringHandler.AppendLiteral().
Referenced by System.Web.Util.HttpEncoder.JavaScriptStringEncode().