Terraria: System.Web.Util.HttpEncoder.UrlEncode
UrlEncode() [1/2]
static byte[] System.Web.Util.HttpEncoder.UrlEncode (byte[] bytes, int offset, int count) inline static private
Definition at line 461 of file HttpEncoder.cs.
    {
        if (!ValidateUrlEncodingParameters(bytes, offset, count))
        {
            return null;
        }
        int num = 0;
        int num2 = 0;
        for (int i = 0; i < count; i++)
        {
            char c = (char)bytes[offset + i];
            if (c == ' ')
            {
                num++;
            }
            else if (!HttpEncoderUtility.IsUrlSafeChar(c))
            {
                num2++;
            }
        }
        if (num == 0 && num2 == 0)
        {
            if (offset == 0 && bytes.Length == count)
            {
                return bytes;
            }
            byte[] array = new byte[count];
            Buffer.BlockCopy(bytes, offset, array, 0, count);
            return array;
        }
        byte[] array2 = new byte[count + num2 * 2];
        int num3 = 0;
        for (int j = 0; j < count; j++)
        {
            byte b = bytes[offset + j];
            char c2 = (char)b;
            if (HttpEncoderUtility.IsUrlSafeChar(c2))
            {
                array2[num3++] = b;
                continue;
            }
            if (c2 == ' ')
            {
                array2[num3++] = 43;
                continue;
            }
            array2[num3++] = 37;
            array2[num3++] = (byte)System.HexConverter.ToCharLower(b >> 4);
            array2[num3++] = (byte)System.HexConverter.ToCharLower(b);
        }
        return array2;
    }
References System.array, System.Buffer.BlockCopy(), System.bytes, System.count, System.Web.Util.HttpEncoderUtility.IsUrlSafeChar(), System.offset, System.HexConverter.ToCharLower(), and System.Web.Util.HttpEncoder.ValidateUrlEncodingParameters().