Terraria: System.Threading.SpinLock.Exit
Exit() [1/2]
void System.Threading.SpinLock.Exit () inline
Definition at line 246 of file SpinLock.cs.
    {
        if ((_owner & int.MinValue) == 0)
        {
            ExitSlowPath(useMemoryBarrier: true);
        }
        else
        {
            Interlocked.Decrement(ref _owner);
        }
    }
References System.Threading.SpinLock._owner, System.Threading.Interlocked.Decrement(), and System.Threading.SpinLock.ExitSlowPath().
Referenced by System.Net.Http.FailedProxyCache.CleanupHelper(), System.Threading.ThreadPoolWorkQueue.WorkStealingQueue.LocalFindAndPop(), System.Threading.ThreadPoolWorkQueue.WorkStealingQueue.LocalPopCore(), System.Threading.ThreadPoolWorkQueue.WorkStealingQueue.LocalPush(), System.Threading.ThreadPoolWorkQueue.WorkStealingQueue.LocalPush_HandleTailOverflow(), System.Buffers.ConfigurableArrayPool< T >.Bucket.Rent(), System.Buffers.ConfigurableArrayPool< T >.Bucket.Return(), and System.Threading.ThreadPoolWorkQueue.WorkStealingQueue.TrySteal().