Terraria: System.Net.Mime.MimePart.ReadCallbackHandler
ReadCallbackHandler()
void System.Net.Mime.MimePart.ReadCallbackHandler (IAsyncResult result) inline package
Definition at line 206 of file MimePart.cs.
    {
        MimePartContext mimePartContext = (MimePartContext)result.AsyncState;
        mimePartContext._bytesLeft = Stream.EndRead(result);
        if (mimePartContext._bytesLeft > 0)
        {
            IAsyncResult asyncResult = mimePartContext._outputStream.BeginWrite(mimePartContext._buffer, 0, mimePartContext._bytesLeft, _writeCallback, mimePartContext);
            if (asyncResult.CompletedSynchronously)
            {
                WriteCallbackHandler(asyncResult);
            }
        }
        else
        {
            Complete(result, null);
        }
    }
References System.Net.Mime.MimePart.MimePartContext._buffer, System.Net.Mime.MimePart.MimePartContext._bytesLeft, System.Net.Mime.MimePart.MimePartContext._outputStream, System.Net.Mime.MimePart._writeCallback, System.asyncResult, System.IAsyncResult.AsyncState, System.IO.Stream.BeginWrite(), System.Net.Mime.MimePart.Complete(), System.IO.Stream.EndRead(), and System.Net.Mime.MimePart.WriteCallbackHandler().
Referenced by System.Net.Mime.MimePart.ContentStreamCallbackHandler(), System.Net.Mime.MimePart.ReadCallback(), and System.Net.Mime.MimePart.WriteCallbackHandler().