Terraria: System.Net.Mime.MimePart.WriteCallbackHandler
WriteCallbackHandler()
void System.Net.Mime.MimePart.WriteCallbackHandler (IAsyncResult result) inline package
Definition at line 241 of file MimePart.cs.
    {
        MimePartContext mimePartContext = (MimePartContext)result.AsyncState;
        mimePartContext._outputStream.EndWrite(result);
        IAsyncResult asyncResult = Stream.BeginRead(mimePartContext._buffer, 0, mimePartContext._buffer.Length, _readCallback, mimePartContext);
        if (asyncResult.CompletedSynchronously)
        {
            ReadCallbackHandler(asyncResult);
        }
    }
References System.Net.Mime.MimePart.MimePartContext._buffer, System.Net.Mime.MimePart.MimePartContext._outputStream, System.Net.Mime.MimePart._readCallback, System.asyncResult, System.IAsyncResult.AsyncState, System.IO.Stream.BeginRead(), System.IO.Stream.EndWrite(), and System.Net.Mime.MimePart.ReadCallbackHandler().
Referenced by System.Net.Mime.MimePart.ReadCallbackHandler(), and System.Net.Mime.MimePart.WriteCallback().