Terraria: System.Net.Mime.MimePart.Send
Send()
override void System.Net.Mime.MimePart.Send (BaseWriter writer, bool allowUnicode) inline package virtual
Reimplemented from System.Net.Mime.MimeBasePart.
Definition at line 317 of file MimePart.cs.
    {
        if (Stream != null)
        {
            byte[] buffer = new byte[17408];
            PrepareHeaders(allowUnicode);
            writer.WriteHeaders(base.Headers, allowUnicode);
            Stream contentStream = writer.GetContentStream();
            contentStream = GetEncodedStream(contentStream);
            ResetStream();
            _streamUsedOnce = true;
            int count;
            while ((count = Stream.Read(buffer, 0, 17408)) > 0)
            {
                contentStream.Write(buffer, 0, count);
            }
            contentStream.Close();
        }
    }
References System.Net.Mime.MimePart._streamUsedOnce, System.buffer, System.IO.Stream.Close(), System.count, System.Net.Mime.MimePart.GetEncodedStream(), System.Net.Mime.MimeBasePart.PrepareHeaders(), System.IO.Stream.Read(), System.Net.Mime.MimePart.ResetStream(), System.IO.Stream.Write(), and System.writer.