Terraria: System.Net.Mime.MimePart.ContentStreamCallbackHandler
ContentStreamCallbackHandler()
void System.Net.Mime.MimePart.ContentStreamCallbackHandler (IAsyncResult result) inline package
Definition at line 270 of file MimePart.cs.
    {
        MimePartContext mimePartContext = (MimePartContext)result.AsyncState;
        Stream stream = mimePartContext._writer.EndGetContentStream(result);
        mimePartContext._outputStream = GetEncodedStream(stream);
        _readCallback = ReadCallback;
        _writeCallback = WriteCallback;
        IAsyncResult asyncResult = Stream.BeginRead(mimePartContext._buffer, 0, mimePartContext._buffer.Length, _readCallback, mimePartContext);
        if (asyncResult.CompletedSynchronously)
        {
            ReadCallbackHandler(asyncResult);
        }
    }
References System.Net.Mime.MimePart.MimePartContext._buffer, System.Net.Mime.MimePart._readCallback, System.Net.Mime.MimePart._writeCallback, System.Net.Mime.MimePart.MimePartContext._writer, System.asyncResult, System.IAsyncResult.AsyncState, System.IO.Stream.BeginRead(), System.Net.Mime.BaseWriter.EndGetContentStream(), System.Net.Mime.MimePart.GetEncodedStream(), System.Net.Mime.MimePart.ReadCallback(), System.Net.Mime.MimePart.ReadCallbackHandler(), System.stream, and System.Net.Mime.MimePart.WriteCallback().
Referenced by System.Net.Mime.MimePart.BeginSend(), and System.Net.Mime.MimePart.ContentStreamCallback().