Terraria: System.Net.Mime.MimePart.ReadCallback
ReadCallback()
void System.Net.Mime.MimePart.ReadCallback (IAsyncResult result) inline package
Definition at line 189 of file MimePart.cs.
    {
        if (result.CompletedSynchronously)
        {
            return;
        }
        ((MimePartContext)result.AsyncState)._completedSynchronously = false;
        try
        {
            ReadCallbackHandler(result);
        }
        catch (Exception e)
        {
            Complete(result, e);
        }
    }
References System.IAsyncResult.AsyncState, System.Net.Mime.MimePart.Complete(), System.IAsyncResult.CompletedSynchronously, and System.Net.Mime.MimePart.ReadCallbackHandler().
Referenced by System.Net.Mime.MimePart.ContentStreamCallbackHandler().