Terraria: System.Net.Mime.MimePart.BeginSend
BeginSend()
override IAsyncResult System.Net.Mime.MimePart.BeginSend (BaseWriter writer, AsyncCallback callback, bool allowUnicode, object state) inline package virtual
Reimplemented from System.Net.Mime.MimeBasePart.
Definition at line 301 of file MimePart.cs.
    {
        PrepareHeaders(allowUnicode);
        writer.WriteHeaders(base.Headers, allowUnicode);
        MimePartAsyncResult result = new MimePartAsyncResult(this, state, callback);
        MimePartContext state2 = new MimePartContext(writer, result);
        ResetStream();
        _streamUsedOnce = true;
        IAsyncResult asyncResult = writer.BeginGetContentStream(ContentStreamCallback, state2);
        if (asyncResult.CompletedSynchronously)
        {
            ContentStreamCallbackHandler(asyncResult);
        }
        return result;
    }
References System.Net.Mime.MimePart._streamUsedOnce, System.asyncResult, System.Net.Mime.MimePart.ContentStreamCallback(), System.Net.Mime.MimePart.ContentStreamCallbackHandler(), System.Net.Mime.MimeBasePart.PrepareHeaders(), System.Net.Mime.MimePart.ResetStream(), System.state, and System.writer.