Terraria: System.Net.Mime.MimePart.ResetStream
ResetStream()
void System.Net.Mime.MimePart.ResetStream () inline package
Definition at line 337 of file MimePart.cs.
    {
        if (_streamUsedOnce)
        {
            if (!Stream.CanSeek)
            {
                throw new InvalidOperationException(System.SR.MimePartCantResetStream);
            }
            Stream.Seek(0L, SeekOrigin.Begin);
            _streamUsedOnce = false;
        }
    }
References System.Net.Mime.MimePart._streamUsedOnce, System.IO.Stream.CanSeek, System.L, System.SR.MimePartCantResetStream, and System.IO.Stream.Seek().
Referenced by System.Net.Mime.MimePart.BeginSend(), System.Net.Mail.AttachmentBase.PrepareForSending(), and System.Net.Mime.MimePart.Send().