Terraria: System.Net.Mime.MimePart.SetContent
SetContent() [1/3]
void System.Net.Mime.MimePart.SetContent (Stream stream) inline package
Definition at line 119 of file MimePart.cs.
    {
        if (stream == null)
        {
            throw new ArgumentNullException("stream");
        }
        if (_streamSet)
        {
            _stream.Close();
            _stream = null;
            _streamSet = false;
        }
        _stream = stream;
        _streamSet = true;
        _streamUsedOnce = false;
        TransferEncoding = TransferEncoding.Base64;
    }
References System.Net.Mime.MimePart._stream, System.Net.Mime.MimePart._streamSet, System.Net.Mime.MimePart._streamUsedOnce, System.IO.Stream.Close(), and System.stream.
Referenced by System.Net.Mail.AttachmentBase.AttachmentBase(), System.Net.Mail.AttachmentBase.AttachmentBase(), System.Net.Mail.AttachmentBase.AttachmentBase(), System.Net.Mail.AttachmentBase.AttachmentBase(), System.Net.Mime.MimePart.SetContent(), System.Net.Mime.MimePart.SetContent(), System.Net.Mail.AttachmentBase.SetContentFromFile(), System.Net.Mail.AttachmentBase.SetContentFromFile(), System.Net.Mail.AttachmentBase.SetContentFromString(), and System.Net.Mail.AttachmentBase.SetContentFromString().