Terraria: System.IO.Compression.ZipArchive.WriteFile
WriteFile()
void System.IO.Compression.ZipArchive.WriteFile () inline private
Definition at line 435 of file ZipArchive.cs.
    {
        if (_mode == ZipArchiveMode.Update)
        {
            List<ZipArchiveEntry> list = new List<ZipArchiveEntry>();
            foreach (ZipArchiveEntry entry in _entries)
            {
                if (!entry.LoadLocalHeaderExtraFieldAndCompressedBytesIfNeeded())
                {
                    list.Add(entry);
                }
            }
            foreach (ZipArchiveEntry item in list)
            {
                item.Delete();
            }
            _archiveStream.Seek(0L, SeekOrigin.Begin);
            _archiveStream.SetLength(0L);
        }
        foreach (ZipArchiveEntry entry2 in _entries)
        {
            entry2.WriteAndFinishLocalEntry();
        }
        long position = _archiveStream.Position;
        foreach (ZipArchiveEntry entry3 in _entries)
        {
            entry3.WriteCentralDirectoryFileHeader();
        }
        long sizeOfCentralDirectory = _archiveStream.Position - position;
        WriteArchiveEpilogue(position, sizeOfCentralDirectory);
    }
References System.IO.Compression.ZipArchive._archiveStream, System.IO.Compression.ZipArchive._entries, System.IO.Compression.ZipArchive._mode, System.item, System.L, System.list, System.IO.Stream.Position, System.IO.Stream.Seek(), System.IO.Stream.SetLength(), and System.IO.Compression.ZipArchive.WriteArchiveEpilogue().
Referenced by System.IO.Compression.ZipArchive.Dispose().