Terraria: System.IO.Compression.ZipArchive.DoCreateEntry
DoCreateEntry()
ZipArchiveEntry System.IO.Compression.ZipArchive.DoCreateEntry (string entryName, CompressionLevel? compressionLevel) inline private
Definition at line 244 of file ZipArchive.cs.
    {
        if (entryName == null)
        {
            throw new ArgumentNullException("entryName");
        }
        if (string.IsNullOrEmpty(entryName))
        {
            throw new ArgumentException(System.SR.CannotBeEmpty, "entryName");
        }
        if (_mode == ZipArchiveMode.Read)
        {
            throw new NotSupportedException(System.SR.CreateInReadMode);
        }
        ThrowIfDisposed();
        ZipArchiveEntry zipArchiveEntry = (compressionLevel.HasValue ? new ZipArchiveEntry(this, entryName, compressionLevel.Value) : new ZipArchiveEntry(this, entryName));
        AddEntry(zipArchiveEntry);
        return zipArchiveEntry;
    }
References System.IO.Compression.ZipArchive._mode, System.IO.Compression.ZipArchive.AddEntry(), System.SR.CannotBeEmpty, System.SR.CreateInReadMode, and System.IO.Compression.ZipArchive.ThrowIfDisposed().
Referenced by System.IO.Compression.ZipArchive.CreateEntry(), and System.IO.Compression.ZipArchive.CreateEntry().