Terraria: Internal.Runtime.InteropServices.ComponentActivator.LoadAssemblyAndGetFunctionPointer
LoadAssemblyAndGetFunctionPointer()
static unsafe int Internal.Runtime.InteropServices.ComponentActivator.LoadAssemblyAndGetFunctionPointer (IntPtr assemblyPathNative, IntPtr typeNameNative, IntPtr methodNameNative, IntPtr delegateTypeNative, IntPtr reserved, IntPtr functionHandle) inline static
Definition at line 42 of file ComponentActivator.cs.
    {
        if (!IsSupported)
        {
            return -2147450713;
        }
        try
        {
            string assemblyPath = MarshalToString(assemblyPathNative, "assemblyPathNative");
            string typeName = MarshalToString(typeNameNative, "typeNameNative");
            string methodName = MarshalToString(methodNameNative, "methodNameNative");
            if (reserved != IntPtr.Zero)
            {
                throw new ArgumentOutOfRangeException("reserved");
            }
            if (functionHandle == IntPtr.Zero)
            {
                throw new ArgumentNullException("functionHandle");
            }
            AssemblyLoadContext isolatedComponentLoadContext = GetIsolatedComponentLoadContext(assemblyPath);
            *(IntPtr*)(void*)functionHandle = InternalGetFunctionPointer(isolatedComponentLoadContext, typeName, methodName, delegateTypeNative);
        }
        catch (Exception ex)
        {
            return ex.HResult;
        }
        return 0;
    }
References Internal.Runtime.InteropServices.ComponentActivator.GetIsolatedComponentLoadContext(), Internal.Runtime.InteropServices.ComponentActivator.InternalGetFunctionPointer(), Internal.Runtime.InteropServices.ComponentActivator.IsSupported, Internal.Runtime.InteropServices.ComponentActivator.MarshalToString(), and System.IntPtr.Zero.