Terraria: System.IO.Compression.ZipArchive.TryReadZip64EndOfCentralDirectory
TryReadZip64EndOfCentralDirectory()
void System.IO.Compression.ZipArchive.TryReadZip64EndOfCentralDirectory (ZipEndOfCentralDirectoryBlock eocd, long eocdStart) inline private
Definition at line 396 of file ZipArchive.cs.
    {
        if (eocd.NumberOfThisDisk != ushort.MaxValue && eocd.OffsetOfStartOfCentralDirectoryWithRespectToTheStartingDiskNumber != uint.MaxValue && eocd.NumberOfEntriesInTheCentralDirectory != ushort.MaxValue)
        {
            return;
        }
        _archiveStream.Seek(eocdStart - 16, SeekOrigin.Begin);
        if (ZipHelper.SeekBackwardsToSignature(_archiveStream, 117853008u, 4))
        {
            Zip64EndOfCentralDirectoryLocator zip64EOCDLocator;
            bool flag = Zip64EndOfCentralDirectoryLocator.TryReadBlock(_archiveReader, out zip64EOCDLocator);
            if (zip64EOCDLocator.OffsetOfZip64EOCD > long.MaxValue)
            {
                throw new InvalidDataException(System.SR.FieldTooBigOffsetToZip64EOCD);
            }
            long offsetOfZip64EOCD = (long)zip64EOCDLocator.OffsetOfZip64EOCD;
            _archiveStream.Seek(offsetOfZip64EOCD, SeekOrigin.Begin);
            if (!Zip64EndOfCentralDirectoryRecord.TryReadBlock(_archiveReader, out var zip64EOCDRecord))
            {
                throw new InvalidDataException(System.SR.Zip64EOCDNotWhereExpected);
            }
            _numberOfThisDisk = zip64EOCDRecord.NumberOfThisDisk;
            if (zip64EOCDRecord.NumberOfEntriesTotal > long.MaxValue)
            {
                throw new InvalidDataException(System.SR.FieldTooBigNumEntries);
            }
            if (zip64EOCDRecord.OffsetOfCentralDirectory > long.MaxValue)
            {
                throw new InvalidDataException(System.SR.FieldTooBigOffsetToCD);
            }
            if (zip64EOCDRecord.NumberOfEntriesTotal != zip64EOCDRecord.NumberOfEntriesOnThisDisk)
            {
                throw new InvalidDataException(System.SR.SplitSpanned);
            }
            _expectedNumberOfEntries = (long)zip64EOCDRecord.NumberOfEntriesTotal;
            _centralDirectoryStart = (long)zip64EOCDRecord.OffsetOfCentralDirectory;
        }
    }
References System.IO.Compression.ZipArchive._archiveReader, System.IO.Compression.ZipArchive._archiveStream, System.IO.Compression.ZipArchive._centralDirectoryStart, System.IO.Compression.ZipArchive._expectedNumberOfEntries, System.IO.Compression.ZipArchive._numberOfThisDisk, System.SR.FieldTooBigNumEntries, System.SR.FieldTooBigOffsetToCD, System.SR.FieldTooBigOffsetToZip64EOCD, System.IO.Stream.Seek(), System.IO.Compression.ZipHelper.SeekBackwardsToSignature(), System.SR.SplitSpanned, System.IO.Compression.Zip64EndOfCentralDirectoryLocator.TryReadBlock(), System.IO.Compression.Zip64EndOfCentralDirectoryRecord.TryReadBlock(), and System.SR.Zip64EOCDNotWhereExpected.
Referenced by System.IO.Compression.ZipArchive.ReadEndOfCentralDirectory().