Terraria: System.IO.Compression.ZipArchive.ReadCentralDirectory
ReadCentralDirectory()
void System.IO.Compression.ZipArchive.ReadCentralDirectory () inline private
Definition at line 329 of file ZipArchive.cs.
    {
        try
        {
            _archiveStream.Seek(_centralDirectoryStart, SeekOrigin.Begin);
            long num = 0L;
            bool saveExtraFieldsAndComments = Mode == ZipArchiveMode.Update;
            ZipCentralDirectoryFileHeader header;
            while (ZipCentralDirectoryFileHeader.TryReadBlock(_archiveReader, saveExtraFieldsAndComments, out header))
            {
                AddEntry(new ZipArchiveEntry(this, header));
                num++;
            }
            if (num != _expectedNumberOfEntries)
            {
                throw new InvalidDataException(System.SR.NumEntriesWrong);
            }
        }
        catch (EndOfStreamException p)
        {
            throw new InvalidDataException(System.SR.Format(System.SR.CentralDirectoryInvalid, p));
        }
    }
References System.IO.Compression.ZipArchive._archiveReader, System.IO.Compression.ZipArchive._archiveStream, System.IO.Compression.ZipArchive._centralDirectoryStart, System.IO.Compression.ZipArchive._expectedNumberOfEntries, System.IO.Compression.ZipArchive.AddEntry(), System.SR.CentralDirectoryInvalid, System.SR.Format(), System.L, System.SR.NumEntriesWrong, System.IO.Stream.Seek(), and System.IO.Compression.ZipCentralDirectoryFileHeader.TryReadBlock().
Referenced by System.IO.Compression.ZipArchive.EnsureCentralDirectoryRead().