Terraria: System.IO.Compression.ZipArchive.CloseStreams
CloseStreams()
void System.IO.Compression.ZipArchive.CloseStreams () inline private
Definition at line 306 of file ZipArchive.cs.
    {
        if (!_leaveOpen)
        {
            _archiveStream.Dispose();
            _backingStream?.Dispose();
            _archiveReader?.Dispose();
        }
        else if (_backingStream != null)
        {
            _archiveStream.Dispose();
        }
    }
References System.IO.Compression.ZipArchive._archiveReader, System.IO.Compression.ZipArchive._archiveStream, System.IO.Compression.ZipArchive._backingStream, System.IO.Compression.ZipArchive._leaveOpen, System.IO.Stream.Dispose(), and System.IO.BinaryReader.Dispose().
Referenced by System.IO.Compression.ZipArchive.Dispose().