Terraria: Internal.Runtime.InteropServices.ComponentActivator.InternalGetFunctionPointer
InternalGetFunctionPointer()
static IntPtr Internal.Runtime.InteropServices.ComponentActivator.InternalGetFunctionPointer (AssemblyLoadContext alc, string typeName, string methodName, IntPtr delegateTypeNative) inline static private
Definition at line 119 of file ComponentActivator.cs.
    {
        Func<AssemblyName, Assembly> assemblyResolver = (AssemblyName name) => alc.LoadFromAssemblyName(name);
        Type type;
        if (delegateTypeNative == IntPtr.Zero)
        {
            type = typeof(ComponentEntryPoint);
        }
        else if (delegateTypeNative == (IntPtr)(-1))
        {
            type = null;
        }
        else
        {
            string typeName2 = MarshalToString(delegateTypeNative, "delegateTypeNative");
            type = Type.GetType(typeName2, assemblyResolver, null, throwOnError: true);
        }
        Type type2 = Type.GetType(typeName, assemblyResolver, null, throwOnError: true);
        IntPtr intPtr;
        if (type == null)
        {
            BindingFlags bindingAttr = BindingFlags.Static | BindingFlags.Public | BindingFlags.NonPublic;
            MethodInfo method = type2.GetMethod(methodName, bindingAttr);
            if (method == null)
            {
                throw new MissingMethodException(typeName, methodName);
            }
            if (method.GetCustomAttribute<UnmanagedCallersOnlyAttribute>() == null)
            {
                throw new InvalidOperationException(SR.InvalidOperation_FunctionMissingUnmanagedCallersOnly);
            }
            intPtr = method.MethodHandle.GetFunctionPointer();
        }
        else
        {
            Delegate @delegate = Delegate.CreateDelegate(type, type2, methodName);
            intPtr = Marshal.GetFunctionPointerForDelegate(@delegate);
            lock (s_delegates)
            {
                s_delegates[intPtr] = @delegate;
            }
        }
        return intPtr;
    }
References Internal.Runtime.InteropServices.ComponentActivator.ComponentEntryPoint(), System.Delegate.CreateDelegate(), System.Runtime.InteropServices.Marshal.GetFunctionPointerForDelegate(), System.Type.GetType(), System.SR.InvalidOperation_FunctionMissingUnmanagedCallersOnly, Internal.Runtime.InteropServices.ComponentActivator.MarshalToString(), Internal.Runtime.InteropServices.ComponentActivator.s_delegates, System.type, and System.IntPtr.Zero.
Referenced by Internal.Runtime.InteropServices.ComponentActivator.GetFunctionPointer(), and Internal.Runtime.InteropServices.ComponentActivator.LoadAssemblyAndGetFunctionPointer().