Terraria: System.IO.Compression.ZipArchive.ZipArchive
ZipArchive() [4/4]
System.IO.Compression.ZipArchive.ZipArchive (Stream stream, ZipArchiveMode mode, bool leaveOpen, Encoding? entryNameEncoding) inline
Definition at line 94 of file ZipArchive.cs.
    {
        if (stream == null)
        {
            throw new ArgumentNullException("stream");
        }
        EntryNameEncoding = entryNameEncoding;
        Stream stream2 = null;
        try
        {
            _backingStream = null;
            switch (mode)
            {
            case ZipArchiveMode.Create:
                if (!stream.CanWrite)
                {
                    throw new ArgumentException(System.SR.CreateModeCapabilities);
                }
                break;
            case ZipArchiveMode.Read:
                if (!stream.CanRead)
                {
                    throw new ArgumentException(System.SR.ReadModeCapabilities);
                }
                if (!stream.CanSeek)
                {
                    _backingStream = stream;
                    stream2 = (stream = new MemoryStream());
                    _backingStream.CopyTo(stream);
                    stream.Seek(0L, SeekOrigin.Begin);
                }
                break;
            case ZipArchiveMode.Update:
                if (!stream.CanRead || !stream.CanWrite || !stream.CanSeek)
                {
                    throw new ArgumentException(System.SR.UpdateModeCapabilities);
                }
                break;
            default:
                throw new ArgumentOutOfRangeException("mode");
            }
            _mode = mode;
            if (mode == ZipArchiveMode.Create && !stream.CanSeek)
            {
                _archiveStream = new PositionPreservingWriteOnlyStreamWrapper(stream);
            }
            else
            {
                _archiveStream = stream;
            }
            _archiveStreamOwner = null;
            if (mode == ZipArchiveMode.Create)
            {
                _archiveReader = null;
            }
            else
            {
                _archiveReader = new BinaryReader(_archiveStream);
            }
            _entries = new List<ZipArchiveEntry>();
            _entriesCollection = new ReadOnlyCollection<ZipArchiveEntry>(_entries);
            _entriesDictionary = new Dictionary<string, ZipArchiveEntry>();
            _readEntries = false;
            _leaveOpen = leaveOpen;
            _centralDirectoryStart = 0L;
            _isDisposed = false;
            _numberOfThisDisk = 0u;
            _archiveComment = null;
            switch (mode)
            {
            case ZipArchiveMode.Create:
                _readEntries = true;
                return;
            case ZipArchiveMode.Read:
                ReadEndOfCentralDirectory();
                return;
            }
            if (_archiveStream.Length == 0L)
            {
                _readEntries = true;
                return;
            }
            ReadEndOfCentralDirectory();
            EnsureCentralDirectoryRead();
            foreach (ZipArchiveEntry entry in _entries)
            {
                entry.ThrowIfNotOpenable(needToUncompress: false, needToLoadIntoMemory: true);
            }
        }
        catch
        {
            stream2?.Dispose();
            throw;
        }
    }
References System.IO.Compression.ZipArchive._archiveComment, System.IO.Compression.ZipArchive._archiveReader, System.IO.Compression.ZipArchive._archiveStream, System.IO.Compression.ZipArchive._archiveStreamOwner, System.IO.Compression.ZipArchive._backingStream, System.IO.Compression.ZipArchive._centralDirectoryStart, System.IO.Compression.ZipArchive._entries, System.IO.Compression.ZipArchive._entriesCollection, System.IO.Compression.ZipArchive._entriesDictionary, System.IO.Compression.ZipArchive._isDisposed, System.IO.Compression.ZipArchive._leaveOpen, System.IO.Compression.ZipArchive._mode, System.IO.Compression.ZipArchive._numberOfThisDisk, System.IO.Compression.ZipArchive._readEntries, System.IO.Stream.CopyTo(), System.SR.CreateModeCapabilities, System.IO.Compression.ZipArchive.EnsureCentralDirectoryRead(), System.IO.Compression.ZipArchive.EntryNameEncoding, System.L, System.IO.Stream.Length, System.IO.Compression.ZipArchive.ReadEndOfCentralDirectory(), System.SR.ReadModeCapabilities, System.stream, and System.SR.UpdateModeCapabilities.