Terraria: System.IO.Compression.ZipArchive.ReadEndOfCentralDirectory
ReadEndOfCentralDirectory()
void System.IO.Compression.ZipArchive.ReadEndOfCentralDirectory () inline private
Definition at line 353 of file ZipArchive.cs.
    {
        try
        {
            _archiveStream.Seek(-18L, SeekOrigin.End);
            if (!ZipHelper.SeekBackwardsToSignature(_archiveStream, 101010256u, 65539))
            {
                throw new InvalidDataException(System.SR.EOCDNotFound);
            }
            long position = _archiveStream.Position;
            ZipEndOfCentralDirectoryBlock eocdBlock;
            bool flag = ZipEndOfCentralDirectoryBlock.TryReadBlock(_archiveReader, out eocdBlock);
            if (eocdBlock.NumberOfThisDisk != eocdBlock.NumberOfTheDiskWithTheStartOfTheCentralDirectory)
            {
                throw new InvalidDataException(System.SR.SplitSpanned);
            }
            _numberOfThisDisk = eocdBlock.NumberOfThisDisk;
            _centralDirectoryStart = eocdBlock.OffsetOfStartOfCentralDirectoryWithRespectToTheStartingDiskNumber;
            if (eocdBlock.NumberOfEntriesInTheCentralDirectory != eocdBlock.NumberOfEntriesInTheCentralDirectoryOnThisDisk)
            {
                throw new InvalidDataException(System.SR.SplitSpanned);
            }
            _expectedNumberOfEntries = eocdBlock.NumberOfEntriesInTheCentralDirectory;
            if (_mode == ZipArchiveMode.Update)
            {
                _archiveComment = eocdBlock.ArchiveComment;
            }
            TryReadZip64EndOfCentralDirectory(eocdBlock, position);
            if (_centralDirectoryStart > _archiveStream.Length)
            {
                throw new InvalidDataException(System.SR.FieldTooBigOffsetToCD);
            }
        }
        catch (EndOfStreamException innerException)
        {
            throw new InvalidDataException(System.SR.CDCorrupt, innerException);
        }
        catch (IOException innerException2)
        {
            throw new InvalidDataException(System.SR.CDCorrupt, innerException2);
        }
    }
References System.IO.Compression.ZipArchive._archiveComment, System.IO.Compression.ZipArchive._archiveReader, System.IO.Compression.ZipArchive._archiveStream, System.IO.Compression.ZipArchive._centralDirectoryStart, System.IO.Compression.ZipArchive._expectedNumberOfEntries, System.IO.Compression.ZipArchive._mode, System.IO.Compression.ZipArchive._numberOfThisDisk, System.SR.CDCorrupt, System.SR.EOCDNotFound, System.SR.FieldTooBigOffsetToCD, System.L, System.IO.Stream.Length, System.IO.Stream.Position, System.IO.Stream.Seek(), System.IO.Compression.ZipHelper.SeekBackwardsToSignature(), System.SR.SplitSpanned, System.IO.Compression.ZipEndOfCentralDirectoryBlock.TryReadBlock(), and System.IO.Compression.ZipArchive.TryReadZip64EndOfCentralDirectory().
Referenced by System.IO.Compression.ZipArchive.ZipArchive().