Terraria: System.IO.Compression.ZipArchive.WriteArchiveEpilogue
WriteArchiveEpilogue()
void System.IO.Compression.ZipArchive.WriteArchiveEpilogue (long startOfCentralDirectory, long sizeOfCentralDirectory) inline private
Definition at line 467 of file ZipArchive.cs.
    {
        if (startOfCentralDirectory >= uint.MaxValue || sizeOfCentralDirectory >= uint.MaxValue || _entries.Count >= 65535)
        {
            long position = _archiveStream.Position;
            Zip64EndOfCentralDirectoryRecord.WriteBlock(_archiveStream, _entries.Count, startOfCentralDirectory, sizeOfCentralDirectory);
            Zip64EndOfCentralDirectoryLocator.WriteBlock(_archiveStream, position);
        }
        ZipEndOfCentralDirectoryBlock.WriteBlock(_archiveStream, _entries.Count, startOfCentralDirectory, sizeOfCentralDirectory, _archiveComment);
    }
References System.IO.Compression.ZipArchive._archiveComment, System.IO.Compression.ZipArchive._archiveStream, System.IO.Compression.ZipArchive._entries, System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.IO.Stream.Position, System.IO.Compression.Zip64EndOfCentralDirectoryRecord.WriteBlock(), System.IO.Compression.ZipEndOfCentralDirectoryBlock.WriteBlock(), and System.IO.Compression.Zip64EndOfCentralDirectoryLocator.WriteBlock().
Referenced by System.IO.Compression.ZipArchive.WriteFile().