Terraria: System.IO.Enumeration.FileSystemEnumerableFactory.NormalizeInputs
NormalizeInputs()
static bool System.IO.Enumeration.FileSystemEnumerableFactory.NormalizeInputs (ref string directory, ref string expression, MatchType matchType) inline static package
Definition at line 9 of file FileSystemEnumerableFactory.cs.
    {
        if (Path.IsPathRooted(expression))
        {
            throw new ArgumentException(SR.Arg_Path2IsRooted, "expression");
        }
        if (expression.Contains('\0'))
        {
            throw new ArgumentException(SR.Argument_InvalidPathChars, expression);
        }
        if (directory.Contains('\0'))
        {
            throw new ArgumentException(SR.Argument_InvalidPathChars, directory);
        }
        ReadOnlySpan<char> directoryName = Path.GetDirectoryName(expression.AsSpan());
        bool result = true;
        if (directoryName.Length != 0)
        {
            directory = Path.Join(directory.AsSpan(), directoryName);
            expression = expression.Substring(directoryName.Length + 1);
            result = false;
        }
        switch (matchType)
        {
        case MatchType.Win32:
            if (expression == "*")
            {
                break;
            }
            if (string.IsNullOrEmpty(expression) || expression == "." || expression == "*.*")
            {
                expression = "*";
                break;
            }
            if (Path.DirectorySeparatorChar != '\\' && expression.IndexOfAny(s_unixEscapeChars) != -1)
            {
                expression = expression.Replace("\\", "\\\\");
                expression = expression.Replace("\"", "\\\"");
                expression = expression.Replace(">", "\\>");
                expression = expression.Replace("<", "\\<");
            }
            expression = FileSystemName.TranslateWin32Expression(expression);
            break;
        default:
            throw new ArgumentOutOfRangeException("matchType");
        case MatchType.Simple:
            break;
        }
        return result;
    }
References System.SR.Arg_Path2IsRooted, System.SR.Argument_InvalidPathChars, System.Collections.Generic.Dictionary< TKey, TValue >.Contains(), System.IO.Path.DirectorySeparatorChar, System.IO.Path.GetDirectoryName(), System.IO.Path.IsPathRooted(), System.IO.Path.Join(), System.IO.Enumeration.FileSystemEnumerableFactory.s_unixEscapeChars, and System.IO.Enumeration.FileSystemName.TranslateWin32Expression().
Referenced by System.IO.DirectoryInfo.InternalEnumerateInfos(), and System.IO.Directory.InternalEnumeratePaths().