Terraria: System.IO.Enumeration.FileSystemEnumerableFactory.MatchesPattern
MatchesPattern()
static bool System.IO.Enumeration.FileSystemEnumerableFactory.MatchesPattern (string expression, ReadOnlySpan< char > name, EnumerationOptions options) inline static private
Definition at line 60 of file FileSystemEnumerableFactory.cs.
    {
        bool ignoreCase = (options.MatchCasing == MatchCasing.PlatformDefault && !PathInternal.IsCaseSensitive) || options.MatchCasing == MatchCasing.CaseInsensitive;
        return options.MatchType switch
        {
            MatchType.Simple => FileSystemName.MatchesSimpleExpression(expression.AsSpan(), name, ignoreCase),
            MatchType.Win32 => FileSystemName.MatchesWin32Expression(expression.AsSpan(), name, ignoreCase),
            _ => throw new ArgumentOutOfRangeException("options"),
        };
    }
References System.IO.PathInternal.IsCaseSensitive, System.IO.Enumeration.FileSystemName.MatchesSimpleExpression(), System.IO.Enumeration.FileSystemName.MatchesWin32Expression(), and System.options.
Referenced by System.IO.Enumeration.FileSystemEnumerableFactory.DirectoryInfos(), System.IO.Enumeration.FileSystemEnumerableFactory.FileInfos(), System.IO.Enumeration.FileSystemEnumerableFactory.FileSystemInfos(), System.IO.Enumeration.FileSystemEnumerableFactory.UserDirectories(), System.IO.Enumeration.FileSystemEnumerableFactory.UserEntries(), and System.IO.Enumeration.FileSystemEnumerableFactory.UserFiles().