Terraria: System.Reflection.Metadata.BlobReader.GetCurrentPointerAndAdvance
GetCurrentPointerAndAdvance()
unsafe byte * System.Reflection.Metadata.BlobReader.GetCurrentPointerAndAdvance (int length) inline private
Definition at line 120 of file BlobReader.cs.
    {
        byte* currentPointer = _currentPointer;
        if ((uint)length > (uint)(_endPointer - currentPointer))
        {
            Throw.OutOfBounds();
        }
        _currentPointer = currentPointer + length;
        return currentPointer;
    }
References System.Reflection.Metadata.BlobReader._currentPointer, System.Reflection.Metadata.BlobReader._endPointer, System.length, and System.Reflection.Throw.OutOfBounds().
Referenced by System.Reflection.Metadata.BlobReader.ReadBytes(), System.Reflection.Metadata.BlobReader.ReadChar(), System.Reflection.Metadata.BlobReader.ReadDecimal(), System.Reflection.Metadata.BlobReader.ReadGuid(), System.Reflection.Metadata.BlobReader.ReadInt16(), System.Reflection.Metadata.BlobReader.ReadInt32(), System.Reflection.Metadata.BlobReader.ReadInt64(), System.Reflection.Metadata.BlobReader.ReadUInt16(), and System.Reflection.Metadata.BlobReader.ReadUInt32().