Terraria: System.Reflection.Metadata.BlobReader.ReadCompressedInteger
ReadCompressedInteger()
int System.Reflection.Metadata.BlobReader.ReadCompressedInteger () inline
Definition at line 303 of file BlobReader.cs.
    {
        if (!TryReadCompressedInteger(out var value))
        {
            Throw.InvalidCompressedInteger();
        }
        return value;
    }
References System.Reflection.Throw.InvalidCompressedInteger(), System.Reflection.Metadata.BlobReader.TryReadCompressedInteger(), and System.value.
Referenced by System.Reflection.Metadata.Ecma335.CustomAttributeDecoder< TType >.DecodeValue(), System.Reflection.Metadata.ImportDefinitionCollection.Enumerator.MoveNext(), System.Reflection.Metadata.SequencePointCollection.Enumerator.MoveNext(), System.Reflection.Metadata.BlobReader.ReadBlobHandle(), System.Reflection.Metadata.SequencePointCollection.Enumerator.ReadColumn(), System.Reflection.Metadata.SequencePointCollection.Enumerator.ReadDeltaLinesAndColumns(), System.Reflection.Metadata.SequencePointCollection.Enumerator.ReadDocumentHandle(), and System.Reflection.Metadata.SequencePointCollection.Enumerator.ReadLine().