Terraria: System.Reflection.Metadata.BlobReader.ReadCompressedSignedInteger
ReadCompressedSignedInteger()
int System.Reflection.Metadata.BlobReader.ReadCompressedSignedInteger () inline
Definition at line 340 of file BlobReader.cs.
    {
        if (!TryReadCompressedSignedInteger(out var value))
        {
            Throw.InvalidCompressedInteger();
        }
        return value;
    }
References System.Reflection.Throw.InvalidCompressedInteger(), System.Reflection.Metadata.BlobReader.TryReadCompressedSignedInteger(), and System.value.
Referenced by System.Reflection.Metadata.SequencePointCollection.Enumerator.MoveNext(), and System.Reflection.Metadata.SequencePointCollection.Enumerator.ReadDeltaLinesAndColumns().