Terraria: System.Reflection.Metadata.BlobReader.ReadConstant
ReadConstant()
object? System.Reflection.Metadata.BlobReader.ReadConstant (ConstantTypeCode typeCode) inline
Definition at line 402 of file BlobReader.cs.
    {
        switch (typeCode)
        {
        case ConstantTypeCode.Boolean:
            return ReadBoolean();
        case ConstantTypeCode.Char:
            return ReadChar();
        case ConstantTypeCode.SByte:
            return ReadSByte();
        case ConstantTypeCode.Int16:
            return ReadInt16();
        case ConstantTypeCode.Int32:
            return ReadInt32();
        case ConstantTypeCode.Int64:
            return ReadInt64();
        case ConstantTypeCode.Byte:
            return ReadByte();
        case ConstantTypeCode.UInt16:
            return ReadUInt16();
        case ConstantTypeCode.UInt32:
            return ReadUInt32();
        case ConstantTypeCode.UInt64:
            return ReadUInt64();
        case ConstantTypeCode.Single:
            return ReadSingle();
        case ConstantTypeCode.Double:
            return ReadDouble();
        case ConstantTypeCode.String:
            return ReadUTF16(RemainingBytes);
        case ConstantTypeCode.NullReference:
            if (ReadUInt32() != 0)
            {
                throw new BadImageFormatException(System.SR.InvalidConstantValue);
            }
            return null;
        default:
            throw new ArgumentOutOfRangeException("typeCode");
        }
    }
References System.SR.InvalidConstantValue, System.Reflection.Metadata.BlobReader.ReadBoolean(), System.Reflection.Metadata.BlobReader.ReadByte(), System.Reflection.Metadata.BlobReader.ReadChar(), System.Reflection.Metadata.BlobReader.ReadDouble(), System.Reflection.Metadata.BlobReader.ReadInt16(), System.Reflection.Metadata.BlobReader.ReadInt32(), System.Reflection.Metadata.BlobReader.ReadInt64(), System.Reflection.Metadata.BlobReader.ReadSByte(), System.Reflection.Metadata.BlobReader.ReadSingle(), System.Reflection.Metadata.BlobReader.ReadUInt16(), System.Reflection.Metadata.BlobReader.ReadUInt32(), System.Reflection.Metadata.BlobReader.ReadUInt64(), System.Reflection.Metadata.BlobReader.ReadUTF16(), and System.Reflection.Metadata.BlobReader.RemainingBytes.