Terraria: System.Xml.Linq.XProcessingInstruction.ValidateName
ValidateName()
static void System.Xml.Linq.XProcessingInstruction.ValidateName (string name) inline static private
Definition at line 122 of file XProcessingInstruction.cs.
    {
        XmlConvert.VerifyNCName(name);
        if (string.Equals(name, "xml", StringComparison.OrdinalIgnoreCase))
        {
            throw new ArgumentException(System.SR.Format(System.SR.Argument_InvalidPIName, name));
        }
    }
References System.SR.Argument_InvalidPIName, System.Xml.ArgumentException, System.SR.Format(), and System.Xml.XmlConvert.VerifyNCName().
Referenced by System.Xml.Linq.XProcessingInstruction.XProcessingInstruction().