Terraria: System.Data.ExprException.AggregateUnbound
AggregateUnbound()
static Exception System.Data.ExprException.AggregateUnbound (string expr) inline static
Definition at line 223 of file ExprException.cs.
    {
        return _Eval(System.SR.Format(System.SR.Expr_AggregateUnbound, expr));
    }
References System.Data.ExprException._Eval(), System.SR.Expr_AggregateUnbound, and System.SR.Format().
Referenced by System.Data.AggregateNode.Bind(), System.Data.AggregateNode.Eval(), and System.Data.AggregateNode.Eval().