Terraria: System.Data.ExprException.ArgumentTypeInteger
ArgumentTypeInteger()
static Exception System.Data.ExprException.ArgumentTypeInteger (string function, int arg) inline static
Definition at line 173 of file ExprException.cs.
    {
        return _Eval(System.SR.Format(System.SR.Expr_ArgumentTypeInteger, function, arg.ToString(CultureInfo.InvariantCulture)));
    }
References System.Data.ExprException._Eval(), System.SR.Expr_ArgumentTypeInteger, System.SR.Format(), and System.Globalization.CultureInfo.InvariantCulture.
Referenced by System.Data.FunctionNode.EvalFunction().