Terraria: System.Data.ExprException._Syntax
_Syntax()
static SyntaxErrorException System.Data.ExprException._Syntax (string error) inline static private
Definition at line 21 of file ExprException.cs.
    {
        SyntaxErrorException ex = new SyntaxErrorException(error);
        ExceptionBuilder.TraceExceptionAsReturnValue(ex);
        return ex;
    }
References System.Data.ExceptionBuilder.TraceExceptionAsReturnValue().
Referenced by System.Data.ExprException.AggregateArgument(), System.Data.ExprException.InvalidDate(), System.Data.ExprException.InvalidIsSyntax(), System.Data.ExprException.InvalidName(), System.Data.ExprException.InvalidNameBracketing(), System.Data.ExprException.InvalidString(), System.Data.ExprException.InWithoutList(), System.Data.ExprException.InWithoutParentheses(), System.Data.ExprException.LookupArgument(), System.Data.ExprException.MissingOperand(), System.Data.ExprException.MissingOperandBefore(), System.Data.ExprException.MissingOperator(), System.Data.ExprException.MissingRightParen(), System.Data.ExprException.SyntaxError(), System.Data.ExprException.TooManyRightParentheses(), System.Data.ExprException.UnknownToken(), and System.Data.ExprException.UnknownToken().