Terraria: System.Data.ExprException.UnresolvedRelation
UnresolvedRelation()
static Exception System.Data.ExprException.UnresolvedRelation (string name, string expr) inline static
Definition at line 208 of file ExprException.cs.
    {
        return _Eval(System.SR.Format(System.SR.Expr_UnresolvedRelation, name, expr));
    }
References System.Data.ExprException._Eval(), System.SR.Expr_UnresolvedRelation, and System.SR.Format().
Referenced by System.Data.AggregateNode.Bind(), and System.Data.LookupNode.Bind().