Terraria: System.Data.ExprException._Eval
_Eval() [1/2]
static EvaluateException System.Data.ExprException._Eval (string error) inline static private
Definition at line 28 of file ExprException.cs.
    {
        EvaluateException ex = new EvaluateException(error);
        ExceptionBuilder.TraceExceptionAsReturnValue(ex);
        return ex;
    }
References System.Data.ExceptionBuilder.TraceExceptionAsReturnValue().
Referenced by System.Data.ExprException.AggregateUnbound(), System.Data.ExprException.AmbiguousBinop(), System.Data.ExprException.ArgumentType(), System.Data.ExprException.ArgumentTypeInteger(), System.Data.ExprException.BindFailure(), System.Data.ExprException.ComputeNotAggregate(), System.Data.ExprException.DatatypeConvertion(), System.Data.ExprException.DatavalueConvertion(), System.Data.ExprException.EvalNoContext(), System.Data.ExprException.ExpressionTooComplex(), System.Data.ExprException.ExpressionUnbound(), System.Data.ExprException.FilterConvertion(), System.Data.ExprException.FunctionArgumentCount(), System.Data.ExprException.InvalidHoursArgument(), System.Data.ExprException.InvalidMinutesArgument(), System.Data.ExprException.InvalidPattern(), System.Data.ExprException.InvalidTimeZoneRange(), System.Data.ExprException.InvalidType(), System.Data.ExprException.MismatchKindandTimeSpan(), System.Data.ExprException.NonConstantArgument(), System.Data.ExprException.TypeMismatch(), System.Data.ExprException.TypeMismatchInBinop(), System.Data.ExprException.UnboundName(), System.Data.ExprException.UndefinedFunction(), System.Data.ExprException.UnresolvedRelation(), and System.Data.ExprException.UnsupportedOperator().