Terraria: System.Data.ExprException.Overflow
Overflow()
static Exception System.Data.ExprException.Overflow (Type type) inline static
Definition at line 163 of file ExprException.cs.
    {
        return _Overflow(System.SR.Format(System.SR.Expr_Overflow, type.Name));
    }
References System.Data.ExprException._Overflow(), System.SR.Expr_Overflow, System.SR.Format(), and System.type.
Referenced by System.Data.Common.SqlStringStorage.Aggregate(), System.Data.Common.BooleanStorage.Aggregate(), System.Data.Common.ByteStorage.Aggregate(), System.Data.Common.CharStorage.Aggregate(), System.Data.Common.DateTimeOffsetStorage.Aggregate(), System.Data.Common.DateTimeStorage.Aggregate(), System.Data.Common.DecimalStorage.Aggregate(), System.Data.Common.DoubleStorage.Aggregate(), System.Data.Common.Int16Storage.Aggregate(), System.Data.Common.Int32Storage.Aggregate(), System.Data.Common.Int64Storage.Aggregate(), System.Data.Common.SByteStorage.Aggregate(), System.Data.Common.SingleStorage.Aggregate(), System.Data.Common.SqlBinaryStorage.Aggregate(), System.Data.Common.SqlBooleanStorage.Aggregate(), System.Data.Common.SqlBytesStorage.Aggregate(), System.Data.Common.SqlByteStorage.Aggregate(), System.Data.Common.SqlCharsStorage.Aggregate(), System.Data.Common.SqlDateTimeStorage.Aggregate(), System.Data.Common.SqlDecimalStorage.Aggregate(), System.Data.Common.SqlDoubleStorage.Aggregate(), System.Data.Common.SqlGuidStorage.Aggregate(), System.Data.Common.SqlInt16Storage.Aggregate(), System.Data.Common.SqlInt32Storage.Aggregate(), System.Data.Common.SqlInt64Storage.Aggregate(), System.Data.Common.SqlMoneyStorage.Aggregate(), System.Data.Common.SqlSingleStorage.Aggregate(), System.Data.Common.TimeSpanStorage.Aggregate(), System.Data.Common.UInt16Storage.Aggregate(), System.Data.Common.UInt32Storage.Aggregate(), System.Data.Common.UInt64Storage.Aggregate(), and System.Data.BinaryNode.EvalBinaryOp().