Terraria: System.Buffers.Text.Utf8Formatter.TryFormatInt64
TryFormatInt64()
static bool System.Buffers.Text.Utf8Formatter.TryFormatInt64 (long value, ulong mask, Span< byte > destination, out int bytesWritten, StandardFormat format) inline static private
Definition at line 832 of file Utf8Formatter.cs.
    {
        if (format.IsDefault)
        {
            return TryFormatInt64Default(value, destination, out bytesWritten);
        }
        switch (format.Symbol)
        {
        case 'G':
        case 'g':
            if (format.HasPrecision)
            {
                throw new NotSupportedException(SR.Argument_GWithPrecisionNotSupported);
            }
            return TryFormatInt64D(value, format.Precision, destination, out bytesWritten);
        case 'D':
        case 'd':
            return TryFormatInt64D(value, format.Precision, destination, out bytesWritten);
        case 'N':
        case 'n':
            return TryFormatInt64N(value, format.Precision, destination, out bytesWritten);
        case 'x':
            return TryFormatUInt64X((ulong)value & mask, format.Precision, useLower: true, destination, out bytesWritten);
        case 'X':
            return TryFormatUInt64X((ulong)value & mask, format.Precision, useLower: false, destination, out bytesWritten);
        default:
            return FormattingHelpers.TryFormatThrowFormatException(out bytesWritten);
        }
    }
References System.SR.Argument_GWithPrecisionNotSupported, System.destination, System.format, System.Buffers.Text.Utf8Formatter.TryFormatInt64D(), System.Buffers.Text.Utf8Formatter.TryFormatInt64Default(), System.Buffers.Text.Utf8Formatter.TryFormatInt64N(), System.Buffers.Text.FormattingHelpers.TryFormatThrowFormatException(), System.Buffers.Text.Utf8Formatter.TryFormatUInt64X(), and System.value.
Referenced by System.Buffers.Text.Utf8Formatter.TryFormat(), System.Buffers.Text.Utf8Formatter.TryFormat(), System.Buffers.Text.Utf8Formatter.TryFormat(), and System.Buffers.Text.Utf8Formatter.TryFormat().