Terraria: System.Buffers.Text.Utf8Formatter.TryFormatUInt64D
TryFormatUInt64D()
static bool System.Buffers.Text.Utf8Formatter.TryFormatUInt64D (ulong value, byte precision, Span< byte > destination, bool insertNegationSign, out int bytesWritten) inline static private
Definition at line 948 of file Utf8Formatter.cs.
    {
        int num = FormattingHelpers.CountDigits(value);
        int num2 = ((precision != byte.MaxValue) ? precision : 0) - num;
        if (num2 < 0)
        {
            num2 = 0;
        }
        int num3 = num + num2;
        if (insertNegationSign)
        {
            num3++;
        }
        if (num3 > destination.Length)
        {
            bytesWritten = 0;
            return false;
        }
        bytesWritten = num3;
        if (insertNegationSign)
        {
            destination[0] = 45;
            destination = destination.Slice(1);
        }
        if (num2 > 0)
        {
            FormattingHelpers.FillWithAsciiZeros(destination.Slice(0, num2));
        }
        FormattingHelpers.WriteDigits(value, destination.Slice(num2, num));
        return true;
    }
References System.Buffers.Text.FormattingHelpers.CountDigits(), System.destination, System.Buffers.Text.FormattingHelpers.FillWithAsciiZeros(), System.value, and System.Buffers.Text.FormattingHelpers.WriteDigits().
Referenced by System.Buffers.Text.Utf8Formatter.TryFormatInt64D(), and System.Buffers.Text.Utf8Formatter.TryFormatUInt64().