Terraria: System.Buffers.Text.Utf8Formatter.TryFormat
TryFormat() [13/16]
static bool System.Buffers.Text.Utf8Formatter.TryFormat (TimeSpan value, Span< byte > destination, out int bytesWritten, StandardFormat format = default(StandardFormat)) inline static
Definition at line 1081 of file Utf8Formatter.cs.
    {
        char c = FormattingHelpers.GetSymbolOrDefault(in format, 'c');
        switch (c)
        {
        case 'T':
        case 't':
            c = 'c';
            break;
        default:
            return FormattingHelpers.TryFormatThrowFormatException(out bytesWritten);
        case 'G':
        case 'c':
        case 'g':
            break;
        }
        int num = 8;
        long ticks = value.Ticks;
        uint valueWithoutTrailingZeros;
        ulong num2;
        if (ticks < 0)
        {
            ticks = -ticks;
            if (ticks < 0)
            {
                valueWithoutTrailingZeros = 4775808u;
                num2 = 922337203685uL;
                goto IL_008d;
            }
        }
        (ulong Quotient, ulong Remainder) tuple = Math.DivRem((ulong)Math.Abs(value.Ticks), 10000000uL);
        num2 = tuple.Quotient;
        ulong item = tuple.Remainder;
        valueWithoutTrailingZeros = (uint)item;
        goto IL_008d;
        IL_008d:
        int num3 = 0;
        switch (c)
        {
        case 'c':
            if (valueWithoutTrailingZeros != 0)
            {
                num3 = 7;
            }
            break;
        case 'G':
            num3 = 7;
            break;
        default:
            if (valueWithoutTrailingZeros != 0)
            {
                num3 = 7 - FormattingHelpers.CountDecimalTrailingZeros(valueWithoutTrailingZeros, out valueWithoutTrailingZeros);
            }
            break;
        }
        if (num3 != 0)
        {
            num += num3 + 1;
        }
        ulong num4 = 0uL;
        ulong num5 = 0uL;
        if (num2 != 0)
        {
            (num4, num5) = Math.DivRem(num2, 60uL);
        }
        ulong num6 = 0uL;
        ulong num7 = 0uL;
        if (num4 != 0)
        {
            (num6, num7) = Math.DivRem(num4, 60uL);
        }
        uint num8 = 0u;
        uint num9 = 0u;
        if (num6 != 0)
        {
            (num8, num9) = Math.DivRem((uint)num6, 24u);
        }
        int num10 = 2;
        if (num9 < 10 && c == 'g')
        {
            num10--;
            num--;
        }
        int num11 = 0;
        if (num8 == 0)
        {
            if (c == 'G')
            {
                num += 2;
                num11 = 1;
            }
        }
        else
        {
            num11 = FormattingHelpers.CountDigits(num8);
            num += num11 + 1;
        }
        if (value.Ticks < 0)
        {
            num++;
        }
        if (destination.Length < num)
        {
            bytesWritten = 0;
            return false;
        }
        bytesWritten = num;
        int num12 = 0;
        if (value.Ticks < 0)
        {
            destination[num12++] = 45;
        }
        if (num11 > 0)
        {
            FormattingHelpers.WriteDigits(num8, destination.Slice(num12, num11));
            num12 += num11;
            destination[num12++] = (byte)((c == 'c') ? 46 : 58);
        }
        FormattingHelpers.WriteDigits(num9, destination.Slice(num12, num10));
        num12 += num10;
        destination[num12++] = 58;
        FormattingHelpers.WriteDigits((uint)num7, destination.Slice(num12, 2));
        num12 += 2;
        destination[num12++] = 58;
        FormattingHelpers.WriteDigits((uint)num5, destination.Slice(num12, 2));
        num12 += 2;
        if (num3 > 0)
        {
            destination[num12++] = 46;
            FormattingHelpers.WriteDigits(valueWithoutTrailingZeros, destination.Slice(num12, num3));
            num12 += num3;
        }
        return true;
    }
References System.Math.Abs(), System.Buffers.Text.FormattingHelpers.CountDecimalTrailingZeros(), System.Buffers.Text.FormattingHelpers.CountDigits(), System.destination, System.Math.DivRem(), System.format, System.Buffers.Text.FormattingHelpers.GetSymbolOrDefault(), System.item, System.Buffers.Text.FormattingHelpers.TryFormatThrowFormatException(), System.value, and System.Buffers.Text.FormattingHelpers.WriteDigits().