Terraria: System.Buffers.Text.Utf8Formatter.TryFormatDateTimeO
TryFormatDateTimeO()
static bool System.Buffers.Text.Utf8Formatter.TryFormatDateTimeO (DateTime value, TimeSpan offset, Span< byte > destination, out int bytesWritten) inline static private
Definition at line 262 of file Utf8Formatter.cs.
    {
        int num = 27;
        DateTimeKind dateTimeKind = DateTimeKind.Local;
        if (offset == Utf8Constants.NullUtcOffset)
        {
            dateTimeKind = value.Kind;
            switch (dateTimeKind)
            {
            case DateTimeKind.Local:
                offset = TimeZoneInfo.Local.GetUtcOffset(value);
                num += 6;
                break;
            case DateTimeKind.Utc:
                num++;
                break;
            }
        }
        else
        {
            num += 6;
        }
        if (destination.Length < num)
        {
            bytesWritten = 0;
            return false;
        }
        bytesWritten = num;
        _ = ref destination[26];
        value.GetDate(out var year, out var month, out var day);
        value.GetTimePrecise(out var hour, out var minute, out var second, out var tick);
        FormattingHelpers.WriteFourDecimalDigits((uint)year, destination);
        destination[4] = 45;
        FormattingHelpers.WriteTwoDecimalDigits((uint)month, destination, 5);
        destination[7] = 45;
        FormattingHelpers.WriteTwoDecimalDigits((uint)day, destination, 8);
        destination[10] = 84;
        FormattingHelpers.WriteTwoDecimalDigits((uint)hour, destination, 11);
        destination[13] = 58;
        FormattingHelpers.WriteTwoDecimalDigits((uint)minute, destination, 14);
        destination[16] = 58;
        FormattingHelpers.WriteTwoDecimalDigits((uint)second, destination, 17);
        destination[19] = 46;
        FormattingHelpers.WriteDigits((uint)tick, destination.Slice(20, 7));
        switch (dateTimeKind)
        {
        case DateTimeKind.Local:
        {
            int num2 = (int)(offset.Ticks / 600000000);
            byte b;
            if (num2 < 0)
            {
                b = 45;
                num2 = -num2;
            }
            else
            {
                b = 43;
            }
            int result;
            int value2 = Math.DivRem(num2, 60, out result);
            FormattingHelpers.WriteTwoDecimalDigits((uint)result, destination, 31);
            destination[30] = 58;
            FormattingHelpers.WriteTwoDecimalDigits((uint)value2, destination, 28);
            destination[27] = b;
            break;
        }
        case DateTimeKind.Utc:
            destination[27] = 90;
            break;
        }
        return true;
    }
References System.destination, System.Math.DivRem(), System.TimeZoneInfo.Local, System.Buffers.Text.Utf8Constants.NullUtcOffset, System.offset, System.value, System.Buffers.Text.FormattingHelpers.WriteDigits(), System.Buffers.Text.FormattingHelpers.WriteFourDecimalDigits(), System.Buffers.Text.FormattingHelpers.WriteTwoDecimalDigits(), and System.year.
Referenced by System.Buffers.Text.Utf8Formatter.TryFormat(), and System.Buffers.Text.Utf8Formatter.TryFormat().