Terraria: System.Buffers.Text.Utf8Formatter.TryFormatDateTimeG
TryFormatDateTimeG()
static bool System.Buffers.Text.Utf8Formatter.TryFormatDateTimeG (DateTime value, TimeSpan offset, Span< byte > destination, out int bytesWritten) inline static private
Definition at line 170 of file Utf8Formatter.cs.
    {
        int num = 19;
        if (offset != Utf8Constants.NullUtcOffset)
        {
            num += 7;
        }
        if (destination.Length < num)
        {
            bytesWritten = 0;
            return false;
        }
        bytesWritten = num;
        byte b = destination[18];
        value.GetDate(out var year, out var month, out var day);
        value.GetTime(out var hour, out var minute, out var second);
        FormattingHelpers.WriteTwoDecimalDigits((uint)month, destination);
        destination[2] = 47;
        FormattingHelpers.WriteTwoDecimalDigits((uint)day, destination, 3);
        destination[5] = 47;
        FormattingHelpers.WriteFourDecimalDigits((uint)year, destination, 6);
        destination[10] = 32;
        FormattingHelpers.WriteTwoDecimalDigits((uint)hour, destination, 11);
        destination[13] = 58;
        FormattingHelpers.WriteTwoDecimalDigits((uint)minute, destination, 14);
        destination[16] = 58;
        FormattingHelpers.WriteTwoDecimalDigits((uint)second, destination, 17);
        if (offset != Utf8Constants.NullUtcOffset)
        {
            int num2 = (int)(offset.Ticks / 600000000);
            byte b2;
            if (num2 < 0)
            {
                b2 = 45;
                num2 = -num2;
            }
            else
            {
                b2 = 43;
            }
            int result;
            int value2 = Math.DivRem(num2, 60, out result);
            FormattingHelpers.WriteTwoDecimalDigits((uint)result, destination, 24);
            destination[23] = 58;
            FormattingHelpers.WriteTwoDecimalDigits((uint)value2, destination, 21);
            destination[20] = b2;
            destination[19] = 32;
        }
        return true;
    }
References System.destination, System.Math.DivRem(), System.Buffers.Text.Utf8Constants.NullUtcOffset, System.offset, System.value, System.Buffers.Text.FormattingHelpers.WriteFourDecimalDigits(), System.Buffers.Text.FormattingHelpers.WriteTwoDecimalDigits(), and System.year.
Referenced by System.Buffers.Text.Utf8Formatter.TryFormat(), and System.Buffers.Text.Utf8Formatter.TryFormat().