Terraria: System.Buffers.Text.Utf8Formatter.TryFormat
TryFormat() [8/16]
static bool System.Buffers.Text.Utf8Formatter.TryFormat (Guid value, Span< byte > destination, out int bytesWritten, StandardFormat format = default(StandardFormat)) inline static
Definition at line 685 of file Utf8Formatter.cs.
    {
        int num;
        switch (FormattingHelpers.GetSymbolOrDefault(in format, 'D'))
        {
        case 'D':
            num = -2147483612;
            break;
        case 'B':
            num = -2139260122;
            break;
        case 'P':
            num = -2144786394;
            break;
        case 'N':
            num = 32;
            break;
        default:
            return FormattingHelpers.TryFormatThrowFormatException(out bytesWritten);
        }
        if ((byte)num > destination.Length)
        {
            bytesWritten = 0;
            return false;
        }
        bytesWritten = (byte)num;
        num >>= 8;
        if ((byte)num != 0)
        {
            destination[0] = (byte)num;
            destination = destination.Slice(1);
        }
        num >>= 8;
        DecomposedGuid decomposedGuid = default(DecomposedGuid);
        decomposedGuid.Guid = value;
        _ = ref destination[8];
        _ = BitConverter.IsLittleEndian;
        HexConverter.ToBytesBuffer(decomposedGuid.Byte03, destination, 0, HexConverter.Casing.Lower);
        HexConverter.ToBytesBuffer(decomposedGuid.Byte02, destination, 2, HexConverter.Casing.Lower);
        HexConverter.ToBytesBuffer(decomposedGuid.Byte01, destination, 4, HexConverter.Casing.Lower);
        HexConverter.ToBytesBuffer(decomposedGuid.Byte00, destination, 6, HexConverter.Casing.Lower);
        if (num < 0)
        {
            destination[8] = 45;
            destination = destination.Slice(9);
        }
        else
        {
            destination = destination.Slice(8);
        }
        _ = ref destination[4];
        _ = BitConverter.IsLittleEndian;
        HexConverter.ToBytesBuffer(decomposedGuid.Byte05, destination, 0, HexConverter.Casing.Lower);
        HexConverter.ToBytesBuffer(decomposedGuid.Byte04, destination, 2, HexConverter.Casing.Lower);
        if (num < 0)
        {
            destination[4] = 45;
            destination = destination.Slice(5);
        }
        else
        {
            destination = destination.Slice(4);
        }
        _ = ref destination[4];
        _ = BitConverter.IsLittleEndian;
        HexConverter.ToBytesBuffer(decomposedGuid.Byte07, destination, 0, HexConverter.Casing.Lower);
        HexConverter.ToBytesBuffer(decomposedGuid.Byte06, destination, 2, HexConverter.Casing.Lower);
        if (num < 0)
        {
            destination[4] = 45;
            destination = destination.Slice(5);
        }
        else
        {
            destination = destination.Slice(4);
        }
        _ = ref destination[4];
        HexConverter.ToBytesBuffer(decomposedGuid.Byte08, destination, 0, HexConverter.Casing.Lower);
        HexConverter.ToBytesBuffer(decomposedGuid.Byte09, destination, 2, HexConverter.Casing.Lower);
        if (num < 0)
        {
            destination[4] = 45;
            destination = destination.Slice(5);
        }
        else
        {
            destination = destination.Slice(4);
        }
        _ = ref destination[11];
        HexConverter.ToBytesBuffer(decomposedGuid.Byte10, destination, 0, HexConverter.Casing.Lower);
        HexConverter.ToBytesBuffer(decomposedGuid.Byte11, destination, 2, HexConverter.Casing.Lower);
        HexConverter.ToBytesBuffer(decomposedGuid.Byte12, destination, 4, HexConverter.Casing.Lower);
        HexConverter.ToBytesBuffer(decomposedGuid.Byte13, destination, 6, HexConverter.Casing.Lower);
        HexConverter.ToBytesBuffer(decomposedGuid.Byte14, destination, 8, HexConverter.Casing.Lower);
        HexConverter.ToBytesBuffer(decomposedGuid.Byte15, destination, 10, HexConverter.Casing.Lower);
        if ((byte)num != 0)
        {
            destination[12] = (byte)num;
        }
        return true;
    }
References System.Buffers.Text.Utf8Formatter.DecomposedGuid.Byte00, System.Buffers.Text.Utf8Formatter.DecomposedGuid.Byte01, System.Buffers.Text.Utf8Formatter.DecomposedGuid.Byte02, System.Buffers.Text.Utf8Formatter.DecomposedGuid.Byte03, System.Buffers.Text.Utf8Formatter.DecomposedGuid.Byte04, System.Buffers.Text.Utf8Formatter.DecomposedGuid.Byte05, System.Buffers.Text.Utf8Formatter.DecomposedGuid.Byte06, System.Buffers.Text.Utf8Formatter.DecomposedGuid.Byte07, System.Buffers.Text.Utf8Formatter.DecomposedGuid.Byte08, System.Buffers.Text.Utf8Formatter.DecomposedGuid.Byte09, System.Buffers.Text.Utf8Formatter.DecomposedGuid.Byte10, System.Buffers.Text.Utf8Formatter.DecomposedGuid.Byte11, System.Buffers.Text.Utf8Formatter.DecomposedGuid.Byte12, System.Buffers.Text.Utf8Formatter.DecomposedGuid.Byte13, System.Buffers.Text.Utf8Formatter.DecomposedGuid.Byte14, System.Buffers.Text.Utf8Formatter.DecomposedGuid.Byte15, System.destination, System.format, System.Buffers.Text.FormattingHelpers.GetSymbolOrDefault(), System.BitConverter.IsLittleEndian, System.HexConverter.ToBytesBuffer(), System.Buffers.Text.FormattingHelpers.TryFormatThrowFormatException(), and System.value.