Terraria: System.Buffers.Text.Utf8Formatter.TryFormatInt64Default
TryFormatInt64Default()
static bool System.Buffers.Text.Utf8Formatter.TryFormatInt64Default (long value, Span< byte > destination, out int bytesWritten) inline static private
Definition at line 875 of file Utf8Formatter.cs.
    {
        if ((ulong)value < 10uL)
        {
            return TryFormatUInt32SingleDigit((uint)value, destination, out bytesWritten);
        }
        _ = IntPtr.Size;
        return TryFormatInt64MultipleDigits(value, destination, out bytesWritten);
    }
References System.destination, System.IntPtr.Size, System.Buffers.Text.Utf8Formatter.TryFormatInt64MultipleDigits(), System.Buffers.Text.Utf8Formatter.TryFormatUInt32SingleDigit(), and System.value.
Referenced by System.Buffers.Text.Utf8Formatter.TryFormatInt64().