Terraria: System.Buffers.Text.Utf8Formatter.TryFormatInt64MultipleDigits
TryFormatInt64MultipleDigits()
static bool System.Buffers.Text.Utf8Formatter.TryFormatInt64MultipleDigits (long value, Span< byte > destination, out int bytesWritten) inline static private
Definition at line 886 of file Utf8Formatter.cs.
    {
        if (value < 0)
        {
            value = -value;
            int num = FormattingHelpers.CountDigits((ulong)value);
            if (num >= destination.Length)
            {
                bytesWritten = 0;
                return false;
            }
            destination[0] = 45;
            bytesWritten = num + 1;
            FormattingHelpers.WriteDigits((ulong)value, destination.Slice(1, num));
            return true;
        }
        return TryFormatUInt64MultipleDigits((ulong)value, destination, out bytesWritten);
    }
References System.Buffers.Text.FormattingHelpers.CountDigits(), System.destination, System.Buffers.Text.Utf8Formatter.TryFormatUInt64MultipleDigits(), System.value, and System.Buffers.Text.FormattingHelpers.WriteDigits().
Referenced by System.Buffers.Text.Utf8Formatter.TryFormatInt64Default().