Terraria: System.Buffers.Text.Utf8Formatter.TryFormatUInt64
TryFormatUInt64()
static bool System.Buffers.Text.Utf8Formatter.TryFormatUInt64 (ulong value, Span< byte > destination, out int bytesWritten, StandardFormat format) inline static private
Definition at line 918 of file Utf8Formatter.cs.
    {
        if (format.IsDefault)
        {
            return TryFormatUInt64Default(value, destination, out bytesWritten);
        }
        switch (format.Symbol)
        {
        case 'G':
        case 'g':
            if (format.HasPrecision)
            {
                throw new NotSupportedException(SR.Argument_GWithPrecisionNotSupported);
            }
            return TryFormatUInt64D(value, format.Precision, destination, insertNegationSign: false, out bytesWritten);
        case 'D':
        case 'd':
            return TryFormatUInt64D(value, format.Precision, destination, insertNegationSign: false, out bytesWritten);
        case 'N':
        case 'n':
            return TryFormatUInt64N(value, format.Precision, destination, insertNegationSign: false, out bytesWritten);
        case 'x':
            return TryFormatUInt64X(value, format.Precision, useLower: true, destination, out bytesWritten);
        case 'X':
            return TryFormatUInt64X(value, format.Precision, useLower: false, destination, out bytesWritten);
        default:
            return FormattingHelpers.TryFormatThrowFormatException(out bytesWritten);
        }
    }
References System.SR.Argument_GWithPrecisionNotSupported, System.destination, System.format, System.Buffers.Text.FormattingHelpers.TryFormatThrowFormatException(), System.Buffers.Text.Utf8Formatter.TryFormatUInt64D(), System.Buffers.Text.Utf8Formatter.TryFormatUInt64Default(), System.Buffers.Text.Utf8Formatter.TryFormatUInt64N(), System.Buffers.Text.Utf8Formatter.TryFormatUInt64X(), and System.value.
Referenced by System.Buffers.Text.Utf8Formatter.TryFormat(), System.Buffers.Text.Utf8Formatter.TryFormat(), System.Buffers.Text.Utf8Formatter.TryFormat(), and System.Buffers.Text.Utf8Formatter.TryFormat().