Terraria: System.Buffers.Text.Utf8Formatter.TryFormatUInt64X
TryFormatUInt64X()
static bool System.Buffers.Text.Utf8Formatter.TryFormatUInt64X (ulong value, byte precision, bool useLower, Span< byte > destination, out int bytesWritten) inline static private
Definition at line 1052 of file Utf8Formatter.cs.
    {
        int num = FormattingHelpers.CountHexDigits(value);
        int num2 = ((precision == byte.MaxValue) ? num : Math.Max(precision, num));
        if (destination.Length < num2)
        {
            bytesWritten = 0;
            return false;
        }
        bytesWritten = num2;
        if (useLower)
        {
            while ((uint)(--num2) < (uint)destination.Length)
            {
                destination[num2] = (byte)HexConverter.ToCharLower((int)value);
                value >>= 4;
            }
        }
        else
        {
            while ((uint)(--num2) < (uint)destination.Length)
            {
                destination[num2] = (byte)HexConverter.ToCharUpper((int)value);
                value >>= 4;
            }
        }
        return true;
    }
References System.Buffers.Text.FormattingHelpers.CountHexDigits(), System.destination, System.Math.Max(), System.HexConverter.ToCharLower(), System.HexConverter.ToCharUpper(), and System.value.
Referenced by System.Buffers.Text.Utf8Formatter.TryFormatInt64(), and System.Buffers.Text.Utf8Formatter.TryFormatUInt64().