Terraria: System.Buffers.Text.Utf8Formatter.TryFormat
TryFormat() [1/16]
static bool System.Buffers.Text.Utf8Formatter.TryFormat (bool value, Span< byte > destination, out int bytesWritten, StandardFormat format = default(StandardFormat)) inline static
Definition at line 82 of file Utf8Formatter.cs.
    {
        char symbolOrDefault = FormattingHelpers.GetSymbolOrDefault(in format, 'G');
        if (value)
        {
            if (symbolOrDefault == 'G')
            {
                if (BinaryPrimitives.TryWriteUInt32BigEndian(destination, 1416787301u))
                {
                    goto IL_0033;
                }
            }
            else
            {
                if (symbolOrDefault != 'l')
                {
                    goto IL_0083;
                }
                if (BinaryPrimitives.TryWriteUInt32BigEndian(destination, 1953658213u))
                {
                    goto IL_0033;
                }
            }
        }
        else if (symbolOrDefault == 'G')
        {
            if (4u < (uint)destination.Length)
            {
                BinaryPrimitives.WriteUInt32BigEndian(destination, 1180789875u);
                goto IL_006e;
            }
        }
        else
        {
            if (symbolOrDefault != 'l')
            {
                goto IL_0083;
            }
            if (4u < (uint)destination.Length)
            {
                BinaryPrimitives.WriteUInt32BigEndian(destination, 1717660787u);
                goto IL_006e;
            }
        }
        bytesWritten = 0;
        return false;
        IL_006e:
        destination[4] = 101;
        bytesWritten = 5;
        return true;
        IL_0083:
        return FormattingHelpers.TryFormatThrowFormatException(out bytesWritten);
        IL_0033:
        bytesWritten = 4;
        return true;
    }
References System.destination, System.format, System.Buffers.Text.FormattingHelpers.GetSymbolOrDefault(), System.Buffers.Text.FormattingHelpers.TryFormatThrowFormatException(), System.Buffers.Binary.BinaryPrimitives.TryWriteUInt32BigEndian(), System.value, and System.Buffers.Binary.BinaryPrimitives.WriteUInt32BigEndian().
Referenced by System.Text.Json.JsonWriterHelper.EscapeNextBytes(), System.Text.Json.Utf8JsonWriter.TryFormatDouble(), System.Text.Json.Utf8JsonWriter.TryFormatSingle(), System.Text.Json.Serialization.Converters.TimeSpanConverter.Write(), System.Text.Json.JsonWriterHelper.WriteDateTimeOffsetTrimmed(), System.Text.Json.JsonWriterHelper.WriteDateTimeTrimmed(), System.Net.Http.HttpConnection.WriteDecimalInt32Async(), System.Formats.Asn1.AsnWriter.WriteGeneralizedTimeCore(), System.Net.Http.HttpConnection.WriteHexInt32Async(), System.Text.Json.Utf8JsonWriter.WriteNumberIndented(), System.Text.Json.Utf8JsonWriter.WriteNumberIndented(), System.Text.Json.Utf8JsonWriter.WriteNumberIndented(), System.Text.Json.Utf8JsonWriter.WriteNumberIndented(), System.Text.Json.Utf8JsonWriter.WriteNumberIndented(), System.Text.Json.Utf8JsonWriter.WriteNumberIndented(), System.Text.Json.Utf8JsonWriter.WriteNumberMinimized(), System.Text.Json.Utf8JsonWriter.WriteNumberMinimized(), System.Text.Json.Utf8JsonWriter.WriteNumberMinimized(), System.Text.Json.Utf8JsonWriter.WriteNumberMinimized(), System.Text.Json.Utf8JsonWriter.WriteNumberMinimized(), System.Text.Json.Utf8JsonWriter.WriteNumberMinimized(), System.Text.Json.Utf8JsonWriter.WriteNumberValueAsString(), System.Text.Json.Utf8JsonWriter.WriteNumberValueAsString(), System.Text.Json.Utf8JsonWriter.WriteNumberValueAsString(), System.Text.Json.Utf8JsonWriter.WriteNumberValueIndented(), System.Text.Json.Utf8JsonWriter.WriteNumberValueIndented(), System.Text.Json.Utf8JsonWriter.WriteNumberValueIndented(), System.Text.Json.Utf8JsonWriter.WriteNumberValueMinimized(), System.Text.Json.Utf8JsonWriter.WriteNumberValueMinimized(), System.Text.Json.Utf8JsonWriter.WriteNumberValueMinimized(), System.Text.Json.Utf8JsonWriter.WritePropertyName(), System.Text.Json.Utf8JsonWriter.WritePropertyName(), System.Text.Json.Utf8JsonWriter.WritePropertyName(), System.Text.Json.Utf8JsonWriter.WritePropertyName(), System.Text.Json.Utf8JsonWriter.WritePropertyName(), System.Text.Json.Utf8JsonWriter.WriteStringIndented(), System.Text.Json.Utf8JsonWriter.WriteStringIndented(), System.Text.Json.Utf8JsonWriter.WriteStringMinimized(), System.Text.Json.Utf8JsonWriter.WriteStringMinimized(), System.Text.Json.Utf8JsonWriter.WriteStringValueIndented(), System.Text.Json.Utf8JsonWriter.WriteStringValueMinimized(), and System.Formats.Asn1.AsnWriter.WriteUtcTimeCore().