Terraria: System.Buffers.Text.Utf8Formatter.TryFormatDateTimeL
TryFormatDateTimeL()
static bool System.Buffers.Text.Utf8Formatter.TryFormatDateTimeL (DateTime value, Span< byte > destination, out int bytesWritten) inline static private
Definition at line 221 of file Utf8Formatter.cs.
    {
        if (28u >= (uint)destination.Length)
        {
            bytesWritten = 0;
            return false;
        }
        value.GetDate(out var year, out var month, out var day);
        value.GetTime(out var hour, out var minute, out var second);
        uint num = s_dayAbbreviationsLowercase[(int)value.DayOfWeek];
        destination[0] = (byte)num;
        num >>= 8;
        destination[1] = (byte)num;
        num >>= 8;
        destination[2] = (byte)num;
        destination[3] = 44;
        destination[4] = 32;
        FormattingHelpers.WriteTwoDecimalDigits((uint)day, destination, 5);
        destination[7] = 32;
        uint num2 = s_monthAbbreviationsLowercase[month - 1];
        destination[8] = (byte)num2;
        num2 >>= 8;
        destination[9] = (byte)num2;
        num2 >>= 8;
        destination[10] = (byte)num2;
        destination[11] = 32;
        FormattingHelpers.WriteFourDecimalDigits((uint)year, destination, 12);
        destination[16] = 32;
        FormattingHelpers.WriteTwoDecimalDigits((uint)hour, destination, 17);
        destination[19] = 58;
        FormattingHelpers.WriteTwoDecimalDigits((uint)minute, destination, 20);
        destination[22] = 58;
        FormattingHelpers.WriteTwoDecimalDigits((uint)second, destination, 23);
        destination[25] = 32;
        destination[26] = 103;
        destination[27] = 109;
        destination[28] = 116;
        bytesWritten = 29;
        return true;
    }
References System.destination, System.Buffers.Text.Utf8Formatter.s_dayAbbreviationsLowercase, System.Buffers.Text.Utf8Formatter.s_monthAbbreviationsLowercase, System.value, System.Buffers.Text.FormattingHelpers.WriteFourDecimalDigits(), System.Buffers.Text.FormattingHelpers.WriteTwoDecimalDigits(), and System.year.
Referenced by System.Buffers.Text.Utf8Formatter.TryFormat(), and System.Buffers.Text.Utf8Formatter.TryFormat().