Terraria: Microsoft.Win32.SafeHandles.SafeHandleCache.GetInvalidHandle
GetInvalidHandle() [2/2]
static T Microsoft.Win32.SafeHandles.SafeHandleCache< T >.GetInvalidHandle (Func< T > invalidHandleFactory) inline static package
Definition at line 11 of file SafeHandleCache.cs.
    {
        T val = Volatile.Read(ref s_invalidHandle);
        if (val == null)
        {
            T val2 = invalidHandleFactory();
            val = Interlocked.CompareExchange(ref s_invalidHandle, val2, null);
            if (val == null)
            {
                GC.SuppressFinalize(val2);
                val = val2;
            }
            else
            {
                val2.Dispose();
            }
        }
        return val;
    }
References System.Threading.Interlocked.CompareExchange(), System.Threading.Volatile.Read(), Microsoft.Win32.SafeHandles.SafeHandleCache< T >.s_invalidHandle, and System.GC.SuppressFinalize().