Terraria: System.IO.UnmanagedMemoryAccessor.Write
Write() [10/13]
unsafe void System.IO.UnmanagedMemoryAccessor.Write (long position, short value) inline inherited
Definition at line 382 of file UnmanagedMemoryAccessor.cs.
    {
        EnsureSafeToWrite(position, 2);
        byte* pointer = null;
        try
        {
            _buffer.AcquirePointer(ref pointer);
            Unsafe.WriteUnaligned(pointer + _offset + position, value);
        }
        finally
        {
            if (pointer != null)
            {
                _buffer.ReleasePointer();
            }
        }
    }
References System.IO.UnmanagedMemoryAccessor._buffer, System.IO.UnmanagedMemoryAccessor._offset, System.Runtime.InteropServices.SafeBuffer.AcquirePointer(), System.IO.UnmanagedMemoryAccessor.EnsureSafeToWrite(), System.pointer, System.Runtime.InteropServices.SafeBuffer.ReleasePointer(), and System.value.