Terraria: System.IO.UnmanagedMemoryAccessor.ReadInt64
ReadInt64()
unsafe long System.IO.UnmanagedMemoryAccessor.ReadInt64 (long position) inline inherited
Definition at line 190 of file UnmanagedMemoryAccessor.cs.
    {
        EnsureSafeToRead(position, 8);
        byte* pointer = null;
        try
        {
            _buffer.AcquirePointer(ref pointer);
            return Unsafe.ReadUnaligned<long>(pointer + _offset + position);
        }
        finally
        {
            if (pointer != null)
            {
                _buffer.ReleasePointer();
            }
        }
    }
References System.IO.UnmanagedMemoryAccessor._buffer, System.IO.UnmanagedMemoryAccessor._offset, System.Runtime.InteropServices.SafeBuffer.AcquirePointer(), System.IO.UnmanagedMemoryAccessor.EnsureSafeToRead(), System.pointer, and System.Runtime.InteropServices.SafeBuffer.ReleasePointer().
Referenced by System.IO.UnmanagedMemoryAccessor.ReadDouble(), and System.IO.UnmanagedMemoryAccessor.ReadUInt64().