Terraria: Terraria.DataStructures.EntryFilterer.ToggleFilter
ToggleFilter()
void Terraria.DataStructures.EntryFilterer< T, U >.ToggleFilter (int filterIndex) inline
Definition at line 57 of file EntryFilterer.cs.
    {
        U item = AvailableFilters[filterIndex];
        if (ActiveFilters.Contains(item))
        {
            ActiveFilters.Remove(item);
        }
        else
        {
            ActiveFilters.Add(item);
        }
    }
References Terraria.DataStructures.EntryFilterer< T, U >.ActiveFilters, System.Collections.Generic.List< T >.Add(), Terraria.DataStructures.EntryFilterer< T, U >.AvailableFilters, System.Collections.Generic.List< T >.Contains(), and System.Collections.Generic.List< T >.Remove().
Referenced by Terraria.GameContent.UI.Elements.UIBestiaryFilteringOptionsGrid.ClickOption().