Terraria: System.IO.UnmanagedMemoryAccessor.EnsureSafeToWrite
EnsureSafeToWrite()
void System.IO.UnmanagedMemoryAccessor.EnsureSafeToWrite (long position, int sizeOfType) inline private inherited
Definition at line 581 of file UnmanagedMemoryAccessor.cs.
    {
        if (!_isOpen)
        {
            throw new ObjectDisposedException("UnmanagedMemoryAccessor", SR.ObjectDisposed_ViewAccessorClosed);
        }
        if (!_canWrite)
        {
            throw new NotSupportedException(SR.NotSupported_Writing);
        }
        if (position < 0)
        {
            throw new ArgumentOutOfRangeException("position", SR.ArgumentOutOfRange_NeedNonNegNum);
        }
        if (position > _capacity - sizeOfType)
        {
            if (position >= _capacity)
            {
                throw new ArgumentOutOfRangeException("position", SR.ArgumentOutOfRange_PositionLessThanCapacityRequired);
            }
            throw new ArgumentException(SR.Argument_NotEnoughBytesToWrite, "position");
        }
    }
References System.IO.UnmanagedMemoryAccessor._canWrite, System.IO.UnmanagedMemoryAccessor._capacity, System.IO.UnmanagedMemoryAccessor._isOpen, System.SR.Argument_NotEnoughBytesToWrite, System.SR.ArgumentOutOfRange_NeedNonNegNum, System.SR.ArgumentOutOfRange_PositionLessThanCapacityRequired, System.SR.NotSupported_Writing, and System.SR.ObjectDisposed_ViewAccessorClosed.
Referenced by System.IO.UnmanagedMemoryAccessor.Write(), System.IO.UnmanagedMemoryAccessor.Write(), System.IO.UnmanagedMemoryAccessor.Write(), System.IO.UnmanagedMemoryAccessor.Write(), and System.IO.UnmanagedMemoryAccessor.Write().