Terraria: System.IO.UnmanagedMemoryAccessor.Initialize
Initialize()
unsafe void System.IO.UnmanagedMemoryAccessor.Initialize (SafeBuffer buffer, long offset, long capacity, FileAccess access) inline protected inherited
Definition at line 64 of file UnmanagedMemoryAccessor.cs.
    {
        if (buffer == null)
        {
            throw new ArgumentNullException("buffer");
        }
        if (offset < 0)
        {
            throw new ArgumentOutOfRangeException("offset", SR.ArgumentOutOfRange_NeedNonNegNum);
        }
        if (capacity < 0)
        {
            throw new ArgumentOutOfRangeException("capacity", SR.ArgumentOutOfRange_NeedNonNegNum);
        }
        if (buffer.ByteLength < (ulong)(offset + capacity))
        {
            throw new ArgumentException(SR.Argument_OffsetAndCapacityOutOfBounds);
        }
        if (access < FileAccess.Read || access > FileAccess.ReadWrite)
        {
            throw new ArgumentOutOfRangeException("access");
        }
        if (_isOpen)
        {
            throw new InvalidOperationException(SR.InvalidOperation_CalledTwice);
        }
        byte* pointer = null;
        try
        {
            buffer.AcquirePointer(ref pointer);
            if ((nuint)((long)pointer + offset + capacity) < (nuint)pointer)
            {
                throw new ArgumentException(SR.Argument_UnmanagedMemAccessorWrapAround);
            }
        }
        finally
        {
            if (pointer != null)
            {
                buffer.ReleasePointer();
            }
        }
        _offset = offset;
        _buffer = buffer;
        _capacity = capacity;
        _access = access;
        _isOpen = true;
        _canRead = (_access & FileAccess.Read) != 0;
        _canWrite = (_access & FileAccess.Write) != 0;
    }
References System.IO.UnmanagedMemoryAccessor._access, System.IO.UnmanagedMemoryAccessor._buffer, System.IO.UnmanagedMemoryAccessor._canRead, System.IO.UnmanagedMemoryAccessor._canWrite, System.IO.UnmanagedMemoryAccessor._capacity, System.IO.UnmanagedMemoryAccessor._isOpen, System.IO.UnmanagedMemoryAccessor._offset, System.SR.Argument_OffsetAndCapacityOutOfBounds, System.SR.Argument_UnmanagedMemAccessorWrapAround, System.SR.ArgumentOutOfRange_NeedNonNegNum, System.buffer, System.capacity, System.SR.InvalidOperation_CalledTwice, System.offset, and System.pointer.
Referenced by System.IO.MemoryMappedFiles.MemoryMappedViewAccessor.MemoryMappedViewAccessor(), System.IO.UnmanagedMemoryAccessor.UnmanagedMemoryAccessor(), and System.IO.UnmanagedMemoryAccessor.UnmanagedMemoryAccessor().