Terraria: System.IO.UnmanagedMemoryAccessor.EnsureSafeToRead
EnsureSafeToRead()
void System.IO.UnmanagedMemoryAccessor.EnsureSafeToRead (long position, int sizeOfType) inline private inherited
Definition at line 557 of file UnmanagedMemoryAccessor.cs.
    {
        if (!_isOpen)
        {
            throw new ObjectDisposedException("UnmanagedMemoryAccessor", SR.ObjectDisposed_ViewAccessorClosed);
        }
        if (!_canRead)
        {
            throw new NotSupportedException(SR.NotSupported_Reading);
        }
        if (position < 0)
        {
            throw new ArgumentOutOfRangeException("position", SR.ArgumentOutOfRange_NeedNonNegNum);
        }
        if (position > _capacity - sizeOfType)
        {
            if (position >= _capacity)
            {
                throw new ArgumentOutOfRangeException("position", SR.ArgumentOutOfRange_PositionLessThanCapacityRequired);
            }
            throw new ArgumentException(SR.Argument_NotEnoughBytesToRead, "position");
        }
    }
References System.IO.UnmanagedMemoryAccessor._canRead, System.IO.UnmanagedMemoryAccessor._capacity, System.IO.UnmanagedMemoryAccessor._isOpen, System.SR.Argument_NotEnoughBytesToRead, System.SR.ArgumentOutOfRange_NeedNonNegNum, System.SR.ArgumentOutOfRange_PositionLessThanCapacityRequired, System.SR.NotSupported_Reading, and System.SR.ObjectDisposed_ViewAccessorClosed.
Referenced by System.IO.UnmanagedMemoryAccessor.ReadByte(), System.IO.UnmanagedMemoryAccessor.ReadDecimal(), System.IO.UnmanagedMemoryAccessor.ReadInt16(), System.IO.UnmanagedMemoryAccessor.ReadInt32(), and System.IO.UnmanagedMemoryAccessor.ReadInt64().