Terraria: Terraria.Social.WeGame.CloudSocialModule.ioLock
ioLock
object Terraria.Social.WeGame.CloudSocialModule.ioLock = new object() private
Referenced by Terraria.Social.WeGame.CloudSocialModule.Delete(), Terraria.Social.WeGame.CloudSocialModule.GetFiles(), Terraria.Social.WeGame.CloudSocialModule.GetFileSize(), Terraria.Social.WeGame.CloudSocialModule.HasFile(), Terraria.Social.WeGame.CloudSocialModule.Read(), and Terraria.Social.WeGame.CloudSocialModule.Write().