Terraria: System.Runtime.Serialization.ScopedKnownTypes.Push
Push()
void System.Runtime.Serialization.ScopedKnownTypes.Push (Dictionary< XmlQualifiedName, DataContract > dataContractDictionary) inline package
Definition at line 12 of file ScopedKnownTypes.cs.
    {
        if (dataContractDictionaries == null)
        {
            dataContractDictionaries = new Dictionary<XmlQualifiedName, DataContract>[4];
        }
        else if (_count == dataContractDictionaries.Length)
        {
            Array.Resize(ref dataContractDictionaries, dataContractDictionaries.Length * 2);
        }
        dataContractDictionaries[_count++] = dataContractDictionary;
    }
References System.Runtime.Serialization.ScopedKnownTypes._count, System.Runtime.Serialization.ScopedKnownTypes.dataContractDictionaries, and System.Runtime.Serialization.Dictionary.
Referenced by System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(), System.Runtime.Serialization.XmlObjectSerializerContext.IsKnownType(), System.Runtime.Serialization.Json.JsonDataContract.PushKnownDataContracts(), System.Runtime.Serialization.XmlObjectSerializerContext.PushKnownTypes(), System.Runtime.Serialization.XmlObjectSerializerReadContext.ReplaceScopedKnownTypesTop(), System.Runtime.Serialization.XmlObjectSerializerWriteContext.SerializeAndVerifyType(), System.Runtime.Serialization.XmlObjectSerializerWriteContext.SerializeWithoutXsiType(), and System.Runtime.Serialization.Json.XmlObjectSerializerWriteContextComplexJson.VerifyType().