Terraria: System.Transactions.DependentTransaction.Complete
Complete()
void System.Transactions.DependentTransaction.Complete () inline
Definition at line 24 of file DependentTransaction.cs.
    {
        TransactionsEtwProvider log = TransactionsEtwProvider.Log;
        if (log.IsEnabled())
        {
            log.MethodEnter(TraceSourceType.TraceSourceLtm, this, "Complete");
        }
        lock (_internalTransaction)
        {
            if (base.Disposed)
            {
                throw new ObjectDisposedException("DependentTransaction");
            }
            if (_complete)
            {
                throw TransactionException.CreateTransactionCompletedException(base.DistributedTxId);
            }
            _complete = true;
            if (_blocking)
            {
                _internalTransaction.State.CompleteBlockingClone(_internalTransaction);
            }
            else
            {
                _internalTransaction.State.CompleteAbortingClone(_internalTransaction);
            }
        }
        if (log.IsEnabled())
        {
            log.TransactionDependentCloneComplete(this, "DependentTransaction");
            log.MethodExit(TraceSourceType.TraceSourceLtm, this, "Complete");
        }
    }
References System.Transactions.DependentTransaction._blocking, System.Transactions.Transaction._complete, System.Transactions.Transaction._internalTransaction, System.Transactions.TransactionState.CompleteAbortingClone(), System.Transactions.TransactionState.CompleteBlockingClone(), System.Transactions.TransactionException.CreateTransactionCompletedException(), System.Diagnostics.Tracing.EventSource.IsEnabled(), System.Transactions.TransactionsEtwProvider.Log, System.Transactions.TransactionsEtwProvider.MethodEnter(), System.Transactions.TransactionsEtwProvider.MethodExit(), System.Transactions.InternalTransaction.State, and System.Transactions.TransactionsEtwProvider.TransactionDependentCloneComplete().
Referenced by System.Transactions.TransactionScope.InternalDispose().