Terraria: TilePaintSystemV2.TryGetTileAndRequestIfNotReady
TryGetTileAndRequestIfNotReady()
Texture2D TilePaintSystemV2.TryGetTileAndRequestIfNotReady (int tileType, int tileStyle, int paintColor) inline
     {
         TileVariationkey tileVariationkey = default(TileVariationkey);
         tileVariationkey.TileType = tileType;
         tileVariationkey.TileStyle = tileStyle;
         tileVariationkey.PaintColor = paintColor;
         TileVariationkey lookupKey = tileVariationkey;
         if (_tilesRenders.TryGetValue(lookupKey, out var value) && value.IsReady)
         {
             return value.Target;
         }
         RequestTile(ref lookupKey);
         return null;
     }
References _tilesRenders, TilePaintSystemV2.TileVariationkey.PaintColor, RequestTile(), TilePaintSystemV2.TileVariationkey.TileStyle, and TilePaintSystemV2.TileVariationkey.TileType.
Referenced by HitTile.DrawFreshAnimations(), and TileDrawing.GetTileDrawTexture().