Terraria: System.Xml.Schema.SymbolsDictionary.AddWildcard
AddWildcard()
void System.Xml.Schema.SymbolsDictionary.AddWildcard (string wildcard, object particle) inline private
Definition at line 102 of file SymbolsDictionary.cs.
    {
        if (_wildcards == null)
        {
            _wildcards = new Hashtable();
        }
        object obj = _wildcards[wildcard];
        if (obj == null)
        {
            _wildcards.Add(wildcard, _last);
            _particles.Add(particle);
            _last++;
        }
        else if (particle != null)
        {
            _particles[(int)obj] = particle;
        }
    }
References System.Xml.Schema.SymbolsDictionary._last, System.Xml.Schema.SymbolsDictionary._particles, System.Xml.Schema.SymbolsDictionary._wildcards, System.Collections.Hashtable.Add(), System.Collections.ArrayList.Add(), System.Xml.Dictionary, and System.obj.
Referenced by System.Xml.Schema.SymbolsDictionary.AddNamespaceList().