Terraria: System.Xml.Schema.SymbolsDictionary.NameOf
NameOf()
string System.Xml.Schema.SymbolsDictionary.NameOf (int symbol) inline
Definition at line 167 of file SymbolsDictionary.cs.
    {
        foreach (DictionaryEntry name in _names)
        {
            if ((int)name.Value == symbol)
            {
                return ((XmlQualifiedName)name.Key).ToString();
            }
        }
        if (_wildcards != null)
        {
            foreach (DictionaryEntry wildcard in _wildcards)
            {
                if ((int)wildcard.Value == symbol)
                {
                    return (string)wildcard.Key + ":*";
                }
            }
        }
        return "##other:*";
    }
References System.Xml.Schema.SymbolsDictionary._names, System.Xml.Schema.SymbolsDictionary._wildcards, and System.Xml.Dictionary.
Referenced by System.Xml.Schema.DfaContentValidator.ExpectedElements(), System.Xml.Schema.NfaContentValidator.ExpectedElements(), and System.Xml.Schema.RangeContentValidator.ExpectedElements().