Terraria: System.Xml.Schema.SymbolsDictionary.GetParticle
GetParticle()
object System.Xml.Schema.SymbolsDictionary.GetParticle (int symbol) inline
Definition at line 158 of file SymbolsDictionary.cs.
    {
        if (symbol != _last)
        {
            return _particles[symbol];
        }
        return _particleLast;
    }
References System.Xml.Schema.SymbolsDictionary._last, System.Xml.Schema.SymbolsDictionary._particleLast, and System.Xml.Schema.SymbolsDictionary._particles.
Referenced by System.Xml.Schema.DfaContentValidator.ExpectedElements(), System.Xml.Schema.DfaContentValidator.ExpectedParticles(), and System.Xml.Schema.DfaContentValidator.ValidateElement().