Terraria: System.Xml.Schema.SymbolsDictionary.AddName
AddName()
int System.Xml.Schema.SymbolsDictionary.AddName (XmlQualifiedName name, object particle) inline
Definition at line 60 of file SymbolsDictionary.cs.
    {
        object obj = _names[name];
        if (obj != null)
        {
            int num = (int)obj;
            if (_particles[num] != particle)
            {
                _isUpaEnforced = false;
            }
            return num;
        }
        _names.Add(name, _last);
        _particles.Add(particle);
        return _last++;
    }
References System.Xml.Schema.SymbolsDictionary._isUpaEnforced, System.Xml.Schema.SymbolsDictionary._last, System.Xml.Schema.SymbolsDictionary._names, System.Xml.Schema.SymbolsDictionary._particles, System.Collections.Hashtable.Add(), System.Collections.ArrayList.Add(), and System.obj.
Referenced by System.Xml.Schema.ParticleContentValidator.AddName(), and System.Xml.Schema.ParticleContentValidator.Finish().