Terraria: Terraria.Initializers.AchievementInitializer.OnAchievementCompleted
OnAchievementCompleted()
static void Terraria.Initializers.AchievementInitializer.OnAchievementCompleted (Achievement achievement) inline static private
Definition at line 616 of file AchievementInitializer.cs.
    {
        //IL_0035: Unknown result type (might be due to invalid IL or missing references)
        Main.NewText(Language.GetTextValue("Achievements.Completed", AchievementTagHandler.GenerateTag(achievement)));
        if (SoundEngine.FindActiveSound(SoundID.AchievementComplete) == null)
        {
            SoundEngine.PlayTrackedSound(SoundID.AchievementComplete);
        }
    }
References Terraria.ID.SoundID.AchievementComplete, Terraria.Audio.SoundEngine.FindActiveSound(), Terraria.GameContent.UI.Chat.AchievementTagHandler.GenerateTag(), Terraria.Localization.Language.GetTextValue(), Terraria.Main.NewText(), and Terraria.Audio.SoundEngine.PlayTrackedSound().
Referenced by Terraria.Initializers.AchievementInitializer.Load().