Terraria: FastRandom.WithModifier
WithModifier() [2/2]
FastRandom FastRandom.WithModifier (ulong modifier) inline
     {
         return new FastRandom(NextSeed(modifier) ^ Seed);
     }
References FastRandom(), NextSeed(), and Seed.
Referenced by LightMap.BlurLine(), LegacyLighting.doColors_Mode0_Swipe(), LegacyLighting.doColors_Mode1_Swipe(), TileDrawing.DrawSingleTile(), TileLightScanner.GetTileLight(), DesertHive.PlaceClustersArea(), GraniteBiome.PlaceDecorations(), and WithModifier().