Terraria: Internal.NativeCrypto.CapiHelper.EncryptKey
EncryptKey()
static void Internal.NativeCrypto.CapiHelper.EncryptKey (SafeKeyHandle safeKeyHandle, byte[] pbKey, int cbKey, bool foep, [NotNull] ref byte[] pbEncryptedKey) inline static package
Definition at line 943 of file CapiHelper.cs.
    {
        VerifyValidHandle(safeKeyHandle);
        int dwFlags = (foep ? 64 : 0);
        int pdwDataLen = cbKey;
        if (!global::Interop.Advapi32.CryptEncrypt(safeKeyHandle, SafeHashHandle.InvalidHandle, Final: true, dwFlags, null, ref pdwDataLen, pdwDataLen))
        {
            throw GetErrorCode().ToCryptographicException();
        }
        pbEncryptedKey = new byte[pdwDataLen];
        Buffer.BlockCopy(pbKey, 0, pbEncryptedKey, 0, cbKey);
        if (!global::Interop.Advapi32.CryptEncrypt(safeKeyHandle, SafeHashHandle.InvalidHandle, Final: true, dwFlags, pbEncryptedKey, ref cbKey, pdwDataLen))
        {
            throw GetErrorCode().ToCryptographicException();
        }
        Array.Reverse(pbEncryptedKey);
    }
References System.Buffer.BlockCopy(), Internal.NativeCrypto.CapiHelper.GetErrorCode(), System.Security.Cryptography.SafeHashHandle.InvalidHandle, System.Array.Reverse(), and Internal.NativeCrypto.CapiHelper.VerifyValidHandle().
Referenced by System.Security.Cryptography.RSACryptoServiceProvider.Encrypt().