Terraria: Internal.NativeCrypto.CapiHelper.ObjToHashAlgId
ObjToHashAlgId()
static int Internal.NativeCrypto.CapiHelper.ObjToHashAlgId (object hashAlg) inline static
Definition at line 1053 of file CapiHelper.cs.
    {
        if (hashAlg == null)
        {
            throw new ArgumentNullException("hashAlg");
        }
        if (hashAlg is string nameOrOid)
        {
            return NameOrOidToHashAlgId(nameOrOid, OidGroup.HashAlgorithm);
        }
        if (hashAlg is HashAlgorithm)
        {
            if (hashAlg is MD5)
            {
                return 32771;
            }
            if (hashAlg is SHA1)
            {
                return 32772;
            }
            if (hashAlg is SHA256)
            {
                return 32780;
            }
            if (hashAlg is SHA384)
            {
                return 32781;
            }
            if (hashAlg is SHA512)
            {
                return 32782;
            }
        }
        else if (hashAlg is Type c)
        {
            if (typeof(MD5).IsAssignableFrom(c))
            {
                return 32771;
            }
            if (typeof(SHA1).IsAssignableFrom(c))
            {
                return 32772;
            }
            if (typeof(SHA256).IsAssignableFrom(c))
            {
                return 32780;
            }
            if (typeof(SHA384).IsAssignableFrom(c))
            {
                return 32781;
            }
            if (typeof(SHA512).IsAssignableFrom(c))
            {
                return 32782;
            }
        }
        throw new ArgumentException(System.SR.Argument_InvalidValue, "hashAlg");
    }
References System.SR.Argument_InvalidValue, and Internal.NativeCrypto.CapiHelper.NameOrOidToHashAlgId().
Referenced by Internal.NativeCrypto.CapiHelper.ObjToHashAlgorithm(), System.Security.Cryptography.RSACryptoServiceProvider.SignData(), System.Security.Cryptography.RSACryptoServiceProvider.SignData(), System.Security.Cryptography.RSACryptoServiceProvider.SignData(), and System.Security.Cryptography.RSACryptoServiceProvider.VerifyData().