Terraria: Internal.NativeCrypto.CapiHelper.ToRSAParameters
ToRSAParameters()
static RSAParameters Internal.NativeCrypto.CapiHelper.ToRSAParameters (this byte[] cspBlob, bool includePrivateParameters) inline static package
Definition at line 329 of file CapiHelper.cs.
    {
        try
        {
            BinaryReader binaryReader = new BinaryReader(new MemoryStream(cspBlob));
            binaryReader.ReadByte();
            binaryReader.ReadByte();
            binaryReader.ReadUInt16();
            int num = binaryReader.ReadInt32();
            if (num != 41984 && num != 9216)
            {
                throw new PlatformNotSupportedException();
            }
            binaryReader.ReadInt32();
            int num2 = binaryReader.ReadInt32();
            int num3 = num2 / 8;
            int count = (num3 + 1) / 2;
            uint exponent = binaryReader.ReadUInt32();
            RSAParameters result = default(RSAParameters);
            result.Exponent = ExponentAsBytes(exponent);
            result.Modulus = binaryReader.ReadReversed(num3);
            if (includePrivateParameters)
            {
                result.P = binaryReader.ReadReversed(count);
                result.Q = binaryReader.ReadReversed(count);
                result.DP = binaryReader.ReadReversed(count);
                result.DQ = binaryReader.ReadReversed(count);
                result.InverseQ = binaryReader.ReadReversed(count);
                result.D = binaryReader.ReadReversed(num3);
            }
            return result;
        }
        catch (EndOfStreamException)
        {
            throw GetEFailException();
        }
    }
References System.count, Internal.NativeCrypto.CapiHelper.ExponentAsBytes(), Internal.NativeCrypto.CapiHelper.GetEFailException(), System.IO.BinaryReader.ReadByte(), System.IO.BinaryReader.ReadInt32(), System.IO.BinaryReader.ReadUInt16(), and System.IO.BinaryReader.ReadUInt32().