Terraria: Internal.NativeCrypto.CapiHelper.CreateHashHandle
CreateHashHandle() [2/2]
static SafeHashHandle Internal.NativeCrypto.CapiHelper.CreateHashHandle (this SafeProvHandle hProv, byte[] hash, int calgHash, bool throwOnSizeError) inline static private
Definition at line 1291 of file CapiHelper.cs.
    {
        if (!CryptCreateHash(hProv, calgHash, SafeKeyHandle.InvalidHandle, global::Interop.Advapi32.CryptCreateHashFlags.None, out var phHash))
        {
            int hRForLastWin32Error = Marshal.GetHRForLastWin32Error();
            phHash.Dispose();
            throw hRForLastWin32Error.ToCryptographicException();
        }
        try
        {
            int pbData = 0;
            int pdwDataLen = 4;
            if (!global::Interop.Advapi32.CryptGetHashParam(phHash, global::Interop.Advapi32.CryptHashProperty.HP_HASHSIZE, out pbData, ref pdwDataLen, 0))
            {
                int hRForLastWin32Error2 = Marshal.GetHRForLastWin32Error();
                throw hRForLastWin32Error2.ToCryptographicException();
            }
            if (pbData != hash.Length)
            {
                if (throwOnSizeError)
                {
                    throw (-2146893821).ToCryptographicException();
                }
                return null;
            }
            if (!global::Interop.Advapi32.CryptSetHashParam(phHash, global::Interop.Advapi32.CryptHashProperty.HP_HASHVAL, hash, 0))
            {
                int hRForLastWin32Error3 = Marshal.GetHRForLastWin32Error();
                throw hRForLastWin32Error3.ToCryptographicException();
            }
            SafeHashHandle result = phHash;
            phHash = null;
            return result;
        }
        finally
        {
            phHash?.Dispose();
        }
    }
References Internal.NativeCrypto.CapiHelper.CryptCreateHash(), System.Security.Cryptography.SafeHashHandle.Dispose(), and System.Runtime.InteropServices.Marshal.GetHRForLastWin32Error().