Terraria: Internal.NativeCrypto.CapiHelper.GetKeyPairHelper
GetKeyPairHelper()
static SafeKeyHandle Internal.NativeCrypto.CapiHelper.GetKeyPairHelper (CspAlgorithmType keyType, CspParameters parameters, int keySize, SafeProvHandle safeProvHandle) inline static package
Definition at line 874 of file CapiHelper.cs.
    {
        SafeKeyHandle safeKeyHandle;
        int userKey = GetUserKey(safeProvHandle, parameters.KeyNumber, out safeKeyHandle);
        if (userKey != 0)
        {
            safeKeyHandle.Dispose();
            if (IsFlagBitSet((uint)parameters.Flags, 8u) || userKey != -2146893811)
            {
                throw userKey.ToCryptographicException();
            }
            GenerateKey(safeProvHandle, parameters.KeyNumber, (int)parameters.Flags, (uint)keySize, out safeKeyHandle);
        }
        byte[] keyParameter = GetKeyParameter(safeKeyHandle, 9);
        int num = BinaryPrimitives.ReadInt32LittleEndian(keyParameter);
        if ((keyType == CspAlgorithmType.Rsa && num != 41984 && num != 9216) || (keyType == CspAlgorithmType.Dss && num != 8704))
        {
            safeKeyHandle.Dispose();
            throw new CryptographicException(System.SR.Format(System.SR.Cryptography_CSP_WrongKeySpec, keyType));
        }
        return safeKeyHandle;
    }
References System.SR.Cryptography_CSP_WrongKeySpec, System.Runtime.InteropServices.SafeHandle.Dispose(), System.Security.Cryptography.CspParameters.Flags, System.SR.Format(), Internal.NativeCrypto.CapiHelper.GenerateKey(), Internal.NativeCrypto.CapiHelper.GetKeyParameter(), Internal.NativeCrypto.CapiHelper.GetUserKey(), Internal.NativeCrypto.CapiHelper.IsFlagBitSet(), System.Security.Cryptography.CspParameters.KeyNumber, and System.Buffers.Binary.BinaryPrimitives.ReadInt32LittleEndian().