Terraria: Internal.NativeCrypto.CapiHelper.GetErrorCode
GetErrorCode()
static int Internal.NativeCrypto.CapiHelper.GetErrorCode () inline static package
Definition at line 897 of file CapiHelper.cs.
    {
        return Marshal.GetLastPInvokeError();
    }
References System.Runtime.InteropServices.Marshal.GetLastPInvokeError().
Referenced by Internal.NativeCrypto.CapiHelper.AcquireCryptContext(), Internal.NativeCrypto.CapiHelper.CreateProvHandle(), Internal.NativeCrypto.CapiHelper.DecryptData(), Internal.NativeCrypto.CapiHelper.DecryptKey(), Internal.NativeCrypto.CapiHelper.EncryptData(), Internal.NativeCrypto.CapiHelper.EncryptKey(), Internal.NativeCrypto.CapiHelper.ExportKeyBlob(), Internal.NativeCrypto.CapiHelper.GenerateKey(), Internal.NativeCrypto.CapiHelper.GetDefaultProvider(), Internal.NativeCrypto.CapiHelper.GetKeyParameter(), Internal.NativeCrypto.CapiHelper.GetProviderParameter(), Internal.NativeCrypto.CapiHelper.GetProviderParameterWorker(), Internal.NativeCrypto.CapiHelper.GetUserKey(), Internal.NativeCrypto.CapiHelper.SetKeyParameter(), and Internal.NativeCrypto.CapiHelper.SetKeyParameter().