Terraria: Internal.NativeCrypto.CapiHelper.DeriveKey
DeriveKey()
static void Internal.NativeCrypto.CapiHelper.DeriveKey (SafeProvHandle hProv, int algid, int algidHash, byte[] password, int cbPassword, int dwFlags, byte[] IV_Out, int cbIV_In, [NotNull] ref byte[] pbKey) inline static
Definition at line 1194 of file CapiHelper.cs.
    {
        VerifyValidHandle(hProv);
        SafeHashHandle phHash = null;
        SafeKeyHandle phKey = null;
        try
        {
            if (!CryptCreateHash(hProv, algidHash, SafeKeyHandle.InvalidHandle, global::Interop.Advapi32.CryptCreateHashFlags.None, out phHash))
            {
                int hRForLastWin32Error = Marshal.GetHRForLastWin32Error();
                throw hRForLastWin32Error.ToCryptographicException();
            }
            if (!global::Interop.Advapi32.CryptHashData(phHash, password, cbPassword, 0))
            {
                int hRForLastWin32Error2 = Marshal.GetHRForLastWin32Error();
                throw hRForLastWin32Error2.ToCryptographicException();
            }
            if (!CryptDeriveKey(hProv, algid, phHash, dwFlags | 1, out phKey))
            {
                int hRForLastWin32Error3 = Marshal.GetHRForLastWin32Error();
                throw hRForLastWin32Error3.ToCryptographicException();
            }
            byte[] key_out = null;
            int cb_out = 0;
            UnloadKey(hProv, phKey, ref key_out, ref cb_out);
            int pdwDataLen = 0;
            if (!global::Interop.Advapi32.CryptGetKeyParam(phKey, global::Interop.Advapi32.CryptGetKeyParamFlags.KP_IV, null, ref pdwDataLen, 0))
            {
                int hRForLastWin32Error4 = Marshal.GetHRForLastWin32Error();
                throw hRForLastWin32Error4.ToCryptographicException();
            }
            byte[] array = new byte[pdwDataLen];
            if (!global::Interop.Advapi32.CryptGetKeyParam(phKey, global::Interop.Advapi32.CryptGetKeyParamFlags.KP_IV, array, ref pdwDataLen, 0))
            {
                int hRForLastWin32Error5 = Marshal.GetHRForLastWin32Error();
                throw hRForLastWin32Error5.ToCryptographicException();
            }
            if (pdwDataLen != cbIV_In)
            {
                throw new CryptographicException(System.SR.Cryptography_PasswordDerivedBytes_InvalidIV);
            }
            Buffer.BlockCopy(array, 0, IV_Out, 0, pdwDataLen);
            pbKey = new byte[cb_out];
            Buffer.BlockCopy(key_out, 0, pbKey, 0, cb_out);
        }
        finally
        {
            phKey?.Dispose();
            phHash?.Dispose();
        }
    }
References System.array, System.Buffer.BlockCopy(), Internal.NativeCrypto.CapiHelper.CryptCreateHash(), Internal.NativeCrypto.CapiHelper.CryptDeriveKey(), System.SR.Cryptography_PasswordDerivedBytes_InvalidIV, System.Runtime.InteropServices.SafeHandle.Dispose(), System.Security.Cryptography.SafeHashHandle.Dispose(), System.Runtime.InteropServices.Marshal.GetHRForLastWin32Error(), Internal.NativeCrypto.CapiHelper.UnloadKey(), and Internal.NativeCrypto.CapiHelper.VerifyValidHandle().
Referenced by System.Security.Cryptography.PasswordDeriveBytes.CryptDeriveKey().