Terraria: Internal.NativeCrypto.CapiHelper.ToKeyBlob
ToKeyBlob() [2/2]
static byte[] Internal.NativeCrypto.CapiHelper.ToKeyBlob (this RSAParameters rsaParameters) inline static package
Definition at line 253 of file CapiHelper.cs.
    {
        if (rsaParameters.Modulus == null)
        {
            throw GetBadDataException();
        }
        if (rsaParameters.Exponent == null || rsaParameters.Exponent.Length > 4)
        {
            throw GetBadDataException();
        }
        int num = rsaParameters.Modulus.Length;
        int num2 = (num + 1) / 2;
        if (rsaParameters.P != null)
        {
            if (rsaParameters.P.Length != num2)
            {
                throw GetBadDataException();
            }
            if (rsaParameters.Q == null || rsaParameters.Q.Length != num2)
            {
                throw GetBadDataException();
            }
            if (rsaParameters.DP == null || rsaParameters.DP.Length != num2)
            {
                throw GetBadDataException();
            }
            if (rsaParameters.DQ == null || rsaParameters.DQ.Length != num2)
            {
                throw GetBadDataException();
            }
            if (rsaParameters.InverseQ == null || rsaParameters.InverseQ.Length != num2)
            {
                throw GetBadDataException();
            }
            if (rsaParameters.D == null || rsaParameters.D.Length != num)
            {
                throw GetBadDataException();
            }
        }
        bool flag = rsaParameters.P != null && rsaParameters.P.Length != 0;
        MemoryStream memoryStream = new MemoryStream();
        BinaryWriter binaryWriter = new BinaryWriter(memoryStream);
        binaryWriter.Write((byte)(flag ? 7u : 6u));
        binaryWriter.Write((byte)2);
        binaryWriter.Write((ushort)0);
        binaryWriter.Write(41984u);
        binaryWriter.Write(flag ? 843141970 : 826364754);
        binaryWriter.Write((uint)(num * 8));
        uint num3 = 0u;
        for (int i = 0; i < rsaParameters.Exponent.Length; i++)
        {
            num3 <<= 8;
            num3 |= rsaParameters.Exponent[i];
        }
        binaryWriter.Write(num3);
        binaryWriter.WriteReversed(rsaParameters.Modulus);
        if (flag)
        {
            binaryWriter.WriteReversed(rsaParameters.P);
            binaryWriter.WriteReversed(rsaParameters.Q);
            binaryWriter.WriteReversed(rsaParameters.DP);
            binaryWriter.WriteReversed(rsaParameters.DQ);
            binaryWriter.WriteReversed(rsaParameters.InverseQ);
            binaryWriter.WriteReversed(rsaParameters.D);
        }
        binaryWriter.Flush();
        return memoryStream.ToArray();
    }
References System.Security.Cryptography.RSAParameters.D, System.Security.Cryptography.RSAParameters.DP, System.Security.Cryptography.RSAParameters.DQ, System.Security.Cryptography.RSAParameters.Exponent, System.IO.BinaryWriter.Flush(), Internal.NativeCrypto.CapiHelper.GetBadDataException(), System.Security.Cryptography.RSAParameters.InverseQ, System.Security.Cryptography.RSAParameters.Modulus, System.Security.Cryptography.RSAParameters.P, System.Security.Cryptography.RSAParameters.Q, System.IO.MemoryStream.ToArray(), and System.IO.BinaryWriter.Write().