Terraria: Internal.NativeCrypto.CapiHelper.ValidateCspFlags
ValidateCspFlags()
static void Internal.NativeCrypto.CapiHelper.ValidateCspFlags (CspProviderFlags flags) inline static private
Definition at line 862 of file CapiHelper.cs.
    {
        if (IsFlagBitSet((uint)flags, 8u))
        {
            CspProviderFlags cspProviderFlags = CspProviderFlags.UseNonExportableKey | CspProviderFlags.UseArchivableKey | CspProviderFlags.UseUserProtectedKey;
            if ((flags & cspProviderFlags) != 0)
            {
                throw new ArgumentException(System.SR.Format(System.SR.Arg_EnumIllegalVal, flags), "flags");
            }
        }
    }
References System.SR.Arg_EnumIllegalVal, System.SR.Format(), and Internal.NativeCrypto.CapiHelper.IsFlagBitSet().
Referenced by Internal.NativeCrypto.CapiHelper.SaveCspParameters().