Terraria: Internal.NativeCrypto.CapiHelper.OpenCSP
OpenCSP()
static int Internal.NativeCrypto.CapiHelper.OpenCSP (CspParameters cspParameters, uint flags, out SafeProvHandle safeProvHandle) inline static
Definition at line 528 of file CapiHelper.cs.
    {
        string text = null;
        if (cspParameters == null)
        {
            throw new ArgumentException(System.SR.Format(System.SR.CspParameter_invalid, "cspParameters"));
        }
        int providerType = cspParameters.ProviderType;
        string providerName = ((cspParameters.ProviderName != null) ? cspParameters.ProviderName : (cspParameters.ProviderName = GetDefaultProvider(providerType)));
        int flags2 = (int)cspParameters.Flags;
        if (!IsFlagBitSet((uint)flags2, 2u) && cspParameters.KeyContainerName != null)
        {
            text = cspParameters.KeyContainerName;
        }
        flags |= MapCspProviderFlags((int)cspParameters.Flags);
        SafeProvHandle safeProvHandle2;
        int num = AcquireCryptContext(out safeProvHandle2, text, providerName, providerType, flags);
        if (num != 0)
        {
            safeProvHandle2.Dispose();
            safeProvHandle = SafeProvHandle.InvalidHandle;
            return num;
        }
        safeProvHandle2.ContainerName = text;
        safeProvHandle2.ProviderName = providerName;
        safeProvHandle2.Types = providerType;
        safeProvHandle2.Flags = flags;
        if (IsFlagBitSet(flags, 4026531840u))
        {
            safeProvHandle2.PersistKeyInCsp = false;
        }
        safeProvHandle = safeProvHandle2;
        return 0;
    }
References Internal.NativeCrypto.CapiHelper.AcquireCryptContext(), System.SR.CspParameter_invalid, System.Security.Cryptography.SafeProvHandle.Dispose(), System.Security.Cryptography.CspParameters.Flags, System.SR.Format(), Internal.NativeCrypto.CapiHelper.GetDefaultProvider(), System.Security.Cryptography.SafeProvHandle.InvalidHandle, Internal.NativeCrypto.CapiHelper.IsFlagBitSet(), System.Security.Cryptography.CspParameters.KeyContainerName, Internal.NativeCrypto.CapiHelper.MapCspProviderFlags(), System.Security.Cryptography.CspParameters.ProviderName, System.Security.Cryptography.CspParameters.ProviderType, and System.text.
Referenced by Internal.NativeCrypto.CapiHelper.AcquireCsp(), Internal.NativeCrypto.CapiHelper.CreateCSP(), Internal.NativeCrypto.CapiHelper.CreateProvHandle(), System.Security.Cryptography.CspKeyContainerInfo.ReadDeviceParameterVerifyContext(), and System.Security.Cryptography.CspKeyContainerInfo.ReadKeyParameterSilent().