Terraria: Internal.NativeCrypto.CapiHelper.ToKeyBlob
ToKeyBlob() [1/2]
static byte[] Internal.NativeCrypto.CapiHelper.ToKeyBlob (this DSAParameters dsaParameters) inline static package
Definition at line 44 of file CapiHelper.cs.
    {
        if (dsaParameters.P == null || dsaParameters.P.Length == 0 || dsaParameters.Q == null || dsaParameters.Q.Length != 20)
        {
            throw GetBadDataException();
        }
        if (dsaParameters.G == null || dsaParameters.G.Length != dsaParameters.P.Length)
        {
            throw GetBadDataException();
        }
        if (dsaParameters.J != null && dsaParameters.J.Length >= dsaParameters.P.Length)
        {
            throw GetBadDataException();
        }
        if (dsaParameters.Y != null && dsaParameters.Y.Length != dsaParameters.P.Length)
        {
            throw GetBadDataException();
        }
        if (dsaParameters.Seed != null && dsaParameters.Seed.Length != 20)
        {
            throw GetBadDataException();
        }
        bool flag = dsaParameters.X != null && dsaParameters.X.Length != 0;
        if (flag && dsaParameters.X.Length != 20)
        {
            throw GetBadDataException();
        }
        uint value = (uint)(dsaParameters.P.Length * 8);
        uint num = ((dsaParameters.J != null) ? ((uint)(dsaParameters.J.Length * 8)) : 0u);
        using MemoryStream memoryStream = new MemoryStream();
        using BinaryWriter binaryWriter = new BinaryWriter(memoryStream);
        WriteKeyBlobHeader(dsaParameters, binaryWriter, flag, out var isV);
        if (isV)
        {
            binaryWriter.Write(flag ? 877876036 : 861098820);
            binaryWriter.Write(value);
            binaryWriter.Write((uint)(dsaParameters.Q.Length * 8));
            binaryWriter.Write(num);
            if (flag)
            {
                binaryWriter.Write((uint)(dsaParameters.X.Length * 8));
            }
            WriteDSSSeed(dsaParameters, binaryWriter);
            binaryWriter.WriteReversed(dsaParameters.P);
            binaryWriter.WriteReversed(dsaParameters.Q);
            binaryWriter.WriteReversed(dsaParameters.G);
            if (num != 0)
            {
                binaryWriter.WriteReversed(dsaParameters.J);
            }
            binaryWriter.WriteReversed(dsaParameters.Y);
            if (flag)
            {
                binaryWriter.WriteReversed(dsaParameters.X);
            }
        }
        else
        {
            binaryWriter.Write(flag ? 844321604 : 827544388);
            binaryWriter.Write(value);
            binaryWriter.WriteReversed(dsaParameters.P);
            binaryWriter.WriteReversed(dsaParameters.Q);
            binaryWriter.WriteReversed(dsaParameters.G);
            if (flag)
            {
                binaryWriter.WriteReversed(dsaParameters.X);
            }
            else
            {
                binaryWriter.WriteReversed(dsaParameters.Y);
            }
            WriteDSSSeed(dsaParameters, binaryWriter);
        }
        binaryWriter.Flush();
        return memoryStream.ToArray();
    }
References System.Security.Cryptography.DSAParameters.G, Internal.NativeCrypto.CapiHelper.GetBadDataException(), System.Security.Cryptography.DSAParameters.J, System.Security.Cryptography.DSAParameters.P, System.Security.Cryptography.DSAParameters.Q, System.Security.Cryptography.DSAParameters.Seed, System.value, Internal.NativeCrypto.CapiHelper.WriteDSSSeed(), Internal.NativeCrypto.CapiHelper.WriteKeyBlobHeader(), System.Security.Cryptography.DSAParameters.X, and System.Security.Cryptography.DSAParameters.Y.