Terraria: Internal.NativeCrypto.CapiHelper.SaveCspParameters
SaveCspParameters()
static CspParameters Internal.NativeCrypto.CapiHelper.SaveCspParameters (CspAlgorithmType keyType, CspParameters userParameters, CspProviderFlags defaultFlags, out bool randomKeyContainer) inline static package
Definition at line 829 of file CapiHelper.cs.
    {
        CspParameters cspParameters;
        if (userParameters == null)
        {
            cspParameters = new CspParameters((keyType == CspAlgorithmType.Dss) ? 13 : 24, null, null, defaultFlags);
        }
        else
        {
            ValidateCspFlags(userParameters.Flags);
            cspParameters = new CspParameters(userParameters);
        }
        if (cspParameters.KeyNumber == -1)
        {
            cspParameters.KeyNumber = ((keyType != CspAlgorithmType.Dss) ? 1 : 2);
        }
        else if (cspParameters.KeyNumber == 8704 || cspParameters.KeyNumber == 9216)
        {
            cspParameters.KeyNumber = 2;
        }
        else if (cspParameters.KeyNumber == 41984)
        {
            cspParameters.KeyNumber = 1;
        }
        randomKeyContainer = IsFlagBitSet((uint)cspParameters.Flags, 128u);
        if (cspParameters.KeyContainerName == null && !IsFlagBitSet((uint)cspParameters.Flags, 2u))
        {
            cspParameters.Flags |= CspProviderFlags.CreateEphemeralKey;
            randomKeyContainer = true;
        }
        return cspParameters;
    }
References System.Security.Cryptography.CspParameters.Flags, Internal.NativeCrypto.CapiHelper.IsFlagBitSet(), System.Security.Cryptography.CspParameters.KeyContainerName, System.Security.Cryptography.CspParameters.KeyNumber, and Internal.NativeCrypto.CapiHelper.ValidateCspFlags().
Referenced by System.Security.Cryptography.DSACryptoServiceProvider.DSACryptoServiceProvider(), and System.Security.Cryptography.RSACryptoServiceProvider.RSACryptoServiceProvider().