Terraria: Internal.NativeCrypto.CapiHelper.VerifyValidHandle
VerifyValidHandle()
static void Internal.NativeCrypto.CapiHelper.VerifyValidHandle (SafeHandleZeroOrMinusOneIsInvalid handle) inline static package
Definition at line 767 of file CapiHelper.cs.
    {
        if (handle.IsInvalid)
        {
            throw new CryptographicException(System.SR.Cryptography_OpenInvalidHandle);
        }
    }
References System.SR.Cryptography_OpenInvalidHandle, and System.handle.
Referenced by Internal.NativeCrypto.CapiHelper.DecryptData(), Internal.NativeCrypto.CapiHelper.DecryptKey(), Internal.NativeCrypto.CapiHelper.DeriveKey(), Internal.NativeCrypto.CapiHelper.EncryptData(), Internal.NativeCrypto.CapiHelper.EncryptKey(), Internal.NativeCrypto.CapiHelper.ExportKeyBlob(), Internal.NativeCrypto.CapiHelper.GenerateKey(), Internal.NativeCrypto.CapiHelper.GetKeyParameter(), Internal.NativeCrypto.CapiHelper.GetPersistKeyInCsp(), Internal.NativeCrypto.CapiHelper.GetProviderParameter(), Internal.NativeCrypto.CapiHelper.GetUserKey(), Internal.NativeCrypto.CapiHelper.SetKeyParameter(), Internal.NativeCrypto.CapiHelper.SetKeyParameter(), and Internal.NativeCrypto.CapiHelper.SetPersistKeyInCsp().