Terraria: Internal.NativeCrypto.CapiHelper.NameOrOidToHashAlgId
NameOrOidToHashAlgId()
static int Internal.NativeCrypto.CapiHelper.NameOrOidToHashAlgId (string nameOrOid, OidGroup oidGroup) inline static
Definition at line 1034 of file CapiHelper.cs.
    {
        if (nameOrOid == null)
        {
            return 32772;
        }
        string text = CryptoConfig.MapNameToOID(nameOrOid);
        if (text == null)
        {
            text = nameOrOid;
        }
        int algIdFromOid = GetAlgIdFromOid(text, oidGroup);
        if (algIdFromOid == 0 || algIdFromOid == -1)
        {
            throw new CryptographicException(System.SR.Cryptography_InvalidOID);
        }
        return algIdFromOid;
    }
References System.SR.Cryptography_InvalidOID, Internal.NativeCrypto.CapiHelper.GetAlgIdFromOid(), System.Security.Cryptography.CryptoConfig.MapNameToOID(), and System.text.
Referenced by System.Security.Cryptography.PasswordDeriveBytes.CryptDeriveKey(), Internal.NativeCrypto.CapiHelper.ObjToHashAlgId(), System.Security.Cryptography.DSACryptoServiceProvider.SignHash(), System.Security.Cryptography.RSACryptoServiceProvider.SignHash(), System.Security.Cryptography.RSACryptoServiceProvider.VerifyHash(), and System.Security.Cryptography.DSACryptoServiceProvider.VerifyHash().