Terraria: Internal.NativeCrypto.CapiHelper.ToDSAParameters
ToDSAParameters()
static DSAParameters Internal.NativeCrypto.CapiHelper.ToDSAParameters (this byte[] cspBlob, bool includePrivateParameters, byte[] cspPublicBlob) inline static package
Definition at line 121 of file CapiHelper.cs.
    {
        try
        {
            using MemoryStream input = new MemoryStream(cspBlob);
            using BinaryReader binaryReader = new BinaryReader(input);
            ReadKeyBlobHeader(binaryReader, out var bVersion);
            DSAParameters dSAParameters = default(DSAParameters);
            if (bVersion > 2)
            {
                binaryReader.ReadInt32();
                int count = (binaryReader.ReadInt32() + 7) / 8;
                int count2 = (binaryReader.ReadInt32() + 7) / 8;
                int num = (binaryReader.ReadInt32() + 7) / 8;
                int count3 = 0;
                if (includePrivateParameters)
                {
                    count3 = (binaryReader.ReadInt32() + 7) / 8;
                }
                ReadDSSSeed(dSAParameters, binaryReader, isV3: true);
                dSAParameters.P = binaryReader.ReadReversed(count);
                dSAParameters.Q = binaryReader.ReadReversed(count2);
                dSAParameters.G = binaryReader.ReadReversed(count);
                if (num > 0)
                {
                    dSAParameters.J = binaryReader.ReadReversed(num);
                }
                dSAParameters.Y = binaryReader.ReadReversed(count);
                if (includePrivateParameters)
                {
                    dSAParameters.X = binaryReader.ReadReversed(count3);
                }
            }
            else
            {
                binaryReader.ReadInt32();
                int count4 = (binaryReader.ReadInt32() + 7) / 8;
                dSAParameters.P = binaryReader.ReadReversed(count4);
                dSAParameters.Q = binaryReader.ReadReversed(20);
                dSAParameters.G = binaryReader.ReadReversed(count4);
                long position = 0L;
                if (includePrivateParameters)
                {
                    position = binaryReader.BaseStream.Position;
                    dSAParameters.X = binaryReader.ReadReversed(20);
                }
                else
                {
                    dSAParameters.Y = binaryReader.ReadReversed(count4);
                }
                ReadDSSSeed(dSAParameters, binaryReader, isV3: false);
                if (includePrivateParameters)
                {
                    if (cspPublicBlob == null)
                    {
                        throw new CryptographicUnexpectedOperationException();
                    }
                    using MemoryStream input2 = new MemoryStream(cspPublicBlob);
                    using BinaryReader binaryReader2 = new BinaryReader(input2);
                    binaryReader2.BaseStream.Position = position;
                    dSAParameters.Y = binaryReader2.ReadReversed(count4);
                }
            }
            return dSAParameters;
        }
        catch (EndOfStreamException)
        {
            throw GetEFailException();
        }
    }
References System.count, Internal.NativeCrypto.CapiHelper.GetEFailException(), System.input, System.L, Internal.NativeCrypto.CapiHelper.ReadDSSSeed(), and Internal.NativeCrypto.CapiHelper.ReadKeyBlobHeader().