Terraria: Internal.NativeCrypto.CapiHelper.ImportKeyBlob
ImportKeyBlob()
static void Internal.NativeCrypto.CapiHelper.ImportKeyBlob (SafeProvHandle saveProvHandle, CspProviderFlags flags, bool addNoSaltFlag, byte[] keyBlob, out SafeKeyHandle safeKeyHandle) inline static package
Definition at line 995 of file CapiHelper.cs.
    {
        bool flag = keyBlob.Length != 0 && keyBlob[0] == 6;
        int num = MapCspKeyFlags((int)flags);
        if (flag)
        {
            num &= -2;
        }
        if (addNoSaltFlag)
        {
            num |= 0x10;
        }
        if (!CryptImportKey(saveProvHandle, keyBlob, SafeKeyHandle.InvalidHandle, num, out var phKey))
        {
            int hRForLastWin32Error = Marshal.GetHRForLastWin32Error();
            phKey.Dispose();
            throw hRForLastWin32Error.ToCryptographicException();
        }
        phKey.PublicOnly = flag;
        safeKeyHandle = phKey;
    }
References Internal.NativeCrypto.CapiHelper.CryptImportKey(), System.Runtime.InteropServices.Marshal.GetHRForLastWin32Error(), and Internal.NativeCrypto.CapiHelper.MapCspKeyFlags().
Referenced by System.Security.Cryptography.DSACryptoServiceProvider.ImportCspBlob(), System.Security.Cryptography.RSACryptoServiceProvider.ImportCspBlob(), and Internal.Cryptography.BasicSymmetricCipherCsp.ImportCspBlob().