Terraria: Internal.NativeCrypto.CapiHelper.GetProviderParameterWorker
GetProviderParameterWorker()
static int Internal.NativeCrypto.CapiHelper.GetProviderParameterWorker (SafeProvHandle safeProvHandle, byte[] impType, ref int cb, global::Interop::Advapi32::CryptProvParam flags) inline static package
Definition at line 612 of file CapiHelper.cs.
    {
        int result = 0;
        if (!global::Interop.Advapi32.CryptGetProvParam(safeProvHandle, flags, impType, ref cb))
        {
            throw GetErrorCode().ToCryptographicException();
        }
        if (impType != null && cb == 4)
        {
            result = BitConverter.ToInt32(impType, 0);
        }
        return result;
    }
References Internal.NativeCrypto.CapiHelper.GetErrorCode(), and System.BitConverter.ToInt32().
Referenced by Internal.NativeCrypto.CapiHelper.GetProviderParameter().