Terraria: Internal.NativeCrypto.CapiHelper.GetKeyParameter
GetKeyParameter()
static byte[] Internal.NativeCrypto.CapiHelper.GetKeyParameter (SafeKeyHandle safeKeyHandle, int keyParam) inline static package
Definition at line 775 of file CapiHelper.cs.
    {
        byte[] array = null;
        int pdwDataLen = 0;
        VerifyValidHandle(safeKeyHandle);
        switch (keyParam)
        {
        case 1:
            if (!global::Interop.Advapi32.CryptGetKeyParam(safeKeyHandle, global::Interop.Advapi32.CryptGetKeyParamFlags.KP_KEYLEN, null, ref pdwDataLen, 0))
            {
                throw GetErrorCode().ToCryptographicException();
            }
            array = new byte[pdwDataLen];
            if (!global::Interop.Advapi32.CryptGetKeyParam(safeKeyHandle, global::Interop.Advapi32.CryptGetKeyParamFlags.KP_KEYLEN, array, ref pdwDataLen, 0))
            {
                throw GetErrorCode().ToCryptographicException();
            }
            break;
        case 2:
            array = new byte[1] { (byte)(safeKeyHandle.PublicOnly ? 1 : 0) };
            break;
        case 9:
            if (!global::Interop.Advapi32.CryptGetKeyParam(safeKeyHandle, global::Interop.Advapi32.CryptGetKeyParamFlags.KP_ALGID, null, ref pdwDataLen, 0))
            {
                throw GetErrorCode().ToCryptographicException();
            }
            array = new byte[pdwDataLen];
            if (!global::Interop.Advapi32.CryptGetKeyParam(safeKeyHandle, global::Interop.Advapi32.CryptGetKeyParamFlags.KP_ALGID, array, ref pdwDataLen, 0))
            {
                throw GetErrorCode().ToCryptographicException();
            }
            break;
        }
        return array;
    }
References System.array, Internal.NativeCrypto.CapiHelper.GetErrorCode(), and Internal.NativeCrypto.CapiHelper.VerifyValidHandle().
Referenced by Internal.NativeCrypto.CapiHelper.GetKeyPairHelper().