Terraria: Internal.NativeCrypto.CapiHelper.VerifySign
VerifySign()
static bool Internal.NativeCrypto.CapiHelper.VerifySign (SafeProvHandle hProv, SafeKeyHandle hKey, int calgKey, int calgHash, byte[] hash, byte[] signature) inline static
Definition at line 1171 of file CapiHelper.cs.
    {
        switch (calgKey)
        {
        case 9216:
            signature = signature.CloneByteArray();
            Array.Reverse(signature);
            break;
        case 8704:
            signature = signature.CloneByteArray();
            ReverseDsaSignature(signature, signature.Length);
            break;
        default:
            throw new InvalidOperationException();
        }
        using SafeHashHandle safeHashHandle = hProv.CreateHashHandle(hash, calgHash, throwOnSizeError: false);
        if (safeHashHandle == null)
        {
            return false;
        }
        return global::Interop.Advapi32.CryptVerifySignature(safeHashHandle, signature, signature.Length, hKey, null, global::Interop.Advapi32.CryptSignAndVerifyHashFlags.None);
    }
References System.Array.Reverse(), and Internal.NativeCrypto.CapiHelper.ReverseDsaSignature().
Referenced by System.Security.Cryptography.RSACryptoServiceProvider.VerifyHash(), and System.Security.Cryptography.DSACryptoServiceProvider.VerifyHash().