Terraria: Internal.NativeCrypto.CapiHelper.UnloadKey
UnloadKey()
static void Internal.NativeCrypto.CapiHelper.UnloadKey (SafeProvHandle hProv, SafeKeyHandle hKey, [NotNull] ref byte[] key_out, ref int cb_out) inline static private
Definition at line 1246 of file CapiHelper.cs.
    {
        SafeKeyHandle phKey = null;
        try
        {
            if (!CryptImportKey(hProv, RgbPubKey, SafeKeyHandle.InvalidHandle, 0, out phKey))
            {
                int hRForLastWin32Error = Marshal.GetHRForLastWin32Error();
                throw hRForLastWin32Error.ToCryptographicException();
            }
            int dwDataLen = 0;
            if (!global::Interop.Advapi32.CryptExportKey(hKey, phKey, 1, 0, null, ref dwDataLen))
            {
                int hRForLastWin32Error2 = Marshal.GetHRForLastWin32Error();
                throw hRForLastWin32Error2.ToCryptographicException();
            }
            byte[] array = new byte[dwDataLen];
            if (!global::Interop.Advapi32.CryptExportKey(hKey, phKey, 1, 0, array, ref dwDataLen))
            {
                int hRForLastWin32Error3 = Marshal.GetHRForLastWin32Error();
                throw hRForLastWin32Error3.ToCryptographicException();
            }
            int num = 8;
            int num2 = num + 4;
            int num3 = checked(dwDataLen - num - 4 - 2);
            while (num3 > 0 && array[num3 + num2] != 0)
            {
                num3--;
            }
            key_out = new byte[num3];
            Buffer.BlockCopy(array, num2, key_out, 0, num3);
            Array.Reverse(key_out);
            cb_out = num3;
        }
        finally
        {
            phKey?.Dispose();
        }
    }
References System.array, System.Buffer.BlockCopy(), Internal.NativeCrypto.CapiHelper.CryptImportKey(), System.Runtime.InteropServices.SafeHandle.Dispose(), System.Runtime.InteropServices.Marshal.GetHRForLastWin32Error(), System.Array.Reverse(), and Internal.NativeCrypto.CapiHelper.RgbPubKey.
Referenced by Internal.NativeCrypto.CapiHelper.DeriveKey().