Terraria: Internal.NativeCrypto.CapiHelper.CreateProvHandle
CreateProvHandle()
static SafeProvHandle Internal.NativeCrypto.CapiHelper.CreateProvHandle (CspParameters parameters, bool randomKeyContainer) inline static package
Definition at line 563 of file CapiHelper.cs.
    {
        uint flags = 0u;
        SafeProvHandle safeProvHandle;
        uint num = (uint)OpenCSP(parameters, flags, out safeProvHandle);
        if (num != 0)
        {
            safeProvHandle.Dispose();
            if (IsFlagBitSet((uint)parameters.Flags, 8u) || (num != 2148073497u && num != 2148073494u && num != 2147942402u))
            {
                throw ((int)num).ToCryptographicException();
            }
            CreateCSP(parameters, randomKeyContainer, out safeProvHandle);
        }
        if (parameters.ParentWindowHandle != IntPtr.Zero)
        {
            IntPtr pbData = parameters.ParentWindowHandle;
            if (!global::Interop.Advapi32.CryptSetProvParam(safeProvHandle, global::Interop.Advapi32.CryptProvParam.PP_CLIENT_HWND, ref pbData, 0))
            {
                throw GetErrorCode().ToCryptographicException();
            }
        }
        if (parameters.KeyPassword != null)
        {
            IntPtr intPtr = Marshal.SecureStringToCoTaskMemAnsi(parameters.KeyPassword);
            try
            {
                global::Interop.Advapi32.CryptProvParam dwParam = ((parameters.KeyNumber == 2) ? global::Interop.Advapi32.CryptProvParam.PP_SIGNATURE_PIN : global::Interop.Advapi32.CryptProvParam.PP_KEYEXCHANGE_PIN);
                if (!global::Interop.Advapi32.CryptSetProvParam(safeProvHandle, dwParam, intPtr, 0))
                {
                    throw GetErrorCode().ToCryptographicException();
                }
            }
            finally
            {
                if (intPtr != IntPtr.Zero)
                {
                    Marshal.ZeroFreeCoTaskMemAnsi(intPtr);
                }
            }
        }
        return safeProvHandle;
    }
References Internal.NativeCrypto.CapiHelper.CreateCSP(), System.Security.Cryptography.SafeProvHandle.Dispose(), System.Security.Cryptography.CspParameters.Flags, Internal.NativeCrypto.CapiHelper.GetErrorCode(), Internal.NativeCrypto.CapiHelper.IsFlagBitSet(), System.Security.Cryptography.CspParameters.KeyPassword, Internal.NativeCrypto.CapiHelper.OpenCSP(), System.Security.Cryptography.CspParameters.ParentWindowHandle, System.Runtime.InteropServices.Marshal.SecureStringToCoTaskMemAnsi(), System.IntPtr.Zero, and System.Runtime.InteropServices.Marshal.ZeroFreeCoTaskMemAnsi().