Terraria: Internal.NativeCrypto.CapiHelper.DecryptKey
DecryptKey()
static void Internal.NativeCrypto.CapiHelper.DecryptKey (SafeKeyHandle safeKeyHandle, byte[] encryptedData, int encryptedDataLength, bool fOAEP, out byte[] decryptedData) inline static package
Definition at line 914 of file CapiHelper.cs.
    {
        VerifyValidHandle(safeKeyHandle);
        byte[] array = new byte[encryptedDataLength];
        Buffer.BlockCopy(encryptedData, 0, array, 0, encryptedDataLength);
        Array.Reverse(array);
        int num = (fOAEP ? 64 : 0);
        int pdwDataLen = encryptedDataLength;
        if (!global::Interop.Advapi32.CryptDecrypt(safeKeyHandle, SafeHashHandle.InvalidHandle, Final: true, num, array, ref pdwDataLen))
        {
            int errorCode = GetErrorCode();
            if ((num & 0x40) == 64)
            {
                switch (errorCode)
                {
                case -2146893815:
                    throw new CryptographicException("Cryptography_OAEP_XPPlus_Only");
                default:
                    throw new CryptographicException("Cryptography_OAEPDecoding");
                case -2146893821:
                    break;
                }
            }
            throw errorCode.ToCryptographicException();
        }
        decryptedData = new byte[pdwDataLen];
        Buffer.BlockCopy(array, 0, decryptedData, 0, pdwDataLen);
    }
References System.array, System.Buffer.BlockCopy(), Internal.NativeCrypto.CapiHelper.GetErrorCode(), System.Security.Cryptography.SafeHashHandle.InvalidHandle, System.Array.Reverse(), and Internal.NativeCrypto.CapiHelper.VerifyValidHandle().
Referenced by System.Security.Cryptography.RSACryptoServiceProvider.Decrypt().