Terraria: Internal.NativeCrypto.CapiHelper.GetProviderParameter
GetProviderParameter()
static object Internal.NativeCrypto.CapiHelper.GetProviderParameter (SafeProvHandle safeProvHandle, int keyNumber, int keyParam) inline static
Definition at line 626 of file CapiHelper.cs.
    {
        VerifyValidHandle(safeProvHandle);
        byte[] impType = new byte[4];
        int cb = 4;
        SafeKeyHandle safeKeyHandle = SafeKeyHandle.InvalidHandle;
        int num = 0;
        int num2 = 0;
        bool flag = false;
        string result = null;
        try
        {
            switch (keyParam)
            {
            case 3:
                num = GetProviderParameterWorker(safeProvHandle, impType, ref cb, global::Interop.Advapi32.CryptProvParam.PP_IMPTYPE);
                if (!IsFlagBitSet((uint)num, 1u))
                {
                    if (!CryptGetUserKey(safeProvHandle, keyNumber, out safeKeyHandle))
                    {
                        throw GetErrorCode().ToCryptographicException();
                    }
                    byte[] array = null;
                    int num3 = 0;
                    array = new byte[4];
                    cb = 4;
                    if (!global::Interop.Advapi32.CryptGetKeyParam(safeKeyHandle, global::Interop.Advapi32.CryptGetKeyParamFlags.KP_PERMISSIONS, array, ref cb, 0))
                    {
                        throw GetErrorCode().ToCryptographicException();
                    }
                    num3 = BitConverter.ToInt32(array, 0);
                    flag = IsFlagBitSet((uint)num3, 4u);
                }
                else
                {
                    flag = false;
                }
                break;
            case 4:
                num = GetProviderParameterWorker(safeProvHandle, impType, ref cb, global::Interop.Advapi32.CryptProvParam.PP_IMPTYPE);
                flag = IsFlagBitSet((uint)num, 8u);
                break;
            case 5:
            case 7:
                num = GetProviderParameterWorker(safeProvHandle, impType, ref cb, global::Interop.Advapi32.CryptProvParam.PP_IMPTYPE);
                flag = IsFlagBitSet((uint)num, 1u);
                break;
            case 6:
                flag = (CryptGetUserKey(safeProvHandle, keyNumber, out safeKeyHandle) ? true : false);
                break;
            case 8:
            {
                num2 = 1;
                byte[] impType2 = null;
                num = GetProviderParameterWorker(safeProvHandle, impType2, ref cb, global::Interop.Advapi32.CryptProvParam.PP_UNIQUE_CONTAINER);
                impType2 = new byte[cb];
                num = GetProviderParameterWorker(safeProvHandle, impType2, ref cb, global::Interop.Advapi32.CryptProvParam.PP_UNIQUE_CONTAINER);
                result = Encoding.ASCII.GetString(impType2, 0, cb - 1);
                break;
            }
            }
        }
        finally
        {
            safeKeyHandle.Dispose();
        }
        if (num2 != 0)
        {
            return result;
        }
        return flag;
    }
References System.array, System.Text.Encoding.ASCII, Internal.NativeCrypto.CapiHelper.CryptGetUserKey(), System.Runtime.InteropServices.SafeHandle.Dispose(), Internal.NativeCrypto.CapiHelper.GetErrorCode(), Internal.NativeCrypto.CapiHelper.GetProviderParameterWorker(), Internal.NativeCrypto.CapiHelper.IsFlagBitSet(), System.BitConverter.ToInt32(), and Internal.NativeCrypto.CapiHelper.VerifyValidHandle().
Referenced by System.Security.Cryptography.CspKeyContainerInfo.ReadDeviceParameterVerifyContext(), and System.Security.Cryptography.CspKeyContainerInfo.ReadKeyParameterSilent().