Terraria: Internal.NativeCrypto.CapiHelper.AcquireCsp
AcquireCsp()
static void Internal.NativeCrypto.CapiHelper.AcquireCsp (CspParameters cspParameters, out SafeProvHandle safeProvHandle) inline static package
Definition at line 516 of file CapiHelper.cs.
    {
        SafeProvHandle safeProvHandle2;
        int num = OpenCSP(cspParameters, 4026531840u, out safeProvHandle2);
        if (num != 0)
        {
            safeProvHandle2.Dispose();
            throw num.ToCryptographicException();
        }
        safeProvHandle = safeProvHandle2;
    }
References System.Security.Cryptography.SafeProvHandle.Dispose(), and Internal.NativeCrypto.CapiHelper.OpenCSP().
Referenced by Internal.Cryptography.BasicSymmetricCipherCsp.AcquireSafeProviderHandle(), System.Security.Cryptography.DSACryptoServiceProvider.AcquireSafeProviderHandle(), System.Security.Cryptography.RSACryptoServiceProvider.AcquireSafeProviderHandle(), and System.Security.Cryptography.PasswordDeriveBytes.AcquireSafeProviderHandle().