Terraria: Internal.NativeCrypto.CapiHelper.SignValue
SignValue()
static byte[] Internal.NativeCrypto.CapiHelper.SignValue (SafeProvHandle hProv, SafeKeyHandle hKey, int keyNumber, int calgKey, int calgHash, byte[] hash) inline static
Definition at line 1142 of file CapiHelper.cs.
    {
        using SafeHashHandle hHash = hProv.CreateHashHandle(hash, calgHash);
        int pdwSigLen = 0;
        if (!global::Interop.Advapi32.CryptSignHash(hHash, (global::Interop.Advapi32.KeySpec)keyNumber, null, global::Interop.Advapi32.CryptSignAndVerifyHashFlags.None, null, ref pdwSigLen))
        {
            int hRForLastWin32Error = Marshal.GetHRForLastWin32Error();
            throw hRForLastWin32Error.ToCryptographicException();
        }
        byte[] array = new byte[pdwSigLen];
        if (!global::Interop.Advapi32.CryptSignHash(hHash, (global::Interop.Advapi32.KeySpec)keyNumber, null, global::Interop.Advapi32.CryptSignAndVerifyHashFlags.None, array, ref pdwSigLen))
        {
            int hRForLastWin32Error2 = Marshal.GetHRForLastWin32Error();
            throw hRForLastWin32Error2.ToCryptographicException();
        }
        switch (calgKey)
        {
        case 9216:
            Array.Reverse(array);
            break;
        case 8704:
            ReverseDsaSignature(array, pdwSigLen);
            break;
        default:
            throw new InvalidOperationException();
        }
        return array;
    }
References System.array, System.Runtime.InteropServices.Marshal.GetHRForLastWin32Error(), System.Array.Reverse(), and Internal.NativeCrypto.CapiHelper.ReverseDsaSignature().
Referenced by System.Security.Cryptography.RSACryptoServiceProvider.SignHash(), and System.Security.Cryptography.DSACryptoServiceProvider.SignHash().