Terraria: Internal.NativeCrypto.CapiHelper.GetDefaultProvider
GetDefaultProvider()
static string Internal.NativeCrypto.CapiHelper.GetDefaultProvider (int dwType) inline static package
Definition at line 455 of file CapiHelper.cs.
    {
        int pcbProvName = 0;
        if (!global::Interop.Advapi32.CryptGetDefaultProvider(dwType, IntPtr.Zero, global::Interop.Advapi32.GetDefaultProviderFlags.CRYPT_MACHINE_DEFAULT, null, ref pcbProvName))
        {
            throw GetErrorCode().ToCryptographicException();
        }
        StringBuilder stringBuilder = new StringBuilder(pcbProvName);
        if (!global::Interop.Advapi32.CryptGetDefaultProvider(dwType, IntPtr.Zero, global::Interop.Advapi32.GetDefaultProviderFlags.CRYPT_MACHINE_DEFAULT, stringBuilder, ref pcbProvName))
        {
            throw GetErrorCode().ToCryptographicException();
        }
        string text = stringBuilder.ToString();
        string text2 = null;
        switch (dwType)
        {
        case 1:
            text2 = UpgradeRSA(dwType, text);
            break;
        case 13:
            text2 = UpgradeDSS(dwType, text);
            break;
        }
        if (text2 == null)
        {
            return text;
        }
        return text2;
    }
References Internal.NativeCrypto.CapiHelper.GetErrorCode(), System.text, System.Text.StringBuilder.ToString(), Internal.NativeCrypto.CapiHelper.UpgradeDSS(), Internal.NativeCrypto.CapiHelper.UpgradeRSA(), and System.IntPtr.Zero.
Referenced by Internal.NativeCrypto.CapiHelper.OpenCSP().