Terraria: Internal.NativeCrypto.CapiHelper.WriteKeyBlobHeader
WriteKeyBlobHeader() [1/2]
static void Internal.NativeCrypto.CapiHelper.WriteKeyBlobHeader (DSAParameters dsaParameters, BinaryWriter bw, bool isPrivate, out bool isV3) inline static private
Definition at line 204 of file CapiHelper.cs.
    {
        isV3 = false;
        byte value = 2;
        if ((dsaParameters.Y != null && isPrivate) || (dsaParameters.Y != null && dsaParameters.J != null))
        {
            isV3 = true;
            value = 3;
        }
        bw.Write((byte)(isPrivate ? 7u : 6u));
        bw.Write(value);
        bw.Write((ushort)0);
        bw.Write(8704);
    }
References System.Security.Cryptography.DSAParameters.J, System.value, System.IO.BinaryWriter.Write(), and System.Security.Cryptography.DSAParameters.Y.
Referenced by Internal.NativeCrypto.CapiHelper.ToKeyBlob(), and Internal.NativeCrypto.CapiHelper.ToPlainTextKeyBlob().