Terraria: Terraria.GameContent.RGB.JungleShader.ProcessHighDetail
ProcessHighDetail()
void Terraria.GameContent.RGB.JungleShader.ProcessHighDetail (RgbDevice device, Fragment fragment, EffectDetailLevel quality, float time) inline private
Definition at line 34 of file JungleShader.cs.
    {
        //IL_0001: Unknown result type (might be due to invalid IL or missing references)
        //IL_0009: Unknown result type (might be due to invalid IL or missing references)
        //IL_000f: Invalid comparison between Unknown and I4
        bool flag = (int)device.Type == 0 || (int)device.Type == 6;
        for (int i = 0; i < fragment.Count; i++)
        {
            Vector2 canvasPositionOfIndex = fragment.GetCanvasPositionOfIndex(i);
            Point gridPositionOfIndex = fragment.GetGridPositionOfIndex(i);
            float dynamicNoise = NoiseHelper.GetDynamicNoise(canvasPositionOfIndex * 0.3f, time / 5f);
            dynamicNoise = Math.Max(0f, 1f - dynamicNoise * 2.5f);
            Vector4 vector = Vector4.Lerp(_backgroundColor, _sporeColor, dynamicNoise);
            if (flag)
            {
                float dynamicNoise2 = NoiseHelper.GetDynamicNoise(gridPositionOfIndex.X, gridPositionOfIndex.Y, time / 100f);
                dynamicNoise2 = Math.Max(0f, 1f - dynamicNoise2 * 20f);
                vector = Vector4.Lerp(vector, _flowerColors[((gridPositionOfIndex.Y * 47 + gridPositionOfIndex.X) % 5 + 5) % 5], dynamicNoise2);
            }
            fragment.SetColor(i, vector);
        }
    }
References Terraria.GameContent.RGB.JungleShader._backgroundColor, Terraria.GameContent.RGB.JungleShader._flowerColors, Terraria.GameContent.RGB.JungleShader._sporeColor, ReLogic.Peripherals.RGB.Fragment.Count, ReLogic.Peripherals.RGB.Fragment.GetCanvasPositionOfIndex(), Terraria.GameContent.RGB.NoiseHelper.GetDynamicNoise(), ReLogic.Peripherals.RGB.Fragment.GetGridPositionOfIndex(), Microsoft.Xna.Framework.Vector4.Lerp(), System.Math.Max(), ReLogic.Peripherals.RGB.Fragment.SetColor(), ReLogic.Peripherals.RGB.RgbDevice.Type, Microsoft.Xna.Framework.Point.X, and Microsoft.Xna.Framework.Point.Y.