Terraria: System.Xml.Xsl.Xslt.ReferenceReplacer.Replace
Replace()
QilNode System.Xml.Xsl.Xslt.ReferenceReplacer.Replace (QilNode expr, QilReference lookFor, QilReference replaceBy) inline
Definition at line 16 of file ReferenceReplacer.cs.
    {
        QilDepthChecker.Check(expr);
        _lookFor = lookFor;
        _replaceBy = replaceBy;
        return VisitAssumeReference(expr);
    }
References System.Xml.Xsl.Xslt.ReferenceReplacer._lookFor, System.Xml.Xsl.Xslt.ReferenceReplacer._replaceBy, System.Xml.Xsl.Qil.QilDepthChecker.Check(), System.Xml.Dictionary, and System.Xml.Xsl.Qil.QilVisitor.VisitAssumeReference().
Referenced by System.Xml.Xsl.Xslt.MatcherBuilder.MatchPattern(), and System.Xml.Xsl.Xslt.QilGenerator.MatchPattern().