Terraria: Terraria.GameContent.Drawing.ParticleOrchestraSettings.DeserializeFrom
DeserializeFrom()
void Terraria.GameContent.Drawing.ParticleOrchestraSettings.DeserializeFrom (BinaryReader reader) inline
Definition at line 26 of file ParticleOrchestraSettings.cs.
    {
        PositionInWorld = reader.ReadVector2();
        MovementVector = reader.ReadVector2();
        UniqueInfoPiece = reader.ReadInt32();
        IndexOfPlayerWhoInvokedThis = reader.ReadByte();
    }
References Terraria.GameContent.Drawing.ParticleOrchestraSettings.IndexOfPlayerWhoInvokedThis, Terraria.GameContent.Drawing.ParticleOrchestraSettings.MovementVector, Terraria.GameContent.Drawing.ParticleOrchestraSettings.PositionInWorld, System.IO.BinaryReader.ReadByte(), System.IO.BinaryReader.ReadInt32(), and Terraria.GameContent.Drawing.ParticleOrchestraSettings.UniqueInfoPiece.
Referenced by Terraria.GameContent.NetModules.NetParticlesModule.Deserialize().