Terraria: System.Xml.XmlWriterSettings.Initialize
Initialize()
void System.Xml.XmlWriterSettings.Initialize () inline private
Definition at line 554 of file XmlWriterSettings.cs.
    {
        _encoding = System.Text.Encoding.UTF8;
        _omitXmlDecl = false;
        _newLineHandling = NewLineHandling.Replace;
        _newLineChars = Environment.NewLine;
        _indent = TriState.Unknown;
        _indentChars = "  ";
        _newLineOnAttributes = false;
        _closeOutput = false;
        _namespaceHandling = NamespaceHandling.Default;
        _conformanceLevel = ConformanceLevel.Document;
        _checkCharacters = true;
        _writeEndDocumentOnClose = true;
        _outputMethod = XmlOutputMethod.Xml;
        _cdataSections.Clear();
        _mergeCDataSections = false;
        _mediaType = null;
        _docTypeSystem = null;
        _docTypePublic = null;
        _standalone = XmlStandalone.Omit;
        _doNotEscapeUriAttributes = false;
        _useAsync = false;
        _isReadOnly = false;
    }
References System.Xml.XmlWriterSettings._cdataSections, System.Xml.XmlWriterSettings._checkCharacters, System.Xml.XmlWriterSettings._closeOutput, System.Xml.XmlWriterSettings._conformanceLevel, System.Xml.XmlWriterSettings._docTypePublic, System.Xml.XmlWriterSettings._docTypeSystem, System.Xml.XmlWriterSettings._doNotEscapeUriAttributes, System.Xml.XmlWriterSettings._encoding, System.Xml.XmlWriterSettings._indent, System.Xml.XmlWriterSettings._indentChars, System.Xml.XmlWriterSettings._isReadOnly, System.Xml.XmlWriterSettings._mediaType, System.Xml.XmlWriterSettings._mergeCDataSections, System.Xml.XmlWriterSettings._namespaceHandling, System.Xml.XmlWriterSettings._newLineChars, System.Xml.XmlWriterSettings._newLineHandling, System.Xml.XmlWriterSettings._newLineOnAttributes, System.Xml.XmlWriterSettings._omitXmlDecl, System.Xml.XmlWriterSettings._outputMethod, System.Xml.XmlWriterSettings._standalone, System.Xml.XmlWriterSettings._useAsync, System.Xml.XmlWriterSettings._writeEndDocumentOnClose, System.Collections.Generic.Dictionary< TKey, TValue >.Clear(), System.Environment.NewLine, and System.Text.Encoding.UTF8.
Referenced by System.Xml.XmlWriterSettings.XmlWriterSettings(), and System.Xml.XmlWriterSettings.Reset().