Terraria: System.Xml.XmlWriterSettings.CreateWriter
CreateWriter() [2/4]
XmlWriter System.Xml.XmlWriterSettings.CreateWriter (string outputFileName) inline package
Definition at line 414 of file XmlWriterSettings.cs.
    {
        if (outputFileName == null)
        {
            throw new ArgumentNullException("outputFileName");
        }
        XmlWriterSettings xmlWriterSettings = this;
        if (!xmlWriterSettings.CloseOutput)
        {
            xmlWriterSettings = xmlWriterSettings.Clone();
            xmlWriterSettings.CloseOutput = true;
        }
        FileStream fileStream = null;
        try
        {
            fileStream = new FileStream(outputFileName, FileMode.Create, FileAccess.Write, FileShare.Read, 4096, _useAsync);
            return xmlWriterSettings.CreateWriter(fileStream);
        }
        catch
        {
            fileStream?.Dispose();
            throw;
        }
    }
References System.Xml.XmlWriterSettings._useAsync, and System.Xml.Dictionary.
Referenced by System.Xml.XmlWriter.Create(), System.Xml.XmlWriter.Create(), System.Xml.XmlWriter.Create(), System.Xml.XmlWriter.Create(), and System.Xml.XmlWriter.Create().