Terraria: System.Xml.XmlWriterSettings.XmlWriterSettings
XmlWriterSettings() [2/2]
System.Xml.XmlWriterSettings.XmlWriterSettings (XmlQueryDataReader reader) inline package
Definition at line 667 of file XmlWriterSettings.cs.
    {
        Encoding = System.Text.Encoding.GetEncoding(reader.ReadInt32());
        OmitXmlDeclaration = reader.ReadBoolean();
        NewLineHandling = (NewLineHandling)reader.ReadSByte(0, 2);
        NewLineChars = reader.ReadStringQ();
        IndentInternal = (TriState)reader.ReadSByte(-1, 1);
        IndentChars = reader.ReadStringQ();
        NewLineOnAttributes = reader.ReadBoolean();
        CloseOutput = reader.ReadBoolean();
        ConformanceLevel = (ConformanceLevel)reader.ReadSByte(0, 2);
        CheckCharacters = reader.ReadBoolean();
        _outputMethod = (XmlOutputMethod)reader.ReadSByte(0, 3);
        int num = reader.ReadInt32();
        _cdataSections = new List<XmlQualifiedName>(num);
        for (int i = 0; i < num; i++)
        {
            _cdataSections.Add(new XmlQualifiedName(reader.ReadString(), reader.ReadString()));
        }
        _mergeCDataSections = reader.ReadBoolean();
        _mediaType = reader.ReadStringQ();
        _docTypeSystem = reader.ReadStringQ();
        _docTypePublic = reader.ReadStringQ();
        Standalone = (XmlStandalone)reader.ReadSByte(0, 2);
        _autoXmlDecl = reader.ReadBoolean();
        ReadOnly = reader.ReadBoolean();
    }
References System.Xml.XmlWriterSettings._autoXmlDecl, System.Xml.XmlWriterSettings._cdataSections, System.Xml.XmlWriterSettings._docTypePublic, System.Xml.XmlWriterSettings._docTypeSystem, System.Xml.XmlWriterSettings._mediaType, System.Xml.XmlWriterSettings._mergeCDataSections, System.Xml.XmlWriterSettings._outputMethod, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Xml.XmlWriterSettings.CheckCharacters, System.Xml.XmlWriterSettings.CloseOutput, System.Xml.XmlWriterSettings.ConformanceLevel, System.Xml.Dictionary, System.Text.Encoding.GetEncoding(), System.Xml.XmlWriterSettings.IndentChars, System.Xml.XmlWriterSettings.IndentInternal, System.Xml.XmlWriterSettings.NewLineChars, System.Xml.XmlWriterSettings.NewLineHandling, System.Xml.XmlWriterSettings.NewLineOnAttributes, System.Xml.XmlWriterSettings.OmitXmlDeclaration, System.IO.BinaryReader.ReadBoolean(), System.IO.BinaryReader.ReadInt32(), System.Xml.XmlWriterSettings.ReadOnly, System.Xml.Xsl.Runtime.XmlQueryDataReader.ReadSByte(), System.IO.BinaryReader.ReadString(), System.Xml.Xsl.Runtime.XmlQueryDataReader.ReadStringQ(), and System.Xml.XmlWriterSettings.Standalone.