Terraria: System.Net.Mail.Message.PrepareEnvelopeHeaders
PrepareEnvelopeHeaders()
void System.Net.Mail.Message.PrepareEnvelopeHeaders (bool sendEnvelope, bool allowUnicode) inline package
Definition at line 348 of file Message.cs.
    {
        if (_headersEncoding == null)
        {
            _headersEncoding = Encoding.GetEncoding("utf-8");
        }
        EncodeHeaders(EnvelopeHeaders, allowUnicode);
        string @string = MailHeaderInfo.GetString(MailHeaderID.XSender);
        if (!IsHeaderSet(@string))
        {
            MailAddress mailAddress = Sender ?? From;
            EnvelopeHeaders.InternalSet(@string, mailAddress.Encode(@string.Length, allowUnicode));
        }
        string string2 = MailHeaderInfo.GetString(MailHeaderID.XReceiver);
        EnvelopeHeaders.Remove(string2);
        foreach (MailAddress item in To)
        {
            EnvelopeHeaders.InternalAdd(string2, item.Encode(string2.Length, allowUnicode));
        }
        foreach (MailAddress item2 in CC)
        {
            EnvelopeHeaders.InternalAdd(string2, item2.Encode(string2.Length, allowUnicode));
        }
        foreach (MailAddress item3 in Bcc)
        {
            EnvelopeHeaders.InternalAdd(string2, item3.Encode(string2.Length, allowUnicode));
        }
    }
References System.Net.Mail.Message._headersEncoding, System.Net.Mail.Message.Bcc, System.Net.Mail.Message.CC, System.Net.Mail.MailAddress.Encode(), System.Net.Mail.Message.EncodeHeaders(), System.Net.Mail.Message.EnvelopeHeaders, System.Net.Mail.Message.From, System.Text.Encoding.GetEncoding(), System.Net.Mail.MailHeaderInfo.GetString(), System.Net.Mime.HeaderCollection.InternalAdd(), System.Net.Mime.HeaderCollection.InternalSet(), System.Net.Mail.Message.IsHeaderSet(), System.item, System.Net.Mime.HeaderCollection.Remove(), System.Net.Mail.Message.Sender, and System.Net.Mail.Message.To.
Referenced by System.Net.Mail.Message.Send().