Terraria: System.Net.Mail.Message.BeginSend
BeginSend()
IAsyncResult System.Net.Mail.Message.BeginSend (BaseWriter writer, bool sendEnvelope, bool allowUnicode, AsyncCallback callback, object state) inline package
Definition at line 284 of file Message.cs.
    {
        PrepareHeaders(sendEnvelope, allowUnicode);
        writer.WriteHeaders(Headers, allowUnicode);
        if (Content != null)
        {
            return Content.BeginSend(writer, callback, allowUnicode, state);
        }
        System.Net.LazyAsyncResult lazyAsyncResult = new System.Net.LazyAsyncResult(this, state, callback);
        IAsyncResult asyncResult = writer.BeginGetContentStream(EmptySendCallback, new EmptySendContext(writer, lazyAsyncResult));
        if (asyncResult.CompletedSynchronously)
        {
            writer.EndGetContentStream(asyncResult).Close();
            lazyAsyncResult.InvokeCallback();
        }
        return lazyAsyncResult;
    }
References System.asyncResult, System.Net.Mail.Message.EmptySendCallback(), System.Net.LazyAsyncResult.InvokeCallback(), System.Net.Mail.Message.PrepareHeaders(), System.state, and System.writer.
Referenced by System.Net.Mail.MailMessage.BeginSend().