Terraria: System.Net.Mail.Message.PrepareHeaders
PrepareHeaders()
void System.Net.Mail.Message.PrepareHeaders (bool sendEnvelope, bool allowUnicode) inline package
Definition at line 377 of file Message.cs.
    {
        if (_headersEncoding == null)
        {
            _headersEncoding = Encoding.GetEncoding("utf-8");
        }
        Headers.Remove(MailHeaderInfo.GetString(MailHeaderID.ContentType));
        Headers[MailHeaderInfo.GetString(MailHeaderID.MimeVersion)] = "1.0";
        string @string = MailHeaderInfo.GetString(MailHeaderID.Sender);
        if (Sender != null)
        {
            Headers.InternalAdd(@string, Sender.Encode(@string.Length, allowUnicode));
        }
        else
        {
            Headers.Remove(@string);
        }
        @string = MailHeaderInfo.GetString(MailHeaderID.From);
        Headers.InternalAdd(@string, From.Encode(@string.Length, allowUnicode));
        @string = MailHeaderInfo.GetString(MailHeaderID.To);
        if (To.Count > 0)
        {
            Headers.InternalAdd(@string, To.Encode(@string.Length, allowUnicode));
        }
        else
        {
            Headers.Remove(@string);
        }
        @string = MailHeaderInfo.GetString(MailHeaderID.Cc);
        if (CC.Count > 0)
        {
            Headers.InternalAdd(@string, CC.Encode(@string.Length, allowUnicode));
        }
        else
        {
            Headers.Remove(@string);
        }
        @string = MailHeaderInfo.GetString(MailHeaderID.ReplyTo);
        if (ReplyTo != null)
        {
            Headers.InternalAdd(@string, ReplyTo.Encode(@string.Length, allowUnicode));
        }
        else if (ReplyToList.Count > 0)
        {
            Headers.InternalAdd(@string, ReplyToList.Encode(@string.Length, allowUnicode));
        }
        else
        {
            Headers.Remove(@string);
        }
        Headers.Remove(MailHeaderInfo.GetString(MailHeaderID.Bcc));
        if (_priority == MailPriority.High)
        {
            Headers[MailHeaderInfo.GetString(MailHeaderID.XPriority)] = "1";
            Headers[MailHeaderInfo.GetString(MailHeaderID.Priority)] = "urgent";
            Headers[MailHeaderInfo.GetString(MailHeaderID.Importance)] = "high";
        }
        else if (_priority == MailPriority.Low)
        {
            Headers[MailHeaderInfo.GetString(MailHeaderID.XPriority)] = "5";
            Headers[MailHeaderInfo.GetString(MailHeaderID.Priority)] = "non-urgent";
            Headers[MailHeaderInfo.GetString(MailHeaderID.Importance)] = "low";
        }
        else if (_priority != (MailPriority)(-1))
        {
            Headers.Remove(MailHeaderInfo.GetString(MailHeaderID.XPriority));
            Headers.Remove(MailHeaderInfo.GetString(MailHeaderID.Priority));
            Headers.Remove(MailHeaderInfo.GetString(MailHeaderID.Importance));
        }
        Headers.InternalAdd(MailHeaderInfo.GetString(MailHeaderID.Date), MailBnfHelper.GetDateTimeString(DateTime.Now, null));
        @string = MailHeaderInfo.GetString(MailHeaderID.Subject);
        if (!string.IsNullOrEmpty(_subject))
        {
            if (allowUnicode)
            {
                Headers.InternalAdd(@string, _subject);
            }
            else
            {
                Headers.InternalAdd(@string, MimeBasePart.EncodeHeaderValue(_subject, _subjectEncoding, MimeBasePart.ShouldUseBase64Encoding(_subjectEncoding), @string.Length));
            }
        }
        else
        {
            Headers.Remove(@string);
        }
        EncodeHeaders(_headers, allowUnicode);
    }
References System.Net.Mail.Message._headers, System.Net.Mail.Message._headersEncoding, System.Net.Mail.Message._priority, System.Net.Mail.Message._subject, System.Net.Mail.Message._subjectEncoding, System.Net.Mail.Message.CC, System.Collections.ObjectModel.Collection< T >.Count, System.Net.Mail.MailAddress.Encode(), System.Net.Mail.MailAddressCollection.Encode(), System.Net.Mail.Message.EncodeHeaders(), System.Net.Mime.MimeBasePart.EncodeHeaderValue(), System.Net.Mail.Message.From, System.Net.Mime.MailBnfHelper.GetDateTimeString(), System.Text.Encoding.GetEncoding(), System.Net.Mail.MailHeaderInfo.GetString(), System.DateTime.Now, System.Net.Mail.Message.ReplyTo, System.Net.Mail.Message.ReplyToList, System.Net.Mail.Message.Sender, System.Net.Mime.MimeBasePart.ShouldUseBase64Encoding(), and System.Net.Mail.Message.To.
Referenced by System.Net.Mail.Message.BeginSend(), and System.Net.Mail.Message.Send().