Terraria: System.Net.Mail.Message.Send
Send()
void System.Net.Mail.Message.Send (BaseWriter writer, bool sendEnvelope, bool allowUnicode) inline package
Definition at line 329 of file Message.cs.
    {
        if (sendEnvelope)
        {
            PrepareEnvelopeHeaders(sendEnvelope, allowUnicode);
            writer.WriteHeaders(EnvelopeHeaders, allowUnicode);
        }
        PrepareHeaders(sendEnvelope, allowUnicode);
        writer.WriteHeaders(Headers, allowUnicode);
        if (Content != null)
        {
            Content.Send(writer, allowUnicode);
        }
        else
        {
            writer.GetContentStream().Close();
        }
    }
References System.Net.Mail.Message.EnvelopeHeaders, System.Net.Mail.Message.PrepareEnvelopeHeaders(), System.Net.Mail.Message.PrepareHeaders(), and System.writer.
Referenced by System.Net.Mail.MailMessage.Send().