Terraria: System.Net.Mail.Message.EncodeHeaders
EncodeHeaders()
void System.Net.Mail.Message.EncodeHeaders (HeaderCollection headers, bool allowUnicode) inline package
Definition at line 466 of file Message.cs.
    {
        if (_headersEncoding == null)
        {
            _headersEncoding = Encoding.GetEncoding("utf-8");
        }
        for (int i = 0; i < headers.Count; i++)
        {
            string key = headers.GetKey(i);
            if (!MailHeaderInfo.IsUserSettable(key))
            {
                continue;
            }
            string[] values = headers.GetValues(key);
            string empty = string.Empty;
            for (int j = 0; j < values.Length; j++)
            {
                empty = ((!MimeBasePart.IsAscii(values[j], permitCROrLF: false) && (!allowUnicode || !MailHeaderInfo.AllowsUnicode(key) || MailBnfHelper.HasCROrLF(values[j]))) ? MimeBasePart.EncodeHeaderValue(values[j], _headersEncoding, MimeBasePart.ShouldUseBase64Encoding(_headersEncoding), key.Length) : values[j]);
                if (j == 0)
                {
                    headers.Set(key, empty);
                }
                else
                {
                    headers.Add(key, empty);
                }
            }
        }
    }
References System.Net.Mail.Message._headersEncoding, System.Net.Mime.HeaderCollection.Add(), System.Net.Mail.MailHeaderInfo.AllowsUnicode(), System.Collections.Specialized.NameObjectCollectionBase.Count, System.Net.Mime.MimeBasePart.EncodeHeaderValue(), System.Text.Encoding.GetEncoding(), System.Collections.Specialized.NameValueCollection.GetKey(), System.Net.Mime.HeaderCollection.GetValues(), System.Net.Mime.MailBnfHelper.HasCROrLF(), System.Net.Mime.MimeBasePart.IsAscii(), System.Net.Mail.MailHeaderInfo.IsUserSettable(), System.key, System.Net.Mime.HeaderCollection.Set(), System.Net.Mime.MimeBasePart.ShouldUseBase64Encoding(), and System.values.
Referenced by System.Net.Mail.Message.PrepareEnvelopeHeaders(), and System.Net.Mail.Message.PrepareHeaders().