Terraria: Terraria.GameContent.Biomes.MarbleBiome.PlaceSlab
PlaceSlab()
void Terraria.GameContent.Biomes.MarbleBiome.PlaceSlab (Slab slab, int originX, int originY, int scale) inline private
    {
        ushort num = 367;
        ushort wall = 178;
        if (WorldGen.drunkWorldGen)
        {
            num = 368;
            wall = 180;
        }
        int num2 = -1;
        int num3 = scale + 1;
        int num4 = 0;
        int num5 = scale;
        for (int i = num2; i < num3; i++)
        {
            if ((i == num2 || i == num3 - 1) && WorldGen.genRand.Next(2) == 0)
            {
                continue;
            }
            if (WorldGen.genRand.Next(2) == 0)
            {
                num4--;
            }
            if (WorldGen.genRand.Next(2) == 0)
            {
                num5++;
            }
            for (int j = num4; j < num5; j++)
            {
                Tile tile = GenBase._tiles[originX + i, originY + j];
                tile.ResetToType(TileID.Sets.Ore[tile.type] ? tile.type : num);
                bool active = slab.State(i, j, scale);
                tile.active(active);
                if (slab.HasWall)
                {
                    tile.wall = wall;
                }
                WorldUtils.TileFrame(originX + i, originY + j, frameNeighbors: true);
                WorldGen.SquareWallFrame(originX + i, originY + j);
                Tile.SmoothSlope(originX + i, originY + j);
                if (WorldGen.SolidTile(originX + i, originY + j - 1) && GenBase._random.Next(4) == 0)
                {
                    WorldGen.PlaceTight(originX + i, originY + j);
                }
                if (WorldGen.SolidTile(originX + i, originY + j) && GenBase._random.Next(4) == 0)
                {
                    WorldGen.PlaceTight(originX + i, originY + j - 1);
                }
            }
        }
    }
References Terraria.WorldBuilding.GenBase._random, Terraria.WorldBuilding.GenBase._tiles, Terraria.Tile.active(), Terraria.WorldGen.drunkWorldGen, Terraria.WorldGen.genRand, Terraria.GameContent.Biomes.MarbleBiome.Slab.HasWall, Terraria.ID.TileID.Sets.Ore, Terraria.WorldGen.PlaceTight(), Terraria.Tile.ResetToType(), Terraria.Tile.SmoothSlope(), Terraria.WorldGen.SolidTile(), Terraria.WorldGen.SquareWallFrame(), Terraria.GameContent.Biomes.MarbleBiome.Slab.State, Terraria.WorldBuilding.WorldUtils.TileFrame(), and Terraria.Tile.type.
Referenced by Terraria.GameContent.Biomes.MarbleBiome.Place().