Terraria: SepiaScreenShaderData.GetDaylightPowers
GetDaylightPowers()
static void SepiaScreenShaderData.GetDaylightPowers (out float nightlightPower, out float daylightPower, out float moonPower, out float dawnPower) inline static private
     {
         nightlightPower = 0f;
         daylightPower = 0f;
         moonPower = 0f;
         Vector2 dayTimeAsDirectionIn24HClock = Utils.GetDayTimeAsDirectionIn24HClock();
         Vector2 dayTimeAsDirectionIn24HClock2 = Utils.GetDayTimeAsDirectionIn24HClock(4.5f);
         Vector2 dayTimeAsDirectionIn24HClock3 = Utils.GetDayTimeAsDirectionIn24HClock(0f);
         float fromValue = Vector2.Dot(dayTimeAsDirectionIn24HClock, dayTimeAsDirectionIn24HClock3);
         float fromValue2 = Vector2.Dot(dayTimeAsDirectionIn24HClock, dayTimeAsDirectionIn24HClock2);
         nightlightPower = Utils.Remap(fromValue, -0.2f, 0.1f, 0f, 1f);
         daylightPower = Utils.Remap(fromValue, 0.1f, -1f, 0f, 1f);
         dawnPower = Utils.Remap(fromValue2, 0.66f, 1f, 0f, 1f);
         if (!Main.dayTime)
         {
             float num = (float)(Main.time / 32400.0) * 2f;
             if (num > 1f)
             {
                 num = 2f - num;
             }
             moonPower = Utils.Remap(num, 0f, 0.25f, 0f, 1f);
         }
     }
References Main.dayTime, Utils.GetDayTimeAsDirectionIn24HClock(), Utils.Remap(), and Main.time.
Referenced by Update().