Terraria: NPCWasChatWithTracker.RegisterChatStartWith
RegisterChatStartWith()
void NPCWasChatWithTracker.RegisterChatStartWith (NPC npc) inline
     {
         string bestiaryCreditId = npc.GetBestiaryCreditId();
         bool flag = !_chattedWithPlayer.Contains(bestiaryCreditId);
         lock (_entryCreationLock)
         {
             _chattedWithPlayer.Add(bestiaryCreditId);
         }
         if (Main.netMode == 2 && flag)
         {
             NetManager.Instance.Broadcast(NetBestiaryModule.SerializeChat(npc.netID));
         }
     }
References _chattedWithPlayer, _entryCreationLock, NetManager.Broadcast(), NPC.GetBestiaryCreditId(), NetManager.Instance, NPC.netID, Main.netMode, and NetBestiaryModule.SerializeChat().
Referenced by NPC.AI_000_TransformBoundNPC(), and Player.SetTalkNPC().