Terraria: System.Net.WebSockets.WebSocketProtocolComponent.ThrowOnError
ThrowOnError()
static void System.Net.WebSockets.WebSocketProtocolComponent.ThrowOnError (int errorCode) inline static private
Definition at line 341 of file WebSocketProtocolComponent.cs.
    {
        if (Succeeded(errorCode))
        {
            return;
        }
        throw new WebSocketException(errorCode);
    }
References System.Succeeded.
Referenced by System.Net.WebSockets.WebSocketProtocolComponent.GetSupportedVersion(), System.Net.WebSockets.WebSocketProtocolComponent.WebSocketCreateServerHandle(), System.Net.WebSockets.WebSocketProtocolComponent.WebSocketGetAction(), System.Net.WebSockets.WebSocketProtocolComponent.WebSocketReceive(), System.Net.WebSockets.WebSocketProtocolComponent.WebSocketSend(), and System.Net.WebSockets.WebSocketProtocolComponent.WebSocketSendWithoutBody().