Terraria: System.Net.WebSockets.WebSocketProtocolComponent.WebSocketGetAction
WebSocketGetAction()
static void System.Net.WebSockets.WebSocketProtocolComponent.WebSocketGetAction (WebSocketBase webSocket, ActionQueue actionQueue, global::Interop::WebSocket::Buffer[] dataBuffers, ref uint dataBufferCount, out Action action, out BufferType bufferType, out IntPtr actionContext) inline static package
Definition at line 245 of file WebSocketProtocolComponent.cs.
    {
        action = Action.NoAction;
        bufferType = BufferType.None;
        actionContext = IntPtr.Zero;
        ThrowIfSessionHandleClosed(webSocket);
        int errorCode;
        try
        {
            errorCode = global::Interop.WebSocket.WebSocketGetAction(webSocket.SessionHandle, actionQueue, dataBuffers, ref dataBufferCount, out action, out bufferType, out var _, out actionContext);
        }
        catch (ObjectDisposedException innerException)
        {
            throw ConvertObjectDisposedException(webSocket, innerException);
        }
        ThrowOnError(errorCode);
        webSocket.ValidateNativeBuffers(action, bufferType, dataBuffers, dataBufferCount);
    }
References System.action, System.Net.WebSockets.WebSocketProtocolComponent.ConvertObjectDisposedException(), System.Net.WebSockets.WebSocketBase.SessionHandle, System.Net.WebSockets.WebSocketProtocolComponent.ThrowIfSessionHandleClosed(), System.Net.WebSockets.WebSocketProtocolComponent.ThrowOnError(), System.Net.WebSockets.WebSocketBase.ValidateNativeBuffers(), and System.IntPtr.Zero.
Referenced by System.Net.WebSockets.WebSocketBase.WebSocketOperation.Process().