Terraria: System.Net.WebSockets.WebSocketProtocolComponent.WebSocketReceive
WebSocketReceive()
static void System.Net.WebSockets.WebSocketProtocolComponent.WebSocketReceive (WebSocketBase webSocket) inline static package
Definition at line 230 of file WebSocketProtocolComponent.cs.
    {
        ThrowIfSessionHandleClosed(webSocket);
        int errorCode;
        try
        {
            errorCode = global::Interop.WebSocket.WebSocketReceive(webSocket.SessionHandle, IntPtr.Zero, IntPtr.Zero);
        }
        catch (ObjectDisposedException innerException)
        {
            throw ConvertObjectDisposedException(webSocket, innerException);
        }
        ThrowOnError(errorCode);
    }
References System.Net.WebSockets.WebSocketProtocolComponent.ConvertObjectDisposedException(), System.Net.WebSockets.WebSocketBase.SessionHandle, System.Net.WebSockets.WebSocketProtocolComponent.ThrowIfSessionHandleClosed(), System.Net.WebSockets.WebSocketProtocolComponent.ThrowOnError(), and System.IntPtr.Zero.
Referenced by System.Net.WebSockets.WebSocketBase.WebSocketOperation.ReceiveOperation.ShouldContinue().