Terraria: System.Runtime.Serialization.Json.JsonDataContract.JsonDataContractCriticalHelper.AddCollectionItemContractsToKnownDataContracts
AddCollectionItemContractsToKnownDataContracts()
void System.Runtime.Serialization.Json.JsonDataContract.JsonDataContractCriticalHelper.AddCollectionItemContractsToKnownDataContracts () inline private inherited
Definition at line 150 of file JsonDataContract.cs.
        {
            if (_traditionalDataContract.KnownDataContracts == null)
            {
                return;
            }
            foreach (KeyValuePair<XmlQualifiedName, DataContract> knownDataContract in _traditionalDataContract.KnownDataContracts)
            {
                CollectionDataContract collectionDataContract = knownDataContract.Value as CollectionDataContract;
                while (collectionDataContract != null)
                {
                    DataContract itemContract = collectionDataContract.ItemContract;
                    if (_knownDataContracts == null)
                    {
                        _knownDataContracts = new Dictionary<XmlQualifiedName, DataContract>();
                    }
                    _knownDataContracts.TryAdd(itemContract.StableName, itemContract);
                    if (collectionDataContract.ItemType.IsGenericType && collectionDataContract.ItemType.GetGenericTypeDefinition() == typeof(KeyValue<, >))
                    {
                        DataContract dataContract = DataContract.GetDataContract(Globals.TypeOfKeyValuePair.MakeGenericType(collectionDataContract.ItemType.GenericTypeArguments));
                        _knownDataContracts.TryAdd(dataContract.StableName, dataContract);
                    }
                    if (!(itemContract is CollectionDataContract))
                    {
                        break;
                    }
                    collectionDataContract = itemContract as CollectionDataContract;
                }
            }
        }
References System.Runtime.Serialization.Json.JsonDataContract.JsonDataContractCriticalHelper._knownDataContracts, System.Runtime.Serialization.Json.JsonDataContract.JsonDataContractCriticalHelper._traditionalDataContract, System.Runtime.Serialization.Dictionary, System.Runtime.Serialization.DataContract.GetDataContract(), System.Runtime.Serialization.DataContract.KnownDataContracts, System.Collections.Generic.Dictionary< TKey, TValue >.TryAdd(), and System.Runtime.Serialization.Globals.TypeOfKeyValuePair.
Referenced by System.Runtime.Serialization.Json.JsonDataContract.JsonDataContractCriticalHelper.JsonDataContractCriticalHelper().