Terraria: System.Net.WebSockets.WebSocketProtocolComponent.GetSupportedVersion
GetSupportedVersion()
static string System.Net.WebSockets.WebSocketProtocolComponent.GetSupportedVersion () inline static package
Definition at line 133 of file WebSocketProtocolComponent.cs.
    {
        if (!IsSupported)
        {
            HttpWebSocket.ThrowPlatformNotSupportedException_WSPC();
        }
        SafeWebSocketHandle webSocketHandle = null;
        try
        {
            int errorCode = global::Interop.WebSocket.WebSocketCreateClientHandle(null, 0u, out webSocketHandle);
            ThrowOnError(errorCode);
            if (webSocketHandle == null || webSocketHandle.IsInvalid)
            {
                HttpWebSocket.ThrowPlatformNotSupportedException_WSPC();
            }
            errorCode = global::Interop.WebSocket.WebSocketBeginClientHandshake(webSocketHandle, IntPtr.Zero, 0u, IntPtr.Zero, 0u, s_initialClientRequestHeaders, (uint)s_initialClientRequestHeaders.Length, out var additionalHeadersPtr, out var additionalHeaderCount);
            ThrowOnError(errorCode);
            global::Interop.WebSocket.HttpHeader[] array = MarshalHttpHeaders(additionalHeadersPtr, (int)additionalHeaderCount);
            string result = null;
            global::Interop.WebSocket.HttpHeader[] array2 = array;
            for (int i = 0; i < array2.Length; i++)
            {
                global::Interop.WebSocket.HttpHeader httpHeader = array2[i];
                if (string.Equals(httpHeader.Name, "Sec-WebSocket-Version", StringComparison.OrdinalIgnoreCase))
                {
                    result = httpHeader.Value;
                    break;
                }
            }
            return result;
        }
        finally
        {
            webSocketHandle?.Dispose();
        }
    }
References System.array, System.Runtime.InteropServices.SafeHandle.Dispose(), System.Net.Equals, System.Net.WebSockets.WebSocketProtocolComponent.IsSupported, System.Net.WebSockets.WebSocketProtocolComponent.MarshalHttpHeaders(), System.Net.WebSockets.WebSocketProtocolComponent.s_initialClientRequestHeaders, System.Net.WebSockets.WebSocketProtocolComponent.ThrowOnError(), System.Net.WebSockets.HttpWebSocket.ThrowPlatformNotSupportedException_WSPC(), and System.IntPtr.Zero.
Referenced by System.Net.WebSockets.WebSocketProtocolComponent.WebSocketProtocolComponent().