Terraria: System.Runtime.Serialization.Json.JsonDataContract.JsonDataContractCriticalHelper.GetJsonDataContract
GetJsonDataContract()
static JsonDataContract System.Runtime.Serialization.Json.JsonDataContract.JsonDataContractCriticalHelper.GetJsonDataContract (DataContract traditionalDataContract) inline static inherited
Definition at line 44 of file JsonDataContract.cs.
        {
            int id = GetId(traditionalDataContract.UnderlyingType.TypeHandle);
            JsonDataContract jsonDataContract = s_dataContractCache[id];
            if (jsonDataContract == null)
            {
                jsonDataContract = CreateJsonDataContract(id, traditionalDataContract);
                s_dataContractCache[id] = jsonDataContract;
            }
            return jsonDataContract;
        }
References System.Runtime.Serialization.Json.JsonDataContract.JsonDataContractCriticalHelper.CreateJsonDataContract(), System.Runtime.Serialization.Dictionary, System.Runtime.Serialization.Json.JsonDataContract.JsonDataContractCriticalHelper.GetId(), and System.Runtime.Serialization.Json.JsonDataContract.JsonDataContractCriticalHelper.s_dataContractCache.
Referenced by System.Runtime.Serialization.Json.JsonDataContract.GetJsonDataContract().