Terraria: System.Net.WebSockets.WebSocketProtocolComponent.MarshalAndVerifyHttpHeader
MarshalAndVerifyHttpHeader()
static void System.Net.WebSockets.WebSocketProtocolComponent.MarshalAndVerifyHttpHeader (IntPtr httpHeaderPtr, ref global::Interop::WebSocket::HttpHeader httpHeader) inline static private
Definition at line 298 of file WebSocketProtocolComponent.cs.
    {
        IntPtr intPtr = Marshal.ReadIntPtr(httpHeaderPtr);
        IntPtr ptr = IntPtr.Add(httpHeaderPtr, IntPtr.Size);
        int num = Marshal.ReadInt32(ptr);
        if (intPtr != IntPtr.Zero)
        {
            httpHeader.Name = Marshal.PtrToStringAnsi(intPtr, num);
        }
        if ((httpHeader.Name == null && num != 0) || (httpHeader.Name != null && num != httpHeader.Name.Length))
        {
            throw new AccessViolationException();
        }
        int offset = 2 * IntPtr.Size;
        int offset2 = 3 * IntPtr.Size;
        IntPtr ptr2 = Marshal.ReadIntPtr(IntPtr.Add(httpHeaderPtr, offset));
        ptr = IntPtr.Add(httpHeaderPtr, offset2);
        num = Marshal.ReadInt32(ptr);
        httpHeader.Value = Marshal.PtrToStringAnsi(ptr2, num);
        if ((httpHeader.Value == null && num != 0) || (httpHeader.Value != null && num != httpHeader.Value.Length))
        {
            throw new AccessViolationException();
        }
    }
References System.IntPtr.Add(), System.offset, System.Runtime.InteropServices.Marshal.PtrToStringAnsi(), System.Runtime.InteropServices.Marshal.ReadInt32(), System.Runtime.InteropServices.Marshal.ReadIntPtr(), System.IntPtr.Size, and System.IntPtr.Zero.
Referenced by System.Net.WebSockets.WebSocketProtocolComponent.MarshalHttpHeaders().