Terraria: System.Security.Cryptography.Asn1.ECDomainParameters.DecodeCore
DecodeCore() [1/2]
static void System.Security.Cryptography.Asn1.ECDomainParameters.DecodeCore (ref AsnValueReader reader, ReadOnlyMemory< byte > rebind, out ECDomainParameters decoded) inline static private
Definition at line 72 of file ECDomainParameters.cs.
    {
        decoded = default(ECDomainParameters);
        Asn1Tag asn1Tag = reader.PeekTag();
        if (asn1Tag.HasSameClassAndValue(Asn1Tag.Sequence))
        {
            SpecifiedECDomain.Decode(ref reader, rebind, out var decoded2);
            decoded.Specified = decoded2;
            return;
        }
        if (asn1Tag.HasSameClassAndValue(Asn1Tag.ObjectIdentifier))
        {
            decoded.Named = reader.ReadObjectIdentifier();
            return;
        }
        throw new CryptographicException();
    }
References System.Security.Cryptography.Asn1.SpecifiedECDomain.Decode(), System.Formats.Asn1.Asn1Tag.HasSameClassAndValue(), System.Formats.Asn1.Asn1Tag.ObjectIdentifier, and System.Formats.Asn1.Asn1Tag.Sequence.
Referenced by System.Security.Cryptography.Asn1.ECDomainParameters.Decode(), System.Security.Cryptography.Asn1.ECDomainParameters.Decode(), and System.Security.Cryptography.Asn1.ECDomainParameters.Decode().