Terraria: System.Collections.Immutable.ImmutableHashSet.Builder.Apply
Apply()
void System.Collections.Immutable.ImmutableHashSet< T >.Builder.Apply (MutationResult result) inline private
Definition at line 264 of file ImmutableHashSet.cs.
        {
            Root = result.Root;
            if (result.CountType == CountType.Adjustment)
            {
                _count += result.Count;
            }
            else
            {
                _count = result.Count;
            }
        }
References System.Collections.Immutable.ImmutableHashSet< T >.Builder._count, System.Collections.Immutable.ImmutableHashSet< T >.MutationResult.Count, System.Collections.Immutable.ImmutableHashSet< T >.MutationResult.CountType, System.Collections.Immutable.ImmutableHashSet< T >.Builder.Root, and System.Collections.Immutable.ImmutableHashSet< T >.MutationResult.Root.
Referenced by System.Collections.Immutable.ImmutableHashSet< T >.Builder.Add(), System.Collections.Immutable.ImmutableHashSet< T >.Builder.ExceptWith(), System.Collections.Immutable.ImmutableHashSet< T >.Builder.IntersectWith(), System.Collections.Immutable.ImmutableHashSet< T >.Builder.Remove(), System.Collections.Immutable.ImmutableHashSet< T >.Builder.SymmetricExceptWith(), and System.Collections.Immutable.ImmutableHashSet< T >.Builder.UnionWith().