Terraria: System.IO.StreamBuffer.ResettableValueTaskSource.Wait
Wait()
void System.IO.StreamBuffer.ResettableValueTaskSource.Wait () inline
Definition at line 62 of file StreamBuffer.cs.
        {
            _waitSource.RunContinuationsAsynchronously = false;
            new ValueTask(this, _waitSource.Version).AsTask().GetAwaiter().GetResult();
        }
References System.IO.StreamBuffer.ResettableValueTaskSource._waitSource, System.Threading.Tasks.ValueTask< TResult >.AsTask(), System.Threading.Tasks.Task< TResult >.GetAwaiter(), and System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore< TResult >.Version.
Referenced by System.IO.StreamBuffer.Read(), and System.IO.StreamBuffer.Write().