Terraria: System.Net.ListenerClientCertAsyncResult.Reset
Reset()
unsafe void System.Net.ListenerClientCertAsyncResult.Reset (uint size) inline package
Definition at line 34 of file ListenerClientCertAsyncResult.cs.
    {
        if (size != _size)
        {
            if (_size != 0)
            {
                _boundHandle.FreeNativeOverlapped(_pOverlapped);
            }
            _size = size;
            if (size == 0)
            {
                _pOverlapped = null;
                _memoryBlob = null;
                _backingBuffer = null;
            }
            else
            {
                _backingBuffer = new byte[checked((int)size)];
                _pOverlapped = _boundHandle.AllocateNativeOverlapped(s_IOCallback, this, _backingBuffer);
                _memoryBlob = (global::Interop.HttpApi.HTTP_SSL_CLIENT_CERT_INFO*)(void*)Marshal.UnsafeAddrOfPinnedArrayElement(_backingBuffer, 0);
            }
        }
    }
References System.Net.ListenerClientCertAsyncResult._backingBuffer, System.Net.ListenerClientCertAsyncResult._boundHandle, System.Net.ListenerClientCertAsyncResult._memoryBlob, System.Net.ListenerClientCertAsyncResult._pOverlapped, System.Net.ListenerClientCertAsyncResult._size, System.Threading.ThreadPoolBoundHandle.AllocateNativeOverlapped(), System.Threading.ThreadPoolBoundHandle.FreeNativeOverlapped(), System.Net.ListenerClientCertAsyncResult.s_IOCallback, and System.Runtime.InteropServices.Marshal.UnsafeAddrOfPinnedArrayElement().
Referenced by System.Net.ListenerClientCertAsyncResult.ListenerClientCertAsyncResult().