Terraria: System.Net.ListenerClientCertAsyncResult.IOCompleted
IOCompleted() [1/2]
static unsafe void System.Net.ListenerClientCertAsyncResult.IOCompleted (ListenerClientCertAsyncResult asyncResult, uint errorCode, uint numBytes) inline static private
Definition at line 63 of file ListenerClientCertAsyncResult.cs.
    {
        HttpListenerRequest httpListenerRequest = (HttpListenerRequest)asyncResult.AsyncObject;
        object result = null;
        try
        {
            if (errorCode == 234)
            {
                global::Interop.HttpApi.HTTP_SSL_CLIENT_CERT_INFO* requestBlob = asyncResult.RequestBlob;
                asyncResult.Reset(numBytes + requestBlob->CertEncodedSize);
                uint num = 0u;
                errorCode = global::Interop.HttpApi.HttpReceiveClientCertificate(httpListenerRequest.HttpListenerContext.RequestQueueHandle, httpListenerRequest._connectionId, 0u, asyncResult._memoryBlob, asyncResult._size, &num, asyncResult._pOverlapped);
                switch (errorCode)
                {
                case 0u:
                    if (!HttpListener.SkipIOCPCallbackOnSuccess)
                    {
                        return;
                    }
                    break;
                case 997u:
                    return;
                }
            }
            if (errorCode != 0)
            {
                asyncResult.ErrorCode = (int)errorCode;
                result = new HttpListenerException((int)errorCode);
            }
            else
            {
                global::Interop.HttpApi.HTTP_SSL_CLIENT_CERT_INFO* memoryBlob = asyncResult._memoryBlob;
                if (memoryBlob != null)
                {
                    if (System.Net.NetEventSource.Log.IsEnabled())
                    {
                        System.Net.NetEventSource.Info(null, $"pClientCertInfo:{(IntPtr)memoryBlob} pClientCertInfo->CertFlags: {memoryBlob->CertFlags} pClientCertInfo->CertEncodedSize: {memoryBlob->CertEncodedSize} pClientCertInfo->pCertEncoded: {(IntPtr)memoryBlob->pCertEncoded} pClientCertInfo->Token: {(IntPtr)memoryBlob->Token} pClientCertInfo->CertDeniedByMapper: {memoryBlob->CertDeniedByMapper}", "IOCompleted");
                    }
                    if (memoryBlob->pCertEncoded != null)
                    {
                        try
{
                            byte[] array = new byte[memoryBlob->CertEncodedSize];
                            Marshal.Copy((IntPtr)memoryBlob->pCertEncoded, array, 0, array.Length);
                            X509Certificate2 x509Certificate2 = (httpListenerRequest.ClientCertificate = new X509Certificate2(array));
                            result = x509Certificate2;
                        }
                        catch (CryptographicException ex)
{
                            if (System.Net.NetEventSource.Log.IsEnabled())
{
                                System.Net.NetEventSource.Info(null, $"HttpListenerRequest: {httpListenerRequest} caught CryptographicException: {ex}", "IOCompleted");
                            }
                            result = ex;
                        }
                        catch (SecurityException ex2)
{
                            if (System.Net.NetEventSource.Log.IsEnabled())
{
                                System.Net.NetEventSource.Info(null, $"HttpListenerRequest: {httpListenerRequest} caught SecurityException: {ex2}", "IOCompleted");
                            }
                            result = ex2;
                        }
                    }
                    httpListenerRequest.SetClientCertificateError((int)memoryBlob->CertFlags);
                }
            }
            if (System.Net.NetEventSource.Log.IsEnabled())
            {
                System.Net.NetEventSource.Info(null, "Calling Complete()", "IOCompleted");
            }
        }
        catch (Exception ex3) when (!System.Net.ExceptionCheck.IsFatal(ex3))
        {
            result = ex3;
        }
        finally
        {
            if (errorCode != 997)
            {
                httpListenerRequest.ClientCertState = ListenerClientCertState.Completed;
            }
        }
        asyncResult.InvokeCallback(result);
    }
References System.Net.HttpListenerRequest._connectionId, System.array, System.asyncResult, System.Runtime.InteropServices.Marshal.Copy(), System.Net.HttpListenerRequest.HttpListenerContext, System.Net.NetEventSource.Info(), System.Net.ExceptionCheck.IsFatal(), System.Net.NetEventSource.Log, System.Net.HttpListenerContext.RequestQueueHandle, System.Net.HttpListenerRequest.SetClientCertificateError(), and System.Net.HttpListener.SkipIOCPCallbackOnSuccess.