Terraria: System.IO.StreamBuffer.ResettableValueTaskSource.SignalWaiter
SignalWaiter()
void System.IO.StreamBuffer.ResettableValueTaskSource.SignalWaiter () inline
Definition at line 36 of file StreamBuffer.cs.
        {
            if (Interlocked.Exchange(ref _hasWaiter, 0) == 1)
            {
                _waitSource.SetResult(result: true);
            }
        }
References System.IO.StreamBuffer.ResettableValueTaskSource._hasWaiter, System.IO.StreamBuffer.ResettableValueTaskSource._waitSource, System.Threading.Interlocked.Exchange(), and System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore< TResult >.SetResult().
Referenced by System.IO.StreamBuffer.AbortRead(), System.IO.StreamBuffer.EndWrite(), System.IO.StreamBuffer.TryReadFromBuffer(), and System.IO.StreamBuffer.TryWriteToBuffer().