Terraria: UIBestiaryEntryIcon.DrawSelf
DrawSelf()
override void UIBestiaryEntryIcon.DrawSelf (SpriteBatch spriteBatch) inline protected virtual
Reimplemented from UIElement.
     {
         CalculatedStyle dimensions = GetDimensions();
         bool unlockState = _entry.Icon.GetUnlockState(_collectionInfo);
         bool isHovered = base.IsMouseHovering || ForceHover;
         if (unlockState)
         {
             _entry.Icon.Draw(_collectionInfo, spriteBatch, new EntryIconDrawSettings
             {
                 iconbox = dimensions.ToRectangle(),
                 IsPortrait = _isPortrait,
                 IsHovered = isHovered
             });
         }
         else
         {
             Texture2D value = _notUnlockedTexture.Value;
             spriteBatch.Draw(value, dimensions.Center(), null, Color.White * 0.15f, 0f, value.Size() / 2f, 1f, SpriteEffects.None, 0f);
         }
     }
References _collectionInfo, _entry, _isPortrait, _notUnlockedTexture, CalculatedStyle.Center(), Color, IEntryIcon.Draw(), ForceHover, UIElement.GetDimensions(), IEntryIcon.GetUnlockState(), BestiaryEntry.Icon, CalculatedStyle.ToRectangle(), and Asset< T >.Value.