Terraria: LogitechSingleLightDevice.Present
Present()
override void LogitechSingleLightDevice.Present () inline virtual
Implements RgbDevice.
     {
         //IL_000a: Unknown result type (might be due to invalid IL or missing references)
         //IL_000f: Unknown result type (might be due to invalid IL or missing references)
         //IL_0010: Unknown result type (might be due to invalid IL or missing references)
         //IL_001d: Unknown result type (might be due to invalid IL or missing references)
         //IL_002a: Unknown result type (might be due to invalid IL or missing references)
         if (NativeMethods.LogiLedSetTargetDevice(2))
         {
             Vector4 processedLedColor = GetProcessedLedColor(0);
             NativeMethods.LogiLedSetLighting((int)(processedLedColor.X * 100f), (int)(processedLedColor.Y * 100f), (int)(processedLedColor.Z * 100f));
         }
     }
References RgbDevice.GetProcessedLedColor(), NativeMethods.LogiLedSetLighting(), and NativeMethods.LogiLedSetTargetDevice().