Terraria: System.Net.Http.HttpMessageHandler.Send
Send()
virtual HttpResponseMessage System.Net.Http.HttpMessageHandler.Send (HttpRequestMessage request, CancellationToken cancellationToken) inline package virtual
Reimplemented in System.Net.Http.DelegatingHandler, System.Net.Http.HttpClientHandler, System.Net.Http.HttpMessageHandlerStage, System.Net.Http.MessageProcessingHandler, and System.Net.Http.SocketsHttpHandler.
Definition at line 16 of file HttpMessageHandler.cs.
    {
        throw new NotSupportedException(System.SR.Format(System.SR.net_http_missing_sync_implementation, GetType(), "HttpMessageHandler", "Send"));
    }
References System.SR.Format(), and System.SR.net_http_missing_sync_implementation.
Referenced by System.Net.Http.DelegatingHandler.Send(), System.Net.Http.HttpClientHandler.Send(), System.Net.Http.HttpMessageInvoker.Send(), System.Net.Http.DiagnosticsHandler.SendAsync(), and System.Net.Http.DiagnosticsHandler.SendAsyncCore().