Terraria: System.MathF.Sqrt
Sqrt()
static float System.MathF.Sqrt (float x)
Referenced by System.Numerics.Matrix4x4.CreateBillboard(), System.Numerics.Matrix4x4.CreateConstrainedBillboard(), System.Numerics.Quaternion.CreateFromRotationMatrix(), System.Numerics.Plane.CreateFromVertices(), System.Numerics.Vector2.Distance(), System.Numerics.Vector3.Distance(), System.Numerics.Vector4.Distance(), System.Numerics.Quaternion.Length(), System.Numerics.Vector2.Length(), System.Numerics.Vector3.Length(), System.Numerics.Vector4.Length(), System.Numerics.Quaternion.Lerp(), System.Numerics.Plane.Normalize(), System.Numerics.Quaternion.Normalize(), System.MathF.ReciprocalSqrtEstimate(), System.Single.Sqrt(), System.Half.Sqrt(), System.Numerics.Vector2.SquareRoot(), System.Numerics.Vector3.SquareRoot(), and System.Numerics.Vector4.SquareRoot().