Terraria: System.MathF.MaxMagnitude
MaxMagnitude()
static float System.MathF.MaxMagnitude (float x, float y) inline static
Definition at line 255 of file MathF.cs.
    {
        float num = Abs(x);
        float num2 = Abs(y);
        if (num > num2 || float.IsNaN(num))
        {
            return x;
        }
        if (num == num2)
        {
            if (!float.IsNegative(x))
            {
                return x;
            }
            return y;
        }
        return y;
    }
References System.MathF.Abs().
Referenced by System.Single.MaxMagnitude(), and System.Half.MaxMagnitude().