Terraria: System.MathF.Sin
Sin()
static float System.MathF.Sin (float x)
Referenced by System.Numerics.Matrix4x4.CreateFromAxisAngle(), System.Numerics.Quaternion.CreateFromAxisAngle(), System.Numerics.Quaternion.CreateFromYawPitchRoll(), System.Numerics.Matrix3x2.CreateRotation(), System.Numerics.Matrix3x2.CreateRotation(), System.Numerics.Matrix4x4.CreateRotationX(), System.Numerics.Matrix4x4.CreateRotationX(), System.Numerics.Matrix4x4.CreateRotationY(), System.Numerics.Matrix4x4.CreateRotationY(), System.Numerics.Matrix4x4.CreateRotationZ(), System.Numerics.Matrix4x4.CreateRotationZ(), System.Single.Sin(), System.Half.Sin(), System.Numerics.Quaternion.Slerp(), and System.MathF.unsafe().