Terraria: System.MathF.Tan
Tan()
static float System.MathF.Tan (float x)
Referenced by System.Numerics.Matrix4x4.CreatePerspectiveFieldOfView(), System.Numerics.Matrix3x2.CreateSkew(), System.Numerics.Matrix3x2.CreateSkew(), System.Single.Tan(), and System.Half.Tan().