Terraria: System.MathF.Round
Round() [3/4]
static unsafe float System.MathF.Round (float x, int digits, MidpointRounding mode) inline static
Definition at line 362 of file MathF.cs.
    {
        if (digits < 0 || digits > 6)
        {
            throw new ArgumentOutOfRangeException("digits", SR.ArgumentOutOfRange_RoundingDigits_MathF);
        }
        if (mode < MidpointRounding.ToEven || mode > MidpointRounding.ToPositiveInfinity)
        {
            throw new ArgumentException(SR.Format(SR.Argument_InvalidEnumValue, mode, "MidpointRounding"), "mode");
        }
        if (Abs(x) < 100000000f)
        {
            float num = roundPower10Single[digits];
            x *= num;
            switch (mode)
            {
            case MidpointRounding.ToEven:
                x = Round(x);
                break;
            case MidpointRounding.AwayFromZero:
            {
                float x2 = ModF(x, &x);
                if (Abs(x2) >= 0.5f)
                {
                    x += (float)Sign(x2);
                }
                break;
            }
            case MidpointRounding.ToZero:
                x = Truncate(x);
                break;
            case MidpointRounding.ToNegativeInfinity:
                x = Floor(x);
                break;
            case MidpointRounding.ToPositiveInfinity:
                x = Ceiling(x);
                break;
            default:
                throw new ArgumentException(SR.Format(SR.Argument_InvalidEnumValue, mode, "MidpointRounding"), "mode");
            }
            x /= num;
        }
        return x;
    }
References System.MathF.Abs(), System.SR.Argument_InvalidEnumValue, System.SR.ArgumentOutOfRange_RoundingDigits_MathF, System.MathF.Ceiling(), System.MathF.Floor(), System.SR.Format(), System.MathF.ModF(), System.MathF.Round(), System.MathF.roundPower10Single, System.MathF.Sign(), and System.MathF.Truncate().