Terraria: System.MathF.MinMagnitude
MinMagnitude()
static float System.MathF.MinMagnitude (float x, float y) inline static
Definition at line 280 of file MathF.cs.
    {
        float num = Abs(x);
        float num2 = Abs(y);
        if (num < num2 || float.IsNaN(num))
        {
            return x;
        }
        if (num == num2)
        {
            if (!float.IsNegative(x))
            {
                return y;
            }
            return x;
        }
        return y;
    }
References System.MathF.Abs().
Referenced by System.Single.MinMagnitude(), and System.Half.MinMagnitude().