Terraria: System.MathF.Round
Round() [1/4]
static float System.MathF.Round (float x) inline static
Definition at line 326 of file MathF.cs.
    {
        uint num = BitConverter.SingleToUInt32Bits(x);
        int num2 = float.ExtractExponentFromBits(num);
        if (num2 <= 126)
        {
            if (num << 1 == 0)
            {
                return x;
            }
            float x2 = ((num2 == 126 && float.ExtractSignificandFromBits(num) != 0) ? 1f : 0f);
            return CopySign(x2, x);
        }
        if (num2 >= 150)
        {
            return x;
        }
        uint num3 = (uint)(1 << 150 - num2);
        uint num4 = num3 - 1;
        num += num3 >> 1;
        num = (((num & num4) != 0) ? (num & ~num4) : (num & ~num3));
        return BitConverter.UInt32BitsToSingle(num);
    }
References System.MathF.CopySign(), System.BitConverter.SingleToUInt32Bits(), and System.BitConverter.UInt32BitsToSingle().
Referenced by System.MathF.IEEERemainder(), System.Single.Round(), System.MathF.Round(), System.MathF.Round(), System.MathF.Round(), System.Single.Round(), System.Half.Round(), System.Half.Round(), System.Single.Round< TInteger >(), System.Single.Round< TInteger >(), System.Half.Round< TInteger >(), and System.Half.Round< TInteger >().