Terraria: System.Net.Http.HttpMessageHandler.Dispose
Dispose() [2/2]
virtual void System.Net.Http.HttpMessageHandler.Dispose (bool disposing) inline protected virtual inherited
Reimplemented in System.Net.Http.DecompressionHandler, System.Net.Http.DelegatingHandler, System.Net.Http.DiagnosticsHandler, System.Net.Http.HttpAuthenticatedConnectionHandler, System.Net.Http.HttpClientHandler, System.Net.Http.HttpConnectionHandler, System.Net.Http.RedirectHandler, and System.Net.Http.SocketsHttpHandler.
Definition at line 23 of file HttpMessageHandler.cs.
    {
    }
Referenced by System.Net.Http.DecompressionHandler.Dispose(), System.Net.Http.DelegatingHandler.Dispose(), System.Net.Http.DiagnosticsHandler.Dispose(), System.Net.Http.HttpMessageInvoker.Dispose(), System.Net.Http.RedirectHandler.Dispose(), and System.Net.Http.SocketsHttpHandler.Dispose().