Terraria: System.MathF.CopySign
CopySign()
static float System.MathF.CopySign (float x, float y) inline static
Definition at line 174 of file MathF.cs.
    {
        if (Sse.IsSupported || AdvSimd.IsSupported)
        {
            return VectorMath.ConditionalSelectBitwise(Vector128.CreateScalarUnsafe(-0f), Vector128.CreateScalarUnsafe(y), Vector128.CreateScalarUnsafe(x)).ToScalar();
        }
        return SoftwareFallback(x, y);
        static float SoftwareFallback(float x, float y)
        {
            int num = BitConverter.SingleToInt32Bits(x);
            int num2 = BitConverter.SingleToInt32Bits(y);
            num &= 0x7FFFFFFF;
            num2 &= int.MinValue;
            return BitConverter.Int32BitsToSingle(num | num2);
        }
    }
References System.Numerics.VectorMath.ConditionalSelectBitwise(), System.Runtime.Intrinsics.Vector128< T >.CreateScalarUnsafe(), System.BitConverter.Int32BitsToSingle(), System.Runtime.Intrinsics.Arm.AdvSimd.IsSupported, System.Runtime.Intrinsics.X86.Sse.IsSupported, and System.BitConverter.SingleToInt32Bits().
Referenced by System.Single.CopySign(), System.Half.CopySign(), and System.MathF.Round().