Terraria: System.Xml.XmlWellFormedWriter.WriteRawAsync
WriteRawAsync() [2/2]
override async Task System.Xml.XmlWellFormedWriter.WriteRawAsync (string data) inline virtual
Reimplemented from System.Xml.XmlWriter.
Definition at line 4028 of file XmlWellFormedWriter.cs.
    {
        _ = 1;
        try
        {
            if (data != null)
            {
                await AdvanceStateAsync(Token.RawData).ConfigureAwait(continueOnCapturedContext: false);
                if (SaveAttrValue)
                {
                    _attrValueCache.WriteRaw(data);
                }
                else
                {
                    await _writer.WriteRawAsync(data).ConfigureAwait(continueOnCapturedContext: false);
                }
            }
        }
        catch
        {
            _currentState = State.Error;
            throw;
        }
    }
References System.Xml.XmlWellFormedWriter._attrValueCache, System.Xml.XmlWellFormedWriter._currentState, System.Xml.XmlWellFormedWriter._writer, System.Xml.XmlWellFormedWriter.AdvanceStateAsync(), System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.Xml.XmlWellFormedWriter.SaveAttrValue, System.Xml.XmlWellFormedWriter.AttributeValueCache.WriteRaw(), and System.Xml.XmlWriter.WriteRawAsync().