Terraria: System.Xml.XmlWellFormedWriter.LookupPrefix
LookupPrefix()
override string System.Xml.XmlWellFormedWriter.LookupPrefix (string ns) inline
Definition at line 2241 of file XmlWellFormedWriter.cs.
    {
        try
        {
            if (ns == null)
            {
                throw new ArgumentNullException("ns");
            }
            for (int num = _nsTop; num >= 0; num--)
            {
                if (_nsStack[num].namespaceUri == ns)
                {
                    string prefix = _nsStack[num].prefix;
                    for (num++; num <= _nsTop; num++)
                    {
                        if (_nsStack[num].prefix == prefix)
{
                            return null;
                        }
                    }
                    return prefix;
                }
            }
            return (_predefinedNamespaces != null) ? _predefinedNamespaces.LookupPrefix(ns) : null;
        }
        catch
        {
            _currentState = State.Error;
            throw;
        }
    }
References System.Xml.XmlWellFormedWriter._currentState, System.Xml.XmlWellFormedWriter._nsStack, System.Xml.XmlWellFormedWriter._nsTop, System.Xml.XmlWellFormedWriter._predefinedNamespaces, System.Xml.IXmlNamespaceResolver.LookupPrefix(), System.prefix, and System.Xml.XmlWellFormedWriter.Namespace.prefix.
Referenced by System.Xml.XmlWellFormedWriter.NamespaceResolverProxy.LookupPrefix(), System.Xml.XmlWellFormedWriter.WriteQualifiedName(), System.Xml.XmlWellFormedWriter.WriteQualifiedNameAsync(), System.Xml.XmlWellFormedWriter.WriteStartAttribute(), System.Xml.XmlWellFormedWriter.WriteStartAttributeAsync_NoAdvanceState(), System.Xml.XmlWellFormedWriter.WriteStartElement(), and System.Xml.XmlWellFormedWriter.WriteStartElementAsync_NoAdvanceState().