Terraria: System.Xml.XmlWellFormedWriter.DisposeAsyncCore
DisposeAsyncCore()
override async ValueTask System.Xml.XmlWellFormedWriter.DisposeAsyncCore () inline protected virtual
Reimplemented from System.Xml.XmlWriter.
Definition at line 4363 of file XmlWellFormedWriter.cs.
    {
        if (_currentState == State.Closed)
        {
            return;
        }
        try
        {
            if (_writeEndDocumentOnClose)
            {
                while (_currentState != State.Error && _elemTop > 0)
                {
                    await WriteEndElementAsync().ConfigureAwait(continueOnCapturedContext: false);
                }
            }
            else if (_currentState != State.Error && _elemTop > 0)
            {
                try
                {
                    await AdvanceStateAsync(Token.EndElement).ConfigureAwait(continueOnCapturedContext: false);
                }
                catch
                {
                    _currentState = State.Error;
                    throw;
                }
            }
            if (InBase64 && _rawWriter != null)
            {
                await _rawWriter.WriteEndBase64Async().ConfigureAwait(continueOnCapturedContext: false);
            }
            await _writer.FlushAsync().ConfigureAwait(continueOnCapturedContext: false);
        }
        finally
        {
            try
            {
                if (_rawWriter == null)
                {
                    await _writer.DisposeAsync().ConfigureAwait(continueOnCapturedContext: false);
                }
                else
                {
                    await _rawWriter.DisposeAsyncCore(WriteState).ConfigureAwait(continueOnCapturedContext: false);
                }
            }
            finally
            {
                _currentState = State.Closed;
            }
        }
    }
References System.Xml.XmlWellFormedWriter._currentState, System.Xml.XmlWellFormedWriter._elemTop, System.Xml.XmlWellFormedWriter._rawWriter, System.Xml.XmlWellFormedWriter._writeEndDocumentOnClose, System.Xml.XmlWellFormedWriter._writer, System.Xml.XmlWellFormedWriter.AdvanceStateAsync(), System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.Xml.XmlWriter.DisposeAsync(), System.Xml.XmlRawWriter.DisposeAsyncCore(), System.Xml.XmlWriter.FlushAsync(), System.Xml.XmlWellFormedWriter.InBase64, System.Xml.XmlRawWriter.WriteEndBase64Async(), and System.Xml.XmlWellFormedWriter.WriteEndElementAsync().