Terraria: System.Xml.XmlWellFormedWriter.WriteStartElementAsync
WriteStartElementAsync() [1/2]
override Task System.Xml.XmlWellFormedWriter.WriteStartElementAsync (string prefix, string localName, string ns) inline
Definition at line 3176 of file XmlWellFormedWriter.cs.
    {
        try
        {
            if (localName == null || localName.Length == 0)
            {
                throw new ArgumentException(System.SR.Xml_EmptyLocalName);
            }
            CheckNCName(localName);
            Task task = AdvanceStateAsync(Token.StartElement);
            if (task.IsSuccess())
            {
                return WriteStartElementAsync_NoAdvanceState(prefix, localName, ns);
            }
            return WriteStartElementAsync_NoAdvanceState(task, prefix, localName, ns);
        }
        catch
        {
            _currentState = State.Error;
            throw;
        }
    }
References System.Xml.XmlWellFormedWriter._currentState, System.Xml.XmlWellFormedWriter.AdvanceStateAsync(), System.Xml.ArgumentException, System.Xml.XmlWellFormedWriter.CheckNCName(), System.prefix, System.task, System.Xml.XmlWellFormedWriter.WriteStartElementAsync_NoAdvanceState(), and System.SR.Xml_EmptyLocalName.