Terraria: System.Xml.XmlWellFormedWriter.WriteStringAsync_NoAdvanceState
WriteStringAsync_NoAdvanceState() [1/2]
Task System.Xml.XmlWellFormedWriter.WriteStringAsync_NoAdvanceState (string text) inline private
Definition at line 3919 of file XmlWellFormedWriter.cs.
    {
        try
        {
            if (SaveAttrValue)
            {
                _attrValueCache.WriteString(text);
                return Task.CompletedTask;
            }
            return TryReturnTask(_writer.WriteStringAsync(text));
        }
        catch
        {
            _currentState = State.Error;
            throw;
        }
    }
References System.Xml.XmlWellFormedWriter._attrValueCache, System.Xml.XmlWellFormedWriter._currentState, System.Xml.XmlWellFormedWriter._writer, System.Threading.Tasks.Task< TResult >.CompletedTask, System.Xml.XmlWellFormedWriter.SaveAttrValue, System.text, System.Xml.XmlWellFormedWriter.TryReturnTask(), System.Xml.XmlWellFormedWriter.AttributeValueCache.WriteString(), and System.Xml.XmlWriter.WriteStringAsync().
Referenced by System.Xml.XmlWellFormedWriter.WriteStringAsync(), and System.Xml.XmlWellFormedWriter.WriteStringAsync_NoAdvanceState().