Terraria: System.Xml.XmlWellFormedWriter.WriteRaw
WriteRaw() [2/2]
override void System.Xml.XmlWellFormedWriter.WriteRaw (string data) inline
Definition at line 2121 of file XmlWellFormedWriter.cs.
    {
        try
        {
            if (data != null)
            {
                AdvanceState(Token.RawData);
                if (SaveAttrValue)
                {
                    _attrValueCache.WriteRaw(data);
                }
                else
                {
                    _writer.WriteRaw(data);
                }
            }
        }
        catch
        {
            _currentState = State.Error;
            throw;
        }
    }
References System.Xml.XmlWellFormedWriter._attrValueCache, System.Xml.XmlWellFormedWriter._currentState, System.Xml.XmlWellFormedWriter._writer, System.Xml.XmlWellFormedWriter.AdvanceState(), System.Xml.XmlWellFormedWriter.SaveAttrValue, System.Xml.XmlWellFormedWriter.AttributeValueCache.WriteRaw(), and System.Xml.XmlWriter.WriteRaw().