Terraria: System.Xml.XmlWellFormedWriter.WriteSurrogateCharEntityAsync
WriteSurrogateCharEntityAsync()
override async Task System.Xml.XmlWellFormedWriter.WriteSurrogateCharEntityAsync (char lowChar, char highChar) inline virtual
Reimplemented from System.Xml.XmlWriter.
Definition at line 3841 of file XmlWellFormedWriter.cs.
    {
        _ = 1;
        try
        {
            if (!char.IsSurrogatePair(highChar, lowChar))
            {
                throw XmlConvert.CreateInvalidSurrogatePairException(lowChar, highChar);
            }
            await AdvanceStateAsync(Token.Text).ConfigureAwait(continueOnCapturedContext: false);
            if (SaveAttrValue)
            {
                _attrValueCache.WriteSurrogateCharEntity(lowChar, highChar);
            }
            else
            {
                await _writer.WriteSurrogateCharEntityAsync(lowChar, highChar).ConfigureAwait(continueOnCapturedContext: false);
            }
        }
        catch
        {
            _currentState = State.Error;
            throw;
        }
    }
References System.Xml.XmlWellFormedWriter._attrValueCache, System.Xml.XmlWellFormedWriter._currentState, System.Xml.XmlWellFormedWriter._writer, System.Xml.XmlWellFormedWriter.AdvanceStateAsync(), System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.Xml.XmlConvert.CreateInvalidSurrogatePairException(), System.Xml.XmlWellFormedWriter.SaveAttrValue, System.Xml.XmlWellFormedWriter.AttributeValueCache.WriteSurrogateCharEntity(), and System.Xml.XmlWriter.WriteSurrogateCharEntityAsync().