Terraria: System.Xml.XmlWellFormedWriter.AdvanceStateAsync
AdvanceStateAsync()
Task System.Xml.XmlWellFormedWriter.AdvanceStateAsync (Token token) inline private
Definition at line 4246 of file XmlWellFormedWriter.cs.
    {
        if (_currentState >= State.Closed)
        {
            if (_currentState == State.Closed || _currentState == State.Error)
            {
                throw new InvalidOperationException(System.SR.Xml_ClosedOrError);
            }
            throw new InvalidOperationException(System.SR.Format(System.SR.Xml_WrongToken, tokenName[(int)token], GetStateName(_currentState)));
        }
        State state;
        while (true)
        {
            state = _stateTable[(int)(((int)token << 4) + _currentState)];
            switch (state)
            {
            case State.Error:
                ThrowInvalidStateTransition(token, _currentState);
                break;
            case State.StartContent:
                return AdvanceStateAsync_ReturnWhenFinish(StartElementContentAsync(), State.Content);
            case State.StartContentEle:
                return AdvanceStateAsync_ReturnWhenFinish(StartElementContentAsync(), State.Element);
            case State.StartContentB64:
                return AdvanceStateAsync_ReturnWhenFinish(StartElementContentAsync(), State.B64Content);
            case State.StartDoc:
                return AdvanceStateAsync_ReturnWhenFinish(WriteStartDocumentAsync(), State.Document);
            case State.StartDocEle:
                return AdvanceStateAsync_ReturnWhenFinish(WriteStartDocumentAsync(), State.Element);
            case State.EndAttrSEle:
            {
                Task task = SequenceRun(WriteEndAttributeAsync(), (XmlWellFormedWriter thisRef) => thisRef.StartElementContentAsync(), this);
                return AdvanceStateAsync_ReturnWhenFinish(task, State.Element);
            }
            case State.EndAttrEEle:
            {
                Task task = SequenceRun(WriteEndAttributeAsync(), (XmlWellFormedWriter thisRef) => thisRef.StartElementContentAsync(), this);
                return AdvanceStateAsync_ReturnWhenFinish(task, State.Content);
            }
            case State.EndAttrSCont:
            {
                Task task = SequenceRun(WriteEndAttributeAsync(), (XmlWellFormedWriter thisRef) => thisRef.StartElementContentAsync(), this);
                return AdvanceStateAsync_ReturnWhenFinish(task, State.Content);
            }
            case State.EndAttrSAttr:
                return AdvanceStateAsync_ReturnWhenFinish(WriteEndAttributeAsync(), State.Attribute);
            case State.PostB64Cont:
                if (_rawWriter != null)
                {
                    return AdvanceStateAsync_ContinueWhenFinish(_rawWriter.WriteEndBase64Async(), State.Content, token);
                }
                _currentState = State.Content;
                continue;
            case State.PostB64Attr:
                if (_rawWriter != null)
                {
                    return AdvanceStateAsync_ContinueWhenFinish(_rawWriter.WriteEndBase64Async(), State.Attribute, token);
                }
                _currentState = State.Attribute;
                continue;
            case State.PostB64RootAttr:
                if (_rawWriter != null)
                {
                    return AdvanceStateAsync_ContinueWhenFinish(_rawWriter.WriteEndBase64Async(), State.RootLevelAttr, token);
                }
                _currentState = State.RootLevelAttr;
                continue;
            case State.StartFragEle:
                StartFragment();
                state = State.Element;
                break;
            case State.StartFragCont:
                StartFragment();
                state = State.Content;
                break;
            case State.StartFragB64:
                StartFragment();
                state = State.B64Content;
                break;
            case State.StartRootLevelAttr:
                return AdvanceStateAsync_ReturnWhenFinish(WriteEndAttributeAsync(), State.RootLevelAttr);
            }
            break;
        }
        _currentState = state;
        return Task.CompletedTask;
    }
References System.Xml.XmlWellFormedWriter._currentState, System.Xml.XmlWellFormedWriter._rawWriter, System.Xml.XmlWellFormedWriter._stateTable, System.Xml.XmlWellFormedWriter.AdvanceStateAsync_ContinueWhenFinish(), System.Xml.XmlWellFormedWriter.AdvanceStateAsync_ReturnWhenFinish(), System.Threading.Tasks.Task< TResult >.CompletedTask, System.Xml.Dictionary, System.SR.Format(), System.Xml.XmlWellFormedWriter.GetStateName(), System.Xml.XmlWellFormedWriter.StartElementContentAsync(), System.Xml.XmlWellFormedWriter.StartFragment(), System.state, System.task, System.Xml.XmlWellFormedWriter.ThrowInvalidStateTransition(), System.Xml.XmlWellFormedWriter.tokenName, System.Xml.XmlWellFormedWriter.WriteEndAttributeAsync(), System.Xml.XmlRawWriter.WriteEndBase64Async(), System.Xml.XmlWellFormedWriter.WriteStartDocumentAsync(), System.SR.Xml_ClosedOrError, and System.SR.Xml_WrongToken.
Referenced by System.Xml.XmlWellFormedWriter._AdvanceStateAsync_ContinueWhenFinish(), System.Xml.XmlWellFormedWriter.AdvanceStateAsync_ContinueWhenFinish(), System.Xml.XmlWellFormedWriter.DisposeAsyncCore(), System.Xml.XmlWellFormedWriter.WriteBase64Async(), System.Xml.XmlWellFormedWriter.WriteBinHexAsync(), System.Xml.XmlWellFormedWriter.WriteCDataAsync(), System.Xml.XmlWellFormedWriter.WriteCharEntityAsync(), System.Xml.XmlWellFormedWriter.WriteCharsAsync(), System.Xml.XmlWellFormedWriter.WriteCommentAsync(), System.Xml.XmlWellFormedWriter.WriteDocTypeAsync(), System.Xml.XmlWellFormedWriter.WriteEndAttributeAsync(), System.Xml.XmlWellFormedWriter.WriteEndDocumentAsync(), System.Xml.XmlWellFormedWriter.WriteEndElementAsync(), System.Xml.XmlWellFormedWriter.WriteEntityRefAsync(), System.Xml.XmlWellFormedWriter.WriteFullEndElementAsync(), System.Xml.XmlWellFormedWriter.WriteProcessingInstructionAsync(), System.Xml.XmlWellFormedWriter.WriteQualifiedNameAsync(), System.Xml.XmlWellFormedWriter.WriteRawAsync(), System.Xml.XmlWellFormedWriter.WriteRawAsync(), System.Xml.XmlWellFormedWriter.WriteStartAttributeAsync(), System.Xml.XmlWellFormedWriter.WriteStartDocumentImplAsync(), System.Xml.XmlWellFormedWriter.WriteStartElementAsync(), System.Xml.XmlWellFormedWriter.WriteStringAsync(), System.Xml.XmlWellFormedWriter.WriteSurrogateCharEntityAsync(), and System.Xml.XmlWellFormedWriter.WriteWhitespaceAsync().