Terraria: System.Xml.XmlWellFormedWriter.WriteStartElementAsync_NoAdvanceState
WriteStartElementAsync_NoAdvanceState() [1/2]
Task System.Xml.XmlWellFormedWriter.WriteStartElementAsync_NoAdvanceState (string prefix, string localName, string ns) inline private
Definition at line 3199 of file XmlWellFormedWriter.cs.
    {
        try
        {
            if (prefix == null)
            {
                if (ns != null)
                {
                    prefix = LookupPrefix(ns);
                }
                if (prefix == null)
                {
                    prefix = string.Empty;
                }
            }
            else if (prefix.Length > 0)
            {
                CheckNCName(prefix);
                if (ns == null)
                {
                    ns = LookupNamespace(prefix);
                }
                if (ns == null || (ns != null && ns.Length == 0))
                {
                    throw new ArgumentException(System.SR.Xml_PrefixForEmptyNs);
                }
            }
            if (ns == null)
            {
                ns = LookupNamespace(prefix);
                if (ns == null)
                {
                    ns = string.Empty;
                }
            }
            if (_elemTop == 0 && _rawWriter != null)
            {
                _rawWriter.OnRootElement(_conformanceLevel);
            }
            Task task = _writer.WriteStartElementAsync(prefix, localName, ns);
            if (task.IsSuccess())
            {
                WriteStartElementAsync_FinishWrite(prefix, localName, ns);
                return Task.CompletedTask;
            }
            return WriteStartElementAsync_FinishWrite(task, prefix, localName, ns);
        }
        catch
        {
            _currentState = State.Error;
            throw;
        }
    }
References System.Xml.XmlWellFormedWriter._conformanceLevel, System.Xml.XmlWellFormedWriter._currentState, System.Xml.XmlWellFormedWriter._elemTop, System.Xml.XmlWellFormedWriter._rawWriter, System.Xml.XmlWellFormedWriter._writer, System.Xml.ArgumentException, System.Xml.XmlWellFormedWriter.CheckNCName(), System.Threading.Tasks.Task< TResult >.CompletedTask, System.Xml.XmlWellFormedWriter.LookupNamespace(), System.Xml.XmlWellFormedWriter.LookupPrefix(), System.Xml.XmlRawWriter.OnRootElement(), System.prefix, System.task, System.Xml.XmlWriter.WriteStartElementAsync(), System.Xml.XmlWellFormedWriter.WriteStartElementAsync_FinishWrite(), and System.SR.Xml_PrefixForEmptyNs.
Referenced by System.Xml.XmlWellFormedWriter.WriteStartElementAsync(), and System.Xml.XmlWellFormedWriter.WriteStartElementAsync_NoAdvanceState().