Terraria: System.Xml.XmlWellFormedWriter.WriteProcessingInstruction
WriteProcessingInstruction() [1/2]
override void System.Xml.XmlWellFormedWriter.WriteProcessingInstruction (string name, string text) inline
Definition at line 1875 of file XmlWellFormedWriter.cs.
    {
        try
        {
            if (name == null || name.Length == 0)
            {
                throw new ArgumentException(System.SR.Xml_EmptyName);
            }
            CheckNCName(name);
            if (text == null)
            {
                text = string.Empty;
            }
            if (name.Length == 3 && string.Equals(name, "xml", StringComparison.OrdinalIgnoreCase))
            {
                if (_currentState != 0)
                {
                    throw new ArgumentException((_conformanceLevel == ConformanceLevel.Document) ? System.SR.Xml_DupXmlDecl : System.SR.Xml_CannotWriteXmlDecl);
                }
                _xmlDeclFollows = true;
                AdvanceState(Token.PI);
                if (_rawWriter != null)
                {
                    _rawWriter.WriteXmlDeclaration(text);
                }
                else
                {
                    _writer.WriteProcessingInstruction(name, text);
                }
            }
            else
            {
                AdvanceState(Token.PI);
                _writer.WriteProcessingInstruction(name, text);
            }
        }
        catch
        {
            _currentState = State.Error;
            throw;
        }
    }
References System.Xml.XmlWellFormedWriter._conformanceLevel, System.Xml.XmlWellFormedWriter._currentState, System.Xml.XmlWellFormedWriter._rawWriter, System.Xml.XmlWellFormedWriter._writer, System.Xml.XmlWellFormedWriter._xmlDeclFollows, System.Xml.XmlWellFormedWriter.AdvanceState(), System.Xml.ArgumentException, System.Xml.XmlWellFormedWriter.CheckNCName(), System.text, System.Xml.XmlWriter.WriteProcessingInstruction(), System.Xml.XmlRawWriter.WriteXmlDeclaration(), System.SR.Xml_CannotWriteXmlDecl, System.SR.Xml_DupXmlDecl, and System.SR.Xml_EmptyName.