Terraria: System.Xml.XmlWellFormedWriter.AddNamespace
AddNamespace()
void System.Xml.XmlWellFormedWriter.AddNamespace (string prefix, string ns, NamespaceKind kind) inline private
Definition at line 2669 of file XmlWellFormedWriter.cs.
    {
        int num = ++_nsTop;
        if (num == _nsStack.Length)
        {
            Namespace[] array = new Namespace[num * 2];
            Array.Copy(_nsStack, array, num);
            _nsStack = array;
        }
        _nsStack[num].Set(prefix, ns, kind);
        if (_useNsHashtable)
        {
            AddToNamespaceHashtable(_nsTop);
        }
        else if (_nsTop == 16)
        {
            _nsHashtable = new Dictionary<string, int>();
            for (int i = 0; i <= _nsTop; i++)
            {
                AddToNamespaceHashtable(i);
            }
            _useNsHashtable = true;
        }
    }
References System.Xml.XmlWellFormedWriter._nsHashtable, System.Xml.XmlWellFormedWriter._nsStack, System.Xml.XmlWellFormedWriter._nsTop, System.Xml.XmlWellFormedWriter._useNsHashtable, System.Xml.XmlWellFormedWriter.AddToNamespaceHashtable(), System.array, System.Array.Copy(), System.prefix, and System.Xml.XmlWellFormedWriter.Namespace.Set().
Referenced by System.Xml.XmlWellFormedWriter.PushNamespaceExplicit(), and System.Xml.XmlWellFormedWriter.PushNamespaceImplicit().