Terraria: System.Xml.XmlWellFormedWriter.XmlWellFormedWriter
XmlWellFormedWriter()
System.Xml.XmlWellFormedWriter.XmlWellFormedWriter (XmlWriter writer, XmlWriterSettings settings) inline package
Definition at line 1305 of file XmlWellFormedWriter.cs.
    {
        _writer = writer;
        _rawWriter = writer as XmlRawWriter;
        _predefinedNamespaces = writer as IXmlNamespaceResolver;
        if (_rawWriter != null)
        {
            _rawWriter.NamespaceResolver = new NamespaceResolverProxy(this);
        }
        _checkCharacters = settings.CheckCharacters;
        _omitDuplNamespaces = (settings.NamespaceHandling & NamespaceHandling.OmitDuplicates) != 0;
        _writeEndDocumentOnClose = settings.WriteEndDocumentOnClose;
        _conformanceLevel = settings.ConformanceLevel;
        _stateTable = ((_conformanceLevel == ConformanceLevel.Document) ? s_stateTableDocument : s_stateTableAuto);
        _currentState = State.Start;
        _nsStack = new Namespace[8];
        _nsStack[0].Set("xmlns", "http://www.w3.org/2000/xmlns/", NamespaceKind.Special);
        _nsStack[1].Set("xml", "http://www.w3.org/XML/1998/namespace", NamespaceKind.Special);
        if (_predefinedNamespaces == null)
        {
            _nsStack[2].Set(string.Empty, string.Empty, NamespaceKind.Implied);
        }
        else
        {
            string text = _predefinedNamespaces.LookupNamespace(string.Empty);
            _nsStack[2].Set(string.Empty, (text == null) ? string.Empty : text, NamespaceKind.Implied);
        }
        _nsTop = 2;
        _elemScopeStack = new ElementScope[8];
        _elemScopeStack[0].Set(string.Empty, string.Empty, string.Empty, _nsTop);
        _elemScopeStack[0].xmlSpace = XmlSpace.None;
        _elemScopeStack[0].xmlLang = null;
        _elemTop = 0;
        _attrStack = new AttrName[8];
    }
References System.Xml.XmlWellFormedWriter._attrStack, System.Xml.XmlWellFormedWriter._checkCharacters, System.Xml.XmlWellFormedWriter._conformanceLevel, System.Xml.XmlWellFormedWriter._currentState, System.Xml.XmlWellFormedWriter._elemScopeStack, System.Xml.XmlWellFormedWriter._elemTop, System.Xml.XmlWellFormedWriter._nsStack, System.Xml.XmlWellFormedWriter._nsTop, System.Xml.XmlWellFormedWriter._omitDuplNamespaces, System.Xml.XmlWellFormedWriter._predefinedNamespaces, System.Xml.XmlWellFormedWriter._rawWriter, System.Xml.XmlWellFormedWriter._stateTable, System.Xml.XmlWellFormedWriter._writeEndDocumentOnClose, System.Xml.XmlWellFormedWriter._writer, System.Xml.XmlWriterSettings.CheckCharacters, System.Xml.XmlWriterSettings.ConformanceLevel, System.Xml.Dictionary, System.Xml.IXmlNamespaceResolver.LookupNamespace(), System.Xml.XmlWellFormedWriter.s_stateTableAuto, System.Xml.XmlWellFormedWriter.s_stateTableDocument, System.Xml.XmlWellFormedWriter.ElementScope.Set(), System.Xml.XmlWellFormedWriter.Namespace.Set(), System.text, System.Xml.XmlWriterSettings.WriteEndDocumentOnClose, System.writer, System.Xml.XmlWellFormedWriter.ElementScope.xmlLang, and System.Xml.XmlWellFormedWriter.ElementScope.xmlSpace.