Terraria: System.Xml.XmlWellFormedWriter.WriteEndAttribute
WriteEndAttribute()
override void System.Xml.XmlWellFormedWriter.WriteEndAttribute () inline
Definition at line 1720 of file XmlWellFormedWriter.cs.
    {
        try
        {
            AdvanceState(Token.EndAttribute);
            if (_specAttr != 0)
            {
                switch (_specAttr)
                {
                case SpecialAttribute.DefaultXmlns:
                {
                    string stringValue = _attrValueCache.StringValue;
                    if (PushNamespaceExplicit(string.Empty, stringValue))
                    {
                        if (_rawWriter != null)
{
                            if (_rawWriter.SupportsNamespaceDeclarationInChunks)
{
                                _rawWriter.WriteStartNamespaceDeclaration(string.Empty);
                                _attrValueCache.Replay(_rawWriter);
                                _rawWriter.WriteEndNamespaceDeclaration();
                            }
                            else
{
                                _rawWriter.WriteNamespaceDeclaration(string.Empty, stringValue);
                            }
                        }
                        else
{
                            _writer.WriteStartAttribute(string.Empty, "xmlns", "http://www.w3.org/2000/xmlns/");
                            _attrValueCache.Replay(_writer);
                            _writer.WriteEndAttribute();
                        }
                    }
                    _curDeclPrefix = null;
                    break;
                }
                case SpecialAttribute.PrefixedXmlns:
                {
                    string stringValue = _attrValueCache.StringValue;
                    if (stringValue.Length == 0)
                    {
                        throw new ArgumentException(System.SR.Xml_PrefixForEmptyNs);
                    }
                    if (stringValue == "http://www.w3.org/2000/xmlns/" || (stringValue == "http://www.w3.org/XML/1998/namespace" && _curDeclPrefix != "xml"))
                    {
                        throw new ArgumentException(System.SR.Xml_CanNotBindToReservedNamespace);
                    }
                    if (PushNamespaceExplicit(_curDeclPrefix, stringValue))
                    {
                        if (_rawWriter != null)
{
                            if (_rawWriter.SupportsNamespaceDeclarationInChunks)
{
                                _rawWriter.WriteStartNamespaceDeclaration(_curDeclPrefix);
                                _attrValueCache.Replay(_rawWriter);
                                _rawWriter.WriteEndNamespaceDeclaration();
                            }
                            else
{
                                _rawWriter.WriteNamespaceDeclaration(_curDeclPrefix, stringValue);
                            }
                        }
                        else
{
                            _writer.WriteStartAttribute("xmlns", _curDeclPrefix, "http://www.w3.org/2000/xmlns/");
                            _attrValueCache.Replay(_writer);
                            _writer.WriteEndAttribute();
                        }
                    }
                    _curDeclPrefix = null;
                    break;
                }
                case SpecialAttribute.XmlSpace:
                {
                    _attrValueCache.Trim();
                    string stringValue = _attrValueCache.StringValue;
                    if (stringValue == "default")
                    {
                        _elemScopeStack[_elemTop].xmlSpace = XmlSpace.Default;
                    }
                    else
                    {
                        if (!(stringValue == "preserve"))
{
                            throw new ArgumentException(System.SR.Format(System.SR.Xml_InvalidXmlSpace, stringValue));
                        }
                        _elemScopeStack[_elemTop].xmlSpace = XmlSpace.Preserve;
                    }
                    _writer.WriteStartAttribute("xml", "space", "http://www.w3.org/XML/1998/namespace");
                    _attrValueCache.Replay(_writer);
                    _writer.WriteEndAttribute();
                    break;
                }
                case SpecialAttribute.XmlLang:
                {
                    string stringValue = _attrValueCache.StringValue;
                    _elemScopeStack[_elemTop].xmlLang = stringValue;
                    _writer.WriteStartAttribute("xml", "lang", "http://www.w3.org/XML/1998/namespace");
                    _attrValueCache.Replay(_writer);
                    _writer.WriteEndAttribute();
                    break;
                }
                }
                _specAttr = SpecialAttribute.No;
                _attrValueCache.Clear();
            }
            else
            {
                _writer.WriteEndAttribute();
            }
        }
        catch
        {
            _currentState = State.Error;
            throw;
        }
    }
References System.Xml.XmlWellFormedWriter._attrValueCache, System.Xml.XmlWellFormedWriter._curDeclPrefix, System.Xml.XmlWellFormedWriter._currentState, System.Xml.XmlWellFormedWriter._elemScopeStack, System.Xml.XmlWellFormedWriter._elemTop, System.Xml.XmlWellFormedWriter._rawWriter, System.Xml.XmlWellFormedWriter._specAttr, System.Xml.XmlWellFormedWriter._writer, System.Xml.XmlWellFormedWriter.AdvanceState(), System.Xml.ArgumentException, System.Xml.XmlWellFormedWriter.AttributeValueCache.Clear(), System.Xml.Dictionary, System.SR.Format(), System.Xml.XmlWellFormedWriter.PushNamespaceExplicit(), System.Xml.XmlWellFormedWriter.AttributeValueCache.Replay(), System.Xml.XmlWellFormedWriter.AttributeValueCache.StringValue, System.Xml.XmlRawWriter.SupportsNamespaceDeclarationInChunks, System.Xml.XmlWellFormedWriter.AttributeValueCache.Trim(), System.Xml.XmlWriter.WriteEndAttribute(), System.Xml.XmlRawWriter.WriteEndNamespaceDeclaration(), System.Xml.XmlRawWriter.WriteNamespaceDeclaration(), System.Xml.XmlWriter.WriteStartAttribute(), System.Xml.XmlRawWriter.WriteStartNamespaceDeclaration(), System.SR.Xml_CanNotBindToReservedNamespace, System.SR.Xml_InvalidXmlSpace, System.SR.Xml_PrefixForEmptyNs, System.Xml.XmlWellFormedWriter.ElementScope.xmlLang, and System.Xml.XmlWellFormedWriter.ElementScope.xmlSpace.
Referenced by System.Xml.XmlWellFormedWriter.AdvanceState().