Terraria: System.Xml.XmlWellFormedWriter.WriteStartDocumentImplAsync
WriteStartDocumentImplAsync()
async Task System.Xml.XmlWellFormedWriter.WriteStartDocumentImplAsync (XmlStandalone standalone) inline private
Definition at line 4179 of file XmlWellFormedWriter.cs.
    {
        _ = 2;
        try
        {
            await AdvanceStateAsync(Token.StartDocument).ConfigureAwait(continueOnCapturedContext: false);
            if (_conformanceLevel == ConformanceLevel.Auto)
            {
                _conformanceLevel = ConformanceLevel.Document;
                _stateTable = s_stateTableDocument;
            }
            else if (_conformanceLevel == ConformanceLevel.Fragment)
            {
                throw new InvalidOperationException(System.SR.Xml_CannotStartDocumentOnFragment);
            }
            if (_rawWriter != null)
            {
                if (!_xmlDeclFollows)
                {
                    await _rawWriter.WriteXmlDeclarationAsync(standalone).ConfigureAwait(continueOnCapturedContext: false);
                }
            }
            else
            {
                await _writer.WriteStartDocumentAsync().ConfigureAwait(continueOnCapturedContext: false);
            }
        }
        catch
        {
            _currentState = State.Error;
            throw;
        }
    }
References System.Xml.XmlWellFormedWriter._conformanceLevel, System.Xml.XmlWellFormedWriter._currentState, System.Xml.XmlWellFormedWriter._rawWriter, System.Xml.XmlWellFormedWriter._stateTable, System.Xml.XmlWellFormedWriter._writer, System.Xml.XmlWellFormedWriter._xmlDeclFollows, System.Xml.XmlWellFormedWriter.AdvanceStateAsync(), System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.Xml.XmlWellFormedWriter.s_stateTableDocument, System.Xml.XmlWriter.WriteStartDocumentAsync(), System.Xml.XmlRawWriter.WriteXmlDeclarationAsync(), and System.SR.Xml_CannotStartDocumentOnFragment.
Referenced by System.Xml.XmlWellFormedWriter.WriteStartDocumentAsync(), and System.Xml.XmlWellFormedWriter.WriteStartDocumentAsync().