Terraria: System.Xml.XmlWellFormedWriter.WriteCharEntity
WriteCharEntity()
override void System.Xml.XmlWellFormedWriter.WriteCharEntity (char ch) inline
Definition at line 1944 of file XmlWellFormedWriter.cs.
    {
        try
        {
            if (char.IsSurrogate(ch))
            {
                throw new ArgumentException(System.SR.Xml_InvalidSurrogateMissingLowChar);
            }
            AdvanceState(Token.Text);
            if (SaveAttrValue)
            {
                _attrValueCache.WriteCharEntity(ch);
            }
            else
            {
                _writer.WriteCharEntity(ch);
            }
        }
        catch
        {
            _currentState = State.Error;
            throw;
        }
    }
References System.Xml.XmlWellFormedWriter._attrValueCache, System.Xml.XmlWellFormedWriter._currentState, System.Xml.XmlWellFormedWriter._writer, System.Xml.XmlWellFormedWriter.AdvanceState(), System.Xml.ArgumentException, System.ch, System.Xml.XmlWellFormedWriter.SaveAttrValue, System.Xml.XmlWellFormedWriter.AttributeValueCache.WriteCharEntity(), System.Xml.XmlWriter.WriteCharEntity(), and System.SR.Xml_InvalidSurrogateMissingLowChar.