Terraria: System.Xml.XmlWellFormedWriter.GeneratePrefix
GeneratePrefix()
string System.Xml.XmlWellFormedWriter.GeneratePrefix () inline private
Definition at line 2907 of file XmlWellFormedWriter.cs.
    {
        IFormatProvider invariantCulture = CultureInfo.InvariantCulture;
        IFormatProvider provider = invariantCulture;
        DefaultInterpolatedStringHandler handler = new DefaultInterpolatedStringHandler(1, 1, invariantCulture);
        handler.AppendLiteral("p");
        handler.AppendFormatted(_nsTop - 2, "d");
        string text = string.Create(provider, ref handler);
        if (LookupNamespace(text) == null)
        {
            return text;
        }
        int num = 0;
        string text2;
        do
        {
            invariantCulture = CultureInfo.InvariantCulture;
            IFormatProvider provider2 = invariantCulture;
            DefaultInterpolatedStringHandler handler2 = new DefaultInterpolatedStringHandler(0, 2, invariantCulture);
            handler2.AppendFormatted(text);
            handler2.AppendFormatted(num);
            text2 = string.Create(provider2, ref handler2);
            num++;
        }
        while (LookupNamespace(text2) != null);
        return text2;
    }
References System.Xml.XmlWellFormedWriter._nsTop, System.Runtime.CompilerServices.DefaultInterpolatedStringHandler.AppendFormatted(), System.Runtime.CompilerServices.DefaultInterpolatedStringHandler.AppendLiteral(), System.Xml.Dictionary, System.Globalization.CultureInfo.InvariantCulture, System.Xml.XmlWellFormedWriter.LookupNamespace(), and System.text.
Referenced by System.Xml.XmlWellFormedWriter.WriteQualifiedName(), System.Xml.XmlWellFormedWriter.WriteQualifiedNameAsync(), System.Xml.XmlWellFormedWriter.WriteStartAttribute(), and System.Xml.XmlWellFormedWriter.WriteStartAttributeAsync_NoAdvanceState().