Terraria: System.Xml.XmlWellFormedWriter.WriteStartElement
WriteStartElement() [3/4]
override void System.Xml.XmlWellFormedWriter.WriteStartElement (string prefix, string localName, string ns) inline
Definition at line 1433 of file XmlWellFormedWriter.cs.
    {
        try
        {
            if (localName == null || localName.Length == 0)
            {
                throw new ArgumentException(System.SR.Xml_EmptyLocalName);
            }
            CheckNCName(localName);
            AdvanceState(Token.StartElement);
            if (prefix == null)
            {
                if (ns != null)
                {
                    prefix = LookupPrefix(ns);
                }
                if (prefix == null)
                {
                    prefix = string.Empty;
                }
            }
            else if (prefix.Length > 0)
            {
                CheckNCName(prefix);
                if (ns == null)
                {
                    ns = LookupNamespace(prefix);
                }
                if (ns == null || (ns != null && ns.Length == 0))
                {
                    throw new ArgumentException(System.SR.Xml_PrefixForEmptyNs);
                }
            }
            if (ns == null)
            {
                ns = LookupNamespace(prefix);
                if (ns == null)
                {
                    ns = string.Empty;
                }
            }
            if (_elemTop == 0 && _rawWriter != null)
            {
                _rawWriter.OnRootElement(_conformanceLevel);
            }
            _writer.WriteStartElement(prefix, localName, ns);
            int num = ++_elemTop;
            if (num == _elemScopeStack.Length)
            {
                ElementScope[] array = new ElementScope[num * 2];
                Array.Copy(_elemScopeStack, array, num);
                _elemScopeStack = array;
            }
            _elemScopeStack[num].Set(prefix, localName, ns, _nsTop);
            PushNamespaceImplicit(prefix, ns);
            if (_attrCount >= 14)
            {
                _attrHashTable.Clear();
            }
            _attrCount = 0;
        }
        catch
        {
            _currentState = State.Error;
            throw;
        }
    }
References System.Xml.XmlWellFormedWriter._attrCount, System.Xml.XmlWellFormedWriter._attrHashTable, System.Xml.XmlWellFormedWriter._conformanceLevel, System.Xml.XmlWellFormedWriter._currentState, System.Xml.XmlWellFormedWriter._elemScopeStack, System.Xml.XmlWellFormedWriter._elemTop, System.Xml.XmlWellFormedWriter._nsTop, System.Xml.XmlWellFormedWriter._rawWriter, System.Xml.XmlWellFormedWriter._writer, System.Xml.XmlWellFormedWriter.AdvanceState(), System.Xml.ArgumentException, System.array, System.Xml.XmlWellFormedWriter.CheckNCName(), System.Collections.Generic.Dictionary< TKey, TValue >.Clear(), System.Array.Copy(), System.Xml.XmlWellFormedWriter.LookupNamespace(), System.Xml.XmlWellFormedWriter.LookupPrefix(), System.Xml.XmlRawWriter.OnRootElement(), System.prefix, System.Xml.XmlWellFormedWriter.PushNamespaceImplicit(), System.Xml.XmlWellFormedWriter.ElementScope.Set(), System.Xml.XmlWriter.WriteStartElement(), System.SR.Xml_EmptyLocalName, and System.SR.Xml_PrefixForEmptyNs.