Terraria: System.Xml.XmlWellFormedWriter.PushNamespaceImplicit
PushNamespaceImplicit()
void System.Xml.XmlWellFormedWriter.PushNamespaceImplicit (string prefix, string ns) inline private
Definition at line 2550 of file XmlWellFormedWriter.cs.
    {
        int num = LookupNamespaceIndex(prefix);
        NamespaceKind kind;
        if (num != -1)
        {
            if (num > _elemScopeStack[_elemTop].prevNSTop)
            {
                if (_nsStack[num].namespaceUri != ns)
                {
                    throw new XmlException(System.SR.Xml_RedefinePrefix, new string[3]
                    {
                        prefix,
                        _nsStack[num].namespaceUri,
                        ns
                    });
                }
                return;
            }
            if (_nsStack[num].kind == NamespaceKind.Special)
            {
                if (!(prefix == "xml"))
                {
                    throw new ArgumentException(System.SR.Xml_XmlnsPrefix);
                }
                if (ns != _nsStack[num].namespaceUri)
                {
                    throw new ArgumentException(System.SR.Xml_XmlPrefix);
                }
                kind = NamespaceKind.Implied;
            }
            else
            {
                kind = ((!(_nsStack[num].namespaceUri == ns)) ? NamespaceKind.NeedToWrite : NamespaceKind.Implied);
            }
        }
        else
        {
            if ((ns == "http://www.w3.org/XML/1998/namespace" && prefix != "xml") || (ns == "http://www.w3.org/2000/xmlns/" && prefix != "xmlns"))
            {
                throw new ArgumentException(System.SR.Format(System.SR.Xml_NamespaceDeclXmlXmlns, prefix));
            }
            if (_predefinedNamespaces != null)
            {
                string text = _predefinedNamespaces.LookupNamespace(prefix);
                kind = ((!(text == ns)) ? NamespaceKind.NeedToWrite : NamespaceKind.Implied);
            }
            else
            {
                kind = NamespaceKind.NeedToWrite;
            }
        }
        AddNamespace(prefix, ns, kind);
    }
References System.Xml.XmlWellFormedWriter._elemScopeStack, System.Xml.XmlWellFormedWriter._elemTop, System.Xml.XmlWellFormedWriter._nsStack, System.Xml.XmlWellFormedWriter._predefinedNamespaces, System.Xml.XmlWellFormedWriter.AddNamespace(), System.Xml.ArgumentException, System.Xml.Dictionary, System.SR.Format(), System.Xml.IXmlNamespaceResolver.LookupNamespace(), System.Xml.XmlWellFormedWriter.LookupNamespaceIndex(), System.Xml.XmlWellFormedWriter.Namespace.namespaceUri, System.prefix, System.text, System.SR.Xml_NamespaceDeclXmlXmlns, System.SR.Xml_RedefinePrefix, System.SR.Xml_XmlnsPrefix, System.SR.Xml_XmlPrefix, and System.Xml.XmlException.
Referenced by System.Xml.XmlWellFormedWriter.WriteQualifiedName(), System.Xml.XmlWellFormedWriter.WriteQualifiedNameAsync(), System.Xml.XmlWellFormedWriter.WriteStartAttribute(), System.Xml.XmlWellFormedWriter.WriteStartAttributeAsync_NoAdvanceState(), System.Xml.XmlWellFormedWriter.WriteStartElement(), and System.Xml.XmlWellFormedWriter.WriteStartElementAsync_FinishWrite().