Terraria: System.Xml.XmlWellFormedWriter.WriteWhitespaceAsync
WriteWhitespaceAsync() [1/2]
override async Task System.Xml.XmlWellFormedWriter.WriteWhitespaceAsync (string ws) inline
Definition at line 3867 of file XmlWellFormedWriter.cs.
    {
        _ = 1;
        try
        {
            if (ws == null)
            {
                ws = string.Empty;
            }
            if (!XmlCharType.IsOnlyWhitespace(ws))
            {
                throw new ArgumentException(System.SR.Xml_NonWhitespace);
            }
            await AdvanceStateAsync(Token.Whitespace).ConfigureAwait(continueOnCapturedContext: false);
            if (SaveAttrValue)
            {
                _attrValueCache.WriteWhitespace(ws);
            }
            else
            {
                await _writer.WriteWhitespaceAsync(ws).ConfigureAwait(continueOnCapturedContext: false);
            }
        }
        catch
        {
            _currentState = State.Error;
            throw;
        }
    }
References System.Xml.XmlWellFormedWriter._attrValueCache, System.Xml.XmlWellFormedWriter._currentState, System.Xml.XmlWellFormedWriter._writer, System.Xml.XmlWellFormedWriter.AdvanceStateAsync(), System.Xml.ArgumentException, System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.Xml.XmlCharType.IsOnlyWhitespace(), System.Xml.XmlWellFormedWriter.SaveAttrValue, System.Xml.XmlWellFormedWriter.AttributeValueCache.WriteWhitespace(), System.Xml.XmlWriter.WriteWhitespaceAsync(), and System.SR.Xml_NonWhitespace.