Terraria: System.Xml.XmlWellFormedWriter.WriteStartAttributeAsync
WriteStartAttributeAsync() [1/2]
override Task System.Xml.XmlWellFormedWriter.WriteStartAttributeAsync (string prefix, string localName, string namespaceName) inline package
Definition at line 3405 of file XmlWellFormedWriter.cs.
    {
        try
        {
            if (localName == null || localName.Length == 0)
            {
                if (!(prefix == "xmlns"))
                {
                    throw new ArgumentException(System.SR.Xml_EmptyLocalName);
                }
                localName = "xmlns";
                prefix = string.Empty;
            }
            CheckNCName(localName);
            Task task = AdvanceStateAsync(Token.StartAttribute);
            if (task.IsSuccess())
            {
                return WriteStartAttributeAsync_NoAdvanceState(prefix, localName, namespaceName);
            }
            return WriteStartAttributeAsync_NoAdvanceState(task, prefix, localName, namespaceName);
        }
        catch
        {
            _currentState = State.Error;
            throw;
        }
    }
References System.Xml.XmlWellFormedWriter._currentState, System.Xml.XmlWellFormedWriter.AdvanceStateAsync(), System.Xml.ArgumentException, System.Xml.XmlWellFormedWriter.CheckNCName(), System.prefix, System.task, System.Xml.XmlWellFormedWriter.WriteStartAttributeAsync_NoAdvanceState(), and System.SR.Xml_EmptyLocalName.