Terraria: System.Xml.XmlWellFormedWriter.WriteValue
WriteValue() [10/11]
override void System.Xml.XmlWellFormedWriter.WriteValue (string value) inline
Definition at line 2430 of file XmlWellFormedWriter.cs.
    {
        try
        {
            if (value != null)
            {
                if (SaveAttrValue)
                {
                    AdvanceState(Token.Text);
                    _attrValueCache.WriteValue(value);
                }
                else
                {
                    AdvanceState(Token.AtomicValue);
                    _writer.WriteValue(value);
                }
            }
        }
        catch
        {
            _currentState = State.Error;
            throw;
        }
    }
References System.Xml.XmlWellFormedWriter._attrValueCache, System.Xml.XmlWellFormedWriter._currentState, System.Xml.XmlWellFormedWriter._writer, System.Xml.XmlWellFormedWriter.AdvanceState(), System.Xml.XmlWellFormedWriter.SaveAttrValue, System.value, System.Xml.XmlWriter.WriteValue(), and System.Xml.XmlWellFormedWriter.AttributeValueCache.WriteValue().