Terraria: System.Xml.XmlWellFormedWriter.WriteBase64Async
WriteBase64Async()
override Task System.Xml.XmlWellFormedWriter.WriteBase64Async (byte[] buffer, int index, int count) inline virtual
Reimplemented from System.Xml.XmlWriter.
Definition at line 4053 of file XmlWellFormedWriter.cs.
    {
        try
        {
            if (buffer == null)
            {
                throw new ArgumentNullException("buffer");
            }
            if (index < 0)
            {
                throw new ArgumentOutOfRangeException("index");
            }
            if (count < 0)
            {
                throw new ArgumentOutOfRangeException("count");
            }
            if (count > buffer.Length - index)
            {
                throw new ArgumentOutOfRangeException("count");
            }
            Task task = AdvanceStateAsync(Token.Base64);
            if (task.IsSuccess())
            {
                return TryReturnTask(_writer.WriteBase64Async(buffer, index, count));
            }
            return WriteBase64Async_NoAdvanceState(task, buffer, index, count);
        }
        catch
        {
            _currentState = State.Error;
            throw;
        }
    }
References System.Xml.XmlWellFormedWriter._currentState, System.Xml.XmlWellFormedWriter._writer, System.Xml.XmlWellFormedWriter.AdvanceStateAsync(), System.buffer, System.count, System.index, System.task, System.Xml.XmlWellFormedWriter.TryReturnTask(), System.Xml.XmlWriter.WriteBase64Async(), and System.Xml.XmlWellFormedWriter.WriteBase64Async_NoAdvanceState().