Terraria: System.Xml.XmlWellFormedWriter.WriteStartAttributeAsync_NoAdvanceState
WriteStartAttributeAsync_NoAdvanceState() [1/2]
Task System.Xml.XmlWellFormedWriter.WriteStartAttributeAsync_NoAdvanceState (string prefix, string localName, string namespaceName) inline private
Definition at line 3433 of file XmlWellFormedWriter.cs.
    {
        try
        {
            if (prefix == null)
            {
                if (namespaceName != null && (!(localName == "xmlns") || !(namespaceName == "http://www.w3.org/2000/xmlns/")))
                {
                    prefix = LookupPrefix(namespaceName);
                }
                if (prefix == null)
                {
                    prefix = string.Empty;
                }
            }
            if (namespaceName == null)
            {
                if (prefix.Length > 0)
                {
                    namespaceName = LookupNamespace(prefix);
                }
                if (namespaceName == null)
                {
                    namespaceName = string.Empty;
                }
            }
            if (prefix.Length == 0)
            {
                if (localName[0] != 'x' || !(localName == "xmlns"))
                {
                    if (namespaceName.Length > 0)
                    {
                        prefix = LookupPrefix(namespaceName);
                        if (prefix == null || prefix.Length == 0)
{
                            prefix = GeneratePrefix();
                        }
                    }
                    goto IL_01bc;
                }
                if (namespaceName.Length > 0 && namespaceName != "http://www.w3.org/2000/xmlns/")
                {
                    throw new ArgumentException(System.SR.Xml_XmlnsPrefix);
                }
                _curDeclPrefix = string.Empty;
                SetSpecialAttribute(SpecialAttribute.DefaultXmlns);
            }
            else
            {
                if (prefix[0] != 'x')
                {
                    goto IL_0188;
                }
                if (prefix == "xmlns")
                {
                    if (namespaceName.Length > 0 && namespaceName != "http://www.w3.org/2000/xmlns/")
                    {
                        throw new ArgumentException(System.SR.Xml_XmlnsPrefix);
                    }
                    _curDeclPrefix = localName;
                    SetSpecialAttribute(SpecialAttribute.PrefixedXmlns);
                }
                else
                {
                    if (!(prefix == "xml"))
                    {
                        goto IL_0188;
                    }
                    if (namespaceName.Length > 0 && namespaceName != "http://www.w3.org/XML/1998/namespace")
                    {
                        throw new ArgumentException(System.SR.Xml_XmlPrefix);
                    }
                    if (!(localName == "space"))
                    {
                        if (!(localName == "lang"))
{
                            goto IL_0188;
                        }
                        SetSpecialAttribute(SpecialAttribute.XmlLang);
                    }
                    else
                    {
                        SetSpecialAttribute(SpecialAttribute.XmlSpace);
                    }
                }
            }
            goto IL_01cc;
            IL_0188:
            CheckNCName(prefix);
            if (namespaceName.Length == 0)
            {
                prefix = string.Empty;
            }
            else
            {
                string text = LookupLocalNamespace(prefix);
                if (text != null && text != namespaceName)
                {
                    prefix = GeneratePrefix();
                }
            }
            goto IL_01bc;
            IL_01bc:
            if (prefix.Length != 0)
            {
                PushNamespaceImplicit(prefix, namespaceName);
            }
            goto IL_01cc;
            IL_01cc:
            AddAttribute(prefix, localName, namespaceName);
            if (_specAttr == SpecialAttribute.No)
            {
                return TryReturnTask(_writer.WriteStartAttributeAsync(prefix, localName, namespaceName));
            }
            return Task.CompletedTask;
        }
        catch
        {
            _currentState = State.Error;
            throw;
        }
    }
References System.Xml.XmlWellFormedWriter._curDeclPrefix, System.Xml.XmlWellFormedWriter._currentState, System.Xml.XmlWellFormedWriter._specAttr, System.Xml.XmlWellFormedWriter._writer, System.Xml.XmlWellFormedWriter.AddAttribute(), System.Xml.ArgumentException, System.Xml.XmlWellFormedWriter.CheckNCName(), System.Threading.Tasks.Task< TResult >.CompletedTask, System.Xml.Dictionary, System.Xml.XmlWellFormedWriter.GeneratePrefix(), System.Xml.XmlWellFormedWriter.LookupLocalNamespace(), System.Xml.XmlWellFormedWriter.LookupNamespace(), System.Xml.XmlWellFormedWriter.LookupPrefix(), System.prefix, System.Xml.XmlWellFormedWriter.PushNamespaceImplicit(), System.Xml.XmlWellFormedWriter.SetSpecialAttribute(), System.text, System.Xml.XmlWellFormedWriter.TryReturnTask(), System.Xml.XmlWriter.WriteStartAttributeAsync(), System.SR.Xml_XmlnsPrefix, and System.SR.Xml_XmlPrefix.
Referenced by System.Xml.XmlWellFormedWriter.WriteStartAttributeAsync(), and System.Xml.XmlWellFormedWriter.WriteStartAttributeAsync_NoAdvanceState().