Terraria: System.Xml.XmlWellFormedWriter.InvalidCharsException
InvalidCharsException()
static Exception System.Xml.XmlWellFormedWriter.InvalidCharsException (string name, int badCharIndex) inline static private
Definition at line 2952 of file XmlWellFormedWriter.cs.
    {
        string[] array = XmlException.BuildCharExceptionArgs(name, badCharIndex);
        string[] array2 = new string[3]
        {
            name,
            array[0],
            array[1]
        };
        string xml_InvalidNameCharsDetail = System.SR.Xml_InvalidNameCharsDetail;
        object[] args = array2;
        return new ArgumentException(System.SR.Format(xml_InvalidNameCharsDetail, args));
    }
References System.Xml.ArgumentException, System.array, System.Xml.XmlException.BuildCharExceptionArgs(), System.Xml.Dictionary, System.SR.Format(), and System.SR.Xml_InvalidNameCharsDetail.
Referenced by System.Xml.XmlWellFormedWriter.CheckNCName().