Terraria: System.Xml.XmlWellFormedWriter.LookupNamespaceIndex
LookupNamespaceIndex()
int System.Xml.XmlWellFormedWriter.LookupNamespaceIndex (string prefix) inline private
Definition at line 2704 of file XmlWellFormedWriter.cs.
    {
        if (_useNsHashtable)
        {
            if (_nsHashtable.TryGetValue(prefix, out var value))
            {
                return value;
            }
        }
        else
        {
            for (int num = _nsTop; num >= 0; num--)
            {
                if (_nsStack[num].prefix == prefix)
                {
                    return num;
                }
            }
        }
        return -1;
    }
References System.Xml.XmlWellFormedWriter._nsHashtable, System.Xml.XmlWellFormedWriter._nsStack, System.Xml.XmlWellFormedWriter._nsTop, System.Xml.XmlWellFormedWriter._useNsHashtable, System.prefix, System.Collections.Generic.Dictionary< TKey, TValue >.TryGetValue(), and System.value.
Referenced by System.Xml.XmlWellFormedWriter.PushNamespaceExplicit(), and System.Xml.XmlWellFormedWriter.PushNamespaceImplicit().