Terraria: System.Xml.XmlWellFormedWriter.WriteEntityRefAsync
WriteEntityRefAsync()
override async Task System.Xml.XmlWellFormedWriter.WriteEntityRefAsync (string name) inline virtual
Reimplemented from System.Xml.XmlWriter.
Definition at line 3788 of file XmlWellFormedWriter.cs.
    {
        _ = 1;
        try
        {
            if (name == null || name.Length == 0)
            {
                throw new ArgumentException(System.SR.Xml_EmptyName);
            }
            CheckNCName(name);
            await AdvanceStateAsync(Token.Text).ConfigureAwait(continueOnCapturedContext: false);
            if (SaveAttrValue)
            {
                _attrValueCache.WriteEntityRef(name);
            }
            else
            {
                await _writer.WriteEntityRefAsync(name).ConfigureAwait(continueOnCapturedContext: false);
            }
        }
        catch
        {
            _currentState = State.Error;
            throw;
        }
    }
References System.Xml.XmlWellFormedWriter._attrValueCache, System.Xml.XmlWellFormedWriter._currentState, System.Xml.XmlWellFormedWriter._writer, System.Xml.XmlWellFormedWriter.AdvanceStateAsync(), System.Xml.ArgumentException, System.Xml.XmlWellFormedWriter.CheckNCName(), System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.Xml.XmlWellFormedWriter.SaveAttrValue, System.Xml.XmlWellFormedWriter.AttributeValueCache.WriteEntityRef(), System.Xml.XmlWriter.WriteEntityRefAsync(), and System.SR.Xml_EmptyName.