Terraria: System.Xml.XmlWellFormedWriter.AddAttribute
AddAttribute()
void System.Xml.XmlWellFormedWriter.AddAttribute (string prefix, string localName, string namespaceName) inline private
Definition at line 2976 of file XmlWellFormedWriter.cs.
    {
        int num = _attrCount++;
        if (num == _attrStack.Length)
        {
            AttrName[] array = new AttrName[num * 2];
            Array.Copy(_attrStack, array, num);
            _attrStack = array;
        }
        _attrStack[num].Set(prefix, localName, namespaceName);
        if (_attrCount < 14)
        {
            for (int i = 0; i < num; i++)
            {
                if (_attrStack[i].IsDuplicate(prefix, localName, namespaceName))
                {
                    throw DupAttrException(prefix, localName);
                }
            }
            return;
        }
        if (_attrCount == 14)
        {
            if (_attrHashTable == null)
            {
                _attrHashTable = new Dictionary<string, int>();
            }
            for (int j = 0; j < num; j++)
            {
                AddToAttrHashTable(j);
            }
        }
        AddToAttrHashTable(num);
        int prev;
        for (prev = _attrStack[num].prev; prev > 0; prev = _attrStack[prev].prev)
        {
            prev--;
            if (_attrStack[prev].IsDuplicate(prefix, localName, namespaceName))
            {
                throw DupAttrException(prefix, localName);
            }
        }
    }
References System.Xml.XmlWellFormedWriter._attrCount, System.Xml.XmlWellFormedWriter._attrHashTable, System.Xml.XmlWellFormedWriter._attrStack, System.Xml.XmlWellFormedWriter.AddToAttrHashTable(), System.array, System.Array.Copy(), System.Xml.XmlWellFormedWriter.DupAttrException(), System.prefix, System.Xml.XmlWellFormedWriter.AttrName.prev, and System.Xml.XmlWellFormedWriter.AttrName.Set().
Referenced by System.Xml.XmlWellFormedWriter.WriteStartAttribute(), and System.Xml.XmlWellFormedWriter.WriteStartAttributeAsync_NoAdvanceState().