Terraria: System.Xml.XmlWellFormedWriter.AdvanceState
AdvanceState()
void System.Xml.XmlWellFormedWriter.AdvanceState (Token token) inline private
Definition at line 2753 of file XmlWellFormedWriter.cs.
    {
        if (_currentState >= State.Closed)
        {
            if (_currentState == State.Closed || _currentState == State.Error)
            {
                throw new InvalidOperationException(System.SR.Xml_ClosedOrError);
            }
            throw new InvalidOperationException(System.SR.Format(System.SR.Xml_WrongToken, tokenName[(int)token], GetStateName(_currentState)));
        }
        State state;
        while (true)
        {
            state = _stateTable[(int)(((int)token << 4) + _currentState)];
            switch (state)
            {
            case State.Error:
                ThrowInvalidStateTransition(token, _currentState);
                break;
            case State.StartContent:
                StartElementContent();
                state = State.Content;
                break;
            case State.StartContentEle:
                StartElementContent();
                state = State.Element;
                break;
            case State.StartContentB64:
                StartElementContent();
                state = State.B64Content;
                break;
            case State.StartDoc:
                WriteStartDocument();
                state = State.Document;
                break;
            case State.StartDocEle:
                WriteStartDocument();
                state = State.Element;
                break;
            case State.EndAttrSEle:
                WriteEndAttribute();
                StartElementContent();
                state = State.Element;
                break;
            case State.EndAttrEEle:
                WriteEndAttribute();
                StartElementContent();
                state = State.Content;
                break;
            case State.EndAttrSCont:
                WriteEndAttribute();
                StartElementContent();
                state = State.Content;
                break;
            case State.EndAttrSAttr:
                WriteEndAttribute();
                state = State.Attribute;
                break;
            case State.PostB64Cont:
                if (_rawWriter != null)
                {
                    _rawWriter.WriteEndBase64();
                }
                _currentState = State.Content;
                continue;
            case State.PostB64Attr:
                if (_rawWriter != null)
                {
                    _rawWriter.WriteEndBase64();
                }
                _currentState = State.Attribute;
                continue;
            case State.PostB64RootAttr:
                if (_rawWriter != null)
                {
                    _rawWriter.WriteEndBase64();
                }
                _currentState = State.RootLevelAttr;
                continue;
            case State.StartFragEle:
                StartFragment();
                state = State.Element;
                break;
            case State.StartFragCont:
                StartFragment();
                state = State.Content;
                break;
            case State.StartFragB64:
                StartFragment();
                state = State.B64Content;
                break;
            case State.StartRootLevelAttr:
                WriteEndAttribute();
                state = State.RootLevelAttr;
                break;
            }
            break;
        }
        _currentState = state;
    }
References System.Xml.XmlWellFormedWriter._currentState, System.Xml.XmlWellFormedWriter._rawWriter, System.Xml.XmlWellFormedWriter._stateTable, System.SR.Format(), System.Xml.XmlWellFormedWriter.GetStateName(), System.Xml.XmlWellFormedWriter.StartElementContent(), System.Xml.XmlWellFormedWriter.StartFragment(), System.state, System.Xml.XmlWellFormedWriter.ThrowInvalidStateTransition(), System.Xml.XmlWellFormedWriter.tokenName, System.Xml.XmlWellFormedWriter.WriteEndAttribute(), System.Xml.XmlRawWriter.WriteEndBase64(), System.Xml.XmlWellFormedWriter.WriteStartDocument(), System.SR.Xml_ClosedOrError, and System.SR.Xml_WrongToken.
Referenced by System.Xml.XmlWellFormedWriter.Close(), System.Xml.XmlWellFormedWriter.WriteBase64(), System.Xml.XmlWellFormedWriter.WriteBinHex(), System.Xml.XmlWellFormedWriter.WriteCData(), System.Xml.XmlWellFormedWriter.WriteCharEntity(), System.Xml.XmlWellFormedWriter.WriteChars(), System.Xml.XmlWellFormedWriter.WriteComment(), System.Xml.XmlWellFormedWriter.WriteDocType(), System.Xml.XmlWellFormedWriter.WriteEndAttribute(), System.Xml.XmlWellFormedWriter.WriteEndDocument(), System.Xml.XmlWellFormedWriter.WriteEndElement(), System.Xml.XmlWellFormedWriter.WriteEntityRef(), System.Xml.XmlWellFormedWriter.WriteFullEndElement(), System.Xml.XmlWellFormedWriter.WriteProcessingInstruction(), System.Xml.XmlWellFormedWriter.WriteQualifiedName(), System.Xml.XmlWellFormedWriter.WriteRaw(), System.Xml.XmlWellFormedWriter.WriteRaw(), System.Xml.XmlWellFormedWriter.WriteStartAttribute(), System.Xml.XmlWellFormedWriter.WriteStartDocumentImpl(), System.Xml.XmlWellFormedWriter.WriteStartElement(), System.Xml.XmlWellFormedWriter.WriteString(), System.Xml.XmlWellFormedWriter.WriteSurrogateCharEntity(), System.Xml.XmlWellFormedWriter.WriteValue(), System.Xml.XmlWellFormedWriter.WriteValue(), System.Xml.XmlWellFormedWriter.WriteValue(), System.Xml.XmlWellFormedWriter.WriteValue(), System.Xml.XmlWellFormedWriter.WriteValue(), System.Xml.XmlWellFormedWriter.WriteValue(), System.Xml.XmlWellFormedWriter.WriteValue(), System.Xml.XmlWellFormedWriter.WriteValue(), System.Xml.XmlWellFormedWriter.WriteValue(), System.Xml.XmlWellFormedWriter.WriteValue(), and System.Xml.XmlWellFormedWriter.WriteWhitespace().