Terraria: System.Xml.XmlWellFormedWriter.WriteStartDocumentImpl
WriteStartDocumentImpl()
void System.Xml.XmlWellFormedWriter.WriteStartDocumentImpl (XmlStandalone standalone) inline private
Definition at line 2512 of file XmlWellFormedWriter.cs.
    {
        try
        {
            AdvanceState(Token.StartDocument);
            if (_conformanceLevel == ConformanceLevel.Auto)
            {
                _conformanceLevel = ConformanceLevel.Document;
                _stateTable = s_stateTableDocument;
            }
            else if (_conformanceLevel == ConformanceLevel.Fragment)
            {
                throw new InvalidOperationException(System.SR.Xml_CannotStartDocumentOnFragment);
            }
            if (_rawWriter != null)
            {
                if (!_xmlDeclFollows)
                {
                    _rawWriter.WriteXmlDeclaration(standalone);
                }
            }
            else
            {
                _writer.WriteStartDocument();
            }
        }
        catch
        {
            _currentState = State.Error;
            throw;
        }
    }
References System.Xml.XmlWellFormedWriter._conformanceLevel, System.Xml.XmlWellFormedWriter._currentState, System.Xml.XmlWellFormedWriter._rawWriter, System.Xml.XmlWellFormedWriter._stateTable, System.Xml.XmlWellFormedWriter._writer, System.Xml.XmlWellFormedWriter._xmlDeclFollows, System.Xml.XmlWellFormedWriter.AdvanceState(), System.Xml.XmlWellFormedWriter.s_stateTableDocument, System.Xml.XmlWriter.WriteStartDocument(), System.Xml.XmlRawWriter.WriteXmlDeclaration(), and System.SR.Xml_CannotStartDocumentOnFragment.
Referenced by System.Xml.XmlWellFormedWriter.WriteStartDocument(), and System.Xml.XmlWellFormedWriter.WriteStartDocument().