Terraria: System.Xml.XmlWellFormedWriter.WriteRaw
WriteRaw() [1/2]
override void System.Xml.XmlWellFormedWriter.WriteRaw (char[] buffer, int index, int count) inline
Definition at line 2084 of file XmlWellFormedWriter.cs.
    {
        try
        {
            if (buffer == null)
            {
                throw new ArgumentNullException("buffer");
            }
            if (index < 0)
            {
                throw new ArgumentOutOfRangeException("index");
            }
            if (count < 0)
            {
                throw new ArgumentOutOfRangeException("count");
            }
            if (count > buffer.Length - index)
            {
                throw new ArgumentOutOfRangeException("count");
            }
            AdvanceState(Token.RawData);
            if (SaveAttrValue)
            {
                _attrValueCache.WriteRaw(buffer, index, count);
            }
            else
            {
                _writer.WriteRaw(buffer, index, count);
            }
        }
        catch
        {
            _currentState = State.Error;
            throw;
        }
    }
References System.Xml.XmlWellFormedWriter._attrValueCache, System.Xml.XmlWellFormedWriter._currentState, System.Xml.XmlWellFormedWriter._writer, System.Xml.XmlWellFormedWriter.AdvanceState(), System.buffer, System.count, System.index, System.Xml.XmlWellFormedWriter.SaveAttrValue, System.Xml.XmlWellFormedWriter.AttributeValueCache.WriteRaw(), and System.Xml.XmlWriter.WriteRaw().