Terraria: System.Xml.XmlWellFormedWriter.WriteQualifiedNameAsync
WriteQualifiedNameAsync() [1/2]
override async Task System.Xml.XmlWellFormedWriter.WriteQualifiedNameAsync (string localName, string ns) inline
Definition at line 4115 of file XmlWellFormedWriter.cs.
    {
        _ = 4;
        try
        {
            if (localName == null || localName.Length == 0)
            {
                throw new ArgumentException(System.SR.Xml_EmptyLocalName);
            }
            CheckNCName(localName);
            await AdvanceStateAsync(Token.Text).ConfigureAwait(continueOnCapturedContext: false);
            string text = string.Empty;
            if (ns != null && ns.Length != 0)
            {
                text = LookupPrefix(ns);
                if (text == null)
                {
                    if (_currentState != State.Attribute)
                    {
                        throw new ArgumentException(System.SR.Format(System.SR.Xml_UndefNamespace, ns));
                    }
                    text = GeneratePrefix();
                    PushNamespaceImplicit(text, ns);
                }
            }
            if (SaveAttrValue || _rawWriter == null)
            {
                if (text.Length != 0)
                {
                    await WriteStringAsync(text).ConfigureAwait(continueOnCapturedContext: false);
                    await WriteStringAsync(":").ConfigureAwait(continueOnCapturedContext: false);
                }
                await WriteStringAsync(localName).ConfigureAwait(continueOnCapturedContext: false);
            }
            else
            {
                await _rawWriter.WriteQualifiedNameAsync(text, localName, ns).ConfigureAwait(continueOnCapturedContext: false);
            }
        }
        catch
        {
            _currentState = State.Error;
            throw;
        }
    }
References System.Xml.XmlWellFormedWriter._currentState, System.Xml.XmlWellFormedWriter._rawWriter, System.Xml.XmlWellFormedWriter.AdvanceStateAsync(), System.Xml.ArgumentException, System.Xml.XmlWellFormedWriter.CheckNCName(), System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.SR.Format(), System.Xml.XmlWellFormedWriter.GeneratePrefix(), System.Xml.XmlWellFormedWriter.LookupPrefix(), System.Xml.XmlWellFormedWriter.PushNamespaceImplicit(), System.Xml.XmlWellFormedWriter.SaveAttrValue, System.text, System.Xml.XmlRawWriter.WriteQualifiedNameAsync(), System.Xml.XmlWellFormedWriter.WriteStringAsync(), System.SR.Xml_EmptyLocalName, and System.SR.Xml_UndefNamespace.