Terraria: System.Xml.XmlWellFormedWriter.CheckNCName
CheckNCName()
void System.Xml.XmlWellFormedWriter.CheckNCName (string ncname) inline private
Definition at line 2935 of file XmlWellFormedWriter.cs.
    {
        int length = ncname.Length;
        if (XmlCharType.IsStartNCNameSingleChar(ncname[0]))
        {
            for (int i = 1; i < length; i++)
            {
                if (!XmlCharType.IsNCNameSingleChar(ncname[i]))
                {
                    throw InvalidCharsException(ncname, i);
                }
            }
            return;
        }
        throw InvalidCharsException(ncname, 0);
    }
References System.Xml.XmlWellFormedWriter.InvalidCharsException(), System.Xml.XmlCharType.IsNCNameSingleChar(), System.Xml.XmlCharType.IsStartNCNameSingleChar(), and System.length.
Referenced by System.Xml.XmlWellFormedWriter.WriteEntityRef(), System.Xml.XmlWellFormedWriter.WriteEntityRefAsync(), System.Xml.XmlWellFormedWriter.WriteProcessingInstruction(), System.Xml.XmlWellFormedWriter.WriteProcessingInstructionAsync(), System.Xml.XmlWellFormedWriter.WriteQualifiedName(), System.Xml.XmlWellFormedWriter.WriteQualifiedNameAsync(), System.Xml.XmlWellFormedWriter.WriteStartAttribute(), System.Xml.XmlWellFormedWriter.WriteStartAttributeAsync(), System.Xml.XmlWellFormedWriter.WriteStartAttributeAsync_NoAdvanceState(), System.Xml.XmlWellFormedWriter.WriteStartElement(), System.Xml.XmlWellFormedWriter.WriteStartElementAsync(), and System.Xml.XmlWellFormedWriter.WriteStartElementAsync_NoAdvanceState().