Terraria: System.Xml.XmlWellFormedWriter.WriteStartAttribute
WriteStartAttribute() [3/4]
override void System.Xml.XmlWellFormedWriter.WriteStartAttribute (string prefix, string localName, string namespaceName) inline
Definition at line 1587 of file XmlWellFormedWriter.cs.
    {
        try
        {
            if (localName == null || localName.Length == 0)
            {
                if (!(prefix == "xmlns"))
                {
                    throw new ArgumentException(System.SR.Xml_EmptyLocalName);
                }
                localName = "xmlns";
                prefix = string.Empty;
            }
            CheckNCName(localName);
            AdvanceState(Token.StartAttribute);
            if (prefix == null)
            {
                if (namespaceName != null && (!(localName == "xmlns") || !(namespaceName == "http://www.w3.org/2000/xmlns/")))
                {
                    prefix = LookupPrefix(namespaceName);
                }
                if (prefix == null)
                {
                    prefix = string.Empty;
                }
            }
            if (namespaceName == null)
            {
                if (prefix.Length > 0)
                {
                    namespaceName = LookupNamespace(prefix);
                }
                if (namespaceName == null)
                {
                    namespaceName = string.Empty;
                }
            }
            if (prefix.Length == 0)
            {
                if (localName[0] != 'x' || !(localName == "xmlns"))
                {
                    if (namespaceName.Length > 0)
                    {
                        prefix = LookupPrefix(namespaceName);
                        if (prefix == null || prefix.Length == 0)
{
                            prefix = GeneratePrefix();
                        }
                    }
                    goto IL_01fd;
                }
                if (namespaceName.Length > 0 && namespaceName != "http://www.w3.org/2000/xmlns/")
                {
                    throw new ArgumentException(System.SR.Xml_XmlnsPrefix);
                }
                _curDeclPrefix = string.Empty;
                SetSpecialAttribute(SpecialAttribute.DefaultXmlns);
            }
            else
            {
                if (prefix[0] != 'x')
                {
                    goto IL_01c9;
                }
                if (prefix == "xmlns")
                {
                    if (namespaceName.Length > 0 && namespaceName != "http://www.w3.org/2000/xmlns/")
                    {
                        throw new ArgumentException(System.SR.Xml_XmlnsPrefix);
                    }
                    _curDeclPrefix = localName;
                    SetSpecialAttribute(SpecialAttribute.PrefixedXmlns);
                }
                else
                {
                    if (!(prefix == "xml"))
                    {
                        goto IL_01c9;
                    }
                    if (namespaceName.Length > 0 && namespaceName != "http://www.w3.org/XML/1998/namespace")
                    {
                        throw new ArgumentException(System.SR.Xml_XmlPrefix);
                    }
                    if (!(localName == "space"))
                    {
                        if (!(localName == "lang"))
{
                            goto IL_01c9;
                        }
                        SetSpecialAttribute(SpecialAttribute.XmlLang);
                    }
                    else
                    {
                        SetSpecialAttribute(SpecialAttribute.XmlSpace);
                    }
                }
            }
            goto IL_020d;
            IL_01c9:
            CheckNCName(prefix);
            if (namespaceName.Length == 0)
            {
                prefix = string.Empty;
            }
            else
            {
                string text = LookupLocalNamespace(prefix);
                if (text != null && text != namespaceName)
                {
                    prefix = GeneratePrefix();
                }
            }
            goto IL_01fd;
            IL_01fd:
            if (prefix.Length != 0)
            {
                PushNamespaceImplicit(prefix, namespaceName);
            }
            goto IL_020d;
            IL_020d:
            AddAttribute(prefix, localName, namespaceName);
            if (_specAttr == SpecialAttribute.No)
            {
                _writer.WriteStartAttribute(prefix, localName, namespaceName);
            }
        }
        catch
        {
            _currentState = State.Error;
            throw;
        }
    }
References System.Xml.XmlWellFormedWriter._curDeclPrefix, System.Xml.XmlWellFormedWriter._currentState, System.Xml.XmlWellFormedWriter._specAttr, System.Xml.XmlWellFormedWriter._writer, System.Xml.XmlWellFormedWriter.AddAttribute(), System.Xml.XmlWellFormedWriter.AdvanceState(), System.Xml.ArgumentException, System.Xml.XmlWellFormedWriter.CheckNCName(), System.Xml.Dictionary, System.Xml.XmlWellFormedWriter.GeneratePrefix(), System.Xml.XmlWellFormedWriter.LookupLocalNamespace(), System.Xml.XmlWellFormedWriter.LookupNamespace(), System.Xml.XmlWellFormedWriter.LookupPrefix(), System.prefix, System.Xml.XmlWellFormedWriter.PushNamespaceImplicit(), System.Xml.XmlWellFormedWriter.SetSpecialAttribute(), System.text, System.Xml.XmlWriter.WriteStartAttribute(), System.SR.Xml_EmptyLocalName, System.SR.Xml_XmlnsPrefix, and System.SR.Xml_XmlPrefix.