Terraria: System.Xml.XmlWellFormedWriter.WriteEntityRef
WriteEntityRef()
override void System.Xml.XmlWellFormedWriter.WriteEntityRef (string name) inline
Definition at line 1918 of file XmlWellFormedWriter.cs.
    {
        try
        {
            if (name == null || name.Length == 0)
            {
                throw new ArgumentException(System.SR.Xml_EmptyName);
            }
            CheckNCName(name);
            AdvanceState(Token.Text);
            if (SaveAttrValue)
            {
                _attrValueCache.WriteEntityRef(name);
            }
            else
            {
                _writer.WriteEntityRef(name);
            }
        }
        catch
        {
            _currentState = State.Error;
            throw;
        }
    }
References System.Xml.XmlWellFormedWriter._attrValueCache, System.Xml.XmlWellFormedWriter._currentState, System.Xml.XmlWellFormedWriter._writer, System.Xml.XmlWellFormedWriter.AdvanceState(), System.Xml.ArgumentException, System.Xml.XmlWellFormedWriter.CheckNCName(), System.Xml.XmlWellFormedWriter.SaveAttrValue, System.Xml.XmlWellFormedWriter.AttributeValueCache.WriteEntityRef(), System.Xml.XmlWriter.WriteEntityRef(), and System.SR.Xml_EmptyName.