Terraria: System.Xml.XmlWellFormedWriter.WriteRawAsync
WriteRawAsync() [1/2]
override async Task System.Xml.XmlWellFormedWriter.WriteRawAsync (char[] buffer, int index, int count) inline virtual
Reimplemented from System.Xml.XmlWriter.
Definition at line 3990 of file XmlWellFormedWriter.cs.
    {
        _ = 1;
        try
        {
            if (buffer == null)
            {
                throw new ArgumentNullException("buffer");
            }
            if (index < 0)
            {
                throw new ArgumentOutOfRangeException("index");
            }
            if (count < 0)
            {
                throw new ArgumentOutOfRangeException("count");
            }
            if (count > buffer.Length - index)
            {
                throw new ArgumentOutOfRangeException("count");
            }
            await AdvanceStateAsync(Token.RawData).ConfigureAwait(continueOnCapturedContext: false);
            if (SaveAttrValue)
            {
                _attrValueCache.WriteRaw(buffer, index, count);
            }
            else
            {
                await _writer.WriteRawAsync(buffer, index, count).ConfigureAwait(continueOnCapturedContext: false);
            }
        }
        catch
        {
            _currentState = State.Error;
            throw;
        }
    }
References System.Xml.XmlWellFormedWriter._attrValueCache, System.Xml.XmlWellFormedWriter._currentState, System.Xml.XmlWellFormedWriter._writer, System.Xml.XmlWellFormedWriter.AdvanceStateAsync(), System.buffer, System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.count, System.index, System.Xml.XmlWellFormedWriter.SaveAttrValue, System.Xml.XmlWellFormedWriter.AttributeValueCache.WriteRaw(), and System.Xml.XmlWriter.WriteRawAsync().