Terraria: System.Xml.XmlWellFormedWriter.ThrowInvalidStateTransition
ThrowInvalidStateTransition()
void System.Xml.XmlWellFormedWriter.ThrowInvalidStateTransition (Token token, State currentState) inline private
Definition at line 2966 of file XmlWellFormedWriter.cs.
    {
        string text = System.SR.Format(System.SR.Xml_WrongToken, tokenName[(int)token], GetStateName(currentState));
        if ((currentState == State.Start || currentState == State.AfterRootEle) && _conformanceLevel == ConformanceLevel.Document)
        {
            throw new InvalidOperationException(text + " " + System.SR.Xml_ConformanceLevelFragment);
        }
        throw new InvalidOperationException(text);
    }
References System.Xml.XmlWellFormedWriter._conformanceLevel, System.SR.Format(), System.Xml.XmlWellFormedWriter.GetStateName(), System.text, System.Xml.XmlWellFormedWriter.tokenName, System.SR.Xml_ConformanceLevelFragment, and System.SR.Xml_WrongToken.
Referenced by System.Xml.XmlWellFormedWriter.AdvanceState(), and System.Xml.XmlWellFormedWriter.AdvanceStateAsync().