Terraria: System.Xml.XmlWellFormedWriter.WriteCharEntityAsync
WriteCharEntityAsync()
override async Task System.Xml.XmlWellFormedWriter.WriteCharEntityAsync (char ch) inline virtual
Reimplemented from System.Xml.XmlWriter.
Definition at line 3815 of file XmlWellFormedWriter.cs.
    {
        _ = 1;
        try
        {
            if (char.IsSurrogate(ch))
            {
                throw new ArgumentException(System.SR.Xml_InvalidSurrogateMissingLowChar);
            }
            await AdvanceStateAsync(Token.Text).ConfigureAwait(continueOnCapturedContext: false);
            if (SaveAttrValue)
            {
                _attrValueCache.WriteCharEntity(ch);
            }
            else
            {
                await _writer.WriteCharEntityAsync(ch).ConfigureAwait(continueOnCapturedContext: false);
            }
        }
        catch
        {
            _currentState = State.Error;
            throw;
        }
    }
References System.Xml.XmlWellFormedWriter._attrValueCache, System.Xml.XmlWellFormedWriter._currentState, System.Xml.XmlWellFormedWriter._writer, System.Xml.XmlWellFormedWriter.AdvanceStateAsync(), System.Xml.ArgumentException, System.ch, System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.Xml.XmlWellFormedWriter.SaveAttrValue, System.Xml.XmlWellFormedWriter.AttributeValueCache.WriteCharEntity(), System.Xml.XmlWriter.WriteCharEntityAsync(), and System.SR.Xml_InvalidSurrogateMissingLowChar.