Terraria: System.Xml.XmlWellFormedWriter.WriteStartElementAsync_FinishWrite
WriteStartElementAsync_FinishWrite() [1/2]
void System.Xml.XmlWellFormedWriter.WriteStartElementAsync_FinishWrite (string prefix, string localName, string ns) inline private
Definition at line 3268 of file XmlWellFormedWriter.cs.
    {
        try
        {
            int num = ++_elemTop;
            if (num == _elemScopeStack.Length)
            {
                ElementScope[] array = new ElementScope[num * 2];
                Array.Copy(_elemScopeStack, array, num);
                _elemScopeStack = array;
            }
            _elemScopeStack[num].Set(prefix, localName, ns, _nsTop);
            PushNamespaceImplicit(prefix, ns);
            if (_attrCount >= 14)
            {
                _attrHashTable.Clear();
            }
            _attrCount = 0;
        }
        catch
        {
            _currentState = State.Error;
            throw;
        }
    }
References System.Xml.XmlWellFormedWriter._attrCount, System.Xml.XmlWellFormedWriter._attrHashTable, System.Xml.XmlWellFormedWriter._currentState, System.Xml.XmlWellFormedWriter._elemScopeStack, System.Xml.XmlWellFormedWriter._elemTop, System.Xml.XmlWellFormedWriter._nsTop, System.array, System.Collections.Generic.Dictionary< TKey, TValue >.Clear(), System.Array.Copy(), System.prefix, System.Xml.XmlWellFormedWriter.PushNamespaceImplicit(), and System.Xml.XmlWellFormedWriter.ElementScope.Set().
Referenced by System.Xml.XmlWellFormedWriter.WriteStartElementAsync_FinishWrite(), and System.Xml.XmlWellFormedWriter.WriteStartElementAsync_NoAdvanceState().