Terraria: System.Xml.XmlWellFormedWriter.WriteWhitespace
WriteWhitespace() [1/2]
override void System.Xml.XmlWellFormedWriter.WriteWhitespace (string ws) inline
Definition at line 1994 of file XmlWellFormedWriter.cs.
    {
        try
        {
            if (ws == null)
            {
                ws = string.Empty;
            }
            if (!XmlCharType.IsOnlyWhitespace(ws))
            {
                throw new ArgumentException(System.SR.Xml_NonWhitespace);
            }
            AdvanceState(Token.Whitespace);
            if (SaveAttrValue)
            {
                _attrValueCache.WriteWhitespace(ws);
            }
            else
            {
                _writer.WriteWhitespace(ws);
            }
        }
        catch
        {
            _currentState = State.Error;
            throw;
        }
    }
References System.Xml.XmlWellFormedWriter._attrValueCache, System.Xml.XmlWellFormedWriter._currentState, System.Xml.XmlWellFormedWriter._writer, System.Xml.XmlWellFormedWriter.AdvanceState(), System.Xml.ArgumentException, System.Xml.XmlCharType.IsOnlyWhitespace(), System.Xml.XmlWellFormedWriter.SaveAttrValue, System.Xml.XmlWellFormedWriter.AttributeValueCache.WriteWhitespace(), System.Xml.XmlWriter.WriteWhitespace(), and System.SR.Xml_NonWhitespace.