Terraria: System.Xml.XmlWellFormedWriter.WriteEndAttributeAsync_SepcialAtt
WriteEndAttributeAsync_SepcialAtt()
async Task System.Xml.XmlWellFormedWriter.WriteEndAttributeAsync_SepcialAtt () inline private
Definition at line 3602 of file XmlWellFormedWriter.cs.
    {
        _ = 19;
        try
        {
            switch (_specAttr)
            {
            case SpecialAttribute.DefaultXmlns:
            {
                string stringValue = _attrValueCache.StringValue;
                if (PushNamespaceExplicit(string.Empty, stringValue))
                {
                    if (_rawWriter == null)
                    {
                        await _writer.WriteStartAttributeAsync(string.Empty, "xmlns", "http://www.w3.org/2000/xmlns/").ConfigureAwait(continueOnCapturedContext: false);
                        await _attrValueCache.ReplayAsync(_writer).ConfigureAwait(continueOnCapturedContext: false);
                        await _writer.WriteEndAttributeAsync().ConfigureAwait(continueOnCapturedContext: false);
                    }
                    else if (!_rawWriter.SupportsNamespaceDeclarationInChunks)
                    {
                        await _rawWriter.WriteNamespaceDeclarationAsync(string.Empty, stringValue).ConfigureAwait(continueOnCapturedContext: false);
                    }
                    else
                    {
                        await _rawWriter.WriteStartNamespaceDeclarationAsync(string.Empty).ConfigureAwait(continueOnCapturedContext: false);
                        await _attrValueCache.ReplayAsync(_rawWriter).ConfigureAwait(continueOnCapturedContext: false);
                        await _rawWriter.WriteEndNamespaceDeclarationAsync().ConfigureAwait(continueOnCapturedContext: false);
                    }
                }
                _curDeclPrefix = null;
                break;
            }
            case SpecialAttribute.PrefixedXmlns:
            {
                string stringValue = _attrValueCache.StringValue;
                if (stringValue.Length == 0)
                {
                    throw new ArgumentException(System.SR.Xml_PrefixForEmptyNs);
                }
                if (stringValue == "http://www.w3.org/2000/xmlns/" || (stringValue == "http://www.w3.org/XML/1998/namespace" && _curDeclPrefix != "xml"))
                {
                    throw new ArgumentException(System.SR.Xml_CanNotBindToReservedNamespace);
                }
                if (PushNamespaceExplicit(_curDeclPrefix, stringValue))
                {
                    if (_rawWriter == null)
                    {
                        await _writer.WriteStartAttributeAsync("xmlns", _curDeclPrefix, "http://www.w3.org/2000/xmlns/").ConfigureAwait(continueOnCapturedContext: false);
                        await _attrValueCache.ReplayAsync(_writer).ConfigureAwait(continueOnCapturedContext: false);
                        await _writer.WriteEndAttributeAsync().ConfigureAwait(continueOnCapturedContext: false);
                    }
                    else if (!_rawWriter.SupportsNamespaceDeclarationInChunks)
                    {
                        await _rawWriter.WriteNamespaceDeclarationAsync(_curDeclPrefix, stringValue).ConfigureAwait(continueOnCapturedContext: false);
                    }
                    else
                    {
                        await _rawWriter.WriteStartNamespaceDeclarationAsync(_curDeclPrefix).ConfigureAwait(continueOnCapturedContext: false);
                        await _attrValueCache.ReplayAsync(_rawWriter).ConfigureAwait(continueOnCapturedContext: false);
                        await _rawWriter.WriteEndNamespaceDeclarationAsync().ConfigureAwait(continueOnCapturedContext: false);
                    }
                }
                _curDeclPrefix = null;
                break;
            }
            case SpecialAttribute.XmlSpace:
            {
                _attrValueCache.Trim();
                string stringValue = _attrValueCache.StringValue;
                if (stringValue == "default")
                {
                    _elemScopeStack[_elemTop].xmlSpace = XmlSpace.Default;
                }
                else
                {
                    if (!(stringValue == "preserve"))
                    {
                        throw new ArgumentException(System.SR.Format(System.SR.Xml_InvalidXmlSpace, stringValue));
                    }
                    _elemScopeStack[_elemTop].xmlSpace = XmlSpace.Preserve;
                }
                await _writer.WriteStartAttributeAsync("xml", "space", "http://www.w3.org/XML/1998/namespace").ConfigureAwait(continueOnCapturedContext: false);
                await _attrValueCache.ReplayAsync(_writer).ConfigureAwait(continueOnCapturedContext: false);
                await _writer.WriteEndAttributeAsync().ConfigureAwait(continueOnCapturedContext: false);
                break;
            }
            case SpecialAttribute.XmlLang:
            {
                string stringValue = _attrValueCache.StringValue;
                _elemScopeStack[_elemTop].xmlLang = stringValue;
                await _writer.WriteStartAttributeAsync("xml", "lang", "http://www.w3.org/XML/1998/namespace").ConfigureAwait(continueOnCapturedContext: false);
                await _attrValueCache.ReplayAsync(_writer).ConfigureAwait(continueOnCapturedContext: false);
                await _writer.WriteEndAttributeAsync().ConfigureAwait(continueOnCapturedContext: false);
                break;
            }
            }
            _specAttr = SpecialAttribute.No;
            _attrValueCache.Clear();
        }
        catch
        {
            _currentState = State.Error;
            throw;
        }
    }
References System.Xml.XmlWellFormedWriter._attrValueCache, System.Xml.XmlWellFormedWriter._curDeclPrefix, System.Xml.XmlWellFormedWriter._currentState, System.Xml.XmlWellFormedWriter._elemScopeStack, System.Xml.XmlWellFormedWriter._elemTop, System.Xml.XmlWellFormedWriter._rawWriter, System.Xml.XmlWellFormedWriter._specAttr, System.Xml.XmlWellFormedWriter._writer, System.Xml.ArgumentException, System.Xml.XmlWellFormedWriter.AttributeValueCache.Clear(), System.Xml.Dictionary, System.SR.Format(), System.Xml.XmlWellFormedWriter.PushNamespaceExplicit(), System.Xml.XmlWellFormedWriter.AttributeValueCache.ReplayAsync(), System.Xml.XmlWellFormedWriter.AttributeValueCache.StringValue, System.Xml.XmlRawWriter.SupportsNamespaceDeclarationInChunks, System.Xml.XmlWellFormedWriter.AttributeValueCache.Trim(), System.Xml.XmlWriter.WriteEndAttributeAsync(), System.Xml.XmlRawWriter.WriteEndNamespaceDeclarationAsync(), System.Xml.XmlRawWriter.WriteNamespaceDeclarationAsync(), System.Xml.XmlWriter.WriteStartAttributeAsync(), System.Xml.XmlRawWriter.WriteStartNamespaceDeclarationAsync(), System.SR.Xml_CanNotBindToReservedNamespace, System.SR.Xml_InvalidXmlSpace, System.SR.Xml_PrefixForEmptyNs, System.Xml.XmlWellFormedWriter.ElementScope.xmlLang, and System.Xml.XmlWellFormedWriter.ElementScope.xmlSpace.
Referenced by System.Xml.XmlWellFormedWriter.WriteEndAttributeAsync_NoAdvance().