Terraria: System.Xml.XmlWellFormedWriter.WriteDocType
WriteDocType() [1/2]
override void System.Xml.XmlWellFormedWriter.WriteDocType (string name, string pubid, string sysid, string subset) inline
Definition at line 1377 of file XmlWellFormedWriter.cs.
    {
        try
        {
            if (name == null || name.Length == 0)
            {
                throw new ArgumentException(System.SR.Xml_EmptyName);
            }
            XmlConvert.VerifyQName(name, ExceptionType.XmlException);
            if (_conformanceLevel == ConformanceLevel.Fragment)
            {
                throw new InvalidOperationException(System.SR.Xml_DtdNotAllowedInFragment);
            }
            AdvanceState(Token.Dtd);
            if (_dtdWritten)
            {
                _currentState = State.Error;
                throw new InvalidOperationException(System.SR.Xml_DtdAlreadyWritten);
            }
            if (_conformanceLevel == ConformanceLevel.Auto)
            {
                _conformanceLevel = ConformanceLevel.Document;
                _stateTable = s_stateTableDocument;
            }
            if (_checkCharacters)
            {
                int invCharIndex;
                if (pubid != null && (invCharIndex = XmlCharType.IsPublicId(pubid)) >= 0)
                {
                    string xml_InvalidCharacter = System.SR.Xml_InvalidCharacter;
                    object[] args = XmlException.BuildCharExceptionArgs(pubid, invCharIndex);
                    throw new ArgumentException(System.SR.Format(xml_InvalidCharacter, args), "pubid");
                }
                if (sysid != null && (invCharIndex = XmlCharType.IsOnlyCharData(sysid)) >= 0)
                {
                    string xml_InvalidCharacter2 = System.SR.Xml_InvalidCharacter;
                    object[] args = XmlException.BuildCharExceptionArgs(sysid, invCharIndex);
                    throw new ArgumentException(System.SR.Format(xml_InvalidCharacter2, args), "sysid");
                }
                if (subset != null && (invCharIndex = XmlCharType.IsOnlyCharData(subset)) >= 0)
                {
                    string xml_InvalidCharacter3 = System.SR.Xml_InvalidCharacter;
                    object[] args = XmlException.BuildCharExceptionArgs(subset, invCharIndex);
                    throw new ArgumentException(System.SR.Format(xml_InvalidCharacter3, args), "subset");
                }
            }
            _writer.WriteDocType(name, pubid, sysid, subset);
            _dtdWritten = true;
        }
        catch
        {
            _currentState = State.Error;
            throw;
        }
    }
References System.Xml.XmlWellFormedWriter._checkCharacters, System.Xml.XmlWellFormedWriter._conformanceLevel, System.Xml.XmlWellFormedWriter._currentState, System.Xml.XmlWellFormedWriter._dtdWritten, System.Xml.XmlWellFormedWriter._stateTable, System.Xml.XmlWellFormedWriter._writer, System.Xml.XmlWellFormedWriter.AdvanceState(), System.Xml.ArgumentException, System.Xml.XmlException.BuildCharExceptionArgs(), System.Xml.Dictionary, System.SR.Format(), System.Xml.XmlCharType.IsOnlyCharData(), System.Xml.XmlCharType.IsPublicId(), System.Xml.XmlWellFormedWriter.s_stateTableDocument, System.Xml.XmlConvert.VerifyQName(), System.Xml.XmlWriter.WriteDocType(), System.SR.Xml_DtdAlreadyWritten, System.SR.Xml_DtdNotAllowedInFragment, System.SR.Xml_EmptyName, and System.SR.Xml_InvalidCharacter.