Terraria: System.Xml.XmlWellFormedWriter.WriteQualifiedName
WriteQualifiedName() [1/2]
override void System.Xml.XmlWellFormedWriter.WriteQualifiedName (string localName, string ns) inline
Definition at line 2273 of file XmlWellFormedWriter.cs.
    {
        try
        {
            if (localName == null || localName.Length == 0)
            {
                throw new ArgumentException(System.SR.Xml_EmptyLocalName);
            }
            CheckNCName(localName);
            AdvanceState(Token.Text);
            string text = string.Empty;
            if (ns != null && ns.Length != 0)
            {
                text = LookupPrefix(ns);
                if (text == null)
                {
                    if (_currentState != State.Attribute)
                    {
                        throw new ArgumentException(System.SR.Format(System.SR.Xml_UndefNamespace, ns));
                    }
                    text = GeneratePrefix();
                    PushNamespaceImplicit(text, ns);
                }
            }
            if (SaveAttrValue || _rawWriter == null)
            {
                if (text.Length != 0)
                {
                    WriteString(text);
                    WriteString(":");
                }
                WriteString(localName);
            }
            else
            {
                _rawWriter.WriteQualifiedName(text, localName, ns);
            }
        }
        catch
        {
            _currentState = State.Error;
            throw;
        }
    }
References System.Xml.XmlWellFormedWriter._currentState, System.Xml.XmlWellFormedWriter._rawWriter, System.Xml.XmlWellFormedWriter.AdvanceState(), System.Xml.ArgumentException, System.Xml.XmlWellFormedWriter.CheckNCName(), System.SR.Format(), System.Xml.XmlWellFormedWriter.GeneratePrefix(), System.Xml.XmlWellFormedWriter.LookupPrefix(), System.Xml.XmlWellFormedWriter.PushNamespaceImplicit(), System.Xml.XmlWellFormedWriter.SaveAttrValue, System.text, System.Xml.XmlRawWriter.WriteQualifiedName(), System.Xml.XmlWellFormedWriter.WriteString(), System.SR.Xml_EmptyLocalName, and System.SR.Xml_UndefNamespace.