Terraria: System.Xml.XmlWellFormedWriter.WriteCDataAsync
WriteCDataAsync() [1/2]
override async Task System.Xml.XmlWellFormedWriter.WriteCDataAsync (string text) inline
Definition at line 3708 of file XmlWellFormedWriter.cs.
    {
        _ = 1;
        try
        {
            if (text == null)
            {
                text = string.Empty;
            }
            await AdvanceStateAsync(Token.CData).ConfigureAwait(continueOnCapturedContext: false);
            await _writer.WriteCDataAsync(text).ConfigureAwait(continueOnCapturedContext: false);
        }
        catch
        {
            _currentState = State.Error;
            throw;
        }
    }
References System.Xml.XmlWellFormedWriter._currentState, System.Xml.XmlWellFormedWriter._writer, System.Xml.XmlWellFormedWriter.AdvanceStateAsync(), System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.text, and System.Xml.XmlWriter.WriteCDataAsync().