Terraria: System.Xml.XmlWellFormedWriter.StartElementContentAsync_WithNS
StartElementContentAsync_WithNS()
async Task System.Xml.XmlWellFormedWriter.StartElementContentAsync_WithNS () inline private
Definition at line 4334 of file XmlWellFormedWriter.cs.
    {
        int start = _elemScopeStack[_elemTop].prevNSTop;
        for (int i = _nsTop; i > start; i--)
        {
            if (_nsStack[i].kind == NamespaceKind.NeedToWrite)
            {
                await _nsStack[i].WriteDeclAsync(_writer, _rawWriter).ConfigureAwait(continueOnCapturedContext: false);
            }
        }
        if (_rawWriter != null)
        {
            _rawWriter.StartElementContent();
        }
    }
References System.Xml.XmlWellFormedWriter._elemScopeStack, System.Xml.XmlWellFormedWriter._elemTop, System.Xml.XmlWellFormedWriter._nsStack, System.Xml.XmlWellFormedWriter._nsTop, System.Xml.XmlWellFormedWriter._rawWriter, System.Xml.XmlWellFormedWriter._writer, System.Xml.XmlWellFormedWriter.ElementScope.prevNSTop, System.start, System.Xml.XmlRawWriter.StartElementContent(), and System.Xml.XmlWellFormedWriter.Namespace.WriteDeclAsync().
Referenced by System.Xml.XmlWellFormedWriter.StartElementContentAsync().