Terraria: CaveHouseBiome.Place
Place()
override bool CaveHouseBiome.Place (Point origin, StructureMap structures) inline virtual
Implements GenStructure.
     {
         if (!WorldGen.InWorld(origin.X, origin.Y, 10))
         {
             return false;
         }
         int num = 25;
         for (int i = origin.X - num; i <= origin.X + num; i++)
         {
             for (int j = origin.Y - num; j <= origin.Y + num; j++)
             {
                 if (Main.tile[i, j].wire())
                 {
                     return false;
                 }
                 if (TileID.Sets.BasicChest[Main.tile[i, j].type])
                 {
                     return false;
                 }
             }
         }
         HouseBuilder houseBuilder = HouseUtils.CreateBuilder(origin, structures);
         if (!houseBuilder.IsValid)
         {
             return false;
         }
         ApplyConfigurationToBuilder(houseBuilder);
         houseBuilder.Place(_builderContext, structures);
         return true;
     }
References _builderContext, ApplyConfigurationToBuilder(), TileID.Sets.BasicChest, HouseUtils.CreateBuilder(), WorldGen.InWorld(), HouseBuilder.IsValid, HouseBuilder.Place(), Main.tile, Tile.type, and Tile.wire().