Terraria: System.Reflection.Emit.DynamicScope.GetTokenFor
GetTokenFor() [5/9]
int System.Reflection.Emit.DynamicScope.GetTokenFor (RuntimeMethodHandle method) inline
Definition at line 46 of file DynamicScope.cs.
    {
        IRuntimeMethodInfo methodInfo = method.GetMethodInfo();
        if (methodInfo != null)
        {
            RuntimeMethodHandleInternal value = methodInfo.Value;
            if (!RuntimeMethodHandle.IsDynamicMethod(value))
            {
                RuntimeType declaringType = RuntimeMethodHandle.GetDeclaringType(value);
                if (declaringType != null && RuntimeTypeHandle.HasInstantiation(declaringType))
                {
                    MethodBase methodBase = RuntimeType.GetMethodBase(methodInfo);
                    Type genericTypeDefinition = methodBase.DeclaringType.GetGenericTypeDefinition();
                    throw new ArgumentException(SR.Format(SR.Argument_MethodDeclaringTypeGenericLcg, methodBase, genericTypeDefinition));
                }
            }
        }
        m_tokens.Add(method);
        return (m_tokens.Count - 1) | 0x6000000;
    }
References System.Collections.Generic.List< T >.Add(), System.SR.Argument_MethodDeclaringTypeGenericLcg, System.Collections.Generic.List< T >.Count, System.SR.Format(), System.RuntimeMethodHandle.GetDeclaringType(), System.RuntimeType.GetMethodBase(), System.RuntimeTypeHandle.HasInstantiation(), System.RuntimeMethodHandle.IsDynamicMethod(), System.Reflection.Emit.DynamicScope.m_tokens, and System.value.