Terraria: System.Reflection.Emit.DynamicScope.GetTokenFor
GetTokenFor() [9/9]
int System.Reflection.Emit.DynamicScope.GetTokenFor (VarArgMethod varArgMethod) inline package
Definition at line 22 of file DynamicScope.cs.
    {
        m_tokens.Add(varArgMethod);
        return (m_tokens.Count - 1) | 0xA000000;
    }
References System.Collections.Generic.List< T >.Add(), System.Collections.Generic.List< T >.Count, and System.Reflection.Emit.DynamicScope.m_tokens.
Referenced by System.Reflection.Emit.DynamicILGenerator.DynamicILGenerator(), System.Reflection.Emit.DynamicILInfo.DynamicILInfo(), System.Reflection.Emit.DynamicILInfo.GetTokenFor(), System.Reflection.Emit.DynamicILGenerator.GetTokenFor(), System.Reflection.Emit.DynamicILInfo.GetTokenFor(), System.Reflection.Emit.DynamicILGenerator.GetTokenFor(), System.Reflection.Emit.DynamicILGenerator.GetTokenFor(), System.Reflection.Emit.DynamicILInfo.GetTokenFor(), System.Reflection.Emit.DynamicILInfo.GetTokenFor(), System.Reflection.Emit.DynamicILGenerator.GetTokenFor(), System.Reflection.Emit.DynamicILGenerator.GetTokenFor(), System.Reflection.Emit.DynamicILInfo.GetTokenFor(), System.Reflection.Emit.DynamicILInfo.GetTokenFor(), System.Reflection.Emit.DynamicILGenerator.GetTokenFor(), System.Reflection.Emit.DynamicILGenerator.GetTokenFor(), System.Reflection.Emit.DynamicILGenerator.GetTokenFor(), System.Reflection.Emit.DynamicILInfo.GetTokenFor(), System.Reflection.Emit.DynamicILInfo.GetTokenFor(), System.Reflection.Emit.DynamicILGenerator.GetTokenForSig(), System.Reflection.Emit.DynamicILGenerator.GetTokenForString(), System.Reflection.Emit.DynamicILGenerator.GetTokenForVarArgMethod(), and System.Reflection.Emit.DynamicILGenerator.GetTokenForVarArgMethod().