Terraria: System.Reflection.Emit.MethodBuilderInstantiation.MakeGenericMethod
MakeGenericMethod() [1/2]
static MethodInfo System.Reflection.Emit.MethodBuilderInstantiation.MakeGenericMethod (MethodInfo method, Type[] inst) inline static package
Definition at line 75 of file MethodBuilderInstantiation.cs.
    {
        if (!method.IsGenericMethodDefinition)
        {
            throw new InvalidOperationException();
        }
        return new MethodBuilderInstantiation(method, inst);
    }
References System.Reflection.Emit.MethodBuilderInstantiation.MethodBuilderInstantiation(), and System.Reflection.MethodBase.IsGenericMethodDefinition.
Referenced by System.Reflection.RuntimeMethodInfo.MakeGenericMethod(), System.Reflection.Emit.MethodOnTypeBuilderInstantiation.MakeGenericMethod(), and System.Reflection.Emit.MethodBuilder.MakeGenericMethod().