Terraria: System.Xml.Serialization.SchemaObjectCache.AddItem
AddItem()
XmlSchemaObject System.Xml.Serialization.SchemaObjectCache.AddItem (XmlSchemaObject item, XmlQualifiedName qname, XmlSchemas schemas) inline package
Definition at line 68 of file SchemaObjectCache.cs.
    {
        if (item == null)
        {
            return null;
        }
        if (qname == null || qname.IsEmpty)
        {
            return null;
        }
        string key = item.GetType().Name + ":" + qname.ToString();
        ArrayList arrayList = (ArrayList)ObjectCache[key];
        if (arrayList == null)
        {
            arrayList = new ArrayList();
            ObjectCache[key] = arrayList;
        }
        for (int i = 0; i < arrayList.Count; i++)
        {
            XmlSchemaObject xmlSchemaObject = (XmlSchemaObject)arrayList[i];
            if (xmlSchemaObject == item)
            {
                return xmlSchemaObject;
            }
            if (Match(xmlSchemaObject, item, shareTypes: true))
            {
                return xmlSchemaObject;
            }
            Warnings.Add(System.SR.Format(System.SR.XmlMismatchSchemaObjects, item.GetType().Name, qname.Name, qname.Namespace));
            Warnings.Add("DEBUG:Cached item key:\r\n" + (string)looks[xmlSchemaObject] + "\r\nnew item key:\r\n" + (string)looks[item]);
        }
        arrayList.Add(item);
        return item;
    }
References System.Collections.Specialized.StringCollection.Add(), System.Xml.Dictionary, System.SR.Format(), System.Xml.XmlQualifiedName.IsEmpty, System.item, System.key, System.Xml.Serialization.SchemaObjectCache.looks, System.Xml.Serialization.SchemaObjectCache.Match(), System.Xml.XmlQualifiedName.Name, System.Xml.XmlQualifiedName.Namespace, System.Xml.Serialization.SchemaObjectCache.ObjectCache, System.Xml.XmlQualifiedName.ToString(), System.Xml.Serialization.SchemaObjectCache.Warnings, and System.SR.XmlMismatchSchemaObjects.