Terraria: System.Diagnostics.NtProcessInfoHelper.GetProcessInfos
GetProcessInfos() [1/2]
static unsafe ProcessInfo[] System.Diagnostics.NtProcessInfoHelper.GetProcessInfos (int? processIdFilter = null) inline static package
Definition at line 13 of file NtProcessInfoHelper.cs.
    {
        int num = 131072;
        long[] array = Interlocked.Exchange(ref CachedBuffer, null);
        try
        {
            while (true)
            {
                if (array == null)
                {
                    array = new long[(num + 7) / 8];
                }
                uint requiredSize = 0u;
                fixed (long* systemInformation = array)
                {
                    uint num2 = global::Interop.NtDll.NtQuerySystemInformation(5, systemInformation, (uint)(array.Length * 8), &requiredSize);
                    if (num2 != 3221225476u)
                    {
                        if ((int)num2 < 0)
{
                            throw new InvalidOperationException(System.SR.CouldntGetProcessInfos, new Win32Exception((int)num2));
                        }
                        return GetProcessInfos(MemoryMarshal.AsBytes<long>(array), processIdFilter);
                    }
                }
                array = null;
                num = GetNewBufferSize(num, (int)requiredSize);
            }
        }
        finally
        {
            Interlocked.Exchange(ref CachedBuffer, array);
        }
    }
References System.array, System.Diagnostics.NtProcessInfoHelper.CachedBuffer, System.SR.CouldntGetProcessInfos, System.Threading.Interlocked.Exchange(), System.Diagnostics.NtProcessInfoHelper.GetNewBufferSize(), and System.Diagnostics.NtProcessInfoHelper.GetProcessInfos().
Referenced by System.Diagnostics.ProcessManager.GetProcessInfo(), System.Diagnostics.NtProcessInfoHelper.GetProcessInfos(), and System.Diagnostics.ProcessManager.GetProcessInfos().