Terraria: System.Diagnostics.NtProcessInfoHelper.GetProcessInfos
GetProcessInfos() [2/2]
static unsafe ProcessInfo[] System.Diagnostics.NtProcessInfoHelper.GetProcessInfos (ReadOnlySpan< byte > data, int? processIdFilter) inline static private
Definition at line 58 of file NtProcessInfoHelper.cs.
    {
        Dictionary<int, ProcessInfo> dictionary = new Dictionary<int, ProcessInfo>(60);
        int num = 0;
        while (true)
        {
            ref readonly global::Interop.NtDll.SYSTEM_PROCESS_INFORMATION reference = ref MemoryMarshal.AsRef<global::Interop.NtDll.SYSTEM_PROCESS_INFORMATION>(data.Slice(num));
            int num2 = reference.UniqueProcessId.ToInt32();
            if (!processIdFilter.HasValue || processIdFilter.GetValueOrDefault() == num2)
            {
                ProcessInfo processInfo = new ProcessInfo((int)reference.NumberOfThreads)
                {
                    ProcessId = num2,
                    SessionId = (int)reference.SessionId,
                    PoolPagedBytes = (long)(ulong)reference.QuotaPagedPoolUsage,
                    PoolNonPagedBytes = (long)(ulong)reference.QuotaNonPagedPoolUsage,
                    VirtualBytes = (long)(ulong)reference.VirtualSize,
                    VirtualBytesPeak = (long)(ulong)reference.PeakVirtualSize,
                    WorkingSetPeak = (long)(ulong)reference.PeakWorkingSetSize,
                    WorkingSet = (long)(ulong)reference.WorkingSetSize,
                    PageFileBytesPeak = (long)(ulong)reference.PeakPagefileUsage,
                    PageFileBytes = (long)(ulong)reference.PagefileUsage,
                    PrivateBytes = (long)(ulong)reference.PrivatePageCount,
                    BasePriority = reference.BasePriority,
                    HandleCount = (int)reference.HandleCount
                };
                if (reference.ImageName.Buffer == IntPtr.Zero)
                {
                    if (processInfo.ProcessId == NtProcessManager.SystemProcessID)
                    {
                        processInfo.ProcessName = "System";
                    }
                    else if (processInfo.ProcessId == 0)
                    {
                        processInfo.ProcessName = "Idle";
                    }
                    else
                    {
                        processInfo.ProcessName = processInfo.ProcessId.ToString(CultureInfo.InvariantCulture);
                    }
                }
                else
                {
                    string processShortName = GetProcessShortName(new ReadOnlySpan<char>(reference.ImageName.Buffer.ToPointer(), reference.ImageName.Length / 2));
                    processInfo.ProcessName = processShortName;
                }
                dictionary[processInfo.ProcessId] = processInfo;
                int num3 = num + sizeof(global::Interop.NtDll.SYSTEM_PROCESS_INFORMATION);
                for (int i = 0; i < reference.NumberOfThreads; i++)
                {
                    ref readonly global::Interop.NtDll.SYSTEM_THREAD_INFORMATION reference2 = ref MemoryMarshal.AsRef<global::Interop.NtDll.SYSTEM_THREAD_INFORMATION>(data.Slice(num3));
                    ThreadInfo item = new ThreadInfo
                    {
                        _processId = (int)reference2.ClientId.UniqueProcess,
                        _threadId = (ulong)(long)reference2.ClientId.UniqueThread,
                        _basePriority = reference2.BasePriority,
                        _currentPriority = reference2.Priority,
                        _startAddress = reference2.StartAddress,
                        _threadState = (ThreadState)reference2.ThreadState,
                        _threadWaitReason = NtProcessManager.GetThreadWaitReason((int)reference2.WaitReason)
                    };
                    processInfo._threadInfoList.Add(item);
                    num3 += sizeof(global::Interop.NtDll.SYSTEM_THREAD_INFORMATION);
                }
            }
            if (reference.NextEntryOffset == 0)
            {
                break;
            }
            num += (int)reference.NextEntryOffset;
        }
        ProcessInfo[] array = new ProcessInfo[dictionary.Values.Count];
        dictionary.Values.CopyTo(array, 0);
        return array;
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.array, System.dictionary, System.Diagnostics.NtProcessInfoHelper.GetProcessShortName(), System.Diagnostics.NtProcessManager.GetThreadWaitReason(), System.Globalization.CultureInfo.InvariantCulture, System.item, System.Diagnostics.ProcessId, System.Diagnostics.NtProcessManager.SystemProcessID, and System.IntPtr.Zero.