Terraria: System.Security.Cryptography.HashAlgorithm.HashCore
HashCore() [1/2]
void System.Security.Cryptography.HashAlgorithm.HashCore (byte[] array, int ibStart, int cbSize) abstract protected inherited
Referenced by System.Security.Cryptography.HashAlgorithm.ComputeHash(), System.Security.Cryptography.HashAlgorithm.ComputeHash(), System.Security.Cryptography.HashAlgorithm.ComputeHash(), System.Security.Cryptography.HashAlgorithm.ComputeHashAsyncCore(), System.Security.Cryptography.HashAlgorithm.HashCore(), System.Security.Cryptography.HashAlgorithm.TransformBlock(), System.Security.Cryptography.HashAlgorithm.TransformFinalBlock(), and System.Security.Cryptography.HashAlgorithm.TryComputeHash().