Terraria: System.Net.Mail.SmtpConnection.ConnectAndHandshakeAsyncResult.SendEHelloCallback
SendEHelloCallback()
static void System.Net.Mail.SmtpConnection.ConnectAndHandshakeAsyncResult.SendEHelloCallback (IAsyncResult result) inline static private
Definition at line 219 of file SmtpConnection.cs.
        {
            if (result.CompletedSynchronously)
            {
                return;
            }
            ConnectAndHandshakeAsyncResult connectAndHandshakeAsyncResult = (ConnectAndHandshakeAsyncResult)result.AsyncState;
            try
            {
                try
                {
                    connectAndHandshakeAsyncResult._connection._extensions = EHelloCommand.EndSend(result);
                    connectAndHandshakeAsyncResult._connection.ParseExtensions(connectAndHandshakeAsyncResult._connection._extensions);
                    if (connectAndHandshakeAsyncResult._connection._networkStream is System.Net.TlsStream)
                    {
                        connectAndHandshakeAsyncResult.Authenticate();
                        return;
                    }
                }
                catch (SmtpException ex)
                {
                    if (ex.StatusCode != SmtpStatusCode.CommandUnrecognized && ex.StatusCode != SmtpStatusCode.CommandNotImplemented)
                    {
                        throw;
                    }
                    if (!connectAndHandshakeAsyncResult.SendHello())
                    {
                        return;
                    }
                }
                if (connectAndHandshakeAsyncResult._connection.EnableSsl)
                {
                    if (!connectAndHandshakeAsyncResult._connection._serverSupportsStartTls && !(connectAndHandshakeAsyncResult._connection._networkStream is System.Net.TlsStream))
                    {
                        throw new SmtpException(System.SR.MailServerDoesNotSupportStartTls);
                    }
                    connectAndHandshakeAsyncResult.SendStartTls();
                }
                else
                {
                    connectAndHandshakeAsyncResult.Authenticate();
                }
            }
            catch (Exception result2)
            {
                connectAndHandshakeAsyncResult.InvokeCallback(result2);
            }
        }
References System.Net.Mail.SmtpConnection.ConnectAndHandshakeAsyncResult.ConnectAndHandshakeAsyncResult(), System.Net.Mail.SmtpConnection.ConnectAndHandshakeAsyncResult._connection, System.Net.Mail.SmtpConnection._extensions, System.Net.Mail.SmtpConnection._networkStream, System.Net.Mail.SmtpConnection._serverSupportsStartTls, System.IAsyncResult.AsyncState, System.Net.Mail.SmtpConnection.ConnectAndHandshakeAsyncResult.Authenticate(), System.IAsyncResult.CompletedSynchronously, System.Net.Mail.SmtpConnection.EnableSsl, System.Net.Mail.EHelloCommand.EndSend(), System.Net.LazyAsyncResult.InvokeCallback(), System.SR.MailServerDoesNotSupportStartTls, System.Net.Mail.SmtpConnection.ParseExtensions(), System.Net.Mail.SmtpConnection.ConnectAndHandshakeAsyncResult.SendHello(), System.Net.Mail.SmtpConnection.ConnectAndHandshakeAsyncResult.SendStartTls(), and System.Net.Mail.SmtpException.StatusCode.