Terraria: System.Net.Mail.SmtpConnection.ConnectAndHandshakeAsyncResult.InitializeConnectionCallback
InitializeConnectionCallback()
static void System.Net.Mail.SmtpConnection.ConnectAndHandshakeAsyncResult.InitializeConnectionCallback (IAsyncResult result) inline static private
Definition at line 111 of file SmtpConnection.cs.
        {
            if (result.CompletedSynchronously)
            {
                return;
            }
            ConnectAndHandshakeAsyncResult connectAndHandshakeAsyncResult = (ConnectAndHandshakeAsyncResult)result.AsyncState;
            try
            {
                connectAndHandshakeAsyncResult._connection.EndInitializeConnection(result);
                if (System.Net.NetEventSource.Log.IsEnabled())
                {
                    System.Net.NetEventSource.Info(null, $"Connect returned {connectAndHandshakeAsyncResult}", "InitializeConnectionCallback");
                }
                connectAndHandshakeAsyncResult.Handshake();
            }
            catch (Exception result2)
            {
                connectAndHandshakeAsyncResult.InvokeCallback(result2);
            }
        }
References System.Net.Mail.SmtpConnection.ConnectAndHandshakeAsyncResult.ConnectAndHandshakeAsyncResult(), System.Net.Mail.SmtpConnection.ConnectAndHandshakeAsyncResult._connection, System.IAsyncResult.AsyncState, System.IAsyncResult.CompletedSynchronously, System.Net.Mail.SmtpConnection.EndInitializeConnection(), System.Net.Mail.SmtpConnection.ConnectAndHandshakeAsyncResult.Handshake(), System.Net.NetEventSource.Info(), System.Net.LazyAsyncResult.InvokeCallback(), and System.Net.NetEventSource.Log.
Referenced by System.Net.Mail.SmtpConnection.ConnectAndHandshakeAsyncResult.InitializeConnection().