Terraria: System.Security.Cryptography.HashAlgorithm.CaptureHashCodeAndReinitialize
CaptureHashCodeAndReinitialize()
byte[] System.Security.Cryptography.HashAlgorithm.CaptureHashCodeAndReinitialize () inline private inherited
Definition at line 172 of file HashAlgorithm.cs.
    {
        HashValue = HashFinal();
        byte[] result = (byte[])HashValue.Clone();
        Initialize();
        return result;
    }
References System.Security.Cryptography.HashAlgorithm.HashFinal(), System.Security.Cryptography.HashAlgorithm.HashValue, and System.Security.Cryptography.HashAlgorithm.Initialize().
Referenced by System.Security.Cryptography.HashAlgorithm.ComputeHash(), System.Security.Cryptography.HashAlgorithm.ComputeHash(), System.Security.Cryptography.HashAlgorithm.ComputeHash(), System.Security.Cryptography.HashAlgorithm.ComputeHashAsyncCore(), and System.Security.Cryptography.HashAlgorithm.TransformFinalBlock().
ml"> 1.10.0