Terraria: System.Net.Mail.SmtpConnection.ConnectAndHandshakeAsyncResult.HandshakeCallback
HandshakeCallback()
static void System.Net.Mail.SmtpConnection.ConnectAndHandshakeAsyncResult.HandshakeCallback (IAsyncResult result) inline static private
Definition at line 157 of file SmtpConnection.cs.
        {
            if (result.CompletedSynchronously)
            {
                return;
            }
            ConnectAndHandshakeAsyncResult connectAndHandshakeAsyncResult = (ConnectAndHandshakeAsyncResult)result.AsyncState;
            try
            {
                try
                {
                    LineInfo lineInfo = connectAndHandshakeAsyncResult._connection.Reader.CurrentReader.EndReadLine(result);
                    if (lineInfo.StatusCode != SmtpStatusCode.ServiceReady)
                    {
                        connectAndHandshakeAsyncResult.InvokeCallback(new SmtpException(lineInfo.StatusCode, lineInfo.Line, serverResponse: true));
                    }
                    else if (connectAndHandshakeAsyncResult.SendEHello())
                    {
                    }
                }
                catch (SmtpException)
                {
                    if (connectAndHandshakeAsyncResult.SendHello())
                    {
                    }
                }
            }
            catch (Exception result2)
            {
                connectAndHandshakeAsyncResult.InvokeCallback(result2);
            }
        }
References System.Net.Mail.SmtpConnection.ConnectAndHandshakeAsyncResult.ConnectAndHandshakeAsyncResult(), System.Net.Mail.SmtpConnection.ConnectAndHandshakeAsyncResult._connection, System.IAsyncResult.AsyncState, System.IAsyncResult.CompletedSynchronously, System.Net.Mail.SmtpReplyReaderFactory.CurrentReader, System.Net.Mail.SmtpReplyReader.EndReadLine(), System.Net.LazyAsyncResult.InvokeCallback(), System.Net.Mail.LineInfo.Line, System.Net.Mail.SmtpConnection.Reader, System.Net.Mail.SmtpConnection.ConnectAndHandshakeAsyncResult.SendEHello(), System.Net.Mail.SmtpConnection.ConnectAndHandshakeAsyncResult.SendHello(), and System.Net.Mail.LineInfo.StatusCode.