Terraria: System.Net.Mail.SmtpConnection.ConnectAndHandshakeAsyncResult.ConnectAndHandshakeAsyncResult
ConnectAndHandshakeAsyncResult()
System.Net.Mail.SmtpConnection.ConnectAndHandshakeAsyncResult.ConnectAndHandshakeAsyncResult (SmtpConnection connection, string host, int port, System::Net::ContextAwareResult outerResult, AsyncCallback callback, object state) inline package
Definition at line 61 of file SmtpConnection.cs.
            : base(null, state, callback)
        {
            _connection = connection;
            _host = host;
            _port = port;
            _outerResult = outerResult;
        }
References System.Net.Mail.SmtpConnection.ConnectAndHandshakeAsyncResult._connection, System.Net.Mail.SmtpConnection.ConnectAndHandshakeAsyncResult._host, System.Net.Mail.SmtpConnection.ConnectAndHandshakeAsyncResult._outerResult, and System.Net.Mail.SmtpConnection.ConnectAndHandshakeAsyncResult._port.
Referenced by System.Net.Mail.SmtpConnection.ConnectAndHandshakeAsyncResult.AuthenticateCallback(), System.Net.Mail.SmtpConnection.ConnectAndHandshakeAsyncResult.AuthenticateContinueCallback(), System.Net.Mail.SmtpConnection.ConnectAndHandshakeAsyncResult.End(), System.Net.Mail.SmtpConnection.ConnectAndHandshakeAsyncResult.HandshakeCallback(), System.Net.Mail.SmtpConnection.ConnectAndHandshakeAsyncResult.InitializeConnectionCallback(), System.Net.Mail.SmtpConnection.ConnectAndHandshakeAsyncResult.SendEHelloCallback(), System.Net.Mail.SmtpConnection.ConnectAndHandshakeAsyncResult.SendHelloCallback(), System.Net.Mail.SmtpConnection.ConnectAndHandshakeAsyncResult.SendStartTlsCallback(), and System.Net.Mail.SmtpConnection.ConnectAndHandshakeAsyncResult.TlsStreamAuthenticateCallback().