Terraria: System.Net.Mail.SmtpConnection.ConnectAndHandshakeAsyncResult.TlsStreamAuthenticate
TlsStreamAuthenticate()
bool System.Net.Mail.SmtpConnection.ConnectAndHandshakeAsyncResult.TlsStreamAuthenticate () inline private
Definition at line 327 of file SmtpConnection.cs.
        {
            _connection._networkStream = new System.Net.TlsStream(_connection._networkStream, _connection._tcpClient.Client, _host, _connection._clientCertificates);
            IAsyncResult asyncResult = ((System.Net.TlsStream)_connection._networkStream).BeginAuthenticateAsClient(TlsStreamAuthenticateCallback, this);
            if (asyncResult.CompletedSynchronously)
            {
                ((System.Net.TlsStream)_connection._networkStream).EndAuthenticateAsClient(asyncResult);
                _connection._responseReader = new SmtpReplyReaderFactory(_connection._networkStream);
                SendEHello();
                return true;
            }
            return false;
        }
References System.Net.Mail.SmtpConnection._clientCertificates, System.Net.Mail.SmtpConnection.ConnectAndHandshakeAsyncResult._connection, System.Net.Mail.SmtpConnection.ConnectAndHandshakeAsyncResult._host, System.Net.Mail.SmtpConnection._networkStream, System.Net.Mail.SmtpConnection._tcpClient, System.asyncResult, System.Net.Sockets.TcpClient.Client, System.Net.Mail.SmtpConnection.ConnectAndHandshakeAsyncResult.SendEHello(), and System.Net.Mail.SmtpConnection.ConnectAndHandshakeAsyncResult.TlsStreamAuthenticateCallback().
Referenced by System.Net.Mail.SmtpConnection.ConnectAndHandshakeAsyncResult.SendStartTls(), and System.Net.Mail.SmtpConnection.ConnectAndHandshakeAsyncResult.SendStartTlsCallback().