Terraria: System.Net.Mail.SmtpConnection.ConnectAndHandshakeAsyncResult.AuthenticateContinue
AuthenticateContinue()
bool System.Net.Mail.SmtpConnection.ConnectAndHandshakeAsyncResult.AuthenticateContinue () inline private
Definition at line 439 of file SmtpConnection.cs.
        {
            while (true)
            {
                Authorization authorization = _connection._authenticationModules[_currentModule].Authenticate(_authResponse, null, _connection, _connection._client.TargetName, null);
                if (authorization == null)
                {
                    throw new SmtpException(System.SR.SmtpAuthenticationFailed);
                }
                IAsyncResult asyncResult = AuthCommand.BeginSend(_connection, authorization.Message, s_authenticateContinueCallback, this);
                if (!asyncResult.CompletedSynchronously)
                {
                    return false;
                }
                LineInfo lineInfo = AuthCommand.EndSend(asyncResult);
                if (lineInfo.StatusCode == (SmtpStatusCode)235)
                {
                    _connection._authenticationModules[_currentModule].CloseContext(_connection);
                    _connection._isConnected = true;
                    InvokeCallback();
                    return false;
                }
                if (lineInfo.StatusCode != (SmtpStatusCode)334)
                {
                    break;
                }
                _authResponse = lineInfo.Line;
            }
            return true;
        }
References System.Net.Mail.SmtpConnection._authenticationModules, System.Net.Mail.SmtpConnection.ConnectAndHandshakeAsyncResult._authResponse, System.Net.Mail.SmtpConnection._client, System.Net.Mail.SmtpConnection.ConnectAndHandshakeAsyncResult._connection, System.Net.Mail.SmtpConnection.ConnectAndHandshakeAsyncResult._currentModule, System.asyncResult, System.Net.Mail.ISmtpAuthenticationModule.Authenticate(), System.Net.Mail.AuthCommand.BeginSend(), System.Net.Mail.ISmtpAuthenticationModule.CloseContext(), System.Net.Mail.AuthCommand.EndSend(), System.Net.LazyAsyncResult.InvokeCallback(), System.Net.Mail.LineInfo.Line, System.Net.Authorization.Message, System.Net.Mail.SmtpConnection.ConnectAndHandshakeAsyncResult.s_authenticateContinueCallback, System.SR.SmtpAuthenticationFailed, System.Net.Mail.LineInfo.StatusCode, and System.Net.Mail.SmtpClient.TargetName.
Referenced by System.Net.Mail.SmtpConnection.ConnectAndHandshakeAsyncResult.Authenticate(), System.Net.Mail.SmtpConnection.ConnectAndHandshakeAsyncResult.AuthenticateCallback(), and System.Net.Mail.SmtpConnection.ConnectAndHandshakeAsyncResult.AuthenticateContinueCallback().