Terraria: System.Transactions.TransactionAbortedException.Create
Create() [2/4]
static new TransactionAbortedException System.Transactions.TransactionAbortedException.Create (string message, Exception innerException, Guid distributedTxId) inline static package
Definition at line 10 of file TransactionAbortedException.cs.
    {
        string text = message;
        if (TransactionException.IncludeDistributedTxId(distributedTxId))
        {
            text = System.SR.Format(System.SR.DistributedTxIDInTransactionException, text, distributedTxId);
        }
        return Create(text, innerException);
    }
References System.Transactions.TransactionAbortedException.Create(), System.Runtime.Serialization.Dictionary, System.SR.DistributedTxIDInTransactionException, System.SR.Format(), System.Transactions.TransactionException.IncludeDistributedTxId(), and System.text.
Referenced by System.Transactions.TransactionStatePromotedAborted.BeginCommit(), System.Transactions.TransactionStatePromotedNonMSDTCAborted.BeginCommit(), System.Transactions.TransactionAbortedException.Create(), System.Transactions.TransactionStatePromotedAborted.CreateAbortingClone(), System.Transactions.TransactionStatePromotedNonMSDTCAborted.CreateAbortingClone(), System.Transactions.TransactionStatePromotedAborted.CreateBlockingClone(), System.Transactions.TransactionStatePromotedNonMSDTCAborted.CreateBlockingClone(), System.Transactions.TransactionStateAborted.CreateTransactionAbortedException(), System.Transactions.TransactionStatePromotedAborted.PromotedTransactionOutcome(), and System.Transactions.TransactionStatePromotedNonMSDTCAborted.PromotedTransactionOutcome().