Terraria: System.Net.Mail.SmtpConnection.ConnectAndHandshakeAsyncResult.SendEHello
SendEHello()
bool System.Net.Mail.SmtpConnection.ConnectAndHandshakeAsyncResult.SendEHello () inline private
Definition at line 190 of file SmtpConnection.cs.
        {
            IAsyncResult asyncResult = EHelloCommand.BeginSend(_connection, _connection._client._clientDomain, s_sendEHelloCallback, this);
            if (asyncResult.CompletedSynchronously)
            {
                _connection._extensions = EHelloCommand.EndSend(asyncResult);
                _connection.ParseExtensions(_connection._extensions);
                if (_connection._networkStream is System.Net.TlsStream)
                {
                    Authenticate();
                    return true;
                }
                if (_connection.EnableSsl)
                {
                    if (!_connection._serverSupportsStartTls && !(_connection._networkStream is System.Net.TlsStream))
                    {
                        throw new SmtpException(System.SR.MailServerDoesNotSupportStartTls);
                    }
                    SendStartTls();
                }
                else
                {
                    Authenticate();
                }
                return true;
            }
            return false;
        }
References System.Net.Mail.SmtpConnection._client, System.Net.Mail.SmtpClient._clientDomain, System.Net.Mail.SmtpConnection.ConnectAndHandshakeAsyncResult._connection, System.Net.Mail.SmtpConnection._extensions, System.Net.Mail.SmtpConnection._networkStream, System.Net.Mail.SmtpConnection._serverSupportsStartTls, System.asyncResult, System.Net.Mail.SmtpConnection.ConnectAndHandshakeAsyncResult.Authenticate(), System.Net.Mail.EHelloCommand.BeginSend(), System.Net.Mail.SmtpConnection.EnableSsl, System.Net.Mail.EHelloCommand.EndSend(), System.SR.MailServerDoesNotSupportStartTls, System.Net.Mail.SmtpConnection.ParseExtensions(), System.Net.Mail.SmtpConnection.ConnectAndHandshakeAsyncResult.s_sendEHelloCallback, and System.Net.Mail.SmtpConnection.ConnectAndHandshakeAsyncResult.SendStartTls().
Referenced by System.Net.Mail.SmtpConnection.ConnectAndHandshakeAsyncResult.Handshake(), System.Net.Mail.SmtpConnection.ConnectAndHandshakeAsyncResult.HandshakeCallback(), System.Net.Mail.SmtpConnection.ConnectAndHandshakeAsyncResult.TlsStreamAuthenticate(), and System.Net.Mail.SmtpConnection.ConnectAndHandshakeAsyncResult.TlsStreamAuthenticateCallback().