Terraria: System.Security.Cryptography.HashAlgorithm.TryHashFinal
TryHashFinal()
virtual bool System.Security.Cryptography.HashAlgorithm.TryHashFinal (Span< byte > destination, out int bytesWritten) inline protected virtual inherited
Reimplemented in System.Security.Cryptography.HMACMD5, System.Security.Cryptography.HMACSHA1, System.Security.Cryptography.HMACSHA256, System.Security.Cryptography.HMACSHA384, System.Security.Cryptography.HMACSHA512, System.Security.Cryptography.MD5.Implementation, System.Security.Cryptography.SHA1.Implementation, System.Security.Cryptography.SHA1Managed, System.Security.Cryptography.SHA256.Implementation, System.Security.Cryptography.SHA256Managed, System.Security.Cryptography.SHA384.Implementation, System.Security.Cryptography.SHA384Managed, System.Security.Cryptography.SHA512.Implementation, System.Security.Cryptography.SHA512Managed, System.Security.Cryptography.MD5CryptoServiceProvider, System.Security.Cryptography.SHA1CryptoServiceProvider, System.Security.Cryptography.SHA256CryptoServiceProvider, System.Security.Cryptography.SHA384CryptoServiceProvider, System.Security.Cryptography.SHA512CryptoServiceProvider, and System.Security.Cryptography.HMAC.
Definition at line 269 of file HashAlgorithm.cs.
    {
        int num = HashSizeValue / 8;
        if (destination.Length >= num)
        {
            byte[] array = HashFinal();
            if (array.Length == num)
            {
                new ReadOnlySpan<byte>(array).CopyTo(destination);
                bytesWritten = array.Length;
                return true;
            }
            throw new InvalidOperationException(System.SR.InvalidOperation_IncorrectImplementation);
        }
        bytesWritten = 0;
        return false;
    }
References System.array, System.ReadOnlySpan< T >.CopyTo(), System.destination, System.Security.Cryptography.HashAlgorithm.HashFinal(), System.Security.Cryptography.HashAlgorithm.HashSizeValue, and System.SR.InvalidOperation_IncorrectImplementation.
Referenced by System.Security.Cryptography.HashAlgorithm.TryComputeHash().