Terraria: System.Net.Mail.SmtpConnection.ConnectAndHandshakeAsyncResult.Authenticate
Authenticate()
void System.Net.Mail.SmtpConnection.ConnectAndHandshakeAsyncResult.Authenticate () inline private
Definition at line 359 of file SmtpConnection.cs.
        {
            if (_connection._credentials != null)
            {
                while (++_currentModule < _connection._authenticationModules.Length)
                {
                    ISmtpAuthenticationModule smtpAuthenticationModule = _connection._authenticationModules[_currentModule];
                    if (!_connection.AuthSupported(smtpAuthenticationModule))
                    {
                        continue;
                    }
                    NetworkCredential credential = _connection._credentials.GetCredential(_host, _port, smtpAuthenticationModule.AuthenticationType);
                    if (credential == null)
                    {
                        continue;
                    }
                    Authorization authorization = _connection.SetContextAndTryAuthenticate(smtpAuthenticationModule, credential, _outerResult);
                    if (authorization == null || authorization.Message == null)
                    {
                        continue;
                    }
                    IAsyncResult asyncResult = AuthCommand.BeginSend(_connection, _connection._authenticationModules[_currentModule].AuthenticationType, authorization.Message, s_authenticateCallback, this);
                    if (!asyncResult.CompletedSynchronously)
                    {
                        return;
                    }
                    LineInfo lineInfo = AuthCommand.EndSend(asyncResult);
                    if (lineInfo.StatusCode == (SmtpStatusCode)334)
                    {
                        _authResponse = lineInfo.Line;
                        if (!AuthenticateContinue())
{
                            return;
                        }
                    }
                    else if (lineInfo.StatusCode == (SmtpStatusCode)235)
                    {
                        smtpAuthenticationModule.CloseContext(_connection);
                        _connection._isConnected = true;
                        break;
                    }
                }
            }
            _connection._isConnected = true;
            InvokeCallback();
        }
References System.Net.Mail.SmtpConnection._authenticationModules, System.Net.Mail.SmtpConnection.ConnectAndHandshakeAsyncResult._authResponse, System.Net.Mail.SmtpConnection.ConnectAndHandshakeAsyncResult._connection, System.Net.Mail.SmtpConnection._credentials, System.Net.Mail.SmtpConnection.ConnectAndHandshakeAsyncResult._currentModule, System.Net.Mail.SmtpConnection.ConnectAndHandshakeAsyncResult._host, System.Net.Mail.SmtpConnection.ConnectAndHandshakeAsyncResult._outerResult, System.Net.Mail.SmtpConnection.ConnectAndHandshakeAsyncResult._port, System.asyncResult, System.Net.Mail.SmtpConnection.ConnectAndHandshakeAsyncResult.AuthenticateContinue(), System.Net.Mail.ISmtpAuthenticationModule.AuthenticationType, System.Net.Mail.SmtpConnection.AuthSupported(), System.Net.Mail.AuthCommand.BeginSend(), System.Net.Mail.ISmtpAuthenticationModule.CloseContext(), System.Net.Mail.AuthCommand.EndSend(), System.Net.ICredentialsByHost.GetCredential(), System.Net.LazyAsyncResult.InvokeCallback(), System.Net.Mail.LineInfo.Line, System.Net.Authorization.Message, System.Net.Mail.SmtpConnection.ConnectAndHandshakeAsyncResult.s_authenticateCallback, System.Net.Mail.SmtpConnection.SetContextAndTryAuthenticate(), and System.Net.Mail.LineInfo.StatusCode.
Referenced by System.Net.Mail.SmtpConnection.ConnectAndHandshakeAsyncResult.AuthenticateCallback(), System.Net.Mail.SmtpConnection.ConnectAndHandshakeAsyncResult.AuthenticateContinueCallback(), System.Net.Mail.SmtpConnection.ConnectAndHandshakeAsyncResult.SendEHello(), System.Net.Mail.SmtpConnection.ConnectAndHandshakeAsyncResult.SendEHelloCallback(), System.Net.Mail.SmtpConnection.ConnectAndHandshakeAsyncResult.SendHello(), and System.Net.Mail.SmtpConnection.ConnectAndHandshakeAsyncResult.SendHelloCallback().