Terraria: System.Security.Cryptography.HashAlgorithm.ComputeHashAsyncCore
ComputeHashAsyncCore()
async Task< byte[]> System.Security.Cryptography.HashAlgorithm.ComputeHashAsyncCore (Stream inputStream, CancellationToken cancellationToken) inline private inherited
Definition at line 153 of file HashAlgorithm.cs.
    {
        byte[] rented = ArrayPool<byte>.Shared.Rent(4096);
        Memory<byte> buffer = rented;
        int clearLimit = 0;
        int num;
        while ((num = await inputStream.ReadAsync(buffer, cancellationToken).ConfigureAwait(continueOnCapturedContext: false)) > 0)
        {
            if (num > clearLimit)
            {
                clearLimit = num;
            }
            HashCore(rented, 0, num);
        }
        CryptographicOperations.ZeroMemory(rented.AsSpan(0, clearLimit));
        ArrayPool<byte>.Shared.Return(rented);
        return CaptureHashCodeAndReinitialize();
    }
References System.buffer, System.cancellationToken, System.Security.Cryptography.HashAlgorithm.CaptureHashCodeAndReinitialize(), System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.Security.Cryptography.HashAlgorithm.HashCore(), System.IO.Stream.ReadAsync(), System.Buffers.ArrayPool< T >.Shared, and System.Security.Cryptography.CryptographicOperations.ZeroMemory().
Referenced by System.Security.Cryptography.HashAlgorithm.ComputeHashAsync().