Terraria: System.Security.Cryptography.HashAlgorithm.TransformBlock
TransformBlock() [2/2]
int System.Security.Cryptography.HashAlgorithm.TransformBlock (byte[] inputBuffer, int inputOffset, int inputCount, byte?[] outputBuffer, int outputOffset) inline inherited
Definition at line 199 of file HashAlgorithm.cs.
    {
        ValidateTransformBlock(inputBuffer, inputOffset, inputCount);
        State = 1;
        HashCore(inputBuffer, inputOffset, inputCount);
        if (outputBuffer != null && (inputBuffer != outputBuffer || inputOffset != outputOffset))
        {
            Buffer.BlockCopy(inputBuffer, inputOffset, outputBuffer, outputOffset, inputCount);
        }
        return inputCount;
    }
References System.Buffer.BlockCopy(), System.Security.Cryptography.HashAlgorithm.HashCore(), and System.Security.Cryptography.HashAlgorithm.ValidateTransformBlock().
Referenced by System.Security.Cryptography.PasswordDeriveBytes.ComputeBaseValue().