Terraria: System.Text.TranscodingStream.WriteAsync
WriteAsync() [3/3]
override ValueTask System.Text.TranscodingStream.WriteAsync (ReadOnlyMemory< byte > buffer, CancellationToken cancellationToken) inline virtual
Reimplemented from System.IO.Stream.
Definition at line 388 of file TranscodingStream.cs.
    {
        EnsurePreWriteConditions();
        if (cancellationToken.IsCancellationRequested)
        {
            return ValueTask.FromCanceled(cancellationToken);
        }
        if (buffer.IsEmpty)
        {
            return ValueTask.CompletedTask;
        }
        return WriteAsyncCore(buffer, cancellationToken);
        async ValueTask WriteAsyncCore(ReadOnlyMemory<byte> remainingOuterEncodedBytes, CancellationToken cancellationToken)
        {
            int minimumLength = Math.Clamp(remainingOuterEncodedBytes.Length, 4096, 1048576);
            char[] scratchChars = ArrayPool<char>.Shared.Rent(minimumLength);
            byte[] scratchBytes = ArrayPool<byte>.Shared.Rent(minimumLength);
            try
            {
                bool decoderFinished;
                do
                {
                    _thisDecoder.Convert(remainingOuterEncodedBytes.Span, scratchChars, flush: false, out var bytesUsed, out var charsUsed, out decoderFinished);
                    remainingOuterEncodedBytes = remainingOuterEncodedBytes.Slice(bytesUsed);
                    ArraySegment<char> decodedChars = new ArraySegment<char>(scratchChars, 0, charsUsed);
                    bool encoderFinished;
                    do
                    {
                        _innerEncoder.Convert(decodedChars, scratchBytes, flush: false, out var charsUsed2, out var bytesUsed2, out encoderFinished);
                        decodedChars = decodedChars.Slice(charsUsed2);
                        await _innerStream.WriteAsync(new ReadOnlyMemory<byte>(scratchBytes, 0, bytesUsed2), cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
                    }
                    while (!encoderFinished);
                }
                while (!decoderFinished);
            }
            finally
            {
                ArrayPool<char>.Shared.Return(scratchChars);
                ArrayPool<byte>.Shared.Return(scratchBytes);
            }
        }
    }
References System.Text.TranscodingStream._innerEncoder, System.Text.TranscodingStream._innerStream, System.Text.TranscodingStream._thisDecoder, System.buffer, System.cancellationToken, System.Math.Clamp(), System.Threading.Tasks.ValueTask< TResult >.CompletedTask, System.Text.Decoder.Convert(), System.Text.Encoder.Convert(), System.Text.TranscodingStream.EnsurePreWriteConditions(), System.Threading.Tasks.ValueTask< TResult >.FromCanceled(), System.ReadOnlyMemory< T >.Length, System.Buffers.ArrayPool< T >.Shared, System.ArraySegment< T >.Slice(), System.ReadOnlyMemory< T >.Slice(), System.ReadOnlyMemory< T >.Span, and System.IO.Stream.WriteAsync().