Terraria: System.Text.TranscodingStream.FinalFlushWriteBuffers
FinalFlushWriteBuffers()
ArraySegment< byte > System.Text.TranscodingStream.FinalFlushWriteBuffers () inline private
Definition at line 179 of file TranscodingStream.cs.
    {
        if (_thisDecoder == null || _innerEncoder == null)
        {
            return default(ArraySegment<byte>);
        }
        char[] chars = Array.Empty<char>();
        int num = _thisDecoder.GetCharCount(Array.Empty<byte>(), 0, 0, flush: true);
        if (num > 0)
        {
            chars = new char[num];
            num = _thisDecoder.GetChars(Array.Empty<byte>(), 0, 0, chars, 0, flush: true);
        }
        byte[] array = Array.Empty<byte>();
        int num2 = _innerEncoder.GetByteCount(chars, 0, num, flush: true);
        if (num2 > 0)
        {
            array = new byte[num2];
            num2 = _innerEncoder.GetBytes(chars, 0, num, array, 0, flush: true);
        }
        return new ArraySegment<byte>(array, 0, num2);
    }
References System.Text.TranscodingStream._innerEncoder, System.Text.TranscodingStream._thisDecoder, System.array, System.chars, System.Text.Encoder.GetByteCount(), System.Text.Encoder.GetBytes(), System.Text.Decoder.GetCharCount(), and System.Text.Decoder.GetChars().
Referenced by System.Text.TranscodingStream.Dispose(), and System.Text.TranscodingStream.DisposeAsync().