Terraria: System.Text.TranscodingStream.Read
Read() [2/2]
override int System.Text.TranscodingStream.Read (Span< byte > buffer) inline virtual
Reimplemented from System.IO.Stream.
Definition at line 220 of file TranscodingStream.cs.
    {
        EnsurePreReadConditions();
        if (_readBufferCount == 0)
        {
            byte[] array = ArrayPool<byte>.Shared.Rent(4096);
            char[] array2 = ArrayPool<char>.Shared.Rent(_readCharBufferMaxSize);
            try
            {
                bool flag;
                int bytes;
                do
                {
                    int num = _innerStream.Read(array, 0, 4096);
                    flag = num == 0;
                    int chars = _innerDecoder.GetChars(array, 0, num, array2, 0, flag);
                    bytes = _thisEncoder.GetBytes(array2, 0, chars, _readBuffer, 0, flag);
                }
                while (!flag && bytes == 0);
                _readBufferOffset = 0;
                _readBufferCount = bytes;
            }
            finally
            {
                ArrayPool<byte>.Shared.Return(array);
                ArrayPool<char>.Shared.Return(array2);
            }
        }
        int num2 = Math.Min(_readBufferCount, buffer.Length);
        _readBuffer.AsSpan(_readBufferOffset, num2).CopyTo(buffer);
        _readBufferOffset += num2;
        _readBufferCount -= num2;
        return num2;
    }
References System.Text.TranscodingStream._innerDecoder, System.Text.TranscodingStream._innerStream, System.Text.TranscodingStream._readBuffer, System.Text.TranscodingStream._readBufferCount, System.Text.TranscodingStream._readBufferOffset, System.Text.TranscodingStream._readCharBufferMaxSize, System.Text.TranscodingStream._thisEncoder, System.array, System.buffer, System.bytes, System.chars, System.Text.TranscodingStream.EnsurePreReadConditions(), System.Text.Encoder.GetBytes(), System.Text.Decoder.GetChars(), System.Math.Min(), System.IO.Stream.Read(), and System.Buffers.ArrayPool< T >.Shared.