Terraria: System.Text.TranscodingStream.Write
Write() [2/2]
override void System.Text.TranscodingStream.Write (ReadOnlySpan< byte > buffer) inline virtual
Reimplemented from System.IO.Stream.
Definition at line 346 of file TranscodingStream.cs.
    {
        EnsurePreWriteConditions();
        if (buffer.IsEmpty)
        {
            return;
        }
        int minimumLength = Math.Clamp(buffer.Length, 4096, 1048576);
        char[] array = ArrayPool<char>.Shared.Rent(minimumLength);
        byte[] array2 = ArrayPool<byte>.Shared.Rent(minimumLength);
        try
        {
            bool completed;
            do
            {
                _thisDecoder.Convert(buffer, array, flush: false, out var bytesUsed, out var charsUsed, out completed);
                buffer = buffer.Slice(bytesUsed);
                Span<char> span = array.AsSpan(0, charsUsed);
                bool completed2;
                do
                {
                    _innerEncoder.Convert(span, array2, flush: false, out var charsUsed2, out var bytesUsed2, out completed2);
                    span = span.Slice(charsUsed2);
                    _innerStream.Write(array2, 0, bytesUsed2);
                }
                while (!completed2);
            }
            while (!completed);
        }
        finally
        {
            ArrayPool<char>.Shared.Return(array);
            ArrayPool<byte>.Shared.Return(array2);
        }
    }
References System.Text.TranscodingStream._innerEncoder, System.Text.TranscodingStream._innerStream, System.Text.TranscodingStream._thisDecoder, System.array, System.buffer, System.Math.Clamp(), System.Text.Decoder.Convert(), System.Text.Encoder.Convert(), System.Text.TranscodingStream.EnsurePreWriteConditions(), System.Buffers.ArrayPool< T >.Shared, System.Span< T >.Slice(), and System.IO.Stream.Write().