Terraria: System.Text.TranscodingStream.DisposeAsync
DisposeAsync()
override ValueTask System.Text.TranscodingStream.DisposeAsync () inline virtual
Reimplemented from System.IO.Stream.
Definition at line 99 of file TranscodingStream.cs.
    {
        if (_innerStream == null)
        {
            return default(ValueTask);
        }
        ArraySegment<byte> pendingData2 = FinalFlushWriteBuffers();
        if (pendingData2.Count == 0)
        {
            Stream innerStream = _innerStream;
            _innerStream = null;
            if (!_leaveOpen)
            {
                return innerStream.DisposeAsync();
            }
            return default(ValueTask);
        }
        return DisposeAsyncCore(pendingData2);
        async ValueTask DisposeAsyncCore(ArraySegment<byte> pendingData)
        {
            Stream innerStream2 = _innerStream;
            _innerStream = null;
            await innerStream2.WriteAsync(pendingData.AsMemory()).ConfigureAwait(continueOnCapturedContext: false);
            if (!_leaveOpen)
            {
                await innerStream2.DisposeAsync().ConfigureAwait(continueOnCapturedContext: false);
            }
        }
    }
References System.Text.TranscodingStream._innerStream, System.Text.TranscodingStream._leaveOpen, System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.Threading.Tasks.ValueTask< TResult >.ConfigureAwait(), System.ArraySegment< T >.Count, System.IO.Stream.DisposeAsync(), System.Text.TranscodingStream.FinalFlushWriteBuffers(), and System.IO.Stream.WriteAsync().