Terraria: System.Text.TranscodingStream.ThrowIfDisposed
ThrowIfDisposed()
void System.Text.TranscodingStream.ThrowIfDisposed () inline private
Definition at line 325 of file TranscodingStream.cs.
    {
        if (_innerStream == null)
        {
            ThrowObjectDisposedException();
        }
    }
References System.Text.TranscodingStream._innerStream, and System.Text.TranscodingStream.ThrowObjectDisposedException().
Referenced by System.Text.TranscodingStream.EnsurePreReadConditions(), System.Text.TranscodingStream.EnsurePreWriteConditions(), System.Text.TranscodingStream.Flush(), and System.Text.TranscodingStream.FlushAsync().