Terraria: System.Text.TranscodingStream.EnsurePreWriteConditions
EnsurePreWriteConditions()
void System.Text.TranscodingStream.EnsurePreWriteConditions () inline private
Definition at line 161 of file TranscodingStream.cs.
    {
        ThrowIfDisposed();
        if (_innerEncoder == null)
        {
            InitializeReadDataStructures();
        }
        void InitializeReadDataStructures()
        {
            if (!CanWrite)
            {
                ThrowHelper.ThrowNotSupportedException_UnwritableStream();
            }
            _innerEncoder = _innerEncoding.GetEncoder();
            _thisDecoder = _thisEncoding.GetDecoder();
        }
    }
References System.Text.TranscodingStream._innerEncoder, System.Text.TranscodingStream._innerEncoding, System.Text.TranscodingStream._thisDecoder, System.Text.TranscodingStream._thisEncoding, System.Text.TranscodingStream.CanWrite, System.Text.Encoding.GetDecoder(), System.Text.Encoding.GetEncoder(), System.Text.TranscodingStream.ThrowIfDisposed(), and System.ThrowHelper.ThrowNotSupportedException_UnwritableStream().
Referenced by System.Text.TranscodingStream.Write(), and System.Text.TranscodingStream.WriteAsync().