Terraria: System.Text.TranscodingStream.ReadAsync
ReadAsync() [3/3]
override ValueTask< int > System.Text.TranscodingStream.ReadAsync (Memory< byte > buffer, CancellationToken cancellationToken) inline virtual
Reimplemented from System.IO.Stream.
Definition at line 261 of file TranscodingStream.cs.
    {
        EnsurePreReadConditions();
        if (cancellationToken.IsCancellationRequested)
        {
            return ValueTask.FromCanceled<int>(cancellationToken);
        }
        return ReadAsyncCore(buffer, cancellationToken);
        async ValueTask<int> ReadAsyncCore(Memory<byte> buffer, CancellationToken cancellationToken)
        {
            if (_readBufferCount == 0)
            {
                byte[] rentedBytes = ArrayPool<byte>.Shared.Rent(4096);
                char[] rentedChars = ArrayPool<char>.Shared.Rent(_readCharBufferMaxSize);
                try
                {
                    bool flag;
                    int bytes;
                    do
                    {
                        int num = await _innerStream.ReadAsync(rentedBytes.AsMemory(0, 4096), cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
                        flag = num == 0;
                        int chars = _innerDecoder.GetChars(rentedBytes, 0, num, rentedChars, 0, flag);
                        bytes = _thisEncoder.GetBytes(rentedChars, 0, chars, _readBuffer, 0, flag);
                    }
                    while (!flag && bytes == 0);
                    _readBufferOffset = 0;
                    _readBufferCount = bytes;
                }
                finally
                {
                    ArrayPool<byte>.Shared.Return(rentedBytes);
                    ArrayPool<char>.Shared.Return(rentedChars);
                }
            }
            int num2 = Math.Min(_readBufferCount, buffer.Length);
            _readBuffer.AsSpan(_readBufferOffset, num2).CopyTo(buffer.Span);
            _readBufferOffset += num2;
            _readBufferCount -= num2;
            return num2;
        }
    }
References System.Text.TranscodingStream._innerDecoder, System.Text.TranscodingStream._innerStream, System.Text.TranscodingStream._readBuffer, System.Text.TranscodingStream._readBufferCount, System.Text.TranscodingStream._readBufferOffset, System.Text.TranscodingStream._readCharBufferMaxSize, System.Text.TranscodingStream._thisEncoder, System.buffer, System.bytes, System.cancellationToken, System.chars, System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.Text.TranscodingStream.EnsurePreReadConditions(), System.Threading.Tasks.ValueTask< TResult >.FromCanceled(), System.Text.Encoder.GetBytes(), System.Text.Decoder.GetChars(), System.Math.Min(), System.IO.Stream.ReadAsync(), and System.Buffers.ArrayPool< T >.Shared.