Terraria: System.Text.TranscodingStream.EnsurePreReadConditions
EnsurePreReadConditions()
void System.Text.TranscodingStream.EnsurePreReadConditions () inline private
Definition at line 140 of file TranscodingStream.cs.
    {
        ThrowIfDisposed();
        if (_innerDecoder == null)
        {
            InitializeReadDataStructures();
        }
        void InitializeReadDataStructures()
        {
            if (!CanRead)
            {
                ThrowHelper.ThrowNotSupportedException_UnreadableStream();
            }
            _innerDecoder = _innerEncoding.GetDecoder();
            _thisEncoder = _thisEncoding.GetEncoder();
            _readCharBufferMaxSize = _innerEncoding.GetMaxCharCount(4096);
            _readBuffer = GC.AllocateUninitializedArray<byte>(_thisEncoding.GetMaxByteCount(_readCharBufferMaxSize));
        }
    }
References System.Text.TranscodingStream._innerDecoder, System.Text.TranscodingStream._innerEncoding, System.Text.TranscodingStream._readBuffer, System.Text.TranscodingStream._readCharBufferMaxSize, System.Text.TranscodingStream._thisEncoder, System.Text.TranscodingStream._thisEncoding, System.Text.TranscodingStream.CanRead, System.Text.Encoding.GetDecoder(), System.Text.Encoding.GetEncoder(), System.Text.Encoding.GetMaxByteCount(), System.Text.Encoding.GetMaxCharCount(), System.Text.TranscodingStream.ThrowIfDisposed(), and System.ThrowHelper.ThrowNotSupportedException_UnreadableStream().
Referenced by System.Text.TranscodingStream.Read(), and System.Text.TranscodingStream.ReadAsync().