Terraria: System.Threading.Tasks.Task.DelayPromise.DelayPromise
DelayPromise()
System.Threading.Tasks.Task< TResult >.DelayPromise.DelayPromise (uint millisecondsDelay) inline package
Definition at line 594 of file Task.cs.
        {
            if (TplEventSource.Log.IsEnabled())
            {
                TplEventSource.Log.TraceOperationBegin(base.Id, "Task.Delay", 0L);
            }
            if (s_asyncDebuggingEnabled)
            {
                AddToActiveTasks(this);
            }
            if (millisecondsDelay != uint.MaxValue)
            {
                _timer = new TimerQueueTimer(s_timerCallback, this, millisecondsDelay, uint.MaxValue, flowExecutionContext: false);
                if (base.IsCompleted)
                {
                    _timer.Close();
                }
            }
        }
References System.Threading.Tasks.Task< TResult >.DelayPromise._timer, System.Threading.Tasks.Task< TResult >.AddToActiveTasks(), System.Threading.TimerQueueTimer.Close(), System.L, System.Threading.Tasks.TplEventSource.Log, System.millisecondsDelay, System.Threading.Tasks.Task< TResult >.s_asyncDebuggingEnabled, and System.Threading.Tasks.Task< TResult >.DelayPromise.s_timerCallback.
Referenced by System.Threading.Tasks.Task< TResult >.DelayPromise.TimerCallback().