Terraria: System.Data.DataReaderExtensions.AssertNotNull
AssertNotNull()
static void System.Data.DataReaderExtensions.AssertNotNull ([NotNull] DbDataReader reader) inline static private
Definition at line 171 of file DataReaderExtensions.cs.
    {
        if (reader == null)
        {
            throw new ArgumentNullException("reader");
        }
    }
Referenced by System.Data.DataReaderExtensions.GetBoolean(), System.Data.DataReaderExtensions.GetByte(), System.Data.DataReaderExtensions.GetBytes(), System.Data.DataReaderExtensions.GetChar(), System.Data.DataReaderExtensions.GetChars(), System.Data.DataReaderExtensions.GetData(), System.Data.DataReaderExtensions.GetDataTypeName(), System.Data.DataReaderExtensions.GetDateTime(), System.Data.DataReaderExtensions.GetDecimal(), System.Data.DataReaderExtensions.GetDouble(), System.Data.DataReaderExtensions.GetFieldType(), System.Data.DataReaderExtensions.GetFieldValue< T >(), System.Data.DataReaderExtensions.GetFieldValueAsync< T >(), System.Data.DataReaderExtensions.GetFloat(), System.Data.DataReaderExtensions.GetGuid(), System.Data.DataReaderExtensions.GetInt16(), System.Data.DataReaderExtensions.GetInt32(), System.Data.DataReaderExtensions.GetInt64(), System.Data.DataReaderExtensions.GetProviderSpecificFieldType(), System.Data.DataReaderExtensions.GetProviderSpecificValue(), System.Data.DataReaderExtensions.GetStream(), System.Data.DataReaderExtensions.GetString(), System.Data.DataReaderExtensions.GetTextReader(), System.Data.DataReaderExtensions.GetValue(), System.Data.DataReaderExtensions.IsDBNull(), and System.Data.DataReaderExtensions.IsDBNullAsync().