Terraria: System.Data.DataReaderExtensions.IsDBNullAsync
IsDBNullAsync()
static Task< bool > System.Data.DataReaderExtensions.IsDBNullAsync (this DbDataReader reader, string name, CancellationToken cancellationToken = default(CancellationToken)) inline static
Definition at line 165 of file DataReaderExtensions.cs.
    {
        AssertNotNull(reader);
        return reader.IsDBNullAsync(reader.GetOrdinal(name), cancellationToken);
    }
References System.Data.DataReaderExtensions.AssertNotNull(), System.cancellationToken, System.Data.Common.DbDataReader.GetOrdinal(), and System.Data.Common.DbDataReader.IsDBNullAsync().