Terraria: FastRandom.NextFloat
NextFloat()
float FastRandom.NextFloat () inline
     {
         return (float)NextBits(24) * 5.9604645E-08f;
     }
References NextBits().
Referenced by AmbientSky.AirBalloonSkyEntity.AirBalloonSkyEntity(), AmbientSky.AirshipSkyEntity.AirshipSkyEntity(), AmbientSky.BatsGroupSkyEntity.BatsGroupSkyEntity(), AmbientSky.BirdsPackSkyEntity.BirdsPackSkyEntity(), AmbientSky.ButterfliesSkyEntity.ButterfliesSkyEntity(), AmbientSky.EOCSkyEntity.EOCSkyEntity(), AmbientSky.GastropodGroupSkyEntity.GastropodGroupSkyEntity(), AmbientSky.HellBatsGoupSkyEntity.HellBatsGoupSkyEntity(), AmbientSky.LostKiteSkyEntity.LostKiteSkyEntity(), AmbientSky.MeteorSkyEntity.MeteorSkyEntity(), AmbientSky.PegasusSkyEntity.PegasusSkyEntity(), AmbientSky.PixiePosseSkyEntity.PixiePosseSkyEntity(), AmbientSky.SeagullsGroupSkyEntity.SeagullsGroupSkyEntity(), AmbientSky.SlimeBalloonGroupSkyEntity.SlimeBalloonGroupSkyEntity(), AmbientSky.VultureSkyEntity.VultureSkyEntity(), AmbientSky.WyvernSkyEntity.WyvernSkyEntity(), AmbientSky.SeagullsGroupSkyEntity.CreateGroup(), AmbientSky.GastropodGroupSkyEntity.CreateGroup(), AmbientSky.SlimeBalloonGroupSkyEntity.CreateGroup(), AmbientSky.HellBatsGoupSkyEntity.CreateGroup(), and AmbientSky.BatsGroupSkyEntity.CreateGroup().