Terraria: System.Nullable.GetUnderlyingType
GetUnderlyingType()
static ? Type System.Nullable< T >.GetUnderlyingType (Type nullableType) inline static
Definition at line 139 of file Nullable.cs.
    {
        if ((object)nullableType == null)
        {
            throw new ArgumentNullException("nullableType");
        }
        if (nullableType.IsGenericType && !nullableType.IsGenericTypeDefinition)
        {
            Type genericTypeDefinition = nullableType.GetGenericTypeDefinition();
            if ((object)genericTypeDefinition == typeof(Nullable<>))
            {
                return nullableType.GetGenericArguments()[0];
            }
        }
        return null;
    }
Referenced by System.ComponentModel.NullableConverter.NullableConverter(), System.Dynamic.DynamicObject.MetaDynamic.BuildCallMethodWithResult< TBinder >(), System.Text.Json.JsonSerializerOptions.GetConverterFromAttribute(), System.Reflection.NullabilityInfoContext.GetNullabilityInfo(), System.Runtime.Serialization.ObjectManager.GetNullableValueField(), System.Text.Json.Serialization.Metadata.JsonPropertyInfo< T >.NumberHandingIsApplicable(), System.Runtime.Serialization.ReflectionClassWriter.ReflectionWriteValue(), System.Reflection.Emit.TypeBuilder.SetConstantValue(), System.Runtime.Serialization.Formatters.Binary.ObjectWriter.WriteArray(), System.Runtime.Serialization.Formatters.Binary.ObjectWriter.WriteArrayMember(), System.Text.Json.Serialization.JsonConverter< T >.WriteCoreAsObject(), System.Runtime.Serialization.Formatters.Binary.ObjectWriter.WriteMembers(), and System.Xml.Serialization.ReflectionAwareCodeGen.WriteTypeInfo().