Terraria: System.Runtime.Serialization.ReflectionClassWriter.ResolveAdapterType
ResolveAdapterType()
object System.Runtime.Serialization.ReflectionClassWriter.ResolveAdapterType (object obj, ClassDataContract classContract) inline private inherited
Definition at line 126 of file ReflectionClassWriter.cs.
    {
        Type type = obj.GetType();
        if (type == Globals.TypeOfDateTimeOffset)
        {
            obj = DateTimeOffsetAdapter.GetDateTimeOffsetAdapter((DateTimeOffset)obj);
        }
        else if (type == Globals.TypeOfMemoryStream)
        {
            obj = MemoryStreamAdapter.GetMemoryStreamAdapter((MemoryStream)obj);
        }
        else if (type.IsGenericType && type.GetGenericTypeDefinition() == Globals.TypeOfKeyValuePair)
        {
            obj = classContract.KeyValuePairAdapterConstructorInfo.Invoke(new object[1] { obj });
        }
        return obj;
    }
References System.Runtime.Serialization.Dictionary, System.Runtime.Serialization.DateTimeOffsetAdapter.GetDateTimeOffsetAdapter(), System.Runtime.Serialization.MemoryStreamAdapter.GetMemoryStreamAdapter(), System.Type.GetType(), System.obj, System.type, System.Runtime.Serialization.Globals.TypeOfDateTimeOffset, System.Runtime.Serialization.Globals.TypeOfKeyValuePair, and System.Runtime.Serialization.Globals.TypeOfMemoryStream.
Referenced by System.Runtime.Serialization.ReflectionClassWriter.ReflectionWriteClass().