Terraria: System.Runtime.Serialization.ReflectionClassWriter.ReflectionWriteValue
ReflectionWriteValue()
void System.Runtime.Serialization.ReflectionClassWriter.ReflectionWriteValue (XmlWriterDelegator xmlWriter, XmlObjectSerializerWriteContext context, Type type, object value, bool writeXsiType, PrimitiveDataContract primitiveContractForParamType) inline inherited
Definition at line 31 of file ReflectionClassWriter.cs.
    {
        Type type2 = type;
        object obj = value;
        bool flag = type2.IsGenericType && type2.GetGenericTypeDefinition() == Globals.TypeOfNullable;
        if (type2.IsValueType && !flag)
        {
            if (primitiveContractForParamType != null && !writeXsiType)
            {
                primitiveContractForParamType.WriteXmlValue(xmlWriter, obj, context);
            }
            else
            {
                ReflectionInternalSerialize(xmlWriter, context, obj, obj.GetType().TypeHandle.Equals(type2.TypeHandle), writeXsiType, type2);
            }
            return;
        }
        if (flag)
        {
            if (obj == null)
            {
                type2 = Nullable.GetUnderlyingType(type2);
            }
            else
            {
                MethodInfo method = type2.GetMethod("get_Value", Type.EmptyTypes);
                obj = method.Invoke(obj, Array.Empty<object>());
                type2 = obj.GetType();
            }
        }
        if (obj == null)
        {
            context.WriteNull(xmlWriter, type2, DataContract.IsTypeSerializable(type2));
            return;
        }
        PrimitiveDataContract primitiveDataContract = (flag ? PrimitiveDataContract.GetPrimitiveDataContract(type2) : primitiveContractForParamType);
        if (primitiveDataContract != null && primitiveDataContract.UnderlyingType != Globals.TypeOfObject && !writeXsiType)
        {
            primitiveDataContract.WriteXmlValue(xmlWriter, obj, context);
        }
        else if (obj == null && (type2 == Globals.TypeOfObject || (flag && type2.IsValueType)))
        {
            context.WriteNull(xmlWriter, type2, DataContract.IsTypeSerializable(type2));
        }
        else
        {
            ReflectionInternalSerialize(xmlWriter, context, obj, obj.GetType().TypeHandle.Equals(type2.TypeHandle), writeXsiType, type2, flag);
        }
    }
References System.Runtime.Serialization.Dictionary, System.Type.EmptyTypes, System.Type.GetGenericTypeDefinition(), System.Runtime.Serialization.PrimitiveDataContract.GetPrimitiveDataContract(), System.Nullable< T >.GetUnderlyingType(), System.Reflection.MethodBase.Invoke(), System.Runtime.Serialization.DataContract.IsTypeSerializable(), System.obj, System.Runtime.Serialization.ReflectionClassWriter.ReflectionInternalSerialize(), System.type, System.Runtime.Serialization.Globals.TypeOfNullable, System.Runtime.Serialization.Globals.TypeOfObject, System.value, System.Runtime.Serialization.XmlObjectSerializerWriteContext.WriteNull(), and System.Runtime.Serialization.PrimitiveDataContract.WriteXmlValue().
Referenced by System.Runtime.Serialization.Json.ReflectionJsonFormatWriter.ReflectionWriteCollection(), and System.Runtime.Serialization.Json.ReflectionJsonClassWriter.ReflectionWriteMembers().