Terraria: ShopHelper.HateBiome
HateBiome()
void ShopHelper.HateBiome (string nameKey) inline
     {
         AddHappinessReportText("HateBiome", new
         {
             BiomeName = BiomeNameByKey(nameKey)
         });
         _currentPriceAdjustment *= 1.12f;
     }
References _currentPriceAdjustment, AddHappinessReportText(), and BiomeNameByKey().
Referenced by BiomePreferenceListTrait.ApplyPreference().