Terraria: System.Runtime.Serialization.ReflectionClassWriter.ReflectionInternalSerialize
ReflectionInternalSerialize()
void System.Runtime.Serialization.ReflectionClassWriter.ReflectionInternalSerialize (XmlWriterDelegator xmlWriter, XmlObjectSerializerWriteContext context, object obj, bool isDeclaredType, bool writeXsiType, Type memberType, bool isNullableOfT = false) inline private inherited
Definition at line 145 of file ReflectionClassWriter.cs.
    {
        if (isNullableOfT)
        {
            context.InternalSerialize(xmlWriter, obj, isDeclaredType, writeXsiType, DataContract.GetId(memberType.TypeHandle), memberType.TypeHandle);
        }
        else
        {
            context.InternalSerializeReference(xmlWriter, obj, isDeclaredType, writeXsiType, DataContract.GetId(memberType.TypeHandle), memberType.TypeHandle);
        }
    }
References System.Runtime.Serialization.Dictionary, System.Runtime.Serialization.DataContract.GetId(), System.Runtime.Serialization.XmlObjectSerializerWriteContext.InternalSerialize(), System.Runtime.Serialization.XmlObjectSerializerWriteContext.InternalSerializeReference(), and System.obj.
Referenced by System.Runtime.Serialization.ReflectionClassWriter.ReflectionWriteValue().