Terraria: ShopHelper.GetNearbyResidentNPCs
GetNearbyResidentNPCs()
List<NPC> ShopHelper.GetNearbyResidentNPCs (NPC npc, out int npcsWithinHouse, out int npcsWithinVillage) inline private
     {
         List<NPC> list = new List<NPC>();
         npcsWithinHouse = 0;
         npcsWithinVillage = 0;
         Vector2 value = new Vector2(npc.homeTileX, npc.homeTileY);
         if (npc.homeless)
         {
             value = new Vector2(npc.Center.X / 16f, npc.Center.Y / 16f);
         }
         for (int i = 0; i < 200; i++)
         {
             if (i == npc.whoAmI)
             {
                 continue;
             }
             NPC nPC = Main.npc[i];
             if (nPC.active && nPC.townNPC && !IsNotReallyTownNPC(nPC) && !WorldGen.TownManager.CanNPCsLiveWithEachOther_ShopHelper(npc, nPC))
             {
                 Vector2 value2 = new Vector2(nPC.homeTileX, nPC.homeTileY);
                 if (nPC.homeless)
                 {
                     value2 = nPC.Center / 16f;
                 }
                 float num = Vector2.Distance(value, value2);
                 if (num < 25f)
                 {
                     list.Add(nPC);
                     npcsWithinHouse++;
                 }
                 else if (num < 120f)
                 {
                     npcsWithinVillage++;
                 }
             }
         }
         return list;
     }
References Entity.active, TownRoomManager.CanNPCsLiveWithEachOther_ShopHelper(), Entity.Center, NPC.homeless, NPC.homeTileX, NPC.homeTileY, IsNotReallyTownNPC(), Main.npc, WorldGen.TownManager, NPC.townNPC, and Entity.whoAmI.
Referenced by ProcessMood().