Terraria: System.Runtime.Serialization.ReflectionClassWriter.ReflectionWriteClass
ReflectionWriteClass()
void System.Runtime.Serialization.ReflectionClassWriter.ReflectionWriteClass (XmlWriterDelegator xmlWriter, object obj, XmlObjectSerializerWriteContext context, ClassDataContract classContract, XmlDictionaryString[] memberNames) inline inherited
Definition at line 11 of file ReflectionClassWriter.cs.
    {
        InvokeOnSerializing(obj, context, classContract);
        obj = ResolveAdapterType(obj, classContract);
        if (classContract.IsISerializable)
        {
            context.WriteISerializable(xmlWriter, (ISerializable)obj);
        }
        else
        {
            if (classContract.HasExtensionData)
            {
                context.WriteExtensionData(xmlWriter, ((IExtensibleDataObject)obj).ExtensionData, -1);
            }
            ReflectionWriteMembers(xmlWriter, obj, context, classContract, classContract, 0, memberNames);
        }
        InvokeOnSerialized(obj, context, classContract);
    }
References System.Runtime.Serialization.Dictionary, System.Runtime.Serialization.ReflectionClassWriter.InvokeOnSerialized(), System.Runtime.Serialization.ReflectionClassWriter.InvokeOnSerializing(), System.obj, System.Runtime.Serialization.ReflectionClassWriter.ReflectionWriteMembers(), System.Runtime.Serialization.ReflectionClassWriter.ResolveAdapterType(), System.Runtime.Serialization.XmlObjectSerializerWriteContext.WriteExtensionData(), and System.Runtime.Serialization.XmlObjectSerializerWriteContext.WriteISerializable().
Referenced by System.Runtime.Serialization.ReflectionXmlFormatWriter.ReflectionWriteClass(), and System.Runtime.Serialization.Json.ReflectionJsonFormatWriter.ReflectionWriteClass().