Terraria: FlameParticle.Draw
Draw()
override void FlameParticle.Draw (ref ParticleRendererSettings settings, SpriteBatch spritebatch) inline virtual
Implements ABasicParticle.
     {
         Color color = new Color(120, 120, 120, 60) * Utils.GetLerpValue(1f, FadeOutNormalizedTime, _timeSinceSpawn / _timeTolive, clamped: true);
         Vector2 vector = settings.AnchorPosition + LocalPosition;
         ulong seed = Main.TileFrameSeed ^ (((ulong)LocalPosition.X << 32) | (uint)LocalPosition.Y);
         Player player = Main.player[_indexOfPlayerWhoSpawnedThis];
         for (int i = 0; i < 4; i++)
         {
             DrawData drawData = new DrawData(position: vector + new Vector2(Utils.RandomInt(ref seed, -2, 3), Utils.RandomInt(ref seed, -2, 3)) * Scale, texture: _texture.Value, sourceRect: _frame, color: color, rotation: Rotation, origin: _origin, scale: Scale, effect: SpriteEffects.None);
             drawData.shader = _packedShaderIndex;
             DrawData cdd = drawData;
             PlayerDrawHelper.SetShaderForData(player, 0, ref cdd);
             cdd.Draw(spritebatch);
         }
         Main.pixelShader.CurrentTechnique.Passes[0].Apply();
     }
References ABasicParticle._frame, _indexOfPlayerWhoSpawnedThis, ABasicParticle._origin, _packedShaderIndex, ABasicParticle._texture, _timeSinceSpawn, _timeTolive, Color, DrawData.Draw(), FadeOutNormalizedTime, Utils.GetLerpValue(), ABasicParticle.LocalPosition, Main.pixelShader, Main.player, Utils.RandomInt(), ABasicParticle.Rotation, ABasicParticle.Scale, PlayerDrawHelper.SetShaderForData(), DrawData.shader, Main.TileFrameSeed, and Asset< T >.Value.