Terraria: CaptureInterface.ToggleCamera
ToggleCamera()
void CaptureInterface.ToggleCamera (bool On = true) inline
     {
         if (CameraLock)
         {
             return;
         }
         bool active = Active;
         Active = Modes.ContainsKey(SelectedMode) && On;
         if (active != Active)
         {
             SoundEngine.PlaySound(On ? 10 : 11);
         }
         foreach (KeyValuePair<int, CaptureInterfaceMode> mode in Modes)
         {
             mode.Value.ToggleActive(Active && mode.Key == SelectedMode);
         }
         if (On && !active)
         {
             JustActivated = true;
         }
     }
References Active, CameraLock, JustActivated, Modes, On, SoundEngine.PlaySound(), and SelectedMode.
Referenced by Update(), and UpdateButtons().