Terraria: CaptureInterface.Draw
Draw()
void CaptureInterface.Draw (SpriteBatch sb) inline
     {
         if (!Active)
         {
             return;
         }
         sb.End();
         sb.Begin(SpriteSortMode.Deferred, BlendState.AlphaBlend, SamplerState.LinearClamp, DepthStencilState.None, RasterizerState.CullCounterClockwise, null, Main.UIScaleMatrix);
         PlayerInput.SetZoom_UI();
         foreach (CaptureInterfaceMode value in Modes.Values)
         {
             value.Draw(sb);
         }
         sb.End();
         sb.Begin(SpriteSortMode.Deferred, BlendState.AlphaBlend, SamplerState.LinearClamp, DepthStencilState.None, RasterizerState.CullCounterClockwise, null, Main.UIScaleMatrix);
         PlayerInput.SetZoom_UI();
         Main.mouseText = false;
         Main.instance.GUIBarsDraw();
         DrawButtons(sb);
         Main.instance.DrawMouseOver();
         Utils.DrawBorderStringBig(sb, Lang.inter[81].Value, new Vector2((float)Main.screenWidth * 0.5f, 100f), Color.White, 1f, 0.5f, 0.5f);
         Utils.DrawCursorSingle(sb, Main.cursorColor, float.NaN, Main.cursorScale);
         DrawCameraLock(sb);
         sb.End();
         sb.Begin();
     }
References Active, Color, Main.cursorColor, Main.cursorScale, CaptureInterface.CaptureInterfaceMode.Draw(), Utils.DrawBorderStringBig(), DrawButtons(), DrawCameraLock(), Utils.DrawCursorSingle(), Main.DrawMouseOver(), Main.GUIBarsDraw(), Main.instance, Lang.inter, Modes, Main.mouseText, Main.screenWidth, PlayerInput.SetZoom_UI(), Main.UIScaleMatrix, and LocalizedText.Value.
Referenced by CaptureManager.Draw().