Terraria: CaptureInterface.UpdateButtons
UpdateButtons()
bool CaptureInterface.UpdateButtons (Vector2 mouse) inline private
     {
         HoveredMode = -1;
         bool flag = !Main.graphics.IsFullScreen;
         int num = 9;
         for (int i = 0; i < num; i++)
         {
             if (!new Rectangle(24 + 46 * i, 24, 42, 42).Contains(mouse.ToPoint()))
             {
                 continue;
             }
             HoveredMode = i;
             bool flag2 = Main.mouseLeft && Main.mouseLeftRelease;
             int num2 = 0;
             if (i == num2++ && flag2)
             {
                 QuickScreenshot();
             }
             if (i == num2++ && flag2 && EdgeAPinned && EdgeBPinned)
             {
                 CaptureSettings obj = new CaptureSettings
                 {
                     Area = GetArea(),
                     Biome = CaptureBiome.GetCaptureBiome(Settings.BiomeChoiceIndex),
                     CaptureBackground = !Settings.TransparentBackground,
                     CaptureEntities = Settings.IncludeEntities,
                     UseScaling = Settings.PackImage,
                     CaptureMech = WiresUI.Settings.DrawWires
                 };
                 if (obj.Biome.WaterStyle != 13)
                 {
                     Main.liquidAlpha[13] = 0f;
                 }
                 StartCamera(obj);
             }
             if (i == num2++ && flag2 && SelectedMode != 0)
             {
                 SoundEngine.PlaySound(12);
                 SelectedMode = 0;
                 ToggleCamera();
             }
             if (i == num2++ && flag2 && SelectedMode != 1)
             {
                 SoundEngine.PlaySound(12);
                 SelectedMode = 1;
                 ToggleCamera();
             }
             if (i == num2++ && flag2)
             {
                 SoundEngine.PlaySound(12);
                 ResetFocus();
             }
             if (i == num2++ && flag2 && Main.mapEnabled)
             {
                 SoundEngine.PlaySound(12);
                 Main.mapFullscreen = !Main.mapFullscreen;
             }
             if (i == num2++ && flag2 && SelectedMode != 2)
             {
                 SoundEngine.PlaySound(12);
                 SelectedMode = 2;
                 ToggleCamera();
             }
             if (i == num2++ && flag2 && flag)
             {
                 SoundEngine.PlaySound(12);
                 Utils.OpenFolder(Path.Combine(Main.SavePath, "Captures"));
             }
             if (i == num2++ && flag2)
             {
                 ToggleCamera(On: false);
                 Main.blockMouse = true;
                 Main.mouseLeftRelease = false;
             }
             return true;
         }
         return false;
     }
References Biome, CaptureSettings.Biome, CaptureInterface.Settings.BiomeChoiceIndex, Main.blockMouse, WiresUI.Settings.DrawWires, EdgeAPinned, EdgeBPinned, GetArea(), CaptureBiome.GetCaptureBiome(), Main.graphics, HoveredMode, CaptureInterface.Settings.IncludeEntities, Main.liquidAlpha, Main.mapEnabled, Main.mapFullscreen, Main.mouseLeft, Main.mouseLeftRelease, On, Utils.OpenFolder(), CaptureInterface.Settings.PackImage, SoundEngine.PlaySound(), QuickScreenshot(), ResetFocus(), Main.SavePath, SelectedMode, StartCamera(), ToggleCamera(), CaptureInterface.Settings.TransparentBackground, and CaptureBiome.WaterStyle.
Referenced by Update().