Terraria: System.Runtime.InteropServices.CustomMarshalers.EnumerableViewOfDispatch.GetEnumerator
GetEnumerator()
unsafe System.Collections.IEnumerator System.Runtime.InteropServices.CustomMarshalers.EnumerableViewOfDispatch.GetEnumerator () inline
Implements System.Collections.IEnumerable.
Definition at line 22 of file EnumerableViewOfDispatch.cs.
    {
        System.Runtime.CompilerServices.Unsafe.SkipInit(out Variant variant);
        void* value = &variant;
        DISPPARAMS pDispParams = default(DISPPARAMS);
        Guid riid = Guid.Empty;
        Dispatch.Invoke(-4, ref riid, 1, InvokeFlags.DISPATCH_METHOD | InvokeFlags.DISPATCH_PROPERTYGET, ref pDispParams, new IntPtr(value), IntPtr.Zero, IntPtr.Zero);
        IntPtr intPtr = IntPtr.Zero;
        try
        {
            object obj = variant.ToObject();
            if (!(obj is IEnumVARIANT o))
            {
                throw new InvalidOperationException(SR.InvalidOp_InvalidNewEnumVariant);
            }
            intPtr = Marshal.GetIUnknownForObject(o);
            return (System.Collections.IEnumerator)EnumeratorToEnumVariantMarshaler.GetInstance(null).MarshalNativeToManaged(intPtr);
        }
        finally
        {
            variant.Clear();
            if (intPtr != IntPtr.Zero)
            {
                Marshal.Release(intPtr);
            }
        }
    }
References System.Runtime.InteropServices.CustomMarshalers.EnumerableViewOfDispatch.Dispatch, System.Guid.Empty, System.Runtime.InteropServices.CustomMarshalers.EnumeratorToEnumVariantMarshaler.GetInstance(), System.Runtime.InteropServices.Marshal.GetIUnknownForObject(), System.SR.InvalidOp_InvalidNewEnumVariant, System.Runtime.InteropServices.IDispatch.Invoke(), System.obj, System.Runtime.InteropServices.Marshal.Release(), System.value, and System.IntPtr.Zero.