Terraria: Terraria.GameContent.UI.Elements.UIResourcePackInfoButton.DrawSelf
DrawSelf()
override void Terraria.GameContent.UI.Elements.UIResourcePackInfoButton< T >.DrawSelf (SpriteBatch spriteBatch) inline protected virtual
Reimplemented from Terraria.GameContent.UI.Elements.UIPanel.
Definition at line 36 of file UIResourcePackInfoButton.cs.
    {
        if (_drawPanel)
        {
            CalculatedStyle dimensions = GetDimensions();
            int num = 10;
            int num2 = 10;
            Utils.DrawSplicedPanel(spriteBatch, _BasePanelTexture.Value, (int)dimensions.X, (int)dimensions.Y, (int)dimensions.Width, (int)dimensions.Height, num, num, num2, num2, Color.Lerp(Color.Black, _color, 0.8f) * 0.5f);
            if (base.IsMouseHovering)
            {
                Utils.DrawSplicedPanel(spriteBatch, _hoveredBorderTexture.Value, (int)dimensions.X, (int)dimensions.Y, (int)dimensions.Width, (int)dimensions.Height, num, num, num2, num2, Color.White);
            }
        }
        DrawText(spriteBatch);
    }
References Terraria.GameContent.UI.Elements.UIResourcePackInfoButton< T >._BasePanelTexture, Terraria.GameContent.UI.Elements.UITextPanel< T >._color, Terraria.GameContent.UI.Elements.UITextPanel< T >._drawPanel, Terraria.GameContent.UI.Elements.UIResourcePackInfoButton< T >._hoveredBorderTexture, Terraria.Utils.DrawSplicedPanel(), Terraria.GameContent.UI.Elements.UITextPanel< T >.DrawText(), Terraria.UI.UIElement.GetDimensions(), and ReLogic.Content.Asset< T >.Value.