Terraria: System.Net.HttpListener.DisconnectAsyncResult.WaitCallback
WaitCallback()
static unsafe void System.Net.HttpListener.DisconnectAsyncResult.WaitCallback (uint errorCode, uint numBytes, NativeOverlapped * nativeOverlapped) inline static private
Definition at line 155 of file HttpListener.cs.
        {
            if (System.Net.NetEventSource.Log.IsEnabled())
            {
                System.Net.NetEventSource.Info(null, $"errorCode: {errorCode}, numBytes: {numBytes}, nativeOverlapped: {(IntPtr)nativeOverlapped:x}", "WaitCallback");
            }
            DisconnectAsyncResult asyncResult = (DisconnectAsyncResult)ThreadPoolBoundHandle.GetNativeOverlappedState(nativeOverlapped);
            IOCompleted(asyncResult, errorCode, numBytes, nativeOverlapped);
        }
References System.Net.HttpListener.DisconnectAsyncResult.DisconnectAsyncResult(), System.asyncResult, System.Threading.ThreadPoolBoundHandle.GetNativeOverlappedState(), System.Net.NetEventSource.Info(), System.Net.HttpListener.DisconnectAsyncResult.IOCompleted(), and System.Net.NetEventSource.Log.