Terraria: System.Net.HttpListener.DisconnectAsyncResult.HandleDisconnect
HandleDisconnect()
void System.Net.HttpListener.DisconnectAsyncResult.HandleDisconnect () inline private
Definition at line 165 of file HttpListener.cs.
        {
            HttpListener listener = _listenerSession.Listener;
            if (System.Net.NetEventSource.Log.IsEnabled())
            {
                System.Net.NetEventSource.Info(this, $"DisconnectResults {listener.DisconnectResults} removing for _connectionId: {_connectionId}", "HandleDisconnect");
            }
            listener.DisconnectResults.Remove(_connectionId);
            if (_session != null)
            {
                _session.CloseContext();
            }
            IDisposable disposable = ((_authenticatedConnection == null) ? null : (_authenticatedConnection.Identity as IDisposable));
            if (disposable != null && _authenticatedConnection.Identity.AuthenticationType == "NTLM" && listener.UnsafeConnectionNtlmAuthentication)
            {
                disposable.Dispose();
            }
            int num = Interlocked.Exchange(ref _ownershipState, 3);
        }
References System.Net.HttpListener.DisconnectAsyncResult._authenticatedConnection, System.Net.HttpListener.DisconnectAsyncResult._connectionId, System.Net.HttpListener.DisconnectAsyncResult._listenerSession, System.Net.HttpListener.DisconnectAsyncResult._ownershipState, System.Net.HttpListener.DisconnectAsyncResult._session, System.Net.HttpListener.DisconnectResults, System.Threading.Interlocked.Exchange(), System.Security.Principal.WindowsPrincipal.Identity, System.Net.NetEventSource.Info(), System.Net.HttpListenerSession.Listener, System.Net.NetEventSource.Log, System.Collections.Generic.Dictionary< TKey, TValue >.Remove(), and System.Net.HttpListener.UnsafeConnectionNtlmAuthentication.
Referenced by System.Net.HttpListener.DisconnectAsyncResult.FinishOwningDisconnectHandling().