Terraria: System.Dynamic.DynamicMetaObject.GetExpressions
GetExpressions()
static Expression[] System.Dynamic.DynamicMetaObject.GetExpressions (DynamicMetaObject[] objects) inline static package inherited
Definition at line 143 of file DynamicMetaObject.cs.
    {
        ContractUtils.RequiresNotNull(objects, "objects");
        Expression[] array = new Expression[objects.Length];
        for (int i = 0; i < objects.Length; i++)
        {
            DynamicMetaObject dynamicMetaObject = objects[i];
            ContractUtils.RequiresNotNull(dynamicMetaObject, "objects");
            Expression expression = dynamicMetaObject.Expression;
            array[i] = expression;
        }
        return array;
    }
References System.array, and System.Dynamic.Utils.ContractUtils.RequiresNotNull().
Referenced by System.Dynamic.DynamicObject.MetaDynamic.BindCreateInstance(), System.Dynamic.DynamicObject.MetaDynamic.BindDeleteIndex(), System.Dynamic.DynamicObject.MetaDynamic.BindGetIndex(), System.Dynamic.DynamicObject.MetaDynamic.BindInvoke(), System.Dynamic.DynamicObject.MetaDynamic.BindInvokeMember(), System.Dynamic.DynamicObject.MetaDynamic.BindSetIndex(), and System.Dynamic.DynamicMetaObjectBinder.MakeDeferred().