Terraria: System.Net.SocketAddress.GetIPAddress
GetIPAddress()
IPAddress System.Net.SocketAddress.GetIPAddress () inline package
Definition at line 87 of file SocketAddress.cs.
    {
        if (Family == AddressFamily.InterNetworkV6)
        {
            Span<byte> span = stackalloc byte[16];
            SocketAddressPal.GetIPv6Address(Buffer, span, out var scope);
            return new IPAddress(span, scope);
        }
        if (Family == AddressFamily.InterNetwork)
        {
            long newAddress = (long)SocketAddressPal.GetIPv4Address(Buffer) & 0xFFFFFFFFL;
            return new IPAddress(newAddress);
        }
        throw new SocketException(SocketError.AddressFamilyNotSupported);
    }
References System.Net.SocketAddress.Family, System.Net.SocketAddressPal.GetIPv4Address(), System.Net.SocketAddressPal.GetIPv6Address(), and System.L.
Referenced by System.Net.SocketAddress.GetIPEndPoint().