Terraria: System.Reflection.Metadata.Ecma335.MemberRefTableReader.GetClass
GetClass()
EntityHandle System.Reflection.Metadata.Ecma335.MemberRefTableReader.GetClass (MemberReferenceHandle handle) inline package
Definition at line 50 of file MemberRefTableReader.cs.
    {
        int num = (handle.RowId - 1) * RowSize;
        return MemberRefParentTag.ConvertToHandle(Block.PeekTaggedReference(num + _ClassOffset, _IsMemberRefParentRefSizeSmall));
    }
References System.Reflection.Metadata.Ecma335.MemberRefTableReader._ClassOffset, System.Reflection.Metadata.Ecma335.MemberRefTableReader._IsMemberRefParentRefSizeSmall, System.Reflection.Metadata.Ecma335.MemberRefTableReader.Block, System.Reflection.Metadata.Ecma335.MemberRefParentTag.ConvertToHandle(), System.Reflection.Internal.MemoryBlock.PeekTaggedReference(), and System.Reflection.Metadata.Ecma335.MemberRefTableReader.RowSize.
Referenced by System.Reflection.Metadata.MetadataReader.GetAttributeTypeRaw(), System.Reflection.Metadata.MemberReference.GetProjectedParent(), System.Reflection.Metadata.MetadataReader.ImplementsRedirectedInterface(), and System.Reflection.Metadata.MetadataReader.IsWindowsAttributeUsageAttribute().