Terraria: System.Threading.Channels.BoundedChannel.BoundedChannelReader.DequeueItemAndPostProcess
DequeueItemAndPostProcess()
T System.Threading.Channels.BoundedChannel< T >.BoundedChannelReader.DequeueItemAndPostProcess () inline private
Definition at line 143 of file BoundedChannel.cs.
        {
            BoundedChannel<T> parent = _parent;
            T result = parent._items.DequeueHead();
            if (parent._doneWriting != null)
            {
                if (parent._items.IsEmpty)
                {
                    ChannelUtilities.Complete(parent._completion, parent._doneWriting);
                }
            }
            else
            {
                while (!parent._blockedWriters.IsEmpty)
                {
                    VoidAsyncOperationWithData<T> voidAsyncOperationWithData = parent._blockedWriters.DequeueHead();
                    if (voidAsyncOperationWithData.TrySetResult(default(VoidResult)))
                    {
                        parent._items.EnqueueTail(voidAsyncOperationWithData.Item);
                        return result;
                    }
                }
                ChannelUtilities.WakeUpWaiters(ref parent._waitingWritersTail, result: true);
            }
            return result;
        }
References System.Threading.Channels.BoundedChannel< T >.BoundedChannelReader._parent, System.Threading.Channels.ChannelUtilities.Complete(), and System.Threading.Channels.ChannelUtilities.WakeUpWaiters().
Referenced by System.Threading.Channels.BoundedChannel< T >.BoundedChannelReader.ReadAsync(), and System.Threading.Channels.BoundedChannel< T >.BoundedChannelReader.TryRead().