Terraria: System.Reflection.PortableExecutable.ManagedTextSection.Serialize
Serialize()
void System.Reflection.PortableExecutable.ManagedTextSection.Serialize (BlobBuilder builder, int relativeVirtualAddess, int entryPointTokenOrRelativeVirtualAddress, CorFlags corFlags, ulong baseAddress, BlobBuilder metadataBuilder, BlobBuilder ilBuilder, BlobBuilder? mappedFieldDataBuilderOpt, BlobBuilder? resourceBuilderOpt, BlobBuilder? debugDataBuilderOpt, out Blob strongNameSignature) inline
Definition at line 176 of file ManagedTextSection.cs.
    {
        int relativeVirtualAddress = GetImportTableDirectoryEntry(relativeVirtualAddess).RelativeVirtualAddress;
        int relativeVirtualAddress2 = GetImportAddressTableDirectoryEntry(relativeVirtualAddess).RelativeVirtualAddress;
        if (RequiresStartupStub)
        {
            WriteImportAddressTable(builder, relativeVirtualAddress);
        }
        WriteCorHeader(builder, relativeVirtualAddess, entryPointTokenOrRelativeVirtualAddress, corFlags);
        ilBuilder.Align(4);
        builder.LinkSuffix(ilBuilder);
        builder.LinkSuffix(metadataBuilder);
        if (resourceBuilderOpt != null)
        {
            builder.LinkSuffix(resourceBuilderOpt);
        }
        strongNameSignature = builder.ReserveBytes(StrongNameSignatureSize);
        new BlobWriter(strongNameSignature).WriteBytes(0, StrongNameSignatureSize);
        if (debugDataBuilderOpt != null)
        {
            builder.LinkSuffix(debugDataBuilderOpt);
        }
        if (RequiresStartupStub)
        {
            WriteImportTable(builder, relativeVirtualAddress, relativeVirtualAddress2);
            WriteNameTable(builder);
            WriteRuntimeStartupStub(builder, relativeVirtualAddress2, baseAddress);
        }
        if (mappedFieldDataBuilderOpt != null)
        {
            builder.LinkSuffix(mappedFieldDataBuilderOpt);
        }
    }
References System.Reflection.Metadata.BlobBuilder.Align(), System.Reflection.PortableExecutable.ManagedTextSection.GetImportAddressTableDirectoryEntry(), System.Reflection.PortableExecutable.ManagedTextSection.GetImportTableDirectoryEntry(), System.Reflection.Metadata.BlobBuilder.LinkSuffix(), System.Reflection.PortableExecutable.DirectoryEntry.RelativeVirtualAddress, System.Reflection.PortableExecutable.ManagedTextSection.RequiresStartupStub, System.Reflection.Metadata.BlobBuilder.ReserveBytes(), System.Reflection.PortableExecutable.ManagedTextSection.StrongNameSignatureSize, System.Reflection.Metadata.BlobWriter.WriteBytes(), System.Reflection.PortableExecutable.ManagedTextSection.WriteCorHeader(), System.Reflection.PortableExecutable.ManagedTextSection.WriteImportAddressTable(), System.Reflection.PortableExecutable.ManagedTextSection.WriteImportTable(), System.Reflection.PortableExecutable.ManagedTextSection.WriteNameTable(), and System.Reflection.PortableExecutable.ManagedTextSection.WriteRuntimeStartupStub().