Terraria: Microsoft.Xna.Framework.Graphics.TextureCube.InitializeDescription
InitializeDescription() [2/2]
unsafe void Microsoft.Xna.Framework.Graphics.TextureCube.InitializeDescription (SurfaceFormat? format) inline protected
Definition at line 317 of file TextureCube.cs.
    {
        IDirect3DCubeTexture9* ptr = pComPtr;
        System.Runtime.CompilerServices.Unsafe.SkipInit(out _D3DSURFACE_DESC d3DSURFACE_DESC);
        int num = ((delegate* unmanaged[Stdcall, Stdcall]<IntPtr, uint, _D3DSURFACE_DESC*, int>)(int)(*(uint*)(*(int*)ptr + 68)))((nint)ptr, 0u, &d3DSURFACE_DESC);
        if (num < 0)
        {
            throw GraphicsHelpers.GetExceptionFromResult((uint)num);
        }
        if (!format.HasValue)
        {
            format = _003CModule_003E.ConvertWindowsFormatToXna(*(_D3DFORMAT*)(&d3DSURFACE_DESC));
        }
        _size = System.Runtime.CompilerServices.Unsafe.As<_D3DSURFACE_DESC, int>(ref System.Runtime.CompilerServices.Unsafe.AddByteOffset(ref d3DSURFACE_DESC, 24));
        int shouldNotRecreate = ((System.Runtime.CompilerServices.Unsafe.As<_D3DSURFACE_DESC, int>(ref System.Runtime.CompilerServices.Unsafe.AddByteOffset(ref d3DSURFACE_DESC, 12)) == 0) ? 1 : 0);
        _shouldNotRecreate = (byte)shouldNotRecreate != 0;
        base.InitializeDescription(format.Value);
    }
References Microsoft.Xna.Framework.Graphics.TextureCube._shouldNotRecreate, Microsoft.Xna.Framework.Graphics.TextureCube._size, System.format, Microsoft.Xna.Framework.Graphics.GraphicsHelpers.GetExceptionFromResult(), and Microsoft.Xna.Framework.Graphics.TextureCube.pComPtr.
Referenced by Microsoft.Xna.Framework.Graphics.TextureCube.TextureCube(), Microsoft.Xna.Framework.Graphics.TextureCube.CreateTexture(), and Microsoft.Xna.Framework.Graphics.TextureCube.OnObjectCreation().