Terraria: System.Reflection.PortableExecutable.ManagedTextSection.ComputeOffsetToMetadata
ComputeOffsetToMetadata()
int System.Reflection.PortableExecutable.ManagedTextSection.ComputeOffsetToMetadata () inline private
Definition at line 134 of file ManagedTextSection.cs.
    {
        return OffsetToILStream + BitArithmetic.Align(ILStreamSize, 4);
    }
References System.Reflection.Internal.BitArithmetic.Align(), System.Reflection.PortableExecutable.ManagedTextSection.ILStreamSize, and System.Reflection.PortableExecutable.ManagedTextSection.OffsetToILStream.
Referenced by System.Reflection.PortableExecutable.ManagedTextSection.ComputeOffsetToDebugDirectory(), and System.Reflection.PortableExecutable.ManagedTextSection.WriteCorHeader().