Terraria: Microsoft.Xna.Framework.Graphics.TextureCube.ValidateCreationParameters
ValidateCreationParameters()
static void Microsoft.Xna.Framework.Graphics.TextureCube.ValidateCreationParameters (ProfileCapabilities profile, int size, SurfaceFormat format) inline static protected
Definition at line 360 of file TextureCube.cs.
    {
        if (size <= 0)
        {
            throw new ArgumentOutOfRangeException("size", FrameworkResources.ResourcesMustBeGreaterThanZeroSize);
        }
        bool flag = Texture.CheckCompressedTexture(_003CModule_003E.ConvertXnaFormatToWindows(format));
        if (!profile.ValidCubeFormats.Contains(format))
        {
            profile.ThrowNotSupportedException(FrameworkResources.ProfileFormatNotSupported, typeof(TextureCube).Name, format);
        }
        int maxCubeSize = profile.MaxCubeSize;
        if (size > maxCubeSize)
        {
            profile.ThrowNotSupportedException(FrameworkResources.ProfileTooBig, typeof(TextureCube).Name, maxCubeSize);
        }
        if (!profile.NonPow2Cube && !Texture.IsPowerOfTwo((uint)size))
        {
            profile.ThrowNotSupportedException(FrameworkResources.ProfileNotPowerOfTwo, typeof(TextureCube).Name);
        }
        if (flag && ((uint)size & 3u) != 0)
        {
            throw new ArgumentException(FrameworkResources.DxtNotMultipleOfFour);
        }
    }
References Microsoft.Xna.Framework.Graphics.Texture.CheckCompressedTexture(), System.Collections.Generic.List< T >.Contains(), Microsoft.Xna.Framework.FrameworkResources.DxtNotMultipleOfFour, System.format, Microsoft.Xna.Framework.Graphics.Texture.IsPowerOfTwo(), Microsoft.Xna.Framework.Graphics.ProfileCapabilities.MaxCubeSize, Microsoft.Xna.Framework.Graphics.GraphicsResource.Name, Microsoft.Xna.Framework.Graphics.ProfileCapabilities.NonPow2Cube, Microsoft.Xna.Framework.FrameworkResources.ProfileFormatNotSupported, Microsoft.Xna.Framework.FrameworkResources.ProfileNotPowerOfTwo, Microsoft.Xna.Framework.FrameworkResources.ProfileTooBig, Microsoft.Xna.Framework.FrameworkResources.ResourcesMustBeGreaterThanZeroSize, Microsoft.Xna.Framework.Graphics.ProfileCapabilities.ThrowNotSupportedException(), and Microsoft.Xna.Framework.Graphics.ProfileCapabilities.ValidCubeFormats.
Referenced by Microsoft.Xna.Framework.Graphics.RenderTargetCube.CreateRenderTarget(), and Microsoft.Xna.Framework.Graphics.TextureCube.CreateTexture().