Terraria: System.Reflection.PortableExecutable.ManagedTextSection.CalculateOffsetToMappedFieldDataStream
CalculateOffsetToMappedFieldDataStream()
int System.Reflection.PortableExecutable.ManagedTextSection.CalculateOffsetToMappedFieldDataStream () inline
Definition at line 112 of file ManagedTextSection.cs.
    {
        int num = ComputeOffsetToImportTable();
        if (RequiresStartupStub)
        {
            num += SizeOfImportTable + SizeOfNameTable;
            num = BitArithmetic.Align(num, Is32Bit ? 4 : 8);
            num += SizeOfRuntimeStartupStub;
        }
        return num;
    }
References System.Reflection.Internal.BitArithmetic.Align(), System.Reflection.PortableExecutable.ManagedTextSection.ComputeOffsetToImportTable(), System.Reflection.PortableExecutable.ManagedTextSection.Is32Bit, System.Reflection.PortableExecutable.ManagedTextSection.RequiresStartupStub, System.Reflection.PortableExecutable.ManagedTextSection.SizeOfImportTable, System.Reflection.PortableExecutable.ManagedTextSection.SizeOfNameTable, and System.Reflection.PortableExecutable.ManagedTextSection.SizeOfRuntimeStartupStub.
Referenced by System.Reflection.PortableExecutable.ManagedTextSection.ComputeSizeOfTextSection(), and System.Reflection.PortableExecutable.ManagedTextSection.GetEntryPointAddress().