Terraria: System.Reflection.PortableExecutable.ManagedTextSection.WriteCorHeader
WriteCorHeader()
void System.Reflection.PortableExecutable.ManagedTextSection.WriteCorHeader (BlobBuilder builder, int textSectionRva, int entryPointTokenOrRva, CorFlags corFlags) inline private
Definition at line 271 of file ManagedTextSection.cs.
    {
        int num = textSectionRva + ComputeOffsetToMetadata();
        int num2 = num + MetadataSize;
        int num3 = num2 + ResourceDataSize;
        int count = builder.Count;
        builder.WriteUInt32(72u);
        builder.WriteUInt16(2);
        builder.WriteUInt16(5);
        builder.WriteUInt32((uint)num);
        builder.WriteUInt32((uint)MetadataSize);
        builder.WriteUInt32((uint)corFlags);
        builder.WriteUInt32((uint)entryPointTokenOrRva);
        builder.WriteUInt32((ResourceDataSize != 0) ? ((uint)num2) : 0u);
        builder.WriteUInt32((uint)ResourceDataSize);
        builder.WriteUInt32((StrongNameSignatureSize != 0) ? ((uint)num3) : 0u);
        builder.WriteUInt32((uint)StrongNameSignatureSize);
        builder.WriteUInt32(0u);
        builder.WriteUInt32(0u);
        builder.WriteUInt32(0u);
        builder.WriteUInt32(0u);
        builder.WriteUInt32(0u);
        builder.WriteUInt32(0u);
        builder.WriteUInt32(0u);
        builder.WriteUInt32(0u);
    }
References System.Reflection.PortableExecutable.ManagedTextSection.ComputeOffsetToMetadata(), System.count, System.Reflection.Metadata.BlobBuilder.Count, System.Reflection.PortableExecutable.ManagedTextSection.MetadataSize, System.Reflection.PortableExecutable.ManagedTextSection.ResourceDataSize, System.Reflection.PortableExecutable.ManagedTextSection.StrongNameSignatureSize, System.Reflection.Metadata.BlobBuilder.WriteUInt16(), and System.Reflection.Metadata.BlobBuilder.WriteUInt32().
Referenced by System.Reflection.PortableExecutable.ManagedTextSection.Serialize().