Terraria: System.Reflection.PortableExecutable.ManagedTextSection.WriteImportTable
WriteImportTable()
void System.Reflection.PortableExecutable.ManagedTextSection.WriteImportTable (BlobBuilder builder, int importTableRva, int importAddressTableRva) inline private
Definition at line 227 of file ManagedTextSection.cs.
    {
        int count = builder.Count;
        int num = importTableRva + 40;
        int num2 = num + (Is32Bit ? 12 : 16);
        int value = num2 + 12 + 2;
        builder.WriteUInt32((uint)num);
        builder.WriteUInt32(0u);
        builder.WriteUInt32(0u);
        builder.WriteUInt32((uint)value);
        builder.WriteUInt32((uint)importAddressTableRva);
        builder.WriteBytes(0, 20);
        if (Is32Bit)
        {
            builder.WriteUInt32((uint)num2);
            builder.WriteUInt32(0u);
            builder.WriteUInt32(0u);
        }
        else
        {
            builder.WriteUInt64((uint)num2);
            builder.WriteUInt64(0uL);
        }
        builder.WriteUInt16(0);
        string corEntryPointName = CorEntryPointName;
        foreach (char c in corEntryPointName)
        {
            builder.WriteByte((byte)c);
        }
        builder.WriteByte(0);
    }
References System.Reflection.PortableExecutable.ManagedTextSection.CorEntryPointName, System.count, System.Reflection.Metadata.BlobBuilder.Count, System.Reflection.PortableExecutable.ManagedTextSection.Is32Bit, System.value, System.Reflection.Metadata.BlobBuilder.WriteBytes(), System.Reflection.Metadata.BlobBuilder.WriteUInt16(), System.Reflection.Metadata.BlobBuilder.WriteUInt32(), and System.Reflection.Metadata.BlobBuilder.WriteUInt64().
Referenced by System.Reflection.PortableExecutable.ManagedTextSection.Serialize().