Terraria: System.Reflection.PortableExecutable.ManagedTextSection.WriteRuntimeStartupStub
WriteRuntimeStartupStub()
void System.Reflection.PortableExecutable.ManagedTextSection.WriteRuntimeStartupStub (BlobBuilder sectionBuilder, int importAddressTableRva, ulong baseAddress) inline private
Definition at line 298 of file ManagedTextSection.cs.
    {
        if (Is32Bit)
        {
            sectionBuilder.Align(4);
            sectionBuilder.WriteUInt16(0);
            sectionBuilder.WriteByte(byte.MaxValue);
            sectionBuilder.WriteByte(37);
            sectionBuilder.WriteUInt32((uint)(importAddressTableRva + (int)baseAddress));
        }
        else
        {
            sectionBuilder.Align(8);
            sectionBuilder.WriteUInt32(0u);
            sectionBuilder.WriteUInt16(0);
            sectionBuilder.WriteByte(byte.MaxValue);
            sectionBuilder.WriteByte(37);
            sectionBuilder.WriteUInt64((ulong)importAddressTableRva + baseAddress);
        }
    }
References System.Reflection.Metadata.BlobBuilder.Align(), System.Reflection.PortableExecutable.ManagedTextSection.Is32Bit, System.Reflection.MaxValue, System.Reflection.Metadata.BlobBuilder.WriteByte(), System.Reflection.Metadata.BlobBuilder.WriteUInt16(), System.Reflection.Metadata.BlobBuilder.WriteUInt32(), and System.Reflection.Metadata.BlobBuilder.WriteUInt64().
Referenced by System.Reflection.PortableExecutable.ManagedTextSection.Serialize().