Terraria: Microsoft.Xna.Framework.Graphics.TextureCube.SaveDataForRecreation
SaveDataForRecreation() [1/2]
virtual unsafe int Microsoft.Xna.Framework.Graphics.TextureCube.SaveDataForRecreation () inline package virtual
Implements Microsoft.Xna.Framework.Graphics.IGraphicsResource.
Reimplemented in Microsoft.Xna.Framework.Graphics.RenderTargetCube, and Microsoft.Xna.Framework.Graphics.RenderTargetCube.
Definition at line 386 of file TextureCube.cs.
    {
        if (pComPtr == null)
        {
            return 0;
        }
        CleanupSavedData();
        int num = CopyOrRestoreData(isStoring: true);
        if (num >= 0)
        {
            ReleaseNativeObject(disposeManagedResource: false);
        }
        else
        {
            CleanupSavedData();
        }
        alreadyRecreated = false;
        return num;
    }
References Microsoft.Xna.Framework.Graphics.Texture.alreadyRecreated, Microsoft.Xna.Framework.Graphics.TextureCube.CleanupSavedData(), Microsoft.Xna.Framework.Graphics.TextureCube.CopyOrRestoreData(), Microsoft.Xna.Framework.Graphics.TextureCube.pComPtr, and Microsoft.Xna.Framework.Graphics.TextureCube.ReleaseNativeObject().
Referenced by Microsoft.Xna.Framework.Graphics.TextureCube.SaveDataForRecreation().