Terraria: Microsoft.Xna.Framework.Graphics.TextureCube.CopyOrRestoreData
CopyOrRestoreData()
unsafe int Microsoft.Xna.Framework.Graphics.TextureCube.CopyOrRestoreData ([MarshalAs(UnmanagedType.U1)] bool isStoring) inline package
Definition at line 477 of file TextureCube.cs.
    {
        IDirect3DCubeTexture9* ptr = pComPtr;
        if (ptr == null)
        {
            return 0;
        }
        System.Runtime.CompilerServices.Unsafe.SkipInit(out _D3DSURFACE_DESC d3DSURFACE_DESC);
        int num = ((delegate* unmanaged[Stdcall, Stdcall]<IntPtr, uint, _D3DSURFACE_DESC*, int>)(int)(*(uint*)(*(int*)ptr + 68)))((nint)ptr, 0u, &d3DSURFACE_DESC);
        if (num >= 0)
        {
            if (isStoring)
            {
                pFaceData = new IntPtr[_levelCount * 6];
            }
            uint num2 = System.Runtime.CompilerServices.Unsafe.As<_D3DSURFACE_DESC, uint>(ref System.Runtime.CompilerServices.Unsafe.AddByteOffset(ref d3DSURFACE_DESC, 24));
            uint num3 = System.Runtime.CompilerServices.Unsafe.As<_D3DSURFACE_DESC, uint>(ref System.Runtime.CompilerServices.Unsafe.AddByteOffset(ref d3DSURFACE_DESC, 28));
            bool flag = Texture.CheckCompressedTexture(*(_D3DFORMAT*)(&d3DSURFACE_DESC));
            byte b = ((!flag) ? Texture.GetExpectedByteSizeFromFormat(*(_D3DFORMAT*)(&d3DSURFACE_DESC)) : ((byte)((*(int*)(&d3DSURFACE_DESC) == 827611204) ? 8u : 16u)));
            int num4 = 0;
            int num5 = 0;
            if (0 < _levelCount)
            {
                System.Runtime.CompilerServices.Unsafe.SkipInit(out _D3DLOCKED_RECT d3DLOCKED_RECT);
                do
                {
                    int num6 = 0;
                    do
                    {
                        byte* ptr2 = null;
                        int num7;
                        if (!isStoring)
{
                            ref IntPtr reference = ref pFaceData[num4];
                            num4++;
                            ptr2 = (byte*)reference.ToPointer();
                            num7 = 0;
                        }
                        else
{
                            num7 = 16;
                        }
                        ptr = pComPtr;
                        num = ((delegate* unmanaged[Stdcall, Stdcall]<IntPtr, _D3DCUBEMAP_FACES, uint, _D3DLOCKED_RECT*, tagRECT*, uint, int>)(int)(*(uint*)(*(int*)ptr + 76)))((nint)ptr, (_D3DCUBEMAP_FACES)num6, (uint)num5, &d3DLOCKED_RECT, null, (uint)num7);
                        if (num < 0)
{
                            break;
                        }
                        uint num8 = num2;
                        uint num9 = num3;
                        if (flag)
{
                            num8 = num2 + 3 >> 2;
                            num9 = num3 + 3 >> 2;
                        }
                        uint num10 = b * num8;
                        byte* ptr3 = (byte*)(int)System.Runtime.CompilerServices.Unsafe.As<_D3DLOCKED_RECT, uint>(ref System.Runtime.CompilerServices.Unsafe.AddByteOffset(ref d3DLOCKED_RECT, 4));
                        if (isStoring)
{
                            ptr2 = (byte*)_003CModule_003E.new_005B_005D(num10 * num9);
                        }
                        byte* ptr4 = ptr2;
                        if (0 < num9)
{
                            uint num11 = num9;
                            do
{
                                if (isStoring)
{
                                    _003CModule_003E.memcpy_s(ptr4, num10 * num9, ptr3, num10);
                                }
                                else
{
                                    _003CModule_003E.memcpy_s(ptr3, *(uint*)(&d3DLOCKED_RECT), ptr4, num10);
                                }
                                ptr3 = *(int*)(&d3DLOCKED_RECT) + ptr3;
                                ptr4 = (int)num10 + ptr4;
                                num11--;
                            }
                            while (num11 != 0);
                        }
                        ptr = pComPtr;
                        num = ((delegate* unmanaged[Stdcall, Stdcall]<IntPtr, _D3DCUBEMAP_FACES, uint, int>)(int)(*(uint*)(*(int*)ptr + 80)))((nint)ptr, (_D3DCUBEMAP_FACES)num6, (uint)num5);
                        if (num < 0)
{
                            break;
                        }
                        if (isStoring)
{
                            IntPtr intPtr = (IntPtr)ptr2;
                            ref IntPtr reference2 = ref pFaceData[num4];
                            num4++;
                            reference2 = intPtr;
                        }
                        num6++;
                    }
                    while (num6 < 6);
                    num2 = ((num2 <= 1) ? 1u : (num2 >> 1));
                    num3 = ((num3 <= 1) ? 1u : (num3 >> 1));
                    num5++;
                }
                while (num5 < _levelCount);
            }
        }
        return num;
    }
References Microsoft.Xna.Framework.Graphics.Texture._levelCount, Microsoft.Xna.Framework.Graphics.Texture.CheckCompressedTexture(), Microsoft.Xna.Framework.Graphics.Texture.GetExpectedByteSizeFromFormat(), Microsoft.Xna.Framework.Graphics.TextureCube.pComPtr, and Microsoft.Xna.Framework.Graphics.TextureCube.pFaceData.
Referenced by Microsoft.Xna.Framework.Graphics.TextureCube.RecreateAndPopulateObject(), and Microsoft.Xna.Framework.Graphics.TextureCube.SaveDataForRecreation().