Terraria: System.Reflection.Metadata.Ecma335.StateMachineMethodTableReader.GetKickoffMethod
GetKickoffMethod()
MethodDefinitionHandle System.Reflection.Metadata.Ecma335.StateMachineMethodTableReader.GetKickoffMethod (int rowId) inline private
Definition at line 40 of file StateMachineMethodTableReader.cs.
    {
        int num = (rowId - 1) * RowSize;
        return MethodDefinitionHandle.FromRowId(Block.PeekReference(num + _kickoffMethodOffset, _isMethodRefSizeSmall));
    }
References System.Reflection.Metadata.Ecma335.StateMachineMethodTableReader._isMethodRefSizeSmall, System.Reflection.Metadata.Ecma335.StateMachineMethodTableReader._kickoffMethodOffset, System.Reflection.Metadata.Ecma335.StateMachineMethodTableReader.Block, System.Reflection.Metadata.MethodDefinitionHandle.FromRowId(), System.Reflection.Internal.MemoryBlock.PeekReference(), and System.Reflection.Metadata.Ecma335.StateMachineMethodTableReader.RowSize.
Referenced by System.Reflection.Metadata.Ecma335.StateMachineMethodTableReader.FindKickoffMethod().