Terraria: TownRoomManager.GetHouseholdStatus
GetHouseholdStatus()
byte TownRoomManager.GetHouseholdStatus (NPC n) inline
     {
         byte result = 0;
         if (n.homeless)
         {
             result = 1;
         }
         else if (HasRoomQuick(n.type))
         {
             result = 2;
         }
         return result;
     }
References HasRoomQuick(), NPC.homeless, and NPC.type.
Referenced by NetMessage.SendNPCHousesAndTravelShop(), NPC.UpdateHomeTileState(), and NPC.UpdateNetworkCode().