Terraria: System.Net.Security.NegotiateStream.ThrowIfFailed
ThrowIfFailed()
void System.Net.Security.NegotiateStream.ThrowIfFailed (bool authSuccessCheck) inline private
Definition at line 793 of file NegotiateStream.cs.
    {
        ThrowIfExceptional();
        if (authSuccessCheck && !IsAuthenticatedCore)
        {
            throw new InvalidOperationException(System.SR.net_auth_noauth);
        }
    }
References System.Net.Security.NegotiateStream.IsAuthenticatedCore, System.SR.net_auth_noauth, and System.Net.Security.NegotiateStream.ThrowIfExceptional().
Referenced by System.Net.Security.NegotiateStream.AuthenticateAsync< TAdapter >(), System.Net.Security.NegotiateStream.DecryptData(), System.Net.Security.NegotiateStream.EncryptData(), System.Net.Security.NegotiateStream.Read(), System.Net.Security.NegotiateStream.ReadAsync(), System.Net.Security.NegotiateStream.ReadAsync(), System.Net.Security.NegotiateStream.Write(), System.Net.Security.NegotiateStream.WriteAsync(), and System.Net.Security.NegotiateStream.WriteAsync().