Terraria: System.Net.Security.NegotiateStream.WriteAsync
WriteAsync() [2/3]
override Task System.Net.Security.NegotiateStream.WriteAsync (byte[] buffer, int offset, int count, CancellationToken cancellationToken) inline virtual
Reimplemented from System.IO.Stream.
Definition at line 590 of file NegotiateStream.cs.
    {
        Stream.ValidateBufferArguments(buffer, offset, count);
        ThrowIfFailed(authSuccessCheck: true);
        if (!CanGetSecureStream)
        {
            return base.InnerStream.WriteAsync(buffer, offset, count, cancellationToken);
        }
        return WriteAsync(new AsyncReadWriteAdapter(base.InnerStream, cancellationToken), new ReadOnlyMemory<byte>(buffer, offset, count));
    }
References System.buffer, System.cancellationToken, System.Net.Security.NegotiateStream.CanGetSecureStream, System.count, System.offset, System.Net.Security.NegotiateStream.ThrowIfFailed(), System.IO.Stream.ValidateBufferArguments(), and System.Net.Security.NegotiateStream.WriteAsync().
Referenced by System.Net.Security.NegotiateStream.BeginWrite(), System.Net.Security.NegotiateStream.Write(), System.Net.Security.NegotiateStream.WriteAsync(), and System.Net.Security.NegotiateStream.WriteAsync().