Terraria: System.Net.Security.NegotiateStream.ThrowIfExceptional
ThrowIfExceptional()
void System.Net.Security.NegotiateStream.ThrowIfExceptional () inline private
Definition at line 665 of file NegotiateStream.cs.
    {
        ExceptionDispatchInfo exception = _exception;
        if (exception != null)
        {
            ThrowExceptional(exception);
        }
        static void ThrowExceptional(ExceptionDispatchInfo e)
        {
            if (e == s_disposedSentinel)
            {
                throw new ObjectDisposedException("NegotiateStream");
            }
            e.Throw();
        }
    }
References System.Net.Security.NegotiateStream._exception, System.exception, System.Net.Security.NegotiateStream.s_disposedSentinel, and System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw().
Referenced by System.Net.Security.NegotiateStream.ThrowIfFailed(), and System.Net.Security.NegotiateStream.ValidateCreateContext().