Terraria: System.Net.Security.NegotiateStream.SendBlobAsync< TAdapter >
SendBlobAsync< TAdapter >()
async Task System.Net.Security.NegotiateStream.SendBlobAsync< TAdapter > (TAdapter adapter, byte[] message) inline private
Type Constraints
TAdapter : IReadWriteAdapter
Definition at line 838 of file NegotiateStream.cs.
                                                                                                : IReadWriteAdapter
    {
        Exception e = null;
        if (message != s_emptyMessage)
        {
            message = GetOutgoingBlob(message, ref e);
        }
        if (e != null)
        {
            await SendAuthResetSignalAndThrowAsync(adapter, message, e).ConfigureAwait(continueOnCapturedContext: false);
        }
        if (HandshakeComplete)
        {
            if (_context.IsServer && !CheckSpn())
            {
                e = new AuthenticationException(System.SR.net_auth_bad_client_creds_or_target_mismatch);
                int num = 1790;
                message = new byte[8];
                for (int num2 = message.Length - 1; num2 >= 0; num2--)
                {
                    message[num2] = (byte)((uint)num & 0xFFu);
                    num >>>= 8;
                }
                await SendAuthResetSignalAndThrowAsync(adapter, message, e).ConfigureAwait(continueOnCapturedContext: false);
            }
            if (PrivateImpersonationLevel < _expectedImpersonationLevel)
            {
                e = new AuthenticationException(System.SR.Format(System.SR.net_auth_context_expectation, _expectedImpersonationLevel.ToString(), PrivateImpersonationLevel.ToString()));
                int num3 = 1790;
                message = new byte[8];
                for (int num4 = message.Length - 1; num4 >= 0; num4--)
                {
                    message[num4] = (byte)((uint)num3 & 0xFFu);
                    num3 >>>= 8;
                }
                await SendAuthResetSignalAndThrowAsync(adapter, message, e).ConfigureAwait(continueOnCapturedContext: false);
            }
            ProtectionLevel protectionLevel = (_context.IsConfidentialityFlag ? ProtectionLevel.EncryptAndSign : (_context.IsIntegrityFlag ? ProtectionLevel.Sign : ProtectionLevel.None));
            if (protectionLevel < _expectedProtectionLevel)
            {
                e = new AuthenticationException(System.SR.Format(System.SR.net_auth_context_expectation, protectionLevel.ToString(), _expectedProtectionLevel.ToString()));
                int num5 = 1790;
                message = new byte[8];
                for (int num6 = message.Length - 1; num6 >= 0; num6--)
                {
                    message[num6] = (byte)((uint)num5 & 0xFFu);
                    num5 >>>= 8;
                }
                await SendAuthResetSignalAndThrowAsync(adapter, message, e).ConfigureAwait(continueOnCapturedContext: false);
            }
            _framer.WriteHeader.MessageId = 20;
            if (_context.IsServer)
            {
                _remoteOk = true;
                if (message == null)
                {
                    message = s_emptyMessage;
                }
            }
        }
        else if (message == null || message == s_emptyMessage)
        {
            throw new InternalException();
        }
        if (message != null)
        {
            await _framer.WriteMessageAsync(adapter, message).ConfigureAwait(continueOnCapturedContext: false);
        }
        if (!HandshakeComplete || !_remoteOk)
        {
            await ReceiveBlobAsync(adapter).ConfigureAwait(continueOnCapturedContext: false);
        }
    }
References System.Net.Security.NegotiateStream._context, System.Net.Security.NegotiateStream._expectedImpersonationLevel, System.Net.Security.NegotiateStream._expectedProtectionLevel, System.Net.Security.NegotiateStream._framer, System.Net.Security.NegotiateStream._remoteOk, System.Net.Security.NegotiateStream.CheckSpn(), System.SR.Format(), System.Net.Security.NegotiateStream.GetOutgoingBlob(), System.Net.Security.NegotiateStream.HandshakeComplete, System.Net.NTAuthentication.IsServer, System.SR.net_auth_bad_client_creds_or_target_mismatch, System.SR.net_auth_context_expectation, System.Net.Security.NegotiateStream.PrivateImpersonationLevel, and System.Net.Security.NegotiateStream.s_emptyMessage.