Terraria: System.Net.Security.NegotiateStream.AuthenticateAsync< TAdapter >
AuthenticateAsync< TAdapter >()
async Task System.Net.Security.NegotiateStream.AuthenticateAsync< TAdapter > (TAdapter adapter, [CallerMemberName] string callerName = null) inline private
Type Constraints
TAdapter : IReadWriteAdapter
Definition at line 802 of file NegotiateStream.cs.
                                                                                                                                 : IReadWriteAdapter
    {
        ThrowIfFailed(authSuccessCheck: false);
        if (Interlocked.Exchange(ref _authInProgress, 1) == 1)
        {
            throw new InvalidOperationException(System.SR.Format(System.SR.net_io_invalidnestedcall, callerName, "authenticate"));
        }
        try
        {
            await (_context.IsServer ? ReceiveBlobAsync(adapter) : SendBlobAsync(adapter, null)).ConfigureAwait(continueOnCapturedContext: false);
        }
        catch (Exception failed)
        {
            SetFailed(failed);
            throw;
        }
        finally
        {
            _authInProgress = 0;
        }
    }
References System.Net.Security.NegotiateStream._authInProgress, System.Net.Security.NegotiateStream._context, System.Threading.Interlocked.Exchange(), System.SR.Format(), System.Net.NTAuthentication.IsServer, System.SR.net_io_invalidnestedcall, System.Net.Security.NegotiateStream.SetFailed(), and System.Net.Security.NegotiateStream.ThrowIfFailed().