Terraria: System.Net.Security.NegotiateStream.WriteAsync< TAdapter >
WriteAsync< TAdapter >()
async Task System.Net.Security.NegotiateStream.WriteAsync< TAdapter > (TAdapter adapter, ReadOnlyMemory< byte > buffer) inline private
Type Constraints
TAdapter : IReadWriteAdapter
Definition at line 611 of file NegotiateStream.cs.
                                                                                                          : IReadWriteAdapter
    {
        if (Interlocked.Exchange(ref _writeInProgress, 1) == 1)
        {
            throw new NotSupportedException(System.SR.Format(System.SR.net_io_invalidnestedcall, "Write", "write"));
        }
        try
        {
            while (!buffer.IsEmpty)
            {
                int chunkBytes = Math.Min(buffer.Length, 64512);
                int count;
                try
                {
                    count = EncryptData(buffer.Slice(0, chunkBytes).Span, ref _writeBuffer);
                }
                catch (Exception innerException)
                {
                    throw new IOException(System.SR.net_io_encrypt, innerException);
                }
                await adapter.WriteAsync(_writeBuffer, 0, count).ConfigureAwait(continueOnCapturedContext: false);
                buffer = buffer.Slice(chunkBytes);
            }
        }
        catch (Exception ex) when (!(ex is IOException) && !(ex is OperationCanceledException))
        {
            throw new IOException(System.SR.net_io_write, ex);
        }
        finally
        {
            _writeInProgress = 0;
        }
    }
References System.Net.Security.NegotiateStream._writeBuffer, System.Net.Security.NegotiateStream._writeInProgress, System.buffer, System.count, System.Net.Security.NegotiateStream.EncryptData(), System.Threading.Interlocked.Exchange(), System.SR.Format(), System.Math.Min(), System.SR.net_io_encrypt, System.SR.net_io_invalidnestedcall, and System.SR.net_io_write.