Terraria: System.Net.Security.NegotiateStream.ValidateCreateContext
ValidateCreateContext() [2/2]
void System.Net.Security.NegotiateStream.ValidateCreateContext (string package, NetworkCredential credential, string servicePrincipalName, ExtendedProtectionPolicy policy, ProtectionLevel protectionLevel, TokenImpersonationLevel impersonationLevel) inline private
Definition at line 682 of file NegotiateStream.cs.
    {
        if (policy != null)
        {
            if (policy.CustomChannelBinding == null && policy.CustomServiceNames == null)
            {
                throw new ArgumentException(System.SR.net_auth_must_specify_extended_protection_scheme, "policy");
            }
            _extendedProtectionPolicy = policy;
        }
        else
        {
            _extendedProtectionPolicy = new ExtendedProtectionPolicy(PolicyEnforcement.Never);
        }
        ValidateCreateContext(package, isServer: true, credential, servicePrincipalName, _extendedProtectionPolicy.CustomChannelBinding, protectionLevel, impersonationLevel);
    }
References System.Net.Security.NegotiateStream._extendedProtectionPolicy, System.Security.Authentication.ExtendedProtection.ExtendedProtectionPolicy.CustomChannelBinding, System.Security.Authentication.ExtendedProtection.ExtendedProtectionPolicy.CustomServiceNames, System.SR.net_auth_must_specify_extended_protection_scheme, and System.Net.Security.NegotiateStream.ValidateCreateContext().
Referenced by System.Net.Security.NegotiateStream.AuthenticateAsClient(), System.Net.Security.NegotiateStream.AuthenticateAsClientAsync(), System.Net.Security.NegotiateStream.AuthenticateAsServer(), System.Net.Security.NegotiateStream.AuthenticateAsServerAsync(), and System.Net.Security.NegotiateStream.ValidateCreateContext().