Terraria: System.Net.Security.NegotiateStream.DecryptData
DecryptData()
int System.Net.Security.NegotiateStream.DecryptData (byte[] buffer, int offset, int count, out int newOffset) inline private
Definition at line 1003 of file NegotiateStream.cs.
    {
        ThrowIfFailed(authSuccessCheck: true);
        _readSequenceNumber++;
        return _context.Decrypt(buffer, offset, count, out newOffset, _readSequenceNumber);
    }
References System.Net.Security.NegotiateStream._context, System.Net.Security.NegotiateStream._readSequenceNumber, System.buffer, System.count, System.Net.NTAuthentication.Decrypt(), System.offset, and System.Net.Security.NegotiateStream.ThrowIfFailed().
Referenced by System.Net.Security.NegotiateStream.ReadAsync< TAdapter >().