Terraria: Terraria.Social.Base.ServerJoinRequestsManager.Add
Add()
void Terraria.Social.Base.ServerJoinRequestsManager.Add (UserJoinToServerRequest request) inline
Definition at line 33 of file ServerJoinRequestsManager.cs.
    {
        for (int num = _requests.Count - 1; num >= 0; num--)
        {
            if (_requests[num].Equals(request))
            {
                RemoveRequestAtIndex(num);
            }
        }
        _requests.Add(request);
        request.OnAccepted += delegate
        {
            RemoveRequest(request);
        };
        request.OnRejected += delegate
        {
            RemoveRequest(request);
        };
        if (this.OnRequestAdded != null)
        {
            this.OnRequestAdded(request);
        }
    }
References Terraria.Social.Base.ServerJoinRequestsManager._requests, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, Terraria.Social.Base.ServerJoinRequestsManager.OnRequestAdded, Terraria.Social.Base.ServerJoinRequestsManager.RemoveRequest(), and Terraria.Social.Base.ServerJoinRequestsManager.RemoveRequestAtIndex().