Terraria: System.Runtime.InteropServices.HandleCollector.Add
Add()
void System.Runtime.InteropServices.HandleCollector.Add () inline
Definition at line 49 of file HandleCollector.cs.
    {
        int num = -1;
        Interlocked.Increment(ref _handleCount);
        if (_handleCount < 0)
        {
            throw new InvalidOperationException(System.SR.InvalidOperation_HCCountOverflow);
        }
        if (_handleCount > _threshold)
        {
            lock (this)
            {
                _threshold = _handleCount + _handleCount / 10;
                num = _gcGeneration;
                if (_gcGeneration < 2)
                {
                    _gcGeneration++;
                }
            }
        }
        if (num >= 0 && (num == 0 || _gcCounts[num] == GC.CollectionCount(num)))
        {
            GC.Collect(num);
            Thread.Sleep(10 * num);
        }
        for (int i = 1; i < 3; i++)
        {
            _gcCounts[i] = GC.CollectionCount(i);
        }
    }
References System.Runtime.InteropServices.HandleCollector._gcCounts, System.Runtime.InteropServices.HandleCollector._gcGeneration, System.Runtime.InteropServices.HandleCollector._handleCount, System.Runtime.InteropServices.HandleCollector._threshold, System.GC.Collect(), System.GC.CollectionCount(), System.Threading.Interlocked.Increment(), System.SR.InvalidOperation_HCCountOverflow, and System.Threading.Thread.Sleep().