Terraria: System.Data.Common.Int16Storage.Aggregate
Aggregate()
override object System.Data.Common.Int16Storage.Aggregate (int[] records, AggregateType kind) inline virtual
Reimplemented from System.Data.Common.DataStorage.
Definition at line 16 of file Int16Storage.cs.
    {
        bool flag = false;
        try
        {
            switch (kind)
            {
            case AggregateType.Sum:
            {
                long num4 = 0L;
                foreach (int num5 in records)
                {
                    if (HasValue(num5))
                    {
                        num4 = checked(num4 + _values[num5]);
                        flag = true;
                    }
                }
                if (flag)
                {
                    return num4;
                }
                return _nullValue;
            }
            case AggregateType.Mean:
            {
                long num11 = 0L;
                int num12 = 0;
                foreach (int num13 in records)
                {
                    if (HasValue(num13))
                    {
                        num11 = checked(num11 + _values[num13]);
                        num12++;
                        flag = true;
                    }
                }
                checked
                {
                    if (flag)
                    {
                        short num14 = (short)unchecked(num11 / num12);
                        return num14;
                    }
                    return _nullValue;
                }
            }
            case AggregateType.Var:
            case AggregateType.StDev:
            {
                int num = 0;
                double num6 = 0.0;
                double num7 = 0.0;
                double num8 = 0.0;
                double num9 = 0.0;
                foreach (int num10 in records)
                {
                    if (HasValue(num10))
                    {
                        num8 += (double)_values[num10];
                        num9 += (double)_values[num10] * (double)_values[num10];
                        num++;
                    }
                }
                if (num > 1)
                {
                    num6 = (double)num * num9 - num8 * num8;
                    num7 = num6 / (num8 * num8);
                    num6 = ((!(num7 < 1E-15) && !(num6 < 0.0)) ? (num6 / (double)(num * (num - 1))) : 0.0);
                    if (kind == AggregateType.StDev)
                    {
                        return Math.Sqrt(num6);
                    }
                    return num6;
                }
                return _nullValue;
            }
            case AggregateType.Min:
            {
                short num2 = short.MaxValue;
                foreach (int num3 in records)
                {
                    if (HasValue(num3))
                    {
                        num2 = Math.Min(_values[num3], num2);
                        flag = true;
                    }
                }
                if (flag)
                {
                    return num2;
                }
                return _nullValue;
            }
            case AggregateType.Max:
            {
                short num15 = short.MinValue;
                foreach (int num16 in records)
                {
                    if (HasValue(num16))
                    {
                        num15 = Math.Max(_values[num16], num15);
                        flag = true;
                    }
                }
                if (flag)
                {
                    return num15;
                }
                return _nullValue;
            }
            case AggregateType.First:
                if (records.Length != 0)
                {
                    return _values[records[0]];
                }
                return null;
            case AggregateType.Count:
            {
                int num = 0;
                for (int i = 0; i < records.Length; i++)
                {
                    if (HasValue(records[i]))
                    {
                        num++;
                    }
                }
                return num;
            }
            }
        }
        catch (OverflowException)
        {
            throw ExprException.Overflow(typeof(short));
        }
        throw ExceptionBuilder.AggregateException(kind, _dataType);
    }
References System.Data.Common.DataStorage._dataType, System.Data.Common.DataStorage._nullValue, System.Data.Common.Int16Storage._values, System.Data.ExceptionBuilder.AggregateException(), System.Xml.Dictionary, System.E, System.Data.Common.DataStorage.HasValue(), System.L, System.Math.Max(), System.Math.Min(), System.Data.ExprException.Overflow(), and System.Math.Sqrt().