Terraria: System.Collections.Generic.SortedList.IndexOfKey
IndexOfKey()
int System.Collections.Generic.SortedList< TKey, TValue >.IndexOfKey (TKey key) inline
Definition at line 910 of file SortedList.cs.
    {
        if (key == null)
        {
            throw new ArgumentNullException("key");
        }
        int num = Array.BinarySearch(keys, 0, _size, key, comparer);
        if (num < 0)
        {
            return -1;
        }
        return num;
    }
References System.Collections.Generic.SortedList< TKey, TValue >._size, System.Array.BinarySearch(), System.Collections.Generic.SortedList< TKey, TValue >.comparer, System.key, and System.Collections.Generic.SortedList< TKey, TValue >.keys.
Referenced by System.Collections.Generic.SortedList< TKey, TValue >.Contains(), System.Collections.Generic.SortedList< TKey, TValue >.ContainsKey(), System.Collections.Generic.SortedList< TKey, TValue >.Remove(), System.Collections.Generic.SortedList< TKey, TValue >.Remove(), and System.Collections.Generic.SortedList< TKey, TValue >.TryGetValue().