Terraria: System.Threading.ThreadLocal.Initialize
Initialize()
void System.Threading.ThreadLocal< T >.Initialize (Func< T > valueFactory, bool trackAllValues) inline private
Definition at line 278 of file ThreadLocal.cs.
    {
        _valueFactory = valueFactory;
        _trackAllValues = trackAllValues;
        _idComplement = ~s_idManager.GetId(trackAllValues);
        _initialized = true;
    }
References System.Threading.ThreadLocal< T >._idComplement, System.Threading.ThreadLocal< T >._initialized, System.Threading.ThreadLocal< T >._trackAllValues, and System.Threading.ThreadLocal< T >._valueFactory.
Referenced by System.Threading.ThreadLocal< T >.ThreadLocal(), System.Threading.ThreadLocal< T >.ThreadLocal(), System.Threading.ThreadLocal< T >.ThreadLocal(), and System.Threading.ThreadLocal< T >.ThreadLocal().