Terraria: System.IO.Compression.Inflater.InflateVerified
InflateVerified()
unsafe int System.IO.Compression.Inflater.InflateVerified (byte * bufPtr, int length) inline
Definition at line 74 of file Inflater.cs.
    {
        try
        {
            int bytesRead = 0;
            if (_uncompressedSize == -1)
            {
                ReadOutput(bufPtr, length, out bytesRead);
            }
            else if (_uncompressedSize > _currentInflatedCount)
            {
                length = (int)Math.Min(length, _uncompressedSize - _currentInflatedCount);
                ReadOutput(bufPtr, length, out bytesRead);
                _currentInflatedCount += bytesRead;
            }
            else
            {
                _finished = true;
                _zlibStream.AvailIn = 0u;
            }
            return bytesRead;
        }
        finally
        {
            if (_zlibStream.AvailIn == 0 && IsInputBufferHandleAllocated)
            {
                DeallocateInputBufferHandle();
            }
        }
    }
References System.IO.Compression.Inflater._currentInflatedCount, System.IO.Compression.Inflater._finished, System.IO.Compression.Inflater._uncompressedSize, System.IO.Compression.Inflater._zlibStream, System.IO.Compression.Inflater.DeallocateInputBufferHandle(), System.IO.Compression.Inflater.IsInputBufferHandleAllocated, System.length, System.Math.Min(), and System.IO.Compression.Inflater.ReadOutput().
Referenced by System.IO.Compression.Inflater.Inflate(), System.IO.Compression.Inflater.Inflate(), and System.IO.Compression.Inflater.Inflate().