Terraria: System.IO.Compression.Inflater.ReadOutput
ReadOutput()
unsafe void System.IO.Compression.Inflater.ReadOutput (byte * bufPtr, int length, out int bytesRead) inline private
Definition at line 105 of file Inflater.cs.
    {
        if (ReadInflateOutput(bufPtr, length, ZLibNative.FlushCode.NoFlush, out bytesRead) == ZLibNative.ErrorCode.StreamEnd)
        {
            if (!NeedsInput() && IsGzipStream() && IsInputBufferHandleAllocated)
            {
                _finished = ResetStreamForLeftoverInput();
            }
            else
            {
                _finished = true;
            }
        }
    }
References System.IO.Compression.Inflater._finished, System.IO.Compression.Inflater.IsGzipStream(), System.IO.Compression.Inflater.IsInputBufferHandleAllocated, System.length, System.IO.Compression.Inflater.NeedsInput(), System.IO.Compression.Inflater.ReadInflateOutput(), and System.IO.Compression.Inflater.ResetStreamForLeftoverInput().
Referenced by System.IO.Compression.Inflater.InflateVerified().