Terraria: Terraria.Cloud.UpdateClouds
UpdateClouds()
static void Terraria.Cloud.UpdateClouds () inline static
    {
        if (Main.netMode == 2)
        {
            return;
        }
        int num = 0;
        for (int i = 0; i < 200; i++)
        {
            if (Main.cloud[i].active)
            {
                Main.cloud[i].Update();
                if (!Main.cloud[i].kill)
                {
                    num++;
                }
            }
        }
        for (int j = 0; j < 200; j++)
        {
            if (Main.cloud[j].active)
            {
                if (j > 1 && (!Main.cloud[j - 1].active || (double)Main.cloud[j - 1].scale > (double)Main.cloud[j].scale + 0.02))
                {
                    Cloud cloud = (Cloud)Main.cloud[j - 1].Clone();
                    Main.cloud[j - 1] = (Cloud)Main.cloud[j].Clone();
                    Main.cloud[j] = cloud;
                }
                if (j < 199 && (!Main.cloud[j].active || (double)Main.cloud[j + 1].scale < (double)Main.cloud[j].scale - 0.02))
                {
                    Cloud cloud2 = (Cloud)Main.cloud[j + 1].Clone();
                    Main.cloud[j + 1] = (Cloud)Main.cloud[j].Clone();
                    Main.cloud[j] = cloud2;
                }
            }
        }
        if (num < Main.numClouds)
        {
            addCloud();
        }
        else if (num > Main.numClouds)
        {
            int num2 = rand.Next(num);
            int num3 = 0;
            while (Main.cloud[num2].kill && num3 < 100)
            {
                num3++;
                num2 = rand.Next(num);
            }
            Main.cloud[num2].kill = true;
        }
    }
References Terraria.Cloud.active, Terraria.Cloud.addCloud(), Terraria.Cloud.Clone(), Terraria.Main.cloud, Terraria.Cloud.kill, Terraria.Main.netMode, Terraria.Utilities.UnifiedRandom.Next(), Terraria.Main.numClouds, Terraria.Cloud.rand, Terraria.Cloud.scale, and Terraria.Cloud.Update().
Referenced by Terraria.Main.DoUpdate(), and Terraria.Main.DrawMenu().