Terraria: System.IO.Compression.Inflater.DeallocateInputBufferHandle
DeallocateInputBufferHandle()
void System.IO.Compression.Inflater.DeallocateInputBufferHandle () inline private
Definition at line 269 of file Inflater.cs.
    {
        lock (SyncLock)
        {
            _zlibStream.AvailIn = 0u;
            _zlibStream.NextIn = ZLibNative.ZNullPtr;
            _inputBufferHandle.Dispose();
        }
    }
References System.IO.Compression.Inflater._inputBufferHandle, System.Buffers.MemoryHandle.Dispose(), System.IO.Compression.Inflater.SyncLock, and System.IO.Compression.ZLibNative.ZNullPtr.
Referenced by System.IO.Compression.Inflater.Dispose(), and System.IO.Compression.Inflater.InflateVerified().