Terraria: System.IO.Compression.Inflater.Dispose
Dispose() [2/2]
void System.IO.Compression.Inflater.Dispose (bool disposing) inline private
Definition at line 174 of file Inflater.cs.
    {
        if (!_isDisposed)
        {
            if (disposing)
            {
                _zlibStream.Dispose();
            }
            if (IsInputBufferHandleAllocated)
            {
                DeallocateInputBufferHandle();
            }
            _isDisposed = true;
        }
    }
References System.IO.Compression.Inflater._isDisposed, System.IO.Compression.Inflater._zlibStream, System.IO.Compression.Inflater.DeallocateInputBufferHandle(), and System.IO.Compression.Inflater.IsInputBufferHandleAllocated.
Referenced by System.IO.Compression.DeflateStream.Dispose(), and System.IO.Compression.DeflateStream.DisposeAsync().