Terraria: System.IO.Compression.Inflater.ResetStreamForLeftoverInput
ResetStreamForLeftoverInput()
unsafe bool System.IO.Compression.Inflater.ResetStreamForLeftoverInput () inline private
Definition at line 120 of file Inflater.cs.
    {
        lock (SyncLock)
        {
            IntPtr nextIn = _zlibStream.NextIn;
            byte* ptr = (byte*)nextIn.ToPointer();
            uint availIn = _zlibStream.AvailIn;
            if (*ptr != 31 || (availIn > 1 && ptr[1] != 139))
            {
                return true;
            }
            _zlibStream.Dispose();
            InflateInit(_windowBits);
            _zlibStream.NextIn = nextIn;
            _zlibStream.AvailIn = availIn;
            _finished = false;
        }
        return false;
    }
References System.IO.Compression.Inflater._finished, System.IO.Compression.Inflater._windowBits, System.IO.Compression.Inflater._zlibStream, System.IO.Compression.Inflater.InflateInit(), System.IO.Compression.Inflater.SyncLock, and System.IntPtr.ToPointer().
Referenced by System.IO.Compression.Inflater.ReadOutput().