Terraria: System.IO.Compression.Inflater.InflateInit
InflateInit()
void System.IO.Compression.Inflater.InflateInit (int windowBits) inline private
Definition at line 202 of file Inflater.cs.
    {
        ZLibNative.ErrorCode errorCode;
        try
        {
            errorCode = ZLibNative.CreateZLibStreamForInflate(out _zlibStream, windowBits);
        }
        catch (Exception innerException)
        {
            throw new ZLibException(System.SR.ZLibErrorDLLLoadError, innerException);
        }
        switch (errorCode)
        {
        case ZLibNative.ErrorCode.Ok:
            break;
        case ZLibNative.ErrorCode.MemError:
            throw new ZLibException(System.SR.ZLibErrorNotEnoughMemory, "inflateInit2_", (int)errorCode, _zlibStream.GetErrorMessage());
        case ZLibNative.ErrorCode.VersionError:
            throw new ZLibException(System.SR.ZLibErrorVersionMismatch, "inflateInit2_", (int)errorCode, _zlibStream.GetErrorMessage());
        case ZLibNative.ErrorCode.StreamError:
            throw new ZLibException(System.SR.ZLibErrorIncorrectInitParameters, "inflateInit2_", (int)errorCode, _zlibStream.GetErrorMessage());
        default:
            throw new ZLibException(System.SR.ZLibErrorUnexpected, "inflateInit2_", (int)errorCode, _zlibStream.GetErrorMessage());
        }
    }
References System.IO.Compression.Inflater._zlibStream, System.IO.Compression.ZLibNative.CreateZLibStreamForInflate(), System.SR.ZLibErrorDLLLoadError, System.SR.ZLibErrorIncorrectInitParameters, System.SR.ZLibErrorNotEnoughMemory, System.SR.ZLibErrorUnexpected, and System.SR.ZLibErrorVersionMismatch.
Referenced by System.IO.Compression.Inflater.Inflater(), and System.IO.Compression.Inflater.ResetStreamForLeftoverInput().