Terraria: UIWorkshopSelectResourcePackToPublish.PopulateEntries
PopulateEntries()
void UIWorkshopSelectResourcePackToPublish.PopulateEntries () inline
     {
         _entries.Clear();
         IOrderedEnumerable<ResourcePack> collection = from x in AssetInitializer.CreatePublishableResourcePacksList(Main.instance.Services).AllPacks
             where x.Branding == ResourcePack.BrandingType.None
             orderby x.IsCompressed
             select x;
         _entries.AddRange(collection);
         _entryList.Clear();
         int num = 0;
         foreach (ResourcePack entry in _entries)
         {
             _entryList.Add(new UIWorkshopPublishResourcePackListItem(this, entry, num++, !entry.IsCompressed));
         }
     }
References _entries, _entryList, UIList.Add(), ResourcePackList.AllPacks, UIList.Clear(), AssetInitializer.CreatePublishableResourcePacksList(), Main.instance, ResourcePack.IsCompressed, and Game.Services.
Referenced by OnActivate().