Terraria: System.Collections.Specialized.NameObjectCollectionBase.BaseSet
BaseSet() [2/2]
void System.Collections.Specialized.NameObjectCollectionBase.BaseSet (string? name, object? value) inline protected inherited
Definition at line 367 of file NameObjectCollectionBase.cs.
    {
        if (_readOnly)
        {
            throw new NotSupportedException(System.SR.CollectionReadOnly);
        }
        NameObjectEntry nameObjectEntry = FindEntry(name);
        if (nameObjectEntry != null)
        {
            nameObjectEntry.Value = value;
            _version++;
        }
        else
        {
            BaseAdd(name, value);
        }
    }
References System.Collections.Specialized.NameObjectCollectionBase._readOnly, System.Collections.Specialized.NameObjectCollectionBase._version, System.Collections.Specialized.NameObjectCollectionBase.BaseAdd(), System.SR.CollectionReadOnly, System.Runtime.Serialization.Dictionary, System.Collections.Specialized.NameObjectCollectionBase.FindEntry(), and System.value.
Referenced by System.Collections.Specialized.NameValueCollection.Set().