Terraria: System.Collections.Specialized.NameObjectCollectionBase.BaseRemove
BaseRemove()
void System.Collections.Specialized.NameObjectCollectionBase.BaseRemove (string? name) inline protected inherited
Definition at line 303 of file NameObjectCollectionBase.cs.
    {
        if (_readOnly)
        {
            throw new NotSupportedException(System.SR.CollectionReadOnly);
        }
        if (name != null)
        {
            _entriesTable.Remove(name);
            for (int num = _entriesArray.Count - 1; num >= 0; num--)
            {
                if (_keyComparer.Equals(name, BaseGetKey(num)))
                {
                    _entriesArray.RemoveAt(num);
                }
            }
        }
        else
        {
            _nullKeyEntry = null;
            for (int num2 = _entriesArray.Count - 1; num2 >= 0; num2--)
            {
                if (BaseGetKey(num2) == null)
                {
                    _entriesArray.RemoveAt(num2);
                }
            }
        }
        _version++;
    }
References System.Collections.Specialized.NameObjectCollectionBase._entriesArray, System.Collections.Specialized.NameObjectCollectionBase._entriesTable, System.Collections.Specialized.NameObjectCollectionBase._keyComparer, System.Collections.Specialized.NameObjectCollectionBase._nullKeyEntry, System.Collections.Specialized.NameObjectCollectionBase._readOnly, System.Collections.Specialized.NameObjectCollectionBase._version, System.Collections.Specialized.NameObjectCollectionBase.BaseGetKey(), System.SR.CollectionReadOnly, System.Collections.ArrayList.Count, System.Runtime.Serialization.Dictionary, System.Collections.IEqualityComparer.Equals(), System.Collections.Hashtable.Remove(), and System.Collections.ArrayList.RemoveAt().
Referenced by System.Collections.Specialized.NameValueCollection.Remove().