Terraria: System.Collections.Specialized.NameObjectCollectionBase.Reset
Reset() [1/2]
void System.Collections.Specialized.NameObjectCollectionBase.Reset () inline private inherited
Definition at line 249 of file NameObjectCollectionBase.cs.
    {
        _entriesArray = new ArrayList();
        _entriesTable = new Hashtable(_keyComparer);
        _nullKeyEntry = null;
        _version++;
    }
References System.Collections.Specialized.NameObjectCollectionBase._entriesArray, System.Collections.Specialized.NameObjectCollectionBase._entriesTable, System.Collections.Specialized.NameObjectCollectionBase._keyComparer, System.Collections.Specialized.NameObjectCollectionBase._nullKeyEntry, and System.Collections.Specialized.NameObjectCollectionBase._version.
Referenced by System.Collections.Specialized.NameObjectCollectionBase.NameObjectCollectionBase(), System.Collections.Specialized.NameObjectCollectionBase.NameObjectCollectionBase(), System.Collections.Specialized.NameObjectCollectionBase.NameObjectCollectionBase(), System.Collections.Specialized.NameObjectCollectionBase.NameObjectCollectionBase(), System.Collections.Specialized.NameObjectCollectionBase.NameObjectCollectionBase(), and System.Collections.Specialized.NameObjectCollectionBase.BaseClear().