Terraria: System.Linq.Parallel.OrderedHashRepartitionEnumerator.EnumerateAndRedistributeElements
EnumerateAndRedistributeElements()
void System.Linq.Parallel.OrderedHashRepartitionEnumerator< TInputOutput, THashKey, TOrderKey >.EnumerateAndRedistributeElements () inline private
Definition at line 113 of file OrderedHashRepartitionEnumerator.cs.
    {
        Mutables mutables = _mutables;
        ListChunk<Pair<TInputOutput, THashKey>>[] array = new ListChunk<Pair<TInputOutput, THashKey>>[_partitionCount];
        ListChunk<TOrderKey>[] array2 = new ListChunk<TOrderKey>[_partitionCount];
        TInputOutput currentElement = default(TInputOutput);
        TOrderKey currentKey = default(TOrderKey);
        int num = 0;
        while (_source.MoveNext(ref currentElement, ref currentKey))
        {
            if ((num++ & 0x3F) == 0)
            {
                _cancellationToken.ThrowIfCancellationRequested();
            }
            THashKey val = default(THashKey);
            int num2;
            if (_keySelector != null)
            {
                val = _keySelector(currentElement);
                num2 = _repartitionStream.GetHashCode(val) % _partitionCount;
            }
            else
            {
                num2 = _repartitionStream.GetHashCode(currentElement) % _partitionCount;
            }
            ListChunk<Pair<TInputOutput, THashKey>> listChunk = array[num2];
            ListChunk<TOrderKey> listChunk2 = array2[num2];
            if (listChunk == null)
            {
                listChunk = (array[num2] = new ListChunk<Pair<TInputOutput, THashKey>>(128));
                listChunk2 = (array2[num2] = new ListChunk<TOrderKey>(128));
            }
            listChunk.Add(new Pair<TInputOutput, THashKey>(currentElement, val));
            listChunk2.Add(currentKey);
        }
        for (int i = 0; i < _partitionCount; i++)
        {
            _valueExchangeMatrix[_partitionIndex][i] = array[i];
            _keyExchangeMatrix[_partitionIndex][i] = array2[i];
        }
        _barrier.Signal();
        mutables._currentBufferIndex = _partitionIndex;
        mutables._currentBuffer = array[_partitionIndex];
        mutables._currentKeyBuffer = array2[_partitionIndex];
        mutables._currentIndex = -1;
    }
References System.Linq.Parallel.OrderedHashRepartitionEnumerator< TInputOutput, THashKey, TOrderKey >._barrier, System.Linq.Parallel.OrderedHashRepartitionEnumerator< TInputOutput, THashKey, TOrderKey >._cancellationToken, System.Linq.Parallel.OrderedHashRepartitionEnumerator< TInputOutput, THashKey, TOrderKey >._keyExchangeMatrix, System.Linq.Parallel.OrderedHashRepartitionEnumerator< TInputOutput, THashKey, TOrderKey >._keySelector, System.Linq.Parallel.OrderedHashRepartitionEnumerator< TInputOutput, THashKey, TOrderKey >._mutables, System.Linq.Parallel.OrderedHashRepartitionEnumerator< TInputOutput, THashKey, TOrderKey >._partitionCount, System.Linq.Parallel.OrderedHashRepartitionEnumerator< TInputOutput, THashKey, TOrderKey >._partitionIndex, System.Linq.Parallel.OrderedHashRepartitionEnumerator< TInputOutput, THashKey, TOrderKey >._repartitionStream, System.Linq.Parallel.OrderedHashRepartitionEnumerator< TInputOutput, THashKey, TOrderKey >._source, System.Linq.Parallel.OrderedHashRepartitionEnumerator< TInputOutput, THashKey, TOrderKey >._valueExchangeMatrix, System.Linq.Parallel.ListChunk< TInputOutput >.Add(), System.array, System.Linq.Parallel.QueryOperatorEnumerator< TElement, TKey >.MoveNext(), System.Threading.CountdownEvent.Signal(), and System.Threading.CancellationToken.ThrowIfCancellationRequested().
Referenced by System.Linq.Parallel.OrderedHashRepartitionEnumerator< TInputOutput, THashKey, TOrderKey >.MoveNext().