Terraria: CreativePowersHelper.UpdateUnlockStateByPowerInternal
UpdateUnlockStateByPowerInternal()
static void CreativePowersHelper.UpdateUnlockStateByPowerInternal (ICreativePower power, Color colorWhenSelected, IGroupOptionButton asButton) inline static private
     {
         bool isUnlocked = power.GetIsUnlocked();
         bool flag = !IsAvailableForPlayer(power, Main.myPlayer);
         asButton.SetBorderColor(flag ? Color.DimGray : Color.White);
         if (flag)
         {
             asButton.SetColorsBasedOnSelectionState(new Color(60, 60, 60), new Color(60, 60, 60), 0.7f, 0.7f);
         }
         else if (isUnlocked)
         {
             asButton.SetColorsBasedOnSelectionState(colorWhenSelected, Colors.InventoryDefaultColor, 1f, 0.7f);
         }
         else
         {
             asButton.SetColorsBasedOnSelectionState(Color.Crimson, Color.Red, 0.7f, 0.7f);
         }
     }
References Color, ICreativePower.GetIsUnlocked(), Colors.InventoryDefaultColor, IsAvailableForPlayer(), Main.myPlayer, IGroupOptionButton.SetBorderColor(), and IGroupOptionButton.SetColorsBasedOnSelectionState().
Referenced by UpdateUnlockStateByPower().