Terraria: CreativePowersHelper.UpdateUseMouseInterface
UpdateUseMouseInterface()
static void CreativePowersHelper.UpdateUseMouseInterface (UIElement affectedElement) inline static
     {
         if (affectedElement.IsMouseHovering)
         {
             Main.LocalPlayer.mouseInterface = true;
         }
     }
References UIElement.IsMouseHovering, Main.LocalPlayer, and Player.mouseInterface.
Referenced by CreativePowers.ModifyTimeRate.ProvideSlider(), CreativePowers.DifficultySliderPower.ProvideSlider(), CreativePowers.ModifyWindDirectionAndStrength.ProvideSlider(), CreativePowers.ModifyRainPower.ProvideSlider(), and CreativePowers.SpawnRateSliderPerPlayerPower.ProvideSlider().