Terraria: DD2Event.SpawnMonsterFromGate
SpawnMonsterFromGate()
static void DD2Event.SpawnMonsterFromGate (Vector2 gateBottom) inline static
     {
         switch (OngoingDifficulty)
         {
         case 3:
             Difficulty_3_SpawnMonsterFromGate(gateBottom);
             break;
         case 2:
             Difficulty_2_SpawnMonsterFromGate(gateBottom);
             break;
         default:
             Difficulty_1_SpawnMonsterFromGate(gateBottom);
             break;
         }
     }
References Difficulty_1_SpawnMonsterFromGate(), Difficulty_2_SpawnMonsterFromGate(), Difficulty_3_SpawnMonsterFromGate(), and OngoingDifficulty.
Referenced by NPC.AI().