Terraria: DD2Event.AttemptToSkipWaitTime
AttemptToSkipWaitTime()
static void DD2Event.AttemptToSkipWaitTime () inline static
     {
         if (Main.netMode != 1 && TimeLeftBetweenWaves > 60)
         {
             SetEnemySpawningOnHold(60);
         }
     }
References Main.netMode, SetEnemySpawningOnHold(), and TimeLeftBetweenWaves.
Referenced by MessageBuffer.GetData(), and RequestToSkipWaitTime().