Terraria: DD2Event.FailureMessage
FailureMessage()
static void DD2Event.FailureMessage (int client) inline static
     {
         LocalizedText text = Language.GetText("DungeonDefenders2.BartenderWarning");
         Color color = new Color(255, 255, 0);
         if (Main.netMode == 2)
         {
             ChatHelper.SendChatMessageToClient(NetworkText.FromKey(text.Key), color, client);
         }
         else
         {
             Main.NewText(text.Value, color.R, color.G, color.B);
         }
     }
References Color, NetworkText.FromKey(), Language.GetText(), LocalizedText.Key, Main.netMode, Main.NewText(), ChatHelper.SendChatMessageToClient(), and LocalizedText.Value.
Referenced by MessageBuffer.GetData(), and Player.TileInteractionsUse().