Terraria: DD2Event.UpdateTime
UpdateTime()
static void DD2Event.UpdateTime () inline static
     {
         if (!Ongoing && !Main.dedServ)
         {
             Filters.Scene.Deactivate("CrystalDestructionVortex");
             Filters.Scene.Deactivate("CrystalDestructionColor");
             Filters.Scene.Deactivate("CrystalWin");
             return;
         }
         if (Main.netMode != 1 && !NPC.AnyNPCs(548))
         {
             StopInvasion();
         }
         if (Main.netMode == 1)
         {
             if (_timeLeftUntilSpawningBegins > 0)
             {
                 _timeLeftUntilSpawningBegins--;
             }
             if (_timeLeftUntilSpawningBegins < 0)
             {
                 _timeLeftUntilSpawningBegins = 0;
             }
             return;
         }
         if (_timeLeftUntilSpawningBegins > 0)
         {
             _timeLeftUntilSpawningBegins--;
             if (_timeLeftUntilSpawningBegins == 0)
             {
                 GetInvasionStatus(out var currentWave, out var requiredKillCount, out var currentKillCount);
                 if (!LostThisRun)
                 {
                     WorldGen.BroadcastText(Lang.GetInvasionWaveText(currentWave, GetEnemiesForWave(currentWave)), INFO_NEW_WAVE_COLOR);
                     if (currentWave == 7 && OngoingDifficulty == 3)
                     {
                         SummonBetsy();
                     }
                 }
                 else
                 {
                     LoseInvasionMessage();
                 }
                 if (Main.netMode != 1)
                 {
                     Main.ReportInvasionProgress(currentKillCount, requiredKillCount, 3, currentWave);
                 }
                 if (Main.netMode == 2)
                 {
                     NetMessage.SendData(78, -1, -1, null, Main.invasionProgress, Main.invasionProgressMax, 3f, currentWave);
                 }
             }
         }
         if (_timeLeftUntilSpawningBegins < 0)
         {
             _timeLeftUntilSpawningBegins = 0;
         }
     }
References _timeLeftUntilSpawningBegins, NPC.AnyNPCs(), WorldGen.BroadcastText(), EffectManager< T >.Deactivate(), Main.dedServ, GetEnemiesForWave(), GetInvasionStatus(), Lang.GetInvasionWaveText(), INFO_NEW_WAVE_COLOR, Main.invasionProgress, Main.invasionProgressMax, LoseInvasionMessage(), LostThisRun, Main.netMode, Ongoing, OngoingDifficulty, Main.ReportInvasionProgress(), Filters.Scene, NetMessage.SendData(), StopInvasion(), and SummonBetsy().
Referenced by Main.UpdateTime().