Terraria: DD2Event.WouldFailSpawningHere
WouldFailSpawningHere()
static bool DD2Event.WouldFailSpawningHere (int x, int y) inline static
     {
         StrayMethods.CheckArenaScore(new Point(x, y).ToWorldCoordinates(), out var xLeftEnd, out var xRightEnd);
         int num = xRightEnd.X - x;
         int num2 = x - xLeftEnd.X;
         if (num < 60 || num2 < 60)
         {
             return true;
         }
         return false;
     }
References StrayMethods.CheckArenaScore().
Referenced by MessageBuffer.GetData(), and Player.TileInteractionsUse().