Terraria: DD2Event.GetMonsterPointsWorth
GetMonsterPointsWorth()
static int DD2Event.GetMonsterPointsWorth (int slainMonsterID) inline static private
     {
         return OngoingDifficulty switch
         {
             3 => Difficulty_3_GetMonsterPointsWorth(slainMonsterID),
             2 => Difficulty_2_GetMonsterPointsWorth(slainMonsterID),
             _ => Difficulty_1_GetMonsterPointsWorth(slainMonsterID),
         };
     }
References Difficulty_1_GetMonsterPointsWorth(), Difficulty_2_GetMonsterPointsWorth(), Difficulty_3_GetMonsterPointsWorth(), and OngoingDifficulty.
Referenced by CheckProgress().