Terraria: DD2Event.StopInvasion
StopInvasion()
static void DD2Event.StopInvasion (bool win = false) inline static
     {
         if (Ongoing)
         {
             if (win)
             {
                 WinInvasionInternal();
             }
             Ongoing = false;
             _deadGoblinSpots.Clear();
             if (Main.netMode != 1)
             {
                 NPC.totalInvasionPoints = 0f;
                 NPC.waveKills = 0f;
                 NPC.waveNumber = 0;
                 WipeEntities();
                 NetMessage.SendData(7);
             }
         }
     }
References _deadGoblinSpots, Main.netMode, Ongoing, NetMessage.SendData(), NPC.totalInvasionPoints, NPC.waveKills, NPC.waveNumber, WinInvasionInternal(), and WipeEntities().
Referenced by NPC.AI(), and UpdateTime().