Terraria: System.Drawing.Color.CheckByte
CheckByte()
static void System.Drawing.Color.CheckByte (int value, string name) inline static private
Definition at line 400 of file Color.cs.
    {
        if ((uint)value > 255u)
        {
            ThrowOutOfByteRange(value, name);
        }
        static void ThrowOutOfByteRange(int v, string n)
        {
            throw new ArgumentException(System.SR.Format(System.SR.InvalidEx2BoundArgument, n, v, (byte)0, byte.MaxValue));
        }
    }
References System.SR.Format(), System.SR.InvalidEx2BoundArgument, System.Drawing.Color.name, and System.Drawing.Color.value.
Referenced by System.Drawing.Color.FromArgb(), and System.Drawing.Color.FromArgb().