Terraria: System.Drawing.Color.FromKnownColor
FromKnownColor()
static Color System.Drawing.Color.FromKnownColor (KnownColor color) inline static
Definition at line 442 of file Color.cs.
    {
        if (color > (KnownColor)0 && color <= KnownColor.RebeccaPurple)
        {
            return new Color(color);
        }
        return FromName(color.ToString());
    }
References System.Drawing.Color.Color(), and System.Drawing.Color.FromName().
Referenced by System.Drawing.KnownColorTable.ArgbToKnownColor(), System.Drawing.ColorTranslator.FromOle(), and System.Drawing.ColorTranslator.InitializeHtmlSysColorTable().