Terraria: System.Drawing.Color.FromName
FromName()
static Color System.Drawing.Color.FromName (string name) inline static
Definition at line 451 of file Color.cs.
    {
        if (ColorTable.TryGetNamedColor(name, out var result))
        {
            return result;
        }
        return new Color(0L, 8, name, (KnownColor)0);
    }
References System.Drawing.Color.Color(), System.L, System.Drawing.Color.name, and System.Drawing.ColorTable.TryGetNamedColor().
Referenced by System.Drawing.ColorConverterCommon.ConvertFromString(), and System.Drawing.Color.FromKnownColor().