Terraria: NetServerSocialModule.Initialize
Initialize() [2/2]
override void NetServerSocialModule.Initialize () inline virtual
Implements NetSocialModule.
     {
         base.Initialize();
         _mode |= ServerMode.Lobby;
         RegisterRailEvent();
         _reader.SetReadEvent(OnPacketRead);
         if (Program.LaunchParameters.ContainsKey("-lobby"))
         {
             _mode |= ServerMode.Lobby;
             string text = Program.LaunchParameters["-lobby"];
             if (!(text == "private"))
             {
                 if (text == "friends")
                 {
                     _mode |= ServerMode.FriendsCanJoin;
                     _lobby.Create(inviteOnly: false);
                 }
                 else
                 {
                     Console.WriteLine(Language.GetTextValue("Error.InvalidLobbyFlag", "private", "friends"));
                 }
             }
             else
             {
                 _lobby.Create(inviteOnly: true);
             }
         }
         if (Program.LaunchParameters.ContainsKey("-friendsoffriends"))
         {
             _mode |= ServerMode.FriendsOfFriends;
         }
         _client.Init("WeGame.Terraria.Message.Client", "WeGame.Terraria.Message.Server");
         _client.OnConnected += OnConnected;
         _client.OnMessage += OnWegameMessage;
         CoreSocialModule.OnTick += _client.Tick;
         _client.Start();
     }
References _client, NetSocialModule._lobby, _mode, NetSocialModule._reader, Lobby.Create(), Language.GetTextValue(), MessageDispatcherClient.Init(), Program.LaunchParameters, MessageDispatcherClient.OnConnected, OnConnected(), MessageDispatcherClient.OnMessage, OnPacketRead(), CoreSocialModule.OnTick, OnWegameMessage(), RegisterRailEvent(), SteamP2PReader.SetReadEvent(), MessageDispatcherClient.Start(), and MessageDispatcherClient.Tick().