Terraria: NetServerSocialModule.OnCreateSessionRequest
OnCreateSessionRequest()
void NetServerSocialModule.OnCreateSessionRequest (CreateSessionRequest data) inline private
     {
         if (!_acceptingClients)
         {
             WeGameHelper.WriteDebugString(" - Ignoring connection from " + ((RailComparableID)data.remote_peer).id_ + " while _acceptionClients is false.");
             return;
         }
         if (!_mode.HasFlag(ServerMode.FriendsOfFriends) && !IsWeGameFriend(data.remote_peer))
         {
             WeGameHelper.WriteDebugString("Ignoring connection from " + ((RailComparableID)data.remote_peer).id_ + ". Friends of friends is disabled.");
             return;
         }
         WeGameHelper.WriteDebugString("pass wegame friend check");
         AcceptAnUserSession(data.local_peer, data.remote_peer);
         _connectionStateMap[data.remote_peer] = ConnectionState.Authenticating;
         if (_connectionAcceptedCallback != null)
         {
             _connectionAcceptedCallback(new SocialSocket(new WeGameAddress(data.remote_peer, "")));
         }
     }
References _acceptingClients, _connectionAcceptedCallback, NetSocialModule._connectionStateMap, _mode, AcceptAnUserSession(), IsWeGameFriend(), and WeGameHelper.WriteDebugString().
Referenced by OnRailEvent().