Terraria: NetServerSocialModule.OnPacketRead
OnPacketRead() [2/2]
bool NetServerSocialModule.OnPacketRead (byte[] data, int size, RailID user) inline private
     {
         if (!IsActiveUser(user))
         {
             WeGameHelper.WriteDebugString("OnPacketRead IsActiveUser false");
             return false;
         }
         ConnectionState connectionState = _connectionStateMap[user];
         if (connectionState == ConnectionState.Authenticating)
         {
             if (!TryAuthUserByRecvData(user, data, size))
             {
                 CloseAndUpdateUserState(user);
             }
             else
             {
                 OnAuthSuccess(user);
             }
             return false;
         }
         return connectionState == ConnectionState.Connected;
     }
References NetSocialModule._connectionStateMap, CloseAndUpdateUserState(), IsActiveUser(), OnAuthSuccess(), TryAuthUserByRecvData(), and WeGameHelper.WriteDebugString().