Terraria: NetServerSocialModule.OnPacketRead
OnPacketRead() [1/2]
bool NetServerSocialModule.OnPacketRead (byte[] data, int length, CSteamID userId) inline private
     {
         //IL_0006: Unknown result type (might be due to invalid IL or missing references)
         //IL_001e: Unknown result type (might be due to invalid IL or missing references)
         //IL_001f: Unknown result type (might be due to invalid IL or missing references)
         //IL_0025: Unknown result type (might be due to invalid IL or missing references)
         //IL_0031: Unknown result type (might be due to invalid IL or missing references)
         //IL_0014: Unknown result type (might be due to invalid IL or missing references)
         //IL_003f: Unknown result type (might be due to invalid IL or missing references)
         //IL_004f: Unknown result type (might be due to invalid IL or missing references)
         //IL_0095: Unknown result type (might be due to invalid IL or missing references)
         //IL_0096: Unknown result type (might be due to invalid IL or missing references)
         //IL_009b: Unknown result type (might be due to invalid IL or missing references)
         //IL_009c: Unknown result type (might be due to invalid IL or missing references)
         //IL_00ba: Expected I4, but got Unknown
         //IL_00c2: Unknown result type (might be due to invalid IL or missing references)
         //IL_00ed: Unknown result type (might be due to invalid IL or missing references)
         //IL_00d2: Unknown result type (might be due to invalid IL or missing references)
         //IL_00f6: Unknown result type (might be due to invalid IL or missing references)
         //IL_00e4: Unknown result type (might be due to invalid IL or missing references)
         //IL_00db: Unknown result type (might be due to invalid IL or missing references)
         if (!_connectionStateMap.ContainsKey(userId) || _connectionStateMap[userId] == ConnectionState.Inactive)
         {
             P2PSessionRequest_t result = default(P2PSessionRequest_t);
             result.m_steamIDRemote = userId;
             OnP2PSessionRequest(result);
             if (!_connectionStateMap.ContainsKey(userId) || _connectionStateMap[userId] == ConnectionState.Inactive)
             {
                 return false;
             }
         }
         ConnectionState connectionState = _connectionStateMap[userId];
         if (connectionState == ConnectionState.Authenticating)
         {
             if (length < 3)
             {
                 return false;
             }
             if (((data[1] << 8) | data[0]) != length)
             {
                 return false;
             }
             if (data[2] != 93)
             {
                 return false;
             }
             byte[] array = new byte[data.Length - 3];
             Array.Copy(data, 3, array, 0, array.Length);
             EBeginAuthSessionResult val = SteamUser.BeginAuthSession(array, array.Length, userId);
             switch ((int)val)
             {
             case 0:
                 _connectionStateMap[userId] = ConnectionState.Connected;
                 BroadcastConnectedUsers();
                 break;
             case 2:
                 Close(userId);
                 break;
             case 5:
                 Close(userId);
                 break;
             case 4:
                 Close(userId);
                 break;
             case 1:
                 Close(userId);
                 break;
             case 3:
                 Close(userId);
                 break;
             }
             return false;
         }
         return connectionState == ConnectionState.Connected;
     }
References NetSocialModule._connectionStateMap, BroadcastConnectedUsers(), Close(), and OnP2PSessionRequest().
Referenced by Initialize().