Terraria: Terraria.Social.WeGame.AchievementsSocialModule.GetMyPlayerAchievement
GetMyPlayerAchievement()
IRailPlayerAchievement Terraria.Social.WeGame.AchievementsSocialModule.GetMyPlayerAchievement () inline private
Definition at line 68 of file AchievementsSocialModule.cs.
    {
        //IL_0016: Unknown result type (might be due to invalid IL or missing references)
        //IL_001c: Expected O, but got Unknown
        if (_playerAchievement == null)
        {
            IRailAchievementHelper val = rail_api.RailFactory().RailAchievementHelper();
            if (val != null)
            {
                RailID val2 = new RailID();
                ((RailComparableID)val2).id_ = 0uL;
                _playerAchievement = val.CreatePlayerAchievement(val2);
            }
        }
        return _playerAchievement;
    }
References Terraria.Social.WeGame.AchievementsSocialModule._playerAchievement.
Referenced by Terraria.Social.WeGame.AchievementsSocialModule.CompleteAchievement(), Terraria.Social.WeGame.AchievementsSocialModule.Initialize(), Terraria.Social.WeGame.AchievementsSocialModule.IsAchievementCompleted(), and Terraria.Social.WeGame.AchievementsSocialModule.SaveAchievement().