Terraria: Terraria.Social.WeGame.AchievementsSocialModule.Initialize
Initialize()
override void Terraria.Social.WeGame.AchievementsSocialModule.Initialize () inline
Implements Terraria.Social.ISocialModule.
Definition at line 22 of file AchievementsSocialModule.cs.
    {
        //IL_0012: Unknown result type (might be due to invalid IL or missing references)
        //IL_001c: Expected O, but got Unknown
        //IL_002e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0038: Expected O, but got Unknown
        //IL_0052: Unknown result type (might be due to invalid IL or missing references)
        //IL_005e: Unknown result type (might be due to invalid IL or missing references)
        _callbackHelper.RegisterCallback((RAILEventID)2001, new RailEventCallBackHandler(RailEventCallBack));
        _callbackHelper.RegisterCallback((RAILEventID)2101, new RailEventCallBackHandler(RailEventCallBack));
        IRailPlayerStats myPlayerStats = GetMyPlayerStats();
        IRailPlayerAchievement myPlayerAchievement = GetMyPlayerAchievement();
        if (myPlayerStats != null && myPlayerAchievement != null)
        {
            myPlayerStats.AsyncRequestStats("");
            myPlayerAchievement.AsyncRequestAchievement("");
            while (!_areStatsReceived && !_areAchievementReceived)
            {
                CoreSocialModule.RailEventTick();
                Thread.Sleep(10);
            }
        }
    }
References Terraria.Social.WeGame.AchievementsSocialModule._areAchievementReceived, Terraria.Social.WeGame.AchievementsSocialModule._areStatsReceived, Terraria.Social.WeGame.AchievementsSocialModule._callbackHelper, Terraria.Social.WeGame.AchievementsSocialModule.GetMyPlayerAchievement(), Terraria.Social.WeGame.AchievementsSocialModule.GetMyPlayerStats(), Terraria.Social.WeGame.AchievementsSocialModule.RailEventCallBack(), and Terraria.Social.WeGame.CoreSocialModule.RailEventTick().