Terraria: Terraria.SceneMetrics.ScanAndExportToMain
ScanAndExportToMain()
void Terraria.SceneMetrics.ScanAndExportToMain (SceneMetricsScanSettings settings) inline
Definition at line 148 of file SceneMetrics.cs.
    {
        Reset();
        int num = 0;
        int num2 = 0;
        int num3 = 0;
        if (settings.ScanOreFinderData)
        {
            _oreFinderTileLocations.Clear();
        }
        if (settings.BiomeScanCenterPositionInWorld.HasValue)
        {
            Point point = settings.BiomeScanCenterPositionInWorld.Value.ToTileCoordinates();
            Rectangle tileRectangle = new Rectangle(point.X - Main.buffScanAreaWidth / 2, point.Y - Main.buffScanAreaHeight / 2, Main.buffScanAreaWidth, Main.buffScanAreaHeight);
            tileRectangle = WorldUtils.ClampToWorld(tileRectangle);
            for (int i = tileRectangle.Left; i < tileRectangle.Right; i++)
            {
                for (int j = tileRectangle.Top; j < tileRectangle.Bottom; j++)
                {
                    if (!tileRectangle.Contains(i, j))
                    {
                        continue;
                    }
                    Tile tile = Main.tile[i, j];
                    if (tile == null)
                    {
                        continue;
                    }
                    if (!tile.active())
                    {
                        if (tile.liquid > 0)
{
                            _liquidCounts[tile.liquidType()]++;
                        }
                        continue;
                    }
                    tileRectangle.Contains(i, j);
                    if (!TileID.Sets.isDesertBiomeSand[tile.type] || !WorldGen.oceanDepths(i, j))
                    {
                        _tileCounts[tile.type]++;
                    }
                    if (tile.type == 215 && tile.frameY < 36)
                    {
                        HasCampfire = true;
                    }
                    if (tile.type == 49 && tile.frameX < 18)
                    {
                        num++;
                    }
                    if (tile.type == 372 && tile.frameX < 18)
                    {
                        num2++;
                    }
                    if (tile.type == 646 && tile.frameX < 18)
                    {
                        num3++;
                    }
                    if (tile.type == 405 && tile.frameX < 54)
                    {
                        HasCampfire = true;
                    }
                    if (tile.type == 506 && tile.frameX < 72)
                    {
                        HasCatBast = true;
                    }
                    if (tile.type == 42 && tile.frameY >= 324 && tile.frameY <= 358)
                    {
                        HasHeartLantern = true;
                    }
                    if (tile.type == 42 && tile.frameY >= 252 && tile.frameY <= 286)
                    {
                        HasStarInBottle = true;
                    }
                    if (tile.type == 91 && (tile.frameX >= 396 || tile.frameY >= 54))
                    {
                        int num4 = tile.frameX / 18 - 21;
                        for (int num5 = tile.frameY; num5 >= 54; num5 -= 54)
{
                            num4 += 90;
                            num4 += 21;
                        }
                        int num6 = Item.BannerToItem(num4);
                        if (ItemID.Sets.BannerStrength.IndexInRange(num6) && ItemID.Sets.BannerStrength[num6].Enabled)
{
                            NPCBannerBuff[num4] = true;
                            hasBanner = true;
                        }
                    }
                    if (settings.ScanOreFinderData && Main.tileOreFinderPriority[tile.type] != 0)
                    {
                        _oreFinderTileLocations.Add(new Point(i, j));
                    }
                }
            }
        }
        if (settings.VisualScanArea.HasValue)
        {
            Rectangle rectangle = WorldUtils.ClampToWorld(settings.VisualScanArea.Value);
            for (int k = rectangle.Left; k < rectangle.Right; k++)
            {
                for (int l = rectangle.Top; l < rectangle.Bottom; l++)
                {
                    Tile tile2 = Main.tile[k, l];
                    if (tile2 == null || !tile2.active())
                    {
                        continue;
                    }
                    if (tile2.type == 104)
                    {
                        HasClock = true;
                    }
                    switch (tile2.type)
                    {
                    case 139:
                        if (tile2.frameX >= 36)
{
                            ActiveMusicBox = tile2.frameY / 36;
                        }
                        break;
                    case 207:
                        if (tile2.frameY >= 72)
{
                            switch (tile2.frameX / 36)
{
                            case 0:
                                ActiveFountainColor = 0;
                                break;
                            case 1:
                                ActiveFountainColor = 12;
                                break;
                            case 2:
                                ActiveFountainColor = 3;
                                break;
                            case 3:
                                ActiveFountainColor = 5;
                                break;
                            case 4:
                                ActiveFountainColor = 2;
                                break;
                            case 5:
                                ActiveFountainColor = 10;
                                break;
                            case 6:
                                ActiveFountainColor = 4;
                                break;
                            case 7:
                                ActiveFountainColor = 9;
                                break;
                            case 8:
                                ActiveFountainColor = 8;
                                break;
                            case 9:
                                ActiveFountainColor = 6;
                                break;
                            default:
                                ActiveFountainColor = -1;
                                break;
                            }
                        }
                        break;
                    case 410:
                        if (tile2.frameY >= 56)
{
                            int activeMonolithType = tile2.frameX / 36;
                            ActiveMonolithType = activeMonolithType;
                        }
                        break;
                    case 509:
                        if (tile2.frameY >= 56)
{
                            ActiveMonolithType = 4;
                        }
                        break;
                    case 480:
                        if (tile2.frameY >= 54)
{
                            BloodMoonMonolith = true;
                        }
                        break;
                    case 657:
                        if (tile2.frameY >= 54)
{
                            EchoMonolith = true;
                        }
                        break;
                    case 658:
                    {
                        int shimmerMonolithState = tile2.frameY / 54;
                        ShimmerMonolithState = shimmerMonolithState;
                        break;
                    }
                    }
                }
            }
        }
        WaterCandleCount = num;
        PeaceCandleCount = num2;
        ShadowCandleCount = num3;
        ExportTileCountsToMain();
        CanPlayCreditsRoll = ActiveMusicBox == 85;
        if (settings.ScanOreFinderData)
        {
            UpdateOreFinderData();
        }
    }
References Terraria.SceneMetrics._liquidCounts, Terraria.SceneMetrics._oreFinderTileLocations, Terraria.SceneMetrics._tileCounts, Terraria.Tile.active(), Terraria.SceneMetrics.ActiveFountainColor, Terraria.SceneMetrics.ActiveMonolithType, Terraria.SceneMetrics.ActiveMusicBox, System.Collections.Generic.List< T >.Add(), Terraria.ID.ItemID.Sets.BannerStrength, Terraria.Item.BannerToItem(), Terraria.SceneMetricsScanSettings.BiomeScanCenterPositionInWorld, Terraria.SceneMetrics.BloodMoonMonolith, Terraria.Main.buffScanAreaHeight, Terraria.Main.buffScanAreaWidth, Terraria.SceneMetrics.CanPlayCreditsRoll, Terraria.WorldBuilding.WorldUtils.ClampToWorld(), System.Collections.Generic.List< T >.Clear(), System.Collections.Generic.Dictionary< TKey, TValue >.Contains(), Terraria.SceneMetrics.EchoMonolith, Terraria.SceneMetrics.ExportTileCountsToMain(), Terraria.Tile.frameX, Terraria.Tile.frameY, Terraria.SceneMetrics.hasBanner, Terraria.SceneMetrics.HasCampfire, Terraria.SceneMetrics.HasCatBast, Terraria.SceneMetrics.HasClock, Terraria.SceneMetrics.HasHeartLantern, Terraria.SceneMetrics.HasStarInBottle, Terraria.ID.TileID.Sets.isDesertBiomeSand, Terraria.Tile.liquid, Terraria.Tile.liquidType(), Terraria.SceneMetrics.NPCBannerBuff, Terraria.WorldGen.oceanDepths(), Terraria.SceneMetrics.PeaceCandleCount, Terraria.SceneMetrics.Reset(), Terraria.SceneMetricsScanSettings.ScanOreFinderData, Terraria.SceneMetrics.ShadowCandleCount, Terraria.SceneMetrics.ShimmerMonolithState, Terraria.Main.tile, Terraria.Main.tileOreFinderPriority, Terraria.Tile.type, Terraria.SceneMetrics.UpdateOreFinderData(), Terraria.SceneMetricsScanSettings.VisualScanArea, Terraria.SceneMetrics.WaterCandleCount, Microsoft.Xna.Framework.Point.X, and Microsoft.Xna.Framework.Point.Y.
Referenced by Terraria.GameContent.TeleportPylonsSystem.HandleTeleportRequest().