Terraria: Extensions.EnumerationExtensions._Value._Value
_Value()
Extensions.EnumerationExtensions._Value._Value (object value, Type type) inline
Definition at line 17 of file EnumerationExtensions.cs.
        {
            if (!type.IsEnum)
            {
                throw new ArgumentException("Value provided is not an enumerated type!");
            }
            Type underlyingType = Enum.GetUnderlyingType(type);
            if (underlyingType.Equals(_UInt32) || underlyingType.Equals(_UInt64))
            {
                Unsigned = Convert.ToUInt64(value);
            }
            else
            {
                Signed = Convert.ToInt64(value);
            }
        }
References Extensions.EnumerationExtensions._Value._UInt32, Extensions.EnumerationExtensions._Value._UInt64, System.Type.Equals(), System.Enum.GetUnderlyingType(), Extensions.EnumerationExtensions._Value.Signed, System.Convert.ToInt64(), System.Convert.ToUInt64(), System.type, Extensions.EnumerationExtensions._Value.Unsigned, and System.value.