Terraria: Terraria.UI.CalculatedStyle.Position
Position()
Vector2 Terraria.UI.CalculatedStyle.Position () inline
Definition at line 28 of file CalculatedStyle.cs.
    {
        return new Vector2(X, Y);
    }
References Terraria.UI.CalculatedStyle.X, and Terraria.UI.CalculatedStyle.Y.
Referenced by Terraria.UI.SnapPoint.Calculate(), Terraria.GameContent.UI.Elements.UIList.UIInnerList.DrawChildren(), Terraria.UI.UIElement.DrawDebugHitbox(), Terraria.GameContent.UI.Elements.UIBestiaryInfoLine< T >.DrawSelf(), Terraria.GameContent.UI.Elements.UIText.DrawSelf(), Terraria.GameContent.UI.Elements.UITextBox.DrawSelf(), Terraria.GameContent.UI.Elements.UITextPanel< T >.DrawText(), and Terraria.GameContent.UI.Elements.UIDynamicItemCollection.GetSnapPoints().