Terraria: System.Reflection.Emit.ModuleBuilder.GetFieldTokenNoLock
GetFieldTokenNoLock()
int System.Reflection.Emit.ModuleBuilder.GetFieldTokenNoLock (FieldInfo field) inline private
Definition at line 1065 of file ModuleBuilder.cs.
    {
        if (field == null)
        {
            throw new ArgumentNullException("field");
        }
        int num = 0;
        int tokenFromTypeSpec;
        if (field is FieldBuilder fieldBuilder)
        {
            if (field.DeclaringType != null && field.DeclaringType.IsGenericType)
            {
                int length;
                byte[] signature = SignatureHelper.GetTypeSigToken(this, field.DeclaringType).InternalGetSignature(out length);
                tokenFromTypeSpec = GetTokenFromTypeSpec(signature, length);
                return GetMemberRef(this, tokenFromTypeSpec, fieldBuilder.MetadataToken);
            }
            if (fieldBuilder.Module.Equals(this))
            {
                return fieldBuilder.MetadataToken;
            }
            if (field.DeclaringType == null)
            {
                throw new InvalidOperationException(SR.InvalidOperation_CannotImportGlobalFromDifferentModule);
            }
            tokenFromTypeSpec = GetTypeTokenInternal(field.DeclaringType);
            return GetMemberRef(field.ReflectedType.Module, tokenFromTypeSpec, fieldBuilder.MetadataToken);
        }
        if (field is RuntimeFieldInfo runtimeField)
        {
            if (field.DeclaringType == null)
            {
                throw new InvalidOperationException(SR.InvalidOperation_CannotImportGlobalFromDifferentModule);
            }
            if (field.DeclaringType != null && field.DeclaringType.IsGenericType)
            {
                int length2;
                byte[] signature2 = SignatureHelper.GetTypeSigToken(this, field.DeclaringType).InternalGetSignature(out length2);
                tokenFromTypeSpec = GetTokenFromTypeSpec(signature2, length2);
                return GetMemberRefOfFieldInfo(tokenFromTypeSpec, field.DeclaringType.GetTypeHandleInternal(), runtimeField);
            }
            tokenFromTypeSpec = GetTypeTokenInternal(field.DeclaringType);
            return GetMemberRefOfFieldInfo(tokenFromTypeSpec, field.DeclaringType.GetTypeHandleInternal(), runtimeField);
        }
        if (field is FieldOnTypeBuilderInstantiation { FieldInfo: var fieldInfo } fieldOnTypeBuilderInstantiation)
        {
            int length3;
            byte[] signature3 = SignatureHelper.GetTypeSigToken(this, field.DeclaringType).InternalGetSignature(out length3);
            tokenFromTypeSpec = GetTokenFromTypeSpec(signature3, length3);
            return GetMemberRef(fieldInfo.ReflectedType.Module, tokenFromTypeSpec, fieldOnTypeBuilderInstantiation.MetadataToken);
        }
        tokenFromTypeSpec = GetTypeTokenInternal(field.ReflectedType);
        SignatureHelper fieldSigHelper = SignatureHelper.GetFieldSigHelper(this);
        fieldSigHelper.AddArgument(field.FieldType, field.GetRequiredCustomModifiers(), field.GetOptionalCustomModifiers());
        int length4;
        byte[] signature4 = fieldSigHelper.InternalGetSignature(out length4);
        return GetMemberRefFromSignature(tokenFromTypeSpec, field.Name, signature4, length4);
    }
References System.Reflection.Emit.SignatureHelper.GetFieldSigHelper(), System.Reflection.Emit.ModuleBuilder.GetMemberRef(), System.Reflection.Emit.ModuleBuilder.GetMemberRefFromSignature(), System.Reflection.Emit.ModuleBuilder.GetMemberRefOfFieldInfo(), System.Reflection.Emit.ModuleBuilder.GetTokenFromTypeSpec(), System.Reflection.Emit.SignatureHelper.GetTypeSigToken(), System.Reflection.Emit.ModuleBuilder.GetTypeTokenInternal(), System.SR.InvalidOperation_CannotImportGlobalFromDifferentModule, System.length, System.length2, and System.length3.
Referenced by System.Reflection.Emit.ModuleBuilder.GetFieldToken().