Terraria: System.Reflection.Emit.ModuleBuilder.GetMethodTokenNoLock
GetMethodTokenNoLock()
int System.Reflection.Emit.ModuleBuilder.GetMethodTokenNoLock (MethodInfo method, bool getGenericTypeDefinition) inline private
Definition at line 898 of file ModuleBuilder.cs.
    {
        if (method == null)
        {
            throw new ArgumentNullException("method");
        }
        int num = 0;
        int tr;
        if (method is MethodBuilder { MetadataToken: var metadataToken })
        {
            if (method.Module.Equals(this))
            {
                return metadataToken;
            }
            if (method.DeclaringType == null)
            {
                throw new InvalidOperationException(SR.InvalidOperation_CannotImportGlobalFromDifferentModule);
            }
            tr = (getGenericTypeDefinition ? GetTypeToken(method.DeclaringType) : GetTypeTokenInternal(method.DeclaringType));
            return GetMemberRef(method.DeclaringType.Module, tr, metadataToken);
        }
        if (method is MethodOnTypeBuilderInstantiation)
        {
            return GetMemberRefToken(method, null);
        }
        if (method is SymbolMethod symbolMethod)
        {
            if (symbolMethod.GetModule() == this)
            {
                return symbolMethod.MetadataToken;
            }
            return symbolMethod.GetToken(this);
        }
        Type declaringType = method.DeclaringType;
        if (declaringType == null)
        {
            throw new InvalidOperationException(SR.InvalidOperation_CannotImportGlobalFromDifferentModule);
        }
        if (declaringType.IsArray)
        {
            ParameterInfo[] parameters = method.GetParameters();
            Type[] array = new Type[parameters.Length];
            for (int i = 0; i < parameters.Length; i++)
            {
                array[i] = parameters[i].ParameterType;
            }
            return GetArrayMethodToken(declaringType, method.Name, method.CallingConvention, method.ReturnType, array);
        }
        if (method is RuntimeMethodInfo method2)
        {
            tr = (getGenericTypeDefinition ? GetTypeToken(declaringType) : GetTypeTokenInternal(declaringType));
            return GetMemberRefOfMethodInfo(tr, method2);
        }
        ParameterInfo[] parameters2 = method.GetParameters();
        Type[] array2 = new Type[parameters2.Length];
        Type[][] array3 = new Type[array2.Length][];
        Type[][] array4 = new Type[array2.Length][];
        for (int j = 0; j < parameters2.Length; j++)
        {
            array2[j] = parameters2[j].ParameterType;
            array3[j] = parameters2[j].GetRequiredCustomModifiers();
            array4[j] = parameters2[j].GetOptionalCustomModifiers();
        }
        tr = (getGenericTypeDefinition ? GetTypeToken(declaringType) : GetTypeTokenInternal(declaringType));
        SignatureHelper methodSigHelper;
        try
        {
            methodSigHelper = SignatureHelper.GetMethodSigHelper(this, method.CallingConvention, method.ReturnType, method.ReturnParameter.GetRequiredCustomModifiers(), method.ReturnParameter.GetOptionalCustomModifiers(), array2, array3, array4);
        }
        catch (NotImplementedException)
        {
            methodSigHelper = SignatureHelper.GetMethodSigHelper(this, method.ReturnType, array2);
        }
        int length;
        byte[] signature = methodSigHelper.InternalGetSignature(out length);
        return GetMemberRefFromSignature(tr, method.Name, signature, length);
    }
References System.array, System.Reflection.Emit.ModuleBuilder.GetArrayMethodToken(), System.Reflection.Emit.ModuleBuilder.GetMemberRef(), System.Reflection.Emit.ModuleBuilder.GetMemberRefFromSignature(), System.Reflection.Emit.ModuleBuilder.GetMemberRefOfMethodInfo(), System.Reflection.Emit.ModuleBuilder.GetMemberRefToken(), System.Reflection.Emit.SignatureHelper.GetMethodSigHelper(), System.Reflection.Emit.ModuleBuilder.GetTypeToken(), System.Reflection.Emit.ModuleBuilder.GetTypeTokenInternal(), System.SR.InvalidOperation_CannotImportGlobalFromDifferentModule, System.length, System.Reflection.Emit.ModuleBuilder.MetadataToken, and System.Reflection.ParameterInfo.ParameterType.
Referenced by System.Reflection.Emit.ModuleBuilder.GetMethodToken().