Terraria: System.Reflection.Emit.ModuleBuilder.GetTypeTokenWorkerNoLock
GetTypeTokenWorkerNoLock()
int System.Reflection.Emit.ModuleBuilder.GetTypeTokenWorkerNoLock (Type type, bool getGenericDefinition) inline private
Definition at line 844 of file ModuleBuilder.cs.
    {
        if (type == null)
        {
            throw new ArgumentNullException("type");
        }
        AssemblyBuilder.CheckContext(type);
        if (type.IsByRef)
        {
            throw new ArgumentException(SR.Argument_CannotGetTypeTokenForByRef);
        }
        if ((type.IsGenericType && (!type.IsGenericTypeDefinition || !getGenericDefinition)) || type.IsGenericParameter || type.IsArray || type.IsPointer)
        {
            int length;
            byte[] signature = SignatureHelper.GetTypeSigToken(this, type).InternalGetSignature(out length);
            return GetTokenFromTypeSpec(signature, length);
        }
        Module module = type.Module;
        if (module.Equals(this))
        {
            TypeBuilder typeBuilder = null;
            EnumBuilder enumBuilder = type as EnumBuilder;
            typeBuilder = ((enumBuilder != null) ? enumBuilder.m_typeBuilder : (type as TypeBuilder));
            if (typeBuilder != null)
            {
                return typeBuilder.TypeToken;
            }
            if (type is GenericTypeParameterBuilder genericTypeParameterBuilder)
            {
                return genericTypeParameterBuilder.MetadataToken;
            }
            return GetTypeRefNested(type, this, string.Empty);
        }
        ModuleBuilder moduleBuilder = module as ModuleBuilder;
        string strRefedModuleFileName = string.Empty;
        if (module.Assembly.Equals(Assembly))
        {
            if (moduleBuilder == null)
            {
                moduleBuilder = ContainingAssemblyBuilder.GetModuleBuilder((InternalModuleBuilder)module);
            }
            strRefedModuleFileName = moduleBuilder._moduleData._moduleName;
        }
        return GetTypeRefNested(type, module, strRefedModuleFileName);
    }
References System.Reflection.Emit.ModuleBuilder.ModuleBuilder(), System.SR.Argument_CannotGetTypeTokenForByRef, System.Reflection.Emit.AssemblyBuilder.CheckContext(), System.Reflection.Emit.ModuleBuilder.ContainingAssemblyBuilder, System.Reflection.Emit.AssemblyBuilder.GetModuleBuilder(), System.Reflection.Emit.ModuleBuilder.GetTokenFromTypeSpec(), System.Reflection.Emit.ModuleBuilder.GetTypeRefNested(), System.Reflection.Emit.SignatureHelper.GetTypeSigToken(), System.length, System.type, and System.Reflection.Emit.TypeBuilder.TypeToken.
Referenced by System.Reflection.Emit.ModuleBuilder.GetTypeTokenInternal().