Terraria: System.Reflection.Emit.ModuleBuilder.GetMethodToken
GetMethodToken()
int System.Reflection.Emit.ModuleBuilder.GetMethodToken (MethodInfo method) inline package
Definition at line 890 of file ModuleBuilder.cs.
    {
        lock (SyncRoot)
        {
            return GetMethodTokenNoLock(method, getGenericTypeDefinition: false);
        }
    }
References System.Reflection.Emit.ModuleBuilder.GetMethodTokenNoLock(), and System.Reflection.Emit.ModuleBuilder.SyncRoot.
Referenced by System.Reflection.Emit.TypeBuilder.DefineMethodOverrideNoLock(), System.Reflection.Emit.ModuleBuilder.GetMemberRefToken(), and System.Reflection.Emit.ModuleBuilder.GetMethodTokenInternal().