Terraria: System.Reflection.Emit.ModuleBuilder.GetConstructorToken
GetConstructorToken()
int System.Reflection.Emit.ModuleBuilder.GetConstructorToken (ConstructorInfo con) inline package
Definition at line 1052 of file ModuleBuilder.cs.
    {
        return InternalGetConstructorToken(con, usingRef: false);
    }
References System.Reflection.Emit.ModuleBuilder.InternalGetConstructorToken().
Referenced by System.Reflection.Emit.CustomAttributeBuilder.CreateCustomAttribute(), System.Reflection.Emit.ModuleBuilder.GetMemberRefToken(), System.Reflection.Emit.ModuleBuilder.GetMethodTokenInternal(), System.Reflection.Emit.AssemblyBuilder.SetCustomAttribute(), System.Reflection.Emit.EventBuilder.SetCustomAttribute(), System.Reflection.Emit.FieldBuilder.SetCustomAttribute(), System.Reflection.Emit.MethodBuilder.SetCustomAttribute(), System.Reflection.Emit.ModuleBuilder.SetCustomAttribute(), System.Reflection.Emit.PropertyBuilder.SetCustomAttribute(), and System.Reflection.Emit.TypeBuilder.SetCustomAttribute().