Terraria: System.Reflection.Emit.ModuleBuilder.DefineType
DefineType() [1/7]
TypeBuilder System.Reflection.Emit.ModuleBuilder.DefineType (string name) inline
Definition at line 627 of file ModuleBuilder.cs.
    {
        lock (SyncRoot)
        {
            return DefineTypeNoLock(name, TypeAttributes.NotPublic, null, null, PackingSize.Unspecified, 0);
        }
    }
References System.Reflection.Emit.ModuleBuilder.DefineTypeNoLock(), and System.Reflection.Emit.ModuleBuilder.SyncRoot.
Referenced by System.Reflection.Emit.IgnoreAccessChecksToAttributeBuilder.AddToModule(), System.Reflection.DispatchProxyGenerator.ProxyAssembly.CreateProxy(), System.Reflection.Emit.TypeBuilder.DefineDataHelper(), and System.Linq.Expressions.Compiler.AssemblyGen.DefineType().