Terraria: SalamanderShellyDadUICollectionInfoProvider.GetLowestAvailableUnlockStateFromEntriesThatAreInWorld
GetLowestAvailableUnlockStateFromEntriesThatAreInWorld()
BestiaryEntryUnlockState SalamanderShellyDadUICollectionInfoProvider.GetLowestAvailableUnlockStateFromEntriesThatAreInWorld (BestiaryEntryUnlockState unlockstatus) inline private
     {
         BestiaryEntryUnlockState bestiaryEntryUnlockState = BestiaryEntryUnlockState.CanShowDropsWithDropRates_4;
         int[,] cavernMonsterType = NPC.cavernMonsterType;
         for (int i = 0; i < cavernMonsterType.GetLength(0); i++)
         {
             for (int j = 0; j < cavernMonsterType.GetLength(1); j++)
             {
                 string persistentId = ContentSamples.NpcBestiaryCreditIdsByNpcNetIds[cavernMonsterType[i, j]];
                 BestiaryEntryUnlockState unlockStateByKillCount = CommonEnemyUICollectionInfoProvider.GetUnlockStateByKillCount(Main.BestiaryTracker.Kills.GetKillCount(persistentId), quickUnlock: false, _killCountNeededToFullyUnlock);
                 if (bestiaryEntryUnlockState > unlockStateByKillCount)
                 {
                     bestiaryEntryUnlockState = unlockStateByKillCount;
                 }
             }
         }
         unlockstatus = bestiaryEntryUnlockState;
         return unlockstatus;
     }
References _killCountNeededToFullyUnlock, Main.BestiaryTracker, NPC.cavernMonsterType, NPCKillsTracker.GetKillCount(), CommonEnemyUICollectionInfoProvider.GetUnlockStateByKillCount(), BestiaryUnlocksTracker.Kills, and ContentSamples.NpcBestiaryCreditIdsByNpcNetIds.
Referenced by GetEntryUICollectionInfo().