Terraria: Terraria.GameContent.Liquid.LiquidRenderer.GetShimmerBaseColor
GetShimmerBaseColor()
static Vector4 Terraria.GameContent.Liquid.LiquidRenderer.GetShimmerBaseColor (float worldPositionX, float worldPositionY) inline static
Definition at line 788 of file LiquidRenderer.cs.
    {
        float shimmerWave = GetShimmerWave(ref worldPositionX, ref worldPositionY);
        return Vector4.Lerp(new Vector4(0.64705884f, 26f / 51f, 14f / 15f, 1f), new Vector4(41f / 51f, 41f / 51f, 1f, 1f), 0.1f + shimmerWave * 0.4f);
    }
References Terraria.GameContent.Liquid.LiquidRenderer.GetShimmerWave(), Microsoft.Xna.Framework.Vector4.Lerp(), and Microsoft.Xna.Framework.Graphics.Vector4.
Referenced by Terraria.Graphics.Light.TileLightScanner.ApplyTileLight(), Terraria.Main.oldDrawWater(), and Terraria.GameContent.Liquid.LiquidRenderer.SetShimmerVertexColors().