Terraria: Terraria.GameContent.Liquid.LiquidRenderer.DrawNormalLiquids
DrawNormalLiquids()
unsafe void Terraria.GameContent.Liquid.LiquidRenderer.DrawNormalLiquids (SpriteBatch spriteBatch, Vector2 drawOffset, int waterStyle, float globalAlpha, bool isBackgroundDraw) inline
Definition at line 618 of file LiquidRenderer.cs.
    {
        Rectangle drawArea = _drawArea;
        Main.tileBatch.Begin();
        fixed (LiquidDrawCache* ptr = &_drawCache[0])
        {
            LiquidDrawCache* ptr2 = ptr;
            for (int i = drawArea.X; i < drawArea.X + drawArea.Width; i++)
            {
                for (int j = drawArea.Y; j < drawArea.Y + drawArea.Height; j++)
                {
                    if (ptr2->IsVisible)
                    {
                        Rectangle sourceRectangle = ptr2->SourceRectangle;
                        if (ptr2->IsSurfaceLiquid)
{
                            sourceRectangle.Y = 1280;
                        }
                        else
{
                            sourceRectangle.Y += _animationFrame * 80;
                        }
                        Vector2 liquidOffset = ptr2->LiquidOffset;
                        float num = ptr2->Opacity * (isBackgroundDraw ? 1f : DEFAULT_OPACITY[ptr2->Type]);
                        int num2 = ptr2->Type;
                        switch (num2)
{
                        case 0:
                            num2 = waterStyle;
                            num *= globalAlpha;
                            break;
                        case 2:
                            num2 = 11;
                            break;
                        }
                        num = Math.Min(1f, num);
                        Lighting.GetCornerColors(i, j, out var vertices);
                        vertices.BottomLeftColor *= num;
                        vertices.BottomRightColor *= num;
                        vertices.TopLeftColor *= num;
                        vertices.TopRightColor *= num;
                        Main.DrawTileInWater(drawOffset, i, j);
                        Main.tileBatch.Draw(_liquidTextures[num2].Value, new Vector2(i << 4, j << 4) + drawOffset + liquidOffset, sourceRectangle, vertices, Vector2.Zero, 1f, SpriteEffects.None);
                    }
                    ptr2++;
                }
            }
        }
        Main.tileBatch.End();
    }
References Terraria.GameContent.Liquid.LiquidRenderer._animationFrame, Terraria.GameContent.Liquid.LiquidRenderer._drawArea, Terraria.GameContent.Liquid.LiquidRenderer._drawCache, Terraria.GameContent.Liquid.LiquidRenderer._liquidTextures, Terraria.GameContent.Liquid.LiquidRenderer.DEFAULT_OPACITY, Terraria.Main.DrawTileInWater(), Terraria.Lighting.GetCornerColors(), Microsoft.Xna.Framework.Rectangle.Height, Terraria.GameContent.Liquid.LiquidRenderer.LiquidDrawCache.IsSurfaceLiquid, Terraria.GameContent.Liquid.LiquidRenderer.LiquidDrawCache.IsVisible, Terraria.GameContent.Liquid.LiquidRenderer.LiquidDrawCache.LiquidOffset, System.Math.Min(), Terraria.GameContent.Liquid.LiquidRenderer.LiquidDrawCache.Opacity, Terraria.GameContent.Liquid.LiquidRenderer.LiquidDrawCache.SourceRectangle, Terraria.Main.tileBatch, Terraria.GameContent.Liquid.LiquidRenderer.LiquidDrawCache.Type, Microsoft.Xna.Framework.Graphics.Vector2, Microsoft.Xna.Framework.Rectangle.Width, Microsoft.Xna.Framework.Rectangle.X, Microsoft.Xna.Framework.Rectangle.Y, and Microsoft.Xna.Framework.Vector2.Zero.