Terraria: System.Reflection.Emit.ModuleBuilder.GetTypeRefNested
GetTypeRefNested()
int System.Reflection.Emit.ModuleBuilder.GetTypeRefNested (Type type, Module refedModule, string strRefedModuleFileName) inline private
Definition at line 181 of file ModuleBuilder.cs.
    {
        Type declaringType = type.DeclaringType;
        int tkResolution = 0;
        string text = type.FullName;
        if (declaringType != null)
        {
            tkResolution = GetTypeRefNested(declaringType, refedModule, strRefedModuleFileName);
            text = UnmangleTypeName(text);
        }
        ModuleBuilder module = this;
        RuntimeModule module2 = GetRuntimeModuleFromModule(refedModule);
        return GetTypeRef(new QCallModule(ref module), text, new QCallModule(ref module2), strRefedModuleFileName, tkResolution);
    }
References System.Reflection.Emit.ModuleBuilder.GetRuntimeModuleFromModule(), System.Reflection.Emit.ModuleBuilder.GetTypeRef(), System.Reflection.Emit.ModuleBuilder.GetTypeRefNested(), System.text, System.type, and System.Reflection.Emit.ModuleBuilder.UnmangleTypeName().
Referenced by System.Reflection.Emit.ModuleBuilder.GetTypeRefNested(), and System.Reflection.Emit.ModuleBuilder.GetTypeTokenWorkerNoLock().