Terraria: System.Reflection.Emit.ModuleBuilder.GetTypeNoLock
GetTypeNoLock()
Type System.Reflection.Emit.ModuleBuilder.GetTypeNoLock (string className, bool throwOnError, bool ignoreCase) inline private
Definition at line 481 of file ModuleBuilder.cs.
    {
        Type type = InternalModule.GetType(className, throwOnError, ignoreCase);
        if (type != null)
        {
            return type;
        }
        string text = null;
        string text2 = null;
        int num = 0;
        while (num <= className.Length)
        {
            int num2 = className.AsSpan(num).IndexOfAny('[', '*', '&');
            if (num2 == -1)
            {
                text = className;
                text2 = null;
                break;
            }
            num2 += num;
            int num3 = 0;
            int num4 = num2 - 1;
            while (num4 >= 0 && className[num4] == '\\')
            {
                num3++;
                num4--;
            }
            if (num3 % 2 == 1)
            {
                num = num2 + 1;
                continue;
            }
            text = className.Substring(0, num2);
            text2 = className.Substring(num2);
            break;
        }
        if (text == null)
        {
            text = className;
            text2 = null;
        }
        text = text.Replace("\\\\", "\\").Replace("\\[", "[").Replace("\\*", "*")
            .Replace("\\&", "&");
        if (text2 != null)
        {
            type = InternalModule.GetType(text, throwOnError: false, ignoreCase);
        }
        if (type == null)
        {
            type = FindTypeBuilderWithName(text, ignoreCase);
            if (type == null && Assembly is AssemblyBuilder)
            {
                List<ModuleBuilder> moduleBuilderList = ContainingAssemblyBuilder._assemblyData._moduleBuilderList;
                int count = moduleBuilderList.Count;
                for (int i = 0; i < count; i++)
                {
                    if (!(type == null))
                    {
                        break;
                    }
                    ModuleBuilder moduleBuilder = moduleBuilderList[i];
                    type = moduleBuilder.FindTypeBuilderWithName(text, ignoreCase);
                }
            }
            if (type == null)
            {
                return null;
            }
        }
        if (text2 == null)
        {
            return type;
        }
        return GetType(text2, type);
    }
References System.Reflection.Emit.AssemblyBuilder._assemblyData, System.Reflection.Emit.AssemblyBuilderData._moduleBuilderList, System.Reflection.Emit.ModuleBuilder.ContainingAssemblyBuilder, System.count, System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Reflection.Emit.ModuleBuilder.FindTypeBuilderWithName(), System.Reflection.RuntimeModule.GetType(), System.Reflection.Emit.ModuleBuilder.GetType(), System.Reflection.Emit.ModuleBuilder.InternalModule, System.text, and System.type.
Referenced by System.Reflection.Emit.ModuleBuilder.GetType().