Terraria: System.Reflection.Emit.ModuleBuilder.GetMemberRefToken
GetMemberRefToken()
int System.Reflection.Emit.ModuleBuilder.GetMemberRefToken (MethodBase method, Type[] optionalParameterTypes) inline private
Definition at line 272 of file ModuleBuilder.cs.
    {
        int cGenericParameters = 0;
        if (method.IsGenericMethod)
        {
            if (!method.IsGenericMethodDefinition)
            {
                throw new InvalidOperationException();
            }
            cGenericParameters = method.GetGenericArguments().Length;
        }
        if (optionalParameterTypes != null && (method.CallingConvention & CallingConventions.VarArgs) == 0)
        {
            throw new InvalidOperationException(SR.InvalidOperation_NotAVarArgCallingConvention);
        }
        MethodInfo methodInfo = method as MethodInfo;
        SignatureHelper memberRefSignature;
        if (method.DeclaringType.IsGenericType)
        {
            MethodBase genericMethodBaseDefinition = GetGenericMethodBaseDefinition(method);
            memberRefSignature = GetMemberRefSignature(genericMethodBaseDefinition, cGenericParameters);
        }
        else
        {
            memberRefSignature = GetMemberRefSignature(method, cGenericParameters);
        }
        if (optionalParameterTypes != null && optionalParameterTypes.Length != 0)
        {
            memberRefSignature.AddSentinel();
            memberRefSignature.AddArguments(optionalParameterTypes, null, null);
        }
        int length;
        byte[] signature = memberRefSignature.InternalGetSignature(out length);
        int tr;
        if (!method.DeclaringType.IsGenericType)
        {
            tr = ((!method.Module.Equals(this)) ? GetTypeToken(method.DeclaringType) : ((!(methodInfo != null)) ? GetConstructorToken(method as ConstructorInfo) : GetMethodToken(methodInfo)));
        }
        else
        {
            int length2;
            byte[] signature2 = SignatureHelper.GetTypeSigToken(this, method.DeclaringType).InternalGetSignature(out length2);
            tr = GetTokenFromTypeSpec(signature2, length2);
        }
        return GetMemberRefFromSignature(tr, method.Name, signature, length);
    }
References System.Reflection.Emit.ModuleBuilder.GetConstructorToken(), System.Reflection.Emit.ModuleBuilder.GetGenericMethodBaseDefinition(), System.Reflection.Emit.ModuleBuilder.GetMemberRefFromSignature(), System.Reflection.Emit.ModuleBuilder.GetMemberRefSignature(), System.Reflection.Emit.ModuleBuilder.GetMethodToken(), System.Reflection.Emit.ModuleBuilder.GetTokenFromTypeSpec(), System.Reflection.Emit.SignatureHelper.GetTypeSigToken(), System.Reflection.Emit.ModuleBuilder.GetTypeToken(), System.SR.InvalidOperation_NotAVarArgCallingConvention, System.length, and System.length2.
Referenced by System.Reflection.Emit.ModuleBuilder.GetMethodTokenInternal(), and System.Reflection.Emit.ModuleBuilder.GetMethodTokenNoLock().