Terraria: System.Reflection.Emit.ModuleBuilder.DefineGlobalMethodNoLock
DefineGlobalMethodNoLock()
MethodBuilder System.Reflection.Emit.ModuleBuilder.DefineGlobalMethodNoLock (string name, MethodAttributes attributes, CallingConventions callingConvention, Type returnType, Type[] requiredReturnTypeCustomModifiers, Type[] optionalReturnTypeCustomModifiers, Type[] parameterTypes, Type requiredParameterTypeCustomModifiers[][], Type optionalParameterTypeCustomModifiers[][]) inline private
Definition at line 749 of file ModuleBuilder.cs.
    {
        if (_moduleData._hasGlobalBeenCreated)
        {
            throw new InvalidOperationException(SR.InvalidOperation_GlobalsHaveBeenCreated);
        }
        if (name == null)
        {
            throw new ArgumentNullException("name");
        }
        if (name.Length == 0)
        {
            throw new ArgumentException(SR.Argument_EmptyName, "name");
        }
        if ((attributes & MethodAttributes.Static) == 0)
        {
            throw new ArgumentException(SR.Argument_GlobalFunctionHasToBeStatic);
        }
        AssemblyBuilder.CheckContext(returnType);
        AssemblyBuilder.CheckContext(requiredReturnTypeCustomModifiers, optionalReturnTypeCustomModifiers, parameterTypes);
        AssemblyBuilder.CheckContext(requiredParameterTypeCustomModifiers);
        AssemblyBuilder.CheckContext(optionalParameterTypeCustomModifiers);
        return _moduleData._globalTypeBuilder.DefineMethod(name, attributes, callingConvention, returnType, requiredReturnTypeCustomModifiers, optionalReturnTypeCustomModifiers, parameterTypes, requiredParameterTypeCustomModifiers, optionalParameterTypeCustomModifiers);
    }
References System.Reflection.Emit.ModuleBuilderData._globalTypeBuilder, System.Reflection.Emit.ModuleBuilderData._hasGlobalBeenCreated, System.Reflection.Emit.ModuleBuilder._moduleData, System.SR.Argument_EmptyName, System.SR.Argument_GlobalFunctionHasToBeStatic, System.Reflection.Emit.AssemblyBuilder.CheckContext(), System.Reflection.Emit.TypeBuilder.DefineMethod(), and System.SR.InvalidOperation_GlobalsHaveBeenCreated.
Referenced by System.Reflection.Emit.ModuleBuilder.DefineGlobalMethod().