Terraria: System.Reflection.Emit.ModuleBuilder.FindTypeBuilderWithName
FindTypeBuilderWithName()
virtual Type System.Reflection.Emit.ModuleBuilder.FindTypeBuilderWithName (string strTypeName, bool ignoreCase) inline package virtual
Definition at line 161 of file ModuleBuilder.cs.
    {
        Type value;
        if (ignoreCase)
        {
            foreach (string key in _typeBuilderDict.Keys)
            {
                if (string.Equals(key, strTypeName, StringComparison.OrdinalIgnoreCase))
                {
                    return _typeBuilderDict[key];
                }
            }
        }
        else if (_typeBuilderDict.TryGetValue(strTypeName, out value))
        {
            return value;
        }
        return null;
    }
References System.Reflection.Emit.ModuleBuilder._typeBuilderDict, System.Reflection.Emit.ModuleBuilder.Equals(), System.key, System.Collections.Generic.Dictionary< TKey, TValue >.Keys, System.Collections.Generic.Dictionary< TKey, TValue >.TryGetValue(), and System.value.
Referenced by System.Reflection.Emit.TypeBuilder.DefineDataHelper(), and System.Reflection.Emit.ModuleBuilder.GetTypeNoLock().