Terraria: System.IO.Stream.Read
Read() [1/2]
int System.IO.Stream.Read (byte[] buffer, int offset, int count) abstract inherited
Referenced by System.IO.Stream.BeginReadInternal(), System.Security.Cryptography.HashAlgorithm.ComputeHash(), System.Data.SqlTypes.SqlBytes.CopyStreamToBuffer(), System.Xml.XmlSqlBinaryReader.FillAllowEOF(), System.Net.Http.HttpConnection.FillAsync(), System.Runtime.Serialization.Json.JsonEncodingStreamWrapper.FillBuffer(), System.Xml.EncodingStreamWrapper.FillBuffer(), System.IO.BinaryReader.FillBuffer(), Internal.Cryptography.CngCommon.HashData(), System.Net.Http.HttpConnection.InitialFillAsync(), System.IO.BinaryReader.InternalRead(), System.IO.BinaryReader.InternalReadChars(), System.IO.BinaryReader.Read(), System.ComponentModel.Design.DesigntimeLicenseContextSerializer.StreamWrapper.Read(), System.Data.SqlTypes.SqlXmlStreamWrapper.Read(), System.IO.Compression.SubReadStream.Read(), System.IO.Compression.WrappedStream.Read(), System.IO.DelegatingStream.Read(), System.Net.Http.MultipartContent.ContentReadStream.Read(), System.Net.DelegatedStream.Read(), System.IO.Strategies.DerivedFileStreamStrategy.Read(), System.IO.BufferedStream.Read(), System.IO.FileStream.Read(), System.Runtime.Serialization.Json.JsonEncodingStreamWrapper.Read(), System.Xml.EncodingStreamWrapper.Read(), System.IO.Stream.SyncStream.Read(), System.Data.SqlTypes.SqlBytes.Read(), System.IO.Compression.BrotliStream.Read(), System.IO.Compression.DeflateManagedStream.Read(), System.IO.Compression.WrappedStream.Read(), System.IO.DelegatingStream.Read(), System.Net.Http.DecompressionHandler.DeflateDecompressedContent.ZLibOrDeflateStream.PeekFirstByteReadStream.Read(), System.Net.Http.DecompressionHandler.DeflateDecompressedContent.ZLibOrDeflateStream.Read(), System.Net.Http.MultipartContent.ContentReadStream.Read(), System.IO.BinaryReader.Read(), System.IO.FileStream.Read(), System.IO.Stream.SyncStream.Read(), System.Text.TranscodingStream.Read(), System.IO.Compression.SubReadStream.Read(), System.Net.Http.HttpConnection.Read(), System.IO.BufferedStream.Read(), Terraria.Audio.WAVAudioTrack.ReadAheadPutAChunkIntoTheBuffer(), System.Net.Security.SyncReadWriteAdapter.ReadAsync(), System.Security.Cryptography.CryptoStream.ReadAsyncCore(), System.IO.StreamReader.ReadBuffer(), System.IO.StreamReader.ReadBuffer(), System.Net.Http.HttpConnection.ReadBuffered(), System.IO.BinaryReader.ReadBytes(), System.IO.Strategies.BufferedFileStreamStrategy.ReadByteSlow(), System.IO.BufferedStream.ReadByteSlow(), System.IO.Compression.DeflateStream.ReadCore(), System.Xml.XmlTextReaderImpl.ReadData(), System.IO.Strategies.BufferedFileStreamStrategy.ReadSpan(), System.IO.BinaryReader.ReadString(), System.Net.Mime.MimePart.Send(), System.Xml.XmlBufferReader.TryEnsureBytes(), and System.Net.WebClient.UploadBits().