Terraria: System.IO.Stream.EndRead
EndRead()
virtual int System.IO.Stream.EndRead (IAsyncResult asyncResult) inline virtual inherited
Reimplemented in System.Net.FtpDataStream, System.Net.WebFileStream, System.IO.Compression.BrotliStream, System.IO.Compression.DeflateManagedStream, System.IO.Compression.DeflateStream, System.IO.Compression.GZipStream, System.IO.Compression.ZLibStream, System.IO.IsolatedStorage.IsolatedStorageFileStream, System.IO.Pipes.PipeStream, System.IO.DelegatingStream, System.IO.ReadOnlyMemoryStream, System.Net.Http.HttpBaseStream, System.Net.Http.MultipartContent.ContentReadStream, System.Net.WebSockets.WebSocketHttpListenerDuplexStream, System.Net.HttpRequestStream, System.Net.HttpResponseStream, System.Net.Base64Stream, System.Net.BufferedReadStream, System.Net.DelegatedStream, System.Net.TlsStream, System.Net.Quic.QuicStream, System.Net.NetworkStreamWrapper, System.Net.TlsStream, System.Net.Security.NegotiateStream, System.Net.Security.SslStream, System.Net.Sockets.NetworkStream, System.IO.DelegatingStream, System.IO.Strategies.BufferedFileStreamStrategy, System.IO.Strategies.DerivedFileStreamStrategy, System.IO.Strategies.Net5CompatFileStreamStrategy, System.IO.Strategies.OSFileStreamStrategy, System.IO.BufferedStream, System.IO.FileStream, System.IO.Stream.NullStream, System.IO.Stream.SyncStream, System.Text.TranscodingStream, and System.Security.Cryptography.CryptoStream.
Definition at line 737 of file Stream.cs.
    {
        if (asyncResult == null)
        {
            ThrowHelper.ThrowArgumentNullException(ExceptionArgument.asyncResult);
        }
        ReadWriteTask readWriteTask = asyncResult as ReadWriteTask;
        if (readWriteTask == null || !readWriteTask._isRead)
        {
            ThrowHelper.ThrowArgumentException(ExceptionResource.InvalidOperation_WrongAsyncResultOrEndCalledMultiple);
        }
        else if (readWriteTask._endCalled)
        {
            ThrowHelper.ThrowInvalidOperationException(ExceptionResource.InvalidOperation_WrongAsyncResultOrEndCalledMultiple);
        }
        try
        {
            return readWriteTask.GetAwaiter().GetResult();
        }
        finally
        {
            FinishTrackingAsyncOperation(readWriteTask);
        }
    }
References System.IO.Stream.ReadWriteTask._endCalled, System.IO.Stream.ReadWriteTask._isRead, System.asyncResult, System.IO.Stream.FinishTrackingAsyncOperation(), System.Threading.Tasks.Task< TResult >.GetAwaiter(), System.ThrowHelper.ThrowArgumentException(), System.ThrowHelper.ThrowArgumentNullException(), and System.ThrowHelper.ThrowInvalidOperationException().
Referenced by System.Net.Base64Stream.ReadAsyncResult.CompleteRead(), System.IO.DelegatingStream.EndRead(), System.Net.DelegatedStream.EndRead(), System.IO.Strategies.DerivedFileStreamStrategy.EndRead(), System.IO.FileStream.EndRead(), System.IO.Stream.SyncStream.EndRead(), System.Net.BufferedReadStream.ReadAsyncResult.OnRead(), System.Net.BufferedReadStream.ReadAsyncResult.Read(), System.Net.CommandStream.ReadCallback(), and System.Net.Mime.MimePart.ReadCallbackHandler().