Terraria: System.IO.Stream.CopyTo
CopyTo() [2/2]
virtual void System.IO.Stream.CopyTo (Stream destination, int bufferSize) inline virtual inherited
Reimplemented in System.IO.Compression.DeflateStream, System.IO.Compression.GZipStream, System.IO.Compression.ZLibStream, System.IO.ReadOnlyMemoryStream, System.Net.Http.Http2Connection.Http2Stream.Http2ReadStream, System.IO.Strategies.BufferedFileStreamStrategy, System.IO.BufferedStream, System.IO.FileStream, System.IO.MemoryStream, System.IO.Stream.NullStream, and System.Security.Cryptography.CryptoStream.
Definition at line 545 of file Stream.cs.
    {
        ValidateCopyToArguments(destination, bufferSize);
        if (!CanRead)
        {
            if (CanWrite)
            {
                ThrowHelper.ThrowNotSupportedException_UnreadableStream();
            }
            ThrowHelper.ThrowObjectDisposedException_StreamClosed(GetType().Name);
        }
        byte[] array = ArrayPool<byte>.Shared.Rent(bufferSize);
        try
        {
            int count;
            while ((count = Read(array, 0, array.Length)) != 0)
            {
                destination.Write(array, 0, count);
            }
        }
        finally
        {
            ArrayPool<byte>.Shared.Return(array);
        }
    }
References System.array, System.IO.Stream.CanRead, System.IO.Stream.CanWrite, System.count, System.destination, System.Name, System.IO.Read, System.Buffers.ArrayPool< T >.Shared, System.ThrowHelper.ThrowNotSupportedException_UnreadableStream(), System.ThrowHelper.ThrowObjectDisposedException_StreamClosed(), and System.IO.Stream.ValidateCopyToArguments().