Terraria: System.IO.Stream.BeginRead
BeginRead()
virtual IAsyncResult System.IO.Stream.BeginRead (byte[] buffer, int offset, int count, AsyncCallback? callback, object? state) inline virtual inherited
Reimplemented in System.IO.IsolatedStorage.IsolatedStorageFileStream, System.IO.Compression.BrotliStream, System.IO.Compression.DeflateStream, System.IO.Compression.GZipStream, System.IO.Compression.ZLibStream, System.Net.Security.NegotiateStream, System.Net.Security.SslStream, System.IO.Pipes.PipeStream, System.Net.Quic.QuicStream, System.Net.Sockets.NetworkStream, System.IO.BufferedStream, System.IO.FileStream, and System.Security.Cryptography.CryptoStream.
Definition at line 688 of file Stream.cs.
    {
        return BeginReadInternal(buffer, offset, count, callback, state, serializeAsynchronously: false, apm: true);
    }
References System.IO.Stream.BeginReadInternal(), System.buffer, System.count, System.offset, and System.state.
Referenced by System.IO.DelegatingStream.BeginRead(), System.Net.DelegatedStream.BeginRead(), System.IO.Strategies.DerivedFileStreamStrategy.BeginRead(), System.IO.Stream.SyncStream.BeginRead(), System.IO.FileStream.BeginRead(), System.Net.Mime.MimePart.ContentStreamCallbackHandler(), System.Net.Base64Stream.ReadAsyncResult.Read(), System.Net.BufferedReadStream.ReadAsyncResult.Read(), and System.Net.Mime.MimePart.WriteCallbackHandler().