Terraria: System.IO.Stream.CopyToAsync
CopyToAsync() [4/4]
virtual Task System.IO.Stream.CopyToAsync (Stream destination, int bufferSize, CancellationToken cancellationToken) inline virtual inherited
Reimplemented in System.IO.Compression.DeflateStream, System.IO.Compression.GZipStream, System.IO.Compression.ZLibStream, System.IO.DelegatingStream, System.IO.ReadOnlyMemoryStream, System.Net.Http.DecompressionHandler.DeflateDecompressedContent.ZLibOrDeflateStream.PeekFirstByteReadStream, System.Net.Http.DecompressionHandler.DeflateDecompressedContent.ZLibOrDeflateStream, System.Net.Http.EmptyReadStream, System.Net.Http.Http2Connection.Http2Stream.Http2ReadStream, System.Net.Http.HttpConnection.ChunkedEncodingReadStream, System.Net.Http.HttpConnection.ConnectionCloseReadStream, System.Net.Http.HttpConnection.ContentLengthReadStream, System.Net.Http.HttpConnection.HttpContentWriteStream, System.Net.Http.HttpConnection.RawConnectionStream, System.Net.Http.HttpContent.LimitMemoryStream, System.Net.WebFileStream, System.IO.DelegatingStream, System.IO.Strategies.AsyncWindowsFileStreamStrategy, System.IO.Strategies.BufferedFileStreamStrategy, System.IO.Strategies.DerivedFileStreamStrategy, System.IO.Strategies.Net5CompatFileStreamStrategy, System.IO.BufferedStream, System.IO.FileStream, System.IO.MemoryStream, System.IO.Stream.NullStream, System.IO.UnmanagedMemoryStreamWrapper, and System.Security.Cryptography.CryptoStream.
Definition at line 586 of file Stream.cs.
    {
        ValidateCopyToArguments(destination, bufferSize);
        if (!CanRead)
        {
            if (CanWrite)
            {
                ThrowHelper.ThrowNotSupportedException_UnreadableStream();
            }
            ThrowHelper.ThrowObjectDisposedException_StreamClosed(GetType().Name);
        }
        return Core(this, destination, bufferSize, cancellationToken);
        static async Task Core(Stream source, Stream destination, int bufferSize, CancellationToken cancellationToken)
        {
            byte[] buffer = ArrayPool<byte>.Shared.Rent(bufferSize);
            try
            {
                int length;
                while ((length = await source.ReadAsync(new Memory<byte>(buffer), cancellationToken).ConfigureAwait(continueOnCapturedContext: false)) != 0)
                {
                    await destination.WriteAsync(new ReadOnlyMemory<byte>(buffer, 0, length), cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
                }
            }
            finally
            {
                ArrayPool<byte>.Shared.Return(buffer);
            }
        }
    }
References System.buffer, System.cancellationToken, System.IO.Stream.CanRead, System.IO.Stream.CanWrite, System.destination, System.length, System.Name, System.Buffers.ArrayPool< T >.Shared, System.source, System.ThrowHelper.ThrowNotSupportedException_UnreadableStream(), System.ThrowHelper.ThrowObjectDisposedException_StreamClosed(), and System.IO.Stream.ValidateCopyToArguments().