Terraria: System.IO.Stream.BeginReadInternal
BeginReadInternal()
Task< int > System.IO.Stream.BeginReadInternal (byte[] buffer, int offset, int count, AsyncCallback callback, object state, bool serializeAsynchronously, bool apm) inline package inherited
Definition at line 693 of file Stream.cs.
    {
        ValidateBufferArguments(buffer, offset, count);
        if (!CanRead)
        {
            ThrowHelper.ThrowNotSupportedException_UnreadableStream();
        }
        SemaphoreSlim semaphoreSlim = EnsureAsyncActiveSemaphoreInitialized();
        Task task = null;
        if (serializeAsynchronously)
        {
            task = semaphoreSlim.WaitAsync();
        }
        else
        {
            semaphoreSlim.Wait();
        }
        ReadWriteTask readWriteTask = new ReadWriteTask(isRead: true, apm, delegate
        {
            ReadWriteTask readWriteTask2 = Task.InternalCurrent as ReadWriteTask;
            try
            {
                return readWriteTask2._stream.Read(readWriteTask2._buffer, readWriteTask2._offset, readWriteTask2._count);
            }
            finally
            {
                if (!readWriteTask2._apm)
                {
                    readWriteTask2._stream.FinishTrackingAsyncOperation(readWriteTask2);
                }
                readWriteTask2.ClearBeginState();
            }
        }, state, this, buffer, offset, count, callback);
        if (task != null)
        {
            RunReadWriteTaskWhenReady(task, readWriteTask);
        }
        else
        {
            RunReadWriteTask(readWriteTask);
        }
        return readWriteTask;
    }
References System.IO.Stream.ReadWriteTask._apm, System.IO.Stream.ReadWriteTask._buffer, System.IO.Stream.ReadWriteTask._count, System.IO.Stream.ReadWriteTask._offset, System.IO.Stream.ReadWriteTask._stream, System.buffer, System.IO.Stream.CanRead, System.IO.Stream.ReadWriteTask.ClearBeginState(), System.count, System.IO.Stream.EnsureAsyncActiveSemaphoreInitialized(), System.IO.Stream.FinishTrackingAsyncOperation(), System.offset, System.IO.Stream.Read(), System.IO.Stream.RunReadWriteTask(), System.IO.Stream.RunReadWriteTaskWhenReady(), System.state, System.task, System.ThrowHelper.ThrowNotSupportedException_UnreadableStream(), System.IO.Stream.ValidateBufferArguments(), System.Threading.SemaphoreSlim.Wait(), and System.Threading.SemaphoreSlim.WaitAsync().
Referenced by System.IO.Stream.BeginEndReadAsync(), System.IO.Stream.SyncStream.BeginRead(), System.IO.Stream.BeginRead(), System.IO.Strategies.Net5CompatFileStreamStrategy.ReadAsync(), and System.IO.Strategies.Net5CompatFileStreamStrategy.ReadAsync().