Terraria: System.IO.Stream.ReadAsync
ReadAsync() [1/3]
Task< int > System.IO.Stream.ReadAsync (byte[] buffer, int offset, int count) inline inherited
Definition at line 762 of file Stream.cs.
    {
        return ReadAsync(buffer, offset, count, CancellationToken.None);
    }
References System.buffer, System.count, System.Threading.CancellationToken.None, System.offset, and System.IO.Stream.ReadAsync().
Referenced by System.Net.Http.HttpConnection.CheckUsabilityOnScavenge(), System.Security.Cryptography.HashAlgorithm.ComputeHashAsyncCore(), System.Net.WebClient.DownloadBitsAsync(), System.Net.Http.HttpConnection.FillAsync(), System.Net.Http.HttpConnection.InitialFillAsync(), System.Net.WebSockets.ManagedWebSocket._003CReceiveAsyncPrivate_003Ed__63< TResult >.MoveNext(), System.Net.WebSockets.ManagedWebSocket._003CEnsureBufferContainsAsync_003Ed__74.MoveNext(), System.IO.Strategies.BufferedFileStreamStrategy._003CReadAsyncSlowPath_003Ed__39.MoveNext(), System.Net.Http.DecompressionHandler.DeflateDecompressedContent.ZLibOrDeflateStream.PeekFirstByteReadStream.PeekFirstByteAsync(), System.Net.Http.HttpConnection.PrepareForReuse(), System.Net.WebSockets.WebSocketBase.WebSocketOperation.Process(), System.Net.Http.Http2Connection.ProcessIncomingFramesAsync(), System.IO.Stream.ReadAsync(), System.IO.Compression.WrappedStream.ReadAsync(), System.IO.DelegatingStream.ReadAsync(), System.Net.DelegatedStream.ReadAsync(), System.IO.FileStream.ReadAsync(), System.Net.Security.AsyncReadWriteAdapter.ReadAsync(), System.Net.Http.DecompressionHandler.DeflateDecompressedContent.ZLibOrDeflateStream.PeekFirstByteReadStream.ReadAsync(), System.Net.Http.DecompressionHandler.DeflateDecompressedContent.ZLibOrDeflateStream.ReadAsync(), System.Text.TranscodingStream.ReadAsync(), System.IO.Compression.BrotliStream.ReadAsync(), System.IO.Compression.SubReadStream.ReadAsync(), System.IO.Compression.WrappedStream.ReadAsync(), System.IO.DelegatingStream.ReadAsync(), System.Net.DelegatedStream.ReadAsync(), System.IO.Strategies.BufferedFileStreamStrategy.ReadAsync(), System.IO.FileStream.ReadAsync(), System.IO.Stream.ReadAsync(), System.Net.Http.HttpConnection.ReadAsync(), System.Net.WebSockets.WebSocketHttpListenerDuplexStream.ReadAsyncCore(), System.Security.Cryptography.CryptoStream.ReadAsyncCore(), System.IO.Compression.DeflateManagedStream.ReadAsyncCore(), System.IO.Compression.DeflateManagedStream.ReadAsyncInternal(), System.IO.StreamReader.ReadAsyncInternal(), System.IO.Compression.DeflateStream.ReadAsyncMemory(), System.Net.Http.MultipartContent.ContentReadStream.ReadAsyncPrivate(), System.Diagnostics.AsyncStreamReader.ReadBufferAsync(), System.IO.StreamReader.ReadBufferAsync(), System.Net.Http.HttpConnection.ReadBufferedAsyncCore(), System.Xml.XmlTextReaderImpl.ReadDataAsync(), System.Net.Http.Http2Connection.ReadFrameAsync(), System.IO.Strategies.BufferedFileStreamStrategy.ReadFromNonSeekableAsync(), System.IO.BufferedStream.ReadFromUnderlyingStreamAsync(), System.Net.WebClient.UploadBitsAsync(), and System.Net.WebSockets.ManagedWebSocket.WaitForServerToCloseConnectionAsync().