Terraria: System.IO.Stream.ValidateBufferArguments
ValidateBufferArguments()
static void System.IO.Stream.ValidateBufferArguments (byte[] buffer, int offset, int count) inline static protected inherited
Definition at line 1044 of file Stream.cs.
    {
        if (buffer == null)
        {
            ThrowHelper.ThrowArgumentNullException(ExceptionArgument.buffer);
        }
        if (offset < 0)
        {
            ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument.offset, ExceptionResource.ArgumentOutOfRange_NeedNonNegNum);
        }
        if ((uint)count > buffer.Length - offset)
        {
            ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument.count, ExceptionResource.Argument_InvalidOffLen);
        }
    }
References System.buffer, System.count, System.offset, System.ThrowHelper.ThrowArgumentNullException(), and System.ThrowHelper.ThrowArgumentOutOfRangeException().
Referenced by System.Net.HttpRequestStream.BeginRead(), System.Net.Base64Stream.BeginRead(), System.Net.Sockets.NetworkStream.BeginRead(), System.IO.FileStream.BeginRead(), System.IO.Stream.BeginReadInternal(), System.Net.RequestStream.BeginWrite(), System.Net.HttpResponseStream.BeginWrite(), System.Net.Mime.EightBitStream.BeginWrite(), System.Net.Mime.QEncodedStream.BeginWrite(), System.Net.Mime.QuotedPrintableStream.BeginWrite(), System.Net.Base64Stream.BeginWrite(), System.Net.Sockets.NetworkStream.BeginWrite(), System.IO.FileStream.BeginWrite(), System.IO.Stream.BeginWriteInternal(), System.Security.Cryptography.CryptoStream.CheckReadArguments(), System.Security.Cryptography.CryptoStream.CheckWriteArguments(), System.Data.SqlTypes.StreamOnSqlBytes.Read(), System.IO.Compression.BrotliStream.Read(), System.IO.Compression.DeflateManagedStream.Read(), System.IO.Compression.DeflateStream.Read(), System.IO.Pipes.PipeStream.Read(), System.IO.ReadOnlyMemoryStream.Read(), System.Net.Http.HttpBaseStream.Read(), System.Net.Http.MultipartContent.ContentReadStream.Read(), System.Net.HttpRequestStream.Read(), System.Net.Base64Stream.Read(), System.Net.Quic.QuicStream.Read(), System.Net.Security.NegotiateStream.Read(), System.Net.Security.SslStream.Read(), System.Net.Sockets.NetworkStream.Read(), System.IO.BufferedStream.Read(), System.IO.MemoryStream.Read(), System.IO.UnmanagedMemoryStream.Read(), System.Text.TranscodingStream.Read(), System.IO.Compression.BrotliStream.ReadAsync(), System.IO.Compression.DeflateManagedStream.ReadAsync(), System.IO.Compression.DeflateStream.ReadAsync(), System.IO.Compression.SubReadStream.ReadAsync(), System.IO.Pipes.PipeStream.ReadAsync(), System.IO.ReadOnlyMemoryStream.ReadAsync(), System.Net.Http.HttpBaseStream.ReadAsync(), System.Net.Http.MultipartContent.ContentReadStream.ReadAsync(), System.Net.Quic.QuicStream.ReadAsync(), System.Net.Security.NegotiateStream.ReadAsync(), System.Net.Security.SslStream.ReadAsync(), System.Net.Sockets.NetworkStream.ReadAsync(), System.IO.BufferedStream.ReadAsync(), System.IO.FileStream.ReadAsync(), System.IO.MemoryStream.ReadAsync(), System.IO.UnmanagedMemoryStream.ReadAsync(), System.Text.TranscodingStream.ReadAsync(), System.IO.ConsoleStream.ValidateRead(), System.IO.FileStream.ValidateReadWriteArgs(), System.IO.ConsoleStream.ValidateWrite(), System.Data.SqlTypes.StreamOnSqlBytes.Write(), System.IO.Compression.BrotliStream.Write(), System.IO.Compression.CheckSumAndSizeWriteStream.Write(), System.IO.Compression.DeflateStream.Write(), System.IO.Compression.ZipArchiveEntry.DirectToArchiveWriterStream.Write(), System.IO.Pipes.PipeStream.Write(), System.Net.Http.HttpContentStream.Write(), System.Net.HttpResponseStream.Write(), System.Net.Mime.EightBitStream.Write(), System.Net.Mime.QEncodedStream.Write(), System.Net.Mime.QuotedPrintableStream.Write(), System.Net.Base64Stream.Write(), System.Net.Quic.QuicStream.Write(), System.Net.RequestStream.Write(), System.Net.Security.NegotiateStream.Write(), System.Net.Security.SslStream.Write(), System.Net.Sockets.NetworkStream.Write(), System.IO.BufferedStream.Write(), System.IO.MemoryStream.Write(), System.IO.UnmanagedMemoryStream.Write(), System.Text.TranscodingStream.Write(), System.IO.Compression.BrotliStream.WriteAsync(), System.IO.Compression.CheckSumAndSizeWriteStream.WriteAsync(), System.IO.Compression.DeflateStream.WriteAsync(), System.IO.Compression.ZipArchiveEntry.DirectToArchiveWriterStream.WriteAsync(), System.IO.Pipes.PipeStream.WriteAsync(), System.Net.Http.HttpBaseStream.WriteAsync(), System.Net.Quic.QuicStream.WriteAsync(), System.Net.RequestStream.WriteAsync(), System.Net.Security.NegotiateStream.WriteAsync(), System.Net.Security.SslStream.WriteAsync(), System.Net.Sockets.NetworkStream.WriteAsync(), System.IO.BufferedStream.WriteAsync(), System.IO.FileStream.WriteAsync(), System.IO.MemoryStream.WriteAsync(), System.IO.UnmanagedMemoryStream.WriteAsync(), and System.Text.TranscodingStream.WriteAsync().