Terraria: System.IO.Stream.Close
Close()
virtual void System.IO.Stream.Close () inline virtual inherited
Reimplemented in System.IO.Compression.PositionPreservingWriteOnlyStreamWrapper, System.Net.Http.EmptyReadStream, System.Net.Mime.QEncodedStream, System.Net.Mime.QuotedPrintableStream, System.Net.Base64Stream, System.Net.ClosableStream, System.Net.DelegatedStream, System.Net.TlsStream, System.Net.TlsStream, and System.IO.Stream.SyncStream.
Definition at line 644 of file Stream.cs.
    {
        Dispose(disposing: true);
        GC.SuppressFinalize(this);
    }
References System.IO.Stream.Dispose(), and System.GC.SuppressFinalize().
Referenced by ReLogic.Peripherals.RGB.SteelSeries.GameSenseConnection._sendMsg(), ReLogic.Peripherals.RGB.SteelSeries.GameSenseConnection._sendServer(), System.Net.CommandStream.Abort(), System.Net.FtpDataStream.AsyncReadCallback(), System.Net.WebSockets.WebSocketBase.CleanUp(), System.Security.Cryptography.CryptoStream.Clear(), System.IO.Compression.PositionPreservingWriteOnlyStreamWrapper.Close(), System.Net.Mail.MailWriter.Close(), System.Net.Mime.MimeWriter.Close(), System.Net.DelegatedStream.Close(), System.Net.TlsStream.Close(), System.Net.FileWebResponse.Close(), System.Net.FtpWebResponse.Close(), System.IO.Stream.SyncStream.Close(), System.Net.HttpListenerResponse.Close(), System.IO.StreamWriter.CloseStreamFromDispose(), System.Net.Mime.MimePart.Complete(), System.Security.Cryptography.PasswordDeriveBytes.ComputeBytes(), System.Net.CommandStream.ContinueCommandPipeline(), System.Net.HttpListenerResponse.Dispose(), System.Net.Mime.MimePart.Dispose(), System.IO.Stream.Dispose(), ReLogic.IO.ConsoleOutputMirror.Dispose(), System.Net.WebSockets.WebSocketHttpListenerDuplexStream.Dispose(), System.IO.BinaryReader.Dispose(), System.IO.BinaryWriter.Dispose(), System.IO.StreamReader.Dispose(), System.IO.BinaryWriter.DisposeAsync(), System.Net.WebClient.DownloadBits(), System.Net.WebClient.DownloadBitsAsync(), System.Net.WebClient.DownloadFile(), System.Net.WebClient.DownloadFileAsync(), System.Net.Mime.MimeWriter.EndClose(), System.Net.FtpWebRequest.FinishRequestStage(), System.Net.FileWebRequest.GetRequestStream(), System.Net.HttpListenerResponse.NonBlockingCloseCallback(), System.Net.FtpDataStream.Read(), Terraria.MessageBuffer.ResetReader(), Terraria.MessageBuffer.ResetWriter(), System.Net.Mime.MimePart.Send(), ReLogic.Peripherals.RGB.SteelSeries.GameSenseConnection.SendJson(), System.Net.Mime.MimePart.SetContent(), System.Net.Mail.AttachmentBase.SetContentFromString(), System.Net.Mail.AttachmentBase.SetContentFromString(), System.Net.HttpRequestStream.UpdateAfterRead(), System.Net.WebClient.UploadFile(), and System.Net.WebClient.UploadFileAsync().