Terraria: System.IO.Stream.ValidateCopyToArguments
ValidateCopyToArguments()
static void System.IO.Stream.ValidateCopyToArguments (Stream destination, int bufferSize) inline static protected inherited
Definition at line 1060 of file Stream.cs.
    {
        if (destination == null)
        {
            throw new ArgumentNullException("destination");
        }
        if (bufferSize <= 0)
        {
            throw new ArgumentOutOfRangeException("bufferSize", bufferSize, SR.ArgumentOutOfRange_NeedPosNum);
        }
        if (!destination.CanWrite)
        {
            if (destination.CanRead)
            {
                ThrowHelper.ThrowNotSupportedException_UnwritableStream();
            }
            ThrowHelper.ThrowObjectDisposedException_StreamClosed(destination.GetType().Name);
        }
    }
References System.SR.ArgumentOutOfRange_NeedPosNum, System.destination, System.ThrowHelper.ThrowNotSupportedException_UnwritableStream(), and System.ThrowHelper.ThrowObjectDisposedException_StreamClosed().
Referenced by System.IO.Compression.DeflateStream.CopyTo(), System.IO.ReadOnlyMemoryStream.CopyTo(), System.Net.Http.Http2Connection.Http2Stream.Http2ReadStream.CopyTo(), System.IO.BufferedStream.CopyTo(), System.IO.FileStream.CopyTo(), System.IO.MemoryStream.CopyTo(), System.IO.Stream.CopyTo(), System.IO.Compression.DeflateStream.CopyToAsync(), System.IO.ReadOnlyMemoryStream.CopyToAsync(), System.Net.Http.DecompressionHandler.DeflateDecompressedContent.ZLibOrDeflateStream.PeekFirstByteReadStream.CopyToAsync(), System.Net.Http.DecompressionHandler.DeflateDecompressedContent.ZLibOrDeflateStream.CopyToAsync(), System.Net.Http.EmptyReadStream.CopyToAsync(), System.Net.Http.Http2Connection.Http2Stream.Http2ReadStream.CopyToAsync(), System.Net.Http.HttpConnection.ChunkedEncodingReadStream.CopyToAsync(), System.Net.Http.HttpConnection.ConnectionCloseReadStream.CopyToAsync(), System.Net.Http.HttpConnection.ContentLengthReadStream.CopyToAsync(), System.Net.Http.HttpConnection.RawConnectionStream.CopyToAsync(), System.Net.Http.HttpContent.LimitMemoryStream.CopyToAsync(), System.IO.BufferedStream.CopyToAsync(), System.IO.FileStream.CopyToAsync(), System.IO.MemoryStream.CopyToAsync(), and System.IO.Stream.CopyToAsync().