Terraria: System.IO.Stream.Flush
Flush()
void System.IO.Stream.Flush () abstract inherited
Referenced by System.Xml.XmlEncodedRawTextWriter.Close(), System.Xml.XmlUtf8RawTextWriter.Close(), System.Net.Security.AuthenticatedStream.Dispose(), System.IO.BinaryWriter.Dispose(), System.ComponentModel.Design.DesigntimeLicenseContextSerializer.StreamWrapper.Flush(), System.Data.SqlTypes.SqlXmlStreamWrapper.Flush(), System.Data.SqlTypes.StreamOnSqlBytes.Flush(), System.IO.Compression.BrotliStream.Flush(), System.IO.Compression.CheckSumAndSizeWriteStream.Flush(), System.IO.Compression.PositionPreservingWriteOnlyStreamWrapper.Flush(), System.IO.Compression.WrappedStream.Flush(), System.IO.DelegatingStream.Flush(), System.Net.DelegatedStream.Flush(), System.IO.BinaryWriter.Flush(), System.IO.BufferedStream.Flush(), System.IO.Stream.SyncStream.Flush(), System.Text.TranscodingStream.Flush(), System.Runtime.Serialization.Json.JsonEncodingStreamWrapper.Flush(), System.Xml.EncodingStreamWrapper.Flush(), System.Xml.XmlStreamNodeWriter.Flush(), System.Xml.XmlEncodedRawTextWriter.Flush(), System.Xml.XmlUtf8RawTextWriter.Flush(), System.Security.Cryptography.CryptoStream.Flush(), System.Text.Json.Utf8JsonWriter.Flush(), System.IO.StreamWriter.Flush(), System.Net.Security.SyncReadWriteAdapter.FlushAsync(), System.IO.Compression.DeflateStream.FlushBuffers(), System.Security.Cryptography.CryptoStream.FlushFinalBlockAsync(), System.IO.BufferedStream.FlushWrite(), System.Net.Mail.MailWriter.OnClose(), and System.Net.Mime.MimeWriter.OnClose().