Terraria: System.IO.Stream.WriteByte
WriteByte()
virtual void System.IO.Stream.WriteByte (byte value) inline virtual inherited
Reimplemented in System.IO.Stream.SyncStream, System.Runtime.Serialization.Json.JsonEncodingStreamWrapper, System.Xml.EncodingStreamWrapper, System.IO.ConsoleStream, System.Data.SqlTypes.SqlXmlStreamWrapper, System.Data.SqlTypes.StreamOnSqlBytes, System.IO.Compression.BrotliStream, System.IO.Compression.CheckSumAndSizeWriteStream, System.IO.Compression.PositionPreservingWriteOnlyStreamWrapper, System.IO.Compression.WrappedStream, System.IO.Compression.ZipArchiveEntry.DirectToArchiveWriterStream, System.IO.Compression.ZLibStream, System.IO.IsolatedStorage.IsolatedStorageFileStream, System.IO.Pipes.PipeStream, System.IO.DelegatingStream, System.Net.Http.HttpBaseStream, System.Net.Http.HttpContent.LimitMemoryStream, System.Net.Http.HttpContent.LimitArrayPoolWriteStream, System.Net.Http.StreamContent.ReadOnlyStream, System.Net.WebSockets.WebSocketHttpListenerDuplexStream, System.Net.Sockets.NetworkStream, System.IO.DelegatingStream, System.IO.Strategies.BufferedFileStreamStrategy, System.IO.Strategies.DerivedFileStreamStrategy, System.IO.Strategies.Net5CompatFileStreamStrategy, System.IO.Strategies.OSFileStreamStrategy, System.IO.BufferedStream, System.IO.FileStream, System.IO.MemoryStream, System.IO.Stream.NullStream, System.IO.UnmanagedMemoryStream, System.IO.UnmanagedMemoryStreamWrapper, System.Text.TranscodingStream, and System.Security.Cryptography.CryptoStream.
Definition at line 1020 of file Stream.cs.
    {
        Write(new byte[1] { value }, 0, 1);
    }
References System.value, and System.IO.Write.
Referenced by System.IO.BinaryWriter.Write(), System.IO.BinaryWriter.Write(), System.IO.BinaryWriter.Write(), System.IO.Stream.SyncStream.WriteByte(), System.Runtime.Serialization.Json.JsonEncodingStreamWrapper.WriteByte(), System.Xml.EncodingStreamWrapper.WriteByte(), System.Data.SqlTypes.SqlXmlStreamWrapper.WriteByte(), System.IO.Compression.PositionPreservingWriteOnlyStreamWrapper.WriteByte(), System.IO.Compression.WrappedStream.WriteByte(), System.IO.Compression.ZLibStream.WriteByte(), System.IO.DelegatingStream.WriteByte(), System.Net.WebSockets.WebSocketHttpListenerDuplexStream.WriteByte(), System.IO.Strategies.DerivedFileStreamStrategy.WriteByte(), and System.IO.FileStream.WriteByte().