Terraria: System.IO.Stream.ReadByte
ReadByte()
virtual int System.IO.Stream.ReadByte () inline virtual inherited
Reimplemented in System.ComponentModel.Design.DesigntimeLicenseContextSerializer.StreamWrapper, System.IO.ConsoleStream, System.Data.SqlTypes.SqlXmlStreamWrapper, System.Data.SqlTypes.StreamOnSqlBytes, System.IO.Compression.BrotliStream, System.IO.Compression.DeflateManagedStream, System.IO.Compression.DeflateStream, System.IO.Compression.GZipStream, System.IO.Compression.SubReadStream, System.IO.Compression.WrappedStream, System.IO.Compression.ZLibStream, System.IO.IsolatedStorage.IsolatedStorageFileStream, System.IO.Pipes.PipeStream, System.IO.DelegatingStream, System.IO.ReadOnlyMemoryStream, System.Net.Http.HttpBaseStream, System.Net.WebSockets.WebSocketHttpListenerDuplexStream, System.Net.BufferedReadStream, System.Net.Security.SslStream, System.Net.Sockets.NetworkStream, System.IO.DelegatingStream, System.IO.Strategies.BufferedFileStreamStrategy, System.IO.Strategies.DerivedFileStreamStrategy, System.IO.Strategies.Net5CompatFileStreamStrategy, System.IO.Strategies.OSFileStreamStrategy, System.IO.BufferedStream, System.IO.FileStream, System.IO.MemoryStream, System.IO.Stream.NullStream, System.IO.Stream.SyncStream, System.IO.UnmanagedMemoryStream, System.IO.UnmanagedMemoryStreamWrapper, System.Text.TranscodingStream, System.Runtime.Serialization.Json.JsonEncodingStreamWrapper, System.Xml.EncodingStreamWrapper, System.Reflection.Internal.ReadOnlyUnmanagedMemoryStream, and System.Security.Cryptography.CryptoStream.
Definition at line 994 of file Stream.cs.
    {
        byte[] array = new byte[1];
        if (Read(array, 0, 1) != 0)
        {
            return array[0];
        }
        return -1;
    }
References System.array, and System.IO.Read.
Referenced by System.Runtime.Serialization.Json.JsonEncodingStreamWrapper.CleanupCharBreak(), System.Xml.EncodingStreamWrapper.CleanupCharBreak(), System.IO.BinaryReader.FillBuffer(), System.IO.BinaryReader.InternalReadByte(), System.Net.Http.DecompressionHandler.DeflateDecompressedContent.ZLibOrDeflateStream.PeekFirstByteReadStream.PeekFirstByte(), System.IO.BinaryReader.Read(), System.Xml.EncodingStreamWrapper.ReadBOMEncoding(), System.ComponentModel.Design.DesigntimeLicenseContextSerializer.StreamWrapper.ReadByte(), System.Data.SqlTypes.SqlXmlStreamWrapper.ReadByte(), System.IO.Compression.WrappedStream.ReadByte(), System.IO.DelegatingStream.ReadByte(), System.Net.WebSockets.WebSocketHttpListenerDuplexStream.ReadByte(), System.IO.Strategies.DerivedFileStreamStrategy.ReadByte(), System.IO.FileStream.ReadByte(), System.IO.Stream.SyncStream.ReadByte(), System.Runtime.Serialization.Json.JsonEncodingStreamWrapper.ReadByte(), System.Xml.EncodingStreamWrapper.ReadByte(), System.Runtime.Serialization.Json.JsonEncodingStreamWrapper.ReadEncoding(), and System.Xml.XmlBufferReader.TryEnsureByte().