Terraria: System.IO.Stream.WriteAsync
WriteAsync() [1/3]
Task System.IO.Stream.WriteAsync (byte[] buffer, int offset, int count) inline inherited
Definition at line 914 of file Stream.cs.
    {
        return WriteAsync(buffer, offset, count, CancellationToken.None);
    }
References System.buffer, System.count, System.Threading.CancellationToken.None, System.offset, and System.IO.Stream.WriteAsync().
Referenced by System.IO.Compression.DeflateStream.CopyToStream.CopyFromSourceToDestinationAsync(), System.IO.Strategies.BufferedFileStreamStrategy.CopyToAsyncCore(), System.Text.TranscodingStream.DisposeAsync(), System.Net.WebClient.DownloadBitsAsync(), System.Xml.XmlEncodedRawTextWriter.EncodeCharsAsync(), System.IO.Compression.DeflateStream.FlushAsync(), System.Text.Json.Utf8JsonWriter.FlushAsync(), System.IO.Compression.BrotliStream.FlushAsyncCore(), System.IO.StreamWriter.FlushAsyncInternal(), System.IO.Strategies.BufferedFileStreamStrategy.FlushAsyncInternal(), System.Xml.XmlStreamNodeWriter.FlushBufferAsync(), System.Xml.XmlUtf8RawTextWriter.FlushBufferAsync(), System.Xml.XmlEncodedRawTextWriter.FlushEncoderAsync(), System.Security.Cryptography.CryptoStream.FlushFinalBlockAsync(), System.Net.Http.Http2Connection.FlushOutgoingBytesAsync(), System.IO.BufferedStream.FlushWriteAsync(), System.IO.Strategies.BufferedFileStreamStrategy._003CReadAsyncSlowPath_003Ed__39.MoveNext(), System.IO.Strategies.BufferedFileStreamStrategy._003CWriteAsyncSlowPath_003Ed__50.MoveNext(), System.IO.Compression.DeflateStream.PurgeBuffersAsync(), System.Net.WebSockets.WebSocketBase.SendFrameAsync(), System.Net.WebSockets.ManagedWebSocket.SendFrameFallbackAsync(), System.Net.WebSockets.ManagedWebSocket.SendFrameLockAcquiredNonCancelableAsync(), System.Net.Http.Http2Connection.SetupAsync(), System.Net.WebClient.UploadBitsAsync(), System.Net.Security.AsyncReadWriteAdapter.WriteAsync(), System.IO.Stream.WriteAsync(), System.IO.Compression.PositionPreservingWriteOnlyStreamWrapper.WriteAsync(), System.IO.Compression.WrappedStream.WriteAsync(), System.IO.DelegatingStream.WriteAsync(), System.Net.DelegatedStream.WriteAsync(), System.IO.FileStream.WriteAsync(), System.Text.TranscodingStream.WriteAsync(), System.IO.Compression.CheckSumAndSizeWriteStream.WriteAsync(), System.IO.Compression.PositionPreservingWriteOnlyStreamWrapper.WriteAsync(), System.IO.Compression.WrappedStream.WriteAsync(), System.IO.DelegatingStream.WriteAsync(), System.Net.DelegatedStream.WriteAsync(), System.IO.Strategies.BufferedFileStreamStrategy.WriteAsync(), System.IO.FileStream.WriteAsync(), System.IO.Stream.WriteAsync(), System.Net.WebSockets.WebSocketHttpListenerDuplexStream.WriteAsyncCore(), System.IO.Compression.DeflateStream.CopyToStream.WriteAsyncCore(), System.Security.Cryptography.CryptoStream.WriteAsyncCore(), System.IO.Compression.BrotliStream.WriteAsyncMemoryCore(), System.IO.Compression.DeflateStream.WriteDeflaterOutputAsync(), System.IO.Strategies.BufferedFileStreamStrategy.WriteToNonSeekableAsync(), System.Net.Http.HttpConnection.WriteToStreamAsync(), and System.IO.BufferedStream.WriteToUnderlyingStreamAsync().