Terraria: System.IO.Stream.SetLength
SetLength()
void System.IO.Stream.SetLength (long value) abstract inherited
Referenced by System.Net.WebClient.DownloadBits(), System.Net.WebClient.DownloadBitsAsync(), System.IO.Stream.SyncStream.SetLength(), System.ComponentModel.Design.DesigntimeLicenseContextSerializer.StreamWrapper.SetLength(), System.Data.SqlTypes.SqlBytes.SetLength(), System.Data.SqlTypes.SqlXmlStreamWrapper.SetLength(), System.IO.Compression.WrappedStream.SetLength(), System.IO.DelegatingStream.SetLength(), System.Net.DelegatedStream.SetLength(), System.IO.Strategies.BufferedFileStreamStrategy.SetLength(), System.IO.Strategies.DerivedFileStreamStrategy.SetLength(), System.IO.BufferedStream.SetLength(), System.IO.FileStream.SetLength(), and System.IO.Compression.ZipArchive.WriteFile().