Terraria: System.IO.Stream.RunReadWriteTaskWhenReady
RunReadWriteTaskWhenReady()
static void System.IO.Stream.RunReadWriteTaskWhenReady (Task asyncWaiter, ReadWriteTask readWriteTask) inline static private inherited
Definition at line 863 of file Stream.cs.
    {
        if (asyncWaiter.IsCompleted)
        {
            RunReadWriteTask(readWriteTask);
            return;
        }
        asyncWaiter.ContinueWith(delegate(Task t, object state)
        {
            ReadWriteTask readWriteTask2 = (ReadWriteTask)state;
            RunReadWriteTask(readWriteTask2);
        }, readWriteTask, default(CancellationToken), TaskContinuationOptions.ExecuteSynchronously, TaskScheduler.Default);
    }
References System.Threading.Tasks.Task< TResult >.ContinueWith(), System.Threading.Tasks.TaskScheduler.Default, System.Threading.Tasks.Task< TResult >.IsCompleted, System.IO.Stream.RunReadWriteTask(), and System.state.
Referenced by System.IO.Stream.BeginReadInternal(), and System.IO.Stream.BeginWriteInternal().