Terraria: System.IO.Stream.CopyToAsync
CopyToAsync() [1/4]
Task System.IO.Stream.CopyToAsync (Stream destination) inline inherited
Definition at line 571 of file Stream.cs.
    {
        return CopyToAsync(destination, GetCopyBufferSize());
    }
References System.IO.Stream.CopyToAsync(), System.destination, and System.IO.Stream.GetCopyBufferSize().
Referenced by System.IO.Compression.DeflateStream.CopyToStream.CopyFromSourceToDestinationAsync(), System.IO.Stream.CopyToAsync(), System.IO.Stream.CopyToAsync(), System.IO.Stream.CopyToAsync(), System.IO.DelegatingStream.CopyToAsync(), System.Net.Http.DecompressionHandler.DeflateDecompressedContent.ZLibOrDeflateStream.PeekFirstByteReadStream.CopyToAsync(), System.Net.Http.DecompressionHandler.DeflateDecompressedContent.ZLibOrDeflateStream.CopyToAsync(), System.IO.FileStream.CopyToAsync(), System.IO.UnmanagedMemoryStreamWrapper.CopyToAsync(), System.IO.Strategies.BufferedFileStreamStrategy.CopyToAsyncCore(), System.IO.BufferedStream.CopyToAsyncCore(), System.Net.Http.HttpConnection.CopyToUntilEofAsync(), System.Net.Http.HttpConnection.CopyToUntilEofWithExistingBufferedDataAsync(), System.Net.Http.HttpClient.GetByteArrayAsyncCore(), and System.Net.Http.HttpClient.GetStringAsyncCore().