Terraria: System.IO.Stream.EndWrite
EndWrite()
virtual void System.IO.Stream.EndWrite (IAsyncResult asyncResult) inline virtual inherited
Reimplemented in System.Net.WebFileStream, System.IO.Compression.BrotliStream, System.IO.Compression.DeflateStream, System.IO.Compression.GZipStream, System.IO.Compression.PositionPreservingWriteOnlyStreamWrapper, System.IO.Compression.ZLibStream, System.IO.IsolatedStorage.IsolatedStorageFileStream, System.IO.Pipes.PipeStream, System.IO.DelegatingStream, System.Net.Http.HttpBaseStream, System.Net.Http.HttpContent.LimitMemoryStream, System.Net.Http.HttpContent.LimitArrayPoolWriteStream, System.Net.WebSockets.WebSocketHttpListenerDuplexStream, System.Net.HttpRequestStream, System.Net.HttpResponseStream, System.Net.Mime.EightBitStream, System.Net.Mime.QEncodedStream, System.Net.Mime.QuotedPrintableStream, System.Net.Base64Stream, System.Net.DelegatedStream, System.Net.Quic.QuicStream, System.Net.FtpDataStream, System.Net.NetworkStreamWrapper, System.Net.RequestStream, System.Net.Security.NegotiateStream, System.Net.Security.SslStream, System.Net.Sockets.NetworkStream, System.IO.DelegatingStream, System.IO.Strategies.BufferedFileStreamStrategy, System.IO.Strategies.DerivedFileStreamStrategy, System.IO.Strategies.Net5CompatFileStreamStrategy, System.IO.Strategies.OSFileStreamStrategy, System.IO.BufferedStream, System.IO.FileStream, System.IO.Stream.NullStream, System.IO.Stream.SyncStream, System.Text.TranscodingStream, System.Security.Cryptography.CryptoStream, System.Net.TlsStream, and System.Net.TlsStream.
Definition at line 889 of file Stream.cs.
    {
        if (asyncResult == null)
        {
            ThrowHelper.ThrowArgumentNullException(ExceptionArgument.asyncResult);
        }
        ReadWriteTask readWriteTask = asyncResult as ReadWriteTask;
        if (readWriteTask == null || readWriteTask._isRead)
        {
            ThrowHelper.ThrowArgumentException(ExceptionResource.InvalidOperation_WrongAsyncResultOrEndCalledMultiple);
        }
        else if (readWriteTask._endCalled)
        {
            ThrowHelper.ThrowInvalidOperationException(ExceptionResource.InvalidOperation_WrongAsyncResultOrEndCalledMultiple);
        }
        try
        {
            readWriteTask.GetAwaiter().GetResult();
        }
        finally
        {
            FinishTrackingAsyncOperation(readWriteTask);
        }
    }
References System.IO.Stream.ReadWriteTask._endCalled, System.IO.Stream.ReadWriteTask._isRead, System.asyncResult, System.IO.Stream.FinishTrackingAsyncOperation(), System.Threading.Tasks.Task< TResult >.GetAwaiter(), System.ThrowHelper.ThrowArgumentException(), System.ThrowHelper.ThrowArgumentNullException(), and System.ThrowHelper.ThrowInvalidOperationException().
Referenced by System.Net.Mime.QEncodedStream.WriteAsyncResult.CompleteWrite(), System.Net.Mime.QuotedPrintableStream.WriteAsyncResult.CompleteWrite(), System.Net.Base64Stream.WriteAsyncResult.CompleteWrite(), System.IO.Compression.PositionPreservingWriteOnlyStreamWrapper.EndWrite(), System.IO.DelegatingStream.EndWrite(), System.Net.DelegatedStream.EndWrite(), System.Net.RequestStream.EndWrite(), System.IO.Strategies.DerivedFileStreamStrategy.EndWrite(), System.IO.FileStream.EndWrite(), System.IO.Stream.SyncStream.EndWrite(), System.Net.Mime.BaseWriter.Flush(), System.Net.Mime.BaseWriter.OnWrite(), and System.Net.Mime.MimePart.WriteCallbackHandler().