Terraria: System.IO.Stream.Write
Write() [1/2]
void System.IO.Stream.Write (byte[] buffer, int offset, int count) abstract inherited
Referenced by System.Xml.EncodingStreamWrapper.EncodingStreamWrapper(), System.Xml.XmlEncodedRawTextWriter.XmlEncodedRawTextWriter(), ReLogic.Peripherals.RGB.SteelSeries.GameSenseConnection._sendServer(), System.IO.Stream.BeginWriteInternal(), System.IO.Compression.DeflateStream.CopyToStream.CopyFromSourceToDestination(), System.Text.TranscodingStream.Dispose(), System.Net.WebClient.DownloadBits(), System.Xml.XmlEncodedRawTextWriter.EncodeChars(), System.IO.Compression.BrotliStream.Flush(), System.Text.Json.Utf8JsonWriter.Flush(), System.IO.StreamWriter.Flush(), System.Net.Mime.BaseWriter.Flush(), System.Xml.XmlStreamNodeWriter.FlushBuffer(), System.Xml.XmlUtf8RawTextWriter.FlushBuffer(), System.IO.Compression.DeflateStream.FlushBuffers(), System.Xml.XmlEncodedRawTextWriter.FlushEncoder(), System.Security.Cryptography.CryptoStream.FlushFinalBlockAsync(), System.IO.Strategies.BufferedFileStreamStrategy.FlushWrite(), System.IO.BufferedStream.FlushWrite(), System.IO.Compression.DeflateStream.PurgeBuffers(), System.Net.Mime.MimePart.Send(), System.Xml.XmlStreamNodeWriter.UnsafeWriteBytes(), System.IO.BinaryWriter.Write(), System.IO.BinaryWriter.Write(), System.ComponentModel.Design.DesigntimeLicenseContextSerializer.StreamWrapper.Write(), System.Data.SqlTypes.SqlXmlStreamWrapper.Write(), System.IO.Compression.CheckSumAndSizeWriteStream.Write(), System.IO.Compression.DeflateStream.CopyToStream.Write(), System.IO.Compression.PositionPreservingWriteOnlyStreamWrapper.Write(), System.IO.Compression.WrappedStream.Write(), System.IO.DelegatingStream.Write(), System.Net.DelegatedStream.Write(), System.IO.Strategies.DerivedFileStreamStrategy.Write(), System.IO.BufferedStream.Write(), System.IO.FileStream.Write(), System.Runtime.Serialization.Json.JsonEncodingStreamWrapper.Write(), System.Xml.EncodingStreamWrapper.Write(), System.IO.Stream.SyncStream.Write(), System.IO.BinaryWriter.Write(), System.IO.BinaryWriter.Write(), System.IO.BinaryWriter.Write(), System.IO.BinaryWriter.Write(), System.IO.BinaryWriter.Write(), System.IO.BinaryWriter.Write(), System.Data.SqlTypes.SqlBytes.Write(), System.IO.BinaryWriter.Write(), System.IO.Compression.PositionPreservingWriteOnlyStreamWrapper.Write(), System.IO.DelegatingStream.Write(), System.IO.BinaryWriter.Write(), System.IO.BufferedStream.Write(), System.IO.FileStream.Write(), System.IO.Stream.SyncStream.Write(), System.Text.TranscodingStream.Write(), System.IO.Compression.CheckSumAndSizeWriteStream.Write(), System.IO.Compression.WrappedStream.Write(), System.IO.BinaryWriter.Write(), System.IO.BinaryWriter.Write(), System.IO.BinaryWriter.Write(), System.IO.BinaryWriter.Write(), System.IO.BinaryWriter.Write(), System.Net.Security.SyncReadWriteAdapter.WriteAsync(), System.Security.Cryptography.CryptoStream.WriteAsyncCore(), System.Xml.XmlStreamNodeWriter.WriteBytes(), System.IO.BinaryWriter.WriteCharsCommonWithoutLengthPrefix(), System.IO.Compression.BrotliStream.WriteCore(), System.IO.Compression.DeflateStream.WriteDeflaterOutput(), System.IO.Compression.ZipArchiveEntry.WriteLocalFileHeaderAndDataIfNeeded(), System.IO.Strategies.BufferedFileStreamStrategy.WriteSpan(), System.Net.Http.HttpConnection.WriteToStream(), System.Net.Http.HttpConnection.WriteToStreamAsync(), and System.Xml.XmlStreamNodeWriter.WriteUTF8Chars().