Terraria: System.IO.Stream.CopyTo
CopyTo() [1/2]
void System.IO.Stream.CopyTo (Stream destination) inline inherited
Definition at line 540 of file Stream.cs.
    {
        CopyTo(destination, GetCopyBufferSize());
    }
References System.IO.Stream.CopyTo(), System.destination, and System.IO.Stream.GetCopyBufferSize().
Referenced by System.IO.Compression.ZipArchive.ZipArchive(), System.IO.Compression.DeflateStream.CopyToStream.CopyFromSourceToDestination(), System.IO.Stream.CopyTo(), System.IO.Strategies.BufferedFileStreamStrategy.CopyTo(), System.IO.BufferedStream.CopyTo(), System.IO.FileStream.CopyTo(), System.Net.Http.HttpConnection.CopyToUntilEofAsync(), System.Net.Http.HttpConnection.CopyToUntilEofWithExistingBufferedDataAsync(), and System.IO.Compression.ZipFileExtensions.ExtractToFile().