Terraria: System.IO.Stream.DisposeAsync
DisposeAsync()
virtual ValueTask System.IO.Stream.DisposeAsync () inline virtual inherited
Implements System.IAsyncDisposable.
Reimplemented in System.IO.Compression.BrotliStream, System.IO.Compression.DeflateStream, System.IO.Compression.GZipStream, System.IO.Compression.ZLibStream, System.IO.IsolatedStorage.IsolatedStorageFileStream, System.IO.DelegatingStream, System.Net.Http.Http3RequestStream.Http3ReadStream, System.Net.Http.MultipartContent.ContentReadStream, System.Net.Security.AuthenticatedStream, System.Net.Security.NegotiateStream, System.Net.Security.SslStream, System.IO.DelegatingStream, System.IO.Strategies.BufferedFileStreamStrategy, System.IO.Strategies.DerivedFileStreamStrategy, System.IO.Strategies.Net5CompatFileStreamStrategy, System.IO.Strategies.OSFileStreamStrategy, System.IO.BufferedStream, System.IO.FileStream, System.IO.Stream.SyncStream, System.Text.TranscodingStream, and System.Security.Cryptography.CryptoStream.
Definition at line 654 of file Stream.cs.
    {
        try
        {
            Dispose();
            return default(ValueTask);
        }
        catch (Exception exception)
        {
            return ValueTask.FromException(exception);
        }
    }
References System.IO.Stream.Dispose(), System.exception, and System.Threading.Tasks.ValueTask< TResult >.FromException().
Referenced by System.IO.Compression.BrotliStream.DisposeAsync(), System.IO.Compression.DeflateStream.DisposeAsync(), System.IO.DelegatingStream.DisposeAsync(), System.Net.Http.Http3RequestStream.DisposeAsync(), System.Net.Security.AuthenticatedStream.DisposeAsync(), System.IO.Strategies.BufferedFileStreamStrategy.DisposeAsync(), System.IO.BufferedStream.DisposeAsync(), System.IO.FileStream.DisposeAsync(), System.IO.Stream.SyncStream.DisposeAsync(), System.Text.TranscodingStream.DisposeAsync(), System.Xml.XmlEncodedRawTextWriter.DisposeAsyncCore(), System.Xml.XmlUtf8RawTextWriter.DisposeAsyncCore(), and System.Security.Cryptography.CryptoStream.DisposeAsyncCore().