Terraria: System.Reflection.Metadata.RuntimeTypeMetadataUpdateHandler.ClearCache
ClearCache() [2/2]
static void System.Reflection.Metadata.RuntimeTypeMetadataUpdateHandler.ClearCache (Type[] types) inline static
Definition at line 8 of file RuntimeTypeMetadataUpdateHandler.cs.
    {
        if (RequiresClearingAllTypes(types))
        {
            Assembly[] assemblies = AppDomain.CurrentDomain.GetAssemblies();
            foreach (Assembly assembly in assemblies)
            {
                if (SkipAssembly(assembly))
                {
                    continue;
                }
                try
                {
                    Type[] types2 = assembly.GetTypes();
                    foreach (Type type in types2)
                    {
                        ClearCache(type);
                    }
                }
                catch (ReflectionTypeLoadException)
                {
                }
            }
        }
        else
        {
            foreach (Type type2 in types)
            {
                ClearCache(type2);
            }
        }
    }
References System.Reflection.Metadata.RuntimeTypeMetadataUpdateHandler.ClearCache(), System.AppDomain.CurrentDomain, System.Reflection.Assembly.GetTypes(), System.Reflection.Metadata.RuntimeTypeMetadataUpdateHandler.RequiresClearingAllTypes(), System.Reflection.Metadata.RuntimeTypeMetadataUpdateHandler.SkipAssembly(), and System.type.
Referenced by System.Reflection.Metadata.RuntimeTypeMetadataUpdateHandler.ClearCache(), and System.Reflection.Metadata.RuntimeTypeMetadataUpdateHandler.ClearCache().