Terraria: System.IO.Stream.FlushAsync
FlushAsync() [1/2]
Task System.IO.Stream.FlushAsync () inline inherited
Definition at line 669 of file Stream.cs.
    {
        return FlushAsync(CancellationToken.None);
    }
References System.IO.Stream.FlushAsync(), and System.Threading.CancellationToken.None.
Referenced by System.Net.Security.AuthenticatedStream.DisposeAsync(), System.IO.Strategies.BufferedFileStreamStrategy.DisposeAsync(), System.IO.Strategies.Net5CompatFileStreamStrategy.DisposeAsync(), System.IO.BinaryWriter.DisposeAsync(), System.IO.BufferedStream.DisposeAsync(), System.Xml.XmlEncodedRawTextWriter.DisposeAsyncCore(), System.Xml.XmlUtf8RawTextWriter.DisposeAsyncCore(), System.Net.Http.HttpBaseStream.Flush(), System.Net.Security.AsyncReadWriteAdapter.FlushAsync(), System.IO.Stream.FlushAsync(), System.Xml.XmlStreamNodeWriter.FlushAsync(), System.Xml.XmlEncodedRawTextWriter.FlushAsync(), System.Xml.XmlUtf8RawTextWriter.FlushAsync(), System.IO.Compression.CheckSumAndSizeWriteStream.FlushAsync(), System.IO.Compression.DeflateStream.FlushAsync(), System.IO.Compression.PositionPreservingWriteOnlyStreamWrapper.FlushAsync(), System.IO.Compression.WrappedStream.FlushAsync(), System.IO.DelegatingStream.FlushAsync(), System.Net.DelegatedStream.FlushAsync(), System.IO.FileStream.FlushAsync(), System.Text.TranscodingStream.FlushAsync(), System.Security.Cryptography.CryptoStream.FlushAsync(), System.Text.Json.Utf8JsonWriter.FlushAsync(), System.IO.Compression.BrotliStream.FlushAsyncCore(), System.IO.StreamWriter.FlushAsyncInternal(), System.IO.BufferedStream.FlushAsyncInternal(), System.Security.Cryptography.CryptoStream.FlushFinalBlockAsync(), System.IO.BufferedStream.FlushWriteAsync(), and System.Net.WebSockets.WebSocketBase.WebSocketOperation.Process().