Terraria: System.IO.Stream.Dispose
Dispose() [1/2]
void System.IO.Stream.Dispose () inline inherited
Implements System.IDisposable.
Definition at line 639 of file Stream.cs.
    {
        Close();
    }
References System.IO.Stream.Close().
Referenced by System.Reflection.PortableExecutable.PEReader.PEReader(), System.IO.Pipes.AnonymousPipeClientStream.~AnonymousPipeClientStream(), System.IO.Pipes.AnonymousPipeServerStream.~AnonymousPipeServerStream(), System.IO.Strategies.BufferedFileStreamStrategy.~BufferedFileStreamStrategy(), System.Net.Http.Http2Connection.Http2Stream.Http2ReadStream.~Http2ReadStream(), System.IO.Pipes.NamedPipeClientStream.~NamedPipeClientStream(), System.IO.Pipes.NamedPipeServerStream.~NamedPipeServerStream(), System.IO.Strategies.Net5CompatFileStreamStrategy.~Net5CompatFileStreamStrategy(), System.Net.Sockets.NetworkStream.~NetworkStream(), System.IO.PinnedBufferMemoryStream.~PinnedBufferMemoryStream(), System.Net.Security.SslStream.~SslStream(), System.IO.Stream.Close(), System.Xml.XmlBufferReader.Close(), System.Xml.XmlStreamNodeWriter.Close(), System.Xml.XmlEncodedRawTextWriter.Close(), System.Xml.XmlSqlBinaryReader.Close(), System.Xml.XmlUtf8RawTextWriter.Close(), System.Xml.XmlTextReaderImpl.ParsingState.Close(), System.Net.Sockets.NetworkStream.Close(), System.IO.Compression.ZipArchive.CloseStreams(), System.IO.Compression.ZipArchiveEntry.CloseStreams(), Terraria.Audio.MP3AudioTrack.Dispose(), Terraria.Audio.WAVAudioTrack.Dispose(), System.IO.Compression.BrotliStream.Dispose(), System.IO.Compression.CheckSumAndSizeWriteStream.Dispose(), System.IO.Compression.DeflateManagedStream.Dispose(), System.IO.Compression.DeflateStream.Dispose(), System.IO.Compression.PositionPreservingWriteOnlyStreamWrapper.Dispose(), System.IO.Compression.WrappedStream.Dispose(), System.IO.DelegatingStream.Dispose(), System.Net.Http.DecompressionHandler.DeflateDecompressedContent.ZLibOrDeflateStream.PeekFirstByteReadStream.Dispose(), System.Net.Http.DecompressionHandler.DeflateDecompressedContent.ZLibOrDeflateStream.Dispose(), System.Net.Http.HttpConnection.Dispose(), System.Net.Http.HttpConnectionResponseContent.Dispose(), System.Net.Http.MultipartContent.ContentReadStream.Dispose(), System.Net.Http.StreamContent.Dispose(), System.Net.Security.AuthenticatedStream.Dispose(), System.IO.Strategies.BufferedFileStreamStrategy.Dispose(), System.IO.BufferedStream.Dispose(), System.Text.TranscodingStream.Dispose(), System.Runtime.Serialization.Json.JsonEncodingStreamWrapper.Dispose(), System.Xml.EncodingStreamWrapper.Dispose(), System.Resources.ResourceWriter.Dispose(), System.Security.Cryptography.CryptoStream.Dispose(), System.IO.Stream.DisposeAsync(), System.Net.WebSockets.ManagedWebSocket.DisposeCore(), System.IO.Strategies.BufferedFileStreamStrategy.DisposeInternal(), System.IO.Strategies.Net5CompatFileStreamStrategy.DisposeInternal(), System.IO.Strategies.OSFileStreamStrategy.DisposeInternal(), System.IO.FileStream.DisposeInternal(), System.Net.Http.Http2Connection.FinalTeardown(), and System.Xml.XmlTextReaderImpl.PopEntity().