Terraria: System.IO.Stream.BeginWrite
BeginWrite()
virtual IAsyncResult System.IO.Stream.BeginWrite (byte[] buffer, int offset, int count, AsyncCallback? callback, object? state) inline virtual inherited
Reimplemented in System.IO.IsolatedStorage.IsolatedStorageFileStream, System.IO.Compression.BrotliStream, System.IO.Compression.DeflateStream, System.IO.Compression.GZipStream, System.IO.Compression.ZLibStream, System.Net.Security.NegotiateStream, System.Net.Security.SslStream, System.IO.Pipes.PipeStream, System.Net.Quic.QuicStream, System.Net.Sockets.NetworkStream, System.IO.BufferedStream, System.IO.FileStream, and System.Security.Cryptography.CryptoStream.
Definition at line 813 of file Stream.cs.
    {
        return BeginWriteInternal(buffer, offset, count, callback, state, serializeAsynchronously: false, apm: true);
    }
References System.IO.Stream.BeginWriteInternal(), System.buffer, System.count, System.offset, and System.state.
Referenced by System.Net.RequestStream.BeginWrite(), System.IO.Compression.PositionPreservingWriteOnlyStreamWrapper.BeginWrite(), System.IO.DelegatingStream.BeginWrite(), System.Net.DelegatedStream.BeginWrite(), System.IO.Strategies.DerivedFileStreamStrategy.BeginWrite(), System.IO.Stream.SyncStream.BeginWrite(), System.IO.FileStream.BeginWrite(), System.Net.Mime.BaseWriter.Flush(), System.Net.Mime.MimePart.ReadCallbackHandler(), System.Net.Mime.QEncodedStream.WriteAsyncResult.Write(), System.Net.Mime.QuotedPrintableStream.WriteAsyncResult.Write(), and System.Net.Base64Stream.WriteAsyncResult.Write().