Terraria: System.IO.Stream.BeginEndReadAsync
BeginEndReadAsync()
Task< int > System.IO.Stream.BeginEndReadAsync (byte[] buffer, int offset, int count) inline private inherited
Definition at line 799 of file Stream.cs.
    {
        if (!HasOverriddenBeginEndRead())
        {
            return BeginReadInternal(buffer, offset, count, null, null, serializeAsynchronously: true, apm: false);
        }
        return TaskFactory<int>.FromAsyncTrim(this, new ReadWriteParameters
        {
            Buffer = buffer,
            Offset = offset,
            Count = count
        }, (Stream stream, ReadWriteParameters args, AsyncCallback callback, object state) => stream.BeginRead(args.Buffer, args.Offset, args.Count, callback, state), (Stream stream, IAsyncResult asyncResult) => stream.EndRead(asyncResult));
    }
References System.asyncResult, System.IO.Stream.BeginReadInternal(), System.buffer, System.count, System.IO.Stream.HasOverriddenBeginEndRead(), System.offset, System.state, and System.stream.
Referenced by System.IO.Stream.ReadAsync().