Terraria: System.IO.Stream.BeginWriteInternal
BeginWriteInternal()
Task System.IO.Stream.BeginWriteInternal (byte[] buffer, int offset, int count, AsyncCallback callback, object state, bool serializeAsynchronously, bool apm) inline package inherited
Definition at line 818 of file Stream.cs.
    {
        ValidateBufferArguments(buffer, offset, count);
        if (!CanWrite)
        {
            ThrowHelper.ThrowNotSupportedException_UnwritableStream();
        }
        SemaphoreSlim semaphoreSlim = EnsureAsyncActiveSemaphoreInitialized();
        Task task = null;
        if (serializeAsynchronously)
        {
            task = semaphoreSlim.WaitAsync();
        }
        else
        {
            semaphoreSlim.Wait();
        }
        ReadWriteTask readWriteTask = new ReadWriteTask(isRead: false, apm, delegate
        {
            ReadWriteTask readWriteTask2 = Task.InternalCurrent as ReadWriteTask;
            try
            {
                readWriteTask2._stream.Write(readWriteTask2._buffer, readWriteTask2._offset, readWriteTask2._count);
                return 0;
            }
            finally
            {
                if (!readWriteTask2._apm)
                {
                    readWriteTask2._stream.FinishTrackingAsyncOperation(readWriteTask2);
                }
                readWriteTask2.ClearBeginState();
            }
        }, state, this, buffer, offset, count, callback);
        if (task != null)
        {
            RunReadWriteTaskWhenReady(task, readWriteTask);
        }
        else
        {
            RunReadWriteTask(readWriteTask);
        }
        return readWriteTask;
    }
References System.IO.Stream.ReadWriteTask._apm, System.IO.Stream.ReadWriteTask._buffer, System.IO.Stream.ReadWriteTask._count, System.IO.Stream.ReadWriteTask._offset, System.IO.Stream.ReadWriteTask._stream, System.buffer, System.IO.Stream.CanWrite, System.IO.Stream.ReadWriteTask.ClearBeginState(), System.count, System.IO.Stream.EnsureAsyncActiveSemaphoreInitialized(), System.IO.Stream.FinishTrackingAsyncOperation(), System.offset, System.IO.Stream.RunReadWriteTask(), System.IO.Stream.RunReadWriteTaskWhenReady(), System.state, System.task, System.ThrowHelper.ThrowNotSupportedException_UnwritableStream(), System.IO.Stream.ValidateBufferArguments(), System.Threading.SemaphoreSlim.Wait(), System.Threading.SemaphoreSlim.WaitAsync(), and System.IO.Stream.Write().
Referenced by System.IO.Stream.BeginEndWriteAsync(), System.IO.Stream.SyncStream.BeginWrite(), System.IO.Stream.BeginWrite(), System.IO.Strategies.Net5CompatFileStreamStrategy.WriteAsync(), and System.IO.Strategies.Net5CompatFileStreamStrategy.WriteAsync().