Terraria: System.Xml.Xsl.Runtime.NamespaceIterator.Create
Create()
void System.Xml.Xsl.Runtime.NamespaceIterator.Create (XPathNavigator context) inline
Definition at line 15 of file NamespaceIterator.cs.
    {
        _navStack.Reset();
        if (!context.MoveToFirstNamespace(XPathNamespaceScope.All))
        {
            return;
        }
        do
        {
            if (context.LocalName.Length != 0 || context.Value.Length != 0)
            {
                _navStack.Push(context.Clone());
            }
        }
        while (context.MoveToNextNamespace(XPathNamespaceScope.All));
        context.MoveToParent();
    }
References System.Xml.Xsl.Runtime.NamespaceIterator._navStack, System.Xml.XPath.XPathNavigator.Clone(), System.Xml.XPath.XPathNavigator.LocalName, System.Xml.XPath.XPathNavigator.MoveToFirstNamespace(), System.Xml.XPath.XPathNavigator.MoveToNextNamespace(), System.Xml.XPath.XPathNavigator.MoveToParent(), System.Xml.Xsl.Runtime.XmlNavigatorStack.Push(), System.Xml.Xsl.Runtime.XmlNavigatorStack.Reset(), and System.Xml.XPath.XPathItem.Value.