Terraria: System.Xml.Serialization.ReflectionXmlSerializationWriter.WriteElements
WriteElements()
void System.Xml.Serialization.ReflectionXmlSerializationWriter.WriteElements (object o, object enumSource, ElementAccessor[] elements, TextAccessor text, ChoiceIdentifierAccessor choice, bool writeAccessors, bool isNullable) inline private
Definition at line 161 of file ReflectionXmlSerializationWriter.cs.
    {
        if (elements.Length == 0 && text == null)
        {
            return;
        }
        if (elements.Length == 1 && text == null)
        {
            WriteElement(o, elements[0], writeAccessors);
        }
        else
        {
            if (isNullable && choice == null && o == null)
            {
                return;
            }
            int num = 0;
            List<ElementAccessor> list = new List<ElementAccessor>();
            ElementAccessor elementAccessor = null;
            foreach (ElementAccessor elementAccessor2 in elements)
            {
                if (elementAccessor2.Any)
                {
                    num++;
                    if (elementAccessor2.Name != null && elementAccessor2.Name.Length > 0)
                    {
                        list.Add(elementAccessor2);
                    }
                    else if (elementAccessor == null)
                    {
                        elementAccessor = elementAccessor2;
                    }
                }
                else if (choice != null)
                {
                    if (o != null && o.GetType() == elementAccessor2.Mapping.TypeDesc.Type)
                    {
                        WriteElement(o, elementAccessor2, writeAccessors);
                        return;
                    }
                }
                else
                {
                    TypeDesc typeDesc = (elementAccessor2.IsUnbounded ? elementAccessor2.Mapping.TypeDesc.CreateArrayTypeDesc() : elementAccessor2.Mapping.TypeDesc);
                    if (o.GetType() == typeDesc.Type)
                    {
                        WriteElement(o, elementAccessor2, writeAccessors);
                        return;
                    }
                }
            }
            if (num > 0 && o is XmlElement xmlElement)
            {
                foreach (ElementAccessor item in list)
                {
                    if (item.Name == xmlElement.Name && item.Namespace == xmlElement.NamespaceURI)
                    {
                        WriteElement(xmlElement, item, writeAccessors);
                        return;
                    }
                }
                if (choice != null)
                {
                    throw CreateChoiceIdentifierValueException(choice.Mapping.TypeDesc.FullName, choice.MemberName, xmlElement.Name, xmlElement.NamespaceURI);
                }
                if (elementAccessor == null)
                {
                    throw CreateUnknownAnyElementException(xmlElement.Name, xmlElement.NamespaceURI);
                }
                WriteElement(xmlElement, elementAccessor, writeAccessors);
            }
            else if (text != null)
            {
                WriteText(o, text);
            }
            else if (elements.Length != 0 && o != null)
            {
                throw CreateUnknownTypeException(o);
            }
        }
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Xml.Serialization.XmlSerializationWriter.CreateChoiceIdentifierValueException(), System.Xml.Serialization.XmlSerializationWriter.CreateUnknownAnyElementException(), System.Xml.Serialization.XmlSerializationWriter.CreateUnknownTypeException(), System.Xml.Dictionary, System.item, System.list, System.text, System.Xml.Serialization.ReflectionXmlSerializationWriter.WriteElement(), and System.Xml.Serialization.ReflectionXmlSerializationWriter.WriteText().
Referenced by System.Xml.Serialization.ReflectionXmlSerializationWriter.WriteArrayItems(), and System.Xml.Serialization.ReflectionXmlSerializationWriter.WriteMember().