Terraria: System.Xml.Serialization.ReflectionXmlSerializationWriter.WriteArrayItems
WriteArrayItems()
void System.Xml.Serialization.ReflectionXmlSerializationWriter.WriteArrayItems (ElementAccessor[] elements, TextAccessor text, ChoiceIdentifierAccessor choice, TypeDesc arrayTypeDesc, object o) inline private
Definition at line 137 of file ReflectionXmlSerializationWriter.cs.
    {
        if (o is IList list)
        {
            for (int i = 0; i < list.Count; i++)
            {
                object o2 = list[i];
                WriteElements(o2, null, elements, text, choice, writeAccessors: true, isNullable: true);
            }
            return;
        }
        IEnumerable enumerable = o as IEnumerable;
        IEnumerator enumerator = enumerable.GetEnumerator();
        if (enumerator != null)
        {
            while (enumerator.MoveNext())
            {
                object current = enumerator.Current;
                WriteElements(current, null, elements, text, choice, writeAccessors: true, isNullable: true);
            }
        }
    }
References System.Xml.Dictionary, System.list, System.text, and System.Xml.Serialization.ReflectionXmlSerializationWriter.WriteElements().
Referenced by System.Xml.Serialization.ReflectionXmlSerializationWriter.WriteArray(), and System.Xml.Serialization.ReflectionXmlSerializationWriter.WriteElement().