Terraria: System.Xml.Serialization.ReflectionXmlSerializationWriter.WriteMember
WriteMember() [1/2]
void System.Xml.Serialization.ReflectionXmlSerializationWriter.WriteMember (object memberValue, AttributeAccessor attribute, TypeDesc memberTypeDesc, object container) inline private
Definition at line 678 of file ReflectionXmlSerializationWriter.cs.
    {
        if (memberTypeDesc.IsAbstract)
        {
            return;
        }
        if (memberTypeDesc.IsArrayLike)
        {
            StringBuilder stringBuilder = new StringBuilder();
            TypeDesc arrayElementTypeDesc = memberTypeDesc.ArrayElementTypeDesc;
            bool flag = CanOptimizeWriteListSequence(arrayElementTypeDesc);
            if (attribute.IsList && flag)
            {
                base.Writer.WriteStartAttribute(null, attribute.Name, (attribute.Form == XmlSchemaForm.Qualified) ? attribute.Namespace : string.Empty);
            }
            if (memberValue == null)
            {
                return;
            }
            IEnumerable enumerable = (IEnumerable)memberValue;
            IEnumerator enumerator = enumerable.GetEnumerator();
            bool flag2 = false;
            if (enumerator == null)
            {
                return;
            }
            while (enumerator.MoveNext())
            {
                object current = enumerator.Current;
                if (attribute.IsList)
                {
                    string stringValue;
                    if (attribute.Mapping is EnumMapping mapping)
                    {
                        stringValue = WriteEnumMethod(mapping, current);
                    }
                    else
                    {
                        WritePrimitiveValue(arrayElementTypeDesc, current, isElement: true, out stringValue);
                    }
                    if (flag)
                    {
                        if (flag2)
{
                            base.Writer.WriteString(" ");
                        }
                        if (current is byte[])
{
                            WriteValue((byte[])current);
                        }
                        else
{
                            WriteValue(stringValue);
                        }
                    }
                    else
                    {
                        if (flag2)
{
                            stringBuilder.Append(' ');
                        }
                        stringBuilder.Append(stringValue);
                    }
                }
                else
                {
                    WriteAttribute(current, attribute, container);
                }
                flag2 = true;
            }
            if (attribute.IsList)
            {
                if (flag)
                {
                    base.Writer.WriteEndAttribute();
                }
                else if (stringBuilder.Length != 0)
                {
                    string ns = ((attribute.Form == XmlSchemaForm.Qualified) ? attribute.Namespace : string.Empty);
                    WriteAttribute(attribute.Name, ns, stringBuilder.ToString());
                }
            }
        }
        else
        {
            WriteAttribute(memberValue, attribute, container);
        }
    }
References System.Xml.Serialization.ReflectionXmlSerializationWriter.CanOptimizeWriteListSequence(), System.Xml.Dictionary, System.Xml.Serialization.ReflectionXmlSerializationWriter.WriteAttribute, System.Xml.Serialization.ReflectionXmlSerializationWriter.WriteEnumMethod(), System.Xml.Serialization.ReflectionXmlSerializationWriter.WritePrimitiveValue(), and System.Xml.Serialization.XmlSerializationWriter.WriteValue().