Terraria: System.Xml.Serialization.ReflectionXmlSerializationWriter.CreateXmlSerializationWriteCallback
CreateXmlSerializationWriteCallback()
XmlSerializationWriteCallback System.Xml.Serialization.ReflectionXmlSerializationWriter.CreateXmlSerializationWriteCallback (TypeMapping mapping, string name, string ns, bool isNullable) inline private
Definition at line 411 of file ReflectionXmlSerializationWriter.cs.
    {
        StructMapping structMapping = mapping as StructMapping;
        if (structMapping != null)
        {
            return Wrapper;
        }
        EnumMapping enumMapping = mapping as EnumMapping;
        if (enumMapping != null)
        {
            return delegate(object o)
            {
                WriteEnumMethod(enumMapping, o);
            };
        }
        throw new InvalidOperationException(System.SR.XmlInternalError);
        [RequiresUnreferencedCode("calls WriteStructMethod")]
        void Wrapper(object o)
        {
            WriteStructMethod(structMapping, name, ns, o, isNullable, needType: false);
        }
    }
References System.Xml.Dictionary, System.Xml.Serialization.ReflectionXmlSerializationWriter.WriteEnumMethod(), System.Xml.Serialization.ReflectionXmlSerializationWriter.WriteStructMethod(), and System.SR.XmlInternalError.
Referenced by System.Xml.Serialization.ReflectionXmlSerializationWriter.InitCallbacks().