Terraria: System.Xml.Serialization.ReflectionXmlSerializationWriter.WriteEnumAndArrayTypes
WriteEnumAndArrayTypes()
bool System.Xml.Serialization.ReflectionXmlSerializationWriter.WriteEnumAndArrayTypes (StructMapping structMapping, object o, string n, string ns) inline private
Definition at line 591 of file ReflectionXmlSerializationWriter.cs.
    {
        Type type = o.GetType();
        foreach (object typeMapping in _mapping.Scope.TypeMappings)
        {
            if (typeMapping is EnumMapping enumMapping && enumMapping.TypeDesc.Type == type)
            {
                base.Writer.WriteStartElement(n, ns);
                WriteXsiType(enumMapping.TypeName, ns);
                base.Writer.WriteString(WriteEnumMethod(enumMapping, o));
                base.Writer.WriteEndElement();
                return true;
            }
            if (typeMapping is ArrayMapping arrayMapping && arrayMapping.TypeDesc.Type == type)
            {
                base.Writer.WriteStartElement(n, ns);
                WriteXsiType(arrayMapping.TypeName, ns);
                WriteMember(o, null, arrayMapping.ElementsSortedByDerivation, null, null, arrayMapping.TypeDesc, writeAccessors: true);
                base.Writer.WriteEndElement();
                return true;
            }
        }
        return false;
    }
References System.Xml.Serialization.ReflectionXmlSerializationWriter._mapping, System.Xml.Serialization.XmlMapping.Scope, System.type, System.Xml.Serialization.TypeScope.TypeMappings, System.Xml.Serialization.ReflectionXmlSerializationWriter.WriteEnumMethod(), System.Xml.Serialization.ReflectionXmlSerializationWriter.WriteMember(), and System.Xml.Serialization.XmlSerializationWriter.WriteXsiType().
Referenced by System.Xml.Serialization.ReflectionXmlSerializationWriter.WriteStructMethod().