Terraria: System.Xml.Serialization.ReflectionXmlSerializationWriter.WritePrimitive
WritePrimitive()
void System.Xml.Serialization.ReflectionXmlSerializationWriter.WritePrimitive (WritePrimitiveMethodRequirement method, string name, string ns, object defaultValue, object o, TypeMapping mapping, bool writeXsiType, bool isElement, bool isNullable) inline private
Definition at line 824 of file ReflectionXmlSerializationWriter.cs.
    {
        TypeDesc typeDesc = mapping.TypeDesc;
        if (defaultValue != null && defaultValue != DBNull.Value && mapping.TypeDesc.HasDefaultSupport)
        {
            if (mapping is EnumMapping)
            {
                if (((EnumMapping)mapping).IsFlags)
                {
                    IEnumerable<string> values = defaultValue.ToString().Split((char[]?)null, StringSplitOptions.RemoveEmptyEntries);
                    string text = string.Join(", ", values);
                    if (o.ToString() == text)
                    {
                        return;
                    }
                }
                else if (o.ToString() == defaultValue.ToString())
                {
                    return;
                }
            }
            else if (IsDefaultValue(mapping, o, defaultValue, isNullable))
            {
                return;
            }
        }
        XmlQualifiedName xsiType = null;
        if (writeXsiType)
        {
            xsiType = new XmlQualifiedName(mapping.TypeName, mapping.Namespace);
        }
        string stringValue = null;
        bool flag = false;
        if (mapping is EnumMapping mapping2)
        {
            stringValue = WriteEnumMethod(mapping2, o);
            flag = true;
        }
        else
        {
            flag = WritePrimitiveValue(typeDesc, o, isElement, out stringValue);
        }
        if (flag)
        {
            if (hasRequirement(method, WritePrimitiveMethodRequirement.WriteElementString))
            {
                if (hasRequirement(method, WritePrimitiveMethodRequirement.Raw))
                {
                    WriteElementStringRaw(name, ns, stringValue, xsiType);
                }
                else
                {
                    WriteElementString(name, ns, stringValue, xsiType);
                }
            }
            else if (hasRequirement(method, WritePrimitiveMethodRequirement.WriteNullableStringLiteral))
            {
                if (hasRequirement(method, WritePrimitiveMethodRequirement.Encoded))
                {
                    if (hasRequirement(method, WritePrimitiveMethodRequirement.Raw))
                    {
                        WriteNullableStringEncodedRaw(name, ns, stringValue, xsiType);
                    }
                    else
                    {
                        WriteNullableStringEncoded(name, ns, stringValue, xsiType);
                    }
                }
                else if (hasRequirement(method, WritePrimitiveMethodRequirement.Raw))
                {
                    WriteNullableStringLiteralRaw(name, ns, stringValue);
                }
                else
                {
                    WriteNullableStringLiteral(name, ns, stringValue);
                }
            }
            else if (hasRequirement(method, WritePrimitiveMethodRequirement.WriteAttribute))
            {
                WriteAttribute(name, ns, stringValue);
            }
        }
        else if (o is byte[] value)
        {
            if (hasRequirement(method, WritePrimitiveMethodRequirement.Raw | WritePrimitiveMethodRequirement.WriteElementString))
            {
                WriteElementStringRaw(name, ns, XmlSerializationWriter.FromByteArrayBase64(value));
            }
            else if (hasRequirement(method, WritePrimitiveMethodRequirement.Raw | WritePrimitiveMethodRequirement.WriteNullableStringLiteral))
            {
                WriteNullableStringLiteralRaw(name, ns, XmlSerializationWriter.FromByteArrayBase64(value));
            }
            else if (hasRequirement(method, WritePrimitiveMethodRequirement.WriteAttribute))
            {
                WriteAttribute(name, ns, value);
            }
        }
    }
References System.Xml.Serialization.XmlSerializationWriter.FromByteArrayBase64(), System.Xml.Serialization.ReflectionXmlSerializationWriter.hasRequirement(), System.Xml.Serialization.ReflectionXmlSerializationWriter.IsDefaultValue(), System.text, System.DBNull.Value, System.value, System.values, System.Xml.Serialization.ReflectionXmlSerializationWriter.WriteAttribute, System.Xml.Serialization.ReflectionXmlSerializationWriter.WriteElementString, System.Xml.Serialization.XmlSerializationWriter.WriteElementStringRaw(), System.Xml.Serialization.ReflectionXmlSerializationWriter.WriteEnumMethod(), System.Xml.Serialization.XmlSerializationWriter.WriteNullableStringEncoded(), System.Xml.Serialization.XmlSerializationWriter.WriteNullableStringEncodedRaw(), System.Xml.Serialization.ReflectionXmlSerializationWriter.WriteNullableStringLiteral, System.Xml.Serialization.XmlSerializationWriter.WriteNullableStringLiteralRaw(), and System.Xml.Serialization.ReflectionXmlSerializationWriter.WritePrimitiveValue().
Referenced by System.Xml.Serialization.ReflectionXmlSerializationWriter.WriteAttribute(), and System.Xml.Serialization.ReflectionXmlSerializationWriter.WriteElement().