Terraria: System.Xml.Serialization.ReflectionXmlSerializationWriter.GenerateMembersElement
GenerateMembersElement()
void System.Xml.Serialization.ReflectionXmlSerializationWriter.GenerateMembersElement (object o, XmlMembersMapping xmlMembersMapping) inline private
Definition at line 1043 of file ReflectionXmlSerializationWriter.cs.
    {
        ElementAccessor accessor = xmlMembersMapping.Accessor;
        MembersMapping membersMapping = (MembersMapping)accessor.Mapping;
        bool hasWrapperElement = membersMapping.HasWrapperElement;
        bool writeAccessors = membersMapping.WriteAccessors;
        bool flag = xmlMembersMapping.IsSoap && writeAccessors;
        WriteStartDocument();
        if (!membersMapping.IsSoap)
        {
            TopLevelElement();
        }
        object[] array = (object[])o;
        int num = array.Length;
        if (hasWrapperElement)
        {
            WriteStartElement(accessor.Name, (accessor.Form == XmlSchemaForm.Qualified) ? accessor.Namespace : string.Empty, membersMapping.IsSoap);
            int num2 = FindXmlnsIndex(membersMapping.Members);
            if (num2 >= 0)
            {
                XmlSerializerNamespaces xmlns = (XmlSerializerNamespaces)array[num2];
                if (num > num2)
                {
                    WriteNamespaceDeclarations(xmlns);
                }
            }
            for (int i = 0; i < membersMapping.Members.Length; i++)
            {
                MemberMapping memberMapping = membersMapping.Members[i];
                if (memberMapping.Attribute == null || memberMapping.Ignore)
                {
                    continue;
                }
                object memberValue = array[i];
                bool? flag2 = null;
                if (memberMapping.CheckSpecified != 0)
                {
                    string text = memberMapping.Name + "Specified";
                    for (int j = 0; j < Math.Min(num, membersMapping.Members.Length); j++)
                    {
                        if (membersMapping.Members[j].Name == text)
{
                            flag2 = (bool)array[j];
                            break;
                        }
                    }
                }
                if (num > i && (!flag2.HasValue || flag2.Value))
                {
                    WriteMember(memberValue, memberMapping.Attribute, memberMapping.TypeDesc, null);
                }
            }
        }
        for (int k = 0; k < membersMapping.Members.Length; k++)
        {
            MemberMapping memberMapping2 = membersMapping.Members[k];
            if (memberMapping2.Xmlns != null || memberMapping2.Ignore)
            {
                continue;
            }
            bool? flag3 = null;
            if (memberMapping2.CheckSpecified != 0)
            {
                string text2 = memberMapping2.Name + "Specified";
                for (int l = 0; l < Math.Min(num, membersMapping.Members.Length); l++)
                {
                    if (membersMapping.Members[l].Name == text2)
                    {
                        flag3 = (bool)array[l];
                        break;
                    }
                }
            }
            if (num <= k || (flag3.HasValue && !flag3.Value))
            {
                continue;
            }
            object o2 = array[k];
            object choiceSource = null;
            if (memberMapping2.ChoiceIdentifier != null)
            {
                for (int m = 0; m < membersMapping.Members.Length; m++)
                {
                    if (membersMapping.Members[m].Name == memberMapping2.ChoiceIdentifier.MemberName)
                    {
                        choiceSource = array[m];
                        break;
                    }
                }
            }
            if (flag && memberMapping2.IsReturnValue && memberMapping2.Elements.Length != 0)
            {
                WriteRpcResult(memberMapping2.Elements[0].Name, string.Empty);
            }
            WriteMember(o2, choiceSource, memberMapping2.ElementsSortedByDerivation, memberMapping2.Text, memberMapping2.ChoiceIdentifier, memberMapping2.TypeDesc, writeAccessors || hasWrapperElement);
        }
        if (hasWrapperElement)
        {
            WriteEndElement();
        }
        if (!accessor.IsSoap)
        {
            return;
        }
        if (!hasWrapperElement && !writeAccessors && num > membersMapping.Members.Length)
        {
            for (int n = membersMapping.Members.Length; n < num; n++)
            {
                if (array[n] != null)
                {
                    WritePotentiallyReferencingElement(null, null, array[n], array[n].GetType(), suppressReference: true, isNullable: false);
                }
            }
        }
        WriteReferencedElements();
    }
References System.array, System.Xml.Dictionary, System.Xml.Serialization.ReflectionXmlSerializationWriter.FindXmlnsIndex(), System.Math.Min(), System.text, System.Xml.Serialization.XmlSerializationWriter.TopLevelElement(), System.Xml.Serialization.XmlSerializationWriter.WriteEndElement(), System.Xml.Serialization.ReflectionXmlSerializationWriter.WriteMember(), System.Xml.Serialization.XmlSerializationWriter.WriteNamespaceDeclarations(), System.Xml.Serialization.XmlSerializationWriter.WritePotentiallyReferencingElement(), System.Xml.Serialization.XmlSerializationWriter.WriteReferencedElements(), System.Xml.Serialization.XmlSerializationWriter.WriteRpcResult(), System.Xml.Serialization.XmlSerializationWriter.WriteStartDocument(), and System.Xml.Serialization.XmlSerializationWriter.WriteStartElement().
Referenced by System.Xml.Serialization.ReflectionXmlSerializationWriter.WriteObject().