Terraria: Terraria.GameContent.Events.MoonlordDeathDrama.Update
Update()
static void Terraria.GameContent.Events.MoonlordDeathDrama.Update () inline static
Definition at line 158 of file MoonlordDeathDrama.cs.
    {
        for (int i = 0; i < _pieces.Count; i++)
        {
            MoonlordPiece moonlordPiece = _pieces[i];
            moonlordPiece.Update();
            if (moonlordPiece.Dead)
            {
                _pieces.Remove(moonlordPiece);
                i--;
            }
        }
        for (int j = 0; j < _explosions.Count; j++)
        {
            MoonlordExplosion moonlordExplosion = _explosions[j];
            moonlordExplosion.Update();
            if (moonlordExplosion.Dead)
            {
                _explosions.Remove(moonlordExplosion);
                j--;
            }
        }
        bool flag = false;
        for (int k = 0; k < _lightSources.Count; k++)
        {
            if (Main.player[Main.myPlayer].Distance(_lightSources[k]) < 2000f)
            {
                flag = true;
                break;
            }
        }
        _lightSources.Clear();
        if (!flag)
        {
            requestedLight = 0f;
        }
        if (requestedLight != whitening)
        {
            if (Math.Abs(requestedLight - whitening) < 0.02f)
            {
                whitening = requestedLight;
            }
            else
            {
                whitening += (float)Math.Sign(requestedLight - whitening) * 0.02f;
            }
        }
        requestedLight = 0f;
    }
References Terraria.GameContent.Events.MoonlordDeathDrama._explosions, Terraria.GameContent.Events.MoonlordDeathDrama._lightSources, Terraria.GameContent.Events.MoonlordDeathDrama._pieces, System.Math.Abs(), Terraria.Main.myPlayer, Terraria.Main.player, Terraria.GameContent.Events.MoonlordDeathDrama.requestedLight, System.Math.Sign(), and Terraria.GameContent.Events.MoonlordDeathDrama.whitening.
Referenced by Terraria.Main.DoUpdate().