Terraria: System.Xml.Serialization.ReflectionXmlSerializationWriter.WriteQualifiedNameElement
WriteQualifiedNameElement()
void System.Xml.Serialization.ReflectionXmlSerializationWriter.WriteQualifiedNameElement (string name, string ns, object defaultValue, XmlQualifiedName o, bool nullable, bool isSoap, PrimitiveMapping mapping) inline private
Definition at line 434 of file ReflectionXmlSerializationWriter.cs.
    {
        if (defaultValue != null && defaultValue != DBNull.Value && mapping.TypeDesc.HasDefaultSupport && IsDefaultValue(mapping, o, defaultValue, nullable))
        {
            return;
        }
        if (isSoap)
        {
            if (nullable)
            {
                WriteNullableQualifiedNameEncoded(name, ns, o, new XmlQualifiedName(mapping.TypeName, mapping.Namespace));
            }
            else
            {
                WriteElementQualifiedName(name, ns, o, new XmlQualifiedName(mapping.TypeName, mapping.Namespace));
            }
        }
        else if (nullable)
        {
            WriteNullableQualifiedNameLiteral(name, ns, o);
        }
        else
        {
            WriteElementQualifiedName(name, ns, o);
        }
    }
References System.Xml.Serialization.ReflectionXmlSerializationWriter.IsDefaultValue(), System.DBNull.Value, System.Xml.Serialization.XmlSerializationWriter.WriteElementQualifiedName(), System.Xml.Serialization.XmlSerializationWriter.WriteNullableQualifiedNameEncoded(), and System.Xml.Serialization.XmlSerializationWriter.WriteNullableQualifiedNameLiteral().
Referenced by System.Xml.Serialization.ReflectionXmlSerializationWriter.WriteElement().