Terraria: System.Xml.Serialization.ReflectionXmlSerializationWriter.WriteText
WriteText()
void System.Xml.Serialization.ReflectionXmlSerializationWriter.WriteText (object o, TextAccessor text) inline private
Definition at line 243 of file ReflectionXmlSerializationWriter.cs.
    {
        if (text.Mapping is PrimitiveMapping primitiveMapping)
        {
            string stringValue;
            if (text.Mapping is EnumMapping mapping)
            {
                stringValue = WriteEnumMethod(mapping, o);
            }
            else
            {
                WritePrimitiveValue(primitiveMapping.TypeDesc, o, isElement: false, out stringValue);
            }
            if (o is byte[] value)
            {
                WriteValue(value);
            }
            else
            {
                WriteValue(stringValue);
            }
        }
        else if (text.Mapping is SpecialMapping specialMapping)
        {
            TypeKind kind = specialMapping.TypeDesc.Kind;
            if (kind != TypeKind.Node)
            {
                throw new InvalidOperationException(System.SR.XmlInternalError);
            }
            ((XmlNode)o).WriteTo(base.Writer);
        }
    }
References System.Xml.Dictionary, System.text, System.value, System.Xml.Serialization.ReflectionXmlSerializationWriter.WriteEnumMethod(), System.Xml.Serialization.ReflectionXmlSerializationWriter.WritePrimitiveValue(), System.Xml.Serialization.XmlSerializationWriter.WriteValue(), and System.SR.XmlInternalError.
Referenced by System.Xml.Serialization.ReflectionXmlSerializationWriter.WriteElements().