Terraria: System.Xml.Serialization.ReflectionXmlSerializationWriter.WritePrimitiveValue
WritePrimitiveValue()
bool System.Xml.Serialization.ReflectionXmlSerializationWriter.WritePrimitiveValue (TypeDesc typeDesc, object o, bool isElement, out string stringValue) inline private
Definition at line 942 of file ReflectionXmlSerializationWriter.cs.
    {
        if (typeDesc == ReflectionXmlSerializationReader.StringTypeDesc || typeDesc.FormatterName == "String")
        {
            stringValue = (string)o;
            return true;
        }
        if (!typeDesc.HasCustomFormatter)
        {
            stringValue = ConvertPrimitiveToString(o, typeDesc);
            return true;
        }
        if (o is byte[] && typeDesc.FormatterName == "ByteArrayHex")
        {
            stringValue = XmlSerializationWriter.FromByteArrayHex((byte[])o);
            return true;
        }
        if (o is DateTime)
        {
            if (typeDesc.FormatterName == "DateTime")
            {
                stringValue = XmlSerializationWriter.FromDateTime((DateTime)o);
                return true;
            }
            if (typeDesc.FormatterName == "Date")
            {
                stringValue = XmlSerializationWriter.FromDate((DateTime)o);
                return true;
            }
            if (typeDesc.FormatterName == "Time")
            {
                stringValue = XmlSerializationWriter.FromTime((DateTime)o);
                return true;
            }
            throw new InvalidOperationException(System.SR.Format(System.SR.XmlInternalErrorDetails, "Invalid DateTime"));
        }
        if (typeDesc == ReflectionXmlSerializationReader.QnameTypeDesc)
        {
            stringValue = FromXmlQualifiedName((XmlQualifiedName)o);
            return true;
        }
        if (o is string)
        {
            switch (typeDesc.FormatterName)
            {
            case "XmlName":
                stringValue = XmlSerializationWriter.FromXmlName((string)o);
                break;
            case "XmlNCName":
                stringValue = XmlSerializationWriter.FromXmlNCName((string)o);
                break;
            case "XmlNmToken":
                stringValue = XmlSerializationWriter.FromXmlNmToken((string)o);
                break;
            case "XmlNmTokens":
                stringValue = XmlSerializationWriter.FromXmlNmTokens((string)o);
                break;
            default:
                stringValue = null;
                return false;
            }
            return true;
        }
        if (o is char && typeDesc.FormatterName == "Char")
        {
            stringValue = XmlSerializationWriter.FromChar((char)o);
            return true;
        }
        if (!(o is byte[]))
        {
            throw new InvalidOperationException(System.SR.XmlInternalError);
        }
        stringValue = null;
        return false;
    }
References System.Xml.Serialization.ReflectionXmlSerializationWriter.ConvertPrimitiveToString(), System.SR.Format(), System.Xml.Serialization.XmlSerializationWriter.FromByteArrayHex(), System.Xml.Serialization.XmlSerializationWriter.FromChar(), System.Xml.Serialization.XmlSerializationWriter.FromDate(), System.Xml.Serialization.XmlSerializationWriter.FromDateTime(), System.Xml.Serialization.XmlSerializationWriter.FromTime(), System.Xml.Serialization.XmlSerializationWriter.FromXmlName(), System.Xml.Serialization.XmlSerializationWriter.FromXmlNCName(), System.Xml.Serialization.XmlSerializationWriter.FromXmlNmToken(), System.Xml.Serialization.XmlSerializationWriter.FromXmlNmTokens(), System.Xml.Serialization.XmlSerializationWriter.FromXmlQualifiedName(), System.Xml.Serialization.ReflectionXmlSerializationReader.QnameTypeDesc, System.Xml.Serialization.ReflectionXmlSerializationReader.StringTypeDesc, System.SR.XmlInternalError, and System.SR.XmlInternalErrorDetails.
Referenced by System.Xml.Serialization.ReflectionXmlSerializationWriter.WriteMember(), System.Xml.Serialization.ReflectionXmlSerializationWriter.WritePrimitive(), and System.Xml.Serialization.ReflectionXmlSerializationWriter.WriteText().