Terraria: System.Xml.Serialization.ReflectionXmlSerializationWriter.WriteStructMethod
WriteStructMethod()
void System.Xml.Serialization.ReflectionXmlSerializationWriter.WriteStructMethod (StructMapping mapping, string n, string ns, object o, bool isNullable, bool needType) inline private
Definition at line 462 of file ReflectionXmlSerializationWriter.cs.
    {
        if (mapping.IsSoap && mapping.TypeDesc.IsRoot)
        {
            return;
        }
        if (!mapping.IsSoap)
        {
            if (o == null)
            {
                if (isNullable)
                {
                    WriteNullTagLiteral(n, ns);
                }
                return;
            }
            if (!needType && o.GetType() != mapping.TypeDesc.Type)
            {
                if (!WriteDerivedTypes(mapping, n, ns, o, isNullable))
                {
                    if (!mapping.TypeDesc.IsRoot)
                    {
                        throw CreateUnknownTypeException(o);
                    }
                    if (!WriteEnumAndArrayTypes(mapping, o, n, ns))
                    {
                        WriteTypedPrimitive(n, ns, o, xsiType: true);
                    }
                }
                return;
            }
        }
        if (mapping.TypeDesc.IsAbstract)
        {
            return;
        }
        if (mapping.TypeDesc.Type != null && typeof(XmlSchemaObject).IsAssignableFrom(mapping.TypeDesc.Type))
        {
            base.EscapeName = false;
        }
        XmlSerializerNamespaces xmlSerializerNamespaces = null;
        MemberMapping[] allMembers = TypeScope.GetAllMembers(mapping);
        int num = FindXmlnsIndex(allMembers);
        if (num >= 0)
        {
            MemberMapping memberMapping = allMembers[num];
            xmlSerializerNamespaces = (XmlSerializerNamespaces)GetMemberValue(o, memberMapping.Name);
        }
        if (!mapping.IsSoap)
        {
            WriteStartElement(n, ns, o, writePrefixed: false, xmlSerializerNamespaces);
            if (!mapping.TypeDesc.IsRoot && needType)
            {
                WriteXsiType(mapping.TypeName, mapping.Namespace);
            }
        }
        else if (xmlSerializerNamespaces != null)
        {
            WriteNamespaceDeclarations(xmlSerializerNamespaces);
        }
        foreach (MemberMapping memberMapping2 in allMembers)
        {
            bool flag = true;
            bool flag2 = true;
            if (memberMapping2.CheckSpecified != 0)
            {
                string memberName = memberMapping2.Name + "Specified";
                flag = (bool)GetMemberValue(o, memberName);
            }
            if (memberMapping2.CheckShouldPersist)
            {
                string name = "ShouldSerialize" + memberMapping2.Name;
                MethodInfo method = o.GetType().GetMethod(name, BindingFlags.DeclaredOnly | BindingFlags.Instance | BindingFlags.Static | BindingFlags.Public | BindingFlags.NonPublic);
                flag2 = (bool)method.Invoke(o, Array.Empty<object>());
            }
            if (memberMapping2.Attribute != null && flag && flag2)
            {
                object memberValue = GetMemberValue(o, memberMapping2.Name);
                WriteMember(memberValue, memberMapping2.Attribute, memberMapping2.TypeDesc, o);
            }
        }
        foreach (MemberMapping memberMapping3 in allMembers)
        {
            if (memberMapping3.Xmlns != null)
            {
                continue;
            }
            bool flag3 = true;
            bool flag4 = true;
            if (memberMapping3.CheckSpecified != 0)
            {
                string memberName2 = memberMapping3.Name + "Specified";
                flag3 = (bool)GetMemberValue(o, memberName2);
            }
            if (memberMapping3.CheckShouldPersist)
            {
                string name2 = "ShouldSerialize" + memberMapping3.Name;
                MethodInfo method2 = o.GetType().GetMethod(name2, BindingFlags.DeclaredOnly | BindingFlags.Instance | BindingFlags.Static | BindingFlags.Public | BindingFlags.NonPublic);
                flag4 = (bool)method2.Invoke(o, Array.Empty<object>());
            }
            if (!memberMapping3.CheckShouldPersist || (memberMapping3.Elements.Length == 0 && memberMapping3.Text == null))
            {
                flag4 = true;
            }
            if (flag3 && flag4)
            {
                object choiceSource = null;
                if (memberMapping3.ChoiceIdentifier != null)
                {
                    choiceSource = GetMemberValue(o, memberMapping3.ChoiceIdentifier.MemberName);
                }
                object memberValue2 = GetMemberValue(o, memberMapping3.Name);
                WriteMember(memberValue2, choiceSource, memberMapping3.ElementsSortedByDerivation, memberMapping3.Text, memberMapping3.ChoiceIdentifier, memberMapping3.TypeDesc, writeAccessors: true);
            }
        }
        if (!mapping.IsSoap)
        {
            WriteEndElement(o);
        }
    }
References System.Xml.Serialization.XmlSerializationWriter.CreateUnknownTypeException(), System.Xml.Dictionary, System.Xml.Serialization.ReflectionXmlSerializationWriter.FindXmlnsIndex(), System.Xml.Serialization.TypeScope.GetAllMembers(), System.Xml.Serialization.ReflectionXmlSerializationWriter.GetMemberValue(), System.Xml.Serialization.ReflectionXmlSerializationWriter.WriteDerivedTypes(), System.Xml.Serialization.XmlSerializationWriter.WriteEndElement(), System.Xml.Serialization.ReflectionXmlSerializationWriter.WriteEnumAndArrayTypes(), System.Xml.Serialization.ReflectionXmlSerializationWriter.WriteMember(), System.Xml.Serialization.XmlSerializationWriter.WriteNamespaceDeclarations(), System.Xml.Serialization.XmlSerializationWriter.WriteNullTagLiteral(), System.Xml.Serialization.XmlSerializationWriter.WriteStartElement(), System.Xml.Serialization.XmlSerializationWriter.WriteTypedPrimitive(), and System.Xml.Serialization.XmlSerializationWriter.WriteXsiType().
Referenced by System.Xml.Serialization.ReflectionXmlSerializationWriter.CreateXmlSerializationWriteCallback(), System.Xml.Serialization.ReflectionXmlSerializationWriter.WriteDerivedTypes(), and System.Xml.Serialization.ReflectionXmlSerializationWriter.WriteElement().