Terraria: Terraria.GameContent.Events.MoonlordDeathDrama.DrawExplosions
DrawExplosions()
static void Terraria.GameContent.Events.MoonlordDeathDrama.DrawExplosions (SpriteBatch spriteBatch) inline static
Definition at line 220 of file MoonlordDeathDrama.cs.
    {
        Rectangle playerScreen = Utils.CenteredRectangle(Main.screenPosition + new Vector2(Main.screenWidth, Main.screenHeight) * 0.5f, new Vector2(Main.screenWidth + 1000, Main.screenHeight + 1000));
        for (int i = 0; i < _explosions.Count; i++)
        {
            if (_explosions[i].InDrawRange(playerScreen))
            {
                _explosions[i].Draw(spriteBatch);
            }
        }
    }
References Terraria.GameContent.Events.MoonlordDeathDrama._explosions, Terraria.Utils.CenteredRectangle(), Terraria.Main.screenHeight, Terraria.Main.screenPosition, and Terraria.Main.screenWidth.
Referenced by Terraria.Main.DoDraw_WallsTilesNPCs(), and Terraria.Main.DrawCapture().