Terraria: System.Net.Mime.ContentDisposition.PersistIfNeeded
PersistIfNeeded()
void System.Net.Mime.ContentDisposition.PersistIfNeeded (HeaderCollection headers, bool forcePersist) inline package
Definition at line 194 of file ContentDisposition.cs.
    {
        if (IsChanged || !_isPersisted || forcePersist)
        {
            headers.InternalSet(MailHeaderInfo.GetString(MailHeaderID.ContentDisposition), ToString());
            _isPersisted = true;
        }
    }
References System.Net.Mime.ContentDisposition._isPersisted, System.Net.Mail.MailHeaderInfo.GetString(), System.Net.Mime.ContentDisposition.IsChanged, and System.Net.Mime.ContentDisposition.ToString().
Referenced by System.Net.Mime.MimeBasePart.PrepareHeaders().