Terraria: System.Net.Mime.ContentDisposition.ToString
ToString()
override string System.Net.Mime.ContentDisposition.ToString () inline
Definition at line 203 of file ContentDisposition.cs.
    {
        if (_disposition == null || _isChanged || (_parameters != null && _parameters.IsChanged))
        {
            _disposition = Encode(allowUnicode: false);
            _isChanged = false;
            _parameters.IsChanged = false;
            _isPersisted = false;
        }
        return _disposition;
    }
References System.Net.Mime.ContentDisposition._disposition, System.Net.Mime.ContentDisposition._isChanged, System.Net.Mime.ContentDisposition._isPersisted, System.Net.Mime.ContentDisposition._parameters, System.Net.Mime.ContentDisposition.Encode(), and System.Net.TrackingValidationObjectDictionary.IsChanged.
Referenced by System.Net.Mime.ContentDisposition.Equals(), System.Net.Mime.ContentDisposition.GetHashCode(), and System.Net.Mime.ContentDisposition.PersistIfNeeded().