Terraria: System.Net.Mime.ContentDisposition.ParseValue
ParseValue()
void System.Net.Mime.ContentDisposition.ParseValue () inline private
Definition at line 261 of file ContentDisposition.cs.
    {
        int offset = 0;
        try
        {
            _dispositionType = MailBnfHelper.ReadToken(_disposition, ref offset, null);
            if (string.IsNullOrEmpty(_dispositionType))
            {
                throw new FormatException(System.SR.MailHeaderFieldMalformedHeader);
            }
            if (_parameters == null)
            {
                _parameters = new TrackingValidationObjectDictionary(s_validators);
            }
            else
            {
                _parameters.Clear();
            }
            while (MailBnfHelper.SkipCFWS(_disposition, ref offset))
            {
                if (_disposition[offset++] != ';')
                {
                    throw new FormatException(System.SR.Format(System.SR.MailHeaderFieldInvalidCharacter, _disposition[offset - 1]));
                }
                if (MailBnfHelper.SkipCFWS(_disposition, ref offset))
                {
                    string text = MailBnfHelper.ReadParameterAttribute(_disposition, ref offset, null);
                    if (_disposition[offset++] != '=')
                    {
                        throw new FormatException(System.SR.MailHeaderFieldMalformedHeader);
                    }
                    if (!MailBnfHelper.SkipCFWS(_disposition, ref offset))
                    {
                        throw new FormatException(System.SR.ContentDispositionInvalid);
                    }
                    string value = ((_disposition[offset] == '"') ? MailBnfHelper.ReadQuotedString(_disposition, ref offset, null) : MailBnfHelper.ReadToken(_disposition, ref offset, null));
                    if (string.IsNullOrEmpty(text) || string.IsNullOrEmpty(value))
                    {
                        throw new FormatException(System.SR.ContentDispositionInvalid);
                    }
                    Parameters.Add(text, value);
                    continue;
                }
                break;
            }
        }
        catch (FormatException innerException)
        {
            throw new FormatException(System.SR.ContentDispositionInvalid, innerException);
        }
        _parameters.IsChanged = false;
    }
References System.Net.Mime.ContentDisposition._disposition, System.Net.Mime.ContentDisposition._dispositionType, System.Net.Mime.ContentDisposition._parameters, System.Collections.Specialized.StringDictionary.Add(), System.Net.TrackingValidationObjectDictionary.Clear(), System.SR.ContentDispositionInvalid, System.SR.Format(), System.SR.MailHeaderFieldInvalidCharacter, System.SR.MailHeaderFieldMalformedHeader, System.offset, System.Net.Mime.ContentDisposition.Parameters, System.Net.Mime.MailBnfHelper.ReadParameterAttribute(), System.Net.Mime.MailBnfHelper.ReadQuotedString(), System.Net.Mime.MailBnfHelper.ReadToken(), System.Net.Mime.ContentDisposition.s_validators, System.Net.Mime.MailBnfHelper.SkipCFWS(), System.text, and System.value.
Referenced by System.Net.Mime.ContentDisposition.ContentDisposition().