Terraria: Terraria.TimeLogger.DetailedDrawTime
DetailedDrawTime()
static void Terraria.TimeLogger.DetailedDrawTime (int detailedDrawType) inline static
Definition at line 307 of file TimeLogger.cs.
    {
        if (detailedDrawType >= 0 && detailedDrawType < detailedDrawTimes.Length)
        {
            double totalMilliseconds = detailedDrawTimer.Elapsed.TotalMilliseconds;
            double time = totalMilliseconds - lastDetailedDrawTime;
            lastDetailedDrawTime = totalMilliseconds;
            UpdateTime(detailedDrawTimes, detailedDrawType, time);
        }
    }
References Terraria.TimeLogger.detailedDrawTimer, Terraria.TimeLogger.detailedDrawTimes, Terraria.TimeLogger.lastDetailedDrawTime, and Terraria.TimeLogger.UpdateTime().
Referenced by Terraria.Main.DoDraw(), Terraria.Main.DoDraw_DrawNPCsBehindTiles(), Terraria.Main.DoDraw_DrawNPCsOverTiles(), Terraria.Main.DoDraw_Tiles_NonSolid(), Terraria.Main.DoDraw_Tiles_Solid(), Terraria.Main.DoDraw_WallsAndBlacks(), Terraria.Main.DoDraw_Waterfalls(), Terraria.Main.DrawBG(), Terraria.Main.DrawDust(), Terraria.Main.DrawGore(), Terraria.Main.DrawMap(), Terraria.Main.DrawPlayerChat(), Terraria.Main.DrawProjectiles(), Terraria.Main.DrawRain(), Terraria.Main.DrawWires(), Terraria.GameContent.Drawing.TileDrawing.GetScreenDrawArea(), Terraria.Main.RenderBackground(), Terraria.Main.RenderBlack(), Terraria.Main.RenderTiles(), Terraria.Main.RenderTiles2(), Terraria.Main.RenderWalls(), and Terraria.Main.RenderWater().