Terraria: System.Linq.Expressions.Interpreter.EnterTryFaultInstruction.Run
Run()
override int System.Linq.Expressions.Interpreter.EnterTryFaultInstruction.Run (InterpretedFrame frame) inline
Definition at line 23 of file EnterTryFaultInstruction.cs.
    {
        frame.PushContinuation(_labelIndex);
        int instructionIndex = frame.InstructionIndex;
        frame.InstructionIndex++;
        Instruction[] instructions = frame.Interpreter.Instructions.Instructions;
        bool flag = false;
        try
        {
            int num = frame.InstructionIndex;
            while (num >= _tryHandler.TryStartIndex && num < _tryHandler.TryEndIndex)
            {
                num = (frame.InstructionIndex = num + instructions[num].Run(frame));
            }
            flag = true;
            frame.RemoveContinuation();
            frame.InstructionIndex += instructions[num].Run(frame);
        }
        finally
        {
            if (!flag)
            {
                int num2 = (frame.InstructionIndex = _tryHandler.FinallyStartIndex);
                while (num2 >= _tryHandler.FinallyStartIndex && num2 < _tryHandler.FinallyEndIndex)
                {
                    num2 = (frame.InstructionIndex = num2 + instructions[num2].Run(frame));
                }
            }
        }
        return frame.InstructionIndex - instructionIndex;
    }
References System.Linq.Expressions.Interpreter.IndexedBranchInstruction._labelIndex, System.Linq.Expressions.Interpreter.EnterTryFaultInstruction._tryHandler, System.Linq.Expressions.Interpreter.TryFaultHandler.FinallyEndIndex, System.Linq.Expressions.Interpreter.TryFaultHandler.FinallyStartIndex, System.Linq.Expressions.Interpreter.InterpretedFrame.InstructionIndex, System.Linq.Expressions.Interpreter.InstructionArray.Instructions, System.Linq.Expressions.Interpreter.Interpreter.Instructions, System.Linq.Expressions.Interpreter.InterpretedFrame.Interpreter, System.Linq.Expressions.Interpreter.InterpretedFrame.PushContinuation(), System.Linq.Expressions.Interpreter.InterpretedFrame.RemoveContinuation(), System.Linq.Expressions.Interpreter.Instruction.Run(), System.Linq.Expressions.Interpreter.TryFaultHandler.TryEndIndex, and System.Linq.Expressions.Interpreter.TryFaultHandler.TryStartIndex.