Terraria: TileSmartInteractCandidateProvider.FillPotentialTargetTiles
FillPotentialTargetTiles()
void TileSmartInteractCandidateProvider.FillPotentialTargetTiles (SmartInteractScanSettings settings) inline private
     {
         for (int i = settings.LX; i <= settings.HX; i++)
         {
             for (int j = settings.LY; j <= settings.HY; j++)
             {
                 Tile tile = Main.tile[i, j];
                 if (tile == null || !tile.active())
                 {
                     continue;
                 }
                 switch (tile.type)
                 {
                 case 10:
                 case 11:
                 case 21:
                 case 29:
                 case 55:
                 case 79:
                 case 85:
                 case 88:
                 case 89:
                 case 97:
                 case 102:
                 case 104:
                 case 125:
                 case 132:
                 case 136:
                 case 139:
                 case 144:
                 case 207:
                 case 209:
                 case 215:
                 case 216:
                 case 287:
                 case 335:
                 case 338:
                 case 354:
                 case 377:
                 case 386:
                 case 387:
                 case 388:
                 case 389:
                 case 410:
                 case 411:
                 case 425:
                 case 441:
                 case 455:
                 case 463:
                 case 464:
                 case 467:
                 case 468:
                 case 470:
                 case 475:
                 case 480:
                 case 487:
                 case 491:
                 case 494:
                 case 509:
                 case 510:
                 case 511:
                 case 573:
                 case 597:
                 case 621:
                 case 657:
                 case 658:
                     targets.Add(new Tuple<int, int>(i, j));
                     break;
                 case 15:
                 case 497:
                     if (settings.player.IsWithinSnappngRangeToTile(i, j, 40))
                     {
                         targets.Add(new Tuple<int, int>(i, j));
                     }
                     break;
                 case 237:
                     if (settings.player.HasItem(1293))
                     {
                         targets.Add(new Tuple<int, int>(i, j));
                     }
                     break;
                 case 212:
                     if (settings.player.HasItem(949))
                     {
                         targets.Add(new Tuple<int, int>(i, j));
                     }
                     break;
                 case 356:
                     if (!Main.fastForwardTimeToDawn && (Main.netMode == 1 || Main.sundialCooldown == 0))
                     {
                         targets.Add(new Tuple<int, int>(i, j));
                     }
                     break;
                 case 663:
                     if (!Main.fastForwardTimeToDusk && (Main.netMode == 1 || Main.moondialCooldown == 0))
                     {
                         targets.Add(new Tuple<int, int>(i, j));
                     }
                     break;
                 }
             }
         }
     }
References Tile.active(), Main.fastForwardTimeToDawn, Main.fastForwardTimeToDusk, Player.HasItem(), SmartInteractScanSettings.HX, SmartInteractScanSettings.HY, Player.IsWithinSnappngRangeToTile(), SmartInteractScanSettings.LX, SmartInteractScanSettings.LY, Main.moondialCooldown, Main.netMode, SmartInteractScanSettings.player, Main.sundialCooldown, targets, Main.tile, and Tile.type.
Referenced by ProvideCandidate().