Terraria: Terraria.TimeLogger.DrawException
DrawException()
static void Terraria.TimeLogger.DrawException (Exception e) inline static
Definition at line 360 of file TimeLogger.cs.
    {
        if (currentlyLogging)
        {
            logBuilder.AppendLine(e.ToString());
        }
    }
References Terraria.TimeLogger.currentlyLogging, Terraria.TimeLogger.logBuilder, and System.Exception.ToString().
Referenced by Terraria.Main.DoDraw(), Terraria.Main.DoDraw_DrawNPCsBehindTiles(), Terraria.Main.DoDraw_DrawNPCsOverTiles(), Terraria.Main.DoDraw_Tiles_NonSolid(), Terraria.Main.DoDraw_Tiles_Solid(), Terraria.Main.DoDraw_WallsTilesNPCs(), Terraria.UI.GameInterfaceLayer.Draw(), Terraria.Main.DrawBackGore(), Terraria.Main.DrawBG(), Terraria.Main.DrawCachedProjs(), Terraria.Main.DrawInterface_16_MapOrMinimap(), Terraria.Main.DrawInterface_27_Inventory(), Terraria.Main.DrawInterface_30_Hotbar(), Terraria.Main.DrawInterface_34_PlayerChat(), Terraria.Main.DrawInterface_39_MouseOver(), Terraria.Main.DrawInterface_7_TownNPCHouseBanners(), Terraria.Main.DrawMap(), Terraria.Main.DrawProjectiles(), Terraria.Main.DrawSuperSpecialProjectiles(), Terraria.Main.GUIBarsDraw(), Terraria.Main.GUIChatDraw(), Terraria.Main.RenderBackground(), Terraria.Main.RenderTiles(), Terraria.Main.RenderTiles2(), and Terraria.Main.RenderWalls().