Terraria: Terraria.TimeLogger.DetailedDrawReset
DetailedDrawReset()
static void Terraria.TimeLogger.DetailedDrawReset () inline static
Definition at line 302 of file TimeLogger.cs.
    {
        lastDetailedDrawTime = detailedDrawTimer.Elapsed.TotalMilliseconds;
    }
References Terraria.TimeLogger.detailedDrawTimer, and Terraria.TimeLogger.lastDetailedDrawTime.
Referenced by Terraria.Main.DoDraw(), Terraria.Main.DoDraw_Tiles_NonSolid(), Terraria.Main.DoDraw_WallsTilesNPCs(), Terraria.GameContent.Drawing.TileDrawing.GetScreenDrawArea(), Terraria.Main.RenderBackground(), Terraria.Main.RenderBlack(), Terraria.Main.RenderTiles(), Terraria.Main.RenderTiles2(), Terraria.Main.RenderWalls(), and Terraria.Main.RenderWater().