Terraria: Terraria.TimeLogger.UpdateTime
UpdateTime()
static void Terraria.TimeLogger.UpdateTime (TimeLogData[] times, int type, double time) inline static private
Definition at line 213 of file TimeLogger.cs.
    {
        bool flag = false;
        if (times[type].resetMaxTime > 0)
        {
            times[type].resetMaxTime--;
        }
        else
        {
            times[type].timeMax = 0f;
        }
        times[type].time = (float)time;
        if ((double)times[type].timeMax < time)
        {
            flag = true;
            times[type].timeMax = (float)time;
            times[type].resetMaxTime = 100;
        }
        times[type].usedLastDraw = true;
        if (currentFrame != 0)
        {
            logBuilder.AppendLine(string.Format("    {0} : {1:F4}ms {2}", times[type].logText, time, flag ? " - New Maximum" : string.Empty));
        }
    }
References Terraria.TimeLogger.currentFrame, System.Format, Terraria.TimeLogger.logBuilder, Terraria.TimeLogger.TimeLogData.resetMaxTime, Terraria.TimeLogger.TimeLogData.time, Terraria.TimeLogger.TimeLogData.timeMax, System.type, and Terraria.TimeLogger.TimeLogData.usedLastDraw.
Referenced by Terraria.TimeLogger.DetailedDrawTime(), Terraria.TimeLogger.DrawTime(), Terraria.TimeLogger.LightingTime(), and Terraria.TimeLogger.RenderTime().