Terraria: Terraria.TimeLogger.DrawTime
DrawTime()
static void Terraria.TimeLogger.DrawTime (int drawType, double timeElapsed) inline static
Definition at line 256 of file TimeLogger.cs.
    {
        if (drawType >= 0 && drawType < drawTimes.Length)
        {
            UpdateTime(drawTimes, drawType, timeElapsed);
        }
    }
References Terraria.TimeLogger.drawTimes, and Terraria.TimeLogger.UpdateTime().
Referenced by Terraria.GameContent.Drawing.TileDrawing.Draw(), Terraria.Main.DrawBackground(), Terraria.Main.DrawBlack(), Terraria.Main.DrawLiquid(), Terraria.GameContent.Drawing.WallDrawing.DrawWalls(), and Terraria.Main.OldDrawBackground().