Terraria: System.Data.DataSet.ReadXDRSchema
ReadXDRSchema()
void System.Data.DataSet.ReadXDRSchema (XmlReader reader) inline package
Definition at line 1532 of file DataSet.cs.
    {
        XmlDocument xmlDocument = new XmlDocument();
        XmlNode xmlNode = xmlDocument.ReadNode(reader);
        xmlDocument.AppendChild(xmlNode);
        XDRSchema xDRSchema = new XDRSchema(this, fInline: false);
        DataSetName = xmlDocument.DocumentElement.LocalName;
        xDRSchema.LoadSchema((XmlElement)xmlNode, this);
    }
References System.Data.DataSet.DataSetName, and System.Runtime.Serialization.Dictionary.
Referenced by System.Data.DataSet.ReadXml(), System.Data.DataSet.ReadXml(), and System.Data.DataSet.ReadXmlSchema().