Terraria: System.Data.DataSet.ReadXmlSerializable
ReadXmlSerializable()
virtual void System.Data.DataSet.ReadXmlSerializable (XmlReader reader) inline protected virtual
Definition at line 2825 of file DataSet.cs.
    {
        _useDataSetSchemaOnly = false;
        _udtIsWrapped = false;
        if (reader.HasAttributes)
        {
            if (reader.MoveToAttribute("xsi:nil"))
            {
                string attribute = reader.GetAttribute("xsi:nil");
                if (string.Equals(attribute, "true", StringComparison.Ordinal))
                {
                    MoveToElement(reader, 1);
                    return;
                }
            }
            if (reader.MoveToAttribute("msdata:UseDataSetSchemaOnly"))
            {
                string attribute2 = reader.GetAttribute("msdata:UseDataSetSchemaOnly");
                if (string.Equals(attribute2, "true", StringComparison.Ordinal) || string.Equals(attribute2, "1", StringComparison.Ordinal))
                {
                    _useDataSetSchemaOnly = true;
                }
                else if (!string.Equals(attribute2, "false", StringComparison.Ordinal) && !string.Equals(attribute2, "0", StringComparison.Ordinal))
                {
                    throw ExceptionBuilder.InvalidAttributeValue("UseDataSetSchemaOnly", attribute2);
                }
            }
            if (reader.MoveToAttribute("msdata:UDTColumnValueWrapped"))
            {
                string attribute3 = reader.GetAttribute("msdata:UDTColumnValueWrapped");
                if (string.Equals(attribute3, "true", StringComparison.Ordinal) || string.Equals(attribute3, "1", StringComparison.Ordinal))
                {
                    _udtIsWrapped = true;
                }
                else if (!string.Equals(attribute3, "false", StringComparison.Ordinal) && !string.Equals(attribute3, "0", StringComparison.Ordinal))
                {
                    throw ExceptionBuilder.InvalidAttributeValue("UDTColumnValueWrapped", attribute3);
                }
            }
        }
        ReadXml(reader, XmlReadMode.DiffGram, denyResolving: true);
    }
References System.Data.DataSet._udtIsWrapped, System.Data.DataSet._useDataSetSchemaOnly, System.Xml.XmlReader.GetAttribute(), System.Xml.XmlReader.HasAttributes, System.Data.ExceptionBuilder.InvalidAttributeValue(), System.Xml.XmlReader.MoveToAttribute(), System.Data.DataSet.MoveToElement(), and System.Data.DataSet.ReadXml().
Referenced by System.Data.DataSet.ReadXmlSerializableInternal().