Terraria: System.Data.DataSet.Reset
Reset()
virtual void System.Data.DataSet.Reset () inline virtual
Definition at line 2693 of file DataSet.cs.
    {
        long scopeId = DataCommonEventSource.Log.EnterScope("<ds.DataSet.Reset|API> {0}", ObjectID);
        try
        {
            for (int i = 0; i < Tables.Count; i++)
            {
                ConstraintCollection constraints = Tables[i].Constraints;
                int num = 0;
                while (num < constraints.Count)
                {
                    if (constraints[num] is ForeignKeyConstraint)
                    {
                        constraints.Remove(constraints[num]);
                    }
                    else
                    {
                        num++;
                    }
                }
            }
            Clear();
            Relations.Clear();
            Tables.Clear();
        }
        finally
        {
            DataCommonEventSource.Log.ExitScope(scopeId);
        }
    }
References System.Data.DataRelationCollection.Clear(), System.Data.DataSet.Clear(), System.Data.DataTableCollection.Clear(), System.Data.InternalDataCollectionBase.Count, System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Data.DataCommonEventSource.Log, System.Data.DataSet.ObjectID, System.Data.DataSet.Relations, System.Collections.Generic.Dictionary< TKey, TValue >.Remove(), and System.Data.DataSet.Tables.