Terraria: System.Data.DataSet.CreateDataReader
CreateDataReader() [1/2]
DataTableReader System.Data.DataSet.CreateDataReader () inline
Definition at line 3023 of file DataSet.cs.
    {
        if (Tables.Count == 0)
        {
            throw ExceptionBuilder.CannotCreateDataReaderOnEmptyDataSet();
        }
        DataTable[] array = new DataTable[Tables.Count];
        for (int i = 0; i < Tables.Count; i++)
        {
            array[i] = Tables[i];
        }
        return CreateDataReader(array);
    }
References System.array, System.Data.ExceptionBuilder.CannotCreateDataReaderOnEmptyDataSet(), System.Data.InternalDataCollectionBase.Count, System.Data.DataSet.CreateDataReader(), and System.Data.DataSet.Tables.
Referenced by System.Data.DataSet.CreateDataReader().