Terraria: System.Data.DataSet.Clone
Clone()
virtual DataSet System.Data.DataSet.Clone () inline virtual
Definition at line 977 of file DataSet.cs.
    {
        long scopeId = DataCommonEventSource.Log.EnterScope("<ds.DataSet.Clone|API> {0}", ObjectID);
        try
        {
            DataSet dataSet = CreateInstanceOfThisType();
            if (dataSet.Tables.Count > 0)
            {
                dataSet.Reset();
            }
            dataSet.DataSetName = DataSetName;
            dataSet.CaseSensitive = CaseSensitive;
            dataSet._culture = _culture;
            dataSet._cultureUserSet = _cultureUserSet;
            dataSet.EnforceConstraints = EnforceConstraints;
            dataSet.Namespace = Namespace;
            dataSet.Prefix = Prefix;
            dataSet.RemotingFormat = RemotingFormat;
            dataSet._fIsSchemaLoading = true;
            DataTableCollection tables = Tables;
            for (int i = 0; i < tables.Count; i++)
            {
                DataTable dataTable = tables[i].Clone(dataSet);
                dataTable._tableNamespace = tables[i].Namespace;
                dataSet.Tables.Add(dataTable);
            }
            for (int j = 0; j < tables.Count; j++)
            {
                ConstraintCollection constraints = tables[j].Constraints;
                for (int k = 0; k < constraints.Count; k++)
                {
                    if (!(constraints[k] is UniqueConstraint))
                    {
                        ForeignKeyConstraint foreignKeyConstraint = (ForeignKeyConstraint)constraints[k];
                        if (foreignKeyConstraint.Table != foreignKeyConstraint.RelatedTable)
{
                            dataSet.Tables[j].Constraints.Add(constraints[k].Clone(dataSet));
                        }
                    }
                }
            }
            DataRelationCollection relations = Relations;
            for (int l = 0; l < relations.Count; l++)
            {
                DataRelation dataRelation = relations[l].Clone(dataSet);
                dataRelation.CheckMultipleNested = false;
                dataSet.Relations.Add(dataRelation);
                dataRelation.CheckMultipleNested = true;
            }
            if (_extendedProperties != null)
            {
                foreach (object key in _extendedProperties.Keys)
                {
                    dataSet.ExtendedProperties[key] = _extendedProperties[key];
                }
            }
            foreach (DataTable table in Tables)
            {
                foreach (DataColumn column in table.Columns)
                {
                    if (column.Expression.Length != 0)
                    {
                        dataSet.Tables[table.TableName, table.Namespace].Columns[column.ColumnName].CopyExpressionFrom(column);
                    }
                }
            }
            for (int m = 0; m < tables.Count; m++)
            {
                dataSet.Tables[m]._tableNamespace = tables[m]._tableNamespace;
            }
            dataSet._fIsSchemaLoading = false;
            return dataSet;
        }
        finally
        {
            DataCommonEventSource.Log.ExitScope(scopeId);
        }
    }
References System.Data.DataSet._culture, System.Data.DataSet._cultureUserSet, System.Data.DataSet._extendedProperties, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Data.DataSet.CaseSensitive, System.Data.DataSet.Clone(), System.Data.DataTable.Columns, System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Data.DataSet.CreateInstanceOfThisType(), System.Data.DataSet.DataSetName, System.Runtime.Serialization.Dictionary, System.Data.DataSet.EnforceConstraints, System.key, System.Collections.Hashtable.Keys, System.Data.DataCommonEventSource.Log, System.Data.DataSet.Namespace, System.Data.DataTable.Namespace, System.Data.DataSet.ObjectID, System.Data.DataSet.Prefix, System.Data.DataSet.Relations, System.Data.DataSet.RemotingFormat, System.Data.DataTable.TableName, and System.Data.DataSet.Tables.
Referenced by System.Data.DataSet.Clone(), System.Xml.XmlDataDocument.CloneNode(), System.Data.DataSet.Copy(), System.Data.DataSet.GetChanges(), and System.Data.DataSet.ReadXmlDiffgram().