Terraria: System.Data.DataSet.InferXmlSchema
InferXmlSchema() [4/4]
void System.Data.DataSet.InferXmlSchema (XmlReader? reader, string?[] nsArray) inline
Definition at line 1313 of file DataSet.cs.
    {
        long scopeId = DataCommonEventSource.Log.EnterScope("<ds.DataSet.InferXmlSchema|API> {0}", ObjectID);
        try
        {
            if (reader != null)
            {
                XmlDocument xmlDocument = new XmlDocument();
                if (reader.NodeType == XmlNodeType.Element)
                {
                    XmlNode newChild = xmlDocument.ReadNode(reader);
                    xmlDocument.AppendChild(newChild);
                }
                else
                {
                    xmlDocument.Load(reader);
                }
                if (xmlDocument.DocumentElement != null)
                {
                    InferSchema(xmlDocument, nsArray, XmlReadMode.InferSchema);
                }
            }
        }
        finally
        {
            DataCommonEventSource.Log.ExitScope(scopeId);
        }
    }
References System.Data.InferSchema, System.Data.DataCommonEventSource.Log, System.Xml.XmlReader.NodeType, and System.Data.DataSet.ObjectID.
Referenced by System.Data.DataSet.InferXmlSchema(), System.Data.DataSet.InferXmlSchema(), and System.Data.DataSet.InferXmlSchema().