Terraria: System.Data.DataSet.Load
Load() [1/3]
virtual void System.Data.DataSet.Load (IDataReader reader, LoadOption loadOption, FillErrorEventHandler? errorHandler, params DataTable[] tables) inline virtual
Definition at line 2967 of file DataSet.cs.
    {
        long scopeId = DataCommonEventSource.Log.EnterScope("<ds.DataSet.Load|API> reader, loadOption={0}", loadOption);
        try
        {
            foreach (DataTable dataTable in tables)
            {
                ADP.CheckArgumentNull(dataTable, "tables");
                if (dataTable.DataSet != this)
                {
                    throw ExceptionBuilder.TableNotInTheDataSet(dataTable.TableName);
                }
            }
            LoadAdapter loadAdapter = new LoadAdapter();
            loadAdapter.FillLoadOption = loadOption;
            loadAdapter.MissingSchemaAction = MissingSchemaAction.AddWithKey;
            if (errorHandler != null)
            {
                loadAdapter.FillError += errorHandler;
            }
            loadAdapter.FillFromReader(tables, reader, 0, 0);
            if (!reader.IsClosed && !reader.NextResult())
            {
                reader.Close();
            }
        }
        finally
        {
            DataCommonEventSource.Log.ExitScope(scopeId);
        }
    }
References System.Data.Common.ADP.CheckArgumentNull(), System.Data.IDataReader.Close(), System.Runtime.Serialization.Dictionary, System.Data.IDataReader.IsClosed, System.Data.DataCommonEventSource.Log, System.Data.IDataReader.NextResult(), and System.Data.ExceptionBuilder.TableNotInTheDataSet().
Referenced by System.Data.DataSet.Load(), and System.Data.DataSet.Load().