Terraria: System.Data.DataSet.ReadXmlDiffgram
ReadXmlDiffgram()
void System.Data.DataSet.ReadXmlDiffgram (XmlReader reader) inline private
Definition at line 1985 of file DataSet.cs.
    {
        long scopeId = DataCommonEventSource.Log.EnterScope("<ds.DataSet.ReadXmlDiffgram|INFO> {0}", ObjectID);
        try
        {
            int depth = reader.Depth;
            bool enforceConstraints = EnforceConstraints;
            EnforceConstraints = false;
            bool flag = IsEmpty();
            DataSet dataSet;
            if (flag)
            {
                dataSet = this;
            }
            else
            {
                dataSet = Clone();
                dataSet.EnforceConstraints = false;
            }
            foreach (DataTable table in dataSet.Tables)
            {
                table.Rows._nullInList = 0;
            }
            reader.MoveToContent();
            if (reader.LocalName != "diffgram" && reader.NamespaceURI != "urn:schemas-microsoft-com:xml-diffgram-v1")
            {
                return;
            }
            reader.Read();
            if (reader.NodeType == XmlNodeType.Whitespace)
            {
                MoveToElement(reader, reader.Depth - 1);
            }
            dataSet._fInLoadDiffgram = true;
            if (reader.Depth > depth)
            {
                if (reader.NamespaceURI != "urn:schemas-microsoft-com:xml-diffgram-v1" && reader.NamespaceURI != "urn:schemas-microsoft-com:xml-msdata")
                {
                    XmlDocument xmlDocument = new XmlDocument();
                    XmlElement topNode = xmlDocument.CreateElement(reader.Prefix, reader.LocalName, reader.NamespaceURI);
                    reader.Read();
                    if (reader.NodeType == XmlNodeType.Whitespace)
                    {
                        MoveToElement(reader, reader.Depth - 1);
                    }
                    if (reader.Depth - 1 > depth)
                    {
                        XmlDataLoader xmlDataLoader = new XmlDataLoader(dataSet, IsXdr: false, topNode, ignoreSchema: false);
                        xmlDataLoader._isDiffgram = true;
                        xmlDataLoader.LoadData(reader);
                    }
                    ReadEndElement(reader);
                    if (reader.NodeType == XmlNodeType.Whitespace)
                    {
                        MoveToElement(reader, reader.Depth - 1);
                    }
                }
                if ((reader.LocalName == "before" && reader.NamespaceURI == "urn:schemas-microsoft-com:xml-diffgram-v1") || (reader.LocalName == "errors" && reader.NamespaceURI == "urn:schemas-microsoft-com:xml-diffgram-v1"))
                {
                    XMLDiffLoader xMLDiffLoader = new XMLDiffLoader();
                    xMLDiffLoader.LoadDiffGram(dataSet, reader);
                }
                while (reader.Depth > depth)
                {
                    reader.Read();
                }
                ReadEndElement(reader);
            }
            foreach (DataTable table2 in dataSet.Tables)
            {
                if (table2.Rows._nullInList > 0)
                {
                    throw ExceptionBuilder.RowInsertMissing(table2.TableName);
                }
            }
            dataSet._fInLoadDiffgram = false;
            foreach (DataTable table3 in dataSet.Tables)
            {
                DataRelation[] nestedParentRelations = table3.NestedParentRelations;
                DataRelation[] array = nestedParentRelations;
                foreach (DataRelation dataRelation in array)
                {
                    if (dataRelation.ParentTable != table3)
                    {
                        continue;
                    }
                    foreach (DataRow row in table3.Rows)
                    {
                        DataRelation[] array2 = nestedParentRelations;
                        foreach (DataRelation rel in array2)
{
                            row.CheckForLoops(rel);
                        }
                    }
                }
            }
            if (!flag)
            {
                Merge(dataSet);
                if (_dataSetName == "NewDataSet")
                {
                    _dataSetName = dataSet._dataSetName;
                }
                dataSet.EnforceConstraints = enforceConstraints;
            }
            EnforceConstraints = enforceConstraints;
        }
        finally
        {
            DataCommonEventSource.Log.ExitScope(scopeId);
        }
    }
References System.Data.DataSet._dataSetName, System.array, System.Data.DataSet.Clone(), System.Xml.XmlReader.Depth, System.Runtime.Serialization.Dictionary, System.Data.DataSet.EnforceConstraints, System.Data.DataSet.IsEmpty(), System.Xml.XmlReader.LocalName, System.Data.DataCommonEventSource.Log, System.Data.DataSet.Merge(), System.Xml.XmlReader.MoveToContent(), System.Data.DataSet.MoveToElement(), System.Xml.XmlReader.NamespaceURI, System.Xml.XmlReader.NodeType, System.Data.DataSet.ObjectID, System.Xml.XmlReader.Prefix, System.Xml.XmlReader.Read(), System.Data.DataSet.ReadEndElement(), and System.Data.ExceptionBuilder.RowInsertMissing().
Referenced by System.Data.DataSet.ReadXml(), and System.Data.DataSet.ReadXml().