Terraria: System.Data.DataSet.MoveToElement
MoveToElement() [2/2]
bool System.Data.DataSet.MoveToElement (XmlReader reader, int depth) inline package
Definition at line 1466 of file DataSet.cs.
    {
        while (!reader.EOF && reader.NodeType != XmlNodeType.EndElement && reader.NodeType != XmlNodeType.Element && reader.Depth > depth)
        {
            reader.Read();
        }
        return reader.NodeType == XmlNodeType.Element;
    }
References System.Xml.XmlReader.Depth, System.Runtime.Serialization.Dictionary, System.Xml.XmlReader.EOF, System.Xml.XmlReader.NodeType, and System.Xml.XmlReader.Read().
Referenced by System.Data.DataSet.ReadXml(), System.Data.DataSet.ReadXml(), System.Data.DataSet.ReadXmlDiffgram(), System.Data.DataSet.ReadXmlSchema(), System.Data.DataSet.ReadXmlSerializable(), and System.Data.DataSet.ReadXSDSchema().