Terraria: System.Data.DataSet.MarkRelatedRowsAsModified
MarkRelatedRowsAsModified()
void System.Data.DataSet.MarkRelatedRowsAsModified (TableChanges[] bitMatrix, DataRow row) inline private
Definition at line 1179 of file DataSet.cs.
    {
        DataRelationCollection parentRelations = row.Table.ParentRelations;
        int count = parentRelations.Count;
        for (int i = 0; i < count; i++)
        {
            DataRow[] parentRows = row.GetParentRows(parentRelations[i], DataRowVersion.Current);
            DataRow[] array = parentRows;
            foreach (DataRow dataRow in array)
            {
                int num = Tables.IndexOf(dataRow.Table);
                int index = dataRow.Table.Rows.IndexOf(dataRow);
                if (!bitMatrix[num][index])
                {
                    bitMatrix[num][index] = true;
                    if (DataRowState.Deleted != dataRow.RowState)
                    {
                        MarkRelatedRowsAsModified(bitMatrix, dataRow);
                    }
                }
            }
        }
    }
References System.array, System.count, System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Runtime.Serialization.Dictionary, System.index, System.Data.DataTableCollection.IndexOf(), System.Data.DataSet.MarkRelatedRowsAsModified(), and System.Data.DataSet.Tables.
Referenced by System.Data.DataSet.MarkModifiedRows(), and System.Data.DataSet.MarkRelatedRowsAsModified().