Terraria: System.Data.DataSet.GetChanges
GetChanges() [2/2]
DataSet? System.Data.DataSet.GetChanges (DataRowState rowStates) inline
Definition at line 1103 of file DataSet.cs.
    {
        long scopeId = DataCommonEventSource.Log.EnterScope("<ds.DataSet.GetChanges|API> {0}, rowStates={1}", ObjectID, rowStates);
        try
        {
            DataSet dataSet = null;
            bool enforceConstraints = false;
            if (((uint)rowStates & 0xFFFFFFE1u) != 0)
            {
                throw ExceptionBuilder.InvalidRowState(rowStates);
            }
            TableChanges[] array = new TableChanges[Tables.Count];
            for (int i = 0; i < array.Length; i++)
            {
                array[i] = new TableChanges(Tables[i].Rows.Count);
            }
            MarkModifiedRows(array, rowStates);
            for (int j = 0; j < array.Length; j++)
            {
                if (0 >= array[j].HasChanges)
                {
                    continue;
                }
                if (dataSet == null)
                {
                    dataSet = Clone();
                    enforceConstraints = dataSet.EnforceConstraints;
                    dataSet.EnforceConstraints = false;
                }
                DataTable dataTable = Tables[j];
                DataTable table = dataSet.Tables[dataTable.TableName, dataTable.Namespace];
                int num = 0;
                while (0 < array[j].HasChanges)
                {
                    if (array[j][num])
                    {
                        dataTable.CopyRow(table, dataTable.Rows[num]);
                        array[j].HasChanges--;
                    }
                    num++;
                }
            }
            if (dataSet != null)
            {
                dataSet.EnforceConstraints = enforceConstraints;
            }
            return dataSet;
        }
        finally
        {
            DataCommonEventSource.Log.ExitScope(scopeId);
        }
    }
References System.array, System.Data.DataSet.Clone(), System.Data.InternalDataCollectionBase.Count, System.Runtime.Serialization.Dictionary, System.Data.DataSet.HasChanges(), System.Data.ExceptionBuilder.InvalidRowState(), System.Data.DataCommonEventSource.Log, System.Data.DataSet.MarkModifiedRows(), System.Data.DataSet.ObjectID, and System.Data.DataSet.Tables.