Terraria: System.Data.DataSet.ReadXml
ReadXml() [8/11]
XmlReadMode System.Data.DataSet.ReadXml (XmlReader reader, bool denyResolving) inline package
Definition at line 1691 of file DataSet.cs.
    {
        IDisposable disposable = null;
        long scopeId = DataCommonEventSource.Log.EnterScope("<ds.DataSet.ReadXml|INFO> {0}, denyResolving={1}", ObjectID, denyResolving);
        try
        {
            disposable = TypeLimiter.EnterRestrictedScope(this);
            DataTable.DSRowDiffIdUsageSection dSRowDiffIdUsageSection = default(DataTable.DSRowDiffIdUsageSection);
            try
            {
                bool flag = false;
                bool flag2 = false;
                bool flag3 = false;
                bool isXdr = false;
                int depth = -1;
                XmlReadMode result = XmlReadMode.Auto;
                bool flag4 = false;
                bool flag5 = false;
                dSRowDiffIdUsageSection.Prepare(this);
                if (reader == null)
                {
                    return result;
                }
                if (Tables.Count == 0)
                {
                    flag4 = true;
                }
                if (reader is XmlTextReader)
                {
                    ((XmlTextReader)reader).WhitespaceHandling = WhitespaceHandling.Significant;
                }
                XmlDocument xmlDocument = new XmlDocument();
                XmlDataLoader xmlDataLoader = null;
                reader.MoveToContent();
                if (reader.NodeType == XmlNodeType.Element)
                {
                    depth = reader.Depth;
                }
                if (reader.NodeType == XmlNodeType.Element)
                {
                    if (reader.LocalName == "diffgram" && reader.NamespaceURI == "urn:schemas-microsoft-com:xml-diffgram-v1")
                    {
                        ReadXmlDiffgram(reader);
                        ReadEndElement(reader);
                        return XmlReadMode.DiffGram;
                    }
                    if (reader.LocalName == "Schema" && reader.NamespaceURI == "urn:schemas-microsoft-com:xml-data")
                    {
                        ReadXDRSchema(reader);
                        return XmlReadMode.ReadSchema;
                    }
                    if (reader.LocalName == "schema" && reader.NamespaceURI == "http://www.w3.org/2001/XMLSchema")
                    {
                        ReadXSDSchema(reader, denyResolving);
                        return XmlReadMode.ReadSchema;
                    }
                    if (reader.LocalName == "schema" && reader.NamespaceURI.StartsWith("http://www.w3.org/", StringComparison.Ordinal))
                    {
                        throw ExceptionBuilder.DataSetUnsupportedSchema("http://www.w3.org/2001/XMLSchema");
                    }
                    XmlElement xmlElement = xmlDocument.CreateElement(reader.Prefix, reader.LocalName, reader.NamespaceURI);
                    if (reader.HasAttributes)
                    {
                        int attributeCount = reader.AttributeCount;
                        for (int i = 0; i < attributeCount; i++)
{
                            reader.MoveToAttribute(i);
                            if (reader.NamespaceURI.Equals("http://www.w3.org/2000/xmlns/"))
{
                                xmlElement.SetAttribute(reader.Name, reader.GetAttribute(i));
                                continue;
                            }
                            XmlAttribute xmlAttribute = xmlElement.SetAttributeNode(reader.LocalName, reader.NamespaceURI);
                            xmlAttribute.Prefix = reader.Prefix;
                            xmlAttribute.Value = reader.GetAttribute(i);
                        }
                    }
                    reader.Read();
                    string value = reader.Value;
                    while (MoveToElement(reader, depth))
                    {
                        if (reader.LocalName == "diffgram" && reader.NamespaceURI == "urn:schemas-microsoft-com:xml-diffgram-v1")
{
                            ReadXmlDiffgram(reader);
                            result = XmlReadMode.DiffGram;
                        }
                        if (!flag2 && !flag && reader.LocalName == "Schema" && reader.NamespaceURI == "urn:schemas-microsoft-com:xml-data")
{
                            ReadXDRSchema(reader);
                            flag2 = true;
                            isXdr = true;
                            continue;
                        }
                        if (reader.LocalName == "schema" && reader.NamespaceURI == "http://www.w3.org/2001/XMLSchema")
{
                            ReadXSDSchema(reader, denyResolving);
                            flag2 = true;
                            continue;
                        }
                        if (reader.LocalName == "schema" && reader.NamespaceURI.StartsWith("http://www.w3.org/", StringComparison.Ordinal))
{
                            throw ExceptionBuilder.DataSetUnsupportedSchema("http://www.w3.org/2001/XMLSchema");
                        }
                        if (reader.LocalName == "diffgram" && reader.NamespaceURI == "urn:schemas-microsoft-com:xml-diffgram-v1")
{
                            ReadXmlDiffgram(reader);
                            flag3 = true;
                            result = XmlReadMode.DiffGram;
                            continue;
                        }
                        while (!reader.EOF && reader.NodeType == XmlNodeType.Whitespace)
{
                            reader.Read();
                        }
                        if (reader.NodeType != XmlNodeType.Element)
{
                            continue;
                        }
                        flag = true;
                        if (!flag2 && Tables.Count == 0)
{
                            XmlNode newChild = xmlDocument.ReadNode(reader);
                            xmlElement.AppendChild(newChild);
                            continue;
                        }
                        if (xmlDataLoader == null)
{
                            xmlDataLoader = new XmlDataLoader(this, isXdr, xmlElement, ignoreSchema: false);
                        }
                        xmlDataLoader.LoadData(reader);
                        flag5 = true;
                        result = (flag2 ? XmlReadMode.ReadSchema : XmlReadMode.IgnoreSchema);
                    }
                    ReadEndElement(reader);
                    bool flag6 = false;
                    bool fTopLevelTable = _fTopLevelTable;
                    if (!flag2 && Tables.Count == 0 && !xmlElement.HasChildNodes)
                    {
                        _fTopLevelTable = true;
                        flag6 = true;
                        if (value != null && value.Length > 0)
{
                            xmlElement.InnerText = value;
                        }
                    }
                    if (!flag4 && value != null && value.Length > 0)
                    {
                        xmlElement.InnerText = value;
                    }
                    xmlDocument.AppendChild(xmlElement);
                    if (xmlDataLoader == null)
                    {
                        xmlDataLoader = new XmlDataLoader(this, isXdr, xmlElement, ignoreSchema: false);
                    }
                    if (!flag4 && !flag5)
                    {
                        XmlElement documentElement = xmlDocument.DocumentElement;
                        if (documentElement.ChildNodes.Count == 0 || (documentElement.ChildNodes.Count == 1 && documentElement.FirstChild.GetType() == typeof(XmlText)))
{
                            bool fTopLevelTable2 = _fTopLevelTable;
                            if (DataSetName != documentElement.Name && _namespaceURI != documentElement.NamespaceURI && Tables.Contains(documentElement.Name, (documentElement.NamespaceURI.Length == 0) ? null : documentElement.NamespaceURI, checkProperty: false, caseSensitive: true))
{
                                _fTopLevelTable = true;
                            }
                            try
{
                                xmlDataLoader.LoadData(xmlDocument);
                            }
                            finally
{
                                _fTopLevelTable = fTopLevelTable2;
                            }
                        }
                    }
                    if (!flag3)
                    {
                        if (!flag2 && Tables.Count == 0)
{
                            InferSchema(xmlDocument, null, XmlReadMode.Auto);
                            result = XmlReadMode.InferSchema;
                            xmlDataLoader.FromInference = true;
                            try
{
                                xmlDataLoader.LoadData(xmlDocument);
                            }
                            finally
{
                                xmlDataLoader.FromInference = false;
                            }
                        }
                        if (flag6)
{
                            _fTopLevelTable = fTopLevelTable;
                        }
                    }
                }
                return result;
            }
            finally
            {
            }
        }
        finally
        {
            disposable?.Dispose();
            DataCommonEventSource.Log.ExitScope(scopeId);
        }
    }
References System.Data.DataSet._fTopLevelTable, System.Data.DataSet._namespaceURI, System.Xml.XmlReader.AttributeCount, System.Data.DataTableCollection.Contains(), System.Data.InternalDataCollectionBase.Count, System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Data.DataSet.DataSetName, System.Data.ExceptionBuilder.DataSetUnsupportedSchema(), System.Xml.XmlReader.Depth, System.Runtime.Serialization.Dictionary, System.Data.TypeLimiter.EnterRestrictedScope(), System.Xml.XmlReader.EOF, System.Xml.XmlReader.GetAttribute(), System.Xml.XmlReader.HasAttributes, System.Data.InferSchema, System.Xml.XmlReader.LocalName, System.Data.DataCommonEventSource.Log, System.Xml.XmlReader.MoveToAttribute(), System.Xml.XmlReader.MoveToContent(), System.Data.DataSet.MoveToElement(), System.Xml.XmlReader.Name, System.Xml.XmlReader.NamespaceURI, System.Xml.XmlReader.NodeType, System.Data.DataSet.ObjectID, System.Xml.XmlReader.Prefix, System.Xml.XmlReader.Read(), System.Data.DataSet.ReadEndElement(), System.Data.DataSet.ReadXDRSchema(), System.Data.DataSet.ReadXmlDiffgram(), System.Data.DataSet.ReadXSDSchema(), System.Data.DataSet.Tables, System.value, and System.Xml.XmlReader.Value.