Terraria: System.Data.DataSet.ReadXmlSchema
ReadXmlSchema() [4/5]
void System.Data.DataSet.ReadXmlSchema (XmlReader reader, bool denyResolving) inline package
Definition at line 1381 of file DataSet.cs.
    {
        long scopeId = DataCommonEventSource.Log.EnterScope("<ds.DataSet.ReadXmlSchema|INFO> {0}, reader, denyResolving={1}", ObjectID, denyResolving);
        try
        {
            int depth = -1;
            if (reader == null)
            {
                return;
            }
            if (reader is XmlTextReader)
            {
                ((XmlTextReader)reader).WhitespaceHandling = WhitespaceHandling.None;
            }
            XmlDocument xmlDocument = new XmlDocument();
            if (reader.NodeType == XmlNodeType.Element)
            {
                depth = reader.Depth;
            }
            reader.MoveToContent();
            if (reader.NodeType != XmlNodeType.Element)
            {
                return;
            }
            if (reader.LocalName == "Schema" && reader.NamespaceURI == "urn:schemas-microsoft-com:xml-data")
            {
                ReadXDRSchema(reader);
                return;
            }
            if (reader.LocalName == "schema" && reader.NamespaceURI == "http://www.w3.org/2001/XMLSchema")
            {
                ReadXSDSchema(reader, denyResolving);
                return;
            }
            if (reader.LocalName == "schema" && reader.NamespaceURI.StartsWith("http://www.w3.org/", StringComparison.Ordinal))
            {
                throw ExceptionBuilder.DataSetUnsupportedSchema("http://www.w3.org/2001/XMLSchema");
            }
            XmlElement xmlElement = xmlDocument.CreateElement(reader.Prefix, reader.LocalName, reader.NamespaceURI);
            if (reader.HasAttributes)
            {
                int attributeCount = reader.AttributeCount;
                for (int i = 0; i < attributeCount; i++)
                {
                    reader.MoveToAttribute(i);
                    if (reader.NamespaceURI.Equals("http://www.w3.org/2000/xmlns/"))
                    {
                        xmlElement.SetAttribute(reader.Name, reader.GetAttribute(i));
                        continue;
                    }
                    XmlAttribute xmlAttribute = xmlElement.SetAttributeNode(reader.LocalName, reader.NamespaceURI);
                    xmlAttribute.Prefix = reader.Prefix;
                    xmlAttribute.Value = reader.GetAttribute(i);
                }
            }
            reader.Read();
            while (MoveToElement(reader, depth))
            {
                if (reader.LocalName == "Schema" && reader.NamespaceURI == "urn:schemas-microsoft-com:xml-data")
                {
                    ReadXDRSchema(reader);
                    return;
                }
                if (reader.LocalName == "schema" && reader.NamespaceURI == "http://www.w3.org/2001/XMLSchema")
                {
                    ReadXSDSchema(reader, denyResolving);
                    return;
                }
                if (reader.LocalName == "schema" && reader.NamespaceURI.StartsWith("http://www.w3.org/", StringComparison.Ordinal))
                {
                    throw ExceptionBuilder.DataSetUnsupportedSchema("http://www.w3.org/2001/XMLSchema");
                }
                XmlNode newChild = xmlDocument.ReadNode(reader);
                xmlElement.AppendChild(newChild);
            }
            ReadEndElement(reader);
            xmlDocument.AppendChild(xmlElement);
            InferSchema(xmlDocument, null, XmlReadMode.Auto);
        }
        finally
        {
            DataCommonEventSource.Log.ExitScope(scopeId);
        }
    }
References System.Xml.XmlReader.AttributeCount, System.Data.ExceptionBuilder.DataSetUnsupportedSchema(), System.Xml.XmlReader.Depth, System.Runtime.Serialization.Dictionary, System.Xml.XmlReader.GetAttribute(), System.Xml.XmlReader.HasAttributes, System.Data.InferSchema, System.Xml.XmlReader.LocalName, System.Data.DataCommonEventSource.Log, System.Xml.XmlReader.MoveToAttribute(), System.Xml.XmlReader.MoveToContent(), System.Data.DataSet.MoveToElement(), System.Xml.XmlReader.Name, System.Xml.XmlReader.NamespaceURI, System.Xml.XmlReader.NodeType, System.Data.DataSet.ObjectID, System.Xml.XmlReader.Prefix, System.Xml.XmlReader.Read(), System.Data.DataSet.ReadEndElement(), System.Data.DataSet.ReadXDRSchema(), and System.Data.DataSet.ReadXSDSchema().