Terraria: System.Data.DataSet.ReadXml
ReadXml() [9/11]
XmlReadMode System.Data.DataSet.ReadXml (XmlReader reader, XmlReadMode mode, bool denyResolving) inline package
Definition at line 2105 of file DataSet.cs.
    {
        IDisposable disposable = null;
        long scopeId = DataCommonEventSource.Log.EnterScope("<ds.DataSet.ReadXml|INFO> {0}, mode={1}, denyResolving={2}", ObjectID, mode, denyResolving);
        try
        {
            disposable = TypeLimiter.EnterRestrictedScope(this);
            XmlReadMode result = mode;
            if (reader == null)
            {
                return result;
            }
            if (mode == XmlReadMode.Auto)
            {
                return ReadXml(reader);
            }
            DataTable.DSRowDiffIdUsageSection dSRowDiffIdUsageSection = default(DataTable.DSRowDiffIdUsageSection);
            try
            {
                bool flag = false;
                bool flag2 = false;
                bool isXdr = false;
                int depth = -1;
                dSRowDiffIdUsageSection.Prepare(this);
                if (reader is XmlTextReader)
                {
                    ((XmlTextReader)reader).WhitespaceHandling = WhitespaceHandling.Significant;
                }
                XmlDocument xmlDocument = new XmlDocument();
                if (mode != XmlReadMode.Fragment && reader.NodeType == XmlNodeType.Element)
                {
                    depth = reader.Depth;
                }
                reader.MoveToContent();
                XmlDataLoader xmlDataLoader = null;
                if (reader.NodeType == XmlNodeType.Element)
                {
                    XmlElement xmlElement = null;
                    if (mode == XmlReadMode.Fragment)
                    {
                        xmlDocument.AppendChild(xmlDocument.CreateElement("ds_sqlXmlWraPPeR"));
                        xmlElement = xmlDocument.DocumentElement;
                    }
                    else
                    {
                        if (reader.LocalName == "diffgram" && reader.NamespaceURI == "urn:schemas-microsoft-com:xml-diffgram-v1")
{
                            if (mode == XmlReadMode.DiffGram || mode == XmlReadMode.IgnoreSchema)
{
                                ReadXmlDiffgram(reader);
                                ReadEndElement(reader);
                            }
                            else
{
                                reader.Skip();
                            }
                            return result;
                        }
                        if (reader.LocalName == "Schema" && reader.NamespaceURI == "urn:schemas-microsoft-com:xml-data")
{
                            if (mode != XmlReadMode.IgnoreSchema && mode != XmlReadMode.InferSchema && mode != XmlReadMode.InferTypedSchema)
{
                                ReadXDRSchema(reader);
                            }
                            else
{
                                reader.Skip();
                            }
                            return result;
                        }
                        if (reader.LocalName == "schema" && reader.NamespaceURI == "http://www.w3.org/2001/XMLSchema")
{
                            if (mode != XmlReadMode.IgnoreSchema && mode != XmlReadMode.InferSchema && mode != XmlReadMode.InferTypedSchema)
{
                                ReadXSDSchema(reader, denyResolving);
                            }
                            else
{
                                reader.Skip();
                            }
                            return result;
                        }
                        if (reader.LocalName == "schema" && reader.NamespaceURI.StartsWith("http://www.w3.org/", StringComparison.Ordinal))
{
                            throw ExceptionBuilder.DataSetUnsupportedSchema("http://www.w3.org/2001/XMLSchema");
                        }
                        xmlElement = xmlDocument.CreateElement(reader.Prefix, reader.LocalName, reader.NamespaceURI);
                        if (reader.HasAttributes)
{
                            int attributeCount = reader.AttributeCount;
                            for (int i = 0; i < attributeCount; i++)
{
                                reader.MoveToAttribute(i);
                                if (reader.NamespaceURI.Equals("http://www.w3.org/2000/xmlns/"))
{
                                    xmlElement.SetAttribute(reader.Name, reader.GetAttribute(i));
                                    continue;
                                }
                                XmlAttribute xmlAttribute = xmlElement.SetAttributeNode(reader.LocalName, reader.NamespaceURI);
                                xmlAttribute.Prefix = reader.Prefix;
                                xmlAttribute.Value = reader.GetAttribute(i);
                            }
                        }
                        reader.Read();
                    }
                    while (MoveToElement(reader, depth))
                    {
                        if (reader.LocalName == "Schema" && reader.NamespaceURI == "urn:schemas-microsoft-com:xml-data")
{
                            if (!flag && !flag2 && mode != XmlReadMode.IgnoreSchema && mode != XmlReadMode.InferSchema && mode != XmlReadMode.InferTypedSchema)
{
                                ReadXDRSchema(reader);
                                flag = true;
                                isXdr = true;
                            }
                            else
{
                                reader.Skip();
                            }
                            continue;
                        }
                        if (reader.LocalName == "schema" && reader.NamespaceURI == "http://www.w3.org/2001/XMLSchema")
{
                            if (mode != XmlReadMode.IgnoreSchema && mode != XmlReadMode.InferSchema && mode != XmlReadMode.InferTypedSchema)
{
                                ReadXSDSchema(reader, denyResolving);
                                flag = true;
                            }
                            else
{
                                reader.Skip();
                            }
                            continue;
                        }
                        if (reader.LocalName == "diffgram" && reader.NamespaceURI == "urn:schemas-microsoft-com:xml-diffgram-v1")
{
                            if (mode == XmlReadMode.DiffGram || mode == XmlReadMode.IgnoreSchema)
{
                                ReadXmlDiffgram(reader);
                                result = XmlReadMode.DiffGram;
                            }
                            else
{
                                reader.Skip();
                            }
                            continue;
                        }
                        if (reader.LocalName == "schema" && reader.NamespaceURI.StartsWith("http://www.w3.org/", StringComparison.Ordinal))
{
                            throw ExceptionBuilder.DataSetUnsupportedSchema("http://www.w3.org/2001/XMLSchema");
                        }
                        if (mode == XmlReadMode.DiffGram)
{
                            reader.Skip();
                            continue;
                        }
                        flag2 = true;
                        if (mode == XmlReadMode.InferSchema || mode == XmlReadMode.InferTypedSchema)
{
                            XmlNode newChild = xmlDocument.ReadNode(reader);
                            xmlElement.AppendChild(newChild);
                            continue;
                        }
                        if (xmlDataLoader == null)
{
                            xmlDataLoader = new XmlDataLoader(this, isXdr, xmlElement, mode == XmlReadMode.IgnoreSchema);
                        }
                        xmlDataLoader.LoadData(reader);
                    }
                    ReadEndElement(reader);
                    xmlDocument.AppendChild(xmlElement);
                    if (xmlDataLoader == null)
                    {
                        xmlDataLoader = new XmlDataLoader(this, isXdr, mode == XmlReadMode.IgnoreSchema);
                    }
                    switch (mode)
                    {
                    case XmlReadMode.DiffGram:
                        return result;
                    case XmlReadMode.InferSchema:
                    case XmlReadMode.InferTypedSchema:
                        InferSchema(xmlDocument, null, mode);
                        result = XmlReadMode.InferSchema;
                        xmlDataLoader.FromInference = true;
                        try
{
                            xmlDataLoader.LoadData(xmlDocument);
                        }
                        finally
{
                            xmlDataLoader.FromInference = false;
                        }
                        break;
                    }
                }
                return result;
            }
            finally
            {
            }
        }
        finally
        {
            disposable?.Dispose();
            DataCommonEventSource.Log.ExitScope(scopeId);
        }
    }
References System.Xml.XmlReader.AttributeCount, System.Data.ExceptionBuilder.DataSetUnsupportedSchema(), System.Xml.XmlReader.Depth, System.Runtime.Serialization.Dictionary, System.Data.TypeLimiter.EnterRestrictedScope(), System.Xml.XmlReader.GetAttribute(), System.Xml.XmlReader.HasAttributes, System.Data.InferSchema, System.Xml.XmlReader.LocalName, System.Data.DataCommonEventSource.Log, System.Xml.XmlReader.MoveToAttribute(), System.Xml.XmlReader.MoveToContent(), System.Data.DataSet.MoveToElement(), System.Xml.XmlReader.Name, System.Xml.XmlReader.NamespaceURI, System.Xml.XmlReader.NodeType, System.Data.DataSet.ObjectID, System.Xml.XmlReader.Prefix, System.Xml.XmlReader.Read(), System.Data.DataSet.ReadEndElement(), System.Data.DataSet.ReadXDRSchema(), System.Data.DataSet.ReadXml(), System.Data.DataSet.ReadXmlDiffgram(), System.Data.DataSet.ReadXSDSchema(), and System.Xml.XmlReader.Skip().