Terraria: System.Data.DataSet.DeserializeDataSetData
DeserializeDataSetData()
void System.Data.DataSet.DeserializeDataSetData (SerializationInfo info, StreamingContext context, SerializationFormat remotingFormat) inline private
Definition at line 679 of file DataSet.cs.
    {
        if (remotingFormat != 0)
        {
            for (int i = 0; i < Tables.Count; i++)
            {
                Tables[i].DeserializeTableData(info, context, i);
            }
            return;
        }
        string text = (string)info.GetValue("XmlDiffGram", typeof(string));
        if (text != null)
        {
            ReadXml(new XmlTextReader(new StringReader(text)), XmlReadMode.DiffGram);
        }
    }
References System.Data.InternalDataCollectionBase.Count, System.info, System.Data.DataSet.ReadXml(), System.Data.DataSet.Tables, and System.text.
Referenced by System.Data.DataSet.DeserializeDataSet(), and System.Data.DataSet.GetSerializationData().