Terraria: System.Data.DataSet.SerializeDataSet
SerializeDataSet()
void System.Data.DataSet.SerializeDataSet (SerializationInfo info, StreamingContext context, SerializationFormat remotingFormat) inline private
Definition at line 570 of file DataSet.cs.
    {
        info.AddValue("DataSet.RemotingVersion", new Version(2, 0));
        if (remotingFormat != 0)
        {
            info.AddValue("DataSet.RemotingFormat", remotingFormat);
        }
        if (SchemaSerializationMode.IncludeSchema != SchemaSerializationMode)
        {
            info.AddValue("SchemaSerializationMode.DataSet", SchemaSerializationMode);
        }
        if (remotingFormat != 0)
        {
            if (SchemaSerializationMode == SchemaSerializationMode.IncludeSchema)
            {
                SerializeDataSetProperties(info, context);
                info.AddValue("DataSet.Tables.Count", Tables.Count);
                for (int i = 0; i < Tables.Count; i++)
                {
                    BinaryFormatter binaryFormatter = new BinaryFormatter(null, new StreamingContext(context.State, false));
                    MemoryStream memoryStream = new MemoryStream();
                    binaryFormatter.Serialize(memoryStream, Tables[i]);
                    memoryStream.Position = 0L;
                    info.AddValue(string.Format(CultureInfo.InvariantCulture, "DataSet.Tables_{0}", i), memoryStream.GetBuffer());
                }
                for (int j = 0; j < Tables.Count; j++)
                {
                    Tables[j].SerializeConstraints(info, context, j, allConstraints: true);
                }
                SerializeRelations(info, context);
                for (int k = 0; k < Tables.Count; k++)
                {
                    Tables[k].SerializeExpressionColumns(info, context, k);
                }
            }
            else
            {
                SerializeDataSetProperties(info, context);
            }
            for (int l = 0; l < Tables.Count; l++)
            {
                Tables[l].SerializeTableData(info, context, l);
            }
        }
        else
        {
            string xmlSchemaForRemoting = GetXmlSchemaForRemoting(null);
            string text = null;
            info.AddValue("XmlSchema", xmlSchemaForRemoting);
            StringBuilder sb = new StringBuilder(EstimatedXmlStringSize() * 2);
            StringWriter stringWriter = new StringWriter(sb, CultureInfo.InvariantCulture);
            XmlTextWriter writer = new XmlTextWriter(stringWriter);
            WriteXml(writer, XmlWriteMode.DiffGram);
            text = stringWriter.ToString();
            info.AddValue("XmlDiffGram", text);
        }
    }
References System.Data.InternalDataCollectionBase.Count, System.Runtime.Serialization.Dictionary, System.Data.DataSet.EstimatedXmlStringSize(), System.Format, System.Data.DataSet.GetXmlSchemaForRemoting(), System.info, System.Globalization.CultureInfo.InvariantCulture, System.L, System.Data.DataSet.SerializeDataSetProperties(), System.Data.DataSet.SerializeRelations(), System.Runtime.Serialization.StreamingContext.State, System.Data.DataSet.Tables, System.text, System.writer, and System.Data.DataSet.WriteXml().
Referenced by System.Data.DataSet.GetObjectData().