Terraria: System.Data.DataSet.SetLocaleValue
SetLocaleValue()
void System.Data.DataSet.SetLocaleValue (CultureInfo value, bool userSet) inline package
Definition at line 825 of file DataSet.cs.
    {
        bool flag = false;
        bool flag2 = false;
        int num = 0;
        CultureInfo culture = _culture;
        bool cultureUserSet = _cultureUserSet;
        try
        {
            _culture = value;
            _cultureUserSet = userSet;
            foreach (DataTable table in Tables)
            {
                if (!table.ShouldSerializeLocale())
                {
                    table.SetLocaleValue(value, userSet: false, resetIndexes: false);
                }
            }
            flag = ValidateLocaleConstraint();
            if (!flag)
            {
                return;
            }
            flag = false;
            foreach (DataTable table2 in Tables)
            {
                num++;
                if (!table2.ShouldSerializeLocale())
                {
                    table2.SetLocaleValue(value, userSet: false, resetIndexes: true);
                }
            }
            flag = true;
        }
        catch
        {
            flag2 = true;
            throw;
        }
        finally
        {
            if (!flag)
            {
                _culture = culture;
                _cultureUserSet = cultureUserSet;
                foreach (DataTable table3 in Tables)
                {
                    if (!table3.ShouldSerializeLocale())
                    {
                        table3.SetLocaleValue(culture, userSet: false, resetIndexes: false);
                    }
                }
                try
                {
                    for (int i = 0; i < num; i++)
                    {
                        if (!Tables[i].ShouldSerializeLocale())
{
                            Tables[i].SetLocaleValue(culture, userSet: false, resetIndexes: true);
                        }
                    }
                }
                catch (Exception e) when (ADP.IsCatchableExceptionType(e))
                {
                    ADP.TraceExceptionWithoutRethrow(e);
                }
                if (!flag2)
                {
                    throw ExceptionBuilder.CannotChangeCaseLocale(null);
                }
            }
        }
    }
References System.Data.DataSet._culture, System.Data.DataSet._cultureUserSet, System.Data.ExceptionBuilder.CannotChangeCaseLocale(), System.culture, System.Runtime.Serialization.Dictionary, System.Data.Common.ADP.IsCatchableExceptionType(), System.Data.DataTable.SetLocaleValue(), System.Data.DataSet.ShouldSerializeLocale(), System.Data.DataTable.ShouldSerializeLocale(), System.Data.DataSet.Tables, System.Data.Common.ADP.TraceExceptionWithoutRethrow(), System.Data.DataSet.ValidateLocaleConstraint(), and System.value.
Referenced by System.Data.XSDSchema.HandleDataSet().