Terraria: System.Data.DataSet.DataSet
DataSet() [1/4]
System.Data.DataSet.DataSet () inline
Definition at line 434 of file DataSet.cs.
    {
        GC.SuppressFinalize(this);
        DataCommonEventSource.Log.Trace("<ds.DataSet.DataSet|API> {0}", ObjectID);
        _tableCollection = new DataTableCollection(this);
        _relationCollection = new DataRelationCollection.DataSetRelationCollection(this);
        _culture = CultureInfo.CurrentCulture;
    }
References System.Data.DataSet._culture, System.Data.DataSet._relationCollection, System.Data.DataSet._tableCollection, System.Globalization.CultureInfo.CurrentCulture, System.Data.DataCommonEventSource.Log, System.Data.DataSet.ObjectID, and System.GC.SuppressFinalize().
Referenced by System.Data.XmlDataTreeWriter.XmlDataTreeWriter(), System.Data.XmlTreeGen.SchemaTree(), System.Data.XmlTreeGen.SchemaTree(), and System.Data.DataRow.SetParentRow().