Terraria: System.Data.DataSet.Load
Load() [3/3]
void System.Data.DataSet.Load (IDataReader reader, LoadOption loadOption, params string[] tables) inline
Definition at line 3006 of file DataSet.cs.
    {
        ADP.CheckArgumentNull(tables, "tables");
        DataTable[] array = new DataTable[tables.Length];
        for (int i = 0; i < tables.Length; i++)
        {
            DataTable dataTable = Tables[tables[i]];
            if (dataTable == null)
            {
                dataTable = new DataTable(tables[i]);
                Tables.Add(dataTable);
            }
            array[i] = dataTable;
        }
        Load(reader, loadOption, null, array);
    }
References System.Data.DataTableCollection.Add(), System.array, System.Data.Common.ADP.CheckArgumentNull(), System.Runtime.Serialization.Dictionary, System.Data.DataSet.Load(), and System.Data.DataSet.Tables.