Terraria: System.Data.DataSet.DeserializeDataSetSchema
DeserializeDataSetSchema()
void System.Data.DataSet.DeserializeDataSetSchema (SerializationInfo info, StreamingContext context, SerializationFormat remotingFormat, SchemaSerializationMode schemaSerializationMode) inline private
Definition at line 636 of file DataSet.cs.
    {
        if (remotingFormat != 0)
        {
            if (schemaSerializationMode == SchemaSerializationMode.IncludeSchema)
            {
                DeserializeDataSetProperties(info, context);
                int @int = info.GetInt32("DataSet.Tables.Count");
                for (int i = 0; i < @int; i++)
                {
                    byte[] buffer = (byte[])info.GetValue(string.Format(CultureInfo.InvariantCulture, "DataSet.Tables_{0}", i), typeof(byte[]));
                    MemoryStream memoryStream = new MemoryStream(buffer);
                    memoryStream.Position = 0L;
                    BinaryFormatter binaryFormatter = new BinaryFormatter(null, new StreamingContext(context.State, false));
                    DataTable table = (DataTable)binaryFormatter.Deserialize(memoryStream);
                    Tables.Add(table);
                }
                for (int j = 0; j < @int; j++)
                {
                    Tables[j].DeserializeConstraints(info, context, j, allConstraints: true);
                }
                DeserializeRelations(info, context);
                for (int k = 0; k < @int; k++)
                {
                    Tables[k].DeserializeExpressionColumns(info, context, k);
                }
            }
            else
            {
                DeserializeDataSetProperties(info, context);
            }
        }
        else
        {
            string text = (string)info.GetValue("XmlSchema", typeof(string));
            if (text != null)
            {
                ReadXmlSchema(new XmlTextReader(new StringReader(text)), denyResolving: true);
            }
        }
    }
References System.Data.DataTableCollection.Add(), System.buffer, System.Data.DataSet.DeserializeDataSetProperties(), System.Data.DataSet.DeserializeRelations(), System.Runtime.Serialization.Dictionary, System.info, System.Globalization.CultureInfo.InvariantCulture, System.L, System.Data.DataSet.ReadXmlSchema(), System.Runtime.Serialization.StreamingContext.State, System.Data.DataSet.Tables, and System.text.
Referenced by System.Data.DataSet.DeserializeDataSet().