Terraria: System.Data.DataSet.SerializeRelations
SerializeRelations()
void System.Data.DataSet.SerializeRelations (SerializationInfo info, StreamingContext context) inline private
Definition at line 720 of file DataSet.cs.
    {
        ArrayList arrayList = new ArrayList();
        foreach (DataRelation relation in Relations)
        {
            int[] array = new int[relation.ParentColumns.Length + 1];
            array[0] = Tables.IndexOf(relation.ParentTable);
            for (int i = 1; i < array.Length; i++)
            {
                array[i] = relation.ParentColumns[i - 1].Ordinal;
            }
            int[] array2 = new int[relation.ChildColumns.Length + 1];
            array2[0] = Tables.IndexOf(relation.ChildTable);
            for (int j = 1; j < array2.Length; j++)
            {
                array2[j] = relation.ChildColumns[j - 1].Ordinal;
            }
            ArrayList arrayList2 = new ArrayList();
            arrayList2.Add(relation.RelationName);
            arrayList2.Add(array);
            arrayList2.Add(array2);
            arrayList2.Add(relation.Nested);
            arrayList2.Add(relation._extendedProperties);
            arrayList.Add(arrayList2);
        }
        info.AddValue("DataSet.Relations", arrayList);
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.array, System.Runtime.Serialization.Dictionary, System.Data.DataTableCollection.IndexOf(), System.info, System.Data.DataSet.Relations, and System.Data.DataSet.Tables.
Referenced by System.Data.DataSet.SerializeDataSet().