Terraria: System.Data.DataSet.ReadXSDSchema
ReadXSDSchema()
void System.Data.DataSet.ReadXSDSchema (XmlReader reader, bool denyResolving) inline package
Definition at line 1500 of file DataSet.cs.
    {
        XmlSchemaSet xmlSchemaSet = new XmlSchemaSet();
        int num = 1;
        if (reader.LocalName == "schema" && reader.NamespaceURI == "http://www.w3.org/2001/XMLSchema" && reader.HasAttributes)
        {
            string attribute = reader.GetAttribute("schemafragmentcount", "urn:schemas-microsoft-com:xml-msdata");
            if (!string.IsNullOrEmpty(attribute))
            {
                num = int.Parse(attribute, null);
            }
        }
        while (reader.LocalName == "schema" && reader.NamespaceURI == "http://www.w3.org/2001/XMLSchema")
        {
            XmlSchema schema = XmlSchema.Read(reader, null);
            xmlSchemaSet.Add(schema);
            ReadEndElement(reader);
            if (--num > 0)
            {
                MoveToElement(reader);
            }
            while (reader.NodeType == XmlNodeType.Whitespace)
            {
                reader.Skip();
            }
        }
        xmlSchemaSet.Compile();
        XSDSchema xSDSchema = new XSDSchema();
        xSDSchema.LoadSchema(xmlSchemaSet, this);
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Xml.XmlReader.GetAttribute(), System.Xml.XmlReader.HasAttributes, System.Xml.XmlReader.LocalName, System.Data.DataSet.MoveToElement(), System.Xml.XmlReader.NamespaceURI, System.Xml.XmlReader.NodeType, System.Xml.Schema.XmlSchema.Read(), System.Data.DataSet.ReadEndElement(), and System.Xml.XmlReader.Skip().
Referenced by System.Data.XmlDataLoader.ProcessXsdSchema(), System.Data.DataSet.ReadXml(), System.Data.DataSet.ReadXml(), and System.Data.DataSet.ReadXmlSchema().