Terraria: System.Data.XSDSchema.SetExtProperties
SetExtProperties() [1/2]
static void System.Data.XSDSchema.SetExtProperties (object instance, XmlAttribute[] attrs) inline static private
Definition at line 282 of file XSDSchema.cs.
    {
        PropertyCollection propertyCollection = null;
        if (attrs == null)
        {
            return;
        }
        for (int i = 0; i < attrs.Length; i++)
        {
            if (!(attrs[i].NamespaceURI == "urn:schemas-microsoft-com:xml-msprop"))
            {
                continue;
            }
            if (propertyCollection == null)
            {
                object value = TypeDescriptor.GetProperties(instance)["ExtendedProperties"].GetValue(instance);
                propertyCollection = (PropertyCollection)value;
            }
            string text = XmlConvert.DecodeName(attrs[i].LocalName);
            if (instance is ForeignKeyConstraint)
            {
                if (!text.StartsWith("fk_", StringComparison.Ordinal))
                {
                    continue;
                }
                text = text.Substring(3);
            }
            if (instance is DataRelation && text.StartsWith("rel_", StringComparison.Ordinal))
            {
                text = text.Substring(4);
            }
            else if (instance is DataRelation && text.StartsWith("fk_", StringComparison.Ordinal))
            {
                continue;
            }
            propertyCollection.Add(text, attrs[i].Value);
        }
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Xml.XmlConvert.DecodeName(), System.ComponentModel.TypeDescriptor.GetProperties(), System.text, and System.value.
Referenced by System.Data.XSDSchema.HandleAttributeColumn(), System.Data.XSDSchema.HandleConstraint(), System.Data.XSDSchema.HandleElementColumn(), System.Data.XSDSchema.HandleKeyref(), System.Data.XSDSchema.HandleRefTableProperties(), System.Data.XSDSchema.HandleRelation(), System.Data.XSDSchema.HandleSimpleContentColumn(), and System.Data.XSDSchema.HandleSimpleTypeSimpleContentColumn().