Terraria: System.Data.XSDSchema.HandleComplexType
HandleComplexType()
void System.Data.XSDSchema.HandleComplexType (XmlSchemaComplexType ct, DataTable table, ArrayList tableChildren, bool isNillable) inline package
Definition at line 944 of file XSDSchema.cs.
    {
        if (_complexTypes.Contains(ct))
        {
            throw ExceptionBuilder.CircularComplexType(ct.Name);
        }
        bool isBase = false;
        _complexTypes.Add(ct);
        if (ct.ContentModel != null)
        {
            if (ct.ContentModel is XmlSchemaComplexContent)
            {
                XmlSchemaAnnotated content = ((XmlSchemaComplexContent)ct.ContentModel).Content;
                if (content is XmlSchemaComplexContentExtension)
                {
                    XmlSchemaComplexContentExtension xmlSchemaComplexContentExtension = (XmlSchemaComplexContentExtension)content;
                    if (!(ct.BaseXmlSchemaType is XmlSchemaComplexType) || !FromInference)
                    {
                        HandleAttributes(xmlSchemaComplexContentExtension.Attributes, table, isBase);
                    }
                    if (ct.BaseXmlSchemaType is XmlSchemaComplexType)
                    {
                        HandleComplexType((XmlSchemaComplexType)ct.BaseXmlSchemaType, table, tableChildren, isNillable);
                    }
                    else if (xmlSchemaComplexContentExtension.BaseTypeName.Namespace != "http://www.w3.org/2001/XMLSchema")
                    {
                        HandleSimpleContentColumn(xmlSchemaComplexContentExtension.BaseTypeName.ToString(), table, isBase, ct.ContentModel.UnhandledAttributes, isNillable);
                    }
                    else
                    {
                        HandleSimpleContentColumn(xmlSchemaComplexContentExtension.BaseTypeName.Name, table, isBase, ct.ContentModel.UnhandledAttributes, isNillable);
                    }
                    if (xmlSchemaComplexContentExtension.Particle != null)
                    {
                        HandleParticle(xmlSchemaComplexContentExtension.Particle, table, tableChildren, isBase);
                    }
                    if (ct.BaseXmlSchemaType is XmlSchemaComplexType && FromInference)
                    {
                        HandleAttributes(xmlSchemaComplexContentExtension.Attributes, table, isBase);
                    }
                }
                else
                {
                    XmlSchemaComplexContentRestriction xmlSchemaComplexContentRestriction = (XmlSchemaComplexContentRestriction)content;
                    if (!FromInference)
                    {
                        HandleAttributes(xmlSchemaComplexContentRestriction.Attributes, table, isBase);
                    }
                    if (xmlSchemaComplexContentRestriction.Particle != null)
                    {
                        HandleParticle(xmlSchemaComplexContentRestriction.Particle, table, tableChildren, isBase);
                    }
                    if (FromInference)
                    {
                        HandleAttributes(xmlSchemaComplexContentRestriction.Attributes, table, isBase);
                    }
                }
            }
            else
            {
                XmlSchemaAnnotated content2 = ((XmlSchemaSimpleContent)ct.ContentModel).Content;
                if (content2 is XmlSchemaSimpleContentExtension)
                {
                    XmlSchemaSimpleContentExtension xmlSchemaSimpleContentExtension = (XmlSchemaSimpleContentExtension)content2;
                    HandleAttributes(xmlSchemaSimpleContentExtension.Attributes, table, isBase);
                    if (ct.BaseXmlSchemaType is XmlSchemaComplexType)
                    {
                        HandleComplexType((XmlSchemaComplexType)ct.BaseXmlSchemaType, table, tableChildren, isNillable);
                    }
                    else
                    {
                        HandleSimpleTypeSimpleContentColumn((XmlSchemaSimpleType)ct.BaseXmlSchemaType, xmlSchemaSimpleContentExtension.BaseTypeName.Name, table, isBase, ct.ContentModel.UnhandledAttributes, isNillable);
                    }
                }
                else
                {
                    XmlSchemaSimpleContentRestriction xmlSchemaSimpleContentRestriction = (XmlSchemaSimpleContentRestriction)content2;
                    HandleAttributes(xmlSchemaSimpleContentRestriction.Attributes, table, isBase);
                }
            }
        }
        else
        {
            isBase = true;
            if (!FromInference)
            {
                HandleAttributes(ct.Attributes, table, isBase);
            }
            if (ct.Particle != null)
            {
                HandleParticle(ct.Particle, table, tableChildren, isBase);
            }
            if (FromInference)
            {
                HandleAttributes(ct.Attributes, table, isBase);
                if (isNillable)
                {
                    HandleSimpleContentColumn("string", table, isBase, null, isNillable);
                }
            }
        }
        _complexTypes.Remove(ct);
    }
References System.Data.XSDSchema._complexTypes, System.Collections.ArrayList.Add(), System.Data.ExceptionBuilder.CircularComplexType(), System.Collections.ArrayList.Contains(), System.Data.XSDSchema.FromInference, System.Data.XSDSchema.HandleAttributes(), System.Data.XSDSchema.HandleComplexType(), System.Data.XSDSchema.HandleParticle(), System.Data.XSDSchema.HandleSimpleContentColumn(), System.Data.XSDSchema.HandleSimpleTypeSimpleContentColumn(), and System.Collections.ArrayList.Remove().
Referenced by System.Data.XSDSchema.HandleComplexType().