Terraria: System.Data.XSDSchema.GetParticleItems
GetParticleItems()
XmlSchemaObjectCollection System.Data.XSDSchema.GetParticleItems (XmlSchemaParticle pt) inline package
Definition at line 799 of file XSDSchema.cs.
    {
        if (pt is XmlSchemaSequence)
        {
            return ((XmlSchemaSequence)pt).Items;
        }
        if (pt is XmlSchemaAll)
        {
            return ((XmlSchemaAll)pt).Items;
        }
        if (pt is XmlSchemaChoice)
        {
            return ((XmlSchemaChoice)pt).Items;
        }
        if (pt is XmlSchemaAny)
        {
            return null;
        }
        if (pt is XmlSchemaElement)
        {
            XmlSchemaObjectCollection xmlSchemaObjectCollection = new XmlSchemaObjectCollection();
            xmlSchemaObjectCollection.Add(pt);
            return xmlSchemaObjectCollection;
        }
        if (pt is XmlSchemaGroupRef)
        {
            return GetParticleItems(((XmlSchemaGroupRef)pt).Particle);
        }
        return null;
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Xml.Dictionary, and System.Data.XSDSchema.GetParticleItems().
Referenced by System.Data.XSDSchema.GetParticleItems(), System.Data.XSDSchema.HandleParticle(), System.Data.XSDSchema.IsDatasetParticle(), and System.Data.XSDSchema.LoadSchema().