Terraria: System.Data.XSDSchema.InstantiateTable
InstantiateTable()
DataTable System.Data.XSDSchema.InstantiateTable (XmlSchemaElement node, XmlSchemaComplexType typeNode, bool isRef) inline package
Definition at line 1391 of file XSDSchema.cs.
    {
        string instanceName = GetInstanceName(node);
        ArrayList arrayList = new ArrayList();
        string @namespace = node.QualifiedName.Namespace;
        DataTable dataTable = _ds.Tables.GetTable(XmlConvert.DecodeName(instanceName), @namespace);
        if (!FromInference || (FromInference && dataTable == null))
        {
            if (dataTable != null)
            {
                if (isRef)
                {
                    return dataTable;
                }
                throw ExceptionBuilder.DuplicateDeclaration(instanceName);
            }
            if (isRef)
            {
                _refTables.Add(@namespace + ":" + instanceName);
            }
            dataTable = new DataTable(XmlConvert.DecodeName(instanceName));
            dataTable.TypeName = node.SchemaTypeName;
            dataTable.Namespace = @namespace;
            dataTable.Namespace = GetStringAttribute(node, "targetNamespace", @namespace);
            string stringAttribute = GetStringAttribute(typeNode, "CaseSensitive", "");
            if (stringAttribute.Length == 0)
            {
                stringAttribute = GetStringAttribute(node, "CaseSensitive", "");
            }
            if (0 < stringAttribute.Length)
            {
                if (stringAttribute == "true" || stringAttribute == "True")
                {
                    dataTable.CaseSensitive = true;
                }
                if (stringAttribute == "false" || stringAttribute == "False")
                {
                    dataTable.CaseSensitive = false;
                }
            }
            stringAttribute = GetMsdataAttribute(node, "Locale");
            if (stringAttribute != null)
            {
                if (0 < stringAttribute.Length)
                {
                    dataTable.Locale = new CultureInfo(stringAttribute);
                }
                else
                {
                    dataTable.Locale = CultureInfo.InvariantCulture;
                }
            }
            if (!FromInference)
            {
                dataTable.MinOccurs = node.MinOccurs;
                dataTable.MaxOccurs = node.MaxOccurs;
            }
            else
            {
                string prefix = GetPrefix(@namespace);
                if (prefix != null)
                {
                    dataTable.Prefix = prefix;
                }
            }
            _ds.Tables.Add(dataTable);
            if (FromInference)
            {
                _tableDictionary.Add(dataTable, new List<DataTable>());
            }
        }
        HandleComplexType(typeNode, dataTable, arrayList, node.IsNillable);
        for (int i = 0; i < dataTable.Columns.Count; i++)
        {
            dataTable.Columns[i].SetOrdinalInternal(i);
        }
        SetProperties(dataTable, node.UnhandledAttributes);
        SetExtProperties(dataTable, node.UnhandledAttributes);
        if (_dsElement != null && _dsElement.Constraints != null)
        {
            foreach (XmlSchemaIdentityConstraint constraint in _dsElement.Constraints)
            {
                if (!(constraint is XmlSchemaKeyref) && GetTableName(constraint) == dataTable.TableName && (GetTableNamespace(constraint) == dataTable.Namespace || GetTableNamespace(constraint) == null))
                {
                    HandleConstraint(constraint);
                }
            }
        }
        foreach (DataTable item in arrayList)
        {
            if (item != dataTable && dataTable.Namespace == item.Namespace)
            {
                item._tableNamespace = null;
            }
            if (_dsElement != null && _dsElement.Constraints != null)
            {
                foreach (XmlSchemaIdentityConstraint constraint2 in _dsElement.Constraints)
                {
                    if (!(constraint2 is XmlSchemaKeyref xmlSchemaKeyref) || !GetBooleanAttribute(xmlSchemaKeyref, "IsNested", defVal: false) || !(GetTableName(xmlSchemaKeyref) == item.TableName))
                    {
                        continue;
                    }
                    if (item.DataSet.Tables.InternalIndexOf(item.TableName) < -1)
                    {
                        if (GetTableNamespace(xmlSchemaKeyref) == item.Namespace)
{
                            HandleKeyref(xmlSchemaKeyref);
                        }
                    }
                    else
                    {
                        HandleKeyref(xmlSchemaKeyref);
                    }
                }
            }
            DataRelation dataRelation = null;
            DataRelationCollection childRelations = dataTable.ChildRelations;
            for (int j = 0; j < childRelations.Count; j++)
            {
                if (childRelations[j].Nested && item == childRelations[j].ChildTable)
                {
                    dataRelation = childRelations[j];
                }
            }
            if (dataRelation != null)
            {
                continue;
            }
            DataColumn dataColumn2;
            if (FromInference)
            {
                int num = dataTable.UKColumnPositionForInference;
                if (num == -1)
                {
                    foreach (DataColumn column in dataTable.Columns)
                    {
                        if (column.ColumnMapping == MappingType.Attribute)
{
                            num = column.Ordinal;
                            break;
                        }
                    }
                }
                dataColumn2 = dataTable.AddUniqueKey(num);
            }
            else
            {
                dataColumn2 = dataTable.AddUniqueKey();
            }
            DataColumn dataColumn3 = item.AddForeignKey(dataColumn2);
            if (FromInference)
            {
                dataColumn3.Prefix = item.Prefix;
            }
            dataRelation = new DataRelation(dataTable.TableName + "_" + item.TableName, dataColumn2, dataColumn3, createConstraints: true);
            dataRelation.Nested = true;
            item.DataSet.Relations.Add(dataRelation);
            if (FromInference && dataRelation.Nested && _tableDictionary.ContainsKey(dataRelation.ParentTable))
            {
                _tableDictionary[dataRelation.ParentTable].Add(dataRelation.ChildTable);
            }
        }
        return dataTable;
    }
References System.Data.DataTableCollection.Add(), System.Collections.ArrayList.Add(), System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Xml.Schema.XmlSchemaElement.Constraints, System.Collections.Generic.Dictionary< TKey, TValue >.ContainsKey(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Xml.XmlConvert.DecodeName(), System.Xml.Dictionary, System.Data.ExceptionBuilder.DuplicateDeclaration(), System.Data.XSDSchema.GetInstanceName(), System.Data.DataTableCollection.GetTable(), System.Globalization.CultureInfo.InvariantCulture, System.item, System.prefix, and System.Data.DataSet.Tables.