Terraria: System.Data.XSDSchema.BuildKey
BuildKey()
DataColumn[] System.Data.XSDSchema.BuildKey (XmlSchemaIdentityConstraint keyNode, DataTable table) inline package
Definition at line 1090 of file XSDSchema.cs.
    {
        ArrayList arrayList = new ArrayList();
        foreach (XmlSchemaXPath field in keyNode.Fields)
        {
            arrayList.Add(FindField(table, field.XPath));
        }
        DataColumn[] array = new DataColumn[arrayList.Count];
        arrayList.CopyTo(array, 0);
        return array;
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.array, System.Collections.Generic.Dictionary< TKey, TValue >.CopyTo(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, and System.Data.XSDSchema.FindField().
Referenced by System.Data.XSDSchema.HandleConstraint(), and System.Data.XSDSchema.HandleKeyref().