Terraria: System.Data.XSDSchema.FindField
FindField()
DataColumn System.Data.XSDSchema.FindField (DataTable table, string field) inline package
Definition at line 1066 of file XSDSchema.cs.
    {
        bool flag = false;
        string text = field;
        if (field.StartsWith('@'))
        {
            flag = true;
            text = field.Substring(1);
        }
        text = text.Split(':')[^1];
        text = XmlConvert.DecodeName(text);
        DataColumn dataColumn = table.Columns[text];
        if (dataColumn == null)
        {
            throw ExceptionBuilder.InvalidField(field);
        }
        bool flag2 = dataColumn.ColumnMapping == MappingType.Attribute || dataColumn.ColumnMapping == MappingType.Hidden;
        if (flag2 != flag)
        {
            throw ExceptionBuilder.InvalidField(field);
        }
        return dataColumn;
    }
References System.Data.DataTable.Columns, System.Xml.XmlConvert.DecodeName(), System.Xml.Dictionary, System.Data.ExceptionBuilder.InvalidField(), and System.text.
Referenced by System.Data.XSDSchema.BuildKey().