Terraria: System.Data.XSDSchema.HandleAttributeColumn
HandleAttributeColumn()
void System.Data.XSDSchema.HandleAttributeColumn (XmlSchemaAttribute attrib, DataTable table, bool isBase) inline package
Definition at line 1864 of file XSDSchema.cs.
    {
        Type type = null;
        XmlSchemaAttribute xmlSchemaAttribute = ((attrib.Name != null) ? attrib : ((XmlSchemaAttribute)_attributes[attrib.RefName]));
        XmlSchemaAnnotated xmlSchemaAnnotated = FindTypeNode(xmlSchemaAttribute);
        string text = null;
        SimpleType simpleType = null;
        if (xmlSchemaAnnotated == null)
        {
            text = xmlSchemaAttribute.SchemaTypeName.Name;
            if (!string.IsNullOrEmpty(text))
            {
                type = ((!(xmlSchemaAttribute.SchemaTypeName.Namespace != "http://www.w3.org/2001/XMLSchema")) ? ParseDataType(xmlSchemaAttribute.SchemaTypeName.Name) : ParseDataType(xmlSchemaAttribute.SchemaTypeName.ToString()));
            }
            else
            {
                text = string.Empty;
                type = typeof(string);
            }
        }
        else if (xmlSchemaAnnotated is XmlSchemaSimpleType)
        {
            XmlSchemaSimpleType xmlSchemaSimpleType = xmlSchemaAnnotated as XmlSchemaSimpleType;
            simpleType = new SimpleType(xmlSchemaSimpleType);
            if (xmlSchemaSimpleType.QualifiedName.Name != null && xmlSchemaSimpleType.QualifiedName.Name.Length != 0 && xmlSchemaSimpleType.QualifiedName.Namespace != "http://www.w3.org/2001/XMLSchema")
            {
                text = xmlSchemaSimpleType.QualifiedName.ToString();
                type = ParseDataType(xmlSchemaSimpleType.QualifiedName.ToString());
            }
            else
            {
                type = ParseDataType(simpleType.BaseType);
                text = simpleType.Name;
                if (simpleType.Length == 1 && type == typeof(string))
                {
                    type = typeof(char);
                }
            }
        }
        else
        {
            if (!(xmlSchemaAnnotated is XmlSchemaElement))
            {
                if (xmlSchemaAnnotated.Id == null)
                {
                    throw ExceptionBuilder.DatatypeNotDefined();
                }
                throw ExceptionBuilder.UndefinedDatatype(xmlSchemaAnnotated.Id);
            }
            text = ((XmlSchemaElement)xmlSchemaAnnotated).SchemaTypeName.Name;
            type = ParseDataType(text);
        }
        string text2 = XmlConvert.DecodeName(GetInstanceName(xmlSchemaAttribute));
        bool flag = true;
        DataColumn dataColumn;
        if ((!isBase || FromInference) && table.Columns.Contains(text2, caseSensitive: true))
        {
            dataColumn = table.Columns[text2];
            flag = false;
            if (FromInference)
            {
                if (dataColumn.ColumnMapping != MappingType.Attribute)
                {
                    throw ExceptionBuilder.ColumnTypeConflict(dataColumn.ColumnName);
                }
                if ((string.IsNullOrEmpty(attrib.QualifiedName.Namespace) && string.IsNullOrEmpty(dataColumn._columnUri)) || string.Equals(attrib.QualifiedName.Namespace, dataColumn.Namespace, StringComparison.Ordinal))
                {
                    return;
                }
                dataColumn = new DataColumn(text2, type, null, MappingType.Attribute);
                flag = true;
            }
        }
        else
        {
            dataColumn = new DataColumn(text2, type, null, MappingType.Attribute);
        }
        SetProperties(dataColumn, xmlSchemaAttribute.UnhandledAttributes);
        HandleColumnExpression(dataColumn, xmlSchemaAttribute.UnhandledAttributes);
        SetExtProperties(dataColumn, xmlSchemaAttribute.UnhandledAttributes);
        if (dataColumn.Expression != null && dataColumn.Expression.Length != 0)
        {
            _columnExpressions.Add(dataColumn);
        }
        if (simpleType != null && simpleType.Name != null && simpleType.Name.Length > 0)
        {
            if (GetMsdataAttribute(xmlSchemaAnnotated, "targetNamespace") != null)
            {
                dataColumn.XmlDataType = simpleType.SimpleTypeQualifiedName;
            }
        }
        else
        {
            dataColumn.XmlDataType = text;
        }
        dataColumn.SimpleType = simpleType;
        dataColumn.AllowDBNull = attrib.Use != XmlSchemaUse.Required;
        dataColumn.Namespace = attrib.QualifiedName.Namespace;
        dataColumn.Namespace = GetStringAttribute(attrib, "targetNamespace", dataColumn.Namespace);
        if (flag)
        {
            if (FromInference)
            {
                dataColumn.AllowDBNull = true;
                dataColumn.Prefix = GetPrefix(dataColumn.Namespace);
            }
            table.Columns.Add(dataColumn);
        }
        if (attrib.Use == XmlSchemaUse.Prohibited)
        {
            dataColumn.ColumnMapping = MappingType.Hidden;
            dataColumn.AllowDBNull = GetBooleanAttribute(xmlSchemaAttribute, "AllowDBNull", defVal: true);
            string msdataAttribute = GetMsdataAttribute(xmlSchemaAttribute, "DefaultValue");
            if (msdataAttribute != null)
            {
                try
                {
                    dataColumn.DefaultValue = dataColumn.ConvertXmlToObject(msdataAttribute);
                }
                catch (FormatException)
                {
                    throw ExceptionBuilder.CannotConvert(msdataAttribute, type.FullName);
                }
            }
        }
        string text3 = ((attrib.Use == XmlSchemaUse.Required) ? GetMsdataAttribute(xmlSchemaAttribute, "DefaultValue") : xmlSchemaAttribute.DefaultValue);
        if (xmlSchemaAttribute.Use == XmlSchemaUse.Optional && text3 == null)
        {
            text3 = xmlSchemaAttribute.FixedValue;
        }
        if (text3 != null)
        {
            try
            {
                dataColumn.DefaultValue = dataColumn.ConvertXmlToObject(text3);
            }
            catch (FormatException)
            {
                throw ExceptionBuilder.CannotConvert(text3, type.FullName);
            }
        }
    }
References System.Data.XSDSchema._attributes, System.Data.XSDSchema._columnExpressions, System.Data.DataColumnCollection.Add(), System.Collections.ArrayList.Add(), System.Data.ExceptionBuilder.CannotConvert(), System.Data.DataTable.Columns, System.Data.ExceptionBuilder.ColumnTypeConflict(), System.Data.DataColumnCollection.Contains(), System.Data.ExceptionBuilder.DatatypeNotDefined(), System.Xml.XmlConvert.DecodeName(), System.Xml.Dictionary, System.Data.XSDSchema.FindTypeNode(), System.Data.XSDSchema.FromInference, System.Data.XSDSchema.GetBooleanAttribute(), System.Data.XSDSchema.GetInstanceName(), System.Data.XSDSchema.GetMsdataAttribute(), System.Data.XSDSchema.GetPrefix(), System.Data.XSDSchema.GetStringAttribute(), System.Data.XSDSchema.HandleColumnExpression(), System.Data.XSDSchema.ParseDataType(), System.Data.XSDSchema.SetExtProperties(), System.Data.XSDSchema.SetProperties(), System.text, System.type, and System.Data.ExceptionBuilder.UndefinedDatatype().
Referenced by System.Data.XSDSchema.HandleAttributeGroup(), and System.Data.XSDSchema.HandleAttributes().