Terraria: System.Data.XSDSchema.IsDatasetParticle
IsDatasetParticle()
bool System.Data.XSDSchema.IsDatasetParticle (XmlSchemaParticle pt) inline private
Definition at line 485 of file XSDSchema.cs.
    {
        XmlSchemaObjectCollection particleItems = GetParticleItems(pt);
        if (particleItems == null)
        {
            return false;
        }
        bool flag = FromInference && pt is XmlSchemaChoice;
        foreach (XmlSchemaAnnotated item in particleItems)
        {
            if (item is XmlSchemaElement)
            {
                if (flag && pt.MaxOccurs > 1m && ((XmlSchemaElement)item).SchemaType is XmlSchemaComplexType)
                {
                    ((XmlSchemaElement)item).MaxOccurs = pt.MaxOccurs;
                }
                if ((((XmlSchemaElement)item).RefName.Name.Length == 0 || (FromInference && (!(((XmlSchemaElement)item).MaxOccurs != 1m) || ((XmlSchemaElement)item).SchemaType is XmlSchemaComplexType))) && !IsTable((XmlSchemaElement)item))
                {
                    return false;
                }
            }
            else if (item is XmlSchemaParticle && !IsDatasetParticle((XmlSchemaParticle)item))
            {
                return false;
            }
        }
        return true;
    }
References System.Xml.Dictionary, System.Data.XSDSchema.FromInference, System.Data.XSDSchema.GetParticleItems(), System.Data.XSDSchema.IsDatasetParticle(), System.Data.XSDSchema.IsTable(), System.item, and System.Xml.Schema.XmlSchemaParticle.MaxOccurs.
Referenced by System.Data.XSDSchema.FindDatasetElement(), and System.Data.XSDSchema.IsDatasetParticle().