Terraria: System.Data.XSDSchema.ParseDataType
ParseDataType()
Type System.Data.XSDSchema.ParseDataType (string dt) inline private
Definition at line 1577 of file XSDSchema.cs.
    {
        if (!IsXsdType(dt) && _udSimpleTypes != null)
        {
            XmlSchemaSimpleType xmlSchemaSimpleType = (XmlSchemaSimpleType)_udSimpleTypes[dt];
            if (xmlSchemaSimpleType == null)
            {
                throw ExceptionBuilder.UndefinedDatatype(dt);
            }
            SimpleType simpleType = new SimpleType(xmlSchemaSimpleType);
            while (simpleType.BaseSimpleType != null)
            {
                simpleType = simpleType.BaseSimpleType;
            }
            return ParseDataType(simpleType.BaseType);
        }
        NameType nameType = FindNameType(dt);
        return nameType.type;
    }
References System.Data.XSDSchema._udSimpleTypes, System.Data.XSDSchema.FindNameType(), System.Data.XSDSchema.IsXsdType(), System.Data.XSDSchema.ParseDataType(), and System.Data.ExceptionBuilder.UndefinedDatatype().
Referenced by System.Data.XSDSchema.HandleAttributeColumn(), System.Data.XSDSchema.HandleElementColumn(), System.Data.XSDSchema.HandleSimpleContentColumn(), System.Data.XSDSchema.HandleSimpleTypeSimpleContentColumn(), and System.Data.XSDSchema.ParseDataType().