Terraria: System.Data.XSDSchema.HandleRelations
HandleRelations()
void System.Data.XSDSchema.HandleRelations (XmlSchemaAnnotation ann, bool fNested) inline private
Definition at line 780 of file XSDSchema.cs.
    {
        foreach (XmlSchemaObject item in ann.Items)
        {
            if (!(item is XmlSchemaAppInfo))
            {
                continue;
            }
            XmlNode[] markup = ((XmlSchemaAppInfo)item).Markup;
            for (int i = 0; i < markup.Length; i++)
            {
                if (XMLSchema.FEqualIdentity(markup[i], "Relationship", "urn:schemas-microsoft-com:xml-msdata"))
                {
                    HandleRelation((XmlElement)markup[i], fNested);
                }
            }
        }
    }
References System.Data.XMLSchema.FEqualIdentity(), System.Data.XSDSchema.HandleRelation(), and System.item.
Referenced by System.Data.XSDSchema.HandleParticle(), and System.Data.XSDSchema.LoadSchema().