Terraria: System.Data.XSDSchema.CollectElementsAnnotations
CollectElementsAnnotations() [2/2]
void System.Data.XSDSchema.CollectElementsAnnotations (XmlSchema schema, ArrayList schemaList) inline private
Definition at line 138 of file XSDSchema.cs.
    {
        if (schemaList.Contains(schema))
        {
            return;
        }
        schemaList.Add(schema);
        foreach (XmlSchemaObject item in schema.Items)
        {
            if (item is XmlSchemaAnnotation)
            {
                _annotations.Add((XmlSchemaAnnotation)item);
            }
            if (item is XmlSchemaElement)
            {
                XmlSchemaElement xmlSchemaElement = (XmlSchemaElement)item;
                _elements.Add(xmlSchemaElement);
                _elementsTable[xmlSchemaElement.QualifiedName] = xmlSchemaElement;
            }
            if (item is XmlSchemaAttribute)
            {
                XmlSchemaAttribute xmlSchemaAttribute = (XmlSchemaAttribute)item;
                _attributes[xmlSchemaAttribute.QualifiedName] = xmlSchemaAttribute;
            }
            if (item is XmlSchemaAttributeGroup)
            {
                XmlSchemaAttributeGroup xmlSchemaAttributeGroup = (XmlSchemaAttributeGroup)item;
                _attributeGroups[xmlSchemaAttributeGroup.QualifiedName] = xmlSchemaAttributeGroup;
            }
            if (!(item is XmlSchemaType))
            {
                continue;
            }
            string text = null;
            if (item is XmlSchemaSimpleType)
            {
                text = GetMsdataAttribute((XmlSchemaType)item, "targetNamespace");
            }
            XmlSchemaType xmlSchemaType = (XmlSchemaType)item;
            _schemaTypes[xmlSchemaType.QualifiedName] = xmlSchemaType;
            if (!(item is XmlSchemaSimpleType xmlSchemaSimpleType))
            {
                continue;
            }
            if (_udSimpleTypes == null)
            {
                _udSimpleTypes = new Hashtable();
            }
            _udSimpleTypes[xmlSchemaType.QualifiedName.ToString()] = xmlSchemaSimpleType;
            SimpleType simpleType = ((DataColumn)_existingSimpleTypeMap[xmlSchemaType.QualifiedName.ToString()])?.SimpleType;
            if (simpleType != null)
            {
                SimpleType simpleType2 = new SimpleType(xmlSchemaSimpleType);
                string text2 = simpleType.HasConflictingDefinition(simpleType2);
                if (text2.Length != 0)
                {
                    throw ExceptionBuilder.InvalidDuplicateNamedSimpleTypeDelaration(simpleType2.SimpleTypeQualifiedName, text2);
                }
            }
        }
        foreach (XmlSchemaExternal include in schema.Includes)
        {
            if (!(include is XmlSchemaImport) && include.Schema != null)
            {
                CollectElementsAnnotations(include.Schema, schemaList);
            }
        }
    }
References System.Data.XSDSchema._annotations, System.Data.XSDSchema._attributeGroups, System.Data.XSDSchema._attributes, System.Data.XSDSchema._elements, System.Data.XSDSchema._elementsTable, System.Data.XSDSchema._existingSimpleTypeMap, System.Data.XSDSchema._schemaTypes, System.Data.XSDSchema._udSimpleTypes, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Xml.Schema.XmlSchemaObjectCollection.Add(), System.Data.XSDSchema.CollectElementsAnnotations(), System.Collections.Generic.Dictionary< TKey, TValue >.Contains(), System.Xml.Dictionary, System.Data.XSDSchema.GetMsdataAttribute(), System.Data.ExceptionBuilder.InvalidDuplicateNamedSimpleTypeDelaration(), System.item, and System.text.