Terraria: System.Data.XSDSchema.HandleSimpleContentColumn
HandleSimpleContentColumn()
void System.Data.XSDSchema.HandleSimpleContentColumn (string strType, DataTable table, bool isBase, XmlAttribute[] attrs, bool isNillable) inline package
Definition at line 1761 of file XSDSchema.cs.
    {
        if (FromInference && table.XmlText != null)
        {
            return;
        }
        Type type = null;
        if (strType == null)
        {
            return;
        }
        type = ParseDataType(strType);
        string text;
        if (FromInference)
        {
            int num = 0;
            text = table.TableName + "_Text";
            while (table.Columns[text] != null)
            {
                text += num++;
            }
        }
        else
        {
            text = table.TableName + "_text";
        }
        string text2 = text;
        bool flag = true;
        DataColumn dataColumn;
        if (!isBase && table.Columns.Contains(text2, caseSensitive: true))
        {
            dataColumn = table.Columns[text2];
            flag = false;
        }
        else
        {
            dataColumn = new DataColumn(text2, type, null, MappingType.SimpleContent);
        }
        SetProperties(dataColumn, attrs);
        HandleColumnExpression(dataColumn, attrs);
        SetExtProperties(dataColumn, attrs);
        string value = (-1).ToString(CultureInfo.CurrentCulture);
        string text3 = null;
        dataColumn.AllowDBNull = isNillable;
        if (attrs != null)
        {
            for (int i = 0; i < attrs.Length; i++)
            {
                if (attrs[i].LocalName == "AllowDBNull" && attrs[i].NamespaceURI == "urn:schemas-microsoft-com:xml-msdata" && attrs[i].Value == "false")
                {
                    dataColumn.AllowDBNull = false;
                }
                if (attrs[i].LocalName == "Ordinal" && attrs[i].NamespaceURI == "urn:schemas-microsoft-com:xml-msdata")
                {
                    value = attrs[i].Value;
                }
                if (attrs[i].LocalName == "DefaultValue" && attrs[i].NamespaceURI == "urn:schemas-microsoft-com:xml-msdata")
                {
                    text3 = attrs[i].Value;
                }
            }
        }
        int num2 = (int)Convert.ChangeType(value, typeof(int), null);
        if (dataColumn.Expression != null && dataColumn.Expression.Length != 0)
        {
            _columnExpressions.Add(dataColumn);
        }
        dataColumn.XmlDataType = strType;
        dataColumn.SimpleType = null;
        if (FromInference)
        {
            dataColumn.Prefix = GetPrefix(dataColumn.Namespace);
        }
        if (flag)
        {
            if (FromInference)
            {
                dataColumn.AllowDBNull = true;
            }
            if (num2 > -1 && num2 < table.Columns.Count)
            {
                table.Columns.AddAt(num2, dataColumn);
            }
            else
            {
                table.Columns.Add(dataColumn);
            }
        }
        if (text3 == null)
        {
            return;
        }
        try
        {
            dataColumn.DefaultValue = dataColumn.ConvertXmlToObject(text3);
        }
        catch (FormatException)
        {
            throw ExceptionBuilder.CannotConvert(text3, type.FullName);
        }
    }
References System.Data.XSDSchema._columnExpressions, System.Data.DataColumnCollection.Add(), System.Collections.ArrayList.Add(), System.Data.DataColumnCollection.AddAt(), System.Data.ExceptionBuilder.CannotConvert(), System.Convert.ChangeType(), System.Data.DataTable.Columns, System.Data.DataColumnCollection.Contains(), System.Data.InternalDataCollectionBase.Count, System.Globalization.CultureInfo.CurrentCulture, System.Xml.Dictionary, System.Data.XSDSchema.FromInference, System.Data.XSDSchema.GetPrefix(), System.Data.XSDSchema.HandleColumnExpression(), System.Data.XSDSchema.ParseDataType(), System.Data.XSDSchema.SetExtProperties(), System.Data.XSDSchema.SetProperties(), System.text, System.ToString, System.type, System.value, and System.Data.DataTable.XmlText.
Referenced by System.Data.XSDSchema.HandleComplexType().