Terraria: System.Data.XSDSchema.InstantiateSimpleTable
InstantiateSimpleTable()
DataTable System.Data.XSDSchema.InstantiateSimpleTable (XmlSchemaElement node) inline package
Definition at line 1300 of file XSDSchema.cs.
    {
        string text = XmlConvert.DecodeName(GetInstanceName(node));
        string @namespace = node.QualifiedName.Namespace;
        DataTable dataTable = _ds.Tables.GetTable(text, @namespace);
        if (!FromInference && dataTable != null)
        {
            throw ExceptionBuilder.DuplicateDeclaration(text);
        }
        if (dataTable == null)
        {
            dataTable = new DataTable(text);
            dataTable.Namespace = @namespace;
            dataTable.Namespace = GetStringAttribute(node, "targetNamespace", @namespace);
            if (!FromInference)
            {
                dataTable.MinOccurs = node.MinOccurs;
                dataTable.MaxOccurs = node.MaxOccurs;
            }
            else
            {
                string prefix = GetPrefix(@namespace);
                if (prefix != null)
                {
                    dataTable.Prefix = prefix;
                }
            }
            SetProperties(dataTable, node.UnhandledAttributes);
            SetExtProperties(dataTable, node.UnhandledAttributes);
        }
        XmlSchemaComplexType xmlSchemaComplexType = node.SchemaType as XmlSchemaComplexType;
        bool flag = node.ElementSchemaType.BaseXmlSchemaType != null || (xmlSchemaComplexType != null && xmlSchemaComplexType.ContentModel is XmlSchemaSimpleContent);
        if (!FromInference || (flag && dataTable.Columns.Count == 0))
        {
            HandleElementColumn(node, dataTable, isBase: false);
            string text2;
            if (FromInference)
            {
                int num = 0;
                text2 = text + "_Text";
                while (dataTable.Columns[text2] != null)
                {
                    text2 += num++;
                }
            }
            else
            {
                text2 = text + "_Column";
            }
            dataTable.Columns[0].ColumnName = text2;
            dataTable.Columns[0].ColumnMapping = MappingType.SimpleContent;
        }
        if (!FromInference || _ds.Tables.GetTable(text, @namespace) == null)
        {
            _ds.Tables.Add(dataTable);
            if (FromInference)
            {
                _tableDictionary.Add(dataTable, new List<DataTable>());
            }
        }
        if (_dsElement != null && _dsElement.Constraints != null)
        {
            foreach (XmlSchemaIdentityConstraint constraint in _dsElement.Constraints)
            {
                if (!(constraint is XmlSchemaKeyref) && GetTableName(constraint) == dataTable.TableName)
                {
                    HandleConstraint(constraint);
                }
            }
        }
        dataTable._fNestedInDataset = false;
        return dataTable;
    }
References System.Data.DataTableCollection.Add(), System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Xml.Schema.XmlSchemaElement.Constraints, System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Xml.XmlConvert.DecodeName(), System.Xml.Dictionary, System.Data.ExceptionBuilder.DuplicateDeclaration(), System.Data.XSDSchema.GetInstanceName(), System.Data.DataTableCollection.GetTable(), System.prefix, System.Data.DataSet.Tables, and System.text.