Terraria: System.Data.XSDSchema.HandleKeyref
HandleKeyref()
void System.Data.XSDSchema.HandleKeyref (XmlSchemaKeyref keyref) inline package
Definition at line 1155 of file XSDSchema.cs.
    {
        string text = XmlConvert.DecodeName(keyref.Refer.Name);
        string defVal = XmlConvert.DecodeName(keyref.Name);
        defVal = GetStringAttribute(keyref, "ConstraintName", defVal);
        string tableName = GetTableName(keyref);
        string msdataAttribute = GetMsdataAttribute(keyref, "TableNamespace");
        DataTable tableSmart = _ds.Tables.GetTableSmart(tableName, msdataAttribute);
        if (tableSmart == null)
        {
            return;
        }
        if (text == null || text.Length == 0)
        {
            throw ExceptionBuilder.MissingRefer(defVal);
        }
        ConstraintTable constraintTable = (ConstraintTable)_constraintNodes[text];
        if (constraintTable == null)
        {
            throw ExceptionBuilder.InvalidKey(defVal);
        }
        DataColumn[] array = BuildKey(constraintTable.constraint, constraintTable.table);
        DataColumn[] array2 = BuildKey(keyref, tableSmart);
        ForeignKeyConstraint foreignKeyConstraint = null;
        if (GetBooleanAttribute(keyref, "ConstraintOnly", defVal: false))
        {
            int num = array2[0].Table.Constraints.InternalIndexOf(defVal);
            if (num > -1 && array2[0].Table.Constraints[num].ConstraintName != defVal)
            {
                num = -1;
            }
            if (num < 0)
            {
                foreignKeyConstraint = new ForeignKeyConstraint(defVal, array, array2);
                array2[0].Table.Constraints.Add(foreignKeyConstraint);
            }
        }
        else
        {
            string text2 = XmlConvert.DecodeName(GetStringAttribute(keyref, "RelationName", keyref.Name));
            if (text2 == null || text2.Length == 0)
            {
                text2 = defVal;
            }
            int num2 = array2[0].Table.DataSet.Relations.InternalIndexOf(text2);
            if (num2 > -1 && array2[0].Table.DataSet.Relations[num2].RelationName != text2)
            {
                num2 = -1;
            }
            DataRelation dataRelation = null;
            if (num2 < 0)
            {
                dataRelation = new DataRelation(text2, array, array2);
                SetExtProperties(dataRelation, keyref.UnhandledAttributes);
                array[0].Table.DataSet.Relations.Add(dataRelation);
                if (FromInference && dataRelation.Nested && _tableDictionary.ContainsKey(dataRelation.ParentTable))
                {
                    _tableDictionary[dataRelation.ParentTable].Add(dataRelation.ChildTable);
                }
                foreignKeyConstraint = dataRelation.ChildKeyConstraint;
                foreignKeyConstraint.ConstraintName = defVal;
            }
            else
            {
                dataRelation = array2[0].Table.DataSet.Relations[num2];
            }
            if (GetBooleanAttribute(keyref, "IsNested", defVal: false))
            {
                dataRelation.Nested = true;
            }
        }
        string msdataAttribute2 = GetMsdataAttribute(keyref, "AcceptRejectRule");
        string msdataAttribute3 = GetMsdataAttribute(keyref, "UpdateRule");
        string msdataAttribute4 = GetMsdataAttribute(keyref, "DeleteRule");
        if (foreignKeyConstraint != null)
        {
            if (msdataAttribute2 != null)
            {
                foreignKeyConstraint.AcceptRejectRule = TranslateAcceptRejectRule(msdataAttribute2);
            }
            if (msdataAttribute3 != null)
            {
                foreignKeyConstraint.UpdateRule = TranslateRule(msdataAttribute3);
            }
            if (msdataAttribute4 != null)
            {
                foreignKeyConstraint.DeleteRule = TranslateRule(msdataAttribute4);
            }
            SetExtProperties(foreignKeyConstraint, keyref.UnhandledAttributes);
        }
    }
References System.Data.XSDSchema._constraintNodes, System.Data.XSDSchema._ds, System.Data.XSDSchema._tableDictionary, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.array, System.Data.XSDSchema.BuildKey(), System.Collections.Generic.Dictionary< TKey, TValue >.ContainsKey(), System.Xml.XmlConvert.DecodeName(), System.Xml.Dictionary, System.Data.XSDSchema.FromInference, System.Data.XSDSchema.GetBooleanAttribute(), System.Data.XSDSchema.GetMsdataAttribute(), System.Data.XSDSchema.GetStringAttribute(), System.Data.XSDSchema.GetTableName(), System.Data.DataTableCollection.GetTableSmart(), System.Data.ExceptionBuilder.InvalidKey(), System.Data.ExceptionBuilder.MissingRefer(), System.Data.XSDSchema.SetExtProperties(), System.Data.DataSet.Tables, System.text, System.Data.XSDSchema.TranslateAcceptRejectRule(), and System.Data.XSDSchema.TranslateRule().