Terraria: System.Data.XSDSchema.FindTypeNode
FindTypeNode()
XmlSchemaAnnotated System.Data.XSDSchema.FindTypeNode (XmlSchemaAnnotated node) inline package
Definition at line 1607 of file XSDSchema.cs.
    {
        XmlSchemaAttribute xmlSchemaAttribute = node as XmlSchemaAttribute;
        XmlSchemaElement xmlSchemaElement = node as XmlSchemaElement;
        bool flag = false;
        if (xmlSchemaAttribute != null)
        {
            flag = true;
        }
        string text = (flag ? xmlSchemaAttribute.SchemaTypeName.Name : xmlSchemaElement.SchemaTypeName.Name);
        string text2 = (flag ? xmlSchemaAttribute.SchemaTypeName.Namespace : xmlSchemaElement.SchemaTypeName.Namespace);
        if (text2 == "http://www.w3.org/2001/XMLSchema")
        {
            return null;
        }
        if (text == null || text.Length == 0)
        {
            text = (flag ? xmlSchemaAttribute.RefName.Name : xmlSchemaElement.RefName.Name);
            if (text == null || text.Length == 0)
            {
                return flag ? xmlSchemaAttribute.SchemaType : xmlSchemaElement.SchemaType;
            }
            return flag ? FindTypeNode((XmlSchemaAnnotated)_attributes[xmlSchemaAttribute.RefName]) : FindTypeNode((XmlSchemaAnnotated)_elementsTable[xmlSchemaElement.RefName]);
        }
        return (XmlSchemaAnnotated)_schemaTypes[flag ? ((XmlSchemaAttribute)node).SchemaTypeName : ((XmlSchemaElement)node).SchemaTypeName];
    }
References System.Data.XSDSchema._attributes, System.Data.XSDSchema._elementsTable, System.Data.XSDSchema._schemaTypes, System.Xml.Dictionary, System.Data.XSDSchema.FindTypeNode(), and System.text.
Referenced by System.Data.XSDSchema.FindTypeNode(), System.Data.XSDSchema.HandleAttributeColumn(), System.Data.XSDSchema.HandleElementColumn(), and System.Data.XSDSchema.LoadSchema().