Terraria: System.Data.XSDSchema.GetPrefix
GetPrefix()
string System.Data.XSDSchema.GetPrefix (string ns) inline private
Definition at line 2345 of file XSDSchema.cs.
    {
        if (ns == null)
        {
            return null;
        }
        foreach (XmlSchema item in _schemaSet.Schemas())
        {
            XmlQualifiedName[] array = item.Namespaces.ToArray();
            for (int i = 0; i < array.Length; i++)
            {
                if (array[i].Namespace == ns)
                {
                    return array[i].Name;
                }
            }
        }
        return null;
    }
References System.array, System.item, System.Xml.Schema.Namespace, and System.Xml.Schema.XmlSchemaSet.Schemas().
Referenced by System.Data.XSDSchema.HandleAttributeColumn(), System.Data.XSDSchema.HandleElementColumn(), System.Data.XSDSchema.HandleSimpleContentColumn(), and System.Data.XSDSchema.HandleSimpleTypeSimpleContentColumn().