Terraria: System.Data.XSDSchema.HandleParticle
HandleParticle()
void System.Data.XSDSchema.HandleParticle (XmlSchemaParticle pt, DataTable table, ArrayList tableChildren, bool isBase) inline package
Definition at line 831 of file XSDSchema.cs.
    {
        XmlSchemaObjectCollection particleItems = GetParticleItems(pt);
        if (particleItems == null)
        {
            return;
        }
        foreach (XmlSchemaAnnotated item in particleItems)
        {
            if (item is XmlSchemaElement xmlSchemaElement)
            {
                if (FromInference && pt is XmlSchemaChoice && pt.MaxOccurs > 1m && xmlSchemaElement.SchemaType is XmlSchemaComplexType)
                {
                    xmlSchemaElement.MaxOccurs = pt.MaxOccurs;
                }
                DataTable dataTable = null;
                if ((xmlSchemaElement.Name == null && xmlSchemaElement.RefName.Name == table.EncodedTableName && xmlSchemaElement.RefName.Namespace == table.Namespace) || (IsTable(xmlSchemaElement) && xmlSchemaElement.Name == table.TableName))
                {
                    dataTable = ((!FromInference) ? table : HandleTable(xmlSchemaElement));
                }
                else
                {
                    dataTable = HandleTable(xmlSchemaElement);
                    if (dataTable == null && FromInference && xmlSchemaElement.Name == table.TableName)
                    {
                        dataTable = table;
                    }
                }
                if (dataTable == null)
                {
                    if (!FromInference || xmlSchemaElement.Name != table.TableName)
                    {
                        HandleElementColumn(xmlSchemaElement, table, isBase);
                    }
                    continue;
                }
                DataRelation dataRelation = null;
                if (xmlSchemaElement.Annotation != null)
                {
                    HandleRelations(xmlSchemaElement.Annotation, fNested: true);
                }
                DataRelationCollection childRelations = table.ChildRelations;
                for (int i = 0; i < childRelations.Count; i++)
                {
                    if (childRelations[i].Nested && dataTable == childRelations[i].ChildTable)
                    {
                        dataRelation = childRelations[i];
                    }
                }
                if (dataRelation != null)
                {
                    continue;
                }
                tableChildren.Add(dataTable);
                if (!FromInference || table.UKColumnPositionForInference != -1)
                {
                    continue;
                }
                int num = -1;
                foreach (DataColumn column in table.Columns)
                {
                    if (column.ColumnMapping == MappingType.Element)
                    {
                        num++;
                    }
                }
                table.UKColumnPositionForInference = num + 1;
            }
            else
            {
                HandleParticle((XmlSchemaParticle)item, table, tableChildren, isBase);
            }
        }
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Data.DataTable.ChildRelations, System.Data.DataTable.Columns, System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Xml.Dictionary, System.Data.DataTable.EncodedTableName, System.Data.XSDSchema.FromInference, System.Data.XSDSchema.GetParticleItems(), System.Data.XSDSchema.HandleElementColumn(), System.Data.XSDSchema.HandleParticle(), System.Data.XSDSchema.HandleRelations(), System.Data.XSDSchema.HandleTable(), System.Data.XSDSchema.IsTable(), System.item, System.Data.DataTable.Namespace, System.Data.DataTable.TableName, and System.Data.DataTable.UKColumnPositionForInference.
Referenced by System.Data.XSDSchema.HandleComplexType(), and System.Data.XSDSchema.HandleParticle().