Terraria: System.Data.XSDSchema.GetInstanceName
GetInstanceName()
string System.Data.XSDSchema.GetInstanceName (XmlSchemaAnnotated node) inline package
Definition at line 1374 of file XSDSchema.cs.
    {
        string result = null;
        if (node is XmlSchemaElement)
        {
            XmlSchemaElement xmlSchemaElement = (XmlSchemaElement)node;
            result = ((xmlSchemaElement.Name != null) ? xmlSchemaElement.Name : xmlSchemaElement.RefName.Name);
        }
        else if (node is XmlSchemaAttribute)
        {
            XmlSchemaAttribute xmlSchemaAttribute = (XmlSchemaAttribute)node;
            result = ((xmlSchemaAttribute.Name != null) ? xmlSchemaAttribute.Name : xmlSchemaAttribute.RefName.Name);
        }
        return result;
    }
References System.Xml.Dictionary.
Referenced by System.Data.XSDSchema.HandleAttributeColumn(), System.Data.XSDSchema.HandleElementColumn(), System.Data.XSDSchema.HandleRefTableProperties(), System.Data.XSDSchema.InstantiateSimpleTable(), System.Data.XSDSchema.InstantiateTable(), and System.Data.XSDSchema.LoadSchema().