Terraria: System.Data.XSDSchema.GetBooleanAttribute
GetBooleanAttribute() [2/2]
bool System.Data.XSDSchema.GetBooleanAttribute (XmlSchemaAnnotated element, string attrName, bool defVal) inline package
Definition at line 1102 of file XSDSchema.cs.
    {
        string msdataAttribute = GetMsdataAttribute(element, attrName);
        if (msdataAttribute == null || msdataAttribute.Length == 0)
        {
            return defVal;
        }
        switch (msdataAttribute)
        {
        case "true":
        case "1":
            return true;
        case "false":
        case "0":
            return false;
        default:
            throw ExceptionBuilder.InvalidAttributeValue(attrName, msdataAttribute);
        }
    }
References System.Xml.Dictionary, System.Data.XSDSchema.GetMsdataAttribute(), and System.Data.ExceptionBuilder.InvalidAttributeValue().
Referenced by System.Data.XSDSchema.DatasetElementCount(), System.Data.XSDSchema.FindDatasetElement(), System.Data.XSDSchema.HandleAttributeColumn(), System.Data.XSDSchema.HandleConstraint(), and System.Data.XSDSchema.HandleKeyref().