Terraria: System.Data.XSDSchema.IsTable
IsTable()
bool System.Data.XSDSchema.IsTable (XmlSchemaElement node) inline package
Definition at line 2415 of file XSDSchema.cs.
    {
        if (node.MaxOccurs == 0m)
        {
            return false;
        }
        XmlAttribute[] unhandledAttributes = node.UnhandledAttributes;
        if (unhandledAttributes != null)
        {
            foreach (XmlAttribute xmlAttribute in unhandledAttributes)
            {
                if (xmlAttribute.LocalName == "DataType" && xmlAttribute.Prefix == "msdata" && xmlAttribute.NamespaceURI == "urn:schemas-microsoft-com:xml-msdata")
                {
                    return false;
                }
            }
        }
        object obj = FindTypeNode(node);
        if (node.MaxOccurs > 1m && obj == null)
        {
            return true;
        }
        if (obj == null || !(obj is XmlSchemaComplexType))
        {
            return false;
        }
        XmlSchemaComplexType xmlSchemaComplexType = (XmlSchemaComplexType)obj;
        if (xmlSchemaComplexType.IsAbstract)
        {
            throw ExceptionBuilder.CannotInstantiateAbstract(node.Name);
        }
        return true;
    }
References System.Data.ExceptionBuilder.CannotInstantiateAbstract(), and System.obj.
Referenced by System.Data.XSDSchema.HandleParticle(), and System.Data.XSDSchema.IsDatasetParticle().