Terraria: System.Data.XSDSchema.HandleColumnExpression
HandleColumnExpression()
void System.Data.XSDSchema.HandleColumnExpression (object instance, XmlAttribute[] attrs) inline private
Definition at line 321 of file XSDSchema.cs.
    {
        if (attrs == null || !(instance is DataColumn dataColumn))
        {
            return;
        }
        for (int i = 0; i < attrs.Length; i++)
        {
            if (attrs[i].NamespaceURI == "urn:schemas-microsoft-com:xml-msdata" && attrs[i].LocalName == "Expression")
            {
                if (_expressions == null)
                {
                    _expressions = new Hashtable();
                }
                _expressions[dataColumn] = attrs[i].Value;
                _columnExpressions.Add(dataColumn);
                break;
            }
        }
    }
References System.Data.XSDSchema._columnExpressions, System.Data.XSDSchema._expressions, System.Collections.ArrayList.Add(), and System.Xml.Dictionary.
Referenced by System.Data.XSDSchema.HandleAttributeColumn(), System.Data.XSDSchema.HandleElementColumn(), System.Data.XSDSchema.HandleSimpleContentColumn(), and System.Data.XSDSchema.HandleSimpleTypeSimpleContentColumn().