Terraria: System.Data.XSDSchema.HandleSimpleTypeSimpleContentColumn
HandleSimpleTypeSimpleContentColumn()
void System.Data.XSDSchema.HandleSimpleTypeSimpleContentColumn (XmlSchemaSimpleType typeNode, string strType, DataTable table, bool isBase, XmlAttribute[] attrs, bool isNillable) inline package
Definition at line 1635 of file XSDSchema.cs.
    {
        if (FromInference && table.XmlText != null)
        {
            return;
        }
        Type type = null;
        SimpleType simpleType = null;
        if (typeNode.QualifiedName.Name != null && typeNode.QualifiedName.Name.Length != 0 && typeNode.QualifiedName.Namespace != "http://www.w3.org/2001/XMLSchema")
        {
            simpleType = new SimpleType(typeNode);
            strType = typeNode.QualifiedName.ToString();
            type = ParseDataType(typeNode.QualifiedName.ToString());
        }
        else if (typeNode.BaseXmlSchemaType is XmlSchemaSimpleType xmlSchemaSimpleType && xmlSchemaSimpleType.QualifiedName.Namespace != "http://www.w3.org/2001/XMLSchema")
        {
            simpleType = new SimpleType(typeNode);
            SimpleType simpleType2 = simpleType;
            while (simpleType2.BaseSimpleType != null)
            {
                simpleType2 = simpleType2.BaseSimpleType;
            }
            type = ParseDataType(simpleType2.BaseType);
            strType = simpleType.Name;
        }
        else
        {
            type = ParseDataType(strType);
        }
        string text;
        if (FromInference)
        {
            int num = 0;
            text = table.TableName + "_Text";
            while (table.Columns[text] != null)
            {
                text += num++;
            }
        }
        else
        {
            text = table.TableName + "_text";
        }
        string text2 = text;
        bool flag = true;
        DataColumn dataColumn;
        if (!isBase && table.Columns.Contains(text2, caseSensitive: true))
        {
            dataColumn = table.Columns[text2];
            flag = false;
        }
        else
        {
            dataColumn = new DataColumn(text2, type, null, MappingType.SimpleContent);
        }
        SetProperties(dataColumn, attrs);
        HandleColumnExpression(dataColumn, attrs);
        SetExtProperties(dataColumn, attrs);
        string value = (-1).ToString(CultureInfo.CurrentCulture);
        string text3 = null;
        dataColumn.AllowDBNull = isNillable;
        if (attrs != null)
        {
            for (int i = 0; i < attrs.Length; i++)
            {
                if (attrs[i].LocalName == "AllowDBNull" && attrs[i].NamespaceURI == "urn:schemas-microsoft-com:xml-msdata" && attrs[i].Value == "false")
                {
                    dataColumn.AllowDBNull = false;
                }
                if (attrs[i].LocalName == "Ordinal" && attrs[i].NamespaceURI == "urn:schemas-microsoft-com:xml-msdata")
                {
                    value = attrs[i].Value;
                }
                if (attrs[i].LocalName == "DefaultValue" && attrs[i].NamespaceURI == "urn:schemas-microsoft-com:xml-msdata")
                {
                    text3 = attrs[i].Value;
                }
            }
        }
        int num2 = (int)Convert.ChangeType(value, typeof(int), null);
        if (dataColumn.Expression != null && dataColumn.Expression.Length != 0)
        {
            _columnExpressions.Add(dataColumn);
        }
        if (simpleType != null && simpleType.Name != null && simpleType.Name.Length > 0)
        {
            if (GetMsdataAttribute(typeNode, "targetNamespace") != null)
            {
                dataColumn.XmlDataType = simpleType.SimpleTypeQualifiedName;
            }
        }
        else
        {
            dataColumn.XmlDataType = strType;
        }
        dataColumn.SimpleType = simpleType;
        if (flag)
        {
            if (FromInference)
            {
                dataColumn.Prefix = GetPrefix(table.Namespace);
                dataColumn.AllowDBNull = true;
            }
            if (num2 > -1 && num2 < table.Columns.Count)
            {
                table.Columns.AddAt(num2, dataColumn);
            }
            else
            {
                table.Columns.Add(dataColumn);
            }
        }
        if (text3 != null)
        {
            try
            {
                dataColumn.DefaultValue = dataColumn.ConvertXmlToObject(text3);
            }
            catch (FormatException)
            {
                throw ExceptionBuilder.CannotConvert(text3, type.FullName);
            }
        }
    }
References System.Data.XSDSchema._columnExpressions, System.Data.DataColumnCollection.Add(), System.Collections.ArrayList.Add(), System.Data.DataColumnCollection.AddAt(), System.Data.ExceptionBuilder.CannotConvert(), System.Convert.ChangeType(), System.Data.DataTable.Columns, System.Data.DataColumnCollection.Contains(), System.Data.InternalDataCollectionBase.Count, System.Globalization.CultureInfo.CurrentCulture, System.Xml.Dictionary, System.Data.XSDSchema.FromInference, System.Data.XSDSchema.GetMsdataAttribute(), System.Data.XSDSchema.GetPrefix(), System.Data.XSDSchema.HandleColumnExpression(), System.Data.DataTable.Namespace, System.Data.XSDSchema.ParseDataType(), System.Data.XSDSchema.SetExtProperties(), System.Data.XSDSchema.SetProperties(), System.text, System.ToString, System.type, System.value, and System.Data.DataTable.XmlText.
Referenced by System.Data.XSDSchema.HandleComplexType().