Terraria: System.Data.XSDSchema.HandleElementColumn
HandleElementColumn()
void System.Data.XSDSchema.HandleElementColumn (XmlSchemaElement elem, DataTable table, bool isBase) inline package
Definition at line 2008 of file XSDSchema.cs.
    {
        Type type = null;
        XmlSchemaElement xmlSchemaElement = ((elem.Name != null) ? elem : ((XmlSchemaElement)_elementsTable[elem.RefName]));
        if (xmlSchemaElement == null)
        {
            return;
        }
        XmlSchemaAnnotated xmlSchemaAnnotated = FindTypeNode(xmlSchemaElement);
        string text = null;
        SimpleType simpleType = null;
        if (xmlSchemaAnnotated == null)
        {
            text = xmlSchemaElement.SchemaTypeName.Name;
            if (string.IsNullOrEmpty(text))
            {
                text = string.Empty;
                type = typeof(string);
            }
            else
            {
                type = ParseDataType(xmlSchemaElement.SchemaTypeName.Name);
            }
        }
        else if (xmlSchemaAnnotated is XmlSchemaSimpleType)
        {
            XmlSchemaSimpleType node = xmlSchemaAnnotated as XmlSchemaSimpleType;
            simpleType = new SimpleType(node);
            if (((XmlSchemaSimpleType)xmlSchemaAnnotated).Name != null && ((XmlSchemaSimpleType)xmlSchemaAnnotated).Name.Length != 0 && ((XmlSchemaSimpleType)xmlSchemaAnnotated).QualifiedName.Namespace != "http://www.w3.org/2001/XMLSchema")
            {
                text = ((XmlSchemaSimpleType)xmlSchemaAnnotated).QualifiedName.ToString();
                type = ParseDataType(text);
            }
            else
            {
                for (node = ((simpleType.XmlBaseType != null && simpleType.XmlBaseType.Namespace != "http://www.w3.org/2001/XMLSchema") ? (_schemaTypes[simpleType.XmlBaseType] as XmlSchemaSimpleType) : null); node != null; node = ((simpleType.XmlBaseType != null && simpleType.XmlBaseType.Namespace != "http://www.w3.org/2001/XMLSchema") ? (_schemaTypes[simpleType.XmlBaseType] as XmlSchemaSimpleType) : null))
                {
                    simpleType.LoadTypeValues(node);
                }
                type = ParseDataType(simpleType.BaseType);
                text = simpleType.Name;
                if (simpleType.Length == 1 && type == typeof(string))
                {
                    type = typeof(char);
                }
            }
        }
        else if (xmlSchemaAnnotated is XmlSchemaElement)
        {
            text = ((XmlSchemaElement)xmlSchemaAnnotated).SchemaTypeName.Name;
            type = ParseDataType(text);
        }
        else
        {
            if (!(xmlSchemaAnnotated is XmlSchemaComplexType))
            {
                if (xmlSchemaAnnotated.Id == null)
                {
                    throw ExceptionBuilder.DatatypeNotDefined();
                }
                throw ExceptionBuilder.UndefinedDatatype(xmlSchemaAnnotated.Id);
            }
            if (string.IsNullOrEmpty(GetMsdataAttribute(elem, "DataType")))
            {
                throw ExceptionBuilder.DatatypeNotDefined();
            }
            type = typeof(object);
        }
        string text2 = XmlConvert.DecodeName(GetInstanceName(xmlSchemaElement));
        bool flag = true;
        DataColumn dataColumn;
        if ((!isBase || FromInference) && table.Columns.Contains(text2, caseSensitive: true))
        {
            dataColumn = table.Columns[text2];
            flag = false;
            if (FromInference)
            {
                if (dataColumn.ColumnMapping != MappingType.Element)
                {
                    throw ExceptionBuilder.ColumnTypeConflict(dataColumn.ColumnName);
                }
                if ((string.IsNullOrEmpty(elem.QualifiedName.Namespace) && string.IsNullOrEmpty(dataColumn._columnUri)) || string.Equals(elem.QualifiedName.Namespace, dataColumn.Namespace, StringComparison.Ordinal))
                {
                    return;
                }
                dataColumn = new DataColumn(text2, type, null, MappingType.Element);
                flag = true;
            }
        }
        else
        {
            dataColumn = new DataColumn(text2, type, null, MappingType.Element);
        }
        SetProperties(dataColumn, xmlSchemaElement.UnhandledAttributes);
        HandleColumnExpression(dataColumn, xmlSchemaElement.UnhandledAttributes);
        SetExtProperties(dataColumn, xmlSchemaElement.UnhandledAttributes);
        if (!string.IsNullOrEmpty(dataColumn.Expression))
        {
            _columnExpressions.Add(dataColumn);
        }
        if (simpleType != null && simpleType.Name != null && simpleType.Name.Length > 0)
        {
            if (GetMsdataAttribute(xmlSchemaAnnotated, "targetNamespace") != null)
            {
                dataColumn.XmlDataType = simpleType.SimpleTypeQualifiedName;
            }
        }
        else
        {
            dataColumn.XmlDataType = text;
        }
        dataColumn.SimpleType = simpleType;
        dataColumn.AllowDBNull = FromInference || elem.MinOccurs == 0m || elem.IsNillable;
        if (!elem.RefName.IsEmpty || elem.QualifiedName.Namespace != table.Namespace)
        {
            dataColumn.Namespace = elem.QualifiedName.Namespace;
            dataColumn.Namespace = GetStringAttribute(xmlSchemaElement, "targetNamespace", dataColumn.Namespace);
        }
        else if (elem.Form == XmlSchemaForm.Unqualified)
        {
            dataColumn.Namespace = string.Empty;
        }
        else if (elem.Form == XmlSchemaForm.None)
        {
            XmlSchemaObject parent = elem.Parent;
            while (parent.Parent != null)
            {
                parent = parent.Parent;
            }
            if (((XmlSchema)parent).ElementFormDefault == XmlSchemaForm.Unqualified)
            {
                dataColumn.Namespace = string.Empty;
            }
        }
        else
        {
            dataColumn.Namespace = elem.QualifiedName.Namespace;
            dataColumn.Namespace = GetStringAttribute(xmlSchemaElement, "targetNamespace", dataColumn.Namespace);
        }
        string stringAttribute = GetStringAttribute(elem, "Ordinal", (-1).ToString(CultureInfo.CurrentCulture));
        int num = (int)Convert.ChangeType(stringAttribute, typeof(int), null);
        if (flag)
        {
            if (num > -1 && num < table.Columns.Count)
            {
                table.Columns.AddAt(num, dataColumn);
            }
            else
            {
                table.Columns.Add(dataColumn);
            }
        }
        if (dataColumn.Namespace == table.Namespace)
        {
            dataColumn._columnUri = null;
        }
        if (FromInference)
        {
            dataColumn.Prefix = GetPrefix(dataColumn.Namespace);
        }
        string defaultValue = xmlSchemaElement.DefaultValue;
        if (defaultValue == null)
        {
            return;
        }
        try
        {
            dataColumn.DefaultValue = dataColumn.ConvertXmlToObject(defaultValue);
        }
        catch (FormatException)
        {
            throw ExceptionBuilder.CannotConvert(defaultValue, type.FullName);
        }
    }
References System.Data.XSDSchema._columnExpressions, System.Data.XSDSchema._elementsTable, System.Data.XSDSchema._schemaTypes, System.Data.DataColumnCollection.Add(), System.Collections.ArrayList.Add(), System.Data.DataColumnCollection.AddAt(), System.Data.ExceptionBuilder.CannotConvert(), System.Convert.ChangeType(), System.Data.DataTable.Columns, System.Data.ExceptionBuilder.ColumnTypeConflict(), System.Data.DataColumnCollection.Contains(), System.Data.InternalDataCollectionBase.Count, System.Globalization.CultureInfo.CurrentCulture, System.Data.ExceptionBuilder.DatatypeNotDefined(), System.Xml.XmlConvert.DecodeName(), System.Xml.Dictionary, System.Data.XSDSchema.FindTypeNode(), System.Data.XSDSchema.FromInference, System.Data.XSDSchema.GetInstanceName(), System.Data.XSDSchema.GetMsdataAttribute(), System.Data.XSDSchema.GetPrefix(), System.Data.XSDSchema.GetStringAttribute(), System.Data.XSDSchema.HandleColumnExpression(), System.Data.Name, System.Data.DataTable.Namespace, System.Xml.Schema.XmlSchemaObject.Parent, System.Data.XSDSchema.ParseDataType(), System.Data.XSDSchema.SetExtProperties(), System.Data.XSDSchema.SetProperties(), System.text, System.ToString, System.type, and System.Data.ExceptionBuilder.UndefinedDatatype().
Referenced by System.Data.XSDSchema.HandleParticle().