Terraria: System.Data.XSDSchema.HandleRelation
HandleRelation()
void System.Data.XSDSchema.HandleRelation (XmlElement node, bool fNested) inline package
Definition at line 387 of file XSDSchema.cs.
    {
        bool createConstraints = false;
        DataRelationCollection relations = _ds.Relations;
        string text = XmlConvert.DecodeName(node.GetAttribute("name"));
        for (int i = 0; i < relations.Count; i++)
        {
            if (string.Equals(relations[i].RelationName, text, StringComparison.Ordinal))
            {
                return;
            }
        }
        string attribute = node.GetAttribute("parent", "urn:schemas-microsoft-com:xml-msdata");
        if (attribute == null || attribute.Length == 0)
        {
            throw ExceptionBuilder.RelationParentNameMissing(text);
        }
        attribute = XmlConvert.DecodeName(attribute);
        string attribute2 = node.GetAttribute("child", "urn:schemas-microsoft-com:xml-msdata");
        if (attribute2 == null || attribute2.Length == 0)
        {
            throw ExceptionBuilder.RelationChildNameMissing(text);
        }
        attribute2 = XmlConvert.DecodeName(attribute2);
        string attribute3 = node.GetAttribute("parentkey", "urn:schemas-microsoft-com:xml-msdata");
        if (attribute3 == null || attribute3.Length == 0)
        {
            throw ExceptionBuilder.RelationTableKeyMissing(text);
        }
        string[] array = attribute3.TrimEnd(null).Split(' ', '+');
        attribute3 = node.GetAttribute("childkey", "urn:schemas-microsoft-com:xml-msdata");
        if (attribute3 == null || attribute3.Length == 0)
        {
            throw ExceptionBuilder.RelationChildKeyMissing(text);
        }
        string[] array2 = attribute3.TrimEnd(null).Split(' ', '+');
        int num = array.Length;
        if (num != array2.Length)
        {
            throw ExceptionBuilder.MismatchKeyLength();
        }
        DataColumn[] array3 = new DataColumn[num];
        DataColumn[] array4 = new DataColumn[num];
        string attribute4 = node.GetAttribute("ParentTableNamespace", "urn:schemas-microsoft-com:xml-msdata");
        string attribute5 = node.GetAttribute("ChildTableNamespace", "urn:schemas-microsoft-com:xml-msdata");
        DataTable tableSmart = _ds.Tables.GetTableSmart(attribute, attribute4);
        if (tableSmart == null)
        {
            throw ExceptionBuilder.ElementTypeNotFound(attribute);
        }
        DataTable tableSmart2 = _ds.Tables.GetTableSmart(attribute2, attribute5);
        if (tableSmart2 == null)
        {
            throw ExceptionBuilder.ElementTypeNotFound(attribute2);
        }
        for (int j = 0; j < num; j++)
        {
            array3[j] = tableSmart.Columns[XmlConvert.DecodeName(array[j])];
            if (array3[j] == null)
            {
                throw ExceptionBuilder.ElementTypeNotFound(array[j]);
            }
            array4[j] = tableSmart2.Columns[XmlConvert.DecodeName(array2[j])];
            if (array4[j] == null)
            {
                throw ExceptionBuilder.ElementTypeNotFound(array2[j]);
            }
        }
        DataRelation dataRelation = new DataRelation(text, array3, array4, createConstraints);
        dataRelation.Nested = fNested;
        SetExtProperties(dataRelation, node.Attributes);
        _ds.Relations.Add(dataRelation);
        if (FromInference && dataRelation.Nested)
        {
            _tableDictionary[dataRelation.ParentTable].Add(dataRelation.ChildTable);
        }
    }
References System.Data.XSDSchema._ds, System.Data.XSDSchema._tableDictionary, System.Data.DataRelationCollection.Add(), System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.array, System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Xml.XmlConvert.DecodeName(), System.Xml.Dictionary, System.Data.ExceptionBuilder.ElementTypeNotFound(), System.Data.XSDSchema.FromInference, System.Data.DataTableCollection.GetTableSmart(), System.Data.ExceptionBuilder.MismatchKeyLength(), System.Data.ExceptionBuilder.RelationChildKeyMissing(), System.Data.ExceptionBuilder.RelationChildNameMissing(), System.Data.ExceptionBuilder.RelationParentNameMissing(), System.Data.DataSet.Relations, System.Data.ExceptionBuilder.RelationTableKeyMissing(), System.Data.XSDSchema.SetExtProperties(), System.Data.DataSet.Tables, and System.text.
Referenced by System.Data.XSDSchema.HandleRelations().