Terraria: System.Data.XSDSchema.HandleDataSet
HandleDataSet()
void System.Data.XSDSchema.HandleDataSet (XmlSchemaElement node, bool isNewDataSet) inline package
Definition at line 2184 of file XSDSchema.cs.
    {
        string text = node.Name;
        string @namespace = node.QualifiedName.Namespace;
        List<DataTable> list = new List<DataTable>();
        string msdataAttribute = GetMsdataAttribute(node, "Locale");
        if (msdataAttribute != null)
        {
            if (msdataAttribute.Length != 0)
            {
                _ds.Locale = new CultureInfo(msdataAttribute);
            }
            else
            {
                _ds.Locale = CultureInfo.InvariantCulture;
            }
        }
        else if (GetBooleanAttribute(node, "UseCurrentLocale", defVal: false))
        {
            _ds.SetLocaleValue(CultureInfo.CurrentCulture, userSet: false);
        }
        else
        {
            _ds.SetLocaleValue(new CultureInfo(1033), userSet: false);
        }
        msdataAttribute = GetMsdataAttribute(node, "DataSetName");
        if (msdataAttribute != null && msdataAttribute.Length != 0)
        {
            text = msdataAttribute;
        }
        msdataAttribute = GetMsdataAttribute(node, "DataSetNamespace");
        if (msdataAttribute != null && msdataAttribute.Length != 0)
        {
            @namespace = msdataAttribute;
        }
        SetProperties(_ds, node.UnhandledAttributes);
        SetExtProperties(_ds, node.UnhandledAttributes);
        if (text != null && text.Length != 0)
        {
            _ds.DataSetName = XmlConvert.DecodeName(text);
        }
        _ds.Namespace = @namespace;
        if (FromInference)
        {
            _ds.Prefix = GetPrefix(_ds.Namespace);
        }
        XmlSchemaComplexType xmlSchemaComplexType = (XmlSchemaComplexType)FindTypeNode(node);
        if (xmlSchemaComplexType.Particle != null)
        {
            XmlSchemaObjectCollection particleItems = GetParticleItems(xmlSchemaComplexType.Particle);
            if (particleItems == null)
            {
                return;
            }
            foreach (XmlSchemaAnnotated item in particleItems)
            {
                if (item is XmlSchemaElement)
                {
                    if (((XmlSchemaElement)item).RefName.Name.Length != 0)
                    {
                        if (!FromInference)
{
                            continue;
                        }
                        DataTable table = _ds.Tables.GetTable(XmlConvert.DecodeName(GetInstanceName((XmlSchemaElement)item)), node.QualifiedName.Namespace);
                        if (table != null)
{
                            list.Add(table);
                        }
                        bool flag = false;
                        if (node.ElementSchemaType != null || !(((XmlSchemaElement)item).SchemaType is XmlSchemaComplexType))
{
                            flag = true;
                        }
                        if (((XmlSchemaElement)item).MaxOccurs != 1m && !flag)
{
                            continue;
                        }
                    }
                    DataTable dataTable = HandleTable((XmlSchemaElement)item);
                    if (dataTable != null)
                    {
                        dataTable._fNestedInDataset = true;
                    }
                    if (FromInference)
                    {
                        list.Add(dataTable);
                    }
                }
                else
                {
                    if (!(item is XmlSchemaChoice))
                    {
                        continue;
                    }
                    XmlSchemaObjectCollection items = ((XmlSchemaChoice)item).Items;
                    if (items == null)
                    {
                        continue;
                    }
                    foreach (XmlSchemaAnnotated item2 in items)
                    {
                        if (!(item2 is XmlSchemaElement))
{
                            continue;
                        }
                        if (((XmlSchemaParticle)item).MaxOccurs > 1m && ((XmlSchemaElement)item2).SchemaType is XmlSchemaComplexType)
{
                            ((XmlSchemaElement)item2).MaxOccurs = ((XmlSchemaParticle)item).MaxOccurs;
                        }
                        if (((XmlSchemaElement)item2).RefName.Name.Length == 0 || FromInference || !(((XmlSchemaElement)item2).MaxOccurs != 1m) || ((XmlSchemaElement)item2).SchemaType is XmlSchemaComplexType)
{
                            DataTable dataTable2 = HandleTable((XmlSchemaElement)item2);
                            if (FromInference)
{
                                list.Add(dataTable2);
                            }
                            if (dataTable2 != null)
{
                                dataTable2._fNestedInDataset = true;
                            }
                        }
                    }
                }
            }
        }
        if (node.Constraints != null)
        {
            foreach (XmlSchemaIdentityConstraint constraint in node.Constraints)
            {
                if (constraint is XmlSchemaKeyref xmlSchemaKeyref && !GetBooleanAttribute(xmlSchemaKeyref, "IsNested", defVal: false))
                {
                    HandleKeyref(xmlSchemaKeyref);
                }
            }
        }
        if (!(FromInference && isNewDataSet))
        {
            return;
        }
        List<DataTable> tableList = new List<DataTable>(_ds.Tables.Count);
        foreach (DataTable item3 in list)
        {
            AddTablesToList(tableList, item3);
        }
        _ds.Tables.ReplaceFromInference(tableList);
    }
References System.Data.InternalDataCollectionBase.Count, System.Globalization.CultureInfo.CurrentCulture, System.Xml.XmlConvert.DecodeName(), System.Xml.Dictionary, System.Data.DataTableCollection.GetTable(), System.Globalization.CultureInfo.InvariantCulture, System.item, System.list, System.Data.DataSet.Namespace, System.Data.DataTableCollection.ReplaceFromInference(), System.Data.DataSet.SetLocaleValue(), System.Data.DataSet.Tables, and System.text.
Referenced by System.Data.XSDSchema.LoadSchema().