Terraria: System.Data.XSDSchema.GetTableName
GetTableName()
string System.Data.XSDSchema.GetTableName (XmlSchemaIdentityConstraint key) inline private
Definition at line 2404 of file XSDSchema.cs.
    {
        string xPath = key.Selector.XPath;
        string text = xPath.Split('/', ':')[^1];
        if (text == null || text.Length == 0)
        {
            throw ExceptionBuilder.InvalidSelector(xPath);
        }
        return XmlConvert.DecodeName(text);
    }
References System.Xml.XmlConvert.DecodeName(), System.Data.ExceptionBuilder.InvalidSelector(), System.key, and System.text.
Referenced by System.Data.XSDSchema.HandleConstraint(), and System.Data.XSDSchema.HandleKeyref().