Terraria: System.Data.XSDSchema.SetProperties
SetProperties() [1/2]
static void System.Data.XSDSchema.SetProperties (object instance, XmlAttribute[] attrs) inline static package
Definition at line 217 of file XSDSchema.cs.
    {
        if (attrs == null)
        {
            return;
        }
        for (int i = 0; i < attrs.Length; i++)
        {
            if (!(attrs[i].NamespaceURI == "urn:schemas-microsoft-com:xml-msdata"))
            {
                continue;
            }
            string localName = attrs[i].LocalName;
            string value = attrs[i].Value;
            switch (localName)
            {
            case "Expression":
                if (instance is DataColumn)
                {
                    continue;
                }
                break;
            case "DefaultValue":
            case "Ordinal":
            case "Locale":
            case "RemotingFormat":
                continue;
            }
            if (localName == "DataType")
            {
                if (instance is DataColumn dataColumn)
                {
                    dataColumn.DataType = DataStorage.GetType(value);
                }
                continue;
            }
            PropertyDescriptor propertyDescriptor = TypeDescriptor.GetProperties(instance)[localName];
            if (propertyDescriptor == null)
            {
                continue;
            }
            Type propertyType = propertyDescriptor.PropertyType;
            TypeConverter converter = XMLSchema.GetConverter(propertyType);
            object value2;
            if (converter.CanConvertFrom(typeof(string)))
            {
                value2 = converter.ConvertFromInvariantString(value);
            }
            else if (propertyType == typeof(Type))
            {
                value2 = Type.GetType(value);
            }
            else
            {
                if (!(propertyType == typeof(CultureInfo)))
                {
                    throw ExceptionBuilder.CannotConvert(value, propertyType.FullName);
                }
                value2 = new CultureInfo(value);
            }
            propertyDescriptor.SetValue(instance, value2);
        }
    }
References System.Data.ExceptionBuilder.CannotConvert(), System.converter, System.Xml.Dictionary, System.Data.XMLSchema.GetConverter(), System.ComponentModel.TypeDescriptor.GetProperties(), System.Type.GetType(), System.Data.Common.DataStorage.GetType(), and System.value.
Referenced by System.Data.XSDSchema.HandleAttributeColumn(), System.Data.XSDSchema.HandleElementColumn(), System.Data.XSDSchema.HandleRefTableProperties(), System.Data.XSDSchema.HandleSimpleContentColumn(), and System.Data.XSDSchema.HandleSimpleTypeSimpleContentColumn().