Terraria: System.Data.XSDSchema.HandleRefTableProperties
HandleRefTableProperties()
void System.Data.XSDSchema.HandleRefTableProperties (ArrayList RefTables, XmlSchemaElement element) inline package
Definition at line 378 of file XSDSchema.cs.
    {
        string instanceName = GetInstanceName(element);
        DataTable table = _ds.Tables.GetTable(XmlConvert.DecodeName(instanceName), element.QualifiedName.Namespace);
        SetProperties(table, element.UnhandledAttributes);
        SetExtProperties(table, element.UnhandledAttributes);
    }
References System.Data.XSDSchema._ds, System.Xml.XmlConvert.DecodeName(), System.Data.XSDSchema.GetInstanceName(), System.Data.DataTableCollection.GetTable(), System.Xml.XmlQualifiedName.Namespace, System.Xml.Schema.XmlSchemaElement.QualifiedName, System.Data.XSDSchema.SetExtProperties(), System.Data.XSDSchema.SetProperties(), System.Data.DataSet.Tables, and System.Xml.Schema.XmlSchemaAnnotated.UnhandledAttributes.
Referenced by System.Data.XSDSchema.LoadSchema().