Terraria: System.Data.XSDSchema.FindDatasetElement
FindDatasetElement()
XmlSchemaElement System.Data.XSDSchema.FindDatasetElement (XmlSchemaObjectCollection elements) inline private
Definition at line 527 of file XSDSchema.cs.
    {
        foreach (XmlSchemaElement element in elements)
        {
            if (GetBooleanAttribute(element, "IsDataSet", defVal: false))
            {
                return element;
            }
        }
        if (elements.Count == 1 || (FromInference && elements.Count > 0))
        {
            XmlSchemaElement xmlSchemaElement2 = (XmlSchemaElement)elements[0];
            if (!GetBooleanAttribute(xmlSchemaElement2, "IsDataSet", defVal: true))
            {
                return null;
            }
            XmlSchemaComplexType xmlSchemaComplexType = xmlSchemaElement2.SchemaType as XmlSchemaComplexType;
            if (xmlSchemaComplexType == null)
            {
                return null;
            }
            while (xmlSchemaComplexType != null)
            {
                if (HasAttributes(xmlSchemaComplexType.Attributes))
                {
                    return null;
                }
                if (xmlSchemaComplexType.ContentModel is XmlSchemaSimpleContent)
                {
                    XmlSchemaAnnotated content = ((XmlSchemaSimpleContent)xmlSchemaComplexType.ContentModel).Content;
                    if (content is XmlSchemaSimpleContentExtension)
                    {
                        XmlSchemaSimpleContentExtension xmlSchemaSimpleContentExtension = (XmlSchemaSimpleContentExtension)content;
                        if (HasAttributes(xmlSchemaSimpleContentExtension.Attributes))
{
                            return null;
                        }
                    }
                    else
                    {
                        XmlSchemaSimpleContentRestriction xmlSchemaSimpleContentRestriction = (XmlSchemaSimpleContentRestriction)content;
                        if (HasAttributes(xmlSchemaSimpleContentRestriction.Attributes))
{
                            return null;
                        }
                    }
                }
                XmlSchemaParticle particle = GetParticle(xmlSchemaComplexType);
                if (particle != null && !IsDatasetParticle(particle))
                {
                    return null;
                }
                if (!(xmlSchemaComplexType.BaseXmlSchemaType is XmlSchemaComplexType))
                {
                    break;
                }
                xmlSchemaComplexType = (XmlSchemaComplexType)xmlSchemaComplexType.BaseXmlSchemaType;
            }
            return xmlSchemaElement2;
        }
        return null;
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Xml.Dictionary, System.Data.XSDSchema.FromInference, System.Data.XSDSchema.GetBooleanAttribute(), System.Data.XSDSchema.GetParticle(), System.Data.XSDSchema.HasAttributes(), and System.Data.XSDSchema.IsDatasetParticle().
Referenced by System.Data.XSDSchema.LoadSchema().