Terraria: System.Data.XSDSchema.HandleConstraint
HandleConstraint()
void System.Data.XSDSchema.HandleConstraint (XmlSchemaIdentityConstraint keyNode) inline package
Definition at line 1248 of file XSDSchema.cs.
    {
        string text = null;
        text = XmlConvert.DecodeName(keyNode.Name);
        if (text == null || text.Length == 0)
        {
            throw ExceptionBuilder.MissingAttribute("name");
        }
        if (_constraintNodes.ContainsKey(text))
        {
            throw ExceptionBuilder.DuplicateConstraintRead(text);
        }
        string tableName = GetTableName(keyNode);
        string msdataAttribute = GetMsdataAttribute(keyNode, "TableNamespace");
        DataTable tableSmart = _ds.Tables.GetTableSmart(tableName, msdataAttribute);
        if (tableSmart == null)
        {
            return;
        }
        _constraintNodes.Add(text, new ConstraintTable(tableSmart, keyNode));
        bool booleanAttribute = GetBooleanAttribute(keyNode, "PrimaryKey", defVal: false);
        text = GetStringAttribute(keyNode, "ConstraintName", text);
        DataColumn[] array = BuildKey(keyNode, tableSmart);
        if (array.Length == 0)
        {
            return;
        }
        UniqueConstraint uniqueConstraint = (UniqueConstraint)array[0].Table.Constraints.FindConstraint(new UniqueConstraint(text, array));
        if (uniqueConstraint == null)
        {
            array[0].Table.Constraints.Add(text, array, booleanAttribute);
            SetExtProperties(array[0].Table.Constraints[text], keyNode.UnhandledAttributes);
        }
        else
        {
            array = uniqueConstraint.ColumnsReference;
            SetExtProperties(uniqueConstraint, keyNode.UnhandledAttributes);
            if (booleanAttribute)
            {
                array[0].Table.PrimaryKey = array;
            }
        }
        if (keyNode is XmlSchemaKey)
        {
            for (int i = 0; i < array.Length; i++)
            {
                array[i].AllowDBNull = false;
            }
        }
    }
References System.Data.XSDSchema._constraintNodes, System.Data.XSDSchema._ds, System.Collections.Hashtable.Add(), System.array, System.Data.XSDSchema.BuildKey(), System.Collections.Hashtable.ContainsKey(), System.Xml.XmlConvert.DecodeName(), System.Data.ExceptionBuilder.DuplicateConstraintRead(), System.Data.XSDSchema.GetBooleanAttribute(), System.Data.XSDSchema.GetMsdataAttribute(), System.Data.XSDSchema.GetStringAttribute(), System.Data.XSDSchema.GetTableName(), System.Data.DataTableCollection.GetTableSmart(), System.Data.ExceptionBuilder.MissingAttribute(), System.Data.XSDSchema.SetExtProperties(), System.Data.DataSet.Tables, and System.text.