Terraria: System.Xml.Serialization.ReflectionXmlSerializationReaderHelper.GetSetMemberValueDelegateWithType< TObj, TParam >
GetSetMemberValueDelegateWithType< TObj, TParam >()
static SetMemberValueDelegate System.Xml.Serialization.ReflectionXmlSerializationReaderHelper.GetSetMemberValueDelegateWithType< TObj, TParam > (MemberInfo memberInfo) inline static
Definition at line 10 of file ReflectionXmlSerializationReaderHelper.cs.
    {
        if (typeof(TObj).IsValueType)
        {
            PropertyInfo propInfo2 = memberInfo as PropertyInfo;
            if ((object)propInfo2 != null)
            {
                return delegate(object o, object p)
                {
                    propInfo2.SetValue(o, p);
                };
            }
            FieldInfo fieldInfo = memberInfo as FieldInfo;
            if ((object)fieldInfo != null)
            {
                return delegate(object o, object p)
                {
                    fieldInfo.SetValue(o, p);
                };
            }
            throw new InvalidOperationException(System.SR.XmlInternalError);
        }
        Action<TObj, TParam> setTypedDelegate = null;
        PropertyInfo propInfo = memberInfo as PropertyInfo;
        if ((object)propInfo != null)
        {
            MethodInfo setMethod = propInfo.GetSetMethod(nonPublic: true);
            if (setMethod == null)
            {
                return delegate(object o, object p)
                {
                    propInfo.SetValue(o, p);
                };
            }
            setTypedDelegate = (Action<TObj, TParam>)setMethod.CreateDelegate(typeof(Action<TObj, TParam>));
        }
        else if (memberInfo is FieldInfo field)
        {
            ParameterExpression parameterExpression = Expression.Parameter(typeof(TObj));
            ParameterExpression parameterExpression2 = Expression.Parameter(typeof(TParam));
            MemberExpression left = Expression.Field(parameterExpression, field);
            BinaryExpression body = Expression.Assign(left, parameterExpression2);
            setTypedDelegate = Expression.Lambda<Action<TObj, TParam>>(body, new ParameterExpression[2] { parameterExpression, parameterExpression2 }).Compile();
        }
        return delegate(object o, object p)
        {
            setTypedDelegate((TObj)o, (TParam)p);
        };
    }
References System.Linq.Expressions.Expression< TDelegate >.Assign(), System.Reflection.MethodInfo.CreateDelegate(), System.Xml.Dictionary, System.Linq.Expressions.Expression< TDelegate >.Field(), System.Linq.Expressions.Expression< TDelegate >.Lambda(), System.Linq.Expressions.Expression< TDelegate >.Parameter(), System.Reflection.FieldInfo.SetValue(), System.Reflection.PropertyInfo.SetValue(), and System.SR.XmlInternalError.