Terraria: System.Threading.Tasks.TaskReplicator.Replica.Execute
Execute()
void System.Threading.Tasks.TaskReplicator.Replica< TState >.Execute () inline
Definition at line 45 of file TaskReplicator.cs.
        {
            try
            {
                if (!_replicator._stopReplicating && _remainingConcurrency > 0)
                {
                    CreateNewReplica();
                    _remainingConcurrency = 0;
                }
                ExecuteAction(out var yieldedBeforeCompletion);
                if (yieldedBeforeCompletion)
                {
                    _pendingTask = new Task(delegate(object s)
                    {
                        ((Replica)s).Execute();
                    }, this, CancellationToken.None, TaskCreationOptions.None);
                    _pendingTask.Start(_replicator._scheduler);
                }
                else
                {
                    _replicator._stopReplicating = true;
                    _pendingTask = null;
                }
            }
            catch (Exception item)
            {
                LazyInitializer.EnsureInitialized(ref _replicator._exceptions).Enqueue(item);
                if (_replicator._stopOnFirstFailure)
                {
                    _replicator._stopReplicating = true;
                }
                _pendingTask = null;
            }
        }
References System.Threading.Tasks.TaskReplicator.Replica< TState >.Replica(), System.Threading.Tasks.TaskReplicator._exceptions, System.Threading.Tasks.TaskReplicator.Replica< TState >._pendingTask, System.Threading.Tasks.TaskReplicator.Replica< TState >._remainingConcurrency, System.Threading.Tasks.TaskReplicator.Replica< TState >._replicator, System.Threading.Tasks.TaskReplicator._scheduler, System.Threading.Tasks.TaskReplicator._stopOnFirstFailure, System.Threading.Tasks.TaskReplicator._stopReplicating, System.Threading.Tasks.TaskReplicator.Replica< TState >.CreateNewReplica(), System.Threading.Tasks.TaskReplicator.Replica< TState >.ExecuteAction(), System.item, System.Threading.CancellationToken.None, System.s, and System.Threading.Tasks.Task< TResult >.Start().