Terraria: System.Threading.Tasks.TaskReplicator.Replica.Replica
Replica() [1/2]
System.Threading.Tasks.TaskReplicator.Replica< TState >.Replica (TaskReplicator replicator, int maxConcurrency, int timeout) inline protected
Definition at line 19 of file TaskReplicator.cs.
        {
            _replicator = replicator;
            _timeout = timeout;
            _remainingConcurrency = maxConcurrency - 1;
            _pendingTask = new Task(delegate(object s)
            {
                ((Replica)s).Execute();
            }, this);
            _replicator._pendingReplicas.Enqueue(this);
        }
References System.Threading.Tasks.TaskReplicator.Replica< TState >.Replica(), System.Threading.Tasks.TaskReplicator._pendingReplicas, System.Threading.Tasks.TaskReplicator.Replica< TState >._pendingTask, System.Threading.Tasks.TaskReplicator.Replica< TState >._remainingConcurrency, System.Threading.Tasks.TaskReplicator.Replica< TState >._replicator, System.Threading.Tasks.TaskReplicator.Replica< TState >._timeout, System.s, and System.timeout.
Referenced by System.Threading.Tasks.TaskReplicator.Replica< TState >.Replica(), and System.Threading.Tasks.TaskReplicator.Replica< TState >.Execute().