Terraria: System.Xml.Xsl.Runtime.XmlQueryOutput.WriteStartAttribute
WriteStartAttribute() [3/4]
override void System.Xml.Xsl.Runtime.XmlQueryOutput.WriteStartAttribute (string prefix, string localName, string ns) inline
Definition at line 162 of file XmlQueryOutput.cs.
    {
        if (prefix.Length == 5 && prefix == "xmlns")
        {
            WriteStartNamespace(localName);
            return;
        }
        ConstructInEnumAttrs(XPathNodeType.Attribute);
        if (ns.Length != 0 && _depth != 0)
        {
            prefix = CheckAttributePrefix(prefix, ns);
        }
        WriteStartAttributeUnchecked(prefix, localName, ns);
    }
References System.Xml.Xsl.Runtime.XmlQueryOutput._depth, System.Xml.Xsl.Runtime.XmlQueryOutput.CheckAttributePrefix(), System.Xml.Xsl.Runtime.XmlQueryOutput.ConstructInEnumAttrs(), System.prefix, System.Xml.Xsl.Runtime.XmlQueryOutput.WriteStartAttributeUnchecked(), and System.Xml.Xsl.Runtime.XmlQueryOutput.WriteStartNamespace().
Referenced by System.Xml.Xsl.Runtime.XmlQueryOutput.StartCopy(), System.Xml.Xsl.Runtime.XmlQueryOutput.WriteStartAttributeLocalName(), System.Xml.Xsl.Runtime.XmlQueryOutput.WriteStartComputed(), System.Xml.Xsl.Runtime.XmlQueryOutput.WriteStartComputed(), System.Xml.Xsl.Runtime.XmlQueryOutput.WriteStartComputed(), and System.Xml.Xsl.Runtime.XmlQueryOutput.WriteStartComputed().