Terraria: System.Xml.Xsl.Runtime.XmlQueryOutput.WriteStartElement
WriteStartElement() [3/4]
override void System.Xml.Xsl.Runtime.XmlQueryOutput.WriteStartElement (string prefix, string localName, string ns) inline
Definition at line 128 of file XmlQueryOutput.cs.
    {
        ConstructWithinContent(XPathNodeType.Element);
        WriteStartElementUnchecked(prefix, localName, ns);
        WriteNamespaceDeclarationUnchecked(prefix, ns);
        if (_attrCache == null)
        {
            _attrCache = new XmlAttributeCache();
        }
        _attrCache.Init(Writer);
        Writer = _attrCache;
        _attrCache = null;
        PushElementNames(prefix, localName, ns);
    }
References System.Xml.Xsl.Runtime.XmlQueryOutput._attrCache, System.Xml.Xsl.Runtime.XmlQueryOutput.ConstructWithinContent(), System.Xml.Xsl.Runtime.XmlAttributeCache.Init(), System.prefix, System.Xml.Xsl.Runtime.XmlQueryOutput.PushElementNames(), System.Xml.Xsl.Runtime.XmlQueryOutput.WriteNamespaceDeclarationUnchecked(), and System.Xml.Xsl.Runtime.XmlQueryOutput.WriteStartElementUnchecked().
Referenced by System.Xml.Xsl.Runtime.XmlQueryOutput.StartCopy(), System.Xml.Xsl.Runtime.XmlQueryOutput.WriteStartComputed(), System.Xml.Xsl.Runtime.XmlQueryOutput.WriteStartComputed(), System.Xml.Xsl.Runtime.XmlQueryOutput.WriteStartComputed(), System.Xml.Xsl.Runtime.XmlQueryOutput.WriteStartComputed(), and System.Xml.Xsl.Runtime.XmlQueryOutput.WriteStartElementLocalName().