Terraria: System.Xml.Xsl.Runtime.XmlQueryOutput.WriteNamespaceDeclaration
WriteNamespaceDeclaration()
void System.Xml.Xsl.Runtime.XmlQueryOutput.WriteNamespaceDeclaration (string prefix, string ns) inline
Definition at line 444 of file XmlQueryOutput.cs.
    {
        ConstructInEnumAttrs(XPathNodeType.Namespace);
        if (_nsmgr == null)
        {
            WriteNamespaceDeclarationUnchecked(prefix, ns);
        }
        else
        {
            string text = _nsmgr.LookupNamespace(prefix);
            if (ns != text)
            {
                if (text != null && _usedPrefixes.ContainsKey(prefix))
                {
                    throw new XslTransformException(System.SR.XmlIl_NmspConflict, (prefix.Length == 0) ? "" : ":", prefix, ns, text);
                }
                AddNamespace(prefix, ns);
            }
        }
        if (_depth == 0)
        {
            EndTree();
        }
        _usedPrefixes[prefix] = ns;
    }
References System.Xml.Xsl.Runtime.XmlQueryOutput._depth, System.Xml.Xsl.Runtime.XmlQueryOutput._nsmgr, System.Xml.Xsl.Runtime.XmlQueryOutput._usedPrefixes, System.Xml.Xsl.Runtime.XmlQueryOutput.AddNamespace(), System.Xml.Xsl.Runtime.XmlQueryOutput.ConstructInEnumAttrs(), System.Collections.Generic.Dictionary< TKey, TValue >.ContainsKey(), System.Xml.Xsl.Runtime.XmlQueryOutput.EndTree(), System.Xml.XmlNamespaceManager.LookupNamespace(), System.prefix, System.text, System.Xml.Xsl.Runtime.XmlQueryOutput.WriteNamespaceDeclarationUnchecked(), and System.SR.XmlIl_NmspConflict.
Referenced by System.Xml.Xsl.Runtime.XmlQueryOutput.StartCopy(), and System.Xml.Xsl.Runtime.XmlQueryOutput.WriteEndNamespace().