Terraria: System.Xml.Xsl.Runtime.XmlQueryOutput.WriteStartComputed
WriteStartComputed() [1/4]
void System.Xml.Xsl.Runtime.XmlQueryOutput.WriteStartComputed (XPathNodeType nodeType, string tagName, int prefixMappingsIndex) inline private
Definition at line 917 of file XmlQueryOutput.cs.
    {
        _runtime.ParseTagName(tagName, prefixMappingsIndex, out var prefix, out var localName, out var ns);
        prefix = EnsureValidName(prefix, localName, ns, nodeType);
        if (nodeType == XPathNodeType.Element)
        {
            WriteStartElement(prefix, localName, ns);
        }
        else
        {
            WriteStartAttribute(prefix, localName, ns);
        }
    }
References System.Xml.Xsl.Runtime.XmlQueryOutput._runtime, System.Xml.Xsl.Runtime.XmlQueryOutput.EnsureValidName(), System.Xml.Xsl.Runtime.XmlQueryRuntime.ParseTagName(), System.prefix, System.Xml.Xsl.Runtime.XmlQueryOutput.WriteStartAttribute(), and System.Xml.Xsl.Runtime.XmlQueryOutput.WriteStartElement().
Referenced by System.Xml.Xsl.Runtime.XmlQueryOutput.WriteStartAttributeComputed(), System.Xml.Xsl.Runtime.XmlQueryOutput.WriteStartAttributeComputed(), System.Xml.Xsl.Runtime.XmlQueryOutput.WriteStartAttributeComputed(), System.Xml.Xsl.Runtime.XmlQueryOutput.WriteStartAttributeComputed(), System.Xml.Xsl.Runtime.XmlQueryOutput.WriteStartElementComputed(), System.Xml.Xsl.Runtime.XmlQueryOutput.WriteStartElementComputed(), System.Xml.Xsl.Runtime.XmlQueryOutput.WriteStartElementComputed(), and System.Xml.Xsl.Runtime.XmlQueryOutput.WriteStartElementComputed().