Terraria: System.Xml.Xsl.Runtime.XmlQueryOutput.ThrowInvalidStateError
ThrowInvalidStateError()
void System.Xml.Xsl.Runtime.XmlQueryOutput.ThrowInvalidStateError (XPathNodeType constructorType) inline private
Definition at line 1006 of file XmlQueryOutput.cs.
    {
        switch (constructorType)
        {
        case XPathNodeType.Root:
        case XPathNodeType.Element:
        case XPathNodeType.Text:
        case XPathNodeType.ProcessingInstruction:
        case XPathNodeType.Comment:
            throw new XslTransformException(System.SR.XmlIl_BadXmlState, constructorType.ToString(), XmlStateToNodeType(_xstate).ToString());
        case XPathNodeType.Attribute:
        case XPathNodeType.Namespace:
            if (_depth == 1)
            {
                throw new XslTransformException(System.SR.XmlIl_BadXmlState, constructorType.ToString(), _rootType.ToString());
            }
            if (_xstate == XmlState.WithinContent)
            {
                throw new XslTransformException(System.SR.XmlIl_BadXmlStateAttr, string.Empty);
            }
            goto case XPathNodeType.Root;
        default:
            throw new XslTransformException(System.SR.XmlIl_BadXmlState, "Unknown", XmlStateToNodeType(_xstate).ToString());
        }
    }
References System.Xml.Xsl.Runtime.XmlQueryOutput._depth, System.Xml.Xsl.Runtime.XmlQueryOutput._rootType, System.Xml.Xsl.Runtime.XmlQueryOutput._xstate, System.ToString, System.SR.XmlIl_BadXmlState, System.SR.XmlIl_BadXmlStateAttr, and System.Xml.Xsl.Runtime.XmlQueryOutput.XmlStateToNodeType().
Referenced by System.Xml.Xsl.Runtime.XmlQueryOutput.ConstructInEnumAttrs(), System.Xml.Xsl.Runtime.XmlQueryOutput.ConstructWithinContent(), System.Xml.Xsl.Runtime.XmlQueryOutput.StartCopy(), and System.Xml.Xsl.Runtime.XmlQueryOutput.WriteStartRoot().