Terraria: System.Xml.Xsl.Runtime.XmlQueryOutput.WriteEndElementUnchecked
WriteEndElementUnchecked() [2/2]
void System.Xml.Xsl.Runtime.XmlQueryOutput.WriteEndElementUnchecked (string prefix, string localName, string ns) inline
Definition at line 310 of file XmlQueryOutput.cs.
    {
        Writer.WriteEndElement(prefix, localName, ns);
        _xstate = XmlState.WithinContent;
        _depth--;
        if (_nsmgr != null)
        {
            _nsmgr.PopScope();
        }
    }
References System.Xml.Xsl.Runtime.XmlQueryOutput._depth, System.Xml.Xsl.Runtime.XmlQueryOutput._nsmgr, System.Xml.Xsl.Runtime.XmlQueryOutput._xstate, System.Xml.XmlNamespaceManager.PopScope(), and System.prefix.
Referenced by System.Xml.Xsl.Runtime.XmlQueryOutput.EndCopy(), System.Xml.Xsl.Runtime.XmlQueryOutput.WriteEndElement(), and System.Xml.Xsl.Runtime.XmlQueryOutput.WriteEndElementUnchecked().