Terraria: System.Xml.Xsl.Runtime.XmlQueryOutput.WriteEndNamespace
WriteEndNamespace()
void System.Xml.Xsl.Runtime.XmlQueryOutput.WriteEndNamespace () inline
Definition at line 484 of file XmlQueryOutput.cs.
    {
        _xstate = XmlState.EnumAttrs;
        _depth--;
        WriteNamespaceDeclaration(_piTarget, _nodeText.GetResult());
        if (_depth == 0)
        {
            EndTree();
        }
    }
References System.Xml.Xsl.Runtime.XmlQueryOutput._depth, System.Xml.Xsl.Runtime.XmlQueryOutput._nodeText, System.Xml.Xsl.Runtime.XmlQueryOutput._piTarget, System.Xml.Xsl.Runtime.XmlQueryOutput._xstate, System.Xml.Xsl.Runtime.XmlQueryOutput.EndTree(), System.Xml.Xsl.Runtime.StringConcat.GetResult(), and System.Xml.Xsl.Runtime.XmlQueryOutput.WriteNamespaceDeclaration().
Referenced by System.Xml.Xsl.Runtime.XmlQueryOutput.WriteEndAttribute().