Terraria: System.Xml.Xsl.Runtime.XmlQueryOutput.WriteString
WriteString() [2/3]
void System.Xml.Xsl.Runtime.XmlQueryOutput.WriteString (string text, bool disableOutputEscaping) inline private
Definition at line 618 of file XmlQueryOutput.cs.
    {
        switch (_xstate)
        {
        case XmlState.WithinSequence:
            StartTree(XPathNodeType.Text);
            goto case XmlState.WithinContent;
        case XmlState.WithinContent:
            if (disableOutputEscaping)
            {
                WriteRawUnchecked(text);
            }
            else
            {
                WriteStringUnchecked(text);
            }
            break;
        case XmlState.EnumAttrs:
            StartElementContentUnchecked();
            goto case XmlState.WithinContent;
        case XmlState.WithinAttr:
            WriteStringUnchecked(text);
            break;
        case XmlState.WithinNmsp:
            WriteNamespaceString(text);
            break;
        case XmlState.WithinComment:
            WriteCommentString(text);
            break;
        case XmlState.WithinPI:
            WriteProcessingInstructionString(text);
            break;
        }
        if (_depth == 0)
        {
            EndTree();
        }
    }
References System.Xml.Xsl.Runtime.XmlQueryOutput._depth, System.Xml.Xsl.Runtime.XmlQueryOutput._xstate, System.Xml.Xsl.Runtime.XmlQueryOutput.EndTree(), System.Xml.Xsl.Runtime.XmlQueryOutput.StartElementContentUnchecked(), System.Xml.Xsl.Runtime.XmlQueryOutput.StartTree(), System.text, System.Xml.Xsl.Runtime.XmlQueryOutput.WriteCommentString(), System.Xml.Xsl.Runtime.XmlQueryOutput.WriteNamespaceString(), System.Xml.Xsl.Runtime.XmlQueryOutput.WriteProcessingInstructionString(), System.Xml.Xsl.Runtime.XmlQueryOutput.WriteRawUnchecked(), and System.Xml.Xsl.Runtime.XmlQueryOutput.WriteStringUnchecked().