Terraria: System.Xml.Xsl.Runtime.XmlQueryOutput.WriteStartComputed
WriteStartComputed() [3/4]
void System.Xml.Xsl.Runtime.XmlQueryOutput.WriteStartComputed (XPathNodeType nodeType, XmlQualifiedName name) inline private
Definition at line 964 of file XmlQueryOutput.cs.
    {
        string prefix = ((name.Namespace.Length != 0) ? RemapPrefix(string.Empty, name.Namespace, nodeType == XPathNodeType.Element) : string.Empty);
        prefix = EnsureValidName(prefix, name.Name, name.Namespace, nodeType);
        if (nodeType == XPathNodeType.Element)
        {
            WriteStartElement(prefix, name.Name, name.Namespace);
        }
        else
        {
            WriteStartAttribute(prefix, name.Name, name.Namespace);
        }
    }
References System.Xml.Dictionary, System.Xml.Xsl.Runtime.XmlQueryOutput.EnsureValidName(), System.prefix, System.Xml.Xsl.Runtime.XmlQueryOutput.RemapPrefix(), System.Xml.Xsl.Runtime.XmlQueryOutput.WriteStartAttribute(), and System.Xml.Xsl.Runtime.XmlQueryOutput.WriteStartElement().