Terraria: System.Xml.Xsl.Runtime.XmlQueryOutput.CopyNode
CopyNode()
void System.Xml.Xsl.Runtime.XmlQueryOutput.CopyNode (XPathNavigator navigator) inline private
Definition at line 657 of file XmlQueryOutput.cs.
    {
        int depth = _depth;
        while (true)
        {
            if (StartCopy(navigator, _depth == depth))
            {
                XPathNodeType nodeType = navigator.NodeType;
                if (navigator.MoveToFirstAttribute())
                {
                    do
                    {
                        StartCopy(navigator, callChk: false);
                    }
                    while (navigator.MoveToNextAttribute());
                    navigator.MoveToParent();
                }
                CopyNamespaces(navigator, (_depth - 1 == depth) ? XPathNamespaceScope.ExcludeXml : XPathNamespaceScope.Local);
                StartElementContentUnchecked();
                if (navigator.MoveToFirstChild())
                {
                    continue;
                }
                EndCopy(navigator, _depth - 1 == depth);
            }
            while (true)
            {
                if (_depth == depth)
                {
                    return;
                }
                if (navigator.MoveToNext())
                {
                    break;
                }
                navigator.MoveToParent();
                EndCopy(navigator, _depth - 1 == depth);
            }
        }
    }
References System.Xml.Xsl.Runtime.XmlQueryOutput._depth, System.Xml.Xsl.Runtime.XmlQueryOutput.CopyNamespaces(), System.Xml.Xsl.Runtime.XmlQueryOutput.EndCopy(), System.Xml.Xsl.Runtime.XmlQueryOutput.StartCopy(), and System.Xml.Xsl.Runtime.XmlQueryOutput.StartElementContentUnchecked().
Referenced by System.Xml.Xsl.Runtime.XmlQueryOutput.WriteItem(), and System.Xml.Xsl.Runtime.XmlQueryOutput.XsltCopyOf().