Terraria: System.Xml.Xsl.Runtime.XmlQueryOutput.StartCopy
StartCopy() [2/2]
bool System.Xml.Xsl.Runtime.XmlQueryOutput.StartCopy (XPathNavigator navigator, bool callChk) inline private
Definition at line 698 of file XmlQueryOutput.cs.
    {
        bool result = false;
        switch (navigator.NodeType)
        {
        case XPathNodeType.Element:
            if (callChk)
            {
                WriteStartElement(navigator.Prefix, navigator.LocalName, navigator.NamespaceURI);
            }
            else
            {
                WriteStartElementUnchecked(navigator.Prefix, navigator.LocalName, navigator.NamespaceURI);
            }
            result = true;
            break;
        case XPathNodeType.Attribute:
            if (callChk)
            {
                WriteStartAttribute(navigator.Prefix, navigator.LocalName, navigator.NamespaceURI);
            }
            else
            {
                WriteStartAttributeUnchecked(navigator.Prefix, navigator.LocalName, navigator.NamespaceURI);
            }
            WriteString(navigator.Value);
            if (callChk)
            {
                WriteEndAttribute();
            }
            else
            {
                WriteEndAttributeUnchecked();
            }
            break;
        case XPathNodeType.Namespace:
            if (callChk)
            {
                if (Writer is XmlAttributeCache { Count: not 0 })
                {
                    throw new XslTransformException(System.SR.XmlIl_NmspAfterAttr, string.Empty);
                }
                WriteNamespaceDeclaration(navigator.LocalName, navigator.Value);
            }
            else
            {
                WriteNamespaceDeclarationUnchecked(navigator.LocalName, navigator.Value);
            }
            break;
        case XPathNodeType.Text:
        case XPathNodeType.SignificantWhitespace:
        case XPathNodeType.Whitespace:
            if (callChk)
            {
                WriteString(navigator.Value, disableOutputEscaping: false);
            }
            else
            {
                WriteStringUnchecked(navigator.Value);
            }
            break;
        case XPathNodeType.Root:
            ThrowInvalidStateError(XPathNodeType.Root);
            break;
        case XPathNodeType.Comment:
            WriteStartComment();
            WriteCommentString(navigator.Value);
            WriteEndComment();
            break;
        case XPathNodeType.ProcessingInstruction:
            WriteStartProcessingInstruction(navigator.LocalName);
            WriteProcessingInstructionString(navigator.Value);
            WriteEndProcessingInstruction();
            break;
        }
        return result;
    }
References System.Xml.Xsl.Runtime.XmlQueryOutput.ThrowInvalidStateError(), System.Xml.Xsl.Runtime.XmlQueryOutput.WriteCommentString(), System.Xml.Xsl.Runtime.XmlQueryOutput.WriteEndAttribute(), System.Xml.Xsl.Runtime.XmlQueryOutput.WriteEndAttributeUnchecked(), System.Xml.Xsl.Runtime.XmlQueryOutput.WriteEndComment(), System.Xml.Xsl.Runtime.XmlQueryOutput.WriteEndProcessingInstruction(), System.Xml.Xsl.Runtime.XmlQueryOutput.WriteNamespaceDeclaration(), System.Xml.Xsl.Runtime.XmlQueryOutput.WriteNamespaceDeclarationUnchecked(), System.Xml.Xsl.Runtime.XmlQueryOutput.WriteProcessingInstructionString(), System.Xml.Xsl.Runtime.XmlQueryOutput.WriteStartAttribute(), System.Xml.Xsl.Runtime.XmlQueryOutput.WriteStartAttributeUnchecked(), System.Xml.Xsl.Runtime.XmlQueryOutput.WriteStartComment(), System.Xml.Xsl.Runtime.XmlQueryOutput.WriteStartElement(), System.Xml.Xsl.Runtime.XmlQueryOutput.WriteStartElementUnchecked(), System.Xml.Xsl.Runtime.XmlQueryOutput.WriteStartProcessingInstruction(), System.Xml.Xsl.Runtime.XmlQueryOutput.WriteString(), System.Xml.Xsl.Runtime.XmlQueryOutput.WriteStringUnchecked(), and System.SR.XmlIl_NmspAfterAttr.