Terraria: System.Xml.Xsl.Runtime.XmlQueryOutput.CopyNamespaces
CopyNamespaces()
void System.Xml.Xsl.Runtime.XmlQueryOutput.CopyNamespaces (XPathNavigator navigator, XPathNamespaceScope nsScope) inline private
Definition at line 788 of file XmlQueryOutput.cs.
    {
        if (navigator.NamespaceURI.Length == 0)
        {
            WriteNamespaceDeclarationUnchecked(string.Empty, string.Empty);
        }
        if (navigator.MoveToFirstNamespace(nsScope))
        {
            CopyNamespacesHelper(navigator, nsScope);
            navigator.MoveToParent();
        }
    }
References System.Xml.Xsl.Runtime.XmlQueryOutput.CopyNamespacesHelper(), and System.Xml.Xsl.Runtime.XmlQueryOutput.WriteNamespaceDeclarationUnchecked().
Referenced by System.Xml.Xsl.Runtime.XmlQueryOutput.CopyNode(), and System.Xml.Xsl.Runtime.XmlQueryOutput.StartCopy().