Terraria: System.Xml.Xsl.Runtime.XmlQueryOutput.CheckAttributePrefix
CheckAttributePrefix()
string System.Xml.Xsl.Runtime.XmlQueryOutput.CheckAttributePrefix (string prefix, string ns) inline private
Definition at line 870 of file XmlQueryOutput.cs.
    {
        if (_nsmgr == null)
        {
            WriteNamespaceDeclarationUnchecked(prefix, ns);
        }
        else
        {
            while (true)
            {
                string text = _nsmgr.LookupNamespace(prefix);
                if (!(text != ns))
                {
                    break;
                }
                if (text != null)
                {
                    prefix = RemapPrefix(prefix, ns, isElemPrefix: false);
                    continue;
                }
                AddNamespace(prefix, ns);
                break;
            }
        }
        return prefix;
    }
References System.Xml.Xsl.Runtime.XmlQueryOutput._nsmgr, System.Xml.Xsl.Runtime.XmlQueryOutput.AddNamespace(), System.Xml.XmlNamespaceManager.LookupNamespace(), System.prefix, System.Xml.Xsl.Runtime.XmlQueryOutput.RemapPrefix(), System.text, and System.Xml.Xsl.Runtime.XmlQueryOutput.WriteNamespaceDeclarationUnchecked().
Referenced by System.Xml.Xsl.Runtime.XmlQueryOutput.WriteStartAttribute().