Terraria: System.Xml.Xsl.Runtime.XmlQueryOutput.EnsureValidName
EnsureValidName()
string System.Xml.Xsl.Runtime.XmlQueryOutput.EnsureValidName (string prefix, string localName, string ns, XPathNodeType nodeType) inline private
Definition at line 978 of file XmlQueryOutput.cs.
    {
        if (!ValidateNames.ValidateName(prefix, localName, ns, nodeType, ValidateNames.Flags.AllExceptNCNames))
        {
            prefix = ((ns.Length != 0) ? RemapPrefix(string.Empty, ns, nodeType == XPathNodeType.Element) : string.Empty);
            ValidateNames.ValidateNameThrow(prefix, localName, ns, nodeType, ValidateNames.Flags.AllExceptNCNames);
        }
        return prefix;
    }
References System.Xml.Dictionary, System.prefix, System.Xml.Xsl.Runtime.XmlQueryOutput.RemapPrefix(), System.Xml.ValidateNames.ValidateName(), and System.Xml.ValidateNames.ValidateNameThrow().
Referenced by System.Xml.Xsl.Runtime.XmlQueryOutput.WriteStartComputed(), System.Xml.Xsl.Runtime.XmlQueryOutput.WriteStartComputed(), System.Xml.Xsl.Runtime.XmlQueryOutput.WriteStartComputed(), and System.Xml.Xsl.Runtime.XmlQueryOutput.WriteStartComputed().