Terraria: System.Net.Http.HttpConnection.ChunkedEncodingWriteStream.WriteAsync
WriteAsync() [3/3]
override ValueTask System.Net.Http.HttpConnection.ChunkedEncodingWriteStream.WriteAsync (ReadOnlyMemory< byte > buffer, CancellationToken ignored) inline virtual
Reimplemented from System.Net.Http.HttpBaseStream.
Definition at line 394 of file HttpConnection.cs.
        {
            base.BytesWritten += buffer.Length;
            HttpConnection connectionOrThrow = GetConnectionOrThrow();
            return (buffer.Length == 0) ? connectionOrThrow.FlushAsync(async: true) : WriteChunkAsync(connectionOrThrow, buffer);
            static async ValueTask WriteChunkAsync(HttpConnection connection, ReadOnlyMemory<byte> buffer)
            {
                await connection.WriteHexInt32Async(buffer.Length, async: true).ConfigureAwait(continueOnCapturedContext: false);
                await connection.WriteTwoBytesAsync(13, 10, async: true).ConfigureAwait(continueOnCapturedContext: false);
                await connection.WriteAsync(buffer, async: true).ConfigureAwait(continueOnCapturedContext: false);
                await connection.WriteTwoBytesAsync(13, 10, async: true).ConfigureAwait(continueOnCapturedContext: false);
            }
        }
References System.buffer, System.Net.Http.HttpContentStream.GetConnectionOrThrow(), System.Net.Http.HttpConnection.WriteAsync(), System.Net.Http.HttpConnection.WriteHexInt32Async(), and System.Net.Http.HttpConnection.WriteTwoBytesAsync().