Terraria: System.Data.Common.SqlConvert.ChangeTypeForDefaultValue
ChangeTypeForDefaultValue()
static object System.Data.Common.SqlConvert.ChangeTypeForDefaultValue (object value, Type type, IFormatProvider formatProvider) inline static
Definition at line 306 of file SqlConvert.cs.
    {
        if (type == typeof(BigInteger))
        {
            if (DBNull.Value == value || value == null)
            {
                return DBNull.Value;
            }
            return BigIntegerStorage.ConvertToBigInteger(value, formatProvider);
        }
        if (value is BigInteger)
        {
            return BigIntegerStorage.ConvertFromBigInteger((BigInteger)value, type, formatProvider);
        }
        return ChangeType2(value, DataStorage.GetStorageType(type), type, formatProvider);
    }
References System.Data.Common.SqlConvert.ChangeType2(), System.Data.Common.BigIntegerStorage.ConvertFromBigInteger(), System.Data.Common.BigIntegerStorage.ConvertToBigInteger(), System.Xml.Dictionary, System.Data.Common.DataStorage.GetStorageType(), System.type, System.DBNull.Value, and System.value.