Terraria: System.Data.Common.SqlConvert.ConvertToSqlGuid
ConvertToSqlGuid()
static SqlGuid System.Data.Common.SqlConvert.ConvertToSqlGuid (object value) inline static
Definition at line 226 of file SqlConvert.cs.
    {
        if (value == DBNull.Value)
        {
            return SqlGuid.Null;
        }
        Type type = value.GetType();
        return DataStorage.GetStorageType(type) switch
        {
            StorageType.SqlGuid => (SqlGuid)value,
            StorageType.Guid => (Guid)value,
            _ => throw ExceptionBuilder.ConvertFailed(type, typeof(SqlGuid)),
        };
    }
References System.Data.ExceptionBuilder.ConvertFailed(), System.Xml.Dictionary, System.Data.Common.DataStorage.GetStorageType(), System.Type.GetType(), System.Data.SqlTypes.SqlGuid.Null, System.Data.Common.SqlGuid, System.type, System.DBNull.Value, and System.value.
Referenced by System.Data.Common.SqlConvert.ChangeType2(), System.Data.Common.SqlGuidStorage.ConvertValue(), and System.Data.Common.SqlGuidStorage.Set().