Terraria: System.Data.Common.SqlConvert.ChangeType2
ChangeType2()
static object System.Data.Common.SqlConvert.ChangeType2 (object value, StorageType stype, Type type, IFormatProvider formatProvider) inline static
Definition at line 323 of file SqlConvert.cs.
    {
        switch (stype)
        {
        case StorageType.SqlBinary:
            return ConvertToSqlBinary(value);
        case StorageType.SqlBoolean:
            return ConvertToSqlBoolean(value);
        case StorageType.SqlByte:
            return ConvertToSqlByte(value);
        case StorageType.SqlBytes:
            return ConvertToSqlBytes(value);
        case StorageType.SqlChars:
            return ConvertToSqlChars(value);
        case StorageType.SqlDateTime:
            return ConvertToSqlDateTime(value);
        case StorageType.SqlDecimal:
            return ConvertToSqlDecimal(value);
        case StorageType.SqlDouble:
            return ConvertToSqlDouble(value);
        case StorageType.SqlGuid:
            return ConvertToSqlGuid(value);
        case StorageType.SqlInt16:
            return ConvertToSqlInt16(value);
        case StorageType.SqlInt32:
            return ConvertToSqlInt32(value);
        case StorageType.SqlInt64:
            return ConvertToSqlInt64(value);
        case StorageType.SqlMoney:
            return ConvertToSqlMoney(value);
        case StorageType.SqlSingle:
            return ConvertToSqlSingle(value);
        case StorageType.SqlString:
            return ConvertToSqlString(value);
        default:
        {
            if (DBNull.Value == value || value == null)
            {
                return DBNull.Value;
            }
            Type type2 = value.GetType();
            StorageType storageType = DataStorage.GetStorageType(type2);
            if ((uint)(storageType - 26) <= 14u)
            {
                throw ExceptionBuilder.ConvertFailed(type2, type);
            }
            if (StorageType.String == stype)
            {
                switch (storageType)
                {
                case StorageType.Boolean:
                    return ((IConvertible)(bool)value).ToString(formatProvider);
                case StorageType.Char:
                    return ((IConvertible)(char)value).ToString(formatProvider);
                case StorageType.SByte:
                    return ((sbyte)value).ToString(formatProvider);
                case StorageType.Byte:
                    return ((byte)value).ToString(formatProvider);
                case StorageType.Int16:
                    return ((short)value).ToString(formatProvider);
                case StorageType.UInt16:
                    return ((ushort)value).ToString(formatProvider);
                case StorageType.Int32:
                    return ((int)value).ToString(formatProvider);
                case StorageType.UInt32:
                    return ((uint)value).ToString(formatProvider);
                case StorageType.Int64:
                    return ((long)value).ToString(formatProvider);
                case StorageType.UInt64:
                    return ((ulong)value).ToString(formatProvider);
                case StorageType.Single:
                    return ((float)value).ToString(formatProvider);
                case StorageType.Double:
                    return ((double)value).ToString(formatProvider);
                case StorageType.Decimal:
                    return ((decimal)value).ToString(formatProvider);
                case StorageType.DateTime:
                    return ((DateTime)value).ToString(formatProvider);
                case StorageType.TimeSpan:
                    return XmlConvert.ToString((TimeSpan)value);
                case StorageType.Guid:
                    return XmlConvert.ToString((Guid)value);
                case StorageType.String:
                    return (string)value;
                case StorageType.CharArray:
                    return new string((char[])value);
                case StorageType.DateTimeOffset:
                    return ((DateTimeOffset)value).ToString(formatProvider);
                default:
                    if (value is IConvertible convertible)
                    {
                        return convertible.ToString(formatProvider);
                    }
                    if (value is IFormattable formattable)
                    {
                        return formattable.ToString(null, formatProvider);
                    }
                    return value.ToString();
                case StorageType.BigInteger:
                    break;
                }
            }
            else
            {
                if (StorageType.TimeSpan == stype)
                {
                    return storageType switch
                    {
                        StorageType.String => XmlConvert.ToTimeSpan((string)value),
                        StorageType.Int32 => new TimeSpan((int)value),
                        StorageType.Int64 => new TimeSpan((long)value),
                        _ => (TimeSpan)value,
                    };
                }
                if (StorageType.DateTimeOffset == stype)
                {
                    return (DateTimeOffset)value;
                }
                if (StorageType.String == storageType)
                {
                    switch (stype)
                    {
                    case StorageType.String:
                        return (string)value;
                    case StorageType.Boolean:
                        if ("1" == (string)value)
{
                            return true;
                        }
                        if ("0" == (string)value)
{
                            return false;
                        }
                        break;
                    case StorageType.Char:
                        return ((IConvertible)(string)value).ToChar(formatProvider);
                    case StorageType.SByte:
                        return ((IConvertible)(string)value).ToSByte(formatProvider);
                    case StorageType.Byte:
                        return ((IConvertible)(string)value).ToByte(formatProvider);
                    case StorageType.Int16:
                        return ((IConvertible)(string)value).ToInt16(formatProvider);
                    case StorageType.UInt16:
                        return ((IConvertible)(string)value).ToUInt16(formatProvider);
                    case StorageType.Int32:
                        return ((IConvertible)(string)value).ToInt32(formatProvider);
                    case StorageType.UInt32:
                        return ((IConvertible)(string)value).ToUInt32(formatProvider);
                    case StorageType.Int64:
                        return ((IConvertible)(string)value).ToInt64(formatProvider);
                    case StorageType.UInt64:
                        return ((IConvertible)(string)value).ToUInt64(formatProvider);
                    case StorageType.Single:
                        return ((IConvertible)(string)value).ToSingle(formatProvider);
                    case StorageType.Double:
                        return ((IConvertible)(string)value).ToDouble(formatProvider);
                    case StorageType.Decimal:
                        return ((IConvertible)(string)value).ToDecimal(formatProvider);
                    case StorageType.DateTime:
                        return ((IConvertible)(string)value).ToDateTime(formatProvider);
                    case StorageType.TimeSpan:
                        return XmlConvert.ToTimeSpan((string)value);
                    case StorageType.Guid:
                        return XmlConvert.ToGuid((string)value);
                    case StorageType.Uri:
                        return new Uri((string)value);
                    }
                }
            }
            return Convert.ChangeType(value, type, formatProvider);
        }
        }
    }
References System.Convert.ChangeType(), System.Data.ExceptionBuilder.ConvertFailed(), System.Data.Common.SqlConvert.ConvertToSqlBinary(), System.Data.Common.SqlConvert.ConvertToSqlBoolean(), System.Data.Common.SqlConvert.ConvertToSqlByte(), System.Data.Common.SqlConvert.ConvertToSqlBytes(), System.Data.Common.SqlConvert.ConvertToSqlChars(), System.Data.Common.SqlConvert.ConvertToSqlDateTime(), System.Data.Common.SqlConvert.ConvertToSqlDecimal(), System.Data.Common.SqlConvert.ConvertToSqlDouble(), System.Data.Common.SqlConvert.ConvertToSqlGuid(), System.Data.Common.SqlConvert.ConvertToSqlInt16(), System.Data.Common.SqlConvert.ConvertToSqlInt32(), System.Data.Common.SqlConvert.ConvertToSqlInt64(), System.Data.Common.SqlConvert.ConvertToSqlMoney(), System.Data.Common.SqlConvert.ConvertToSqlSingle(), System.Data.Common.SqlConvert.ConvertToSqlString(), System.Xml.Dictionary, System.Data.Common.DataStorage.GetStorageType(), System.Type.GetType(), System.Data.Common.TimeSpan, System.Xml.XmlConvert.ToGuid(), System.Xml.XmlConvert.ToString(), System.Xml.XmlConvert.ToTimeSpan(), System.type, System.Data.Common.Uri, System.DBNull.Value, and System.value.
Referenced by System.Data.Common.SqlConvert.ChangeTypeForDefaultValue(), System.Data.Select.Eval(), System.Data.LikeNode.Eval(), System.Data.FunctionNode.EvalFunction(), System.Data.DataExpression.Evaluate(), and System.Data.AutoIncrementInt64.SetCurrentAndIncrement().