Terraria: System.Data.Common.SqlConvert.ConvertToSqlString
ConvertToSqlString()
static SqlString System.Data.Common.SqlConvert.ConvertToSqlString (object value) inline static
Definition at line 256 of file SqlConvert.cs.
    {
        if (value == DBNull.Value || value == null)
        {
            return SqlString.Null;
        }
        Type type = value.GetType();
        return DataStorage.GetStorageType(type) switch
        {
            StorageType.SqlString => (SqlString)value,
            StorageType.String => (string)value,
            _ => throw ExceptionBuilder.ConvertFailed(type, typeof(SqlString)),
        };
    }
References System.Data.ExceptionBuilder.ConvertFailed(), System.Xml.Dictionary, System.Data.Common.DataStorage.GetStorageType(), System.Type.GetType(), System.Data.SqlTypes.SqlString.Null, System.Data.Common.SqlString, System.type, System.DBNull.Value, and System.value.
Referenced by System.Data.Common.SqlConvert.ChangeType2(), System.Data.Common.SqlStringStorage.ConvertValue(), System.Data.BinaryNode.EvalBinaryOp(), and System.Data.Common.SqlStringStorage.Set().