Terraria: System.Data.Common.SqlConvert.ConvertToSqlDouble
ConvertToSqlDouble()
static SqlDouble System.Data.Common.SqlConvert.ConvertToSqlDouble (object value) inline static
Definition at line 85 of file SqlConvert.cs.
    {
        if (value == DBNull.Value)
        {
            return SqlDouble.Null;
        }
        Type type = value.GetType();
        return DataStorage.GetStorageType(type) switch
        {
            StorageType.SqlDouble => (SqlDouble)value,
            StorageType.Double => (double)value,
            StorageType.SqlInt64 => (SqlInt64)value,
            StorageType.Int64 => (long)value,
            StorageType.UInt64 => (ulong)value,
            StorageType.SqlInt16 => (SqlInt16)value,
            StorageType.Int16 => (short)value,
            StorageType.UInt16 => (int)(ushort)value,
            StorageType.SqlInt32 => (SqlInt32)value,
            StorageType.Int32 => (int)value,
            StorageType.UInt32 => (uint)value,
            StorageType.SqlByte => (SqlByte)value,
            StorageType.Byte => (int)(byte)value,
            StorageType.SqlSingle => (SqlSingle)value,
            StorageType.Single => (float)value,
            StorageType.SqlMoney => (SqlMoney)value,
            StorageType.SqlDecimal => (SqlDecimal)value,
            _ => throw ExceptionBuilder.ConvertFailed(type, typeof(SqlDouble)),
        };
    }
References System.Data.ExceptionBuilder.ConvertFailed(), System.Xml.Dictionary, System.Data.Common.DataStorage.GetStorageType(), System.Type.GetType(), System.Data.SqlTypes.SqlDouble.Null, System.Data.Common.SqlByte, System.Data.Common.SqlDecimal, System.Data.Common.SqlDouble, System.Data.Common.SqlInt64, System.type, System.DBNull.Value, and System.value.
Referenced by System.Data.BinaryNode.BinaryCompare(), System.Data.Common.SqlConvert.ChangeType2(), System.Data.Common.SqlDoubleStorage.ConvertValue(), System.Data.BinaryNode.EvalBinaryOp(), and System.Data.Common.SqlDoubleStorage.Set().