Terraria: System.Data.Common.SqlConvert.ConvertToSqlBinary
ConvertToSqlBinary()
static SqlBinary System.Data.Common.SqlConvert.ConvertToSqlBinary (object value) inline static
Definition at line 241 of file SqlConvert.cs.
    {
        if (value == DBNull.Value)
        {
            return SqlBinary.Null;
        }
        Type type = value.GetType();
        return DataStorage.GetStorageType(type) switch
        {
            StorageType.SqlBinary => (SqlBinary)value,
            StorageType.ByteArray => (byte[])value,
            _ => throw ExceptionBuilder.ConvertFailed(type, typeof(SqlBinary)),
        };
    }
References System.Data.ExceptionBuilder.ConvertFailed(), System.Xml.Dictionary, System.Data.Common.DataStorage.GetStorageType(), System.Type.GetType(), System.Data.SqlTypes.SqlBinary.Null, System.Data.Common.SqlBinary, System.type, System.DBNull.Value, and System.value.
Referenced by System.Data.BinaryNode.BinaryCompare(), System.Data.Common.SqlConvert.ChangeType2(), System.Data.Common.SqlBinaryStorage.ConvertValue(), and System.Data.Common.SqlBinaryStorage.Set().