Terraria: System.Data.Common.SqlConvert.ConvertToSqlDecimal
ConvertToSqlDecimal()
static SqlDecimal System.Data.Common.SqlConvert.ConvertToSqlDecimal (object value) inline static
Definition at line 115 of file SqlConvert.cs.
    {
        if (value == DBNull.Value)
        {
            return SqlDecimal.Null;
        }
        Type type = value.GetType();
        return DataStorage.GetStorageType(type) switch
        {
            StorageType.SqlDecimal => (SqlDecimal)value,
            StorageType.Decimal => (decimal)value,
            StorageType.SqlInt64 => (SqlInt64)value,
            StorageType.Int64 => (long)value,
            StorageType.UInt64 => (ulong)value,
            StorageType.SqlInt16 => (SqlInt16)value,
            StorageType.Int16 => (short)value,
            StorageType.UInt16 => (ushort)value,
            StorageType.SqlInt32 => (SqlInt32)value,
            StorageType.Int32 => (int)value,
            StorageType.UInt32 => (uint)value,
            StorageType.SqlByte => (SqlByte)value,
            StorageType.Byte => (byte)value,
            StorageType.SqlMoney => (SqlMoney)value,
            _ => throw ExceptionBuilder.ConvertFailed(type, typeof(SqlDecimal)),
        };
    }
References System.Data.ExceptionBuilder.ConvertFailed(), System.Xml.Dictionary, System.Data.Common.DataStorage.GetStorageType(), System.Type.GetType(), System.Data.SqlTypes.SqlDecimal.Null, System.Data.Common.SqlDecimal, System.Data.Common.SqlInt32, System.Data.Common.SqlInt64, System.type, System.DBNull.Value, and System.value.
Referenced by System.Data.BinaryNode.BinaryCompare(), System.Data.Common.SqlConvert.ChangeType2(), System.Data.Common.SqlDecimalStorage.ConvertValue(), System.Data.BinaryNode.EvalBinaryOp(), and System.Data.Common.SqlDecimalStorage.Set().