Terraria: System.Data.Common.SqlConvert.ChangeTypeForXML
ChangeTypeForXML()
static object System.Data.Common.SqlConvert.ChangeTypeForXML (object value, Type type) inline static
Definition at line 497 of file SqlConvert.cs.
    {
        StorageType storageType = DataStorage.GetStorageType(type);
        Type type2 = value.GetType();
        StorageType storageType2 = DataStorage.GetStorageType(type2);
        switch (storageType)
        {
        case StorageType.SqlBinary:
            return new SqlBinary(Convert.FromBase64String((string)value));
        case StorageType.SqlBoolean:
            return new SqlBoolean(XmlConvert.ToBoolean((string)value));
        case StorageType.SqlByte:
            return new SqlByte(XmlConvert.ToByte((string)value));
        case StorageType.SqlBytes:
            return new SqlBytes(Convert.FromBase64String((string)value));
        case StorageType.SqlChars:
            return new SqlChars(((string)value).ToCharArray());
        case StorageType.SqlDateTime:
            return new SqlDateTime(XmlConvert.ToDateTime((string)value, XmlDateTimeSerializationMode.RoundtripKind));
        case StorageType.SqlDecimal:
            return SqlDecimal.Parse((string)value);
        case StorageType.SqlDouble:
            return new SqlDouble(XmlConvert.ToDouble((string)value));
        case StorageType.SqlGuid:
            return new SqlGuid(XmlConvert.ToGuid((string)value));
        case StorageType.SqlInt16:
            return new SqlInt16(XmlConvert.ToInt16((string)value));
        case StorageType.SqlInt32:
            return new SqlInt32(XmlConvert.ToInt32((string)value));
        case StorageType.SqlInt64:
            return new SqlInt64(XmlConvert.ToInt64((string)value));
        case StorageType.SqlMoney:
            return new SqlMoney(XmlConvert.ToDecimal((string)value));
        case StorageType.SqlSingle:
            return new SqlSingle(XmlConvert.ToSingle((string)value));
        case StorageType.SqlString:
            return new SqlString((string)value);
        case StorageType.Boolean:
            if ("1" == (string)value)
            {
                return true;
            }
            if ("0" == (string)value)
            {
                return false;
            }
            return XmlConvert.ToBoolean((string)value);
        case StorageType.Char:
            return XmlConvert.ToChar((string)value);
        case StorageType.SByte:
            return XmlConvert.ToSByte((string)value);
        case StorageType.Byte:
            return XmlConvert.ToByte((string)value);
        case StorageType.Int16:
            return XmlConvert.ToInt16((string)value);
        case StorageType.UInt16:
            return XmlConvert.ToUInt16((string)value);
        case StorageType.Int32:
            return XmlConvert.ToInt32((string)value);
        case StorageType.UInt32:
            return XmlConvert.ToUInt32((string)value);
        case StorageType.Int64:
            return XmlConvert.ToInt64((string)value);
        case StorageType.UInt64:
            return XmlConvert.ToUInt64((string)value);
        case StorageType.Single:
            return XmlConvert.ToSingle((string)value);
        case StorageType.Double:
            return XmlConvert.ToDouble((string)value);
        case StorageType.Decimal:
            return XmlConvert.ToDecimal((string)value);
        case StorageType.DateTime:
            return XmlConvert.ToDateTime((string)value, XmlDateTimeSerializationMode.RoundtripKind);
        case StorageType.Guid:
            return XmlConvert.ToGuid((string)value);
        case StorageType.Uri:
            return new Uri((string)value);
        case StorageType.DateTimeOffset:
            return XmlConvert.ToDateTimeOffset((string)value);
        case StorageType.TimeSpan:
            return storageType2 switch
            {
                StorageType.String => XmlConvert.ToTimeSpan((string)value),
                StorageType.Int32 => new TimeSpan((int)value),
                StorageType.Int64 => new TimeSpan((long)value),
                _ => (TimeSpan)value,
            };
        default:
            if (DBNull.Value == value || value == null)
            {
                return DBNull.Value;
            }
            switch (storageType2)
            {
            case StorageType.SqlBinary:
                return Convert.ToBase64String(((SqlBinary)value).Value);
            case StorageType.SqlBoolean:
                return XmlConvert.ToString(((SqlBoolean)value).Value);
            case StorageType.SqlByte:
                return XmlConvert.ToString(((SqlByte)value).Value);
            case StorageType.SqlBytes:
                return Convert.ToBase64String(((SqlBytes)value).Value);
            case StorageType.SqlChars:
                return new string(((SqlChars)value).Value);
            case StorageType.SqlDateTime:
                return XmlConvert.ToString(((SqlDateTime)value).Value, XmlDateTimeSerializationMode.RoundtripKind);
            case StorageType.SqlDecimal:
                return ((SqlDecimal)value).ToString();
            case StorageType.SqlDouble:
                return XmlConvert.ToString(((SqlDouble)value).Value);
            case StorageType.SqlGuid:
                return XmlConvert.ToString(((SqlGuid)value).Value);
            case StorageType.SqlInt16:
                return XmlConvert.ToString(((SqlInt16)value).Value);
            case StorageType.SqlInt32:
                return XmlConvert.ToString(((SqlInt32)value).Value);
            case StorageType.SqlInt64:
                return XmlConvert.ToString(((SqlInt64)value).Value);
            case StorageType.SqlMoney:
                return XmlConvert.ToString(((SqlMoney)value).Value);
            case StorageType.SqlSingle:
                return XmlConvert.ToString(((SqlSingle)value).Value);
            case StorageType.SqlString:
                return ((SqlString)value).Value;
            case StorageType.Boolean:
                return XmlConvert.ToString((bool)value);
            case StorageType.Char:
                return XmlConvert.ToString((char)value);
            case StorageType.SByte:
                return XmlConvert.ToString((sbyte)value);
            case StorageType.Byte:
                return XmlConvert.ToString((byte)value);
            case StorageType.Int16:
                return XmlConvert.ToString((short)value);
            case StorageType.UInt16:
                return XmlConvert.ToString((ushort)value);
            case StorageType.Int32:
                return XmlConvert.ToString((int)value);
            case StorageType.UInt32:
                return XmlConvert.ToString((uint)value);
            case StorageType.Int64:
                return XmlConvert.ToString((long)value);
            case StorageType.UInt64:
                return XmlConvert.ToString((ulong)value);
            case StorageType.Single:
                return XmlConvert.ToString((float)value);
            case StorageType.Double:
                return XmlConvert.ToString((double)value);
            case StorageType.Decimal:
                return XmlConvert.ToString((decimal)value);
            case StorageType.DateTime:
                return XmlConvert.ToString((DateTime)value, XmlDateTimeSerializationMode.RoundtripKind);
            case StorageType.TimeSpan:
                return XmlConvert.ToString((TimeSpan)value);
            case StorageType.Guid:
                return XmlConvert.ToString((Guid)value);
            case StorageType.String:
                return (string)value;
            case StorageType.CharArray:
                return new string((char[])value);
            case StorageType.DateTimeOffset:
                return XmlConvert.ToString((DateTimeOffset)value);
            default:
                if (value is IConvertible convertible)
                {
                    return convertible.ToString(CultureInfo.InvariantCulture);
                }
                if (value is IFormattable formattable)
                {
                    return formattable.ToString(null, CultureInfo.InvariantCulture);
                }
                return value.ToString();
            }
        }
    }
References System.Xml.Dictionary, System.Convert.FromBase64String(), System.Data.Common.DataStorage.GetStorageType(), System.Type.GetType(), System.Globalization.CultureInfo.InvariantCulture, System.Data.SqlTypes.SqlDecimal.Parse(), System.Data.Common.SqlBinary, System.Data.Common.SqlBoolean, System.Data.Common.SqlByte, System.Data.Common.SqlBytes, System.Data.Common.SqlChars, System.Data.Common.SqlDateTime, System.Data.Common.SqlDouble, System.Data.Common.SqlGuid, System.Data.Common.SqlInt16, System.Data.Common.SqlInt32, System.Data.Common.SqlInt64, System.Data.Common.SqlMoney, System.Data.Common.SqlSingle, System.Data.Common.SqlString, System.Data.Common.TimeSpan, System.Convert.ToBase64String(), System.Xml.XmlConvert.ToBoolean(), System.Xml.XmlConvert.ToByte(), System.Xml.XmlConvert.ToChar(), System.Xml.XmlConvert.ToDateTime(), System.Xml.XmlConvert.ToDateTimeOffset(), System.Xml.XmlConvert.ToDecimal(), System.Xml.XmlConvert.ToDouble(), System.Xml.XmlConvert.ToGuid(), System.Xml.XmlConvert.ToInt16(), System.Xml.XmlConvert.ToInt32(), System.Xml.XmlConvert.ToInt64(), System.Xml.XmlConvert.ToSByte(), System.Xml.XmlConvert.ToSingle(), System.Xml.XmlConvert.ToString(), System.Xml.XmlConvert.ToTimeSpan(), System.Xml.XmlConvert.ToUInt16(), System.Xml.XmlConvert.ToUInt32(), System.Xml.XmlConvert.ToUInt64(), System.type, System.Data.Common.Uri, System.DBNull.Value, and System.value.
Referenced by System.Data.XmlTreeGen.AddExtendedProperties(), System.Data.Common.ObjectStorage.ConvertObjectToXml(), System.Data.Common.ObjectStorage.ConvertXmlToObject(), and System.Data.XDRSchema.HandleColumn().