Terraria: System.Xml.Serialization.ReflectionXmlSerializationReader.WriteDerivedTypes
WriteDerivedTypes()
bool System.Xml.Serialization.ReflectionXmlSerializationReader.WriteDerivedTypes (out object o, StructMapping mapping, XmlQualifiedName xsiType, string defaultNamespace, bool checkType, bool isNullable) inline private
Definition at line 1626 of file ReflectionXmlSerializationReader.cs.
    {
        for (StructMapping structMapping = mapping.DerivedMappings; structMapping != null; structMapping = structMapping.NextDerivedMapping)
        {
            if (QNameEqual(xsiType, structMapping.TypeName, structMapping.Namespace, defaultNamespace))
            {
                o = WriteStructMethod(structMapping, isNullable, checkType, defaultNamespace);
                return true;
            }
            if (WriteDerivedTypes(out o, structMapping, xsiType, defaultNamespace, checkType, isNullable))
            {
                return true;
            }
        }
        o = null;
        return false;
    }
References System.Xml.Serialization.ReflectionXmlSerializationReader.QNameEqual(), System.Xml.Serialization.ReflectionXmlSerializationReader.WriteDerivedTypes(), and System.Xml.Serialization.ReflectionXmlSerializationReader.WriteStructMethod().
Referenced by System.Xml.Serialization.ReflectionXmlSerializationReader.WriteDerivedTypes(), and System.Xml.Serialization.ReflectionXmlSerializationReader.WriteLiteralStructMethod().