Terraria: System.Xml.Serialization.ReflectionXmlSerializationReader.WriteMemberText
WriteMemberText()
bool System.Xml.Serialization.ReflectionXmlSerializationReader.WriteMemberText (Member anyText) inline private
Definition at line 662 of file ReflectionXmlSerializationReader.cs.
    {
        MemberMapping mapping = anyText.Mapping;
        if (base.Reader.NodeType == XmlNodeType.Text || base.Reader.NodeType == XmlNodeType.CDATA || base.Reader.NodeType == XmlNodeType.Whitespace || base.Reader.NodeType == XmlNodeType.SignificantWhitespace)
        {
            TextAccessor text = mapping.Text;
            object obj;
            if (text.Mapping is SpecialMapping specialMapping)
            {
                if (specialMapping.TypeDesc.Kind != TypeKind.Node)
                {
                    throw new InvalidOperationException(System.SR.XmlInternalError);
                }
                obj = base.Document.CreateTextNode(base.Reader.ReadString());
            }
            else
            {
                obj = (mapping.TypeDesc.IsArrayLike ? ((!text.Mapping.TypeDesc.CollapseWhitespace) ? base.Reader.ReadString() : CollapseWhitespace(base.Reader.ReadString())) : ((text.Mapping.TypeDesc != StringTypeDesc && !(text.Mapping.TypeDesc.FormatterName == "String")) ? WritePrimitive(text.Mapping, (object state) => ((ReflectionXmlSerializationReader)state).Reader.ReadString(), this) : ReadString(null, text.Mapping.TypeDesc.CollapseWhitespace)));
            }
            anyText.Source(obj);
            return true;
        }
        return false;
    }
References System.Xml.Serialization.CollapseWhitespace, System.Xml.Dictionary, System.obj, System.Xml.Serialization.XmlSerializationReader.ReadString(), System.state, System.Xml.Serialization.ReflectionXmlSerializationReader.StringTypeDesc, System.text, System.Xml.Serialization.ReflectionXmlSerializationReader.WritePrimitive(), and System.SR.XmlInternalError.
Referenced by System.Xml.Serialization.ReflectionXmlSerializationReader.WriteMemberElements().