Terraria: System.Xml.Serialization.ReflectionXmlSerializationReader.WriteLiteralStructMethod
WriteLiteralStructMethod()
object System.Xml.Serialization.ReflectionXmlSerializationReader.WriteLiteralStructMethod (StructMapping structMapping, bool isNullable, bool checkType, string defaultNamespace) inline private
Definition at line 1357 of file ReflectionXmlSerializationReader.cs.
    {
        XmlQualifiedName xmlQualifiedName = (checkType ? GetXsiType() : null);
        bool flag = false;
        if (isNullable)
        {
            flag = ReadNull();
        }
        if (checkType)
        {
            if (structMapping.TypeDesc.IsRoot && flag)
            {
                if (xmlQualifiedName != null)
                {
                    return ReadTypedNull(xmlQualifiedName);
                }
                if (structMapping.TypeDesc.IsValueType)
                {
                    return ReflectionCreateObject(structMapping.TypeDesc.Type);
                }
                return null;
            }
            object o2 = null;
            if (!(xmlQualifiedName == null) && (structMapping.TypeDesc.IsRoot || !QNameEqual(xmlQualifiedName, structMapping.TypeName, structMapping.Namespace, defaultNamespace)))
            {
                if (WriteDerivedTypes(out o2, structMapping, xmlQualifiedName, defaultNamespace, checkType, isNullable))
                {
                    return o2;
                }
                if (structMapping.TypeDesc.IsRoot && WriteEnumAndArrayTypes(out o2, structMapping, xmlQualifiedName, defaultNamespace))
                {
                    return o2;
                }
                if (structMapping.TypeDesc.IsRoot)
                {
                    return ReadTypedPrimitive(xmlQualifiedName);
                }
                throw CreateUnknownTypeException(xmlQualifiedName);
            }
            if (structMapping.TypeDesc.IsRoot)
            {
                return ReadTypedPrimitive(new XmlQualifiedName("anyType", "http://www.w3.org/2001/XMLSchema"));
            }
        }
        if (structMapping.TypeDesc.IsNullable && flag)
        {
            return null;
        }
        if (structMapping.TypeDesc.IsAbstract)
        {
            throw CreateAbstractTypeException(structMapping.TypeName, structMapping.Namespace);
        }
        if (structMapping.TypeDesc.Type != null && typeof(XmlSchemaObject).IsAssignableFrom(structMapping.TypeDesc.Type))
        {
            throw new NotImplementedException("XmlSchemaObject");
        }
        object o = ReflectionCreateObject(structMapping.TypeDesc.Type);
        MemberMapping[] settableMembers = TypeScope.GetSettableMembers(structMapping);
        MemberMapping memberMapping = null;
        MemberMapping memberMapping2 = null;
        Member anyAttribute = null;
        Member anyElement = null;
        Member anyText = null;
        bool flag2 = structMapping.HasExplicitSequence();
        List<Member> list = new List<Member>(settableMembers.Length);
        List<MemberMapping> list2 = new List<MemberMapping>(settableMembers.Length);
        foreach (MemberMapping memberMapping3 in settableMembers)
        {
            Member member = new Member(memberMapping3);
            if (memberMapping3.Text != null)
            {
                memberMapping = memberMapping3;
            }
            if (memberMapping3.Attribute != null)
            {
                member.Source = Wrapper;
                if (memberMapping3.Attribute.Any)
                {
                    anyAttribute = member;
                }
            }
            if (!flag2)
            {
                for (int j = 0; j < memberMapping3.Elements.Length; j++)
                {
                    if (memberMapping3.Elements[j].Any && (memberMapping3.Elements[j].Name == null || memberMapping3.Elements[j].Name.Length == 0))
                    {
                        memberMapping2 = memberMapping3;
                        break;
                    }
                }
            }
            else if (memberMapping3.IsParticle && !memberMapping3.IsSequence)
            {
                structMapping.FindDeclaringMapping(memberMapping3, out var declaringMapping, structMapping.TypeName);
                throw new InvalidOperationException(System.SR.Format(System.SR.XmlSequenceHierarchy, structMapping.TypeDesc.FullName, memberMapping3.Name, declaringMapping.TypeDesc.FullName, "Order"));
            }
            if (memberMapping3.TypeDesc.IsArrayLike)
            {
                if (member.Source == null && memberMapping3.TypeDesc.IsArrayLike && (memberMapping3.Elements.Length != 1 || !(memberMapping3.Elements[0].Mapping is ArrayMapping)))
                {
                    member.Source = delegate(object item)
                    {
                        if (member.Collection == null)
{
                            member.Collection = new CollectionMember();
                        }
                        member.Collection.Add(item);
                    };
                    member.ArraySource = member.Source;
                }
                else
                {
                    _ = memberMapping3.TypeDesc.IsArray;
                }
            }
            if (member.Source == null)
            {
                PropertyInfo pi = member.Mapping.MemberInfo as PropertyInfo;
                if (pi != null && typeof(IList).IsAssignableFrom(pi.PropertyType) && (pi.SetMethod == null || !pi.SetMethod.IsPublic))
                {
                    member.Source = delegate(object value)
                    {
                        IList list3 = (IList)pi.GetValue(o);
                        if (value is IList list4)
{
{
                                foreach (object item in list4)
{
                                    list3.Add(item);
                                }
                                return;
                            }
                        }
                        list3.Add(value);
                    };
                }
                else if (member.Mapping.Xmlns != null)
                {
                    XmlSerializerNamespaces xmlSerializerNamespaces = new XmlSerializerNamespaces();
                    ReflectionXmlSerializationReaderHelper.SetMemberValueDelegate setMemberValueDelegate = GetSetMemberValueDelegate(o, member.Mapping.Name);
                    setMemberValueDelegate(o, xmlSerializerNamespaces);
                    member.XmlnsSource = delegate(string ns, string name)
                    {
                        xmlSerializerNamespaces.Add(ns, name);
                    };
                }
                else
                {
                    ReflectionXmlSerializationReaderHelper.SetMemberValueDelegate setterDelegate = GetSetMemberValueDelegate(o, member.Mapping.Name);
                    member.Source = delegate(object value)
                    {
                        setterDelegate(o, value);
                    };
                }
            }
            if (member.Mapping.CheckSpecified == SpecifiedAccessor.ReadWrite)
            {
                member.CheckSpecifiedSource = Wrapper;
            }
            ChoiceIdentifierAccessor choice = memberMapping3.ChoiceIdentifier;
            if (choice != null && o != null)
            {
                member.ChoiceSource = Wrapper;
            }
            list2.Add(memberMapping3);
            list.Add(member);
            if (memberMapping3 == memberMapping2)
            {
                anyElement = member;
            }
            else if (memberMapping3 == memberMapping)
            {
                anyText = member;
            }
            [RequiresUnreferencedCode("calls SetOrAddValueToMember")]
            void Wrapper(object value)
            {
                SetOrAddValueToMember(o, value, member.Mapping.MemberInfo);
            }
            [RequiresUnreferencedCode("calls GetType on object")]
            void Wrapper(object _)
            {
                string text3 = member.Mapping.Name + "Specified";
                MethodInfo method = o.GetType().GetMethod("set_" + text3);
                if (method != null)
                {
                    method.Invoke(o, new object[1] { true });
                }
            }
            [RequiresUnreferencedCode("Calls SetOrAddValueToMember")]
            void Wrapper(object elementNameObject)
            {
                string text = elementNameObject as string;
                string[] memberIds = choice.MemberIds;
                foreach (string text2 in memberIds)
                {
                    if (text2 == text)
                    {
                        object value2 = Enum.Parse(choice.Mapping.TypeDesc.Type, text2);
                        SetOrAddValueToMember(o, value2, choice.MemberInfo);
                        break;
                    }
                }
            }
        }
        Member[] array = list.ToArray();
        UnknownNodeAction unknownNodeAction = delegate
        {
            UnknownNode(o);
        };
        WriteAttributes(array, anyAttribute, unknownNodeAction, ref o);
        base.Reader.MoveToElement();
        if (base.Reader.IsEmptyElement)
        {
            base.Reader.Skip();
            return o;
        }
        base.Reader.ReadStartElement();
        bool flag3 = IsSequence(array);
        WriteMembers(ref o, array, unknownNodeAction, unknownNodeAction, anyElement, anyText);
        Member[] array2 = array;
        foreach (Member member2 in array2)
        {
            if (member2.Collection != null)
            {
                MemberInfo[] member3 = o.GetType().GetMember(member2.Mapping.Name);
                MemberInfo memberInfo = member3[0];
                object collection = null;
                SetCollectionObjectWithCollectionMember(ref collection, member2.Collection, member2.Mapping.TypeDesc.Type);
                ReflectionXmlSerializationReaderHelper.SetMemberValueDelegate setMemberValueDelegate2 = GetSetMemberValueDelegate(o, memberInfo.Name);
                setMemberValueDelegate2(o, collection);
            }
        }
        ReadEndElement();
        return o;
    }
References System.Collections.Generic.List< T >.Add(), System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.array, System.Xml.Serialization.MemberMapping.CheckSpecified, System.collection, System.Xml.Serialization.ReflectionXmlSerializationReader.Member.Collection, System.Xml.Serialization.XmlSerializationReader.CreateAbstractTypeException(), System.Xml.Serialization.XmlSerializationReader.CreateUnknownTypeException(), System.Xml.Dictionary, System.SR.Format(), System.Xml.Serialization.ReflectionXmlSerializationReader.GetSetMemberValueDelegate(), System.Xml.Serialization.TypeScope.GetSettableMembers(), System.Xml.Serialization.XmlSerializationReader.GetXsiType(), System.Xml.Serialization.ReflectionXmlSerializationReader.IsSequence(), System.item, System.list, System.Xml.Serialization.ReflectionXmlSerializationReader.Member.Mapping, System.Xml.Serialization.MemberMapping.MemberInfo, System.Xml.Serialization.MemberMapping.Name, System.Enum.Parse(), System.Xml.Serialization.ReflectionXmlSerializationReader.QNameEqual(), System.Xml.Serialization.XmlSerializationReader.ReadEndElement(), System.Xml.Serialization.XmlSerializationReader.ReadNull(), System.Xml.Serialization.XmlSerializationReader.ReadTypedNull(), System.Xml.Serialization.XmlSerializationReader.ReadTypedPrimitive(), System.Xml.Serialization.ReflectionXmlSerializationReader.ReflectionCreateObject(), System.Xml.Serialization.ReflectionXmlSerializationReader.SetCollectionObjectWithCollectionMember(), System.Xml.Serialization.ReflectionXmlSerializationReader.SetOrAddValueToMember(), System.Xml.Serialization.ReflectionXmlSerializationReader.Member.Source, System.text, System.Xml.Serialization.XmlSerializationReader.UnknownNode(), System.Xml.Serialization.UnknownNodeAction(), System.value, System.Xml.Serialization.ReflectionXmlSerializationReader.WriteAttributes(), System.Xml.Serialization.ReflectionXmlSerializationReader.WriteDerivedTypes(), System.Xml.Serialization.ReflectionXmlSerializationReader.WriteEnumAndArrayTypes(), System.Xml.Serialization.ReflectionXmlSerializationReader.WriteMembers(), System.Xml.Serialization.AccessorMapping.Xmlns, and System.SR.XmlSequenceHierarchy.
Referenced by System.Xml.Serialization.ReflectionXmlSerializationReader.WriteStructMethod().