Terraria: System.Xml.Serialization.ReflectionXmlSerializationReader.GenerateLiteralMembersElementInternal
GenerateLiteralMembersElementInternal()
bool System.Xml.Serialization.ReflectionXmlSerializationReader.GenerateLiteralMembersElementInternal (MemberMapping[] mappings, bool hasWrapperElement, object[] p) inline private
Definition at line 165 of file ReflectionXmlSerializationReader.cs.
    {
        Member anyText = null;
        Member anyElement = null;
        Member member = null;
        List<Member> list = new List<Member>();
        List<Member> list2 = new List<Member>();
        List<Member> list3 = new List<Member>();
        for (int i = 0; i < mappings.Length; i++)
        {
            int index = i;
            MemberMapping memberMapping = mappings[index];
            Action<object> source = delegate(object o)
            {
                p[index] = o;
            };
            Member member2 = new Member(memberMapping);
            Member anyMember = new Member(memberMapping);
            if (memberMapping.Xmlns != null)
            {
                XmlSerializerNamespaces xmlns = new XmlSerializerNamespaces();
                p[index] = xmlns;
                member2.XmlnsSource = delegate(string ns, string name)
                {
                    xmlns.Add(ns, name);
                };
            }
            member2.Source = source;
            anyMember.Source = source;
            if (memberMapping.CheckSpecified == SpecifiedAccessor.ReadWrite)
            {
                string text = memberMapping.Name + "Specified";
                for (int j = 0; j < mappings.Length; j++)
                {
                    if (mappings[j].Name == text)
                    {
                        int indexJ = j;
                        member2.CheckSpecifiedSource = delegate(object o)
{
                            p[indexJ] = o;
                        };
                    }
                }
            }
            bool flag = false;
            if (memberMapping.Text != null)
            {
                anyText = anyMember;
            }
            if (memberMapping.Attribute != null && memberMapping.Attribute.Any)
            {
                anyMember.Collection = new CollectionMember();
                anyMember.ArraySource = anyMember.Source;
                anyMember.Source = delegate(object item)
                {
                    anyMember.Collection.Add(item);
                };
                member = anyMember;
            }
            if (memberMapping.Attribute != null || memberMapping.Xmlns != null)
            {
                list3.Add(member2);
            }
            else if (memberMapping.Text != null)
            {
                list2.Add(member2);
            }
            if (!memberMapping.IsSequence)
            {
                for (int k = 0; k < memberMapping.Elements.Length; k++)
                {
                    if (!memberMapping.Elements[k].Any || memberMapping.Elements[k].Name.Length != 0)
                    {
                        continue;
                    }
                    anyElement = anyMember;
                    if (memberMapping.Attribute == null && memberMapping.Text == null)
                    {
                        anyMember.Collection = new CollectionMember();
                        anyMember.ArraySource = delegate(object item)
{
                            anyMember.Collection.Add(item);
                        };
                        list2.Add(anyMember);
                    }
                    flag = true;
                    break;
                }
            }
            if (memberMapping.Attribute != null || memberMapping.Text != null || flag)
            {
                list.Add(anyMember);
            }
            else if (memberMapping.TypeDesc.IsArrayLike && (memberMapping.Elements.Length != 1 || !(memberMapping.Elements[0].Mapping is ArrayMapping)))
            {
                anyMember.Collection = new CollectionMember();
                anyMember.ArraySource = delegate(object item)
                {
                    anyMember.Collection.Add(item);
                };
                list.Add(anyMember);
                list2.Add(anyMember);
            }
            else
            {
                list.Add(member2);
            }
        }
        Member[] array = list.ToArray();
        Member[] array2 = list2.ToArray();
        if (array.Length != 0 && array[0].Mapping.IsReturnValue)
        {
            base.IsReturnValue = true;
        }
        if (list3.Count > 0)
        {
            Member[] members = list3.ToArray();
            object o2 = null;
            WriteAttributes(members, member, base.UnknownNode, ref o2);
            base.Reader.MoveToElement();
        }
        if (hasWrapperElement)
        {
            if (base.Reader.IsEmptyElement)
            {
                base.Reader.Skip();
                base.Reader.MoveToContent();
                return false;
            }
            base.Reader.ReadStartElement();
        }
        base.Reader.MoveToContent();
        while (base.Reader.NodeType != XmlNodeType.EndElement && base.Reader.NodeType != 0)
        {
            WriteMemberElements(array, base.UnknownNode, base.UnknownNode, anyElement, anyText);
            base.Reader.MoveToContent();
        }
        Member[] array3 = array2;
        foreach (Member member3 in array3)
        {
            object collection = null;
            SetCollectionObjectWithCollectionMember(ref collection, member3.Collection, member3.Mapping.TypeDesc.Type);
            member3.Source(collection);
        }
        if (member != null)
        {
            object collection2 = null;
            SetCollectionObjectWithCollectionMember(ref collection2, member.Collection, member.Mapping.TypeDesc.Type);
            member.ArraySource(collection2);
        }
        return true;
    }
References System.Xml.Serialization.XmlSerializerNamespaces.Add(), System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.array, System.collection, System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Xml.Dictionary, System.index, System.item, System.list, System.Xml.Name, System.Xml.Serialization.ReflectionXmlSerializationReader.SetCollectionObjectWithCollectionMember(), System.source, System.text, System.Xml.Serialization.ReflectionXmlSerializationReader.WriteAttributes(), and System.Xml.Serialization.ReflectionXmlSerializationReader.WriteMemberElements().
Referenced by System.Xml.Serialization.ReflectionXmlSerializationReader.GenerateLiteralMembersElement().