Terraria: System.Xml.Serialization.ReflectionXmlSerializationReader.WritePrimitive
WritePrimitive()
object System.Xml.Serialization.ReflectionXmlSerializationReader.WritePrimitive (TypeMapping mapping, Func< object, string > readFunc, object funcState) inline private
Definition at line 1045 of file ReflectionXmlSerializationReader.cs.
    {
        if (mapping is EnumMapping mapping2)
        {
            return WriteEnumMethod(mapping2, readFunc, funcState);
        }
        if (mapping.TypeDesc == StringTypeDesc)
        {
            return readFunc(funcState);
        }
        if (mapping.TypeDesc.FormatterName == "String")
        {
            if (mapping.TypeDesc.CollapseWhitespace)
            {
                return CollapseWhitespace(readFunc(funcState));
            }
            return readFunc(funcState);
        }
        if (!mapping.TypeDesc.HasCustomFormatter)
        {
            string s = readFunc(funcState);
            return mapping.TypeDesc.FormatterName switch
            {
                "Boolean" => XmlConvert.ToBoolean(s),
                "Int32" => XmlConvert.ToInt32(s),
                "Int16" => XmlConvert.ToInt16(s),
                "Int64" => XmlConvert.ToInt64(s),
                "Single" => XmlConvert.ToSingle(s),
                "Double" => XmlConvert.ToDouble(s),
                "Decimal" => XmlConvert.ToDecimal(s),
                "Byte" => XmlConvert.ToByte(s),
                "SByte" => XmlConvert.ToSByte(s),
                "UInt16" => XmlConvert.ToUInt16(s),
                "UInt32" => XmlConvert.ToUInt32(s),
                "UInt64" => XmlConvert.ToUInt64(s),
                "Guid" => XmlConvert.ToGuid(s),
                "Char" => XmlConvert.ToChar(s),
                "TimeSpan" => XmlConvert.ToTimeSpan(s),
                "DateTimeOffset" => XmlConvert.ToDateTimeOffset(s),
                _ => throw new InvalidOperationException(System.SR.Format(System.SR.XmlInternalErrorDetails, "unknown FormatterName: " + mapping.TypeDesc.FormatterName)),
            };
        }
        string name = "To" + mapping.TypeDesc.FormatterName;
        MethodInfo method = typeof(XmlSerializationReader).GetMethod(name, BindingFlags.Instance | BindingFlags.Static | BindingFlags.Public | BindingFlags.NonPublic, new Type[1] { typeof(string) });
        if (method == null)
        {
            throw new InvalidOperationException(System.SR.Format(System.SR.XmlInternalErrorDetails, "unknown FormatterName: " + mapping.TypeDesc.FormatterName));
        }
        return method.Invoke(this, new object[1] { readFunc(funcState) });
    }
References System.Xml.Serialization.CollapseWhitespace, System.Xml.Dictionary, System.SR.Format(), System.s, System.Xml.Serialization.ReflectionXmlSerializationReader.StringTypeDesc, System.Xml.XmlConvert.ToBoolean(), System.Xml.XmlConvert.ToByte(), System.Xml.XmlConvert.ToChar(), System.Xml.XmlConvert.ToDateTimeOffset(), System.Xml.XmlConvert.ToDecimal(), System.Xml.XmlConvert.ToDouble(), System.Xml.XmlConvert.ToGuid(), System.Xml.XmlConvert.ToInt16(), System.Xml.XmlConvert.ToInt32(), System.Xml.XmlConvert.ToInt64(), System.Xml.XmlConvert.ToSByte(), System.Xml.XmlConvert.ToSingle(), System.Xml.XmlConvert.ToTimeSpan(), System.Xml.XmlConvert.ToUInt16(), System.Xml.XmlConvert.ToUInt32(), System.Xml.XmlConvert.ToUInt64(), System.Xml.Serialization.ReflectionXmlSerializationReader.WriteEnumMethod(), and System.SR.XmlInternalErrorDetails.
Referenced by System.Xml.Serialization.ReflectionXmlSerializationReader.WriteAttribute(), System.Xml.Serialization.ReflectionXmlSerializationReader.WriteElement(), and System.Xml.Serialization.ReflectionXmlSerializationReader.WriteMemberText().