Terraria: System.Xml.Serialization.ReflectionXmlSerializationReader.WriteMemberElements
WriteMemberElements()
void System.Xml.Serialization.ReflectionXmlSerializationReader.WriteMemberElements (Member[] expectedMembers, UnknownNodeAction elementElseAction, UnknownNodeAction elseAction, Member anyElement, Member anyText, Fixup fixup = null, List< CheckTypeSource > checkTypeHrefsSource = null) inline private
Definition at line 501 of file ReflectionXmlSerializationReader.cs.
    {
        bool flag = checkTypeHrefsSource != null;
        if (base.Reader.NodeType == XmlNodeType.Element)
        {
            if (flag)
            {
                if (base.Reader.GetAttribute("root", "http://schemas.xmlsoap.org/soap/encoding/") == "0")
                {
                    elementElseAction(null);
                }
                else
                {
                    WriteMemberElementsCheckType(checkTypeHrefsSource);
                }
            }
            else
            {
                WriteMemberElementsIf(expectedMembers, anyElement, elementElseAction, fixup);
            }
        }
        else if (anyText == null || anyText.Mapping == null || !WriteMemberText(anyText))
        {
            ProcessUnknownNode(elseAction);
        }
    }
References System.Xml.Dictionary, System.Xml.Serialization.ReflectionXmlSerializationReader.ProcessUnknownNode(), System.Xml.Serialization.ReflectionXmlSerializationReader.WriteMemberElementsCheckType(), System.Xml.Serialization.ReflectionXmlSerializationReader.WriteMemberElementsIf(), and System.Xml.Serialization.ReflectionXmlSerializationReader.WriteMemberText().
Referenced by System.Xml.Serialization.ReflectionXmlSerializationReader.GenerateEncodedMembersElement(), System.Xml.Serialization.ReflectionXmlSerializationReader.GenerateLiteralMembersElementInternal(), System.Xml.Serialization.ReflectionXmlSerializationReader.GenerateTypeElement(), System.Xml.Serialization.ReflectionXmlSerializationReader.WriteArray(), System.Xml.Serialization.ReflectionXmlSerializationReader.WriteEncodedStructMethod(), and System.Xml.Serialization.ReflectionXmlSerializationReader.WriteMembers().