Terraria: System.Xml.Serialization.ReflectionXmlSerializationReader.WriteArray
WriteArray()
object System.Xml.Serialization.ReflectionXmlSerializationReader.WriteArray (ArrayMapping arrayMapping, bool readOnly, bool isNullable, string defaultNamespace, int fixupIndex = -1, Fixup fixup = null, Member member = null) inline private
Definition at line 979 of file ReflectionXmlSerializationReader.cs.
    {
        object collection = null;
        if (arrayMapping.IsSoap)
        {
            object obj = ((fixupIndex < 0) ? ReadReferencedElement(arrayMapping.TypeName, arrayMapping.Namespace) : ReadReferencingElement(arrayMapping.TypeName, arrayMapping.Namespace, out fixup.Ids[fixupIndex]));
            TypeDesc typeDesc = arrayMapping.TypeDesc;
            if (obj != null)
            {
                if (typeDesc.IsEnumerable || typeDesc.IsCollection)
                {
                    WriteAddCollectionFixup(member.GetSource, member.Source, obj, typeDesc, readOnly);
                    member.Source = NoopAction;
                }
                else
                {
                    if (member == null)
                    {
                        throw new InvalidOperationException(System.SR.XmlInternalError);
                    }
                    member.Source(obj);
                }
            }
            collection = obj;
        }
        else if (!ReadNull())
        {
            MemberMapping memberMapping = new MemberMapping
            {
                Elements = arrayMapping.Elements,
                TypeDesc = arrayMapping.TypeDesc,
                ReadOnly = readOnly
            };
            Type type = memberMapping.TypeDesc.Type;
            collection = ReflectionCreateObject(memberMapping.TypeDesc.Type);
            if (memberMapping.ChoiceIdentifier != null)
            {
                throw new NotImplementedException("memberMapping.ChoiceIdentifier != null");
            }
            Member arrayMember = new Member(memberMapping);
            arrayMember.Collection = new CollectionMember();
            arrayMember.ArraySource = delegate(object item)
            {
                arrayMember.Collection.Add(item);
            };
            if ((readOnly && collection == null) || base.Reader.IsEmptyElement)
            {
                base.Reader.Skip();
            }
            else
            {
                base.Reader.ReadStartElement();
                base.Reader.MoveToContent();
                while (base.Reader.NodeType != XmlNodeType.EndElement && base.Reader.NodeType != 0)
                {
                    WriteMemberElements(new Member[1] { arrayMember }, base.UnknownNode, base.UnknownNode, null, null);
                    base.Reader.MoveToContent();
                }
                ReadEndElement();
            }
            SetCollectionObjectWithCollectionMember(ref collection, arrayMember.Collection, type);
        }
        return collection;
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.collection, System.Xml.Dictionary, System.item, System.Xml.Serialization.ReflectionXmlSerializationReader.NoopAction(), System.obj, System.Xml.Serialization.XmlSerializationReader.ReadEndElement(), System.Xml.Serialization.XmlSerializationReader.ReadNull(), System.Xml.Serialization.ReadOnly, System.Xml.Serialization.XmlSerializationReader.ReadReferencedElement(), System.Xml.Serialization.XmlSerializationReader.ReadReferencingElement(), System.Xml.Serialization.ReflectionXmlSerializationReader.ReflectionCreateObject(), System.Xml.Serialization.ReflectionXmlSerializationReader.SetCollectionObjectWithCollectionMember(), System.type, System.Xml.Serialization.ReflectionXmlSerializationReader.WriteAddCollectionFixup(), System.Xml.Serialization.ReflectionXmlSerializationReader.WriteMemberElements(), and System.SR.XmlInternalError.
Referenced by System.Xml.Serialization.ReflectionXmlSerializationReader.WriteElement(), and System.Xml.Serialization.ReflectionXmlSerializationReader.WriteEnumAndArrayTypes().