Terraria: System.Xml.Serialization.ReflectionXmlSerializationReader.SetCollectionObjectWithCollectionMember
SetCollectionObjectWithCollectionMember()
void System.Xml.Serialization.ReflectionXmlSerializationReader.SetCollectionObjectWithCollectionMember ([NotNull] ref object collection, CollectionMember collectionMember, [DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicConstructors | DynamicallyAccessedMemberTypes.NonPublicConstructors | DynamicallyAccessedMemberTypes.PublicMethods | DynamicallyAccessedMemberTypes.NonPublicMethods)] Type collectionType) inline private
Definition at line 564 of file ReflectionXmlSerializationReader.cs.
    {
        if (collectionType.IsArray)
        {
            Array array2;
            if (collection is Array array && array.Length == collectionMember.Count)
            {
                array2 = array;
            }
            else
            {
                Type elementType = collectionType.GetElementType();
                array2 = Array.CreateInstance(elementType, collectionMember.Count);
            }
            for (int i = 0; i < collectionMember.Count; i++)
            {
                array2.SetValue(collectionMember[i], i);
            }
            collection = array2;
        }
        else
        {
            if (collection == null)
            {
                collection = ReflectionCreateObject(collectionType);
            }
            AddObjectsIntoTargetCollection(collection, collectionMember, collectionType);
        }
    }
References System.Xml.Serialization.ReflectionXmlSerializationReader.AddObjectsIntoTargetCollection(), System.array, System.collection, System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Array.CreateInstance(), System.Xml.Dictionary, System.elementType, System.Array.Length, and System.Xml.Serialization.ReflectionXmlSerializationReader.ReflectionCreateObject().
Referenced by System.Xml.Serialization.ReflectionXmlSerializationReader.GenerateLiteralMembersElementInternal(), System.Xml.Serialization.ReflectionXmlSerializationReader.WriteArray(), and System.Xml.Serialization.ReflectionXmlSerializationReader.WriteLiteralStructMethod().