Terraria: System.Xml.Serialization.ReflectionXmlSerializationReader.GenerateLiteralMembersElement
GenerateLiteralMembersElement()
object System.Xml.Serialization.ReflectionXmlSerializationReader.GenerateLiteralMembersElement (XmlMembersMapping xmlMembersMapping) inline private
Definition at line 127 of file ReflectionXmlSerializationReader.cs.
    {
        ElementAccessor accessor = xmlMembersMapping.Accessor;
        MemberMapping[] members = ((MembersMapping)accessor.Mapping).Members;
        bool hasWrapperElement = ((MembersMapping)accessor.Mapping).HasWrapperElement;
        base.Reader.MoveToContent();
        object[] array = new object[members.Length];
        InitializeValueTypes(array, members);
        if (hasWrapperElement)
        {
            string name = accessor.Name;
            string text = ((accessor.Form == XmlSchemaForm.Qualified) ? accessor.Namespace : string.Empty);
            base.Reader.MoveToContent();
            while (base.Reader.NodeType != XmlNodeType.EndElement && base.Reader.NodeType != 0)
            {
                if (base.Reader.IsStartElement(accessor.Name, text))
                {
                    if (!GenerateLiteralMembersElementInternal(members, hasWrapperElement, array))
                    {
                        continue;
                    }
                    ReadEndElement();
                }
                else
                {
                    UnknownNode(null, text + ":" + name);
                }
                base.Reader.MoveToContent();
            }
        }
        else
        {
            GenerateLiteralMembersElementInternal(members, hasWrapperElement, array);
        }
        return array;
    }
References System.array, System.Xml.Dictionary, System.Xml.Serialization.ReflectionXmlSerializationReader.GenerateLiteralMembersElementInternal(), System.Xml.Serialization.ReflectionXmlSerializationReader.InitializeValueTypes(), System.Xml.Serialization.XmlSerializationReader.ReadEndElement(), System.text, and System.Xml.Serialization.XmlSerializationReader.UnknownNode().
Referenced by System.Xml.Serialization.ReflectionXmlSerializationReader.GenerateMembersElement().