Terraria: System.Xml.Serialization.ReflectionXmlSerializationReader.GetSetMemberValueDelegate
GetSetMemberValueDelegate()
static ReflectionXmlSerializationReaderHelper.SetMemberValueDelegate System.Xml.Serialization.ReflectionXmlSerializationReader.GetSetMemberValueDelegate (object o, string memberName) inline static private
Definition at line 620 of file ReflectionXmlSerializationReader.cs.
    {
        (Type, string) key = (o.GetType(), memberName);
        if (!s_setMemberValueDelegateCache.TryGetValue(key, out var value))
        {
            MemberInfo effectiveSetInfo = ReflectionXmlSerializationHelper.GetEffectiveSetInfo(o.GetType(), memberName);
            Type type;
            if (effectiveSetInfo is PropertyInfo propertyInfo)
            {
                type = propertyInfo.PropertyType;
            }
            else
            {
                if (!(effectiveSetInfo is FieldInfo fieldInfo))
                {
                    throw new InvalidOperationException(System.SR.XmlInternalError);
                }
                type = fieldInfo.FieldType;
            }
            MethodInfo method = typeof(ReflectionXmlSerializationReaderHelper).GetMethod("GetSetMemberValueDelegateWithType", BindingFlags.Static | BindingFlags.Public);
            MethodInfo methodInfo = method.MakeGenericMethod(o.GetType(), type);
            Func<MemberInfo, ReflectionXmlSerializationReaderHelper.SetMemberValueDelegate> func = (Func<MemberInfo, ReflectionXmlSerializationReaderHelper.SetMemberValueDelegate>)methodInfo.CreateDelegate(typeof(Func<MemberInfo, ReflectionXmlSerializationReaderHelper.SetMemberValueDelegate>));
            value = func(effectiveSetInfo);
            s_setMemberValueDelegateCache.TryAdd(key, value);
        }
        return value;
    }
References System.Xml.Dictionary, System.Xml.Serialization.ReflectionXmlSerializationHelper.GetEffectiveSetInfo(), System.key, System.Xml.Serialization.ReflectionXmlSerializationReader.s_setMemberValueDelegateCache, System.Xml.Serialization.ReflectionXmlSerializationReaderHelper.SetMemberValueDelegate(), System.type, System.Xml.Serialization.Type, System.value, and System.SR.XmlInternalError.
Referenced by System.Xml.Serialization.ReflectionXmlSerializationReader.AddItemInArrayMember(), System.Xml.Serialization.ReflectionXmlSerializationReader.SetOrAddValueToMember(), System.Xml.Serialization.ReflectionXmlSerializationReader.WriteAddCollectionFixup(), System.Xml.Serialization.ReflectionXmlSerializationReader.WriteEncodedStructMethod(), and System.Xml.Serialization.ReflectionXmlSerializationReader.WriteLiteralStructMethod().