Terraria: System.Xml.Serialization.ReflectionXmlSerializationReader.CreateXmlSerializationReadCallback
CreateXmlSerializationReadCallback()
XmlSerializationReadCallback System.Xml.Serialization.ReflectionXmlSerializationReader.CreateXmlSerializationReadCallback (TypeMapping mapping) inline private
Definition at line 916 of file ReflectionXmlSerializationReader.cs.
    {
        StructMapping structMapping = mapping as StructMapping;
        if (structMapping != null)
        {
            return WriteStruct;
        }
        EnumMapping enumMapping = mapping as EnumMapping;
        if (enumMapping != null)
        {
            return () => WriteEnumMethodSoap(enumMapping);
        }
        NullableMapping nullableMapping = mapping as NullableMapping;
        if (nullableMapping != null)
        {
            return Wrapper;
        }
        return DummyReadArrayMethod;
        [RequiresUnreferencedCode("calls WriteNullableMethod")]
        object Wrapper()
        {
            return WriteNullableMethod(nullableMapping, checkType: false, null);
        }
        [RequiresUnreferencedCode("calls WriteStructMethod")]
        object WriteStruct()
        {
            return WriteStructMethod(structMapping, mapping.TypeDesc.IsNullable, checkType: true, null);
        }
    }
References System.Xml.Dictionary, System.Xml.Serialization.ReflectionXmlSerializationReader.DummyReadArrayMethod(), System.Xml.Serialization.ReflectionXmlSerializationReader.WriteEnumMethodSoap(), System.Xml.Serialization.ReflectionXmlSerializationReader.WriteNullableMethod(), and System.Xml.Serialization.ReflectionXmlSerializationReader.WriteStructMethod().
Referenced by System.Xml.Serialization.ReflectionXmlSerializationReader.InitCallbacks().