Terraria: System.Xml.Serialization.ReflectionXmlSerializationReader.WriteAttributes
WriteAttributes()
void System.Xml.Serialization.ReflectionXmlSerializationReader.WriteAttributes (Member[] members, Member anyAttribute, UnknownNodeAction elseCall, ref object o) inline private
Definition at line 1645 of file ReflectionXmlSerializationReader.cs.
    {
        Member member = null;
        List<AttributeAccessor> list = new List<AttributeAccessor>();
        foreach (Member member2 in members)
        {
            if (member2.Mapping.Xmlns != null)
            {
                member = member2;
                break;
            }
        }
        while (base.Reader.MoveToNextAttribute())
        {
            bool flag = false;
            foreach (Member member3 in members)
            {
                if (member3.Mapping.Xmlns != null || member3.Mapping.Ignore)
                {
                    continue;
                }
                AttributeAccessor attribute = member3.Mapping.Attribute;
                if (attribute != null && !attribute.Any)
                {
                    list.Add(attribute);
                    flag = ((!attribute.IsSpecialXmlNamespace) ? XmlNodeEqual(base.Reader, attribute.Name, (attribute.Form == XmlSchemaForm.Qualified) ? attribute.Namespace : string.Empty) : XmlNodeEqual(base.Reader, attribute.Name, "http://www.w3.org/XML/1998/namespace"));
                    if (flag)
                    {
                        WriteAttribute(member3);
                        flag = true;
                        break;
                    }
                }
            }
            if (flag)
            {
                continue;
            }
            bool flag2 = false;
            if (member != null)
            {
                if (IsXmlnsAttribute(base.Reader.Name))
                {
                    member.XmlnsSource((base.Reader.Name.Length == 5) ? string.Empty : base.Reader.LocalName, base.Reader.Value);
                }
                else
                {
                    flag2 = true;
                }
            }
            else if (!IsXmlnsAttribute(base.Reader.Name))
            {
                flag2 = true;
            }
            if (flag2)
            {
                if (anyAttribute != null)
                {
                    XmlAttribute attr = base.Document.ReadNode(base.Reader) as XmlAttribute;
                    ParseWsdlArrayType(attr);
                    WriteAttribute(anyAttribute, attr);
                }
                else
                {
                    elseCall(o);
                }
            }
        }
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Xml.Dictionary, System.Xml.Serialization.XmlSerializationReader.IsXmlnsAttribute(), System.list, System.Xml.Serialization.XmlSerializationReader.ParseWsdlArrayType(), System.Xml.Serialization.ReflectionXmlSerializationReader.WriteAttribute(), System.Xml.Serialization.ReflectionXmlSerializationReader.XmlNodeEqual(), and System.Xml.Serialization.ReflectionXmlSerializationReader.Member.XmlnsSource.
Referenced by System.Xml.Serialization.ReflectionXmlSerializationReader.GenerateLiteralMembersElementInternal(), System.Xml.Serialization.ReflectionXmlSerializationReader.WriteEncodedStructMethod(), and System.Xml.Serialization.ReflectionXmlSerializationReader.WriteLiteralStructMethod().