Terraria: System.Xml.Serialization.ReflectionXmlSerializationReader.WriteMemberFixupBegin
WriteMemberFixupBegin()
Fixup System.Xml.Serialization.ReflectionXmlSerializationReader.WriteMemberFixupBegin (Member[] members, object o) inline private
Definition at line 1251 of file ReflectionXmlSerializationReader.cs.
    {
        int num = 0;
        foreach (Member member in members)
        {
            if (member.Mapping.Elements.Length != 0)
            {
                TypeMapping mapping = member.Mapping.Elements[0].Mapping;
                if (mapping is StructMapping || mapping is ArrayMapping || mapping is PrimitiveMapping || mapping is NullableMapping)
                {
                    member.MultiRef = true;
                    member.FixupIndex = num++;
                }
            }
        }
        Fixup fixup;
        if (num > 0)
        {
            fixup = new Fixup(o, CreateWriteFixupMethod(members), num);
            AddFixup(fixup);
        }
        else
        {
            fixup = null;
        }
        return fixup;
    }
References System.Xml.Serialization.XmlSerializationReader.AddFixup(), System.Xml.Serialization.ReflectionXmlSerializationReader.CreateWriteFixupMethod(), System.Xml.Dictionary, System.Xml.Serialization.AccessorMapping.Elements, System.Xml.Serialization.Accessor.Mapping, and System.Xml.Serialization.ReflectionXmlSerializationReader.Member.Mapping.
Referenced by System.Xml.Serialization.ReflectionXmlSerializationReader.GenerateEncodedMembersElement(), and System.Xml.Serialization.ReflectionXmlSerializationReader.WriteEncodedStructMethod().