Terraria: System.Xml.Serialization.ReflectionXmlSerializationReader.GenerateTypeElement
GenerateTypeElement()
object System.Xml.Serialization.ReflectionXmlSerializationReader.GenerateTypeElement (XmlTypeMapping xmlTypeMapping) inline private
Definition at line 472 of file ReflectionXmlSerializationReader.cs.
    {
        ElementAccessor accessor = xmlTypeMapping.Accessor;
        TypeMapping mapping = accessor.Mapping;
        base.Reader.MoveToContent();
        MemberMapping memberMapping = new MemberMapping();
        memberMapping.TypeDesc = mapping.TypeDesc;
        memberMapping.Elements = new ElementAccessor[1] { accessor };
        object obj = null;
        ObjectHolder holder = new ObjectHolder();
        Member member = new Member(memberMapping);
        member.Source = delegate(object value)
        {
            holder.Object = value;
        };
        member.GetSource = () => holder.Object;
        UnknownNodeAction elementElseAction = CreateUnknownNodeException;
        UnknownNodeAction elseAction = base.UnknownNode;
        WriteMemberElements(new Member[1] { member }, elementElseAction, elseAction, accessor.Any ? member : null, null);
        obj = holder.Object;
        if (accessor.IsSoap)
        {
            Referenced(obj);
            ReadReferencedElements();
        }
        return obj;
    }
References System.Xml.Serialization.XmlSerializationReader.CreateUnknownNodeException(), System.Xml.Dictionary, System.obj, System.Xml.Serialization.XmlSerializationReader.ReadReferencedElements(), System.Xml.Serialization.XmlSerializationReader.Referenced(), System.Xml.Serialization.UnknownNodeAction(), System.value, and System.Xml.Serialization.ReflectionXmlSerializationReader.WriteMemberElements().
Referenced by System.Xml.Serialization.ReflectionXmlSerializationReader.ReadObject().