Terraria: System.Xml.Serialization.ReflectionXmlSerializationReader.ReflectionCreateObject
ReflectionCreateObject()
object System.Xml.Serialization.ReflectionXmlSerializationReader.ReflectionCreateObject ([DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicConstructors | DynamicallyAccessedMemberTypes.NonPublicConstructors | DynamicallyAccessedMemberTypes.PublicMethods | DynamicallyAccessedMemberTypes.NonPublicMethods)] Type type) inline private
Definition at line 1162 of file ReflectionXmlSerializationReader.cs.
    {
        if (type.IsArray)
        {
            return Activator.CreateInstance(type, 32);
        }
        ConstructorInfo defaultConstructor = GetDefaultConstructor(type);
        if (defaultConstructor != null)
        {
            return defaultConstructor.Invoke(Array.Empty<object>());
        }
        return Activator.CreateInstance(type);
    }
References System.Activator.CreateInstance(), System.Xml.Serialization.ReflectionXmlSerializationReader.GetDefaultConstructor(), and System.type.
Referenced by System.Xml.Serialization.ReflectionXmlSerializationReader.InitializeValueTypes(), System.Xml.Serialization.ReflectionXmlSerializationReader.SetCollectionObjectWithCollectionMember(), System.Xml.Serialization.ReflectionXmlSerializationReader.WriteAddCollectionFixup(), System.Xml.Serialization.ReflectionXmlSerializationReader.WriteArray(), System.Xml.Serialization.ReflectionXmlSerializationReader.WriteElement(), System.Xml.Serialization.ReflectionXmlSerializationReader.WriteEncodedStructMethod(), and System.Xml.Serialization.ReflectionXmlSerializationReader.WriteLiteralStructMethod().