Terraria: System.Xml.Serialization.ReflectionXmlSerializationReader.WriteEnumAndArrayTypes
WriteEnumAndArrayTypes()
bool System.Xml.Serialization.ReflectionXmlSerializationReader.WriteEnumAndArrayTypes (out object o, StructMapping mapping, XmlQualifiedName xsiType, string defaultNamespace) inline private
Definition at line 1596 of file ReflectionXmlSerializationReader.cs.
    {
        foreach (object typeMapping in _mapping.Scope.TypeMappings)
        {
            if (typeMapping is EnumMapping enumMapping)
            {
                if (QNameEqual(xsiType, enumMapping.TypeName, enumMapping.Namespace, defaultNamespace))
                {
                    base.Reader.ReadStartElement();
                    Func<object, string> readFunc = delegate(object state)
                    {
                        ReflectionXmlSerializationReader reflectionXmlSerializationReader = (ReflectionXmlSerializationReader)state;
                        return reflectionXmlSerializationReader.CollapseWhitespace(reflectionXmlSerializationReader.Reader.ReadString());
                    };
                    o = WriteEnumMethod(enumMapping, readFunc, this);
                    ReadEndElement();
                    return true;
                }
            }
            else if (typeMapping is ArrayMapping arrayMapping && QNameEqual(xsiType, arrayMapping.TypeName, arrayMapping.Namespace, defaultNamespace))
            {
                o = WriteArray(arrayMapping, readOnly: false, isNullable: false, defaultNamespace);
                return true;
            }
        }
        o = null;
        return false;
    }
References System.Xml.Serialization.ReflectionXmlSerializationReader.ReflectionXmlSerializationReader(), System.Xml.Serialization.ReflectionXmlSerializationReader._mapping, System.Xml.Dictionary, System.Xml.Serialization.ReflectionXmlSerializationReader.QNameEqual(), System.Xml.Serialization.XmlSerializationReader.ReadEndElement(), System.Xml.Serialization.XmlMapping.Scope, System.state, System.Xml.Serialization.TypeScope.TypeMappings, System.Xml.Serialization.ReflectionXmlSerializationReader.WriteArray(), and System.Xml.Serialization.ReflectionXmlSerializationReader.WriteEnumMethod().
Referenced by System.Xml.Serialization.ReflectionXmlSerializationReader.WriteLiteralStructMethod().