Terraria: System.Xml.Serialization.ReflectionXmlSerializationReader.AddItemInArrayMember
AddItemInArrayMember()
void System.Xml.Serialization.ReflectionXmlSerializationReader.AddItemInArrayMember (object o, MemberInfo memberInfo, Type memberType, object item) inline private
Definition at line 1776 of file ReflectionXmlSerializationReader.cs.
    {
        Array array = (Array)GetMemberValue(o, memberInfo);
        int num = array?.Length ?? 0;
        Array array2 = Array.CreateInstance(memberType.GetElementType(), num + 1);
        if (array != null)
        {
            Array.Copy(array, array2, num);
        }
        array2.SetValue(item, num);
        ReflectionXmlSerializationReaderHelper.SetMemberValueDelegate setMemberValueDelegate = GetSetMemberValueDelegate(o, memberInfo.Name);
        setMemberValueDelegate(o, array2);
    }
References System.array, System.Xml.Serialization.Array, System.Array.Copy(), System.Array.CreateInstance(), System.Xml.Dictionary, System.Xml.Serialization.ReflectionXmlSerializationReader.GetMemberValue(), System.Xml.Serialization.ReflectionXmlSerializationReader.GetSetMemberValueDelegate(), and System.item.
Referenced by System.Xml.Serialization.ReflectionXmlSerializationReader.SetOrAddValueToMember().