Terraria: System.Xml.Serialization.ReflectionXmlSerializationReader.GenerateEncodedMembersElement
GenerateEncodedMembersElement()
object System.Xml.Serialization.ReflectionXmlSerializationReader.GenerateEncodedMembersElement (XmlMembersMapping xmlMembersMapping) inline private
Definition at line 337 of file ReflectionXmlSerializationReader.cs.
    {
        ElementAccessor accessor = xmlMembersMapping.Accessor;
        MembersMapping membersMapping = (MembersMapping)accessor.Mapping;
        MemberMapping[] members = membersMapping.Members;
        bool hasWrapperElement = membersMapping.HasWrapperElement;
        bool writeAccessors = membersMapping.WriteAccessors;
        base.Reader.MoveToContent();
        object[] p = new object[members.Length];
        InitializeValueTypes(p, members);
        bool flag = true;
        if (hasWrapperElement)
        {
            base.Reader.MoveToContent();
            while (base.Reader.NodeType == XmlNodeType.Element)
            {
                string attribute = base.Reader.GetAttribute("root", "http://schemas.xmlsoap.org/soap/encoding/");
                if (attribute == null || XmlConvert.ToBoolean(attribute))
                {
                    break;
                }
                ReadReferencedElement();
                base.Reader.MoveToContent();
            }
            if (membersMapping.ValidateRpcWrapperElement)
            {
                string name = accessor.Name;
                string ns = ((accessor.Form == XmlSchemaForm.Qualified) ? accessor.Namespace : string.Empty);
                if (!XmlNodeEqual(base.Reader, name, ns))
                {
                    throw CreateUnknownNodeException();
                }
            }
            flag = base.Reader.IsEmptyElement;
            base.Reader.ReadStartElement();
        }
        Member[] array = new Member[members.Length];
        for (int i = 0; i < members.Length; i++)
        {
            int index = i;
            MemberMapping memberMapping = members[index];
            Member member = new Member(memberMapping);
            member.Source = delegate(object value)
            {
                p[index] = value;
            };
            array[index] = member;
            if (memberMapping.CheckSpecified != SpecifiedAccessor.ReadWrite)
            {
                continue;
            }
            string text = memberMapping.Name + "Specified";
            for (int j = 0; j < members.Length; j++)
            {
                if (members[j].Name == text)
                {
                    int indexOfSpecifiedMember = j;
                    member.CheckSpecifiedSource = delegate(object value)
                    {
                        p[indexOfSpecifiedMember] = value;
                    };
                    break;
                }
            }
        }
        Fixup fixup = WriteMemberFixupBegin(array, p);
        if (array.Length != 0 && array[0].Mapping.IsReturnValue)
        {
            base.IsReturnValue = true;
        }
        List<CheckTypeSource> list = null;
        if (!hasWrapperElement && !writeAccessors)
        {
            list = new List<CheckTypeSource>();
        }
        base.Reader.MoveToContent();
        while (base.Reader.NodeType != XmlNodeType.EndElement && base.Reader.NodeType != 0)
        {
            UnknownNodeAction elementElseAction = ((list != null) ? new UnknownNodeAction(Wrapper) : ((UnknownNodeAction)delegate
            {
                UnknownNode(p);
            }));
            WriteMemberElements(array, elementElseAction, delegate
            {
                UnknownNode(p);
            }, null, null, fixup, list);
            base.Reader.MoveToContent();
        }
        if (!flag)
        {
            ReadEndElement();
        }
        if (list != null)
        {
            foreach (CheckTypeSource item in list)
            {
                bool isReferenced = true;
                bool isObject = item.IsObject;
                object obj = (isObject ? item.RefObject : GetTarget((string)item.RefObject));
                if (obj != null)
                {
                    CheckTypeSource checkTypeSource = new CheckTypeSource
                    {
                        RefObject = obj,
                        Type = obj.GetType(),
                        Id = null
                    };
                    WriteMemberElementsIf(array, null, delegate
                    {
                        isReferenced = false;
                    }, fixup, checkTypeSource);
                    if (isObject && isReferenced)
                    {
                        Referenced(obj);
                    }
                }
            }
        }
        ReadReferencedElements();
        return p;
        [RequiresUnreferencedCode("calls ReadReferencedElement")]
        void Wrapper(object _)
        {
            if (base.Reader.GetAttribute("id", null) != null)
            {
                ReadReferencedElement();
            }
            else
            {
                UnknownNode(p);
            }
        }
    }
References System.array, System.Xml.Serialization.XmlSerializationReader.CreateUnknownNodeException(), System.Xml.Dictionary, System.Xml.Serialization.XmlSerializationReader.GetTarget(), System.Type.GetType(), System.Xml.Schema.Id, System.index, System.Xml.Serialization.ReflectionXmlSerializationReader.InitializeValueTypes(), System.item, System.list, System.Xml.Name, System.obj, System.Xml.Serialization.XmlSerializationReader.ReadEndElement(), System.Xml.Serialization.XmlSerializationReader.ReadReferencedElement(), System.Xml.Serialization.XmlSerializationReader.ReadReferencedElements(), System.Xml.Serialization.XmlSerializationReader.Referenced(), System.text, System.Xml.XmlConvert.ToBoolean(), System.Xml.Serialization.XmlSerializationReader.UnknownNode(), System.Xml.Serialization.UnknownNodeAction(), System.value, System.Xml.Serialization.ReflectionXmlSerializationReader.WriteMemberElements(), System.Xml.Serialization.ReflectionXmlSerializationReader.WriteMemberElementsIf(), System.Xml.Serialization.ReflectionXmlSerializationReader.WriteMemberFixupBegin(), and System.Xml.Serialization.ReflectionXmlSerializationReader.XmlNodeEqual().
Referenced by System.Xml.Serialization.ReflectionXmlSerializationReader.GenerateMembersElement().