Terraria: System.Xml.Serialization.ReflectionXmlSerializationReader.WriteMemberElementsIf
WriteMemberElementsIf()
void System.Xml.Serialization.ReflectionXmlSerializationReader.WriteMemberElementsIf (Member[] expectedMembers, Member anyElementMember, UnknownNodeAction elementElseAction, Fixup fixup = null, CheckTypeSource checkTypeSource = null) inline private
Definition at line 693 of file ReflectionXmlSerializationReader.cs.
    {
        bool flag = checkTypeSource != null;
        bool flag2 = IsSequence(expectedMembers);
        ElementAccessor elementAccessor = null;
        Member member = null;
        bool flag3 = false;
        int elementIndex = -1;
        foreach (Member member2 in expectedMembers)
        {
            if (member2.Mapping.Xmlns != null || member2.Mapping.Ignore || (flag2 && (member2.Mapping.IsText || member2.Mapping.IsAttribute)))
            {
                continue;
            }
            for (int j = 0; j < member2.Mapping.Elements.Length; j++)
            {
                ElementAccessor elementAccessor2 = member2.Mapping.Elements[j];
                string text = ((elementAccessor2.Form == XmlSchemaForm.Qualified) ? elementAccessor2.Namespace : string.Empty);
                if (flag)
                {
                    Type type;
                    if (elementAccessor2.Mapping is NullableMapping nullableMapping)
                    {
                        TypeDesc typeDesc = nullableMapping.BaseMapping.TypeDesc;
                        type = typeDesc.Type;
                    }
                    else
                    {
                        type = elementAccessor2.Mapping.TypeDesc.Type;
                    }
                    if (type.IsAssignableFrom(checkTypeSource.Type))
                    {
                        flag3 = true;
                    }
                }
                else if (elementAccessor2.Name == base.Reader.LocalName && text == base.Reader.NamespaceURI)
                {
                    flag3 = true;
                }
                if (flag3)
                {
                    elementAccessor = elementAccessor2;
                    member = member2;
                    elementIndex = j;
                    break;
                }
            }
            if (flag3)
            {
                break;
            }
        }
        if (flag3)
        {
            if (flag)
            {
                member.Source(checkTypeSource.RefObject);
                if (member.FixupIndex >= 0)
                {
                    fixup.Ids[member.FixupIndex] = checkTypeSource.Id;
                }
            }
            else
            {
                string defaultNamespace = ((elementAccessor.Form == XmlSchemaForm.Qualified) ? elementAccessor.Namespace : string.Empty);
                bool flag4 = member.Mapping.TypeDesc.IsArrayLike && !member.Mapping.TypeDesc.IsArray;
                WriteElement(elementAccessor, member.Mapping.CheckSpecified == SpecifiedAccessor.ReadWrite, flag4 && member.Mapping.TypeDesc.IsNullable, member.Mapping.ReadOnly, defaultNamespace, member.FixupIndex, elementIndex, fixup, member);
            }
        }
        else if (anyElementMember != null && anyElementMember.Mapping != null)
        {
            MemberMapping mapping = anyElementMember.Mapping;
            member = anyElementMember;
            ElementAccessor[] elements = mapping.Elements;
            foreach (ElementAccessor elementAccessor3 in elements)
            {
                if (elementAccessor3.Any && elementAccessor3.Name.Length == 0)
                {
                    string defaultNamespace2 = ((elementAccessor3.Form == XmlSchemaForm.Qualified) ? elementAccessor3.Namespace : string.Empty);
                    WriteElement(elementAccessor3, mapping.CheckSpecified == SpecifiedAccessor.ReadWrite, checkForNull: false, readOnly: false, defaultNamespace2, -1, -1, fixup, member);
                    break;
                }
            }
        }
        else
        {
            member = null;
            ProcessUnknownNode(elementElseAction);
        }
    }
References System.Xml.Dictionary, System.elementIndex, System.Xml.Serialization.ReflectionXmlSerializationReader.IsSequence(), System.Xml.Serialization.ReflectionXmlSerializationReader.ProcessUnknownNode(), System.text, System.type, and System.Xml.Serialization.ReflectionXmlSerializationReader.WriteElement().
Referenced by System.Xml.Serialization.ReflectionXmlSerializationReader.GenerateEncodedMembersElement(), and System.Xml.Serialization.ReflectionXmlSerializationReader.WriteMemberElements().