Terraria: System.Xml.Serialization.ReflectionXmlSerializationReader.SetOrAddValueToMember
SetOrAddValueToMember()
void System.Xml.Serialization.ReflectionXmlSerializationReader.SetOrAddValueToMember (object o, object value, MemberInfo memberInfo) inline private
Definition at line 1756 of file ReflectionXmlSerializationReader.cs.
    {
        Type memberType = GetMemberType(memberInfo);
        if (memberType == value.GetType())
        {
            ReflectionXmlSerializationReaderHelper.SetMemberValueDelegate setMemberValueDelegate = GetSetMemberValueDelegate(o, memberInfo.Name);
            setMemberValueDelegate(o, value);
        }
        else if (memberType.IsArray)
        {
            AddItemInArrayMember(o, memberInfo, memberType, value);
        }
        else
        {
            ReflectionXmlSerializationReaderHelper.SetMemberValueDelegate setMemberValueDelegate2 = GetSetMemberValueDelegate(o, memberInfo.Name);
            setMemberValueDelegate2(o, value);
        }
    }
References System.Xml.Serialization.ReflectionXmlSerializationReader.AddItemInArrayMember(), System.Xml.Dictionary, System.Xml.Serialization.ReflectionXmlSerializationReader.GetMemberType(), System.Xml.Serialization.ReflectionXmlSerializationReader.GetSetMemberValueDelegate(), and System.value.
Referenced by System.Xml.Serialization.ReflectionXmlSerializationReader.WriteLiteralStructMethod().