Terraria: System.Xml.Serialization.ReflectionXmlSerializationReader.WriteElement
WriteElement()
object System.Xml.Serialization.ReflectionXmlSerializationReader.WriteElement (ElementAccessor element, bool checkSpecified, bool checkForNull, bool readOnly, string defaultNamespace, int fixupIndex = -1, int elementIndex = -1, Fixup fixup = null, Member member = null) inline private
Definition at line 785 of file ReflectionXmlSerializationReader.cs.
    {
        object obj = null;
        if (element.Mapping is ArrayMapping arrayMapping)
        {
            obj = WriteArray(arrayMapping, readOnly, element.IsNullable, defaultNamespace, fixupIndex, fixup, member);
        }
        else if (element.Mapping is NullableMapping nullableMapping)
        {
            obj = WriteNullableMethod(nullableMapping, checkType: true, defaultNamespace);
        }
        else if (!element.Mapping.IsSoap && element.Mapping is PrimitiveMapping)
        {
            if (element.IsNullable && ReadNull())
            {
                obj = ((!element.Mapping.TypeDesc.IsValueType) ? null : ReflectionCreateObject(element.Mapping.TypeDesc.Type));
            }
            else if (element.Default != null && element.Default != DBNull.Value && element.Mapping.TypeDesc.IsValueType && base.Reader.IsEmptyElement)
            {
                base.Reader.Skip();
            }
            else if (element.Mapping.TypeDesc.Type == typeof(TimeSpan) && base.Reader.IsEmptyElement)
            {
                base.Reader.Skip();
                obj = default(TimeSpan);
            }
            else if (element.Mapping.TypeDesc.Type == typeof(DateTimeOffset) && base.Reader.IsEmptyElement)
            {
                base.Reader.Skip();
                obj = default(DateTimeOffset);
            }
            else if (element.Mapping.TypeDesc == QnameTypeDesc)
            {
                obj = ReadElementQualifiedName();
            }
            else if (element.Mapping.TypeDesc.FormatterName == "ByteArrayBase64")
            {
                obj = ToByteArrayBase64(isNull: false);
            }
            else if (element.Mapping.TypeDesc.FormatterName == "ByteArrayHex")
            {
                obj = ToByteArrayHex(isNull: false);
            }
            else
            {
                Func<object, string> readFunc = (object state) => ((XmlReader)state).ReadElementContentAsString();
                obj = WritePrimitive(element.Mapping, readFunc, base.Reader);
            }
        }
        else if (element.Mapping is StructMapping || (element.Mapping.IsSoap && element.Mapping is PrimitiveMapping))
        {
            TypeMapping mapping = element.Mapping;
            if (mapping.IsSoap)
            {
                object obj2 = ((fixupIndex >= 0) ? ReadReferencingElement(mapping.TypeName, mapping.Namespace, out fixup.Ids[fixupIndex]) : ReadReferencedElement(mapping.TypeName, mapping.Namespace));
                if (!mapping.TypeDesc.IsValueType || obj2 != null)
                {
                    obj = obj2;
                    Referenced(obj);
                }
                if (fixupIndex >= 0)
                {
                    if (member == null)
                    {
                        throw new InvalidOperationException(System.SR.XmlInternalError);
                    }
                    member.Source(obj);
                    return obj;
                }
            }
            else if (checkForNull && member.Source == null && member.ArraySource == null)
            {
                base.Reader.Skip();
            }
            else
            {
                obj = WriteStructMethod((StructMapping)mapping, mapping.TypeDesc.IsNullable && element.IsNullable, checkType: true, defaultNamespace);
            }
        }
        else
        {
            if (!(element.Mapping is SpecialMapping specialMapping))
            {
                throw new InvalidOperationException(System.SR.XmlInternalError);
            }
            switch (specialMapping.TypeDesc.Kind)
            {
            case TypeKind.Node:
                obj = ((!(specialMapping.TypeDesc.FullName == typeof(XmlDocument).FullName)) ? ReadXmlNode(!element.Any) : ReadXmlDocument(!element.Any));
                break;
            case TypeKind.Serializable:
            {
                SerializableMapping serializableMapping = (SerializableMapping)element.Mapping;
                bool flag = true;
                if (serializableMapping.DerivedMappings != null)
                {
                    XmlQualifiedName xsiType = GetXsiType();
                    if (!(xsiType == null) && !QNameEqual(xsiType, serializableMapping.XsiType.Name, serializableMapping.XsiType.Namespace, defaultNamespace))
                    {
                        flag = false;
                    }
                }
                if (flag)
                {
                    bool wrappedAny = !element.Any && IsWildcard(serializableMapping);
                    obj = ReadSerializable((IXmlSerializable)ReflectionCreateObject(serializableMapping.TypeDesc.Type), wrappedAny);
                }
                if (serializableMapping.DerivedMappings != null)
                {
                    throw new NotImplementedException("sm.DerivedMappings != null");
                }
                break;
            }
            default:
                throw new InvalidOperationException(System.SR.XmlInternalError);
            }
        }
        member?.ChoiceSource?.Invoke(element.Name);
        if (member != null && member.ArraySource != null)
        {
            member?.ArraySource(obj);
        }
        else
        {
            member?.Source?.Invoke(obj);
            member?.CheckSpecifiedSource?.Invoke(true);
        }
        return obj;
    }
References System.Xml.Serialization.Accessor.Any, System.Xml.Serialization.Accessor.Default, System.Xml.Dictionary, System.Xml.Serialization.TypeDesc.FormatterName, System.Xml.Serialization.XmlSerializationReader.GetXsiType(), System.Xml.Serialization.ElementAccessor.IsNullable, System.Xml.Serialization.Mapping.IsSoap, System.Xml.Serialization.TypeDesc.IsValueType, System.Xml.Serialization.ReflectionXmlSerializationReader.IsWildcard(), System.Xml.Serialization.Accessor.Mapping, System.Xml.Serialization.Accessor.Name, System.obj, System.Xml.Serialization.ReflectionXmlSerializationReader.QNameEqual(), System.Xml.Serialization.ReflectionXmlSerializationReader.QnameTypeDesc, System.Xml.Serialization.XmlSerializationReader.ReadElementQualifiedName(), System.Xml.Serialization.XmlSerializationReader.ReadNull(), System.Xml.Serialization.XmlSerializationReader.ReadReferencedElement(), System.Xml.Serialization.XmlSerializationReader.ReadReferencingElement(), System.Xml.Serialization.XmlSerializationReader.ReadSerializable(), System.Xml.Serialization.XmlSerializationReader.ReadXmlDocument(), System.Xml.Serialization.XmlSerializationReader.ReadXmlNode(), System.Xml.Serialization.XmlSerializationReader.Referenced(), System.Xml.Serialization.ReflectionXmlSerializationReader.ReflectionCreateObject(), System.state, System.Xml.Serialization.XmlSerializationReader.ToByteArrayBase64(), System.Xml.Serialization.XmlSerializationReader.ToByteArrayHex(), System.Xml.Serialization.TypeDesc.Type, System.Xml.Serialization.TypeMapping.TypeDesc, System.DBNull.Value, System.Xml.Serialization.ReflectionXmlSerializationReader.WriteArray(), System.Xml.Serialization.ReflectionXmlSerializationReader.WriteNullableMethod(), System.Xml.Serialization.ReflectionXmlSerializationReader.WritePrimitive(), System.Xml.Serialization.ReflectionXmlSerializationReader.WriteStructMethod(), and System.SR.XmlInternalError.
Referenced by System.Xml.Serialization.ReflectionXmlSerializationReader.WriteMemberElementsIf(), and System.Xml.Serialization.ReflectionXmlSerializationReader.WriteNullableMethod().