Terraria: System.Xml.Serialization.ReflectionXmlSerializationReader.WriteAttribute
WriteAttribute()
void System.Xml.Serialization.ReflectionXmlSerializationReader.WriteAttribute (Member member, object attr = null) inline private
Definition at line 1716 of file ReflectionXmlSerializationReader.cs.
    {
        AttributeAccessor attribute = member.Mapping.Attribute;
        object obj = null;
        if (attribute.Mapping is SpecialMapping specialMapping)
        {
            if (specialMapping.TypeDesc.Kind != TypeKind.Attribute)
            {
                if (specialMapping.TypeDesc.CanBeAttributeValue)
                {
                    throw new NotImplementedException("special.TypeDesc.CanBeAttributeValue");
                }
                throw new InvalidOperationException(System.SR.XmlInternalError);
            }
            obj = attr;
        }
        else if (attribute.IsList)
        {
            string value = base.Reader.Value;
            string[] array = value.Split((char[]?)null);
            Array array2 = Array.CreateInstance(member.Mapping.TypeDesc.Type.GetElementType(), array.Length);
            int i;
            for (i = 0; i < array.Length; i++)
            {
                array2.SetValue(WritePrimitive(attribute.Mapping, (object state) => ((string[])state)[i], array), i);
            }
            obj = array2;
        }
        else
        {
            obj = WritePrimitive(attribute.Mapping, (object state) => ((XmlReader)state).Value, base.Reader);
        }
        member.Source(obj);
        if (member.Mapping.CheckSpecified == SpecifiedAccessor.ReadWrite)
        {
            member.CheckSpecifiedSource?.Invoke(null);
        }
    }
References System.array, System.Xml.Serialization.AccessorMapping.Attribute, System.Xml.Serialization.MemberMapping.CheckSpecified, System.Xml.Serialization.ReflectionXmlSerializationReader.Member.CheckSpecifiedSource, System.Array.CreateInstance(), System.Xml.Dictionary, System.Type.GetElementType(), System.Xml.Serialization.ReflectionXmlSerializationReader.Member.Mapping, System.obj, System.Xml.Serialization.ReflectionXmlSerializationReader.Member.Source, System.state, System.Xml.Serialization.TypeDesc.Type, System.Xml.Serialization.AccessorMapping.TypeDesc, System.value, System.Xml.Serialization.ReflectionXmlSerializationReader.WritePrimitive(), and System.SR.XmlInternalError.
Referenced by System.Xml.Serialization.ReflectionXmlSerializationReader.WriteAttributes().