Terraria: System.Xml.Serialization.ReflectionXmlSerializationReader.WriteAddCollectionFixup
WriteAddCollectionFixup() [1/2]
object System.Xml.Serialization.ReflectionXmlSerializationReader.WriteAddCollectionFixup (Func< object > getSource, Action< object > setSource, object memberValue, TypeDesc typeDesc, bool readOnly) inline private
Definition at line 1316 of file ReflectionXmlSerializationReader.cs.
    {
        object obj = getSource();
        if (obj == null)
        {
            if (readOnly)
            {
                throw CreateReadOnlyCollectionException(typeDesc.CSharpName);
            }
            obj = ReflectionCreateObject(typeDesc.Type);
            setSource(obj);
        }
        CollectionFixup fixup = new CollectionFixup(obj, GetCreateCollectionOfObjectsCallback(typeDesc.Type).Invoke, memberValue);
        AddFixup(fixup);
        return obj;
    }
References System.Xml.Serialization.XmlSerializationReader.AddFixup(), System.Xml.Serialization.XmlSerializationReader.CreateReadOnlyCollectionException(), System.Xml.Dictionary, System.Xml.Serialization.ReflectionXmlSerializationReader.GetCreateCollectionOfObjectsCallback(), System.obj, and System.Xml.Serialization.ReflectionXmlSerializationReader.ReflectionCreateObject().