Terraria: System.Xml.Serialization.ReflectionXmlSerializationReader.WriteEncodedStructMethod
WriteEncodedStructMethod()
object System.Xml.Serialization.ReflectionXmlSerializationReader.WriteEncodedStructMethod (StructMapping structMapping) inline private
Definition at line 1186 of file ReflectionXmlSerializationReader.cs.
    {
        if (structMapping.TypeDesc.IsRoot)
        {
            return null;
        }
        Member[] array = null;
        if (structMapping.TypeDesc.IsAbstract)
        {
            throw CreateAbstractTypeException(structMapping.TypeName, structMapping.Namespace);
        }
        object o = ReflectionCreateObject(structMapping.TypeDesc.Type);
        MemberMapping[] settableMembers = TypeScope.GetSettableMembers(structMapping);
        array = new Member[settableMembers.Length];
        for (int i = 0; i < settableMembers.Length; i++)
        {
            MemberMapping mapping = settableMembers[i];
            Member member = new Member(mapping);
            TypeDesc typeDesc = member.Mapping.TypeDesc;
            if (typeDesc.IsCollection || typeDesc.IsEnumerable)
            {
                member.Source = Wrapper;
            }
            else if (!member.Mapping.ReadOnly)
            {
                ReflectionXmlSerializationReaderHelper.SetMemberValueDelegate setterDelegate = GetSetMemberValueDelegate(o, member.Mapping.MemberInfo.Name);
                member.Source = delegate(object value)
                {
                    setterDelegate(o, value);
                };
            }
            else
            {
                member.Source = NoopAction;
            }
            array[i] = member;
            [RequiresUnreferencedCode("Calls WriteAddCollectionFixup")]
            void Wrapper(object value)
            {
                WriteAddCollectionFixup(o, member, value);
            }
        }
        Fixup fixup = WriteMemberFixupBegin(array, o);
        UnknownNodeAction elseCall = delegate
        {
            UnknownNode(o);
        };
        WriteAttributes(array, null, elseCall, ref o);
        base.Reader.MoveToElement();
        if (base.Reader.IsEmptyElement)
        {
            base.Reader.Skip();
            return o;
        }
        base.Reader.ReadStartElement();
        base.Reader.MoveToContent();
        while (base.Reader.NodeType != XmlNodeType.EndElement && base.Reader.NodeType != 0)
        {
            WriteMemberElements(array, base.UnknownNode, base.UnknownNode, null, null, fixup);
            base.Reader.MoveToContent();
        }
        ReadEndElement();
        return o;
    }
References System.array, System.Xml.Serialization.XmlSerializationReader.CreateAbstractTypeException(), System.Xml.Dictionary, System.Xml.Serialization.ReflectionXmlSerializationReader.GetSetMemberValueDelegate(), System.Xml.Serialization.TypeScope.GetSettableMembers(), System.Xml.Serialization.ReflectionXmlSerializationReader.Member.Mapping, System.Xml.Serialization.MemberMapping.MemberInfo, System.Reflection.MemberInfo.Name, System.Xml.Serialization.ReflectionXmlSerializationReader.NoopAction(), System.Xml.Serialization.XmlSerializationReader.ReadEndElement(), System.Xml.Serialization.MemberMapping.ReadOnly, System.Xml.Serialization.ReflectionXmlSerializationReader.ReflectionCreateObject(), System.Xml.Serialization.AccessorMapping.TypeDesc, System.Xml.Serialization.XmlSerializationReader.UnknownNode(), System.Xml.Serialization.UnknownNodeAction(), System.value, System.Xml.Serialization.ReflectionXmlSerializationReader.WriteAddCollectionFixup(), System.Xml.Serialization.ReflectionXmlSerializationReader.WriteAttributes(), System.Xml.Serialization.ReflectionXmlSerializationReader.WriteMemberElements(), and System.Xml.Serialization.ReflectionXmlSerializationReader.WriteMemberFixupBegin().
Referenced by System.Xml.Serialization.ReflectionXmlSerializationReader.WriteStructMethod().