Terraria: System.Globalization.CompareInfo.InvariantCreateSortKeyOrdinalIgnoreCase
InvariantCreateSortKeyOrdinalIgnoreCase()
static void System.Globalization.CompareInfo.InvariantCreateSortKeyOrdinalIgnoreCase (ReadOnlySpan< char > source, Span< byte > sortKey) inline static private
Definition at line 1842 of file CompareInfo.cs.
    {
        for (int i = 0; i < source.Length; i++)
        {
            char c = source[i];
            if (char.IsHighSurrogate(c) && i < source.Length - 1)
            {
                char c2 = source[i + 1];
                if (char.IsLowSurrogate(c2))
                {
                    SurrogateCasing.ToUpper(c, c2, out var hr, out var lr);
                    BinaryPrimitives.WriteUInt16BigEndian(sortKey, hr);
                    BinaryPrimitives.WriteUInt16BigEndian(sortKey, lr);
                    i++;
                    sortKey = sortKey.Slice(4);
                    continue;
                }
            }
            BinaryPrimitives.WriteUInt16BigEndian(sortKey, InvariantModeCasing.ToUpper(c));
            sortKey = sortKey.Slice(2);
        }
    }
References System.source, System.Globalization.InvariantModeCasing.ToUpper(), System.Globalization.SurrogateCasing.ToUpper(), and System.Buffers.Binary.BinaryPrimitives.WriteUInt16BigEndian().
Referenced by System.Globalization.CompareInfo.InvariantCreateSortKey(), and System.Globalization.CompareInfo.InvariantGetSortKey().