Terraria: System.Globalization.CompareInfo.IndexOfOrdinalIgnoreCaseHelper
IndexOfOrdinalIgnoreCaseHelper()
unsafe int System.Globalization.CompareInfo.IndexOfOrdinalIgnoreCaseHelper (ReadOnlySpan< char > source, ReadOnlySpan< char > target, CompareOptions options, int * matchLengthPtr, bool fromBeginning) inline private
Definition at line 1155 of file CompareInfo.cs.
    {
        fixed (char* ptr = &MemoryMarshal.GetReference(source))
        {
            fixed (char* ptr3 = &MemoryMarshal.GetReference(target))
            {
                char* ptr2 = ptr;
                char* ptr4 = ptr3;
                int num = 0;
                while (true)
                {
                    if (num < target.Length)
                    {
                        char c = ptr4[num];
                        if (c >= '\u0080' || HighCharTable[c])
{
                            break;
                        }
                        num++;
                        continue;
                    }
                    if (target.Length > source.Length)
                    {
                        int num2 = 0;
                        while (true)
{
                            if (num2 < source.Length)
{
                                char c2 = ptr2[num2];
                                if (c2 >= '\u0080' || HighCharTable[c2])
{
                                    break;
                                }
                                num2++;
                                continue;
                            }
                            return -1;
                        }
                        break;
                    }
                    int num3;
                    int num4;
                    int num5;
                    if (fromBeginning)
                    {
                        num3 = 0;
                        num4 = source.Length - target.Length + 1;
                        num5 = 1;
                    }
                    else
                    {
                        num3 = source.Length - target.Length;
                        num4 = -1;
                        num5 = -1;
                    }
                    int num6 = num3;
                    while (true)
                    {
                        int num8;
                        if (num6 != num4)
{
                            int num7 = 0;
                            num8 = num6;
                            while (true)
{
                                if (num7 < target.Length)
{
                                    char c3 = ptr2[num8];
                                    char c4 = ptr4[num7];
                                    if (c3 >= '\u0080' || HighCharTable[c3])
{
                                        break;
                                    }
                                    if (c3 == c4)
{
                                        goto IL_0184;
                                    }
                                    if ((uint)(c3 - 97) <= 25u)
{
                                        c3 = (char)(c3 - 32);
                                    }
                                    if ((uint)(c4 - 97) <= 25u)
{
                                        c4 = (char)(c4 - 32);
                                    }
                                    if (c3 == c4)
{
                                        goto IL_0184;
                                    }
                                    goto IL_0163;
                                }
                                if (num8 < source.Length && ptr2[num8] >= '\u0080')
{
                                    break;
                                }
                                if (matchLengthPtr != null)
{
                                    *matchLengthPtr = target.Length;
                                }
                                return num6;
                                IL_0184:
                                num7++;
                                num8++;
                            }
                            break;
                        }
                        return -1;
                        IL_0163:
                        if (num8 < source.Length - 1 && (ptr2 + num8)[1] >= '\u0080')
{
                            break;
                        }
                        num6 += num5;
                    }
                    break;
                }
                if (fromBeginning)
                {
                    return Interop.Globalization.IndexOf(_sortHandle, ptr4, target.Length, ptr2, source.Length, options, matchLengthPtr);
                }
                return Interop.Globalization.LastIndexOf(_sortHandle, ptr4, target.Length, ptr2, source.Length, options, matchLengthPtr);
            }
        }
    }
References System.Globalization.CompareInfo._sortHandle, System.Runtime.Serialization.Dictionary, System.Globalization.CompareInfo.HighCharTable, Interop.Globalization.IndexOf(), Interop.Globalization.LastIndexOf(), System.options, and System.source.
Referenced by System.Globalization.CompareInfo.IcuIndexOfCore().