Terraria: System.Globalization.CompareInfo.Compare
Compare() [6/7]
int System.Globalization.CompareInfo.Compare (string? string1, string? string2) inline
Definition at line 261 of file CompareInfo.cs.
    {
        return Compare(string1, string2, CompareOptions.None);
    }
References System.Globalization.CompareInfo.Compare().
Referenced by System.InvariantComparer.Compare(), MS.Internal.Xml.XPath.XPathComparerHelper.Compare(), System.Collections.CaseInsensitiveComparer.Compare(), System.Collections.Comparer.Compare(), System.Globalization.CompareInfo.Compare(), System.Globalization.CompareInfo.Compare(), System.Globalization.CompareInfo.Compare(), System.Globalization.CompareInfo.Compare(), System.Globalization.CompareInfo.Compare(), System.Globalization.CompareInfo.Compare(), System.CultureAwareComparer.Compare(), System.CultureAwareComparer.Equals(), System.Data.ProviderBase.FieldNameLookup.LinearIndexOf(), System.__DTString.Match(), System.__DTString.MatchSpecifiedWord(), System.__DTString.MatchSpecifiedWords(), System.Data.InternalDataCollectionBase.NamesEqual(), System.Data.ExpressionParser.ScanReserved(), and System.Data.SqlTypes.SqlString.StringCompare().