Terraria: System.Globalization.CompareInfo.IndexOf
IndexOf() [16/16]
int System.Globalization.CompareInfo.IndexOf (string source, string value, int startIndex, int count, CompareOptions options) inline
Definition at line 670 of file CompareInfo.cs.
    {
        if (source == null)
        {
            ThrowHelper.ThrowArgumentNullException(ExceptionArgument.source);
        }
        if (value == null)
        {
            ThrowHelper.ThrowArgumentNullException(ExceptionArgument.value);
        }
        if (!source.TryGetSpan(startIndex, count, out var slice))
        {
            if ((uint)startIndex > (uint)source.Length)
            {
                ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument.startIndex, ExceptionResource.ArgumentOutOfRange_Index);
            }
            else
            {
                ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument.count, ExceptionResource.ArgumentOutOfRange_Count);
            }
        }
        int num = IndexOf(slice, value, options);
        if (num >= 0)
        {
            num += startIndex;
        }
        return num;
    }
References System.count, System.Globalization.CompareInfo.IndexOf(), System.options, System.source, System.startIndex, System.ThrowHelper.ThrowArgumentNullException(), System.ThrowHelper.ThrowArgumentOutOfRangeException(), and System.value.