Terraria: System.Globalization.CompareInfo.NlsGetSortKey
NlsGetSortKey()
unsafe int System.Globalization.CompareInfo.NlsGetSortKey (ReadOnlySpan< char > source, Span< byte > destination, CompareOptions options) inline private
Definition at line 2109 of file CompareInfo.cs.
    {
        if (destination.IsEmpty)
        {
            ThrowHelper.ThrowArgumentException_DestinationTooShort();
        }
        if (!Environment.IsWindows8OrAbove)
        {
            source = source.ToString();
        }
        uint dwMapFlags = 0x400u | (uint)GetNativeCompareFlags(options);
        int num = source.Length;
        if (num == 0)
        {
            source = string.Empty;
            num = -1;
        }
        int num3;
        fixed (char* lpSrcStr = &MemoryMarshal.GetReference(source))
        {
            fixed (byte* lpDestStr = &MemoryMarshal.GetReference(destination))
            {
                if (!Environment.IsWindows8OrAbove)
                {
                    int num2 = Interop.Kernel32.LCMapStringEx((_sortHandle != IntPtr.Zero) ? null : _sortName, dwMapFlags, lpSrcStr, num, null, 0, null, null, _sortHandle);
                    if (num2 > destination.Length)
                    {
                        ThrowHelper.ThrowArgumentException_DestinationTooShort();
                    }
                    if (num2 <= 0)
                    {
                        throw new ArgumentException(SR.Arg_ExternalException);
                    }
                }
                num3 = Interop.Kernel32.LCMapStringEx((_sortHandle != IntPtr.Zero) ? null : _sortName, dwMapFlags, lpSrcStr, num, lpDestStr, destination.Length, null, null, _sortHandle);
            }
        }
        if (num3 <= 0)
        {
            if (Marshal.GetLastPInvokeError() != 122)
            {
                throw new ArgumentException(SR.Arg_ExternalException);
            }
            ThrowHelper.ThrowArgumentException_DestinationTooShort();
        }
        return num3;
    }
References System.Globalization.CompareInfo._sortHandle, System.Globalization.CompareInfo._sortName, System.SR.Arg_ExternalException, System.destination, System.Runtime.Serialization.Dictionary, System.Runtime.InteropServices.Marshal.GetLastPInvokeError(), System.Globalization.CompareInfo.GetNativeCompareFlags(), System.Environment.IsWindows8OrAbove, Interop.Kernel32.LCMapStringEx(), System.options, System.source, System.ThrowHelper.ThrowArgumentException_DestinationTooShort(), and System.IntPtr.Zero.
Referenced by System.Globalization.CompareInfo.GetSortKeyCore().