Terraria: System.Globalization.CompareInfo.GetSortKey
GetSortKey() [1/3]
int System.Globalization.CompareInfo.GetSortKey (ReadOnlySpan< char > source, Span< byte > destination, CompareOptions options = CompareOptions::None) inline
Definition at line 1003 of file CompareInfo.cs.
    {
        if (((uint)options & 0xDFFFFFE0u) != 0)
        {
            ThrowHelper.ThrowArgumentException(ExceptionResource.Argument_InvalidFlag, ExceptionArgument.options);
        }
        if (GlobalizationMode.Invariant)
        {
            return InvariantGetSortKey(source, destination, options);
        }
        return GetSortKeyCore(source, destination, options);
    }
References System.destination, System.Globalization.CompareInfo.GetSortKeyCore(), System.Globalization.GlobalizationMode.Invariant, System.Globalization.CompareInfo.InvariantGetSortKey(), System.options, System.source, and System.ThrowHelper.ThrowArgumentException().