Terraria: System.Globalization.CompareInfo.NlsGetSortHandle
NlsGetSortHandle()
static unsafe IntPtr System.Globalization.CompareInfo.NlsGetSortHandle (string cultureName) inline static package
Definition at line 1897 of file CompareInfo.cs.
    {
        if (GlobalizationMode.Invariant)
        {
            return IntPtr.Zero;
        }
        System.Runtime.CompilerServices.Unsafe.SkipInit(out IntPtr intPtr);
        int num = Interop.Kernel32.LCMapStringEx(cultureName, 536870912u, null, 0, &intPtr, IntPtr.Size, null, null, IntPtr.Zero);
        if (num > 0)
        {
            int num2 = 0;
            char c = 'a';
            num = Interop.Kernel32.LCMapStringEx(null, 262144u, &c, 1, &num2, 4, null, null, intPtr);
            if (num > 1)
            {
                return intPtr;
            }
        }
        return IntPtr.Zero;
    }
References System.Runtime.Serialization.Dictionary, System.Globalization.GlobalizationMode.Invariant, Interop.Kernel32.LCMapStringEx(), System.IntPtr.Size, and System.IntPtr.Zero.
Referenced by System.Globalization.TextInfo.TextInfo(), and System.Globalization.CompareInfo.NlsInitSortHandle().