Terraria: System.Globalization.CompareInfo.Compare
Compare() [1/7]
int System.Globalization.CompareInfo.Compare (ReadOnlySpan< char > string1, ReadOnlySpan< char > string2, CompareOptions options = CompareOptions::None) inline
Definition at line 370 of file CompareInfo.cs.
    {
        if (string1 == string2)
        {
            CheckCompareOptionsForCompare(options);
            return 0;
        }
        if ((options & ~(CompareOptions.IgnoreCase | CompareOptions.IgnoreNonSpace | CompareOptions.IgnoreSymbols | CompareOptions.IgnoreKanaType | CompareOptions.IgnoreWidth | CompareOptions.StringSort)) == 0)
        {
            if (!GlobalizationMode.Invariant)
            {
                return CompareStringCore(string1, string2, options);
            }
            if ((options & CompareOptions.IgnoreCase) == 0)
            {
                return string1.SequenceCompareTo(string2);
            }
            return Ordinal.CompareStringIgnoreCase(ref MemoryMarshal.GetReference(string1), string1.Length, ref MemoryMarshal.GetReference(string2), string2.Length);
        }
        switch (options)
        {
        case CompareOptions.Ordinal:
            return string1.SequenceCompareTo(string2);
        case CompareOptions.OrdinalIgnoreCase:
            return Ordinal.CompareStringIgnoreCase(ref MemoryMarshal.GetReference(string1), string1.Length, ref MemoryMarshal.GetReference(string2), string2.Length);
        default:
            ThrowCompareOptionsCheckFailed(options);
            return -1;
        }
    }
References System.Globalization.CompareInfo.CheckCompareOptionsForCompare(), System.Globalization.CompareInfo.CompareStringCore(), System.Globalization.Ordinal.CompareStringIgnoreCase(), System.Globalization.GlobalizationMode.Invariant, System.options, and System.Globalization.CompareInfo.ThrowCompareOptionsCheckFailed().