Terraria: System.Globalization.CompareInfo.IndexOf
IndexOf() [5/16]
int System.Globalization.CompareInfo.IndexOf (string source, char value) inline
Definition at line 575 of file CompareInfo.cs.
    {
        return IndexOf(source, value, CompareOptions.None);
    }
References System.Globalization.CompareInfo.IndexOf(), System.source, and System.value.
Referenced by System.Globalization.CompareInfo.IndexOf(), System.Globalization.CompareInfo.IndexOf(), System.Data.DataTable.IndexOf(), System.Globalization.CompareInfo.IndexOf(), System.Globalization.CompareInfo.IndexOf(), System.Globalization.CompareInfo.IndexOf(), System.Globalization.CompareInfo.IndexOf(), System.Globalization.CompareInfo.IndexOf(), System.Globalization.CompareInfo.IndexOf(), System.Globalization.CompareInfo.IndexOf(), System.Globalization.CompareInfo.IndexOf(), System.Globalization.CompareInfo.IndexOf(), System.Globalization.CompareInfo.IndexOf(), System.Globalization.CompareInfo.IndexOf(), System.Globalization.CompareInfo.IndexOf(), and System.Globalization.CompareInfo.LastIndexOf().