Terraria: System.Globalization.CompareInfo.GetSortKey
GetSortKey() [3/3]
SortKey System.Globalization.CompareInfo.GetSortKey (string source, CompareOptions options) inline
Definition at line 976 of file CompareInfo.cs.
    {
        if (GlobalizationMode.Invariant)
        {
            return InvariantCreateSortKey(source, options);
        }
        return CreateSortKeyCore(source, options);
    }
References System.Globalization.CompareInfo.CreateSortKeyCore(), System.Globalization.GlobalizationMode.Invariant, System.Globalization.CompareInfo.InvariantCreateSortKey(), System.options, and System.source.
Referenced by System.Xml.Xsl.Runtime.XmlCollation.CreateSortKey().