Terraria: System.Globalization.CompareInfo.NlsGetHashCodeOfString
NlsGetHashCodeOfString()
unsafe int System.Globalization.CompareInfo.NlsGetHashCodeOfString (ReadOnlySpan< char > source, CompareOptions options) inline private
Definition at line 1935 of file CompareInfo.cs.
    {
        if (!Environment.IsWindows8OrAbove)
        {
            source = source.ToString();
        }
        int num = source.Length;
        if (num == 0)
        {
            source = string.Empty;
            num = -1;
        }
        uint dwMapFlags = 0x400u | (uint)GetNativeCompareFlags(options);
        fixed (char* lpSrcStr = &MemoryMarshal.GetReference(source))
        {
            int num2 = Interop.Kernel32.LCMapStringEx((_sortHandle != IntPtr.Zero) ? null : _sortName, dwMapFlags, lpSrcStr, num, null, 0, null, null, _sortHandle);
            if (num2 == 0)
            {
                throw new ArgumentException(SR.Arg_ExternalException);
            }
            byte[] array = null;
            Span<byte> span = ((num2 > 512) ? ((Span<byte>)(array = ArrayPool<byte>.Shared.Rent(num2))) : stackalloc byte[512]);
            Span<byte> span2 = span;
            fixed (byte* lpDestStr = &MemoryMarshal.GetReference(span2))
            {
                if (Interop.Kernel32.LCMapStringEx((_sortHandle != IntPtr.Zero) ? null : _sortName, dwMapFlags, lpSrcStr, num, lpDestStr, num2, null, null, _sortHandle) != num2)
                {
                    throw new ArgumentException(SR.Arg_ExternalException);
                }
            }
            int result = Marvin.ComputeHash32(span2.Slice(0, num2), Marvin.DefaultSeed);
            if (array != null)
            {
                ArrayPool<byte>.Shared.Return(array);
            }
            return result;
        }
    }
References System.Globalization.CompareInfo._sortHandle, System.Globalization.CompareInfo._sortName, System.SR.Arg_ExternalException, System.array, System.Marvin.ComputeHash32(), System.Marvin.DefaultSeed, System.Runtime.Serialization.Dictionary, System.Globalization.CompareInfo.GetNativeCompareFlags(), System.Environment.IsWindows8OrAbove, Interop.Kernel32.LCMapStringEx(), System.options, System.source, and System.IntPtr.Zero.
Referenced by System.Globalization.CompareInfo.GetHashCodeOfStringCore().