Terraria: System.Globalization.CompareInfo.StartsWithOrdinalHelper
StartsWithOrdinalHelper()
unsafe bool System.Globalization.CompareInfo.StartsWithOrdinalHelper (ReadOnlySpan< char > source, ReadOnlySpan< char > prefix, CompareOptions options, int * matchLengthPtr) inline private
Definition at line 1481 of file CompareInfo.cs.
    {
        int num = Math.Min(source.Length, prefix.Length);
        fixed (char* ptr = &MemoryMarshal.GetReference(source))
        {
            fixed (char* ptr3 = &MemoryMarshal.GetReference(prefix))
            {
                char* ptr2 = ptr;
                char* ptr4 = ptr3;
                while (true)
                {
                    if (num != 0)
                    {
                        int num2 = *ptr2;
                        int num3 = *ptr4;
                        if (num2 >= 128 || num3 >= 128 || HighCharTable[num2] || HighCharTable[num3])
{
                            break;
                        }
                        if (num2 == num3)
{
                            ptr2++;
                            ptr4++;
                            num--;
                            continue;
                        }
                        if ((ptr2 < ptr + source.Length - 1 && ptr2[1] >= '\u0080') || (ptr4 < ptr3 + prefix.Length - 1 && ptr4[1] >= '\u0080'))
{
                            break;
                        }
                        return false;
                    }
                    if (source.Length < prefix.Length)
                    {
                        if (*ptr4 >= '\u0080')
{
                            break;
                        }
                        return false;
                    }
                    if (source.Length > prefix.Length && *ptr2 >= '\u0080')
                    {
                        break;
                    }
                    if (matchLengthPtr != null)
                    {
                        *matchLengthPtr = prefix.Length;
                    }
                    return true;
                }
                return Interop.Globalization.StartsWith(_sortHandle, ptr3, prefix.Length, ptr, source.Length, options, matchLengthPtr);
            }
        }
    }
References System.Globalization.CompareInfo._sortHandle, System.Runtime.Serialization.Dictionary, System.Globalization.CompareInfo.HighCharTable, System.Math.Min(), System.options, System.prefix, System.source, and Interop.Globalization.StartsWith().
Referenced by System.Globalization.CompareInfo.IcuStartsWith().