Terraria: System.Globalization.CompareInfo.InitSort
InitSort()
void System.Globalization.CompareInfo.InitSort (CultureInfo culture) inline private
Definition at line 213 of file CompareInfo.cs.
    {
        _sortName = culture.SortName;
        if (GlobalizationMode.UseNls)
        {
            NlsInitSortHandle();
        }
        else
        {
            IcuInitSortHandle();
        }
    }
References System.Globalization.CompareInfo._sortName, System.Globalization.CompareInfo.culture, System.Globalization.CompareInfo.IcuInitSortHandle(), System.Globalization.CompareInfo.NlsInitSortHandle(), and System.Globalization.GlobalizationMode.UseNls.
Referenced by System.Globalization.CompareInfo.CompareInfo(), and System.Globalization.CompareInfo.OnDeserialized().