Terraria: System.Globalization.CompareInfo.GetHashCode
GetHashCode() [1/3]
override int System.Globalization.CompareInfo.GetHashCode () inline
Definition at line 1056 of file CompareInfo.cs.
    {
        return Name.GetHashCode();
    }
References System.Globalization.CompareInfo.Name.
Referenced by System.Globalization.CultureInfo.GetHashCode(), System.Globalization.SortKey.GetHashCode(), System.CultureAwareComparer.GetHashCode(), System.Collections.CaseInsensitiveHashCodeProvider.GetHashCode(), System.CultureAwareComparer.GetHashCode(), and System.Globalization.CompareInfo.GetHashCode().