Terraria: System.Globalization.CompareInfo.IsPrefix
IsPrefix() [4/4]
bool System.Globalization.CompareInfo.IsPrefix (string source, string prefix, CompareOptions options) inline
Definition at line 427 of file CompareInfo.cs.
    {
        if (source == null)
        {
            ThrowHelper.ThrowArgumentNullException(ExceptionArgument.source);
        }
        if (prefix == null)
        {
            ThrowHelper.ThrowArgumentNullException(ExceptionArgument.prefix);
        }
        return IsPrefix(source.AsSpan(), prefix.AsSpan(), options);
    }
References System.Globalization.CompareInfo.IsPrefix(), System.options, System.prefix, System.source, and System.ThrowHelper.ThrowArgumentNullException().
Referenced by System.Globalization.CompareInfo.IsPrefix(), System.Globalization.CompareInfo.IsPrefix(), and System.Globalization.CompareInfo.IsPrefix().