Terraria: System.Globalization.CompareInfo.ThrowCompareOptionsCheckFailed
ThrowCompareOptionsCheckFailed()
static void System.Globalization.CompareInfo.ThrowCompareOptionsCheckFailed (CompareOptions options) inline static private
Definition at line 413 of file CompareInfo.cs.
    {
        throw new ArgumentException(((options & CompareOptions.Ordinal) != 0) ? SR.Argument_CompareOptionOrdinal : SR.Argument_InvalidFlag, "options");
    }
References System.SR.Argument_CompareOptionOrdinal, System.SR.Argument_InvalidFlag, and System.options.
Referenced by System.Globalization.CompareInfo.CheckCompareOptionsForCompare(), System.Globalization.CompareInfo.Compare(), System.Globalization.CompareInfo.GetHashCode(), System.Globalization.CompareInfo.IsPrefix(), and System.Globalization.CompareInfo.IsSuffix().