Terraria: System.Globalization.CompareInfo.IcuGetHashCodeOfString
IcuGetHashCodeOfString()
unsafe int System.Globalization.CompareInfo.IcuGetHashCodeOfString (ReadOnlySpan< char > source, CompareOptions options) inline private
Definition at line 1755 of file CompareInfo.cs.
    {
        int num = ((source.Length <= 262144) ? (4 * source.Length) : 0);
        byte[] array = null;
        Span<byte> span = ((num > 1024) ? ((Span<byte>)(array = ArrayPool<byte>.Shared.Rent(num))) : stackalloc byte[1024]);
        Span<byte> span2 = span;
        fixed (char* str = &MemoryMarshal.GetNonNullPinnableReference(source))
        {
            fixed (byte* sortKey = &MemoryMarshal.GetReference(span2))
            {
                num = Interop.Globalization.GetSortKey(_sortHandle, str, source.Length, sortKey, span2.Length, options);
            }
            if (num > span2.Length)
            {
                if (array != null)
                {
                    ArrayPool<byte>.Shared.Return(array);
                }
                span2 = (array = ArrayPool<byte>.Shared.Rent(num));
                fixed (byte* sortKey2 = &MemoryMarshal.GetReference(span2))
                {
                    num = Interop.Globalization.GetSortKey(_sortHandle, str, source.Length, sortKey2, span2.Length, options);
                }
            }
        }
        if (num == 0 || num > span2.Length)
        {
            throw new ArgumentException(SR.Arg_ExternalException);
        }
        int result = Marvin.ComputeHash32(span2.Slice(0, num), Marvin.DefaultSeed);
        if (array != null)
        {
            ArrayPool<byte>.Shared.Return(array);
        }
        return result;
    }
References System.Globalization.CompareInfo._sortHandle, System.SR.Arg_ExternalException, System.array, System.Marvin.ComputeHash32(), System.Marvin.DefaultSeed, System.Runtime.Serialization.Dictionary, Interop.Globalization.GetSortKey(), System.options, System.source, and System.str.
Referenced by System.Globalization.CompareInfo.GetHashCodeOfStringCore().