Terraria: System.Globalization.CompareInfo.IsSuffix
IsSuffix() [4/4]
bool System.Globalization.CompareInfo.IsSuffix (string source, string suffix, CompareOptions options) inline
Definition at line 501 of file CompareInfo.cs.
    {
        if (source == null)
        {
            ThrowHelper.ThrowArgumentNullException(ExceptionArgument.source);
        }
        if (suffix == null)
        {
            ThrowHelper.ThrowArgumentNullException(ExceptionArgument.suffix);
        }
        return IsSuffix(source.AsSpan(), suffix.AsSpan(), options);
    }
References System.Globalization.CompareInfo.IsSuffix(), System.options, System.source, System.suffix, and System.ThrowHelper.ThrowArgumentNullException().
Referenced by System.Globalization.CompareInfo.IsSuffix(), System.Data.DataTable.IsSuffix(), System.Globalization.CompareInfo.IsSuffix(), and System.Globalization.CompareInfo.IsSuffix().