Terraria: System.Globalization.CompareInfo.NlsGetSortKeyLength
NlsGetSortKeyLength()
unsafe int System.Globalization.CompareInfo.NlsGetSortKeyLength (ReadOnlySpan< char > source, CompareOptions options) inline private
Definition at line 2157 of file CompareInfo.cs.
    {
        uint dwMapFlags = 0x400u | (uint)GetNativeCompareFlags(options);
        int num = source.Length;
        if (num == 0)
        {
            source = string.Empty;
            num = -1;
        }
        int num2;
        fixed (char* lpSrcStr = &MemoryMarshal.GetReference(source))
        {
            num2 = Interop.Kernel32.LCMapStringEx((_sortHandle != IntPtr.Zero) ? null : _sortName, dwMapFlags, lpSrcStr, num, null, 0, null, null, _sortHandle);
        }
        if (num2 <= 0)
        {
            throw new ArgumentException(SR.Arg_ExternalException);
        }
        return num2;
    }
References System.Globalization.CompareInfo._sortHandle, System.Globalization.CompareInfo._sortName, System.SR.Arg_ExternalException, System.Runtime.Serialization.Dictionary, System.Globalization.CompareInfo.GetNativeCompareFlags(), Interop.Kernel32.LCMapStringEx(), System.options, System.source, and System.IntPtr.Zero.
Referenced by System.Globalization.CompareInfo.GetSortKeyLengthCore().