Terraria: System.Net.Mail.DotAtomReader.TryReadReverse
TryReadReverse()
static bool System.Net.Mail.DotAtomReader.TryReadReverse (string data, int index, out int outIndex, bool throwExceptionIfFail) inline static package
Definition at line 7 of file DotAtomReader.cs.
    {
        int num = index;
        while (0 <= index && (data[index] > '\u007f' || data[index] == '.' || MailBnfHelper.Atext[(uint)data[index]]))
        {
            index--;
        }
        if (num == index)
        {
            if (throwExceptionIfFail)
            {
                throw new FormatException(System.SR.Format(System.SR.MailHeaderFieldInvalidCharacter, data[index]));
            }
            outIndex = 0;
            return false;
        }
        if (data[index + 1] == '.')
        {
            if (throwExceptionIfFail)
            {
                throw new FormatException(System.SR.Format(System.SR.MailHeaderFieldInvalidCharacter, '.'));
            }
            outIndex = 0;
            return false;
        }
        outIndex = index;
        return true;
    }
References System.Net.Mime.MailBnfHelper.Atext, System.SR.Format(), System.index, and System.SR.MailHeaderFieldInvalidCharacter.
Referenced by System.Net.Mail.MailAddressParser.TryParseDomain(), and System.Net.Mail.MailAddressParser.TryParseLocalPart().