Terraria: Terraria.GameContent.ItemDropRules.CommonCode.DropItemFromNPC
DropItemFromNPC()
static void Terraria.GameContent.ItemDropRules.CommonCode.DropItemFromNPC (NPC npc, int itemId, int stack, bool scattered = false) inline static
Definition at line 9 of file CommonCode.cs.
    {
        if (itemId > 0 && itemId < ItemID.Count)
        {
            int x = (int)npc.position.X + npc.width / 2;
            int y = (int)npc.position.Y + npc.height / 2;
            if (scattered)
            {
                x = (int)npc.position.X + Main.rand.Next(npc.width + 1);
                y = (int)npc.position.Y + Main.rand.Next(npc.height + 1);
            }
            int itemIndex = Item.NewItem(npc.GetItemSource_Loot(), x, y, 0, 0, itemId, stack, noBroadcast: false, -1);
            ModifyItemDropFromNPC(npc, itemIndex);
        }
    }
References Terraria.ID.ItemID.Count, Terraria.NPC.GetItemSource_Loot(), Terraria.Entity.height, Terraria.GameContent.ItemDropRules.CommonCode.ModifyItemDropFromNPC(), Terraria.Item.NewItem(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Entity.position, Terraria.Main.rand, and Terraria.Entity.width.
Referenced by Terraria.GameContent.ItemDropRules.CommonCode.DropItemForEachInteractingPlayerOnThePlayer(), Terraria.GameContent.ItemDropRules.CommonCode.DropItemLocalPerClientAndSetNPCMoneyTo0(), Terraria.GameContent.ItemDropRules.CommonDrop.TryDroppingItem(), Terraria.GameContent.ItemDropRules.CommonDropNotScalingWithLuck.TryDroppingItem(), Terraria.GameContent.ItemDropRules.CommonDropWithRerolls.TryDroppingItem(), Terraria.GameContent.ItemDropRules.DropOneByOne.TryDroppingItem(), Terraria.GameContent.ItemDropRules.FromOptionsWithoutRepeatsDropRule.TryDroppingItem(), Terraria.GameContent.ItemDropRules.MechBossSpawnersDropRule.TryDroppingItem(), Terraria.GameContent.ItemDropRules.OneFromOptionsDropRule.TryDroppingItem(), Terraria.GameContent.ItemDropRules.OneFromOptionsNotScaledWithLuckDropRule.TryDroppingItem(), and Terraria.GameContent.ItemDropRules.SlimeBodyItemDropRule.TryDroppingItem().