Terraria: Terraria.GameContent.ItemDropRules.CommonCode.DropItemLocalPerClientAndSetNPCMoneyTo0
DropItemLocalPerClientAndSetNPCMoneyTo0()
static void Terraria.GameContent.ItemDropRules.CommonCode.DropItemLocalPerClientAndSetNPCMoneyTo0 (NPC npc, int itemId, int stack, bool interactionRequired = true) inline static
Definition at line 25 of file CommonCode.cs.
    {
        if (itemId <= 0 || itemId >= ItemID.Count)
        {
            return;
        }
        if (Main.netMode == 2)
        {
            int num = Item.NewItem(npc.GetItemSource_Loot(), (int)npc.position.X, (int)npc.position.Y, npc.width, npc.height, itemId, stack, noBroadcast: true, -1);
            Main.timeItemSlotCannotBeReusedFor[num] = 54000;
            for (int i = 0; i < 255; i++)
            {
                if (Main.player[i].active && (npc.playerInteraction[i] || !interactionRequired))
                {
                    NetMessage.SendData(90, i, -1, null, num);
                }
            }
            Main.item[num].active = false;
        }
        else
        {
            DropItemFromNPC(npc, itemId, stack);
        }
        npc.value = 0f;
    }
References Terraria.ID.ItemID.Count, Terraria.GameContent.ItemDropRules.CommonCode.DropItemFromNPC(), Terraria.NPC.GetItemSource_Loot(), Terraria.Entity.height, Terraria.Main.item, Terraria.Main.netMode, Terraria.Item.NewItem(), Terraria.Main.player, Terraria.NPC.playerInteraction, Terraria.Entity.position, Terraria.NetMessage.SendData(), Terraria.Main.timeItemSlotCannotBeReusedFor, Terraria.Entity.width, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.GameContent.ItemDropRules.DropLocalPerClientAndResetsNPCMoneyTo0.TryDroppingItem().