Terraria: WorldGen.Hooks.Initialize
Initialize()
static void WorldGen.Hooks.Initialize () inline static
         {
             Player.Hooks.OnEnterWorld += delegate(Player player)
             {
                 if (player.whoAmI == Main.myPlayer)
                 {
                     WorldLoaded();
                     if (Main.netMode != 1)
                     {
                         Main.FixUIScale();
                     }
                 }
             };
             OnWorldLoad += mysticLogsEvent.StartWorld;
             OnWorldLoad += Main.checkHalloween;
             OnWorldLoad += Main.checkXMas;
         }
References Main.checkHalloween(), Main.checkXMas(), Main.FixUIScale(), Main.myPlayer, WorldGen.mysticLogsEvent, Main.netMode, Player.Hooks.OnEnterWorld, WorldGen.Hooks.OnWorldLoad, MysticLogFairiesEvent.StartWorld(), Entity.whoAmI, and WorldGen.Hooks.WorldLoaded().
Referenced by Main.Initialize_AlmostEverything().