Terraria: System.Xml.Xsl.XsltOld.XsltCompileContext.XsltFunctionImpl.IteratorToString
IteratorToString()
static string System.Xml.Xsl.XsltOld.XsltCompileContext.XsltFunctionImpl.IteratorToString (XPathNodeIterator it) inline static private
Definition at line 69 of file XsltCompileContext.cs.
        {
            if (it.MoveNext())
            {
                return it.Current.Value;
            }
            return string.Empty;
        }
References System.Xml.Dictionary.
Referenced by System.Xml.Xsl.XsltOld.XsltCompileContext.XsltFunctionImpl.ToBoolean(), System.Xml.Xsl.XsltOld.XsltCompileContext.XsltFunctionImpl.ToNumber(), and System.Xml.Xsl.XsltOld.XsltCompileContext.XsltFunctionImpl.ToString().