Terraria: Terraria.GameContent.ObjectInteractions.AHoverInteractionChecker.AttemptInteraction
AttemptInteraction()
HoverStatus Terraria.GameContent.ObjectInteractions.AHoverInteractionChecker.AttemptInteraction (Player player, Rectangle Hitbox) inline package inherited
Definition at line 16 of file AHoverInteractionChecker.cs.
    {
        Point point = Hitbox.ClosestPointInRect(player.Center).ToTileCoordinates();
        if (!player.IsInTileInteractionRange(point.X, point.Y, TileReachCheckSettings.Simple))
        {
            return HoverStatus.NotSelectable;
        }
        Matrix matrix = Matrix.Invert(Main.GameViewMatrix.ZoomMatrix);
        Vector2 vector = Main.ReverseGravitySupport(Main.MouseScreen);
        Vector2.Transform(Main.screenPosition, matrix);
        Vector2 v = vector + Main.screenPosition;
        bool flag = Hitbox.Contains(v.ToPoint());
        bool flag2 = flag;
        bool? flag3 = AttemptOverridingHoverStatus(player, Hitbox);
        if (flag3.HasValue)
        {
            flag2 = flag3.Value;
        }
        flag2 &= !player.lastMouseInterface;
        bool flag4 = !Main.SmartCursorIsUsed && !PlayerInput.UsingGamepad;
        if (!flag2)
        {
            if (!flag4)
            {
                return HoverStatus.SelectableButNotSelected;
            }
            return HoverStatus.NotSelectable;
        }
        Main.HasInteractibleObjectThatIsNotATile = true;
        if (flag)
        {
            DoHoverEffect(player, Hitbox);
        }
        if (PlayerInput.UsingGamepad)
        {
            player.GamepadEnableGrappleCooldown();
        }
        bool flag5 = ShouldBlockInteraction(player, Hitbox);
        if (Main.mouseRight && Main.mouseRightRelease && !flag5)
        {
            Main.mouseRightRelease = false;
            player.tileInteractAttempted = true;
            player.tileInteractionHappened = true;
            player.releaseUseTile = false;
            PerformInteraction(player, Hitbox);
        }
        if (!Main.SmartCursorIsUsed && !PlayerInput.UsingGamepad)
        {
            return HoverStatus.NotSelectable;
        }
        if (!flag4)
        {
            return HoverStatus.Selected;
        }
        return HoverStatus.NotSelectable;
    }
References Terraria.GameContent.ObjectInteractions.AHoverInteractionChecker.AttemptOverridingHoverStatus(), Terraria.Entity.Center, Microsoft.Xna.Framework.Rectangle.Contains(), Terraria.GameContent.ObjectInteractions.AHoverInteractionChecker.DoHoverEffect(), Terraria.Player.GamepadEnableGrappleCooldown(), Terraria.Main.GameViewMatrix, Microsoft.Xna.Framework.Matrix.Invert(), Terraria.Player.IsInTileInteractionRange(), Terraria.Player.lastMouseInterface, Terraria.Main.mouseRight, Terraria.Main.mouseRightRelease, Terraria.Main.MouseScreen, Terraria.GameContent.ObjectInteractions.AHoverInteractionChecker.PerformInteraction(), Terraria.Main.ReverseGravitySupport(), Terraria.Main.screenPosition, Terraria.GameContent.ObjectInteractions.AHoverInteractionChecker.ShouldBlockInteraction(), Terraria.DataStructures.TileReachCheckSettings.Simple, Terraria.Main.SmartCursorIsUsed, Microsoft.Xna.Framework.Vector2.Transform(), Terraria.GameInput.PlayerInput.UsingGamepad, Microsoft.Xna.Framework.Point.X, and Microsoft.Xna.Framework.Point.Y.
Referenced by Terraria.Graphics.Renderers.ReturnGatePlayerRenderer.DrawReturnGateInWorld().