Terraria: Terraria.GameContent.ItemDropRules.CommonCode.DropItemForEachInteractingPlayerOnThePlayer
DropItemForEachInteractingPlayerOnThePlayer()
static void Terraria.GameContent.ItemDropRules.CommonCode.DropItemForEachInteractingPlayerOnThePlayer (NPC npc, int itemId, UnifiedRandom rng, int chanceNumerator, int chanceDenominator, int stack = 1, bool interactionRequired = true) inline static
Definition at line 51 of file CommonCode.cs.
    {
        if (itemId <= 0 || itemId >= ItemID.Count)
        {
            return;
        }
        if (Main.netMode == 2)
        {
            for (int i = 0; i < 255; i++)
            {
                Player player = Main.player[i];
                if (player.active && (npc.playerInteraction[i] || !interactionRequired) && rng.Next(chanceDenominator) < chanceNumerator)
                {
                    int itemIndex = Item.NewItem(npc.GetItemSource_Loot(), player.position, player.Size, itemId, stack, noBroadcast: false, -1);
                    ModifyItemDropFromNPC(npc, itemIndex);
                }
            }
        }
        else if (rng.Next(chanceDenominator) < chanceNumerator)
        {
            DropItemFromNPC(npc, itemId, stack);
        }
        npc.value = 0f;
    }
References Terraria.Entity.active, Terraria.ID.ItemID.Count, Terraria.GameContent.ItemDropRules.CommonCode.DropItemFromNPC(), Terraria.NPC.GetItemSource_Loot(), Terraria.GameContent.ItemDropRules.CommonCode.ModifyItemDropFromNPC(), Terraria.Main.netMode, Terraria.Item.NewItem(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Main.player, Terraria.NPC.playerInteraction, Terraria.Entity.position, and Terraria.Entity.Size.
Referenced by Terraria.GameContent.ItemDropRules.DropPerPlayerOnThePlayer.TryDroppingItem().