Terraria: Terraria.GameContent.ItemDropRules.CommonCode.ModifyItemDropFromNPC
ModifyItemDropFromNPC()
static void Terraria.GameContent.ItemDropRules.CommonCode.ModifyItemDropFromNPC (NPC npc, int itemIndex) inline static
Definition at line 76 of file CommonCode.cs.
    {
        Item item = Main.item[itemIndex];
        switch (item.type)
        {
        case 23:
            if (npc.type == 1 && npc.netID != -1 && npc.netID != -2 && npc.netID != -5 && npc.netID != -6)
            {
                item.color = npc.color;
                NetMessage.SendData(88, -1, -1, null, itemIndex, 1f);
            }
            if (Main.remixWorld && npc.type == 59)
            {
                item.color = new Color(255, 127, 0);
                NetMessage.SendData(88, -1, -1, null, itemIndex, 1f);
            }
            break;
        case 319:
            switch (npc.netID)
            {
            case 542:
                item.color = new Color(189, 148, 96, 255);
                NetMessage.SendData(88, -1, -1, null, itemIndex, 1f);
                break;
            case 543:
                item.color = new Color(112, 85, 89, 255);
                NetMessage.SendData(88, -1, -1, null, itemIndex, 1f);
                break;
            case 544:
                item.color = new Color(145, 27, 40, 255);
                NetMessage.SendData(88, -1, -1, null, itemIndex, 1f);
                break;
            case 545:
                item.color = new Color(158, 113, 164, 255);
                NetMessage.SendData(88, -1, -1, null, itemIndex, 1f);
                break;
            }
            break;
        }
    }
References Terraria.NPC.color, Terraria.Main.item, Terraria.NPC.netID, Terraria.Main.remixWorld, Terraria.NetMessage.SendData(), and Terraria.NPC.type.
Referenced by Terraria.GameContent.ItemDropRules.CommonCode.DropItemForEachInteractingPlayerOnThePlayer(), and Terraria.GameContent.ItemDropRules.CommonCode.DropItemFromNPC().