Terraria: System.Diagnostics.ActivityTraceId.IsLowerCaseHexAndNotAllZeros
IsLowerCaseHexAndNotAllZeros()
static bool System.Diagnostics.ActivityTraceId.IsLowerCaseHexAndNotAllZeros (ReadOnlySpan< char > idData) inline static package
Definition at line 146 of file ActivityTraceId.cs.
    {
        bool result = false;
        for (int i = 0; i < idData.Length; i++)
        {
            char c = idData[i];
            if (!System.HexConverter.IsHexLowerChar(c))
            {
                return false;
            }
            if (c != '0')
            {
                result = true;
            }
        }
        return result;
    }
References System.HexConverter.IsHexLowerChar(), and System.ReadOnlySpan< T >.Length.
Referenced by System.Diagnostics.ActivitySpanId.CreateFromString(), System.Diagnostics.ActivityTraceId.CreateFromString(), and System.Diagnostics.Activity.TryConvertIdToContext().