Terraria: System.Diagnostics.ActivityTraceId.CreateFromString
CreateFromString()
static ActivityTraceId System.Diagnostics.ActivityTraceId.CreateFromString (ReadOnlySpan< char > idData) inline static
Definition at line 39 of file ActivityTraceId.cs.
    {
        if (idData.Length != 32 || !IsLowerCaseHexAndNotAllZeros(idData))
        {
            throw new ArgumentOutOfRangeException("idData");
        }
        return new ActivityTraceId(idData.ToString());
    }
References System.Diagnostics.ActivityTraceId.ActivityTraceId(), System.Diagnostics.ActivityTraceId.IsLowerCaseHexAndNotAllZeros(), System.ReadOnlySpan< T >.Length, and System.ReadOnlySpan< T >.ToString().
Referenced by System.Diagnostics.Activity.TrySetTraceIdFromParent().