Terraria: System.Diagnostics.ActivityTraceId.CreateFromBytes
CreateFromBytes()
static ActivityTraceId System.Diagnostics.ActivityTraceId.CreateFromBytes (ReadOnlySpan< byte > idData) inline static
Definition at line 25 of file ActivityTraceId.cs.
    {
        if (idData.Length != 16)
        {
            throw new ArgumentOutOfRangeException("idData");
        }
        return new ActivityTraceId(System.HexConverter.ToString(idData, System.HexConverter.Casing.Lower));
    }
References System.Diagnostics.ActivityTraceId.ActivityTraceId(), System.ReadOnlySpan< T >.Length, and System.HexConverter.ToString().
Referenced by System.Diagnostics.ActivityTraceId.CreateRandom().