Terraria: System.Security.Cryptography.PKCS1MaskGenerationMethod.GenerateMask
GenerateMask()
override byte[] System.Security.Cryptography.PKCS1MaskGenerationMethod.GenerateMask (byte[] rgbSeed, int cbReturn) inline
Definition at line 31 of file PKCS1MaskGenerationMethod.cs.
    {
        using HashAlgorithm hashAlgorithm = CryptoConfig.CreateFromName(_hashNameValue) as HashAlgorithm;
        if (hashAlgorithm == null)
        {
            throw new CryptographicException(System.SR.Format(System.SR.Cryptography_UnknownHashAlgorithm, _hashNameValue));
        }
        byte[] array = new byte[4];
        byte[] array2 = new byte[cbReturn];
        uint num = 0u;
        for (int i = 0; i < array2.Length; i += hashAlgorithm.Hash.Length)
        {
            BinaryPrimitives.WriteUInt32BigEndian(array, num++);
            hashAlgorithm.TransformBlock(rgbSeed, 0, rgbSeed.Length, rgbSeed, 0);
            hashAlgorithm.TransformFinalBlock(array, 0, 4);
            byte[] hash = hashAlgorithm.Hash;
            hashAlgorithm.Initialize();
            Buffer.BlockCopy(hash, 0, array2, i, Math.Min(array2.Length - i, hash.Length));
        }
        return array2;
    }
References System.Security.Cryptography.PKCS1MaskGenerationMethod._hashNameValue, System.array, System.Buffer.BlockCopy(), System.Security.Cryptography.CryptoConfig.CreateFromName(), System.SR.Cryptography_UnknownHashAlgorithm, System.SR.Format(), System.Security.Cryptography.HashAlgorithm, System.Math.Min(), and System.Buffers.Binary.BinaryPrimitives.WriteUInt32BigEndian().