Terraria: Terraria.GameContent.Skies.CreditsRoll.CreditsRollComposer.PlaySegment_ClothierChasingTruffle
PlaySegment_ClothierChasingTruffle()
SegmentInforReport Terraria.GameContent.Skies.CreditsRoll.CreditsRollComposer.PlaySegment_ClothierChasingTruffle (int startTime, Vector2 sceneAnchorPosition) inline private
Definition at line 1556 of file CreditsRollComposer.cs.
    {
        sceneAnchorPosition += GetSceneFixVector();
        int num = startTime;
        int num2 = 10;
        sceneAnchorPosition.X += num2;
        Asset<Texture2D> val = TextureAssets.Extra[225];
        Rectangle rectangle = val.Frame();
        DrawData data = new DrawData(val.Value, Vector2.Zero, rectangle, Color.White, 0f, rectangle.Size() * new Vector2(0.5f, 1f) + new Vector2(num2, -42f), 1f, SpriteEffects.None);
        Segments.AnimationSegmentWithActions<Segments.LooseSprite> animationSegmentWithActions = new Segments.SpriteSegment(val, num, data, sceneAnchorPosition + _backgroundOffset).UseShaderEffect(new Segments.SpriteSegment.MaskedFadeEffect()).Then(new Actions.Sprites.Fade(0f)).With(new Actions.Sprites.Fade(1f, 60));
        _segments.Add(animationSegmentWithActions);
        Segments.AnimationSegmentWithActions<NPC> animationSegmentWithActions2 = new Segments.NPCSegment(startTime, 160, sceneAnchorPosition + new Vector2(20f, 0f), _originAtBottom).Then(new Actions.NPCs.Fade(255)).With(new Actions.NPCs.Fade(-5, 51)).Then(new Actions.NPCs.LookAt(1))
            .Then(new Actions.NPCs.Wait(60))
            .Then(new Actions.NPCs.LookAt(-1));
        animationSegmentWithActions.Then(new Actions.Sprites.Wait((int)animationSegmentWithActions2.DedicatedTimeNeeded));
        num += (int)animationSegmentWithActions2.DedicatedTimeNeeded;
        int num3 = 60;
        Segments.EmoteSegment item = new Segments.EmoteSegment(10, num, num3, sceneAnchorPosition + new Vector2(20f, 0f) + _emoteBubbleOffsetWhenOnRight, SpriteEffects.None);
        animationSegmentWithActions2.Then(new Actions.NPCs.Wait(num3));
        animationSegmentWithActions.Then(new Actions.Sprites.Wait(num3));
        num += num3;
        Segments.EmoteSegment item2 = new Segments.EmoteSegment(3, num, num3, sceneAnchorPosition + new Vector2(20f, 0f) + _emoteBubbleOffsetWhenOnRight, SpriteEffects.None);
        animationSegmentWithActions2.Then(new Actions.NPCs.Wait(num3));
        animationSegmentWithActions.Then(new Actions.Sprites.Wait(num3));
        num += num3;
        Vector2 vector = new Vector2(1.2f, 0f);
        Vector2 vector2 = new Vector2(1f, 0f);
        Segments.AnimationSegmentWithActions<NPC> item3 = new Segments.NPCSegment(num, 54, sceneAnchorPosition + new Vector2(-100f, 0f), _originAtBottom).Then(new Actions.NPCs.Fade(255)).With(new Actions.NPCs.Fade(-5, 51)).Then(new Actions.NPCs.Move(vector, 60))
            .Then(new Actions.NPCs.Move(vector, 130))
            .With(new Actions.NPCs.Fade(2, 127));
        animationSegmentWithActions2.Then(new Actions.NPCs.Move(vector2, 60)).Then(new Actions.NPCs.Move(vector2, 130)).With(new Actions.NPCs.Fade(2, 127));
        animationSegmentWithActions.Then(new Actions.Sprites.Wait(60)).Then(new Actions.Sprites.Wait(130)).With(new Actions.Sprites.Fade(0f, 127));
        int num4 = 10;
        int num5 = 40;
        int timeToPlay = 70;
        Segments.EmoteSegment item4 = new Segments.EmoteSegment(134, num + num4, timeToPlay, sceneAnchorPosition + new Vector2(20f, 0f) + _emoteBubbleOffsetWhenOnLeft + vector2 * num4, SpriteEffects.FlipHorizontally, vector2);
        Segments.EmoteSegment item5 = new Segments.EmoteSegment(15, num + num5, timeToPlay, sceneAnchorPosition + new Vector2(-100f, 0f) + _emoteBubbleOffsetWhenOnLeft + vector * num5, SpriteEffects.FlipHorizontally, vector);
        _segments.Add(item3);
        _segments.Add(animationSegmentWithActions2);
        _segments.Add(item);
        _segments.Add(item2);
        _segments.Add(item4);
        _segments.Add(item5);
        num += 200;
        SegmentInforReport result = default(SegmentInforReport);
        result.totalTime = num - startTime;
        return result;
    }
References Terraria.GameContent.Skies.CreditsRoll.CreditsRollComposer._backgroundOffset, Terraria.GameContent.Skies.CreditsRoll.CreditsRollComposer._emoteBubbleOffsetWhenOnLeft, Terraria.GameContent.Skies.CreditsRoll.CreditsRollComposer._emoteBubbleOffsetWhenOnRight, Terraria.GameContent.Skies.CreditsRoll.CreditsRollComposer._originAtBottom, Terraria.GameContent.Skies.CreditsRoll.CreditsRollComposer._segments, System.Collections.Generic.List< T >.Add(), Terraria.GameContent.TextureAssets.Extra, Terraria.GameContent.Skies.CreditsRoll.CreditsRollComposer.GetSceneFixVector(), System.item, Terraria.GameContent.Animations.Segments.AnimationSegmentWithActions< T >.Then(), Terraria.GameContent.Animations.Segments.SpriteSegment.UseShaderEffect(), Microsoft.Xna.Framework.Graphics.Vector2, Microsoft.Xna.Framework.Color.White, and Microsoft.Xna.Framework.Vector2.Zero.
Referenced by Terraria.GameContent.Skies.CreditsRoll.CreditsRollComposer.FillSegments().