Terraria: System.Reflection.TypeInfo.IsAssignableFrom
IsAssignableFrom() [4/4]
virtual bool System.Reflection.TypeInfo.IsAssignableFrom ([NotNullWhen(true)] TypeInfo? typeInfo) inline virtual inherited
Reimplemented in System.Reflection.Emit.EnumBuilder, System.Reflection.Emit.GenericTypeParameterBuilder, System.Reflection.Emit.TypeBuilder, and System.Reflection.TypeDelegator.
Definition at line 159 of file TypeInfo.cs.
    {
        if (typeInfo == null)
        {
            return false;
        }
        if (this == typeInfo)
        {
            return true;
        }
        if (typeInfo.IsSubclassOf(this))
        {
            return true;
        }
        if (base.IsInterface)
        {
            return typeInfo.ImplementInterface(this);
        }
        if (IsGenericParameter)
        {
            Type[] genericParameterConstraints = GetGenericParameterConstraints();
            for (int i = 0; i < genericParameterConstraints.Length; i++)
            {
                if (!genericParameterConstraints[i].IsAssignableFrom(typeInfo))
                {
                    return false;
                }
            }
            return true;
        }
        return false;
    }
References System.Type.GetGenericParameterConstraints(), System.Type.ImplementInterface(), System.Reflection.TypeInfo.IsAssignableFrom(), System.Type.IsGenericParameter, and System.Type.IsSubclassOf().
Referenced by System.Reflection.TypeInfo.IsAssignableFrom().