Terraria: System.Reflection.TypeInfo.AsType
AsType()
virtual Type System.Reflection.TypeInfo.AsType () inline virtual inherited
Definition at line 106 of file TypeInfo.cs.
    {
        return this;
    }
Referenced by System.Xml.Xsl.IlGen.XmlILModule.BakeMethods(), System.Xml.Serialization.XmlSerializationILGen.GenerateBaseSerializer(), System.Xml.Serialization.XmlSerializationWriterILGen.GenerateEnd(), System.Xml.Serialization.XmlSerializationReaderILGen.GenerateEnd(), System.Xml.Serialization.XmlSerializationILGen.GenerateSerializerContract(), System.Reflection.Emit.SymbolType.IsAssignableFrom(), System.Reflection.Emit.TypeBuilderInstantiation.IsAssignableFrom(), System.RuntimeType.IsAssignableFrom(), System.Reflection.Emit.EnumBuilder.IsAssignableFrom(), System.Reflection.Emit.GenericTypeParameterBuilder.IsAssignableFrom(), System.Reflection.Emit.TypeBuilder.IsAssignableFrom(), and System.Reflection.TypeDelegator.IsAssignableFrom().