Terraria: System.Reflection.TypeInfo.GetRankString
GetRankString()
static string System.Reflection.TypeInfo.GetRankString (int rank) inline static package inherited
Definition at line 192 of file TypeInfo.cs.
    {
        if (rank <= 0)
        {
            throw new IndexOutOfRangeException();
        }
        if (rank != 1)
        {
            return "[" + new string(',', rank - 1) + "]";
        }
        return "[*]";
    }
Referenced by System.Reflection.Emit.EnumBuilder.MakeArrayType(), System.Reflection.Emit.GenericTypeParameterBuilder.MakeArrayType(), System.Reflection.Emit.SymbolType.MakeArrayType(), and System.Reflection.Emit.TypeBuilder.MakeArrayType().