Terraria: WorkshopIssueReporter.ReportDownloadProblem
ReportDownloadProblem()
void WorkshopIssueReporter.ReportDownloadProblem (string textKey, string path, Exception exception) inline
     {
         object obj = new
         {
             FilePath = path,
             Reason = exception.ToString()
         };
         string textValueWith = Language.GetTextValueWith(textKey, obj);
         AddReport(textValueWith);
         NotifyReportsScreen();
     }
References AddReport(), Language.GetTextValueWith(), and NotifyReportsScreen().