Terraria: IngameOptions.DrawValueBar
DrawValueBar()
static float IngameOptions.DrawValueBar (SpriteBatch sb, float scale, float perc, int lockState = 0, Utils.ColorLerpMethod colorMethod = null) inline static
     {
         if (colorMethod == null)
         {
             colorMethod = Utils.ColorLerp_BlackToWhite;
         }
         Texture2D value = TextureAssets.ColorBar.Value;
         Vector2 vector = new Vector2(value.Width, value.Height) * scale;
         valuePosition.X -= (int)vector.X;
         Rectangle rectangle = new Rectangle((int)valuePosition.X, (int)valuePosition.Y - (int)vector.Y / 2, (int)vector.X, (int)vector.Y);
         Rectangle destinationRectangle = rectangle;
         sb.Draw(value, rectangle, Color.White);
         int num = 167;
         float num2 = (float)rectangle.X + 5f * scale;
         float num3 = (float)rectangle.Y + 4f * scale;
         for (float num4 = 0f; num4 < (float)num; num4 += 1f)
         {
             float percent = num4 / (float)num;
             sb.Draw(TextureAssets.ColorBlip.Value, new Vector2(num2 + num4 * scale, num3), null, colorMethod(percent), 0f, Vector2.Zero, scale, SpriteEffects.None, 0f);
         }
         rectangle.Inflate((int)(-5f * scale), 0);
         bool flag = rectangle.Contains(new Point(Main.mouseX, Main.mouseY));
         if (lockState == 2)
         {
             flag = false;
         }
         if (flag || lockState == 1)
         {
             sb.Draw(TextureAssets.ColorHighlight.Value, destinationRectangle, Main.OurFavoriteColor);
         }
         sb.Draw(TextureAssets.ColorSlider.Value, new Vector2(num2 + 167f * scale * perc, num3 + 4f * scale), null, Color.White, 0f, new Vector2(0.5f * (float)TextureAssets.ColorSlider.Width(), 0.5f * (float)TextureAssets.ColorSlider.Height()), scale, SpriteEffects.None, 0f);
         if (Main.mouseX >= rectangle.X && Main.mouseX <= rectangle.X + rectangle.Width)
         {
             inBar = flag;
             return (float)(Main.mouseX - rectangle.X) / (float)rectangle.Width;
         }
         inBar = false;
         if (rectangle.X >= Main.mouseX)
         {
             return 0f;
         }
         return 1f;
     }
References Color, TextureAssets.ColorBar, TextureAssets.ColorBlip, TextureAssets.ColorHighlight, Utils.ColorLerp_BlackToWhite(), TextureAssets.ColorSlider, Main.mouseX, Main.mouseY, Main.OurFavoriteColor, and Asset< T >.Value.
Referenced by Draw(), Main.DrawMenu(), and UIKeybindingSliderItem.DrawSelf().