Terraria: IngameOptions.Close
Close()
static void IngameOptions.Close () inline static
     {
         if (Main.setKey == -1)
         {
             Main.ingameOptionsWindow = false;
             SoundEngine.PlaySound(11);
             Recipe.FindRecipes();
             Main.playerInventory = true;
             Main.SaveSettings();
         }
     }
References Recipe.FindRecipes(), Main.ingameOptionsWindow, Main.playerInventory, SoundEngine.PlaySound(), Main.SaveSettings(), and Main.setKey.
Referenced by Draw(), Main.DrawInterface_29_SettingsButton(), AchievementTagHandler.AchievementSnippet.OnClick(), Player.ToggleCreativeMenu(), Player.ToggleInv(), and Player.TryOpeningInGameOptionsBasedOnInput().