Terraria: IngameOptions.Draw
Draw()
static void IngameOptions.Draw (Main mainInstance, SpriteBatch sb) inline static
     {
         _canConsumeHover = true;
         for (int i = 0; i < skipRightSlot.Length; i++)
         {
             skipRightSlot[i] = false;
         }
         bool flag = GameCulture.FromCultureName(GameCulture.CultureName.Russian).IsActive || GameCulture.FromCultureName(GameCulture.CultureName.Portuguese).IsActive || GameCulture.FromCultureName(GameCulture.CultureName.Polish).IsActive || GameCulture.FromCultureName(GameCulture.CultureName.French).IsActive;
         bool isActive = GameCulture.FromCultureName(GameCulture.CultureName.Polish).IsActive;
         bool isActive2 = GameCulture.FromCultureName(GameCulture.CultureName.German).IsActive;
         bool flag2 = GameCulture.FromCultureName(GameCulture.CultureName.Italian).IsActive || GameCulture.FromCultureName(GameCulture.CultureName.Spanish).IsActive;
         bool flag3 = false;
         int num = 70;
         float scale = 0.75f;
         float num2 = 60f;
         float num3 = 300f;
         if (flag)
         {
             flag3 = true;
         }
         if (isActive)
         {
             num3 = 200f;
         }
         new Vector2(Main.mouseX, Main.mouseY);
         bool flag4 = Main.mouseLeft && Main.mouseLeftRelease;
         Vector2 vector = new Vector2(Main.screenWidth, Main.screenHeight);
         Vector2 vector2 = new Vector2(670f, 480f);
         Vector2 vector3 = vector / 2f - vector2 / 2f;
         int num4 = 20;
         _GUIHover = new Rectangle((int)(vector3.X - (float)num4), (int)(vector3.Y - (float)num4), (int)(vector2.X + (float)(num4 * 2)), (int)(vector2.Y + (float)(num4 * 2)));
         Utils.DrawInvBG(sb, vector3.X - (float)num4, vector3.Y - (float)num4, vector2.X + (float)(num4 * 2), vector2.Y + (float)(num4 * 2), new Color(33, 15, 91, 255) * 0.685f);
         if (new Rectangle((int)vector3.X - num4, (int)vector3.Y - num4, (int)vector2.X + num4 * 2, (int)vector2.Y + num4 * 2).Contains(new Point(Main.mouseX, Main.mouseY)))
         {
             Main.player[Main.myPlayer].mouseInterface = true;
         }
         Utils.DrawBorderString(sb, Language.GetTextValue("GameUI.SettingsMenu"), vector3 + vector2 * new Vector2(0.5f, 0f), Color.White, 1f, 0.5f);
         if (flag)
         {
             Utils.DrawInvBG(sb, vector3.X + (float)(num4 / 2), vector3.Y + (float)(num4 * 5 / 2), vector2.X / 3f - (float)num4, vector2.Y - (float)(num4 * 3));
             Utils.DrawInvBG(sb, vector3.X + vector2.X / 3f + (float)num4, vector3.Y + (float)(num4 * 5 / 2), vector2.X * 2f / 3f - (float)(num4 * 3 / 2), vector2.Y - (float)(num4 * 3));
         }
         else
         {
             Utils.DrawInvBG(sb, vector3.X + (float)(num4 / 2), vector3.Y + (float)(num4 * 5 / 2), vector2.X / 2f - (float)num4, vector2.Y - (float)(num4 * 3));
             Utils.DrawInvBG(sb, vector3.X + vector2.X / 2f + (float)num4, vector3.Y + (float)(num4 * 5 / 2), vector2.X / 2f - (float)(num4 * 3 / 2), vector2.Y - (float)(num4 * 3));
         }
         float num5 = 0.7f;
         float num6 = 0.8f;
         float num7 = 0.01f;
         if (flag)
         {
             num5 = 0.4f;
             num6 = 0.44f;
         }
         if (isActive2)
         {
             num5 = 0.55f;
             num6 = 0.6f;
         }
         if (oldLeftHover != leftHover && leftHover != -1)
         {
             SoundEngine.PlaySound(12);
         }
         if (oldRightHover != rightHover && rightHover != -1)
         {
             SoundEngine.PlaySound(12);
         }
         if (flag4 && rightHover != -1 && !noSound)
         {
             SoundEngine.PlaySound(12);
         }
         oldLeftHover = leftHover;
         oldRightHover = rightHover;
         noSound = false;
         bool flag5 = SocialAPI.Network != null && SocialAPI.Network.CanInvite();
         int num8 = (flag5 ? 1 : 0);
         int num9 = 5 + num8 + 2;
         Vector2 vector4 = new Vector2(vector3.X + vector2.X / 4f, vector3.Y + (float)(num4 * 5 / 2));
         Vector2 vector5 = new Vector2(0f, vector2.Y - (float)(num4 * 5)) / (num9 + 1);
         if (flag)
         {
             vector4.X -= 55f;
         }
         UILinkPointNavigator.Shortcuts.INGAMEOPTIONS_BUTTONS_LEFT = num9 + 1;
         for (int j = 0; j <= num9; j++)
         {
             bool flag6 = false;
             if (_leftSideCategoryMapping.TryGetValue(j, out var value))
             {
                 flag6 = category == value;
             }
             if (leftHover == j || flag6)
             {
                 leftScale[j] += num7;
             }
             else
             {
                 leftScale[j] -= num7;
             }
             if (leftScale[j] < num5)
             {
                 leftScale[j] = num5;
             }
             if (leftScale[j] > num6)
             {
                 leftScale[j] = num6;
             }
         }
         leftHover = -1;
         int num10 = category;
         int num11 = 0;
         if (DrawLeftSide(sb, Lang.menu[114].Value, num11, vector4, vector5, leftScale))
         {
             leftHover = num11;
             if (flag4)
             {
                 category = 0;
                 SoundEngine.PlaySound(10);
             }
         }
         num11++;
         if (DrawLeftSide(sb, Lang.menu[210].Value, num11, vector4, vector5, leftScale))
         {
             leftHover = num11;
             if (flag4)
             {
                 category = 1;
                 SoundEngine.PlaySound(10);
             }
         }
         num11++;
         if (DrawLeftSide(sb, Lang.menu[63].Value, num11, vector4, vector5, leftScale))
         {
             leftHover = num11;
             if (flag4)
             {
                 category = 2;
                 SoundEngine.PlaySound(10);
             }
         }
         num11++;
         if (DrawLeftSide(sb, Lang.menu[218].Value, num11, vector4, vector5, leftScale))
         {
             leftHover = num11;
             if (flag4)
             {
                 category = 3;
                 SoundEngine.PlaySound(10);
             }
         }
         num11++;
         if (DrawLeftSide(sb, Lang.menu[66].Value, num11, vector4, vector5, leftScale))
         {
             leftHover = num11;
             if (flag4)
             {
                 Close();
                 IngameFancyUI.OpenKeybinds();
             }
         }
         num11++;
         if (flag5 && DrawLeftSide(sb, Lang.menu[147].Value, num11, vector4, vector5, leftScale))
         {
             leftHover = num11;
             if (flag4)
             {
                 Close();
                 SocialAPI.Network.OpenInviteInterface();
             }
         }
         if (flag5)
         {
             num11++;
         }
         if (DrawLeftSide(sb, Lang.menu[131].Value, num11, vector4, vector5, leftScale))
         {
             leftHover = num11;
             if (flag4)
             {
                 Close();
                 IngameFancyUI.OpenAchievements();
             }
         }
         num11++;
         if (DrawLeftSide(sb, Lang.menu[118].Value, num11, vector4, vector5, leftScale))
         {
             leftHover = num11;
             if (flag4)
             {
                 Close();
             }
         }
         num11++;
         if (DrawLeftSide(sb, Lang.inter[35].Value, num11, vector4, vector5, leftScale))
         {
             leftHover = num11;
             if (flag4)
             {
                 Close();
                 Main.menuMode = 10;
                 Main.gameMenu = true;
                 WorldGen.SaveAndQuit();
             }
         }
         num11++;
         if (num10 != category)
         {
             for (int k = 0; k < rightScale.Length; k++)
             {
                 rightScale[k] = 0f;
             }
         }
         int num12 = 0;
         int num13 = 0;
         switch (category)
         {
         case 0:
             num13 = 16;
             num5 = 1f;
             num6 = 1.001f;
             num7 = 0.001f;
             break;
         case 1:
             num13 = 11;
             num5 = 1f;
             num6 = 1.001f;
             num7 = 0.001f;
             break;
         case 2:
             num13 = 12;
             num5 = 1f;
             num6 = 1.001f;
             num7 = 0.001f;
             break;
         case 3:
             num13 = 15;
             num5 = 1f;
             num6 = 1.001f;
             num7 = 0.001f;
             break;
         }
         if (flag)
         {
             num5 -= 0.1f;
             num6 -= 0.1f;
         }
         if (isActive2 && category == 3)
         {
             num5 -= 0.15f;
             num6 -= 0.15f;
         }
         if (flag2 && (category == 0 || category == 3))
         {
             num5 -= 0.2f;
             num6 -= 0.2f;
         }
         UILinkPointNavigator.Shortcuts.INGAMEOPTIONS_BUTTONS_RIGHT = num13;
         Vector2 vector6 = new Vector2(vector3.X + vector2.X * 3f / 4f, vector3.Y + (float)(num4 * 5 / 2));
         Vector2 vector7 = new Vector2(0f, vector2.Y - (float)(num4 * 3)) / (num13 + 1);
         if (category == 2)
         {
             vector7.Y -= 2f;
         }
         new Vector2(8f, 0f);
         if (flag)
         {
             vector6.X = vector3.X + vector2.X * 2f / 3f;
         }
         for (int l = 0; l < rightScale.Length; l++)
         {
             if (rightLock == l || (rightHover == l && rightLock == -1))
             {
                 rightScale[l] += num7;
             }
             else
             {
                 rightScale[l] -= num7;
             }
             if (rightScale[l] < num5)
             {
                 rightScale[l] = num5;
             }
             if (rightScale[l] > num6)
             {
                 rightScale[l] = num6;
             }
         }
         inBar = false;
         rightHover = -1;
         if (!Main.mouseLeft)
         {
             rightLock = -1;
         }
         if (rightLock == -1)
         {
             notBar = false;
         }
         if (category == 0)
         {
             int num14 = 0;
             DrawRightSide(sb, Lang.menu[65].Value, num14, vector6, vector7, rightScale[num14], 1f);
             skipRightSlot[num14] = true;
             num14++;
             vector6.X -= num;
             if (DrawRightSide(sb, Lang.menu[99].Value + " " + Math.Round(Main.musicVolume * 100f) + "%", num14, vector6, vector7, rightScale[num14], (rightScale[num14] - num5) / (num6 - num5)))
             {
                 if (rightLock == -1)
                 {
                     notBar = true;
                 }
                 noSound = true;
                 rightHover = num14;
             }
             valuePosition.X = vector3.X + vector2.X - (float)(num4 / 2) - 20f;
             valuePosition.Y -= 3f;
             float musicVolume = DrawValueBar(sb, scale, Main.musicVolume);
             if ((inBar || rightLock == num14) && !notBar)
             {
                 rightHover = num14;
                 if (Main.mouseLeft && rightLock == num14)
                 {
                     Main.musicVolume = musicVolume;
                 }
             }
             if ((float)Main.mouseX > vector3.X + vector2.X * 2f / 3f + (float)num4 && (float)Main.mouseX < valuePosition.X + 3.75f && (float)Main.mouseY > valuePosition.Y - 10f && (float)Main.mouseY <= valuePosition.Y + 10f)
             {
                 if (rightLock == -1)
                 {
                     notBar = true;
                 }
                 rightHover = num14;
             }
             if (rightHover == num14)
             {
                 UILinkPointNavigator.Shortcuts.OPTIONS_BUTTON_SPECIALFEATURE = 2;
             }
             num14++;
             if (DrawRightSide(sb, Lang.menu[98].Value + " " + Math.Round(Main.soundVolume * 100f) + "%", num14, vector6, vector7, rightScale[num14], (rightScale[num14] - num5) / (num6 - num5)))
             {
                 if (rightLock == -1)
                 {
                     notBar = true;
                 }
                 rightHover = num14;
             }
             valuePosition.X = vector3.X + vector2.X - (float)(num4 / 2) - 20f;
             valuePosition.Y -= 3f;
             float soundVolume = DrawValueBar(sb, scale, Main.soundVolume);
             if ((inBar || rightLock == num14) && !notBar)
             {
                 rightHover = num14;
                 if (Main.mouseLeft && rightLock == num14)
                 {
                     Main.soundVolume = soundVolume;
                     noSound = true;
                 }
             }
             if ((float)Main.mouseX > vector3.X + vector2.X * 2f / 3f + (float)num4 && (float)Main.mouseX < valuePosition.X + 3.75f && (float)Main.mouseY > valuePosition.Y - 10f && (float)Main.mouseY <= valuePosition.Y + 10f)
             {
                 if (rightLock == -1)
                 {
                     notBar = true;
                 }
                 rightHover = num14;
             }
             if (rightHover == num14)
             {
                 UILinkPointNavigator.Shortcuts.OPTIONS_BUTTON_SPECIALFEATURE = 3;
             }
             num14++;
             if (DrawRightSide(sb, Lang.menu[119].Value + " " + Math.Round(Main.ambientVolume * 100f) + "%", num14, vector6, vector7, rightScale[num14], (rightScale[num14] - num5) / (num6 - num5)))
             {
                 if (rightLock == -1)
                 {
                     notBar = true;
                 }
                 rightHover = num14;
             }
             valuePosition.X = vector3.X + vector2.X - (float)(num4 / 2) - 20f;
             valuePosition.Y -= 3f;
             float ambientVolume = DrawValueBar(sb, scale, Main.ambientVolume);
             if ((inBar || rightLock == num14) && !notBar)
             {
                 rightHover = num14;
                 if (Main.mouseLeft && rightLock == num14)
                 {
                     Main.ambientVolume = ambientVolume;
                     noSound = true;
                 }
             }
             if ((float)Main.mouseX > vector3.X + vector2.X * 2f / 3f + (float)num4 && (float)Main.mouseX < valuePosition.X + 3.75f && (float)Main.mouseY > valuePosition.Y - 10f && (float)Main.mouseY <= valuePosition.Y + 10f)
             {
                 if (rightLock == -1)
                 {
                     notBar = true;
                 }
                 rightHover = num14;
             }
             if (rightHover == num14)
             {
                 UILinkPointNavigator.Shortcuts.OPTIONS_BUTTON_SPECIALFEATURE = 4;
             }
             num14++;
             vector6.X += num;
             DrawRightSide(sb, "", num14, vector6, vector7, rightScale[num14], 1f);
             skipRightSlot[num14] = true;
             num14++;
             DrawRightSide(sb, Language.GetTextValue("GameUI.ZoomCategory"), num14, vector6, vector7, rightScale[num14], 1f);
             skipRightSlot[num14] = true;
             num14++;
             vector6.X -= num;
             string text = Language.GetTextValue("GameUI.GameZoom", Math.Round(Main.GameZoomTarget * 100f), Math.Round(Main.GameViewMatrix.Zoom.X * 100f));
             if (flag3)
             {
                 text = FontAssets.ItemStack.Value.CreateWrappedText(text, num3, Language.ActiveCulture.CultureInfo);
             }
             if (DrawRightSide(sb, text, num14, vector6, vector7, rightScale[num14] * 0.85f, (rightScale[num14] - num5) / (num6 - num5)))
             {
                 if (rightLock == -1)
                 {
                     notBar = true;
                 }
                 rightHover = num14;
             }
             valuePosition.X = vector3.X + vector2.X - (float)(num4 / 2) - 20f;
             valuePosition.Y -= 3f;
             float num15 = DrawValueBar(sb, scale, Main.GameZoomTarget - 1f);
             if ((inBar || rightLock == num14) && !notBar)
             {
                 rightHover = num14;
                 if (Main.mouseLeft && rightLock == num14)
                 {
                     Main.GameZoomTarget = num15 + 1f;
                 }
             }
             if ((float)Main.mouseX > vector3.X + vector2.X * 2f / 3f + (float)num4 && (float)Main.mouseX < valuePosition.X + 3.75f && (float)Main.mouseY > valuePosition.Y - 10f && (float)Main.mouseY <= valuePosition.Y + 10f)
             {
                 if (rightLock == -1)
                 {
                     notBar = true;
                 }
                 rightHover = num14;
             }
             if (rightHover == num14)
             {
                 UILinkPointNavigator.Shortcuts.OPTIONS_BUTTON_SPECIALFEATURE = 10;
             }
             num14++;
             bool flag7 = false;
             if (Main.temporaryGUIScaleSlider == -1f)
             {
                 Main.temporaryGUIScaleSlider = Main.UIScaleWanted;
             }
             string text2 = Language.GetTextValue("GameUI.UIScale", Math.Round(Main.temporaryGUIScaleSlider * 100f), Math.Round(Main.UIScale * 100f));
             if (flag3)
             {
                 text2 = FontAssets.ItemStack.Value.CreateWrappedText(text2, num3, Language.ActiveCulture.CultureInfo);
             }
             if (DrawRightSide(sb, text2, num14, vector6, vector7, rightScale[num14] * 0.75f, (rightScale[num14] - num5) / (num6 - num5)))
             {
                 if (rightLock == -1)
                 {
                     notBar = true;
                 }
                 rightHover = num14;
             }
             valuePosition.X = vector3.X + vector2.X - (float)(num4 / 2) - 20f;
             valuePosition.Y -= 3f;
             float num16 = DrawValueBar(sb, scale, MathHelper.Clamp((Main.temporaryGUIScaleSlider - 0.5f) / 1.5f, 0f, 1f));
             if ((inBar || rightLock == num14) && !notBar)
             {
                 rightHover = num14;
                 if (Main.mouseLeft && rightLock == num14)
                 {
                     Main.temporaryGUIScaleSlider = num16 * 1.5f + 0.5f;
                     Main.temporaryGUIScaleSlider = (float)(int)(Main.temporaryGUIScaleSlider * 100f) / 100f;
                     Main.temporaryGUIScaleSliderUpdate = true;
                     flag7 = true;
                 }
             }
             if (!flag7 && Main.temporaryGUIScaleSliderUpdate && Main.temporaryGUIScaleSlider != -1f)
             {
                 Main.UIScale = Main.temporaryGUIScaleSlider;
                 Main.temporaryGUIScaleSliderUpdate = false;
             }
             if ((float)Main.mouseX > vector3.X + vector2.X * 2f / 3f + (float)num4 && (float)Main.mouseX < valuePosition.X + 3.75f && (float)Main.mouseY > valuePosition.Y - 10f && (float)Main.mouseY <= valuePosition.Y + 10f)
             {
                 if (rightLock == -1)
                 {
                     notBar = true;
                 }
                 rightHover = num14;
             }
             if (rightHover == num14)
             {
                 UILinkPointNavigator.Shortcuts.OPTIONS_BUTTON_SPECIALFEATURE = 11;
             }
             num14++;
             vector6.X += num;
             DrawRightSide(sb, "", num14, vector6, vector7, rightScale[num14], 1f);
             skipRightSlot[num14] = true;
             num14++;
             DrawRightSide(sb, Language.GetTextValue("GameUI.Gameplay"), num14, vector6, vector7, rightScale[num14], 1f);
             skipRightSlot[num14] = true;
             num14++;
             if (DrawRightSide(sb, Main.autoSave ? Lang.menu[67].Value : Lang.menu[68].Value, num14, vector6, vector7, rightScale[num14], (rightScale[num14] - num5) / (num6 - num5)))
             {
                 rightHover = num14;
                 if (flag4)
                 {
                     Main.autoSave = !Main.autoSave;
                 }
             }
             num14++;
             if (DrawRightSide(sb, Main.autoPause ? Lang.menu[69].Value : Lang.menu[70].Value, num14, vector6, vector7, rightScale[num14], (rightScale[num14] - num5) / (num6 - num5)))
             {
                 rightHover = num14;
                 if (flag4)
                 {
                     Main.autoPause = !Main.autoPause;
                 }
             }
             num14++;
             if (DrawRightSide(sb, Main.ReversedUpDownArmorSetBonuses ? Lang.menu[220].Value : Lang.menu[221].Value, num14, vector6, vector7, rightScale[num14], (rightScale[num14] - num5) / (num6 - num5)))
             {
                 rightHover = num14;
                 if (flag4)
                 {
                     Main.ReversedUpDownArmorSetBonuses = !Main.ReversedUpDownArmorSetBonuses;
                 }
             }
             num14++;
             if (DrawRightSide(sb, DoorOpeningHelper.PreferenceSettings switch
             {
                 DoorOpeningHelper.DoorAutoOpeningPreference.EnabledForEverything => Language.GetTextValue("UI.SmartDoorsEnabled"),
                 DoorOpeningHelper.DoorAutoOpeningPreference.EnabledForGamepadOnly => Language.GetTextValue("UI.SmartDoorsGamepad"),
                 _ => Language.GetTextValue("UI.SmartDoorsDisabled"),
             }, num14, vector6, vector7, rightScale[num14], (rightScale[num14] - num5) / (num6 - num5)))
             {
                 rightHover = num14;
                 if (flag4)
                 {
                     DoorOpeningHelper.CyclePreferences();
                 }
             }
             num14++;
             string textValue;
             if (Player.Settings.HoverControl != 0)
             {
                 _ = 1;
                 textValue = Language.GetTextValue("UI.HoverControlSettingIsClick");
             }
             else
             {
                 textValue = Language.GetTextValue("UI.HoverControlSettingIsHold");
             }
             if (DrawRightSide(sb, textValue, num14, vector6, vector7, rightScale[num14], (rightScale[num14] - num5) / (num6 - num5)))
             {
                 rightHover = num14;
                 if (flag4)
                 {
                     Player.Settings.CycleHoverControl();
                 }
             }
             num14++;
             if (DrawRightSide(sb, Language.GetTextValue(Main.SettingsEnabled_AutoReuseAllItems ? "UI.AutoReuseAllOn" : "UI.AutoReuseAllOff"), num14, vector6, vector7, rightScale[num14], (rightScale[num14] - num5) / (num6 - num5)))
             {
                 rightHover = num14;
                 if (flag4)
                 {
                     Main.SettingsEnabled_AutoReuseAllItems = !Main.SettingsEnabled_AutoReuseAllItems;
                 }
             }
             num14++;
             DrawRightSide(sb, "", num14, vector6, vector7, rightScale[num14], 1f);
             skipRightSlot[num14] = true;
             num14++;
         }
         if (category == 1)
         {
             int num17 = 0;
             if (DrawRightSide(sb, Main.showItemText ? Lang.menu[71].Value : Lang.menu[72].Value, num17, vector6, vector7, rightScale[num17], (rightScale[num17] - num5) / (num6 - num5)))
             {
                 rightHover = num17;
                 if (flag4)
                 {
                     Main.showItemText = !Main.showItemText;
                 }
             }
             num17++;
             if (DrawRightSide(sb, Lang.menu[123].Value + " " + Lang.menu[124 + Main.invasionProgressMode], num17, vector6, vector7, rightScale[num17], (rightScale[num17] - num5) / (num6 - num5)))
             {
                 rightHover = num17;
                 if (flag4)
                 {
                     Main.invasionProgressMode++;
                     if (Main.invasionProgressMode >= 3)
                     {
                         Main.invasionProgressMode = 0;
                     }
                 }
             }
             num17++;
             if (DrawRightSide(sb, Main.placementPreview ? Lang.menu[128].Value : Lang.menu[129].Value, num17, vector6, vector7, rightScale[num17], (rightScale[num17] - num5) / (num6 - num5)))
             {
                 rightHover = num17;
                 if (flag4)
                 {
                     Main.placementPreview = !Main.placementPreview;
                 }
             }
             num17++;
             if (DrawRightSide(sb, ItemSlot.Options.HighlightNewItems ? Lang.inter[117].Value : Lang.inter[116].Value, num17, vector6, vector7, rightScale[num17], (rightScale[num17] - num5) / (num6 - num5)))
             {
                 rightHover = num17;
                 if (flag4)
                 {
                     ItemSlot.Options.HighlightNewItems = !ItemSlot.Options.HighlightNewItems;
                 }
             }
             num17++;
             if (DrawRightSide(sb, Main.MouseShowBuildingGrid ? Lang.menu[229].Value : Lang.menu[230].Value, num17, vector6, vector7, rightScale[num17], (rightScale[num17] - num5) / (num6 - num5)))
             {
                 rightHover = num17;
                 if (flag4)
                 {
                     Main.MouseShowBuildingGrid = !Main.MouseShowBuildingGrid;
                 }
             }
             num17++;
             if (DrawRightSide(sb, Main.GamepadDisableInstructionsDisplay ? Lang.menu[241].Value : Lang.menu[242].Value, num17, vector6, vector7, rightScale[num17], (rightScale[num17] - num5) / (num6 - num5)))
             {
                 rightHover = num17;
                 if (flag4)
                 {
                     Main.GamepadDisableInstructionsDisplay = !Main.GamepadDisableInstructionsDisplay;
                 }
             }
             num17++;
             string textValue2 = Language.GetTextValue("UI.MinimapFrame_" + Main.MinimapFrameManagerInstance.ActiveSelectionKeyName);
             if (DrawRightSide(sb, Language.GetTextValue("UI.SelectMapBorder", textValue2), num17, vector6, vector7, rightScale[num17], (rightScale[num17] - num5) / (num6 - num5)))
             {
                 rightHover = num17;
                 if (flag4)
                 {
                     Main.MinimapFrameManagerInstance.CycleSelection();
                 }
             }
             num17++;
             vector6.X -= num;
             string text3 = Language.GetTextValue("GameUI.MapScale", Math.Round(Main.MapScale * 100f));
             if (flag3)
             {
                 text3 = FontAssets.ItemStack.Value.CreateWrappedText(text3, num3, Language.ActiveCulture.CultureInfo);
             }
             if (DrawRightSide(sb, text3, num17, vector6, vector7, rightScale[num17] * 0.85f, (rightScale[num17] - num5) / (num6 - num5)))
             {
                 if (rightLock == -1)
                 {
                     notBar = true;
                 }
                 rightHover = num17;
             }
             valuePosition.X = vector3.X + vector2.X - (float)(num4 / 2) - 20f;
             valuePosition.Y -= 3f;
             float num18 = DrawValueBar(sb, scale, (Main.MapScale - 0.5f) / 0.5f);
             if ((inBar || rightLock == num17) && !notBar)
             {
                 rightHover = num17;
                 if (Main.mouseLeft && rightLock == num17)
                 {
                     Main.MapScale = num18 * 0.5f + 0.5f;
                 }
             }
             if ((float)Main.mouseX > vector3.X + vector2.X * 2f / 3f + (float)num4 && (float)Main.mouseX < valuePosition.X + 3.75f && (float)Main.mouseY > valuePosition.Y - 10f && (float)Main.mouseY <= valuePosition.Y + 10f)
             {
                 if (rightLock == -1)
                 {
                     notBar = true;
                 }
                 rightHover = num17;
             }
             if (rightHover == num17)
             {
                 UILinkPointNavigator.Shortcuts.OPTIONS_BUTTON_SPECIALFEATURE = 12;
             }
             num17++;
             vector6.X += num;
             string activeSetKeyName = Main.ResourceSetsManager.ActiveSetKeyName;
             string textValue3 = Language.GetTextValue("UI.HealthManaStyle_" + activeSetKeyName);
             if (DrawRightSide(sb, Language.GetTextValue("UI.SelectHealthStyle", textValue3), num17, vector6, vector7, rightScale[num17], (rightScale[num17] - num5) / (num6 - num5)))
             {
                 rightHover = num17;
                 if (flag4)
                 {
                     Main.ResourceSetsManager.CycleResourceSet();
                 }
             }
             num17++;
             string textValue4 = Language.GetTextValue(BigProgressBarSystem.ShowText ? "UI.ShowBossLifeTextOn" : "UI.ShowBossLifeTextOff");
             if (DrawRightSide(sb, textValue4, num17, vector6, vector7, rightScale[num17], (rightScale[num17] - num5) / (num6 - num5)))
             {
                 rightHover = num17;
                 if (flag4)
                 {
                     BigProgressBarSystem.ToggleShowText();
                 }
             }
             num17++;
             if (DrawRightSide(sb, Main.SettingsEnabled_OpaqueBoxBehindTooltips ? Language.GetTextValue("GameUI.HoverTextBoxesOn") : Language.GetTextValue("GameUI.HoverTextBoxesOff"), num17, vector6, vector7, rightScale[num17], (rightScale[num17] - num5) / (num6 - num5)))
             {
                 rightHover = num17;
                 if (flag4)
                 {
                     Main.SettingsEnabled_OpaqueBoxBehindTooltips = !Main.SettingsEnabled_OpaqueBoxBehindTooltips;
                 }
             }
             num17++;
         }
         if (category == 2)
         {
             int num19 = 0;
             if (DrawRightSide(sb, Main.graphics.IsFullScreen ? Lang.menu[49].Value : Lang.menu[50].Value, num19, vector6, vector7, rightScale[num19], (rightScale[num19] - num5) / (num6 - num5)))
             {
                 rightHover = num19;
                 if (flag4)
                 {
                     Main.ToggleFullScreen();
                 }
             }
             num19++;
             if (DrawRightSide(sb, Lang.menu[51].Value + ": " + Main.PendingResolutionWidth + "x" + Main.PendingResolutionHeight, num19, vector6, vector7, rightScale[num19], (rightScale[num19] - num5) / (num6 - num5)))
             {
                 rightHover = num19;
                 if (flag4)
                 {
                     int num20 = 0;
                     for (int m = 0; m < Main.numDisplayModes; m++)
                     {
                         if (Main.displayWidth[m] == Main.PendingResolutionWidth && Main.displayHeight[m] == Main.PendingResolutionHeight)
{
                             num20 = m;
                             break;
                         }
                     }
                     num20++;
                     if (num20 >= Main.numDisplayModes)
                     {
                         num20 = 0;
                     }
                     Main.PendingResolutionWidth = Main.displayWidth[num20];
                     Main.PendingResolutionHeight = Main.displayHeight[num20];
                     Main.SetResolution(Main.PendingResolutionWidth, Main.PendingResolutionHeight);
                 }
             }
             num19++;
             vector6.X -= num;
             if (DrawRightSide(sb, Lang.menu[52].Value + ": " + Main.bgScroll + "%", num19, vector6, vector7, rightScale[num19], (rightScale[num19] - num5) / (num6 - num5)))
             {
                 if (rightLock == -1)
                 {
                     notBar = true;
                 }
                 noSound = true;
                 rightHover = num19;
             }
             valuePosition.X = vector3.X + vector2.X - (float)(num4 / 2) - 20f;
             valuePosition.Y -= 3f;
             float num21 = DrawValueBar(sb, scale, (float)Main.bgScroll / 100f);
             if ((inBar || rightLock == num19) && !notBar)
             {
                 rightHover = num19;
                 if (Main.mouseLeft && rightLock == num19)
                 {
                     Main.bgScroll = (int)(num21 * 100f);
                     Main.caveParallax = 1f - (float)Main.bgScroll / 500f;
                 }
             }
             if ((float)Main.mouseX > vector3.X + vector2.X * 2f / 3f + (float)num4 && (float)Main.mouseX < valuePosition.X + 3.75f && (float)Main.mouseY > valuePosition.Y - 10f && (float)Main.mouseY <= valuePosition.Y + 10f)
             {
                 if (rightLock == -1)
                 {
                     notBar = true;
                 }
                 rightHover = num19;
             }
             if (rightHover == num19)
             {
                 UILinkPointNavigator.Shortcuts.OPTIONS_BUTTON_SPECIALFEATURE = 1;
             }
             num19++;
             vector6.X += num;
             if (DrawRightSide(sb, Lang.menu[(int)(247 + Main.FrameSkipMode)].Value, num19, vector6, vector7, rightScale[num19], (rightScale[num19] - num5) / (num6 - num5)))
             {
                 rightHover = num19;
                 if (flag4)
                 {
                     Main.CycleFrameSkipMode();
                 }
             }
             num19++;
             if (DrawRightSide(sb, Language.GetTextValue("UI.LightMode_" + Lighting.Mode), num19, vector6, vector7, rightScale[num19], (rightScale[num19] - num5) / (num6 - num5)))
             {
                 rightHover = num19;
                 if (flag4)
                 {
                     Lighting.NextLightMode();
                 }
             }
             num19++;
             if (DrawRightSide(sb, Lang.menu[59 + Main.qaStyle].Value, num19, vector6, vector7, rightScale[num19], (rightScale[num19] - num5) / (num6 - num5)))
             {
                 rightHover = num19;
                 if (flag4)
                 {
                     Main.qaStyle++;
                     if (Main.qaStyle > 3)
                     {
                         Main.qaStyle = 0;
                     }
                 }
             }
             num19++;
             if (DrawRightSide(sb, Main.BackgroundEnabled ? Lang.menu[100].Value : Lang.menu[101].Value, num19, vector6, vector7, rightScale[num19], (rightScale[num19] - num5) / (num6 - num5)))
             {
                 rightHover = num19;
                 if (flag4)
                 {
                     Main.BackgroundEnabled = !Main.BackgroundEnabled;
                 }
             }
             num19++;
             if (DrawRightSide(sb, ChildSafety.Disabled ? Lang.menu[132].Value : Lang.menu[133].Value, num19, vector6, vector7, rightScale[num19], (rightScale[num19] - num5) / (num6 - num5)))
             {
                 rightHover = num19;
                 if (flag4)
                 {
                     ChildSafety.Disabled = !ChildSafety.Disabled;
                 }
             }
             num19++;
             if (DrawRightSide(sb, Language.GetTextValue("GameUI.HeatDistortion", Main.UseHeatDistortion ? Language.GetTextValue("GameUI.Enabled") : Language.GetTextValue("GameUI.Disabled")), num19, vector6, vector7, rightScale[num19], (rightScale[num19] - num5) / (num6 - num5)))
             {
                 rightHover = num19;
                 if (flag4)
                 {
                     Main.UseHeatDistortion = !Main.UseHeatDistortion;
                 }
             }
             num19++;
             if (DrawRightSide(sb, Language.GetTextValue("GameUI.StormEffects", Main.UseStormEffects ? Language.GetTextValue("GameUI.Enabled") : Language.GetTextValue("GameUI.Disabled")), num19, vector6, vector7, rightScale[num19], (rightScale[num19] - num5) / (num6 - num5)))
             {
                 rightHover = num19;
                 if (flag4)
                 {
                     Main.UseStormEffects = !Main.UseStormEffects;
                 }
             }
             num19++;
             if (DrawRightSide(sb, Language.GetTextValue("GameUI.WaveQuality", Main.WaveQuality switch
             {
                 1 => Language.GetTextValue("GameUI.QualityLow"),
                 2 => Language.GetTextValue("GameUI.QualityMedium"),
                 3 => Language.GetTextValue("GameUI.QualityHigh"),
                 _ => Language.GetTextValue("GameUI.QualityOff"),
             }), num19, vector6, vector7, rightScale[num19], (rightScale[num19] - num5) / (num6 - num5)))
             {
                 rightHover = num19;
                 if (flag4)
                 {
                     Main.WaveQuality = (Main.WaveQuality + 1) % 4;
                 }
             }
             num19++;
             if (DrawRightSide(sb, Language.GetTextValue("UI.TilesSwayInWind" + (Main.SettingsEnabled_TilesSwayInWind ? "On" : "Off")), num19, vector6, vector7, rightScale[num19], (rightScale[num19] - num5) / (num6 - num5)))
             {
                 rightHover = num19;
                 if (flag4)
                 {
                     Main.SettingsEnabled_TilesSwayInWind = !Main.SettingsEnabled_TilesSwayInWind;
                 }
             }
             num19++;
         }
         if (category == 3)
         {
             int num22 = 0;
             float num23 = num;
             if (flag)
             {
                 num2 = 126f;
             }
             Vector3 hSLVector = Main.mouseColorSlider.GetHSLVector();
             Main.mouseColorSlider.ApplyToMainLegacyBars();
             DrawRightSide(sb, Lang.menu[64].Value, num22, vector6, vector7, rightScale[num22], 1f);
             skipRightSlot[num22] = true;
             num22++;
             vector6.X -= num23;
             if (DrawRightSide(sb, "", num22, vector6, vector7, rightScale[num22], (rightScale[num22] - num5) / (num6 - num5)))
             {
                 if (rightLock == -1)
                 {
                     notBar = true;
                 }
                 rightHover = num22;
             }
             valuePosition.X = vector3.X + vector2.X - (float)(num4 / 2) - 20f;
             valuePosition.Y -= 3f;
             valuePosition.X -= num2;
             DelegateMethods.v3_1 = hSLVector;
             float x = DrawValueBar(sb, scale, hSLVector.X, 0, DelegateMethods.ColorLerp_HSL_H);
             if ((inBar || rightLock == num22) && !notBar)
             {
                 rightHover = num22;
                 if (Main.mouseLeft && rightLock == num22)
                 {
                     hSLVector.X = x;
                     noSound = true;
                 }
             }
             if ((float)Main.mouseX > vector3.X + vector2.X * 2f / 3f + (float)num4 && (float)Main.mouseX < valuePosition.X + 3.75f && (float)Main.mouseY > valuePosition.Y - 10f && (float)Main.mouseY <= valuePosition.Y + 10f)
             {
                 if (rightLock == -1)
                 {
                     notBar = true;
                 }
                 rightHover = num22;
             }
             if (rightHover == num22)
             {
                 UILinkPointNavigator.Shortcuts.OPTIONS_BUTTON_SPECIALFEATURE = 5;
                 Main.menuMode = 25;
             }
             num22++;
             if (DrawRightSide(sb, "", num22, vector6, vector7, rightScale[num22], (rightScale[num22] - num5) / (num6 - num5)))
             {
                 if (rightLock == -1)
                 {
                     notBar = true;
                 }
                 rightHover = num22;
             }
             valuePosition.X = vector3.X + vector2.X - (float)(num4 / 2) - 20f;
             valuePosition.Y -= 3f;
             valuePosition.X -= num2;
             DelegateMethods.v3_1 = hSLVector;
             x = DrawValueBar(sb, scale, hSLVector.Y, 0, DelegateMethods.ColorLerp_HSL_S);
             if ((inBar || rightLock == num22) && !notBar)
             {
                 rightHover = num22;
                 if (Main.mouseLeft && rightLock == num22)
                 {
                     hSLVector.Y = x;
                     noSound = true;
                 }
             }
             if ((float)Main.mouseX > vector3.X + vector2.X * 2f / 3f + (float)num4 && (float)Main.mouseX < valuePosition.X + 3.75f && (float)Main.mouseY > valuePosition.Y - 10f && (float)Main.mouseY <= valuePosition.Y + 10f)
             {
                 if (rightLock == -1)
                 {
                     notBar = true;
                 }
                 rightHover = num22;
             }
             if (rightHover == num22)
             {
                 UILinkPointNavigator.Shortcuts.OPTIONS_BUTTON_SPECIALFEATURE = 6;
                 Main.menuMode = 25;
             }
             num22++;
             if (DrawRightSide(sb, "", num22, vector6, vector7, rightScale[num22], (rightScale[num22] - num5) / (num6 - num5)))
             {
                 if (rightLock == -1)
                 {
                     notBar = true;
                 }
                 rightHover = num22;
             }
             valuePosition.X = vector3.X + vector2.X - (float)(num4 / 2) - 20f;
             valuePosition.Y -= 3f;
             valuePosition.X -= num2;
             DelegateMethods.v3_1 = hSLVector;
             DelegateMethods.v3_1.Z = Utils.GetLerpValue(0.15f, 1f, DelegateMethods.v3_1.Z, clamped: true);
             x = DrawValueBar(sb, scale, DelegateMethods.v3_1.Z, 0, DelegateMethods.ColorLerp_HSL_L);
             if ((inBar || rightLock == num22) && !notBar)
             {
                 rightHover = num22;
                 if (Main.mouseLeft && rightLock == num22)
                 {
                     hSLVector.Z = x * 0.85f + 0.15f;
                     noSound = true;
                 }
             }
             if ((float)Main.mouseX > vector3.X + vector2.X * 2f / 3f + (float)num4 && (float)Main.mouseX < valuePosition.X + 3.75f && (float)Main.mouseY > valuePosition.Y - 10f && (float)Main.mouseY <= valuePosition.Y + 10f)
             {
                 if (rightLock == -1)
                 {
                     notBar = true;
                 }
                 rightHover = num22;
             }
             if (rightHover == num22)
             {
                 UILinkPointNavigator.Shortcuts.OPTIONS_BUTTON_SPECIALFEATURE = 7;
                 Main.menuMode = 25;
             }
             num22++;
             if (hSLVector.Z < 0.15f)
             {
                 hSLVector.Z = 0.15f;
             }
             Main.mouseColorSlider.SetHSL(hSLVector);
             Main.mouseColor = Main.mouseColorSlider.GetColor();
             vector6.X += num23;
             DrawRightSide(sb, "", num22, vector6, vector7, rightScale[num22], 1f);
             skipRightSlot[num22] = true;
             num22++;
             hSLVector = Main.mouseBorderColorSlider.GetHSLVector();
             if (PlayerInput.UsingGamepad && rightHover == -1)
             {
                 Main.mouseBorderColorSlider.ApplyToMainLegacyBars();
             }
             DrawRightSide(sb, Lang.menu[217].Value, num22, vector6, vector7, rightScale[num22], 1f);
             skipRightSlot[num22] = true;
             num22++;
             vector6.X -= num23;
             if (DrawRightSide(sb, "", num22, vector6, vector7, rightScale[num22], (rightScale[num22] - num5) / (num6 - num5)))
             {
                 if (rightLock == -1)
                 {
                     notBar = true;
                 }
                 rightHover = num22;
             }
             valuePosition.X = vector3.X + vector2.X - (float)(num4 / 2) - 20f;
             valuePosition.Y -= 3f;
             valuePosition.X -= num2;
             DelegateMethods.v3_1 = hSLVector;
             x = DrawValueBar(sb, scale, hSLVector.X, 0, DelegateMethods.ColorLerp_HSL_H);
             if ((inBar || rightLock == num22) && !notBar)
             {
                 rightHover = num22;
                 if (Main.mouseLeft && rightLock == num22)
                 {
                     hSLVector.X = x;
                     noSound = true;
                 }
             }
             if ((float)Main.mouseX > vector3.X + vector2.X * 2f / 3f + (float)num4 && (float)Main.mouseX < valuePosition.X + 3.75f && (float)Main.mouseY > valuePosition.Y - 10f && (float)Main.mouseY <= valuePosition.Y + 10f)
             {
                 if (rightLock == -1)
                 {
                     notBar = true;
                 }
                 rightHover = num22;
             }
             if (rightHover == num22)
             {
                 UILinkPointNavigator.Shortcuts.OPTIONS_BUTTON_SPECIALFEATURE = 5;
                 Main.menuMode = 252;
             }
             num22++;
             if (DrawRightSide(sb, "", num22, vector6, vector7, rightScale[num22], (rightScale[num22] - num5) / (num6 - num5)))
             {
                 if (rightLock == -1)
                 {
                     notBar = true;
                 }
                 rightHover = num22;
             }
             valuePosition.X = vector3.X + vector2.X - (float)(num4 / 2) - 20f;
             valuePosition.Y -= 3f;
             valuePosition.X -= num2;
             DelegateMethods.v3_1 = hSLVector;
             x = DrawValueBar(sb, scale, hSLVector.Y, 0, DelegateMethods.ColorLerp_HSL_S);
             if ((inBar || rightLock == num22) && !notBar)
             {
                 rightHover = num22;
                 if (Main.mouseLeft && rightLock == num22)
                 {
                     hSLVector.Y = x;
                     noSound = true;
                 }
             }
             if ((float)Main.mouseX > vector3.X + vector2.X * 2f / 3f + (float)num4 && (float)Main.mouseX < valuePosition.X + 3.75f && (float)Main.mouseY > valuePosition.Y - 10f && (float)Main.mouseY <= valuePosition.Y + 10f)
             {
                 if (rightLock == -1)
                 {
                     notBar = true;
                 }
                 rightHover = num22;
             }
             if (rightHover == num22)
             {
                 UILinkPointNavigator.Shortcuts.OPTIONS_BUTTON_SPECIALFEATURE = 6;
                 Main.menuMode = 252;
             }
             num22++;
             if (DrawRightSide(sb, "", num22, vector6, vector7, rightScale[num22], (rightScale[num22] - num5) / (num6 - num5)))
             {
                 if (rightLock == -1)
                 {
                     notBar = true;
                 }
                 rightHover = num22;
             }
             valuePosition.X = vector3.X + vector2.X - (float)(num4 / 2) - 20f;
             valuePosition.Y -= 3f;
             valuePosition.X -= num2;
             DelegateMethods.v3_1 = hSLVector;
             x = DrawValueBar(sb, scale, hSLVector.Z, 0, DelegateMethods.ColorLerp_HSL_L);
             if ((inBar || rightLock == num22) && !notBar)
             {
                 rightHover = num22;
                 if (Main.mouseLeft && rightLock == num22)
                 {
                     hSLVector.Z = x;
                     noSound = true;
                 }
             }
             if ((float)Main.mouseX > vector3.X + vector2.X * 2f / 3f + (float)num4 && (float)Main.mouseX < valuePosition.X + 3.75f && (float)Main.mouseY > valuePosition.Y - 10f && (float)Main.mouseY <= valuePosition.Y + 10f)
             {
                 if (rightLock == -1)
                 {
                     notBar = true;
                 }
                 rightHover = num22;
             }
             if (rightHover == num22)
             {
                 UILinkPointNavigator.Shortcuts.OPTIONS_BUTTON_SPECIALFEATURE = 7;
                 Main.menuMode = 252;
             }
             num22++;
             if (DrawRightSide(sb, "", num22, vector6, vector7, rightScale[num22], (rightScale[num22] - num5) / (num6 - num5)))
             {
                 if (rightLock == -1)
                 {
                     notBar = true;
                 }
                 rightHover = num22;
             }
             valuePosition.X = vector3.X + vector2.X - (float)(num4 / 2) - 20f;
             valuePosition.Y -= 3f;
             valuePosition.X -= num2;
             DelegateMethods.v3_1 = hSLVector;
             float num24 = Main.mouseBorderColorSlider.Alpha;
             x = DrawValueBar(sb, scale, num24, 0, DelegateMethods.ColorLerp_HSL_O);
             if ((inBar || rightLock == num22) && !notBar)
             {
                 rightHover = num22;
                 if (Main.mouseLeft && rightLock == num22)
                 {
                     num24 = x;
                     noSound = true;
                 }
             }
             if ((float)Main.mouseX > vector3.X + vector2.X * 2f / 3f + (float)num4 && (float)Main.mouseX < valuePosition.X + 3.75f && (float)Main.mouseY > valuePosition.Y - 10f && (float)Main.mouseY <= valuePosition.Y + 10f)
             {
                 if (rightLock == -1)
                 {
                     notBar = true;
                 }
                 rightHover = num22;
             }
             if (rightHover == num22)
             {
                 UILinkPointNavigator.Shortcuts.OPTIONS_BUTTON_SPECIALFEATURE = 8;
                 Main.menuMode = 252;
             }
             num22++;
             Main.mouseBorderColorSlider.SetHSL(hSLVector);
             Main.mouseBorderColorSlider.Alpha = num24;
             Main.MouseBorderColor = Main.mouseBorderColorSlider.GetColor();
             vector6.X += num23;
             DrawRightSide(sb, "", num22, vector6, vector7, rightScale[num22], 1f);
             skipRightSlot[num22] = true;
             num22++;
             string txt = "";
             switch (LockOnHelper.UseMode)
             {
             case LockOnHelper.LockOnMode.FocusTarget:
                 txt = Lang.menu[232].Value;
                 break;
             case LockOnHelper.LockOnMode.TargetClosest:
                 txt = Lang.menu[233].Value;
                 break;
             case LockOnHelper.LockOnMode.ThreeDS:
                 txt = Lang.menu[234].Value;
                 break;
             }
             if (DrawRightSide(sb, txt, num22, vector6, vector7, rightScale[num22] * 0.9f, (rightScale[num22] - num5) / (num6 - num5)))
             {
                 rightHover = num22;
                 if (flag4)
                 {
                     LockOnHelper.CycleUseModes();
                 }
             }
             num22++;
             if (DrawRightSide(sb, Player.SmartCursorSettings.SmartBlocksEnabled ? Lang.menu[215].Value : Lang.menu[216].Value, num22, vector6, vector7, rightScale[num22] * 0.9f, (rightScale[num22] - num5) / (num6 - num5)))
             {
                 rightHover = num22;
                 if (flag4)
                 {
                     Player.SmartCursorSettings.SmartBlocksEnabled = !Player.SmartCursorSettings.SmartBlocksEnabled;
                 }
             }
             num22++;
             if (DrawRightSide(sb, Main.cSmartCursorModeIsToggleAndNotHold ? Lang.menu[121].Value : Lang.menu[122].Value, num22, vector6, vector7, rightScale[num22], (rightScale[num22] - num5) / (num6 - num5)))
             {
                 rightHover = num22;
                 if (flag4)
                 {
                     Main.cSmartCursorModeIsToggleAndNotHold = !Main.cSmartCursorModeIsToggleAndNotHold;
                 }
             }
             num22++;
             if (DrawRightSide(sb, Player.SmartCursorSettings.SmartAxeAfterPickaxe ? Lang.menu[214].Value : Lang.menu[213].Value, num22, vector6, vector7, rightScale[num22] * 0.9f, (rightScale[num22] - num5) / (num6 - num5)))
             {
                 rightHover = num22;
                 if (flag4)
                 {
                     Player.SmartCursorSettings.SmartAxeAfterPickaxe = !Player.SmartCursorSettings.SmartAxeAfterPickaxe;
                 }
             }
             num22++;
         }
         if (rightHover != -1 && rightLock == -1)
         {
             rightLock = rightHover;
         }
         for (int n = 0; n < num9 + 1; n++)
         {
             UILinkPointNavigator.SetPosition(2900 + n, vector4 + vector5 * (n + 1));
         }
         Vector2 zero = Vector2.Zero;
         if (flag)
         {
             zero.X = -40f;
         }
         for (int num25 = 0; num25 < num13; num25++)
         {
             if (!skipRightSlot[num25])
             {
                 UILinkPointNavigator.SetPosition(2930 + num12, vector6 + zero + vector7 * (num25 + 1));
                 num12++;
             }
         }
         UILinkPointNavigator.Shortcuts.INGAMEOPTIONS_BUTTONS_RIGHT = num12;
         Main.DrawInterface_29_SettingsButton();
         Main.DrawGamepadInstructions();
         Main.mouseText = false;
         Main.instance.GUIBarsDraw();
         Main.instance.DrawMouseOver();
         Main.DrawCursor(Main.DrawThickCursor());
     }
References _canConsumeHover, _GUIHover, _leftSideCategoryMapping, Language.ActiveCulture, SelectionHolder< TCycleType >.ActiveSelectionKeyName, PlayerResourceSetsManager.ActiveSetKeyName, Main.ambientVolume, Main.autoPause, Main.autoSave, Main.BackgroundEnabled, Main.bgScroll, NetSocialModule.CanInvite(), category, Main.caveParallax, Close(), Color, GameCulture.CultureInfo, Main.CycleFrameSkipMode(), Player.Settings.CycleHoverControl(), DoorOpeningHelper.CyclePreferences(), PlayerResourceSetsManager.CycleResourceSet(), SelectionHolder< TCycleType >.CycleSelection(), ChildSafety.Disabled, Main.displayHeight, Main.displayWidth, Utils.DrawBorderString(), Utils.DrawInvBG(), DrawLeftSide(), DrawRightSide(), DrawValueBar(), Main.FrameSkipMode, GameCulture.FromCultureName(), Main.gameMenu, Main.GamepadDisableInstructionsDisplay, Main.GameViewMatrix, Main.GameZoomTarget, Language.GetTextValue(), Main.graphics, ItemSlot.Options.HighlightNewItems, Player.Settings.HoverControl, inBar, UILinkPointNavigator.Shortcuts.INGAMEOPTIONS_BUTTONS_LEFT, UILinkPointNavigator.Shortcuts.INGAMEOPTIONS_BUTTONS_RIGHT, Lang.inter, Main.invasionProgressMode, GameCulture.IsActive, FontAssets.ItemStack, leftHover, leftScale, Main.MapScale, Lang.menu, Main.menuMode, Main.MinimapFrameManagerInstance, Lighting.Mode, Player.mouseInterface, Main.mouseLeft, Main.mouseLeftRelease, Main.MouseShowBuildingGrid, Main.mouseX, Main.mouseY, Main.musicVolume, Main.myPlayer, SocialAPI.Network, Lighting.NextLightMode(), noSound, notBar, Main.numDisplayModes, oldLeftHover, oldRightHover, IngameFancyUI.OpenAchievements(), NetSocialModule.OpenInviteInterface(), IngameFancyUI.OpenKeybinds(), UILinkPointNavigator.Shortcuts.OPTIONS_BUTTON_SPECIALFEATURE, Main.PendingResolutionHeight, Main.PendingResolutionWidth, Main.placementPreview, Main.player, SoundEngine.PlaySound(), DoorOpeningHelper.PreferenceSettings, Main.qaStyle, Main.ResourceSetsManager, Main.ReversedUpDownArmorSetBonuses, rightHover, rightLock, rightScale, WorldGen.SaveAndQuit(), Main.screenHeight, Main.screenWidth, Main.SetResolution(), Main.SettingsEnabled_AutoReuseAllItems, Main.SettingsEnabled_OpaqueBoxBehindTooltips, Main.SettingsEnabled_TilesSwayInWind, Main.showItemText, BigProgressBarSystem.ShowText, skipRightSlot, Main.soundVolume, Main.temporaryGUIScaleSlider, Main.temporaryGUIScaleSliderUpdate, Main.ToggleFullScreen(), BigProgressBarSystem.ToggleShowText(), Main.UIScale, Main.UIScaleWanted, Main.UseHeatDistortion, Main.UseStormEffects, Asset< T >.Value, LocalizedText.Value, valuePosition, Main.WaveQuality, and SpriteViewMatrix.Zoom.
Referenced by Main.DrawInterface_11_IngameOptionsMenu().