Terraria: RemoteClient.SpamUpdate
SpamUpdate()
void RemoteClient.SpamUpdate () inline
     {
         if (!Netplay.SpamCheck)
         {
             SpamProjectile = 0f;
             SpamDeleteBlock = 0f;
             SpamAddBlock = 0f;
             SpamWater = 0f;
             return;
         }
         if (SpamProjectile > SpamProjectileMax)
         {
             NetMessage.BootPlayer(Id, NetworkText.FromKey("Net.CheatingProjectileSpam"));
         }
         if (SpamAddBlock > SpamAddBlockMax)
         {
             NetMessage.BootPlayer(Id, NetworkText.FromKey("Net.CheatingTileSpam"));
         }
         if (SpamDeleteBlock > SpamDeleteBlockMax)
         {
             NetMessage.BootPlayer(Id, NetworkText.FromKey("Net.CheatingTileRemovalSpam"));
         }
         if (SpamWater > SpamWaterMax)
         {
             NetMessage.BootPlayer(Id, NetworkText.FromKey("Net.CheatingLiquidSpam"));
         }
         SpamProjectile -= 0.4f;
         if (SpamProjectile < 0f)
         {
             SpamProjectile = 0f;
         }
         SpamAddBlock -= 0.3f;
         if (SpamAddBlock < 0f)
         {
             SpamAddBlock = 0f;
         }
         SpamDeleteBlock -= 5f;
         if (SpamDeleteBlock < 0f)
         {
             SpamDeleteBlock = 0f;
         }
         SpamWater -= 0.2f;
         if (SpamWater < 0f)
         {
             SpamWater = 0f;
         }
     }
References NetMessage.BootPlayer(), NetworkText.FromKey(), Id, SpamAddBlock, SpamAddBlockMax, Netplay.SpamCheck, SpamDeleteBlock, SpamDeleteBlockMax, SpamProjectile, SpamProjectileMax, SpamWater, and SpamWaterMax.
Referenced by Main.UpdateServer().