Terraria: RemoteClient.CheckSection
CheckSection()
static void RemoteClient.CheckSection (int playerIndex, Vector2 position, int fluff = 1) inline static
     {
         int sectionX = Netplay.GetSectionX((int)(position.X / 16f));
         int sectionY = Netplay.GetSectionY((int)(position.Y / 16f));
         int num = 0;
         for (int i = sectionX - fluff; i < sectionX + fluff + 1; i++)
         {
             for (int j = sectionY - fluff; j < sectionY + fluff + 1; j++)
             {
                 if (i >= 0 && i < Main.maxSectionsX && j >= 0 && j < Main.maxSectionsY && !Netplay.Clients[playerIndex].TileSections[i, j])
                 {
                     num++;
                 }
             }
         }
         if (num <= 0)
         {
             return;
         }
         int num2 = num;
         NetMessage.SendData(9, playerIndex, -1, Lang.inter[44].ToNetworkText(), num2);
         Netplay.Clients[playerIndex].StatusText2 = Language.GetTextValue("Net.IsReceivingTileData");
         Netplay.Clients[playerIndex].StatusMax += num2;
         for (int k = sectionX - fluff; k < sectionX + fluff + 1; k++)
         {
             for (int l = sectionY - fluff; l < sectionY + fluff + 1; l++)
             {
                 NetMessage.SendSection(playerIndex, k, l);
             }
         }
     }
References Netplay.Clients, Netplay.GetSectionX(), Netplay.GetSectionY(), Language.GetTextValue(), Lang.inter, Main.maxSectionsY, NetMessage.SendData(), NetMessage.SendSection(), StatusMax, StatusText2, TileSections, and LocalizedText.ToNetworkText().
Referenced by Projectile.AI_149_GolfBall(), Projectile.AI_195_JimsDrone(), Player.DemonConch(), MessageBuffer.GetData(), TeleportPylonsSystem.HandleTeleportRequest(), Player.MagicConch(), Player.Shellphone_Spawn(), PortalHelper.SyncPortalSections(), Wiring.Teleport(), Player.TeleportationPotion(), and Main.UpdateServer().