Terraria: System.Data.XmlDataLoader.LoadTopMostTable
LoadTopMostTable()
void System.Data.XmlDataLoader.LoadTopMostTable (DataTable table) inline private
Definition at line 596 of file XmlDataLoader.cs.
    {
        bool flag = _isTableLevel || _dataSet.DataSetName != table.TableName;
        DataRow dataRow = null;
        bool flag2 = false;
        int num = _dataReader.Depth - 1;
        int count = _childRowsStack.Count;
        DataColumnCollection columns = table.Columns;
        object[] array = new object[columns.Count];
        foreach (XmlAttribute attribute in _topMostNode.Attributes)
        {
            if (_nodeToSchemaMap.GetColumnSchema(attribute, FIgnoreNamespace(attribute)) is DataColumn { ColumnMapping: MappingType.Attribute } dataColumn)
            {
                XmlNode n = attribute.FirstChild;
                array[dataColumn.Ordinal] = dataColumn.ConvertXmlToObject(GetInitialTextFromNodes(ref n));
                flag2 = true;
            }
        }
        while (num < _dataReader.Depth)
        {
            switch (_dataReader.NodeType)
            {
            case XmlNodeType.Element:
            {
                object columnSchema = _nodeToSchemaMap.GetColumnSchema(table, _dataReader, FIgnoreNamespace(_dataReader));
                if (columnSchema is DataColumn dataColumn2)
                {
                    if (array[dataColumn2.Ordinal] == null)
                    {
                        LoadColumn(dataColumn2, array);
                        flag2 = true;
                    }
                    else
                    {
                        _dataReader.Read();
                    }
                }
                else if (columnSchema is DataTable table2)
                {
                    LoadTable(table2, isNested: true);
                    flag2 = true;
                }
                else if (!ProcessXsdSchema())
                {
                    if (!(flag2 || flag))
                    {
                        return;
                    }
                    _dataReader.Read();
                }
                break;
            }
            case XmlNodeType.EntityReference:
                throw ExceptionBuilder.FoundEntity();
            case XmlNodeType.Text:
            case XmlNodeType.CDATA:
            case XmlNodeType.Whitespace:
            case XmlNodeType.SignificantWhitespace:
            {
                string s = _dataReader.ReadString();
                DataColumn xmlText = table._xmlText;
                if (xmlText != null && array[xmlText.Ordinal] == null)
                {
                    array[xmlText.Ordinal] = xmlText.ConvertXmlToObject(s);
                }
                break;
            }
            default:
                _dataReader.Read();
                break;
            }
        }
        _dataReader.Read();
        for (int num2 = array.Length - 1; num2 >= 0; num2--)
        {
            if (array[num2] == null)
            {
                DataColumn xmlText = columns[num2];
                if (xmlText.AllowDBNull && xmlText.ColumnMapping != MappingType.Hidden && !xmlText.AutoIncrement)
                {
                    array[num2] = DBNull.Value;
                }
            }
        }
        dataRow = table.Rows.AddWithColumnEvents(array);
        while (count < _childRowsStack.Count)
        {
            DataRow dataRow2 = _childRowsStack.Pop();
            bool flag3 = dataRow2.RowState == DataRowState.Unchanged;
            dataRow2.SetNestedParentRow(dataRow, setNonNested: false);
            if (flag3)
            {
                dataRow2._oldRecord = dataRow2._newRecord;
            }
        }
    }
References System.Data.XmlDataLoader._childRowsStack, System.Data.XmlDataLoader._dataReader, System.Data.XmlDataLoader._isTableLevel, System.Data.XmlDataLoader._nodeToSchemaMap, System.Data.XmlDataLoader._topMostNode, System.array, System.Xml.XmlElement.Attributes, System.Data.DataTable.Columns, System.count, System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Xml.XmlReader.Depth, System.Xml.Dictionary, System.Data.XmlDataLoader.FIgnoreNamespace(), System.Data.ExceptionBuilder.FoundEntity(), System.Data.XmlToDatasetMap.GetColumnSchema(), System.Data.XmlDataLoader.GetInitialTextFromNodes(), System.Data.XmlDataLoader.LoadColumn(), System.Data.XmlDataLoader.LoadTable(), System.Xml.XmlReader.NodeType, System.Data.XmlDataLoader.ProcessXsdSchema(), System.Xml.XmlReader.Read(), System.Xml.XmlReader.ReadString(), System.s, System.Data.DataTable.TableName, and System.DBNull.Value.
Referenced by System.Data.XmlDataLoader.LoadData().