Terraria: System.Data.XmlDataLoader.AttachRows
AttachRows()
void System.Data.XmlDataLoader.AttachRows (DataRow parentRow, XmlNode parentElement) inline private
Definition at line 115 of file XmlDataLoader.cs.
    {
        if (parentElement == null)
        {
            return;
        }
        for (XmlNode xmlNode = parentElement.FirstChild; xmlNode != null; xmlNode = xmlNode.NextSibling)
        {
            if (xmlNode.NodeType == XmlNodeType.Element)
            {
                XmlElement e = (XmlElement)xmlNode;
                DataRow rowFromElement = GetRowFromElement(e);
                if (rowFromElement != null && rowFromElement.RowState == DataRowState.Detached)
                {
                    if (parentRow != null)
                    {
                        rowFromElement.SetNestedParentRow(parentRow, setNonNested: false);
                    }
                    rowFromElement.Table.Rows.Add(rowFromElement);
                }
                else if (rowFromElement == null)
                {
                    AttachRows(parentRow, xmlNode);
                }
                AttachRows(rowFromElement, xmlNode);
            }
        }
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Data.XmlDataLoader.AttachRows(), and System.Data.XmlDataLoader.GetRowFromElement().
Referenced by System.Data.XmlDataLoader.AttachRows(), and System.Data.XmlDataLoader.LoadData().