Terraria: System.Data.XmlDataLoader.LoadTable
LoadTable()
void System.Data.XmlDataLoader.LoadTable (DataTable table, bool isNested) inline private
Definition at line 694 of file XmlDataLoader.cs.
    {
        DataRow dataRow = null;
        int depth = _dataReader.Depth;
        int count = _childRowsStack.Count;
        DataColumnCollection columns = table.Columns;
        object[] array = new object[columns.Count];
        int pos = -1;
        string key = string.Empty;
        string text = null;
        bool flag = false;
        for (int num = _dataReader.AttributeCount - 1; num >= 0; num--)
        {
            _dataReader.MoveToAttribute(num);
            if (_nodeToSchemaMap.GetColumnSchema(table, _dataReader, FIgnoreNamespace(_dataReader)) is DataColumn { ColumnMapping: MappingType.Attribute } dataColumn)
            {
                array[dataColumn.Ordinal] = dataColumn.ConvertXmlToObject(_dataReader.Value);
            }
            if (_isDiffgram)
            {
                if (_dataReader.NamespaceURI == "urn:schemas-microsoft-com:xml-diffgram-v1")
                {
                    switch (_dataReader.LocalName)
                    {
                    case "id":
                        key = _dataReader.Value;
                        break;
                    case "hasChanges":
                        text = _dataReader.Value;
                        break;
                    case "hasErrors":
                        flag = (bool)Convert.ChangeType(_dataReader.Value, typeof(bool), CultureInfo.InvariantCulture);
                        break;
                    }
                }
                else if (_dataReader.NamespaceURI == "urn:schemas-microsoft-com:xml-msdata")
                {
                    if (_dataReader.LocalName == "rowOrder")
                    {
                        pos = (int)Convert.ChangeType(_dataReader.Value, typeof(int), CultureInfo.InvariantCulture);
                    }
                    else if (_dataReader.LocalName.StartsWith("hidden", StringComparison.Ordinal))
                    {
                        DataColumn dataColumn2 = columns[XmlConvert.DecodeName(_dataReader.LocalName.Substring(6))];
                        if (dataColumn2 != null && dataColumn2.ColumnMapping == MappingType.Hidden)
{
                            array[dataColumn2.Ordinal] = dataColumn2.ConvertXmlToObject(_dataReader.Value);
                        }
                    }
                }
            }
        }
        if (_dataReader.Read() && depth < _dataReader.Depth)
        {
            while (depth < _dataReader.Depth)
            {
                switch (_dataReader.NodeType)
                {
                case XmlNodeType.Element:
                {
                    object columnSchema = _nodeToSchemaMap.GetColumnSchema(table, _dataReader, FIgnoreNamespace(_dataReader));
                    if (columnSchema is DataColumn dataColumn3)
                    {
                        if (array[dataColumn3.Ordinal] == null)
{
                            LoadColumn(dataColumn3, array);
                        }
                        else
{
                            _dataReader.Read();
                        }
                    }
                    else if (columnSchema is DataTable table2)
                    {
                        LoadTable(table2, isNested: true);
                    }
                    else if (!ProcessXsdSchema())
                    {
                        DataTable tableForNode = _nodeToSchemaMap.GetTableForNode(_dataReader, FIgnoreNamespace(_dataReader));
                        if (tableForNode != null)
{
                            LoadTable(tableForNode, isNested: false);
                        }
                        else
{
                            _dataReader.Read();
                        }
                    }
                    break;
                }
                case XmlNodeType.EntityReference:
                    throw ExceptionBuilder.FoundEntity();
                case XmlNodeType.Text:
                case XmlNodeType.CDATA:
                case XmlNodeType.Whitespace:
                case XmlNodeType.SignificantWhitespace:
                {
                    string s = _dataReader.ReadString();
                    DataColumn dataColumn2 = table._xmlText;
                    if (dataColumn2 != null && array[dataColumn2.Ordinal] == null)
                    {
                        array[dataColumn2.Ordinal] = dataColumn2.ConvertXmlToObject(s);
                    }
                    break;
                }
                default:
                    _dataReader.Read();
                    break;
                }
            }
            _dataReader.Read();
        }
        if (_isDiffgram)
        {
            dataRow = table.NewRow(table.NewUninitializedRecord());
            dataRow.BeginEdit();
            for (int num2 = array.Length - 1; num2 >= 0; num2--)
            {
                DataColumn dataColumn2 = columns[num2];
                dataColumn2[dataRow._tempRecord] = ((array[num2] != null) ? array[num2] : DBNull.Value);
            }
            dataRow.EndEdit();
            table.Rows.DiffInsertAt(dataRow, pos);
            if (text == null)
            {
                dataRow._oldRecord = dataRow._newRecord;
            }
            if (text == "modified" || flag)
            {
                table.RowDiffId[key] = dataRow;
            }
        }
        else
        {
            for (int num3 = array.Length - 1; num3 >= 0; num3--)
            {
                if (array[num3] == null)
                {
                    DataColumn dataColumn2 = columns[num3];
                    if (dataColumn2.AllowDBNull && dataColumn2.ColumnMapping != MappingType.Hidden && !dataColumn2.AutoIncrement)
                    {
                        array[num3] = DBNull.Value;
                    }
                }
            }
            dataRow = table.Rows.AddWithColumnEvents(array);
        }
        while (count < _childRowsStack.Count)
        {
            DataRow dataRow2 = _childRowsStack.Pop();
            bool flag2 = dataRow2.RowState == DataRowState.Unchanged;
            dataRow2.SetNestedParentRow(dataRow, setNonNested: false);
            if (flag2)
            {
                dataRow2._oldRecord = dataRow2._newRecord;
            }
        }
        if (isNested)
        {
            _childRowsStack.Push(dataRow);
        }
    }
References System.Data.XmlDataLoader._childRowsStack, System.Data.XmlDataLoader._dataReader, System.Data.XmlDataLoader._isDiffgram, System.Data.XmlDataLoader._nodeToSchemaMap, System.Data.DataTable._xmlText, System.Data.DataRowCollection.AddWithColumnEvents(), System.array, System.Xml.XmlReader.AttributeCount, System.Convert.ChangeType(), System.Data.DataTable.Columns, System.count, System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Xml.XmlConvert.DecodeName(), System.Xml.XmlReader.Depth, System.Xml.Dictionary, System.Data.DataRowCollection.DiffInsertAt(), System.Data.XmlDataLoader.FIgnoreNamespace(), System.Data.ExceptionBuilder.FoundEntity(), System.Data.XmlToDatasetMap.GetColumnSchema(), System.Data.XmlToDatasetMap.GetTableForNode(), System.Globalization.CultureInfo.InvariantCulture, System.key, System.Data.XmlDataLoader.LoadColumn(), System.Data.XmlDataLoader.LoadTable(), System.Xml.XmlReader.LocalName, System.Xml.XmlReader.MoveToAttribute(), System.Xml.XmlReader.NamespaceURI, System.Data.DataTable.NewRow(), System.Data.DataTable.NewUninitializedRecord(), System.Xml.XmlReader.NodeType, System.Data.XmlDataLoader.ProcessXsdSchema(), System.Xml.XmlReader.Read(), System.Xml.XmlReader.ReadString(), System.Data.DataTable.RowDiffId, System.Data.DataTable.Rows, System.s, System.text, System.DBNull.Value, and System.Xml.XmlReader.Value.
Referenced by System.Data.XmlDataLoader.LoadColumn(), System.Data.XmlDataLoader.LoadData(), System.Data.XmlDataLoader.LoadTable(), and System.Data.XmlDataLoader.LoadTopMostTable().