Terraria: System.Data.XmlDataLoader.ProcessXsdSchema
ProcessXsdSchema()
bool System.Data.XmlDataLoader.ProcessXsdSchema () inline private
Definition at line 1014 of file XmlDataLoader.cs.
    {
        if (_dataReader.LocalName == _XSD_SCHEMA && _dataReader.NamespaceURI == _XSDNS)
        {
            if (_ignoreSchema)
            {
                _dataReader.Skip();
            }
            else if (_isTableLevel)
            {
                _dataTable.ReadXSDSchema(_dataReader, denyResolving: false);
                _nodeToSchemaMap = new XmlToDatasetMap(_dataReader.NameTable, _dataTable);
            }
            else
            {
                _dataSet.ReadXSDSchema(_dataReader, denyResolving: false);
                _nodeToSchemaMap = new XmlToDatasetMap(_dataReader.NameTable, _dataSet);
            }
        }
        else
        {
            if ((_dataReader.LocalName != _XDR_SCHEMA || _dataReader.NamespaceURI != _XDRNS) && (_dataReader.LocalName != _SQL_SYNC || _dataReader.NamespaceURI != _UPDGNS))
            {
                return false;
            }
            _dataReader.Skip();
        }
        return true;
    }
References System.Data.XmlDataLoader._dataReader, System.Data.XmlDataLoader._dataSet, System.Data.XmlDataLoader._dataTable, System.Data.XmlDataLoader._ignoreSchema, System.Data.XmlDataLoader._isTableLevel, System.Data.XmlDataLoader._nodeToSchemaMap, System.Data.XmlDataLoader._SQL_SYNC, System.Data.XmlDataLoader._UPDGNS, System.Data.XmlDataLoader._XDR_SCHEMA, System.Data.XmlDataLoader._XDRNS, System.Data.XmlDataLoader._XSD_SCHEMA, System.Data.XmlDataLoader._XSDNS, System.Xml.XmlReader.LocalName, System.Xml.XmlReader.NamespaceURI, System.Xml.XmlReader.NameTable, System.Data.DataSet.ReadXSDSchema(), System.Data.DataTable.ReadXSDSchema(), and System.Xml.XmlReader.Skip().
Referenced by System.Data.XmlDataLoader.LoadColumn(), System.Data.XmlDataLoader.LoadData(), System.Data.XmlDataLoader.LoadTable(), and System.Data.XmlDataLoader.LoadTopMostTable().