Terraria: System.Data.XmlDataLoader.LoadData
LoadData() [1/2]
void System.Data.XmlDataLoader.LoadData (XmlDocument xdoc) inline package
Definition at line 315 of file XmlDataLoader.cs.
    {
        if (xdoc.DocumentElement == null)
        {
            return;
        }
        bool enforceConstraints;
        if (_isTableLevel)
        {
            enforceConstraints = _dataTable.EnforceConstraints;
            _dataTable.EnforceConstraints = false;
        }
        else
        {
            enforceConstraints = _dataSet.EnforceConstraints;
            _dataSet.EnforceConstraints = false;
            _dataSet._fInReadXml = true;
        }
        if (_isTableLevel)
        {
            _nodeToSchemaMap = new XmlToDatasetMap(_dataTable, xdoc.NameTable);
        }
        else
        {
            _nodeToSchemaMap = new XmlToDatasetMap(_dataSet, xdoc.NameTable);
        }
        DataRow dataRow = null;
        if (_isTableLevel || (_dataSet != null && _dataSet._fTopLevelTable))
        {
            XmlElement documentElement = xdoc.DocumentElement;
            DataTable dataTable = (DataTable)_nodeToSchemaMap.GetSchemaForNode(documentElement, FIgnoreNamespace(documentElement));
            if (dataTable != null)
            {
                dataRow = dataTable.CreateEmptyRow();
                _nodeToRowMap[documentElement] = dataRow;
                LoadRowData(dataRow, documentElement);
                dataTable.Rows.Add(dataRow);
            }
        }
        LoadRows(dataRow, xdoc.DocumentElement);
        AttachRows(dataRow, xdoc.DocumentElement);
        if (_isTableLevel)
        {
            _dataTable.EnforceConstraints = enforceConstraints;
            return;
        }
        _dataSet._fInReadXml = false;
        _dataSet.EnforceConstraints = enforceConstraints;
    }
References System.Data.XmlDataLoader._dataSet, System.Data.XmlDataLoader._dataTable, System.Data.DataSet._fTopLevelTable, System.Data.XmlDataLoader._isTableLevel, System.Data.XmlDataLoader._nodeToRowMap, System.Data.XmlDataLoader._nodeToSchemaMap, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Data.XmlDataLoader.AttachRows(), System.Xml.Dictionary, System.Data.DataSet.EnforceConstraints, System.Data.DataTable.EnforceConstraints, System.Data.XmlDataLoader.FIgnoreNamespace(), System.Data.XmlToDatasetMap.GetSchemaForNode(), System.Data.XmlDataLoader.LoadRowData(), and System.Data.XmlDataLoader.LoadRows().