Terraria: System.Data.XmlDataLoader.GetInitialTextFromNodes
GetInitialTextFromNodes()
string System.Data.XmlDataLoader.GetInitialTextFromNodes (ref XmlNode n) inline private
Definition at line 189 of file XmlDataLoader.cs.
    {
        string text = null;
        if (n != null)
        {
            while (n.NodeType == XmlNodeType.Whitespace)
            {
                n = n.NextSibling;
            }
            if (IsTextLikeNode(n.NodeType) && (n.NextSibling == null || !IsTextLikeNode(n.NodeType)))
            {
                text = n.Value;
                n = n.NextSibling;
            }
            else
            {
                StringBuilder stringBuilder = new StringBuilder();
                while (n != null && IsTextLikeNode(n.NodeType))
                {
                    stringBuilder.Append(n.Value);
                    n = n.NextSibling;
                }
                text = stringBuilder.ToString();
            }
        }
        if (text == null)
        {
            text = string.Empty;
        }
        return text;
    }
References System.Data.XmlDataLoader.IsTextLikeNode(), and System.text.
Referenced by System.Data.XmlDataLoader.LoadRowData(), and System.Data.XmlDataLoader.LoadTopMostTable().