Terraria: System.Data.XmlDataLoader.LoadColumn
LoadColumn()
void System.Data.XmlDataLoader.LoadColumn (DataColumn column, object[] foundColumns) inline private
Definition at line 858 of file XmlDataLoader.cs.
    {
        string text = string.Empty;
        string text2 = null;
        int depth = _dataReader.Depth;
        if (_dataReader.AttributeCount > 0)
        {
            text2 = _dataReader.GetAttribute("nil", "http://www.w3.org/2001/XMLSchema-instance");
        }
        if (column.IsCustomType)
        {
            object obj = null;
            string text3 = null;
            string text4 = null;
            XmlRootAttribute xmlRootAttribute = null;
            if (_dataReader.AttributeCount > 0)
            {
                text3 = _dataReader.GetAttribute("type", "http://www.w3.org/2001/XMLSchema-instance");
                text4 = _dataReader.GetAttribute("InstanceType", "urn:schemas-microsoft-com:xml-msdata");
            }
            bool flag = !column.ImplementsIXMLSerializable && !(column.DataType == typeof(object)) && text4 == null && text3 == null;
            if (text2 != null && XmlConvert.ToBoolean(text2))
            {
                if (!flag && text4 != null && text4.Length > 0)
                {
                    obj = SqlUdtStorage.GetStaticNullForUdtType(DataStorage.GetType(text4));
                }
                if (obj == null)
                {
                    obj = DBNull.Value;
                }
                if (!_dataReader.IsEmptyElement)
                {
                    while (_dataReader.Read() && depth < _dataReader.Depth)
                    {
                    }
                }
                _dataReader.Read();
            }
            else
            {
                bool flag2 = false;
                if (column.Table.DataSet != null && column.Table.DataSet._udtIsWrapped)
                {
                    _dataReader.Read();
                    flag2 = true;
                }
                if (flag)
                {
                    if (flag2)
                    {
                        xmlRootAttribute = new XmlRootAttribute(_dataReader.LocalName);
                        xmlRootAttribute.Namespace = _dataReader.NamespaceURI;
                    }
                    else
                    {
                        xmlRootAttribute = new XmlRootAttribute(column.EncodedColumnName);
                        xmlRootAttribute.Namespace = column.Namespace;
                    }
                }
                obj = column.ConvertXmlToObject(_dataReader, xmlRootAttribute);
                if (flag2)
                {
                    _dataReader.Read();
                }
            }
            foundColumns[column.Ordinal] = obj;
            return;
        }
        if (_dataReader.Read() && depth < _dataReader.Depth)
        {
            while (depth < _dataReader.Depth)
            {
                switch (_dataReader.NodeType)
                {
                case XmlNodeType.Text:
                case XmlNodeType.CDATA:
                case XmlNodeType.Whitespace:
                case XmlNodeType.SignificantWhitespace:
                    if (text.Length == 0)
                    {
                        text = _dataReader.Value;
                        StringBuilder stringBuilder = null;
                        while (_dataReader.Read() && depth < _dataReader.Depth && IsTextLikeNode(_dataReader.NodeType))
{
                            if (stringBuilder == null)
{
                                stringBuilder = new StringBuilder(text);
                            }
                            stringBuilder.Append(_dataReader.Value);
                        }
                        if (stringBuilder != null)
{
                            text = stringBuilder.ToString();
                        }
                    }
                    else
                    {
                        _dataReader.ReadString();
                    }
                    break;
                case XmlNodeType.Element:
                {
                    if (ProcessXsdSchema())
                    {
                        break;
                    }
                    object columnSchema = _nodeToSchemaMap.GetColumnSchema(column.Table, _dataReader, FIgnoreNamespace(_dataReader));
                    if (columnSchema is DataColumn dataColumn)
                    {
                        if (foundColumns[dataColumn.Ordinal] == null)
{
                            LoadColumn(dataColumn, foundColumns);
                        }
                        else
{
                            _dataReader.Read();
                        }
                        break;
                    }
                    if (columnSchema is DataTable table)
                    {
                        LoadTable(table, isNested: true);
                        break;
                    }
                    DataTable tableForNode = _nodeToSchemaMap.GetTableForNode(_dataReader, FIgnoreNamespace(_dataReader));
                    if (tableForNode != null)
                    {
                        LoadTable(tableForNode, isNested: false);
                    }
                    else
                    {
                        _dataReader.Read();
                    }
                    break;
                }
                case XmlNodeType.EntityReference:
                    throw ExceptionBuilder.FoundEntity();
                default:
                    _dataReader.Read();
                    break;
                }
            }
            _dataReader.Read();
        }
        if (text.Length == 0 && text2 != null && XmlConvert.ToBoolean(text2))
        {
            foundColumns[column.Ordinal] = DBNull.Value;
        }
        else
        {
            foundColumns[column.Ordinal] = column.ConvertXmlToObject(text);
        }
    }
References System.Data.XmlDataLoader._dataReader, System.Data.XmlDataLoader._nodeToSchemaMap, System.Xml.XmlReader.AttributeCount, System.Xml.XmlReader.Depth, System.Xml.Dictionary, System.Data.XmlDataLoader.FIgnoreNamespace(), System.Data.ExceptionBuilder.FoundEntity(), System.Xml.XmlReader.GetAttribute(), System.Data.XmlToDatasetMap.GetColumnSchema(), System.Data.Common.SqlUdtStorage.GetStaticNullForUdtType(), System.Data.XmlToDatasetMap.GetTableForNode(), System.Data.Common.DataStorage.GetType(), System.Xml.XmlReader.IsEmptyElement, System.Data.XmlDataLoader.IsTextLikeNode(), System.Data.XmlDataLoader.LoadColumn(), System.Data.XmlDataLoader.LoadTable(), System.Xml.XmlReader.LocalName, System.Xml.XmlReader.NamespaceURI, System.Xml.XmlReader.NodeType, System.obj, System.Data.XmlDataLoader.ProcessXsdSchema(), System.Xml.XmlReader.Read(), System.Xml.XmlReader.ReadString(), System.text, System.Xml.XmlConvert.ToBoolean(), System.DBNull.Value, and System.Xml.XmlReader.Value.
Referenced by System.Data.XmlDataLoader.LoadColumn(), System.Data.XmlDataLoader.LoadTable(), and System.Data.XmlDataLoader.LoadTopMostTable().