Terraria: System.Data.XmlDataLoader.FColumnElement
FColumnElement()
bool System.Data.XmlDataLoader.FColumnElement (XmlElement e) inline package
Definition at line 241 of file XmlDataLoader.cs.
    {
        if (_nodeToSchemaMap.GetColumnSchema(e, FIgnoreNamespace(e)) == null)
        {
            return false;
        }
        if (CountNonNSAttributes(e) > 0)
        {
            return false;
        }
        for (XmlNode xmlNode = e.FirstChild; xmlNode != null; xmlNode = xmlNode.NextSibling)
        {
            if (xmlNode is XmlElement)
            {
                return false;
            }
        }
        return true;
    }
References System.Data.XmlDataLoader._nodeToSchemaMap, System.Data.XmlDataLoader.CountNonNSAttributes(), System.Data.XmlDataLoader.FIgnoreNamespace(), System.Xml.XmlNode.FirstChild, and System.Data.XmlToDatasetMap.GetColumnSchema().
Referenced by System.Data.XmlDataLoader.LoadRowData(), and System.Data.XmlDataLoader.LoadRows().