Terraria: System.Data.XmlDataLoader.LoadRowData
LoadRowData()
void System.Data.XmlDataLoader.LoadRowData (DataRow row, XmlElement rowElement) inline private
Definition at line 366 of file XmlDataLoader.cs.
    {
        DataTable table = row.Table;
        if (FromInference)
        {
            table.Prefix = rowElement.Prefix;
        }
        Hashtable hashtable = new Hashtable();
        row.BeginEdit();
        XmlNode xmlNode = rowElement.FirstChild;
        DataColumn textOnlyColumn = GetTextOnlyColumn(row);
        if (textOnlyColumn != null)
        {
            hashtable[textOnlyColumn] = textOnlyColumn;
            string valueForTextOnlyColums = GetValueForTextOnlyColums(xmlNode);
            if (XMLSchema.GetBooleanAttribute(rowElement, "nil", "http://www.w3.org/2001/XMLSchema-instance", defVal: false) && string.IsNullOrEmpty(valueForTextOnlyColums))
            {
                row[textOnlyColumn] = DBNull.Value;
            }
            else
            {
                SetRowValueFromXmlText(row, textOnlyColumn, valueForTextOnlyColums);
            }
        }
        while (xmlNode != null && xmlNode != rowElement)
        {
            if (xmlNode.NodeType == XmlNodeType.Element)
            {
                XmlElement xmlElement = (XmlElement)xmlNode;
                object obj = _nodeToSchemaMap.GetSchemaForNode(xmlElement, FIgnoreNamespace(xmlElement));
                if (obj is DataTable && FColumnElement(xmlElement))
                {
                    obj = _nodeToSchemaMap.GetColumnSchema(xmlElement, FIgnoreNamespace(xmlElement));
                }
                if (obj == null || obj is DataColumn)
                {
                    xmlNode = xmlElement.FirstChild;
                    if (obj != null && obj is DataColumn)
                    {
                        DataColumn dataColumn = (DataColumn)obj;
                        if (dataColumn.Table == row.Table && dataColumn.ColumnMapping != MappingType.Attribute && hashtable[dataColumn] == null)
{
                            hashtable[dataColumn] = dataColumn;
                            string valueForTextOnlyColums2 = GetValueForTextOnlyColums(xmlNode);
                            if (XMLSchema.GetBooleanAttribute(xmlElement, "nil", "http://www.w3.org/2001/XMLSchema-instance", defVal: false) && string.IsNullOrEmpty(valueForTextOnlyColums2))
{
                                row[dataColumn] = DBNull.Value;
                            }
                            else
{
                                SetRowValueFromXmlText(row, dataColumn, valueForTextOnlyColums2);
                            }
                        }
                    }
                    else if (obj == null && xmlNode != null)
                    {
                        continue;
                    }
                    if (xmlNode == null)
                    {
                        xmlNode = xmlElement;
                    }
                }
            }
            while (xmlNode != rowElement && xmlNode.NextSibling == null)
            {
                xmlNode = xmlNode.ParentNode;
            }
            if (xmlNode != rowElement)
            {
                xmlNode = xmlNode.NextSibling;
            }
        }
        foreach (XmlAttribute attribute in rowElement.Attributes)
        {
            object columnSchema = _nodeToSchemaMap.GetColumnSchema(attribute, FIgnoreNamespace(attribute));
            if (columnSchema != null && columnSchema is DataColumn)
            {
                DataColumn dataColumn2 = (DataColumn)columnSchema;
                if (dataColumn2.ColumnMapping == MappingType.Attribute && hashtable[dataColumn2] == null)
                {
                    hashtable[dataColumn2] = dataColumn2;
                    xmlNode = attribute.FirstChild;
                    SetRowValueFromXmlText(row, dataColumn2, GetInitialTextFromNodes(ref xmlNode));
                }
            }
        }
        foreach (DataColumn column in row.Table.Columns)
        {
            if (hashtable[column] != null || !XmlToDatasetMap.IsMappedColumn(column))
            {
                continue;
            }
            if (!column.AutoIncrement)
            {
                if (column.AllowDBNull)
                {
                    row[column] = DBNull.Value;
                }
                else
                {
                    row[column] = column.DefaultValue;
                }
            }
            else
            {
                column.Init(row._tempRecord);
            }
        }
        row.EndEdit();
    }
References System.Data.XmlDataLoader._nodeToSchemaMap, System.Xml.Dictionary, System.Data.XmlDataLoader.FColumnElement(), System.Data.XmlDataLoader.FIgnoreNamespace(), System.Data.XmlDataLoader.FromInference, System.Data.XMLSchema.GetBooleanAttribute(), System.Data.XmlToDatasetMap.GetColumnSchema(), System.Data.XmlDataLoader.GetInitialTextFromNodes(), System.Data.XmlToDatasetMap.GetSchemaForNode(), System.Data.XmlDataLoader.GetTextOnlyColumn(), System.Data.XmlDataLoader.GetValueForTextOnlyColums(), System.Data.XmlToDatasetMap.IsMappedColumn(), System.obj, System.Data.XmlDataLoader.SetRowValueFromXmlText(), and System.DBNull.Value.
Referenced by System.Data.XmlDataLoader.LoadData(), and System.Data.XmlDataLoader.LoadRows().