Terraria: Terraria.Graphics.Renderers.NPCHeadRenderer.DrawWithOutlines
DrawWithOutlines()
void Terraria.Graphics.Renderers.NPCHeadRenderer.DrawWithOutlines (Entity entity, int headId, Vector2 position, Color color, float rotation, float scale, SpriteEffects effects) inline
Definition at line 27 of file NPCHeadRenderer.cs.
    {
        if (_contents[headId] == null)
        {
            _contents[headId] = new NPCHeadDrawRenderTargetContent();
            _contents[headId].SetTexture(_matchingArray[headId].Value);
        }
        NPCHeadDrawRenderTargetContent nPCHeadDrawRenderTargetContent = _contents[headId];
        if (nPCHeadDrawRenderTargetContent.IsReady)
        {
            RenderTarget2D target = nPCHeadDrawRenderTargetContent.GetTarget();
            Main.spriteBatch.Draw(target, position, null, color, rotation, ((Texture2D)target).Size() / 2f, scale, effects, 0f);
        }
        else
        {
            nPCHeadDrawRenderTargetContent.Request();
        }
    }
References Terraria.Graphics.Renderers.NPCHeadRenderer._contents, Terraria.Graphics.Renderers.NPCHeadRenderer._matchingArray, Terraria.GameContent.ARenderTargetContentByRequest.GetTarget(), Terraria.GameContent.ARenderTargetContentByRequest.IsReady, Terraria.GameContent.ARenderTargetContentByRequest.Request(), Terraria.GameContent.NPCHeadDrawRenderTargetContent.SetTexture(), and Terraria.Main.spriteBatch.