Terraria: System.Data.XmlDataLoader.LoadData
LoadData() [2/2]
void System.Data.XmlDataLoader.LoadData (XmlReader reader) inline package
Definition at line 539 of file XmlDataLoader.cs.
    {
        _dataReader = DataTextReader.CreateReader(reader);
        int depth = _dataReader.Depth;
        bool enforceConstraints = (_isTableLevel ? _dataTable.EnforceConstraints : _dataSet.EnforceConstraints);
        InitNameTable();
        if (_nodeToSchemaMap == null)
        {
            _nodeToSchemaMap = (_isTableLevel ? new XmlToDatasetMap(_dataReader.NameTable, _dataTable) : new XmlToDatasetMap(_dataReader.NameTable, _dataSet));
        }
        if (_isTableLevel)
        {
            _dataTable.EnforceConstraints = false;
        }
        else
        {
            _dataSet.EnforceConstraints = false;
            _dataSet._fInReadXml = true;
        }
        if (_topMostNode != null)
        {
            if (!_isDiffgram && !_isTableLevel && _nodeToSchemaMap.GetSchemaForNode(_topMostNode, FIgnoreNamespace(_topMostNode)) is DataTable table)
            {
                LoadTopMostTable(table);
            }
            _topMostNode = null;
        }
        while (!_dataReader.EOF && _dataReader.Depth >= depth)
        {
            if (reader.NodeType != XmlNodeType.Element)
            {
                _dataReader.Read();
                continue;
            }
            DataTable tableForNode = _nodeToSchemaMap.GetTableForNode(_dataReader, FIgnoreNamespace(_dataReader));
            if (tableForNode == null)
            {
                if (!ProcessXsdSchema())
                {
                    _dataReader.Read();
                }
            }
            else
            {
                LoadTable(tableForNode, isNested: false);
            }
        }
        if (_isTableLevel)
        {
            _dataTable.EnforceConstraints = enforceConstraints;
            return;
        }
        _dataSet._fInReadXml = false;
        _dataSet.EnforceConstraints = enforceConstraints;
    }
References System.Data.XmlDataLoader._dataReader, System.Data.XmlDataLoader._dataSet, System.Data.XmlDataLoader._dataTable, System.Data.XmlDataLoader._isDiffgram, System.Data.XmlDataLoader._isTableLevel, System.Data.XmlDataLoader._nodeToSchemaMap, System.Data.XmlDataLoader._topMostNode, System.Data.DataTextReader.CreateReader(), System.Xml.XmlReader.Depth, System.Xml.Dictionary, System.Data.DataSet.EnforceConstraints, System.Xml.XmlReader.EOF, System.Data.XmlDataLoader.FIgnoreNamespace(), System.Data.XmlToDatasetMap.GetSchemaForNode(), System.Data.XmlToDatasetMap.GetTableForNode(), System.Data.XmlDataLoader.InitNameTable(), System.Data.XmlDataLoader.LoadTable(), System.Data.XmlDataLoader.LoadTopMostTable(), System.Xml.XmlReader.NameTable, System.Xml.XmlReader.NodeType, System.Data.XmlDataLoader.ProcessXsdSchema(), and System.Xml.XmlReader.Read().