Terraria: System.Data.XmlDataLoader.LoadRows
LoadRows()
void System.Data.XmlDataLoader.LoadRows (DataRow parentRow, XmlNode parentElement) inline private
Definition at line 479 of file XmlDataLoader.cs.
    {
        if (parentElement == null || (parentElement.LocalName == "schema" && parentElement.NamespaceURI == "http://www.w3.org/2001/XMLSchema") || (parentElement.LocalName == "sync" && parentElement.NamespaceURI == "urn:schemas-microsoft-com:xml-updategram") || (parentElement.LocalName == "Schema" && parentElement.NamespaceURI == "urn:schemas-microsoft-com:xml-data"))
        {
            return;
        }
        for (XmlNode xmlNode = parentElement.FirstChild; xmlNode != null; xmlNode = xmlNode.NextSibling)
        {
            if (!(xmlNode is XmlElement))
            {
                continue;
            }
            XmlElement xmlElement = (XmlElement)xmlNode;
            object schemaForNode = _nodeToSchemaMap.GetSchemaForNode(xmlElement, FIgnoreNamespace(xmlElement));
            if (schemaForNode != null && schemaForNode is DataTable)
            {
                DataRow dataRow = GetRowFromElement(xmlElement);
                if (dataRow == null)
                {
                    if (parentRow != null && FColumnElement(xmlElement))
                    {
                        continue;
                    }
                    dataRow = ((DataTable)schemaForNode).CreateEmptyRow();
                    _nodeToRowMap[xmlElement] = dataRow;
                    LoadRowData(dataRow, xmlElement);
                }
                LoadRows(dataRow, xmlNode);
            }
            else
            {
                LoadRows(null, xmlNode);
            }
        }
    }
References System.Data.XmlDataLoader._nodeToRowMap, System.Data.XmlDataLoader._nodeToSchemaMap, System.Xml.Dictionary, System.Data.XmlDataLoader.FColumnElement(), System.Data.XmlDataLoader.FIgnoreNamespace(), System.Data.XmlDataLoader.GetRowFromElement(), System.Data.XmlToDatasetMap.GetSchemaForNode(), System.Data.XmlDataLoader.LoadRowData(), and System.Data.XmlDataLoader.LoadRows().
Referenced by System.Data.XmlDataLoader.LoadData(), and System.Data.XmlDataLoader.LoadRows().