Terraria: System.Xml.Serialization.TempAssembly.ValidateEncodingStyle
ValidateEncodingStyle()
string System.Xml.Serialization.TempAssembly.ValidateEncodingStyle (string encodingStyle, string methodKey) inline private
Definition at line 499 of file TempAssembly.cs.
    {
        if (encodingStyle != null && encodingStyle.Length > 0)
        {
            if (!_methods[methodKey].isSoap)
            {
                throw new InvalidOperationException(System.SR.Format(System.SR.XmlInvalidEncodingNotEncoded1, encodingStyle));
            }
            if (encodingStyle != "http://schemas.xmlsoap.org/soap/encoding/" && encodingStyle != "http://www.w3.org/2003/05/soap-encoding")
            {
                throw new InvalidOperationException(System.SR.Format(System.SR.XmlInvalidEncoding3, encodingStyle, "http://schemas.xmlsoap.org/soap/encoding/", "http://www.w3.org/2003/05/soap-encoding"));
            }
        }
        else if (_methods[methodKey].isSoap)
        {
            encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
        }
        return encodingStyle;
    }
References System.Xml.Serialization.TempAssembly._methods, System.Xml.Dictionary, System.SR.Format(), System.SR.XmlInvalidEncoding3, and System.SR.XmlInvalidEncodingNotEncoded1.
Referenced by System.Xml.Serialization.TempAssembly.InvokeReader(), and System.Xml.Serialization.TempAssembly.InvokeWriter().