Terraria: System.Xml.Serialization.TempAssembly.IsSerializerVersionMatch
IsSerializerVersionMatch()
static bool System.Xml.Serialization.TempAssembly.IsSerializerVersionMatch (Assembly serializer, Type type, string defaultNamespace) inline static private
Definition at line 234 of file TempAssembly.cs.
    {
        if (serializer == null)
        {
            return false;
        }
        object[] customAttributes = serializer.GetCustomAttributes(typeof(XmlSerializerVersionAttribute), inherit: false);
        if (customAttributes.Length != 1)
        {
            return false;
        }
        XmlSerializerVersionAttribute xmlSerializerVersionAttribute = (XmlSerializerVersionAttribute)customAttributes[0];
        if (xmlSerializerVersionAttribute.ParentAssemblyId == GenerateAssemblyId(type) && xmlSerializerVersionAttribute.Namespace == defaultNamespace)
        {
            return true;
        }
        return false;
    }
References System.Xml.Dictionary, System.Xml.Serialization.TempAssembly.GenerateAssemblyId(), System.Reflection.Assembly.GetCustomAttributes(), and System.type.
Referenced by System.Xml.Serialization.TempAssembly.LoadGeneratedAssembly().