Terraria: System.Xml.Serialization.TempAssembly.InvokeReader
InvokeReader()
object System.Xml.Serialization.TempAssembly.InvokeReader (XmlMapping mapping, XmlReader xmlReader, XmlDeserializationEvents events, string encodingStyle) inline package
Definition at line 520 of file TempAssembly.cs.
    {
        XmlSerializationReader xmlSerializationReader = null;
        try
        {
            encodingStyle = ValidateEncodingStyle(encodingStyle, mapping.Key);
            xmlSerializationReader = Contract.Reader;
            xmlSerializationReader.Init(xmlReader, events, encodingStyle, this);
            if (_methods[mapping.Key].readMethod == null)
            {
                if (_readerMethods == null)
                {
                    _readerMethods = Contract.ReadMethods;
                }
                string text = (string)_readerMethods[mapping.Key];
                if (text == null)
                {
                    throw new InvalidOperationException(System.SR.Format(System.SR.XmlNotSerializable, mapping.Accessor.Name));
                }
                _methods[mapping.Key].readMethod = GetMethodFromType(xmlSerializationReader.GetType(), text);
            }
            return _methods[mapping.Key].readMethod.Invoke(xmlSerializationReader, Array.Empty<object>());
        }
        catch (SecurityException innerException)
        {
            throw new InvalidOperationException(System.SR.XmlNoPartialTrust, innerException);
        }
        finally
        {
            xmlSerializationReader?.Dispose();
        }
    }
References System.Xml.Serialization.TempAssembly._methods, System.Xml.Serialization.TempAssembly._readerMethods, System.Xml.Serialization.TempAssembly.Contract, System.SR.Format(), System.Xml.Serialization.TempAssembly.GetMethodFromType(), System.Xml.Serialization.XmlSerializerImplementation.Reader, System.Xml.Serialization.XmlSerializerImplementation.ReadMethods, System.text, System.Xml.Serialization.TempAssembly.ValidateEncodingStyle(), System.SR.XmlNoPartialTrust, and System.SR.XmlNotSerializable.
Referenced by System.Xml.Serialization.XmlSerializer.Deserialize().