Terraria: System.Xml.Serialization.TempAssembly.InvokeWriter
InvokeWriter()
void System.Xml.Serialization.TempAssembly.InvokeWriter (XmlMapping mapping, XmlWriter xmlWriter, object o, XmlSerializerNamespaces namespaces, string encodingStyle, string id) inline package
Definition at line 554 of file TempAssembly.cs.
    {
        XmlSerializationWriter xmlSerializationWriter = null;
        try
        {
            encodingStyle = ValidateEncodingStyle(encodingStyle, mapping.Key);
            xmlSerializationWriter = Contract.Writer;
            xmlSerializationWriter.Init(xmlWriter, namespaces, encodingStyle, id, this);
            if (_methods[mapping.Key].writeMethod == null)
            {
                if (_writerMethods == null)
                {
                    _writerMethods = Contract.WriteMethods;
                }
                string text = (string)_writerMethods[mapping.Key];
                if (text == null)
                {
                    throw new InvalidOperationException(System.SR.Format(System.SR.XmlNotSerializable, mapping.Accessor.Name));
                }
                _methods[mapping.Key].writeMethod = GetMethodFromType(xmlSerializationWriter.GetType(), text);
            }
            _methods[mapping.Key].writeMethod.Invoke(xmlSerializationWriter, new object[1] { o });
        }
        catch (SecurityException innerException)
        {
            throw new InvalidOperationException(System.SR.XmlNoPartialTrust, innerException);
        }
        finally
        {
            xmlSerializationWriter?.Dispose();
        }
    }
References System.Xml.Serialization.TempAssembly._methods, System.Xml.Serialization.TempAssembly._writerMethods, System.Xml.Serialization.TempAssembly.Contract, System.SR.Format(), System.Xml.Serialization.TempAssembly.GetMethodFromType(), System.text, System.Xml.Serialization.TempAssembly.ValidateEncodingStyle(), System.Xml.Serialization.XmlSerializerImplementation.WriteMethods, System.Xml.Serialization.XmlSerializerImplementation.Writer, System.SR.XmlNoPartialTrust, and System.SR.XmlNotSerializable.
Referenced by System.Xml.Serialization.XmlSerializer.Serialize().