Terraria: System.Xml.Serialization.TempAssembly.LoadAssemblyByPath
LoadAssemblyByPath()
static Assembly System.Xml.Serialization.TempAssembly.LoadAssemblyByPath (Type type, string assemblyName) inline static private
Definition at line 201 of file TempAssembly.cs.
    {
        Assembly result = null;
        string text = null;
        try
        {
            if (!string.IsNullOrEmpty(type.Assembly.Location))
            {
                text = Path.Combine(Path.GetDirectoryName(type.Assembly.Location), assemblyName + ".dll");
            }
            if ((string.IsNullOrEmpty(text) || !File.Exists(text)) && !string.IsNullOrEmpty(Assembly.GetEntryAssembly()?.Location))
            {
                text = Path.Combine(Path.GetDirectoryName(Assembly.GetEntryAssembly().Location), assemblyName + ".dll");
            }
            if ((string.IsNullOrEmpty(text) || !File.Exists(text)) && !string.IsNullOrEmpty(AppContext.BaseDirectory))
            {
                text = Path.Combine(Path.GetDirectoryName(AppContext.BaseDirectory), assemblyName + ".dll");
            }
            if (!string.IsNullOrEmpty(text))
            {
                result = Assembly.LoadFile(text);
            }
        }
        catch (Exception ex)
        {
            if (ex is ThreadAbortException || ex is StackOverflowException || ex is OutOfMemoryException)
            {
                throw;
            }
        }
        return result;
    }
References System.AppContext.BaseDirectory, System.IO.Path.Combine(), System.IO.File.Exists(), System.IO.Path.GetDirectoryName(), System.Reflection.Assembly.GetEntryAssembly(), System.Reflection.Assembly.LoadFile(), System.text, and System.type.
Referenced by System.Xml.Serialization.TempAssembly.LoadGeneratedAssembly().