Terraria: System.Xml.Serialization.TempAssembly.GenerateRefEmitAssembly
GenerateRefEmitAssembly()
static Assembly System.Xml.Serialization.TempAssembly.GenerateRefEmitAssembly (XmlMapping[] xmlMappings, Type[] types, string defaultNamespace) inline static package
Definition at line 395 of file TempAssembly.cs.
    {
        Dictionary<TypeScope, XmlMapping> dictionary = new Dictionary<TypeScope, XmlMapping>();
        foreach (XmlMapping xmlMapping in xmlMappings)
        {
            dictionary[xmlMapping.Scope] = xmlMapping;
        }
        TypeScope[] array = new TypeScope[dictionary.Keys.Count];
        dictionary.Keys.CopyTo(array, 0);
        string name = "Microsoft.GeneratedCode";
        AssemblyBuilder assemblyBuilder = CodeGenerator.CreateAssemblyBuilder(name);
        if (types != null && types.Length != 0 && types[0] != null)
        {
            ConstructorInfo constructor = typeof(AssemblyVersionAttribute).GetConstructor(new Type[1] { typeof(string) });
            string text = types[0].Assembly.GetName().Version.ToString();
            assemblyBuilder.SetCustomAttribute(new CustomAttributeBuilder(constructor, new object[1] { text }));
        }
        CodeIdentifiers codeIdentifiers = new CodeIdentifiers();
        codeIdentifiers.AddUnique("XmlSerializationWriter", "XmlSerializationWriter");
        codeIdentifiers.AddUnique("XmlSerializationReader", "XmlSerializationReader");
        string text2 = null;
        if (types != null && types.Length == 1 && types[0] != null)
        {
            text2 = CodeIdentifier.MakeValid(types[0].Name);
            if (types[0].IsArray)
            {
                text2 += "Array";
            }
        }
        ModuleBuilder moduleBuilder = CodeGenerator.CreateModuleBuilder(assemblyBuilder, name);
        string text3 = "XmlSerializationWriter" + text2;
        text3 = codeIdentifiers.AddUnique(text3, text3);
        XmlSerializationWriterILGen xmlSerializationWriterILGen = new XmlSerializationWriterILGen(array, "public", text3);
        xmlSerializationWriterILGen.ModuleBuilder = moduleBuilder;
        xmlSerializationWriterILGen.GenerateBegin();
        string[] array2 = new string[xmlMappings.Length];
        for (int j = 0; j < xmlMappings.Length; j++)
        {
            array2[j] = xmlSerializationWriterILGen.GenerateElement(xmlMappings[j]);
        }
        Type type = xmlSerializationWriterILGen.GenerateEnd();
        string text4 = "XmlSerializationReader" + text2;
        text4 = codeIdentifiers.AddUnique(text4, text4);
        XmlSerializationReaderILGen xmlSerializationReaderILGen = new XmlSerializationReaderILGen(array, "public", text4);
        xmlSerializationReaderILGen.ModuleBuilder = moduleBuilder;
        xmlSerializationReaderILGen.CreatedTypes.Add(type.Name, type);
        xmlSerializationReaderILGen.GenerateBegin();
        string[] array3 = new string[xmlMappings.Length];
        for (int k = 0; k < xmlMappings.Length; k++)
        {
            array3[k] = xmlSerializationReaderILGen.GenerateElement(xmlMappings[k]);
        }
        xmlSerializationReaderILGen.GenerateEnd(array3, xmlMappings, types);
        string baseSerializer = xmlSerializationReaderILGen.GenerateBaseSerializer("XmlSerializer1", text4, text3, codeIdentifiers);
        Dictionary<string, string> dictionary2 = new Dictionary<string, string>();
        for (int l = 0; l < xmlMappings.Length; l++)
        {
            if (!dictionary2.ContainsKey(xmlMappings[l].Key))
            {
                dictionary2[xmlMappings[l].Key] = xmlSerializationReaderILGen.GenerateTypedSerializer(array3[l], array2[l], xmlMappings[l], codeIdentifiers, baseSerializer, text4, text3);
            }
        }
        xmlSerializationReaderILGen.GenerateSerializerContract("XmlSerializerContract", xmlMappings, types, text4, array3, text3, array2, dictionary2);
        return type.Assembly;
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.array, System.Collections.Generic.Dictionary< TKey, TValue >.ContainsKey(), System.Xml.Serialization.CodeGenerator.CreateAssemblyBuilder(), System.Xml.Serialization.CodeGenerator.CreateModuleBuilder(), System.dictionary, System.Xml.Dictionary, System.Reflection.Emit.IsArray, System.Xml.Serialization.CodeIdentifier.MakeValid(), System.Xml.Name, System.text, and System.type.
Referenced by System.Xml.Serialization.TempAssembly.TempAssembly().