Terraria: System.Xml.Serialization.TempAssembly.LoadGeneratedAssembly
LoadGeneratedAssembly()
static Assembly System.Xml.Serialization.TempAssembly.LoadGeneratedAssembly (Type type, string defaultNamespace, out XmlSerializerImplementation contract) inline static package
Definition at line 122 of file TempAssembly.cs.
    {
        Assembly assembly = null;
        contract = null;
        string text = null;
        object[] customAttributes = type.GetCustomAttributes(typeof(XmlSerializerAssemblyAttribute), inherit: false);
        if (customAttributes.Length == 0)
        {
            AssemblyName name = type.Assembly.GetName();
            text = (name.Name = Compiler.GetTempAssemblyName(name, defaultNamespace));
            name.CodeBase = null;
            name.CultureInfo = CultureInfo.InvariantCulture;
            try
            {
                assembly = Assembly.Load(name);
            }
            catch (Exception ex)
            {
                if (ex is OutOfMemoryException)
                {
                    throw;
                }
            }
            if ((object)assembly == null)
            {
                assembly = LoadAssemblyByPath(type, text);
            }
            if (assembly == null)
            {
                if (XmlSerializer.Mode == SerializationMode.PreGenOnly)
                {
                    throw new Exception(System.SR.Format(System.SR.FailLoadAssemblyUnderPregenMode, text));
                }
                return null;
            }
            if (!IsSerializerVersionMatch(assembly, type, defaultNamespace))
            {
                XmlSerializationEventSource.Log.XmlSerializerExpired(text, type.FullName);
                return null;
            }
        }
        else
        {
            XmlSerializerAssemblyAttribute xmlSerializerAssemblyAttribute = (XmlSerializerAssemblyAttribute)customAttributes[0];
            if (xmlSerializerAssemblyAttribute.AssemblyName != null && xmlSerializerAssemblyAttribute.CodeBase != null)
            {
                throw new InvalidOperationException(System.SR.Format(System.SR.XmlPregenInvalidXmlSerializerAssemblyAttribute, "AssemblyName", "CodeBase"));
            }
            if (xmlSerializerAssemblyAttribute.AssemblyName != null)
            {
                text = xmlSerializerAssemblyAttribute.AssemblyName;
                assembly = Assembly.Load(text);
            }
            else if (xmlSerializerAssemblyAttribute.CodeBase != null && xmlSerializerAssemblyAttribute.CodeBase.Length > 0)
            {
                text = xmlSerializerAssemblyAttribute.CodeBase;
                assembly = Assembly.LoadFrom(text);
            }
            else
            {
                text = type.Assembly.FullName;
                assembly = type.Assembly;
            }
            if (assembly == null)
            {
                throw new FileNotFoundException(null, text);
            }
        }
        Type typeFromAssembly = GetTypeFromAssembly(assembly, "XmlSerializerContract");
        contract = (XmlSerializerImplementation)Activator.CreateInstance(typeFromAssembly);
        if (contract.CanSerialize(type))
        {
            return assembly;
        }
        return null;
    }
References System.Activator.CreateInstance(), System.Xml.Dictionary, System.SR.FailLoadAssemblyUnderPregenMode, System.SR.Format(), System.Xml.Serialization.Compiler.GetTempAssemblyName(), System.Xml.Serialization.TempAssembly.GetTypeFromAssembly(), System.Globalization.CultureInfo.InvariantCulture, System.Xml.Serialization.TempAssembly.IsSerializerVersionMatch(), System.Reflection.Assembly.Load(), System.Xml.Serialization.TempAssembly.LoadAssemblyByPath(), System.Reflection.Assembly.LoadFrom(), System.Xml.Serialization.XmlSerializationEventSource.Log, System.Xml.Serialization.XmlSerializer.Mode, System.text, System.type, and System.SR.XmlPregenInvalidXmlSerializerAssemblyAttribute.
Referenced by System.Xml.Serialization.XmlSerializer.XmlSerializer(), and System.Xml.Serialization.XmlSerializer.FromMappings().