Terraria: System.Transactions.TransactionStatePromotedNonMSDTCBase.ChangeStateTransactionAborted
ChangeStateTransactionAborted()
override void System.Transactions.TransactionStatePromotedNonMSDTCBase.ChangeStateTransactionAborted (InternalTransaction tx, Exception e) inline package virtual inherited
Reimplemented from System.Transactions.TransactionState.
Reimplemented in System.Transactions.TransactionStatePromotedNonMSDTCSinglePhaseCommit.
Definition at line 122 of file TransactionStatePromotedNonMSDTCBase.cs.
    {
        if (tx._innerException == null)
        {
            tx._innerException = e;
        }
        TransactionState.TransactionStateAborted.EnterState(tx);
    }
References System.Transactions.InternalTransaction._innerException, and System.Transactions.TransactionState.TransactionStateAborted.
Referenced by System.Transactions.TransactionStatePromotedNonMSDTCVolatilePhase1.EnterState(), System.Transactions.TransactionStatePromotedNonMSDTCPhase0.Rollback(), and System.Transactions.TransactionStatePromotedNonMSDTCVolatilePhase1.Rollback().