Terraria: System.Text.Json.JsonReaderHelper.IsHexDigit
IsHexDigit()
static bool System.Text.Json.JsonReaderHelper.IsHexDigit (byte nextByte) inline static
Definition at line 55 of file JsonReaderHelper.cs.
    {
        return System.HexConverter.IsHexChar(nextByte);
    }
References System.Text.Json.Dictionary, and System.HexConverter.IsHexChar().
Referenced by System.Text.Json.Utf8JsonReader.ConsumeStringAndValidateMultiSegment(), System.Text.Json.Utf8JsonReader.ConsumeStringNextSegment(), and System.Text.Json.Utf8JsonReader.ValidateHexDigits().