Terraria: System.Text.Json.JsonReaderHelper.Unescape
Unescape()
static void System.Text.Json.JsonReaderHelper.Unescape (ReadOnlySpan< byte > source, Span< byte > destination, int idx, out int written) inline static package
Definition at line 481 of file JsonReaderHelper.cs.
    {
        source.Slice(0, idx).CopyTo(destination);
        written = idx;
        while (idx < source.Length)
        {
            byte b = source[idx];
            if (b == 92)
            {
                idx++;
                switch (source[idx])
                {
                case 34:
                    destination[written++] = 34;
                    break;
                case 110:
                    destination[written++] = 10;
                    break;
                case 114:
                    destination[written++] = 13;
                    break;
                case 92:
                    destination[written++] = 92;
                    break;
                case 47:
                    destination[written++] = 47;
                    break;
                case 116:
                    destination[written++] = 9;
                    break;
                case 98:
                    destination[written++] = 8;
                    break;
                case 102:
                    destination[written++] = 12;
                    break;
                case 117:
                {
                    bool flag = Utf8Parser.TryParse(source.Slice(idx + 1, 4), out int value, out int bytesConsumed, 'x');
                    idx += bytesConsumed;
                    if (JsonHelpers.IsInRangeInclusive((uint)value, 55296u, 57343u))
                    {
                        if (value >= 56320)
{
                            ThrowHelper.ThrowInvalidOperationException_ReadInvalidUTF16(value);
                        }
                        idx += 3;
                        if (source.Length < idx + 4 || source[idx - 2] != 92 || source[idx - 1] != 117)
{
                            ThrowHelper.ThrowInvalidOperationException_ReadInvalidUTF16();
                        }
                        flag = Utf8Parser.TryParse(source.Slice(idx, 4), out int value2, out bytesConsumed, 'x');
                        if (!JsonHelpers.IsInRangeInclusive((uint)value2, 56320u, 57343u))
{
                            ThrowHelper.ThrowInvalidOperationException_ReadInvalidUTF16(value2);
                        }
                        idx += bytesConsumed - 1;
                        value = 1024 * (value - 55296) + (value2 - 56320) + 65536;
                    }
                    int num = new Rune(value).EncodeToUtf8(destination.Slice(written));
                    written += num;
                    break;
                }
                }
            }
            else
            {
                destination[written++] = b;
            }
            idx++;
        }
    }
References System.destination, System.Text.Json.Dictionary, System.Text.Rune.EncodeToUtf8(), System.Text.Json.JsonHelpers.IsInRangeInclusive(), System.source, System.Text.Json.ThrowHelper.ThrowInvalidOperationException_ReadInvalidUTF16(), System.Buffers.Text.Utf8Parser.TryParse(), and System.value.
Referenced by System.Text.Json.Serialization.Converters.TimeSpanConverter.Read(), System.Text.Json.JsonDocument.TryGetNamedPropertyValue(), and System.Text.Json.JsonDocument.UnescapeString().