Terraria: System.Activator.CreateInstance
CreateInstance() [3/10]
static ? object System.Activator.CreateInstance ([DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicConstructors | DynamicallyAccessedMemberTypes.NonPublicConstructors)] Type type, BindingFlags bindingAttr, Binder? binder, object??[] args, CultureInfo? culture) inline static
Definition at line 17 of file Activator.cs.
    {
        return CreateInstance(type, bindingAttr, binder, args, culture, null);
    }
References System.Reflection.CreateInstance, System.culture, and System.type.
Referenced by System.ComponentModel.TypeDescriptor.ComNativeDescriptorProxy.ComNativeDescriptorProxy(), System.ComponentModel.BindingList< T >.AddNewCore(), System.Diagnostics.Metrics.AggregationManager.BuildInstrumentState(), System.ComponentModel.TypeDescriptor.CheckDefaultProvider(), System.ComponentModel.MaskedTextProvider.Clone(), System.Data.DataColumn.Clone(), System.Data.Common.DataAdapter.CloneInternals(), System.Data.Common.ObjectStorage.ConvertXmlToObject(), System.Data.Common.SqlUdtStorage.ConvertXmlToObject(), System.Data.Common.ObjectStorage.ConvertXmlToObject(), System.Data.Common.SqlUdtStorage.ConvertXmlToObject(), System.Linq.EnumerableExecutor< T >.Create(), System.Linq.EnumerableQuery< T >.Create(), System.Linq.EnumerableQuery< T >.Create(), System.Text.Json.Serialization.Converters.EnumConverterFactory.Create(), System.Text.Json.Serialization.Converters.EnumConverterFactory.Create(), System.Text.Json.Serialization.Converters.UnsupportedTypeConverterFactory.CreateConverter(), System.Text.Json.Serialization.Converters.FSharpTypeConverterFactory.CreateConverter(), System.Text.Json.Serialization.Converters.IEnumerableConverterFactory.CreateConverter(), System.Text.Json.Serialization.Converters.ObjectConverterFactory.CreateConverter(), System.Text.Json.Serialization.IAsyncEnumerableConverterFactory.CreateConverter(), System.ComponentModel.TypeDescriptor.CreateDesigner(), System.__ComObject.CreateEventProvider(), System.Text.Json.Serialization.Metadata.GenericMethodHolder< T >.CreateHolder(), System.Data.DataTable.CreateInstance(), System.Text.Json.Serialization.Metadata.ReflectionMemberAccessor.ConstructorContext.CreateInstance(), System.ComponentModel.ReflectTypeDescriptionProvider.CreateInstance(), Internal.Runtime.InteropServices.ComActivator.BasicClassFactory.CreateInstance(), System.ComponentModel.ReflectTypeDescriptionProvider.CreateInstance(), System.ComponentModel.TypeDescriptionProvider.CreateInstance(), System.AppDomain.CreateInstance(), System.AppDomain.CreateInstance(), System.AppDomain.CreateInstance(), System.Reflection.Assembly.CreateInstance(), System.RuntimeType.CreateInstanceImpl(), System.Data.DataSet.CreateInstanceOfThisType(), System.Text.Json.Serialization.Converters.ObjectConverterFactory.CreateKeyValuePairConverter(), System.Reflection.DispatchProxyGenerator.CreateProxyInstance(), System.Resources.ManifestBasedResourceGroveler.CreateResourceSet(), System.Resources.FileBasedResourceGroveler.CreateResourceSet(), System.Text.Json.Serialization.Converters.NullableConverterFactory.CreateValueConverter(), System.LazyHelper.CreateViaDefaultConstructor<[DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicParameterlessConstructor)] T >(), System.ComponentModel.LicenseManager.CreateWithContext(), System.Threading.LazyInitializer.EnsureInitializedCore<[DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicParameterlessConstructor)] T >(), System.Threading.LazyInitializer.EnsureInitializedCore<[DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicParameterlessConstructor)] T >(), System.Diagnostics.DiagnosticSourceEventSource.TransformSpec.PropertySpec.PropertyFetch.FetcherForProperty(), Microsoft.Xna.Framework.Graphics.VertexDeclaration.FromType(), System.Text.Json.JsonSerializerOptions.GetConverterFromAttribute(), System.Diagnostics.Tracing.EventSource.GetCustomAttributeHelper(), Internal.Runtime.InteropServices.LicenseInteropProxy.GetLicInfo(), System.Runtime.CompilerServices.ConditionalWeakTable< TKey, TValue >.GetOrCreateValue(), System.Diagnostics.Tracing.PropertyValue.GetReferenceTypePropertyGetter(), System.Resources.ResourceReader.InitializeBinaryFormatter(), System.Diagnostics.StackFrameHelper.InitializeSourceInfo(), System.Resources.ManifestBasedResourceGroveler.InternalGetResourceSetFromSerializedData(), System.Runtime.Serialization.SchemaExporter.InvokeGetSchemaMethod(), System.RuntimeType.InvokeMember(), System.Xml.Serialization.TempAssembly.LoadGeneratedAssembly(), System.Runtime.InteropServices.Marshal.PtrToStructure(), System.Runtime.InteropServices.Marshal.PtrToStructure<[DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicConstructors|DynamicallyAccessedMemberTypes.NonPublicConstructors)] T >(), System.Runtime.Serialization.ReflectionReader.ReflectionCreateCollection(), System.Xml.Serialization.ReflectionXmlSerializationReader.ReflectionCreateObject(), System.Xml.Serialization.SerializableMapping.RetrieveSerializableSchema(), System.Linq.Expressions.Interpreter.InitializeLocalInstruction.MutableValue.Run(), System.Linq.Expressions.Interpreter.InitializeLocalInstruction.MutableBox.Run(), System.Linq.Expressions.Interpreter.CallInstruction.SlowCreate(), System.ComponentModel.LicenseManager.ValidateInternalRecursive(), and System.Xml.Serialization.ReflectionXmlSerializationReader.WriteNullableMethod().