Terraria: System.Text.Json.JsonReaderHelper.TryGetEscapedDateTimeOffset
TryGetEscapedDateTimeOffset()
static bool System.Text.Json.JsonReaderHelper.TryGetEscapedDateTimeOffset (ReadOnlySpan< byte > source, out DateTimeOffset value) inline static
Definition at line 232 of file JsonReaderHelper.cs.
    {
        int idx = source.IndexOf<byte>(92);
        Span<byte> span = stackalloc byte[252];
        Unescape(source, span, idx, out var written);
        span = span.Slice(0, written);
        if (span.Length <= 42 && JsonHelpers.TryParseAsISO((ReadOnlySpan<byte>)span, out DateTimeOffset value2))
        {
            value = value2;
            return true;
        }
        value = default(DateTimeOffset);
        return false;
    }
References System.Text.Json.Dictionary, System.source, System.Text.Json.JsonHelpers.TryParseAsISO(), System.Unescape, and System.value.
Referenced by System.Text.Json.Utf8JsonReader.TryGetDateTimeOffsetCore(), and System.Text.Json.JsonDocument.TryGetValue().