Terraria: System.Activator.CreateInstanceInternal
CreateInstanceInternal()
static ObjectHandle System.Activator.CreateInstanceInternal (string assemblyString, string typeName, bool ignoreCase, BindingFlags bindingAttr, Binder binder, object[] args, CultureInfo culture, object[] activationAttributes, ref StackCrawlMark stackMark) inline static private
Definition at line 135 of file Activator.cs.
    {
        Assembly assembly;
        if (assemblyString == null)
        {
            assembly = Assembly.GetExecutingAssembly(ref stackMark);
        }
        else
        {
            AssemblyName assemblyName = new AssemblyName(assemblyString);
            assembly = RuntimeAssembly.InternalLoad(assemblyName, ref stackMark, AssemblyLoadContext.CurrentContextualReflectionContext);
        }
        Type type = assembly.GetType(typeName, throwOnError: true, ignoreCase);
        object obj = CreateInstance(type, bindingAttr, binder, args, culture, activationAttributes);
        if (obj == null)
        {
            return null;
        }
        return new ObjectHandle(obj);
    }
References System.Reflection.CreateInstance, System.culture, System.Runtime.Loader.AssemblyLoadContext.CurrentContextualReflectionContext, System.Reflection.Assembly.GetExecutingAssembly(), System.Reflection.Assembly.GetType(), System.Reflection.RuntimeAssembly.InternalLoad(), System.obj, and System.type.
Referenced by System.Activator.CreateInstance(), System.Activator.CreateInstance(), and System.Activator.CreateInstance().