Terraria: System.Text.Json.JsonReaderHelper.TryGetEscapedDateTime
TryGetEscapedDateTime()
static bool System.Text.Json.JsonReaderHelper.TryGetEscapedDateTime (ReadOnlySpan< byte > source, out DateTime value) inline static
Definition at line 217 of file JsonReaderHelper.cs.
    {
        int idx = source.IndexOf<byte>(92);
        Span<byte> span = stackalloc byte[252];
        Unescape(source, span, idx, out var written);
        span = span.Slice(0, written);
        if (span.Length <= 42 && JsonHelpers.TryParseAsISO((ReadOnlySpan<byte>)span, out DateTime value2))
        {
            value = value2;
            return true;
        }
        value = default(DateTime);
        return false;
    }
References System.Text.Json.Dictionary, System.source, System.Text.Json.JsonHelpers.TryParseAsISO(), System.Unescape, and System.value.
Referenced by System.Text.Json.Utf8JsonReader.TryGetDateTimeCore(), and System.Text.Json.JsonDocument.TryGetValue().