Terraria: System.Text.Json.JsonReaderHelper.IndexOfOrLessThan
IndexOfOrLessThan()
static unsafe int System.Text.Json.JsonReaderHelper.IndexOfOrLessThan (ref byte searchSpace, byte value0, byte value1, byte lessThan, int length) inline static private
Definition at line 66 of file JsonReaderHelper.cs.
    {
        IntPtr intPtr = (IntPtr)0;
        IntPtr intPtr2 = (IntPtr)length;
        if (Vector.IsHardwareAccelerated && length >= Vector<byte>.Count * 2)
        {
            int num = (int)Unsafe.AsPointer(ref searchSpace) & (Vector<byte>.Count - 1);
            intPtr2 = (IntPtr)((Vector<byte>.Count - num) & (Vector<byte>.Count - 1));
        }
        while (true)
        {
            if ((nuint)(void*)intPtr2 >= (nuint)8u)
            {
                intPtr2 -= 8;
                uint num2 = Unsafe.AddByteOffset(ref searchSpace, intPtr);
                if (value0 == num2 || value1 == num2 || lessThan > num2)
                {
                    goto IL_0393;
                }
                num2 = Unsafe.AddByteOffset(ref searchSpace, intPtr + 1);
                if (value0 == num2 || value1 == num2 || lessThan > num2)
                {
                    goto IL_039b;
                }
                num2 = Unsafe.AddByteOffset(ref searchSpace, intPtr + 2);
                if (value0 == num2 || value1 == num2 || lessThan > num2)
                {
                    goto IL_03a9;
                }
                num2 = Unsafe.AddByteOffset(ref searchSpace, intPtr + 3);
                if (value0 != num2 && value1 != num2 && lessThan <= num2)
                {
                    num2 = Unsafe.AddByteOffset(ref searchSpace, intPtr + 4);
                    if (value0 != num2 && value1 != num2 && lessThan <= num2)
                    {
                        num2 = Unsafe.AddByteOffset(ref searchSpace, intPtr + 5);
                        if (value0 != num2 && value1 != num2 && lessThan <= num2)
{
                            num2 = Unsafe.AddByteOffset(ref searchSpace, intPtr + 6);
                            if (value0 != num2 && value1 != num2 && lessThan <= num2)
{
                                num2 = Unsafe.AddByteOffset(ref searchSpace, intPtr + 7);
                                if (value0 == num2 || value1 == num2 || lessThan > num2)
{
                                    break;
                                }
                                intPtr += 8;
                                continue;
                            }
                            return (int)(void*)(intPtr + 6);
                        }
                        return (int)(void*)(intPtr + 5);
                    }
                    return (int)(void*)(intPtr + 4);
                }
                goto IL_03b7;
            }
            if ((nuint)(void*)intPtr2 >= (nuint)4u)
            {
                intPtr2 -= 4;
                uint num2 = Unsafe.AddByteOffset(ref searchSpace, intPtr);
                if (value0 == num2 || value1 == num2 || lessThan > num2)
                {
                    goto IL_0393;
                }
                num2 = Unsafe.AddByteOffset(ref searchSpace, intPtr + 1);
                if (value0 == num2 || value1 == num2 || lessThan > num2)
                {
                    goto IL_039b;
                }
                num2 = Unsafe.AddByteOffset(ref searchSpace, intPtr + 2);
                if (value0 == num2 || value1 == num2 || lessThan > num2)
                {
                    goto IL_03a9;
                }
                num2 = Unsafe.AddByteOffset(ref searchSpace, intPtr + 3);
                if (value0 == num2 || value1 == num2 || lessThan > num2)
                {
                    goto IL_03b7;
                }
                intPtr += 4;
            }
            while ((void*)intPtr2 != null)
            {
                intPtr2 -= 1;
                uint num2 = Unsafe.AddByteOffset(ref searchSpace, intPtr);
                if (value0 != num2 && value1 != num2 && lessThan <= num2)
                {
                    intPtr += 1;
                    continue;
                }
                goto IL_0393;
            }
            if (Vector.IsHardwareAccelerated && (int)(void*)intPtr < length)
            {
                intPtr2 = (IntPtr)((length - (int)(void*)intPtr) & ~(Vector<byte>.Count - 1));
                Vector<byte> right = new Vector<byte>(value0);
                Vector<byte> right2 = new Vector<byte>(value1);
                Vector<byte> right3 = new Vector<byte>(lessThan);
                for (; (void*)intPtr2 > (void*)intPtr; intPtr += Vector<byte>.Count)
                {
                    Vector<byte> left = Unsafe.ReadUnaligned<Vector<byte>>(ref Unsafe.AddByteOffset(ref searchSpace, intPtr));
                    Vector<byte> vector = Vector.BitwiseOr(Vector.BitwiseOr(Vector.Equals(left, right), Vector.Equals(left, right2)), Vector.LessThan(left, right3));
                    if (!Vector<byte>.Zero.Equals(vector))
                    {
                        return (int)(void*)intPtr + LocateFirstFoundByte(vector);
                    }
                }
                if ((int)(void*)intPtr < length)
                {
                    intPtr2 = (IntPtr)(length - (int)(void*)intPtr);
                    continue;
                }
            }
            return -1;
            IL_0393:
            return (int)(void*)intPtr;
            IL_039b:
            return (int)(void*)(intPtr + 1);
            IL_03b7:
            return (int)(void*)(intPtr + 3);
            IL_03a9:
            return (int)(void*)(intPtr + 2);
        }
        return (int)(void*)(intPtr + 7);
    }
References System.Numerics.Vector< T >.Count, System.Text.Json.Dictionary, System.Numerics.Vector< T >.Equals(), System.Text.Json.JsonReaderHelper.int, System.Numerics.Vector< T >.IsHardwareAccelerated, System.length, System.Numerics.Vector< T >.LessThan(), and System.Text.Json.JsonReaderHelper.LocateFirstFoundByte().
Referenced by System.Text.Json.JsonReaderHelper.IndexOfQuoteOrAnyControlOrBackSlash().