Terraria: System.Text.Json.JsonReaderHelper.TryDecodeBase64
TryDecodeBase64()
static bool System.Text.Json.JsonReaderHelper.TryDecodeBase64 (ReadOnlySpan< byte > utf8Unescaped, [NotNullWhen(true)] out byte[] bytes) inline static
Definition at line 416 of file JsonReaderHelper.cs.
    {
        byte[] array = null;
        Span<byte> span = ((utf8Unescaped.Length > 256) ? ((Span<byte>)(array = ArrayPool<byte>.Shared.Rent(utf8Unescaped.Length))) : stackalloc byte[256]);
        Span<byte> bytes2 = span;
        if (Base64.DecodeFromUtf8(utf8Unescaped, bytes2, out var _, out var bytesWritten) != 0)
        {
            bytes = null;
            if (array != null)
            {
                bytes2.Clear();
                ArrayPool<byte>.Shared.Return(array);
            }
            return false;
        }
        bytes = bytes2.Slice(0, bytesWritten).ToArray();
        if (array != null)
        {
            bytes2.Clear();
            ArrayPool<byte>.Shared.Return(array);
        }
        return true;
    }
References System.array, System.bytes, System.Span< T >.Clear(), System.Buffers.Text.Base64.DecodeFromUtf8(), System.Text.Json.Dictionary, and System.Buffers.ArrayPool< T >.Shared.
Referenced by System.Text.Json.Utf8JsonReader.TryGetBytesFromBase64(), and System.Text.Json.JsonDocument.TryGetValue().