Terraria: System.Text.Json.JsonReaderHelper.TranscodeHelper
TranscodeHelper()
static string System.Text.Json.JsonReaderHelper.TranscodeHelper (ReadOnlySpan< byte > utf8Unescaped) inline static
Definition at line 440 of file JsonReaderHelper.cs.
    {
        try
        {
            return s_utf8Encoding.GetString(utf8Unescaped);
        }
        catch (DecoderFallbackException innerException)
        {
            throw ThrowHelper.GetInvalidOperationException_ReadInvalidUTF8(innerException);
        }
    }
References System.Text.Json.Dictionary, System.Text.Json.ThrowHelper.GetInvalidOperationException_ReadInvalidUTF8(), and System.Text.Json.JsonReaderHelper.s_utf8Encoding.
Referenced by System.Text.Json.Utf8JsonReader.GetComment(), System.Text.Json.JsonDocument.GetPropertyRawValueAsString(), System.Text.Json.JsonDocument.GetRawValueAsString(), System.Text.Json.Utf8JsonReader.GetString(), System.Text.Json.JsonDocument.GetString(), System.Text.Json.JsonReaderHelper.GetUnescapedString(), System.Text.Json.JsonSerializer.WriteStringUsingGeneratedSerializer< TValue >(), and System.Text.Json.JsonSerializer.WriteStringUsingSerializer< TValue >().