Terraria: Entity.Distance
Distance()
float Entity.Distance (Vector2 Other) inline inherited
References Entity.Center.
Referenced by NPC.AI(), AI(), NPC.AI_003_Fighters(), NPC.AI_007_TownEntities(), NPC.AI_026_Unicorns(), AI_062(), NPC.AI_107_ImprovedWalkers(), NPC.AI_109_DarkMage(), NPC.AI_110_Betsy(), NPC.AI_112_FairyCritter(), NPC.AI_114_Dragonflies(), NPC.AI_115_LadyBugs(), NPC.AI_120_HallowBoss(), NPC.AI_120_HallowBoss_DashTo(), AI_120_StardustGuardian_FindTarget(), AI_121_StardustDragon(), NPC.AI_123_Deerclops(), NPC.AI_123_Deerclops_Movement(), AI_130_FlameBurstTower_FindTarget(), AI_134_Ballista_FindTarget(), AI_156_TryAttackingNPCs(), AI_158_BabyBird(), AI_169_Smolstars(), NPC.BloodNautilus_CallForHelp(), NPC.Boss_CanShootExtraAt(), CanHitWithMeleeWeapon(), CanHitWithOwnBody(), Mount.CastSuperCartLaser(), EmoteBubble.CheckForNPCsToReactToEmoteBubble(), NewMultiplayerClosePlayersOverlay.Draw(), Main.DrawInterface_14_EntityHealthBars(), Main.DrawNPCDirect(), LockOnHelper.GetClosestTarget(), MessageBuffer.GetData(), NPC.GetFairyTreasureCoords(), NPC.GetNPCLocation(), Player.GetZenithTarget(), ghostHeal(), HandleMovement(), Wiring.HitWireSingle(), Player.Hurt(), NPCUtils.SearchFilters.OnlyPlayersInCertainDistance(), LockOnHelper.RefreshTargets(), NPCUtils.SearchForTarget(), NPC.ShouldRunAway(), WorldGen.SpawnFallingBlockProjectile(), SmartCursorHelper.Step_Pickaxe_MineSolids(), SummonMonkGhast(), NPC.TargetClosestUpgraded(), BigProgressBarSystem.TryFindingNPCToTrack(), MoonlordDeathDrama.Update(), ScreenDarkness.Update(), Update(), and Player.VolatileGelatin().