Terraria: System.Data.BinaryNode.Optimize
Optimize()
override ExpressionNode System.Data.BinaryNode.Optimize () inline package inherited
Definition at line 133 of file BinaryNode.cs.
    {
        _left = _left.Optimize();
        if (_op == 13)
        {
            if (_right is UnaryNode)
            {
                UnaryNode unaryNode = (UnaryNode)_right;
                if (unaryNode._op != 3)
                {
                    throw ExprException.InvalidIsSyntax();
                }
                _op = 39;
                _right = unaryNode._right;
            }
            if (!(_right is ZeroOpNode))
            {
                throw ExprException.InvalidIsSyntax();
            }
            if (((ZeroOpNode)_right)._op != 32)
            {
                throw ExprException.InvalidIsSyntax();
            }
        }
        else
        {
            _right = _right.Optimize();
        }
        if (IsConstant())
        {
            object obj = EvalConstant();
            if (obj == DBNull.Value)
            {
                return new ZeroOpNode(32);
            }
            if (obj is bool)
            {
                if ((bool)obj)
                {
                    return new ZeroOpNode(33);
                }
                return new ZeroOpNode(34);
            }
            return new ConstNode(base.table, ValueType.Object, obj, fParseQuotes: false);
        }
        return this;
    }
References System.Data.BinaryNode._left, System.Data.BinaryNode._op, System.Data.BinaryNode._right, System.Data.BinaryNode.EvalConstant(), System.Data.ExprException.InvalidIsSyntax(), System.Data.BinaryNode.IsConstant(), System.obj, System.Data.ExpressionNode.Optimize(), and System.DBNull.Value.