Terraria: System.Data.BinaryNode.ResultType
ResultType()
StorageType System.Data.BinaryNode.ResultType (StorageType left, StorageType right, bool lc, bool rc, int op) inline package inherited
Definition at line 1006 of file BinaryNode.cs.
    {
        if (left == StorageType.Guid && right == StorageType.Guid && Operators.IsRelational(op))
        {
            return left;
        }
        if (left == StorageType.String && right == StorageType.Guid && Operators.IsRelational(op))
        {
            return left;
        }
        if (left == StorageType.Guid && right == StorageType.String && Operators.IsRelational(op))
        {
            return right;
        }
        int precedence = (int)GetPrecedence(left);
        if (precedence == 0)
        {
            return StorageType.Empty;
        }
        int precedence2 = (int)GetPrecedence(right);
        if (precedence2 == 0)
        {
            return StorageType.Empty;
        }
        if (Operators.IsLogical(op))
        {
            if (left == StorageType.Boolean && right == StorageType.Boolean)
            {
                return StorageType.Boolean;
            }
            return StorageType.Empty;
        }
        if (left == StorageType.DateTimeOffset || right == StorageType.DateTimeOffset)
        {
            if (Operators.IsRelational(op) && left == StorageType.DateTimeOffset && right == StorageType.DateTimeOffset)
            {
                return StorageType.DateTimeOffset;
            }
            return StorageType.Empty;
        }
        if (op == 15 && (left == StorageType.String || right == StorageType.String))
        {
            return StorageType.String;
        }
        DataTypePrecedence dataTypePrecedence = (DataTypePrecedence)Math.Max(precedence, precedence2);
        StorageType precedenceType = GetPrecedenceType(dataTypePrecedence);
        if (Operators.IsArithmetical(op) && precedenceType != StorageType.String && precedenceType != StorageType.Char)
        {
            if (!ExpressionNode.IsNumeric(left))
            {
                return StorageType.Empty;
            }
            if (!ExpressionNode.IsNumeric(right))
            {
                return StorageType.Empty;
            }
        }
        if (op == 18 && ExpressionNode.IsInteger(precedenceType))
        {
            return StorageType.Double;
        }
        if (IsMixed(left, right))
        {
            if (lc && !rc)
            {
                return right;
            }
            if (!lc && rc)
            {
                return left;
            }
            if (ExpressionNode.IsUnsigned(precedenceType))
            {
                if (dataTypePrecedence >= DataTypePrecedence.UInt64)
                {
                    throw ExprException.AmbiguousBinop(op, DataStorage.GetTypeStorage(left), DataStorage.GetTypeStorage(right));
                }
                precedenceType = GetPrecedenceType(dataTypePrecedence + 1);
            }
        }
        return precedenceType;
    }
References System.Data.ExprException.AmbiguousBinop(), System.Data.BinaryNode.GetPrecedence(), System.Data.BinaryNode.GetPrecedenceType(), System.Data.Common.DataStorage.GetTypeStorage(), System.Data.Operators.IsArithmetical(), System.Data.ExpressionNode.IsInteger(), System.Data.Operators.IsLogical(), System.Data.BinaryNode.IsMixed(), System.Data.ExpressionNode.IsNumeric(), System.Data.Operators.IsRelational(), System.Data.ExpressionNode.IsUnsigned(), and System.Math.Max().
Referenced by System.Data.Select.Eval(), and System.Data.BinaryNode.EvalBinaryOp().