Terraria: System.Data.BinaryNode.ResultSqlType
ResultSqlType()
StorageType System.Data.BinaryNode.ResultSqlType (StorageType left, StorageType right, bool lc, bool rc, int op) inline package inherited
Definition at line 1089 of file BinaryNode.cs.
    {
        int precedence = (int)GetPrecedence(left);
        if (precedence == 0)
        {
            return StorageType.Empty;
        }
        int precedence2 = (int)GetPrecedence(right);
        if (precedence2 == 0)
        {
            return StorageType.Empty;
        }
        if (Operators.IsLogical(op))
        {
            if ((left != StorageType.Boolean && left != StorageType.SqlBoolean) || (right != StorageType.Boolean && right != StorageType.SqlBoolean))
            {
                return StorageType.Empty;
            }
            if (left == StorageType.Boolean && right == StorageType.Boolean)
            {
                return StorageType.Boolean;
            }
            return StorageType.SqlBoolean;
        }
        if (op == 15)
        {
            if (left == StorageType.SqlString || right == StorageType.SqlString)
            {
                return StorageType.SqlString;
            }
            if (left == StorageType.String || right == StorageType.String)
            {
                return StorageType.String;
            }
        }
        if ((left == StorageType.SqlBinary && right != StorageType.SqlBinary) || (left != StorageType.SqlBinary && right == StorageType.SqlBinary))
        {
            return StorageType.Empty;
        }
        if ((left == StorageType.SqlGuid && right != StorageType.SqlGuid) || (left != StorageType.SqlGuid && right == StorageType.SqlGuid))
        {
            return StorageType.Empty;
        }
        if (precedence > 19 && precedence2 < 20)
        {
            return StorageType.Empty;
        }
        if (precedence < 20 && precedence2 > 19)
        {
            return StorageType.Empty;
        }
        if (precedence > 19)
        {
            if (op == 15 || op == 16)
            {
                if (left == StorageType.TimeSpan)
                {
                    return right;
                }
                if (right == StorageType.TimeSpan)
                {
                    return left;
                }
                return StorageType.Empty;
            }
            if (!Operators.IsRelational(op))
            {
                return StorageType.Empty;
            }
            return left;
        }
        DataTypePrecedence dataTypePrecedence = (DataTypePrecedence)Math.Max(precedence, precedence2);
        StorageType precedenceType = GetPrecedenceType(dataTypePrecedence);
        precedenceType = GetPrecedenceType((DataTypePrecedence)SqlResultType((int)dataTypePrecedence));
        if (Operators.IsArithmetical(op) && precedenceType != StorageType.String && precedenceType != StorageType.Char && precedenceType != StorageType.SqlString)
        {
            if (!ExpressionNode.IsNumericSql(left))
            {
                return StorageType.Empty;
            }
            if (!ExpressionNode.IsNumericSql(right))
            {
                return StorageType.Empty;
            }
        }
        if (op == 18 && ExpressionNode.IsIntegerSql(precedenceType))
        {
            return StorageType.SqlDouble;
        }
        if (precedenceType == StorageType.SqlMoney && left != StorageType.SqlMoney && right != StorageType.SqlMoney)
        {
            precedenceType = StorageType.SqlDecimal;
        }
        if (IsMixedSql(left, right) && ExpressionNode.IsUnsignedSql(precedenceType))
        {
            if (dataTypePrecedence >= DataTypePrecedence.UInt64)
            {
                throw ExprException.AmbiguousBinop(op, DataStorage.GetTypeStorage(left), DataStorage.GetTypeStorage(right));
            }
            precedenceType = GetPrecedenceType(dataTypePrecedence + 1);
        }
        return precedenceType;
    }
References System.Data.ExprException.AmbiguousBinop(), System.Data.BinaryNode.GetPrecedence(), System.Data.BinaryNode.GetPrecedenceType(), System.Data.Common.DataStorage.GetTypeStorage(), System.Data.Operators.IsArithmetical(), System.Data.ExpressionNode.IsIntegerSql(), System.Data.Operators.IsLogical(), System.Data.BinaryNode.IsMixedSql(), System.Data.ExpressionNode.IsNumericSql(), System.Data.Operators.IsRelational(), System.Data.ExpressionNode.IsUnsignedSql(), System.Math.Max(), and System.Data.BinaryNode.SqlResultType().
Referenced by System.Data.Select.Eval(), and System.Data.BinaryNode.EvalBinaryOp().