Terraria: System.Data.BinaryNode.BinaryCompare
BinaryCompare() [2/2]
int System.Data.BinaryNode.BinaryCompare (object vLeft, object vRight, StorageType resultType, int op, CompareInfo comparer) inline package inherited
Definition at line 207 of file BinaryNode.cs.
    {
        int result = 0;
        try
        {
            if (!DataStorage.IsSqlType(resultType))
            {
                switch (resultType)
                {
                case StorageType.SByte:
                case StorageType.Byte:
                case StorageType.Int16:
                case StorageType.UInt16:
                case StorageType.Int32:
                    return Convert.ToInt32(vLeft, base.FormatProvider).CompareTo(Convert.ToInt32(vRight, base.FormatProvider));
                case StorageType.UInt32:
                case StorageType.Int64:
                case StorageType.UInt64:
                case StorageType.Decimal:
                    return decimal.Compare(Convert.ToDecimal(vLeft, base.FormatProvider), Convert.ToDecimal(vRight, base.FormatProvider));
                case StorageType.Char:
                    return Convert.ToInt32(vLeft, base.FormatProvider).CompareTo(Convert.ToInt32(vRight, base.FormatProvider));
                case StorageType.Double:
                    return Convert.ToDouble(vLeft, base.FormatProvider).CompareTo(Convert.ToDouble(vRight, base.FormatProvider));
                case StorageType.Single:
                    return Convert.ToSingle(vLeft, base.FormatProvider).CompareTo(Convert.ToSingle(vRight, base.FormatProvider));
                case StorageType.DateTime:
                    return DateTime.Compare(Convert.ToDateTime(vLeft, base.FormatProvider), Convert.ToDateTime(vRight, base.FormatProvider));
                case StorageType.DateTimeOffset:
                    return DateTimeOffset.Compare((DateTimeOffset)vLeft, (DateTimeOffset)vRight);
                case StorageType.String:
                    return base.table.Compare(Convert.ToString(vLeft, base.FormatProvider), Convert.ToString(vRight, base.FormatProvider), comparer);
                case StorageType.Guid:
                    return ((Guid)vLeft).CompareTo((Guid)vRight);
                case StorageType.Boolean:
                    if (op == 7 || op == 12)
                    {
                        return Convert.ToInt32(DataExpression.ToBoolean(vLeft), base.FormatProvider) - Convert.ToInt32(DataExpression.ToBoolean(vRight), base.FormatProvider);
                    }
                    break;
                case StorageType.TimeSpan:
                case StorageType.ByteArray:
                case StorageType.CharArray:
                case StorageType.Type:
                    break;
                }
            }
            else
            {
                switch (resultType)
                {
                case StorageType.SByte:
                case StorageType.Byte:
                case StorageType.Int16:
                case StorageType.UInt16:
                case StorageType.Int32:
                case StorageType.SqlByte:
                case StorageType.SqlInt16:
                case StorageType.SqlInt32:
                    return SqlConvert.ConvertToSqlInt32(vLeft).CompareTo(SqlConvert.ConvertToSqlInt32(vRight));
                case StorageType.UInt32:
                case StorageType.Int64:
                case StorageType.SqlInt64:
                    return SqlConvert.ConvertToSqlInt64(vLeft).CompareTo(SqlConvert.ConvertToSqlInt64(vRight));
                case StorageType.UInt64:
                case StorageType.SqlDecimal:
                    return SqlConvert.ConvertToSqlDecimal(vLeft).CompareTo(SqlConvert.ConvertToSqlDecimal(vRight));
                case StorageType.SqlDouble:
                    return SqlConvert.ConvertToSqlDouble(vLeft).CompareTo(SqlConvert.ConvertToSqlDouble(vRight));
                case StorageType.SqlSingle:
                    return SqlConvert.ConvertToSqlSingle(vLeft).CompareTo(SqlConvert.ConvertToSqlSingle(vRight));
                case StorageType.SqlString:
                    return base.table.Compare(vLeft.ToString(), vRight.ToString());
                case StorageType.SqlGuid:
                    return ((SqlGuid)vLeft).CompareTo(vRight);
                case StorageType.SqlBoolean:
                    if (op == 7 || op == 12)
                    {
                        result = 1;
                        if ((vLeft.GetType() == typeof(SqlBoolean) && (vRight.GetType() == typeof(SqlBoolean) || vRight.GetType() == typeof(bool))) || (vRight.GetType() == typeof(SqlBoolean) && (vLeft.GetType() == typeof(SqlBoolean) || vLeft.GetType() == typeof(bool))))
{
                            return SqlConvert.ConvertToSqlBoolean(vLeft).CompareTo(SqlConvert.ConvertToSqlBoolean(vRight));
                        }
                    }
                    break;
                case StorageType.SqlBinary:
                    return SqlConvert.ConvertToSqlBinary(vLeft).CompareTo(SqlConvert.ConvertToSqlBinary(vRight));
                case StorageType.SqlDateTime:
                    return SqlConvert.ConvertToSqlDateTime(vLeft).CompareTo(SqlConvert.ConvertToSqlDateTime(vRight));
                case StorageType.SqlMoney:
                    return SqlConvert.ConvertToSqlMoney(vLeft).CompareTo(SqlConvert.ConvertToSqlMoney(vRight));
                case StorageType.Single:
                case StorageType.Double:
                case StorageType.Decimal:
                case StorageType.DateTime:
                case StorageType.TimeSpan:
                case StorageType.String:
                case StorageType.Guid:
                case StorageType.ByteArray:
                case StorageType.CharArray:
                case StorageType.Type:
                case StorageType.DateTimeOffset:
                case StorageType.BigInteger:
                case StorageType.Uri:
                case StorageType.SqlBytes:
                case StorageType.SqlChars:
                    break;
                }
            }
        }
        catch (ArgumentException e)
        {
            ExceptionBuilder.TraceExceptionWithoutRethrow(e);
        }
        catch (FormatException e2)
        {
            ExceptionBuilder.TraceExceptionWithoutRethrow(e2);
        }
        catch (InvalidCastException e3)
        {
            ExceptionBuilder.TraceExceptionWithoutRethrow(e3);
        }
        catch (OverflowException e4)
        {
            ExceptionBuilder.TraceExceptionWithoutRethrow(e4);
        }
        catch (EvaluateException e5)
        {
            ExceptionBuilder.TraceExceptionWithoutRethrow(e5);
        }
        SetTypeMismatchError(op, vLeft.GetType(), vRight.GetType());
        return result;
    }
References System.DateTime.Compare(), System.DateTimeOffset.Compare(), System.comparer, System.Data.Common.SqlConvert.ConvertToSqlBinary(), System.Data.Common.SqlConvert.ConvertToSqlBoolean(), System.Data.Common.SqlConvert.ConvertToSqlDateTime(), System.Data.Common.SqlConvert.ConvertToSqlDecimal(), System.Data.Common.SqlConvert.ConvertToSqlDouble(), System.Data.Common.SqlConvert.ConvertToSqlInt32(), System.Data.Common.SqlConvert.ConvertToSqlInt64(), System.Data.Common.SqlConvert.ConvertToSqlMoney(), System.Data.Common.SqlConvert.ConvertToSqlSingle(), System.Data.Common.DataStorage.IsSqlType(), System.Data.BinaryNode.SetTypeMismatchError(), System.Data.DataExpression.ToBoolean(), System.Convert.ToDateTime(), System.Convert.ToDecimal(), System.Convert.ToDouble(), System.Convert.ToInt32(), System.Convert.ToSingle(), System.Convert.ToString(), and System.Data.ExceptionBuilder.TraceExceptionWithoutRethrow().