Terraria: Terraria.GameContent.RGB.DD2Shader.ProcessHighDetail
ProcessHighDetail()
void Terraria.GameContent.RGB.DD2Shader.ProcessHighDetail (RgbDevice device, Fragment fragment, EffectDetailLevel quality, float time) inline private
Definition at line 19 of file DD2Shader.cs.
    {
        //IL_0007: Unknown result type (might be due to invalid IL or missing references)
        Vector2 vector = fragment.CanvasCenter;
        if ((int)quality == 0)
        {
            vector = new Vector2(1.7f, 0.5f);
        }
        time *= 0.5f;
        for (int i = 0; i < fragment.Count; i++)
        {
            Vector2 canvasPositionOfIndex = fragment.GetCanvasPositionOfIndex(i);
            Vector4 value = new Vector4(0f, 0f, 0f, 1f);
            float num = (canvasPositionOfIndex - vector).Length();
            float num2 = num * num * 0.75f;
            float num3 = (num - time) % 1f;
            if (num3 < 0f)
            {
                num3 += 1f;
            }
            num3 = ((!(num3 > 0.8f)) ? (num3 / 0.8f) : (num3 * (1f - (num3 - 1f + 0.2f) / 0.2f)));
            Vector4 value2 = Vector4.Lerp(_darkGlowColor, _lightGlowColor, num3 * num3);
            num3 *= MathHelper.Clamp(1f - num2, 0f, 1f) * 0.75f + 0.25f;
            value = Vector4.Lerp(value, value2, num3);
            if (num < 0.5f)
            {
                float amount = 1f - MathHelper.Clamp((num - 0.5f + 0.4f) / 0.4f, 0f, 1f);
                value = Vector4.Lerp(value, _lightGlowColor, amount);
            }
            fragment.SetColor(i, value);
        }
    }
References Terraria.GameContent.RGB.DD2Shader._darkGlowColor, Terraria.GameContent.RGB.DD2Shader._lightGlowColor, ReLogic.Peripherals.RGB.Fragment.CanvasCenter, Microsoft.Xna.Framework.MathHelper.Clamp(), ReLogic.Peripherals.RGB.Fragment.Count, ReLogic.Peripherals.RGB.Fragment.GetCanvasPositionOfIndex(), Microsoft.Xna.Framework.Vector4.Lerp(), and ReLogic.Peripherals.RGB.Fragment.SetColor().