Terraria: System.Data.BinaryNode.EvalBinaryOp
EvalBinaryOp()
object System.Data.BinaryNode.EvalBinaryOp (int op, ExpressionNode left, ExpressionNode right, DataRow row, DataRowVersion version, int[] recordNos) inline private inherited
Definition at line 342 of file BinaryNode.cs.
    {
        object obj2;
        StorageType storageType3;
        object obj;
        if (op != 27 && op != 26 && op != 5 && op != 13 && op != 39)
        {
            obj = Eval(left, row, version, recordNos);
            obj2 = Eval(right, row, version, recordNos);
            Type type = obj.GetType();
            Type type2 = obj2.GetType();
            StorageType storageType = DataStorage.GetStorageType(type);
            StorageType storageType2 = DataStorage.GetStorageType(type2);
            bool flag = DataStorage.IsSqlType(storageType);
            bool flag2 = DataStorage.IsSqlType(storageType2);
            if (flag && DataStorage.IsObjectSqlNull(obj))
            {
                return obj;
            }
            if (flag2 && DataStorage.IsObjectSqlNull(obj2))
            {
                return obj2;
            }
            if (obj == DBNull.Value || obj2 == DBNull.Value)
            {
                return DBNull.Value;
            }
            storageType3 = ((!(flag || flag2)) ? ResultType(storageType, storageType2, left is ConstNode, right is ConstNode, op) : ResultSqlType(storageType, storageType2, left is ConstNode, right is ConstNode, op));
            if (storageType3 == StorageType.Empty)
            {
                SetTypeMismatchError(op, type, type2);
            }
        }
        else
        {
            obj = (obj2 = DBNull.Value);
            storageType3 = StorageType.Empty;
        }
        object result = DBNull.Value;
        bool flag3 = false;
        try
        {
            switch (op)
            {
            case 15:
                switch (storageType3)
                {
                case StorageType.Byte:
                    result = Convert.ToByte(Convert.ToByte(obj, base.FormatProvider) + Convert.ToByte(obj2, base.FormatProvider), base.FormatProvider);
                    break;
                case StorageType.SByte:
                    result = Convert.ToSByte(Convert.ToSByte(obj, base.FormatProvider) + Convert.ToSByte(obj2, base.FormatProvider), base.FormatProvider);
                    break;
                case StorageType.Int16:
                    result = Convert.ToInt16(Convert.ToInt16(obj, base.FormatProvider) + Convert.ToInt16(obj2, base.FormatProvider), base.FormatProvider);
                    break;
                case StorageType.UInt16:
                    result = Convert.ToUInt16(Convert.ToUInt16(obj, base.FormatProvider) + Convert.ToUInt16(obj2, base.FormatProvider), base.FormatProvider);
                    break;
                case StorageType.Int32:
                    result = checked(Convert.ToInt32(obj, base.FormatProvider) + Convert.ToInt32(obj2, base.FormatProvider));
                    break;
                case StorageType.UInt32:
                    result = checked(Convert.ToUInt32(obj, base.FormatProvider) + Convert.ToUInt32(obj2, base.FormatProvider));
                    break;
                case StorageType.UInt64:
                    result = checked(Convert.ToUInt64(obj, base.FormatProvider) + Convert.ToUInt64(obj2, base.FormatProvider));
                    break;
                case StorageType.Int64:
                    result = checked(Convert.ToInt64(obj, base.FormatProvider) + Convert.ToInt64(obj2, base.FormatProvider));
                    break;
                case StorageType.Decimal:
                    result = Convert.ToDecimal(obj, base.FormatProvider) + Convert.ToDecimal(obj2, base.FormatProvider);
                    break;
                case StorageType.Single:
                    result = Convert.ToSingle(obj, base.FormatProvider) + Convert.ToSingle(obj2, base.FormatProvider);
                    break;
                case StorageType.Double:
                    result = Convert.ToDouble(obj, base.FormatProvider) + Convert.ToDouble(obj2, base.FormatProvider);
                    break;
                case StorageType.Char:
                case StorageType.String:
                    result = Convert.ToString(obj, base.FormatProvider) + Convert.ToString(obj2, base.FormatProvider);
                    break;
                case StorageType.DateTime:
                    if (obj is TimeSpan && obj2 is DateTime)
                    {
                        result = (DateTime)obj2 + (TimeSpan)obj;
                    }
                    else if (obj is DateTime && obj2 is TimeSpan)
                    {
                        result = (DateTime)obj + (TimeSpan)obj2;
                    }
                    else
                    {
                        flag3 = true;
                    }
                    break;
                case StorageType.TimeSpan:
                    result = (TimeSpan)obj + (TimeSpan)obj2;
                    break;
                case StorageType.SqlInt16:
                    result = SqlConvert.ConvertToSqlInt16(obj) + SqlConvert.ConvertToSqlInt16(obj2);
                    break;
                case StorageType.SqlInt32:
                    result = SqlConvert.ConvertToSqlInt32(obj) + SqlConvert.ConvertToSqlInt32(obj2);
                    break;
                case StorageType.SqlInt64:
                    result = SqlConvert.ConvertToSqlInt64(obj) + SqlConvert.ConvertToSqlInt64(obj2);
                    break;
                case StorageType.SqlDouble:
                    result = SqlConvert.ConvertToSqlDouble(obj) + SqlConvert.ConvertToSqlDouble(obj2);
                    break;
                case StorageType.SqlSingle:
                    result = SqlConvert.ConvertToSqlSingle(obj) + SqlConvert.ConvertToSqlSingle(obj2);
                    break;
                case StorageType.SqlDecimal:
                    result = SqlConvert.ConvertToSqlDecimal(obj) + SqlConvert.ConvertToSqlDecimal(obj2);
                    break;
                case StorageType.SqlMoney:
                    result = SqlConvert.ConvertToSqlMoney(obj) + SqlConvert.ConvertToSqlMoney(obj2);
                    break;
                case StorageType.SqlByte:
                    result = SqlConvert.ConvertToSqlByte(obj) + SqlConvert.ConvertToSqlByte(obj2);
                    break;
                case StorageType.SqlString:
                    result = SqlConvert.ConvertToSqlString(obj) + SqlConvert.ConvertToSqlString(obj2);
                    break;
                case StorageType.SqlDateTime:
                    if (obj is TimeSpan && obj2 is SqlDateTime)
                    {
                        result = SqlConvert.ConvertToSqlDateTime(SqlConvert.ConvertToSqlDateTime(obj2).Value + (TimeSpan)obj);
                    }
                    else if (obj is SqlDateTime && obj2 is TimeSpan)
                    {
                        result = SqlConvert.ConvertToSqlDateTime(SqlConvert.ConvertToSqlDateTime(obj).Value + (TimeSpan)obj2);
                    }
                    else
                    {
                        flag3 = true;
                    }
                    break;
                default:
                    flag3 = true;
                    break;
                }
                break;
            case 16:
                switch (storageType3)
                {
                case StorageType.Byte:
                    result = Convert.ToByte(Convert.ToByte(obj, base.FormatProvider) - Convert.ToByte(obj2, base.FormatProvider), base.FormatProvider);
                    break;
                case StorageType.SqlByte:
                    result = SqlConvert.ConvertToSqlByte(obj) - SqlConvert.ConvertToSqlByte(obj2);
                    break;
                case StorageType.SByte:
                    result = Convert.ToSByte(Convert.ToSByte(obj, base.FormatProvider) - Convert.ToSByte(obj2, base.FormatProvider), base.FormatProvider);
                    break;
                case StorageType.Int16:
                    result = Convert.ToInt16(Convert.ToInt16(obj, base.FormatProvider) - Convert.ToInt16(obj2, base.FormatProvider), base.FormatProvider);
                    break;
                case StorageType.SqlInt16:
                    result = SqlConvert.ConvertToSqlInt16(obj) - SqlConvert.ConvertToSqlInt16(obj2);
                    break;
                case StorageType.UInt16:
                    result = Convert.ToUInt16(Convert.ToUInt16(obj, base.FormatProvider) - Convert.ToUInt16(obj2, base.FormatProvider), base.FormatProvider);
                    break;
                case StorageType.Int32:
                    result = checked(Convert.ToInt32(obj, base.FormatProvider) - Convert.ToInt32(obj2, base.FormatProvider));
                    break;
                case StorageType.SqlInt32:
                    result = SqlConvert.ConvertToSqlInt32(obj) - SqlConvert.ConvertToSqlInt32(obj2);
                    break;
                case StorageType.UInt32:
                    result = checked(Convert.ToUInt32(obj, base.FormatProvider) - Convert.ToUInt32(obj2, base.FormatProvider));
                    break;
                case StorageType.Int64:
                    result = checked(Convert.ToInt64(obj, base.FormatProvider) - Convert.ToInt64(obj2, base.FormatProvider));
                    break;
                case StorageType.SqlInt64:
                    result = SqlConvert.ConvertToSqlInt64(obj) - SqlConvert.ConvertToSqlInt64(obj2);
                    break;
                case StorageType.UInt64:
                    result = checked(Convert.ToUInt64(obj, base.FormatProvider) - Convert.ToUInt64(obj2, base.FormatProvider));
                    break;
                case StorageType.Decimal:
                    result = Convert.ToDecimal(obj, base.FormatProvider) - Convert.ToDecimal(obj2, base.FormatProvider);
                    break;
                case StorageType.SqlDecimal:
                    result = SqlConvert.ConvertToSqlDecimal(obj) - SqlConvert.ConvertToSqlDecimal(obj2);
                    break;
                case StorageType.Single:
                    result = Convert.ToSingle(obj, base.FormatProvider) - Convert.ToSingle(obj2, base.FormatProvider);
                    break;
                case StorageType.SqlSingle:
                    result = SqlConvert.ConvertToSqlSingle(obj) - SqlConvert.ConvertToSqlSingle(obj2);
                    break;
                case StorageType.Double:
                    result = Convert.ToDouble(obj, base.FormatProvider) - Convert.ToDouble(obj2, base.FormatProvider);
                    break;
                case StorageType.SqlDouble:
                    result = SqlConvert.ConvertToSqlDouble(obj) - SqlConvert.ConvertToSqlDouble(obj2);
                    break;
                case StorageType.SqlMoney:
                    result = SqlConvert.ConvertToSqlMoney(obj) - SqlConvert.ConvertToSqlMoney(obj2);
                    break;
                case StorageType.DateTime:
                    result = (DateTime)obj - (TimeSpan)obj2;
                    break;
                case StorageType.TimeSpan:
                    result = ((!(obj is DateTime)) ? ((object)((TimeSpan)obj - (TimeSpan)obj2)) : ((object)((DateTime)obj - (DateTime)obj2)));
                    break;
                case StorageType.SqlDateTime:
                    if (obj is TimeSpan && obj2 is SqlDateTime)
                    {
                        result = SqlConvert.ConvertToSqlDateTime(SqlConvert.ConvertToSqlDateTime(obj2).Value - (TimeSpan)obj);
                    }
                    else if (obj is SqlDateTime && obj2 is TimeSpan)
                    {
                        result = SqlConvert.ConvertToSqlDateTime(SqlConvert.ConvertToSqlDateTime(obj).Value - (TimeSpan)obj2);
                    }
                    else
                    {
                        flag3 = true;
                    }
                    break;
                default:
                    flag3 = true;
                    break;
                }
                break;
            case 17:
                switch (storageType3)
                {
                case StorageType.Byte:
                    result = Convert.ToByte(Convert.ToByte(obj, base.FormatProvider) * Convert.ToByte(obj2, base.FormatProvider), base.FormatProvider);
                    break;
                case StorageType.SqlByte:
                    result = SqlConvert.ConvertToSqlByte(obj) * SqlConvert.ConvertToSqlByte(obj2);
                    break;
                case StorageType.SByte:
                    result = Convert.ToSByte(Convert.ToSByte(obj, base.FormatProvider) * Convert.ToSByte(obj2, base.FormatProvider), base.FormatProvider);
                    break;
                case StorageType.Int16:
                    result = Convert.ToInt16(Convert.ToInt16(obj, base.FormatProvider) * Convert.ToInt16(obj2, base.FormatProvider), base.FormatProvider);
                    break;
                case StorageType.SqlInt16:
                    result = SqlConvert.ConvertToSqlInt16(obj) * SqlConvert.ConvertToSqlInt16(obj2);
                    break;
                case StorageType.UInt16:
                    result = Convert.ToUInt16(Convert.ToUInt16(obj, base.FormatProvider) * Convert.ToUInt16(obj2, base.FormatProvider), base.FormatProvider);
                    break;
                case StorageType.Int32:
                    result = checked(Convert.ToInt32(obj, base.FormatProvider) * Convert.ToInt32(obj2, base.FormatProvider));
                    break;
                case StorageType.SqlInt32:
                    result = SqlConvert.ConvertToSqlInt32(obj) * SqlConvert.ConvertToSqlInt32(obj2);
                    break;
                case StorageType.UInt32:
                    result = checked(Convert.ToUInt32(obj, base.FormatProvider) * Convert.ToUInt32(obj2, base.FormatProvider));
                    break;
                case StorageType.Int64:
                    result = checked(Convert.ToInt64(obj, base.FormatProvider) * Convert.ToInt64(obj2, base.FormatProvider));
                    break;
                case StorageType.SqlInt64:
                    result = SqlConvert.ConvertToSqlInt64(obj) * SqlConvert.ConvertToSqlInt64(obj2);
                    break;
                case StorageType.UInt64:
                    result = checked(Convert.ToUInt64(obj, base.FormatProvider) * Convert.ToUInt64(obj2, base.FormatProvider));
                    break;
                case StorageType.Decimal:
                    result = Convert.ToDecimal(obj, base.FormatProvider) * Convert.ToDecimal(obj2, base.FormatProvider);
                    break;
                case StorageType.SqlDecimal:
                    result = SqlConvert.ConvertToSqlDecimal(obj) * SqlConvert.ConvertToSqlDecimal(obj2);
                    break;
                case StorageType.Single:
                    result = Convert.ToSingle(obj, base.FormatProvider) * Convert.ToSingle(obj2, base.FormatProvider);
                    break;
                case StorageType.SqlSingle:
                    result = SqlConvert.ConvertToSqlSingle(obj) * SqlConvert.ConvertToSqlSingle(obj2);
                    break;
                case StorageType.SqlMoney:
                    result = SqlConvert.ConvertToSqlMoney(obj) * SqlConvert.ConvertToSqlMoney(obj2);
                    break;
                case StorageType.Double:
                    result = Convert.ToDouble(obj, base.FormatProvider) * Convert.ToDouble(obj2, base.FormatProvider);
                    break;
                case StorageType.SqlDouble:
                    result = SqlConvert.ConvertToSqlDouble(obj) * SqlConvert.ConvertToSqlDouble(obj2);
                    break;
                default:
                    flag3 = true;
                    break;
                }
                break;
            case 18:
                switch (storageType3)
                {
                case StorageType.Byte:
                    result = Convert.ToByte(Convert.ToByte(obj, base.FormatProvider) / Convert.ToByte(obj2, base.FormatProvider), base.FormatProvider);
                    break;
                case StorageType.SqlByte:
                    result = SqlConvert.ConvertToSqlByte(obj) / SqlConvert.ConvertToSqlByte(obj2);
                    break;
                case StorageType.SByte:
                    result = Convert.ToSByte(Convert.ToSByte(obj, base.FormatProvider) / Convert.ToSByte(obj2, base.FormatProvider), base.FormatProvider);
                    break;
                case StorageType.Int16:
                    result = Convert.ToInt16(Convert.ToInt16(obj, base.FormatProvider) / Convert.ToInt16(obj2, base.FormatProvider), base.FormatProvider);
                    break;
                case StorageType.SqlInt16:
                    result = SqlConvert.ConvertToSqlInt16(obj) / SqlConvert.ConvertToSqlInt16(obj2);
                    break;
                case StorageType.UInt16:
                    result = Convert.ToUInt16(Convert.ToUInt16(obj, base.FormatProvider) / Convert.ToUInt16(obj2, base.FormatProvider), base.FormatProvider);
                    break;
                case StorageType.Int32:
                    result = Convert.ToInt32(obj, base.FormatProvider) / Convert.ToInt32(obj2, base.FormatProvider);
                    break;
                case StorageType.SqlInt32:
                    result = SqlConvert.ConvertToSqlInt32(obj) / SqlConvert.ConvertToSqlInt32(obj2);
                    break;
                case StorageType.UInt32:
                    result = Convert.ToUInt32(obj, base.FormatProvider) / Convert.ToUInt32(obj2, base.FormatProvider);
                    break;
                case StorageType.UInt64:
                    result = Convert.ToUInt64(obj, base.FormatProvider) / Convert.ToUInt64(obj2, base.FormatProvider);
                    break;
                case StorageType.Int64:
                    result = Convert.ToInt64(obj, base.FormatProvider) / Convert.ToInt64(obj2, base.FormatProvider);
                    break;
                case StorageType.SqlInt64:
                    result = SqlConvert.ConvertToSqlInt64(obj) / SqlConvert.ConvertToSqlInt64(obj2);
                    break;
                case StorageType.Decimal:
                    result = Convert.ToDecimal(obj, base.FormatProvider) / Convert.ToDecimal(obj2, base.FormatProvider);
                    break;
                case StorageType.SqlDecimal:
                    result = SqlConvert.ConvertToSqlDecimal(obj) / SqlConvert.ConvertToSqlDecimal(obj2);
                    break;
                case StorageType.Single:
                    result = Convert.ToSingle(obj, base.FormatProvider) / Convert.ToSingle(obj2, base.FormatProvider);
                    break;
                case StorageType.SqlSingle:
                    result = SqlConvert.ConvertToSqlSingle(obj) / SqlConvert.ConvertToSqlSingle(obj2);
                    break;
                case StorageType.SqlMoney:
                    result = SqlConvert.ConvertToSqlMoney(obj) / SqlConvert.ConvertToSqlMoney(obj2);
                    break;
                case StorageType.Double:
                {
                    double num = Convert.ToDouble(obj2, base.FormatProvider);
                    result = Convert.ToDouble(obj, base.FormatProvider) / num;
                    break;
                }
                case StorageType.SqlDouble:
                    result = SqlConvert.ConvertToSqlDouble(obj) / SqlConvert.ConvertToSqlDouble(obj2);
                    break;
                default:
                    flag3 = true;
                    break;
                }
                break;
            case 7:
                if (obj == DBNull.Value || (left.IsSqlColumn && DataStorage.IsObjectSqlNull(obj)) || obj2 == DBNull.Value || (right.IsSqlColumn && DataStorage.IsObjectSqlNull(obj2)))
                {
                    return DBNull.Value;
                }
                return BinaryCompare(obj, obj2, storageType3, 7) == 0;
            case 8:
                if (obj == DBNull.Value || (left.IsSqlColumn && DataStorage.IsObjectSqlNull(obj)) || obj2 == DBNull.Value || (right.IsSqlColumn && DataStorage.IsObjectSqlNull(obj2)))
                {
                    return DBNull.Value;
                }
                return 0 < BinaryCompare(obj, obj2, storageType3, op);
            case 9:
                if (obj == DBNull.Value || (left.IsSqlColumn && DataStorage.IsObjectSqlNull(obj)) || obj2 == DBNull.Value || (right.IsSqlColumn && DataStorage.IsObjectSqlNull(obj2)))
                {
                    return DBNull.Value;
                }
                return 0 > BinaryCompare(obj, obj2, storageType3, op);
            case 10:
                if (obj == DBNull.Value || (left.IsSqlColumn && DataStorage.IsObjectSqlNull(obj)) || obj2 == DBNull.Value || (right.IsSqlColumn && DataStorage.IsObjectSqlNull(obj2)))
                {
                    return DBNull.Value;
                }
                return 0 <= BinaryCompare(obj, obj2, storageType3, op);
            case 11:
                if (obj == DBNull.Value || (left.IsSqlColumn && DataStorage.IsObjectSqlNull(obj)) || obj2 == DBNull.Value || (right.IsSqlColumn && DataStorage.IsObjectSqlNull(obj2)))
                {
                    return DBNull.Value;
                }
                return 0 >= BinaryCompare(obj, obj2, storageType3, op);
            case 12:
                if (obj == DBNull.Value || (left.IsSqlColumn && DataStorage.IsObjectSqlNull(obj)) || obj2 == DBNull.Value || (right.IsSqlColumn && DataStorage.IsObjectSqlNull(obj2)))
                {
                    return DBNull.Value;
                }
                return BinaryCompare(obj, obj2, storageType3, op) != 0;
            case 13:
                obj = Eval(left, row, version, recordNos);
                if (obj == DBNull.Value || (left.IsSqlColumn && DataStorage.IsObjectSqlNull(obj)))
                {
                    return true;
                }
                return false;
            case 39:
                obj = Eval(left, row, version, recordNos);
                if (obj == DBNull.Value || (left.IsSqlColumn && DataStorage.IsObjectSqlNull(obj)))
                {
                    return false;
                }
                return true;
            case 26:
                obj = Eval(left, row, version, recordNos);
                if (obj == DBNull.Value || (left.IsSqlColumn && DataStorage.IsObjectSqlNull(obj)))
                {
                    return DBNull.Value;
                }
                if (!(obj is bool) && !(obj is SqlBoolean))
                {
                    obj2 = Eval(right, row, version, recordNos);
                    flag3 = true;
                    break;
                }
                if (obj is bool)
                {
                    if (!(bool)obj)
                    {
                        result = false;
                        break;
                    }
                }
                else if (((SqlBoolean)obj).IsFalse)
                {
                    result = false;
                    break;
                }
                obj2 = Eval(right, row, version, recordNos);
                if (obj2 == DBNull.Value || (right.IsSqlColumn && DataStorage.IsObjectSqlNull(obj2)))
                {
                    return DBNull.Value;
                }
                if (obj2 is bool || obj2 is SqlBoolean)
                {
                    result = ((!(obj2 is bool)) ? ((object)((SqlBoolean)obj2).IsTrue) : ((object)(bool)obj2));
                }
                else
                {
                    flag3 = true;
                }
                break;
            case 27:
                obj = Eval(left, row, version, recordNos);
                if (obj != DBNull.Value && !DataStorage.IsObjectSqlNull(obj))
                {
                    if (!(obj is bool) && !(obj is SqlBoolean))
                    {
                        obj2 = Eval(right, row, version, recordNos);
                        flag3 = true;
                        break;
                    }
                    if ((bool)obj)
                    {
                        result = true;
                        break;
                    }
                }
                obj2 = Eval(right, row, version, recordNos);
                if (obj2 == DBNull.Value || DataStorage.IsObjectSqlNull(obj2))
                {
                    return obj;
                }
                if (obj == DBNull.Value || DataStorage.IsObjectSqlNull(obj))
                {
                    return obj2;
                }
                if (!(obj2 is bool) && !(obj2 is SqlBoolean))
                {
                    flag3 = true;
                }
                else
                {
                    result = ((obj2 is bool) ? ((bool)obj2) : ((SqlBoolean)obj2).IsTrue);
                }
                break;
            case 20:
                if (ExpressionNode.IsIntegerSql(storageType3))
                {
                    if (storageType3 == StorageType.UInt64)
                    {
                        result = Convert.ToUInt64(obj, base.FormatProvider) % Convert.ToUInt64(obj2, base.FormatProvider);
                    }
                    else if (DataStorage.IsSqlType(storageType3))
                    {
                        SqlInt64 sqlInt = SqlConvert.ConvertToSqlInt64(obj) % SqlConvert.ConvertToSqlInt64(obj2);
                        result = storageType3 switch
{
                            StorageType.SqlInt32 => sqlInt.ToSqlInt32(),
                            StorageType.SqlInt16 => sqlInt.ToSqlInt16(),
                            StorageType.SqlByte => sqlInt.ToSqlByte(),
                            _ => sqlInt,
                        };
                    }
                    else
                    {
                        result = Convert.ToInt64(obj, base.FormatProvider) % Convert.ToInt64(obj2, base.FormatProvider);
                        result = Convert.ChangeType(result, DataStorage.GetTypeStorage(storageType3), base.FormatProvider);
                    }
                }
                else
                {
                    flag3 = true;
                }
                break;
            case 5:
            {
                if (!(right is FunctionNode))
                {
                    throw ExprException.InWithoutParentheses();
                }
                obj = Eval(left, row, version, recordNos);
                if (obj == DBNull.Value || (left.IsSqlColumn && DataStorage.IsObjectSqlNull(obj)))
                {
                    return DBNull.Value;
                }
                result = false;
                FunctionNode functionNode = (FunctionNode)right;
                for (int i = 0; i < functionNode._argumentCount; i++)
                {
                    obj2 = functionNode._arguments[i].Eval();
                    if (obj2 != DBNull.Value && (!right.IsSqlColumn || !DataStorage.IsObjectSqlNull(obj2)))
                    {
                        storageType3 = DataStorage.GetStorageType(obj.GetType());
                        if (BinaryCompare(obj, obj2, storageType3, 7) == 0)
{
                            result = true;
                            break;
                        }
                    }
                }
                break;
            }
            default:
                throw ExprException.UnsupportedOperator(op);
            }
        }
        catch (OverflowException)
        {
            throw ExprException.Overflow(DataStorage.GetTypeStorage(storageType3));
        }
        if (flag3)
        {
            SetTypeMismatchError(op, obj.GetType(), obj2.GetType());
        }
        return result;
    }
References System.Data.BinaryNode.BinaryCompare(), System.Convert.ChangeType(), System.Data.Common.SqlConvert.ConvertToSqlByte(), System.Data.Common.SqlConvert.ConvertToSqlDateTime(), System.Data.Common.SqlConvert.ConvertToSqlDecimal(), System.Data.Common.SqlConvert.ConvertToSqlDouble(), System.Data.Common.SqlConvert.ConvertToSqlInt16(), System.Data.Common.SqlConvert.ConvertToSqlInt32(), System.Data.Common.SqlConvert.ConvertToSqlInt64(), System.Data.Common.SqlConvert.ConvertToSqlMoney(), System.Data.Common.SqlConvert.ConvertToSqlSingle(), System.Data.Common.SqlConvert.ConvertToSqlString(), System.Data.BinaryNode.DateTime, System.Data.BinaryNode.Eval(), System.Data.Common.DataStorage.GetStorageType(), System.Type.GetType(), System.Data.Common.DataStorage.GetTypeStorage(), System.Data.ExprException.InWithoutParentheses(), System.Data.ExpressionNode.IsIntegerSql(), System.Data.Common.DataStorage.IsObjectSqlNull(), System.Data.ExpressionNode.IsSqlColumn, System.Data.Common.DataStorage.IsSqlType(), System.obj, System.Data.ExprException.Overflow(), System.Data.BinaryNode.ResultSqlType(), System.Data.BinaryNode.ResultType(), System.Data.BinaryNode.SetTypeMismatchError(), System.Data.BinaryNode.SqlBoolean, System.Data.BinaryNode.TimeSpan, System.Convert.ToByte(), System.Convert.ToDecimal(), System.Convert.ToDouble(), System.Convert.ToInt16(), System.Convert.ToInt32(), System.Convert.ToInt64(), System.Convert.ToSByte(), System.Convert.ToSingle(), System.Convert.ToString(), System.Convert.ToUInt16(), System.Convert.ToUInt32(), System.Convert.ToUInt64(), System.type, System.Data.ExprException.UnsupportedOperator(), and System.DBNull.Value.
Referenced by System.Data.BinaryNode.Eval(), and System.Data.BinaryNode.Eval().