Terraria: System.Xml.Xsl.Runtime.XmlNavigatorStack.Pop
Pop()
XPathNavigator System.Xml.Xsl.Runtime.XmlNavigatorStack.Pop () inline
Definition at line 28 of file XmlNavigatorStack.cs.
    {
        return _stkNav[--_sp];
    }
References System.Xml.Xsl.Runtime.XmlNavigatorStack._sp, and System.Xml.Xsl.Runtime.XmlNavigatorStack._stkNav.
Referenced by System.Xml.Xsl.Runtime.AncestorDocOrderIterator.MoveNext(), System.Xml.Xsl.Runtime.NamespaceIterator.MoveNext(), System.Xml.Xsl.Runtime.PrecedingIterator.MoveNext(), System.Xml.Xsl.Runtime.XPathPrecedingDocOrderIterator.MoveNext(), System.Xml.Xsl.Runtime.XPathPrecedingIterator.MoveNext(), System.Xml.Xsl.Runtime.XPathPrecedingMergeIterator.MoveNext(), System.Xml.Xsl.Runtime.ContentMergeIterator.MoveNext(), System.Xml.Xsl.Runtime.XPathPrecedingDocOrderIterator.PushAncestors(), and System.Xml.Xsl.Runtime.XPathPrecedingMergeIterator.PushAncestors().