Terraria: System.Xml.Xsl.Runtime.XmlNavigatorStack.Push
Push()
void System.Xml.Xsl.Runtime.XmlNavigatorStack.Push (XPathNavigator nav) inline
Definition at line 13 of file XmlNavigatorStack.cs.
    {
        if (_stkNav == null)
        {
            _stkNav = new XPathNavigator[8];
        }
        else if (_sp >= _stkNav.Length)
        {
            XPathNavigator[] stkNav = _stkNav;
            _stkNav = new XPathNavigator[2 * _sp];
            Array.Copy(stkNav, _stkNav, _sp);
        }
        _stkNav[_sp++] = nav;
    }
References System.Xml.Xsl.Runtime.XmlNavigatorStack._sp, System.Xml.Xsl.Runtime.XmlNavigatorStack._stkNav, System.Array.Copy(), and System.Xml.Dictionary.
Referenced by System.Xml.Xsl.Runtime.NamespaceIterator.Create(), System.Xml.Xsl.Runtime.PrecedingIterator.Create(), System.Xml.Xsl.Runtime.XPathPrecedingIterator.Create(), System.Xml.Xsl.Runtime.AncestorDocOrderIterator.Create(), System.Xml.Xsl.Runtime.ContentMergeIterator.DocOrderMerge(), System.Xml.Xsl.Runtime.XPathPrecedingDocOrderIterator.PushAncestors(), and System.Xml.Xsl.Runtime.XPathPrecedingMergeIterator.PushAncestors().