Terraria: System.Numerics.Vector3.Cross
Cross()
static Vector3 System.Numerics.Vector3.Cross (Vector3 vector1, Vector3 vector2) inline static
Definition at line 162 of file Vector3.cs.
    {
        return new Vector3(vector1.Y * vector2.Z - vector1.Z * vector2.Y, vector1.Z * vector2.X - vector1.X * vector2.Z, vector1.X * vector2.Y - vector1.Y * vector2.X);
    }
References System.Numerics.Vector3.Vector3(), System.Numerics.Vector3.X, System.Numerics.Vector3.Y, and System.Numerics.Vector3.Z.
Referenced by System.Numerics.Matrix4x4.CreateBillboard(), System.Numerics.Matrix4x4.CreateConstrainedBillboard(), System.Numerics.Plane.CreateFromVertices(), System.Numerics.Matrix4x4.CreateLookAt(), System.Numerics.Matrix4x4.CreateWorld(), and System.Numerics.Matrix4x4.Decompose().