Terraria: System.Numerics.Vector3.Vector3
Vector3() [1/4]
System.Numerics.Vector3.Vector3 (float value) inline
Definition at line 44 of file Vector3.cs.
        : this(value, value, value)
    {
    }
Referenced by System.Numerics.Vector3.Abs(), System.Numerics.Vector3.Cross(), System.Numerics.Vector3.Max(), System.Numerics.Vector3.Min(), System.Numerics.Vector3.operator*(), System.Numerics.Vector3.operator*(), System.Numerics.Vector3.operator+(), System.Numerics.Vector3.operator-(), System.Numerics.Vector3.operator/(), System.Numerics.Vector3.operator/(), System.Numerics.Vector3.SquareRoot(), System.Numerics.Vector3.Transform(), System.Numerics.Vector3.Transform(), and System.Numerics.Vector3.TransformNormal().