Terraria: System.Numerics.Vector3.ToString
ToString() [3/3]
readonly string System.Numerics.Vector3.ToString (string? format, IFormatProvider? formatProvider) inline
Implements System.IFormattable.
Definition at line 390 of file Vector3.cs.
    {
        StringBuilder stringBuilder = new StringBuilder();
        string numberGroupSeparator = NumberFormatInfo.GetInstance(formatProvider).NumberGroupSeparator;
        stringBuilder.Append('<');
        stringBuilder.Append(X.ToString(format, formatProvider));
        stringBuilder.Append(numberGroupSeparator);
        stringBuilder.Append(' ');
        stringBuilder.Append(Y.ToString(format, formatProvider));
        stringBuilder.Append(numberGroupSeparator);
        stringBuilder.Append(' ');
        stringBuilder.Append(Z.ToString(format, formatProvider));
        stringBuilder.Append('>');
        return stringBuilder.ToString();
    }
References System.Text.StringBuilder.Append(), System.format, System.Globalization.NumberFormatInfo.GetInstance(), System.Text.StringBuilder.ToString(), System.Numerics.Vector3.X, System.Numerics.Vector3.Y, and System.Numerics.Vector3.Z.