Terraria: System.Numerics.Vector3.Dot
Dot()
static float System.Numerics.Vector3.Dot (Vector3 vector1, Vector3 vector2) inline static
Definition at line 195 of file Vector3.cs.
    {
        return vector1.X * vector2.X + vector1.Y * vector2.Y + vector1.Z * vector2.Z;
    }
References System.Numerics.Vector3.Z.
Referenced by System.Numerics.Matrix4x4.CreateConstrainedBillboard(), System.Numerics.Plane.CreateFromVertices(), System.Numerics.Matrix4x4.CreateLookAt(), System.Numerics.Vector3.DistanceSquared(), System.Numerics.Plane.DotCoordinate(), System.Numerics.Plane.DotNormal(), System.Numerics.Vector3.LengthSquared(), and System.Numerics.Vector3.Reflect().