Terraria: CreativePowers.SpawnRateSliderPerPlayerPower.ProvideSlider
ProvideSlider()
override UIElement CreativePowers.SpawnRateSliderPerPlayerPower.ProvideSlider () inline virtual
Implements CreativePowers.APerPlayerSliderPower.
         {
             UIVerticalSlider uIVerticalSlider = CreativePowersHelper.CreateSlider(base.GetSliderValue, base.SetValueKeyboard, base.SetValueGamepad);
             uIVerticalSlider.OnUpdate += UpdateSliderAndShowMultiplierMouseOver;
             UIPanel uIPanel = new UIPanel();
             uIPanel.Width = new StyleDimension(77f, 0f);
             uIPanel.Height = new StyleDimension(180f, 0f);
             uIPanel.HAlign = 0f;
             uIPanel.VAlign = 0.5f;
             uIPanel.Append(uIVerticalSlider);
             uIPanel.OnUpdate += CreativePowersHelper.UpdateUseMouseInterface;
             UIText uIText = new UIText("x10")
             {
                 HAlign = 1f,
                 VAlign = 0f
             };
             uIText.OnMouseOut += Button_OnMouseOut;
             uIText.OnMouseOver += Button_OnMouseOver;
             uIText.OnLeftClick += topText_OnClick;
             uIPanel.Append(uIText);
             UIText uIText2 = new UIText("x1")
             {
                 HAlign = 1f,
                 VAlign = 0.5f
             };
             uIText2.OnMouseOut += Button_OnMouseOut;
             uIText2.OnMouseOver += Button_OnMouseOver;
             uIText2.OnLeftClick += middleText_OnClick;
             uIPanel.Append(uIText2);
             UIText uIText3 = new UIText("x0")
             {
                 HAlign = 1f,
                 VAlign = 1f
             };
             uIText3.OnMouseOut += Button_OnMouseOut;
             uIText3.OnMouseOver += Button_OnMouseOver;
             uIText3.OnLeftClick += bottomText_OnClick;
             uIPanel.Append(uIText3);
             return uIPanel;
         }
References UIElement.Append(), CreativePowers.SpawnRateSliderPerPlayerPower.bottomText_OnClick(), CreativePowers.SpawnRateSliderPerPlayerPower.Button_OnMouseOut(), CreativePowers.SpawnRateSliderPerPlayerPower.Button_OnMouseOver(), CreativePowersHelper.CreateSlider(), UIElement.HAlign, UIElement.Height, CreativePowers.SpawnRateSliderPerPlayerPower.middleText_OnClick(), UIElement.OnLeftClick, UIElement.OnMouseOut, UIElement.OnMouseOver, UIElement.OnUpdate, CreativePowers.SpawnRateSliderPerPlayerPower.topText_OnClick(), CreativePowers.SpawnRateSliderPerPlayerPower.UpdateSliderAndShowMultiplierMouseOver(), CreativePowersHelper.UpdateUseMouseInterface(), UIElement.VAlign, and UIElement.Width.