Terraria: Lang.GetInvasionWaveText
GetInvasionWaveText()
static NetworkText Lang.GetInvasionWaveText (int wave, params short[] npcIds) inline static
     {
         NetworkText[] array = new NetworkText[npcIds.Length + 1];
         for (int i = 0; i < npcIds.Length; i++)
         {
             array[i + 1] = NetworkText.FromKey(GetNPCName(npcIds[i]).Key);
         }
         switch (wave)
         {
         case -1:
             array[0] = NetworkText.FromKey("Game.FinalWave");
             break;
         case 1:
             array[0] = NetworkText.FromKey("Game.FirstWave");
             break;
         default:
             array[0] = NetworkText.FromKey("Game.Wave", wave);
             break;
         }
         string key = "Game.InvasionWave_Type" + npcIds.Length;
         object[] substitutions = array;
         return NetworkText.FromKey(key, substitutions);
     }
References NetworkText.FromKey(), and GetNPCName().
Referenced by NPC.CheckProgressFrostMoon(), NPC.CheckProgressPumpkinMoon(), Main.startPumpkinMoon(), Main.startSnowMoon(), and DD2Event.UpdateTime().