Terraria: System.Runtime.CompilerServices.RuntimeHelpers.GetMethodTable
GetMethodTable()
static unsafe MethodTable * System.Runtime.CompilerServices.RuntimeHelpers.GetMethodTable (object obj) inline static package
Definition at line 195 of file RuntimeHelpers.cs.
    {
        return (MethodTable*)(void*)Unsafe.Add(ref Unsafe.As<byte, IntPtr>(ref obj.GetRawData()), -1);
    }
References System.Runtime.Serialization.Dictionary, and System.obj.
Referenced by System.Runtime.CompilerServices.CastHelpers.ChkCast_Helper(), System.Runtime.CompilerServices.CastHelpers.ChkCastAny(), System.Runtime.CompilerServices.CastHelpers.ChkCastClass(), System.Runtime.CompilerServices.CastHelpers.ChkCastClassSpecial(), System.Runtime.CompilerServices.CastHelpers.ChkCastInterface(), System.Array.Clear(), System.Array.Clear(), System.Array.Copy(), System.Array.Copy(), System.Array.Copy(), System.Runtime.InteropServices.MemoryMarshal.GetArrayDataReference(), System.Runtime.CompilerServices.RuntimeHelpers.GetElementSize(), System.Array.GetFlattenedIndex(), System.Runtime.CompilerServices.RuntimeHelpers.GetMultiDimensionalArrayRank(), System.Runtime.CompilerServices.RuntimeHelpers.GetRawObjectDataSize(), System.Runtime.CompilerServices.CastHelpers.IsInstance_Helper(), System.Runtime.CompilerServices.CastHelpers.IsInstanceOfAny(), System.Runtime.CompilerServices.CastHelpers.IsInstanceOfClass(), System.Runtime.CompilerServices.CastHelpers.IsInstanceOfInterface(), System.Array.IsValueOfElementType(), System.Runtime.CompilerServices.CastHelpers.LdelemaRef(), System.Object.MemberwiseClone(), System.Runtime.CompilerServices.RuntimeHelpers.ObjectHasComponentSize(), System.Runtime.CompilerServices.CastHelpers.StelemRef(), System.Runtime.CompilerServices.CastHelpers.StelemRef_Helper(), and System.Runtime.CompilerServices.CastHelpers.Unbox().