Terraria: System.Runtime.CompilerServices.RuntimeHelpers.GetHashCode
GetHashCode()
static int System.Runtime.CompilerServices.RuntimeHelpers.GetHashCode (object? o)
Referenced by System.Runtime.Serialization.ObjectToIdCache.ComputeStartPosition(), System.Runtime.CompilerServices.ConditionalWeakTable< TKey, TValue >.Container.CreateEntryNoResize(), System.Runtime.Serialization.ObjectIDGenerator.FindElement(), System.Runtime.CompilerServices.ConditionalWeakTable< TKey, TValue >.Container.FindEntry(), System.Dynamic.BindingRestrictions.InstanceRestriction.GetHashCode(), System.Linq.Expressions.Compiler.BoundConstants.TypedConstant.GetHashCode(), System.Delegate.GetHashCode(), System.Memory< T >.GetHashCode(), System.Object.GetHashCode(), System.ReadOnlyMemory< T >.GetHashCode(), System.RuntimeType.GetHashCode(), System.Text.Json.Serialization.ReferenceEqualsWrapper.GetHashCode(), and System.Collections.Generic.ReferenceEqualityComparer.GetHashCode().