Terraria: System.Runtime.CompilerServices.RuntimeHelpers.GetUninitializedObject
GetUninitializedObject() [1/2]
static object System.Runtime.CompilerServices.RuntimeHelpers.GetUninitializedObject ([DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicConstructors | DynamicallyAccessedMemberTypes.NonPublicConstructors)] Type type) inline static
Definition at line 104 of file RuntimeHelpers.cs.
    {
        RuntimeType type2 = type as RuntimeType;
        if ((object)type2 == null)
        {
            if ((object)type == null)
            {
                throw new ArgumentNullException("type", SR.ArgumentNull_Type);
            }
            throw new SerializationException(SR.Format(SR.Serialization_InvalidType, type));
        }
        object o = null;
        GetUninitializedObject(new QCallTypeHandle(ref type2), ObjectHandleOnStack.Create(ref o));
        return o;
    }
References System.SR.ArgumentNull_Type, System.Runtime.Serialization.Dictionary, System.SR.Format(), System.Runtime.CompilerServices.RuntimeHelpers.GetUninitializedObject(), System.SR.Serialization_InvalidType, and System.type.
Referenced by System.Runtime.Serialization.FormatterServices.GetSafeUninitializedObject(), System.Runtime.CompilerServices.RuntimeHelpers.GetUninitializedObject(), System.Runtime.Serialization.FormatterServices.GetUninitializedObject(), System.Runtime.Serialization.SurrogateDataContract.GetUninitializedObject(), System.Linq.Expressions.Interpreter.DefaultValueInstruction.Run(), System.Linq.Expressions.Interpreter.InitializeLocalInstruction.MutableValue.Run(), System.Linq.Expressions.Interpreter.InitializeLocalInstruction.MutableBox.Run(), System.Linq.Expressions.Interpreter.NullableMethodCallInstruction.GetValueOrDefault.Run(), System.Runtime.Serialization.XmlFormatReaderGenerator.UnsafeGetUninitializedObject(), and System.Diagnostics.Tracing.NullableTypeInfo.WriteData().