Terraria: NPCPreferenceTrait.ModifyShopPrice
ModifyShopPrice()
void NPCPreferenceTrait.ModifyShopPrice (HelperInfo info, ShopHelper shopHelperInstance) inline
Implements IShopPersonalityTrait.
     {
         if (info.nearbyNPCsByType[NpcId])
         {
             switch (Level)
             {
             case AffectionLevel.Love:
                 shopHelperInstance.LoveNPC(NpcId);
                 break;
             case AffectionLevel.Like:
                 shopHelperInstance.LikeNPC(NpcId);
                 break;
             case AffectionLevel.Dislike:
                 shopHelperInstance.DislikeNPC(NpcId);
                 break;
             case AffectionLevel.Hate:
                 shopHelperInstance.HateNPC(NpcId);
                 break;
             }
         }
     }
References ShopHelper.DislikeNPC(), ShopHelper.HateNPC(), Level, ShopHelper.LikeNPC(), ShopHelper.LoveNPC(), HelperInfo.nearbyNPCsByType, and NpcId.