Terraria: System.Xml.Linq.XDocument.ValidateNode
ValidateNode()
override void System.Xml.Linq.XDocument.ValidateNode (XNode node, XNode previous) inline package virtual
Reimplemented from System.Xml.Linq.XContainer.
Definition at line 423 of file XDocument.cs.
    {
        switch (node.NodeType)
        {
        case XmlNodeType.Text:
            ValidateString(((XText)node).Value);
            break;
        case XmlNodeType.Element:
            ValidateDocument(previous, XmlNodeType.DocumentType, XmlNodeType.None);
            break;
        case XmlNodeType.DocumentType:
            ValidateDocument(previous, XmlNodeType.None, XmlNodeType.Element);
            break;
        case XmlNodeType.CDATA:
            throw new ArgumentException(System.SR.Format(System.SR.Argument_AddNode, XmlNodeType.CDATA));
        case XmlNodeType.Document:
            throw new ArgumentException(System.SR.Format(System.SR.Argument_AddNode, XmlNodeType.Document));
        }
    }
References System.SR.Argument_AddNode, System.Xml.ArgumentException, System.Xml.Dictionary, System.SR.Format(), System.Xml.Linq.XDocument.ValidateDocument(), System.Xml.Linq.XDocument.ValidateString(), and System.Xml.Linq.Value.