Terraria: System.Xml.Linq.XDocument.Load
Load() [3/8]
static XDocument System.Xml.Linq.XDocument.Load (string uri) inline static
Definition at line 56 of file XDocument.cs.
    {
        return Load(uri, LoadOptions.None);
    }
References System.Xml.Linq.XDocument.Load().
Referenced by System.Xml.Linq.XDocument.Load(), System.Xml.Linq.XDocument.Load(), System.Xml.Linq.XDocument.Load(), System.Xml.Linq.XDocument.Load(), System.Xml.Linq.XDocument.Load(), System.Xml.Linq.XDocument.Load(), System.Xml.Linq.XDocument.Load(), and System.Xml.Linq.XDocument.Parse().