Terraria: System.Xml.Linq.XDocument.Save
Save() [4/7]
void System.Xml.Linq.XDocument.Save (string fileName, SaveOptions options) inline
Definition at line 304 of file XDocument.cs.
    {
        XmlWriterSettings xmlWriterSettings = XNode.GetXmlWriterSettings(options);
        if (_declaration != null && !string.IsNullOrEmpty(_declaration.Encoding))
        {
            try
            {
                xmlWriterSettings.Encoding = Encoding.GetEncoding(_declaration.Encoding);
            }
            catch (ArgumentException)
            {
            }
        }
        using XmlWriter writer = XmlWriter.Create(fileName, xmlWriterSettings);
        Save(writer);
    }
References System.Xml.Linq.XDocument._declaration, System.Xml.XmlWriter.Create(), System.Xml.Dictionary, System.Xml.Linq.XDeclaration.Encoding, System.Text.Encoding.GetEncoding(), System.Xml.Linq.XNode.GetXmlWriterSettings(), System.options, System.Xml.Linq.XDocument.Save(), and System.writer.