Terraria: System.Xml.Linq.XDocument.LoadAsyncInternal
LoadAsyncInternal()
static async Task< XDocument > System.Xml.Linq.XDocument.LoadAsyncInternal (XmlReader reader, LoadOptions options, CancellationToken cancellationToken) inline static private
Definition at line 149 of file XDocument.cs.
    {
        if (reader.ReadState == ReadState.Initial)
        {
            await reader.ReadAsync().ConfigureAwait(continueOnCapturedContext: false);
        }
        XDocument d = InitLoad(reader, options);
        await d.ReadContentFromAsync(reader, options, cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
        if (!reader.EOF)
        {
            throw new InvalidOperationException(System.SR.InvalidOperation_ExpectedEndOfFile);
        }
        if (d.Root == null)
        {
            throw new InvalidOperationException(System.SR.InvalidOperation_MissingRoot);
        }
        return d;
    }
References System.cancellationToken, System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.Xml.Dictionary, System.Xml.XmlReader.EOF, System.Xml.Linq.XDocument.InitLoad(), System.SR.InvalidOperation_ExpectedEndOfFile, System.SR.InvalidOperation_MissingRoot, System.options, System.Xml.XmlReader.ReadAsync(), and System.Xml.XmlReader.ReadState.
Referenced by System.Xml.Linq.XDocument.LoadAsync().