Terraria: Terraria.Utils.CoinsSplit
CoinsSplit()
static int[] Terraria.Utils.CoinsSplit (long count) inline static
Definition at line 665 of file Utils.cs.
    {
        int[] array = new int[4];
        long num = 0L;
        long num2 = 1000000L;
        for (int num3 = 3; num3 >= 0; num3--)
        {
            array[num3] = (int)((count - num) / num2);
            num += array[num3] * num2;
            num2 /= 100;
        }
        return array;
    }
References System.array, System.Linq.count, and System.L.
Referenced by Terraria.UI.ItemSlot.DrawSavings(), Terraria.Main.GUIChatDrawInner(), Terraria.UI.ItemSorting.SortCoins(), Terraria.GameContent.CoinLossRevengeSystem.RevengeMarker.UseMouseOver(), and Terraria.Chest.VisualizeChestTransfer_CoinsBatch().