Terraria: Terraria.Utils.OpenFolder
OpenFolder()
static void Terraria.Utils.OpenFolder (string folderPath) inline static
Definition at line 772 of file Utils.cs.
    {
        if (TryCreatingDirectory(folderPath))
        {
            if (Platform.IsLinux)
            {
                Process.Start(new ProcessStartInfo(folderPath)
                {
                    FileName = "open-folder",
                    Arguments = folderPath,
                    UseShellExecute = true,
                    CreateNoWindow = true
                });
            }
            else
            {
                Process.Start(folderPath);
            }
        }
    }
References System.IO.FileName, ReLogic.OS.Platform.IsLinux, System.Diagnostics.Process.Start(), and Terraria.Utils.TryCreatingDirectory().
Referenced by Terraria.GameContent.UI.States.UIResourcePackSelectionMenu.OpenFoldersClick(), and Terraria.Graphics.Capture.CaptureInterface.UpdateButtons().