Terraria: Terraria.Utils.FormatWith
FormatWith()
static string Terraria.Utils.FormatWith (string original, object obj) inline static
Definition at line 739 of file Utils.cs.
    {
        PropertyDescriptorCollection properties = TypeDescriptor.GetProperties(obj);
        return _substitutionRegex.Replace(original, delegate(Match match)
        {
            if (match.Groups[1].Length != 0)
            {
                return "";
            }
            string name = match.Groups[2].ToString();
            PropertyDescriptor propertyDescriptor = properties.Find(name, ignoreCase: false);
            return (propertyDescriptor == null) ? "" : (propertyDescriptor.GetValue(obj) ?? "").ToString();
        });
    }
References Terraria.Utils._substitutionRegex, System.ComponentModel.PropertyDescriptorCollection.Find(), System.ComponentModel.TypeDescriptor.GetProperties(), System.match, System.Text.RegularExpressions.name, System.obj, and System.ToString.
Referenced by Terraria.UI.InGamePopups.PlayerWantsToJoinGamePopup.DrawInGame(), and Terraria.UI.InGamePopups.PlayerWantsToJoinGamePopup.DrawInNotificationsArea().