Terraria: Terraria.Utils.RandomInt
RandomInt() [1/2]
static int Terraria.Utils.RandomInt (ref ulong seed, int max) inline static
    {
        if ((max & -max) == max)
        {
            return (int)((long)max * (long)RandomNext(ref seed, 31) >> 31);
        }
        int num;
        int num2;
        do
        {
            num = RandomNext(ref seed, 31);
            num2 = num % max;
        }
        while (num - num2 + (max - 1) < 0);
        return num2;
    }
References Terraria.Utils.RandomNext().
Referenced by Terraria.Graphics.Renderers.FlameParticle.Draw(), Terraria.DataStructures.PlayerDrawLayers.DrawCompositeArmorPiece(), Terraria.GameContent.Drawing.TileDrawing.DrawMultiTileVinesInWind(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_21_Head(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_28_ArmOverItem(), Terraria.Main.DrawProjDirect(), Terraria.GameContent.Drawing.TileDrawing.DrawSingleTile_Flames(), and Terraria.Utils.RandomInt().