Terraria: Terraria.Utils.PlotLine
PlotLine() [3/3]
static bool Terraria.Utils.PlotLine (Point16 p0, Point16 p1, TileActionAttempt plot, bool jump = true) inline static
Definition at line 1566 of file Utils.cs.
    {
        return PlotLine(p0.X, p0.Y, p1.X, p1.Y, plot, jump);
    }
References Terraria.Utils.PlotLine(), Terraria.DataStructures.Point16.X, and Terraria.DataStructures.Point16.Y.
Referenced by Terraria.GameContent.PortalHelper.FindCollision(), Terraria.GameContent.Generation.ShapeBranch.PerformSegment(), Terraria.Utils.PlotLine(), Terraria.Utils.PlotLine(), Terraria.Utils.PlotTileLine(), and Terraria.Utils.PlotTileTale().