Terraria: Terraria.Utils.PoofOfSmoke
PoofOfSmoke()
static void Terraria.Utils.PoofOfSmoke (Vector2 position) inline static
Definition at line 695 of file Utils.cs.
    {
        int num = Main.rand.Next(3, 7);
        for (int i = 0; i < num; i++)
        {
            int num2 = Gore.NewGore(position, (Main.rand.NextFloat() * ((float)Math.PI * 2f)).ToRotationVector2() * new Vector2(2f, 0.7f) * 0.7f, Main.rand.Next(11, 14));
            Main.gore[num2].scale = 0.7f;
            Main.gore[num2].velocity *= 0.5f;
        }
        for (int j = 0; j < 10; j++)
        {
            Dust obj = Main.dust[Dust.NewDust(position, 14, 14, 16, 0f, 0f, 100, default(Color), 1.5f)];
            obj.position += new Vector2(5f);
            obj.velocity = (Main.rand.NextFloat() * ((float)Math.PI * 2f)).ToRotationVector2() * new Vector2(2f, 0.7f) * 0.7f * (0.5f + 0.5f * Main.rand.NextFloat());
        }
    }
References Terraria.Main.dust, Terraria.Main.gore, System.Text.RegularExpressions.i, Terraria.Dust.NewDust(), Terraria.Gore.NewGore(), System.obj, System.Math.PI, Terraria.Main.rand, Terraria.Utils.ToRotationVector2(), and Microsoft.Xna.Framework.Graphics.Vector2.
Referenced by Terraria.NPC.CatchNPC(), Terraria.Wiring.CheckLogicGate(), Terraria.Projectile.Damage(), Terraria.MessageBuffer.GetData(), Terraria.NPC.HitEffect(), Terraria.NPC.MakeTransitionEffectsForTextureChanges(), and Terraria.NPC.TryTeleportingCaughtMysticFrog().