Terraria: Terraria.Utils.DrawLaser
DrawLaser()
static void Terraria.Utils.DrawLaser (SpriteBatch sb, Texture2D tex, Vector2 start, Vector2 end, Vector2 scale, LaserLineFraming framing) inline static
Definition at line 2010 of file Utils.cs.
    {
        Vector2 vector = start;
        Vector2 vector2 = Vector2.Normalize(end - start);
        float num = (end - start).Length();
        float rotation = vector2.ToRotation() - (float)Math.PI / 2f;
        if (vector2.HasNaNs())
        {
            return;
        }
        framing(0, vector, num, default(Rectangle), out var distanceCovered, out var frame, out var origin, out var color);
        sb.Draw(tex, vector, frame, color, rotation, frame.Size() / 2f, scale, SpriteEffects.None, 0f);
        num -= distanceCovered * scale.Y;
        vector += vector2 * ((float)frame.Height - origin.Y) * scale.Y;
        if (num > 0f)
        {
            float num2 = 0f;
            while (num2 + 1f < num)
            {
                framing(1, vector, num - num2, frame, out distanceCovered, out frame, out origin, out color);
                if (num - num2 < (float)frame.Height)
                {
                    distanceCovered *= (num - num2) / (float)frame.Height;
                    frame.Height = (int)(num - num2);
                }
                sb.Draw(tex, vector, frame, color, rotation, origin, scale, SpriteEffects.None, 0f);
                num2 += distanceCovered * scale.Y;
                vector += vector2 * distanceCovered * scale.Y;
            }
        }
        framing(2, vector, num, default(Rectangle), out distanceCovered, out frame, out origin, out color);
        sb.Draw(tex, vector, frame, color, rotation, origin, scale, SpriteEffects.None, 0f);
    }
References Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(), Microsoft.Xna.Framework.Vector2.Normalize(), System.Math.PI, System.start, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.Main.DrawProjDirect().