Terraria: Terraria.Utils.PlotTileLine
PlotTileLine() [1/2]
static bool Terraria.Utils.PlotTileLine (Vector2 start, Vector2 end, float width, TileActionAttempt plot) inline static
Definition at line 1670 of file Utils.cs.
    {
        //IL_0001: Unknown result type (might be due to invalid IL or missing references)
        //IL_0007: Unknown result type (might be due to invalid IL or missing references)
        return PlotTileLine(start.ToVector2D(), end.ToVector2D(), width, plot);
    }
References Terraria.Utils.PlotTileLine().
Referenced by Terraria.Projectile.AI_001(), Terraria.Projectile.AI_007_GrapplingHooks(), Terraria.NPC.AI_007_TownEntities(), Terraria.NPC.AI_007_TownEntities_GetWalkPrediction(), Terraria.Projectile.AI_026(), Terraria.Projectile.AI_075(), Terraria.NPC.AI_107_ImprovedWalkers(), Terraria.NPC.AI_109_DarkMage(), Terraria.Projectile.AI_136_BetsyBreath(), Terraria.Projectile.AI_137_LightningAura(), Terraria.Projectile.AI_139_ExplosiveTrapExplosion(), Terraria.Projectile.AI_144_DD2Pet(), Terraria.Player.ApplyEquipFunctional(), Terraria.Projectile.CutTiles(), Terraria.Mount.DrillSmartCursor_Blocks(), Terraria.Mount.DrillSmartCursor_Walls(), Terraria.Mount.EmitGolfCartlight(), Terraria.WorldGen.IsSafeFromRain(), Terraria.Utils.PlotTileLine(), Terraria.Mount.UpdateEffects(), and Terraria.Player.Yoraiz0rEye().