Terraria: Terraria.Utils.DrawSettings2Panel
DrawSettings2Panel()
static void Terraria.Utils.DrawSettings2Panel (SpriteBatch spriteBatch, Vector2 position, float width, Color color) inline static
Definition at line 1990 of file Utils.cs.
    {
        DrawPanel(TextureAssets.SettingsPanel.Value, 2, 0, spriteBatch, position, width, color);
    }
References Terraria.Utils.DrawPanel(), and Terraria.GameContent.TextureAssets.SettingsPanel.
Referenced by Terraria.GameContent.UI.Elements.UIKeybindingSimpleListItem.DrawSelf(), and Terraria.Main.DrawWindowsIMEPanel().