Terraria: Terraria.Utils.PlotTileTale
PlotTileTale()
static bool Terraria.Utils.PlotTileTale (Vector2D start, Vector2D end, double width, TileActionAttempt plot) inline static
Definition at line 1712 of file Utils.cs.
    {
        //IL_0007: Unknown result type (might be due to invalid IL or missing references)
        //IL_0008: Unknown result type (might be due to invalid IL or missing references)
        //IL_0025: Unknown result type (might be due to invalid IL or missing references)
        //IL_0027: Unknown result type (might be due to invalid IL or missing references)
        //IL_002c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0031: Unknown result type (might be due to invalid IL or missing references)
        //IL_0032: Unknown result type (might be due to invalid IL or missing references)
        //IL_003a: Unknown result type (might be due to invalid IL or missing references)
        //IL_003f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0041: Unknown result type (might be due to invalid IL or missing references)
        //IL_0048: Unknown result type (might be due to invalid IL or missing references)
        //IL_004e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0053: Unknown result type (might be due to invalid IL or missing references)
        //IL_005a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0069: Unknown result type (might be due to invalid IL or missing references)
        double halfWidth = width / 2.0;
        Vector2D val = end - start;
        Vector2D val2 = val / ((Vector2D)(ref val)).Length();
        Vector2D perpOffset = new Vector2D(0.0 - val2.Y, val2.X);
        Point pointStart = start.ToTileCoordinates();
        Point point = end.ToTileCoordinates();
        int length = 0;
        PlotLine(pointStart.X, pointStart.Y, point.X, point.Y, delegate
        {
            length++;
            return true;
        });
        length--;
        int curLength = 0;
        return PlotLine(pointStart.X, pointStart.Y, point.X, point.Y, delegate(int x, int y)
        {
            //IL_002d: Unknown result type (might be due to invalid IL or missing references)
            //IL_0033: Unknown result type (might be due to invalid IL or missing references)
            //IL_003e: Unknown result type (might be due to invalid IL or missing references)
            //IL_0044: Unknown result type (might be due to invalid IL or missing references)
            //IL_0049: Unknown result type (might be due to invalid IL or missing references)
            //IL_0055: Unknown result type (might be due to invalid IL or missing references)
            //IL_005b: Unknown result type (might be due to invalid IL or missing references)
            //IL_0066: Unknown result type (might be due to invalid IL or missing references)
            //IL_006c: Unknown result type (might be due to invalid IL or missing references)
            //IL_0071: Unknown result type (might be due to invalid IL or missing references)
            double num = 1.0 - (double)curLength / (double)length;
            curLength++;
            Point point2 = (start - perpOffset * halfWidth * num).ToTileCoordinates();
            Point point3 = (start + perpOffset * halfWidth * num).ToTileCoordinates();
            Point point4 = new Point(point2.X - pointStart.X, point2.Y - pointStart.Y);
            Point point5 = new Point(point3.X - pointStart.X, point3.Y - pointStart.Y);
            return PlotLine(x + point4.X, y + point4.Y, x + point5.X, y + point5.Y, plot, jump: false);
        });
    }
References System.length, Terraria.Utils.PlotLine(), Microsoft.Xna.Framework.Graphics.Point, System.start, Terraria.Utils.ToTileCoordinates(), Microsoft.Xna.Framework.Point.X, and Microsoft.Xna.Framework.Point.Y.
Referenced by Terraria.WorldBuilding.Shapes.Tail.Perform().