Terraria: HouseUtils.FindRoom
FindRoom()
static Rectangle HouseUtils.FindRoom (Point origin) inline static private
     {
         Point result;
         bool flag = WorldUtils.Find(origin, Searches.Chain(new Searches.Left(25), new Conditions.IsSolid()), out result);
         Point result2;
         bool num = WorldUtils.Find(origin, Searches.Chain(new Searches.Right(25), new Conditions.IsSolid()), out result2);
         if (!flag)
         {
             result = new Point(origin.X - 25, origin.Y);
         }
         if (!num)
         {
             result2 = new Point(origin.X + 25, origin.Y);
         }
         Rectangle result3 = new Rectangle(origin.X, origin.Y, 0, 0);
         if (origin.X - result.X > result2.X - origin.X)
         {
             result3.X = result.X;
             result3.Width = Utils.Clamp(result2.X - result.X, 15, 30);
         }
         else
         {
             result3.Width = Utils.Clamp(result2.X - result.X, 15, 30);
             result3.X = result2.X - result3.Width;
         }
         Point result4;
         bool flag2 = WorldUtils.Find(result, Searches.Chain(new Searches.Up(10), new Conditions.IsSolid()), out result4);
         Point result5;
         bool num2 = WorldUtils.Find(result2, Searches.Chain(new Searches.Up(10), new Conditions.IsSolid()), out result5);
         if (!flag2)
         {
             result4 = new Point(origin.X, origin.Y - 10);
         }
         if (!num2)
         {
             result5 = new Point(origin.X, origin.Y - 10);
         }
         result3.Height = Utils.Clamp(Math.Max(origin.Y - result4.Y, origin.Y - result5.Y), 8, 12);
         result3.Y -= result3.Height;
         return result3;
     }
References Searches.Chain(), WorldUtils.Find(), Utils.Height(), and Utils.Width().
Referenced by CreateRooms().