Terraria: Terraria.GameContent.RGB.MoonShader.ProcessHighDetail
ProcessHighDetail()
void Terraria.GameContent.RGB.MoonShader.ProcessHighDetail (RgbDevice device, Fragment fragment, EffectDetailLevel quality, float time) inline private
Definition at line 62 of file MoonShader.cs.
    {
        //IL_0001: Unknown result type (might be due to invalid IL or missing references)
        //IL_0009: Unknown result type (might be due to invalid IL or missing references)
        //IL_000f: Invalid comparison between Unknown and I4
        //IL_0014: Unknown result type (might be due to invalid IL or missing references)
        if ((int)device.Type != 0 && (int)device.Type != 6)
        {
            ProcessLowDetail(device, fragment, quality, time);
            return;
        }
        Vector2 vector = new Vector2(2f, 0.5f);
        Vector2 vector2 = new Vector2(2.5f, 1f);
        float num = _progress * (float)Math.PI + (float)Math.PI;
        Vector2 vector3 = new Vector2((float)Math.Cos(num), (float)Math.Sin(num)) * vector2 + vector;
        for (int i = 0; i < fragment.Count; i++)
        {
            Vector2 canvasPositionOfIndex = fragment.GetCanvasPositionOfIndex(i);
            float dynamicNoise = NoiseHelper.GetDynamicNoise(canvasPositionOfIndex * new Vector2(0.1f, 0.5f) + new Vector2(time * 0.02f, 0f), time / 40f);
            dynamicNoise = (float)Math.Sqrt(Math.Max(0f, 1f - 2f * dynamicNoise));
            float num2 = (canvasPositionOfIndex - vector3).Length();
            Vector4 vector4 = Vector4.Lerp(_skyColor, _cloudColor, dynamicNoise * 0.15f);
            if (num2 < 0.8f)
            {
                vector4 = Vector4.Lerp(_moonRingColor, _moonCoreColor, Math.Min(0.1f, 0.8f - num2) / 0.1f);
            }
            else if (num2 < 1f)
            {
                vector4 = Vector4.Lerp(vector4, _moonRingColor, Math.Min(0.2f, 1f - num2) / 0.2f);
            }
            fragment.SetColor(i, vector4);
        }
    }
References Terraria.GameContent.RGB.MoonShader._cloudColor, Terraria.GameContent.RGB.MoonShader._moonCoreColor, Terraria.GameContent.RGB.MoonShader._moonRingColor, Terraria.GameContent.RGB.MoonShader._progress, Terraria.GameContent.RGB.MoonShader._skyColor, System.Math.Cos(), ReLogic.Peripherals.RGB.Fragment.Count, ReLogic.Peripherals.RGB.Fragment.GetCanvasPositionOfIndex(), Terraria.GameContent.RGB.NoiseHelper.GetDynamicNoise(), Microsoft.Xna.Framework.Vector4.Lerp(), System.Math.Max(), System.Math.Min(), System.Math.PI, Terraria.GameContent.RGB.MoonShader.ProcessLowDetail(), ReLogic.Peripherals.RGB.Fragment.SetColor(), System.Math.Sin(), System.Math.Sqrt(), and ReLogic.Peripherals.RGB.RgbDevice.Type.