Terraria: System.Half.RoundPackToHalf
RoundPackToHalf()
static ushort System.Half.RoundPackToHalf (bool sign, short exp, ushort sig) inline static private
Definition at line 535 of file Half.cs.
    {
        int num = sig & 0xF;
        if ((uint)exp >= 29u)
        {
            if (exp < 0)
            {
                sig = (ushort)ShiftRightJam(sig, -exp);
                exp = 0;
                num = sig & 0xF;
            }
            else if (exp > 29 || sig + 8 >= 32768)
            {
                if (!sign)
                {
                    return 31744;
                }
                return 64512;
            }
        }
        sig = (ushort)(sig + 8 >> 4);
        sig &= (ushort)(~((((num ^ 8) == 0) ? 1u : 0u) & 1u));
        if (sig == 0)
        {
            exp = 0;
        }
        return new Half(sign, (ushort)exp, sig)._value;
    }
References System.Half.Half(), and System.Half.ShiftRightJam().
Referenced by System.Half.operator Half(), and System.Half.operator Half().