Terraria: System.Half.operator double
operator double()
static System.Half.operator double (Half value) inline explicit static
Definition at line 480 of file Half.cs.
    {
        bool flag = IsNegative(value);
        int num = value.Exponent;
        uint num2 = value.Significand;
        switch (num)
        {
        case 31:
            if (num2 != 0)
            {
                return CreateDoubleNaN(flag, (ulong)num2 << 54);
            }
            if (!flag)
            {
                return double.PositiveInfinity;
            }
            return double.NegativeInfinity;
        case 0:
        {
            if (num2 == 0)
            {
                return BitConverter.UInt64BitsToDouble(flag ? 9223372036854775808uL : 0);
            }
            (int Exp, uint Sig) tuple = NormSubnormalF16Sig(num2);
            num = tuple.Exp;
            num2 = tuple.Sig;
            num--;
            break;
        }
        }
        return CreateDouble(flag, (ushort)(num + 1008), (ulong)num2 << 42);
    }
References System.Half.CreateDouble(), System.Half.CreateDoubleNaN(), System.Half.Exp, System.Half.IsNegative(), System.Half.NormSubnormalF16Sig(), System.BitConverter.UInt64BitsToDouble(), and System.value.