Terraria: System.Half.operator Half
operator Half() [1/2]
static System.Half.operator Half (double value) inline explicit static
Definition at line 421 of file Half.cs.
    {
        ulong num = BitConverter.DoubleToUInt64Bits(value);
        bool flag = (num & 0x8000000000000000uL) >> 63 != 0;
        int num2 = (int)((num & 0x7FF0000000000000L) >> 52);
        ulong num3 = num & 0xFFFFFFFFFFFFFuL;
        if (num2 == 2047)
        {
            if (num3 != 0L)
            {
                return CreateHalfNaN(flag, num3 << 12);
            }
            if (!flag)
            {
                return PositiveInfinity;
            }
            return NegativeInfinity;
        }
        uint num4 = (uint)ShiftRightJam(num3, 38);
        if (((uint)num2 | num4) == 0)
        {
            return new Half(flag, 0, 0);
        }
        return new Half(RoundPackToHalf(flag, (short)(num2 - 1009), (ushort)(num4 | 0x4000u)));
    }
References System.Half.Half(), System.Half.CreateHalfNaN(), System.BitConverter.DoubleToUInt64Bits(), System.L, System.Half.NegativeInfinity, System.Half.PositiveInfinity, System.Half.RoundPackToHalf(), System.Half.ShiftRightJam(), and System.value.