Terraria: System.Half.operator float
operator float()
static System.Half.operator float (Half value) inline explicit static
Definition at line 447 of file Half.cs.
    {
        bool flag = IsNegative(value);
        int num = value.Exponent;
        uint num2 = value.Significand;
        switch (num)
        {
        case 31:
            if (num2 != 0)
            {
                return CreateSingleNaN(flag, (ulong)num2 << 54);
            }
            if (!flag)
            {
                return float.PositiveInfinity;
            }
            return float.NegativeInfinity;
        case 0:
        {
            if (num2 == 0)
            {
                return BitConverter.UInt32BitsToSingle(flag ? 2147483648u : 0u);
            }
            (int Exp, uint Sig) tuple = NormSubnormalF16Sig(num2);
            num = tuple.Exp;
            num2 = tuple.Sig;
            num--;
            break;
        }
        }
        return CreateSingle(flag, (byte)(num + 112), num2 << 13);
    }
References System.Half.CreateSingle(), System.Half.CreateSingleNaN(), System.Half.Exp, System.Half.IsNegative(), System.Half.NormSubnormalF16Sig(), System.BitConverter.UInt32BitsToSingle(), and System.value.