Terraria: System.Half.operator Half
operator Half() [2/2]
static System.Half.operator Half (float value) inline explicit static
Definition at line 395 of file Half.cs.
    {
        uint num = BitConverter.SingleToUInt32Bits(value);
        bool flag = (num & 0x80000000u) >> 31 != 0;
        int num2 = (int)(num & 0x7F800000) >> 23;
        uint num3 = num & 0x7FFFFFu;
        if (num2 == 255)
        {
            if (num3 != 0)
            {
                return CreateHalfNaN(flag, (ulong)num3 << 41);
            }
            if (!flag)
            {
                return PositiveInfinity;
            }
            return NegativeInfinity;
        }
        uint num4 = (num3 >> 9) | (((num3 & 0x1FFu) != 0) ? 1u : 0u);
        if (((uint)num2 | num4) == 0)
        {
            return new Half(flag, 0, 0);
        }
        return new Half(RoundPackToHalf(flag, (short)(num2 - 113), (ushort)(num4 | 0x4000u)));
    }
References System.Half.Half(), System.Half.CreateHalfNaN(), System.Half.NegativeInfinity, System.Half.PositiveInfinity, System.Half.RoundPackToHalf(), System.BitConverter.SingleToUInt32Bits(), and System.value.