Terraria: System.Half.TryParse
TryParse() [6/12]
static bool System.Half.TryParse ([NotNullWhen(true)] string? s, out Half result) inline static
Definition at line 254 of file Half.cs.
    {
        if (s == null)
        {
            result = default(Half);
            return false;
        }
        return TryParse(s, NumberStyles.Float | NumberStyles.AllowThousands, null, out result);
    }
References System.s, and System.Half.TryParse().
Referenced by System.Half.TryParse(), System.Half.TryParse(), System.Half.TryParse(), System.Half.TryParse(), System.Half.TryParse(), System.Half.TryParse(), and System.Half.TryParse().