Terraria: System.Half.CreateHalfNaN
CreateHalfNaN()
static Half System.Half.CreateHalfNaN (bool sign, ulong significand) inline static private
Definition at line 528 of file Half.cs.
    {
        uint num = (uint)((sign ? 1 : 0) << 15);
        uint num2 = (uint)(significand >> 54);
        return BitConverter.UInt16BitsToHalf((ushort)(num | 0x7E00u | num2));
    }
References System.BitConverter.UInt16BitsToHalf().
Referenced by System.Half.operator Half(), and System.Half.operator Half().