Terraria: System.Half.Parse
Parse() [12/12]
static Half System.Half.Parse (string s, NumberStyles style = NumberStyles::Float | NumberStyles::AllowThousands, IFormatProvider? provider = null) inline static
Definition at line 238 of file Half.cs.
    {
        NumberFormatInfo.ValidateParseStyleFloatingPoint(style);
        if (s == null)
        {
            ThrowHelper.ThrowArgumentNullException(ExceptionArgument.s);
        }
        return Number.ParseHalf(s, style, NumberFormatInfo.GetInstance(provider));
    }
References System.Globalization.NumberFormatInfo.GetInstance(), System.Number.ParseHalf(), System.s, System.ThrowHelper.ThrowArgumentNullException(), and System.Globalization.NumberFormatInfo.ValidateParseStyleFloatingPoint().