Terraria: NPC.TransformCopperSlime
TransformCopperSlime()
static void NPC.TransformCopperSlime (int npcIndex) inline static
     {
         if (Main.netMode == 1)
         {
             NetMessage.SendData(140, -1, -1, null, 1, npcIndex);
         }
         else if (!unlockedSlimeCopperSpawn && Main.npc.IndexInRange(npcIndex))
         {
             NPC nPC = Main.npc[npcIndex];
             if (nPC.type >= 0 && nPC.type < NPCID.Count && NPCID.Sets.CanConvertIntoCopperSlimeTownNPC[nPC.type])
             {
                 unlockedSlimeCopperSpawn = true;
                 NetMessage.SendData(7);
                 Vector2 vector = nPC.velocity;
                 nPC.Transform(684);
                 nPC.netUpdate = true;
                 nPC.velocity = vector;
                 ParticleOrchestrator.BroadcastParticleSpawn(ParticleOrchestraType.TownSlimeTransform, new ParticleOrchestraSettings
                 {
                     PositionInWorld = nPC.Center,
                     MovementVector = Vector2.Zero,
                     UniqueInfoPiece = 1
                 });
             }
         }
     }
References ParticleOrchestrator.BroadcastParticleSpawn(), NPCID.Sets.CanConvertIntoCopperSlimeTownNPC, NPCID.Count, Main.netMode, netUpdate, Main.npc, NetMessage.SendData(), Transform(), type, unlockedSlimeCopperSpawn, and Entity.velocity.
Referenced by MessageBuffer.GetData(), and Item.GetPickedUpByMonsters_Special().