Terraria: NPC.UpdateNPC_CastLights
UpdateNPC_CastLights()
void NPC.UpdateNPC_CastLights () inline private
     {
         if ((type >= 442 && type <= 448) || type == 539 || type == 592 || type == 593 || type == 601 || type == 605 || type == 627)
         {
             position += netOffset;
             Color color = Lighting.GetColor((int)base.Center.X / 16, (int)base.Center.Y / 16);
             if (color.R > 20 || color.B > 20 || color.G > 20)
             {
                 int num = color.R;
                 if (color.G > num)
                 {
                     num = color.G;
                 }
                 if (color.B > num)
                 {
                     num = color.B;
                 }
                 num /= 30;
                 if (Main.rand.Next(300) < num)
                 {
                     int num2 = Dust.NewDust(position, width, height, 43, 0f, 0f, 254, new Color(255, 255, 0), 0.5f);
                     Main.dust[num2].velocity *= 0f;
                 }
             }
             position -= netOffset;
         }
         if (type == 160)
         {
             float num3 = (float)Main.rand.Next(28, 42) * 0.005f;
             num3 += (float)(270 - Main.mouseTextColor) / 500f;
             float num4 = 0.1f;
             float num5 = 0.3f + num3 / 2f;
             float num6 = 0.6f + num3;
             if (townNpcVariationIndex == 1)
             {
                 float num7 = num4;
                 num4 = num6;
                 num6 = num7;
             }
             float num8 = 0.35f;
             num4 *= num8;
             num5 *= num8;
             num6 *= num8;
             Lighting.AddLight((int)base.Center.X / 16, (int)base.Center.Y / 16, num4, num5, num6);
         }
         if ((type >= 254 && type <= 261) || type == 634 || type == 635)
         {
             float num9 = (float)Main.rand.Next(28, 42) * 0.005f;
             num9 += (float)(270 - Main.mouseTextColor) / 500f;
             float num10 = 0.1f;
             float num11 = 0.3f + num9 / 2f;
             float num12 = 0.6f + num9;
             float num13 = 0.35f;
             if (type == 634)
             {
                 num13 = 0.65f;
             }
             num10 *= num13;
             num11 *= num13;
             num12 *= num13;
             Lighting.AddLight((int)base.Center.X / 16, (int)base.Center.Y / 16, num10, num11, num12);
         }
         if (type == 209)
         {
             float num14 = (float)Main.rand.Next(28, 42) * 0.005f;
             num14 += (float)(270 - Main.mouseTextColor) / 500f;
             float num15 = 0.1f;
             float num16 = 0.3f + num14 / 2f;
             float num17 = 0.4f + num14 / 2f;
             float num18 = 0.35f;
             num15 *= num18;
             num16 *= num18;
             num17 *= num18;
             Lighting.AddLight((int)base.Center.X / 16, (int)base.Center.Y / 16, num15, num16, num17);
             if (ai[0] == 12f)
             {
                 Lighting.AddLight(base.Top, 0.3f, 0.1f, 0.1f);
             }
         }
         if (type == 44)
         {
             Lighting.AddLight((int)(position.X + (float)(width / 2)) / 16, (int)(position.Y + 4f) / 16, 0.9f, 0.75f, 0.5f);
         }
     }
References Lighting.AddLight(), Color, Main.dust, Lighting.GetColor(), Main.mouseTextColor, Dust.NewDust(), UnifiedRandom.Next(), Main.rand, and Dust.velocity.