Terraria: NPC.AI_118_Seahorses
AI_118_Seahorses()
void NPC.AI_118_Seahorses () inline private
     {
         noGravity = wet;
         Collision.GetWaterLineIterate(base.Center.ToTileCoordinates(), out var waterLineHeight);
         bool flag = waterLineHeight > 0f && base.Top.Y - waterLineHeight < 20f;
         if (!wet)
         {
             if (velocity.Y == 0f)
             {
                 velocity.X *= 0.95f;
             }
             rotation += (velocity.X + velocity.Y) / 2f * 0.05f;
         }
         else
         {
             ai[1] -= 1f;
             if (ai[1] <= 0f)
             {
                 velocity += ai[0].ToRotationVector2() * 0.06f;
                 float num = velocity.Length();
                 if (num > 3f || num < -3f)
                 {
                     velocity.X = Math.Min(3f, Math.Max(-3f, velocity.X));
                     ai[1] = Main.rand.Next(450, 600);
                     ai[0] = Main.rand.NextFloat() * ((float)Math.PI * 2f);
                     if (flag && ai[0] > (float)Math.PI)
                     {
                         ai[0] -= (float)Math.PI;
                     }
                     netUpdate = true;
                 }
             }
             else
             {
                 velocity *= 0.95f;
             }
             rotation = velocity.X * 0.1f;
         }
         bool flag2 = collideY && wet && (!flag || velocity.Y < 0f);
         if (collideX || flag2)
         {
             Vector2 v = ai[0].ToRotationVector2();
             if (collideX)
             {
                 v.X *= -1f;
             }
             if (flag2)
             {
                 v.Y *= -1f;
             }
             ai[0] = v.ToRotation();
             velocity = ai[0].ToRotationVector2() * velocity.Length();
             netUpdate = true;
         }
     }
References ai, collideX, collideY, Collision.GetWaterLineIterate(), netUpdate, UnifiedRandom.Next(), noGravity, Main.rand, rotation, Entity.velocity, and Entity.wet.
Referenced by AI().