Terraria: NPC.AI_AttemptToFindTeleportSpot
AI_AttemptToFindTeleportSpot()
bool NPC.AI_AttemptToFindTeleportSpot (ref Vector2 chosenTile, int targetTileX, int targetTileY, int rangeFromTargetTile = 20, int telefragPreventionDistanceInTiles = 5, int solidTileCheckFluff = 1, bool solidTileCheckCentered = false, bool teleportInAir = false) inline
     {
         int num = (int)base.Center.X / 16;
         int num2 = (int)base.Center.Y / 16;
         int num3 = 0;
         bool flag = false;
         float num4 = 20f;
         if (Math.Abs(num * 16 - targetTileX * 16) + Math.Abs(num2 * 16 - targetTileY * 16) > 2000)
         {
             num3 = 100;
             flag = false;
         }
         while (!flag && num3 < 100)
         {
             num3++;
             int num5 = Main.rand.Next(targetTileX - rangeFromTargetTile, targetTileX + rangeFromTargetTile + 1);
             for (int i = Main.rand.Next(targetTileY - rangeFromTargetTile, targetTileY + rangeFromTargetTile + 1); i < targetTileY + rangeFromTargetTile; i++)
             {
                 if ((i >= num2 - 1 && i <= num2 + 1 && num5 >= num - 1 && num5 <= num + 1) || (!teleportInAir && !Main.tile[num5, i].nactive()))
                 {
                     continue;
                 }
                 bool flag2 = true;
                 if ((type == 32 || (type >= 281 && type <= 286)) && !Main.wallDungeon[Main.tile[num5, i - 1].wall])
                 {
                     if (!AnyNPCs(35))
                     {
                         flag2 = false;
                     }
                 }
                 else if (Main.tile[num5, i - 1].lava())
                 {
                     flag2 = false;
                 }
                 if (!flag2 || (!teleportInAir && !Main.tileSolid[Main.tile[num5, i].type]))
                 {
                     continue;
                 }
                 bool flag3 = false;
                 if (!((!solidTileCheckCentered) ? (!Collision.SolidTiles(num5 - solidTileCheckFluff, num5 + solidTileCheckFluff, i - 3 - solidTileCheckFluff, i - 1)) : (!Collision.SolidTiles(num5 - solidTileCheckFluff, num5 + solidTileCheckFluff, i - solidTileCheckFluff, i + solidTileCheckFluff))))
                 {
                     continue;
                 }
                 Rectangle rectangle = new Rectangle(num5 * 16, i * 16, 16, 16);
                 rectangle.Inflate(telefragPreventionDistanceInTiles * 16, telefragPreventionDistanceInTiles * 16);
                 for (int j = 0; j < Main.player.Length; j++)
                 {
                     Player player = Main.player[j];
                     if (player != null && player.active && !player.DeadOrGhost)
                     {
                         Rectangle value = player.Hitbox;
                         Rectangle value2 = value.Modified((int)(player.velocity.X * num4), (int)(player.velocity.Y * num4), 0, 0);
                         Rectangle.Union(ref value2, ref value, out value2);
                         if (value2.Intersects(rectangle))
{
                             flag2 = false;
                             flag = false;
                             break;
                         }
                     }
                 }
                 if (flag2)
                 {
                     chosenTile = new Vector2(num5, i);
                     flag = true;
                 }
                 break;
             }
         }
         return flag;
     }
References Entity.active, AnyNPCs(), Player.DeadOrGhost, Entity.Hitbox, Tile.lava(), Tile.nactive(), UnifiedRandom.Next(), Main.player, Main.rand, Collision.SolidTiles(), Main.tile, Main.tileSolid, type, Tile.type, value, Entity.velocity, Tile.wall, and Main.wallDungeon.
Referenced by AI(), and AI_003_Fighters().