Terraria: NPC.CountKillForAchievements
CountKillForAchievements()
void NPC.CountKillForAchievements () inline private
     {
         switch (type)
         {
         case 125:
         case 126:
             if (!AnyNPCs((type == 126) ? 125 : 126))
             {
                 AchievementsHelper.NotifyNPCKilled(this);
                 AchievementsHelper.CheckMechaMayhem(type);
             }
             break;
         case 127:
         case 134:
             AchievementsHelper.CheckMechaMayhem(type);
             AchievementsHelper.NotifyNPCKilled(this);
             break;
         case 13:
         case 14:
         case 15:
             if (boss)
             {
                 AchievementsHelper.NotifyNPCKilled(this);
             }
             break;
         default:
             AchievementsHelper.NotifyNPCKilled(this);
             break;
         }
     }
References AchievementsHelper.CheckMechaMayhem(), and AchievementsHelper.NotifyNPCKilled().
Referenced by NPCLoot().