Terraria: NPC.NPCLoot
NPCLoot()
void NPC.NPCLoot () inline
     {
         if (Main.netMode == 1 || type >= NPCID.Count || (Main.getGoodWorld && !downedBoss3 && (type == 31 || type == 294 || type == 296 || type == 295 || type == 32 || type == 34 || type == 71)))
         {
             return;
         }
         Player closestPlayer = Main.player[Player.FindClosest(position, width, height)];
         if (0 == 0)
         {
             CountKillForAchievements();
             if (GetWereThereAnyInteractions())
             {
                 if (IsNPCValidForBestiaryKillCredit())
                 {
                     Main.BestiaryTracker.Kills.RegisterKill(this);
                 }
                 CountKillForBannersAndDropThem();
             }
         }
         if ((type == 23 && Main.hardMode) || (SpawnedFromStatue && NPCID.Sets.NoEarlymodeLootWhenSpawnedFromStatue[type] && !Main.hardMode) || (SpawnedFromStatue && NPCID.Sets.StatueSpawnedDropRarity[type] != -1f && (Main.rand.NextFloat() >= NPCID.Sets.StatueSpawnedDropRarity[type] || !AnyInteractions())))
         {
             return;
         }
         bool num = downedMechBoss1 && downedMechBoss2 && downedMechBoss3;
         DoDeathEvents_BeforeLoot(closestPlayer);
         NPCLoot_DropItems(closestPlayer);
         DoDeathEvents(closestPlayer);
         if (!num && downedMechBoss1 && downedMechBoss2 && downedMechBoss3 && Main.hardMode)
         {
             if (Main.netMode == 0)
             {
                 Main.NewText(Lang.misc[32].Value, 50, byte.MaxValue, 130);
             }
             else if (Main.netMode == 2)
             {
                 ChatHelper.BroadcastChatMessage(NetworkText.FromKey(Lang.misc[32].Key), new Color(50, 255, 130));
             }
         }
         NPCLoot_DropMoney(closestPlayer);
         NPCLoot_DropHeals(closestPlayer);
     }
References AnyInteractions(), Main.BestiaryTracker, ChatHelper.BroadcastChatMessage(), Color, NPCID.Count, CountKillForAchievements(), CountKillForBannersAndDropThem(), DoDeathEvents(), DoDeathEvents_BeforeLoot(), downedBoss3, downedMechBoss1, downedMechBoss2, downedMechBoss3, Player.FindClosest(), NetworkText.FromKey(), Main.getGoodWorld, GetWereThereAnyInteractions(), Main.hardMode, Entity.height, IsNPCValidForBestiaryKillCredit(), LocalizedText.Key, BestiaryUnlocksTracker.Kills, Lang.misc, Main.netMode, Main.NewText(), NPCID.Sets.NoEarlymodeLootWhenSpawnedFromStatue, NPCLoot_DropHeals(), NPCLoot_DropItems(), NPCLoot_DropMoney(), Main.player, Entity.position, Main.rand, NPCKillsTracker.RegisterKill(), SpawnedFromStatue, NPCID.Sets.StatueSpawnedDropRarity, type, LocalizedText.Value, and Entity.width.
Referenced by checkDead(), and DropEoWLoot().