Terraria: NPC.SpawnWOF
SpawnWOF()
static void NPC.SpawnWOF (Vector2 pos) inline static
     {
         if (pos.Y / 16f < (float)(Main.maxTilesY - 205) || Main.wofNPCIndex >= 0 || Main.netMode == 1 || AnyNPCs(113))
         {
             return;
         }
         Player.FindClosest(pos, 16, 16);
         int num = 1;
         if (pos.X / 16f > (float)(Main.maxTilesX / 2))
         {
             num = -1;
         }
         bool flag = false;
         int num2 = (int)pos.X;
         int targetPlayerIndex = 0;
         while (!flag)
         {
             flag = true;
             for (int i = 0; i < 255; i++)
             {
                 if (Main.player[i].active && Main.player[i].position.X > (float)(num2 - 1200) && Main.player[i].position.X < (float)(num2 + 1200))
                 {
                     num2 -= num * 16;
                     flag = false;
                     targetPlayerIndex = i;
                 }
             }
             if (num2 / 16 < 20 || num2 / 16 > Main.maxTilesX - 20)
             {
                 flag = true;
             }
         }
         int num3 = (int)pos.Y;
         int num4 = num2 / 16;
         int num5 = num3 / 16;
         int num6 = 0;
         int num7 = 1000;
         if (!WorldGen.InWorld(num4, num5, 2) || WorldGen.SolidTile(num4, num5) || Main.tile[num4, num5 - num6].liquid >= 100)
         {
             while (true)
             {
                 num7--;
                 if (num7 <= 0)
                 {
                     break;
                 }
                 try
                 {
                     if (WorldGen.InWorld(num4, num5 - num6, 2) && !WorldGen.SolidTile(num4, num5 - num6) && Main.tile[num4, num5 - num6].liquid < 100)
                     {
                         num5 -= num6;
                         break;
                     }
                     if (WorldGen.InWorld(num4, num5 + num6, 2) && !WorldGen.SolidTile(num4, num5 + num6) && Main.tile[num4, num5 + num6].liquid < 100)
                     {
                         num5 += num6;
                         break;
                     }
                     num6++;
                 }
                 catch
                 {
                     break;
                 }
             }
         }
         int num8 = Main.UnderworldLayer + 10;
         int num9 = num8 + 70;
         if (num5 < num8)
         {
             num5 = num8;
         }
         if (num5 > num9)
         {
             num5 = num9;
         }
         num3 = num5 * 16;
         int num10 = NewNPC(GetBossSpawnSource(targetPlayerIndex), num2, num3, 113);
         if (Main.netMode == 0)
         {
             Main.NewText(Language.GetTextValue("Announcement.HasAwoken", Main.npc[num10].TypeName), 175, 75);
         }
         else if (Main.netMode == 2)
         {
             ChatHelper.BroadcastChatMessage(NetworkText.FromKey("Announcement.HasAwoken", Main.npc[num10].GetTypeNetName()), new Color(175, 75, 255));
         }
     }
References Entity.active, ChatHelper.BroadcastChatMessage(), Color, Player.FindClosest(), NetworkText.FromKey(), Language.GetTextValue(), GetTypeNetName(), WorldGen.InWorld(), Tile.liquid, Main.maxTilesX, Main.maxTilesY, Main.netMode, Main.NewText(), Main.npc, Main.player, Entity.position, WorldGen.SolidTile(), Main.tile, TypeName, Main.UnderworldLayer, and Main.wofNPCIndex.
Referenced by Item.CheckLavaDeath(), and DoDeathEvents().