Terraria: NPC.AI_119_Dandelion
AI_119_Dandelion()
void NPC.AI_119_Dandelion () inline private
     {
         if (!Main.IsItAHappyWindyDay && timeLeft > 10)
         {
             timeLeft = 10;
         }
         bool flag = false;
         float num = 0f;
         float num2 = 0f;
         NPCUtils.TargetClosestDownwindFromNPC(this, 600f);
         NPCAimedTarget targetData = GetTargetData();
         if (targetData.Type == NPCTargetType.Player)
         {
             Rectangle hitbox = targetData.Hitbox;
             float windSpeedCurrent = Main.windSpeedCurrent;
             num = (float)hitbox.Center.X - base.Center.X;
             num2 = Math.Abs(num);
             flag = Math.Abs((float)hitbox.Center.Y - base.Center.Y) < 100f && num2 < 600f && ((num > 0f && windSpeedCurrent > 0f) || (num < 0f && windSpeedCurrent < 0f));
         }
         if (ai[0] == 1f)
         {
             localAI[0] = 0f;
             if (num2 < 500f)
             {
                 localAI[0] = 1f;
             }
             if (Main.netMode == 1)
             {
                 return;
             }
             if (!flag)
             {
                 ai[0] = 0f;
                 netUpdate = true;
             }
             else
             {
                 if (localAI[0] != 1f)
                 {
                     return;
                 }
                 localAI[1] += 1f;
                 if (localAI[1] > 80f)
                 {
                     ai[0] = 0f;
                     netUpdate = true;
                 }
                 else
                 {
                     if (localAI[1] != 40f)
                     {
                         return;
                     }
                     for (int i = 0; i < 1 + Main.rand.Next(3); i++)
                     {
                         int num3 = -1;
                         if (num > 0f)
{
                             num3 = 1;
                         }
                         Vector2 vector = new Vector2(num3 * Main.rand.Next(-2, 10), 10 + Main.rand.Next(-6, 6));
                         Vector2 vector2 = new Vector2(2f * (float)num3, -2f);
                         vector2 += vector * 0.25f;
                         if (vector2.Y > -3f)
{
                             vector2.Y = -3f;
                         }
                         Vector2 vector3 = base.Center + vector;
                         vector3.X += num3 * 6;
                         int num4 = 7;
                         Projectile.NewProjectile(GetSpawnSource_ForProjectile(), vector3, vector2, 836, num4, 1f, Main.myPlayer, 0f, target);
                     }
                     netUpdate = true;
                 }
             }
         }
         else if (ai[0] == 0f)
         {
             localAI[0] = 0f;
             localAI[1] = 0f;
             if (Main.netMode != 1 && flag)
             {
                 ai[0] = 1f;
                 netUpdate = true;
             }
         }
     }
References ai, GetSpawnSource_ForProjectile(), GetTargetData(), NPCAimedTarget.Hitbox, Main.IsItAHappyWindyDay, localAI, Main.myPlayer, Main.netMode, netUpdate, Projectile.NewProjectile(), UnifiedRandom.Next(), Main.rand, target, NPCUtils.TargetClosestDownwindFromNPC(), timeLeft, NPCAimedTarget.Type, and Main.windSpeedCurrent.
Referenced by AI().