Terraria: NPC.TryTrackingTarget
TryTrackingTarget()
void NPC.TryTrackingTarget (ref float distance, ref float realDist, ref bool t, ref int tankTarget, int j) inline private
     {
         float num = Math.Abs(Main.player[j].position.X + (float)(Main.player[j].width / 2) - position.X + (float)(width / 2)) + Math.Abs(Main.player[j].position.Y + (float)(Main.player[j].height / 2) - position.Y + (float)(height / 2));
         num -= (float)Main.player[j].aggro;
         if (Main.player[j].npcTypeNoAggro[type] && direction != 0)
         {
             num += 1000f;
         }
         if (!t || num < distance)
         {
             t = true;
             tankTarget = -1;
             realDist = Math.Abs(Main.player[j].position.X + (float)(Main.player[j].width / 2) - position.X + (float)(width / 2)) + Math.Abs(Main.player[j].position.Y + (float)(Main.player[j].height / 2) - position.Y + (float)(height / 2));
             distance = num;
             target = j;
         }
         if (Main.player[j].tankPet >= 0 && !Main.player[j].npcTypeNoAggro[type])
         {
             int tankPet = Main.player[j].tankPet;
             float num2 = Math.Abs(Main.projectile[tankPet].position.X + (float)(Main.projectile[tankPet].width / 2) - position.X + (float)(width / 2)) + Math.Abs(Main.projectile[tankPet].position.Y + (float)(Main.projectile[tankPet].height / 2) - position.Y + (float)(height / 2));
             num2 -= 200f;
             if (num2 < distance && num2 < 200f && Collision.CanHit(base.Center, 1, 1, Main.projectile[tankPet].Center, 1, 1))
             {
                 tankTarget = tankPet;
             }
         }
     }
References Player.aggro, Collision.CanHit(), Entity.Center, Entity.direction, Entity.height, Player.npcTypeNoAggro, Main.player, Entity.position, Main.projectile, Player.tankPet, target, type, and Entity.width.
Referenced by TargetClosest(), and TargetClosest_WOF().