Terraria: NPC.checkArmorPenetration
checkArmorPenetration()
int NPC.checkArmorPenetration (int armorPenetration, float armorPenetrationPercent) inline
     {
         if (ichor)
         {
             armorPenetration += 15;
         }
         if (betsysCurse)
         {
             armorPenetration += 40;
         }
         armorPenetration += (int)((float)defense * armorPenetrationPercent);
         if (armorPenetration <= 0 || defense <= 0)
         {
             return 0;
         }
         if (armorPenetration > defense)
         {
             return defense / 2;
         }
         return armorPenetration / 2;
     }
Referenced by Player.ApplyDamageToNPC(), Projectile.Damage(), and Player.ProcessHitAgainstNPC().