Terraria: NPC.FindFirstNPC
FindFirstNPC()
static int NPC.FindFirstNPC (int Type) inline static
     {
         for (int i = 0; i < 200; i++)
         {
             if (Main.npc[i].active && Main.npc[i].type == Type)
             {
                 return i;
             }
         }
         return -1;
     }
References Entity.active, Main.npc, and type.
Referenced by AI(), AI_005_EaterOfSouls(), DD2Event.Difficulty_3_GetRequiredWaveKills(), DoDeathEvents(), SpawnMechQueen(), DD2Event.StartVictoryScene(), DD2Event.SummonBetsy(), and Player.UpdateBiomes().