Terraria: NPC.ShouldFaceTarget
ShouldFaceTarget()
bool NPC.ShouldFaceTarget (ref NPCUtils.TargetSearchResults searchResults, NPCUtils.TargetType? overrideTargetType = null) inline
     {
         NPCUtils.TargetType nearestTargetType = searchResults.NearestTargetType;
         if (overrideTargetType.HasValue)
         {
             nearestTargetType = overrideTargetType.Value;
         }
         switch (nearestTargetType)
         {
         case NPCUtils.TargetType.NPC:
         case NPCUtils.TargetType.TankPet:
             return true;
         case NPCUtils.TargetType.Player:
         {
             bool flag = true;
             Player nearestTankOwner = searchResults.NearestTankOwner;
             if (nearestTankOwner.dead || (nearestTankOwner.npcTypeNoAggro[type] && direction != 0))
             {
                 flag = false;
             }
             if (!flag)
             {
                 break;
             }
             float num = (float)(nearestTankOwner.width + nearestTankOwner.height + width + height) / 4f + 800f;
             if (nearestTankOwner.itemAnimation == 0 && nearestTankOwner.aggro < 0 && searchResults.NearestTankDistance > num)
             {
                 if (oldTarget >= 0)
                 {
                     return oldTarget >= 255;
                 }
                 return true;
             }
             return true;
         }
         }
         return false;
     }
References Player.aggro, Player.dead, Entity.direction, Entity.height, Player.itemAnimation, Player.npcTypeNoAggro, oldTarget, type, and Entity.width.
Referenced by NPCUtils.TargetClosestBetsy(), NPCUtils.TargetClosestDownwindFromNPC(), NPCUtils.TargetClosestNonBees(), and NPCUtils.TargetClosestOldOnesInvasion().