Terraria: NPC.GetTypeNetName
GetTypeNetName()
NetworkText NPC.GetTypeNetName () inline
     {
         return NetworkText.FromKey(Lang.GetNPCName(netID).Key);
     }
References NetworkText.FromKey(), Lang.GetNPCName(), LocalizedText.Key, and netID.
Referenced by DoDeathEvents_CelebrateBossDeath(), GetFullNetName(), GetGivenOrTypeNetName(), NewNPC(), SpawnBoss(), SpawnOnPlayer(), and SpawnWOF().