Terraria: NPC.AI_87_BigMimic_FireStuffCannonBurst
AI_87_BigMimic_FireStuffCannonBurst()
void NPC.AI_87_BigMimic_FireStuffCannonBurst () inline private
     {
         int num = 10;
         for (int i = 0; i < num; i++)
         {
             int itemID = ItemID.Sets.ItemsForStuffCannon[Main.rand.Next(ItemID.Sets.ItemsForStuffCannon.Length)];
             AI_87_BigMimic_ShootItem(itemID);
         }
     }
References AI_87_BigMimic_ShootItem(), ItemID.Sets.ItemsForStuffCannon, UnifiedRandom.Next(), and Main.rand.
Referenced by AI().