Terraria: NPC.GetTargetData
GetTargetData()
NPCAimedTarget NPC.GetTargetData (bool ignorePlayerTankPets = true) inline
     {
         if (!HasValidTarget)
         {
             return default(NPCAimedTarget);
         }
         if (SupportsNPCTargets && HasNPCTarget)
         {
             return new NPCAimedTarget(Main.npc[TranslatedTargetIndex]);
         }
         return new NPCAimedTarget(Main.player[target], ignorePlayerTankPets);
     }
References HasNPCTarget, HasValidTarget, Main.npc, Main.player, SupportsNPCTargets, target, and TranslatedTargetIndex.
Referenced by AI_005_EaterOfSouls(), AI_007_TownEntities(), AI_065_Butterflies(), AI_107_ImprovedWalkers(), AI_108_DivingFlyer(), AI_109_DarkMage(), AI_110_Betsy(), AI_111_DD2LightningBug(), AI_112_FairyCritter(), AI_113_WindyBalloon(), AI_117_BloodNautilus(), AI_119_Dandelion(), AI_120_HallowBoss(), AI_122_PirateGhost(), AI_123_Deerclops(), AI_123_Deerclops_Movement(), AI_123_Deerclops_TryMakingSpike_FindBestY(), AI_124_DeerclopsLeg(), and AI_125_ClumsySlimeBalloon().