Terraria: NPC.AI_007_TryForcingSitting
AI_007_TryForcingSitting()
void NPC.AI_007_TryForcingSitting (int homeFloorX, int homeFloorY) inline private
     {
         Tile tile = Main.tile[homeFloorX, homeFloorY - 1];
         bool flag = type != 638 && type != 656 && !NPCID.Sets.IsTownSlime[type] && ai[0] != 5f;
         if (flag)
         {
             flag &= tile != null && tile.active() && (tile.type == 15 || tile.type == 497);
         }
         if (flag)
         {
             flag &= tile.type != 15 || tile.frameY < 1080 || tile.frameY > 1098;
         }
         if (flag)
         {
             Point point = (base.Bottom + Vector2.UnitY * -2f).ToTileCoordinates();
             for (int i = 0; i < 200; i++)
             {
                 if (Main.npc[i].active && Main.npc[i].aiStyle == 7 && Main.npc[i].townNPC && Main.npc[i].ai[0] == 5f && (Main.npc[i].Bottom + Vector2.UnitY * -2f).ToTileCoordinates() == point)
                 {
                     flag = false;
                     break;
                 }
             }
         }
         if (flag)
         {
             ai[0] = 5f;
             ai[1] = 900 + Main.rand.Next(10800);
             direction = ((tile.frameX != 0) ? 1 : (-1));
             base.Bottom = new Vector2(homeFloorX * 16 + 8 + 2 * direction, homeFloorY * 16);
             velocity = Vector2.Zero;
             localAI[3] = 0f;
             netUpdate = true;
         }
     }
References Entity.active, Tile.active(), ai, aiStyle, Entity.Bottom, Entity.direction, Tile.frameX, Tile.frameY, NPCID.Sets.IsTownSlime, localAI, netUpdate, UnifiedRandom.Next(), Main.npc, Main.rand, Main.tile, townNPC, type, Tile.type, and Entity.velocity.
Referenced by AI_007_TownEntities(), and AI_007_TownEntities_TeleportToHome().