Terraria: NPC.moneyPing
moneyPing()
void NPC.moneyPing (Vector2 pos) inline
     {
         SoundEngine.PlaySound(38, pos);
         int num = 244;
         if (extraValue >= 1000000)
         {
             num = 247;
         }
         else if (extraValue >= 10000)
         {
             num = 246;
         }
         else if (extraValue >= 100)
         {
             num = 245;
         }
         for (int i = 0; i < 20; i++)
         {
             int num2 = Dust.NewDust(pos - new Vector2(1f, 2f), 10, 14, num, 0f, 0f, 254, default(Color), 0.25f);
             Main.dust[num2].velocity *= 0.2f;
         }
     }
References Color, Main.dust, Dust.NewDust(), SoundEngine.PlaySound(), and Dust.velocity.
Referenced by MessageBuffer.GetData(), Item.GetPickedUpByMonsters_Money(), and CoinLossRevengeSystem.RevengeMarker.SpawnEnemy().