Terraria: NPC.AI_111_DD2LightningBug
AI_111_DD2LightningBug()
void NPC.AI_111_DD2LightningBug () inline private
     {
         //IL_02f6: Unknown result type (might be due to invalid IL or missing references)
         bool flag = true;
         float num = 7f;
         float num2 = 60f;
         float num3 = 60f;
         float num4 = 1f;
         float num5 = 0.96f;
         int num6 = 30;
         int num7 = 20;
         float num8 = 200f;
         int num9 = 40;
         int num10 = 438;
         float num11 = 10f;
         float num12 = 100f;
         bool flag2 = false;
         float num13 = 0.05f;
         Vector2 center = base.Center;
         NPCUtils.TargetClosestOldOnesInvasion(this);
         NPCAimedTarget targetData = GetTargetData();
         bool flag3 = false;
         int num14 = type;
         if (num14 == 578)
         {
             num = 4f;
             num2 = 20f;
             num3 = 20f;
             flag3 = true;
             flag2 = true;
             num13 = 0.1f;
             num10 = 682;
             num9 = 50;
             num11 = 10f;
             num12 = 50f;
             num6 = 5;
             num7 = 30;
             center += new Vector2(-spriteDirection * 20, 10f);
             position += netOffset;
             if (Main.rand.Next(15) == 0)
             {
                 Vector2 vector = position;
                 if (direction == -1)
                 {
                     vector.X += width / 2;
                 }
                 Dust dust = Dust.NewDustDirect(vector, width / 2, height, 272);
                 dust.scale = 0.65f;
                 dust.velocity.Y -= 0.8f;
                 if (dust.velocity.X * (float)direction > 0f)
                 {
                     dust.velocity.X *= -1f;
                 }
                 if (dust.velocity.Y > 0f)
                 {
                     dust.velocity *= -0.5f;
                 }
             }
             if (Main.rand.Next(80) == 0)
             {
                 Vector2 vector2 = (Main.rand.NextFloat() * ((float)Math.PI * 2f)).ToRotationVector2();
                 Dust dust2 = Dust.NewDustPerfect(base.Center, 272, vector2);
                 dust2.velocity *= 1.1f;
                 dust2.noGravity = true;
                 dust2.customData = this;
                 Dust dust3 = Dust.NewDustPerfect(base.Center, 272, vector2);
                 dust3.velocity *= 1.5f;
                 dust3.noGravity = true;
                 dust3.customData = this;
             }
             position -= netOffset;
         }
         if (flag3)
         {
             if (localAI[1] == 0f)
             {
                 alpha = 255;
             }
             if (localAI[1] == 30f)
             {
                 SoundEngine.PlayTrackedSound(SoundID.DD2_EtherianPortalSpawnEnemy, base.Center);
             }
             if (localAI[1] < 60f)
             {
                 localAI[1] += 1f;
                 alpha -= 5;
                 if (alpha < 0)
                 {
                     alpha = 0;
                 }
                 int num15 = (int)localAI[1] / 10;
                 float num16 = base.Size.Length() / 2f;
                 num16 /= 20f;
                 int maxValue = 5;
                 if (type == 576 || type == 577)
                 {
                     maxValue = 1;
                 }
                 for (int i = 0; i < num15; i++)
                 {
                     if (Main.rand.Next(maxValue) == 0)
                     {
                         Dust dust4 = Dust.NewDustDirect(position, width, height, 27, velocity.X * 1f, 0f, 100);
                         dust4.scale = 0.55f;
                         dust4.fadeIn = 0.7f;
                         dust4.velocity *= 0.1f * num16;
                         dust4.velocity += velocity;
                     }
                 }
             }
         }
         if (flag2)
         {
             for (int j = 0; j < 200; j++)
             {
                 if (j != whoAmI && Main.npc[j].active && Main.npc[j].type == type && Math.Abs(position.X - Main.npc[j].position.X) + Math.Abs(position.Y - Main.npc[j].position.Y) < (float)width)
                 {
                     if (position.X < Main.npc[j].position.X)
                     {
                         velocity.X -= num13;
                     }
                     else
                     {
                         velocity.X += num13;
                     }
                     if (position.Y < Main.npc[j].position.Y)
                     {
                         velocity.Y -= num13;
                     }
                     else
                     {
                         velocity.Y += num13;
                     }
                 }
             }
         }
         rotation = Math.Abs(velocity.X) * (float)direction * 0.1f;
         spriteDirection = direction;
         Vector2 vector3 = center;
         Vector2 vector4 = targetData.Center - vector3;
         Vector2 vector5 = vector4.SafeNormalize(Vector2.UnitY) * num;
         bool flag4 = Collision.CanHit(base.Center, 1, 1, targetData.Center, 1, 1);
         if (localAI[0] < 0f)
         {
             localAI[0] += 1f;
         }
         if (!flag)
         {
             velocity = (velocity * (num2 - 1f) + vector5) / num2;
             EncourageDespawn(10);
         }
         else if (vector4.Length() > num8 || !flag4)
         {
             velocity = (velocity * (num3 - 1f) + vector5) / num3;
         }
         else if (vector4.Y < num12)
         {
             velocity.Y -= 0.03f;
         }
         else if (localAI[0] >= 0f)
         {
             velocity *= num5;
             if (velocity.Length() < num4 && Main.netMode != 1)
             {
                 localAI[0] += 1f;
                 if (localAI[0] >= (float)num6)
                 {
                     localAI[0] = -num7;
                     direction = (spriteDirection = ((vector5.X > 0f) ? 1 : (-1)));
                     vector5 = vector4 + Utils.RandomVector2(Main.rand, -25f, 25f);
                     vector5.X *= 1f + (float)Main.rand.Next(-20, 21) * 0.005f;
                     vector5.Y *= 1f + (float)Main.rand.Next(-20, 21) * 0.005f;
                     vector5 = vector5.SafeNormalize(Vector2.UnitY) * num11;
                     vector5.X *= 1f + (float)Main.rand.Next(-20, 21) * (1f / 160f);
                     vector5.Y *= 1f + (float)Main.rand.Next(-20, 21) * (1f / 160f);
                     Projectile.NewProjectile(GetSpawnSource_ForProjectile(), vector3, vector5, num10, num9, 0f, Main.myPlayer);
                 }
             }
         }
         if (!flag)
         {
             return;
         }
         bool flag5 = false;
         if (targetData.Center.Y < base.Center.Y)
         {
             flag5 = true;
         }
         if (!flag5)
         {
             Point point = base.Center.ToTileCoordinates();
             if (WorldGen.InWorld(point.X, point.Y, 2))
             {
                 Tile tile = Main.tile[point.X, point.Y];
                 if (tile != null && tile.active() && WorldGen.SolidTile(tile))
                 {
                     flag5 = true;
                 }
             }
         }
         if (flag5)
         {
             velocity.Y -= 0.2f;
             if (velocity.Y < -10f)
             {
                 velocity.Y = -10f;
             }
         }
     }
References Entity.active, Tile.active(), alpha, Collision.CanHit(), NPCAimedTarget.Center, Dust.customData, SoundID.DD2_EtherianPortalSpawnEnemy, Entity.direction, EncourageDespawn(), Dust.fadeIn, GetSpawnSource_ForProjectile(), GetTargetData(), Entity.height, WorldGen.InWorld(), localAI, Main.myPlayer, Main.netMode, netOffset, Dust.NewDustDirect(), Dust.NewDustPerfect(), Projectile.NewProjectile(), UnifiedRandom.Next(), Dust.noGravity, Main.npc, SoundEngine.PlayTrackedSound(), Entity.position, Main.rand, Utils.RandomVector2(), rotation, Dust.scale, WorldGen.SolidTile(), spriteDirection, NPCUtils.TargetClosestOldOnesInvasion(), Main.tile, type, Dust.velocity, Entity.velocity, Entity.whoAmI, and Entity.width.
Referenced by AI().