Terraria: NPC.TryTeleportingCaughtMysticFrog
TryTeleportingCaughtMysticFrog()
bool NPC.TryTeleportingCaughtMysticFrog () inline private
     {
         if (Main.netMode == 1)
         {
             return false;
         }
         if (type != 687)
         {
             return false;
         }
         Vector2 chosenTile = Vector2.Zero;
         Point point = base.Center.ToTileCoordinates();
         if (AI_AttemptToFindTeleportSpot(ref chosenTile, point.X, point.Y, 15, 8))
         {
             Vector2 newPos = new Vector2(chosenTile.X * 16f - (float)(width / 2), chosenTile.Y * 16f - (float)height);
             NetMessage.SendData(23, -1, -1, null, whoAmI);
             Teleport(newPos, 13);
             return true;
         }
         Vector2 vector = base.Center - new Vector2(20f);
         Utils.PoofOfSmoke(vector);
         active = false;
         NetMessage.SendData(23, -1, -1, null, whoAmI);
         NetMessage.SendData(106, -1, -1, null, (int)vector.X, vector.Y);
         return false;
     }
References Main.netMode, Utils.PoofOfSmoke(), and NetMessage.SendData().
Referenced by CatchNPC().