Terraria: NPC.NPCLoot_DropMoney
NPCLoot_DropMoney()
void NPC.NPCLoot_DropMoney (Player closestPlayer) inline private
     {
         float num = 0f;
         float luck = closestPlayer.luck;
         int num2 = 1;
         if (Main.rand.NextFloat() < Math.Abs(luck))
         {
             num2 = 2;
         }
         for (int i = 0; i < num2; i++)
         {
             float num3 = value;
             if (midas)
             {
                 num3 *= 1f + (float)Main.rand.Next(10, 51) * 0.01f;
             }
             num3 *= 1f + (float)Main.rand.Next(-20, 76) * 0.01f;
             if (Main.rand.Next(2) == 0)
             {
                 num3 *= 1f + (float)Main.rand.Next(5, 11) * 0.01f;
             }
             if (Main.rand.Next(4) == 0)
             {
                 num3 *= 1f + (float)Main.rand.Next(10, 21) * 0.01f;
             }
             if (Main.rand.Next(8) == 0)
             {
                 num3 *= 1f + (float)Main.rand.Next(15, 31) * 0.01f;
             }
             if (Main.rand.Next(16) == 0)
             {
                 num3 *= 1f + (float)Main.rand.Next(20, 41) * 0.01f;
             }
             if (Main.rand.Next(32) == 0)
             {
                 num3 *= 1f + (float)Main.rand.Next(25, 51) * 0.01f;
             }
             if (Main.rand.Next(64) == 0)
             {
                 num3 *= 1f + (float)Main.rand.Next(50, 101) * 0.01f;
             }
             if (Main.bloodMoon)
             {
                 num3 *= 1f + (float)Main.rand.Next(101) * 0.01f;
             }
             if (i == 0)
             {
                 num = num3;
             }
             else if (luck < 0f)
             {
                 if (num3 < num)
                 {
                     num = num3;
                 }
             }
             else if (num3 > num)
             {
                 num = num3;
             }
         }
         num += (float)extraValue;
         while ((int)num > 0)
         {
             if (num > 1000000f)
             {
                 int num4 = (int)(num / 1000000f);
                 if (num4 > 50 && Main.rand.Next(5) == 0)
                 {
                     num4 /= Main.rand.Next(3) + 1;
                 }
                 if (Main.rand.Next(5) == 0)
                 {
                     num4 /= Main.rand.Next(3) + 1;
                 }
                 int num5 = num4;
                 while (num5 > 999)
                 {
                     num5 -= 999;
                     Item.NewItem(GetItemSource_Loot(), (int)position.X, (int)position.Y, width, height, 74, 999);
                 }
                 num -= (float)(1000000 * num4);
                 Item.NewItem(GetItemSource_Loot(), (int)position.X, (int)position.Y, width, height, 74, num5);
             }
             else if (num > 10000f)
             {
                 int num6 = (int)(num / 10000f);
                 if (num6 > 50 && Main.rand.Next(5) == 0)
                 {
                     num6 /= Main.rand.Next(3) + 1;
                 }
                 if (Main.rand.Next(5) == 0)
                 {
                     num6 /= Main.rand.Next(3) + 1;
                 }
                 num -= (float)(10000 * num6);
                 Item.NewItem(GetItemSource_Loot(), (int)position.X, (int)position.Y, width, height, 73, num6);
             }
             else if (num > 100f)
             {
                 int num7 = (int)(num / 100f);
                 if (num7 > 50 && Main.rand.Next(5) == 0)
                 {
                     num7 /= Main.rand.Next(3) + 1;
                 }
                 if (Main.rand.Next(5) == 0)
                 {
                     num7 /= Main.rand.Next(3) + 1;
                 }
                 num -= (float)(100 * num7);
                 Item.NewItem(GetItemSource_Loot(), (int)position.X, (int)position.Y, width, height, 72, num7);
             }
             else
             {
                 int num8 = (int)num;
                 if (num8 > 50 && Main.rand.Next(5) == 0)
                 {
                     num8 /= Main.rand.Next(3) + 1;
                 }
                 if (Main.rand.Next(5) == 0)
                 {
                     num8 /= Main.rand.Next(4) + 1;
                 }
                 if (num8 < 1)
                 {
                     num8 = 1;
                 }
                 num -= (float)num8;
                 Item.NewItem(GetItemSource_Loot(), (int)position.X, (int)position.Y, width, height, 71, num8);
             }
         }
     }
References Main.bloodMoon, Player.luck, Item.NewItem(), UnifiedRandom.Next(), and Main.rand.
Referenced by NPCLoot().