Terraria: NPC.BigMimicSummonCheck
BigMimicSummonCheck()
static bool NPC.BigMimicSummonCheck (int x, int y, Player user) inline static
     {
         if (Main.netMode == 1 || !Main.hardMode)
         {
             return false;
         }
         int num = Chest.FindChest(x, y);
         if (num < 0)
         {
             return false;
         }
         int num2 = 0;
         int num3 = 0;
         int num4 = 0;
         for (int i = 0; i < 40; i++)
         {
             ushort num5 = Main.tile[Main.chest[num].x, Main.chest[num].y].type;
             int num6 = Main.tile[Main.chest[num].x, Main.chest[num].y].frameX / 36;
             if (TileID.Sets.BasicChest[num5] && (num5 != 21 || num6 < 5 || num6 > 6) && Main.chest[num].item[i] != null && Main.chest[num].item[i].type > 0)
             {
                 if (Main.chest[num].item[i].type == 3092)
                 {
                     num2 += Main.chest[num].item[i].stack;
                 }
                 else if (Main.chest[num].item[i].type == 3091)
                 {
                     num3 += Main.chest[num].item[i].stack;
                 }
                 else
                 {
                     num4++;
                 }
             }
         }
         if (num4 == 0 && num2 + num3 == 1)
         {
             if (num2 != 1)
             {
                 _ = 1;
             }
             if (TileID.Sets.BasicChest[Main.tile[x, y].type])
             {
                 if (Main.tile[x, y].frameX % 36 != 0)
                 {
                     x--;
                 }
                 if (Main.tile[x, y].frameY % 36 != 0)
                 {
                     y--;
                 }
                 int number = Chest.FindChest(x, y);
                 for (int j = 0; j < 40; j++)
                 {
                     Main.chest[num].item[j] = new Item();
                 }
                 Chest.DestroyChest(x, y);
                 for (int k = x; k <= x + 1; k++)
                 {
                     for (int l = y; l <= y + 1; l++)
                     {
                         if (TileID.Sets.BasicChest[Main.tile[k, l].type])
{
                             Main.tile[k, l].ClearTile();
                         }
                     }
                 }
                 int number2 = 1;
                 if (Main.tile[x, y].type == 467)
                 {
                     number2 = 5;
                 }
                 NetMessage.SendData(34, -1, -1, null, number2, x, y, 0f, number);
                 NetMessage.SendTileSquare(-1, x, y, 3);
             }
             int num7 = 475;
             if (num3 == 1)
             {
                 num7 = ((!WorldGen.crimson) ? 473 : 474);
             }
             int num8 = NewNPC(user.GetNPCSource_TileInteraction(x, y), x * 16 + 16, y * 16 + 32, num7);
             Main.npc[num8].whoAmI = num8;
             NetMessage.SendData(23, -1, -1, null, num8);
             Main.npc[num8].BigMimicSpawnSmoke();
         }
         return false;
     }
References TileID.Sets.BasicChest, BigMimicSpawnSmoke(), Main.chest, Tile.ClearTile(), WorldGen.crimson, Chest.DestroyChest(), Chest.FindChest(), Tile.frameX, Tile.frameY, Player.GetNPCSource_TileInteraction(), Main.hardMode, Chest.item, Main.netMode, NewNPC(), Main.npc, NetMessage.SendData(), NetMessage.SendTileSquare(), Item.stack, Main.tile, Item.type, Tile.type, Entity.whoAmI, Chest.x, and Chest.y.
Referenced by Player.Update().