Terraria: NPC.CheckProgressPumpkinMoon
CheckProgressPumpkinMoon()
void NPC.CheckProgressPumpkinMoon () inline private
     {
         if (!Main.pumpkinMoon)
         {
             return;
         }
         int num = 0;
         NetworkText networkText = NetworkText.Empty;
         num = MoonEventRequiredPointsPerWaveLookup[waveNumber];
         switch (waveNumber)
         {
         case 1:
             networkText = Lang.GetInvasionWaveText(2, 326, 305);
             break;
         case 2:
             networkText = Lang.GetInvasionWaveText(3, 329, 326);
             break;
         case 3:
             networkText = Lang.GetInvasionWaveText(4, 330, 326, 305);
             break;
         case 4:
             networkText = Lang.GetInvasionWaveText(5, 315, 329);
             break;
         case 5:
             networkText = Lang.GetInvasionWaveText(6, 325, 326, 305);
             break;
         case 6:
             networkText = Lang.GetInvasionWaveText(7, 325, 330, 329);
             break;
         case 7:
             networkText = Lang.GetInvasionWaveText(8, 315, 330, 329);
             break;
         case 8:
             networkText = Lang.GetInvasionWaveText(9, 325, 330, 329, 326, 305);
             break;
         case 9:
             networkText = Lang.GetInvasionWaveText(10, 327, 329, 326);
             break;
         case 10:
             networkText = Lang.GetInvasionWaveText(11, 325, 330, 326);
             break;
         case 11:
             networkText = Lang.GetInvasionWaveText(12, 327, 330);
             break;
         case 12:
             networkText = Lang.GetInvasionWaveText(13, 325, 315, 330, 329, 326);
             break;
         case 13:
             networkText = Lang.GetInvasionWaveText(14, 327, 325, 315, 330, 329, 326, 305);
             break;
         case 14:
             networkText = Lang.GetInvasionWaveText(15, 327, 325, 330, 326, 305);
             break;
         case 15:
             networkText = Lang.GetInvasionWaveText(16, 327, 315, 330, 329, 326);
             break;
         case 16:
             networkText = Lang.GetInvasionWaveText(17, 327, 325, 315, 330, 329);
             break;
         case 17:
             networkText = Lang.GetInvasionWaveText(18, 327, 325, 315, 330);
             break;
         case 18:
             networkText = Lang.GetInvasionWaveText(19, 327, 325, 315);
             break;
         case 19:
             networkText = Lang.GetInvasionWaveText(-1, 327, 325, 315);
             break;
         }
         float num2 = 0f;
         switch (type)
         {
         case 305:
         case 306:
         case 307:
         case 308:
         case 309:
         case 310:
         case 311:
         case 312:
         case 313:
         case 314:
             num2 = 1f;
             break;
         case 315:
             num2 = 50f;
             break;
         case 325:
             num2 = 75f;
             break;
         case 326:
             num2 = 2f;
             break;
         case 327:
             num2 = 150f;
             break;
         case 329:
             num2 = 5f;
             break;
         case 330:
             num2 = 10f;
             break;
         }
         num2 *= GetMoonEventPointScalar();
         float num3 = waveKills;
         waveKills += num2;
         totalInvasionPoints += num2;
         if (waveKills >= (float)num && num != 0)
         {
             waveKills = 0f;
             waveNumber++;
             num = MoonEventRequiredPointsPerWaveLookup[waveNumber];
             if (networkText != NetworkText.Empty)
             {
                 if (Main.netMode == 0)
                 {
                     Main.NewText(networkText.ToString(), 175, 75);
                 }
                 else if (Main.netMode == 2)
                 {
                     ChatHelper.BroadcastChatMessage(networkText, new Color(175, 75, 255));
                 }
                 if (waveNumber == 15)
                 {
                     AchievementsHelper.NotifyProgressionEvent(15);
                 }
             }
         }
         if (waveKills != num3 && num2 != 0f)
         {
             if (Main.netMode != 1)
             {
                 Main.ReportInvasionProgress((int)waveKills, num, 2, waveNumber);
             }
             if (Main.netMode == 2)
             {
                 NetMessage.SendData(78, -1, -1, null, Main.invasionProgress, Main.invasionProgressMax, 2f, waveNumber);
             }
         }
     }
References ChatHelper.BroadcastChatMessage(), Color, NetworkText.Empty, Lang.GetInvasionWaveText(), GetMoonEventPointScalar(), Main.invasionProgress, Main.invasionProgressMax, MoonEventRequiredPointsPerWaveLookup, Main.netMode, Main.NewText(), AchievementsHelper.NotifyProgressionEvent(), Main.pumpkinMoon, Main.ReportInvasionProgress(), NetMessage.SendData(), NetworkText.ToString(), totalInvasionPoints, type, waveKills, and waveNumber.
Referenced by checkDead().