Terraria: NPC.OnGameEventClearedForTheFirstTime
OnGameEventClearedForTheFirstTime()
static void NPC.OnGameEventClearedForTheFirstTime (int gameEventId) inline static
     {
         switch (gameEventId)
         {
         default:
             LanternNight.NextNightIsLanternNight = true;
             break;
         case 10:
             LanternNight.NextNightIsLanternNight = true;
             CreditsRollEvent.TryStartingCreditsRoll();
             break;
         case 16:
         case 17:
         case 18:
             LanternNight.NextNightIsLanternNight = true;
             if (Main.netMode != 1 && Main.hardMode && downedMechBoss1 && downedMechBoss2 && downedMechBoss3)
             {
                 WorldGen.GeneratePlanteraBulbOnAllMechsDefeated();
             }
             break;
         case 4:
         case 21:
         case 22:
             break;
         }
     }
References downedMechBoss1, downedMechBoss2, downedMechBoss3, WorldGen.GeneratePlanteraBulbOnAllMechsDefeated(), Main.hardMode, Main.netMode, LanternNight.NextNightIsLanternNight, and CreditsRollEvent.TryStartingCreditsRoll().
Referenced by SetEventFlagCleared().