Terraria: NPC.AI_121_QueenSlime_FlyMovement
AI_121_QueenSlime_FlyMovement()
void NPC.AI_121_QueenSlime_FlyMovement () inline private
     {
         noTileCollide = true;
         noGravity = true;
         float num = 12f;
         float num2 = 0.085f;
         float num3 = 250f;
         TargetClosest();
         Vector2 desiredVelocity = base.Center;
         if (timeLeft > 10)
         {
             if (!Collision.CanHit(this, Main.player[target]))
             {
                 bool flag = false;
                 Vector2 center = Main.player[target].Center;
                 for (int i = 0; i < 16; i++)
                 {
                     float num4 = 16 * i;
                     Point point = (center + new Vector2(0f, 0f - num4)).ToTileCoordinates();
                     if (WorldGen.SolidOrSlopedTile(point.X, point.Y))
                     {
                         desiredVelocity = center + new Vector2(0f, 0f - num4 + 16f) - base.Center;
                         flag = true;
                         break;
                     }
                 }
                 if (!flag)
                 {
                     desiredVelocity = center - base.Center;
                 }
             }
             else
             {
                 desiredVelocity = Main.player[target].Center + new Vector2(0f, 0f - num3) - base.Center;
             }
         }
         else
         {
             desiredVelocity = base.Center + new Vector2(500f * (float)direction, 0f - num3) - base.Center;
         }
         float num5 = desiredVelocity.Length();
         if (Math.Abs(desiredVelocity.X) < 40f)
         {
             desiredVelocity.X = velocity.X;
         }
         float num6 = num - 2f;
         if (num5 > 100f && ((velocity.X < 0f - num6 && desiredVelocity.X > 0f) || (velocity.X > num6 && desiredVelocity.X < 0f)))
         {
             num2 *= 2f;
         }
         if (num5 < 40f)
         {
             desiredVelocity = velocity;
         }
         else if (num5 < 80f)
         {
             desiredVelocity.Normalize();
             desiredVelocity *= num * 0.65f;
         }
         else
         {
             desiredVelocity.Normalize();
             desiredVelocity *= num;
         }
         SimpleFlyMovement(desiredVelocity, num2);
         rotation = velocity.X * 0.1f;
         if (rotation > 0.5f)
         {
             rotation = 0.5f;
         }
         if (rotation < -0.5f)
         {
             rotation = -0.5f;
         }
     }
References Collision.CanHit(), Entity.Center, Entity.direction, noGravity, noTileCollide, Main.player, rotation, SimpleFlyMovement(), WorldGen.SolidOrSlopedTile(), target, TargetClosest(), timeLeft, and Entity.velocity.
Referenced by AI_121_QueenSlime().