Terraria: NPC.BeHurtByOtherNPC
BeHurtByOtherNPC()
void NPC.BeHurtByOtherNPC (int npcIndex, NPC thatNPC) inline private
     {
         int num = 30;
         if (type == 548)
         {
             num = 20;
         }
         int num2 = Main.DamageVar(thatNPC.damage);
         int num3 = 6;
         int num4 = ((!(thatNPC.Center.X > base.Center.X)) ? 1 : (-1));
         double num5 = StrikeNPCNoInteraction(num2, num3, num4);
         if (Main.netMode != 0)
         {
             NetMessage.SendData(28, -1, -1, null, whoAmI, num2, num3, num4);
         }
         netUpdate = true;
         immune[255] = num;
         if (dryadWard)
         {
             num2 = (int)num5 / 3;
             num3 = 6;
             num4 *= -1;
             thatNPC.StrikeNPCNoInteraction(num2, num3, num4);
             if (Main.netMode != 0)
             {
                 NetMessage.SendData(28, -1, -1, null, npcIndex, num2, num3, num4);
             }
             thatNPC.netUpdate = true;
             thatNPC.immune[255] = num;
         }
         if (NPCID.Sets.HurtingBees[thatNPC.type])
         {
             num2 = damage;
             num3 = 6;
             num4 *= -1;
             thatNPC.StrikeNPCNoInteraction(num2, num3, num4);
             if (Main.netMode != 0)
             {
                 NetMessage.SendData(28, -1, -1, null, npcIndex, num2, num3, num4);
             }
             thatNPC.netUpdate = true;
             thatNPC.immune[255] = num;
         }
     }
References Entity.Center, damage, Main.DamageVar(), NPCID.Sets.HurtingBees, immune, Main.netMode, netUpdate, NetMessage.SendData(), StrikeNPCNoInteraction(), and type.