Terraria: NPC.AI_109_DarkMage
AI_109_DarkMage()
void NPC.AI_109_DarkMage () inline private
     {
         //IL_01c8: Unknown result type (might be due to invalid IL or missing references)
         //IL_0661: Unknown result type (might be due to invalid IL or missing references)
         //IL_034a: Unknown result type (might be due to invalid IL or missing references)
         bool flag = false;
         bool flag2 = false;
         bool flag3 = true;
         bool flag4 = false;
         int num = 4;
         int num2 = 3;
         int num3 = 0;
         float num4 = 0.2f;
         float num5 = 2f;
         float num6 = -0.2f;
         float num7 = -4f;
         bool flag5 = true;
         float num8 = 2f;
         float num9 = 0.1f;
         float num10 = 1f;
         float num11 = 0.04f;
         bool flag6 = false;
         float num12 = 0.96f;
         bool flag7 = true;
         NPCAimedTarget targetData = GetTargetData();
         if (type == 564 || type == 565)
         {
             flag5 = false;
             rotation = velocity.X * 0.04f;
             spriteDirection = ((direction > 0) ? 1 : (-1));
             num3 = 2;
             num6 = -0.05f;
             num7 = -0.4f;
             num4 = 0.05f;
             num5 = 0.2f;
             num10 = 0.5f;
             num11 = 0.02f;
             num8 = 0.5f;
             num9 = 0.1f;
             localAI[2] = 0f;
             DelegateMethods.v3_1 = new Vector3(0.3f, 0.05f, 0.45f) * 1.5f;
             Utils.PlotTileLine(base.Top, base.Bottom, width, DelegateMethods.CastLightOpen);
             if (ai[0] < 0f)
             {
                 ai[0] = MathHelper.Min(ai[0] + 1f, 0f);
             }
             if (ai[0] > 0f)
             {
                 flag7 = false;
                 flag6 = true;
                 num12 = 0.9f;
                 ai[0] -= 1f;
                 if (ai[0] == 80f && ai[1] == 2f)
                 {
                     SoundEngine.PlayTrackedSound(SoundID.DD2_DarkMageSummonSkeleton, base.Center);
                 }
                 if (ai[1] == 2f && ai[0] == 64f && Main.netMode != 1)
                 {
                     Projectile.NewProjectile(GetSpawnSource_ForProjectile(), base.Center + new Vector2(direction * 24, -40f), Vector2.Zero, 673, 0, 0f, Main.myPlayer);
                     DD2Event.RaiseGoblins(this, base.Center);
                 }
                 if (ai[1] == 0f && ai[0] == 32f)
                 {
                     Vector2 vector = (targetData.Center - (base.Center + new Vector2(direction * 10, -16f))).SafeNormalize(Vector2.UnitY) * 14f;
                     direction = ((vector.X > 0f) ? 1 : (-1));
                     if (Main.netMode != 1)
                     {
                         Projectile.NewProjectile(GetSpawnSource_ForProjectile(), base.Center + new Vector2(direction * 10, -16f), vector, 675, 40, 0f, Main.myPlayer);
                     }
                 }
                 if (ai[0] == 126f && ai[1] == 1f)
                 {
                     SoundEngine.PlayTrackedSound(SoundID.DD2_DarkMageCastHeal, base.Center);
                 }
                 if (ai[1] == 1f && Main.netMode != 1 && (ai[0] == 40f || ai[0] == 48f || ai[0] == 56f) && WorldUtils.Find(new Vector2(base.Center.X + (float)(direction * 240), base.Center.Y).ToTileCoordinates(), Searches.Chain(new Searches.Down(50), new Terraria.WorldBuilding.Conditions.IsSolid()), out var result))
                 {
                     Projectile.NewProjectile(GetSpawnSource_ForProjectile(), result.ToWorldCoordinates(8f, 0f), Vector2.Zero, 674, 0, 0f, Main.myPlayer);
                 }
                 if (ai[0] <= 0f)
                 {
                     float num13 = ai[1];
                     ai[1] += 1f;
                     if (ai[1] >= 3f)
                     {
                         ai[1] = 0f;
                     }
                     ai[0] = -120f;
                     if (num13 == 0f)
                     {
                         ai[0] = -20f;
                     }
                     netUpdate = true;
                 }
             }
             if (ai[0] == 0f && localAI[3] >= 60f)
             {
                 bool flag8 = false;
                 Vector2 minimum = base.Center + new Vector2(-600f, -200f);
                 Vector2 maximum = base.Center + new Vector2(600f, 200f);
                 int num14 = 0;
                 for (int i = 0; i < 200; i++)
                 {
                     NPC nPC = Main.npc[i];
                     if (nPC.active && nPC.lifeMax != nPC.life && nPC.Center.Between(minimum, maximum) && ++num14 >= 2)
                     {
                         flag8 = true;
                         break;
                     }
                 }
                 if (!flag8)
                 {
                     ai[1] = 2f;
                 }
                 if (ai[1] == 2f && !DD2Event.CanRaiseGoblinsHere(base.Center))
                 {
                     ai[1] = 0f;
                 }
                 bool flag9 = true;
                 if (ai[1] == 0f && (Distance(targetData.Center) >= 1000f || !Collision.CanHitLine(base.Center, 0, 0, targetData.Center, 0, 0)))
                 {
                     flag9 = false;
                 }
                 if (flag9)
                 {
                     switch ((int)ai[1])
                     {
                     case 0:
                         ai[0] = 97f;
                         break;
                     case 1:
                         ai[0] = 127f;
                         break;
                     case 2:
                         ai[0] = 183f;
                         break;
                     }
                     netUpdate = true;
                     flag6 = true;
                 }
             }
             if (localAI[3] == 0f)
             {
                 alpha = 255;
             }
             if (localAI[3] == 30f)
             {
                 SoundEngine.PlayTrackedSound(SoundID.DD2_EtherianPortalSpawnEnemy, base.Center);
             }
             if (localAI[3] < 60f)
             {
                 localAI[3] += 1f;
                 alpha -= 5;
                 if (alpha < 0)
                 {
                     alpha = 0;
                 }
                 int num15 = (int)localAI[3] / 10;
                 float num16 = base.Size.Length() / 2f;
                 num16 /= 20f;
                 int maxValue = 5;
                 if (type == 576 || type == 577)
                 {
                     maxValue = 1;
                 }
                 for (int j = 0; j < num15; j++)
                 {
                     if (Main.rand.Next(maxValue) == 0)
                     {
                         Dust dust = Dust.NewDustDirect(position, width, height, 27, velocity.X * 1f, 0f, 100);
                         dust.scale = 0.55f;
                         dust.fadeIn = 0.7f;
                         dust.velocity *= 0.1f * num16;
                         dust.velocity += velocity;
                     }
                 }
             }
         }
         if (justHit)
         {
             localAI[2] = 0f;
         }
         if (!flag2)
         {
             if (localAI[2] >= 0f)
             {
                 float num17 = 16f;
                 bool flag10 = false;
                 bool flag11 = false;
                 if (position.X > localAI[0] - num17 && position.X < localAI[0] + num17)
                 {
                     flag10 = true;
                 }
                 else if ((velocity.X < 0f && direction > 0) || (velocity.X > 0f && direction < 0))
                 {
                     flag10 = true;
                     num17 += 24f;
                 }
                 if (position.Y > localAI[1] - num17 && position.Y < localAI[1] + num17)
                 {
                     flag11 = true;
                 }
                 if (flag10 && flag11)
                 {
                     localAI[2] += 1f;
                     if (localAI[2] >= 30f && num17 == 16f)
                     {
                         flag = true;
                     }
                     if (localAI[2] >= 60f)
                     {
                         localAI[2] = -180f;
                         direction *= -1;
                         velocity.X *= -1f;
                         collideX = false;
                     }
                 }
                 else
                 {
                     localAI[0] = position.X;
                     localAI[1] = position.Y;
                     localAI[2] = 0f;
                 }
                 if (flag7)
                 {
                     NPCUtils.TargetClosestOldOnesInvasion(this);
                 }
             }
             else
             {
                 localAI[2] += 1f;
                 direction = ((targetData.Center.X > base.Center.X) ? 1 : (-1));
             }
         }
         int num18 = (int)((position.X + (float)(width / 2)) / 16f) + direction * 2;
         int num19 = (int)((position.Y + (float)height) / 16f);
         int num20 = (int)base.Bottom.Y / 16;
         int num21 = (int)base.Bottom.X / 16;
         if (flag6)
         {
             velocity *= num12;
             return;
         }
         for (int k = num19; k < num19 + num; k++)
         {
             if (Main.tile[num18, k] == null)
             {
                 Main.tile[num18, k] = new Tile();
             }
             if ((Main.tile[num18, k].nactive() && Main.tileSolid[Main.tile[num18, k].type]) || Main.tile[num18, k].liquid > 0)
             {
                 if (k <= num19 + 1)
                 {
                     flag4 = true;
                 }
                 flag3 = false;
                 break;
             }
         }
         for (int l = num20; l < num20 + num3; l++)
         {
             if (Main.tile[num21, l] == null)
             {
                 Main.tile[num21, l] = new Tile();
             }
             if ((Main.tile[num21, l].nactive() && Main.tileSolid[Main.tile[num21, l].type]) || Main.tile[num21, l].liquid > 0)
             {
                 flag4 = true;
                 flag3 = false;
                 break;
             }
         }
         if (flag5)
         {
             for (int m = num19 - num2; m < num19; m++)
             {
                 if (Main.tile[num18, m] == null)
                 {
                     Main.tile[num18, m] = new Tile();
                 }
                 if ((Main.tile[num18, m].nactive() && Main.tileSolid[Main.tile[num18, m].type]) || Main.tile[num18, m].liquid > 0)
                 {
                     flag4 = false;
                     flag = true;
                     break;
                 }
             }
         }
         if (flag)
         {
             flag4 = false;
             flag3 = true;
         }
         if (flag3)
         {
             velocity.Y += num4;
             if (velocity.Y > num5)
             {
                 velocity.Y = num5;
             }
         }
         else
         {
             if ((directionY < 0 && velocity.Y > 0f) || flag4)
             {
                 velocity.Y += num6;
             }
             if (velocity.Y < num7)
             {
                 velocity.Y = num7;
             }
         }
         if (collideX)
         {
             velocity.X = oldVelocity.X * -0.4f;
             if (direction == -1 && velocity.X > 0f && velocity.X < 1f)
             {
                 velocity.X = 1f;
             }
             if (direction == 1 && velocity.X < 0f && velocity.X > -1f)
             {
                 velocity.X = -1f;
             }
         }
         if (collideY)
         {
             velocity.Y = oldVelocity.Y * -0.25f;
             if (velocity.Y > 0f && velocity.Y < 1f)
             {
                 velocity.Y = 1f;
             }
             if (velocity.Y < 0f && velocity.Y > -1f)
             {
                 velocity.Y = -1f;
             }
         }
         if (direction == -1 && velocity.X > 0f - num8)
         {
             velocity.X -= num9;
             if (velocity.X > num8)
             {
                 velocity.X -= num9;
             }
             else if (velocity.X > 0f)
             {
                 velocity.X += num9 / 2f;
             }
             if (velocity.X < 0f - num8)
             {
                 velocity.X = 0f - num8;
             }
         }
         else if (direction == 1 && velocity.X < num8)
         {
             velocity.X += num9;
             if (velocity.X < 0f - num8)
             {
                 velocity.X += num9;
             }
             else if (velocity.X < 0f)
             {
                 velocity.X -= num9 / 2f;
             }
             if (velocity.X > num8)
             {
                 velocity.X = num8;
             }
         }
         if (directionY == -1 && velocity.Y > 0f - num10)
         {
             velocity.Y -= num11;
             if (velocity.Y > num10)
             {
                 velocity.Y -= num11 * 1.25f;
             }
             else if (velocity.Y > 0f)
             {
                 velocity.Y += num11 * 0.75f;
             }
             if (velocity.Y < 0f - num10)
             {
                 velocity.Y = 0f - num8;
             }
         }
         else if (directionY == 1 && velocity.Y < num10)
         {
             velocity.Y += num11;
             if (velocity.Y < 0f - num10)
             {
                 velocity.Y += num11 * 1.25f;
             }
             else if (velocity.Y < 0f)
             {
                 velocity.Y -= num11 * 0.75f;
             }
             if (velocity.Y > num10)
             {
                 velocity.Y = num10;
             }
         }
     }
References Entity.active, ai, alpha, Collision.CanHitLine(), DD2Event.CanRaiseGoblinsHere(), DelegateMethods.CastLightOpen(), NPCAimedTarget.Center, Entity.Center, Searches.Chain(), collideX, collideY, GenSearch.Conditions(), SoundID.DD2_DarkMageCastHeal, SoundID.DD2_DarkMageSummonSkeleton, SoundID.DD2_EtherianPortalSpawnEnemy, Entity.direction, directionY, Entity.Distance(), Dust.fadeIn, WorldUtils.Find(), GetSpawnSource_ForProjectile(), GetTargetData(), Entity.height, justHit, life, lifeMax, Tile.liquid, localAI, Main.myPlayer, Tile.nactive(), Main.netMode, netUpdate, Dust.NewDustDirect(), Projectile.NewProjectile(), UnifiedRandom.Next(), Main.npc, Entity.oldVelocity, SoundEngine.PlayTrackedSound(), Utils.PlotTileLine(), Entity.position, DD2Event.RaiseGoblins(), Main.rand, rotation, Dust.scale, spriteDirection, NPCUtils.TargetClosestOldOnesInvasion(), Tile, Main.tile, Main.tileSolid, type, Tile.type, DelegateMethods.v3_1, Dust.velocity, Entity.velocity, and Entity.width.
Referenced by AI().