Terraria: NPC.CountKillForBannersAndDropThem
CountKillForBannersAndDropThem()
void NPC.CountKillForBannersAndDropThem () inline private
     {
         int num = Item.NPCtoBanner(BannerID());
         if (num <= 0 || ExcludedFromDeathTally())
         {
             return;
         }
         killCount[num]++;
         if (Main.netMode == 2)
         {
             NetMessage.SendData(83, -1, -1, null, num);
         }
         int num2 = ItemID.Sets.KillsToBanner[Item.BannerToItem(num)];
         if (killCount[num] % num2 == 0 && num > 0)
         {
             int num3 = Item.BannerToNPC(num);
             int num4 = lastInteraction;
             if (!Main.player[num4].active || Main.player[num4].dead)
             {
                 num4 = FindClosestPlayer();
             }
             NetworkText networkText = NetworkText.FromKey("Game.EnemiesDefeatedAnnouncement", killCount[num], NetworkText.FromKey(Lang.GetNPCName(num3).Key));
             if (num4 >= 0 && num4 < 255)
             {
                 networkText = NetworkText.FromKey("Game.EnemiesDefeatedByAnnouncement", Main.player[num4].name, killCount[num], NetworkText.FromKey(Lang.GetNPCName(num3).Key));
             }
             if (Main.netMode == 0)
             {
                 Main.NewText(networkText.ToString(), 250, 250, 0);
             }
             else if (Main.netMode == 2)
             {
                 ChatHelper.BroadcastChatMessage(networkText, new Color(250, 250, 0));
             }
             int num5 = Item.BannerToItem(num);
             Vector2 vector = position;
             if (num4 >= 0 && num4 < 255)
             {
                 vector = Main.player[num4].position;
             }
             Item.NewItem(GetItemSource_Loot(), (int)vector.X, (int)vector.Y, width, height, num5);
         }
     }
References Entity.active, Item.BannerToItem(), Item.BannerToNPC(), ChatHelper.BroadcastChatMessage(), Color, Player.dead, NetworkText.FromKey(), Lang.GetNPCName(), LocalizedText.Key, ItemID.Sets.KillsToBanner, Player.name, Main.netMode, Item.NewItem(), Main.NewText(), Item.NPCtoBanner(), Main.player, Entity.position, NetMessage.SendData(), and NetworkText.ToString().
Referenced by AI_003_Fighters(), and NPCLoot().