Terraria: NPC.GetChat
GetChat()
string NPC.GetChat () inline
     {
         PreventJojaColaDialog = false;
         RerollDryadText = 0;
         Recipe.FindRecipes();
         bool flag = false;
         bool flag2 = false;
         bool flag3 = false;
         bool flag4 = false;
         bool flag5 = false;
         bool flag6 = false;
         bool flag7 = false;
         bool flag8 = false;
         bool flag9 = false;
         bool flag10 = false;
         bool flag11 = false;
         bool flag12 = false;
         bool flag13 = false;
         bool flag14 = false;
         bool flag15 = false;
         bool flag16 = false;
         bool flag17 = false;
         object obj = Lang.CreateDialogSubstitutionObject(this);
         for (int i = 0; i < 200; i++)
         {
             if (Main.npc[i].active)
             {
                 if (Main.npc[i].type == 17)
                 {
                     flag = true;
                 }
                 else if (Main.npc[i].type == 18)
                 {
                     flag2 = true;
                 }
                 else if (Main.npc[i].type == 19)
                 {
                     flag3 = true;
                 }
                 else if (Main.npc[i].type == 20)
                 {
                     flag4 = true;
                 }
                 else if (Main.npc[i].type == 37)
                 {
                     flag5 = true;
                 }
                 else if (Main.npc[i].type == 38)
                 {
                     flag6 = true;
                 }
                 else if (Main.npc[i].type == 124)
                 {
                     flag7 = true;
                 }
                 else if (Main.npc[i].type == 107)
                 {
                     flag8 = true;
                 }
                 else if (Main.npc[i].type == 54)
                 {
                     flag9 = true;
                 }
                 else if (Main.npc[i].type == 160)
                 {
                     flag10 = true;
                 }
                 else if (Main.npc[i].type == 178)
                 {
                     flag11 = true;
                 }
                 else if (Main.npc[i].type == 229)
                 {
                     flag12 = true;
                 }
                 else if (Main.npc[i].type == 209)
                 {
                     flag13 = true;
                 }
                 else if (Main.npc[i].type == 208)
                 {
                     flag14 = true;
                 }
                 else if (Main.npc[i].type == 353)
                 {
                     flag15 = true;
                 }
                 else if (Main.npc[i].type == 22)
                 {
                     flag16 = true;
                 }
                 else if (Main.npc[i].type == 441)
                 {
                     flag17 = true;
                 }
             }
         }
         string result = "";
         string specialEventText = "";
         if (type == 17)
         {
             result = (HasSpecialEventText("Merchant", out specialEventText) ? specialEventText : ((!downedBoss1 && Main.rand.Next(3) == 0) ? ((Main.player[Main.myPlayer].statLifeMax < 200) ? Lang.dialog(1) : ((Main.player[Main.myPlayer].statDefense > 10) ? Lang.dialog(3) : Lang.dialog(2))) : (Main.dayTime ? ((Main.time < 16200.0) ? (Main.rand.Next(3) switch
             {
                 0 => Lang.dialog(4),
                 1 => Lang.dialog(5),
                 _ => Lang.dialog(6),
             }) : ((Main.time > 37800.0) ? (Main.rand.Next(3) switch
             {
                 0 => Lang.dialog(7),
                 1 => Lang.dialog(8),
                 _ => Lang.dialog(9),
             }) : (Main.rand.Next(3) switch
             {
                 0 => Lang.dialog(10),
                 1 => Lang.dialog(11),
                 _ => Lang.dialog(12),
             }))) : (Main.bloodMoon ? ((flag2 && flag7 && Main.rand.Next(3) == 0) ? Lang.dialog(13) : (Main.rand.Next(4) switch
             {
                 0 => Lang.dialog(14),
                 1 => Lang.dialog(15),
                 2 => Lang.dialog(16),
                 _ => Lang.dialog(17),
             })) : ((Main.time < 9720.0) ? ((Main.rand.Next(2) != 0) ? Lang.dialog(19) : Lang.dialog(18)) : ((Main.time > 22680.0) ? ((Main.rand.Next(2) != 0) ? Lang.dialog(21) : Lang.dialog(20)) : (Main.rand.Next(3) switch
             {
                 0 => Lang.dialog(22),
                 1 => Lang.dialog(23),
                 _ => Lang.dialog(24),
             })))))));
         }
         else if (type == 18)
         {
             if (HasSpecialEventText("Nurse", out specialEventText))
             {
                 result = specialEventText;
             }
             else if (Main.bloodMoon)
             {
                 result = (((double)Main.player[Main.myPlayer].statLife < (double)Main.player[Main.myPlayer].statLifeMax2 * 0.66) ? (Main.rand.Next(3) switch
                 {
                     0 => Lang.dialog(25),
                     1 => Lang.dialog(26),
                     _ => Lang.dialog(27),
                 }) : (Main.rand.Next(4) switch
                 {
                     0 => Lang.dialog(28),
                     1 => Lang.dialog(29),
                     2 => Lang.dialog(30),
                     _ => Lang.dialog(31),
                 }));
             }
             else if (Main.rand.Next(5) == 0 && Main.LocalPlayer.numberOfDeathsPVE > 1)
             {
                 int numberOfDeathsPVE = Main.LocalPlayer.numberOfDeathsPVE;
                 int num = 25;
                 int num2 = 100;
                 string text = "Low";
                 if (numberOfDeathsPVE >= num2)
                 {
                     text = "High";
                 }
                 else if (numberOfDeathsPVE >= num)
                 {
                     text = "Medium";
                 }
                 result = Language.GetTextValueWith("NurseSpecialText.DeathCount" + text, obj);
             }
             else if (Main.rand.Next(3) == 0 && !downedBoss3)
             {
                 result = Lang.dialog(32);
             }
             else if (flag6 && Main.rand.Next(4) == 0)
             {
                 result = Lang.dialog(33);
             }
             else if (flag3 && Main.rand.Next(4) == 0)
             {
                 result = Lang.dialog(34);
             }
             else if (flag16 && Main.rand.Next(4) == 0)
             {
                 result = Lang.dialog(35);
             }
             else if ((double)Main.player[Main.myPlayer].statLife < (double)Main.player[Main.myPlayer].statLifeMax2 * 0.33)
             {
                 result = Main.rand.Next(5) switch
                 {
                     0 => Lang.dialog(36),
                     1 => Lang.dialog(37),
                     2 => Lang.dialog(38),
                     3 => Lang.dialog(39),
                     _ => Lang.dialog(40),
                 };
             }
             else if ((double)Main.player[Main.myPlayer].statLife < (double)Main.player[Main.myPlayer].statLifeMax2 * 0.66)
             {
                 result = Main.rand.Next(7) switch
                 {
                     0 => Lang.dialog(41),
                     1 => Lang.dialog(42),
                     2 => Lang.dialog(43),
                     3 => Lang.dialog(44),
                     4 => Lang.dialog(45),
                     5 => Lang.dialog(46),
                     _ => Lang.dialog(47),
                 };
             }
             else
             {
                 LocalizedText[] array = Language.FindAll(Lang.CreateDialogFilter("NurseChatter.", obj));
                 int num3 = Main.rand.Next(4 + array.Length);
                 result = ((num3 >= 4) ? array[num3 - 4].FormatWith(obj) : (num3 switch
                 {
                     0 => Lang.dialog(48),
                     1 => Lang.dialog(49),
                     2 => Lang.dialog(50),
                     _ => Lang.dialog(51),
                 }));
             }
         }
         else if (type == 19)
         {
             result = (HasSpecialEventText("ArmsDealer", out specialEventText) ? specialEventText : ((flag16 && downedBoss3 && !Main.hardMode) ? Lang.dialog(58) : ((flag2 && Main.rand.Next(5) == 0) ? Lang.dialog(59) : ((flag2 && Main.rand.Next(5) == 0) ? Lang.dialog(60) : ((flag4 && Main.rand.Next(5) == 0) ? Lang.dialog(61) : ((flag6 && Main.rand.Next(5) == 0) ? Lang.dialog(62) : ((flag6 && Main.rand.Next(5) == 0) ? Lang.dialog(63) : (Main.bloodMoon ? ((Main.rand.Next(2) != 0) ? Lang.dialog(65) : Lang.dialog(64)) : (Main.rand.Next(3) switch
             {
                 0 => Lang.dialog(66),
                 1 => Lang.dialog(67),
                 _ => Lang.dialog(68),
             })))))))));
         }
         else if (type == 20)
         {
             result = (HasSpecialEventText("Dryad", out specialEventText) ? specialEventText : ((DD2Event.DownedInvasionT1 && Main.rand.Next(6) == 0) ? ((!DD2Event.DownedInvasionT2) ? Language.GetTextValueWith("DryadSpecialText.AfterDD2Tier1", obj) : Language.GetTextValueWith("DryadSpecialText.AfterDD2Tier2", obj)) : ((!downedBoss2 && Main.rand.Next(3) == 0) ? ((!WorldGen.crimson) ? Lang.dialog(69) : Lang.dialog(332)) : ((flag3 && Main.rand.Next(6) == 0) ? Lang.dialog(70) : ((flag && Main.rand.Next(6) == 0) ? Lang.dialog(71) : ((flag5 && Main.rand.Next(6) == 0) ? Lang.dialog(72) : ((flag10 && Main.rand.Next(6) == 0) ? Lang.dialog(238) : (Main.bloodMoon ? (Main.rand.Next(4) switch
             {
                 0 => Lang.dialog(73),
                 1 => Lang.dialog(74),
                 2 => Lang.dialog(75),
                 _ => Lang.dialog(76),
             }) : (Main.rand.Next(5) switch
             {
                 0 => (!WorldGen.crimson) ? Lang.dialog(77) : Lang.dialog(333),
                 1 => Lang.dialog(78),
                 2 => Lang.dialog(79),
                 3 => Lang.dialog(80),
                 _ => Lang.dialog(81),
             })))))))));
             if (Main.LocalPlayer.HasItem(5275))
             {
                 result = Language.GetTextValue("StardewTalk.PlayerHasColaButIsNotHoldingIt");
             }
         }
         else if (type == 37)
         {
             result = ((!Main.dayTime || Main.remixWorld) ? ((Main.player[Main.myPlayer].statLifeMax < 300 || Main.player[Main.myPlayer].statDefense < 10) ? (Main.rand.Next(4) switch
             {
                 0 => Lang.dialog(85),
                 1 => Lang.dialog(86),
                 2 => Lang.dialog(87),
                 _ => Lang.dialog(88),
             }) : (Main.rand.Next(4) switch
             {
                 0 => Lang.dialog(89),
                 1 => Lang.dialog(90),
                 2 => Lang.dialog(91),
                 _ => Lang.dialog(92),
             })) : (Main.rand.Next(3) switch
             {
                 0 => Lang.dialog(82),
                 1 => Lang.dialog(83),
                 _ => Lang.dialog(84),
             }));
         }
         else if (type == 38)
         {
             result = (HasSpecialEventText("Demolitionist", out specialEventText) ? specialEventText : ((!downedBoss2 && Main.rand.Next(3) == 0) ? Lang.dialog(93) : (Main.bloodMoon ? (Main.rand.Next(3) switch
             {
                 0 => Lang.dialog(94),
                 1 => Lang.dialog(95),
                 _ => Lang.dialog(96),
             }) : (((DD2Event.DownedInvasionT1 || DD2Event.Ongoing) && Main.rand.Next(5) == 0) ? Language.GetTextValueWith("DemolitionistSpecialText.AfterDD2Start", obj) : ((flag3 && Main.rand.Next(5) == 0) ? Lang.dialog(97) : ((flag3 && Main.rand.Next(5) == 0) ? Lang.dialog(98) : ((flag2 && Main.rand.Next(4) == 0) ? Lang.dialog(99) : ((flag4 && Main.rand.Next(4) == 0) ? Lang.dialog(100) : ((!Main.dayTime) ? (Main.rand.Next(4) switch
             {
                 0 => Lang.dialog(101),
                 1 => Lang.dialog(102),
                 2 => Lang.dialog(103),
                 _ => Lang.dialog(104),
             }) : (Main.rand.Next(5) switch
             {
                 0 => Lang.dialog(105),
                 1 => Lang.dialog(106),
                 2 => Lang.dialog(107),
                 3 => Lang.dialog(108),
                 _ => Lang.dialog(109),
             }))))))))));
         }
         else if (type == 54)
         {
             result = (HasSpecialEventText("Clothier", out specialEventText) ? specialEventText : ((!flag7 && Main.rand.Next(2) == 0) ? Lang.dialog(110) : ((flag10 && Main.rand.Next(6) == 0) ? Lang.dialog(237) : (Main.bloodMoon ? Lang.dialog(111) : ((flag2 && Main.rand.Next(4) == 0) ? Lang.dialog(112) : ((Main.player[Main.myPlayer].head == 24) ? Lang.dialog(113) : (Main.rand.Next(6) switch
             {
                 0 => Lang.dialog(114),
                 1 => Lang.dialog(115),
                 2 => Lang.dialog(116),
                 3 => Lang.dialog(117),
                 4 => Lang.dialog(118),
                 _ => Lang.dialog(119),
             })))))));
         }
         else if (type == 105)
         {
             result = Lang.dialog(120);
         }
         else if (type == 107)
         {
             if (homeless)
             {
                 result = Main.rand.Next(5) switch
                 {
                     0 => Lang.dialog(121),
                     1 => Lang.dialog(122),
                     2 => Lang.dialog(123),
                     3 => Lang.dialog(124),
                     _ => Lang.dialog(125),
                 };
             }
             else if (HasSpecialEventText("GoblinTinkerer", out specialEventText))
             {
                 result = specialEventText;
             }
             else if (flag7 && Main.rand.Next(5) == 0)
             {
                 result = Lang.dialog(126);
             }
             else if (flag15 && Main.rand.Next(5) == 0)
             {
                 result = Lang.dialog(309);
             }
             else
             {
                 LocalizedText[] array2 = Language.FindAll(Lang.CreateDialogFilter("GoblinTinkererChatter.", obj));
                 int num4 = Main.rand.Next(array2.Length + 5);
                 result = ((num4 >= 5) ? array2[num4 - 5].FormatWith(obj) : ((!Main.dayTime) ? (num4 switch
                 {
                     0 => Lang.dialog(127),
                     1 => Lang.dialog(128),
                     2 => Lang.dialog(129),
                     3 => Lang.dialog(130),
                     _ => Lang.dialog(131),
                 }) : (num4 switch
                 {
                     0 => Lang.dialog(132),
                     1 => Lang.dialog(133),
                     2 => Lang.dialog(134),
                     3 => Lang.dialog(135),
                     _ => Lang.dialog(136),
                 })));
             }
         }
         else if (type == 106)
         {
             result = Lang.dialog(137);
         }
         else if (type == 108)
         {
             if (homeless)
             {
                 int num5 = Main.rand.Next(3);
                 if (num5 == 0)
                 {
                     result = Lang.dialog(138);
                 }
                 else if (num5 == 1 && !Main.player[Main.myPlayer].Male)
                 {
                     result = Lang.dialog(139);
                 }
                 else
                 {
                     switch (num5)
                     {
                     case 1:
                         result = Lang.dialog(140);
                         break;
                     case 2:
                         result = Lang.dialog(141);
                         break;
                     }
                 }
             }
             else if (HasLuckTextForWizard(out specialEventText))
             {
                 result = specialEventText;
             }
             else if (HasSpecialEventText("Wizard", out specialEventText))
             {
                 result = specialEventText;
             }
             else if (DD2Event.DownedInvasionT1 && Main.rand.Next(6) == 0)
             {
                 result = Language.GetTextValueWith("WizardSpecialText.AfterDD2Tier1", obj);
             }
             else if (Main.player[Main.myPlayer].Male && flag16 && Main.rand.Next(6) == 0)
             {
                 result = Lang.dialog(142);
             }
             else if (Main.player[Main.myPlayer].Male && flag6 && Main.rand.Next(6) == 0)
             {
                 result = Lang.dialog(143);
             }
             else if (Main.player[Main.myPlayer].Male && flag8 && Main.rand.Next(6) == 0)
             {
                 result = Lang.dialog(144);
             }
             else if (!Main.player[Main.myPlayer].Male && flag2 && Main.rand.Next(6) == 0)
             {
                 result = Lang.dialog(145);
             }
             else if (!Main.player[Main.myPlayer].Male && flag7 && Main.rand.Next(6) == 0)
             {
                 result = Lang.dialog(146);
             }
             else if (!Main.player[Main.myPlayer].Male && flag4 && Main.rand.Next(6) == 0)
             {
                 result = Lang.dialog(147);
             }
             else if (Main.dayTime)
             {
                 result = Main.rand.Next(5) switch
                 {
                     0 => Lang.dialog(151),
                     1 => Lang.dialog(152),
                     2 => Lang.dialog(153),
                     3 => Lang.dialog(154),
                     _ => Lang.dialog(155),
                 };
             }
             else
             {
                 switch (Main.rand.Next(3))
                 {
                 case 0:
                     result = Lang.dialog(148);
                     break;
                 case 1:
                     result = Lang.dialog(149);
                     break;
                 case 2:
                     result = Lang.dialog(150);
                     break;
                 }
             }
         }
         else if (type == 123)
         {
             result = Lang.dialog(156);
         }
         else if (type == 124)
         {
             if (homeless)
             {
                 result = Main.rand.Next(4) switch
                 {
                     0 => Lang.dialog(157),
                     1 => Lang.dialog(158),
                     2 => Lang.dialog(159),
                     _ => Lang.dialog(160),
                 };
             }
             else if (HasSpecialEventText("Mechanic", out specialEventText))
             {
                 result = specialEventText;
             }
             else if (Main.bloodMoon)
             {
                 result = Main.rand.Next(4) switch
                 {
                     0 => Lang.dialog(161),
                     1 => Lang.dialog(162),
                     2 => Lang.dialog(163),
                     _ => Lang.dialog(164),
                 };
             }
             else if (flag8 && Main.rand.Next(6) == 0)
             {
                 result = Lang.dialog(165);
             }
             else if (flag3 && Main.rand.Next(6) == 0)
             {
                 result = Lang.dialog(166);
             }
             else
             {
                 LocalizedText[] array3 = Language.FindAll(Lang.CreateDialogFilter("MechanicChatter.", obj));
                 int num6 = Main.rand.Next(3 + array3.Length);
                 result = ((num6 >= 3) ? array3[num6 - 3].FormatWith(obj) : (num6 switch
                 {
                     0 => Lang.dialog(167),
                     1 => Lang.dialog(168),
                     _ => Lang.dialog(169),
                 }));
             }
         }
         else if (type == 22)
         {
             result = (HasSpecialEventText("Guide", out specialEventText) ? specialEventText : (Main.bloodMoon ? (Main.rand.Next(3) switch
             {
                 0 => Lang.dialog(170),
                 1 => Lang.dialog(171),
                 _ => Lang.dialog(172),
             }) : ((LanternNight.LanternsUp && !downedMoonlord) ? Language.GetTextValue("GuideSpecialText.Lantern1") : ((LanternNight.LanternsUp && downedMoonlord) ? Language.GetTextValue("GuideSpecialText.Lantern2") : (Main.eclipse ? Language.GetTextValue("GuideSpecialText.Eclipse") : (Main.slimeRain ? Language.GetTextValue("GuideSpecialText.SlimeRain") : ((!Main.dayTime) ? Lang.dialog(173) : ((Main.hardMode && flag17 && Main.rand.Next(8) == 0) ? Language.GetTextValueWith("GuideChatter.Chatter_1", obj) : ((Main.hardMode && Main.rand.Next(8) == 0) ? Language.GetTextValue("GuideChatter.Chatter_2") : (Main.rand.Next(3) switch
             {
                 0 => Lang.dialog(174),
                 1 => Lang.dialog(175),
                 _ => Lang.dialog(176),
             }))))))))));
         }
         else if (type == 142)
         {
             int num7 = Main.rand.Next(3);
             if (HasSpecialEventText("Santa", out specialEventText))
             {
                 result = specialEventText;
             }
             else
             {
                 switch (num7)
                 {
                 case 0:
                     result = Lang.dialog(224);
                     break;
                 case 1:
                     result = Lang.dialog(225);
                     break;
                 case 2:
                     result = Lang.dialog(226);
                     break;
                 }
             }
         }
         else if (type == 160)
         {
             int num8 = Main.rand.Next(6);
             if (HasSpecialEventText("Truffle", out specialEventText))
             {
                 result = specialEventText;
             }
             else if (flag4 && Main.rand.Next(6) == 0)
             {
                 result = Lang.dialog(232);
             }
             else if (flag9 && Main.rand.Next(6) == 0)
             {
                 result = Lang.dialog(236);
             }
             else
             {
                 switch (num8)
                 {
                 case 0:
                     result = Lang.dialog(231);
                     break;
                 case 1:
                     result = Lang.dialog(233);
                     break;
                 case 2:
                     result = Lang.dialog(234);
                     break;
                 case 3:
                     result = Lang.dialog(235);
                     break;
                 case 4:
                     result = Lang.dialog(240);
                     break;
                 case 5:
                     result = Lang.dialog(241);
                     break;
                 }
             }
         }
         else if (type == 178)
         {
             int num9 = Main.rand.Next(5);
             if (HasSpecialEventText("Steampunker", out specialEventText))
             {
                 result = specialEventText;
             }
             else if (Main.bloodMoon && Main.rand.Next(3) == 0)
             {
                 result = Lang.dialog(245);
             }
             else if (flag13 && Main.rand.Next(6) == 0)
             {
                 result = Lang.dialog(246);
             }
             else if (flag12 && Main.rand.Next(6) == 0)
             {
                 result = Lang.dialog(247);
             }
             else
             {
                 switch (num9)
                 {
                 case 0:
                     result = Lang.dialog(242);
                     break;
                 case 1:
                     result = Lang.dialog(243);
                     break;
                 case 2:
                     result = Lang.dialog(244);
                     break;
                 case 3:
                     result = Lang.dialog(248);
                     break;
                 case 4:
                     result = Lang.dialog(249);
                     break;
                 }
             }
         }
         else if (type == 207)
         {
             int num10 = Main.rand.Next(3);
             if (HasSpecialEventText("DyeTrader", out specialEventText))
             {
                 result = specialEventText;
             }
             else if (flag12 && Main.rand.Next(6) == 0)
             {
                 result = Lang.dialog(260);
             }
             else
             {
                 switch (num10)
                 {
                 case 0:
                     result = Lang.dialog(257);
                     break;
                 case 1:
                     result = Lang.dialog(258);
                     break;
                 case 2:
                     result = Lang.dialog(259);
                     break;
                 }
             }
         }
         else if (type == 208)
         {
             if (freeCake)
             {
                 int num11 = Main.rand.Next(1, 4);
                 result = Language.GetTextValueWith("PartyGirlSpecialText.Cake" + num11, obj);
             }
             else
             {
                 int num12 = Main.rand.Next(7);
                 if (HasSpecialEventText("PartyGirl", out specialEventText))
                 {
                     result = specialEventText;
                 }
                 else if (DD2Event.DownedInvasionT1 && Main.rand.Next(5) == 0)
                 {
                     result = Language.GetTextValueWith("PartyGirlSpecialText.AfterDD2Tier1", obj);
                 }
                 else if (Main.player[Main.myPlayer].Male && Main.rand.Next(5) == 0)
                 {
                     result = Lang.dialog(268);
                 }
                 else if (flag15 && Main.rand.Next(5) == 0)
                 {
                     result = Lang.dialog(310);
                 }
                 else
                 {
                     switch (num12)
                     {
                     case 0:
                         result = Lang.dialog(265);
                         break;
                     case 1:
                         result = Lang.dialog(266);
                         break;
                     case 2:
                         result = Lang.dialog(267);
                         break;
                     case 3:
                         result = Lang.dialog(269);
                         break;
                     case 4:
                         result = Lang.dialog(270);
                         break;
                     case 5:
                         result = Lang.dialog(271);
                         break;
                     case 6:
                         result = Lang.dialog(272);
                         break;
                     }
                 }
             }
         }
         else if (type == 209)
         {
             if (HasSpecialEventText("Cyborg", out specialEventText))
             {
                 result = specialEventText;
             }
             else if (flag12 && Main.rand.Next(6) == 0)
             {
                 result = Lang.dialog(284);
             }
             else if (flag11 && Main.rand.Next(6) == 0)
             {
                 result = Lang.dialog(283);
             }
             else
             {
                 LocalizedText[] array4 = Language.FindAll(Lang.CreateDialogFilter("CyborgChatter.", obj));
                 int num13 = Main.rand.Next(5 + array4.Length);
                 if (num13 >= 5)
                 {
                     result = array4[num13 - 5].FormatWith(obj);
                 }
                 else
                 {
                     switch (num13)
                     {
                     case 0:
                         result = Lang.dialog(280);
                         break;
                     case 1:
                         result = Lang.dialog(281);
                         break;
                     case 2:
                         result = Lang.dialog(282);
                         break;
                     case 3:
                         result = Lang.dialog(285);
                         break;
                     case 4:
                         result = Lang.dialog(286);
                         break;
                     }
                 }
             }
         }
         else if (type == 227)
         {
             int num14 = Main.rand.Next(5);
             if (HasSpecialEventText("Painter", out specialEventText))
             {
                 result = specialEventText;
             }
             else if (Main.hardMode && Main.rand.Next(7) == 0)
             {
                 result = Lang.dialog(250);
             }
             else if (flag14 && Main.rand.Next(6) == 0)
             {
                 result = Lang.dialog(251);
             }
             else
             {
                 switch (num14)
                 {
                 case 0:
                     result = Lang.dialog(252);
                     break;
                 case 1:
                     result = Lang.dialog(253);
                     break;
                 case 2:
                     result = Lang.dialog(254);
                     break;
                 case 3:
                     result = Lang.dialog(255);
                     break;
                 case 4:
                     result = Lang.dialog(256);
                     break;
                 }
             }
         }
         else if (type == 228)
         {
             int num15 = Main.rand.Next(4);
             if (HasSpecialEventText("WitchDoctor", out specialEventText))
             {
                 result = specialEventText;
             }
             else if (flag2 && Main.rand.Next(4) == 0)
             {
                 result = Lang.dialog(263);
             }
             else
             {
                 switch (num15)
                 {
                 case 0:
                     result = Lang.dialog(261);
                     break;
                 case 1:
                     result = Lang.dialog(262);
                     break;
                 case 2:
                     result = Lang.dialog(264);
                     break;
                 case 3:
                     result = Language.GetTextValueWith("WitchDoctorSpecialText.AfterDD2Tier1", obj);
                     break;
                 }
             }
         }
         else if (type == 229)
         {
             LocalizedText[] array5 = Language.FindAll(Lang.CreateDialogFilter("PirateChatter.", obj));
             int num16 = Main.rand.Next(6 + array5.Length);
             if (num16 >= 6)
             {
                 result = array5[num16 - 6].FormatWith(obj);
             }
             else if (HasSpecialEventText("Pirate", out specialEventText))
             {
                 result = specialEventText;
             }
             else if (!Main.player[Main.myPlayer].Male && Main.rand.Next(5) == 0)
             {
                 result = Lang.dialog(276);
             }
             else
             {
                 switch (num16)
                 {
                 case 0:
                     result = Lang.dialog(273);
                     break;
                 case 1:
                     result = Lang.dialog(274);
                     break;
                 case 2:
                     result = Lang.dialog(275);
                     break;
                 case 3:
                     result = Lang.dialog(277);
                     break;
                 case 4:
                     result = Lang.dialog(278);
                     break;
                 case 5:
                     result = Lang.dialog(279);
                     break;
                 }
             }
         }
         else if (type == 354)
         {
             result = Lang.dialog(Main.rand.Next(315, 319));
         }
         else if (type == 353)
         {
             if (HasSpecialEventText("Stylist", out specialEventText))
             {
                 result = specialEventText;
             }
             else if (Main.bloodMoon)
             {
                 switch (Main.rand.Next(3))
                 {
                 case 0:
                     result = Lang.dialog(304);
                     break;
                 case 1:
                     result = Lang.dialog(305);
                     break;
                 case 2:
                     result = Lang.dialog(306);
                     break;
                 }
             }
             else if (Main.dayTime && Main.time < 16200.0 && Main.rand.Next(3) == 0)
             {
                 result = Lang.dialog(311);
             }
             else if (Main.player[Main.myPlayer].Male && Main.rand.Next(3) == 0)
             {
                 switch (Main.rand.Next(2))
                 {
                 case 0:
                     result = Lang.dialog(293);
                     break;
                 case 1:
                     result = Lang.dialog(300);
                     break;
                 }
             }
             else if (!Main.player[Main.myPlayer].Male && Main.rand.Next(3) == 0)
             {
                 switch (Main.rand.Next(3))
                 {
                 case 0:
                     result = Lang.dialog(291);
                     break;
                 case 1:
                     result = Lang.dialog(292);
                     break;
                 case 2:
                     result = Lang.dialog(312);
                     break;
                 }
             }
             else if (flag14 && flag7 && flag2 && flag3 && Main.rand.Next(5) == 0)
             {
                 result = Lang.dialog(307);
             }
             else if (flag14 && Main.rand.Next(5) == 0)
             {
                 result = Lang.dialog(302);
             }
             else if (flag6 && Main.rand.Next(5) == 0)
             {
                 result = Lang.dialog(303);
             }
             else if (flag13 && Main.rand.Next(5) == 0)
             {
                 result = Lang.dialog(308);
             }
             else
             {
                 LocalizedText[] array6 = Language.FindAll(Lang.CreateDialogFilter("StylistChatter.", obj));
                 int num17 = ((Main.moonPhase < 3) ? 5 : 4);
                 int num18 = Main.rand.Next(num17 + array6.Length);
                 if (num18 >= num17)
                 {
                     result = array6[num18 - num17].FormatWith(obj);
                 }
                 else if (Main.moonPhase < 3)
                 {
                     switch (num18)
                     {
                     case 0:
                         result = Lang.dialog(287);
                         break;
                     case 1:
                         result = Lang.dialog(288);
                         break;
                     case 2:
                         result = Lang.dialog(289);
                         break;
                     case 3:
                         result = Lang.dialog(290);
                         break;
                     case 4:
                         result = Lang.dialog(294);
                         break;
                     }
                 }
                 else if (Main.moonPhase < 6)
                 {
                     switch (num18)
                     {
                     case 0:
                         result = Lang.dialog(295);
                         break;
                     case 1:
                         result = Lang.dialog(296);
                         break;
                     case 2:
                         result = Lang.dialog(297);
                         break;
                     case 3:
                         result = Lang.dialog(298);
                         break;
                     }
                 }
                 else
                 {
                     switch (num18)
                     {
                     case 0:
                         result = Lang.dialog(299);
                         break;
                     case 1:
                         result = Lang.dialog(301);
                         break;
                     case 2:
                         result = Lang.dialog(313);
                         break;
                     case 3:
                         result = Lang.dialog(314);
                         break;
                     }
                 }
             }
         }
         else if (type == 368)
         {
             result = (HasSpecialEventText("TravellingMerchant", out specialEventText) ? specialEventText : ((flag16 && Main.rand.Next(5) == 0) ? Lang.dialog(319) : ((flag && Main.rand.Next(5) == 0) ? Lang.dialog(320) : ((!flag9 || Main.rand.Next(5) != 0) ? Lang.dialog(Main.rand.Next(322, 331)) : Lang.dialog(321)))));
         }
         else if (type == 376)
         {
             result = Lang.dialog(Main.rand.Next(353, 356));
         }
         else if (type == 369)
         {
             result = ((Main.rand.Next(5) == 0 && Main.LocalPlayer.anglerQuestsFinished > 1) ? Lang.AnglerQuestCountChat(this) : (HasSpecialEventText("Angler", out specialEventText) ? specialEventText : (Main.bloodMoon ? ((Main.rand.Next(3) == 0) ? Language.SelectRandom(Lang.CreateDialogFilter("AnglerSpecialText.BloodMoonFishing")).FormatWith(obj) : (Main.anglerQuestFinished ? Lang.dialog(Main.rand.Next(350, 353)) : Lang.dialog(Main.rand.Next(348, 350)))) : ((!Main.anglerQuestFinished) ? Lang.dialog(Main.rand.Next(334, 338)) : ((!flag4 || Main.rand.Next(5) != 0) ? Language.SelectRandom(Lang.CreateDialogFilter("AnglerChatter.", obj)).FormatWith(obj) : Lang.dialog(347))))));
         }
         else if (type == 453)
         {
             result = ((!HasSpecialEventText("SkeletonMerchant", out specialEventText)) ? Lang.dialog(Main.rand.Next(356, 364)) : specialEventText);
         }
         else if (type == 441)
         {
             result = (HasSpecialEventText("TaxCollector", out specialEventText) ? specialEventText : ((Main.rand.Next(6) == 0 && flag4) ? Lang.dialog(371) : ((Main.rand.Next(6) == 0 && flag3) ? Lang.dialog(372) : ((Main.rand.Next(6) == 0 && flag6) ? Lang.dialog(373) : ((!(Main.rand.Next(6) == 0 && flag)) ? Lang.dialog(Main.rand.Next(364, 370)) : Lang.dialog(374))))));
         }
         else if (type == 579)
         {
             result = Language.GetTextValue("BartenderSpecialText.FirstMeeting");
         }
         else if (type == 550)
         {
             result = ((!HasSpecialEventText("Bartender", out specialEventText)) ? Lang.BartenderChat(this) : specialEventText);
         }
         else if (type == 589)
         {
             result = ((Main.rand.Next(2) != 0) ? Language.GetTextValue("GolferSpecialText.FirstMeeting2") : Language.GetTextValue("GolferSpecialText.FirstMeeting1"));
         }
         else if (type == 588)
         {
             if (Main.rand.Next(3) != 0 && HasSpecialEventText("Golfer", out specialEventText))
             {
                 result = specialEventText;
             }
             else if (Main.rand.Next(3) == 0)
             {
                 string text2 = ((Main.LocalPlayer.golferScoreAccumulated >= 2000) ? "GolferQuestsChatterMaster" : ((Main.LocalPlayer.golferScoreAccumulated >= 1000) ? "GolferQuestsChatterJourneyman" : ((Main.LocalPlayer.golferScoreAccumulated < 500) ? "GolferQuestsChatterBeginner" : "GolferQuestsChatterApprentice")));
                 result = Language.SelectRandom(Lang.CreateDialogFilter(text2 + ".")).FormatWith(obj);
             }
             else
             {
                 result = Lang.GolferChat(this);
             }
         }
         else if (type == 633)
         {
             result = ((ShouldBestiaryGirlBeLycantrope() || !HasSpecialEventText("BestiaryGirl", out specialEventText)) ? Lang.BestiaryGirlChat(this) : specialEventText);
         }
         else if (type == 663)
         {
             result = ((!HasSpecialEventText("Princess", out specialEventText)) ? Lang.PrincessChat(this) : specialEventText);
         }
         else if (type == 637)
         {
             result = ((!HasSpecialEventText("Cat", out specialEventText)) ? Lang.CatChat(this) : specialEventText);
         }
         else if (type == 638)
         {
             result = ((!HasSpecialEventText("Dog", out specialEventText)) ? Lang.DogChat(this) : specialEventText);
         }
         else if (type == 656)
         {
             result = ((!HasSpecialEventText("Bunny", out specialEventText)) ? Lang.BunnyChat(this) : specialEventText);
         }
         else if (NPCID.Sets.IsTownSlime[type])
         {
             result = ((!HasSpecialEventText("Slime", out specialEventText)) ? Lang.SlimeChat(this) : specialEventText);
         }
         return result;
     }
References Entity.active, Lang.AnglerQuestCountChat(), Main.anglerQuestFinished, Player.anglerQuestsFinished, Lang.BartenderChat(), Lang.BestiaryGirlChat(), Main.bloodMoon, Lang.BunnyChat(), Lang.CatChat(), Lang.CreateDialogFilter(), Lang.CreateDialogSubstitutionObject(), WorldGen.crimson, Main.dayTime, Lang.dialog(), Lang.DogChat(), DD2Event.DownedInvasionT1, DD2Event.DownedInvasionT2, Main.eclipse, Language.FindAll(), Recipe.FindRecipes(), LocalizedText.FormatWith(), Language.GetTextValue(), Language.GetTextValueWith(), Lang.GolferChat(), Player.golferScoreAccumulated, Main.hardMode, Player.HasItem(), Player.head, NPCID.Sets.IsTownSlime, LanternNight.LanternsUp, Main.LocalPlayer, Player.Male, Main.moonPhase, Main.myPlayer, UnifiedRandom.Next(), Main.npc, Player.numberOfDeathsPVE, DD2Event.Ongoing, Main.player, Lang.PrincessChat(), Main.rand, Main.remixWorld, Language.SelectRandom(), Lang.SlimeChat(), Main.slimeRain, Player.statDefense, Player.statLife, Player.statLifeMax, Player.statLifeMax2, Main.time, and type.
Referenced by Main.GUIChatDrawInner(), and Main.HoverOverNPCs().