Terraria: NPC.AI_113_WindyBalloon
AI_113_WindyBalloon()
void NPC.AI_113_WindyBalloon () inline private
     {
         if (localAI[0] == 0f && Main.netMode != 1)
         {
             TargetClosest();
             localAI[0] = 1f;
             ai[2] = Main.rand.Next(7) + 1;
             int num = NewNPC(GetSpawnSourceForNPCFromNPCAI(), (int)position.X, (int)position.Y, 1);
             if (Main.rand.Next(180) == 0)
             {
                 Main.npc[num].SetDefaults(-4);
             }
             else if (Main.rand.Next(10) == 0)
             {
                 Main.npc[num].SetDefaults(-7);
             }
             else if (Main.rand.Next(3) == 0)
             {
                 Main.npc[num].SetDefaults(-3);
             }
             Main.npc[num].ai[0] = -999f;
             Main.npc[num].netUpdate = true;
             ai[3] = num;
             netUpdate = true;
             ai[1] = Main.npc[num].scale;
         }
         position = base.Center;
         base.Size = new Vector2(20f, 20f) * ai[1];
         scale = ai[1];
         base.Center = position;
         NPC nPC = AI_113_WindyBalloon_GetSlaveNPC();
         rotation = velocity.X * 0.05f;
         if (nPC != null)
         {
             NPCAimedTarget targetData = GetTargetData();
             float num2 = float.PositiveInfinity;
             int num3 = 0;
             Vector2 zero = Vector2.Zero;
             if (!targetData.Invalid)
             {
                 zero = targetData.Center - base.Bottom;
                 if (zero.Y < 0f)
                 {
                     num3 = (int)zero.Y / -16;
                 }
                 num2 = zero.Length();
                 if (direction != Math.Sign(zero.X))
                 {
                     num3 = 0;
                 }
             }
             if (wet || nPC.wet || collideX || (collideY && oldVelocity.Y < 0f))
             {
                 float num4 = oldVelocity.X + (float)(direction * 8);
                 position.X -= num4;
                 nPC.position.X -= num4;
                 TargetClosest(faceTarget: false);
                 direction *= -1;
                 velocity.X = direction * 2;
                 life = -1;
                 HitEffect();
                 active = false;
                 netUpdate = true;
                 SoundEngine.PlaySound(DeathSound, position);
                 return;
             }
             if (collideY)
             {
                 velocity.Y = ((oldVelocity.Y > 0f) ? 1 : (-1));
                 TargetClosest(faceTarget: false);
             }
             float num5 = 2f + Math.Abs(Main.windSpeedTarget) * 2f;
             if (Math.Sign(velocity.X) != direction || Math.Abs(velocity.X) < num5)
             {
                 velocity.X += (float)direction * 0.01f;
                 if (velocity.X * (float)direction < 0f)
                 {
                     if (Math.Abs(velocity.X) > num5)
                     {
                         velocity.X += (float)direction * 0.1f;
                     }
                     else
                     {
                         velocity.X += (float)direction * 0.05f;
                     }
                 }
                 else if (Math.Abs(velocity.X) > num5)
                 {
                     velocity.X = (float)direction * num5;
                 }
             }
             int num6 = (int)((position.X + (float)(width / 2)) / 16f) + direction;
             int num7 = (int)((position.Y + (float)height) / 16f);
             bool flag = true;
             int num8 = 8 + num3;
             bool flag2 = false;
             for (int i = num7; i < num7 + num8; i++)
             {
                 if (Main.tile[num6, i] == null)
                 {
                     Main.tile[num6, i] = new Tile();
                 }
                 if ((Main.tile[num6, i].nactive() && Main.tileSolid[Main.tile[num6, i].type]) || Main.tile[num6, i].liquid > 0)
                 {
                     if (i < num7 + 5 + num3)
                     {
                         flag2 = true;
                     }
                     flag = false;
                     break;
                 }
             }
             if (num2 < 400f && Collision.CanHit(position, width, height, Main.player[target].position, Main.player[target].width, Main.player[target].height))
             {
                 float num9 = 2f;
                 float num10 = 0.035f;
                 if (base.Center.Y + (float)(height / 4) > Main.player[target].position.Y + (float)(Main.player[target].height / 4) && velocity.Y > 0f - num9)
                 {
                     velocity.Y -= num10;
                     if (velocity.Y > 0f)
                     {
                         velocity.Y -= num10;
                     }
                 }
                 else if (base.Center.Y + (float)(height / 4) < Main.player[target].position.Y + (float)(Main.player[target].height / 4) && velocity.Y < num9)
                 {
                     velocity.Y += num10;
                     if (velocity.Y < 0f)
                     {
                         velocity.Y += num10;
                     }
                 }
             }
             else
             {
                 if (flag)
                 {
                     velocity.Y += 0.05f;
                 }
                 else
                 {
                     velocity.Y -= 0.1f;
                 }
                 if (flag2)
                 {
                     velocity.Y -= 0.2f;
                 }
                 if (velocity.Y > 2f)
                 {
                     velocity.Y = 2f;
                 }
                 if (velocity.Y < -4f)
                 {
                     velocity.Y = -4f;
                 }
             }
             nPC.Center = base.Bottom + new Vector2(0f, -8f) + new Vector2(0f, 56f * ai[1]);
             nPC.velocity = velocity;
         }
         else
         {
             velocity.Y = MathHelper.Clamp(velocity.Y - 0.2f, -8f, 8f);
             velocity.X = MathHelper.Clamp(velocity.X + Main.windSpeedTarget * 0.3f, -4f, 4f);
             if (collideX || collideY)
             {
                 float num11 = oldVelocity.X + (float)(direction * 8);
                 position.X -= num11;
                 TargetClosest(faceTarget: false);
                 direction *= -1;
                 velocity.X = direction * 2;
                 life = -1;
                 HitEffect();
                 active = false;
                 netUpdate = true;
                 SoundEngine.PlaySound(DeathSound, position);
             }
         }
     }
References Entity.active, ai, AI_113_WindyBalloon_GetSlaveNPC(), Collision.CanHit(), NPCAimedTarget.Center, Entity.Center, collideX, collideY, DeathSound, Entity.direction, GetSpawnSourceForNPCFromNPCAI(), GetTargetData(), Entity.height, HitEffect(), NPCAimedTarget.Invalid, life, Tile.liquid, localAI, Tile.nactive(), Main.netMode, netUpdate, NewNPC(), UnifiedRandom.Next(), Main.npc, Entity.oldVelocity, Main.player, SoundEngine.PlaySound(), Entity.position, Main.rand, rotation, scale, SetDefaults(), target, TargetClosest(), Tile, Main.tile, Main.tileSolid, Tile.type, Entity.velocity, Entity.wet, Entity.width, and Main.windSpeedTarget.
Referenced by AI().