Terraria: NPC.CheckDrowning
CheckDrowning()
void NPC.CheckDrowning () inline
     {
         bool flag = Collision.DrownCollision(position, width, height, 1f);
         if (Main.netMode != 1)
         {
             if (flag)
             {
                 if (++breathCounter >= 7)
                 {
                     breathCounter = 0;
                     breath--;
                     if (breath <= 0)
                     {
                         friendlyRegen = 0;
                         breath = 0;
                         life -= 2;
                         if (life % 24 < 2)
{
                             netUpdate = true;
                         }
                         if (life <= 0)
{
                             life = 1;
                             StrikeNPCNoInteraction(2, 0f, 0);
                             if (Main.netMode != 0)
{
                                 NetMessage.SendData(28, -1, -1, null, whoAmI, 2f);
                             }
                         }
                     }
                 }
             }
             else
             {
                 breath += 3;
                 if (breath > 200)
                 {
                     breath = 200;
                 }
                 breathCounter = 0;
             }
         }
         if (flag && Main.rand.Next(20) == 0 && !lavaWet && !honeyWet && !shimmerWet)
         {
             int num = 0;
             int num2 = 0;
             if (type == 369)
             {
                 num2 = 8;
             }
             Dust.NewDust(new Vector2(position.X + (float)((10 + num) * direction), position.Y + (float)num2 + 4f), width - 8, 8, 34, 0f, 0f, 0, default(Color), 1.2f);
         }
     }
References Color, Collision.DrownCollision(), Main.netMode, Dust.NewDust(), UnifiedRandom.Next(), Main.rand, and NetMessage.SendData().