Terraria: NPC.AI_117_BloodNautilus
AI_117_BloodNautilus()
void NPC.AI_117_BloodNautilus () inline private
     {
         float moveSpeed = 0.15f;
         float num = 7.5f;
         float num2 = 60f;
         float num3 = 90f;
         float num4 = 180f;
         float num5 = 90f;
         float num6 = 90f;
         int num7 = 3;
         float num8 = 180f;
         bool flag = false;
         if (localAI[0] == 0f)
         {
             localAI[0] = 1f;
             alpha = 255;
             if (Main.netMode != 1)
             {
                 ai[0] = -1f;
                 netUpdate = true;
             }
         }
         if (ai[0] != -1f && Main.rand.Next(4) == 0)
         {
             position += netOffset;
             Dust dust = Dust.NewDustDirect(position + new Vector2(5f), width - 10, height - 10, 5);
             dust.velocity *= 0.5f;
             if (dust.velocity.Y < 0f)
             {
                 dust.velocity.Y *= -1f;
             }
             dust.alpha = 120;
             dust.scale = 1f + Main.rand.NextFloat() * 0.4f;
             dust.velocity += velocity * 0.3f;
             position -= netOffset;
         }
         if (target == 255)
         {
             TargetClosest();
             ai[2] = direction;
         }
         if (Main.player[target].dead || Vector2.Distance(Main.player[target].Center, base.Center) > 2000f)
         {
             TargetClosest();
         }
         NPCAimedTarget nPCAimedTarget = GetTargetData();
         if (Main.dayTime || !Main.bloodMoon)
         {
             nPCAimedTarget = default(NPCAimedTarget);
         }
         int num9 = -1;
         switch ((int)ai[0])
         {
         case -1:
         {
             velocity *= 0.98f;
             int num17 = Math.Sign(nPCAimedTarget.Center.X - base.Center.X);
             if (num17 != 0)
             {
                 direction = num17;
                 spriteDirection = -direction;
             }
             if (localAI[1] == 0f && alpha < 100)
             {
                 localAI[1] = 1f;
                 int num18 = 36;
                 for (int l = 0; l < num18; l++)
                 {
                     position += netOffset;
                     Vector2 vector3 = (Vector2.Normalize(velocity) * new Vector2((float)width / 2f, height) * 0.75f * 0.5f).RotatedBy((float)(l - (num18 / 2 - 1)) * ((float)Math.PI * 2f) / (float)num18) + base.Center;
                     Vector2 vector4 = vector3 - base.Center;
                     int num19 = Dust.NewDust(vector3 + vector4, 0, 0, 5, vector4.X * 2f, vector4.Y * 2f, 100, default(Color), 1.4f);
                     Main.dust[num19].noGravity = true;
                     Main.dust[num19].velocity = Vector2.Normalize(vector4) * 3f;
                     position -= netOffset;
                 }
             }
             if (ai[2] > 5f)
             {
                 velocity.Y = -2.5f;
                 alpha -= 10;
                 if (Collision.SolidCollision(position, width, height))
                 {
                     alpha += 15;
                     if (alpha > 150)
                     {
                         alpha = 150;
                     }
                 }
                 if (alpha < 0)
                 {
                     alpha = 0;
                 }
             }
             ai[2] += 1f;
             if (ai[2] >= 50f)
             {
                 ai[0] = 0f;
                 ai[1] = 0f;
                 ai[2] = 0f;
                 ai[3] = 0f;
                 netUpdate = true;
             }
             break;
         }
         case 0:
         {
             Vector2 destination = nPCAimedTarget.Center + new Vector2((0f - ai[2]) * 300f, -200f);
             if (base.Center.Distance(destination) > 50f)
             {
                 Vector2 desiredVelocity = DirectionTo(destination) * num;
                 SimpleFlyMovement(desiredVelocity, moveSpeed);
             }
             direction = ((base.Center.X < nPCAimedTarget.Center.X) ? 1 : (-1));
             float num15 = base.Center.DirectionTo(nPCAimedTarget.Center).ToRotation() - 0.47123894f * (float)spriteDirection;
             if (spriteDirection == -1)
             {
                 num15 += (float)Math.PI;
             }
             if (spriteDirection != direction)
             {
                 spriteDirection = direction;
                 rotation = 0f - rotation;
                 num15 = 0f - num15;
             }
             rotation = rotation.AngleTowards(num15, 0.02f);
             ai[1] += 1f;
             if (ai[1] > num2)
             {
                 num9 = 1;
                 int num16 = (int)ai[3];
                 if (num16 % 7 == 3)
                 {
                     num9 = 3;
                 }
                 else if (num16 % 2 == 0)
                 {
                     SoundEngine.PlaySound(SoundID.Item170, base.Center);
                     num9 = 2;
                 }
                 else
                 {
                     SoundEngine.PlaySound(SoundID.Item170, base.Center);
                     num9 = 1;
                 }
             }
             break;
         }
         case 1:
         {
             direction = ((!(base.Center.X < nPCAimedTarget.Center.X)) ? 1 : (-1));
             float num20 = base.Center.DirectionFrom(nPCAimedTarget.Center).ToRotation() - 0.47123894f * (float)spriteDirection;
             if (spriteDirection == -1)
             {
                 num20 += (float)Math.PI;
             }
             bool flag2 = ai[1] < num3;
             if (spriteDirection != direction && flag2)
             {
                 spriteDirection = direction;
                 rotation = 0f - rotation;
                 num20 = 0f - num20;
             }
             if (ai[1] < num3)
             {
                 if (ai[1] == num3 - 1f)
                 {
                     SoundEngine.PlaySound(SoundID.Item172, base.Center);
                 }
                 flag = true;
                 velocity *= 0.95f;
                 rotation = rotation.AngleLerp(num20, 0.02f);
                 position += netOffset;
                 BloodNautilus_GetMouthPositionAndRotation(out var mouthPosition4, out var mouthDirection4);
                 Dust dust6 = Dust.NewDustDirect(mouthPosition4 + mouthDirection4 * 60f - new Vector2(40f), 80, 80, 16, 0f, 0f, 150, Color.Transparent, 0.6f);
                 dust6.fadeIn = 1f;
                 dust6.velocity = dust6.position.DirectionTo(mouthPosition4 + Main.rand.NextVector2Circular(15f, 15f)) * dust6.velocity.Length();
                 dust6.noGravity = true;
                 dust6 = Dust.NewDustDirect(mouthPosition4 + mouthDirection4 * 100f - new Vector2(30f), 60, 60, 16, 0f, 0f, 100, Color.Transparent, 0.9f);
                 dust6.fadeIn = 1.5f;
                 dust6.velocity = dust6.position.DirectionTo(mouthPosition4 + Main.rand.NextVector2Circular(15f, 15f)) * (dust6.velocity.Length() + 5f);
                 dust6.noGravity = true;
                 position -= netOffset;
             }
             else if (ai[1] < num3 + num4)
             {
                 position += netOffset;
                 rotation = rotation.AngleLerp(num20, 0.05f);
                 BloodNautilus_GetMouthPositionAndRotation(out var mouthPosition5, out var mouthDirection5);
                 if (base.Center.Distance(nPCAimedTarget.Center) > 150f)
                 {
                     velocity = mouthDirection5 * -16f + base.Center.DirectionTo(nPCAimedTarget.Center) * 1.5f;
                 }
                 for (int m = 0; m < 4; m++)
                 {
                     Dust dust7 = Dust.NewDustDirect(mouthPosition5 + mouthDirection5 * 60f - new Vector2(15f), 30, 30, 5, 0f, 0f, 0, Color.Transparent, 1.5f);
                     dust7.velocity = dust7.position.DirectionFrom(mouthPosition5 + Main.rand.NextVector2Circular(5f, 5f)) * dust7.velocity.Length();
                     dust7.position -= mouthDirection5 * 60f;
                     dust7 = Dust.NewDustDirect(mouthPosition5 + mouthDirection5 * 100f - new Vector2(20f), 40, 40, 5, 0f, 0f, 100, Color.Transparent, 1.5f);
                     dust7.velocity = dust7.position.DirectionFrom(mouthPosition5 + Main.rand.NextVector2Circular(10f, 10f)) * (dust7.velocity.Length() + 5f);
                     dust7.position -= mouthDirection5 * 100f;
                 }
                 position -= netOffset;
             }
             ai[1] += 1f;
             if (ai[1] >= num3 + num4)
             {
                 num9 = 0;
             }
             break;
         }
         case 2:
         {
             direction = ((base.Center.X < nPCAimedTarget.Center.X) ? 1 : (-1));
             float num12 = base.Center.DirectionTo(nPCAimedTarget.Center).ToRotation() - 0.47123894f * (float)spriteDirection;
             if (spriteDirection == -1)
             {
                 num12 += (float)Math.PI;
             }
             if (spriteDirection != direction)
             {
                 spriteDirection = direction;
                 rotation = 0f - rotation;
                 num12 = 0f - num12;
             }
             rotation = rotation.AngleLerp(num12, 0.2f);
             if (ai[1] < num5)
             {
                 position += netOffset;
                 velocity *= 0.95f;
                 BloodNautilus_GetMouthPositionAndRotation(out var mouthPosition2, out var mouthDirection2);
                 if (Main.rand.Next(4) != 0)
                 {
                     Dust dust3 = Dust.NewDustDirect(mouthPosition2 + mouthDirection2 * 60f - new Vector2(60f), 120, 120, 16, 0f, 0f, 150, Color.Transparent, 0.6f);
                     dust3.fadeIn = 1f;
                     dust3.velocity = dust3.position.DirectionTo(mouthPosition2 + Main.rand.NextVector2Circular(15f, 15f)) * (dust3.velocity.Length() + 3f);
                     dust3.noGravity = true;
                     dust3 = Dust.NewDustDirect(mouthPosition2 + mouthDirection2 * 100f - new Vector2(80f), 160, 160, 16, 0f, 0f, 100, Color.Transparent, 0.9f);
                     dust3.fadeIn = 1.5f;
                     dust3.velocity = dust3.position.DirectionTo(mouthPosition2 + Main.rand.NextVector2Circular(15f, 15f)) * (dust3.velocity.Length() + 5f);
                     dust3.noGravity = true;
                 }
                 position -= netOffset;
             }
             else if (ai[1] < num5 + num6)
             {
                 position += netOffset;
                 velocity *= 0.9f;
                 float num13 = (ai[1] - num5) % (num6 / (float)num7);
                 BloodNautilus_GetMouthPositionAndRotation(out var mouthPosition3, out var mouthDirection3);
                 if (num13 < num6 / (float)num7 * 0.8f)
                 {
                     for (int i = 0; i < 5; i++)
                     {
                         Dust dust4 = Dust.NewDustDirect(mouthPosition3 + mouthDirection3 * 50f - new Vector2(15f), 30, 30, 5, 0f, 0f, 0, Color.Transparent, 1.5f);
                         dust4.velocity = dust4.position.DirectionFrom(mouthPosition3 + Main.rand.NextVector2Circular(5f, 5f)) * dust4.velocity.Length();
                         dust4.position -= mouthDirection3 * 60f;
                         dust4 = Dust.NewDustDirect(mouthPosition3 + mouthDirection3 * 90f - new Vector2(20f), 40, 40, 5, 0f, 0f, 100, Color.Transparent, 1.5f);
                         dust4.velocity = dust4.position.DirectionFrom(mouthPosition3 + Main.rand.NextVector2Circular(10f, 10f)) * (dust4.velocity.Length() + 5f);
                         dust4.position -= mouthDirection3 * 100f;
                     }
                 }
                 if ((int)num13 == 0)
                 {
                     velocity += mouthDirection3 * -8f;
                     for (int j = 0; j < 20; j++)
                     {
                         Dust dust5 = Dust.NewDustDirect(mouthPosition3 + mouthDirection3 * 60f - new Vector2(15f), 30, 30, 5, 0f, 0f, 0, Color.Transparent, 1.5f);
                         dust5.velocity = dust5.position.DirectionFrom(mouthPosition3 + Main.rand.NextVector2Circular(5f, 5f)) * dust5.velocity.Length();
                         dust5.position -= mouthDirection3 * 60f;
                         dust5 = Dust.NewDustDirect(mouthPosition3 + mouthDirection3 * 100f - new Vector2(20f), 40, 40, 5, 0f, 0f, 100, Color.Transparent, 1.5f);
                         dust5.velocity = dust5.position.DirectionFrom(mouthPosition3 + Main.rand.NextVector2Circular(10f, 10f)) * (dust5.velocity.Length() + 5f);
                         dust5.position -= mouthDirection3 * 100f;
                     }
                     if (Main.netMode != 1)
                     {
                         int num14 = Main.rand.Next(5, 11);
                         Vector2 vector = mouthDirection3 * 10f;
                         int attackDamage_ForProjectiles = GetAttackDamage_ForProjectiles(30f, 25f);
                         for (int k = 0; k < num14; k++)
{
                             Vector2 vector2 = vector + Main.rand.NextVector2Square(-6f, 6f);
                             Projectile.NewProjectile(GetSpawnSource_ForProjectile(), mouthPosition3 - mouthDirection3 * 5f, vector2, 814, attackDamage_ForProjectiles, 0f, Main.myPlayer);
                         }
                     }
                 }
                 position -= netOffset;
             }
             ai[1] += 1f;
             if (ai[1] >= num5 + num6)
             {
                 num9 = 0;
             }
             break;
         }
         case 3:
         {
             direction = ((base.Center.X < nPCAimedTarget.Center.X) ? 1 : (-1));
             float targetAngle = 0f;
             spriteDirection = direction;
             if (ai[1] < num8)
             {
                 position += netOffset;
                 float num10 = MathHelper.Clamp(1f - ai[1] / num8 * 1.5f, 0f, 1f);
                 velocity = Vector2.Lerp(value2: new Vector2(0f, num10 * -1.5f), value1: velocity, amount: 0.03f);
                 velocity = Vector2.Zero;
                 rotation = rotation.AngleLerp(targetAngle, 0.02f);
                 BloodNautilus_GetMouthPositionAndRotation(out var _, out var _);
                 float t = ai[1] / num8;
                 float num11 = Utils.GetLerpValue(0f, 0.5f, t) * Utils.GetLerpValue(1f, 0.5f, t);
                 Lighting.AddLight(base.Center, new Vector3(1f, 0.5f, 0.5f) * num11);
                 if (Main.rand.Next(3) != 0)
                 {
                     Dust dust2 = Dust.NewDustDirect(base.Center - new Vector2(6f), 12, 12, 5, 0f, 0f, 60, Color.Transparent, 1.4f);
                     dust2.position += new Vector2(spriteDirection * 12, 12f);
                     dust2.velocity *= 0.1f;
                 }
                 position -= netOffset;
             }
             if (ai[1] == 10f || ai[1] == 20f || ai[1] == 30f)
             {
                 BloodNautilus_CallForHelp();
             }
             ai[1] += 1f;
             if (ai[1] >= num8)
             {
                 num9 = 0;
             }
             break;
         }
         }
         if (num9 != -1)
         {
             ai[0] = num9;
             ai[1] = 0f;
             ai[2] = 0f;
             netUpdate = true;
             TargetClosest();
             if (num9 == 0)
             {
                 ai[2] = direction;
             }
             else
             {
                 ai[3] += 1f;
             }
         }
         reflectsProjectiles = flag;
     }
References Lighting.AddLight(), ai, Dust.alpha, alpha, Main.bloodMoon, BloodNautilus_CallForHelp(), BloodNautilus_GetMouthPositionAndRotation(), NPCAimedTarget.Center, Entity.Center, Color, Main.dayTime, Player.dead, Entity.direction, Entity.DirectionTo(), Main.dust, Dust.fadeIn, GetAttackDamage_ForProjectiles(), Utils.GetLerpValue(), GetSpawnSource_ForProjectile(), GetTargetData(), Entity.height, SoundID.Item170, SoundID.Item172, localAI, Main.myPlayer, Main.netMode, netOffset, netUpdate, Dust.NewDust(), Dust.NewDustDirect(), Projectile.NewProjectile(), UnifiedRandom.Next(), Dust.noGravity, Main.player, SoundEngine.PlaySound(), Dust.position, Entity.position, Main.rand, reflectsProjectiles, rotation, Dust.scale, SimpleFlyMovement(), Collision.SolidCollision(), spriteDirection, target, TargetClosest(), Dust.velocity, Entity.velocity, and Entity.width.
Referenced by AI().