Terraria: NPC.UnlockOrExchangePet
UnlockOrExchangePet()
static void NPC.UnlockOrExchangePet (ref bool petBoughtFlag, int npcType, string textKeyForLicense, int netMessageData) inline static
     {
         Color color = new Color(50, 255, 130);
         if (Main.netMode == 1)
         {
             if (!petBoughtFlag || AnyNPCs(npcType))
             {
                 NetMessage.SendData(61, -1, -1, null, Main.myPlayer, netMessageData);
             }
         }
         else if (!petBoughtFlag)
         {
             petBoughtFlag = true;
             ChatHelper.BroadcastChatMessage(NetworkText.FromKey(textKeyForLicense), color);
             NetMessage.TrySendData(7);
         }
         else if (RerollVariationForNPCType(npcType))
         {
             ChatHelper.BroadcastChatMessage(NetworkText.FromKey("Misc.PetExchangeSuccess"), color);
         }
         else
         {
             ChatHelper.BroadcastChatMessage(NetworkText.FromKey("Misc.PetExchangeFail"), color);
         }
     }
References ChatHelper.BroadcastChatMessage(), Color, NetworkText.FromKey(), Main.myPlayer, Main.netMode, NetMessage.SendData(), and NetMessage.TrySendData().
Referenced by MessageBuffer.GetData(), and Player.LicenseOrExchangePet().