Terraria: NPC.checkDead
checkDead()
void NPC.checkDead () inline
     {
         if (!active || (realLife >= 0 && realLife != whoAmI) || life > 0)
         {
             return;
         }
         if (type == 604 || type == 605)
         {
             LadyBugKilled(base.Center, type == 605);
         }
         if (type == 397 || type == 396)
         {
             if (ai[0] != -2f)
             {
                 ai[0] = -2f;
                 life = lifeMax;
                 netUpdate = true;
                 dontTakeDamage = true;
                 if (Main.netMode != 1)
                 {
                     int num = NewNPC(GetSpawnSourceForNPCFromNPCAI(), (int)base.Center.X, (int)base.Center.Y, 400);
                     Main.npc[num].ai[3] = ai[3];
                     Main.npc[num].netUpdate = true;
                 }
             }
             return;
         }
         if (type == 398 && ai[0] != 2f)
         {
             ai[0] = 2f;
             life = lifeMax;
             netUpdate = true;
             dontTakeDamage = true;
             return;
         }
         if ((type == 517 || type == 422 || type == 507 || type == 493) && ai[2] != 1f)
         {
             ai[2] = 1f;
             ai[1] = 0f;
             life = lifeMax;
             dontTakeDamage = true;
             netUpdate = true;
             return;
         }
         if (type == 548 && ai[1] != 1f)
         {
             ai[1] = 1f;
             ai[0] = 0f;
             life = lifeMax;
             dontTakeDamageFromHostiles = true;
             netUpdate = true;
             return;
         }
         if (Main.netMode != 1 && Main.getGoodWorld && (type == 42 || type == 176 || (type >= 231 && type <= 235)))
         {
             StingerExplosion();
         }
         if (Main.netMode != 1 && Main.getGoodWorld)
         {
             if (type == 13)
             {
                 int num2 = NewNPC(GetSpawnSourceForNaturalSpawn(), (int)base.Center.X, (int)(position.Y + (float)height), -12);
                 if (Main.netMode == 2 && num2 < 200)
                 {
                     NetMessage.SendData(23, -1, -1, null, num2);
                 }
             }
             if (type == 36)
             {
                 int num3 = 3;
                 for (int i = 0; i < num3; i++)
                 {
                     int num4 = 1000;
                     for (int j = 0; j < num4; j++)
                     {
                         int num5 = (int)(base.Center.X / 16f) + Main.rand.Next(-50, 51);
                         int k;
                         for (k = (int)(base.Center.Y / 16f) + Main.rand.Next(-50, 51); k < Main.maxTilesY - 200 && !WorldGen.SolidTile(num5, k); k++)
{
                         }
                         k--;
                         if (!WorldGen.SolidTile(num5, k))
{
                             int num6 = NewNPC(GetSpawnSourceForNaturalSpawn(), num5 * 16 + 8, k * 16, 32);
                             if (Main.netMode == 2 && num6 < 200)
{
                                 NetMessage.SendData(23, -1, -1, null, num6);
                             }
                             break;
                         }
                     }
                 }
             }
         }
         noSpawnCycle = true;
         if (townNPC && type != 37 && type != 453)
         {
             if (Main.netMode != 2)
             {
                 NPCLuck();
             }
             bool flag = true;
             NetworkText fullNetName = GetFullNetName();
             int num7 = 19;
             if (type == 369 || type == 663 || NPCID.Sets.IsTownPet[type])
             {
                 num7 = 36;
                 flag = false;
             }
             NetworkText networkText = NetworkText.FromKey(Lang.misc[num7].Key, fullNetName);
             if (flag)
             {
                 for (int l = 0; l < 255; l++)
                 {
                     Player player = Main.player[l];
                     if (player != null && player.active && player.difficulty != 2)
                     {
                         flag = false;
                         break;
                     }
                 }
             }
             if (flag)
             {
                 DropTombstoneTownNPC(networkText);
             }
             if (Main.netMode == 0)
             {
                 Main.NewText(networkText.ToString(), byte.MaxValue, 25, 25);
             }
             else if (Main.netMode == 2)
             {
                 ChatHelper.BroadcastChatMessage(networkText, new Color(255, 25, 25));
             }
         }
         if (Main.netMode != 1 && !Main.IsItDay() && type == 54 && !AnyNPCs(35))
         {
             for (int m = 0; m < 255; m++)
             {
                 if (Main.player[m].active && !Main.player[m].dead && Main.player[m].killClothier)
                 {
                     SpawnSkeletron(m);
                     break;
                 }
             }
         }
         if (townNPC && Main.netMode != 1 && homeless && WorldGen.prioritizedTownNPCType == type)
         {
             WorldGen.prioritizedTownNPCType = 0;
         }
         LegacySoundStyle legacySoundStyle = DeathSound;
         if (type == 229 && IsShimmerVariant)
         {
             legacySoundStyle = SoundID.NPCDeath6;
         }
         if (legacySoundStyle != null)
         {
             SoundEngine.PlaySound(legacySoundStyle, position);
         }
         if (type == 13 || type == 14 || type == 15)
         {
             DropEoWLoot();
         }
         else if (type == 134)
         {
             Vector2 vector = position;
             Vector2 center = Main.player[target].Center;
             float num8 = 100000000f;
             Vector2 vector2 = position;
             for (int n = 0; n < 200; n++)
             {
                 if (Main.npc[n].active && (Main.npc[n].type == 134 || Main.npc[n].type == 135 || Main.npc[n].type == 136))
                 {
                     float num9 = Math.Abs(Main.npc[n].Center.X - center.X) + Math.Abs(Main.npc[n].Center.Y - center.Y);
                     if (num9 < num8)
                     {
                         num8 = num9;
                         vector2 = Main.npc[n].position;
                     }
                 }
             }
             position = vector2;
             NPCLoot();
             position = vector;
         }
         else
         {
             NPCLoot();
         }
         active = false;
         if (Main.getGoodWorld && Main.netMode != 1 && type == 631)
         {
             Projectile.NewProjectile(GetSpawnSource_ForProjectile(), base.Center, Vector2.Zero, 99, 70, 10f, Main.myPlayer);
         }
         DD2Event.CheckProgress(type);
         CheckProgressFrostMoon();
         CheckProgressPumpkinMoon();
         int nPCInvasionGroup = GetNPCInvasionGroup(type);
         if (nPCInvasionGroup <= 0 || nPCInvasionGroup != Main.invasionType)
         {
             return;
         }
         int num10 = 1;
         switch (type)
         {
         case 216:
             num10 = 5;
             break;
         case 395:
             num10 = 10;
             break;
         case 491:
             num10 = 10;
             break;
         case 471:
             num10 = 10;
             break;
         case 472:
             num10 = 0;
             break;
         case 387:
             num10 = 0;
             break;
         }
         if (num10 > 0)
         {
             Main.invasionSize -= num10;
             if (Main.invasionSize < 0)
             {
                 Main.invasionSize = 0;
             }
             if (Main.netMode != 1)
             {
                 Main.ReportInvasionProgress(Main.invasionSizeStart - Main.invasionSize, Main.invasionSizeStart, nPCInvasionGroup + 3, 0);
             }
             if (Main.netMode == 2)
             {
                 NetMessage.SendData(78, -1, -1, null, Main.invasionProgress, Main.invasionProgressMax, Main.invasionProgressIcon);
             }
         }
     }
References Entity.active, ai, AnyNPCs(), ChatHelper.BroadcastChatMessage(), Entity.Center, DD2Event.CheckProgress(), CheckProgressFrostMoon(), CheckProgressPumpkinMoon(), Color, Player.dead, DeathSound, Player.difficulty, dontTakeDamage, dontTakeDamageFromHostiles, DropEoWLoot(), DropTombstoneTownNPC(), NetworkText.FromKey(), GetFullNetName(), Main.getGoodWorld, GetNPCInvasionGroup(), GetSpawnSource_ForProjectile(), GetSpawnSourceForNaturalSpawn(), GetSpawnSourceForNPCFromNPCAI(), Entity.height, homeless, Main.invasionProgress, Main.invasionProgressIcon, Main.invasionProgressMax, Main.invasionSize, Main.invasionSizeStart, Main.invasionType, Main.IsItDay(), IsShimmerVariant, NPCID.Sets.IsTownPet, LocalizedText.Key, Player.killClothier, LadyBugKilled(), life, lifeMax, Main.maxTilesY, Lang.misc, Main.myPlayer, Main.netMode, netUpdate, NewNPC(), Projectile.NewProjectile(), Main.NewText(), UnifiedRandom.Next(), noSpawnCycle, Main.npc, SoundID.NPCDeath6, NPCLoot(), NPCLuck(), Main.player, SoundEngine.PlaySound(), Entity.position, WorldGen.prioritizedTownNPCType, Main.rand, realLife, Main.ReportInvasionProgress(), NetMessage.SendData(), WorldGen.SolidTile(), SpawnSkeletron(), StingerExplosion(), target, NetworkText.ToString(), townNPC, type, and Entity.whoAmI.
Referenced by AI(), AI_006_Worms(), AI_037_Destroyer(), and StrikeNPC().