Terraria: NPC.FindBuffIndex
FindBuffIndex()
int NPC.FindBuffIndex (int type) inline
     {
         if (buffImmune[type])
         {
             return -1;
         }
         for (int i = 0; i < maxBuffs; i++)
         {
             if (buffTime[i] >= 1 && buffType[i] == type)
             {
                 return i;
             }
         }
         return -1;
     }
Referenced by AI_007_TownEntities(), Projectile.AI_111_DryadsWard(), and Player.UpdateBuffs().