Terraria: NPC.SpawnSkeletron
SpawnSkeletron()
static void NPC.SpawnSkeletron (int onWho) inline static
     {
         bool flag = true;
         bool flag2 = false;
         Vector2 zero = Vector2.Zero;
         int num = 0;
         int num2 = 0;
         for (int i = 0; i < 200; i++)
         {
             if (Main.npc[i].active && Main.npc[i].type == 35)
             {
                 flag = false;
                 break;
             }
         }
         for (int j = 0; j < 200; j++)
         {
             if (!Main.npc[j].active)
             {
                 continue;
             }
             if (Main.npc[j].type == 37)
             {
                 flag2 = true;
                 Main.npc[j].ai[3] = 1f;
                 zero = Main.npc[j].position;
                 num = Main.npc[j].width;
                 num2 = Main.npc[j].height;
                 if (Main.netMode == 2)
                 {
                     NetMessage.SendData(23, -1, -1, null, j);
                 }
             }
             else if (Main.npc[j].type == 54)
             {
                 flag2 = true;
                 zero = Main.npc[j].position;
                 num = Main.npc[j].width;
                 num2 = Main.npc[j].height;
             }
         }
         if (flag && flag2)
         {
             int num3 = NewNPC(GetBossSpawnSource(onWho), (int)zero.X + num / 2, (int)zero.Y + num2 / 2, 35);
             Main.npc[num3].netUpdate = true;
             string nPCNameValue = Lang.GetNPCNameValue(35);
             if (Main.netMode == 0)
             {
                 Main.NewText(Language.GetTextValue("Announcement.HasAwoken", nPCNameValue), 175, 75);
             }
             else if (Main.netMode == 2)
             {
                 ChatHelper.BroadcastChatMessage(NetworkText.FromKey("Announcement.HasAwoken", Lang.GetNPCName(35).ToNetworkText()), new Color(175, 75, 255));
             }
         }
     }
References Entity.active, ai, ChatHelper.BroadcastChatMessage(), Color, NetworkText.FromKey(), Lang.GetNPCName(), Lang.GetNPCNameValue(), Language.GetTextValue(), Entity.height, Main.netMode, netUpdate, Main.NewText(), Main.npc, Entity.position, NetMessage.SendData(), LocalizedText.ToNetworkText(), type, and Entity.width.
Referenced by checkDead(), MessageBuffer.GetData(), and Main.GUIChatDrawInner().