Terraria: NPC.SpawnOnPlayer
SpawnOnPlayer()
static void NPC.SpawnOnPlayer (int plr, int Type) inline static
     {
         if (Main.netMode == 1 || (Type == 262 && AnyNPCs(262)))
         {
             return;
         }
         switch (Type)
         {
         case 245:
             if (AnyNPCs(245))
             {
                 return;
             }
             try
             {
                 int num2 = (int)Main.player[plr].Center.X / 16;
                 int num3 = (int)Main.player[plr].Center.Y / 16;
                 int num4 = 0;
                 int num5 = 0;
                 for (int j = num2 - 20; j < num2 + 20; j++)
                 {
                     for (int k = num3 - 20; k < num3 + 20; k++)
                     {
                         if (Main.tile[j, k].active() && Main.tile[j, k].type == 237 && Main.tile[j, k].frameX == 18 && Main.tile[j, k].frameY == 0)
{
                             num4 = j;
                             num5 = k;
                         }
                     }
                 }
                 if (num4 <= 0 || num5 <= 0)
                 {
                     return;
                 }
                 int num6 = num5 - 15;
                 int num7 = num5 - 15;
                 for (int num8 = num5; num8 > num5 - 50; num8--)
                 {
                     if (WorldGen.SolidTile(num4, num8))
                     {
                         num6 = num8;
                         break;
                     }
                 }
                 for (int l = num5; l < num5 + 50; l++)
                 {
                     if (WorldGen.SolidTile(num4, l))
                     {
                         num7 = l;
                         break;
                     }
                 }
                 num5 = (num6 + num6 + num7) / 3;
                 int num9 = NewNPC(GetBossSpawnSource(plr), num4 * 16 + 8, num5 * 16, 245);
                 Main.npc[num9].target = plr;
                 string typeName2 = Main.npc[num9].TypeName;
                 if (Main.netMode == 0)
                 {
                     Main.NewText(Language.GetTextValue("Announcement.HasAwoken", typeName2), 175, 75);
                 }
                 else if (Main.netMode == 2)
                 {
                     ChatHelper.BroadcastChatMessage(NetworkText.FromKey("Announcement.HasAwoken", Main.npc[num9].GetTypeNetName()), new Color(175, 75, 255));
                 }
                 return;
             }
             catch
             {
                 return;
             }
         case 370:
         {
             Player player2 = Main.player[plr];
             if (!player2.active || player2.dead)
             {
                 return;
             }
             for (int i = 0; i < 1000; i++)
             {
                 Projectile projectile = Main.projectile[i];
                 if (projectile.active && projectile.bobber && projectile.owner == plr)
                 {
                     int num = NewNPC(GetBossSpawnSource(plr), (int)projectile.Center.X, (int)projectile.Center.Y + 100, 370);
                     string typeName = Main.npc[num].TypeName;
                     if (Main.netMode == 0)
                     {
                         Main.NewText(Language.GetTextValue("Announcement.HasAwoken", typeName), 175, 75);
                     }
                     else if (Main.netMode == 2)
                     {
                         ChatHelper.BroadcastChatMessage(NetworkText.FromKey("Announcement.HasAwoken", Main.npc[num].GetTypeNetName()), new Color(175, 75, 255));
                     }
                     break;
                 }
             }
             return;
         }
         case 398:
             if (!AnyNPCs(Type))
             {
                 Player player = Main.player[plr];
                 NewNPC(GetBossSpawnSource(plr), (int)player.Center.X, (int)player.Center.Y - 150, Type);
                 if (Main.netMode == 0)
                 {
                     Main.NewText(Language.GetTextValue("Announcement.HasAwoken", Language.GetTextValue("Enemies.MoonLord")), 175, 75);
                 }
                 else if (Main.netMode == 2)
                 {
                     ChatHelper.BroadcastChatMessage(NetworkText.FromKey("Announcement.HasAwoken", NetworkText.FromKey("Enemies.MoonLord")), new Color(175, 75, 255));
                 }
             }
             return;
         }
         bool flag = false;
         int num10 = 0;
         int num11 = 0;
         int num12 = (int)(Main.player[plr].position.X / 16f) - spawnRangeX * 2;
         int num13 = (int)(Main.player[plr].position.X / 16f) + spawnRangeX * 2;
         int num14 = (int)(Main.player[plr].position.Y / 16f) - spawnRangeY * 2;
         int num15 = (int)(Main.player[plr].position.Y / 16f) + spawnRangeY * 2;
         int num16 = (int)(Main.player[plr].position.X / 16f) - safeRangeX;
         int num17 = (int)(Main.player[plr].position.X / 16f) + safeRangeX;
         int num18 = (int)(Main.player[plr].position.Y / 16f) - safeRangeY;
         int num19 = (int)(Main.player[plr].position.Y / 16f) + safeRangeY;
         if (num12 < 0)
         {
             num12 = 0;
         }
         if (num13 > Main.maxTilesX)
         {
             num13 = Main.maxTilesX;
         }
         if (num14 < 0)
         {
             num14 = 0;
         }
         if (num15 > Main.maxTilesY)
         {
             num15 = Main.maxTilesY;
         }
         for (int m = 0; m < 1000; m++)
         {
             for (int n = 0; n < 100; n++)
             {
                 int num20 = Main.rand.Next(num12, num13);
                 int num21 = Main.rand.Next(num14, num15);
                 if (!Main.tile[num20, num21].nactive() || !Main.tileSolid[Main.tile[num20, num21].type])
                 {
                     if ((Main.wallHouse[Main.tile[num20, num21].wall] && m < 999) || (Type == 50 && m < 500 && Main.tile[num21, num21].wall > 0))
                     {
                         continue;
                     }
                     for (int num22 = num21; num22 < Main.maxTilesY; num22++)
                     {
                         if (Main.tile[num20, num22].nactive() && Main.tileSolid[Main.tile[num20, num22].type])
{
                             if ((num20 < num16 || num20 > num17 || num22 < num18 || num22 > num19 || m == 999) && ((num20 >= num12 && num20 <= num13 && num22 >= num14 && num22 <= num15) || m == 999))
{
                                 _ = Main.tile[num20, num22].type;
                                 num10 = num20;
                                 num11 = num22;
                                 flag = true;
                             }
                             break;
                         }
                     }
                     if (flag && Type == 50 && m < 900)
                     {
                         int num23 = 20;
                         if (!Collision.CanHit(new Vector2(num10, num11 - 1) * 16f, 16, 16, new Vector2(num10, num11 - 1 - num23) * 16f, 16, 16) || !Collision.CanHit(new Vector2(num10, num11 - 1 - num23) * 16f, 16, 16, Main.player[plr].Center, 0, 0))
{
                             num10 = 0;
                             num11 = 0;
                             flag = false;
                         }
                     }
                     if (flag && m < 999)
                     {
                         int num24 = num10 - spawnSpaceX / 2;
                         int num25 = num10 + spawnSpaceX / 2;
                         int num26 = num11 - spawnSpaceY;
                         int num27 = num11;
                         if (num24 < 0)
{
                             flag = false;
                         }
                         if (num25 > Main.maxTilesX)
{
                             flag = false;
                         }
                         if (num26 < 0)
{
                             flag = false;
                         }
                         if (num27 > Main.maxTilesY)
{
                             flag = false;
                         }
                         if (flag)
{
                             for (int num28 = num24; num28 < num25; num28++)
{
                                 for (int num29 = num26; num29 < num27; num29++)
{
                                     if (Main.tile[num28, num29].nactive() && Main.tileSolid[Main.tile[num28, num29].type])
{
                                         flag = false;
                                         break;
                                     }
                                 }
                             }
                         }
                     }
                 }
                 if (flag || flag)
                 {
                     break;
                 }
             }
             if (flag && m < 999)
             {
                 Rectangle rectangle = new Rectangle(num10 * 16, num11 * 16, 16, 16);
                 for (int num30 = 0; num30 < 255; num30++)
                 {
                     if (Main.player[num30].active)
                     {
                         Rectangle rectangle2 = new Rectangle((int)(Main.player[num30].position.X + (float)(Main.player[num30].width / 2) - (float)(sWidth / 2) - (float)safeRangeX), (int)(Main.player[num30].position.Y + (float)(Main.player[num30].height / 2) - (float)(sHeight / 2) - (float)safeRangeY), sWidth + safeRangeX * 2, sHeight + safeRangeY * 2);
                         if (rectangle.Intersects(rectangle2))
{
                             flag = false;
                         }
                     }
                 }
             }
             if (flag)
             {
                 break;
             }
         }
         if (flag)
         {
             int spawnPositionX = num10 * 16 + 8;
             int spawnPositionY = num11 * 16;
             SpawnBoss(spawnPositionX, spawnPositionY, Type, plr);
         }
     }
References Entity.active, Tile.active(), Projectile.bobber, ChatHelper.BroadcastChatMessage(), Collision.CanHit(), Entity.Center, Color, Player.dead, Tile.frameX, Tile.frameY, NetworkText.FromKey(), Language.GetTextValue(), GetTypeNetName(), Entity.height, Main.maxTilesX, Main.maxTilesY, Tile.nactive(), Main.netMode, Main.NewText(), UnifiedRandom.Next(), Main.npc, Projectile.owner, Main.player, Entity.position, Main.projectile, Main.rand, WorldGen.SolidTile(), target, Main.tile, Main.tileSolid, Tile.type, TypeName, Tile.wall, Main.wallHouse, and Entity.width.
Referenced by WorldGen.Check3x3(), WorldGen.CheckJunglePlant(), WorldGen.CheckOrb(), WorldGen.CheckSign(), DoDeathEvents(), DoDeathEvents_AdvanceSlimeRain(), MessageBuffer.GetData(), Player.ItemCheck_CheckFishingBobber_PullBobber(), Player.ItemCheck_UseBossSpawners(), WorldGen.SmashAltar(), SpawnMechQueen(), DD2Event.SummonBetsy(), Player.TileInteractionsUse(), and Main.UpdateTime().