Terraria: NPC.DoDeathEvents_AdvanceSlimeRain
DoDeathEvents_AdvanceSlimeRain()
void NPC.DoDeathEvents_AdvanceSlimeRain (Player closestPlayer) inline private
     {
         if (Main.slimeRain && Main.slimeRainNPC[type] && !AnyNPCs(50))
         {
             int num = 150;
             if (downedSlimeKing)
             {
                 num /= 2;
             }
             Main.slimeRainKillCount++;
             if (Main.slimeRainKillCount >= num)
             {
                 SpawnOnPlayer(closestPlayer.whoAmI, 50);
                 Main.slimeRainKillCount = -num / 2;
             }
         }
     }
References AnyNPCs(), downedSlimeKing, Main.slimeRain, Main.slimeRainKillCount, Main.slimeRainNPC, SpawnOnPlayer(), type, and Entity.whoAmI.
Referenced by DoDeathEvents().