Terraria: NPC.TransformVisuals
TransformVisuals()
void NPC.TransformVisuals (int oldType, int newType) inline
     {
         position += netOffset;
         if ((oldType == 158 && newType == 159) || (oldType == 159 && newType == 158))
         {
             SoundEngine.PlaySound(SoundID.Item8, position);
             int num = Gore.NewGore(new Vector2(position.X, position.Y - 10f), velocity, 99, scale);
             Main.gore[num].velocity *= 0.3f;
             num = Gore.NewGore(new Vector2(position.X, position.Y + (float)(height / 2) - 10f), velocity, 99, scale);
             Main.gore[num].velocity *= 0.3f;
             num = Gore.NewGore(new Vector2(position.X, position.Y + (float)height - 10f), velocity, 99, scale);
             Main.gore[num].velocity *= 0.3f;
         }
         else if (oldType == 478 && newType == 479)
         {
             for (int i = 0; i < 30; i++)
             {
                 int num2 = Dust.NewDust(position, width, height, 238, 0f, -2f);
                 if (Main.rand.Next(2) == 0)
                 {
                     Main.dust[num2].noGravity = true;
                 }
             }
             Gore.NewGore(position, velocity, 684, scale);
             Gore.NewGore(position, velocity, 685, scale);
             Gore.NewGore(position, velocity, 686, scale);
             Gore.NewGore(position, velocity, 684 + Main.rand.Next(3), scale);
         }
         else if (oldType == 406 && newType == 405)
         {
             float num3 = Main.rand.Next(10, 21);
             float num4 = (float)Math.PI * 2f * Main.rand.NextFloat();
             Vector2 vector = new Vector2(22f, 22f);
             for (float num5 = 0f; num5 < num3; num5 += 1f)
             {
                 Dust dust = Main.dust[Dust.NewDust(base.Center, 0, 0, 229)];
                 Vector2 vector2 = Vector2.UnitY.RotatedBy(num5 * ((float)Math.PI * 2f) / num3 + num4);
                 dust.position = base.Center + vector2 * vector / 2f;
                 dust.velocity = vector2;
                 dust.noGravity = true;
                 dust.scale = 0.6f + Main.rand.NextFloat() * 1.8f;
                 dust.velocity *= dust.scale;
                 dust.fadeIn = Main.rand.NextFloat() * 2f;
             }
         }
         if (oldType == 428 && newType == 427)
         {
             for (int j = 0; j < 20; j++)
             {
                 int num6 = Utils.SelectRandom<int>(Main.rand, 229, 240);
                 Dust dust2 = Main.dust[Dust.NewDust(position, width, height, num6)];
                 dust2.noGravity = true;
                 dust2.scale = 0.6f + Main.rand.NextFloat() * 1.8f;
                 dust2.fadeIn = 0.25f;
                 dust2.velocity *= dust2.scale / 2f;
             }
         }
         if (oldType == 427 && newType == 426)
         {
             for (int k = 0; k < 30; k++)
             {
                 int num7 = Utils.SelectRandom<int>(Main.rand, 229, 240, 240);
                 Dust dust3 = Main.dust[Dust.NewDust(position, width, height, num7)];
                 dust3.noGravity = true;
                 dust3.scale = 0.6f + Main.rand.NextFloat() * 1.8f;
                 dust3.fadeIn = 0.25f;
                 dust3.velocity *= dust3.scale * 0.75f;
             }
         }
         position -= netOffset;
     }
References Main.dust, Dust.fadeIn, Main.gore, SoundID.Item8, Dust.NewDust(), Gore.NewGore(), UnifiedRandom.Next(), Dust.noGravity, SoundEngine.PlaySound(), Dust.position, Main.rand, Dust.scale, Dust.velocity, and Gore.velocity.
Referenced by MessageBuffer.GetData().