Terraria: NPC.GetSpawnSourceForNPCFromNPCAI
GetSpawnSourceForNPCFromNPCAI()
IEntitySource NPC.GetSpawnSourceForNPCFromNPCAI () inline
     {
         return new EntitySource_Parent(this);
     }
Referenced by AI(), AI_003_Fighters(), AI_005_EaterOfSouls(), AI_006_Worms(), AI_026_Unicorns(), AI_037_Destroyer(), AI_045_Golem(), AI_069_DukeFishron(), AI_084_LunaticCultist(), AI_110_Betsy(), AI_113_WindyBalloon(), AI_121_QueenSlime(), checkDead(), and ViolentlySpawnNerdySlime().