Terraria: NPC.GetNPCLocation
GetNPCLocation()
static bool NPC.GetNPCLocation (int i, bool seekHead, bool averageDirection, out int index, out Vector2 pos) inline static
     {
         int num = Main.npc[i].type;
         int num2 = -1;
         int num3 = -1;
         switch (num)
         {
         case 13:
             num3 = 15;
             num2 = 0;
             break;
         case 14:
         case 15:
             num3 = 13;
             num2 = 1;
             break;
         case 134:
             num3 = 136;
             num2 = 0;
             break;
         case 135:
         case 136:
             num3 = 134;
             num2 = 1;
             break;
         case 454:
             num3 = 459;
             num2 = 0;
             break;
         case 455:
         case 456:
         case 457:
         case 458:
         case 459:
             num3 = 454;
             num2 = 1;
             break;
         case 98:
             num3 = 100;
             num2 = 0;
             break;
         case 99:
         case 100:
             num3 = 98;
             num2 = 1;
             break;
         case 39:
             num3 = 41;
             num2 = 0;
             break;
         case 40:
         case 41:
             num3 = 39;
             num2 = 1;
             break;
         case 510:
             num3 = 512;
             num2 = 0;
             break;
         case 511:
         case 512:
             num3 = 510;
             num2 = 1;
             break;
         case 621:
             num3 = 623;
             num2 = 0;
             break;
         case 622:
         case 623:
             num3 = 621;
             num2 = 1;
             break;
         case 513:
             num3 = 515;
             num2 = 0;
             break;
         case 514:
         case 515:
             num3 = 513;
             num2 = 1;
             break;
         case 87:
             num3 = 92;
             num2 = 0;
             break;
         case 88:
         case 89:
         case 90:
         case 91:
         case 92:
             num3 = 87;
             num2 = 1;
             break;
         case 117:
             num3 = 119;
             num2 = 0;
             break;
         case 118:
         case 119:
             num3 = 117;
             num2 = 1;
             break;
         case 7:
             num3 = 9;
             num2 = 0;
             break;
         case 8:
         case 9:
             num3 = 7;
             num2 = 1;
             break;
         case 95:
             num3 = 97;
             num2 = 0;
             break;
         case 96:
         case 97:
             num3 = 95;
             num2 = 1;
             break;
         case 10:
             num3 = 12;
             num2 = 0;
             break;
         case 11:
         case 12:
             num3 = 10;
             num2 = 1;
             break;
         }
         if (num2 != -1)
         {
             if (seekHead && num2 == 1)
             {
                 index = -1;
                 pos = Vector2.Zero;
                 return false;
             }
             Vector2 center = Main.npc[i].Center;
             int num4 = -1;
             float num5 = -1f;
             int num6 = -1;
             Vector2 center2 = Main.player[Main.myPlayer].Center;
             int num7 = (int)Main.npc[i].ai[num2];
             int num8 = 0;
             while (num7 >= 0 && num7 < 200 && ++num8 < 100 && Main.npc[num7].active)
             {
                 if (!averageDirection && (num6 == -1 || Main.npc[num7].Distance(center2) < num5))
                 {
                     num5 = Main.npc[num7].Distance(center2);
                     num6 = num7;
                 }
                 if (Main.npc[num7].type == num3)
                 {
                     num4 = num7;
                     break;
                 }
                 num7 = (int)Main.npc[num7].ai[num2];
             }
             if (num4 >= 0)
             {
                 if (!averageDirection)
                 {
                     pos = Main.npc[num6].Center;
                     index = num6;
                 }
                 else
                 {
                     center += Main.npc[num4].Center;
                     pos = center / 2f;
                     index = num4;
                 }
                 return true;
             }
             pos = Vector2.Zero;
             index = -1;
             return false;
         }
         pos = Main.npc[i].Center;
         index = i;
         return true;
     }
References Entity.active, ai, Entity.Center, Entity.Distance(), Main.myPlayer, Main.npc, Main.player, and type.
Referenced by LockOnHelper.Draw(), and Main.DrawInterface_14_EntityHealthBars().