Terraria: NPC.AI_001_Slimes
AI_001_Slimes()
void NPC.AI_001_Slimes () inline private
     {
         if (type == 1 && (ai[1] == 1f || ai[1] == 2f || ai[1] == 3f))
         {
             ai[1] = -1f;
         }
         if (type == 1 && ai[1] == 75f)
         {
             float num = 0.3f;
             Lighting.AddLight((int)(base.Center.X / 16f), (int)(base.Center.Y / 16f), 0.8f * num, 0.7f * num, 0.1f * num);
             if (Main.rand.Next(12) == 0)
             {
                 Dust dust = Dust.NewDustPerfect(base.Center + new Vector2(0f, (float)height * 0.2f) + Main.rand.NextVector2CircularEdge(width, (float)height * 0.6f) * (0.3f + Main.rand.NextFloat() * 0.5f), 228, new Vector2(0f, (0f - Main.rand.NextFloat()) * 0.3f - 1.5f), 127);
                 dust.scale = 0.5f;
                 dust.fadeIn = 1.1f;
                 dust.noGravity = true;
                 dust.noLight = true;
             }
         }
         if (type == 1 && ai[1] == 0f && Main.netMode != 1 && value > 0f)
         {
             ai[1] = -1f;
             if (Main.remixWorld && ai[0] != -999f && Main.rand.Next(3) == 0)
             {
                 ai[1] = 75f;
                 netUpdate = true;
             }
             else if (Main.rand.Next(20) == 0)
             {
                 int num2 = AI_001_Slimes_GenerateItemInsideBody(ai[0] == -999f);
                 ai[1] = num2;
                 netUpdate = true;
             }
         }
         if (type == 1 && ai[0] == -999f)
         {
             frame.Y = 0;
             frameCounter = 0.0;
             rotation = 0f;
             return;
         }
         if (type == 244)
         {
             float num3 = (float)Main.DiscoR / 255f;
             float num4 = (float)Main.DiscoG / 255f;
             float num5 = (float)Main.DiscoB / 255f;
             num3 *= 1f;
             num4 *= 1f;
             num5 *= 1f;
             Lighting.AddLight((int)((position.X + (float)(width / 2)) / 16f), (int)((position.Y + (float)(height / 2)) / 16f), num3, num4, num5);
             AI_001_SetRainbowSlimeColor();
         }
         bool flag = false;
         if (!Main.dayTime || life != lifeMax || (double)position.Y > Main.worldSurface * 16.0 || Main.slimeRain)
         {
             flag = true;
         }
         if (Main.remixWorld && type == 59 && life == lifeMax)
         {
             flag = false;
         }
         if (type == 81)
         {
             flag = true;
             if (Main.rand.Next(30) == 0)
             {
                 position += netOffset;
                 int num6 = Dust.NewDust(position, width, height, 14, 0f, 0f, alpha, this.color);
                 Main.dust[num6].velocity *= 0.3f;
                 position -= netOffset;
             }
         }
         if ((type == 377 || type == 446) && target != 255 && !Main.player[target].dead && Vector2.Distance(base.Center, Main.player[target].Center) <= 200f && !wet)
         {
             flag = true;
         }
         if (type == 183)
         {
             flag = true;
         }
         if (type == 304)
         {
             flag = true;
         }
         if (type == 667)
         {
             flag = true;
         }
         if (type == 244)
         {
             flag = true;
             ai[0] += 2f;
         }
         if (type == 147 && Main.rand.Next(10) == 0)
         {
             position += netOffset;
             int num7 = Dust.NewDust(position, width, height, 76);
             Main.dust[num7].noGravity = true;
             Main.dust[num7].velocity *= 0.1f;
             position -= netOffset;
         }
         if (type == 667)
         {
             Color color = new Color(204, 181, 72, 255);
             Lighting.AddLight((int)(base.Center.X / 16f), (int)(base.Center.Y / 16f), (float)(int)color.R / 255f * 1.1f, (float)(int)color.G / 255f * 1.1f, (float)(int)color.B / 255f * 1.1f);
             if (velocity.Length() > 1f || Main.rand.Next(4) != 0)
             {
                 int num8 = 8;
                 Vector2 vector = position + new Vector2(-num8, -num8);
                 int num9 = width + num8 * 2;
                 int num10 = height + num8 * 2;
                 position += netOffset;
                 int num11 = Dust.NewDust(vector, num9, num10, 246);
                 Main.dust[num11].noGravity = true;
                 Main.dust[num11].noLightEmittence = true;
                 Main.dust[num11].velocity *= 0.2f;
                 Main.dust[num11].scale = 1.5f;
                 position -= netOffset;
             }
         }
         if (type == 676)
         {
             Lighting.AddLight(base.Center, 23);
             if ((velocity.Length() > 1f && Main.rand.Next(3) == 0) || Main.rand.Next(5) == 0)
             {
                 Dust dust2 = Dust.NewDustPerfect(Main.rand.NextVector2FromRectangle(base.Hitbox), 306);
                 dust2.noGravity = true;
                 dust2.noLightEmittence = true;
                 dust2.alpha = 127;
                 dust2.color = Main.hslToRgb(((float)Main.timeForVisualEffects / 300f + Main.rand.NextFloat() * 0.1f) % 1f, 1f, 0.65f);
                 dust2.color.A = 0;
                 dust2.velocity = dust2.position - base.Center;
                 dust2.velocity *= 0.1f;
                 dust2.velocity.X *= 0.25f;
                 if (dust2.velocity.Y > 0f)
                 {
                     dust2.velocity.Y *= -1f;
                 }
                 dust2.scale = Main.rand.NextFloat() * 0.3f + 0.5f;
                 dust2.fadeIn = 0.9f;
                 dust2.position += netOffset;
             }
         }
         if (type == 184)
         {
             if (Main.rand.Next(8) == 0)
             {
                 position += netOffset;
                 int num12 = Dust.NewDust(position - velocity, width, height, 76);
                 Main.dust[num12].noGravity = true;
                 Main.dust[num12].velocity *= 0.15f;
                 position -= netOffset;
             }
             flag = true;
             if (localAI[0] > 0f)
             {
                 localAI[0] -= 1f;
             }
             if (!wet && !Main.player[target].npcTypeNoAggro[type])
             {
                 Vector2 vector2 = new Vector2(position.X + (float)width * 0.5f, position.Y + (float)height * 0.5f);
                 float num13 = Main.player[target].position.X + (float)Main.player[target].width * 0.5f - vector2.X;
                 float num14 = Main.player[target].position.Y - vector2.Y;
                 float num15 = (float)Math.Sqrt(num13 * num13 + num14 * num14);
                 if (Main.expertMode && num15 < 120f && Collision.CanHit(position, width, height, Main.player[target].position, Main.player[target].width, Main.player[target].height) && velocity.Y == 0f)
                 {
                     ai[0] = -40f;
                     if (velocity.Y == 0f)
                     {
                         velocity.X *= 0.9f;
                     }
                     if (Main.netMode != 1 && localAI[0] == 0f)
                     {
                         for (int i = 0; i < 5; i++)
{
                             Vector2 vector3 = new Vector2(i - 2, -4f);
                             vector3.X *= 1f + (float)Main.rand.Next(-50, 51) * 0.005f;
                             vector3.Y *= 1f + (float)Main.rand.Next(-50, 51) * 0.005f;
                             vector3.Normalize();
                             vector3 *= 4f + (float)Main.rand.Next(-50, 51) * 0.01f;
                             int attackDamage_ForProjectiles = GetAttackDamage_ForProjectiles(9f, 9f);
                             Projectile.NewProjectile(GetSpawnSource_ForProjectile(), vector2.X, vector2.Y, vector3.X, vector3.Y, 174, attackDamage_ForProjectiles, 0f, Main.myPlayer);
                             localAI[0] = 30f;
                         }
                     }
                 }
                 else if (num15 < 200f && Collision.CanHit(position, width, height, Main.player[target].position, Main.player[target].width, Main.player[target].height) && velocity.Y == 0f)
                 {
                     ai[0] = -40f;
                     if (velocity.Y == 0f)
                     {
                         velocity.X *= 0.9f;
                     }
                     if (Main.netMode != 1 && localAI[0] == 0f)
                     {
                         num14 = Main.player[target].position.Y - vector2.Y - (float)Main.rand.Next(0, 200);
                         num15 = (float)Math.Sqrt(num13 * num13 + num14 * num14);
                         num15 = 4.5f / num15;
                         num13 *= num15;
                         num14 *= num15;
                         localAI[0] = 50f;
                         Projectile.NewProjectile(GetSpawnSource_ForProjectile(), vector2.X, vector2.Y, num13, num14, 174, 9, 0f, Main.myPlayer);
                     }
                 }
             }
         }
         if (type == 535)
         {
             flag = true;
             if (localAI[0] > 0f)
             {
                 localAI[0] -= 1f;
             }
             if (!wet && !Main.player[target].npcTypeNoAggro[type])
             {
                 Vector2 vector4 = new Vector2(position.X + (float)width * 0.5f, position.Y + (float)height * 0.5f);
                 float num16 = Main.player[target].position.X + (float)Main.player[target].width * 0.5f - vector4.X;
                 float num17 = Main.player[target].position.Y - vector4.Y;
                 float num18 = (float)Math.Sqrt(num16 * num16 + num17 * num17);
                 if (Main.expertMode && num18 < 120f && Collision.CanHit(position, width, height, Main.player[target].position, Main.player[target].width, Main.player[target].height) && velocity.Y == 0f)
                 {
                     ai[0] = -40f;
                     if (velocity.Y == 0f)
                     {
                         velocity.X *= 0.9f;
                     }
                     if (Main.netMode != 1 && localAI[0] == 0f)
                     {
                         for (int j = 0; j < 5; j++)
{
                             Vector2 vector5 = new Vector2(j - 2, -4f);
                             vector5.X *= 1f + (float)Main.rand.Next(-50, 51) * 0.005f;
                             vector5.Y *= 1f + (float)Main.rand.Next(-50, 51) * 0.005f;
                             vector5.Normalize();
                             vector5 *= 4f + (float)Main.rand.Next(-50, 51) * 0.01f;
                             int attackDamage_ForProjectiles2 = GetAttackDamage_ForProjectiles(9f, 9f);
                             Projectile.NewProjectile(GetSpawnSource_ForProjectile(), vector4.X, vector4.Y, vector5.X, vector5.Y, 605, attackDamage_ForProjectiles2, 0f, Main.myPlayer);
                             localAI[0] = 30f;
                         }
                     }
                 }
                 else if (num18 < 200f && Collision.CanHit(position, width, height, Main.player[target].position, Main.player[target].width, Main.player[target].height) && velocity.Y == 0f)
                 {
                     ai[0] = -40f;
                     if (velocity.Y == 0f)
                     {
                         velocity.X *= 0.9f;
                     }
                     if (Main.netMode != 1 && localAI[0] == 0f)
                     {
                         num17 = Main.player[target].position.Y - vector4.Y - (float)Main.rand.Next(0, 200);
                         num18 = (float)Math.Sqrt(num16 * num16 + num17 * num17);
                         num18 = 4.5f / num18;
                         num16 *= num18;
                         num17 *= num18;
                         localAI[0] = 50f;
                         Projectile.NewProjectile(GetSpawnSource_ForProjectile(), vector4.X, vector4.Y, num16, num17, 605, 9, 0f, Main.myPlayer);
                     }
                 }
             }
         }
         if (type == 658)
         {
             flag = true;
             if (localAI[0] > 0f)
             {
                 localAI[0] -= 1f;
             }
             if (!wet && Main.player[target].active && !Main.player[target].dead && !Main.player[target].npcTypeNoAggro[type])
             {
                 Player obj = Main.player[target];
                 Vector2 center = base.Center;
                 float num19 = obj.Center.X - center.X;
                 float num20 = obj.Center.Y - center.Y;
                 float num21 = (float)Math.Sqrt(num19 * num19 + num20 * num20);
                 int num22 = CountNPCS(658);
                 if (Main.expertMode && num22 < 5 && Math.Abs(num19) < 500f && Math.Abs(num20) < 550f && Collision.CanHit(position, width, height, Main.player[target].position, Main.player[target].width, Main.player[target].height) && velocity.Y == 0f)
                 {
                     ai[0] = -40f;
                     if (velocity.Y == 0f)
                     {
                         velocity.X *= 0.9f;
                     }
                     if (Main.netMode != 1 && localAI[0] == 0f)
                     {
                         for (int k = 0; k < 3; k++)
{
                             Vector2 vector6 = new Vector2(k - 1, -4f);
                             vector6.X *= 1f + (float)Main.rand.Next(-50, 51) * 0.005f;
                             vector6.Y *= 1f + (float)Main.rand.Next(-50, 51) * 0.005f;
                             vector6.Normalize();
                             vector6 *= 6f + (float)Main.rand.Next(-50, 51) * 0.01f;
                             if (num21 > 350f)
{
                                 vector6 *= 2f;
                             }
                             else if (num21 > 250f)
{
                                 vector6 *= 1.5f;
                             }
                             int attackDamage_ForProjectiles_MultiLerp = GetAttackDamage_ForProjectiles_MultiLerp(15f, 17f, 20f);
                             Projectile.NewProjectile(GetSpawnSource_ForProjectile(), center.X, center.Y, vector6.X, vector6.Y, 920, attackDamage_ForProjectiles_MultiLerp, 0f, Main.myPlayer);
                             localAI[0] = 25f;
                             if (num22 > 4)
{
                                 break;
                             }
                         }
                     }
                 }
                 else if (Math.Abs(num19) < 500f && Math.Abs(num20) < 550f && Collision.CanHit(position, width, height, Main.player[target].position, Main.player[target].width, Main.player[target].height) && velocity.Y == 0f)
                 {
                     float num23 = num21;
                     ai[0] = -40f;
                     if (velocity.Y == 0f)
                     {
                         velocity.X *= 0.9f;
                     }
                     if (Main.netMode != 1 && localAI[0] == 0f)
                     {
                         num20 = Main.player[target].position.Y - center.Y - (float)Main.rand.Next(0, 200);
                         num21 = (float)Math.Sqrt(num19 * num19 + num20 * num20);
                         num21 = 4.5f / num21;
                         num21 *= 2f;
                         if (num23 > 350f)
{
                             num21 *= 2f;
                         }
                         else if (num23 > 250f)
{
                             num21 *= 1.5f;
                         }
                         num19 *= num21;
                         num20 *= num21;
                         localAI[0] = 50f;
                         int attackDamage_ForProjectiles_MultiLerp2 = GetAttackDamage_ForProjectiles_MultiLerp(15f, 17f, 20f);
                         Projectile.NewProjectile(GetSpawnSource_ForProjectile(), center.X, center.Y, num19, num20, 920, attackDamage_ForProjectiles_MultiLerp2, 0f, Main.myPlayer);
                     }
                 }
             }
         }
         if (type == 659)
         {
             flag = true;
             if (localAI[0] > 0f)
             {
                 localAI[0] -= 1f;
             }
             if (!wet && Main.player[target].active && !Main.player[target].dead && !Main.player[target].npcTypeNoAggro[type])
             {
                 Player obj2 = Main.player[target];
                 Vector2 center2 = base.Center;
                 float num24 = obj2.Center.X - center2.X;
                 float num25 = obj2.Center.Y - center2.Y;
                 float num26 = (float)Math.Sqrt(num24 * num24 + num25 * num25);
                 float num27 = num26;
                 if (Math.Abs(num24) < 500f && Math.Abs(num25) < 550f && Collision.CanHit(position, width, height, Main.player[target].position, Main.player[target].width, Main.player[target].height) && velocity.Y == 0f)
                 {
                     ai[0] = -40f;
                     if (velocity.Y == 0f)
                     {
                         velocity.X *= 0.9f;
                     }
                     if (Main.netMode != 1 && localAI[0] == 0f)
                     {
                         num25 = Main.player[target].position.Y - center2.Y - (float)Main.rand.Next(0, 200);
                         num26 = (float)Math.Sqrt(num24 * num24 + num25 * num25);
                         num26 = 4.5f / num26;
                         num26 *= 2f;
                         if (num27 > 350f)
{
                             num26 *= 1.75f;
                         }
                         else if (num27 > 250f)
{
                             num26 *= 1.25f;
                         }
                         num24 *= num26;
                         num25 *= num26;
                         localAI[0] = 40f;
                         if (Main.expertMode)
{
                             localAI[0] = 30f;
                         }
                         int attackDamage_ForProjectiles_MultiLerp3 = GetAttackDamage_ForProjectiles_MultiLerp(15f, 17f, 20f);
                         Projectile.NewProjectile(GetSpawnSource_ForProjectile(), center2.X, center2.Y, num24, num25, 921, attackDamage_ForProjectiles_MultiLerp3, 0f, Main.myPlayer);
                     }
                 }
             }
         }
         if (type == 204)
         {
             flag = true;
             if (localAI[0] > 0f)
             {
                 localAI[0] -= 1f;
             }
             if (!wet && !Main.player[target].npcTypeNoAggro[type])
             {
                 Vector2 vector7 = new Vector2(position.X + (float)width * 0.5f, position.Y + (float)height * 0.5f);
                 float num28 = Main.player[target].position.X + (float)Main.player[target].width * 0.5f - vector7.X;
                 float num29 = Main.player[target].position.Y - vector7.Y;
                 float num30 = (float)Math.Sqrt(num28 * num28 + num29 * num29);
                 if (Main.expertMode && num30 < 200f && Collision.CanHit(new Vector2(position.X, position.Y - 20f), width, height + 20, Main.player[target].position, Main.player[target].width, Main.player[target].height) && velocity.Y == 0f)
                 {
                     ai[0] = -40f;
                     if (velocity.Y == 0f)
                     {
                         velocity.X *= 0.9f;
                     }
                     if (Main.netMode != 1 && localAI[0] == 0f)
                     {
                         for (int l = 0; l < 5; l++)
{
                             Vector2 vector8 = new Vector2(l - 2, -2f);
                             vector8.X *= 1f + (float)Main.rand.Next(-50, 51) * 0.02f;
                             vector8.Y *= 1f + (float)Main.rand.Next(-50, 51) * 0.02f;
                             vector8.Normalize();
                             vector8 *= 3f + (float)Main.rand.Next(-50, 51) * 0.01f;
                             int attackDamage_ForProjectiles3 = GetAttackDamage_ForProjectiles(13f, 13f);
                             Projectile.NewProjectile(GetSpawnSource_ForProjectile(), vector7.X, vector7.Y, vector8.X, vector8.Y, 176, attackDamage_ForProjectiles3, 0f, Main.myPlayer);
                             localAI[0] = 80f;
                         }
                     }
                 }
                 if (num30 < 400f && Collision.CanHit(new Vector2(position.X, position.Y - 20f), width, height + 20, Main.player[target].position, Main.player[target].width, Main.player[target].height) && velocity.Y == 0f)
                 {
                     ai[0] = -80f;
                     if (velocity.Y == 0f)
                     {
                         velocity.X *= 0.9f;
                     }
                     if (Main.netMode != 1 && localAI[0] == 0f)
                     {
                         num29 = Main.player[target].position.Y - vector7.Y - (float)Main.rand.Next(-30, 20);
                         num29 -= num30 * 0.05f;
                         num28 = Main.player[target].position.X - vector7.X - (float)Main.rand.Next(-20, 20);
                         num30 = (float)Math.Sqrt(num28 * num28 + num29 * num29);
                         num30 = 7f / num30;
                         num28 *= num30;
                         num29 *= num30;
                         localAI[0] = 65f;
                         Projectile.NewProjectile(GetSpawnSource_ForProjectile(), vector7.X, vector7.Y, num28, num29, 176, 13, 0f, Main.myPlayer);
                     }
                 }
             }
         }
         if (type == 377 || type == 446)
         {
             if (localAI[2] < 90f)
             {
                 localAI[2] += 1f;
             }
             else
             {
                 friendly = false;
             }
         }
         if (type == 59)
         {
             position += netOffset;
             Lighting.AddLight((int)((position.X + (float)(width / 2)) / 16f), (int)((position.Y + (float)(height / 2)) / 16f), 1f, 0.3f, 0.1f);
             int num31 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 6, velocity.X * 0.2f, velocity.Y * 0.2f, 100, default(Color), 1.7f);
             Main.dust[num31].noGravity = true;
             position -= netOffset;
         }
         if (ai[2] > 1f)
         {
             ai[2] -= 1f;
         }
         if (wet)
         {
             if (collideY)
             {
                 velocity.Y = -2f;
             }
             if (velocity.Y < 0f && ai[3] == position.X)
             {
                 direction *= -1;
                 ai[2] = 200f;
             }
             if (velocity.Y > 0f)
             {
                 ai[3] = position.X;
             }
             if (type == 59 && !Main.remixWorld)
             {
                 if (velocity.Y > 2f)
                 {
                     velocity.Y *= 0.9f;
                 }
                 else if (directionY < 0)
                 {
                     velocity.Y -= 0.8f;
                 }
                 velocity.Y -= 0.5f;
                 if (velocity.Y < -10f)
                 {
                     velocity.Y = -10f;
                 }
             }
             else
             {
                 if (velocity.Y > 2f)
                 {
                     velocity.Y *= 0.9f;
                 }
                 velocity.Y -= 0.5f;
                 if (velocity.Y < -4f)
                 {
                     velocity.Y = -4f;
                 }
             }
             if (ai[2] == 1f && flag)
             {
                 TargetClosest();
             }
         }
         aiAction = 0;
         if (ai[2] == 0f)
         {
             ai[0] = -100f;
             ai[2] = 1f;
             TargetClosest();
         }
         if (velocity.Y == 0f)
         {
             if (collideY && oldVelocity.Y != 0f && Collision.SolidCollision(position, width, height))
             {
                 position.X -= velocity.X + (float)direction;
             }
             if (ai[3] == position.X)
             {
                 direction *= -1;
                 ai[2] = 200f;
             }
             ai[3] = 0f;
             velocity.X *= 0.8f;
             if ((double)velocity.X > -0.1 && (double)velocity.X < 0.1)
             {
                 velocity.X = 0f;
             }
             if (flag)
             {
                 ai[0] += 1f;
             }
             ai[0] += 1f;
             if (type == 59 && !Main.remixWorld)
             {
                 ai[0] += 2f;
             }
             if (type == 71)
             {
                 ai[0] += 3f;
             }
             if (type == 667)
             {
                 ai[0] += 3f;
             }
             if (type == 138)
             {
                 ai[0] += 2f;
             }
             if (type == 183)
             {
                 ai[0] += 1f;
             }
             if (type == 658)
             {
                 ai[0] += 5f;
             }
             if (type == 659)
             {
                 ai[0] += 3f;
             }
             if (type == 304)
             {
                 float num32 = (1 - life / lifeMax) * 10;
                 ai[0] += num32;
             }
             if (type == 377 || type == 446)
             {
                 ai[0] += 3f;
             }
             if (type == 81)
             {
                 if (scale >= 0f)
                 {
                     ai[0] += 4f;
                 }
                 else
                 {
                     ai[0] += 1f;
                 }
             }
             float num33 = -1000f;
             if (type == 659)
             {
                 num33 = -500f;
             }
             if (type == 667)
             {
                 num33 = -400f;
             }
             int num34 = 0;
             if (ai[0] >= 0f)
             {
                 num34 = 1;
             }
             if (ai[0] >= num33 && ai[0] <= num33 * 0.5f)
             {
                 num34 = 2;
             }
             if (ai[0] >= num33 * 2f && ai[0] <= num33 * 1.5f)
             {
                 num34 = 3;
             }
             if (num34 > 0)
             {
                 netUpdate = true;
                 if (flag && ai[2] == 1f)
                 {
                     TargetClosest();
                 }
                 if (num34 == 3)
                 {
                     velocity.Y = -8f;
                     if (type == 59 && !Main.remixWorld)
                     {
                         velocity.Y -= 2f;
                     }
                     velocity.X += 3 * direction;
                     if (type == 59 && !Main.remixWorld)
                     {
                         velocity.X += 0.5f * (float)direction;
                     }
                     ai[0] = -200f;
                     ai[3] = position.X;
                 }
                 else
                 {
                     velocity.Y = -6f;
                     velocity.X += 2 * direction;
                     if (type == 59 && !Main.remixWorld)
                     {
                         velocity.X += 2 * direction;
                     }
                     ai[0] = -120f;
                     if (num34 == 1)
                     {
                         ai[0] += num33;
                     }
                     else
                     {
                         ai[0] += num33 * 2f;
                     }
                 }
                 if (type == 659)
                 {
                     velocity.Y *= 1.6f;
                     velocity.X *= 1.2f;
                 }
                 if (type == 685)
                 {
                     velocity.Y *= 0.5f;
                     velocity.X *= 0.2f;
                     if (Main.rand.Next(2) == 0)
                     {
                         direction *= -1;
                     }
                 }
                 if (type == 141)
                 {
                     velocity.Y *= 1.3f;
                     velocity.X *= 1.2f;
                 }
                 if (type == 377 || type == 446)
                 {
                     velocity.Y *= 0.9f;
                     velocity.X *= 0.6f;
                     if (flag)
                     {
                         direction = -direction;
                         velocity.X *= -1f;
                     }
                     int i2 = (int)(base.Center.X / 16f);
                     int j2 = (int)(base.Center.Y / 16f) - 1;
                     if (WorldGen.SolidTile(i2, j2) && 0f - velocity.Y + (float)height > 16f)
                     {
                         velocity.Y = -(16 - height);
                     }
                 }
             }
             else if (ai[0] >= -30f)
             {
                 aiAction = 1;
             }
         }
         else if (target < 255 && ((direction == 1 && velocity.X < 3f) || (direction == -1 && velocity.X > -3f)))
         {
             if (collideX && Math.Abs(velocity.X) == 0.2f)
             {
                 position.X -= 1.4f * (float)direction;
             }
             if (collideY && oldVelocity.Y != 0f && Collision.SolidCollision(position, width, height))
             {
                 position.X -= velocity.X + (float)direction;
             }
             if ((direction == -1 && (double)velocity.X < 0.01) || (direction == 1 && (double)velocity.X > -0.01))
             {
                 velocity.X += 0.2f * (float)direction;
             }
             else
             {
                 velocity.X *= 0.93f;
             }
         }
     }
References Entity.active, Lighting.AddLight(), ai, AI_001_SetRainbowSlimeColor(), AI_001_Slimes_GenerateItemInsideBody(), aiAction, Dust.alpha, alpha, Collision.CanHit(), Entity.Center, collideX, collideY, Color, Dust.color, color, CountNPCS(), Main.dayTime, Player.dead, Entity.direction, directionY, Main.DiscoB, Main.DiscoG, Main.DiscoR, Main.dust, Main.expertMode, Dust.fadeIn, frame, frameCounter, friendly, GetAttackDamage_ForProjectiles(), GetAttackDamage_ForProjectiles_MultiLerp(), GetSpawnSource_ForProjectile(), Entity.height, Main.hslToRgb(), life, lifeMax, localAI, Main.myPlayer, Main.netMode, netOffset, netUpdate, Dust.NewDust(), Dust.NewDustPerfect(), Projectile.NewProjectile(), UnifiedRandom.Next(), Dust.noGravity, Dust.noLight, Dust.noLightEmittence, Player.npcTypeNoAggro, Entity.oldVelocity, Main.player, Dust.position, Entity.position, Main.rand, Main.remixWorld, rotation, Dust.scale, scale, Main.slimeRain, Collision.SolidCollision(), WorldGen.SolidTile(), target, TargetClosest(), Main.timeForVisualEffects, type, value, Dust.velocity, Entity.velocity, Entity.wet, Entity.width, and Main.worldSurface.
Referenced by AI().