Terraria: NPC.NPCCanStickToWalls
NPCCanStickToWalls()
bool NPC.NPCCanStickToWalls () inline
     {
         int num = (int)base.Center.X / 16;
         int num2 = (int)base.Center.Y / 16;
         int num3 = 0;
         for (int i = num - 1; i <= num + 1; i++)
         {
             for (int j = num2 - 1; j <= num2 + 1; j++)
             {
                 Tile tileSafely = Framing.GetTileSafely(i, j);
                 if ((!tileSafely.active() || !Main.tileSolid[tileSafely.type] || TileID.Sets.Platforms[tileSafely.type]) && tileSafely.wall > 0)
                 {
                     num3++;
                     if (num3 > 4)
                     {
                         return true;
                     }
                 }
             }
         }
         return false;
     }
References Tile.active(), Framing.GetTileSafely(), TileID.Sets.Platforms, Main.tileSolid, Tile.type, and Tile.wall.
Referenced by AI(), and AI_003_Fighters().