Terraria: NPC.AddBuff
AddBuff()
void NPC.AddBuff (int type, int time, bool quiet = false) inline
     {
         if (buffImmune[type])
         {
             return;
         }
         if (!quiet)
         {
             if (Main.netMode == 1)
             {
                 NetMessage.SendData(53, -1, -1, null, whoAmI, type, time);
             }
             else if (Main.netMode == 2)
             {
                 NetMessage.SendData(54, -1, -1, null, whoAmI);
             }
         }
         int num = -1;
         for (int i = 0; i < maxBuffs; i++)
         {
             if (buffType[i] == type)
             {
                 if (buffTime[i] < time)
                 {
                     buffTime[i] = time;
                 }
                 return;
             }
         }
         while (num == -1)
         {
             int num2 = -1;
             for (int j = 0; j < maxBuffs; j++)
             {
                 if (!Main.debuff[buffType[j]])
                 {
                     num2 = j;
                     break;
                 }
             }
             if (num2 == -1)
             {
                 return;
             }
             for (int k = num2; k < maxBuffs; k++)
             {
                 if (buffType[k] == 0)
                 {
                     num = k;
                     break;
                 }
             }
             if (num == -1)
             {
                 DelBuff(num2);
             }
         }
         buffType[num] = type;
         buffTime[num] = time;
     }
References Main.debuff, Main.netMode, and NetMessage.SendData().
Referenced by Projectile.AI_111_DryadsWard(), MessageBuffer.GetData(), HitEffect(), Player.Hurt(), Projectile.StatusNPC(), Player.StatusToNPC(), and Player.UpdateBuffs().