Terraria: NPC.CheckActive
CheckActive()
void NPC.CheckActive () inline
     {
         if (!active || DoesntDespawnToInactivity())
         {
             return;
         }
         if (townNPC)
         {
             AddIntoPlayersTownNPCSlots();
             return;
         }
         bool flag = DoesntDespawnToInactivityAndCountsNPCSlots();
         bool flag2 = false;
         Rectangle rectangle = new Rectangle((int)(position.X + (float)(width / 2) - (float)activeRangeX), (int)(position.Y + (float)(height / 2) - (float)activeRangeY), activeRangeX * 2, activeRangeY * 2);
         Rectangle rectangle2 = new Rectangle((int)((double)(position.X + (float)(width / 2)) - (double)sWidth * 0.5 - (double)width), (int)((double)(position.Y + (float)(height / 2)) - (double)sHeight * 0.5 - (double)height), sWidth + width * 2, sHeight + height * 2);
         for (int i = 0; i < 255; i++)
         {
             if (!Main.player[i].active)
             {
                 continue;
             }
             Rectangle hitbox = Main.player[i].Hitbox;
             if (rectangle.Intersects(hitbox))
             {
                 flag2 = true;
                 if (type != 25 && type != 30 && type != 33 && releaseOwner == 255 && lifeMax > 0)
                 {
                     if (Main.slimeRain && Main.slimeRainNPC[type])
                     {
                         Main.player[i].nearbyActiveNPCs += npcSlots * Main.slimeRainNPCSlots;
                     }
                     else
                     {
                         Main.player[i].nearbyActiveNPCs += npcSlots;
                     }
                 }
             }
             if (flag)
             {
                 continue;
             }
             if (rectangle2.Intersects(hitbox))
             {
                 timeLeft = activeTime;
                 despawnEncouraged = false;
                 if (i == Main.myPlayer && (type == 604 || type == 605))
                 {
                     LadyBugLuck(i, type == 605);
                 }
             }
             if (boss)
             {
                 flag2 = true;
             }
             switch (type)
             {
             case 7:
             case 10:
             case 13:
             case 35:
             case 36:
             case 39:
             case 87:
             case 127:
             case 128:
             case 129:
             case 130:
             case 131:
             case 392:
             case 393:
             case 394:
             case 491:
             case 492:
                 flag2 = true;
                 break;
             case 399:
                 if (ai[0] == 2f || ai[0] == 1f)
                 {
                     timeLeft = activeTime;
                 }
                 flag2 = true;
                 break;
             case 583:
             case 584:
             case 585:
                 if (!Main.dayTime && ai[2] == 0f)
                 {
                     flag2 = true;
                     timeLeft = activeTime;
                 }
                 break;
             }
         }
         if (flag)
         {
             return;
         }
         timeLeft--;
         if (timeLeft <= 0)
         {
             flag2 = false;
         }
         if (!flag2 && Main.netMode != 1)
         {
             noSpawnCycle = true;
             active = false;
             if (Main.netMode == 2)
             {
                 netSkip = -1;
                 life = 0;
                 NetMessage.SendData(23, -1, -1, null, whoAmI);
             }
             if (extraValue > 0)
             {
                 RevengeManager.CacheEnemy(this);
             }
             CheckActive_WormSegments();
         }
     }
References Entity.active, activeRangeX, activeRangeY, activeTime, AddIntoPlayersTownNPCSlots(), ai, boss, CoinLossRevengeSystem.CacheEnemy(), CheckActive_WormSegments(), Main.dayTime, despawnEncouraged, DoesntDespawnToInactivity(), DoesntDespawnToInactivityAndCountsNPCSlots(), extraValue, Entity.height, Entity.Hitbox, LadyBugLuck(), life, lifeMax, Main.myPlayer, Player.nearbyActiveNPCs, Main.netMode, netSkip, noSpawnCycle, npcSlots, Main.player, Entity.position, releaseOwner, RevengeManager, NetMessage.SendData(), sHeight, Main.slimeRain, Main.slimeRainNPC, Main.slimeRainNPCSlots, sWidth, timeLeft, townNPC, type, Entity.whoAmI, and Entity.width.