Terraria: NPC.DoDeathEvents_CelebrateBossDeath
DoDeathEvents_CelebrateBossDeath()
void NPC.DoDeathEvents_CelebrateBossDeath () inline private
     {
         if (type == 125 || type == 126)
         {
             if (Main.netMode == 0)
             {
                 Main.NewText(Language.GetTextValue("Announcement.HasBeenDefeated_Plural", Language.GetTextValue("Enemies.TheTwins")), 175, 75);
             }
             else if (Main.netMode == 2)
             {
                 ChatHelper.BroadcastChatMessage(NetworkText.FromKey("Announcement.HasBeenDefeated_Plural", NetworkText.FromKey("Enemies.TheTwins")), new Color(175, 75, 255));
             }
         }
         else if (type == 398)
         {
             if (Main.netMode == 0)
             {
                 Main.NewText(Language.GetTextValue("Announcement.HasBeenDefeated_Single", Language.GetTextValue("Enemies.MoonLord")), 175, 75);
             }
             else if (Main.netMode == 2)
             {
                 ChatHelper.BroadcastChatMessage(NetworkText.FromKey("Announcement.HasBeenDefeated_Single", NetworkText.FromKey("Enemies.MoonLord")), new Color(175, 75, 255));
             }
         }
         else if (Main.netMode == 0)
         {
             Main.NewText(Language.GetTextValue("Announcement.HasBeenDefeated_Single", TypeName), 175, 75);
         }
         else if (Main.netMode == 2)
         {
             ChatHelper.BroadcastChatMessage(NetworkText.FromKey("Announcement.HasBeenDefeated_Single", GetTypeNetName()), new Color(175, 75, 255));
         }
     }
References ChatHelper.BroadcastChatMessage(), Color, NetworkText.FromKey(), Language.GetTextValue(), GetTypeNetName(), Main.netMode, Main.NewText(), type, and TypeName.
Referenced by DoDeathEvents().