Terraria: NPC.AI_006_Worms
AI_006_Worms()
void NPC.AI_006_Worms () inline private
     {
         if (type == 117 && localAI[1] == 0f)
         {
             localAI[1] = 1f;
             SoundEngine.PlaySound(SoundID.NPCDeath13, position);
             int num = 1;
             if (velocity.X < 0f)
             {
                 num = -1;
             }
             for (int i = 0; i < 20; i++)
             {
                 Dust.NewDust(new Vector2(position.X - 20f, position.Y - 20f), width + 40, height + 40, 5, num * 8, -1f);
             }
         }
         if (type == 454 && localAI[3] == 0f)
         {
             SoundEngine.PlaySound(SoundID.Item119, position);
             localAI[3] = 1f;
         }
         if (type >= 454 && type <= 459)
         {
             dontTakeDamage = alpha > 0;
             if (type == 454 || (type != 454 && Main.npc[(int)ai[1]].alpha < 85))
             {
                 if (dontTakeDamage)
                 {
                     for (int j = 0; j < 2; j++)
                     {
                         int num2 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 228, 0f, 0f, 100, default(Color), 2f);
                         Main.dust[num2].noGravity = true;
                         Main.dust[num2].noLight = true;
                     }
                 }
                 alpha -= 42;
                 if (alpha < 0)
                 {
                     alpha = 0;
                 }
             }
         }
         if (type >= 621 && type <= 623)
         {
             position += netOffset;
             dontTakeDamage = alpha > 0;
             if (type == 621 || (type != 621 && Main.npc[(int)ai[1]].alpha < 85))
             {
                 if (dontTakeDamage)
                 {
                     for (int k = 0; k < 2; k++)
                     {
                         Dust.NewDust(position, width, height, 5, 0f, 0f, 100);
                     }
                 }
                 alpha -= 42;
                 if (alpha < 0)
                 {
                     alpha = 0;
                 }
             }
             if (alpha == 0 && Main.rand.Next(5) == 0)
             {
                 Dust.NewDust(position, width, height, 5, 0f, 0f, 100);
             }
             position -= netOffset;
         }
         else if (type == 402)
         {
             ai[2] += 1f;
             float num3 = 600f;
             float num4 = num3 - 30f;
             if (velocity.Length() >= 1f && ai[2] <= num4)
             {
                 velocity *= Utils.Remap(ai[2], num4 * 0.5f, num4, 1f, 0.5f);
             }
             if (ai[2] == num4)
             {
                 for (int l = 0; l < 50; l++)
                 {
                     Vector2 vector = Main.rand.NextVector2Circular(8f, 8f);
                     if (Main.rand.Next(2) == 0)
                     {
                         int num5 = Dust.NewDust(position, width, height, 180, 0f, 0f, 100);
                         Main.dust[num5].scale += (float)Main.rand.Next(50) * 0.04f;
                         Main.dust[num5].noGravity = true;
                         Main.dust[num5].velocity = vector;
                         Main.dust[num5].fadeIn = Main.rand.NextFloat() * 1.5f;
                     }
                     if (Main.rand.Next(2) == 0)
                     {
                         int num6 = Dust.NewDust(position, width, height, 176, 0f, 0f, 100);
                         Main.dust[num6].scale += 0.3f + (float)Main.rand.Next(50) * 0.01f;
                         Main.dust[num6].noGravity = true;
                         Main.dust[num6].velocity = vector;
                         Main.dust[num6].fadeIn = Main.rand.NextFloat() * 1.5f;
                     }
                 }
                 if (Main.netMode != 1)
                 {
                     SpawnStardustMark_StardustWorm();
                     velocity = velocity.SafeNormalize(Vector2.Zero) * 6f;
                     netUpdate = true;
                 }
             }
             if (ai[2] >= num3 && Main.netMode != 1)
             {
                 ai[2] = 0f;
                 netUpdate = true;
             }
         }
         if (Main.netMode != 1 && Main.expertMode)
         {
             if (type == 14 && ((double)(position.Y / 16f) < Main.worldSurface || Main.getGoodWorld))
             {
                 int num7 = (int)(base.Center.X / 16f);
                 int num8 = (int)(base.Center.Y / 16f);
                 if (WorldGen.InWorld(num7, num8) && Main.tile[num7, num8].wall == 0)
                 {
                     int num9 = 900;
                     if (Main.getGoodWorld)
                     {
                         num9 /= 2;
                     }
                     if (Main.rand.Next(num9) == 0)
                     {
                         TargetClosest();
                         if (Collision.CanHitLine(base.Center, 1, 1, Main.player[target].Center, 1, 1))
{
                             NewNPC(GetSpawnSourceForNPCFromNPCAI(), (int)(position.X + (float)(width / 2) + velocity.X), (int)(position.Y + (float)(height / 2) + velocity.Y), 666, 0, 0f, 1f);
                         }
                     }
                 }
             }
             else if (type == 13)
             {
                 int num10 = 90;
                 num10 += (int)((float)life / (float)lifeMax * 60f * 5f);
                 if (Main.rand.Next(num10) == 0)
                 {
                     TargetClosest();
                     if (Collision.CanHitLine(base.Center, 1, 1, Main.player[target].Center, 1, 1))
                     {
                         NewNPC(GetSpawnSourceForNPCFromNPCAI(), (int)(position.X + (float)(width / 2) + velocity.X), (int)(position.Y + (float)(height / 2) + velocity.Y), 666, 0, 0f, 1f);
                     }
                 }
             }
         }
         bool flag = false;
         float num11 = 0.2f;
         switch (type)
         {
         case 513:
             flag = !Main.player[target].ZoneUndergroundDesert;
             num11 = 0.1f;
             break;
         case 10:
         case 39:
         case 95:
         case 117:
         case 510:
             flag = true;
             break;
         case 621:
             flag = false;
             break;
         }
         if (type >= 13 && type <= 15)
         {
             realLife = -1;
         }
         else if (ai[3] > 0f)
         {
             realLife = (int)ai[3];
         }
         if (target < 0 || target == 255 || Main.player[target].dead || (flag && (double)Main.player[target].position.Y < Main.worldSurface * 16.0))
         {
             TargetClosest();
         }
         if (Main.player[target].dead || (flag && (double)Main.player[target].position.Y < Main.worldSurface * 16.0))
         {
             EncourageDespawn(300);
             if (flag)
             {
                 velocity.Y += num11;
             }
         }
         if (type == 621 && Main.dayTime)
         {
             EncourageDespawn(60);
             velocity.Y += 1f;
         }
         if (Main.netMode != 1)
         {
             if (type == 87 && ai[0] == 0f)
             {
                 ai[3] = whoAmI;
                 realLife = whoAmI;
                 int num12 = 0;
                 int num13 = whoAmI;
                 for (int m = 0; m < 14; m++)
                 {
                     int num14 = 89;
                     switch (m)
                     {
                     case 1:
                     case 8:
                         num14 = 88;
                         break;
                     case 11:
                         num14 = 90;
                         break;
                     case 12:
                         num14 = 91;
                         break;
                     case 13:
                         num14 = 92;
                         break;
                     }
                     num12 = NewNPC(GetSpawnSourceForNPCFromNPCAI(), (int)(position.X + (float)(width / 2)), (int)(position.Y + (float)height), num14, whoAmI);
                     Main.npc[num12].ai[3] = whoAmI;
                     Main.npc[num12].realLife = whoAmI;
                     Main.npc[num12].ai[1] = num13;
                     Main.npc[num12].CopyInteractions(this);
                     Main.npc[num13].ai[0] = num12;
                     NetMessage.SendData(23, -1, -1, null, num12);
                     num13 = num12;
                 }
             }
             if (type == 454 && ai[0] == 0f)
             {
                 ai[3] = whoAmI;
                 realLife = whoAmI;
                 int num15 = 0;
                 int num16 = whoAmI;
                 for (int n = 0; n < 30; n++)
                 {
                     int num17 = 456;
                     if ((n - 2) % 4 == 0 && n < 26)
                     {
                         num17 = 455;
                     }
                     else
                     {
                         switch (n)
{
                         case 27:
                             num17 = 457;
                             break;
                         case 28:
                             num17 = 458;
                             break;
                         case 29:
                             num17 = 459;
                             break;
                         }
                     }
                     num15 = NewNPC(GetSpawnSourceForNPCFromNPCAI(), (int)(position.X + (float)(width / 2)), (int)(position.Y + (float)height), num17, whoAmI);
                     Main.npc[num15].ai[3] = whoAmI;
                     Main.npc[num15].realLife = whoAmI;
                     Main.npc[num15].ai[1] = num16;
                     Main.npc[num15].CopyInteractions(this);
                     Main.npc[num16].ai[0] = num15;
                     NetMessage.SendData(23, -1, -1, null, num15);
                     num16 = num15;
                 }
             }
             if (type == 513 && ai[0] == 0f)
             {
                 ai[3] = whoAmI;
                 realLife = whoAmI;
                 int num18 = 0;
                 int num19 = whoAmI;
                 int num20 = Main.rand.Next(6, 10);
                 for (int num21 = 0; num21 < num20; num21++)
                 {
                     int num22 = 514;
                     if (num21 == num20 - 1)
                     {
                         num22 = 515;
                     }
                     num18 = NewNPC(GetSpawnSourceForNPCFromNPCAI(), (int)(position.X + (float)(width / 2)), (int)(position.Y + (float)height), num22, whoAmI);
                     Main.npc[num18].ai[3] = whoAmI;
                     Main.npc[num18].realLife = whoAmI;
                     Main.npc[num18].ai[1] = num19;
                     Main.npc[num18].CopyInteractions(this);
                     Main.npc[num19].ai[0] = num18;
                     NetMessage.SendData(23, -1, -1, null, num18);
                     num19 = num18;
                 }
             }
             if (type == 510 && ai[0] == 0f)
             {
                 ai[3] = whoAmI;
                 realLife = whoAmI;
                 int num23 = 0;
                 int num24 = whoAmI;
                 int num25 = Main.rand.Next(12, 21);
                 for (int num26 = 0; num26 < num25; num26++)
                 {
                     int num27 = 511;
                     if (num26 == num25 - 1)
                     {
                         num27 = 512;
                     }
                     num23 = NewNPC(GetSpawnSourceForNPCFromNPCAI(), (int)(position.X + (float)(width / 2)), (int)(position.Y + (float)height), num27, whoAmI);
                     Main.npc[num23].ai[3] = whoAmI;
                     Main.npc[num23].realLife = whoAmI;
                     Main.npc[num23].ai[1] = num24;
                     Main.npc[num23].CopyInteractions(this);
                     Main.npc[num24].ai[0] = num23;
                     NetMessage.SendData(23, -1, -1, null, num23);
                     num24 = num23;
                 }
             }
             if (type == 621 && ai[0] == 0f)
             {
                 ai[3] = whoAmI;
                 realLife = whoAmI;
                 int num28 = 0;
                 int num29 = whoAmI;
                 int num30 = 16;
                 for (int num31 = 0; num31 < num30; num31++)
                 {
                     int num32 = 622;
                     if (num31 == num30 - 1)
                     {
                         num32 = 623;
                     }
                     num28 = NewNPC(GetSpawnSourceForNPCFromNPCAI(), (int)(position.X + (float)(width / 2)), (int)(position.Y + (float)height), num32, whoAmI);
                     Main.npc[num28].ai[3] = whoAmI;
                     Main.npc[num28].realLife = whoAmI;
                     Main.npc[num28].ai[1] = num29;
                     Main.npc[num28].CopyInteractions(this);
                     Main.npc[num29].ai[0] = num28;
                     NetMessage.SendData(23, -1, -1, null, num28);
                     num29 = num28;
                 }
             }
             else if ((type == 7 || type == 8 || type == 10 || type == 11 || type == 13 || type == 14 || type == 39 || type == 40 || type == 95 || type == 96 || type == 98 || type == 99 || type == 117 || type == 118) && ai[0] == 0f)
             {
                 if (type == 7 || type == 10 || type == 13 || type == 39 || type == 95 || type == 98 || type == 117)
                 {
                     if (type < 13 || type > 15)
                     {
                         ai[3] = whoAmI;
                         realLife = whoAmI;
                     }
                     ai[2] = Main.rand.Next(8, 13);
                     if (type == 10)
                     {
                         ai[2] = Main.rand.Next(4, 7);
                     }
                     if (type == 13)
                     {
                         ai[2] = GetEaterOfWorldsSegmentsCount();
                     }
                     if (type == 39)
                     {
                         ai[2] = Main.rand.Next(14, 23);
                         if (Main.getGoodWorld)
{
                             ai[2] += 3f;
                             if (Main.remixWorld)
{
                                 ai[2] += 4f;
                             }
                         }
                     }
                     if (type == 95)
                     {
                         ai[2] = Main.rand.Next(6, 12);
                     }
                     if (type == 98)
                     {
                         ai[2] = Main.rand.Next(20, 26);
                     }
                     if (type == 117)
                     {
                         ai[2] = Main.rand.Next(3, 6);
                     }
                     if (type == 7 && Main.remixWorld)
                     {
                         ai[2] *= 2f;
                     }
                     ai[0] = NewNPC(GetSpawnSourceForNPCFromNPCAI(), (int)(position.X + (float)(width / 2)), (int)(position.Y + (float)height), type + 1, whoAmI);
                     Main.npc[(int)ai[0]].CopyInteractions(this);
                 }
                 else if ((type == 8 || type == 11 || type == 14 || type == 40 || type == 96 || type == 99 || type == 118) && ai[2] > 0f)
                 {
                     ai[0] = NewNPC(GetSpawnSourceForNPCFromNPCAI(), (int)(position.X + (float)(width / 2)), (int)(position.Y + (float)height), type, whoAmI);
                     Main.npc[(int)ai[0]].CopyInteractions(this);
                 }
                 else
                 {
                     ai[0] = NewNPC(GetSpawnSourceForNPCFromNPCAI(), (int)(position.X + (float)(width / 2)), (int)(position.Y + (float)height), type + 1, whoAmI);
                     Main.npc[(int)ai[0]].CopyInteractions(this);
                 }
                 if (type < 13 || type > 15)
                 {
                     Main.npc[(int)ai[0]].ai[3] = ai[3];
                     Main.npc[(int)ai[0]].realLife = realLife;
                 }
                 Main.npc[(int)ai[0]].ai[1] = whoAmI;
                 Main.npc[(int)ai[0]].ai[2] = ai[2] - 1f;
                 netUpdate = true;
             }
             if (type == 412 && ai[0] == 0f)
             {
                 ai[3] = whoAmI;
                 realLife = whoAmI;
                 int num33 = 0;
                 int num34 = whoAmI;
                 int num35 = 30;
                 for (int num36 = 0; num36 < num35; num36++)
                 {
                     int num37 = 413;
                     if (num36 == num35 - 1)
                     {
                         num37 = 414;
                     }
                     num33 = NewNPC(GetSpawnSourceForNPCFromNPCAI(), (int)(position.X + (float)(width / 2)), (int)(position.Y + (float)height), num37, whoAmI);
                     Main.npc[num33].ai[3] = whoAmI;
                     Main.npc[num33].realLife = whoAmI;
                     Main.npc[num33].ai[1] = num34;
                     Main.npc[num33].CopyInteractions(this);
                     Main.npc[num34].ai[0] = num33;
                     NetMessage.SendData(23, -1, -1, null, num33);
                     num34 = num33;
                 }
             }
             switch (type)
             {
             case 8:
             case 9:
             case 11:
             case 12:
             case 40:
             case 41:
             case 88:
             case 89:
             case 90:
             case 91:
             case 92:
             case 96:
             case 97:
             case 99:
             case 100:
             case 118:
             case 119:
             case 413:
             case 414:
             case 455:
             case 456:
             case 457:
             case 458:
             case 459:
             case 511:
             case 512:
             case 514:
             case 515:
             case 622:
             case 623:
                 if (!Main.npc[(int)ai[1]].active || Main.npc[(int)ai[1]].aiStyle != aiStyle)
                 {
                     life = 0;
                     HitEffect();
                     checkDead();
                     active = false;
                     NetMessage.SendData(28, -1, -1, null, whoAmI, -1f);
                     return;
                 }
                 break;
             }
             switch (type)
             {
             case 7:
             case 8:
             case 10:
             case 11:
             case 39:
             case 40:
             case 87:
             case 88:
             case 89:
             case 90:
             case 91:
             case 95:
             case 96:
             case 98:
             case 99:
             case 117:
             case 118:
             case 412:
             case 413:
             case 454:
             case 455:
             case 456:
             case 457:
             case 458:
             case 510:
             case 511:
             case 513:
             case 514:
             case 621:
             case 622:
                 if (!Main.npc[(int)ai[0]].active || Main.npc[(int)ai[0]].aiStyle != aiStyle)
                 {
                     life = 0;
                     HitEffect();
                     checkDead();
                     active = false;
                     NetMessage.SendData(28, -1, -1, null, whoAmI, -1f);
                     return;
                 }
                 break;
             }
             if (type == 13 || type == 14 || type == 15)
             {
                 if (!Main.npc[(int)ai[1]].active && !Main.npc[(int)ai[0]].active)
                 {
                     life = 0;
                     HitEffect();
                     checkDead();
                     active = false;
                     NetMessage.SendData(28, -1, -1, null, whoAmI, -1f);
                     return;
                 }
                 if (type == 13 && !Main.npc[(int)ai[0]].active)
                 {
                     life = 0;
                     HitEffect();
                     checkDead();
                     active = false;
                     NetMessage.SendData(28, -1, -1, null, whoAmI, -1f);
                     return;
                 }
                 if (type == 15 && !Main.npc[(int)ai[1]].active)
                 {
                     life = 0;
                     HitEffect();
                     checkDead();
                     active = false;
                     NetMessage.SendData(28, -1, -1, null, whoAmI, -1f);
                     return;
                 }
                 if (type == 14 && (!Main.npc[(int)ai[1]].active || Main.npc[(int)ai[1]].aiStyle != aiStyle))
                 {
                     type = 13;
                     int num38 = whoAmI;
                     float num39 = (float)life / (float)lifeMax;
                     float num40 = ai[0];
                     SetDefaultsKeepPlayerInteraction(type);
                     life = (int)((float)lifeMax * num39);
                     ai[0] = num40;
                     TargetClosest();
                     netUpdate = true;
                     whoAmI = num38;
                     alpha = 0;
                 }
                 if (type == 14 && (!Main.npc[(int)ai[0]].active || Main.npc[(int)ai[0]].aiStyle != aiStyle))
                 {
                     type = 15;
                     int num41 = whoAmI;
                     float num42 = (float)life / (float)lifeMax;
                     float num43 = ai[1];
                     SetDefaultsKeepPlayerInteraction(type);
                     life = (int)((float)lifeMax * num42);
                     ai[1] = num43;
                     TargetClosest();
                     netUpdate = true;
                     whoAmI = num41;
                     alpha = 0;
                 }
             }
             if (!active && Main.netMode == 2)
             {
                 NetMessage.SendData(28, -1, -1, null, whoAmI, -1f);
             }
         }
         int num44 = (int)(position.X / 16f) - 1;
         int num45 = (int)((position.X + (float)width) / 16f) + 2;
         int num46 = (int)(position.Y / 16f) - 1;
         int num47 = (int)((position.Y + (float)height) / 16f) + 2;
         if (num44 < 0)
         {
             num44 = 0;
         }
         if (num45 > Main.maxTilesX)
         {
             num45 = Main.maxTilesX;
         }
         if (num46 < 0)
         {
             num46 = 0;
         }
         if (num47 > Main.maxTilesY)
         {
             num47 = Main.maxTilesY;
         }
         bool flag2 = false;
         if (type >= 87 && type <= 92)
         {
             flag2 = true;
         }
         if (type >= 454 && type <= 459)
         {
             flag2 = true;
         }
         if (type >= 621 && type <= 623)
         {
             flag2 = true;
         }
         if (type >= 412 && type <= 414)
         {
             flag2 = true;
         }
         if (type == 402)
         {
             flag2 = true;
         }
         if (!flag2)
         {
             Vector2 vector2 = default(Vector2);
             for (int num48 = num44; num48 < num45; num48++)
             {
                 for (int num49 = num46; num49 < num47; num49++)
                 {
                     if (Main.tile[num48, num49] == null || ((!Main.tile[num48, num49].nactive() || (!Main.tileSolid[Main.tile[num48, num49].type] && (!Main.tileSolidTop[Main.tile[num48, num49].type] || Main.tile[num48, num49].frameY != 0))) && Main.tile[num48, num49].liquid <= 64))
                     {
                         continue;
                     }
                     vector2.X = num48 * 16;
                     vector2.Y = num49 * 16;
                     if (position.X + (float)width > vector2.X && position.X < vector2.X + 16f && position.Y + (float)height > vector2.Y && position.Y < vector2.Y + 16f)
                     {
                         flag2 = true;
                         if (Main.rand.Next(100) == 0 && type != 117 && Main.tile[num48, num49].nactive() && Main.tileSolid[Main.tile[num48, num49].type])
{
                             WorldGen.KillTile(num48, num49, fail: true, effectOnly: true);
                         }
                     }
                 }
             }
         }
         if (!flag2 && (type == 7 || type == 10 || type == 13 || type == 39 || type == 95 || type == 98 || type == 117 || type == 375 || type == 454 || type == 510 || type == 513 || type == 621))
         {
             Rectangle rectangle = new Rectangle((int)position.X, (int)position.Y, width, height);
             int num50 = 1000;
             bool flag3 = true;
             for (int num51 = 0; num51 < 255; num51++)
             {
                 if (Main.player[num51].active)
                 {
                     Rectangle rectangle2 = new Rectangle((int)Main.player[num51].position.X - num50, (int)Main.player[num51].position.Y - num50, num50 * 2, num50 * 2);
                     if (rectangle.Intersects(rectangle2))
                     {
                         flag3 = false;
                         break;
                     }
                 }
             }
             if (flag3)
             {
                 flag2 = true;
             }
         }
         if ((type >= 87 && type <= 92) || (type >= 454 && type <= 459) || (type >= 621 && type <= 623))
         {
             if (velocity.X < 0f)
             {
                 spriteDirection = 1;
             }
             else if (velocity.X > 0f)
             {
                 spriteDirection = -1;
             }
         }
         if (type == 414)
         {
             if (justHit)
             {
                 localAI[3] = 3f;
             }
             if (localAI[2] > 0f)
             {
                 localAI[2] -= 16f;
                 if (localAI[2] == 0f)
                 {
                     localAI[2] = -128f;
                 }
             }
             else if (localAI[2] < 0f)
             {
                 localAI[2] += 16f;
             }
             else if (localAI[3] > 0f)
             {
                 localAI[2] = 128f;
                 localAI[3] -= 1f;
             }
         }
         if (type == 412)
         {
             position += netOffset;
             Vector2 vector3 = base.Center + (rotation - (float)Math.PI / 2f).ToRotationVector2() * 8f;
             Vector2 vector4 = rotation.ToRotationVector2() * 16f;
             Dust obj = Main.dust[Dust.NewDust(vector3 + vector4, 0, 0, 6, velocity.X, velocity.Y, 100, Color.Transparent, 1f + Main.rand.NextFloat() * 3f)];
             obj.noGravity = true;
             obj.noLight = true;
             obj.position -= new Vector2(4f);
             obj.fadeIn = 1f;
             obj.velocity = Vector2.Zero;
             Dust obj2 = Main.dust[Dust.NewDust(vector3 - vector4, 0, 0, 6, velocity.X, velocity.Y, 100, Color.Transparent, 1f + Main.rand.NextFloat() * 3f)];
             obj2.noGravity = true;
             obj2.noLight = true;
             obj2.position -= new Vector2(4f);
             obj2.fadeIn = 1f;
             obj2.velocity = Vector2.Zero;
             position -= netOffset;
         }
         float num52 = 8f;
         float num53 = 0.07f;
         if (type == 95)
         {
             num52 = 5.5f;
             num53 = 0.045f;
         }
         if (type == 10)
         {
             num52 = 6f;
             num53 = 0.05f;
         }
         if (type == 513)
         {
             num52 = 7f;
             num53 = 0.1f;
         }
         if (type == 7)
         {
             num52 = 9f;
             num53 = 0.1f;
         }
         if (type == 13)
         {
             num52 = 10f;
             num53 = 0.07f;
             if (Main.expertMode)
             {
                 num52 = 12f;
                 num53 = 0.15f;
             }
             if (Main.getGoodWorld)
             {
                 num52 += 4f;
                 num53 += 0.05f;
             }
         }
         if (type == 510)
         {
             if (!Main.player[target].dead && Main.player[target].ZoneSandstorm)
             {
                 num52 = 16f;
                 num53 = 0.35f;
             }
             else
             {
                 num52 = 10f;
                 num53 = 0.25f;
             }
         }
         if (type == 87)
         {
             num52 = 11f;
             num53 = 0.25f;
         }
         if (type == 621)
         {
             num52 = 15f;
             num53 = 0.45f;
         }
         if (type == 375)
         {
             num52 = 6f;
             num53 = 0.15f;
         }
         if (type == 454)
         {
             num52 = 20f;
             num53 = 0.55f;
         }
         if (type == 402)
         {
             num52 = 9f;
             num53 = 0.3f;
         }
         if (type == 117 && Main.wofNPCIndex >= 0)
         {
             float num54 = (float)Main.npc[Main.wofNPCIndex].life / (float)Main.npc[Main.wofNPCIndex].lifeMax;
             if ((double)num54 < 0.5)
             {
                 num52 += 1f;
                 num53 += 0.1f;
             }
             if ((double)num54 < 0.25)
             {
                 num52 += 1f;
                 num53 += 0.1f;
             }
             if ((double)num54 < 0.1)
             {
                 num52 += 2f;
                 num53 += 0.1f;
             }
         }
         if (type == 39)
         {
             num52 = 9f;
             num53 = 0.1f;
             if (Main.getGoodWorld)
             {
                 num52 = 10f;
                 num53 = 0.12f;
             }
         }
         Vector2 vector5 = new Vector2(position.X + (float)width * 0.5f, position.Y + (float)height * 0.5f);
         float num55 = Main.player[target].position.X + (float)(Main.player[target].width / 2);
         float num56 = Main.player[target].position.Y + (float)(Main.player[target].height / 2);
         if (type == 412)
         {
             num52 = 10f;
             num53 = 0.3f;
             int num57 = -1;
             int num58 = (int)(Main.player[target].Center.X / 16f);
             int num59 = (int)(Main.player[target].Center.Y / 16f);
             for (int num60 = num58 - 2; num60 <= num58 + 2; num60++)
             {
                 for (int num61 = num59; num61 <= num59 + 15; num61++)
                 {
                     if (WorldGen.SolidTile2(num60, num61))
                     {
                         num57 = num61;
                         break;
                     }
                 }
                 if (num57 > 0)
                 {
                     break;
                 }
             }
             if (num57 > 0)
             {
                 num57 *= 16;
                 float num62 = num57 - 800;
                 if (Main.player[target].position.Y > num62)
                 {
                     num56 = num62;
                     if (Math.Abs(base.Center.X - Main.player[target].Center.X) < 500f)
                     {
                         num55 = ((!(velocity.X > 0f)) ? (Main.player[target].Center.X - 600f) : (Main.player[target].Center.X + 600f));
                     }
                 }
             }
             else
             {
                 num52 = 14f;
                 num53 = 0.5f;
             }
             float num63 = num52 * 1.3f;
             float num64 = num52 * 0.7f;
             float num65 = velocity.Length();
             if (num65 > 0f)
             {
                 if (num65 > num63)
                 {
                     velocity.Normalize();
                     velocity *= num63;
                 }
                 else if (num65 < num64)
                 {
                     velocity.Normalize();
                     velocity *= num64;
                 }
             }
             if (num57 > 0)
             {
                 for (int num66 = 0; num66 < 200; num66++)
                 {
                     if (Main.npc[num66].active && Main.npc[num66].type == type && num66 != whoAmI)
                     {
                         Vector2 vector6 = Main.npc[num66].Center - base.Center;
                         if (vector6.Length() < 400f)
{
                             vector6.Normalize();
                             vector6 *= 1000f;
                             num55 -= vector6.X;
                             num56 -= vector6.Y;
                         }
                     }
                 }
             }
             else
             {
                 for (int num67 = 0; num67 < 200; num67++)
                 {
                     if (Main.npc[num67].active && Main.npc[num67].type == type && num67 != whoAmI)
                     {
                         Vector2 vector7 = Main.npc[num67].Center - base.Center;
                         if (vector7.Length() < 60f)
{
                             vector7.Normalize();
                             vector7 *= 200f;
                             num55 -= vector7.X;
                             num56 -= vector7.Y;
                         }
                     }
                 }
             }
         }
         num55 = (int)(num55 / 16f) * 16;
         num56 = (int)(num56 / 16f) * 16;
         vector5.X = (int)(vector5.X / 16f) * 16;
         vector5.Y = (int)(vector5.Y / 16f) * 16;
         num55 -= vector5.X;
         num56 -= vector5.Y;
         if (type == 375)
         {
             num55 *= -1f;
             num56 *= -1f;
         }
         float num68 = (float)Math.Sqrt(num55 * num55 + num56 * num56);
         if (ai[1] > 0f && ai[1] < (float)Main.npc.Length)
         {
             try
             {
                 vector5 = new Vector2(position.X + (float)width * 0.5f, position.Y + (float)height * 0.5f);
                 num55 = Main.npc[(int)ai[1]].position.X + (float)(Main.npc[(int)ai[1]].width / 2) - vector5.X;
                 num56 = Main.npc[(int)ai[1]].position.Y + (float)(Main.npc[(int)ai[1]].height / 2) - vector5.Y;
             }
             catch
             {
             }
             rotation = (float)Math.Atan2(num56, num55) + 1.57f;
             num68 = (float)Math.Sqrt(num55 * num55 + num56 * num56);
             int num69 = width;
             if (type >= 87 && type <= 92)
             {
                 num69 = 42;
             }
             if (type >= 454 && type <= 459)
             {
                 num69 = 36;
             }
             if (type >= 13 && type <= 15)
             {
                 num69 = (int)((float)num69 * scale);
             }
             if (type >= 513 && type <= 515)
             {
                 num69 -= 6;
             }
             if (type >= 412 && type <= 414)
             {
                 num69 += 6;
             }
             if (type >= 621 && type <= 623)
             {
                 num69 = 24;
             }
             if (Main.getGoodWorld && type >= 13 && type <= 15)
             {
                 num69 = 62;
             }
             num68 = (num68 - (float)num69) / num68;
             num55 *= num68;
             num56 *= num68;
             velocity = Vector2.Zero;
             position.X += num55;
             position.Y += num56;
             if (type >= 87 && type <= 92)
             {
                 if (num55 < 0f)
                 {
                     spriteDirection = 1;
                 }
                 else if (num55 > 0f)
                 {
                     spriteDirection = -1;
                 }
             }
             if (type >= 454 && type <= 459)
             {
                 if (num55 < 0f)
                 {
                     spriteDirection = 1;
                 }
                 else if (num55 > 0f)
                 {
                     spriteDirection = -1;
                 }
             }
             if (type >= 621 && type <= 623)
             {
                 if (num55 < 0f)
                 {
                     spriteDirection = 1;
                 }
                 else if (num55 > 0f)
                 {
                     spriteDirection = -1;
                 }
             }
         }
         else
         {
             if (!flag2)
             {
                 TargetClosest();
                 if (type == 39 && velocity.Y < 0f)
                 {
                     velocity.Y += 0.08f;
                 }
                 else
                 {
                     velocity.Y += 0.11f;
                 }
                 if (velocity.Y > num52)
                 {
                     velocity.Y = num52;
                 }
                 if ((double)(Math.Abs(velocity.X) + Math.Abs(velocity.Y)) < (double)num52 * 0.4)
                 {
                     if (velocity.X < 0f)
                     {
                         velocity.X -= num53 * 1.1f;
                     }
                     else
                     {
                         velocity.X += num53 * 1.1f;
                     }
                 }
                 else if (velocity.Y == num52)
                 {
                     if (velocity.X < num55)
                     {
                         velocity.X += num53;
                     }
                     else if (velocity.X > num55)
                     {
                         velocity.X -= num53;
                     }
                 }
                 else if (velocity.Y > 4f)
                 {
                     if (velocity.X < 0f)
                     {
                         velocity.X += num53 * 0.9f;
                     }
                     else
                     {
                         velocity.X -= num53 * 0.9f;
                     }
                 }
             }
             else
             {
                 if (type != 621 && type != 87 && type != 117 && type != 454 && type != 412 && soundDelay == 0)
                 {
                     float num70 = num68 / 40f;
                     if (num70 < 10f)
                     {
                         num70 = 10f;
                     }
                     if (num70 > 20f)
                     {
                         num70 = 20f;
                     }
                     soundDelay = (int)num70;
                     SoundEngine.PlaySound(15, (int)position.X, (int)position.Y);
                 }
                 num68 = (float)Math.Sqrt(num55 * num55 + num56 * num56);
                 float num71 = Math.Abs(num55);
                 float num72 = Math.Abs(num56);
                 float num73 = num52 / num68;
                 num55 *= num73;
                 num56 *= num73;
                 bool flag4 = false;
                 if ((type == 7 || type == 13) && ((!Main.player[target].ZoneCorrupt && !Main.player[target].ZoneCrimson) || Main.player[target].dead))
                 {
                     flag4 = true;
                 }
                 if ((type == 513 && (double)Main.player[target].position.Y < Main.worldSurface * 16.0 && !Main.player[target].ZoneSandstorm && !Main.player[target].ZoneUndergroundDesert) || Main.player[target].dead)
                 {
                     flag4 = true;
                 }
                 if ((type == 510 && (double)Main.player[target].position.Y < Main.worldSurface * 16.0 && !Main.player[target].ZoneSandstorm && !Main.player[target].ZoneUndergroundDesert) || Main.player[target].dead)
                 {
                     flag4 = true;
                 }
                 if (flag4)
                 {
                     bool flag5 = true;
                     for (int num74 = 0; num74 < 255; num74++)
                     {
                         if (Main.player[num74].active && !Main.player[num74].dead && Main.player[num74].ZoneCorrupt)
{
                             flag5 = false;
                         }
                     }
                     if (flag5)
                     {
                         if (Main.netMode != 1 && (double)(position.Y / 16f) > (Main.rockLayer + (double)Main.maxTilesY) / 2.0)
{
                             active = false;
                             int num75 = (int)ai[0];
                             while (num75 > 0 && num75 < 200 && Main.npc[num75].active && Main.npc[num75].aiStyle == aiStyle)
{
                                 int num76 = (int)Main.npc[num75].ai[0];
                                 Main.npc[num75].active = false;
                                 life = 0;
                                 if (Main.netMode == 2)
{
                                     NetMessage.SendData(23, -1, -1, null, num75);
                                 }
                                 num75 = num76;
                             }
                             if (Main.netMode == 2)
{
                                 NetMessage.SendData(23, -1, -1, null, whoAmI);
                             }
                         }
                         num55 = 0f;
                         num56 = num52;
                     }
                 }
                 bool flag6 = false;
                 if (type == 87)
                 {
                     if (((velocity.X > 0f && num55 < 0f) || (velocity.X < 0f && num55 > 0f) || (velocity.Y > 0f && num56 < 0f) || (velocity.Y < 0f && num56 > 0f)) && Math.Abs(velocity.X) + Math.Abs(velocity.Y) > num53 / 2f && num68 < 300f)
                     {
                         flag6 = true;
                         if (Math.Abs(velocity.X) + Math.Abs(velocity.Y) < num52)
{
                             velocity *= 1.1f;
                         }
                     }
                     if (position.Y > Main.player[target].position.Y || (double)(Main.player[target].position.Y / 16f) > Main.worldSurface || Main.player[target].dead)
                     {
                         flag6 = true;
                         if (Math.Abs(velocity.X) < num52 / 2f)
{
                             if (velocity.X == 0f)
{
                                 velocity.X -= direction;
                             }
                             velocity.X *= 1.1f;
                         }
                         else if (velocity.Y > 0f - num52)
{
                             velocity.Y -= num53;
                         }
                     }
                 }
                 if (type == 454 || type == 621)
                 {
                     float num77 = 300f;
                     if (type == 621)
                     {
                         num77 = 120f;
                     }
                     if (((velocity.X > 0f && num55 < 0f) || (velocity.X < 0f && num55 > 0f) || (velocity.Y > 0f && num56 < 0f) || (velocity.Y < 0f && num56 > 0f)) && Math.Abs(velocity.X) + Math.Abs(velocity.Y) > num53 / 2f && num68 < num77)
                     {
                         flag6 = true;
                         if (Math.Abs(velocity.X) + Math.Abs(velocity.Y) < num52)
{
                             velocity *= 1.1f;
                         }
                     }
                     if (position.Y > Main.player[target].position.Y || Main.player[target].dead)
                     {
                         flag6 = true;
                         if (Math.Abs(velocity.X) < num52 / 2f)
{
                             if (velocity.X == 0f)
{
                                 velocity.X -= direction;
                             }
                             velocity.X *= 1.1f;
                         }
                         else if (velocity.Y > 0f - num52)
{
                             velocity.Y -= num53;
                         }
                     }
                 }
                 if (!flag6)
                 {
                     if ((velocity.X > 0f && num55 > 0f) || (velocity.X < 0f && num55 < 0f) || (velocity.Y > 0f && num56 > 0f) || (velocity.Y < 0f && num56 < 0f))
                     {
                         if (velocity.X < num55)
{
                             velocity.X += num53;
                         }
                         else if (velocity.X > num55)
{
                             velocity.X -= num53;
                         }
                         if (velocity.Y < num56)
{
                             velocity.Y += num53;
                         }
                         else if (velocity.Y > num56)
{
                             velocity.Y -= num53;
                         }
                         if ((double)Math.Abs(num56) < (double)num52 * 0.2 && ((velocity.X > 0f && num55 < 0f) || (velocity.X < 0f && num55 > 0f)))
{
                             if (velocity.Y > 0f)
{
                                 velocity.Y += num53 * 2f;
                             }
                             else
{
                                 velocity.Y -= num53 * 2f;
                             }
                         }
                         if ((double)Math.Abs(num55) < (double)num52 * 0.2 && ((velocity.Y > 0f && num56 < 0f) || (velocity.Y < 0f && num56 > 0f)))
{
                             if (velocity.X > 0f)
{
                                 velocity.X += num53 * 2f;
                             }
                             else
{
                                 velocity.X -= num53 * 2f;
                             }
                         }
                     }
                     else if (num71 > num72)
                     {
                         if (velocity.X < num55)
{
                             velocity.X += num53 * 1.1f;
                         }
                         else if (velocity.X > num55)
{
                             velocity.X -= num53 * 1.1f;
                         }
                         if ((double)(Math.Abs(velocity.X) + Math.Abs(velocity.Y)) < (double)num52 * 0.5)
{
                             if (velocity.Y > 0f)
{
                                 velocity.Y += num53;
                             }
                             else
{
                                 velocity.Y -= num53;
                             }
                         }
                     }
                     else
                     {
                         if (velocity.Y < num56)
{
                             velocity.Y += num53 * 1.1f;
                         }
                         else if (velocity.Y > num56)
{
                             velocity.Y -= num53 * 1.1f;
                         }
                         if ((double)(Math.Abs(velocity.X) + Math.Abs(velocity.Y)) < (double)num52 * 0.5)
{
                             if (velocity.X > 0f)
{
                                 velocity.X += num53;
                             }
                             else
{
                                 velocity.X -= num53;
                             }
                         }
                     }
                 }
             }
             rotation = (float)Math.Atan2(velocity.Y, velocity.X) + 1.57f;
             if (type == 7 || type == 10 || type == 13 || type == 39 || type == 95 || type == 98 || type == 117 || type == 510 || type == 513 || type == 621)
             {
                 if (flag2)
                 {
                     if (localAI[0] != 1f)
                     {
                         netUpdate = true;
                     }
                     localAI[0] = 1f;
                 }
                 else
                 {
                     if (localAI[0] != 0f)
                     {
                         netUpdate = true;
                     }
                     localAI[0] = 0f;
                 }
                 if (((velocity.X > 0f && oldVelocity.X < 0f) || (velocity.X < 0f && oldVelocity.X > 0f) || (velocity.Y > 0f && oldVelocity.Y < 0f) || (velocity.Y < 0f && oldVelocity.Y > 0f)) && !justHit)
                 {
                     netUpdate = true;
                 }
             }
             if (type == 454)
             {
                 float num78 = Vector2.Distance(Main.player[target].Center, base.Center);
                 int num79 = 0;
                 if (Vector2.Normalize(Main.player[target].Center - base.Center).ToRotation().AngleTowards(velocity.ToRotation(), (float)Math.PI / 2f) == velocity.ToRotation() && num78 < 350f)
                 {
                     num79 = 4;
                 }
                 if ((double)num79 > frameCounter)
                 {
                     frameCounter += 1.0;
                 }
                 if ((double)num79 < frameCounter)
                 {
                     frameCounter -= 1.0;
                 }
                 if (frameCounter < 0.0)
                 {
                     frameCounter = 0.0;
                 }
                 if (frameCounter > 4.0)
                 {
                     frameCounter = 4.0;
                 }
             }
         }
         if (type < 13 || type > 15 || (type != 13 && (type == 13 || Main.npc[(int)ai[1]].alpha >= 85)))
         {
             return;
         }
         if (alpha > 0 && life > 0)
         {
             for (int num80 = 0; num80 < 2; num80++)
             {
                 int num81 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 14, 0f, 0f, 100, default(Color), 2f);
                 Main.dust[num81].noGravity = true;
                 Main.dust[num81].noLight = true;
             }
         }
         if ((position - oldPosition).Length() > 2f)
         {
             alpha -= 42;
             if (alpha < 0)
             {
                 alpha = 0;
             }
         }
     }
References Entity.active, ai, aiStyle, alpha, Collision.CanHitLine(), Entity.Center, checkDead(), Color, CopyInteractions(), Main.dayTime, Player.dead, Entity.direction, dontTakeDamage, Main.dust, EncourageDespawn(), Main.expertMode, Dust.fadeIn, frameCounter, Tile.frameY, GetEaterOfWorldsSegmentsCount(), Main.getGoodWorld, GetSpawnSourceForNPCFromNPCAI(), Entity.height, HitEffect(), WorldGen.InWorld(), SoundID.Item119, justHit, WorldGen.KillTile(), life, lifeMax, Tile.liquid, localAI, Main.maxTilesX, Main.maxTilesY, Tile.nactive(), Main.netMode, netOffset, netUpdate, Dust.NewDust(), NewNPC(), UnifiedRandom.Next(), Dust.noGravity, Dust.noLight, Main.npc, SoundID.NPCDeath13, Entity.oldPosition, Entity.oldVelocity, Main.player, SoundEngine.PlaySound(), Dust.position, Entity.position, Main.rand, realLife, Utils.Remap(), Main.remixWorld, Main.rockLayer, rotation, Dust.scale, scale, NetMessage.SendData(), SetDefaultsKeepPlayerInteraction(), WorldGen.SolidTile2(), soundDelay, SpawnStardustMark_StardustWorm(), spriteDirection, target, TargetClosest(), Main.tile, Main.tileSolid, Main.tileSolidTop, type, Tile.type, Dust.velocity, Entity.velocity, Tile.wall, Entity.whoAmI, Entity.width, Main.wofNPCIndex, Main.worldSurface, Player.ZoneCorrupt, Player.ZoneCrimson, Player.ZoneSandstorm, and Player.ZoneUndergroundDesert.
Referenced by AI().